### PR TITLE
Fix GDExtension Variant type conversion

### LINKED ISSUE #907: Variables with wrong types become 0 instead of being cast correctly
Say I have the following function in a GDExtension project:

```cpp
void Example::print_variables(double double_val, int int_val) {
	UtilityFunctions::print(double_val, " and ", int_val);
}
```

As expected, calling `example.print_variables(123.0, 321)` from GDScript prints "123 and 321" to the console.

However, when the types do not match (e.g. mixing up float and int), they are not properly cast automatically: the debugger does print a warning like `Narrowing conversion (float is converted to int and loses precision)`, but the output is not still "123 and 321" as I would expect. Rather, the variable with the false type is simply 0.

Example: calling `example.print_variables(123, 321)` (first argument is now int rather than float) produces "0 and 321" in the console.

This type of bug is really hard to track down in a reasonably complex project, so I would expect either a full error if the types don't match, or a better automatic conversion.

Here's a minimal reproduction (just a quick modification of the example project from this repo): [type-cast-repro.zip](https://github.com/godotengine/godot-cpp/files/9921935/type-cast-repro.zip) running it in Godot shows that, as described above, parameters with wrong types simply become 0. This is the case even if Godot's optional static typing is not used (`=` rather than `:=`).

Tested in Godot 4.0 Beta 3

### LINKED ISSUE #1106: Sending int from GDScript to float c++ function receives 0 (zero)
I have c++ function `ClassDB::bind_method(D_METHOD("ReceivedDamage","damage"), &Person::ReceivedDamage);` which is `ReceivedDamage(float damage);`
From `gdscript` I call it with `ReceivedDamage(10)` and in c++ 0 is received. Sending `ReceivedDamage(10.0)` works fine

### LINKED ISSUE #1132: GDExtension Vector*i to Vector* conversion results in wrong values
### Godot version

4.0.3

### godot-cpp version

4.0.3

### System information

Windows 11

### Issue description

When you declare a function that takes Vector2i as an argument it works correctly if you pass Vector2i to the function, but the moment you pass Vector2 instead it gives some crazy high numbers (likely a conversion problem).

Basically calling `do_stuff_with_vec2i(Vecotr2i(1,1))` works fine but `do_stuff_with_vec2i(Vecotr2(1,1))` reads `Vector2(1,1)` as `Vector2i(213213213,213213213)`

### Steps to reproduce

If you write a simple function that takes Vector2i as an argument
```c++
Vector3i vec2i_vec3i(const Vector2i &vec, int32_t z)
{
    UtilityFunctions::print(vec);
    return Vector3i(vec.x, vec.y, z);
}
```
Everything is fine if you for example call it via `vec2i_vec3i(Vector2i(1,1), 1)`, but calling `vec2i_vec3i(Vector2(1,1), 1)` results in very high x and y values in vector being printed

### Minimal reproduction project

Example minimalistic source code to reproduce the above bug
[src.zip](https://github.com/godotengine/godot-cpp/files/11646326/src.zip)

### LINKED ISSUE #75757: [GDExtension] Cannot convert `Variant` to other types correctly
### Godot version

4.0.2.stable.official.7a0977ce2

### System information

Linux

### Issue description

The following code fails with godot-cpp
```c++
Variant variant_int = 1234;
double double_value = variant_int;
UtilityFunctions::print(double_value); // prints 0. it must be 1234

Variant double_variant = 6789.0;
int int_value = double_variant;
UtilityFunctions::print(int_value); // prints 0. it must be 1234

Variant variant_string = "12345";
StringName string_name = variant_string;
UtilityFunctions::print(string_name); // Segmentation Fault!
```

When godot-cpp converts a `Variant` to another type, it calls `type_from_variant_constructor` without checking its type. It only does  `reinterpret_cast` and does no type conversion.
I think this issue can be solved by implementing type conversion on the godot-cpp side or by making `type_from_variant_constructor` do the type conversion.

### Steps to reproduce

Unzip the minimal reproduction project and run `scons` to build the GDExtension.

### Minimal reproduction project

[variant-conversion-issue.zip](https://github.com/godotengine/godot/files/11171860/variant-conversion-issue.zip)

### PR DESCRIPTION
**Pull request by Pylgos**
Fixes https://github.com/godotengine/godot/issues/75757
Fixes https://github.com/godotengine/godot-cpp/issues/1132
Fixes https://github.com/godotengine/godot-cpp/issues/907
Fixes https://github.com/godotengine/godot-cpp/issues/1106

With this PR, `VariantTypeConstructor<T>::type_from_variant` now does the type conversion from `Variant` to `T`. Previously, it only `reinterpret_cast` the variant data by `VariantInternalAccessor<T>::get`.

### CODE REVIEW

**Comment by dsnopek** [comment]
To check if I'm understanding this correctly:

Presently, `VariantTypeConstructor<T>::type_from_variant()` will assume that the Variant internally already has a value that is type `T`. When it isn't actually type `T`, then weird things happen (ala #75757).

With this PR, rather than using `VariantInternalAccessor<T>::get()`, it'll rely on the `operator T()` method on `Variant` to get the value, possibly converting it to `T` if it isn't already internally `T`.

Do I have that right?

**Review by dsnopek — APPROVED** [review]
I just tested the reproduction project on #75757 and I'm able to reproduce the issue. Using the changes in this PR fixes it!

Assuming I'm understanding the changes (as described in my previous comment), this seems good to me. :-)

However, it should still be reviewed by someone on the @godotengine/core or @godotengine/gdextension teams in case this would cause some collateral damage that I'm not aware of.

**Comment by Pylgos** [comment]
@dsnopek
Your understanding is correct. Thanks for reviewing this PR.

File: core/variant/variant_internal.h [hunk 1]
```diff
@@ -1537,7 +1537,7 @@ struct VariantTypeConstructor {
 	}
 
 	_FORCE_INLINE_ static void type_from_variant(void *p_value, void *p_variant) {
-		*((T *)p_value) = VariantInternalAccessor<T>::get(reinterpret_cast<Variant *>(p_variant));
+		*((T *)p_value) = *reinterpret_cast<Variant *>(p_variant);
```
Comment (touilleMan) [inline core/variant/variant_internal.h:1540]: Is there a reason for the C-style cast instead of reinterpret_cast everywhere ?
```c++
*reinterpret_cast<T *>p_value = *reinterpret_cast<Variant *>(p_variant);
```

Comment (dsnopek) [reply core/variant/variant_internal.h:1540]: I don't know the answer to the question :-) but because that cast isn't added by this PR, I don't think this should block this PR.

There's loads and loads of casts in GDExtension, and more than one bug has been caused by using the inappropriate cast for the situation, so perhaps we need an issue/PR that's dedicated to sorting out all the different casts?

**Comment by dsnopek** [comment]
Given my increased understanding of GDExtension since I wrote my last comment, and the additional testing of this change from #1132, I'm feeling pretty confident that this change is correct. Let's see if the CI agrees with me :-)

**Comment by akien-mga** [comment]
Would need a rebase to pass CI, last time this PR was updated godot-cpp was mid update and it's now locked to that state.

**Comment by dsnopek** [comment]
A quick explanation for why I think this change is right for future reviewers:

The functions generated by `VariantTypeConstructor<T>::type_from_variant()` are used in godot-cpp exclusively for all the `T Variant::operator T()` methods. This change makes it so that we're also calling the `T Variant::operator T()` methods on the Godot side (hence converting to the requested type), as opposed to calling `VariantInternalAccessor<T>::get()` which is used currently (and hence not converting, but just assuming the data is internally already the requested type).

Despite coming from variant_internal.h and the generic name, `VariantTypeConstructor<T>` appears to only be used by GDExtension, so this change won't have any ramifications on the Godot side.

**Review by dsnopek — APPROVED** [review]
Discussed at the GDExtension meeting, and this change seems fine from the perspective of godot-cpp. It would be good if @Bromeon and @touilleMan could confirm that this won't cause any problems in the Rust or Python bindings. Approved if they say it looks fine!

**Review by Bromeon — APPROVED** [review]
I ran our full CI on commit d7eb7108f0f172adede96f6d7c3b3c0eaee9036d.

[All green!](https://github.com/godot-rust/gdext/actions/runs/5308982427/jobs/9609153252) ✔️

**Comment by akien-mga** [comment]
Thanks!
