### PR TITLE
Fix TrackCache conflict when tracks have same name but different type

### LINKED ISSUE #43848: Bezier tracks can't fade in/out animations with AnimationTree
**Godot version:**
3,2,2

**OS/device including version:**
Windows 10 , RTX 2080 Super GLS2

**Issue description:**
OneShot node can't fade in/out animations where one animation from animationPlayer is made "normal" and second have animation based on Bezier key's 

**Steps to reproduce:**
repro in zip file

**Minimal reproduction project:**
[oneShot_issue.zip](https://github.com/godotengine/godot/files/5595277/oneShot_issue.zip)

select AnimationTree and test OneShot nodes

### LINKED ISSUE #48526: AnimationTree does not apply Call Method Track for a method in an AudioStreamPlayer script.
**Godot version:**
3.3

**OS/device including version:**
Windows 10 Home, version 20H2, build 19042.928, HP Pavilion Gaming Laptop 16-a0xxx.
nVidia GeForce GTX 1660 Ti Max-Q, driver version 457.63, any backend.

**Issue description:**
Apologies, this is a weird one.

What happens: AnimationTree state machine does not apply method calls to an AudioStreamPlayer script in a Call Method Track in an Animation when another Animation exists on the same AnimationPlayer and which is alphabetically after the current animation and has an Audio Playback Track.

(yes, all of those details are important, see steps to reproduce below)

What I expected: The Call Method Track should get called regardless of other animations' Audio Playback Tracks and alphabetical status.

**Steps to reproduce:**
Gosh, where to begin...

Setup:
1. Create a new Node2D scene with a child Sprite node to animate (optional but useful for debugging).
2. Add AudioStreamPlayer node to the scene with some audio stream imported.
3. Attach a script to the AudioStreamPlayer with a simple method that prints a debug message or something.
    ```gdscript
    extends AudioStreamPlayer
    
    func play_bloop():
	    print("hi")
	    play()
    ```
4. Add an AnimationPlayer node to the scene.
5. Create a simple animation named `default` which translates the Sprite (optional) and which has a Call Method track pointing to the AudioStreamPlayer. Optionally, make this looping.
6. Add a keyframe to the Call Method track which calls the AudioStreamPlayer's method which was added in step 3.
    image
7. Create a second animation named `zzz` which has an Audio Playback track with a keyframe that plays a stream to the AudioStreamPlayer (edit: actually, the keyframe is optional, only the track itself needs to exist).
    image
8. Add an AnimationTree node to the scene.
9. Point the AnimationTree to the AnimationPlayer, mark it as Active, and create a new state machine tree root.
10. In the tree root, add a single node to play the `default` animation.
11. Attach a script to the scene root node which starts the AnimationTree's state machine at the `default` node on ready:
    ```gdscript
    extends Node2D
    
    func _ready():
	    #$AnimationPlayer.play("default")
	    $AnimationTree["parameters/playback"].start("default")
    ```

Actual bug reproduction:
1. Play the scene. Observe that the `default` animation is playing, but the method in the Call Method track is not being called.
2. Do any one of the following:
    - Change the root node script to play the animation via the AnimationPlayer directly, without using the AnimationTree.
    - Remove the Audio Playback track from the `zzz` animation.
    - Rename the `zzz` animation to `aaa`.
3. Play the scene. Observe that the method is now being called as expected.

Additional notes:
- If there are multiple other animations which are similar to `zzz`, they must all be "fixed" in order to get the method calls to function.
- This does not affect a Call Method track which targets a node other than the AudioStreamPlayer.
- *[screaming]*

**Minimal reproduction project:**
[AudioAnimationTreeTest.zip](https://github.com/godotengine/godot/files/6440509/AudioAnimationTreeTest.zip)

### LINKED ISSUE #49431: AnimationTree doesn't blend different track types
### Godot version

3.x, 4.0.dev

### System information

MacOS X, Windows 10

### Issue description

AnimationTree doesn't blend different track types.

### Steps to reproduce

For example, there are two animations, A and B, and one object O.

- In animation A, the object O is moved using the ValueTrack.
- In animation B, the object O is moved using the BezierTrack.

If you blend Animation A and Animation B, they will not blend and only one of them will play.

#### Related issues

- https://github.com/godotengine/godot/issues/48526
- https://github.com/godotengine/godot/issues/43848

This is also the case when a Transform3DTrack is mixed in. Also, some tracks are generated by importing, while others are generated by pressing the key button in the inspector, so it is not easy to unify track types.

### Minimal reproduction project

[track_blends.zip (Godot 4.0 project file)](https://github.com/godotengine/godot/files/6618487/track_blends.zip)

### LINKED ISSUE #85365: Potential use-after-free in AnimationMixer due to dereferencing pointers to foreign objects, which may have been freed.
### Godot version

git master [1ba920f]

### System information

Arch Linux, KDE 5, Radeon RX6800XT, X11

### Issue description

The act of shooting a Plasma Gun in Liblast causes the engine to segfault not long after.
The backtrace point to AnimationMixer.
I a,m seeing a lot of errors related to animations for that weapon, but I don't expect the engine to segfault from that. 

Backtrace:

```gdb
Thread 1 "godot.linuxbsd." received signal SIGSEGV, Segmentation fault.
StringName::hash (this=<optimized out>) at ./core/string/string_name.h:136
136                             return _data->hash;
(gdb) bt
#0  StringName::hash (this=<optimized out>) at ./core/string/string_name.h:136
#1  HashMapHasherDefault::hash (p_string_name=...) at ./core/templates/hashfuncs.h:314
#2  HashMap<StringName, ClassDB::ClassInfo, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, ClassDB::ClassInfo> > >::_hash (p_key=..., this=0x55555c189540 <ClassDB::classes>)
    at ./core/templates/hash_map.h:85
#3  HashMap<StringName, ClassDB::ClassInfo, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, ClassDB::ClassInfo> > >::_lookup_pos (p_key=..., r_pos=<synthetic pointer>: <optimized out>, 
    this=0x55555c189540 <ClassDB::classes>) at ./core/templates/hash_map.h:106
#4  HashMap<StringName, ClassDB::ClassInfo, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, ClassDB::ClassInfo> > >::getptr (this=0x55555c189540 <ClassDB::classes>, p_key=...)
    at ./core/templates/hash_map.h:300
#5  0x00005555599a0773 in ClassDB::set_property (p_object=p_object@entry=0x555573eb7600, p_property=..., p_value=..., 
    r_valid=r_valid@entry=0x0) at core/object/class_db.cpp:1208
#6  0x00005555599c1dd4 in Object::set (this=this@entry=0x555573eb7600, p_name=..., p_value=..., r_valid=0x0)
    at core/object/object.cpp:257
#7  0x00005555599c39e9 in Object::set_indexed (this=this@entry=0x555573eb7600, p_names=..., p_value=..., 
    r_valid=r_valid@entry=0x0) at core/object/object.cpp:407
#8  0x0000555558320300 in AnimationMixer::_blend_apply (this=this@entry=0x555573eb7fc0)
    at scene/animation/animation_mixer.cpp:1711
#9  0x0000555558334df1 in AnimationMixer::_process_animation (this=0x555573eb7fc0, p_delta=0.017045999999999999, 
    p_update_only=<optimized out>) at scene/animation/animation_mixer.cpp:940
#10 0x0000555558377d33 in AnimationMixer::_notificationv (p_reversed=false, p_notification=25, this=0x555573eb7fc0)
    at scene/animation/animation_mixer.h:44
#11 AnimationPlayer::_notificationv (this=0x555573eb7fc0, p_notification=25, p_reversed=false)
    at scene/animation/animation_player.h:39
#12 0x00005555599bcdf0 in Object::notification (this=0x555573eb7fc0, p_notification=25, p_reversed=false)
    at core/object/object.cpp:837
#13 0x0000555557b09c91 in SceneTree::_process_group (this=0x5555601349d0, p_group=0x555560134c28, p_physics=false)
    at scene/main/scene_tree.cpp:948
#14 0x0000555557b0a372 in SceneTree::_process (this=this@entry=0x5555601349d0, p_physics=p_physics@entry=false)
    at scene/main/scene_tree.cpp:1028
#15 0x0000555557b0a952 in SceneTree::process (this=0x5555601349d0, p_time=0.017045999999999999) at scene/main/scene_tree.cpp:508
--Type <RET> for more, q to quit, c to continue without paging--c
#16 0x0000555555b21b65 in Main::iteration () at main/main.cpp:3636
#17 0x0000555555ab5531 in OS_LinuxBSD::run (this=this@entry=0x7fffffffd280) at platform/linuxbsd/os_linuxbsd.cpp:933
#18 0x0000555555aa4f58 in main (argc=<optimized out>, argv=0x7fffffffd858) at platform/linuxbsd/godot_linuxbsd.cpp:74
```

### Steps to reproduce

Clone Liblast repository:

```sh
git clone https://codeberg.org/Liblast/Liblast.git
cd Liblast
git lfs install
git pull
```
Open the game in Godot 4.2 editor to import all media (if they all fail, check LFS again)
After the game is imported, run via GDB automatically starting a game:

```sh
GODOT_BINARY="./godot.linuxbsd.editor.x86_64" # replace with your debug godot binary
gdb -ex run --args $GODOT_BINARY  --path ./Game/ --host CP1
```
Once the map loads, click on the "start now" button to avoid waiting 10 sec.
After that, the bots will do their thing and shoot their Plasma Guns causing a crash.

The crash seems to most often happen when shooting that weapon - hitscan weapons don't seem to cause it.

### Minimal reproduction project

I am afraid I don't have one just yet.

### LINKED ISSUE #85571: Animation Player fails to run script functions.
### Godot version

4.2

### System information

Godot v4.1.stable - Fedora Linux 38 (KDE Plasma) - Vulkan (Forward+) - integrated Intel(R) Xe Graphics (TGL GT2) () - 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 Threads)

### Issue description

When creating an animation in the Animation Player that is to call a script function, the player will not run the function if it also has other tracks for the node that has the said script (meaning if tries to run function f() for node x, as well as change position of node x).

### Steps to reproduce

Create animation player.
Attach script to parent node.
Create test function.
Add animation track to the player calling the function.
Add animation track to the player changing the position of the parent node.

### Minimal reproduction project

[anim_bug.zip](https://github.com/godotengine/godot/files/13517976/anim_bug.zip)

### LINKED ISSUE #85572: Animation Player crashes editor.
### Godot version

4.2

### System information

Godot v4.1.stable - Fedora Linux 38 (KDE Plasma) - Vulkan (Forward+) - integrated Intel(R) Xe Graphics (TGL GT2) () - 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 Threads)

### Issue description

When creating example project for #85571 I created a basic project that will always crash the editor.
The only modification is that it contains two animation tracks calling a script function.

Trace:

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.stable.official (46dc277917a93cbf601bbcf0d27d00f6feeec0d5)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib64/libc.so.6(+0x3dbb0) [0x7f06c0034bb0] (??:0)
[2] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x27d87a1] (??:0)
[3] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x27d818b] (??:0)
[4] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x282d654] (??:0)
[5] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x2831e9e] (??:0)
[6] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x2856a6e] (??:0)
[7] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x16c87f3] (??:0)
[8] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x16c8f1f] (??:0)
[9] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x16c9c9d] (??:0)
[10] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x16f4d86] (??:0)
[11] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x1235654] (??:0)
[12] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x1246297] (??:0)
[13] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x1482ce2] (??:0)
[14] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x14dbc8a] (??:0)
[15] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x3b8f190] (??:0)
[16] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x1d58be9] (??:0)
[17] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x591fe9] (??:0)
[18] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x3b40f28] (??:0)
[19] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x3912911] (??:0)
[20] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x4019c0d] (??:0)
[21] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x3b8c20c] (??:0)
[22] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x20940fd] (??:0)
[23] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x4f935d] (??:0)
[24] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x41ed28] (??:0)
[25] /lib64/libc.so.6(+0x27b8a) [0x7f06c001eb8a] (??:0)
[26] /lib64/libc.so.6(__libc_start_main+0x8b) [0x7f06c001ec4b] (??:0)
[27] /home/leshy/Apps/Godot/versions/Godot_v4.2-stable_linux.x86_64() [0x42aa6a] (??:0)
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

Create node.
Add script to node.
Add test function.
Add animation player to node.
Add animation 1 to the player.
Add track calling the function to animation 1.
Add track moving the node to animation 1.
Add animation 2 to player.
Add track calling the function to animation 2.

-- it might crash at this point already --

Add _ready call to node script that will start animation 1 or 2.
Run the project.
The game will crash.
Shortly after the editor will crash as well.

### Minimal reproduction project

[anim_crash.zip](https://github.com/godotengine/godot/files/13517983/anim_crash.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
Co-authored-by: Rémi Verschelde <rverschelde@gmail.com>

Using it could easily lead to use-after-free crashes, as the object may have been freed. Caching object pointers like this is unsafe. Instead, we rely only on the ObjectID and query ObjectDB with it each time we need access to the instance.

- Supersedes #85604
- Fixes #85365
- Fixes #85572

This PR is a salvaged version of #49411 with more proper solution. Merge Value and Bezier track into the same cache. Also, make the hash generated from those track types and track paths the key of the cache map instead of the only track path.

However, as I mentioned in https://github.com/godotengine/godot/pull/49411#issuecomment-858141010, the Bezier and Value Tracks have different paths in most cases, and will not blend unless the paths are manually matched. So I believe it will be necessary to rework Bezier tracks to match path name with Value Tracks and manage subpath in a different way from current in the future.

- Fixes #43848
- Fixes #48526
- Fixes #49431
- Fixes #85571

### CODE REVIEW

File: scene/resources/animation.cpp [hunk 1]
```diff
@@ -996,6 +997,23 @@ int Animation::find_track(const NodePath &p_path, const TrackType p_type) const
...
 };
 
+void Animation::_track_update_hash(int p_track) {
+	NodePath track_path = tracks[p_track]->path;
+	TrackType track_cache_type = tracks[p_track]->type;
+	if (track_cache_type == Animation::TYPE_BEZIER) {
+		track_cache_type = Animation::TYPE_VALUE;
+	}
+	if (track_cache_type == Animation::TYPE_ROTATION_3D || track_cache_type == Animation::TYPE_SCALE_3D) {
+		track_cache_type = Animation::TYPE_POSITION_3D; //reference them as position3D tracks, even if they modify rotation or scale
```
Comment (AThousandShips) [inline scene/resources/animation.cpp:1007]:
```suggestion
		track_cache_type = Animation::TYPE_POSITION_3D; // Reference them as position3D tracks, even if they modify rotation or scale.
```

File: scene/animation/animation_mixer.h [hunk 2]
```diff
@@ -351,17 +327,23 @@ class AnimationMixer : public Node {
...
 	virtual bool _blend_pre_process(double p_delta, int p_track_count, const HashMap<NodePath, int> &p_track_map);
 	void _blend_calc_total_weight(); // For undeterministic blending.
 	void _blend_process(double p_delta, bool p_update_only = false);
 	void _blend_apply();
 	virtual void _blend_post_process();
-	void _call_object(Object *p_object, const StringName &p_method, const Vector<Variant> &p_params, bool p_deferred);
+	void _call_object(ObjectID p_object_id, const StringName &p_method, const Vector<Variant> &p_params, bool p_deferred);
+
+#ifndef DISABLE_DEPRECATED
+	virtual Variant _post_process_key_value_bind_compat(const Ref<Animation> &p_anim, int p_track, Variant p_value, Object *p_object, int p_object_idx = -1);
```
Comment (AThousandShips) [inline scene/animation/animation_mixer.h:343]:
```suggestion
	virtual Variant _post_process_key_value_bind_compat_86687(const Ref<Animation> &p_anim, int p_track, Variant p_value, Object *p_object, int p_object_idx = -1);
```
Add the PR number

File: misc/extension_api_validation/4.2-stable.expected [hunk 3]
```diff
@@ -14,3 +14,9 @@ Validate extension JSON: Error: Field 'classes/TileData/methods/get_navigation_p
 Validate extension JSON: Error: Field 'classes/TileData/methods/get_occluder/arguments': size changed value in new API, from 1 to 4.
 
 Added optional argument to get_navigation_polygon and get_occluder to specify a polygon transform.
+
+GH-86687
```
Comment (AThousandShips) [inline misc/extension_api_validation/4.2-stable.expected:18]:
```suggestion

GH-86687
```
Two lines 🙂

**Review by akien-mga — APPROVED** [review]
Looks great!

Confirmed that it fixes the MRP in #85572.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
It breaks compatibility, so not suitable for cherry-picking.
