### PR TITLE
Fix ValueTrack with Resource is leaking

### LINKED ISSUE #84483: AnimationPlayer texture leaked at exit
### Godot version

v4.2.beta4.official.93cdacbb0

### System information

Windows 10, 64bit, Vulkan API 1.3.242 - Forward+

### Issue description

If an AnimationPlayer is instantiated from another scene, the texture of the animation leaked at exit.
Stopping the animation manually and deleting the node does not seem to help.
Tested under v4.2-beta4 mono and gd-script. Leak occurs in both versions. However, the problem does not occur in version 4.1.3.

output:
```
XR: Clearing primary interface
XR: Removed interfaceNative mobile
XR: Removed interfaceOpenXR
ERROR: 1 RID allocations of type 'N10RendererRD14TextureStorage7TextureE' were leaked at exit.
WARNING: 2 RIDs of type "Texture" were leaked.
     at: finalize (drivers/vulkan/rendering_device_vulkan.cpp:9623)
WEditorSettings: Save OK!
XR: Clearing primary interface
XR: Removed interfaceNative mobile
XR: Removed interfaceOpenXR
ERROR: 1 RID allocations of type 'N10RendererRD14TextureStorage7TextureE' were leaked at exit.
WARNING: 2 RIDs of type "Texture" were leaked.
     at: finalize (drivers/vulkan/rendering_device_vulkan.cpp:9623)
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:2207)
Leaked instance: CompressedTexture2D:-9167777430419476631 - Resource path: res://frames.png
Leaked instance: BitMap:-9166121016152231285 - Resource path:
Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not freed (with `free()` or `queue_free()`).
ERROR: Resources still in use at exit (run with --verbose for details).
   at: clear (core/io/resource.cpp:489)
Resource still in use: res://frames.png (CompressedTexture2D)
```

### Steps to reproduce

Run the minimal project under 4.2.beta4 with the verbose attribute and close the project after the animation has been started.

### Minimal reproduction project

[GD_Min_AnimLeak.zip](https://github.com/godotengine/godot/files/13260062/GD_Min_AnimLeak.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
Fixes #84483.

TrackCache must explicitly release references to the resource.

### CODE REVIEW

File: scene/animation/animation_mixer.h [hunk 1]
```diff
@@ -143,6 +143,8 @@ class AnimationMixer : public Node {
 		Object *object = nullptr;
 		ObjectID object_id;
 		real_t total_weight = 0.0;
+
+		virtual ~TrackCache(){};
```
Comment (akien-mga) [inline scene/animation/animation_mixer.h:147]: Style nit, not critical.
```suggestion
		virtual ~TrackCache() {}
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

File: scene/animation/animation_mixer.h [hunk 2]
```diff
@@ -377,6 +390,12 @@ class AnimatedValuesBackup : public RefCounted {
 public:
 	void set_data(const HashMap<NodePath, AnimationMixer::TrackCache *> p_data) { data = p_data; };
 	HashMap<NodePath, AnimationMixer::TrackCache *> get_data() const { return data; };
+
+	~AnimatedValuesBackup() {
+		for (KeyValue<NodePath, AnimationMixer::TrackCache *> &K : data) {
+			memdelete(K.value);
```
Comment (nlupugla) [inline scene/animation/animation_mixer.h:396]: You might need a guard here to prevent a crash in a case where the `TrackCache *` is a nullpointer. Something like

```cpp
if (K.value) {
    memdelete(K.value);
}
```
or 
```cpp
ERR_FAIL_NULL(K.value);
memdelete(K.value);
```

Comment (KoBeWi) [reply scene/animation/animation_mixer.h:396]: This won't help if the pointer is freed (points to invalid, non-null, memory).
