### PR TITLE
[Unix] Remove leading `..` from absolute paths and apply `simplify_path` to Unix current directory path.

### LINKED ISSUE #113497: File dialog shows repeated "/.." segments when navigating parent from root
### Tested versions

- Reproducible in: v4.6.dev.custom_build [7a228b4b9]
- Not reproducible in: 4.6.dev5

### System information

Godot v4.6.dev (7a228b4b9) - Arch Linux #1 SMP PREEMPT_DYNAMIC Mon, 24 Nov 2025 15:21:09 +0000 on X11 - X11 display driver, Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3060 Ti (nvidia; 580.105.08) - 13th Gen Intel(R) Core(TM) i5-13400F (16 threads) - 15.37 GiB memory

### Issue description

For a FileDialog or EditorFileDialog that is configured to pick FileSystem paths: the current folder path becomes something like `/../../..` if you keep clicking Up after reaching the root folder.

Image

### Steps to reproduce

1. Open the Project Manager
2. Click Scan
3. Click the Up arrow in the file dialog (Go to Parent Folder)
4. Keep clicking after reaching root
5. Check the path becomes something like `/../../../..`

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
- Removes all leading `..` from absolute paths in `simplify_path`.
- Apply `simplify_path` in the Unix `fix_path` (same is already done on Windows).

Fixes https://github.com/godotengine/godot/issues/113497

### CODE REVIEW

File: core/string/ustring.cpp [hunk 1]
```diff
@@ -4189,6 +4189,7 @@ String String::simplify_path() const {
 		}
 	}
 	Vector<String> dirs = s.split("/", false);
+	bool absolute_path = is_absolute_path();
```
Comment (adamscott) [inline core/string/ustring.cpp:4192]: Technically, this code will not fix `"/.."` because `dirs` would be empty.

```suggestion
	Vector<String> dirs = s.split("/", false);
	if (dirs.is_empty() && !s.is_empty()) {
		dirs.push_back(s);
	}

	bool absolute_path = is_absolute_path();
```

Comment (bruvzg) [reply core/string/ustring.cpp:4192]: > this code will not fix "/.." because dirs would be empty.

It will work, `/..` splits to a `dirs` with single `..` and simplify to `/`. First slash will be in `drive` not in `dirs`.

**Comment by bruvzg** [comment]
Failed test seems to be an abuse of path, it's trying to load `res://../texture.png`, which should not work.

**Comment by bruvzg** [comment]
Since it might be used by GLTF importer, I have added a check to allow `res://../` paths, but this should be reconsidered in the future, files outside the project should not be accessible this way.

**Review by akien-mga — APPROVED** [review]
The bug has already been fixed by an alternative approach, so this is not urgent.

But let's give it a spin for 4.7-dev so that we have enough time to solve any potential side effects of changing `simplify_path`.
