### PR TITLE
Changed the title of change node type dialog

### LINKED ISSUE #36831: Change type always says Node
**Godot version:**
3.2

**Issue description:**
When you select Change Type in scene tree, you always see this
image
But the format for this string is `Change %s Type`. It's filled incorrectly.

### PR DESCRIPTION
**Pull request by theoway**
Fixes #36831
The title of 'change node type' dialog was ambiguous. Now it reads `Convert Node from NodeType`, where Node is the selected node's name and NodeType is the selected node's type. This title is much more clear than the previous one, which was `Change Node Type`. This way, users can have more clarity about the node and its type that they're changing/replacing.
**Code Modification:-**
A default parameter to store the selected node's name is added, whose default value is `""`(empty string), to the function `popup_create()` in the `CreateDialog` class. 
Looking at the call hierarchy of this function, this modification is consistent with the functions it is being called from.

### CODE REVIEW

**Review by clayjohn — DISMISSED** [review]
Approved in PR review meeting, can be merged once conflicts resolved.

File: editor/create_dialog.cpp [hunk 1]
```diff
@@ -111,7 +111,7 @@ void CreateDialog::popup_create(bool p_dont_clear, bool p_replace_mode, const St
 
 	if (p_replace_mode) {
 		select_type(p_select_type);
-		set_title(vformat(TTR("Change %s Type"), base_type));
+		set_title(vformat(TTR("Convert %s from %s"), p_select_name, p_select_type));
```
Comment (YuriSizov) [inline editor/create_dialog.cpp:114]: `CreateDialog` is used in visual script with `p_replace_mode` enabled but no other parameters parsed:

```
void VisualScriptEditor::_change_base_type() {
	select_base_type->popup_create(true, true);
}
```

This change would make the title look weird, and probably needs addressing. (Though visual script is on its way out so, maybe we don't care).

**Comment by theoway** [comment]
Conflicts resolved. Ready to be merged 👍

File: editor/scene_tree_dock.cpp [hunk 2]
```diff
@@ -509,9 +509,8 @@ void SceneTreeDock::_tool_selected(int p_tool, bool p_confirm_override) {
 				selected = editor_selection->get_selected_node_list().front()->get();
 			}
 
-			if (selected) {
-				create_dialog->popup_create(false, true, selected->get_class());
-			}
+			if (selected)
+				create_dialog->popup_create(false, true, selected->get_class(), selected->get_name());
```
Comment (KoBeWi) [inline editor/scene_tree_dock.cpp:513]:
```suggestion
			if (selected) {
				create_dialog->popup_create(false, true, selected->get_class(), selected->get_name());
			}
```

File: editor/create_dialog.cpp (hunk 1 above)
Comment (KoBeWi) [reply editor/create_dialog.cpp]: The fix is easy to do, so no reason to break the editor IMO (it's still there).
Here's the relevant line:
https://github.com/godotengine/godot/blob/f2a61684143af02a8cbe7002645af817607f9bd6/modules/visual_script/editor/visual_script_editor.cpp#L2939
`p_select_name` can't be determined in VisualScript though.

Comment (theoway) [reply editor/create_dialog.cpp]: @KoBeWi What should I set `p_select_name` & `p_select_type` to in ` select_base_type->popup_create(true, true)`?

Comment (KoBeWi) [reply editor/create_dialog.cpp]: `p_select_type` can be either `base_type` or `script->get_instance_base_type()` I think.
As for `p_select_name`... maybe something generic, like "base type" or "VisualScript"? You could also add a special case for empty `p_select_name`.

Comment (YuriSizov) [reply editor/create_dialog.cpp]: Something generic would be hard to localize. I'd go for handling this case of an empty value properly in the dialog.

Comment (theoway) [reply editor/create_dialog.cpp]:
```
if (!p_select_name.size()) {
			set_title(vformat(TTR("Convert %s from %s"), p_select_name, p_select_type));
		} else {
			set_title(vformat(TTR("Convert from %s type base script"), p_select_type));
		}
```
I think this will do well. Let me know your thoughts.

Comment (KoBeWi) [reply editor/create_dialog.cpp]: Should be `p_select_name.is_empty()`.

Comment (theoway) [reply editor/create_dialog.cpp]: Done :)

**Review by KoBeWi — APPROVED** [review]
Looks good now.

The only thing that slightly bothers me is when node has the same name as the type:
image
`p_select_name` could be checked if it's not equal to `p_select_type`, but not sure if it's worth it.

**Comment by YuriSizov** [comment]
Thanks!
