### PR TITLE
Fix crash when assigning a node on editing animation key

### LINKED ISSUE #19712: NodePath property assignment for inspected resource crashes editor
**Godot version:**
v3.1.dev.calinou.a9acdd8

**OS/device including version:**
Windows 10

**Issue description:**
Editor will crash when selecting a node for a NodePath property in an inspected resource. Possible to see this in AnimationPlayer when using a call func track and creating a key that takes a NodePath as a parameter. Not specific to AnimationPlayer since also producible in other inspected resources.

**Steps to reproduce:**
- create a call func track in AnimationPlayer
- create a key that takes a NodePath as a parameter
- click on the key to inspect the AnimationTrackKeyEdit in the property inspector
- try assigning a node to the arg in the property inspector
nodepathbug

**Minimal reproduction project:**

[NodePathBug.zip](https://github.com/godotengine/godot/files/2126311/NodePathBug.zip)

### PR DESCRIPTION
**Pull request by volzhs**
Fix #19712

### CODE REVIEW

File: editor/editor_properties.cpp [hunk 1]
```diff
@@ -1522,8 +1522,15 @@ EditorPropertyColor::EditorPropertyColor() {
 
 void EditorPropertyNodePath::_node_selected(const NodePath &p_path) {
 
+	NodePath path = p_path;
 	Node *base_node = Object::cast_to<Node>(get_edited_object());
-	emit_signal("property_changed", get_edited_property(), base_node->get_path().rel_path_to(p_path));
+	if (base_node == NULL && get_edited_object()->has_method("get_root_path")) {
+		base_node = get_edited_object()->call("get_root_path");
+	}
+	if (base_node) { // for AnimationTrackKeyEdit
```
Comment (bojidar-bg) [inline editor/editor_properties.cpp]: I think you can remove the comment; some day, other resources might also have nodepaths.
