### PR TITLE
Cache world in VisibilityNotifier3D to avoid crash

### LINKED ISSUE #45508: Engine crash when changing Viewport::own_world with VisibilityNotifier in that viewport
**Godot version:**
Godot Engine v3.2.4.rc.mono.custom_build. 98666f985517a67d9d514b53c249f865c438c00b
Godot Engine v3.2.4.beta.custom_build.633c9555d

**OS/device including version:**
Windows 10, GLES2/GLES3

**Issue description:**
Crash when changing the `own_world` property of the `Viewport` node.

```
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] World::_remove_notifier (C:\My\Godot\Sources\godot\scene\resources\world.cpp:247)
[1] World::_remove_notifier (C:\My\Godot\Sources\godot\scene\resources\world.cpp:247)
[2] VisibilityNotifier::_notification (C:\My\Godot\Sources\godot\scene\3d\visibility_notifier.cpp:96)
[3] VisibilityNotifier::_notificationv (C:\My\Godot\Sources\godot\scene\3d\visibility_notifier.h:39)
[4] Object::notification (C:\My\Godot\Sources\godot\core\object.cpp:931)
[5] Viewport::_propagate_exit_world (C:\My\Godot\Sources\godot\scene\main\viewport.cpp:1123)
[6] Viewport::_propagate_exit_world (C:\My\Godot\Sources\godot\scene\main\viewport.cpp:1125)
[7] Viewport::set_use_own_world (C:\My\Godot\Sources\godot\scene\main\viewport.cpp:2897)
[8] MethodBind1<Viewport,bool>::call (C:\My\Godot\Sources\godot\core\method_bind.gen.inc:867)
[9] ClassDB::set_property (C:\My\Godot\Sources\godot\core\class_db.cpp:1049)
[10] Object::set (C:\My\Godot\Sources\godot\core\object.cpp:423)
[11] UndoRedo::_process_operation_list (C:\My\Godot\Sources\godot\core\undo_redo.cpp:311)
[12] UndoRedo::redo (C:\My\Godot\Sources\godot\core\undo_redo.cpp:338)
[13] UndoRedo::commit_action (C:\My\Godot\Sources\godot\core\undo_redo.cpp:261)
[14] EditorInspector::_edit_set (C:\My\Godot\Sources\godot\editor\editor_inspector.cpp:2062)
[15] EditorInspector::_property_changed (C:\My\Godot\Sources\godot\editor\editor_inspector.cpp:2081)
[16] MethodBind4<EditorInspector,String const &,Variant const &,String const &,bool>::call (C:\My\Godot\Sources\godot\core\method_bind.gen.inc:3219)
[17] Object::call (C:\My\Godot\Sources\godot\core\object.cpp:919)
[18] Object::emit_signal (C:\My\Godot\Sources\godot\core\object.cpp:1246)
[19] EditorProperty::emit_changed (C:\My\Godot\Sources\godot\editor\editor_inspector.cpp:89)
[20] EditorPropertyCheck::_checkbox_pressed (C:\My\Godot\Sources\godot\editor\editor_properties.cpp:468)
[21] MethodBind0<EditorPropertyCheck>::call (C:\My\Godot\Sources\godot\core\method_bind.gen.inc:150)
[22] Object::call (C:\My\Godot\Sources\godot\core\object.cpp:919)
[23] Object::emit_signal (C:\My\Godot\Sources\godot\core\object.cpp:1246)
[24] Object::emit_signal (C:\My\Godot\Sources\godot\core\object.cpp:1304)
[25] BaseButton::_pressed (C:\My\Godot\Sources\godot\scene\gui\base_button.cpp:135)
[26] BaseButton::on_action_event (C:\My\Godot\Sources\godot\scene\gui\base_button.cpp:174)
[27] BaseButton::_gui_input (C:\My\Godot\Sources\godot\scene\gui\base_button.cpp:64)
[28] MethodBind1<BaseButton,Ref<InputEvent> >::call (C:\My\Godot\Sources\godot\core\method_bind.gen.inc:867)
[29] Object::call_multilevel (C:\My\Godot\Sources\godot\core\object.cpp:761)
[30] Object::call_multilevel (C:\My\Godot\Sources\godot\core\object.cpp:862)
[31] Viewport::_gui_call_input (C:\My\Godot\Sources\godot\scene\main\viewport.cpp:1688)
[32] Viewport::_gui_input_event (C:\My\Godot\Sources\godot\scene\main\viewport.cpp:2068)
[33] Viewport::input (C:\My\Godot\Sources\godot\scene\main\viewport.cpp:2861)
[34] Viewport::_vp_input (C:\My\Godot\Sources\godot\scene\main\viewport.cpp:1453)
[35] MethodBind1<Viewport,Ref<InputEvent> const &>::call (C:\My\Godot\Sources\godot\core\method_bind.gen.inc:867)
[36] Object::call (C:\My\Godot\Sources\godot\core\object.cpp:919)
[37] Object::call (C:\My\Godot\Sources\godot\core\object.cpp:846)
[38] SceneTree::call_group_flags (C:\My\Godot\Sources\godot\scene\main\scene_tree.cpp:275)
[39] SceneTree::input_event (C:\My\Godot\Sources\godot\scene\main\scene_tree.cpp:431)
[40] InputDefault::_parse_input_event_impl (C:\My\Godot\Sources\godot\main\input_default.cpp:442)
[41] InputDefault::flush_accumulated_events (C:\My\Godot\Sources\godot\main\input_default.cpp:679)
[42] OS_Windows::run (C:\My\Godot\Sources\godot\platform\windows\os_windows.cpp:3449)
[43] widechar_main (C:\My\Godot\Sources\godot\platform\windows\godot_windows.cpp:162)
[44] _main (C:\My\Godot\Sources\godot\platform\windows\godot_windows.cpp:186)
[45] main (C:\My\Godot\Sources\godot\platform\windows\godot_windows.cpp:196)
[46] __scrt_common_main_seh (d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[47] BaseThreadInitThunk
-- END OF BACKTRACE --
```

**Steps to reproduce:**
1. Create a scene with the Viewport root node
2. Add VisibilityNotifier as a child of the Viewport
3. Change the `own_world` property of the Viewport

**Minimal reproduction project:**
[ViewportVisibilityNotifier.zip](https://github.com/godotengine/godot/files/5881849/ViewportVisibilityNotifier.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #45508
Not sure why the world was null, but if it works...

### CODE REVIEW

File: scene/3d/visibility_notifier_3d.cpp [hunk 1]
```diff
@@ -80,13 +80,16 @@ AABB VisibilityNotifier3D::get_aabb() const {
 void VisibilityNotifier3D::_notification(int p_what) {
 	switch (p_what) {
 		case NOTIFICATION_ENTER_WORLD: {
-			get_world_3d()->_register_notifier(this, get_global_transform().xform(aabb));
+			world = get_world_3d();
```
Comment (akien-mga) [inline scene/3d/visibility_notifier_3d.cpp:83]: What's the advantage of caching it, as opposed to just assigning to a local variable and doing `ERR_FAIL_COND` check? The same check might be need in `NOTIFICATION_TRANSFORM_CHANGED` too, or you might end up operating on a different `world` than the one cached maybe?

**Comment by akien-mga** [comment]
In `set_aabb()` it checks `is_inside_world()` before accessing `get_world()`, maybe that's what is needed here too?

File: scene/3d/visibility_notifier_3d.cpp (hunk 1 above)
Comment (KoBeWi) [reply scene/3d/visibility_notifier_3d.cpp:83]: It guarantees that on EXIT_WORLD you exit the same world you entered. The crash happened because for some reason notifier was losing the world reference. If you add only null check, the old world stays "unexited" and crashes on exit.

And yeah, replacing other references might be a good idea.

**Comment by KoBeWi** [comment]
No, there's still crash on exit.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
