### PR TITLE
Handle NOTIFICATION_WM_CLOSE_REQUEST in EditorSpinSlider

### LINKED ISSUE #59174: Mouse cursor disappears after adjusting environment preview sky light parameters
### Godot version

4.0 alpha 4 [f47097973]

### System information

Vulkan, Windows 11, Nvidia GTX 1060, intel i5 11400

### Issue description

After clicking the three dots on the top of the editor preview to adjust the properties of the sky light and adjusting the angular altitude or the azimuth with the sliders, the mouse cursor no longer displays while Godot is open
Screenshot (6)
.

### Steps to reproduce

In a new project, adjust the azimuth or angular altitude settings of the sun with the sliders from the drop down menu above the preview window.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Sauermann**
resolve #59174

The bug in the referenced issue is caused by the fact that the `EditorSpinSlider` receives a `NOTIFICATION_WM_CLOSE_REQUEST`, that is initiated in
https://github.com/godotengine/godot/blob/cfd21adf64087c750dde89191bcfcf4d166adc85/platform/linuxbsd/display_server_x11.cpp#L3261-L3270
because the mouse leaves the area of the popup window.

This patch makes sure, that `NOTIFICATION_WM_CLOSE_REQUEST` is handled correctly in `EditorSpinSlider::_notification`, so that the GUI does not get into an unstable internal state.

It feels like unintended behavior, that dragging the mouse too far causes the `sun_environ_popup` to close itself.
Therefore this patch also sets the `safe_rect` of the `sun_environ_popup` to the screen size, so that the close request is never sent.

### CODE REVIEW

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -6863,6 +6863,8 @@ void Node3DEditor::_sun_environ_settings_pressed() {
 	sun_environ_popup->set_position(pos - Vector2(sun_environ_popup->get_contents_minimum_size().width / 2, 0));
 	sun_environ_popup->reset_size();
 	sun_environ_popup->popup();
+	Rect2i safe_rect = DisplayServer::get_singleton()->screen_get_usable_rect();
+	DisplayServer::get_singleton()->window_set_popup_safe_rect(sun_environ_popup->get_window_id(), safe_rect);
```
Comment (bruvzg) [inline editor/plugins/node_3d_editor_plugin.cpp:6867]: This will prevent closing the popup by clicking outside it. Probably X11 mouse handler should be changed to only trigger if mouse button state is changed (this need to be tested). On the other platforms, it should be the case already.

```diff
diff --git a/platform/linuxbsd/display_server_x11.cpp b/platform/linuxbsd/display_server_x11.cpp
index 07cb6a23e8..a2ec9cbe13 100644
--- a/platform/linuxbsd/display_server_x11.cpp
+++ b/platform/linuxbsd/display_server_x11.cpp
@@ -3250,7 +3250,7 @@ void DisplayServerX11::mouse_process_popups() {
 			XWindowAttributes root_attrs;
 			XGetWindowAttributes(x11_display, root, &root_attrs);
 			Vector2i pos = Vector2i(root_attrs.x + root_x, root_attrs.y + root_y);
-			if ((pos != last_mouse_monitor_pos) || (mask != last_mouse_monitor_mask)) {
+			if (mask != last_mouse_monitor_mask) {
 				if (((mask & Button1Mask) || (mask & Button2Mask) || (mask & Button3Mask) || (mask & Button4Mask) || (mask & Button5Mask))) {
 					List<WindowID>::Element *E = popup_list.back();
 					while (E) {
@@ -3272,7 +3272,6 @@ void DisplayServerX11::mouse_process_popups() {
 				}
 			}
 			last_mouse_monitor_mask = mask;
-			last_mouse_monitor_pos = pos;
 		}
 	}
 }
diff --git a/platform/linuxbsd/display_server_x11.h b/platform/linuxbsd/display_server_x11.h
index 63d32d939d..0a2194a23d 100644
--- a/platform/linuxbsd/display_server_x11.h
+++ b/platform/linuxbsd/display_server_x11.h
@@ -154,7 +154,6 @@ class DisplayServerX11 : public DisplayServer {
 	Map<WindowID, WindowData> windows;
 
 	unsigned int last_mouse_monitor_mask = 0;
-	Vector2i last_mouse_monitor_pos;
 	uint64_t time_since_popup = 0;
 
 	List<WindowID> popup_list;
```

File: editor/editor_spin_slider.cpp [hunk 2]
```diff
@@ -443,6 +443,7 @@ void EditorSpinSlider::_notification(int p_what) {
 
 		case NOTIFICATION_WM_WINDOW_FOCUS_IN:
 		case NOTIFICATION_WM_WINDOW_FOCUS_OUT:
+		case NOTIFICATION_WM_CLOSE_REQUEST:
```
Comment (bruvzg) [inline editor/editor_spin_slider.cpp:446]: This change seems good.

**Review by bruvzg — CHANGES_REQUESTED** [review]

File: editor/plugins/node_3d_editor_plugin.cpp (hunk 1 above)
Comment (Sauermann) [reply editor/plugins/node_3d_editor_plugin.cpp]: Thanks for the explanation. It would probably be best to split this change into a different PR, so that this PR can deal with the referenced issue.

**Review by bruvzg — APPROVED** [review]

File: editor/plugins/node_3d_editor_plugin.cpp (hunk 1 above)
Comment (bruvzg) [reply editor/plugins/node_3d_editor_plugin.cpp]: For the reference, "safe rect" is intended to prevent submenus from closing and re-opening when you click the parent menu item that was used to open the submenu.

Like the marked area here:
Screenshot 2022-03-16 at 09 56 45

**Comment by akien-mga** [comment]
Thanks!
