### PR TITLE
Wayland: Improve compositor compatibility by allowing older globals

### LINKED ISSUE #90612: wayland cannot work with weston
### Tested versions

Godot Engine v4.3.dev4.official.df78c0636 - https://godotengine.org/

### System information

ubuntu 2204 with weston 

### Issue description

cannot open edit with weston, cmdline out is:
`Godot Engine v4.3.dev4.official.df78c0636 - https://godotengine.org/
WARNING: Can't obtain the XDG decoration manager. Libdecor will be used for drawing CSDs, if available.
at: init (platform/linuxbsd/wayland/wayland_thread.cpp:3493)
WARNING: Can't obtain the XDG activation global. Attention requesting won't work!
at: init (platform/linuxbsd/wayland/wayland_thread.cpp:3500)
wl_registry@2: error 0: invalid version for global xdg_wm_base (22): have 1, wanted 2
ERROR: Wayland protocol error 0 on interface wl_registry@2.
at: _poll_events_thread (platform/linuxbsd/wayland/wayland_thread.cpp:2540)

================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.3.dev4.official (https://github.com/godotengine/godot/commit/df78c0636d79c9545a283e0e2a926d623998cc27)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f3a4fa42520] (??:0)
[2] godot4_3() [0x47e587] (??:0)
[3] godot4_3() [0x3c9fbe5] (??:0)
[4] godot4_3() [0x48e4963] (??:0)
[5] /lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7f3a4fa94ac3] (??:0)
[6] /lib/x86_64-linux-gnu/libc.so.6(+0x126850) [0x7f3a4fb26850] (??:0)
-- END OF BACKTRACE --
================================================================`

### Steps to reproduce

1. run weston
2. in weston window, open a terminal, type: 
godot --display-driver wayland
3.it crashes

### Minimal reproduction project (MRP)

no

### PR DESCRIPTION
**Pull request by deralmas**
Fixes #90612

Previously we pretty much hardcoded most of the globals we requested, causing compatibility issues with certain compositors like Weston, which support only some pretty old versions or miss some more advanced protocols.

To put fuel on the fire, we also errored out when certain protocols weren't available, despite us being able to boot a game just fine (but obviously with a degraded featureset).

The solution is to simply allow all the way from version 1 to the current latest, adding some compatibility code (such as for older `wl_output`s or newer `wl_pointer`s).

While we're at it, this commit also fixes a few typos and naming inconsistencies I found.

Edit: oh right, this also removes some initialization code for an unused global, `wl_subcompositor`.

## Bonus content

Here's a an updated version of the table I put in the above issue ticket:

|               Object Name               | Minimum Version Accepted | Maximum Version Implemented | Mandatory? | Notes
|-----------------------------------------|--------------------------|-----------------------------|------------|-------
|`wl_compositor`                          |1                         |6                            |y           |surface creation
|`xdg_wm_base`                            |1                         |6                            |y           |desktop windows
|`wl_shm`                                 |1                         |1                            |y           |cursor buffer handling
|`wl_data_device_manager`                 |1                         |3                            |n           |clipboard and drag&drop
|`wl_output`                              |1                         |4                            |n           |screen info, can be registered multiple times
|`wl_seat`                                |1                         |9                            |n           |basic input, can be registered multiple times
|`wp_viewporter`                          |1                         |1                            |n           |buffer "stretching", fractional scaling dependency
|`wp_fractional_scale_manager_v1`         |1                         |1                            |n           |fractional scaling
|`zwp_primary_selection_device_manager_v1`|1                         |1                            |n           |primary clipboard
|`zwp_pointer_constraints_v1`             |1                         |1                            |n           |pointer constraints
|`zwp_relative_pointer_manager_v1`        |1                         |1                            |n           |relative pointer input, especially useful when paired with pointer constraints
|`zwp_pointer_gestures_v1`                |1                         |1                            |n           |touchpad gestures
|`zwp_tablet_manager_v2`                  |1                         |1                            |n           |drawing tablet support
|`zxdg_decoration_manager_v1`             |1                         |1                            |n           |manual server-side decorations handling (libdecor-less fallback)
|`zxdg_activation_v1`                     |1                         |1                            |n           |attention requesting
|`zwp_idle_inhibit_manager_v1`            |1                         |1                            |n           |idle inibition (non-GNOME)
|`zxdg_exporter_v1`                       |1                         |1                            |n           |dbus desktop integration

Much better I'd say :D

### CODE REVIEW

File: platform/linuxbsd/wayland/wayland_thread.cpp [hunk 1]
```diff
@@ -371,28 +371,22 @@ void WaylandThread::_wl_registry_on_global(void *data, struct wl_registry *wl_re
...
-		registry->wl_exporter = (struct zxdg_exporter_v1 *)wl_registry_bind(wl_registry, name, &zxdg_exporter_v1_interface, 1);
-		registry->wl_exporter_name = name;
+		registry->xdg_exporter = (struct zxdg_exporter_v1 *)wl_registry_bind(wl_registry, name, &zxdg_exporter_v1_interface, 1);
+		registry->xdg_exporter_name = name;
 		return;
 	}
 
 	if (strcmp(interface, wl_compositor_interface.name) == 0) {
-		registry->wl_compositor = (struct wl_compositor *)wl_registry_bind(wl_registry, name, &wl_compositor_interface, 4);
+		registry->wl_compositor = (struct wl_compositor *)wl_registry_bind(wl_registry, name, &wl_compositor_interface, MAX(1, MIN(6, (int)version)));
```
Comment (akien-mga) [inline platform/linuxbsd/wayland/wayland_thread.cpp:380]: You could use `CLAMP` instead of `MAX(MIN(...))`.

File: platform/linuxbsd/wayland/wayland_thread.cpp [hunk 2]
```diff
@@ -1596,13 +1594,13 @@ void WaylandThread::_wl_pointer_on_frame(void *data, struct wl_pointer *wl_point
 				if (test_button == MouseButton::WHEEL_UP || test_button == MouseButton::WHEEL_DOWN) {
 					// If this is a discrete scroll, specify how many "clicks" it did for this
 					// pointer frame.
-					mb->set_factor(abs(pd.discrete_scroll_vector.y));
+					mb->set_factor(fabs(pd.discrete_scroll_vector_120.y / (float)120));
```
Comment (akien-mga) [inline platform/linuxbsd/wayland/wayland_thread.cpp:1597]: Prefer using our own `Math::abs` abstraction over the C API directly, this used to be a source of trouble on MSVC.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
