### PR TITLE
Fix import and saving related crashes

### LINKED ISSUE #89776: Importing a line only obj crash Godot Editor
### Tested versions

- Reproductible in 4.3-dev5

### System information

Windows 10 - Godot 4.3-dev5 Vulkan (Forward+)

### Issue description

When importing a simple obj with only lines inside, Godot crashes.

### Steps to reproduce

Just import the provided file in a Godot project

### Minimal reproduction project (MRP)

Create a new project and copy the provided obj file into it.
[profil.zip](https://github.com/godotengine/godot/files/14720714/profil.zip)

### PR DESCRIPTION
**Pull request by AThousandShips**
* Don't add empty mesh to result when importing obj files
* Check for null resources in `ResourceSaver`

This adds the check from `core_bind` to `ResourceSaver` directly, ~could remove the one in `ResourceSaver.save` in `core_bind` as it's now redundant, but just added it for now~, it helps catch broken cases when doing things from c++

The obj side avoids doing any of the remaining code, makes things a bit clearer, and matches the code here:
https://github.com/godotengine/godot/blob/fe01776f05b1787b28b4a270d53037a3c25f4ca2/editor/import/3d/resource_importer_obj.cpp#L441-L445

For this specific case we might want to look at adding support for lines in obj files as they support it, or a more clear error message or warning when using unsupported features, but that's outside the scope of this

---

* Fixes: https://github.com/godotengine/godot/issues/89776

### CODE REVIEW

**Comment by akien-mga** [comment]
> This adds the check from `core_bind` to `ResourceSaver` directly, could remove the one in `ResourceSaver.save` in `core_bind` as it's now redundant, but just added it for now, it helps catch broken cases when doing things from c++

I would remove the redundant `core_bind` checks then, as it seems to be wasteful for performance to do these checks twice.

**Comment by AThousandShips** [comment]
Done!

File: core/core_bind.cpp [hunk 1]
```diff
@@ -152,12 +152,10 @@ void ResourceLoader::_bind_methods() {
 ////// ResourceSaver //////
 
 Error ResourceSaver::save(const Ref<Resource> &p_resource, const String &p_path, BitField<SaverFlags> p_flags) {
-	ERR_FAIL_COND_V_MSG(p_resource.is_null(), ERR_INVALID_PARAMETER, "Can't save empty resource to path '" + p_path + "'.");
 	return ::ResourceSaver::save(p_resource, p_path, p_flags);
 }
 
 Vector<String> ResourceSaver::get_recognized_extensions(const Ref<Resource> &p_resource) {
-	ERR_FAIL_COND_V_MSG(p_resource.is_null(), Vector<String>(), "It's not a reference to a valid Resource object.");
```
Comment (AThousandShips) [inline core/core_bind.cpp:160]: This one isn't entirely redundant as it exits a bit faster, but it's only skipping over the loop which is minimal

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank *you*!
