### PR TITLE
`ThemeEditor`: Reorganize/fix UI to make it fit in editor (at its minimum size in single-window mode) better

### LINKED ISSUE #9372: Improve the theme editor's `Add Preview` button
### Describe the project you are working on

stuff

### Describe the problem or limitation you are having in your project

Scene tabs:
image

Theme editor tabs:
image

This `Add Preview` button feels far away to me, it should be close to the TabBar. Additionally, its text and icons could possibly be improved.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

either
image

or
image

I don't know if the text is necessary.

Alternatively, since this is about opening a file and not creating one, the icon could also be this one instead (which I think wouldn't stand alone as well as the `+` one does):
image
and the text could possibly be changed to `open preview scene` or something.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

see above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

it can't be worked around

### Is there a reason why this should be core and not an add-on in the asset library?

it's about improving the current editor experience

### PR DESCRIPTION
**Pull request by arkology**
Replace text for add preview / close buttons with icons, remove theme preview custom minimum width, fix "Manage Items" window size in single-window mode and editor window at minimum size. 
This allows to reduce minimum size of `ThemeEditor`, improving (partially fixing) the use of non-standard editor layouts (for example, 2 columns for left dock and 1 column for right dock) without panels pushed out of screen.

| 4.5 beta 3 | PR |
| --- | --- |
| Godot_v4 5-beta3_win64_KyEbXAurPz | godot windows editor dev x86_64_8hsh5LIC4U |

https://github.com/user-attachments/assets/6345fc48-af08-4caf-ac03-fb1b3b610f02

Related to https://github.com/godotengine/godot/pull/102301

---

UPD: Now it looks a bit different (after addressing @KoBeWi feedback) and also closes https://github.com/godotengine/godot-proposals/issues/9372:

https://github.com/user-attachments/assets/badd3221-f8df-4ad4-a418-4e440d27641e

### CODE REVIEW

File: editor/scene/gui/theme_editor_plugin.cpp [hunk 1]
```diff
@@ -3897,10 +3900,21 @@ ThemeEditor::ThemeEditor() {
...
 	theme_name->set_theme_type_variation("HeaderSmall");
+	theme_name->set_h_size_flags(Control::SIZE_EXPAND_FILL);
 	top_menu->add_child(theme_name);
 
-	top_menu->add_spacer(false);
+	top_menu->add_child(memnew(VSeparator));
+
+	Button *theme_edit_button = memnew(Button);
+	theme_edit_button->set_text(TTRC("Manage Items..."));
+	theme_edit_button->set_tooltip_text(TTRC("Add, remove, organize and import Theme items."));
```
Comment (AThousandShips) [inline editor/scene/gui/theme_editor_plugin.cpp]:
```suggestion
	theme_edit_button->set_tooltip_text(TTRC("Add, remove, organize, and import Theme items."));
```
Would break translations but this should really use Oxford comma

**Review by bruvzg — APPROVED** [review]
Looks good, theme editor seems to be usable at min. window size.

**Review by AThousandShips — APPROVED** [review]

File: editor/scene/gui/theme_editor_plugin.cpp (hunk 1 above)
Comment (arkology) [reply editor/scene/gui/theme_editor_plugin.cpp]: Ok, lets break it.
UPD: Done.

File: editor/scene/gui/theme_editor_plugin.cpp [hunk 2]
```diff
@@ -3897,10 +3900,21 @@ ThemeEditor::ThemeEditor() {
 
 	theme_name = memnew(Label);
 	theme_name->set_text(TTR("Theme:"));
+	theme_name->set_text_overrun_behavior(TextServer::OVERRUN_TRIM_ELLIPSIS);
```
Comment (KoBeWi) [inline editor/scene/gui/theme_editor_plugin.cpp:3967]: It could be useful to put the full theme name in the tooltip, in case it's trimmed.

**Comment by KoBeWi** [comment]
This stray separator looks odd when there is much space:
image
Maybe you could add icon to Manage Elements, to act as separator?

These 2 Add buttons next to each other are also questionable:
image
idk how to improve it though.

File: editor/scene/gui/theme_editor_plugin.cpp [hunk 3]
```diff
@@ -3914,21 +3928,15 @@ ThemeEditor::ThemeEditor() {
 	theme_save_as_button->connect(SceneStringName(pressed), callable_mp(this, &ThemeEditor::_theme_save_button_cbk).bind(true));
 	top_menu->add_child(theme_save_as_button);
 
-	Button *theme_close_button = memnew(Button);
-	theme_close_button->set_text(TTR("Close"));
+	top_menu->add_child(memnew(VSeparator));
+
+	theme_close_button = memnew(Button);
+	theme_close_button->set_tooltip_text(TTRC("Close"));
+	theme_close_button->set_accessibility_name(TTRC("Close"));
```
Comment (KoBeWi) [inline editor/scene/gui/theme_editor_plugin.cpp]: Not needed after #107656

File: editor/scene/gui/theme_editor_plugin.cpp (hunk 2 above)
Comment (arkology) [reply editor/scene/gui/theme_editor_plugin.cpp:3967]: I was going to do it in a follow-up PR (improve autotranslation support)

**Comment by arkology** [comment]
> This stray separator looks odd when there is much space: 
> image 
> Maybe you could add icon to Manage Elements, to act as separator?

This is questionable, for me it does not look odd. I could add icon, but it will eat more space I just freed and I'm not sure which icon to use.

> These 2 Add buttons next to each other are also questionable:
> image 
> idk how to improve it though.

Agreed. I could move "Add preview" button to the left of preview tabs, but it will also look odd (tested it before).

File: editor/scene/gui/theme_editor_plugin.cpp (hunk 3 above)
Comment (arkology) [reply editor/scene/gui/theme_editor_plugin.cpp]: Got it, thanks. Done.

**Comment by arkology** [comment]
> These 2 Add buttons next to each other are also questionable:
> image
> idk how to improve it though.

I was looking through the list of issues I had saved earlier (and was interested in) and found this https://github.com/godotengine/godot-proposals/issues/9372. So actually I could make this button flat! @KoBeWi what do you think?

**Comment by KoBeWi** [comment]
Flat and next to the last tab, like in the proposal and scene tabs. That would be nice.

File: editor/scene/gui/theme_editor_plugin.cpp (hunk 2 above)
Comment (arkology) [reply editor/scene/gui/theme_editor_plugin.cpp:3967]: Done it current PR.

File: editor/scene/gui/theme_editor_plugin.cpp [hunk 4]
```diff
@@ -3875,18 +3884,56 @@ void ThemeEditor::drop_data_fw(const Point2 &p_point, const Variant &p_data, Con
 	preview_tab->connect("scene_reloaded", callable_mp(this, &ThemeEditor::_update_preview_tab).bind(preview_tab));
 }
 
+void ThemeEditor::_preview_tabs_resized() {
+	const Size2 add_button_size = Size2(add_preview_button->get_size().x, preview_tabs->get_size().y);
+	if (preview_tabs->get_offset_buttons_visible()) {
+		// Move the add button to a fixed position.
+		if (add_preview_button->get_parent() == preview_tabs) {
+			preview_tabs->remove_child(add_preview_button);
+			add_preview_button_ph->add_child(add_preview_button);
```
Comment (KoBeWi) [inline editor/scene/gui/theme_editor_plugin.cpp]: You can use `reparent()` instead.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
