### PR TITLE
Fix Tree check propagation not unchecking parent items

### LINKED ISSUE #79942: Tree.propagate_check() does not uncheck parents
### Godot version

4.2 dev1

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Calling `Tree.propagate_check()` after an item is unchecked does not properly uncheck the parents. They are left in partially checked state.

It's easy to observe in theme editor:

https://github.com/godotengine/godot/assets/2223172/71d0479c-0a5e-48d3-957f-d90379a95c22

### Steps to reproduce

1. Edit a Theme resource
2. Go to Manage Items... menu
3. Go to Import Items tab
4. Unfold something
5. Check and uncheck a child checkbox

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Ymanawat**
This PR focuses on `4.x` branches and resolves a tree selection bug that exists in various application sections, including theme editor, asset installation and import. The bug caused problems with deselecting parents when all children were deselected. 

Fixes : #79942 

https://github.com/godotengine/godot/assets/81252768/821024ee-3cd5-4ea1-9dc5-34bea85a6243

Additionally, tested the bug in the `3.5.2` stable version, where parents are automatically checked if any child is selected, and there is no indeterminate check in that version.

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -247,31 +247,25 @@ void TreeItem::_propagate_check_through_parents(int p_column, bool p_emit_signal
...
-	if (all_unchecked_and_not_indeterminate) {
-		current->set_checked(p_column, false);
-	} else if (any_unchecked_or_indeterminate) {
-		current->set_indeterminate(p_column, true);
-	} else {
-		current->set_checked(p_column, true);
-	}
-
+	current->set_checked(p_column, has_checked && !has_unchecked && !has_indeterminate);
+	current->set_indeterminate(p_column, has_indeterminate || (has_checked && has_unchecked));
```
Comment (AThousandShips) [inline scene/gui/tree.cpp:267]: This logic should be done separately, as the two update each other, setting checked clears indeterminate and vice versa, they are exclusive

File: scene/gui/tree.cpp [hunk 2]
```diff
@@ -247,31 +247,25 @@ void TreeItem::_propagate_check_through_parents(int p_column, bool p_emit_signal
...
 
 	TreeItem *child_item = current->get_first_child();
-	while (child_item) {
-		if (!child_item->is_checked(p_column)) {
-			any_unchecked_or_indeterminate = true;
-			if (child_item->is_indeterminate(p_column)) {
-				all_unchecked_and_not_indeterminate = false;
-				break;
-			}
+	while(child_item) {
```
Comment (AThousandShips) [inline scene/gui/tree.cpp:255]:
```suggestion
	while (child_item) {
```
Code style, the code you replaced was correct already

File: scene/gui/tree.cpp [hunk 3]
```diff
@@ -247,31 +247,25 @@ void TreeItem::_propagate_check_through_parents(int p_column, bool p_emit_signal
 		return;
 	}
 
-	bool all_unchecked_and_not_indeterminate = true;
-	bool any_unchecked_or_indeterminate = false;
+	bool has_checked = false;
```
Comment (AThousandShips) [inline scene/gui/tree.cpp:250]: I'd keep the naming `any_*`

File: scene/gui/tree.cpp (hunk 1 above)
Comment (Ymanawat) [reply scene/gui/tree.cpp:267]: Okay! will this work?

```
if (any_indeterminate || (any_checked && any_unchecked)){
	current->set_indeterminate(p_column, true);
} else {
	current->set_checked(p_column, any_checked);
}
```

File: scene/gui/tree.cpp (hunk 2 above)
Comment (Ymanawat) [reply scene/gui/tree.cpp:255]: Sorry for this I didn't notice.

File: scene/gui/tree.cpp (hunk 3 above)
Comment (Ymanawat) [reply scene/gui/tree.cpp:250]: May I name them like this:
```
bool any_checked = false;
bool any_unchecked = false;
bool any_indeterminate = false;
```

File: scene/gui/tree.cpp (hunk 1 above)
Comment (AThousandShips) [reply scene/gui/tree.cpp:267]: It should, as the second condition is only entered if `any_indeterminate` is false and `any_checked` and `any_unchecked` are not both true, so the condition should be equivalent.

File: scene/gui/tree.cpp (hunk 3 above)
Comment (AThousandShips) [reply scene/gui/tree.cpp:250]: It's either way, was just suggesting, but I prefer `any` here

File: scene/gui/tree.cpp [hunk 4]
```diff
@@ -247,31 +247,25 @@ void TreeItem::_propagate_check_through_parents(int p_column, bool p_emit_signal
...
-			any_unchecked_or_indeterminate = true;
-			if (child_item->is_indeterminate(p_column)) {
-				all_unchecked_and_not_indeterminate = false;
-				break;
-			}
+	while(child_item) {
+		if (child_item->is_checked(p_column)) {
+			has_checked = true;
+		} else if (child_item->is_indeterminate(p_column)) {
+			has_indeterminate = true;
```
Comment (AThousandShips) [inline scene/gui/tree.cpp:259]:
```suggestion
			any_indeterminate = true;
			break;
```
Finding an indeterminate makes the check only end one way, so we can exit early

File: scene/gui/tree.cpp (hunk 2 above)
Comment (kleonc) [reply scene/gui/tree.cpp:255]: > I didn't notice

@Ymanawat You'd `clang-format` to avoid that. See [Code style guidelines](https://docs.godotengine.org/en/latest/contributing/development/code_style_guidelines.html) for more info (I recommend pre-commit hooks for automatic formatting checking etc., they're mentioned in there).

**Comment by Ymanawat** [comment]
@AThousandShips I've updated the PR, have a look.

File: scene/gui/tree.cpp [hunk 5]
```diff
@@ -247,29 +247,30 @@ void TreeItem::_propagate_check_through_parents(int p_column, bool p_emit_signal
...
-	if (all_unchecked_and_not_indeterminate) {
-		current->set_checked(p_column, false);
-	} else if (any_unchecked_or_indeterminate) {
+	if (any_indeterminate || (any_checked && any_unchecked)) {
 		current->set_indeterminate(p_column, true);
+	} else if (any_checked || any_unchecked) {
+		current->set_checked(p_column, any_checked);
 	} else {
-		current->set_checked(p_column, true);
+		current->set_indeterminate(p_column, false);
```
Comment (AThousandShips) [inline scene/gui/tree.cpp:273]: Is this necessary? This won't happen unless there are no children, what was insufficient with the check you suggested?

Comment (Ymanawat) [reply scene/gui/tree.cpp]: Fixed! I encountered some problems with my local build, but after rebuilding it, everything is working as expected.

**Comment by KoBeWi** [comment]
I tested the newest version of this PR and it doesn't fix the issue.

File: scene/gui/tree.cpp [hunk 6]
```diff
@@ -247,31 +247,33 @@ void TreeItem::_propagate_check_through_parents(int p_column, bool p_emit_signal
...
 		}
 		child_item = child_item->get_next();
 	}
 
-	if (all_unchecked_and_not_indeterminate) {
-		current->set_checked(p_column, false);
-	} else if (any_unchecked_or_indeterminate) {
+	if (any_indeterminate || (any_checked && any_unchecked)) {
 		current->set_indeterminate(p_column, true);
+	} else if (current->is_indeterminate(p_column) && any_checked==false){
```
Comment (AThousandShips) [inline scene/gui/tree.cpp:270]:
```suggestion
	} else if (current->is_indeterminate(p_column) && any_checked==false) {
```
See the comment earlier about `clang-format`

**Comment by Ymanawat** [comment]
@KoBeWi @AThousandShips   Actually I've tested the issue then updated the PR, in my local build it was working. 

But I think I found that the issue now : 

https://github.com/godotengine/godot/blob/031aa99d313ceec7cdb8263957d22cae10de0b95/scene/gui/tree.cpp#L186-L188

when the check is already false, set by the set_indeterminate function. I'm passing any_checked which is false in case of no child selected, it won't continue to set the indeterminate to false.

https://github.com/godotengine/godot/blob/031aa99d313ceec7cdb8263957d22cae10de0b95/scene/gui/tree.cpp#L191

I think the changes I made now should fix the issue.

**Review by KoBeWi — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks! And congrats on your first merged Godot PR!
