### PR TITLE
Fix depth draw alpha prepass for shadow

### LINKED ISSUE #12058: Alpha Pre-Pass with transparent material doesn't cast shadows
**OS: macOS 10.12 Sierra, 
Godot version: 3.0.alpha.custom_build.b759d14 
GPU: Intel Iris 6100**

**I want to make a shadow from 3d sprite:**
I've tried to make this with Alpha Pre-pass of depth draw mode with custom material and get this

**Steps to reproduce:**
Just try to add sprite3d with custom material or open example project

**Link to minimal example project:**
[thibronepa1.zip](https://github.com/godotengine/godot/files/1380562/thibronepa1.zip)

### PR DESCRIPTION
**Pull request by hi-ogawa**
I added one simple condition so that `DEPTH_DRAW_ALPHA_PREPASS` will cast shadow when shader uses alpha (`uses_alpha`).
This will fix https://github.com/godotengine/godot/issues/12058

Here is a screenshot of the example scene from the issue:

alpha_cast_shadow

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by djrm** [comment]
works really nice, 👍

File: drivers/gles3/rasterizer_storage_gles3.cpp [hunk 1]
```diff
@@ -2430,7 +2430,9 @@ void RasterizerStorageGLES3::_update_material(Material *material) {
 
 		if (material->shader && material->shader->mode == VS::SHADER_SPATIAL) {
 
-			if (!material->shader->spatial.uses_alpha && material->shader->spatial.blend_mode == Shader::Spatial::BLEND_MODE_MIX) {
+			Shader::Spatial spatial = material->shader->spatial;
```
Comment (reduz) [inline drivers/gles3/rasterizer_storage_gles3.cpp]: Assigning the whole struct for just a comparison seems a little overkill
