### PR TITLE
Fix seed not randomizing for particles. Fix seed being stored when fixed seed is off

### LINKED ISSUE #102182: `GPUParticles2D` not random
### Tested versions

- Reproducible in current master [ee4acfbfbf15b3528c34a8d4f65d66097e636044], 4.4-beta2
- Not reproducible in 4.4-beta1

### System information

Godot v4.4.beta.mono (3979c174e) - Ubuntu 24.04.1 LTS 24.04 on Wayland - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - integrated AMD Radeon Graphics (RADV RENOIR) - AMD Ryzen 7 5800H with Radeon Graphics (16 threads)

### Issue description

`GPUParticles2D` spawn always in the same 'pattern', even when ranges are set (e.g., initial velocity or spread). It's as if they use a fixed seed. 
This also applies to one-shot emitters.

### Steps to reproduce

In the mrp there are two `GPUParticles2D` nodes that spawn one particle with a initial velocity of 50 - 100 and a spread of 180. When run, both nodes always emit the same particles as each other.

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/18601098/mrp.zip)

### PR DESCRIPTION
**Pull request by QbieShay**
Fixes https://github.com/godotengine/godot/issues/102182

### CODE REVIEW

File: scene/2d/gpu_particles_2d.cpp [hunk 1]
```diff
@@ -910,10 +910,14 @@ GPUParticles2D::GPUParticles2D() {
 	RS::get_singleton()->particles_set_draw_pass_mesh(particles, 0, mesh);
 
 	one_shot = false; // Needed so that set_emitting doesn't access uninitialized values
+	// This is a bit tricky but we have to set only the seed here and not uset set_seed()
+	// Otherwise particles won't randomize on their first appearance and will all look the same.
+	// We don't want to use set_seed(randf) because that will affect the docs.
```
Comment (akien-mga) [inline scene/2d/gpu_particles_2d.cpp:915]: You can use `ADD_PROPERTY_DEFAULT` for the docs to force a fixed value (e.g. 0) and avoid having to do hacks.

Comment (QbieShay) [reply scene/2d/gpu_particles_2d.cpp]: Done!

File: scene/2d/cpu_particles_2d.cpp [hunk 2]
```diff
@@ -1561,6 +1563,7 @@ CPUParticles2D::CPUParticles2D() {
 	set_emitting(true);
 	set_amount(8);
 	set_use_local_coordinates(false);
+	set_seed(Math::rand());
```
Comment (AThousandShips) [inline scene/2d/cpu_particles_2d.cpp:1566]: Calling `set_seed` instead of assigning `seed` directly will mean the seed generated in the editor will be saved, or should, this might not be desired

**Comment by KoBeWi** [comment]
When you enable fixed seed, you will be greeted with the randomly generated one:

https://github.com/user-attachments/assets/415057cc-f284-4c43-8076-1fcc6511dbd6

If it's not intended then you could reset the seed when `use_fixed_seed` is being enabled.

File: scene/2d/cpu_particles_2d.cpp [hunk 3]
```diff
@@ -597,7 +597,7 @@ void CPUParticles2D::_validate_property(PropertyInfo &p_property) const {
 	}
 
 	if (p_property.name == "seed" && !use_fixed_seed) {
```
Comment (KoBeWi) [inline scene/2d/cpu_particles_2d.cpp:599]: Unrelated now, but it's better like this.
```suggestion
	if (!use_fixed_seed && p_property.name == "seed") {
```

**Review by KoBeWi — APPROVED** [review]

**Review by AThousandShips — APPROVED** [review]
Fixes the problem for `GPUParticles2D`, and seed isn't stored in the file, and already stored seeds are respected

Didn't test other nodes

**Comment by AThousandShips** [comment]
> If it's not intended then you could reset the seed when use_fixed_seed is being enabled.

This would reset a manually assigned one when toggling it off and on, so think having a random seed when enabling it from scratch is worth not erasing it each time

File: scene/2d/cpu_particles_2d.cpp (hunk 2 above)
Comment (QbieShay) [reply scene/2d/cpu_particles_2d.cpp:1566]: It's marked with property hint none when fixed seed is off, so shouldnt be a problem

**Comment by QbieShay** [comment]
> When you enable fixed seed, you will be greeted with the randomly generated one:

This is by design! That way if you see a combination you like when testing, you can freeze the random seed.

**Comment by akien-mga** [comment]
Thanks!
