### PR TITLE
Fix immersive mode and virtual keyboard height issue on Android

### LINKED ISSUE #86663: Virtual keyboard height is wrong when making navigation bar permanently visible
### Tested versions

4.2 (betas and devs), 4.2, 4.2.1, 4.3 dev1

### System information

Editor on MacOS, exporting for Android

### Issue description

The keyboard height gets calculated wrong when using specific system UI flags on android which cause the navigation bar to be visible all the time. 
It seems like the virtual keyboard height gets added to the navigation bar height which i set as permanent in a flag.
Didnt find a workaround, spent already too much time trying to.
I hope the devs fix this in the next version

This only happens on android 11+, I have one phone on which this does not happen

Here are a few screenshots from a minimal reproduction project i made:

https://github.com/godotengine/godot/assets/144027730/ddc72c1b-0c04-427e-96a3-64f5c01c44a1
Screenshot_20231231_134936_NavigationBarProblem
Screenshot_20231231_134929_NavigationBarProblem

### Steps to reproduce

Make a minimal project which needs the height of the virtual keyboard in android
Use these themes.xml, androidmanifest.xml and GodotApp.java files to properly style the app
[Archive.zip](https://github.com/godotengine/godot/files/13801011/Archive.zip)

Expand the keyboard
You will see a gap of the size of the navigation bar (if activated)

This only happens on android 11+, I have one phone on which this does not happen

### Minimal reproduction project (MRP)

[NavigationBarProblem.zip](https://github.com/godotengine/godot/files/13801018/NavigationBarProblem.zip)
[Archive.zip](https://github.com/godotengine/godot/files/13801019/Archive.zip)

The Archive.zip contains the GodotApp.java, themes.xml and AndroidManifest.xml which you have to insert in the android export template accordingly because i couldn't upload the project with that export template installed (too much space)

### PR DESCRIPTION
**Pull request by syntaxerror247**
Fixes https://github.com/godotengine/godot/issues/86663

This PR fixes the incorrect virtual keyboard height issue and adds support on API 29 and older.
Fixes all the known immersive and edge-to-edge mode issues.

### CODE REVIEW

**Comment by Calinou** [comment]
@kilojool Can you [test](https://docs.godotengine.org/en/stable/contributing/workflow/testing_pull_requests.html) this PR locally to see if it resolves the issue?

**Comment by llama-nl** [comment]
Tested the on Android 15. I am not seeing any difference:

Screenshot_20250705_091640
Screenshot_20250705_091600

**Comment by syntaxerror247** [comment]
@llama-nl It might not work on embedded window. Can you test with exported project, or try disabling embedded window and with gamebar hidden.

**Comment by llama-nl** [comment]
@syntaxerror247 ok, it works in protrait mode. I think it doesn't working in landscape mode? 
Screenshot_20250705_103759

**Comment by syntaxerror247** [comment]
> @syntaxerror247 ok, it works in protrait mode. I think it doesn't working in landscape mode? Screenshot_20250705_103759

That's an issue with the MRP project. Stretch mode is set to `canvas_item`, which scales the viewport (as seen in landscape). But the keyboard height is not scaled, it's in physical pixels.

To fix this, either set stretch mode to `disabled`, or divide the keyboard height by the scale 
```
size.y = get_viewport_rect().size.y - (DisplayServer.virtual_keyboard_get_height() / get_viewport_transform().get_scale().y)
```

**Comment by kilojool** [comment]
It works great on Android 12 for me, but on Android 9 it always returns 0 regardless if the keyboard is visible or not.

**Comment by syntaxerror247** [comment]
> It works great on Android 12 for me, but on Android 9 it always returns 0 regardless if the keyboard is visible or not.

@kilojool The method used to calculate the virtual keyboard height is only available on Android 11 and above. I’ve now added support for older versions as well. Could you please test it again and let me know if it works now?

File: platform/android/java/lib/src/org/godotengine/godot/Godot.kt [hunk 1]
```diff
@@ -521,41 +522,78 @@ class Godot private constructor(val context: Context) {
...
+
+							// Update keyboard height based on IME animation.
+							if (imeAnimation != null) {
+								val interpolatedFraction = imeAnimation.interpolatedFraction
+								// Linear interpolation between start and end values.
+								val keyboardHeight =
+									startBottom * (1.0f - interpolatedFraction) + endBottom * interpolatedFraction
+								val finalHeight = maxOf(keyboardHeight.toInt() - topView.rootView.paddingBottom, 0)
+						GodotLib.setVirtualKeyboardHeight(finalHeight)
+								GodotLib.setVirtualKeyboardHeight(finalHeight)
```
Comment (Alex2782) [inline platform/android/java/lib/src/org/godotengine/godot/Godot.kt]:
```suggestion
								GodotLib.setVirtualKeyboardHeight(finalHeight)
```

**Review by Alex2782 — CHANGES_REQUESTED** [review]

**Comment by kilojool** [comment]
@syntaxerror247 Yes, that fixed it for me on Android 9 also! Nice work! =D

File: platform/android/java/lib/src/org/godotengine/godot/Godot.kt (hunk 1 above)
Comment (syntaxerror247) [reply platform/android/java/lib/src/org/godotengine/godot/Godot.kt]: Thanks for spotting that. It must’ve caused while merging commits.

File: platform/android/java/lib/src/org/godotengine/godot/Godot.kt [hunk 2]
```diff
@@ -521,41 +522,72 @@ class Godot private constructor(val context: Context) {
...
+					override fun onGlobalLayout() {
+						val rect = Rect()
+						rootView.getWindowVisibleDisplayFrame(rect)
+						val screenHeight = rootView.height
+						val diff = screenHeight - rect.height()
+						val keyboardHeight = diff - rootView.paddingBottom - rootView.paddingTop
+
+						if (keyboardHeight != lastHeight) {
+							lastHeight = keyboardHeight
+							if (keyboardHeight > screenHeight * 0.15) {
```
Comment (Alex2782) [inline platform/android/java/lib/src/org/godotengine/godot/Godot.kt]: `screenHeight * 0.15` 

What exactly is being calculated here? I've often seen other places where something has been hard-coded, usually not correctly on every display size and resolution.

example: https://github.com/godotengine/godot/issues/83743#issuecomment-2923389966

Comment (syntaxerror247) [reply platform/android/java/lib/src/org/godotengine/godot/Godot.kt]: It’s a workaround to estimate whether the keyboard is visible. If the height difference exceeds 15% of the screen height, we assume the keyboard is being shown.

The 15% threshold is an empirical value, not exact, but chosen because the keyboard typically covers much more than that. It helps avoid false positives caused by minor layout changes or system UI elements like the navigation bar.

Comment (syntaxerror247) [reply platform/android/java/lib/src/org/godotengine/godot/Godot.kt]: I couldn’t find a more reliable solution than this.

Comment (Alex2782) [reply platform/android/java/lib/src/org/godotengine/godot/Godot.kt]: I'll try to find time tomorrow to test it thoroughly on different devices. I think we need to read the `density`, which is also necessary for other functions.

- `density`: https://developer.android.com/reference/android/util/DisplayMetrics#density
- or `densityDpi`: https://developer.android.com/reference/android/util/DisplayMetrics#densityDpi

Comment (Alex2782) [reply platform/android/java/lib/src/org/godotengine/godot/Godot.kt]: > It helps avoid false positives caused by minor layout changes or system UI elements like the navigation bar.

Yes, that's true. There are many differences depending on the virtual keyboard app installed (Samsung / Google). I'm trying to do some research on that, too.

Comment (syntaxerror247) [reply platform/android/java/lib/src/org/godotengine/godot/Godot.kt]: I don’t think we need `density` in this case since we're using a percentage of the screen height instead of hardcoded pixel values. This should be consistant accross devices.

> I'll try to find time tomorrow to test it thoroughly on different devices.

Okay!

**Review by Alex2782 — APPROVED** [review]
Test project: [NavigationBarProblem.zip](https://github.com/user-attachments/files/21105933/NavigationBarProblem.zip)

Tested on Samsung Tab S7 (Android 13) and LG Nexus 5X (Android 8)

I had to modify MRP, disable Gradle build _(Godot 4.3 custom mods, probably no longer compatible)_, and take scaling into account.

```gdscript
func _process(_delta):
	#https://github.com/godotengine/godot/issues/86663#issuecomment-2132230189
	var keyboard_height := DisplayServer.virtual_keyboard_get_height()
	self.size.y = get_viewport_rect().size.y - (keyboard_height / get_viewport_transform().get_scale().y)

```

----------------

On the LG Nexus 5X (Android 8), there are problems when Immersive mode is enabled. As soon as the keyboard appears, Immersive mode is exited. Probably OS specific. On Samsung Tab S7 (Android 13), I couldn't find any issues.

<details><summary> Video: Issues / Test LG Nexus 5X, Immersive mode + Edge To Edge </summary>

https://github.com/user-attachments/assets/6277beee-df27-40b2-8936-18558bef982d

</details>

Input field is suddenly behind the navigation bar when the keyboard is hidden again.

**Comment by syntaxerror247** [comment]
> On the LG Nexus 5X (Android 8), there are problems when Immersive mode is enabled. As soon as the keyboard appears, Immersive mode is exited. Probably OS specific. On Samsung Tab S7 (Android 13), I couldn't find any issues.
> 
> Video: Issues / Test LG Nexus 5X, Immersive mode + Edge To Edge
> Input field is suddenly behind the navigation bar when the keyboard is hidden again.

I also noticed issues with immersive/edge-to-edge mode on android 9 (emulator), I'm looking into it.

**Review by Alex2782 — COMMENTED** [review]
It works better than before on Nexus 5X Android 8, in `Immersive Mode`.

However, if `Immersive Mode` is disabled and `Edge to Edge` is enabled, the input field behind the navigation bar disappears. Partially on the Samsung Tab S7, and completely on the Nexus 5X.


<details><summary>Screenshots</summary>

image

### Samsung Tab S7 (Android 13)

image

Bildschirmfoto 2025-07-09 um 23 25 16

-----------------

### Google Nexus 5X (Android 8)

image

image



</details>

**Comment by Alex2782** [comment]
Test project: [NavigationBarProblem.zip](https://github.com/user-attachments/files/21105933/NavigationBarProblem.zip)


`DisplayServer.virtual_keyboard_get_height()` 

Now the function returns 0 (Android 8) if `Immersive Mode` is disabled.
Only the first time the keyboard is displayed `height` = 0, the second time it works.

image

**Review by Alex2782 — CHANGES_REQUESTED** [review]
See above. 

Can you reproduce it? Otherwise, I'll check it more closely on my device later.

**Comment by syntaxerror247** [comment]
> However, if Immersive Mode is disabled and Edge to Edge is enabled, the input field behind the navigation bar disappears. Partially on the Samsung Tab S7, and completely on the Nexus 5X.

That's an exected behaviour. App shouldn't place any interactable node at bottom, if using edge-to-edge mode.

**Comment by syntaxerror247** [comment]
> DisplayServer.virtual_keyboard_get_height()
>
> Now the function returns 0 (Android 8) if Immersive Mode is disabled.
> Only the first time the keyboard is displayed height = 0, the second time it works.

Yes, I can reproduce this on an Android 7 emulator (not reproducible on Android 9; I haven't tested on 8).
The `WindowInsetsAnimationCallback` doesn’t get triggered the first time the keyboard opens. I looked into it but couldn’t find anything. Initially, I suspected it might be an emulator bug, but since it can be reproduced on a physical device as well, it's likely a bug in the API itself.

We have two possible solutions:
1. Revert to my previous approach using `OnGlobalLayoutListener` for Android 7 and 8.

2. Document this behavior: the keyboard height is not returned the first time the keyboard opens for non-immersive mode on Android 7 and 8.

**Comment by Alex2782** [comment]
> We have two possible solutions:
> 
> 1. Revert to my previous approach using `OnGlobalLayoutListener` for Android 7 and 8.
> 2. Document this behavior: the keyboard height is not returned the first time the keyboard opens for non-immersive mode on Android 7 and 8.

@m4gr3d What do you think? 

[previous approach](https://github.com/godotengine/godot/compare/63aacd5e1e1fe657b7602c51e272381c5e372881..80cce84f50d4ba0e6882649c4f5d9b3517b7231d) _( `OnGlobalLayoutListener` for Android 7 + 8)_

Only about **0.01%** of users _(PlayStore Stats for Godot Android Editor)_
In my opinion, this workaround code isn't worth it _(for non-immersive mode apps)._

image

**Comment by Alex2782** [comment]
> Document this behavior: the keyboard height is not returned the first time the keyboard opens for non-immersive mode on Android 7 and 8.

Should we document this first? Then see how many people will request support for versions 7 and 8.

**Comment by syntaxerror247** [comment]
I tried a few more workarounds, but none of them worked. The only way to make it work the first time (on Android 7 and 8) is to briefly toggle immersive mode on and off.
I’ve documented this behavior.

Edit: Just to be clear, using `OnGlobalLayoutListener` works but I'm avoiding it as it causes mis-calculation in immersive mode and then we'd have to do workaround for that :)

**Review by Alex2782 — APPROVED** [review]
[NavigationBarProblem.zip](https://github.com/user-attachments/files/21268180/NavigationBarProblem.zip)

It looks good on Android 13 (Samsung Tab S7). However, I had to modify the test project to make it work with every possible combination. 

<details><summary>A hack/workaround for `edge-to-edge` (without immersive). </summary>

```gdscript
func _process(_delta):
	var safe_area := DisplayServer.get_display_safe_area()
	var edge_height = DisplayServer.window_get_size().y - safe_area.size.y - safe_area.position.y
	
	#https://github.com/godotengine/godot/issues/86663#issuecomment-2132230189
	var keyboard_height := DisplayServer.virtual_keyboard_get_height()
	if keyboard_height == 0:
		keyboard_height += edge_height
	var scale_y := get_viewport_transform().get_scale().y 
	self.size.y = get_viewport_rect().size.y - (keyboard_height / scale_y)

```

</details>

I think this hack wasn't necessary in the first version a week ago.
But we can get feedback first and see later if we can optimize it further.
The most important thing is that the input field is not hidden behind the navigation bar.

--------------

<details><summary>Tests on Android 13 (Samsung OS / Keyboard)</summary>


https://github.com/user-attachments/assets/7ea55f83-d0bb-4862-9b01-e5cd1d798929


https://github.com/user-attachments/assets/4ee25c1d-1950-40c1-8807-1d8e780a5d32


</details>

------------------

<details><summary>Tests on Android 8.1 (Google OS / Keyboard)</summary>



Note here `safe_area` is determined differently than under Samsung Android 13, because of the hack/workaround the initial state is wrong (without keyboard)

https://github.com/user-attachments/assets/5ce5cf6c-1643-4e2f-8270-26f0312c59c8


https://github.com/user-attachments/assets/56b5d13b-d795-498b-9c6b-b7d2e34a8794




</details>

**Comment by syntaxerror247** [comment]
> I think this hack wasn't necessary in the first version a week ago.
But we can get feedback first and see later if we can optimize it further.
The most important thing is that the input field is not hidden behind the navigation bar.

That's actually the expected behavior when using edge-to-edge (https://developer.android.com/design/ui/mobile/guides/layout-and-content/edge-to-edge). Interactive elements shouldn’t be placed at the very edge of the screen, as they can end up under system bars. There's nothing we can do about that, it’s just how it's designed to work. The correct approach is to use the safe area `DisplayServer.get_display_safe_area()`.

**Comment by Repiteo** [comment]
Thanks!
