### PR TITLE
`ColorPicker` remove unused children and fix sample bugs.

### LINKED ISSUE #88073: Pressing the `ColorPicker`'s sample left half side changes the color to black when old color is not displayed.
### Tested versions

4.2.1 stable

### System information

Windows 10

### Issue description

Pressing the `ColorPicker`'s sample left half side changes the color to black when old color is not displayed.

### Steps to reproduce

Add a `ColorPicker` node to the scene, and run the game, then left click the left half side of the color sample.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by WhalesState**
* Fixes: https://github.com/godotengine/godot/issues/88073

Remove an unused `VBoxContainer`.
Remove a redundant `VBoxContainer` and add it's children directly to main vbox.
Remove 3 unused children from grid (Label, Slider, SpinBox).
Fix current color overbright position.
Added color mode buttons and sliders to a another `VBoxContainer` to hide both when `sliders_visible` is false.
Use `tab_hovered` instead of `tab_pressed` when hovering a mode button.

### CODE REVIEW

**Comment by KoBeWi** [comment]
Pretty sure changing base type breaks compatibility, which is why the redundant VBoxContainer had to exist.

**Comment by WhalesState** [comment]
> Pretty sure changing base type breaks compatibility, which is why the redundant VBoxContainer had to exist.

What is the use case of the `MarginContainer` ? if for the color button popup, then why don't we include the margins inside the popup's panel ?

**Comment by WhalesState** [comment]
Reverted the base class to `VBoxContainer` again, it's easier to be reviewed now.

**Comment by KoBeWi** [comment]
> What is the use case of the MarginContainer?

The use case is that ColorPicker doesn't need to be used with popup. It's a stand-alone node, ColorPickerButton only wraps it.
The container was added in #78468

**Comment by WhalesState** [comment]
Check the title, should i open a new issue for each fix to track them?

File: scene/gui/color_picker.cpp [hunk 1]
```diff
@@ -1258,13 +1258,15 @@ void ColorPicker::_update_text_value() {
...
 
 void ColorPicker::_sample_input(const Ref<InputEvent> &p_event) {
-	const Ref<InputEventMouseButton> mb = p_event;
-	if (mb.is_valid() && mb->is_pressed() && mb->get_button_index() == MouseButton::LEFT) {
-		const Rect2 rect_old = Rect2(Point2(), Size2(sample->get_size().width * 0.5, sample->get_size().height * 0.95));
-		if (rect_old.has_point(mb->get_position())) {
-			// Revert to the old color when left-clicking the old color sample.
-			set_pick_color(old_color);
-			emit_signal(SNAME("color_changed"), color);
+	if (display_old_color) {
```
Comment (KoBeWi) [inline scene/gui/color_picker.cpp:1261]:
```suggestion
	if (!display_old_color) {
		return;
	}
```
Less nesting and less changes.

File: scene/gui/color_picker.cpp [hunk 2]
```diff
@@ -2234,8 +2236,11 @@ ColorPicker::ColorPicker() {
 	add_mode(new ColorModeRAW(this));
 	add_mode(new ColorModeOKHSL(this));
 
+	sliders_vbox = memnew(VBoxContainer);
+	real_vbox->add_child(sliders_vbox);
+
 	mode_hbc = memnew(HBoxContainer);
-	real_vbox->add_child(mode_hbc);
+	sliders_vbox->add_child(mode_hbc);
```
Comment (KoBeWi) [inline scene/gui/color_picker.cpp:2243]: This changes the behavior of `sliders_visible` to also hide color modes. Why this change?
I know color modes are *probably* not useful without sliders, but they are still 2 separate properties.

**Comment by KoBeWi** [comment]
There is a behavior change, which is questionable. Everything else looks fine.

File: scene/gui/color_picker.cpp [hunk 3]
```diff
@@ -2177,7 +2179,7 @@ void ColorPicker::_bind_methods() {
 
 	BIND_THEME_ITEM_EXT(Theme::DATA_TYPE_STYLEBOX, ColorPicker, mode_button_normal, "tab_unselected", "TabContainer");
 	BIND_THEME_ITEM_EXT(Theme::DATA_TYPE_STYLEBOX, ColorPicker, mode_button_pressed, "tab_selected", "TabContainer");
-	BIND_THEME_ITEM_EXT(Theme::DATA_TYPE_STYLEBOX, ColorPicker, mode_button_hover, "tab_selected", "TabContainer");
+	BIND_THEME_ITEM_EXT(Theme::DATA_TYPE_STYLEBOX, ColorPicker, mode_button_hover, "tab_hovered", "TabContainer");
```
Comment (KoBeWi) [inline scene/gui/color_picker.cpp:2182]: Not important, but this style has visible borders at sides:
image

Comment (WhalesState) [reply scene/gui/color_picker.cpp:2182]: Also the `tab_unselected` has the same left and right borders but it's less visible, was thinking about removing those borders but less visible.

They are clear here.
image

**Comment by WhalesState** [comment]
Applied all the suggestions.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
