### PR TITLE
Remove size restriction for mouse cursor

### LINKED ISSUE #17992: Custom mouse cursor is limited to 32x32
**Godot version:** 3.0.2

**OS/device including version:** Windows 10

**Issue description:** `set_custom_mouse_cursor` doesn't work. Either via GDScript or from the project settings. It still shows the system's cursor instead.

**Steps to reproduce:**
1. Try to set a custom mouse cursor

### PR DESCRIPTION
**Pull request by guilhermefelipecgs**
Fix #17992

I put a limit of 256x256 because on my linux machine any size bigger than this starts to flicker.

I think 256px is it enough for a cursor, right?

Tested on Win10 and Linux, dunno what will happen in other windows versions.
Mac is probably working, I'm without a virtual machine to test right now.

### CODE REVIEW

File: platform/windows/os_windows.cpp [hunk 1]
```diff
@@ -1896,28 +1896,26 @@ void OS_Windows::set_custom_mouse_cursor(const RES &p_cursor, CursorShape p_shap
...
 
 		// Create the BITMAP with alpha channel
 		COLORREF *buffer = (COLORREF *)malloc(sizeof(COLORREF) * image_size);
 
 		image->lock();
 		for (UINT index = 0; index < image_size; index++) {
-			int column_index = floor(index / 32);
-			int row_index = index % 32;
+			int column_index = floor(index / texture->get_width());
+			int row_index = index % texture->get_width();
```
Comment (akien-mga) [inline platform/windows/os_windows.cpp]: Shouldn't it be `get_height()` for the row index?

File: platform/x11/os_x11.cpp [hunk 2]
```diff
@@ -2393,8 +2393,8 @@ void OS_X11::set_custom_mouse_cursor(const RES &p_cursor, CursorShape p_shape, c
 		image->lock();
 
 		for (XcursorPixel index = 0; index < image_size; index++) {
-			int column_index = floor(index / 32);
-			int row_index = index % 32;
+			int column_index = floor(index / texture->get_width());
+			int row_index = index % texture->get_width();
```
Comment (akien-mga) [inline platform/x11/os_x11.cpp]: Same here.

File: platform/windows/os_windows.cpp (hunk 1 above)
Comment (guilhermefelipecgs) [reply platform/windows/os_windows.cpp]: No, this is exactly what I want.

Comment (guilhermefelipecgs) [reply platform/windows/os_windows.cpp]: Because the index is a range of [0..(width x height)], when this formula is applied, everything works fine.

Comment (akien-mga) [reply platform/windows/os_windows.cpp]: Then shouldn't the column index use `texture->get_height()`?

Comment (akien-mga) [reply platform/windows/os_windows.cpp]: Nevermind, it's correct :)

Comment (akien-mga) [reply platform/windows/os_windows.cpp]: Actually... `index` is the pixel position from top to bottom and then left to right, is that correct?

So let's say I have a 5x3 (WxH) sprite and index 12, it would give: `column_index == 2` and `row_index == 2`, when it should be column 4 (divided by height) and row 0 (modulo height), no?
image

Comment (guilhermefelipecgs) [reply platform/windows/os_windows.cpp]: I renamed row and column index.

With a image 5x3, this is the results (This result I get with an example I made and putting printf on code):
```
r=0, c=0
r=0, c=1
r=0, c=2
r=0, c=3
r=0, c=4
r=1, c=0
r=1, c=1
r=1, c=2
r=1, c=3
r=1, c=4
r=2, c=0
r=2, c=1
r=2, c=2
r=2, c=3
r=2, c=4
```

Comment (guilhermefelipecgs) [reply platform/windows/os_windows.cpp]: > So let's say I have a 5x3 (WxH) sprite and index 12, it would give: column_index == 2 and row_index == 2, when it should be column 4 (divided by height) and row 0 (modulo height), no?

No, the correct is row=2 and column=2, this will be passed to ```get_pixel(x, y)``` function.

Comment (akien-mga) [reply platform/windows/os_windows.cpp]: Thanks for the clarification :)

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we don't plan to cherry-pick new features and enhancements to the 3.0 branch, unless there is very strong support in favor of it. Removing cherrypick label for 3.0.
