### PR TITLE
[3.x] Fix RichTextLabel auto-wrapping on CJK texts

### LINKED ISSUE #21482: RichTextLabel auto-wrapping on chinese
**Godot version:**
v3.0.6

**OS/device including version:**
Archlinux

**Issue description:**
I'm getting different behaviors on Label and RichTextLabel regarding auto-wrapping and spacing.
image

This is the output I'm getting, as you can see the RTL isn't handling it the same way. This is caused by the space that follows the hyphen.

There's no difference when RTL bbcode is enabled.

I've found #3081 which marks #1848 as done, but I'm not sure it's the same issue.

**Steps to reproduce:**
Add a RichTextLabel to your scene and set this text: `- 你是个乐观主义者，你制定的计划永远会关注产出和利益，不过也千万记得关注风险与劣势，这样才能让你提高成功几率;`

**Minimal reproduction project:**
There's an official RichTextLabel demo that could be used as a playground.

Edit: As a workaround I've found that with other [whitespace characters](https://en.wikipedia.org/wiki/Whitespace_character#Unicode) this isn't happening. For example with: `U+2002`.

### PR DESCRIPTION
**Pull request by timothyqiu**
This PR fixes #21482.

There is still 1 px difference between when they wrap the last character after this fix. This is becauses `Label` autowraps if the text chunk width >= frame width, while `RichTextLabel` autowraps if text chunk width > frame width. I think this is not related to the original issue and worth a dedicated PR if desired.

Complex Text Layout on the `master` branch is the proper way to solve the wrapping problem, but it seems that it won't be backported.

This PR also supersedes #45290. I also added a fix to solve the issue mentioned in https://github.com/godotengine/godot/pull/45290#issuecomment-762410458, allowing word breaking on CJK and non-CJK edge. I'll revert this additional fix if it should be a separate PR.

---

Before:  (there is unexpected linebreak after "Hopefully, ", and "should" wraps after "sh")
before

After:
after

### CODE REVIEW

File: scene/gui/rich_text_label.cpp [hunk 1]
```diff
@@ -410,6 +412,18 @@ int RichTextLabel::_process_line(ItemFrame *p_frame, const Vector2 &p_ofs, int &
 							break; //don't allow lines longer than assigned width
 						}
 
+						// For info about the unicode range, see Label::regenerate_word_cache.
+						const CharType current = c[end];
+						const bool separatable = (current >= 0x2E08 && current <= 0xFAFF) || (current >= 0xFE30 && current <= 0xFE4F);
```
Comment (bruvzg) [inline scene/gui/rich_text_label.cpp:417]: Range probably should start with `2E80` not `2E08` and seems to be too broad (includes Cyrillic, Devanagari extended and other scripts that should not be separable).

Something like `2E80 - 9FCB`, `AC00 - D7FB`, `F900 - FAD9`, `FE30 - FE4F`, `20000 - 2FA1D` (The last range won't work on Windows, but should be supported on any other OS).

Comment (timothyqiu) [reply scene/gui/rich_text_label.cpp:417]: Yeah, I noticed that. Should I change the range used in `Label` too?

Comment (akien-mga) [reply scene/gui/rich_text_label.cpp:417]: Yeah that would make sense.

**Comment by timothyqiu** [comment]
@bruvzg I used a slightly different range than you suggested.

* Ends CJK Unified Ideographs at `9FFF` instead of `9FCB`, the latter is the end of assigned code points as of Unicode 5.2, but expanded to the end of the block in later versions.
* Added `F900 - FAFF`, the [CJK Compatibility Ideographs block](https://en.wikipedia.org/wiki/CJK_Compatibility_Ideographs)
* Added `30000 - 3134F`, the [CJK Unified Ideographs Extension G block](https://en.wikipedia.org/wiki/CJK_Unified_Ideographs_Extension_G)
* Added `FF65 - FF9F` and `FFA0 - FFDC` for halfwidth form of katakana and compatibility jamo

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.3.
