### PR TITLE
GLTF: Make skeleton bone names unique per-skeleton instead of scene-wide

### LINKED ISSUE #93758: Imported models with multiple skeletons can't have same bone names
### Tested versions

Reproducible in 4.3.beta2

### System information

Godot v4.3.beta2 - Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 32.0.15.5599) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 Threads)

### Issue description

When any Blender file or GLTF file (haven't tested others) is imported, if the file contained multiple skeletons, they cannot have bones with the same names as each other. e.g., if a file contained `Skeleton1` and `Skeleton2`, they cannot each have a `Head` bone. One of them gets sanitized by Godot into `Head_2`. The naming sanitation conflict resolution for bones is applied on a file level as opposed to on a skeleton level.

This is a Godot issue, not an issue from the exporting program, because the actual GLTF file contains the correct bone names.

### Steps to reproduce

- Open up the attached project's `test.tscn`, and inspect each imported skeleton. Note that one of them has incorrectly renamed bones suffixed with `_2`.
- Now open up the GLTF file in a text editor. Note that the bones in each skeleton are correct.

### Minimal reproduction project (MRP)

[bug-report.zip](https://github.com/user-attachments/files/16042021/bug-report.zip)

### LINKED ISSUE #96248: Godot's GLB Importer in MacOSX adds "_2" suffix randomly to bone names, it doesn't in Windows
### Tested versions

Did it in 4.3 in MacOSX

### System information

MacOSX - Godot 4.3

### Issue description

Needed to open my project in MacOSX so I can export my project for iOS. Turns out many instances of my code's Skeleton3D.find_bone() didn't work, because, in MacOSX, the importer randomly added the "_2" in some bones while Windows didn't.

Keep in mind that this happened throughout a lot of crashes while I was importing the whole project.

### Steps to reproduce

Open a project with .glb with Skeletons and bones files in Windows, then try to open it in MacOSX.

### Minimal reproduction project (MRP)

Here's is my project with two .glb files that were culprits of this. I think they both do the "_2" for different reasons.
[glbimporterexample.zip](https://github.com/user-attachments/files/16789120/glbimporterexample.zip)

I got the inherited scene of the .glb from the project that crashed a bunch of times while importing.

### LINKED ISSUE #106073: Godot 4.3 and 4.4 model importer renames skeleton bones, breaking animation retargeting and bone map support
### Tested versions

- Reproducible in Godot 4.3.0 up to 4.4.1 (newest current version)
- Not reproducible in Godot 4.2.2

### System information

Windows 10, Godot 4.2.2 / 4.3.0 / 4.4.1

### Issue description

I have a library of character models stored as a single GLB file.
The characters have similar but not always identical humanoid skeletons.
I have created bone maps for the humanoid characters but some extra bones remain unmapped.
Since Godot 4.2 all bones in the GLB file are treated as belonging to a single skeleton and duplicate names are silently renamed even though there should be no conflict. The new import feature "Import as Skeleton Bones" is explicitly turned off (default).

This is what the bone names on the second skeleton in the GLB look like in Godot 4.2:
Image

This is what happens to the skeleton bone names if imported into Godot 4.3 or higher:
Image

For the MRP example I donwloaded free assets from here (only the two characters are included here):
https://syntystore.com/products/polygon-starter-pack

### Steps to reproduce

I have attached a tiny Godot 4.2 project to demonstate the issue.
It contains a single GLB file called Humans.glb.
The GLB contains 2 rigged characters. Each character model has its own mesh and skeleton.
There is also a bone map with a humanoid profile included in the project.
This setup work perfectly in Godot 4.2.2.

Try upgrading the project to Godot 4.3 or higher.
The setup no longer works.
Godot now insists that the bones on the second skeleton have different names with the suffix "_2".
It is no longer possible to import the model in Godot. For example the bone "Eyebrows" will always have different names among skeletons, which breaks animation retargeting.
This is a breaking change but if fails silently so I only realized it's happening just now.

In my opinion the problem is caused by  the new feature "Import as Skeleton Bones" which can't be fully disabled even though it's turned off by default.

### Minimal reproduction project (MRP)

[SkeletonBug.zip](https://github.com/user-attachments/files/20027872/SkeletonBug.zip)

### PR DESCRIPTION
**Pull request by aaronfranke**
Fixes #106073, fixes #93758, fixes #96248. This restores the behavior in Godot 4.2 and earlier.

This PR makes the unique name feature no longer apply cross-skeleton. Skeleton bones now need to be unique within the same skeleton and compared to scene nodes, but not compared to all skeletons in the scene node.

This only affects glTF files with multiple skeletons in it, which is a niche use case, so this is low-risk. Users of this feature expect to be able to use the same bone map for each skeleton for animation targeting.

Note: This PR makes it possible to generate multiple nodes with the same name in the case of BoneAttachment3D nodes, since they are given the same name as the bone they are attached to. I think this is fine, and the alternatives are worse.

Note: This PR does not affect export. A comment introduced in PR #53114 indicates the current export behavior of having all glTF nodes including bones be unique was intentional. We could change the export behavior too, though.

~~Note: This PR adds a `duplicate()` function to HashSet, because I needed to duplicate a HashSet.~~

### CODE REVIEW

File: modules/gltf/skin_tool.cpp [hunk 1]
```diff
@@ -563,9 +563,12 @@ Error SkinTool::_create_skeletons(
 		Vector<Ref<GLTFNode>> &nodes,
 		HashMap<ObjectID, GLTFSkeletonIndex> &skeleton3d_to_gltf_skeleton,
 		Vector<Ref<GLTFSkeleton>> &skeletons,
-		HashMap<GLTFNodeIndex, Node *> &scene_nodes) {
+		HashMap<GLTFNodeIndex, Node *> &scene_nodes,
+		int p_naming_version) {
+	HashSet<String> unique_node_names = unique_names.duplicate();
```
Comment (Ivorforce) [inline modules/gltf/skin_tool.cpp]: You can use the copy constructor:

```suggestion
	HashSet<String> unique_node_names(unique_names);
```

This should allow you to avoid modifying `hash_set.h` :)

Comment (aaronfranke) [reply modules/gltf/skin_tool.cpp]: I think an explicit `duplicate()` is clearer, like we already have for Vector<>. But I can remove it if core doesn't want it.

Comment (Ivorforce) [reply modules/gltf/skin_tool.cpp]: It's worth a thought as a general codebase change, but out of scope for the PR.

**Review by fire — APPROVED** [review]
Did not review the code.

Approve of the feature.

File: modules/fbx/fbx_document.cpp [hunk 2]
```diff
@@ -2221,7 +2221,7 @@ Error FBXDocument::_parse_fbx_state(Ref<FBXState> p_state, const String &p_searc
 	ERR_FAIL_COND_V(err != OK, ERR_PARSE_ERROR);
 
 	/* CREATE SKELETONS */
-	err = SkinTool::_create_skeletons(p_state->unique_names, p_state->skins, p_state->nodes, p_state->skeleton3d_to_fbx_skeleton, p_state->skeletons, p_state->scene_nodes);
+	err = SkinTool::_create_skeletons(p_state->unique_names, p_state->skins, p_state->nodes, p_state->skeleton3d_to_fbx_skeleton, p_state->skeletons, p_state->scene_nodes, 2);
```
Comment (lyuma) [inline modules/fbx/fbx_document.cpp]: I hope this `2` doesn't cause a problem... I'm a little worried about arbitrarily changing FBX without compatibility...
 
But it's probably a somewhat rare case, and I don't want to tell you to do unnecessary work for FBX. I guess if this happens, we can tell users who want the unique bone name behavior to switch to FBX2glTF, or if we catch it during beta we can maybe come back here and also implement naming compatibility for FBX

**Review by lyuma — APPROVED** [review]
Seems good for glTF

File: modules/fbx/fbx_document.cpp (hunk 2 above)
Comment (aaronfranke) [reply modules/fbx/fbx_document.cpp]: For FBX, I'm open to anything, I don't have any stakes in it.

I considered making this be like 999 or something to try and pin it to the latest version (just in case something else changes), but I wasn't sure so I figured 2 was a safe bet.

Comment (lyuma) [reply modules/fbx/fbx_document.cpp]: Which number to hardcode isn't exactly my concern. The concern is this is technically as much a compatibility breakage for FBX as it is for GLTF, and the correct thing to do would be to add a FBX Compatibility import setting similar to the gLTF one.

Speaking of which, is there a risk that the .blend importer also has a similar issue, since it is also not a gltf file, but needs the compatibility option?

Comment (aaronfranke) [reply modules/fbx/fbx_document.cpp]: We don't expose the glTF naming version in the `.blend` file import options, so users directly importing `.blend` files always have the latest glTF naming version setting.

Recent fixes like PR #104184 and PR #103332 have the goal of improving compatibility with Blender, so I'm not sure that users would ever want to use older naming versions, it would just mean that the node tree in Godot would be different from the node tree in Blender.

Comment (lyuma) [reply modules/fbx/fbx_document.cpp]: The issue isn't that users *want* the old naming scheme. I don't think anyone would choose the old system by choice... that's the same for gltf, blend or fbx. The issue is that existing projects might have already imported files and users might have extended those scenes or somehow reference data from them in their projects.

For any such users, upon upgrade to 4.5, all of their existing node paths will break, and inherited scenes might just lose data when the referenced nodepaths no longer exist. These users might prefer to keep their projects functional rather than to have the latest bugfixes for node naming. That is why we have the naming compatibility, and that's why it is just as important for FBX and Blend as it is for glTF.

Comment (aaronfranke) [reply modules/fbx/fbx_document.cpp]: Ok: https://github.com/godotengine/godot/pull/107352

**Comment by akien-mga** [comment]
Thanks!

**Comment by dmlary** [comment]
EDIT: There's a config option at the bottom of the import settings under glTF, called Naming Version.  It needs to be set to "Godot 4.5 or later".  I think it preserved the 4.3-4.4 naming when I opened an old project.

This works great, thank you so much! 

~~I was looking for this fix on 4.5-beta1.  It looks like it is present for GLTF import, but bones are still renamed when imported directly from `.blender` files.  Does the blender import path leveraged GLTF behind the scenes?  Is there any way we can get this fix in for `.blender` files too by the 4.5 release?~~
