### PR TITLE
ColorPicker: fix DPI, hue & color update issues

### LINKED ISSUE #9184: Color Picker Bad hiDPI support
**Issue description:**

the color picker top area does not take EDSCALE into account and is sized wrongly when using hiDPI.
HiDpi

screen shot 2017-06-14 at 15 32 55

Normal Dpi
screen shot 2017-06-14 at 15 27 00

### PR DESCRIPTION
**Pull request by ghost**
Fix the following issues:
- Popup is too small on VeryLoDPI
- Scaling on HiDPI (need testing)
- Color not update when dragging sliders
- When dragging UV pick to white or black, hue changes to red (still happens when editing via sliders)

Closes #9184, #9224

### CODE REVIEW

**Comment by vnen** [comment]
This superseeds #9238 if merged. @remorse107 could take a look if this is better or not.

@Noshyaar,  you should mention the issue number on the PR description if you are fixing a reported bug.

**Comment by remorse107** [comment]
I'm trying to fix the eye dropper and the issue with dragging the sliders.  The last_hsv and the color keep equaling when the RGB components are exactly the same so it is not allowing the hue slider to impact the uv edit portion of the color picker.

**Comment by remorse107** [comment]
I'm checking those changes.  If it looks good, I'll just close my PR.

**Comment by remorse107** [comment]
I have checked the changes.  And I think it looks really good now.  The only thing missing now is the eye dropper functionality.  I'm going to close #9238, as these changes are more complete.

File: editor/property_editor.cpp [hunk 1]
```diff
@@ -818,10 +818,12 @@ bool CustomPropertyEditor::edit(Object *p_owner, const String &p_name, Variant::
 				color_picker->connect("color_changed", this, "_color_changed");
 			}
 
+			float upscale = EDSCALE < 1 ? 1 : EDSCALE;
```
Comment (akien-mga) [inline editor/property_editor.cpp]: Why is this needed? Don't we want to support scaling down in VeryLoDPI?

**Comment by toger5** [comment]
It would be nicer if the color palette just gets redrawn on size change and calculates the size based on the rect of color picker. Now you always have to think a bout palett scale to make it work... I also looked into it and could not figure out a straight forward solution for updating with the color picker rect. But if you find one that would be a better implementation.

File: editor/property_editor.cpp (hunk 1 above)
Comment (Noshyaar) [inline editor/property_editor.cpp]: It's there to keep the UV picker's minimum size at 256x256 so that users can pick from 256 different values in VeryLoDPI. If it's not desired, I'll change it to use EDSCALE directly.

**Comment by Noshyaar** [comment]
@toger5 I'll try to implement that first. Please don't merge yet.

**Comment by Noshyaar** [comment]
I've made the pickers resizable and removed palette_scale. Please test on HiDPI and review. Thank you.

**Comment by karroffel** [comment]
@Noshyaar Looks like @MarianoGnu already fixed some of the things you changed, looks like only the dragging and HiDPI issues need solving
