### PR TITLE
Fix some editor crashes

### LINKED ISSUE #29574: Editor crash when using Tabs::get_tab_rect
**Godot version:**
3.2.dev.custom_build. 197b65f32

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f98e6eadf60] (??:0)
[2] CowData<Tabs::Tab>::get(int) const (/home/rafal/Pulpit/godot/./core/cowdata.h:151 (discriminator 7))
[3] Vector<Tabs::Tab>::operator[](int) const (/home/rafal/Pulpit/godot/./core/vector.h:85)
[4] Tabs::get_tab_rect(int) const (/home/rafal/Pulpit/godot/scene/gui/tabs.cpp:895)
[5] MethodBind1RC<Rect2, int>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:1333 (discriminator 8))
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[7] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1071 (discriminator 1))
[8] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1072)
[9] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[10] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[11] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[12] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[13] Control::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/gui/control.h:51 (discriminator 3))
[14] Tabs::_notificationv(int, bool) (/home/rafal/Pulpit/godot/scene/gui/tabs.h:38 (discriminator 3))
[15] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[16] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[17] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[18] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1919)
[19] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3034)
[20] /usr/bin/godot(main+0xdc) [0x138598e] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[21] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f98e6e90b6b] (??:0)
[22] /usr/bin/godot(_start+0x2a) [0x13857fa] (??:?)

```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project
commit a8fb39e50aea10f8793ed09d6b084678204b0b68
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/a8fb39e50aea10f8793ed09d6b084678204b0b68.zip

### LINKED ISSUE #29684: Editor crash when using GridMap::set_cell_item
**Godot version:**
3.2.dev.custom_build. 15425b450
**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f4f7c8c3f60] (??:0)
[2] GridMap::set_cell_item(int, int, int, int, int) (/home/rafal/Pulpit/godot/modules/gridmap/grid_map.cpp:300 (discriminator 2))
[3] GridMap::_recreate_octant_data() (/home/rafal/Pulpit/godot/modules/gridmap/grid_map.cpp:779 (discriminator 2))
[4] GridMap::set_octant_size(int) (/home/rafal/Pulpit/godot/modules/gridmap/grid_map.cpp:246)
[5] MethodBind1<int>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:775 (discriminator 12))
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[7] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1071 (discriminator 1))
[8] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1078)
[9] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[10] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[11] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[12] Spatial::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/3d/spatial.h:58 (discriminator 3))
[13] GridMap::_notificationv(int, bool) (/home/rafal/Pulpit/godot/modules/gridmap/grid_map.h:44 (discriminator 3))
[14] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[15] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[16] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[17] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1919)
[18] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3051)
[19] /usr/bin/godot(main+0xdc) [0x138798e] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[20] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f4f7c8a6b6b] (??:0)
[21] /usr/bin/godot(_start+0x2a) [0x13877fa] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit 330a38184b951634f059c042408c419aba257993
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/330a38184b951634f059c042408c419aba257993.zip

### LINKED ISSUE #29924: Editor crash in Gradient::get_color(int)
**Godot version:**
3.2.dev.custom_build. 974b07fc7

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f7c57796f60] (??:0)
[2] CowData<Gradient::Point>::get(int) const (/home/rafal/Pulpit/godot/./core/cowdata.h:151 (discriminator 7))
[3] Vector<Gradient::Point>::operator[](int) const (/home/rafal/Pulpit/godot/./core/vector.h:85)
[4] Gradient::get_color(int) const (/home/rafal/Pulpit/godot/scene/resources/gradient.cpp:170)
[5] MethodBind1RC<Color, int>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:1333 (discriminator 8))
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[7] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1073 (discriminator 1))
[8] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1080)
[9] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[10] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[11] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[12] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[13] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[14] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[15] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[16] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[17] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1922)
[18] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[19] /usr/bin/godot(main+0xdf) [0x138d871] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[20] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f7c57779b6b] (??:0)
[21] /usr/bin/godot(_start+0x2a) [0x138d6da] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit 7419d41a59119130fe61a498a07ad17d9a377c37
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/7419d41a59119130fe61a498a07ad17d9a377c37.zip

### LINKED ISSUE #29925: Editor crash in Gradient::set_color(int, Color const&)
**Godot version:**
3.2.dev.custom_build. 974b07fc7

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f2c92e1ef60] (??:0)
[2] VectorWriteProxy<Gradient::Point>::operator[](int) (/home/rafal/Pulpit/godot/./core/vector.h:49 (discriminator 7))
[3] Gradient::set_color(int, Color const&) (/home/rafal/Pulpit/godot/scene/resources/gradient.cpp:164)
[4] MethodBind2<int, Color const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:1523 (discriminator 19))
[5] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[6] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1073 (discriminator 1))
[7] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1086)
[8] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[9] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[10] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[11] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[12] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[13] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[14] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[15] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[16] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1922)
[17] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[18] /usr/bin/godot(main+0xdf) [0x138d871] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[19] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f2c92e01b6b] (??:0)
[20] /usr/bin/godot(_start+0x2a) [0x138d6da] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit 3a4f935883278d49ee44bac9fc62b65ca73e557e
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/3a4f935883278d49ee44bac9fc62b65ca73e557e.zip

### LINKED ISSUE #29926: Editor crash in TileSet::tile_get_shape_transform(int, int)
**Godot version:**
3.2.dev.custom_build. 974b07fc7

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f82e9051f60] (??:0)
[2] CowData<TileSet::ShapeData>::get(int) const (/home/rafal/Pulpit/godot/./core/cowdata.h:151 (discriminator 7))
[3] Vector<TileSet::ShapeData>::operator[](int) const (/home/rafal/Pulpit/godot/./core/vector.h:85)
[4] TileSet::tile_get_shape_transform(int, int) const (/home/rafal/Pulpit/godot/scene/resources/tile_set.cpp:750)
[5] MethodBind2RC<Transform2D, int, int>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:2105 (discriminator 13))
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[7] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1073 (discriminator 1))
[8] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1080)
[9] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[10] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[11] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[12] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[13] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[14] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[15] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[16] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[17] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1922)
[18] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[19] /usr/bin/godot(main+0xdf) [0x138d871] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[20] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f82e9034b6b] (??:0)
[21] /usr/bin/godot(_start+0x2a) [0x138d6da] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit b79bafa5873356254415930b4dc27fd6ae78d723
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/b79bafa5873356254415930b4dc27fd6ae78d723.zip

### LINKED ISSUE #29927: Editor crash in Gradient::set_offset(int, float)
**Godot version:**
3.2.dev.custom_build. 974b07fc7

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f010f1fdf60] (??:0)
[2] VectorWriteProxy<Gradient::Point>::operator[](int) (/home/rafal/Pulpit/godot/./core/vector.h:49 (discriminator 7))
[3] Gradient::set_offset(int, float) (/home/rafal/Pulpit/godot/scene/resources/gradient.cpp:148)
[4] MethodBind2<int, float>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:1523 (discriminator 19))
[5] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[6] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1073 (discriminator 1))
[7] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1086)
[8] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[9] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[10] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[11] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[12] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[13] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[14] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[15] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[16] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1922)
[17] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[18] /usr/bin/godot(main+0xdf) [0x138d871] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[19] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f010f1e0b6b] (??:0)
[20] /usr/bin/godot(_start+0x2a) [0x138d6da] (??:?)

```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit df61a78e9471ea6e8f195e5ccc64e3ee22fcde82
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/df61a78e9471ea6e8f195e5ccc64e3ee22fcde82.zip

### LINKED ISSUE #29928: Editor crash in Gradient::get_offset(int)
**Godot version:**
3.2.dev.custom_build. 974b07fc7

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f6ee1534f60] (??:0)
[2] CowData<Gradient::Point>::get(int) const (/home/rafal/Pulpit/godot/./core/cowdata.h:151 (discriminator 7))
[3] Vector<Gradient::Point>::operator[](int) const (/home/rafal/Pulpit/godot/./core/vector.h:85)
[4] Gradient::get_offset(int) const (/home/rafal/Pulpit/godot/scene/resources/gradient.cpp:155)
[5] MethodBind1RC<float, int>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:1333 (discriminator 8))
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[7] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1073 (discriminator 1))
[8] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1080)
[9] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[10] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[11] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[12] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[13] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[14] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[15] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[16] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[17] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1922)
[18] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[19] /usr/bin/godot(main+0xdf) [0x138d871] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[20] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f6ee1517b6b] (??:0)
[21] /usr/bin/godot(_start+0x2a) [0x138d6da] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit 9b5317d025208604737920de6e1c2c230d577a52
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/9b5317d025208604737920de6e1c2c230d577a52.zip

### LINKED ISSUE #29929: Editor crash in TileSet::tile_set_shape_one_way(int, int, bool)
**Godot version:**
3.2.dev.custom_build. 974b07fc7

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f4d4fb74f60] (??:0)
[2] VectorWriteProxy<TileSet::ShapeData>::operator[](int) (/home/rafal/Pulpit/godot/./core/vector.h:49 (discriminator 7))
[3] TileSet::tile_set_shape_one_way(int, int, bool) (/home/rafal/Pulpit/godot/scene/resources/tile_set.cpp:770)
[4] MethodBind3<int, int, bool>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:2303 (discriminator 26))
[5] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[6] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1073 (discriminator 1))
[7] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1086)
[8] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[9] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[10] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[11] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[12] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[13] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[14] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[15] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[16] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1922)
[17] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[18] /usr/bin/godot(main+0xdf) [0x138d871] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[19] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f4d4fb57b6b] (??:0)
[20] /usr/bin/godot(_start+0x2a) [0x138d6da] (??:?)

```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit 7ea1c8595eed454e8ca9be3966159b38951260e3
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/7ea1c8595eed454e8ca9be3966159b38951260e3.zip

### LINKED ISSUE #29931: Editor crash in TileSet::tile_set_shape(int, int, Ref<Shape2D> const&)
**Godot version:**
3.2.dev.custom_build. 974b07fc7

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f6cf70d2f60] (??:0)
[2] VectorWriteProxy<TileSet::ShapeData>::operator[](int) (/home/rafal/Pulpit/godot/./core/vector.h:49 (discriminator 7))
[3] TileSet::tile_set_shape(int, int, Ref<Shape2D> const&) (/home/rafal/Pulpit/godot/scene/resources/tile_set.cpp:723)
[4] MethodBind3<int, int, Ref<Shape2D> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:2303 (discriminator 26))
[5] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[6] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1073 (discriminator 1))
[7] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1086)
[8] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[9] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[10] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[11] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[12] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[13] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[14] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[15] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[16] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1922)
[17] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[18] /usr/bin/godot(main+0xdf) [0x138d871] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[19] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f6cf70b5b6b] (??:0)
[20] /usr/bin/godot(_start+0x2a) [0x138d6da] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit 88e20e175daa90ccca281d5296a17c5a47ad22fd
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/88e20e175daa90ccca281d5296a17c5a47ad22fd.zip

### LINKED ISSUE #29932: Editor crash in TileSet::tile_get_shape(int, int)
**Godot version:**
3.2.dev.custom_build. 974b07fc7

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f5cf4077f60] (??:0)
[2] CowData<TileSet::ShapeData>::get(int) const (/home/rafal/Pulpit/godot/./core/cowdata.h:151 (discriminator 7))
[3] Vector<TileSet::ShapeData>::operator[](int) const (/home/rafal/Pulpit/godot/./core/vector.h:85)
[4] TileSet::tile_get_shape(int, int) const (/home/rafal/Pulpit/godot/scene/resources/tile_set.cpp:732)
[5] MethodBind2RC<Ref<Shape2D>, int, int>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:2105 (discriminator 13))
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[7] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1073 (discriminator 1))
[8] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1080)
[9] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[10] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[11] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[12] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[13] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[14] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[15] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[16] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[17] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1922)
[18] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[19] /usr/bin/godot(main+0xdf) [0x138d871] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[20] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f5cf405ab6b] (??:0)
[21] /usr/bin/godot(_start+0x2a) [0x138d6da] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit ff73254afc2a04103dfd577961fbf2541e4586aa
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/ff73254afc2a04103dfd577961fbf2541e4586aa.zip

### PR DESCRIPTION
**Pull request by qarmin**
Fixes #29924
Fixes #29925
Fixes #29926
Fixes #29927 
Fixes #29928 
Fixes #29929 
Fixes #29931 
Fixes #29932 
Fixes #29684 
Fixes #29574

### CODE REVIEW

File: scene/resources/gradient.cpp [hunk 1]
```diff
@@ -151,12 +153,12 @@ void Gradient::set_offset(int pos, const float offset) {
 }
 
 float Gradient::get_offset(int pos) const {
-	if (points.size() && points.size() > pos)
-		return points[pos].offset;
-	return 0; //TODO: Maybe throw some error instead?
+	ERR_FAIL_INDEX_V(pos, points.size(), 0.0)
```
Comment (akien-mga) [inline scene/resources/gradient.cpp]: Missing trailing semicolon.

File: scene/resources/gradient.cpp [hunk 2]
```diff
@@ -166,9 +168,8 @@ void Gradient::set_color(int pos, const Color &color) {
 }
 
 Color Gradient::get_color(int pos) const {
-	if (points.size() && points.size() > pos)
-		return points[pos].color;
-	return Color(0, 0, 0, 1); //TODO: Maybe throw some error instead?
+	ERR_FAIL_INDEX_V(pos, points.size(), Color(0, 0, 0, 1))
```
Comment (akien-mga) [inline scene/resources/gradient.cpp]: Semicolon.

Comment (akien-mga) [reply scene/resources/gradient.cpp]: You can return `Color()` directly, those are default values.

**Comment by Zireael07** [comment]
Not only you find crashes, but also fix them :100:

**Comment by akien-mga** [comment]
Thanks!
