### PR TITLE
Prevent int overflow and underflow

### LINKED ISSUE #31138: Int64_t overflows in GDScriptTokenizerText::_advance
**Godot version:**
3.2.dev.custom_build 7126654ea

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
Screenshot_20190806_142017
Max int_64t value 9,223,372,036,854,775,808
```
core/ustring.cpp:1801:12: runtime error: signed integer overflow: 2152153523423251523 * 10 cannot be represented in type 'long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior core/ustring.cpp:1801:12 in 
```

### PR DESCRIPTION
**Pull request by qarmin**
Fixes #31138
This show message like:
```
ERROR: to_int: Cannot represent 1111111111111111111 as int, provided value is too big.
   At: core/ustring.cpp:1778.
```
when found overflow or underflow.

### CODE REVIEW

**Comment by KoBeWi** [comment]
Maybe the message should tell that it happens due to overflow? Or even simpler - that the number is too big.

**Comment by qarmin** [comment]
I added info about overflow to error message.

It is a little strange that in core/math/expression.cpp, `num` variable from below, is never negative(minus sign is added later), so in this case, error message is not accurate.
file


https://github.com/godotengine/godot/blob/51def4dab9d0e787c519aef914764a6140565d90/core/math/expression.cpp#L1149

**Comment by bojidar-bg** [comment]
Maybe change "as a long int" with "as a 64-bit integer" in the error messages? Also, I'm not sure that `int64_t`'s maximum value is `LONG_MAX`.

**Comment by akien-mga** [comment]
> Also, I'm not sure that `int64_t`'s maximum value is `LONG_MAX`.

Indeed, at least the guaranteed max for `INT_MAX` would be 16-bit and for `LONG_MAX` would be 32-bit. In practice I think it's twice that for each on x86_64, but that's still a bit unclear whether this bounds properly match the actual implementation we have on each platform.

http://www.cplusplus.com/reference/climits/

**Comment by bojidar-bg** [comment]
There should be `INT64_MAX` according to https://en.cppreference.com/w/cpp/types/integer

File: core/ustring.cpp [hunk 1]
```diff
@@ -39,6 +39,7 @@
 #include "core/ucaps.h"
 #include "core/variant.h"
 
+#include <limits.h>
```
Comment (akien-mga) [inline core/ustring.cpp]: That should likely be `<cstdint>` as per https://en.cppreference.com/w/cpp/types/integer, currently it doesn't build on AppVeyor.

And maybe we should use `INT32_MAX` instead of `INT_MAX`?

Comment (qarmin) [reply core/ustring.cpp]: INT_MAX and INT_MIN doesn't exists in <cstdint>, so INT32_MAX and INT32_MIN are the only solution.

**Comment by akien-mga** [comment]
Thanks!

File: core/ustring.cpp [hunk 2]
```diff
@@ -2140,6 +2147,14 @@ int64_t String::to_int(const CharType *p_str, int p_len) {
 
 				if (c >= '0' && c <= '9') {
 
+					if (integer > INT32_MAX / 10) {
+						String number("");
+						str = p_str;
+						while (str != limit) {
+							number += *(str++);
+						}
+						ERR_FAIL_V_MSG(sign == 1 ? INT32_MAX : INT32_MIN, "Cannot represent " + number + " as integer, provided value is " + (sign == 1 ? "too big." : "too small."));
```
Comment (aaronfranke) [inline core/ustring.cpp]: This should be `INT64_MAX` and `INT64_MIN` since this function returns `int64_t`.

**Review by aaronfranke — COMMENTED** [review]
Found one bug post-merge...

File: core/ustring.cpp (hunk 2 above)
Comment (akien-mga) [reply core/ustring.cpp]: Fixed by #32055.
