### PR TITLE
Fix error when non-ASCII characters in resource pack path

### LINKED ISSUE #78933: `ProjectSettings.load_resource_pack()` cannot open Chinese path
### Godot version

v4.1.rc2.official [46424488e]

### System information

win10 21H2,Vulkan API 1.2.0

### Issue description

```
E 0:00:00:0469   Node2D.gd:7 @ _ready(): Condition "f.is_null()" is true. Returning: nullptr
  <C++ 源文件>      core/io/file_access_zip.cpp:51 @ godot_open()
  <栈追踪>          Node2D.gd:7 @ _ready()

E 0:00:00:0471   Node2D.gd:7 @ _ready(): Condition "!zfile" is true. Returning: false
  <C++ 源文件>      core/io/file_access_zip.cpp:171 @ try_open_pack()
  <栈追踪>          Node2D.gd:7 @ _ready()

```

### Steps to reproduce

run mini project

### Minimal reproduction project

[test_path.zip](https://github.com/godotengine/godot/files/11928867/test_path.zip)

### PR DESCRIPTION
**Pull request by timothyqiu**
Fixes #78933

### CODE REVIEW

File: core/io/file_access_zip.cpp [hunk 1]
```diff
@@ -47,7 +47,10 @@ static void *godot_open(voidpf opaque, const char *p_fname, int mode) {
 		return nullptr;
 	}
 
-	Ref<FileAccess> f = FileAccess::open(p_fname, FileAccess::READ);
+	String fname;
+	fname.parse_utf8(p_fname);
+
+	Ref<FileAccess> f = FileAccess::open(fname, FileAccess::READ);
```
Comment (bruvzg) [inline core/io/file_access_zip.cpp:53]:
```suggestion
	Ref<FileAccess> f = FileAccess::open(String::utf8(p_fname), FileAccess::READ);
```

**Review by akien-mga — APPROVED** [review]
Seems consistent with what's done in `zip_io.cpp` and other similar file opens.

**Comment by akien-mga** [comment]
Thanks!
