### PR TITLE
GDScript: Fix some bugs with static variables and functions

### LINKED ISSUE #41919: GDScript static methods not implicitly cast into Callable
**Godot version:**  0a8c5845e

**OS/device including version:** windows 10

**Issue description:**

It's possible to assign a native function to a variable as a Callable but it's not possible for GDScript static function.

```gdscript
class Aclass:
	static func static_func():
		return 'Aclass::static_func() called'

func _ready():
	var callable1 = OS.get_process_id
	print(callable1.call())  ## <-- prints the pid
	
	var callable2 = Aclass.static_func
	print(callable2.call()) ## <-- invalid get index 'static_func'
	
```

### MRP
[41919.zip](https://github.com/godotengine/godot/files/11736820/41919.zip) (for 4.x)

_Bugsquad edit: added the MRP_

### LINKED ISSUE #77098: GDScript: Issues with static variables
### Godot version

v4.1.dev.custom_build [5c653c27c]

### System information

Kubuntu 23.04

### Issue description

1\. The setter is called when initializing a static variable (for both cases: a. if a static type is specified and b. if there is an initializer).

```gdscript
static var a: int = 1:
    set(value):
        prints("set a", value)

# For a non-static variable it's correct.
var b: int = 1:
    set(value):
        prints("set b", value)
```

```
set a 0
set a 1
```

This is because `_make_static_initializer()` uses `codegen.generator->write_set_named()` rather than `codegen.generator->write_assign()` since static variables belong to the script. We probably need a separate instruction that will not call the setter. I'm not familiar with the late stages, so I'm not sure how to properly fix this.

Also food for thought: does this make static variables slightly slower than non-static ones?

```
GDScript::callp at modules/gdscript/gdscript.cpp:866
GDScript::_set at modules/gdscript/gdscript.cpp:942
GDScript::_setv at modules/gdscript/gdscript.h:61
Object::set at core/object/object.cpp:299
Variant::set_named at core/variant/variant_setget.cpp:248
GDScriptFunction::call at modules/gdscript/gdscript_vm.cpp:1050
GDScript::_static_init at modules/gdscript/gdscript.cpp:657
```

### MRP
[77098_1.zip](https://github.com/godotengine/godot/files/11737162/77098_1.zip)

2\. An inner class static variable is falsely considered readonly.

```gdscript
class Inner:
    static var a

func _run() -> void:
    Inner.a = 1 # Error: Cannot assign a new value to a constant.
```

But you can work around this:

```gdscript
class Inner:
    static var a

func _run() -> void:
    var t: Variant = Inner
    t.a = 1
    print(Inner.a) # 1
```

This is an analyzer bug. I can try to fix it.

https://github.com/godotengine/godot/blob/5c653c27cdf779e1e70a16ec9514435537a01779/modules/gdscript/gdscript_analyzer.cpp#L2465C18-L2468

For scripts with `class_name` this already works.

### MRP
[77098_2.zip](https://github.com/godotengine/godot/files/11737273/77098_2.zip)

3\. You can apply the `@export*` and `@onready` annotations to static variables, but that doesn't make sense and may not work correctly (since one script can be attached to multiple objects). I can add the necessary checks.

### MRP
[77098_3.zip](https://github.com/godotengine/godot/files/11737341/77098_3.zip)

4\. ~~Not a bug,~~ but more of a design issue. Should static variables be accessed via an instance? Currently no, but within a class, you can access both static and non-static variables the same way, without the `self` prefix.

```gdscript
# my_class.gd
class_name MyClass

static var a

# test.gd
func test():
    var x = MyClass.new()
    MyClass.a # OK.
    x.a # Error.
```

Or perhaps we should think again about the keyword for accessing the current class (`Self`). See godotengine/godot-proposals#391.

```gdscript
static var a
var b

func test():
    a # OK.
    b # OK.
    self.a # Runtime error. Should be a compile-time error.
    self.b # OK.

    # Proposal:
    Self.a # OK.
    Self.b # Error.
```

**EDIT:** You can access any static member via `self` or instance, except for static variables. Probably for consistency and compatibility we should allow this for static variables as well.

By the way, the line 38 is incorrectly marked as safe.

### MRP
[77098_4.zip](https://github.com/godotengine/godot/files/11737436/77098_4.zip)

5\. _Separated to #78195._

<details>
<summary>Old content</summary>

5\. Static variables are not in the property list of both the object and the script. If we want the former, then we need a new `PROPERTY_USAGE_STATIC` flag, but I think we can just add it to the script's property list.

```gdscript
static var a: int
var b: int

func _ready() -> void:
    for property in get_property_list():
        if property.name in ["a", "b"]:
            print(property)
    print("---")
    for property in get_script().get_property_list():
        if property.name in ["a", "b"]:
            print(property)
    print("---")
    for property in get_script().get_script_property_list():
        if property.name in ["a", "b"]:
            print(property)
```

```
{ "name": "b", "class_name": &"", "type": 2, "hint": 0, "hint_string": "", "usage": 4096 }
---
---
{ "name": "b", "class_name": &"", "type": 2, "hint": 0, "hint_string": "", "usage": 4096 }
```

**EDIT:** I think this makes sense, since we have to add the `static` flag in the user documentation, and also because point 4.

</details>

### Steps to reproduce

See above.

### Minimal reproduction project

~~N/A~~
_Bugsquad edit: add MRPs_

### LINKED ISSUE #77331: Report error "Bad address index" when use static var
### Godot version

v4.1.dev2.official [668cf3c66]

### System information

Windows 10, 64bit

### Issue description

1. Create a Test1.gd file and code like this:
image

2. Create a scene and make a node extends Test1:
image

3. Run the scene, it report error:
image

### Steps to reproduce

Please run the reproduce project.

### Minimal reproduction project

[StaticVarTest.zip](https://github.com/godotengine/godot/files/11527662/StaticVarTest.zip)

### PR DESCRIPTION
**Pull request by dalexeev**
Closes #41919.
Closes #77098.
Closes #77331.

### CODE REVIEW

File: modules/gdscript/gdscript_compiler.cpp [hunk 1]
```diff
@@ -939,19 +951,38 @@ GDScriptCodeGenerator::Address GDScriptCompiler::_parse_expression(CodeGen &code
...
+										GDScript *scr = codegen.script;
+										while (scr) {
+											if (scr->static_variables_indices.has(var_name)) {
+												is_member_property = true;
+												is_static = true;
+												const GDScript::MemberInfo &minfo = scr->static_variables_indices[var_name];
+												member_property_setter_function = minfo.setter;
+												member_property_has_setter = member_property_setter_function != StringName();
+												member_property_is_in_setter = member_property_has_setter && member_property_setter_function == codegen.function_name;
+												static_var_class = codegen.add_constant(scr);
```
Comment (vnen) [inline modules/gdscript/gdscript_compiler.cpp:979]: This might be problematic if `scr` refers to the script being compiled, because it will make a reference to itself so it will never be freed. In such case it should use a `CLASS` address instead to use the current script.

There are other instances of this pattern in the compiler, all of them have the same issue.

File: modules/gdscript/gdscript_codegen.h [hunk 2]
```diff
@@ -110,6 +109,8 @@ class GDScriptCodeGenerator {
 	virtual void write_get_named(const Address &p_target, const StringName &p_name, const Address &p_source) = 0;
 	virtual void write_set_member(const Address &p_value, const StringName &p_name) = 0;
 	virtual void write_get_member(const Address &p_target, const StringName &p_name) = 0;
+	virtual void write_set_static_variable(const Address &p_class, const Address &p_index, const Address &p_value) = 0;
+	virtual void write_get_static_variable(const Address &p_class, const Address &p_index, const Address &p_dst) = 0;
```
Comment (vnen) [inline modules/gdscript/gdscript_codegen.h:113]: The index can be simply `int`, it does not need to be a full `Address` because it will be always be known at compile-time.

File: modules/gdscript/gdscript_vm.cpp [hunk 3]
```diff
@@ -1171,6 +1173,38 @@ Variant GDScriptFunction::call(GDScriptInstance *p_instance, const Variant **p_a
...
+				CHECK_SPACE(4);
+
+				GET_VARIANT_PTR(_class, 0);
+				GDScript *gdscript = Object::cast_to<GDScript>(_class->operator Object *());
+				GD_ERR_BREAK(!gdscript);
+
+				GET_VARIANT_PTR(index, 1);
+				GET_VARIANT_PTR(value, 2);
+
+				gdscript->static_variables.write[*index] = *value;
```
Comment (vnen) [inline modules/gdscript/gdscript_vm.cpp:1186]: With `index` being `int` instead of `Address`, this part won't need to create a Variant for the index:

```suggestion
				int index = _code_ptr[ip + 2];
				GD_ERR_BREAK(index < 0 || index >= gdscript->static_variables.size());
				GET_VARIANT_PTR(value, 2);

				gdscript->static_variables.write[index] = *value;
```

Might be better to put the index argument last so the Variant addresses are contiguous, which is common in other opcodes making it easier to understand the flow.

Same applies to the `GET` opcode below.

File: modules/gdscript/gdscript.cpp [hunk 4]
```diff
@@ -874,44 +874,46 @@ Variant GDScript::callp(const StringName &p_method, const Variant **p_args, int
...
+	if (p_name == GDScriptLanguage::get_singleton()->strings._script_source) {
+		r_ret = get_source_code();
+		return true;
+	}
+
+	const GDScript *top = this;
+	while (top) {
+		{
+			// Constants.
+			HashMap<StringName, Variant>::ConstIterator E = top->constants.find(p_name);
```
Comment (vnen) [inline modules/gdscript/gdscript.cpp:886]: This is a nitpick of mine but I don't think this type of comment says much, since in the very next line you can see it's about the constants. It does not harm though.

File: modules/gdscript/gdscript.cpp [hunk 5]
```diff
@@ -1510,84 +1534,128 @@ bool GDScriptInstance::set(const StringName &p_name, const Variant &p_value) {
...
+				}
+			}
+		}
 
-			Callable::CallError err;
-			Variant ret = E->value->call(this, (const Variant **)args, 2, err);
-			if (err.error == Callable::CallError::CALL_OK && ret.get_type() == Variant::BOOL && ret.operator bool()) {
-				return true;
+		{
+			// Script method.
```
Comment (vnen) [inline modules/gdscript/gdscript.cpp:1564]: This particular comment I find harmful for understanding the code. This section is about a custom `_set` method in the script, but the comment does not convey this information and can be confusing when compared to the previous sections since this one is not looking into a list. It should be at least:

```suggestion
			// Script `_set()` method.
```

Same applies to the `get()` method below.

**Review by vnen — DISMISSED** [review]
Overall it looks good, just a couple of things can be improved.

File: modules/gdscript/gdscript.cpp (hunk 5 above)
Comment (dalexeev) [reply modules/gdscript/gdscript.cpp]: I removed the comment.

File: modules/gdscript/gdscript_compiler.cpp (hunk 1 above)
Comment (dalexeev) [reply modules/gdscript/gdscript_compiler.cpp:979]: The problem is that the method can be inherited (see #77331) in which case `CLASS` will point to the current class, not the one the static variable is located. This will result in an error (the child class variable with the same index will be used or the `GD_ERR_BREAK` index check will be triggered).

So the `CLASS` address can only be used in the static initializer, since in this case the current class always matches.

Also, if these constants are counted, then we can still have problems in case of cyclic references. But I think they shouldn't count because it's `*GDScript` (not `Ref<GDScript>`)?

Comment (dalexeev) [reply modules/gdscript/gdscript_compiler.cpp:980]: I tested it, it does add an extra reference and doesn't depend on `GDScript*` vs `Ref<GDScript>` (some `Variant`/`Object` magic?). But we could store `ObjectID` instead of `GDScript*` (this is how `WeakRef` is implemented).

I also found that we **already** have an extra reference to each script somewhere, the bug is reproduced in master and in 4.0.3. Later I will check/open an issue.

File: modules/gdscript/gdscript_compiler.cpp [hunk 6]
```diff
@@ -1200,13 +1262,21 @@ GDScriptCodeGenerator::Address GDScriptCompiler::_parse_expression(CodeGen &code
...
+					gen->write_call(GDScriptCodeGenerator::Address(), call_base, setter_function, args);
+				} else if (is_static) {
+					GDScriptCodeGenerator::Address temp = codegen.add_temporary(static_var_data_type);
+					if (assignment->use_conversion_assign) {
+						gen->write_assign_with_conversion(temp, to_assign);
+					} else {
+						gen->write_assign(temp, to_assign);
+					}
+					gen->write_set_static_variable(temp, static_var_class, static_var_index);
+					gen->pop_temporary();
```
Comment (dalexeev) [inline modules/gdscript/gdscript_compiler.cpp:1279]: This makes me worry about performance (the need for intermediate temporaries) and maintainability (with this approach, we have to duplicate a lot of tests for static variables that we already have for non-static variables). In this sense, addressing modes is better than separate opcodes.

Since we can't get a contiguous array, maybe we could have a dynamically sized array (or a two-dimensional array if we assume that in the future we might add something else after static arrays)? The address already consists of two parts: the index of the nested array in `variant_addresses` and the index of the element in the nested array.

The compiler could take into account the depth of class inheritance, instead of storing pointers to scripts. A script that doesn't have a base script has a depth of 0, then 1, 2, 3, and so on.

Comment (dalexeev) [reply modules/gdscript/gdscript_compiler.cpp:1279]: Done: https://github.com/dalexeev/godot/commit/14efadf3888f1011fc384280a1de90099f3f75b8

**Comment by dalexeev** [comment]
I reset the branch to the new version as there are more fixes. You can see the old version with separate opcodes here: https://github.com/dalexeev/godot/commit/fee4ea4381413f82763e250e2dc79f6a0e2c9293.

File: modules/gdscript/gdscript_vm.cpp [hunk 7]
```diff
@@ -679,11 +678,40 @@ Variant GDScriptFunction::call(GDScriptInstance *p_instance, const Variant **p_a
...
+	int variant_addresses_size = ADDR_TYPE_STATIC_VAR + script->inheritance_level + 1;
+
+	int *variant_address_limits = memnew_arr(int, ADDR_TYPE_STATIC_VAR + script->inheritance_level + 1);
+	variant_address_limits[ADDR_TYPE_STACK] = _stack_size;
+	variant_address_limits[ADDR_TYPE_CONSTANT] = _constant_count;
+	variant_address_limits[ADDR_TYPE_MEMBER] = p_instance ? p_instance->members.size() : 0;
 #endif
 
-	Variant *variant_addresses[ADDR_TYPE_MAX] = { stack, _constants_ptr, p_instance ? p_instance->members.ptrw() : nullptr, script->static_variables.ptrw() };
+	Variant **variant_addresses = memnew_arr(Variant *, ADDR_TYPE_STATIC_VAR + script->inheritance_level + 1);
```
Comment (dalexeev) [inline modules/gdscript/gdscript_vm.cpp:691]: I'm not sure about the preferred way to allocate memory, maybe `new[]` or `alloca()` is better here?

Comment (adamscott) [reply modules/gdscript/gdscript_vm.cpp:691]: I think this is the preferred way in the Godot codebase:
https://github.com/godotengine/godot/blob/49243a9a9816b334002f7d73d9e940d00b49158d/scene/animation/tween.cpp#L748

**Comment by adamscott** [comment]
@dalexeev Can you isolate point 5 of https://github.com/godotengine/godot/issues/77098 in its own issue? We could close then #77098 when merging this PR.

**Comment by dalexeev** [comment]
> @dalexeev Can you isolate point 5 of #77098 in its own issue?

* Done: #78195.

**Review by akien-mga — APPROVED** [review]
@vnen last reviewed with "Overall it looks good", and the suggestions for improvements have been made, so this should be good to merge and test in the next beta.

**Comment by dalexeev** [comment]
I think it's better to wait for George's comment. While this closes related issues, I'm not sure which approach is better: dedicated opcodes or addressing modes (I've updated the PR for the second option). And also there is Adam's comment about `alloca()`. And I also have a doubt about how `inheritance_level` will work with hot reloading.

File: modules/gdscript/gdscript_compiler.cpp (hunk 6 above)
Comment (vnen) [reply modules/gdscript/gdscript_compiler.cpp]: I'm not sure about that. Sure it's slower having a two-step approach, but generating this address array dynamically every time seems to be worse for me. Regarding tests, we will need tests for static variables a anyway, so I don't think it makes much of a difference (IMO testing for generating a particular addressing mode is as important as testing for generating opcodes).

File: modules/gdscript/gdscript_compiler.cpp (hunk 1 above)
Comment (vnen) [reply modules/gdscript/gdscript_compiler.cpp]: > I tested it, it does add an extra reference and doesn't depend on `GDScript*` vs `Ref<GDScript>` (some `Variant`/`Object` magic?)

All constants are Variants, if you put a RefCounted object it will increment the count (it does not matter if the `Ref<>` wrapper is used, the Variant itself act as the wrapper). 

> I also found that we **already** have an extra reference to each script somewhere, the bug is reproduced in master and in 4.0.3. Later I will check/open an issue.

I mentioned this in the static variables PR. But I don't think there's an open issue yet. There's a bit of weird stuff happening in the GDScriptCache so the issue is a bit complicated.

Comment (vnen) [reply modules/gdscript/gdscript_compiler.cpp]: > The problem is that the method can be inherited (see #77331) in which case `CLASS` will point to the current class, not the one the static variable is located

What I meant is to use `CLASS` only in the case where it is in current class. If it is from a super class then it's fine because there's already a reference to it anyway.

**Review by vnen — CHANGES_REQUESTED** [review]
IMO the previous approach with opcodes was better. The changes in addressing modes is more complex and seems to create extra overhead in all function calls to populate the array.

**Comment by dalexeev** [comment]
Okay, I can go back to the opcode version and add some later changes to it. Not sure how to deal with `RefCounted`, replace with `ObjectID` as I suggested above?

File: modules/gdscript/gdscript_compiler.cpp (hunk 1 above)
Comment (dalexeev) [reply modules/gdscript/gdscript_compiler.cpp:980]: > I mentioned this in the static variables PR. But I don't think there's an open issue yet.

* See #77513.

**Comment by dalexeev** [comment]
Done. Only the issue with `RefCounted` remained. But at the moment the scripts are never unloaded due to the `GDScriptCache` issue anyway.

**Review by vnen — APPROVED** [review]
Looks OK to me. The issue with references can be sorted out later since it's shadowed by a bigger issue for now anyway.

**Comment by akien-mga** [comment]
Thanks!

**Comment by capnm** [comment]
Looks like this is recent enough to cause the  73ac33342fa8326e533604f43494844483dcca3d linux/clang 16.0.5 compiler error:

```
[ 22%] clang++ -o modules/gdscript/editor/scu/scu_modules_gdscript_editor.gen.linuxbsd.editor.dev.x86_64.llvm.o -c -std=gnu++17 -fpic -pipe -gdwarf-4 -g3 -Og -Wall -Wshadow-field-in-constructor -Wshadow-uncaptured-local -Wno-ordered-compare-function-pointers -isystem thirdparty/glad -DTOOLS_ENABLED -DDEBUG_ENABLED -DDEV_ENABLED -DNO_EDITOR_SPLASH -DSOWRAP_ENABLED -DTOUCH_ENABLED -DFONTCONFIG_ENABLED -DALSA_ENABLED -DALSAMIDI_ENABLED -DPULSEAUDIO_ENABLED -D_REENTRANT -DDBUS_ENABLED -DSPEECHD_ENABLED -DXKB_ENABLED -DJOYDEV_ENABLED -DUDEV_ENABLED -DLINUXBSD_ENABLED -DUNIX_ENABLED -D_FILE_OFFSET_BITS=64 -DX11_ENABLED -DVULKAN_ENABLED -DGLES3_ENABLED -DMINIZIP_ENABLED -DBROTLI_ENABLED -DZSTD_STATIC_LINKING_ONLY -DUSE_VOLK -DVK_USE_PLATFORM_XLIB_KHR -DGLAD_ENABLED -DGLES_OVER_GL -Ithirdparty/libpng -Ithirdparty/volk -Ithirdparty/vulkan -Ithirdparty/vulkan/include -Ithirdparty/zstd -Ithirdparty/zlib -Ithirdparty/brotli/include -Ithirdparty/linuxbsd_headers -Iplatform/linuxbsd -I. modules/gdscript/editor/scu/scu_modules_gdscript_editor.gen.cpp
In file included from modules/gdscript/scu/scu_modules_gdscript.gen.cpp:14:
./modules/gdscript/gdscript_vm.cpp:52:10: error: call to '_get_script_name' is ambiguous
                return _get_script_name(script_type);
                       ^~~~~~~~~~~~~~~~
./modules/gdscript/gdscript_disassembler.cpp:38:15: note: candidate function
static String _get_script_name(const Ref<Script> &p_script) {
              ^
./modules/gdscript/gdscript_vm.cpp:39:15: note: candidate function
static String _get_script_name(const Ref<Script> p_script) {
              ^
./modules/gdscript/gdscript_vm.cpp:78:24: error: call to '_get_script_name' is ambiguous
                                        basestr += " (" + _get_script_name(bobj->get_script_instance()->get_script()) + ")";
                                                          ^~~~~~~~~~~~~~~~
./modules/gdscript/gdscript_disassembler.cpp:38:15: note: candidate function
static String _get_script_name(const Ref<Script> &p_script) {
              ^
./modules/gdscript/gdscript_vm.cpp:39:15: note: candidate function
static String _get_script_name(const Ref<Script> p_script) {
              ^
./modules/gdscript/gdscript_vm.cpp:2687:47: error: call to '_get_script_name' is ambiguous
                                                        Variant::get_type_name(r->get_type()), _get_script_name(Ref<Script>(base_type)));
                                                                                               ^~~~~~~~~~~~~~~~
./modules/gdscript/gdscript_disassembler.cpp:38:15: note: candidate function
static String _get_script_name(const Ref<Script> &p_script) {
              ^
./modules/gdscript/gdscript_vm.cpp:39:15: note: candidate function
static String _get_script_name(const Ref<Script> p_script) {
              ^
./modules/gdscript/gdscript_vm.cpp:2709:36: error: call to '_get_script_name' is ambiguous
                                                                ret_obj->get_class_name(), _get_script_name(Ref<GDScript>(base_type)));
                                                                                           ^~~~~~~~~~~~~~~~
./modules/gdscript/gdscript_disassembler.cpp:38:15: note: candidate function
static String _get_script_name(const Ref<Script> &p_script) {
              ^
./modules/gdscript/gdscript_vm.cpp:39:15: note: candidate function
static String _get_script_name(const Ref<Script> p_script) {
              ^
./modules/gdscript/gdscript_vm.cpp:2728:9: error: call to '_get_script_name' is ambiguous
                                                                _get_script_name(ret_obj->get_script_instance()->get_script()), _get_script_name(Ref<GDScript>(base_type)));
                                                                ^~~~~~~~~~~~~~~~
./modules/gdscript/gdscript_disassembler.cpp:38:15: note: candidate function
static String _get_script_name(const Ref<Script> &p_script) {
              ^
./modules/gdscript/gdscript_vm.cpp:39:15: note: candidate function
static String _get_script_name(const Ref<Script> p_script) {
              ^
./modules/gdscript/gdscript_vm.cpp:2728:73: error: call to '_get_script_name' is ambiguous
                                                                _get_script_name(ret_obj->get_script_instance()->get_script()), _get_script_name(Ref<GDScript>(base_type)));
                                                                                                                                ^~~~~~~~~~~~~~~~
./modules/gdscript/gdscript_disassembler.cpp:38:15: note: candidate function
static String _get_script_name(const Ref<Script> &p_script) {
              ^
./modules/gdscript/gdscript_vm.cpp:39:15: note: candidate function
static String _get_script_name(const Ref<Script> p_script) {
              ^
6 errors generated.
scons: *** [modules/gdscript/scu/scu_modules_gdscript.gen.linuxbsd.editor.dev.x86_64.llvm.o] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:00:15.977]
```

**Comment by akien-mga** [comment]
@capnm See #78465.

**Comment by capnm** [comment]
Thanks after #78465 .patch it compiles again.
