### PR TITLE
Disable code font ligatures by default in the editor

### LINKED ISSUE #63865: Code ligatures shouldn't apply on literal strings
### Godot version

v4.0.alpha13.official [59dcddc45]

### System information

Linux

### Issue description

Code ligatures shouldn't apply to literal strings. The text should show exactly the text that it actually is. When printed etc the ligature will not be shown. And, we don't know how the string is going to be used anyway.

Currently:
image

Should be:
image

Also, ligatures shouldn't be on by default. If you type some characters, those are the characters that should be displayed. If the user wants something different they can make that choice manually. Ligatures are confusing for beginners too.

### Steps to reproduce

Type `"<="` in the text editor.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Calinou**
In the interest of principle of least astonishment, having ligatures disabled by default is probably better.

This closes https://github.com/godotengine/godot/issues/63865.

### CODE REVIEW

File: editor/editor_settings.cpp [hunk 1]
```diff
@@ -412,7 +412,7 @@ void EditorSettings::_load_defaults(Ref<ConfigFile> p_extra_config) {
 	EDITOR_SETTING_USAGE(Variant::FLOAT, PROPERTY_HINT_RANGE, "interface/editor/custom_display_scale", 1.0, "0.5,3,0.01", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_RESTART_IF_CHANGED)
 	EDITOR_SETTING(Variant::INT, PROPERTY_HINT_RANGE, "interface/editor/main_font_size", 14, "8,48,1")
 	EDITOR_SETTING(Variant::INT, PROPERTY_HINT_RANGE, "interface/editor/code_font_size", 14, "8,48,1")
-	EDITOR_SETTING(Variant::INT, PROPERTY_HINT_ENUM, "interface/editor/code_font_contextual_ligatures", 0, "Default,Disable Contextual Alternates (Coding Ligatures),Use Custom OpenType Feature Set")
+	EDITOR_SETTING(Variant::INT, PROPERTY_HINT_ENUM, "interface/editor/code_font_contextual_ligatures", 1, "Default,Disable Contextual Alternates (Coding Ligatures),Use Custom OpenType Feature Set")
```
Comment (DarkKilauea) [inline editor/editor_settings.cpp:415]: Do we want to rename "Default" here to "Enabled" in the enum?

It seems odd that the default option is not the default for this setting.

**Review by Geometror — APPROVED** [review]
I agree, having ligatures disabled by default is probably the best (at least for now).

**Comment by akien-mga** [comment]
Thanks!
