### PR TITLE
Fix inconsistent CanvasModulate color in 2D HDR

### LINKED ISSUE #92796: CanvasModulate color too bright when using 2D HDR
### Tested versions

Reproducible in 4.2.2
Not reproducible in 3.x

### System information

Godot v4.2.2.stable.mono - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (nvidia; 535.171.04) - Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 Threads)

### Issue description

When using a CanvasModulate with 2D HDR enabled the modulate color is too bright.
Modulate color 1, 1, 1, 255:
cm

The color should be converted to linear space to get similar results to a CanvasModulate without 2D HDR enabled.

### Steps to reproduce

-Add Sprite to project
-Add CanvasModulate to project
-Set modulate color to anything besides pure black or white
-Compare 2D HDR enabled to disabled

### Minimal reproduction project (MRP)

[cm_mrp.zip](https://github.com/user-attachments/files/15586703/cm_mrp.zip)

### PR DESCRIPTION
**Pull request by feiyue-z**
Linearize CanvasModulate color if HDR 2D is on.

Fix #92796

### CODE REVIEW

**Review by clayjohn — DISMISSED** [review]
Looks great! Thank you!

**Review by Calinou — COMMENTED** [review]
Tested locally, it works as expected when the root viewport has HDR 2D enabled. However, when the root viewport has HDR 2D disabled, this makes CanvasModulate in SubViewports no longer match each other depending on whether they have HDR 2D enabled.

The SubViewport on the left has HDR 2D disabled, while the one on the right has HDR 2D enabled. Using Forward+.

**Testing project:** [test_pr_93802.zip](https://github.com/user-attachments/files/16317690/test_pr_93802.zip)

### HDR 2D *enabled* on the root Viewport (working correctly in this PR)

Before | After
-|-
Before | After


### HDR 2D *disabled* on the root Viewport (not working correctly in this PR)

Before | After
-|-
Before | After

**Comment by feiyue-z** [comment]
@Calinou 
Thank you for the feedback!
I have fixed the issue by adding a check to see if 2D HDR is enabled in project settings. I also took out the linearization in compatibility mode because it seems to work just fine without it.

File: servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp [hunk 1]
```diff
@@ -1451,10 +1451,15 @@ void RendererCanvasRenderRD::canvas_render_items(RID p_to_render_target, Item *p
 		normal_transform.columns[2] = Vector2();
 		_update_transform_2d_to_mat4(normal_transform, state_buffer.canvas_normal_transform);
 
-		state_buffer.canvas_modulate[0] = p_modulate.r;
-		state_buffer.canvas_modulate[1] = p_modulate.g;
-		state_buffer.canvas_modulate[2] = p_modulate.b;
-		state_buffer.canvas_modulate[3] = p_modulate.a;
+		bool use_linear_colors = texture_storage->render_target_is_using_hdr(p_to_render_target) && GLOBAL_GET("rendering/viewport/hdr_2d");
```
Comment (akien-mga) [inline servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:1454]: The project setting should likely be checked in the constructor only once, and saved in a member variable, for performance reasons. Reading project settings for each render command is going to be expensive.

That being said I'm not sure this is the correct check. I haven't looked in depth but I believe `rendering/viewport/hdr_2d` only sets the default value for the root viewport. It can still be changed later on for any viewport with `RenderingServer::viewport_set_use_hdr_2d` and `Viewport::set_use_hdr_2d`.

I'm no rendering expert so TIWAGOS[^1], but it sounds to me like this might need to check the value for the target viewport. No idea how that's done at this stage of the render pipeline, @clayjohn might know.

[^1]: Take It With A Grain Of Salt

Comment (clayjohn) [reply servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:1454]: I suspect the original fix was correct. Taking a look now. 

It seems like the demo project is treating the linear HDR Viewport's texture as if it is sRGB color texture. If so, that would be the source of the problem.

Comment (clayjohn) [reply servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:1454]: Ya, the problem comes from the demo project. When HDR_2D is disabled on the root viewport, the root viewport expects to receive sRGB textures (it doesn't do any color conversion). However, the demo passes a linear HD texture which ends up looking incorrect. Simply doing the linear->sRGB conversion in the shader makes the output correct. 

This issue highlights a broader issue which is that mixing HDR_2D and non HDR content is still confusing for users and prone to error. So there is likely stuff we can do to improve the situation. 

As for this PR, we should not be checking the project setting, the code should be reverted back to the way it was

Comment (feiyue-z) [reply servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp]: Thank you! I have reverted the changes.

I just started contributing to Godot and I'm trying to fix good first issues by tinkering with the code through trial and error. I'm wondering if there are any resources to learn more about the rendering architecture of Godot, so I can avoid situation like this next time.

**Review by akien-mga — APPROVED** [review]
I rebased to remove the reverted commits.

Approving on the basis on Clay's original approval, which was later confirmed in discussion.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
