### PR TITLE
Fix mouse position with screen transform

### LINKED ISSUE #74868: TreeItem buttons do not function in a SubViewport using the push_input method.
### Godot version

4.0.stable

### System information

Windows 10

### Issue description

In my project, we are rendering a GUI to a QuadMesh as an in-game interactive display. We push mouse click events when the player clicks the display. This worked fine during 4.0 beta, but after moving to the stable release the buttons on TreeItems stopped working. I put together a MRP and went back through the versions and it seems the issue started in RC1.

### Steps to reproduce

When running the MRP, it has a standard GUI on the left hand side of the screen and a QuadMesh rendered GUI on the right hand side. If you click the + button on an item, it will add another item to the list. On the QuadMesh you will see that you can highlight and collapse items in the list, but the + button does not function. If you run the MRP on 4.0.beta17 everything will function as expected.

### Minimal reproduction project

[TreeUI_through_SubViewport.zip](https://github.com/godotengine/godot/files/10959159/TreeUI_through_SubViewport.zip)

### PR DESCRIPTION
**Pull request by Sauermann**
When a Viewport is not in the scene tree or not a child of a `SubViewportContainer`, the function `Viewport::get_mouse_position` can't rely on `get_screen_transform`, because that function is ambiguous in these situations.
In these cases it is necessary to use the mouse position from the most recent mouse InputEvent.

resolve #74868

### CODE REVIEW

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -1351,7 +1351,12 @@ Ref<InputEvent> Viewport::_make_input_local(const Ref<InputEvent> &ev) {
 
 Vector2 Viewport::get_mouse_position() const {
 	ERR_READ_THREAD_GUARD_V(Vector2());
-	if (DisplayServer::get_singleton()->has_feature(DisplayServer::FEATURE_MOUSE)) {
+	if (!is_inside_tree() || (Object::cast_to<SubViewport>(this) && !Object::cast_to<SubViewportContainer>(get_parent()))) {
```
Comment (RandomShaper) [inline scene/main/viewport.cpp:1354]: I'm wondering if this condition can be rewritten based on some already existing is-attached-to-screen functionality or at least should be put in a new `virtual bool is_attached_to_screen()`, or the like.

Maybe not. It's that checking the type of `this` seems a bit odd.

Comment (Sauermann) [reply scene/main/viewport.cpp:1354]: I am not aware of any existing functionality, that covers this.

`is_attached_to_screen` could be something like:
```c++
bool SubViewport::is_attached_to_screen() const {
   return Object::cast_to<SubViewportContainer>(get_parent()) && get_parent()->get_viewport() && get_parent()->get_viewport()->is_attached_to_screen();
}
bool Window::is_attached_to_screen() const {
    if (get_embedder()) {
        return get_embedder()->is_attached_to_screen();
    }
    return is_inside_tree();
}
```

Alternatively we could introduce a virtual function:
``` c++
bool Viewport::is_window() const {
    return true;
}
bool SubViewport::is_window() const {
    return false;
}
```
And replace `Object::cast_to<SubViewport>(this)` by `!_is_window()`.

Comment (Sauermann) [reply scene/main/viewport.cpp]: I have updated the PR and introduced a `is_directly_attached_to_screen` method.

**Review by RandomShaper — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
