### PR TITLE
Disable dark mode title bar on Windows 10.

### LINKED ISSUE #65492: Windows 10: Title bar not changing color while in dark mode
### Godot version

4.0.alpha16

### System information

Windows 10

### Issue description

When launching the Godot editor with dark mode enabled, the title bar stays white, but the other UI elements switch to dark mode (also white) so they cannot be seen properly. 

This also happens to any child window when it is created even when the main window has the black title bar.

dark_mode

This effect disappears as soon as the window is unfocused or resized. Dragging it around does nothing as well as switching from project manager to the editor.

### Steps to reproduce

Launch the editor either directly or trough console

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by bruvzg**
- Adds Windows 10 build version checks.
- Disables dark mode title bar on Windows 10 (it's officially supported only on Windows 11, and is buggy on Windows 10).

*Bugsquad edit: This closes https://github.com/godotengine/godot/issues/65492.*

### CODE REVIEW

**Comment by Calinou** [comment]
The class reference should mention which Windows 10 versions support dark mode detection. As I understand it, 1809 is required for basic support, and 20H2 is required for full support (or any Windows 11 version).

**Comment by fire-forge** [comment]
This doesn't work, unfortunately. The title bars have the same problem with this PR as they did in https://github.com/godotengine/godot/pull/65026.

I am working on finding a fix for this in a separate branch though. So far, I've tried two approaches that don't work, and I have a few more ideas for a solution. Hopefully I can find one that works.

**Comment by fire-forge** [comment]
I've made several unsuccessful attempts to fix this issue using various Windows window APIs. So I'll have to defer this to someone else who knows what they're doing :P

I will write a new issue for this bug soon where I'll document the different methods I tried so I can hopefully save whoever tries to fix this some time.

File: platform/windows/display_server_windows.cpp [hunk 1]
```diff
@@ -2400,14 +2396,16 @@ LRESULT DisplayServerWindows::WndProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARA
 			if (lParam && CompareStringOrdinal(reinterpret_cast<LPCWCH>(lParam), -1, L"ImmersiveColorSet", -1, true) == CSTR_EQUAL) {
 				if (is_dark_mode_supported()) {
 					BOOL value = is_dark_mode();
-					::DwmSetWindowAttribute(windows[window_id].hWnd, DWMWA_USE_IMMERSIVE_DARK_MODE, &value, sizeof(value));
+					::DwmSetWindowAttribute(windows[window_id].hWnd, immersive_dark_mode, &value, sizeof(value));
+					SetWindowPos(windows[window_id].hWnd, 0, 0, 0, 0, 0, SWP_DRAWFRAME | SWP_NOACTIVATE | SWP_NOMOVE | SWP_NOSIZE | SWP_NOZORDER);
```
Comment (fire-forge) [inline platform/windows/display_server_windows.cpp:2400]: This line can be removed. The window title bar updates correctly when the theme changes even when this line is removed.

File: platform/windows/display_server_windows.cpp [hunk 2]
```diff
@@ -2400,14 +2396,16 @@ LRESULT DisplayServerWindows::WndProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARA
...
 				}
 			}
 		} break;
 		case WM_THEMECHANGED: {
 			if (is_dark_mode_supported()) {
 				BOOL value = is_dark_mode();
-				::DwmSetWindowAttribute(windows[window_id].hWnd, DWMWA_USE_IMMERSIVE_DARK_MODE, &value, sizeof(value));
+				::DwmSetWindowAttribute(windows[window_id].hWnd, immersive_dark_mode, &value, sizeof(value));
+				SetWindowPos(windows[window_id].hWnd, 0, 0, 0, 0, 0, SWP_DRAWFRAME | SWP_NOACTIVATE | SWP_NOMOVE | SWP_NOSIZE | SWP_NOZORDER);
```
Comment (fire-forge) [inline platform/windows/display_server_windows.cpp:2408]: This line can also be removed, same as above.

File: platform/windows/display_server_windows.cpp [hunk 3]
```diff
@@ -3522,7 +3520,8 @@ DisplayServer::WindowID DisplayServerWindows::_create_window(WindowMode p_mode,
 
 		if (is_dark_mode_supported()) {
 			BOOL value = is_dark_mode();
-			::DwmSetWindowAttribute(wd.hWnd, DWMWA_USE_IMMERSIVE_DARK_MODE, &value, sizeof(value));
+			::DwmSetWindowAttribute(wd.hWnd, immersive_dark_mode, &value, sizeof(value));
+			SetWindowPos(wd.hWnd, 0, 0, 0, 0, 0, SWP_DRAWFRAME | SWP_NOACTIVATE | SWP_NOMOVE | SWP_NOSIZE | SWP_NOZORDER);
```
Comment (fire-forge) [inline platform/windows/display_server_windows.cpp:3524]: This line can also be removed because it has no effect. The window title bar doesn't draw correctly with or without this line included.

**Review by fire-forge — CHANGES_REQUESTED** [review]

**Comment by bruvzg** [comment]
> This doesn't work, unfortunately.

I have no idea how to fix it, so I guess it's better to disable dark title bar for Windows 10 (but keep dark mode/accent APIs) until it's fixed, and use it only on Windows 11.

**Comment by fire-forge** [comment]
Blender 3.3 was released recently, and it supports the dark title bar on Windows 10 without any issues. At some point I will look at Blender's source code to see how they did it, and open a PR to implement it in Godot if I'm able to. Until then, this PR will be fine to merge since it's better to keep using the light title bar than a broken one.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by bruvzg** [comment]
> This is the commit on the Blender repository

It seems to be doing exactly the same. Probably something else is interfering with the title.

**Comment by naphipps** [comment]
Doing the following fixed the dark mode title bar on Windows 10 for me:
```cpp
//include <dwmapi.h> and link to dwmapi.lib

LPCSTR subkey = "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize";
LPCSTR value = "SystemUsesLightTheme";
DWORD word = 0;
DWORD size = sizeof(DWORD);
LSTATUS status = RegGetValueA(HKEY_CURRENT_USER, subkey, value, RRF_RT_DWORD, nullptr, &word, &size);
bl is_dark_mode = status == ERROR_SUCCESS && word == 0;

if (is_dark_mode)
{
	HWND native_window = (HWND)GetNativeWindow();
	BOOL value = true;
	DwmSetWindowAttribute(native_window, 20, &value, sizeof(value));

	WPARAM wparam{};
	LPARAM lparam{};
	wparam = FALSE;
	CallWindowProcA(_prev_window_procedure, native_window, WM_NCACTIVATE, wparam, lparam);
	wparam = TRUE;
	CallWindowProcA(_prev_window_procedure, native_window, WM_NCACTIVATE, wparam, lparam);
}
```
For some reason, deactivating the title bar, then activating it again works... Feel free to use the DefWindowProcA instead of CallWindowProcA. I happen to subclass my window procedure in my project.

I started on this topic over on [pull 65026](https://github.com/godotengine/godot/pull/65026) and found my way here as well.
