### PR TITLE
[Core] Fix TypedArray encoding when full objects is disabled

### LINKED ISSUE #90467: Typed arrays with custom types don't show up in the debugger's variable stack
### Tested versions

v4.3.dev.custom_build [a7b860250]

### System information

linux

### Issue description

```gdscript
var my_array: Array[MyCustomClass] = []
breakpoint
```
at the breakpoint, `my_array` doesn't show up as a local variable in the debugger.

### Steps to reproduce

run the above code and check the debugger

### Minimal reproduction project (MRP)

```gdscript
extends Node

class MyCustomClass:
	pass

func _ready() -> void:
	var custom: Array[MyCustomClass]
	breakpoint
```

### LINKED ISSUE #94384: Error encoding object typed array with `var_to_bytes` and decoding with `bytes_to_var_with_objects`
### Tested versions

- Reproducible in 4.3.dev (regression from #78219)

### System information

Irrelevant

### Issue description

Encoding a (object) typed array with `var_to_bytes` then decoding with `bytes_to_var_with_objects` cause an error.

While this is very uncommon, encoding with `var_to_bytes` and  decoding with `bytes_to_var_with_objects` should always be possible.

### Steps to reproduce

Run the following script:

```gdscript
func _ready():
	var res := ImageTexture.new()
	var my_arr : Array[ImageTexture]
	my_arr.push_back(res)
	print(bytes_to_var_with_objects(var_to_bytes(my_arr)))
```

Notice the error:

```
ERROR: Attempted to push_back an object of type 'EncodedObjectAsID' into a TypedArray, which does not inherit from 'ImageTexture'.
   at: validate_object (core/variant/container_type_validate.h:129)
ERROR: Condition "!_p->typed.validate(value, "push_back")" is true.
   at: push_back (core/variant/array.cpp:285)
```

### Minimal reproduction project (MRP)

See the script above.

### PR DESCRIPTION
**Pull request by Faless**
Typed arrays containing objects, are now correctly encoded with type `EncodedObjectAsID` when full objects is disabled.

Alternative to #90990
Fixes #90467
Fixes #94384

### CODE REVIEW

File: core/io/marshalls.cpp [hunk 1]
```diff
@@ -1783,11 +1783,15 @@ Error encode_variant(const Variant &p_variant, uint8_t *r_buffer, int &r_len, bo
...
 				if (script.is_valid()) {
-					String path = script->get_path();
-					ERR_FAIL_COND_V_MSG(path.is_empty() || !path.begins_with("res://"), ERR_UNAVAILABLE, "Failed to encode a path to a custom script for an array type.");
-					_encode_string(path, buf, r_len);
+					if (p_full_objects) {
+						String path = script->get_path();
+						ERR_FAIL_COND_V_MSG(path.is_empty() || !path.begins_with("res://"), ERR_UNAVAILABLE, "Failed to encode a path to a custom script for an array type.");
+						_encode_string(path, buf, r_len);
+					} else {
+						_encode_string(EncodedObjectAsID::get_class_static(), buf, r_len);
```
Comment (dalexeev) [inline core/io/marshalls.cpp:1791]: `Array[EncodedObjectAsID]` may be incompatible with `Array[T]`.

Comment (Faless) [reply core/io/marshalls.cpp:1791]: > `Array[EncodedObjectAsID]` may be incompatible with `Array[T]`.

Not sure I understand, this is exactly why when encoding with `p_full_objects = false` we **must** set the serialized array type to to `EncodedObjectAsID` since the content will actually be `EncodedObjectAsID`.

Comment (dalexeev) [reply core/io/marshalls.cpp:1791]: This will cause an error when assigning the array to a typed variable.

Comment (Faless) [reply core/io/marshalls.cpp:1791]: I've opened https://github.com/godotengine/godot/issues/94384 showing the other regression (fixed by this PR).

File: core/io/marshalls.cpp [hunk 2]
```diff
@@ -1783,11 +1783,15 @@ Error encode_variant(const Variant &p_variant, uint8_t *r_buffer, int &r_len, bo
...
+					}
 				} else if (array.get_typed_class_name() != StringName()) {
-					_encode_string(array.get_typed_class_name(), buf, r_len);
+					_encode_string(p_full_objects ? array.get_typed_class_name().operator String() : EncodedObjectAsID::get_class_static(), buf, r_len);
 				} else {
 					if (buf) {
```
Comment (dalexeev) [inline core/io/marshalls.cpp:1796]:
```suggestion
				} else {
					// No need to check `p_full_objects` since for `Variant::OBJECT`
					// `array.get_typed_class_name()` should be non-empty.
					if (buf) {
```

File: core/io/marshalls.cpp [hunk 3]
```diff
@@ -1315,7 +1315,7 @@ Error encode_variant(const Variant &p_variant, uint8_t *r_buffer, int &r_len, bo
 			if (array.is_typed()) {
 				Ref<Script> script = array.get_typed_script();
 				if (script.is_valid()) {
-					header |= HEADER_DATA_FIELD_TYPED_ARRAY_SCRIPT;
+					header |= p_full_objects ? HEADER_DATA_FIELD_TYPED_ARRAY_SCRIPT : HEADER_DATA_FIELD_TYPED_ARRAY_CLASS_NAME;
 				} else if (array.get_typed_class_name() != StringName()) {
 					header |= HEADER_DATA_FIELD_TYPED_ARRAY_CLASS_NAME;
 				} else {
```
Comment (dalexeev) [inline core/io/marshalls.cpp:1321]:
```suggestion
				} else {
					// No need to check `p_full_objects` since for `Variant::OBJECT`
					// `array.get_typed_class_name()` should be non-empty.
```

**Review by dalexeev — APPROVED** [review]
Makes sense to me, thanks! Note that this creates some inconsistency: with `p_full_objects = false` pathless scripts are supported, but with `p_full_objects = true` they are not. However, it's less controversial than #90990, so we can fix it in the future if necessary.

**Comment by akien-mga** [comment]
Thanks!
