### PR TITLE
Mark shader built-ins as used when passed to functions as out parameter

### LINKED ISSUE #68378: It seems that you can only modify VERTEX in a vertex fragment
### Godot version

4.0B4

### System information

WIN10 VULKAN GTX1660TiMaxQ

### Issue description

When I modified VERTEX by passing it as an inout argument to a function outside the vertex fragment, it didn't look right.

``` c
shader_type spatial;

void test(inout vec3 vertex)
{
	vertex.y = 10.0;
}
void vertex()
{
	test(VERTEX);
}
```

### Steps to reproduce

see mini project

### Minimal reproduction project

[vertex.zip](https://github.com/godotengine/godot/files/9953052/vertex.zip)

### PR DESCRIPTION
**Pull request by Chaosus**
Fix https://github.com/godotengine/godot/issues/68378 by marking the built-in as used when it passed to function as `out` or `inout` parameter (we cannot guarantee that it will not be modified inside it anyway). Fixes the cases like:

```
void test(inout vec3 vertex) {
 vertex.y = 10.0;
}

void vertex() {
	test(VERTEX);
}
```

or

```
void test(inout float component) {
	component = 10.0f;
}

void vertex() {
	test(VERTEX.y);
}
```

and also for built-in functions:

```
void vertex() {
	modf(1.0, VERTEX.y);
}
```

### CODE REVIEW

File: servers/rendering/shader_language.cpp [hunk 1]
```diff
@@ -9717,6 +9717,25 @@ String ShaderLanguage::get_shader_type(const String &p_code) {
...
+				int arg = builtin_func_out_args[i].arguments[j];
+				if (arg == p_param) {
+					return true;
+				}
+				if (arg < 0) {
+					return false;
+				}
+			}
+		}
+		++i;
```
Comment (clayjohn) [inline servers/rendering/shader_language.cpp:9734]: As a matter of style, I prefer i++ and here they are equivalent.

Comment (Chaosus) [reply servers/rendering/shader_language.cpp:9734]: Hm, and I prefer maximum reasonable solutions (post-increment is not useful here)... Also interesting discussion about it - https://stackoverflow.com/questions/4706199/post-increment-and-pre-increment-within-a-for-loop-produce-same-output

But if you want I can fix it of course...

**Review by clayjohn — APPROVED** [review]

File: servers/rendering/shader_language.cpp (hunk 1 above)
Comment (clayjohn) [reply servers/rendering/shader_language.cpp]: Its not a big deal either way
