### PR TITLE
[GUI] Fix reparenting control does not update recursive mode cache properly

### LINKED ISSUE #104443: [GUI] Setting a control's recursive mode to disabled does not work on start
### Tested versions

latest main branch [2303ce843a362cf5497ca3336451de23793eb711]

### System information

Godot v4.5.dev (2303ce843) - Windows 10 (build 19044) - Multi-window, 4 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti (NVIDIA; 32.0.15.7260) - AMD Ryzen 9 5900X 12-Core Processor (24 threads)

### Issue description

#97495 introduces properties for managing children's controls' focus mode and mouse filters. However, this won't work if you set the recursive behavior to `Disable` in the editor.

### Steps to reproduce

https://github.com/user-attachments/assets/c498932f-8874-4a14-a693-fe0e09b74443

### Minimal reproduction project (MRP)

[MrpRecursiveGuiDisable.zip](https://github.com/user-attachments/files/19391423/MrpRecursiveGuiDisable.zip)

### PR DESCRIPTION
**Pull request by Delsin-Yu**
Fixes #104443

#97495 didn't correctly handle the internal cache update on reparenting (for example, if the control has its recursive mode set to `Disabled` and the cache is `Disabled,` it won't update the property at all).

This PR also renames the `_apply_xxx_behavior_recursively` to `_propagate_xxx_behavior_recursively` to better clarity.

### CODE REVIEW

File: scene/gui/control.cpp [hunk 1]
```diff
@@ -1875,21 +1875,25 @@ Control::MouseFilter Control::get_mouse_filter_with_recursive() const {
 }
 
 void Control::set_mouse_recursive_behavior(RecursiveBehavior p_recursive_mouse_behavior) {
-	ERR_MAIN_THREAD_GUARD;
```
Comment (KoBeWi) [inline scene/gui/control.cpp:1878]: I think the thread guard should be before accessing `data` (although not sure).

File: scene/gui/control.cpp [hunk 2]
```diff
@@ -2059,21 +2063,25 @@ Control::FocusMode Control::get_focus_mode_with_recursive() const {
 }
 
 void Control::set_focus_recursive_behavior(RecursiveBehavior p_recursive_focus_behavior) {
-	ERR_MAIN_THREAD_GUARD;
-	ERR_FAIL_INDEX((int)p_recursive_focus_behavior, 4);
```
Comment (KoBeWi) [inline scene/gui/control.cpp:2063]: Same here.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
