### PR TITLE
Fix cases of broken user:// paths.

### LINKED ISSUE #69366: naming project with file name with 2 or more prohibited characters causes user:// directory to not exist
### Godot version

3.5.1

### System information

Windows 10

### Issue description

I named my project something, and later renamed it with a colon and a period(not knowing of the problems). I later was adding saves and was using "user://save_game.save" like most people but it wasn't working. after a while we figured out that the problem was the colon in the project title made "user://" not functional (print(save_file.open("user://save_game.save", File.WRITE)) returned 7) i changed the name and now it works fine but the bug is still there.

### Steps to reproduce

On windows 10 (windows 11 doesnt work) Make a new project with two special characters in the project name (two colons, two periods, one colon one period, etc). Try to access "user://" one way is to do

var save_file = File.new();
print(save_file.open("user://save_game.save", File.WRITE));
save_file.close();

it should return 7 which is wrong, if you rename the project without a colon and try the code again it will return 0

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/10119154/project.zip)

### PR DESCRIPTION
**Pull request by reduz**
* Properly validate paths when supplying the project name.
* Ensures that the user data dir will always be valid.

Fixes #69366.

### CODE REVIEW

File: core/os/os.cpp [hunk 1]
```diff
@@ -203,16 +203,20 @@ uint64_t OS::get_embedded_pck_offset() const {
...
+	String safe_dir_name = p_dir_name;
 	Vector<String> invalid_chars = String(": * ? \" < > |").split(" ");
-	if (p_allow_dir_separator) {
+	if (p_allow_paths) {
 		// Dir separators are allowed, but disallow ".." to avoid going up the filesystem
 		invalid_chars.push_back("..");
+		safe_dir_name = safe_dir_name.replace("\\", "/").strip_edges();
 	} else {
 		invalid_chars.push_back("/");
+		invalid_chars.push_back(".");
```
Comment (akien-mga) [inline core/os/os.cpp:215]: Why do we need to forbid dots? Seems uqite restrictive.

Comment (reduz) [reply core/os/os.cpp:215]: This is for the userdata folder, which is not visible to the user either way. It avoids folders like "." or "..".

Comment (akien-mga) [reply core/os/os.cpp:215]: What if uses want to create `user://Jetpaca 2.0 Logs/`?

Comment (reduz) [reply core/os/os.cpp:215]: I think its pointless, but if it makes you happy I can change the check

**Comment by reduz** [comment]
Changed approach so dots are treated as a special case (I still think this is pointless, this dir is pretty much invisible). If still not good, I accept suggestions.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
