### PR TITLE
Fix slider size in compact mode

### LINKED ISSUE #96800: Slider background disappears when using compact mode
### Tested versions

Godot v4.3.stable

### System information

Fedora Linux 39 (KDE Plasma) - X11 - Vulkan (Forward+) 

### Issue description

Slider background disappears when using compact mode.

See RGB sliders
Screenshot_20240910_165054

Db slider
Screenshot_20240910_170436

### Steps to reproduce

Change to compact mode in Editor Settings

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Giganzo**
Fixes: https://github.com/godotengine/godot/issues/96800

After:
Screenshot_20240910_165012

Screenshot_20240910_170447

### CODE REVIEW

File: editor/themes/editor_theme_manager.cpp [hunk 1]
```diff
@@ -1418,18 +1418,18 @@ void EditorThemeManager::_populate_standard_styles(const Ref<EditorTheme> &p_the
 		// HSlider.
 		p_theme->set_icon("grabber_highlight", "HSlider", p_theme->get_icon(SNAME("GuiSliderGrabberHl"), EditorStringName(EditorIcons)));
 		p_theme->set_icon("grabber", "HSlider", p_theme->get_icon(SNAME("GuiSliderGrabber"), EditorStringName(EditorIcons)));
-		p_theme->set_stylebox("slider", "HSlider", make_flat_stylebox(p_config.dark_color_3, 0, p_config.base_margin / 2, 0, p_config.base_margin / 2, p_config.corner_radius));
-		p_theme->set_stylebox("grabber_area", "HSlider", make_flat_stylebox(p_config.contrast_color_1, 0, p_config.base_margin / 2, 0, p_config.base_margin / 2, p_config.corner_radius));
-		p_theme->set_stylebox("grabber_area_highlight", "HSlider", make_flat_stylebox(p_config.contrast_color_1, 0, p_config.base_margin / 2, 0, p_config.base_margin / 2));
+		p_theme->set_stylebox("slider", "HSlider", make_flat_stylebox(p_config.dark_color_3, 0, MAX(2, p_config.base_margin / 2), 0, MAX(2, p_config.base_margin / 2), p_config.corner_radius));
```
Comment (akien-mga) [inline editor/themes/editor_theme_manager.cpp:1421]: Since it's used 12 times, I think it's worth extracting `MAX(2, p_config.base_margin / 2)` to a `const int` calculated before the HSlider / VSlider blocks.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.
