### PR TITLE
Export nested nodes in TileSet scenes; resolves #8819.

### LINKED ISSUE #8819: TileSet Exporter does not export nested sprites
**Operating system or device - Godot version:**

Arch Linux; Godot 2.1.3 official

**Issue description:**

When converting a TileSet scene into a TileSet resource, the exporter requires the sprites to be top-level or one child down. For example, if you had a scene with the hierarchy:

```
+ root
|
+-+ dirt
| +- dirt-center
| +- dirt-top
| +- dirt-bottom
|
+-+ grass
| +- grass-1
| +- grass-2
|
+-+ nuclear-barrel
```

the TileSet exporter would export only `dirt-center`, `grass-`, and `nuclear-barrel`. This is because of the non-recursive nature of the parser.

#5816 is potentially related.

**Steps to reproduce:**

1. Create a new TileSet scene.
2. Create a hierarchy of nodes.
3. Scene > Convert To > TileSet
4. Most of the nested tiles are missing.

The fix for this should be pretty simple. I'm working on one right now, and if it works properly, I'll submit a PR soon.

### PR DESCRIPTION
**Pull request by zlsa**
Adds _import_node() that, when used in conjunction with _import_scene, recurses through the scene tree and exports all available nodes.

*Important note:* This is not tested with nested sprites, although it should work. More eyes on this are gladly welcome.

### CODE REVIEW

File: editor/plugins/tile_set_editor_plugin.cpp [hunk 1]
```diff
@@ -35,24 +35,19 @@ void TileSetEditor::edit(const Ref<TileSet> &p_tileset) {
...
+		Node *child = p_node->get_child(i);
 
-			} else
-				continue;
+		if(!child->cast_to<Sprite>()) {
+			if(child->get_child_count() > 0) {
+				_import_node(child, p_library);
+			}
+      
+      continue;
```
Comment (akien-mga) [inline editor/plugins/tile_set_editor_plugin.cpp]: Indentation issue, you used spaces instead of tabs.

File: editor/plugins/tile_set_editor_plugin.cpp [hunk 2]
```diff
@@ -136,6 +131,13 @@ void TileSetEditor::_import_scene(Node *scene, Ref<TileSet> p_library, bool p_me
 	}
 }
 
+void TileSetEditor::_import_scene(Node *p_scene, Ref<TileSet> p_library, bool p_merge) {
+  if (!p_merge)
```
Comment (akien-mga) [inline editor/plugins/tile_set_editor_plugin.cpp]: Same here.

**Comment by akien-mga** [comment]
Could you squash the two commits together? See http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

Also if you could make the corresponding PR for the *master* branch, that would be nice. I prefer not to merge new features in the stable branch unless they are implemented in the development branch too.

**Comment by zlsa** [comment]
Closed in favor of #8838, which is based on master.

**Comment by akien-mga** [comment]
Well I wouldn't mind merging that one *too* :)
