### PR TITLE
Fix missing gutter icon for inner class method overrides

### LINKED ISSUE #69023: Override gutter icon does not show for inner classes
### Godot version

4.0.dev (e3a51e53ef055a1fe94351b68173c6dfcd2cb371)

### System information

Windows 10

### Issue description

The script editor does not show the override gutter icon when overriding a method of an inner class:

image

### Steps to reproduce

```gdscript
extends Node2D

func _draw() -> void:   # override icon :)
	pass

class Inner extends Node2D:
	func _draw() -> void:   # no icon :(
		pass
```

### Minimal reproduction project

See above code snippet.

### PR DESCRIPTION
**Pull request by brno32**
Fixes https://github.com/godotengine/godot/issues/69023

Also handles inner, inner classes! And inner, inner, inner classes... and so on.
Cap

### CODE REVIEW

File: editor/plugins/script_text_editor.cpp [hunk 1]
```diff
@@ -1164,11 +1164,20 @@ void ScriptTextEditor::_update_connected_methods() {
 	// Add override icons to methods.
 	methods_found.clear();
 	for (int i = 0; i < functions.size(); i++) {
-		StringName name = StringName(functions[i].get_slice(":", 0));
+		String raw_name = functions[i].get_slice(":", 0);
+		StringName name = StringName(raw_name);
 		if (methods_found.has(name)) {
```
Comment (RedMser) [inline editor/plugins/script_text_editor.cpp:1169]: Further down it's doing methods_found.insert on the shortened name. But up here you're comparing the full name, including period. I believe you'll need to tweak the insert to use the full name as well.

**Review by RedMser — APPROVED** [review]

**Comment by RedMser** [comment]
Haven't tested but code changes look good.

File: editor/plugins/script_text_editor.cpp [hunk 2]
```diff
@@ -1164,11 +1164,20 @@ void ScriptTextEditor::_update_connected_methods() {
...
 			continue;
 		}
 
+		// Account for inner classes
+		if (raw_name.contains(".")) {
+			// Strip inner class name from the method, and always grab last since
+			// our inner class might be inside another inner class
+			PackedStringArray parts = raw_name.split(".");
+			name = StringName(parts[parts.size() - 1]);
+		}
```
Comment (Paulb23) [inline editor/plugins/script_text_editor.cpp:1179]: Can avoid the split by doing something like this?
```
int pos = rfind(".");
if (pos != -1) {
	name =  substr(pos + 1);
}
```

**Review by Paulb23 — COMMENTED** [review]
Small note inline otherwise looks good.

File: editor/plugins/script_text_editor.cpp (hunk 2 above)
Comment (RedMser) [reply editor/plugins/script_text_editor.cpp]: I think they meant you can remove the contains check as well, since if it doesn't contain a period it will return -1

**Comment by akien-mga** [comment]
Thanks!
