### PR TITLE
Deleting only repeating "Scripted Variables" props

### LINKED ISSUE #43491: Script properties coming from `_get_property_list` are no longer shown in inspector
Godot 3.2.4 adf2dabbde23fdd89803871e26dd1d33ca20bf77
Windows 10 64 bits

From report https://github.com/Zylann/godot_heightmap_plugin/issues/216#issuecomment-726427174
My plugin makes extensive use of `_get_property_list` to add specific hints and categories to its exported variables and make a few dynamic ones appear, which worked in Godot 3.2.3. However, it appears the commit 8a02f221b468056345b7506a463a8c8b529bfb29 now prevents all these properties from appearing.

Godot3 MRP:
[CustomPropertyList.zip](https://github.com/godotengine/godot/files/5534471/CustomPropertyList.zip)
Open main scene, select root node. The first property is the only one exported with the `export` keyword. There are many others supposed to be visible, but in master they aren't showing up anymore.

Godot4 MRP:
https://github.com/godotengine/godot/issues/43491#issuecomment-1001666589

### LINKED ISSUE #54410: Inspector does not display properties without category
### Godot version

v4.0.dev.custom_build [61786f803]

### System information

Windows 10

### Issue description

If script usages `_get_property_list()` method Inspector does not display properties without custom Category.

### Steps to reproduce

Create a script with a `_get_property_list()` method without a category. 

### Minimal reproduction project

[demo-project.zip](https://github.com/godotengine/godot/files/7445846/demo-project.zip)

### LINKED ISSUE #58239: GDScript 2.0: Advanced exports (`_get_property_list()`) don't work
### Godot version

v4.0-alpha2

### System information

Windows 10 64-bit, GPU: NVIDIA Geforce GTX 1650 Ti, CPU: AMD Ryzen 7 4800H

### Issue description

I was doing some stuff in Godot 4 and I realize Advanced exports don't work. While `@export`s still work, advanced ones with `_get_property_list` don't. I have no idea why this happens so its probably a bug (unless they changed the syntax since the 4.0 documentation is even less helpful than the 3.x one). I made the code below in the `Steps to reproduce` section almost compatible with 3.x (You have to replace the first line with `tool` instead of `@tool`). And in 3.x it works perfectly.

Please Fix this bug.

### Steps to reproduce

1. Add a `Node`
2. Attach a script to the `Node`
3. Paste in the following code:
```gdscript
@tool 
extends Node

var rotate_enabled: bool = false

func _get_property_list() -> Array:
	var properties: Array = []
	properties.append({
		name = "Rotate",
		type = TYPE_NIL,
		hint_string = "rotate_",
		usage = PROPERTY_USAGE_GROUP | PROPERTY_USAGE_SCRIPT_VARIABLE,
	})
	properties.append({
		name = "rotate_enabled",
		type = TYPE_BOOL,
		usage = PROPERTY_USAGE_DEFAULT,
	})
	return properties
```
4. Click on the `Node`
5. You can't see any catogories

### Minimal reproduction project

_No response_

### LINKED ISSUE #63454: Tool scripts export categories and their properties to the inspector twice
### Godot version

4.0.alpha12.official [2c11e6d9e]

### System information

Windows 10

### Issue description

Tool scripts that export properties under a category using `@export_category` will have this category and properties shown twice in the inspector.
image

image

### Steps to reproduce

From a new project:

1. Create a tool script and attach it to whichever object it extends.
2. Use the `@export_category` annotation to add a category.
3. Export one or more properties.
4. Inspect the object with the tool script attached.
5. Note how the category and properties are displayed twice.

From the reproduction project:

1. Open `new_resource.tres`.
2. Note how the "Category" category and its associated properties are displayed twice.

### Minimal reproduction project

[Duplicate Property Repro.zip](https://github.com/godotengine/godot/files/9183794/Duplicate.Property.Repro.zip)

### PR DESCRIPTION
**Pull request by object71**
Fixes #58239
Fixes #43491
Fixes #54410

As described in the linked issue more properties were deleted from the initial "Scripted Variables" section than needed. My changes will perserve additional properties defined in ```_get_property_list``` but it won't categorize them properly when a few user  scripts are extended.

_Bugsquad edit: Also fixes https://github.com/godotengine/godot/issues/63454_

### CODE REVIEW

**Comment by TheSecondReal0** [comment]
This is an absolute life saver! I'd just finished porting my project to 4.0 alpha 3 to find that all of my custom exports were broken and this PR fixed it. I've been using the build artifact ever since and everything seems to be working as expected even when I'm doing some weird stuff with inherited custom classes.

**Comment by object71** [comment]
btw do i need to do something for a PR to get reviewed?

**Comment by Calinou** [comment]
> btw do i need to do something for a PR to get reviewed?

No, but since there is a lot of backlog for reviewing PRs, it may take a while for this PR to be merged. Sorry for the inconvenience.

**Comment by object71** [comment]
> > btw do i need to do something for a PR to get reviewed?
> 
> No, but since there is a lot of backlog for reviewing PRs, it may take a while for this PR to be merged. Sorry for the inconvenience.

Thanks, there is no inconvenience.

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -3627,11 +3638,6 @@ void EditorInspector::_update_script_class_properties(const Object &p_object, Li
 	// NodeC -> C props... -> NodeB..C..
```
Comment (akien-mga) [inline editor/editor_inspector.cpp:3638]: The comment is likely no longer accurate.

File: editor/editor_inspector.cpp [hunk 2]
```diff
@@ -3618,6 +3618,17 @@ void EditorInspector::_update_script_class_properties(const Object &p_object, Li
 			added.insert(pi.name);
 
 			r_list.insert_before(insert_here, pi);
+
+			List<PropertyInfo>::Element *prop_bellow = bottom->next();
```
Comment (akien-mga) [inline editor/editor_inspector.cpp:3622]: Typo: `prop_below`.

**Comment by object71** [comment]
> 

Indeed the problem is that ```get_script_property_list``` on line 3609 doesn't produce all the properties that are related to a single script (the missing ones are the ones defined by the user in gdscript but not through the ```export``` keyword. My solution on the other hand solves the problem by not deleting any properties that couldn't be categorized which is somewhere to start from and would solve the general issue and any further issues of this kind.

It is still better to not be trigger-happy with the deleting of properties and then solve the problem of them not being categorized in the proper script.

**Comment by YuriSizov** [comment]
So while investigating https://github.com/godotengine/godot/issues/63454 I've run into issues with code from https://github.com/godotengine/godot/pull/32428 as well, came to the same conclusions, and that in turn led me here. It's a very weird solution, originally, to remove everything from the `bottom` item to till the next category. It doesn't support `_get_property_list` for some reason (might be a GDScript module issue), and it doesn't work with the new grouping annotations.

This PR seems to fix https://github.com/godotengine/godot/issues/63454 and it works correctly with the issues it was set to fix, according to my limited testing. I'm going to approve it, as the code and the approach makes more sense to me than what we have right now. But I think this piece of code, the entire `_update_script_class_properties` method, is problematic.

**Review by YuriSizov — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by reduz** [comment]
I have no problem in merging this, but it should have comments of what it fixes and why because its basically a hack.
