### PR TITLE
Make CanvasItem's "drawing outside of NOTIFICATION_DRAW" error a macro

### LINKED ISSUE #75376: Cannot call Callable in a draw method (because no way to set_object on Callable?)
### Godot version

v4.0.1.stable.official [cacf49999]

### System information

Windows 11

### Issue description

If you try to pass a lambda/callable to be used inside a draw function, you get the error below. As far as I can tell, this is because the object that the callable is attached to is NOT the class that is calling the _draw function, so Godot doesn't recognize that it's actually being called inside `_draw` ?

```
 Drawing is only allowed inside NOTIFICATION_DRAW, _draw() function or 'draw' signal.
  <C++ Error>    Condition "!drawing" is true.
  <C++ Source>   scene/main/canvas_item.cpp:599 @ draw_rect()
````

### Steps to reproduce

```gdscript
class CustomDrawNode extends Node2D:
	var draw_func:Callable
	
	func _init(custom_draw_func:Callable):
		draw_func = custom_draw_func

	func _draw():
		draw_func.call()

# Then instantiate this as follows
var custom_draw_node = CustomDrawNode.new(func(): draw_rect(Rect2(0.0, 0.0, 100.0, 100.0), Color.GREEN)
	)
add_child(custom_draw_node)
```

I think to fix this I would want to do something like 

```gdscript
draw_func.set_object(self)
```

so that the passed in `custom_draw_func` can be called with the `CustomDrawNode` as its self? 

### Minimal reproduction project

N/A

Can be reproduced completely with the snippet above.

### PR DESCRIPTION
**Pull request by Mickeon**
The premise is simple:
image
Imagine this but 25 times.

I also took the chance to improve upon the error message itself. At least, attempted to.

Please give suggestions for a better macro name, I do not know the pattern.

Resolves #75376.

### CODE REVIEW

File: scene/main/canvas_item.h [hunk 1]
```diff
@@ -427,4 +427,10 @@ class CanvasTexture : public Texture2D {
 	~CanvasTexture();
 };
 
+#ifdef DEBUG_ENABLED
```
Comment (AThousandShips) [inline scene/main/canvas_item.h:430]: This is a change, might be desired but needs to be considered

Comment (AThousandShips) [reply scene/main/canvas_item.h:430]: Have you tested what happens on a release build when violating this? If it crashes or glitches instead of handling it gracefully it shouldn't be changed

Comment (Mickeon) [reply scene/main/canvas_item.h:430]: Good question. My guess is _something_ will screw up, but actually seeing crashes or glitches will be pretty difficult with a simple example.
About unexpected behavior you could make the same argument with the THREAD_GUARD though. I copied this snippet from it.

Comment (AThousandShips) [reply scene/main/canvas_item.h:430]: I'd just remove that part, and make it safe, deciding to make a check debug only needs quite a bit of testing IMO, for cleaning up it's not worth the risk

Comment (Mickeon) [reply scene/main/canvas_item.h:430]: Can do. Worth revisiting in my opinion, though. "Drawing outside of draw" is _one_ highly unlikely scenario in a final project, more unlikely than most.

Comment (AThousandShips) [reply scene/main/canvas_item.h:430]: It's an extremely cheap check so it'd only be worth it to remove annoying errors that the end user can't resolve

But there's cases where code behaves differently in release, so it's still reasonable to detect I'd say during development, especially if it causes glitches

**Comment by Mickeon** [comment]
I do not have the capacity to test any of this so I just stripped the DEBUG_ENABLED

**Review by AThousandShips — APPROVED** [review]
LGTM

Worth doing a future pass to see if it's something to make a debug only check, but generally we don't make that distinction unless it's very development side, if it's possible without weird side effects it'd be worth considering, but since the check is so cheap I don't think it's worth evaluating on it's own, maybe a future sweep for different checks would be something to consider

**Comment by kleonc** [comment]
>I also took the chance to improve upon the error message itself. At least, attempted to.

This should resolve #75376. But maybe the error message should also explicitly state what `this` and `CanvasItem::current_item_drawn` are when the error happens? Directly pointing out the problematic nodes should make debugging / understanding what's the problem much easier.

**Comment by Mickeon** [comment]
I do agree and I tried to do that. Problem is I just couldn't find a nice "spot" to explicitly state both.

**Comment by AThousandShips** [comment]
`CanvasItem::current_item_drawn` will always be `nullptr` when `drawing` is false though

**Comment by Mickeon** [comment]
Yeah, that one cannot be done. But the node name can.

**Comment by AThousandShips** [comment]
Risks causing unhelpful editor paths indeed, like parenting errors at times `root/@EditorNode@17034/@Panel@13/@VBoxContainer@14/@HSplitContainer@17/@HSplitContainer@25/@VSplitContainer@27/@TabContainer@29/Scene/@P`

**Comment by Mickeon** [comment]
I thought about it and I cannot fit the name anywhere. I wish there was a standard way to mention it.
``vformat("Node (%s) cannot draw outside of its drawing routine. Drawing is only allowed inside this node's `_draw()`, functions connected to its `draw` signal, or when it receives NOTIFICATION_DRAW.", )``

But this is bad already.
image
Of course that doesn't mean errors shouldn't be more explicit, and the Errors tab should be MUCH IMPROVED for this, but for this message any longer and it's just plain irritating.
This behavior is already documented but perhaps it needs to be even more explicit, as what the "drawing routine" is isn't exactly clear on the surface.

File: scene/main/canvas_item.h [hunk 2]
```diff
@@ -427,4 +427,6 @@ class CanvasTexture : public Texture2D {
 	~CanvasTexture();
 };
 
+#define ERR_DRAW_GUARD ERR_FAIL_COND_MSG(!drawing, "Drawing is only allowed inside this node's `_draw()`, functions connected to its `draw` signal, or when it receives NOTIFICATION_DRAW.");
```
Comment (akien-mga) [inline scene/main/canvas_item.h:430]: Since it's only used in `canvas_item.cpp`, it should be moved there.

Otherwise it's going to be available to anything that includes `canvas_item.h` (like 2/3rd the nodes and all editor code), while it's not actually usable there since `drawing` is a member of `CanvasItem`.

Comment (akien-mga) [reply scene/main/canvas_item.h:430]: Also, nitpicky but I would style it like this:
```suggestion
#define ERR_DRAW_GUARD \
		ERR_FAIL_COND_MSG(!drawing, "Drawing is only allowed inside this node's `_draw()`, functions connected to its `draw` signal, or when it receives NOTIFICATION_DRAW.")
```
And note I removed the semicolon - this would make sure `ERR_DRAW_GUARD` needs to be used with a semicolon to look like a method / be consistent. And avoid otherwise getting two semicolons in a row after the pre-processor does its magic.

**Comment by Mickeon** [comment]
Applied both suggestions. Note that the ERR_THREAD_GUARDs are not formatted the same way.

File: scene/main/canvas_item.cpp [hunk 3]
```diff
@@ -1683,3 +1683,6 @@ CanvasTexture::~CanvasTexture() {
 	ERR_FAIL_NULL(RenderingServer::get_singleton());
 	RS::get_singleton()->free(canvas_texture);
 }
+
+#define ERR_DRAW_GUARD \
```
Comment (akien-mga) [inline scene/main/canvas_item.cpp:1687]: Does this work with this being at the end of the file? I would expect it at the start (after includes, by convention).

Comment (Mickeon) [reply scene/main/canvas_item.cpp:1687]: I didn't know that was the convention. I will move it all the way up.

Comment (akien-mga) [reply scene/main/canvas_item.cpp]: Well it's not _just_ a convention ;)
```
$ cat main.cpp 
int main() {
        return SOME_VALUE;
}

#define SOME_VALUE 1
$ g++ main.cpp 
main.cpp: In function ‘int main()’:
main.cpp:2:16: error: ‘SOME_VALUE’ was not declared in this scope
    2 |         return SOME_VALUE;
      |                ^~~~~~~~~~
main.cpp:2:16: note: the macro ‘SOME_VALUE’ had not yet been defined
main.cpp:5: note: it was later defined here
    5 | #define SOME_VALUE 1
      |
```

**Review by akien-mga — APPROVED** [review]

**Review by AThousandShips — APPROVED** [review]
Re-confirming, let's take a look later at a standardized and low-clutter way to convey where errors occur as per the suggestions above, but looks good just as a cleanup

**Comment by kleonc** [comment]
> `CanvasItem::current_item_drawn` will always be `nullptr` when `drawing` is false though

Not really, you can call `draw_x` methods on a different CanvasItem than `current_item_drawn` and it will result in such errors, as such other CanvasItem is not `drawing` at that point (`drawing` is non-static contrary to `current_item_drawn`).
That's exactly when the current error message (pre this PR) would confuse people when they try to do something like:
```gdscript
extends Node2D
func _draw():
	# When this is called `current_item_drawn` is `self`.
	some_other_canvas_item.draw_circle(...) # Any `draw_x` method called on non-self canvas item.

	# Error: "Drawing is only allowed inside NOTIFICATION_DRAW, _draw() function or 'draw' signal."
	# User: What do you mean?! It is in `_draw()`...
```

The error being changed to:
```
"Drawing is only allowed inside this node's `_draw()`, functions connected to its `draw` signal, or when it receives NOTIFICATION_DRAW."
```
already makes the error message correct/clearier. :+1:

---

Regarding further improvement - yeah, I agree it's out of scope of this PR. I'm also not sure what would be a good way to refer to the problematic nodes. Path seems too long, just names too vague, `Node::to_string` which includes ObjectID not "friendly enough" and still it doesn't provide info the path does, etc. 

---

BTW it could be also considered to have slightly different error messages depending on the case, like:
```cpp
ERR_FAIL_COND_MSG(current_item_drawn == nulltpr, "..."); // Not in drawing routine at all.
ERR_FAIL_COND_MSG(current_item_drawn != this, "..."); // In drawing routine of a different CanvasItem.
```
(`drawing` bool would be no longer needed if the error conditions would be changed like that.)

Wondering if something like this could make things clearer even if not directly specifying what canvas item(s) this happened for. But also not sure how doubling the checks would affect performance.

Just a thought, not saying it should be done in here. This PR is fine as is.

**Review by kleonc — APPROVED** [review]

**Comment by Mickeon** [comment]
Speaking of the much prior topic, if only checking for `drawing` in debug builds has a good chance of breaking things in release builds. I have to question how bad things can break when the raw RenderingServer methods try to draw outside of the routine, as well? If that's even possible?

**Comment by akien-mga** [comment]
Thanks!
