### PR TITLE
Fix issue with OpenXR environment blend mode not being applied properly

### LINKED ISSUE #81338: Passthrough not working on Godot 4 OpenXR with a Varjo XR3 Headset
### Godot version

4.1

### System information

Windows 10 - Godot 4.1.1 - Compatibility

### Issue description

When trying to use the Varjo XR3 headset (in OpenXR mode) with Godot 4 (with OpenXR and passthrough activated), the passthrough does not work, i.e. the scene is rendered on a black background instead of the camera stream.

It seems to me that are two problems in the openxr module, more precisely in the openx_api.cpp file (fixing them solves  the issue) : 

1. The XR_COMPOSITION_LAYER_BLEND_TEXTURE_SOURCE_ALPHA_BIT  is only set when the number of layers is > 1, which is fine for the Meta Quest headset but does not work for the Varjo since it only requires one layer. 
2. The environment blend mode XR_ENVIRONMENT_BLEND_MODE_ALPHA_BLEND  is only really set when the XRFbPassthrough extension is present, which is not the case with the Varjo runtime. 

I am not sure how to fix this without causing issues for other headsets.

1. Would it be an issue to always activate the XR_COMPOSITION_LAYER_BLEND_TEXTURE_SOURCE_ALPHA_BIT ? 
2. Could blend modes be activated even if they are not supported by an extension ? 

### Steps to reproduce

- Create a Godot 4 project with OpenXR activated in Compatibility mode
- Add the code to activate OpenXr and to enable passthrough : https://docs.godotengine.org/en/stable/tutorials/xr/openxr_passthrough.html#passthrough-extension
- Start the Varjo Base software and activate OpenXR
- Run the Godot project

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by BastiaanOlij**
This PR ensures environment blending is properly applied by setting the `XR_COMPOSITION_LAYER_BLEND_TEXTURE_SOURCE_ALPHA_BIT` flag if needed when submitting our images to OpenXR. 

While fixing this I also improved some of the checking and added a project settings flag for this.

Fixes #81338

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
@hitmuri please let me know if this solves your issue properly.

File: modules/openxr/openxr_api.cpp [hunk 1]
```diff
@@ -2028,6 +2057,21 @@ OpenXRAPI::OpenXRAPI() {
 				break;
 		}
 
+		int ebm = GLOBAL_GET("xr/openxr/environment_blend_mode");
```
Comment (AThousandShips) [inline modules/openxr/openxr_api.cpp:2060]: Is `blend_mode` used here, otherwise I think it'd be more descriptive

Comment (BastiaanOlij) [reply modules/openxr/openxr_api.cpp:2060]: Not entirely sure what you mean by that?

This is basically the default mode for the environment blend mode that you can set in project settings so it is applied seeing OpenXR starts before any user code is run.

Comment (AThousandShips) [reply modules/openxr/openxr_api.cpp:2060]: Meant a clearer name over `ebm`

Comment (BastiaanOlij) [reply modules/openxr/openxr_api.cpp:2060]: Environment in this case has nothing to do with the Godot environment, it's the environment in which the XR headset is used. In most practical situations, the environment referring to the real world around you, ergo how do we blend the camera image together with what is being rendered?

**Comment by hitmuri** [comment]
> @hitmuri please let me know if this solves your issue properly.

Yes it works perfectly now. Thanks !

File: modules/openxr/openxr_api.cpp (hunk 1 above)
Comment (BastiaanOlij) [reply modules/openxr/openxr_api.cpp:2060]: Ah, ok no worries, because those temporary variables overlap in name with the actual member variables I shorthanded them. It's just to do the integer to proper enum conversion :)

**Review by m4gr3d — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!
