### PR TITLE
Fixed resource loading when editing built-in script from resource

### LINKED ISSUE #27380: Editor crashes when editing a resource script: "Object was deleted while awaiting a callback"
**Godot version:**
3.1

**OS/device including version:**
Windows 10 Pro x86-64
AMD Ryzen 1800X
Nvidia Geforce GTX 1060

**Issue description:**
After creating a new resource, I created a new GDScript under "Reference->Script" in the inspector and saved. Reselecting this script from the inspector makes Godot crash with _"Object was deleted while awaiting a callback"_.
I tried deleting the contents of Roaming/Godot/projects/ already, did not solve the problem.

grafik

**Steps to reproduce:**
1) Create a new resource by right-clicking in the filesystem on the _"res://"_ folder -> _"New Resource"_.
2) Go into the resource's _"Reference"_ tab within the inspector, create a new GDScript and save.
3) Reopen the project and click again on the script within the _"Reference"_ tab

**Minimal reproduction project:**
[bug.zip](https://github.com/godotengine/godot/files/3000564/bug.zip)

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
Before it wasn't handling the special case of a built-in script within a resource, and was trying to load it as a scene, which was causing a recursive loading in some cases.

Fixes #27380

### CODE REVIEW

File: editor/plugins/script_editor_plugin.cpp [hunk 1]
```diff
@@ -3463,15 +3471,16 @@ void ScriptEditorPlugin::edit(Object *p_object) {
...
 
-			script_editor->call_deferred("edit", p_script);
-		} else {
-			script_editor->edit(p_script);
+		if (_is_built_in_script(p_script) && !EditorNode::get_singleton()->is_scene_open(res_path)) {
+			if (ResourceLoader::get_resource_type(res_path) == "PackedScene") {
+				EditorNode::get_singleton()->load_scene(res_path);
+			} else {
+				EditorNode::get_singleton()->load_resource(res_path);
+			}
```
Comment (Paulb23) [inline editor/plugins/script_editor_plugin.cpp]: The if's here should align with the other ones, checking for the open scene after it's confirmed to be a `PackedScene`.

**Review by Paulb23 — CHANGES_REQUESTED** [review]

File: editor/plugins/script_editor_plugin.cpp (hunk 1 above)
Comment (pouleyKetchoupp) [reply editor/plugins/script_editor_plugin.cpp]: Done!

**Review by Paulb23 — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
