### PR TITLE
Use half float precision buffer for 3D when HDR2D is enabled

### LINKED ISSUE #7878: Allow the Mobile rendering method to use 16 bpc HDR instead of 10 bpc
### Describe the project you are working on

a 3D game that focuses on somewhat high quality visuals.

### Describe the problem or limitation you are having in your project

No HDR in the Mobile Renderer

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add an option in project settings to opt-in for HDR for vulkan mobile , similar to how unreal engine does it : 
image

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I am no expert at rendering code so N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, the renderer can't be modified through scripts.

### Is there a reason why this should be core and not an add-on in the asset library?

Vulkan Mobile Renderer is a core feature.

### LINKED ISSUE #86098: 4.2 World Environment Glow Effect - Makes Everything Glow
### Tested versions

4.2 Stable

### System information

WIndows 10 Godot Steam Version - Mobile Mode

### Issue description

In Godot 3x World Environment used to be simple on choosing what object should glow, you just had to add the World Environment change **Background** to **Canvas** , and **Enable Glow**.

But in Godot 4x The World Environment glow makes everything to glow even the things they aren't supposed to glow.

### **Example Imagen**
image

### Steps to reproduce

1. Go to **Project** -> **Project Settings**, Scroll into section of **Rendering** -> **Viewport** -> **Enable HDR 2D**
2. Add a **Node**
3. In the **Node**, add **two Sprite2d** node and set one to **RAW(1.5,1.5,1.5)**
4. Add a **WorldEnvironment+Environment**, set background to Canvas, enable Glow
5. Change **Glow Mode** to **Screen**
6. See both of them are glowing

### Minimal reproduction project (MRP)

[Godot Test FIles.zip](https://github.com/godotengine/godot/files/13654207/Godot.Test.FIles.zip)

### LINKED ISSUE #106282: WorldEnvironment with background_mode Canvas is too bright in Mobile renderer
### Tested versions

- Reproducible in 4.4.1 stable

### System information

Godot v4.4.1.stable - Windows 11 (build 22631) - Multi-window, 1 monitor - Vulkan (Mobile) - integrated Intel(R) UHD Graphics 620 (Intel Corporation; 25.20.100.6519) - Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 threads)

### Issue description

I have been watching a few tutorials on adding HDR glow in Godot:

- https://www.youtube.com/watch?v=2emrbvigizI
- https://www.youtube.com/watch?v=14X_2WYZvRI
- https://www.youtube.com/watch?v=7R4NkOF5b2A

But when I try this (see steps to reproduce) I always get an instantly brighter scene.

Apparently this only happens for the Mobile renderer, not compatability.

### Steps to reproduce

Create new project with Mobile renderer.

Go to Project -> Project settings -> Rendering -> Viewport -> Enable HDR 2D

Make `WorldEnvironment` Node, add new `Environment`, set Background -> Mode to `Canvas`.

This has been consistend throughout all projects/set ups I have tried. 

### Minimal reproduction project (MRP)

[test_environment.zip](https://github.com/user-attachments/files/20150017/test_environment.zip)

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/86098
Fixes: https://github.com/godotengine/godot/issues/106282
Closes: https://github.com/godotengine/godot-proposals/issues/7878

This took a bit of refactoring. Originally we selected a 3D framebuffer format based purely on whether we were in the mobile renderer or the Forward+ renderer. For the 2D framebuffer, we selected based on the presence of the HDR2D setting. 

This created a strange incompatibility when using glow with HDR2D with the mobile renderer. Your 2D content would be rendered in HDR. Then copied into an LDR framebuffer. Then copied back to HDR with glow applied. 

While there is a theoretical benefit to using an LDR framebuffer in 3D (especially when using glow), it just isn't compatiblity with 2D HDR. It is much better quality-wise to keep everything in HDR from beginning to end. 

The biggest change is that we now look to the RenderBuffers class to determine if we should use an HDR format and whether we need to use a luminance multiplier. The RenderBuffers are automatically recreated if we switch to HDR, so this ensures that every part of the pipeline uses the same settings. 

Reflections and sky still use LDR always since they can be shared between several Viewports and not all viewports necessarily have the same HDR2D setting. In the future we may want to consider making ReflectionProbes and Sky always use HDR. But that decision is out of scope for this PR.

### CODE REVIEW

**Comment by beicause** [comment]
Does this mean even not targeting 2D, enabling `HDR 2D` will cause 3D to use an RGBAH buffer? (Related: https://github.com/godotengine/godot-proposals/issues/7878)

**Comment by clayjohn** [comment]
> Does this mean even not targeting 2D, enabling `HDR 2D` will cause 3D to use an RGBAH buffer? (Related: [godotengine/godot-proposals#7878](https://github.com/godotengine/godot-proposals/issues/7878))

That's right! Thank you for pointing that out

**Comment by beicause** [comment]
If so, this may cause a performance regression in 3D projects with HDR2D enabled, which could be unexpected (the term "HDR 2D" is not accurate anymore, docs need changes).

**Comment by clayjohn** [comment]
> If so, this may cause a performance regression in 3D projects with HDR2D enabled, which could be unexpected (the term "HDR 2D" is not accurate anymore).

That's right. We discussed the performance tradeoff at length in https://github.com/godotengine/godot/issues/86098 and in subsequent rendering meetings and decided that it was worth the change. If 2D is using full HDR, then the entire pipeline should use full HDR. 

That being said, its not necessarily going to be a performance regression because:
1. Not all games are bandwidth limited. This change only hurts bandwidth limited games
2. It opens up more opportunities to share resources between 2D and 3D which can have a positive impact on performance
3. Most modern phones support framebuffer compression for RGBA16 buffers now. So the original reason to limit to RGB10A2 is gone now for many devices
4. Once we support HDR output, this change is 100% necessary and will improve performance since we won't have to do a needless copy to promote the RGB10A2 buffer to full RGBA16. 
5. If users were already using HDR2D, they are paying the cost of having a RGBA16 buffer already, so they have already decided to accept reduced performance for the benefits it provides. 

Overall, we felt that making this change was worthwhile.

**Review by Calinou — COMMENTED** [review]
Tested locally on many demo projects and https://github.com/Calinou/godot-reflection, it works as expected.

However, the sky appears visibly darker in Truck Town when HDR 2D is enabled in the project settings:

https://github.com/user-attachments/assets/a6bbb2c8-97a3-48e2-a477-c6091f9313a9

This also carries over to the running project. However, reflection probes are not affected by this issue, even if you force them to update by moving them after changing the setting:

https://github.com/user-attachments/assets/1c73b6a9-3ad7-4532-ae2e-d4abef1ceee5

(The NaN you see in the reflection probe on the sun also occurs in `master`; I'll open a separate issue. **Edit:** https://github.com/godotengine/godot/issues/110207)

Either way, this has the upside of making viewport debanding functional in Mobile if HDR 2D is also enabled.

It's worth investigating for a future PR if we should also switch over the sky and reflection probes to HDR. This would improve visual consistency with Forward+ and increase the viability of HDR output for the Mobile renderer, but this needs its own proposal.

**Comment by clayjohn** [comment]
> It's worth investigating for a future PR if we should also switch over the sky and reflection probes to HDR. This would improve visual consistency with Forward+ and increase the viability of HDR output for the Mobile renderer, but this needs its own proposal.

See the last paragraph in the PR description above

> Reflections and sky still use LDR always since they can be shared between several Viewports and not all viewports necessarily have the same HDR2D setting. In the future we may want to consider making ReflectionProbes and Sky always use HDR. But that decision is out of scope for this PR.

**Comment by beicause** [comment]
The sky is draker in Forward+ even HDR 2D is disabled, but it's normal in Mobile:
屏幕截图_20250906_093247

Edit: This issue only happens with #110077, not this PR.

File: servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp [hunk 1]
```diff
@@ -3148,6 +3143,7 @@ void RenderForwardMobile::_mesh_compile_pipelines_for_surface(const SurfacePipel
 		for (uint32_t use_post_pass = post_pass_start; use_post_pass < post_pass_iterations; use_post_pass++) {
 			const uint32_t hdr_iterations = use_post_pass ? hdr_target_iterations : (hdr_start + 1);
 			for (uint32_t use_hdr = hdr_start; use_hdr < hdr_iterations; use_hdr++) {
+				const RD::DataFormat buffers_color_format = use_hdr ? RD::DATA_FORMAT_R16G16B16A16_SFLOAT : RD::DATA_FORMAT_A2B10G10R10_UNORM_PACK32;
```
Comment (allenwp) [inline servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp]: Is it possible for this format to be read from somewhere, like `get_base_data_format()` rather than being hardcoded?

**Comment by allenwp** [comment]
I'm actually not immediately sure why from glancing at the code changes, but this PR breaks debanding in the following configuration:
- Mobile renderer
- SMAA antialiasing
- HDR 2D disabled

View these screenshots in a dark viewing environment at 100% scaling:
| Godot 4.5 | This PR
|--|--
|godot-4 5|this-pr

MRP: [mobile-hdr-2d-debanding.zip](https://github.com/user-attachments/files/22452076/mobile-hdr-2d-debanding.zip)

SMAA causes the first tonemap pass to match the scene rendering buffer format, which is 10-bit when HDR 2D is disabled, so 10-bit debanding in the tonemap shader is required for this configuration.

The code that detects what buffer format should be used for debanding makes a lot of assumptions about data formats because the exact format of a given buffer isn't really saved in an accessible way for easy access. It's possible that the debanding code now thinks that this configuration is using a 16 bit buffer for even though it is actually using a 10 bit buffer?

Edit: Sorry, some of what I wrote in the first pass of this comment wasn't quite right... I think I've corrected it(?) To be honest, I need to dig deep into this every time I try and think about it because it's a little complicated to keep track of the different buffer formats used through the different passes with each renderer and HDR 2D configuration 😵‍💫

File: servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp (hunk 1 above)
Comment (clayjohn) [reply servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp]: Sure! updated

Comment (allenwp) [reply servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp]: Thanks!

**Comment by clayjohn** [comment]
@allenwp I think I may have fixed that issue in the last rebase when I fixed the conflicts. I can't repro that issue right now. Your MRP looks totally fine and matches the behaviour in Godot 4.5

Screenshot 2025-10-20 at 9 08 58 PM

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Comment by allenwp** [comment]
> @allenwp I think I may have fixed that issue in the last rebase when I fixed the conflicts. I can't repro that issue right now. Your MRP looks totally fine and matches the behaviour in Godot 4.5

Just got around to testing this and reviewing the updated PR that was merged: yes, this looks good! Thanks!
