### PR TITLE
Fix update order for `exclusive` child window

### LINKED ISSUE #92848: The FileDialog > Create New Folder popup should also be exclusive and not hide if you click on it's parent FileDialog pane.
### Tested versions

v4.3.dev5.official [c9c17d6ca]

### System information

Linux Kubuntu 23.04 KDE Plasma Version: 5.27.4 KDE Frameworks Version: 5.104.0 Qt Version: 5.15.8

### Issue description

When using the FileDialog node, the Create Folder popup should be forced to exclusive. If you click away by accident  (e.g. inside the the FileDialog panel), the popup hides behind the FileDialog panel and cannot be recovered (unless you know to drag the FileDialog away to find it). In that case you need to force close the application.

image

### Steps to reproduce

See reproduction attachment below.

- Create a main Node scene and add a FileDialog node with visible, exclusive, centered, size of main window (I used a small code snippet to position and size).
- Run the project
- Click on Create new folder button to the top right of the FileDialog
- The Create Folder popup should appear.
- Click inside the FileDialog pane
- The Create Folder popup hides behind. Cannot be recovered (unless you were able to drag the File Dialog pane away)

### Minimal reproduction project (MRP)

[Archive.zip](https://github.com/user-attachments/files/15685429/Archive.zip)

### LINKED ISSUE #94446: Bug: Create Folder in Godot Android
### Tested versions

-Reproducible in: Godot Android v4.2.2.stable
- Unable to check previous versions because it is early access and unable to download previous versions

### System information

Android - Godot 4.2.2stable - (forward, mobile, compatibility)

### Issue description

Whenever you select the browse option and then click on "Create Folder" option, and instead of writing the name click back, this should result in cancelling the naming process, but this process freezes the game

### Steps to reproduce

Create a new project, select browse in "Project Path", click on "Create Folder", after that, click back or touch somewhere on the screen except the keypad, the game will freeze. This doesn't only work in creating new project, but also in saving a scene, node, etc. Everywhere we have the "Create Folder" option after selecting browse 

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Alex2782**
Fixes #94446
Fixes #92848

Docs: [window-property-exclusive](https://docs.godotengine.org/en/stable/classes/class_window.html#class-window-property-exclusive)

> If true, the Window will be in exclusive mode. Exclusive windows are always on top of their parent and will block all input going to the parent Window.

-----------------------------------------

<details><summary>Tests</summary>

Android Editor **before**

https://github.com/user-attachments/assets/d0a2a457-039f-45c1-8aab-93d4499c4e6f

-----------------------

Android Editor **after**

https://github.com/user-attachments/assets/b8d84afd-dea8-4ad8-9665-b4fb553b34ef
</details>

### CODE REVIEW

File: editor/gui/editor_file_dialog.cpp [hunk 1]
```diff
@@ -2326,6 +2326,10 @@ EditorFileDialog::EditorFileDialog() {
 
 	makedialog = memnew(ConfirmationDialog);
 	makedialog->set_title(TTR("Create Folder"));
+#if !defined(WIN32) && !defined(X11_ENABLED)
+	// On WinOS and Linux X11: Windows with the 'on top' can't become transient.
+	makedialog->set_flag(FLAG_ALWAYS_ON_TOP, true);
```
Comment (bruvzg) [inline editor/gui/editor_file_dialog.cpp:2331]: This is definitly not a correct fix, being `exclusive` child (which it already is) should be enough to keep it on top of parent. 

The issue seems to be relevant only for embedded windows, so it's something wrong with subwindow handling in the `Viewport` code, and should be fixed there oinstead of adding random unrelated flags to the `Window`.

Comment (bruvzg) [reply editor/gui/editor_file_dialog.cpp:2331]: Probably in `Viewport::_sub_window_update_order()`, seems like it's not checking for exclusive children at all.

Comment (Alex2782) [reply editor/gui/editor_file_dialog.cpp:2331]: The following solution works with 2 `sub_windows`. 
Over the next few days, I will first check the effects on the editor GUI.

```cpp
	if (!gui.sub_windows[gui.sub_windows.size() - 1].window->get_flag(Window::FLAG_ALWAYS_ON_TOP)) {
		int index = gui.sub_windows.size() - 1;

		while (index > 0 && gui.sub_windows[index - 1].window->get_flag(Window::FLAG_ALWAYS_ON_TOP)) {
			--index;
		}

		//NEW CODE
		//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
		Window *exclusive_child = gui.sub_windows[index].window->get_exclusive_child();
		if (exclusive_child != nullptr) {
			while (index > 0 && gui.sub_windows[index - 1].window == exclusive_child) {
				--index;
			}
		}
		//-----------------------------------------------------------------------------------

		if (index != (gui.sub_windows.size() - 1)) {
			SubWindow sw = gui.sub_windows[gui.sub_windows.size() - 1];
			gui.sub_windows.remove_at(gui.sub_windows.size() - 1);
			gui.sub_windows.insert(index, sw);
		}
	}
```

**Comment by Alex2782** [comment]
Testproject: [bug_92848_CreateFolder.zip](https://github.com/user-attachments/files/16322771/bug_92848_CreateFolder.zip)






https://github.com/user-attachments/assets/c4bc004f-e4dd-45d5-be7e-4cefaace6ae9

**Comment by Repiteo** [comment]
Needs rebase

**Comment by Alex2782** [comment]
The bugfix seems to still be compatible with 4.6.dev, tested on MacOS.

`v4.6.dev.custom_build [085e95bea]`

https://github.com/user-attachments/assets/cc9f90e1-e1fa-4c1c-b5ba-cd1a236d1830

File: scene/main/viewport.cpp [hunk 2]
```diff
@@ -270,17 +270,31 @@ void Viewport::_sub_window_update_order() {
...
+			}
+			insert_index--;
 		}
+	}
 
-		if (index != (gui.sub_windows.size() - 1)) {
-			SubWindow sw = gui.sub_windows[gui.sub_windows.size() - 1];
-			gui.sub_windows.remove_at(gui.sub_windows.size() - 1);
-			gui.sub_windows.insert(index, sw);
+	// Reorder exclusive child's.
```
Comment (AThousandShips) [inline scene/main/viewport.cpp]:
```suggestion
	// Reorder exclusive children.
```
I assume that's what meant

**Comment by m4gr3d** [comment]
@bruvzg Ping on reviewing this bug fix.

**Review by bruvzg — APPROVED** [review]
Seems to be working as expected. Code looks good.

File: scene/main/viewport.cpp (hunk 2 above)
Comment (Alex2782) [reply scene/main/viewport.cpp]: Thanks! I've changed it. Did you suggest it three weeks ago, or is it a display bug?

image

Comment (Repiteo) [reply scene/main/viewport.cpp]: That usually means it was a queued review comment

**Comment by Repiteo** [comment]
Thanks!
