### PR TITLE
Better and non-buggy Polygon2D editing disabling

### LINKED ISSUE #25860: Dragging a Polygon2D with internal vertices can crash the editor (and other problems)
**Issue description:**
Dragging a Polygon2D with internal vertices has now been disabled thanks to 419fb45a3eea68516828fe4541a62f8641cf13ef by @reduz , the problem is that this created other problems:
- It prevents the polygon's node itself from being dragged in normal situations.
- When dragging it (by clicking and moving it in the canvas editor when not selected), it will initially get stuck on your mouse until you click outside the canvas editor, and then depending on your input (generally doing anything in the canvas editor again) will crash the editor, dumping this:

```
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x37e00) [0x7f19a8744e00] (??:0)
[2] Dictionary::operator[](Variant const&) const (/home/michael/git/godot/core/dictionary.cpp:86)
[3] Node2D::_edit_set_state(Dictionary const&) (/home/michael/git/godot/scene/2d/node_2d.cpp:49)
[4] Polygon2D::_edit_set_state(Dictionary const&) (/home/michael/git/godot/scene/2d/polygon_2d.cpp:44)
[5] CanvasItemEditor::_restore_canvas_item_state(List<CanvasItem*, DefaultAllocator>, bool) (/home/michael/git/godot/editor/plugins/canvas_item_editor_plugin.cpp:805)
[6] CanvasItemEditor::_gui_input_move(Ref<InputEvent> const&) (/home/michael/git/godot/editor/plugins/canvas_item_editor_plugin.cpp:1807 (discriminator 3))
[7] CanvasItemEditor::_gui_input_viewport(Ref<InputEvent> const&) (/home/michael/git/godot/editor/plugins/canvas_item_editor_plugin.cpp:2209)
[8] MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/michael/git/godot/./core/method_bind.gen.inc:729 (discriminator 12))
[9] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/michael/git/godot/core/object.cpp:945 (discriminator 1))
[10] Object::emit_signal(StringName const&, Variant const**, int) (/home/michael/git/godot/core/object.cpp:1231 (discriminator 1))
[11] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/michael/git/godot/core/object.cpp:1287)
[12] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (/home/michael/git/godot/scene/main/viewport.cpp:1534 (discriminator 2))
[13] Viewport::_gui_input_event(Ref<InputEvent>) (/home/michael/git/godot/scene/main/viewport.cpp:2128 (discriminator 3))
[14] Viewport::input(Ref<InputEvent> const&) (/home/michael/git/godot/scene/main/viewport.cpp:2663 (discriminator 2))
[15] Viewport::_vp_input(Ref<InputEvent> const&) (/home/michael/git/godot/scene/main/viewport.cpp:1319)
[16] MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/michael/git/godot/./core/method_bind.gen.inc:729 (discriminator 12))
[17] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/michael/git/godot/core/object.cpp:945 (discriminator 1))
[18] Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/michael/git/godot/core/object.cpp:870)
[19] SceneTree::call_group_flags(unsigned int, StringName const&, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/michael/git/godot/scene/main/scene_tree.cpp:262)
[20] SceneTree::input_event(Ref<InputEvent> const&) (/home/michael/git/godot/scene/main/scene_tree.cpp:418 (discriminator 6))
[21] InputDefault::_parse_input_event_impl(Ref<InputEvent> const&, bool) (/home/michael/git/godot/main/input_default.cpp:414)
[22] InputDefault::parse_input_event(Ref<InputEvent> const&) (/home/michael/git/godot/main/input_default.cpp:260)
[23] OS_X11::process_xevents() (/home/michael/git/godot/platform/x11/os_x11.cpp:2247 (discriminator 3))
[24] OS_X11::run() (/home/michael/git/godot/platform/x11/os_x11.cpp:2973)
[25] /home/michael/git/godot/bin/godot.x11.tools.64(main+0xdc) [0x115c412] (/home/michael/git/godot/platform/x11/godot_x11.cpp:56)
[26] /usr/lib/libc.so.6(__libc_start_main+0xf3) [0x7f19a8731223] (??:0)
[27] /home/michael/git/godot/bin/godot.x11.tools.64(_start+0x2e) [0x115c27e] (??:?)
-- END OF BACKTRACE --
```

### PR DESCRIPTION
**Pull request by YeldhamDev**
This implementation reverts 419fb45a3eea68516828fe4541a62f8641cf13ef and places a better option which enables moving the node, doesn't make the canvas editor unusable, as well as not crashing the editor itself.

Fixes #25860.

### CODE REVIEW

**Comment by akien-mga** [comment]
Git history wise, it would be better to start with a proper `git revert 419fb45`, and then add a second commit with the better fix. This way we know that 419fb45 was actually reverted, and not just tweaked. And if there are issues with the new version of the code, we only have the second commit to review for differences with previous releases.

**Comment by YeldhamDev** [comment]
@akien-mga Done.

**Comment by akien-mga** [comment]
@reduz says your better code should be OK, so let's merge :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by guilhermefelipecgs** [comment]
I'm getting this error to open the editor:
```
OpenGL ES 3.0 Renderer: GeForce GTX 970/PCIe/SSE2
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x37e00) [0x7f526ac52e00] (??:0)
[2] BaseButton::set_disabled(bool) (/home/guilherme/Workspaces/godot/scene/gui/base_button.cpp:314)
[3] AbstractPolygon2DEditor::disable_polygon_editing(bool, String) (/home/guilherme/Workspaces/godot/editor/plugins/abstract_polygon_2d_editor.cpp:283)
[4] AbstractPolygon2DEditor::AbstractPolygon2DEditor(EditorNode*, bool) (/home/guilherme/Workspaces/godot/editor/plugins/abstract_polygon_2d_editor.cpp:800 (discriminator 3))
[5] CollisionPolygon2DEditor::CollisionPolygon2DEditor(EditorNode*) (/home/guilherme/Workspaces/godot/editor/plugins/collision_polygon_2d_editor_plugin.cpp:44)
[6] CollisionPolygon2DEditorPlugin::CollisionPolygon2DEditorPlugin(EditorNode*) (/home/guilherme/Workspaces/godot/editor/plugins/collision_polygon_2d_editor_plugin.cpp:49)
[7] EditorNode::EditorNode() (/home/guilherme/Workspaces/godot/editor/editor_node.cpp:5770)
[8] Main::start() (/home/guilherme/Workspaces/godot/main/main.cpp:1587)
[9] /home/guilherme/Workspaces/godot/bin/godot.x11.tools.64(main+0xc9) [0x115d42f] (/home/guilherme/Workspaces/godot/platform/x11/godot_x11.cpp:54)
[10] /usr/lib/libc.so.6(__libc_start_main+0xf3) [0x7f526ac3f223] (??:0)
[11] /home/guilherme/Workspaces/godot/bin/godot.x11.tools.64(_start+0x2e) [0x115d2ae] (??:?)
-- END OF BACKTRACE --
```

File: editor/plugins/abstract_polygon_2d_editor.cpp [hunk 1]
```diff
@@ -778,24 +797,23 @@ AbstractPolygon2DEditor::AbstractPolygon2DEditor(EditorNode *p_editor, bool p_wi
 	selected_point = Vertex();
 	edge_point = PosVertex();
 
+	disable_polygon_editing(false, String());
```
Comment (akien-mga) [inline editor/plugins/abstract_polygon_2d_editor.cpp]: This call is too early, the buttons don't exist yet.

Comment (akien-mga) [reply editor/plugins/abstract_polygon_2d_editor.cpp]: I'd put this in `NOTIFICATION_READY` instead.

Comment (YeldhamDev) [reply editor/plugins/abstract_polygon_2d_editor.cpp]: Done, see #25958.
