### PR TITLE
Make Set methods obsolete

### LINKED ISSUE #30744: Should the Set methods be removed?
@neikeq So basically, this code fails with a compiler error:

    Transform.origin = Vector2.Zero; // Error CS1612 cannot modify return value.

I assumed that the Set method was a way to work around this problem:

    Transform.origin.Set(Vector2.Zero);

But after actually testing this... this code silently fails and does nothing at all! It seems that the `Set()` methods only work with variables that are otherwise settable with `=`:

    Vector2 a = Vector2.One;
    a.Set(Vector2.Zero); // Works.
    a = Vector2.Zero; // Or you can just do this...

Considering that they add nothing new and can silently fail, they should probably be removed.

If you run a blame on this file, you will see that Vector2's `Set` was added by... uh... me... but I was just trying to make Vectors consistent with Quat which [already had this](https://github.com/godotengine/godot/commit/ff97c97c930f80209480c630622b1b64372bd65a#diff-aff89657dda2c194037126619efa69b4L94). 

Quat also has `set()` [in core](https://github.com/godotengine/godot/blame/master/core/math/quat.h#L112), which is where it came from, so is / was there a purpose to Quat's `set()` method and what was it, and should it be removed too? It seems to have existed [before](https://github.com/godotengine/godot/blame/45438e9918d421b244bfd7776a30e67dc7f2d3e3/core/math/quat.h#L102) @akien-mga's very [musical commit](https://github.com/godotengine/godot/commit/5dbf1809c6e3e905b94b8764e99491e608122261#diff-46e3482d3d8d24cdcef5fb32c7380f82R97) (cc @reduz). I know that, for example, this works just fine in GDScript:

    transform.origin = Vector2.ZERO # Works

So, it's a good thing that @akien-mga rejected me adding this into core, as not only is it not a problem in GDScript, but also the "solution" doesn't work either...

Sorry for the long post, but I just wanted to post the whole story of `Set()` to my knowledge.

### PR DESCRIPTION
**Pull request by aaronfranke**
Mono: Declare all set methods obsolete and suggest using the constructors instead, fixes https://github.com/godotengine/godot/issues/30744

~~Core: Warn when using `set_axis_angle` and suggest using the constructor instead. Previously the constructor called the method, so I copied the logic.~~ We can delete the method in 4.0+. I looked into doing this for `set_euler` too, but the constructor doesn't work.

Partial follow-up to https://github.com/godotengine/godot/pull/21348

### CODE REVIEW

File: modules/mono/glue/Managed/Files/Quat.cs [hunk 1]
```diff
@@ -95,6 +95,7 @@ public Quat Normalized()
             return this / Length;
         }
 
+        [Obsolete("Deprecated, please use constructor and assignment instead.", true)]
```
Comment (neikeq) [inline modules/mono/glue/Managed/Files/Quat.cs]:
```C#
[Obsolete("Set is deprecated. Use the Quat(" + nameof(real_t) + ", " + nameof(real_t) + ", " + nameof(real_t) + ", " + nameof(real_t) + ") constructor instead.", error: true)]
```

File: modules/mono/glue/Managed/Files/Quat.cs [hunk 2]
```diff
@@ -103,16 +104,19 @@ public void Set(real_t x, real_t y, real_t z, real_t w)
             this.w = w;
         }
 
+        [Obsolete("Deprecated, please use constructor and assignment instead.", true)]
```
Comment (neikeq) [inline modules/mono/glue/Managed/Files/Quat.cs]:
```C#
[Obsolete("Set is deprecated. Use the Quat(" + nameof(Quat) + ") constructor instead.", error: true)]
```

File: modules/mono/glue/Managed/Files/Quat.cs [hunk 3]
```diff
@@ -103,16 +104,19 @@ public void Set(real_t x, real_t y, real_t z, real_t w)
...
         public void Set(Quat q)
         {
             this = q;
         }
 
+        [Obsolete("Deprecated, please use constructor and assignment instead.", true)]
```
Comment (neikeq) [inline modules/mono/glue/Managed/Files/Quat.cs]:
```C#
[Obsolete("SetAxisAngle is deprecated. Use the Quat(" + nameof(Vector3) + ", " + nameof(real_t) + ") constructor instead.", error: true)]
```

File: modules/mono/glue/Managed/Files/Quat.cs [hunk 4]
```diff
@@ -103,16 +104,19 @@ public void Set(real_t x, real_t y, real_t z, real_t w)
...
         public void SetAxisAngle(Vector3 axis, real_t angle)
         {
             this = new Quat(axis, angle);
         }
 
+        [Obsolete("Deprecated, please use constructor and assignment instead.", true)]
```
Comment (neikeq) [inline modules/mono/glue/Managed/Files/Quat.cs]:
```C#
[Obsolete("SetEuler is deprecated. Use the Quat(" + nameof(Vector3) + ") constructor instead.", error: true)]
```

File: modules/mono/glue/Managed/Files/Vector2.cs [hunk 5]
```diff
@@ -222,11 +222,13 @@ public Vector2 Round()
             return new Vector2(Mathf.Round(x), Mathf.Round(y));
         }
 
+        [Obsolete("Deprecated, please use constructor and assignment instead.", true)]
```
Comment (neikeq) [inline modules/mono/glue/Managed/Files/Vector2.cs]:
```C#
[Obsolete("Set is deprecated. Use the Vector2(" + nameof(real_t) + ", " + nameof(real_t) + ") constructor instead.", error: true)]
```

File: modules/mono/glue/Managed/Files/Vector2.cs [hunk 6]
```diff
@@ -222,11 +222,13 @@ public Vector2 Round()
...
         public void Set(real_t x, real_t y)
         {
             this.x = x;
             this.y = y;
         }
+        [Obsolete("Deprecated, please use constructor and assignment instead.", true)]
```
Comment (neikeq) [inline modules/mono/glue/Managed/Files/Vector2.cs]:
```C#
[Obsolete("Set is deprecated. Use the Vector2(" + nameof(Vector2) + ") constructor instead.", error: true)]
```

File: modules/mono/glue/Managed/Files/Vector3.cs [hunk 7]
```diff
@@ -248,12 +248,14 @@ public Vector3 Rotated(Vector3 axis, real_t phi)
             return new Basis(axis, phi).Xform(this);
         }
 
+        [Obsolete("Deprecated, please use constructor and assignment instead.", true)]
```
Comment (neikeq) [inline modules/mono/glue/Managed/Files/Vector3.cs]:
```C#
[Obsolete("Set is deprecated. Use the Vector3(" + nameof(real_t) + ", " + nameof(real_t) + ", " + nameof(real_t) + ") constructor instead.", error: true)]
```

File: modules/mono/glue/Managed/Files/Vector3.cs [hunk 8]
```diff
@@ -248,12 +248,14 @@ public Vector3 Rotated(Vector3 axis, real_t phi)
...
         public void Set(real_t x, real_t y, real_t z)
         {
             this.x = x;
             this.y = y;
             this.z = z;
         }
+        [Obsolete("Deprecated, please use constructor and assignment instead.", true)]
```
Comment (neikeq) [inline modules/mono/glue/Managed/Files/Vector3.cs]:
```C#
[Obsolete("Set is deprecated. Use the Quat(" + nameof(Vector3) + ") constructor instead.", error: true)]
```

**Review by neikeq — CHANGES_REQUESTED** [review]
I've commented how the Obsolete messages should be, to be consistent with the existing ones. I also think it's better to specify the exact constructor to use. The assignment part is not needed as people will understand it. Also, we must use named parameters for booleans.

I can't comment on the C++ API. I don't know if the changes are needed there.

File: core/math/quat.cpp [hunk 9]
```diff
@@ -232,6 +232,8 @@ Quat::operator String() const {
 }
 
 void Quat::set_axis_angle(const Vector3 &axis, const real_t &angle) {
+	ERR_EXPLAIN("set_axis_angle is deprecated. Use the Quat(Vector3 axis, float angle) constructor instead.");
```
Comment (akien-mga) [inline core/math/quat.cpp]: You could remove the duplicated code below by a call to the constructor I guess.

**Comment by akien-mga** [comment]
To be fair I'm not sure if it's really useful to deprecate this API in Quat. I can't comment about C#, but Quat has `set_euler()` and `set_axis_angle()`, which both make their mathematical implications clear. `Quat(Vector3)` and `Quat(Vector3, float)` on the other hand are a lot less obvious, and while the documentation can make the arguments expicit, once it's in your code, `quat = Quat(some_vec, some_float)` will be less explicit than `quat.set_axis_angle(some_vec, some_float)`.

**Comment by aaronfranke** [comment]
@akien-mga Those methods in Basis aren't currently exposed (and also aren't in C#).

There are actual issues with these in C# that causes the code to silently fail, so if core is unchanged it would still be a good idea to remove them from the mono module.

**Review by neikeq — APPROVED** [review]
C# changes are good.

**Comment by aaronfranke** [comment]
I removed the core Quat changes from this PR, so that it's just the C# changes and some nitpicking stuff. I have the core change saved elsewhere in case we want to revisit this later, if it's better to keep those methods in GDScript then that's fine even if it's inconsistent with C#.

**Comment by akien-mga** [comment]
Thanks!

For the core changes, you can mention them in #16863.
