### PR TITLE
Fix crash when converting `Variant` to incompatible `RequiredPtr<T>`

### LINKED ISSUE #115179: 4.6RC2: Creating LightOccluder2D crashes project with no error
### Tested versions

4.6RC2 (and RC1)

### System information

Godot v4.6.rc2 - macOS Tahoe (26.2.0) - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M1 Max (Apple7) - Apple M1 Max (10 threads) - 64.00 GiB memory

### Issue description

When adding an occluder polygon via code launching the game starts and immediately terminates with no errors. The console only reads:

```
Godot Engine v4.6.rc2.official.78c6632eb - https://godotengine.org
Metal 4.0 - Forward+ - Using Device #0: Apple - Apple M1 Max (Apple7)

--- Debugging process stopped ---
```

### Steps to reproduce

See included project. When using script:

```
extends Polygon2D
class_name StaticPolygon

func _ready() -> void:
	var static_body: StaticBody2D = StaticBody2D.new()
	var light_occluder: LightOccluder2D = LightOccluder2D.new()
	var collision_polygon: CollisionPolygon2D = CollisionPolygon2D.new()
	var occluder_polygon: OccluderPolygon2D = OccluderPolygon2D.new()
	
	
	collision_polygon.polygon = polygon
	#occluder_polygon.polygon = polygon
	
	add_child(static_body)
	add_child(light_occluder)
	
	static_body.add_child.call_deferred(collision_polygon)
	static_body.add_child.call_deferred(occluder_polygon)
	
	light_occluder.occluder = occluder_polygon
```

### Minimal reproduction project (MRP)

[4.6-occluder-test.zip](https://github.com/user-attachments/files/24742899/4.6-occluder-test.zip)

### PR DESCRIPTION
**Pull request by dsnopek**
Fixes https://github.com/godotengine/godot/issues/115179

~~I think I've narrowed down what's causing the issue, but I don't think this PR is exactly right.~~

~~It does a weird thing where it puts `#include "core/variant/required_ptr.h"` at the _end_ of `object.h`. We could copy `Object::cast_to<T>()` somewhere else, so don't have to do that. But I also want to spend a bit more time investigating if there's somewhere earlier we could do this check?~~

### CODE REVIEW

File: core/object/object.h [hunk 1]
```diff
@@ -1137,3 +1136,5 @@ class ObjectDB {
 	static void debug_objects(DebugFunc p_func, void *p_user_data);
 	static int get_object_count();
 };
+
+#include "core/variant/required_ptr.h"
```
Comment (Ivorforce) [inline core/object/object.h]: How about we just move RequiredPtr and RequiredResult to object.h?

They obviously depend on each other, so we might as well put them in the same header.
We'll probably need to revisit this, as soon as Object wants to declare required params / results, but we can cross that bridge when we come to it.

**Review by Ivorforce — APPROVED** [review]
Agreed, the fix makes sense.

File: core/object/object.h (hunk 1 above)
Comment (dsnopek) [reply core/object/object.h]: That sounds good to me!

**Review by akien-mga — APPROVED** [review]
