### PR TITLE
Fix for Node3D request gizmos multiple times

### LINKED ISSUE #88119: _CreateGizmo is invoked twice for gizmo plugins with their own gizmo subclasses
### Tested versions

Only tested in 4.2 stable

### System information

Windows 10 - Godot_v4.2.1-stable_mono_win64

### Issue description

Attached is a minimal 3D gizmo plugin that simply draws a line from origin to (1,1,1). Print statements are present in the plugin to demonstrate that `_CreateGizmo` is being invoked twice for some nodes, seemingly at random. This leads to duplicate `EditorNode3DGizmo` instances (also as indicated by print statements), which, while not too big of a deal for lines, is a major problem for handles as only one handle can be grabbed at a time. I have only tested this with C#, as I do not use or know GDScript, but the example present is very nearly a direct translation of the example on the [docs page](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/3d_gizmos.html) for 3D gizmo plugins. When following the first example on that page (not using a `EditorNode3DGizmo` subclass), everything behaves as expected.

Example of log output for demonstration:
duplicate_call_output

### Steps to reproduce

1. Build project
2. Enable plugin "TestPlugin"
3. Create new 3D scene
4. Add an `ExampleNode`
5. See duplicated lines in output panel

### Minimal reproduction project (MRP)

[GizmoPluginTests.zip](https://github.com/godotengine/godot/files/14215404/GizmoPluginTests.zip)

### PR DESCRIPTION
**Pull request by IphStich**
FIXES: #88119

This can result in multiple gizmos being created for the same nodes in some circumstances

Requests for node gizmos are meant to happen only once, as specified in the [documentation](https://docs.godotengine.org/en/4.4/classes/class_editornode3dgizmoplugin.html#class-editornode3dgizmoplugin-private-method-has-gizmo) "Whenever a node is added to a scene this method is called".

In practice, it was possible for this to be called multiple times in some circumstances, resulting in multiple gizmos being created for a given node.

To Reproduce Error:
1. Create new 3D scene from FileSystem dock
2. With the scene open, select the created Node3D
3. Save the scene by pressing Ctrl + S
4. Click Scene > Reload Saved Scene
5. (you will now have multiple gizmos requested for the selected Node3D)

It is possible to reproduce this problem in other ways that are more complex and less likely to occur, and more impactful, while harder to debug. (Took me several hours of debugging to narrow it down to a `emit_changed.call_deferred()` being called by a setter function applying initial `@export` values to an instance in the scene - these were then being executed in order, and resulted in many deffered calls to `_request_gizmo` being stacked due to multiple `update_gizmos` calls)

(as an aside, it is likely that repeated and un-needed calls to `_request_gizmo` are being made for nodes that have no applicable gizmos)

For the plugin, the following code shoud suffice for testing/debugging purposes.

```GDScript
@tool
extends EditorPlugin

var gizmo_plugin = MyGizmo.new()
func _enter_tree() -> void:
	add_node_3d_gizmo_plugin(gizmo_plugin)
func _exit_tree() -> void:
	remove_node_3d_gizmo_plugin(gizmo_plugin)

class MyGizmo extends EditorNode3DGizmoPlugin:
	func _has_gizmo(for_node_3d: Node3D) -> bool:
		print(for_node_3d)
		return false
```

(note: this is my first ever pull request! sorry if this comes off as strange)

### CODE REVIEW

File: scene/3d/node_3d.cpp [hunk 1]
```diff
@@ -230,7 +230,10 @@ void Node3D::_notification(int p_what) {
 
 #ifdef TOOLS_ENABLED
 			if (is_part_of_edited_scene()) {
```
Comment (KoBeWi) [inline scene/3d/node_3d.cpp]: Can be single condition.
```suggestion
			if (is_part_of_edited_scene() && !data.gizmos_requested) {
```

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
