### PR TITLE
Fix get_used_rect() calculation

### LINKED ISSUE #51253: Bucket tool doesn't fill topmost row
### Godot version

85186bc

### System information

W10

### Issue description

When you have an empty area at the top of your tilemap and want to fill it, the topmost row is not filled:
ZIq1N7wPMN

It used to be fine a few versions earlier.

### Steps to reproduce

1. Have a tilemap with empty area at the top
2. Place any amount of tiles at the top row you want to fill
3. Try to fill it

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #51253 (regression from #51004, but it was possibly broken before in different way; not sure why I wouldn't notice though)

The fixed algorithm starts from 0 size and expands to size - 1 and then adds one row and column. I tested with single rows, empty tilemap, different setups etc and seems to work fine.

### CODE REVIEW

File: scene/2d/tile_map.cpp [hunk 1]
```diff
@@ -2668,19 +2668,25 @@ Rect2 TileMap::get_used_rect() { // Not const because of cache
...
 
 				for (Map<Vector2i, TileMapCell>::Element *E = tile_map.front(); E; E = E->next()) {
-					used_size_cache.expand_to(Vector2(E->key().x + 1, E->key().y + 1));
+					used_size_cache.expand_to(Vector2(E->key().x, E->key().y));
 				}
 			}
 		}
+
+		if (!first) { // first is true if every layer is empty.
+			used_size_cache.expand_to(used_size_cache.get_end() + Vector2(1, 1)); // The cache expands to top-left coordinate, so we add one full tile.
```
Comment (groud) [inline scene/2d/tile_map.cpp:2688]: Maybe `used_size_cache.size += Vector2i(1, 1)` would be clearer instead ? (And should be Vector2i btw)

File: scene/2d/tile_map.cpp [hunk 2]
```diff
@@ -2668,19 +2668,25 @@ Rect2 TileMap::get_used_rect() { // Not const because of cache
 	// Return the rect of the currently used area
 	if (used_size_cache_dirty) {
 		bool first = true;
+		used_size_cache = Rect2();
```
Comment (groud) [inline scene/2d/tile_map.cpp:2671]: Should be `Rect2i()`

**Review by groud — CHANGES_REQUESTED** [review]

File: scene/2d/tile_map.cpp (hunk 2 above)
Comment (KoBeWi) [reply scene/2d/tile_map.cpp:2671]: But the variable is of type Rect2 and it's also assigned with Rect2 few lines below.

Comment (groud) [reply scene/2d/tile_map.cpp:2671]: Ah, I think that's a mistake I did then, I see no reason why the variable is Rect2 instead of Rect2i. 
Could you hange it?

Comment (kleonc) [reply scene/2d/tile_map.cpp:2671]: Renaming it to `used_rect_cache` would make sense too, it's not just size. And the same for `used_size_cache_dirty`.

Comment (groud) [reply scene/2d/tile_map.cpp:2671]: > Renaming it to used_rect_cache would make sense too, it's not just size. And the same for used_size_cache_dirty.

Ah yeah, that's true.

**Comment by KoBeWi** [comment]
Done, I also renamed the variables.

**Review by groud — APPROVED** [review]
LGTM! Thanks.

**Comment by akien-mga** [comment]
Thanks!
