### PR TITLE
Hide/show `AcceptDialog`'s button spacer on button visibility changed

### LINKED ISSUE #79096: Version upgrade/downgrade confirmation dialog buttons misaligned
### Godot version

v4.1.stable.official [970459615]  < Steam

### System information

Godot v4.1.stable - Debian GNU/Linux trixie/sid trixie - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1060 (nvidia) - Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 Threads)

### Issue description

After Godot got upgraded 4.0 -> 4.1, when opening a project from the earlier version, I noticed that the buttons in the confirmation dialog look a bit squiffy:

Screenshot_20230706_123457

(Somewhat aside, but that dialog should probably be able to deduce and be more precise about whether it's an upgrade or downgrade!)

### Steps to reproduce

1. Have a project from Godot 4.0
2. Upgrade Godot to 4.1
3. Open project manager

Alternatively:
1. Create a new project in 4.1
2. Quit Godot
3. Edit the `project.godot`'s `config/features` to read `4.0` instead of `4.1`
4. Open project manager

### Minimal reproduction project

[default.zip](https://github.com/godotengine/godot/files/11967512/default.zip)

### PR DESCRIPTION
**Pull request by kleonc**
Fixes #79096.

| Before| After |
|--------|--------|
|0dyPvBDWdQ|GitHubDesktop_ZolZrNAUIs|

### CODE REVIEW

File: scene/gui/dialogs.cpp [hunk 1]
```diff
@@ -286,19 +286,26 @@ void AcceptDialog::_custom_action(const String &p_action) {
...
 
+void AcceptDialog::_custom_button_visibility_changed(Button *button, Control *spacer) {
+	spacer->set_visible(button->is_visible());
+}
+
 Button *AcceptDialog::add_button(const String &p_text, bool p_right, const String &p_action) {
 	Button *button = memnew(Button);
 	button->set_text(p_text);
 
+	Control *spacer;
```
Comment (YuriSizov) [inline scene/gui/dialogs.cpp:297]: Could be good to store a hashmap of buttons and spacers. Will make `remove_button`'s logic safer as well.

Comment (KoBeWi) [reply scene/gui/dialogs.cpp:297]: The spacer can also be stored in button's metadata. It'd be simpler 🙃

Comment (kleonc) [reply scene/gui/dialogs.cpp]: Went for metadata, additional HashMap seems excessive to me. Maybe it would make sense if we'd want to add a method like `get_buttons` or something like that. :thinking: But that's out of scope of this PR.

File: scene/gui/dialogs.cpp [hunk 2]
```diff
@@ -330,21 +341,24 @@ void AcceptDialog::remove_button(Control *p_button) {
...
 	}
 
-	Node *right_spacer = buttons_hbox->get_child(button->get_index() + 1);
-	// Should always be valid but let's avoid crashing.
-	if (right_spacer) {
-		buttons_hbox->remove_child(right_spacer);
-		memdelete(right_spacer);
-	}
-	buttons_hbox->remove_child(button);
-
```
Comment (kleonc) [inline scene/gui/dialogs.cpp:347]: @YuriSizov In #65446 you've changed the ordering of disconnecting/removing parts, any reason for that? :thinking:

I've changed it back so nothing is disconnected in case removing fails.

Comment (YuriSizov) [reply scene/gui/dialogs.cpp:347]: Probably so everything is done in a neat order. Why do we expect the removal to fail? It looks very unusual to check after the removal if node's parent is `nullptr`. I don't think we do anything like that anywhere.

The only reason I can imagine is that the button, or the spacer, were moved elsewhere. But we can check that before trying to remove each node and fail early instead. In fact, for the `button` we already do that check.

Comment (kleonc) [reply scene/gui/dialogs.cpp:347]: It could fail e.g. if trying to `remove_button` from not a main thread, or when the parent is "blocked" which would be the case e.g. if it's called when handling some notification for such button (it's propagated through the parent). In such cases `remove_child` would fail and error out, but if it would be followed by e.g. `memdelete(right_spacer)` it would likely result in a crash (or at least in an invalid internal state).

Yeah, there's the question where to draw the line between safe handling situations where user breaks things which they shouldn't change in the first place. And these I'd ignore. But `remove_child` can fail for kinda valid usages as mentioned above, I think these should be handled gracefully.

Comment (YuriSizov) [reply scene/gui/dialogs.cpp:347]: I think the implications of being called when blocked or not on the main thread affect quite a lot of our codebase. And we mostly ignore those situations (you'll get an error, things will be kinda broken). So I wouldn't go out of our way to handle it here. But it is something we should discuss and devise a common solution for.

> but if it would be followed by e.g. memdelete(right_spacer) it would likely result in a crash (or at least in an invalid internal state).

We can `queue_free()` it, it should avoid the crash.

Comment (YuriSizov) [reply scene/gui/dialogs.cpp:347]: You can keep the code as is, by the way. It's not making it worse. It's just not something that is consistent with the rest of the GUI codebase, and we still need to think about solving this properly in a more generic way. For example, this method is explicitly for removing children, so it can be locked the same way `remove_child` is. Through some helper perhaps. Though that is definitely beyond the scope here.

Comment (kleonc) [reply scene/gui/dialogs.cpp]: Went ahead and already got rid of these. Also moved the disconnecting/removing back, so less changes overall. :upside_down_face: Yeah, it's problematic to keep everything being handled the same way across the codebase.

File: scene/gui/dialogs.cpp [hunk 3]
```diff
@@ -286,18 +286,29 @@ void AcceptDialog::_custom_action(const String &p_action) {
...
+		right_spacer = buttons_hbox->add_spacer();
 	} else {
 		buttons_hbox->add_child(button);
 		buttons_hbox->move_child(button, 0);
-		buttons_hbox->add_spacer(true);
+		right_spacer = buttons_hbox->add_spacer(true);
 	}
+	button->set_meta("__right_spacer", right_spacer);
+
+	button->connect("visibility_changed", callable_mp(this, &AcceptDialog::_custom_button_visibility_changed).bind(button));
```
Comment (YuriSizov) [inline scene/gui/dialogs.cpp:311]: Since we're disconnecting other signals when the button is removed, we should probably disconnect this one as well.

File: scene/gui/dialogs.cpp [hunk 4]
```diff
@@ -337,11 +348,11 @@ void AcceptDialog::remove_button(Control *p_button) {
 		button->disconnect("pressed", callable_mp(this, &AcceptDialog::_cancel_pressed));
 	}
 
-	Node *right_spacer = buttons_hbox->get_child(button->get_index() + 1);
-	// Should always be valid but let's avoid crashing.
+	Control *right_spacer = Object::cast_to<Control>(button->get_meta("__right_spacer"));
```
Comment (YuriSizov) [inline scene/gui/dialogs.cpp:351]: I think you can still move it above the disconnects and add something like this, similar to the check for the button:

```
ERR_FAIL_COND_MSG(right_spacer->get_parent() != buttons_hbox, vformat("Cannot remove button %s as its associated spacer does not belong to this dialog.", button->get_name()));
```

File: scene/gui/dialogs.cpp (hunk 3 above)
Comment (kleonc) [reply scene/gui/dialogs.cpp:311]: It should be auto disconnected when the spacer is freed though.

`remove_button` doesn't free the button itself and hence the other signals need to be manually disconnected.

**Review by YuriSizov — APPROVED** [review]
Conceptually it's great, just some things to iron out.

File: scene/gui/dialogs.cpp (hunk 3 above)
Comment (YuriSizov) [reply scene/gui/dialogs.cpp:311]: This line has no spacer in it :) It's a signal from a button and we connect it to the dialog.

Comment (kleonc) [reply scene/gui/dialogs.cpp:311]: :man_facepalming:

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.1.
