### PR TITLE
Make draw/compute lists threadsafe

### LINKED ISSUE #48265: Deadlock in multithreaded importer for .obj files, or "Creating buffers with data is forbidden during creation of a draw list" error
**Godot version:**
4.0.dev 1c2766e

**OS/device including version:**
Windows 10.0.19041.928

**Issue description:**
I had a deadlock occur while reimporting my project containing a few .obj files, as well as a plethora of random content.

The last output is:
```
 Couldn't open MTL file 'aria.mtl', it may not exist or not be readable.
   at:    at: (editor\import\resource_importer_obj.cpp:48)
(editor\import\resource_importer_obj.cpp:48)
WARNING:WARNING: OBJ: Ambient light for material 'palette' is ignored in PBR
 OBJ: Ambient light for material 'palette' is ignored in PBR
     at:      at: _parse_material_library (editor\import\resource_importer_obj.cpp:65)
_parse_material_library (editor\import\resource_importer_obj.cpp:65)
```

Stacktraces from the two relevant threads are as follows:
```
 	ntdll.dll!NtWaitForAlertByThreadId()	Unknown
 	ntdll.dll!RtlSleepConditionVariableSRW()	Unknown
 	KernelBase.dll!SleepConditionVariableSRW()	Unknown
 	godot.windows.opt.tools.64.exe!__crtSleepConditionVariableSRW(_RTL_CONDITION_VARIABLE * pCond, _RTL_SRWLOCK * pLock, unsigned long dwMs, unsigned long flags) Line 482	C++
>	[Inline Frame] godot.windows.opt.tools.64.exe!Concurrency::details::stl_condition_variable_win7::wait_for(Concurrency::details::stl_critical_section_interface *) Line 177	C++
 	godot.windows.opt.tools.64.exe!Concurrency::details::stl_condition_variable_win7::wait(Concurrency::details::stl_critical_section_interface * lock) Line 171	C++
 	godot.windows.opt.tools.64.exe!do_wait(_Cnd_internal_imp_t * cond, _Mtx_internal_imp_t * mtx, const xtime * target) Line 62	C++
 	[Inline Frame] godot.windows.opt.tools.64.exe!std::condition_variable::wait(std::unique_lock<std::mutex> &) Line 601	C++
 	[Inline Frame] godot.windows.opt.tools.64.exe!Semaphore::wait() Line 58	C++
 	[Inline Frame] godot.windows.opt.tools.64.exe!ThreadWorkPool::end_work() Line 121	C++
 	godot.windows.opt.tools.64.exe!EditorFileSystem::reimport_files(const Vector<String> & p_files) Line 2011	C++
 	godot.windows.opt.tools.64.exe!EditorFileSystem::_update_scan_actions() Line 582	C++
 	godot.windows.opt.tools.64.exe!EditorFileSystem::_notification(int p_what) Line 1141	C++
 	godot.windows.opt.tools.64.exe!EditorFileSystem::_notificationv(int p_notification, bool p_reversed) Line 110	C++
 	godot.windows.opt.tools.64.exe!Object::notification(int p_notification, bool p_reversed) Line 795	C++
 	godot.windows.opt.tools.64.exe!SceneTree::_notify_group_pause(const StringName & p_group, int p_notification) Line 796	C++
 	godot.windows.opt.tools.64.exe!SceneTree::process(float p_time) Line 443	C++
 	godot.windows.opt.tools.64.exe!Main::iteration() Line 2505	C++
 	godot.windows.opt.tools.64.exe!OS_Windows::run() Line 622	C++
 	godot.windows.opt.tools.64.exe!widechar_main(int argc, wchar_t * * argv) Line 163	C++
 	godot.windows.opt.tools.64.exe!_main() Line 187	C++
 	godot.windows.opt.tools.64.exe!main(int argc, char * * argv) Line 199	C++
```

and both of the stalled importer threads had the same stacktrace as follows:
```
 	ntdll.dll!NtWaitForAlertByThreadId()	Unknown
 	ntdll.dll!RtlSleepConditionVariableSRW()	Unknown
 	KernelBase.dll!SleepConditionVariableSRW()	Unknown
 	godot.windows.opt.tools.64.exe!__crtSleepConditionVariableSRW(_RTL_CONDITION_VARIABLE * pCond, _RTL_SRWLOCK * pLock, unsigned long dwMs, unsigned long flags) Line 482	C++
>	[Inline Frame] godot.windows.opt.tools.64.exe!Concurrency::details::stl_condition_variable_win7::wait_for(Concurrency::details::stl_critical_section_interface *) Line 177	C++
 	godot.windows.opt.tools.64.exe!Concurrency::details::stl_condition_variable_win7::wait(Concurrency::details::stl_critical_section_interface * lock) Line 171	C++
 	godot.windows.opt.tools.64.exe!do_wait(_Cnd_internal_imp_t * cond, _Mtx_internal_imp_t * mtx, const xtime * target) Line 62	C++
 	[Inline Frame] godot.windows.opt.tools.64.exe!std::condition_variable::wait(std::unique_lock<std::mutex> &) Line 601	C++
 	[Inline Frame] godot.windows.opt.tools.64.exe!Semaphore::wait() Line 58	C++
 	godot.windows.opt.tools.64.exe!CommandQueueMT::push_and_ret<RendererStorage,RenderingServer::SurfaceData (__cdecl RendererStorage::*)(RID,int)const ,RID,int,RenderingServer::SurfaceData>(RendererStorage * p_instance, RenderingServer::SurfaceData(const RendererStorage::*)(RID, int) p_method, RID p1, int p2, RenderingServer::SurfaceData * r_ret) Line 489	C++
 	godot.windows.opt.tools.64.exe!RenderingServerDefault::mesh_get_surface(RID p1, int p2) Line 298	C++
 	godot.windows.opt.tools.64.exe!ArrayMesh::_get_surfaces() Line 892	C++
 	[Inline Frame] godot.windows.opt.tools.64.exe!call_with_variant_args_ret_helper(Performance *) Line 623	C++
 	[Inline Frame] godot.windows.opt.tools.64.exe!call_with_variant_args_ret_dv(Performance *) Line 428	C++
 	godot.windows.opt.tools.64.exe!MethodBindTR<Performance,Array>::call(Object * p_object, const Variant * * p_args, int p_arg_count, Callable::CallError & r_error) Line 450	C++
 	godot.windows.opt.tools.64.exe!ClassDB::get_property(Object * p_object, const StringName & p_property, Variant & r_value) Line 1167	C++
 	godot.windows.opt.tools.64.exe!Object::get(const StringName & p_name, bool * r_valid) Line 456	C++
 	godot.windows.opt.tools.64.exe!ResourceFormatSaverBinaryInstance::_find_resources(const Variant & p_variant, bool p_main) Line 1682	C++
 	godot.windows.opt.tools.64.exe!ResourceFormatSaverBinaryInstance::save(const String & p_path, const Ref<Resource> & p_resource, unsigned int p_flags) Line 1791	C++
 	godot.windows.opt.tools.64.exe!ResourceFormatSaverBinary::save(const String & p_path, const Ref<Resource> & p_resource, unsigned int p_flags) Line 1972	C++
 	godot.windows.opt.tools.64.exe!ResourceSaver::save(const String & p_path, const Ref<Resource> & p_resource, unsigned int p_flags) Line 116	C++
 	godot.windows.opt.tools.64.exe!ResourceImporterOBJ::import(const String & p_source_file, const String & p_save_path, const Map<StringName,Variant,Comparator<StringName>,DefaultAllocator> & p_options, List<String,DefaultAllocator> * r_platform_variants, List<String,DefaultAllocator> * r_gen_files, Variant * r_metadata) Line 529	C++
 	godot.windows.opt.tools.64.exe!EditorFileSystem::_reimport_file(const String & p_file, const Map<StringName,Variant,Comparator<StringName>,DefaultAllocator> * p_custom_options, const String & p_custom_importer) Line 1779	C++
 	godot.windows.opt.tools.64.exe!EditorFileSystem::_reimport_thread(unsigned int p_index, EditorFileSystem::ImportThreadData * p_import_data) Line 1927	C++
 	godot.windows.opt.tools.64.exe!ThreadWorkPool::Work<RaycastOcclusionCull::Scenario,void (__cdecl RaycastOcclusionCull::Scenario::*)(unsigned int,RaycastOcclusionCull::Scenario::TransformThreadData *),RaycastOcclusionCull::Scenario::TransformThreadData *>::work() Line 61	C++
 	godot.windows.opt.tools.64.exe!ThreadWorkPool::_thread_function(void * p_user) Line 43	C++
 	godot.windows.opt.tools.64.exe!Thread::callback(Thread * p_self, const Thread::Settings & p_settings, void(*)(void *) p_callback, void * p_userdata) Line 73	C++
 	[Inline Frame] godot.windows.opt.tools.64.exe!std::invoke(void(*)(Thread *, const Thread::Settings &, void(*)(void *), void *) &&) Line 1607	C++
 	godot.windows.opt.tools.64.exe!std::thread::_Invoke<std::tuple<void (__cdecl*)(Thread *,Thread::Settings const &,void (__cdecl*)(void *),void *),Thread *,Thread::Settings,void (__cdecl*)(void *),void *>,0,1,2,3,4>(void * _RawVals) Line 44	C++
 	godot.windows.opt.tools.64.exe!thread_start<unsigned int (__cdecl*)(void *),1>(void * const parameter) Line 97	C++
 	kernel32.dll!BaseThreadInitThunk()	Unknown
```

In case it's relevant, I have stacktraces from all threads saved in the following gist:
https://gist.github.com/lyuma/11dc95ac44db79c9af54aacd61ee7f37
Notably, I was unable to find a RenderingServer thread.

**Steps to reproduce:**
1. Ensure your project contains .obj files.
2. Close the project
3. Delete the .godot directory
4. Re-open the project
5. While files are importing, Godot may deadlock.

**Minimal reproduction project:**
I have a 100MB zip file but it contains copyrighted files. I was able to reproduce the issue twice with this project.

I tried simplifying things, for example only including the .obj files. But I was not able to reproduce the issue on the simpler project. It does seem like a race condition.

### PR DESCRIPTION
**Pull request by briansemrau**
Discussed with reduz on rocketchat.
Creating resources asynchronously can sometimes catch the renderer while it is building a draw list, causing creation to fail.

Should fix #48265, but while I've reproduced those errors in the past, I'm struggling to reproduce them now so I can't test this.

(bonus: removes an accidental line that may cause issues with other renderers in the future)

### CODE REVIEW

**Review by Chaosus — APPROVED** [review]
> I'm struggling to reproduce them now so I can't test this.

That fixes a lot of loading errors on models at startup, at least for me.

**Comment by brianwinterpixel** [comment]
may also fix #54151

File: drivers/vulkan/rendering_device_vulkan.cpp [hunk 1]
```diff
@@ -7684,6 +7687,9 @@ void RenderingDeviceVulkan::_draw_list_free(Rect2i *r_last_viewport) {
 		memdelete(draw_list);
 		draw_list = nullptr;
 	}
+
+	// draw_list is no longer active
+	_THREAD_SAFE_UNLOCK_
```
Comment (reduz) [inline drivers/vulkan/rendering_device_vulkan.cpp:7692]: unlock is not needed

**Review by reduz — CHANGES_REQUESTED** [review]

File: drivers/vulkan/rendering_device_vulkan.cpp (hunk 1 above)
Comment (brianwinterpixel) [reply drivers/vulkan/rendering_device_vulkan.cpp:7692]: `_THREAD_SAFE_LOCK_` isn't a MutexLock, it's a `.lock()` call, so we need to be sure to `unlock()` it when the draw list is complete.

Comment (BastiaanOlij) [reply drivers/vulkan/rendering_device_vulkan.cpp:7692]: I think there is a mix up here, 99% of the code base uses `_THREAD_SAFE_METHOD_` which makes sense to use here as well. `_THREAD_SAFE_METHOD_` automatically unlocks after the method is called (it uses a temporary variable that when it goes out of scope unlocks). It's a safer approach then using `_THREAD_SAFE_LOCK_` as you guarantee the lock being freed, while `_THREAD_SAFE_LOCK_` introduces the risk of exiting the method early and not unlocking.

Comment (BastiaanOlij) [reply drivers/vulkan/rendering_device_vulkan.cpp:7692]: Ah hang on, sorry guys, I misread this. It's two methods, `_draw_list_allocate`, in which we lock, and `_draw_list_free` in which we unlock. Then it does make sense to use `_THREAD_SAFE_LOCK_` and `_THREAD_SAFE_UNLOCK_` though. 

That said, it feels dangerous to me. There is a lot of potential here for a mismatch between lock and unlock. That one I'll leave to @reduz to comment on.

File: drivers/vulkan/rendering_device_vulkan.cpp [hunk 2]
```diff
@@ -8270,6 +8279,9 @@ void RenderingDeviceVulkan::compute_list_end(uint32_t p_post_barrier) {
 
 	memdelete(compute_list);
 	compute_list = nullptr;
+
+	// compute_list is no longer active
+	_THREAD_SAFE_UNLOCK_
 }
```
Comment (BastiaanOlij) [inline drivers/vulkan/rendering_device_vulkan.cpp:8285]: On the 'dangerous' remark, in theory (possibly not in practice) this unlock could end up unlocking the lock we obtained on allocating our drawlist. There is nothing protecting this.

File: drivers/vulkan/rendering_device_vulkan.cpp (hunk 1 above)
Comment (brianwinterpixel) [reply drivers/vulkan/rendering_device_vulkan.cpp:7692]: The problem is that thread safety must be maintained for the entire duration that the draw list is being built, not just in the context of these individual functions.

I understand the risk of manual locking/unlocking. We could maybe modify the draw_list to hold a MutexLock for the duration of its life, but that would have equivalent risk.

Comment (brianwinterpixel) [reply drivers/vulkan/rendering_device_vulkan.cpp:7692]: If at any point a draw list is created and not ended, you likely have other serious problems in the renderer anyways.

Comment (BastiaanOlij) [reply drivers/vulkan/rendering_device_vulkan.cpp:7692]: Yup, agree @brianwinterpixel , I think @reduz just mixed up the two approaches.

I haven't examined the code base close enough for 2D rendering, mostly been working on 3D and we call other calls to create draw lists, but they internally may end up calling the method you changed. I guess its that sort of scenarios I would caution about when lock and unlock are loosely joined.

I don't really have a more valid alternative though, I think @reduz is best to comment here

**Comment by Chaosus** [comment]
I would merge this before alpha - it fixes crashes that randomly happen on the startup of one of my home projects:

```
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.0.dev.custom_build (baac3f5ed320bbfc5f7ba3fdba1299cb888df4e4)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] vkGetInstanceProcAddr
[1] vkGetInstanceProcAddr
[2] vkGetInstanceProcAddr
[3] vkGetInstanceProcAddr
[4] RenderingDeviceVulkan::draw_list_end (C:\Git\godot\drivers\vulkan\rendering_device_vulkan.cpp:7642)
[5] RendererSceneRenderImplementation::RenderForwardClustered::_render_scene (C:\Git\godot\servers\rendering\renderer_rd\forward_clustered\render_forward_clustered.cpp:1598)
[6] RendererSceneRenderRD::render_scene (C:\Git\godot\servers\rendering\renderer_rd\renderer_scene_render_rd.cpp:5084)
[7] RendererSceneCull::_render_scene (C:\Git\godot\servers\rendering\renderer_scene_cull.cpp:3223)
[8] RendererSceneCull::render_camera (C:\Git\godot\servers\rendering\renderer_scene_cull.cpp:2515)
[9] RendererViewport::_draw_3d (C:\Git\godot\servers\rendering\renderer_viewport.cpp:173)
[10] RendererViewport::_draw_viewport (C:\Git\godot\servers\rendering\renderer_viewport.cpp:233)
[11] RendererViewport::draw_viewports (C:\Git\godot\servers\rendering\renderer_viewport.cpp:671)
[12] RenderingServerDefault::_draw (C:\Git\godot\servers\rendering\rendering_server_default.cpp:92)
[13] RenderingServerDefault::draw (C:\Git\godot\servers\rendering\rendering_server_default.cpp:377)
[14] Main::iteration (C:\Git\godot\main\main.cpp:2707)
[15] OS_Windows::run (C:\Git\godot\platform\windows\os_windows.cpp:621)
[16] widechar_main (C:\Git\godot\platform\windows\godot_windows.cpp:163)
[17] _main (C:\Git\godot\platform\windows\godot_windows.cpp:187)
[18] main (C:\Git\godot\platform\windows\godot_windows.cpp:199)
[19] __scrt_common_main_seh (d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[20] BaseThreadInitThunk
-- END OF BACKTRACE --
```

**Review by akien-mga — APPROVED** [review]
I think this is good to merge as is given the severity of the bugs it fixes. If there are still doubts in the implementation, we could open an issue to remember that this needs double checking.

**Comment by akien-mga** [comment]
Thanks!
