### PR TITLE
Editor: Display deprecated/experimental messages in tooltips

### LINKED ISSUE #90137: Cannot interact with popups inside the editor
### Tested versions

v4.3.dev.custom_build [29b3d9e9e]

### System information

Godot v4.3.dev (29b3d9e9e) - Fedora Linux 39 (Workstation Edition) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX Vega (RADV VEGA10) () - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

We cannot select text neither interact with it (e.g. click on a link) on an editor popup.

[Capture vidéo du 2024-04-02 10-54-09.webm](https://github.com/godotengine/godot/assets/270928/0164f4b5-a60c-4aa2-bef3-580cc69302ee)

[Capture vidéo du 2024-04-02 10-55-44.webm](https://github.com/godotengine/godot/assets/270928/5dbff900-08f2-4496-9a25-e3cebfc89dc8)

### Steps to reproduce

1. Highlight an inspector entry or a export entry.
2. Try to select text from the popup.

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by dalexeev**
* Resolves #90137 (for `EditorHelpBit`).

### CODE REVIEW

**Comment by dalexeev** [comment]
Some refactoring was necessary to avoid code duplication for different types of class members, so the `HelpData` structure was added. Also, I needed to unify the custom descriptions, since `EditorHelpBit` is used in several places in the editor.

Additionally, I implemented hover and scroll functionality since sometimes the descriptions are too tall to fit on the screen.

https://github.com/godotengine/godot/assets/47700418/d82b04ec-4088-463d-ba2e-f74a251571e8

**Comment by KoBeWi** [comment]
The experimental/deprecated message looks like part of the description. It needs to be more separated IMO.

**Comment by dalexeev** [comment]
This matches the current appearance in the main help. Deprecated/experimental messages are simply inserted as paragraphs before the description. The only indicator is an icon and red/yellow bold text. In the future we may add some decorative elements if we deem it necessary. But in my opinion, it’s already quite noticeable.

**Comment by KoBeWi** [comment]
Something is wrong here.
image
The tooltip appears out of screen.

File: editor/connections_dialog.cpp [hunk 1]
```diff
@@ -872,7 +872,17 @@ ConnectDialog::~ConnectDialog() {
...
 Control *ConnectionsDockTree::make_custom_tooltip(const String &p_text) const {
 	// If it's not a doc tooltip, fallback to the default one.
-	return p_text.contains("::") ? nullptr : memnew(EditorHelpTooltip(p_text));
+	if (p_text.contains("::")) {
+		return nullptr;
+	}
+
+	EditorHelpBit *help_bit = memnew(EditorHelpBit(p_text));
+	EditorHoverableTooltip *tooltip = memnew(EditorHoverableTooltip(const_cast<ConnectionsDockTree *>(this)));
+	help_bit->connect("request_hide", Callable(tooltip, "hide")); // Will be deleted on its timer.
```
Comment (KoBeWi) [inline editor/connections_dialog.cpp:881]: This can be `callable_mp()`.

File: editor/connections_dialog.cpp [hunk 2]
```diff
@@ -872,7 +872,17 @@ ConnectDialog::~ConnectDialog() {
 
 Control *ConnectionsDockTree::make_custom_tooltip(const String &p_text) const {
 	// If it's not a doc tooltip, fallback to the default one.
-	return p_text.contains("::") ? nullptr : memnew(EditorHelpTooltip(p_text));
+	if (p_text.contains("::")) {
+		return nullptr;
+	}
+
+	EditorHelpBit *help_bit = memnew(EditorHelpBit(p_text));
+	EditorHoverableTooltip *tooltip = memnew(EditorHoverableTooltip(const_cast<ConnectionsDockTree *>(this)));
```
Comment (KoBeWi) [inline editor/connections_dialog.cpp:880]: You can avoid `const_casts` if you store the Control in a variable and then connect the signals in `_notification()`.

File: editor/editor_inspector.cpp [hunk 3]
```diff
@@ -1178,7 +1183,18 @@ void EditorInspectorCategory::_notification(int p_what) {
...
+		return nullptr;
+	}
+
+	EditorHelpBit *help_bit = memnew(EditorHelpBit(p_text));
+	EditorHoverableTooltip *tooltip = memnew(EditorHoverableTooltip(const_cast<EditorInspectorCategory *>(this)));
+	help_bit->connect("request_hide", Callable(tooltip, "hide")); // Will be deleted on its timer.
+	tooltip->add_child(help_bit);
+	EditorNode::get_singleton()->add_child(tooltip);
+	tooltip->popup_under_cursor();
+	return memnew(Control); // Make the standard tooltip invisible.
```
Comment (KoBeWi) [inline editor/editor_inspector.cpp:1197]: Same here.

File: editor/editor_help.h [hunk 4]
```diff
@@ -251,53 +254,91 @@ class EditorHelp : public VBoxContainer {
...
+	void set_content_height_limits(float p_min, float p_max);
 
-	EditorHelpBit();
+	EditorHelpBit(const String &p_symbol = String());
 };
 
-class EditorHelpTooltip : public EditorHelpBit {
-	GDCLASS(EditorHelpTooltip, EditorHelpBit);
+// Standard tooltips do not allow you to hover over them.
+// This class is intended as a temporary workaround.
```
Comment (KoBeWi) [inline editor/editor_help.h:329]: I'd say it's a proper solution, not a workaround. If you want to do more than a standard tooltip, make a more specialized one.
Though it sucks that it basically bypasses the tooltip system (returning empty Controls as custom tooltips is an *interesting* solution).

**Comment by KoBeWi** [comment]
Seems like this PR also fixes #90395

File: editor/editor_help.h [hunk 5]
```diff
@@ -38,6 +38,7 @@
 #include "scene/gui/margin_container.h"
```
Comment (KoBeWi) [inline editor/editor_help.h:38]: This can be removed now.

File: editor/editor_help.h [hunk 6]
```diff
@@ -251,53 +254,91 @@ class EditorHelp : public VBoxContainer {
...
+	String symbol_visible_type;
+	String symbol_name;
 
-	RichTextLabel *rich_text = nullptr;
+	HelpData help_data;
+
+	bool dirty = false;
+
+	float content_min_height;
+	float content_max_height;
```
Comment (KoBeWi) [inline editor/editor_help.h:300]:
```suggestion
	float content_min_height = 0.0;
	float content_max_height = 0.0;
```

File: editor/editor_help.cpp [hunk 7]
```diff
@@ -3320,142 +3370,464 @@ String EditorHelpBit::get_theme_item_description(const StringName &p_class_name,
...
+	queue_redraw();
+}
+
+EditorHelpBit::EditorHelpBit(const String &p_symbol) {
+	add_theme_constant_override("separation", 0);
+
+	title = memnew(RichTextLabel);
+	title->set_fit_content(true);
+	title->set_selection_enabled(true);
+	//title->set_context_menu_enabled(true);
```
Comment (KoBeWi) [inline editor/editor_help.cpp:3741]: Commented-out code should be removed.

File: editor/editor_help.cpp [hunk 8]
```diff
@@ -3320,142 +3370,464 @@ String EditorHelpBit::get_theme_item_description(const StringName &p_class_name,
...
+
+	timer = memnew(Timer);
+	timer->set_wait_time(0.2);
+	timer->connect("timeout", Callable(this, "queue_free"));
+	add_child(timer);
 
-	get_rich_text()->set_custom_minimum_size(Size2(360 * EDSCALE, 0));
+	ERR_FAIL_NULL(p_target);
+	p_target->connect("mouse_entered", callable_mp(timer, &Timer::stop));
+	p_target->connect("mouse_exited", callable_mp(timer, &Timer::start).bind(-1));
```
Comment (KoBeWi) [inline editor/editor_help.cpp:3830]: Doesn't it duplicate the notifications?

File: editor/editor_help.cpp [hunk 9]
```diff
@@ -3320,142 +3370,464 @@ String EditorHelpBit::get_theme_item_description(const StringName &p_class_name,
...
+	} else if (p_select.begins_with("#")) { // Class.
+		_go_to_help("class_name:" + p_select.substr(1));
+	} else if (p_select.begins_with("@")) { // Member.
+		const int tag_end = p_select.find_char(' ');
+		const String tag = p_select.substr(1, tag_end - 1);
+		const String link = p_select.substr(tag_end + 1).lstrip(" ");
+
+		String topic;
+		if (tag == "method") {
+			topic = "class_method";
```
Comment (KoBeWi) [inline editor/editor_help.cpp:3591]: This could be something like `const String topic = "class_" + tag;`.

File: editor/editor_help.h (hunk 5 above)
Comment (dalexeev) [reply editor/editor_help.h]: Done. I had to fix a few files that relied on transitive includes.

File: editor/connections_dialog.cpp (hunk 2 above)
Comment (dalexeev) [reply editor/connections_dialog.cpp]: I don't think this is possible. In any case you will need to remove the qualifier, since you cannot assign `const T *` to `T *`.

File: editor/editor_help.h (hunk 4 above)
Comment (dalexeev) [reply editor/editor_help.h:325]: I think a better solution would be to allow hovering over tooltips (we can make this configurable). In this case, when you hover over a tooltip control, another tooltip may appear. That is, we need a tooltip stack.

File: editor/editor_help.cpp (hunk 7 above)
Comment (dalexeev) [reply editor/editor_help.cpp]: Added TODO comment.

File: editor/editor_help.cpp (hunk 8 above)
Comment (dalexeev) [reply editor/editor_help.cpp:3834]: No, the tooltip should remain as long as the cursor points either to it or to the control that created it (target).

File: editor/connections_dialog.cpp (hunk 2 above)
Comment (KoBeWi) [reply editor/connections_dialog.cpp]: Then maybe move the const cast to `EditorHoverableTooltip()` and make the argument const? It would at least make creating tooltips cleaner.

**Comment by dalexeev** [comment]
> Seems like this PR also fixes #90395

No, this PR doesn't fix the bug. See #90446 instead.

> The tooltip appears out of screen.

I'm not sure how to fix this.

> Main window loses focus when tooltip appears.
> EDIT: This one might be unsolvable though 🤔The tooltip does not block events or anything, so it's not that bad.

This is probably platform specific. On Linux (KDE), the parent window only loses focus if I click on the tooltip.

> I'm not sure about the horizontal separator. It's somewhat ugly IMO, especially in small tooltips.

> Also I already said the horizontal separator is meh, but after checking other instances of help bits, it looks even worse outside the tooltips. Like here, the content is very wide, which makes the separator super long and you are wasting a line of space.

I fixed this by changing the title background and making the minimum content height about 2 lines:



> The help panel in property selector jumps a lot

Made the height of embedded `EditorHelpBit`s fixed.

**Comment by KoBeWi** [comment]
> No, this PR doesn't fix the bug.

I mean I tested and it does fix it.

**Comment by dalexeev** [comment]
> I mean I tested and it does fix it.

You probably missed this step:

> 4. Unselect and select again the node

**Comment by KoBeWi** [comment]
I looked into the popup out of screen issue and this happens when you use `call_deferred()`:
image
It's arguably better, because you can read it at least 🙃
idk how to make it right, I might try some other solutions.

File: editor/editor_help.cpp (hunk 7 above)
Comment (KoBeWi) [reply editor/editor_help.cpp]: Why would you want the context menu though?

Comment (dalexeev) [reply editor/editor_help.cpp]: * See #74114.

Some people like me are used to copy text with context menu in certain scenarios. I have no idea why I'm not using <kbd>Ctrl + C</kbd> here.

**Comment by dalexeev** [comment]
> The tooltip appears out of screen.

> Main window loses focus when tooltip appears.

It looks like I managed to solve both problems.

**Review by KoBeWi — APPROVED** [review]

File: editor/connections_dialog.cpp (hunk 2 above)
Comment (dalexeev) [reply editor/connections_dialog.cpp]: I'd rather keep the `const_cast` in calls rather than move it into the definition. Because `EditorHelpBitTooltip` requires a non-const pointer for `connect()`. In my opinion, it is better not to hide the problem.

File: editor/editor_help.cpp [hunk 10]
```diff
@@ -3321,142 +3370,467 @@ String EditorHelpBit::get_theme_item_description(const StringName &p_class_name,
...
+		name = class_name;
+		help_data = _get_class_help_data(class_name);
+	} else if (item_type == "property") {
+		if (name.begins_with("metadata/")) {
+			visible_type = TTR("Metadata:");
+			name = name.trim_prefix("metadata/");
+		} else if (class_name == "ProjectSettings") {
+			visible_type = TTR("Project Setting:");
+		} else if (class_name == "EditorSettings") {
+			visible_type = TTR("Editor Setting:");
```
Comment (dalexeev) [inline editor/editor_help.cpp:3650]:
```suggestion
		} else if (class_name == "ProjectSettings" || class_name == "EditorSettings") {
			visible_type = TTR("Setting:");
```

**Comment by KoBeWi** [comment]
I actually found another bug .-.
When doc tooltip appears, you can't use keyboard. It's annoying when you e.g. try to set position, but unfortunate mouse placement opens a tooltip and you can't write in spin slider.

**Comment by dalexeev** [comment]
> When doc tooltip appears, you can't use keyboard.

I tried different flag combinations, but I could not get the keyboard input to be passed to the parent window, and the mouse input to be processed in the popup. If I fix the keyboard issue, then hyperlinks in the popup become unclickable and vice versa.

**Comment by KoBeWi** [comment]
Unless you manage to fix it, it's better to have links unclickable than to introduce regression. Scrolling alone is a great improvement already, the link issue could be fixed later.

**Comment by dalexeev** [comment]
> it's better to have links unclickable than to introduce regression

I'm not sure if this is a regression. It's somewhat expected that while an interactive popup is on the screen, it will prevent input. Previously, the tooltip was non-interactive, you simply couldn't hover over it.

> Scrolling alone is a great improvement already, the link issue could be fixed later.

The problem is that the hyperlinks _look_ interactive, an underline appears on hover, but nothing happens on click. To me this looks like a bigger bug than the problem above.

> Unless you manage to fix it

We could try forwarding keyboard input (except `ui_cancel`) to the parent viewport.

**Comment by KoBeWi** [comment]
> I'm not sure if this is a regression. It's somewhat expected that while an interactive popup is on the screen, it will prevent input.

But it's not expected that when you have an input field active and focused, you are not able to input text. I discovered this issue by accident, because I was doing something using a build with this PR included; it's confusing and makes editing values troublesome, because you have to be aware of your cursor and avoid hovering the inspector.

> We could try forwarding keyboard input (except ui_cancel) to the parent viewport.

That could work. I think `_window_input` method can be used.

**Comment by dalexeev** [comment]
> > Scrolling alone is a great improvement already, the link issue could be fixed later.
> 
> The problem is that the hyperlinks _look_ interactive, an underline appears on hover, but nothing happens on click.

@KoBeWi If you agree with this, let's do it this way. This PR is already too big and to be honest I don't want to mess around with input forwarding, at least right now.

**Comment by KoBeWi** [comment]
> If you agree with this, let's do it this way.

What way? Like it is now? Or with disabled clicks?

**Comment by dalexeev** [comment]
Options:

1. (Current) Keyboard input in the parent window does not work as long as the popup is displayed.
2. Hyperlinks in the popup are not clickable (but look interactive visually) and the popup cannot be hidden by pressing <kbd>Escape</kbd>. Scrolling in the popup works.

**Comment by KoBeWi** [comment]
I'd go with 1. The links were already unclickable before. Now it would be a bit more confusing (since you can hover them), but it's a bug with the new feature, while the other option is a regression. It's better to add new things and iron them out than to break old things.

**Comment by dalexeev** [comment]
> When doc tooltip appears, you can't use keyboard. It's annoying when you e.g. try to set position, but unfortunate mouse placement opens a tooltip and you can't write in spin slider.

Fixed by forwarding input to the parent viewport.

File: editor/editor_help.cpp (hunk 10 above)
Comment (dalexeev) [reply editor/editor_help.cpp]: Applied to save space and due to the lack of objections.

**Comment by dalexeev** [comment]
Added `request_hide` signal handling to `EditorBuildProfileManager` and `EditorFeatureProfileManager` to be consistent with `CreateDialog` and `PropertySelector`.

**Comment by akien-mga** [comment]
Thanks!
