### PR TITLE
Fix CPU particles bug with local_coords and transform

### LINKED ISSUE #27743: CPUParticle World Coordinate Rotation Improperly Applied
**Godot version:** 3.1 official

**OS:** Ubuntu 18.04.1

**Issue description:**
When moving and rotating an instance of CPUParticles in 3d space with Local Coords = false the translations of the particles don't update properly when the particle system is rotated. For a single frame all of the particles rotate with the parent node then return to their original world coordinate, but slightly offset.

**Steps to reproduce:**
Create a CPUParticle node and set Local Coordinates to false in the Display options. Animate the system moving and rotating in world space.

CPUParticleBug

**Minimal reproduction project:**
[CPUParticle_Bug.zip](https://github.com/godotengine/godot/files/3050968/CPUParticle_Bug.zip)

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/27743

Code graciously donated by Gamblify.

The bug was arising out a situation where the ``global_transform`` of the CPUParticles node was out of sync with the internal ``particle_process``. This became especially apparent when ``fixed_fps`` was set to a low number. 

To understand the issue, you have to consider how CPUParticles previously applied ``local_coords``. Each time the particles updated the individual particle's ``instance_transform`` would be "un-transformed" by taking the ``affine_inverse()`` of the ``global_transform``. The bug arose whenever ``global_transform`` changed before the particles were re-processed. The result is that the particles would slide and then skip at each update. And where the change in position was large (as in #27743), there was a visible stutter. 

The way to fix this is to avoid offsetting the individual ``instance_transform`` of each particle on particle_process by using the same implementation that particles use. To do this, when ``local_coords`` is set, simply ignore the ``WORLD_TRANSFORM`` in the vertex shader and treat the ``instance_transform`` as if it were in world space already. This achieves the same effect as the previous method, only we are avoiding doing a computation instead of nullifying it with another computation. The main benefit is that there is no longer a disconnect between when the ``global_transform`` is updated and when the particle nullifies the effect of the transform. This way, we also avoid performing a transformation on CPU on every particle, every update.

CC: @Keetz, @jesperkondrup, @uldall

### CODE REVIEW

**Comment by Keetz** [comment]
Works perfectly.

Would it be hard to get these improvements on CPUParticles2D as well? I guess it is the exact same issue as you described with the CPUParticles here.

I Updated the test project with a simple 2D scene:
[CPUParticle_Bug.tar.gz](https://github.com/godotengine/godot/files/3280096/CPUParticle_Bug.tar.gz)

File: scene/3d/cpu_particles.cpp [hunk 1]
```diff
@@ -932,7 +928,7 @@ void CPUParticles::_update_particle_data_buffer() {
 					Vector3 dir = c->get_global_transform().basis.get_axis(2); //far away to close
 
 					if (local_coords) {
-						dir = un_transform.basis.xform(dir).normalized();
+						dir = Basis().xform(dir).normalized();
```
Comment (JFonS) [inline scene/3d/cpu_particles.cpp]:
```suggestion
						dir = dir.normalized();
```
Wouldn't that get us the same result? Also, I find it weird that the direction gets normalized only in local coords but not in global coords. We may be able to skip this normalization, or maybe we have to normalize in both cases, but the distinction seems supicious.

**Review by JFonS — COMMENTED** [review]
The code looks good, but @reduz will probably have the final word on adding local coordinates directly into MultiMesh :)

File: scene/3d/cpu_particles.cpp (hunk 1 above)
Comment (clayjohn) [reply scene/3d/cpu_particles.cpp]: I feel the same way. I reduced it to this so that I could get rid of ``un_transform``, but I wanted to leave it as intact as possible. 

I'll compare it to the code for particles and see if that exposes any reason for normalizing ``dir`` only when using ``local_coords``.

Comment (clayjohn) [reply scene/3d/cpu_particles.cpp]: I got it ``sorted`` out. :p 

Here is the implementation for Particles
https://github.com/godotengine/godot/blob/f410e7a8a9b14fd9f5c210afcc9e3519e9ce246d/drivers/gles3/rasterizer_scene_gles3.cpp#L1462-L1466

And here is how I updated it
```
if (local_coords) {

	// will look different from Particles in editor as this is based on the camera in the scenetree
	// and not the editor camera
	dir = get_global_transform().affine_inverse().xform(dir).normalized();
} else {
	dir = dir.normalized();
}
```
I also tested out and confirmed that the previous implementation did not match the behaviour of Particles. It is fixed now. Thanks for drawing attention to this.

**Comment by clayjohn** [comment]
@Keetz The API for MultiMesh is the same for 3D and 2D the same fix shouldn't be too hard. 

Thanks for the MRP, the reason I didn't do the 2D fix in the first place was that I was unable to replicate the issue in 2D.

File: scene/3d/cpu_particles.cpp (hunk 1 above)
Comment (JFonS) [reply scene/3d/cpu_particles.cpp]: Great work!

**Comment by clayjohn** [comment]
After reviewing it, reduz was not okay with the API changes. Accordingly, I have updated the PR to be contained completely within the CPUParticles* classes. 

Now, instead of nullifying the global_transform at the rendering side. We track ``global_transform`` and whenever it changes (even if its between particle updates) we update the particle transforms. This avoids the bug without having to update anything on the rendering API side. 

This solution is not as fast in theory as the prior solution, but in practice the speed difference should be negligible.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-pick for 3.1.2.
