### PR TITLE
Fix EditorTranslationParser leak

### LINKED ISSUE #40693: Leaked PackedSceneEditorTranslationParserPlugin in editor
**Godot version:**

4.0.dev.custom_build. 93b50a62e

**Issue description:**

When I open and close editor then with -v flag I see this leak
```
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object.cpp:2041)
Orphan StringName: PackedSceneEditorTranslationParserPlugin
StringName: 1 unclaimed string names at exit.
```

**Steps to reproduce:**
1. Run Godot - `godot4 -e -v -q`

### PR DESCRIPTION
**Pull request by SkyLucilfer**
Fix #40693

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -6799,6 +6799,7 @@ EditorNode::EditorNode() {
 
 EditorNode::~EditorNode() {
 	EditorInspector::cleanup_plugins();
+	EditorTranslationParser::get_singleton()->clean_parsers();
```
Comment (akien-mga) [inline editor/editor_node.cpp:6802]: Can't this be done in `EditorTranslationParser`'s destructor directly?

Comment (SkyLucilfer) [reply editor/editor_node.cpp:6802]: When I'm debugging, I couldn't detect the destructor of `EditorTranslationParser` being called - `print_line()` doesn't print. I assume the destructor is not called or only called when it's too late (after the leak is detected), because of how I create the singleton.

So I tried making `EditorTranslationParser` inherit from `Node`, then do `singleton = memnew(EditorTranslationParser)` and `add_child()` in EditorNode constructor. See [example ](https://github.com/godotengine/godot/blob/master/editor/editor_node.cpp#L5705). The idea is to let `EditorNode` clear its children together with `EditorTranslationParser`, so that the destructor will be called. Unfortunately `GDScriptTranslationParser` wants to register first before we enter `EditorNode` constructor, so the singleton will be empty and it will crash. 

I consider some other ways too. But it wasn't elegant :/

**Comment by akien-mga** [comment]
Thanks!

File: modules/gdscript/register_types.cpp [hunk 2]
```diff
@@ -143,9 +142,4 @@ void unregister_gdscript_types() {
 
 	ResourceSaver::remove_resource_format_saver(resource_saver_gd);
 	resource_saver_gd.unref();
-
-#ifdef TOOLS_ENABLED
-	EditorTranslationParser::get_singleton()->remove_parser(gdscript_translation_parser_plugin, EditorTranslationParser::STANDARD);
-	gdscript_translation_parser_plugin.unref();
```
Comment (qarmin) [inline modules/gdscript/register_types.cpp:149]: Removing this lines caused (again) leak of GDScriptEditorTranslationParserPlugin
