### PR TITLE
Provide default values for fold state in "Edit Animation Libraries" window to prevent errors

### LINKED ISSUE #116293: "Couldn't find the given section "[hash or UID]" and key "folding", and no default was given" when opening "Edit Animation Libraries" window
### Tested versions

Reproducible in:
- v4.7.dev.custom_build [bf95b6258]

### System information

Godot v4.7.dev (bf95b6258) - macOS Tahoe (26.3.0) - Multi-window, 2 monitors - OpenGL 3 (Compatibility) - Apple M4 Pro - Apple M4 Pro (14 threads) - 24.00 GiB memory

### Issue description

When the "Edit Animation Libraries" window is opened, such as by selecting Animation > Manage Animations... from the Animation tab, an error like the following appears:
```
ERROR: Couldn't find the given section "9e3c9149c2f6404f234f0707f7f31e8d" and key "folding", and no default was given.
   at: get_value (./core/io/config_file.cpp:60)
``` 
- I don't see any adverse effects in the editor itself; libraries are still able to be folded, and retain their fold state when the window is closed and reopened.
- After adding a second library (in addition to the global one) to the AnimationPlayer, then closing and reopening the project, the error is no longer appearing.
- Deleting the project's `.godot` folder, then opening the project and the "Edit Animation Libraries" window again caused the error to appear.
  - I toggled the fold state of the global library, closed the window, and reopened it again; this time, the error did *not* appear.

### Steps to reproduce

Create a new project. Add an AnimationPlayer node to the scene. In the "Animation" tab, navigate to "Animation > Manage Animations...". The error should appear.

### Minimal reproduction project (MRP)

N/A; best seen with a completely fresh project

### PR DESCRIPTION
**Pull request by Meorge**
Closes https://github.com/godotengine/godot/issues/116293.

The "Edit Animation Libraries" window would try to get folding data even if the file with that data had not been created yet. Because no default value was provided, the error described in #116293 would be thrown.

This PR provides empty PackedStringArrays as default values for these `get_value()` calls, so that if there is no folding data, the editor considers no sections to be folded.

### CODE REVIEW

File: editor/animation/animation_library_editor.cpp [hunk 1]
```diff
@@ -807,7 +807,7 @@ void AnimationLibraryEditor::_save_mixer_lib_folding(TreeItem *p_item) {
 
 	Vector<String> collapsed_libs;
 	if (config->has_section(md)) {
```
Comment (KoBeWi) [inline editor/animation/animation_library_editor.cpp]: You can do

```suggestion
	if (config->has_section_key(md, "folding")) {
```

**Review by KoBeWi — APPROVED** [review]
