### PR TITLE
Prevent 'Change Type' on nodes from a foreign scene

### LINKED ISSUE #45912: Change Type in editable children cannot be saved
**Godot version:**
4.0.dev e5bb89cdd5e92fa6fdeff78aad08bf0cbfbcc692

**OS/device including version:**
Windows 10.0.19041.804
Nvidia RTX 2080 Ti driver 452.06

**Issue description:**
When I add a glTF model or other imported asset, I may have an asset which is missing some rich feature from the program that exported it: for example, a missing light from a program which did not support or use the glTF lights extension; or a Reflection Probe; or a physics object of sorts.

Here is an example of such an asset, imported from a glTF file. The scene was originally intended for another game engine...
Scene, showing hierarchy with many meshes and plain Node3D

As a user, it seems to me reasonable to embed this inside another scene and attempt to assign the correct types to those nodes which were not imported as desired. For example, this seems like a reasonable action for a creator to make:
Scene, showing editable children subscene with some types changed
(Note, that collision shapes did not match one-to-one with the original hierarchy, but all of the other type changes felt very natural to me: StreamAudioPlayer, OmniLight, ReflectionProbe, etc.

Upon saving and later re-opening the scene, the type changes were not preserved.

You can see this in the .tscn format: when saving changes to editable children, it does not embed type="" attributes in the [node] headings, and when a type="" attribute is added manually, it no longer merges with the original editable children and instead creates a separate copy of the node in question.

The best way to solve this issue is to prevent users from using the Change Type feature in editable children:
> reduz 2021-02-11 6:06 PM PST
> The bug I guess is that this is allowed
> It should not be

**Steps to reproduce:**
1. Open the attached project, which should open MainScene.tscn
2. Right click `Sun` and change type to, for example, `DirectionalLight3D`
3. Notice that the scene is now lit up.
4. Save the scene and reopen it.
5. The `Sun` node has reverted to a plain Node3D type.

Can probably be reproduced from any project. The attached project uses a .glb to mimic the workflow where this issue is most likely to occur.

**Minimal reproduction project:**
[EditableChildrenChangeType.zip](https://github.com/godotengine/godot/files/5969324/EditableChildrenChangeType.zip)

### PR DESCRIPTION
**Pull request by hilfazer**
Fixes #45912.

Checking for foreign nodes is not enough since the root of an instanced scene does not count as a foreign node. Therefore i've added `SceneTreeDock::_validate_no_instance()`. The error messege for popup window is taken from existing code in SceneTreeDock.

### CODE REVIEW

**Comment by KoBeWi** [comment]
The option should also be removed from the context menu when it's unavailable (`break` inside `menu_option` is mostly for shortcuts).

**Comment by hilfazer** [comment]
There's a number of options in the context menu that can't be used on foreign nodes, e.g. Rename, Move Up. Should they also be removed (not neccesarily in this PR)?

**Comment by KoBeWi** [comment]
> Should they also be removed (not neccesarily in this PR)?

Yep, the menu got few cleanups in the past, but still not everything is handled as it should.

File: editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -2581,7 +2603,17 @@ void SceneTreeDock::_tree_rmb(const Vector2 &p_menu_pos) {
...
+		bool can_replace = true;
+		for (List<Node *>::Element *E = selection.front(); E; E = E->next()) {
+			if (E->get() != edited_scene && (E->get()->get_owner() != edited_scene || E->get()->get_filename() != "")) {
+				can_replace = false;
+				break;
+			}
+		}
+
+		if (can_replace)
+			menu->add_icon_shortcut(get_theme_icon("Reload", "EditorIcons"), ED_GET_SHORTCUT("scene_tree/change_node_type"), TOOL_REPLACE);
```
Comment (KoBeWi) [inline editor/scene_tree_dock.cpp:2616]: Wrap the code under condition in brackets even if it's one line (as per Godot's code style guide).

**Review by KoBeWi — CHANGES_REQUESTED** [review]

**Review by KoBeWi — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
