### PR TITLE
Fix export variable of type Node pointing to a wrong child node when duplicating

### LINKED ISSUE #82670: Duplicating a node with an export variable doesn't update variable's nodepath
### Godot version

v4.2.dev.custom_build [0ca854232]

### System information

Pop Os 22.04 lts 12th Gen Intel® Core™ i7-12700H × 20 NVIDIA RTX A2000 8GB 32.0  ram

### Issue description

A node that has a script attached to it and it has a couple of child nodes (type of a child node doesn't matter). In the script you have an export variable of type Node. You save the scene into a file and you add it in level scene. When you start to duplicate that scene in the level and you'll hover over exported variable to show a node path, it will show an incorrect path. 

https://github.com/godotengine/godot/assets/33091666/75088d1b-c014-41e0-bae3-46610eccbad1

### Steps to reproduce

1. create a scene with a node and a child node.
2. attach a script to the parent node and create an export variable of type Node
3. assign child node to that exported variable through the editor
4. save the scene and create a level scene where you are going to add just saved scene.
5. _Possibly requires a reboot of the engine before seeing the bug_
6. start duplicating nodes in the level scene

### Minimal reproduction project

[NodeTest.zip](https://github.com/godotengine/godot/files/12781547/NodeTest.zip)

### PR DESCRIPTION
**Pull request by warriormaster12**
Took a while to figure that this was a two part issue. 

1. properties were considered as overridden since `get_property_value`  method would return a variant that was read from a packed scene file (NodePath). However, when calling `instantiate` the variants would be converted to a proper type (Object) if they were in the [deferred_properties list](https://github.com/godotengine/godot/blob/master/scene/resource/packed_scene.cpp#L487).
2. When duplicating a node, variants of type Object would not update their path in that  process, which is fine for nodes that aren't children of the duplicated node.

before pr: 

https://github.com/godotengine/godot/assets/33091666/2d5312ab-112a-4b20-a73b-a6b6948cf4c6

pr:

https://github.com/godotengine/godot/assets/33091666/7e880a6b-8e21-4aab-a128-cbe25dcf4588

Fixes: https://github.com/godotengine/godot/issues/82670
Supersedes: https://github.com/godotengine/godot/pull/83006

### CODE REVIEW

File: scene/main/node.cpp [hunk 1]
```diff
@@ -2548,6 +2548,29 @@ Node *Node::_duplicate(int p_flags, HashMap<const Node *, Node *> *r_duplimap) c
 				}
 
 			} else {
+				// If property points to a node which is an ancestor of a node we are duplicating, update its path.
+				if (value.get_type() == Variant::OBJECT) {
+					Node *property_node = Object::cast_to<Node>(value);
+					if (property_node) {
+						if (this->is_ancestor_of(property_node)) {
```
Comment (AThousandShips) [inline scene/main/node.cpp:2555]:
```suggestion
						if (is_ancestor_of(property_node)) {
```

File: scene/main/node.cpp [hunk 2]
```diff
@@ -2548,6 +2548,29 @@ Node *Node::_duplicate(int p_flags, HashMap<const Node *, Node *> *r_duplimap) c
...
+						}
+					}
+				}
+				else if (value.get_type() == Variant::ARRAY) {
+					Array arr = value;
+					if (arr.get_typed_builtin() == Variant::OBJECT) {
+						for (int i = 0; i < arr.size(); i++) {
+							Node *property_node = Object::cast_to<Node>(arr[i]);
+							if (property_node) {
+								if (this->is_ancestor_of(property_node)) {
```
Comment (AThousandShips) [inline scene/main/node.cpp:2566]:
```suggestion
								if (is_ancestor_of(property_node)) {
```

File: scene/main/node.cpp [hunk 3]
```diff
@@ -2548,6 +2548,29 @@ Node *Node::_duplicate(int p_flags, HashMap<const Node *, Node *> *r_duplimap) c
...
+									arr[i] = current_node->get_node_or_null(this->get_path_to(property_node));
```
Comment (AThousandShips) [inline scene/main/node.cpp:2567]:
```suggestion
									arr[i] = current_node->get_node_or_null(get_path_to(property_node));
```

File: scene/main/node.cpp [hunk 4]
```diff
@@ -2548,6 +2548,29 @@ Node *Node::_duplicate(int p_flags, HashMap<const Node *, Node *> *r_duplimap) c
 				}
 
 			} else {
+				// If property points to a node which is an ancestor of a node we are duplicating, update its path.
+				if (value.get_type() == Variant::OBJECT) {
+					Node *property_node = Object::cast_to<Node>(value);
+					if (property_node) {
+						if (this->is_ancestor_of(property_node)) {
+							value = current_node->get_node_or_null(this->get_path_to(property_node));
```
Comment (AThousandShips) [inline scene/main/node.cpp:2556]:
```suggestion
							value = current_node->get_node_or_null(get_path_to(property_node));
```

**Review by Stronkkey — APPROVED** [review]

**Comment by warriormaster12** [comment]
Updated a comment in the node.cpp as it was a bit unclear

**Comment by warriormaster12** [comment]
Is it also possible to cherrypick for 4.1.x? If there's going to be another maintenance release.

**Comment by Mickeon** [comment]
Am I reading this correctly? Does this also supersede https://github.com/godotengine/godot/pull/81866 by solving a similar or pretty much identical issue?

**Comment by warriormaster12** [comment]
@Mickeon seems like it solves an similar problem though I'm not sure how yours handles arrays if it even does.

**Comment by warriormaster12** [comment]
So what is the next step? Would be nice to merge this so that I can continue working on my game project without worrying about duplicating nodes 😊

**Comment by AThousandShips** [comment]
No team member has approved this yet, it's still waiting for a review

File: scene/property_utils.cpp [hunk 5]
```diff
@@ -74,10 +74,31 @@ Variant PropertyUtils::get_property_default_value(const Object *p_object, const
...
+						Array paths = value_in_ancestor;
+
+						bool valid;
+						Array array = node->get(p_property, &valid);
+						ERR_CONTINUE(!valid);
+						array = array.duplicate();
+
+						array.resize(paths.size());
+						for (int j = 0; j < array.size(); j++) {
+							array.set(i, node->get_node_or_null(paths[i]));
```
Comment (AThousandShips) [inline scene/property_utils.cpp:95]:
```suggestion
							array.set(j, node->get_node_or_null(paths[j]));
```
Assuming you meant this

Comment (warriormaster12) [reply scene/property_utils.cpp]: Yes I did, I guess muscle memory said to type i instead of j XD

**Comment by AThousandShips** [comment]
Is it that way before? If not this PR should make sure it doesn't introduce that behaviour

**Comment by warriormaster12** [comment]
Aight, I'll take a closer look at home. Hopefully it will be simple enough to patch this.

**Comment by AThousandShips** [comment]
I'd suggest to first update your branch to get a good view of how the code looks right now, as you're about 9 days behind

**Comment by warriormaster12** [comment]
Do you mean that I should update the branch with the master?

**Comment by AThousandShips** [comment]
Yes, rebase it

**Comment by warriormaster12** [comment]
Aight, I'll do that :+1:

**Comment by AThousandShips** [comment]
If you need help I can help you in a bit

**Comment by warriormaster12** [comment]
Hi, thanks for the help with squashing. Very rarely I've done this.

**Comment by warriormaster12** [comment]
But yeah, I'll take a look now if the override issue with array is still present

**Comment by warriormaster12** [comment]
Could it be this https://github.com/godotengine/godot/pull/83902

**Comment by warriormaster12** [comment]
Like so?

Also I've tested against latest commit. 

image

image

image

Now seems to work as it should

**Comment by warriormaster12** [comment]
So I guess false alarm earlier today

File: scene/property_utils.cpp [hunk 6]
```diff
@@ -74,10 +74,31 @@ Variant PropertyUtils::get_property_default_value(const Object *p_object, const
 			const SceneState::PackState &ia = states_stack[i];
 			bool found = false;
 			Variant value_in_ancestor = ia.state->get_property_value(ia.node, p_property, found);
+			Vector<String> deferred_properties = ia.state->get_node_deferred_nodepath_properties(ia.node);
```
Comment (RandomShaper) [inline scene/property_utils.cpp:77]:
```suggestion
			const Vector<String> &deferred_properties = ia.state->get_node_deferred_nodepath_properties(ia.node);
```

File: scene/property_utils.cpp [hunk 7]
```diff
@@ -74,10 +74,31 @@ Variant PropertyUtils::get_property_default_value(const Object *p_object, const
...
 				if (r_is_valid) {
 					*r_is_valid = true;
 				}
+				// Replace properties stored as NodePaths with actual Nodes.
+				// Otherwise, the property value would be considered as overridden.
+				if (deferred_properties.find(p_property) != -1) {
+					if (value_in_ancestor.get_type() == Variant::ARRAY) {
+						Array paths = value_in_ancestor;
+
+						bool valid;
```
Comment (RandomShaper) [inline scene/property_utils.cpp:88]:
```suggestion
						bool valid = false;
```

File: scene/main/node.cpp [hunk 8]
```diff
@@ -2548,6 +2548,24 @@ Node *Node::_duplicate(int p_flags, HashMap<const Node *, Node *> *r_duplimap) c
...
+					if (arr.get_typed_builtin() == Variant::OBJECT) {
+						for (int i = 0; i < arr.size(); i++) {
+							Node *property_node = Object::cast_to<Node>(arr[i]);
+							if (property_node && is_ancestor_of(property_node)) {
+								arr[i] = current_node->get_node_or_null(get_path_to(property_node));
+							}
+						}
+						value = arr;
+					}
+				}
```
Comment (RandomShaper) [inline scene/main/node.cpp:2568]: Wouldn't this also need to recurse into deeper array levels, dictionaries, etc.? I think we have some code around to traverse a `Variant`. If not already there, I'd suggest adding something like `PropertyUtils::visit_objects(p_variant, p_visitor_callback)`.

Comment (warriormaster12) [reply scene/main/node.cpp:2568]: As an example do you mean an array of node3Ds which is inside an array type of situation? As far as I understood, you don't have to do anything with dictionaries since they don't provide a user a way to give an Object type. So we don't have to do anything special with them until typed version of dictionary is introduced.

Comment (warriormaster12) [reply scene/main/node.cpp:2568]: @RandomShaper

Comment (RandomShaper) [reply scene/main/node.cpp:2568]: Oh, that's very true.

**Review by RandomShaper — APPROVED** [review]
I wouldn't mind more eyes here, but I can give my take with some confidence:

This supersedes #81866. In that one we concluded that updating the node references should be the default behavior, which is intrinsic to the present PR. Also, this one handles every possibility of typed variables, so this one is more comprehensive.

**Comment by KoBeWi** [comment]
Tested the PR with a very simple case and the property is cleared:

https://github.com/godotengine/godot/assets/2223172/0d82b262-5914-4e24-bcf3-fec6bc1c5a1c

**Comment by warriormaster12** [comment]
Interesting, I guess the behavior differs between prefabs and just child nodes.

**Comment by warriormaster12** [comment]
@KoBeWi updated the pr and duplication should work now properly with local nodes as well. Could you confirm on your end that there aren't any other issues? 

I had to move properties duplication as a last operation since for local nodes, children were initialized after properties therefore the bug that you demonstrated.

**Comment by warriormaster12** [comment]
https://github.com/godotengine/godot/assets/33091666/284eba73-b4e3-4895-85a2-127a83608bb1

File: scene/property_utils.cpp [hunk 9]
```diff
@@ -74,10 +74,31 @@ Variant PropertyUtils::get_property_default_value(const Object *p_object, const
...
 			bool found = false;
 			Variant value_in_ancestor = ia.state->get_property_value(ia.node, p_property, found);
+			const Vector<String> &deferred_properties = ia.state->get_node_deferred_nodepath_properties(ia.node);
 			if (found) {
 				if (r_is_valid) {
 					*r_is_valid = true;
 				}
+				// Replace properties stored as NodePaths with actual Nodes.
+				// Otherwise, the property value would be considered as overridden.
+				if (deferred_properties.find(p_property) != -1) {
```
Comment (KoBeWi) [inline scene/property_utils.cpp:84]:
```suggestion
				if (deferred_properties.has(p_property)) {
```

File: scene/main/node.cpp [hunk 10]
```diff
@@ -2618,6 +2580,62 @@ Node *Node::_duplicate(int p_flags, HashMap<const Node *, Node *> *r_duplimap) c
...
+			} else {
+				// If property points to a node which is owned by a node we are duplicating, update its path.
+				if (value.get_type() == Variant::OBJECT) {
+					Node *property_node = Object::cast_to<Node>(value);
+					if (property_node && is_ancestor_of(property_node)) {
+						value = current_node->get_node_or_null(get_path_to(property_node));
+					}
+				} else if (value.get_type() == Variant::ARRAY) {
+					Array arr = value;
+					if (arr.get_typed_builtin() == Variant::OBJECT) {
```
Comment (KoBeWi) [inline scene/main/node.cpp:2624]: This won't handle non-typed Arrays, which can hold Objects too, but I guess it's not that important (and the current code is more performant).

**Review by KoBeWi — APPROVED** [review]

File: scene/main/node.cpp (hunk 10 above)
Comment (warriormaster12) [reply scene/main/node.cpp:2624]: Do you want me to take a look at that before merging this pr?

Comment (warriormaster12) [reply scene/main/node.cpp:2624]: Unless you are talking about a case when you duplicate a node in gdscript and you use non-typed array to store nodes :thinking:

Comment (KoBeWi) [reply scene/main/node.cpp:2624]: If it can't be assigned then ok.

Comment (warriormaster12) [reply scene/main/node.cpp:2624]: I tested quickly assigning from code with non typed array and non typed variable, duplication seems to work correctly:

image


```
extends Node3D

@export var health: float = 100
@export var cube: Node3D = null
@export var cubes: Array[Node3D] = []
var non_typed_array: Array = []
var non_typed_node = null

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	health = PlayerStats.player_health
	non_typed_node = get_node("MeshInstance3D")
	non_typed_array.push_back(get_node("MeshInstance3D"))
	if name == "Cube":
		var dup_node: Node3D = duplicate()
		get_tree().get_current_scene().add_child.call_deferred(dup_node)
		dup_node.global_position.x += 3
	print(non_typed_array[0])

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _physics_process(delta: float) -> void:
	if Input.is_action_just_pressed("hurt_self"):
		health -= 10
		PlayerStats.player_health = health
		print(health)
	if Input.is_action_just_pressed('switch_level'):
		get_tree().change_scene_to_file("res://scene_2.tscn")
	if non_typed_array.size() > 0:
		non_typed_array[0].rotation.y += 90 * delta
```

**Comment by MetRiko** [comment]
Does someone know what is the status for this PR? 
It looks like it was approved 2 weeks ago but I didn't find it in the changelog of the latest Godot 4.2 RC1 release. Does it mean it will be in the RC2 or it is not ready yet?

**Comment by KoBeWi** [comment]
It has 4.3 milestone with 4.2 cherry-pick label, so it will be available in 4.2.1.
It was approved around release freeze, all PRs that weren't merged before then and weren't fixing issues important for the release were pushed to the next version.

**Comment by YuriSizov** [comment]
Would be nice to evaluate if this would lead to performance regressions like other similar recent changes did. Looks like we're iterating over a bunch of nodes and all of their properties to solve the issue here.

**Comment by KoBeWi** [comment]
It's not recursive, so it's probably fine.

**Comment by YuriSizov** [comment]
> It's not recursive

It kind of is, I think? We just collect all the nodes ahead of time. Though that's not new to this PR. So I guess it won't be any worse.

**Comment by warriormaster12** [comment]
The pr itself imo doesn't have recursion directly since it just takes the nodepath and converts into an object. If you have child with a property that needs to be converted then you get recursion. Maybe there might be a performance penalty for nodepath conersion 🤔

**Comment by YuriSizov** [comment]
Thanks!

**Comment by MikeFP** [comment]
> It has 4.3 milestone with 4.2 cherry-pick label, so it will be available in 4.2.1. It was approved around release freeze, all PRs that weren't merged before then and weren't fixing issues important for the release were pushed to the next version.

I couldn't find this commit in either 4.2.1 nor 4.3-dev. Was it included?

**Comment by Mickeon** [comment]
Once the cherry-pick is done, the label is removed, so this has been forgotten.

**Comment by warriormaster12** [comment]
It was included in 4.3 dev1

You just have to go through interactive commit history.

**Comment by MikeFP** [comment]
The issue solved by this PR still happens in 4.3-dev1, so that's why I guessed the commit wasn't included. I don't know, though.

The test I did:
```
Root > Node1 > NodeWithProp (exported Node prop set to parent `Node1`)
```

I selected `Node1`, hit duplicate, and the result was:
```
Root > Node2 > NodeWithProp (exported Node prop set to `Node1` instead of `Node2`)
```

**Comment by warriormaster12** [comment]
Interesting, maybe I misunderstood  how interactive commit page works. I’ll have to check once I get a chance.

**Comment by warriormaster12** [comment]
@MikeFP could you send a minimum project?

**Comment by kleonc** [comment]
> The test I did:
> 
> ```
> Root > Node1 > NodeWithProp (exported Node prop set to parent `Node1`)
> ```
> 
> I selected `Node1`, hit duplicate, and the result was:
> 
> ```
> Root > Node2 > NodeWithProp (exported Node prop set to `Node1` instead of `Node2`)
> ```

@MikeFP Can confirm, indeed this case seems to be broken. :thinking:

> The issue solved by this PR still happens in 4.3-dev1

#82670 was specifically reporting a case when it's the Node with the exported Node property being duplicated though. And such case seems to be fixed by this PR.
What you've mentioned (exported Node property in a child of a Node being duplicated) is a different case, you could open a new issue for it.

**Comment by MikeFP** [comment]
@kleonc I see. In fact, there's already an issue here: #78060, with an open PR #81866. I thought it would get superseded by this, like a previous comment in this discussion suggested:

> I wouldn't mind more eyes here, but I can give my take with some confidence:
> 
> This supersedes #81866. In that one we concluded that updating the node references should be the default behavior, which is intrinsic to the present PR. Also, this one handles every possibility of typed variables, so this one is more comprehensive.

But maybe this PR didn't actually end up covering that case. Now it's a matter of working on that other PR, then.

**Comment by warriormaster12** [comment]
I’ll take a look after new year celebration. I already have one suspect.
