### PR TITLE
Assign return value on `Variant` operator failure

### LINKED ISSUE #95152: String format and `in` operator can return unexpected values on failure
### Tested versions

- Reproducible in 4.2 stable, 4.3 [3978628c6] (latest master branch at the time)

### System information

Godot v4.3.rc (3978628c6) - Arch Linux

### Issue description

The string formatting (`%`) and `in` operator can both fail while still returning a value, in which case the operators can return a value encountered previously in the program.

I think this is because both of these use `ERR_FAIL_COND_MSG` in their evaluators, which on failure will return without writing to `r_ret`. If you're writing to a previously used temporary, this will then keep its previous value.

I'm not sure what the sensible way to fix this is. I would probably expect them both to throw an exception in these cases, but it might also make sense for them to just return a some kind of default value (the raw format string? false?).

### Steps to reproduce

```gdscript
func _ready() -> void:
	print("a %d" % [])
```

pushes an error and prints the empty string (missing format args).

```gdscript
func _ready() -> void:
	OS.get_name()
	print("a %d" % [])
```

pushes an error and prints the value that `OS.get_name` returns.

```gdscript
func _ready() -> void:
	print("a" in get_node("this node doesn't exist"))
```

pushes an error and prints `false` (null value on the right side of the `in` operator)

```gdscript
func _ready() -> void:
	print(is_instance_valid(self))
	print("a" in get_node("this node doesn't exist"))
```

pushes an error and prints `true` `true`

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by aaronp64**
`Variant` operators for `String` formatting and `in` could result in errors, which would return from `validated_evaluate` without assigning `r_ret`.  This would cause scripts using the return value from these operators to get results from previously run code.  Updated to return the original `String` value in the `String` formatting case, and false for `in` when an error occurs.

Fixes #95152

### CODE REVIEW

File: core/variant/variant_op.h [hunk 1]
```diff
@@ -1492,7 +1504,10 @@ class OperatorEvaluatorObjectHasPropertyString {
 	}
 	static inline void validated_evaluate(const Variant *left, const Variant *right, Variant *r_ret) {
 		Object *l = right->get_validated_object();
-		ERR_FAIL_NULL(l);
+		if (unlikely(!l)) {
+			*VariantGetInternalPtr<bool>::get_ptr(r_ret) = false;
+			ERR_FAIL_MSG("Invalid base object for 'in'");
```
Comment (akien-mga) [inline core/variant/variant_op.h:1509]: `ERR_FAIL` messages should by a full sentence ending with `.`:
```suggestion
			ERR_FAIL_MSG("Invalid base object for 'in'.");
```
(same below)

File: core/variant/variant_op.h [hunk 2]
```diff
@@ -923,7 +923,10 @@ class OperatorEvaluatorStringFormat<S, void> {
 	static inline void validated_evaluate(const Variant *left, const Variant *right, Variant *r_ret) {
 		bool valid = true;
 		String result = do_mod(*VariantGetInternalPtr<S>::get_ptr(left), &valid);
-		ERR_FAIL_COND_MSG(!valid, result);
+		if (unlikely(!valid)) {
+			*VariantGetInternalPtr<String>::get_ptr(r_ret) = *VariantGetInternalPtr<S>::get_ptr(left);
+			ERR_FAIL_MSG(result);
```
Comment (akien-mga) [inline core/variant/variant_op.h:928]: This is a pre-existing issue, but the error message formatting won't match the rule I stated in my other review comment.

I think we might want to make it similar to what `vformat` does with the lowercase sub-sentence that `sprintf` returns:
```
        ERR_FAIL_COND_V_MSG(error, String(), String("Formatting error in string \"") + p_text + "\": " + fmt + ".");
```

E.g.:
```suggestion
			ERR_FAIL_MSG(vformat("String formatting error: %s.", result));
```

Comment (akien-mga) [reply core/variant/variant_op.h:928]: Same thing for the other `ERR_FAIL_MSG(result);`.

**Review by akien-mga — APPROVED** [review]
I'm not familiar with the internals there so I'm not sure what this assignment of `left` to `r_ret` means, but if it fixes the issue, overall the change seems sane to me.

**Comment by akien-mga** [comment]
Thanks!
