### PR TITLE
Check if the line pointer goes away from the image buffer's EOF in the BMP importer

### LINKED ISSUE #46542: Crash when importing broken bmp file
**Godot version:**
3.2.4.rc.custom_build. 8385a0d8a

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
When trying to open broken bmp file, then Godot crashes with this backtrace:
```
[1] godots() [0x1736270] (/mnt/Miecz/godot3.2/platform/x11/crash_handler_x11.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7fd8a708d210] (??:0)
[3] ImageLoaderBMP::convert_to_image(Ref<Image>, unsigned char const*, unsigned char const*, unsigned int, ImageLoaderBMP::bmp_header_s const&) (/mnt/Miecz/godot3.2/modules/bmp/image_loader_bmp.cpp:133)
[4] ImageLoaderBMP::load_image(Ref<Image>, FileAccess*, bool, float) (/mnt/Miecz/godot3.2/modules/bmp/image_loader_bmp.cpp:290)
[5] ImageLoader::load_image(String, Ref<Image>, FileAccess*, bool, float) (/mnt/Miecz/godot3.2/core/io/image_loader.cpp:67 (discriminator 2))
[6] ResourceImporterTexture::import(String const&, String const&, Map<StringName, Variant, Comparator<StringName>, DefaultAllocator> const&, List<String, DefaultAllocator>*, List<String, DefaultAllocator>*, Variant*) (/mnt/Miecz/godot3.2/editor/import/resource_importer_texture.cpp:400 (discriminator 3))
[7] EditorFileSystem::_reimport_file(String const&) (/mnt/Miecz/godot3.2/editor/editor_file_system.cpp:1788)
[8] EditorFileSystem::reimport_files(Vector<String> const&) (/mnt/Miecz/godot3.2/editor/editor_file_system.cpp:1984 (discriminator 3))
[9] EditorFileSystem::_update_scan_actions() (/mnt/Miecz/godot3.2/editor/editor_file_system.cpp:592)
[10] EditorFileSystem::_notification(int) (/mnt/Miecz/godot3.2/editor/editor_file_system.cpp:1164)
[11] EditorFileSystem::_notificationv(int, bool) (/mnt/Miecz/godot3.2/editor/editor_file_system.h:110 (discriminator 14))
[12] Object::notification(int, bool) (/mnt/Miecz/godot3.2/core/object.cpp:931)
[13] SceneTree::_notify_group_pause(StringName const&, int) (/mnt/Miecz/godot3.2/scene/main/scene_tree.cpp:992)
[14] SceneTree::idle(float) (/mnt/Miecz/godot3.2/scene/main/scene_tree.cpp:529 (discriminator 3))
[15] Main::iteration() (/mnt/Miecz/godot3.2/main/main.cpp:2115)
[16] OS_X11::run() (/mnt/Miecz/godot3.2/platform/x11/os_x11.cpp:3628)
[17] godots(main+0x326) [0x172cefc] (/mnt/Miecz/godot3.2/platform/x11/godot_x11.cpp:57)
[18] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fd8a706e0b3] (??:0)
[19] godots(_start+0x2e) [0x172cb1e] (??:?)

```
**Steps to reproduce:**
1. Just open editor

**Minimal reproduction project:**
[ImportFiles.zip](https://github.com/godotengine/godot/files/6059382/ImportFiles.zip)

### PR DESCRIPTION
**Pull request by gongpha**
Fixes #46542.

I wish there is a better way to handle this.

### CODE REVIEW

File: modules/bmp/image_loader_bmp.cpp [hunk 1]
```diff
@@ -91,11 +91,15 @@ Error ImageLoaderBMP::convert_to_image(Ref<Image> p_image,
...
 		const uint32_t w = bits_per_pixel >= 24 ? width : width_bytes;
 		const uint8_t *line = p_buffer + (line_width * (height - 1));
+		const uint8_t *end_buffer = p_buffer + p_header.bmp_info_header.bmp_size_image;
 
 		for (uint64_t i = 0; i < height; i++) {
 			const uint8_t *line_ptr = line;
 
 			for (unsigned int j = 0; j < w; j++) {
+				if (line_ptr >= end_buffer) {
+					return ERR_FILE_CORRUPT;
```
Comment (fire) [inline modules/bmp/image_loader_bmp.cpp:101]: We use ERR_FAIL_COND typically instead of an if statement because one extra thing it does is show the line number.

File: modules/bmp/image_loader_bmp.cpp [hunk 2]
```diff
@@ -91,11 +91,13 @@ Error ImageLoaderBMP::convert_to_image(Ref<Image> p_image,
 		// the data width in case of 8/4/1 bit images
 		const uint32_t w = bits_per_pixel >= 24 ? width : width_bytes;
 		const uint8_t *line = p_buffer + (line_width * (height - 1));
+		const uint8_t *end_buffer = p_buffer + p_header.bmp_info_header.bmp_size_image;
```
Comment (fire) [inline modules/bmp/image_loader_bmp.cpp:94]: bmp_size_image do we trust this number? How is this calculated? I would expect the buffer size to be calculable from the size of the bmp.

Comment (gongpha) [reply modules/bmp/image_loader_bmp.cpp:94]: I found that buffer size is calculated from `bmp_file_size - bmp_file_offset`. However, if two variables are corrupt but the buffer had allocated as calculated. I think it may be safe to trust this calculation.

**Review by theraot — APPROVED** [review]
- I tested that the bug still works on master, and also that this fixes it.
- Yep, that would be how you compute the buffer size, as evidenced here: https://github.com/godotengine/godot/blob/ac5d7abe13b658078111b3144c748dc72bd287d1/modules/bmp/image_loader_bmp.cpp#L280-L281

Would this change allow Godot to catch every possible case of a corrupted image? No, probably not. But it will prevent crashes!

*I would argue the class would benefit from a refactor, but that is not here nor there.*

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
