### PR TITLE
Move GridMapEditor to bottom panel

### LINKED ISSUE #10405: Add a GridMap bottom panel (similar to TileMap)
### Describe the project you are working on

I am working on a Twinstick Shooter starter kit:
https://github.com/Nodragem/twin-stick-shooter-starter-kit
I've used Gridmap for making the levels, using Kaykit's prototype bits.

### Describe the problem or limitation you are having in your project

Gridmap is a very useful tool for putting static, grid-based, modular parts of a level together. It deserves a lot of love 😸 !

This proposal tries to make the UI of Gridmap a little bit better, and more consistent with the other nodes:
- 1) **making Gridmap tools more visible**: at the moment, a lot of the tools are hidden behing a shortcut or in the Gridmap menu. This proposal suggests to surface all the tools on the screen as it is done for Tilemap.
- 2) **moving Gridmap UI to the Bottom Panel:** at the moment, the Gridmap dock is on the right side, while most Nodes with advanced on-screen functionality use the bottom panel (e.g. AnimationPlayer, Tilemap, etc),
- 3) **making space for tool settings**: out of scope for this proposal, but it will make space to add settings for the tools (e.g. brush size, brush spacing)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Done above.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I have built a little mockup here. Maybe the tool icons are not matching one-to-one to the current tools (I just copy-pasted the one in Tilemap); but that's the idea.
mockup

Here the full list of tools, with possible shortcuts:
- Selection mode (Q)
- Erase mode (W)
- Paint mode (E)
- Pick mode (R)
- Fill action (Z)
- Move tool (cut and paste) (X)
- Duplicate tool (copy and paste) (C)
- Delete tool (V) 
- Rotate tools  (A,S,D)
- Floor selection (1, 3)
- Change editing plane (Shift + Z,X,C)

In terms of implementation, I'd try to stick to the current behavior of the current tools.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

It is a core feature.

### LINKED ISSUE #19860: Gridmap spatial gizmo is not responding
Godot 3.0.4

With a Gridmap node, the spatial gizmo cannot be moved, rotated or scaled. It places tiles instead.
The gizmo should be able to receive and handle input before the gridmap plugin.

Note: when I first open the scene, the gizmo responds, but it doesn't anymore as soon as any tile in the right panel is selected.

Similar to #17499

### LINKED ISSUE #74520: Grid Map 3D controls overrides camera movement.
### Godot version

4.0 Stable

### System information

Windows 10 x64, AMD Athlon(tm) II X4 640 Processor   3.01 GHz

### Issue description

When having Grid Map 3D selected with a tile selected, you can't move the camera any way possible, until you change the current selected object in the hierarchy.

### Steps to reproduce

1. Have the Grid Map 3D be selected in the hierarchy.
2. Select a tile.
3. Try moving or rotating the camera.
4. Get frustrated.
5. OTL

### Minimal reproduction project

[Super Frustration Grid Map 3D.zip](https://github.com/godotengine/godot/files/10903630/Super.Frustration.Grid.Map.3D.zip)

### LINKED ISSUE #87487: Tapping Q and E while GridMap node is selected and right-click is pressed down triggers floor change in Editor
### Tested versions

4.2.1

### System information

Godot v4.2.1.stable - macOS 14.1.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

In the Godot Editor, select the GridMap node in the tree and switch to 3D view. Now click and hold the right mouse button to rotate the camera in the editor. Now tap the Q and E buttons to move the camera up and down. You will notice that it is also changing the active floor of the Gridmap by -1 and +1.

### Steps to reproduce

see above

### Minimal reproduction project (MRP)

[gridMapCameraIssue.zip](https://github.com/godotengine/godot/files/14015826/gridMapCameraIssue.zip)

### LINKED ISSUE #92655: Gridmap selection only follows world grid and not gridmap
### Tested versions

- Reproducable in 4.2 stable, 4.3 dev6, and 4.3 beta1

### System information

Windows 11

### Issue description

I offset my gridmap so that the world origin would align with the center of a tile (the GridMap node's transform position is 1, 0, 1). However, when I shift-select, the base of the selection remains aligned with the original world grid and not the gridmap which has an offset position. 
gridmapselectionerror

### Steps to reproduce

1. Add GridMap node
2. Change transform position
3. Shift+click and drag to see the selection box and outline

### Minimal reproduction project (MRP)

[gridmap.zip](https://github.com/user-attachments/files/15522928/gridmap.zip)

### PR DESCRIPTION
**Pull request by Nodragem**
implements the proposal: https://github.com/godotengine/godot-proposals/issues/10405

https://github.com/user-attachments/assets/9c24679c-5cc6-4302-a8d5-6c40aed6fea6

with:
- minimum changes to the current tools and functionality of Gridmap;
- a cursor that changes color depending on the tool you are using
- I might have corrected some unexpected behaviours along the way (e.g. no tile selected when first opening)

*Bugsquad edit:*
- Fixes https://github.com/godotengine/godot/issues/19860
- Fixes https://github.com/godotengine/godot/issues/74520
- Fixes https://github.com/godotengine/godot/issues/87487
- Fixes https://github.com/godotengine/godot/issues/92655
- Closes: https://github.com/godotengine/godot-proposals/issues/10405

### CODE REVIEW

**Comment by Nodragem** [comment]
the conflict does not seem to be super important, it's about a `#include`, but I would need to double-check which `#include` are really needed.
```
<<<<<<< moving-gridmap-panel-one-commit
#include "editor/editor_command_palette.h"
=======
#include "editor/editor_main_screen.h"
>>>>>>> master
```

**Comment by ShawnHardern** [comment]
I think this would be a fantastic addition! 🥳 From an engine usability perspective, this change greatly improves the consistency between the placement of the GridMapEditor and the TileMap (for example). From personal experience, the difference has been a bit confusing, and this update would make the UI feel much more cohesive and intuitive. Was there originally a reason the GridMapEditor was placed on the right and not made consistent with something like TileMap?

**Comment by HeadClot** [comment]
I am very happy that grid map is getting some much needed love :)

**Comment by Nodragem** [comment]
I forgot to mentionned that:
- I resolved the merge conflict (I don't use the minimim width anymore),
- I cleaned the code so that it passes the automated checks,

The merge conflict made me realised that we can probably delete some of the editor settings for Gridmap which aren't relevant anymore.

**Comment by smix8** [comment]
In general in favor of moving it to the bottom panel. 

Not sure about all the "extras" in this PR. I tested a little and while overall it worked decent it did not take long to encounter all kinds of random visual or selection bugs. E.g. a giant version of the new selection cursor appearing at scene load out of nowhere. I had multiple random instances when playing with the toolbar options the selection wouldn't update correctly. Maybe some of those issues already existed but since there where no visuals it was hard to notice. Whatever the case this needs more testing from people.

**Comment by smix8** [comment]
The "big selection cursor" happens for me by just opening a scene with a GridMap node or switching to it. The GridMap node does not even need to be selected or something.

I think this is one of the main issues that should be fixed for this PR because it is something that all users will notice.

 I am personally fine with keeping the already existing GridMap bugs for other PRs, rome wasn't (re)build in a day as well.

**Comment by Nodragem** [comment]
Hello, I had a go with the code today.

Here are the changes/fixes:
- made sure that the cursor is not visible when entering the scene tree (the giant cube issue)
- fixed the rotation of the selection when using `keep selection` and rotations during move or duplicate action 
- reintroduced the `clear rotation` action in the tool popup menu (quite useful to reset the rotation!!)
- deleted a few lines of code that where obsolete

**Before we can merge this PR**, I would like to fix a bug that was already there before but that is a little bit worse now:
- when using Gridmap, we can't use the move/rotate/scale tool of the 3D Editor to transform the Gridmap

This issue already existed, but you could use ESC to unselect the current tile in the Gridmap's palette. In this particular state of the Gridmap you could use the move/rotate/scale tool of the 3D editor. This walkaround won't work anymore, and it was not easy to find anyway.

What I would like to do is to add a `transform mode` on the left to the `selection mode`:
image

It will be obvious to find for the users and in this mode, the input will be relegated to the 3D Editor, allowing the move/rotate/scale tool to work.

**Comment by Nodragem** [comment]
Today I added the Transform Mode which can be toggled with T. This makes it easy for the user to be in a state where they can move, rotate, scale the gridmap.

**When in Transform Mode,** the Transform gizmo of the 3D Editor will be visible and QWER selects the 3D Editor tools: Node Selection, Move, Rotate and Scale.

**When NOT in Transform Mode,** the Transform gizmo of the 3D editor is hidden, and QWER selects the Gridmap tools: Selection Mode, Paint Mode, Erased Mode, etc.

Here is a demo (although we don't see which key I am typing!):

https://github.com/user-attachments/assets/1e1dd73a-8b4b-4c3c-8c73-41c24a581fd2

I also fixed the following (pre-existing) bug where the selection floor was not applying the transform of the Gridmap:
Screenshot 2024-10-13 112155

**Comment by Nodragem** [comment]
Speaking with @smix8 today, we think that for this PR, I may have to drop the following feature:
- when _not_ in Transform mode in the Gridmap bottom panel, the Transform gizmo of the 3D Editor is hidden. 

This is because I edited the `Node3DEditorViewport` code to achieve that and it might delay the reviewing process.

Alternatively, @smix8 suggested that I could implement a `EditorNode3DGizmoPlugin` for Gridmap and hence show different gizmos depending on the tool mode. This would be a cleaner way to implement the different cursors, but I am not sure that it would allow me to hide the 3D Editor's Transform gizmo. I would also be a lot of refactoring work so better in another PR!

If anyone can think of an easy way to hide/show the Transform gizmo of the 3D Editor, please let me know!

**Comment by Nodragem** [comment]
I implemented the new solution to hide/show the transform gizmo, using `set_state()`. Hence all my changes are now contained within the Gridmap module.

**Comment by kitbdev** [comment]
Is this the same bug that was fixed?
- https://github.com/godotengine/godot/issues/19860

If so, then related:
- https://github.com/godotengine/godot/pull/97664

**Comment by Nodragem** [comment]
> Is this the same bug that was fixed?
> 
>     * [Gridmap spatial gizmo is not responding #19860](https://github.com/godotengine/godot/issues/19860)

yes this PR solves this issue! The bottom panel adds the concept of "tool mode" so you can select between transform, paint, erase, pick and selection mode. In transform mode, the inputs are simply delegated to the 3D Editor and transform gizmo. In other modes, the transform gizmo is hidden.

Note: I don't why the videos don't work anymore :/ might need to update them.

**Comment by Nodragem** [comment]
If I understand well, the conflict is about replacing `set_icon` with `set_button_icon`, so it should not be too complicated. I will have a look now.

**Review by smix8 — APPROVED** [review]
Approving the change to bottom panel. I think it is a good change and consistent with TileMap. The side panel also limited what could be reasonably added in the editor for GridMap considering how already cramped it was around the main Viewport window.

I didn't encounter (new) bugs while testing it except issues that already exists in GridMap and need to be solved in with different PRs.

PR still needs a code review from someone.

File: modules/gridmap/editor/grid_map_editor_plugin.h [hunk 1]
```diff
@@ -71,11 +75,34 @@ class GridMapEditor : public VBoxContainer {
...
+	Button *duplicate_action_button = nullptr;
+	Button *delete_action_button = nullptr;
+	// rotation
+	Button *rotate_x_button = nullptr;
+	Button *rotate_y_button = nullptr;
+	Button *rotate_z_button = nullptr;
+
+	// toggle
+	// Button *keep_selected_button = nullptr;
+
```
Comment (AThousandShips) [inline modules/gridmap/editor/grid_map_editor_plugin.h:100]:
```suggestion
```
Remove dead code

File: modules/gridmap/editor/grid_map_editor_plugin.cpp [hunk 2]
```diff
@@ -1275,40 +1323,187 @@ GridMapEditor::GridMapEditor() {
...
+	HBoxContainer *action_buttons = memnew(HBoxContainer);
+	toolbar->add_child(action_buttons);
+
+	fill_action_button = memnew(Button);
+	fill_action_button->set_theme_type_variation("FlatButton");
+	fill_action_button->set_shortcut(ED_SHORTCUT("grid_map/fill_tool", TTR("Fill"), Key::Z, true));
+	fill_action_button->connect(SceneStringName(pressed),
+			callable_mp(this, &GridMapEditor::_menu_option).bind(MENU_OPTION_SELECTION_FILL));
+	action_buttons->add_child(fill_action_button);
+	// viewport_shortcut_buttons.push_back(fill_action_button);
```
Comment (AThousandShips) [inline modules/gridmap/editor/grid_map_editor_plugin.cpp:1399]:
```suggestion
```

File: modules/gridmap/editor/grid_map_editor_plugin.cpp [hunk 3]
```diff
@@ -1275,40 +1323,187 @@ GridMapEditor::GridMapEditor() {
...
+
+	move_action_button = memnew(Button);
+	move_action_button->set_theme_type_variation("FlatButton");
+	move_action_button->set_shortcut(ED_SHORTCUT("grid_map/move_tool", TTR("Move"), Key::X, true));
+	move_action_button->connect(SceneStringName(pressed),
+			callable_mp(this, &GridMapEditor::_menu_option).bind(MENU_OPTION_SELECTION_CUT));
+	action_buttons->add_child(move_action_button);
+	// viewport_shortcut_buttons.push_back(move_action_button);
```
Comment (AThousandShips) [inline modules/gridmap/editor/grid_map_editor_plugin.cpp:1407]:
```suggestion
```

File: modules/gridmap/editor/grid_map_editor_plugin.cpp [hunk 4]
```diff
@@ -1275,40 +1323,187 @@ GridMapEditor::GridMapEditor() {
...
+
+	duplicate_action_button = memnew(Button);
+	duplicate_action_button->set_theme_type_variation("FlatButton");
+	duplicate_action_button->set_shortcut(ED_SHORTCUT("grid_map/duplicate_tool", TTR("Duplicate"), Key::C, true));
+	duplicate_action_button->connect(SceneStringName(pressed),
+			callable_mp(this, &GridMapEditor::_menu_option).bind(MENU_OPTION_SELECTION_DUPLICATE));
+	action_buttons->add_child(duplicate_action_button);
+	// viewport_shortcut_buttons.push_back(duplicate_action_button);
```
Comment (AThousandShips) [inline modules/gridmap/editor/grid_map_editor_plugin.cpp:1415]:
```suggestion
```

File: modules/gridmap/editor/grid_map_editor_plugin.cpp [hunk 5]
```diff
@@ -1275,40 +1323,187 @@ GridMapEditor::GridMapEditor() {
...
+	HBoxContainer *rotation_buttons = memnew(HBoxContainer);
+	toolbar->add_child(rotation_buttons);
+
+	rotate_x_button = memnew(Button);
+	rotate_x_button->set_theme_type_variation("FlatButton");
+	rotate_x_button->set_shortcut(ED_SHORTCUT("grid_map/cursor_rotate_x", TTR("Cursor Rotate X"), Key::A, true));
+	rotate_x_button->connect(SceneStringName(pressed),
+			callable_mp(this, &GridMapEditor::_menu_option).bind(MENU_OPTION_CURSOR_ROTATE_X));
+	rotation_buttons->add_child(rotate_x_button);
+	// viewport_shortcut_buttons.push_back(rotate_x_button);
```
Comment (AThousandShips) [inline modules/gridmap/editor/grid_map_editor_plugin.cpp:1436]:
```suggestion
```

File: modules/gridmap/editor/grid_map_editor_plugin.cpp [hunk 6]
```diff
@@ -1275,40 +1323,187 @@ GridMapEditor::GridMapEditor() {
...
+
+	rotate_y_button = memnew(Button);
+	rotate_y_button->set_theme_type_variation("FlatButton");
+	rotate_y_button->set_shortcut(ED_SHORTCUT("grid_map/cursor_rotate_y", TTR("Cursor Rotate Y"), Key::S, true));
+	rotate_y_button->connect(SceneStringName(pressed),
+			callable_mp(this, &GridMapEditor::_menu_option).bind(MENU_OPTION_CURSOR_ROTATE_Y));
+	rotation_buttons->add_child(rotate_y_button);
+	// viewport_shortcut_buttons.push_back(rotate_y_button);
```
Comment (AThousandShips) [inline modules/gridmap/editor/grid_map_editor_plugin.cpp:1444]:
```suggestion
```

File: modules/gridmap/editor/grid_map_editor_plugin.cpp [hunk 7]
```diff
@@ -1275,40 +1323,187 @@ GridMapEditor::GridMapEditor() {
...
+
+	rotate_z_button = memnew(Button);
+	rotate_z_button->set_theme_type_variation("FlatButton");
+	rotate_z_button->set_shortcut(ED_SHORTCUT("grid_map/cursor_rotate_z", TTR("Cursor Rotate Z"), Key::D, true));
+	rotate_z_button->connect(SceneStringName(pressed),
+			callable_mp(this, &GridMapEditor::_menu_option).bind(MENU_OPTION_CURSOR_ROTATE_Z));
+	rotation_buttons->add_child(rotate_z_button);
+	// viewport_shortcut_buttons.push_back(rotate_z_button);
```
Comment (AThousandShips) [inline modules/gridmap/editor/grid_map_editor_plugin.cpp:1452]:
```suggestion
```

File: modules/gridmap/editor/grid_map_editor_plugin.cpp [hunk 8]
```diff
@@ -1275,40 +1323,187 @@ GridMapEditor::GridMapEditor() {
...
+	floor->get_line_edit()->add_theme_constant_override("minimum_character_width", 2);
+	floor->get_line_edit()->set_context_menu_enabled(false);
+	floor->connect(SceneStringName(value_changed), callable_mp(this, &GridMapEditor::_floor_changed));
+	floor->connect(SceneStringName(mouse_exited), callable_mp(this, &GridMapEditor::_floor_mouse_exited));
+	floor->get_line_edit()->connect(SceneStringName(mouse_exited), callable_mp(this, &GridMapEditor::_floor_mouse_exited));
 
 	search_box = memnew(LineEdit);
-	search_box->set_h_size_flags(SIZE_EXPAND_FILL);
+	search_box->add_theme_constant_override("minimum_character_width", 10);
+	// search_box->set_h_size_flags(SIZE_EXPAND_FILL);
```
Comment (AThousandShips) [inline modules/gridmap/editor/grid_map_editor_plugin.cpp:1477]:
```suggestion
```

File: modules/gridmap/editor/grid_map_editor_plugin.cpp [hunk 9]
```diff
@@ -613,13 +630,93 @@ void GridMapEditor::_do_paste() {
 	_clear_clipboard_data();
 }
 
+void GridMapEditor::_show_viewports_transform_gizmo(bool value) {
+	Dictionary new_state;
+	new_state["transform_gizmo"] = value;
```
Comment (AThousandShips) [inline modules/gridmap/editor/grid_map_editor_plugin.cpp:635]:
```suggestion
void GridMapEditor::_show_viewports_transform_gizmo(bool p_value) {
	Dictionary new_state;
	new_state["transform_gizmo"] = p_value;
```

File: modules/gridmap/editor/grid_map_editor_plugin.h [hunk 10]
```diff
@@ -208,6 +242,7 @@ class GridMapEditor : public VBoxContainer {
 	void _set_clipboard_data();
 	void _update_paste_indicator();
 	void _do_paste();
+	void _show_viewports_transform_gizmo(bool value);
```
Comment (AThousandShips) [inline modules/gridmap/editor/grid_map_editor_plugin.h:245]:
```suggestion
	void _show_viewports_transform_gizmo(bool p_value);
```

Comment (Nodragem) [reply modules/gridmap/editor/grid_map_editor_plugin.h:245]: hello! thank you for reviewing the code. What is the fatest method to accept your changes?
 
I have a button "Commit suggestion" for each of your suggestions, but it would then split the PR into several commits, while you prefer it in a single commit.

Comment (AThousandShips) [reply modules/gridmap/editor/grid_map_editor_plugin.h:245]: You can add suggestions to a batch and commit all together, then you'll need to squash your commits into one, see [the interactive rebase](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase), or you can apply them manually

**Review by AThousandShips — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Comment by geowarin** [comment]
@Nodragem This is a really great change, thank you for your amazing work! :smile: 

However I fear that this reintroduced a bug related to conflicting shortcuts in the editor originally fixed in #79529.

For instance, I have bound the S key to "begin scale transformation" (blender-like shortcuts).

If I'm on the gridmap and I press S to rotate a mesh, it also triggers the scaling of the whole gridmap, making a mess.

**Comment by Nodragem** [comment]
I will have a look today! Should the fix be a new PR?

**Comment by akien-mga** [comment]
> Should the fix be a new PR?

Yes, as this PR was merged so it can't be edited further.

**Comment by Nodragem** [comment]
Here is the new PR: https://github.com/godotengine/godot/pull/99170
Nice catch @geowarin !

**Comment by geowarin** [comment]
After using it a bit more, woah, what a glow up!

Here are a couple of random thoughts, for future improvements:

- I'd like the picker tool to automatically switch to paint mode after picking a mesh
- The fill tool only works when in paint mode. Whereas the intuitive thing is to go to select mode, select an area an click paint immediately, which does not work (you have to switch to select, select area, switch to paint, fill)
- I'd love the arrow keys to move to the next and previous mesh for total keyboard control :smile:

**Comment by Nodragem** [comment]
@geowarin Thanks for the feedback and the ideas.

Would you like to leave your ideas for the next steps in this meta-proposal I've made: https://github.com/godotengine/godot-proposals/issues/10992 ?  Like that we can discuss all related ideas in one place :) thank you!
