### PR TITLE
Fix select_all() crash in RichTextLabel

### LINKED ISSUE #60207: Executing `RichTextLabel.select_all` crashes Godot
### Godot version

4.0.alpha.custom_build. 5974e1432

### System information

Ubuntu 21.10 - Nvidia GTX 970, Gnome shell 40.4 X11

### Issue description

When executing
```
	var temp_variable543 = RichTextLabel.new()
	temp_variable543.set_selection_enabled(true)
	temp_variable543.select_all()
```

Godot crashes with this backtrace
```
scene/gui/rich_text_label.cpp:4235:32: runtime error: member access within null pointer of type 'struct ItemFrame'

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.alpha.custom_build (5974e1432ef7941a5e29f8723dec85aa45505963)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] godot4s() [0x23ba45c] (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/crash_handler_linuxbsd.cpp:55)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f58ef3fe520] (??:0)
[3] CowData<RichTextLabel::Line>::_get_size() const (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/templates/cowdata.h:82)
[4] CowData<RichTextLabel::Line>::size() const (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/templates/cowdata.h:139)
[5] CowData<RichTextLabel::Line>::get(int) const (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/templates/cowdata.h:163 (discriminator 2))
[6] Vector<RichTextLabel::Line>::operator[](int) const (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/templates/vector.h:92)
[7] RichTextLabel::select_all() (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/gui/rich_text_label.cpp:4235)
[8] void call_with_variant_args_helper<__UnexistingClass>(__UnexistingClass*, void (__UnexistingClass::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:241 (discriminator 4))
[9] void call_with_variant_args_dv<__UnexistingClass>(__UnexistingClass*, void (__UnexistingClass::*)(), Variant const**, int, Callable::CallError&, Vector<Variant> const&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:354)
[10] MethodBindT<>::call(Object*, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/object/method_bind.h:334)
[11] Object::callp(StringName const&, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/object.cpp:839 (discriminator 1))
[12] Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/variant/variant_call.cpp:1021)
[13] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/gdscript/gdscript_vm.cpp:1543)
[14] GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/gdscript/gdscript.cpp:1537)
[15] bool Node::_gdvirtual__process_call<false>(double) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/node.h:229 (discriminator 5))
[16] Node::_notification(int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/node.cpp:57)
[17] Node::_notificationv(int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./scene/main/node.h:45 (discriminator 14))
[18] Object::notification(int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/object.cpp:850)
[19] SceneTree::_notify_group_pause(StringName const&, int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/scene_tree.cpp:851)
[20] SceneTree::process(double) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/scene_tree.cpp:450 (discriminator 4))
[21] Main::iteration() (/home/runner/work/GodotBuilds/GodotBuilds/godot/main/main.cpp:2722)
[22] OS_LinuxBSD::run() (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/os_linuxbsd.cpp:356)
[23] godot4s(main+0x48a) [0x23b7d70] (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/godot_linuxbsd.cpp:70)
[24] /lib/x86_64-linux-gnu/libc.so.6(+0x29fd0) [0x7f58ef3e5fd0] (??:0)
[25] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d) [0x7f58ef3e607d] (??:0)
[26] godot4s(_start+0x2e) [0x23b782e] (??:?)
-- END OF BACKTRACE --
================================================================

```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by ConteZero**
Should fix https://github.com/godotengine/godot/issues/60207

### CODE REVIEW

File: scene/gui/rich_text_label.cpp [hunk 1]
```diff
@@ -4265,13 +4265,22 @@ void RichTextLabel::select_all() {
 		}
 		it = _get_next_item(it, true);
 	}
+	if ((from_item == nullptr) || (to_item == nullptr)) {
```
Comment (KoBeWi) [inline scene/gui/rich_text_label.cpp:4268]:
```suggestion
	if (!from_item || !to_item) {
```
Can be simplified.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
