### PR TITLE
Fix inspector jumping when gaining focus

### LINKED ISSUE #100695: Node inspector location jumping when tree item is opened or closed
### Tested versions

Reproducible
v4.4.dev6.mono.official [1f47e4c4e]
v4.4.dev7.mono.official [46c8f8c5c]

NOT reproducible:
v4.3.stable.mono.official [77dcf97d8]
v4.4.dev1.mono.official [28a72fa43]
v4.4.dev2.mono.official [97ef3c837]
v4.4.dev3.mono.official [f4af8201b]
v4.4.dev4.mono.official [36e6207bb]
v4.4.dev5.mono.official [9e6098432]

### System information

Godot v4.4.dev7.mono - Windows 10 (build 19045) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 32.0.15.6094) - Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 threads)

### Issue description

When in the node inspector a item (for example `GPUParticles2D | Process Material | Process Material (Particle Process Material) | Display | Scale`) is clicked open, the view jumps. The item under the mouse cursor is no longer the item that was clicked. Sometimes the item will be higher, sometimes lower in the view, which makes this very annoying. Click something, then try to find the item again.

I haven't been able to reproduce this with simple nodes, like `Node2D,` but with nodes with a lots of stuff, like `GPUParticles2D,` this is easily reproducible.

The jumping happens both when tree items are opened and closed. But it seems that jumping happens only once per node selection. So after the first jump, no other jumps will happen until some other node is selected and then this node is selected again.

The first and second to screenshots show what happens when `Scale` item is opened. The second and third screenshots show wahn happens when `Scale` item is closed. The red arrow shows where the mouse cursor is (sorry, too difficult to get mouse cursor in screenshots in Windows).

Image

### Steps to reproduce

Setup:
1. Add `Node2D` as a root node
2. Add `GPUParticles2D` to the root node
3. Add `Particle Process Material` to the `GPUParticles2D` node

Reproduction:

4. Scroll to `Process Material (Particle Process Material) | Display | Scale`
6. Click `Scale` tree item to open it 
7. => THE PROBLEM `Scale` is no longer under mouse cursor 

Repeat:

9. Click Scale tree item to close it
10. Select scene's root node `Node2D`
11. Select `GPUParticles2D` again 
12. goto step 4

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by KoBeWi**
Closes #100695

### CODE REVIEW

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -4742,6 +4743,15 @@ void EditorInspector::_notification(int p_what) {
 				update_tree();
 			}
 		} break;
+
+		case NOTIFICATION_FOCUS_ENTER: {
+			set_deferred("follow_focus", true);
```
Comment (Maran23) [inline editor/editor_inspector.cpp:4748]: Is `deferring` needed here?

Comment (KoBeWi) [reply editor/editor_inspector.cpp:4748]: I had problems without deferring, but it might've been caused by another thing I fixed. I'll check again to make sure.

**Review by Hilderin — APPROVED** [review]
Tested locally and it fixed the issue. Code looks good.

File: editor/editor_inspector.cpp [hunk 2]
```diff
@@ -4742,6 +4743,15 @@ void EditorInspector::_notification(int p_what) {
 				update_tree();
 			}
 		} break;
+
+		case NOTIFICATION_FOCUS_ENTER: {
+			set_follow_focus(true);
+		} break;
+
+		case NOTIFICATION_FOCUS_EXIT: {
+			// Don't follow focus when the inspector in not focused. Prevents potential jumping when gaining focus.
```
Comment (AThousandShips) [inline editor/editor_inspector.cpp:4752]:
```suggestion
			// Don't follow focus when the inspector is not focused. Prevents potential jumping when gaining focus.
```

**Review by AThousandShips — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
