### PR TITLE
Fix script properties being lost and prevent node reference corruption upon scene reimport

### LINKED ISSUE #91764: The engine crashes when re-importing .gtlf file
### Tested versions

Bugs in 4.3dev6
Works in 4.3dev5

### System information

Windows 10, Ryzen 3 3300x, 16gb RAM 2666mhz, GTX 1660 6gb.

### Issue description

As shown in the video, if I click on re-import the engine crashes, giving a loop of errors in the console.

This all started once I decided to move the .gtlf file across folders in the filesystem. I did this using godot drag and drop. When moving the file, the engine crashed. After that, I started getting these errors.

I've tried deleting the .godot and the related .import file, but nothing has changed.

https://github.com/godotengine/godot/assets/58512144/7ffd5a86-ebae-4a71-9692-12cb46cfdd74

I do not extract any materials or animations from the .gltf file. The only way I interact with this model is through putting a script in its inherited scene. The .gltf file is not used anywhere except in the inherited scene, and the inherited scene is only used once, inside a character.

I've tried re-exporting the file from blender, but nothing has changed.

image
image

This is what's inside the moved folder:

image

And inside the sub-folder Witch. 

image

Considering that maybe this could be a problem, I don't export the .blend file, I always use the .gltf exported.

I tried moving the .gltf file to a new project, and it works normally, so I don't think an MRP makes much sense. I don't know what's causing the error, but it's unsettling how much the engine crashes with me when using the file system.

### Steps to reproduce

Move a .gltf file across folders~, I guess.

### Minimal reproduction project (MRP)

I tried moving the .gltf file to a new project, and it works normally, so I don't think an MRP makes much sense.

### LINKED ISSUE #92277: Script variables get reset upon reimporting a scene.
### Tested versions

6118592c6d88350d01f74faff6fd49754f84a7d0

### System information

Windows 11

### Issue description

If a script with exported variables is attached to a node in an imported scene, it will not always preserve its values when the scene is reimported. This is due to the get_property_list function being called before the script is reattached to the node upon the recovery stage during a reimport.

### Steps to reproduce

Open the sample project and attempt to reimport xbot.gltf. Then check properties for the xbot node. The number and node reference should have been reset.

### Minimal reproduction project (MRP)

[reimport_test.zip](https://github.com/godotengine/godot/files/15415243/reimport_test.zip)

### LINKED ISSUE #92278: Direct node references to reimported scenes will become corrupted and cause crashes upon reimport.
### Tested versions

aa6ed199de43a053336f8833b22ccdd2e2dd29e5

### System information

Window 11

### Issue description

If you have a script in your scene with an exported node reference, if that node reference references a node on contained inside of an imported scene and that scene gets reimported, the node reference will break and/or become corrupted. The fix for this appears to be that in the stage which attempts to save all the properties on relevant nodes during a reimport step, to detect if the property is a node reference, and instead of storing the node itself, store an node path and reaccquire the node reference from that path after the scene has been successfully reimported.

### Steps to reproduce

Open the project, reimport xbot.gltf, and save the scene.

### Minimal reproduction project (MRP)

[reimport_test.zip](https://github.com/godotengine/godot/files/15415371/reimport_test.zip)

### PR DESCRIPTION
**Pull request by SaracenOne**
- Closes: #92278
- Closes: #92277
- Closes: #91764
- Supersedes and closes: #92182

Expands and depends upon the previous PR (https://github.com/godotengine/godot/pull/92182) to fix further bugs in the hot scene reloader. It now prevents script properties on reimported nodes from getting lost, and prevents node reference properties referencing nodes which get replaced by the reimport system from being retained, preventing several cases which can cause editor crashes.

### CODE REVIEW

**Review by fire — COMMENTED** [review]
I tested https://github.com/godotengine/godot/files/15415243/reimport_test.zip.

### On 4.3 and this pr it keeps the last value


https://github.com/godotengine/godot/assets/32321/6a6d82b8-aebf-41ff-b701-ce31f6428131


## On 4.2 it resets on reimport

https://github.com/godotengine/godot/assets/32321/c97597b7-1501-424a-a291-029cd07563b4

Will do more testing.

**Review by fire — APPROVED** [review]
I tested the broken cases. See video. It seems to resolve property reload bugs.

Didn't see anything obviously problematic.

The last attempt to introduce this fix created a signal. In this bugfix pull request we use `_nodes_scene_reimported` as the callback as a replacement.

**Comment by fire** [comment]
@lyuma I expect this to solve your common case of "click on the skeleton" and click reimport to see Godot Engine crash bug.

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -4120,10 +4130,116 @@ void EditorNode::update_ownership_table_for_addition_node_ancestors(Node *p_curr
 	}
 }
 
-void EditorNode::update_diff_data_for_node(
-		Node *p_edited_scene,
+void EditorNode::update_node_from_node_modification_entry(Node *p_node, ModificationNodeEntry &p_node_modification) {
+	if (p_node) {
+		// First, attempt to restore the script property since it may affect the get_property_list method.
+		if (p_node_modification.property_table.find("script")) {
```
[the remark this answers is not in the document]
Comment (SaracenOne) [reply editor/editor_node.cpp]: Updated now with usage of getptr and CoreStringName.

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -4120,10 +4131,118 @@ void EditorNode::update_ownership_table_for_addition_node_ancestors(Node *p_curr
 	}
 }
 
-void EditorNode::update_diff_data_for_node(
-		Node *p_edited_scene,
+void EditorNode::update_node_from_node_modification_entry(Node *p_node, ModificationNodeEntry &p_node_modification) {
+	if (p_node) {
+		// First, attempt to restore the script property since it may affect the get_property_list method.
+		Variant *script_table_entry = p_node_modification.property_table.getptr(CoreStringNames::get_singleton()->_to_string);
```
Comment (AThousandShips) [inline editor/editor_node.cpp:4137]:
```suggestion
		Variant *script_table_entry = p_node_modification.property_table.getptr(CoreStringName(_to_string));
```
Though I assume you meant to fetch the `script` property:
```suggestion
		Variant *script_table_entry = p_node_modification.property_table.getptr(CoreStringName(script));
```

File: editor/editor_node.cpp [hunk 3]
```diff
@@ -31,6 +31,7 @@
 #include "editor_node.h"
 
 #include "core/config/project_settings.h"
+#include "core/core_string_names.h"
```
Comment (AThousandShips) [inline editor/editor_node.cpp:34]:
```suggestion
```
Already included

**Review by AThousandShips — APPROVED** [review]

File: editor/editor_node.cpp [hunk 4]
```diff
@@ -4120,10 +4131,118 @@ void EditorNode::update_ownership_table_for_addition_node_ancestors(Node *p_curr
...
+				}
+			}
+		}
+
+		// Restore the connections to other nodes.
+		for (const ConnectionWithNodePath &E : p_node_modification.connections_to) {
+			Connection conn = E.connection;
+
+			// Get the node the callable is targeting.
+			Node *target_node = cast_to<Node>(conn.callable.get_object());
```
Comment (AThousandShips) [inline editor/editor_node.cpp:4179]:
```suggestion
			Node *target_node = Object::cast_to<Node>(conn.callable.get_object());
```
We normally don't omit this

File: editor/editor_node.cpp (hunk 2 above)
Comment (SaracenOne) [reply editor/editor_node.cpp]: Okay, I fixed this to use the correct StringName now, the change to use format `CoreStringName(script));` doesn't seem to work. Could you elaborate?

File: editor/editor_node.cpp (hunk 3 above)
Comment (SaracenOne) [reply editor/editor_node.cpp:34]: Again, I'm not sure what you mean by this. Removing this `#include` makes it impossible to access CoreStringNames in this context as far as I can tell.

File: editor/editor_node.cpp [hunk 5]
```diff
@@ -4120,10 +4131,119 @@ void EditorNode::update_ownership_table_for_addition_node_ancestors(Node *p_curr
 	}
 }
 
-void EditorNode::update_diff_data_for_node(
-		Node *p_edited_scene,
+void EditorNode::update_node_from_node_modification_entry(Node *p_node, ModificationNodeEntry &p_node_modification) {
+	if (p_node) {
+		// First, attempt to restore the script property since it may affect the get_property_list method.
+		StringName script_property_name = CoreStringNames::get_singleton()->_script;
```
Comment (akien-mga) [inline editor/editor_node.cpp:4137]: This is now:
```suggestion
		StringName script_property_name = CoreStringNames::get_singleton()->script;
```
Since `script_property_name` is only used once, there's little point in having this local variable though. Using `CoreStringNames::get_singleton()->script` directly should be as/more efficient, as it's already a pre-cached StringName.

File: editor/editor_node.cpp (hunk 2 above)
Comment (akien-mga) [reply editor/editor_node.cpp]: Your branch is 800 commits behind `master`, so you're missing a number of important changes there, notably #91909.

So you should rebase, and then you can use what @AThousandShips suggested.

File: editor/editor_node.cpp (hunk 5 above)
Comment (akien-mga) [reply editor/editor_node.cpp:4137]: Duplicate of https://github.com/godotengine/godot/pull/92279#discussion_r1616166022.

File: editor/editor_node.cpp [hunk 6]
```diff
@@ -4137,10 +4147,119 @@ void EditorNode::update_ownership_table_for_addition_node_ancestors(Node *p_curr
 	}
 }
 
-void EditorNode::update_diff_data_for_node(
-		Node *p_edited_scene,
+void EditorNode::update_node_from_node_modification_entry(Node *p_node, ModificationNodeEntry &p_node_modification) {
+	if (p_node) {
+		// First, attempt to restore the script property since it may affect the get_property_list method.
+		StringName script_property_name = CoreStringNames::get_singleton()->script;
+		Variant *script_property_table_entry = p_node_modification.property_table.getptr(script_property_name);
```
Comment (AThousandShips) [inline editor/editor_node.cpp:4154]:
```suggestion
		Variant *script_property_table_entry = p_node_modification.property_table.getptr(CoreStringName(script));
```

**Comment by SaracenOne** [comment]
Thanks @fire, I was a bit confused how the CoreStringNames API was meant to be used.

**Comment by akien-mga** [comment]
Thanks!
