### PR TITLE
Don't show exported script variables twice in the remote inspector

### LINKED ISSUE #39847: Properties duplicated in Remote SceneTree inspector
**Godot version:**
3.2.2.rc4.mono.official

**Issue description:**
In playmode the Scenetree displays properties of nodes twice in different subsections:
grafik

**Steps to reproduce:**
Attach a script (c# in this case) with exported properties to an object, start play, switch to remote Scenetree, select object with script, find properties under 'Members' and also duplicated under 'Script Variables'.

### PR DESCRIPTION
**Pull request by YeldhamDev**
Fixes #39847.

### CODE REVIEW

File: scene/debugger/scene_debugger.cpp [hunk 1]
```diff
@@ -815,9 +815,23 @@ void SceneDebuggerObject::_parse_script_properties(Script *p_script, ScriptInsta
...
+	for (const PropertyInfo &E : pinfo) {
+		if (E.usage & (PROPERTY_USAGE_EDITOR | PROPERTY_USAGE_CATEGORY)) {
+			exported_members.push_back(E.name);
+		}
+	}
+
 	// Members
 	for (KeyValue<const Script *, HashSet<StringName>> sm : members) {
 		for (const StringName &E : sm.value) {
+			if (exported_members.has(E)) {
```
Comment (KoBeWi) [inline scene/debugger/scene_debugger.cpp:831]: Seems like this should be a HashSet?

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by mihe** [comment]
This change doesn't take into account that `_parse_script_properties` can be called with a `p_instance` that's `nullptr`, leading to a crash when the call to `p_instance->get_property_list` happens.

https://github.com/godotengine/godot/blob/7a207b3eaa6ebeb020a83b52467ddcab9ee1ccf4/scene/debugger/scene_debugger.cpp#L776-L779

https://github.com/godotengine/godot/blob/7a207b3eaa6ebeb020a83b52467ddcab9ee1ccf4/scene/debugger/scene_debugger.cpp#L820-L821

I got this crash when capturing an ObjectDB snapshot at any point in [godotengine/tps-demo](https://github.com/godotengine/tps-demo), using the new ObjectDB Profiler.

I'm not very familiar with this code, but I assume a simple `if (p_instance)` should suffice?

**Comment by akien-mga** [comment]
Yeah adding a `if (p_instance)` check should be good. Could you send a PR?
I'm about to (re)start dev5 builds.

**Comment by mihe** [comment]
> Could you send a PR?

Done: #113395
