### PR TITLE
Prevent locked and child nodes of selection groups from being selected in the Game view

### LINKED ISSUE #113892: Locked nodes are selectable in the Game view
### Tested versions

- 4.6.dev
- 4.5

### System information

Windows 11 (build 22631) - OpenGL 3 (Compatibility)

### Issue description

Locking a node to prevent selection works in the editor's viewport, but not in the Game view.

I have a whole-screen effect using a `ColorRect`. Since it is always on top of everything in the running game, I can't select anything else when in 2D selection mode in the Game view.

The editor uses metadata for locking nodes, `_edit_lock_`. It is available at runtime, so it can be used by the Game view too to prevent selection.

### Steps to reproduce

Lock any 2D node and select it in the Game view.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by ydeltastar**
- Fix https://github.com/godotengine/godot/issues/113892

This makes selection in the Game view work like in the 2D/3D view, where regular selection skips locked nodes or selects the parent when it's the child of a selection group. Also, like in the main views, these nodes are still included when in list mode with a suffix "(Locked)" or "(Grouped)".

### CODE REVIEW

**Comment by YeldhamDev** [comment]
This should be an option, not hardcoded behavior.

**Comment by AThousandShips** [comment]
Is it optional in the editor? If not it should be in both or neither I'd say

**Comment by YeldhamDev** [comment]
@AThousandShips Selection needs work differently from editor to debugging. Wanting to select specific components that would probably be locked/grouped in-editor comes much more often, and having to always use the list mode to select them would create unnecessary attrition.

**Comment by ydeltastar** [comment]
> Wanting to select specific components that would probably be locked/grouped in-editor comes much more often

Not my experience. If I'm using locking or selection groups, it's because these nodes are really in the way of what I want to pick.

I added the options.

**Review by YeldhamDev — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

File: scene/debugger/scene_debugger.cpp [hunk 1]
```diff
@@ -1881,6 +1885,57 @@ void RuntimeNodeSelect::_physics_frame() {
...
+			// Replace the node by the group if grouped.
+			if (prefer_group_selection) {
+				while (node && node != root) {
+					if (node->has_meta("_edit_group_")) {
+						final_node = node;
+
+						if (Object::cast_to<CanvasItem>(final_node)) {
+							CanvasItem *ci_tmp = Object::cast_to<CanvasItem>(final_node);
+							order = ci_tmp->get_effective_z_index() + ci_tmp->get_canvas_layer();
+						} else if (Object::cast_to<Node3D>(final_node)) {
```
Comment (AThousandShips) [inline scene/debugger/scene_debugger.cpp:1903]: This broke 3D disabled builds, needs to be in `#ifndef _3D_DISABLED` checks, will make a fix tomorrow if someone hasn't gotten to it before then

Edit: Will write a fix now, pushing momentarily
