### PR TITLE
C#: Print error when MethodBind/Callable call fails

### LINKED ISSUE #59830: [Mono] `Node.Call()` silently fails
### Godot version

v4.0.alpha.mono.custom_build [a647fb3e6]

### System information

manjaro KDE

### Issue description

When you use `Node.call()` if the args of the function doesnt exacly matches the target node's function it doesnt report to the user that the target function doesnt exists!

PS: I tested only in C# but not sure about gdscript

### Steps to reproduce

* create a script
* copy the following script:
```gdscript
extends Node

func _ready() -> void:
  call("test_func") # should not work because test_func has a number argument, but godot doesnt report this user mistake
  pass

func test_func(number:float) -> void: print(number)

```

```cs
public partial class Test : Node
{

  public override void _Ready()
  {
    Call("TestFunc"); //should not work because test_func has a number argument, but godot doesnt report this user mistake
  }
  
  public void TestFunc(float number)
  {
    GD.Print(number);
  }
}
```

### Minimal reproduction project

N/a

### PR DESCRIPTION
**Pull request by raulsntos**
- Implement same behavior for handling `CallError` as in [GDScript VM](https://github.com/godotengine/godot/blob/85c9db592f22941ce7c2a540a526e702f4cc1848/modules/gdscript/gdscript_vm.cpp) (except it doesn't do `debug_break`, just printing the error for now since the debugger functions are not implemented in C# yet).
	- Fixes https://github.com/godotengine/godot/issues/59830.
- Add missing member to `CallError` enum.
	- Member was added to Core in https://github.com/godotengine/godot/pull/62468.

### CODE REVIEW

File: modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs [hunk 1]
```diff
@@ -135,5 +135,122 @@ public static void LogUnhandledException(Exception e)
...
+                    }
+                    else
+#endif
+                    {
+                        return $"Invalid type in {where}. Cannot convert argument {errorarg + 1} from {args[errorarg]->Type} to {error.Expected}.";
+                    }
+                }
+                case godot_variant_call_error_error.GODOT_CALL_ERROR_CALL_ERROR_TOO_MANY_ARGUMENTS:
+                case godot_variant_call_error_error.GODOT_CALL_ERROR_CALL_ERROR_TOO_FEW_ARGUMENTS:
+                    return $"Invalid call to {where}. Expected {error.Argument} arguments.";
```
Comment (RedworkDE) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:222]: This case doesn't seem to get triggered and instead the invalid method case is used.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs [hunk 2]
```diff
@@ -135,5 +135,122 @@ public static void LogUnhandledException(Exception e)
...
+                    break;
+                case "CallRecursive" when basestr == "Godot.TreeItem":
+                    if (argCount >= 1)
+                    {
+                        methodstr = $"{VariantUtils.ConvertToString(*args[0])} (via TreeItem.CallRecursive)";
+                    }
+                    break;
+            }
+
+            methodstr = $"function '{methodstr}'";
```
Comment (RedworkDE) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:188]: (it is the same in gdscript but) IMO it is kinda weird that the `(via call)` ends up inside the single quotes, I would only keep the method name in the quotes and then have the parenthesized part after.

**Review by RedworkDE — COMMENTED** [review]
Additionally there seem to be a whole bunch of issues related to the error itself, but they are probably largely resolved by https://github.com/godotengine/godot/pull/79280

File: modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs (hunk 1 above)
Comment (raulsntos) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:222]: When the method can't be found, we always use `CALL_ERROR_INVALID_METHOD` regardless of the arg count. See https://github.com/godotengine/godot/issues/69519.

https://github.com/godotengine/godot/blob/f438fdb752cc3417d3926c20c50c92d615cfca0c/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs#L24-L34

I added all the enum cases assuming we may change this behavior in the future and decide to use the other ones.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs (hunk 2 above)
Comment (raulsntos) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:188]: I agree, we don't have to use the exact same messages that GDScript uses but I thought it would be a good starting point. Do you have any opinions on the other messages?

**Comment by raulsntos** [comment]
> Additionally there seem to be a whole bunch of issues related to the error itself, but they are probably largely resolved by https://github.com/godotengine/godot/pull/79280

I'm not sure what issues you are referring to. If they are existing issues then yeah that would be unrelated to this PR. Or are you saying that this PR introduces new issues?

**Comment by RedworkDE** [comment]
I was referring to the errors that pop up when clicking a from of source generated code, which are really visible with this PR as the top stack frame of the error is such a frame, and when you click it you are immediately greeted with a bunch of error popup. So no new issue from this PR but actually not already fixed either.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs (hunk 2 above)
Comment (RedworkDE) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:188]: TBH it's jsut this little detail that annoyed me, but if we (slightly) change these errors I would simplify this whole method a bit:
```cs
        private unsafe static string GetCallErrorWhere(string method, godot_variant* instance, godot_variant** args, int argCount)
        {
            return method == "Call" || method == "CallRecursive"
                ? instance->Type == Variant.Type.Callable
                    ? $"callable '{VariantUtils.ConvertToString(*instance)}'"
                    : $"function '{VariantUtils.ConvertToString(*args[0])}' in base '{GetVariantTypeName(instance)}' via {method}"
                : $"function '{method}' in base '{GetVariantTypeName(instance)}'"
        }
```
ie I would put the via at the end and have `callable` as a prefix instead of `function`

Comment (raulsntos) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:188]: I'm not sure how I feel about nested ternary operators. Also, not sure if we should remove the check for `TreeItem` since then we assume every `CallRecursive` method will have the method name as its first parameter and that may not always be the case.

Comment (RedworkDE) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:188]: just a suggestion, mostly about the message format coupled with an observation that the method can be simplified a lot, except that it didn't exactly work as well as I had guessed. Using proper if statements and adjusting the conditions is probably best.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs (hunk 1 above)
Comment (raulsntos) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:210]: By the way, I just realized the other enums will be used by GDScript, so for example:

```csharp
var gdnode = GetNode("GDScriptNode");
gdnode.Call("my_gdscript_method");
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs (hunk 2 above)
Comment (raulsntos) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs]: I tried simplifying it a bit and changed the method string to be a `StringName` so I can use the cached names in `MethodName`.

**Review by RedworkDE — COMMENTED** [review]
Even with #79280 and #79342 the error location seems a bit confused: 
image
Works great then otherwise, with no more errors by the editor.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs [hunk 3]
```diff
@@ -135,5 +135,110 @@ public static void LogUnhandledException(Exception e)
...
+            }
+        }
+
+        private unsafe static string GetCallErrorWhere(godot_string_name method, godot_variant* instance, godot_variant** args, int argCount)
+        {
+            string? methodstr = null;
+            string basestr = GetVariantTypeName(instance);
+
+            if (method == GodotObject.MethodName.Call
+            || (basestr == "Godot.TreeItem" && method == TreeItem.MethodName.CallRecursive))
```
[the remark this answers is not in the document]
Comment (raulsntos) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:169]: I think you are right, it should be indented. But it could also be all in the same line.

**Comment by raulsntos** [comment]
> Even with https://github.com/godotengine/godot/pull/79280 and https://github.com/godotengine/godot/pull/79342 the error location seems a bit confused

We should probably add `[StackTraceHidden]` to the `DebugCheckCallError` methods, like I do in #79280 for `ErrPrintError`. I'll do it here even though it's weird because in this PR it won't do anything.

**Comment by RedworkDE** [comment]
> We should probably add `[StackTraceHidden]` to the `DebugCheckCallError` methods, like I do in #79280 for `ErrPrintError`. I'll do it here even though it's weird because in this PR it won't do anything.

This doesn't really help (at least for me), unless the stack trace hidden is added pretty much everywhere. Instead I think it is easier to add a PushError overload that allows skipping a few stack frames:

```diff
diff --git a/modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs b/modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs
index 33ebb8171e..83f674989e 100644
--- a/modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs
+++ b/modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs
@@ -336,10 +336,10 @@ namespace Godot
         }
 
         [StackTraceHidden]
-        private static void ErrPrintError(string message, godot_error_handler_type type = godot_error_handler_type.ERR_HANDLER_ERROR)
+        private static void ErrPrintError(string message, godot_error_handler_type type = godot_error_handler_type.ERR_HANDLER_ERROR, int skipFrames = 0)
         {
             // Skip 1 frame to avoid current method.
-            var stackFrame = DebuggingUtils.GetCurrentStackFrame(skipFrames: 1);
+            var stackFrame = DebuggingUtils.GetCurrentStackFrame(skipFrames: skipFrames + 1);
             string callerFilePath = ProjectSettings.LocalizePath(stackFrame.GetFileName());
             DebuggingUtils.GetStackFrameMethodDecl(stackFrame, out string callerName);
             int callerLineNumber = stackFrame.GetFileLineNumber();
@@ -366,6 +366,11 @@ namespace Godot
             ErrPrintError(message);
         }
 
+        internal static void PushErrorWithSkippedFrames(string message, int skipFrames)
+        {
+            ErrPrintError(message, skipFrames: skipFrames);
+        }
+
         /// <summary>
         /// Pushes an error message to Godot's built-in debugger and to the OS terminal.
         ///
diff --git a/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs b/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs
index 28bdc25524..b9e49c9285 100644
--- a/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs
+++ b/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs
@@ -136,7 +136,7 @@ namespace Godot.NativeInterop
             }
         }
 
-        [Conditional("DEBUG"), StackTraceHidden]
+        [Conditional("DEBUG")]
         public unsafe static void DebugCheckCallError(godot_string_name method, IntPtr instance, godot_variant** args, int argCount, godot_variant_call_error error)
         {
             if (error.Error != godot_variant_call_error_error.GODOT_CALL_ERROR_CALL_OK)
@@ -144,11 +144,11 @@ namespace Godot.NativeInterop
                 using godot_variant instanceVariant = VariantUtils.CreateFromGodotObjectPtr(instance);
                 string where = GetCallErrorWhere(method, &instanceVariant, args, argCount);
                 string errorText = GetCallErrorMessage(error, where, args);
-                GD.PushError(errorText);
+                GD.PushErrorWithSkippedFrames(errorText, 3);
             }
         }
 
-        [Conditional("DEBUG"), StackTraceHidden]
+        [Conditional("DEBUG")]
         public unsafe static void DebugCheckCallError(in godot_callable callable, godot_variant** args, int argCount, godot_variant_call_error error)
         {
             if (error.Error != godot_variant_call_error_error.GODOT_CALL_ERROR_CALL_OK)
@@ -156,7 +156,7 @@ namespace Godot.NativeInterop
                 using godot_variant callableVariant = VariantUtils.CreateFromCallableTakingOwnershipOfDisposableValue(callable);
                 string where = $"callable '{VariantUtils.ConvertToString(callableVariant)}'";
                 string errorText = GetCallErrorMessage(error, where, args);
-                GD.PushError(errorText);
+                GD.PushErrorWithSkippedFrames(errorText, 3);
             }
         }
 ```
 
(while this somewhat reintroduces the stack frame count & inlining concerns, after some thinking about it this doesn't apply to the editor as such optimizations are disabled for assemblies built in debug mode)

**Comment by raulsntos** [comment]
> This doesn't really help (at least for me), unless the stack trace hidden is added pretty much everywhere.

Yes, it feels like we'd end up having to add it all throughout GodotSharp at this point. Which is why I suggested in the other PR (https://github.com/godotengine/godot/pull/79280) that maybe we should just filter every frame until we reach the first method defined in the game project assembly.

Anyway, this is kind of unrelated to the purpose of this PR which was only to make sure the `Call` methods would not fail silently, so I decided to undo that change and leave that issue to the other PR (https://github.com/godotengine/godot/pull/79280).

**Review by RedworkDE — APPROVED** [review]
Does what it supposed to, there are some minor issues that are largely resolved by other pending PRs.

**Comment by akien-mga** [comment]
Thanks!
