### PR TITLE
Fix multiple issues with CSGPolygon

### LINKED ISSUE #23257: UV coordinates with CSGPolygon repeat for each face
**Godot version:** 955a913a1fcc7551a3e03017eb2ac8edc4ee7043

**Issue description:**

The `UV.y` coordinate on an extruded `CSGPolygon` in *Path* mode transitions from 0 to 1 for each polygon side. This makes it impossible to wrap a Texture around the whole extruded geometry, forcing repetitions.

Instead, `UV.y` should range from 0 to 1 over the whole polygon's length.

Below is a screenshot of the current behaviour (`ALBEDO=vec3(UV,0)`), clearly showing the green (`UV.y`) channel to ramp up four times for the four visible sides.
godot

Similarly, `UV.x` is repeating for each face, unless "Path Continuous" is checked. I can't see any point in this, and propose "Path Continous" to be checked by default.

**Steps to reproduce:**
1. Create a path, a CSGPolygon, set it to "Path" mode and select the created path
2. Draw an 8-sided polygon
3. Add a ShaderMaterial doing `ALBEDO=vec3(UV,0)` in the fragment shader.

### LINKED ISSUE #48233: `CSGPolygon` faces using circular `Path` are one one side inverted
**Godot version:**
3.3

**OS/device including version:**
Windows 10 (19042.928)

**Issue description:**
When you use `CSGPolygon` in path mode the faces of circular paths are one one side inverted.
grafik

**Steps to reproduce:**
1. Create circular `Path3D`
2. Assign path to `CSGPolygon` in path mode

**Minimal reproduction project:**
[CSG Path.zip](https://github.com/godotengine/godot/files/6384366/CSG.Path.zip)

### LINKED ISSUE #48408: CSGPolygon3D when set to Path mode, Path Rotation set to PathFollow and attached to a Path3D, the resultant geometry normals are inverted.
**Godot version:**
v4.0.dev.custom_build.8abd50359

**OS/device including version:**
Windows 10

**Issue description:**
CSGPolygon3D when set to Path mode, Path Rotation set to PathFollow and attached to a Path3D, the resultant geometry normals are inverted.
This is similar to #48233 except that Path Rotation is set to PathFollow.

image

**Steps to reproduce:**
1. Add a Path3D
2. Create a curve for the Path3D (Add points)
3. Add a CSGPolygon3D
4. Set Mode to Path, assign the Path3D and set Path Rotation to PathFollow

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/6415325/test.zip)

### PR DESCRIPTION
**Pull request by madmiraal**
Currently, there are a number of issues with the way face vertices and UV mappings are created in `CSGPolygon`. This results in normals being inverted, UVs repeating when they shouldn't, and extrusions rotating when they shouldn't. This makes `CSGPolygon` practically unusable. Furthermore, each `CSGPolygon` extrusion mode has its own code, which not only results in a lot of duplicated code, but requires fixes to be applied in multiple places or issues occurring in one mode and not another. This PR fixes the issues and consolidates the code to provide a standard way of creating `CSGPolygons`.

To prevent the UV mapping from simply repeating on each end and each extrusion, I've taken the liberty of defining a UV mapping for the entire `CSGPolygon`: the top half is rolled around the extrusions (`u` along the the length of the extrusions and `v` around the outline of the 2D polygon shape) and the bottom half left and right sides are used for the front and end caps respectively.

So, for example this [texture](https://ambientcg.com/view?id=WoodFloor043):
WoodFloor043_1K_Color
Maps to a sample `CSGPolygon` in `MODE_SPIN`, 270° like this:
CSGPolygon-Spin

In `MODE_PATH`, the `path_continuous_u` parameter (which now defaults to `true` to make it consistent with the other extrusion modes) can be set to `false` to create a repeating pattern along the length of the path as before:

`path_continuous_u` = `true` | `path_continuous_u` = `false`
-- | --
CSGPolygon-Path | CSGPolygon-Path-Repeating

`MODE_PATH`'s `Path Rotation` modes have been fixed so they do what I believe they were intended to do:
- `PATH_ROTATION_POLYGON`: The polygon shape is not rotated.
- `PATH_ROTATION_PATH`: The polygon shape is rotated along the path, but it is not rotated around the path axis.
- `PATH_ROTATION_PATH_FOLLOW`: The polygon shape follows the path and it's rotations around the path axis.

In addition to making `MODE_PATH`'s `path_continuous_u` parameter default to `true`, `MODE_PATH`'s `Path Rotation` mode now defaults to `PathFollow`, because this is the mode most likely to provide a viable shape from a `Path3D`, and `MODE_PATH`'s `Path Interval` property is now constrained to (0; 1].

Finally, the documentation has been updated to reflect both these changes and make some of the other settings clearer.

Closes #23257
Fixes #48233
Fixes #48408
Supersedes #48412

### CODE REVIEW

**Comment by stebulba** [comment]
The code is clearer, I like it.
But my pull request have to rewrite : https://github.com/godotengine/godot/pull/41499

**Comment by madmiraal** [comment]
@stebulba I haven't looked at #41499, but hopefully these changes will actually make it easier to implement godotengine/godot-proposals#1062 for all modes.

File: modules/csg/csg_shape.cpp [hunk 1]
```diff
@@ -2224,11 +2046,11 @@ void CSGPolygon3D::_bind_methods() {
 
 	ADD_PROPERTY(PropertyInfo(Variant::PACKED_VECTOR2_ARRAY, "polygon"), "set_polygon", "get_polygon");
 	ADD_PROPERTY(PropertyInfo(Variant::INT, "mode", PROPERTY_HINT_ENUM, "Depth,Spin,Path"), "set_mode", "get_mode");
-	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "depth", PROPERTY_HINT_EXP_RANGE, "0.001,1000.0,0.001,or_greater"), "set_depth", "get_depth");
+	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "depth", PROPERTY_HINT_EXP_RANGE, "0.01,100.0,0.01,or_greater"), "set_depth", "get_depth");
 	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "spin_degrees", PROPERTY_HINT_RANGE, "1,360,0.1"), "set_spin_degrees", "get_spin_degrees");
 	ADD_PROPERTY(PropertyInfo(Variant::INT, "spin_sides", PROPERTY_HINT_RANGE, "3,64,1"), "set_spin_sides", "get_spin_sides");
 	ADD_PROPERTY(PropertyInfo(Variant::NODE_PATH, "path_node", PROPERTY_HINT_NODE_PATH_VALID_TYPES, "Path3D"), "set_path_node", "get_path_node");
-	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "path_interval", PROPERTY_HINT_EXP_RANGE, "0.001,1000.0,0.001,or_greater"), "set_path_interval", "get_path_interval");
```
Comment (stebulba) [inline modules/csg/csg_shape.cpp:2231]: Why did you change the range of path_interval from "0.001,1000.0,0.001,or_greater" to "0.1,1.0,0.1" ?
For exemple In my slide of my proposal I am using around "0.145".
at least should be "0.01,1.0,0.01" but in same time that limit us a lot in possibility.
Maybe can be "0.005,1.0,0.001" to save us a lot of process with "0.001" of path_interval.

**Comment by BastiaanOlij** [comment]
I'm not sure I get the change for `path_continuous_u`, this was introduced to have the U follow the length of the extruded path. So it would be 0 at the start, and equal to the length of the path at the end. This allows using a tiled texture over the length of the path. A use case here is using CSGPolygon to extrude a road for a driving game where there is a nice repeating road texture.

It sounds like you're changing that behavior which is going to break peoples games.

I do agree that the UV mapping in CSGPolygon leaves a lot to be desired.

**Comment by madmiraal** [comment]
> I'm not sure I get the change for `path_continuous_u`

The only change made to `path_continuous_u` is the default. It now defaults to `true`. This makes it consistent with the other extrusion modes. Setting it to `false` still results in the old behaviour of creating a repeating pattern along the length of the path.

File: modules/csg/csg_shape.cpp (hunk 1 above)
Comment (madmiraal) [reply modules/csg/csg_shape.cpp:2231]: @stebulba I assume you agree that it should never need to be greater than 1. Therefore, the question is about the minimum and the step size.

What is your use case for having a smaller minimum and/or smaller step sizes? Since `path_interval` simply sub-divides each extrusion without adding fidelity. If a user wants to increase the number of extrusions, I would expect the preferred approach to be to increase the number of points on the curve and leave `path_interval` at 1.

It's also worth pointing out that this is just a limitation in the editor. A minimum of 0.1 and a step size of 0.1 seemed reasonable for making adjustments in the editor. However, the user can always set the path interval to any value between (0:1] in code using `set_path_interval()` or the property `path_interval`.

Comment (stebulba) [reply modules/csg/csg_shape.cpp:2231]: I understand.
- I used path_interval 0.152 and 360 points to do the 360 degrees.
- For approximately the same result path_interval 1 and 60 points to do the 360 degrees.
And the render I a lot better. This point is ok.

But I have a bug. When the extrudes follow the curve points, is rotating around it. 
What expected:
copy_paste1
What I got:
copy_paste2
I racing car will get trouble keep on track.

**Comment by stebulba** [comment]
I found a bug. When you reverse the polygon like a mirror or you reverse one point, the mesh is not created as the previous version. This bug, broke my game.
What this change do :

https://user-images.githubusercontent.com/26193340/128980183-b4f12f72-1bd1-4668-a36b-932788695c22.mp4

What should do before your change :

https://user-images.githubusercontent.com/26193340/128980255-c7feb82d-ebb3-47e4-88b7-0b44800db026.mp4

In my game this bug force me to invert face when this pull suppose to fixe it and the front and the back face is inverted with the sides faces.
image

**Comment by madmiraal** [comment]
Fixed bug identified by @stebulba [above](https://github.com/godotengine/godot/pull/49313#issuecomment-896549547), and increased the granularity of `path_interval` in the editor to `0.05` to allow values like `0.25`.

File: modules/csg/csg_shape.cpp [hunk 2]
```diff
@@ -2323,7 +2148,7 @@ NodePath CSGPolygon3D::get_path_node() const {
 }
 
 void CSGPolygon3D::set_path_interval(float p_interval) {
-	ERR_FAIL_COND_MSG(p_interval < 0.001, "Path interval cannot be smaller than 0.001.");
+	ERR_FAIL_COND_MSG(p_interval <= 0 || p_interval > 1, "Path interval must be greater than 0 an less than or equal to 1.0.");
```
Comment (akien-mga) [inline modules/csg/csg_shape.cpp:2151]:
```suggestion
	ERR_FAIL_COND_MSG(p_interval <= 0 || p_interval > 1, "Path interval must be greater than 0 and less than or equal to 1.0.");
```

File: modules/csg/doc_classes/CSGPolygon3D.xml [hunk 3]
```diff
@@ -4,71 +4,73 @@
...
+			The [member polygon] shape is extruded by rotating it around the y-axis.
 		</constant>
 		<constant name="MODE_PATH" value="2" enum="Mode">
-			Shape3D is extruded along a path set by a [Shape3D] set in [member path_node].
+			The [member polygon] shape is extruded along the [Path3D] specified in [member path_node].
 		</constant>
 		<constant name="PATH_ROTATION_POLYGON" value="0" enum="PathRotation">
-			Slice is not rotated.
+			The [member polygon] shape is not rotated.
+			[b]Note:[/b] Requires the path z-coordiantes to continually decrease to ensure viable shapes.
```
Comment (akien-mga) [inline modules/csg/doc_classes/CSGPolygon3D.xml:66]:
```suggestion
			[b]Note:[/b] Requires the path Z coordinates to continually decrease to ensure viable shapes.
```
(Most important to fix is the typo, but we tend to use "Y axis", "XZ plane" so I think "Z coordinates" might be more consistent with existing docs - I didn't check though.)

File: modules/csg/doc_classes/CSGPolygon3D.xml [hunk 4]
```diff
@@ -4,71 +4,73 @@
...
 		</constant>
 		<constant name="PATH_ROTATION_PATH" value="1" enum="PathRotation">
-			Slice is rotated around the up vector of the path.
+			The [member polygon] shape is rotated along the path, but it is not rotated around the path axis.
+			[b]Note:[/b] Requires the path z-coordiantes to continually decrease to ensure viable shapes.
```
Comment (akien-mga) [inline modules/csg/doc_classes/CSGPolygon3D.xml:70]:
```suggestion
			[b]Note:[/b] Requires the path's Z coordinates to continually decrease to ensure viable shapes.
```

File: modules/csg/doc_classes/CSGPolygon3D.xml [hunk 5]
```diff
@@ -4,71 +4,73 @@
...
 		</constant>
 		<constant name="PATH_ROTATION_PATH_FOLLOW" value="2" enum="PathRotation">
-			Slice is rotate to match the path exactly.
+			The [member polygon] shape follows the path and it's rotations around the path axis.
```
Comment (akien-mga) [inline modules/csg/doc_classes/CSGPolygon3D.xml:73]:
```suggestion
			The [member polygon] shape follows the path and its rotations around the path axis.
```

File: modules/csg/doc_classes/CSGPolygon3D.xml [hunk 6]
```diff
@@ -4,71 +4,73 @@
...
 		</member>
 	</members>
 	<constants>
 		<constant name="MODE_DEPTH" value="0" enum="Mode">
-			Shape3D is extruded to [member depth].
+			The [member polygon] shape is extruded along the negative z-axis.
 		</constant>
 		<constant name="MODE_SPIN" value="1" enum="Mode">
-			Shape3D is extruded by rotating it around an axis.
+			The [member polygon] shape is extruded by rotating it around the y-axis.
```
Comment (akien-mga) [inline modules/csg/doc_classes/CSGPolygon3D.xml:59]:
```suggestion
			The [member polygon] shape is extruded by rotating it around the Y axis.
```

File: modules/csg/doc_classes/CSGPolygon3D.xml [hunk 7]
```diff
@@ -4,71 +4,73 @@
...
 		</member>
 		<member name="spin_sides" type="int" setter="set_spin_sides" getter="get_spin_sides">
-			Number of extrusion when [member mode] is [constant MODE_SPIN].
+			When [member mode] is [constant MODE_SPIN], the number of extrusions made.
 		</member>
 	</members>
 	<constants>
 		<constant name="MODE_DEPTH" value="0" enum="Mode">
-			Shape3D is extruded to [member depth].
+			The [member polygon] shape is extruded along the negative z-axis.
```
Comment (akien-mga) [inline modules/csg/doc_classes/CSGPolygon3D.xml:56]:
```suggestion
			The [member polygon] shape is extruded along the negative Z axis.
```

File: modules/csg/doc_classes/CSGPolygon3D.xml [hunk 8]
```diff
@@ -4,71 +4,73 @@
...
 	<methods>
 	</methods>
 	<members>
 		<member name="depth" type="float" setter="set_depth" getter="get_depth" default="1.0">
-			Extrusion depth when [member mode] is [constant MODE_DEPTH].
+			When [member mode] is [constant MODE_DEPTH], the depth of the extrusion.
 		</member>
 		<member name="material" type="Material" setter="set_material" getter="get_material">
-			Material to use for the resulting mesh.
+			Material to use for the resulting mesh. The UV maps the top half of the material to the extruded shape (u along the length of the extrusions and v around the outline of the [member polygon]), the bottom-left quarter to the front end face, and the bottom-right quarter to the back end face.
```
Comment (akien-mga) [inline modules/csg/doc_classes/CSGPolygon3D.xml:18]:
```suggestion
			Material to use for the resulting mesh. The UV maps the top half of the material to the extruded shape (U along the length of the extrusions and V around the outline of the [member polygon]), the bottom-left quarter to the front end face, and the bottom-right quarter to the back end face.
```

**Review by akien-mga — APPROVED** [review]
I'm not familiar with that code but from a quick look it seems sensible, and it fixes important issues.

**Comment by madmiraal** [comment]
Updated with suggested changes to the documentation and the comment.

**Comment by akien-mga** [comment]
Thanks!

File: modules/csg/csg_shape.cpp [hunk 9]
```diff
@@ -2228,11 +2053,11 @@ void CSGPolygon3D::_bind_methods() {
 
 	ADD_PROPERTY(PropertyInfo(Variant::PACKED_VECTOR2_ARRAY, "polygon"), "set_polygon", "get_polygon");
 	ADD_PROPERTY(PropertyInfo(Variant::INT, "mode", PROPERTY_HINT_ENUM, "Depth,Spin,Path"), "set_mode", "get_mode");
-	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "depth", PROPERTY_HINT_RANGE, "0.001,1000.0,0.001,or_greater,exp"), "set_depth", "get_depth");
+	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "depth", PROPERTY_HINT_RANGE, "0.01,100.0,0.01,or_greater,exp"), "set_depth", "get_depth");
```
Comment (aaronfranke) [inline modules/csg/csg_shape.cpp:2056]: Was there any particular reason to make this less granular, raise the minimum, and lower the maximum?
