### PR TITLE
Fixed script and visibility icons's highlight height in tree

### LINKED ISSUE #29919: Script and visibility icon doesn't highlight properly in scene tree
**Godot version:**
3.2.dev.custom_build. c6507933a

**Issue description:**
With clean Godot config, script highlight in scene tree are 1/2 pixels smaller than node name
Zrzut ekranu z 2019-06-20 11-18-37
 
When I set editor scale to 75%, and main font size to 23 then this looks worse
Zrzut ekranu z 2019-06-20 11-17-23

### PR DESCRIPTION
**Pull request by Anutrix**
Fixed script and visibility icons's highlight height in tree.
The issue was due to label_height being more than icon button height.
Fixes https://github.com/godotengine/godot/issues/29919.
Haven't tested for bugs though.

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -1128,6 +1128,8 @@ int Tree::draw_item(const Point2i &p_pos, const Point2 &p_draw_ofs, const Size2
 			for (int j = p_item->cells[i].buttons.size() - 1; j >= 0; j--) {
 				Ref<Texture> b = p_item->cells[i].buttons[j].texture;
 				Size2 s = b->get_size() + cache.button_pressed->get_minimum_size();
+                if(s.height < label_h)
```
Comment (akien-mga) [inline scene/gui/tree.cpp]: Indentation should use tabs, and there should be a space after `if`. See http://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html

Comment (Anutrix) [reply scene/gui/tree.cpp]: Done.

**Comment by akien-mga** [comment]
Thanks!
