### PR TITLE
Remove Adreno 3xx flip workaround

### LINKED ISSUE #108817: Rendering output is vertically flipped on Android 7
### Tested versions

- Reproducible in 4.5-dev5
- Not reproducible in 4.5-dev4
Regression from https://github.com/godotengine/godot/pull/106267

### System information

Samsung Galaxy J5 2016 - Snapdragon 410 - Adreno 306 - Android 7

### Issue description

Rendering output is just flipped vertically. Can't reproduce on Vulkan since it is not supported on tested device. On Android 8+ (Samsung Galaxy J7 2016 for example) this is not reproducible.

With force MSAA x4 enabled, screen is just flickering on splash screen on 4.5-dev4 and lower.

### Steps to reproduce

Run any project on Android 7.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Summersay415**
Fixes #108817

### CODE REVIEW

File: drivers/gles3/rasterizer_gles3.cpp [hunk 1]
```diff
@@ -431,19 +426,11 @@ void RasterizerGLES3::_blit_render_target_to_screen(DisplayServer::WindowID p_sc
...
-	}
-
-	Vector2 p1 = Vector2(flip_x ? screen_rect_end.x : p_blit.dst_rect.position.x, flip_y ? screen_rect_end.y : p_blit.dst_rect.position.y);
-	Vector2 p2 = Vector2(flip_x ? p_blit.dst_rect.position.x : screen_rect_end.x, flip_y ? p_blit.dst_rect.position.y : screen_rect_end.y);
+	Vector2 p1 = Vector2(p_blit.dst_rect.position.x, flip_y ? screen_rect_end.y : p_blit.dst_rect.position.y);
+	Vector2 p2 = Vector2(screen_rect_end.x, flip_y ? p_blit.dst_rect.position.y : screen_rect_end.y);
 	Vector2 size = p2 - p1;
 
-	Rect2 screenrect = Rect2(Vector2(flip_x ? 1.0 : 0.0, flip_y ? 1.0 : 0.0), Vector2(flip_x ? -1.0 : 1.0, flip_y ? -1.0 : 1.0));
+	Rect2 screenrect = Rect2(Vector2(0.0, flip_y ? 1.0 : 0.0), Vector2(1.0, flip_y ? -1.0 : 1.0));
```
Comment (Summersay415) [inline drivers/gles3/rasterizer_gles3.cpp:433]: is everything correct here? flip_x is not used anywhere else, so I decided to remove it

**Review by clayjohn — APPROVED** [review]
Looks great to me!

Removing flip_x is a nice bonus!

**Comment by Repiteo** [comment]
Thanks!
