### PR TITLE
Force window position if spawned outside screen

### LINKED ISSUE #58591: Project Settings window does not appear and locks Godot if it was on secondary screen and then used in a one screen setup (DisplayServer regression)
### Godot version

4.0.alpha3

### System information

Windows 10, RTX3070 laptop, Vulkan

### Issue description

If you have the Project Settings window dragged to a secondary monitor and exit Godot, later if you open Godot on a one monitor setup there's no way to get into the Project Settings or exit the Project Settings window after you open it so you can't continue using Godot without killing it with the task manager and you can't change any of your project settings until you plug a secondary monitor back in. The Project Settings window probably tries to appear on the location it appeared last, but can't because there's no secondary screen so it just doesn't appear at all and locks you out of using Godot.

The Project Settings window should default to showing on the center of the main screen if no additional screens are detected. I also propose making the Project Settings window not disable interaction with the main Godot window. For instance if you want the project settings window to always be open on a secondary monitor but still be able to work on your project.

### Steps to reproduce

have a dual monitor setup
open Godot
open Project Settings window
drag it to secondary monitor
close Godot
unplug secondary monitor
open Godot
open Project Settings window
can't use Godot anymore, must close through Task Manager

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #58591

After window is made visible, I assume it has its final position and screen id. Also if the target position is outside of the desktop available area, the window gets the default/closest screen id (I think). So if the window position is outside of its current screen, it's probably safe to assume that it spawned outside of the visible screen area. When this happens, I force it to the center of its screen.

### CODE REVIEW

File: scene/main/window.cpp [hunk 1]
```diff
@@ -1140,6 +1140,15 @@ void Window::popup(const Rect2i &p_screen_rect) {
 
 	set_transient(true);
 	set_visible(true);
+
+	int screen_id = DisplayServer::get_singleton()->window_get_current_screen(get_window_id());
+	Rect2i screen_rect = Rect2i(DisplayServer::get_singleton()->screen_get_position(screen_id), DisplayServer::get_singleton()->screen_get_size(screen_id));
+	if (!screen_rect.intersects(Rect2i(position, size))) {
```
Comment (bruvzg) [inline scene/main/window.cpp:1146]: It should check for `screen_rect != Rect2i()`, IIRC some Linux configs unable get correct screen rects so `screen_get_position` and `screen_get_size` might fail.

File: scene/main/window.cpp [hunk 2]
```diff
@@ -1212,6 +1212,15 @@ void Window::popup(const Rect2i &p_screen_rect) {
 
 	set_transient(true);
 	set_visible(true);
+
+	int screen_id = DisplayServer::get_singleton()->window_get_current_screen(get_window_id());
+	Rect2i screen_rect = Rect2i(DisplayServer::get_singleton()->screen_get_position(screen_id), DisplayServer::get_singleton()->screen_get_size(screen_id));
```
Comment (bruvzg) [inline scene/main/window.cpp:1217]:
```suggestion
	Rect2i screen_rect = DisplayServer::get_singleton()->screen_get_usable_rect(screen_id);
```
Not a big difference, but can also prevent popups from spawning under the taskbar.

**Review by bruvzg — APPROVED** [review]

**Review by bruvzg — APPROVED** [review]
