### PR TITLE
Fix TextEdit clips children and focus style.

### LINKED ISSUE #32996: TextEdit always clips content
**Godot version:**
3564547208030264a28cc55232992aab3cbdad94

**OS/device including version:**
ArcoLinux

**Issue description:**
TextEdit forcibly clips all content, regardless of whether the `Clip Content` box is checked.

image
image

### LINKED ISSUE #42342: TextEdit text is not clipped into content margin.
**Godot version:**
3.2.3

**OS/device including version:**
Windows 10 ltsc 64 bit

**Issue description:**
The TextEdit text is not clipped to the styles content margin on a per pixel basis.
image

**Steps to reproduce:**
- create a theme
- add all text edit items
- set the style for normal so that it has really small content margin
- apply theme to text edit
- run project and see that the scrollbar is limited to it but not the text drawn.

**Minimal reproduction project:**
[FocusBug.zip](https://github.com/godotengine/godot/files/5284721/FocusBug.zip)

### LINKED ISSUE #74445: Expand Margin is not working in Styles for TextEdit
### Godot version

4.1.dev (5dccc94)

### System information

Ubuntu 22.04, Vulkan renderer, gforce 1650ti

### Issue description

Modifying the Expand Margin property in a style applied to a TextEdit does not draw extending outside the rect like in other controls, which causes the style to be clipped.

### Steps to reproduce

1. Add a TextEdit
2. Add a Style to it
3. Use expand margins
4. Note that it doesn't work as expected

### Minimal reproduction project

[TestTheme.zip](https://github.com/godotengine/godot/files/10892436/TestTheme.zip)

### PR DESCRIPTION
**Pull request by WhalesState**
This PR refactors TextEdit to stop clipping its children and now uses its own CanvasItem logic for drawing text.

Changes:
- TextEdit no longer clips child nodes.
- Custom CI-based drawing is used for rendering text in TextEdit.
- Custom CI-based drawing is used for rendering code completion in CodeEdit.

Note: This PR is not intended to change any existing behavior due to the complexity of the `TextEdit` class. The only goal is to resolve the mentioned issues and improve internal drawing consistency.

* Fixes: https://github.com/godotengine/godot/issues/42342
* Fixes: https://github.com/godotengine/godot/issues/32996
* Fixes: https://github.com/godotengine/godot/issues/74445

### CODE REVIEW

File: editor/themes/editor_theme_manager.cpp [hunk 1]
```diff
@@ -2783,7 +2783,9 @@ void EditorThemeManager::_populate_text_editor_styles(const Ref<EditorTheme> &p_
 	Ref<StyleBoxFlat> code_edit_stylebox = make_flat_stylebox(background_color, p_config.widget_margin.x, p_config.widget_margin.y, p_config.widget_margin.x, p_config.widget_margin.y, p_config.corner_radius);
 	p_theme->set_stylebox(CoreStringName(normal), "CodeEdit", code_edit_stylebox);
 	p_theme->set_stylebox("read_only", "CodeEdit", code_edit_stylebox);
-	p_theme->set_stylebox("focus", "CodeEdit", memnew(StyleBoxEmpty));
+	Ref<StyleBoxFlat> code_edit_focus_stylebox = p_config.button_style_focus->duplicate();
+	code_edit_focus_stylebox->set_expand_margin_all(Math::round(2 * MAX(1, EDSCALE)));
+	p_theme->set_stylebox("focus", "CodeEdit", code_edit_focus_stylebox);
```
Comment (kitbdev) [inline editor/themes/editor_theme_manager.cpp]: I don't think adding a focus to the Script Editor is needed. It has been like this for a long time, and its probably intentional. Also, no other IDEs I tested have focus outlines around their script area.

Changing the default Script Editor look is also unrelated to the rest of the PR, I think it should be discussed separately.

File: scene/gui/code_edit.cpp [hunk 2]
```diff
@@ -177,7 +177,7 @@ void CodeEdit::_notification(int p_what) {
 						code_completion_rect.position.x = caret_pos.x - code_completion_base_width;
 					}
 
-					draw_style_box(theme_cache.code_completion_style, Rect2(code_completion_rect.position - theme_cache.code_completion_style->get_offset(), code_completion_rect.size + theme_cache.code_completion_style->get_minimum_size() + Size2(scroll_width, 0)));
+					theme_cache.code_completion_style->draw(ci, Rect2(code_completion_rect.position - theme_cache.code_completion_style->get_offset(), code_completion_rect.size + theme_cache.code_completion_style->get_minimum_size() + Size2(scroll_width, 0)));
```
Comment (kitbdev) [inline scene/gui/code_edit.cpp:180]: The code completion should probably use the regular canvas item, not the text canvas item. It doesn't need to be clipped. 
- related https://github.com/godotengine/godot/issues/104953

But maybe it would be better as a popup instead? 
Either way it can be done later, since you want to keep this PR focused.

File: scene/gui/text_edit.h [hunk 3]
```diff
@@ -717,6 +718,8 @@ class TextEdit : public Control {
 	// Line hiding.
 	bool hiding_enabled = false;
 
+	RID _get_text_canvas_item() const;
```
Comment (kitbdev) [inline scene/gui/text_edit.h]: The Script Editor draws inline objects and needs to use this canvas item instead.
So this needs to be public. or maybe it could be passed to the function.
See `ScriptTextEditor::_inline_object_draw`.

image

File: scene/gui/text_edit.cpp [hunk 4]
```diff
@@ -901,6 +901,10 @@ void TextEdit::_notification(int p_what) {
 				first_draw = false;
 			}
 
+			RID ci = get_canvas_item();
+			Ref<StyleBox> style = editable ? theme_cache.style_normal : theme_cache.style_readonly;
+			style->draw(ci, Rect2(Point2(), get_size()));
```
Comment (kitbdev) [inline scene/gui/text_edit.cpp]: Why is this draw added here, isn't it already later at line 935?

File: scene/gui/text_edit.cpp [hunk 5]
```diff
@@ -1297,13 +1301,8 @@ void TextEdit::_notification(int p_what) {
...
 			int bottom_limit_y = get_size().height;
-			if (!editable) {
-				top_limit_y += theme_cache.style_readonly->get_margin(SIDE_TOP);
-				bottom_limit_y -= theme_cache.style_readonly->get_margin(SIDE_BOTTOM);
-			} else {
-				top_limit_y += theme_cache.style_normal->get_margin(SIDE_TOP);
-				bottom_limit_y -= theme_cache.style_normal->get_margin(SIDE_BOTTOM);
-			}
+			top_limit_y += style->get_margin(SIDE_TOP);
+			bottom_limit_y -= style->get_margin(SIDE_BOTTOM);
```
Comment (kitbdev) [inline scene/gui/text_edit.cpp]:
```suggestion
			int top_limit_y = style->get_margin(SIDE_TOP);
			int bottom_limit_y = get_size().height - style->get_margin(SIDE_BOTTOM);
```
These can be combined with the above two lines.

File: scene/gui/text_edit.cpp [hunk 6]
```diff
@@ -1366,7 +1365,6 @@ void TextEdit::_notification(int p_what) {
 					int ofs_y = 0;
 					if (!editable) {
 						ofs_x = theme_cache.style_readonly->get_offset().x / 2;
-						ofs_x -= theme_cache.style_normal->get_offset().x / 2;
 						ofs_y = theme_cache.style_readonly->get_offset().y / 2;
 					} else {
 						ofs_y = theme_cache.style_normal->get_offset().y / 2;
```
Comment (kitbdev) [inline scene/gui/text_edit.cpp]: Honestly this existing logic doesn't make any sense. The offset is just the top and left margins and shouldn't be divided by 2, and the x and y offset logic are different.

I think the y offset can just be set to the top margin here, and then the drawing logic can be adjusted in some areas.
But that would require lots more changes, so it doesn't need to be in this PR.

File: scene/gui/text_edit.cpp [hunk 7]
```diff
@@ -1366,7 +1365,6 @@ void TextEdit::_notification(int p_what) {
 					int ofs_y = 0;
 					if (!editable) {
 						ofs_x = theme_cache.style_readonly->get_offset().x / 2;
-						ofs_x -= theme_cache.style_normal->get_offset().x / 2;
```
Comment (kitbdev) [inline scene/gui/text_edit.cpp]: I believe the purpose of this was because `xmargin_beg` used the normal style so this had to remove the normal margin and replace it with the readonly margin. (See https://github.com/godotengine/godot/pull/45858)
Though I don't know why this is divided by 2, it doesn't make any sense.

So now that `xmargin_beg` uses the correct style, `ofs_x` should just be 0, it can be deleted.
But that may need more changes, and it is already broken, so it doesn't need to be done in this PR.

File: scene/gui/text_edit.cpp [hunk 8]
```diff
@@ -4963,7 +4965,8 @@ String TextEdit::get_word(int p_line, int p_column) const {
 }
 
 Point2i TextEdit::get_line_column_at_pos(const Point2i &p_pos, bool p_clamp_line, bool p_clamp_column) const {
-	float rows = p_pos.y - theme_cache.style_normal->get_margin(SIDE_TOP);
+	Ref<StyleBox> style = editable ? theme_cache.style_normal : theme_cache.style_readonly;
+	float rows = p_pos.y - style->get_margin(SIDE_TOP);
 	if (!editable) {
 		rows -= theme_cache.style_readonly->get_offset().y / 2;
 		rows += theme_cache.style_normal->get_offset().y / 2;
```
Comment (kitbdev) [inline scene/gui/text_edit.cpp]: This if statement can be deleted, like the one for the x offset below was deleted.

File: scene/gui/text_edit.cpp [hunk 9]
```diff
@@ -1561,7 +1559,7 @@ void TextEdit::_notification(int p_what) {
 								} else if (rect.position.x + rect.size.x > xmargin_end) {
 									rect.size.x = xmargin_end - rect.position.x;
 								}
-								RS::get_singleton()->canvas_item_add_rect(ci, rect, theme_cache.search_result_color);
+								RS::get_singleton()->canvas_item_add_rect(text_ci, rect, theme_cache.search_result_color);
 								draw_rect(rect, theme_cache.search_result_border_color, false);
```
Comment (kitbdev) [inline scene/gui/text_edit.cpp]: There are 5 `draw_rect`s (including this one) in TextEdit draw that need to be updated to use the new `text_ci`.

**Review by kitbdev — COMMENTED** [review]
I don't know much about the rendering server methods to add canvas items, but it seems to work fine.

Some minor issues:

`CodeEdit::_draw_guidelines` still uses `theme_cache.style_normal`.

`TextEdit::set_editable` should call `update_minimum_size()`.

File: scene/gui/code_edit.cpp (hunk 2 above)
Comment (WhalesState) [reply scene/gui/code_edit.cpp:180]: We can't use the TextEdit CanvasItem because the text is drawn over it.
image

Fixed it by using a new CanvasItem for code completion to make it draw over the text and to not be clipped.
image

File: scene/gui/text_edit.h (hunk 3 above)
Comment (WhalesState) [reply scene/gui/text_edit.h]: Fixed.
image

File: scene/gui/text_edit.cpp (hunk 4 above)
Comment (WhalesState) [reply scene/gui/text_edit.cpp]: Removed the other line.

File: scene/gui/code_edit.cpp (hunk 2 above)
Comment (WhalesState) [reply scene/gui/code_edit.cpp:180]: We may need to convert it to Popup since it draws behind the BottomPanel when the text size is large and we only clip it horizontally.

image

Using `z_index = 1` may solve this issue but the HScrollBar still draws over it:

image

And it still goes off-screen:

image

File: scene/gui/text_edit.cpp (hunk 6 above)
Comment (WhalesState) [reply scene/gui/text_edit.cpp]: It breaks the unit tests but i can fix them, I have kept them earlier to avoid causing regressions from this PR.

File: scene/gui/text_edit.cpp [hunk 10]
```diff
@@ -4979,11 +4971,8 @@ String TextEdit::get_word(int p_line, int p_column) const {
 }
 
 Point2i TextEdit::get_line_column_at_pos(const Point2i &p_pos, bool p_clamp_line, bool p_clamp_column) const {
-	float rows = p_pos.y - theme_cache.style_normal->get_margin(SIDE_TOP);
-	if (!editable) {
-		rows -= theme_cache.style_readonly->get_offset().y / 2;
-		rows += theme_cache.style_normal->get_offset().y / 2;
-	}
+	Ref<StyleBox> style = _get_current_stylebox();
+	float rows = p_pos.y - (style->get_margin(SIDE_TOP) + (theme_cache.line_spacing / 2));
```
Comment (WhalesState) [inline scene/gui/text_edit.cpp]: Fixed a bug here where the half line spacing used to offset the text wasn't taken into account, check the video where the issue happens on the left side.

https://github.com/user-attachments/assets/070b313f-93f2-4da5-a4f2-daab37cea1ed

Note: This will change the return values for `get_pos_at_line_column` and `get_rect_at_line_column`.

File: scene/gui/code_edit.cpp [hunk 11]
```diff
@@ -268,21 +273,22 @@ void CodeEdit::_draw_guidelines() {
 
 	RID ci = get_canvas_item();
 	const Size2 size = get_size();
-	const bool rtl = is_layout_rtl();
+	RenderingServer *rs = RenderingServer::get_singleton();
```
Comment (kitbdev) [inline scene/gui/code_edit.cpp]: Why did you change rtl to not be cached and the rendering server to be cached? 
rtl is cached often since it has more logic to it, and the rendering server singleton doesn't need to be cached.
If it is too long you can use `RS::get_singleton()`.

File: scene/gui/code_edit.cpp (hunk 2 above)
Comment (kitbdev) [reply scene/gui/code_edit.cpp:180]: In that case we can leave it using the text ci, it will have to be made into a popup later. So there is no need to make a separate ci for it.

File: editor/script/script_text_editor.cpp [hunk 12]
```diff
@@ -516,9 +516,12 @@ void ScriptTextEditor::_inline_object_draw(const Dictionary &p_info, const Rect2
...
 			color_alpha_texture = inline_color_picker->get_theme_icon("sample_bg", "ColorPicker");
 		}
-		code_editor->get_text_editor()->draw_texture_rect(color_alpha_texture, col_rect, false);
-		code_editor->get_text_editor()->draw_rect(col_rect, Color(p_info["color"]));
-		code_editor->get_text_editor()->draw_rect(col_rect, Color(1, 1, 1), false, 1);
+		RID text_ci = code_editor->get_text_editor()->get_text_canvas_item();
+		RenderingServer *rs = RenderingServer::get_singleton();
+
+		rs->canvas_item_add_rect(text_ci, p_rect.grow(-3), Color(1, 1, 1));
+		rs->canvas_item_add_texture_rect(text_ci, col_rect, color_alpha_texture->get_rid());
```
Comment (kitbdev) [inline editor/script/script_text_editor.cpp]:
```suggestion
		color_alpha_texture->draw(text_ci, col_rect);
```

File: scene/gui/text_edit.cpp [hunk 13]
```diff
@@ -1311,20 +1312,15 @@ void TextEdit::_notification(int p_what) {
...
-				bottom_limit_y -= theme_cache.style_normal->get_margin(SIDE_BOTTOM);
-			}
+			int top_limit_y = style->get_margin(SIDE_TOP);
+			int bottom_limit_y = get_size().height - style->get_margin(SIDE_BOTTOM);
 
 			// Draw guidelines.
 			_draw_guidelines();
 
 			// Draw main text.
+			RenderingServer *rs = RenderingServer::get_singleton();
```
Comment (kitbdev) [inline scene/gui/text_edit.cpp]: Why have this part way through the drawing?

File: scene/gui/text_edit.cpp [hunk 14]
```diff
@@ -1577,8 +1565,8 @@ void TextEdit::_notification(int p_what) {
 								} else if (rect.position.x + rect.size.x > xmargin_end) {
 									rect.size.x = xmargin_end - rect.position.x;
 								}
-								RS::get_singleton()->canvas_item_add_rect(ci, rect, theme_cache.search_result_color);
-								draw_rect(rect, theme_cache.search_result_border_color, false);
+								rs->canvas_item_add_rect(text_ci, rect, theme_cache.search_result_color);
+								rs->canvas_item_add_rect(text_ci, rect, theme_cache.search_result_border_color);
```
Comment (kitbdev) [inline scene/gui/text_edit.cpp]: This isn't correct, the rect needs to not be filled in. There isn't an add rect without fill on the RS though, so it may need to be something like:

```suggestion
rs->canvas_item_add_polyline(text_ci, {rect.position, rect.position + Vector2(rect.size.x, 0), rect.position + rect.size, rect.position + Vector2(0, rect.size.y), rect.position, }, {theme_cache.search_result_border_color});
```
Or there would need to be changes to RenderingServer, but that would be out of scope.

File: scene/gui/text_edit.cpp [hunk 15]
```diff
@@ -1821,18 +1809,18 @@ void TextEdit::_notification(int p_what) {
 													ts_caret.t_caret.position.y = -TS->shaped_text_get_ascent(rid);
 													ts_caret.t_caret.size.y = h;
 												}
-												ts_caret.t_caret.position += Vector2(char_margin + ofs_x, ofs_y);
-												draw_rect(ts_caret.t_caret, theme_cache.caret_color, overtype_mode);
+												ts_caret.t_caret.position += Vector2(char_margin, ofs_y);
+												rs->canvas_item_add_rect(text_ci, ts_caret.t_caret, theme_cache.caret_color, overtype_mode);
```
Comment (kitbdev) [inline scene/gui/text_edit.cpp]: Same as above, `overtype_mode` determines fill and not antialiasing.
and same with the next `draw_rect`.

See the EditorSetting `text_editor/appearance/caret/type` for block caret mode.

File: scene/gui/text_edit.cpp (hunk 10 above)
Comment (kitbdev) [reply scene/gui/text_edit.cpp]: - This sounds kind of like https://github.com/godotengine/godot/issues/79735 but offset the other way.

File: scene/gui/code_edit.cpp (hunk 11 above)
Comment (WhalesState) [reply scene/gui/code_edit.cpp]: The cached variable `rtl` was only used once in that code. will use `RS::get_singleton()` for this without caching both of them.

File: scene/gui/text_edit.cpp (hunk 13 above)
Comment (WhalesState) [reply scene/gui/text_edit.cpp:1322]: yes, all the drawing calls are long lines and this helps shortens them, it's used the same way across the engine.

File: scene/gui/code_edit.cpp (hunk 11 above)
Comment (WhalesState) [reply scene/gui/code_edit.cpp]: Removed all the cached variables for `RenderingServer`.

File: scene/gui/text_edit.cpp (hunk 13 above)
Comment (WhalesState) [reply scene/gui/text_edit.cpp]: I removed it, using `RS::get_singleton()` directly now for the changed lines only to avoid having unrelated changes.

File: scene/gui/text_edit.cpp (hunk 14 above)
Comment (WhalesState) [reply scene/gui/text_edit.cpp]: Added a helper method for `TextEdit` since it was used in 3 different places and two of them needed an if statement.
```C++
	// FIXME: Helper method to draw unfilled rects, should be moved to RenderingServer.
	void _draw_rect_unfilled(RID p_canvas_item, const Rect2 &p_rect, const Color &p_color, real_t p_width = -1.0, bool p_antialiased = false) const;

```

**Comment by WhalesState** [comment]
> This sounds kind of like https://github.com/godotengine/godot/issues/79735 but offset the other way.

The half line spacing we add to offset the text should be removed or double checked if it's taken into account in all other calculations like `_get_visible_lines_offset` and `get_visible_line_count`.

File: scene/gui/code_edit.cpp (hunk 11 above)
Comment (kitbdev) [reply scene/gui/code_edit.cpp]: It is used in a loop here.

File: editor/script/script_text_editor.cpp (hunk 12 above)
Comment (kitbdev) [reply editor/script/script_text_editor.cpp]: It looks like this one still needs to be addressed.

**Comment by WhalesState** [comment]
Moved the styles fix to another PR https://github.com/godotengine/godot/pull/110527, will keep this PR fixing only the clipping issues.

**Comment by kitbdev** [comment]
>  The half line spacing we add to offset the text should be removed or double checked if it's taken into account in all other calculations like _get_visible_lines_offset and get_visible_line_count.

I think it will have to be considered there. I've been looking for some inconsistency with related calculations, so thanks for pointing that out. This can be done later though, the behavior in https://github.com/godotengine/godot/pull/110527  get_line_column_at_pos is good for now. It can be more easily seen with the cross cursor.

**Review by kitbdev — APPROVED** [review]
Looks good.

- This also fixes https://github.com/godotengine/godot/issues/74445 since the expand margins now work by default .
- I don't think this fixes https://github.com/godotengine/godot/issues/42342 I think it is talking about how the text doesn't get clipped accurately when there is a content margin on a per pixel bases, though it is hard to tell.

Note that TextEdit's clip_contents default value changed, but this is needed to fix the issues.

**Comment by Repiteo** [comment]
Thanks!
