### PR TITLE
Fix errors while deselecting all tree items; issue #65185

### LINKED ISSUE #65185: Shift-selecting multiple resources in FileSystem dock top-to-bottom and deselecting causes index out of bounds errors
### Godot version

3.3.stable - 4.0.alpha15

### System information

Windows 10

### Issue description

When selecting multiple items in the FileSystem dock top-to-bottom, the output will throw `p_column = -1 is out of bounds` errors and only the topmost selected item will actually be deselected. This issue appears to occur in versions all the way back to Godot 3.3! Selecting bottom-to-top does not result in any odd behavior.

https://user-images.githubusercontent.com/18225391/187875817-12809547-17ea-479a-89fa-eb4089dc09f5.mp4

### Steps to reproduce

- Open (or create) a project with a few resources available in the FileSystem dock
- Hold Shift and select more than one item in the tree view, going in a top-to-bottom direction
- Deselect your current selection by clicking on empty space in the tree view

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by marzecdawid**
Fixes #65185

The problem is `item->deselect(selected_col);` where it uses the column id from the selected cell by cursor so not the column from the cell we actually want to deselect. With this fix it correctly iterates through each column to deselect each cell.

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -4191,12 +4191,9 @@ void Tree::item_selected(int p_column, TreeItem *p_item) {
...
 void Tree::item_deselected(int p_column, TreeItem *p_item) {
-	if (selected_item == p_item) {
+	if (selected_item == p_item && selected_col == p_column) {
 		selected_item = nullptr;
-
-		if (selected_col == p_column) {
-			selected_col = -1;
-		}
+		selected_col = -1;
 	}
```
Comment (anvilfolk) [inline scene/gui/tree.cpp:4197]: Everything else looks good, and I've tested it and it seems to fix the issue.

This is the only thing that worries me a little, despite it making more sense to me this way. However, it changes how the method works, and I'm not certain there aren't other parts of the code that rely on it working this way.

Is there any situation where we want `Tree::selected_item` to be null, but `Tree::selected_col` to be not null? I can't really think of one, so your change makes sense to me. @KoBeWi was the last person to look at this code - any insights?

Comment (anvilfolk) [reply scene/gui/tree.cpp:4197]: I also couldn't find a dialog that made use of `Tree::SELECT_SINGLE`, where individual cells of a `TreeItem` might be selected. That would help us test whether selecting/deselecting individual cells causes undesired behavior.

**Comment by anvilfolk** [comment]
Also, in order to link the issue you're fixing, you have to type "fixes #65185" or alternatives you can see [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue). :)

File: scene/gui/tree.cpp (hunk 1 above)
Comment (marzecdawid) [reply scene/gui/tree.cpp:4197]: I should have created a separate PR for this change. While fixing, I noticed this minor problem, so I also corrected it as it also applies to deselecting elements. In the case of a tree with several columns, if we had a selected cell with several columns, then before this change, deselecting a different cell than the one the cursor is pointing to would also unselect the cursor in the same row, which should not happen the same way as it is with selecting other fields than the cursor is pointing to.
I just tested it by changing the Select type for filesystem_dock and everything works correctly, but it has only one column. When I wanted to test it by creating Tree node with 2 columns in the editor I noticed that the function deselect_all() is not available in GDScript, which I think could also be added.

Should I leave this PR as is or separate them? I just started to contribute so I'm still learning the process of it. In future I will try to separate each change.

**Comment by marzecdawid** [comment]
> Also, in order to link the issue you're fixing, you have to type "fixes https://github.com/godotengine/godot/issues/65185" or alternatives you can see [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue). :)

Thank you, corrected it here and in other PRs.

File: scene/gui/tree.cpp (hunk 1 above)
Comment (marzecdawid) [reply scene/gui/tree.cpp:4197]: For `Tree::SELECT_SINGLE` this change should not matter at all as the cursor is always the same as the selected cell so unselecting it will always clear both `Tree::selected_item` and `Tree::selected_col` before and after the change.

Comment (anvilfolk) [reply scene/gui/tree.cpp:4197]: Yes, I'm having the same issue trying to find a tree with multiple columns to test this out with. I looked through the source code but I think there's only one or two examples of that in the codebase, but with the time I had couldn't really find them & test.

I think it's worth testing multi-column trees. Exposing a few more methods to GDScript doesn't sound like a bad idea to me. I'll let someone else decide whether that ought to go in a new PR, but you can always temporarily do that to test.

From the time I spent looking at this, Tree just seems to be in need of a nice review, documentation & refactor :) Lots of code commended away without explanation.

Comment (marzecdawid) [reply scene/gui/tree.cpp:4197]: Simple deselecting by mouse looks ok.
Before:
(You can see the problem; deselecting column 1 will remove cursor from column 0)

https://user-images.githubusercontent.com/23726629/201540070-cd1ea3a0-1bf9-48da-b261-65be7bb1973d.mp4

After:

https://user-images.githubusercontent.com/23726629/201539864-bcf3732d-3df4-4c34-bc26-4c697233be00.mp4

Comment (anvilfolk) [reply scene/gui/tree.cpp:4197]: Wonderful! I'd be happy to see this in :)

**Comment by marzecdawid** [comment]
I changed the commit to only include the fix for #65185
For other changes I will create a new PR as I found more problems with cursor for both selecting and deselecting.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.2.
