### PR TITLE
Chunk tilemap physics

### LINKED ISSUE #84163: Big TileMap with collisions is extremely slow
### Godot version

4.2 beta3

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

I noticed this issue before, but I just encountered a super extreme case and decided to report it.

I'm doing 8x `test_move()` and the framerate is unbearably choppy.

https://github.com/godotengine/godot/assets/2223172/f6b6eb9d-03fb-4a73-abd5-07c8e1a9fb58

The profiler reports ~300ms of physics time, caused by integrate forces.

If I remove collisions of center tiles, the frame drop is completely gone.

https://github.com/godotengine/godot/assets/2223172/bae6f498-8e16-4983-81ed-535390c9a5ac

This workaround has many problems however, so I can't use it in the final product.

The problem is most likely that each tile is a separate collision shape. What's weird, I can get good FPS with collisions on the same scene, it seems to depend on the physics check position.

### Steps to reproduce

1. Create a TileMap with hundreds of tiles
2. Do simple raycast in a wrong spot

### Minimal reproduction project

It's difficult to make a minimal project.

### LINKED ISSUE #89458: Physics bodies can collide with tile seams
### Tested versions

4.3 dev4 and earlier

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

There is an issue with TileMap where a body can sometimes detect a wall collision on a completely flat surface. This causes bugs like projectile bouncing backwards instead of being reflected or characters turning at random point as if they hit something. Unfortunately the bug is very random - it depends on body shape, position and movement velocity. Sometimes I can reproduce it reliably in one very specific spot, but some time later it can fix itself and happen elsewhere.

Since it's so random, I didn't report it until now, because I though the issue is fixed multiple times. Apparently it's not and I just have another of these "reliable" cases.

Bug in action. Notice how the orange enemy turns for no reason, while the other enemy (which has a different shape) walks normally:

https://github.com/godotengine/godot/assets/2223172/edea97f4-b459-41f1-a118-baf0804ce943

Here I replaced the TileMap with a flat StaticBody2D and moved the TileMap below:

https://github.com/godotengine/godot/assets/2223172/a82c8e8a-7149-416a-a76b-d264132fe569

I suspect that it's caused by the fact that the TileMap is composed of multiple collision shapes and due to some physics glitches it's possible to hit corner of a tile. Related to #84163 and I assume solution would be merging the tiles into polygons (AFAIK navigation already does that).

### Steps to reproduce

1. Use TileMap
2. It might happen

### Minimal reproduction project (MRP)

The bug is too random to create a reliable MRP.

### PR DESCRIPTION
**Pull request by groud**
Right now, TileMapLayer physics is implemented using one collision body for each cell, which is likely lowering runtime performance (to be verified, but I doubt having thousands of colliders on a map has no impact). This PR reworks the TileMapLayer physics so that cells shapes get merged into bigger collision shapes, whenever possible. A`physics_quadrant_size` param allow changing the size of each collision chunk.

This video illustrate the processing done:

https://github.com/user-attachments/assets/ce32292c-f8f5-47d5-8fe2-506f3f097932

Note this PR breaks compatibility for `get_coords_for_body_rid`, as with the PR, a single body can cover multiple cells.

*Bugsquad edit:* Fixes #84163 Fixes #89458

### CODE REVIEW

**Comment by groud** [comment]
> (this is essentially the physics counterpart of the existing TileMap navmesh baking).

More or less though. This PR makes the baking as built-in to the TileMaplayer itself, while navmesh baking is made on the navigation region side (like, you to define a region and bake it).

**Comment by KoBeWi** [comment]
I could confirm it fixes performance issues (#84163). Could not confirm fixing seams (#89458) because it's too unreliable, but it's safe to assume it's fixed too.

**Comment by KoBeWi** [comment]
From further testing:
- It would be nice to have a way to visualize chunks. If the chunk size is too small, it could still cause seams and visualization would make it easier to pick a better size. Although seems like there is no size limit, so you can just make it super big to cover whole map.
- The chunks are regenerated every time you modify tiles. While it's expected, it causes problems in the editor, because too big chunks make editing super slow. Is there no way to avoid re-creating shapes in the editor? Maybe only do that when they are visible? Though it's easily solvable with a script that makes chunks bigger at runtime, so not much a problem.

**Comment by groud** [comment]
> It would be nice to have a way to visualize chunks. If the chunk size is too small, it could still cause seams and visualization would make it easier to pick a better size. Although seems like there is no size limit, so you can just make it super big to cover whole map.

Ah well, the colors are a bit randomized (to distinguish shapes a bit), but it is done per-chunk. So well, the first shape always use the same color so you cannot distinguish chunks. I guess making the seams visible should be doable, I'll give it a try.

> The chunks are regenerated every time you modify tiles. While it's expected, it causes problems in the editor, because too big chunks make editing super slow. Is there no way to avoid re-creating shapes in the editor? Maybe only do that when they are visible? Though it's easily solvable with a script that makes chunks bigger at runtime, so not much a problem.

Hmm, I don't think it would be easily solvable. Modifying the TileSet kind of has to re-generate the whole TileMap. I guess it could be optimized but that's sadly a toooon of work. So for now I don't really see a good solution for the problem.

**Comment by KoBeWi** [comment]
> Modifying the TileSet kind of has to re-generate the whole TileMap.

I meant modifying the TileMap itself. When you paint or erase tiles, it seems to re-create physics chunks for no reason.

**Comment by groud** [comment]
>  I meant modifying the TileMap itself. When you paint or erase tiles, it seems to re-create physics chunks for no reason.

Oh ok. Well yeah, it updates chunk by chunk, like for rendering. So indeed changing a tile in a given chunk re-renders the whole chunk. Not sure it could be optimized more though.

Maybe I could limit the chunk size in the editor, but It might hurt debugging I guess.

In any case, the polygon merging can maybe be optimized a bit, I need to check.

**Comment by djrain** [comment]
This would be great to have for light occluders also. I can say that merging tiles _greatly_ reduced the impact of shadows in our game in 4.3. Clay has made some shadow performance improvements in 4.4 that I've yet to test, but I'm guessing the chunking will still help.

**Comment by groud** [comment]
> This would be great to have for light occluders also. I can say that merging tiles greatly reduced the impact of shadows in our game in 4.3. Clay has made some shadow performance improvements in 4.4 that I've yet to test, but I'm guessing the chunking will still help.

That's a good point. It should be doable.

**Comment by smix8** [comment]
It is definitely an improvement over the status quo but no full fix to physics ghost collision.

> Could not confirm fixing seams (https://github.com/godotengine/godot/issues/89458) because it's too unreliable, but it's safe to assume it's fixed too.

This technically can not fix physics seam issues as when you bake it to chunks you still have chunk seams. For physics to really remove all those internal edge ghost collision issues it would need to merge all cells together that create a combined shape  instead of slicing them to chunk size.

>  I don't think we can keep the debug lines, as it has a performance impact.

Change from rendering the debug with the very inefficient canvas item polygline function to bake a chunk mesh to render.

**Comment by groud** [comment]
> Change from rendering the debug with the very inefficient canvas item polyline function to bake a chunk mesh to render, it is dirt cheap in comparison.

Hmm, interesting idea. IIRC, I had issues with 2D meshes back in the days, but maybe it got better? I'll try it out.

**Comment by smix8** [comment]
Maybe there were issues but by now the 2d navmesh, csg and other places with a lot of edge debug use it already with no reported issues so I think it should not be a problem for TileMap to adopt it as well to improve performance.

**Comment by KoBeWi** [comment]
> This technically can not fix physics seam issues as when you bake it to chunks you still have chunk seams.

You can set chunk size to cover the whole TileMap. I checked my biggest one, chunk size 512 and works without problems. It does not impact loading time, but modifying the tiles is slower (luckily I don't need to do it).

**Comment by smix8** [comment]
> You can set chunk size to cover the whole TileMap.

Ok I did not thought about that option, just assumed there would be a limit of quadrant size of sorts, yeah that could work.

**Comment by groud** [comment]
I'm thinking about something. Maybe I could try implementing some sort of an automatic "edge smoothing" ? 
edgesmoothing

Like, a 45° on the edge of each chunk's polygon might help avoiding characters being stuck when sliding? I guess we gotta try by making this change in tile first maybe. By like, adding a 1px "chamfer" and if there still are issues.

**Comment by Calinou** [comment]
> I'm thinking about something. Maybe I could try implementing some sort of an automatic "edge smoothing" ?

I think this is better solved at a character controller level by implementing *skimming*, so that you don't need to make the collision shapes more complex.

At a core level, skimming refers to preserving the character's velocity when hitting something for a short amount of time. This means that you will keep sliding until you no longer hit the surface, and as soon as you are no longer colliding, you will keep the velocity you've had before hitting the surface.

**Review by Calinou — COMMENTED** [review]
Tested locally, it works as expected.

**Testing project:** [test_tilemap_large.zip](https://github.com/user-attachments/files/18738578/test_tilemap_large.zip)

### Physics seams issues

*Holding left arrow in the testing project's main scene.*

### Before

https://github.com/user-attachments/assets/8ac8688c-1f3d-41a5-a8bf-8578610eb2f4

### After

*Physics seams issues still occur occasionally, but are much rarer and less severe.*

https://github.com/user-attachments/assets/69dff3a4-3957-463e-a61b-fe4c1a0bb547

### After (physics quadrant size set to `2**31 - 1`)

*This fully avoids the issue, but makes editing slower in the editor and may have adverse performance issues in large scenes (due to each object having to check collision against the entire level's shape).*

https://github.com/user-attachments/assets/e8d0f8ca-fae6-4c0d-b423-75c89b6bc0a1

### Performance

<details open>

<summary>PC specifications</summary>

- **CPU:** Intel Core i9-13900K
- **GPU:** NVIDIA GeForce RTX 4090
- **RAM:** 64 GB (2×32 GB DDR5-5800 C30)
- **SSD:** Solidigm P44 Pro 2 TB
- **OS:** Linux (Fedora 41)
</details>

Command line used for testing (we render in a tiny window to avoid GPU bottlenecks[^1]):

[^1]: `--disable-render-loop` breaks `--print-fps` reporting, so we can't use it to test physics performance.

```
godot --path /path/to/project lots_of_tiles.tscn --resolution 64x64 --print-fps
```

1000 RigidBodies enclosed in a complex TileMap.

### Before

*We encounter a "physics spiral of death" phenomenon, hence the sudden decrease in FPS at some point.*

```
Project FPS: 391 (2.55 mspf)
Project FPS: 577 (1.73 mspf)
Project FPS: 11 (90.90 mspf)
Project FPS: 8 (125.00 mspf)
Project FPS: 60 (16.66 mspf)
Project FPS: 9 (111.11 mspf)
Project FPS: 20 (50.00 mspf)
Project FPS: 590 (1.69 mspf)
Project FPS: 328 (3.04 mspf)
Project FPS: 399 (2.50 mspf)
Project FPS: 442 (2.26 mspf)
```

### After

*No more physics spiral of death, and overall performance is greatly improved.*

```
Project FPS: 837 (1.19 mspf)
Project FPS: 488 (2.04 mspf)
Project FPS: 698 (1.43 mspf)
Project FPS: 876 (1.14 mspf)
Project FPS: 900 (1.11 mspf)
Project FPS: 872 (1.14 mspf)
Project FPS: 880 (1.13 mspf)
Project FPS: 649 (1.54 mspf)
```

### Feedback

- The property should be documented in the class reference, and it should have a property hint added to set a suitable range. I'd suggest something like `1,1024,1` as sizes above 1024 will likely run into the aforementioned performance issue, on top of being very slow for editing.
- We could sidestep the editing performance problem at large quadrant sizes by clamping the size of the physics quadrant while in the editor to a value like 16 or 32.

**Comment by KoBeWi** [comment]
> it should have a property hint added to set a suitable range. I'd suggest something like 1,1024,1 as sizes above 1024 will likely run into the aforementioned performance issue

That depends. The chunk size is square, while the TileMap can be wide. My widest level is 128x1664, which is much smaller than 1024x1024, but with size limit it couldn't be covered by single chunk. Though with `or_greater` it would be fine.

**Comment by smix8** [comment]
Could just do as the navmesh baking does. The navmesh editing has a timer that triggers and sets the time on any editing. So pnly when the user stops editing the time fires and the navmesh gets rebaked.

File: scene/2d/tile_map_layer.h [hunk 1]
```diff
@@ -220,6 +220,88 @@ class RenderingQuadrant : public RefCounted {
 	}
 };
 
+class PhysicsQuadrant : public RefCounted {
+	GDCLASS(PhysicsQuadrant, RefCounted);
+
+public:
+	struct PhysicsBodyKey {
+		int physics_layer;
```
Comment (KoBeWi) [inline scene/2d/tile_map_layer.h:228]:
```suggestion
		int physics_layer = 0;
```
Technically these should all be initialized.

File: scene/2d/tile_map_layer.h [hunk 2]
```diff
@@ -220,6 +220,88 @@ class RenderingQuadrant : public RefCounted {
...
+					}
+					return angular_velocity < p_other.angular_velocity;
+				}
+				return linear_velocity < p_other.linear_velocity;
+			}
+			return physics_layer < p_other.physics_layer;
+		}
+
+		bool operator!=(const PhysicsBodyKey &p_other) const {
+			return !this->operator!=(p_other);
```
Comment (KoBeWi) [inline scene/2d/tile_map_layer.h:251]:
```suggestion
			return !this->operator==(p_other);
```

File: scene/2d/tile_map_layer.cpp [hunk 3]
```diff
@@ -929,23 +1033,58 @@ void TileMapLayer::_physics_draw_cell_debug(const RID &p_canvas_item, const Vect
...
+
+	// Redraw all shapes from the physics quadrants
+	Rect2i covered_cell_area = Rect2i(r_debug_quadrant.quadrant_coords * TILE_MAP_DEBUG_QUADRANT_SIZE, Vector2i(TILE_MAP_DEBUG_QUADRANT_SIZE, TILE_MAP_DEBUG_QUADRANT_SIZE));
+	Vector2i first_physics_quadrant_coords = _coords_to_quadrant_coords(covered_cell_area.get_position() - Vector2i(1, 1), physics_quadrant_size) + Vector2i(1, 1);
+	Vector2i last_physics_quadrant_coords = _coords_to_quadrant_coords(covered_cell_area.get_end() - Vector2i(1, 1), physics_quadrant_size) + Vector2i(1, 1);
+
+	for (int x = first_physics_quadrant_coords.x; x < last_physics_quadrant_coords.x; x++) {
+		for (int y = first_physics_quadrant_coords.y; y < last_physics_quadrant_coords.y; y++) {
+			const Vector2i physics_quadrant_coords = Vector2i(x, y);
+			if (physics_quadrant_map.has(physics_quadrant_coords)) {
```
Comment (KoBeWi) [inline scene/2d/tile_map_layer.cpp:1046]: Can be early return.
```suggestion
			if (!physics_quadrant_map.has(physics_quadrant_coords)) {
				continue;
			}
```

File: scene/2d/tile_map_layer.cpp [hunk 4]
```diff
@@ -929,23 +1033,58 @@ void TileMapLayer::_physics_draw_cell_debug(const RID &p_canvas_item, const Vect
...
+				int body_index = 0;
+				for (const KeyValue<PhysicsQuadrant::PhysicsBodyKey, PhysicsQuadrant::PhysicsBodyValue> &kvbody : physics_quadrant->bodies) {
+					const RID &body = kvbody.value.body;
+					Transform2D body_to_quadrant = global_to_debug_quadrant * Transform2D(ps->body_get_state(body, PhysicsServer2D::BODY_STATE_TRANSFORM));
+
+					Color random_variation_color = debug_collision_color;
+					random_variation_color.set_hsv(
+							color.write[0].get_h() + rand.random(-1.0, 1.0) * 0.05,
+							color.write[0].get_s(),
+							color.write[0].get_v() + rand.random(-1.0, 1.0) * 0.1,
```
Comment (KoBeWi) [inline scene/2d/tile_map_layer.cpp:1062]:
```suggestion
							color[0].get_h() + rand.random(-1.0, 1.0) * 0.05,
							color[0].get_s(),
							color[0].get_v() + rand.random(-1.0, 1.0) * 0.1,
```

**Comment by KoBeWi** [comment]
> Ah well, the colors are a bit randomized (to distinguish shapes a bit), but it is done per-chunk. So well, the first shape always use the same color so you cannot distinguish chunks.

From what I see, you randomize colors once per chunk, so each chunk should have unique color. But:
- `rand.random` returns the same value for whatever reason.
- The color stays unchanged anyway, even if randomizing the same number should change it (because you are adding to previous color).
- You are using (-1, 1) range for color randomization, which can eventually go out of bounds. Not sure if `set_hsv()` can handle it.

This is what I got by changing `rand.random()` to `Matf::randf()` (and tweaking some values):
image
You could distinguish both chunks and shapes by randomizing hue for chunks and value for shapes.

File: scene/2d/tile_map_layer.cpp [hunk 5]
```diff
@@ -3008,6 +3150,22 @@ TileMapLayer::DebugVisibilityMode TileMapLayer::get_collision_visibility_mode()
 	return collision_visibility_mode;
 }
 
+void TileMapLayer::set_physics_quadrant_size(int p_size) {
+	if (physics_quadrant_size == p_size) {
+		return;
+	}
+	ERR_FAIL_COND_MSG(p_size < 1, "Physics quandrant size cannot be smaller than 1.");
```
Comment (KoBeWi) [inline scene/2d/tile_map_layer.cpp:3157]: Usually I've seen error checks before guards, but not sure if it's consistent.

**Comment by KoBeWi** [comment]
> Note this PR breaks compatibility for get_coords_for_body_rid, as with the PR, a single body can cover multiple cells.

This can be worked around with (
```GDScript
var pos := tile_map_layer.to_local(col.get_position())
var coords := tile_map_layer.local_to_map(pos)
```
but I just remembered that it wasn't very reliable. The position would some times report outside any tile. (I didn't test if it's still the case)

**Comment by groud** [comment]
> rand.random returns the same value for whatever reason.

Yeah. Because `rand` is initialialized every time, and with the same seed, within  `_physics_draw_quadrant_debug` (ran for each quadrant). 
I'll generate the seed from the quadrant coords, that should be enough.

> The color stays unchanged anyway, even if randomizing the same number should change it (because you are adding to previous color).

I'm not sure, it worked for me within a quadrant.

> You are using (-1, 1) range for color randomization, which can eventually go out of bounds. Not sure if set_hsv() can handle it.

Well, the returned value is multiplied by `0.05` or `0.1`, so well, it's not that wide of a range. The `hue` parameter goes through `fmod` so it should be fine. There's only the `value` one that might go below 0 but I'm not sure if that's possible.

> This is what I got by changing rand.random() to Matf::randf() (and tweaking some values):

I don't want something that spread, it should stay around the selected debug color.

**Comment by KoBeWi** [comment]
> rand is initialialized every time, and with the same seed, within _physics_draw_quadrant_debug (ran for each quadrant).

Ok I misunderstood what the method does. Makes sense.

File: scene/2d/tile_map_layer.h (hunk 2 above)
Comment (KoBeWi) [reply scene/2d/tile_map_layer.h:251]: But the method is a operator, it can't call itself.

**Comment by KoBeWi** [comment]
You need to run doctool.

**Comment by groud** [comment]
Alright, thanks. It should be ready now. Hope I didn't mess anything else :sweat_smile:

**Comment by KoBeWi** [comment]
Some generated shapes don't look optimal 🤔
image
The slope could be a single triangle, but it got heavily segmented (assuming the outlines are accurate). Though it's probably limitation of the algorithm. Either case, it has no visible effect on performance.

**Comment by groud** [comment]
I am not super sure. Maybe there are some precision errors too. Is there any visible gap if you zoom in a lot ?

But yeah, the concave to convex algorithm might have some limitations too. Though I would expect it to be smart enough to merge the triangles there. Weird...

**Comment by KoBeWi** [comment]
Ok I guess that's the reason
image

**Review by KoBeWi — APPROVED** [review]
The quadrant preview looks great now.
Editing with big quadrants is still slow, but it's easy to workaround, so whateves. Also I only tested dev build, in optimized build it's probably not noticeable.

**Comment by groud** [comment]
Hmm, if you want to try it out there's a `solution = SimplifyPaths(solution, 0.01);` line in the `geometry_2d.cpp`. You may try to increase the `0.01` to something higher, maybe it can help too. If your shape isn't, like, wrongly configured I mean.

**Comment by KoBeWi** [comment]
Yeah the tile shape was wrong. I made it before grid snap was a thing and it wasn't aligned properly (slopes spanning over 4 tiles are tricky).

**Review by akien-mga — APPROVED** [review]

**Comment by Mickeon** [comment]
I would like to ask a question just as food for thought before we regret it later.

Rotated, one-way platforms are not _technically_ possible to register in the current TileSet workflow. My own project checks a vast area for collision RIDs that correspond to a specific tile. No need to go in the specifics, but if they do correspond, they are rotated from within the physics server.

Does this PR affect this kind of routine? And how to work around it?

File: doc/classes/TileMapLayer.xml [hunk 6]
```diff
@@ -310,8 +310,13 @@
 		<member name="occlusion_enabled" type="bool" setter="set_occlusion_enabled" getter="is_occlusion_enabled" default="true">
 			Enable or disable light occlusion.
 		</member>
+		<member name="physics_quadrant_size" type="int" setter="set_physics_quadrant_size" getter="get_physics_quadrant_size" default="16">
+			The [TileMapLayer]'s physics quadrant size. Within a physics quadrant, cells with similar physics properties are grouped together and their collision shapes get merged. [member physics_quadrant_size] defines the length of a square's side, in the map's coordinate system, that forms the quadrant. Thus, the default quadrant size groups together [code]16 * 16 = 256[/code] tiles.
+			[b]Note:[/b] As quadrants are created according to the map's coordinate system, the quadrant's "square shape" might not look like square in the [TileMapLayer]'s local coordinate system.
```
Comment (Mickeon) [inline doc/classes/TileMapLayer.xml:315]:
```suggestion
			[b]Note:[/b] As quadrants are created according to the map's coordinate system, the quadrants may not look like squares in the [TileMapLayer]'s local coordinate system, depending on the [member tile_set]'s [member TileSet.tile_shape].
```
Maybe it's too verbose?

**Review by Mickeon — COMMENTED** [review]
Unsure if "_quadrant_" has ever been the most accurate word to describe this. Even in geometry it's not accurate, but, oh well. That's been their name.

**Comment by KeyboardDanni** [comment]
> I would like to ask a question just as food for thought before we regret it later.
> 
> Rotated, one-way platforms are not _technically_ possible to register in the current TileSet workflow. My own project checks a vast area for collision RIDs that correspond to a specific tile. No need to go in the specifics, but if they do correspond, they are rotated from within the physics server.
> 
> Does this PR affect this kind of routine? And how to work around it?

This would affect the collision RIDs from my understanding, since this is basically just creating merged shapes out of each chunk. As a workaround you could set the quadrant size to 1. But if you still wanted the benefits of this PR, you could have a separate TileMapLayer with just the one-ways. Not an elegant solution but it'd work.

**Comment by Mickeon** [comment]
> This would affect the collision RIDs from my understanding, since this is basically just creating merged shapes out of each chunk. As a workaround you could set the quadrant size to 1. But if you still wanted the benefits of this PR, you could have a separate TileMapLayer with just the one-ways. Not an elegant solution but it'd work.

Okay. It's among the things worth sharing around and documenting when this gets merged, so let's take note.

**Comment by Repiteo** [comment]
Thanks!

**Comment by KoBeWi** [comment]
You can set quadrant size to 1 and it should behave as before (including the performance). Bigger quadrants will result in slower updating, so you might want to disable them anyway.

AFAIK there is no reliable way to get a tile from a position (see #35344). For some use-cases, where you don't need precise coordinates (like for detecting floor type), you can use a couple of raycasts to get tile data and approximate the result.

**Comment by dginovker** [comment]
WOW this PR is amazing. You still get the collision issues on corners of tilemaps but building Godot from source to get this change has saved my project!

**Comment by h0lley** [comment]
unfortunately this broke my enemy behavior.

my enemies have an Area2D with the `body_shape_entered` signal hooked up. if body_shape_entered passes a TileMapLayer, I need to know the position of the specific tile that clipped into the Area2D so that an avoidance vector can be updated accordingly.

this was previously possible by using `PhysicsServer2D.body_get_direct_state(body_rid).transform.origin`. now that presumably the physics bodies have been consolidated into one I am no longer getting a tile position from this.

**Comment by KeyboardDanni** [comment]
As discussed previously, you can get the old behavior back by setting the chunk size to 1. Unless you're saying that this is broken too...?

**Comment by h0lley** [comment]
> As discussed previously, you can get the old behavior back by setting the chunk size to 1. Unless you're saying that this is broken too...?

yes, that did the trick! thank you and apologies for not combing through the entire thread.
