### PR TITLE
Fix wrong order in autocompletion sorting with empty string to complete.

### LINKED ISSUE #78296: Script Editor auto completions sorting is broken
### Godot version

c0d8d91

### System information

Windows 11

### Issue description

There's weird bug going on with the latest master branch. The auto completion in script editor is sorted in a wacky ways, putting sort of constants ahead of anything because it's ahead alphabetically
image

Now compare it to my build about two weeks ago
image

Both are using the same content of 'editor_data' settings folder. And loading up the same project.

### Steps to reproduce

- Open a new blank project
- Make a new script
- Triggers any auto completion in Script Editor

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by ajreckof**
Fixes #78296
The problem is not really that it is sorted alphabetically but more that it isn't. It was sorting upper-case letters before lower-case ones which meant all constants would go at the top. 
This what now is shown for similar setup as the issue 
Capture d’écran 2023-06-16 à 11 24 19
I'm wondering about the `Import path` maybe I should remove underscores before sorting alphabetically, or at least the first one as with it they will always appear first (for empty string to complete).

Edit : There was also a bug about location created because of bad initialisation which resulted in option being ranked only by alphabetical order instead of first by location. Here is what it now shows : 
Capture d’écran 2023-06-16 à 14 05 18

### CODE REVIEW

File: scene/gui/code_edit.cpp [hunk 1]
```diff
@@ -3344,5 +3342,5 @@ bool CodeCompletionOptionCompare::operator()(const ScriptLanguage::CodeCompletio
 			return l.matches[i].second > r.matches[i].second;
 		}
 	}
-	return l.display < r.display;
+	return l.display.to_lower() < r.display.to_lower();
```
Comment (AThousandShips) [inline scene/gui/code_edit.cpp:3345]:
```suggestion
	return l.display.naturalnocasecmp_to(r.display) < 0;
```
Or better yet, to follow the way documentation works:
```suggestion
	return l.display.naturalcasecmp_to(r.display) < 0;
```

Comment (AThousandShips) [inline scene/gui/code_edit.cpp:3345]: Might be useful to use the existing function:
```suggestion
	return l.display.nocasecmp(r.display) < 0;
```

Comment (ajreckof) [reply scene/gui/code_edit.cpp:3345]: wow didn't know this existed was exactly what I was looking for ^__^ Thanks

**Comment by akien-mga** [comment]
> The problem is not really that it is sorted alphabetically but more that it isn't. It was sorting upper-case letters before lower-case ones which meant all constants would go at the top.

Well that's arguable, sorting upper case letters before lower case letters is fairly common. But if we want to go all the way this should maybe use `NaturalNoCaseComparator`.

Sorting like this is maybe a slight improvement over listing constants first, but still a regression compared to 4.0 IMO. I think what it used to do is give higher priority to members which are defined directly in the current class (script variables and methods, and for the C++ class itself, ordered in order of inheritance: Sprite2D methods first, then Node2D, then Node, etc.
With the idea that the more local methods are the ones you'll need to be reminded of when using a specialized node.

That might be out of scope for this issue of course.

**Comment by AThousandShips** [comment]
Using `naturalnocasecmp_to` would make it closer to documentation, but I think that a more comprehensive rework of the way results are sorted would be best, and I think just `nocasecmp_to` is enough for now

File: scene/gui/code_edit.cpp (hunk 1 above)
Comment (AThousandShips) [reply scene/gui/code_edit.cpp]: My bad for my incorrect function

**Comment by ajreckof** [comment]
> > The problem is not really that it is sorted alphabetically but more that it isn't. It was sorting upper-case letters before lower-case ones which meant all constants would go at the top.
> 
> Well that's arguable, sorting upper case letters before lower case letters is fairly common. But if we want to go all the way this should maybe use `NaturalNoCaseComparator`. _Edit:_ That's what @AThousandShips suggested.
> 
> Sorting like this is maybe a slight improvement over listing constants first, but still a regression compared to 4.0 IMO. I think what it used to do is give higher priority to members which are defined directly in the current class (script variables and methods, and for the C++ class itself, ordered in order of inheritance: Sprite2D methods first, then Node2D, then Node, etc. With the idea that the more local methods are the ones you'll need to be reminded of when using a specialized node.
> 
> That might be out of scope for this issue of course.

This should still be the case. Didn't think of it and thought that it was all Sprite2D variables :( shwoing first but this is clearly not the case.


> Using `naturalnocasecmp_to` would make it closer to documentation, but I think that a more comprehensive rework of the way results are sorted would be best, and I think just `nocasecmp_to` is enough for now

I was wondering about this but didn't know what was the difference between the two. I'll use the natural version one.

okay so from your commentaries I realised there was another bug hidden behind the case bug which was in certain cases for empty string location was ignored. I'm fixing it right now.

**Comment by akien-mga** [comment]
> > Using `naturalnocasecmp_to` would make it closer to documentation, but I think that a more comprehensive rework of the way results are sorted would be best, and I think just `nocasecmp_to` is enough for now
> 
> I was wondering about this but didn't know what was the difference between the two. I'll use the natural version one.

Yes you should use `naturalnocasecmp_to` - the difference is the handling of numbers. Natural order: 1, 2, 10. Otherwise: 1, 10, 2.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
