### PR TITLE
Use versioned URL for "Online Documentation" buttons in the editor

### LINKED ISSUE #58245: Godot 4: Online Docs option in script editor leads to stable documentation (3.x) instead of latest (4.0)
### Godot version

v4.0-alpha2

### System information

Windows 10 64-bit, GPU: NVIDIA Geforce GTX 1650 Ti, CPU: AMD Ryzen 7 4800H

### Issue description

The "Online Docs" option in the Godot 4 script editor leads you to the [Godot stable docs](https://docs.godotengine.org/en/stable/) (3.x) instead of the [Godot latest docs](https://docs.godotengine.org/en/latest/) (4.0). This is just a minor inconvenience but still an inconvenience.

Of course this change will need to be reverted once 4.0 becomes stable.

### Steps to reproduce

1. Go to the script editor in Godot 4
2. Click on the "Online Docs" option at the top:
Godot-OnlineDocsThingy
3. Verify the link:
Stable (3.x) Docs: `https://docs.godotengine.org/en/stable/`
Latest (4.0) Docs: `https://docs.godotengine.org/en/latest/` (What its should be)
Wheree you goo: `https://docs.godotengine.org/en/stable/`

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Calinou**
This also avoids a redirect, making the page appear to load faster.

This closes https://github.com/godotengine/godot/issues/58245.

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -2908,7 +2908,7 @@ void EditorNode::_menu_option_confirm(int p_option, bool p_confirmed) {
 			command_palette->open_popup();
 		} break;
 		case HELP_DOCS: {
-			OS::get_singleton()->shell_open("https://docs.godotengine.org/");
+			OS::get_singleton()->shell_open(VERSION_DOCS_URL "/");
```
Comment (akien-mga) [inline editor/editor_node.cpp:2911]: Is that trailing slash actually needed?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.
