### PR TITLE
GDScript: Fix for UNUSED_PRIVATE_CLASS_VARIABLE

### LINKED ISSUE #42318: GDScript: variables that begin with an underscore ("_") do not count as being used, gives UNUSED_PRIVATE_CLASS_VARIABLE warning
**Godot version:**
4.0 master - 72aaf81518253e25f28b3a23b5d3509e1264a5ad

**Issue description:**
If a variable's name starts with an underscore it will not count towards being used (from the tests I've done) and thus produce a warning, UNUSED_PRIVATE_CLASS_VARIABLE, even if it is used.

**Steps to reproduce:**
```
var _test_var: int = 2
var another_var: int = 5

func test() -> void:
	another_var = _test_var
```

### LINKED ISSUE #47888: GDScript editor: Spurious warnings "declared but never used in the script"
**Godot version:**
4.0.dev 6b39980e

**OS/device including version:**
Windows 10

**Issue description:**

I'm seeing warnings of the form
```
[Ignore] Line 52 (UNUSED_PRIVATE_CLASS_VARIABLE): The class variable '_cache_uniq_key' is declared but never used in the script.
```
for private variables and properties I declare which do get used within the same class.

**Steps to reproduce:**
1. Edit the attached project (do not run it)
2. In the script editor, open crashy.gd
3. Check the Warnings panel at the bottom. You will see the above unused variable warnings:
* `_cache_uniq_key` is used by `uniq_key` property getter which is used by `_to_string` which is used by str() on line 101.
* `_type_dictionary` is used directly by the instantiate function

**Minimal reproduction project:**
[ExtendsCrash.zip](https://github.com/godotengine/godot/files/6310726/ExtendsCrash.zip)

### PR DESCRIPTION
**Pull request by ZuBsPaCe**
Fixes following issues in master:

Fixes #47888
Fixes #42318

Usage count of member variables was never increased. This lead to UNUSED_PRIVATE_CLASS_VARIABLE warnings for private variables like "_my_private_var" even if the variable was used.

Test script, which will only report "_private_unused" with this fix:

```gdscript
var _private_used: int = 1
var _private_unused: int = 1

var public_used: int = 1
var public_unused: int = 1

func test() -> void:
	public_used = _private_used
```

### CODE REVIEW

**Comment by ZuBsPaCe** [comment]
Was a bit unsure, if I should use a switch statement on ClassNode::Member instead. Not sure, if handling all cases is necessary, but I don't think so. Decided to use the simple if statement just for ClassNode::Member::VARIABLE.

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -2042,6 +2042,14 @@ GDScriptParser::ExpressionNode *GDScriptParser::parse_identifier(ExpressionNode
...
 				ERR_FAIL_V_MSG(nullptr, "Undefined local found.");
 		}
+	} else if (current_class != nullptr && current_class->has_member(identifier->name)) {
+		const ClassNode::Member &declaration = current_class->get_member(identifier->name);
+
+		if (declaration.type == ClassNode::Member::VARIABLE) {
+			identifier->source = IdentifierNode::MEMBER_VARIABLE;
+			identifier->variable_source = declaration.variable;
+			declaration.variable->usages++;
+		}
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp:2052]: This won't really work in all cases because member variables can be used before they are declared. This check needs to be done in the analyzer.

**Review by vnen — CHANGES_REQUESTED** [review]

File: modules/gdscript/gdscript_parser.cpp (hunk 1 above)
Comment (ZuBsPaCe) [reply modules/gdscript/gdscript_parser.cpp]: You're right, thanks! Did not think about that. Moved the usage increment into the analyzer. Here's a small test case:
```gdscript
var pub

var _priv_forward_used
var _priv_forward_unused

func test1() -> void:
	pub = _priv_forward_used
	pub = _priv_backward_used
	
var _priv_backward_used
var _priv_backward_unused
```
Result:
image

I don't like, that some usages are counted in the parser and this new one in the analyzer...

Comment (vnen) [reply modules/gdscript/gdscript_parser.cpp]: > I don't like, that usages are counted in the parser and this new one in the analyzer, but I don't think that this could be changed easily..

TBH I don't like it either, but for now I guess it's not worth changing.

**Review by vnen — APPROVED** [review]
Looks good to me.

**Comment by vnen** [comment]
@ZuBsPaCe I just noticed that the commit is being attributed to another user. You may want to change the email address in your git settings to one that is tied to your user in GitHub and then run `git commit --amend --no-edit --reset-author` to change the author in the commit and force push to update the PR.

**Comment by ZuBsPaCe** [comment]
@vnen Thanks for pointing this out to me! Completely missed that one. 

Now everything should be correct.

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Built and tested, works and indeed fixed the issue which I could reproduce without this.

Thanks for the fix!
