### PR TITLE
Stereo rendering: Fix omni lights

### LINKED ISSUE #82278: Enabling use_xr breaks OmniLights in gl_compatibility
### Godot version

4.1.2-rc.1

### System information

Windows 11, gl_compatibility, NVidia RTX 3070 TI

### Issue description

The Godot XR Dungeon Demo project has a single OmnlLight3D for the player:
image

When the renderer is switched over to gl_compatibility the OmniLight3D stops working:
image

This was tracked down to `get_viewport().use_xr = true`. When this is performed, the OmniLight3D fails on both the PC and the headset. If it's commented out then the PC renders correctly and no output goes to the headset.

### Steps to reproduce

This can be replicated by:
- Check out https://github.com/Malcolmnixon/godot-xr-dungeon-template
- Open with Godot 4.1.2
- Switch renderer over to gl_compatibility
- To go directly to broken scene:
  - Set game/zones/level1/level1.tscn as main scene
  - Add Godot XR Tools StartXR node
- Run project on PC and observe failure
- Comment out `get_viewport().use_xr = true` in the Godot XR Tools start_xr.gd script
- Run project on PC and observe light working on PC (but no headset output)

### Minimal reproduction project

A smaller demo project can be constructed if needed; however it still requires enough machinery to start an XR instance in the headset, so it wouldn't be "small".

### LINKED ISSUE #92147: Compatibility OmniLight turns everything green, only for XRCamera
### Tested versions

reproducible in  4.2.1 and 4.3-dev6 at the least

### System information

Windows 10, i5, Geforce 1070, as well as tested on quest3 (BUILD)

### Issue description

do you guys know of a green-shifting error with omnilights in the compatability renderer, only caused with a xr camera?

- error disappears in other renderers.
- only with a xr camera, uses only a origin, a camera, and the given xrtools starter
- tested in different scenes, tested in different project but with the same assets and
- only with omnilights
- anything in its affecting range is shifted green (albedo wise. acts like any color, alpha and darkness affect it)
- only caused when it has a procedural skybox or fog (sky affect to 0 has no affect)
             (custom color and clear color is fine, but fog breaks it if enabled)
- i dont seem to notice any abnormal choices pertaining to rendering in settings
- havent tested cross-devices (but builds have been tested on a quest 3, no difference)
- seems to happen to all shaders in 3d-space atleast
- light doesnt actually emit when error. 😕
- disabled ambient and reflected light has no affect
- disabling fog in the MATERIAL, does not stop the issue in its respective edgecase

PICTURE NOTE : the directional light is fine, i had it turned off to notice the omnilight easier in these pictures. it doesnt seem to affect the bug. also if it was off for the skybox-only it would've been pitch black. the omnilight is on in all these pictures

### Steps to reproduce

- use compatability renderer
- use monolight in a scene.
- have fog or procedural sky enabled
- have xrcamera rendering

thats the best i got for ya :/

### Minimal reproduction project (MRP)

how the hell do i fit this in 10Mb???

https://drive.google.com/file/d/1CKaiCyspeKlmJxetN3smaXchhZn4tPtQ/view?usp=sharing

### PR DESCRIPTION
**Pull request by BastiaanOlij**
This one was super dumb. 

Turns out setting stereo rendering for sky set uniform location 5 to the uniform buffer containing Multiview data for the sky.
Geometry rendering however uses this to access the omni light buffer.
The result is that the rendering was accessing the incorrect data.

- Fixes: https://github.com/godotengine/godot/issues/92147
- Fixes: https://github.com/godotengine/godot/issues/82278

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
@clayjohn I think this could use a rework at some point so that we rebind the correct uniform buffers after we perform the sky process, but for now I've solved it the same way this was already solved for the conflict with `SCENE_DATA_UNIFORM_LOCATION` and `SKY_DIRECTIONAL_LIGHT_UNIFORM_LOCATION`.

**Comment by akien-mga** [comment]
https://github.com/godotengine/godot/issues/82278 might be the same issue, does this fix it too?

**Comment by decacis** [comment]
Can confirm this fixes the issue!

| 4.3-dev6 | This PR |
|-----------|--------|
| Lionfish-First-Appropriate | Quagga-Blind-Nervous |

File: drivers/gles3/rasterizer_scene_gles3.h [hunk 1]
```diff
@@ -70,21 +70,28 @@ enum SceneUniformLocation {
...
 	SCENE_MATERIAL_UNIFORM_LOCATION,
-	SCENE_EMPTY, // Unused, put here to avoid conflicts with SKY_DIRECTIONAL_LIGHT_UNIFORM_LOCATION.
+	SCENE_EMPTY1, // Unused, put here to avoid conflicts with SKY_DIRECTIONAL_LIGHT_UNIFORM_LOCATION.
 	SCENE_OMNILIGHT_UNIFORM_LOCATION,
 	SCENE_SPOTLIGHT_UNIFORM_LOCATION,
 	SCENE_DIRECTIONAL_LIGHT_UNIFORM_LOCATION,
 	SCENE_MULTIVIEW_UNIFORM_LOCATION,
 	SCENE_POSITIONAL_SHADOW_UNIFORM_LOCATION,
 	SCENE_DIRECTIONAL_SHADOW_UNIFORM_LOCATION,
+	SCENE_EMPTY2, // Unused, put here to avoid conflicts with SKY_DIRECTIONAL_LIGHT_UNIFORM_LOCATION.
```
Comment (dsnopek) [inline drivers/gles3/rasterizer_scene_gles3.h:80]:
```suggestion
	SCENE_EMPTY2, // Unused, put here to avoid conflicts with SKY_MULTIVIEW_UNIFORM_LOCATION.
```

**Review by dsnopek — APPROVED** [review]
I just tested if this fixes issue https://github.com/godotengine/godot/issues/82278 (using the MRP from issue https://github.com/godotengine/godot/issues/89662) and it does! (I've updated the description to add that issue)

Other than a small issue in a comment, the code changes look good to me!

**Review by clayjohn — APPROVED** [review]
I agree this has gotten quite ugly. We should probably reorganize at some point, but this change is fine for now

**Comment by wiseblank** [comment]
Awesome debugging, been troubled by this as well.

File: drivers/gles3/rasterizer_scene_gles3.h (hunk 1 above)
Comment (BastiaanOlij) [reply drivers/gles3/rasterizer_scene_gles3.h]: oops :)

**Comment by akien-mga** [comment]
Thanks!

@BastiaanOlij I see you flagged this for a 4.2 cherrypick, which makes sense. Do you think it would also cherry-pick and work properly for 4.1?

**Comment by BastiaanOlij** [comment]
@akien-mga I think this has been in there for a long time so probably yes, but I think someone might want to test that hypothesis.
