### PR TITLE
Use OrderedHashMap for enum_values

### LINKED ISSUE #55534: Exporting Named enum values is shown out of order in editor
### Godot version

4.0-alpha

### System information

Windows 10

### Issue description

Using a named enum as value for an exported variable shows the elements out of order in the editor. Also, the order changes with each loading of the scene.

This example:
```
enum EnumTest{TEST_1, TEST_2, TEST_3, TEST_4, TEST_7}
@export var choose_type: EnumTest = 0

func _ready():
	print(choose_type == EnumTest.TEST_3)
```
brings:
image

I know that we can use something like `@export_enum(TEST_1, TEST_2, TEST_3, TEST_4, TEST_7) var choose_type: int`, but you will need to create an enum with these same values to check equality in the script.

### Steps to reproduce

Following the docs (https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_exports.html?highlight=exporting%20variable#named-enum-values):

Create a named enum, and use it as value for an exported variable and check it's order in the editor.

Example:
```
enum EnumTest{TEST_1, TEST_2, TEST_3, TEST_4, TEST_7}
@export var choose_type: EnumTest = 0
```

### Minimal reproduction project

[export_enum_order_problem.zip](https://github.com/godotengine/godot/files/7638418/export_enum_order_problem.zip)

### PR DESCRIPTION
**Pull request by nathanfranke**
Fixes https://github.com/godotengine/godot/issues/55534

### CODE REVIEW

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -3510,12 +3510,12 @@ bool GDScriptParser::export_annotations(const AnnotationNode *p_annotation, Node
 				variable->export_info.hint = PROPERTY_HINT_ENUM;
 
 				String enum_hint_string;
-				for (const Map<StringName, int>::Element *E = export_type.enum_values.front(); E; E = E->next()) {
-					enum_hint_string += E->key().operator String().capitalize().xml_escape();
+				for (OrderedHashMap<StringName, int>::Element E = export_type.enum_values.front(); E; E = E.next()) {
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp:3513]: Ideally this should use a range iterator, but it's not available for `OrderedHashMap` yet, so it's fine for now.

**Review by vnen — APPROVED** [review]
LGTM

**Comment by akien-mga** [comment]
Thanks!
