### PR TITLE
Fix grouping annotations displayed in script document

### LINKED ISSUE #62953: GDScript 2.0: Export group annotations show in documentation
### Godot version

v4.0.alpha.custom_build [d26442e70]

### System information

Arch on 5.18.10-arch1-1

### Issue description

Given code:

```gdscript
extends Node

@export_group("Hello")
@export var world: int

```

Open it in docs, and `Variant Hello` is shown
image

### Steps to reproduce

1) Use the code above

### Minimal reproduction project

[test9.zip](https://github.com/godotengine/godot/files/9093545/test9.zip)

### PR DESCRIPTION
**Pull request by Xwdit**
Fix #62953

### CODE REVIEW

**Comment by akien-mga** [comment]
Needs rebase to fix CI due to a temporary godot-cpp issue.

**Comment by Xwdit** [comment]
> Needs rebase to fix CI due to a temporary godot-cpp issue.

Rebased to fix CI issue

File: modules/gdscript/gdscript.cpp [hunk 1]
```diff
@@ -536,6 +536,9 @@ void GDScript::_update_doc() {
 	List<PropertyInfo> props;
 	_get_script_property_list(&props, false);
 	for (int i = 0; i < props.size(); i++) {
+		if (props[i].usage & PROPERTY_USAGE_CATEGORY || props[i].usage & PROPERTY_USAGE_GROUP || props[i].usage & PROPERTY_USAGE_SUBGROUP) {
```
Comment (nathanfranke) [inline modules/gdscript/gdscript.cpp:539]:
```suggestion
		if (props[i].usage & (PROPERTY_USAGE_CATEGORY | PROPERTY_USAGE_GROUP | PROPERTY_USAGE_SUBGROUP)) {
```

99% sure this will work the same, and is arguably more readable, but if anyone disagrees that's fine.

Comment (vnen) [reply modules/gdscript/gdscript.cpp:539]: @nathanfranke It's not the same thing. Your way will only work if usage has all 3 flags set at once.

**Review by vnen — APPROVED** [review]
Looks good to me.

File: modules/gdscript/gdscript.cpp (hunk 1 above)
Comment (nathanfranke) [reply modules/gdscript/gdscript.cpp:539]: if the usages are `0b001`, `0b010`, and `0b100`, `x | y | z` will be `0b111` and `usage & (x | y | z)` will be truthy if any flag is enabled.

Comment (akien-mga) [reply modules/gdscript/gdscript.cpp:539]: Let's merge as is, but this could be a relevant cleanup PR as it seems we use both styles currently:
```
$ rg "usage & \(PROPERTY_USAGE.*\| PROPERTY_USAGE.*\)" | wc -l
16

$ rg "usage & PROPERTY_USAGE.* \|\| .*usage & PROPERTY_USAGE.*" | wc -l
11
```

**Comment by akien-mga** [comment]
Thanks!
