### PR TITLE
Make `AnimationTree` time / delta value force `double` in core

### LINKED ISSUE #57274: `AnimationTree` weird animation stuttering
### Godot version

4.0.alpha1 (31a7ddb)

### System information

Windows 11 21H2, Vulkan Clustered, Geforce 1660 (511.23)

### Issue description

I get weird animation stuttering at beginning of animation, then it disappears.

Godot v4.0.alpha1 (with stuttering):

https://user-images.githubusercontent.com/10379487/151245120-d82e8b90-e39b-48c5-b600-e657bb161ff1.mp4

Version 3.x don't have this problem. 

Godot v3.5.beta1 (without stuttering):

https://user-images.githubusercontent.com/10379487/151245397-de03c423-861f-4787-b5ad-e4aa1d066bbf.mp4

### Steps to reproduce

- open `Animation Test G4` project;
- press play button;
- run from one side to another.

Here the [AnimationTest_G3.zip](https://github.com/godotengine/godot/files/7945556/AnimationTest_G3.zip) for comparison how it should work.

### Minimal reproduction project

[AnimationTest_G4.zip](https://github.com/godotengine/godot/files/7945548/AnimationTest_G4.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
Fixed #57274. Probably the cause of the bug is that the process time from core is not passed as `double`.
Include some revert unnecessary change of #57295.

### CODE REVIEW

File: scene/animation/animation_tree.cpp [hunk 1]
```diff
@@ -1159,7 +1159,7 @@ void AnimationTree::_process_graph(real_t p_delta) {
 									}
 								}
 							} else {
-								if (prev_time > a->get_length()) {
+								if (prev_time > (double)a->get_length()) {
```
Comment (aaronfranke) [inline scene/animation/animation_tree.cpp:1162]: Why? I don't think that an explicit cast in this comparison does anything. Or is it to avoid warnings?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
