### PR TITLE
Fix node processing order

### LINKED ISSUE #77548: Setting bone rotation in _process gets overridden by running animation in 4.1-dev3
### Godot version

4.1 dev3

### System information

Windows 11, Forward+, Intel 13700k, 4070ti

### Issue description

In 4.0.x and in 4.1 dev2, if you overwrite the rotation of a bone in `_process` it has preferred over the currently running animation. In 4.1 dev3, the running animation takes precedence and overwrites any changes in `_process`. This happens both with a simple animation and with an animation tree, and happens in-editor and in-game.

### Steps to reproduce

1. Open the attached project.
2. Click on `AnimationPlayer` and pick an animation, e.g. `Armature|Standing`. Set it to looping if it's not already. (@RandomShaper's note: and play it).
3. Click on the `PointOfInterest` and move it along the X axis.
4. If you're on:
    - 4.0.x or 4.1-dev2: Notice the head rotating
    - 4.1-dev3: Notice that nothing happens

### Minimal reproduction project

[BoneRotationIssue-4.0.3.zip](https://github.com/godotengine/godot/files/11582187/BoneRotationIssue-4.0.3.zip)
[BoneRotationIssue-4.1-dev.zip](https://github.com/godotengine/godot/files/11582188/BoneRotationIssue-4.1-dev.zip)

Should include all licensing stuff for the model, but let me just add [the link](https://opengameart.org/content/human-model-ready-for-animation) for good measure.

### PR DESCRIPTION
**Pull request by RandomShaper**
Node processing used to work like this (disclaimer: pseudocode):
```
FOR-EACH (Physics, Idle):
	FOR-EACH node:
		node.internal_process()
	FOR-EACH node:
		node.process()
```

After #75901 it changed to (note changed nesting of internal/external and node iterations, as well as the relative order of internal/external):
```
FOR-EACH (Physics, Idle):
	FOR-EACH group:
		group.message_queue.flush()
		FOR-EACH node in group:
			node.process()
			node.internal_process()
		group.message_queue.flush()
```

This PR changes the processing so it looks much closer to what it was like. Specifically, while still supporting group processing, it makes internal happen first and changes the nesting of internal/external and node iterations:
```
FOR-EACH (Physics, Idle):
	FOR-EACH group:
		group.message_queue.flush()
		FOR-EACH node in group:
			node.internal_process()
	FOR-EACH group:
		FOR-EACH node in group:
			node.process()
		group.message_queue.flush()
```

**UPDATE:** See https://github.com/godotengine/godot/pull/78745#issuecomment-1609935022.

Bonus: _Fix issues in group-processing related setters_.

**WARNING:** While this fixes a relevant compat breakage, it's very likely that we have edge cases here and there. Moreover, this would need to be smoke and non-smoke tested to be sure the remedy is not worse than the illness.

Fixes #77548.

### CODE REVIEW

File: scene/main/scene_tree.h [hunk 1]
```diff
@@ -214,9 +214,9 @@ class SceneTree : public MainLoop {
 	void remove_from_group(const StringName &p_group, Node *p_node);
 	void make_group_changed(const StringName &p_group);
 
-	void _process_group(ProcessGroup *p_group, bool p_physics);
-	void _process_groups_thread(uint32_t p_index, bool p_physics);
-	void _process(bool p_physics);
+	void _process_group(ProcessGroup *p_group, bool p_physics, bool p_internal);
+	void _process_groups_thread(uint32_t p_index, Pair<bool, bool> p_physics_internal);
```
Comment (akien-mga) [inline scene/main/scene_tree.h:218]: Out of curiosity, what's the rationale for using a `Pair<bool, bool>` here as opposed to passing two bool arguments like for the other two `_process*`?

Comment (RandomShaper) [reply scene/main/scene_tree.h:218]: `WorkerThreadPool::add_template_group_task()` allows for a single user data argument. At first, I made a custom `ProcessingPass` struct and then I thought of `Pair`, that was kind of OK for this very specific case. In a future polishing pass we may want to rescue the `ProcessingPass` idea and make refactor all these functions to make use of it, for consistency.

**Comment by akien-mga** [comment]
Tested and confirmed this fixes https://github.com/godotengine/godot/issues/77548.
I'll try to find some other projects to make sure there's no obvious breakage.

**Comment by reduz** [comment]
While this is a solution, I am pretty sure that this will have a very significant performance impact, specially when having to deal with thread groups. So I am not very sure that doing this change just to warrant a specific processing order is better vs simply assuming that processing order will not be there any more.

Does not simply changing it to this:

```GDScript
FOR-EACH (Physics, Idle):
	FOR-EACH group:
		group.message_queue.flush()
		FOR-EACH node in group:
		        # just swap these
			node.internal_process()
			node.process()
		group.message_queue.flush()
```

Resolve the problem? Otherwise, how could this be solved in the context of the skeleton so we don't have to do such major change with the performance implications it carries with it?

**Comment by reduz** [comment]
To further clarify, with this PR, threads will most of the time be organized, allocated, started and waited to do essentially nothing, so I think this is not the right solution to the problem.

This could be optimized by improving the thread allocation in the process code to avoid them starting if they are going to do nothing, but I think this is a ton of work with little benefit, all for keeping an order of processing that is not very important in the remaining 99.99% of nodes or for Godot users.

So I insist that I would find a solution to the problem elsewhere without doing this type of change.

**Comment by RandomShaper** [comment]
It seems that switching the order of internal/non-internal does the trick for the bug, so I've updated the PR removing the other changes.

This is the original patch (as a backup, just in case): [d.txt](https://github.com/godotengine/godot/files/11885481/d.txt)

**Review by akien-mga — APPROVED** [review]
That's a more minimal and safe change in line with what reduz asked for, so I'm relatively confident approving this, TIWAGOS of course.

**Comment by akien-mga** [comment]
Thanks!
