### PR TITLE
[macOS] Fix microphone issue

### LINKED ISSUE #110624: Mic Record fails on Godot 4.5 on macOS
### Tested versions

- Reproducable in Godot 4.5

### System information

Godot v4.5.stable - macOS Sequoia (15.6.1) - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - Apple M1 Pro - Apple M1 Pro (10 threads) - 16.00 GiB memory

### Issue description

I am getting this error on 4.5 when i want to record with mic.

E 0:00:00:326 init_input_device: Condition "result != noErr" is true. Returning: FAILED

<C++ Source> drivers/coreaudio/audio_driver_coreaudio.mm:408 @ init_input_device()

W 0:00:00:326 initialize: All audio drivers failed, falling back to the dummy driver.

<C++ Source> servers/audio_server.cpp:244 @ initialize()

### Steps to reproduce

Open Godot 4.5 on macOS.

Create or open a project that uses AudioServer / AudioEffect / AudioStream for microphone capture (or call your microphone recording script).

Request microphone access / start recording from the project (e.g. using AudioServer input methods or AudioStreamMicrophone).

Observe Godot console/log — initialization fails with the error above and no audio is recorded.

### Minimal reproduction project (MRP)

[mic_record.zip](https://github.com/user-attachments/files/22391446/mic_record.zip)

### PR DESCRIPTION
**Pull request by adamscott**
Fixes #110624
Supersedes (in some ways) #111662 (as it doesn't require checking for permissions)

>[!NOTE]
>A variation of #111662 will be needed, as macOS seems to ask for permission each time the binary needs microphone access. I'm investigating.

### CODE REVIEW

File: drivers/coreaudio/audio_driver_coreaudio.mm [hunk 1]
```diff
@@ -394,6 +394,11 @@
 	UInt32 flag = 1;
 	result = AudioUnitSetProperty(input_unit, kAudioOutputUnitProperty_EnableIO, kAudioUnitScope_Input, kInputBus, &flag, sizeof(flag));
 	ERR_FAIL_COND_V(result != noErr, FAILED);
+#ifdef MACOS_ENABLED
+	flag = 0;
+	result = AudioUnitSetProperty(input_unit, kAudioOutputUnitProperty_EnableIO, kAudioUnitScope_Output, kOutputBus, &flag, sizeof(flag));
+	ERR_FAIL_COND_V(result != noErr, FAILED);
+#endif
```
Comment (adamscott) [inline drivers/coreaudio/audio_driver_coreaudio.mm:401]: Was there a reason for removing this flag set on #107973? Was setting this flag on Apple Embedded devices triggering the permissions system? Because removing it broke macOS microphone input.

cc. @paddy-exe @migueldeicaza

Comment (migueldeicaza) [reply drivers/coreaudio/audio_driver_coreaudio.mm:401]: I will investigate, as I do not recall.  My tree does not have it on mobile.

But looking at this audio unit call, it is odd that it would be necessary, as what that does is disable the output on the microphone.

Comment (migueldeicaza) [reply drivers/coreaudio/audio_driver_coreaudio.mm:401]: Ok, I checked both with and without on iOS and it makes no difference to have it.

Perhaps on iOS, we could remove the ERR_FAIL_COND_V return, just in case?

**Review by bruvzg — APPROVED** [review]
I can confirm it is fixing recording on macOS.

This code disables output on recording component, I have no idea why it's needed, but should be safe to do.

Note: Permission popup do show up without any additional changes, but https://github.com/godotengine/godot/pull/111662 probably still is a good idea, since it fill allow user code to check if permission is granted.

**Comment by Repiteo** [comment]
Thanks!
