### PR TITLE
Fix lambda cross-thread dynamics (reverted)

### LINKED ISSUE #84046: Deferred call of GDScript lambda from thread leads to double free or corruption when hot reloading
### Godot version

v4.2.beta3.official [e8d57afae]

### System information

Godot v4.2.beta3 - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA RTX A2000 Laptop GPU (NVIDIA; 31.0.15.2737) - 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 Threads)

### Issue description

In Godot 4.1 I regularly use `call_deferred` to send data from a WorkerThreadPool thread back to the main thread. Usually this involves a direct function call, but occasionally I emit a deferred signal by wrapping the emit call into a lambda:
```gdscript
(func(): test_signal.emit()).call_deferred()
```
In Godot 4.2, this crashes the game.

Simply emitting the signal (without deferring it) does not immediately crash the game, but does not call the connected signals either. 

### Steps to reproduce

Simply create a node with the following script and attempt to run it.

```gdscript
extends Node2D

signal test_signal

func _ready():
	test_signal.connect(test_done)
	WorkerThreadPool.add_task(T_test_func)

func T_test_func():
	print("Test processing called.")
	#test_done.call_deferred() # This works.
	#test_signal.emit() # This doesn't crash but test_done is not called.
	(func(): test_signal.emit()).call_deferred() # This crashes the game.

func test_done():
	print("Test done.")
```

### Minimal reproduction project

Reproduction is trivial without a dedicated project.

### LINKED ISSUE #84190: Lambda call within a non-main thread forces Godot to crash at exit
### Godot version

9144457484f9d2f53990a0aac37caff1c9012e6d

### System information

Windows 11

### Issue description

Running the following code:

```gdscript
extends Node3D

var thread : Thread
var array = [3, 2, 1]

func _ready():
	thread = Thread.new()
	thread.start(do_some_work)
	thread.wait_to_finish()
	print(array)

func do_some_work() -> void:
	array.sort_custom(func(a, b): return a < b)
```

executes correctly, but when user closes the application or call get_tree().quit() the Godot will crash with the following call stack:
```
 	godot.windows.editor.x86_64.exe!GDScript::clear(GDScript::ClearData * p_clear_data) Line 1440	C++
 	godot.windows.editor.x86_64.exe!GDScript::~GDScript() Line 1518	C++
 	godot.windows.editor.x86_64.exe!GDScript::`scalar deleting destructor'(unsigned int)	C++
 	[Inline Frame] godot.windows.editor.x86_64.exe!memdelete(GDScript * p_class) Line 109	C++
 	godot.windows.editor.x86_64.exe!Ref<GDScript>::unref() Line 210	C++
 	[Inline Frame] godot.windows.editor.x86_64.exe!Ref<GDScript>::{dtor}() Line 222	C++
 	[Inline Frame] godot.windows.editor.x86_64.exe!memdelete(HashMapElement<String,Ref<GDScript>> *) Line 109	C++
 	[Inline Frame] godot.windows.editor.x86_64.exe!DefaultTypedAllocator<HashMapElement<String,Ref<GDScript>>>::delete_allocation(HashMapElement<String,Ref<GDScript>> * p_allocation) Line 206	C++
 	godot.windows.editor.x86_64.exe!HashMap<String,Ref<GDScript>,HashMapHasherDefault,HashMapComparatorDefault<String>,DefaultTypedAllocator<HashMapElement<String,Ref<GDScript>>>>::clear() Line 265	C++
 	godot.windows.editor.x86_64.exe!GDScriptCache::clear() Line 445	C++
>	godot.windows.editor.x86_64.exe!GDScriptLanguage::finish() Line 2116	C++
 	godot.windows.editor.x86_64.exe!ScriptServer::finish_languages() Line 229	C++
 	godot.windows.editor.x86_64.exe!Main::cleanup(bool p_force) Line 3763	C++
 	godot.windows.editor.x86_64.exe!widechar_main(int argc, wchar_t * * argv) Line 184	C++
 	godot.windows.editor.x86_64.exe!_main() Line 206	C++
 	godot.windows.editor.x86_64.exe!main(int argc, char * * argv) Line 218	C++
 	[Inline Frame] godot.windows.editor.x86_64.exe!invoke_main() Line 102	C++
 	godot.windows.editor.x86_64.exe!__scrt_common_main_seh() Line 288	C++
 	kernel32.dll!00007fff2373257d()	Unknown
 	ntdll.dll!00007fff2540aa78()	Unknown
```
изображение

Seems like a desynced mutex, or corrupted heap. Maybe this is a duplicate of https://github.com/godotengine/godot/issues/84046, but I'm not sure.

### Steps to reproduce

Run the script printed above, and after then try to close the game application.

### Minimal reproduction project

[TestThreadCrash.zip](https://github.com/godotengine/godot/files/13206161/TestThreadCrash.zip)

### PR DESCRIPTION
**Pull request by RandomShaper**
While reviewing #84616 (which this one supersedes) I found the underlying issue to be more complicated.

This requires #84657 so tasks submitted to the `WorkerThreadPool` have their thread cleanup run.

Fixes #84046.
Fixes #84190.

~**TEMP:** In draft until I can be sure both issues are really fixed.~

**UPDATE:** In a future iteration, all this thread-local bookeeping may be replaced by heap-allocated items. That would simplify this a lot, but now it's better (I think) to keep the current approach to lower the risk of regressions.

### CODE REVIEW

File: modules/gdscript/gdscript.h [hunk 1]
```diff
@@ -128,11 +128,15 @@ class GDScript : public Script {
 		Mutex *mutex = nullptr;
 	};
 	static thread_local UpdatableFuncPtr func_ptrs_to_update_thread_local;
+	static UpdatableFuncPtr *GDScript::func_ptrs_to_update_main_thread;
```
Comment (akien-mga) [inline modules/gdscript/gdscript.h:131]:
```suggestion
	static UpdatableFuncPtr *func_ptrs_to_update_main_thread;
```

**Comment by adamscott** [comment]
Got an error while exiting the app for #84046.

image

**Comment by RandomShaper** [comment]
Out of draft! Given the complexity of the fix, any testing is welcome.

File: modules/gdscript/gdscript.cpp [hunk 2]
```diff
@@ -1387,33 +1387,105 @@ String GDScript::debug_get_script_name(const Ref<Script> &p_script) {
...
+
+			E->erase();
+		}
+	}
+
+	{
+		// Remove orphan thread-to-script entries from every script.
+		// FIXME: This involves iterating through every script whenever a thread dies.
+		//        While it's OK that thread creation/destruction are heavy operations,
+		//        additional bookkeeping can be used to outperforma this brute-force approach.
```
Comment (adamscott) [inline modules/gdscript/gdscript.cpp:1470]:
```suggestion
		//        additional bookkeeping can be used to outperform this brute-force approach.
```

File: modules/gdscript/gdscript.cpp [hunk 3]
```diff
@@ -1387,33 +1387,105 @@ String GDScript::debug_get_script_name(const Ref<Script> &p_script) {
...
+			if (!scripts.has(script)) {
+				scripts.insert(script);
+
+				// Replace dying thread by the main thread in the script-to-thread records.
+
+				MutexLock lock3(script->func_ptrs_to_update_mutex);
+				DEV_ASSERT(script->func_ptrs_to_update.find(&func_ptrs_to_update_thread_local));
+				{
+					for (List<UpdatableFuncPtrElement>::Element *F = script->func_ptrs_to_update_elems.front(); F; F = F->next()) {
+						bool is_main_thread_entry = F->get().mutex == &func_ptrs_to_update_main_thread->mutex;
```
Comment (adamscott) [inline modules/gdscript/gdscript.cpp:1450]:
```suggestion

```

This line doesn't seem to be used in the scope.

File: modules/gdscript/gdscript.cpp (hunk 2 above)
Comment (adamscott) [reply modules/gdscript/gdscript.cpp:1470]: For once, I will be able that I was faster than you, friend!

**Comment by adamscott** [comment]
I tested (at least 10 times) your build against MRPs of #84046 and #84190 and it seems to do the trick!

File: modules/gdscript/gdscript.cpp [hunk 4]
```diff
@@ -1387,33 +1387,105 @@ String GDScript::debug_get_script_name(const Ref<Script> &p_script) {
...
-	ERR_FAIL_NULL(p_func_ptr_element.mutex);
-	MutexLock lock(*p_func_ptr_element.mutex);
-	p_func_ptr_element.element->erase();
+void GDScript::_remove_func_ptr_to_update(const UpdatableFuncPtrElement *p_func_ptr_element) {
+	ERR_FAIL_NULL(p_func_ptr_element);
+	ERR_FAIL_NULL(p_func_ptr_element->element);
+	ERR_FAIL_NULL(p_func_ptr_element->mutex);
+	MutexLock lock(*p_func_ptr_element->mutex);
+	p_func_ptr_element->element->erase();
+}
```
Comment (nlupugla) [inline modules/gdscript/gdscript.cpp:1420]: Is it okay to lock the mutex after the null checks? What if `p_func_ptr_element` exists when you null check it, but another thread frees it by the time you lock the mutex?

**Comment by allenwp** [comment]
870149924abc1b36715cc90e852aa5818446a14b fixes #84046 on my machine!

File: modules/gdscript/gdscript.cpp (hunk 3 above)
Comment (RandomShaper) [reply modules/gdscript/gdscript.cpp:1450]: Fixed!

File: modules/gdscript/gdscript.cpp (hunk 2 above)
Comment (RandomShaper) [reply modules/gdscript/gdscript.cpp:1470]: Fix coming in next push, where I will also split the function.

Comment (RandomShaper) [reply modules/gdscript/gdscript.cpp]: Well, just renamed in the end. Splitting would have not been appropiate.

File: modules/gdscript/gdscript.cpp (hunk 4 above)
Comment (RandomShaper) [reply modules/gdscript/gdscript.cpp:1420]: First of all, I think none of the checks can fail unless there's a bug. Neither `element` nor `mutex` are ever nullified (if they were nullified here to mark the deletion or something, the lock should happen before indeed). Regarding the whole `p_func_ptr_element`, its users (`GDScriptLambda*Callable`) should never try to call this function with it being null. Because of that, I've added an `if` to `GDScriptLambdaSelfCallable`, which can indeed have it as null. I think that's cleaner. I won't remove the checks now, for extra safety, though, but in the end my advise would be to remove them. We could keep a `DEV_ASSERT(p_func_ptr_element != nullptr)`, but a null pointer there would be very easy to spot while debugging a crash anyway.

For completeness, let me add that multiple theards can't call this function on the same `UpdatableFuncPtrElement`. There's one of those per lambda, and a lambda is destroyed on one thread. If multiple threads were trying to run its destructor, something would be very broken.

Comment (nlupugla) [reply modules/gdscript/gdscript.cpp]: Would it be more appropriate to make the function take a `const UpdateableFuncPtrElement &` instead of a `const UpdateableFuncPtrElement *` so the type checker can ensure the parameter isn't null?

Comment (RandomShaper) [reply modules/gdscript/gdscript.cpp]: It may be a good idea. However, I stayed away from doing so since that would propagate back to the caller, which right now would need to dereference what is already a pointer for it, with the ugly `*something` notation. Something worth doing in an upcoming iteration.

**Comment by akien-mga** [comment]
I can't say much about the implementation, but I've been testing this today with a number of projects, some relying a lot on lambdas, and so far I haven't noticed any regression.

I also tested the MRPs and confirmed it fixes #84046 for me. The other one seems Windows specific so I didn't test as I'm on Linux right now.

**Review by akien-mga — APPROVED** [review]
Cautiously approving, but TIWAGOS.
I've been using it the whole day and didn't run into any obvious issue.

**Comment by akien-mga** [comment]
Thanks!

File: modules/gdscript/gdscript.cpp [hunk 5]
```diff
@@ -1387,33 +1387,106 @@ String GDScript::debug_get_script_name(const Ref<Script> &p_script) {
...
-	MutexLock lock(*p_func_ptr_element.mutex);
-	p_func_ptr_element.element->erase();
+void GDScript::_remove_func_ptr_to_update(const UpdatableFuncPtrElement *p_func_ptr_element) {
+	// None of these checks should ever fail, unless there's a bug.
+	// They can be removed once we are sure they never catch anything.
+	// Left here now due to extra safety needs late in the release cycle.
+	ERR_FAIL_NULL(p_func_ptr_element);
+	MutexLock lock(*p_func_ptr_element->mutex);
+	ERR_FAIL_NULL(p_func_ptr_element->element);
+	ERR_FAIL_NULL(p_func_ptr_element->mutex);
```
Comment (neobine) [inline modules/gdscript/gdscript.cpp:1421]: Just reading over commits getting a feel for the engine internals and noticed it checks if p_func_ptr_element->mutex is null after already deref to lock above?

Comment (AThousandShips) [reply modules/gdscript/gdscript.cpp:1421]: This code is no longer present, it was reworked later

**Comment by akien-mga** [comment]
For the record, this was reverted/superseded by #85248.
