### PR TITLE
Fix inspector spacing issues

### LINKED ISSUE #104931: [4.4.1] In the Inspector, gaps between properties outside of groups are missing
### Tested versions

Reproducible: 4.4.1 (.NET)
Not reproducible: 4.4 (.NET)

### System information

Godot v4.4.1.stable.mono - Windows 11 (build 26100) - Single-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 Ti Laptop GPU (NVIDIA; 32.0.15.5597) - AMD Ryzen 7 5800HS with Radeon Graphics (16 threads)

### Issue description

As in title, gaps between properties outside of groups are missing.

In 4.4.1:
Image

In 4.4:
Image

The gaps between properties in groups and subgroups are still there.

This is purely a cosmetic issue, while it does introduces inconsistency between versions and cases, and reduces readability when multiple input fields are stuck together.

Image

### Steps to reproduce

Open Godot 4.4 and Godot 4.4.1, add a node (for example, a button, as properties of a button cover all three cases: not in a group, in a group, and in a subgroup) and check the inspector.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by dugramen**
Fixes #104931 and reverts #103309 & #104344. 

This instead adds a new solution, where adjacent `EditorInspectorSections` are automatically grouped into the same vbox, with 0 separation and without disrupting their order.

This has the added benefit of preserving the order of normal groups (They were always stuck to the bottom of the category, unlike subgroups which would stay in place. See https://github.com/godotengine/godot/issues/104931#issuecomment-2829211862)

image
(Screenshot of normal properties being properly spaced again. And array groups, which are all the groups besides "Resource", having no gaps)

### CODE REVIEW

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -3386,6 +3384,23 @@ bool EditorInspector::_is_property_disabled_by_feature_profile(const StringName
...
+	VBoxContainer *container = nullptr;
+	if (p_current_vbox->get_child_count() > 0) {
+		Node *last_child = p_current_vbox->get_child(-1);
+		if (last_child->is_class("VBoxContainer")) {
+			container = Object::cast_to<VBoxContainer>(last_child);
+		}
+	}
+	if (!container) {
+		container = memnew(VBoxContainer);
+		container->add_theme_constant_override("separation", 0);
```
Comment (passivestar) [inline editor/editor_inspector.cpp:3398]: This would break [theming](https://github.com/godotengine/godot/pull/93435), should be `get_theme_constant(SNAME("v_separation"), SNAME("EditorInspector")`

It's already `0` by default:
https://github.com/godotengine/godot/blob/e37c6261ea48b1a339c469282df7e9b7c073a72f/editor/themes/editor_theme_manager.cpp#L2249-L2250

File: editor/inspector/editor_inspector.cpp [hunk 2]
```diff
@@ -3386,6 +3384,23 @@ bool EditorInspector::_is_property_disabled_by_feature_profile(const StringName
...
 }
 
+inline void add_section_in_tree(EditorInspectorSection *p_section, VBoxContainer *p_current_vbox) {
+	// Place adjacent sections in their own vbox with 0 separation
+	VBoxContainer *container = nullptr;
+	if (p_current_vbox->get_child_count() > 0) {
+		Node *last_child = p_current_vbox->get_child(-1);
+		if (last_child->is_class("VBoxContainer")) {
+			container = Object::cast_to<VBoxContainer>(last_child);
+		}
```
Comment (AThousandShips) [inline editor/inspector/editor_inspector.cpp]:
```suggestion
		container = Object::cast_to<VBoxContainer>(last_child);
```
Should be equivalent and more efficient

File: editor/editor_inspector.cpp (hunk 1 above)
Comment (dugramen) [reply editor/editor_inspector.cpp]: Forgot about that. Just pushed the change

**Comment by passivestar** [comment]
Tested with minimal theme, fixes the spacing. Needs a rebase

| 4.5 | PR |
|--------|--------|
| a | b |

**Comment by YeldhamDev** [comment]
Needs a rebase.

**Comment by dugramen** [comment]
Ok rebased it, but theres a failed test idk about. It looks like an svg issue. Is that related to this PR somehow?

**Comment by YeldhamDev** [comment]
macOS CI shenanigans, all good now.

**Review by YeldhamDev — APPROVED** [review]

File: editor/inspector/editor_inspector.cpp (hunk 2 above)
Comment (dugramen) [reply editor/inspector/editor_inspector.cpp]: ok updated it

**Comment by Repiteo** [comment]
Thanks!
