### PR TITLE
Fix SceneTree Item text display bug in Right-to-Left

### LINKED ISSUE #103790: In Right-to-Left, the SceneTree Item text is displayed incorrectly.
### Tested versions

 Reproducible in 4.5dev.
Not  reproducible in 4.4stable.
The bug is trggered after #103424

### System information

Windows 11 Intel(R) Core(TM) i7-11800H NVIDIA RTX3050

### Issue description

In Right-to-Left, if you narrow the SceneTree, the SceneTree Item text is displayed incorrectly.
Left-to-Right - correctly:

Image
Right-to-Left - incorrectly:

Image

### Steps to reproduce

1. Create a new project.
2. Add multi-level child items to the SceneTree.
3. Narrow the SceneTree.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by BrotherShort**
Fix #103790
After fix:
test_record1

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -1945,60 +1945,67 @@ void Tree::draw_item_rect(TreeItem::Cell &p_cell, const Rect2i &p_rect, const Co
...
 
 	RID ci = get_canvas_item();
 
-	if (rtl && rect.size.width > 0) {
-		Point2 draw_pos = rect.position;
-		draw_pos.y += Math::floor((rect.size.y - p_cell.text_buf->get_size().y) * 0.5);
-		if (p_ol_size > 0 && p_ol_color.a > 0) {
-			p_cell.text_buf->draw_outline(ci, draw_pos, p_ol_size, p_ol_color);
+	if (rtl) {
+		if (ts.width > 0) {
```
Comment (KoBeWi) [inline scene/gui/tree.cpp:1984]: Why this split if the cody only exists for both conditions?

Comment (BrotherShort) [reply scene/gui/tree.cpp:1984]: Line 1983 "if" and line 1984 "if" have different uses.
if not "rtl", do nothing;
if rtl and ts.width > 0, draw text and move position;
if rtl and ts.width <=0, move position;

I think you have a question about the line 2000 and line 2001. They are similar to line 1983 and line 1984.
Line 2000 "if" and line 2001 "if" control same body. I split two conditons to make the line 2001-2008 same as 1984-1991. 
If you don't like split conditons, I will put them in one "if".

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
