### PR TITLE
Ignore process serial number argument passed by macOS Gatekeeper.

### LINKED ISSUE #35383: MacOS Application Not Responding on First Launch
**Godot version:**
3.2 RC 2 (Mono)

**OS/device including version:**
MacOS Catalina 10.15.2

**Issue description:**
When I downloaded the latest RC and launch the first time, after allowing the unsigned app to launch in System Prefs -> Security, Godot just sits running fairly intensively but doesn't launch.  The icon shows "Application Not Responding" and so I have to Force Quit.  After that, it works.

**Steps to reproduce:**
1) Download on macOS
2) Launch Godot, macOS will give warnings
3) Go to System Preferences -> Security and allow the app to run
4) Launch Godot again
5) It's spinning and doing nothing, right click the icon to see "Application Not Responding", click Force Quit.
6) Relaunch Godot again, all is well.

**Minimal reproduction project:**
N/A

### LINKED ISSUE #36616: cfprefsd process at 100% CPU usage
**Godot version:**
Godot 3.2.1 rc1

**OS/device including version:**
MacOS Catalina 10.15.3 (19D76)

**Issue description:**
cfprefsd process regularly jumps to 100%, sometimes just launching Godot is enough to cause it to happen, sometimes it happens while I'm using the UI, everything is unresponsive, the cfprefsd progress can't be closed even with `kill -9` and only restarting the computer is possible.

**Steps to reproduce:**
It happened to me the first time when I copied Godot 3.2.1.rc1.mono to the Applications folder then launched it. I tried uninstalling Godot entirely and starting it again. It doesn't happen all the time. But if I use Godot long enough (1h+) it always end up happening at some point.

I reverted to 3.2.stable.mono - I'm sending it so that it gets looked at before going from rc1 to the final version.

### LINKED ISSUE #37446: Godot application keeps crashing on launch
**Godot version:**
3.2.1
**OS/device including version:**
Mac OS X 10.13.6 
**Issue description:**
Uninstalled 3.2, fresh installed 3.2.1 version. Tried to run newly installed godot app but crashed with message "Godot quit unexpectedly"
**Steps to reproduce:**
Fresh install and run the app
**Full stacktrace of the crash:**

```Process:               Godot [69001]
Path:                  /Applications/Godot_mono.app/Contents/MacOS/Godot
Identifier:            org.godotengine.godot
Version:               3.2 (3.2)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Godot [69001]
User ID:               501

Date/Time:             2020-03-30 17:14:00.436 -0400
OS Version:            Mac OS X 10.13.6 (17G65)
Report Version:        12
Bridge OS Version:     3.0 (14Y664)
Anonymous UUID:        3DDF1EFF-841B-EA1C-ED03-2C23CD241F6F

Sleep/Wake UUID:       EB370A9F-8351-4087-A8A4-E428AF508100

Time Awake Since Boot: 840000 seconds
Time Since Wake:       300 seconds

System Integrity Protection: enabled

Crashed Thread:        0  tid_307  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGABRT)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Thread 0 Crashed:: tid_307  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff76055b66 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff76220080 pthread_kill + 333
2   libsystem_c.dylib             	0x00007fff75fb11ae abort + 127
3   org.godotengine.godot         	0x000000010586478e mono_post_native_crash_handler + 14
4   org.godotengine.godot         	0x0000000105857c8b mono_handle_native_crash + 475
5   org.godotengine.godot         	0x000000010586b5a0 mono_sigill_signal_handler + 80
6   libsystem_platform.dylib      	0x00007fff76213f5a _sigtramp + 26
7   ???                           	000000000000000000 0 + 0
8   org.godotengine.godot         	0x0000000106079dfe GDMono::initialize_load_assemblies() + 14
9   org.godotengine.godot         	0x0000000105ff33fa CSharpLanguage::init() + 314
10  org.godotengine.godot         	0x0000000108258009 ScriptServer::init_languages() + 937
11  org.godotengine.godot         	0x0000000105ae715a Main::setup2(unsigned long long) + 6554
12  org.godotengine.godot         	0x0000000105ae1848 Main::setup(char const*, int, char**, bool) + 25368
13  org.godotengine.godot         	0x0000000105ac8149 main + 313
14  libdyld.dylib                 	0x00007fff75f05015 start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff7605628a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff7621d20e _pthread_wqthread + 1552
2   libsystem_pthread.dylib       	0x00007fff7621cbe9 start_wqthread + 13

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff7605628a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff7621d20e _pthread_wqthread + 1552
2   libsystem_pthread.dylib       	0x00007fff7621cbe9 start_wqthread + 13

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff7605628a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff7621d20e _pthread_wqthread + 1552
2   libsystem_pthread.dylib       	0x00007fff7621cbe9 start_wqthread + 13

Thread 4:
0   libsystem_kernel.dylib        	0x00007fff7605628a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff7621d20e _pthread_wqthread + 1552
2   libsystem_pthread.dylib       	0x00007fff7621cbe9 start_wqthread + 13

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff7605628a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff7621d009 _pthread_wqthread + 1035
2   libsystem_pthread.dylib       	0x00007fff7621cbe9 start_wqthread + 13

Thread 6:
0   libsystem_kernel.dylib        	0x00007fff7605628a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff7621d009 _pthread_wqthread + 1035
2   libsystem_pthread.dylib       	0x00007fff7621cbe9 start_wqthread + 13

Thread 7:
0   libsystem_kernel.dylib        	0x00007fff7605628a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff7621d20e _pthread_wqthread + 1552
2   libsystem_pthread.dylib       	0x00007fff7621cbe9 start_wqthread + 13

Thread 8:
0   libsystem_kernel.dylib        	0x00007fff76057142 read + 10
1   org.godotengine.godot         	0x0000000105ac85c9 SemaphoreOSX::wait() + 25
2   org.godotengine.godot         	0x000000010840eb03 _IP_ResolverPrivate::_thread_function(void*) + 83
3   org.godotengine.godot         	0x000000010653b6c5 ThreadPosix::thread_callback(void*) + 85
4   libsystem_pthread.dylib       	0x00007fff7621d661 _pthread_body + 340
5   libsystem_pthread.dylib       	0x00007fff7621d50d _pthread_start + 377
6   libsystem_pthread.dylib       	0x00007fff7621cbf9 thread_start + 13

Thread 9:
0   libsystem_kernel.dylib        	0x00007fff76057142 read + 10
1   org.godotengine.godot         	0x0000000105ac85c9 SemaphoreOSX::wait() + 25
2   org.godotengine.godot         	0x0000000107fea8fd VisualServerScene::_gi_probe_bake_thread() + 29
3   org.godotengine.godot         	0x000000010653b6c5 ThreadPosix::thread_callback(void*) + 85
4   libsystem_pthread.dylib       	0x00007fff7621d661 _pthread_body + 340
5   libsystem_pthread.dylib       	0x00007fff7621d50d _pthread_start + 377
6   libsystem_pthread.dylib       	0x00007fff7621cbf9 thread_start + 13

Thread 10:
0   libsystem_kernel.dylib        	0x00007fff7604c25e semaphore_timedwait_trap + 10
1   libdispatch.dylib             	0x00007fff75edb94f _dispatch_sema4_timedwait + 72
2   libdispatch.dylib             	0x00007fff75ed394e _dispatch_semaphore_wait_slow + 58
3   libdispatch.dylib             	0x00007fff75ecee53 _dispatch_worker_thread + 251
4   libsystem_pthread.dylib       	0x00007fff7621d661 _pthread_body + 340
5   libsystem_pthread.dylib       	0x00007fff7621d50d _pthread_start + 377
6   libsystem_pthread.dylib       	0x00007fff7621cbf9 thread_start + 13

Thread 11:: com.apple.audio.IOThread.client
0   libsystem_kernel.dylib        	0x00007fff7604c20a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff7604b724 mach_msg + 60
2   com.apple.audio.CoreAudio     	0x00007fff4db2587a HALB_MachPort::SendMessageWithReply(unsigned int, unsigned int, unsigned int, unsigned int, mach_msg_header_t*, bool, unsigned int) + 124
3   com.apple.audio.CoreAudio     	0x00007fff4db257ed HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 45
4   com.apple.audio.CoreAudio     	0x00007fff4db22859 HALC_ProxyIOContext::IOWorkLoop() + 977
5   com.apple.audio.CoreAudio     	0x00007fff4db222bc HALC_ProxyIOContext::IOThreadEntry(void*) + 128
6   com.apple.audio.CoreAudio     	0x00007fff4db21ffe HALB_IOThread::Entry(void*) + 72
7   libsystem_pthread.dylib       	0x00007fff7621d661 _pthread_body + 340
8   libsystem_pthread.dylib       	0x00007fff7621d50d _pthread_start + 377
9   libsystem_pthread.dylib       	0x00007fff7621cbf9 thread_start + 13

Thread 12:: SGen worker
0   libsystem_kernel.dylib        	0x00007fff76055a16 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff7621e589 _pthread_cond_wait + 732
2   org.godotengine.godot         	0x0000000105a809c3 thread_func + 243
3   libsystem_pthread.dylib       	0x00007fff7621d661 _pthread_body + 340
4   libsystem_pthread.dylib       	0x00007fff7621d50d _pthread_start + 377
5   libsystem_pthread.dylib       	0x00007fff7621cbf9 thread_start + 13

Thread 13:: Finalizer
0   libsystem_kernel.dylib        	0x00007fff7604c246 semaphore_wait_trap + 10
1   org.godotengine.godot         	0x000000010593b86b finalizer_thread + 379
2   org.godotengine.godot         	0x0000000105a0f026 start_wrapper_internal + 374
3   org.godotengine.godot         	0x0000000105a0ee87 start_wrapper + 71
4   libsystem_pthread.dylib       	0x00007fff7621d661 _pthread_body + 340
5   libsystem_pthread.dylib       	0x00007fff7621d50d _pthread_start + 377
6   libsystem_pthread.dylib       	0x00007fff7621cbf9 thread_start + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00007fffaea1c380  rcx: 0x00007ffeea478908  rdx: 0x0000000000000000
  rdi: 0x0000000000000307  rsi: 0x0000000000000006  rbp: 0x00007ffeea478940  rsp: 0x00007ffeea478908
   r8: 0x00007ffeea4782b8   r9: 0x00007ffeea478550  r10: 0x0000000000000000  r11: 0x0000000000000206
  r12: 0x0000000000000307  r13: 0x00007fc7e9563cc0  r14: 0x0000000000000006  r15: 0x000000000000002d
  rip: 0x00007fff76055b66  rfl: 0x0000000000000206  cr2: 0x00007fffae9ff0c8
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133


Binary Images:
       0x105785000 -        0x1097fdfa7 +org.godotengine.godot (3.2 - 3.2) <D579A97E-2FAF-3AA2-9F14-C447F0E2C3E4> /Applications/Godot_mono.app/Contents/MacOS/Godot
       0x10c2ca000 -        0x10c314acf  dyld (551.4) <8A72DE9C-A136-3506-AA02-4BA2B82DCAF3> /usr/lib/dyld
       0x10dd07000 -        0x10de3efff  com.apple.AMDMTLBronzeDriver (1.68.20 - 1.6.8) <C5D6A803-7CE1-32BD-BE34-C518131CED8B> /System/Library/Extensions/AMDMTLBronzeDriver.bundle/Contents/MacOS/AMDMTLBronzeDriver
       0x10e7bd000 -        0x10f53aff7  com.apple.driver.AppleIntelKBLGraphicsGLDriver (10.36.19 - 10.3.6) <7363D45E-0011-38F0-BDBF-C298AC5C9A59> /System/Library/Extensions/AppleIntelKBLGraphicsGLDriver.bundle/Contents/MacOS/AppleIntelKBLGraphicsGLDriver
       0x10f978000 -        0x10fa3affb  com.apple.AMDRadeonX4000GLDriver (1.68.20 - 1.6.8) <03AC29A1-DE03-3031-854D-B7F6D2018B4D> /System/Library/Extensions/AMDRadeonX4000GLDriver.bundle/Contents/MacOS/AMDRadeonX4000GLDriver
       0x116509000 -        0x1166b1ff7  com.apple.audio.units.Components (1.14 - 1.14) <1E04BB32-1550-3851-8CD1-4A588BFE5D46> /System/Library/Components/CoreAudio.component/Contents/MacOS/CoreAudio
       0x116753000 -        0x116757ffb  com.apple.audio.AppleHDAHALPlugIn (281.52 - 281.52) <23C7DDE6-A44B-3BE4-B47C-EB3045B267D9> /System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/AppleHDAHALPlugIn.bundle/Contents/MacOS/AppleHDAHALPlugIn
       0x116bad000 -        0x116bd3fff  com.apple.cmio.DAL.VDC-4 (814.0 - 4995) <FCDA18EC-2875-35FA-B10E-9F14FBAABFC9> /System/Library/Frameworks/CoreMediaIO.framework/Resources/VDC.plugin/Contents/MacOS/VDC
    0x7fff46b94000 -     0x7fff473eaff7  ATIRadeonX4000SCLib.dylib (1.68.20) <09BE979C-D263-34F4-A83D-3E36420ED78D> /System/Library/Extensions/AMDRadeonX4000GLDriver.bundle/Contents/MacOS/ATIRadeonX4000SCLib.dylib
    0x7fff47fe1000 -     0x7fff481ccfff  com.apple.driver.AppleIntelKBLGraphicsMTLDriver (10.36.19 - 10.3.6) <A5C358C5-A4EC-3726-A7EB-49300B599A2D> /System/Library/Extensions/AppleIntelKBLGraphicsMTLDriver.bundle/Contents/MacOS/AppleIntelKBLGraphicsMTLDriver
    0x7fff4a21b000 -     0x7fff4a21fffb  com.apple.agl (3.3.1 - AGL-3.3.1) <9B886891-66A5-3026-8C61-61B3C5F4EAC9> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fff4a220000 -     0x7fff4a400ff3  com.apple.avfoundation (2.0 - 1536.36) <BB65ED51-CE44-31BD-A6EC-4B1EC5EADDD9> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff4a401000 -     0x7fff4a4bafff  com.apple.audio.AVFAudio (1.0 - ???) <ECE63BA3-4344-3522-904B-71F89677AC7D> /System/Library/Frameworks/AVFoundation.framework/Versions/A/Frameworks/AVFAudio.framework/Versions/A/AVFAudio
    0x7fff4a5c0000 -     0x7fff4a5c0fff  com.apple.Accelerate (1.11 - Accelerate 1.11) <8632A9C5-19EA-3FD7-A44D-80765CC9C540> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff4a5c1000 -     0x7fff4a5d7fef  libCGInterfaces.dylib (417.2) <2E67702C-75F6-308A-A023-F28120BEE667> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/Libraries/libCGInterfaces.dylib
    0x7fff4a5d8000 -     0x7fff4aad6fc3  com.apple.vImage (8.1 - ???) <A243A7EF-0C8E-3A9A-AA38-44AFD7507F00> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/vImage
    0x7fff4aad7000 -     0x7fff4ac31fe3  libBLAS.dylib (1211.50.2) <62C659EB-3E32-3B5F-83BF-79F5DF30D5CE> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
    0x7fff4ac32000 -     0x7fff4ac60fef  libBNNS.dylib (38.1) <7BAEFDCA-3227-3E07-80D8-59B6370B89C6> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib
    0x7fff4ac61000 -     0x7fff4b020ff7  libLAPACK.dylib (1211.50.2) <40ADBA5F-8B2D-30AC-A7AD-7B17C37EE52D> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
    0x7fff4b021000 -     0x7fff4b036ff7  libLinearAlgebra.dylib (1211.50.2) <E8E0B7FD-A0B7-31E5-AF01-81781F71EBBE> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLinearAlgebra.dylib
    0x7fff4b037000 -     0x7fff4b03cff3  libQuadrature.dylib (3) <3D6BF66A-55B2-3692-BAC7-DEB0C676ED29> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libQuadrature.dylib
    0x7fff4b03d000 -     0x7fff4b0bdfff  libSparse.dylib (79.50.2) <0DC25CDD-F8C1-3D6E-B472-8B060708424F> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparse.dylib
    0x7fff4b0be000 -     0x7fff4b0d1fff  libSparseBLAS.dylib (1211.50.2) <722573CC-31CC-34B2-9032-E4F652A9CCFE> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparseBLAS.dylib
    0x7fff4b0d2000 -     0x7fff4b27ffc3  libvDSP.dylib (622.50.5) <40690941-CF89-3F90-A0AC-A4D200744A5D> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib
    0x7fff4b280000 -     0x7fff4b331fff  libvMisc.dylib (622.50.5) <BA2532DF-2D68-3DD0-9B59-D434BF702AA4> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib
    0x7fff4b332000 -     0x7fff4b332fff  com.apple.Accelerate.vecLib (3.11 - vecLib 3.11) <54FF3B43-E66C-3F36-B34B-A2B3B0A36502> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
    0x7fff4b626000 -     0x7fff4c484fff  com.apple.AppKit (6.9 - 1561.60.100) <3C27CF6F-E640-3411-A87D-CCB2222CC754> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff4c4d6000 -     0x7fff4c4d6fff  com.apple.ApplicationServices (48 - 50) <AFFBD94A-AF76-336E-B53E-57524EAE8EF3> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff4c4d7000 -     0x7fff4c53dfff  com.apple.ApplicationServices.ATS (377 - 445.4) <85E779EE-0219-3181-B4C4-201E4CC82AB5> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS
    0x7fff4c5d6000 -     0x7fff4c6f8fff  libFontParser.dylib (222.1.6) <6CEBACDD-B848-302E-B4B2-630CB16E663E> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontParser.dylib
    0x7fff4c6f9000 -     0x7fff4c743ff7  libFontRegistry.dylib (221.4) <5FDB4F1A-E15C-3ACB-A5C1-F15458C0C6DC> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib
    0x7fff4c7e8000 -     0x7fff4c81bff7  libTrueTypeScaler.dylib (222.1.6) <9147F859-8BD9-31D9-AB54-8E9549B92AE9> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libTrueTypeScaler.dylib
    0x7fff4c885000 -     0x7fff4c889ff3  com.apple.ColorSyncLegacy (4.13.0 - 1) <A5FB2694-1559-34A8-A3D3-2029F68A63CA> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSyncLegacy.framework/Versions/A/ColorSyncLegacy
    0x7fff4c929000 -     0x7fff4c97bffb  com.apple.HIServices (1.22 - 624.1) <66FD9ED2-9630-313C-86AE-4C2FBCB3F351> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices
    0x7fff4c97c000 -     0x7fff4c98afff  com.apple.LangAnalysis (1.7.0 - 1.7.0) <B65FF7E6-E9B5-34D8-8CA7-63D415A8A9A6> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LangAnalysis.framework/Versions/A/LangAnalysis
    0x7fff4c98b000 -     0x7fff4c9d7fff  com.apple.print.framework.PrintCore (13.4 - 503.2) <B90C67C1-0292-3CEC-885D-F1882CD104BE> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/PrintCore
    0x7fff4c9d8000 -     0x7fff4ca12fff  com.apple.QD (3.12 - 404.2) <38B20AFF-9D54-3B52-A6DC-C0D71380AA5F> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/QD
    0x7fff4ca13000 -     0x7fff4ca1ffff  com.apple.speech.synthesis.framework (7.8.1 - 7.8.1) <A08DE016-C8F2-3B0E-BD34-15959D13DBF0> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis
    0x7fff4ca20000 -     0x7fff4ccaeff7  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <E0B8B5D8-80A0-308B-ABD6-F8612102B5D8> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff4ccb0000 -     0x7fff4ccb0fff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <ABF8778E-4F9D-305E-A528-DE406A1A2B68> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff4cfd3000 -     0x7fff4d36dff7  com.apple.CFNetwork (902.1 - 902.1) <76EB8CB6-BF59-3BDA-BF2B-F21B161611B9> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff4d382000 -     0x7fff4d382fff  com.apple.Carbon (158 - 158) <F8B370D9-2103-3276-821D-ACC756167F86> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff4d383000 -     0x7fff4d386ffb  com.apple.CommonPanels (1.2.6 - 98) <2391761C-5CAA-3F68-86B7-50B37927B104> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/CommonPanels.framework/Versions/A/CommonPanels
    0x7fff4d387000 -     0x7fff4d68cfff  com.apple.HIToolbox (2.1.1 - 911.10) <BF7F9C0E-C732-3FB2-9BBC-362888BDA57B> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7fff4d68d000 -     0x7fff4d690ffb  com.apple.help (1.3.8 - 66) <DEBADFA8-C189-3195-B0D6-A1F2DE95882A> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Help.framework/Versions/A/Help
    0x7fff4d691000 -     0x7fff4d696fff  com.apple.ImageCapture (9.0 - 9.0) <23B4916F-3B43-3DFF-B956-FC390EECA284> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/ImageCapture.framework/Versions/A/ImageCapture
    0x7fff4d697000 -     0x7fff4d72cffb  com.apple.ink.framework (10.9 - 221) <5206C8B0-22DA-36C9-998E-846EDB626D5B> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Ink.framework/Versions/A/Ink
    0x7fff4d72d000 -     0x7fff4d747ff7  com.apple.openscripting (1.7 - 174) <1B2A1F9E-5534-3D61-83CA-9199B39E8708> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/OpenScripting.framework/Versions/A/OpenScripting
    0x7fff4d768000 -     0x7fff4d769fff  com.apple.print.framework.Print (12 - 267) <3682ABFB-2561-3419-847D-02C247F4800D> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Print.framework/Versions/A/Print
    0x7fff4d76a000 -     0x7fff4d76cff7  com.apple.securityhi (9.0 - 55006) <C1406B8D-7D05-3959-808F-9C82189CF57F> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SecurityHI.framework/Versions/A/SecurityHI
    0x7fff4d76d000 -     0x7fff4d773fff  com.apple.speech.recognition.framework (6.0.3 - 6.0.3) <2ED8643D-B0C3-3F17-82A2-BBF13E6CBABC> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SpeechRecognition.framework/Versions/A/SpeechRecognition
    0x7fff4d894000 -     0x7fff4d894fff  com.apple.Cocoa (6.11 - 22) <78E6C28E-4308-3D10-AD14-0CBCF6789B3F> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff4d8a2000 -     0x7fff4d95bfff  com.apple.ColorSync (4.13.0 - 3325) <D283C285-447D-3258-A7E4-59532123B8FF> /System/Library/Frameworks/ColorSync.framework/Versions/A/ColorSync
    0x7fff4dae8000 -     0x7fff4db7bff7  com.apple.audio.CoreAudio (4.3.0 - 4.3.0) <EB35D3EC-56EA-33E6-98DC-BDC3A5FA8ACE> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff4dbe2000 -     0x7fff4dc0bffb  com.apple.CoreBluetooth (1.0 - 1) <E1335074-9D07-370E-8440-61C4874BAC56> /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
    0x7fff4dc0c000 -     0x7fff4df62fef  com.apple.CoreData (120 - 851) <A2B59780-FB16-36A3-8EE0-E0EF072454E0> /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
    0x7fff4df63000 -     0x7fff4e046fff  com.apple.CoreDisplay (99.14 - 99.14) <A1B91ADD-828D-33A0-8A92-CC3F83DF89D0> /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
    0x7fff4e047000 -     0x7fff4e4e8fef  com.apple.CoreFoundation (6.9 - 1454.90) <E5D594BF-9142-3325-A62D-CF4AAF472642> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff4e4ea000 -     0x7fff4eafafef  com.apple.CoreGraphics (2.0 - 1161.21) <375C477F-5A89-3C49-9B63-373C81A63F7E> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff4eafc000 -     0x7fff4edebfff  com.apple.CoreImage (13.0.0 - 579.5) <AAE2DFD0-9B0A-3D56-8A3E-C460BAF70394> /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
    0x7fff4ee58000 -     0x7fff4ee9dfff  com.apple.audio.midi.CoreMIDI (1.10 - 88) <BC3E756C-A066-325C-9383-A78A4A66C7BF> /System/Library/Frameworks/CoreMIDI.framework/Versions/A/CoreMIDI
    0x7fff4f07a000 -     0x7fff4f170ffb  com.apple.CoreMedia (1.0 - 2276.68) <5F0001EF-10FF-3334-9170-7FD5FB026205> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff4f171000 -     0x7fff4f1bffff  com.apple.CoreMediaIO (814.0 - 4995) <4A7FA7DF-4F7C-3378-AE5F-A33273B2FEA6> /System/Library/Frameworks/CoreMediaIO.framework/Versions/A/CoreMediaIO
    0x7fff4f1c0000 -     0x7fff4f1c0fff  com.apple.CoreServices (822.36 - 822.36) <C8368F17-1589-3BA5-A0E7-89CB8DF2454F> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff4f1c1000 -     0x7fff4f235ffb  com.apple.AE (735.1 - 735.1) <08EBA184-20F7-3725-AEA6-C314448161C6> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
    0x7fff4f236000 -     0x7fff4f50dfff  com.apple.CoreServices.CarbonCore (1178.4 - 1178.4) <0D5E19BF-18CB-3FA4-8A5F-F6C787C5EE08> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
    0x7fff4f50e000 -     0x7fff4f542fff  com.apple.DictionaryServices (1.2 - 284.2) <6505B075-41C3-3C62-A4C3-85CE3F6825CD> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
    0x7fff4f543000 -     0x7fff4f54bffb  com.apple.CoreServices.FSEvents (1239.50.1 - 1239.50.1) <3637CEC7-DF0E-320E-9634-44A442925C65> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents
    0x7fff4f54c000 -     0x7fff4f709fff  com.apple.LaunchServices (822.36 - 822.36) <6E68C090-B12D-3D3D-9617-E5D82C36B2D0> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
    0x7fff4f70a000 -     0x7fff4f7baff7  com.apple.Metadata (10.7.0 - 1191.4.13) <B5C22E70-C265-3C9F-865F-B138994A418D> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
    0x7fff4f7bb000 -     0x7fff4f81bfff  com.apple.CoreServices.OSServices (822.36 - 822.36) <3BB2E0CE-81AE-3D3D-9FCE-E1B7FC6D6A61> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
    0x7fff4f81c000 -     0x7fff4f88afff  com.apple.SearchKit (1.4.0 - 1.4.0) <3662545A-B1CF-3079-BDCD-C83855CEFEEE> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
    0x7fff4f88b000 -     0x7fff4f8afffb  com.apple.coreservices.SharedFileList (71.21 - 71.21) <35582D88-5975-35E2-A29A-E3148C3EE727> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList
    0x7fff4fb50000 -     0x7fff4fca0fff  com.apple.CoreText (352.0 - 578.22) <6129F39D-284D-3BBF-8999-7854AB61C01C> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff4fca1000 -     0x7fff4fcdbfff  com.apple.CoreVideo (1.8 - 0.0) <86CCC036-51BB-3DD1-9601-D93798BCCD0F> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff4fcdc000 -     0x7fff4fd67ff3  com.apple.framework.CoreWLAN (13.0 - 1350.1) <E862CC02-69D2-3503-887B-B6E8223081E7> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff4ffe2000 -     0x7fff4ffe7fff  com.apple.DiskArbitration (2.7 - 2.7) <A975AD56-4CD3-3A89-8732-858CA9BD3DAA> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff501a5000 -     0x7fff501a7ff7  com.apple.ForceFeedback (1.0.6 - 1.0.6) <87FB3F31-DF4C-3172-BF86-45EFC331BDD8> /System/Library/Frameworks/ForceFeedback.framework/Versions/A/ForceFeedback
    0x7fff501a8000 -     0x7fff5056efff  com.apple.Foundation (6.9 - 1454.90) <8EA924F3-ADAE-3F4B-8482-8B11C027D9A5> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff505df000 -     0x7fff5060ffff  com.apple.GSS (4.0 - 2.0) <D774A165-5581-3479-AB5D-2BBDB5CF8882> /System/Library/Frameworks/GSS.framework/Versions/A/GSS
    0x7fff50721000 -     0x7fff50825ffb  com.apple.Bluetooth (6.0.7 - 6.0.7f10) <557F26F9-C7A0-34EA-A905-22E243BF6B48> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth
    0x7fff50885000 -     0x7fff50920fff  com.apple.framework.IOKit (2.0.2 - 1445.71.1) <2EA4F383-CAA9-3AF0-99C5-90C22ADAA6B6> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff50922000 -     0x7fff50929fff  com.apple.IOSurface (211.15 - 211.15) <9FD406F1-6BF2-35B0-8339-DF83A1A661EB> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
    0x7fff50980000 -     0x7fff50afaff7  com.apple.ImageIO.framework (3.3.0 - 1739.3) <7C579D3F-AE0B-31C9-8F80-67F2290B8DE0> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff50afb000 -     0x7fff50affffb  libGIF.dylib (1739.3) <7AA44C9D-48E8-3090-B044-61FE6F0AEF38> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libGIF.dylib
    0x7fff50b00000 -     0x7fff50be7fef  libJP2.dylib (1739.3) <AEBF7260-0C10-30C0-8F0F-8B347DEE78B3> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib
    0x7fff50be8000 -     0x7fff50c0bff7  libJPEG.dylib (1739.3) <D8C966AD-A00C-3E8B-A7ED-D7CC7ECB3224> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib
    0x7fff50ee7000 -     0x7fff50f0dfeb  libPng.dylib (1739.3) <1737F680-99D1-3F03-BFA5-5CDA30EB880A> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
    0x7fff50f0e000 -     0x7fff50f10ffb  libRadiance.dylib (1739.3) <21746434-FCC7-36DE-9331-11277DF66AA8> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libRadiance.dylib
    0x7fff50f11000 -     0x7fff50f5ffef  libTIFF.dylib (1739.3) <C4CB5C1D-20F2-3BD4-B0E6-629FDB3EF8E8> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib
    0x7fff51e19000 -     0x7fff51e32ff7  com.apple.Kerberos (3.0 - 1) <F86DCCDF-93C1-38B3-82C2-477C12E8EE6D> /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
    0x7fff520f1000 -     0x7fff520f8fff  com.apple.MediaAccessibility (1.0 - 114) <9F72AACD-BAEB-3646-BD0F-12C47591C20D> /System/Library/Frameworks/MediaAccessibility.framework/Versions/A/MediaAccessibility
    0x7fff521a8000 -     0x7fff52812ff7  com.apple.MediaToolbox (1.0 - 2276.68) <CB6791F2-B401-360E-9531-BFBC5138254E> /System/Library/Frameworks/MediaToolbox.framework/Versions/A/MediaToolbox
    0x7fff52814000 -     0x7fff52895fff  com.apple.Metal (125.30 - 125.30) <975FD6B5-D695-346A-869F-0584A968D100> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
    0x7fff528b2000 -     0x7fff528cdfff  com.apple.MetalPerformanceShaders.MPSCore (1.0 - 1) <AD754E8F-CA00-3878-9AF3-208C224A230B> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSCore.framework/Versions/A/MPSCore
    0x7fff528ce000 -     0x7fff5293dfef  com.apple.MetalPerformanceShaders.MPSImage (1.0 - 1) <338B7779-E608-3D68-8A07-2ACC11299744> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSImage.framework/Versions/A/MPSImage
    0x7fff5293e000 -     0x7fff52962fff  com.apple.MetalPerformanceShaders.MPSMatrix (1.0 - 1) <9CE072D7-853B-3939-9645-7EB951376B87> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSMatrix.framework/Versions/A/MPSMatrix
    0x7fff52963000 -     0x7fff52a4aff7  com.apple.MetalPerformanceShaders.MPSNeuralNetwork (1.0 - 1) <0DE891AD-27E5-38FF-AEC8-4A95356C4357> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSNeuralNetwork.framework/Versions/A/MPSNeuralNetwork
    0x7fff52a4b000 -     0x7fff52a4bff7  com.apple.MetalPerformanceShaders.MetalPerformanceShaders (1.0 - 1) <2D2D261C-50B0-32F9-BF9A-5C01382BB528> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/MetalPerformanceShaders
    0x7fff53a4a000 -     0x7fff53a56ffb  com.apple.NetFS (6.0 - 4.0) <471DD96F-FA2E-3FE9-9746-2519A6780D1A> /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS
    0x7fff5683f000 -     0x7fff56847fef  libcldcpuengine.dylib (2.8.7) <EF9A91AC-029C-300A-99E7-4952C15DA09F> /System/Library/Frameworks/OpenCL.framework/Versions/A/Libraries/libcldcpuengine.dylib
    0x7fff56848000 -     0x7fff568a2ff7  com.apple.opencl (2.8.24 - 2.8.24) <4D7401A7-6ADD-3632-85AE-7A5012DFFA04> /System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL
    0x7fff568a3000 -     0x7fff568bfffb  com.apple.CFOpenDirectory (10.13 - 207.50.1) <29F55F7B-379F-3053-8FF3-5C6675A3DD4D> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory
    0x7fff568c0000 -     0x7fff568cbfff  com.apple.OpenDirectory (10.13 - 207.50.1) <F895547D-4915-353F-9C1E-E95172BA803B> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
    0x7fff57a4a000 -     0x7fff57a4cfff  libCVMSPluginSupport.dylib (16.7.4) <F9270AE0-CC3B-3E3E-BA32-CC1068DD8F27> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCVMSPluginSupport.dylib
    0x7fff57a4d000 -     0x7fff57a52ffb  libCoreFSCache.dylib (162.9) <7AF87F3E-D5D0-3625-BE09-CA4223195466> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreFSCache.dylib
    0x7fff57a53000 -     0x7fff57a57fff  libCoreVMClient.dylib (162.9) <115FE643-6141-39B4-8193-77DFCBE7A4E0> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreVMClient.dylib
    0x7fff57a58000 -     0x7fff57a61ff3  libGFXShared.dylib (16.7.4) <EB2BF8A0-E10D-35EA-8F46-B2E3C62C12A8> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGFXShared.dylib
    0x7fff57a62000 -     0x7fff57a6dfff  libGL.dylib (16.7.4) <2BB333D3-5C61-33DF-8545-06DF2D08B83D> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib
    0x7fff57a6e000 -     0x7fff57aa9fe7  libGLImage.dylib (16.7.4) <4DA003CE-0B74-3FE4-808C-B2FBCE517EB4> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLImage.dylib
    0x7fff57aaa000 -     0x7fff57c17ff3  libGLProgrammability.dylib (16.7.4) <ECC9D79B-C0B1-33F9-A9BB-097EF12D9E13> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLProgrammability.dylib
    0x7fff57c18000 -     0x7fff57c56ffb  libGLU.dylib (16.7.4) <BCB09CD8-EB0E-38FA-8B5A-9E29532EE364> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib
    0x7fff585ce000 -     0x7fff585ddff3  com.apple.opengl (16.7.4 - 16.7.4) <9BDE8FF9-5418-3C70-8D1C-09656884CE48> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff585de000 -     0x7fff58775ff3  GLEngine (16.7.4) <E2EE1D9C-826E-3DA9-9DCA-2FF371CDE5BB> /System/Library/Frameworks/OpenGL.framework/Versions/A/Resources/GLEngine.bundle/GLEngine
    0x7fff58776000 -     0x7fff5879effb  GLRendererFloat (16.7.4) <3B51AC1B-0A3C-30E5-80EB-F64EBB1B1F77> /System/Library/Frameworks/OpenGL.framework/Versions/A/Resources/GLRendererFloat.bundle/GLRendererFloat
    0x7fff5942c000 -     0x7fff59678ff7  com.apple.QuartzCore (1.11 - 584.62) <1950D993-DE48-3C97-95A5-66D98BDFC95D> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff59ead000 -     0x7fff5a1d8fff  com.apple.security (7.0 - 58286.70.7) <9FC166E1-14D0-305C-A086-02B9E83F547E> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff5a1d9000 -     0x7fff5a265ff7  com.apple.securityfoundation (6.0 - 55185.50.5) <D708D069-AEDB-36C2-B1DA-479DA91D7711> /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
    0x7fff5a297000 -     0x7fff5a29bffb  com.apple.xpc.ServiceManagement (1.0 - 1) <71B45D83-ECA4-3265-997E-683A8B8DF413> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff5a640000 -     0x7fff5a6b0ff3  com.apple.SystemConfiguration (1.17 - 1.17) <8532B8E9-7E30-35A3-BC4A-DDE8E0614FDA> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff5a865000 -     0x7fff5abe0fff  com.apple.VideoToolbox (1.0 - 2276.68) <8F6FBC7D-60EA-38B2-B583-7ECB58E8936E> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff5d5ad000 -     0x7fff5d640fff  com.apple.APFS (1.0 - 1) <6BBB3988-1C91-314F-A77A-4E093A1B18F0> /System/Library/PrivateFrameworks/APFS.framework/Versions/A/APFS
    0x7fff5e26b000 -     0x7fff5e293fff  com.apple.framework.Apple80211 (13.0 - 1361.7) <16627876-8CF5-3502-A1D6-35FCBDD5E79A> /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Apple80211
    0x7fff5e295000 -     0x7fff5e2a4fef  com.apple.AppleFSCompression (96.60.1 - 1.0) <A7C875C4-F5EE-3272-AFB6-57C9FD5352B3> /System/Library/PrivateFrameworks/AppleFSCompression.framework/Versions/A/AppleFSCompression
    0x7fff5e3a3000 -     0x7fff5e3aeff7  com.apple.AppleIDAuthSupport (1.0 - 1) <2FAF5567-CDB3-33EF-AB71-05D37F2248B7> /System/Library/PrivateFrameworks/AppleIDAuthSupport.framework/Versions/A/AppleIDAuthSupport
    0x7fff5e3e8000 -     0x7fff5e430ff3  com.apple.AppleJPEG (1.0 - 1) <8DD410CB-76A1-3F22-9A9F-0491FA0CEB4A> /System/Library/PrivateFrameworks/AppleJPEG.framework/Versions/A/AppleJPEG
    0x7fff5e46b000 -     0x7fff5e493fff  com.apple.applesauce (1.0 - ???) <CCA8B094-1BCE-3AE3-A0A7-D544C818DE36> /System/Library/PrivateFrameworks/AppleSauce.framework/Versions/A/AppleSauce
    0x7fff5e560000 -     0x7fff5e5b0ff7  com.apple.AppleVAFramework (5.0.41 - 5.0.41) <14E91E09-C345-3C5F-8D3C-4BC291FAF796> /System/Library/PrivateFrameworks/AppleVA.framework/Versions/A/AppleVA
    0x7fff5e8e5000 -     0x7fff5eb7effb  com.apple.AuthKit (1.0 - 1) <6CA71A11-91C5-307C-B933-9FCDEDCB580A> /System/Library/PrivateFrameworks/AuthKit.framework/Versions/A/AuthKit
    0x7fff5ecb5000 -     0x7fff5ecbcff7  com.apple.coreservices.BackgroundTaskManagement (1.0 - 57.1) <51A41CA3-DB1D-3380-993E-99C54AEE518E> /System/Library/PrivateFrameworks/BackgroundTaskManagement.framework/Versions/A/BackgroundTaskManagement
    0x7fff5ecbd000 -     0x7fff5ed44ff7  com.apple.backup.framework (1.9.5 - 1.9.5) <5E7B0925-8C71-353D-BB0F-9CA144BB264C> /System/Library/PrivateFrameworks/Backup.framework/Versions/A/Backup
    0x7fff606fe000 -     0x7fff60707ff3  com.apple.CommonAuth (4.0 - 2.0) <4D237B25-27E5-3577-948B-073659F6D3C0> /System/Library/PrivateFrameworks/CommonAuth.framework/Versions/A/CommonAuth
    0x7fff60a43000 -     0x7fff60e4bfff  com.apple.CoreAUC (259.0.0 - 259.0.0) <B3D5289B-9E8A-37FE-855B-7277D700029E> /System/Library/PrivateFrameworks/CoreAUC.framework/Versions/A/CoreAUC
    0x7fff60e4c000 -     0x7fff60e7cff7  com.apple.CoreAVCHD (5.9.0 - 5900.4.1) <E9FF9574-122A-3966-AA2B-546E512ACD06> /System/Library/PrivateFrameworks/CoreAVCHD.framework/Versions/A/CoreAVCHD
    0x7fff6120d000 -     0x7fff6121dff7  com.apple.CoreEmoji (1.0 - 69.3) <A4357F5C-0C38-3A61-B456-D7321EB2CEE5> /System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/CoreEmoji
    0x7fff619b1000 -     0x7fff619b9ff3  com.apple.CorePhoneNumbers (1.0 - 1) <A5D41251-9F38-3AB9-9DE7-F77023FAAA44> /System/Library/PrivateFrameworks/CorePhoneNumbers.framework/Versions/A/CorePhoneNumbers
    0x7fff61b44000 -     0x7fff61b75ff3  com.apple.CoreServicesInternal (309.1 - 309.1) <4ECD14EA-A493-3B84-A32F-CF928474A405> /System/Library/PrivateFrameworks/CoreServicesInternal.framework/Versions/A/CoreServicesInternal
    0x7fff61eb2000 -     0x7fff61f43fff  com.apple.CoreSymbolication (9.3 - 64026.2) <D55A6E5B-0267-3F3A-8D90-4B8F39458420> /System/Library/PrivateFrameworks/CoreSymbolication.framework/Versions/A/CoreSymbolication
    0x7fff61fc6000 -     0x7fff620fbfff  com.apple.coreui (2.1 - 494.1) <B2C515C3-FCE8-3B28-A225-05AD917F509B> /System/Library/PrivateFrameworks/CoreUI.framework/Versions/A/CoreUI
    0x7fff620fc000 -     0x7fff6222dfff  com.apple.CoreUtils (5.6 - 560.11) <1A02D6F0-8C65-3FAE-AD63-56477EDE4773> /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
    0x7fff62282000 -     0x7fff622e6fff  com.apple.framework.CoreWiFi (13.0 - 1350.1) <6EC5DEB3-6E2F-3DC2-BE59-1FD05175FB0C> /System/Library/PrivateFrameworks/CoreWiFi.framework/Versions/A/CoreWiFi
    0x7fff622e7000 -     0x7fff622f7ff7  com.apple.CrashReporterSupport (10.13 - 1) <A909F468-0648-3F51-A77E-3F9ADBC9A941> /System/Library/PrivateFrameworks/CrashReporterSupport.framework/Versions/A/CrashReporterSupport
    0x7fff62375000 -     0x7fff62384ff7  com.apple.framework.DFRFoundation (1.0 - 191.7) <5F486F5A-3795-3CD4-86A2-FD008A23F205> /System/Library/PrivateFrameworks/DFRFoundation.framework/Versions/A/DFRFoundation
    0x7fff62387000 -     0x7fff6238bffb  com.apple.DSExternalDisplay (3.1 - 380) <901B7F6D-376A-3848-99D0-170C4D00F776> /System/Library/PrivateFrameworks/DSExternalDisplay.framework/Versions/A/DSExternalDisplay
    0x7fff6240d000 -     0x7fff62483fff  com.apple.datadetectorscore (7.0 - 590.3) <7437160E-68A3-3FD7-8868-5E3F92E23C4F> /System/Library/PrivateFrameworks/DataDetectorsCore.framework/Versions/A/DataDetectorsCore
    0x7fff624d1000 -     0x7fff62511ff7  com.apple.DebugSymbols (181.0 - 181.0) <299A0238-ED78-3676-B131-274D972824AA> /System/Library/PrivateFrameworks/DebugSymbols.framework/Versions/A/DebugSymbols
    0x7fff62512000 -     0x7fff62641fff  com.apple.desktopservices (1.12.5 - 1.12.5) <7739C9A5-64D9-31A5-899B-5FFA242AD70D> /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv
    0x7fff6345b000 -     0x7fff63889fff  com.apple.vision.FaceCore (3.3.2 - 3.3.2) <B574FE33-4A41-3611-9738-388EBAF03E37> /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/FaceCore
    0x7fff654e5000 -     0x7fff654e5fff  libmetal_timestamp.dylib (802.4.8) <311A8FAA-5FA9-3AAF-887E-DC9884DE8BE5> /System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/3802/Libraries/libmetal_timestamp.dylib
    0x7fff66b45000 -     0x7fff66b50ff7  libGPUSupportMercury.dylib (16.7.4) <A4D6F79C-1DFA-3E96-8F76-4882FBEDE9CF> /System/Library/PrivateFrameworks/GPUSupport.framework/Versions/A/Libraries/libGPUSupportMercury.dylib
    0x7fff66b51000 -     0x7fff66b56fff  com.apple.GPUWrangler (3.20.13 - 3.20.13) <9C5BD618-69E3-36D5-9BC9-A4841BC00D2A> /System/Library/PrivateFrameworks/GPUWrangler.framework/Versions/A/GPUWrangler
    0x7fff678cc000 -     0x7fff678dbfff  com.apple.GraphVisualizer (1.0 - 5) <B993B8A2-5700-3DFC-9EB7-4CCEE8F959F1> /System/Library/PrivateFrameworks/GraphVisualizer.framework/Versions/A/GraphVisualizer
    0x7fff6795e000 -     0x7fff679d2fff  com.apple.Heimdal (4.0 - 2.0) <93091531-CC91-34FF-8B93-5D3F02C37BC5> /System/Library/PrivateFrameworks/Heimdal.framework/Versions/A/Heimdal
    0x7fff682d8000 -     0x7fff682e1fff  com.apple.IOAccelMemoryInfo (1.0 - 1) <E2416468-8B64-3BB8-A099-361954C8DED7> /System/Library/PrivateFrameworks/IOAccelMemoryInfo.framework/Versions/A/IOAccelMemoryInfo
    0x7fff682e2000 -     0x7fff682e9ff7  com.apple.IOAccelerator (378.26 - 378.26) <2274BE11-18DE-3B13-BCDB-C488C9BB19AD> /System/Library/PrivateFrameworks/IOAccelerator.framework/Versions/A/IOAccelerator
    0x7fff682ed000 -     0x7fff68304fff  com.apple.IOPresentment (1.0 - 35.1) <7C6332FF-6535-3064-B437-1E9F70671927> /System/Library/PrivateFrameworks/IOPresentment.framework/Versions/A/IOPresentment
    0x7fff686cf000 -     0x7fff686f5ffb  com.apple.IconServices (97.6 - 97.6) <A56D826D-20D2-34BE-AACC-A80CFCB4E915> /System/Library/PrivateFrameworks/IconServices.framework/Versions/A/IconServices
    0x7fff68802000 -     0x7fff68805ff3  com.apple.InternationalSupport (1.0 - 1) <5AB382FD-BF81-36A1-9565-61F1FD398ECA> /System/Library/PrivateFrameworks/InternationalSupport.framework/Versions/A/InternationalSupport
    0x7fff68873000 -     0x7fff68883ffb  com.apple.IntlPreferences (2.0 - 227.5.2) <DA6BC4CA-14F5-3A83-82B6-812344A050D2> /System/Library/PrivateFrameworks/IntlPreferences.framework/Versions/A/IntlPreferences
    0x7fff6897a000 -     0x7fff6898dff3  com.apple.security.KeychainCircle.KeychainCircle (1.0 - 1) <AED421B0-90A0-3969-98A4-CCBCF2D3360B> /System/Library/PrivateFrameworks/KeychainCircle.framework/Versions/A/KeychainCircle
    0x7fff6898e000 -     0x7fff68a83ff7  com.apple.LanguageModeling (1.0 - 159.5.3) <7F0AC200-E3DD-39FB-8A95-00DD70B66A9F> /System/Library/PrivateFrameworks/LanguageModeling.framework/Versions/A/LanguageModeling
    0x7fff68a84000 -     0x7fff68ac6fff  com.apple.Lexicon-framework (1.0 - 33.5) <DC94CF9E-1EB4-3C0E-B298-CA1190885276> /System/Library/PrivateFrameworks/Lexicon.framework/Versions/A/Lexicon
    0x7fff68aca000 -     0x7fff68ad1ff7  com.apple.LinguisticData (1.0 - 238.3) <49A54649-1021-3DBD-99B8-1B2EDFFA5378> /System/Library/PrivateFrameworks/LinguisticData.framework/Versions/A/LinguisticData
    0x7fff692d0000 -     0x7fff692d3fff  com.apple.Mangrove (1.0 - 1) <27D6DF76-B5F8-3443-8826-D25B284331BF> /System/Library/PrivateFrameworks/Mangrove.framework/Versions/A/Mangrove
    0x7fff697e3000 -     0x7fff6984cff7  com.apple.gpusw.MetalTools (1.0 - 1) <458F319A-2707-3C83-8351-BD9F02EC05BD> /System/Library/PrivateFrameworks/MetalTools.framework/Versions/A/MetalTools
    0x7fff699c8000 -     0x7fff699e1fff  com.apple.MobileKeyBag (2.0 - 1.0) <32E63C7B-E133-33DE-A593-C3C10D64FCAA> /System/Library/PrivateFrameworks/MobileKeyBag.framework/Versions/A/MobileKeyBag
    0x7fff69a6d000 -     0x7fff69a97ffb  com.apple.MultitouchSupport.framework (1404.4 - 1404.4) <45374A2A-C0BC-3A70-8183-37295205CDFA> /System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/A/MultitouchSupport
    0x7fff69cfe000 -     0x7fff69d09fff  com.apple.NetAuth (6.2 - 6.2) <B3795F63-C14A-33E1-9EE6-02A2E7661321> /System/Library/PrivateFrameworks/NetAuth.framework/Versions/A/NetAuth
    0x7fff6b59f000 -     0x7fff6b5afffb  com.apple.PerformanceAnalysis (1.194 - 194) <2844933E-B71C-3BE9-9A84-27B29E111F13> /System/Library/PrivateFrameworks/PerformanceAnalysis.framework/Versions/A/PerformanceAnalysis
    0x7fff6d36e000 -     0x7fff6d38cfff  com.apple.ProtocolBuffer (1 - 260) <40704740-4A53-3010-A49B-08D1D69D1D5E> /System/Library/PrivateFrameworks/ProtocolBuffer.framework/Versions/A/ProtocolBuffer
    0x7fff6d556000 -     0x7fff6d562fff  com.apple.xpc.RemoteServiceDiscovery (1.0 - 1205.70.9) <2937CFBF-587C-33A0-B493-FFB4E606A498> /System/Library/PrivateFrameworks/RemoteServiceDiscovery.framework/Versions/A/RemoteServiceDiscovery
    0x7fff6d563000 -     0x7fff6d586ffb  com.apple.RemoteViewServices (2.0 - 125) <592323D1-CB44-35F1-9921-4C2AB8D920A0> /System/Library/PrivateFrameworks/RemoteViewServices.framework/Versions/A/RemoteViewServices
    0x7fff6d587000 -     0x7fff6d59cff3  com.apple.xpc.RemoteXPC (1.0 - 1205.70.9) <C3DB7D30-903A-306C-9DFA-1669D2B60497> /System/Library/PrivateFrameworks/RemoteXPC.framework/Versions/A/RemoteXPC
    0x7fff6eea5000 -     0x7fff6efbaff7  com.apple.Sharing (1050.22.2 - 1050.22.2) <4E3CCDF2-EA26-334F-8EBA-79BD28486C9D> /System/Library/PrivateFrameworks/Sharing.framework/Versions/A/Sharing
    0x7fff6efe5000 -     0x7fff6efe6ff7  com.apple.performance.SignpostNotification (1.2.6 - 2.6) <8F04800F-3570-3392-A24D-B229FF03F7F9> /System/Library/PrivateFrameworks/SignpostNotification.framework/Versions/A/SignpostNotification
    0x7fff6fd2e000 -     0x7fff6ffcaff7  com.apple.SkyLight (1.600.0 - 312.103) <27F91170-846C-3E9E-9B8A-788F27C7DAF5> /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight
    0x7fff70793000 -     0x7fff707a0fff  com.apple.SpeechRecognitionCore (4.6.1 - 4.6.1) <87EE7AB5-6925-3D21-BE00-F155CB457699> /System/Library/PrivateFrameworks/SpeechRecognitionCore.framework/Versions/A/SpeechRecognitionCore
    0x7fff71346000 -     0x7fff713cffc7  com.apple.Symbolication (9.3 - 64033) <C2C55C9A-C264-3044-A953-16457148190A> /System/Library/PrivateFrameworks/Symbolication.framework/Versions/A/Symbolication
    0x7fff71940000 -     0x7fff71948ff7  com.apple.TCC (1.0 - 1) <E1EB7272-FE6F-39AB-83CA-B2B5F2A88D9B> /System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC
    0x7fff71b55000 -     0x7fff71c12ff7  com.apple.TextureIO (3.7 - 3.7) <F8BAC954-405D-3CC3-AB7B-048C866EF980> /System/Library/PrivateFrameworks/TextureIO.framework/Versions/A/TextureIO
    0x7fff71cbc000 -     0x7fff71cbdfff  com.apple.TrustEvaluationAgent (2.0 - 31) <39F533B2-211E-3635-AF47-23F27749FF4A> /System/Library/PrivateFrameworks/TrustEvaluationAgent.framework/Versions/A/TrustEvaluationAgent
    0x7fff71cc3000 -     0x7fff71e72fff  com.apple.UIFoundation (1.0 - 547.5) <86A2FBA7-2709-3894-A3D5-A00C19BAC48D> /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation
    0x7fff7357b000 -     0x7fff7357dffb  com.apple.loginsupport (1.0 - 1) <D1232C1B-80EA-3DF8-9466-013695D0846E> /System/Library/PrivateFrameworks/login.framework/Versions/A/Frameworks/loginsupport.framework/Versions/A/loginsupport
    0x7fff736e4000 -     0x7fff73717ff7  libclosured.dylib (551.4) <3FB6B209-51F4-38DA-B1D8-2EE29D5BDD83> /usr/lib/closure/libclosured.dylib
    0x7fff737d1000 -     0x7fff7380aff7  libCRFSuite.dylib (41) <FE5EDB68-2593-3C2E-BBAF-1C52D206F296> /usr/lib/libCRFSuite.dylib
    0x7fff7380b000 -     0x7fff73816fff  libChineseTokenizer.dylib (28) <53633C9B-A3A8-36F7-A53C-432D802F4BB8> /usr/lib/libChineseTokenizer.dylib
    0x7fff738a8000 -     0x7fff738a9ff3  libDiagnosticMessagesClient.dylib (104) <9712E980-76EE-3A89-AEA6-DF4BAF5C0574> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff738e0000 -     0x7fff73aaaff3  libFosl_dynamic.dylib (17.8) <C58ED77A-4986-31C2-994C-34DDFB8106F0> /usr/lib/libFosl_dynamic.dylib
    0x7fff73ae2000 -     0x7fff73ae2fff  libOpenScriptingUtil.dylib (174) <610F0242-7CE5-3C86-951B-B646562694AF> /usr/lib/libOpenScriptingUtil.dylib
    0x7fff73c19000 -     0x7fff73c1dffb  libScreenReader.dylib (562.18.4) <E239923D-54C9-3BBF-852F-87C09DEF4091> /usr/lib/libScreenReader.dylib
    0x7fff73c1e000 -     0x7fff73c1fffb  libSystem.B.dylib (1252.50.4) <CD555F3B-FDDB-35E5-A2FB-FBBF3D62031A> /usr/lib/libSystem.B.dylib
    0x7fff73cb2000 -     0x7fff73cb2fff  libapple_crypto.dylib (109.50.14) <48BA2E76-BF2F-3522-A54E-D7FB7EAF7A57> /usr/lib/libapple_crypto.dylib
    0x7fff73cb3000 -     0x7fff73cc9ff7  libapple_nghttp2.dylib (1.24) <01402BC4-4822-3676-9C80-50D83F816424> /usr/lib/libapple_nghttp2.dylib
    0x7fff73cca000 -     0x7fff73cf4ff3  libarchive.2.dylib (54) <8FC28DD8-E315-3C3E-95FE-D1D2CBE49888> /usr/lib/libarchive.2.dylib
    0x7fff73cf5000 -     0x7fff73d76fdf  libate.dylib (1.13.1) <178ACDAD-DE7E-346C-A613-1CBF7929AC07> /usr/lib/libate.dylib
    0x7fff73d7a000 -     0x7fff73d7aff3  libauto.dylib (187) <A05C7900-F8C7-3E75-8D3F-909B40C19717> /usr/lib/libauto.dylib
    0x7fff73d7b000 -     0x7fff73e33ff3  libboringssl.dylib (109.50.14) <E6813F87-B5E4-3F7F-A725-E6A7F2BD02EC> /usr/lib/libboringssl.dylib
    0x7fff73e34000 -     0x7fff73e44ff3  libbsm.0.dylib (39) <6BC96A72-AFBE-34FD-91B1-748A530D8AE6> /usr/lib/libbsm.0.dylib
    0x7fff73e45000 -     0x7fff73e52ffb  libbz2.1.0.dylib (38) <0A5086BB-4724-3C14-979D-5AD4F26B5B45> /usr/lib/libbz2.1.0.dylib
    0x7fff73e53000 -     0x7fff73ea9fff  libc++.1.dylib (400.9) <7D3DACCC-3804-393C-ABC1-1A580FD00CB6> /usr/lib/libc++.1.dylib
    0x7fff73eaa000 -     0x7fff73eceff7  libc++abi.dylib (400.8.2) <EF5E37D7-11D9-3530-BE45-B986612D13E2> /usr/lib/libc++abi.dylib
    0x7fff73ed0000 -     0x7fff73ee0fff  libcmph.dylib (6) <A5509EE8-7E00-3224-8814-015B077A3CF5> /usr/lib/libcmph.dylib
    0x7fff73ee1000 -     0x7fff73ef8fcf  libcompression.dylib (47.60.2) <543F07BF-2F2F-37D5-9866-E84BF659885B> /usr/lib/libcompression.dylib
    0x7fff741a3000 -     0x7fff741bbff7  libcoretls.dylib (155.50.1) <D350052E-DC4D-3185-ADBA-BA48EDCEE955> /usr/lib/libcoretls.dylib
    0x7fff741bc000 -     0x7fff741bdff3  libcoretls_cfhelpers.dylib (155.50.1) <B297F5D8-F2FE-3566-A752-E9D998B9C039> /usr/lib/libcoretls_cfhelpers.dylib
    0x7fff74356000 -     0x7fff744e7fff  libcrypto.35.dylib (22.50.2) <97828BFD-4675-35DF-BE2E-C6D1555BB71D> /usr/lib/libcrypto.35.dylib
    0x7fff7468e000 -     0x7fff746e4ff3  libcups.2.dylib (462.2.4) <908099FB-C70E-38FA-9573-88CB98FDDE29> /usr/lib/libcups.2.dylib
    0x7fff74824000 -     0x7fff74824fff  libenergytrace.dylib (16) <A92AB8B8-B986-3CE6-980D-D55090FEF387> /usr/lib/libenergytrace.dylib
    0x7fff74825000 -     0x7fff7483effb  libexpat.1.dylib (16.1.1) <5E1796FA-4041-3187-B5C2-8E6B03D1D72A> /usr/lib/libexpat.1.dylib
    0x7fff7485b000 -     0x7fff74860ff3  libheimdal-asn1.dylib (520.50.6) <E358445A-B84E-31B5-BCCD-7E1397519D96> /usr/lib/libheimdal-asn1.dylib
    0x7fff7488c000 -     0x7fff7497dff7  libiconv.2.dylib (51.50.1) <2FEC9707-3FAF-3828-A50D-8605086D060F> /usr/lib/libiconv.2.dylib
    0x7fff7497e000 -     0x7fff74ba5ffb  libicucore.A.dylib (59180.0.1) <34EBADD6-4092-30EC-90E8-F75241E94D76> /usr/lib/libicucore.A.dylib
    0x7fff74bf2000 -     0x7fff74bf3fff  liblangid.dylib (128) <39C39393-0D05-301D-93B2-F224FC4949AA> /usr/lib/liblangid.dylib
    0x7fff74bf4000 -     0x7fff74c0dffb  liblzma.5.dylib (10) <3D419A50-961F-37D2-8A01-3DC7AB7B8D18> /usr/lib/liblzma.5.dylib
    0x7fff74c0e000 -     0x7fff74c24ff7  libmarisa.dylib (9) <D6D2D55D-1D2E-3442-B152-B18803C0ABB4> /usr/lib/libmarisa.dylib
    0x7fff74cd5000 -     0x7fff74efdff7  libmecabra.dylib (779.7.6) <F462F170-E872-3D09-B219-973D5E99C09F> /usr/lib/libmecabra.dylib
    0x7fff750d5000 -     0x7fff75250fff  libnetwork.dylib (1229.70.2) <E185D902-AC7F-3044-87C0-AE2887C59CE7> /usr/lib/libnetwork.dylib
    0x7fff752d7000 -     0x7fff756c57e7  libobjc.A.dylib (723) <DD9E5EC5-B507-3249-B700-93433E2D5EDF> /usr/lib/libobjc.A.dylib
    0x7fff756d8000 -     0x7fff756dcfff  libpam.2.dylib (22) <7B4D2CE2-1438-387A-9802-5CEEFBF26F86> /usr/lib/libpam.2.dylib
    0x7fff756df000 -     0x7fff75713fff  libpcap.A.dylib (79.20.1) <FA13918B-A247-3181-B256-9B852C7BA316> /usr/lib/libpcap.A.dylib
    0x7fff75792000 -     0x7fff757aeffb  libresolv.9.dylib (65) <E8F3415B-4472-3202-8901-41FD87981DB2> /usr/lib/libresolv.9.dylib
    0x7fff757fd000 -     0x7fff757feff3  libspindump.dylib (252) <D8E27057-E3CC-3D7F-A010-4A87830F6A83> /usr/lib/libspindump.dylib
    0x7fff757ff000 -     0x7fff75992ff7  libsqlite3.dylib (274.8.1) <FCAD6A57-829E-3701-B16E-1833D620E0E8> /usr/lib/libsqlite3.dylib
    0x7fff75b66000 -     0x7fff75bc6ff3  libusrtcp.dylib (1229.70.2) <1E065228-D0E3-3808-9405-894056C6BEC0> /usr/lib/libusrtcp.dylib
    0x7fff75bc7000 -     0x7fff75bcaffb  libutil.dylib (51.20.1) <216D18E5-0BAF-3EAF-A38E-F6AC37CBABD9> /usr/lib/libutil.dylib
    0x7fff75bcb000 -     0x7fff75bd8fff  libxar.1.dylib (400) <0316128D-3B47-3052-995D-97B4FE5491DC> /usr/lib/libxar.1.dylib
    0x7fff75bdc000 -     0x7fff75cc3fff  libxml2.2.dylib (31.11) <C2B5C43F-9C0B-31E6-8EC0-939591EDAC49> /usr/lib/libxml2.2.dylib
    0x7fff75cc4000 -     0x7fff75cecfff  libxslt.1.dylib (15.12) <4A5E011D-8B29-3135-A52B-9A9070ABD752> /usr/lib/libxslt.1.dylib
    0x7fff75ced000 -     0x7fff75cffffb  libz.1.dylib (70) <48C67CFC-940D-3857-8DAD-857774605352> /usr/lib/libz.1.dylib
    0x7fff75d9b000 -     0x7fff75d9fff7  libcache.dylib (80) <092479CB-1008-3A83-BECF-E115F24D13C1> /usr/lib/system/libcache.dylib
    0x7fff75da0000 -     0x7fff75daaff3  libcommonCrypto.dylib (60118.50.1) <029F5985-9B6E-3DCB-9B96-FD007678C6A7> /usr/lib/system/libcommonCrypto.dylib
    0x7fff75dab000 -     0x7fff75db2fff  libcompiler_rt.dylib (62) <968B8E3F-3681-3230-9D78-BB8732024F6E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff75db3000 -     0x7fff75dbcffb  libcopyfile.dylib (146.50.5) <3885083D-50D8-3EEC-B481-B2E605180D7F> /usr/lib/system/libcopyfile.dylib
    0x7fff75dbd000 -     0x7fff75e42fff  libcorecrypto.dylib (562.70.1) <5C26364F-2269-31EC-84AF-0FED2C902E38> /usr/lib/system/libcorecrypto.dylib
    0x7fff75eca000 -     0x7fff75f03ff7  libdispatch.dylib (913.60.2) <232C69BD-022E-3AB9-8807-79F9FA7CB5EC> /usr/lib/system/libdispatch.dylib
    0x7fff75f04000 -     0x7fff75f21ff7  libdyld.dylib (551.4) <81BF3A82-5719-3B54-ABA9-76C82D932CAC> /usr/lib/system/libdyld.dylib
    0x7fff75f22000 -     0x7fff75f22ffb  libkeymgr.dylib (28) <E34E283E-90FA-3C59-B48E-1277CDB9CDCE> /usr/lib/system/libkeymgr.dylib
    0x7fff75f23000 -     0x7fff75f2fff3  libkxld.dylib (4570.71.2) <C3C31E1B-3E74-3828-8429-4D442E26D41C> /usr/lib/system/libkxld.dylib
    0x7fff75f30000 -     0x7fff75f30ff7  liblaunch.dylib (1205.70.9) <B184B521-FF24-3142-AFAF-23D170CF918C> /usr/lib/system/liblaunch.dylib
    0x7fff75f31000 -     0x7fff75f35ffb  libmacho.dylib (906) <1902A611-081A-3452-B11E-EBD1B166E831> /usr/lib/system/libmacho.dylib
    0x7fff75f36000 -     0x7fff75f38ff3  libquarantine.dylib (86) <26C0BA22-8F93-3A07-9A4E-C8D53D2CE42E> /usr/lib/system/libquarantine.dylib
    0x7fff75f39000 -     0x7fff75f3aff3  libremovefile.dylib (45) <711E18B2-5BBE-3211-A916-56740C27D17A> /usr/lib/system/libremovefile.dylib
    0x7fff75f3b000 -     0x7fff75f52fff  libsystem_asl.dylib (356.70.1) <39E46A6F-B228-3E78-B83E-1779F9707A39> /usr/lib/system/libsystem_asl.dylib
    0x7fff75f53000 -     0x7fff75f53fff  libsystem_blocks.dylib (67) <17303FDF-0D2D-3963-B05E-B4DF63052D47> /usr/lib/system/libsystem_blocks.dylib
    0x7fff75f54000 -     0x7fff75fddff7  libsystem_c.dylib (1244.50.9) <1187BFE8-4576-3247-8177-481554E1F9E7> /usr/lib/system/libsystem_c.dylib
    0x7fff75fde000 -     0x7fff75fe1ffb  libsystem_configuration.dylib (963.50.8) <DF6B5287-203E-30CB-9947-78DF446C72B8> /usr/lib/system/libsystem_configuration.dylib
    0x7fff75fe2000 -     0x7fff75fe5ffb  libsystem_coreservices.dylib (51) <486000D3-D8CB-3BE7-8EE5-8BF380DE6DF7> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff75fe6000 -     0x7fff75fe7fff  libsystem_darwin.dylib (1244.50.9) <09C21A4A-9EE0-388B-A9D9-DFF8F6758791> /usr/lib/system/libsystem_darwin.dylib
    0x7fff75fe8000 -     0x7fff75feeff7  libsystem_dnssd.dylib (878.70.2) <3290768B-54DE-3AB6-B155-AC0950AC5564> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff75fef000 -     0x7fff76038ff7  libsystem_info.dylib (517.30.1) <AB634A98-B8AA-3804-8436-38261FC8EC4D> /usr/lib/system/libsystem_info.dylib
    0x7fff76039000 -     0x7fff7605fff7  libsystem_kernel.dylib (4570.71.2) <F22B8D73-69D8-36D7-BF66-7F9AC70C08C2> /usr/lib/system/libsystem_kernel.dylib
    0x7fff76060000 -     0x7fff760abfcb  libsystem_m.dylib (3147.50.1) <8CFB51C9-B422-3379-8552-064C63943A23> /usr/lib/system/libsystem_m.dylib
    0x7fff760ac000 -     0x7fff760cbfff  libsystem_malloc.dylib (140.50.6) <7FD43735-9DDD-300E-8C4A-F909A74BDF49> /usr/lib/system/libsystem_malloc.dylib
    0x7fff760cc000 -     0x7fff761fcff7  libsystem_network.dylib (1229.70.2) <5E86B2DE-9E15-3354-8714-4094ED5F698D> /usr/lib/system/libsystem_network.dylib
    0x7fff761fd000 -     0x7fff76207ffb  libsystem_networkextension.dylib (767.70.1) <D23EAFC1-E8BD-34D5-969C-6E45A1C3B4E4> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff76208000 -     0x7fff76211ff3  libsystem_notify.dylib (172) <08012EC0-2CD2-34BE-BF93-E7F56491299A> /usr/lib/system/libsystem_notify.dylib
    0x7fff76212000 -     0x7fff76219ff7  libsystem_platform.dylib (161.50.1) <6355EE2D-5456-3CA8-A227-B96E8F1E2AF8> /usr/lib/system/libsystem_platform.dylib
    0x7fff7621a000 -     0x7fff76225fff  libsystem_pthread.dylib (301.50.1) <0E51CCBA-91F2-34E1-BF2A-FEEFD3D321E4> /usr/lib/system/libsystem_pthread.dylib
    0x7fff76226000 -     0x7fff76229fff  libsystem_sandbox.dylib (765.70.1) <553DFCC6-9D31-3B9C-AB7C-30F6F265786D> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff7622a000 -     0x7fff7622bff3  libsystem_secinit.dylib (30) <DE8D14E8-A276-3FF8-AE13-77F7040F33C1> /usr/lib/system/libsystem_secinit.dylib
    0x7fff7622c000 -     0x7fff76233ff7  libsystem_symptoms.dylib (820.60.2) <585BDFA2-D54D-39D0-8046-44E824DABD43> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff76234000 -     0x7fff76247fff  libsystem_trace.dylib (829.70.1) <3A6CB706-8CA6-3616-8AFC-14AAD7FAF187> /usr/lib/system/libsystem_trace.dylib
    0x7fff76249000 -     0x7fff7624eff7  libunwind.dylib (35.3) <BEF3FB49-5604-3B5F-82B5-332B80023AC3> /usr/lib/system/libunwind.dylib
    0x7fff7624f000 -     0x7fff7627cff7  libxpc.dylib (1205.70.9) <0BC7AD67-671D-31D4-8B88-C317B8379598> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 2
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 1336007
    thread_create: 0
    thread_set_state: 157

VM Region Summary:
ReadOnly portion of Libraries: Total=460.2M resident=0K(0%) swapped_out_or_unallocated=460.2M(100%)
Writable regions: Total=232.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=232.4M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        2 
Activity Tracing                   256K        2 
CG backing stores                 1456K        3 
CG image                           328K        2 
CoreGraphics                         8K        2 
CoreImage                           32K        5 
CoreUI image data                  148K        2 
CoreUI image file                  300K        5 
Foundation                           4K        2 
Kernel Alloc Once                    8K        2 
MALLOC                           181.5M       49 
MALLOC guard page                   48K       13 
Memory Tag 242                      12K        2 
OpenGL GLSL                        256K        4 
STACK GUARD                       56.1M       15 
Stack                             15.6M       15 
VM_ALLOCATE                       32.1M       30 
__DATA                            28.5M      260 
__FONT_DATA                          4K        2 
__GLSLBUILTINS                    2588K        2 
__LINKEDIT                       208.0M       10 
__TEXT                           252.2M      265 
__UNICODE                          560K        2 
mapped file                       48.8M       17 
shared memory                      716K       15 
===========                     =======  ======= 
TOTAL                            829.4M      703 

Model: MacBookPro14,3, BootROM 190.0.0.0.0, 4 processors, Intel Core i7, 3.1 GHz, 16 GB, SMC 2.45f0
Graphics: Intel HD Graphics 630, Intel HD Graphics 630, Built-In
Graphics: Radeon Pro 560, Radeon Pro 560, PCIe
Memory Module: BANK 0/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C31473332443450472D30393320
Memory Module: BANK 1/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C31473332443450472D30393320
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x173), Broadcom BCM43xx 1.0 (7.77.37.31.1a9)
Bluetooth: Version 6.0.7f10, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: SAMSUNG_Android
USB Device: USB2.0 Hub
USB Device: USB-C Digital AV Multiport Adapter
USB Device: iBridge
USB Device: USB3.0 Hub
Thunderbolt Bus: MacBook Pro, Apple Inc., 39.2
Thunderbolt Bus: MacBook Pro, Apple Inc., 39.2
```

### LINKED ISSUE #37713: Mono version does not respond and causes high CPU usage until reboot on first launch
**Godot version:**
Godot_v3.2.1-stable_mono

**OS/device including version:**
maxOS Catalina (10.15.2)/MacBook Pro 15 inch, 2017

**Issue description:**
The mono version of Godot causes high CPU usage on first launch after Developer Tools prompt. In console, "- IOAudioEngineUserClient[<private>]::performWatchdogOutput(<private>, ...) - (...)" can constantly be seen, Activity Monitor is prevented from functioning until machine reboot. CPU usage also jumps high and stays until machine reboot. 

**Steps to reproduce:**
Launch Godot_mono 3.2.1 for the first time, and authenticate with password for the Developer Tools prompt

**Minimal reproduction project:**
N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Ignore process serial number (`-psn_...`) command line argument passed by macOS Gatekeeper.

PSN is only passed on the first start of the downloaded app (.app bundle with `com.apple.quarantine` extended file attribute), confuses Godot, causing it to load non-existent project instead of project manager.

Fixes #37713
Probably fixes #37446, fixes #35383 and fixes #36616?

### CODE REVIEW

File: main/main.cpp [hunk 1]
```diff
@@ -478,6 +478,12 @@ Error Main::setup(const char *execpath, int argc, char *argv[], bool p_second_ph
 
 	I = args.front();
 	while (I) {
+#ifdef OSX_ENABLED
+		if (I->get().begins_with("-psn_")) {
```
Comment (Calinou) [inline main/main.cpp:482]:
```suggestion
		// Ignore the process serial number argument passed by macOS Gatekeeper.
		// Otherwise, Godot would try to open a nonexistent project on the first start and abort.
		if (I->get().begins_with("-psn_")) {
```

**Review by Calinou — COMMENTED** [review]
There should be a comment so we know why this was added in the future :slightly_smiling_face:

**Comment by akien-mga** [comment]
It's really a weird design for macOS to arbitrarily pass arguments to thirdparty processes that are not designed to handle them... I'm sure we're not the only ones to have issues with that (though our argument parsing is particularly bad right now, but we'll get to properly fixing #20000 eventually :)).

Anyway, this is hacky but seems like a good solution for now.

**Comment by akien-mga** [comment]
Thanks!

**Comment by bruvzg** [comment]
> It's really a weird design for macOS to arbitrarily pass arguments to thirdparty processes that are not designed to handle them... 

This was the normal way to pass PSN to the Carbon apps (API deprecated in 10.8 and removed in 10.15), probably some of the old code accidentally get into the Gatekeeper.

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.
