### PR TITLE
Ignore empty lines when uncommenting code

### LINKED ISSUE #81474: Empty lines should be ignored when comment/uncomment code
### Godot version

Godot v4.2.dev (fc99492d3) 

### System information

Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.3699) - 12th Gen Intel(R) Core(TM) i7-12700F (20 Threads)

### Issue description

1. Inserting a newline in the commented code and then uncomment all of them won't work, godot will think the new line (usually just a '\t' or '\n') is uncommented, so it assumes the whole code block is uncommented and will comment all the code again.
2.  Comment will work when comment a empty line, by empty I mean the line only consist of '\t' '\n' and ' '

### Steps to reproduce

For 1, write some code like this:
```
	var a = 1
	var b = 2
```
comment them by ctrl + k, and press enter after `#var a = 1` to make a new line, it should look like this:
```
	#var a = 1
		
	#var b = 2
```
And uncomment all the three lines together, you will get this instead of uncommentting all the lines
```
	##var a = 1
#
	##var b = 2
```

For 2, it's trivial to reproduce.

### Minimal reproduction project

Any project should work.

I has already fixed it in my local branch, but I think it need mroe disscussion about which behavior is intented and which is not. 
I can understand the behaviour of point 2 to some extent but point 1 really brings inconvenience. 

After the disscussion, I can update my fix and create a pr for it if necessary.

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes #81474

### CODE REVIEW

File: editor/code_editor.cpp [hunk 1]
```diff
@@ -1510,7 +1518,7 @@ void CodeTextEditor::toggle_inline_comment(const String &delimiter) {
 		// Comment/uncomment.
 		for (int line = from; line <= to; line++) {
 			String line_text = text_editor->get_line(line);
-			if (line_text.strip_edges().is_empty()) {
+			if (line_text.strip_edges().is_empty() && !is_commented) {
```
Comment (Paulb23) [inline editor/code_editor.cpp:1521]: Given this is no longer always adding / removing, do we need to change the caret readjustment below? 
`int offset = (is_commented ? -1 : 1) * delimiter.length();` particularly with multiple carets.

Comment (jsjtxietian) [reply editor/code_editor.cpp:1521]: Great Catch! I think it needs more investigation, I will take a look.

Comment (jsjtxietian) [reply editor/code_editor.cpp:1521]: I did some test and it seems fine because affected lines are empty lines so nothing weird happens. Could you help me to construct a scenario where my code fails ? I can take a look and decide how to update my code. Thanks !

**Comment by jsjtxietian** [comment]
I did some test with vscode and have updated my code a little bit according to vscode's default behaviour, the code works this way now:

When commenting/uncommenting code, empty lines do not affect godot's decision of whether the selected code is commented or not,  unless they are all empty lines,  in that case I treat them as uncommented code.

File: editor/code_editor.cpp (hunk 1 above)
Comment (Paulb23) [reply editor/code_editor.cpp]: Sure I'm thinking of a situation like this:
```
1. |#some test
2. #code
3.    |      |
```
In this case there is one caret with a selection on lines 1-3. 
The second caret is on line 3.

When toggling comment in this situation, I would expect that the carets on line 3 will not change position.

File: editor/code_editor.cpp [hunk 2]
```diff
@@ -1487,14 +1487,22 @@ void CodeTextEditor::toggle_inline_comment(const String &delimiter) {
...
 		bool is_commented = true;
+		bool is_all_empty = true;
 		for (int line = from; line <= to; line++) {
 			// `+ delimiter.length()` here because comment delimiter is not actually `in comment` so we check first character after it
 			int delimiter_idx = text_editor->is_in_comment(line, text_editor->get_first_non_whitespace_column(line) + delimiter.length());
-			if (delimiter_idx == -1 || text_editor->get_delimiter_start_key(delimiter_idx) != delimiter) {
+			// Empty lines should not be counted.
+			bool is_empty = text_editor->get_line(line).strip_edges().is_empty();
+			is_all_empty = is_all_empty && is_empty;
+			if ((delimiter_idx == -1 || text_editor->get_delimiter_start_key(delimiter_idx) != delimiter) && !is_empty) {
```
Comment (AThousandShips) [inline editor/code_editor.cpp:1497]:
```suggestion
			if (!is_empty && (delimiter_idx == -1 || text_editor->get_delimiter_start_key(delimiter_idx) != delimiter)) {
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
