### PR TITLE
[Web] Detect host OS and use macOS keys on Mac hosts.

### LINKED ISSUE #68653: TextEdit uses wrong copy/paste shortcuts on Mac in HTML5 build
### Godot version

3.5.1 stable official

### System information

macOS 12.1

### Issue description

TextEdit uses wrong copy/paste shortcuts on Mac in htmpl5 build

### Steps to reproduce

Create any projects with TextEdit, run as HTML on macOS. Right-click to see shortcuts being ctrl+C ctrl+v instead of using Command

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by bruvzg**
- Adds `web_android`, `web_ios`, `web_linuxbsd`, `web_macos`, and `web_windows` OS feature tags based on the host platform.
- Uses runtime checks/overrides for the default keys based on `macos` and `web_macos` tags instead of `ifdef`s.

Fixes https://github.com/godotengine/godot/issues/68653

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: platform/web/os_web.cpp [hunk 1]
```diff
@@ -111,7 +111,7 @@ Error OS_Web::create_process(const String &p_path, const List<String> &p_argumen
 		args.push_back(E);
 	}
 	String json_args = Variant(args).to_json_string();
-	int failed = godot_js_os_execute(json_args.utf8().get_data());
+	int failed = godot_js_os_execute(json_args.to_lower().utf8().get_data());
```
Comment (Faless) [inline platform/web/os_web.cpp:114]: Is this on purpose? Why the to_lower?

**Review by Faless — CHANGES_REQUESTED** [review]

File: platform/web/os_web.cpp (hunk 1 above)
Comment (bruvzg) [reply platform/web/os_web.cpp]: > Is this on purpose?

No, it should not be there. Removed.

File: platform/web/js/libs/library_godot_os.js [hunk 2]
```diff
@@ -291,6 +291,27 @@ const GodotOS = {
 		});
 	},
 
+	godot_js_os_has_feature__sig: 'ii',
+	godot_js_os_has_feature: function (p_ftr) {
+		const ftr = GodotRuntime.parseString(p_ftr);
+		if (ftr === 'web_macos') {
+			return (navigator.appVersion.indexOf('Mac') !== -1) ? 1 : 0;
```
Comment (Faless) [inline platform/web/js/libs/library_godot_os.js:298]: `navigator.appVersion` is deprecated: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/appVersion
We should probably use [`navigator.userAgent`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgent) instead like done in [`GodotInputGamepads.get_guid`](https://github.com/godotengine/godot/blob/master/platform/web/js/libs/library_godot_input.js#L122).

Comment (bruvzg) [reply platform/web/js/libs/library_godot_os.js]: Changed it to `navigator.userAgent`.

**Review by Faless — APPROVED** [review]
LGTM, :rocket: :apple:

**Comment by akien-mga** [comment]
Thanks!
