### PR TITLE
Fix `button_up` and `button_down` signals with focus changes or multiple inputs

### LINKED ISSUE #52578: Unexpected behavior of `button_up` signal when focus is changed while `ui_accept` is pressed
### Godot version

3.3.3

### System information

Windows 10

### Issue description

I'm seeing unexpected behavior with the `button_up` signal when focus is switched between buttons while holding a `ui_accept` button (and then releasing `ui_accept` after focus has changed). If I start holding `ui_accept`, a `button_down` signal is fired for the button under focus. This is as expected. However, if I use the arrow keys to navigate to a different button, and afterwards release the `ui_accept` button, no `button_up` signal ever gets fired for the button I initially selected, and a `button_up` signal is instead fired for the button that I've navigated focus to.

This behavior is unexpected to me for a few reasons:

1.  If I instead press a button with the mouse, then change focus, then release the mouse, I do not get the same signal behavior. Instead, `button_down` and `button_up` both fire for the original button I selected (even if I've moved the mouse around on the screen to a new location). This is the more expected result in my opinion.
2. This behavior does not seem to correspond with the behavior of the `pressed` or `toggled` signals, which do not fire when I start pressing one button but navigate to another button before releasing `ui_accept`.
3. Conceptually, I don't think it makes sense that it is possible for the `button_up` signal to fire for a button which has never been pressed down.

Instead of the current behavior, I would expect the following signal behavior when the steps described above are executed:

`button_up` signals always fire on the same button from which the initial `button_down` signal was triggered, firing once the `ui_accept` button has been released. In my opinion, this would be the most desirable behavior, to ensure consistency of `button_up` signal behavior between input types (matches current behavior when button is selected with a mouse and focus is changed).

### Steps to reproduce

Attached a project with minimal reproduction steps (featuring two buttons, which log to the console whenever they receive `button_up` or `button_down` signals). In that project, if you focus the "Middle Button", hold a `ui_accept` button like spacebar, then navigate down to the "Bottom Button" while holding the `ui_accept` button, and release the accept button afterwards, the following events will fire.

```
Middle Button button_down has been triggered

Bottom Button button_up has been triggered
```

In my opinion, the expected output for this set of actions would instead be

```
Middle Button button_down has been triggered

Middle Button button_up has been triggered
```

### Minimal reproduction project

[repro.zip](https://github.com/godotengine/godot/files/7148228/repro.zip)

### PR DESCRIPTION
**Pull request by wlsnmrk**
Proposed fix for #52578. Adds a flag to guard `button_up` and `button_down` events based on whether `button_down` has been previously emitted while focused, and emits `button_up` if focus is lost after `button_down` is emitted. 

Behavior changes are that buttons:
* emit `button_up` signals if they have emitted `button_down`, have not yet emitted `button_up`, and lose focus
* do not emit `button_up` if they gain focus while a `ui_accept` key is still pressed and it is subsequently released
* do not emit multiple up/down signals if multiple press actions overlap (e.g., space and enter keys)

This is based on work in #52621, but seems to avoid the mouse-event regressions identified for that PR. In particular:
* pressed buttons with `keep_pressed_outside` correctly become unpressed when the mouse click is released outside the button area
* pressed buttons without `keep_pressed_outside` do not become re-pressed if the mouse click is released outside the button area and the cursor subsequently re-enters the button area

button-focus-event-bug-cropped

I know there are pitfalls and subtleties around this behavior, so I'm happy to hear if this needs to be changed in some way - or it's fine if this approach doesn't work for some reason I didn't anticipate.

I'm attaching a test project I used to check for introduced bugs, in case it's helpful - it's not exhaustive, but it has many different kinds of buttons with different options set to see if their behavior remains correct. 
[ButtonDownUpFocusBug.zip](https://github.com/godotengine/godot/files/12571799/ButtonDownUpFocusBug.zip)

*Bugsquad edit:*
- Fixes https://github.com/godotengine/godot/issues/52578

### CODE REVIEW

**Comment by KoBeWi** [comment]
> do not emit multiple up/down signals if multiple press actions overlap (e.g., space and enter keys)

This doesn't seem to work. Multiple signals are still being emitted.

**Comment by wlsnmrk** [comment]
Thanks for checking! Can I ask if there's a particular project or setup that's getting you multiple signals? I just checked and it's only emitting one down and one up signal for me:

https://github.com/godotengine/godot/assets/23439518/912bba30-894d-49b1-8496-d56a674de013

You can't see my mouse and keyboard here, but the first press is an overlapped mouse click and spacebar, the second is mouse click and enter, and the third is spacebar and enter, and you can see in the log file at the end that they produced one down and one up signal each.

**Comment by KoBeWi** [comment]
Ah I think I misunderstood. What I did was press and hold Space and then press Enter. It emits the button up signal. Now I noticed that button ups and downs still match, so indeed it's correct.

**Comment by wlsnmrk** [comment]
Ah, yeah, if you meant that the up signal should only be emitted in response to the exact input that triggered the down signal (or focus loss), then I think we'd have to modify the code to track the original input. If you're satisfied with the current behavior, I'll leave it alone - otherwise let me know if it ought to be changed to wait until the original input is released.

File: scene/gui/base_button.cpp [hunk 1]
```diff
@@ -145,9 +150,10 @@ void BaseButton::_toggled(bool p_pressed) {
 }
 
 void BaseButton::on_action_event(Ref<InputEvent> p_event) {
-	if (p_event->is_pressed()) {
+	if (p_event->is_pressed() && !status.pressed_down_with_focus) {
```
Comment (KoBeWi) [inline scene/gui/base_button.cpp:153]:
```suggestion
	if (!status.pressed_down_with_focus && p_event->is_pressed()) {
```
Cheaper check first. Same below.

**Review by KoBeWi — APPROVED** [review]

**Review by Hilderin — APPROVED** [review]
Tested and seems to work as expected. Thanks!

**Comment by akien-mga** [comment]
Thanks!
