### PR TITLE
Fix incorrect animation section when playing a custom timeline with stretched time scale.

### LINKED ISSUE #118101: Blendtree Animation Custom Timeline/Stretch Time Scale no longer works in 4.6.2
### Tested versions

-Reproducible in 4.6.2 stable, 4.6.2 RC2 (no other 4.6.2 versions tested)
-Not reproducible 4.6.1, 4.6.0.

### System information

Windows 11, RTX 3090, Godot 4.6.2 stable

### Issue description

After updating from 4.6.1 stable to 4.6.2 the option "Use custom timeline" in blendtree's Animation nodes seems to crop the animation even if "Stretch time line" is selected. 

Not all animation channels types seem to be affected by this bug.

### Steps to reproduce

I'm including a simple project that exposed the bug, a simple 1 second animation loop calls a method that prints a string at 0.75 seconds. The animation is played through an animation node in a Blendtree with a custom timeline of length 0.50 and the option "Stretch Time Scale" activated.

The expected behavior, and the one happening in older version, is that the string will be printed on the console at 0.75s/2 = 0.375s, instead the string is never printed and any method call past the 0.5 mark will be ignored.

### Minimal reproduction project (MRP)

[b-tree-bug.zip](https://github.com/user-attachments/files/26426218/b-tree-bug.zip)

### PR DESCRIPTION
**Pull request by chocola-mint**
Fixes https://github.com/godotengine/godot/issues/118101

The PR basically sets the animation section's end to be the animation length when AnimationNodeAnimation's `use_custom_timeline` and `stretch_time_scale` are both enabled. (This effectively just plays the original animation at a different speed)

In https://github.com/godotengine/godot/pull/91765, I incorrectly set the animation section's end to be the custom timeline's length. However, AnimationNodeAnimation had been relying on the buggy behavior in https://github.com/godotengine/godot/issues/116002, which allowed it to evaluate keys after the incorrect animation section, which is why this error managed to stay hidden.

https://github.com/godotengine/godot/pull/116046 fixed the buggy behavior, revealing the error in AnimationNodeAnimation.

### CODE REVIEW

**Review by TokageItLab — APPROVED** [review]

File: scene/animation/animation_blend_tree.cpp [hunk 1]
```diff
@@ -107,12 +107,21 @@ AnimationNode::NodeTimeInfo AnimationNodeAnimation::_process(ProcessState &p_pro
...
+	double playback_end;
 	Animation::LoopMode cur_loop_mode;
 	if (use_custom_timeline) {
 		cur_len = timeline_length;
+		if (stretch_time_scale) {
+			// When time scale is stretched, the entire animation is played anyway using a time scale based on the timeline length.
+			// Therefore, the end of the animation section is the animation length.
+			playback_end = anim_size;
+		} else {
+			playback_end = timeline_length;
```
Comment (TokageItLab) [inline scene/animation/animation_blend_tree.cpp:119]: Isn't it necessary to take custom_timeline's `start_offset` into account?
