### PR TITLE
Fix crash when deallocating named colors map

### LINKED ISSUE #18216: ColorN() can cause game to crash before SceneTree.quit() completes.
Running this in 2.1.4 and 2.1.5 for Windows.

To reproduce this, you need a scene running in game that has a GDScript where one of the script scope variables request a ColorN() Color.  

Export the project and run it.  When exiting it will crash before closing.  This only happens in the exported .exe.

```
extends Node2D

var color = ColorN("white")
```

Color8() appears to be fine, and Godot 3.0.2 doesn't have this issue, but depending on the issue maybe it manifests itself in some other way.  Is the string argument passed in leaking in some way?

Attached a sample project, just export it, run it, and quit it.

[ColorN Crash.zip](https://github.com/godotengine/godot/files/1913109/ColorN.Crash.zip)

### PR DESCRIPTION
**Pull request by bojidar-bg**
Fixes #18216.
Not sure why it doesn't happen on 3.0, but it can be cherrypicked there as well.

The code is a bit of a hack, unfortunately.The code is a bit of a hack, unfortunately.

### CODE REVIEW

File: main/main.cpp [hunk 1]
```diff
@@ -1649,6 +1651,8 @@ void Main::cleanup() {
 		memdelete(script_debugger);
 	}
 
+	Color::_clear_named();
```
Comment (akien-mga) [inline main/main.cpp]: Maybe this could go in `unregister_core_types()` instead? It's already where `CoreStringNames` and `StringName` gets cleaned up.

Comment (bojidar-bg) [reply main/main.cpp]: Eh, didn't notice we already have a place for those, going to move it there :)

Comment (akien-mga) [reply main/main.cpp]: Ping me when it's updated, I'm waiting for this last fix to build 2.1.5 RC2.

**Comment by akien-mga** [comment]
Thanks! Might be worth PR'ing for master and then cherry-picking for 3.0 too, just to be sure.
