### PR TITLE
check for empty string TextServer _string_to_upper

### LINKED ISSUE #69888: UI Label Uppercase
### Godot version

4.0 beta 8

### System information

Linux PopOS

### Issue description

When working with a UI Label Node if uppercase is enabled but the text field is empty U_STRING_NOT_TERMINATED_WARNING is thrown.

Expected behavior would be that uppercase would not do anything if the text field were empty.

### Steps to reproduce

Create a Node, enable the uppercase option and run the scene.

Alternatively via code one can do:
```
extends Control


func _ready():
	var new_label = Label.new()
	new_label.uppercase = true
	new_label.text = ""
	self.add_child(new_label)
```

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by evan-gordon**
Adds a check to TextServerAdvanced.::_string_to_upper
Now properly does nothing when the string is empty.

Closes #69888

### CODE REVIEW

File: modules/text_server_adv/text_server_adv.cpp [hunk 1]
```diff
@@ -6196,6 +6196,9 @@ String TextServerAdvanced::_strip_diacritics(const String &p_string) const {
 }
 
 String TextServerAdvanced::_string_to_upper(const String &p_string, const String &p_language) const {
+	if (p_string.size() == 0) {
```
Comment (akien-mga) [inline modules/text_server_adv/text_server_adv.cpp:6199]: Could use `p_string.is_empty()` instead, which is the preferred way to check this (does the same internally).

Could also be relevant for `_string_to_lower`.

*Note:* Please make modifications by _amending_ the commit so that it stays as a single commit (see [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request)).

**Review by bruvzg — APPROVED** [review]
The same should be done for `_string_to_lower` as well.

**Review by bruvzg — APPROVED** [review]

File: modules/text_server_adv/text_server_adv.cpp (hunk 1 above)
Comment (evan-gordon) [reply modules/text_server_adv/text_server_adv.cpp]: Thanks for the suggestions, changed to using is_empty() and added the same change to _string_to_lower

**Comment by evan-gordon** [comment]
> The same should be done for `_string_to_lower` as well.

Thanks for the suggestion, fixed.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
