### PR TITLE
Ensure optional CopyEffects variants are loaded last.

### LINKED ISSUE #84841: Toggling XR/Shaders/Enabled caused errors spam when using WorldEnvironment
### Godot version

4.2 beta 5

### System information

windows 10

### Issue description

when choosing the option in the editor 
project settings / XR - shaders / enable on , off
It works the frist time, 
when choosing back to off ( default ) the entire screen stays black

### Steps to reproduce

- add a colorRect with a shader on
- add node WorldEnvironment, choose new enviorement, canvas
- go into project settings / XR - shaders / turn it on ( restart )
- now turn it off
- delete WorldEnvironment node, to clear the black screen, add WorldEnvironment again / canvas
- the error presists in memory condition shader null()

XR_option01

XR_option00

XR_option02

### Minimal reproduction project

[XR_shaderOption.zip](https://github.com/godotengine/godot/files/13334861/XR_shaderOption.zip)

### PR DESCRIPTION
**Pull request by BastiaanOlij**
This is a quick fix for #84841

There is an issue with our shader cache when there are disabled variants, it does not seem to deal with these properly (though this seems to be a recently introduced issue, possibly due to shader groups being added in 4.2).
For the most part this isn't a problem as the missing variants end up being recompiled and the cache fixes itself. The exception are our copy effects where a new copy type was added after the optional variants.
There is a more serious bug in the shader cache that causes all variants to be deleted (even the ones loaded properly) but in such a way that the Godot can no longer compile new versions.

This PR works around the problem by moving this new variant before the optional variants. This fixes the immediate problem.

We will need to fix the cache logic at some point but that will be a 4.3 fix. 

*Bugsquad edit:*
- Fixes #84841

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
Just for future reference, we'll need to investigate this further. But I think the problem is that disabled variants are simply not added to the cache at all. So now it's trying to load the `COPY_TO_FB_SET_COLOR` variant as if it's the `COPY_TO_FB_MULTIVIEW`.
We'll probably need to save something into the cache to indicate that slow contains a disabled variant, so that `COPY_TO_FB_SET_COLOR` is saved in the correct slot.

File: servers/rendering/renderer_rd/effects/copy_effects.h [hunk 1]
```diff
@@ -172,11 +172,11 @@ class CopyEffects {
 		COPY_TO_FB_COPY,
 		COPY_TO_FB_COPY_PANORAMA_TO_DP,
 		COPY_TO_FB_COPY2,
+		COPY_TO_FB_SET_COLOR,
```
Comment (akien-mga) [inline servers/rendering/renderer_rd/effects/copy_effects.h:176]: I would add a comment here to clarify that the variants below are optional and should come last in the enum.

Comment (BastiaanOlij) [reply servers/rendering/renderer_rd/effects/copy_effects.h:176]: Done, let me know if you agree with the text :)

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Review by clayjohn — APPROVED** [review]
Seems fine to me. As-is, I think this is a very low risk change. 

That said, I think it is a band-aid to an underlying problem with how we deal with disabling/enabling XR variants. So we should probably revisit this after 4.2 releases

**Comment by akien-mga** [comment]
Thanks!
