### PR TITLE
Make AABB change trigger bounding box update

### LINKED ISSUE #42388: Gizmo not updated immediately when changing mesh size
**Godot version:**

64d3827

**Steps to reproduce:**
1. Create a MeshInstance3D
2. Add a CubeMesh (or any mesh really)
3. Change its size
4.
rumhJZygRm

Loosely related to #31633

### PR DESCRIPTION
**Pull request by DavidSichma**
closes #42388

Changing AABB (e.g., by modifying mesh) will now trigger a redraw of the bounding box.

### CODE REVIEW

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -2405,18 +2405,18 @@ void Node3DEditorViewport::_notification(int p_what) {
 			}
 
 			Transform t = sp->get_global_gizmo_transform();
+			VisualInstance3D *vi = Object::cast_to<VisualInstance3D>(sp);
+			AABB naabb = vi ? vi->get_aabb() : _calculate_spatial_bounds(sp);
```
Comment (akien-mga) [inline editor/plugins/node_3d_editor_plugin.cpp:2409]: What does `naabb` mean? If it's for "new AABB", please use `new_aabb` to make the code self-documenting.

**Comment by capnm** [comment]
Works for me on 3.2 branch :+1:

**Review by JFonS — APPROVED** [review]
Looks good :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
