### PR TITLE
[Web] Fix file locked issue when exporting to Web.

### LINKED ISSUE #65660: Export to Web fails from Windows (file in use and can't be overwritten)
### Godot version

4.0 alpha 16

### System information

Windows 11

### Issue description

image
All other exports work fine, but web produces this error each time. I've tried changing what directory it saves to, no difference.

### Steps to reproduce

Export, add, Web, export project.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by zaevi**
Fixes #65660 directly by closing file handle manually before writing.

### CODE REVIEW

File: platform/web/export/export_plugin.cpp [hunk 1]
```diff
@@ -485,6 +485,7 @@ Error EditorExportPlatformWeb::export_project(const Ref<EditorExportPreset> &p_p
 	}
 	html.resize(f->get_length());
 	f->get_buffer(html.ptrw(), html.size());
+	f.unref(); // close file.
```
Comment (bruvzg) [inline platform/web/export/export_plugin.cpp:488]: Can `html_path` be the same as `p_path`? It seems to be reading and writing a different files.

**Review by bruvzg — APPROVED** [review]

File: platform/web/export/export_plugin.cpp (hunk 1 above)
Comment (zaevi) [reply platform/web/export/export_plugin.cpp:488]: It changes if use a custom html shell

**Comment by akien-mga** [comment]
Thanks!
