### PR TITLE
Fix: Sync built-in script memory before signal connection

### LINKED ISSUE #107606: Signal is not connected when creating new method with binds
### Tested versions

4.4.1
4.5 dev1-5

### System information

W10

### Issue description

When you connect a signal and add some binds, the connection will not be created if the method you selected did not exist. The method is created though, so you can try connecting again and it will work.

This gets printed in the output:
```
 Cannot connect to 'method': the provided callable is not valid
```
This is the same error as in #83549, but under different circumstances.

### Steps to reproduce

1. Add node with a script
2. Go to Node dock -> Signals
3. Double click a signal
4. Select some new method as target
5. Enable Advanced and add some binds
6. Press Connect
7. The method is created
8. The signal is not connected

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by tciviero**
When creating both the callback function with binds and/or unbinds on a built-in script and the connection to a signal on the connections dialog, the `_add_callback` did not reload the script memory in the case of built-in scripts. Consequently, the `Object::connect` method could not find the callback, leading to a connection error.

This fix makes `_add_callback` perform an in-memory reload of the built-in script using `apply_code()` and `reload(true)`. This resolves the issue while maintaining the "user-in-control" philosophy by avoiding a forced save to disk without the user's explicit consent.

Fixes #107606

### CODE REVIEW

**Review by kitbdev — APPROVED** [review]
Fixes the issue, makes sense.

Needs rebase (`se` variable name changed to `ste`.)

**Comment by Repiteo** [comment]
Could you squash your commits? See our [pull request guidelines](https://contributing.godotengine.org/en/latest/organization/pull_requests/creating_pull_requests.html#the-interactive-rebase) for more information

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉

File: editor/script/script_editor_plugin.cpp [hunk 1]
```diff
@@ -2620,6 +2620,9 @@ void ScriptEditor::_add_callback(Object *p_obj, const String &p_function, const
 		// Save the current script so the changes can be picked up by an external editor.
 		if (!scr.ptr()->is_built_in()) { // But only if it's not built-in script.
 			save_current_script();
+		} else {
+			ste->apply_code();
+			scr->reload(true);
```
Comment (KoBeWi) [inline editor/script/script_editor_plugin.cpp:2625]: This will cause errors when using tool scripts:
```
 ERROR: Cannot reload script while instances exist.
```
It should be `reload(false)` if it works.

Comment (kitbdev) [reply editor/script/script_editor_plugin.cpp:2625]: It looks like this is actually preexisting, it happens in 4.7.dev1 too. It errors on selecting the node in the dialog, not when this code runs. 
It happens when `ConnectDialog::_update_method_tree()` calls `si->get_script()->reload();`. Maybe this call actually needs to be `reload(true)`?

Comment (tciviero) [reply editor/script/script_editor_plugin.cpp:2625]: https://github.com/godotengine/godot/blob/8120fb1242065202775831c04f099d9156c37ba2/modules/gdscript/gdscript.cpp#L751-L758

The only way it can show that error message is if `reload(false)` or `reload()` gets called since it defaults to `false`, so `si->get_script()->reload(true);` could fix the issue.
