### PR TITLE
Fix file permissions for the web platform (affects every Unix-like platform)

### LINKED ISSUE #79594: Godot Editor does not import files correctly in web editor.
### Godot version

v4.1.1 stable

### System information

Windows 11 - Chrome & Firefox - Godot 4.1.1 - Web Editor

### Issue description

This issue also happens on Chromebook.

Every file won't import correctly and will always show an 'X' next to it. It is not possible to use these files basically making the editor worthless.

### Steps to reproduce

1. Open Godot Web Editor
2. Create Project
3. Open It
4. Check the FileSystem in the bottom-left

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by adamscott**
Fixes #79594.

~~`umask()` is now called only once and will be applied to `fchmod()` automatically as it has been called just before.~~
`umask()` was removed, [see bruvzg's comment](https://github.com/godotengine/godot/pull/79866#discussion_r1273456052).

With this PR, the web platform now imports correctly files.

If needed, a MRP is simply creating a new project from the project explorer: if the icon is correctly imported, the fix worked.

### CODE REVIEW

**Comment by adamscott** [comment]
Added as label each Unix-like platform.

File: drivers/unix/file_access_unix.cpp [hunk 1]
```diff
@@ -108,10 +108,8 @@ Error FileAccessUnix::open_internal(const String &p_path, int p_mode_flags) {
 			last_error = ERR_FILE_CANT_OPEN;
 			return last_error;
 		}
-		// Fix temporary file permissions (defaults to 0600 instead of 0666 & ~umask).
-		mode_t mask = umask(022);
-		umask(mask);
-		fchmod(fd, 0666 & ~mask);
+		umask(022);
```
Comment (bruvzg) [inline drivers/unix/file_access_unix.cpp:111]: This change will set `umask` for the whole app, but the original code was intended to get the current mask instead (first call to get the mask, and second to restore it). 

`0022` is default `umask` on most Unix systems, but seems like web use `0777`. I guess it would be better to use `fchmod` with hardcoded `0666` and avoid touching `umask` at all, if it's causing issues.

**Review by bruvzg — CHANGES_REQUESTED** [review]

File: drivers/unix/file_access_unix.cpp (hunk 1 above)
Comment (adamscott) [reply drivers/unix/file_access_unix.cpp:111]: > This change will set umask for the whole app, but the original code was intended to get the current mask instead (first call to get the mask, and second to restore it).

Oh! I understand better your code, now.

Comment (adamscott) [reply drivers/unix/file_access_unix.cpp:111]: We could keep your code for Unix systems and hardcode 0666 for web with a macro.

Comment (bruvzg) [reply drivers/unix/file_access_unix.cpp:111]: This part was there to mimic previous behavior (before code to create temp files were changed) as close as possible, but I do not think it's important for anything, so hardcoding 0666 everywhere should be fine as well.

Comment (adamscott) [reply drivers/unix/file_access_unix.cpp]: Done. I removed `umask()`.

**Review by bruvzg — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.
