### PR TITLE
[Texture Import] Fix invert color

### LINKED ISSUE #21681: Import Texture with Invert Color results in an infinite loop of errors.
My build is Windows 10, 64-bit, v3.1.alpha.custom_build.ab60283

By tinkering with the import texture settings, ticking the Invert Color option and doing a reimport results in this stream of errors that will not return control to the editor:

godot master_2018-08-31_17-29-18
this happens when setting invert color on import options

Here is a sample project if needed:  
[Texture Option Bug.zip](https://github.com/godotengine/godot/files/2342985/Texture.Option.Bug.zip)

### PR DESCRIPTION
**Pull request by guilhermefelipecgs**
Fix #21681.

### CODE REVIEW

File: editor/import/resource_importer_texture.cpp [hunk 1]
```diff
@@ -433,7 +433,7 @@ Error ResourceImporterTexture::import(const String &p_source_file, const String
 		image->lock();
 		for (int i = 0; i < height; i++) {
 			for (int j = 0; j < width; j++) {
-				image->set_pixel(i, j, image->get_pixel(i, j).inverted());
+				image->set_pixel(j, i, image->get_pixel(j, i).inverted());
```
Comment (akien-mga) [inline editor/import/resource_importer_texture.cpp]: It's actually more common to use `i` for width (`x` coordinate) and `j` for height (`y` coordinate), which avoids such confusion.

Comment (guilhermefelipecgs) [reply editor/import/resource_importer_texture.cpp]: Changed.

**Comment by akien-mga** [comment]
Thanks!
