### PR TITLE
Use cached hue for color picker when saturation is 0 

### LINKED ISSUE #76968: Color Widget's HSV mode doesn't update the hue properly when saturation is 0.
### Godot version

4.0.2

### System information

Ubuntu 22.04.1 LTS

### Issue description

image

Notice how the hue is on the blue color, but the saturation is insists on remaining red.

If I change the saturation a little bit, the correct value will apply. But if I adjust the value or the alpha, the blue hue will be punched out and become red again.

### Steps to reproduce

Go to a ColorPicker in the editor (say, the modulate property of Node2D), open the color picker, and copy the above configuration in the HSV tab.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by dinoplane**
Hue is cached when the saturation in hsv mode is nonzero. When the saturation is 0, the cached hue is set as the slider in `_update_color`. This is to prevent #76968 from happening.

Fixes #76968

### CODE REVIEW

**Comment by akien-mga** [comment]
It seems you're a first time contributor, so welcome!

To ensure you can pass style checks from CI, we recommend running checks locally, using the tools described in https://docs.godotengine.org/en/latest/contributing/development/code_style_guidelines.html
There are notably pre-commit hooks in `misc/hooks/` which you can set up locally if you want, to run checks on each commit.

Once the PR is ready, we'd typically ask you to squash the commits into one, you can see [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html) for details.

Contributors familiar with the ColorPicker will review this as time permits.

**Comment by KoBeWi** [comment]
Seems like this doesn't work correctly 🤔

https://github.com/godotengine/godot/assets/2223172/32abccbd-13bc-4ff2-8acb-3143969c0275

The saturation bar is always red when it's 0 and changing to different color mode and back resets the hue slider. tbh I don't see any difference from the previous behavior.

Also I think the change could be done in ColorModeHSV class. We should avoid hard-coding mode-specific code in ColorPicker if possible.

**Comment by dinoplane** [comment]
Ok I shall make these changes immediately

**Comment by dinoplane** [comment]
On second thought, I don't think its possible to completely isolate the fix in ColorModeHSV. This is because in color_picker, the slider values are updated using  `sliders[i]->set_value(modes[current_mode]->get_slider_value(i));` . `ColorModeHSV::get_slider_value()` is a const function, which means we cannot update a cached value (that would be a member of ColorModeHSV) from there. There would need to be some intermediate function called by the color picker for HSV mode  that updates the cached value of the hue.

**Comment by dinoplane** [comment]
I have fixed the issue with the slider color and the changing of hues when the color mode is changed. I've isolated most of the behavior in `color_mode.cpp`, though as I've mentioned before, it seems to be impossible to completely contain the solution there.

File: scene/gui/color_mode.cpp [hunk 1]
```diff
@@ -117,8 +117,13 @@ float ColorModeHSV::get_slider_max(int idx) const {
...
 float ColorModeHSV::get_slider_value(int idx) const {
 	switch (idx) {
-		case 0:
-			return color_picker->get_pick_color().get_h() * 360.0;
+		case 0: {
+			float ret = color_picker->get_cached_hue();
+			if (color_picker->get_pick_color().get_s() > 0) {
+				ret = color_picker->get_pick_color().get_h() * 360.0;
+			}
+			return ret;
```
Comment (KoBeWi) [inline scene/gui/color_mode.cpp:125]:
```suggestion
			if (color_picker->get_pick_color().get_s() > 0) {
				return color_picker->get_pick_color().get_h() * 360.0;
			} else {
				return color_picker->get_cached_hue();
			}
```

**Comment by KoBeWi** [comment]
> ColorModeHSV::get_slider_value() is a const function, which means we cannot update a cached value (that would be a member of ColorModeHSV) from there.

You can change a member inside const function if it has `mutable` modifier. We do allow that for caching something.

File: scene/gui/color_picker.h [hunk 2]
```diff
@@ -206,6 +206,8 @@ class ColorPicker : public VBoxContainer {
 	float v = 0.0;
 	Color last_color;
 
+	float cached_hue = 0.0;
+
```
Comment (KoBeWi) [inline scene/gui/color_picker.h:210]:
```suggestion
	float v = 0.0;
	float cached_hue = 0.0;
	Color last_color;
```

**Review by KoBeWi — APPROVED** [review]
Works correctly now.
The special case you added is next to another special case, so it's probably fine.

Left 2 style comments that need to be addressed.

**Comment by KoBeWi** [comment]
You need to squash commits into 1. Also accepting changes from GitHub added me as co-author, so you need to remove that.

**Comment by dinoplane** [comment]
just squashed it all into one! Thank you very much!

**Comment by akien-mga** [comment]
I pushed a small update amending the commit message to make it more explicit about the bug being fixed.
