### PR TITLE
Fix ImporterMesh bone weight handling during lightmap unwrap

### LINKED ISSUE #81636: Lightmap UV generation on rigged FBX files causes the mesh to disappear
### Godot version

v4.2.dev.custom_build [3ed449711]

### System information

Fedora, RX 590

### Issue description

When attempting to use the lightmap unwrap on a rigged fbx (doesn't repro with glb), there's an error in the console and the mesh disappears.

I created this mesh in blender as a reproduction case, but this issue was observed yesterday on minionsart's stream (https://www.twitch.tv/videos/1924312339, problems starting at 2h32 min roughly). She kindly sent me the model and I've managed to make a reproduction case that behave the same way (see MRP below)

Screenshot from 2023-09-14 09-59-39

### Steps to reproduce

Download MRP

There's an fbx (test2.fbx). It's a cube rigged to a metarig.

Double click the FBX, you'll see a cube mesh 
image

Hit reimport

Open the test_2.tscn, observe the cube is missing
image
 with errors in the console
 
 ```
   scene/resources/importer_mesh.cpp:337 - Index bone_idx = 545021568 is out of bounds (static_cast<int>(bone_transform_vector.size()) = 159).
  servers/rendering_server.cpp:599 - Condition "array.size() != (int32_t)(p_vertex_array_len * bone_count)" is true. Returning: ERR_INVALID_PARAMETER
  Invalid array format for surface.
  scene/resources/mesh.cpp:1771 - Condition "err != OK" is true.
  scene/resources/mesh.cpp:1892 - Index p_idx = -1 is out of bounds (surfaces.size() = 0).
  scene/resources/mesh.cpp:1912 - Index p_idx = -1 is out of bounds (surfaces.size() = 0).
  Attempt to disconnect a nonexistent connection from 'test2:<Node3D#1917988171855>'. Signal: 'replacing_by', callable: 'EditorNode::set_edited_scene
  ```

### Minimal reproduction project

[minions-test.zip](https://github.com/godotengine/godot/files/12606421/minions-test.zip)

### PR DESCRIPTION
**Pull request by bitsawer**
* Fixes https://github.com/godotengine/godot/issues/81636

When unwrapping surfaces for lightmaps we need to update the format flag depending on if we use 0, 4 or 8 influences. Previously this was not done and afterwards the code read invalid memory in some cases (for example seeing invalid bone indices like 545021568 in the bug report).

After this patch, the cube import works. The cube does look pretty busted, but as it is just a test model it might be intentional and bones still seem to affect it correctly when moved. And removing the skeleton influence makes it look like a normal cube. I don't have access to the original model, so @QbieShay might be able to test this more.

Also, I spotted another weird thing with the test project. Simply repeatedly selecting between the Cube mesh node and then another node causes errors and the top UI toolbar keeps growing and adds what looks like a vertical separator every time you do this:

```
Attempt to disconnect a nonexistent connection from 'test2:<Node3D#1869871115769>'. Signal: 'replacing_by', callable: 'EditorNode::set_edited_scene'.
editor\plugins\node_3d_editor_plugin.cpp:7693 - Condition "p_control->get_parent() != context_toolbar_hbox" is true.
editor\plugins\node_3d_editor_plugin.cpp:7693 - Condition "p_control->get_parent() != context_toolbar_hbox" is true.
editor\plugins\node_3d_editor_plugin.cpp:7693 - Condition "p_control->get_parent() != context_toolbar_hbox" is true.
```

bug

### CODE REVIEW

File: scene/resources/importer_mesh.cpp [hunk 1]
```diff
@@ -1292,7 +1293,15 @@ Error ImporterMesh::lightmap_unwrap_cached(const Transform3D &p_base_transform,
 		Ref<SurfaceTool> &tool = surfaces_tools[i];
 		tool->index();
 		Array arrays = tool->commit_to_arrays();
-		add_surface(tool->get_primitive_type(), arrays, Array(), Dictionary(), tool->get_material(), tool->get_meta("name"), lightmap_surfaces[i].format);
+
+		uint64_t format = lightmap_surfaces[i].format;
```
Comment (bitsawer) [inline scene/resources/importer_mesh.cpp:1297]: I made this `uint64_t` instead of `uint32_t` as future proofing for https://github.com/godotengine/godot/pull/81138

**Review by clayjohn — APPROVED** [review]
Looks great! Tested locally and it appears to work. 

I get the same janky cube that you get, but when moving bones around it deforms in a way that seems right.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.3.
