### PR TITLE
Make sure to normalize subtags when parsing BBCode

### LINKED ISSUE #75501: Quotes in RichTextLabel BBCode string arguments are passed as-is, which is inconsistent with string arguments elsewhere
### Godot version

4.0.1.stable

### System information

Fedora 37, GeForce RTX 4090 (NVIDIA 525.89.02)

### Issue description

The following BBCode in a RichTextLabel:

```
[p align=center]p align center[/p]

[p align="center"]p align "center"[/p]

[p align='center']p align 'center'[/p]
```

Results in:

image

I'd expect all 3 to be center-aligned, parsing the `align` argument's value as `center` and not `"center"` or `'center'` with the quotes. This is the behavior found in any programming language, HTML/CSS, etc. This can cause difficult-to-diagnose issues as to why string parameters aren't behaving as expected in BBCode, especially when file paths are involved.

We should handle string paths with quotes (single or double) in RichTextLabel to avoid this kind of issue. It should be as simple as calling `.trim_prefix("\"").trim_suffix("\"").trim_prefix("'").trim_suffix("'")` when parsing a string parameter in RichTextLabel's BBCode parser.

See https://github.com/godotengine/godot-docs/issues/6574#issuecomment-1377460963 where this issue was originally encountered.

Modifying this behavior is technically a breaking change, but the chance that someone is relying on the current behavior (string arguments containing their beginning/end quotes) is very low.

### Steps to reproduce

- Add a RichTextLabel node with BBCode enabled.
- Write `[p align="center"]p align "center"[/p]` within the Text property.
- Notice how the label isn't centered because `center` is surrounded by quotes.

### Minimal reproduction project

[test_richtextlabel_string_quotes.zip](https://github.com/godotengine/godot/files/11114324/test_richtextlabel_string_quotes.zip)

### PR DESCRIPTION
**Pull request by joao-pedro-braz**
This PR makes it so that all subtags are normalized before usage. Normalization means removing any leading and/or trailing quotation marks from any given subtag.

Fixes: https://github.com/godotengine/godot/issues/75501

image

### CODE REVIEW

**Comment by joao-pedro-braz** [comment]
A nice followup would be adding some tests for the parser.
There are so many little things that could break during parsing, that it would be a nightmare to debug.
Not saying that the current parser is bad, not all, just that it's complex enough to warrant unit tests.

File: scene/gui/rich_text_label.cpp [hunk 1]
```diff
@@ -2579,6 +2579,12 @@ void RichTextLabel::_fetch_item_fx_stack(Item *p_item, Vector<ItemFX *> &r_stack
 	}
 }
 
+void RichTextLabel::_normalize_subtags(Vector<String> &subtags) {
+	for (auto &subtag : subtags) {
```
Comment (KoBeWi) [inline scene/gui/rich_text_label.cpp:2583]:
```suggestion
	for (String &subtag : subtags) {
```
Can't use `auto`.

File: scene/gui/rich_text_label.cpp [hunk 2]
```diff
@@ -2579,6 +2579,12 @@ void RichTextLabel::_fetch_item_fx_stack(Item *p_item, Vector<ItemFX *> &r_stack
...
+		subtag = subtag.trim_prefix("\"").trim_suffix("\"").trim_prefix("'").trim_suffix("'");
```
Comment (KoBeWi) [inline scene/gui/rich_text_label.cpp:2584]:
```suggestion
		subtag = subtag.unquote();
```

File: scene/gui/rich_text_label.cpp [hunk 3]
```diff
@@ -3718,7 +3724,7 @@ void RichTextLabel::append_text(const String &p_bbcode) {
 				const String &expr = split_tag_block[i];
 				int value_pos = expr.find("=");
 				if (value_pos > -1) {
-					bbcode_options[expr.substr(0, value_pos)] = expr.substr(value_pos + 1);
+					bbcode_options[expr.substr(0, value_pos)] = expr.substr(value_pos + 1).trim_prefix("\"").trim_suffix("\"").trim_prefix("'").trim_suffix("'");
```
Comment (KoBeWi) [inline scene/gui/rich_text_label.cpp:3727]:
```suggestion
					bbcode_options[expr.substr(0, value_pos)] = expr.substr(value_pos + 1).unquote();
```

**Comment by joao-pedro-braz** [comment]
Sorry it took me so long to address your points @KoBeWi, Github decided to just not notify me of them :clown_face:

**Review by KoBeWi — APPROVED** [review]
I think `color` and `outline_color` also need unquote, because they don't work quoted.

Other than that seems fine (I don't know if it covers all cases though).

**Review by bruvzg — COMMENTED** [review]
> I think color and outline_color also need unquote, because they don't work quoted.

Indeed, it should be unquoted as well (both main tags and drop cap subtags). Quoted colors won't work, at least in case of HTML color codes.

Otherwise, seems OK.

**Comment by joao-pedro-braz** [comment]
> I think `color` and `outline_color` also need unquote, because they don't work quoted.
> 
> Other than that seems fine (I don't know if it covers all cases though).

Weird... I would guess they would work, I'll have a look

**Comment by joao-pedro-braz** [comment]
image
Fixed!

**Comment by akien-mga** [comment]
Thanks!
