### PR TITLE
Fix error spam when hovering minimap in the script editor

### LINKED ISSUE #70775: Godot 4 script editor throws errror when hover on minimap
### Godot version

4.0 beta 10

### System information

Windos 10, Vulkan, NVIDIA GeForce GTX 1050 (31.0.15.2647)

### Issue description

When opened file is 196 or 197 lines, script editor throws error when hover on minimap.
I also found that only happen on "Output" is opened.
The error shows attach below.

`scene/gui/text_edit.cpp:3602 - Index p_line_from = -1 is out of bounds (text.size() = 196).`
`scene/gui/text_edit.cpp:3602 - Index p_line_from = -1 is out of bounds (text.size() = 197).`

https://user-images.githubusercontent.com/50160052/210150255-08ce5875-aa82-47f4-8d34-d151ade24c01.mp4

### Steps to reproduce

Open a file and input any text to 196 or 197 lines.
Mouse hover on script editor minimap.
Throws error.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by jamesmintram**
Fixes https://github.com/godotengine/godot/issues/70775

The calculation on 4338 would end up setting `minimap_line` to -1

This happened when the document had enough lines that it reached the bottom of the viewport.

This fix is inline with the existing behaviour of if `minimap_line` is -1, then set it to zero.

### CODE REVIEW

**Comment by Calinou** [comment]
Thanks for opening a pull request!

Please [amend the commit to use a human-readable commit message](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind) (`git commit --amend`). This way, people reading the Git log can easily figure out what's going on :slightly_smiling_face:

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -4333,7 +4333,9 @@ int TextEdit::get_minimap_line_at_pos(const Point2i &p_pos) const {
 	if (first_vis_line > 0 && minimap_line >= 0) {
 		minimap_line -= get_next_visible_line_index_offset_from(first_vis_line, 0, -num_lines_before).x;
 		minimap_line -= (minimap_line > 0 && smooth_scroll_enabled ? 1 : 0);
-	} else {
+	}
+
+	if (minimap_line == -1) {
```
Comment (Paulb23) [inline scene/gui/text_edit.cpp:4338]: `< 0` would be better to catch any further edgecases

**Review by Paulb23 — DISMISSED** [review]

**Review by akien-mga — APPROVED** [review]
Force pushed an update to change the code as suggested. Should be good to merge now.

The surrounding code seems a bit confusing and might need further work, it seems weird that `minimap_line` is explicitly set to `-1` in some cases, but then we treat it as a case that needs to be set to 0. The `if` conditional seems to partially redo what the `minimap_line` initial assignment's ternary operator checks... this could probably be rewritten to be less confusing and bug prone.

**Comment by akien-mga** [comment]
Thanks!
