### PR TITLE
AudioServer to have function to access microphone buffer directly

### LINKED ISSUE #11347: A new InputEventMicrophone class to deliver audio chunks of microphone data independently of the Audio system
### Describe the project you are working on

A reliable and easy to use Voice over IP plugin https://github.com/goatchurchprime/two-voip-godot-4

### Describe the problem or limitation you are having in your project

The microphone input is unreliable and sounds distorted on different platforms when it is put to use.  

I have gone into the implementation in depth as discussed in my [previous proposal](https://github.com/godotengine/godot-proposals/issues/11325#issuecomment-2539505337).  

TDLR: 
* When the rate of the input samples from microphone does not exactly match the rate of the output sample in the audio system the buffering between them fails and causes bugs.  
* The current implementation uses an extra buffer that causes lag in the audio encoding.  
* Microphone data is not required in the audio system, as evidenced by the fact that it must always be routed to a bus that is set to mute.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The microphone would be input in the same way as the midi and the mouse is input, and can be handled in the same way.

The most common purpose of microphone data is for packaging and compressing into Opus packets for transmission across the network to another player.  The unpack and playback stage in the other player's game has to handle the jitter and buffering of packets as well the mismatch between the clockrates on different computers.  Compared to this, any jittering on the rate of input is irrelevant. 

The second most common purpose of microphone data is as a trigger (shout or blowing in the mic) to set off an event.

The least common use is to feed the sound into the speakers because it causes a feedback screech. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Basing this on the [Midi Input](https://docs.godotengine.org/en/stable/classes/class_inputeventmidi.html#class-inputeventmidi) we should control this with the functions:

* [AudioServer.get_input_device_list()](https://docs.godotengine.org/en/stable/classes/class_audioserver.html#class-audioserver-method-get-input-device-list)
* AudioServer.start_microphone_input(chunk_size: int, input_device: string)
* AudioServer.stop_microphone_input()

Then we emit an `InputEventMicrophone` every time the [AudioDriver::input_buffer](https://github.com/godotengine/godot/blob/master/servers/audio_server.h#L62) has more than `chunk_size` samples in it, with the properties:
 
* data : PackedVector2Array   # length = chunk_size
* abs_max : float   # maximum volume of the samples in the chunks

These packets could be resampled and encoded into opus chunks the moment they are emitted to the `_input()` function, and not in a process loop that has to poll the buffer to check if it's got enough samples to form a chunk.  The default Opus chunk size is 20ms long which is 882 samples at 44.1kHz.  

This interface also very useful if you want to use a voice activated sound (eg shout or blow into the microphone to fire a bullet) by monitoring the value of abs_max as you would the events from a pressure sensitive pad.  

To avoid copying large chunks of data around in the InputEventMicrophone, we could instead return indexes into the `input_buffer` and copy the data to the Opus encoding buffer with a function:

* AudioServer.copy_input_data(PackedVector2Array&, start, length)

The code required for this implementation of this feature would be modest.  It is the case that [all five platforms](https://github.com/godotengine/godot-proposals/issues/11325#issuecomment-2539505337) fill the input_buffer via the [AudioDriver::input_buffer_write(int32_t sample)](https://github.com/godotengine/godot/blob/master/servers/audio_server.cpp#L105) function in chunks of varying size.  At the end of each of these chunks we need to call a new function:
* AudioDriver::generate_microphone_events()

This would construct as many events in the buffer as necessary that matched the chunk_size, and then call `Input::get_singleton()->parse_input_event(event)` on each one to enter it into the system.
  

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

The microphone is core.

### PR DESCRIPTION
**Pull request by goatchurchprime**
Direct access to the audio data in the microphone buffer is necessary to overcome the design flaw of connecting the Audio Input stream (microphone) to the Audio Output stream under the mistaken assumption that they will always proceed at exactly the same rate for all time on every platform.

A diagram of the current design and the improved situation [can be seen here]( https://github.com/godotengine/godot/pull/105244#issuecomment-2830480213).

The following issues are illustrative of the flaw in the current design.
* Issue #112836 (which has been replicated on 3 platforms, not only Android)
* Issue #80173
* Issue #95120
* Issue #86428 -- which works by packing zero values into the audio stream when the buffer under-runs, causing a degradation of the sound quality (such as _Garbling_)
* (Observed Godot3) Issue #54544 

This PR is a re-implementation of three previous attempts to find an appropriate place for a `get_microphone_frames()` function:
 * PR #100508 
 * PR #105244 
 * PR #108773 

This also resolves godotengine/godot-proposals#11347 (proposal).

A comprehensive demo is at:
https://github.com/goatchurchprime/godot-demo-projects/tree/gtch/mic_input/audio/mic_input

This PR adds four new functions to `AudioServer`: 

```GDScript
set_input_device_active(active : bool) -> int
get_input_buffer_length_frames() -> int
get_input_frames_available() -> int
get_input_frames(frames : int) -> PackedVector2Array
```

In the class [AudioEffectCapture](https://docs.godotengine.org/en/stable/classes/class_audioeffectcapture.html#methods), the function that is equivalent to `get_input_frames()` is known as `get_buffer()`.

The function `get_buffer_length_frames()` is necessary to predict when the overflow is likely to occur. 

The function `set_input_device_active()` provides direct control of exactly when the microphone stream is turned on and off, rather than it currently being done by the existence of an active `AudioStreamMicrophone` playback object.

This could mean that we never have to call `AudioServer.set_input_device()` while the input device is active, which leads to [problematic situations](https://github.com/godotengine/godot/blob/master/drivers/pulseaudio/audio_driver_pulseaudio.cpp#L557) where the error case of a failure to start the new device cannot be properly handled. Instead you would call `set_input_device_active(false)`, then change the device, before calling `set_input_device_active(true)` which can return an error if it doesn't work.

### Stuff to do
* <strike>Review the function names and whether it needs `get_input_device_active()` and member variable `input_device_active` and functions to be const.</strike>
* <strike>Write the docs</strike>
* <strike>Make AudioStreamMicrophonePlayback use the `input_device_active` interface, and check it still works as before (if none of these new functions are used).</strike>

### CODE REVIEW

File: servers/audio/audio_server.cpp [hunk 1]
```diff
@@ -109,6 +109,9 @@ void AudioDriver::input_buffer_write(int32_t sample) {
 			input_size++;
 		}
 	} else {
+		// This protection was added at https://github.com/godotengine/godot/commit/f529649cece9f08002c527fca25c45a5e66d2a4b due to a "possible crash".
```
Comment (Ivorforce) [inline servers/audio/audio_server.cpp]:
```suggestion
		// This protection was added in GH-26505 due to a "possible crash".
```

File: servers/audio/audio_server.cpp [hunk 2]
```diff
@@ -1839,9 +1842,75 @@ String AudioServer::get_input_device() {
 }
 
 void AudioServer::set_input_device(const String &p_name) {
+	// how about: if (!p_is_active) here?
```
Comment (Ivorforce) [inline servers/audio/audio_server.cpp]: I'm not sure I understand the suggestion?

File: servers/audio/audio_server.cpp [hunk 3]
```diff
@@ -1839,9 +1842,75 @@ String AudioServer::get_input_device() {
...
 	AudioDriver::get_singleton()->set_input_device(p_name);
 }
 
+Error AudioServer::set_input_device_active(bool p_is_active) {
+	if (input_device_active == p_is_active) {
+		return OK;
+	}
+	if (p_is_active) {
```
Comment (Ivorforce) [inline servers/audio/audio_server.cpp:1852]: Nitpick, but I would use `if/else` instead of early return here, because `p_is_active` and `!p_is_active` are of equal importance, and neither is an 'early return case' of the other.
If you do want to use early return syntax, I'd probably put the shorter one in the early return.

File: servers/audio/audio_server.h [hunk 4]
```diff
@@ -232,6 +232,9 @@ class AudioServer : public Object {
 	bool debug_mute = false;
 #endif // DEBUG_ENABLED
 
+	bool input_device_active = false;
```
Comment (Ivorforce) [inline servers/audio/audio_server.h:235]: Do we need a separate boolean for this? Can't we ask the audio driver instead if it's active? I'm always a bit wary of dual states that aren't enforceable.

File: servers/audio/audio_server.h [hunk 5]
```diff
@@ -492,6 +495,10 @@ class AudioServer : public Object {
 	PackedStringArray get_input_device_list();
 	String get_input_device();
 	void set_input_device(const String &p_name);
+	Error set_input_device_active(bool p_is_active);
+	int get_input_frames_available();
+	int get_input_buffer_length_frames();
+	PackedVector2Array get_input_frames(int p_frames);
```
Comment (Ivorforce) [inline servers/audio/audio_server.h:501]: I think `_if_available` helps clear up what the parameter is meant to do at a glance

```suggestion
	PackedVector2Array get_input_frames_if_available(int p_frames);
```

File: servers/audio/audio_server.h [hunk 6]
```diff
@@ -492,6 +495,10 @@ class AudioServer : public Object {
 	PackedStringArray get_input_device_list();
 	String get_input_device();
 	void set_input_device(const String &p_name);
+	Error set_input_device_active(bool p_is_active);
+	int get_input_frames_available();
```
Comment (Ivorforce) [inline servers/audio/audio_server.h:499]: It's a little verbose for some people, but i like to make absolutely sure nobody can misunderstand the function name:

```suggestion
	int get_number_of_available_input_frames();
```

(`get_input_frames_available` could be interpreted as "get the input frames that are available", as in, the actual frames, instead of the number of frames)

File: servers/audio/audio_server.cpp [hunk 7]
```diff
@@ -1839,9 +1842,75 @@ String AudioServer::get_input_device() {
...
+	ad->unlock();
+	return buffsize / 2;
+}
+
+PackedVector2Array AudioServer::get_input_frames(int p_frames) {
+	PackedVector2Array ret;
+	AudioDriver *ad = AudioDriver::get_singleton();
+	ad->lock();
+	int input_position = ad->get_input_position();
+	Vector<int32_t> buf = ad->get_input_buffer(); // should this be returning Vector<int32_t>& ??
```
Comment (Ivorforce) [inline servers/audio/audio_server.cpp]: > // should this be returning Vector<int32_t>& ??

Yes! Or rather, it should return `const Vector<int32_t>&`. Feel free to adjust accordingly.

File: servers/audio/audio_server.cpp [hunk 8]
```diff
@@ -1839,9 +1842,75 @@ String AudioServer::get_input_device() {
...
+	if (input_position < input_buffer_ofs) {
+		input_position += buf.size();
+	}
+	if ((input_buffer_ofs + p_frames * 2 <= input_position) && (p_frames >= 0)) {
```
Comment (Ivorforce) [inline servers/audio/audio_server.cpp:1895]: Prefer early return:


```suggestion
	if (p_frames < 0 || (input_buffer_ofs + p_frames * 2 > input_position)) {
		ad->unlock();
		return PackedVector2Array();
```

(and move to the top of the function)

File: servers/audio/audio_server.cpp [hunk 9]
```diff
@@ -1839,9 +1842,75 @@ String AudioServer::get_input_device() {
...
+			float l = (buf[input_buffer_ofs++] >> 16) / 32768.f;
+			if (input_buffer_ofs >= buf.size()) {
+				input_buffer_ofs = 0;
+			}
+			float r = (buf[input_buffer_ofs++] >> 16) / 32768.f;
+			if (input_buffer_ofs >= buf.size()) {
+				input_buffer_ofs = 0;
+			}
+			ret.write[i] = Vector2(l, r);
+		}
```
Comment (Ivorforce) [inline servers/audio/audio_server.cpp:1907]: This can be replaced with two `memcpy` calls, one from `input_position` to `buf.size()` and one from `0` to `input_position` (both limited by `p_frames` of course).
Edit: I missed that it's taking ints and setting floats. So possibly this is as simple a it gets?

File: servers/audio/audio_server.cpp [hunk 10]
```diff
@@ -1839,9 +1842,75 @@ String AudioServer::get_input_device() {
...
+		input_position += buffsize;
+	}
+	ad->unlock();
+	return (input_position - input_buffer_ofs) / 2;
+}
+
+int AudioServer::get_input_buffer_length_frames() {
+	AudioDriver *ad = AudioDriver::get_singleton();
+	ad->lock();
+	int buffsize = ad->get_input_buffer().size();
```
Comment (Ivorforce) [inline servers/audio/audio_server.cpp:1881]: `size()` returns `int64_t`, I believe.

File: servers/audio/audio_server.cpp [hunk 11]
```diff
@@ -1839,9 +1842,75 @@ String AudioServer::get_input_device() {
...
+	ad->unlock();
+	return buffsize / 2;
```
Comment (Ivorforce) [inline servers/audio/audio_server.cpp:1883]: Why `/ 2`? Is it to compensate for stereo channels? Either way it should be commented.

File: platform/android/audio_driver_opensl.cpp [hunk 12]
```diff
@@ -271,28 +271,30 @@ Error AudioDriverOpenSL::input_start() {
...
 	}
 
 	WARN_PRINT("Unable to start audio capture - No RECORD_AUDIO permission");
 	return ERR_UNAUTHORIZED;
 }
 
 Error AudioDriverOpenSL::input_stop() {
-	if (!recordItf || !recordBufferQueueItf) {
-		return ERR_CANT_OPEN;
+	if (recordItf) {
```
Comment (Ivorforce) [inline platform/android/audio_driver_opensl.cpp:286]: I'm a little confused by all these changes to specific audio drivers. I'm guessing you needed to make them more reliable to make the functionality work fully?

**Review by Ivorforce — COMMENTED** [review]
Looks like a great start! This is about the amount of complexity I was hoping to see :)

File: servers/audio/audio_server.cpp (hunk 3 above)
Comment (goatchurchprime) [reply servers/audio/audio_server.cpp:1852]: Think I got this. Knowledge of compiler that it knows all branches logically return.

File: servers/audio/audio_server.h (hunk 4 above)
Comment (goatchurchprime) [reply servers/audio/audio_server.h:235]: This state needs to be implemented in all of the 7 platforms, and I can't compile and test them all.  Each one has different issues.


Take the Web case, for example.

The `AudioDriverWeb::input_start()` doesn't set any state detectable in the C++ to tell whether it has been called or not.

https://github.com/godotengine/godot/blob/7ed0b6167618f9c8c5df87c7e83da6003c081368/platform/web/audio_driver_web.cpp#L192

Instead, the state that it is running is known deeper in the Javascript implementation on this line here.
https://github.com/godotengine/godot/blob/7ed0b6167618f9c8c5df87c7e83da6003c081368/platform/web/js/libs/library_godot_audio.js#L1291

There are similar issues with the other platforms, and I am likely to cause bugs.  So the simplest way is to use this global flag to prevent double calls (which are not protected for pulseaudio till this PR is made), and then replace it by the internal state of each platform in the future.

Comment (Ivorforce) [reply servers/audio/audio_server.h:235]: Alright. Yea, no need to add anything new to the driver if they don't have code to handle this yet. The boolean is fine.

File: servers/audio/audio_server.h (hunk 5 above)
Comment (goatchurchprime) [reply servers/audio/audio_server.h:501]: Nice idea, but not in common use for buffers.  Buffer gets returning empty or incomplete values when there's not enough data is normally assumed.

For example:

https://docs.godotengine.org/en/stable/classes/class_fileaccess.html#class-fileaccess-method-get-buffer

https://docs.godotengine.org/en/stable/classes/class_audioeffectcapture.html#class-audioeffectcapture-method-get-buffer

Comment (Ivorforce) [reply servers/audio/audio_server.h:501]: Ok, if it's consistent with current APIs, the current naming is fine with me!

File: servers/audio/audio_server.h (hunk 6 above)
Comment (goatchurchprime) [reply servers/audio/audio_server.h:499]: I'm modelling it closely with other functions nobody has an issue with.  It's clarified by the documentation as well as the return value.  I believe my current name will raise fewer objections with people.  If you are think I'm wrong about this I'll change it.

https://docs.godotengine.org/en/stable/classes/class_audioeffectcapture.html#class-audioeffectcapture-method-get-frames-available

Comment (Ivorforce) [reply servers/audio/audio_server.h:499]: Thanks for linking the other API. I may disagree with the naming, but it's more important that it's consistent. So your name is fine I think.

File: servers/audio/audio_server.cpp (hunk 7 above)
Comment (goatchurchprime) [reply servers/audio/audio_server.cpp]: Originally I did use `Vector<int32_t>&`, but  @lyuma was adamant that this made things worse because the Vector class contains a CowData array, so it's not being copied if nothing is written. https://github.com/godotengine/godot/blob/7ed0b6167618f9c8c5df87c7e83da6003c081368/core/templates/cowdata.h

Comment (Ivorforce) [reply servers/audio/audio_server.cpp]: The data is not copied, but copying Vector still incurs overhead from the atomic. It's better to avoid it when possible.

File: servers/audio/audio_server.cpp (hunk 10 above)
Comment (goatchurchprime) [reply servers/audio/audio_server.cpp:1881]: Common way of doing things.  At least it's not "unsigned int" which is even more strictly true, but has caused me really nasty bugs in the past, so I never use it.

File: platform/android/audio_driver_opensl.cpp (hunk 12 above)
Comment (goatchurchprime) [reply platform/android/audio_driver_opensl.cpp:286]: The use of the `ERR_FAIL_COND_V` macro in the init function bails out early and potentially leaves various components of the input driver in an unclean state.  The `input_stop` function needs to be rewritten to clean up these bits of leftover state.  
 https://github.com/godotengine/godot/blob/master/platform/android/audio_driver_opensl.cpp#L201

File: servers/audio/audio_server.cpp (hunk 10 above)
Comment (AThousandShips) [reply servers/audio/audio_server.cpp:1881]: Common way for the audio code to use a smaller type? I'm not sure I understand what you mean

Comment (goatchurchprime) [reply servers/audio/audio_server.cpp:1881]: While it's true that CowData has `typedef int64_t Size`, almost everywhere I look in the code where the value of a `Vector<X>::size()` is stored to a variable it is of type `int`, so I assume this is normal practice.  There is zero chance that this buffer size overflows 32 bits, or whatever an `int` is.

eg
https://github.com/godotengine/godot/blob/master/scene/debugger/scene_debugger.cpp#L2706

Comment (AThousandShips) [reply servers/audio/audio_server.cpp:1881]: I'd say to not use old code that's formally incorrect as a guideline, it's better to be safe

The reason there's so many `int` is because `CowData` *used* to be 32 bit until just last year so it's recent so a lot of left over code that wasn't migrated

File: servers/audio/audio_server.cpp (hunk 2 above)
Comment (goatchurchprime) [reply servers/audio/audio_server.cpp]: Adding this if-statement would remove a feature from the engine where it is possible to change the microphone input_device while it is running.  

Instead you would have to call `set_input_device_active(false)`, then change the device, before calling `set_input_device_active(true)`.

This is actually how it is implemented under the hood on some of the platforms, see here:

https://github.com/godotengine/godot/blob/master/drivers/pulseaudio/audio_driver_pulseaudio.cpp#L557

However, this hot-swapping feature is hacky because it handles the case where the new_input_device fails by shutting down the thread, while being unable to inform the game that it has failed.

If changing the input device was only possible when the input was switched off (easy to do with the new function), then the failure case can be properly handled when it is switched back on when `set_input_device_active(true)` is called.

File: servers/audio/audio_server.cpp (hunk 8 above)
Comment (Ivorforce) [reply servers/audio/audio_server.cpp]: You didn't address this comment. The reason I ask to early return here is that not being able to return frames is a special case, so I think it's easier to read on a logical level if it's handled separately.

File: servers/audio/audio_server.cpp (hunk 2 above)
Comment (Ivorforce) [reply servers/audio/audio_server.cpp]: Makes sense.
I think this is worth addressing, but I'd say this is out of scope for the PR. I'd rather do it in a separate PR.

File: platform/android/audio_driver_opensl.cpp [hunk 13]
```diff
@@ -271,28 +271,30 @@ Error AudioDriverOpenSL::input_start() {
...
+		(*recordItf)->SetRecordState(recordItf, SL_RECORDSTATE_STOPPED);
```
Comment (Ivorforce) [inline platform/android/audio_driver_opensl.cpp:287]: Are you 100% sure this is safe to call without making the `GetRecordState` check first?

**Review by Ivorforce — COMMENTED** [review]
I think this might be ready to merge (though I want to test before approving). Any reason it's still in draft?

File: platform/android/audio_driver_opensl.cpp (hunk 13 above)
Comment (goatchurchprime) [reply platform/android/audio_driver_opensl.cpp:287]: p400 of [the specifications](https://registry.khronos.org/OpenSL-ES/specs/OpenSL_ES_Specification_1.1.pdf) says there is no precondition on the state when calling this function.   

image

**Review by Ivorforce — APPROVED** [review]
I think this PR is as ready to merge as it will ever get. Great job!
I'm not in the audio team, so it would be nice to get confirmation on its mergability as well. I'm hoping to fit it into 4.6, since it's a pretty riskless, potentially high impact change.

Since this PR has quite some history, I want to lay out my reasons for endorsing this form of the feature.
Full disclosure, I have been part of a few audio meetings discussing this, and further had dedicated meetings with @goatchurchprime discussing this feature in detail. This PR is the outcome of these discussions.

**First off, why is this feature needed?**
To cut it short, the current way to accept microphone data is inherently flawed. It is done through `AudioEffectCapture`, after it has [experienced a lot of travel](https://github.com/godotengine/godot/pull/105244#issuecomment-2830480213) through the audio systems.
The main problem with this is that audio input is accepted asynchronously to the audio server's clock. Even when they have the same theoretical sampling rate, they inevitably drift apart. This can lead to either too many samples being produced to consume, or too few. In our codebase, this leads to audio stutters and gaps (previously, it led to capture ending abruptly), making audio capturing like this problematic. A way to fix it in place might be to resample on the fly, but this is expensive and difficult, and more importantly, it is not needed.

The above example shows that handling input data on the audio system designed for playback is inherently error prone. On the bright side, most games do not need to play back the audio. They just need to capture it, and send it elsewhere, also known as voice over IP (or, use it as an input, ala One Hand Clapping). So a system is needed to capture the audio before it enters the server at an incorrect sampling rate.

The three previous PRs were various attempts at this.
[The first PR](https://github.com/godotengine/godot/pull/100508) injected an alternative usage path into `AudioStreamPlaybackMicrophone`, which is the class that handles the microphone input for playback in Godot's audio playback system. I can see the reasoning, but in my opinion it makes the class ambiguous, and adds unnecessary complexity to it.

[The second PR](https://github.com/godotengine/godot/pull/105244) was created after maintainer feedback which suggested the perspective to handle the microphone input more like other control inputs, like mouse, keyboard and controllers, and add it to the `Input` class. That PR ended up similar to this PR. It's not bad, but the kind of data microphones generate is very different to the data `Input` usually deals with For that reason, I believe `AudioServer` is a more suitable class to working with it appropriately.

[The third PR](https://github.com/godotengine/godot/pull/108773) was created after feedback that the system proposed in `Input` could not deal with multiple microphones at once, and was therefore underdesigned. 
However, I believe this feedback was misguided. By our [contribution guidelines](https://contributing.godotengine.org/en/latest/engine/guidelines/best_practices.html#to-solve-the-problem-it-has-to-exist-in-the-first-place), we should strive to only solve problems that people actually have. Using multiple microphones at once is not a feature that has been requested by users. Even dedicated audio software does not support capturing input from multiple audio inputs simultaneously a lot of the time, probably because it's so rarely needed in actual projects. @goatchurchprime's PR indulging the feedback, and adding a microphone server and feeds, ended up [way more complicated](https://github.com/godotengine/godot/pull/113288) than this one, with multiple new classes exposed, and functionality skeletons added for functions that are unlikely to be needed by anyone anytime soon. An alternative implementation by @adamscott attempted to implement the feature wholesale, but ended up even more complicated. In contrast to this PR, which adds and exposes barely any features, and solves the microphone needs of most games perfectly, I think this clearly shows why we should add demand-driven infrastructure, rather than infrastructure designed for a potential future case that is unlikely to be needed by most Godot engine users. (on that note, the addition of `AudioStreamPlaybackMicrophone` idea was probably premature in the first place, since it's unlikely many games want to play back the player's voice to them from their own speaker).
Even if people run into limitations with the system added here, we can deprecate this system and add a better one that solves whatever problem users run into at that time. Since this is an extremely small solution, it's easy to sculpt or remove completely when it outlives its designed purpose.

**All in all, I believe this PR is the appropriate solution for the problem at hand.** 
The PR is low risk, especially with @goatchurchprime's rigorous testing with his [bespoke tool](https://github.com/goatchurchprime/godot-demo-projects/tree/gtch/mic_input/audio/mic_input).
It is also potentially high-impact, since for the first time in Godot's history, it will be possible to have stable voice-over-ip technology in Godot made games. A demand for this is evident by the popularity of @goatchurchprime's extension [two-voip](https://github.com/goatchurchprime/two-voip-godot-4), which even in the current state of the godot interface is attracting users.

Due to the reasons given above, I'd like to restate my initial comment that I think this should be merged into 4.6.

File: doc/classes/AudioServer.xml [hunk 14]
```diff
@@ -124,13 +124,34 @@
...
 			<description>
 				Returns the names of all audio input devices detected on the system.
 				[b]Note:[/b] [member ProjectSettings.audio/driver/enable_input] must be [code]true[/code] for audio input to work. See also that setting's description for caveats related to permissions and operating system privacy settings.
 			</description>
 		</method>
+		<method name="get_input_frames">
+			<return type="PackedVector2Array" />
+			<param index="0" name="frames" type="int" />
+			<description>
+				Returns a [PackedVector2Array] containing exactly [param frames] audio samples from the internal microphone buffer if available, or an empty [PackedVector2Array].
```
Comment (AThousandShips) [inline doc/classes/AudioServer.xml]:
```suggestion
				Returns a [PackedVector2Array] containing exactly [param frames] audio samples from the internal microphone buffer if available, otherwise returns an empty [PackedVector2Array].
```

File: doc/classes/AudioServer.xml [hunk 15]
```diff
@@ -124,13 +124,34 @@
...
+				The buffer is filled at the rate of [method get_input_mix_rate] frames per second when [method set_input_device_active] has successfully been set to true.
```
Comment (AThousandShips) [inline doc/classes/AudioServer.xml]:
```suggestion
				The buffer is filled at the rate of [method get_input_mix_rate] frames per second when [method set_input_device_active] has successfully been set to [code]true[/code].
```

File: doc/classes/AudioServer.xml [hunk 16]
```diff
@@ -330,6 +351,14 @@
 				[b]Note:[/b] This is enabled by default in the editor, as it is used by editor plugins for the audio stream previews.
 			</description>
 		</method>
+		<method name="set_input_device_active">
+			<return type="int" enum="Error" />
+			<param index="0" name="active" type="bool" />
+			<description>
+				If [param active] is [code]true[/code], start the microphone input stream specified by [member input_device] or return an error if failed.
+				If [param active] is [code]false[/code], stop the input stream if it is running.
```
Comment (AThousandShips) [inline doc/classes/AudioServer.xml]:
```suggestion
				If [param active] is [code]true[/code], starts the microphone input stream specified by [member input_device] or returns an error if it failed.
				If [param active] is [code]false[/code], stops the input stream if it is running.
```

**Comment by goatchurchprime** [comment]
I just want to add that there are a number of users of my [twovoip plugin](https://github.com/goatchurchprime/two-voip-godot-4) who are waiting on this issue (they've submitted tickets about the sound quality on my repo that are actually due to this Godot problem), and who would probably begin using this feature as soon as it's on a development release.

Some have already tested that it's good with an earlier PR, but not everyone is set up for compiling PRs very easy -- especially the export templates.

The important point is that I expect this is going to get tested by users on different pieces of hardware right away, so we're going to find out about any problems I've not anticipated very quickly, and I am committed to getting on top of them asap.

**Review by lyuma — APPROVED** [review]
The code looks good. the only risk is this api is designed for single-consumer since it has only one global offset variable, and modifies with the same start/stop state as AudioStreamMicrophone.

Some day, I would prefer a higher level object oriented API which would also be used by `AudioStreamMicrophone`, that holds the offset internally and and can increment/decrement a "active counter" that will control start / stop so you can have two consumers of the audio data without interference. For the object oriented idea, we'd need a Vector<AudioFrame> version of the `get_input_frames` function (which `AudioStreamPlaybackMicrophone::_mix_internal` would call). 

As for my review, the code should do what it says so I'll approve.

I consider this to be a low level API which ideally users wouldn't use directly. If there was more time I'd really prefer an object oriented api that will have exactly the same performance but avoids the single global offset variable stored in AudioServer which limits our ability to improve things in the future.

**Comment by Ivorforce** [comment]
> The code looks good. the only risk is this api is designed for single-consumer since it has only one global offset variable, and modifies with the same start/stop state as AudioStreamMicrophone.

Right, this was also my primary reservation.
However, after some consideration, I think we don't need to address this concern now, at least not until people actually raise it as a limitation. I think the vast majority of games will only need a single consumer of this microphone data. Especially, `AudioStreamMicrophone` will probably not be used much at all when this API is available, because playing the player's voice back to them from their own speakers is not very useful for most games.

> Some day, I would prefer a higher level object oriented API which would also be used by AudioStreamMicrophone, that holds the offset internally and and can increment/decrement a "active counter" that will control start / stop so you can have two consumers of the audio data without interference. For the object oriented idea, we'd need a Vector version of the get_input_frames function (which AudioStreamPlaybackMicrophone::_mix_internal would call).
> I consider this to be a low level API which ideally users wouldn't use directly. If there was more time I'd really prefer an object oriented api that will have exactly the same performance but avoids the single global offset variable stored in AudioServer which limits our ability to improve things in the future.

I also think it's likely we'll have some more comprehensive API eventually, and this code will be deprecated.
However, as mentioned above, I don't think we're at a state yet where we can confidently design this API. If we were to design it now, it would probably look like https://github.com/godotengine/godot/pull/108773, and add a ton of complexity most people don't need.
As players will start using the microphone input for voip or game controls, I'm sure they'll raise the limitations they'll run into, and we can design the future API around those concerns.

**Comment by allenwp** [comment]
> I also think it's likely we'll have some more comprehensive API eventually, and this code will be deprecated.

With multiple maintainers expecting this to be deprecated in the future: should we mark the API as experimental? This way users can expect to need to update their code to a new API in the future (and if they don’t need to, then that’s just a bonus to them).

**Review by zodiepupper — APPROVED** [review]

File: doc/classes/AudioServer.xml [hunk 17]
```diff
@@ -124,13 +124,34 @@
 				Returns the name of the current audio driver. The default usually depends on the operating system, but may be overridden via the [code]--audio-driver[/code] [url=$DOCS_URL/tutorials/editor/command_line_tutorial.html]command line argument[/url]. [code]--headless[/code] also automatically sets the audio driver to [code]Dummy[/code]. See also [member ProjectSettings.audio/driver/driver].
 			</description>
 		</method>
+		<method name="get_input_buffer_length_frames">
```
Comment (adamscott) [inline doc/classes/AudioServer.xml]:
```suggestion
		<method name="get_input_buffer_length_frames" experimental="">
```

File: doc/classes/AudioServer.xml [hunk 18]
```diff
@@ -124,13 +124,34 @@
...
+			</description>
+		</method>
 		<method name="get_input_device_list">
 			<return type="PackedStringArray" />
 			<description>
 				Returns the names of all audio input devices detected on the system.
 				[b]Note:[/b] [member ProjectSettings.audio/driver/enable_input] must be [code]true[/code] for audio input to work. See also that setting's description for caveats related to permissions and operating system privacy settings.
 			</description>
 		</method>
+		<method name="get_input_frames">
```
Comment (adamscott) [inline doc/classes/AudioServer.xml]:
```suggestion
		<method name="get_input_frames" experimental="">
```

File: doc/classes/AudioServer.xml [hunk 19]
```diff
@@ -124,13 +124,34 @@
...
+			<return type="PackedVector2Array" />
+			<param index="0" name="frames" type="int" />
+			<description>
+				Returns a [PackedVector2Array] containing exactly [param frames] audio samples from the internal microphone buffer if available, otherwise returns an empty [PackedVector2Array].
+				The buffer is filled at the rate of [method get_input_mix_rate] frames per second when [method set_input_device_active] has successfully been set to [code]true[/code].
+				The samples are signed floating-point PCM values between [code]-1[/code] and [code]1[/code].
+			</description>
+		</method>
+		<method name="get_input_frames_available">
```
Comment (adamscott) [inline doc/classes/AudioServer.xml]:
```suggestion
		<method name="get_input_frames_available" experimental="">
```

File: doc/classes/AudioServer.xml [hunk 20]
```diff
@@ -330,6 +351,14 @@
 				[b]Note:[/b] This is enabled by default in the editor, as it is used by editor plugins for the audio stream previews.
 			</description>
 		</method>
+		<method name="set_input_device_active">
```
Comment (adamscott) [inline doc/classes/AudioServer.xml]:
```suggestion
		<method name="set_input_device_active" experimental="">
```

File: drivers/pulseaudio/audio_driver_pulseaudio.cpp [hunk 21]
```diff
@@ -555,6 +555,8 @@ void AudioDriverPulseAudio::thread_func(void *p_udata) {
 			}
 
 			// User selected a new input device, finish the current one so we'll init the new input device
+			// (If AudioServer.set_input_device() did not set the value when the microphone was running,
+			//  this section with its problematic error handling could be deleted.)
```
Comment (adamscott) [inline drivers/pulseaudio/audio_driver_pulseaudio.cpp]:
```suggestion
			// (If `AudioServer.set_input_device()` did not set the value when the microphone was running,
			//  this section with its problematic error handling could be deleted.)
```

File: servers/audio/audio_server.cpp [hunk 22]
```diff
@@ -109,6 +109,9 @@ void AudioDriver::input_buffer_write(int32_t sample) {
 			input_size++;
 		}
 	} else {
+		// This protection was added in GH-26505 due to a "possible crash".
+		// This cannot have happened unless two non-locked threads entered function simultaneously, which was possible when multiple calls to
+		// AudioDriver::input_start() did not raise an error condition.
```
Comment (adamscott) [inline servers/audio/audio_server.cpp]:
```suggestion
		// This protection was added in GH-26505 due to a "possible crash".
		// This cannot have happened unless two non-locked threads entered function simultaneously, which was possible when multiple calls to
		// `AudioDriver::input_start()` did not raise an error condition.
```

File: platform/android/audio_driver_opensl.cpp [hunk 23]
```diff
@@ -271,28 +271,30 @@ Error AudioDriverOpenSL::input_start() {
...
+	if (recordBufferQueueItf) {
+		(*recordBufferQueueItf)->Clear(recordBufferQueueItf);
+		recordBufferQueueItf = nullptr;
+	}
+	if (recorder) {
+		(*recorder)->Destroy(recorder);
+		recorder = nullptr;
 	}
 
 	return OK;
```
Comment (adamscott) [inline platform/android/audio_driver_opensl.cpp:300]: Why did the errors checks were removed? I understand that we want to return OK even if the driver wasn't recording, but removing every error check doesn't help either.

File: servers/audio/audio_server.cpp [hunk 24]
```diff
@@ -1842,6 +1845,72 @@ void AudioServer::set_input_device(const String &p_name) {
...
+}
+
+int AudioServer::get_input_frames_available() {
+	AudioDriver *ad = AudioDriver::get_singleton();
+	ad->lock();
+	int64_t input_position = ad->get_input_position();
+	if (input_position < input_buffer_ofs) {
+		int64_t buffsize = ad->get_input_buffer().size();
+		input_position += buffsize;
+	}
```
Comment (adamscott) [inline servers/audio/audio_server.cpp:1873]: In newer code, we don't tend to create contracted variable names. (i.e. `buffer_size` instead of `buffsize`.) But here, we can just skip the variable initialization.

```suggestion
	if (input_position < input_buffer_ofs) {
		input_position += ad->get_input_buffer().size();
	}
```

**Review by adamscott — APPROVED** [review]
There's a few changes to make, but I'll give my approval anyway right now.

This saga has been long time coming.

First of all, I tip my hat to @goatchurchprime's tenacity and to @Ivorforce for taking this over.

---

If it was just by me, I wouldn't merge this PR to be honest. While the code is well made, it exposes a buffer that wasn't made to be exposed. All of this from an API that was built intending audio input to be used as an audio device (instead of as data entry).

We need a refactor. I [created a branch](https://github.com/godotengine/godot/compare/master...adamscott:godot:new-microphone-feeds-mk2) that implements a prototype of a `MicrophoneServer`. While still flawed, I was able to record from two distinct inputs at a time. While games may not need multiple entries, we must still understand that Godot is used more and more as a general purpose engine. I showed @goatchurchprime that Web apps like Jitsi use multiple inputs to display VU meters of the available input devices to facilitate selection:

Image

It's also more in line with the current Godot way of dealing with input devices. See [`CameraServer`](https://docs.godotengine.org/en/stable/classes/class_cameraserver.html) for more details. (even if I found multiple flaws of `CameraServer` while experimenting on my `MicrophoneServer`)

But a refactor is costly and takes time. And people needing some features cannot wait.

The arguments made by @Ivorforce are convincing. Even if I'm not fully convinced, I'm enough to give this PR a go.

**Comment by allenwp** [comment]
I’m going to go out on a limb and speak on behalf of @goatchurchprime, who may not be available to respond quickly today:

I suspect that any change requests can be applied, including reintroducing error checking, and these can be applied directly to this branch, squashed, and merged to get this in before feature freeze. Marking it as experimental makes this acceptable to me.

Let me know if you need me to come in and do this; I may have enough knowledge to do so without risk.

**Comment by Ivorforce** [comment]
> I suspect that any change requests can be applied, including reintroducing error checking, and these can be applied directly to this branch, squashed, and merged to get this in before feature freeze. Marking it as experimental makes this acceptable to me.

Agreed.

> Let me know if you need me to come in and do this; I may have enough knowledge to do so without risk.

Yea, that would be appreciated. It doesn't look like @goatchurchprime is online today.
Edit: Seems like we were wrong :)

File: platform/android/audio_driver_opensl.cpp (hunk 23 above)
Comment (goatchurchprime) [reply platform/android/audio_driver_opensl.cpp:300]: It is not useful for `input_stop()` to have an error condition, because you couldn't assume anything (is the input still running?).

I've written this function to clean up the incomplete states `init_input_device()` could leave the classes in with its heavy use of the `ERR_FAIL_COND_V` macro to quit early.

For these three specific functions [the docs say](https://registry.khronos.org/OpenSL-ES/specs/OpenSL_ES_Specification_1.1.pdf):

1. The only possible error for `SetRecordState()` is `SL_RESULT_PARAMETER_INVALID`, which we can rule out.
image

2. `SLBufferQueueItf::Clear()` has no error case

image

3. Destroy() has no return value.

image

**Comment by goatchurchprime** [comment]
I'm leery of making any code changes when I don't have time to retest them properly (typos happen).

If this gets merged there will be a reasonable amount of testing across all platforms very soon, so we can count on there something needing to be fixed early on (if there is a bug, which there almost always is), and that would be a better time to add these changes in.

**Comment by allenwp** [comment]
OK, I’ll stay out of the way!

File: platform/android/audio_driver_opensl.cpp (hunk 23 above)
Comment (Ivorforce) [reply platform/android/audio_driver_opensl.cpp:300]: It would be possible to collect the errors and return them at the end, after making sure as much as possible is cleaned up.
Anyway, I agree with Julian that for now trying to clean up as much as possible is preferable to exiting early and leaving behind a broken state. We can try to make this even more robust later. Edit: Or not, if there's no error state to begin with!

**Comment by Repiteo** [comment]
Thanks!
