### PR TITLE
Fix shadow peter-panning with default spotlight

### LINKED ISSUE #101857: SpotLight3D shadow has significant peter-panning with default settings (4.4-dev7 and 4.4-beta1)
### Tested versions

Reproducible in: 4.4-dev7 and 4.4-beta1
Not reproducible in: 4.4-dev6 and before

### System information

Godot v4.4.dev7 - Windows 11 (build 22631) - Single-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 (NVIDIA; 32.0.15.6603) - 13th Gen Intel(R) Core(TM) i7-13700K (24 threads)

### Issue description

Shadow casting SpotLight3D has noticeable peter-panning effect with default bias value. Example below:

Image

### Steps to reproduce

Create a new 3D scene
Add floor into the scene and add mesh on the floor
Add SpotLight3D and enable shadows
Point the spotlight towards mesh and observe shadow it casts

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Flarkk**
Fixes #101857.

A regression with default spotlights exhibiting significant shadow peter-panning was introduced in #100319.

This PR fixes it with 2 changes :
1. sets the now-fixed light znear to *0.025* instead of *0.005*. This is to match the former behavior of default spotlights and omnis (*range = 5* driving *znear = 0.005 * 5 = 0.025*)
2. applies bias as a constant offset in clip space. Now znear is fixed, *z = w* in clip space always represents the same *z = znear* in view space, therefore there is no need to rescale bias before applying it in clip space anymore

This is how default point lights' shadows look like with this PR.
Appearance also does not depend on range.
| Default Spotlight | Default Omni |
| --- | --- |
| range = 5 and bias =  0.03| range = 5 and bias = 0.1 |
| Capture d’écran du 2025-01-23 09-19-01 | Capture d’écran du 2025-01-23 09-19-34 |

I'd need other pairs of eyes especially on change no. 2. I was originally counting on Omni shadows implementation to serve as a reference to double check Spotlight implementation, but it turned out that they are rather different both code-wise and math-wise.

### CODE REVIEW

File: servers/rendering/renderer_scene_cull.cpp [hunk 1]
```diff
@@ -2510,7 +2510,7 @@ bool RendererSceneCull::_light_instance_update_shadow(Instance *p_instance, cons
 				}
 
 				real_t radius = RSG::light_storage->light_get_param(p_instance->base, RS::LIGHT_PARAM_RANGE);
-				real_t z_near = MIN(0.005f, radius);
+				real_t z_near = MIN(0.025f, radius);
```
Comment (clayjohn) [inline servers/rendering/renderer_scene_cull.cpp:2513]: This will work at the default radius, but its going to break once the radius changes isn't it?

Comment (Flarkk) [reply servers/rendering/renderer_scene_cull.cpp:2513]: It works at all radiuses.
It's just that now with the default settings (range, bias) it has the same appearance as before, i.e. you don't have to manually set a lower bias to get the same results as before.

Comment (Flarkk) [reply servers/rendering/renderer_scene_cull.cpp:2513]: It works with all radiuses. The reason is different for Omnis and Spotlights.
#### For Omnis
Bias is applied in **view space** as a constant  z-offset :
https://github.com/godotengine/godot/blob/d08ff57148c42b63e74adb669f6937d35fde1f6e/servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl#L435-L437
https://github.com/godotengine/godot/blob/d08ff57148c42b63e74adb669f6937d35fde1f6e/servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl#L543

This is because `omni_lights.data[idx].shadow_matrix` is **not a projection matrix** as its name may suggest but [the light's modelview matrix](https://github.com/godotengine/godot/blob/d08ff57148c42b63e74adb669f6937d35fde1f6e/servers/rendering/renderer_rd/storage_rd/light_storage.cpp#L982-L984).

:point_right: None of the above depend on the shadow *projection* matrix, therefore the bias does not depend on the range.

#### For Spotlights
Bias is applied in **clip space**, now as a constant z-offset : see diff of  [scene_forward_lights_inc.glsl
](https://github.com/godotengine/godot/pull/101952/files#diff-aa6868a9e3e4496f8debd4ec9d3e1edeebe3249c8f269a5585276766fed157df)
This is because unlike Omnis, `spot_lights.data[idx].shadow_matrix` *is* the [shadow projection matrix](https://github.com/godotengine/godot/blob/d08ff57148c42b63e74adb669f6937d35fde1f6e/servers/rendering/renderer_rd/storage_rd/light_storage.cpp#L1004-L1006).

Because znear is also constant since #100319, clip space coordinates do not depend on the range anymore at the vincinity of clip.z = 1.0 (near plane)

Comment (Flarkk) [reply servers/rendering/renderer_scene_cull.cpp:2513]: This now makes me wonder if I should still keep the scaling by `light_length` : 
```glsl
splane.z += spot_lights.data[idx].shadow_bias / light_length
```

Without it shadows might now be distorted near the light's range.
Will make a test with some geometry more complex than a box.

File: servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl [hunk 2]
```diff
@@ -733,7 +733,7 @@ void light_process_spot(uint idx, vec3 vertex, vec3 eye_vec, vec3 normal, vec3 v
 		vec4 v = vec4(vertex + normal_bias, 1.0);
 
 		vec4 splane = (spot_lights.data[idx].shadow_matrix * v);
-		splane.z += spot_lights.data[idx].shadow_bias / (light_length * spot_lights.data[idx].inv_radius);
+		splane.z += spot_lights.data[idx].shadow_bias;
```
Comment (Flarkk) [inline servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl:736]: The other comment by @clayjohn now makes me wonder if I should still keep the scaling by `light_length` : 
```glsl
splane.z += spot_lights.data[idx].shadow_bias / light_length
```

Without it shadows might now be distorted close to the light's range.
Will make a test with some geometry more complex than a box.

Comment (Flarkk) [reply servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl:736]: Did a few tests and restoring `light_length` didn't change anything visible on the shape of the shadow, but reintroduced a lot of self-shadowing as soon as the fragment is farther apart from the spotlight than ~40 units.
This is not a surprise in the end as dividing by `light_length` essentially cancels out the bias effect for far away fragments.
I'm going to keep it as is for now, unless other contributors see something I would have overlooked.

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected.

Out of curiosity, I've tried putting SpotLights at extreme ranges and while shadowing does work correctly *initially*, it will break down once you change the spot range again, even after reloading the scene or toggling all lights in the scene.

**Testing project:** [test_pr_101952.zip](https://github.com/user-attachments/files/18538854/test_pr_101952.zip)

https://github.com/user-attachments/assets/4e997b17-7239-47e3-b176-90cb4b3c9924

It is not an issue of the shadowmap not being updated, as you can clearly notice the shadowmap being updated in this video (focus on the buildings' shadows):

https://github.com/user-attachments/assets/387b8d3f-6254-407c-92a8-1ae558ed010b

**Comment by Flarkk** [comment]
@Calinou I watched your videos very closely again.

I don't have the impression the building's shadows change before / after you reset the lights range.

See these captures from the 1st video : 
| Before re-changing | After re-changing |
|---|---|
|image|image|

What's changing for sure is the stripped pattern I cannot understand right now exhibited by the spotlight.

**Comment by mrjustaguy** [comment]
Calinou, are you using 4,4,16,64 quadrants? to me it seems like what happened is a quadrant shift, which is a bit buggy

**Comment by Calinou** [comment]
> @Calinou, are you using 4,4,16,64 quadrants? to me it seems like what happened is a quadrant shift, which is a bit buggy

I was using the default quadrant project settings. The project has a fair amount of shadow-casting spotlights (more than 8), so maybe it was due to that.

File: servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl (hunk 2 above)
Comment (clayjohn) [reply servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl:736]: I don't think this makes sense. Clip space is not a linear space. So using a fixed bias is bound to cause issues at one end of the space or the other.

Comment (Flarkk) [reply servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl:736]: Both this change and the other are needed to fix the regression :
- the other one ensures peter-panning is as small as before with default settings
- this change makes peter-panning constant no matter the light range

And for clarity:
Clip space *is* linear - it's just a scaled / skewed / translated version of the view space.
You maybe meant *ndc* space which indeed *is not* because of perspective division.

Applying a fixed bias in clip space is the way to go.
Prior to this PR, the bias was scaled because the near plane was dynamically adjusted based on the light's range.
One unit in clip space represents different depths depending on the near plane setting.
The scaling factor was intended to compensate for this, ensuring consistent peter-panning regardless of the light's range.

**Comment by Flarkk** [comment]
I made tests with the MRP provided by @Calinou.

### Banding artifacts
The banding are self-shadowing artifacts.
Increasing the bias a little bit gets rid of them, at the cost of loosing shadows on smaller details.
I believe there is nothing wrong in this, just the normal behavior when the light's range gets bigger and the geometry farther away.

The only point still unclear is why such banding doesn't appear with an Omni light instead of a Spotlight, with identical settings. I think it's related to the resolution of the shadow map (spotlights have a single texture where omnis have a cubemap), but this assumption would deserve to be confirmed.

### Possibly broken shadowing when changing range

> while shadowing does work correctly initially, it will break down once you change the spot range again

I couldn't reproduce that. And I couldn't see anything going wrong with the shadows in any of the 2 videos you shared (see my previous comment https://github.com/godotengine/godot/pull/101952#issuecomment-2613841780)

What I noticed though in the MRP is that there is no banding artifact at startup. They re-appeared as soon as I changed the light's range. It's like the bias was set internally to a high value (no self-shadowing) and got back to normal then.

Worth also noting that after saving the project with another very large range and repoening it, I couldn't reproduce this anymore. So it's still not clear what's the cause of if, but I think it's unrelated to this PR.

File: servers/rendering/renderer_scene_cull.cpp (hunk 1 above)
Comment (Flarkk) [reply servers/rendering/renderer_scene_cull.cpp:2513]: Happy to clarify or do anything more to make you fully comfortable with it.

> this change maintains the high risk of self-shadowing for high ranges

Self shadowing happens with large ranges *only on far away geometry* : now we use reverse-z precision is much less of a problem even with very small z-near.

This means there should not be any visual change on shadows reasonably closeby geometry, even with large light ranges.

File: servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl (hunk 2 above)
Comment (clayjohn) [reply servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl:736]: > And for clarity:
> Clip space is linear - it's just a scaled / skewed / translated version of the view space.
> You maybe meant ndc space which indeed is not because of perspective division.

That's right, my mistake. 

This should be fine then. I tested it locally and it appears to be at least as good as the situation in 4.3. So let's go ahead with this and see if anything else breaks.

**Review by clayjohn — APPROVED** [review]
Let's go ahead with this. 

I'm starting to get nervous with all these bandaid fixes on top of bandaid fixes, but the changes in this PR make sense, so let's test them out and see. Worst case scenario we get more regressions in beta 3 and then we can just revert for 4.4 and try again for 4.5

**Comment by akien-mga** [comment]
Thanks!

**Comment by Flarkk** [comment]
> Worst case scenario we get more regressions in beta 3 and then we can just revert for 4.4 and try again for 4.5

Agree. For later reference in case we need to move back, we'll need to revert all three #100319, #100862 and this one. This will revert spotlight shadows to the exact 4.3 behavior.
