### PR TITLE
[Web] Fix inappropriate `memfree()` use

### LINKED ISSUE #108873: [Web] Some exports are broken and fail to load (memory out of bounds)
### Tested versions

- Reproducible since #107415

### System information

Godot v4.5.beta (960fc52f0) - macOS Unknown (26.0.0) - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M3 Max (Apple9) - Apple M3 Max (16 threads) - 48.00 GiB memory

### Issue description

Reported initially by @Frozenfire92:

Image

### Steps to reproduce

1. Export a (big) Web project 
2. Wait that the loading bar completes
3. See the error

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by adamscott**
- ~~Adds `godot_js_runtime_free()`, a way to call `GodotRuntime.free()` from C++~~
- ~~Fixes an issue where `memfree()` would throw, but `GodotRuntime.free()` wouldn't.~~

- Uses `free()` instead of `memfree()` as that memory was not allocated by Godot

Fixes #108873

### CODE REVIEW

File: platform/web/web_main.cpp [hunk 1]
```diff
@@ -108,7 +108,7 @@ void print_web_header() {
 	// Emscripten.
 	char *emscripten_version_char = godot_js_emscripten_get_version();
 	String emscripten_version = vformat("Emscripten %s", emscripten_version_char);
-	memfree(emscripten_version_char);
+	free(emscripten_version_char);
```
Comment (bruvzg) [inline platform/web/web_main.cpp:112]: I would add a comment to ensure it is not accidentally changed back to `memfree` in the future.

**Review by Repiteo — APPROVED** [review]
Makes sense

**Comment by Frozenfire92** [comment]
Confirming this fixes #108873 for me

**Review by Faless — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
