### PR TITLE
fix #32588 out of range crash in language server

### LINKED ISSUE #32588: Language Server crashes Editor when function is parsed
**Godot version:**
1d9233c3882afe888b9396f7f2aac917d4dcac4d

**OS/device including version:**
Windows x64

**Issue description:**
The editor crashes when the language server parses the code du to an out of range error.
(gdscript_extend_parser.cpp:302)
`lines[r_symbol.range.end.line]` line == lines.size()
**Steps to reproduce:**

1. Open a project
2. Use an external editor via the lsp (VS Code)
3. Write `func _` and get the autocompletion
4. Select any
5. Crash of the Editor

Open a new project
**Minimal reproduction project:**
[project.zip](https://github.com/godotengine/godot/files/3694450/project.zip)

### PR DESCRIPTION
**Pull request by HaSa1002**
fixes #32588

### CODE REVIEW

File: modules/gdscript/language_server/gdscript_extend_parser.cpp [hunk 1]
```diff
@@ -299,7 +299,7 @@ void ExtendGDScriptParser::parse_function_symbol(const GDScriptParser::FunctionN
 	r_symbol.range.start.line = line;
 	r_symbol.range.start.character = p_func->column;
 	r_symbol.range.end.line = MAX(p_func->body->end_line - 2, p_func->body->line);
```
Comment (Geequlim) [inline modules/gdscript/language_server/gdscript_extend_parser.cpp]: There is a bug on the GDScript parse with function body position here.
CC @vnen 
We'd better ensure the value is valid here maybe `CLAMP(p_func->body->end_line - 2, p_func->body->line, lines.size()-1)`

Comment (HaSa1002) [reply modules/gdscript/language_server/gdscript_extend_parser.cpp]: CLAMP does not work, because when end_line is -1 the body line will be exact the lines.size().
That one worked with my testing setup: (It got a bit messy using inlines and I am not quite sure about the result. It feels like to much work for the same result.)
```suggestion
	if (p_func->body->end_line - 2 > p_func->body->line) {
		r_symbol.range.end.line = p_func->body->end_line - 2;
	} else if (p_func->body->line < lines.size()) {
		r_symbol.range.end.line = p_func->body->line;
	} else {
		r_symbol.range.end.line = lines.size() - 1;
	}
```

File: modules/gdscript/language_server/gdscript_extend_parser.cpp [hunk 2]
```diff
@@ -298,7 +298,7 @@ void ExtendGDScriptParser::parse_function_symbol(const GDScriptParser::FunctionN
 	const int line = LINE_NUMBER_TO_INDEX(p_func->line);
 	r_symbol.range.start.line = line;
 	r_symbol.range.start.character = p_func->column;
-	r_symbol.range.end.line = MAX(p_func->body->end_line - 2, p_func->body->line);
+	r_symbol.range.end.line = (p_func->body->end_line - 2 > p_func->body->line) ? p_func->body->end_line - 2 : ((p_func->body->line < lines.size()) ? p_func->body->line : lines.size() - 1);
```
Comment (akien-mga) [inline modules/gdscript/language_server/gdscript_extend_parser.cpp]: That's not very readable with two ternary operators and comparisons like that.

**Comment by HaSa1002** [comment]
Okay found the real bug while looking at the `symbol.range.start.line = LINE_NUMBER_TO_INDEX(p_func->body->line);` line

**Comment by HaSa1002** [comment]
Should be fixed now. (My tests worked)

**Review by Geequlim — COMMENTED** [review]
Maybe add another line after  `r_symbol.range.end.line = MAX(p_func->body->end_line - 2, p_func->body->line);`

`r_symbol.range.end.line = MIN(r_symbol.range.end.line, lines.size()-1);`

**Review by Geequlim — COMMENTED** [review]
I think 
```c
r_symbol.range.end.line = MAX(p_func->body->end_line - 2, r_symbol.range.start.line);
```
should fix this

**Comment by HaSa1002** [comment]
Fixed using @Geequlim last suggestion.

**Review by Geequlim — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
