### PR TITLE
Fix TextEdit v_scroll_speed invalid values breaks wheel scrolling

### LINKED ISSUE #58009: Text editor ``v_scroll_speed`` setting can break mouse wheel scrolling
### Godot version

b50ec3753e24eea658c00b052388b626a28e08d2

### System information

Windows 10

### Issue description

Some values of text_editor/behavior/navigation/v_scroll_speed Editor settings breaks mouse wheel scrolling of TextEdit.

If the value is lesser than 8, no scrolling occurs.

If the value is set to a negative value, scrolling is broken as it scrolls to the bad side and never reach the target scroll value until the top or bottom of the script.

### Steps to reproduce

Open any long script (you can copy/paste the default template multiples time as it don't have to be valid script)

In Editor Settings, change the value of text_editor/behavior/navigation/v_scroll_speed :
- to a negative value : mouse wheel scroll don't work anymore (scrolls until the top or the bottom of file)
- to a value under 8 : no scroll at all.

### Minimal reproduction project

Not needed

### PR DESCRIPTION
**Pull request by jmb462**
Fixes #58009

### Issue description

Some values of text_editor/behavior/navigation/v_scroll_speed Editor settings breaks mouse wheel scrolling of TextEdit.

### Identified causes

- Missing hint_range in property declaration to prevent null or negative values
- If the value is under 8, the increment in vscroll position is under its range step, so the value keeps unchanged and wheel scroll is blocked.

### Fix proposal

- Add hint_range "1, 10000,1" in property declaration 
10000 leads to immediately scroll to destination. As comparison, clicking on minimap leads to a 3000 scrolling speed and is already nearly instantaneous.

- Ensure that scrolling speed is equal or greater than the scrollbar step to prevent blocking mouse wheel scroll.

### After (I roll the mouse wheel a LOT to see the scrolling speed)
fixed

### CODE REVIEW

**Review by bruvzg — COMMENTED** [review]
In addition to the property hint, it's probably worth adding the same checks to the `TextEdit::set_v_scroll_speed` and reject invalid values. Property hint will help when it's set from UI, but won't if it's set in the config file or `set_v_scroll_speed` is called directly.

**Comment by jmb462** [comment]
For too low values, should you set it to the minimum accepted value or should we return without modifying the value and throw an error/warning ?

**Review by Paulb23 — COMMENTED** [review]
Would suggest using `ERR_FAIL_COND` rather then `MAX` otherwise looks good.

**Comment by jmb462** [comment]
> Would suggest using `ERR_FAIL_COND` rather then `MAX` otherwise looks good.

You're right. Done.

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -4390,6 +4395,8 @@ int TextEdit::get_h_scroll() const {
 }
 
 void TextEdit::set_v_scroll_speed(float p_speed) {
+	// Prevent setting a vertical scroll speed value under 1.0
+	ERR_FAIL_COND(v_scroll_speed < 1.0);
```
Comment (Paulb23) [inline scene/gui/text_edit.cpp:4399]:
```suggestion
	ERR_FAIL_COND(p_speed < 1.0);
```

Comment (jmb462) [reply scene/gui/text_edit.cpp]: Of course... Thanks...

**Review by Paulb23 — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
