### PR TITLE
Fix String.ends_with() for empty string arguments

### LINKED ISSUE #45299: String.ends_with("") returns false
**Godot version:**
3.2.3.stable

**Issue description:**
`String.ends_with()` returns false when empty string is passed as an argument. It should return true (same as `String.begins_with()` does).

**Steps to reproduce:**
```
# Incorrect:
print("".ends_with("")) # False
print("aaa".ends_with("")) # False

# Correct:
print("".begins_with("")) # True
print("aaa".begins_with("")) # True
```

### PR DESCRIPTION
**Pull request by VedatGunel**
Fixes #45299.

### CODE REVIEW

File: core/string/ustring.cpp [hunk 1]
```diff
@@ -3074,6 +3074,11 @@ int String::rfindn(const String &p_str, int p_from) const {
 }
 
 bool String::ends_with(const String &p_string) const {
+	int l = p_string.length();
```
Comment (akien-mga) [inline core/string/ustring.cpp:3077]: Please also use `l` further down instead of recalculating the `p_string.length()`.
(Make the changes with `git commit --amend` and `git push --force` to keep it all in one commit, see [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request)).

Comment (VedatGunel) [reply core/string/ustring.cpp:3077]: Done!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
