### PR TITLE
EditorNode: fix scene save over others

### LINKED ISSUE #10675: Godot saves scenes over others, producing data loss and stack overflows
Godot 3.0 master
Windows 10 64 bits

For some reason, I managed to save my main scene over another scene that was contained in the main scene, causing a circular reference:
```
main.tscn --> references character.tscn
character.tscn
```
Became:
```
main.tscn --> references character.tscn
character.tscn --> references character.tscn (because character.tscn contents became the same as main.tscn)
```
So I lost my character.tscn \o/ no idea how that happened.
I reverted character.tscn, now the project loads fine! Then I played again: re-stack overflow. Investigating...

**Second breakthrough:
I didn't dream, Godot just saved a scene over another, this time I lost the main scene completely, replaced by character.tscn contents D:**
image
I have two main scenes now (stored in files with different names though)

Repro steps:
1) Create a new project
2) Create a scene, save it as `a.tscn`
3) Create another scene in a second tab, save it as `b.tscn`
image
4) Click on scene `a`, hit Play, select the scene as main one etc
5) Click on scene `b`, hit Play: notice both scene tabs have the same name:
image
6) If you attempt to click on the first tab and Play, Godot will save the contents of `b.tscn` over `a.tscn` when auto-save occurs (not sure yet if that's exactly what happens, but it happens shortly after I see both tabs named the same)

### PR DESCRIPTION
**Pull request by ghost**
Fixes #10675 by partially reverts dd7145b

I might be wrong but I don't think this part has to do with the addition of EditorInterface?

### CODE REVIEW

**Comment by zinkkrysty** [comment]
Seems to fix the problem for me

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -983,7 +986,10 @@ void EditorNode::_dialog_action(String p_file) {
 			if (file->get_mode() == EditorFileDialog::MODE_SAVE_FILE) {
 
 				_save_default_environment();
-				_save_scene_with_preview(p_file);
+				if (scene_idx != editor_data.get_edited_scene() || _get_current_main_editor() == EDITOR_SCRIPT)
```
Comment (reduz) [inline editor/editor_node.cpp]: yeah i totally did not realize the first condition.
Fix is right, but just leave the condition as:
scene_idx != editor_data.get_edited_scene() 

as checking whether you are in spatial editor or not does not make any sense now

**Review by reduz — DISMISSED** [review]
