### PR TITLE
Fix transparent viewport backgrounds with custom clear color

### LINKED ISSUE #79778: Viewport background transparency not working with custom clear color in Mobile and Compatibility renderers
### Godot version

4.1.1.stable, 4.2.dev [6588a4a]

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1080 Ti (NVIDIA; 31.0.15.3640) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 Threads)

### Issue description

This is related to #72602, but since this also affects the Mobile renderer, this is likely a separate issue.

Setting the "Transparent BG" setting on a viewport is supposed to always keep the background transparent. On the Forward+ renderer, this setting is respected for all Environment Background Modes . On both the Mobile and Compatibility renderers, using the "Clear Color" background mode works with the transparent background, but using a "Custom Color" background does not render it as transparent.

Using Custom Color:
bug

Using Clear Color:
clear

### Steps to reproduce

1. Add a SubViewport to render some 3D scene and a way to view it (eg. a Sprite2D using the viewport as its texture)
2. Enable the "Transparent BG" option on the SubViewport
3. Setup an Environment for the 3D scene being rendered to the SubViewport (either on the Camera3D node or on a WorldEnvironment node)
4. Change the Background Mode of the Environment to Custom Color.

### Minimal reproduction project

[SkyTest.zip](https://github.com/godotengine/godot/files/12135972/SkyTest.zip)

### PR DESCRIPTION
**Pull request by LRFLEW**
This fixes #79778. This code change zeroes out the alpha component of the clear color. This basically just ports a change made in #61109 from the Forward+ renderer to the Mobile renderer, as well as an equivalent change to the Compatibility renderer.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Looks great!

If you want you can do the same fix for OpenGL (either in this PR or a followup). Clear color is set here: https://github.com/godotengine/godot/blob/0c2144da908a8223e188d27ed1d31d8248056c78/drivers/gles3/rasterizer_scene_gles3.cpp#L1982-L1984

**Comment by LRFLEW** [comment]
I went ahead and made the change to the PR for the Compatibility renderer. I tested it, and it *is* working, but with a caveat: The viewport's transparency doesn't seem to update until you reload the scene. I'm not sure why, but I'll look into it.

**Review by clayjohn — APPROVED** [review]

File: servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp [hunk 1]
```diff
@@ -932,13 +932,19 @@ void RenderForwardMobile::_render_scene(RenderDataRD *p_render_data, const Color
...
-				if (p_render_data->render_buffers->get_msaa_3d() != RS::VIEWPORT_MSAA_DISABLED) {
-					c.push_back(clear_color.srgb_to_linear()); // our resolve buffer
+			{
+				Color cc = clear_color.srgb_to_linear();
+				if (rb_data.is_valid()) {
+					cc.a = 0; // for transparent viewport backgrounds
 				}
-				if (using_subpass_post_process) {
-					c.push_back(Color()); // our 2D buffer we're copying into
+				c.push_back(cc); // our render buffer
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp:940]:
```suggestion
				c.push_back(cc); // Our render buffer.
```
As per the [style guide](https://docs.godotengine.org/en/latest/contributing/development/code_style_guidelines.html#comment-style-guide)

File: servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp [hunk 2]
```diff
@@ -932,13 +932,19 @@ void RenderForwardMobile::_render_scene(RenderDataRD *p_render_data, const Color
...
+				if (rb_data.is_valid()) {
+					if (p_render_data->render_buffers->get_msaa_3d() != RS::VIEWPORT_MSAA_DISABLED) {
+						c.push_back(clear_color.srgb_to_linear()); // our resolve buffer
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp:943]:
```suggestion
						c.push_back(clear_color.srgb_to_linear()); // Our resolve buffer.
```

File: servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp [hunk 3]
```diff
@@ -932,13 +932,19 @@ void RenderForwardMobile::_render_scene(RenderDataRD *p_render_data, const Color
...
+					}
+					if (using_subpass_post_process) {
+						c.push_back(Color()); // our 2D buffer we're copying into
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp:946]:
```suggestion
						c.push_back(Color()); // Our 2D buffer we're copying into.
```

File: servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp [hunk 4]
```diff
@@ -932,13 +932,19 @@ void RenderForwardMobile::_render_scene(RenderDataRD *p_render_data, const Color
...
 			// regular forward for now
 			Vector<Color> c;
-			c.push_back(clear_color.srgb_to_linear()); // our render buffer
-			if (rb_data.is_valid()) {
-				if (p_render_data->render_buffers->get_msaa_3d() != RS::VIEWPORT_MSAA_DISABLED) {
-					c.push_back(clear_color.srgb_to_linear()); // our resolve buffer
+			{
+				Color cc = clear_color.srgb_to_linear();
+				if (rb_data.is_valid()) {
+					cc.a = 0; // for transparent viewport backgrounds
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp:938]:
```suggestion
					cc.a = 0; // For transparent viewport backgrounds.
```

File: servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp (hunk 1 above)
Comment (LRFLEW) [reply servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp]: All these comments (other than the "for transparent viewport backgrounds" one) were in the code already. They were only marked as new / changed because I increased the indentation. I went ahead and addressed all of them in a force-push, though, since I'm in the area anyways.

Comment (clayjohn) [reply servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp]: Most comments in the codebase pre-date the style guide. So we are making an effort to make sure that they get updated when nearby code is changed. That way we get consistent style without muddying our git history too much.

**Comment by LRFLEW** [comment]
For the Compatibility renderer, I changed `if (render_data.transparent_bg)` to `if (rt->is_transparent)`, which resolved the issue of the background transparency not updating until the scene was reloaded. I don't really understand why the two are different, but the change worked.

I also made another change to force consistency between the renderers. Right now, setting an alpha on the custom clear color is ignored by the Forward+ and Mobile renderers. However, the alpha of the clear color was used when clearing the viewport in the Compatibility renderer, even with the viewport set to use an opaque background. I decided to force the alpha of the clear color to be 1 when the render target is not transparent to make the Compatibility renderer's behavior match the other renderers.

**Comment by LRFLEW** [comment]
From what I can tell, `RenderSceneBuffersGLES3::is_transparent` is redundant, since it's just duplicating `GLES3::RenderTarget::is_transparent`, and trying to keep them in sync looks to be a problem. I added a commit (not an amended commit since it might want to be approved / declined separately, and wanted to keep an easy way to undo it) that removes `RenderSceneBuffersGLES3::is_transparent` entirely, which turned out to be fairly simple. This directly addresses the issue I had when making this work with the Compatibility renderer, as well as addressing any other part of the Compatibility renderer that depended on `render_data.transparent_bg` being accurate.

**Comment by clayjohn** [comment]
> From what I can tell, `RenderSceneBuffersGLES3::is_transparent` is redundant, since it's just duplicating `GLES3::RenderTarget::is_transparent`, and trying to keep them in sync looks to be a problem. I added a commit (not an amended commit since it might want to be approved / declined separately, and wanted to keep an easy way to undo it) that removes `RenderSceneBuffersGLES3::is_transparent` entirely, which turned out to be fairly simple. This directly addresses the issue I had when making this work with the Compatibility renderer, as well as addressing any other parts of the Compatibility renderer that depended on `render_data.transparent_bg` being accurate.

Thanks for looking into that more deeply. Indeed it makes sense to remove ``is_transparent`` from render buffers. That was an artifact from before we merged RT and RB. 

Go ahead and squash the commits together, then we can merge this!

**Review by clayjohn — APPROVED** [review]

**Comment by YuriSizov** [comment]
Also needs a rebase now :)

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.4.
