### PR TITLE
Fix weird deselection behaviour with text field

### LINKED ISSUE #5375: Add CTRL+<left/right arrow> and CTRL+SHIFT+<left/right arrow> cursor operations in text inputs
In most programs:

* `CTRL+left arrow` moves to the start of the current word or else, the start of the previous word

* `CTRL+shift+left arrow` selects everything from the cursor position to the beginning of the current word, and previous words after repeated presses

The reverse applies for the right arrow. I think this is a simple but important function and should be implemented in Godot's text inputs.

(The text editor already has this functionality, BTW, but it's broken because when you use `CTRL+SHIFT+<left/right key>` and then use `CTRL+<left/right arrow>` the selection stays)

### PR DESCRIPTION
**Pull request by neikeq**
- TextEdit will now deselect if Ctrl+Left/Right is pressed.
- TextEdit and LineEdit no longer deselect text when Alt is pressed (except with Apple style keys).

Fixes #5375

### CODE REVIEW

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -2065,6 +2065,12 @@ void TextEdit::_input_event(const InputEvent& p_input_event) {
 
 					if (k.mod.shift)
 						_pre_shift_selection();
+#ifdef APPLE_STYLE_KEYS
+					else
```
Comment (akien-mga) [inline scene/gui/text_edit.cpp]: Isn't this `else` alone, or do I misunderstand the snippet?

Comment (vnen) [inline scene/gui/text_edit.cpp]: It seems so. Maybe the `#endif`should be before `deselect()`? It's also the case in the other `else` below.

Comment (neikeq) [inline scene/gui/text_edit.cpp]: Oops... yeah, `deselect()` was supposed to be outside that preprocessor block... What a miss!

Comment (neikeq) [inline scene/gui/text_edit.cpp]: Fixed!
