### PR TITLE
Fix `AnimationPlayer` crash when it's made the scene root

### LINKED ISSUE #91043: AnimationPlayer RootNode null crash
### Tested versions

-4.2.2.stable

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce GT 1030 (NVIDIA; 31.0.15.5161) - AMD Ryzen 3 1300X Quad-Core Processor (4 Threads)

### Issue description

If you add a property track or idk any track and change the root node of scene and click this thing 
image
godot will crash.
(sorry for bad english lol)

### Steps to reproduce

-Create a scene
-Add a node and a animationplayer
-Add a key to animationplayer that is on root node
-Change the root node and click that thing on the image in description

### Minimal reproduction project (MRP)

[project.zip](https://github.com/godotengine/godot/files/15073370/project.zip)

### PR DESCRIPTION
**Pull request by ArshPanesar**
When an AnimationPlayer node is made the root of a scene, the node links on the Animation Track can become broken and clicking on them will crash Godot 4.2.2-stable. The current master branch also breaks the node links when AnimationPlayer is made scene root, and can also crash the engine if another node was made the scene root prior to the AnimationPlayer (See Issue #91043)

This happens because when made root, the editor loses track of AnimationPlayer's `root_node`. By keeping a cached pointer to the `root_node`, the track links can remain functional.

Fixes Crash in 4.2.2-stable and Fixes Broken Node Links and Potential Crash in current master branch.

* *Bugsquad edit, fixes: #91043*

### CODE REVIEW

File: editor/plugins/animation_player_editor_plugin.h [hunk 1]
```diff
@@ -52,6 +52,7 @@ class AnimationPlayerEditor : public VBoxContainer {
 	AnimationPlayerEditorPlugin *plugin = nullptr;
 	AnimationMixer *original_node = nullptr; // For pinned mark in SceneTree.
 	AnimationPlayer *player = nullptr; // For AnimationPlayerEditor, could be dummy.
+	Node *cached_player_root_node = nullptr;
```
Comment (TokageItLab) [inline editor/plugins/animation_player_editor_plugin.h:55]: I think it is generally OK, but I don't understand why the pointer is cached.

Comment (ArshPanesar) [reply editor/plugins/animation_player_editor_plugin.h:55]: Sorry for the late reply! 

It is unsafe. My thought process was: Since a broken NodePath to the player root would be impossible to resolve, keeping a direct raw pointer to the current player's root can always work as long as its validity is checked before accessing it (2nd commit in this PR does this validity check). 

This pointer's lifetime should be the same as the current AnimationPlayer, so I declared it right below `AnimationPlayer *player = nullptr;`. 

Maybe hiding the raw pointer in a nested struct could alleviate its unsafety. Something like:

```
...
AnimationPlayer *player = nullptr; // For AnimationPlayerEditor, could be dummy.
struct PlayerCache {
private:
    Node* root_node = nullptr;
public:
    bool check_valid(AnimationPlayer* player) {
        NodePath cached_root_path = player->get_path_to(root_node);
        return root_node == player->get_node_or_null(cached_root_path);
    }

    Node* get_root_node(AnimationPlayer* player) {
        if (check_valid(player)) {
            return root_node;
        }
        return nullptr;
    }

    Node* set_root_node(Node* node) {
        root_node = node;
    }
} player_cache;
...
```

Comment (TokageItLab) [reply editor/plugins/animation_player_editor_plugin.h:55]: Can you make it to keep the InstanceID and be able to fetch node from it as needed as we do elsewhere? Like:

```cpp
ObjectID *cached_player_root_node;
```
```cpp
Node *AnimationPlayerEditor::get_root_node() {
    return Object::cast_to<Node>(ObjectDB::get_instance(cached_player_root_node));
}
```

Comment (ArshPanesar) [reply editor/plugins/animation_player_editor_plugin.h]: I changed the code to use the instance ID instead of a raw pointer. Everything still works as expected. Thanks for the advice! You can check if everything looks good in the new commit.

**Comment by TokageItLab** [comment]
As I wrote in https://github.com/godotengine/godot/issues/91043#issuecomment-2323043703, I can't actually reproduce the crash of issue #91043. Can you raise a video or something that reproduces the occurrence of the crash?

As the this PR change is understandable, so for approving, we need to actually see the crash reproduced and if this PR fix it.

**Review by TokageItLab — APPROVED** [review]

**Comment by akien-mga** [comment]
I updated the PR branch to squash the commits and tweaked the commit message a bit. Should be ready to merge once CI passes.

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.
