### PR TITLE
Fix: TabBar/TabContainer can't start with all tabs deselected

### LINKED ISSUE #108223: TabContainer selects first tab (0) when current_tab == -1 and does not persist value of -1
### Tested versions

- reproducible in 4.5-beta1

### System information

Win11, Godot 4.5 beta

### Issue description

A tab container configured to allow deselection of all tabs, and in conflict with the help text, starts with the first tab selected, rather than no tab selected, if current_tab is set to -1.

The in-editor representation works as expected once, but not across editor restarts.

I suspect this is a problem in serializing the value, reloading the editor will result in the value being set to 0 instead of -1.

Image

### Steps to reproduce

1. Open MRP.
2. observe: first tab is selected (should be not selected)
3. observe: current_tab is 0 (and shows "rever to default" arrow)
4. set current tab to -1
5. observe: all tabs deselected
6. run MRP.
7. observe: first tab is selected
8. repeat step 4
9. save and close scene or quit editor
10. reopen scene or project
11. observe 2 & 3 again

Expected output: (editor state analogous)
Image

Actual output:
Image

### Minimal reproduction project (MRP)

[MRP-tabcontainer.zip](https://github.com/user-attachments/files/21025847/MRP-tabcontainer.zip)

### PR DESCRIPTION
**Pull request by thygrrr**
`TabBars` and `TabContainers` were unable to start with no tabs selected, and couldn't properly retain their current tab value of "-1", also across editor restarts. 

### Fix for Issue:
https://github.com/godotengine/godot/issues/108223

### Cause
As the tabs were added to a TabBar (or children to a TabContainer) as the scene was set up, a bug in TabBar would always select tab index 0, even if deselection was enabled.

### Repro (also in linked issue):
image

### Before fix:
image

### Fixed via: 
A missing check for `deselect_enabled` was added in `TabBar.cpp` on the code path when a first tab is added to an empty bar. 

### After fix: 
image

### Tests:
- Modified 2 Test cases in [TabBar].
- Added 1 Test case in [TabBar].

Verified on Windows only via manual testing and  
`./bin/godot.windows.editor.x86_64.console.exe --test --test-case="*[TabBar]*"`

* *Bugsquad edit, fixes: https://github.com/godotengine/godot/issues/108223*

### CODE REVIEW

File: scene/gui/tab_bar.cpp [hunk 1]
```diff
@@ -1266,7 +1266,7 @@ void TabBar::add_tab(const String &p_str, const Ref<Texture2D> &p_icon) {
 	queue_redraw();
 	update_minimum_size();
 
-	if (tabs.size() == 1) {
+	if (tabs.size() == 1 && !deselect_enabled) {
```
Comment (KoBeWi) [inline scene/gui/tab_bar.cpp]:
```suggestion
	if (!deselect_enabled && tabs.size() == 1) {
```
Cheaper checks should be performed first.

File: tests/scene/test_tab_bar.h [hunk 2]
```diff
@@ -92,6 +93,48 @@ TEST_CASE("[SceneTree][TabBar] tab operations") {
...
+		CHECK(tab_bar->get_tab_tooltip(1) == "");
+		CHECK(tab_bar->get_tab_text_direction(1) == Control::TEXT_DIRECTION_INHERITED);
+		CHECK_FALSE(tab_bar->is_tab_disabled(1));
+		CHECK_FALSE(tab_bar->is_tab_hidden(1));
+
+		CHECK(tab_bar->get_tab_title(2) == "tab2");
+		CHECK(tab_bar->get_tab_tooltip(2) == "");
+		CHECK(tab_bar->get_tab_text_direction(2) == Control::TEXT_DIRECTION_INHERITED);
+		CHECK_FALSE(tab_bar->is_tab_disabled(2));
+		CHECK_FALSE(tab_bar->is_tab_hidden(2));
```
Comment (KoBeWi) [inline tests/scene/test_tab_bar.h]: These checks are redundant, already covered by previous subcase.

Comment (thygrrr) [reply tests/scene/test_tab_bar.h]: ~~Good point, though not all are.~~
~~The code path may be the same, but refactors could make the deselect_enable branch succeed where it shouldn't.~~

Edit: That's literally what you highlighted, my bad. :)

I will remove the ones that are covered. I find the original test case already tests too much, but I mirrored it for that reason that they share a code path.

File: scene/gui/tab_bar.cpp (hunk 1 above)
Comment (thygrrr) [reply scene/gui/tab_bar.cpp]: Right. Also fits the style of the source file better.

**Review by KoBeWi — APPROVED** [review]
Needs to be squashed into single commit.

**Comment by Repiteo** [comment]
Please rename the commit to not include references to issues; that'll cause GitHub to send tons of unwanted pings

I'd remove the followup comment as well, shortening the commit message in its entirety to: 
"TabBar current tab now stays -1 when adding first tab on deselect_enable"

**Comment by thygrrr** [comment]
> Please rename the commit to not include references to issues; that'll cause GitHub to send tons of unwanted pings

I thought that was *literally how it's done.* My bad. 😟


> I'd remove the followup comment as well, shortening the commit message in its entirety...

Done.

**Comment by Repiteo** [comment]
No worries! It's pretty counterintuitive, so that slips a bunch of people up (even some of our long-time members!)

Thanks!
