### PR TITLE
Fix `set_item_submenu` infinite recursion crash

### LINKED ISSUE #84692: Executing `PopupMenu.activate_item_by_event` function crashes Godot
### Godot version

4.2.beta.custom_build. 9df649185

### System information

Ubuntu 22.04 CI

### Issue description

When executing (this code was automatically minimized, so it is possible, that an even more "minimal" project can be created)
```
extends Node
func _process(delta):
	for i in get_children():
		i.queue_free()
	var temp_variable29522 = CodeHighlighter.new()
	temp_variable29522.clear_member_keyword_colors()
	var temp_variable29574 = GLTFBufferView.new()
	var temp_variable29766 = PopupMenu.new()
	add_child(temp_variable29766)
	temp_variable29766.get_item_icon_max_width(-63)
	temp_variable29766.get_item_shortcut(11)
	temp_variable29766.set_item_count(49)
	temp_variable29766.set_item_submenu(11, ".")
	temp_variable29766.activate_item_by_event(InputEventAction.new(), false)
```
Godot crashes:
```
Godot Engine v4.2.beta.custom_build.9df649185 - https://godotengine.org
Vulkan API 1.2.0 - Forward+ - Using Vulkan Device #0: Unknown - SwiftShader Device (LLVM 10.0.0)
ERROR: Index p_idx = -63 is out of bounds (items.size() = 0).
   at: get_item_icon_max_width (scene/gui/popup_menu.cpp:1813)
ERROR: Index p_idx = 11 is out of bounds (items.size() = 0).
   at: get_item_shortcut (scene/gui/popup_menu.cpp:1868)
Segmentation fault (core dumped)
```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

Memory leaks or asan backtraces are visible when using Godot build with sanitizers support - https://github.com/qarmin/GodotBuilds/actions (linux -> linux-editor-sanitizers)

   

### Steps to reproduce

Above

### Minimal reproduction project

Above

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes https://github.com/godotengine/godot/issues/84692
Same as https://github.com/godotengine/godot/pull/84183

### CODE REVIEW

File: scene/gui/popup_menu.cpp [hunk 1]
```diff
@@ -1800,7 +1805,7 @@ void PopupMenu::set_item_submenu(int p_idx, const String &p_submenu) {
 		}
 	}
 
-	items.write[p_idx].submenu = p_submenu;
+	items.write[p_idx].submenu = submenu_name_safe;
```
Comment (KoBeWi) [inline scene/gui/popup_menu.cpp:1808]: Why are you assigning changed name if it's layer used for `get_node()`?

Comment (jsjtxietian) [reply scene/gui/popup_menu.cpp:1808]: Sorry, it was a mistake.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
