### PR TITLE
Tree: Fix offset relationship lines with Hide Folding

### LINKED ISSUE #104329: Tree's Relationship Guides do not render properly if Hide Folding is enabled.
### Tested versions

- Reproducible in: 4.4-stable

### System information

Godot v4.4.stable - Windows 11 (build 26100) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 32.0.15.7270) - AMD Ryzen 7 3700X 8-Core Processor (16 threads)

### Issue description

Image

Image

As you can see, the lines for branch nodes go slightly to the left when there is no collapse icon. 

### Steps to reproduce

Create a tree, hide folding, override relationship lines to a positive value in the theme.

### Minimal reproduction project (MRP)

[tree.zip](https://github.com/user-attachments/files/19326806/tree.zip)

### PR DESCRIPTION
**Pull request by BrotherShort**
Fix #104329

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -2641,7 +2641,7 @@ int Tree::draw_item(const Point2i &p_pos, const Point2 &p_draw_ofs, const Size2
 				int parent_ofs = p_pos.x + theme_cache.item_margin;
 				Point2i root_pos = Point2i(root_ofs, children_pos.y + child_self_height / 2) - theme_cache.offset + p_draw_ofs;
 
-				if (c->get_visible_child_count() > 0) {
+				if (c->get_visible_child_count() > 0 && !(p_item->disable_folding || hide_folding)) {
```
Comment (KoBeWi) [inline scene/gui/tree.cpp:2644]:
```suggestion
				if (!hide_folding && !p_item->disable_folding && c->get_visible_child_count() > 0) {
```

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
