### PR TITLE
Ensure `r_aabb` is always used when creating surfaces through the RenderingServer

### LINKED ISSUE #82890: Imported models are flat.
### Godot version

v4.2.dev.custom_build [f71259be3]

### System information

Windows 10

### **IT'S FLATT!?!?**
flatt

My custom changes shouldn't affect this but can someone confirm that this happens in the raw build?

### Steps to reproduce

1) Import a blender file containing a model into your project.
2) Open it.
3) Observe Flatness.

### Minimal reproduction project
[flatt test.zip](https://github.com/godotengine/godot/files/12827277/flatt.test.zip)

### PR DESCRIPTION
**Pull request by clayjohn**
Tentative fix for https://github.com/godotengine/godot/issues/82890

@kevinkuo52 Is still investigating and may find a better fix. But this change is needed in either case as it is possible for compressed meshes to be created without an AABB and that is a potential big issue. 

[Link to download Windows Editory Binary for testing](https://github.com/godotengine/godot/suites/17531258105/artifacts/1001583060) (taken from Github Actions)

*Bugsquad edit:*
- Fixes #82890

### CODE REVIEW

**Comment by RandomShaper** [comment]
Would it make sense to do `r_aabb = AABB()` to have some default for cases that don't end up writing to it?

**Comment by kevinkuo52** [comment]
> Would it make sense to do `r_aabb = AABB()` to have some default for cases that don't end up writing to it?

just heads up, aabb could be type Rect2(src[i], SMALL_VEC2); here
https://github.com/godotengine/godot/blob/e39f73b2a70412a90ba40bfd6d45394d80dc9d0a/servers/rendering_server.cpp#L429C13-L429C13

File: servers/rendering_server.cpp [hunk 1]
```diff
@@ -441,16 +441,13 @@ Error RenderingServer::_surface_set_data(Array p_arrays, uint64_t p_format, uint
 
 					const Vector3 *src = array.ptr();
 
-					// Setting vertices means regenerating the AABB.
```
Comment (kevinkuo52) [inline servers/rendering_server.cpp:444]: minor: maybe leave in this comment?

**Review by kevinkuo52 — APPROVED** [review]

**Comment by clayjohn** [comment]
> Would it make sense to do `r_aabb = AABB()` to have some default for cases that don't end up writing to it?

I added one. In theory, there should be no case where r_aabb isn't written to.

**Comment by kevinkuo52** [comment]
> @kevinkuo52 It would be interesting to see if just initializing r_aabb to AABB() is enough to fix the bug on your system. If so, then my theory is probably correct and this PR will properly fix the bug.

just initializing r_aabb to AABB() didnt fix the issue (also tried setting AABB aabb = AABB()).

huh this is interesting thought ur theory of "r_aabb is only guaranteed to be written out in the 2D " made a lot of sense.

but just setting r_aabb to AABB() didnt fix it, also try to set it in different places to make sure it is always initialized (like before towards begining of this function, were AABB aabb is currently initizliezed, in the block of using_normals_tangents  before the continue) but still didnt fix it.

it was only fixed when i made this change of operating directly on r_aabb

**Review by akien-mga — APPROVED** [review]
Confirmed working, so let's go.

If any MSVC compiler engineer wants to debug this further, let us know :)

**Comment by akien-mga** [comment]
Thanks!
