### PR TITLE
Check if parent is null before updating transform

### LINKED ISSUE #29263: Crash when adding shape to CollisionShape
**Godot version:**

3.2dev build

**OS/device including version:**

PopOS!, Intel HD 4000

**Issue description:**

Crash when adding shape to CollisionShape

**Steps to reproduce:**
Create new 3d scene with Node root, add CollisionShape, try to choose one of the shapes

**Stacktrace**
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x41100) [0x7f88ba561100] (??:0)
[2] Map<unsigned int, CollisionObject::ShapeData, Comparator<unsigned int>, DefaultAllocator>::find(unsigned int const&) const (/home/nikita_bliznyuk/Programs/Godot/./core/map.h:524)
[3] Map<unsigned int, CollisionObject::ShapeData, Comparator<unsigned int>, DefaultAllocator>::has(unsigned int const&) const (/home/nikita_bliznyuk/Programs/Godot/./core/map.h:560)
[4] CollisionObject::shape_owner_set_transform(unsigned int, Transform const&) (/home/nikita_bliznyuk/Programs/Godot/scene/3d/collision_object.cpp:226)
[5] CollisionShape::_update_in_shape_owner(bool) (/home/nikita_bliznyuk/Programs/Godot/scene/3d/collision_shape.cpp:69)
[6] CollisionShape::_shape_changed() (/home/nikita_bliznyuk/Programs/Godot/scene/3d/collision_shape.cpp:233)
[7] CollisionShape::set_shape(Ref<Shape> const&) (/home/nikita_bliznyuk/Programs/Godot/scene/3d/collision_shape.cpp:172)
[8] MethodBind1<Ref<Shape> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/nikita_bliznyuk/Programs/Godot/./core/method_bind.gen.inc:775 (discriminator 12))
[9] ClassDB::set_property(Object*, StringName const&, Variant const&, bool*) (/home/nikita_bliznyuk/Programs/Godot/core/class_db.cpp:1038)
[10] Object::set(StringName const&, Variant const&, bool*) (/home/nikita_bliznyuk/Programs/Godot/core/object.cpp:422)
[11] UndoRedo::_process_operation_list(List<UndoRedo::Operation, DefaultAllocator>::Element*) (/home/nikita_bliznyuk/Programs/Godot/core/undo_redo.cpp:311 (discriminator 2))
[12] UndoRedo::redo() (/home/nikita_bliznyuk/Programs/Godot/core/undo_redo.cpp:338)
[13] UndoRedo::commit_action() (/home/nikita_bliznyuk/Programs/Godot/core/undo_redo.cpp:260)
[14] EditorInspector::_edit_set(String const&, Variant const&, bool, String const&) (/home/nikita_bliznyuk/Programs/Godot/editor/editor_inspector.cpp:2029)
[15] EditorInspector::_property_changed(String const&, Variant const&, String const&, bool) (/home/nikita_bliznyuk/Programs/Godot/editor/editor_inspector.cpp:2045)
[16] MethodBind4<String const&, Variant const&, String const&, bool>::call(Object*, Variant const**, int, Variant::CallError&) (/home/nikita_bliznyuk/Programs/Godot/./core/method_bind.gen.inc:3115 (discriminator 33))
[17] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/nikita_bliznyuk/Programs/Godot/core/object.cpp:940 (discriminator 1))
[18] Object::emit_signal(StringName const&, Variant const**, int) (/home/nikita_bliznyuk/Programs/Godot/core/object.cpp:1240 (discriminator 1))
[19] EditorProperty::emit_changed(StringName const&, Variant const&, StringName const&, bool) (/home/nikita_bliznyuk/Programs/Godot/editor/editor_inspector.cpp:88 (discriminator 3))
[20] EditorPropertyResource::_menu_option(int) (/home/nikita_bliznyuk/Programs/Godot/editor/editor_properties.cpp:2221 (discriminator 7))
[21] MethodBind1<int>::call(Object*, Variant const**, int, Variant::CallError&) (/home/nikita_bliznyuk/Programs/Godot/./core/method_bind.gen.inc:775 (discriminator 12))
[22] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/nikita_bliznyuk/Programs/Godot/core/object.cpp:940 (discriminator 1))
[23] Object::emit_signal(StringName const&, Variant const**, int) (/home/nikita_bliznyuk/Programs/Godot/core/object.cpp:1240 (discriminator 1))
[24] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/nikita_bliznyuk/Programs/Godot/core/object.cpp:1296)
[25] PopupMenu::activate_item(int) (/home/nikita_bliznyuk/Programs/Godot/scene/gui/popup_menu.cpp:1117 (discriminator 4))
[26] PopupMenu::_gui_input(Ref<InputEvent> const&) (/home/nikita_bliznyuk/Programs/Godot/scene/gui/popup_menu.cpp:331)
[27] MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/nikita_bliznyuk/Programs/Godot/./core/method_bind.gen.inc:775 (discriminator 12))
[28] Object::call_multilevel(StringName const&, Variant const**, int) (/home/nikita_bliznyuk/Programs/Godot/core/object.cpp:775 (discriminator 1))
[29] Object::call_multilevel(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/nikita_bliznyuk/Programs/Godot/core/object.cpp:881)
[30] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (/home/nikita_bliznyuk/Programs/Godot/scene/main/viewport.cpp:1539 (discriminator 2))
[31] Viewport::_gui_input_event(Ref<InputEvent>) (/home/nikita_bliznyuk/Programs/Godot/scene/main/viewport.cpp:1911 (discriminator 3))
[32] Viewport::input(Ref<InputEvent> const&) (/home/nikita_bliznyuk/Programs/Godot/scene/main/viewport.cpp:2686 (discriminator 2))
[33] Viewport::_vp_input(Ref<InputEvent> const&) (/home/nikita_bliznyuk/Programs/Godot/scene/main/viewport.cpp:1315)
[34] MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/nikita_bliznyuk/Programs/Godot/./core/method_bind.gen.inc:775 (discriminator 12))
[35] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/nikita_bliznyuk/Programs/Godot/core/object.cpp:940 (discriminator 1))
[36] Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/nikita_bliznyuk/Programs/Godot/core/object.cpp:865)
[37] SceneTree::call_group_flags(unsigned int, StringName const&, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/nikita_bliznyuk/Programs/Godot/scene/main/scene_tree.cpp:267)
[38] SceneTree::input_event(Ref<InputEvent> const&) (/home/nikita_bliznyuk/Programs/Godot/scene/main/scene_tree.cpp:422 (discriminator 6))
[39] InputDefault::_parse_input_event_impl(Ref<InputEvent> const&, bool) (/home/nikita_bliznyuk/Programs/Godot/main/input_default.cpp:416)
[40] InputDefault::parse_input_event(Ref<InputEvent> const&) (/home/nikita_bliznyuk/Programs/Godot/main/input_default.cpp:260)
[41] InputDefault::flush_accumulated_events() (/home/nikita_bliznyuk/Programs/Godot/main/input_default.cpp:671)
[42] OS_X11::process_xevents() (/home/nikita_bliznyuk/Programs/Godot/platform/x11/os_x11.cpp:2485)
[43] OS_X11::run() (/home/nikita_bliznyuk/Programs/Godot/platform/x11/os_x11.cpp:3032)
[44] /home/nikita_bliznyuk/Programs/Godot/bin/godot.x11.tools.64(main+0xdc) [0x138199e] (/home/nikita_bliznyuk/Programs/Godot/platform/x11/godot_x11.cpp:56)
[45] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f88ba54409b] (??:0)
[46] /home/nikita_bliznyuk/Programs/Godot/bin/godot.x11.tools.64(_start+0x2a) [0x138180a] (??:?)
-- END OF BACKTRACE --

### PR DESCRIPTION
**Pull request by creikey**
Check if parent is null before updating transform
 - parent being null means it's not a CollisionObject

Fixes #29263.

### CODE REVIEW

File: scene/3d/collision_shape.cpp [hunk 1]
```diff
@@ -228,7 +228,9 @@ void CollisionShape::_update_debug_shape() {
 
 void CollisionShape::_shape_changed() {
 	// If this is a heightfield shape our center may have changed
-	_update_in_shape_owner(true);
+	if (parent) {
```
Comment (akien-mga) [inline scene/3d/collision_shape.cpp]: That test should be done in `_update_in_shape_owner(true)` itself, with
```
if (!parent)
	return;
```

Comment (BastiaanOlij) [reply scene/3d/collision_shape.cpp]: I second that :)

Comment (creikey) [reply scene/3d/collision_shape.cpp]: I was going to do this, but I felt as if it was unnecessary to check every time as most of the calling code already checks. Maybe a comment to specify that it is necessary?

Comment (akien-mga) [reply scene/3d/collision_shape.cpp]: That's a good point, all other calls to this method ensure `if (parent)` before calling it.
IMO they could all be simplified by putting the call in that method and removing the `if (parent)` on calling sites, but that could be done in another PR, this one is consistent with the current codebase.

**Comment by akien-mga** [comment]
Thanks!
