### PR TITLE
Properly pass SCREEN_PIXEL_SIZE to canvas light shader

### LINKED ISSUE #30903: Usage of SCREEN_UV appears to break lighting (with Light2D)
**Godot version:** 3.1.1.stable.official

**OS/device including version:**  Ubuntu 16.04.6 LTS

**Issue description:**

It appears that usage of `SCREEN_UV` inside a `canvas_item` shader changes how those sprites are rendered in a way that breaks lighting (for my purposes).

I'm not precisely sure how to describe the behavior, but here's my use case:

I'm putting together a 2D platformer using the tilemap system. However, in order to add detail to the tilemaps, I've decided to use a masking system, where a mask for the tilemap is first rendered onto a Viewport, and then the tile shader reads from that mask to see whether to discard the fragment.

However, it appears that Light2Ds will still illuminate the discarded fragments, and I haven't found a way to stop that from happening.

Here's an image demonstrating the behavior:
godot_light_behavior

Upon further investigation, I was able to create a situation where a shader that reads from `SCREEN_UV` has a similar problem, while a shader that reads from `UV` does not. I have attached a demo project. In this demo, strangely enough, reading from `SCREEN_UV` completely disables lighting, which is seemingly not related to the behavior in my real project.

I believe this is, incidentally, related to an issue I opened before, so I might have a bit more understanding of why it is happening. I believe that screen-reading shaders are likely rendered differently from non-screen-reading shaders, and this is for some justifiable reasons, from my understanding.

However, it is important to note that just because a shader reads from `SCREEN_UV` does not mean it is a screen-reading shader. The example project I have attached should exemplify this.

So my suggestion is that reading from `SCREEN_UV` should not impact how a shader is rendered.

Of course, for my real use case, there may be additional factors causing the problem. But I think the demo project indicates that the `SCREEN_UV` issue does exist independently in any case.

**Steps to reproduce:**
Create a shader that does something. Change it to use `SCREEN_UV` somewhere. Observe if this changes how it interacts with lights.

**Minimal reproduction project:**

[screen-uv-example.zip](https://github.com/godotengine/godot/files/3439761/screen-uv-example.zip)

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: #30903

### CODE REVIEW

**Comment by akien-mga** [comment]
Piexels, yummy :cake:

File: drivers/gles3/rasterizer_canvas_gles3.cpp [hunk 1]
```diff
@@ -1585,6 +1585,11 @@ void RasterizerCanvasGLES3::canvas_render_items(Item *p_item_list, int p_z, cons
 						state.canvas_shader.set_uniform(CanvasShaderGLES3::FINAL_MODULATE, state.canvas_item_modulate);
 						state.canvas_shader.set_uniform(CanvasShaderGLES3::MODELVIEW_MATRIX, state.final_transform);
 						state.canvas_shader.set_uniform(CanvasShaderGLES3::EXTRA_MATRIX, Transform2D());
+						if (storage->frame.current_rt) {
+							state.canvas_shader.set_uniform(CanvasShaderGLES3::SCREEN_PIXEL_SIZE, Vector2(1.0 / storage->frame.current_rt->width, 1.0 / storage->frame.current_rt->height));
+						}	else {
```
Comment (akien-mga) [inline drivers/gles3/rasterizer_canvas_gles3.cpp]: Style issue here, shouldn't be a tab before `else`.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.
