### PR TITLE
GUI: Fix `Tree` performance regression by using cache

### LINKED ISSUE #79292: Inspector causes huge lags in large scenes after 4.1.stable
### Godot version

v4.1.stable.mono.official [970459615]

### System information

Godot v4.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (NVIDIA; 31.0.15.3179) - AMD Ryzen 3 3200G with Radeon Vega Graphics (4 Threads)

### Issue description

I have a scene with a large amount of InstanceMesh3D, StaticBody3D which are in a Map node. This scene does not cause any lags for me, but as soon as I expand the Map node, my scene starts to lag and it is impossible to work with the project at all. Before that I moved my project from 4.0.2.stable to 4.1.stable. The previous version did not cause such problems.

### Steps to reproduce

Create a scene of over +500 MeshInstance3D with any shape that is in a Node3D node. Try to open and close Node3D and you will see the performance drop.

### Minimal reproduction project

N/A

### LINKED ISSUE #79927: Too many warnings in the debugger causing editor lag especially in Chinese language and GLES3 (Compatibility) .
### Godot version

v4.2.dev1.official [0c2144da9]

### System information

Godot v4.2.dev1 - Windows 10.0.19044 - GLES3 (Compatibility) - AMD Radeon(TM) Vega 8 Graphics (Advanced Micro Devices, Inc.; 31.0.14051.5006) - AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx (8 Threads)

### Issue description
**Edit: Bug introduced between 4.1.dev2 and 4.1.dev3. In dev2, the scrollbars can be dragged very smoothly, and even if the scrollbars are at the bottom, there is no performance loss.**

When there are too many warnings in the debugger and render mode is GLES3 (Compatibility).
The lag situation of the editor is positively correlated with the position of the scroll bar. The closer the scroll bar is to the bottom, the more lagging the editor becomes.
Although the English version may be a bit lag, the situation is much better, but the Chinese version will be very poor.
In forward+ mode, both Chinese and English perform similarly, with slight performance impact.

Chinese:

https://github.com/godotengine/godot/assets/45038185/2449fedb-113e-45b6-ba6a-0fbd3652175d

English:

https://github.com/godotengine/godot/assets/45038185/ff3448e5-d08e-4077-93ac-32e180a8cf3b

### Steps to reproduce

1. Run Project.
2. Waiting for warnings of around 1000.
3. When the scroll bar in the error panel of the debugger is at the top, test the editor.
4. Test the editor when the scroll bar is at the bottom.
5. Try Chinese language mode.
6. Try foward+ and GLES3 (Compatibility).

When switching languages, you may need to use arrow keys because of other bugs.

### Minimal reproduction project

[WarningLag.zip](https://github.com/godotengine/godot/files/12174463/WarningLag.zip)

### PR DESCRIPTION
**Pull request by dalexeev**
* Closes #79292.
* Closes #79927.

On @YuriSizov's advice, I used cache to optimize the bottleneck. This made `Tree` responsive again for 10,000 rows, but `Tree` is still slower than in 4.0.3. My guess is that further optimizations (and possible refactoring) of `draw_item()` are desirable.

**Please test this PR carefully to make sure the cache is invalidated when needed!**

Test project: [GUITree.zip](https://github.com/godotengine/godot/files/12012885/GUITree.zip)

**Before**

**After**

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -4927,6 +4941,7 @@ void Tree::set_column_title_language(int p_column, const String &p_language) {
 	ERR_FAIL_INDEX(p_column, columns.size());
 	if (columns[p_column].language != p_language) {
 		columns.write[p_column].language = p_language;
+		//columns.write[p_column].cached_minimum_width_dirty = true;
```
Comment (bruvzg) [inline scene/gui/tree.cpp:4944]: `title` and `language` (in some conditions, usually it's not) can change min. width, `text_direction` and `alignment` should not.

Comment (dalexeev) [reply scene/gui/tree.cpp:4944]: `update_column()` invalidates the cache.

**Comment by dalexeev** [comment]
> But the scene tree starts to lag like hell the more down you scroll (and gets back to snappy once you scroll back to top).

Note that this behavior is still present, albeit to a lesser extent. Some changes are needed in the algorithm for skipping previous rows, but their height must still be taken into account. Perhaps the problem is that the previous rows are being drawn, although they are invisible. See `draw_item()`.

**Comment by YuriSizov** [comment]
> Perhaps the problem is that the previous rows are being drawn, although they are invisible. See `draw_item()`.

I haven't checked the code, but indeed, we don't need to draw them and I think previously we didn't do that. Can you make the necessary changes so that the previous rows are only used to compute the offset?

File: scene/gui/tree.cpp (hunk 1 above)
Comment (YuriSizov) [reply scene/gui/tree.cpp:4958]: I thought the point of adding these commented out lines here was to indicate that we might want to uncomment them in the future. But since `update_column` does indeed invalidate the cache already, I think they should be removed.

File: scene/gui/tree.cpp [hunk 2]
```diff
@@ -2449,7 +2452,7 @@ int Tree::draw_item(const Point2i &p_pos, const Point2 &p_draw_ofs, const Size2
 			int child_h = -1;
 			int child_self_height = 0;
 			if (htotal >= 0) {
-				child_h = draw_item(children_pos, p_draw_ofs, p_draw_size, c, &child_self_height);
+				child_h = draw_item(children_pos, p_draw_ofs, p_draw_size, c, child_self_height);
 				child_self_height += theme_cache.v_separation;
```
Comment (YuriSizov) [inline scene/gui/tree.cpp:2456]: This seems to be the only place where we care for the returned self height value. So I think this line adding vertical separation can be removed and instead we can assign `r_self_height` after we add this value to `label_h`.

File: scene/gui/tree.cpp [hunk 3]
```diff
@@ -4231,7 +4234,8 @@ void Tree::_notification(int p_what) {
 			cache.rtl = is_layout_rtl();
 
 			if (root && get_size().x > 0 && get_size().y > 0) {
-				draw_item(Point2(), draw_ofs, draw_size, root);
+				int self_height;
```
Comment (YuriSizov) [inline scene/gui/tree.cpp:4237]: Should we initialize this value? I understand it's discarded anyway, which is kind of meh as well, just not sure if not having it correctly initialize can lead to problems. Also, a comment would be handy that we have no use for it.

**Review by YuriSizov — APPROVED** [review]
I've tested it, and I can confirm that it doesn't fully solve the slowdown when you scroll all the way down on larger trees, but it does significantly improve the experience. So I think we should go with this, at least for now.

One curiosity that I noticed was that I could clearly experience a slowdown in the editor, but not in a test scene. The scene is just a tree and I fill it up as follows:

```gdscript

extends Tree

const ICON = preload("res://icon.svg")

func _init():
	var root := create_item()
	
	for i in range(0, 10000):
		var item := create_item(root)
		item.set_text(0, str(i))
		item.set_icon_max_width(0, 16)
		item.set_icon(0, ICON)
```

This works much smoother than the scene tree in the editor with 5.8k items in it (which I think I took from the linked issue). I suspect it may be something to do with buttons. I think if I add buttons to each row with `item.add_button(0, ICON, -1, false, "Hello")`, it does get slightly slower at the bottom.

That's the only difference that I can think of between my test scene and the scene tree view in the editor, as in the editor every node has a visibility toggle in my case.

There are several things to improve about buttons in trees, however, as I outlined in https://github.com/godotengine/godot/pull/79792#issuecomment-1664105612. So this is something that can be done in a separate PR (I can take a look but I'm giving a chance to the author of the linked PR to work a bit more on their contribution, if they want to).

File: scene/gui/tree.cpp (hunk 2 above)
Comment (dalexeev) [reply scene/gui/tree.cpp:2456]: I'm not sure about whether to include the separator's height in the item's `self_height`. But I replaced the code with the following:

```c++
r_self_height = compute_item_height(p_item);
label_h = r_self_height + theme_cache.v_separation;
```

**Comment by dalexeev** [comment]
After rebasing, I noticed crashes. They look unrelated to this PR, but they didn't exist before.

```
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.2.dev.custom_build (4bc871ae0f30f435655df4b5e2c214607a2e7e45)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3c4b0) [0x7f44ee43c4b0] (??:0)
[2] Window::_event_callback(DisplayServer::WindowEvent) (/home/danil/godot-src/scene/main/window.cpp:684 (discriminator 1))
[3] void call_with_variant_args_helper<Window, DisplayServer::WindowEvent, 0ul>(Window*, void (Window::*)(DisplayServer::WindowEvent), Variant const**, Callable::CallError&, IndexSequence<0ul>) (/home/danil/godot-src/./core/variant/binder_common.h:308 (discriminator 4))
[4] void call_with_variant_args<Window, DisplayServer::WindowEvent>(Window*, void (Window::*)(DisplayServer::WindowEvent), Variant const**, int, Callable::CallError&) (/home/danil/godot-src/./core/variant/binder_common.h:418)
[5] CallableCustomMethodPointer<Window, DisplayServer::WindowEvent>::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/danil/godot-src/./core/object/callable_method_pointer.h:105)
[6] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (/home/danil/godot-src/core/variant/callable.cpp:64)
[7] DisplayServerX11::_send_window_event(DisplayServerX11::WindowData const&, DisplayServer::WindowEvent) (/home/danil/godot-src/platform/linuxbsd/x11/display_server_x11.cpp:3772)
[8] DisplayServerX11::process_events() (/home/danil/godot-src/platform/linuxbsd/x11/display_server_x11.cpp:4298)
[9] OS_LinuxBSD::run() (/home/danil/godot-src/platform/linuxbsd/os_linuxbsd.cpp:910)
[10] /home/danil/godot-src/bin/godot.linuxbsd.editor.dev.x86_64(main+0x19f) [0x56467c099b48] (/home/danil/godot-src/platform/linuxbsd/godot_linuxbsd.cpp:76)
[11] /lib/x86_64-linux-gnu/libc.so.6(+0x23a90) [0x7f44ee423a90] (??:0)
[12] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x89) [0x7f44ee423b49] (??:0)
[13] /home/danil/godot-src/bin/godot.linuxbsd.editor.dev.x86_64(_start+0x25) [0x56467c0998e5] (??:?)
-- END OF BACKTRACE --
```

**Comment by akien-mga** [comment]
Might be related to #80187? CC @Sauermann

**Comment by Sauermann** [comment]
Yes, that crash gets fixed by #80187. I was previously unable to cause this crash on X11, so I will take a look at the Test Project to see, where in the X11-platform-code this problem appears.

File: scene/gui/tree.cpp (hunk 2 above)
Comment (YuriSizov) [reply scene/gui/tree.cpp:2456]: It just seems redundant to add it in two places if these are the only two places that use this value. The name may be not the best, so I understand your hesitation. But I'd say this is pretty minor as far as semantics go.

Comment (YuriSizov) [reply scene/gui/tree.cpp:2456]: That said, I'm not insisting. We can merge it as is.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.
