### PR TITLE
Fix Inspector revert and animation keying button sizing

### LINKED ISSUE #102629: Animation: To insert key, you must click precisely on the key icon rectangle near Inspector property
### Tested versions

- Reproducible in: v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Ubuntu 22.04.5 LTS 22.04 - X11 - GLES3 (Compatibility) - NVIDIA GeForce GTX 860M (nvidia; 535.183.01) - Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 Threads)

### Issue description

I noticed that clicking on the key icon near an Inspector property didn't consistently insert a new key (whether for new track or existing track).

Trying to reproduce, I found out that you had to click precisely on the bounding box of the key icon. Clicking on the surrounding part of the square button containing the key icon will not work.

Demonstration video:

https://github.com/user-attachments/assets/2461f98a-c11e-4bb7-90a5-b6c34dad5bc3

### Steps to reproduce

1. Create an animation player
2. Select some node (make sure Animation panel is still open - easiest is to work on the AnimationPlayer node directly)
3. Choose a property in the inspector and click on the key icon next to it
4. Try both clicking inside and outside the bounding box of the key icon inside the square button

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Giganzo**
Fixes: https://github.com/godotengine/godot/issues/102629

This PR also replaces: https://github.com/godotengine/godot/pull/94742

Button are now bigger, full height, and they have a hover background to make it more obvious where to click.

[Screencast_20250209_031302.webm](https://github.com/user-attachments/assets/101624d0-c795-4592-b57d-024e85d2b689)

Also fixes an issue with hover state being wrong.
If you moved mouse quickly over a button they would stay in the hover state.

I didn't change the styling of checkable. As I don't know how or where this is displayed. Let me know if this should be applied to that one too.

### CODE REVIEW

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -547,6 +588,13 @@ void EditorProperty::_notification(int p_what) {
 				get_parent()->disconnect(SceneStringName(theme_changed), callable_mp(this, &EditorProperty::_update_property_bg));
 			}
 		} break;
+		case NOTIFICATION_MOUSE_EXIT: {
+			keying_hover = false;
+			revert_hover = false;
+			check_hover = false;
+			delete_hover = false;
+			queue_redraw();
```
Comment (KoBeWi) [inline editor/editor_inspector.cpp:596]: You should only redraw if any hover was `true`.

Comment (Giganzo) [reply editor/editor_inspector.cpp]: Changes made

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
