### PR TITLE
Fix TabContainer not respecting `tabbar_background`'s margins

### LINKED ISSUE #106421: TabContainer does not respect `tabbar_background`'s margins
### Tested versions

- Reproducible in 4.4

### System information

Godot v4.5.dev (ced7e2c03) - macOS Sonoma (14.5.0) - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M1 Pro (Apple7) - Apple M1 Pro (10 threads)

### Issue description

Currently, the `TabContainer` class has a theme stylebox called `tabbar_background`. With most other UI elements, the rendered element is resized to respect the stylebox's set margins, however this theme item does not respect that / have that behavior.

Margins not being respected

Expectation: There is 20px of empty space (just showing the stylebox) on the left, right, top, and bottom of the TabBar.

This is a mockup:
Image

### Steps to reproduce

- Create a TabContainer
- Give the TabContainer a theme
- In that theme, override `tabbar_background` and add a stylebox
- Change the margins of stylebox to be any number
- Note how the TabContainer is unaffected.

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/user-attachments/files/20217569/MRP.zip)

### PR DESCRIPTION
**Pull request by lodetrick**
Fixes #106421 (more details there)

Currently, TabContainers do not respect the margins of the `tabbar_background` stylebox, ignoring them completely. This PR makes the container respect the margins. This enables users to create custom vertical and horizontal margins for the TabBar internally within the TabContainer.

### CODE REVIEW

File: scene/gui/tab_container.cpp [hunk 1]
```diff
@@ -32,10 +32,20 @@
 
 #include "scene/theme/theme_db.h"
 
+Rect2 TabContainer::_get_tab_rect() const {
+	Rect2 rect = Rect2();
```
Comment (KoBeWi) [inline scene/gui/tab_container.cpp:36]:
```suggestion
	Rect2 rect;
```
Not needed.

**Comment by KoBeWi** [comment]
This makes dock position popup appear the wrong way:
image
vs
image

**Comment by lodetrick** [comment]
It should be fixed; I also checked rtl mode and it worked same as 4.1.

**Comment by KoBeWi** [comment]
The margin is not reversed for RTL:

https://github.com/user-attachments/assets/8fb1aedb-6824-4ef9-b4fc-1e734de79f6b

**Comment by lodetrick** [comment]
Thanks for the feedback, but I'm having trouble reproducing this. Does this have to do with the custom menu icon that you have? I tried the default menu icon and it wasn't an issue that I could see.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
