### PR TITLE
Update rendering driver name on fallbacks. Fix rendering driver/method in the editor system info.

### LINKED ISSUE #96380: Copy System Info shows incorrect rendering method when overriden on command line
### Tested versions

- Reproducible on v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.19045 - GLES3 (Compatibility) - dedicated Intel(R) UHD Graphics 620 (Intel Corporation; 31.0.101.2128) - Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 Threads)

### Issue description

When opening a project in the editor with the rendering driver and/or rendering method specified in the command line, 

### Steps to reproduce

- Run:  
```
Godot_v4.3-stable_win64_console.exe --rendering-driver d3d12 --path D:/empty --editor
```
- Select "Copy System Info" from menu
- Paste the value somewhere and check that it contains "GLES3 (Compatibility)"

### Minimal reproduction project (MRP)

[empty.zip](https://github.com/user-attachments/files/16824466/empty.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
- Fixes wrong names used in `Help` → `Copy System Info` (was using project settings, instead of real current driver/method).
- Add missing Direct3D 12 to the list.
- Set saved driver name if it was changed by fallback

Might fix some issues with shaders when D3D12 ↔ Vulkan fallback is used, since saved name is used to set defines: https://github.com/godotengine/godot/blob/3b3d6226c5cd3f9897160815990e2e234f165605/servers/rendering/renderer_rd/shader_rd.cpp#L202

Fixes #96380

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -5026,10 +5026,13 @@ String EditorNode::_get_system_info() const {
 		rendering_method = "Mobile";
 	} else if (rendering_method == "gl_compatibility") {
 		rendering_method = "Compatibility";
-		driver_name = GLOBAL_GET("rendering/gl_compatibility/driver");
 	}
 	if (driver_name == "vulkan") {
 		driver_name = "Vulkan";
+	} else if (driver_name == "d3d12") {
+		driver_name = "Direct3D 12";
+	} else if (driver_name == "opengl3_angle") {
```
Comment (akien-mga) [inline editor/editor_node.cpp:5034]: If we're making a special case for `opengl3_angle`, we might as well do one for `opengl3_es` too.

**Review by akien-mga — APPROVED** [review]

File: editor/editor_node.cpp (hunk 1 above)
Comment (bruvzg) [reply editor/editor_node.cpp:5034]: I guess it this case, we should change `opengl3` to return `OpenGL 3` instead of `GLES3`.

Comment (bruvzg) [reply editor/editor_node.cpp:5065]: Updated to return `OpenGL 3` or `OpenGL ES 3` based on actually used backend.

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
This breaks compiling with MSVC, it seems to introduce bad declares by introducing platform code, suspect `platform/windows/platform_gl.h`

Trying to create a fix

**Comment by bruvzg** [comment]
> This breaks compiling with MSVC, it seems to introduce bad declares by introducing platform code, suspect platform/windows/platform_gl.h

Strange, CI runs MSVC and passed.

**Comment by AThousandShips** [comment]
Starting with a simple undefine series but might be something that can be configured for the include to block the defines

**Comment by bruvzg** [comment]
> simple undefine series but might be something that can be configured for the include to block the defines, can alternatively build editor_node.cpp separately in scu

Or we can add another internal `OS` method like `set_current_rendering_method()` and remove the include, actual value is set in the same init code that sets `set_current_rendering_method`.

**Comment by AThousandShips** [comment]
Sounds like a more coherent solution, making a PR to split up the SCU as a band-aid while that solution can be implemented
