### PR TITLE
Camera2D: Fix crash calling align when not in tree

### LINKED ISSUE #45976: Simple executing align function in Camera2D cause crash of engine
**Godot version:**
Godot 3.2.4 rc 2

**Issue description:**
```
Camera2D.new().align()
```
cause crash with backtrace
```
scene/2d/camera_2d.cpp:503:49: runtime error: member call on misaligned address 0xbebebebebebebebe for type 'struct Viewport', which requires 8 byte alignment
0xbebebebebebebebe: note: pointer points here
<memory cannot be printed>
scene/2d/camera_2d.cpp:503:49: runtime error: member access within misaligned address 0xbebebebebebebebe for type 'struct Viewport', which requires 8 byte alignment
0xbebebebebebebebe: note: pointer points here
<memory cannot be printed>
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] godots() [0x16f757a] (/mnt/Miecz/godot3.2/platform/x11/crash_handler_x11.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f7507b4c210] (??:0)
[3] Camera2D::align() (/mnt/Miecz/godot3.2/scene/2d/camera_2d.cpp:503)
[4] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/./core/method_bind.gen.inc:61 (discriminator 4))
[5] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/core/object.cpp:919 (discriminator 1))
[6] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/mnt/Miecz/godot3.2/core/variant_call.cpp:1129 (discriminator 1))
[7] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript_function.cpp:1089)
[8] GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript.cpp:1238)
[9] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/core/object.cpp:898 (discriminator 1))
[10] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/mnt/Miecz/godot3.2/core/variant_call.cpp:1129 (discriminator 1))
[11] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript_function.cpp:1089)
[12] GDScriptInstance::_ml_call_reversed(GDScript*, StringName const&, Variant const**, int) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript.cpp:1269)
[13] GDScriptInstance::call_multilevel_reversed(StringName const&, Variant const**, int) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript.cpp:1278)
[14] Node::_notification(int) (/mnt/Miecz/godot3.2/scene/main/node.cpp:152)
[15] Node::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/main/node.h:46 (discriminator 14))
[16] CanvasItem::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/2d/canvas_item.h:166 (discriminator 3))
[17] Node2D::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/2d/node_2d.h:38 (discriminator 3))
[18] Object::notification(int, bool) (/mnt/Miecz/godot3.2/core/object.cpp:931)
[19] Node::_propagate_ready() (/mnt/Miecz/godot3.2/scene/main/node.cpp:197)
[20] Node::_propagate_ready() (/mnt/Miecz/godot3.2/scene/main/node.cpp:186 (discriminator 2))
[21] Node::_set_tree(SceneTree*) (/mnt/Miecz/godot3.2/scene/main/node.cpp:2560)
[22] SceneTree::init() (/mnt/Miecz/godot3.2/scene/main/scene_tree.cpp:464)
[23] OS_X11::run() (/mnt/Miecz/godot3.2/platform/x11/os_x11.cpp:3628)
[24] godots(main+0x331) [0x16ee467] (/mnt/Miecz/godot3.2/platform/x11/godot_x11.cpp:57)
[25] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f7507b2d0b3] (??:0)
[26] godots(_start+0x2e) [0x16ee07e] (??:?)
```

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #45976.

The `master` branch is not affected, the code changed there and it won't do a null pointer dereference.

### CODE REVIEW

File: scene/2d/camera_2d.cpp [hunk 1]
```diff
@@ -498,6 +498,7 @@ void Camera2D::reset_smoothing() {
 
 void Camera2D::align() {
 
+	ERR_FAIL_COND(is_inside_tree() || !viewport);
```
Comment (KoBeWi) [inline scene/2d/camera_2d.cpp:501]: Shouldn't it be `!is_inside_tree()`?

Comment (akien-mga) [reply scene/2d/camera_2d.cpp:501]: Yes definitely :facepalm:

**Review by Summersay415 — APPROVED** [review]

File: scene/2d/camera_2d.cpp (hunk 1 above)
Comment (akien-mga) [reply scene/2d/camera_2d.cpp]: Fixed.
