### PR TITLE
[Complex Text Layouts] Adds missing Font::SPACING_* to the controls, align glyphs to pixel grid.

### LINKED ISSUE #43966: TextServer: LineEdit height unexpectedly increases if it contains any text
**Godot version:** Git 0167bfa53

**OS/device including version:** Fedora 33, GeForce GTX 1080 (NVIDIA 455.45)

**Issue description:** LineEdit height unexpectedly increases if it contains any text. This makes most LineEdits appear taller than they used to be, since a lot of them have a placeholder.

Peek 2020-11-29 22-54

**Steps to reproduce:** Enter text into any LineEdit field in the project manager.

**Minimal reproduction project:** Use the Project Manager's New Project button and create a new folder using the FileDialog.

### LINKED ISSUE #43967: TextServer: Text is blurrier/less crisp than it used to be
**Godot version:** Git 0167bfa53

**OS/device including version:** Fedora 33, GeForce GTX 1080 (NVIDIA 455.45)

**Issue description:**

Text appears to be less sharp than it used to be in 3.2.3.

## `master` with TextServer, blurry text

*Compare the "Projects" and "Templates" text in the top-left corner between the 2 screenshots below.*

Blurry text

## 3.2.3 (Light font hinting), crisp text

Sharp text

**Steps to reproduce:**

On a loDPI display, open the project manager or editor and compare with Godot 3.2.3 with the Light font hinting setting.

**Minimal reproduction project:** N/A

### LINKED ISSUE #44002: Memory leak when using Label/RichTextLabel
**Godot version:**
4.0.dev.custom_build.ef2d1f6d1

Regression from 

**OS/device including version:**
Ubuntu 20.04
Nvidia GTX 970 - 440

**Issue description:**
This leak happens when I use Label or RichTextLabel
```
Direct leak of 424 byte(s) in 1 object(s) allocated from:
    #0 0x7f612166c6e7 in calloc (/lib/x86_64-linux-gnu/libasan.so.6+0xb06e7)
    #1 0x13da76ef in hb_object_create<hb_font_funcs_t> thirdparty/harfbuzz/src/hb-object.hh:227
    #2 0x13d9b6bf in hb_font_funcs_create thirdparty/harfbuzz/src/hb-font.cc:535
    #3 0x348ed3c in _hb_bmp_get_font_funcs modules/text_server_adv/bitmap_font_adv.cpp:179
    #4 0x348ee65 in _hb_bmp_font_set_funcs modules/text_server_adv/bitmap_font_adv.cpp:202
    #5 0x348eee3 in hb_bmp_font_create(BitmapFontDataAdvanced*, int, void (*)(void*)) modules/text_server_adv/bitmap_font_adv.cpp:211
    #6 0x3498936 in BitmapFontDataAdvanced::get_hb_handle(int) modules/text_server_adv/bitmap_font_adv.cpp:463
    #7 0x340c1bb in TextServerAdvanced::_shape_run(TextServerAdvanced::ShapedTextDataAdvanced*, int, int, hb_script_t, hb_direction_t, Vector<RID>, int, int) modules/text_server_adv/text_server_adv.cpp:1908
    #8 0x34208ec in TextServerAdvanced::shaped_text_shape(RID) modules/text_server_adv/text_server_adv.cpp:2238
    #9 0x3401235 in TextServerAdvanced::shaped_text_update_breaks(RID) modules/text_server_adv/text_server_adv.cpp:1559
    #10 0x10485f19 in TextServer::shaped_text_get_line_breaks(RID, float, int, unsigned char) const servers/text_server.cpp:614
    #11 0xcf87c5d in Label::_shape() scene/gui/label.cpp:102
    #12 0xcf97956 in Label::get_minimum_size() const scene/gui/label.cpp:358
    #13 0xcbf5b5c in Control::_update_minimum_size_cache() scene/gui/control.cpp:179
    #14 0xcbf69f7 in Control::get_combined_minimum_size() const scene/gui/control.cpp:198
    #15 0xcc272cd in Control::_size_changed() scene/gui/control.cpp:1328
    #16 0xcc077dd in Control::_notification(int) scene/gui/control.cpp:531
    #17 0x2c069ad in Control::_notificationv(int, bool) scene/gui/control.h:47
    #18 0xc910fe0 in Label::_notificationv(int, bool) scene/gui/label.h:37
    #19 0x1346e3cc in Object::notification(int, bool) core/object/object.cpp:793
    #20 0xc695e22 in Node::_propagate_ready() scene/main/node.cpp:184
    #21 0xc695ab9 in Node::_propagate_ready() scene/main/node.cpp:180
    #22 0xc695ab9 in Node::_propagate_ready() scene/main/node.cpp:180
    #23 0xc6e5806 in Node::_set_tree(SceneTree*) scene/main/node.cpp:2561
    #24 0xc7825b8 in SceneTree::init() scene/main/scene_tree.cpp:395
    #25 0x1e54bae in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:249
    #26 0x1e48030 in main platform/linuxbsd/godot_linuxbsd.cpp:58
    #27 0x7f61204390b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
```
**Steps to reproduce:**
1. Run minimal project with Godot compiled with address sanitizer or valgrind

**Minimal reproduction project:**
[RegressionTestProject.zip](https://github.com/godotengine/godot/files/5621432/RegressionTestProject.zip)

### LINKED ISSUE #44049: Crash when in ItemList::_shape due using TextParagraph null pointer
**Godot version:**
4.0.dev.custom_build. 2a0de6d88

**OS/device including version:**
Ubuntu 20.04
Nvidia GTX 970 - 440

**Issue description:**
Backtrace
```
scene/gui/item_list.cpp:39:22: runtime error: member call on null pointer of type 'struct TextParagraph'
scene/gui/item_list.cpp:39:22: runtime error: member access within null pointer of type 'struct TextParagraph'
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] godot4s() [0x1e52278] (/mnt/Miecz/godot/platform/linuxbsd/crash_handler_linuxbsd.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7fe5b9e4b210] (??:0)
[3] ItemList::_shape(int) (/mnt/Miecz/godot/scene/gui/item_list.cpp:39)
[4] ItemList::set_item_text(int, String const&) (/mnt/Miecz/godot/scene/gui/item_list.cpp:97)
[5] void call_with_ptr_args_helper<__UnexistingClass, int, String const&, 0ul, 1ul>(__UnexistingClass*, void (__UnexistingClass::*)(int, String const&), void const**, IndexSequence<0ul, 1ul>) (/mnt/Miecz/godot/./core/variant/binder_common.h:217 (discriminator 6))
[6] void call_with_ptr_args<__UnexistingClass, int, String const&>(__UnexistingClass*, void (__UnexistingClass::*)(int, String const&), void const**) (/mnt/Miecz/godot/./core/variant/binder_common.h:436)
[7] MethodBindT<int, String const&>::ptrcall(Object*, void const**, void*) (/mnt/Miecz/godot/./core/object/method_bind.h:293)
[8] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/mnt/Miecz/godot/modules/gdscript/gdscript_vm.cpp:1710)
[9] GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) (/mnt/Miecz/godot/modules/gdscript/gdscript.cpp:1555)
[10] Object::call(StringName const&, Variant const**, int, Callable::CallError&) (/mnt/Miecz/godot/core/object/object.cpp:765 (discriminator 1))
[11] Variant::call(StringName const&, Variant const**, int, Variant&, Callable::CallError&) (/mnt/Miecz/godot/core/variant/variant_call.cpp:611)
[12] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/mnt/Miecz/godot/modules/gdscript/gdscript_vm.cpp:1377)
[13] GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) (/mnt/Miecz/godot/modules/gdscript/gdscript.cpp:1555)
[14] ScriptInstance::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/mnt/Miecz/godot/core/object/script_language.cpp:303)
[15] Node::_notification(int) (/mnt/Miecz/godot/scene/main/node.cpp:58)
[16] Node::_notificationv(int, bool) (/mnt/Miecz/godot/./scene/main/node.h:45 (discriminator 14))
[17] CanvasItem::_notificationv(int, bool) (/mnt/Miecz/godot/./scene/main/canvas_item.h:163 (discriminator 3))
[18] Control::_notificationv(int, bool) (/mnt/Miecz/godot/./scene/gui/control.h:47 (discriminator 3))
[19] ItemList::_notificationv(int, bool) (/mnt/Miecz/godot/scene/gui/item_list.h:39 (discriminator 3))
[20] Object::notification(int, bool) (/mnt/Miecz/godot/core/object/object.cpp:795)
[21] SceneTree::_notify_group_pause(StringName const&, int) (/mnt/Miecz/godot/scene/main/scene_tree.cpp:818)
[22] SceneTree::idle(float) (/mnt/Miecz/godot/scene/main/scene_tree.cpp:447 (discriminator 2))
[23] Main::iteration() (/mnt/Miecz/godot/main/main.cpp:2498)
[24] OS_LinuxBSD::run() (/mnt/Miecz/godot/platform/linuxbsd/os_linuxbsd.cpp:261)
[25] godot4s(main+0x40b) [0x1e50031] (/mnt/Miecz/godot/platform/linuxbsd/godot_linuxbsd.cpp:60)
[26] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fe5b9e2c0b3] (??:0)
[27] godot4s(_start+0x2e) [0x1e4fb6e] (??:?)
-- END OF BACKTRACE --

```

**Steps to reproduce:**
1. Run minimal project

**Minimal reproduction project:**
[TheWorstGodotTestProject.zip](https://github.com/godotengine/godot/files/5632046/TheWorstGodotTestProject.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
- Fixes oversized editor control height (default editor spacing is negative) and control size changing when text is set.

Fixes #43966

- Round glyph offsets and advances to make small size text sharper.

Fixes #43967

- Fixes bitmap font leak.

Fixes #44002

- Fixes missing text buffer init in `ItemList::add_icon_item`.

Fixes #44049

- Some optimizations.

### CODE REVIEW

File: scene/resources/text_paragraph.cpp [hunk 1]
```diff
@@ -490,16 +504,18 @@ void TextParagraph::draw_line_outline(RID p_canvas, const Vector2 &p_pos, int p_
...
 	return TS->shaped_text_draw_outline(lines[p_line], p_canvas, ofs, -1, -1, p_outline_size, p_color);
 }
 
 TextParagraph::TextParagraph(const String &p_text, const Ref<Font> &p_fonts, int p_size, const Dictionary &p_opentype_features, const String &p_language, float p_width, TextServer::Direction p_direction, TextServer::Orientation p_orientation) {
 	rid = TS->create_shaped_text(p_direction, p_orientation);
 	TS->shaped_text_add_string(rid, p_text, p_fonts->get_rids(), p_size, p_opentype_features, p_language);
+	spacing_top = p_fonts->get_spacing(Font::SPACING_TOP);
+	spacing_bottom = p_fonts->get_spacing(Font::SPACING_BOTTOM);
 	width = p_width;
 	dirty_lines = true;
```
Comment (akien-mga) [inline scene/resources/text_paragraph.cpp:520]: Nitpick but this one is redundant since it's already initialized to `true` in the header.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
