### PR TITLE
Make Lookup Symbol recognize `assert` and `preload` in the script editor

### LINKED ISSUE #61376: Preload not recognised as a symbol
### Godot version

v3.4.4.stable.flathub [419e713a2], v4.0.alpha8.official [cc3ed63af]

### System information

Pop!_OS 22.04 LTS 64-bit

### Issue description

In a line with preload:
```gdscipt
var icon = preload("res://icon.png")
```

Preload is not properly recognised as a symbol. In 3.x, right-clicking it won't show "Lookup Symbol" in the right click menu, and the help page doesn't open when ctrl-clicking. The word `preload` is underlined when mousing over with ctrl held, however.

In 4.0, the behaviour is the same except no underline appears when mousing over with ctrl held. (Possibly related: #61374)

### Steps to reproduce

Right click on `preload` in 

```gdscipt
var icon = preload("res://icon.png")
```
see no option to Lookup Symbol.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by snailrhymer**
Fixes #61376 for `master` by adding a special case for `assert` and `preload` to  GDScriptLanguage::lookup_code.

If this is an appropriate fix, `3.x` will need at least `yield` and possibly other `@GDScript` 'methods' added to the special case.

### CODE REVIEW

**Comment by KoBeWi** [comment]
I checked whether it would conflict with custom functions, but seems like you can't make a func called `preload()` or `assert()`, so it's ok.

File: modules/gdscript/gdscript_editor.cpp [hunk 1]
```diff
@@ -3178,6 +3178,13 @@ ::Error GDScriptLanguage::lookup_code(const String &p_code, const String &p_symb
 		return OK;
 	}
 
+	if ("assert" == p_symbol || "preload" == p_symbol) {
```
Comment (akien-mga) [inline modules/gdscript/gdscript_editor.cpp:3181]: These could be put as `||` checks in the above `function_exists()` one since the block is the same.

**Review by akien-mga — APPROVED** [review]

File: modules/gdscript/gdscript_editor.cpp (hunk 1 above)
Comment (akien-mga) [reply modules/gdscript/gdscript_editor.cpp:3181]: Maybe also add a short comment that `assert` and `preload` are pseudo-functions (actually keywords).

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

Feel free to PR the matching fix for `3.x`.
