### PR TITLE
Fix AudioServer missing deletes.

### LINKED ISSUE #103882: There is a memory leak defect at line 1234 in the file /godot/servers/audio_server.cpp.
### Tested versions

4.4-stable

### System information

Ubuntu 20.04

### Issue description

At line 1225 in the file /godot/servers/audio_server.cpp, a pointer variable named playback_node is defined and allocated a new dynamic memory region using the new operator. When the if condition at line 1232 evaluates to true, the function neither utilizes the dynamic memory region pointed to by playback_node as done at line 1259 nor frees the dynamic memory region pointed to by new_bus_details (another dynamically allocated memory block) before returning, as done at line 1233. This results in a memory leak defect, as illustrated below.
https://github.com/LuMingYinDetect/godot_defects/blob/main/godot_2.png

### Steps to reproduce

It can be triggered by following the path.

### Minimal reproduction project (MRP)

It can be triggered by following the path.

### LINKED ISSUE #103883: There is a memory leak defect at line 1325 in the file /godot/servers/audio_server.cpp.
### Tested versions

4.4-stable

### System information

Ubuntu 20.04

### Issue description

A pointer variable named new_bus_details is defined at line 1318 in the file /godot/servers/audio_server.cpp and allocated a new dynamic memory region using the new operator. At line 1325, ERR_FAIL_COND is essentially a macro definition, which causes the function to return when an if condition evaluates to true. Therefore, at this point, when the if condition evaluates to true, the function will return. At this time, the dynamic memory region pointed to by new_bus_details is neither used, as seen at line 1338, nor freed, resulting in a memory leak defect, as shown in the figure below:
https://github.com/LuMingYinDetect/godot_defects/blob/main/godot_3.png

### Steps to reproduce

The defect can be triggered by following the path provided in the figure.

### Minimal reproduction project (MRP)

The defect can be triggered by following the path provided in the figure.

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/103882
Fixes https://github.com/godotengine/godot/issues/103883

### CODE REVIEW

File: servers/audio_server.cpp [hunk 1]
```diff
@@ -1230,6 +1230,7 @@ void AudioServer::start_playback_stream(Ref<AudioStreamPlayback> p_playback, con
 	int idx = 0;
 	for (KeyValue<StringName, Vector<AudioFrame>> pair : p_bus_volumes) {
 		if (pair.value.size() < channel_count || pair.value.size() != MAX_CHANNELS_PER_BUS) {
+			delete playback_node;
 			delete new_bus_details;
```
Comment (bruvzg) [inline servers/audio_server.cpp:1234]: Is there any reason why `AudiServer` is using generic `new`/`delete` instead of our custom `memnew`/`memdelete`?

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
