### PR TITLE
GLES2 fix for consistent light ordering with BVH

### LINKED ISSUE #46353: Dynamic light is flickering possibly a bug with BVH+Fog interaction
**Godot version:**

3.2.4 rc3

**OS/device including version:**

NVIDIA 1650 Super
3.2.4 RC 3
GLES2

**Issue description:**

Dynamic light is now flickering in intensity in my game. 
I don't remember if previous RC 2 had this but it definitely didn't happen in 3.2.3 .
If I turn BVH off the flicker goes away. I'm fairly confident is related to BVH changes.  

**Edit: Further testing reveals is related to BVH + Fog option turned on. It doesn't happen with BVH off or with BVH on + Fog off and it doesn't happen when you are very close to the light only when you are quite a bit away. Might also be related with the Fog option `fog_transmit_enabled` ** 

a

Looks like my game is ready for Christmas 🎄 🤣  

**Steps to reproduce:**

See minimal reproduction project. Is a complex interaction between multiple components. bvh + animated point meshes + fog + fog_transmit_enabled + dynamic light with cast shadow enabled.

**Minimal reproduction project:**

[bvh_test.zip](https://github.com/godotengine/godot/files/6031132/bvh_test.zip)

### PR DESCRIPTION
**Pull request by lawnjelly**
Due to multi pass approach to lighting in GLES2, it has become apparent that in some situations the rendered result can look different if lights are presented in a different order.

The order (aside from directional lights) seems to be simply copied from the culling routine (octree or bvh or portals) which is essentially arbitrary. While octree is usually consistent with order, bvh uses a trickle optimize which may result in lights occurring in different order from frame to frame.

This PR adds an extra layer of sorting on GLES2 lights in order to get some kind of order consistency.

Fixes #46353.

## Notes
* Making this draft as I want to get some opinion from @clayjohn before finalizing.
* Should we make this consistent ordering occur in all cases, or limit (as I have here) to when `fog_transmit` is used? I suspect that there may be more cases where ordering matters. On the other hand if we make it global we will never find out when it is, and when not required.
* Here I am just sorting by memory address. This is arbitrary, but should be consistent on a 'run' of the program. Maybe there's something slightly better we could sort by. Position in the scene tree?
* There is the slight possibility of this having an interaction with some other sorting (I'm not super familiar with GLES2 3d rasterizer), so that is something to bear in mind as we get close to 3.2.4 stable.

This whole area is interesting, because it suggests that the current rendered result of some GLES2 scenes is subject to some random effects (e.g. some lights relatively brighter than others). To me, the whole order dependence is a 'render smell', however practically speaking it may come with the territory of multipass rendering.

I suspect GLES2 has been vulnerable to issue #46353 all along, even with octree, but the visual result was harder to notice until the flickering caused by bvh made it apparent.

### CODE REVIEW

**Comment by clayjohn** [comment]
This PR looks fine. Sorting should be relatively fast as users shouldn't have too many lights in GLES2 to begin with. 

That being said, we should first try changing the shader to not rely on the order of the lights. 

In GLES3 ``fog_transmit`` works by altering the ``fog_color`` by the total light in the scene:
https://github.com/godotengine/godot/blob/e5fcb41aabc683b36ad566e466a8dcf014981063/drivers/gles3/shaders/scene.glsl#L2239-L2243

``fog_color`` is then mixed into the emission channel:
https://github.com/godotengine/godot/blob/e5fcb41aabc683b36ad566e466a8dcf014981063/drivers/gles3/shaders/scene.glsl#L2253

In GLES2 this same process happens, but only for one light at a time (so instead of ``total_light`` it uses "light from the current light":
https://github.com/godotengine/godot/blob/e5fcb41aabc683b36ad566e466a8dcf014981063/drivers/gles2/shaders/scene.glsl#L2250-L2254

``fog_color`` is only mixed back in on the base pass. So the ``total_light`` only ends up including the first light:
https://github.com/godotengine/godot/blob/e5fcb41aabc683b36ad566e466a8dcf014981063/drivers/gles2/shaders/scene.glsl#L2265-L2268

In a perfect world, we could rewrite this to blend ``fog_color`` from all light sources, and then order won't matter.

I'm wondering if it is as easy as always mixing fog color before scaling e.g. the above code becomes:

```
        gl_FragColor.rgb = mix(gl_FragColor.rgb, fog_color, fog_amount);
#if !defined(BASE_PASS)
	gl_FragColor.rgb *= (1.0 - fog_amount);
#endif
```

**Comment by lawnjelly** [comment]
If we have the option I agree a fix to the shader would be preferable -

I'm not familiar enough with the scene shaders yet (especially things like fog) to make a shader fix so go for it with a PR if you come up with something that works. I'll try it out. :+1:

File: drivers/gles2/rasterizer_scene_gles2.cpp [hunk 1]
```diff
@@ -3285,6 +3285,30 @@ void RasterizerSceneGLES2::render_scene(const Transform &p_cam_transform, const
...
 
+		// for fog transmission, we want some kind of consistent ordering of lights
+		// add any more conditions here in which we need consistent light ordering
+		// (perhaps we always should have it, but don't know yet)
+		if (env && env->fog_transmit_enabled) {
+
+			struct _LightSort {
+
+				bool operator()(LightInstance *A, LightInstance *B) const {
+					return A > B;
```
Comment (clayjohn) [inline drivers/gles2/rasterizer_scene_gles2.cpp:3296]: Will this result in a consistent sort across runs? I'm worried that each time the game is run this will result in a random sort order. If the user has a mix of dim and bright lights this would be very noticeable.

Comment (lawnjelly) [reply drivers/gles2/rasterizer_scene_gles2.cpp:3296]: Nope, as each time you run the memory addresses may well be different in relation to each other. But I suspect there is a similar problem with octree already - order of adding etc may be important. There may not be a perfect solution in that respect.

There may be something else we can use for more consistent sorting. We could just give lights an ever increasing ID (for each allocation) and sort on that? That might be better as it would be consistent within the run and between runs (providing everything was exactly the same). It's just storing an extra value with each light but I don't think that should matter.

Comment (lawnjelly) [reply drivers/gles2/rasterizer_scene_gles2.cpp]: I've now added a per light counter as discussed above, a little bit more verbose, but should be consistent between runs of the game. :+1:

**Review by clayjohn — APPROVED** [review]
I'm not happy about fog only taking the first light into account. But fixing how fog works in the multipass renderer is beyond the scope of this PR. 

This PR fixes the flickering issue which is the reported issue from bug reports. Plus this approach will fix any other visual glitches that arise as a result of other order-dependent lighting effects.

**Review by JFonS — APPROVED** [review]
Looks good to me :)

**Comment by akien-mga** [comment]
Thanks!
