### PR TITLE
Fix highlight rect in "Whole search" being slightly offset

### LINKED ISSUE #83009: Highlight rect in "Whole search" is slightly offseted since 4.2.dev1
### Godot version

v4.2.dev1.official [0c2144da9]

### System information

Godot v4.2.dev1 - Linux Mint 21.1 (Vera) - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (RADV NAVI22) () - 12th Gen Intel(R) Core(TM) i5-12400 (12 Threads)

### Issue description

Since 4.2.dev1, the highlight rectangle of the whole search (Ctrl+Maj+F) is slightly offseted to the left : 
godot_whole_search_highlight_issue

Issue is still here on 4.2.dev6.

EDIT : Is it related to commit 92287c2 ?

### Steps to reproduce

1. In script editor : Ctrl+Maj+F, then search for a word
2. See the highlight rectangle

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by joao-pedro-braz**
This fixes https://github.com/godotengine/godot/issues/83009.

cc @Calinou

### CODE REVIEW

File: editor/find_in_files.cpp [hunk 1]
```diff
@@ -604,6 +604,8 @@ FindInFilesPanel::FindInFilesPanel() {
 	_results_display->set_select_mode(Tree::SELECT_ROW);
 	_results_display->set_allow_rmb_select(true);
 	_results_display->set_allow_reselect(true);
+	_results_display->add_theme_constant_override("inner_item_margin_left", 0);	
+	_results_display->add_theme_constant_override("inner_item_margin_right", 0);
```
Comment (akien-mga) [inline editor/find_in_files.cpp:608]:
```suggestion
	_results_display->add_theme_constant_override("inner_item_margin_left", 0);
	_results_display->add_theme_constant_override("inner_item_margin_right", 0);
```

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` c5291a3555343e8aa5aefa1c7e17f2ad05ee1fc9), it works as expected.

image

200% editor scale:

image

**Comment by akien-mga** [comment]
Thanks!
