### PR TITLE
Fix tab container too large when tabs are hidden

### LINKED ISSUE #35030: Tab container with invisible tabs still expands rect size
**Godot version:** 3.2 Beta 5

**OS/device including version:**
Linux Mint 19.3

**Issue description:**
image
image

The rect size calculation does not reduce when tabs are not visible

**Steps to reproduce:**
Create a tab container with a child such as a label with a single line of text
Disable tabs visible, and you will see that the panel has a huge margin on the bottom

Other Notes:

- If you make a tab with a ridiculous margin, it continue to match the same height. Even while the tabs are not visible, it will expand immediately
image
image
- "Use Hidden Tabs for min size" really sounds like it would cause this, but it is referring to the content below the tabs. Regardless, it is disabled currently
- Cherry pick 3.2?

**Minimal reproduction project:**
[Test4.zip](https://github.com/godotengine/godot/files/4050080/Test4.zip)

### PR DESCRIPTION
**Pull request by nathanfranke**
Fixes #35030 

tabcontainerfix

This is my first pull request, so hopefully everything works well

Also fixed a spelling mistake... For some reason the argument `p_visible` was misspelled as `p_visibe`

### CODE REVIEW

File: scene/gui/tab_container.cpp [hunk 1]
```diff
@@ -785,23 +785,25 @@ TabContainer::TabAlign TabContainer::get_tab_align() const {
...
 		Control *c = tabs[i];
-		if (p_visibe)
+		if (p_visible)
 			c->set_margin(MARGIN_TOP, _get_top_margin());
 		else
 			c->set_margin(MARGIN_TOP, 0);
 	}
+
 	update();
+	minimum_size_changed();
```
Comment (nathanwfranke) [inline scene/gui/tab_container.cpp]: Does anyone know if this is a standard code practice? Without `minimum_size_changed()`, the size doesn't seem to update (as I would assume would happen with `update()`)

**Review by nathanfranke — COMMENTED** [review]
Not sure if I should be calling `minimum_size_changed()` here

File: scene/gui/tab_container.cpp (hunk 1 above)
Comment (aaronfranke) [reply scene/gui/tab_container.cpp]: `update` is a member of `CanvasItem`, while `minimum_size_changed` is a member of `Control`, so `update` can't call `minimum_size_changed`.

**Review by aaronfranke — APPROVED** [review]
I can confirm that this works and that the fix makes sense.

`minimum_size_changed` has some checks (which might be unnecessary) and then calls `_update_minimum_size` internally, but `_update_minimum_size` is private so we can't use that, so this PR is correct to use `minimum_size_changed` even though the user didn't manually change that specifically so the name of the method is a little bit misleading.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.
