### PR TITLE
Fix the Animation Optimization results for Nearest and Cubic Interpolation

### LINKED ISSUE #105385: Animation Optimization results for Nearest Interpolation is not correct
### Tested versions

- Reproducible in Godot v4.4.1.stable

### System information

Godot v4.4.1.stable - Gentoo 2.17 on X11 - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA RTX A6000 (nvidia; 570.86.16) - AMD Ryzen 9 5950X 16-Core Processor (32 threads)

### Issue description

The `Optimize Animation` operation does not respect the interpolation mode of the track (specifically tested with the `nearest` mode).

Keys, that move on a linear trajectory (so essentially keys that *would not* be necessary for linear interpolation, but *are* in fact required for nearest interpolation) are optimized away, causing big discrepancy between before and after optimization, essentially breaking the animation.

### Steps to reproduce

- Create gltf with keys on linear trajectory, but on nearest interpolation.
- import the file on the correct framerate with or without optimization in the advanced import settings enabled

Before optimization:
Image

After optimization:
Image

### Minimal reproduction project (MRP)

[bug-animation_optimization_interpolation_mode-mrp.zip](https://github.com/user-attachments/files/19737754/bug-animation_optimization_interpolation_mode-mrp.zip)

### PR DESCRIPTION
**Pull request by lazarosY**
This is a proposed fix for the issue :[#105385](https://github.com/godotengine/godot/issues/105385). Now both before and after animation optimization, the additional keys that wouldn't be "necessary" for _linear_ interpolation will be retained should they be necessary for _Nearest_ interpolation.

image

* *Bugsquad edit, fixes: https://github.com/godotengine/godot/issues/105385*

### CODE REVIEW

**Comment by lazarosY** [comment]
The lines 4456 and for 4457 contain the appropriate fix.

**Review by AThousandShips — CHANGES_REQUESTED** [review]
Thank you for your contribution! But you've created a new file instead of modifying the correct one

**Comment by lazarosY** [comment]
> Thank you for your contribution! But you've created a new file instead of modifying the correct one

Apologies, I am fixing it now

**Comment by lazarosY** [comment]
Should be fine now.

File: scene/resources/animation.cpp [hunk 1]
```diff
@@ -4455,6 +4453,9 @@ void Animation::_value_track_optimize(int p_idx, real_t p_allowed_velocity_err,
 void Animation::optimize(real_t p_allowed_velocity_err, real_t p_allowed_angular_err, int p_precision) {
 	real_t precision = Math::pow(0.1, p_precision);
 	for (int i = 0; i < tracks.size(); i++) {
+		if (track_get_interpolation_type(i) == Animation::INTERPOLATION_NEAREST) {
+			continue;
+		}
```
Comment (lazarosY) [inline scene/resources/animation.cpp:4458]: These are the changes I made.

File: scene/resources/animation.cpp [hunk 2]
```diff
@@ -2478,7 +2476,7 @@ Variant Animation::_interpolate_angle(const Variant &p_a, const Variant &p_b, re
 	if (vformat == ((1 << Variant::INT) | (1 << Variant::FLOAT)) || vformat == (1 << Variant::FLOAT)) {
 		real_t a = p_a;
 		real_t b = p_b;
-		return Math::fposmod((float)Math::lerp_angle(a, b, p_c), (float)Math::TAU);
+		return Math::fposmod((float)Math::lerp_angle(a, b, p_c), (float)Math_TAU);
```
Comment (fire) [inline scene/resources/animation.cpp:2479]: These changes to Math::TAU are incorrect.

Comment (lazarosY) [reply scene/resources/animation.cpp:2479]: I didnt even change that, well be right back.

**Review by TokageItLab — CHANGES_REQUESTED** [review]

**Review by TokageItLab — CHANGES_REQUESTED** [review]
As I said in the comment https://github.com/godotengine/godot/issues/105385#issuecomment-2811502639, Nearest can be optimized to some extent, so skipping everything here is not the right approach.

For example, look at the following:

```cpp
bool Animation::_float_track_optimize_key(const TKey<float> t0, const TKey<float> t1, const TKey<float> t2, real_t p_allowed_velocity_err, real_t p_allowed_precision_error) {
	// Remove overlapping keys.
	if (Math::is_equal_approx(t0.time, t1.time) || Math::is_equal_approx(t1.time, t2.time)) {
		return true;
	}
	if (abs(t0.value - t1.value) < p_allowed_precision_error && abs(t1.value - t2.value) < p_allowed_precision_error) {
		return true;
	}
	// Calc velocities.
	double v0 = (t1.value - t0.value) / (t1.time - t0.time);
	double v1 = (t2.value - t1.value) / (t2.time - t1
```

There is a check for the exact equality of the keys in the first. And it should also be valid for Nearest. So if we were to skip some checks for the Nearest, you could add a line under the equality check that would return `false` to skip velocity check if it is Nearest like:

```cpp
bool Animation::_float_track_optimize_key(const TKey<float> t0, const TKey<float> t1, const TKey<float> t2, real_t p_allowed_velocity_err, real_t p_allowed_precision_error, bool p_is_nearest) {
	// Remove overlapping keys.
	if (Math::is_equal_approx(t0.time, t1.time) || Math::is_equal_approx(t1.time, t2.time)) {
		return true;
	}
	if (abs(t0.value - t1.value) < p_allowed_precision_error && abs(t1.value - t2.value) < p_allowed_precision_error) {
		return true;
	}
	if (p_is_nearest) {
		return false;
	}
	// Calc velocities.
	double v0 = (t1.value - t0.value) / (t1.time - t0.time);
	double v1 = (t2.value - t1.value) / (t2.time - t1
```

**Comment by lazarosY** [comment]
> As I said in the comment [#105385 (comment)](https://github.com/godotengine/godot/issues/105385#issuecomment-2811502639), Nearest can be optimized to some extent, so skipping everything here is not the right approach.
> 
> For example, look at the following:
> 
> ```c++
> bool Animation::_float_track_optimize_key(const TKey<float> t0, const TKey<float> t1, const TKey<float> t2, real_t p_allowed_velocity_err, real_t p_allowed_precision_error) {
> 	// Remove overlapping keys.
> 	if (Math::is_equal_approx(t0.time, t1.time) || Math::is_equal_approx(t1.time, t2.time)) {
> 		return true;
> 	}
> 	if (abs(t0.value - t1.value) < p_allowed_precision_error && abs(t1.value - t2.value) < p_allowed_precision_error) {
> 		return true;
> 	}
> 	// Calc velocities.
> 	double v0 = (t1.value - t0.value) / (t1.time - t0.time);
> 	double v1 = (t2.value - t1.value) / (t2.time - t1
> ```
> 
> There is a check for the exact equality of the keys in the first. And it should also be valid for Nearest. So if we were to skip some checks for the Nearest, you could add a line under the equality check that would return `false` to skip velocity check if it is Nearest like:
> 
> ```c++
> bool Animation::_float_track_optimize_key(const TKey<float> t0, const TKey<float> t1, const TKey<float> t2, real_t p_allowed_velocity_err, real_t p_allowed_precision_error, bool p_is_nearest) {
> 	// Remove overlapping keys.
> 	if (Math::is_equal_approx(t0.time, t1.time) || Math::is_equal_approx(t1.time, t2.time)) {
> 		return true;
> 	}
> 	if (abs(t0.value - t1.value) < p_allowed_precision_error && abs(t1.value - t2.value) < p_allowed_precision_error) {
> 		return true;
> 	}
> 	if (p_is_nearest) {
> 		return false;
> 	}
> 	// Calc velocities.
> 	double v0 = (t1.value - t0.value) / (t1.time - t0.time);
> 	double v1 = (t2.value - t1.value) / (t2.time - t1
> ```

Thank you very much for taking the time to look into it and guiding me as much as you did. I will implement the fix as you've requested and get back to you.

File: scene/resources/animation.cpp [hunk 3]
```diff
@@ -4311,14 +4330,17 @@ void Animation::_blend_shape_track_optimize(int p_idx, real_t p_allowed_velocity
 	ERR_FAIL_INDEX(p_idx, tracks.size());
 	ERR_FAIL_COND(tracks[p_idx]->type != TYPE_BLEND_SHAPE);
 	BlendShapeTrack *bst = static_cast<BlendShapeTrack *>(tracks[p_idx]);
-
+	bool p_is_nearest = false;
```
Comment (TokageItLab) [inline scene/resources/animation.cpp:4333]:
```suggestion
```

File: scene/resources/animation.cpp [hunk 4]
```diff
@@ -4367,7 +4393,7 @@ void Animation::_value_track_optimize(int p_idx, real_t p_allowed_velocity_err,
 						break; // Rotation is more than 180 deg, keep key.
 					}
 				}
-				erase = _float_track_optimize_key(t0, t1, t2, p_allowed_velocity_err, p_allowed_precision_error);
+				erase = _float_track_optimize_key(t0, t1, t2, p_allowed_velocity_err, p_allowed_precision_error, p_is_nearest);
```
Comment (TokageItLab) [inline scene/resources/animation.cpp:4396]:
```suggestion
				erase = _float_track_optimize_key(t0, t1, t2, p_allowed_velocity_err, p_allowed_precision_error, track_get_interpolation_type(i) == Animation::INTERPOLATION_NEAREST);
```

File: scene/resources/animation.cpp [hunk 5]
```diff
@@ -4379,7 +4405,7 @@ void Animation::_value_track_optimize(int p_idx, real_t p_allowed_velocity_err,
 				t0.value = vt->values[i].value;
 				t1.value = vt->values[i + 1].value;
 				t2.value = vt->values[i + 2].value;
-				erase = _vector2_track_optimize_key(t0, t1, t2, p_allowed_velocity_err, p_allowed_angular_err, p_allowed_precision_error);
+				erase = _vector2_track_optimize_key(t0, t1, t2, p_allowed_velocity_err, p_allowed_angular_err, p_allowed_precision_error, p_is_nearest);
```
Comment (TokageItLab) [inline scene/resources/animation.cpp:4408]:
```suggestion
				erase = _vector2_track_optimize_key(t0, t1, t2, p_allowed_velocity_err, p_allowed_angular_err, p_allowed_precision_error, track_get_interpolation_type(i) == Animation::INTERPOLATION_NEAREST);
```

File: scene/resources/animation.cpp [hunk 6]
```diff
@@ -4391,7 +4417,7 @@ void Animation::_value_track_optimize(int p_idx, real_t p_allowed_velocity_err,
 				t0.value = vt->values[i].value;
 				t1.value = vt->values[i + 1].value;
 				t2.value = vt->values[i + 2].value;
-				erase = _vector3_track_optimize_key(t0, t1, t2, p_allowed_velocity_err, p_allowed_angular_err, p_allowed_precision_error);
+				erase = _vector3_track_optimize_key(t0, t1, t2, p_allowed_velocity_err, p_allowed_angular_err, p_allowed_precision_error, p_is_nearest);
```
Comment (TokageItLab) [inline scene/resources/animation.cpp:4420]:
```suggestion
				erase = _vector3_track_optimize_key(t0, t1, t2, p_allowed_velocity_err, p_allowed_angular_err, p_allowed_precision_error, track_get_interpolation_type(i) == Animation::INTERPOLATION_NEAREST);
```

File: scene/resources/animation.cpp [hunk 7]
```diff
@@ -4403,7 +4429,7 @@ void Animation::_value_track_optimize(int p_idx, real_t p_allowed_velocity_err,
 				t0.value = vt->values[i].value;
 				t1.value = vt->values[i + 1].value;
 				t2.value = vt->values[i + 2].value;
-				erase = _quaternion_track_optimize_key(t0, t1, t2, p_allowed_velocity_err, p_allowed_angular_err, p_allowed_precision_error);
+				erase = _quaternion_track_optimize_key(t0, t1, t2, p_allowed_velocity_err, p_allowed_angular_err, p_allowed_precision_error, p_is_nearest);
```
Comment (TokageItLab) [inline scene/resources/animation.cpp:4432]:
```suggestion
				erase = _quaternion_track_optimize_key(t0, t1, t2, p_allowed_velocity_err, p_allowed_angular_err, p_allowed_precision_error, track_get_interpolation_type(i) == Animation::INTERPOLATION_NEAREST);
```

**Review by TokageItLab — CHANGES_REQUESTED** [review]
I believe the implementation way is fine, so I would suggest just formatting the coding style. We will test it later to see if it fixes the issue.

**Comment by lazarosY** [comment]
> I believe the implementation way is fine, so I would suggest just formatting the coding style. We will test it later to see if it fixes the issue.

I implemented your suggestions, hoping for a favorable result! Thank you so much for all the time you spent reviewing and helping me out.

File: scene/resources/animation.cpp [hunk 8]
```diff
@@ -4233,14 +4246,12 @@ void Animation::_position_track_optimize(int p_idx, real_t p_allowed_velocity_er
...
 	PositionTrack *tt = static_cast<PositionTrack *>(tracks[p_idx]);
-
 	int i = 0;
 	while (i < tt->positions.size() - 2) {
 		TKey<Vector3> t0 = tt->positions[i];
 		TKey<Vector3> t1 = tt->positions[i + 1];
 		TKey<Vector3> t2 = tt->positions[i + 2];
-
-		bool erase = _vector3_track_optimize_key(t0, t1, t2, p_allowed_velocity_err, p_allowed_angular_err, p_allowed_precision_error);
+		bool erase = _vector3_track_optimize_key(t0, t1, t2, p_allowed_velocity_err, p_allowed_angular_err, p_allowed_precision_error, track_get_interpolation_type(i) == Animation::INTERPOLATION_NEAREST);
```
Comment (TokageItLab) [inline scene/resources/animation.cpp:4254]: A closer look at the code reveals that `i` is a mistake as it is the key index. The correct variable for the track index is `p_idx`, so which should be:
```cpp
	int i = 0;
	bool is_nearest = tracks[p_idx]->interpolation == INTERPOLATION_NEAREST;
	while (i < tt->positions.size() - 2) {
		TKey<Vector3> t0 = tt->positions[i];
		TKey<Vector3> t1 = tt->positions[i + 1];
		TKey<Vector3> t2 = tt->positions[i + 2];
		bool erase = _vector3_track_optimize_key(t0, t1, t2, p_allowed_velocity_err, p_allowed_angular_err, p_allowed_precision_error, is_nearest);
```
Please make the same correction elsewhere.

**Review by TokageItLab — CHANGES_REQUESTED** [review]

File: scene/resources/animation.cpp [hunk 9]
```diff
@@ -4233,14 +4246,19 @@ void Animation::_position_track_optimize(int p_idx, real_t p_allowed_velocity_er
...
 	ERR_FAIL_COND(tracks[p_idx]->type != TYPE_POSITION_3D);
 	PositionTrack *tt = static_cast<PositionTrack *>(tracks[p_idx]);
-
+	bool is_nearest = false;
+	if (tracks[p_idx]->interpolation == INTERPOLATION_NEAREST) {
+		is_nearest = true;
+	}
+	else if (tracks[p_idx]->interpolation != INTERPOLATION_LINEAR) {
+		return;
+	}
```
Comment (TokageItLab) [inline scene/resources/animation.cpp:4255]:
```suggestion
	bool is_nearest = false;
	if (tracks[p_idx]->interpolation == INTERPOLATION_NEAREST) {
		is_nearest = true;
	}
	else if (tracks[p_idx]->interpolation != INTERPOLATION_LINEAR) {
		return;
	}
	PositionTrack *tt = static_cast<PositionTrack *>(tracks[p_idx]);
```
It is better to place the checking just below the error check because static_cast may be ignored.

File: scene/resources/animation.cpp [hunk 10]
```diff
@@ -4259,14 +4277,13 @@ void Animation::_rotation_track_optimize(int p_idx, real_t p_allowed_velocity_er
 	ERR_FAIL_INDEX(p_idx, tracks.size());
 	ERR_FAIL_COND(tracks[p_idx]->type != TYPE_ROTATION_3D);
 	RotationTrack *rt = static_cast<RotationTrack *>(tracks[p_idx]);
-
 	int i = 0;
+	bool is_nearest = tracks[p_idx]->interpolation == INTERPOLATION_NEAREST;
```
Comment (TokageItLab) [inline scene/resources/animation.cpp:4281]: Implementation should be matched with others.

File: scene/resources/animation.cpp [hunk 11]
```diff
@@ -4285,14 +4302,13 @@ void Animation::_scale_track_optimize(int p_idx, real_t p_allowed_velocity_err,
 	ERR_FAIL_INDEX(p_idx, tracks.size());
 	ERR_FAIL_COND(tracks[p_idx]->type != TYPE_SCALE_3D);
 	ScaleTrack *st = static_cast<ScaleTrack *>(tracks[p_idx]);
-
 	int i = 0;
+	bool is_nearest = tracks[p_idx]->interpolation == INTERPOLATION_NEAREST;
```
Comment (TokageItLab) [inline scene/resources/animation.cpp:4306]: Implementation should be matched with others.

File: scene/resources/animation.cpp [hunk 12]
```diff
@@ -4311,14 +4327,14 @@ void Animation::_blend_shape_track_optimize(int p_idx, real_t p_allowed_velocity
 	ERR_FAIL_INDEX(p_idx, tracks.size());
 	ERR_FAIL_COND(tracks[p_idx]->type != TYPE_BLEND_SHAPE);
 	BlendShapeTrack *bst = static_cast<BlendShapeTrack *>(tracks[p_idx]);
-
 	int i = 0;
+	bool is_nearest = tracks[p_idx]->interpolation == INTERPOLATION_NEAREST;
```
Comment (TokageItLab) [inline scene/resources/animation.cpp:4331]: Implementation should be matched with others.

**Review by TokageItLab — CHANGES_REQUESTED** [review]

**Review by TokageItLab — CHANGES_REQUESTED** [review]

**Review by TokageItLab — APPROVED** [review]
Alright now this is worked correctly, thanks. Please squash the commits into one to follow [PR workflow](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase).

**Comment by lazarosY** [comment]
> Alright now this is worked correctly, thanks. Please squash the commits into one to follow [PR workflow](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase).

Once again thank you very much for your valuable help. I do have a question though since I am new to this and have never used rebase before . Will using "git rebase -i upstream/master" on my branch be enough, or should I go about this by git "rebase -i HEAD~10" and picking only my first commit ?

**Comment by TokageItLab** [comment]
There are several ways to do this. FYI I mainly use one of the followings:

- Do `git commit --fixup` several times to reach the first commit
- Do `git reset --mixed` with root of the branch and force push the commit (be careful to don't use `git reset -hard` to prevent discarding your changes)

**Comment by lazarosY** [comment]
> There are several ways to do that. FYI I mainly use one of the followings:
> 
> * Do `git commit --fixup` several times to reach the first commit and finally force push to overwrite the first commit
> * Do `git reset --mixed` with root of the branch and force push the commit (be careful to don't use `git reset -hard` to prevent discarding your changes)

would you advice against doing it as so : git 
rebase -i HEAD~10 and picking only my first commit ?

**Comment by TokageItLab** [comment]
If you want to use interactive rebase, you need to set fixup the latest 9

**Comment by lazarosY** [comment]
> Alternatively, if that seems difficult to you, you can leave it to force push with maintainer authority. If you prefer to do so, please leave a comment indicating your intention to do so (to prevent conflicts in the work).

I think I got it right. Thank you very much for your help and swift responses!

**Review by TokageItLab — APPROVED** [review]

File: scene/resources/animation.h [hunk 13]
```diff
@@ -373,10 +373,10 @@ class Animation : public Resource {
...
-	bool _quaternion_track_optimize_key(const TKey<Quaternion> t0, const TKey<Quaternion> t1, const TKey<Quaternion> t2, real_t p_allowed_velocity_err, real_t p_allowed_angular_error, real_t p_allowed_precision_error);
+	bool _float_track_optimize_key(const TKey<float> t0, const TKey<float> t1, const TKey<float> t2, real_t p_allowed_velocity_err, real_t p_allowed_precision_error, bool is_nearest);
+	bool _vector2_track_optimize_key(const TKey<Vector2> t0, const TKey<Vector2> t1, const TKey<Vector2> t2, real_t p_allowed_velocity_err, real_t p_allowed_angular_error, real_t p_allowed_precision_error, bool is_nearest);
+	bool _vector3_track_optimize_key(const TKey<Vector3> t0, const TKey<Vector3> t1, const TKey<Vector3> t2, real_t p_allowed_velocity_err, real_t p_allowed_angular_error, real_t p_allowed_precision_error, bool is_nearest);
+	bool _quaternion_track_optimize_key(const TKey<Quaternion> t0, const TKey<Quaternion> t1, const TKey<Quaternion> t2, real_t p_allowed_velocity_err, real_t p_allowed_angular_error, real_t p_allowed_precision_error, bool is_nearest);
```
Comment (TokageItLab) [inline scene/resources/animation.h:379]:
```suggestion
	bool _float_track_optimize_key(const TKey<float> t0, const TKey<float> t1, const TKey<float> t2, real_t p_allowed_velocity_err, real_t p_allowed_precision_error, bool p_is_nearest);
	bool _vector2_track_optimize_key(const TKey<Vector2> t0, const TKey<Vector2> t1, const TKey<Vector2> t2, real_t p_allowed_velocity_err, real_t p_allowed_angular_error, real_t p_allowed_precision_error, bool p_is_nearest);
	bool _vector3_track_optimize_key(const TKey<Vector3> t0, const TKey<Vector3> t1, const TKey<Vector3> t2, real_t p_allowed_velocity_err, real_t p_allowed_angular_error, real_t p_allowed_precision_error, bool p_is_nearest);
	bool _quaternion_track_optimize_key(const TKey<Quaternion> t0, const TKey<Quaternion> t1, const TKey<Quaternion> t2, real_t p_allowed_velocity_err, real_t p_allowed_angular_error, real_t p_allowed_precision_error, bool p_is_nearest);
```

File: scene/resources/animation.cpp [hunk 14]
```diff
@@ -4105,14 +4105,17 @@ void Animation::clear() {
 	emit_changed();
 }
 
-bool Animation::_float_track_optimize_key(const TKey<float> t0, const TKey<float> t1, const TKey<float> t2, real_t p_allowed_velocity_err, real_t p_allowed_precision_error) {
+bool Animation::_float_track_optimize_key(const TKey<float> t0, const TKey<float> t1, const TKey<float> t2, real_t p_allowed_velocity_err, real_t p_allowed_precision_error, bool is_nearest) {
```
Comment (TokageItLab) [inline scene/resources/animation.cpp:4108]:
```suggestion
bool Animation::_float_track_optimize_key(const TKey<float> t0, const TKey<float> t1, const TKey<float> t2, real_t p_allowed_velocity_err, real_t p_allowed_precision_error, bool p_is_nearest) {
```

File: scene/resources/animation.cpp [hunk 15]
```diff
@@ -4105,14 +4105,17 @@ void Animation::clear() {
...
 	// Remove overlapping keys.
 	if (Math::is_equal_approx(t0.time, t1.time) || Math::is_equal_approx(t1.time, t2.time)) {
 		return true;
 	}
 	if (abs(t0.value - t1.value) < p_allowed_precision_error && abs(t1.value - t2.value) < p_allowed_precision_error) {
 		return true;
 	}
+	if (is_nearest) {
```
Comment (TokageItLab) [inline scene/resources/animation.cpp:4116]:
```suggestion
	if (p_is_nearest) {
```

File: scene/resources/animation.cpp [hunk 16]
```diff
@@ -4133,14 +4136,17 @@ bool Animation::_float_track_optimize_key(const TKey<float> t0, const TKey<float
 	return false;
 }
 
-bool Animation::_vector2_track_optimize_key(const TKey<Vector2> t0, const TKey<Vector2> t1, const TKey<Vector2> t2, real_t p_allowed_velocity_err, real_t p_allowed_angular_error, real_t p_allowed_precision_error) {
+bool Animation::_vector2_track_optimize_key(const TKey<Vector2> t0, const TKey<Vector2> t1, const TKey<Vector2> t2, real_t p_allowed_velocity_err, real_t p_allowed_angular_error, real_t p_allowed_precision_error, bool is_nearest) {
```
Comment (TokageItLab) [inline scene/resources/animation.cpp:4139]:
```suggestion
bool Animation::_vector2_track_optimize_key(const TKey<Vector2> t0, const TKey<Vector2> t1, const TKey<Vector2> t2, real_t p_allowed_velocity_err, real_t p_allowed_angular_error, real_t p_allowed_precision_error, bool p_is_nearest) {
```

File: scene/resources/animation.cpp [hunk 17]
```diff
@@ -4133,14 +4136,17 @@ bool Animation::_float_track_optimize_key(const TKey<float> t0, const TKey<float
...
 	// Remove overlapping keys.
 	if (Math::is_equal_approx(t0.time, t1.time) || Math::is_equal_approx(t1.time, t2.time)) {
 		return true;
 	}
 	if ((t0.value - t1.value).length() < p_allowed_precision_error && (t1.value - t2.value).length() < p_allowed_precision_error) {
 		return true;
 	}
+	if (is_nearest) {
```
Comment (TokageItLab) [inline scene/resources/animation.cpp:4147]:
```suggestion
	if (p_is_nearest) {
```

File: scene/resources/animation.cpp [hunk 18]
```diff
@@ -4164,14 +4170,18 @@ bool Animation::_vector2_track_optimize_key(const TKey<Vector2> t0, const TKey<V
 	return false;
 }
 
-bool Animation::_vector3_track_optimize_key(const TKey<Vector3> t0, const TKey<Vector3> t1, const TKey<Vector3> t2, real_t p_allowed_velocity_err, real_t p_allowed_angular_error, real_t p_allowed_precision_error) {
+bool Animation::_vector3_track_optimize_key(const TKey<Vector3> t0, const TKey<Vector3> t1, const TKey<Vector3> t2, real_t p_allowed_velocity_err, real_t p_allowed_angular_error, real_t p_allowed_precision_error, bool is_nearest) {
```
Comment (TokageItLab) [inline scene/resources/animation.cpp:4173]:
```suggestion
bool Animation::_vector3_track_optimize_key(const TKey<Vector3> t0, const TKey<Vector3> t1, const TKey<Vector3> t2, real_t p_allowed_velocity_err, real_t p_allowed_angular_error, real_t p_allowed_precision_error, bool p_is_nearest) {
```

File: scene/resources/animation.cpp [hunk 19]
```diff
@@ -4164,14 +4170,18 @@ bool Animation::_vector2_track_optimize_key(const TKey<Vector2> t0, const TKey<V
...
 	// Remove overlapping keys.
 	if (Math::is_equal_approx(t0.time, t1.time) || Math::is_equal_approx(t1.time, t2.time)) {
 		return true;
 	}
 	if ((t0.value - t1.value).length() < p_allowed_precision_error && (t1.value - t2.value).length() < p_allowed_precision_error) {
 		return true;
 	}
+	if (is_nearest) {
```
Comment (TokageItLab) [inline scene/resources/animation.cpp:4181]:
```suggestion
	if (p_is_nearest) {
```

File: scene/resources/animation.cpp [hunk 20]
```diff
@@ -4195,14 +4205,17 @@ bool Animation::_vector3_track_optimize_key(const TKey<Vector3> t0, const TKey<V
 	return false;
 }
 
-bool Animation::_quaternion_track_optimize_key(const TKey<Quaternion> t0, const TKey<Quaternion> t1, const TKey<Quaternion> t2, real_t p_allowed_velocity_err, real_t p_allowed_angular_error, real_t p_allowed_precision_error) {
+bool Animation::_quaternion_track_optimize_key(const TKey<Quaternion> t0, const TKey<Quaternion> t1, const TKey<Quaternion> t2, real_t p_allowed_velocity_err, real_t p_allowed_angular_error, real_t p_allowed_precision_error, bool is_nearest) {
```
Comment (TokageItLab) [inline scene/resources/animation.cpp:4208]:
```suggestion
bool Animation::_quaternion_track_optimize_key(const TKey<Quaternion> t0, const TKey<Quaternion> t1, const TKey<Quaternion> t2, real_t p_allowed_velocity_err, real_t p_allowed_angular_error, real_t p_allowed_precision_error, bool p_is_nearest) {
```

File: scene/resources/animation.cpp [hunk 21]
```diff
@@ -4195,14 +4205,17 @@ bool Animation::_vector3_track_optimize_key(const TKey<Vector3> t0, const TKey<V
...
 	// Remove overlapping keys.
 	if (Math::is_equal_approx(t0.time, t1.time) || Math::is_equal_approx(t1.time, t2.time)) {
 		return true;
 	}
 	if ((t0.value - t1.value).length() < p_allowed_precision_error && (t1.value - t2.value).length() < p_allowed_precision_error) {
 		return true;
 	}
+	if (is_nearest) {
```
Comment (TokageItLab) [inline scene/resources/animation.cpp:4216]:
```suggestion
	if (p_is_nearest) {
```

**Review by TokageItLab — CHANGES_REQUESTED** [review]
Oops, sorry. I missed the change in argument names. `p_` is a prefix to indicate that it is an argument parameter, so it is required here. Conversely, do not prefix local variables with `p_`.

**Comment by lazarosY** [comment]
> Oops, sorry. I missed the change in argument names. `p_` is a prefix to indicate that it is an argument parameter, so it is required here. Conversely, do not prefix local variables with `p_`.

All good, I imagined that this might have been the case, I did make the necessary changes. Rebase seems to be sucking in additional changes that I haven't made so I will just leave it at 2 commits for now.

**Comment by lazarosY** [comment]
> Please try to not push so many times in a row, if you are adding suggestions please use batches, otherwise please try to be more deliberate with your pushing. Right now as you are a first-time contributor it doesn't run CI until someone approves it but otherwise it'd run CI very unnecessarily (over 18 times in just 10 hours)

I am very sorry, you're right it's just that this was my first time doing a lot of this so I was a little anxious and there were many unforeseen circumstances that I hadn't accounted for due to my inexperience. I will be more careful and try to be more frugal when it comes to pushing changes.

**Comment by TokageItLab** [comment]
> I haven't made so I will just leave it at 2 commits for now.

In order to merge, there must be only one commit, so you needs squash it.

**Comment by lazarosY** [comment]
please don't have any workflows run I've messed up.

**Comment by lazarosY** [comment]
I am terrible sorry for the long wait but I kept on tripping over myself. Never the less, I have implemented the changes requested and have squashed the commits into 1. I can't thank you enough for your patience, understanding and help.

**Review by TokageItLab — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
