### PR TITLE
Check if resource exists before loading

### LINKED ISSUE #17729: load() produces generic error for incorrect paths
**Godot version:**
Recent build from master: 4b00cc9

**OS/device including version:**
Windows 7

**Issue description:**
If a call to `load()` is passed a path that doesn't point to file then a generic "No loader found for resource" error is produced.

However if we change the loader so  it is able to detect a file not found situation and produce a more specific message it will help developers identify when they have incorrect resource paths.

This is probably more relevant now that C Sharp users are using external editors.

**Steps to reproduce:**

If I run this code:

```
var dummy = load("res://no/resource/at/this/path.png")
````

This error is displayed in the debugger panel:
```
0:00:02:0174 - No loader found for resource: res://no/resource/at/this/path.png
----------
Type:Error
Description: No loader found for resource: res://no/resource/at/this/path.png
Time: 0:00:02:0174
C Error: Method/Function Failed, returning: RES()
C Source: core\io\resource_loader.cpp:186
C Function: ResourceLoader::_load
```

### PR DESCRIPTION
**Pull request by KoBeWi**
Closes #17729
(not sure if doesn't have unwanted side-effects)

### CODE REVIEW

**Comment by reduz** [comment]
No, this is a terrible idea, the remap system may remap resources that were removed on export so this will break in plenty of cases.

I suggest doing this at the time of printing the error, and only if tools is enabled.

**Comment by KoBeWi** [comment]
Changed.

File: core/io/resource_loader.cpp [hunk 1]
```diff
@@ -277,6 +277,11 @@ RES ResourceLoader::_load(const String &p_path, const String &p_original_path, c
 
 	ERR_FAIL_COND_V_MSG(found, RES(), "Failed loading resource: " + p_path + ".");
 
+#ifdef TOOLS_ENABLED
+	FileAccessRef file_check = FileAccess::create(FileAccess::ACCESS_RESOURCES);
+	ERR_FAIL_COND_V_MSG(!file_check->file_exists(p_path), RES(), "Resource file not found: " + p_path + ".");
+#endif
```
Comment (akien-mga) [inline core/io/resource_loader.cpp]: Shouldn't this come before the `found` error?
IIUC, `found` will be true if a valid loader was found for the given path (based on the extension), so if you try to load `res://doesnt_exist.png`, I guess it will show the first error and not the one about the file actually not existing.

Comment (KoBeWi) [reply core/io/resource_loader.cpp]: Nope:
```
_load: No loader found for resource: res://test.png.
```
The first error is for a case when the file exists, but loader failed to load it (e.g. corrupted image).

**Comment by akien-mga** [comment]
Thanks!
