### PR TITLE
Fix crash with String::copy_from with NULL string parameter

### LINKED ISSUE #9358: Editor crashed while open script with external editor
**Operating system or device - Godot version:**
Godot 3.0 with latest commit

**Issue description:**

Editor crashed while open GDScript file  with external editor.

**Steps to reproduce:**
* Fill the external code editor path like `/usr/sbin/code`.
* Leave the flags input as empty.
* Open a gdscript file in godot editor.
* The editor crashed

**Link to minimal example project:**

### PR DESCRIPTION
**Pull request by Geequlim**
Fix #9358

### CODE REVIEW

**Comment by Geequlim** [comment]
#9358 Still exists. Don't merge until I find out the reason.

**Comment by Geequlim** [comment]
This PR should fix the problem.
Before this commit the engine will crash with script below script
```
"".format({"a": 1})
```
This should be fix with this PR.

File: core/ustring.cpp [hunk 1]
```diff
@@ -120,9 +120,13 @@ void String::copy_from(const char *p_cstr) {
 void String::copy_from(const CharType *p_cstr, int p_clip_to) {
 
 	int len = 0;
-	const CharType *ptr = p_cstr;
-	while (*(ptr++) != 0)
-		len++;
+
+	if (p_cstr) {
```
Comment (akien-mga) [inline core/ustring.cpp]: Maybe it would be better to move the test at the top and add an early `resize(0); return;`? (+ maybe an error message?)

Comment (Geequlim) [inline core/ustring.cpp]: Look at the code below:
```c++
int len = 0;

if (p_cstr) {

    const CharType *ptr = p_cstr;
    while (*(ptr++) != 0)
        len++;
}

if (p_clip_to >= 0 && len > p_clip_to)
    len = p_clip_to;

if (len == 0) {

    resize(0);
    return;
}
```
The variable `len` will keep `0` if the value of `p_cstr` is `NULL`. So we don't need to do that :)

Comment (akien-mga) [inline core/ustring.cpp]: We don't *need*, but I said it would be better. What if we added 100 LOCs before that `if (len == 0)` test? :) Functionally, if `p_cstr` is NULL, the method should abort right away IMO, that's cleaner.

**Comment by Geequlim** [comment]
@akien-mga The null checking is move to the top functions. Thanks for your advice.
I don't think we should abort the copy action as
```c++
String s = "Hello"
s = '\0'  // The copy_from is called by `String::operator=(const CharType *p_str)`
```
If we abort the copy_from action the s will keep value `Hello`.

**Review by akien-mga — APPROVED** [review]

**Comment by Geequlim** [comment]
Is anothor one for 2.1 branch required?

**Comment by akien-mga** [comment]
It's ok, I'll cherry-pick that one.
