### PR TITLE
SDFGI: Fix crash if `update_data` is nullptr

### LINKED ISSUE #94534: Crash when transitioning between scenes with SDFGI enabled and disabled respectively
### Tested versions

Godot Engine v4.3.beta3.official (82cedc83c9069125207c128f9a07ce3d82c317cc)

### System information

Godot v4.3.beta3 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.2647) - 12th Gen Intel(R) Core(TM) i7-12700K (20 Threads)

### Issue description

When transitioning from a scene with SDFGI enabled to one without it, the game stalls and crashes.

### Steps to reproduce

1. Scene "scene_a" with a WorldEnvironment node with SDFGI enabled
2. Scene "scene_b" with a WorldEnvironment node with SDFGI disabled (default) _AND_ Background Mode set to Canvas
3. Change scene from "scene_a" to "scene_b"

### Minimal reproduction project (MRP)

Run the MRP and press "ui_accept" (Enter or Space) to crash.
[sdfgi_crash.zip](https://github.com/user-attachments/files/16311858/sdfgi_crash.zip)

### PR DESCRIPTION
**Pull request by Garteal**
Fixes #94534

### CODE REVIEW

File: servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp [hunk 1]
```diff
@@ -1142,7 +1142,7 @@ void RenderForwardClustered::_update_sdfgi(RenderDataRD *p_render_data) {
 		for (int i = 0; i < p_render_data->render_sdfgi_region_count; i++) {
 			sdfgi->render_region(rb, p_render_data->render_sdfgi_regions[i].region, p_render_data->render_sdfgi_regions[i].instances, exposure_normalization);
 		}
-		if (p_render_data->sdfgi_update_data->update_static) {
+		if (p_render_data->sdfgi_update_data != nullptr && p_render_data->sdfgi_update_data->update_static) {
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:1145]: I would move the condition `p_render_data->sdfgi_update_data != nullptr` to the top of this function and early out if `p_render_data->sdfgi_update_data == nullptr` that way we can avoid the cost of the entire function.

File: servers/rendering/renderer_rd/environment/gi.cpp [hunk 2]
```diff
@@ -1866,6 +1866,10 @@ void GI::SDFGI::pre_process_gi(const Transform3D &p_transform, RenderDataRD *p_r
 
 	RD::get_singleton()->buffer_update(gi->sdfgi_ubo, 0, sizeof(SDFGIData), &sdfgi_data);
 
+	if (p_render_data->sdfgi_update_data == nullptr) {
+		return;
+	}
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/environment/gi.cpp:1871]: I would do this check at the top of the function. We can't use SDFGI when `sdfgi_update_data` is a nullptr anyway, so we might as well skip the whole function

**Review by clayjohn — COMMENTED** [review]
Great work tracking this down. 

It seems that  `sdfgi_update_data` is often nullptr when drawing with canvas background enabled. In those cases, we can't use SDFGI anyway, so as much of the work from SDFGI should be skipped as possible

File: servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp (hunk 1 above)
Comment (Garteal) [reply servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp]: Done and I agree! I chose to add it there for safety reasons to not introduce unwanted side-effects since I'm not too familiar with the codebase yet. 😃

Comment (clayjohn) [reply servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp]: I figured! I appreciate the caution :)

**Review by clayjohn — APPROVED** [review]
Looks great! Thank you for your quick response and for catching this one

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected.

**Comment by akien-mga** [comment]
Thanks!
