### PR TITLE
Fix crash when GraphNode wasn't a child of a Control

### LINKED ISSUE #5761: Clicking GraphNode Crashes Game
**Operating system or device - Godot version:**
Ubuntu MATE 15.10, Godot 2.1-beta

**Issue description** (what happened, and what was expected):
I create a Node, add a GraphNode to it, save my scene, hit play. When I click on the GraphNode in the game it crashes. No debug information or anything on crash either.

**Steps to reproduce:**
Create a GraphNode, play game, and click on the GraphNode.

**Link to minimal example project** (optional but very welcome):
[Test2.zip](https://github.com/godotengine/godot/files/368190/Test2.zip)

### PR DESCRIPTION
**Pull request by 29jm**
Fixes #5761.

### CODE REVIEW

File: scene/gui/graph_node.cpp [hunk 1]
```diff
@@ -559,7 +559,15 @@ Color GraphNode::get_connection_output_color(int p_idx) {
 void GraphNode::_input_event(const InputEvent& p_ev) {
 
 	if (p_ev.type==InputEvent::MOUSE_BUTTON) {
-		get_parent_control()->grab_focus();
+
+		ERR_EXPLAIN("GraphNode must be the child of a GraphEdit node.");
+		ERR_FAIL_COND(get_parent_control() == NULL);
+
+		if (get_parent_control())
```
Comment (akien-mga) [inline scene/gui/graph_node.cpp]: As far as I understand ``ERR_FAIL_COND`` already returns if its test is true, so you don't need the `if/else` afterwards.

Comment (29jm) [inline scene/gui/graph_node.cpp]: Thanks, you're right! I'll rebase

**Comment by akien-mga** [comment]
Tested, it does the trick. Interestingly, the input event is received twice (might be echo from the mouse click, though I tried to click super fast :p).
