### PR TITLE
Move TileMap layers to their own class

### LINKED ISSUE #77477: Tilemaps on ParallaxLayers are very slow
### Godot version

4.0.stable

### System information

Ubuntu, AMD Ryzen 5 2600, GTX 1650, Vulkan

### Issue description

When putting Tilemaps with lots of tiles on Parallaxlayers, it massively slows down Godot from roughly around 600fps to 20fps. This happens whether or not the parallaxlayers are invisible, have lightoccluder information, or have collision. It seems just the process of having lots of tiles exist slows it down. 

### Steps to reproduce

Open the minimal project and convert the 2 parallaxlayers from parallaxlayers to basic node2ds and watch the FPS massively increase.

### Minimal reproduction project

[ParallaxTilemap.zip](https://github.com/godotengine/godot/files/11566812/ParallaxTilemap.zip)

### LINKED ISSUE #79553: TileMap Memory Leak caused by switching collidable tiles in cells
### Godot version

4.1.stable

### System information

Godot v4.1.stable - elementary OS 7 Horus 7 (Ubuntu 22.04) - Vulkan (Mobile) - dedicated AMD Radeon RX 6600 (RADV NAVI23) () - Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 Threads)

### Issue description

Tilemap has a memory leak where if you repeatedly change the tile (that has collidable physics) of cells, the static memory (shown in the debugger) increases and stays there. This only happens if you have a physics layer in the Tileset and one of the tiles is collidable.

Also the memory usage is extremely high even when generating the map once. A 1000x1000 tiles map uses 1.4 GB of memory!

Workaround is simple. Simply clear the tilemap with `clear()` before you change the map.

### Steps to reproduce

1. Create a TileMap node
2. Create a TileSet containing two tiles on the atlas coordinates `(0, 0)` and `(1, 0)`
3. Create a Physics Layer in the TileSet and make one of the tiles fully collidable
4. Attach a script to the TileMap
5. Set the script to this
```
extends TileMap

func _process(delta):
	if Input.is_key_pressed(KEY_SPACE):
		for i in range(5000):
			set_cell(0, Vector2i(i, 0), 0, Vector2i(randi_range(0, 1), 0))
```
6. Run the scene
7. Go into "Debugger" tab in the editor while the scene is running
8. Press the "Monitors" tab press and observe the "Static" memory
9. Now hold down the space bar and observe the static memory climbing but never coming down
10. To workaround the problem simply add `clear()` before the loop like this:
```
extends TileMap

func _process(delta):
	if Input.is_key_pressed(KEY_SPACE):
		clear()
		for i in range(5000):
			set_cell(0, Vector2i(i, 0), 0, Vector2i(randi_range(0, 1), 0))
```

### Minimal reproduction project

[tilemapmemoryleak.zip](https://github.com/godotengine/godot/files/12064640/tilemapmemoryleak.zip)

### PR DESCRIPTION
**Pull request by groud**
Sorry for the huge PR, but it, hopefully, does not change the TileMap behavior. It does the following:
- Move layer data and methods to a TileMapLayer class. This helps keeping things more independent from one layer to another. It's kind of needed to cleanly improve performances on following up PRs.
- Make all layer-indexing functions work with negative indices.
- Likely fix a bug with navigation.
- Might improve performances significantly on some cases as I reduced the number of calls to `canvas_item_set_draw_index`. It might create bugs too as I am not 100% of the change. Though it looks like it worked well on my test project.

Might fix: #77477, to be tested.
*Bugsquad edit:* Fixes #79553

### CODE REVIEW

**Comment by KoBeWi** [comment]
Tested with my project. Overall seems to work fine and layer modifications are noticeably faster, but something wrong is happening with physics.

I have a condition like this: `floor_collision.get_collider().is_in_group(&"wallrun")` and it results in an error that `is_in_group()` method is not found in RefCounted. Then I have this code:
```GDscript

**Comment by KoBeWi** [comment]
Tested with my project. Overall seems to work fine and layer modifications are noticeably faster, but something wrong is happening with physics.

I have a condition like this: `floor_collision.get_collider().is_in_group(&"wallrun")` and it results in an error that `is_in_group()` method is not found in RefCounted. Then I have this code:
```GDscript
for body in collider.get_overlapping_bodies():
	if body.is_in_group(&"powable"):
		body.do_pow(down)
		powed_any = true
```
And it results in outright crash:
```
[0] HashMap<StringName,Node::GroupData,HashMapHasherDefault,HashMapComparatorDefault<StringName>,DefaultTypedAllocator<HashMapElement<StringName,Node::GroupData> > >::_lookup_pos (C:\godot_source\core\templates\hash_map.h:104)
[1] HashMap<StringName,Node::GroupData,HashMapHasherDefault,HashMapComparatorDefault<StringName>,DefaultTypedAllocator<HashMapElement<StringName,Node::GroupData> > >::has (C:\godot_source\core\templates\hash_map.h:311)
[2] Node::is_in_group (C:\godot_source\scene\main\node.cpp:2077)
[3] call_with_ptr_args_retc_helper<Node,bool,StringName const &,0> (C:\godot_source\core\variant\binder_common.h:339)
[4] call_with_ptr_args_retc<Node,bool,StringName const &> (C:\godot_source\core\variant\binder_common.h:588)
[5] MethodBindTRC<Node,bool,StringName const &>::ptrcall (C:\godot_source\core\object\method_bind.h:598)
[6] GDScriptFunction::call (C:\godot_source\modules\gdscript\gdscript_vm.cpp:1943)
[7] GDScriptInstance::callp (C:\godot_source\modules\gdscript\gdscript.cpp:1791)
[8] Object::callp (C:\godot_source\core\object\object.cpp:717)
[9] Variant::callp (C:\godot_source\core\variant\variant_call.cpp:1174)
[10] GDScriptFunction::call (C:\godot_source\modules\gdscript\gdscript_vm.cpp:1662)
[11] GDScriptInstance::callp (C:\godot_source\modules\gdscript\gdscript.cpp:1791)
[12] Object::callp (C:\godot_source\core\object\object.cpp:717)
[13] Variant::callp (C:\godot_source\core\variant\variant_call.cpp:1174)
[14] GDScriptFunction::call (C:\godot_source\modules\gdscript\gdscript_vm.cpp:1662)
[15] GDScriptInstance::callp (C:\godot_source\modules\gdscript\gdscript.cpp:1791)
[16] Node::_gdvirtual__physics_process_call<0> (C:\godot_source\scene\main\node.h:319)
[17] Node::_notification (C:\godot_source\scene\main\node.cpp:61)
[18] Node::_notificationv (C:\godot_source\scene\main\node.h:49)
[19] CanvasItem::_notificationv (C:\godot_source\scene\main\canvas_item.h:45)
[20] Node2D::_notificationv (C:\godot_source\scene\2d\node_2d.h:37)
[21] CollisionObject2D::_notificationv (C:\godot_source\scene\2d\collision_object_2d.h:40)
[22] PhysicsBody2D::_notificationv (C:\godot_source\scene\2d\physics_body_2d.h:42)
[23] CharacterBody2D::_notificationv (C:\godot_source\scene\2d\physics_body_2d.h:327)
[24] Object::notification (C:\godot_source\core\object\object.cpp:798)
[25] SceneTree::_process_group (C:\godot_source\scene\main\scene_tree.cpp:934)
[26] SceneTree::_process (C:\godot_source\scene\main\scene_tree.cpp:1022)
[27] SceneTree::physics_process (C:\godot_source\scene\main\scene_tree.cpp:468)
[28] Main::iteration (C:\godot_source\main\main.cpp:3382)
[29] OS_Windows::run (C:\godot_source\platform\windows\os_windows.cpp:1479)
[30] widechar_main (C:\godot_source\platform\windows\godot_windows.cpp:182)
[31] _main (C:\godot_source\platform\windows\godot_windows.cpp:204)
[32] main (C:\godot_source\platform\windows\godot_windows.cpp:218)
[33] WinMain (C:\godot_source\platform\windows\godot_windows.cpp:232)
[34] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[35] <couldn't map PC to fn name>
```
In both cases I'm accessing a TileMap collider, which seems to be RefCounted. Did the collision change from TileMap node to TileMapLayer refcounted?

**Comment by groud** [comment]
> In both cases I'm accessing a TileMap collider, which seems to be RefCounted. Did the collision change from TileMap node to TileMapLayer refcounted?

Yes, but the TileMapLayer is refcounted too, so that should not be a problem ? 

I am not really sure how to reproduce the bug though, seems like `get_coords_for_body_rid()` and `get_layer_for_body_rid()` work fine for me. :thinking:

**Comment by groud** [comment]
Ah nevermind, found the issue! That was an oversight with a call to `get_instance_id()` instead of `tile_map_node->get_instance_id()`.

Can you try again ?

**Comment by KoBeWi** [comment]
The first error comes from KinematicCollision2D (CharacterBody2D colliding with TileMap), the other from Area2D overlapping TileMap. Previously the returned collider was the TileMap.

It's not really a problem, except it kind of breaks compatibility and can cause a crash in a previously working code.

**Comment by KoBeWi** [comment]
I can't test right now, will do tomorrow.

**Comment by KoBeWi** [comment]
The error is fixed.

File: scene/2d/tile_map.h [hunk 1]
```diff
@@ -37,6 +37,58 @@
 
 class TileSetAtlasSource;
 
+class TerrainConstraint {
+private:
+	const TileMap *tile_map;
```
Comment (KoBeWi) [inline scene/2d/tile_map.h:42]:
```suggestion
	const TileMap *tile_map = nullptr;
```

File: scene/2d/tile_map.h [hunk 2]
```diff
@@ -108,62 +157,170 @@ struct TileMapQuadrant {
...
-
-	public:
-		bool operator<(const TerrainConstraint &p_other) const {
-			if (base_cell_coords == p_other.base_cell_coords) {
-				return bit < p_other.bit;
-			}
-			return base_cell_coords < p_other.base_cell_coords;
-		}
+	enum DataFormat {
+		FORMAT_1 = 0,
```
Comment (KoBeWi) [inline scene/2d/tile_map.h:163]:
```suggestion
		FORMAT_1,
```
This is default.

File: scene/2d/tile_map.h [hunk 3]
```diff
@@ -108,62 +157,170 @@ struct TileMapQuadrant {
...
+		FORMAT_2,
+		FORMAT_3
```
Comment (KoBeWi) [inline scene/2d/tile_map.h:165]:
```suggestion
		FORMAT_3,
```

File: scene/2d/tile_map.h [hunk 4]
```diff
@@ -108,62 +157,170 @@ struct TileMapQuadrant {
...
+	bool enabled = true;
+	Color modulate = Color(1, 1, 1, 1);
+	bool y_sort_enabled = false;
+	int y_sort_origin = 0;
+	int z_index = 0;
+	RID navigation_map;
+	bool uses_world_navigation_map = false;
+
+	// Internal
+	TileMap *tile_map_node;
```
Comment (KoBeWi) [inline scene/2d/tile_map.h:180]:
```suggestion
	TileMap *tile_map_node = nullptr;
```

File: scene/2d/tile_map.h [hunk 5]
```diff
@@ -108,62 +157,170 @@ struct TileMapQuadrant {
...
-		int get_terrain() const {
-			return terrain;
-		}
+	// Runtime tile data
+	void _build_runtime_update_tile_data(SelfList<TileMapQuadrant>::List &r_dirty_quadrant_list);
 
-		void set_priority(int p_priority) {
-			priority = p_priority;
-		}
+	// Terrains.
```
Comment (KoBeWi) [inline scene/2d/tile_map.h:229]: Either all these labels should end with period or none.
We usually add the period, but the comments here are not sentences, so not sure.

File: scene/2d/tile_map.h [hunk 6]
```diff
@@ -108,62 +157,170 @@ struct TileMapQuadrant {
...
 
-		TerrainConstraint(const TileMap *p_tile_map, const Vector2i &p_position, int p_terrain); // For the center terrain bit
-		TerrainConstraint(const TileMap *p_tile_map, const Vector2i &p_position, const TileSet::CellNeighbor &p_bit, int p_terrain); // For peering bits
-		TerrainConstraint(){};
-	};
+	// Rect caching.
+	Rect2 get_rect(bool &r_changed) const;
+
+	// Terrains.
+	HashMap<Vector2i, TileSet::TerrainsPattern> terrain_fill_constraints(const Vector<Vector2i> &p_to_replace, int p_terrain_set, const RBSet<TerrainConstraint> &p_constraints); // Not exposed.
```
Comment (KoBeWi) [inline scene/2d/tile_map.h:243]:
```suggestion
	// Terrains (not exposed).
	HashMap<Vector2i, TileSet::TerrainsPattern> terrain_fill_constraints(const Vector<Vector2i> &p_to_replace, int p_terrain_set, const RBSet<TerrainConstraint> &p_constraints);
```
If anything...
Not sure how useful is saying that something is not exposed though. It can be checked quite easily.

**Comment by KoBeWi** [comment]
Actually, what is DataFormat enum for? I assumed it's some compatibility thing, but not sure.

File: scene/2d/tile_map.cpp [hunk 7]
```diff
@@ -38,1220 +38,757 @@
 #include "servers/navigation_server_3d.h"
 #endif // DEBUG_ENABLED
 
-HashMap<Vector2i, TileSet::CellNeighbor> TileMap::TerrainConstraint::get_overlapping_coords_and_peering_bits() const {
-	HashMap<Vector2i, TileSet::CellNeighbor> output;
+Vector2i TileMapLayer::_coords_to_quadrant_coords(const Vector2i &p_coords) const {
+	int quad_size = get_effective_quadrant_size();
 
-	ERR_FAIL_COND_V(is_center_bit(), output);
+	// Rounding down, instead of simply rounding towards zero (truncating)
```
Comment (KoBeWi) [inline scene/2d/tile_map.cpp:44]:
```suggestion
	// Rounding down, instead of simply rounding towards zero (truncating).
```

File: scene/2d/tile_map.cpp [hunk 8]
```diff
@@ -38,1220 +38,757 @@
...
-					bit = 5;
-					base_cell_coords = p_tile_map->get_neighbor_cell(p_position, TileSet::CELL_NEIGHBOR_TOP_RIGHT_SIDE);
-					break;
-				default:
-					ERR_FAIL();
-					break;
-			}
+		/*Transform2D xform;
+		xform.set_origin(Vector2(0, p_layer));
+		rs->canvas_item_set_transform(ci, xform);*/
```
Comment (KoBeWi) [inline scene/2d/tile_map.cpp:115]: Any reason to comment out this instead of removing?

File: scene/2d/tile_map.cpp [hunk 9]
```diff
@@ -1436,1690 +885,2468 @@ void TileMap::_rendering_draw_quadrant_debug(TileMapQuadrant *p_quadrant) {
...
+		used_rect_cache_dirty = false;
+	}
+
+	return used_rect_cache;
+}
+
+void TileMapLayer::clear() {
+	// Remove all tiles.
+	clear_internals();
+	tile_map.clear();
```
Comment (KoBeWi) [inline scene/2d/tile_map.cpp:2156]: Why clearing layer clears TileMap?
Also why are internals recreated?

File: scene/2d/tile_map.cpp [hunk 10]
```diff
@@ -3172,7 +3404,7 @@ bool TileMap::_set(const StringName &p_name, const Variant &p_value) {
 bool TileMap::_get(const StringName &p_name, Variant &r_ret) const {
 	Vector<String> components = String(p_name).split("/", true, 2);
 	if (p_name == "format") {
-		r_ret = FORMAT_3; // When saving, always save highest format
+		r_ret = TileMapLayer::FORMAT_3; // When saving, always save highest format
```
Comment (KoBeWi) [inline scene/2d/tile_map.cpp:3407]: This could be dehardcoded. E.g. with something like `FORMAT_MAX - 1`.

File: scene/2d/tile_map.cpp [hunk 11]
```diff
@@ -1436,1690 +885,2468 @@ void TileMap::_rendering_draw_quadrant_debug(TileMapQuadrant *p_quadrant) {
...
+/////////////////////////////////////////////////////////////////////
 
-		bool transpose = tile_data->get_transpose();
-		if (transpose) {
-			dest_rect.position = (p_position - Vector2(dest_rect.size.y, dest_rect.size.x) / 2 - tile_offset);
-		} else {
-			dest_rect.position = (p_position - dest_rect.size / 2 - tile_offset);
-		}
+void TileMapLayer::_build_runtime_update_tile_data(SelfList<TileMapQuadrant>::List &r_dirty_quadrant_list) {
+	if (tile_map_node->GDVIRTUAL_IS_OVERRIDDEN(_use_tile_data_runtime_update) && tile_map_node->GDVIRTUAL_IS_OVERRIDDEN(_tile_data_runtime_update)) {
```
Comment (KoBeWi) [inline scene/2d/tile_map.cpp:891]: This can be changed into early return.

File: scene/2d/tile_map.cpp [hunk 12]
```diff
@@ -1436,1690 +885,2468 @@ void TileMap::_rendering_draw_quadrant_debug(TileMapQuadrant *p_quadrant) {
...
+	recreate_internals();
+	used_rect_cache_dirty = true;
+}
+
+void TileMapLayer::set_name(String p_name) {
+	if (name == p_name) {
+		return;
+	}
+	name = p_name;
+	tile_map_node->emit_signal(SNAME("changed"));
```
Comment (KoBeWi) [inline scene/2d/tile_map.cpp:2166]: You could replace it with `changed` constant from CoreStringNames.

File: scene/2d/tile_map.cpp (hunk 9 above)
Comment (groud) [reply scene/2d/tile_map.cpp:2156]: > Why clearing layer clears TileMap?

It only clears the current layer, not the whole tile map. `tile_map` is local to the layer, `tile_map_node` is the pointer to the TileMap node.

> Also why are internals recreated?

After internals are cleared they should always be recreated. Basically it recreates the layer parent CanvasItems and things like that. This should be changed in a follow up PR anyway. For now I tried not to change too many things.

File: scene/2d/tile_map.h (hunk 2 above)
Comment (groud) [reply scene/2d/tile_map.h:163]: I think I'd prefer to keep it that way. Since this enum is serialized I thinks it's a bit better to be explicit about the starting value (especially since `FORMAT_1 = 0` and not `FORMAT_1 = 1`.

**Review by KoBeWi — APPROVED** [review]
I did not review the whole code, because GitHub is super slow with this many changes. Though I assume it's mostly a copy paste of the previous code.

I didn't spot any regressions from testing with my project, but I don't use all TileMap features. Most notably I didn't test terrains and navigation.

File: scene/2d/tile_map.cpp [hunk 13]
```diff
@@ -4232,13 +4395,20 @@ TileMap::TileMap() {
...
 	if (tile_set.is_valid()) {
-		tile_set->disconnect("changed", callable_mp(this, &TileMap::_tile_set_changed));
+		tile_set->disconnect(CoreStringNames::get_singleton()->changed, callable_mp(this, &TileMap::_tile_set_changed));
 	}
 
 	_clear_internals();
 }
+
+#undef TILEMAP_CALL_FOR_LAYER
+#undef TILEMAP_CALL_FOR_LAYER_V
```
Comment (YuriSizov) [inline scene/2d/tile_map.cpp:4414]: Missing new line at the end of the file.

**Review by YuriSizov — APPROVED** [review]
Approving in principle, the nitpick needs fixing.

This also breaks compatibility with GDExtension by making `get_used_rect` const. This needs to be handled gracefully.

**Comment by YuriSizov** [comment]
> Does it though ?

It does at least in the sense that we include const-ness in the hash calculation. So you get a hash mismatch, which I think means that ABI compatibility is going to be broken for that method.

File: scene/2d/tile_map.compat.inc [hunk 14]
```diff
@@ -0,0 +1,45 @@
...
+
+Rect2i TileMap::_get_used_rect_bind_compat_78328() {
+	return get_used_rect();
+}
+
+void TileMap::_bind_compatibility_methods() {
+	ClassDB::bind_compatibility_method(D_METHOD("get_used_rect"), &TileMap::_get_used_rect_bind_compat_78328);
+}
+
+#endif
```
Comment (YuriSizov) [inline scene/2d/tile_map.compat.inc:45]: You're missing a new line here :)

**Review by YuriSizov — APPROVED** [review]
The new compat changes seem correct 👍

**Comment by YuriSizov** [comment]
Thanks! _Now the real work begins_ 🙃
