### PR TITLE
Fix crash when extending inner class in GDScript

### LINKED ISSUE #59508: GDScript 2.0: Can't extend inner class
### Godot version

v4.0.alpha5.official [d7d528c15]

### System information

Windows 10

### Issue description

I coding a built-in GDScript like this:

```
extends Node2D

class A:
	func test():
		prints("A test")

class B extends A: # error here
	func test():
		prints("B test")

func _ready():
	var b = B.new()
	b.test()
```

when I run this scene, App will freeze a moment then crash, and print nothing.
If I change code like this:
```
extends Node2D

class A:
	func test():
		prints("A test")

class B:
	func test():
		prints("B test")

func _ready():
	var b = B.new()
	b.test()
```
There was no error.

### Steps to reproduce

Please run the reproduction project

### Minimal reproduction project

[InnerClsExtendsTest.zip](https://github.com/godotengine/godot/files/8348601/InnerClsExtendsTest.zip)

### PR DESCRIPTION
**Pull request by Chaosus**
Fix https://github.com/godotengine/godot/issues/59508

### CODE REVIEW

File: modules/gdscript/gdscript_compiler.cpp [hunk 1]
```diff
@@ -131,16 +135,39 @@ GDScriptDataType GDScriptCompiler::_gdtype_from_datatype(const GDScriptParser::D
...
 					}
-					result.kind = GDScriptDataType::GDSCRIPT;
 					result.script_type = script.ptr();
 					result.native_type = script->get_instance_base_type();
-					result.builtin_type = p_datatype.builtin_type;
 				} else {
-					result.kind = GDScriptDataType::GDSCRIPT;
-					result.script_type_ref = GDScriptCache::get_shallow_script(p_datatype.script_path, main_script->path);
+					PackedStringArray classes = class_type->fqcn.split("::");
+					if (classes.size() > 0) {
```
Comment (fire-forge) [inline modules/gdscript/gdscript_compiler.cpp:142]:
```suggestion
					if (!classes.is_empty()) {
```

File: modules/gdscript/gdscript_compiler.cpp [hunk 2]
```diff
@@ -131,16 +135,39 @@ GDScriptDataType GDScriptCompiler::_gdtype_from_datatype(const GDScriptParser::D
 						script = script->subclasses[names.back()->get()];
 						names.pop_back();
 					}
-					result.kind = GDScriptDataType::GDSCRIPT;
 					result.script_type = script.ptr();
 					result.native_type = script->get_instance_base_type();
-					result.builtin_type = p_datatype.builtin_type;
 				} else {
```
Comment (akien-mga) [inline modules/gdscript/gdscript_compiler.cpp:140]: To make the code easier to understand, it could be good to add a short comment that explains what the `else` case is here (i.e. what are we working on if not "Local class." as above).

**Review by vnen — APPROVED** [review]
LGTM. Could add some comments as Akien suggested.

**Comment by akien-mga** [comment]
After further discussion we realized that it's intended that
```
extends Node

class A:
	func _init():
		print("A")

class B extends A:
	func _init():
		print("B")

func _ready():
	var b = B.new()
() # Should print A and B
```

Does not print both A and B, this was changed in GDScript 2.0 that callbacks no longer happen multilevel. One should call the parent constructor explicitly with `super()` if it's wanted.

But the crash still needs to be fixed for sure.

**Comment by akien-mga** [comment]
Thanks!
