### PR TITLE
Core: Fix `Callable.get_bound_arguments{,_count}()` return incorrect data

### LINKED ISSUE #98695: `get_bound_arguments` is wrong after using `unbind`
### Tested versions

- Reproducible in v4.4.dev3.official [f4af8201b]

### System information

Windows 11, Vulkan API 1.3.280 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3060 Ti

### Issue description

The doc of `get_bound_arguments_count` says:
```
Returns the total amount of arguments bound (or unbound) via successive bind() or unbind() calls. 
If the amount of arguments unbound is greater than the ones bound, this function returns a value less than zero.
```
So we can guess that `get_bound_arguments` also influenced by unbind() calls.

They bahave just as what the doc says however not be consistent with the real bound arguments used by Callable at runtime.
See the code:
```
extends Node2D

func test(a, b, c, d):
	printt("a:", a)
	printt("b:", b)
	printt("c:", c)
	printt("d:", d)
	
func _ready() -> void:
	var callable = test.bind(1, 2).unbind(1)
	callable.call(7, 8, 9)
	printt("get_bound_arguments:", callable.get_bound_arguments())
```
The output is:
```
a:	7
b:	8
c:	1
d:	2
get_bound_arguments:	[1]
```
The output shows that the `unbind()` call only discard the arguments we passed to the callable and does **NOT** remove previously bound arguments. In the case above, `9` is discard by `unbind(1)` and `1`, `2` are still bound to the last two arguments `c` and `d`. This is not consistent with the result of `c.get_bound_arguments()` which says there is only one argument bound and the value is `1` however we all know that there are two arguments are bound (`1` to `c` and `2` to `d`).

In other words, if `get_bound_arguments` returning `[1]` is correct, then we are being told that `1` is bound to the argument `d` which is absolutely wrong.

From another perspective, isn't the purpose of this method to tell us the real bound arguments used by a Callable? If not, what else can we use to get such information?

So my opinion is `get_bound_arguments_count ` and `get_bound_arguments` should not be influenced by unbind() calls.

**--------------------------Update----------------------------**:  

The conclusion 
```
get_bound_arguments_count ` and `get_bound_arguments` should not be influenced by unbind() calls.
```
is not correct because `unbind()` calls can still "unbind" the arguments bound by a **following** `bind()` call. One example is 
```
var callable = func(a = 1): printt(a)
callable.unbind(1).bind(9).call() # Output is 1, not 9.
```
So the `unbind` doesn't remove previously bound arguments but will remove following bound arguments.
-----------------------------------------------------------------

### Steps to reproduce

Use the code as a script of a 2D node scene and run.

```
extends Node2D

func test(a, b, c, d):
	printt("a:", a)
	printt("b:", b)
	printt("c:", c)
	printt("d:", d)
	
func _ready() -> void:
	var callable = test.bind(1, 2).unbind(1)
	callable.call(7, 8, 9)
	printt("get_bound_arguments:", callable.get_bound_arguments())
```

### Minimal reproduction project (MRP)

NA

### PR DESCRIPTION
**Pull request by dalexeev**
* Fixes #98695.

<details>
<summary>Test script</summary>

```gdscript
@tool
extends EditorScript

func f(a = 0, b = 0, c = 0, d = 0, e = 0, f = 0, g = 0, h = 0):
    return [a, b, c, d, e, f, g, h]

#func get_effective_arguments(callable: Callable, call_args: Array) -> Array:
    #assert(call_args.size() - callable.get_unbound_arguments_count() >= 0)
    #var result = call_args.slice(0, call_args.size() - callable.get_unbound_arguments_count())
    #result.append_array(callable.get_bound_arguments())
    #return result

func test(c: Callable) -> void:
    print("%d %d %-9s %s" % [
    #print("%d %d %d %-9s %s %s" % [
        c.get_argument_count(),
        #c.get_unbound_arguments_count(),
        c.get_bound_arguments_count(),
        c.get_bound_arguments(),
        c.call(7, 8, 9),
        #get_effective_arguments(c, [7, 8, 9])
    ])

func _run() -> void:
    test(f)
    test(f.bind(1, 2))
    test(f.bind(1, 2).unbind(1))
    test(f.bind(1, 2).unbind(1).bind(3, 4))
    test(f.bind(1, 2).unbind(1).bind(3, 4).unbind(1))
    print("---")
    test(f.bind(1).bind(2).bind(3).unbind(1))
    test(f.bind(1).bind(2).unbind(1).bind(3))
    test(f.bind(1).unbind(1).bind(2).bind(3))
    test(f.unbind(1).bind(1).bind(2).bind(3))
    print("---")
    test(f.unbind(1).unbind(1).unbind(1).bind(1, 2, 3))
    test(f.unbind(1).unbind(1).bind(1, 2, 3).unbind(1))
    test(f.unbind(1).bind(1, 2, 3).unbind(1).unbind(1))
    test(f.bind(1, 2, 3).unbind(1).unbind(1).unbind(1))
```

</details>

Before:

```
8 0 []        [7, 8, 9, 0, 0, 0, 0, 0]
6 2 [1, 2]    [7, 8, 9, 1, 2, 0, 0, 0]
7 1 [1]       [7, 8, 1, 2, 0, 0, 0, 0]
5 3 [1, 3, 4] [7, 8, 9, 3, 1, 2, 0, 0]
6 2 [1, 3]    [7, 8, 3, 1, 2, 0, 0, 0]
---
6 2 [1, 2]    [7, 8, 3, 2, 1, 0, 0, 0]
6 2 [1, 3]    [7, 8, 9, 2, 1, 0, 0, 0]
6 2 [2, 3]    [7, 8, 9, 3, 1, 0, 0, 0]
6 2 [2, 3]    [7, 8, 9, 3, 2, 0, 0, 0]
---
8 0 [2, 3]    [7, 8, 9, 0, 0, 0, 0, 0]
8 0 [2]       [7, 8, 1, 0, 0, 0, 0, 0]
8 0 []        [7, 1, 2, 0, 0, 0, 0, 0]
8 0 []        [1, 2, 3, 0, 0, 0, 0, 0]
```

After:

```
8 0 0 []        [7, 8, 9, 0, 0, 0, 0, 0] [7, 8, 9]
6 0 2 [1, 2]    [7, 8, 9, 1, 2, 0, 0, 0] [7, 8, 9, 1, 2]
7 1 2 [1, 2]    [7, 8, 1, 2, 0, 0, 0, 0] [7, 8, 1, 2]
5 0 3 [3, 1, 2] [7, 8, 9, 3, 1, 2, 0, 0] [7, 8, 9, 3, 1, 2]
6 1 3 [3, 1, 2] [7, 8, 3, 1, 2, 0, 0, 0] [7, 8, 3, 1, 2]
---
6 1 3 [3, 2, 1] [7, 8, 3, 2, 1, 0, 0, 0] [7, 8, 3, 2, 1]
6 0 2 [2, 1]    [7, 8, 9, 2, 1, 0, 0, 0] [7, 8, 9, 2, 1]
6 0 2 [3, 1]    [7, 8, 9, 3, 1, 0, 0, 0] [7, 8, 9, 3, 1]
6 0 2 [3, 2]    [7, 8, 9, 3, 2, 0, 0, 0] [7, 8, 9, 3, 2]
---
8 0 0 []        [7, 8, 9, 0, 0, 0, 0, 0] [7, 8, 9]
8 1 1 [1]       [7, 8, 1, 0, 0, 0, 0, 0] [7, 8, 1]
8 2 2 [1, 2]    [7, 1, 2, 0, 0, 0, 0, 0] [7, 1, 2]
8 3 3 [1, 2, 3] [1, 2, 3, 0, 0, 0, 0, 0] [1, 2, 3]
```

Note: This is probably unrelated and may not be a bug, but `get_argument_count()` can return negative values ​​for variadic functions, as in the test.

### CODE REVIEW

**Comment by jinyangcruise** [comment]
Thanks very much for your quick fix.

BTW, I just figured out that unbind() can not only discard the arguments passed to the `call()` or `callv()`, but also the arguments bound by the `bind()` which is chained **after** `unbind()`. I will mention this under my issue page because I wrote that 
```
So my opinion is `get_bound_arguments_count` and `get_bound_arguments` should not be influenced by unbind() calls.
```
which is not that accurate.

**Comment by dalexeev** [comment]
I will try to give a formal proof of why this works and why we first remove unbound arguments and then add bound ones, and not vice versa.

**1\. Successive calls of the same name can be reduced to the form `.bind(...).unbind(...)`.**

1.1. `.bind(A).bind(B)` can be reduced to `.bind(B, A)`, i.e. `.bind(B, A).unbind(0)`.

1.2. `.unbind(N).unbind(M)` can be reduced to `.unbind(N + M)`, i.e. `.bind().unbind(N + M)`.

**2\. Successive calls of different names can be reduced to the form `.bind(...).unbind(...)`.**

2.1. `.bind(A).unbind(N)` cannot be reduced.

2.2. `.unbind(N).bind(A)` can be reduced to `.unbind(N').bind(A')`, where:

```
R = min(N, A.size())
N' = N - R
A' = A.slice(0, A.size() - R)
```

Since `R = min(N, A.size())`, either `N' = 0` or `A'.size() = 0`.

So, `.unbind(N).bind(A)` can be reduced either to `.unbind(N')` or `.bind(A')`, i.e. `bind().unbind(N')` or `.bind(A').unbind(0)`.

**3\. Any sequence of `bind()` and `unbind()` calls can be reduced to the form `.bind(...).unbind(...)`.**

`.bind(A).unbind(N).bind(B).unbind(M)` can be reduced to `.bind(A).unbind(N').bind(B').unbind(M)` (2.2).

So, it will be either `.bind(A).unbind(N').unbind(M)` or `.bind(A).bind(B').unbind(M)` (2.2).

So, it will be either `.bind(A).unbind(N'+ M)` (1.2) or `.bind(B', A).unbind(M)` (1.1).

**Comment by jinyangcruise** [comment]
Very impresive! I hope your summarization can be added on the Godot's documentation which can help many users to better understand the design of bind and unbind.

**Review by AThousandShips — APPROVED** [review]
The theory checks out and the tests provided covers all the cases I think are necessary, didn't do any deeper analysis of the code at this time but it looks good to me!

File: core/variant/callable_bind.cpp [hunk 1]
```diff
@@ -100,44 +100,41 @@ int CallableCustomBind::get_argument_count(bool &r_is_valid) const {
...
-	} else {
-		for (int i = 0; i < binds.size() + sub_count; i++) {
-			r_arguments.write[i] = binds[i - sub_count];
-		}
+	for (int i = 0; i < added_count; i++) {
+		r_arguments.write[i] = binds[i];
 	}
+	for (int i = 0; i < sub_bound_count; i++) {
+		r_arguments.write[i + added_count] = sub_bound_args[i];
+	}
```
Comment (kleonc) [inline core/variant/callable_bind.cpp:133]: Could call `.ptrw()` once before the loops instead (and use such pointer for writing), as each `.write[i]` calls `.ptrw()` on its own (potential minimal overhead).

**Review by kleonc — APPROVED** [review]
Assuming the current behavior of chained `Callable.bind`/`Callable.unbind` calls is correct / we don't want to change that, this fix looks correct to me.
The previous behavior of `Callable.get_bound_arguments` / `Callable.get_bound_arguments_count` makes not much sense for chained binds/unbinds indeed.

The theory in https://github.com/godotengine/godot/pull/98713#issuecomment-2451567279 looks good, code looks fine too. I've tested it some further in action and everything seems to work as expected. :+1:

<details><summary>Test script</summary>
<p>

```gdscript
@tool
extends EditorScript

func foo(a = 0, b = 0, c = 0, d = 0, e = 0, f = 0, g = 0, h = 0):
	return [a, b, c, d, e, f, g, h]
var foo_lambda: Callable = func (a = 0, b = 0, c = 0, d = 0, e = 0, f = 0, g = 0, h = 0):
	return [a, b, c, d, e, f, g, h]

func test(c: Callable, repr: String = "") -> void:
	print("%-18s %-22s  %2d %2d %2d  %-9s  %s" % [
		repr,
		".call(5, 6, 7, 8, 9)" if c.get_unbound_arguments_count() <= 5 else "CAN'T .call(5, 6, 7, 8, 9)",
		c.get_argument_count(),
		c.get_unbound_arguments_count(),
		c.get_bound_arguments_count(),
		c.get_bound_arguments(),
		c.call(5, 6, 7, 8, 9) if c.get_unbound_arguments_count() <= 5 else "N/A",
	])
	##4.3
	#print("%-18s %-22s  %2d %2s %2d  %-9s  %s" % [
		#repr,
		#".call(5, 6, 7, 8, 9)",
		#c.get_argument_count(),
		#"-",
		#c.get_bound_arguments_count(),
		#c.get_bound_arguments(),
		#c.call(5, 6, 7, 8, 9),
	#])

func test_subcalls(c: Callable, subcalls: Array[Subcall]) -> void:
	var repr: String = c.get_method()
	test(c, repr)
	for i in subcalls.size():
		var subcall: Subcall = subcalls[i]
		c = subcall.apply_to(c)
		repr = "%s%s" % [" ".repeat(i), subcall]
		test(c, repr)
	print_separator()

func print_separator() -> void:
	print("-".repeat(90))


func Bind(args: Array) -> Subcall: return Subcall.new(Subcall.Type.BIND, args)
func Unbind(count: int) -> Subcall: return Subcall.new(Subcall.Type.UNBIND, [count])

class Subcall:
	enum Type { BIND, UNBIND }
	var type: Type
	var args: Array
	
	func _init(type: Type, args: Array) -> void:
		self.type = type
		self.args = args
	
	func _to_string() -> String:
		return ".%s(%s)" % [
			"bind" if type == Type.BIND else "unbind",
			", ".join(args),
		]
	
	func apply_to(c: Callable) -> Callable:
		if type == Type.BIND:
			return c.bindv(args)
		else:
			return c.unbind(args[0])


func _run() -> void:
	var f: Callable = foo
	#var f: Callable = foo_lambda
	
	test_subcalls(f, [
		Bind([1, 2]),
		Unbind(1),
		Bind([3, 4]),
		Unbind(1),
	])

	for unbind_arg in [1, 3, 5]:
		print_separator()
		test_subcalls(f, [
			Bind([1]),
			Bind([2]),
			Bind([3]),
			Unbind(unbind_arg),
		])
		test_subcalls(f, [
			Bind([1]),
			Bind([2]),
			Unbind(unbind_arg),
			Bind([3]),
		])
		test_subcalls(f, [
			Bind([1]),
			Unbind(unbind_arg),
			Bind([2]),
			Bind([3]),
		])
		test_subcalls(f, [
			Unbind(unbind_arg),
			Bind([1]),
			Bind([2]),
			Bind([3]),
		])
	
	print_separator()
	test_subcalls(f, [
		Unbind(1),
		Unbind(1),
		Unbind(1),
		Bind([1, 2, 3]),
	])
	test_subcalls(f, [
		Unbind(1),
		Unbind(1),
		Bind([1, 2, 3]),
		Unbind(1),
	])
	test_subcalls(f, [
		Unbind(1),
		Bind([1, 2, 3]),
		Unbind(1),
		Unbind(1),
	])
	test_subcalls(f, [
		Bind([1, 2, 3]),
		Unbind(1),
		Unbind(1),
		Unbind(1),
	])
	
	print_separator()
	test_subcalls(f, [
		Bind([1]),
		Unbind(2),
		Bind([2]),
		Unbind(2),
		Bind([3]),
		Unbind(2),
	])
```

</p>
</details> 

<details><summary>Output (this PR)</summary>
<p>

```
foo                .call(5, 6, 7, 8, 9)     8  0  0  []         [5, 6, 7, 8, 9, 0, 0, 0]
.bind(1, 2)        .call(5, 6, 7, 8, 9)     6  0  2  [1, 2]     [5, 6, 7, 8, 9, 1, 2, 0]
 .unbind(1)        .call(5, 6, 7, 8, 9)     7  1  2  [1, 2]     [5, 6, 7, 8, 1, 2, 0, 0]
  .bind(3, 4)      .call(5, 6, 7, 8, 9)     5  0  3  [3, 1, 2]  [5, 6, 7, 8, 9, 3, 1, 2]
   .unbind(1)      .call(5, 6, 7, 8, 9)     6  1  3  [3, 1, 2]  [5, 6, 7, 8, 3, 1, 2, 0]
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
foo                .call(5, 6, 7, 8, 9)     8  0  0  []         [5, 6, 7, 8, 9, 0, 0, 0]
.bind(1)           .call(5, 6, 7, 8, 9)     7  0  1  [1]        [5, 6, 7, 8, 9, 1, 0, 0]
 .bind(2)          .call(5, 6, 7, 8, 9)     6  0  2  [2, 1]     [5, 6, 7, 8, 9, 2, 1, 0]
  .bind(3)         .call(5, 6, 7, 8, 9)     5  0  3  [3, 2, 1]  [5, 6, 7, 8, 9, 3, 2, 1]
   .unbind(1)      .call(5, 6, 7, 8, 9)     6  1  3  [3, 2, 1]  [5, 6, 7, 8, 3, 2, 1, 0]
------------------------------------------------------------------------------------------
foo                .call(5, 6, 7, 8, 9)     8  0  0  []         [5, 6, 7, 8, 9, 0, 0, 0]
.bind(1)           .call(5, 6, 7, 8, 9)     7  0  1  [1]        [5, 6, 7, 8, 9, 1, 0, 0]
 .bind(2)          .call(5, 6, 7, 8, 9)     6  0  2  [2, 1]     [5, 6, 7, 8, 9, 2, 1, 0]
  .unbind(1)       .call(5, 6, 7, 8, 9)     7  1  2  [2, 1]     [5, 6, 7, 8, 2, 1, 0, 0]
   .bind(3)        .call(5, 6, 7, 8, 9)     6  0  2  [2, 1]     [5, 6, 7, 8, 9, 2, 1, 0]
------------------------------------------------------------------------------------------
foo                .call(5, 6, 7, 8, 9)     8  0  0  []         [5, 6, 7, 8, 9, 0, 0, 0]
.bind(1)           .call(5, 6, 7, 8, 9)     7  0  1  [1]        [5, 6, 7, 8, 9, 1, 0, 0]
 .unbind(1)        .call(5, 6, 7, 8, 9)     8  1  1  [1]        [5, 6, 7, 8, 1, 0, 0, 0]
  .bind(2)         .call(5, 6, 7, 8, 9)     7  0  1  [1]        [5, 6, 7, 8, 9, 1, 0, 0]
   .bind(3)        .call(5, 6, 7, 8, 9)     6  0  2  [3, 1]     [5, 6, 7, 8, 9, 3, 1, 0]
------------------------------------------------------------------------------------------
foo                .call(5, 6, 7, 8, 9)     8  0  0  []         [5, 6, 7, 8, 9, 0, 0, 0]
.unbind(1)         .call(5, 6, 7, 8, 9)     9  1  0  []         [5, 6, 7, 8, 0, 0, 0, 0]
 .bind(1)          .call(5, 6, 7, 8, 9)     8  0  0  []         [5, 6, 7, 8, 9, 0, 0, 0]
  .bind(2)         .call(5, 6, 7, 8, 9)     7  0  1  [2]        [5, 6, 7, 8, 9, 2, 0, 0]
   .bind(3)        .call(5, 6, 7, 8, 9)     6  0  2  [3, 2]     [5, 6, 7, 8, 9, 3, 2, 0]
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
foo                .call(5, 6, 7, 8, 9)     8  0  0  []         [5, 6, 7, 8, 9, 0, 0, 0]
.bind(1)           .call(5, 6, 7, 8, 9)     7  0  1  [1]        [5, 6, 7, 8, 9, 1, 0, 0]
 .bind(2)          .call(5, 6, 7, 8, 9)     6  0  2  [2, 1]     [5, 6, 7, 8, 9, 2, 1, 0]
  .bind(3)         .call(5, 6, 7, 8, 9)     5  0  3  [3, 2, 1]  [5, 6, 7, 8, 9, 3, 2, 1]
   .unbind(3)      .call(5, 6, 7, 8, 9)     8  3  3  [3, 2, 1]  [5, 6, 3, 2, 1, 0, 0, 0]
------------------------------------------------------------------------------------------
foo                .call(5, 6, 7, 8, 9)     8  0  0  []         [5, 6, 7, 8, 9, 0, 0, 0]
.bind(1)           .call(5, 6, 7, 8, 9)     7  0  1  [1]        [5, 6, 7, 8, 9, 1, 0, 0]
 .bind(2)          .call(5, 6, 7, 8, 9)     6  0  2  [2, 1]     [5, 6, 7, 8, 9, 2, 1, 0]
  .unbind(3)       .call(5, 6, 7, 8, 9)     9  3  2  [2, 1]     [5, 6, 2, 1, 0, 0, 0, 0]
   .bind(3)        .call(5, 6, 7, 8, 9)     8  2  2  [2, 1]     [5, 6, 7, 2, 1, 0, 0, 0]
------------------------------------------------------------------------------------------
foo                .call(5, 6, 7, 8, 9)     8  0  0  []         [5, 6, 7, 8, 9, 0, 0, 0]
.bind(1)           .call(5, 6, 7, 8, 9)     7  0  1  [1]        [5, 6, 7, 8, 9, 1, 0, 0]
 .unbind(3)        .call(5, 6, 7, 8, 9)    10  3  1  [1]        [5, 6, 1, 0, 0, 0, 0, 0]
  .bind(2)         .call(5, 6, 7, 8, 9)     9  2  1  [1]        [5, 6, 7, 1, 0, 0, 0, 0]
   .bind(3)        .call(5, 6, 7, 8, 9)     8  1  1  [1]        [5, 6, 7, 8, 1, 0, 0, 0]
------------------------------------------------------------------------------------------
foo                .call(5, 6, 7, 8, 9)     8  0  0  []         [5, 6, 7, 8, 9, 0, 0, 0]
.unbind(3)         .call(5, 6, 7, 8, 9)    11  3  0  []         [5, 6, 0, 0, 0, 0, 0, 0]
 .bind(1)          .call(5, 6, 7, 8, 9)    10  2  0  []         [5, 6, 7, 0, 0, 0, 0, 0]
  .bind(2)         .call(5, 6, 7, 8, 9)     9  1  0  []         [5, 6, 7, 8, 0, 0, 0, 0]
   .bind(3)        .call(5, 6, 7, 8, 9)     8  0  0  []         [5, 6, 7, 8, 9, 0, 0, 0]
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
foo                .call(5, 6, 7, 8, 9)     8  0  0  []         [5, 6, 7, 8, 9, 0, 0, 0]
.bind(1)           .call(5, 6, 7, 8, 9)     7  0  1  [1]        [5, 6, 7, 8, 9, 1, 0, 0]
 .bind(2)          .call(5, 6, 7, 8, 9)     6  0  2  [2, 1]     [5, 6, 7, 8, 9, 2, 1, 0]
  .bind(3)         .call(5, 6, 7, 8, 9)     5  0  3  [3, 2, 1]  [5, 6, 7, 8, 9, 3, 2, 1]
   .unbind(5)      .call(5, 6, 7, 8, 9)    10  5  3  [3, 2, 1]  [3, 2, 1, 0, 0, 0, 0, 0]
------------------------------------------------------------------------------------------
foo                .call(5, 6, 7, 8, 9)     8  0  0  []         [5, 6, 7, 8, 9, 0, 0, 0]
.bind(1)           .call(5, 6, 7, 8, 9)     7  0  1  [1]        [5, 6, 7, 8, 9, 1, 0, 0]
 .bind(2)          .call(5, 6, 7, 8, 9)     6  0  2  [2, 1]     [5, 6, 7, 8, 9, 2, 1, 0]
  .unbind(5)       .call(5, 6, 7, 8, 9)    11  5  2  [2, 1]     [2, 1, 0, 0, 0, 0, 0, 0]
   .bind(3)        .call(5, 6, 7, 8, 9)    10  4  2  [2, 1]     [5, 2, 1, 0, 0, 0, 0, 0]
------------------------------------------------------------------------------------------
foo                .call(5, 6, 7, 8, 9)     8  0  0  []         [5, 6, 7, 8, 9, 0, 0, 0]
.bind(1)           .call(5, 6, 7, 8, 9)     7  0  1  [1]        [5, 6, 7, 8, 9, 1, 0, 0]
 .unbind(5)        .call(5, 6, 7, 8, 9)    12  5  1  [1]        [1, 0, 0, 0, 0, 0, 0, 0]
  .bind(2)         .call(5, 6, 7, 8, 9)    11  4  1  [1]        [5, 1, 0, 0, 0, 0, 0, 0]
   .bind(3)        .call(5, 6, 7, 8, 9)    10  3  1  [1]        [5, 6, 1, 0, 0, 0, 0, 0]
------------------------------------------------------------------------------------------
foo                .call(5, 6, 7, 8, 9)     8  0  0  []         [5, 6, 7, 8, 9, 0, 0, 0]
.unbind(5)         .call(5, 6, 7, 8, 9)    13  5  0  []         [0, 0, 0, 0, 0, 0, 0, 0]
 .bind(1)          .call(5, 6, 7, 8, 9)    12  4  0  []         [5, 0, 0, 0, 0, 0, 0, 0]
  .bind(2)         .call(5, 6, 7, 8, 9)    11  3  0  []         [5, 6, 0, 0, 0, 0, 0, 0]
   .bind(3)        .call(5, 6, 7, 8, 9)    10  2  0  []         [5, 6, 7, 0, 0, 0, 0, 0]
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
foo                .call(5, 6, 7, 8, 9)     8  0  0  []         [5, 6, 7, 8, 9, 0, 0, 0]
.unbind(1)         .call(5, 6, 7, 8, 9)     9  1  0  []         [5, 6, 7, 8, 0, 0, 0, 0]
 .unbind(1)        .call(5, 6, 7, 8, 9)    10  2  0  []         [5, 6, 7, 0, 0, 0, 0, 0]
  .unbind(1)       .call(5, 6, 7, 8, 9)    11  3  0  []         [5, 6, 0, 0, 0, 0, 0, 0]
   .bind(1, 2, 3)  .call(5, 6, 7, 8, 9)     8  0  0  []         [5, 6, 7, 8, 9, 0, 0, 0]
------------------------------------------------------------------------------------------
foo                .call(5, 6, 7, 8, 9)     8  0  0  []         [5, 6, 7, 8, 9, 0, 0, 0]
.unbind(1)         .call(5, 6, 7, 8, 9)     9  1  0  []         [5, 6, 7, 8, 0, 0, 0, 0]
 .unbind(1)        .call(5, 6, 7, 8, 9)    10  2  0  []         [5, 6, 7, 0, 0, 0, 0, 0]
  .bind(1, 2, 3)   .call(5, 6, 7, 8, 9)     7  0  1  [1]        [5, 6, 7, 8, 9, 1, 0, 0]
   .unbind(1)      .call(5, 6, 7, 8, 9)     8  1  1  [1]        [5, 6, 7, 8, 1, 0, 0, 0]
------------------------------------------------------------------------------------------
foo                .call(5, 6, 7, 8, 9)     8  0  0  []         [5, 6, 7, 8, 9, 0, 0, 0]
.unbind(1)         .call(5, 6, 7, 8, 9)     9  1  0  []         [5, 6, 7, 8, 0, 0, 0, 0]
 .bind(1, 2, 3)    .call(5, 6, 7, 8, 9)     6  0  2  [1, 2]     [5, 6, 7, 8, 9, 1, 2, 0]
  .unbind(1)       .call(5, 6, 7, 8, 9)     7  1  2  [1, 2]     [5, 6, 7, 8, 1, 2, 0, 0]
   .unbind(1)      .call(5, 6, 7, 8, 9)     8  2  2  [1, 2]     [5, 6, 7, 1, 2, 0, 0, 0]
------------------------------------------------------------------------------------------
foo                .call(5, 6, 7, 8, 9)     8  0  0  []         [5, 6, 7, 8, 9, 0, 0, 0]
.bind(1, 2, 3)     .call(5, 6, 7, 8, 9)     5  0  3  [1, 2, 3]  [5, 6, 7, 8, 9, 1, 2, 3]
 .unbind(1)        .call(5, 6, 7, 8, 9)     6  1  3  [1, 2, 3]  [5, 6, 7, 8, 1, 2, 3, 0]
  .unbind(1)       .call(5, 6, 7, 8, 9)     7  2  3  [1, 2, 3]  [5, 6, 7, 1, 2, 3, 0, 0]
   .unbind(1)      .call(5, 6, 7, 8, 9)     8  3  3  [1, 2, 3]  [5, 6, 1, 2, 3, 0, 0, 0]
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
foo                .call(5, 6, 7, 8, 9)     8  0  0  []         [5, 6, 7, 8, 9, 0, 0, 0]
.bind(1)           .call(5, 6, 7, 8, 9)     7  0  1  [1]        [5, 6, 7, 8, 9, 1, 0, 0]
 .unbind(2)        .call(5, 6, 7, 8, 9)     9  2  1  [1]        [5, 6, 7, 1, 0, 0, 0, 0]
  .bind(2)         .call(5, 6, 7, 8, 9)     8  1  1  [1]        [5, 6, 7, 8, 1, 0, 0, 0]
   .unbind(2)      .call(5, 6, 7, 8, 9)    10  3  1  [1]        [5, 6, 1, 0, 0, 0, 0, 0]
    .bind(3)       .call(5, 6, 7, 8, 9)     9  2  1  [1]        [5, 6, 7, 1, 0, 0, 0, 0]
     .unbind(2)    .call(5, 6, 7, 8, 9)    11  4  1  [1]        [5, 1, 0, 0, 0, 0, 0, 0]
------------------------------------------------------------------------------------------
```

</p>
</details>

---

Some core folks should take a look at this before merging though (I'm not sure if everything needed was changed, if it won't break extensions etc.).

**Comment by AThousandShips** [comment]
> Assuming the current behavior of chained `Callable.bind/Callable.unbind` calls is correct / we don't want to change that, this fix looks correct to me.

I think we can evaluate down the line exactly the desired behavior, but I think maintaining the behavior of those, as it is at least useful, is more important than these methods, I would say more people would be affected by changes to the binding behavior

**Comment by Repiteo** [comment]
Thanks!
