### PR TITLE
StyleBoxFlat: Fix glitchy overlapping shapes

### LINKED ISSUE #102818: Panel - StyleBoxFlat with rounded borders LEFT and RIGHT creates a line of lighter color in the middle of the panel
### Tested versions

Godot Engine v4.3.stable.official.77dcf97d8

### System information

Win11 - OpenGL API 3.3.0 NVIDIA 572.16 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce RTX 2060 SUPER

### Issue description

Left and Right border (light line is present):
Image

Top and Bottom (no light line):
Image

At runtime:
Image

But if I change the size (to a greater value on X axis) - the line disappears:
Image

### Steps to reproduce

1. Create a Panel
2. Change the size to 128x128
3. Add StyleBoxFlat in Theme Override - Styles
4. Set all Corner Radiuses to 70 (to create the circle)
5. Change the BG color to a darker one with some opacity
6. In Border Width for the StyleBox start adding to LEFT or RIGHT (or both)

### Minimal reproduction project (MRP)

Not needed

### PR DESCRIPTION
**Pull request by dugramen**
Fixes #102818

This should fix a lot of issues relating to StyleBoxFlat producing glitchy overlapping shapes. It does this by reducing the inner corner radii proportionately to how much they cause overflows (when the borders + radii are bigger than the available rect).

| Before | After |
| --- | --- |
| image | image |
| image | image |
| image | image |

It's worth noting that anti aliasing is a separate issue and can still sometimes cause tiny bands to appear with translucent colors. I (or someone else) can try to tackle that in another PR. For example:

image

Edit: Corners now scale down instead of reducing their radius

### CODE REVIEW

**Comment by KoBeWi** [comment]
Is scaling the shape more complex? If it isn't much more costly than reducing radius then it's better to use it instead.
The code looks quite complex, it would be nice to have some test scene with various StyleBoxes to make sure there is no regression.

**Comment by dugramen** [comment]
> Is scaling the shape more complex? If it isn't much more costly than reducing radius then it's better to use it instead.

It's a few more lines of code, but it does mostly the same calculations.

> The code looks quite complex, it would be nice to have some test scene with various StyleBoxes to make sure there is no regression.

I'll try to upload a project with some test cases.

**Comment by dugramen** [comment]
Made a test project that generates combinations of border widths and radii
[stylebox-test_2025-03-09_23-49-45.zip](https://github.com/user-attachments/files/19155313/stylebox-test_2025-03-09_23-49-45.zip)

Also pushed the version that scales corners. I added a lot of comments, though I don't think they all need to be there. Hopefully they can at least make it clearer for now

File: scene/resources/style_box_flat.cpp [hunk 1]
```diff
@@ -234,6 +234,79 @@ inline void set_inner_corner_radius(const Rect2 style_rect, const Rect2 inner_re
 	inner_corner_radius[3] = MAX(corner_radius[3] - MIN(border_bottom, border_left), 0); // Bottom left.
 }
 
+inline void set_corner_scale(const Rect2 style_rect, const Rect2 inner_rect, const real_t corner_radius[4], Point2 *inner_scale) {
```
Comment (KoBeWi) [inline scene/resources/style_box_flat.cpp:237]:
```suggestion
inline void set_corner_scale(const Rect2 &style_rect, const Rect2 &inner_rect, const real_t corner_radius[4], Point2 *inner_scale) {
```
(I know other methods don't do that, but they should)

**Review by KoBeWi — APPROVED** [review]

File: scene/resources/style_box_flat.cpp (hunk 1 above)
Comment (dugramen) [reply scene/resources/style_box_flat.cpp]: Ok I pushed the change

**Comment by akien-mga** [comment]
Thanks!
