### PR TITLE
Run resource previewer on the main thread if using GL compatibility

### LINKED ISSUE #87196: Enabling the compatibility renderer leaks `Image` objects when using the Editor
### Tested versions

26b1fd0d842fa3c2f090ead47e8ea7cd2d6515e1 - reproducible
4.2.1 - Not reproducible

### System information

Godot v4.3.dev (e3b9f08ce) - Arch Linux #1 SMP PREEMPT_DYNAMIC Fri, 05 Jan 2024 16:20:41 +0000 - Tty - GLES3 (Compatibility) - AMD Radeon RX 6900 XT (radeonsi, navi21, LLVM 16.0.6, DRM 3.54, 6.6.10-arch1-1) () - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

Enabling the compatibility renderer will leak `Image` objects. This issue does not happen with the `Forward+` nor the `Mobile` rendering methods.

I think this issue was introduced within the last two months.

### Steps to reproduce

Open the Editor against the MRP through the command line (i.e. for example `godot -e --verbose` if on path).

Close the editor after a few seconds and you should see a similar message:

```
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:2204)
Leaked instance: Image:-9170885200035390510 - Resource path: 
Leaked instance: Image:-9170880252233060709 - Resource path: 
Leaked instance: Image:-9170864309314457951 - Resource path: 
Leaked instance: Image:-9170863759558644050 - Resource path: 
Leaked instance: Image:-9170858811756319055 - Resource path: 
Leaked instance: Image:-9170858262000505166 - Resource path: 
Leaked instance: Image:-9170853863953994059 - Resource path: 
Leaked instance: Image:-9170853314198180170 - Resource path: 
Leaked instance: Image:-9170848366395855175 - Resource path: 
Leaked instance: Image:-9170847816640041286 - Resource path: 
```

### Minimal reproduction project (MRP)

[glow.zip](https://github.com/godotengine/godot/files/13933608/glow.zip) - from the [demo projects](https://github.com/godotengine/godot-demo-projects/tree/4a4b46cbe1f5105b664b99f325984096151b75a1/2d/glow) with the Compatibility renderer enabled by default.

### PR DESCRIPTION
**Pull request by RandomShaper**
I don't know why the issue was surfaced by #86587, but to my understanding, it was already there previously. The issue is that with OpenGL (Compatibility rendering method)  you can't deal with textures from arbitrary threads. The rendering server tries to do the right thing by sending the tasks to a queue, but the resource importer will blindly continue doing its job without waiting for them to be created. The worst consequence is that, given the relevant texture-related functions take references to resource references (`Ref<>&`), by the time the previewer thinks it's done with some images it can decrease their refcount to zero. Because of that, there are dangling references by the time the queue is flushed later.

This PR fixes the ill situations by just letting the main thread flush any outstanding resource importing tasks every idle frame. That ensures that any previewer, either one that directly deals with rendering or one that doesn't, because in the end all of them have to create the preview images, don't incurr in sync issues.

This will affect the responsiveness of the editor while there are queued preview tasks. The code tries to let the editor breathe a bit to avoid looking frozen.

#77004 should fix the issue at some point, so this PR may be reverted or the approach re-assessed. Some care will be needed anyway in the resource previewing code so that lifespans, etc. are properly handled. Pre-4.3 there's no other fix than this.

Finally, some extra testing would be appreciated.

Fixes #87196.

### CODE REVIEW

**Comment by YuriSizov** [comment]
`TilesEditorUtils` is a very close copy of the entire `EditorResourcePreview` class. I assume it needs the same fix?

**Comment by RandomShaper** [comment]
> `TilesEditorUtils` is a very close copy of the entire `EditorResourcePreview` class. I assume it needs the same fix?

Good question. I've checked the code and it seems it's fine already. The code there is already safe by using several sync mechanisms to let the main thread deal with the viewports and eventually, only when it's known the texture is ready, claiming the results.

By the way, `EditorResourcePreview` may want to do something similar, which would still allow some work to happen in parallel on another thread, but such an approach would involve adding the needed "sync points" across both that class and all the preview plugins. I don't think it's very worth the work, when an upcoming PR will fix the underlying issue for good, unless the approach in this PR turned out to be too impractical in practice (he-he, what an expression).

File: editor/editor_resource_preview.cpp [hunk 1]
```diff
@@ -441,27 +456,38 @@ void EditorResourcePreview::check_for_invalidation(const String &p_path) {
...
+	if (DisplayServer::get_singleton()->get_name() == "headless") {
+		return;
+	}
+
+	if (RSG::texture_storage->can_create_resources_async()) {
 		ERR_FAIL_COND_MSG(thread.is_started(), "Thread already started.");
 		thread.start(_thread_func, this);
+	} else {
+		SceneTree *st = Object::cast_to<SceneTree>(OS::get_singleton()->get_main_loop());
+		if (st) {
```
Comment (akien-mga) [inline editor/editor_resource_preview.cpp:468]: Is there any realistic scenario where the editor main loop wouldn't be SceneTree?
If not, we might want to put a `ERR_FAIL_NULL(st);` there for good measure instead of `if (st)`.

**Review by akien-mga — APPROVED** [review]
Looks good to me.

File: editor/editor_resource_preview.cpp (hunk 1 above)
Comment (RandomShaper) [reply editor/editor_resource_preview.cpp]: Good point. Changed.

**Comment by akien-mga** [comment]
Tested and confirmed this fixes https://github.com/godotengine/godot/issues/87196.

**Comment by akien-mga** [comment]
Thanks!
