### PR TITLE
Use min_size/max_size to limit window size and position while popup center

### LINKED ISSUE #62163: When popup center, non-default limit value will make the window off-center
### Godot version

v4.0.alpha9.official [fc18891db]

### System information

Linux Mint 20.3, Vulkan, NVIDIA GeForce GTX 1050 Ti

### Issue description

If `max_size`/`min_size` is not `(0,0)` (the default value), the window may be off-center when calling `pop_center`. ~~It may be caused by not considering these two limit values when calculating `_get_contents_minimum_size`.~~ 

I'm not sure if these limits should be considered in `_get_contents_minimum_size`, in `AcceptDialog`, only `min_size.x` is considered, in other `Window` derived classes, these are not considered at all. Probably because of `wrap_controls` (it seems redundant in AcceptDialog), `_get_contents_minimum_size` is calculated completely differently in `Window` and `AcceptDialog`. Maybe we should also take `wrap_controls` into account when calculating.

### Steps to reproduce

Make `max_size` small enough or make `min_size` large enough before calling `popup_center()`

### Minimal reproduction project

[popup-center-off-center.zip](https://github.com/godotengine/godot/files/10670922/popup-center-off-center.zip)

### PR DESCRIPTION
**Pull request by Rindbee**
Fix #62163.

The `popup_center*` methods need to determine the popup position according to the actual size of the window.

Previously, `max_size`/`min_size` was not considered in these methods, which in some cases could cause the window to actually be off-center.

In this PR, Add a method to get the minimum size of content that has been clamped by a custom minimum size. `Window::get_clamped_minimum_size`.

`min_size` will be considered in `Window::get_clamped_minimum_size`. The result is to return the value clamped by the custom min size.

And `wrap_controls` is also taken into account. if `wrap_controls` is not enabled, `Window::get_clamped_minimum_size` return `min_size` directly.

The return value of `get_clamped_minimum_size` is the actual **lower** limit of the window `size`, and `max_size` is the actual **upper** limit of the window `size`.

~~If a component of `max_size` is `0`, it means there is no limit on the corresponding axis. This is the same as before.~~

Follow the rules of `min_size`/`max_size`, but at this stage `max_size` seems to be unable to limit only one axis when resize, and let the other axis unlimited. Only `(0, 0)` means unlimited, a single component of `0` is not yet possible, it may only invalidate the entire `max_size`. Therefore, for consistency, `max_size` will use the same invalidation rules as in #63925.

Edit:

| Control | Window | Explanation |
| :--------: | :---------: | :--------------: |
| `get_custom_minimum_size` | `get_min_size` | Get custom min size limit |
| `get_minimum_size` | `get_contents_minimum_size` | Get contents minimum size |
| `get_combined_minimum_size` | `get_clamped_minimum_size` | Get the minimum size of the content that has been clamped by the custom min size |

| Before | After | Explanation |
| :-------: | :-----: | :-------------: |
|  |  | `max_size = (300, 200)` |
|  |  | `max_size = (0, 0)` or **invalid** (eg. `max_size = (300, 200)`; `min_size = (0, 300)`)

Edit:

Test project
[popup-center-off-center.zip](https://github.com/godotengine/godot/files/10670960/popup-center-off-center.zip)

Beta17:

https://user-images.githubusercontent.com/30386067/217132685-533c74c1-4968-4541-84ae-5ac020d8d2b5.mp4

This PR:

https://user-images.githubusercontent.com/30386067/217132734-7c15cc43-9fe4-4c0b-8009-c6ac358aa48e.mp4

### CODE REVIEW

File: scene/main/window.cpp [hunk 1]
```diff
@@ -1179,6 +1183,17 @@ Size2 Window::get_contents_minimum_size() const {
 	return _get_contents_minimum_size();
 }
 
+Size2 Window::get_clamped_minimun_size() const {
```
Comment (akien-mga) [inline scene/main/window.cpp:1186]: Typo (minimuM).

Comment (Rindbee) [reply scene/main/window.cpp]: OK, thanks for pointing out

File: scene/main/window.h [hunk 2]
```diff
@@ -96,6 +96,7 @@ class Window : public Viewport {
 	mutable Size2i size = Size2i(DEFAULT_WINDOW_SIZE, DEFAULT_WINDOW_SIZE);
 	mutable Size2i min_size;
 	mutable Size2i max_size;
+	Size2i max_size_used;
```
Comment (KoBeWi) [inline scene/main/window.h:99]: This property should probably be elsewhere. It doesn't look good here.

**Review by KoBeWi — APPROVED** [review]
Needs rebase.

**Comment by Rindbee** [comment]
Done.

**Comment by YuriSizov** [comment]
Seems like it needs another one 🙈

**Comment by Rindbee** [comment]
It has been rebase, and I uploaded the test project and comparison video by the way.

**Comment by akien-mga** [comment]
CC @Sauermann

File: scene/main/window.cpp [hunk 3]
```diff
@@ -833,49 +859,34 @@ bool Window::is_visible() const {
...
-	if (wrap_controls) {
-		size_limit = get_contents_minimum_size();
-	}
+	return window_size_clamped;
+}
 
-	size_limit.x = MAX(size_limit.x, min_size.x);
-	size_limit.y = MAX(size_limit.y, min_size.y);
+void Window::_update_window_size() {
+	Size2i size_limit = get_clamped_minimum_size();
```
Comment (Sauermann) [inline scene/main/window.cpp:875]: Isn't this value cached in `Window::min_size`?

**Review by Sauermann — COMMENTED** [review]
The idea of this PR makes sense. Have tested, that it solves the linked issue.
The implemented functionality looks fine, but I can't tell for sure, if there are corner-cases, that aren't considered.

File: scene/main/window.cpp (hunk 3 above)
Comment (Rindbee) [reply scene/main/window.cpp:875]: This is the minimum window size can actually reach, it may be larger than `min_size` when `wrap_controls` is enabled.

File: scene/main/window.cpp [hunk 4]
```diff
@@ -833,49 +859,34 @@ bool Window::is_visible() const {
 	return visible;
 }
 
-void Window::_update_window_size() {
-	// Force window to respect size limitations of rendering server.
```
[the remark this answers is not in the document]
Comment (Rindbee) [reply scene/main/window.cpp:837]: This PR indirectly limits the size:

1. Make `min_size` and `max_size` follow the size limit of the rendering server, see `Window::_clamp_limit_size`;
2. Then make sure that `max_size_used` is not less than `min_size`, see `Window::_validate_limit_size()`.

`max_size_used` is the upper limit of actual use, it will be clamped by `min_size` and `max_size`, combined with 1, it will eventually follow the size limit of the rendering server.

`get_clamped_minimum_size()` returns the actual lower bound used, which takes into account the case when `wrap_controls` is enabled.

[the remark this answers is not in the document]
Comment (Rindbee) [reply scene/main/window.cpp:837]: >     2. Then make sure that `max_size_used` is not less than `min_size`, see `Window::_validate_limit_size()`.

It just ensures that when `max_size` is not as large as `min_size`, `RS::get_singleton()->get_maximum_viewport_size()` is actually used. I'm not sure whether this method returns `(0,0)`.

[the remark this answers is not in the document]
Comment (Sauermann) [reply scene/main/window.cpp:837]: Since this is not an obvious functionality, I believe, that it should be documented in a comment.

[the remark this answers is not in the document]
Comment (Rindbee) [reply scene/main/window.cpp:837]: OK, some comments have been added.

**Comment by akien-mga** [comment]
Thanks!
