### PR TITLE
Remove word duplicates in comments and strings, and fix casing and punctuation

### LINKED ISSUE #88711: Typo in message (word duplicated)
### Tested versions

Reproductible

### System information

not OS related

### Issue description

In https://github.com/godotengine/godot/blob/master/modules/multiplayer/editor/replication_editor.cpp#L295
word "them" is typed twice.

### Steps to reproduce

n/a

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by ryevdokimov**
Used regex to find these. Ignored third party files. 

Fixes: #88711

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
What regex did you use? Might be handy to re-run in the future as such issues slip through review.

**Comment by ryevdokimov** [comment]
Hold off on this, I found more with a refined search. 

> What regex did you use? Might be handy to re-run in the future as such issues slip through review.

Currently: 

For comments: \/\/.*\b(\w+)\b\s+\1\b (There are some results I ignored like owner owner, because I didn't know if it meant owner's owner, I didn't want to get too nitpicky) 

For strings: (["'])(?:(?=(\\?))\2.)*?\b(\w+)\b(?:\s+\3\b)+(?:(?=(\\?))\4.)*?\1

File: core/variant/variant_construct.h [hunk 1]
```diff
@@ -661,7 +661,7 @@ class VariantConstructNoArgsNil {
 		VariantInternal::clear(r_ret);
 	}
 	static void ptr_construct(void *base, const void **p_args) {
-		ERR_FAIL_MSG("can't ptrcall nil constructor");
+		ERR_FAIL_MSG("Cannot ptrcall nil constructor");
```
Comment (ryevdokimov) [inline core/variant/variant_construct.h:664]: Regex for MSG( starting with lower case, updated a few to fit other messages I found.

File: scene/resources/skeleton_modification_2d_twoboneik.cpp [hunk 2]
```diff
@@ -281,16 +281,16 @@ void SkeletonModification2DTwoBoneIK::update_joint_one_bone2d_cache() {
...
 				ERR_FAIL_COND_MSG(!node->is_inside_tree(),
-						"Cannot update update joint one Bone2D cache: node is not in the scene tree!");
+						"Cannot update joint one Bone2D cache: node is not in the scene tree!");
 				joint_one_bone2d_node_cache = node->get_instance_id();
 
 				Bone2D *bone = Object::cast_to<Bone2D>(node);
 				if (bone) {
 					joint_one_bone_idx = bone->get_index_in_skeleton();
 				} else {
-					ERR_FAIL_MSG("update joint one Bone2D cache: Nodepath to Bone2D is not a Bone2D node!");
```
Comment (ryevdokimov) [inline scene/resources/skeleton_modification_2d_twoboneik.cpp:293]: Lower case to upper case.

File: core/variant/variant_construct.h (hunk 1 above)
Comment (ryevdokimov) [reply core/variant/variant_construct.h:664]: What about exclamation points?

https://github.com/godotengine/godot/blob/da4f50851d15c073ca413196aa1501fb97108c07/scene/resources/skeleton_modification_2d_twoboneik.cpp#L286

Comment (akien-mga) [reply core/variant/variant_construct.h:664]: In most cases yeah, the exclamation mark might be overdoing it a bit. But that might imply further improving the phrasing for consistency with other similar errors, which may be outside the scope of this PR :)

File: core/io/dir_access.h [hunk 3]
```diff
@@ -116,10 +116,10 @@ class DirAccess : public RefCounted {
 		Ref<DirAccess> da = create(ACCESS_FILESYSTEM);
 		if (da->file_exists(p_path)) {
 			if (da->remove(p_path) != OK) {
-				ERR_FAIL_MSG("Cannot remove file or directory: " + p_path);
+				ERR_FAIL_MSG("Cannot remove file or directory: " + p_path + ".");
 			}
 		} else {
-			ERR_FAIL_MSG("Cannot remove non-existent file or directory: " + p_path);
+			ERR_FAIL_MSG("Cannot remove non-existent file or directory: " + p_path + ".");
```
Comment (akien-mga) [inline core/io/dir_access.h:122]: I think in this case, the omission was intention, to avoid confusion at to whether the dot is part of the file path or not.

Comment (ryevdokimov) [reply core/io/dir_access.h:122]: Oops, yeah that makes sense. I should avoid doing it to file paths. Agreed.

File: core/math/basis.cpp [hunk 4]
```diff
@@ -685,7 +685,7 @@ void Basis::set_euler(const Vector3 &p_euler, EulerOrder p_order) {
 			*this = zmat * ymat * xmat;
 		} break;
 		default: {
-			ERR_FAIL_MSG("Invalid order parameter for set_euler(vec3,order)");
+			ERR_FAIL_MSG("Invalid order parameter for set_euler(vec3,order).");
```
Comment (akien-mga) [inline core/math/basis.cpp:688]:
```suggestion
			ERR_FAIL_MSG("Invalid Euler order parameter.");
```

File: servers/rendering/rendering_device.cpp [hunk 5]
```diff
@@ -3782,12 +3782,12 @@ void RenderingDevice::draw_list_draw(DrawListID p_list, bool p_use_indices, uint
 #ifdef DEBUG_ENABLED
 		if (dl->state.sets[i].pipeline_expected_format != dl->state.sets[i].uniform_set_format) {
 			if (dl->state.sets[i].uniform_set_format == 0) {
-				ERR_FAIL_MSG("Uniforms were never supplied for set (" + itos(i) + ") at the time of drawing, which are required by the pipeline");
+				ERR_FAIL_MSG("Uniforms were never supplied for set (" + itos(i) + ") at the time of drawing, which are required by the pipeline.");
 			} else if (uniform_set_owner.owns(dl->state.sets[i].uniform_set)) {
 				UniformSet *us = uniform_set_owner.get_or_null(dl->state.sets[i].uniform_set);
-				ERR_FAIL_MSG("Uniforms supplied for set (" + itos(i) + "):\n" + _shader_uniform_debug(us->shader_id, us->shader_set) + "\nare not the same format as required by the pipeline shader. Pipeline shader requires the following bindings:\n" + _shader_uniform_debug(dl->state.pipeline_shader));
+				ERR_FAIL_MSG("Uniforms supplied for set (" + itos(i) + "):\n" + _shader_uniform_debug(us->shader_id, us->shader_set) + "\nare not the same format as required by the pipeline shader. Pipeline shader requires the following bindings:\n" + _shader_uniform_debug(dl->state.pipeline_shader) + ".");
```
Comment (akien-mga) [inline servers/rendering/rendering_device.cpp:3788]: This will look weird, I think it's better without dot. Same for the one below.

File: servers/rendering/rendering_device.cpp [hunk 6]
```diff
@@ -4269,9 +4269,9 @@ void RenderingDevice::compute_list_dispatch_indirect(ComputeListID p_list, RID p
...
 				UniformSet *us = uniform_set_owner.get_or_null(cl->state.sets[i].uniform_set);
-				ERR_FAIL_MSG("Uniforms supplied for set (" + itos(i) + "):\n" + _shader_uniform_debug(us->shader_id, us->shader_set) + "\nare not the same format as required by the pipeline shader. Pipeline shader requires the following bindings:\n" + _shader_uniform_debug(cl->state.pipeline_shader));
+				ERR_FAIL_MSG("Uniforms supplied for set (" + itos(i) + "):\n" + _shader_uniform_debug(us->shader_id, us->shader_set) + "\nare not the same format as required by the pipeline shader. Pipeline shader requires the following bindings:\n" + _shader_uniform_debug(cl->state.pipeline_shader) + ".");
 			} else {
-				ERR_FAIL_MSG("Uniforms supplied for set (" + itos(i) + ", which was was just freed) are not the same format as required by the pipeline shader. Pipeline shader requires the following bindings:\n" + _shader_uniform_debug(cl->state.pipeline_shader));
+				ERR_FAIL_MSG("Uniforms supplied for set (" + itos(i) + ", which was just freed) are not the same format as required by the pipeline shader. Pipeline shader requires the following bindings:\n" + _shader_uniform_debug(cl->state.pipeline_shader) + ".");
```
Comment (akien-mga) [inline servers/rendering/rendering_device.cpp:4274]: Also those two wouldn't work with a dot on the line with the shader binding.

File: core/io/dir_access.h (hunk 3 above)
Comment (ryevdokimov) [reply core/io/dir_access.h:122]: There are existing examples of adding the period at the end of the path. Would you like me to remove those? 

https://github.com/godotengine/godot/blob/87d40ba743ff3a3a484db051c11b16559604efa9/core/config/project_settings.cpp#L1096

Comment (akien-mga) [reply core/io/dir_access.h:122]: What's most commonly used currently?

Comment (ryevdokimov) [reply core/io/dir_access.h:122]: Without the dot is used 3x as much. 

image

vs

image

Comment (akien-mga) [reply core/io/dir_access.h:122]: Let's standardize on no dots for these then.

File: core/variant/variant_construct.h (hunk 1 above)
Comment (ryevdokimov) [reply core/variant/variant_construct.h:664]: Understood. Leaving them alone for now.

**Review by akien-mga — APPROVED** [review]

File: drivers/d3d12/rendering_device_driver_d3d12.cpp [hunk 7]
```diff
@@ -1860,7 +1860,7 @@ void RenderingDeviceDriverD3D12::command_pipeline_barrier(
 		VectorView<RDD::BufferBarrier> p_buffer_barriers,
 		VectorView<RDD::TextureBarrier> p_texture_barriers) {
 	if (p_src_stages.has_flag(PIPELINE_STAGE_ALL_COMMANDS_BIT) && p_dst_stages.has_flag(PIPELINE_STAGE_ALL_COMMANDS_BIT)) {
-		// Looks like the intent is a a full barrier.
```
Comment (ryevdokimov) [inline drivers/d3d12/rendering_device_driver_d3d12.cpp:1863]: Rebased to fix recent merge conflict and found another one in the process.

File: editor/editor_settings.cpp [hunk 8]
```diff
@@ -1597,7 +1597,7 @@ void ED_SHORTCUT_OVERRIDE(const String &p_path, const String &p_feature, Key p_k
 	ERR_FAIL_NULL_MSG(EditorSettings::get_singleton(), "EditorSettings not instantiated yet.");
 
 	Ref<Shortcut> sc = EditorSettings::get_singleton()->get_shortcut(p_path);
-	ERR_FAIL_COND_MSG(!sc.is_valid(), "Used ED_SHORTCUT_OVERRIDE with invalid shortcut: " + p_path + ".");
+	ERR_FAIL_COND_MSG(!sc.is_valid(), "Used ED_SHORTCUT_OVERRIDE with invalid shortcut: " + p_path);
```
Comment (Mickeon) [inline editor/editor_settings.cpp:1600]: I don't understand, are error messages with paths meant to end with, or without punctuation? What's the rule here?

Comment (ryevdokimov) [reply editor/editor_settings.cpp:1600]: My understanding is without: https://github.com/godotengine/godot/pull/88733#discussion_r1501214002

**Comment by akien-mga** [comment]
Thanks!
