### PR TITLE
[PopupMenu] Fix incorrect vertical scroll bar visible at fractional content scale

### LINKED ISSUE #89482: Vertical scrollbar is visible in all popup menus when using a custom display scale
### Tested versions

v4.3.dev.custom_build [da945ce62]

Wasn't happening in 4.2.1

### System information

Godot v4.3.dev (da945ce62) - macOS 14.2.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

It's like this in every popup menu:

image<br>

**_EDIT: Correction, this has nothing to do with a theme, this is with no theme:_**

image

### Steps to reproduce

~~Use [this theme](https://github.com/passivestar/godot-minimal-theme) with 4.3~~

~~This might be mac-specific because I asked another person and found out that it's not happening on windows~~

Open 4.3 and set custom display scale to 1.6

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Koyper**
Fixes #89482

### CODE REVIEW

**Comment by passivestar** [comment]
Works, thanks 🤍

File: scene/gui/popup_menu.cpp [hunk 1]
```diff
@@ -276,6 +276,7 @@ Size2 PopupMenu::_get_contents_minimum_size() const {
 		}
 	}
 
+	minsize.height = minsize.ceil().height; // Ensures enough height at fractional content scales to prevent the v_scroll_bar from showing.
```
Comment (akien-mga) [inline scene/gui/popup_menu.cpp:279]: Nitpick, but isn't it enough to just ceil the y component?
```suggestion
	// Ensures enough height at fractional content scales to prevent the v_scroll_bar from showing.
	minsize.height = Math::ceil(minsize.height);
```

Comment (Koyper) [reply scene/gui/popup_menu.cpp:279]: Not a nitpick - it's a good suggestion! Will do...

**Review by akien-mga — APPROVED** [review]

**Comment by Koyper** [comment]
Can someone advise on why the Editor unit test checks failed? I don't see how this PR is related to them.

**Comment by akien-mga** [comment]
It's a temporary issue due to conflicting merges. You can rebase to fix it.

**Comment by Koyper** [comment]
I've managed to farkle this branch with a rebase mistake. Is there a way to revert to the prior state?

**Comment by fire** [comment]
`git checkout -f https://github.com/godotengine/godot/commit/ea2335d2a09aaabbedd9b267532173f6d7d0eb80`

**Comment by Koyper** [comment]
> `git checkout -f ea2335d2a09aaabbedd9b267532173f6d7d0eb80`

Now the force push says "Everything up-to-date" - how do I override that? Is it because of the detatched head?

**Comment by KoBeWi** [comment]
You can push with `--set-upstream` to your branch.

**Comment by Koyper** [comment]
> You can push with `--set-upstream` to your branch.

Will this work while in my current detached head state?

Like this?:

`git push --set-upstream --force origin fix_popup_menu_incorrect_v_scrollbar`

**Comment by akien-mga** [comment]
> `git reset --hard ea2335d2a09aaabbedd9b267532173f6d7d0eb80`

This is the way IMO, after checking out your local branch.

**Comment by Koyper** [comment]
> > `git reset --hard ea2335d2a09aaabbedd9b267532173f6d7d0eb80`
> 
> This is the way IMO, after checking out your local branch.

Okay, this worked! Good grief 😡.
