### PR TITLE
Fix Window position preview in the editor.

### LINKED ISSUE #92314: Editor: Window node: position preview ignores screen-relative initial position, still uses Absolute position even though hidden - resets to wrong position after hide & show
### Tested versions

- Reproducible in v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 860M (nvidia; 535.161.07) - Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 Threads)

### Issue description

When editing a Window (or subclass like AcceptDialog), editor should auto-preview position in game by checking the Initial Position.

It works in Absolute mode, where the window can be moved around:

image

When switching to another mode, relative to a screen, such as Center of Primary Screen, the position is not updated:

image

It's not set to center of expected screen using the current application settings (display/window/size/viewport_width & viewport_height), nor reset to 0, it just keeps using the Absolute Position although the field is hidden, which looks weird.

Of course we cannot predict all sorts of screens, but at least previewing position at the center of the current expected viewport would be a good improvement.

Or, we could let the user freely modify some debug position, that would be shown instead of Absolute Position. In this case I'd suggest also unlocking the Move tool to let the user move the window visually with the mouse, and it would affect that debug position instead of the usual position 2D (only available for Node2D and Control, not Viewport subclass nodes like Window).

### Steps to reproduce

1. Create a Window
2. Modify Initial Position in Absolute mode
3. Switch to another mode like Center of Primary Screen
4. See how position remains unchanged

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/92314

### CODE REVIEW

File: scene/main/window.cpp [hunk 1]
```diff
@@ -1265,6 +1281,12 @@ void Window::_notification(int p_what) {
 		} break;
 
 		case NOTIFICATION_ENTER_TREE: {
+			if (is_in_edited_scene_root()) {
+				if (!ProjectSettings::get_singleton()->is_connected("settings_changed", callable_mp(this, &Window::_settings_changed))) {
+					ProjectSettings::get_singleton()->connect("settings_changed", callable_mp(this, &Window::_settings_changed));
+				}
+			}
```
Comment (akien-mga) [inline scene/main/window.cpp:1288]: Should we disconnect it too on `EXIT_TREE`?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
