### PR TITLE
Fixing incorrect normal map when using triplanar world mapping and mesh rotation

### LINKED ISSUE #82311: Triplanar World mapping - incorrect normal direction for normal map
### Godot version

4.1.1 stable

### System information

Windows 10

### Issue description

When setting up a material using triplanar world mapping, the normal map is correctly rotated and applied.
However, the direction that the light is calculated is screwed.

**Here is the expected behaviour in Godot 3.5.2:**

https://github.com/godotengine/godot/assets/9423774/d8f0d600-cd73-4435-85f1-227922060150

**Here is the current, bugged behaviour:**

https://github.com/godotengine/godot/assets/9423774/8f639c3c-be89-4993-97c8-bc55d13a5fb7

### Steps to reproduce

- Create a mesh (e.g. plane)
- Place a light source
- Create a new material
- Under UV1 use the following settings:
image
- Rotate the mesh

### Minimal reproduction project

[triplanar-world-normalmaps.zip](https://github.com/godotengine/godot/files/12717396/triplanar-world-normalmaps.zip)

### PR DESCRIPTION
**Pull request by RPicster**
Fixes #82311

On the original PRs (#82317) branch I unfortunately did a dumb move and it was faster moving the commit to a new branch. Sorry for the extra work @clayjohn @AThousandShips 

This PR includes the feedback that @clayjohn gave on the original PR.

### CODE REVIEW

File: scene/resources/material.cpp [hunk 1]
```diff
@@ -1062,12 +1062,19 @@ void BaseMaterial3D::_update_shader() {
 		code += "	TANGENT = vec3(0.0,0.0,-1.0) * abs(NORMAL.x);\n";
 		code += "	TANGENT+= vec3(1.0,0.0,0.0) * abs(NORMAL.y);\n";
 		code += "	TANGENT+= vec3(1.0,0.0,0.0) * abs(NORMAL.z);\n";
-		code += "	TANGENT = normalize(TANGENT);\n";
-
+		if (flags[FLAG_UV1_USE_WORLD_TRIPLANAR]) {
+			code += "	TANGENT = normalize(TANGENT) * MODEL_NORMAL_MATRIX;\n";
+		} else {
+			code += "	TANGENT = normalize(TANGENT);\n";
+		}
```
Comment (AThousandShips) [inline scene/resources/material.cpp:1069]:
```suggestion
		}

```
Leave an empty line after this to group

**Comment by clayjohn** [comment]
It looks like you missed [my comment](https://github.com/godotengine/godot/pull/82317#pullrequestreview-1661043841) in the original PR. 

For ease of reference, the correct code (for world space) is:
```
vec3 normal = MODEL_NORMAL_MATRIX * NORMAL;
TANGENT = vec3(0.0,0.0,-1.0) * abs(normal.x);
TANGENT+= vec3(1.0,0.0,0.0) * abs(normal.y);
TANGENT+= vec3(1.0,0.0,0.0) * abs(normal.z);
TANGENT = inverse(MODEL_NORMAL_MATRIX)* normalize(TANGENT);
BINORMAL = vec3(0.0,1.0,0.0) * abs(normal.x);
BINORMAL+= vec3(0.0,0.0,-1.0) * abs(normal.y);
BINORMAL+= vec3(0.0,1.0,0.0) * abs(normal.z);
BINORMAL = inverse(MODEL_NORMAL_MATRIX)* normalize(BINORMAL);
```

You can't rely on the post-multiplication trick like in this PR as it only works for planes.

File: scene/resources/material.cpp (hunk 1 above)
Comment (RPicster) [reply scene/resources/material.cpp:1069]: Why?

Comment (AThousandShips) [reply scene/resources/material.cpp:1069]: Because it's a separate group of values, and you removed such an existing line in the original code, it was:
```cpp
		code += "	TANGENT = vec3(0.0,0.0,-1.0) * abs(NORMAL.x);\n";
		code += "	TANGENT+= vec3(1.0,0.0,0.0) * abs(NORMAL.y);\n";
		code += "	TANGENT+= vec3(1.0,0.0,0.0) * abs(NORMAL.z);\n";
		code += "	TANGENT = normalize(TANGENT);\n";

		code += "	BINORMAL = vec3(0.0,1.0,0.0) * abs(NORMAL.x);\n";
		code += "	BINORMAL+= vec3(0.0,0.0,-1.0) * abs(NORMAL.y);\n";
		code += "	BINORMAL+= vec3(0.0,1.0,0.0) * abs(NORMAL.z);\n";
		code += "	BINORMAL = normalize(BINORMAL);\n";
```

Much easier to read with the space

Comment (RPicster) [reply scene/resources/material.cpp:1069]: Thanks for the explanation, I'll fix it!

File: scene/resources/material.cpp [hunk 2]
```diff
@@ -1059,20 +1059,34 @@ void BaseMaterial3D::_update_shader() {
...
+			code += "	vec3 normal = MODEL_NORMAL_MATRIX * NORMAL;\n";
+		} else {
+			code += "	vec3 normal = NORMAL;\n";
+		}
+		code += "	vec3 normal = MODEL_NORMAL_MATRIX * NORMAL;\n";
+		code += "	TANGENT = vec3(0.0,0.0,-1.0) * abs(normal.x);\n";
+		code += "	TANGENT+= vec3(1.0,0.0,0.0) * abs(normal.y);\n";
+		code += "	TANGENT+= vec3(1.0,0.0,0.0) * abs(normal.z);\n";
+		if (flags[FLAG_UV1_USE_WORLD_TRIPLANAR]) {
+			code += "	TANGENT = normalize(TANGENT) * inverse(MODEL_NORMAL_MATRIX);\n";
```
Comment (clayjohn) [inline scene/resources/material.cpp:1072]:
```suggestion
			code += "	TANGENT = inverse(MODEL_NORMAL_MATRIX) * normalize(TANGENT);\n";
```

When multiplying by a matrix, the order of multiplication matters so ``X * Y`` is not the same as ``Y * X``. In this case, the matrix needs to be on the left hand side

File: scene/resources/material.cpp [hunk 3]
```diff
@@ -1059,20 +1059,34 @@ void BaseMaterial3D::_update_shader() {
...
 
-		code += "	BINORMAL = vec3(0.0,1.0,0.0) * abs(NORMAL.x);\n";
-		code += "	BINORMAL+= vec3(0.0,0.0,-1.0) * abs(NORMAL.y);\n";
-		code += "	BINORMAL+= vec3(0.0,1.0,0.0) * abs(NORMAL.z);\n";
-		code += "	BINORMAL = normalize(BINORMAL);\n";
+		code += "	BINORMAL = vec3(0.0,1.0,0.0) * abs(normal.x);\n";
+		code += "	BINORMAL+= vec3(0.0,0.0,-1.0) * abs(normal.y);\n";
+		code += "	BINORMAL+= vec3(0.0,1.0,0.0) * abs(normal.z);\n";
+		if (flags[FLAG_UV1_USE_WORLD_TRIPLANAR]) {
+			code += "	BINORMAL = normalize(BINORMAL) * inverse(MODEL_NORMAL_MATRIX);\n";
```
Comment (clayjohn) [inline scene/resources/material.cpp:1081]:
```suggestion
			code += "	BINORMAL = inverse(MODEL_NORMAL_MATRIX) * normalize(BINORMAL);\n";
```
Same here

File: scene/resources/material.cpp (hunk 2 above)
Comment (RPicster) [reply scene/resources/material.cpp:1072]: Thanks!

**Review by clayjohn — APPROVED** [review]
Looks great to me!

File: scene/resources/material.cpp [hunk 4]
```diff
@@ -1059,20 +1059,34 @@ void BaseMaterial3D::_update_shader() {
...
-		code += "	TANGENT = vec3(0.0,0.0,-1.0) * abs(NORMAL.x);\n";
-		code += "	TANGENT+= vec3(1.0,0.0,0.0) * abs(NORMAL.y);\n";
-		code += "	TANGENT+= vec3(1.0,0.0,0.0) * abs(NORMAL.z);\n";
-		code += "	TANGENT = normalize(TANGENT);\n";
+		if (flags[FLAG_UV1_USE_WORLD_TRIPLANAR]) {
+			code += "	vec3 normal = MODEL_NORMAL_MATRIX * NORMAL;\n";
+		} else {
+			code += "	vec3 normal = NORMAL;\n";
+		}
+		code += "	vec3 normal = MODEL_NORMAL_MATRIX * NORMAL;\n";
```
Comment (AThousandShips) [inline scene/resources/material.cpp:1067]: You're declaring `normal` twice here

**Review by AThousandShips — CHANGES_REQUESTED** [review]

File: scene/resources/material.cpp [hunk 5]
```diff
@@ -1059,20 +1059,34 @@ void BaseMaterial3D::_update_shader() {
...
+			code += "	BINORMAL = inverse(MODEL_NORMAL_MATRIX) * normalize(BINORMAL);\n";
+		} else {
+			code += "	BINORMAL = normalize(BINORMAL);\n";
+		}
 	}
 
 	if (flags[FLAG_UV1_USE_TRIPLANAR]) {
 		if (flags[FLAG_UV1_USE_WORLD_TRIPLANAR]) {
-			code += "	uv1_power_normal=pow(abs(mat3(MODEL_MATRIX) * NORMAL),vec3(uv1_blend_sharpness));\n";
+			code += "	uv1_power_normal=pow(abs(normal),vec3(uv1_blend_sharpness));\n";
```
Comment (AThousandShips) [inline scene/resources/material.cpp:1089]: You're replacing this here, but not below in the `UV2` case

Comment (clayjohn) [reply scene/resources/material.cpp:1089]: ``normal`` should only be a drop in replacement when ``FLAG_UV1_USE_WORLD_TRIPLANAR`` is used. UV2 has its own logic and isn't necessarily the same. 

Also, to be clear, this change doesn't change behaviour anyway. ``mat3(MODEL_MATRIX) * NORMAL`` is the same as ``MODEL_NORMAL_MATRIX * NORMAL``

Comment (AThousandShips) [reply scene/resources/material.cpp:1089]: Goot to have cleared up!

File: scene/resources/material.cpp (hunk 4 above)
Comment (RPicster) [reply scene/resources/material.cpp]: Good catch, thanks!

**Review by AThousandShips — APPROVED** [review]
Can't speak for the functionality but the style looks good!

**Comment by akien-mga** [comment]
Thanks!

**Comment by RPicster** [comment]
> > Don't merge yet, I'll do some testing first 😅
> 
> Welp I didn't see this, just two approvals :) You can mark PRs as drafts to prevent from merging them (and then turn them back to ready to review/merge once done).

Argh 🙈

But today is our lucky day! I just tested everything and it works perfectly ⭐
