### PR TITLE
AssetLib pagination modifications

### LINKED ISSUE #15705: Misaligned page navigation
**Godot version:**

Build date: 2018-01-13 19:42:27
Git commit id (short): c01575b31

**OS/device including version:**

Win10 64 bits

**Issue description:**

Page navigation : numbers and texts aren't correctly aligned.
See this : 

**Steps to reproduce:**
Just open AssetLib in Godot editor.

### PR DESCRIPTION
**Pull request by TailyFair**
Indirectly fixes https://github.com/godotengine/godot/issues/15705

Clicking on single character links are difficult, so changed them into buttons. 
Removed cryptic totals line.
Made navigation buttons always visible, so whole pagination doesn't shift when navigating pages.

Old and new comparison.
pagination

### CODE REVIEW

**Review by djrm — APPROVED** [review]
This looks nice.

**Comment by Calinou** [comment]
I think it would be better to write "Previous" in full rather than just "prev". Also, button labels should be capitalized.

**Comment by akien-mga** [comment]
It's OK to change the strings for 3.1, translators will have some time to check the new strings.

**Comment by TailyFair** [comment]
Capitalized navigation buttons. Should be good now.

**Comment by groud** [comment]
LGTM

File: editor/plugins/asset_library_editor_plugin.cpp [hunk 1]
```diff
@@ -936,70 +936,70 @@ HBoxContainer *EditorAssetLibrary::_make_pages(int p_page, int p_page_count, int
...
 		first->connect("pressed", this, "_search", varray(0));
-		hbc->add_child(first);
+	} else {
+		first->set_disabled(true);
+		first->set_focus_mode(Control::FOCUS_NONE);
 	}
+	hbc->add_child(first);
 
+	Button *prev = memnew(Button);
+	prev->set_text(TTR("Prev"));
```
Comment (Calinou) [inline editor/plugins/asset_library_editor_plugin.cpp]: What about using Previous instead of Prev? This may confuse translators who may not know whether to abbreviate the translated word or not.

Comment (TailyFair) [reply editor/plugins/asset_library_editor_plugin.cpp]: I think initially it was made, to make everything symmetrical. I agree that `previous` would look more profesional, but not as symmetrical.
image

**Comment by TailyFair** [comment]
Changed `prev` into `Previous`.
Although `prev` made symmetry in English locale, I don't think it's important enough to confuse translators or potentially users. And that symmetry only occurs in English anyway.

image

**Comment by akien-mga** [comment]
Thanks!
