### PR TITLE
[TextEdit] Draw guidelines under the text and caret.

### LINKED ISSUE #92238: Script editor cuts off certain characters with vertical lines due to line length guideline appearing in front
### Tested versions

Reproduced in 4.2

### System information

Godot v4.2.2.stable.mono - Ubuntu 23.10 23.10 - Wayland - Vulkan (Forward+) - integrated Intel(R) HD Graphics 4400 (HSW GT2) () - Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 Threads)

### Issue description

Vertical lines in the script editor cuts off letters on that line (see image for example). I don't know why the lines are there (maybe preferred line length, like in Python?)

The vertical line seems to overwrite the lines of the letters. This only applies to small font sizes, where I assume the width of a vertical line is either smaller or equal to the width of a vertical line.
image

### Steps to reproduce

Open a new text file, start typing until lines appear, zoom out until the vertical line cuts off letters.

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #108481: Caret not visible in code editor when it is at same position as the line length guideline for hard column.
### Tested versions

Godot v4.5.beta2 and 4.4.1

### System information

Fedora Linux 42 (KDE Plasma Desktop Edition) on Wayland - X11 display driver

### Issue description

Caret not visible in code editor when it is at same position as the line length guideline for hard column.

https://github.com/user-attachments/assets/f4533573-2a0e-458f-94ec-2e0088b354f5

When placed at the soft column it doesn't get invisible but it gets a bit harder to see.

### Steps to reproduce

Write a line so the caret ends up at the line length guideline for hard column.

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/92238
Fixes https://github.com/godotengine/godot/issues/108481

Adds an internal virtual method to draw guidelines in the middle of `TextEdit` draw instead of using own `DRAW`.

Before:
Screenshot 2025-07-14 at 10 49 29

After:
Screenshot 2025-07-14 at 10 51 09

### CODE REVIEW

**Comment by KoBeWi** [comment]
Guidelines are something specific to CodeEdit, no? The new method could have more generic name, like `_background_draw()` or something. But it's internal, so it can always be renamed I suppose.

**Comment by bruvzg** [comment]
> Guidelines are something specific to CodeEdit, no?

Yes, but I can't think of anything else that cab be drawn between background and text.

> like _background_draw() or something.

It's not on the background, so not sure what the beast name would be.

File: scene/gui/code_edit.cpp [hunk 1]
```diff
@@ -280,6 +261,30 @@ void CodeEdit::_notification(int p_what) {
 	}
 }
 
+void CodeEdit::_draw_guidelines() {
+	RID ci = get_canvas_item();
+	const Size2 size = get_size();
+	const bool rtl = is_layout_rtl();
+
+	if (line_length_guideline_columns.size() > 0) {
```
Comment (KoBeWi) [inline scene/gui/code_edit.cpp]:
```suggestion
	if (!line_length_guideline_columns.is_empty()) {
```
Also it could be an early return.

File: scene/gui/text_edit.cpp [hunk 2]
```diff
@@ -1304,6 +1304,9 @@ void TextEdit::_notification(int p_what) {
 				bottom_limit_y -= theme_cache.style_normal->get_margin(SIDE_BOTTOM);
 			}
 
+			// Draw fuidelines.
```
Comment (KoBeWi) [inline scene/gui/text_edit.cpp]:
```suggestion
			// Draw guidelines.
```
Although the comment just repeats method name, so it's not really useful.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
