### PR TITLE
Display project settings splash color on web export

### LINKED ISSUE #96874: Changing the Boot Splash background color does not reflect in the web export
### Tested versions

Godot_v4.3-stable_win64

### System information

Windows 10 Pro - Godot_v4.3-stable_win64 - Compatibility 

### Issue description

Changing the Boot Splash background color does not reflect in the web export. I even tried to Run directly from the Editor but same result. (Run in Browser). 
or Export Web build and Check Background

### Steps to reproduce

Project Settings -> Application -> Boot Splash -> BG Color -> Set any Color 
This change project.godot -> boot_splash/bg_color=Color(1, 0, 0, 1)

Run directly from Editor but same result. 

### Minimal reproduction project (MRP)

[bootsplashbgcolor.zip](https://github.com/user-attachments/files/16969162/bootsplashbgcolor.zip)

### PR DESCRIPTION
**Pull request by elpozewaunig**
This is a minor improvement to the new web export splash screen, which now displays the correct splash color specified in the project settings as the background, as was mentioned in #91852.

I've been a fan of Godot for quite some time now and have been using it for hobby projects, as well as convincing friends to try it. I don't have much experience with the inner workings of the engine, or C++ for that matter but I got very excited to find that I can help out with small additions too ;). My changes have been tested locally and work as expected but since this is my very first contribution to Godot, I'd appreciate a thorough check and I hope that everything is alright!

* *Bugsquad edit, closes: https://github.com/godotengine/godot/issues/96874*

### CODE REVIEW

**Review by Calinou — COMMENTED** [review]
Looks good to me.

One concern however is that there's compatibility breakage for custom HTML shells, since `$GODOT_SPLASH` was renamed to `$GODOT_SPLASH_IMAGE`. It's probably not a dealbreaker and is unavoidable here, but it should be highlighted in the release notes and the upgrade guide.

**Comment by timothyqiu** [comment]
We can keep `$GODOT_SPLASH` as-is, or provide `$GODOT_SPLASH` along with `$GODOT_SPLASH_IMAGE` for compatibility.

**Comment by elpozewaunig** [comment]
Both can work, but keeping `$GODOT_SPLASH` the way it is requires a specific order in the `replaces` HashMap for it not to break the `$GODOT_SPLASH_COLOR` placeholder. I think it is also more intuitive to name them more similarly to the project settings they apply, so if we want to keep the compatibility, providing it alongside `$GODOT_SPLASH_IMAGE` might be the better way to go.

**Comment by elpozewaunig** [comment]
Has there been any decision yet as to how we should proceed regarding compatibility? I'm happy to make any changes needed.

File: platform/web/export/export_plugin.cpp [hunk 1]
```diff
@@ -170,7 +170,8 @@ void EditorExportPlatformWeb::_fix_html(Vector<uint8_t> &p_html, const Ref<Edito
 	replaces["$GODOT_PROJECT_NAME"] = GLOBAL_GET("application/config/name");
 	replaces["$GODOT_HEAD_INCLUDE"] = head_include + custom_head_include;
 	replaces["$GODOT_CONFIG"] = str_config;
-	replaces["$GODOT_SPLASH"] = p_name + ".png";
+	replaces["$GODOT_SPLASH_IMAGE"] = p_name + ".png";
+	replaces["$GODOT_SPLASH_COLOR"] = "#" + Color(GLOBAL_GET("application/boot_splash/bg_color")).to_html(false);
```
Comment (adamscott) [inline platform/web/export/export_plugin.cpp:174]:
```suggestion
	replaces["$GODOT_SPLASH"] = p_name + ".png";
	replaces["$GODOT_SPLASH_COLOR"] = "#" + Color(GLOBAL_GET("application/boot_splash/bg_color")).to_html(false);
```

File: misc/dist/html/full-size.html [hunk 2]
```diff
@@ -88,7 +88,7 @@
 		</noscript>
 
 		<div id="status">
-			<img id="status-splash" src="$GODOT_SPLASH" alt="">
+			<img id="status-splash" src="$GODOT_SPLASH_IMAGE" alt="">
```
Comment (adamscott) [inline misc/dist/html/full-size.html:91]:
```suggestion
			<img id="status-splash" src="$GODOT_SPLASH" alt="">
```

See my other comment.

**Review by adamscott — COMMENTED** [review]
Even if I like up-to-date code, it doesn't warrant breaking compatibility, really.

> Both can work, but keeping `$GODOT_SPLASH` the way it is requires a specific order in the `replaces` HashMap for it not to break the `$GODOT_SPLASH_COLOR` placeholder.

I don't understand how it could break.

> Has there been any decision yet as to how we should proceed regarding compatibility?

Sorry for the delay! Don't hesitate to join the [developers' chat](https://chat.godotengine.org/) [\#Web channel](https://chat.godotengine.org/channel/web) in order to discuss topics.

**Comment by elpozewaunig** [comment]
> I don't understand how it could break.

If `$GODOT_SPLASH` is replaced before `$GODOT_SPLASH_COLOR`, it changes the "$GODOT_SPLASH_COLOR" string in the CSS to e.g. "splashimage.png_COLOR", breaking the value and preventing the correct replacement (since the placeholder string doesn't exist in the CSS anymore). I just realised my initial assessment was likely wrong too (though I can't test it currently) - changing the order in the code wouldn't reliably work either, since we're dealing with a HashMap. If we want to revert back to the old name, we would either have to rename `$GODOT_SPLASH_COLOR` so that `$GODOT_SPLASH` is no longer a prefix, or change the implementation of the replacement.

> Even if I like up-to-date code, it doesn't warrant breaking compatibility, really.

I agree! I was under the impression that strict compatibility preservation is only done for the API, not for the export system, which is why I didn't think of this problem.

> Sorry for the delay! Don't hesitate to join the [developers' chat](https://chat.godotengine.org/) [#Web channel](https://chat.godotengine.org/channel/web) in order to discuss topics.

Done, much appreciated!

**Comment by elpozewaunig** [comment]
I just realised that my rebase seems to have caused review requests to be sent to all code owner teams affected by changes since I opened this PR - I'm very sorry for this!

**Comment by adamscott** [comment]
> * Keep the old name, change the order so that `$GODOT_SPLASH` is after `$GODOT_SPLASH_COLOR`

Yes. This is the simplest solution.

**Comment by elpozewaunig** [comment]
Alright, I made the change now! I hope we can eventually move to a variable name that matches the project settings since relying on the order seems a little fragile to me but for now, I think this is good to merge! Let me know if there's anything else I should change and thank you for taking the time to review this PR. :)

**Review by adamscott — APPROVED** [review]

**Comment by Repiteo** [comment]
Please squash your commits into one, see [the interactive rebase](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for details

**Comment by elpozewaunig** [comment]
@Repiteo Done! Sorry for the inconvenience!

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first contribution! 🎉
