### PR TITLE
Fix CSGShape `debug_collision_shape` crash

### LINKED ISSUE #84304: Making a CSG Mesh visible again crashes Godot 4.2 beta4
### Godot version

4.2-beta4

### System information

Windows 10 - Godot 4.2 beta4 - NVIDIA GForce GTX 970 - Forward+

### Issue description

Switching visibility of a CSG Mesh back to visible makes Godot to crash.

This was not the case in beta3 or previous ones.

It could be related to #84174 of @jsjtxietian (merged by @akien-mga) as it touches [modules/csg/csg_shape.cpp](https://github.com/godotengine/godot/pull/84174/commits/173e2c7f29c6d4304bf02f895082a34cf30c0908#diff-a81f2e3a53dfacfdb0037de9538db28d5646ae0c3a11a52eca1caa5d665dfd1c).

### Steps to reproduce

In a simple 3D, adding any CSG mesh, hiding node, then showing it back crashes editor.

In example project, I put an editor script in order to test by script ; here is awaited output : 

hiding : MeshInstance3D OK
showing : MeshInstance3D OK
hiding : CSGMesh3D OK
showing : CSGMesh3D OK
hiding : CSGBox3D OK
showing : CSGBox3D OK

### Minimal reproduction project

[4.2-beta4-csg-mesh-visbility-bug.zip](https://github.com/godotengine/godot/files/13226896/4.2-beta4-csg-mesh-visbility-bug.zip)

### PR DESCRIPTION
**Pull request by smix8**
Fixes CSGShape debug_collision_shape crash.

Fixes https://github.com/godotengine/godot/issues/84304

While the immediate crash source was `root_collision_shape` being null I also do not trust a function that does not guard itself against crashes from e.g. `get_world_3d()` or `get_global_transform()`. In fact the only guard was a well-meaning comment.

### CODE REVIEW

**Review by jsjtxietian — COMMENTED** [review]
What about print some warning with the origin comment as it's content ?

File: modules/csg/csg_shape.cpp [hunk 1]
```diff
@@ -488,7 +488,9 @@ bool CSGShape3D::_is_debug_collision_shape_visible() {
 }
 
 void CSGShape3D::_update_debug_collision_shape() {
-	// NOTE: This is called only for the root shape with collision, when root_collision_shape is valid.
+	if (!(use_collision && is_root_shape() && root_collision_shape.is_valid() && _is_debug_collision_shape_visible())) {
```
Comment (AThousandShips) [inline modules/csg/csg_shape.cpp:491]:
```suggestion
	if (!use_collision || !is_root_shape() || !root_collision_shape.is_valid() || !_is_debug_collision_shape_visible()) {
```
IMO the leading `!` is hard to notice when skimming the code

**Comment by smix8** [comment]
> What about print some warning with the origin comment as it's content ?

I am not sure. Do people benefit from a printed warning here  about this?
The original comment was a code comment, not directed or with useful information for engine users in particular.

**Review by AThousandShips — APPROVED** [review]
Haven't verified but should cover the cases (the validity of `get_world_3d` should be covered by the `is_inside_tree` check, but might be incomplete)

**Review by YuriSizov — APPROVED** [review]
Seems in line with other checks in this class, if not a bit excessive.

**Comment by YuriSizov** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Should be cherry picked, see:
* https://github.com/godotengine/godot/issues/89640

**Comment by akien-mga** [comment]
Cherry-picked for 4.1.4.
