### PR TITLE
Fix particles resetting properties when emitting is toggled

### LINKED ISSUE #104511: GPUParticles3D resize when is_emitting is toggled
### Tested versions

- reproducible in 4.4 stable, 4.4 rc1, 4.4 rc2, 4.5 dev1
- not reproducible in 4.3 stable

### System information

Windows 10 - Vulkan (Forward+)  GeForce GTX 1080 

### Issue description

GPU particle 3D instances resize if size randomization is adjusted and is_emitting is toggled ( see [screenshot of settings](https://github.com/krautdev/GODOT_4.4_GPUparticles_resize_bug/blob/main/Screenshot%202025-03-23%20094603.png) and [gif](https://github.com/krautdev/GODOT_4.4_GPUparticles_resize_bug/blob/main/gpuparticles_size_broken__4_4.gif) )

### Steps to reproduce

Create a new GPU particles node, add a material, add a drawing pass. Adjust the scale settings in the material (inspector: GPUParticles3D -> Process Material -> Scale). Then turn "Emitting" Off and on again.

### Minimal reproduction project (MRP)

[projects for 4.3 and 4.4](https://github.com/krautdev/GODOT_4.4_GPUparticles_resize_bug/blob/main/gpuparticles_size_broken.rar)

### LINKED ISSUE #107575: GPUParticles2D resize when `emitting` is enabled
### Tested versions

Reproducible in v4.5.dev.custom_build [1218a16de]

### System information

Godot v4.5.dev (1218a16de) - macOS Sequoia (15.5.0) - Multi-window, 2 monitors - OpenGL 3 (Compatibility) - Apple M4 Pro - Apple M4 Pro (14 threads) - 24.00 GiB memory

### Issue description

When setting the `emitting` property of a GPUParticles2D node to `true`, the size of existing particles appears to be re-calculated. This has a very jarring effect.

https://github.com/user-attachments/assets/f8241c7b-1e67-435c-9569-6c8307764ce2

As I was preparing to file this report, I found https://github.com/godotengine/godot/issues/104511 which sounds like basically the same problem, except with the 3D particle system instead of the 2D one. A merged PR that sounds like it should've fixed the issue, including for GPUParticles2D, is linked there, but for me it seems the issue persists (or is a different one).

### Steps to reproduce

Create a GPUParticles2D system with a ParticleProcessMaterial where the display scale has a range. Disable `emitting`, then re-enable it; any particles that were already there will change their scale instantaneously.

### Minimal reproduction project (MRP)

[test-emitting-particles-wrong_2025-06-15_15-29-49.zip](https://github.com/user-attachments/files/20747817/test-emitting-particles-wrong_2025-06-15_15-29-49.zip)

Run this MRP, and press the Enter key to toggle the particle system's emission. When emission is enabled, you should see the scale of the on-screen particles change randomly, as seen in the video above.

### PR DESCRIPTION
**Pull request by QbieShay**
Fixes https://github.com/godotengine/godot/issues/107575
Fixes https://github.com/godotengine/godot/issues/104511

### CODE REVIEW

File: scene/2d/gpu_particles_2d.cpp [hunk 1]
```diff
@@ -491,7 +491,7 @@ float GPUParticles2D::get_amount_ratio() const {
 }
 
 void GPUParticles2D::restart(bool p_keep_seed) {
-	if (!p_keep_seed && !use_fixed_seed) {
+	if (!p_keep_seed && !use_fixed_seed && one_shot) {
```
Comment (clayjohn) [inline scene/2d/gpu_particles_2d.cpp]: Should this change be made for `GPUParticles3D` as well?

Comment (QbieShay) [reply scene/2d/gpu_particles_2d.cpp]: actually that's an oversight and shouldn't be there

**Review by Ansraer — APPROVED** [review]

**Review by Meorge — APPROVED** [review]
Tested with both my MRP and main project where I originally experienced the issue, and both are working now! Thanks so much for this fix!

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
