### PR TITLE
Fix GraphNode frag/vert port positions misaligned

### LINKED ISSUE #105232: Visual Shader Nodes connections are visually connected to the headers rather than ports
### Tested versions

From 4.5 dev1 to latest master (c374ce211c00279ac4a69aaaa12b5ff12d7cf6da)

### System information

Windows 11

### Issue description

Detected visual bug:

Image

### Steps to reproduce

^^

Happens even on existed visual shaders.

### Minimal reproduction project (MRP)

Too easy to reproduce.

### PR DESCRIPTION
**Pull request by ytianle**
Issue conclusion: GraphNode port connections appear misaligned when switching between vertex and fragment modes, only realigning after zoom or layout refresh.

Investigation: The root cause was due to port positions being calculated before child layouts had been finalized, resulting in inaccurate Y positions for ports. The original implementation relied on Control::position.y, which was not yet updated during the initial layout pass.

Explanation: This fix computes vertical offset using titlebar and stylebox sizes instead, ensuring port alignment is correct immediately after layout, without relying on zoom-triggered re-layouts.

Resolves: #105232

### CODE REVIEW

**Comment by yuantianle** [comment]
Demoing :
image

File: scene/gui/graph_node.cpp [hunk 1]
```diff
@@ -980,42 +980,52 @@ Size2 GraphNode::get_minimum_size() const {
 
 void GraphNode::_port_pos_update() {
 	int edgeofs = theme_cache.port_h_offset;
+	int separation = theme_cache.separation;
+
+	Ref<StyleBox> sb_panel = theme_cache.panel;
+	Ref<StyleBox> sb_titlebar = theme_cache.titlebar;
```
Comment (KoBeWi) [inline scene/gui/graph_node.cpp:986]: You don't need these variables. You could just use the cache values directly.

File: scene/gui/graph_node.cpp [hunk 2]
```diff
@@ -980,42 +980,52 @@ Size2 GraphNode::get_minimum_size() const {
...
-				port_cache.color = slot_table[slot_index].color_left;
-				port_cache.slot_index = slot_index;
-				left_port_cache.push_back(port_cache);
+		Size2 size = child->get_size();
+
+		if (slot_table.has(slot_count)) {
+			const Slot &slot = slot_table[slot_count];
+
+			int port_y;
+			bool is_using_resort_layout = slot_y_cache.is_empty();
```
Comment (KoBeWi) [inline scene/gui/graph_node.cpp:1008]: Also not needed. It's short and referenced only once.

**Review by KoBeWi — APPROVED** [review]

File: scene/gui/graph_node.cpp (hunk 2 above)
Comment (yuantianle) [reply scene/gui/graph_node.cpp:1008]: Can you elaborate your comment for this? Which lines are not necessary? Thanks!

Comment (KoBeWi) [reply scene/gui/graph_node.cpp]: 1008 (`is_using_resort_layout`)
I see you already handled it.

**Comment by KoBeWi** [comment]
Needs to be squashed into single commit.

**Comment by yuantianle** [comment]
Now there is one commit record. Sorry, the force-push was for solving the mistake. I merged a backup branch into the current. But I have already reverted it.

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉

**Comment by yuantianle** [comment]
Thank you, @Repiteo!
