### PR TITLE
Make the script search have a proper matches counter

### LINKED ISSUE #29234: Closing Search bar will remove error message
**Godot version:**
3.1.1

**Issue description:**
When there's error in script editor and you close search bar, the message disappears and you no longer know what is wrong.

**Steps to reproduce:**
1. Write some bad code, so error appears
2. Open search bar
3. Close the search bar
4. Error message disappears and there's no way to bring it back
image

### PR DESCRIPTION
**Pull request by YeldhamDev**
A little tight on the fit, but still usable and a better alternative than showing it in the error messages section:
Screenshot_20190809_113549

Fixes #29234.

### CODE REVIEW

File: editor/code_editor.cpp [hunk 1]
```diff
@@ -332,6 +332,24 @@ void FindReplaceBar::_update_results_count() {
...
+		matches_label->add_color_override("font_color", Color(1, 1, 1));
+		matches_label->set_text(vformat(TTR("%d match(es)."), results_count));
+	} else if (search_text->get_text().empty()) {
+
+		matches_label->hide();
+	} else {
+		matches_label->show();
+
+		matches_label->add_color_override("font_color", EditorNode::get_singleton()->get_gui_base()->get_color("error_color", "Editor"));
+		matches_label->set_text(TTR("No Matches"));
```
Comment (akien-mga) [inline editor/code_editor.cpp]: I think the M should likely be lowercase here, it's not a button/title label but a "normal" sentence.

**Comment by KoBeWi** [comment]
Wouldn't it make sense to update matches label in `update_results_count()`? The count isn't used for anything else anyways.

**Comment by YeldhamDev** [comment]
@KoBeWi They are in separate functions because `_update_results_count()` doesn't need to be called if nothing is found.

**Comment by Calinou** [comment]
Looks good to me :slightly_smiling_face:

Maybe the match counter could use singular form if there is only one match, and plural form if there are zero or 2+ matches. Godot doesn't support localized pluralization, but the English pluralization are still correct in many languages out there. (As a workaround, unsupported languages would have to use the plural form for both strings.)

**Comment by YeldhamDev** [comment]
@Calinou Done!

File: editor/code_editor.cpp [hunk 2]
```diff
@@ -332,6 +332,18 @@ void FindReplaceBar::_update_results_count() {
...
 
+void FindReplaceBar::_update_matches_label() {
+
+	if (search_text->get_text().empty() || results_count == -1) {
+		matches_label->hide();
+	} else {
+		matches_label->show();
+
+		matches_label->add_color_override("font_color", results_count > 0 ? Color(1, 1, 1) : EditorNode::get_singleton()->get_gui_base()->get_color("error_color", "Editor"));
+		matches_label->set_text(vformat(TTR(results_count == 1 ? "%d match." : "%d matches."), results_count));
```
Comment (akien-mga) [inline editor/code_editor.cpp]: That's not going to work, `TTR()` is a macro and extracts its contents for localization, but doesn't parse the code.

You should use `vformat(results_count == 1 ? TTR("%d match.") : TTR("%d matches."), results_count)`.

File: editor/editor_help.cpp [hunk 3]
```diff
@@ -1738,19 +1738,13 @@ void FindBar::_update_results_count() {
...
-
+	if (search_text->get_text().empty() || results_count == -1) {
 		matches_label->hide();
 	} else {
 		matches_label->show();
 
-		matches_label->add_color_override("font_color", EditorNode::get_singleton()->get_gui_base()->get_color("error_color", "Editor"));
-		matches_label->set_text(TTR("No Matches"));
+		matches_label->add_color_override("font_color", results_count > 0 ? Color(1, 1, 1) : EditorNode::get_singleton()->get_gui_base()->get_color("error_color", "Editor"));
+		matches_label->set_text(vformat(TTR(results_count == 1 ? "%d match." : "%d matches."), results_count));
```
Comment (akien-mga) [inline editor/editor_help.cpp]: Same here.

**Comment by YeldhamDev** [comment]
That should be it.

**Comment by akien-mga** [comment]
Thanks!
