### PR TITLE
[Web] Fix sample playback deletion and `AudioStreamPolyphonic` issue

### LINKED ISSUE #103311: `AudioStreamPolyphonic` will not work after a certain number of playback only on the web with `PLAYBACK_TYPE_SAMPLE`
### Tested versions

4.4 RC1

### System information

OS: Windows 10, Browser: Chrome 133.0.6943.127

### Issue description

It seems that when the AudioPlaybackPolyphonic playback limit is reached, the old samples that have finished playing are not discarded, and the queue is constantly being filled.

Video (please turn on the audio) ⚠️Volume alert!⚠️:

https://github.com/user-attachments/assets/9c41cff8-7a25-4531-a727-41d03ded0b09

Using `PLAYBACK_TYPE_STREAM` can work around this, but it is not the correct solution due to cracks and latency issues.

### Steps to reproduce

Playback audio with `PLAYBACK_TYPE_SAMPLE` by AudioPlaybackPolyphonic on the Web

### Minimal reproduction project (MRP)

[web-polyphonic.zip](https://github.com/user-attachments/files/18979544/web-polyphonic.zip)

### PR DESCRIPTION
**Pull request by adamscott**
This PR fixes sample playback deletion, as samples were never flagged as deleted.

This also fixes #103311 as samples were marked as active, but never marked as inactive, filling up the polyphonic playback without any way to make space.

> [!NOTE]
> ~~A commit will follow to inverse the flow: instead of polling JavaScript to know if a sample is active or not, I'll create a callback for JavaScript to notify Godot directly when a sample was deleted.~~ Done.

### CODE REVIEW

File: servers/audio_server.cpp [hunk 1]
```diff
@@ -1618,6 +1618,20 @@ void AudioServer::update() {
...
+	if (!sample_playback_list.is_empty()) {
+		LocalVector<Ref<AudioSamplePlayback>> sample_playbacks_to_remove;
+		for (Ref<AudioSamplePlayback> &sample_playback : sample_playback_list) {
+			if (!is_sample_playback_active(sample_playback)) {
+				sample_playbacks_to_remove.push_back(sample_playback);
+			}
+		}
+		for (Ref<AudioSamplePlayback> &sample_playback_to_remove : sample_playbacks_to_remove) {
+			sample_playback_list.erase(sample_playback_to_remove);
+		}
```
Comment (adamscott) [inline servers/audio_server.cpp]: Is there a better way to remove elements from the currently looping for loop list?

Comment (rburing) [reply servers/audio_server.cpp]: Just loop with an index instead of range-based `for`, and start with the last element.

Comment (adamscott) [reply servers/audio_server.cpp]: Finally, the callback functionality existed, but wasn't working. So I fixed it, and removed that part.
But I'll remember the trick. Thanks @rburing!

**Comment by adamscott** [comment]
Oops. Fixed the PR without making it shown as ready 2 weeks ago.

**Review by clayjohn — APPROVED** [review]

**Comment by clayjohn** [comment]
Seems fine to me

**Comment by Repiteo** [comment]
Thanks!
