### PR TITLE
[iOS] Fix sensors orientation.

### LINKED ISSUE #90901: iOS sensors have incorrect orientation
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

iPadOS 17.4, iPad 9th gen

### Issue description

I'm using SCREEN_SENSOR orientation to automatically rotate my app, and sensor vectors (gravity, accelerometer, magnetometer, gyro) don't maintain their orientation relative to the app. This causes them to point in unpredictable directions. Portrait is the only mode that works properly.

The relevant code is here. According to [this comment](https://github.com/godotengine/godot/issues/8101#issuecomment-288239424), it was meant to correct their coordinate system by a rotation.
https://github.com/godotengine/godot/blob/9bc49a66bae5e9e506f12df3b3e141c8da13f983/platform/ios/godot_view.mm#L452-L477

The 3rd case is wrong and should have been (-x,-y,z) in order to rotate 180 degrees in the xy plane. The other 2 cases may have worked at the time, but not anymore.

### Steps to reproduce

Export the MRP for iOS. The 3D arrow should point down no matter the orientation.

You can also use the official sensors demo: https://github.com/godotengine/godot-demo-projects/tree/master/mobile/sensors

### Minimal reproduction project (MRP)

[down-MRP.zip](https://github.com/godotengine/godot/files/15040909/down-MRP.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/90901

### CODE REVIEW

File: platform/ios/display_server_ios.h [hunk 1]
```diff
@@ -129,10 +129,10 @@ class DisplayServerIOS : public DisplayServer {
 
 	// MARK: Motion
```
Comment (akien-mga) [inline platform/ios/display_server_ios.h:130]: Who is Mark? :P

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
