### PR TITLE
Fix screen-space AA when scaling using bilinear filtering

### LINKED ISSUE #68096: FXAA breaks with Resolution Scale
### Godot version

4.0 Beta 3

### System information

Windows 11, Vulkan, GTX 1050 Ti 516.94

### Issue description

FXAA seems to calculate Pixel size by Resolution, without taking into account Resolution Scale, which creates artifacts especially clear at very low resolution scales.

### Steps to reproduce

Turn on FXAA
1) Set Resolution Scale to 0.5 - Observe result
2) Set Resolution Scale to 1.0 and set Viewport to Half Res - Observe result
Observe how cases 1&2 clearly don't have the same result with FXAA

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Kaleb-Reid**
This fixes an existing issue I noticed while working on https://github.com/godotengine/godot/pull/79731. If using bilinear scaling, screen-space AA methods (and I guess anything else in the tonemapping shader) sample the internal 3D viewport texture, but render to a full-sized framebuffer, breaking the screen-space AA algorithms.

**0.25x scale using bilinear filtering:**
|Before|After|
|:-------------------------:|:-------------------------:|
|||

You can see more easily how it breaks when using nearest-neighbour filtering:
**0.25x scale using nearest-neighbour filtering:**
|Before|After|
|:-------------------------:|:-------------------------:|
|image|image|

This pr only covers the fix for bilinear scaling because nearest-neighbour is already functional in https://github.com/godotengine/godot/pull/79731.

I didn't make any changes to Compatibility because currently it has no screen-space AA, but if a copy is cheaper than tonemapping the full resolution then maybe it's a good idea.

Fixes https://github.com/godotengine/godot/issues/68096
Depends on https://github.com/godotengine/godot/pull/79731

### CODE REVIEW

**Comment by mrjustaguy** [comment]
Resolves https://github.com/godotengine/godot/issues/68096

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected. Code looks good to me.

**Testing project:** https://github.com/godotengine/godot-demo-projects/tree/master/3d/graphics_settings

## Preview

*All screenshots use 0.25 render scale with bilinear filtering.*

### FXAA

Before | After
-|-
Screenshot_20251202_000011 | Screenshot_20251201_235922

### SMAA

Before | After
-|-
Screenshot_20251202_000024 | Screenshot_20251201_235940

The results are a little blurrier, but this is intended since it allows the screen-space antialiasing to do its job correctly. Edge coverage works a lot better than in `master`.

File: servers/rendering/renderer_rd/renderer_scene_render_rd.cpp [hunk 1]
```diff
@@ -783,9 +784,9 @@ void RendererSceneRenderRD::_render_buffers_post_process_and_tonemap(const Rende
 
 		tonemap.debanding_mode = RendererRD::ToneMapper::TonemapSettings::DebandingMode::DEBANDING_MODE_DISABLED;
 		if (rb->get_use_debanding() && !using_hdr) {
-			if (!can_use_storage && (use_smaa || spatial_upscaler)) {
+			if (!can_use_storage && (use_smaa || using_scaling_pass)) {
 				tonemap.debanding_mode = RendererRD::ToneMapper::TonemapSettings::DebandingMode::DEBANDING_MODE_10_BIT;
-			} else if (!(use_smaa || spatial_upscaler)) {
+			} else if (!(use_smaa || using_scaling_pass)) {
```
Comment (Kaleb-Reid) [inline servers/rendering/renderer_rd/renderer_scene_render_rd.cpp]: Not really sure if this should be changed or not.

Comment (allenwp) [reply servers/rendering/renderer_rd/renderer_scene_render_rd.cpp]: `use_scaling_pass` changes the destination buffer format to 10 bit integer in this case, doesn't it? So yes, these need to be changed as you mentioned here.

Comment (allenwp) [reply servers/rendering/renderer_rd/renderer_scene_render_rd.cpp]: Since it's not clear to everyone, maybe add in the comment that I suggested in this comment: https://github.com/godotengine/godot/pull/79731#discussion_r2669895014

Comment (Kaleb-Reid) [reply servers/rendering/renderer_rd/renderer_scene_render_rd.cpp]: @allenwp My assumption is that you are correct and they are 10 bit integer because the same textures with the same format are created whether `spatial_upscaler != nullptr` on master or `using_upscaling_pass == true` on this pr.

Comment (Kaleb-Reid) [reply servers/rendering/renderer_rd/renderer_scene_render_rd.cpp]: @allenwp I reverted this section as you've addressed it in #114890

Comment (allenwp) [reply servers/rendering/renderer_rd/renderer_scene_render_rd.cpp]: Thanks! Sorry for the confusion about this!

**Comment by allenwp** [comment]
Did some testing. Thanks!

It seems that when FSR 1.0 is enabled and FXAA is enabled, this fix doesn't work on the Forward+ or Mobile renderers. It's especially noticeable on the Mobile renderer where FSR 1.0 isn't supported.

I did not test the HDR 2D code path because I think it should be similar. I didn't try MSAA either, but maybe those would be worth testing, too...

### Forward+ HDR 2D off
**After this PR**
Scaling mode | No anti-aliasing | FXAA | SMAA
-|-|-|-
Nearest | image | image | image
Bilinear | image |image| image
FSR 1.0 | image | image |image

**Before this PR**
Scaling mode | No anti-aliasing | FXAA | SMAA
-|-|-|-
Nearest | image|image|image
Bilinear | image|image|image
FSR 1.0 | image|image|image

### Mobile HDR 2D off
**After this PR**
Scaling mode | No anti-aliasing | FXAA | SMAA
-|-|-|-
Nearest | image | image| image
Bilinear | image| image|image
FSR 1.0 | image | image| image

**Before this PR**
Scaling mode | No anti-aliasing | FXAA | SMAA
-|-|-|-
Nearest | image| image | image
Bilinear | image|image|image
FSR 1.0 | image|image|image

### Compatibility HDR 2D off
**After this PR**
Scaling mode | No anti-aliasing | FXAA | SMAA
-|-|-|-
Nearest | image| image | image
Bilinear | image| image|image
FSR 1.0 | image| image | image

**Before this PR**
Scaling mode | No anti-aliasing | FXAA | SMAA
-|-|-|-
Nearest | image | image | image
Bilinear |image | image | image
FSR 1.0 | image| image|image

**Comment by allenwp** [comment]
Sorry, I forgot to mention that I did review the code and the changes look great to me. This is clearly better than before the fix!

If the issue I identified (Mobile with FXAA and FSR 1.0) is related to something that isn’t directly a part of this PR, then we can make that fix in a followup PR and merge this one as-is, but I think it would be good to know what’s going on first so that we can make and informed decision.

**Comment by Kaleb-Reid** [comment]
@allenwp I believe I've fixed the issue with the mobile renderer which was because `scale_mode` does not get changed if the selected mode is not supported (fsr 1 & 2 / metalfx spatial & temporal). Also yes I'm pretty sure forward+ already has the correct behaviour when using fsr / metalfx upscalers + screen space aa because the tonemapper / smaa should output to internal resolution to pass to the upscaler for upscaling.

**Comment by Kaleb-Reid** [comment]
@allenwp I'm reverting the change I made because I realized that the behaviour you found is a different bug which I've opened https://github.com/godotengine/godot/pull/118629 to fix.

**Review by allenwp — APPROVED** [review]
Looks great to me! #118629 does indeed sound like the right fix for this. Requesting review from Skyth to do a final check on this.

**Review by blueskythlikesclouds — APPROVED** [review]
Looks and works great.

**Comment by allenwp** [comment]
Removed the old cherry pick 4.5 label because this PR has been updated to target the changes of #79731 (introduced in 4.7) and will conflict with 4.5 or 4.6.

**Comment by Repiteo** [comment]
Thanks!
