### PR TITLE
Fix animation library serialization compatibility for 4.5 projects

### LINKED ISSUE #113037: Regression: Saving a scene in 4.6 that was created in 4.5 or earlier saves all animation data to .tscn file for editable children.
### Tested versions

- Reproduces in v4.6.dev.custom_build [b79fe2e02]
- Not present in 4.6-dev4

### System information

Godot v4.6.dev (b79fe2e02) - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 32.0.15.8115) - AMD Ryzen 7 3700X 8-Core Processor (16 threads) - 15.95 GiB memory

### Issue description

After updating to latest master, saving scenes that have editable children of imported .blend files will result in all animation data being stored in the .tscn file.  This does not seem to happen with new scenes created in the latest 4.6 (master branch).

### Steps to reproduce

- Open Godot 4.5.
- Import a .blend file that has bones and animations.
- Add .blend to a scene.
- Make blend file editable children.
- (Optional?) Add something like a BoneAttachment3D as a child to the Skeleton3D.
- Save and close the project.
- Open the project in latest master.
- Save the the scene.
- Note that all the animation data is stored in the .tscn file:

```

[sub_resource type="Animation" id="Animation_y21ge"]
resource_name = "Anim2"
length = 3.3333333
tracks/0/type = "rotation_3d"
tracks/0/imported = true
tracks/0/enabled = true
tracks/0/path = NodePath("Armature/Skeleton3D:Bone")
tracks/0/interp = 1
tracks/0/loop_wrap = true
tracks/0/keys = PackedFloat32Array(0, 1, 0, 0, 0, 1, 0.06666667, 1, -0.00021768807, -0.00014519705, -0.00056523393, 0.9999998, 0.1, 1, -0.0007831062, -0.0005183674, -0.0020179395, 0.9999976, 0.13333334, 1, -0.0017500045, -0.0011504084, -0.004478396, 0.99998784, 0.16666667, 1, -0.003095829, -0.002020331, -0.007864894, 0.9999623, 0.2, 1, -0.0049018823, -0.0031655026, -0.012322904, 0.9999071, 0.23333333, 1, -0.007019245, -0.0044855843, -0.01746182, 0.99981284, 0.26666668, 1, -0.009425188, -0.005959454, -0.023199413, 0.9996687, 0.3, 1, -0.012096869, -0.007565915, -0.029453162, 0.99946433, 0.33333334, 1, -0.015011333, -0.009283703, -0.036140293, 0.99919087, 0.36666667, 1, -0.018203717, -0.011107478, -0.043240022, 0.9988372, 0.4, 1, -0.021569546, -0.012978518, -0.05052375, 0.9984056, 0.5, 1, -0.03247412, -0.01866055, -0.072643176, 0.9966545, 0.53333336, 1, -0.036312513, -0.02047966, -0.079724744, 0.9959448, 0.56666666, 1, -0.04018521, -0.022218, -0.08649188, 0.99519384, 0.6, 1, -0.04406954, -0.02385458, -0.09286289, 0.9944171, 0.6333333, 1, -0.047943056, -0.025368532, -0.09875654, 0.9936323, 0.6666667, 1, -0.05178357, -0.026739132, -0.10409209, 0.9928587, 0.7, 1, -0.055537038, -0.027877722, -0.10852449, 0.99214965, 0.73333335, 1, -0.059192345, -0.028811274, -0.1121587, 0.9915073, 0.76666665, 1, -0.062728316, -0.029519368, -0.11491522, 0.9909532, 0.8, 1, -0.06612388, -0.029981554, -0.116714455, 0.9905082, 0.8333333, 1, -0.06935799, -0.030177308, -0.117476486, 0.9901909, 0.8666667, 1, -0.072349936, -0.029874828, -0.11611462, 0.9901467, 0.9, 1, -0.07516638, -0.029142871, -0.112823054, 0.99033916, 0.93333334, 1, -0.07781153, -0.028011722, -0.107738204, 0.99073374, 0.96666664, 1, -0.08028854, -0.026511379, -0.10099531, 0.99128747, 1, 1, -0.082599774, -0.024671696, -0.092729114, 0.9919526, 1.0333333, 1, -0.0846975, -0.022440838, -0.082707524, 0.99271464, 1.0666667, 1, -0.08663611, -0.019962128, -0.07157505, 0.99346507, 1.1, 1, -0.08841671, -0.017266944, -0.05947324, 0.9941566, 1.1333333, 1, -0.09004052, -0.014387172, -0.046545833, 0.9947458, 1.1666666, 1, -0.09150911, -0.011355258, -0.032939047, 0.99519455, 1.2, 1, -0.092782795, -0.008187523, -0.018726593, 0.9954766, 1.3, 1, -0.095750436, 0.0014900465, 0.024669081, 0.99509853, 1.3333334, 1, -0.09647289, 0.004659799, 0.038874917, 0.9945653, 1.3666667, 1, -0.09704374, 0.0076945336, 0.05247204, 0.99386626, 1.4, 1, -0.0975081, 0.010578002, 0.06538818, 0.99302804, 1.4333333, 1, -0.097875595, 0.013277648, 0.07747805, 0.99208933, 1.4666667, 1, -0.09815644, 0.015761454, 0.08859887, ...
```

### Minimal reproduction project (MRP)

[test-editable-children-animation.zip](https://github.com/user-attachments/files/23686703/test-editable-children-animation.zip)

Just open this and save the scene and note what happens to the .tscn file.

### PR DESCRIPTION
**Pull request by Clubhouse1661**
Fixes #113037

Problem:
When opening a Godot 4.5 project in 4.6 and saving scenes with editable children of imported scenes (e.g., `.blend` files), all animation data was incorrectly being saved to the `.tscn` file, causing massive file bloat.

Root Cause:
The AnimationLibrary serialization format changed between 4.5 and 4.6:
- **4.5**: `libraries` as a single Dictionary property
- **4.6**: `libraries/<name>` as separate properties per library

When the scene packer looked for `libraries/<name>` in old imported scenes, it didn't find them (only `libraries` existed), causing the property comparison to fail and all animation data to appear as "overridden."

Solution:
Added backwards compatibility in `SceneState::get_property_value()` to check for the old Dictionary format when looking up `libraries/<name>` properties. This allows property comparison to work correctly with both old and new serialization formats.

Testing:
- Took a project in 4.5 with imported `.blend` file as editable children
- Opened in 4.6 with this fix, saved the scene
- Verified animation data is NOT duplicated into the `.tscn` file
- Verified animations still work correctly

https://github.com/user-attachments/assets/546852d7-a034-48a2-93cf-2663a04e0e76

https://github.com/user-attachments/assets/d2168842-9aab-4a7b-8524-5849e96cac36

### CODE REVIEW

File: scene/resources/packed_scene.cpp [hunk 1]
```diff
@@ -1560,6 +1560,31 @@ Variant SceneState::get_property_value(int p_node, const StringName &p_property,
...
 		}
+
+#ifndef DISABLE_DEPRECATED
+		// Compatibility: In 4.5 and earlier, AnimationMixer used a single "libraries" Dictionary property.
+		// In 4.6+, each library is stored as a separate "libraries/<name>" property.
+		// If we're looking for "libraries/<name>" and didn't find it, check the old format.
+		String prop_str = p_property.operator String();
+		if (prop_str.begins_with("libraries/")) {
+			String library_name = prop_str.get_slicec('/', 1);
+			static const StringName libraries_sname = "libraries";
```
Comment (TokageItLab) [inline scene/resources/packed_scene.cpp]: Can you check if the node's base class is AnimationMixer?

**Review by TokageItLab — APPROVED** [review]

**Comment by Clubhouse1661** [comment]
@TokageItLab Commits have been squashed into a single commit as requested. 
Thanks for testing!

File: scene/resources/packed_scene.cpp [hunk 2]
```diff
@@ -1560,6 +1560,34 @@ Variant SceneState::get_property_value(int p_node, const StringName &p_property,
 				return variants[p[i].value];
 			}
 		}
+
+#ifndef DISABLE_DEPRECATED
```
Comment (akien-mga) [inline scene/resources/packed_scene.cpp:1564]: This should probably also be guarded with a `TOOLS_ENABLED` check, as this is not relevant at runtime IINM, and this would have some performance cost for the string conversion and check every time a value is read.

Given the above, I also wonder if this isn't something  that could be handled in `AnimationMixer` via `_set`/`_get` instead of doing it here?

Comment (TokageItLab) [reply scene/resources/packed_scene.cpp:1564]: The code within this block should indicate that it is attempting to retrieve `libraries/xxxxx` from a scene that does not have the `libraries/xxxxx`.

In 4.6, setters and getters already perform serialization assuming the `libraries/xxxxx` path.

As compatibility code, the setter is written to parse dictionaries passed with the `libraries` path. However, enabling the getter to retrieve dictionaries with the `libraries` path, as shown below, does not resolve this issue.

```cpp
bool AnimationMixer::_get(const StringName &p_name, Variant &r_ret) const {
	String name = p_name;

#ifndef DISABLE_DEPRECATED
#ifdef TOOLS_ENABLED
	if (name == "libraries") {
		r_ret = get_animation_libraries();
	} else if (name.begins_with("libraries/")) {
#endif // TOOLS_ENABLED
#else
	if (name.begins_with("libraries/")) {
#endif // DISABLE_DEPRECATED
		String which = name.get_slicec('/', 1);
		if (has_animation_library(which)) {
			r_ret = get_animation_library(which);
		} else {
			return false;
		}
	} else {
		return false;
	}

	return true;
}

#ifndef DISABLE_DEPRECATED
#ifdef TOOLS_ENABLED
Dictionary AnimationMixer::get_animation_libraries() const {
	Dictionary ret;
	for (const AnimationLibraryData &lib : animation_libraries) {
		Dictionary d;
		List<StringName> ls;
		lib.library->get_animation_list(&ls);
		for (const StringName &an : ls) {
			d[an] = lib.library->get_animation(an);
		}
		ret[lib.name] = d;
	}
	return ret;
}
#endif // TOOLS_ENABLED
#endif // DISABLE_DEPRECATED
```

(BTW, `get_animation_libraries()` was a dead definition, so I sent a fix as https://github.com/godotengine/godot/pull/114897.)

Therefore, I don't think there's any other way.

Adding `TOOLS_ENABLED` makes point. If reducing string comparison cost is a consideration, I think increasing the `gd_scene format` in `4.6` might allow checks to be performed only on tscn versions prior to `4.5` by integer comparison (but I'm not sure increasing format version is approved as it is not within my area to decide that).

Comment (Clubhouse1661) [reply scene/resources/packed_scene.cpp:1564]: @akien-mga I added `TOOLS_ENABLED` guard as suggested. The compatibility code is now only compiled for editor builds, which eliminates any runtime performance impact.

File: scene/resources/packed_scene.cpp (hunk 1 above)
Comment (Clubhouse1661) [reply scene/resources/packed_scene.cpp]:
```cpp
StringName node_type = get_node_type(p_node);
			if (node_type != StringName() && ClassDB::is_parent_class(node_type, SNAME("AnimationMixer"))) {
```
Good catch. I've added the check to ensure the node's base class is AnimationMixer before applying the backwards compatibility logic.

File: scene/resources/packed_scene.cpp (hunk 2 above)
Comment (Clubhouse1661) [reply scene/resources/packed_scene.cpp]: Adding to @TokageItLab's point: 
When the editor checks if `libraries/default` is overridden, it reads directly from the inherited `.tscn` file. It doesn't go through `AnimationMixer::_get`. So even though `_set` handles loading old scenes correctly, `_get` can't help here because it's never called during this comparison. The fix needs to be where the file data is actually read, which is `SceneState`.

**Review by akien-mga — APPROVED** [review]
