### PR TITLE
Do not allow editing Scene-inherited signal connections

### LINKED ISSUE #12373: it's impossible to disconnect signals in inherited scene.
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 2.1

**Issue description:**

If I have a base scene and connect a method to a signal, 
And in the inherited scene, I do not need this connect, I can disconnect the signal in the editor, but when open the scene again, the signal is still connected to that method.

**Steps to reproduce:**

**Link to minimal example project:**

### PR DESCRIPTION
**Pull request by Mickeon**
Closes https://github.com/godotengine/godot/issues/12373.

Editing inherited signal connections has never actually really worked, in practice.
In fact, saving and reopening the **Scene** makes all inherited connections appear again, as if no change has even happened. Very strange to let the user touch them, in the first place. It really has no effect. Nor it probably should, as it would lead to an unorganised workflow.

This PR makes it so that signal connections from an **inherited** Scene can no longer be modified in any way in the **Editor**. 
Inherited connections are displayed in **warning yellow** (same as inherited Nodes) and they cannot be edited or removed.

Showcase

Likewise, "Disconnect All" will not disconnect inherited connections, and is disabled if no connection can be disconnected.
image

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
The idea seems fine to me, could use a more in depth review as I just gave it a quick look.

**Comment by KoBeWi** [comment]
Found a bug. Connecting an instance blocks disconnecting until reload.

https://user-images.githubusercontent.com/2223172/195660416-7464d82c-d6f2-4924-9cfa-dc75ad28b8d8.mp4

File: editor/connections_dialog.cpp [hunk 1]
```diff
@@ -737,6 +740,26 @@ bool ConnectionsDock::_is_item_signal(TreeItem &p_item) {
...
+
+	Node *source = Object::cast_to<Node>(p_connection.signal.get_object());
+	Node *target = Object::cast_to<Node>(p_connection.callable.get_object());
+
+	const NodePath source_path = scene_root->get_path_to(source);
+	const NodePath target_path = scene_root->get_path_to(target);
+	const StringName signal_name = p_connection.signal.get_name();
+	const StringName method_name = p_connection.callable.get_method();
+
+	// If it cannot be found it in PackedScene, this connection has got to be inherited.
```
Comment (KoBeWi) [inline editor/connections_dialog.cpp:759]:
```suggestion
	// If it cannot be found in PackedScene, this connection has got to be inherited.
```

File: editor/connections_dialog.cpp [hunk 2]
```diff
@@ -1116,6 +1159,12 @@ void ConnectionsDock::update_tree() {
 				connection_item->set_text(0, path);
 				connection_item->set_metadata(0, connection);
 				connection_item->set_icon(0, get_theme_icon(SNAME("Slot"), SNAME("EditorIcons")));
+
+				if (_is_connection_inherited(connection)) {
+					// The Scene does not inherit this connection.
```
Comment (KoBeWi) [inline editor/connections_dialog.cpp:1164]:
```suggestion
					// The scene does not inherit this connection.
```

**Comment by Mickeon** [comment]
> Connecting an instance blocks disconnecting until reload.

Hmm... It technically makes sense. I wonder how to address this one...

**Comment by KoBeWi** [comment]
It's not important tbh, so it can be fixed later (e.g. when someone open an issue xd)

**Review by KoBeWi — APPROVED** [review]
Looks ok, aside from some comment typos and unimportant issue.

File: editor/connections_dialog.cpp (hunk 2 above)
Comment (Mickeon) [reply editor/connections_dialog.cpp:1164]: Upon a second look that comment is incorrect, it's the exact opposite.

**Comment by Mickeon** [comment]
Reflecting on the bug more, to solve it would mean to change the way direct scene connections are detected, to do a bit of the opposite of what it is currently doing.

**Comment by akien-mga** [comment]
Thanks!
