### PR TITLE
Fix various crashes relating to low roughness_layers

### LINKED ISSUE #56747: Vulkan: Crash when setting Reflection Roughness Layers to a low value
### Godot version

v4.0.dev.20220105.official [8f6cba3a4]

### System information

Windows 11, Vulkan, Nvidia Quadro K2000 472.84

### Issue description

When Roughness Layers are set to 1,2 when trying to manipulate object materials the editor crashes (in VMR, didn't test VCR)

### Steps to reproduce

Set Roughness Layers to 1 or 2, restart the editor, Make a Mesh Instance and try to manipulate a Material for it. This will Result in a Crash.

Notes: Mobile Renderer was tested

### Minimal reproduction project

_No response_

### LINKED ISSUE #71444: Texture Array Sky Reflections Project Setting Causes Crash
### Godot version

Godot Engine v4.0.beta.custom_build.3c9bf4bc2

### System information

Manjaro Linux 5.10.161-1-MANJARO,  Nvida Quadro M620 (525.60.11), X11

### Issue description

Godot crashes while loading the project.

```
Godot Engine v4.0.beta.custom_build.3c9bf4bc2 - https://godotengine.org
WARNING: XOpenIM failed
     at: DisplayServerX11 (platform/linuxbsd/x11/display_server_x11.cpp:4969)
WARNING: XCreateIC couldn't create wd.xic
     at: _create_window (platform/linuxbsd/x11/display_server_x11.cpp:4765)
OpenGL Renderer: Quadro M620/PCIe/SSE2
 
Project is missing: [ 8<  --- CUT ---  >8]

ERROR: Error opening file '/home/marcin/src/vendor/Godot-4-forest-benchmark/icon.svg'.
   at: load_image (core/io/image_loader.cpp:90)
Editing project: /home/marcin/Godot/4/TiledImporterTest_v4
Godot Engine v4.0.beta.custom_build.3c9bf4bc2 - https://godotengine.org
WARNING: XOpenIM failed
     at: DisplayServerX11 (platform/linuxbsd/x11/display_server_x11.cpp:4969)
WARNING: XCreateIC couldn't create wd.xic
     at: _create_window (platform/linuxbsd/x11/display_server_x11.cpp:4765)
Vulkan API 1.3.224 - Using Vulkan Device #0: NVIDIA - Quadro M620

SCRIPT ERROR: Parse Error: Identifier "AudioSlicer" not declared in the current scope.
          at: GDScript::reload (res://starterpack/AudioSlicePlayer/AudioSlicePlayer3D.gd:11)
SCRIPT ERROR: Parse Error: Identifier "AudioSlicer" not declared in the current scope.
          at: GDScript::reload (res://starterpack/AudioSlicePlayer/AudioSlicePlayer3D.gd:12)
SCRIPT ERROR: Parse Error: Identifier "AudioSlicer" not declared in the current scope.
          at: GDScript::reload (res://starterpack/AudioSlicePlayer/AudioSlicePlayer3D.gd:13)
SCRIPT ERROR: Parse Error: Assigned value for constant "STRATEGY_MAP" isn't a constant expression.
          at: GDScript::reload (res://starterpack/AudioSlicePlayer/AudioSlicePlayer3D.gd:10)
SCRIPT ERROR: Parse Error: Identifier "AudioSlicer" not declared in the current scope.
          at: GDScript::reload (res://starterpack/AudioSlicePlayer/AudioSlicePlayer3D.gd:19)
SCRIPT ERROR: Parse Error: Identifier "AudioSlicer" not declared in the current scope.
          at: GDScript::reload (res://starterpack/AudioSlicePlayer/AudioSlicePlayer.gd:10)
SCRIPT ERROR: Parse Error: Identifier "AudioSlicer" not declared in the current scope.
          at: GDScript::reload (res://starterpack/AudioSlicePlayer/AudioSlicePlayer.gd:11)
SCRIPT ERROR: Parse Error: Identifier "AudioSlicer" not declared in the current scope.
          at: GDScript::reload (res://starterpack/AudioSlicePlayer/AudioSlicePlayer.gd:12)
SCRIPT ERROR: Parse Error: Assigned value for constant "STRATEGY_MAP" isn't a constant expression.
          at: GDScript::reload (res://starterpack/AudioSlicePlayer/AudioSlicePlayer.gd:9)
SCRIPT ERROR: Parse Error: "CameraEffects" was not found in the current scope.
          at: GDScript::reload (res://starterpack/CameraLens/CameraLens.gd:144)
SCRIPT ERROR: Parse Error: Could not find base class "WeaponBase".
          at: GDScript::reload (res://starterpack/FPSPrototypePlayer/BulletThrower.gd:0)
ERROR: Cannot open file 'res://.godot/imported/349081__yoyodaman234__jumping-over-object-while-hiking.wav-5a85051c163b49c19a3d7a7f808c5a9e.sample'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/407957__judith136__28.wav-31f2d6ee49f9a5bace261dfab2c4ab7b.sample'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/620343__marb7e__footsteps-stiletto-stone-walk01.wav-a5a892c912b1ae334c06e24656af912f.sample'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/620345__marb7e__footsteps-stiletto-stone-walk05.wav-1a19dada8ab03617bcdc3358125f1f1a.sample'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/footstep_wood1.wav-43ef2641fb1410591e9dc5656467dafa.sample'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/footstep_wood2.wav-49944262aac95815e7ad60246a17da36.sample'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/pop.wav-6bfb9cb2204d8d802db000bce92dff1b.sample'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/housemedieval.obj-24c8b27d1cee9c854e6f5c12e5f51ea4.mesh'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/housemediieval_low.obj-739838e333006b197eafd027ce35bcf0.mesh'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/untitled.glb-3dab1b81b8fc00484e1583f62f60ac40.scn'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/Medieval_House_Sell.glb-b6b6aa8e5a4de168d8431bece1193814.scn'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/Medieval_House_Sell.obj-387e23891599fcf16573bf27a6ef3e1a.mesh'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/Archer.obj-2b65145d11fa24b67ef684d46d24818e.mesh'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/House2.fbx-f8d671f02f05b6ed90784281681baaf9.scn'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/House2.obj-d58585563cd95f839373812e73528eb9.mesh'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/Medieval_Inn.glb-fbcac1553b3ff11d5c1c8abd448de991.scn'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/RuralStall.obj-676c8b344208bf17572f03aa7497084c.mesh'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/rural_stall.glb-7591d8ea10523558f727280a58feab06.scn'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/stragan_.obj-4d1a933cc8ab26010356a755645d2331.mesh'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/uploads_files_2304363_Well.fbx-9e3ebfdbb9500a526ef5266c4576c22e.scn'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/tower12.obj-95e392127990b90083cacc6df22c3695.mesh'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/wall.blend-4015e7fc18b117cbe0333426d32dddc1.scn'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/wall.obj-2b1d988eb97581a1e12896007077a8e2.mesh'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/KubelSmieci.glb-379a6e6a0896bfffe67fa321fd6c6b88.scn'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/pine-tree-3-lod2.obj-1992c6bdac6619037d58d0b51b862ffd.mesh'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/quad_mesh.obj-f4a5397828c95bdb27cb34e87ad8cb26.mesh'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/quad_small_mesh.mtl.obj-e637aa39c5b0fa158ff552a138b7fed3.mesh'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Cannot open file 'res://.godot/imported/340325__rambler52__rural-ourdoors-birds.wav-033909e66caf8ae6c70762a9d0616387.sample'.
   at: get_dependencies (core/io/resource_format_binary.cpp:1185)
ERROR: Trying to unreference a SafeRefCount which is already zero is wrong and a symptom of it being misused.
Upon a SafeRefCount reaching zero any object whose lifetime is tied to it, as well as the ref count itself, must be destroyed.
Moreover, to guarantee that, no multiple threads should be racing to do the final unreferencing to zero.
   at: _check_unref_sanity (./core/templates/safe_refcount.h:173)
ERROR: Trying to unreference a SafeRefCount which is already zero is wrong and a symptom of it being misused.
Upon a SafeRefCount reaching zero any object whose lifetime is tied to it, as well as the ref count itself, must be destroyed.
Moreover, to guarantee that, no multiple threads should be racing to do the final unreferencing to zero.
   at: _check_unref_sanity (./core/templates/safe_refcount.h:173)
ERROR: Trying to unreference a SafeRefCount which is already zero is wrong and a symptom of it being misused.
Upon a SafeRefCount reaching zero any object whose lifetime is tied to it, as well as the ref count itself, must be destroyed.
Moreover, to guarantee that, no multiple threads should be racing to do the final unreferencing to zero.
   at: _check_unref_sanity (./core/templates/safe_refcount.h:173)

================================================================

================================================================

================================================================
handle_crash: Program crashed with signal 4
handle_crash: Program crashed with signal 4
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.0.beta.custom_build (3c9bf4bc210a8e6a208f30ca59de4d4d7e18c04d)
Engine version: Godot Engine v4.0.beta.custom_build (3c9bf4bc210a8e6a208f30ca59de4d4d7e18c04d)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
Engine version: Godot Engine v4.0.beta.custom_build (3c9bf4bc210a8e6a208f30ca59de4d4d7e18c04d)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x38a00) [0x7fc2e328ea00] (??:0)
[1] /usr/lib/libc.so.6(+0x38a00) [0x7fc2e328ea00] (??:0)
ERROR: Parent node is busy setting up children, `remove_child()` failed. Consider using `remove_child.call_deferred(child)` instead.
   at: remove_child (scene/main/node.cpp:1169)
ERROR: Condition "data.parent" is true.
   at: ~Node (scene/main/node.cpp:3042)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta.custom_build (3c9bf4bc210a8e6a208f30ca59de4d4d7e18c04d)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x38a00) [0x7fc2e328ea00] (??:0)
[2] StringName::unref() (??:0)
[2] StringName::unref() (??:0)
[2] StringName::unref() (??:0)
[1] /usr/lib/libc.so.6(+0x38a00) [0x7fc2e328ea00] (??:0)
[3] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0xa717ba) [0x56369f0727ba] (??:0)
[3] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0xa717ba) [0x56369f0727ba] (??:0)
[3] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0xa717ba) [0x56369f0727ba] (??:0)
[4] ResourceImporterTexture::import(String const&, String const&, HashMap<StringName, Variant, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, Variant> > > const&, List<String, DefaultAllocator>*, List<String, DefaultAllocator>*, Variant*) (??:0)
[2] Object::notification(int, bool) (??:0)
[4] ResourceImporterTexture::import(String const&, String const&, HashMap<StringName, Variant, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, Variant> > > const&, List<String, DefaultAllocator>*, List<String, DefaultAllocator>*, Variant*) (??:0)
[4] ResourceImporterTexture::import(String const&, String const&, HashMap<StringName, Variant, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, Variant> > > const&, List<String, DefaultAllocator>*, List<String, DefaultAllocator>*, Variant*) (??:0)
[5] EditorFileSystem::_reimport_file(String const&, HashMap<StringName, Variant, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, Variant> > > const*, String const&) (??:0)
[5] EditorFileSystem::_reimport_file(String const&, HashMap<StringName, Variant, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, Variant> > > const*, String const&) (??:0)
[5] EditorFileSystem::_reimport_file(String const&, HashMap<StringName, Variant, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, Variant> > > const*, String const&) (??:0)
[3] Object::_predelete() (??:0)
[6] EditorFileSystem::_reimport_thread(unsigned int, EditorFileSystem::ImportThreadData*) (??:0)
[6] EditorFileSystem::_reimport_thread(unsigned int, EditorFileSystem::ImportThreadData*) (??:0)
[4] predelete_handler(Object*) (??:0)
[6] EditorFileSystem::_reimport_thread(unsigned int, EditorFileSystem::ImportThreadData*) (??:0)
[7] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x286100a) [0x5636a0e6200a] (??:0)
[7] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x286100a) [0x5636a0e6200a] (??:0)
[7] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x286100a) [0x5636a0e6200a] (??:0)
[5] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x14d307b) [0x56369fad407b] (??:0)
[8] WorkerThreadPool::_process_task(WorkerThreadPool::Task*) (??:0)
[6] Node::_notification(int) (??:0)
[8] WorkerThreadPool::_process_task(WorkerThreadPool::Task*) (??:0)
[9] WorkerThreadPool::_native_low_priority_thread_function(void*) (??:0)
[8] WorkerThreadPool::_process_task(WorkerThreadPool::Task*) (??:0)
[9] WorkerThreadPool::_native_low_priority_thread_function(void*) (??:0)
[7] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x11f3a7a) [0x56369f7f4a7a] (??:0)
[10] Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) (??:0)
[8] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x18a67f5) [0x56369fea77f5] (??:0)
[10] Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) (??:0)
[9] WorkerThreadPool::_native_low_priority_thread_function(void*) (??:0)
[9] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x18a717f) [0x56369fea817f] (??:0)
[11] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x5301fce) [0x5636a3902fce] (??:0)
[11] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x5301fce) [0x5636a3902fce] (??:0)
[10] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x18a7b09) [0x56369fea8b09] (??:0)
[12] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x5301e97) [0x5636a3902e97] (??:0)
[12] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x5301e97) [0x5636a3902e97] (??:0)
[10] Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) (??:0)
[13] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x5301d53) [0x5636a3902d53] (??:0)
[13] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x5301d53) [0x5636a3902d53] (??:0)
[11] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x2e0912d) [0x5636a140a12d] (??:0)
[14] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x5301cba) [0x5636a3902cba] (??:0)
[14] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x5301cba) [0x5636a3902cba] (??:0)
[11] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x5301fce) [0x5636a3902fce] (??:0)
[12] Object::notification(int, bool) (??:0)
[15] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x5301ca0) [0x5636a3902ca0] (??:0)
[15] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x5301ca0) [0x5636a3902ca0] (??:0)
[12] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x5301e97) [0x5636a3902e97] (??:0)
[13] Object::_predelete() (??:0)
[16] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x5e76013) [0x5636a4477013] (??:0)
[16] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x5e76013) [0x5636a4477013] (??:0)
[13] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x5301d53) [0x5636a3902d53] (??:0)
[14] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x5301cba) [0x5636a3902cba] (??:0)
[17] /usr/lib/libc.so.6(+0x868fd) [0x7fc2e32dc8fd] (??:0)
[14] predelete_handler(Object*) (??:0)
[17] /usr/lib/libc.so.6(+0x868fd) [0x7fc2e32dc8fd] (??:0)
[15] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x5301ca0) [0x5636a3902ca0] (??:0)
[15] /home/marcin/src/vendor/godot/bin/godot.linuxbsd.editor.dev.x86_64(+0x10a4d08) [0x56369f6a5d08] (??:0)
[18] /usr/lib/libc.so.6(+0x108a60) [0x7fc2e335ea60] (??:0)
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

* Unpack, import and open the MRP. The Godot Editor should crash during opening the project
* remove `reflections/sky_reflections/texture_array_reflections=false` setting from the `project.godot` file. Now the editor should open the project.

### Minimal reproduction project

[ProjectSettingsCrashMRP.zip](https://github.com/godotengine/godot/files/10419843/ProjectSettingsCrashMRP.zip)

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/71444
Fixes: https://github.com/godotengine/godot/issues/56747

The core of the issue here comes from how we reuse mipmap layers for the quarter-res and half-res buffers. We only allocate a number of mipmaps equal to the lesser of mipmaps (based on the size of the radiance map) and ``rendering/reflections/sky_reflections/roughness_layers`` when ``texture_array_reflections`` is ``false``. In #71444 this means we only allocate two mipmaps (one for for res, one for half res). 

Currently, this makes the check for the quarter res validity fail as we attempt to read from an invalid index. This PR checks that the index actually exists before attempting to read from it. If it does not exist, we fall back to the default texture. This is enough to  fix #71444

However, there is still a crash when trying to render to the quarter res buffer. Accoridngly, I added a check and a warning to ensure that users can't render to the quarter res buffer unless there are enough roughness layers allocated

Finally, the crash in #56747 has a similar root cause, but it comes from reflection probes. The reflection probe update logic is as follows:
1. Update layer 1 over 6 frames (one face per frame)
2. update layer 2 over 6 frames (one face per frame)
3. update layer 3 in one frame
4. Check if we have exceeded the number of roughness layers, exit if so otherwise proceed to next layer
5. repeat

This logic always read from at least 3 layers before checking if the max layer was reached. I just duplicated code from above to make that check after updating layers 1 and 2 so the function can properly end once the max layers has been reached.

### CODE REVIEW

File: servers/rendering/renderer_rd/storage_rd/light_storage.cpp [hunk 1]
```diff
@@ -1552,6 +1552,12 @@ bool LightStorage::reflection_probe_instance_postprocess_step(RID p_instance) {
 	if (rpi->processing_side == 6) {
 		rpi->processing_side = 0;
 		rpi->processing_layer++;
+		if (rpi->processing_layer == atlas->reflections[rpi->atlas_index].data.layers[0].mipmaps.size()) {
+			rpi->rendering = false;
+			rpi->processing_side = 0;
```
Comment (akien-mga) [inline servers/rendering/renderer_rd/storage_rd/light_storage.cpp:1557]: This is redundant with line 1553. Shouldn't hurt, and might prevent potential bugs if line 1553 is changed, but I think some static analysis tools may complain about it?

Comment (clayjohn) [reply servers/rendering/renderer_rd/storage_rd/light_storage.cpp:1557]: I'll just remove it then. I copied it to keep it the same as the check above, but it would be better just to remove the redundancy

Comment (clayjohn) [reply servers/rendering/renderer_rd/storage_rd/light_storage.cpp]: Done!

**Comment by clayjohn** [comment]
Updated to remove the redundant line!

File: servers/rendering/renderer_rd/environment/sky.cpp [hunk 2]
```diff
@@ -1323,7 +1323,7 @@ void SkyRD::update_radiance_buffers(Ref<RenderSceneBuffersRD> p_render_buffers,
 
 		// Note, we ignore environment_get_sky_orientation here as this is applied when we do our lookup in our scene shader.
 
-		if (shader_data->uses_quarter_res) {
+		if (shader_data->uses_quarter_res && roughness_layers >= 3) {
```
Comment (BastiaanOlij) [inline servers/rendering/renderer_rd/environment/sky.cpp:1326]: We need to do more testing with this. The most likely scenario where we're using quarter or half res is on mobile, and on mobile by default reflection texture atlas is turned off so it is likely we won't have working quarter or half res sky in the use case its most needed.

I think we need to consider creating separate textures for quarter and half res, seeing the most likely use case we won't be creating the reflection textures there isn't that much of a risk of allocated double memory.

Comment (BastiaanOlij) [reply servers/rendering/renderer_rd/environment/sky.cpp:1326]: After discussing with Clay how this works, it is a little counter intuitive because we're using the same buffers, but they are being created for sky even if the setting in project settings is turned off. The added problem here is the roughness layer count now comes into play.

**Review by BastiaanOlij — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
