### PR TITLE
Make sure that `data.last_minimum_size` is consistent with `get_combined_minimum_size()` at the same time (reverted)

### LINKED ISSUE #74052: Label + [autowrap] in VBoxContainer changes its size at startup (like line_spacing)
### Godot version

v4 RC3 - RC6

### System information

Windows 10

### Issue description

If a Label with any autowrap enabled is in the VBoxContainer, then depending on the type of autowrap, the Label size changes along the Y axis when it is first displayed (or the project is launched). As if at this moment the line_spacing parameter increases. If you change line_spacing through the code after the program is launched (the project file is attached), then everything immediately falls into place, and in all the Labels of this container.
I understand that this is not a great problem and it can be circumvented with one line of code, however, I spent several hours trying to figure out why my Popup window does not take the correct size at the time of the first call, and why everything falls into place after the second call. It turns out I had a VBoxContainer with Labels there, which behaved like this.
PS: changing the size of the main window, apparently, leads to a forced redrawing of the Labels, and also everything falls into place.
label_test

### Steps to reproduce

image
The autowrap parameter for Labels should be different from OFF

### Minimal reproduction project

The project is attached. By clicking on the buttons or changing the screen size, you can see this issue.
[_labels_test.zip](https://github.com/godotengine/godot/files/10840488/_labels_test.zip)

### PR DESCRIPTION
**Pull request by Rindbee**
Move the code for switching `data.minimum_size_valid` in `Control::update_minimum_size()` to `Control::_update_minimum_size()`, make sure to switch `data.minimum_size_valid` to `false` only before updating `data.last_minimum_size` , so that it will remain consistent with `get_combined_minimum_size()`.

Fixes #74052.
Supersedes #77573. In the method connected to the `minimum_size_changed` signal, the result obtained by using `get_combined_minimum_size()` is consistent with `data.last_minimum_size`.

Works fine with #77280.

### CODE REVIEW

File: scene/gui/box_container.cpp [hunk 1]
```diff
@@ -296,6 +296,7 @@ void BoxContainer::_update_theme_item_cache() {
 
 void BoxContainer::_notification(int p_what) {
 	switch (p_what) {
+		case NOTIFICATION_POST_ENTER_TREE:
```
Comment (KoBeWi) [inline scene/gui/box_container.cpp:299]: This doesn't seem necessary. The PR still fixes the issue without this line and it's not something other containers do.

File: scene/gui/control.cpp [hunk 2]
```diff
@@ -3267,11 +3265,8 @@ void Control::_notification(int p_notification) {
 				if (get_viewport() != nullptr) {
 					get_viewport()->_gui_hide_control(this);
 				}
-			} else {
-				data.minimum_size_valid = false;
-				_update_minimum_size();
-				_size_changed();
 			}
+			_update_minimum_size();
```
Comment (KoBeWi) [inline scene/gui/control.cpp:3269]: Is there any point in updating minimum size if the Control is invisible?

**Comment by KoBeWi** [comment]
I can understand what this PR does, but I didn't delve why it works. But it fixes the linked issue; I didn't test with any project though (yet).
However seems like the code needs some cleanup (see my comments). It feels like you tried a couple of solutions until it worked and there are unnecessary leftover changes.

File: scene/gui/box_container.cpp (hunk 1 above)
Comment (Rindbee) [reply scene/gui/box_container.cpp:299]: Yes, it is not necessary. I intend to make the child controls aware of the drawable size early on, but the minimum size needs to be updated at least twice to be determined (after applying #77280).

File: scene/gui/control.cpp (hunk 2 above)
Comment (Rindbee) [reply scene/gui/control.cpp:3269]: Let the parent container recalculate the size instead of continuing to use the cached minimum size.

Comment (KoBeWi) [reply scene/gui/control.cpp:3269]: But containers ignore invisible children.

File: scene/gui/box_container.cpp (hunk 1 above)
Comment (KoBeWi) [reply scene/gui/box_container.cpp:299]: If this line is a part of another issue, it should be removed from this PR.

File: scene/gui/control.cpp [hunk 3]
```diff
@@ -1620,6 +1604,21 @@ void Control::update_minimum_size() {
 		return;
 	}
 
+	Size2 minsize = get_combined_minimum_size();
```
Comment (Rindbee) [inline scene/gui/control.cpp:1607]: Ensuring that `data.minimum_size_valid` is changed from `false` to `true` only happens here. 

Previously switched to `false` in `update_minimum_size()`, `get_combined_minimum_size()` may have been called multiple times before getting here.

File: scene/gui/control.cpp (hunk 2 above)
Comment (Rindbee) [reply scene/gui/control.cpp]: Yes, a change in visibility of a child control will notify the parent container to update the minimum size. Not necessary here.

**Review by KoBeWi — APPROVED** [review]
I tested some GUI projects and didn't see any problems. It fixes the issue, so it's probably fine.

**Review by YuriSizov — APPROVED** [review]
I'm a bit concerned that we are now calling all this invalidation logic on visibility changes. The idea is fine, but it also signals to the owning window that controls have changed, multiple times, from every child of the node that has changed its visibility. At the moment, `child_controls_changed` has guards, so it's probably not going to making anything worse, but it's still a bit concerning.

**Comment by YuriSizov** [comment]
Thanks!

**Comment by akien-mga** [comment]
Reverted by #78009.
