### PR TITLE
SkeletonIK3D: Avoid holding hard pointers to Skeleton3D

### LINKED ISSUE #77464: SkeletonIK3D use-after-free if Skeleton3D is freed
### Godot version

4.1dev 4c677c88

### System information

Windows 10

### Issue description

A use-after-free situation exists in SkeletonIK3D because it holds hard references to both SkeletonIK3D and the target node Node3D.

### Steps to reproduce

1. Open the attached reference project.
2. It should already have a scene named `vrm_1_constraint_twist_sample.tscn` open. If not, open that specific scene.
3. Select the SkeletonIK3D node and click Play IK in the toolbar (this step is usually not necessary)
4. Middle click the scene tab or close the scene tab another way.
5. It crashes because bones._cowdata._ptr[172] and higher (up to [400]) have corrupt data on my system. This type of memory corruption is often caused by use-after-free.

That said, due to the nature of memory allocations and undefined behavior, this problem may be uniquely reproducible on my system.

### Minimal reproduction project

[crash_when_closing_tab.zip](https://github.com/godotengine/godot/files/11561795/crash_when_closing_tab.zip)

### PR DESCRIPTION
**Pull request by lyuma**
Use a Variant to hold references across frames.

Fixes #77464

After doing research and discussing a similar issue with others, I determined that this is the best course of action and ought to be a convention of sorts.

The alternative, which is used elsewhere in Godot, would be to use `get_parent()` every frame to access the Skeleton3D. I'm not sure why it was not written this way. I did not want to risk changing behavior in case scripts depend on reparenting, but I'm open to doing it this way if it's better. (My fear was that the code caches a lot of information and assumes the Skeleton3D does not change across frames, so it would need to check for the reference changing.)

For the target node, I have to decide between using `Variant` or calling `get_node()` every frame, so I'm open to either approach.

### CODE REVIEW

File: scene/3d/skeleton_ik_3d.cpp [hunk 1]
```diff
@@ -523,6 +524,10 @@ void SkeletonIK3D::set_max_iterations(int p_iterations) {
 	max_iterations = p_iterations;
 }
 
+Skeleton3D *SkeletonIK3D::get_parent_skeleton() const {
+	return cast_to<Skeleton3D>((Object *)skeleton_ref);
```
Comment (AThousandShips) [inline scene/3d/skeleton_ik_3d.cpp:528]: This doesn't catch cases when the skeleton is freed, I think you need
```suggestion
	return cast_to<Skeleton3D>(skeleton_ref.get_validated_object());
```

Comment (lyuma) [reply scene/3d/skeleton_ik_3d.cpp]: Wow, I had assumed that `Variant::operator Object*` validates the ObjectID. good to know. Changed to get_validated_object.

Comment (AThousandShips) [reply scene/3d/skeleton_ik_3d.cpp]: It avoids doing so for performance

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
