### PR TITLE
Change Node `set_name` to use StringName, slightly improves performance

### LINKED ISSUE #96805: Node::set_name and Node::get_name have inconsistent types
### Tested versions

- 4.3-stable

### System information

- Windows 10

### Issue description

Node::set_name is expecting a String parameter, while Node::get_name returns a StringName.
This is not an issue when using GDScript as the language can seamlessly use both, but it is for third party languages that can use properties. 
When generating bindings for the Kotlin language, the `name` property for Node doesn't compile because of the difference in type between getter and setter. The language doesn't have implicit conversion like C++ or GDScript. To bypass this, we use StringName for both and rely on the C++ Variant  ability to cast it back to String when calling `MethodBind::call`, but soon we will switch to `MethodBind::ptrcall` for optimization purposes and I think this won't work anymore.

### Steps to reproduce

-

### Minimal reproduction project (MRP)

-

### PR DESCRIPTION
**Pull request by aaronfranke**
This PR changes the `Node::set_name()` method to use StringName. This code skips StringName construction in the case where the desired name is already a valid node name. This improves performance by about 15% to 20% in my testing in the case where the desired name is already valid (the common case, the happy code path).

The code has been split up into multiple methods. `invalid_node_name_index()` finds the index of the first character that would be invalid for a node name. Then this is passed to `validate_node_name_internal()` which starts replacing the invalid characters from that index. The same logic used to exist combined into one method, but having it be separate allows us to speed up `Node::set_name()`. The logic in `invalid_node_name_index()` is even slightly simpler because it doesn't have to keep track of `bool valid`, it just returns if invalid. However, the existing `validate_node_name()` is still present as a wrapper, for being exposed to GDScript and is also used in many other parts of the codebase. I also renamed some local variables for readability. I'm open to any suggestions if this can be improved further.

Test and benchmarking code:

```gdscript
func _ready():
	var nodes: Array = []
	for i in range(1000000):
		nodes.append(Node.new())
	var start_time = Time.get_ticks_usec()
	for i in range(1000000):
		nodes[i].set_name(&"MyStringName")
	var end_time = Time.get_ticks_usec()
	print("Time elapsed: " + str(end_time - start_time))
```

Results:

Without calling set_name, just accessing the array:  
Time elapsed: 28971 (varies between about 25k and 30k)

This PR with valid name, skips StringName construction:  
Time elapsed: 132565 (varies between about 120k and 140k)

This PR with invalid name:  
Time elapsed: 220087 (varies between about 200k and 230k)

Current master with valid name:  
Time elapsed: 160325 (varies between about 150k and 170k)

Current master with invalid name:  
Time elapsed: 213259 (varies between about 190k and 220k)

I also did some testing with longer StringNames and the speed improvement gets more significant as length increases.

* *Bugsquad edit, closes: https://github.com/godotengine/godot/issues/96805*

### CODE REVIEW

**Comment by aaronfranke** [comment]
Since this breaks ABI compatibility, what can I do to preserve compatibility?

**Comment by dsnopek** [comment]
> Since this breaks ABI compatibility, what can I do to preserve compatibility?

This should be addressable via `bind_compatibility_method()` (following the usual pattern with `node.compat.inc`, and `_bind_compatibility_methods()`, etc - take a look at one of the examples already in the engine, ie in `TileMap`)

And after that you should remove this line from the expected errors (it won't be needed once you add the compatibility method):

```
Validate extension JSON: Error: Hash changed for 'classes/Node/methods/set_name', from 04FD3184 to C4FB126E.
```

File: scene/main/node.h [hunk 1]
```diff
@@ -327,6 +327,11 @@ class Node : public Object {
 	GDVIRTUAL1(_unhandled_input, Ref<InputEvent>)
 	GDVIRTUAL1(_unhandled_key_input, Ref<InputEvent>)
 
+#ifndef DISABLE_DEPRECATED
+	void set_name_76560(const String &p_name);
```
Comment (RedworkDE) [inline scene/main/node.h:331]: IIRC the `_bind_compatibility_methods` generally is listed first

**Review by RedworkDE — COMMENTED** [review]
And `Validate extension JSON: Error: Field 'classes/Node/methods/set_name/arguments/0': type changed value in new API, from "String" to "StringName".` needs to be added to `4.1-stable.expected` instead of the hash error that you removed.

File: scene/main/node.h (hunk 1 above)
Comment (aaronfranke) [reply scene/main/node.h:331]: In the current code, it's listed after in every case.

**Comment by raulsntos** [comment]
This doesn't break compatibility in C# because we don't expose the property accessors, so no additional changes should be needed for C#.

With this PR, we likely don't need to special-case this anymore in the C# bindings generator:

https://github.com/godotengine/godot/blob/6afd320984cf14198368cc6c53752813a02169e3/modules/mono/editor/bindings_generator.cpp#L1951-L1953

File: scene/main/node.h (hunk 1 above)
Comment (AThousandShips) [inline scene/main/node.h:331]:
```suggestion
	void _set_name_bind_compat_76560(const String &p_name);
```
Established naming at this point 🙂

File: misc/extension_api_validation/4.2-stable.expected
Comment (AThousandShips) [inline misc/extension_api_validation/4.2-stable.expected:1]: This should be at the end of the file

Comment (aaronfranke) [reply misc/extension_api_validation/4.2-stable.expected:1]: I thought they were ordered by PR number? That would make more sense than ordering by having the newest entries at the bottom, because that means we'll get Git conflicts every time a PR adds text to the bottom (we could still get conflicts if it's ordered by PR number but hopefully not as much as "every time").

Comment (AThousandShips) [reply misc/extension_api_validation/4.2-stable.expected:1]: It says in the instructions 🙂

File: misc/extension_api_validation/4.2-stable.expected [hunk 2]
```diff
@@ -160,3 +160,10 @@ Validate extension JSON: JSON file: Field was added in a way that breaks compati
 Validate extension JSON: JSON file: Field was added in a way that breaks compatibility 'classes/RenderSceneBuffersRD/methods/get_velocity_texture': arguments
 
 MSAA flag was added, compatibility functions exist for these.
+
+
+GH-76560
+--------
+Validate extension JSON: Error: Field 'classes/Node/methods/set_name/arguments/0': type changed value in new API, from "String" to "StringName".
```
Comment (Bromeon) [inline misc/extension_api_validation/4.2-stable.expected:167]: This error still appears even with compatibility method registered?

File: misc/extension_api_validation/4.1-stable_4.2-stable.expected [hunk 3]
```diff
@@ -1,10 +1,5 @@
-This file contains the expected output of --validate-extension-api when run against the extension_api.json of the
-4.1-stable tag (the basename of this file).
-
-Only lines that start with "Validate extension JSON:" matter, everything else is considered a comment and ignored. They
-should instead be used to justify these changes and describe how users should work around these changes.
-
-Add new entries at the end of the file.
+This file contains, when concatenated to the expected output since 4.2, the expected output of --validate-extension-api
+when run against the extension_api.json of the 4.1-stable tag (first part of the basename of this file).
```
Comment (Bromeon) [inline misc/extension_api_validation/4.1-stable_4.2-stable.expected:3]: Is this change intended? It was between 4.1 -> 4.2

File: core/string/ustring.cpp [hunk 4]
```diff
@@ -5275,47 +5275,49 @@ String String::get_invalid_node_name_characters(bool p_allow_internal) {
 	return r;
 }
 
-String String::validate_node_name() const {
-	// This is a critical validation in node addition, so it must be optimized.
-	const char32_t *cn = ptr();
-	if (cn == nullptr) {
-		return String();
+int32_t String::invalid_node_name_index() const {
```
Comment (Ivorforce) [inline core/string/ustring.cpp:5278]: I see you've split this into two functions to speed up the call.
I appreciate the thought, but I don't think this change is needed. 

Returning `*this` as in `validate_node_name` is near instantaneous (in the context of this function, and `set_name` in general. Try your PR without this change, I'd be surprised if it made any measurable speed difference :)

**Review by Ivorforce — COMMENTED** [review]
This PR is very welcome! I had actually considered proposing this myself at some point, since it has very obvious performance improvement potential.
The slight slow down on invalid name calls is expected but acceptable as the cold path.

I think however your change can be made a bit simpler by focusing on the main proposal of changing the parameter, I don't think the change to `validate_node_name` is needed :)

File: core/string/ustring.cpp (hunk 4 above)
Comment (aaronfranke) [reply core/string/ustring.cpp:5278]: @Ivorforce No, it's not a simple CoW thing. Constructing a new StringName is not a cheap operation. I tested not using this function and the performance was worse than master. This function is necessary.

Comment (Ivorforce) [reply core/string/ustring.cpp:5278]: No, `StringName` construction is indeed not cheap! I would do something like this to avoid it:

```c++
String node_name_string = String(node_name);
String validated_node_name_string = .validate_node_name();
if (node_name_string != validated_node_name_string) {
    node_name = StringName(validated_node_name_string);
}
```

This should be just about as fast as what you currently have in your PR.

Comment (aaronfranke) [reply core/string/ustring.cpp:5278]: Oh, I see, that makes sense. I did some testing and that seems to give like 70-80% the performance improvement of this PR, while having a cleaner API. Do you think it's worth going with your suggestion or with this PR as-is?

Comment (Ivorforce) [reply core/string/ustring.cpp:5278]: I don't want to nitpick; if it makes such a big difference then your approach is definitely better :)

File: scene/main/node.cpp [hunk 5]
```diff
@@ -1388,17 +1389,25 @@ void Node::_set_name_nocheck(const StringName &p_name) {
...
-void Node::set_name(const String &p_name) {
+void Node::set_name(const StringName &p_name) {
 	ERR_FAIL_COND_MSG(data.inside_tree && !Thread::is_main_thread(), "Changing the name to nodes inside the SceneTree is only allowed from the main thread. Use `set_name.call_deferred(new_name)`.");
-	String name = p_name.validate_node_name();
-
-	ERR_FAIL_COND(name.is_empty());
+	StringName new_name;
+	{
+		String input_name_str = p_name;
+		ERR_FAIL_COND(input_name_str.is_empty());
```
Comment (Ivorforce) [inline scene/main/node.cpp:1397]: Would be nice to have an error message here, how about the same as you have in `ustring.cpp`?

File: scene/main/node.cpp [hunk 6]
```diff
@@ -1388,17 +1389,25 @@ void Node::_set_name_nocheck(const StringName &p_name) {
...
+		}
+	}
 
 	if (data.unique_name_in_owner && data.owner) {
 		_release_unique_name_in_owner();
 	}
-	String old_name = data.name;
-	data.name = name;
+	StringName old_name = data.name;
+	data.name = new_name;
```
Comment (Ivorforce) [inline scene/main/node.cpp:1410]: You can save an assignment by setting `old_name` at the top of the function, and not having `new_name` at all, instead just assigning to `data.name` directly.

**Review by Ivorforce — APPROVED** [review]
Looks good code wise. I cannot vouch for the correctness of the compat header, but it looks correct too.

To re-iterate, I agree this is a good change. It's always good to match parameters closely to what is actually needed, and the tests show it's impactful.

I think there is one case where it breaks compatibility to GDScript code, which would be `NodePath` arguments:
```gdscript
set_name(^"Test")
```

However, I think this is acceptable.

File: core/string/ustring.cpp (hunk 4 above)
Comment (aaronfranke) [reply core/string/ustring.cpp:5433]: Well, it's a small difference between your solution and mine, but a big difference between either and master.

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected. Code looks good to me.

**Testing project:** [test_node_stringname_performance.zip](https://github.com/user-attachments/files/19795666/test_node_stringname_performance.zip)
Same benchmark as in OP, but with 5 million iterations for each scenario instead of 1 million to reduce variance. (10 million will crash due to the node count being too high, even in `master`.)

## Benchmark

<details open>

<summary>PC specifications</summary>

- **CPU:** Intel Core i9-13900K
- **GPU:** NVIDIA GeForce RTX 4090
- **RAM:** 64 GB (2×32 GB DDR5-5800 C30)
- **SSD:** Solidigm P44 Pro 2 TB
- **OS:** Linux (Fedora 41)
</details>

Using a release optimized export template (`production=yes lto=full`).

### `master`

```
Time elapsed (valid name): 514795 usecs
Time elapsed (invalid name): 642047 usecs
```

### This PR

```
Time elapsed (valid name): 458555 usecs
Time elapsed (invalid name): 654856 usecs
```

**Comment by Repiteo** [comment]
Needs rebase

**Comment by Repiteo** [comment]
Thanks!
