### PR TITLE
Fix renaming a node to the name of its siblings breaking NodePath

### LINKED ISSUE #76192: Renaming a name present in a NodePath to an invalid name will wrongly update the NodePath
### Godot version

4.1.dev (4d5f10fc3a)

### System information

MacOS 13.3 M1 Pro

### Issue description

If you have a NodePath pointing to a node and you rename a node on this path to a value that is already used by one of his siblings, the NodePath will be updated with the value you set while the node will be updated with another unused value created by adding a number after the value you set.

### Steps to reproduce

1. create a root and two children
2. On the root export a NodePath and set it to one of the children
3. Rename the referenced child to the name of the other child
4. now the NodePath points to the other child

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by ajreckof**
rebase and updated version of #76575
Fix #76192
I also fix another issue where there was cases where node name was not visually updated because name was changed to an invalid node name which was automatically changed to a valid one which happens to be the previous name of the node which cancels renaming.
This issue was already present with invalid character and this PR added the same for renaming to the name of a sibling.

### CODE REVIEW

File: scene/main/node.h [hunk 1]
```diff
@@ -614,6 +614,7 @@ class Node : public Object {
 
 #ifdef TOOLS_ENABLED
 	String validate_child_name(Node *p_child);
+	String prevalidate_child_name(Node *p_child, StringName p_name);
```
Comment (AThousandShips) [inline scene/main/node.h:617]:
```suggestion
	String prevalidate_child_name(Node *p_child, const StringName &p_name);
```

**Review by KoBeWi — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!
