### PR TITLE
[Windows] Only use long executable path when necessary, fix broken apksigner detection.

### LINKED ISSUE #95070: All located 'apksigner' tools in /home/apollo/Android/Sdk/build-tools failed to execute
### Tested versions

4.2.2(stable)

### System information

Distributor ID:	Ubuntu Description: Ubuntu 22.04.4 LTS Release:	22.04 

### Issue description

```editor/export/editor_export_platform.h:179 - Code Signing: All 'apksigner' tools located in Android SDK 'build-tools' directory failed to execute. Please check that you have the correct version installed for your target sdk version. The resulting APK is unsigned.```
```All located 'apksigner' tools in /home/apollo/Android/Sdk/build-tools failed to execute```

i followed the docs to export and debug my game on android but i get this error every time I'm trying to export for days now.
tried installing all version of build-tools and changing the keystore and some solutions out there but nothing works 

### Steps to reproduce

just exporting to android following the steps in the docs

### Minimal reproduction project (MRP)

tried it with all my projects

### LINKED ISSUE #96762: Android export failing on Windows
### Tested versions

Experienced this bug in:
- Master [d0dc3896a]
- [78883a52c64adbab56aaa363138a9f661a67d48e]

Bug does not take place in:
- 4.3-stable

### System information

Godot v4.4.dev (d0dc3896a) - Windows 10.0.22631 - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 4070 (NVIDIA; 31.0.15.3161) - Intel(R) Core(TM) i7-14700K (28 Threads)

### Issue description

When attempting to export an XR project to my Quest 3, the export fails and I get the following error:

```
C:\Users\langl\workspace\godot\editor\export\editor_export_platform.h:227 - Export: Building of Android project failed, check output for the error:
  
The system cannot find the path specified.

Cannot remove non-existent file or directory: C:/Users/langl/AppData/Local/Godot/tmpexport.1725898406.apk
```

### Steps to reproduce

Just export the project to an android device, in my case, from Windows to Quest 3.

### Minimal reproduction project (MRP)

I'm testing using the demo project from the [OpenXR Vendors Repo](https://github.com/GodotVR/godot_openxr_vendors).

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/96762

Seems like Windows does not support `\\?\` prefixed long paths when running batch files (works fine with executables), so use for OS execute methods only if path is longer than 260 characters.

Fixes https://github.com/godotengine/godot/issues/95070

`apksigner` can't run without valid `JAVA_HOME` set, and it was updated only after it is called.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: platform/windows/os_windows.cpp [hunk 1]
```diff
@@ -101,7 +101,7 @@ static String fix_path(const String &p_path) {
 	}
 	path = path.simplify_path();
 	path = path.replace("/", "\\");
-	if (!path.is_network_share_path() && !path.begins_with(R"(\\?\)")) {
+	if (!path.is_network_share_path() && !path.begins_with(R"(\\?\)") && path.size() >= MAX_PATH) {
```
Comment (akien-mga) [inline platform/windows/os_windows.cpp:104]: Doesn't matter much, but I feel like the new check could be the first, and shortcircuit the rest if this necessary condition isn't met.
```suggestion
	if (path.size() >= MAX_PATH && !path.is_network_share_path() && !path.begins_with(R"(\\?\)")) {
```

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1. (Only the Android fix, the other one is a 4.4-only regression fix.)
