### PR TITLE
Enforce custom nodes to keep their original type

### LINKED ISSUE #7905: Enforce that custom nodes/resources keep their original type (assigned script)
### Describe the project you are working on

Improvement to Godot's custom node and resource type handling.
https://github.com/godotengine/godot-proposals/discussions/7808

### Describe the problem or limitation you are having in your project

Currently Godot's custom node/resource types are no different than native nodes/resources with a script attached to them. The problem with that is that plugins exposing custom node types and resources with systems functionality (AI for example) are no different than scripted nodes by the user with game logic. Extending a plugins node to add ones own game logic to it and then clearing the extension to that node in a later stage, also clears its original script, turning it into a naked native node and losing the fundamental logic it was meant to perform.

A similar problem happens with resources. The script of a custom resource type can accidentally be cleared, effectively changing it's underlying type.

A custom node type or resource type, once created, should retain it's baseline type, just like native nodes or resources do. This is an intuitive expectation I believe most users have.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Custom node types will have a faded script icon. This script cannot be cleared.
image

An additional property "Custom Type Script" will hold it's underlying type (only visible in the inspector with DEBUG_ENABLED). This will be the fallback script in case "Script" is cleared.
image

When a custom node holds an extension to it's type, it's script icon is shown in full color.
image

"Script" will hold the extension script as normal.
image

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

An additional property "custom_type_script" has been added next to "script" inside Object. When a custom type object is instantiated, both "custom_type_script" and "script" are set. "custom_type_script" defines the baseline type of this object and will be the fallback in case "script" is cleared by the user. A check is also performed so that "script" must be a valid extension of "custom_type_script". These checks are currently in form of warnings, but can be changed in a later stage to actively prevent setting an incompatible script.

**Note for C#**: When running a project, there will be several warnings that "Script" was set to null, not respecting the existence of a "custom_type_script" as baseline. This happens during C# domain reload where scripts are detached from all objects and re-attached after reload.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I would say, no.

### Is there a reason why this should be core and not an add-on in the asset library?

I believe this needs to be part of Godot's core functionality, to make a clear distinction for the user between different node types:
- Native nodes, that carry core engine system functionality
- Custom nodes, that carry systems functionality (i.e. AI system provided by a plugin)
- Scripted nodes, that carry game logic

### LINKED ISSUE #37479: Change Type with GDScript types / attached scripts does nothing.
**Godot version:** 3.2.1 / master (a2da99f40cf2123c0906c734a2eb01e9b65a45a2)

**OS/device including version:** Windows 10

**Issue description:**
Using Change Type on a node with an attached script (notably scripts with `class_name`s and hence appearing as types in Add Child dialogs) does nothing.

**Steps to reproduce:**
* Provided Reproduction
  * Create two scripts with `class_name`s (`A` and `B`).
  * Create a new node with with one of the types (`A`)
* Change type on the node to the other type (`B`)

**Minimal reproduction project:** [TempTest.zip](https://github.com/godotengine/godot/files/4412229/TempTest.zip)

### PR DESCRIPTION
**Pull request by bjornmp**
Replaces PR https://github.com/godotengine/godot/pull/82684 with a move away from Core/Object in favor of ~~Scene/Main/Node~~ metadata usage.

Closes https://github.com/godotengine/godot-proposals/issues/7905
Closes #37479

### CODE REVIEW

File: editor/editor_resource_picker.h [hunk 1]
```diff
@@ -81,6 +81,8 @@ class EditorResourcePicker : public HBoxContainer {
 		CONVERT_BASE_ID = 1000,
 	};
 
+	Object *Owner = nullptr;
```
Comment (AThousandShips) [inline editor/editor_resource_picker.h:84]:
```suggestion
	Object *_owner = nullptr;
```

File: editor/editor_resource_picker.cpp [hunk 2]
```diff
@@ -924,6 +932,10 @@ void EditorResourcePicker::set_toggle_pressed(bool p_pressed) {
 	assign_button->set_pressed(p_pressed);
 }
 
+void EditorResourcePicker::set_owner(Object *p_object) {
+	Owner = p_object;
```
Comment (AThousandShips) [inline editor/editor_resource_picker.cpp:936]:
```suggestion
	_owner = p_object;
```

File: editor/editor_resource_picker.cpp [hunk 3]
```diff
@@ -216,7 +218,13 @@ void EditorResourcePicker::_update_menu_items() {
 		}
 
 		if (is_editable()) {
-			edit_menu->add_icon_item(get_editor_theme_icon(SNAME("Clear")), TTR("Clear"), OBJ_MENU_CLEAR);
+			if (Owner && Owner->has_meta("__custom_type_script")) {
```
Comment (AThousandShips) [inline editor/editor_resource_picker.cpp:221]:
```suggestion
			if (_owner && _owner->has_meta("__custom_type_script")) {
```

File: editor/editor_resource_picker.h [hunk 4]
```diff
@@ -134,6 +136,8 @@ class EditorResourcePicker : public HBoxContainer {
 	bool is_toggle_mode() const;
 	void set_toggle_pressed(bool p_pressed);
 
+	void set_owner(Object *p_object);
```
Comment (AThousandShips) [inline editor/editor_resource_picker.h:139]: This shadows a method in `Node`, you need to name it something else, you shouldn't use this method to achieve this

**Review by AThousandShips — DISMISSED** [review]

File: editor/editor_data.cpp [hunk 5]
```diff
@@ -534,6 +534,7 @@ Variant EditorData::instantiate_custom_type(const String &p_type, const String &
 				if (n) {
 					n->set_name(p_type);
 				}
+				n->set_meta("__custom_type_script", script);
```
Comment (KoBeWi) [inline editor/editor_data.cpp:537]: Meta keys use StringName, so `"__custom_type_script"` should either use SNAME, or better, be registered in core string names.

File: editor/editor_node.cpp [hunk 6]
```diff
@@ -4458,6 +4458,13 @@ void EditorNode::stop_child_process(OS::ProcessID p_pid) {
 Ref<Script> EditorNode::get_object_custom_type_base(const Object *p_object) const {
 	ERR_FAIL_NULL_V(p_object, nullptr);
 
+	const Node *node = Object::cast_to<const Node>(p_object);
+	if (node) {
+		if (node->has_meta("__custom_type_script")) {
```
Comment (KoBeWi) [inline editor/editor_node.cpp:4463]:
```suggestion
	if (node && node->has_meta("__custom_type_script")) {
```

File: editor/editor_resource_picker.h [hunk 7]
```diff
@@ -81,6 +81,8 @@ class EditorResourcePicker : public HBoxContainer {
 		CONVERT_BASE_ID = 1000,
 	};
 
+	Object *_owner = nullptr;
```
Comment (KoBeWi) [inline editor/editor_resource_picker.h:84]:
```suggestion
	Object *resource_owner = nullptr;
```

File: editor/editor_resource_picker.cpp [hunk 8]
```diff
@@ -216,7 +218,13 @@ void EditorResourcePicker::_update_menu_items() {
 		}
 
 		if (is_editable()) {
-			edit_menu->add_icon_item(get_editor_theme_icon(SNAME("Clear")), TTR("Clear"), OBJ_MENU_CLEAR);
+			if (_owner && _owner->has_meta("__custom_type_script")) {
+				can_clear = false;
```
Comment (KoBeWi) [inline editor/editor_resource_picker.cpp:222]: What is this variable for? You can replace the condition below with this one. `can_clear` is not used outside this block.

File: editor/editor_resource_picker.cpp [hunk 9]
```diff
@@ -216,7 +218,13 @@ void EditorResourcePicker::_update_menu_items() {
 		}
 
 		if (is_editable()) {
-			edit_menu->add_icon_item(get_editor_theme_icon(SNAME("Clear")), TTR("Clear"), OBJ_MENU_CLEAR);
+			if (_owner && _owner->has_meta("__custom_type_script")) {
```
Comment (KoBeWi) [inline editor/editor_resource_picker.cpp:221]: You are not checking whether the current resource is script. I think this should be handled in property setup instead.

**Comment by KoBeWi** [comment]
Not sure if showing extend icon for non-custom-type scripts is a good idea:
image
It can show for scripts that can't be extended, and more importantly, takes space, which is very sparse in that area.

File: editor/scene_tree_dock.cpp [hunk 10]
```diff
@@ -2607,33 +2608,49 @@ void SceneTreeDock::_delete_confirm(bool p_cut) {
...
-		button_detach_script->hide();
-	} else if (editor_selection->get_selection().size() == 0) {
-		button_create_script->hide();
-		button_detach_script->hide();
-	} else if (editor_selection->get_selection().size() == 1) {
+	bool can_create_script = false;
+	bool can_detach_script = false;
+	bool can_extend_script = false;
+
+	if (editor_selection->get_selection().size() == 1) {
```
Comment (KoBeWi) [inline editor/scene_tree_dock.cpp:2615]: This can be integrated with the block below, as the code inside the `for` loop is the same as here.

File: editor/scene_tree_dock.cpp [hunk 11]
```diff
@@ -3265,6 +3304,15 @@ void SceneTreeDock::_script_dropped(const String &p_file, NodePath p_to) {
 		undo_redo->add_undo_method(ed, "live_debug_remove_node", NodePath(String(edited_scene->get_path_to(n)).path_join(new_node->get_name())));
 		undo_redo->commit_action();
 	} else {
+		// Check if dropped script is compatible.
+		if (n->has_meta("__custom_type_script")) {
+			Ref<Script> ct_scr = n->get_meta("__custom_type_script");
+			if (!scr->inherits_script(ct_scr)) {
+				WARN_PRINT_ED("Script does not extend type: " + ct_scr->get_global_name());
```
Comment (KoBeWi) [inline editor/scene_tree_dock.cpp:3311]: Scripts added with `add_custom_type()` will display empty name.

File: scene/property_utils.cpp [hunk 12]
```diff
@@ -65,6 +65,17 @@ Variant PropertyUtils::get_property_default_value(const Object *p_object, const
 		*r_is_valid = false;
 	}
 
+	// Handle special case "script" property, where the default value is either null or the custom type script.
+	if (p_property == SNAME("script")) {
+		if (p_object->has_meta("__custom_type_script")) {
```
Comment (KoBeWi) [inline scene/property_utils.cpp:70]:
```suggestion
	if (p_property == SNAME("script") && p_object->has_meta("__custom_type_script")) {
```

**Comment by KoBeWi** [comment]
You could try using `_property_can_revert()` and `_property_get_revert()` to handle script default. It could allow removing PackedScene changes.

**Comment by bjornmp** [comment]
- Script button "Extend" is now only shown when the script is a custom type script
- "Clear" is only removed if resource is actually a script

I haven't found a nice way around the PackedScene changes yet. As I see it, `_property_can_revert()` and `_property_get_revert()` are virtual methods. Where would be a good place to override them to get the desired effect?

**Comment by KoBeWi** [comment]
> Where would be a good place to override them to get the desired effect?

In Object. Although they are part of GDClass, so not sure if it's possible. In worst case you can put some duplicate code in Node and Resource.

**Comment by bjornmp** [comment]
I was trying to avoid changes to `core/` as much as possible with this PR, as this was requested in the last PR attempt. That's why I initially didn't use CoreStringNames.

Maybe I can get away with the changes in `packed_scene` if I add a condition in `PropertyUtils::is_property_value_different` as I already did in `PropertyUtils::get_property_default_value`.

**Comment by KoBeWi** [comment]
Can you rebase to resolve conflicts?

**Comment by bjornmp** [comment]
> Can you rebase to resolve conflicts?

Yes, will do this now.

**Comment by bjornmp** [comment]
Rebased.

File: editor/editor_data.cpp [hunk 13]
```diff
@@ -534,6 +535,7 @@ Variant EditorData::instantiate_custom_type(const String &p_type, const String &
 				if (n) {
 					n->set_name(p_type);
 				}
+				n->set_meta(CoreStringNames::get_singleton()->__custom_type_script, script);
```
Comment (KoBeWi) [inline editor/editor_data.cpp:538]:
```suggestion
				n->set_meta(CoreStringName(__custom_type_script), script);
```
New preferred way of using core stringnames.

File: editor/editor_resource_picker.cpp [hunk 14]
```diff
@@ -1076,7 +1093,16 @@ void EditorScriptPicker::set_create_options(Object *p_menu_node) {
...
+	bool allow_new_script = true;
+	if (script_owner) {
+		if (script_owner->has_meta(CoreStringName(__custom_type_script))) {
+			allow_new_script = false;
+		}
+	}
+	if (allow_new_script) {
+		menu_node->add_icon_item(get_editor_theme_icon(SNAME("ScriptCreate")), TTR("New Script..."), OBJ_MENU_NEW_SCRIPT);
+	}
+
```
Comment (KoBeWi) [inline editor/editor_resource_picker.cpp:1105]:
```suggestion
	if (!script_owner || !script_owner->has_meta(CoreStringName(__custom_type_script))) {
		menu_node->add_icon_item(get_editor_theme_icon(SNAME("ScriptCreate")), TTR("New Script..."), OBJ_MENU_NEW_SCRIPT);
	}
```

File: editor/scene_tree_dock.cpp [hunk 15]
```diff
@@ -3268,6 +3307,22 @@ void SceneTreeDock::_script_dropped(const String &p_file, NodePath p_to) {
...
 	} else {
+		// Check if dropped script is compatible.
+		if (n->has_meta(CoreStringName(__custom_type_script))) {
+			Ref<Script> ct_scr = n->get_meta(CoreStringName(__custom_type_script));
+			if (!scr->inherits_script(ct_scr)) {
+				StringName custom_type_name = ct_scr->get_global_name();
+
+				// Legacy custom type, registered with "add_custom_type()".
+				if (!custom_type_name) {
+					custom_type_name = get_editor_data()->get_custom_type_by_path(ct_scr->get_path())->name;
```
Comment (KoBeWi) [inline editor/scene_tree_dock.cpp:3318]: This is super unsafe. If something fails and the type can't be found, it will crash.
You should safeguard against `get_custom_type_by_path()` returning null.

File: scene/property_utils.cpp [hunk 16]
```diff
@@ -65,6 +66,15 @@ Variant PropertyUtils::get_property_default_value(const Object *p_object, const
 		*r_is_valid = false;
 	}
 
+	// Handle special case "script" property, where the default value is either null or the custom type script.
+	if (p_property == SNAME("script") && p_object->has_meta(CoreStringName(__custom_type_script))) {
```
Comment (KoBeWi) [inline scene/property_utils.cpp:70]:
```suggestion
	if (p_property == CoreStringName(script) && p_object->has_meta(CoreStringName(__custom_type_script))) {
```

**Review by KoBeWi — DISMISSED** [review]
Looks fine overall and also works correctly.

I realized the new `__custom_type_script` name can be moved to scene string names instead, as it's not really related to core.

**Comment by bjornmp** [comment]
I think I got all suggestions in place and also moved `CoreStringNames` to `SceneStringNames`.

File: editor/scene_tree_dock.cpp [hunk 17]
```diff
@@ -3268,6 +3307,27 @@ void SceneTreeDock::_script_dropped(const String &p_file, NodePath p_to) {
...
+			if (!scr->inherits_script(ct_scr)) {
+				StringName custom_type_name = ct_scr->get_global_name();
+
+				// Legacy custom type, registered with "add_custom_type()".
+				if (!custom_type_name) {
+					const EditorData::CustomType *custom_type = get_editor_data()->get_custom_type_by_path(ct_scr->get_path());
+					if (custom_type) {
+						custom_type_name = custom_type->name;
+					} else {
+						custom_type_name = SNAME("<unknown>");
```
Comment (KoBeWi) [inline editor/scene_tree_dock.cpp:3322]: This could be translated I think.
```suggestion
						custom_type_name = TTR("<unknown>");
```

File: editor/scene_tree_dock.cpp [hunk 18]
```diff
@@ -3268,6 +3307,27 @@ void SceneTreeDock::_script_dropped(const String &p_file, NodePath p_to) {
 		undo_redo->add_undo_method(ed, "live_debug_remove_node", NodePath(String(edited_scene->get_path_to(n)).path_join(new_node->get_name())));
 		undo_redo->commit_action();
 	} else {
+		// Check if dropped script is compatible.
+		if (n->has_meta(SceneStringName(__custom_type_script))) {
+			Ref<Script> ct_scr = n->get_meta(SceneStringName(__custom_type_script));
+			if (!scr->inherits_script(ct_scr)) {
+				StringName custom_type_name = ct_scr->get_global_name();
```
Comment (KoBeWi) [inline editor/scene_tree_dock.cpp:3314]:
```suggestion
				String custom_type_name = ct_scr->get_global_name();
```
This is purely for displaying in a warning, so it can be string. Especially when the 2 strings below are also String (when you remove SNAME).

File: editor/scene_tree_dock.cpp (hunk 17 above)
Comment (bjornmp) [reply editor/scene_tree_dock.cpp]: You're right.

File: editor/scene_tree_dock.cpp [hunk 19]
```diff
@@ -3268,6 +3307,27 @@ void SceneTreeDock::_script_dropped(const String &p_file, NodePath p_to) {
...
+				if (custom_type_name.is_empty()) {
+					const EditorData::CustomType *custom_type = get_editor_data()->get_custom_type_by_path(ct_scr->get_path());
+					if (custom_type) {
+						custom_type_name = custom_type->name;
+					} else {
+						custom_type_name = TTR("<unknown>");
+					}
+				}
+
+				WARN_PRINT_ED("Script does not extend type: " + custom_type_name);
```
Comment (bjornmp) [inline editor/scene_tree_dock.cpp:3326]: Should I add TTR to the warning message as well?

File: editor/editor_node.cpp [hunk 20]
```diff
@@ -65,6 +65,7 @@
 #include "scene/resources/image_texture.h"
 #include "scene/resources/packed_scene.h"
 #include "scene/resources/portable_compressed_texture.h"
+#include "scene/scene_string_names.h"
```
Comment (AThousandShips) [inline editor/editor_node.cpp:68]:
```suggestion
```
Available via `node.h`

File: editor/editor_data.cpp [hunk 21]
```diff
@@ -42,6 +42,7 @@
 #include "editor/plugins/script_editor_plugin.h"
 #include "editor/themes/editor_scale.h"
 #include "scene/resources/packed_scene.h"
+#include "scene/scene_string_names.h"
```
Comment (AThousandShips) [inline editor/editor_data.cpp:45]:
```suggestion
```

File: editor/editor_resource_picker.cpp [hunk 22]
```diff
@@ -46,6 +46,7 @@
 #include "scene/gui/texture_rect.h"
 #include "scene/resources/gradient_texture.h"
 #include "scene/resources/image_texture.h"
+#include "scene/scene_string_names.h"
```
Comment (AThousandShips) [inline editor/editor_resource_picker.cpp:49]:
```suggestion
```

File: editor/scene_tree_dock.cpp [hunk 23]
```diff
@@ -59,6 +59,7 @@
 #include "scene/gui/check_box.h"
 #include "scene/property_utils.h"
 #include "scene/resources/packed_scene.h"
+#include "scene/scene_string_names.h"
```
Comment (AThousandShips) [inline editor/scene_tree_dock.cpp:62]:
```suggestion
```

File: scene/property_utils.cpp [hunk 24]
```diff
@@ -31,9 +31,11 @@
 #include "property_utils.h"
 
 #include "core/config/engine.h"
+#include "core/core_string_names.h"
 #include "core/object/script_language.h"
 #include "core/templates/local_vector.h"
 #include "scene/resources/packed_scene.h"
+#include "scene/scene_string_names.h"
```
Comment (AThousandShips) [inline scene/property_utils.cpp:38]:
```suggestion
```

**Review by AThousandShips — DISMISSED** [review]

**Comment by akien-mga** [comment]
Thanks for rebasing!

@KoBeWi @AThousandShips Does this still look good to merge to you after a few months?

**Comment by KoBeWi** [comment]
So I decided to give it a last try by testing with my project and there is a critical bug 💀

If you instantiate a scene, the value of `script` property will always be saved (as if it couldn't determine the default value). In case of built-in scripts, they will get embedded in the parent scene.

**Comment by bjornmp** [comment]
Hi @KoBeWi, let me look into it. Can you give me minimal steps to reproduce this issue?

**Comment by KoBeWi** [comment]
1. Create a scene
2. Attach any script to root node
3. Create another scene
4. Instantiate the first scene in the new scene
5. Save and check the tscn file

File: scene/property_utils.cpp [hunk 25]
```diff
@@ -89,6 +89,16 @@ Variant PropertyUtils::get_property_default_value(const Object *p_object, const
 		*r_is_valid = false;
 	}
 
+	// Handle special case "script" property, where the default value is either null or the custom type script.
+	// Do this only if there's no states stack cache to trace for default values.
+	if (p_property == CoreStringName(script) && p_object->has_meta(SceneStringName(__custom_type_script)) && !p_states_stack_cache) {
```
Comment (KoBeWi) [inline scene/property_utils.cpp:94]:
```suggestion
	if (p_property == CoreStringName(script) && !p_states_stack_cache && p_object->has_meta(SceneStringName(__custom_type_script))) {
```
Cheaper check first.

**Review by KoBeWi — APPROVED** [review]
Now it works correctly.

I still think it's a nice feature. It improves usability of custom Nodes, though the drawback is that every newly created custom node has an additional metadata property for the base script.

It's safe to merge, because it can be reverted at any time without breaking compatibility. It's only relevant to editor.

File: scene/scene_string_names.cpp [hunk 26]
```diff
@@ -130,6 +130,8 @@ SceneStringNames::SceneStringNames() {
 	shader_overrides_group = StaticCString::create("_shader_overrides_group_");
 	shader_overrides_group_active = StaticCString::create("_shader_overrides_group_active_");
 
+	__custom_type_script = StaticCString::create("__custom_type_script");
```
Comment (Repiteo) [inline scene/scene_string_names.cpp:133]: This is *very* unorthodox syntax for this repo. Is there a functional reason for the double-underscore, or is it strictly stylistic?

File: editor/scene_tree_dock.cpp [hunk 27]
```diff
@@ -3542,6 +3580,27 @@ void SceneTreeDock::_script_dropped(const String &p_file, NodePath p_to) {
...
+				if (custom_type_name.is_empty()) {
+					const EditorData::CustomType *custom_type = get_editor_data()->get_custom_type_by_path(ct_scr->get_path());
+					if (custom_type) {
+						custom_type_name = custom_type->name;
+					} else {
+						custom_type_name = TTR("<unknown>");
+					}
+				}
+
+				WARN_PRINT_ED("Script does not extend type: " + custom_type_name);
```
Comment (AThousandShips) [inline editor/scene_tree_dock.cpp:3599]:
```suggestion
				WARN_PRINT_ED(vformat("Script does not extend type: '%s'.", custom_type_name));
```
[Prefer `vformat`](https://docs.godotengine.org/en/latest/contributing/development/core_and_modules/common_engine_methods_and_macros.html#format-a-string) for readability

**Review by AThousandShips — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks, and congratulations on your first contribution! 🎉
