### PR TITLE
Fix "Could not resolve script" error after renaming a preloaded script

### LINKED ISSUE #92007: Changing name of script after using it in `preload()` generates "Could not resolve script" error, recoverable only by reloading project
### Tested versions

v4.3.beta.custom_build [557f63d03]

Custom build for the `precision=double` flag

### System information

Godot v4.3.beta (557f63d03) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 Ti Laptop GPU (NVIDIA; 31.0.15.3598) - AMD Ryzen 7 5800H with Radeon Graphics (16 Threads)

### Issue description

Using a script's path in a `const XXX := preload()` function, and then renaming the script using Godot's "Rename" menu command, gives a "Error at (xx, yy): Could not resolve script "res://script_name.gd".

The error persists even after retyping the expression. Using "=" instead of ":=" also does not make the error go away. Renaming the script back and using the old name in `preload()` also does not resolve the issue.

It's undoable. Gives vibes of "Anton Chigurh" in "No Country for Old Men".

### Steps to reproduce

1. Create any script. e.g. "script_a.gd".
2. In another script, load the first script into a `const` using `preload()`. e.g. `const ScriptA := preload("res://script_a.gd")`.
3. Rename the first script's name. e.g. "script_b.gd".
4. Error appears in the second script.
5. Edit the name in the `preload()` function, rename the first script to original name, close and reopen the second script, and try a few other things, but the error persists.
6. Reload project, error gone.

### Minimal reproduction project (MRP)

The steps above to reproduce the issue are sufficient to display the problem, and no MRP is needed.

### PR DESCRIPTION
**Pull request by shoyguer**
Fixes #92007

### CODE REVIEW

File: modules/gdscript/gdscript_cache.cpp [hunk 1]
```diff
@@ -178,6 +178,21 @@ void GDScriptCache::move_script(const String &p_from, const String &p_to) {
...
+			if (kv.key.begins_with(from_base)) {
+				to_remap.push_back(kv.key);
+			}
+		}
+		for (const String &E : to_remap) {
+			singleton->static_gdscript_cache[to_base + E.substr(from_base.length())] = singleton->static_gdscript_cache[E];
+			singleton->static_gdscript_cache.erase(E);
+		}
+	}
 }
```
Comment (HolonProduction) [inline modules/gdscript/gdscript_cache.cpp]: This part is irrelevant to the fix, please remove it. `static_gdscript_cache` serves no purpose at the moment so there is no need to update it.

**Review by HolonProduction — CHANGES_REQUESTED** [review]
I can confirm that this fixes the linked issue.

However one of the changes is unrelated to the fix.

File: modules/gdscript/gdscript_cache.cpp (hunk 1 above)
Comment (shoyguer) [reply modules/gdscript/gdscript_cache.cpp]: @HolonProduction , fixed!
Tested and still works. 
My bad 😄

Comment (HolonProduction) [reply modules/gdscript/gdscript_cache.cpp]: Nah, it would be a good catch if we actually used it. But since we don't it's just not worth the code. We should probably get rid of `static_gdscript_cache` for the time being, it might be a bit confusing.

Comment (shoyguer) [reply modules/gdscript/gdscript_cache.cpp]: Sure!
If you find any more stuff for me to fix, please let me know

**Review by HolonProduction — APPROVED** [review]
Can confirm that this fixes the linked issue. The failing test is an android test which iirc is quite flaky.

The code looks a bit convoluted at first, but given that this gracefully needs to handle fqns of inner classes of a globally named class, I don't think there's a better solution.

**Review by HolonProduction — APPROVED** [review]

**Comment by HolonProduction** [comment]
Github is still showing 3 commits. I can squash this for you if you'd like.

**Comment by shoyguer** [comment]
@HolonProduction , done!
