### PR TITLE
Don't attempt shutting down adb on exit if not started

### LINKED ISSUE #88864: Error on shutdown: cannot connect to daemon at tcp:5037: Connection refused (regression from #87823)
### Tested versions

- Reproducible in 4.3.dev (8eb34cb78bc2df3715cfdfcf4562bd36ddf91f7f)
- Bisected to #87823

### System information

Fedora Linux 39 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7600M XT (RADV NAVI33) () - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)

### Issue description

When starting a project in current `master` on Linux, I get the following error twice:
```
cannot connect to daemon at tcp:5037: Connection refused
```

```
godot-git --rendering-driver opengl3 -e --path TestJPEG/
Godot Engine v4.3.dev.custom_build.343bfb112 - https://godotengine.org
Plugin "GTK3 plugin" uses conflicting symbol "png_free".
Invalid value (0) for DRI_PRIME. Should be > 0
Inconsistent value (2) for DRI_PRIME. Should be < 2 (GPU devices count). Using: 1
Inconsistent value (3) for DRI_PRIME. Should be < 2 (GPU devices count). Using: 1
OpenGL API 4.6 (Core Profile) Mesa 23.3.5 - Compatibility - Using Device: AMD - AMD Radeon Graphics (radeonsi, gfx1103_r1, LLVM 17.0.6, DRM 3.57, 6.7.5-200.fc39.x86_64)
 
cannot connect to daemon at tcp:5037: Connection refused
WARNING: Icon not supported by this display server.
     at: set_icon (./servers/display_server.cpp:587)
cannot connect to daemon at tcp:5037: Connection refused
```

I didn't test if a similar issue is present on other platforms.

My test project doesn't have an Android running preset.

CC @KoBeWi 

### Steps to reproduce

- Run editor on Linux

### Minimal reproduction project (MRP)

Brand new project.

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #88864.

### CODE REVIEW

**Review by m4gr3d — APPROVED** [review]

File: platform/android/export/export_plugin.cpp [hunk 1]
```diff
@@ -416,7 +416,7 @@ void EditorExportPlatformAndroid::_check_for_changes_poll_thread(void *ud) {
 		}
 	}
 
-	if (EDITOR_GET("export/android/shutdown_adb_on_exit")) {
+	if (ea->has_runnable_preset.is_set() && EDITOR_GET("export/android/shutdown_adb_on_exit")) {
 		String adb = get_adb_path();
 		if (!FileAccess::exists(adb)) {
```
Comment (KoBeWi) [inline platform/android/export/export_plugin.cpp:421]: You could add the preset check here, it would be more consistent with the check for device updates above.

**Review by KoBeWi — APPROVED** [review]
I can't reproduce the error, but this makes sense.

File: platform/android/export/export_plugin.cpp (hunk 1 above)
Comment (akien-mga) [reply platform/android/export/export_plugin.cpp:421]: True, but there's no point running querying the editor setting or getting the adb path if we'll skip using it.

Comment (KoBeWi) [reply platform/android/export/export_plugin.cpp:421]: The path won't be queried if the runnable check is false.
