### PR TITLE
Ignore locked nodes when click selecting in 3d editor

### LINKED ISSUE #84764: Can't select nodes behind a locked node in editor
### Godot version

v4.1.3.stable.mono.official [f06b6836a]

### System information

Godot v4.1.3.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti with Max-Q Design (NVIDIA; 31.0.15.3640) - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 Threads)

### Issue description

When I lock a node in the editor, I expect to be able to click and select things behind it. Instead, clicks are ignored.

I have a game where your typical view (as the player and when editing using Godot) is an isometric camera and the player is inside a building. There's a ceiling, represented by a plane, with the "front" of the ceiling mesh is pointed down towards the player, leaving the backface to be culled/invisible. The player is able to carry a camera that renders into a viewport in the UI, but this handheld camera (and Camera3D) render from the first person perspective -- that is, below the ceiling, which is why it's there in the first place. That is, the ceiling should be invisible to the bird's eye camera, but not to the first-person camera.

Basically in the editor there's this giant invisible plane covering the entire visible map that, even when locked, blocks my attempts to select anything else in the scene. My workaround is to hide the plane and wire the `ready` event to the `show()` method as a one-shot, but this is crude.

### Steps to reproduce

1. Create any two meshes, with one mesh interposed between the other and the editor camera. In my case, one of the meshes is a large plane that sits between the rest of the scene and the editor camera.
2. Mark the mesh closer to the camera as Locked.
3. Try to click the further mesh.

In the repro project attached, notice that it's quite hard to actually select the "Player" node.

### Minimal reproduction project

[LockBlockRepro.zip](https://github.com/godotengine/godot/files/13326210/LockBlockRepro.zip) -- does not require the C# build.

### PR DESCRIPTION
**Pull request by EelisOtsamo**
This PR changes the 3D node editor click selection to skip locked nodes.
Previously clicking on a locked node blocked the input. Now the next closest unlocked node is selected instead.

Fixes #84764

### CODE REVIEW

**Comment by Cammymoop** [comment]
I feel like this isn't ideal, unlike in 2D, having a locked node preventing you from selecting nodes that are hidden behind it is a feature. I don't want to be randomly selecting or dragging various nodes I can't even see.

I wish this could specifically avoid selecting when clicking on the backface of a mesh that isn't rendered, or maybe adding visual layer mask to the 3d editor view and use that to get things out of the way without hiding them.

Maybe it could be worked around by having the locked node that's in the way being higher up in the scene hierarchy and only editing the lower level scene that doesn't include it.

If #85740 is accepted along with this, then clicking and dragging on a locked node will start a selection, unless there happens to be a node behind it (same as 2D) but in 3D you could easily have several nodes behind the locked node and not know where they are exactly so it seems like it would be pretty error-prone.
Without it though the issue is less noticeable since both starting a box select over a locked node and clicking and moving a non-selected node are both currently broken.

**Comment by KoBeWi** [comment]
> I feel like this isn't ideal, unlike in 2D, having a locked node preventing you from selecting nodes that are hidden behind it is a feature. I don't want to be randomly selecting or dragging various nodes I can't even see.

I don't get why would this be ok for 2D, but not 3D.

https://github.com/user-attachments/assets/9f36a083-9c60-4f26-a380-68ba4b68825a

Actually in 2D it's worse, because you can drag a node you just selected. In 3D dragging without selection will always start box selecting.

https://github.com/user-attachments/assets/05570a57-98c0-4e5f-b63c-2cc493d8986a

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -1856,7 +1856,14 @@ void Node3DEditorViewport::_sinput(const Ref<InputEvent> &p_event) {
 
 					if (after != EditorPlugin::AFTER_GUI_INPUT_CUSTOM) {
 						//clicking is always deferred to either move or release
-						clicked = _select_ray(b->get_position());
+
+						//single item selection
```
Comment (KoBeWi) [inline editor/plugins/node_3d_editor_plugin.cpp:1860]:
```suggestion
						// Single item selection.
```
Also the above comment could get removed probably. Not sure what it refers to and with your changes there is awkward blank space that makes it disconnected.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
