### PR TITLE
Fix Theora video issues

### LINKED ISSUE #21568: VideoPlayer glitch when video ends with identical frames
**Godot version:**
3.0.6

**OS/device including version:**
Windows 10 Home

**Issue description:**

https://www.youtube.com/watch?v=gs2L_lzKJQ8&feature=youtu.be

Basically, it seems that if a video ends with a bunch of identical frames it just completely glitches out. That video was shot using Godot 3.0.2 and using a VP9 encoded video, but I have since tested it with 3.0.6 and it is still present. I've tested this with Theora and VP9 videos, and the main difference is that Theora correctly continues the stream_position variable to the end, but the audio still glitches out. I have also confirmed this happening with another video from Riven.

I straight up could not get videos converted with FFMPEG to work with Godot (Theora would be blue shifted, VP9 would just mess all the colors up), so I suppose it could be an encoding issue, but since the symptoms are almost identical between the codecs I suspect it's an issue with videoplayer.

**Steps to reproduce:**
Get a video with a bunch of identical frames at the end, and put it in a Videoplayer node.

**Minimal reproduction project:**
[videoplayer bug.zip](https://github.com/godotengine/godot/files/2332686/videoplayer.bug.zip)

### LINKED ISSUE #53503: Game unresponsive when trying to play corrupted ogv video
### Godot version

3.3 stable

### System information

Windows 10, Android

### Issue description

If you try to play a corrupted ogv video on windows or Android, the game will become unresponsive. 

I think it should stop playing the video and return an error code and still be responsive.

### Steps to reproduce

Add a VideoPlayer node in your scene
Get a ogv file: https://upload.wikimedia.org/wikipedia/commons/7/79/Big_Buck_Bunny_small.ogv
Corrupt it with this https://corrupt-a-file.net/
Add file to res://Assets/Video/

Call this code:

var stream = VideoStreamTheora.new()
  stream.set_file("res://Assets/Video/Big_Buck_Bunny_small.ogv")
  stream.resource_local_to_scene = true
  stream.resource_path = "res://Assets/Video/Big_Buck_Bunny_small.ogv"
  stream.resource_name = "Big_Buck_Bunny_small.ogv"
  videoPlayerNode.set_stream(stream)
  videoPlayerNode.play()

The game should be unresponsive.

### Minimal reproduction project

_No response_

### LINKED ISSUE #62752: Godot doesn't crop 8-pixel overscan area when playing Ogg Theora video
### Godot version

4.0.alpha11

### System information

Fedora 36, GeForce GTX 1080 (NVIDIA 510.68.02)

### Issue description

Notice how the last 8 rows of pixels are duplicated in Godot, but not in mpv:

### Screenshot from Godot (bad)

*Ignore the window size being too large.*

### Screenshot from mpv (good)

image

This happens even if I re-encode the video using FFmpeg (`ffmpeg -i Big_Buck_Bunny_medium.ogv bb.ogv`.

### ffprobe information (on original video file)

```
[ogg @ 0x55c00d5965c0] Broken file, keyframe not correctly marked.
Input #0, ogg, from '/tmp/test_ogg_theora/Big_Buck_Bunny_medium.ogv':
  Duration: 00:09:56.47, start: 0.000000, bitrate: 1317 kb/s
  Stream #0:0: Data: none
  Stream #0:1: Video: theora, yuv420p, 896x504, 24 tbr, 24 tbn
    Metadata:
      ENCODER         : ffmpeg2theora-0.25
      SOURCE_OSHASH   : cc9e38e85baf7573
  Stream #0:2: Audio: vorbis, 48000 Hz, stereo, fltp, 96 kb/s
    Metadata:
      ENCODER         : ffmpeg2theora-0.25
      SOURCE_OSHASH   : cc9e38e85baf7573
Unsupported codec with id 0 for input stream 0
```

### Steps to reproduce

- Add VideoStreamPlayer node and specify an Ogg Theora video file.
- Disable **Expand** on the VideoStreamPlayer.
- Run the project and look at the video's bottom pixels.
- Play the video in another video player such as [mpv](https://mpv.io/) or [VLC](https://www.videolan.org/vlc/), and compare the visual output.

### Minimal reproduction project

https://0x0.st/oQfc.zip <sub>(link expires in January 2023)</sub>

### LINKED ISSUE #66331: VideoStreamTheora: Identical frames make the audio buggy
### Godot version

Both 3.5 and 4.0 beta 1

### System information

Kubuntu 22.04

### Issue description

On videos that start with a black screen, the audio plays incorrectly.

This bug is much more noticeable if the keyframe interval is set to a high value (through `-g` or `-g:v`) such as 300 (10 times the frame rate, the max recommended by Theora guides), where the audio only begins playing after the first non-black frame appears, then randomly starts trying to seek to the correct position. This won't happen in video players such as VLC or mpv.

On videos that don't start with a black screen, or have a keyframe interval set to 1 (which will result in a very heavy file) the audio begins playing normally.

(Seriously, increasing the keyframe interval is simply an amazing way to reduce Theora file sizes, at the cost of having some *very* minor motion artifacts, but you can get a video of quality 8 at the same size as quality 6 at low keyframe interval)

### Steps to reproduce

1. Download the Bink file at [this video](https://www.youtube.com/watch?v=4oijqgtd3Gg)'s description (this is the exact same video I used to find this bug);
2. Convert it to Ogg Theora using FFmpeg (`-g:v` set to a high number such as 300 is very important)
3. Drag the video into Godot and play it.

- Also try using a low keyframe interval, it will noticeably reduce the delay.
- FFmpeg uses a default value of 12 for the keyframe interval.

### Minimal reproduction project

I'm afraid of inserting a branded video here.

### LINKED ISSUE #98302: SceneTreeTimer breaks when playing a video in loop
### Tested versions

v4.3 stable

### System information

Windows 10, Ryzen 3 3300x, 16gb RAM 2666mhz, GTX 1660 6gb.

### Issue description

If the video is looping, for whatever reason, the timer breaks and never returns the timeout signal. 

```
@onready var _video: VideoStreamPlayer = $video

var timer : SceneTreeTimer

func _ready() -> void:
	print('Starting')
	await _execute_and_stop()
	print('\n\nFinished!\n\n')
	
	
func _execute_and_stop() -> void:
	_video.play()
	timer = get_tree().create_timer(10, true)  			# Error.
	#timer = get_tree().create_timer(10, true, true)  	# ok.
	await timer.timeout
	_video.stop()
```

Playing a video with 6.9166667 sec (166 frames at 24fps), using a timer with 10 sec, that's the log I get when printing the 'time_left' in the SceneTreeTimer.

```
3.30371609090929
3.29765548484868
3.29159487878808
3.28553427272747
3.27947366666686
3.27341306060626
3.26735245454565
3.26129184848505
3.25523124242444
3.24917063636383
3.24311003030323
3.23704942424262
3.23098881818202
3.22492821212141
3.2188676060608
3.2128070000002
3.20674639393959
3.20068578787899
3.19462518181838
3.18856457575778
3.18250396969717
3.17644336363656
3.17038275757596
3.16432215151535
3.15826154545475
3.15220093939414
3.14614033333353
3.14007972727293
3.13401912121232
3.12795851515172
3.12189790909111
3.1158373030305
3.1097766969699
3.10371609090929
3.09765548484869
3.09159487878808
3.08553427272748
3.07947366666687
3.07341306060626
3.06735245454566
3.06129184848505
3.05523124242445
14745887137786335000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
14745887137786335000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
14745887137786335000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
14745887137786335000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
14745887137786335000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

In the MRP, there are 2 videos. For reasons I don't understand, the timer works ok when updating in the physics frame, but not in the process frame. Also, the first video1 works ok, but the video2 breaks the timer...

### Steps to reproduce

As shown in the script above.

### Minimal reproduction project (MRP)

[demo_timer.zip](https://github.com/user-attachments/files/17438564/demo_timer.zip)

### LINKED ISSUE #101837: VideoStreamPlayer rendering frames out of time (Theora video)
### Tested versions

Reproducible in: 4.3.stable

### System information

Debian GNU/Linux 12.9

### Issue description

I've encoded a pair of videos to illustrate a problem when rendering pictures with areas of solid colors. It might not be exclussive to any kind of content but probably more noticeable here and it's even more evident when trying to improve compression ratios by increasing the keyframe interval.

Even with default keyframe interval values there's still glitches in the franknstein_short.ogv video. It gets fixed with keyframe interval at 1 but then file size goes up noticeably.

Like #66331, the issue gets worse with higher keyframe intervals but it's not the same.

### Steps to reproduce

Load the attached videos in Godot and play them. Compare them against the same videos played in another player like VLC.

The videos played in Godot freeze in some frames.

In the case of the video with solid colors, Colors white, cyan and yellow should stay while red and cyan should past by fast. Godot stays at red and green while white, cyan and yellow past by fast.

The other video displays a border changing color and showing some bands. It freezes at frames at frames that the original video doesn't.

I think the issue must be the same in both videos.

### Minimal reproduction project (MRP)

https://www.mediafire.com/file/7abnxvzz54plvos/test.ogv/file
https://www.mediafire.com/file/i2w0wrt5ahi1p0g/franknstein_short.ogv/file

### PR DESCRIPTION
**Pull request by berarma**
This fixes many (if not all) of the long-standing issues when playing Theora video streams. Even though Theora is an old codec, it can still do a decent job, specially when it works 100% correctly. That's what this PR aims to do.

Videos are an essential piece for many games, and I think Godot can be a lot better by fulfilling that need in the core. Having at least a backup codec which can be used out of the box and offers compatibility with old and new hardware will make life easier for a lot of developers.

What's fixed:

- Duplicate frames being ignored (TH_DUPFRAME). These are used when there are continuous identical frames in the stream.
- Frames playing ahead of time, more noticeable with lower framerates. ~~The latter can happen when the encoder skips identical frames, but also when the video frame rate is lower than the screen frame rate.~~ Edit: this was made worse by a bug in FFmpeg.
- Audio buffer running out of data when the previous situations happened and also when decoding was slow.
- Buffering of the stream didn't work. Now it works for the decoded audio and the encoded video data.
- The audio buffer couldn't be filled without overwriting previous audio data.
- Frames weren't being cropped to the original picture size and offset and produced artifacts around the image for some frame sizes.

I've also removed the Theora thread streaming code since it was disabled in code and it would involve more testing. I think it's better to remove that code for now than leave it untested and focus on getting it working 100% right.

The issues fixed could be mostly worked around by setting the keyframe inverval to 1 but this would take away most compression benefits. Now videos should play correctly even at the highest keyframe interval.

- Fixes #66331 (same as #21568)
- Fixes #101837
- Fixes #62752 
- Fixes #53503
- Fixes #98302

And possibly other issues.

There's some code left to dynamically change post-processing levels depending on codec performance, but it doesn't really do anything as it's set to no post-processing. I think I could easily make it work but it would be good to have a setting so the user can disable post-processing or set a max level that suits the video content.

Audio delay compensation is supposed to need some work also according to code comments. I could look at it too.

Please test it. Now that I've gotten a grasp of the code, I'm determined to make it work 100%.

I think this could be easily ported to Godot 3.X.

### CODE REVIEW

**Comment by berarma** [comment]
I'll fix the code style issues in a moment. Sorry.

**Comment by berarma** [comment]
> The patch in AudioRBResampler didn't seem to interfere in custom VideoStream implementations, so LGTM.

It will prevent overwriting buffered audio.

**Comment by berarma** [comment]
I've added a fix for #62752. Updated PR description.

**Review by Calinou — COMMENTED** [review]
Tested locally, it causes a significant performance regression in debug builds when reading a high-bitrate 1080p60 video despite using a high-end CPU.

<details open>

<summary>PC specifications</summary>

- **CPU:** Intel Core i9-13900K
- **GPU:** NVIDIA GeForce RTX 4090
- **RAM:** 64 GB (2×32 GB DDR5-5800 C30)
- **SSD:** Solidigm P44 Pro 2 TB
- **OS:** Linux (Fedora 41)
</details>

See these 120 FPS videos of the running project which should showcase frame drops clearly:

### Before

https://github.com/user-attachments/assets/3ef35318-8f94-4e33-b994-35ec7800e7a3

### After

https://github.com/user-attachments/assets/47ecf982-cad9-4937-9545-439b1d5ad004

Source video file: https://0x0.st/8Xbm.ogv

Thankfully, this is not reproducible when using an optimized editor build (`production=yes lto=full`), but I worry about low-end and mobile CPUs here.

**Comment by fire** [comment]
Note that a debug builds is not a release build of Godot Engine. So this may still be ok if we can test on a low end computer or android tablet.

**Comment by DeeJayLSP** [comment]
Kinda off-topic, but I should warn that Theora doesn't have ARM SIMD enabled in Godot.

I made an attempt a long time ago on #68694, but it added a dependency (perl) and only worked for 32-bit ARM. I presume it's similar to libvpx's buildsystem issue.

**Comment by berarma** [comment]
> Tested locally, it causes a significant performance regression in debug builds when reading a high-bitrate 1080p60 video despite using a high-end CPU.

I don't think this is really a performance regression. The code is doing the same work but only in a different way.

I think it's because the way I choose the frames to render causing frame stuttering.

> Thankfully, this is not reproducible when using an optimized editor build (`production=yes lto=full`), but I worry about low-end and mobile CPUs here.

I don't think it's directly related to the performance of the code but to the resulting framerate being more or less in sync with the video rate. Thus, it might happen either with low or high end machines.

Running a high-bitrate HD video at 60fps on an unoptimized codec without hardware acceleration is the worst possible scenario. Since the codec is running fully in the CPU, code optimization will be a must in most systems. Anyway, I'm glad you tried this because I think it uncovered an issue in the frame dropping/choosing logic.

I've pushed a new commit with an improved logic that worked well in my tests. I've left `printf` in the code so that it outputs debug information to the terminal. Iin case it's still not fixed I'd need that information to see what's happening on your computer. I'll remove them when we're done testing it.

**Comment by DeeJayLSP** [comment]
Tested the current changes with 5 different videos.

The runtime crashed with 2 of them.

Here are the first 4 lines of the backtrace:
```
[1] /lib64/libc.so.6(+0x1a090) [0x7aa235226090] (??:0)
[2] /home/user/sources/godot-drwav-rebase/bin/godot.linuxbsd.editor.dev.x86_64() [0x5982cf0] (/home/user/sources/godot-drwav-rebase/./thirdparty/misc/yuv2rgb.h:946)
[3] VideoStreamPlaybackTheora::video_write(th_img_plane*) (/home/user/sources/godot-drwav-rebase/modules/theora/video_stream_theora.cpp:77)
[4] VideoStreamPlaybackTheora::update(double) (/home/user/sources/godot-drwav-rebase/modules/theora/video_stream_theora.cpp:472)
```

**Comment by berarma** [comment]
> Tested the current changes with 5 different videos.
> 
> The runtime crashed with two of them right at the end.

Thanks for testing. I've tested a bunch of videos and it didn't crash for me but it entered an infinite loop in some of them. I've added conditions for the cases where the streams are incomplete and libogg doesn't detect the end of the stream.

**Comment by berarma** [comment]
I've tried playing some intentionally corrupted files (zeros or random data written in the middle and the end). In all cases the playing continued or stopped depending on the severity of the corruption but it never crashed or became unresponsive, so I think #53503 is also fixed.

**Comment by berarma** [comment]
I've just learned that the frame timestamps calculated by the codec point to the end of frame, not the start. I shouldn't have trusted the original implementation based on the example player. Sorry for the many changes. This makes the code a lot simpler so it's something good after all.

Just for the record, extracting a fragment from an OGG video with the command `ffmpeg -ss 00:00:00 -t 00:00:20 -c:v copy -an` produces a bad stream, it will play but long sequences of identical frames will get mangled. Doing the same operation from another container/codec stream works well. I may file an issue for ffmpeg.

**Comment by DeeJayLSP** [comment]
Tested again

In cases where the video *starts* with identical frames (the one mentioned in #66331) it seems to skip to the first non-duplicate frame, then freeze until its time is reached.

**Comment by berarma** [comment]
> Tested again
> 
> In cases where the video _starts_ with identical frames (the one mentioned in #66331) it seems to skip to the first non-duplicate frame, then freeze until its time is reached.

I can't reproduce this. I only see a black frame for the first few seconds.

> 
> If the video is played with loop enabled, audio will desync a lot.

Fixed. VideoStreamPlayer wasn't flushing the audio buffer between loop plays.

**Comment by DeeJayLSP** [comment]
> I can't reproduce this. I only see a black frame for the first few seconds.

For reference, the video was encoded with a keyframe interval of 10 seconds (-g:v 300, the video is 30 FPS)

**Comment by berarma** [comment]
> For reference, the video was encoded with a keyframe interval of 10 seconds (-g:v 300, the video is 30 FPS)

I've used the command `ffmpeg -i valve.bik -codec:v libtheora -codec:a libvorbis valve.ogv` and several variations all with the same result. I've even made screenshots and inspected them with extreme brightness and contrast values and still nothing. This is with ffmpeg 5.1.6 from Debian 12 repositories.

Can you share the command line you've used to convert the file or share the file you're testing?

**Comment by DeeJayLSP** [comment]
> Can you share the command line you've used to convert the file or share the file you're testing?

I've been using [this script I wrote 3 years ago](https://gist.github.com/DeeJayLSP/19eab37d664500925b1b8fdbf025228e).

I needed the reference encoder since it was able to achieve a better compression ratio

**Comment by berarma** [comment]
> > Can you share the command line you've used to convert the file or share the file you're testing?
> 
> I've been using [this script I wrote 3 years ago](https://gist.github.com/DeeJayLSP/19eab37d664500925b1b8fdbf025228e).
> 
> I needed the reference encoder since it was able to achieve a better compression ratio and had options not available in FFmpeg.
> 
> **Edit**: By using a static FFmpeg build and the command `ffmpeg -i valve.bik -c:v libtheora -q:v 6 -g:v 300 -c:a libvorbis -q:a 5 valve.ogv` the first frame won't appear that soon, but the freeze still happens.
> 
> `-g:v 300` is necessary as FFmpeg's default value of 12 is too low and significantly increases video size (even Google recommends increasing the value when encoding WebM).

Sorry, I copied the wrong command. We're using the same options, I don't understand why it works differently.

**Comment by DeeJayLSP** [comment]
> Sorry, I copied the wrong command. We're using the same options, I don't understand why it works differently. Can you share the video?

This is the one encoded with the reference encoder: https://0x0.st/88Qu.ogv

And this is the one encoded directly with FFmpeg: https://0x0.st/88QS.ogv

**Comment by berarma** [comment]
> > Sorry, I copied the wrong command. We're using the same options, I don't understand why it works differently. Can you share the video?
> 
> This is the one encoded with the reference encoder: https://0x0.st/88Qu.ogv

I'm pretty confident this is badly encoded. There's an error either in the encoding process or when reading from the source.

This video plays well when the timestamps given by libtheora are interpreted as the start of the frame, but they signal the end of the frame. At first, I used them like this and some videos would play without the freezes but that was wrong. The frozen frame is a normal frame encoded in the stream.

> 
> And this is the one encoded directly with FFmpeg: https://0x0.st/88QS.ogv

This one plays fine.

> 
> You can see the detail from the first frame for a while in the first video, while both freeze for a moment when "valve" is starting to appear.

I only see the freezing in the first video, and the reason is the same as above. The second one is smooth all the way until the end.

I've observed VLC doesn't play videos correctly. Although it tends to unfreeze frames, maybe because it's using the end of frame as the start, it's incorrect.

ffplay and mpv seem to be reliable, with the only problem that they finish the video before time when there are identical frames at the end.

**Comment by DeeJayLSP** [comment]
> This one plays fine.

I swear I could see the freeze before, but after playing it again, it's gone.

**Comment by berarma** [comment]
> > This one plays fine.
> 
> I swear I could see the freeze before, but after playing it again, it's gone.
> 
> Also, my copy of VLC seems to play the first one correctly, so idk.

Yes, VLC plays it without the freeze for me too. That's why I say it doesn't work correctly. Try it with ffplay and mpv and you'll see they show the same freezes.

**Comment by DeeJayLSP** [comment]
> Yes, VLC plays it without the freeze for me too. That's why I say it doesn't work correctly. Try it with ffplay and mpv and you'll see they show the freezes. They're not really freezes, it's encoded like that.

On my end:
First video:
- VLC: Plays normally
- mpv: Starts playing from the first non-black frame, then freezes for a moment to sync with audio
- ffplay: Renders the first frame, then begins moving once it's time arrives. Freezes for a moment at the valve logo to sync with audio (same behavior in Godot with this PR in the current state)

Second video:
- All players work normally.

**Comment by berarma** [comment]
> On my end:
> ### First video:
> 
>     * VLC: Plays normally
> 
>     * mpv: Starts playing from the first non-black frame, then freezes for a moment to sync with audio
> 
>     * ffplay: Renders the first frame, then begins moving once it's time arrives. Freezes for a moment at the valve logo to sync with audio (same behavior in Godot with this PR in the current state)

Same as you, but I want to make this perfectly clear: the video with the "freezes" that mpv/ffplay plays is the actually encoded content. So VLC is playing it wrong indeed.

I don't know what you mean when you say it freezes to sync with audio. Audio is playing fine for me all the way through. I honestly think there's nothing wrong with the way mpv, ffplay or this PR play this video.

Oddly enough, I've taken a look at your script and constructed a loosely similar command to convert the file using the Theora example encoder installed in my system:

`ffmpeg -i valve.bik -an -c:v rawvideo -pix_fmt yuv420p -f rawvideo - | ffmpeg -s 1920x1080 -f rawvideo -i - -pix_fmt yuv420p -f yuv4mpegpipe - | theora_encoder_example -z 0 -k 300 - -o valve.ogv`

And the resulting video plays fine.

> Well, it's a shame that the encoder that yields the best quality per bytes has this bug. And won't get fixed anytime soon since Xiph.org is likely trying to kill Theora (no commits since 2020).

In the videos that you have sent, both videos have the same video bitrate, and the one encoded with ffmpeg is the smallest one. The audio stream is the same size on both. So ffmpeg seems to do a better job packaging the video stream. I haven't noticed differences in the quality, at least for this one.

**Comment by berarma** [comment]
Just one more discovery about the encoding. ffmpeg uses a default max keyframe interval of 64, so values higher than 64 are treated as 64. But for some reason, values higher than 64 increase the file size a bit. It's probably generating extra empty packets that are discarded when decoding. Theoretically, the encoder allows values up to 65535 if instructed to do so, but ffmpeg just doesn't. This isn't an issue for this PR since it's all handled by the decoder.

Back on topic, I think this PR is as good as it gets. At least, it should be a notable improvement over the current implementation. I'll be testing and following any testing by others but I think it's good to go.

I'm finishing to implement seek capabilities and seamless loops based on the changes in this PR. That will be in another PR coming soon.

**Comment by DeeJayLSP** [comment]
> And the resulting video plays fine.

Until you combine it with an audio stream using `-c:v copy -c:a copy`

**Comment by berarma** [comment]
> > And the resulting video plays fine.
> 
> Until you combine it with an audio stream using `-c:v copy -c:a copy`

There's the problem. There's some bug in ffmpeg that I already mentioned before, it doesn't really copy the stream but breaks it. It does no longer represent the same sequence of frames.

**Comment by berarma** [comment]
I've reported bugs for the FFmpeg issues commented here:

- [Duplicate frames dropped when copying Theora streams](https://trac.ffmpeg.org/ticket/11451)
- [Ogg/Theora: Bad granulepos when GOP higher than 64](https://trac.ffmpeg.org/ticket/11454)

@DeeJayLSP, I'll let you know when there are updates.

These issues don't change anything for this PR. I'll put workarounds in the Godot docs unless they're fixed before this is merged.

**Review by Calinou — APPROVED** [review]
Tested locally using https://commons.wikimedia.org/wiki/File:Big_Buck_Bunny_first_23_seconds_1080p.ogv, it works as expected.

Code looks good to me.

**Review by fire — COMMENTED** [review]
I did some minor review but I am not able to find time to do the test with video files cycle.

File: servers/audio/audio_rb_resampler.h [hunk 1]
```diff
@@ -86,7 +86,7 @@ struct AudioRBResampler {
 		} else if (w < r) {
 			space = r - w - 1;
 		} else {
-			space = (rb_len - r) + w - 1;
```
[the remark this answers is not in the document]
Comment (berarma) [reply servers/audio/audio_rb_resampler.h:89]: Yes, without this change previous queued samples will get overwritten when the buffer is full.

File: servers/audio/audio_rb_resampler.h [hunk 2]
```diff
@@ -86,7 +86,7 @@ struct AudioRBResampler {
...
+			space = rb_len - w + r - 1;
```
Comment (fire) [inline servers/audio/audio_rb_resampler.h:89]:
```suggestion
			space = (rb_len - w) + (r - 1);
```
Can you check if this has the same meaning?

File: modules/theora/video_stream_theora.h [hunk 3]
```diff
@@ -41,27 +41,20 @@
...
 	Ref<FileAccess> file;
 	String file_name;
-	int audio_frames_wrote = 0;
 	Point2i size;
+	Rect2i region;
 
 	int buffer_data();
 	int queue_page(ogg_page *page);
-	void video_write();
+	void video_write(th_ycbcr_buffer yuv);
```
[the remark this answers is not in the document]
Comment (berarma) [reply modules/theora/video_stream_theora.h:57]: I'd like to be able to do it in the GPU but that's an improvement that I'm not sure how to implement. Also, since other codecs will need it, I think it should rather be implemented as a generic solution, see godotengine/godot-proposals#8049. Any suggestions and/or help welcomed for a future PR.

File: servers/audio/audio_rb_resampler.h (hunk 2 above)
Comment (berarma) [reply servers/audio/audio_rb_resampler.h:89]: Of course, it has the same meaning. Are you suggesting to put the parenthesis?

Comment (fire) [reply servers/audio/audio_rb_resampler.h:89]: Yes

File: modules/theora/video_stream_theora.cpp [hunk 4]
```diff
@@ -82,34 +60,23 @@ int VideoStreamPlaybackTheora::queue_page(ogg_page *page) {
...
+	if (px_fmt == TH_PF_444) {
+		yuv444_2_rgb8888((uint8_t *)dst, (uint8_t *)yuv[0].data + y_offset, (uint8_t *)yuv[1].data + uv_offset, (uint8_t *)yuv[2].data + uv_offset, region.size.x, region.size.y, yuv[0].stride, yuv[1].stride, region.size.x << 2);
+	} else if (px_fmt == TH_PF_422) {
+		yuv422_2_rgb8888((uint8_t *)dst, (uint8_t *)yuv[0].data + y_offset, (uint8_t *)yuv[1].data + uv_offset, (uint8_t *)yuv[2].data + uv_offset, region.size.x, region.size.y, yuv[0].stride, yuv[1].stride, region.size.x << 2);
+	} else if (px_fmt == TH_PF_420) {
+		yuv420_2_rgb8888((uint8_t *)dst, (uint8_t *)yuv[0].data + y_offset, (uint8_t *)yuv[1].data + uv_offset, (uint8_t *)yuv[2].data + uv_offset, region.size.x, region.size.y, yuv[0].stride, yuv[1].stride, region.size.x << 2);
 	}
 
-	Ref<Image> img = memnew(Image(size.x, size.y, false, Image::FORMAT_RGBA8, frame_data)); //zero copy image creation
+	Ref<Image> img = memnew(Image(region.size.x, region.size.y, false, Image::FORMAT_RGBA8, frame_data)); //zero copy image creation
```
Comment (fire) [inline modules/theora/video_stream_theora.cpp:77]: We've been moving to `instantiate(region.size.x, region.size.y, false, Image::FORMAT_RGBA8, frame_data)` rather than memnew.

**Review by fire — APPROVED** [review]
I did as much code style review as I can. Did not test.

**Review by akien-mga — APPROVED** [review]
Looks like a good cleanup, and solid work and testing on the related bug fixes.

I haven't tested myself but let's give it a spin, it's very likely to be a better implementation than what we had before (and we don't have an active Theora / VideoStream maintainer to fully assess the details).

**Comment by akien-mga** [comment]
Thanks!

**Comment by berarma** [comment]
The Theora bugs in FFmpeg have been already fixed. Details [here](/godotengine/godot-docs/pull/10614#issuecomment-2671246526).
