### PR TITLE
Fix File switching between reading and writing, opened with READ_WRITE on Windows

### LINKED ISSUE #24393: File.READ_WRITE only reads OR writes on Windows
Godot 3.1 alpha 3
Windows 10 x64

In the documentation for the File.READ_WRITE mode, it says "Opens the file for read **and** write operations." However, it only appears to work for read **or** write, depending on which operation happens first.

For example, consider the following read operation::
```
#read operation
var testString = file.get_line()
```

and write operation:
```
#write operation
file.store_string("this is fun text")
```

Only one of those lines will work, specifically the one that happens first. If you reverse the order, then the other one will work.

I'm not sure if this is intended behavior, but it makes me wonder what's the point of having a File.READ_WRITE, if it is not much different than just opening the file with File.READ and File.WRITE separately.

### PR DESCRIPTION
**Pull request by Chaosus**
According to official MS documentation (https://docs.microsoft.com/en-US/cpp/c-runtime-library/reference/fopen-wfopen?view=vs-2017) -

> When the "r+", "w+", or "a+" access type is specified, both reading and writing are enabled (the file is said to be open for "update"). However, when you switch from reading to writing, the input operation must encounter an EOF marker. If there is no EOF, you must use an intervening call to a file positioning function. The file positioning functions are fsetpos, fseek, and rewind. When you switch from writing to reading, you must use an intervening call to either fflush or to a file positioning function.

After readed a discussion in https://stackoverflow.com/questions/14878574/the-use-of-r-in-fopen-on-windows-vs-linux I've added these steps

1. Added call of fseek (if not EOF) when switching from reading to writing
2. Added call of fflush when switching from writing to reading

Fix #24393

### CODE REVIEW

**Comment by reduz** [comment]
If this is needed on windows, I guess it' s ok

**Comment by Chaosus** [comment]
Yeah, it is required, otherwise user should manually call "seek" between write and read operations (described in #24393)

File: drivers/windows/file_access_windows.cpp [hunk 1]
```diff
@@ -234,6 +236,12 @@ bool FileAccessWindows::eof_reached() const {
 uint8_t FileAccessWindows::get_8() const {
 
 	ERR_FAIL_COND_V(!f, 0);
+	if (flags > 2) { // READ_WRITE or WRITE_READ
```
Comment (akien-mga) [inline drivers/windows/file_access_windows.cpp]: That's a bit dangerous if we decide to renumber/reorder those flags.
Would be better to check explicitly for `READ_WRITE` and `WRITE_READ` in the bitmask.

Comment (Chaosus) [reply drivers/windows/file_access_windows.cpp]: Fixed !

Comment (akien-mga) [reply drivers/windows/file_access_windows.cpp]: Sorry I was not explicit enough, I meant to do bitwise checks with `(flags & READ_WRITE) || (flags & WRITE_READ)`.

Comment (Chaosus) [reply drivers/windows/file_access_windows.cpp]: They are not really formatted as flags, in fact its just an enum

Comment (akien-mga) [reply drivers/windows/file_access_windows.cpp]: I think they're meant to be formatted as flags, see:
```
        enum ModeFlags {

                READ = 1,
                WRITE = 2,
                READ_WRITE = 3,
                WRITE_READ = 7,
        };
```
```
READ_WRITE = READ | WRITE
WRITE_READ = 4 | READ_WRITE
```
(so if you use `READ | WRITE` in your code, it should behave the same as `READ_WRITE` which is just sugar for it. And `WRITE_READ` includes `READ_WRITE` too, but is more specialized via the `4` bit)

Comment (Chaosus) [reply drivers/windows/file_access_windows.cpp]: Hmm.. ok, I can of course change it as you said, however the flags are a bit different and should have power of 2 for example(in C#):

> [Flags]
> public enum Options 
> {
>     None    = 0,
>     Option1 = 1,
>     Option2 = 2,
>     Option3 = 4,
>     Option4 = 8
> }
>

Comment (akien-mga) [reply drivers/windows/file_access_windows.cpp]: But that's the case here, `READ` and `WRITE` are powers of 2, and `READ_WRITE` is just `READ | WRITE` (so it's a combination of flags).
And `WRITE_READ` is also a combination of powers of 2, namely `4 | READ | WRITE`. `4` is not used by itself, but it's used to make `WRITE_READ` a superset of `READ_WRITE`.

Comment (akien-mga) [reply drivers/windows/file_access_windows.cpp]: But well, those flags are always checked with `==` so far so I guess it's fine as is.

**Comment by akien-mga** [comment]
Thanks!

File: drivers/windows/file_access_windows.cpp (hunk 1 above)
Comment (Chaosus) [reply drivers/windows/file_access_windows.cpp]: Ah, you right :S there are two ways to solve same problem..

**Comment by hpvb** [comment]
Cherry-picked for 3.1.1.
