### PR TITLE
Fix inability to insert keys via Insert Key context menu

### LINKED ISSUE #30495: AnimationPlayer cannot insert key for Node2D property
**Godot version:**
3.2.dev.custom_build. 5e495750a37e3314a8cd85cb3f7be9a676420c44

**OS/device including version:**
Xubuntu 19.04

**Issue description:**
Cannot insert key for `Node2D:position` property for a Sprite Node using right-click on the timeline.
Trying to insert key throws error: 
```
 core/undo_redo.cpp:296 - Error calling method from signal 'track_insert_key': 'Animation::track_insert_key': Method expected 3 arguments, but called with 2.
```

With `Auto Insert Keys`  enabled I was able to add animation keys to the timeline by moving the sprite node.

**Steps to reproduce:**

1. Create Sprite Node
2. Add AnimationPlayer Node to Sprite Node
3. Create new animation
4. Add `Node2D:position` property track from Sprite Node/Node2D
5. Right-click on timeline and insert key

**Minimal reproduction project:**
[MinimalTestProject.zip](https://github.com/godotengine/godot/files/3378535/MinimalTestProject.zip)

### PR DESCRIPTION
**Pull request by bojidar-bg**
Fixes #30495.

Note that the cause is a bit complicated:
1. `AnimationTrackEdtior._find_hint_for_track` checks if the passed in path is valid with `has_node_and_resource`.
    https://github.com/godotengine/godot/blob/1abe12f5bb869605646797e043db88bb3d428e62/editor/animation_track_editor.cpp#L3138-L3144
2. The `AnimationTrackEdtior` uses `_find_hint_for_track` to get the value at the given path.
    https://github.com/godotengine/godot/blob/1abe12f5bb869605646797e043db88bb3d428e62/editor/animation_track_editor.cpp#L3948-L3954
3. `UndoRedo` assumes that method arguments end at the first `null` (`Variant()`).
    https://github.com/godotengine/godot/blob/1abe12f5bb869605646797e043db88bb3d428e62/core/undo_redo.cpp#L284-L290
4. Since `has_node_and_resource` returns `false` for a otherwise valid path,
    `_find_hint_for_track` does not set `r_current_val`,
    which results in the 3rd argument to `track_insert_key` ending up `null`.
    Then `UndoRedo._process_operation_list` calls the method with only two parameters,
    and all results in an error message and no work done.

Regression from #30088, CC @akien-mga.

### CODE REVIEW

File: scene/main/node.cpp [hunk 1]
```diff
@@ -2487,7 +2487,7 @@ bool Node::has_node_and_resource(const NodePath &p_path) const {
 	Vector<StringName> leftover_path;
 	Node *node = get_node_and_resource(p_path, res, leftover_path, false);
 
-	return (node && res.is_valid());
+	return node;
```
Comment (akien-mga) [inline scene/main/node.cpp]: When it's alone like this I prefer to make the conversion to bool explicit, so that it doesn't look like a logic mistake, so `return (node != NULL)`.

That being said, doesn't that defeat the purpose of `has_node_and_resource`, at least the one I documented? This would make it behave basically the same as `has_node()`, no?

Comment (bojidar-bg) [reply scene/main/node.cpp]: I changed `get_node_and_resource` so it returns `NULL` when there is no such resource.

Comment (akien-mga) [reply scene/main/node.cpp]: Alright, that makes sense.

**Comment by akien-mga** [comment]
Thanks!
