### PR TITLE
Make LSP ignore $/cancelRequest msgs

### LINKED ISSUE #38814: $/cancelRequest message not errors language server
**Godot version:**
3.2.2 beta
**Issue description:**
Currently the $/cancelRequest notification specified by the language server protocol is not implemented in the gdscript language server.  Because of this users constantly get error messages while using the language server.  This should be changed to either implement or ignore the request (this is allowed per the specification).

**Steps to reproduce:**
Open up a godot project in doom-emacs or any other lsp client editor

### PR DESCRIPTION
**Pull request by Razoric480**
Currently, the LSP reports errors whenever the client sends $/cancelRequest messages. This PR will make the LSP ignore $ messages, as allowed by the [LSP specifications](https://microsoft.github.io/language-server-protocol/specification#dollarRequests)

> If a server or client receives notifications starting with ‘$/’ it is free to ignore the notification.

Fixes #38814

### CODE REVIEW

File: modules/jsonrpc/jsonrpc.cpp [hunk 1]
```diff
@@ -98,6 +98,10 @@ Variant JSONRPC::process_action(const Variant &p_action, bool p_process_arr_elem
 	if (p_action.get_type() == Variant::DICTIONARY) {
 		Dictionary dict = p_action;
 		String method = dict.get("method", "");
+		if (method.find("$/") == 0) {
```
Comment (madmiraal) [inline modules/jsonrpc/jsonrpc.cpp:101]: Shouldn't this be `if (method.begins_with("$/")) {`?

Comment (akien-mga) [reply modules/jsonrpc/jsonrpc.cpp:101]: It should give the same result, but yes `begins_with` is cleaner and possibly faster.

Comment (Razoric480) [reply modules/jsonrpc/jsonrpc.cpp:101]: Ahhh. Keeping track of all the string manipulation functions is a challenge. I'll edit.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
