### PR TITLE
Make query for `GL_MAX_VIEWPORT_DIMS` compatible with web exports 

### LINKED ISSUE #92601: Tooltips are drawn outside of screen on web builds, making them cut off / cropped and unreadable, when stretch mode is set to viewport
### Tested versions

- v4.2.1

### System information

Windows 10 - Godot v4.2.1

### Issue description

Here is what a tooltip looks like on my windows build, it stays within the screen
Godot_v4 2 1-stable_win64_2024-05-31_14-46-20

Here is what the same tooltip looks like on the same game, built for HTML5
firefox_2024-05-31_14-50-58

And again with my example project:
firefox_2024-05-31_15-02-21
Godot_v4 2 1-stable_win64_2024-05-31_15-02-30

It does not seem to recognize that the tooltip is too close to the edge of the screen, and needs to be moved over. This happens even if I resize the window to fit the game view. 

### Steps to reproduce

1. in settings under display > window, set stretch mode to viewport
2. put a button or other element with a tool tip near the right side of the screen
3. build for web

### Minimal reproduction project (MRP)

View export online: https://skeddles.itch.io/godot-tooltip-broken-web-exmaple?secret=FcL5R2zAnAJCuXxvirEsvGHDkBQ

[TooltipsBrokenExample.zip](https://github.com/user-attachments/files/15517751/TooltipsBrokenExample.zip)

### PR DESCRIPTION
**Pull request by patwork**
# Info

This is an attempt to fix https://github.com/godotengine/godot/issues/92601 which turned out to be more puzzling than I originally thought.

## Investigation

As described in the original bug, tooltips in web exports were not moving correctly to avoid being cut off by the edge of the screen. At the same time, Windows and Linux exports were working correctly.

The problem was that in `godot/scene/main/viewport.cpp` the function `panel->get_max_size()` was returning values of 0/0 making the function `min()` to set the tooltip size to zero. In fact, it happened only in web exports.

https://github.com/godotengine/godot/blob/e96ad5af98547df71b50c4c4695ac348638113e0/scene/main/viewport.cpp#L1505

Going a step further, `get_max_size()` returned the value of the `max_viewport_size` variable from the Config class of `drivers/gles3/storage/config.cpp`. This value should be set by querying the GL driver for the `GL_MAX_VIEWPORT_DIMS` variable.

https://github.com/godotengine/godot/blob/e96ad5af98547df71b50c4c4695ac348638113e0/drivers/gles3/storage/config.h#L63

https://github.com/godotengine/godot/blob/e96ad5af98547df71b50c4c4695ac348638113e0/drivers/gles3/storage/config.cpp#L83-L87

Here is the source of the problem, because it turns out that in the case of web export, query for GL_MAX_VIEWPORT_DIMS does not save anything. Of these above 5 queries, the first 4 work correctly and the last 4 do not. The variable is not changed at all, if we write some values to it beforehand it remains the same.

However, it turns out that in the `drivers/gles3/rasterizer_gles3.cpp` file, a different `glGetIntegerv` function is used for the same query. It works in both Windows / Linux and web exports.

https://github.com/godotengine/godot/blob/e96ad5af98547df71b50c4c4695ac348638113e0/drivers/gles3/rasterizer_gles3.cpp#L401-L402

# Fix

My suggested fix is to replace `glGetInteger64v` with `glGetIntegerv`. Unfortunately `max_viewport_size` in Config class is of type `int64_t [2]` and `glGetIntegerv` operates on `GLint * data` (32 bit).

Please review if it is possible to somehow rewrite the values of these variables more elegantly?

```cpp
max_viewport_size[0] = max_vp[0];
max_viewport_size[1] = max_vp[1];
```

https://www.khronos.org/opengl/wiki/OpenGL_Type

# Notes

The `glGetInteger64v` function is used in Godot only in the `drivers/gles3/storage/config.cpp` and `drivers/gles3/shader_gles3.cpp` files. It seems that except for one case it doesn't cause any other problems, but the mystery for me remains why it doesn't work for `GL_MAX_VIEWPORT_DIMS` (this is the only case where it sets an array and not a single variable).

Perhaps the problem is that the web export is in WASM32? I have not tested 32-bit Windows / Linux exports.

In addition, according to the Khronos table, `glGetInteger64v` officialy appeared in OpenGL 3.2 / OpenGL ES 3.0 and `glGetIntegerv` had been around since OpenGL 2.0 / OpenGL ES 2.0.

https://registry.khronos.org/OpenGL-Refpages/gl4/html/glGet.xhtml

https://registry.khronos.org/OpenGL-Refpages/es3.0/html/glGet.xhtml

### CODE REVIEW

**Comment by clayjohn** [comment]
I can't take a look now. But we should double check the specification for OpenGL 3.3 and OpenGL ES 3.0 and see if the return value for `GL_MAX_VIEWPORT_DIMS` is a 32 but value or 64 but value. That will inform whether we use the normal variant or the 32 but variant of getIntegerV. You can find that information in the PDF copy of the specification.

File: drivers/gles3/storage/config.cpp [hunk 1]
```diff
@@ -84,7 +84,11 @@ Config::Config() {
 	glGetInteger64v(GL_MAX_TEXTURE_IMAGE_UNITS, &max_texture_image_units);
 	glGetInteger64v(GL_MAX_TEXTURE_SIZE, &max_texture_size);
 	glGetInteger64v(GL_MAX_UNIFORM_BLOCK_SIZE, &max_uniform_buffer_size);
-	glGetInteger64v(GL_MAX_VIEWPORT_DIMS, max_viewport_size);
+
+	GLsizei max_vp[2] = {};
+	glGetIntegerv(GL_MAX_VIEWPORT_DIMS, max_vp);
+	max_viewport_size[0] = max_vp[0];
+	max_viewport_size[1] = max_vp[1];
```
Comment (bruvzg) [inline drivers/gles3/storage/config.cpp:91]: For the reference, it is defined as 32-bit int in ANGLE (which is usually used for WebGL):

https://github.com/google/angle/blob/4d47c73a627a2cb65d943bd764b21e9a33ca4faf/src/libANGLE/queryutils.cpp#L3303-L3308

But the same is true for the other values checked here, except `GL_MAX_UNIFORM_BLOCK_SIZE`.

**Comment by patwork** [comment]
From https://registry.khronos.org/OpenGL/specs/es/3.0/es_spec_3.0.pdf

```
Get value MAX VIEWPORT DIMS
Type 2 × Z+ (Non-negative integer or enumerated token value)
Get Command GetIntegerv
Description Maximum viewport dimensions
```

I think we're safe with 32 bit GetIntegerv.

File: drivers/gles3/storage/config.cpp (hunk 1 above)
Comment (adamscott) [reply drivers/gles3/storage/config.cpp:91]: Then I would suggest to apply this patch file:
```diff
diff --git a/drivers/gles3/storage/config.cpp b/drivers/gles3/storage/config.cpp
index 6b5e227782..40dd340ecf 100644
--- a/drivers/gles3/storage/config.cpp
+++ b/drivers/gles3/storage/config.cpp
@@ -80,11 +80,11 @@ Config::Config() {
 		rgtc_supported = extensions.has("GL_EXT_texture_compression_rgtc") || extensions.has("GL_ARB_texture_compression_rgtc") || extensions.has("EXT_texture_compression_rgtc");
 	}
 
-	glGetInteger64v(GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS, &max_vertex_texture_image_units);
-	glGetInteger64v(GL_MAX_TEXTURE_IMAGE_UNITS, &max_texture_image_units);
-	glGetInteger64v(GL_MAX_TEXTURE_SIZE, &max_texture_size);
+	glGetIntegerv(GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS, &max_vertex_texture_image_units);
+	glGetIntegerv(GL_MAX_TEXTURE_IMAGE_UNITS, &max_texture_image_units);
+	glGetIntegerv(GL_MAX_TEXTURE_SIZE, &max_texture_size);
+	glGetIntegerv(GL_MAX_VIEWPORT_DIMS, max_viewport_size);
 	glGetInteger64v(GL_MAX_UNIFORM_BLOCK_SIZE, &max_uniform_buffer_size);
-	glGetInteger64v(GL_MAX_VIEWPORT_DIMS, max_viewport_size);
 
 	support_anisotropic_filter = extensions.has("GL_EXT_texture_filter_anisotropic");
 	if (support_anisotropic_filter) {
diff --git a/drivers/gles3/storage/config.h b/drivers/gles3/storage/config.h
index c3ab65f0bc..026707aa88 100644
--- a/drivers/gles3/storage/config.h
+++ b/drivers/gles3/storage/config.h
@@ -57,14 +57,15 @@ public:
 	bool use_nearest_mip_filter = false;
 	bool use_depth_prepass = true;
 
-	int64_t max_vertex_texture_image_units = 0;
-	int64_t max_texture_image_units = 0;
-	int64_t max_texture_size = 0;
-	int64_t max_viewport_size[2] = { 0, 0 };
+	int32_t max_vertex_texture_image_units = 0;
+	int32_t max_texture_image_units = 0;
+	int32_t max_texture_size = 0;
+	int32_t max_viewport_size[2] = { 0, 0 };
 	int64_t max_uniform_buffer_size = 0;
-	int64_t max_renderable_elements = 0;
-	int64_t max_renderable_lights = 0;
-	int64_t max_lights_per_object = 0;
+
+	int32_t max_renderable_elements = 0;
+	int32_t max_renderable_lights = 0;
+	int32_t max_lights_per_object = 0;
 
 	bool generate_wireframes = false;
```

Comment (patwork) [reply drivers/gles3/storage/config.cpp:91]: Sure, I can change all variables and related query functions to match OpenGL specification. But won't this be too much of a change, given the other parts of the engine that will be referenced?

Interestingly, GL_MAX_VIEWPORT_DIMS is saved here only to be later mapped to Size2i in `Size2i Utilities::get_maximum_viewport_size()`:

https://github.com/godotengine/godot/blob/5833f597865c773fae3ee09fc4e31d4a243f812d/drivers/gles3/storage/utilities.cpp#L470

Size2i = Vector2i = 2 x 32 bit 💣 

In Vulcan we query for `uint32_t maxViewportDimensions[2];` and in D3D12 simply returning "16384" 🤣 

https://github.com/godotengine/godot/blob/5833f597865c773fae3ee09fc4e31d4a243f812d/drivers/d3d12/rendering_device_driver_d3d12.cpp#L6174-L6176

Anyway, question for you guys, is it safe to change rest of those variables to GLint 32 bit?

I don't know why GL_MAX_UNIFORM_BLOCK_SIZE is different, given that it is mostly 16384-65536:

```
GL_MAX_UNIFORM_BLOCK_SIZE
    params returns one value, the maximum size in basic machine units of a uniform block. The value must be at least 16384. See glUniformBlockBinding. 
```

Comment (clayjohn) [reply drivers/gles3/storage/config.cpp:91]: > Anyway, question for you guys, is it safe to change rest of those variables to GLint 32 bit?

We need to use the function that the spec requires. Some will require the 64 but variant while others won't. Don't worry about the rest of the engine

**Comment by patwork** [comment]
So I more or less reverted most of the changes from https://github.com/godotengine/godot/pull/80909

From the documentation, it seems that actually MAX_UNIFORM_BLOCK_SIZE should be queried as 64 bit. The remaining variables remain GLint (32-bit).

> The total amount of buffer object storage available for any given uniform block is subject to an implementation-dependent limit. The maximum amount of avail- able space, in basic machine units, can be queried by calling GetInteger64v with the constant MAX_UNIFORM_BLOCK_SIZE. If the amount of storage required for a uniform block exceeds this limit, a program may fail to link.

## buffer size

By the way, I checked where the references to `config->max_uniform_buffer_size` are located and I have a question, what to do with the following?

https://github.com/godotengine/godot/blob/5833f597865c773fae3ee09fc4e31d4a243f812d/drivers/gles3/storage/material_storage.cpp#L1111-L1115

`buffer_size` is type of `uint32_t` and `max_uniform_buffer_size` is 64 bit (since Aug 28, 2023) and _sometimes_ can be `INT_MAX + 1` https://github.com/godotengine/godot/pull/80909#issuecomment-1690157045 🤔 

## viewport dims

I changed the reading of `GL_MAX_VIEWPORT_DIMS` in `rasterizer_gles3.cpp` to use the previously retrieved value from Config. This gave rise to two topics:

https://github.com/godotengine/godot/blob/20d5b6c1117579a3187bb2a80f620b40d2dc5ce5/drivers/gles3/rasterizer_gles3.cpp#L396-L406

1. As I understand it, referencing a singleton from Utilities will not cause threading issues here?

2. When the game screen is smaller than the window, this code creates a viewport of size GL_MAX_VIEWPORT_DIMS in each image frame and fills it with black. Isn't this overkill? Using my Firefox / Windows / GTX960 example, this means creating a black 32767x 32767 rectangle every frame. 💣

**Comment by clayjohn** [comment]
> By the way, I checked where the references to `config->max_uniform_buffer_size` are located and I have a question, what to do with the following?
> 
> https://github.com/godotengine/godot/blob/5833f597865c773fae3ee09fc4e31d4a243f812d/drivers/gles3/storage/material_storage.cpp#L1111-L1115
> 
> `buffer_size` is type of `uint32_t` and `max_uniform_buffer_size` is 64 bit (since Aug 28, 2023) and _sometimes_ can be `INT_MAX + 1` [#80909 (comment)](https://github.com/godotengine/godot/pull/80909#issuecomment-1690157045) 🤔

We should probably clamp `max_uniform_buffer_size` to a reasonable size in config.cpp . Maybe `1048576` (1 mb). Realistically almost every GPU only supports a maximum of 65536. I suspect many drivers only support 65536 even when they advertise support for more

> ## viewport dims
> I changed the reading of `GL_MAX_VIEWPORT_DIMS` in `rasterizer_gles3.cpp` to use the previously retrieved value from Config. This gave rise to two topics:
> 
> 1. As I understand it, referencing a singleton from Utilities will not cause threading issues here?

That's right. Reading from the Window is what caused the issue, reading from Config/Utilities is fine.

> 2. When the game screen is smaller than the window, this code creates a viewport of size GL_MAX_VIEWPORT_DIMS in each image frame and fills it with black. Isn't this overkill? Using my Firefox / Windows / GTX960 example, this means creating a black 32767x 32767 rectangle every frame. 💣

Its not a problem. This just sets the Viewport size. The actual drawing will be limited to the size of the framebuffer/texture. 

> ## shader_gles3
> For consistency and DRY, is it safe to add a reference to the singleton from Config in `shader_gles3.cpp`?
> 
> https://github.com/godotengine/godot/blob/5833f597865c773fae3ee09fc4e31d4a243f812d/drivers/gles3/shader_gles3.cpp#L804

Yes.

**Comment by patwork** [comment]
OK, how does it look now?

I've added CLAMP in `config.cpp` to max_uniform_buffer_size (GL_MAX_UNIFORM_BLOCK_SIZE) from minimal 16K (according to khronos.org) to maximum 1MB.

```
max_uniform_buffer_size = CLAMP(max_uniform_buffer_size, 16384, 1048576);
```

💣 One more thing, as I am assuming, `initialize ` in `shader_gles3.cpp` is performed in threads (in my case it runs 12 times). can I be 100% sure that this will always happen already after Config initialisation?

**Comment by clayjohn** [comment]
> 💣 One more thing, as I am assuming, `initialize ` in `shader_gles3.cpp` is performed in threads (in my case it runs 12 times). can I be 100% sure that this will always happen already after Config initialisation?

Yes, Config is initialized before any shaders. I don't think any of the shaders are initialized from threads by the way. I'm fairly certain all shader initialization happens on the rendering thread and at initialization time.

**Comment by patwork** [comment]
Ah, yes, my mistake. `ShaderGLES3::initialize` is run multiple times because it is used by different modules called from `RasterizerGLES3::RasterizerGLES3`.

https://github.com/godotengine/godot/blob/ac95e0f4ff45dcb6f4709edda2c65ff8524c6f7a/drivers/gles3/rasterizer_gles3.cpp#L348-L363

**Review by clayjohn — APPROVED** [review]
Looks good!

**Comment by akien-mga** [comment]
Thanks!
