### PR TITLE
Re-architect how Android plugins are packaged and handled at export time

### LINKED ISSUE #76963: Unable to modify AndroidManifest.xml.
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Ubuntu 22.04

### Issue description

I followed this tutorial
https://docs.godotengine.org/en/stable/tutorials/export/android_custom_build.html#doc-android-custom-build.

I want to create Android launcher app to do this i added following code to AndroidManifest.xml in Android Studio.
`<category android:name="android.intent.category.HOME" />
<category android:name="android.intent.category.DEFAULT" />`

But when I export APK my modifications are removed from AndroidManifest.xml.

### Steps to reproduce

Followed this tutorial
https://docs.godotengine.org/en/stable/tutorials/export/android_custom_build.html#doc-android-custom-build.

then open android project in Android studio and edit AndroidManifest.xml.

### Minimal reproduction project

N/A

### LINKED ISSUE #78782: AndroidManifest.xml can't change the default <activity>
### Godot version

Godot4.0.2 Stable

### System information

Windows11, Inter i3-8100, RX580 2048SP, GLES2.

### Issue description

I want to start my own Activity before .GodotApp starts because the Chinese app market requires users to read and agree to the privacy policy before applying for permissions.
When I checked "use_gradle_build" and modified the Activity corresponding to ".GodotApp" in android/build/AndroidManifest.xml, I removed the "intent-filter" from it and added it to my custom Activity. Then I built the app.
When I installed the app, two game icons appeared on my phone. I know this is because there are two "intent-filter" tags.

### Steps to reproduce

1. Open android/build/AndroidManifest.xml.
2. removed the "intent-filter".
3. added it to custom Activity.
4. built the app.
5. You will find that the previously deleted intent-filter in AndroidManifest.xml still exists, and two intent-filter exist at this time.

### Minimal reproduction project

I had one, but it was too big after packing.

### PR DESCRIPTION
**Pull request by m4gr3d**
The previous packaging format for Godot Android plugins consisted of the plugin's `gdap` config file accompanied by binaries defined in the `gdap` file. 
This format is now deprecated (starting with Godot 4.2), and instead Godot Android plugins are now packaged as `EditorExportPlugin` plugins.

The `EditorExportPlugin` class has been updated with the following methods to provide the necessary set of functionality:
- `_supports_platform`: returns true if the plugin supports the given platform
- `_get_android_dependencies`: retrieve the set of android dependencies (e.g: `org.godot.example:my-plugin:0.0.0`) provided by the plugin
- `_get_android_dependencies_maven_repos`: retrieve the urls of the maven repos for the provided android dependencies
- `_get_android_libraries`: retrieve the local paths of the android libraries (AAR files) provided by the plugin
- `_get_android_manifest_activity_element_contents`: update the contents of the `<activity>` element in the generated Android manifest
- `_get_android_manifest_application_element_contents`: update the contents of the `<application>` element in the generated Android manifest
- `_get_android_manifest_element_contents`: update the contents of the `<manifest>` element in the generated Android manifest

The last three methods allow the plugin to automatically provide changes to the app's manifest which are preserved when the editor is updated, resolving a long standing issue.

Fixes https://github.com/godotengine/godot/issues/76963
Fixes https://github.com/godotengine/godot/issues/78782

**Examples**:
- Sample Godot Android plugins: https://github.com/m4gr3d/Godot-Android-Plugins
- (In-progress) refactor of the Godot OpenXR loaders: https://github.com/GodotVR/godot_openxr_loaders/pull/38

### CODE REVIEW

**Comment by m4gr3d** [comment]
cc @naithar The same concept can be applied on iOS removing the need for the `.gdip` config file, and aligning all the plugins to the same architecture.

**Comment by BastiaanOlij** [comment]
Amazing work @m4gr3d, this indeed solves all the issues we were discussing in the XR meeting. For any logic we add to the core we can add the needed features and permissions to the loader for each platform (though I still hope that in that scenario we'll end up with standardised strings in due time), for any OpenXR extension we implement as a GDExtension we'll be able to handle those in that extension by adding an export plugin class to that as well.

@kisg , @dsnopek you guys should review this as well.

**Comment by akien-mga** [comment]
> cc @naithar The same concept can be applied on iOS removing the need for the `.gdip` config file, and aligning all the plugins to the same architecture.

For the record, naithar hasn't been actively contributing to Godot lately. @bruvzg is the sole maintainer for iOS, he might be able to have a look at doing the matching changes for iOS, though any help from interested contributors would be welcome.

**Comment by m4gr3d** [comment]
Ran into a bug with restoring the saved values of the editor export plugin options from the preset:
- The preset is created in [EditorExport::load_config()](https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/editor/export/editor_export.cpp#L231)
- During its creation, it [retrieves the options from the platform and from the available export plugins](https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/editor/export/editor_export_platform.cpp#L331-L335) and use them to initialize a few maps and list. However this happens before editor plugins in the project have been loaded.
- This causes the saved export plugin options to be [discarded at loading time](https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/editor/export/editor_export.cpp#L309) because [they're not included in the preset's map](https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/editor/export/editor_export_preset.cpp#L34)

Given an export plugin can be added at any time, we may need to separate the platform options from the export plugins' options and store them in the preset regardless of whether the export plugin is available or not.

**Comment by m4gr3d** [comment]
> Ran into a bug with restoring the saved values of the editor export plugin options from the preset:
> 
> * The preset is created in [EditorExport::load_config()](https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/editor/export/editor_export.cpp#L231)
> * During its creation, it [retrieves the options from the platform and from the available export plugins](https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/editor/export/editor_export_platform.cpp#L331-L335) and use them to initialize a few maps and list. However this happens before editor plugins in the project have been loaded.
> * This causes the saved export plugin options to be [discarded at loading time](https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/editor/export/editor_export.cpp#L309) because [they're not included in the preset's map](https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/editor/export/editor_export_preset.cpp#L34)
> 
> Given an export plugin can be added at any time, we may need to separate the platform options from the export plugins' options and store them in the preset regardless of whether the export plugin is available or not.

Fixed by https://github.com/godotengine/godot/pull/79025

**Review by BastiaanOlij — APPROVED** [review]
As mentioned before, I really like this new approach. Code wise it looks really good

File: editor/export/editor_export_plugin.cpp [hunk 1]
```diff
@@ -132,6 +132,25 @@ Variant EditorExportPlugin::get_option(const StringName &p_name) const {
 	return export_preset->get(p_name);
 }
 
+String EditorExportPlugin::_has_valid_export_configuration(const Ref<EditorExportPlatform> &p_export_platform, const Ref<EditorExportPreset> &p_preset) {
+	String warning;
+	if (!_supports_platform(p_export_platform)) {
+		return warning;
+	}
```
Comment (YuriSizov) [inline editor/export/editor_export_plugin.cpp:139]: I think this should result in a warning, not in an early return. Unsupported platform does mean that configuration passed to this method is invalid. The caller can safely check for this cases itself (and you already do that, actually).

File: editor/export/editor_export_plugin.h [hunk 2]
```diff
@@ -142,10 +155,20 @@ class EditorExportPlugin : public RefCounted {
...
-public:
+	virtual bool _supports_platform(const Ref<EditorExportPlatform> &p_export_platform) const;
+
+	virtual PackedStringArray _get_android_dependencies(const Ref<EditorExportPlatform> &p_export_platform, bool p_debug) const;
+	virtual PackedStringArray _get_android_dependencies_maven_repos(const Ref<EditorExportPlatform> &p_export_platform, bool p_debug) const;
+	virtual PackedStringArray _get_android_libraries(const Ref<EditorExportPlatform> &p_export_platform, bool p_debug) const;
+	virtual String _get_android_manifest_activity_element_contents(const Ref<EditorExportPlatform> &p_export_platform, bool p_debug) const;
+	virtual String _get_android_manifest_application_element_contents(const Ref<EditorExportPlatform> &p_export_platform, bool p_debug) const;
+	virtual String _get_android_manifest_element_contents(const Ref<EditorExportPlatform> &p_export_platform, bool p_debug) const;
+
```
Comment (YuriSizov) [inline editor/export/editor_export_plugin.h:171]: These shouldn't be public themselves. If we need to call them from outside of the class, we need public counterparts. Yeah, it's a bit of boilerplate but it's for the sake of code clarity and maintainability. If this is only needed for some small hackish logic within editor/export plugin classes, you can also use class `friend`ness, while keeping the methods private.

File: editor/export/editor_export_preset.cpp [hunk 3]
```diff
@@ -57,7 +57,26 @@ void EditorExportPreset::_bind_methods() {
 }
 
 String EditorExportPreset::_get_property_warning(const StringName &p_name) const {
-	return platform->get_export_option_warning(this, p_name);
+	String warning = platform->get_export_option_warning(this, p_name);
+	if (!warning.is_empty()) {
+		warning += "\n";
+	}
+
+	// Get property warning for the editor export plugins
```
Comment (YuriSizov) [inline editor/export/editor_export_preset.cpp:65]:
```suggestion
	// Get property warning from editor export plugins.
```

**Review by YuriSizov — CHANGES_REQUESTED** [review]
A couple of nitpicks, but also a couple of bigger notes worth addressing.

File: editor/export/editor_export_plugin.h (hunk 2 above)
Comment (YuriSizov) [reply editor/export/editor_export_plugin.h:171]: Or rather, I think C++ virtual methods themselves can be public if that's how they are supposed to be used. Whichever you prefer.

**Review by YuriSizov — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by m4gr3d** [comment]
> If I understand correctly, only the way Godot interacts with the plugins has changed. The way the plugin is written remains the same. Am I correct?
> 
> I've checked the example repo, the package is placed inside the **addons** folder instead of **plugins/android**. Does this matter or location is irrelevant?

The plugin logic (java code) remains the same, but the configuration for the plugin, including the folder layout, are changed to the new format which better aligns with other types of Godot plugins.

> I've checked the example repo, the package is placed inside the addons folder instead of plugins/android. Does this matter or location is irrelevant?

Yes the location matters. See the [tutorial about making Godot plugins](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html) for reference.

The documentation for the Android plugins will be updated to reflect all of these changes prior to Godot 4.2 being stable. The current version of the documentation is now obsolete.

**Comment by tokengamedev** [comment]
This is big change with respect to how plugins are handled. Can the documentation be updated earlier than beta release so that I can test it properly and if any issues than it can be fixed within 4.2 release

**Comment by m4gr3d** [comment]
> This is big change with respect to how plugins are handled. Can the documentation be updated earlier than beta release so that I can test it properly and if any issues than it can be fixed within 4.2 release

It'll be done prior to the beta release, but there are a few more incoming changes / refactor so the documentation will be updated once those are landed and the full end to end plugin flow has been validated.

I'll be posting examples as the refactor progress so you can use those as reference until the documentation is updated.
The Godot OpenXR loader plugin for example has already been updated.

**Comment by WNJH** [comment]
This is machine translation.
I want to delete “intent-filter“ from AndroidManifest.xml. However, after exporting as shown in the diagram, only elements are added.
How can I delete the red circle in the picture?
屏幕截图 2023-08-12 103339
屏幕截图 2023-08-12 103455

**Comment by m4gr3d** [comment]
> This is machine translation. I want to delete “intent-filter“ from AndroidManifest.xml. However, after exporting as shown in the diagram, only elements are added. How can I delete the red circle in the picture? 屏幕截图 2023-08-12 103339 屏幕截图 2023-08-12 103455

@WNJH it's not possible to do so on purpose to prevent export plugins from interfering with each other.
What are you trying to achieve by removing the default `intent-filter`?

**Comment by WNJH** [comment]
> > 这是机器翻译。我想从 AndroidManifest 中删除“意图过滤器”.xml。但是，如图所示导出后，仅添加元素。如何删除图片中的红色圆圈？屏幕截图 2023-08-12 103339 屏幕截图 2023-08-12 103455
> 
> 不可能故意这样做以防止导出插件相互干扰。你想通过删除默认值来实现什么？`intent-filter`

Similar to this https://github.com/godotengine/godot/issues/78782#issue-1778268099
I want to start my custom activity before going to GodotApp and then jump to GodotApp with the button.
So I create a new activity and cut GodotApp's intent-filter from build\AndroidManifest.xml into the custom activity.
When I use "one-click deploy", two apps will be installed on my phone, One is a GodotApp and the other is a custom activity.
So I need to remove "intent-filter" from build\src\debug\AndroidManifest.xml.

build\AndroidManifest.xml:
屏幕截图 2023-08-12 225133

build\src\debug\AndroidManifest.xml:
屏幕截图 2023-08-12 225234

My temporary solution is to make debug\AndroidManifest.xml read-only.

**Comment by m4gr3d** [comment]
@WNJH Only the `android.intent.category.LAUNCHER` category needs to be removed. I'll add an export settings for doing so.

**Comment by m4gr3d** [comment]
@WNJH I've added https://github.com/godotengine/godot/pull/80569 which adds an export setting to control whether the app shows in the app library.

**Comment by WNJH** [comment]
@m4gr3d Thank you!

I have one more small question." one-click deploy" Does it have to go directly to GodotApp? After I annotated "intent-filter", "one-click deploy" did not display the custom activity. But when I quit, and tap into the APP on my phone, the custom activity is displayed.

**Comment by m4gr3d** [comment]
> @m4gr3d Thank you!
> 
> I have one more small question." one-click deploy" Does it have to go directly to GodotApp? After I annotated "intent-filter", "one-click deploy" did not display the custom activity. But when I quit, and tap into the APP on my phone, the custom activity is displayed.

@WNJH Yes it launches the `GodotApp` directly. 
@BastiaanOlij is working on a proposal to improve the launch flow. As part of that proposal, we can add the option to specify which activity to launch, but for the moment it's hardcoded to the `GodotApp` since that's the most prevalent launch flow.

**Comment by duarteroso** [comment]
Is there an early version of the updated documentation that I could read? Having a crash in gd_mono.cpp:431 and I believe it to be related to the GodotPlugins with a failed initialization (a blank project works fine). 
Instead of opening an issue, I'd rather try seriously 🙂

**Comment by m4gr3d** [comment]
> Is there an early version of the updated documentation that I could read? Having a crash in gd_mono.cpp:431 and I believe it to be related to the GodotPlugins with a failed initialization (a blank project works fine). Instead of opening an issue, I'd rather try seriously 🙂

@duarteroso Early draft of the documentation update available in https://github.com/godotengine/godot-docs/pull/7884
