### PR TITLE
Fix VoxelGI MultiMesh and CSG mesh baking

### LINKED ISSUE #56024: Vulkan: VoxelGI does not take MultiMeshes into account for baking
*Related to https://github.com/godotengine/godot/issues/56027 which is for LightmapGI.*

### Godot version

4.0.dev (1cbf3947d)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

*Similar to https://github.com/godotengine/godot/issues/45313, but with the new voxel GI implementation in `master`.*

VoxelGI does not take MultiMeshes into account for baking. On the screenshot below, you can see that objects on the left are smoothly shaded by GI. On the right, it looks very flat due to those objects not being present in the bake:

Left: Individual MeshInstances, right: MultiMeshInstance:

The VoxelGI Lighting debug draw mode also evidences that MultiMeshes are simply not included in the VoxelGI bake, despite having the **Baked** global illumination mode:

MultiMeshInstances **are** taken into account by SDFGI however, as demonstrated by the screenshots below:

SDFGI Cascades debug draw mode:

### Steps to reproduce

- Add a MeshInstance node with a BoxMesh to act as a floor. Resize it so it can fit several objects on top. Set the global illumination mode to **Baked** in the inspector.
- Add a MeshInstance node with a BoxMesh to act as a source mesh for the MultiMesh. Set the global illumination mode to **Baked** in the inspector.
- Add a MultiMeshInstance node. Use the menu at the top of the 3D editor viewport to populate the MultiMeshInstance with BoxMeshes.
- Add a VoxelGI node, select it and click **Bake** at the top of the 3D editor viewport.

### Minimal reproduction project

[test_voxelgi_multimesh.zip](https://github.com/godotengine/godot/files/7736590/test_voxelgi_multimesh.zip)

### LINKED ISSUE #79987: VoxelGI dynamic meshes linger in original position in GI data after bake, have lower energy when moved.
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Laptop GPU (NVIDIA; 31.0.15.3667) - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 Threads)

### Issue description

When baking VoxelGI with a dynamic GI mesh, that mesh appears to stay in place in the GI data when moved. Furthermore, the mesh appears to emit less energy in the GI solution when it does move.

### Steps to reproduce

Open the repro project
Select VoxelGI to rebake
Move the box named Dynamic and notice 1) it's original GI data stays in place and 2) it is somewhat darker.

### Minimal reproduction project

[BugProject.zip](https://github.com/godotengine/godot/files/12195684/BugProject.zip)

### PR DESCRIPTION
**Pull request by bitsawer**
* Fixes https://github.com/godotengine/godot/issues/56024
* Fixes https://github.com/godotengine/godot/issues/79987 as a side effect.

Adds `MultiMeshInstance3D::get_meshes()` so that VoxelGI will collect the non-node geometry from MultiMeshInstance3D. That method is the semi-secret handshake that VoxelGI uses for this, currently GridMap, CSGShape3D and after this PR MultiMeshInstance3D support it. I'm not a big fan of that way of exposing this functionality, it's kind of limited, hard to extend and has to be made public only for this one usecase, but it's currently the supported way.

Also fixes a node GI mode check so that disabled, static and dynamic options work correctly. Bug https://github.com/godotengine/godot/issues/79987 was caused because this check was missing from one branch when collecting nodes during VoxelGI baking. This meant that CSGShape3D VoxelGI baking was wrong in following ways depending on its GI mode:

* Disabled was actually Static
* Static was Static (correct)
* Dynamic was both Static AND Dynamic, which is not normally possible.

The last issue caused https://github.com/godotengine/godot/issues/79987 as the CSGShape3D was both baked as static while also considered dynamic, which caused some visual issues.

I also added the `ERR_FAIL_COND_MSG()` transform check to `Voxelizer::plot_mesh()` because of https://github.com/godotengine/godot/issues/75485. It's pretty easy to accidentally create NAN's and INF's when currently playing around with MultiMesh, this adds a simple validation check and skips the mesh with an error message if the transform is obviously wrong.

### CODE REVIEW

**Comment by fire** [comment]
How would you recommend I test this?

**Comment by bitsawer** [comment]
I think the MRP projects and their repro steps in the linked issues are a good start. You can also visualize the generated VoxelGI data in the 3D view by selecting `Perspective -> Display Advanced -> VoxelGI Lightning` after baking the VoxelGI.

Basically before this PR MultiMesh does not create any VoxelGI data when baked and CSG shape Global Illumination Mode is incorrect. After this PR the MultiMeshes should create VoxelGI representation and CSG shape mode should be correct. Also in both cases setting their node GI mode to disabled should also stop creating VoxelGI data for them and setting it to Static or Dynamic should enable it (after baking).

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` c5291a3555343e8aa5aefa1c7e17f2ad05ee1fc9), it works as expected.

image

out webp

File: scene/3d/multimesh_instance_3d.cpp [hunk 1]
```diff
@@ -49,6 +52,26 @@ Ref<MultiMesh> MultiMeshInstance3D::get_multimesh() const {
...
+	if (count == -1) {
+		count = multimesh->get_instance_count();
+	}
+
+	Ref<Mesh> mesh = multimesh->get_mesh();
+
+	Array results;
+	for (int i = 0; i < count; i++) {
+		results.push_back(multimesh->get_instance_transform(i));
+		results.push_back(mesh);
```
Comment (clayjohn) [inline scene/3d/multimesh_instance_3d.cpp:70]: I wonder if it would be better to return a dictionary with a mesh and an array of instance transforms since there can only ever be one mesh.

Alternatively, we could just have a function to return the array of transforms, since the mesh can be obtained already

Looking deeper I see this is so that it can match the CSG API. Honestly, I would add another condition to the VoxelGI code instead of exposing this function. We already have a different case for MeshInstance3D. I would add a new case for MultiMeshInstance3D

File: scene/3d/voxel_gi.cpp [hunk 2]
```diff
@@ -338,7 +347,7 @@ void VoxelGI::_find_meshes(Node *p_at_node, List<PlotMesh> &plot_meshes) {
 
 	Node3D *s = Object::cast_to<Node3D>(p_at_node);
 	if (s) {
-		if (s->is_visible_in_tree()) {
+		if (is_node_voxel_bakeable(s)) {
 			Array meshes = p_at_node->call("get_meshes");
```
Comment (clayjohn) [inline scene/3d/voxel_gi.cpp:351]: To clarify my earlier comment. I would add:
```suggestion
Array meshes;

MultiMeshInstance3D *mmi = Object::cast_to<MultiMeshInstance3D>(p_at_node);
if (mmi ) {
    // Create meshes from MultiMesh properties
} else {
meshes = p_at_node->call("get_meshes");
}
```

File: scene/3d/voxel_gi.cpp [hunk 3]
```diff
@@ -314,9 +314,18 @@ Ref<CameraAttributes> VoxelGI::get_camera_attributes() const {
 	return camera_attributes;
 }
 
+static bool is_node_voxel_bakeable(Node3D *p_node) {
+	bool static_gi = true;
+	GeometryInstance3D *geometry = Object::cast_to<GeometryInstance3D>(p_node);
+	if (geometry != nullptr) {
+		static_gi = geometry->get_gi_mode() == GeometryInstance3D::GI_MODE_STATIC;
+	}
+	return static_gi && p_node->is_visible_in_tree();
```
Comment (AThousandShips) [inline scene/3d/voxel_gi.cpp:323]: I'd exit early with false if `p_node->is_visible_in_tree()` is false here

**Review by AThousandShips — APPROVED** [review]

**Comment by bitsawer** [comment]
I kept the `MultiMeshInstance3D::get_meshes()` method and data format but removed the the scripting binding and instead call it directly as suggested. The voxel baker doesn't really have any mesh instancing support, we have to pass each mesh and transform separately and bake them individually anyway. However, this is pretty fast and only affects the baking step, this data doesn't exist during runtime.

I also noticed that `GPUParticlesCollisionSDF3D` uses similar logic and format too, so keeping the logic in one place in MultiMeshInstance3D is probably a good idea if we also want to make the particle collision generation support multimeshes in the future. However, that might need some planning to make sure people don't accidentally enable particle collisions with their million vertex grass multimesh or something like that. 

Also rebased the PR and tweaked the `is_node_voxel_bakeable()` to return early in a few cases as suggested. I think current version is a pretty good, we can now also add/unify the particles multimesh support in another PR if needed without breaking any existing API's.

**Review by clayjohn — APPROVED** [review]
Looks good to me

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.4.
