### PR TITLE
Register the export info correctly when a script is used as the variable type for Node

### LINKED ISSUE #73993: Exported node types with a custom type defined by a preloaded const script path can't be selected in inspector.
### Godot version

SHA-1: 1bd0b296e195a622c362a12d8e3dca51e8648578

### System information

Windows 10, Vulkan, Intel® Core™ i7-8700K, Nvidia GTX 1080 (471.11)

### Issue description

Scripts now allow you to export node variables with explicit types, including those defined by scripts. However, while using a script type defined by a class_name will allow expected valid node to be selectable in the inspector, if the type is instead defined by a const, for example:

```
const type_b_const = preload("res://type_b.gd")
@export var type_b: type_b_const = null
```

No nodes with this script attached will be selectable in the inspector.

### Steps to reproduce

Create a node and attach a script to it (we call this script in the example 'type_b.gd')
Create another node, attach another script to it, and export a variable like this:
```
const type_b_const = preload("res://type_b.gd")
@export var type_b: type_b_const = null
```
Attempt to assign the type_b variable the node with the type_b script attached a note that it is not selectable.

### Minimal reproduction project

[TypeSelection.zip](https://github.com/godotengine/godot/files/10834394/TypeSelection.zip)

### PR DESCRIPTION
**Pull request by preslavnpetrov**
This PR fixes #73993

It will allow a preloaded const script to be used as the type of an exported variable in GDScript

### CODE REVIEW

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -4343,6 +4343,11 @@ bool GDScriptParser::export_annotations(const AnnotationNode *p_annotation, Node
 					variable->export_info.hint = PROPERTY_HINT_RESOURCE_TYPE;
 					variable->export_info.hint_string = class_name;
 				}
+				if (class_name != StringName() && native_base != StringName() && ClassDB::is_parent_class(native_base, SNAME("Node"))) {
+					variable->export_info.type = Variant::OBJECT;
+					variable->export_info.hint = PROPERTY_HINT_NODE_TYPE;
+					variable->export_info.hint_string = class_name;
+				}
```
Comment (dalexeev) [inline modules/gdscript/gdscript_parser.cpp:4350]: For consistency with `GDScriptParser::DataType::CLASS` I suggest replace lines 4341-4350 with:

```c++
				if (ClassDB::is_parent_class(native_base, SNAME("Resource"))) {
					variable->export_info.type = Variant::OBJECT;
					variable->export_info.hint = PROPERTY_HINT_RESOURCE_TYPE;
					variable->export_info.hint_string = class_name;
				} else if (ClassDB::is_parent_class(native_base, SNAME("Node"))) {
					variable->export_info.type = Variant::OBJECT;
					variable->export_info.hint = PROPERTY_HINT_NODE_TYPE;
					variable->export_info.hint_string = class_name;
				} else {
					push_error(R"(Export type can only be built-in, a resource, a node, or an enum.)", p_annotation);
					return false;
				}
```

Comment (preslavnpetrov) [reply modules/gdscript/gdscript_parser.cpp:4352]: Ah good catch, I've updated the changes to reflect that now.

File: modules/gdscript/gdscript_parser.cpp [hunk 2]
```diff
@@ -4342,6 +4342,13 @@ bool GDScriptParser::export_annotations(const AnnotationNode *p_annotation, Node
...
 					variable->export_info.hint = PROPERTY_HINT_RESOURCE_TYPE;
 					variable->export_info.hint_string = class_name;
+				} else if (class_name != StringName() && native_base != StringName() && ClassDB::is_parent_class(native_base, SNAME("Node"))) {
+					variable->export_info.type = Variant::OBJECT;
+					variable->export_info.hint = PROPERTY_HINT_NODE_TYPE;
+					variable->export_info.hint_string = class_name;
+				} else {
+					push_error(R"(Export type can only be built-in, a resource, a node, or an enum.)", p_annotation);
+					return false;
 				}
```
Comment (dalexeev) [inline modules/gdscript/gdscript_parser.cpp:4352]: Please add a check for global classes, which is currently missing. The inspector currently cannot work with non-global and inner classes.

```c++
				if (class_name != StringName()) {
					push_error(R"(Only global classes can be exported.)", p_annotation);
					return false;
				}
				if (ClassDB::is_parent_class(native_base, SNAME("Resource"))) {
					variable->export_info.type = Variant::OBJECT;
					variable->export_info.hint = PROPERTY_HINT_RESOURCE_TYPE;
					variable->export_info.hint_string = class_name;
				} else if (ClassDB::is_parent_class(native_base, SNAME("Node"))) {
					variable->export_info.type = Variant::OBJECT;
					variable->export_info.hint = PROPERTY_HINT_NODE_TYPE;
					variable->export_info.hint_string = class_name;
				} else {
					push_error(R"(Export type can only be built-in, a resource, a node, or an enum.)", p_annotation);
					return false;
				}
```

```c++
			case GDScriptParser::DataType::CLASS: {
				StringName class_name;
				if (export_type.class_type) {
					class_name = export_type.class_type->get_global_name();
				}
				if (class_name != StringName()) {
					push_error(R"(Only global classes can be exported.)", p_annotation);
					return false;
				}
				if (ClassDB::is_parent_class(export_type.native_type, SNAME("Resource"))) {
					variable->export_info.type = Variant::OBJECT;
					variable->export_info.hint = PROPERTY_HINT_RESOURCE_TYPE;
					variable->export_info.hint_string = class_name;
				} else if (ClassDB::is_parent_class(export_type.native_type, SNAME("Node"))) {
					variable->export_info.type = Variant::OBJECT;
					variable->export_info.hint = PROPERTY_HINT_NODE_TYPE;
					variable->export_info.hint_string = class_name;
				} else {
					push_error(R"(Export type can only be built-in, a resource, a node, or an enum.)", p_annotation);
					return false;
				}
			} break;
```

Also it would be nice to add tests, see [`export_variable.gd`](https://github.com/godotengine/godot/blob/master/modules/gdscript/tests/scripts/parser/features/export_variable.gd). To test `CLASS` you can add a `class_name` to the current script. To test `SCRIPT` you can add `.notest.gd` scripts and `const`-`preload` them.

Comment (preslavnpetrov) [reply modules/gdscript/gdscript_parser.cpp:4352]: Makes sense, will get that set up asap, probably the weekend

Comment (preslavnpetrov) [reply modules/gdscript/gdscript_parser.cpp:4363]: Sorry I totally blanked on the test part of this, unresolving so I can look at it again

Comment (preslavnpetrov) [reply modules/gdscript/gdscript_parser.cpp:4370]: Finally got some time to put these tests in! Resolving the conversation, hope that's good to merge now :)

File: modules/gdscript/tests/scripts/parser/features/export_variable.gd [hunk 3]
```diff
@@ -20,6 +22,10 @@ const Utils = preload("../../utils.notest.gd")
 @export var test_image: Image
 @export var test_timer: Timer
 
+# Custom Scripts
```
Comment (dalexeev) [inline modules/gdscript/tests/scripts/parser/features/export_variable.gd:25]:
```suggestion
# Global custom classes.
```

**Review by dalexeev — COMMENTED** [review]
Sorry for delay. Here's my suggestion for making `CLASS` and `SCRIPT` cases consistent:

<details>
<summary>Patch</summary>

```diff
diff --git a/modules/gdscript/gdscript_parser.cpp b/modules/gdscript/gdscript_parser.cpp
index da599bf57b..771ccf47b7 100644
--- a/modules/gdscript/gdscript_parser.cpp
+++ b/modules/gdscript/gdscript_parser.cpp
@@ -4327,11 +4327,11 @@ bool GDScriptParser::export_annotations(const AnnotationNode *p_annotation, Node
 				if (ClassDB::is_parent_class(export_type.native_type, SNAME("Resource"))) {
 					variable->export_info.type = Variant::OBJECT;
 					variable->export_info.hint = PROPERTY_HINT_RESOURCE_TYPE;
-					variable->export_info.hint_string = export_type.to_string();
+					variable->export_info.hint_string = class_name;
 				} else if (ClassDB::is_parent_class(export_type.native_type, SNAME("Node"))) {
 					variable->export_info.type = Variant::OBJECT;
 					variable->export_info.hint = PROPERTY_HINT_NODE_TYPE;
-					variable->export_info.hint_string = export_type.to_string();
+					variable->export_info.hint_string = class_name;
 				} else {
 					push_error(R"(Export type can only be built-in, a resource, a node, or an enum.)", p_annotation);
 					return false;
@@ -4340,27 +4340,24 @@ bool GDScriptParser::export_annotations(const AnnotationNode *p_annotation, Node
 
 			case GDScriptParser::DataType::SCRIPT: {
 				StringName class_name;
-				StringName native_base;
 				if (export_type.script_type.is_valid()) {
-					class_name = export_type.script_type->get_language()->get_global_class_name(export_type.script_type->get_path());
-					native_base = export_type.script_type->get_instance_base_type();
+					class_name = export_type.script_type->get_global_name();
 				}
 				if (class_name == StringName()) {
 					Ref<Script> script = ResourceLoader::load(export_type.script_path, SNAME("Script"));
 					if (script.is_valid()) {
-						class_name = script->get_language()->get_global_class_name(export_type.script_path);
-						native_base = script->get_instance_base_type();
+						class_name = script->get_global_name();
 					}
 				}
 				if (class_name == StringName()) {
 					push_error(R"(Script export type must be a global class.)", p_annotation);
 					return false;
 				}
-				if (native_base != StringName() && ClassDB::is_parent_class(native_base, SNAME("Resource"))) {
+				if (ClassDB::is_parent_class(export_type.native_type, SNAME("Resource"))) {
 					variable->export_info.type = Variant::OBJECT;
 					variable->export_info.hint = PROPERTY_HINT_RESOURCE_TYPE;
 					variable->export_info.hint_string = class_name;
-				} else if (native_base != StringName() && ClassDB::is_parent_class(native_base, SNAME("Node"))) {
+				} else if (ClassDB::is_parent_class(export_type.native_type, SNAME("Node"))) {
 					variable->export_info.type = Variant::OBJECT;
 					variable->export_info.hint = PROPERTY_HINT_NODE_TYPE;
 					variable->export_info.hint_string = class_name;
```

</details>

File: modules/gdscript/tests/scripts/parser/features/export_variable.gd (hunk 3 above)
Comment (preslavnpetrov) [reply modules/gdscript/tests/scripts/parser/features/export_variable.gd]: Thanks! I've put those changes in the latest commit :)

File: modules/gdscript/tests/scripts/parser/features/export_variable.gd [hunk 4]
```diff
@@ -20,6 +22,10 @@ const Utils = preload("../../utils.notest.gd")
 @export var test_image: Image
 @export var test_timer: Timer
 
+# Global custom classes
```
Comment (dalexeev) [inline modules/gdscript/tests/scripts/parser/features/export_variable.gd:25]:
```suggestion
# Global custom classes.
```

**Review by dalexeev — APPROVED** [review]

File: modules/gdscript/tests/scripts/parser/features/export_variable.gd (hunk 4 above)
Comment (akien-mga) [reply modules/gdscript/tests/scripts/parser/features/export_variable.gd:25]: While addressing this, please also squash the commits so there's only one commit in this PR. See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

Comment (preslavnpetrov) [reply modules/gdscript/tests/scripts/parser/features/export_variable.gd:25]: Ah just saw that extra commit sorry, will do.

**Comment by akien-mga** [comment]
Thanks!

**Comment by shakesoda** [comment]
this merge seems to break spatial gardener (and, looks like, anything that extends with a script path instead of a class name)

**Comment by dalexeev** [comment]
@shakesoda Please open a new issue if you find a regression. Note that `@export` requires global classes, as [documented](https://docs.godotengine.org/en/stable/classes/class_%40gdscript.html#class-gdscript-annotation-export) (unfortunately, the Inspector does not currently support unnamed and inner classes). The previous behavior with no GDScript error was a bug, there was an inconsistency between the `SCRIPT` and `CLASS` datatypes.
