### PR TITLE
Fix `OS.find_scancode_from_string()` not working with modifiers

### LINKED ISSUE #17430: find_scancode_from_string does not work on scancodes with modifiers
**Godot version:**
3.0.2

**OS**
Linux Ubuntu 17.10

image

**Issue description:**
`find_scancode_from_string` returns a scancode based on a given string input.
If given for example `"Shift+J"`, it should return `33554506`.
But it returns `0` for all inputs with modifiers such as shift or ctrl etc.

`OS.get_scancode_string` returns `Shift+J` when passed `33554506`, the values
are from there.
So serializing with `OS.get_scancode_string` works, but not the other way around.

**Steps to reproduce:**
`print(str(OS.find_scancode_from_string("Shift+J")))`

**Minimal reproduction project:**
[ExampleProject.zip](https://github.com/godotengine/godot/files/1800143/ExampleProject.zip)

### PR DESCRIPTION
**Pull request by madmiraal**
Fixes #17430.

Tested by converting scancodes to strings using `OS.get_scancode_string()` and converting them back again using `OS.find_scancode_from_string()`:
```
65 -> A -> 65
33554498 -> Shift+B -> 33554498
67108931 -> Alt+C -> 67108931
134217796 -> Meta+D -> 134217796
301989958 -> Shift+Control+F -> 301989958
335544389 -> Alt+Control+E -> 335544389
301989959 -> Shift+Control+G -> 301989959
369098824 -> Shift+Alt+Control+H -> 369098824
```

### CODE REVIEW

File: core/os/keyboard.cpp [hunk 1]
```diff
@@ -426,17 +426,38 @@ String keycode_get_string(uint32_t p_code) {
...
+		} else if (code_part.nocasecmp_to(find_keycode_name(KEY_ALT)) == 0) {
+			code += KEY_MASK_ALT;
+		} else if (code_part.nocasecmp_to(find_keycode_name(KEY_CONTROL)) == 0) {
+			code += KEY_MASK_CTRL;
+		} else if (code_part.nocasecmp_to(find_keycode_name(KEY_META)) == 0) {
+			code += KEY_MASK_META;
+		}
+	}
+
+	return code;
```
Comment (bruvzg) [inline core/os/keyboard.cpp:460]: This probably need to account for the alternative names:
- `Key::META` - "Command", "Windows" or "Meta"
- `Key::ALT` - "Option" or "Alt"

**Review by bruvzg — COMMENTED** [review]
Seems fine, needs rebase (`Key` enum instead of `int`/`KEY_*`) also probably should check all alternative names for different platforms.

File: core/os/keyboard.cpp (hunk 1 above)
Comment (madmiraal) [reply core/os/keyboard.cpp]: Done as part of the rebase.

File: core/os/keyboard.cpp [hunk 2]
```diff
@@ -400,17 +400,40 @@ String keycode_get_string(Key p_code) {
...
 	}
 
-	return Key::NONE;
+	for (int part = 0; part < code_parts.size() - 1; part++) {
+		String code_part = code_parts[part];
+		if (code_part.nocasecmp_to(find_keycode_name(Key::SHIFT)) == 0) {
+			keycode |= KeyModifierMask::SHIFT;
+		} else if (code_part.nocasecmp_to(find_keycode_name(Key::CTRL)) == 0) {
+			keycode |= KeyModifierMask::CTRL;
+		} else if (code_part.nocasecmp_to(find_keycode_name(Key::META)) == 0) {
```
Comment (bruvzg) [inline core/os/keyboard.cpp:427]:
```suggestion
		} else if ((code_part.nocasecmp_to("Command") == 0) || (code_part.nocasecmp_to("Windows") == 0) || (code_part.nocasecmp_to("Meta") == 0)) {
```

File: core/os/keyboard.cpp [hunk 3]
```diff
@@ -400,17 +400,40 @@ String keycode_get_string(Key p_code) {
...
+			keycode |= KeyModifierMask::META;
+		} else if (code_part.nocasecmp_to(find_keycode_name(Key::CMD_OR_CTRL)) == 0) {
+			keycode |= KeyModifierMask::CMD_OR_CTRL;
+		} else if (code_part.nocasecmp_to(find_keycode_name(Key::ALT)) == 0) {
+			keycode |= KeyModifierMask::ALT;
+		}
```
Comment (bruvzg) [inline core/os/keyboard.cpp:433]:
```suggestion
		} else if ((code_part.nocasecmp_to("Option") == 0) || (code_part.nocasecmp_to("Alt") == 0)) {
			keycode |= KeyModifierMask::ALT;
		}
```

Comment (bruvzg) [reply core/os/keyboard.cpp:433]: Three's no need to check for `CMD_OR_CTRL` it's an alias to `CTRL` or `META`. `META` and `ALT` can have different names depending on platform, so it's better to check all of them.

File: core/os/keyboard.cpp (hunk 2 above)
Comment (madmiraal) [reply core/os/keyboard.cpp:427]: This shouldn't be necessary, because the variations are defined at compile time:
https://github.com/godotengine/godot/blob/5eb2011423fd96d42f97757b6e582712498180c3/core/os/keyboard.cpp#L64-L75

File: core/os/keyboard.cpp (hunk 3 above)
Comment (madmiraal) [reply core/os/keyboard.cpp]: I've removed the `CMD_OR_CTRL` option.

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
