### PR TITLE
[3.x] Android: Refactor Custom Build options in export preset

### LINKED ISSUE #62465: "Changing the "Target SDK" is not valid" error even though I never tried to
### Godot version

3.5. RC5

### System information

Win, Nvidea 765M

### Issue description

I'm testing the latest Godot 3.5.RC build, trying the one click deploy but can't export and get this error:

image

I have not touched the "Target SDK":

image

If I enable "Use Custom Build" like the error message seems to want me to, I get another error which also makes no sense to me (I have the 3.5.RC5 templates installed, even restarted Godot 3.5RC5 after just to make sure):

image

Not sure if this is related to https://github.com/godotengine/godot/pull/61691 or https://github.com/godotengine/godot/pull/51815 since the times I have tested Godot 3.5 so far, I never tried to export.

### Steps to reproduce

Trying to export working 3.4.4 project to Android.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by akien-mga**
Instead of reusing the custom_template/ prefix which is actually only
used for the prebuilt APK workflow, we add a new custom_build/ prefix.

This is a slight compat breakage (users will have to redo their config)
but enables us to group the Min SDK and Target SDK options where they make
sense, and avoid reusing the previously hardcoded Target SDK 30 from
Godot 3.4.

Those two options are now strings instead of integers so that we can keep
them empty by default, and show their default value using a placeholder.
So some validation has been added to make sure they are proper ints.
The upper bound on Target SDK was also removed as it has little use if
it's limited to only the default target SDK (as it's typically used to
support newer SDKs faster than we do with official builds).

The export info dialog is now exclusive so that when it doesn't auto-close,
i.e. when it errors, you don't close it by mistake by clicking outside.

- Fixes #62465.
- `master` PR: #62611.
- If we go with this solution, the documentation will need to be updated so that references to `custom_template/use_custom_build` are updated (both in text and in screenshots).
  * Done: https://github.com/godotengine/godot-docs/pull/5905
- For the upcoming 3.4.5 where we increased the Target SDK to 31, users will face #62465 again. I wouldn't want to break compatibility there, so we might need to find another hack (maybe just changing the error message so users have a clue that they should change "30" to "31").
  * Implemented a non-compat breaking option for 3.4.5: #62609.

Screenshots:

image
image
image
Screenshot_20220701_201231
(Integer validation would also allow negative numbers, but the checks that `min_sdk >= 19` and `min_sdk < target_sdk` prevent this already.)

### CODE REVIEW

**Comment by akien-mga** [comment]
@m4gr3d BTW, the follow warning is printed when doing custom builds:
image

We should likely upgrade the plugin ASAP.

File: platform/android/export/export_plugin.cpp [hunk 1]
```diff
@@ -2230,45 +2232,70 @@ bool EditorExportPlatformAndroid::can_export(const Ref<EditorExportPreset> &p_pr
...
+			err += TTR("\"Target SDK\" can only be overridden when \"Use Custom Build\" is enabled.");
+			err += "\n";
+		}
+		if (!target_sdk_str.is_valid_integer()) {
+			valid = false;
+			err += vformat(TTR("\"Target SDK\" should be a valid integer, but got \"%s\" which is invalid."), target_sdk_str);
+			err += "\n";
+		} else {
+			target_sdk_int = target_sdk_str.to_int();
+		}
```
Comment (m4gr3d) [inline platform/android/export/export_plugin.cpp:2293]: Same comment as in https://github.com/godotengine/godot/pull/62611/files#r912493588, we should include a warning when the target sdk is greater than the default.

**Review by m4gr3d — DISMISSED** [review]

File: platform/android/export/export_plugin.cpp (hunk 1 above)
Comment (akien-mga) [reply platform/android/export/export_plugin.cpp]: Fixed.

**Comment by akien-mga** [comment]
Added a warning for target SDK > 32 as we discussed:
image
