### PR TITLE
Fixes invalid writes in Image operations

### LINKED ISSUE #29953: Invalid write(and possibly crash) in Image::set_pixel, Image::fill, Image::blit_rect
**Godot version:**
3.2.dev.custom_build. 02319dceb

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
`Image::fill`
```
for (int k = 0; k < pixel_size; k++) {
	dst[k] = dst_data_ptr[k];
```
```
Invalid write of size 1
   at 0x366E9DC: Image::fill(Color const&) (image.cpp:2318)
   by 0x20C2514: MethodBind1<Color const&>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:775)
   by 0x36AD2B0: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:940)
   by 0x3749D3A: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1073)
   by 0x14ABEB9: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1083)
   by 0x1456E93: GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (gdscript.cpp:1192)
   by 0x28E4680: Node::_notification(int) (node.cpp:60)
   by 0x141B4C9: Node::_notificationv(int, bool) (node.h:46)
   by 0x141BB10: CanvasItem::_notificationv(int, bool) (canvas_item.h:166)
   by 0x2D3652A: Node2D::_notificationv(int, bool) (node_2d.h:38)
   by 0x36AD429: Object::notification(int, bool) (object.cpp:950)
   by 0x291917A: SceneTree::_notify_group_pause(StringName const&, int) (scene_tree.cpp:975)
 Address 0x25ff9668 is 0 bytes after a block of size 24 alloc'd
   at 0x58CA74F: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x37E8F87: Memory::alloc_static(unsigned long, bool) (memory.cpp:85)
   by 0x13F45BC: PoolVector<unsigned char>::resize(int) (pool_vector.h:577)
   by 0x366A769: Image::create(int, int, bool, Image::Format) (image.cpp:1598)
   by 0x368F10C: Image::_create_empty(int, int, bool, Image::Format) (image.h:155)
   by 0x3699E8D: MethodBind4<int, int, bool, Image::Format>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:3115)
   by 0x36AD2B0: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:940)
   by 0x3749D3A: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1073)
   by 0x14ABEB9: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1083)
   by 0x1456E93: GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (gdscript.cpp:1192)
   by 0x28E4680: Node::_notification(int) (node.cpp:60)
   by 0x141B4C9: Node::_notificationv(int, bool) (node.h:46)
```
`Image::set_pixel`
```
ptr[ofs * 2 + 0] = uint8_t(CLAMP(p_color.get_v() * 255.0, 0, 255));
ptr[ofs * 2 + 1] = uint8_t(CLAMP(p_color.a * 255.0, 0, 255));
```
```
Invalid write of size 1
   at 0x36715E2: Image::set_pixel(int, int, Color const&) (image.cpp:2560)
   by 0x3694C72: MethodBind3<int, int, Color const&>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:2303)
   by 0x36AD2B0: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:940)
   by 0x3749D3A: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1073)
   by 0x14ABEB9: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1083)
   by 0x1456E93: GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (gdscript.cpp:1192)
   by 0x28E4680: Node::_notification(int) (node.cpp:60)
   by 0x141B4C9: Node::_notificationv(int, bool) (node.h:46)
   by 0x141BB10: CanvasItem::_notificationv(int, bool) (canvas_item.h:166)
   by 0x2D3652A: Node2D::_notificationv(int, bool) (node_2d.h:38)
   by 0x36AD429: Object::notification(int, bool) (object.cpp:950)
   by 0x291917A: SceneTree::_notify_group_pause(StringName const&, int) (scene_tree.cpp:975)
 Address 0x14011a29 is 281 bytes inside a block of size 16,400 free'd
   at 0x58CB97B: free (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x37E9370: Memory::free_static(void*, bool) (memory.cpp:181)
   by 0x13A4632: PoolVector<unsigned char>::_unreference() (pool_vector.h:246)
   by 0x180BDFC: PoolVector<unsigned char>::_reference(PoolVector<unsigned char> const&) (pool_vector.h:196)
   by 0x180BD32: PoolVector<unsigned char>::operator=(PoolVector<unsigned char> const&) (pool_vector.h:463)
   by 0x368F1D6: Image::_copy_internals_from(Image const&) (image.h:172)
   by 0x3665E1B: Image::convert(Image::Format) (image.cpp:503)
   by 0x3679351: Image::normalmap_to_xy() (image.cpp:2882)
   by 0x143479E: MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:59)
   by 0x36AD2B0: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:940)
   by 0x3749D3A: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1073)
   by 0x14ABEB9: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1083)
 Block was alloc'd at
   at 0x58CA74F: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x37E8F87: Memory::alloc_static(unsigned long, bool) (memory.cpp:85)
   by 0x13F45BC: PoolVector<unsigned char>::resize(int) (pool_vector.h:577)
   by 0x1F2D7CF: PNGDriverCommon::png_to_image(unsigned char const*, unsigned long, Ref<Image>) (png_driver_common.cpp:106)
   by 0x1F2CE83: ImageLoaderPNG::load_image(Ref<Image>, FileAccess*, bool, float) (image_loader_png.cpp:54)
   by 0x386B814: ImageLoader::load_image(String, Ref<Image>, FileAccess*, bool, float) (image_loader.cpp:67)
   by 0x366BC3F: Image::load(String const&) (image.cpp:1904)
   by 0x154561E: MethodBind1R<Error, String const&>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:961)
   by 0x36AD2B0: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:940)
   by 0x3749D3A: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1073)
   by 0x14ABE87: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1080)
   by 0x1456E93: GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (gdscript.cpp:1192)
```
```
Invalid read of size 1
   at 0x366CFBD: Image::blit_rect(Ref<Image> const&, Rect2 const&, Vector2 const&) (image.cpp:2116)
   by 0x366C9BA: Image::get_rect(Rect2 const&) const (image.cpp:2068)
   by 0x3696582: MethodBind1RC<Ref<Image>, Rect2 const&>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:1333)
   by 0x36AD2B0: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:940)
   by 0x3749D3A: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1073)
   by 0x14ABE87: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1080)
   by 0x1456E93: GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (gdscript.cpp:1192)
   by 0x28E4680: Node::_notification(int) (node.cpp:60)
   by 0x141B4C9: Node::_notificationv(int, bool) (node.h:46)
   by 0x141BB10: CanvasItem::_notificationv(int, bool) (canvas_item.h:166)
   by 0x2D3652A: Node2D::_notificationv(int, bool) (node_2d.h:38)
   by 0x36AD429: Object::notification(int, bool) (object.cpp:950)
 Address 0xf7d5914 is 0 bytes after a block of size 20 alloc'd
   at 0x58CA74F: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x37E8F87: Memory::alloc_static(unsigned long, bool) (memory.cpp:85)
   by 0x13F45BC: PoolVector<unsigned char>::resize(int) (pool_vector.h:577)
   by 0x366A769: Image::create(int, int, bool, Image::Format) (image.cpp:1598)
   by 0x368F10C: Image::_create_empty(int, int, bool, Image::Format) (image.h:155)
   by 0x3699E8D: MethodBind4<int, int, bool, Image::Format>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:3115)
   by 0x36AD2B0: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:940)
   by 0x3749D3A: Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (variant_call.cpp:1073)
   by 0x14ABEB9: GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (gdscript_function.cpp:1083)
   by 0x1456E93: GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (gdscript.cpp:1192)
   by 0x28E4680: Node::_notification(int) (node.cpp:60)
   by 0x141B4C9: Node::_notificationv(int, bool) (node.h:46)
```
**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit 8a6855549827c753269fd89e15b7f6270bd7a66f
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/8a6855549827c753269fd89e15b7f6270bd7a66f.zip

### PR DESCRIPTION
**Pull request by timothyqiu**
This fixes #29953

The invalid writes are caused by:
* modifying the image after `lock()` invalidates the `write_lock`'s pointer
* accessing pixel data without checking for compressed image format

### CODE REVIEW

File: core/image.cpp [hunk 1]
```diff
@@ -880,8 +882,8 @@ void Image::resize_to_po2(bool p_square) {
 void Image::resize(int p_width, int p_height, Interpolation p_interpolation) {
 
 	ERR_FAIL_COND_MSG(data.size() == 0, "Cannot resize image before creating it, use create() or create_from_data() first.");
-
 	ERR_FAIL_COND_MSG(!_can_modify(format), "Cannot resize in compressed or custom image formats.");
+	ERR_FAIL_COND_MSG(write_lock.ptr(), "Image must not be locked during resize.");
```
Comment (clayjohn) [inline core/image.cpp]: I prefer language more like what you have below. I.e. "image cannot be resized when it is locked"

Same goes for the above comment. 

The current language creates confusion because locked is both a state and an action. So it is ambiguous whether you are telling the user not to lock the image when a resize is occuring, or whether you are telling the user that a locked image cannot be resized.

Comment (timothyqiu) [reply core/image.cpp]: Updated. I changed it to "Cannot resize image when it is locked" to match the above error message "Cannot resize image before creating it".

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
