### PR TITLE
Mobile: Uncomment code required for fog rendering on clear color

### LINKED ISSUE #74187: Vulkan mobile: fog does not affect plain color skies even at fog_affect_sky = 1.
### Godot version

4.0 Stable

### System information

Ubuntu 22.04

### Issue description

Setting fog_affect_sky = 1 do not have the desired effect when using a Color sky mode. It works properly if we use a procedural sky or the forward+ renderer.

Screenshot from 2023-03-03 16-50-53

### Steps to reproduce

Add a sky with a plain color mode like the Clear Color default option. Enable fog and set fog_affect_sky value to 1. Sky is still not affected by fog. 

### Minimal reproduction project
[mobile_fog_sky_bug.zip](https://github.com/godotengine/godot/files/10887265/mobile_fog_sky_bug.zip)

### PR DESCRIPTION
**Pull request by LRFLEW**
This should fix #74187. I noticed these lines of code were commented out while looking into an unrelated issue. The equivalent lines of code are not commented out in the Forward+ (forward clustered) renderer, so I assume it's an error here,

I'm not entirely sure *why* the code here was commented out originally, only that it was commented out when the Mobile renderer was first added with #47059. Perhaps there was some issue this was working around? I wasn't able to identify any issues with uncommenting it now, so I assume there's no problem with this PR. I would like to know *why* it was commented out originally if anybody still remembers, so I can be certain there are no issues with uncommenting it now.

### CODE REVIEW

File: servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp [hunk 1]
```diff
@@ -805,24 +805,20 @@ void RenderForwardMobile::_render_scene(RenderDataRD *p_render_data, const Color
...
 				}
-				*/
 			} break;
 			case RS::ENV_BG_COLOR: {
 				clear_color = environment_get_bg_color(p_render_data->environment);
 				clear_color.r *= bg_energy_multiplier;
 				clear_color.g *= bg_energy_multiplier;
 				clear_color.b *= bg_energy_multiplier;
-				/*
 				if (p_render_data->render_buffers->has_custom_data(RB_SCOPE_FOG) || environment_get_fog_enabled(p_render_data->environment)) {
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp:818]:
```suggestion
				if (environment_get_fog_enabled(p_render_data->environment)) {
```

**Comment by LRFLEW** [comment]
I implemented the suggestions as an amended commit to avoid cluttering the git history. That does make sense as a change, so thanks for the suggestion. I'm still not entirely aware of what's not available between the different renderers, so it wasn't something I would have caught on my own.

**Review by clayjohn — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.3.
