### PR TITLE
Fix tangent baking for curves when cubic derivatives are 0

### LINKED ISSUE #82658: [BUG] sample_baked_with_rotation return wrong rotation when offset=0
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - integrated AMD Radeon(TM) Vega 8 Graphics  () - AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

image

As shown in the picture above, when the curve offset is 0, the rotation angle seems to be incorrect. I just get the rotation of the offset (contained in the transform) and then copy the sprite2d to this position.
The other offset are correct, And I've also looked at existing questions and there doesn't seem to be the exact same problem as mine.

code as below.
image

Thanks for any help.

### Steps to reproduce

1, create a Node Path2D
2, invoke path2d's curve with sample_baked_with_rotation(0) # only offset=0 seemd not correct
3, display path in debug and run

### Minimal reproduction project

[Curve2DSampleTest.zip](https://github.com/godotengine/godot/files/12779488/Curve2DSampleTest.zip)

### LINKED ISSUE #100590: `sample_baked_with_rotation` in Curve3D gives wrong rotation near first and last points
#### Reproducible in
 - 4.4.dev.custom_build.fafc07335
 - 4.3.stable.official.77dcf97d8
 - 4.2.2.stable.official.15073afe3
 
### System information

Godot v4.3.stable - Ubuntu 22.04.5 LTS 22.04 - X11 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3080 (nvidia; 550.120) - Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 Threads)

### Issue description

Curve3D's `sample_baked_with_rotation` returns strange rotation values near the first point and the last point of a curve. 

### Steps to reproduce

1. Construct a Curve3D with at least 3 points.
2. Give the middle point a non-zero in and out vector. 
3. Sample the curve with rotation using `sample_baked_with_rotation` at regular intervals to see that the rotation value veers off in a weird direction as the first and the final points are approached. 

### Minimal reproduction project (MRP)

[mrp_curve3d-edge-rotation.zip](https://github.com/user-attachments/files/18191202/mrp_curve3d-edge-rotation.zip)

The attached MRP is a 3D scene with a Camera3D, a Path3D, and a MeshInstance3D. The Path3D has a script attached to it that draws basis provided by `sample_baked_with_rotation` along the entire length of the Path3D. This is not a tool script, so the project must be ran to see the basis drawn. The Path3D script has some exported parameters to help the user investigate this issue: `count` is the number of samples of the curve taken and drawn in the 3D viewport as basis gizmos, `size` is the length of the vector that represents a basis in a gizmo, and `cubic` changes whether `sample_baked_with_rotation` is called with `cubic = true` or `cubic = false` (the issue behavior does not appear to change based on this). 

#### Examples from MRP
The following is the 3D scene with only 50 samples taken so the basis gizmo can be more easily seen.
Image

As the number of samples increases so does the number of problematic rotation samples near the first and last points.
Image

When the middle point has zero in and out vectors, there are only straight lines and this issue does not occur. 
Image

### PR DESCRIPTION
**Pull request by Teschnique**
This attempts to fix the [issue](https://github.com/godotengine/godot/issues/100590) where the path-follower does not smoothly follow the curve due to the tangent being computed incorrectly when there are collinear control points.

The problem can be most easily understood with the scenario where one of the control points is collinear with the anchor points and the other is not.  In this case the control points form a quadratic bezier curve but is treated as a linear curve.

For example given `begin`, `c1`, `c2`, `end` if `begin` and `c1` are the same but `c2` and `end` are distinct from the other points the current code will return `end` - `begin` when it should return `c2` - `begin` (when `t` is 0).

* *Bugsquad edit, fixes: https://github.com/godotengine/godot/issues/100590*
* Fixes #82658

### CODE REVIEW

File: tests/scene/test_path_follow_3d.h [hunk 1]
```diff
@@ -283,4 +283,57 @@ TEST_CASE("[SceneTree][PathFollow3D] Calculate forward vector") {
 
 	memdelete(path);
 }
+
+TEST_CASE("[SceneTree][PathFollow3D] Calculate forward vector with degenerate curves") {
+	Ref<Curve3D> curve = memnew(Curve3D);
+
+	// Form a circle using 2 cubic and 2 quadratic curves
```
Comment (kleonc) [inline tests/scene/test_path_follow_3d.h:290]: All 4 sub-curves are cubic (besides not really a circle).
```suggestion
```

If anything, I'd explain what's degenerate about this curve (equal control points).

File: tests/scene/test_path_follow_3d.h [hunk 2]
```diff
@@ -283,4 +283,57 @@ TEST_CASE("[SceneTree][PathFollow3D] Calculate forward vector") {
...
+	path->add_child(path_follow_3d);
+	SceneTree::get_singleton()->get_root()->add_child(path);
+
+	path_follow_3d->set_loop(false);
+	path_follow_3d->set_rotation_mode(PathFollow3D::RotationMode::ROTATION_ORIENTED);
+
+	path_follow_3d->set_progress_ratio(0.00);
+	CHECK(is_equal_approx(Vector3(-1, 0, 0), path_follow_3d->get_transform().get_basis().get_column(2)));
+
+	// Quadratic curve segment end-point
```
Comment (kleonc) [inline tests/scene/test_path_follow_3d.h:310]: Not quadratic.
```suggestion
```

File: tests/scene/test_path_follow_3d.h [hunk 3]
```diff
@@ -283,4 +283,57 @@ TEST_CASE("[SceneTree][PathFollow3D] Calculate forward vector") {
...
+	path_follow_3d->set_progress_ratio(0.25);
+	CHECK(is_equal_approx(Vector3(0, 0, 1), path_follow_3d->get_transform().get_basis().get_column(2)));
+
+	path_follow_3d->set_progress_ratio(0.50);
+	CHECK(is_equal_approx(Vector3(1, 0, 0), path_follow_3d->get_transform().get_basis().get_column(2)));
+
+	// Quadratic curve segment end-point
```
Comment (kleonc) [inline tests/scene/test_path_follow_3d.h:317]:
```suggestion
```

**Review by kleonc — APPROVED** [review]
> The problem can be most easily understood with the scenario where one of the control points is collinear with the anchor points and the other is not. In this case the control points form a quadratic bezier curve but is treated as a linear curve.

[`(A, B, C, D)` cubic bezier curve is quadratic only if `D - A == 3(C - B)`.](https://math.stackexchange.com/a/2759963)
Meaning your example curve (_"one of the control points is collinear with the anchor points and the other is not"_) can't be quadratic, it's still cubic (if 3 of the points would be collinear and the curve would be quadratic, the above would imply that all 4 points must be collinear).

E.g. the curve from the added test:
```
A = (0, 0, 1)
B = (1, 0, 1)
C = (1, 0, 0)
D = (1, 0, 0)
```
has equation `P(t) = (1, 0, 2) * t^3 - (3, 0, 3) * t^2 + (3, 0, 0) * t + (0, 0, 1)`. It's cubic.

---

Nevertheless, the fix looks good to me, thanks! :+1:

I'd just remove misleading comments from the added test.

**Comment by Teschnique** [comment]
You are right, I am using the wrong terminology here and while practically you end up with something that looks like it only has three control points the curve itself is not actually a quadratic curve I'll remove the comments.

File: tests/scene/test_path_follow_3d.h [hunk 4]
```diff
@@ -283,4 +283,54 @@ TEST_CASE("[SceneTree][PathFollow3D] Calculate forward vector") {
 
 	memdelete(path);
 }
+
+TEST_CASE("[SceneTree][PathFollow3D] Calculate forward vector with degenerate curves") {
+	Ref<Curve3D> curve = memnew(Curve3D);
+
+
+	curve->add_point(Vector3(0, 0, 1), Vector3(), Vector3(1, 0, 0));
```
Comment (akien-mga) [inline tests/scene/test_path_follow_3d.h:291]: Two consecutive empty lines fails the style checks:
```suggestion
	Ref<Curve3D> curve = memnew(Curve3D);

	curve->add_point(Vector3(0, 0, 1), Vector3(), Vector3(1, 0, 0));
```

**Comment by akien-mga** [comment]
Looks good! After fixing the style issue, could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

File: tests/scene/test_path_follow_3d.h [hunk 5]
```diff
@@ -283,4 +283,58 @@ TEST_CASE("[SceneTree][PathFollow3D] Calculate forward vector") {
 
 	memdelete(path);
 }
+
+TEST_CASE("[SceneTree][PathFollow3D] Calculate forward vector with degenerate curves") {
+	const real_t dist_cube_100 = 100 * Math::sqrt(3.0);
+	Ref<Curve3D> curve = memnew(Curve3D);
```
[the remark this answers is not in the document]
Comment (Teschnique) [reply tests/scene/test_path_follow_3d.h]: Okay, I was following the other tests in this file, so I modified all instances of `Ref<Curve3D> curve = memnew(Curve3D);` to fit the style suggestion.

**Review by Calinou — APPROVED** [review]
Code looks good to me.

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
