### PR TITLE
AnimationMixer: Fix non-numeric misc type (`Resource`, `Dictionary` & etc.) values cannot be blended with `UpdateMode.UPDATE_CONTINUOUS`

### LINKED ISSUE #82905: 4.2 dev6 node AnimationPlayer Play Not effective
### Godot version

4.2 dev 6 mono

### System information

win11 22H2

### Issue description

4.2 dev6 node AnimationPlayer Play Not effective but 4.2 dev5 is normal

### Steps to reproduce

    public override void _PhysicsProcess(double delta)
    {
        ChangeAnimation();
    }

    private void ChangeAnimation()
    {
        var anim = Velocity.X switch
        {
            < 0 => "left",
            > 0 => "right",
            _ => "down"
        };

        if (Velocity.Y < 0) anim = "up";

        animation_play?.Play("walk-" + anim);
    }

### Minimal reproduction project

    public override void _Ready()
    {
        animation_play = GetNode<AnimationPlayer>("AnimationPlayer");
    }

### LINKED ISSUE #82949: Texture keyframe ignored in continous update mode
### Godot version

4.2.dev6, master[6916349]

### System information

Arch Linux

### Issue description

Texture keyframe seems ignored when the track's update mode is set to Continous.

* This happens regardless how many keyframes are on that track.
* This does not happen in 4.2.dev5.

CC @TokageItLab 

### Steps to reproduce

Use the MRP, or create two animations by

1. Create a keyframe for Texture of Sprite2D node.
2. Change the update mode of the newly created track to Continous.

Switching between different animations in the Animation editor:

* Expected: Behaves the same as using Discrete mode.
* Actual: Texture not updated after switching animation. The keyframe is ignored.

### Minimal reproduction project

[test-4.zip](https://github.com/godotengine/godot/files/12837117/test-4.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
Closes #82949
Closes #82905

If you try to use `UpdateMode.UPDATE_CONTINUOUS` with a non-numeric Misc Type value, it will fail to apply the value because there is currently no way to blend using `UpdateMode.UPDATE_CONTINUOUS`.

I believe that in the future we should convert them to have weight as `Pair<Variant value, float weight>` in the similar way that `bool` values are converted to `0` or `1` and blended, but for now it will force `UpdateMode.UPDATE_DISCRETE` instead of `UpdateMode.UPDATE_CONTINUOUS` since it is useless now.

### CODE REVIEW

File: scene/animation/animation_mixer.cpp [hunk 1]
```diff
@@ -868,6 +868,27 @@ bool AnimationMixer::_update_caches() {
...
+					case Variant::NIL:
+					case Variant::STRING_NAME:
+					case Variant::NODE_PATH:
+					case Variant::RID:
+					case Variant::OBJECT:
+					case Variant::CALLABLE:
+					case Variant::SIGNAL:
+					case Variant::DICTIONARY:
+					case Variant::ARRAY: {
+						WARN_PRINT_ONCE_ED("AnimationMixer: '" + String(E) + "', Value Track:  '" + String(path) + "' use misc type as key value with UpdateMode.UPDATE_CONTINUOUS. Currently this will not be blended correctly, so it is forced UpdateMode.UPDATE_DISCRETE.");
```
Comment (akien-mga) [inline scene/animation/animation_mixer.cpp:884]:
```suggestion
						WARN_PRINT_ONCE_ED("AnimationMixer: '" + String(E) + "', Value Track: '" + String(path) + "' uses a non-numeric type as key value with UpdateMode.UPDATE_CONTINUOUS. This will not be blended correctly, so it is forced to UpdateMode.UPDATE_DISCRETE.");
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
