### PR TITLE
Fix TextEdit breakpoint hover not hiding on mouse exit

### LINKED ISSUE #65517: The breakpoint hover indicator doesn't overlap with its click detection
### Godot version

4.0.alpha16

### System information

Ubuntu 20.04.3 LTS

### Issue description

1. One pixel to the right of a breakpoint, the cursor becomes an arrow, but a breakpoint can still be added.

image

2. ~This creates a breakpoint on the top line, even though the indicator is on the bottom line:~

image

3. The indicator lags behind sometimes when the mouse exits the CodeEdit, or stays forever if the caret is not blinking.

4. ~Creating a breakpoint is possible if you go below the last line or above the first line, but the hover indicator doesn't reflect it.~

5. ~The hover indicator also activates when the mouse is outside of the main window on partially hidden lines:~

image

6. ~It doesn't work with word wrap.~

### Steps to reproduce

Place your mouse exactly like in the photos

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by kitbdev**
- Fixes #65517

The area below the last line is no longer part of the last line's gutter.
The hovering, mouse cursor shape, and clicking gutter now uses the same logic.
Updating the gutter (add/remove/change size) now immediately updates the hover as well.
Added some gutter hover and click tests.

### CODE REVIEW

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -1675,6 +1675,10 @@ void TextEdit::_notification(int p_what) {
 				drag_caret_force_displayed = false;
 				queue_redraw();
 			}
+			if (hovered_gutter != Vector2i(-1, -1)) {
+				hovered_gutter = Vector2i(-1, -1);
+				queue_redraw();
+			}
```
Comment (MewPurPur) [inline scene/gui/text_edit.cpp:1681]: The hover update is why I added a `queue_redraw()` in CodeEdit's NOTIFICATION_MOUSE_EXIT, so that one shouldn't be needed anymore.

**Review by MewPurPur — APPROVED** [review]
Reviewed the code and tested the changes, it all looks good.

I see breakpoints left behind all the time now when using the code editor, so I think it would be a good idea to merge this during beta to clear up this jank for 4.4

**Comment by kitbdev** [comment]
Removed the CodeEdit mouse exit redraw, I don't think anything else was relying on it and I didn't notice any issues.

I don't think this can be cherry-picked. The breakpoint indicator did hide during 4.1 to 4.3 from https://github.com/godotengine/godot/pull/78509, it was just recently re-introduced in https://github.com/godotengine/godot/issues/65517.
This PR also relies on the changes #65517 made for the breakpoint hover, so without it this also may not fix the click logic and hover logic being different.

**Comment by syntaxerror247** [comment]
Removed cherrypick labels due to the reason mentioned by @kitbdev in above comment.

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected. I made sure this doesn't cause unnecessary redraws.

Code looks good to me.
