### PR TITLE
Propagate the keying state in the inspector

### LINKED ISSUE #70588: I can't move to Animation player when I open a AnimatedSprite
### Godot version

Godot 4-beta10

### System information

Linux, KDE Neon, OpenGL3, Mesa Intel(R) UHD Graphics (CML GT2)

### Issue description

I can't move to Animation player when I open a AnimatedSprite

See the video:
https://youtu.be/_nyN42rNlTw

### Steps to reproduce

- Open Scene GPlayer
- Select Idle (Animation player) node
- Select Body (Animation sprite) node
- Select animation in bottom tab

### Minimal reproduction project

You can test in my game is open source and don't have many files 👍🏻 

[the-zero-day.zip](https://github.com/godotengine/godot/files/10304677/the-zero-day.zip)

### PR DESCRIPTION
**Pull request by Rindbee**
Toggling the keying state does not significantly change the structure of the inspector. So it's ok to propagate the keying state and then use `queue_redraw()` to update the keying icon.

Fixes #70588.
Supersedes #70616.

### CODE REVIEW

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -3365,7 +3365,10 @@ void EditorInspector::set_keying(bool p_active) {
 		return;
 	}
 	keying = p_active;
-	update_tree();
+	// Propagate the keying state to its editor properties.
+	Array args;
+	args.append(keying);
+	main_vbox->propagate_call(SNAME("set_keying"), args, true);
```
Comment (KoBeWi) [inline editor/editor_inspector.cpp:3371]: I think you can do
```suggestion
	main_vbox->propagate_call(SNAME("set_keying"), { keying }, true);
```

Comment (Rindbee) [reply editor/editor_inspector.cpp:3371]: It doesn't seem to work, and an error is reported when compiling: `error: no matching constructor for initialization of 'const Array &'`.

Comment (KoBeWi) [reply editor/editor_inspector.cpp:3371]: Ah right, it's only possible with Vector.

File: editor/editor_properties.cpp [hunk 2]
```diff
@@ -4121,6 +4121,7 @@ void EditorPropertyResource::update_property() {
 
 				if (use_editor) {
 					// Open editor directly and hide other such editors which are currently open.
+					sub_inspector->set_keying(false);
```
Comment (TokageItLab) [inline editor/editor_properties.cpp:4124]: After all, this is just like SpecialCase in #70616, and for every additional implementation like `keying` in the EditorInspector, we need to add a line similar to this one. But it would work better than #70616.

It is preferred to add a comment as to why this line is needed in case someone later adds an implementation to the EditorInspector.

**Review by TokageItLab — APPROVED** [review]

File: editor/editor_properties.cpp (hunk 2 above)
Comment (Rindbee) [reply editor/editor_properties.cpp:4124]: At this time, the property tree of the sub inspector has not been fully established (`_update_tree()` will be called at the end of the frame), and `EditorInspector::set_keying()` is not registered in `ClassDB`, so `Node::propagate_call()` has no effect on it. The code here is not needed if the method is registered.

Here is judged by this condition: the opened editor is an editor for editing sub-resources, so it will not be the Animation editor.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
