### PR TITLE
Fix specific bug related to submenus in `PopupMenu`

### LINKED ISSUE #58126: Bizarre bug with PopupMenu submenus when popped up near the bottom of the screen
### Godot version

3.x 9bb6f9576d3ce09941c8ae18a033c15a3f98251f
Probably also happens in 4.0

### System information

Arch Linux

### Issue description

The specific setup in the linked MRP causes hovering over the item that opens the submenu to flicker the opening of the submenu for every time the mouse is moved, this seems to be caused by f63bea9ef281be2513b8653a4d2eabd77842a5c9 in fact moving the `pm->popup();` line under `pm->set_scale(get_global_transform().get_scale());` in `_activate_submenu` seems to fix the issue.

It only seems to happen on a setup specifically like the one in the linked MRP, where the submenu item is the first and it has 4 normal items following it, yeah I don't get it either but this is what it does.

### Steps to reproduce

Load the linked MRP and right click anywhere on the screen, hover the "Change type" item and observe how the menu flickers when moving over it, making it impossible to select any of the items.

### Minimal reproduction project

[PopupMenuBug.zip](https://github.com/godotengine/godot/files/8065186/PopupMenuBug.zip)

### PR DESCRIPTION
**Pull request by YeldhamDev**
Fixes #58126 (thanks @RodZill4 for the code snippet).

I tested the MRP with the `master` branch and the bug is not present there.

### CODE REVIEW

**Comment by RodZill4** [comment]
Thanks for fixing this, that bug made Material Maker unusable (and 3.5 has 32 bits viewports which is a game changer for textures generation).
The code on master is roughly the same as this PR (popup between keyboard handling and autohides setup).

**Review by Geometror — APPROVED** [review]

File: scene/gui/popup_menu.cpp [hunk 1]
```diff
@@ -174,7 +174,12 @@ void PopupMenu::_activate_submenu(int over) {
 		if (pum->get_item_count() > 0 && Input::get_singleton()->is_action_just_pressed("ui_accept")) {
 			pum->set_current_index(0);
 		}
+	}
+
+	// Must be in the middle, see GH-58126.
+	pm->popup();
 
+	if (pum) {
```
Comment (kleonc) [inline scene/gui/popup_menu.cpp:182]: I'd explain instead why setting up autohide areas must be done after `popup()`:
```suggestion
	pm->popup();

	// Setting autohide areas must be done after `popup()` which can move the popup (to fit it into the viewport).
	if (pum) {
```

Actually this made me wonder: does `pm->popup();` need to be in the middle? Can't it be before `pum->set_current_index(0);`?

Comment (YeldhamDev) [reply scene/gui/popup_menu.cpp]: Commented updated.

> Actually this made me wonder: does pm->popup(); need to be in the middle? Can't it be before `pum->set_current_index(0);`?

Yep, seems to work fine doing that also. I wonder why I changed the position before.

Comment (kleonc) [reply scene/gui/popup_menu.cpp]: >Yep, seems to work fine doing that also. I wonder why I changed the position before.

Also not sure what would be the reason, looks fine as is.
But in case of a regression let's remember to add a comment explaining the reason. :wink:

**Review by kleonc — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
