### PR TITLE
Fix uniform array alignment to fix a bug

### LINKED ISSUE #54657: Strange problems with Uniform Arrays
### Godot version

4.0.dev (d04681753)

### System information

Windows 10, Vulkan Clustered, INTEL R CPU 0000 / RTX 3060 Ti

### Issue description

In some cases, depending on the location of the uniform declaration, arrays may stop returning values.

For example:

```glsl
uniform int texture_count = 1;

uniform sampler2D diffuse[1];
uniform sampler2D roughness[1];

uniform sampler2D weights[1];

uniform sampler2D heightmap;
uniform sampler2D colormap;

uniform vec2 uv_scale[1];
uniform vec2 uv_offset[1];
uniform bool depth_blending[1];
uniform bool triplanar[1];
uniform bool tile_reduction[1];
```

In this case, regardless of what is in uv_scale, uv_scale[0] will always return vec2(0, 0). However, all sampler2D arrays work fine.

However, in this case, when the variables are arranged in a different order, everything works well:

```glsl
uniform vec2 uv_scale[1];
uniform vec2 uv_offset[1];
uniform bool depth_blending[1];
uniform bool triplanar[1];
uniform bool tile_reduction[1];

uniform int texture_count = 1;

uniform sampler2D diffuse[1];
uniform sampler2D roughness[1];

uniform sampler2D weights[1];

uniform sampler2D heightmap;
uniform sampler2D colormap;
```

### Steps to reproduce

I discovered this by accident while working on the Terrain system for Godot 4, so other than a test project, I do not know how to recreate it. With that, it took me sooo much time to figure out where the problem is at all.

In the test project there is a scene with two Planes, each with a material with different shaders specified above. Uniforms has the same values set from the editor, but in one case it does not affect Plane in any way, and in the other it does.

### Minimal reproduction project

[unform_array_bug_test.zip](https://github.com/godotengine/godot/files/7490210/unform_array_bug_test.zip)

### PR DESCRIPTION
**Pull request by Chaosus**
Fix #54657 + fixes the size checking for the arrays in `update_uniform_buffer` function

### CODE REVIEW

File: servers/rendering/renderer_rd/renderer_storage_rd.cpp [hunk 1]
```diff
@@ -2652,7 +2652,16 @@ void RendererStorageRD::MaterialData::update_uniform_buffer(const Map<StringName
 		//regular uniform
 		uint32_t offset = p_uniform_offsets[E.value.order];
 #ifdef DEBUG_ENABLED
-		uint32_t size = ShaderLanguage::get_type_size(E.value.type);
+		uint32_t size = 0U;
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/renderer_storage_rd.cpp:2655]:
```suggestion
		// The following code enforces 16 byte alignment of uniform arrays
		uint32_t size = 0U;
```

**Review by clayjohn — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
