### PR TITLE
Fix `emulate_mouse_from_touch` setting affecting editor

### LINKED ISSUE #96784: Disabling "emulate mouse from touch" in android editor makes it unusable upon restart
### Tested versions

Godot 4.3.0 stable [Android]

### System information

Android 13 (Xiaomi Poco F3) - Godot 4.3 stable

### Issue description

After disabling "emulate mouse from touch" in project settings and restarting the editor, it becomes impossible to use the editor with touch.

### Steps to reproduce

1. Disable "emulate mouse from touch" in project settings
2. Exit Godot editor and remove from recents
3. Re-open the editor and open your project

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by ohboh**
Fixes #96784, #84207
Make `emulate_mouse_from_touch` always true in the editor.

### CODE REVIEW

**Review by RandomShaper — APPROVED** [review]

**Review by akien-mga — COMMENTED** [review]
This looks fishy to me, the code on lines 3185 to 3190 does nothing as it's always overridden by line 3193. I think this requires a bit more research into why the code is this way and how to fix it.

Also, thanks for your first contribution and welcome :tada:

**Comment by ohboh** [comment]
> This looks fishy to me, the code on lines 3185 to 3190 does nothing as it's always overridden by line 3193. I think this requires a bit more research into why the code is this way and how to fix it.

I think 3185 to 3190 is for `set_emulate_touch_from_mouse` while 3193 is for `set_emulate_mouse_from_touch`.

File: main/main.cpp [hunk 1]
```diff
@@ -3191,6 +3191,10 @@ Error Main::setup2(bool p_show_boot_logo) {
 			}
 
 			id->set_emulate_mouse_from_touch(bool(GLOBAL_DEF_BASIC("input_devices/pointing/emulate_mouse_from_touch", true)));
+
+			if (editor) {
```
Comment (m4gr3d) [inline main/main.cpp:3195]: Should this also include the `project_manager`?

**Review by m4gr3d — APPROVED** [review]
Looks good to me!

Did you validate that the setting still apply to the running project in the Play window?

File: main/main.cpp (hunk 1 above)
Comment (ohboh) [reply main/main.cpp:3195]: Project manager seems to be unaffected by the setting but i can include it if necessary

**Comment by ohboh** [comment]
> Did you validate that the setting still apply to the running project in the Play window?

Yep, all seems to work fine for me

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first contribution!
