### PR TITLE
Fix mipmaps of VRAM compressed textures

### LINKED ISSUE #48261: Wrong mipmaps for VRAM compressed textures.
**Godot version:**

Latest master 7bca907

**OS/device including version:**

Linux

**Issue description:**

Looks like textures that are imported a "VRAM compressed" have incorrect mip map data, so they show artifacts when used in 3D meshes. Using any other compression mode seems to fix the issue, so it's most likely related.

Screenshot_20210428_103045
Same file, VRAM compressed on the left, lossless compression mode on the right.

**Steps to reproduce:**

* Import any texture as "VRAM compressed"
* Use it on a 3D mesh.
* Notice artifacts from mip maps.

**Minimal reproduction project:**

[vram-compressed-bug.tar.gz](https://github.com/godotengine/godot/files/6390381/vram-compressed-bug.tar.gz)

### PR DESCRIPTION
**Pull request by floppyhammer**
Fixes #48261.

### CODE REVIEW

File: core/io/image.cpp [hunk 1]
```diff
@@ -1428,16 +1428,23 @@ void Image::flip_x() {
...
+	// In this function, mipmap 0 represents the first mipmap instead of the original texture.
 	int mm = 0;
 
 	int pixsize = get_format_pixel_size(p_format);
 	int pixshift = get_format_pixel_rshift(p_format);
 	int block = get_format_block_size(p_format);
-	//technically, you can still compress up to 1 px no matter the format, so commenting this
+
+	// Technically, you can still compress up to 1 px no matter the format, so commenting this.
 	//int minw, minh;
```
Comment (fire) [inline core/io/image.cpp:1448]: If we don't use it, should we delete the comment?

Comment (floppyhammer) [reply core/io/image.cpp:1448]: The comment is not from me, so I'm not sure.

**Review by reduz — APPROVED** [review]
