### PR TITLE
Fix `draw_multiline_colors` usage

### LINKED ISSUE #76973: Marker2D does not draw
### Godot version

4.1 dev2

### System information

Windows 10 x64

### Issue description

Regression from #74883
```
 (2) servers/rendering/renderer_canvas_cull.cpp:1181 - Condition "p_colors.size() != 1 && p_colors.size() * 2 != p_points.size()" is true.
```
CC @dalexeev 

### Steps to reproduce

1. Add Marker2D

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by dalexeev**
In #74883, I fixed an inconsistency in `draw_multiline_colors()` for `width < 0`: if you passed the number of colors equal to **the number of lines**, then this did not work, unlike `width > 0`. But I did not pay attention to the fact that this worked when passing the number of colors equal to **the number of points**. The documentation says the following:

> Draws multiple disconnected lines with a uniform width and segment-by-segment coloring. Colors assigned to line segments match by index between points and colors. When drawing large amounts of lines, this is faster than using individual draw_line() calls. To draw interconnected lines, use draw_polyline_colors() instead.

Since this works for `width > 0` and `draw_multiline*` is analogous to `draw_line`, I suggest that the old behavior for `width < 0` is wrong, the number of colors should be equal to the number of lines (or 1), not the number of points.

Note that this is inconsistent with `draw_polyline*`, in these methods the colors correspond to points, not segments (and you can use gradients).

```
An idea

multiline:
  colors.size() == 1 -- One color
  colors.size() == points.size() -- Points
  colors.size() * 2 == points.size() -- Lines

polyline:
  colors.size() == 1 -- One color
  colors.size() == points.size() -- Points
  colors.size() == points.size() - 1 -- Segments
```

I had an idea to allow the number of colors to be equal to the number of points to avoid breaking compatibility, but it's hard to do for `width > 0` as there is a call to `canvas_item_add_line` in the loop in that case.

https://github.com/godotengine/godot/blob/fd4a06c51555904104b18494d0224f450d74fe2a/servers/rendering/renderer_canvas_cull.cpp#L1205-L1222

Closes #76973.

### CODE REVIEW

File: scene/2d/marker_2d.cpp [hunk 1]
```diff
@@ -55,19 +55,15 @@ void Marker2D::_draw_cross() {
...
 	draw_multiline_colors(points_x, colors_x);
 
 	const Color color_y = Color(0.53, 0.84, 0.01);
 	PackedColorArray colors_y = {
-		color_y,
 		color_y,
 		color_y.lerp(Color(0, 0, 0), 0.5),
-		color_y.lerp(Color(0, 0, 0), 0.5)
 	};
 	draw_multiline_colors(points_y, colors_y);
```
Comment (MewPurPur) [inline scene/2d/marker_2d.cpp:68]: On the topic of fixing up this code, `lerp(Color(0, 0, 0), 0.5)` can be `darkened(0.5)`. I also don't think we need two sets of points, two sets of colors, and two multiline draw calls.

**Review by clayjohn — APPROVED** [review]
Makes sense to me. When p_width < 0 the behaviour should match when p_width > 0

**Comment by kleonc** [comment]
> The documentation says the following:
> 
> > Draws multiple disconnected lines with a uniform width and segment-by-segment coloring. Colors assigned to line segments match by index between points and colors. When drawing large amounts of lines, this is faster than using individual draw_line() calls. To draw interconnected lines, use draw_polyline_colors() instead.
> 
> Since this works for `width > 0` and `draw_multiline*` is analogous to `draw_line`, I suggest that the old behavior for `width < 0` is wrong, the number of colors should be equal to the number of lines (or 1), not the number of points.

Then these docs should be fixed / clarified. E.g. by changing:

>Colors assigned to line segments match by index between points and colors.


to something like:

>Each segment is defined by two consecutive points from [param points] array and a corresponding color from [param colors] array, i.e. i-th segment consists of [code]points[2 * i][/code], [code]points[2 * i + 1][/code] endpoints and has [code]colors[i][/code] color.

(more or less, rewording welcomed)

---



> An idea
> 
> polyline:
>   colors.size() == points.size() - 1 -- Segments

Note this would require duplicating inner points so it would kinda end up being a multiline (a specific one, where each subsequent line starts at the end of the preceding one). In such case it might make more sense to draw it as actual multiline instead of a polyline with nearly half of its segments being zero-length. Anyway, seems of out scope of this PR. :upside_down_face:

File: editor/animation_track_editor_plugins.cpp [hunk 2]
```diff
@@ -919,8 +916,8 @@ void AnimationTrackEditTypeAudio::draw_key(int p_index, float p_pixels_sec, int
 	Rect2 rect = Rect2(from_x, (h - fh) / 2, to_x - from_x, fh);
 	draw_rect(rect, Color(0.25, 0.25, 0.25));
 
-	Vector<Vector2> lines;
-	lines.resize((to_x - from_x + 1) * 2);
+	Vector<Vector2> points;
+	points.resize((to_x - from_x + 1) * 2);
 	preview_len = preview->get_length();
 
 	for (int i = from_x; i < to_x; i++) {
```
Comment (kleonc) [inline editor/animation_track_editor_plugins.cpp:923]: As above.

**Review by kleonc — APPROVED** [review]
LGTM!

**Comment by akien-mga** [comment]
Thanks!
