### PR TITLE
Core: Allow methods of built-in `Variant` types to be used as Callables

### LINKED ISSUE #82251: GDScript: "Cannot find property emit on base Signal"
### Godot version

Godot v4.2.dev5 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### System information

Godot v4.2.dev5 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

```gdscript
extends Node

signal lmofa
signal yeet

func _ready():
    lmofa.connect(yeet.emit)
```

This results in a "Cannot find property emit on base Signal" error. This is either a bug or a weird error text.

### Steps to reproduce

Copy the script above.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by dalexeev**
* Closes #82251.
* Reverts #78274.

Makes the following code work:

```gdscript
var array: Array = [1, 2, 3]
print(array) # [1, 2, 3]
var callable: Callable = array.clear
callable.call()
print(array) # []
```

~~Note that signals can still only be connected to `Object`-based callables.~~ Fixed by #82695.

### CODE REVIEW

File: core/variant/variant_setget.cpp [hunk 1]
```diff
@@ -264,42 +266,46 @@ void Variant::set_named(const StringName &p_member, const Variant &p_value, bool
...
+				return obj->get(p_member, &r_valid);
+			}
+		} break;
+		case Variant::DICTIONARY: {
+			const Variant *v = VariantGetInternalPtr<Dictionary>::get_ptr(this)->getptr(p_member);
+			if (v) {
+				r_valid = true;
+				return *v;
+			}
+			[[fallthrough]];
```
Comment (dalexeev) [inline core/variant/variant_setget.cpp:297]: I don't think this is a good idea, it makes dictionary properties ambiguous (if there is `size` key, then its value is returned, otherwise `size` callable).

File: doc/classes/Object.xml [hunk 2]
```diff
@@ -564,6 +564,7 @@
 				}
 				[/csharp]
 				[/codeblocks]
+				[b]Note:[/b] [param callable] must be [Object]-based. Connecting a signal to a method of a built-in type such as [Array], [Callable], or [Signal] is not supported.
```
Comment (dalexeev) [inline doc/classes/Object.xml:567]: * See #82695.

**Comment by dalexeev** [comment]
It makes sense to change the argument type in the constructor from `Object` to `Variant`, but I think it's hard to do with the current system. The only thing we can do is declare constructors for all `Variant` types. It might make sense to add a constructor only for the `Dictionary`, since it does not support the callables method due to ambiguity with properties. Or add a static method, which is much easier to bind.

**Comment by akien-mga** [comment]
This is quite important IMO, as currently there is no proper type safe way to do `call_deferred` on built-in Variant type methods.

See https://github.com/godotengine/godot/issues/84046#issuecomment-1783453765 for context, where currently a lambda needs to be used instead of doing `some_signal.emit.call_deferred()` to emit a signal from a thread.

**Review by RandomShaper — APPROVED** [review]
No apparent issues to me. TIWAGOS, though.

**Comment by KoBeWi** [comment]
I found an issue with `free()` (#86706), which seems related to this PR, but it doesn't fix that bug.

> Note that signals can still only be connected to Object-based callables.

Does not work with `free()`.

**Comment by akien-mga** [comment]
Thanks!

**Comment by nlupugla** [comment]
Hi folks!

I ran into this commit while working on GDScript Structs https://github.com/godotengine/godot/pull/82198 and worried there might be an issue with this feature and built in Variants with dynamic properties, that is, Dictionaries and eventually Structs (which are just fancy arrays).

For example if I run
```gdscript
var dict: Dictionary = {&"clear" : "oops"}
var callable: Callable = dict.clear
```
The analyzer does not complain, but at runtime, I get "INTERNAL ERROR: Trying to assign value of type 'String' to a variable of type 'Callable'."

At the moment, my Struct branch is failing the unit test that was added for this feature:

```gdscript
var array: Array = [1, 2, 3]
print(array) # [1, 2, 3]
var callable: Callable = array.clear
callable.call()
print(array) # []
```

in the same way that the dictionary example I gave above fails as I have added named getters to arrays so that struct fields can be accessed like `my_struct.my_field`.

I'm not entirely sure what the best solution would be here, but one easy and temporary fix would be to change the test so that it tests using a method from a different Variant type as a callable, say, Vector2. For example,

```gdscript
var vec: Vector2 = Vector2(1.5, 2.5)
print(vec)
var callable: Callable = vec.ceil
print(callable.call())
```
