### PR TITLE
Directional 2 Split Shadow stabilization fix

### LINKED ISSUE #59232: Vulkan: DirectionalLight3D PSSM 2 Splits exhibits shadow acne not present in other modes, and shadows are unstable
### Godot version

4.0 Alpha 4

### System information

Windows 11, Vulkan, Nvidia GTX 1050 Ti, 511.23

### Issue description

2 Split mode has severe Shadow Acne issues, unrelated to Shadow Resolution (both Orthogonal and 4 Split don't have Any issues in the same example) and the Shadows are unstable with 2 Splits (they jitter as the camera moves) again, unlike the other modes.

### Steps to reproduce

Switch Between Orthogonal or 4 Split Mode and 2 Split mode and Observe the differences

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/8283451/Bug.zip)

### PR DESCRIPTION
**Pull request by mrjustaguy**
Fixes https://github.com/godotengine/godot/issues/59232

Before:

https://github.com/godotengine/godot/assets/50302479/c85de38a-230c-44ff-9483-199ec979d2b2

After:

https://github.com/godotengine/godot/assets/50302479/6783a58b-a02b-4bf2-9ac8-df170daa9bb2

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` 6916349697a4339216469e9bf5899b983d78db07), it works as expected. Shadows are now perfectly stable in motion with all rendering methods (Forward+, Mobile, Compatibility).

4-split PSSM and Orthogonal shadow modes still render correctly.

Note that this doesn't fix https://github.com/godotengine/godot/issues/54849.

### `master`

Orthogonal | PSSM 2 Splits[^1] | PSSM 4 Splits
-|-|-
Screenshot_20231007_191911 webp | Screenshot_20231007_191854 webp | Screenshot_20231007_191905 webp

### This PR

*There are very small differences in still scenes when using PSSM 2 Splits, which is expected.*

Orthogonal | PSSM 2 Splits[^1] | PSSM 4 Splits
-|-|-
Screenshot_20231007_190245 webp | Screenshot_20231007_190223 webp | Screenshot_20231007_190239 webp

[^1]: Split distance increased to 0.2 (instead of 0.1) to improve quality.

File: servers/rendering/renderer_scene_cull.cpp [hunk 1]
```diff
@@ -2239,7 +2239,7 @@ void RendererSceneCull::_light_instance_setup_directional_shadow(int p_shadow_in
 
 			// This trick here is what stabilizes the shadow (make potential jaggies to not move)
 			// at the cost of some wasted resolution. Still, the quality increase is very well worth it.
-			const real_t unit = (radius + soft_shadow_expand) * 2.0 / texture_size;
+			const real_t unit = (radius + soft_shadow_expand) * 4.0 / texture_size;
```
Comment (clayjohn) [inline servers/rendering/renderer_scene_cull.cpp:2242]: I'm a little skeptical about this change. Using a multiplier of 2 makes sense since we are both adding and subtracting ``radius + soft_shadow_expand``. 

I'd expect a visual difference as you are constricting the effective size of the shadowmap. Maybe this should only be change when using 2 splits?

Comment (mrjustaguy) [reply servers/rendering/renderer_scene_cull.cpp:2242]: there was no visual difference with 4 splits so seems fine to me... though don't ask me why lol

**Review by clayjohn — APPROVED** [review]
Testing locally I can't see any visual regressions (tested with both a high res and low res shadow maps at varying max distances and varying camera distances). 

I can confirm this fixes the stability of the 2 split variant. The fix makes sense as the 2 split variant uses a shadow map that is effectively twice as wide as the regular one.

It also makes sense that it wouldn't break the 4 split variant since 2 is a factor of 4

**Comment by akien-mga** [comment]
Thanks!
