### PR TITLE
Move Bullet physics query flush from Bullet space pre-tick callback to Bullet physics flush_queries()

### LINKED ISSUE #37702: 3d physics stepping is two frames late for bullet physics
**Godot version:**

3.2.1-stable

**OS/device including version:**

Mac

**Issue description:**

3d physics stepping is two frames late using bullet physics. Expected would be that it is one frame late.

**Steps to reproduce:**

Apply either velocity or force to a 3d rigid body. You will notice that the object moves two frames after you apply the velocity.

**Minimal reproduction project:**

Create a 3d scene and add rigid body with this script.

```
extends RigidBody

var frame = 0

func _ready():
	pass # Replace with function body.

func _physics_process(delta):
	match frame:
		10:
			linear_velocity = Vector3(1,0,0)
		12:
			linear_velocity = Vector3(0,0,0)

	force_update_transform()
	print("frame: " + str(frame) + " vel " + str(linear_velocity) +" " + str(transform.origin))

	frame += 1
```

The output is 

```
frame: 9 vel (0, 0, 0) (0, 0, 0)
frame: 10 vel (1, 0, 0) (0, 0, 0)
frame: 11 vel (1, 0, 0) (0, 0, 0)
frame: 12 vel (0, 0, 0) (0.1, 0, 0)
frame: 13 vel (0, 0, 0) (0.2, 0, 0)
frame: 14 vel (0, 0, 0) (0.2, 0, 0)
```

Expected would be that body has moved at frame 11.

** Note **

Using godot physics is the update is only one frame late. Hence bullet physics works differently.

Create equivalent script for 2d. You will notice that the body moves on frame 11. Hence, 2d physics works correctly.

### LINKED ISSUE #40110: Modifying RigidBody rotation every frame prevents it from moving
**Godot version:**
3.2.2

**OS/device including version:**
Linux Mint 20

**Issue description:**
Modifying a RigidBody's transform (or a child shape's transform) in any way will prevent it from moving that frame.

The Ball should fall, but it is stuck in place

**Steps to reproduce:**
Run the reproduction project
Test behaviour with different lines uncommented in `Ball.gd`

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/4872110/Test.zip)

### PR DESCRIPTION
**Pull request by madmiraal**
This is where it's done in Godot physics. It ensures that the queries are flushed before `_physics_process()` is called; so current values are available within `_physics_process()`.

Fixes #37702.
Fixes #40110.

### CODE REVIEW

**Comment by aaronfranke** [comment]
The issue says it's 2 frames late. Does this make physics 1 frame late or 0 frames late?

**Comment by madmiraal** [comment]
> The issue says it's 2 frames late. Does this make physics 1 frame late or 0 frames late?

It makes it one frame "late", which is expected, as per the issue description:

> 3d physics stepping is two frames late using bullet physics. Expected would be that it is one frame late.

Basically, the effect of any changes made during the current physics frame should be available in the next frame.

File: modules/bullet/space_bullet.cpp [hunk 1]
```diff
@@ -542,7 +542,6 @@ void SpaceBullet::remove_all_collision_objects() {
 }
 
 void onBulletPreTickCallback(btDynamicsWorld *p_dynamicsWorld, btScalar timeStep) {
-	static_cast<SpaceBullet *>(p_dynamicsWorld->getWorldUserInfo())->flush_queries();
```
Comment (akien-mga) [inline modules/bullet/space_bullet.cpp:545]: Should we de-register the callback if we don't use it anymore? @AndreaCatania

Comment (madmiraal) [reply modules/bullet/space_bullet.cpp:583]: Updated to also remove the pre-tick callback.

**Review by AndreaCatania — APPROVED** [review]
This looks good, thanks!

**Comment by akien-mga** [comment]
Thanks!
