### PR TITLE
Fix `Quaternion(arc_from: Vector3, arc_to: Vector3)` behaves differently in gdscript and c#

### LINKED ISSUE #107595: `Quaternion(arc_from: Vector3, arc_to: Vector3)` behaves differently in gdscript and c#
### Tested versions

Reproducible in 4.5dev5

### System information

Godot v4.5.dev5.mono - Windows 11 (build 26100) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 (NVIDIA; 32.0.15.6094) - 13th Gen Intel(R) Core(TM) i5-13500 (20 threads)

### Issue description

When using ```Quaternion(arc_from: Vector3, arc_to: Vector3)``` with Vector3.Up and Vector3.Down, gdscript produces a quaternion with (0, 0, -1, 0) and c# produces one with (0, 1, 0, 0) (which is wrong).

### Steps to reproduce

 - Use the ```Quaternion(arc_from: Vector3, arc_to: Vector3)``` constructor with Vector3.Up and Vector3.Down
 - Print the result
 - Repeat in the other language

### Minimal reproduction project (MRP)

[quat.zip](https://github.com/user-attachments/files/20759306/quat.zip)

### PR DESCRIPTION
**Pull request by dagarsar**
Fixes #107595

### CODE REVIEW

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs [hunk 1]
```diff
@@ -558,26 +558,39 @@ public Quaternion(Vector3 axis, real_t angle)
...
+                real_t s = Mathf.Sqrt((1f + d) * 2f);
+                real_t rs = 1f / s;
 
                 X = c.X * rs;
                 Y = c.Y * rs;
                 Z = c.Z * rs;
                 W = s * 0.5f;
             }
+            
+            Normalized();
```
Comment (AThousandShips) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs]:
```suggestion
            this = Normalized();
```
I believe, the method isn't mutating (and the equivalent method to GDScript doesn't exist)

Comment (dagarsar) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs]: You're right 😅 Somehow there was also whitespace on the line above so I'll fix that as well

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs [hunk 2]
```diff
@@ -558,26 +558,39 @@ public Quaternion(Vector3 axis, real_t angle)
...
         {
-            Vector3 c = arcFrom.Cross(arcTo);
-            real_t d = arcFrom.Dot(arcTo);
+            Vector3 n0 = arcFrom.Normalized();
+            Vector3 n1 = arcTo.Normalized();
 
-            if (d < -1.0f + Mathf.Epsilon)
+            real_t d = n0.Dot(n1);
+
+            if (Mathf.Abs(d) > 1.0f - Mathf.Epsilon)
```
Comment (aaronfranke) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs]: Please change the code to exactly match core, except for a language translation. Including `ALMOST_ONE`.

**Review by aaronfranke — CHANGES_REQUESTED** [review]

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs (hunk 2 above)
Comment (dagarsar) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs]: Should I also include the `#ifdef MATH_CHECKS` as a `#if DEBUG` section?

Comment (beicause) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs]: FYI, here is the changes I made:
(I think we should also change `Basis` to match the c++ code)

```diff
diff --git a/modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs b/modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs
index 10ca28a025dd..f0b0a5323a15 100644
--- a/modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs
+++ b/modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs
@@ -655,7 +655,8 @@ public static Basis LookingAt(Vector3 target, Vector3? up = null, bool useModelF
 #if DEBUG
             if (column0.IsZeroApprox())
             {
-                throw new ArgumentException("The target vector and up vector can't be parallel to each other.");
+                GD.PushWarning("Target and up vectors are colinear. This is not advised as it may cause unwanted rotation around local Z axis.");
+                column0 = up.Value.GetAnyPerpendicular(); // Vectors are almost parallel.
             }
 #endif
             column0.Normalize();
diff --git a/modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs b/modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs
index 09511ebdcaeb..ab046f9512a4 100644
--- a/modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs
+++ b/modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs
@@ -558,18 +558,32 @@ public Quaternion(Vector3 axis, real_t angle)
 
         public Quaternion(Vector3 arcFrom, Vector3 arcTo)
         {
-            Vector3 c = arcFrom.Cross(arcTo);
-            real_t d = arcFrom.Dot(arcTo);
-
-            if (d < -1.0f + Mathf.Epsilon)
+#if DEBUG
+            if (arcFrom.IsZeroApprox() || arcTo.IsZeroApprox()) throw new ArgumentException("The vectors must not be zero.");
+#endif
+#if REAL_T_IS_DOUBLE
+            const real_t ALMOST_ONE = 0.999999999999999;
+#else
+            const real_t ALMOST_ONE = 0.99999975f;
+#endif
+            Vector3 n0 = arcFrom.Normalized();
+            Vector3 n1 = arcTo.Normalized();
+            real_t d = n0.Dot(n1);
+            if (Mathf.Abs(d) > ALMOST_ONE)
             {
-                X = 0f;
-                Y = 1f;
-                Z = 0f;
-                W = 0f;
+                if (d >= 0)
+                {
+                    return; // Vectors are same.
+                }
+                Vector3 axis = n0.GetAnyPerpendicular();
+                X = axis.X;
+                Y = axis.Y;
+                Z = axis.Z;
+                W = 0;
             }
             else
             {
+                Vector3 c = n0.Cross(n1);
                 real_t s = Mathf.Sqrt((1.0f + d) * 2.0f);
                 real_t rs = 1.0f / s;
 
@@ -578,6 +592,7 @@ public Quaternion(Vector3 arcFrom, Vector3 arcTo)
                 Z = c.Z * rs;
                 W = s * 0.5f;
             }
+            this = Normalized();
         }
 
         /// <summary>
diff --git a/modules/mono/glue/GodotSharp/GodotSharp/Core/Vector3.cs b/modules/mono/glue/GodotSharp/GodotSharp/Core/Vector3.cs
index 9c403d2e2017..99d4253dc5f3 100644
--- a/modules/mono/glue/GodotSharp/GodotSharp/Core/Vector3.cs
+++ b/modules/mono/glue/GodotSharp/GodotSharp/Core/Vector3.cs
@@ -1283,5 +1283,18 @@ public readonly string ToString(string? format)
         {
             return $"({X.ToString(format, CultureInfo.InvariantCulture)}, {Y.ToString(format, CultureInfo.InvariantCulture)}, {Z.ToString(format, CultureInfo.InvariantCulture)})";
         }
+
+        internal readonly Vector3 GetAnyPerpendicular()
+        {
+            // Return the any perpendicular vector by cross product with the Vector3.RIGHT or Vector3.UP,
+            // whichever has the greater angle to the current vector with the sign of each element positive.
+            // The only essence is "to avoid being parallel to the current vector", and there is no mathematical basis for using Vector3.RIGHT and Vector3.UP,
+            // since it could be a different vector depending on the prior branching code Math::abs(x) <= Math::abs(y) && Math::abs(x) <= Math::abs(z).
+            // However, it would be reasonable to use any of the axes of the basis, as it is simpler to calculate.
+#if DEBUG
+            if (IsZeroApprox()) throw new ArgumentException("The Vector3 must not be zero.");
+#endif
+            return Cross((Mathf.Abs(X) <= Mathf.Abs(Y) && Mathf.Abs(X) <= Mathf.Abs(Z)) ? new Vector3(1, 0, 0) : new Vector3(0, 1, 0)).Normalized();
+        }
     }
 }
```

Comment (dagarsar) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs]: > FYI, here is the changes I made: (I think we should also change `Basis` to match the c++ code)

I'm sorry for the confusion, but should I simply apply these changes now?

Edit: I think in `Basis` the `#if DEBUG` clause should not be there

**Comment by dagarsar** [comment]
Went ahead and changed it into what @beicause posted, with the correction in `Basis`.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Vector3.cs [hunk 3]
```diff
@@ -1283,5 +1283,18 @@ public readonly string ToString(string? format)
...
+        internal readonly Vector3 GetAnyPerpendicular()
+        {
+            // Return the any perpendicular vector by cross product with the Vector3.RIGHT or Vector3.UP,
+            // whichever has the greater angle to the current vector with the sign of each element positive.
+            // The only essence is "to avoid being parallel to the current vector", and there is no mathematical basis for using Vector3.RIGHT and Vector3.UP,
+            // since it could be a different vector depending on the prior branching code Math::abs(x) <= Math::abs(y) && Math::abs(x) <= Math::abs(z).
+            // However, it would be reasonable to use any of the axes of the basis, as it is simpler to calculate.
+#if DEBUG
+            if (IsZeroApprox()) throw new ArgumentException("The Vector3 must not be zero.");
+#endif
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Vector3.cs]: This check doesn't happen only on debug builds in the C++ code:

https://github.com/godotengine/godot/blob/46c495ca21f40f57a7fb9c7cde6143738f1652d4/core/math/vector3.h#L336

The throw statement should also be in a new line.

```suggestion
            if (IsZeroApprox())
            {
                throw new ArgumentException("The Vector3 must not be zero.");
            }
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs [hunk 4]
```diff
@@ -652,12 +652,11 @@ public static Basis LookingAt(Vector3 target, Vector3? up = null, bool useModelF
                 column2 = -column2;
             }
             Vector3 column0 = up.Value.Cross(column2);
-#if DEBUG
             if (column0.IsZeroApprox())
             {
-                throw new ArgumentException("The target vector and up vector can't be parallel to each other.");
+                GD.PushWarning("Target and up vectors are colinear. This is not advised as it may cause unwanted rotation around local Z axis.");
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs]: If this is not advised, it should still throw an exception IMO.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs [hunk 5]
```diff
@@ -558,26 +558,41 @@ public Quaternion(Vector3 axis, real_t angle)
 
         public Quaternion(Vector3 arcFrom, Vector3 arcTo)
         {
-            Vector3 c = arcFrom.Cross(arcTo);
-            real_t d = arcFrom.Dot(arcTo);
-
-            if (d < -1.0f + Mathf.Epsilon)
+#if DEBUG
+            if (arcFrom.IsZeroApprox() || arcTo.IsZeroApprox()) throw new ArgumentException("The vectors must not be zero.");
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs]: To match our C# code-style.

```suggestion
            if (arcFrom.IsZeroApprox() || arcTo.IsZeroApprox())
            {
                throw new ArgumentException("The vectors must not be zero.");
            }
```

**Review by raulsntos — CHANGES_REQUESTED** [review]

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs (hunk 4 above)
Comment (dagarsar) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs]: In the c++ [code](https://github.com/godotengine/godot/blob/master/core/math/basis.cpp#L1044), it only sends a warning and continues execution. Should I get c# to mimic c++ or c++ to throw an error?

Comment (raulsntos) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs]: We don't use exceptions in C++. I don't know why it's a warning instead of an error in the C++ code, but since we've been throwing an exception in the C# code I would just keep it unchanged unless we have a good reason not to.

Comment (dagarsar) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs]: Changed it to throw an exception and have the same message as the c++ counterpart.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs [hunk 6]
```diff
@@ -558,26 +558,44 @@ public Quaternion(Vector3 axis, real_t angle)
...
-                Y = 1f;
-                Z = 0f;
-                W = 0f;
+                throw new ArgumentException("The vectors must not be zero.");
+            }
+#endif
+#if REAL_T_IS_DOUBLE
+            const real_t ALMOST_ONE = 0.999999999999999;
+#else
+            const real_t ALMOST_ONE = 0.99999975f;
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs]: To match our naming convention for constants in C#.

```suggestion
            const real_t AlmostOne = 0.999999999999999;
#else
            const real_t AlmostOne = 0.99999975f;
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs [hunk 7]
```diff
@@ -558,26 +558,44 @@ public Quaternion(Vector3 axis, real_t angle)
...
+#endif
+            Vector3 n0 = arcFrom.Normalized();
+            Vector3 n1 = arcTo.Normalized();
+            real_t d = n0.Dot(n1);
+            if (Mathf.Abs(d) > ALMOST_ONE)
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs]:
```suggestion
            if (Mathf.Abs(d) > AlmostOne)
```

**Review by raulsntos — APPROVED** [review]
Just a few naming nit-picks, otherwise looks good to me. The code matches the C++ implementation and seems to work as expected checking with the MRP.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs [hunk 8]
```diff
@@ -558,26 +558,44 @@ public Quaternion(Vector3 axis, real_t angle)
...
+                Z = axis.Z;
+                W = 0;
             }
             else
             {
-                real_t s = Mathf.Sqrt((1.0f + d) * 2.0f);
-                real_t rs = 1.0f / s;
+                Vector3 c = n0.Cross(n1);
+                real_t s = Mathf.Sqrt((1f + d) * 2f);
+                real_t rs = 1f / s;
```
Comment (aaronfranke) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs]: The existing code uses `1.0f`, and I prefer `1.0f`, so this shouldn't be changed unless there is agreement somewhere that `1f` is preferred.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs [hunk 9]
```diff
@@ -558,18 +558,35 @@ public Quaternion(Vector3 axis, real_t angle)
...
+            {
+                if (d >= 0)
+                {
+                    return; // Vectors are same.
+                }
+                Vector3 axis = n0.GetAnyPerpendicular();
+                X = axis.X;
+                Y = axis.Y;
+                Z = axis.Z;
+                W = 0;
```
Comment (aaronfranke) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs]: Further nitpicks.

```suggestion
                if (d >= 0.0f)
                {
                    return; // Vectors are same.
                }
                Vector3 axis = n0.GetAnyPerpendicular();
                X = axis.X;
                Y = axis.Y;
                Z = axis.Z;
                W = 0.0f;
```

**Review by aaronfranke — APPROVED** [review]

**Review by aaronfranke — APPROVED** [review]
I did not test but this looks good to me.

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉

**Comment by dagarsar** [comment]
Thanks for all the help!

(I had already made a contribution in #101066 but I think the commit author was a different account of mine and that's why it showed this as my first again)

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs [hunk 10]
```diff
@@ -558,18 +558,35 @@ public Quaternion(Vector3 axis, real_t angle)
...
+            const real_t AlmostOne = 0.99999975f;
+#endif
+            Vector3 n0 = arcFrom.Normalized();
+            Vector3 n1 = arcTo.Normalized();
+            real_t d = n0.Dot(n1);
+            if (Mathf.Abs(d) > AlmostOne)
+            {
+                if (d >= 0.0f)
+                {
+                    return; // Vectors are same.
```
Comment (aaronfranke) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs:579]: In the C++ code, the default values are initialized as `(0, 0, 0, 1)` for an unrotated Quaternion.

In C#, due to technical limitations, the default values are `(0, 0, 0, 0)`, so this code doesn't match the behavior of core. I believe this is the cause of this bug: https://github.com/godotengine/godot/issues/109261

We need to ensure X, Y, Z, and W are set in all code paths, so we should add this before the return.

Comment (dagarsar) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs:579]: This escaped me, sorry... I see that the fix is already made by #109281, thanks!
