### PR TITLE
Fix audio track end and start offset editing

### LINKED ISSUE #68788: Audio Playback Track Offset broken
### Godot version

4.0 beta5

### System information

Windows 10

### Issue description

The Audio Playback Track in the Animation Player appears to be broken when using offsets. You can drag from the end of the track to add an End Offset, dragging from the start does not work at all. But when you add an End Offset, then selecting the track does not work anymore and it displays the error message:
`scene/resources/animation.cpp:3696 - Index p_key = -1 is out of bounds (at->values.size() = 1).`
No more changes to the track can be applied, until you reload the scene.

### Steps to reproduce

- Create an Animation Player and an AudioStreamPlayer. Add an animation and an AudioPlaybackTrack
- Drag an Audio File into the AudioPlaybackTrack
- Manipulate start end end of the track 

### Minimal reproduction project

[BrokenAudioAnimationPlayer.zip](https://github.com/godotengine/godot/files/10032057/BrokenAudioAnimationPlayer.zip)

### PR DESCRIPTION
**Pull request by RumblingTurtle**
Fixes #68788. Both start and end offset dragging is now possible with proper preview of the changes

### CODE REVIEW

File: editor/animation_track_editor_plugins.cpp [hunk 1]
```diff
@@ -1086,8 +1087,24 @@ void AnimationTrackEditTypeAudio::gui_input(const Ref<InputEvent> &p_event) {
...
+		if (len == 0) {
+			Ref<AudioStreamPreview> preview = AudioStreamPreviewGenerator::get_singleton()->generate_preview(stream);
+			float preview_len = preview->get_length();
+			len = preview_len;
+		}
+
+		if (len_resizing_start)
+			len_resizing_rel = CLAMP(ofs_local, -prev_ofs_start + 0.01, len - prev_ofs_end - prev_ofs_start - 0.01) * get_timeline()->get_zoom_scale();
+		else
+			len_resizing_rel = CLAMP(ofs_local, -(len - prev_ofs_end - prev_ofs_start) + 0.01, prev_ofs_end - 0.01) * get_timeline()->get_zoom_scale();
```
Comment (akien-mga) [inline editor/animation_track_editor_plugins.cpp:1106]: Our style guide requires brackets even for single-line `if`/`else` blocks.

Comment (RumblingTurtle) [reply editor/animation_track_editor_plugins.cpp]: https://github.com/godotengine/godot/pull/69302/commits/70abca3a9e2fc3a8926a1bfec5951b2e22d407fa

**Review by TokageItLab — APPROVED** [review]
I tested. LGTM!

**Comment by TokageItLab** [comment]
@RumblingTurtle Needs to squash. https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html

File: editor/animation_track_editor_plugins.cpp [hunk 2]
```diff
@@ -1106,15 +1128,30 @@ void AnimationTrackEditTypeAudio::gui_input(const Ref<InputEvent> &p_event) {
 
 	Ref<EditorUndoRedoManager> &undo_redo = EditorNode::get_undo_redo();
 	if (len_resizing && mb.is_valid() && !mb->is_pressed() && mb->get_button_index() == MouseButton::LEFT) {
-		float ofs_local = -len_resizing_rel / get_timeline()->get_zoom_scale();
+		if (len_resizing_rel == 0 || len_resizing_index < 0) {
+			len_resizing = false;
+			return;
+		}
+
 		if (len_resizing_start) {
```
Comment (TokageItLab) [inline editor/animation_track_editor_plugins.cpp:1136]:
```suggestion
		if (len_resizing_start) {
			float ofs_local = len_resizing_rel / get_timeline()->get_zoom_scale();
			float prev_ofs = get_animation()->audio_track_get_key_start_offset(get_track(), len_resizing_index);
			float prev_time = get_animation()->track_get_key_time(get_track(), len_resizing_index);
			float new_ofs = prev_ofs + ofs_local;
			float new_time = prev_time + ofs_local;
			if (prev_time != new_time) {
				undo_redo->create_action(TTR("Change Audio Track Clip Start Offset"));

				undo_redo->add_do_method(get_animation().ptr(), "track_set_key_time", get_track(), len_resizing_index, new_time);
				undo_redo->add_undo_method(get_animation().ptr(), "track_set_key_time", get_track(), len_resizing_index, prev_time);

				undo_redo->add_do_method(get_animation().ptr(), "audio_track_set_key_start_offset", get_track(), len_resizing_index, new_ofs);
				undo_redo->add_undo_method(get_animation().ptr(), "audio_track_set_key_start_offset", get_track(), len_resizing_index, prev_ofs);

				undo_redo->commit_action();
			}
		} else {
			float ofs_local = -len_resizing_rel / get_timeline()->get_zoom_scale();
			float prev_ofs = get_animation()->audio_track_get_key_end_offset(get_track(), len_resizing_index);
			float new_ofs = prev_ofs + ofs_local;
			if (prev_ofs != new_ofs) {
				undo_redo->create_action(TTR("Change Audio Track Clip End Offset"));
				undo_redo->add_do_method(get_animation().ptr(), "audio_track_set_key_end_offset", get_track(), len_resizing_index, new_ofs);
				undo_redo->add_undo_method(get_animation().ptr(), "audio_track_set_key_end_offset", get_track(), len_resizing_index, prev_ofs);
				undo_redo->commit_action();
			}
		}
```
The operation should be canceled.

File: editor/animation_track_editor_plugins.cpp [hunk 3]
```diff
@@ -1086,8 +1087,25 @@ void AnimationTrackEditTypeAudio::gui_input(const Ref<InputEvent> &p_event) {
...
+			Ref<AudioStreamPreview> preview = AudioStreamPreviewGenerator::get_singleton()->generate_preview(stream);
+			float preview_len = preview->get_length();
+			len = preview_len;
+		}
+
+		if (len_resizing_start) {
+			len_resizing_rel = CLAMP(ofs_local, -prev_ofs_start + 0.01, len - prev_ofs_end - prev_ofs_start - 0.01) * get_timeline()->get_zoom_scale();
+		} else {
+			len_resizing_rel = CLAMP(ofs_local, -(len - prev_ofs_end - prev_ofs_start) + 0.01, prev_ofs_end - 0.01) * get_timeline()->get_zoom_scale();
+		}
```
Comment (TokageItLab) [inline editor/animation_track_editor_plugins.cpp:1107]:
```suggestion
		if (len_resizing_start) {
			len_resizing_rel = CLAMP(ofs_local, -prev_ofs_start, len - prev_ofs_end - prev_ofs_start) * get_timeline()->get_zoom_scale();
		} else {
			len_resizing_rel = CLAMP(ofs_local, -(len - prev_ofs_end - prev_ofs_start), prev_ofs_end) * get_timeline()->get_zoom_scale();
		}
```
This shifting is unnecessary. It will not be possible to back to the original value.

**Review by TokageItLab — CHANGES_REQUESTED** [review]
I found that there are several processing problems that need to be fixed.

File: editor/animation_track_editor_plugins.cpp (hunk 2 above)
Comment (RumblingTurtle) [reply editor/animation_track_editor_plugins.cpp:1135]: Didn't really understand what are you suggesting here

File: editor/animation_track_editor_plugins.cpp (hunk 3 above)
Comment (RumblingTurtle) [reply editor/animation_track_editor_plugins.cpp]: I don't think that reverting to the original value wouldn't be an issue since it is cached right after you stop dragging the offset. I just wanted to make zero length offsets impossible but I guess that is not necessary.

File: editor/animation_track_editor_plugins.cpp (hunk 2 above)
Comment (TokageItLab) [reply editor/animation_track_editor_plugins.cpp:1135]: Due to github's suggestion formatting, this suggestion has been wrote here, but the old unnecessary lines below from that need to be deleted at your discretion.

**Review by TokageItLab — APPROVED** [review]
