### PR TITLE
Automatically set `text_editor/external/exec_flags` based on the editor specified in `exec_path` text box

### LINKED ISSUE #226: Add documentation for "External" editor settings with gdscript-only projects
I have been unable to find documentation for how to get Godot to play nice with rider on gdscript-only projects. Dotnet projects open fine because (i think) rider identifies the project folder by the solution file / csproj file.

However, when opening a `.gd` file in gdscript-only projects when rider isn't launched yet, it opens the script's containing folder instead.

The following command line arguments added to "Text Editor / External / Exec Flags" provide the desired behavior where Rider will open the Godot _project folder_, then navigate to the file and line number.

```
{project} {file} --line {line} 
```

So far I have only tested this with opening a file from Godot. I am unsure if it behaves correctly with debugging features

### LINKED ISSUE #10631: Automatically specify exec flags based on the selected external editor
### Describe the project you are working on

JetBrains Rider

### Describe the problem or limitation you are having in your project

As described in [Using an external text editor](https://docs.godotengine.org/en/stable/tutorials/editor/external_editor.html#using-an-external-text-editor) section, to configure an external editor, you need to specify the path to editor executable and the required flags suitable for the selected editor. From the UI it is not evident that you need a specific set of exec flags configured when you select an external editor executable, nor it is evident that each editor required a different set of flags. 

As a member of the JetBrains Rider support team, I regularly deal with support requests from Godot+Rider users regarding Rider not opening the project properly. Usually those requests are resolved by proper exec flags configuration. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Since flags for most popular external editors are already documented, it would be convenient to have the Godot Editor automatically set exec flags based on the path to the external editor specified by the user. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I was thinking that it might be worth adding an event that fires off when the **Exec Path** setting is edited. On this event, use a regex to parse the path and detect editor name and then set **Exec Flags** field value to have appropriate flags. If no known editor was detected, indicate it in the Settings window (e.g. using a tooltip) and set the field to a fallback value like `{file}`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I can't see any easy workaround, however I'd be happy to be proven wrong.

### Is there a reason why this should be core and not an add-on in the asset library?

It's core editor functionality.

### PR DESCRIPTION
**Pull request by ivanskorikov**
Whenever `exec_path` is changed, a signal is emitted. On this signal, a method is called that searches the contents of the `exec_path` field for a predefined pattern using a regex. Upon a valid match, a value for `text_editor/external/exec_flags` is selected and this property is modified.

Values for exec_flags are taken from the [Using an external text editor](https://docs.godotengine.org/en/stable/tutorials/editor/external_editor.html) doc

Closes https://github.com/godotengine/godot-proposals/issues/10631 and closes https://github.com/JetBrains/godot-support/issues/226

### CODE REVIEW

**Comment by ivanskorikov** [comment]
Squashed commits per Godot Git checklist

**Comment by van800** [comment]
@Calinou would you please review or help to find someone to review?

File: editor/editor_properties.cpp [hunk 1]
```diff
@@ -462,10 +462,50 @@ void EditorPropertyPath::_set_read_only(bool p_read_only) {
...
+		emit_signal("exec_path_changed", p_path);
+	}
 	update_property();
 }
 
+void EditorPropertyPath::_on_exec_path_changed(String new_path) {
+	Ref<RegEx> regex;
+	regex.instantiate();
+
+	const String editor_pattern = R"([\\/]((?:[jJ]et[Bb]rains\s*)?[rR]ider(?:\s*(EAP|\d{4}\.\d+|\d{4}\.\d+\s*[Dd]ev)?)?|[vV]isual\s*[sS]tudio\s*[cC]ode|[sS]ubl(ime\s*[tT]ext)?|sublime_text|(g)?vim|emacs|atom|geany|kate|code)(?:\.app|\.exe|\.bat|\.sh)?)";
```
Comment (Calinou) [inline editor/editor_properties.cpp:477]: There's a way to make the regex case-insensitive, so you don't need to check for both uppercase and lowercase:

- Use the case-insensitive regex flag.
- Make the source text lowercase before matching.

**Comment by Calinou** [comment]
@ivanskorikov Bump 🙂 Can you take a look at the review comments above? If you don't have time anymore, let us know and someone can salvage this PR.

**Comment by ivanskorikov** [comment]
@Calinou Apologies, got a bit swept up by daily work and business trips. Thanks for the feedback, I've added the suggested changes, namely simplified the regex to handle only lowercase matches and added support for VSCodium

**Comment by van800** [comment]
@Calinou would you please review?

**Comment by Calinou** [comment]
> @Calinou would you please review?

This fails to build when rebased on `master` on macOS:

```
editor/editor_properties.cpp:505:7: error: member access into incomplete type 'RegEx'
  505 |         regex->compile(editor_pattern);
      |              ^
./core/io/logger.h:40:7: note: forward declaration of 'RegEx'
   40 | class RegEx;
      |       ^
editor/editor_properties.cpp:506:6: error: use of undeclared identifier 'RegExMatch'
  506 |         Ref<RegExMatch> editor_match = regex->search(new_path.to_lower());
      |             ^
editor/editor_properties.cpp:506:38: error: member access into incomplete type 'RegEx'
  506 |         Ref<RegExMatch> editor_match = regex->search(new_path.to_lower());
      |                                             ^
./core/io/logger.h:40:7: note: forward declaration of 'RegEx'
   40 | class RegEx;
      |       ^
In file included from editor/editor_properties.cpp:31:
In file included from editor/editor_properties.h:34:
In file included from ./editor/editor_inspector.h:34:
In file included from ./editor/add_metadata_dialog.h:34:
In file included from ./editor/gui/editor_validation_panel.h:34:
In file included from ./scene/gui/panel_container.h:34:
In file included from ./scene/gui/container.h:34:
In file included from ./scene/gui/control.h:35:
In file included from ./core/object/gdvirtual.gen.inc:5:
In file included from ./core/object/script_instance.h:34:
./core/object/ref_counted.h:184:29: error: member access into incomplete type 'RegEx'
  184 |                 if (reference && reference->unreference()) {
      |                                           ^
./core/object/ref_counted.h:198:3: note: in instantiation of member function 'Ref<RegEx>::unref' requested here
  198 |                 unref();
      |                 ^
editor/editor_properties.cpp:501:13: note: in instantiation of member function 'Ref<RegEx>::~Ref' requested here
  501 |         Ref<RegEx> regex;
      |                    ^
./core/io/logger.h:40:7: note: forward declaration of 'RegEx'
   40 | class RegEx;
      |       ^
In file included from editor/editor_properties.cpp:31:
In file included from editor/editor_properties.h:34:
In file included from ./editor/editor_inspector.h:34:
In file included from ./editor/add_metadata_dialog.h:34:
In file included from ./editor/gui/editor_validation_panel.h:34:
In file included from ./scene/gui/panel_container.h:34:
In file included from ./scene/gui/container.h:34:
In file included from ./scene/gui/control.h:34:
In file included from ./core/math/transform_2d.h:34:
In file included from ./core/math/math_funcs.h:34:
In file included from ./core/error/error_macros.h:34:
In file included from ./core/object/object_id.h:34:
In file included from ./core/typedefs.h:46:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:254:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__utility/cmp.h:16:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/limits:819:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:510:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/is_trivially_destructible.h:26:38: error: incomplete type 'RegEx' used in type trait expression
   26 |     : public integral_constant<bool, __is_trivially_destructible(_Tp)> {};
      |                                      ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/is_trivially_destructible.h:42:53: note: in instantiation of template class 'std::is_trivially_destructible<RegEx>' requested here
   42 | inline constexpr bool is_trivially_destructible_v = is_trivially_destructible<_Tp>::value;
      |                                                     ^
./core/os/memory.h:139:22: note: in instantiation of variable template specialization 'std::is_trivially_destructible_v<RegEx>' requested here
  139 |         if constexpr (!std::is_trivially_destructible_v<T>) {
      |                             ^
./core/object/ref_counted.h:185:4: note: in instantiation of function template specialization 'memdelete<RegEx>' requested here
  185 |                         memdelete(reference);
      |                         ^
./core/object/ref_counted.h:198:3: note: in instantiation of member function 'Ref<RegEx>::unref' requested here
  198 |                 unref();
      |                 ^
editor/editor_properties.cpp:501:13: note: in instantiation of member function 'Ref<RegEx>::~Ref' requested here
  501 |         Ref<RegEx> regex;
      |                    ^
./core/io/logger.h:40:7: note: forward declaration of 'RegEx'
   40 | class RegEx;
      |       ^
In file included from editor/editor_properties.cpp:31:
In file included from editor/editor_properties.h:34:
In file included from ./editor/editor_inspector.h:34:
In file included from ./editor/add_metadata_dialog.h:34:
In file included from ./editor/gui/editor_validation_panel.h:34:
In file included from ./scene/gui/panel_container.h:34:
In file included from ./scene/gui/container.h:34:
In file included from ./scene/gui/control.h:34:
In file included from ./core/math/transform_2d.h:37:
In file included from ./core/templates/vector.h:43:
./core/os/memory.h:140:10: error: member access into incomplete type 'RegEx'
  140 |                 p_class->~T();
      |                        ^
./core/object/ref_counted.h:185:4: note: in instantiation of function template specialization 'memdelete<RegEx>' requested here
  185 |                         memdelete(reference);
      |                         ^
./core/object/ref_counted.h:198:3: note: in instantiation of member function 'Ref<RegEx>::unref' requested here
  198 |                 unref();
      |                 ^
editor/editor_properties.cpp:501:13: note: in instantiation of member function 'Ref<RegEx>::~Ref' requested here
  501 |         Ref<RegEx> regex;
      |                    ^
./core/io/logger.h:40:7: note: forward declaration of 'RegEx'
   40 | class RegEx;
      |       ^
In file included from editor/editor_properties.cpp:31:
In file included from editor/editor_properties.h:34:
In file included from ./editor/editor_inspector.h:34:
In file included from ./editor/add_metadata_dialog.h:34:
In file included from ./editor/gui/editor_validation_panel.h:34:
In file included from ./scene/gui/panel_container.h:34:
In file included from ./scene/gui/container.h:34:
In file included from ./scene/gui/control.h:35:
In file included from ./core/object/gdvirtual.gen.inc:5:
In file included from ./core/object/script_instance.h:34:
./core/object/ref_counted.h:192:14: error: allocation of incomplete type 'RegEx'
  192 |                 ref(memnew(T(p_params...)));
      |                            ^
./core/os/memory.h:125:53: note: expanded from macro 'memnew'
  125 | #define memnew(m_class) _post_initialize(::new ("") m_class)
      |                                                     ^~~~~~~
editor/editor_properties.cpp:502:8: note: in instantiation of function template specialization 'Ref<RegEx>::instantiate<>' requested here
  502 |         regex.instantiate();
      |               ^
./core/io/logger.h:40:7: note: forward declaration of 'RegEx'
   40 | class RegEx;
      |       ^
In file included from editor/editor_properties.cpp:31:
In file included from editor/editor_properties.h:34:
In file included from ./editor/editor_inspector.h:34:
In file included from ./editor/add_metadata_dialog.h:34:
In file included from ./editor/gui/editor_validation_panel.h:34:
In file included from ./scene/gui/panel_container.h:34:
In file included from ./scene/gui/container.h:34:
In file included from ./scene/gui/control.h:35:
In file included from ./core/object/gdvirtual.gen.inc:5:
In file included from ./core/object/script_instance.h:34:
./core/object/ref_counted.h:80:19: error: member access into incomplete type 'RegEx'
   80 |                                 if (!reference->reference()) {
      |                                               ^
./core/object/ref_counted.h:61:3: note: in instantiation of function template specialization 'Ref<RegEx>::ref_pointer<false>' requested here
   61 |                 ref_pointer<false>(p_from.reference);
      |                 ^
./core/object/ref_counted.h:192:3: note: in instantiation of member function 'Ref<RegEx>::ref' requested here
  192 |                 ref(memnew(T(p_params...)));
      |                 ^
editor/editor_properties.cpp:502:8: note: in instantiation of function template specialization 'Ref<RegEx>::instantiate<>' requested here
  502 |         regex.instantiate();
      |               ^
./core/io/logger.h:40:7: note: forward declaration of 'RegEx'
   40 | class RegEx;
      |       ^
8 errors generated.
scons: *** [editor/editor_properties.macos.editor.arm64.o] Error 1
scons: building terminated because of errors.
```

**Comment by van800** [comment]
What do I need to do to take this over from @ivanskorikov?
New pull request?

**Comment by Calinou** [comment]
> What do I need to do to take this over from @ivanskorikov? New pull request?

Yes, I suggest opening a new PR.

**Comment by van800** [comment]
We have solved it by adding me as a contributor.
Waiting for the workflow...

**Comment by van800** [comment]
@Calinou would you please review. Sorry for a lot of mentions today, I am desperate to have this merged at least to master.

**Comment by KoBeWi** [comment]
This shouldn't be implemented in EditorPropertyPath, but in EditorSettings.

File: editor/editor_properties.cpp [hunk 2]
```diff
@@ -496,6 +501,42 @@ String EditorPropertyPath::_get_path_text() {
 	return full_path;
 }
 
+void EditorPropertyPath::_on_exec_path_changed(String new_path) {
+	Ref<RegEx> regex;
+	regex.instantiate();
+
+	const String editor_pattern = R"([\\/]((?:jetbrains\s*)?rider(?:\s*(eap|\d{4}\.\d+|\d{4}\.\d+\s*dev)?)?|visual\s*studio\s*code|subl(ime\s*text)?|sublime_text|(g)?vim|emacs|atom|geany|kate|code|(vs)?codium)(?:\.app|\.exe|\.bat|\.sh)?)";
```
Comment (KoBeWi) [inline editor/editor_properties.cpp:508]: You can use `Regex::create_from_string()`

**Comment by van800** [comment]
> This shouldn't be implemented in EditorPropertyPath, but in EditorSettings.

moved

File: editor/editor_settings.cpp [hunk 3]
```diff
@@ -68,6 +69,9 @@ bool EditorSettings::_set(const StringName &p_name, const Variant &p_value) {
 	if (changed && initialized) {
 		changed_settings.insert(p_name);
 		emit_signal(SNAME("settings_changed"));
+		if (p_name == "text_editor/external/exec_path") {
+			_exec_path_changed(p_value);
```
Comment (KoBeWi) [inline editor/editor_settings.cpp:73]: This changes the path again, so it should happen before emitting the signal.

Comment (van800) [reply editor/editor_settings.cpp:73]: It is not changing the path, it should change the `exec_flags`.
Where would you suggest to place it?
image

Comment (KoBeWi) [reply editor/editor_settings.cpp:73]: Ah right. But it's still modifying a setting, so set it before the signal.

Comment (van800) [reply editor/editor_settings.cpp]: done, thank you for the pointer.

File: editor/editor_settings.cpp [hunk 4]
```diff
@@ -67,6 +68,13 @@ bool EditorSettings::_set(const StringName &p_name, const Variant &p_value) {
 	bool changed = _set_only(p_name, p_value);
 	if (changed && initialized) {
 		changed_settings.insert(p_name);
+		if (p_name == "text_editor/external/exec_path") {
```
Comment (KoBeWi) [inline editor/editor_settings.cpp:71]:
```suggestion
		if (p_name == SNAME("text_editor/external/exec_path")) {
```

**Review by KoBeWi — APPROVED** [review]

**Comment by KoBeWi** [comment]
Yes.
There is one comment you missed, but it's not blocking.

**Comment by van800** [comment]
@Calinou Can we please have this merged?

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉

File: editor/editor_settings.cpp [hunk 5]
```diff
@@ -1108,6 +1116,40 @@ void EditorSettings::_load_default_visual_shader_editor_theme() {
...
 
+String EditorSettings::_guess_exec_args_for_extenal_editor(const String &p_path) {
+	Ref<RegEx> regex;
+	regex.instantiate();
+
+	const String editor_pattern = R"([\\/]((?:jetbrains\s*)?rider(?:\s*(eap|\d{4}\.\d+|\d{4}\.\d+\s*dev)?)?|visual\s*studio\s*code|subl(ime\s*text)?|sublime_text|(g)?vim|emacs|atom|geany|kate|code|(vs)?codium)(?:\.app|\.exe|\.bat|\.sh)?)";
+	regex->compile(editor_pattern);
+	Ref<RegExMatch> editor_match = regex->search(p_path.to_lower());
+
+	if (editor_match.is_null()) {
```
Comment (DeeJayLSP) [inline editor/editor_settings.cpp:1127]: I placed a `printf("%s is not a valid editor.\n", p_path.to_lower().to_utf8_buffer().ptr());` before the return and got the following after trying to set `kate`, `code` and `subl`:

```
kate is not a valid editor.
code is not a valid editor.
subl is not a valid editor.
```
Did so because my editor wasn't autodetecting anything. Was this PR even tested before merging?

Comment (ghost) [reply editor/editor_settings.cpp:1127]: That is weird, I don't think that it was tested if you encountered this. Can you send your builds so I can test as well?

Comment (ghost) [reply editor/editor_settings.cpp:1127]: cc @van800 @ivanskorikov

Comment (DeeJayLSP) [reply editor/editor_settings.cpp:1127]: I copypasted the regex into some testing website, and it didn't work at all with the editor names.

This one did work, although not with paths: `R"((subl|sublime text|sublime_text|vim|gvim|emacs|atom|geany|code|visual studio code|codium|vscodium)(\.app|\.exe|\.bat|\.sh)?)"`

This should be possible without using regex.

Comment (ghost) [reply editor/editor_settings.cpp:1127]: Can you share the website & the code as well?

Comment (DeeJayLSP) [reply editor/editor_settings.cpp:1127]: I already got a possible fix, will open a PR in a while.

Comment (ghost) [reply editor/editor_settings.cpp:1127]: Alright, do ping me so I can look around.

Comment (DeeJayLSP) [reply editor/editor_settings.cpp:1127]: @AR-DEV-1 #111820
