### PR TITLE
Save the current script when pressing Ctrl + S if no scene is open

### LINKED ISSUE #9069: Saving scripts with the shortcut (CTRL+S) does not work with empty scene
**Operating system or device - Godot version:** 
Ubuntu Linux 16.04 - Godot 3.0 master branch (cloned 4 hours ago)

**Issue description:**

Trying to save scripts with the save shortcut (CTRL+S) does not work until an existing scene is 
opened or a valid scene with root node is saved.
Message: "This operation can't be done without a tree root"

**Steps to reproduce:**

Open an empty or existing project and close all open scenes. Open an empty or existing script in 
the script editor and press (CTRL+S).

### PR DESCRIPTION
**Pull request by Calinou**
- Tweak the dialog messages to be more informative.
  - The "Saved N modified resources" dialog is not a warning per se, so make it more explicit.

This closes https://github.com/godotengine/godot/issues/9069.

### CODE REVIEW

File: editor/plugins/script_editor_plugin.cpp [hunk 1]
```diff
@@ -2330,6 +2277,59 @@ bool ScriptEditor::edit(const RES &p_resource, int p_line, int p_col, bool p_gra
 	return true;
 }
 
+void ScriptEditor::save_current_script() {
```
Comment (Calinou) [inline editor/plugins/script_editor_plugin.cpp:2280]: I moved this method to be next to `save_all_scripts()`, since these are logically related and both methods are now public.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by EricEzaM** [comment]
Why still have a dialog in this case? It seems unnecessary and breaks the flow of writing code just to say 'yep, we saved your files'. Could this me made an output log message instead?

**Comment by Calinou** [comment]
> Why still have a dialog in this case? It seems unnecessary and breaks the flow of writing code just to say 'yep, we saved your files'. Could this me made an output log message instead?

It could be moved to an output log message, but the output log currently doesn't show a notification icon when it has new *non-warning/error* messages. Therefore, if the user currently has the output log collapsed, they won't notice the message.
