### PR TITLE
Revert "Core: Use `__fastfail()` in MSVC error macros"

### LINKED ISSUE #115490: Godot compiled with MSVC doesn't print the backtrace when a crash happens
### Tested versions

- Reproducible in 4.6 stable and latest master 77579f93e
- Not reproducible in 4.5 dev 3 and lower

### System information

Godot v4.7.dev (77579f93e) - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 580 2048SP (Advanced Micro Devices, Inc.; 31.0.21923.11000) - AMD Ryzen 5 3600 6-Core Processor (12 threads) - 31.91 GiB memory

### Issue description

After PR #105916 if you compile Godot with MSVC, no backtrace will be printed after a crash in the console. Doesn't affect the backtrace provided by the IDE if using one.

### Steps to reproduce

1. Compile Godot with MSVC
2. Force a crash to happen (like calling `OS.crash()`)
3. No backtrace will be printed in the console

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Repiteo**
This reverts commit b23a233b5b0d80d287f2eeca9c7f3ec26f2558a6, PR #105916.

Confirmed that this indeed fixes the issue. Turns out that an explicit abort doesn't necessarily guarantee a breakpoint. Notably, it only fixes the issue for MSVC if not using console-mode, but that was revealed to be an entirely separate bug that already existed prior to this change

- Fixes #115490

### CODE REVIEW

File: core/error/error_macros.h [hunk 1]
```diff
@@ -95,11 +91,11 @@ void _physics_interpolation_warning(const char *p_function, const char *p_file,
 #define FUNCTION_STR __FUNCTION__
 #endif
 
-#ifdef _MSC_VER
+#if defined(_MSC_VER) && !defined(__clang__)
```
Comment (Repiteo) [inline core/error/error_macros.h:94]: In addition to the revert, this extra `__clang__` check needed to be specified, as clang-cl expects `__fastfail()` to return. Granted, it's never actually labeled as `[[noreturn]]`, but MSVC's cl just treats it as such (at least moreso?) because Microsoft does whatever it wants

**Review by Ivorforce — APPROVED** [review]
