### PR TITLE
[Linux/BSD] Prefer `gimli-rs/addr2line` or `llvm-addr2line` over binutils.

### LINKED ISSUE #115508: `debug_symbols=yes` --> Backtrace takes too long (~a minute) (with 100% CPU used by `addr2line`)
### Tested versions

4.7.dev
4.4-stable
maybe even previous versions, but can't test due to compile errors

### System information

Godot v4.7.dev (77579f93e) - Arch Linux #1 SMP PREEMPT_DYNAMIC Sun, 18 Jan 2026 00:34:07 +0000 on Wayland - X11 display driver, Multi-window, 1 monitor - OpenGL 3 (Compatibility) - AMD Radeon 890M Graphics (radeonsi, gfx1150, LLVM 21.1.6, DRM 3.64, 6.18.6-arch1-1) - AMD Ryzen AI 9 HX 370 w/ Radeon 890M (24 threads) - 23.07 GiB memory

### Issue description

If I compile with `debug_symbols=yes`, when a crash occurs:
- Instead of successfully printing the backtrace, ~it hangs.~ (Edit: Apparently it just takes too long.)  (This happens after printing `Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
`)
- Meanwhile, a process named `addr2line` uses 100% CPU Edit: for a whole minute.

### Steps to reproduce

1. `scons platform=linuxbsd debug_symbols=yes`
2. Crash the engine (e.g. `OS.crash`)

### Minimal reproduction project (MRP)

Doesn't depend on a project. To force a crash, you may use `OS.crash("")` in a script.

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/115508

### CODE REVIEW

File: platform/linuxbsd/crash_handler_linuxbsd.cpp [hunk 1]
```diff
@@ -98,7 +98,30 @@ static void handle_crash(int sig) {
 	uintptr_t relocation = 0;
 #endif //__GLIBC__
 	if (strings) {
+		int ret;
+		String output = "";
```
Comment (AThousandShips) [inline platform/linuxbsd/crash_handler_linuxbsd.cpp]:
```suggestion
		String output;
```

**Review by AThousandShips — APPROVED** [review]
Tested and this works! Tested with both the cargo install one and llvm, both are much faster but the cargo one produces more detailed results

Some kind of note should probably be added to the docs when it has been merged to inform how to obtain it

File: platform/linuxbsd/crash_handler_linuxbsd.cpp [hunk 2]
```diff
@@ -103,7 +98,30 @@ static void handle_crash(int sig) {
...
 	if (strings) {
+		int ret;
+		String output;
+
 		List<String> args;
+		args.push_back("--version");
+		String exe_name;
+
+		if (exe_name.is_empty()) {
+			Error err = OS::get_singleton()->execute(OS::get_singleton()->get_environment("HOME").path_join(String("/.cargo/bin/addr2line")), args, &output, &ret);
```
Comment (akien-mga) [inline platform/linuxbsd/crash_handler_linuxbsd.cpp:115]:
```suggestion
			// Faster implementation from gimli-rs/addr2line.
			Error err = OS::get_singleton()->execute(OS::get_singleton()->get_environment("HOME").path_join(String("/.cargo/bin/addr2line")), args, &output, &ret);
```

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Comment by bruvzg** [comment]
Actually it's possible it simply needs `output = String();` added before final call. It's possible I have added `--version` after testing LLVM one and did not notice it is not cleaned.
