### PR TITLE
Fix SubViewport physics picking

### LINKED ISSUE #84258: Mouse input events not being detected from Area2D inside a SubViewport unless a key is pressed
### Godot version

v4.2.beta4.official [93cdacbb0]

### System information

Godot v4.2.beta4 - Windows 10.0.23570 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.5009) - AMD Ryzen 5 5500 (12 Threads)

### Issue description

Testing my 4.1.2 project with 4.2-beta 4 I noticed this behavior that might be related with the changes within subviewports and event handling. I'm not sure if any of the issues mentioned by #83276 is really similar to this so decided to open a new issue.

It seems that mouse events are not being sent to an Area2D that's a child from a sub view port, unless some other event is fired up into the main viewport before.

In the screen recording bellow, 'D' is a direct child from my root scene node while 'S' is inside a Subviewport

https://github.com/godotengine/godot/assets/8123916/3992481a-0890-44bb-990f-393786b369b2

This is the setup:

image

The mouse_entered and mouse_exited events are captured properly by the direct child scene "D" while the events only has effects in "S" if other event is fired before. Per exemple, start a click in "D" and drag until "S" or hold any keyboard key pressed and hover over "S", then the mouse_entered and mouse_exited work.

### Steps to reproduce

Using the given MRP:

1) Load the main scene
2) Hover over the tile "D", it should become green;
3) Exit mouse from the tile "D", it should be back to its original color;
4) Hover over the tile "S", it was supposed to become green, but it is not;
  4.1) Hold any keyboard key and hover the tile "S", it becomes green.

### Minimal reproduction project

[subviewport_mrp.zip](https://github.com/godotengine/godot/files/13219169/subviewport_mrp.zip)

### PR DESCRIPTION
**Pull request by Sauermann**
Apply the logic of `handle_input_locally` for physics picking.

resolve #84258
cherry-pick of #85665 from 4.2 to master.

I see this as an interim solution until #77926 gets reviewed.
I believe, that it is unlikely that #77926 gets reviews anytime soon, but since #84258 is quite nasty, I want to provide a bugfix-PR, that is easier to review and that already received some testing in 4.2.

### CODE REVIEW

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -738,6 +738,14 @@ void Viewport::_process_picking() {
 
 	while (physics_picking_events.size()) {
 		local_input_handled = false;
+		if (!handle_input_locally) {
+			Viewport *vp = this;
+			while (!Object::cast_to<Window>(vp) && vp->get_parent()) {
```
Comment (AThousandShips) [inline scene/main/viewport.cpp:743]: Assuming it's guaranteed this will always be non-null?

Comment (Sauermann) [reply scene/main/viewport.cpp:743]: Physics picking happens only when the viewport is inside the scene-tree:

https://github.com/godotengine/godot/blob/74c32faa78b54863f8f25c538083907c2bf71791/scene/main/viewport.cpp#L676-L679

So the returned viewport is also inside the scene-tree.

The same method is used in preexisting code:

https://github.com/godotengine/godot/blame/d76c1d0e516fedc535a2e394ab780cac79203477/scene/main/viewport.cpp#L3657-L3673

File: scene/main/viewport.cpp [hunk 2]
```diff
@@ -738,6 +738,14 @@ void Viewport::_process_picking() {
...
+				vp = vp->get_parent()->get_viewport();
+			}
+			vp->local_input_handled = false;
+		}
+
```
Comment (adamscott) [inline scene/main/viewport.cpp:748]: Just to be sure, you seem to skip every viewport (even ones with `local_input_handled == true` until the last one, then you set `local_input_handled` to `false`.
Is this what you want?

Comment (Sauermann) [reply scene/main/viewport.cpp:748]: This PR intends to treat `handle_input_locally` for physics picking in the same way as it is treated in other places. That includes skipping viewports with `local_input_handled == true`.
The fact that currently `handle_input_locally` is treated differently in different parts of the code-base is the reason for the linked issue.

**Review by akien-mga — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!
