### PR TITLE
Fix icons with non-ASCII file names in project manager.

### LINKED ISSUE #104363: Project Icon Not Updating in Editor (4.4 and 4.4-rc1)
### Tested versions

- Godot 4.4 stable and 4.4-rc1
- Downloaded from official website

### System information

Godot v4.4.1.rc1 - Windows 11 (build 26100) - Multi-window, 1 monitor - Vulkan (Forward+) - integrated AMD Radeon 780M Graphics (Advanced Micro Devices, Inc.; 32.0.12033.1030) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 threads)

### Issue description

The project icon in the Project Manager cannot be changed. When attempting to set a custom project icon through project settings, the icon remains as the default Godot icon regardless of the custom icon being properly set.

Image

Image

### Steps to reproduce

1. Open Project Manager
2. Create a new project or open existing project
3. Go to Project Settings
4. Navigate to Application > Config > Icon
5. Set a custom icon (supported format)
6. Save settings and restart the editor
7. Check Project Manager

**Expected behavior:**
The project should display the custom icon in the Project Manager.

**Actual behavior:**
The project continues to show the default Godot icon instead of the custom icon.

**Additional context:**
This issue appears to be consistent across both Godot 4.4 stable and 4.4-rc1 versions.

### Minimal reproduction project (MRP)

Not required as this can be reproduced with any new project.

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/104363

### CODE REVIEW

**Review by AThousandShips — APPROVED** [review]

File: core/io/resource_uid.cpp [hunk 1]
```diff
@@ -311,7 +311,7 @@ String ResourceUID::get_path_from_cache(Ref<FileAccess> &p_cache_file, const Str
 		ERR_FAIL_COND_V(rl != len, String());
 
 		if (singleton->id_to_text(id) == p_uid_string) {
-			return String(cs.get_data());
+			return String::utf8(cs.get_data());
```
Comment (Ivorforce) [inline core/io/resource_uid.cpp:314]: You could make use of `Span` here:
```c++
		ERR_FAIL_COND_V(cs.resize(len) != OK, String());
		int32_t rl = p_cache_file->get_buffer((uint8_t *)cs.ptrw(), len);
 		ERR_FAIL_COND_V(rl != len, String());

 		if (singleton->id_to_text(id) == p_uid_string) {
 			return String::utf8(cs);
 		}
```
This would notably stop using `strlen`, so it would stop cutting the string early if `\0` was found.

**Review by Ivorforce — APPROVED** [review]
This will work, though I'd take the opportunity to change to `Span` construction.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.4.1.
