### PR TITLE
Fix FileSystem dock navigation when using Split Mode

### LINKED ISSUE #100277: Problems navigating folders when using FileSystem split view
### Tested versions

- Reproducable in v4.4.dev.custom_build [a40fc2354]
- Works fine in 4.4.dev6 and earlier

### System information

Windows 11

### Issue description

There's a few different problems, but I assume they are all related.

Image
When using a folder structure like the one above, and navigating using the window to the right (not the tree view on the left):
- Cannot navigate to any subfolder from `res://`.
- From `res://a/`, clicking `..` works, but the `a` folder will still be highlighted in the tree, instead of `res://`.
- From `res://x/`, clicking `..` works, but the `a` folder (always the first subfolder) will be highlighted instead of `res://`.
- From `res://a/b/` (or any folder at a depth of 2), clicking `..` will **not** work.
- Navigating to or back from a folder at a depth of 3 or deeper works as expected.

**Note:** In all of these cases, the text field showing the current folder path is correctly updated.

### Steps to reproduce

As described above.

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by larspet**
Fixes #100277

The regression was  introduced by #100010 (most likely), which made bigger changes to `_navigate_to_path()`.
This also simplifies the logic a bit, and does less trimming and appending of `/` all the time.

### CODE REVIEW

**Comment by KoBeWi** [comment]
Show in FileSystem does not work properly in split mode. You need to use it twice to show/select the file.

**Comment by larspet** [comment]
> Show in FileSystem does not work properly in split mode. You need to use it twice to show the file.

Fixed.

Also, I've noticed that every time `navigate_to_path()` is called, `_navigate_to_path()` will be called twice, because of the "Filter Files" search box being cleared with `file_list_search_box->clear()` and thus invoking `_search_changed()`.

This would be simple enough to fix in the case when it's already empty and doesn't need to be cleared, but in the other case it's a little more involved. Since this is also kind of a separate issue, it's probably better handled in a separate PR.

**Comment by KoBeWi** [comment]
> _navigate_to_path() will be called twice, because of the "Filter Files" search box being cleared with file_list_search_box->clear() and thus invoking _search_changed().

Sounds like #100275 will fix it.

**Comment by KoBeWi** [comment]
Another bug is that it changes behavior when navigating to folder depending on `/` suffix. With the suffix it correctly selects the folder in tree (in split view), without the suffix it selects the parent folder instead.
The previous implementation was a bit hacky, but it was to ensure that folders work correctly both with and without the `/` suffix.

**Comment by larspet** [comment]
It should work now regardless of the path ending with `/` or not. I also made it default to `res://` if the given path is empty.

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -705,88 +705,62 @@ void FileSystemDock::_set_current_path_line_edit_text(const String &p_path) {
...
-		while (directory) {
-			directory->set_collapsed(false);
-			directory = directory->get_parent();
-		}
-	}
-
-	if (!found) {
+	TreeItem **directory_ptr = folder_map.getptr(base_dir_path);
+	if (!directory_ptr) {
 		return;
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:737]: I wonder if this should result in an error 🤔

File: editor/filesystem_dock.cpp [hunk 2]
```diff
@@ -705,88 +705,62 @@ void FileSystemDock::_set_current_path_line_edit_text(const String &p_path) {
...
+		while (item) {
+			if (item->get_metadata(0).operator String().ends_with(file_name)) {
+				item->select(0);
 				break;
 			}
+			item = item->get_next();
 		}
+	} else {
+		(*directory_ptr)->select(0);
+		_update_file_list(false);
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:761]: This can be optimized to not update list when the base directory is the same, but that would probably require more changes so it's something potentially for later.

File: editor/filesystem_dock.cpp [hunk 3]
```diff
@@ -705,88 +705,62 @@ void FileSystemDock::_set_current_path_line_edit_text(const String &p_path) {
...
-			if (files->get_item_text(i) == file_name) {
-				files->select(i, true);
-				files->ensure_current_is_visible();
+	// Select the file or directory in the tree.
+	tree->deselect_all();
+	if (display_mode == DISPLAY_MODE_TREE_ONLY) {
+		const String file_name = is_directory ? target_path.trim_suffix("/").get_file() + "/" : target_path.get_file();
+		TreeItem *item = is_directory ? *directory_ptr : (*directory_ptr)->get_first_child();
+		while (item) {
+			if (item->get_metadata(0).operator String().ends_with(file_name)) {
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:753]: This check is redundant when selecting directory, because it should always match anyway.

**Review by KoBeWi — APPROVED** [review]
Works correctly now.

**Comment by Repiteo** [comment]
Thanks!

KoBeWi comments were all non-blockers, so they can be handled in a separate PR
