### PR TITLE
Made favorites dragable

### LINKED ISSUE #26624: Can't Drag n Drop Instance Scenes From Favorites
**Godot version:**
3.1 Beta 10

**OS/device including version:**
Windows 10

**Issue description:**
You can't drag n drop scenes saved in favorites to quickly instance them in the current scene, unlike the rest of the filesystem.

### LINKED ISSUE #32892: Can't drag'n'drop scenes from Favorites to create path in script editor
**Godot version:**
3.2.alpha2

**OS/device including version:**
OSX Sierra

**Issue description:**
When a scene is saved in Favorites and when you drag it in the script editor, its path doesn't appear.

**Steps to reproduce:**
Put a scene into favorites > drag it in the script editor > nothing happens

**Minimal reproduction project:**
Any project with at least one scene

### PR DESCRIPTION
**Pull request by DavidSichma**
fixes #26624, fixes #32892 
There were other instances of this issue but i was unable to find more on github.
Basicly everytime you could drag a regular file you were unable drag a favorite.

Changes:
- a selection of favorites is now of type "files" or "files_and_dirs" like any other file/dir selection
- information regarding favorites is now stored under "favorite"
- selections from both favorites and non-favorites can be dragged and used
- the file dock still won't accept a mixed selection of favorites and non-favorites. This avoids confusion when moving or reorganizing files and is in line with current behavior.

What should break:
- Nothing. `filesystem_dock.cpp` is the only place even aware of favorites existing. The other code expects just regular files and should now work.

Todo:
- it is possible to select the same file twice as favorite and non-favorite

### CODE REVIEW

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -1839,7 +1840,7 @@ Variant FileSystemDock::get_drag_data_fw(const Point2 &p_point, Control *p_from)
 			all_not_favorites &= !is_favorite;
 			selected = tree->get_next_selected(selected);
 		}
-		if (all_favorites) {
+		if (!all_not_favorites) {
 			paths = _tree_get_selected(false);
 		} else {
 			paths = _tree_get_selected();
```
Comment (DavidSichma) [inline editor/filesystem_dock.cpp]: @groud
Why is there this distinction? Or why is false not passed for non-favorites?
This makes the actual selection not contain the individual files if the dir containing them is also selected. I think this behavior is unintuitive especially since the visible selection can contain both the dir and the contained files. If the user wants only the dir they can select just that.

Comment (groud) [reply editor/filesystem_dock.cpp]: No, I think the use case when you want both the containing folder and the children recorded as favorites is a pretty non-existing situation. I think it is is better to avoid confusing situation where a user unintentionally selected a bunch of files and end up with nested favorites for no real reasons.

Also, the variable name should be kept as before, negations in variable naming does not make a lot of sense.

Comment (DavidSichma) [reply editor/filesystem_dock.cpp]: I just think that this
sel_a
shouldn't be the same as this
sel_o

Comment (groud) [reply editor/filesystem_dock.cpp]: Well, for making favorites, I think it should be the same. :)

**Comment by akien-mga** [comment]
Thanks!
