### PR TITLE
[Window] Add unfiltered input handler signal for custom decorations.

### LINKED ISSUE #111235: Cannot move editor window when another dialog is open (macos)
### Tested versions

(edit: corrected referenced issue)

Reproducible in 
- v4.6.dev
- v4.5.stable.official

### System information

Godot v4.5.stable - macOS Tahoe (26.0.1) - Multi-window, 2 monitors - Metal (Forward+) - integrated Apple M2 (Apple8) - Apple M2 (8 threads) - 24.00 GiB memory

### Issue description

Cannot drag editor main window when another dialog (e.g. "Quick Open") is open.

Likely related to #99642 ~#99632~, since `start_drag()` on the main window never gets called. OS-handled window operations such as minimize, fullscreen and resize work.

Workaround: disable "Expand to Title", which lets OS handle window title bar drag. Everything works as expected.

### Steps to reproduce

- Open empty project
- Make sure that "Expand to Title" is enabled
- Verify that main editor window can be dragged
- Open "Quick Open..." or "Settings" dialog
- Verify that main editor window cannot be dragged

### Minimal reproduction project (MRP)

Default empty project will do

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/111235

### CODE REVIEW

**Comment by KoBeWi** [comment]
Doesn't work if the input is blocked by embedded window. Is it intended? If yes, it should be mentioned in the documentation.

File: editor/gui/editor_title_bar.cpp [hunk 1]
```diff
@@ -89,57 +89,73 @@ Control *EditorTitleBar::get_center_control() const {
...
-		}
-		if (base) {
-			next = c;
+				fit_child_in_rect(prev, Rect2i(prev->get_position().x, 0, offset - prev->get_position().x, title_size.height));
+				fit_child_in_rect(base, Rect2i(offset, 0, c_size.width, title_size.height));
+				fit_child_in_rect(next, Rect2i(offset + c_size.width, 0, next->get_position().x + next->get_size().x - (offset + c_size.width), title_size.height));
+			}
+		} break;
+		default:
 			break;
```
Comment (KoBeWi) [inline editor/gui/editor_title_bar.cpp]: This shouldn't be needed.
```suggestion
```

**Comment by bruvzg** [comment]
> Doesn't work if the input is blocked by embedded window.

Updated to work with embedded window as well.

File: doc/classes/Window.xml [hunk 2]
```diff
@@ -803,6 +806,12 @@
 				Emitted when the mouse cursor leaves the [Window]'s visible area, that is not occluded behind other [Control]s or windows, provided its [member Viewport.gui_disable_input] is [code]false[/code] and regardless if it's currently focused or not.
 			</description>
 		</signal>
+		<signal name="nonclient_window_input">
+			<param index="0" name="event" type="InputEvent" />
+			<description>
+				Emitted when the mouse event is received by the custom decoration area defined by [member nonclient_area], and normal input to the window is blocked (e.g, window has exclusive child opened).
```
Comment (Mickeon) [inline doc/classes/Window.xml]: We can always aim to reduce the amount of "e.g." to reduce ambiguity. Some contributors have used it to actually mean "i.e.", or "that means". In this case, it may not clear if it's one occasion of a window being blocked, or it's _essentially_ what "blocked" means.
It's also worth specifying the coordinate system (see `window_input`'s description). I am not sure if what I suggested is actually correct.
```suggestion
				Emitted when the mouse event is received by the custom decoration area defined by [member nonclient_area], and normal input to the window is blocked (such as when it has an exclusive child opened). [param event]'s position is in the embedder's coordinate system.
```

File: doc/classes/Window.xml [hunk 3]
```diff
@@ -691,6 +691,9 @@
 			[b]Note:[/b] On Windows, the portion of a window that lies outside the region is not drawn, while on Linux (X11) and macOS it is.
 			[b]Note:[/b] This property is implemented on Linux (X11), macOS and Windows.
 		</member>
+		<member name="nonclient_area" type="Rect2i" setter="set_nonclient_area" getter="get_nonclient_area" default="Rect2i(0, 0, 0, 0)">
+			If set, defines custom window decoration area, which will receive mouse input even if normal input to the window is blocked. See [signal nonclient_window_input].
```
Comment (Mickeon) [inline doc/classes/Window.xml]: Maybe...?
```suggestion
			If set, defines the window's custom decoration area which will receive mouse input, even if normal input to the window is blocked (such as when it has an exclusive child opened). See also [signal nonclient_window_input].
```

File: doc/classes/Window.xml (hunk 2 above)
Comment (bruvzg) [reply doc/classes/Window.xml]: > It's also worth specifying the coordinate system (see window_input's description).

Same as `window_input`, embedder's system for embedded windows and window own coordinates for native window (since there's no embedder).

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
