### PR TITLE
Keep the drawing transform when drawing meshing in CanvasItem

### LINKED ISSUE #49825: Vulkan: Setting the drawing transform in CanvasItem does not affects drawing of meshes.
### Godot version

4.0 dev (0638ca00373a7fb9e0c114ccc43eae7a17f6f61d)

### System information

Arch Linux

### Issue description

When using CanvasItem drawing commands, setting the drawing transform via `draw_set_tranform_matrix(...)` does not affect future calls to `draw_mesh(...)`. This is due to the `draw_mesh` function overriding the transform internally.

### Steps to reproduce

Try this script on a Node2D the drawing of the mesh is not affected by the provided transform:
```gdscript
extends Node2D

var texture := load("res://icon.png")
var mesh := ArrayMesh.new()
var a = []

func _init():
	a.resize(Mesh.ARRAY_MAX)
	a[Mesh.ARRAY_VERTEX] = PackedVector2Array([Vector2(0, 0), Vector2(100, 0), Vector2(0, 100)])
	a[Mesh.ARRAY_TEX_UV] = PackedVector2Array([Vector2(0, 0), Vector2(1, 0), Vector2(0, 1)])
	a[Mesh.ARRAY_COLOR] = PackedColorArray([Color(1,1,1), Color(1,1,1), Color(1,1,1)])
	a[Mesh.ARRAY_INDEX] = PackedInt32Array([0, 1, 2])
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, a, [], {}, Mesh.ARRAY_FLAG_USE_2D_VERTICES)
	
func _draw():
	var xform := Transform2D().translated(Vector2(0, 100)).rotated(0.5)
	draw_set_transform_matrix(xform)
	draw_mesh(mesh, texture, Transform2D())
	draw_set_transform_matrix(Transform2D())

```

### Minimal reproduction project

Ask if needed (I already opened a PR solving the issue)

### PR DESCRIPTION
**Pull request by groud**
Fixes https://github.com/godotengine/godot/issues/49825

Tested on my side, seems to work fine.

### CODE REVIEW

File: servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp [hunk 1]
```diff
@@ -408,6 +408,7 @@ void RendererCanvasRenderRD::_render_item(RD::DrawListID p_draw_list, RID p_rend
 
 	PushConstant push_constant;
 	Transform2D base_transform = p_canvas_transform_inverse * p_item->final_transform;
+	Transform2D draw_transform = Transform2D();
```
Comment (akien-mga) [inline servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:411]: AFAIK `Transform2D draw_transform;` would be enough, it's already initialized.

**Comment by lawnjelly** [comment]
As far as I remember, the logic around these extra transforms (and having them present separately from the main transform in the shaders) ended up being quite problematic in terms of implementation in 3.x. They may have been introduced originally for instancing. It might be worth considering in 4.x whether it could be worth simplifying this whole area.

For instance just have the extra transforms multiply with the existing transform for the item, and therefore apply to all further commands, update the main transform to the shader, but not keep the separation between main and extra transform.

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
