### PR TITLE
Fix `ColorPickerButton` close popup on mouse click

### LINKED ISSUE #91813: ColorPickerButton toggle mode has no effect on color picker visibility
### Tested versions

- Reproducible in v3.5.3.stable.official [6c814135b], v4.0.1.stable.mono.official [cacf49999], v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 Threads)

### Issue description

Setting `toggle_mode` to true (by default) on a `ColorPickerButton` will not actually make the button togglable. When first pressing the button it will show the color picker but pressing the button again will not hide it; the user must click elsewhere to hide the picker.

As is said in the [documentation](https://docs.godotengine.org/en/stable/classes/class_colorpickerbutton.html#description):
> Pressing the button will toggle the [ColorPicker](https://docs.godotengine.org/en/stable/classes/class_colorpicker.html#class-colorpicker)'s visibility.

but that's not the case, the picker is always shown when clicking on the button.

### Steps to reproduce

- Run the scene in the MRP
- Click the color picker button => the color picker is shown
- Click the button again => the color picker is still visible
- Click outside the button => the color picker is hidden

### Minimal reproduction project (MRP)

[bug_color_picker_button.zip](https://github.com/godotengine/godot/files/15279424/bug_color_picker_button.zip)

### PR DESCRIPTION
**Pull request by pafuent**
Fixes #91813

There is a [proposal](https://github.com/godotengine/godot-proposals/issues/6115) to fix this properly, because it is out of my league and it seems that nobody started to work on it, I decided to propose this fix as a temporary measure until that proposal is implemented.

ColorPickerBug ColorPickerFix

### CODE REVIEW

File: scene/gui/color_picker.cpp [hunk 1]
```diff
@@ -2092,6 +2100,19 @@ void ColorPickerButton::pressed() {
...
+
+	Ref<InputEventMouseButton> mouse_button = p_event;
+	bool ui_accept = p_event->is_action("ui_accept", true) && !p_event->is_echo();
+	bool mouse_left_pressed = mouse_button.is_valid() && mouse_button->get_button_index() == MouseButton::LEFT && mouse_button->is_pressed();
+	if (mouse_left_pressed || ui_accept) {
+		popup_was_open = popup && popup->is_visible();
+	}
+
+	BaseButton::gui_input(p_event);
+}
```
Comment (KoBeWi) [inline scene/gui/color_picker.cpp:2114]: Why this code isn't in `pressed()` method?

**Comment by KoBeWi** [comment]
There is another fix for that issue (#93775), but this one is simpler, so it's more preferable.
However I left a comment in the issue: https://github.com/godotengine/godot/issues/91813#issuecomment-2475020421
If the other bug I mentioned is fixed, this will become irrelevant. I'm not sure if it's worth to fix it now.

File: scene/gui/color_picker.cpp (hunk 1 above)
Comment (pafuent) [reply scene/gui/color_picker.cpp:2114]: I tried that at the beginning, but I noticed that when `pressed()` is being executed, the popup is not visible anymore because you click outside of it (which hides the popup). If this code is implemented into `pressed()`, `popup->is_visible()` will always return false and that will lead to assume that the popup should be open.
To overcome that, I implemented this code into `gui_input` which gets executed before the popup is hidden due to a click was made outside of it.

**Comment by pafuent** [comment]
(updating to the latest changes on master just because I was here 😉 )

**Review by KoBeWi — APPROVED** [review]
My comment from a year ago is still valid, but I guess the fix for underlying issue is not coming anytime soon 🤷‍♂️

**Comment by Repiteo** [comment]
Thanks!
