### PR TITLE
[Windows] Fix root and current folder in native file dialog.

### LINKED ISSUE #98832: Native FileDialog does not open on Windows when using FILE_MODE_OPEN_DIR in some 4.4 dev builds
### Tested versions

- Reproducible in: v4.4.dev2.official [97ef3c837] and v4.4.dev3.official [f4af8201b]
- Not reproducible in: v4.4.dev1.official [28a72fa43] and v4.3.stable.official [77dcf97d8]

### System information

Godot v4.4.dev3 - Windows 10.0.22631 - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 32.0.15.6094) - AMD Ryzen 7 5700G with Radeon Graphics (16 threads)

### Issue description

In current development builds of Godot 4.4 _(dev2 onwards)_, opening a native FileDialog on Windows fails if the file mode is `FileDialog.FILE_MODE_OPEN_DIR`. Specifically, the game window loses focus for a moment before immediately re-gaining focus, almost as if the separate process immediately exits.

This behavior does not exist and functions correctly when:
- Using other file modes
- Used in Godot 4.4.dev1 or Godot 4.3.
- Calling `DisplayServer.file_dialog_show()` with `DisplayServer.FILE_DIALOG_MODE_OPEN_DIR` in any version

I do not have the means to test behavior on macOS or Linux, so I'm unsure if those operating systems are affected.

### Steps to reproduce

To observe the behavior, the following code can be used:
```gd
var dialog = FileDialog.new()
dialog.use_native_dialog = true
dialog.file_mode = FileDialog.FILE_MODE_OPEN_DIR
# ... bring FileDialog to scene tree ...
dialog.popup_centered()
```

The DisplayServer can be used as a baseline and works in all versions:
```gd
DisplayServer.file_dialog_show(
    "Test Dialog", "", "", false, 
    DisplayServer.FILE_DIALOG_MODE_OPEN_DIR,
    PackedStringArray(), func c(_a, _b, _c): pass
)
```

### Minimal reproduction project (MRP)

[OpenDirTest.zip](https://github.com/user-attachments/files/17625616/OpenDirTest.zip)

### LINKED ISSUE #99598: Native FileDialog does not open `current_dir` on Windows
### Tested versions

Godot v4.4.dev5.official [9e6098432]

### System information

Godot v4.4.dev5 - Windows 10.0.19044 - Multi-window, 3 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 2080 (NVIDIA; 32.0.15.5585) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 threads)

### Issue description

`current_dir` does not work on Windows when using native FileDialog.

As far as I can tell, this is because of this code:

https://github.com/godotengine/godot/blob/68f638c/scene/gui/file_dialog.cpp#L367-L372

The `false` parameter removes the drive letter from the path (so `C:/Users/` turns to `/Users/`), which is fine when using the embedded file browser since that has a dropdown for drive letters. But on native file browser, it should use the full path, including drive letter.

Line 73 passes `ProjectSettings::get_singleton()->globalize_path(dir->get_text())` along, which in the case of `/Users/` as input does not touch the path at all.

I haven't done more testing with `res://` and `user://` paths, but those might be broken as well.

### Steps to reproduce

On Windows: Set `current_dir` to a folder, then popup native FileDialog.

### Minimal reproduction project (MRP)

[native-file-dialog-currentdir.zip](https://github.com/user-attachments/files/17882319/native-file-dialog-currentdir.zip)

Be aware that Windows remembers the last opened folder in the dialog, so you might want to change what you're setting `current_dir` to, to avoid it "looking like it works" but not actually updating due to your script's code.

### PR DESCRIPTION
**Pull request by bruvzg**
Supersede https://github.com/godotengine/godot/pull/98839

Fixes https://github.com/godotengine/godot/issues/98832
Fixes https://github.com/godotengine/godot/issues/99598

### CODE REVIEW

File: scene/gui/file_dialog.cpp [hunk 1]
```diff
@@ -174,6 +176,7 @@ void FileDialog::_native_dialog_cb_with_options(bool p_ok, const Vector<String>
 	file->set_text(f);
 	dir->set_text(f.get_base_dir());
 	filter->select(p_filter);
+	update_dir();
```
Comment (RedMser) [inline scene/gui/file_dialog.cpp:179]:
```suggestion
	_change_dir(f.get_base_dir());
```

`current_dir` would just be reset to the same value when using `update_dir()`. Calling `_change_dir()` properly updates the `curent_dir` and also calls `update_dir`.

But this made me discover a new bug: since you're changing this *after* the `*_selected` signals are emitted, you can't retrieve the new `current_dir` value unless you waited a frame in the signal handler.

This is *not* a problem for embedded FileDialogs, only native ones. Do you think the fix is as easy as moving this update-logic above the signal emission? Or should I open a new bug ticket for it instead?

**Review by RedMser — CHANGES_REQUESTED** [review]

File: scene/gui/file_dialog.cpp (hunk 1 above)
Comment (bruvzg) [reply scene/gui/file_dialog.cpp:179]: Yes, probably moving it will work fine.

Comment (RedMser) [reply scene/gui/file_dialog.cpp]: I tried moving it and it works as expected.
Not sure if you saw but I updated my above comment since I found 2 more semi-related bugs, regarding the values of `current_dir` and `current_path` after selecting a file/dir in dialog.

Comment (RedMser) [reply scene/gui/file_dialog.cpp]: I fixed it like this, feel free to cherry-pick: https://github.com/RedMser/godot/commit/bf1d24bfdfa7ee862d33f4da715e66b1ec323fc9

This also fixes embedded file dialogs, which used to return paths like `/Users/Public/...` for `current_dir` and `current_path`, now also returning the drive letter as expected.

Comment (bruvzg) [reply scene/gui/file_dialog.cpp]: Not sure what changing `dir_access->get_current_dir()` to `full_path` should do, it should always be the same value.

Comment (bruvzg) [reply scene/gui/file_dialog.cpp]: > Yes I guess the EditorFileDialog change is not strictly needed then.

Missed that it is different in `FileDialog` (why do we have two almost identical dialogs?), this make sense for the `FileDialog`. Updated PR.

**Review by RedMser — APPROVED** [review]
Looks good to me. I can't say anything about the root folder fix.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
