### PR TITLE
Fix broken negative scaling when using Jolt Physics

### LINKED ISSUE #103408: Negative scaling is broken when using Jolt Physics
### Tested versions

v4.4.rc2.mono.official [01545c995]

This error appeared after upgrading to 4.4rc2 from 4.3.  I was previously using the jolt physics add on.  

This error goes away if i switch to the godot physics engine instead.  It reappears if using jolt.  

### System information

Godot v4.4.rc2.mono - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 32.0.15.6603) - AMD Ryzen 7 3700X 8-Core Processor (16 threads)

### Issue description

With Jolt Physics enabled, when adding a static body as a child of a VehicleWheel3D I get a flood of quaternion errors:

```
E 0:00:01:120   get_quaternion: Basis [X: (1.0, 0.0, 0.0), Y: (0.0, 1.0, 0.0), Z: (0.0, 0.0, -1.0)] must be 
normalized in order to be casted to a Quaternion. Use get_rotation_quaternion() or call orthonormalized() 
if the Basis contains linearly independent vectors.
  <C++ Error>   Condition "!is_rotation()" is true. Returning: Quaternion()
  <C++ Source>  core/math/basis.cpp:730 @ get_quaternion()
```

I can get rid of the errors if I move the StaticBody3D outside of the VehicleWheel3D.  I do expect it to work as before.  I prefer adding a staticBody3D as a child of VehicleWheel3D for organizations sake. 

### Steps to reproduce

1. Enable Jolt Physics under Project -> Project Settings -> Physics -> 3D -> Physics Engine
2. Add a VehicleBody3D node with a collision mesh
3. Add a VehicleWheel3D node
4. Add a StaticBody3D node as a child of the VehicleWheel3D
5. Launch the scene and a flood of quaternion errors should appear

Including project as well.  Open the project and run.  

Thank you.

### Minimal reproduction project (MRP)

[mrpWheelStaticBodyChild.zip](https://github.com/user-attachments/files/19031403/mrpWheelStaticBodyChild.zip)

### PR DESCRIPTION
**Pull request by mihe**
Fixes #103408.
Supersedes #103426.

This PR effectively just brings back [some code](https://github.com/jrouwe/JoltPhysics/blob/548a9716a990c1ddde64423caa5e3ad4c63d7540/src/misc/math.cpp#L5-L28) (derived in part from Jolt's own [`JPH::Mat44::Decompose`](https://github.com/godot-jolt/jolt/blob/c93401ea6577af6ae052f7c22cda6067a30333f3/Jolt/Math/Mat44.inl#L919-L948)) that I had left behind when porting the Jolt integration from the Godot Jolt extension in #99895, due to wanting to keep things as minimal as possible.

What this code is meant to do is take a potentially scaled `Basis` (or `Transform3D`) and decompose it into a rotation part and a scale part, which must be done before passing any transform into Jolt, as Jolt takes scale separately from the rest of the transform in its API, and sometimes also takes rotation separately, in the form of a quaternion.

I had mistaken the following code:

```
Vector3 scale = some_basis.get_scale();
Basis rotation = some_basis.orthonormalized();
```

... as being a valid substitute for this code:

```
Basis rotation;
Vector3 scale;
decomposed(some_basis, rotation, scale);
```

... which it is not, because while [`Basis::orthonormalize`](https://github.com/godotengine/godot/blob/15ff450680a40391aabbffde0a57ead2cd84db56/core/math/basis.cpp#L56-L72) does also use the Gram-Schmidt process to perform the orthonormalization, much like this "new" `decompose` function, it does not handle reflection (i.e. negative scaling) in any way, meaning we can end up with a `Basis` that is orthonormal, but is not in fact a valid (right-handed) rotation, which causes problems with things like [`Basis::get_quaternion`](https://github.com/godotengine/godot/blob/15ff450680a40391aabbffde0a57ead2cd84db56/core/math/basis.cpp#L728-L762), as it assumes a valid (right-handed) rotation.

This "new" `decompose` function solves this by essentially just flipping all the axes of the `Basis` when we find ourselves with a negative determinant (i.e. negative scaling) which seems to line up with the convention used by other `Basis` methods, like [`Basis::get_scale`](https://github.com/godotengine/godot/blob/15ff450680a40391aabbffde0a57ead2cd84db56/core/math/basis.cpp#L302-L325) and [`Basis::get_rotation_quaternion`](https://github.com/godotengine/godot/blob/15ff450680a40391aabbffde0a57ead2cd84db56/core/math/basis.cpp#L401-L413).

It also serves as a minor optimization, since we can avoid some of the redundant vector normalizations that are shared between `Basis::get_scale` and `Basis::orthonormalize`.

### CODE REVIEW

**Comment by mihe** [comment]
I'd love for someone more mathematically inclined than myself to check that I'm not talking too much rubbish here, like perhaps @jrouwe or @rburing (or anyone else who feels up to it).

File: modules/jolt_physics/misc/jolt_math_funcs.cpp [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+	const real_t x_dot_x = x.dot(x);
+
+	y -= x * (y.dot(x) / x_dot_x);
+	z -= x * (z.dot(x) / x_dot_x);
+
+	const real_t y_dot_y = y.dot(y);
+
+	z -= y * (z.dot(y) / y_dot_y);
+
+	const real_t z_dot_z = z.dot(z);
```
Comment (jrouwe) [inline modules/jolt_physics/misc/jolt_math_funcs.cpp:67]: Could be simplified to just calculating the length of z (since you do sqrt below)

File: modules/jolt_physics/misc/jolt_math_funcs.cpp [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+
+	r_scale = sign * Vector3(Math::sqrt(x_dot_x), Math::sqrt(y_dot_y), Math::sqrt(z_dot_z));
```
Comment (jrouwe) [inline modules/jolt_physics/misc/jolt_math_funcs.cpp:69]: My code is only flipping the sign of z, not x and y (flipping the sign of all 3 components will keep the matrix left handed)

File: modules/jolt_physics/misc/jolt_math_funcs.cpp [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+
+THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR
+A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
+ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
+*/
+
+#include "jolt_math_funcs.h"
+
+void JoltMath::decompose(Basis &p_basis, Vector3 &r_scale) {
+	const real_t sign = SIGN(p_basis.determinant());
```
Comment (mihe) [inline modules/jolt_physics/misc/jolt_math_funcs.cpp:52]: I'm curious if this calculation of the determinant could/should be replaced with the scalar triple product instead, since it's likely cheaper, similar to what's being done in [`JPH::Mat44::Decompose`](https://github.com/godot-jolt/jolt/blob/4f9a86b53916cc91c042acf6cd79eeef62bf5f0c/Jolt/Math/Mat44.inl#L943).

Is it equivalent for all types of input, even more degenerate matrices?

Does it matter if it's done before or after the orthogonalization?

File: modules/jolt_physics/misc/jolt_math_funcs.h [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+/**************************************************************************/
+
+#ifndef JOLT_MATH_FUNCS_H
+#define JOLT_MATH_FUNCS_H
+
+#include "core/math/transform_3d.h"
+
+class JoltMath {
+public:
+	static void decompose(Basis &p_basis, Vector3 &r_scale);
```
Comment (jrouwe) [inline modules/jolt_physics/misc/jolt_math_funcs.h:38]: Could use a comment saying that on output p_basis is a right-handed orthonormal matrix and the scale extracted to r_scale

File: modules/jolt_physics/misc/jolt_math_funcs.cpp (hunk 3 above)
Comment (jrouwe) [reply modules/jolt_physics/misc/jolt_math_funcs.cpp:52]: The determinant and scalar triple product result in the same expression for a 3x3 matrix, so it doesn't matter which one you use.

I think it does not matter if you do it before or after orthogonalization as we're only looking at the sign. I wonder though what happens if you get into float precision issues for really small vectors, so I would say it's safer to do it after orthogonalization.

B.t.w. my code also doesn't handle every case. E.g. If you pass in a matrix where all columns are the same vector then it will happily divide by zero.

Comment (mihe) [reply modules/jolt_physics/misc/jolt_math_funcs.cpp:52]: > The determinant and scalar triple product result in the same expression for a 3x3 matrix, so it doesn't matter which one you use.

That does indeed seem to be the case, in pretty black-and-white [on Wikipedia](https://en.wikipedia.org/wiki/Triple_product) even. I'll switch over to it.

> I wonder though what happens if you get into float precision issues for really small vectors, so I would say it's safer to do it after orthogonalization.

I'll take your word for it. 😅

> B.t.w. my code also doesn't handle every case. E.g. If you pass in a matrix where all columns are the same vector then it will happily divide by zero.

There's a separate check happening (only in editor/debug builds though) that ensures that there's no singular matrix being passed into this function, so it should be somewhat safe as-is.

File: modules/jolt_physics/misc/jolt_math_funcs.cpp (hunk 1 above)
Comment (mihe) [reply modules/jolt_physics/misc/jolt_math_funcs.cpp:61]: I preferred the "symmetry" of having all components `*_dot_*`.

File: modules/jolt_physics/misc/jolt_math_funcs.cpp (hunk 3 above)
Comment (mihe) [reply modules/jolt_physics/misc/jolt_math_funcs.cpp]: I just realized `Basis::determinant()` (which uses cofactor expansion) and the scalar triple product were basically the exact same amount of operations, so suggesting one was cheaper than the other was not very bright of me.

But I guess I should use the scalar triple product anyway, since we don't have the `Basis` object set up right after orthogonalization.

**Review by jrouwe — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by fire** [comment]
In godot engine the common conversion from Basis to quaternion is get_rotation_quaternion. I don't know why we're doing it this way.

**Review by fire — CHANGES_REQUESTED** [review]
Please explain why we can't use get_rotation_quaternion or orthogonalize?

https://github.com/godotengine/godot/blob/master/core/math/basis.cpp#L80

**Comment by mihe** [comment]
@fire Sorry, I wasn't very clear in the PR description, but as mentioned [in the issue](https://github.com/godotengine/godot/issues/103408#issuecomment-2692275694), in the majority of cases we are not in fact converting our `Basis` to a `Quaternion`, we just want to make our `Basis` right-handed orthonormal, and extract our scale in the process, since Jolt expects to be passed a transform (and scale separately) in a lot of these cases. So `Basis::get_rotation_quaternion` has no relevance in these cases, unless we want to go through the trouble of converting it back to a `Basis`.

I must admit I'm not sure if the handedness is strictly important to resolve before passing a _transform_ to Jolt though, but seeing as how the extracted scale that goes along with it is what's meant to represent the reflection, the extraction of which seems to be some matter of convention (flipping one versus three axes) I assume we should be stripping said reflection from the transforms as well? Perhaps @jrouwe can shed some light on whether that would cause any problems in Jolt or trigger some assertion somewhere. Either way, `Basis::orthogonalize` is not relevant, since it doesn't normalize, and doesn't give us the scale.

As far as I can see, if we wanted to only make use of existing `Basis` methods, this is what this new `decompose` function would look like:

```cpp
void decompose(Basis &p_basis, Vector3 &r_scale) {
    // Extract the scale.
    r_scale = p_basis.get_scale();

    // Orthogonalize and normalize.
    p_basis.orthonormalize();

    // Ensure right-handed rotation.
    real_t det = p_basis.determinant();
    if (det < 0) {
        p_basis.scale(Vector3(-1, -1, -1));
    }
}
```

I'd be fine with merging this as well, but there is some amount of wasted computation compared to what's in the PR currently.

Also, note that since this `decompose` method would be applied to any transform passed into the Jolt physics server, the additional stuff done in `Basis::get_rotation_quaternion`, when compared to `Basis::get_quaternion`, is entirely redundant. Frankly the normalization of the quaternion currently happening in `JPH::Quat to_jolt(const Basis &p_basis)` might be redundant as well.

**Comment by fire** [comment]
Add decompose (decompose_to_scale) to Basis would be a valid fix too in my opinion.

**Comment by mihe** [comment]
> The various methods should be unified in Basis in my opinion.

There might very well be some argument for adding/changing some stuff in `Basis`, but since this need seems somewhat specific to the Jolt integration at the moment, I'd prefer not to complicate this fix with core changes.

> I am not sure forcing right-handed rotation is correct. It feels wrong but I don't have an argument so...

In case you haven't seen it, this is what `Basis::get_rotation_quaternion` does already:

https://github.com/godotengine/godot/blob/9f68a816599412c56a4626dd6c47244ebc65ed1f/core/math/basis.cpp#L406-L410

And is what's being asserted in `Basis::is_rotation`:

https://github.com/godotengine/godot/blob/9f68a816599412c56a4626dd6c47244ebc65ed1f/core/math/basis.cpp#L128-L131

I'm frankly out of my depth here as well, but from what I understand it is in fact not "correct" to do this, because there is no one unique way of decomposing a negatively scaled matrix into rotation and scale, so you're forced to pick one arbitrarily.

There's some reasoning for the way Godot does it [here](https://github.com/godotengine/godot/blob/9f68a816599412c56a4626dd6c47244ebc65ed1f/core/math/basis.cpp#L307-L316) as well as a mention of it [here](https://docs.godotengine.org/en/latest/classes/class_node3d.html#class-node3d-property-scale).

**Comment by fire** [comment]
Copying https://github.com/godotengine/godot/blob/9f68a816599412c56a4626dd6c47244ebc65ed1f/core/math/basis.cpp#L406-L410 is a pretty convincing argument for your change.

**Comment by jrouwe** [comment]
> Perhaps @jrouwe can shed some light on whether not doing so would cause any problems in Jolt, or trigger some assertion somewhere.

I've never tested this but I'm pretty sure that if you pass in a left-handed matrix into Jolt that everything will explode.

**Comment by jrouwe** [comment]
> I'm frankly out of my depth here as well, but from what I understand it is in fact not "correct" to do this, because there is no one unique way of decomposing a negatively scaled matrix into rotation and scale, so you're forced to pick one arbitrarily.

I think there is, but you have to make sure that the sign of the scale that you 'extract' matches the flipping that you do to the rotation part. E.g. the code above doesn't do that:

```
void decompose(Basis &p_basis, Vector3 &r_scale) {
    // Extract the scale.
    r_scale = p_basis.get_scale();

    // Orthogonalize and normalize.
    p_basis.orthonormalize();

    // Ensure right-handed rotation.
    real_t det = p_basis.determinant();
    if (det < 0) {
        p_basis.scale(Vector3(-1, -1, -1));
    }
}
```

If you decide to scale `p_basis` you have to apply the same operation to `r_scale`.

In an equation:

M = R * S

Where M is `p_basis` at the start of the function, R is `p_basis` after orthonormalization and S a diagonal matrix `r_scale`. Note that I haven't checked the implementations of `get_scale` and `orthonormalize` to see if multiplying those two will indeed result in getting the original matrix back (if there's no shearing). I'm assuming they do so that the equation above holds.

When the determinant is negative, you're doing:

M = (R * F) * S

where F is the diagonal matrix [-1, -1, -1], so in order to keep the matrix the same you need to do:

M = (R * F) * (F^-1 * S)

And since F^-1 = F this means you need to multiply your `r_scale` with [-1, -1, -1] too.

Since this code can be called quite often, I would opt for not wasting CPU cycles by doing duplicate work in `get_scale` and `orthonormalize`. I would go with the code that is currently in the PR.

**Comment by Repiteo** [comment]
We'll roll with this as-is, I think the reasons given are adequate.

Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.4.1.
