### PR TITLE
Show tile set editor bottom panel button when creating a tile set for a tile map

### LINKED ISSUE #56413: TileSet editor doesn't open right after creating TileSet
### Godot version

bc2445d

### System information

W10

### Issue description

When you create a fresh new TileMap, right click `tile_set` property and create a new TileSet, the resource is created, but then nothing happens. You need to click the TileSet resource for the TileSet bottom editor to appear.

This could make sense if not the fact that you can deselect TileMap node and select it again for the TileSet to appear again. Whenever you do something with TileMap, both TileSet and TileMap editors are always automatically visible. The only exception is when you create a new TileMap and click it when it doesn't have any TileSet. I got used so much to having both editors always visible that it actually confused me.

When a new TileSet is created in TileMap, the TileSet editor tab should be immediately visible.

### Steps to reproduce

1. Create new TileMap node
2. Create new TileSet for that TileMap
3. Where editor
image

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by PucklaJ**
Fixes #56413

In `TilesEditorPlugin::_update_editors`, which is connected to the `changed` signal of a `TileMap`, the bottom panel buttons `tileset_editor_button` and `tilemap_editor_button` are correctly hidden or shown. Also this fix switches to another bottom panel if the `TileSetEditor` panel is displayed while there is no active `TileSet`.

### CODE REVIEW

File: editor/plugins/tiles/tiles_editor_plugin.cpp [hunk 1]
```diff
@@ -157,6 +157,17 @@ void TilesEditorPlugin::_update_editors() {
 
 	// Update the viewport.
 	CanvasItemEditor::get_singleton()->update_viewport();
+
+	// Update visibility of bottom panel buttons
```
Comment (YeldhamDev) [inline editor/plugins/tiles/tiles_editor_plugin.cpp:161]:
```suggestion
	// Update visibility of bottom panel buttons.
```

**Review by YeldhamDev — CHANGES_REQUESTED** [review]

**Comment by YeldhamDev** [comment]
Simple PRs should be squashed into a single commit. Here are the instructions on how to do so: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase

**Review by YeldhamDev — APPROVED** [review]

**Review by groud — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
