### PR TITLE
Android: Fix `java.util.HashMap` handling

### LINKED ISSUE #114920: Android: Crash when emitting signal with java.util.HashMap (NoSuchMethodError: get_keys)
### Tested versions

 Godot version
4.5

### System information

Android - Android 15 - Vulkan/Mobile

### Issue description

When an Android plugin emits a signal using `GodotPlugin.emitSignal()` and passes a `java.util.HashMap` (or `java.util.Map`) as a parameter, the game crashes immediately.
The JNI layer attempts to call a method named `get_keys()` on the Java object, which is a method specific to Godot's internal `GodotDictionary` class, not Java's standard `HashMap`.
**Error Log:**
```text
Pending exception java.lang.NoSuchMethodError: no non-static method "Ljava/util/HashMap;.get_keys()[Ljava/lang/String;"
JNI DETECTED ERROR IN APPLICATION: JNI CallObjectMethodV called with pending exception java.lang.NoSuchMethodError

 **source code:**
https://github.com/godotengine/godot/blob/4.5/platform/android/jni_utils.cpp#L448
```

### Steps to reproduce

Create an Android plugin extending GodotPlugin.

Emit a signal with a HashMap as an argument:
java
Map<String, Object> map = new HashMap<>();
map.put("key", "value");
emitSignal("my_signal", map); // Crash occurs here

The application crashes with a SIGABRT.

### Minimal reproduction project (MRP)

N/A (Simple code snippet provided above is sufficient).

### PR DESCRIPTION
**Pull request by syntaxerror247**
- Fixes #114920

### CODE REVIEW

File: platform/android/java/lib/src/main/java/org/godotengine/godot/Dictionary.java [hunk 1]
```diff
@@ -33,6 +33,7 @@
 import java.util.HashMap;
 import java.util.Set;
 
+@Deprecated
```
Comment (m4gr3d) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/Dictionary.java]: Can you specify in the javadocs that a regular `Map` should be used instead.

File: platform/android/jni_utils.cpp [hunk 2]
```diff
@@ -422,22 +422,43 @@ Variant _jobject_to_variant(JNIEnv *env, jobject obj, int p_depth) {
...
+			env->DeleteLocalRef(jkey);
+			env->DeleteLocalRef(jvalue);
 		}
 
+		env->DeleteLocalRef(entrySetObj);
+		env->DeleteLocalRef(iteratorObj);
+		env->DeleteLocalRef(setClass);
+		env->DeleteLocalRef(iteratorClass);
+		env->DeleteLocalRef(entryClass);
+
```
Comment (m4gr3d) [inline platform/android/jni_utils.cpp:470]: Instead of using the `iterator()`, you could get the `keySet()` and `values()` and invoke `toArray()` on them to get an `Object` array of the keys and values respectively.. I'm not sure if the code would be simpler than the current code, so I leave it at your discretion about which approach to use.

**Review by m4gr3d — CHANGES_REQUESTED** [review]
Searching for `org.godotengine.godot.Dictionary` in the codebase shows other locations that would also need to be updated:
- https://github.com/godotengine/godot/blob/481f36ed20520db3195a09cc309abf48c03cf51a/platform/android/java/app/src/instrumented/java/com/godot/game/test/javaclasswrapper/TestClass.kt#L33
- https://github.com/godotengine/godot/blob/481f36ed20520db3195a09cc309abf48c03cf51a/platform/android/java_class_wrapper.cpp#L1076
- https://github.com/godotengine/godot/blob/481f36ed20520db3195a09cc309abf48c03cf51a/platform/android/java_class_wrapper.cpp#L1440
- https://github.com/godotengine/godot/blob/481f36ed20520db3195a09cc309abf48c03cf51a/platform/android/jni_utils.cpp#L475

**Comment by m4gr3d** [comment]
> If I'm not mistaken with some tests I did, currently (Godot 4.5.1) java lists and arrays are accessible as `JavaObject`, not godot `Array`. Which btw is particularly complicated in the case of arrays, as you can't call indexer like `array[i]` from GDScript. List is a little less of an issue since you can do `list.call(&'get', i)` I believe.
> 
> Will this PR change behavior so all java maps are accessible in GDScript as a Godot `Dictionary` instead of a `JavaObject`? Because if so, it would be inconsistent with `Array` if the same is not done to convert java arrays and/or collections into godot arrays.
> 
> I think either everything should be converted, or better yet only java arrays into godot `Array[JavaObject]` and lists/collections and maps remain as `JavaObject` as you can do everything via methods and field access.

@geekley Let's continue this conversation in the linked issue to keep the PR focused on the Map / HashMap implementation.

**Comment by geekley** [comment]
Well, it's relevant because now I don't think `Dictionary` should be deprecated.

File: platform/android/java/lib/src/main/java/org/godotengine/godot/Dictionary.java [hunk 3]
```diff
@@ -33,8 +33,8 @@
 import java.util.HashMap;
 import java.util.Set;
 
-public class Dictionary extends HashMap<String, Object> {
-	protected String[] keys_cache;
+public final class Dictionary extends HashMap<String, Object> {
```
Comment (m4gr3d) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/Dictionary.java:37]: Let's mark the methods below as deprecated and instead recommend using the `Map` equivalents.

Comment (m4gr3d) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/Dictionary.java:37]: > extend from HashMap<Object, Object>, since godot does not require dictionary keys to be strings

Looks like we may be able to also make that change by making `Dictionary extends HashMap<? extends Object, Object>`

**Review by m4gr3d — CHANGES_REQUESTED** [review]

File: platform/android/java/lib/src/main/java/org/godotengine/godot/Dictionary.java (hunk 3 above)
Comment (syntaxerror247) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/Dictionary.java:37]: > Dictionary extends HashMap<? extends Object, Object>

This doesn't looks valid for extending a class. Did you mean `HashMap<Object, Object>`?

Comment (m4gr3d) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/Dictionary.java:37]: No, the `? extends` notation is known as an upper bounded wildcard and indicates that the data structure accepts the given type or any other that extends from it.

See https://en.wikipedia.org/wiki/Wildcard_(Java)#Bounded_wildcards

Comment (syntaxerror247) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/Dictionary.java:37]: image


https://docs.oracle.com/javase/tutorial/java/generics/wildcards.html

> The wildcard is never used as a type argument for a generic method invocation, a generic class instance creation, or a supertype.

Comment (m4gr3d) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/Dictionary.java:37]: you're right, I think I confused it with the ability to do so for variable declaration.

File: platform/android/java/lib/src/main/java/org/godotengine/godot/Dictionary.java [hunk 4]
```diff
@@ -33,9 +33,13 @@
...
+	private String[] keys_cache;
 
+	/**
+	 * @deprecated Use {@link java.util.HashMap} APIs instead.
```
Comment (m4gr3d) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/Dictionary.java]:
```suggestion
	 * @deprecated Use {@link java.util.HashMap#keySet()} APIs instead.
```

File: platform/android/java/lib/src/main/java/org/godotengine/godot/Dictionary.java [hunk 5]
```diff
@@ -48,6 +52,10 @@ public String[] get_keys() {
 		return ret;
 	}
 
+	/**
+	 * @deprecated Use {@link java.util.HashMap} APIs instead.
```
Comment (m4gr3d) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/Dictionary.java]:
```suggestion
	 * @deprecated Use {@link java.util.HashMap#values()} APIs instead.
```

File: platform/android/java/lib/src/main/java/org/godotengine/godot/Dictionary.java [hunk 6]
```diff
@@ -60,10 +68,18 @@ public Object[] get_values() {
...
```
Comment (m4gr3d) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/Dictionary.java]:
```suggestion
	 * @deprecated Use {@link java.util.HashMap#putAll(Map)} APIs instead.
```

File: platform/android/java/lib/src/main/java/org/godotengine/godot/Dictionary.java [hunk 7]
```diff
@@ -60,10 +68,18 @@ public Object[] get_values() {
...
+	 */
+	@Deprecated
 	public void set_keys(String[] keys) {
 		keys_cache = keys;
 	}
 
+	/**
+	 * @deprecated Use {@link java.util.HashMap} APIs instead.
```
Comment (m4gr3d) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/Dictionary.java]:
```suggestion
	 * @deprecated Use {@link java.util.HashMap#putAll(Map)} APIs instead.
```

**Review by m4gr3d — APPROVED** [review]
Looks good!
