### PR TITLE
Fix invalid tooltip position

### LINKED ISSUE #66477: Tooltip not clamped to viewport and isn't rendering anything behind it
### Godot version

v4.0.beta1.official.20d667284

### System information

Windows 10, Vulkan, NVIDIA GeForce GTX 1080 Ti

### Issue description

Tooltip_text isn't clamped to viewport and isn't rendering anything behind it except the background color. Examples below comparing 4.0 and 3.5. Exact same steps taken in both versions and the results are very different

4.0

3.5, expected behavior

### Steps to reproduce

1. Make a theme and change TooltipPanel panel texture to something that has a transparent background
2. Set control node tooltip to something and put the theme on it as well
3. You'll see the background color through everything as well as notice it's not clamped to the viewport, cutting the rest of the text

### Minimal reproduction project

[tooltip_test.zip](https://github.com/godotengine/godot/files/9650203/tooltip_test.zip)

### PR DESCRIPTION
**Pull request by Cykyrios**
Fixes #66477. Tooltips would get clipped when close to the window's right edge, instead of being pushed to the left. This also fixes tooltips not appearing at all when the window is on a monitor other than the first one (also applies to the editor when in single window mode).

### CODE REVIEW

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -1266,6 +1266,9 @@ void Viewport::_gui_show_tooltip() {
 
 	Window *window = gui.tooltip_popup->get_parent_visible_window();
 	Rect2i vr = window->get_usable_parent_rect();
+	if (gui.tooltip_popup->is_embedded()) {
+		vr = Rect2i(Point2i(), window->size);
+	}
```
Comment (akien-mga) [inline scene/main/viewport.cpp:1271]: There's no point to the first line calculating `vr` if it's overridden afterwards, so this should likely be `if () {} else {}`.

Comment (Cykyrios) [reply scene/main/viewport.cpp:1271]: True, updated.

File: scene/main/viewport.cpp [hunk 2]
```diff
@@ -1265,7 +1265,12 @@ void Viewport::_gui_show_tooltip() {
 	Rect2 r(gui.tooltip_pos + tooltip_offset, gui.tooltip_popup->get_contents_minimum_size());
 
 	Window *window = gui.tooltip_popup->get_parent_visible_window();
-	Rect2i vr = window->get_usable_parent_rect();
+	Rect2i vr;
+	if (gui.tooltip_popup->is_embedded()) {
+		vr = Rect2i(Point2i(), window->size);
+	} else {
+		vr = window->get_usable_parent_rect();
+	}
```
Comment (Sauermann) [inline scene/main/viewport.cpp:1274]: There are cases, where `window` is not the embedder of the popup. In these cases, some tooltips get positioned unexpected.
- Root window (embed_subwindows = true)
  - Window (embed_subwindows = true)
    - Button with tooltip

The tooltip of the button is displayed in the Root window, but in your suggestion, Window is used for calculating the position.

I suggest to use `Rect2i(Point2i(), gui.tooltip_popup->_get_embedder()->size);` instead of `Rect2i(Point2i(), window->size);` in your change.

Comment (Cykyrios) [reply scene/main/viewport.cpp:1274]: I hadn't thought about that, but quickly found an example with the sun/environment preview dialog, where tooltips do indeed position themselves unexpectedly. Changing this as per your suggestion.

File: scene/main/viewport.cpp [hunk 3]
```diff
@@ -1265,7 +1265,12 @@ void Viewport::_gui_show_tooltip() {
 	Rect2 r(gui.tooltip_pos + tooltip_offset, gui.tooltip_popup->get_contents_minimum_size());
 
 	Window *window = gui.tooltip_popup->get_parent_visible_window();
-	Rect2i vr = window->get_usable_parent_rect();
+	Rect2i vr;
+	if (gui.tooltip_popup->is_embedded()) {
+		vr = Rect2i(Point2i(), gui.tooltip_popup->_get_embedder()->size);
```
Comment (Sauermann) [inline scene/main/viewport.cpp:1270]: I just noticed, that `size` is not enough.
As soon, as the window is scaled (`Window.content_scale_mode = CONTENT_SCALE_MODE_CANVAS_ITEMS`), it becomes necessary to use
```
    vr = gui.tooltip_popup->_get_embedder()->get_visible_rect();
```
because `size` does not necessarily indicate the visible area of the embedder, which again leads to mispositioned windows.

**Comment by Dunkhan** [comment]
Damn I was really hoping this would make it in for beta 3

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
