### PR TITLE
GDScript: Keep builtin method info on release builds

### LINKED ISSUE #61092: Type inferrence fails in release build when using str()
### Godot version

3.x ddc14b6bbce41ca539e6314403b5afea7d192b19

### System information

Arch Linux

### Issue description

This error is not the same as #59723

example code:

```
var item_id := 0

func _ready():
	var id := "ugc_" + str(item_id)
```

### Steps to reproduce

Execute the code above

### Minimal reproduction project

[type_inference_mrp.zip](https://github.com/godotengine/godot/files/8701236/type_inference_mrp.zip)

### PR DESCRIPTION
**Pull request by vnen**
This is so type inference still works properly after exporting the project. The argument names are still stripped on release builds.

Fix #61092

### CODE REVIEW

File: modules/gdscript/gdscript_functions.cpp [hunk 1]
```diff
@@ -1467,193 +1467,196 @@ bool GDScriptFunctions::is_deterministic(Function p_func) {
 
 MethodInfo GDScriptFunctions::get_info(Function p_func) {
 #ifdef DEBUG_ENABLED
+#define ARGNAME(m_name) #m_name
```
Comment (akien-mga) [inline modules/gdscript/gdscript_functions.cpp:1470]: This actually includes `""` in the argument name:
```diff
@@ -971,7 +971,7 @@
 		</method>
 		<method name="sqrt">
 			<return type="float" />
-			<argument index="0" name="s" type="float" />
+			<argument index="0" name=""s"" type="float" />
 			<description>
 				Returns the square root of [code]s[/code], where [code]s[/code] is a non-negative number.
 				[codeblock]
```

I guess it should work without `#`? Or without quotes in calls to `ARGNAME()`.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
