### PR TITLE
Fix updating lightmap captures on Mobile

### LINKED ISSUE #84846: Vulkan Mobile: LightmapGI dynamic object lighting results in black objects
### Godot version

v4.1.3.stable.official [f06b6836a] and v4.2.beta5.official [4c96e9676]

### System information

Godot v4.1.3.stable and Godot v4.2.beta5 - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.2849) - 12th Gen Intel(R) Core(TM) i7-12700KF (20 Threads)

### Issue description

Hey guys, Seems like Lightmap**Probes** are not working on **Mobile** renderer. They work well on **Forward+** but **not in Mobile**. 

https://github.com/godotengine/godot/assets/67930504/b3c681fa-061c-4e2e-bd4d-8b5b22cc4264

I've already:
- Tested on both Godot 4.1.3 and 4.2 beta 5.
  - Light**maps** don't work on Godot 4.1.2 on Mobile Renderer, but works in 4.2 beta 5. Light Probes don't work with Mobile Renderer on both.
- Set up lightmap UVs.
- Marked static and dynamic objects and lights.
- Set up all kinds of World Environment settings, even tried to delete and disable it.
  - In this node, the Background mode `Sky` have issues on Mobile, so I set up to `Custom Color` (seems related to https://github.com/godotengine/godot/issues/55868#issue-1077887433)
- Baked LightmapGI on both Forward+ and Mobile:
- Tried many combinations on the LightmapGI node.
- Tried a brand new project, now even the Lightmaps stopped working on Godot 4.1.2 (Still working on 4.2 beta 5)...
- Yes, I restarted my PC.
- Deleted all Godot config files in `AppData\Local` and `AppData\Roaming`

### Steps to reproduce

Bake a scene with LightmapGI and an object that transition between different lighting conditions. The Probes will work on Forward+ but not on Mobile.

### Minimal reproduction project

[LightmapProbes_Test.zip](https://github.com/godotengine/godot/files/13335324/LightmapProbes_Test.zip)

Edit: MRP for Godot 4.3.dev6
[Lightmap_Test_4.3.dev6.zip](https://github.com/godotengine/godot/files/15354314/Lightmap_Test_4.3.dev6.zip)

### PR DESCRIPTION
**Pull request by BlueCube3310**
Fixes #84846

"The best solution is usually the easiest one"

The mobile backend would only create the probe buffer, but never update it (unlike Forward)

### CODE REVIEW

**Comment by SpockBauru** [comment]
Updated my MRP to this PR:
[light_probes_mobile.zip](https://github.com/user-attachments/files/17792369/light_probes_mobile.zip)

This PR Indeed fixes the issues for the Mobile Renderer, thanks!

https://github.com/user-attachments/assets/e4e17865-808a-4a95-8e6f-1fb90eb6bcac

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected.

File: servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp [hunk 1]
```diff
@@ -2064,6 +2064,10 @@ void RenderForwardMobile::_fill_render_list(RenderListType p_render_list, const
 			surf = surf->next;
 		}
 	}
+
+	if (p_render_list == RENDER_LIST_OPAQUE && lightmap_captures_used) {
+		RD::get_singleton()->buffer_update(scene_state.lightmap_capture_buffer, 0, sizeof(LightmapCaptureData) * lightmap_captures_used, scene_state.lightmap_captures);
+	}
```
Comment (Calinou) [inline servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp:2070]: Note that despite this being done in the opaque render list, it works on dynamic objects that have transparent materials too.

**Review by clayjohn — APPROVED** [review]
Looks great! 

These fixes always make me laugh when I run into them. You prepare yourself to do a deep dive into figuring out how a system works and what needs to change and then you realize that its literally just one forgotten line of code

**Comment by Repiteo** [comment]
Thanks!
