### PR TITLE
Fix TrackCache memory crash

### LINKED ISSUE #85233: Crash on reimport when applying AnimatedValueBackups from an Apply Reset
### Godot version

4.2.rc 7022271

### System information

Godot v4.2.rc (702227129) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

Godot crashes due to a complicated chain of events in the stack trace involving `reimport_files`, `reload_scene` and a synchronous `clear_history` which memdeletes several dangling TrackCache pointers in this RefCounted AnimatedValuesBackup ?!

```
Critical error detected c0000374
A breakpoint instruction (__debugbreak() statement or a similar call) was executed in godot.windows.editor.x86_64.exe.
```
image

Something feels very wrong about holding raw pointers to an AnimationMixer TrackCache in AnimatedValuesBackup. I can't follow the flow at all of how values get stored in AnimatedValuesBackup.

To maintain single-free semantics, these `TrackCache*` values must be **moved** and **owned by** the AnimatedValuesBackup.

TrackCache pointers must never be shared by other objects, otherwise a use-after-free or double-delete is likely to happen

### Steps to reproduce

1. Follow the steps in #85232 to Apply Reset on an opened gltf
2. Select the gltf in the filesystem (it will already be selected if you followed the steps)
3. Open the Import dock and click Reimport
4. Godot will crash.

### Minimal reproduction project

[ApplyReset.zip](https://github.com/godotengine/godot/files/13442920/ApplyReset.zip)

### LINKED ISSUE #85250: Random crash when saving scene
### Godot version

4.2 rc1

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

```
_free_base(void * block) Line 105 (c:\Users\Tomek\AppData\Local\Programs\Microsoft VS Code\minkernel\crts\ucrt\src\appcrt\heap\free_base.cpp:105)
Memory::free_static(void * p_ptr, bool p_pad_align) Line 169 (c:\godot_source\core\os\memory.cpp:169)
memdelete<AnimationMixer::TrackCache>(AnimationMixer::TrackCache * p_class) Line 113 (c:\godot_source\core\os\memory.h:113)
AnimatedValuesBackup::~AnimatedValuesBackup() Line 398 (c:\godot_source\scene\animation\animation_mixer.h:398)
AnimatedValuesBackup::`scalar deleting destructor'(unsigned int) (Nieznane źródło:0)
memdelete<AnimatedValuesBackup>(AnimatedValuesBackup * p_class) Line 112 (c:\godot_source\core\os\memory.h:112)
Ref<AnimatedValuesBackup>::unref() Line 212 (c:\godot_source\core\object\ref_counted.h:212)
Ref<AnimatedValuesBackup>::~Ref<AnimatedValuesBackup>() Line 223 (c:\godot_source\core\object\ref_counted.h:223)
Pair<AnimationMixer *,Ref<AnimatedValuesBackup>>::~Pair<AnimationMixer *,Ref<AnimatedValuesBackup>>() (Nieznane źródło:0)
List<Pair<AnimationMixer *,Ref<AnimatedValuesBackup>>,DefaultAllocator>::Element::~Element() (Nieznane źródło:0)
List<Pair<AnimationMixer *,Ref<AnimatedValuesBackup>>,DefaultAllocator>::Element::`scalar deleting destructor'(unsigned int) (Nieznane źródło:0)
memdelete_allocator<List<Pair<AnimationMixer *,Ref<AnimatedValuesBackup>>,DefaultAllocator>::Element,DefaultAllocator>(List<Pair<AnimationMixer *,Ref<AnimatedValuesBackup>>,DefaultAllocator>::Element * p_class) Line 124 (c:\godot_source\core\os\memory.h:124)
List<Pair<AnimationMixer *,Ref<AnimatedValuesBackup>>,DefaultAllocator>::_Data::erase(const List<Pair<AnimationMixer *,Ref<AnimatedValuesBackup>>,DefaultAllocator>::Element * p_I) Line 242 (c:\godot_source\core\templates\list.h:242)
List<Pair<AnimationMixer *,Ref<AnimatedValuesBackup>>,DefaultAllocator>::erase(const List<Pair<AnimationMixer *,Ref<AnimatedValuesBackup>>,DefaultAllocator>::Element * p_I) Line 429 (c:\godot_source\core\templates\list.h:429)
List<Pair<AnimationMixer *,Ref<AnimatedValuesBackup>>,DefaultAllocator>::clear() Line 463 (c:\godot_source\core\templates\list.h:463)
List<Pair<AnimationMixer *,Ref<AnimatedValuesBackup>>,DefaultAllocator>::~List<Pair<AnimationMixer *,Ref<AnimatedValuesBackup>>,DefaultAllocator>() Line 758 (c:\godot_source\core\templates\list.h:758)
EditorNode::_save_scene(String p_file, int idx) Line 1846 (c:\godot_source\editor\editor_node.cpp:1846)
EditorNode::_save_scene_with_preview(String p_file, int p_idx) Line 1676 (c:\godot_source\editor\editor_node.cpp:1676)
EditorNode::_menu_option_confirm(int p_option, bool p_confirmed) Line 2610 (c:\godot_source\editor\editor_node.cpp:2610)
EditorNode::_menu_option(int p_option) Line 1386 (c:\godot_source\editor\editor_node.cpp:1386)
call_with_variant_args_helper<EditorNode,int,0>(EditorNode * p_instance, void(EditorNode::*)(int) p_method, const Variant * * p_args, Callable::CallError & r_error, IndexSequence<0> __formal) Line 308 (c:\godot_source\core\variant\binder_common.h:308)
call_with_variant_args<EditorNode,int>(EditorNode * p_instance, void(EditorNode::*)(int) p_method, const Variant * * p_args, int p_argcount, Callable::CallError & r_error) Line 418 (c:\godot_source\core\variant\binder_common.h:418)
CallableCustomMethodPointer<EditorNode,int>::call(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 105 (c:\godot_source\core\object\callable_method_pointer.h:105)
Callable::callp(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 58 (c:\godot_source\core\variant\callable.cpp:58)
Object::emit_signalp(const StringName & p_name, const Variant * * p_args, int p_argcount) Line 1128 (c:\godot_source\core\object\object.cpp:1128)
Node::emit_signalp(const StringName & p_name, const Variant * * p_args, int p_argcount) Line 3607 (c:\godot_source\scene\main\node.cpp:3607)
Object::emit_signal<int>(const StringName & p_name, int <p_args_0>) Line 922 (c:\godot_source\core\object\object.h:922)
PopupMenu::activate_item(int p_idx) Line 2312 (c:\godot_source\scene\gui\popup_menu.cpp:2312)
PopupMenu::activate_item_by_event(const Ref<InputEvent> & p_event, bool p_for_global_only) Line 2224 (c:\godot_source\scene\gui\popup_menu.cpp:2224)
MenuBar::shortcut_input(const Ref<InputEvent> & p_event) Line 166 (c:\godot_source\scene\gui\menu_bar.cpp:166)
Node::_call_shortcut_input(const Ref<InputEvent> & p_event) Line 3132 (c:\godot_source\scene\main\node.cpp:3132)
SceneTree::_call_input_pause(const StringName & p_group, SceneTree::CallInputType p_call_type, const Ref<InputEvent> & p_input, Viewport * p_viewport) Line 1233 (c:\godot_source\scene\main\scene_tree.cpp:1233)
Viewport::_push_unhandled_input_internal(const Ref<InputEvent> & p_event) Line 3373 (c:\godot_source\scene\main\viewport.cpp:3373)
Viewport::push_input(const Ref<InputEvent> & p_event, bool p_local_coords) Line 3334 (c:\godot_source\scene\main\viewport.cpp:3334)
Window::_window_input(const Ref<InputEvent> & p_ev) Line 1553 (c:\godot_source\scene\main\window.cpp:1553)
call_with_variant_args_helper<Window,Ref<InputEvent> const &,0>(Window * p_instance, void(Window::*)(const Ref<InputEvent> &) p_method, const Variant * * p_args, Callable::CallError & r_error, IndexSequence<0> __formal) Line 303 (c:\godot_source\core\variant\binder_common.h:303)
call_with_variant_args<Window,Ref<InputEvent> const &>(Window * p_instance, void(Window::*)(const Ref<InputEvent> &) p_method, const Variant * * p_args, int p_argcount, Callable::CallError & r_error) Line 418 (c:\godot_source\core\variant\binder_common.h:418)
CallableCustomMethodPointer<Window,Ref<InputEvent> const &>::call(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 105 (c:\godot_source\core\object\callable_method_pointer.h:105)
Callable::callp(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 58 (c:\godot_source\core\variant\callable.cpp:58)
Callable::call<Ref<InputEvent>>(Ref<InputEvent> <p_args_0>) Line 850 (c:\godot_source\core\variant\variant.h:850)
DisplayServerWindows::_dispatch_input_event(const Ref<InputEvent> & p_event) Line 2716 (c:\godot_source\platform\windows\display_server_windows.cpp:2716)
DisplayServerWindows::_dispatch_input_events(const Ref<InputEvent> & p_event) Line 2686 (c:\godot_source\platform\windows\display_server_windows.cpp:2686)
Input::_parse_input_event_impl(const Ref<InputEvent> & p_event, bool p_is_emulated) Line 731 (c:\godot_source\core\input\input.cpp:731)
Input::flush_buffered_events() Line 995 (c:\godot_source\core\input\input.cpp:995)
DisplayServerWindows::process_events() Line 2401 (c:\godot_source\platform\windows\display_server_windows.cpp:2401)
OS_Windows::run() Line 1474 (c:\godot_source\platform\windows\os_windows.cpp:1474)
widechar_main(int argc, wchar_t * * argv) Line 182 (c:\godot_source\platform\windows\godot_windows.cpp:182)
_main() Line 204 (c:\godot_source\platform\windows\godot_windows.cpp:204)
main(int argc, char * * argv) Line 218 (c:\godot_source\platform\windows\godot_windows.cpp:218)
WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 232 (c:\godot_source\platform\windows\godot_windows.cpp:232)
[Inline Frame] invoke_main() Line 102 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:102)
__scrt_common_main_seh() Line 288 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
```
Hard crash not caught by the built-in crash handler. Happens when saving some scenes, I did not determine yet what kind of scenes.

Related to #85233 and #85093

### Steps to reproduce

1. Open scene (TBD what scene)
2. Save

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #85250
Fixes #85233

### CODE REVIEW

File: scene/animation/animation_mixer.cpp [hunk 1]
```diff
@@ -2138,3 +2138,80 @@ AnimationMixer::AnimationMixer() {
...
+	return ret;
+}
+
+void AnimatedValuesBackup::clear_data() {
+	for (KeyValue<NodePath, AnimationMixer::TrackCache *> &K : data) {
+		memdelete(K.value);
+	}
+	data.clear();
+}
+void AnimatedValuesBackup::copy_cache(AnimationMixer::TrackCache *p_from, AnimationMixer::TrackCache **p_to) const {
```
Comment (AThousandShips) [inline scene/animation/animation_mixer.cpp:2169]:
```suggestion

void AnimatedValuesBackup::copy_cache(AnimationMixer::TrackCache *p_from, AnimationMixer::TrackCache **p_to) const {
```

File: scene/animation/animation_mixer.cpp [hunk 2]
```diff
@@ -2138,3 +2138,82 @@ AnimationMixer::AnimationMixer() {
...
+	}
+	data.clear();
+}
+
+AnimationMixer::TrackCache *AnimatedValuesBackup::get_cache_copy(AnimationMixer::TrackCache *p_cache) const {
+	switch (p_cache->type) {
+		case Animation::TYPE_VALUE: {
+			AnimationMixer::TrackCacheValue *src = static_cast<AnimationMixer::TrackCacheValue *>(p_cache);
+			AnimationMixer::TrackCacheValue *tc = memnew(AnimationMixer::TrackCacheValue);
+			memcpy((void *)tc, src, sizeof(AnimationMixer::TrackCacheValue));
```
Comment (AThousandShips) [inline scene/animation/animation_mixer.cpp:2170]: I'm not sure it'll be safe to ignore this warning, I don't think it's overly careful saying not to memcpy virtual classes

Comment (KoBeWi) [reply scene/animation/animation_mixer.cpp]: How it should be handled otherwise?

Comment (AThousandShips) [reply scene/animation/animation_mixer.cpp]: With a copy constructor or copy assignment, as per the error suggestion I'd say

File: scene/animation/animation_mixer.cpp [hunk 3]
```diff
@@ -2138,3 +2138,82 @@ AnimationMixer::AnimationMixer() {
...
+			memcpy((void *)tc, (void *)src, sizeof(AnimationMixer::TrackCacheBlendShape));
+			return tc;
+		}
+
+		case Animation::TYPE_METHOD: {
+			AnimationMixer::TrackCacheMethod *src = static_cast<AnimationMixer::TrackCacheMethod *>(p_cache);
+			AnimationMixer::TrackCacheMethod *tc = memnew(AnimationMixer::TrackCacheMethod);
+			memcpy((void *)tc, (void *)src, sizeof(AnimationMixer::TrackCacheMethod));
+			return tc;
+		}
```
Comment (TokageItLab) [inline scene/animation/animation_mixer.cpp:2195]: I am not sure if this is necessary for backup. At least, it will be ignored on apply of reset, so I don't think it is a problem.

File: scene/animation/animation_mixer.cpp [hunk 4]
```diff
@@ -2138,3 +2138,82 @@ AnimationMixer::AnimationMixer() {
...
+			memcpy((void *)tc, (void *)src, sizeof(AnimationMixer::TrackCacheAudio));
+			return tc;
+		}
+
+		case Animation::TYPE_ANIMATION: {
+			AnimationMixer::TrackCacheAnimation *src = static_cast<AnimationMixer::TrackCacheAnimation *>(p_cache);
+			AnimationMixer::TrackCacheAnimation *tc = memnew(AnimationMixer::TrackCacheAnimation);
+			memcpy((void *)tc, (void *)src, sizeof(AnimationMixer::TrackCacheAnimation));
+			return tc;
+		}
```
Comment (TokageItLab) [inline scene/animation/animation_mixer.cpp:2216]: Same above.

**Review by TokageItLab — APPROVED** [review]
There is concern about the safety of memcpy with virtual above, but the major crash problem should have been resolved for now.

File: scene/animation/animation_mixer.cpp (hunk 2 above)
Comment (KoBeWi) [reply scene/animation/animation_mixer.cpp]: From what I understand, this is only a problem if we ever add a new cache type that inherits a *subtype* AND the new type will use an existing enum value. It's unlikely and that would be a bug in itself, so it's not really a concern IMO.

Comment (AThousandShips) [reply scene/animation/animation_mixer.cpp]: As long as the copying of the vtable is safe

Comment (KoBeWi) [reply scene/animation/animation_mixer.cpp]: The HashMap is not copied, it's recreated. Only the track cache pointers are copied.

Comment (AThousandShips) [reply scene/animation/animation_mixer.cpp]: How do you mean? The audio track cache has a hash map in it, how is it not copied?

Comment (TokageItLab) [reply scene/animation/animation_mixer.cpp]: If that is a problem, it may be safe not to copy for the audio, method, and animation tracks although I think the more problem is that the Reset track is allowed for them in the first place.

Comment (AThousandShips) [reply scene/animation/animation_mixer.cpp]: It's be safe to copy just as long as you do a copy and not just a raw copy of the memory, copying the memory stored in a hash map is unsafe as it uses raw data

File: scene/animation/animation_mixer.cpp (hunk 3 above)
Comment (KoBeWi) [reply scene/animation/animation_mixer.cpp:2195]: So how it should be handled? By adding an empty case? 🤔

Comment (TokageItLab) [reply scene/animation/animation_mixer.cpp:2195]: I think it's fine not to do anything so through to default, but for AudioTrack is special, perhaps resetting AudioStreamPolyphonic would be preferable.

Comment (TokageItLab) [reply scene/animation/animation_mixer.cpp:2195]: However, as far as Iooking `_build_backup_track_cache()`, I don't think these backup conversions will occur. We may not need to worry too much.

File: scene/animation/animation_mixer.cpp [hunk 5]
```diff
@@ -2138,3 +2138,67 @@ AnimationMixer::AnimationMixer() {
...
+			AnimationMixer::TrackCacheBezier *tc = memnew(AnimationMixer::TrackCacheBezier);
+			memcpy((void *)tc, (void *)src, sizeof(AnimationMixer::TrackCacheBezier));
+			return tc;
+		}
+
+		case Animation::TYPE_METHOD:
+		case Animation::TYPE_AUDIO:
+		case Animation::TYPE_ANIMATION: {
+			// Nothing to do here.
+		} break;
```
Comment (TokageItLab) [inline scene/animation/animation_mixer.cpp:2201]:
```suggestion
		case Animation::TYPE_AUDIO: {
			AnimationMixer::TrackCacheAudio *src = static_cast<AnimationMixer::TrackCacheAudio *>(p_cache);
			AnimationMixer::TrackCacheAudio *tc = memnew(AnimationMixer::TrackCacheAudio);
			memcpy((void *)tc, (void *)src, sizeof(AnimationMixer::TrackCacheAudio));
			return tc;
		}
		default: {
			// Nothing to do here.
		} break;
```
`Ref<AudioStream>()` is passed for reset.

`AnimationMixer::_build_backup_track_cache()`:
```cpp
			case Animation::TYPE_AUDIO: {
				TrackCacheAudio *t = static_cast<TrackCacheAudio *>(track);
				Node *asp = Object::cast_to<Node>(t->object);
				if (asp) {
					t->object->call(SNAME("set_stream"), Ref<AudioStream>());
				}
			} break;
```

File: scene/animation/animation_mixer.cpp (hunk 2 above)
Comment (AThousandShips) [reply scene/animation/animation_mixer.cpp]: I haven't tested it as I'm not able to right now but my assumption here is that the members of these classes are copied wholesale byte by byte, but the problem with that is that at least `HashMap` is going to be unsafe *if* it is copied that way, as it handles memory by pointers, in the "best" case the resulting copied map would share data with the original, which at minimum causes problems with manipulation of one, might cause crashes due to invalid pointer access in the worst case

I also am not sure it's safe to memcpy a `Ref` as it should do refcounting and I suspect you'd have a double-reference in two elements, so no additional referencing would happen, causing extra freeing

**Comment by akien-mga** [comment]
Tested on Linux with GCC, I confirm this fixes the MRP in #85233.

The concerns outlined by @AThousandShips above still need further consideration, but given that this seems to fix the crashes on Windows and Linux without apparent further regression, I'm merging it already to include into the 4.2-rc2 build I'm starting now.

Worse cast if there's some data corruption with the way hashmaps are copied, it shouldn't be worse than what we currently have before this PR. :sweat_drops:

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Crossing my fingers it won't cause any problems, not familiar enough with it to test it specifically, but the thing to look out for is likely data loss, and the likely most visible error would be the safety check failing in `SafeRefcount` due to duplication, without increment

File: scene/animation/animation_mixer.cpp (hunk 2 above)
Comment (RandomShaper) [reply scene/animation/animation_mixer.cpp]: I agree so much with @AThousandShips that I've made #85302.
