### PR TITLE
Fix missing tooltips on "Advanced Import Settings for Scene" window

### LINKED ISSUE #83484: Advanced mesh import dialogue missing parameter tooltips
### Godot version

4.2beta1

### System information

Godot v4.2.beta1 - macOS 13.6.0 - Vulkan (Mobile) - integrated Apple M2 Pro - Apple M2 Pro (10 Threads)

### Issue description

When trying to fix some mesh importing issues (looks like this issue https://github.com/godotengine/godot/issues/83240) I encountered an issue I think might be a bug/oversight:

When hovering over the different import options, they don't display the appropriate tooltips, explaining what they do. It just seems like they display the current heading name, like "Meshes" (hovering the new Force Disable Compression). This seems to apply to all the controls in the advanced panel, not just this new setting. 

Screenshot 2023-10-17 at 10 44 57

While if you hover the corresponding setting in the small import panel you get the appropriate tooltip (so they exist).

Screenshot 2023-10-17 at 10 45 16

I also noticed two other unexpected behaviors in this Advanced import panel, but I'm not sure if they're bugs:
- When changing a setting, the preview doesn't update to reflect this setting (which I'd assume was the point of the import panel?) For example toggling Force Disable Compression on fixes the normals in the model, but this isn't shown in the preview as you can see above.
- Clicking "Reimport" closes the panel, but the settings for the mesh in the regular small import panel aren't updated in case you've changed something (like Ensure tangents or Force Disable Compression), so it made me unsure if the changes in the Advanced import panel were applied.

### Steps to reproduce

Open the Advanced mesh import panel for a mesh. Hover over a parameter control.

### Minimal reproduction project

n/a editor interface issue

### PR DESCRIPTION
**Pull request by etherealxx**
Resolves #83484

This commit fixes a regression since 4.2 where settings in the inspector panel on the right part of the "Advanced Import Settings for Scene" window does not contain the same tooltips as its Import Dock counterpart (which were retrieved from the XML class reference).

Before (4.4.1.stable) :
image

After:
image

The fix are borrowed from the Import Dock code (`editor\import_dock.cpp`) that has the same tooltips.

Note: I don't think hard coding "ResourceImporterScene" as the object class is the best idea, perhaps those who knows the source better could help? Though i think it's safe for this case?

### CODE REVIEW

**Comment by etherealxx** [comment]
✅`clang-format`
✅`pre-commit` hook
```
clang-format.............................................................Passed
clang-format-glsl....................................(no files to check)Skipped
ruff.................................................(no files to check)Skipped
ruff-format..........................................(no files to check)Skipped
mypy.................................................(no files to check)Skipped
codespell................................................................Passed
make-rst.............................................(no files to check)Skipped
doc-status...........................................(no files to check)Skipped
eslint...............................................(no files to check)Skipped
jsdoc................................................(no files to check)Skipped
svgo.................................................(no files to check)Skipped
copyright-headers........................................................Passed
header-guards........................................(no files to check)Skipped
file-format..............................................................Passed
dotnet-format........................................(no files to check)Skipped
```

**Comment by AThousandShips** [comment]
What is this comment for? The check is listed below so there's no need to comment it here, it's just noisy

**Comment by etherealxx** [comment]
Sorry, it's my second PR, and my first has the same comment too and no one complained about it afaik. I thought i need to report the result of pre commit hook based on the docs. I'll hide it now.

**Review by fire — APPROVED** [review]
It looks good, but maybe editor people want to look.

File: editor/import/3d/scene_import_settings.cpp [hunk 1]
```diff
@@ -1891,6 +1891,9 @@ SceneImportSettingsDialog::SceneImportSettingsDialog() {
 	inspector = memnew(EditorInspector);
 	inspector->set_custom_minimum_size(Size2(300 * EDSCALE, 0));
 	inspector->connect(SNAME("property_edited"), callable_mp(this, &SceneImportSettingsDialog::_inspector_property_edited));
+	// Display the same tooltips as in the Import dock
+	inspector->set_object_class("ResourceImporterScene");
```
Comment (fire) [inline editor/import/3d/scene_import_settings.cpp:1895]: you can get class name from the class which is slightly better, but not really.

Comment (Calinou) [inline editor/import/3d/scene_import_settings.cpp:1895]: I've tested this locally and it works:

```suggestion
	// Display the same tooltips as in the Import dock.
	inspector->set_object_class(ResourceImporterScene::get_class_static());
```

It removes the dependency on a string which is prone to typos.

**Review by Calinou — COMMENTED** [review]
Tested locally, it works as expected.

**Review by Calinou — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
