### PR TITLE
Make `EditorInterface` accessible as a singleton

### LINKED ISSUE #68685: EditorPlugin singleton doesn't work
### Godot version

Godot 4 Beta 4

### System information

Windows 11/64, RTX 3070, Vulkan

### Issue description

The `EditorPlugin` singleton doesn't work. Or the documentation needs to be updated.

The [docs](https://docs.godotengine.org/en/latest/classes/class_editorinterface.html#class-editorinterface) say this:

`Note: This class shouldn't be instantiated directly. Instead, access the singleton using EditorPlugin.get_editor_interface.`

However if I write:
```
var ei: EditorInterface = EditorPlugin.get_editor_interface()
```

The editor reports this:

`SCRIPT ERROR: Parse Error: Cannot call non-static function "get_editor_interface()" on the class "EditorPlugin" directly. Make an instance instead.
          at: GDScript::reload (res://node_3d.gd:35)`

So I either have to make a class derived from EditorPlugin, which I don't wish to as I just want the editor camera position. Or I have to do what the docs say to not do:
```
var ei: EditorInterface = EditorPlugin.new().get_editor_interface()
```

For my terrain system I want it updating based on camera position in the editor. I'm not writing an editor plugin. I just want the position. I wrote this code segment to get the editor cameras outside of an EP:
https://github.com/godotengine/godot-proposals/issues/1302#issuecomment-1315180021

### Steps to reproduce

n/a

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by YuriSizov**
Supersedes https://github.com/godotengine/godot/pull/66109 and part of https://github.com/godotengine/godot/pull/68696. Closes https://github.com/godotengine/godot/issues/68685.

It was previously impossible to access this editor-specific singleton without first creating an instance of `EditorScript` or `EditorPlugin`. Which led to hacks, where users would create such instances ad-hoc in their tool scripts. And within the editor plugins you would need to carry a reference everywhere just to have this access. All while the `EditorInterface` object was internally a singleton, and accessible throughout the editor code directly.

So I made it a singleton officially, in the API. Naturally, like any other editor class it is only available in editor builds. So if you end up relying on it, guard your code accordingly.

godot windows editor dev x86_64_2023-04-05_17-05-44

In the future we could probably refine the exposed API more, make use of the editor-specific singletons more too.

### CODE REVIEW

**Comment by YuriSizov** [comment]
I initially wanted to preserve the `EditorPlugin.get_editor_interface` method as is, so that existing projects keep working. Unfortunately this is not possible due to singleton-related limitations. Both unit tests and the C# binding generator have a clause to err if we use a return type matching a singleton name. This seems to be because C# generates singletons as static classes, so this makes it impossible to use the same type as a return type.

This actually means that this PR breaks C# compatibility no matter what. Not sure how much of a problem we would consider that. Updating user projects to use the new API is trivial. But the ABI compatibility is just going to be broken regardless.

In the meantime, to make the tests pass and keep this compatible for GDScript at least, I'm changing the return type of the method to `Object`. This should keep working in GDScript as before, just without a good narrow type.

**Comment by neikeq** [comment]
For C# we could add a hard-coded list of singleton classes that must not be generated as static classes. That way we avoid breaking compat until the next major release.

The singleton could still be accessed globally via `(EditorInterface)Engine.GetSingleton("EditorInterface")` (we could also add a `Instance` property that does this).

File: editor/editor_run_script.h [hunk 1]
```diff
@@ -48,7 +50,7 @@ class EditorScript : public RefCounted {
 public:
 	void add_root_node(Node *p_node);
 	Node *get_scene();
-	EditorInterface *get_editor_interface();
+	Object *get_editor_interface();
```
Comment (neikeq) [inline editor/editor_run_script.h:53]: ditto

File: editor/editor_plugin.h [hunk 2]
```diff
@@ -265,7 +184,7 @@ class EditorPlugin : public Node {
 	virtual void edited_scene_changed() {} // if changes are pending in editor, apply them
 	virtual bool build(); // builds with external tools. Returns true if safe to continue running scene.
 
-	EditorInterface *get_editor_interface();
+	Object *get_editor_interface();
```
[the remark this answers is not in the document]
Comment (YuriSizov) [reply editor/editor_plugin.h:187]: The reason is explained in my comment above. It allows this PR to pass the tests and for C# bindings to generate without errors while we're trying to figure out how to best preserve compatibility here, if at all.

[the remark this answers is not in the document]
Comment (neikeq) [reply editor/editor_plugin.h:187]: Oh, I see. I'll make the changes I mentioned before, to avoid breaking compatibility in C#.

[the remark this answers is not in the document]
Comment (YuriSizov) [reply editor/editor_plugin.h:187]: Thanks, I appreciate it!

**Comment by YuriSizov** [comment]
We discussed the situation with @akien-mga and the rest of the production team a bit, and I think that it's better to break compatibility by removing the existing method than to create workarounds and hacks to make it work. For our end-users the changes would be minimal, but yes, they'd need to use some updated assemblies. On the plus side, the singleton introduced in this PR will work just like any other singleton, as a static class, convenient and consistent.

**Comment by neikeq** [comment]
I'd really prefer not to break compat. For Godot 5, I'll probably change the way we generate C# singletons to avoid this problem, but for Godot 4 it's better to go with a workaround.

Here's the patch I was referring to: https://github.com/neikeq/godot/commit/29a733c117cab7538f3c841c1529f063fddb57be. I can push it to your branch or make a follow-up PR (or you are welcome to just add them to your commit if you want). The class name has to be added to the list, so it's still possible to miss this in the future and accidentally break compat, but in the coming days I'll add a CI step to check for C# API compatibility.

**Comment by YuriSizov** [comment]
> I'd really prefer not to break compat.

Do you think it's worth preserving compatibility for a very small number of users who create editor plugins with C# by making the API inconsistent and overall coding experience for them worse?

The reason why we concluded that it's better to break backwards compatibility here is because the impact of it is small, but we avoid creating workarounds, hacks, and inconsistencies. In this case the benefit from preserving compatibility seems smaller than from keeping the API consistent.

**Comment by neikeq** [comment]
Unlike GDScript, breaking backwards compatibility in C# can have very negative results, like crashes. Just as it would be to break compatibility in GDExtension.

I don't think this inconsistency will be that annoying to the user considering new singletons classes should not be that common, at least until Godot 5.

I really wanted to take compatibility seriously for C# in Godot 4. We're going to have a CI step to ensure this, and I don't know if we can tell the .NET compat tool to ignore stuff.

**Comment by neikeq** [comment]
> We also can't really ensure ABI compatibility with such a vast API surface.

I don't see why we can't, as long as we have a CI check to ensure this. The question is whether or not we care.

> But there are going to be other changes that we have announced ahead of time. Some parts of the public API, marked as experimental, will be replaced and complete BC will not always be possible. Which is why we target a minor release for this, not a patch release.

I truly hope that doesn't end up being the case. I talked about this with @reduz a few times before, and there really seemed to be a commitment to ensure backwards compatibility. We even intended to add a CI check for 4.0. This didn't end up happening, but I'm going to add one for C#.

When you say some APIs are marked as experimental, do you mean that this is how we communicated it or is there an actual flag in ClassDB I can query to know whether an API is experimental?

> Bug fixes will also break compatibility, and already have, where incorrect types were specified for arguments and return values.

There are some types of changes I'm aware I can't really ask Godot not to make, and I have a plan to ensure they don't break C# ABI compatibility.

Since GDScript doesn't have method overloads, adding new optional parameters is the norm to avoid breaking GDScript compatibility. It does break C# compatibility though (and other languages), but I already have a solution for that (adding a method overload for each optional parameter).

Regarding the change of types in signatures. I think this already shows little interest in backwards compatibility, but if it's going to happen I can work on a solution within C# as well.

**Comment by neikeq** [comment]
> Edit: I can suggest we keep `EditorInterface` as is and expose a new singleton instead. This will result in a bit of an awkward API, but we will 100% preserve compatibility and will be free to design the new singleton as we need.

I don't see what's the problem with the patch to the C# bindings. It's simple and solves the issue (and won't be needed in Godot 5). Adding a new class for the singleton sounds worse than the slight inconsistency with `EditorInterface.Instance` (the latter is limited to C# as well, so it doesn't affect anyone else).

Not that I'm against doing that. I just think the C# patch seems less intrusive to the rest of the engine.

**Comment by RedworkDE** [comment]
TBH, I don't see how such a patch can be C# only, as yuri noted, gdscript doesn't like returning singleton instances either and third-party language bindings probably made similar design decisions and would need similar workarounds.

The easiest backwards compatible change would probably be to just add a static `get_instance` method to `EditorInterface` and then live with that weird 'singleton' rather than an even weirder 'singleton but not really' which every language has to work around.

---

Also I think C# is probably one of the better languages to break like this, since you generally get all the errors at compile time, rather than if that code actually gets executed. Also even if you load a precompiled binary, you get a pretty clear `MethodNotFoundException` instead of strange crashes. (Not that loading godot specific binaries is very useful right now, as you cant use scripts from it)

**Comment by neikeq** [comment]
> TBH, I don't see how such a patch can be C# only, as yuri noted, gdscript doesn't like returning singleton instances either and third-party language bindings probably made similar design decisions and would need similar workarounds.

I don't understand the part about GDScript. There may be some confusion there.

My patch can be C#-only because the compatibility issue is caused by how we implemented singletons in C#. We went with static classes because `Input.Instance` was deemed too verbose, and at the time there was no better way to shorten that (now we have global aliases, so we could use that in Godot 5).

Regarding other languages, Godot singletons are normal classes, and the constructor is not private (unlike the singleton pattern) so adding a new singleton doesn't necessarily break compatibility. But ultimately, it depends on how these third-party bindings implement singletons.

**Comment by RedworkDE** [comment]
GDScript: I was refering to this comment https://github.com/godotengine/godot/pull/75694#issuecomment-1497850251, but it turns out I was missremembering what exactly it said (I thought it meant that GDScript did not allow typing variables as singleton types)

My point was that given that the C# bindings make the assumption that for singletons only instance is useful and that there is no point in passing it around, other language bindings may make the same assumption and then would similar workarounds if we break that assumption.

**Comment by YuriSizov** [comment]
Since we are clearly not on the same page regarding BC at the moment, I'll mark this PR as a draft. We are planning to have a meeting about BC some time in a near future. In the meantime I'll make another version of this PR that only does the refactoring, as this currently blocks my further work on the editor node rework. This PR will be rebased on top of that to provide the necessary enhancements in a way that we can all agree to.

**Comment by YuriSizov** [comment]
Rebased and made changes necessary to preserve compatibility with C# bindings (cc @raulsntos). At the behest of the C# team, I kept the old `get_editor_interface` methods intact, but marked them as deprecated with an appropriate notice in the docs:

image

**Review by akien-mga — APPROVED** [review]
Looks good to me, if it gets the OK from the .NET team.

**Comment by YuriSizov** [comment]
Ah, right, we still have this check on the CI:

```
./tests/core/object/test_class_db.h:413: ERROR: CHECK_FALSE( return_class->is_singleton ) is NOT correct!
  values: CHECK_FALSE( true )
  logged: Method return type is a singleton: 'EditorPlugin.get_editor_interface'.

./tests/core/object/test_class_db.h:413: ERROR: CHECK_FALSE( return_class->is_singleton ) is NOT correct!
  values: CHECK_FALSE( true )
  logged: Method return type is a singleton: 'EditorScript.get_editor_interface'.
```

It exists specifically for C# I think, what do we want to do about it?

**Comment by akien-mga** [comment]
Would be good to evaluate how singleton access works in GDExtension too to make sure this is compatible.

**Comment by YuriSizov** [comment]
I (temporarily) removed the check for singletons. If we want to keep it, it needs to sync somehow with the list of compat singletons from C# bindings. But that may be better done as a separate C# API compatibility check rather than a general test for ClassDB.

File: doc/classes/EditorInterface.xml [hunk 3]
```diff
@@ -5,7 +5,7 @@
 	</brief_description>
 	<description>
 		[EditorInterface] gives you control over Godot editor's window. It allows customizing the window, saving and (re-)loading scenes, rendering mesh previews, inspecting and editing resources and objects, and provides access to [EditorSettings], [EditorFileSystem], [EditorResourcePreview], [ScriptEditor], the editor viewport, and information about scenes.
-		[b]Note:[/b] This class shouldn't be instantiated directly. Instead, access the singleton using [method EditorPlugin.get_editor_interface].
+		[b]Note:[/b] This class shouldn't be instantiated directly. Instead, access the singleton directly by its name.
```
Comment (raulsntos) [inline doc/classes/EditorInterface.xml:8]: I wonder if this line could be confusing for C# users, since they need to use the `Singleton` property. But it's a static property so they'll probably find it through IntelliSense.

File: doc/classes/EditorPlugin.xml [hunk 4]
```diff
@@ -245,15 +245,15 @@
...
+				    return EditorInterface.get_base_control().get_theme_icon("Node", "EditorIcons")
 				[/gdscript]
 				[csharp]
 				public override Texture2D _GetPluginIcon()
 				{
 				    // You can use a custom icon:
 				    return ResourceLoader.Load&lt;Texture2D&gt;("res://addons/my_plugin/my_plugin_icon.svg");
 				    // Or use a built-in icon:
-				    return GetEditorInterface().GetBaseControl().GetThemeIcon("Node", "EditorIcons");
+				    return EditorInterface.GetBaseControl().GetThemeIcon("Node", "EditorIcons");
```
Comment (raulsntos) [inline doc/classes/EditorPlugin.xml:256]:
```suggestion
				    return EditorInterface.Singleton.GetBaseControl().GetThemeIcon("Node", "EditorIcons");
```

File: doc/classes/EditorSettings.xml [hunk 5]
```diff
@@ -9,15 +9,15 @@
...
+		var settings = EditorInterface.get_editor_settings()
 		# `settings.set("some/property", 10)` also works as this class overrides `_set()` internally.
 		settings.set_setting("some/property", 10)
 		# `settings.get("some/property")` also works as this class overrides `_get()` internally.
 		settings.get_setting("some/property")
 		var list_of_settings = settings.get_property_list()
 		[/gdscript]
 		[csharp]
-		EditorSettings settings = GetEditorInterface().GetEditorSettings();
+		EditorSettings settings = EditorInterface.GetEditorSettings();
```
Comment (raulsntos) [inline doc/classes/EditorSettings.xml:20]:
```suggestion
		EditorSettings settings = EditorInterface.Singleton.GetEditorSettings();
```

**Review by raulsntos — APPROVED** [review]
Needs a few changes in the C# documentation, but otherwise looks good to me.

File: doc/classes/EditorInterface.xml (hunk 3 above)
Comment (YuriSizov) [reply doc/classes/EditorInterface.xml:8]: Good point, I'll clarify this.

**Comment by YuriSizov** [comment]
That's curious, but I'd rather look into it in a follow-up, if there are no other problems with this right now.

**Comment by dsnopek** [comment]
> Would be good to evaluate how singleton access works in GDExtension too to make sure this is compatible.

From the perspective of GDExtension in isolation, I think this is fine. I don't think there's anything in the GDExtension interface that would have a problem with a singleton instance being returned by an ordinary method.

However, similar to the problems that came up for C#, there may be specific GDExtension bindings (like godot-cpp, godot-rust, etc) that made the assumption that singleton instances can't be passed around and exposed them like static classes, and this could break their code generators. I think this should be fine for godot-cpp - I just tried building it with the `extension_api.json` from this patch and the automated tests passed.

Personally, I'd be fine with making this change even if some GDExtension bindings would need to update their code generators. This won't break binary compatibility and we never really promised that singletons couldn't be passed as instances. But this is probably something that more GDExtension team members should weight in on!

/cc @vnen @Faless @BastiaanOlij

**Comment by Bromeon** [comment]
Thanks for the mention! In godot-rust, we currently treat singletons like regular instances, so it should be OK right now. We have been considering to move towards static-method syntax, and for that it's good to consider cases like this one 👍

**Comment by YuriSizov** [comment]
> not sure why/if this could happen

Since in the engine singletons are just your normally instanced classes with a static instance reference, it can happen quite easily. In fact, there are some classes that can be freely instantiated while also having a singleton reference.

That's unlikely to be needed in the public API, but not impossible.
