### PR TITLE
Fix project settings not properly saved after a file deletion

### LINKED ISSUE #95260: Improper saving of the project after deleting the main scene
### Tested versions

- 4.3 rc 2

### System information

Windows 11

### Issue description

When you delete the main scene and then save the Project > Run configuration shows it has saved by clearing the value, but it is not.
Now if you reopen the project, the run configuration will have the value of the deleted scene. 

### Steps to reproduce

Create a Project and a Scene
Set the Scene as Main Scene and Save the Scene and Project
Now delete the Main Scene in the file system editor
Save project 
Do not save the Scene if it is opened, otherwise file will be recreated
Now check the configuration Project Settings >> Application >> Run >> Main Scene property will be empty. indicating it cleared the value.
Now restart the project., by closing and opening again
check the configuration Project Settings >> Application >> Run >> Main Scene property will have the value of the delete scene.
No errors shown in the output window

Now in some complicated cases where you delete multiple files, then it will cause some error that file not found in output window.

### Minimal reproduction project (MRP)

Not Required, but if needed will be provided

### PR DESCRIPTION
**Pull request by Lunarisnia**
Fixes #95260

### CODE REVIEW

File: editor/dependency_editor.cpp [hunk 1]
```diff
@@ -578,32 +578,41 @@ void DependencyRemoveDialog::ok_pressed() {
 		}
 	}
 
+	bool project_settings_modified = false;
```
Comment (akien-mga) [inline editor/dependency_editor.cpp:581]: I would refactor a bit to avoid redundancy:
```cpp
bool project_settings_modified = true;
for (int i = 0; i < files_to_delete.size(); ++i) {
	// If the file we are deleting for e.g. the main scene, default environment,
	// or audio bus layout, we must clear its definition in Project Settings.
	const String &file = files_to_delete[i];
	if (file == String(GLOBAL_GET("application/config/icon"))) {
		ProjectSettings::get_singleton()->set("application/config/icon", "");
	} else if (file == String(GLOBAL_GET("application/run/main_scene"))) {
		ProjectSettings::get_singleton()->set("application/run/main_scene", "");
	} else if (  ...
... etc.
	} else {
		project_settings_modified = false;
	}
```

Comment (Lunarisnia) [reply editor/dependency_editor.cpp:581]: I don't think setting the bool to false only when no match is found fixes this since this method is being called anytime a file is removed not just one that has ties to project settings. This would cause issue when the user is deleting multiple files and one of them is not related to any of these fields depending on the order of how the file is processed it would cause the same issue.

I have also tested and confirmed this approach produce the same bug when deleting multi files.

Comment (akien-mga) [reply editor/dependency_editor.cpp:581]: I'm pretty sure the approach I suggest is strictly equivalent to the current code.
- Current code is: Assume false, if there's a match, set to true.
- My suggestion: Assume true, if there's no match, set to false.

This should lead to the same state at the end of the big `if`/`else if`/`else` block, as there can be only two options:
- Either there's a match, and it will stay `true`
- Or there's no match, it enters the `else`, and becomes `false`

Comment (akien-mga) [reply editor/dependency_editor.cpp:581]: Well there's one case where my approach would lead to different behavior, which is if the `for` loop never runs, i.e. `files_to_delete.size() == 0`.

I don't know if this can happen, but that's right, let's keep the defensive form then.

**Review by akien-mga — APPROVED** [review]

File: editor/dependency_editor.cpp (hunk 1 above)
Comment (Lunarisnia) [reply editor/dependency_editor.cpp:581]: The issue happens if we assume this value for `files_to_delete` with your approach
["the_main_scene", "completely_unrelated_file"]

The first iteration will leave the flag at `true`, and then the 2nd iteration will set it to `false` and then no actual save will happen since I only save after loop has finished and the flag is final.
https://github.com/godotengine/godot/blob/138bcc7cfdbddcc05a4f2373fb2cb20fb23e0f2b/editor/dependency_editor.cpp#L617-L622

Comment (akien-mga) [reply editor/dependency_editor.cpp:581]: You're totally right. Thanks for bearing with me :D

Comment (Lunarisnia) [reply editor/dependency_editor.cpp:581]: Cheers! 🍺

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.
