### PR TITLE
Fix animation editor snapping value not lowering as intended when holding shift

### LINKED ISSUE #98609: Animation editor key snapping is rounded to some predetermined value instead of using exact snap value
### Tested versions

- Reproducible in : 4.4.dev3, 4.4.dev2
- Not reproducible in : 4.2.2.stable

### System information

Windows 11 - Godot v4.4.dev3

### Issue description

When you set time snap value in animation editor and you try to create or move key, the result key time value is rounded to some predetermined value instead of using exact number to snap.
Some examples:
- If snap value is 0.15, key is actually snapped to value 0.1429
- If snap value is 0.225 or 0.275, key is actually snapped to value 0.25
- If snap value is 0.3 or 0.4, key is actually snapped to value 0.3333333...
- If snap value is from 0.45 to 0.75, key is actually snapped to value 0.5
- If snap value is bigger than 0.75, key is actually snapped to value 1
The same rules apply for any integer value like 2.225 is snapped to 2.25, or 4.3 is snapped to 4.33333...

Note that timeline cursor doesn't have this issue and it snaps correctly to exact snap value, no matter how much decimal part is.

### Steps to reproduce

1.) Create AnimationPlayer, some Sprite or ColorRect, and create some simple moving animation for it
2.) Try to set snapping value to 0.25, 0.3, 0.425, 0.45 and 0.75 and try to create new key or move existing one and see that it snaps to incorrect value, while timeline cursor is moving correctly (when timeline cursor snap is enabled)

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/user-attachments/files/17541034/MRP.zip)

### PR DESCRIPTION
**Pull request by UnfavorableEnhancer**
Closes #98609 
I have no idea what weird piece of code in "_update_snap_unit()" which breaks snapping was meant to do, but my guess is that it was made for limiting fractional part so I've replaced it with snapped() function.
Also fixed holding shift not lowering snap value as intended.

### CODE REVIEW

**Comment by fire** [comment]
@TokageItLab, does anyone remember what this is? 

I am satisfied with merging this once we know the reason or someone can prove the new code does the same thing as the existing code.

**Comment by TokageItLab** [comment]
As far as I remember, the original problem was that the FPS mode values were not restored correctly by precision when serialized to tscn.

As for modf(), it was implemented follow for snapping when using values above 1s:
- https://github.com/godotengine/godot/pull/96328
  - issue by https://github.com/godotengine/godot/issues/96159

The 0.0625 snap is due to the fix in:
-  https://github.com/godotengine/godot/pull/97569
  - issue by https://github.com/godotengine/godot/issues/97548

Then, two approaches are mixed here, which may create some confusion.

I think this PR would be okay if the following test results are correct:

- [ ] Save tscn in FPS mode and restart Godot, the snap values should be restored correctly
- [ ] Save tscn in Second mode and restart Godot, the snap value is restored correctly
- [ ] In second mode, larger than 1.0s snap value is working correctly
- [ ] When switching between Second mode and FPS mode with a snap value of 1.0s or less, the snap value is not corrupted 
- [ ] When switching between Second mode and FPS mode with a snap value of larget than 1.0s, the snap value is not corrupted

File: editor/animation_track_editor.cpp [hunk 1]
```diff
@@ -7319,27 +7319,26 @@ void AnimationTrackEditor::_update_snap_unit() {
...
 
 	if (timeline->is_using_fps()) {
-		snap_unit = 1.0 / step->get_value();
+		snap_unit = Math::snapped(1.0 / step->get_value(), FPS_STEP_FRACTION);
 	} else {
-		double integer;
-		double fraction = Math::modf(step->get_value(), &integer);
-		fraction = 1.0 / Math::round(1.0 / fraction);
-		snap_unit = integer + fraction;
+		snap_unit = Math::snapped(step->get_value(), SECOND_DECIMAL);
```
Comment (TokageItLab) [inline editor/animation_track_editor.cpp:7324]: Will a snap of 0.333 accumulate correctly?
I remember that the modf was needed so that when 0.333 was accumulated 3 times, it would snap to 1.0 instead of 0.999.

**Review by TokageItLab — CHANGES_REQUESTED** [review]
As I described in https://github.com/godotengine/godot/issues/98609#issuecomment-2456985645, probably this fix should only be applied when the snapping value is 1.0s or greater. Also, I think we need to document snaps less than 1.0 (although we can separate the documentation PR from this IMO).

@fire @lyuma Should glTF baking on import also take into account the 1.0s interval?

**Comment by UnfavorableEnhancer** [comment]
> As I described in [#98609 (comment)](https://github.com/godotengine/godot/issues/98609#issuecomment-2456985645), probably this fix should only be applied when the snapping value is 1.0s or greater. Also, I think we need to document snaps less than 1.0 (although we can separate the documentation PR from this IMO).
> 
> @fire @lyuma Should glTF baking on import also take into account the 1.0s interval?

I don't really like idea of ignoring values below 1.0s. Code which was before equally breaked snap values both above 1.0s and below 1.0s (Quoting myself: The same rules apply for any integer value like 2.225 is snapped to 2.25, or 4.3 is snapped to 4.33333...).
And I think that rounding snap values at all is a bad practice, since sometimes you need a precise snap value to make your animation correctly (for example my game uses a lot of music BPM tied animations, so I quite oftenly use quite precise float values like 0.432 or 5.393 to sync animation keys to the music), and overall game engine should allow for any possibilities, not limit them.

But now I see that the root of the problem is FPS to seconds convertion things and will try to do something with it.

**Comment by TokageItLab** [comment]
I understand that some people need precise snapping for music, but there are users who want to use Second mode while prioritizing FPS for animation.

Therefore, I think that for the most compatible and safe solution, we need to add FPS compatible mode as an option for Second mode, as in Approach 3 described there https://github.com/godotengine/godot/issues/98609#issuecomment-2456985645.

**Comment by UnfavorableEnhancer** [comment]
just did little fix for this PR
I've realized that adding "snapped" functions was actually a bad idea, it introduced some accumulation issues in fps mode and it also snapped to incorrect values
so I've checked everything and all is working fine now, but accumulation error still occur when you work in seconds mode, so adding a special toggle for fixing it, is actually a good idea, but I kinda think that it might be out of scope of this PR

**Comment by fire** [comment]
The animation frame snapping code is fragile, so don't worry if we're nit-picking over the design.

**Comment by TokageItLab** [comment]
I sent a PR #99013 for 4.4 which partially supersedes this PR.

So, since there are two fixes in this PR, can you separate only the fix for the pressing Shift behavior for 4.4? The Second mode fix must be removed from this PR and sent separately in the as new PR as cherry-pick for 4.3.

**Review by TokageItLab — APPROVED** [review]

**Comment by TokageItLab** [comment]
@UnfavorableEnhancer Alright, please fixup this PR into one commit to follow [PR workflow](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase.)

**Comment by UnfavorableEnhancer** [comment]
Reverted changes and created new PR for 4.3 branch here #99058

**Comment by UnfavorableEnhancer** [comment]
Fixed-up into single commit

**Comment by TokageItLab** [comment]
Yes, if you really want to fix that, perhaps a different approach is needed, as we mentioned in https://github.com/godotengine/godot/issues/97548#issuecomment-2468960497.

For now, this PR now only fixes the bug in the snapping behavior when Shift is pressed, so it can be merged.

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first contribution! 🎉
