### PR TITLE
Fixes variable nodes not showing updated name in visualscript editor

### LINKED ISSUE #59449: Variable/signal nodes are not renamed in VisualScript editor (fixed in `master`)
### Godot version

3.x

### System information

Any system

### Issue description

This issue has been fixed for `Godot 4`(#55291). but it still remains in `3.x`. Please refer to [this](https://github.com/godotengine/godot/issues/55265) for complete description.

### Steps to reproduce

- Create a variable in visual script editor
- Drop a setter/getter node into the graph
- Rename the that variable
- By default, all the nodes should be renamed.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by theoway**
Fixes #59449
_Due to different API `master` & `3.x`, separate PR has been made._ 

*Bugsquad edit:* `3.x` equivalent to #55291.

**Bug reason:**
`variable` and `custom_signal` nodes are not properly tracked by the `visual_script`, unlike `function` nodes.  This PR fixes that and also fixes whenever a `variable` is renamed, all of it's corresponding nodes are updated and show the new name.

**To produce the bug:**
- Create a variable in Visual Script Editor
- Drag and drop a setter/getter node of that variable
- Rename the variable in the editor
- The name of the existing setter/getter variable node does not change - (_Bug_)
- If you drop another setter/getter node of the same variable, that node will display the updated name. But the old node will not do the same.

**Results:**
_As you can see, now the new name of the variable is updated in the existing variable getter/setter nodes that are in the editor_

https://user-images.githubusercontent.com/41969735/162732898-e664ebde-f0c1-46c1-8ff1-5710fc9eb283.mp4

**Note:**
**Since it is a major change, this PR only fixes it for variable nodes**. **A separate PR has to be made for `custom_signal` nodes**

### CODE REVIEW

File: modules/visual_script/visual_script.cpp [hunk 1]
```diff
@@ -291,80 +292,113 @@ void VisualScript::_node_ports_changed(int p_id) {
...
-	nd.pos = p_pos;
+			func.function_id = p_id;
+		}
 
+		Function::NodeData nd;
+		nd.node = p_node;
+		nd.pos = p_pos;
+		func.nodes[p_id] = nd;
+	}
+
```
Comment (akien-mga) [inline modules/visual_script/visual_script.cpp:334]: There seems to be trailing whitespace on this line (select diff to see it): https://github.com/godotengine/godot/runs/5821764351?check_suite_focus=true

Comment (theoway) [reply modules/visual_script/visual_script.cpp]: Oops! I forgot to format before pushing :)

**Comment by fire** [comment]
Asked for a test plan / testing procedure from @theoway.

**Comment by theoway** [comment]
> Asked for a test plan / testing procedure from @theoway.

@fire Details and demo have been added to the PR description as requested.

File: modules/visual_script/visual_script.cpp [hunk 2]
```diff
@@ -291,80 +292,113 @@ void VisualScript::_node_ports_changed(int p_id) {
...
+		Variable &var = variables[var_name];
+		var.nodes[p_id] = p_node;
+	}
 
-	if (Object::cast_to<VisualScriptFunction>(*p_node)) {
-		//the function indeed
-		ERR_FAIL_COND_MSG(func.function_id >= 0, "A function node has already been set here.");
+	if (functions.has(p_name)) {
+		for (Map<StringName, Function>::Element *E = functions.front(); E; E = E->next()) {
+			ERR_FAIL_COND(E->get().nodes.has(p_id)); //id can exist only one in script, even for different functions
```
Comment (fire) [inline modules/visual_script/visual_script.cpp:318]: Comments are usually written. `// This is a comment.` style see the contributor docs.

**Review by fire — APPROVED** [review]
Looks good. Can you also check if the pointers are valid before use?

File: modules/visual_script/visual_script.cpp [hunk 3]
```diff
@@ -291,80 +292,113 @@ void VisualScript::_node_ports_changed(int p_id) {
...
-	for (Map<StringName, Function>::Element *E = functions.front(); E; E = E->next()) {
-		ERR_FAIL_COND(E->get().nodes.has(p_id)); //id can exist only one in script, even for different functions
+	StringName var_name;
+	if (Object::cast_to<VisualScriptVariableGet>(*p_node)) {
+		Ref<VisualScriptVariableGet> vget = p_node;
+		var_name = vget->get_variable();
+	} else if (Object::cast_to<VisualScriptVariableSet>(*p_node)) {
+		Ref<VisualScriptVariableSet> vset = p_node;
+		var_name = vset->get_variable();
 	}
```
Comment (fire) [inline modules/visual_script/visual_script.cpp:306]: p_node can be invalide here.

Comment (theoway) [reply modules/visual_script/visual_script.cpp:306]: `ERR_FAIL_COND(p_node.is_null());`
This error macro takes care of this

File: modules/visual_script/visual_script.cpp (hunk 2 above)
Comment (theoway) [reply modules/visual_script/visual_script.cpp:318]: These are old comments. Nonetheless, I'll update them 👍

Comment (theoway) [reply modules/visual_script/visual_script.cpp]: Updated the comments as per contributor guidelines

Comment (fire) [reply modules/visual_script/visual_script.cpp]: The end punctuation is required.

**Comment by akien-mga** [comment]
Thanks!
