### PR TITLE
Particles: Fix missing configuration warning updates

### LINKED ISSUE #33488: Configuration warnings not updated correctly for (CPU)Particles(2D)
**Godot version:**
Master 0ab0d11c17dd58ac35335cabd032409c42a41a94

**OS/device including version:**
Windows 10

**Issue description:**
Some changes in meshes, render materials and particle materials are not immediately reflected in configuration warnings for `Particles`, `CPUParticles`, `Particles2D` & `CPUParticles2D`.
The only way to see updated warnings in these cases is to deselect everything from the scene tree.

**Steps to reproduce:**
Example with `CPUParticles`:
1. Create a node of type `CPUParticle`
2. Observe warning:
`Nothing is visible because no mesh has been assigned`
3. Assign a new mesh to `Drawing/Mesh` property
4. Observe the warning is still displayed
5. Set a positive value to `Animation/Speed` property
6. Observe the same warning is still displayed
7. Deselect everything from the scene tree
8. Observe the new updated warning:
`CPUParticles animation requires the usage of a SpatialMaterial whose Billboard Mode is set to "Particle Billboard"`

**Minimal reproduction project:**
Easy to reproduce in any project.

### PR DESCRIPTION
**Pull request by akien-mga**
- Fixes #33488, by calling updates where relevant.
- Supersedes #33489 - that convoluted update logic was likely required back then but now the Inspector is more clever.

### CODE REVIEW

File: scene/2d/gpu_particles_2d.cpp [hunk 1]
```diff
@@ -141,7 +141,6 @@ void GPUParticles2D::set_process_material(const Ref<Material> &p_material) {
 void GPUParticles2D::set_trail_enabled(bool p_enabled) {
 	trail_enabled = p_enabled;
 	RS::get_singleton()->particles_set_trails(particles, trail_enabled, trail_length);
-	update_configuration_warnings();
```
Comment (akien-mga) [inline scene/2d/gpu_particles_2d.cpp:144]: This one was copied from the 3D implementation which does have a warning, but there's no matching warning in 2D.
