### PR TITLE
fix: "Reload Current Project" prompts the user to open Project Manager

### LINKED ISSUE #60783: "Reload Current Project" prompts the user to open Project Manager
### Godot version

3.5 Beta 5

### System information

Windows 10

### Issue description

Reloading the current project asks the user if they want to open the Project Manager, despite it having not much to do with the operation.
bfdb3880b6d18810abfd0756d8fdc9bc

Clicking on "Yes" reloads the project just fine, without ever showing the Project Manager.

This does **not** happen in Godot 3.3.3. The project reloads without any prompt.

### Steps to reproduce

Click on Project on the top-left, then click on "Reload Current Project".

### Minimal reproduction project

No need.

### PR DESCRIPTION
**Pull request by RedHeadphone**
fixes #60783

### CODE REVIEW

**Comment by RedHeadphone** [comment]
sorry wrong fix

**Review by ghost — APPROVED** [review]

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -2715,7 +2715,7 @@ void EditorNode::_menu_option_confirm(int p_option, bool p_confirmed) {
 					bool confirm = EDITOR_GET("interface/editor/quit_confirmation");
 					if (confirm) {
 						confirmation->get_ok()->set_text(p_option == FILE_QUIT ? TTR("Quit") : TTR("Yes"));
-						confirmation->set_text(p_option == FILE_QUIT ? TTR("Exit the editor?") : TTR("Open Project Manager?"));
+						confirmation->set_text(p_option == FILE_QUIT ? TTR("Exit the editor?") : TTR("Reload Current Project?"));
```
Comment (akien-mga) [inline editor/editor_node.cpp:2718]: That's not correct when using `RUN_PROJECT_MANAGER`. There are three possible options which should all have their wn text.

**Comment by Mickeon** [comment]
Does it really fix this? Feel free to correct me, but I find the commit "Made reload current project ask for confirmation with unsaved changes" https://github.com/godotengine/godot/commit/8d1827cf7c50b6cc5915eec75917e7b231be196c to be the cause of it. It is done in good faith, but the confirmation dialog does appear on reload even if there's **no** unsaved changes at all.

**Comment by RedHeadphone** [comment]
@Mickeon So do I remove the confirmation if all files are saved?

**Comment by Mickeon** [comment]
I suppose so, yeah. As you've mentioned, this problem is not present in `master`

**Comment by Vitika9** [comment]
> @Mickeon So do I remove the confirmation if all files are saved?

Use if else statement https://github.com/godotengine/godot/blob/3.x/editor/editor_node.cpp#L2718

**Comment by Vitika9** [comment]
If you are removing the confirmation then you have to remove interface/editor/quit_confirmation too, as now its of no use.

**Comment by Vitika9** [comment]
see https://github.com/godotengine/godot/pull/32321

**Comment by akien-mga** [comment]
That seems to go a bit over the scope of the issue it was trying to solve. This is removing the quit confirmation for quitting the editor in all cases.

**Comment by RedHeadphone** [comment]
So do I remove quit confirmation only when reloading project when files are saved? @akien-mga

**Comment by akien-mga** [comment]
Yes, I think that would be the proper fix. You just need to check `if (p_option != RELOAD_CURRENT_PROJECT) { [quit confirmation] }` as done elsewhere in this multi-use case.

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -2712,11 +2712,16 @@ void EditorNode::_menu_option_confirm(int p_option, bool p_confirmed) {
 			if (!p_confirmed) {
 				bool save_each = EDITOR_GET("interface/editor/save_each_scene_on_quit");
 				if (_next_unsaved_scene(!save_each) == -1) {
-					bool confirm = EDITOR_GET("interface/editor/quit_confirmation");
-					if (confirm) {
-						confirmation->get_ok()->set_text(p_option == FILE_QUIT ? TTR("Quit") : TTR("Yes"));
-						confirmation->set_text(p_option == FILE_QUIT ? TTR("Exit the editor?") : TTR("Open Project Manager?"));
-						confirmation->popup_centered_minsize();
+					if (p_option != RELOAD_CURRENT_PROJECT) {
+						bool confirm = EDITOR_GET("interface/editor/quit_confirmation");
```
Comment (akien-mga) [inline editor/editor_node.cpp:2716]: Another option would be to directly do:
```suggestion
						bool confirm = (p_option != RELOAD_CURRENT_PROJECT) && EDITOR_GET("interface/editor/quit_confirmation");
```
So you don't need to duplicate the `else` branch.

Comment (akien-mga) [reply editor/editor_node.cpp:2716]: Then be sure to squash the commits so that the PR is ready to merge (see [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase)).

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
