### PR TITLE
Skip swapchain logic if there is nothing to present (Android OpenXR)

### LINKED ISSUE #74963: Android/Quest suboptimal swapchain error
### Godot version

4.0.stabl

### System information

Android - Meta Quest 2

### Issue description

When running a project on a Quest 2 using the Vulkan renderer (I believe there is no difference between mobile and clustered Vulkan renderer) the log gets filled with these repeated errors:

```
Vulkan: Early out of date swapchain, recreating.
Vulkan queue submit: Swapchain is suboptimal.
Vulkan: Early out of date swapchain, recreating.
Vulkan queue submit: Swapchain is suboptimal.
```

While discovered on the Quest this issue may not be limited to this device.

Need to investigate the origin of these errors. My current theory is that this may be the swap chain the renderer creates by default for outputting to screen. This swap chain is unused (as when using XR the XR Runtime is responsible for output to the device) but still maintained.

### Steps to reproduce

Run a project on a Meta Quest (2)

### Minimal reproduction project

The demo in XR tools can be used for this: https://github.com/GodotVR/godot-xr-tools

### PR DESCRIPTION
**Pull request by BastiaanOlij**
When we are running XR in standalone mode (e.g. OpenXR on Android such as Quest, Lynx, ML2, etc) output to screen is handled by OpenXR however Godot still creates and attempts to display it's build in swapchain for normal output. This is causing a bundle of issues from warnings being spammed (suboptimal swapchain), outright failures (device lost), to simply an empty swapchain overwriting whatever was rendered to screen by OpenXR.

This PR solves that issue by having Godot skip it's normal output if nothing is being blit to screen (e.g. there is no output because the output has been redirected).

Testing so far has removed the issues I was having on Quest Pro, awaiting feedback to see if this solves more serious issues on Quest 3 and ML2. It also shaved 1ms of overhead per frame.

For GLES3 I had to introduce a proper `end_viewport` to get the logic to work correctly. 

Test project:
https://www.dropbox.com/scl/fi/htl04po1ylfex3k64e1c9/TestXRv2.zip?rlkey=l7t9nmpwtlt44o5ogbib3xr8w&dl=0
(requires android build templates to be compiled and installed)

Fixes #74963

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
This may make #74754 unnecessary

File: drivers/vulkan/vulkan_context.cpp [hunk 1]
```diff
@@ -2468,7 +2468,7 @@ Error VulkanContext::prepare_buffers() {
 	return OK;
 }
 
-Error VulkanContext::swap_buffers() {
+Error VulkanContext::swap_buffers(bool p_present) {
```
Comment (RandomShaper) [inline drivers/vulkan/vulkan_context.cpp:2471]: Conceptually, swapping buffers involves presenting. This would be a bit confusing. Wouldn't `flush(true, true)` would the right thing to call instead of `swap_buffers(false)` when there's no intention to present?

Comment (BastiaanOlij) [reply drivers/vulkan/vulkan_context.cpp:2471]: Yeah I was thinking about splitting it or something. I'm going from the old situation where this existing function both flushes the command queue and does the swap + present, to it only doing the flush.
So maybe have a function called `flush` and then `swap_buffers`? It would clean up the change log a lot too as I don't need to indent all the code.

**Comment by trent-waddington** [comment]
Tested on Quest 3. Both debug and release templates are working with your test case.

File: drivers/vulkan/vulkan_context.cpp (hunk 1 above)
Comment (BastiaanOlij) [reply drivers/vulkan/vulkan_context.cpp]: I ended up just creating a separate method with just the flush of the buffers. Should look into if the existing `flush` method does a similar thing and shouldn't be used instead, I'm not sure enough about whats going on here

Comment (RandomShaper) [reply drivers/vulkan/vulkan_context.cpp]: Your new `flush_buffer()` function still detals present-related concerns. I'm certain that `flush(true, true)` will do the trick.

Comment (BastiaanOlij) [reply drivers/vulkan/vulkan_context.cpp]: Seems to work but I did get a small performance penalty, so I am worried about the device wait idle that we're introducing. Is it really required to wait for that or can we make that optional?

Comment (RandomShaper) [reply drivers/vulkan/vulkan_context.cpp]: Oh, those waits totally break CPU-GPU parallelism... Sorry for the bad idea. I'd still leverage `flush()`, though. What do you think about adding a third `bool p_sync = true` parameter. `vkDeviceWaitIdle()`s will happen only if `true`. For this usage of yours, you'd pass `false`, of course.

Comment (BastiaanOlij) [reply drivers/vulkan/vulkan_context.cpp]: Ah, that makes perfect sense, yeah I will add the `p_sync`, thats an easy fix

Comment (BastiaanOlij) [reply drivers/vulkan/vulkan_context.cpp]: Didn't seem to make a lot of difference but I'm still around the 9ms frame time with my example project.

**Comment by BastiaanOlij** [comment]
Just some extra info here for reviewers and the production team.

This was always an annoyance on Quest 2 and Pro, but on Quest 3 without this fix you can't run a Vulkan game. So far the feedback I've had is that compatibility works fine. I should be able to test this myself soon and add some extra feedback.

**Review by clayjohn — APPROVED** [review]
Looks good to me. I tested locally on a non-XR project and can't see any regressions. 

Would be good to hear from someone with a Quest 3 about whether this fixes the issue we are having there.

**Comment by BastiaanOlij** [comment]
> Would be good to hear from someone with a Quest 3 about whether this fixes the issue we are having there.

I've had feedback from several users on the XR discord that it does, but they don't tent to come here on github.

**Comment by clayjohn** [comment]
Note for merging: this should be merged after https://github.com/godotengine/godot/pull/83452. Bastiaan has some small fixups related to this PR to make it work well with the RDD changes. It makes sense to do those fixups directly on this PR after merging https://github.com/godotengine/godot/pull/83452

**Comment by akien-mga** [comment]
> Note for merging: this should be merged after #83452. Bastiaan has some small fixups related to this PR to make it work well with the RDD changes. It makes sense to do those fixups directly on this PR after merging #83452

If this is wanted for 4.2 and 4.1 cherrypicks, a dedicated PR with the current version would likely need to be made against the `4.2` branch then, as we won't be able to cherry-pick the change after it has been rebased on top of RDD.

**Comment by dsnopek** [comment]
If this issue really is preventing Quest 3 from using Vulkan (I have a Quest 3 - I'll try to test this when I have a chance :-)), then I think we really should try to get a version of this PR cherry-picked into 4.2. Most folks deploying to Quest are using the compatibility renderer (myself included), but having Vulkan supported on Quest 1, Quest 2, Quest Pro, but _not_ Quest 3, would be unfortunate.

**Comment by dsnopek** [comment]
Hm, I'm not entirely sure how to trigger the Quest 3 issue. Using Godot 4.2-stable (so without this PR), I tried switching one of my projects from gl_compatibility to mobile, and I ran it 3 times on the Quest 3 (only playing for about 20-30 seconds each time) and everything seemed to work fine. And there were no messages in the log like those described in issue https://github.com/godotengine/godot/issues/74963

Is this something that only happens some percentage of the time? Or, only after the app runs for awhile? Or, maybe it depends on certain setup from your test project?

Anyway, I'm happy to try testing again, but I'm not sure I fully understand what the critical Quest 3 issue is :-/

File: drivers/vulkan/vulkan_context.cpp [hunk 2]
```diff
@@ -2473,7 +2477,7 @@ Error VulkanContext::swap_buffers() {
 		return OK;
 	}
 
-	//	print_line("swapbuffers?");
+	//	print_line("swap_buffers");
```
Comment (AThousandShips) [inline drivers/vulkan/vulkan_context.cpp:2480]:
```suggestion
	//print_line("swap_buffers");
```
Commented code, as we're already modifying

**Comment by BastiaanOlij** [comment]
> Anyway, I'm happy to try testing again, but I'm not sure I fully understand what the critical Quest 3 issue is :-/

Weird, it's pretty consistent for me. Interestingly enough @RandomShaper PR does prevent the crash as well, but the error spam remains a problem. Or maybe another fix snuck in since I last tested this that prevents the crash.

All in all it's still a good fix as we're never presenting this swapchain, there is extra overhead we're removing, both memory wise and performance wise.

File: drivers/vulkan/vulkan_context.cpp (hunk 2 above)
Comment (BastiaanOlij) [reply drivers/vulkan/vulkan_context.cpp:2480]: I'll fix this up after the rebase

**Comment by YuriSizov** [comment]
I assume this still needs a rebase?

**Comment by BastiaanOlij** [comment]
> I assume this still needs a rebase?

It did since Pedros PR was merged :) should be all good now

File: servers/rendering/renderer_viewport.cpp [hunk 3]
```diff
@@ -764,6 +763,7 @@ void RendererViewport::draw_viewports(bool p_swap_buffers) {
 							blit_to_screen_list[vp->viewport_to_screen].push_back(blits[b]);
 						}
 					}
+					RSG::rasterizer->end_viewport(p_swap_buffers && blits.size() > 0);
```
Comment (AThousandShips) [inline servers/rendering/renderer_viewport.cpp:766]:
```suggestion
					RSG::rasterizer->end_viewport(p_swap_buffers && !blits.is_empty());
```
Optional style suggestion

**Review by AThousandShips — APPROVED** [review]
Looks good otherwise! 🎉

**Comment by akien-mga** [comment]
There's a warning/error with MSVC:
```
.\drivers/d3d12/d3d12_context.h(235): error C3668: 'D3D12Context::flush': method with override specifier 'override' did not override any base class methods
.\drivers/d3d12/d3d12_context.h(235): error C3668: 'D3D12Context::flush': method with override specifier 'override' did not override any base class methods
.\drivers/d3d12/d3d12_context.h(235): error C3668: 'D3D12Context::flush': method with override specifier 'override' did not override any base class methods


scons: *** [platform\windows\godot_windows.windows.editor.x86_64.obj] Error 2
Error: platform\windows\display_server_windows.cpp(4663): error C2259: 'D3D12Context': cannot instantiate abstract class
.\drivers/d3d12/d3d12_context.h(68): note: see declaration of 'D3D12Context'
platform\windows\display_server_windows.cpp(4663): note: due to following members:
platform\windows\display_server_windows.cpp(4663): note: 'void ApiContextRD::flush(bool,bool,bool)': is abstract
.\servers/rendering/renderer_rd/api_context_rd.h(61): note: see declaration of 'ApiContextRD::flush'
```

**Comment by AThousandShips** [comment]
This is because that class hasn't been updated and the override has just two arguments instead of three

**Comment by BastiaanOlij** [comment]
> There's a warning/error with MSVC:
> 
> ```
> .\drivers/d3d12/d3d12_context.h(235): error C3668: 'D3D12Context::flush': method with override specifier 'override' did not override any base class methods
> .\drivers/d3d12/d3d12_context.h(235): error C3668: 'D3D12Context::flush': method with override specifier 'override' did not override any base class methods
> .\drivers/d3d12/d3d12_context.h(235): error C3668: 'D3D12Context::flush': method with override specifier 'override' did not override any base class methods
> 
> 
> scons: *** [platform\windows\godot_windows.windows.editor.x86_64.obj] Error 2
> Error: platform\windows\display_server_windows.cpp(4663): error C2259: 'D3D12Context': cannot instantiate abstract class
> .\drivers/d3d12/d3d12_context.h(68): note: see declaration of 'D3D12Context'
> platform\windows\display_server_windows.cpp(4663): note: due to following members:
> platform\windows\display_server_windows.cpp(4663): note: 'void ApiContextRD::flush(bool,bool,bool)': is abstract
> .\servers/rendering/renderer_rd/api_context_rd.h(61): note: see declaration of 'ApiContextRD::flush'
> ```

Oops, forgot about that. Added the property but didn't do anything with this. The scenario where this would be set to false really only happens on Android (and possibly iOS/VisionPro some day) so there doesn't need to be a DX12 implementation. @RandomShaper I'm guessing we could skip the `_wait_for_idle_queue` if `p_sync` is `false` just in case? But it feels risky to me as there is no way to test the behaviour.

**Comment by RandomShaper** [comment]
If there's no expectation it will be called with `false`, we can even just `ERR_FAIL_COND` it as not implemented.

**Comment by BastiaanOlij** [comment]
> If there's no expectation it will be called with `false`, we can even just `ERR_FAIL_COND` it as not implemented.

Done!

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
This PR is not cherry-pickable because it's based on the codebase after https://github.com/godotengine/godot/pull/83452 (and D3D12). A separate PR needs to be made for the 4.2 branch.
