### PR TITLE
GLES2 disable half-float project setting

### LINKED ISSUE #38318: GLES2 Batching + CPUParticles2D texture + Label = Rendering issue on iOS
**Godot version:**
3.2.2.beta1.official

**OS/device including version:**
iPhone 6 running iOS 12.4.5

**Issue description:**
The CPUParticles2D texture particles are rendered as a flat color instead of showing the actual texture image. 

This happens in a very specific scenario:

1. It only happens when running on an iPhone. The issue doesn't appear when running in Godot.
2. It only happens when there's a Label object present in the scene.
3. It only happens when the new "Use Batching" is ON (in the GLES2 section of the project settings).

Below are some screenshots taken from my iPhone with various settings toggled:

If GLES2 Use Batching = OFF and Label is visible: **[CORRECT]**
batchOFF_labelON

If GLES2 Use Batching = ON and Label is hidden: **[CORRECT]**
batchON_labelOFF

If GLES2 Use Batching = ON and Label is visible: **[WRONG]**
batchON_labelON

As you can see the first two cases it works fine.  But it breaks if Use Batching is ON and the Label is visible.

**NOTE:** I tested this exact same project in the official 3.2.1.official release and the bug is not there. So the bug is only introduced in 3.2.2.beta1 with the Use Batching=ON. 

**NOTE:** Again, this bug is not visible when running inside Godot. You must export an iOS project and build with XCode on a device. I didn't try an iOS simulator.

**Steps to reproduce:**

1. Download the sample project included below.
2. Run the project in the 3.2.2.beta1 beta build.
3. Export the project for iOS. I've included some dummy app icons so you can use those to bypass the warnings. You'll have to enter your own Team ID and bundle identifier. I removed the ones I use.
4. Once exported, open the generated XCode project and build on an iPhone device.
5. You should be able to see the bug right away. Notice that the particles appear as blue squares. The godot robot face is not shown. 

To get the particle texture to render properly you can either: 1) Hide the label (just click the little eye icon) or 2) Open the project settings and under GLES2 turn OFF "Use Batching".   Then export the project again and you should see the proper particle textures working again.

**Minimal reproduction project:**
[ParticleBugTest.zip](https://github.com/godotengine/godot/files/4549493/ParticleBugTest.zip)

### PR DESCRIPTION
**Pull request by lawnjelly**
It seems that particles (and some other features) do not work correctly on iOS in GLES2 because either many of the devices do not support half float compression, or the GL constant used to reference it from Godot is incorrect.

This PR adds a project setting in rendering/gles2/ to disable half-float compression on iOS.

See #38441

May fix - #38318, #38211, #32837, #27191, #31907

## Notes
* This is a hacky approach intended for testing in beta - users can turn it on and off
* If it solves the problem we can hard code it for iOS / add detection code etc

Also, I'm not sure the whole approach (also currently used in web) of compressing to half float in the visual server then decompressing in the renderer is a good idea. It would be better to set some flags or something in the visual server to disable compression happening at all. But maybe it only happens as a once off during mesh creation, not sure yet, in which case it isn't so bad.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
This is good for now for testing. We may be able to do something better later. But keep in mind how few users this problem has been affecting.

**Comment by akien-mga** [comment]
Thanks!

File: drivers/gles2/rasterizer_storage_gles2.cpp [hunk 1]
```diff
@@ -5950,12 +5950,15 @@ void RasterizerStorageGLES2::initialize() {
...
 
+	config.support_half_float_vertices = true;
+//every platform should support this except web, iOS has issues with their support, so add option to disable
 #ifdef JAVASCRIPT_ENABLED
 	config.support_half_float_vertices = false;
-#else
-	//every other platform, be it mobile or desktop, supports this (even if not in the GLES2 spec).
-	config.support_half_float_vertices = true;
 #endif
+	bool disable_half_float = GLOBAL_GET("rendering/gles2/batching/disable_half_float");
```
Comment (avril-gh) [inline drivers/gles2/rasterizer_storage_gles2.cpp:5958]: https://github.com/godotengine/godot/pull/38538
