### PR TITLE
Fix texture/mesh file dropping in 2D and 3D editors

### LINKED ISSUE #57883: Can no longer drop textures on 2D editor
### Godot version

8161e28

### System information

W10

### Issue description

godot windows tools 64_68APmexJYG

### Steps to reproduce

1. Open 2D editor
2. Try dropping any texture on the scene

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #57883

### CODE REVIEW

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -5949,13 +5949,14 @@ bool CanvasItemEditorViewport::can_drop_data(const Point2 &p_point, const Varian
...
 					Ref<PackedScene> scn = res;
+					Ref<Texture2D> tex = res;
 					if (scn.is_valid()) {
 						Node *instantiated_scene = scn->instantiate(PackedScene::GEN_EDIT_STATE_INSTANCE);
 						if (!instantiated_scene) {
 							continue;
 						}
 						memdelete(instantiated_scene);
-					} else {
+					} else if (!tex.is_valid()) {
```
Comment (akien-mga) [inline editor/plugins/canvas_item_editor_plugin.cpp:5959]: When does this actually happen? My understanding was that we already check for extensions for texture above, and it's already checked for being a valid RES. What valid RES with a texture extension wouldn't be a texture?

Comment (KoBeWi) [reply editor/plugins/canvas_item_editor_plugin.cpp:5959]: The problem was if the `res` was not a PackedScene, it would `continue` and never set `can_instantiate` to true.

The code can be simplified I guess.

**Comment by KoBeWi** [comment]
There's `break` after `can_instantiate = true;`, so the check stops after it finds first valid resource.

**Comment by akien-mga** [comment]
> As for 3D code, the change is not needed, because it accepts only one resource type. The `else continue` is redundant, but without it the code looks like "check if it's valid packed scene, and if not, accept".

It accepts both `Mesh`es and `PackedScene`s, isn't that the same as for 2D?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
