### PR TITLE
Check for parameters shadowing class members

### LINKED ISSUE #63092: function argument is constant if it's named "name"
### Godot version

4.0.alpha12

### System information

macOS catalina 10.15.7

### Issue description

Function argument is constant if it's named "name"

```gdscript
extends Control

func _custom_function(name: String = "variant 1"):
	print(name)
	name = "variant 2"
	print(name)

func _ready():
	_custom_function()
```

output:
```
variant 1
variant 1
```

### Steps to reproduce

just open a project

### Minimal reproduction project

[constant_argument_bug.zip](https://github.com/godotengine/godot/files/9126820/constant_argument_bug.zip)

### PR DESCRIPTION
**Pull request by cdemirer**
Fixes #63092

By the way, should shadowing be disallowed for members in their setters?

### CODE REVIEW

File: modules/gdscript/gdscript_compiler.cpp [hunk 1]
```diff
@@ -43,6 +43,10 @@ bool GDScriptCompiler::_is_class_member_property(CodeGen &codegen, const StringN
 		return false;
 	}
 
+	if (codegen.parameters.has(p_name)) {
+		return false; //shadowed
+	}
+
 	if (codegen.locals.has(p_name)) {
 		return false; //shadowed
 	}
```
Comment (akien-mga) [inline modules/gdscript/gdscript_compiler.cpp:52]:
```suggestion
	if (codegen.parameters.has(p_name) || codegen.locals.has(p_name)) {
		return false; // Shadowed.
	}
```
maybe? Not sure what's the preferred style for GDScript specifically, up to @vnen to say I guess.

Comment (cdemirer) [reply modules/gdscript/gdscript_compiler.cpp]: This is indeed more concise :smile:

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by vnen** [comment]
> By the way, should shadowing be disallowed for members in their setters?

Yeah, I guess if you are shadowing the variable that you are writing the setter for, you are essentially making the setter do nothing, so we can forbid this specific case to avoid this problem.
