### PR TITLE
Prevent non-existent scene from being saved to persistent editor config

### LINKED ISSUE #78142: `set_edited_scene` out of bounds errors on empty project
### Godot version

4.1.beta (7b1387ff2)

### System information

Mageia 9, Linux

### Issue description

When opening an empty project in latest `master`, I get these errors:
```
ERROR: Index p_idx = -1 is out of bounds (edited_scene.size() = 1).
   at: get_scene_path (editor/scu/../editor_data.cpp:880)
ERROR: Index p_idx = -1 is out of bounds (edited_scene.size() = 1).
   at: check_and_update_scene (editor/scu/../editor_data.cpp:683)
ERROR: Index p_idx = -1 is out of bounds (edited_scene.size() = 1).
   at: set_edited_scene (editor/scu/../editor_data.cpp:745)
```

Possibly related to recent changes to restore past sessions, but there's nothing to restore in this case?

### Steps to reproduce

- Create a new project, edit it
- Quit to project manager
- Re-open the newly created project -> errors

### Minimal reproduction project

Empty project.

### PR DESCRIPTION
**Pull request by brno32**
Fixes https://github.com/godotengine/godot/issues/78142

There are two issues.

Sometimes we save an empty path to the config:

```python
void EditorNode::_save_open_scenes_to_config(Ref<ConfigFile> p_layout) {
    // ...
    String currently_edited_scene_path = editor_data.get_scene_path(editor_data.get_edited_scene());
    p_layout->set_value(EDITOR_NODE_CONFIG_SECTION, "current_scene", currently_edited_scene_path);
}
```

we try to load whatever the config gives us, even if it's invalid:

```python
if (p_layout->has_section_key(EDITOR_NODE_CONFIG_SECTION, "current_scene")) {
    String current_scene = p_layout->get_value(EDITOR_NODE_CONFIG_SECTION, "current_scene");
    int current_scene_idx = scenes.find(current_scene);
    set_current_scene(current_scene_idx);
}
```

I've opted to not set `"current_scene"` if the value is bad.

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -4932,7 +4932,10 @@ void EditorNode::_save_open_scenes_to_config(Ref<ConfigFile> p_layout) {
 	p_layout->set_value(EDITOR_NODE_CONFIG_SECTION, "open_scenes", scenes);
 
 	String currently_edited_scene_path = editor_data.get_scene_path(editor_data.get_edited_scene());
-	p_layout->set_value(EDITOR_NODE_CONFIG_SECTION, "current_scene", currently_edited_scene_path);
+	// don't save a bad path to the config
```
Comment (akien-mga) [inline editor/editor_node.cpp:4935]: This is the preferred comment style in the codebase (capital letter to start and ends with a dot).
```suggestion
	// Don't save a bad path to the config.
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
