### PR TITLE
Pass window exclusive and transient properties for subwindow creation

### LINKED ISSUE #74261: Differing resolutions on Dual Monitors will trigger engine crashes when Project Settings & Script Docs are closed on different screen as engine (DisplayServer regression)
### Godot version

4.0 Stable

### System information

Windows 10 , Nvidia GeForce RTX 2080 , V 528.49 , Vulkan

### Issue description

When using a dual monitor setup, with different resolutions ( I have a 4k and 1k setup ) , if you open project settings or script docs on the large window, move it to the smaller window, and then close it there, the next time you try to open it Godot will lock up and prevent you from doing anything. You will often ( though not always ) need to close it through task manager.

As a workaround - you can set your resolution on your larger screen to match the smaller one, and functionality is restored.

This issue does not occur if the past position of the project-settings or windows page when closed was on same side as the fully maximized Godot instance. 

I believe it is related to this already closed issue, but I do not believe it is the same problem.

https://github.com/godotengine/godot/issues/58591

### Steps to reproduce

1) Open Godot and open any project.
2) Maximize Godot to fill the largest of two windows.
3) Open Project Settings
4) Move project settings to second window
5) Close project settings
6) Try to open project settings again
7) Observe Godot locking up - menu bar is no longer accessible. 
--- That's the bug. Now do the following to help isolate it.
1) Set your resolution on your larger resolution screen to match your smaller resolution screen.
2) Open Godot and open the same project.
3) Open Project Settings 
4) Observe Godot functioning normally

No repro project included. This is reproducible with a fresh project with nothing in it.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by alvinhochun**
On Windows this allows to avoid having to change the owner of the window after it has been created, which in rare circumstances may cause the window to bug out.

---
- Fixes #74261

This PR complements #94315, but does *not* replace it. By setting the window owner early when creating the window, we can avoid needing to use `SetWindowLongPtr` with `GWLP_HWNDPARENT` which is what triggers the referenced bug. This allows the Project Settings window and etc. to show without having to activate the workaround in #94315, therefore avoiding the window flashing. However, setting the transient parent after the window has already been created will still require said workaround.

CC @bruvzg

### CODE REVIEW

File: platform/linuxbsd/x11/display_server_x11.cpp [hunk 1]
```diff
@@ -1749,6 +1749,12 @@ DisplayServer::WindowID DisplayServerX11::create_sub_window(WindowMode p_mode, V
 		rendering_device->screen_create(id);
 	}
 #endif
+
+	window_set_exclusive(id, p_exclusive);
```
Comment (bruvzg) [inline platform/linuxbsd/x11/display_server_x11.cpp:1753]:
```suggestion
```
It's not implemented for X11 (I do not think there's such thing as exclusive child in X11), so the call is not necessary.

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Thanks!
