### PR TITLE
Fix precision in physics supports generation

### LINKED ISSUE #73869: CollisionShape2D using CapsuleShape2D does not enter sleep
### Godot version

4.0RC5 https://github.com/godotengine/godot/commit/6296b46008fb8d8e5cb9b60af05fa1ea26b8f600

### System information

Windows 10, Forward+, Intel HD 620

### Issue description

Using a CapsuleShape2D as a collisionshape in a Rigidbody2D, the Rigidbody never goes to sleep even when lying on a surface. The CapsuleShape2D keeps registering flickering collisions leading to micro jittering in the Rigidbody.
Using any other shape other than CapsuleShape2D works as intended, with the Rigidbody going to sleep after coming to rest.
(If the CapsuleShape2D is left unrotated it does come to rest, standing on one end.)
image

### Steps to reproduce

Create a static body with a rectangle collision shape.

Create two Rigidbody2D above the rectangle.
Give one rigidbody a CapsuleShape2D and the other one a different collision shape.
Rotate the rigidbodies or the shapes to any angle except 0.

Turn on visible collision shapes.

Run and observe how the red collision indicators never go out on the CapsuleShape.

### Minimal reproduction project

[MinimalReproductionCapsuleShapeCollision.zip](https://github.com/godotengine/godot/files/10824060/MinimalReproductionCapsuleShapeCollision.zip)

### PR DESCRIPTION
**Pull request by Black-Cat**
Fixes #73869

`_SEGMENT_IS_VALID_SUPPORT_THRESHOLD` is used to threshold dot values in code but `1.0 - threshold` is not a correct inverse. As a result of this, condition was never triggered, even in best case scenario like in linked issue test project. That resulted in Capsule2D generating only one support point . Point that was selected was switching sides each 2 physics iteration, which lead to velocities that were above sleeping threshold.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @rburing. See #69657 for the previous change to this code (both 2D and 3D).

File: servers/physics_2d/godot_shape_2d.cpp [hunk 1]
```diff
@@ -371,7 +371,7 @@ void GodotCapsuleShape2D::get_supports(const Vector2 &p_normal, Vector2 *r_suppo
 	real_t d = n.y;
```
Comment (rburing) [inline servers/physics_2d/godot_shape_2d.cpp:371]: This local `d` variable can be removed now, and its usage below replaced by `n.y`.

**Comment by rburing** [comment]
Indeed the condition `abs(n.y) < 1.0 - threshold` is much stronger than `abs(n.x) > threshold`.

Here is a [visualization](https://sagecell.sagemath.org/?z=eJydUkFuwjAQvCPxhxWX2NRNAzeq0iuPqKrIDYZYBDuyXUKK-HvXsRERKWrVPc7OemZn7UojbKmrNSwhSxeL8Uh97vODKJw2FrF5lgWo1EZ-aeV4lUf2AFeiCfgqUlaG16UsLKEeC-0-ttEGdiAVGK62gvSU6fN4BFhHnCi0JfNpLae7pz4jEFokWKnuEwa--YclLYUXmKUZPIK7BBDowfoD0ozRzXxNSMYyysiRtZQVutJmmWyNECoBubl9XFRWQGLEOoniA0pcy9cPoaLsbOA6xOZdHym8Dv36_j_8-rFf_CLlvt8oi3638aI5WuAteesiTOtKO0LZdf5SnePYfqcp7tIQbms8Wm64k3o5QzO1kcqRxCcGpzNMrsITuHzOAzTSlV0yh7S76OmcpPin9tyRYbrs9uD0quM3_ZtOd4P7OvgQ6yt8AzvbE2Y=&lang=sage&interacts=eJyLjgUAARUAuQ==) with `threshold = 0.99` and `200` unit vectors:

to_be_horizontal_or_not_to_be

- Old: 2 "horizontal-ish" vectors `n` with `abs(n.y) < 0.01`
- New: 18 "horizontal-ish" vectors `n` with `abs(n.x) > 0.99`

I agree checking for a horizontal vector is better done with the condition `abs(n.x) > threshold` where `threshold` is close to `1.0` and less than `1.0`. (The alternative would be to keep using `abs(n.y) < threshold` but increase the `threshold`.)

So I agree with this PR, but we need to do the same in 3D.

You can do that in this PR (and [add me as coauthor](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors)) or I can do it in a follow-up PR.

**Comment by Black-Cat** [comment]
@rburing Updated commit to fix all cases in 2d and 3d shapes

**Review by rburing — APPROVED** [review]
Looks good to me. Thanks for pointing out the issue!

No regressions (compared to `master`) are found by the test project [Godot-Physics-Tests](https://github.com/fabriceci/Godot-Physics-Tests).
