### PR TITLE
PortableCompressedTexture: Fix create compressed format from image

### LINKED ISSUE #104950: Unexpected image buffer size when creating PortableCompressedTexture2D from Image
### Tested versions

- Reproducible in v4.5.dev [1f56d96cf], 4.4.1.stable [96579d139]

### System information

Windows 11 Vulkan (Forward+)

### Issue description

When trying to create a PortableCompressedTexture2D from an Image, the following error shows when using compressed formats.
```
  ERROR: Expected Image data size of 512x512x3 (RGB8 without mipmaps) = 786432 bytes, got 131072 bytes instead.
  ERROR: Width must be equal or greater than 1 for all textures
```
If `COMPRESSION_MODE_LOSSLESS `is used, there's no error displayed. Most probably, what's happening is that the Image data buffer is compressed here:
https://github.com/godotengine/godot/blob/1f56d96cf2c768c3844c68ccb504dfeee841ae15/scene/resources/portable_compressed_texture.cpp#L182-L204
So the buffer is no longer of the expected size, since it is compressed.

### Steps to reproduce

- Open the MRP.
- Open the script `test.gd`
- Then run the script with File > Run

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/19578958/test.zip)

### PR DESCRIPTION
**Pull request by beicause**
Fixes #104950

### CODE REVIEW

**Review by BlueCube3310 — APPROVED** [review]

**Comment by rafallus** [comment]
This stops showing the error, but I'm wondering why, in the MRP, the original image (image.png) is 1.45kB, and when you convert to `PortableCompressedTexture2D` it is 128.3kB

File: scene/resources/portable_compressed_texture.cpp [hunk 1]
```diff
@@ -133,6 +133,7 @@ Vector<uint8_t> PortableCompressedTexture2D::_get_data() const {
 
 void PortableCompressedTexture2D::create_from_image(const Ref<Image> &p_image, CompressionMode p_compression_mode, bool p_normal_map, float p_lossy_quality) {
 	ERR_FAIL_COND(p_image.is_null() || p_image->is_empty());
+	ERR_FAIL_COND(p_image->is_compressed());
```
Comment (beicause) [inline scene/resources/portable_compressed_texture.cpp:136]: For lossless or lossy compression, it will be decompressed internally even if the image is compressed.
Maybe I should also decompress it here for the other vram compression formats? 🤔

Comment (BlueCube3310) [reply scene/resources/portable_compressed_texture.cpp]: I'm not sure about that, this is also how the normal CompressedTexture importing works. VRAM-Compressing multiple times will heavily downgrade the quality, the better solution would be to simply store the compressed data directly

Comment (beicause) [reply scene/resources/portable_compressed_texture.cpp]: Returns error for now to minimize the changes. Multiple compressions may not be what users expect.

**Comment by Repiteo** [comment]
Thanks!
