### PR TITLE
Return fast for built-in class icon

### LINKED ISSUE #98666: GDScript code completion is extremely laggy on Android Editor
### Tested versions

Reproducible in build of current master branch - Godot v4.4.dev (8004c7524).
Not reproducible in 4.4.dev3 / 4.3 stable

### System information

Godot v4.4.dev (8004c7524) - Android 14 - Single-window, 1 monitor - Vulkan (Mobile) - integrated Adreno (TM) 618 -  (8 threads)

### Issue description

GDScript autocomplete is now extremely laggy on the Android editor, with the editor freezing until the code completion dialog appears. The code completion delay and  idle auto parse delay are in their defaults.
This does not happen on 4.4.dev3 or earlier.

### Steps to reproduce

Just create a gdscript and type anything that prompts auto complete.

### Minimal reproduction project (MRP)

None

### PR DESCRIPTION
**Pull request by YYF233333**
~~Add a fast path for built-in class in `EditorNode::get_class_icon`.~~

#78645 MRP with 28K objects now runs smoothly, 91K objects still sucks.

~~Would be good if someone knows what `EditorNode::get_object_icon` does could refactor these code.~~

Refactor get icon logic.
- ~Split `_get_class_or_script_icon` into `_get_class_icon` and `_get_script_icon`.~
- ~Change `get_class/object_icon` to avoid multiple checking.~
- Use file extension to identify resource path. This should be cheaper than `ResourceLoader::exists`.

Test with [test_custom_icon.zip](https://github.com/user-attachments/files/18389824/test_custom_icon.zip), `class_name` and `@icon` seems to work without problem. And the performance boost remains true.

*Bugsquad edit:*
- Fixes #98666.

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -4885,6 +4885,12 @@ Ref<Texture2D> EditorNode::get_class_icon(const String &p_class, const String &p
 	ERR_FAIL_COND_V_MSG(p_class.is_empty(), nullptr, "Class name cannot be empty.");
 
 	Ref<Script> scr;
```
Comment (Maran23) [inline editor/editor_node.cpp:4887]: I would suggest moving this down after the `if`, since it is not needed when we go through the fast path.

Comment (YYF233333) [reply editor/editor_node.cpp:4887]: Thanks for the review, but I’ve decided to refactor this code to separate the icon loading process for classes and scripts. This part of the code will likely be moved elsewhere, so I’ll leave it as it is for now.

**Comment by 777joe** [comment]
Tried this out. This fixes https://github.com/godotengine/godot/issues/98666 too.

**Review by Calinou — COMMENTED** [review]
Tested locally, it works as expected. It's faster overall but due to remaining bottlenecks, scrolling large Trees is still sluggish, especially when near the bottom.

Code looks good to me.

All tests done with an optimized editor build with theMRP from https://github.com/godotengine/godot/issues/78645.

I've also tried the MRP of this PR with 16,384 nodes (duplicated from the original 4 nodes) but couldn't spot much of a performance difference when scrolling.

### Local

#### `master`

https://github.com/user-attachments/assets/970e1be6-ef97-41b6-b770-f3bab3a29950

#### This PR

https://github.com/user-attachments/assets/1b094be6-f8d7-4dca-9aea-b74b447a2226

### Remote

*Stutters due to Tree updates being performed every second are still present.*

#### `master`

https://github.com/user-attachments/assets/eff971be-3635-4684-a16a-08b168ac7ec8

#### This PR

https://github.com/user-attachments/assets/98f16233-9bc5-4c30-b587-b19082ffa67e

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -4783,34 +4783,38 @@ void EditorNode::_pick_main_scene_custom_action(const String &p_custom_action_na
...
+			return theme->get_icon(base_type, EditorStringName(EditorIcons));
 		}
 	}
 
+	return nullptr;
+}
+
+Ref<Texture2D> EditorNode::_get_class_icon(const String &p_class, const String &p_fallback) {
+	ERR_FAIL_COND_V_MSG(p_class.is_empty(), nullptr, "Class name cannot be empty.");
+	EditorData &ed = EditorNode::get_editor_data();
```
Comment (KoBeWi) [inline editor/editor_node.cpp:4816]:
```suggestion
	EditorData &ed = get_editor_data();
```
Although the variable feels redundant.

File: editor/editor_node.cpp [hunk 3]
```diff
@@ -4857,41 +4861,57 @@ Ref<Texture2D> EditorNode::get_object_icon(const Object *p_object, const String
...
+	return _get_class_icon(p_object->get_class(), p_fallback);
 }
 
 Ref<Texture2D> EditorNode::get_class_icon(const String &p_class, const String &p_fallback) {
 	ERR_FAIL_COND_V_MSG(p_class.is_empty(), nullptr, "Class name cannot be empty.");
 
-	Ref<Script> scr;
+	// If p_class is a resource path, try to load the resource and get icon from it.
+	if (!p_class.get_extension().is_empty()) {
+		if (ResourceLoader::exists(p_class)) {
```
Comment (KoBeWi) [inline editor/editor_node.cpp:4894]:
```suggestion
	if (!p_class.get_extension().is_empty() && ResourceLoader::exists(p_class)) {
```

**Comment by KoBeWi** [comment]
This looks mostly like a cleanup, while #101489 is a complete solution. The key point is avoiding to load scripts.

Still, it does not have problems I mentioned in https://github.com/godotengine/godot/pull/101489#issuecomment-2607109614, and if it's indeed faster, then it's fine for now. The two PRs don't seem mutually exclusive.

**Review by KoBeWi — APPROVED** [review]

**Review by AThousandShips — APPROVED** [review]
Code looks good

**Comment by YYF233333** [comment]
Unfortunately I cannot make this refactor after #101489, it will crash the editor when create node for unknown reason. But at least we can solve the performance problem first.

I also found a possible regression: after creating a new script and adding `@icon`, the icon doesn't load—it requires restarting the editor to appear. Don't know if it is related to #101489. I tested this on the dev version, not sure if the release version is affected as well.

**Comment by Repiteo** [comment]
Thanks!
