### PR TITLE
Fix crash when dumping extension API in a non-writable directory

### LINKED ISSUE #74534: Segfault when using --dump-extension-api in a non-writable directory
### Godot version

4.0.stable.official.92bee43ad

### System information

Arch Linux x86_64

### Issue description

Using `--dump-extension-api` while in a non-writable directory produces a segfault, rather than an error message and clean abort. A very minor issue, but an issue nonetheless.

### Steps to reproduce

Writable directory, all good:
```
$ cd /tmp
$ godot4 --headless --dump-extension-api
Dumping Extension API
Godot Engine v4.0.stable.official.92bee43ad - https://godotengine.org
Vulkan API 1.3.230 - Forward+ - Using Vulkan Device #0: AMD - AMD Radeon RX 6600 (RADV NAVI23)
```

Unwritable directory (as non-root), crash:
``` 
$ cd /
$ godot4 --headless --dump-extension-api
Dumping Extension API
Godot Engine v4.0.stable.official.92bee43ad - https://godotengine.org
 

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.stable.official (92bee43adba8d2401ef40e2480e53087bcb1eaf1)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x38f50) [0x7f0a3f803f50] (??:0)
[2] godot4() [0xf0a3c3] (??:0)
[3] godot4() [0xe027b2] (??:0)
[4] /usr/lib/libc.so.6(+0x23790) [0x7f0a3f7ee790] (??:0)
[5] /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f0a3f7ee84a] (??:0)
[6] godot4() [0xe2286e] (??:0)
-- END OF BACKTRACE --
================================================================
Aborted (core dumped)
```

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by timothyqiu**
Fixes #74534

### CODE REVIEW

File: core/extension/extension_api_dump.cpp [hunk 1]
```diff
@@ -1052,6 +1052,7 @@ void GDExtensionAPIDump::generate_extension_json_file(const String &p_path) {
 
 	String text = json->stringify(api, "\t", false) + "\n";
 	Ref<FileAccess> fa = FileAccess::open(p_path, FileAccess::WRITE);
+	ERR_FAIL_COND_MSG(fa.is_null(), vformat("Cannot open file '%s' for writing.", p_path));
```
Comment (bruvzg) [inline core/extension/extension_api_dump.cpp:1055]: The same is relevant for `generate_gdextension_interface_file` used by `--dump-gdextension-interface`.

**Review by bruvzg — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.1.
