### PR TITLE
Rotation APIs: Better exposure for degrees methods

### LINKED ISSUE #4511: set_rot() is in degree in editor but in radian in script
**Operating system or device:**
Windows 10 Pro

**Issue description** (what happened, and what was expected):
When setting rot from script you must use deg2rad, but in editor it's in degree. It was supposed to be either everything in radians or in degrees. At the very least something in the docs saying that it was in radian.

**Steps to reproduce:**
Attach a new script to a sprite and write set_rot(80). It's going to be completely erroneous. Now put set_rot(deg2rad(80)). It works just fine.

### PR DESCRIPTION
**Pull request by akien-mga**
Made public the various set/getters for rotations in degrees.
For consistency, renamed the exposed method names to remove the leading
underscore, and kept the old names with a deprecation warning.

Fixes #4511.

### CODE REVIEW

**Comment by akien-mga** [comment]
I *think* I found all places where such degrees methods were defined, but if you know of other classes with this mechanism, please tell me.

Until we implement a proper method for deprecating stuff in #4397, I've kept the old names and added a deprecating warning manually.

Note that the current method names are quite versatile, as we have ``set_rotd``, ``set_rotationd`` and ``set_rotation_deg`` depending on the class. But if we were to change that, it should be done for the radians methods too, and with some more deprecation warnings.

File: scene/3d/spatial.cpp [hunk 1]
```diff
@@ -391,6 +404,20 @@ Vector3 Spatial::get_rotation() const{
...
+Vector3 Spatial::get_rotation_deg() const {
+
+	return get_rotation() * 180.0 / Math_PI;
+}
+
+// Kept for compatibility after rename to set_rotd.
+// Could be removed after a couple releases.
+Vector3 Spatial::_get_rotation_deg() const {
+
+	WARN_PRINT("Deprecated method Spatial._get_rotation_deg(): This method was renamed to get_rotation_deg. Please adapt your code accordingly, as the old method will be obsoleted.");
```
Comment (bojidar-bg) [inline scene/3d/spatial.cpp]: I guess nobody uses this method, and even if he does, he shouldn't expect it to work, since it is private API.

Comment (akien-mga) [inline scene/3d/spatial.cpp]: Well GDScript users don't know if it's private or public in C++, the function was exposed to GDScript, so we need to warn users about it becoming deprecated.

**Comment by djrm** [comment]
There are too many manimngs for the same function, set_rot, set_rotation, set_rotation_deg, set_rotationd, set_rotd, also there are thing like set_param functions that takes an angle, should we add things like PARAM_ANGLE_DEG, i think is too much bloat, there shoul be only one rotation type function either in degrees or radians and use deg2rad, also it is confusing that angles in the editor are expressed in degrees whereas angles in scripts are expresed in radians, probabily theres a good reason for that, but for begginers i dont think that friendly.
