### PR TITLE
Fix color picking on Linux/X11.

### LINKED ISSUE #101265: ColorPicker picking color on Linux is unusable when single window mode is disabled
### Tested versions

4.4.dev7

### System information

Linux

### Issue description

* This was not implemented on Linux, makes it impossible to pick a color from screen on linux, https://github.com/godotengine/godot/commit/9fece033ab11b97bb1c3b1ddeca7b5a21bab0771

### Steps to reproduce

Pick a color from screen on linux.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by WhalesState**
* Fixes : https://github.com/godotengine/godot/issues/101265

### CODE REVIEW

File: scene/gui/color_picker.cpp [hunk 1]
```diff
@@ -1708,7 +1714,13 @@ void ColorPicker::_pick_button_pressed() {
 
 	if (!picker_window) {
 		picker_window = memnew(Popup);
-		picker_window->set_size(Vector2i(55, 72));
+		bool linuxbsd = OS::get_singleton()->get_name() == "Linux";
```
Comment (bruvzg) [inline scene/gui/color_picker.cpp:1717]:
```suggestion
		bool linuxbsd = !DisplayServer::get_singleton()->has_feature(DisplayServer::FEATURE_SCREEN_EXCLUDE_FROM_CAPTURE);
```

Comment (bruvzg) [reply scene/gui/color_picker.cpp:1717]: I have also missed this flag when implementing exclude mode on Windows and macOS:

```diff
diff --git a/platform/macos/display_server_macos.mm b/platform/macos/display_server_macos.mm
index 253b4b0a9f..2f0e7ea487 100644
--- a/platform/macos/display_server_macos.mm
+++ b/platform/macos/display_server_macos.mm
@@ -788,6 +788,7 @@ bool DisplayServerMacOS::has_feature(Feature p_feature) const {
 		case FEATURE_STATUS_INDICATOR:
 		case FEATURE_NATIVE_HELP:
 		case FEATURE_WINDOW_DRAG:
+		case FEATURE_SCREEN_EXCLUDE_FROM_CAPTURE:
 			return true;
 		default: {
 		}
diff --git a/platform/windows/display_server_windows.cpp b/platform/windows/display_server_windows.cpp
index 3459602265..9b495a9135 100644
--- a/platform/windows/display_server_windows.cpp
+++ b/platform/windows/display_server_windows.cpp
@@ -138,6 +138,7 @@ bool DisplayServerWindows::has_feature(Feature p_feature) const {
 		case FEATURE_SCREEN_CAPTURE:
 		case FEATURE_STATUS_INDICATOR:
 		case FEATURE_WINDOW_EMBEDDING:
+		case FEATURE_SCREEN_EXCLUDE_FROM_CAPTURE:
 			return true;
 		default:
 			return false;
```

**Review by bruvzg — COMMENTED** [review]
Seems like I forgot real X11 still exist (it's irrelevant for Wayland and XWayland since both use embedded picker only). The change looks fine, but it should use a feature flag instead of hard-coding "Linux".

File: scene/gui/color_picker.cpp [hunk 2]
```diff
@@ -1708,7 +1714,13 @@ void ColorPicker::_pick_button_pressed() {
 
 	if (!picker_window) {
 		picker_window = memnew(Popup);
-		picker_window->set_size(Vector2i(55, 72));
+		bool has_feature_exclude_from_capture = DisplayServer::get_singleton()->has_feature(DisplayServer::FEATURE_SCREEN_EXCLUDE_FROM_CAPTURE);
+		if (!has_feature_exclude_from_capture) {
+			picker_window->set_size(Vector2i(28, 28));
+		} else {
+			picker_window->set_size(Vector2i(55, 72));
+			picker_window->set_flag(Window::FLAG_EXCLUDE_FROM_CAPTURE, true); // Unsupported on linux.
```
Comment (bruvzg) [inline scene/gui/color_picker.cpp:1722]:
```suggestion
```

It's already set two lines below.

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
