### PR TITLE
Make uids of duplicated items unique in FileSystemDock

### LINKED ISSUE #54774: Duplicated files or resources retains the same UID
### Godot version

4.0.dev (56cfebbe9)

### System information

Windows 10

### Issue description

When duplicating a file through the FileSystem dock, the duplicated file has the same UID as the original file. This leads to the wrong file being used later on, if something references the original and duplicated files.

### Steps to reproduce

Duplicate a file through the FileSystem dock.
Open the original file in a text editor (or it's .import file if it has one)
Open the duplicated file the same way.
Notice that both file's UIDs are identical.

To see the issue with duplicated UIDs:
Duplicate a file through the FileSystem dock.
Add both the original and duplicated files to a scene.
Run the scene.
Notice that, instead of loading the original file, the duplicated file was loaded twice.

### Minimal reproduction project

[DuplicateTest.zip](https://github.com/godotengine/godot/files/7499188/DuplicateTest.zip)

*Bugsquad edit (keywords for easier searching): ID*

### PR DESCRIPTION
**Pull request by PucklaJ**
Fixes #54774

This PR does the following things:
1. If a folder is duplicated. It iterates over all elements of the folder and recursively calls `_try_duplicate_item` for every element.
2. If a file, that does not have a corresponding .import file, gets duplicated, the file is loaded as a `Resource` and then saved again. The new uid is generated when the resource gets saved at a new location. If the file does have a .import file the file itself will be copied and the .import will be saved after removing the uid entry (which is the current behaviour). When saving the .import file a new uid is generated.

+ Files, which do not use a uid or when the uid could not be retrieved, will just be copied. Since it probably means that it is either a text file (.txt, .gd, .md, ...) or does not have a uid set.
+ I am using `ResourceSaver::save` with the `FLAG_COMPRESS` flag, therefore some files which have not been originally compressed, will differ from the old file (But this flag seems to have no impact on text based files like .tres and .tscn).

### CODE REVIEW

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -1293,33 +1293,66 @@ void FileSystemDock::_try_duplicate_item(const FileOrFolder &p_item, const Strin
...
+	if (p_old_is_file) {
+		// Ignore some files, since they do not use a uid
+		String ext = p_new_path.get_extension();
+		// FIXME: Add more file extensions to this list
+		if (ext == "gd" ||
+				ext == "gdshader" ||
+				ext == "txt" ||
+				ext == "md") {
+			return;
+		}
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:1314]: You could instead check if the resource has UID available:
```C++
ResourceUID::ID uid = ResourceLoader::get_resource_uid(p_old_path);
if (uid == ResourceUID::INVALID_ID) {
    return;
}
```

Comment (PucklaMotzer09) [reply editor/filesystem_dock.cpp:1314]: Thank You! This is exactly something I was looking for.

**Comment by PucklaMotzer09** [comment]
@KoBeWi Is there still something that needs to be evaluated? I intend to do this PR as part of hacktoberfest. So it would be nice if this PR got accepted before the end of october.

**Comment by KoBeWi** [comment]
Sorry for waiting.
It does not fix the issue, duplicated scenes still have the same UID. `scene_unique_id` is id of built-in resources within scenes.

**Comment by PucklaMotzer09** [comment]
I changed the PR quit heavily. Instead of fixing the UIDs after copying the files, the resources are loaded and saved. And also the `_fix_uid_of_duplicated_item` method has been removed and `_try_duplicate_item` is directly used.

File: editor/filesystem_dock.cpp [hunk 2]
```diff
@@ -1283,42 +1283,71 @@ void FileSystemDock::_try_duplicate_item(const FileOrFolder &p_item, const Strin
...
 		}
 	} else {
-		EditorNode::get_singleton()->add_io_error(TTR("Error duplicating:") + "\n" + old_path + "\n");
+		// Recursively duplicate all files inside the folder
+		Ref<DirAccess> old_dir = DirAccess::open(old_path);
+		Ref<FileAccess> file_access = FileAccess::create(FileAccess::ACCESS_RESOURCES);
+		old_dir->list_dir_begin();
+		for (String f = old_dir->get_next(); !f.is_empty(); f = old_dir->get_next()) {
+			if (f == "." || f == ".." || f.get_extension() == "import")
+				continue;
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:1343]:
```suggestion
			if (f == "." || f == ".." || f.get_extension() == "import") {
				continue;
			}
```

File: editor/filesystem_dock.cpp [hunk 3]
```diff
@@ -1283,42 +1283,71 @@ void FileSystemDock::_try_duplicate_item(const FileOrFolder &p_item, const Strin
...
-	Error err = p_item.is_file ? da->copy(old_path, new_path) : da->copy_dir(old_path, new_path);
-	if (err == OK) {
-		// Move/Rename any corresponding import settings too.
-		if (p_item.is_file && FileAccess::exists(old_path + ".import")) {
-			err = da->copy(old_path + ".import", new_path + ".import");
+
+	if (p_item.is_file) {
+		print_verbose("Duplicating " + old_path + " -> " + new_path);
+
+		// Create the directory structure
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:1290]:
```suggestion
		// Create the directory structure.
```

File: editor/filesystem_dock.cpp [hunk 4]
```diff
@@ -1283,42 +1283,71 @@ void FileSystemDock::_try_duplicate_item(const FileOrFolder &p_item, const Strin
...
-				PackedStringArray lines = file->get_as_utf8_string().split("\n");
-				String line = lines[0];
-
-				if (line.contains("uid")) {
-					line = line.substr(0, line.find(" uid")) + "]";
-					lines.write[0] = line;
+			err = cfg->save(new_path + ".import");
+			if (err != OK) {
+				// Delete the duplicated file
+				da->remove(new_path);
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:1308]: Why delete the file? If import fails to save, it will simply be reimported.

File: editor/filesystem_dock.cpp [hunk 5]
```diff
@@ -1283,42 +1283,71 @@ void FileSystemDock::_try_duplicate_item(const FileOrFolder &p_item, const Strin
...
-					if (err == OK) {
-						file2->store_string(String("\n").join(lines));
-					}
+			// Load the resource and save it again in the new location (by saving the resource at a new location a new uid gets generated)
+			Error err;
+			Ref<Resource> res = ResourceLoader::load(old_path, "", ResourceFormatLoader::CACHE_MODE_REUSE, &err);
+			if (err == OK && !res.is_null()) {
+				err = ResourceSaver::save(res, new_path, ResourceSaver::FLAG_COMPRESS);
+				if (err != OK) {
+					EditorNode::get_singleton()->add_io_error(TTR("Error duplicating:") + " " + vformat(TTR("Failed to save resource of %s: %s"), new_path, error_names[err]));
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:1328]:
```suggestion
					EditorNode::get_singleton()->add_io_error(TTR("Error duplicating:") + " " + vformat(TTR("Failed to save resource at %s: %s"), new_path, error_names[err]));
```
Same below.

File: editor/filesystem_dock.cpp [hunk 6]
```diff
@@ -1283,42 +1283,71 @@ void FileSystemDock::_try_duplicate_item(const FileOrFolder &p_item, const Strin
...
 				}
+			} else if (err != OK) {
+				// When loading files like text files the error is OK but the resource is still null
+				// We can ignore such files
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:1332]:
```suggestion
				// When loading files like text files the error is OK but the resource is still null.
				// We can ignore such files.
```

File: editor/filesystem_dock.cpp [hunk 7]
```diff
@@ -1283,42 +1283,71 @@ void FileSystemDock::_try_duplicate_item(const FileOrFolder &p_item, const Strin
...
+			}
 
-					Ref<FileAccess> file2 = FileAccess::open(new_path, FileAccess::WRITE, &err);
-					if (err == OK) {
-						file2->store_string(String("\n").join(lines));
-					}
+			// Load the resource and save it again in the new location (by saving the resource at a new location a new uid gets generated)
+			Error err;
+			Ref<Resource> res = ResourceLoader::load(old_path, "", ResourceFormatLoader::CACHE_MODE_REUSE, &err);
+			if (err == OK && !res.is_null()) {
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:1325]:
```suggestion
			if (err == OK && res.is_valid()) {
```

File: editor/filesystem_dock.cpp (hunk 4 above)
Comment (PucklaMotzer09) [reply editor/filesystem_dock.cpp:1308]: This is true, but it will probably be reimported with different settings. Therefore I decided to delete the file.

Comment (KoBeWi) [reply editor/filesystem_dock.cpp:1308]: Well, if you duplicate a file, it's better to have it reimported with different settings than not getting duplicated at all.
Not to mention such situation is rare anyway.

**Review by KoBeWi — APPROVED** [review]

File: editor/filesystem_dock.cpp [hunk 8]
```diff
@@ -1283,42 +1283,71 @@ void FileSystemDock::_try_duplicate_item(const FileOrFolder &p_item, const Strin
...
+					EditorNode::get_singleton()->add_io_error(TTR("Error duplicating:") + "\n" + old_path + ": " + error_names[err] + "\n");
+				}
+				return;
+			}
 
-					Ref<FileAccess> file2 = FileAccess::open(new_path, FileAccess::WRITE, &err);
-					if (err == OK) {
-						file2->store_string(String("\n").join(lines));
-					}
+			// Load the resource and save it again in the new location (by saving the resource at a new location a new uid gets generated)
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:1320]:
```suggestion
			// Load the resource and save it again in the new location (this generates a new UID).
```

File: editor/filesystem_dock.cpp [hunk 9]
```diff
@@ -1283,42 +1283,71 @@ void FileSystemDock::_try_duplicate_item(const FileOrFolder &p_item, const Strin
...
 				}
+			} else if (err != OK) {
+				// When loading files like text files the error is OK but the resource is still null.
+				// We can ignore such files.
+				EditorNode::get_singleton()->add_io_error(TTR("Error duplicating:") + " " + vformat(TTR("Failed to load resource at %s: %s"), new_path, error_names[err]));
 			}
 		}
 	} else {
-		EditorNode::get_singleton()->add_io_error(TTR("Error duplicating:") + "\n" + old_path + "\n");
+		// Recursively duplicate all files inside the folder
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:1335]:
```suggestion
		// Recursively duplicate all files inside the folder.
```

**Comment by akien-mga** [comment]
Thanks!
