### PR TITLE
Fix `BottomPanel` excessive width.

### LINKED ISSUE #95681: Too many plugins on the bottom panel make it impossible to resize side panels
### Tested versions

Godot v4.3.stable.mono

### System information

Godot v4.3.stable.mono - macOS 14.5.0 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

https://github.com/user-attachments/assets/4b64ed61-6bb4-4522-bef9-61d6edad51ac

Screenshot 2024-08-16 at 8 51 49 PM

With enough plugins, the list on the bottom panel gets unwieldy and makes it impossible to resize the side bars. This makes working on a smaller screen nearly impossible. I'm on a 1440x900 Macbook with the default display scale of 200%.

It would be nice if the bottom panel tabs got arrows like all the other tabs, for example the right side bar when it's smaller:
https://github.com/user-attachments/assets/87c353b0-ea61-4965-a912-f44b0af5404d

### Steps to reproduce

Install a few addons that add to the bottom panel

Some examples:
- [AssetPlacer](https://cookiebadger.itch.io/assetplacer)
- [Phantom Camera](https://phantom-camera.dev/)
- [Terrain3D](https://terrain3d.readthedocs.io/)

Additionally, using the dotnet build of Godot adds an "MSBuild" tab. You can also move the "FileSystem" tab to the bottom which contributes to the problem.

### Minimal reproduction project (MRP)

See comment below (thank you @tetrapod00 !!!)

### PR DESCRIPTION
**Pull request by WhalesState**
* Fixes: https://github.com/godotengine/godot/issues/95681

### CODE REVIEW

**Comment by tetrapod00** [comment]
Tested locally.

With a typical use case, this allows the bottom bar to stay as narrow as it currently does in 4.3. However, this PR does truncate names unnecessarily by forcing each button to have an equal-length name. Subjectively, forcing equal spacing also looks slightly worse at wide widths.
4.3, minimum width:
Godot_v4 3-stable_win64_7GtDjThK0s
This PR, minimum width:
godot windows editor x86_64_tU3XRykGFX
This PR, maximum width:
godot windows editor x86_64_yKkjVncwZf

 
With the second MRP in the issue (https://github.com/godotengine/godot/issues/95681#issuecomment-2379133094). On a 1080 screen (I use windows with the taskbar on the side, so the width is a bit less than 1080), that MRP still produces a broken UI with this PR. The right side of the inspector is cut off, and the left and right panels still can't be dragged to rescale.
godot windows editor x86_64_4Q6WsY5rl7

I suspect one of the other proposed solutions mentioned in the issue, using a TabBar or HFlowContainer, is a more robust solution.

**Comment by WhalesState** [comment]
`TabBar` is not ideal, unless we find a way to change one tab's text color without affecting the others.

`HFlowContainer` will just move this from a width issue to a height issue with the same amount of tabs that you already have drawn.

Maybe `ScrollContainer` is the only way to fix this, but it will require some more work, to allow focus mode for buttons and to focus the button after using `Button->set_button_pressed(true)` to allow the `ScrollContainer` to use `follow_focus` to scroll to the selected button.

**Comment by kitbdev** [comment]
We could add text customization to TabBar (see https://github.com/godotengine/godot-proposals/issues/9161 and https://github.com/godotengine/godot/pull/88709). We could also add the ability to change tabs when dragging, as it would be useful for regular docks (added in https://github.com/godotengine/godot/pull/86765).

But the real problem with changing it to a TabBar is the method [`add_control_to_bottom_panel`](https://docs.godotengine.org/en/stable/classes/class_editorplugin.html#class-editorplugin-method-add-control-to-bottom-panel) returns a Button, and we need to keep compatibility.

**Comment by WhalesState** [comment]
we can consider creating a custom `Container` for the bottom panel, similar to `TabBar`, to handle button layout and behavior, we don't have to tweak the `TabBar` to solve an issue that doesn't belong to it.

**Comment by WhalesState** [comment]
Another try.

https://github.com/user-attachments/assets/021e1404-d4d8-4d41-9476-72d38b0c9d6a

**Comment by tetrapod00** [comment]
Tested the new version with the arrows. It works great for both typical editor usage and the pathological MRP. I like this solution, it feels very natural.

The arrows should be either disabled (grayed out and non-interactive) or completely hidden when all the buttons fit horizontally  (which is most of the time, in typical editor usage). I would personally prefer being hidden entirely, since in typical editor usage you should never need to use these arrows. But you can find a precedent for either hiding or disabling within the `BottomPanel` itself (toast notifications are disabled/enabled, but the expand vertically button hides and unhides).

**Review by tetrapod00 — CHANGES_REQUESTED** [review]
Reviewing functionality, not code:
Tested the new version with the arrows. It works great for both typical editor usage and the pathological MRP. I like this solution, it feels very natural.

The arrows should be either disabled (grayed out and non-interactive) or completely hidden when all the buttons fit horizontally  (which is most of the time, in typical editor usage). I would personally prefer being hidden entirely, since in typical editor usage you should never need to use these arrows. But you can find a precedent for either hiding or disabling within the `BottomPanel` itself (toast notifications are disabled/enabled, but the expand vertically button hides and unhides).

**Comment by WhalesState** [comment]
> The arrows should be either disabled (grayed out and non-interactive) or completely hidden when all the buttons fit horizontally (which is most of the time, in typical editor usage).

Thank You!

Disabling buttons is safer than hiding them to prevent accidental selection. Additionally, connecting the `value_changed` signal is not necessary since pressing the button when no room to scroll does nothing.

I'm just laying the groundwork, and it's open to future changes and improvements.

**Comment by arkology** [comment]
I would prefer these buttons to be hidden, which is typical editor usage 99.999999% of the time.

**Comment by WhalesState** [comment]
To avoid accidental selection we can only hide them when they aren't needed, and then we can show both and disable each one separately when there are many editor plugins.

**Comment by KoBeWi** [comment]
The buttons should definitely be disabled when not needed.

Also if hiding is a problem, you could "hide" them by setting modulate alpha to 0. Not sure if such margin out of nowhere is acceptable though.
image

**Comment by KoBeWi** [comment]
image
Ctrl is usually used for scroll to the end, so Ctrl and Shift should be swapped here IMO.

File: editor/gui/editor_bottom_panel.cpp [hunk 1]
```diff
@@ -59,6 +62,26 @@ void EditorBottomPanel::_switch_by_control(bool p_visible, Control *p_control) {
 	}
 }
 
+void EditorBottomPanel::_scroll_left() {
+	if (Input::get_singleton()->is_key_pressed(Key::SHIFT)) {
+		button_scroll->set_h_scroll(0);
+	} else if (Input::get_singleton()->is_key_pressed(Key::CTRL)) {
+		button_scroll->set_h_scroll(button_scroll->get_h_scroll() - button_scroll->get_size().width);
```
Comment (KoBeWi) [inline editor/gui/editor_bottom_panel.cpp:69]:
```suggestion
		button_scroll->set_h_scroll(button_scroll->get_h_scroll() - button_scroll->get_page());
```
Same below.

File: editor/gui/editor_bottom_panel.cpp [hunk 2]
```diff
@@ -246,9 +270,29 @@ EditorBottomPanel::EditorBottomPanel() {
 	bottom_hbox->set_custom_minimum_size(Size2(0, 24 * EDSCALE)); // Adjust for the height of the "Expand Bottom Dock" icon.
 	item_vbox->add_child(bottom_hbox);
 
+	left_button = memnew(Button);
+	left_button->set_tooltip_text(TTR("Scroll Left\nHold Shift to scroll to the begin.\nHold Ctrl to scroll one page."));
```
Comment (KoBeWi) [inline editor/gui/editor_bottom_panel.cpp:274]: You can make a `const String` to store this message, so it's not repeated.

**Comment by WhalesState** [comment]
> The buttons should definitely be disabled when not needed.
> 
> Also if hiding is a problem, you could "hide" them by setting modulate alpha to 0. Not sure if such margin out of nowhere is acceptable though.

Hiding was so easy, the issue was disabling the buttons which have required a lot of code and to be deferred to work properly, hiding the buttons when not needed and disabling each one when it reaches it's own limit makes it more usable.

> Scrolling to last element when panel is opened does not work correctly, because of the expand button becoming visible.
> Making ensure_control_visible() deferred can probably fix it.

I have tried to make it deferred and also have tried to adjust the `HScrollBar` value or defer the adjustment, but nothing has worked. Also, I have some concerns that if we wait two frames until the scroll updates correctly, the button may change or be freed.

I will make a final test before pushing the changes.

File: editor/gui/editor_bottom_panel.cpp (hunk 2 above)
Comment (WhalesState) [reply editor/gui/editor_bottom_panel.cpp:274]: `Scroll Left/Right` and `to the begin/end` are distinct. Did you mean to suggest using vformat() like other controls?

**Comment by KoBeWi** [comment]
For updating disable status, maybe connecting `value_changed` of scrollbar with CONNECT_DEFERRED would suffice? 🤔

**Comment by WhalesState** [comment]
> For updating disable status, maybe connecting `value_changed` of scrollbar with CONNECT_DEFERRED would suffice? 🤔

It's enough for the left button, but for the right button it should update when resized or when the `button_hbox` size changes (ie. adding/removing buttons).

File: editor/gui/editor_bottom_panel.cpp [hunk 3]
```diff
@@ -41,11 +41,28 @@
...
 void EditorBottomPanel::_notification(int p_what) {
 	switch (p_what) {
 		case NOTIFICATION_THEME_CHANGED: {
 			expand_button->set_icon(get_editor_theme_icon(SNAME("ExpandBottomDock")));
+			left_button->set_icon(get_editor_theme_icon(SNAME("Back")));
+			right_button->set_icon(get_editor_theme_icon(SNAME("Forward")));
+		} break;
+
+		case NOTIFICATION_READY: {
+			callable_mp(this, &EditorBottomPanel::_update_scroll_buttons).call_deferred();
```
Comment (KoBeWi) [inline editor/gui/editor_bottom_panel.cpp:55]: Can't this be done in constructor? It's deferred anyway.

File: editor/gui/editor_bottom_panel.cpp [hunk 4]
```diff
@@ -59,6 +76,34 @@ void EditorBottomPanel::_switch_by_control(bool p_visible, Control *p_control) {
...
+void EditorBottomPanel::_scroll(bool p_right) {
+	HScrollBar *h_scroll = button_scroll->get_h_scroll_bar();
+	if (Input::get_singleton()->is_key_pressed(Key::CTRL)) {
+		h_scroll->set_value(p_right ? h_scroll->get_max() : 0);
+	} else if (Input::get_singleton()->is_key_pressed(Key::SHIFT)) {
+		h_scroll->set_value(h_scroll->get_value() + (h_scroll->get_page() * (p_right ? 1 : -1)));
+	} else {
+		h_scroll->set_value(h_scroll->get_value() + ((h_scroll->get_page() * 0.5) * (p_right ? 1 : -1)));
+	}
+	_update_disabled_buttons();
```
Comment (KoBeWi) [inline editor/gui/editor_bottom_panel.cpp:88]: You already connected the signal, so this makes the buttons updated twice.

File: editor/gui/editor_bottom_panel.cpp [hunk 5]
```diff
@@ -59,6 +76,34 @@ void EditorBottomPanel::_switch_by_control(bool p_visible, Control *p_control) {
 	}
 }
 
+void EditorBottomPanel::_scroll(bool p_right) {
+	HScrollBar *h_scroll = button_scroll->get_h_scroll_bar();
+	if (Input::get_singleton()->is_key_pressed(Key::CTRL)) {
+		h_scroll->set_value(p_right ? h_scroll->get_max() : 0);
+	} else if (Input::get_singleton()->is_key_pressed(Key::SHIFT)) {
+		h_scroll->set_value(h_scroll->get_value() + (h_scroll->get_page() * (p_right ? 1 : -1)));
```
Comment (KoBeWi) [inline editor/gui/editor_bottom_panel.cpp:84]:
```suggestion
		h_scroll->set_value(h_scroll->get_value() + h_scroll->get_page() * (p_right ? 1 : -1));
```
Not needed due to operator precedence.
Same below.

File: editor/gui/editor_bottom_panel.cpp [hunk 6]
```diff
@@ -59,6 +76,34 @@ void EditorBottomPanel::_switch_by_control(bool p_visible, Control *p_control) {
...
+	_update_disabled_buttons();
+}
+
+void EditorBottomPanel::_update_scroll_buttons() {
+	bool show_arrows = button_hbox->get_size().width > button_scroll->get_size().width;
+	left_button->set_visible(show_arrows);
+	right_button->set_visible(show_arrows);
+
+	if (show_arrows) {
+		callable_mp(this, &EditorBottomPanel::_update_disabled_buttons).call_deferred();
```
Comment (KoBeWi) [inline editor/gui/editor_bottom_panel.cpp:97]: `_update_scroll_buttons()` is always deferred, so `_update_disabled_buttons()`, so this call doesn't need to (it doesn't even make difference in this case).

**Review by KoBeWi — APPROVED** [review]
There are some inefficient calls (see comments), but functionally it's ok.

File: editor/gui/editor_bottom_panel.cpp (hunk 4 above)
Comment (WhalesState) [reply editor/gui/editor_bottom_panel.cpp:88]: `set_value()` doesn't emit `value_changed` signal, and it was just shorter to call the function directly instead of emitting.

**Comment by AThousandShips** [comment]
Please rebase to fix a CI problem

File: editor/gui/editor_bottom_panel.cpp (hunk 4 above)
Comment (WhalesState) [reply editor/gui/editor_bottom_panel.cpp:85]: The `set_value()` is calling `set_value_no_signal()`.

**Comment by WhalesState** [comment]
I want to start by expressing my sincere respect for all Godot developers. I have learned so much from you all, and I am genuinely grateful for the many times you've helped me correct my mistakes and deepen my understanding of Godot. Thank you for your support and guidance.

I apologize if my decision to close my PRs seemed abrupt. I know many developers are currently occupied with GodotCon and the holiday season.

One reason for closing my PRs is that I am working on another Godot fork, and I need to consolidate everything under my main GitHub account. I also felt that my PRs weren’t receiving attention, even those that were already approved and had been pending for over 20 days.

However, there was a deeper issue: several of my merged PRs in the Blazium fork were cherry-picked by the Redot project before these changes were integrated into Godot 4.x. I had applied these changes specifically to the Blazium engine, yet Redot copied my commits, divided them into multiple PRs, and presented them as if they were original contributions without any acknowledgment. This experience was frustrating and discouraging.

Another concern I have is related to the approach toward blocking on GitHub. I'm concerned about the possibility of being blocked if my personal opinions or beliefs don’t align with certain community politics or principles. This has made me cautious, as I deeply value the freedom that open-source projects stand for.

**Comment by hpvb** [comment]
@WhalesState I am sorry to hear that. However the only people that were blocked from Github were people opening spam issues on our bug tracker. The people who claimed they were blocked because of something they said on Twitter were lying, they had posted spam to the Github.

**Comment by WhalesState** [comment]
Godot didn't say anything about this, they didn't correct it and thank you for making it clear, we are left to hear from one side and i didn't care about being blocked anywhere except on github, I always try to stay away from politics and to focus on learning and writing code.
I just need to delete the branch from main and to fork godot from another account, I think I'm doing it wrong and maybe i should have transfered the ownership to another account instead of closing the PRs. It's the first time to deal with such issue and sorry about that.

**Comment by kitbdev** [comment]
Needs rebase to fix conflicts.

Sometimes it doesn't scroll to the button that was just selected:

https://github.com/user-attachments/assets/26cd30e4-9eb3-419f-94a7-0c1d5b300ed0

but otherwise it looks good.

**Comment by WhalesState** [comment]
> Needs rebase to fix conflicts.
> 
> Sometimes it doesn't scroll to the button that was just selected:

Deferred the call for `ScrollContainer::insure_control_visible`, it didn't work because the control was already visible then the bottom panel was resized down.

**Review by tetrapod00 — APPROVED** [review]
I tested the functionality of the latest artifact. It still works fine for me in both typical editor usage and with the pathological MRP. Between this and the alternate PR https://github.com/godotengine/godot/pull/99594, I slightly prefer this one.

I appreciate that the arrows now both disappear when not needed, and also are grayed out when at the start or end of the list of tabs.

I don't know enough to review the code.

**Comment by TranquilMarmot** [comment]
Finally trying this out in 4.4, thank you so so much @WhalesState for fixing this!
