### PR TITLE
Remove redraw timer for theme previews

### LINKED ISSUE #118255: Theme Editor odd behavior related to buttons with a `hover` stylebox
### Tested versions

v4.6.stable.official [89cea1439]

### System information

Godot v4.6.stable - Windows 11 (build 26200) - Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 4060 Laptop GPU (NVIDIA; 32.0.15.8097) - Intel(R) Core(TM) i9-14900HX (32 threads) - 31.62 GiB memory

### Issue description

https://github.com/user-attachments/assets/be558378-5a1c-4bca-be90-9fea78c54361

The Theme Editor has strange behavior, which does not occur in the running game. For example these buttons are shrinking (after a random time hovered) and remain shrunk (again for a random time) after unhovering. 

### Steps to reproduce

See MRP. The setup is a few buttons in an HBoxContainer, where the scene has a theme with a single value set: The `hover` field of `Button` with a default/new `StyleBoxFlat`

You can open `theme.tres` and then add `example.tscn` as a custom preview. Hover the buttons to see the odd behavior. 

You can also run `example.tscn` to compare.

### Minimal reproduction project (MRP)

[buttonstyleboxmrp_2026-04-06_22-08-31.zip](https://github.com/user-attachments/files/26519893/buttonstyleboxmrp_2026-04-06_22-08-31.zip)

### PR DESCRIPTION
**Pull request by YeldhamDev**
The `Theme` editor preview has had for several years a refresh timer to manually trigger redrawing for the `Control` nodes inside. The problem is that it not only feels like it's totally pointless (since I didn't see anything toggled to disable the automatic redrawing), but also breaks stuff. So this PR outright removes that stuff.

Fixes #118255.

### CODE REVIEW

File: editor/scene/gui/theme_editor_preview.cpp [hunk 1]
```diff
@@ -232,12 +197,8 @@ void ThemeEditorPreview::_notification(int p_what) {
 			theme_cache.font_size = get_theme_default_font_size();
 		} break;
 
-		case NOTIFICATION_PROCESS: {
-			time_left -= get_process_delta_time();
-			if (time_left < 0) {
-				time_left = REFRESH_TIMER;
-				_refresh_interval();
-			}
+		case EditorSettings::NOTIFICATION_EDITOR_SETTINGS_CHANGED: {
```
Comment (KoBeWi) [inline editor/scene/gui/theme_editor_preview.cpp]: Wrong settings.

Comment (YeldhamDev) [reply editor/scene/gui/theme_editor_preview.cpp]: Fixed.

File: editor/scene/gui/theme_editor_preview.cpp [hunk 2]
```diff
@@ -202,18 +176,12 @@ void ThemeEditorPreview::_reset_picker_overlay() {
 	picker_overlay->queue_redraw();
 }
 
+void ThemeEditorPreview::_update_preview_bg() {
+	preview_bg->set_color(GLOBAL_GET("rendering/environment/defaults/default_clear_color"));
```
Comment (KoBeWi) [inline editor/scene/gui/theme_editor_preview.cpp]: This could get a `check_changed_settings_in_group()` check.

**Review by KoBeWi — APPROVED** [review]

File: editor/scene/gui/theme_editor_preview.cpp (hunk 2 above)
Comment (YeldhamDev) [reply editor/scene/gui/theme_editor_preview.cpp]: Feels a little overkill, but sure. :man_shrugging:

**Comment by Repiteo** [comment]
Thanks!
