### PR TITLE
Exporting -> Android: Keystore Warnings

### LINKED ISSUE #48787: Exporting Android Project Missing Default Debug Keystore Values from Editor Settings
**Godot version:** 3.3

**OS/device including version:** Windows 10 Version 20H2, Dell XPS 13 9310

**Issue description:**
I am following the ["Exporting for Android"](https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_android.html#setting-it-up-in-godot) tutorial to export my project for Android. I set the `Debug Keystore`, `Debug Keystore User`, and `Debug Keystore Pass` in the `Editor Settings` in accordance with the tutorial (https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_android.html#setting-it-up-in-godot). 

When I go to export the project (Project -> Export -> Add -> Android) I see that under Options -> Keystore, the `Debug`, `Debug User`, and `Debug Password` fields are all empty. 

I would expect those values to be defaulted to match the values set in the `Editor Settings`.

I had opened a pull request to add documentation to remind the developer to set these values in the Export preset, but learned that this is a bug: https://github.com/godotengine/godot-docs/pull/4918

Noting that https://github.com/godotengine/godot/issues/48096 & https://github.com/godotengine/godot/issues/48220 look similar (could be related?), but not the same.

**Steps to reproduce:**
1. Set `Debug Keystore`, `Debug Keystore User`, and `Debug Keystore Pass` in the `Editor Settings` (following https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_android.html#setting-it-up-in-godot).
2. Add a new Android Export preset (Project -> Export -> Add -> Android).
3. Observe that no defaults have been provided for the Options -> Keystore `Debug`, `Debug User`, or `Debug Password` fields.

**Minimal reproduction project:**
[DemoDebugKeystoreIssue.zip](https://github.com/godotengine/godot/files/6493744/DemoDebugKeystoreIssue.zip)
^ This is just a blank project.

### PR DESCRIPTION
**Pull request by HaywardMorihara**
Warns the user when they provide one or two of the three keystore values (path, user, password) in the Android export presets, but not all three. If the user does not provide all three, then they will get an APK signing error that doesn't give any details (all it says is `'apksigner' returned with error #1`). See https://godotengine.org/qa/101943/error-apksigner-returned-with-error-%231

fixes https://github.com/godotengine/godot/issues/48787

### CODE REVIEW

**Comment by HaywardMorihara** [comment]
I didn't see any relevant unit tests to add to - is there a suite that I missed?

**Comment by Calinou** [comment]
> I didn't see any relevant unit tests to add to - is there a suite that I missed?

There are some unit tests for core classes, but none of the editor itself. You don't have to do anything more for this PR :slightly_smiling_face:

File: platform/android/export/export.cpp [hunk 1]
```diff
@@ -2028,6 +2028,13 @@ class EditorExportPlatformAndroid : public EditorExportPlatform {
 		// Validate the rest of the configuration.
 
 		String dk = p_preset->get("keystore/debug");
+		String dk_user = p_preset->get("keystore/debug_user");
+		String dk_password = p_preset->get("keystore/debug_password");
+
+		if ((dk.is_empty() || dk_user.is_empty() || dk_password.is_empty()) && (!dk.is_empty() || !dk_user.is_empty() || !dk_password.is_empty())) {
+			valid = false;
+			err += TTR("Either Debug keystore, Debug User AND Debug Password presets must be configured OR none of them.") + "\n";
```
Comment (Calinou) [inline platform/android/export/export.cpp:2036]: Use consistent capitalization and terminology:

```suggestion
			err += TTR("Either Debug Keystore, Debug User AND Debug Password settings must be configured OR none of them.") + "\n";
```

File: platform/android/export/export.cpp [hunk 2]
```diff
@@ -2038,6 +2045,13 @@ class EditorExportPlatformAndroid : public EditorExportPlatform {
 		}
 
 		String rk = p_preset->get("keystore/release");
+		String rk_user = p_preset->get("keystore/release_user");
+		String rk_password = p_preset->get("keystore/release_password");
+
+		if ((rk.is_empty() || rk_user.is_empty() || rk_password.is_empty()) && (!rk.is_empty() || !rk_user.is_empty() || !rk_password.is_empty())) {
+			valid = false;
+			err += TTR("Either Release keystore, Release User AND Release Password presets must be configured OR none of them.") + "\n";
```
Comment (Calinou) [inline platform/android/export/export.cpp:2053]: Use consistent capitalization and terminology:

```suggestion
			err += TTR("Either Release Keystore, Release User AND Release Password settings must be configured OR none of them.") + "\n";
```

**Review by Calinou — DISMISSED** [review]

**Review by m4gr3d — APPROVED** [review]

**Comment by Calinou** [comment]
@HaywardMorihara Looks good to me, please squash the commits together so we can merge this. See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase) for instructions :slightly_smiling_face:

**Comment by HaywardMorihara** [comment]
Squashed!

**Comment by HaywardMorihara** [comment]
Sorry to bother, just bumping this in case it got lost, thanks!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by HaywardMorihara** [comment]
> Thanks! And congrats for your first merged Godot contribution 🎉

@akien-mga Thank you! In fact, my first merge to any open-source project! Really appreciate all the guidance from you and @Calinou!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.3.
