### PR TITLE
Warn on filesystem case mismatch

### LINKED ISSUE #23441: macOS filesystems can be case insensitive, editor should also warn like Windows on case mismatch
I found an irritating bug that took a long time to track down. I was able to make a minimal reproducible project. The project would work when launching in Godot but crash immediately when launching on the exported Mac app.

Suppose we have a script like this:

```gdscript
# res://base/Bar.gd

extends Node
```

and another file

```gdscript
# res://Foo.gd

extends 'res://Base/Bar.gd'
```

Notice the capitalization mistake? Neither did I. Godot, I guess, will ignore capitalization in directories. The project runs just fine. It throws no errors. But when exporting to Mac, it will not launch. Caused me a lot of frustration.

Suggestions for a fix: make Godot case-sensitive with directories. Or at least throw a warning when capitalization does not match.

Edit: these tests were done on macOS.

### PR DESCRIPTION
**Pull request by fire**
Salvages https://github.com/godotengine/godot/pull/24860.

Fixes: https://github.com/godotengine/godot/issues/23441

### CODE REVIEW

**Review by AThousandShips — APPROVED** [review]

File: drivers/windows/file_access_windows.cpp [hunk 1]
```diff
@@ -127,7 +127,7 @@ Error FileAccessWindows::open_internal(const String &p_path, int p_mode_flags) {
 	}
 
 #ifdef TOOLS_ENABLED
-	// Windows is case insensitive, but all other platforms are sensitive to it
+	// Windows is case insensitive, but other platforms can be sensitive to it
```
Comment (mhilbrunner) [inline drivers/windows/file_access_windows.cpp:130]: I would just remove this sentence, or at least add a "by default" for Windows, because its also not strictly true anymore: https://learn.microsoft.com/en-us/windows/wsl/case-sensitivity

Comment (fire) [reply drivers/windows/file_access_windows.cpp]: Update to:

```c++
// Windows is case insensitive in the default configuration, but other platforms can be sensitive to it
```

**Review by Repiteo — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
