### PR TITLE
Changed logic and optimized ObjectID in ObjectDB and Variant, removed…

### LINKED ISSUE #32383: Reference to freed object can return a random different one
**Godot version & OS/device including version:**
3.1.1 Windows 10. 

**Issue description:**
I think this is a simple explanation of an issue I have on my project. I have raised this issue without an example project because it will take some time to reproduce in a simple form and I would like some godot experts to look at what I am describing, and let me know if the issue is already logged and known (and perhaps fixed) before I spend more time working on a reproduction cases

----
Say I have a RobotFactory class and it can instantiate Robots, but it is only allowed to have one active in the world at once.  It saves the instantiated robot in a var. 

var my_robot = RobotScene.instance()

The robot walks around the world for a while an then is destroyed by something so in its own script it calls queue_free() on itself. 

Sometime later in the RobotFactory we call is_instance_valid(my_robot) to see if we should create a new robot. 

In my project I have found that sometimes is_instance_valid(my_robot) returns true after my_robot has been freed, but that it is pointing to some other random object in the scene that has been instantiated. Perhaps sometime after the queue_free, but before is_instance_valid call. 

The only thing I think could be happening is that there is some kind of underlying pooling system and my_robot is pointing to somewhere that is being reused after the robot is freed. 

Please let me know if this is a known issue, is already logged, or if I should do some more work to explain the issue better. 

---

*Bugsquad edit:* Keyword: previously freed instance

### PR DESCRIPTION
**Pull request by reduz**
Refactored how ObjectID works in ObjectDB, it is now very fast to obtain an object pointer from an ObjectID. Also, RefPtr was removed and the referencing logic for Refecence has been replicated inside Variant. This hugely simplifies the code and logic.

Finally, the functions to check if an object pointer is invalid were removed given they are dangerous and unfixable. Instead, Variant now contains an ObjectID together with the pointer, which ensures validity can be checked at all times.

Also fixes #32383

### CODE REVIEW

File: core/object.h [hunk 1]
```diff
@@ -680,8 +685,8 @@ class Object {
 
 	/* SCRIPT */
 
-	void set_script(const RefPtr &p_script);
```
Comment (reduz) [inline core/object.h]: Had to do this because RefPtr no longer exists, should be fine I think

File: core/object.h [hunk 2]
```diff
@@ -760,49 +766,63 @@ void postinitialize_handler(Object *p_object);
 
 class ObjectDB {
 
-	struct ObjectPtrHash {
```
Comment (reduz) [inline core/object.h]: Doubt we will ever have more than 16 million object simultaneous  instances, if we do we can always change this :P but giving priority (more bits) to the validator is usually better.

File: core/variant.cpp [hunk 3]
```diff
@@ -1589,14 +1617,12 @@ String Variant::stringify(List<const void *> &stack) const {
 		case OBJECT: {
 
 			if (_get_obj().obj) {
-#ifdef DEBUG_ENABLED
-				if (ScriptDebugger::get_singleton() && _get_obj().ref.is_null()) {
+
+				if (ScriptDebugger::get_singleton() && !_get_obj().id.is_reference() && ObjectDB::get_instance(_get_obj().id) == nullptr) {
 					//only if debugging!
```
Comment (RandomShaper) [inline core/variant.cpp]: Since the other _only if debugging_ comments have gone away, this one should too.

Please don't kill me for this.

File: core/variant.cpp [hunk 4]
```diff
@@ -1589,14 +1617,12 @@ String Variant::stringify(List<const void *> &stack) const {
 		case OBJECT: {
 
 			if (_get_obj().obj) {
-#ifdef DEBUG_ENABLED
```
Comment (RandomShaper) [inline core/variant.cpp]: Shouldn't this `#ifdef` stay?

File: core/variant.cpp [hunk 5]
```diff
@@ -2309,7 +2337,24 @@ Variant::Variant(const Object *p_object) {
 	type = OBJECT;
 
 	memnew_placement(_data._mem, ObjData);
-	_get_obj().obj = const_cast<Object *>(p_object);
+
+	if (p_object) {
+
+		if (p_object->is_reference()) {
+			Reference *reference = const_cast<Reference *>(static_cast<const Reference *>(p_object));
+			if (!reference->reference()) {
```
Comment (neikeq) [inline core/variant.cpp]: Shouldn't this be `init_ref()` as one can do `Variant(memnew(Reference))`?

File: core/object.cpp [hunk 6]
```diff
@@ -979,7 +979,7 @@ void Object::set_script_and_instance(const RefPtr &p_script, ScriptInstance *p_i
 	script_instance = p_instance;
 }
 
-void Object::set_script(const RefPtr &p_script) {
+void Object::set_script(const Variant &p_script) {
```
[the remark this answers is not in the document]
Comment (reduz) [reply core/object.cpp]: you can't, because Ref uses Reference, which inherits Object.. and since its a template, you can't forward declare it.

File: core/variant.cpp (hunk 5 above)
Comment (reduz) [reply core/variant.cpp]: I think the problem is that this is used for initializing the reference, which is not supposed to be something you make within Variant.. so I wonder if we could more or less forbid it.

File: core/object.h [hunk 7]
```diff
@@ -760,49 +766,63 @@ void postinitialize_handler(Object *p_object);
...
+		Object *object;
 	};
 
-	static HashMap<ObjectID, Object *> instances;
-	static HashMap<Object *, ObjectID, ObjectPtrHash> instance_checks;
+	static SpinLock spin_lock;
+	static uint32_t slot_count;
+	static uint32_t slot_max;
+	static ObjectSlot *object_slots;
+	static uint64_t validator;
```
Comment (akien-mga) [inline core/object.h]: Huge amount of warnings due to this:
```
./core/object.h: In static member function 'static Object* ObjectDB::get_instance(ObjectID)':
./core/object.h:811:12: warning: declaration of 'validator' shadows a previous local [-Wshadow=local]
   uint64_t validator = (id >> OBJECTDB_SLOT_MAX_COUNT_BITS) & OBJECTDB_VALIDATOR_MASK;
            ^~~~~~~~~
./core/object.h:787:18: note: shadowed declaration is here
  static uint64_t validator;
                  ^~~~~~~~~
```

Do you build with `warnings=no`? ;)

File: core/object.h [hunk 8]
```diff
@@ -760,49 +766,63 @@ void postinitialize_handler(Object *p_object);
...
+		uint64_t id = p_instance_id;
+		uint32_t slot = id & OBJECTDB_SLOT_MAX_COUNT_MASK;
+
+		ERR_FAIL_COND_V(slot >= slot_max, nullptr); //this should never happen unless RID is corrupted
+
+		spin_lock.lock();
 
-	_FORCE_INLINE_ static bool instance_validate(Object *p_ptr) {
-		rw_lock->read_lock();
+		uint64_t validator = (id >> OBJECTDB_SLOT_MAX_COUNT_BITS) & OBJECTDB_VALIDATOR_MASK;
```
Comment (akien-mga) [inline core/object.h]: Huge amount of warnings due to this:
```
./core/object.h: In static member function 'static Object* ObjectDB::get_instance(ObjectID)':
./core/object.h:811:12: warning: declaration of 'validator' shadows a previous local [-Wshadow=local]
   uint64_t validator = (id >> OBJECTDB_SLOT_MAX_COUNT_BITS) & OBJECTDB_VALIDATOR_MASK;
            ^~~~~~~~~
./core/object.h:787:18: note: shadowed declaration is here
  static uint64_t validator;
                  ^~~~~~~~~
```

Do you build with `warnings=no`? ;)

File: core/object.cpp [hunk 9]
```diff
@@ -1993,96 +2001,139 @@ void postinitialize_handler(Object *p_object) {
...
-}
+#ifdef DEBUG_ENABLED
 
-RWLock *ObjectDB::rw_lock = NULL;
+	if (object_slots[slot].object != p_object) {
+		spin_lock.unlock();
+		ERR_FAIL_COND(object_slots[slot].object != p_object);
+	}
+	{
+		uint64_t validator = (t >> OBJECTDB_SLOT_MAX_COUNT_BITS) & OBJECTDB_VALIDATOR_MASK;
```
Comment (akien-mga) [inline core/object.cpp]: Also shadowing `validator` here.

**Comment by akien-mga** [comment]
This fixes the mono build:
```diff
diff --git a/modules/mono/csharp_script.cpp b/modules/mono/csharp_script.cpp
index 43cdd19411..c722076fe2 100644
--- a/modules/mono/csharp_script.cpp
+++ b/modules/mono/csharp_script.cpp
@@ -854,7 +854,7 @@ void CSharpLanguage::reload_assemblies(bool p_soft_reload) {
 
 		while (script->instances.front()) {
 			Object *obj = script->instances.front()->get();
-			obj->set_script(RefPtr()); // Remove script and existing script instances (placeholder are not removed before domain reload)
+			obj->set_script(REF()); // Remove script and existing script instances (placeholder are not removed before domain reload)
 		}
 
 		script->_clear();
@@ -877,7 +877,7 @@ void CSharpLanguage::reload_assemblies(bool p_soft_reload) {
 
 				// Use a placeholder for now to avoid losing the state when saving a scene
 
-				obj->set_script(scr.get_ref_ptr());
+				obj->set_script(scr);
 
 				PlaceHolderScriptInstance *placeholder = scr->placeholder_instance_create(obj);
 				obj->set_script_instance(placeholder);
@@ -1003,7 +1003,7 @@ void CSharpLanguage::reload_assemblies(bool p_soft_reload) {
 				CRASH_COND(si != NULL);
 #endif
 				// Re-create script instance
-				obj->set_script(script.get_ref_ptr()); // will create the script instance as well
+				obj->set_script(script); // will create the script instance as well
 			}
 		}
 
diff --git a/modules/mono/mono_gd/gd_mono_internals.cpp b/modules/mono/mono_gd/gd_mono_internals.cpp
index 75aa77c7b0..74ffa90cb3 100644
--- a/modules/mono/mono_gd/gd_mono_internals.cpp
+++ b/modules/mono/mono_gd/gd_mono_internals.cpp
@@ -107,7 +107,7 @@ void tie_managed_to_unmanaged(MonoObject *managed, Object *unmanaged) {
 
 	ScriptInstance *si = CSharpInstance::create_for_managed_type(unmanaged, script.ptr(), gchandle);
 
-	unmanaged->set_script_and_instance(script.get_ref_ptr(), si);
+	unmanaged->set_script_and_instance(script, si);
 }
 
 void unhandled_exception(MonoException *p_exc) {
```

See above note on shadowing though, this warning spams the build a lot.

File: core/variant.cpp (hunk 5 above)
Comment (reduz) [reply core/variant.cpp]: or maybe I guess it would not hurt

File: core/variant.cpp (hunk 4 above)
Comment (reduz) [reply core/variant.cpp]: No... stringify is not something that will affect performance anyway so it should be fine. The ifdefs were there because the reverse hash map in 3.x at some point was removed durin release build but then kept. Now it's gone so there is no longer a point.

File: core/variant.cpp (hunk 3 above)
Comment (reduz) [reply core/variant.cpp]: alright

File: core/variant.cpp (hunk 5 above)
Comment (neikeq) [reply core/variant.cpp]: Whether it's meant or not to be used like that, it's possible and if that happens it will result in a bug hard to debug.

File: core/variant.cpp (hunk 4 above)
Comment (RandomShaper) [reply core/variant.cpp]: That's not the reason for my comment (the `#endif` ends anyway before the call to `to_string()`).

My point is that all other `if (ScriptDebugger::get_singleton() [...]` checks are inside an `#ifdef DEBUG_ENABLED`, because there's no point in non-debug builds. It's only for consistency.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
