### PR TITLE
Fix script editor guideline colors

### LINKED ISSUE #118817: Script editor line length guidelines are hard to see with the new default color preset since 4.6 (especially on light theme)
### Tested versions

- Reproducible in: 4.6.stable, 4.7.dev f94bbfc07
- Not reproducible in: 4.5.2.stable (except for light theme, in which case it's always reproducible)

### System information

Godot v4.7.dev (f94bbfc07) - Fedora Linux 43 (KDE Plasma Desktop Edition) on X11 - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 5090 (nvidia; 580.126.18) - AMD Ryzen 9 9950X3D 16-Core Processor (32 threads) - 62.33 GiB memory

### Issue description

On the default (dark) theme, both line length guidelines became significantly less visible since 4.6 with the introduction of the Modern theme and its new default color preset (with a lower contrast than before). That said, switching to the Classic theme does not restore the lines' contrast back to how it was in 4.5. Instead, you need to set Color Preset to Godot 3 to get the previous lines' contrast back.

On a light theme, the soft line length guidelines is invisible, and the hard line length guideline is very hard to see. This is not a new issue in the Modern theme; it was already present in 4.5.

While you can manually adjust the line length guideline colors in the Editor Settings, we should adjust the default opacity of the line length guidelines to resolve this issue on the default and light color presets at least.

### Default

4.6+ | 4.5
-|-
Image | Image

### Light

4.6+ | 4.5
-|-
Image | Image

### Steps to reproduce

- Create a new script, then look at the lines drawn at columns 80 and 100.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by passivestar**
Closes https://github.com/godotengine/godot/issues/118817

| Old | New |
|--------|--------|
|  |  |
|  |  |
|  |  |

### CODE REVIEW

File: editor/themes/editor_theme_manager.cpp [hunk 1]
```diff
@@ -528,7 +528,7 @@ void EditorThemeManager::_populate_text_editor_styles(const Ref<EditorTheme> &p_
 			colors["text_editor/theme/highlighting/selection_color"] = p_config.selection_color;
 			colors["text_editor/theme/highlighting/brace_mismatch_color"] = p_config.dark_icon_and_font ? p_config.error_color : Color(1, 0.08, 0, 1);
 			colors["text_editor/theme/highlighting/current_line_color"] = alpha1;
-			colors["text_editor/theme/highlighting/line_length_guideline_color"] = p_config.dark_icon_and_font ? p_config.base_color : p_config.dark_color_2;
+			colors["text_editor/theme/highlighting/line_length_guideline_color"] = p_config.base_color.lerp(Color(0, 0, 0), p_config.contrast * -1.25).clamp();
```
Comment (Calinou) [inline editor/themes/editor_theme_manager.cpp:533]: It might be worth adding a comment to explain why we're `lerp()`ing with a negative value (if contrast is positive), as this doesn't look very intuitive.

**Review by Calinou — COMMENTED** [review]
In terms of colors, this looks good to me.

Note that this also makes soft line length guidelines look slightly more opaque in projects using CodeEdit (with more than one line length guideline), but it's a subtle change so it's probably fine.

File: editor/themes/editor_theme_manager.cpp (hunk 1 above)
Comment (passivestar) [reply editor/themes/editor_theme_manager.cpp:533]: Done.

> if contrast is positive

It's positive in dark themes and negative in light themes by default, and some users don't use the default contrast sign in settings. Negative multiplier in that line pushes luminance in the opposite direction of regular luminance shift to make the lines visible against their background.

It's not as intuitive as a ternary at a glance, but it ensures that the value actually works with any editor settings.

**Review by YeldhamDev — APPROVED** [review]
Looks fine. Hopefully the small change of guideline opacity in `CodeEdit` doesn't affect anyone's project.

**Comment by Repiteo** [comment]
Thanks!
