### PR TITLE
Skeleton rest fixer: Apply orthonormalized scale to anims

### LINKED ISSUE #91893: [4.3] Mesh disappears when importing an AnimationLibrary onto a GeneralSkeleton
### Tested versions

* Reproducible in 4.3-dev6
* Not reproducible in 4.2.2.stable

### System information

Windows 11, geForce 4080, Godot 4.3-dev6, Forward+

### Issue description

I have an anim library I've applied a bone map on and an armature with mesh I've also applied a bone map on. Both are taken from mixamo. When I create an inherited scene from the mesh GLB, add an animation player and import my anim library in 4.2, things work exactly as they should. The same process in 4.3-dev6 causes the entire mesh to disappear.

image

Example video: https://www.youtube.com/watch?v=9Ob5M0YIgQs

### Steps to reproduce

- Have a character and some animations downloaded from mixamo. Mine are in an anim library.
- Apply a bone map with default settings to both the character and anim library.
- Create inherited scene from the character GLB. Add an animation player
- Load the AnimationLibrary into the anim player

### Minimal reproduction project (MRP)

Godot 4.2.2 project: [TestMixamo42.zip](https://github.com/godotengine/godot/files/15290104/TestMixamo42.zip)
Godot 4.3-dev6 project: [testmixamo43d6.zip](https://github.com/godotengine/godot/files/15290105/testmixamo43d6.zip)

In both:
* Open Main.tscn
* Click on the AnimationPlayer and load the animation library

### PR DESCRIPTION
**Pull request by lyuma**
Adjust the logic for position and scale animation tracks in the Apply Node Transforms case To match how we adjust bone pose/rest, use basis.orthonormalized() for parentless bones.

Fixes #91893 
Cc @TokageItLab @fire

### CODE REVIEW

File: editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp [hunk 1]
```diff
@@ -204,7 +204,7 @@ void PostImportPluginSkeletonRestFixer::internal_process(InternalImportCategory
 								} else {
 									for (int j = 0; j < key_len; j++) {
 										Basis sc = Basis().scaled(static_cast<Vector3>(anim->track_get_key_value(i, j)));
-										anim->track_set_key_value(i, j, (global_transform.basis * sc).get_scale());
+										anim->track_set_key_value(i, j, (global_transform.orthonormalized().basis * sc).get_scale());
```
Comment (AThousandShips) [inline editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:207]: Do we need to orthonormalize the transform or just the basis? Like so:
```suggestion
										anim->track_set_key_value(i, j, (global_transform.basis.orthonormalized() * sc).get_scale());
```

Comment (TokageItLab) [inline editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:207]: I assume this is not a valid solution for bones that are intentionally scaled as glTF, as there is no guarantee that this is normalized.

I think there is a guarantee that glTF bones exported from Blender will be scale normalized but it is not for all glTF.

So, if we do this, wouldn't we need to process the Apply Node Scale to set the Scale of all bones to 1?

Comment (lyuma) [reply editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:207]: To be honest, I am not sure. The point is that this calculation should be identical to line 136, where they also wrote it this way.

Comment (AThousandShips) [reply editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:207]: Looking at the code in `Transform3D` it's identical, wasn't sure if there was some unnecessary computations done in the `Transform3D` method so it's equivalent

Comment (lyuma) [reply editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:207]: Why would it be invalid for scaled bones? global_transforms is the global scale adjustment propagated from nodes, and that is what is being orthonormalized. The point of Apply Node Transforms is to make these transforms identity. The code is not orthonormalizing the scale and so still apply any non-uniform local bone scales.

if your assertion is that this code is wrong, then line 146 (set_bone_pose_scale) would also be wrong. But I would need to see a test case

Comment (TokageItLab) [reply editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:207]: I think line 136 is correct, but the code to apply scaling to each bone is lacking.

Also, I think the code for the scale track around line 200 is wrong: the position track is scaled, but the scale track should be multiplied by the inverse.

Comment (TokageItLab) [reply editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:207]: For test cases, you should have tested only:

```
Skeleton: scale = (0.01, 0.01, 0.01)
L Hips: scale = (1.0, 1.0, 1.0)
  L Spine: scale = (1.0, 1.0, 1.0)
    L Chest: scale = (1.0, 1.0, 1.0)
```

So, the following should be tested:

```
Skeleton: scale = (1.0, 1.0, 1.0)
L Hips: scale = (0.1, 0.1, 0.1)
  L Spine: scale = (0.1, 0.1, 0.1)
    L Chest: scale = (1.0, 1.0, 1.0)
```
```
Skeleton: scale = (1.0, 1.0, 1.0)
L Hips: scale = (1.0, 1.0, 1.0)
  L Spine: scale = (0.1, 0.1, 0.1)
    L Chest: scale = (1.0, 1.0, 1.0)
```
```
Skeleton: scale = (1.0, 1.0, 1.0)
L Hips: scale = (1.0, 1.0, 1.0)
  L Spine: scale = (2.0, 1.0, -1.0)
    L Chest: scale = (1.0, 1.0, 1.0)
```

I guess the only restriction on the bone scale that glTF has is orthogonal. So I expect that scale(0, 0, 0) would not be acceptable, but something like scale(0.001, 0.001, 0.001) or scale(1, 2, 1) would be acceptable

Comment (TokageItLab) [reply editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:207]: > Suppose we have a model with a neck rest scale of 0.001 for headless-able model like Dullahan, and an animation key value with a pose scale of 1.0 for the neck with a head for retargeting. If the rest scale of the neck is set to 1.0, then the animation key value should be 1000.0.

Ah, I missed that this is the PR to do that. If so, this change may be correct.

However, apart from this, I am wondering if the past remove immutable tracks are dead code due to the #90064 change, are they still being used for something other than Skeleton?

Comment (fire) [reply editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:207]: Are you aware of the difference between orthonormal (uniform scale) and orthogonal (non uniform scale) methods on basis?

Comment (fire) [reply editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:207]: https://github.com/godotengine/godot/blob/5708a3a02e00061e03366f2dabf8942df66fedca/core/math/basis.cpp#L80

Comment (fire) [reply editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:207]: https://github.com/godotengine/godot/blob/5708a3a02e00061e03366f2dabf8942df66fedca/core/math/basis.cpp#L56

Comment (TokageItLab) [reply editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:207]: Yes, I assume the glTF restriction is orthogonal with no isotropic and allows non-uniform scale, but please point out if I'm wrong. However, I am getting a bit off-topic.

I think we need to make a new proposal on how to handle individual bone scales.

**Comment by TokageItLab** [comment]
For now, I think it is fine about this fix. My only concern for now about remove immutable tracks is:

> However, apart from this, I am wondering if the past remove immutable tracks are dead code due to the https://github.com/godotengine/godot/pull/90064 change, are they still being used for something other than Skeleton?

If we need it for something other than Skeleton, we need to consider whether that code can be commonized with what we added in #90064.

P.S. BTW, I will send another proposal later for bones which have own scales.

**Review by TokageItLab — APPROVED** [review]
For now, I think it is fine about this fix. My only concern for now about remove immutable tracks is:

> However, apart from this, I am wondering if the past remove immutable tracks are dead code due to the https://github.com/godotengine/godot/pull/90064 change, are they still being used for something other than Skeleton?

If we need it for something other than Skeleton, we need to consider whether that code can be commonized with what we added in #90064.

P.S. BTW, I will send another proposal later for bones which have own scales.

**Review by fire — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
