### PR TITLE
Fix "grab_focus: Condition "!is_inside_tree()" is true" when AcceptDialog was visible from the editor.

### LINKED ISSUE #65363: Opening a scene with a visible-enabled `AcceptDialog` gets an error
### Godot version

3e6c34299

### System information

Linux mint 21, NVIDIA GeForce GTX 1050 Ti, Vulkan API 1.2.0

### Issue description

```
ERROR: Condition "!is_inside_tree()" is true.
   at: grab_focus (scene/gui/control.cpp:1853)
```
When opening a scene with a visible-enabled `AcceptDialog`, you will get the above error message.

### Steps to reproduce

1. Add an `AcceptDialog` to a scene;
2. Make the `AcceptDialog` visible;
3. Close and reopen the scene.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by ItsNL**
Fix  #65363

The error happened when the AcceptDialog's visibility was turned on from the editor. When trying to grab the focus the node was not in the tree yet.
I moved the grab focus that happened in `NOTIFICATION_VISIBILITY_CHANGED` to:

`NOTIFICATION_READY`: To check if it was visible and be able to grab the focus. (When ready the node is already in the tree so it has no problems). This only turns grabs the focus on ready.

I also added a check in the `NOTIFICATION_VISIBILITY_CHANGED`. It checks if the ok button is in the tree. If its is, `grab_focus` is called. This allows the focus happen when turning visibility on and off during the game.

It is not compatible with the 3.x branch because the Dialog is different. They can't be showed from the editor and need the `popup()` method to be visible. Anyways, this error doesn't happen in 3.x versions.

image

### CODE REVIEW

**Comment by Rindbee** [comment]
`NOTIFICATION_READY` will only occur once by default, while `NOTIFICATION_ENTER_TREE` may occur multiple times. (move in TreeDock)

Maybe it might be better to consider using ok_button's `tree_entered`/`tree_exited` signals.

**Comment by ItsNL** [comment]
> `NOTIFICATION_READY` will only occur once by default, while `NOTIFICATION_ENTER_TREE` may occur multiple times. (move in TreeDock)
> 
> Maybe it might be better to consider using ok_button's `tree_entered`~/`tree_exited`~ signals.

I've been trying with the `NOTIFICATION_ENTER_TREE` notification, but the problem still happens.
image
Looks like when the node enters the tree, the Ok Button is not in the tree yet, so the `!is_inside_tree()` returns `true`.

I've also checked if, using `NOTIFICATION_READY`, some type of error occurs when I reorder AcceptDialog in the SceneTree but no errors happen. But the focus get lost.

I ended up using `NOTIFICATION_POST_ENTER_TREE`. Which is called later than `NOTIFICATION_ENTER_TREE` and the OK button is already in the tree when emitted.

File: scene/gui/dialogs.cpp [hunk 1]
```diff
@@ -90,7 +97,6 @@ void AcceptDialog::_notification(int p_what) {
 			}
 		} break;
 
-		case NOTIFICATION_READY:
```
Comment (YuriSizov) [inline scene/gui/dialogs.cpp:93]: This removal doesn't seem relevant to the fix.

Comment (ItsNL) [reply scene/gui/dialogs.cpp:93]: You're right. I'm sorry, I used that notification in the first commit so I deleted the empty one. When I changed it to `NOTIFICATION_POST_TREE_ENTERED` I forgot to add it again. I'm updating it now!

**Comment by YuriSizov** [comment]
You've re-added it in a wrong place, should be together with `NOTIFICATION_WM_SIZE_CHANGED`. Also, please squash your commits. Your PR must only contain one.

**Review by YuriSizov — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
