### PR TITLE
Vulkan: Disable layers in editor deemed buggy by RenderDoc

### LINKED ISSUE #103800: Godot 4.4 silently closes when using OBS advanced scene switcher (detects active window). GameCapture Mode
### Tested versions

4.4 issue
4.3 works fine

### System information

Godot v4.4.stable - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 (NVIDIA; 32.0.15.6636) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 threads)

### Issue description

4.4 Godot Crashes when tabbing into other windows using OBS Scene Switcher Plugin(which detects the current window and changes scene)

I will temporarily go back to 4.3 which does not do this.

 I'm not sure what options in the editor have changed or if there are some options I can tick to help with this. I've tried many different options. I know the detection of windows isn't youre problem, but why did it work flawlessly in 4.3?

It only happens if im using GameCapture for Godot 4.4. I just dont want to stream my whole display monitor. I use the advanced scene switcher plugin to make devlogs. Switching scenes between my notes, editor, ect.

No errors. Just my Godot disappears and closes when I tab into other windows. It works fine if Godot isn't Game Capture. 

Did anything change in 4.4 for window detection and compatibility with OBS? Ive even tried setting godot 4.4 to single window mode.

### Steps to reproduce

Open Godot 4.4,

Have scene setup in game capture mode for Godot 4.4.

Use Window Detection with another application ( OBS Automatic Scene Switcher)

Scenes automatically switch based on the active window.

Godot crashes when tabbing into other windows.

Open Godot 4.3

Repeat steps.

Godot does not close/crash

### Minimal reproduction project (MRP)

Happens with any 4.4 project. Even brand new ones.

Unable to replicate in 4.3

### PR DESCRIPTION
**Pull request by unvermuthet**
Potentially fixes #103800

This adds the following buggy layers to be disabled in the editor
```
DISABLE_VULKAN_OBS_CAPTURE
DISABLE_VULKAN_OW_OBS_CAPTURE
DISABLE_SAMPLE_LAYER
DISABLE_GAMEPP_LAYER
DISABLE_VK_LAYER_TENCENT_wegame_cross_overlay_1
NODEVICE_SELECT
DISABLE_VK_LAYER_GPUOpen_GRS
```

According to [RenderDoc](https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/driver/vulkan/vk_layer.cpp#L118-L159)

### CODE REVIEW

**Comment by bruvzg** [comment]
We should probably add all the layer from [RenderDoc](https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/driver/vulkan/vk_layer.cpp#L118-L159) to the list at once, instead of adding them one by one.

**Comment by unvermuthet** [comment]
Alright, I'm on it.

**Comment by unvermuthet** [comment]
I checked across the codebase and didn't see `PackedStringArray` used with `std::initializer_list<String>` even a single time in production code. Is there a reason?

**Comment by Calinou** [comment]
> DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1

This is a Windows-only layer that is already disabled here:

https://github.com/godotengine/godot/blob/0028fd625e2c5b202e204bc12828cbca043213d3/platform/windows/rendering_context_driver_vulkan_windows.cpp#L43-L49

**Comment by unvermuthet** [comment]
I removed `DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1` from the list

File: main/main.cpp [hunk 1]
```diff
@@ -2517,24 +2517,36 @@ Error Main::setup(const char *execpath, int argc, char *argv[], bool p_second_ph
...
+			// Disable Vulkan overlays in editor, they cause various issues.
+			for (int i = 0; i < layers_to_disable.size(); i++) {
+				OS::get_singleton()->set_environment(layers_to_disable[i], "1");
+			}
+		} else {
+			// Re-allow using Vulkan overlays, disabled while using the editor.
+			for (int i = 0; i < layers_to_disable.size(); i++) {
+				OS::get_singleton()->unset_environment(layers_to_disable[i]);
+			}
+		}
```
Comment (akien-mga) [inline main/main.cpp:2549]: I would use a `LocalVector` here, `PackedStringArray` is only meant when using APIs that interface with Variant / method bindings.

```suggestion
		LocalVector<String> layers_to_disable = {
				"DISABLE_RTSS_LAYER", // GH-57937.
				"DISABLE_VULKAN_OBS_CAPTURE", // GH-103800.
				"DISABLE_VULKAN_OW_OBS_CAPTURE", // GH-104154.
				"DISABLE_SAMPLE_LAYER", // GH-104154.
				"DISABLE_GAMEPP_LAYER", // GH-104154.
				"DISABLE_VK_LAYER_TENCENT_wegame_cross_overlay_1", // GH-104154.
				"NODEVICE_SELECT", // GH-104154.
				"VK_LAYER_bandicam_helper_DEBUG_1", // GH-101480.
				"DISABLE_VK_LAYER_bandicam_helper_1", // GH-101480.
				"DISABLE_VK_LAYER_reshade_1", // GH-70849.
				"DISABLE_VK_LAYER_GPUOpen_GRS", // GH-104154.
				"DISABLE_MANGOHUD", // GH-57403.
				"DISABLE_VKBASALT",
		};

		if (editor || project_manager) {
			// The editor and project manager always detect and use hiDPI if needed.
			OS::get_singleton()->_allow_hidpi = true;
			// Disable Vulkan overlays in editor, they cause various issues.
			for (const String &layer_disable : layers_to_disable) {
				OS::get_singleton()->set_environment(layer_disable, "1");
			}
		} else {
			// Re-allow using Vulkan overlays, disabled while using the editor.
			for (const String &layer_disable : layers_to_disable) {
				OS::get_singleton()->unset_environment(layer_disable);
			}
		}
```

Comment (akien-mga) [reply main/main.cpp]: > I would use a `LocalVector` here, `PackedStringArray` is only meant when using APIs that interface with Variant / method bindings.

BTW that's the reason for what you noticed:

> I checked across the codebase and didn't see `PackedStringArray` used with `std::initializer_list<String>` even a single time in production code. Is there a reason?

**Review by akien-mga — APPROVED** [review]

File: main/main.cpp [hunk 2]
```diff
@@ -2517,24 +2517,38 @@ Error Main::setup(const char *execpath, int argc, char *argv[], bool p_second_ph
...
+				"DISABLE_VULKAN_OW_OBS_CAPTURE", // GH-104154.
+				"DISABLE_SAMPLE_LAYER", // GH-104154.
+				"DISABLE_GAMEPP_LAYER", // GH-104154.
+				"DISABLE_VK_LAYER_TENCENT_wegame_cross_overlay_1", // GH-104154.
+				"NODEVICE_SELECT", // GH-104154.
+				"VK_LAYER_bandicam_helper_DEBUG_1", // GH-101480.
+				"DISABLE_VK_LAYER_bandicam_helper_1", // GH-101480.
+				"DISABLE_VK_LAYER_reshade_1", // GH-70849.
+				"DISABLE_VK_LAYER_GPUOpen_GRS", // GH-104154.
+				"DISABLE_LAYER", // fpsmon
```
Comment (unvermuthet) [inline main/main.cpp:2534]: Should this comment maybe just point to this PR too? Or maybe replace all comments pointing to this PR with a `*` and say `* = synced with ...`

Comment (unvermuthet) [reply main/main.cpp]: I pointed to this PR and added the period according to the comment style.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 4.4.1.

File: main/main.cpp [hunk 3]
```diff
@@ -2517,24 +2517,38 @@ Error Main::setup(const char *execpath, int argc, char *argv[], bool p_second_ph
...
+	{
+		// Synced with https://github.com/baldurk/renderdoc/blob/2b01465c7/renderdoc/driver/vulkan/vk_layer.cpp#L118-L165
+		LocalVector<String> layers_to_disable = {
+			"DISABLE_RTSS_LAYER", // GH-57937.
+			"DISABLE_VULKAN_OBS_CAPTURE", // GH-103800.
+			"DISABLE_VULKAN_OW_OBS_CAPTURE", // GH-104154.
+			"DISABLE_SAMPLE_LAYER", // GH-104154.
+			"DISABLE_GAMEPP_LAYER", // GH-104154.
+			"DISABLE_VK_LAYER_TENCENT_wegame_cross_overlay_1", // GH-104154.
+			"NODEVICE_SELECT", // GH-104154.
```
Comment (akien-mga) [inline main/main.cpp:2529]: I propose reverting this one in https://github.com/godotengine/godot/pull/104592 as this layer is actually useful, and so far we're not aware of it causing problems for Godot.

Comment (unvermuthet) [reply main/main.cpp:2529]: Sounds good!
