### PR TITLE
[4.0] [GUI] Fix LineEdit clearing

### LINKED ISSUE #45245: The clear button of LineEdit can not delete the text on iOS devices.
**Godot version:**
3.2.x

**OS/device including version:**

**Issue description:**

after clear the text of LineEdit by click the clear button, the text disappeared, however, when continue to input characters, the original text still displayed and the new input characters is append to it.

**Steps to reproduce:**
1. add a LineEdit 
2. enable clear button in the property of LineEdit
3. input some text
4. click clear button to clear the text
5. continue to input
6. the cleared text plus the new text displayed in the LineEdit.

The above behavior only happened on iOS devices.

And the following behavior happened on iOS and Android devices.
After clicking the clear button, the suggestion words on the soft keyboard  is not cleared, which will be cleared on the UITextField.

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by naithar**
Fixes `LineEdit` not updating text value for iOS backing `UITextView`.
Also should fix Android's not clearing suggestions on clearing the `LineEdit`.

Fixes https://github.com/godotengine/godot/issues/45245 in `master`

### CODE REVIEW

File: scene/gui/line_edit.cpp [hunk 1]
```diff
@@ -1407,6 +1394,21 @@ Array LineEdit::get_structured_text_bidi_override_options() const {
 void LineEdit::clear() {
 	clear_internal();
 	_text_changed();
+
+	// This should reset virtual keyboard keyboard state if needed.
```
Comment (akien-mga) [inline scene/gui/line_edit.cpp:1398]:
```suggestion
	// This should reset virtual keyboard state if needed.
```

**Review by bruvzg — APPROVED** [review]
The same change might be useful to update virtual keyboard text in the other text changing functions (like `set_text`, e.t.c.). For example, when text is changed from `text_changed`/`text_entered` callback.

**Comment by naithar** [comment]
> The same change might be useful to update virtual keyboard text in the other text changing functions (like `set_text`, e.t.c.). For example, when text is changed from `text_changed`/`text_entered` callback.

The problem with `clear` is that (at least on iOS) focus notification is handled before `clear` method gets called, so we have old data passed into the backend text views. 
Not sure this can happen with other methods, but I might be wrong.

**Comment by akien-mga** [comment]
Thanks!
