### PR TITLE
Fix certain characters being recognized as special keys on Windows when using the us international layout

### LINKED ISSUE #25548: Writing quotation marks makes cursor jump to the bottom of the page [Windows, US International layout]
**Godot version:**
Godot 3.1 beta3, and beta2

**OS/device including version:**
Windows 7 (EDIT: i forgot to add that I'm using and American International layout for my keyboard)

**Issue description:**
When i try to write in a script a quotation mark, the cursor jumps down to the bottom of the page, selecting everything in between

image

**Steps to reproduce:**
Write a quotation mark at the top of a script

**Minimal reproduction project:**
It works for every script

### PR DESCRIPTION
**Pull request by ericrybick**
As supposed by the participants of #25548, the problem is that certain characters emit special key signals additionally. I found [this](https://stackoverflow.com/a/8181107) post on stackoverflow bringing some light into the darkness. 

I have implemented a simple check to see if a WM_CHAR message sends a special key signal, and if so, the message is discarded.

Fixes #25548

### CODE REVIEW

File: platform/windows/key_mapping_windows.cpp [hunk 1]
```diff
@@ -335,6 +336,8 @@ static _WinTranslatePair _scancode_to_keycode[] = {
 	{ KEY_UNKNOWN, 0 }
 };
 
+static std::unordered_set<unsigned int> _extended_keys({ VK_INSERT, VK_DELETE, VK_HOME, VK_END, VK_PRIOR, VK_NEXT, VK_LEFT, VK_UP, VK_RIGHT, VK_DOWN });
```
Comment (akien-mga) [inline platform/windows/key_mapping_windows.cpp:339]: We have our own container types in Godot and don't use STL ones, see `core/list.h`, `core/set.h` and `core/vector.h`.

While it doesn't make a big difference here, I'd ask to change it to use a Godot container (not sure which is best for the use case but `Set<int>` or `Vector<int>` should work fine for such a simple set).

File: platform/windows/key_mapping_windows.cpp [hunk 2]
```diff
@@ -411,3 +414,7 @@ unsigned int KeyMappingWindows::get_scansym(unsigned int p_code, bool p_extended
 
 	return keycode;
 }
+
+bool KeyMappingWindows::is_extended_key(unsigned int p_code) {
+	return _extended_keys.count(p_code) > 0 ? true : false;
```
Comment (ThakeeNathees) [inline platform/windows/key_mapping_windows.cpp:419]: `_extended_keys` never used anywhere else, IMO this can be written as
```c++
return p_code == VK_INSERT || p_code == VK_DELETE || ...;
```

Comment (akien-mga) [reply platform/windows/key_mapping_windows.cpp:419]: BTW, this line is `cond ? true : false`, the ternary operator is unnecessary, `cond` is already a boolean.

**Comment by ericrybick** [comment]
Thanks for reviewing!

I've changed the code according to your comments.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.
