### PR TITLE
Optimize AtlasTexture packing by minimal perimeter (fixes #19307)

### LINKED ISSUE #19307: Regression on altas texture packing at export - Godot 2 - commit bbf6694
**Godot version:**
2.1.4

**OS/device including version:**
Archlinux

**Issue description:**
There is a regression in packing texture on altas at export.
Packing seems to be less square as before.
It seems that commit bbf66945e7cebfbd3141e8ef3d4fe1e712b1f241 introduce this regression (https://github.com/godotengine/godot/pull/10604)

Here is packing before commit (atlas is 990x641) -> require 1024x1024 texture :
packing_before

Here is packing with commit (atlas is 230x3525) -> require 256x4096 texture (some device doesn't support 4096 texture):
packing_after

**Steps to reproduce:**
Se below for project to reproduce bug, just go in export and generate altas preview:
bad size is 4096x512 and expected size is 1024x2048

**Minimal reproduction project:**
[PackingExportBug.zip](https://github.com/godotengine/godot/files/2063429/PackingExportBug.zip)

### PR DESCRIPTION
**Pull request by DrMoriarty**
For atlas efficiency now used minimal perimeter instead of minimal area.
fix #19307

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks! Could you amend the commit (`git commit --amend` and then `git push --force`) to give it a more explicit description? The commit title should say what it does beyond the GitHub issue reference, e.g.
```
Optimize AtlasTexture packing by minimal perimeter

Fixes #19307.
```

File: editor/io_plugins/editor_atlas.cpp [hunk 1]
```diff
@@ -144,19 +145,25 @@ void EditorAtlas::fit(const Vector<Size2i> &p_rects, Vector<Point2i> &r_result,
...
+		float perimeter = (next_power_of_2(w) + h) * 2.f;
+		if (perimeter < min_perimeter) {
 			best = i;
-			max_eff = efficiency;
+			min_perimeter = perimeter;
 		}
 	}
 
+	if (best < 0) {
+		print_line("Atlas processing failed!");
```
Comment (akien-mga) [inline editor/io_plugins/editor_atlas.cpp]: You could use `ERR_PRINT` here instead.

File: editor/io_plugins/editor_atlas.cpp [hunk 2]
```diff
@@ -144,19 +145,25 @@ void EditorAtlas::fit(const Vector<Size2i> &p_rects, Vector<Point2i> &r_result,
...
-	float max_eff = 0;
+	float min_perimeter = FLT_MAX;
 
 	for (int i = 0; i < results.size(); i++) {
 
 		float h = results[i].max_h;
 		float w = results[i].max_w;
-		float efficiency = float(w * h) / float(next_power_of_2(w) * next_power_of_2(h));
-		if (efficiency > max_eff) {
+		//float efficiency = float(w * h) / float(next_power_of_2(w) * next_power_of_2(h));
```
Comment (akien-mga) [inline editor/io_plugins/editor_atlas.cpp]: Maybe drop this comment if no longer relevant.

**Comment by DrMoriarty** [comment]
@akien-mga done

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
