### PR TITLE
Focus current node after connecting

### LINKED ISSUE #21950: Deselecting a node while working with signals
**Godot version:**
3.1.dev-1

**OS/device including version:**
Arch Linux

**Issue description:**
Node gets deselected after any action related to signals. Connecting them, editing, etc.

**Steps to reproduce:**
1. Select a node,
2. Connect a signal,
3. Node is deselected now (at least window says so, even if it is still highlighted)
imgur-2018_09_10-20 48 38

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #21950

I changed ConnectionsDock constructor to take NodeDock instead of EditorNode, not sure why it was originally like that.

### CODE REVIEW

**Comment by YuriSizov** [comment]
This needs to be rebased, but also, shouldn't we bubble up the signal and connect to it in NodeDock instead of passing the reference and connecting it inside of another class? That doesn't look very idiomatic or even clear to read.

File: editor/node_dock.cpp [hunk 1]
```diff
@@ -70,6 +70,9 @@ void NodeDock::update_lists() {
 void NodeDock::set_node(Node *p_node) {
 	connections->set_node(p_node);
 	groups->set_current(p_node);
+	if (p_node) {
+		prev_node = p_node;
+	}
```
Comment (YuriSizov) [inline editor/node_dock.cpp:75]: So if I understand correctly, this can be better described as "last valid node" rather than "previous node", correct?

I suppose it works for the problem, but maybe we should at least rename the property (and the method)?

**Review by YuriSizov — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
