### PR TITLE
Fix OGG audio loop offset pop

### LINKED ISSUE #59348: OGG playback errors printed occasionally when stopping specific OGG file near the end in audio preview dialog
### Godot version

v4.0.beta8.official (45cac42c0), v4.0.beta.custom_build (62a508276)

### System information

Windows 11, Forward+, GeForce GTX 1660 (527.56)

### Issue description

When you ~stop~ pause an audio file near the end, Godot crashes.

<details>
  <summary>console output</summary>
  
  ```cmd
Godot Engine v4.0.beta8.official.45cac42c0 - https://godotengine.org
Vulkan API 1.3.224 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1660

ERROR: Condition "p_points.size() < 2" is true.
   at: canvas_item_add_multiline (servers/rendering/renderer_canvas_cull.cpp:1077)
WARNING: ran out of packets in stream
     at: _mix_frames_vorbis (modules/vorbis/audio_stream_ogg_vorbis.cpp:152)
ERROR: Condition "mixed < 0" is true. Returning: 0
   at: _mix_internal (modules/vorbis/audio_stream_ogg_vorbis.cpp:62)
ERROR: Index p_index = 13 is out of bounds (size() = 13).
   at: get (./core/templates/cowdata.h:155)
```
</details>

### Steps to reproduce

https://user-images.githubusercontent.com/10379487/159160668-88ab07c0-b986-47b9-b0fd-20d3b16712d1.mp4

### Minimal reproduction project

[StopSoudCrashTest_G4.zip](https://github.com/godotengine/godot/files/8311149/StopSoudCrashTest_G4.zip)

### LINKED ISSUE #75762: A warning is triggered by AudioStreamPlayer when using play(seek in position) in an ogg audio track
### Godot version

4.0.2 stable

### System information

Apple M2 Pro; Vulkan API 1.2.231 - Forward+

### Issue description

This warning will be triggered when using play(certain position) from an AudioStreamPlayer loaded with ogg file.
The warning was not always occurred, only some certain seeking positions will trigger it.

```
W 0:00:11:0687   audio.gd:47 @ changeBGM(): Burning negative samples doesn't make sense. Check seek algorithm.
  <C++ Source>   modules/vorbis/audio_stream_ogg_vorbis.cpp:332 @ seek()
  <Stack Trace>  audio.gd:47 @ changeBGM()
                 audio.gd:65 @ _on_button_3_pressed()
```

### Steps to reproduce

By pressing buttons for switching audios in the same position. Some positions will trigger the warning.
Toggle the CheckButton to true, and pressing the buttons will play the audio in a fixed position, which will trigger the warning every time for certain audios.

### Minimal reproduction project

[Archive.zip](https://github.com/godotengine/godot/files/11173023/Archive.zip)

### PR DESCRIPTION
**Pull request by ghost**
This fixes #75762, fixes #59348 and parts of #64775

Fixed the mixing function so it doesn't skip the last ogg packet of the file, and also made it so the burning algorithm only burns the needed samples from the last packet, and not the whole packet.

There are still some issues, if you download the example project from the issue, and you try the audio-pop-no-intro.ogg file, you'll see that there's still a pop, this is because for some reason, the engine is missing 38 samples, and not at the end of the file like the error originally was.

Another problem that became aparent is the decimal precision of the loop offset variable, in a song of mine which has a loop point at 31.46, the loop offset becomes 31.459991 or something like that, which introduces a tiny pop (this does not happen in Godot 3). If I manually change that value to 31.4600010, the pop disappears and the song plays like it does in Godot 3. So that's another problem somewhere else.

THIS DOES NOT FIX THE WAV POP.

However, it seems to have fixed the mp3 pop I was getting, so I guess it could have been a simple floating point precision error, but more testing is probably needed.

I'll keep looking into it.

If you know why the 38 samples from the 0 seconds offset loop could be going missing please let me know.

Thanks.

### CODE REVIEW

File: modules/ogg/ogg_packet_sequence.cpp [hunk 1]
```diff
@@ -159,7 +159,9 @@ bool OggPacketSequencePlayback::next_ogg_packet(ogg_packet **p_packet) const {
 
 	*p_packet = packet;
 
-	packet_cursor++;
+	if (!packet->e_o_s) { //STRELLY: Added this so it doesn't try to go to the next packet if it's the last packet of the file.
```
Comment (AThousandShips) [inline modules/ogg/ogg_packet_sequence.cpp:162]:
```suggestion
	if (!packet->e_o_s) {
		// Added this so it doesn't try to go to the next packet if it's the last packet of the file.
```
We don't sign comments like this, same elsewhere

**Review by AThousandShips — COMMENTED** [review]
Thank you for contributing, some style checks

**Comment by AThousandShips** [comment]
Please update your commit message to be more brief and descriptive, like the PR title, you can add the description in the body of the message

**Comment by strellydev** [comment]
Thanks, I fixed the comments, I was using them to find my changes and forgot to remove the name, also thanks for pointing out the commented return as well.

I will make this into a draft. Sorry for the inconvenience.

**Comment by AThousandShips** [comment]
> I will make this into a draft. Sorry for the inconvenience.

No problem!

**Comment by strellydev** [comment]
Oh no, I renamed the commits and somehow an older commit made it's way into this, uh... is there a way I can fix this?

**Comment by AThousandShips** [comment]
See [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

**Comment by strellydev** [comment]
All fixed, thank you again!

**Comment by strellydev** [comment]
Hello again, I fixed the issue with the offset being at 0, it didn't have to do with the offset being at 0 at all, I was just checking if the samples left in the last packet were greater than the needed samples by the mixer, instead of checking if they were greater than 0 like I should have been, I think this is ready for review.

File: modules/ogg/ogg_packet_sequence.cpp [hunk 2]
```diff
@@ -159,7 +159,9 @@ bool OggPacketSequencePlayback::next_ogg_packet(ogg_packet **p_packet) const {
 
 	*p_packet = packet;
 
-	packet_cursor++;
+	if (!packet->e_o_s) { //Added this so it doesn't try to go to the next packet if it's the last packet of the file.
```
Comment (AThousandShips) [inline modules/ogg/ogg_packet_sequence.cpp:162]:
```suggestion
	if (!packet->e_o_s) { // Added this so it doesn't try to go to the next packet if it's the last packet of the file.
```

File: modules/vorbis/audio_stream_ogg_vorbis.cpp [hunk 3]
```diff
@@ -186,6 +168,31 @@ int AudioStreamPlaybackOggVorbis::_mix_frames_vorbis(AudioFrame *p_buffer, int p
 		}
 	}
 	vorbis_synthesis_read(&dsp_state, frames);
+
+	if (!have_samples_left) { //Moved down so the check happens after we know if we have packets left or not.
```
Comment (AThousandShips) [inline modules/vorbis/audio_stream_ogg_vorbis.cpp:172]:
```suggestion
	if (!have_samples_left) { // Moved down so the check happens after we know if we have packets left or not.
```

**Comment by strellydev** [comment]
Alright, everything should be correctly styled now, and I also realized that loop_offset was a float even though the getter returns a double and the seek function receives a double as well, so I changed it to double and that also fixed the decimal point precision issue, which means ogg now fully functions the same as Godot 3 (Hopefully)

Thanks for taking the time to review this.

**Comment by AThousandShips** [comment]
Does it now completely fix the issue you referenced?

**Comment by strellydev** [comment]
It completely fixes the OGG part, however, the issue also talks about WAV and MP3 having pops as well. This pull request doesn't touch any of that.

**Comment by MJacred** [comment]
First of all: Thank you so much for tackling this!

I tested with couple of files (all loop offsets > 0 and at full seconds). And I sometimes still get pops…

I have 3 files that are exactly 92 secs. They work fine.  
Then I tested two files with 67.333 secs. The loop offset was exactly 6 secs for both. And only one popped.  
Thus, I cut that popping file in Audacity to a total length of 5.5 secs. While the loop offset changed, it was still at 1.5 secs. No audio pop.  
Therefore, I reckon there is still something wrong with the sample calculation. Especially because…

I got sometimes the warning
```
modules/vorbis/audio_stream_ogg_vorbis.cpp:340 - Burning negative samples doesn't make sense. Check seek algorithm.
```
when
* I double-click the file in the Godot Editor and it opens the importer dialog,
* I seek with the mouse manually
* **the file loops** <<< this happened every time for that file I cut in Audacity, but not for the others

And I had some file drop issues in the editor (`Failed to open [filename].ogg`, no further info). But that's something else

**Comment by strellydev** [comment]
The burning negative samples warning is something that has me weirded out as well.

I was sure that to calculate the samples to burn I could substract the previous page to the seeked one to the desired granule position, which would give us the amount of "granule" to burn in the current page. Then, we'd substract the previous granule position from the current page granule position, which would give us the granule size of the page, and then use that size to compare it to the burned samples.

Doing all of that actually gets rid of the warning, so it never tries to burn negative samples, however, it seems that calculating samples_to_burn that way is wrong, because it leads to popping.

And that doesn't make any sense to me. But doing the current calculation seems to work with the caveat of giving the warning when manually seeking through the file.

I could go in and try again with the desired granule - last granule formula. Maybe I did something wrong the first time I tried it.

This is my first time working with audio, so trying to navigate all the calculations is a bit tricky,

Thanks for testing this out, I will await your next comment!

**Comment by strellydev** [comment]
Is there ANY chance that the bug could come from the third party ogg vorbis code?

Because when we do vorbis_synthesis_restart(), the dsp_state->pcm_current is set to -1, which, later, when reading the first packet after the restart, it checks if pcm_current is -1, and if it is, it sets pcm_current to the same value as pcm_returned, which basically makes it act as if those first 1024 samples were already read.

block

If I do the change shown in the image in the file thirdparty/libvorbis/block.c, everything works fine. I didn't find anything breaking, but I don't know if changing that would have an effect on a specific scenario, or whatever. It's hard to tell.

**Comment by strellydev** [comment]
I'm going to sleep, but you can check the current commit to see a workaround for the vorbis pcm_out being 0 situation.

If we are against changing third party code, this is a solution that works.

@MJacred can you confirm that the pops you were having are gone with this new version of the code?

File: modules/vorbis/audio_stream_ogg_vorbis.cpp [hunk 4]
```diff
@@ -325,9 +332,34 @@ void AudioStreamPlaybackOggVorbis::seek(double p_time) {
...
+
+		Since modifying the third party code seems hacky, this work around was coded.
+
+		We basically calculate the samples_in_page from the previous page granule and the current page granule.
+		With that, we can then calculate if any samples were skipped due to the "bug".
+		Later, in the samples burn loop, if pcmout() returns 0, and there were samples skipped, we set samples_out to the skipped
+		samples, which makes the code burn the correct amount of samples, avoiding pops.
+	*/
+	int64_t previous_page_granule = 0;
+	PackedInt64Array granule_positions = vorbis_data->get_packet_granule_positions(); // We get all the granule positions
```
Comment (AThousandShips) [inline modules/vorbis/audio_stream_ogg_vorbis.cpp:350]:
```suggestion
	PackedInt64Array granule_positions = vorbis_data->get_packet_granule_positions(); // We get all the granule positions.
```

File: modules/vorbis/audio_stream_ogg_vorbis.cpp [hunk 5]
```diff
@@ -325,9 +332,34 @@ void AudioStreamPlaybackOggVorbis::seek(double p_time) {
...
+	for (size_t i = 1; i < granule_positions.size() - 1; i++) { // Starting at the second page, until the second to last one
```
Comment (AThousandShips) [inline modules/vorbis/audio_stream_ogg_vorbis.cpp:351]:
```suggestion
	for (size_t i = 1; i < granule_positions.size() - 1; i++) { // Starting at the second page, until the second to last one.
```

**Comment by MJacred** [comment]
@strellydev 

> This is my first time working with audio, so trying to navigate all the calculations is a bit tricky,

Hehe, same for me. I studied up from time to time, but was still quite a bit off from doing code fixing. So I'm really grateful to you and happy. Thanks : )


> Is there ANY chance that the bug could come from the third party ogg vorbis code?

Hm… maybe. But less likely (says my gut).

Pulling some stuff from my docs in the hope it helps…

Regarding the third party libs:  
According to this comment https://github.com/godotengine/godot/issues/64775#issuecomment-1427145947 we are using stb_vorbis (in Godot 4), although it was replaced with libvorbis (aka vorbisfile) + libogg (in Godot 4) -> https://github.com/godotengine/godot/pull/52406. That has me a bit confused. Maybe Godot 3 and 4 were mixed up or there is some detail gone missing. Either way, I could not find any files of stb_vorbis in master branch.

There are various reasons not to use stb_vorbis:
* https://github.com/search?q=repo%3Amackron%2Fminiaudio+stb_vorbis&type=issues
* https://github.com/nothings/stb/issues/1329#issuecomment-1133820101

Maybe these comments/docs helps with seeking/looping/mixing
* https://github.com/mackron/miniaudio/issues/152
* https://github.com/mackron/miniaudio/blob/master/examples/simple_looping.c
* https://github.com/mackron/miniaudio/blob/master/examples/simple_mixing.c
* https://github.com/mackron/miniaudio/blob/master/extras/miniaudio_libvorbis.h
* Because of the issues with Godot audio, someone used miniaudio (+ libvorbis) to do the mixing: https://github.com/EIRTeam/godot/tree/0.16/modules/shinobu (background info from maker: https://www.youtube.com/watch?v=oVp2ByYNg7U)

I'll now commence testing all the files and give feedback in the next comment (this time for sure &#8482;)

---


The referenced libs are up-to-date. If they have a bug, we can fix it here (need an account there first)
* libogg: https://gitlab.xiph.org/xiph/ogg
* libvorbis: https://gitlab.xiph.org/xiph/vorbis

or contact via
* mailing lists:
  * http://lists.xiph.org/mailman/listinfo/ogg-dev
  * http://lists.xiph.org/mailman/listinfo/vorbis
  * http://lists.xiph.org/mailman/listinfo/vorbis-dev
* or IRC on [irc.libera.chat](https://libera.chat/): channel #xiph for general information, or the general project channels: #vorbis

**Comment by MJacred** [comment]
First things first: I applied the `size_t` -> `int` fix locally.

Now to my testing:

Hm… guess I don't need to test all files (yet). So far, I could only fix one file with re-exporting from Audacity.

Thus far, I have now 2 files (more lying in wait) where the pop appeared and
* each has other files with the same sample count and the pop does not appear.
* The only difference I can spot so far is that their file size is different.
* And after cutting down the file to ~7 seconds, neither pop on their loop point… (no file is longer than 2 minutes)
* Both have again smooth loop offsets of 6 and 10 seconds respectively.

So if the sample count is not the issue. Then maybe the sample / buffer size?  
Some debug stats coming from Godot for audio files sure would be nice (so we can see how they understand the files…)

File: modules/vorbis/audio_stream_ogg_vorbis.cpp [hunk 6]
```diff
@@ -357,8 +395,13 @@ void AudioStreamPlaybackOggVorbis::seek(double p_time) {
 			ERR_FAIL_COND_MSG(err != 0, "Error during vorbis block processing " + itos(err));
 
 			int samples_out = vorbis_synthesis_pcmout(&dsp_state, nullptr);
+			if (samples_out == 0 && skipped_samples_in_page > 0) { // If we skipped samples and pcmout() returned 0.
+				dsp_state.pcm_returned = 0; // We reset pcm_returned to 0 to mark the packet as not read. (This is very hacky)
```
Comment (AThousandShips) [inline modules/vorbis/audio_stream_ogg_vorbis.cpp:399]:
```suggestion
				dsp_state.pcm_returned = 0; // We reset pcm_returned to 0 to mark the packet as not read. (This is very hacky).
```

**Comment by strellydev** [comment]
As expected, the check did nothing, and it's always treating the first packet as fully burned.

However, I implemented a hacky fix to the problem. If this doesn't fix the issue, I'll mark this as draft and go back to the drawing board, to check for buffer sizes maybe as you said.

File: modules/vorbis/audio_stream_ogg_vorbis.cpp (hunk 6 above)
Comment (strellydev) [reply modules/vorbis/audio_stream_ogg_vorbis.cpp:399]: So close...

**Comment by strellydev** [comment]
Sorry for being an airhead and missing the removal of the other dot and the lower case 't'.

**Comment by MJacred** [comment]
Sadly, the pop is still there

**Comment by MJacred** [comment]
Ok, I compared 2 files, using the cmd tool `mediainfo` and I got the following technical diffs

| name | popped? | File size (Bit) | Overall bit rate | 
| --- | --- | --- | --- |
| 1c | No | 3933996 | 425297 |
| 3a | Yes | 3817426 | 412695 |

> "Overall bit rate" = sum of all stream bit rates + container overhead

The rest is the same:
* duration: 74000 ms
* Bit rate: 499821 (500 kb/s)
* Bit rate mode: Variable
* Channels: 2
* Sampling rate: 44100 Hz
* Sample count: 3263400
* Bits per Sample: 32
* Stream size: 4623344 Bit

On the other hand,  
what VLC player read in its statistics after it finished playing the audio files (ran both several times and results were the same except in one case), though not sure if helpful:

**1c**
statistics_1c


**3a**
statistics_3a

after the first play, the input bit rate was different (checked it twice): 407 kb/s

**Comment by strellydev** [comment]
Thank you very much for taking the time to test this as well, I'll await your results, do you think you could share the file that pops for you? Maybe I can use it to figure something out.

**Comment by MJacred** [comment]
Here, I managed to keep the error intact: **loop offset is 6 seconds** flat
[2_02.ogg.tar.gz](https://github.com/godotengine/godot/files/12372564/2_02.ogg.tar.gz)

And this theory/speculation is invalid

> higher bit rates MAY cause trouble if loop point is not perfect enough

as I cut the file into a ~7 seconds version with same bit rate and the pop was gone.

Side note: Now I can guess why Audacity adds 200-300 KB by just re-exporting the ogg file as-is at quality level 10, most likely the same reason as for mp3: https://forum.audacityteam.org/t/i-need-to-know-why-my-exported-files-are-always-larger-than-the-original-even-if-i-dont-do-anything/65658

**Comment by strellydev** [comment]
Is this how the file is supposed to look like? (Just making sure)

image

**Comment by MJacred** [comment]
Yep, I cut out the non-important parts without changing the file length (which would eliminate the pop)

**Comment by strellydev** [comment]
Well, I can't seem to find anything conclusive, the loop point DOES coincide with the case where it's in the first 1024 samples of the page, which would be skipped by the first packet blockin call.

However, setting pcm_returned to 0 seems to do nothing, and I don't know if that's because it really isn't the issue, or if maybe the blockin function also messes with the internal sound tracking buffer (pcm/pcmret) which skips them and setting pcm_returned to 0 doesn't actually fix the issue.

Doesn't help that vorbis variable names include amazing things like... "w" or... "n" or... "n1", or that they create a pcm variable that points to pcm. It's all very confusing and not commentated, with a lack of proper documentation on their site as well.

I'll keep looking at this.
Cheers.

**Comment by MJacred** [comment]
Phew, I tackled the code myself (almost 10 hours) and did some performance improvements and simplifications. But I could not fix that pop…  
I could also do without `dsp_state.pcm_returned = 0;`, so that direction is probably a dead end…

**Comment by ellenhp** [comment]
Just wanted to say thank you to you folks for working on this. I saw a few emails move through my inbox about the vorbis code. As far as I know we're using the latest version of the reference implementation of vorbis, and it's a fairly mature piece of software so I would expect that we wouldn't need to change anything upstream. The only thing I can think of is to maybe look at how vorbisfile does things, since that's a fairly mature high-level interface to libogg and libvorbis.

**Comment by strellydev** [comment]
I'm pretty sure we'd still need the pcm_returned = 0 even if that's not the fix for this specific pop, because we still need to read the buffer from the right position, not from the end of the packet. But we can check that after fixing this pop, since this file is the perfect testing file giving that the loop point meets the requirement. But yeah, I agree the issue has to be somewhere else, I have triple checked that the mixed samples are correct, the sample we jump to is the correct one, I also checked there wasn't anything funny going on with the volume, in case it was just peaking, I checked the mixing steps for the buses, etc. And nothing. Checked if the buffer sizes were being miscalculated somewhere and couldn't find anything either.

I then followed Ellen's advice and tried to check how vorbisfile does it, but the vorbisfile code is another labyrinth. I'll say it's at least commentated, so you can kinda go along, but for example, there are seeking functions that only exist to call another seeking funciton, which then calls a misterious "seekinternal" function of which I can't find the definition off. And I don't know, I couldn't really tell where they were actually seeking, or where they were burning, etc. Maybe I'll look at it again another time.

I really don't know where this specific pop is coming from, this just may be outside of my league.

I guess we could test by creating another file that has it's loop point be in the first 1024 samples of a page and see if that one pops, so we can at least discard that, but I also don't know how I would go about creating a file like that except by random chance x_x...

**Comment by ellenhp** [comment]
Please don't say that it's outside of your league! This issue has languished for a long time because there aren't many people who wanted to tackle it. Not because it's not important, but because audio code is hard and painful to work with. The libogg/libvorbis/vorbisfile developers didn't document their code well. It's complicated stuff, none of it is self-explanatory, and often things aren't explained in comments because we're all human and sometimes comments aren't the top priority for people. But it does mean that making sense of it is more a reverse-engineering task than anything else.

I'm refreshing my memory on this stuff and reading through the comments, maybe I'll be able to make some progress.

**Comment by MJacred** [comment]
@ellenhp: we cannot use vorbisfile directly because of the "don't do allocations in audio" or so, right?

---

@strellydev: here's my code

my current assumption is that the 0 read is because we have a dead/empty packet. Though I'm not really convinced of that, as in my various alterations of the code I managed to get a non-zero read in the first for-loop. Well, my current solution only needs one for-loop.

I'll see what I can do about more files. Finding weird edge cases in life is my strongest passive skill.

```c++
// ogg_packet_sequence.h
	int get_current_page_size();
	int64_t get_current_page_granule();


// and this goes to ogg_packet_sequence.cpp:
int OggPacketSequencePlayback::get_current_page_size() {
	int64_t prev = 0;
	int64_t curr = ogg_packet_sequence->page_granule_positions[page_cursor];

	if (page_cursor > 0) {
		prev = ogg_packet_sequence->page_granule_positions[page_cursor - 1];
	}

	return curr - prev;
}

int64_t OggPacketSequencePlayback::get_current_page_granule() {
	return ogg_packet_sequence->page_granule_positions[page_cursor];
}
```

```c++
void AudioStreamPlaybackOggVorbis::seek(double p_time) {
	ERR_FAIL_COND(!ready);
	ERR_FAIL_COND(vorbis_stream.is_null());
	if (!active) {
		return;
	}

	vorbis_synthesis_restart(&dsp_state);

	if (p_time >= vorbis_stream->get_length()) {
		p_time = 0;
	}

	const int64_t desired_sample = p_time * get_stream_sampling_rate();
	frames_mixed = uint32_t(desired_sample);

	if (!vorbis_data_playback->seek_page(desired_sample)) {
		WARN_PRINT("seek failed");
		return;
	}

	ogg_packet *packet;
	// WARN_PRINT("Seek " + itos(desired_sample));
	if (!vorbis_data_playback->next_ogg_packet(&packet)) {
		WARN_PRINT_ONCE("seeking beyond limits");
		return;
	}

	// The granule position of the page we're seeking through.
	int64_t granule_pos = vorbis_data_playback->get_current_page_granule();
	int samples_in_page = vorbis_data_playback->get_current_page_size();

	// WARN_PRINT("granule (" + itos(granule_pos) + ") vs page sample count (" + itos(samples_in_page) + ")");

	int64_t samples_to_burn = samples_in_page - (granule_pos - desired_sample);

	if (samples_to_burn > samples_in_page) { // We now do the check against the true size of the page.
		WARN_PRINT("Burning more samples than we have in this page. Check seek algorithm.");
	} else if (samples_to_burn < 0) {
		WARN_PRINT("Burning negative samples doesn't make sense. Check seek algorithm.");
	}

	// WARN_PRINT("burn " + itos(samples_to_burn) + " samples");

	int headers_remaining = 0;
	int err;
	// Burn through the samples so that the seeking position is reached.
	while (true) {
		if (vorbis_synthesis_idheader(packet)) {
			headers_remaining = 3; // Skip 3 headers spanning multiple packets/pages.
		}
		if (!headers_remaining) {
			err = vorbis_synthesis(&block, packet);
			ERR_FAIL_COND_MSG(err != 0, "Error during vorbis synthesis " + itos(err));

			err = vorbis_synthesis_blockin(&dsp_state, &block);
			ERR_FAIL_COND_MSG(err != 0, "Error during vorbis block processing " + itos(err));

			int samples_out = vorbis_synthesis_pcmout(&dsp_state, nullptr);
			if (samples_out == 0 && samples_to_burn > 0) {
				continue; // We reached the end of the packet, please continue in next packet.
				// dsp_state.pcm_returned = 0;
				// samples_out = vorbis_synthesis_pcmout(&dsp_state, nullptr);
			}
			// WARN_PRINT("pcmout burn " + itos(samples_out));
			int read_samples = samples_to_burn > samples_out ? samples_out : samples_to_burn;
			err = vorbis_synthesis_read(&dsp_state, read_samples); // Changed to read_samples so we don't burn the whole packet.
			ERR_FAIL_COND_MSG(err != 0, "Error during vorbis read updating " + itos(err));
			samples_to_burn -= read_samples;

			if (samples_to_burn <= 0) {
				break;
			}
		} else {
			headers_remaining--;
		}
		if (packet->granulepos != -1 && headers_remaining == 0) {
			// WARN_PRINT("page end");
			// This indicates the end of the page.
			break;
		}
		if (packet->e_o_s) {
			// WARN_PRINT("e_o_s");
			break;
		}
		// WARN_PRINT("next_ogg_packet");
		if (!vorbis_data_playback->next_ogg_packet(&packet)) {
			// We should get an e_o_s flag before this happens.
			WARN_PRINT("Vorbis file ended without warning.");
			break;
		}
	}

	// WARN_PRINT("samples burn leftover " + itos(samples_to_burn));
}
```

And I have some more `float` to `double` changes, namely in
* audio_stream_mp3.h
* resource_importer_mp3.cpp
* resource_importer_ogg_vorbis.cpp

**Comment by strellydev** [comment]
@ellenhp thanks for the encouragement. I didn't mean that as a "I'm going to stop trying to fix this", I love learning new things and solving problems, so I'll probably stick around until this is actually fixed.

---
@MJacred your version of the code is much cleaner and it gets the same results, but without the pcm_returned = 0, audio-pop.ogg and my own song still pop, after uncommenting them, the pop is fixed in all of the files (except the mistery pop that comes from nowhere).

Does your code not pop for you in the audio-pop.ogg file?
---
I'm gonna check if maybe the ogg importer is messing something up with the file next.

**Comment by MJacred** [comment]
> your version of the code is much cleaner and it gets the same results

Why thank you : ) After looking at the code for a couple hours the first while-clause started looking annoying to me x)

> Does your code not pop for you in the audio-pop.ogg file?

Um, I tested with 2_02.ogg and that had still a pop, but another file where your changes fixed a pop was still fine. But I'll recheck that and with audio-pop.ogg tomorrow. Err, I mean later (it's one o'clock in the morning here)…

Is audio-pop.ogg from my original issue's description or which do you mean?

---

Even Doom 3 uses vorbisfile!! \*yell\*  
Phew, that needed to be said.

And throwing this at the wall, we're not alone with vorbis looping: http://nothings.org/stb_vorbis/ogg_seek.txt

**Comment by strellydev** [comment]
Yes, it's from the original issue.
You should rest then, as should I, it's 00:00 for me, so I hope you have a good night.

**Comment by ellenhp** [comment]
I have something that might fix the pop? I based it on this PR so I made a PR into @strellydev's feature branch but the changes could be incorporated piecemeal based on what issues testing reveals. https://github.com/strellydev/godot/pull/1

If you two could test it that would be great. I'm hopeful that we may have finally fixed this? I don't want to celebrate yet but I am hopeful. The ogg seek code has been a source of background anxiety for me for ages. :laughing:

**Comment by MJacred** [comment]
> it's going back to the beginning which ends up reloading the same block into the state

@strellydev: Indeed. Good catch!

---


@ellenhp: I tested with 3 files that were popping before and now they don't! I could cry (from relief). I'll test all files later. For now: breakfast time.

**Comment by MJacred** [comment]
Hm… ok, I tested some more files and I get the `audio_stream_ogg_vorbis.cpp:349 - Burning negative samples doesn't make sense. Check seek algorithm.` warning from @ellenhp's PR. Sometimes. When opening the importer dialog. When seeking inbetween. When looping. It's irregular. But even if the warning does not trigger, there are, at times, audio pops.

So, some pops that are in this PR are gone in the other PR and vice versa…

So in this archive, there are 2 files
1. sMission_S01a.ogg (loop offset 10.0)
2. sMission_S01a_2.ogg (loop offset 1.0)

File 1. is my original file with some parts silenced. The original file works in with this PR, but not with the other PR. After silencing parts, it's pops in both.  
File 2. is file 1. but with the silent parts cut. Now it pops in neither PR.

[sMission.tar.gz](https://github.com/godotengine/godot/files/12385438/sMission.tar.gz)

As the loop samples themselves are fine, it seems we are still not sample-accurate. Afaik if you re-save ogg file, it degrades. Therefore I also reckon the packages/pages changed, which might fix the pop if you're lucky. Therefore, I feel @ellenhp's additions go into the right direction. I believe we need to read the `page headers` and check if we should move up or down a bit or not at all.

**Comment by strellydev** [comment]
Hi! Thank you so much!

I tested your code and the mistery pop is gone from my end too.
I also merged both of your changes and I think the "samples_in_page += dsp_state.centerW;" may not be needed. With both changes merged together there is still no pop, I will commit it so you both can test as well just in case.

Before I do that though, is there a way I can include you both as co-authors of the commit? I'd love it if I could include you two in the pr commit so it's properly credited as well.

**Comment by MJacred** [comment]
Here's the syntax for your commit message: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

Afaik you can auto-get Ellen's if you merge her PR (or use her GitHub-provided no-reply email) or after the squash afterwards. My mail address is loesch[dot]benny92[at]gmx.de (I'll remove mine after you got it to ward off some crawlers).

---

Did you test with the first sMission file? If there was no pop, I'll gladly re-test it on my machine once you pushed your newest commit

**Comment by strellydev** [comment]
I got the email, you can delete it now, thanks!

**Comment by strellydev** [comment]
GOOD NEWS! With both of your changes merged, sMission files do not pop for me, I will make a commit and let you test!

**Comment by strellydev** [comment]
Hey it worked, how cute, however, the emails show in the commit message, I wonder if I can fix that.

**Comment by MJacred** [comment]
That cannot be avoided. That's why alternatively you can use the `GitHub-provided no-reply email` addresses mentioned in the previous link.

**Comment by strellydev** [comment]
Alright, I squashed the commit so the PR only has one.

Thank you both again for your help, let's hope this is the final commit! And if anyone wants so change their email to the no-replay one just let me know!

I'll await your testing and if everything is cool I'll open this for review again.

**Comment by MJacred** [comment]
Indeed… now it's gone. Weird.

Anyway, I tested a couple dozen files with speaker and headset and there are very few pops left. Here's one example:

[cooking_S00.tar.gz](https://github.com/godotengine/godot/files/12385918/cooking_S00.tar.gz) loops at 9 seconds (and I checked 2 in Audacity for looping, just to be sure).


---

Will you also update the float -> double changes I mentioned before (can't harm as they should be double anyway):

```
And I have some more float to double changes for variables named length and loop_offset, namely in
    audio_stream_mp3.h
    resource_importer_mp3.cpp
    resource_importer_ogg_vorbis.cpp
```

**Comment by strellydev** [comment]
I could update them but I don't know if that goes against the rule of keeping one pull request to one problem alone, and then have the mp3 doubles fixed whenever the mp3 pops are tackled. I guess I'll update them and change them back if they tell us it shouldn't be there. 

I'll check that file after eating lunch!

**Comment by strellydev** [comment]
One curious thing about that new file that pops.

image

Whenever I set a breakpoint in that line in the file "audio_stream_ogg_vorbis.cpp", if I open an ogg file in the editor with the loop offset set and enabled, whenever the editor is building the wave preview thing, it triggers the breakpoint, since to build the wave form preview it has to traverse the file.

However, with the cooking file, this breakpoint is not being triggered, even though later, when playing the file, it does trigger it to loop. So I guess that could be our first clue that shows that something funny is going on with that file specifically.

**Comment by MJacred** [comment]
Yeah, I learned that Godot reads the file when I wanted to add the waveform in my adaptive music addon back in 3.2. I wondered how and what they got data for it x)

Although I thought Godot was calling seek for preview from somewhere else...

I can get another popping file later tonight



Am 19. August 2023 14:17:24 UTC schrieb Strelly ***@***.***>:

**Comment by strellydev** [comment]
Aha!

image

In this function, the frames_total variables is equal to the amount of samples in the file for every other file, but for the cooking file, it's (somehow) 315900 samples more.

**Comment by ellenhp** [comment]
> However, with the cooking file, this breakpoint is not being triggered, even though later, when playing the file, it does trigger it to loop. So I guess that could be our first clue that shows that something funny is going on with that file specifically.

If you're on linux and your distro has `oggz` available in the package repos, you can try to use that to get information about the structure of the ogg file. It's not terribly easy to use but it can still help a lot because it's hard to get visibility into the files any other way.

**Comment by strellydev** [comment]
Well, we still have the lead on the file not triggering the breakpoint when building the wave form preview.

But apart from that, the only other thing I can think of is the following:

As we know, an ogg page can sadly start with a packet that actually begins from the last page, so the granule_position of a page doesn't necesarily mean that it starts on a packet, I don't know if Godot fixes this when importing it, and sets the granule position to be the end of the last packet of the page, I'm assuming it does, so this may lead to nothing, but if it doesn't, we may be running into the problem of wanting to go to a sample that's in a page, but the packet begins in the previous one?

I'm not sure if this is how it works or if that can actually happen, but from reading the rantings from the link provided by MJacred, it occured to me that that may be an issue.

As far as I know we don't have access the page header info in the seek_page function, so I can't seem to check if that's the case.

In any case, I'll leave this out here in case one of you know if this could happen.

**Comment by strellydev** [comment]
The file is not triggering the breakpoint on preview because it's skipping the last 4 samples of the files.

This skip doesn't seem to happen on the playback of the file, so this shouldn't be the issue, however, the pop is so small that I'd believe 4 samples did it if I hadn't triple checked that on playback it's actually mixing the whole file.

**Comment by MJacred** [comment]
@ellenhp / @strellydev: From now on, I'll add example files at the bottom of #64775's issue description (already added the `cooking` file) so that they don't get lost in the conversation.

I'll now prepare some files that may help with narrowing the problem space down and attach them in that issue description

---

side note: having the incorrect mixing rate reminds me of another issue where people were using an audio interface #75109

**Comment by ellenhp** [comment]
> The file is not triggering the breakpoint on preview because it's skipping the last 4 samples of the file.

4 samples is the latency caused by the resampling algorithm in AudioStreamResampled. Could you try changing the project settings mix rate from 44100 to 48000 (or reverse) to see if the resampling is causing this?

**Comment by strellydev** [comment]
> 4 samples is the latency caused by the resampling algorithm in AudioStreamResampled. Could you try changing the project settings mix rate from 44100 to 48000 (or reverse) to see if the resampling is causing this?

Changing the sample rate of the project doesn't change the behavior, however, I find it interesting that the sample rate was at 44100, but the sample rate returned by the driver in the preview was 48000.

**Comment by xMakerx** [comment]
Not too sure if this is allowed here, but I'll share it. Here is how another engine implements OGG files. It might be helpful to check this [#read_samples()](https://github.com/panda3d/panda3d/blob/160ba090a5e80068f61f34fc3d6f49dbb6ad52c5/panda/src/movies/vorbisAudioCursor.cxx#L145) method out as it includes some interesting behavior: it notes that the buffer must be N samples * number of channels, and the code adds silence to the buffer if necessary.

**Comment by MJacred** [comment]
@xMakerx: thanks, I'll add it to my reading list.

@strellydev: if this PR is merged, it would definitely fix https://github.com/godotengine/godot/issues/75762 (could you add this to the description, please?)

**Comment by strellydev** [comment]
For sure, it's been added, I've also commited everything I had left to commit, that being some changed comments to better represent the new code, and the mp3 changes, which, by the way, seem to have fixed the mp3 pop that was happening to me. So it seems that the mp3 part was just a floating point precision problem.

**Comment by MJacred** [comment]
#59348 will also be fixed (edited my previous comment but I guess we just missed each other!)

And you did not yet react to my review (found some obsolete code).

**Comment by strellydev** [comment]
Wait, review? where? I don't see anything in my notifs x_x

**Comment by MJacred** [comment]
Here on github just above this comment https://github.com/godotengine/godot/pull/80452#issuecomment-1690001135

You can also see all pending code reviews on Github's `Files changed` tab at the top of this page

**Comment by strellydev** [comment]
I'm unable to see any reviews from you, I only see the ones AThousandShips left.

**Comment by MJacred** [comment]
Ok, that's a first…

Here's a reproduction:

```
lines 317-327 can be deleted. Already called in line 274 and 289-298. This is leftover code from the time when there were 2 while-loops
```

**Comment by strellydev** [comment]
You are completely right, it is redundant code. It's been deleted, I'll push it in a couple of days to give a bit more time to see if a miracle happens and the solution for the remaining pops is found.

**Comment by MJacred** [comment]
What I find interesting: Before this PR, `frames_mixed` and `desired_sample` were equal. Now they are not. If you set them equal once more (including the centerW offset into frames_mixed), it generates more audio pops. @ellenhp, did you know that would happen so you didn't do that in your PR?

Either way, as they are equal _at some point_ (here we ignore centerW), we can save a function call and make their relation clearer with this proposed alternative in line 283:
```cxx
	// The overlapping nature of vorbis packets requires that we go back half a packet before the place we want to seek to.
	int64_t desired_sample = p_time * vorbis_data->get_sampling_rate();
	frames_mixed = uint32_t(desired_sample);
	desired_sample -= dsp_state.centerW;
	if (desired_sample < 0) {
		desired_sample = 0;
	}
```

Apart from that, while subtracting `centerW` seems to help, this is probably not the right way (according to the [docs](https://xiph.org/vorbis/doc/libvorbis/vorbis_dsp_state.html)): `they should not be directly modified or relied upon in any way`. 

I'll try contacting the vorbis maintainers tomorrow, maybe they can shed some light on our problem.

**Comment by strellydev** [comment]
Yeah, that happens because you set the desired_sample to be a packet before, that way, after the restart, the first packet called in block_in is set to read, leaving you at the same place as the frames mixed.

This is basically the same as setting the pcm_returned to 0 we were doing before, however, I assume that doing it this way, lets vorbis mix the half a packet it must mix before the actually desired one, hence the fixed pop of that other audio file.

So that is intended.

The docs say that, but they also don't provide another way to fix that and they don't even document the fact that the first packet after restart is "skipped" or at least used to mix the half a packet of the next packet. So I don't know how trust worthy it is.

**Comment by MJacred** [comment]
I'm still reading docs, but so far I've found some things we currently ignore
* in the importer, we're not accounting for the case where one ogg page may have a granule position of `-1`, because the packet spans more than 2 pages (is rare, but can happen) -> in this case we push a page with granule_pos == `0` (resource_importer_ogg_vorbis.cp:L229)
* we read ALL the samples given by vorbis, even though the ogg file creator (the encoder specifically) may spam additional samples at the end of the file (this is padding to ensure the file has an integral number of packets)
  * see [here](https://github.com/xiph/vorbis/blob/master/doc/vorbis-clip.txt#L55)
  * **solution**: we can find out by reading the very last page of the stream and check it's granular position. If it's a `short`, then we got some data added -> i.e. if the file should loop, we need to discard those samples. (that granular position should also imply a smaller value than the granular position before, I reckon)
  * this sounds like it would be good to have an `end_loop` (in sample count, not time) position for loopable files, so that we auto-skip on the correct sample

**Comment by ellenhp** [comment]
I think I may not have given much thought at all to the overlapping nature of vorbis packets when I designed the ogg system originally, so it occurred to me today that it's possible I misunderstood the meaning of the granule position of a page. Do we know if it refers to the last (in time) sample in the stream that's possible to extract with `pcmout`? If so I there may be some more half-packet offsets we need to add. It' possible I assumed it would be the last sample we have any information about, which in general would be half a packet after the last sample that we could extract with pcmout.

**Comment by MJacred** [comment]
granule can be
* `-1`, meaning: this packets ends in another castle/page
* nonsense: an integral number of packets are necessary, so the very last packet of the stream may have extra 0 value samples which need to be discarded during decoding
  * the last granule in the last page is the original length of the file discarding extra samples!
* `> 0`: granular position, the final decoded pcm sample number of the last packet FINISHED in this page
  * So the true last sample of the page is unknown. Unless the next page header tells us we neatly wrapped up the packet with the page.

while a packet will most likely be cut by the page end, its segments cannot be split cross pages.  
a header flag of 0x01 tells us if the packet is actually split by the page.

By the way: we can actually read the granule from the page header (we don't need to count it ourselves):
`int64_t granule_pos = (int64_t)ogg_page_granulepos(&page);`

In the hope that helps

**Comment by MJacred** [comment]
Wait… `ogg_page_granulepos` should give us the granular of the page irrelevant of the packet size. But currently, we only read the granular position from the packet (which is not necessarily the page granular…).

Therefore, `OggPacketSequencePlayback::get_current_page_size()` is should be incorrect. Therefore `samples_to_burn` should be incorrect.

Hm… I'm not 100% certain about `ogg_page_granulepos`. I'm pretty sure I compared them 2 weeks ago and the granular position values were equal to the packet granular positions, but I can recheck over the weekend.

Either way, if we seek using packet granular positions we would definitely not land in the wrong page (which could happen currently).

**Comment by MJacred** [comment]
Hm… I hoped the true last granule position of a page may be read when we run `ogg_stream_packetout` and it returns `0`. Then inspect the packet and read the packet's `granulepos`. Though it fully equals `ogg_page_granulepos`, which fully equals the last finished packet of the page.

Maybe we need to work on packet byte level to get the size of a page? I think I remember vorbisfile considering more data while seeking, including channel size (not sure if also bit depth, but they should if they use byte-level for seeking). I guess back to reading vorbis code when I find time again…

**Comment by strellydev** [comment]
I've been reading as well and trying to check if maybe we should be skipping samples when decoding the pages, but I don't know if I've been doing it right.

> The encoder indicates to the decoder that the file is actually shorter
than all of the samples ('original' + 'extra') by setting the granule
position in the last page to a short value, that is, the last
timestamp is the original length of the file discarding extra samples.
The decoder will see that the number of samples it has decoded in the
last page is too many; it is 'original' + 'extra', where the
granulepos says that through the last packet we only have 'original'
number of samples.  The decoder then ignores the 'extra' samples.
This behavior is to occur only when the end-of-stream bit is set in
the page (indicating last page of the logical stream).

I don't understand what they mean with the granule position of the last page being a short value.

I assumed it meant that if the granule position of the last page was less than the granule position of the last packet, it would mean the last packet was just padding and could be skipped, but that didn't make much sense, so then I thought it could mean that the number of bytes in the last packet could be grater than the last page granule position - the second to last page granule position, meaning there are more bytes than there should be, but it doesn't seem to be the case, or maybe I'm doing something wrong, or maybe that's not the problem with the file.

I've also been trying to mess with the desired granule again to see if I missed anything last time I checked, but to no avail.

I changed the importer code to save the page granule position as the one returned by the function ogg_page_granulepos(), this didn't fix anything, nor broke anything, at least with the current files I have to test with.

The seek_page_internal function does have a comment saying "This function needs better corner case handling." but it doesn't elavorate so I'm not sure which corners it refers to.

And that's all I've been able to do.

I don't feel any closer to a solution.

**Comment by bs-mwoerner** [comment]
I hope you don't mind me chiming in. I've had this loop pop problem in my own project and came across this issue. I've spent some time reading through this, the code, and the documentation and I think there are three main issues:
- The original code went to great lengths to find the correct sample but ended up skipping the whole packet (and thus possibly a few hundred samples too much) anyway. This is fixed in the current pull request and eliminates the vast majority of pops.
- The `seek` method does not correctly update the `have_samples_left` and `have_packets_left` flags, which may lead to some weird behavior later in `_mix_frames_vorbis`. I think this has been worked around in the current pull request by making changes to `_mix_frames_vorbis`.
- The `seek` method can't access samples in packets that span page boundaries because it will start reading at the beginning of the page that the packet _ends_ on and thus in the middle of the packet.

That last point is a bit tricky to reproduce, but luckily the _cooking_S00.ogg_ file linked above demonstrates one such case: The loop point at 9 seconds is near the start of page 14 in a packet that started on page 13. `seek` jumps to page 14 and starts feeding the decoder with data from the start of the page. The decoder drops the first packet as incomplete and returns samples starting from the second packet onwards. Having skipped past the desired seek point, `seek` ends up printing the _Burning negative samples doesn't make sense._ message when it notices that the target sample is not in the range it checked.

I suppose a seek algorithm that can deal with partial packets would have to look something like this:
- As before, use a binary search to find a page to start the search on.
- Move back one page and start decoding from there.
- Since at this point we don't know exactly where in the stream we are, just continue decoding blindly until we come across a granule position. This should happen at the end of each page.
- If this granule position is already past the desired sample, we need to go back further, reset the decoder, and start decoding again. Technically, this shouldn't happen with Vorbis streams as samples are much smaller than pages, so we should always be able to arrive at the desired sample in a valid decoder state by starting just one page early (may not be true for the very first pages, though).
- If the granule position is before the desired sample, continue decoding, counting samples and updating the current position until we reach the desired seek position. Then leave the decoder in that state and return to the caller who can start reading samples from the correct position.

I've never contributed anything to Godot so I'm not sure if there's a better way to contribute code to this pull request, but here's an updated `seek` method that for me does not produce pops when looping _cooking_S00.ogg_ or my other test files:

```c++
void AudioStreamPlaybackOggVorbis::seek(double p_time) {
	ERR_FAIL_COND(!ready);
	ERR_FAIL_COND(vorbis_stream.is_null());
	if (!active) {
		return;
	}

	if (p_time >= vorbis_stream->get_length()) {
		p_time = 0;
	}
	frames_mixed = uint32_t(vorbis_data->get_sampling_rate() * p_time);

	const int64_t desired_sample = p_time * get_stream_sampling_rate();

	if (!vorbis_data_playback->seek_page(desired_sample)) {
		WARN_PRINT("seek failed");
		return;
	}

	// We want to start reading before the page that contains the sample (the sample may be part of a
	// partial packet overlapping pages). Otherwise, the decoder may not have synchronized before
	// reaching the sample.
	int64_t start_page_number = vorbis_data_playback->get_page_number() - 1;
	if (start_page_number < 0) {
		start_page_number = 0;
	}

	while (true) {
		ogg_packet* packet;
		int err;

		// We start at an unknown granule position.
		int64_t granule_pos = -1;

		// Decode data until we get to the desired sample or notice that we have read past it.
		vorbis_data_playback->set_page_number(start_page_number);
		vorbis_synthesis_restart(&dsp_state);

		while (true) {
			if (!vorbis_data_playback->next_ogg_packet(&packet)) {
				WARN_PRINT_ONCE("seeking beyond limits");
				return;
			}

			err = vorbis_synthesis(&block, packet);
			if (err != OV_ENOTAUDIO) {
				ERR_FAIL_COND_MSG(err != 0, "Error during vorbis synthesis " + itos(err));

				err = vorbis_synthesis_blockin(&dsp_state, &block);
				ERR_FAIL_COND_MSG(err != 0, "Error during vorbis block processing " + itos(err));

				int samples_out = vorbis_synthesis_pcmout(&dsp_state, nullptr);

				if (granule_pos < 0) {
					// We don't know where we are yet, so just keep on decoding.
					err = vorbis_synthesis_read(&dsp_state, samples_out);
					ERR_FAIL_COND_MSG(err != 0, "Error during vorbis read updating " + itos(err));
				} else if (granule_pos + samples_out >= desired_sample) {
					// Our sample is in this block. Skip the beginning of the block up to the sample, then
					// return.
					int skip_samples = (int)(desired_sample - granule_pos);
					err = vorbis_synthesis_read(&dsp_state, skip_samples);
					ERR_FAIL_COND_MSG(err != 0, "Error during vorbis read updating " + itos(err));
					have_samples_left = skip_samples < samples_out;
					have_packets_left = !packet->e_o_s;
					return;
				} else {
					// Our sample is not in this block. Skip it.
					err = vorbis_synthesis_read(&dsp_state, samples_out);
					ERR_FAIL_COND_MSG(err != 0, "Error during vorbis read updating " + itos(err));
					granule_pos += samples_out;
				}
			}
			if (packet->granulepos != -1) {
				// We found an update to our granule position.
				granule_pos = packet->granulepos;
				if (granule_pos > desired_sample) {
					// We've read past our sample. We need to start on an earlier page.
					if (start_page_number == 0) {
						// We didn't find the sample even reading from the beginning.
						return;
					}
					start_page_number--;
					break;
				}
			}
			if (packet->e_o_s) {
				// We've reached the end of the stream and didn't find our sample.
				have_samples_left = false;
				have_packets_left = false;
				return;
			}
		}
	}
}
``` 

This requires access to the current page number in `OggPacketSequencePlayback`:

```c++
int64_t OggPacketSequencePlayback::get_page_number() const {
	return page_cursor;
}

bool OggPacketSequencePlayback::set_page_number(int64_t page_number) {
	if (page_number >= 0 && page_number < ogg_packet_sequence->page_data.size()) {
		page_cursor = page_number;
		packet_cursor = 0;
		packetno = 0;
		return true;
	}
	return false;
}
```

**Comment by ellenhp** [comment]
This is amazing work @bs-mwoerner. I think your reasoning makes sense. There are several ways to miss samples and I think the original code in #52406 hits approximately all of them. At least I got the binary search right, I think. :laughing: 

Earlier in this comment thread I mentioned making a pull-request into @strellydev's feature branch, and then they squashed commits with me as a co-author. I think that the same sort of thing makes sense here if you're comfortable with that workflow. I can provide more detailed steps on how to do that if need be. Git is tricky to work with sometimes. I'm going to try to test this. It would be incredible to finally leave this unfortunate chapter of 4.x audio issues in the past.

**Comment by strellydev** [comment]
> I hope you don't mind me chiming in.
Thanks a lot for chiming in.

I'll test this once I get home from work, in about 8 hours or so and if it works and no one else seems to find any issue, I'll just add it and update the pull request.
If you want, you can do a PR to my branch and then I'll squash the changes as Ellen pointed out, or you can just leave your no-reply github email, or your normal email if you prefer so I can add you to the commit, and I'll manually add the changes.

Again, thanks a lot.

**Comment by MJacred** [comment]
Thank you so much for chiming in, @bs-mwoerner. I'll gladly test your adjustments once it's in this PR with all the audio files I've got.

**Comment by bs-mwoerner** [comment]
@ellenhp Thanks! 😃 That original code certainly does many more things right than it does wrong. 😄 In fact, I wouldn't even change anything in `_mix_frames_vorbis`. From what I know now, it feels correct that it starts by checking whether it needs to go to the next packet and relies on `seek` to have set the corresponding flags correctly.

@strellydev Yes, I'll be at work for the next hours as well but I've now forked your fork and created a pull request back into your repository. I hope this is how this works. 😅 Note that I've also reverted your changes to `_mix_frames_vorbis`. Please check if that makes sense to you in combination with the new `seek`. Also, I tested this right on the Godot master branch and still need to check if it still works when combined with your other (importer) changes.

@MJacred Actually, I just noticed that your last comment _Alternatively: always go one page earlier, get page granulepos, skip all completed packets on that page (then we're at page_granulepos) and then burn samples (seek_pos - page_granulepos)_ is exactly what I ended up doing. The main reason for having to go back is that the decoder can't start decoding at arbitrary positions in the stream and may need some time before it can produce actual samples. If you start decoding too close to where you want to go, there is a chance that you've read past the desired sample before the decoder catches on. The safe way, therefore, is to start decoding one page early. Upon reaching the end of that page, the decoder will be properly initialized _and_ you get the current granule position to tell you exactly where in the stream you are. From that point onwards, it's just counting samples until you get to the correct position.

**Comment by strellydev** [comment]
Sigh, I made the merge and everything went right, but then github told me there was a conflict, I fixed it and github generated an automatic commit merging it and now I can't seem to rebase the merge commit so only the original one shows up, does anyone know how to fix this? I've been trying to revert and some other things but can't seem to get it right.

Apart from that, all my tests went great, all the pops are gone from my end.

**Comment by AThousandShips** [comment]
Use `git push --force` instead of allowing it to merge after you've rebased

**Comment by strellydev** [comment]
Alright, I think I managed to revert it back to before the automatic github merge, the conflict is there again, but not in my local files, so I don't know what's up with that, I'll leave it up to the reviewers.

In any case, no pops!! I'm gonna touch on wood and say thanks to everyone that hoped on this train and helped, I ended up poking something that was more than I could handle so I wouldn't have been able to fix it by myself, or at least not this soon. So thanks!!

As a final note, I ended up testing mp3 more, and the pops are still there, so this pull request only fixes the OGG pops after all.

**Comment by AThousandShips** [comment]
You need to rebase your branch, your branch is behind

File: modules/vorbis/resource_importer_ogg_vorbis.cpp [hunk 7]
```diff
@@ -40,6 +40,7 @@
 
 #include <ogg/ogg.h>
 #include <vorbis/codec.h>
+#include <map>
```
Comment (AThousandShips) [inline modules/vorbis/resource_importer_ogg_vorbis.cpp:43]:
```suggestion
```
No standard library

File: modules/vorbis/resource_importer_ogg_vorbis.cpp [hunk 8]
```diff
@@ -184,14 +185,15 @@ Ref<AudioStreamOggVorbis> ResourceImporterOggVorbis::load_from_buffer(const Vect
 		ERR_FAIL_COND_V_MSG(err != 0, Ref<AudioStreamOggVorbis>(), "Ogg stream error " + itos(err));
 		int desync_iters = 0;
 
-		Vector<Vector<uint8_t>> packet_data;
+		std::map<uint64_t, Vector<Vector<uint8_t>>> sorted_packets;
```
Comment (AThousandShips) [inline modules/vorbis/resource_importer_ogg_vorbis.cpp:188]:
```suggestion
		RBMap<uint64_t, Vector<Vector<uint8_t>>> sorted_packets;
```

File: modules/vorbis/resource_importer_ogg_vorbis.cpp [hunk 9]
```diff
@@ -207,16 +209,24 @@ Ref<AudioStreamOggVorbis> ResourceImporterOggVorbis::load_from_buffer(const Vect
...
 
 			PackedByteArray data;
 			data.resize(packet.bytes);
 			memcpy(data.ptrw(), packet.packet, packet.bytes);
-			packet_data.push_back(data);
+			sorted_packets[granule_pos].push_back(data);
 			packet_count++;
 		}
+		Vector<Vector<uint8_t>> packet_data;
+		for (auto no_autos_in_godot : sorted_packets) {
```
Comment (AThousandShips) [inline modules/vorbis/resource_importer_ogg_vorbis.cpp:223]:
```suggestion
		for (const KeyValue<uint64_t, Vector<Vector<uint8_t>> &pair : sorted_packets) {
```

File: modules/vorbis/resource_importer_ogg_vorbis.cpp [hunk 10]
```diff
@@ -207,16 +209,24 @@ Ref<AudioStreamOggVorbis> ResourceImporterOggVorbis::load_from_buffer(const Vect
...
+			for (auto packets : no_autos_in_godot.second) {
```
Comment (AThousandShips) [inline modules/vorbis/resource_importer_ogg_vorbis.cpp:224]:
```suggestion
			for (const Vector<uint8_t> &packets : pair.value) {
```

**Comment by strellydev** [comment]
Sorry if I'm being dumb, but, rebase it with what? I'm not used to working with git to this extent so I'm not sure how to proceed.

**Comment by AThousandShips** [comment]
See [here](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#updating-your-branch)

**Comment by ellenhp** [comment]
> As a final note, I ended up testing mp3 more, and the pops are still there, so this pull request only fixes the OGG pops after all.

Someone correct me if I'm wrong, but I remember right I think MP3 doesn't support sample-accurate seeks. At any rate, we're using minimp3 for those so it might be an upstream issue. Having at least one lossy audio format working flawlessly will be huge though so I'm really happy that we managed to figure this out. :)

File: modules/minimp3/resource_importer_mp3.cpp [hunk 11]
```diff
@@ -113,7 +113,7 @@ Ref<AudioStreamMP3> ResourceImporterMP3::import_mp3(const String &p_path) {
 
 Error ResourceImporterMP3::import(const String &p_source_file, const String &p_save_path, const HashMap<StringName, Variant> &p_options, List<String> *r_platform_variants, List<String> *r_gen_files, Variant *r_metadata) {
 	bool loop = p_options["loop"];
-	float loop_offset = p_options["loop_offset"];
+	double loop_offset = p_options["loop_offset"];
```
Comment (ellenhp) [inline modules/minimp3/resource_importer_mp3.cpp:116]: Could we make these changes in a separate PR since it didn't end up fixing the MP3 pops?

**Review by ellenhp — COMMENTED** [review]
LGTM for audio. Just a nit. I'm going to wait to approve until the dust settles with all the rebasing and @AThousandShips suggestions are addressed.

File: modules/minimp3/resource_importer_mp3.cpp (hunk 11 above)
Comment (strellydev) [reply modules/minimp3/resource_importer_mp3.cpp:120]: For sure, I'll change it back.

**Comment by strellydev** [comment]
Okay, I think everything should be fixed now.

Thanks a lot to you too @AThousandShips for putting up with me, and for pointing out all the dumb things I left out.

**Comment by AThousandShips** [comment]
No problems! Nothing to put up with! It's a learning experience

**Comment by bs-mwoerner** [comment]
Oh, I think that style violation is on me. There was an error message about some problem with the Formatter but I forgot to follow up on that before comitting.

**Comment by ellenhp** [comment]
@strellydev you were part of a group of people who collectively fixed one of the most complex Godot engine bugs I've ever seen, and I've seen some crazy stuff. Don't beat yourself up for struggling with git. Git is notoriously confusing for stuff like this. No negativity, I won't allow it. :laughing: 

I think there are still some changes in the mp3 streams to revert. You'll know you have it right when you can run a `git diff master` on your branch and it shows only the ogg/vorbis changes. After that you can amend your commit and force-push.

**Comment by strellydev** [comment]
Reverted the two minimp3 files as well, and fixed the style error.

**Comment by ellenhp** [comment]
@strellydev Currently building your fork to test. Also approved the CI workflows.I think this can be merged without Juan's approval because I have more context on the ogg code and if I remember right Juan doesn't like working directly with container formats (who can blame him?). I'm going to test it pretty extensively before approving.

I'm not sure on timing though. Does anyone know if we're freezing `master` for a release soon? Even if we are, this might be worth merging anyway because users have been complaining about it for years and I'd love to get it out in the next release. @AThousandShips do you know about timing? We can also summon Remi to hit the green button once it's all ready to go. That's what I usually do. :)

**Comment by AThousandShips** [comment]
Feature freeze is in effect right now, looking at release early November, but as long as it doesn't have any serious side-effects it can probably be merged in 4.2 given the green light as it's a bug fix

File: modules/vorbis/audio_stream_ogg_vorbis.h [hunk 12]
```diff
@@ -107,9 +107,9 @@ class AudioStreamOggVorbis : public AudioStream {
 	friend class AudioStreamPlaybackOggVorbis;
 
 	int channels = 1;
-	float length = 0.0;
+	double length = 0.0; // Changed to double because it's getter returns a double.
```
Comment (ellenhp) [inline modules/vorbis/audio_stream_ogg_vorbis.h:110]: Nit: here and below, you don't need to justify your changes with inline comments. The place for discussion of the changes themselves is the PR. Inline comments should be relevant for the next person to read the code, and they won't necessarily know about or care about what the broken code looked like before your changes.

**Review by ellenhp — COMMENTED** [review]
One minor suggestion about the comments. Otherwise everything looks good. I tested it on all the files I could get my hands on. They all looped perfectly. I also scrubbed back and forth through entire files with zero issues. That used to spam tons of log messages and sound terrible. I think we have a bug-free ogg importer and player now? Amazing work. Since we made changes to the importer, we should document in the release notes that files may need to be re-imported in the new version of the editor for the fixes to fully take effect. Can you call attention to that in the PR description with a little thing in bold at the bottom just so it doesn't get missed?

File: modules/vorbis/audio_stream_ogg_vorbis.h (hunk 12 above)
Comment (strellydev) [reply modules/vorbis/audio_stream_ogg_vorbis.h]: Removed the comments!

**Comment by MJacred** [comment]
@ellenhp: Before you do the final approve, please let me test through my files as well. I'll do so this night and report back.  
I can already confirm that 3 popping files are playing just fine after the most recent changes.

I need some tea, there are several dozen files...

**Comment by ellenhp** [comment]
@MJacred Sure thing.

**Comment by MJacred** [comment]
@ellenhp: ok, I'm done.

So, my result is: Only one file was popping. But it also popped in Audacity. And only at a rather high volume output. Therefore a file issue.  
I tested on both speakers (stereo) and audio jack headphones (yeah, sometimes it pops in one but not the other. Or at least the pops are more audible in one or the other).  
Though I must say all my files have a loop offset > 0, so I didn't test looping to beginning.

**The final verdict from my end: the looping is so smooth, you can slip on it.**

Now I want to celebrate. All of us have earned some celebration :partying_face: I'll sleep well tonight

---

> […] is exactly what I ended up doing

@bs-mwoerner: Haha. Kinda glad I narrowed down on the solution over time and didn't get lost. And thank you again for your contribution!

**Comment by strellydev** [comment]
Imma dance

**Review by ellenhp — APPROVED** [review]

**Comment by ellenhp** [comment]
@akien-mga I think it's worth merging this despite the freeze. I'll let you make that call though.

@strellydev Thank you for your hard work tracking down this bug, isolating the problem areas and coming up with partial fixes. Also for your patience with git and all the nit comments I left.
@MJacred Thank you for the test files, help tracking down the issue and ultimately proposing a working solution.
@bs-mwoerner Thank you for getting this across the finish line.

I'm so glad this is fixed. I feel like I can breathe again. It's been a source of anxiety for me for years.

**Comment by AThousandShips** [comment]
Unless this is considered an enhancement or a new feature it's unaffected by freeze, unless it's a risky fix that we want to test for longer I don't see any problem merging for 4.2

**Review by akien-mga — APPROVED** [review]
Amazing teamwork everyone!

**Comment by akien-mga** [comment]
Thanks everyone, and congrats @strellydev and @bs-mwoerner for your first merged Godot contribution :tada:

**Comment by ellenhp** [comment]
@akien-mga just to make sure you don't miss it for release notes: there are importer changes here so users will (potentially? needs testing) have to re-import ogg files to get the full effect of this fix.

File: modules/ogg/ogg_packet_sequence.cpp [hunk 13]
```diff
@@ -159,7 +159,9 @@ bool OggPacketSequencePlayback::next_ogg_packet(ogg_packet **p_packet) const {
 
 	*p_packet = packet;
 
-	packet_cursor++;
+	if (!packet->e_o_s) { // Added this so it doesn't try to go to the next packet if it's the last packet of the file.
```
Comment (nikitalita) [inline modules/ogg/ogg_packet_sequence.cpp:162]: This change makes it such that this function will NEVER return false; at EOS, the packet_cursor always stays pointed to the last packet, so this will keep returning the last packet forever.

Comment (bs-mwoerner) [reply modules/ogg/ogg_packet_sequence.cpp:162]: That may be a bit unintuitive yes. Normally, callers check the `e_o_s` flag and are supposed to stop reading at the end of the stream. If they don't, then they would have previously gotten false and logged an error, whereas now, they get true and the last packet again. This doesn't make a difference as long as callers correctly check the `e_o_s` flag, but you might argue that the previous way of erroring out when trying to read past the end of the stream was the safer route.

I think this change wasn't directly related to the fix but rather one of a few modifications made in an attempt to narrow down the original problem.

Comment (nikitalita) [reply modules/ogg/ogg_packet_sequence.cpp:162]: Returning a boolean value instead of an error makes it look like one of those classic reader functions that you put this in the condition of a while loop and keep going until it returns false; the fact that it doesn't behave that way is very confusing, and I ended up banging my head against the wall for a couple of hours trying to figure out why this kept not returning false.

In either case, I've tested removing this check with the example projects for the issues that this PR is purported to have fixed, and they work fine.

Comment (ellenhp) [reply modules/ogg/ogg_packet_sequence.cpp:162]: Can you provide an ogg/vorbis file that causes this issue? Here or in the comments of #85996

Comment (nikitalita) [reply modules/ogg/ogg_packet_sequence.cpp:162]: It's not really a problem with any particular ogg file, it's an issue with this being part of the public API and it having confusing behavior. It's also semantically incorrect, since there's no case where this function will actually return false.

When something other than godot uses this function (e.g a custom module) and expects the `next_ogg_packet()` to return false when there's no more packets to be read (e.g. `while (playback->next_ogg_packet(&pkt))`, this can cause an infinite loop.

Comment (ellenhp) [reply modules/ogg/ogg_packet_sequence.cpp:162]: Okay, you mentioned an infinite loop so I assumed it was a reproducible case rather than an API issue. Sorry for misunderstanding.

**Comment by YuriSizov** [comment]
Unfortunately cannot be cleanly cherry-picked because it's based on the codebase which includes https://github.com/godotengine/godot/pull/78084. A dedicated PR for 4.1 is welcome, if we want to fix this issue in that branch.
