### PR TITLE
Fix inserting bezier curve in Animation editor

### LINKED ISSUE #24523: Add key button not function collectly when using bezier curve.
**Godot version:**
Godot3.1.alpha.custom_build.6cdcde7

**Issue description:**
In animation editor, if you choose "beizer curve" mode when press add key button, after then every time you click add key button, it will ask you again if you want to use "beizer curve" mode, and it will add same track again and again.

**Steps to reproduce:**

1.add a node2d node to scene.
2.add an animationPlayer node.
3.create a new animation.
4,select the node2d node, click add key button beside position.
5.choose "beizer curve" mode.

and then, if you try to add key by clicking the button, it will ask your again the question, and create key on new track.

add key button

### PR DESCRIPTION
**Pull request by volzhs**
Fix #24523

### CODE REVIEW

File: editor/animation_track_editor.cpp [hunk 1]
```diff
@@ -3790,8 +3790,9 @@ void AnimationTrackEditor::insert_value_key(const String &p_property, const Vari
 				value = p_value; //all good
 			} else {
 				String tpath = animation->track_get_path(i);
-				if (NodePath(tpath.get_basename()) == np) {
-					String subindex = tpath.get_extension();
+				int index = tpath.find_last(":");
+				if (NodePath(tpath.substr(0, index + 1)) == np) {
+					String subindex = tpath.substr(index + 1, tpath.length() - index);
```
Comment (akien-mga) [inline editor/animation_track_editor.cpp]: You can also use `left()` and `right()` which are somewhat more convenient for this.
Arewe sure that there will always be a `:`?

Comment (volzhs) [reply editor/animation_track_editor.cpp]: yes. it comes from here
https://github.com/godotengine/godot/blob/3bcedd02b2eb2cfb78327249cafa195b55cdc499/editor/animation_track_editor.cpp#L3907-L3954

**Comment by akien-mga** [comment]
Thanks!
