### PR TITLE
Clamp NavigationMesh sample_distance above zero

### LINKED ISSUE #38173: Godot crash while generating the NavigationMeshInstance
**Godot version:**
3.2.1 stable
**OS/device including version:**
Ubuntu Budgie 19.10
**Issue description:**
Godot crash while generating the `NavigationMeshInstance`, when `0` is set for `NavigationMeshInstance/Detail/Sample Distance`
**Steps to reproduce:**
- Add `Navigation` node
- Add `NavigationMeshInstance` node as child of `Navigation`
- In `NavigationMeshInstance` node, add a `NavigationMesh`
- Inside `NavigationMesh`, go to `Detail` section and drag `Sample Distance` to `0`
- Add a MeshInstance with a cube (or whatever)
- Select `NavigationMeshInstance` node and click `Bake NavMesh`
```
~/Bureau handle_crash: Program crashed with signal 11                                                        13:36:44
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x46470) [0x7f857efe2470] (??:0)
[2] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0x241eb6a] (??:?)
[3] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0x8c55d9] (<artificial>:?)
[4] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0x91b67b] (??:?)
[5] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0x25f97d6] (<artificial>:?)
[6] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0x25f9a75] (<artificial>:?)
[7] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0x2898209] (??:?)
[8] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0xbe6033] (??:?)
[9] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0xc8c576] (??:?)
[10] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0xc8d570] (??:?)
[11] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0x184b4a5] (<artificial>:?)
[12] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0x184b9ba] (<artificial>:?)
[13] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0x184bd41] (??:?)
[14] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0x1f6be86] (??:?)
[15] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0xc01314] (??:?)
[16] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0xbce1c1] (??:?)
[17] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0x18c8488] (<artificial>:?)
[18] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0x18eaf7f] (<artificial>:?)
[19] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0x18ec066] (??:?)
[20] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0x18ec1be] (<artificial>:?)
[21] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0x2725c26] (??:?)
[22] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0xbe6033] (??:?)
[23] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0xbce245] (??:?)
[24] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0x1883923] (??:?)
[25] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0x1886a4c] (??:?)
[26] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0x28cd843] (??:?)
[27] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0x28caaad] (<artificial>:?)
[28] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0x2a0c4ab] (<artificial>:?)
[29] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0x84ac3c] (??:?)
[30] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f857efc31e3] (??:0)
[31] /home/nutriz/Bureau/Godot_v3.2.1-stable_x11.64() [0x857fde] (??:?)
-- END OF BACKTRACE --
```

**Minimal reproduction project:**
[NavMeshCrash.zip](https://github.com/godotengine/godot/files/4528587/NavMeshCrash.zip)

Open the project, select `NavigationMeshInstance` node and click `Bake NavMesh`, it will crash

### PR DESCRIPTION
**Pull request by smix8**
Previously Godot would set all `sample_distance` values < 0.9 to 0 which causes the crashes. This pr limits the sample_distance range selection to 0.1 - 16.0 and also clamps sample_distance that are below 0.1 before ReCast receives them.

While default ReCast library has support for 0.0 and >= 0.9 'sample_distance' the Godot implementation does not for a zero value. In fact against the ReCast doc numbers below 0.9 also work in Godot. Godot was already using values as low as 0.01 on small grids cause the Godot implementation is multiplying the `sample_distance` with `cell_size` behind the scene and cell_size can get as low as 0.1 in value.

Fixes #38173

### CODE REVIEW

File: modules/navigation/navigation_mesh_generator.cpp [hunk 1]
```diff
@@ -445,7 +445,7 @@ void NavigationMeshGenerator::_build_recast_navigation_mesh(
 	cfg.minRegionArea = (int)(p_nav_mesh->get_region_min_size() * p_nav_mesh->get_region_min_size());
 	cfg.mergeRegionArea = (int)(p_nav_mesh->get_region_merge_size() * p_nav_mesh->get_region_merge_size());
 	cfg.maxVertsPerPoly = (int)p_nav_mesh->get_verts_per_poly();
-	cfg.detailSampleDist = p_nav_mesh->get_detail_sample_distance() < 0.9f ? 0 : p_nav_mesh->get_cell_size() * p_nav_mesh->get_detail_sample_distance();
+	cfg.detailSampleDist = p_nav_mesh->get_detail_sample_distance() < 0.1f ? 0.1f : p_nav_mesh->get_cell_size() * p_nav_mesh->get_detail_sample_distance();
```
Comment (akien-mga) [inline modules/navigation/navigation_mesh_generator.cpp:448]: Maybe you can instead remove this check here, and add it in `set_detail_sample_distance`? There's already a validation that it's not less than 0, it could instead validate that it's not less than 0.1f. So at least if users try to set it they get an error and not just a silent clamp.

**Review by akien-mga — APPROVED** [review]
Aside from my comment, makes sense to me.

File: modules/navigation/navigation_mesh_generator.cpp (hunk 1 above)
Comment (smix8) [reply modules/navigation/navigation_mesh_generator.cpp:448]: Does the setter also run when someone loads in an old navmesh resource with a stored zero value?
I will change the setter to 0.1 regardless but I would like to keep this line to avoid any chance to crash ReCast with old navmesh properties.

Comment (akien-mga) [reply modules/navigation/navigation_mesh_generator.cpp:448]: Yeah properties always go through the setter, also when reading from config, so it should be safe.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.
