### PR TITLE
`LineEdit` add member `keep_editing_on_text_submit`

### LINKED ISSUE #100230: Regression: LineEdit loses focus after hitting enter.
### Tested versions

- Reproducible in 4.4-dev6.
- Doesn't happen in 4.3 stable.

### System information

Godot v4.4.dev6 - Windows 10.0.19045 - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 32.0.15.6603) - AMD Ryzen 7 3700X 8-Core Processor (16 threads)

### Issue description

If you have a line edit and type something then press enter, you can no longer type in the edit box until you re-focus it by clicking or pressing enter again.

### Steps to reproduce

* Add a LineEdit to the scene.
* Type in the line edit.
* Press enter.
* Note that you can't type anymore.

(Very obvious with the dev console addon.  You can only type one command at a type).

### Minimal reproduction project (MRP)

[test_console.zip](https://github.com/user-attachments/files/18071805/test_console.zip)

### PR DESCRIPTION
**Pull request by WhalesState**
* Fixes: https://github.com/godotengine/godot/issues/100230#issuecomment-2531281622

Add member `editing_on_text_submit` to optionally allow users to exit edit mode when Enter is pressed.

### CODE REVIEW

File: scene/gui/line_edit.cpp [hunk 1]
```diff
@@ -2990,6 +3001,12 @@ LineEdit::LineEdit(const String &p_placeholder) {
 	set_placeholder(p_placeholder);
 
 	set_editable(true); // Initialize to opposite first, so we get past the early-out in set_editable.
+
+#ifdef TOOLS_ENABLED
+	set_editing_on_text_submit(Engine::get_singleton()->is_editor_hint());
+#else
+	set_editing_on_text_submit(false);
```
Comment (WhalesState) [inline scene/gui/line_edit.cpp:3008]: I think this line should be removed after building since the default is already false.

**Comment by WhalesState** [comment]
how to pass the checks, it should be false but the doctool `Engine::is_editor_hint()` returns true. needs a better trick to keep it enabled by default for editor nodes.

**Comment by KoBeWi** [comment]
Maybe you could add a static variable, e.g. `in_editor` which is set to true in EditorNode, and LineEdit would enable the new property if the variable is true and is not part of edited scene.
Somewhat related to #89448 (similar problem)

File: scene/gui/line_edit.cpp [hunk 2]
```diff
@@ -2990,6 +3001,10 @@ LineEdit::LineEdit(const String &p_placeholder) {
 	set_placeholder(p_placeholder);
 
 	set_editable(true); // Initialize to opposite first, so we get past the early-out in set_editable.
+
+#ifdef TOOLS_ENABLED
+	set_editing_on_text_submit(!(Engine::get_singleton()->is_editor_hint() || Engine::get_singleton()->is_project_manager_hint()));
```
Comment (WhalesState) [inline scene/gui/line_edit.cpp:3006]: Found that `main.cpp` falls back to project manager when running the `--doctool`.

**Comment by WhalesState** [comment]
> Maybe you could add a static variable, e.g. `in_editor` which is set to true in EditorNode, and LineEdit would enable the new property if the variable is true and is not part of edited scene. Somewhat related to #89448 (similar problem)

Added `Engine::is_cmdline_tool()` to know if it's a cmdline tools like --doctool without importing `main/main.cpp`.

**Comment by KoBeWi** [comment]
Half of the changes here is for changing default between editor and game and... they don't seem to even work. I think the property can be disabled by default like now, without the additional hacks. It's actually undesired in the editor, e.g. in the inspector.

**Comment by WhalesState** [comment]
> What was the reason for the current implementation? (i.e. having separate defaults)

Yes, for Editor, we are using the new behavior for all `LineEdit` nodes except for the `Script Editor` search, and for games, we should revert it back for compatibility, if we set the default to false, we will need to add an extra line for every editor LineEdit node, and if we set the default to true, we are breaking compatibility with 4.3.

**Comment by KoBeWi** [comment]
Eh, but with the new property, isn't `true` the old default behavior?

**Comment by WhalesState** [comment]
> Eh, but with the new property, isn't `true` the old default behavior?

Can we keep the default value true? because it's true since we have merged the `LineEdit` focus mode PR, and we are breaking compatibility already for months in 4.4, i just wanted a solution since every new issue related to the old behavior will be marked as a compatibility break.

**Comment by KoBeWi** [comment]
> we are breaking compatibility already for months in 4.4

Compatibility with stable release is more important.

That said, I do think the new behavior makes more sense, so you can keep it `false`. But then the extra changes for editor default are unnecessary as I said, because the desired editor default is also `false`.

So to sum up.
The old behavior is that when you press Enter, the LineEdit keeps editing.
The new behavior is that when you press Enter, the LineEdit stops "editing", but keeps focus. To input value again, you need to press Enter again.

The issue is about the change in behavior; the user prefers the old one for some dev console addon, which makes sense. However it's the only report we got, so it's safe to assume that the new behavior is better in general.

Your new property `editing_on_text_submit` allows switching between old and new behavior, with `false` being new behavior and `true` being old. So to keep the new behavior by default, the default value of this property should be `false`. 

> default value is false for game and true for editor and editor plugins.

I'm not sure what this part was for. I think the default should be consistent. Also with the current implementation, `editing_on_text_submit` might have unexpected behavior in editor plugins.

btw I'd rename the property to `keep_editing_on_text_submit`.

**Comment by WhalesState** [comment]
OK, the default is now false, and we should note this as a breaking change in 4.4.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
