### PR TITLE
Remapped the numpad keys on linux when numlock is off

### LINKED ISSUE #54814: Keypad navigation in text editor no longer working
### Godot version

v4.0.dev.20211108.official [596865366]

### System information

Manjaro Linux (swaywm)

### Issue description

Seems like there was a regression of https://github.com/godotengine/godot/issues/720

With num lock OFF pressing 7/1/9/3 for home/end/PgUp/PgDn no longer work in the editor. It does on 3.4

### Steps to reproduce

* Open up a script in the godot script editor.

* Turn num lock off

* Press 7, 1, 9, or 3. Nothing happens

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by MladoniSzabi**
On Linux, when using the numpad while numlock is off doesn't do anything.
Made the numpad keys map to the correct control keys.

Resolves: #54814.

### CODE REVIEW

**Comment by Calinou** [comment]
Did you test with numlock enabled as well?

File: platform/linuxbsd/key_mapping_x11.cpp [hunk 1]
```diff
@@ -109,16 +109,16 @@ static _XTranslatePair _xkeysym_to_keycode[] = {
...
-	{ XK_KP_Right, Key::KP_6 },
-	{ XK_KP_Home, Key::KP_7 },
-	{ XK_KP_Up, Key::KP_8 },
-	{ XK_KP_Page_Up, Key::KP_9 },
+	{ XK_KP_Insert, Key::INSERT },
+	{ XK_KP_End, Key::END },
+	{ XK_KP_Down, Key::DOWN },
+	{ XK_KP_Page_Down, Key::PAGEDOWN },
+	{ XK_KP_Left, Key::LEFT },
+	{ XK_KP_Begin, Key::KP_5 }, // not sure what this should be, doesn't do anything if left like this
```
Comment (akien-mga) [inline platform/linuxbsd/key_mapping_x11.cpp:117]: It's interesting that it doesn't do anything instead of inserting `5`.

X11 seems to define `XK_KP_Begin` as "BOL" which I suppose means "begin of line" as opposed to "EOL" which is "end of line". So I think they want it to be interpreted the same way as `Key::HOME` like `XK_KP_Begin`?

That being said, I'm on X11 / KDE and neither GTK+3 apps (Firefox) nor Qt5 ones (Dolphin, Konsole) seem to do anything with `XK_KP_Begin`. The only application I found where it seems to do _something_ is `xterm` where it triggers a weird refresh (the terminal flashes from light theme to dark theme for a second).

So I think the standard expectation should indeed be that this key doesn't do anything.
I'd suggest documenting it like this:
```suggestion
	// X11 documents this (numpad 5) as "begin of line" but no toolkit seems to interpret it this way.
	//{ XK_KP_Begin, Key::NONE },
```

**Comment by akien-mga** [comment]
Tested and I confirm that it works fine, when numlock is on the number keys are received, when it's off the directional keys are used.

Would be good to confirm if that matches the behavior on Windows and macOS @bruvzg.

**Comment by bruvzg** [comment]
> Would be good to confirm if that matches the behavior on Windows and macOS @bruvzg.

There's no Num Lock on macOS, numpad keys always produce `Kp *` keycodes. I'll check it on Windows a bit later.

**Comment by bruvzg** [comment]
On Windows, its `Kp *` when Num Lock is on and `Home/Up/PageUp` etc. when it's off, `5` is `Clear`. Physical keycodes are always `Kp *`.

**Comment by akien-mga** [comment]
> `5` is `Clear`.

Does that actually clear text in e.g. a LineEdit? Or what does it do? If it does clear content it sounds a bit dangerous :D

> Physical keycodes are always `Kp *`.

Would be good to check if it's the same with this PR on Linux. Though I don't know if the behavior on Windows is what users would expect.

**Comment by bruvzg** [comment]
> Does that actually clear text in e.g. a LineEdit? Or what does it do? If it does clear content it sounds a bit dangerous :D

No, it's emitting `Key::CLEAR` event, but I do not think it's bound to any action in Godot.

**Comment by bruvzg** [comment]
Checked it on Fedora 36 as well, I can confirm the issue, and this PR is fixing it. Behavior seems to be the same as on Windows (except `5` → `Clear`).

**Comment by MladoniSzabi** [comment]
I made numpad 5 map to Key::CLEAR and changed the comments. Is this OK?

File: platform/linuxbsd/key_mapping_x11.cpp [hunk 2]
```diff
@@ -109,16 +109,16 @@ static _XTranslatePair _xkeysym_to_keycode[] = {
 	{ XK_KP_8, Key::KP_8 },
 	{ XK_KP_9, Key::KP_9 },
 	// same but with numlock
```
[the remark this answers is not in the document]
Comment (MladoniSzabi) [reply platform/linuxbsd/key_mapping_x11.cpp]: done

File: platform/linuxbsd/key_mapping_x11.cpp (hunk 1 above)
Comment (MladoniSzabi) [reply platform/linuxbsd/key_mapping_x11.cpp]: done but changed to Key::CLEAR as suggested below

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
