### PR TITLE
Editor: Fix default behavior of `@export_dir` rejects folders in drag and drop

### LINKED ISSUE #118646: Default behaviour of `@export_dir` rejects folders in drag and drop
### Tested versions

- Tested in 4.4 and 4.6/4.6.2 but seems to be default behaviour of `@export_dir` annotation.

### System information

Godot v4.6.2.stable - Windows 11 (build 26200) - Multi-window, 1 monitor - Direct3D 12 (Forward+) - dedicated AMD Radeon(TM) R4 Graphics (Advanced Micro Devices, Inc.; 27.20.20912.1002) - AMD A6-9225 RADEON R4, 5 COMPUTE CORES 2C+3G (2 threads) - 11.44 GiB memory

### Issue description

It isn't possible to drag and drop folders into an exposed variable using the @export_dir annotation. But it does accept files.

Image

### Steps to reproduce

Any new project, just create a script and then expose a property with `@export_dir` annotation. Drag a folder then a file, it should reject the folder and accept the file.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by unit-tick**
Closes #118646 

`@export_dir ` currently doesn't accept folders in drag and drop, but it does accept files, which shouldn't be intended behaviour. This PR reverses that. So it now only accepts directories and rejects files.

Old export behaviour
old_behaviour

new export behaviour
new_behaviour

### CODE REVIEW

File: editor/inspector/editor_properties.h [hunk 1]
```diff
@@ -190,6 +190,7 @@ class EditorPropertyTextEnum : public EditorProperty {
 class EditorPropertyPath : public EditorProperty {
 	GDCLASS(EditorPropertyPath, EditorProperty);
 	Vector<String> extensions;
+	bool needs_extension = false;
```
Comment (KoBeWi) [inline editor/inspector/editor_properties.h]: Why is it needed if `folder` exists?

**Review by KoBeWi — COMMENTED** [review]
I think `@export_dir` could still accept files, but assign the base directory instead of full path. (not sure if useful though)

File: editor/inspector/editor_properties.h (hunk 1 above)
Comment (unit-tick) [reply editor/inspector/editor_properties.h]: In my search I didn't find `folder`, all I found was the `drag_data["type"]` being either `"files"` or `"files_and_dirs"`. So I added that to make it so that if `@export_file` is used it will reject the file because in my first attempt it worked perfectly except in Arrays, as both `@export_file` and `@export_dir` then accepted both files and folders.

Now it works properly with file exports rejecting folders (standard behaviour) and directories rejecting files (new behaviour).

Comment (KoBeWi) [reply editor/inspector/editor_properties.h]: > In my search I didn't find folder

How. It's next to the parameter you modified
image
It serves the same purpose as your new flag, but reveresed.

Comment (unit-tick) [reply editor/inspector/editor_properties.h]: Damn you're right, my bad. I'll edit it.

Comment (unit-tick) [reply editor/inspector/editor_properties.h]: About `@export_dir` accepting the base directory of the files, I think "prettifying" this right now isn't going to be very useful since I didn't find any complaints about it means that most people use the Dialog to find their directories (based on the lack of traction the proposal got). The reason I went ahead with it anyway is because I believe it should be intended behaviour for the `@export_dir` to accept folders and reject files. I believe it should be kept as barebones as possible for now.

File: editor/inspector/editor_properties.cpp [hunk 2]
```diff
@@ -819,17 +816,24 @@ bool EditorPropertyPath::_can_drop_data_fw(const Point2 &p_point, const Variant
...
 	}
-	if (String(drag_data["type"]) != "files") {
-		return false;
-	}
-	const Vector<String> filesPaths = drag_data["files"];
-	if (filesPaths.is_empty()) {
-		return false;
-	}
+	if (folder) {
+		if (String(drag_data["type"]) != "files_and_dirs") {
```
Comment (KoBeWi) [inline editor/inspector/editor_properties.cpp:815]: `files_and_dirs` is also used when dragging, well, files _and_ dirs. In that case a file may still get assigned to a directory property. You need to skip files from the list (directory path always ends with `/`).

Although drop always uses the first element in the list, so you could just add a check if files size is 1 and don't accept multiple entries.

File: editor/inspector/editor_properties.cpp
Comment (KoBeWi) [inline editor/inspector/editor_properties.cpp]: Somewhat unrelated, but most of this code is unnecessary. `_can_drop_data_fw()` already checks this, so the data is guaranteed to be what is expected.

Comment (unit-tick) [reply editor/inspector/editor_properties.cpp]: That code was in the original so I just left it as-is, but I can update it if necessary.

Comment (KoBeWi) [reply editor/inspector/editor_properties.cpp]: It's not _necessary_, but it's close to the code you are editing, so you could as well clean it up.

File: editor/inspector/editor_properties.cpp (hunk 2 above)
Comment (unit-tick) [reply editor/inspector/editor_properties.cpp:815]: Will do that. Will also clean up the code and remove the other thing mentioned.

File: editor/inspector/editor_properties.cpp [hunk 3]
```diff
@@ -4058,6 +4063,7 @@ EditorProperty *EditorInspectorDefaultPlugin::get_editor_for_property(Object *p_
 				bool folder = p_hint == PROPERTY_HINT_DIR || p_hint == PROPERTY_HINT_GLOBAL_DIR;
 				bool save = p_hint == PROPERTY_HINT_SAVE_FILE || p_hint == PROPERTY_HINT_GLOBAL_SAVE_FILE;
 				bool enable_uid = p_hint == PROPERTY_HINT_FILE;
+
```
Comment (AThousandShips) [inline editor/inspector/editor_properties.cpp]: Random unrelated change, please restore to avoid unnecessary noise

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
