### PR TITLE
Fix CharacterBody3D stuck in some advanced scenario

### LINKED ISSUE #55191: Body is stuck with move and slide on some advanced circumstance
### Godot version

4.0 Dev (8c162f4)

### System information

macOS 11.5 

### Issue description

#52889 Brings the support of advanced cases when a body touches 2 walls on each side, however, by testing another issue I found one case not well handled:
body stuck

The body struggle and then is stuck.

### Steps to reproduce

Replicate the gif with the MRP.

### Minimal reproduction project

https://github.com/fabriceci/3d-platform-test-for-godot4

### LINKED ISSUE #55205: Visual Studio Code cannot run programs from within VSCode starting with version 1.62
### Godot version

3.4 stable

### System information

Windows 10

### Issue description

Visual Studio Code recently released version 1.62.  Unfortunately, with this version it is no longer possible to run or debug your projects from within Visual Studio Code.  I had to downgrade to version 1.61 to be able to debug again.

https://godotforums.org/discussion/comment/56303#Comment_56303

### Steps to reproduce

Create a simple scene in Godot and attach a c# script to it.  Open the script in VSCode 1.62 or higher.  Try to run the game from within VSCode.  The process will hang without launching the game.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by fabriceci**
Improvement of #52889
Fix #55191

**Before**:

body stuck

**After**:

after2

### CODE REVIEW

**Comment by Calinou** [comment]
> Fix #55205

Did you miswrite the issue number?

**Comment by fabriceci** [comment]
> > Fix #55205
> 
> Did you misspell the issue number? That issue appears to be unrelated.

Indeed ! Bad copy paste, sorry !

File: scene/3d/physics_body_3d.cpp [hunk 1]
```diff
@@ -1584,6 +1584,7 @@ void CharacterBody3D::_set_collision_direction(const PhysicsServer3D::MotionResu
 	Vector3 prev_wall_normal = wall_normal;
 	int wall_collision_count = 0;
 	Vector3 combined_wall_normal;
+	Vector3 tmp_wall_col = Vector3(); // Avoid duplicate on average calculation.
```
Comment (akien-mga) [inline scene/3d/physics_body_3d.cpp:1587]:
```suggestion
	Vector3 tmp_wall_col; // Avoid duplicate on average calculation.
```
`Vector3` is already default initialized to 0.

Comment (fabriceci) [reply scene/3d/physics_body_3d.cpp]: Always the same mistake, I promise one day I'll remember it!!

**Review by pouleyKetchoupp — APPROVED** [review]
Looks good, thank you!
