### PR TITLE
Smoke test: Log an error if `reserve()` is called with fewer elements than `size()`

### LINKED ISSUE #102612: AStar2D reserve_space
### Tested versions

-

### System information

Godot 4.3 the latest stable Win 11 64-bit

### Issue description

If the value of `num_nodes` as the `reserve_space()` argument is less than 64, the error `‘New capacity must be greater than current capacity: 64, new was: num_nodes` is printed.
However, I haven't set the capacity to 64 before. Perhaps Godot defaults to a capacity of 64, but it's worth writing about in the documentation.
The current documentation only states that `'The new capacity must be greater or equal to the old capacity.'`

### Steps to reproduce

-

### Minimal reproduction project (MRP)

-

### PR DESCRIPTION
**Pull request by Ivorforce**
Follow-up to @AThousandShips' and my conversation at https://github.com/godotengine/godot/pull/103698#issuecomment-2721117519

Currently, some core collections (`OAHashMap`, `AStar2D`, `AStar3D`, and `AHashMap`) log an error if `new_capacity < old_capacity`.
At first glance, this makes sense because you want to catch bugs in `reserve()` calling behavior.
However, the logic is flawed, because the following will also print an error:
```c++
map.reserve(10);
map.reserve(11);
// Error: It is impossible to reserve less capacity than is currently available.
```

This is because `reserve` doesn't reserve exactly the number of requested elements (for almost all collections), but rather to the next largest power of 2. This fact is not exposed to the caller. This can be confusing, and leads to callers always having to run explicit checks to avoid error messages:

```c++
if (map.capacity() < needed_capacity) {
	map.reserve(needed_capacity)
}
```

There is a good alternative: Checking for `size() < capacity` instead. This should catch the same mistake that was intended with the current check, without being misleading or accidentally exposing reserve mechanics. I don't think there is a situation where calling `reserve` is realistically correct with a number smaller than the current size.

For example, this smoke test finds the following bug:
```c++
void add_elements(LocalVector<Vector3> r_points) {
	r_points.reserve(3);
	// Should have been r_points.reserve(r_points.size() + 3);
	r_points.push_back(Vector3(1, 2, 3));
	r_points.push_back(Vector3(1, 2, 3));
	r_points.push_back(Vector3(1, 2, 3));
}
```

The suggested smoke test is added to all collections that support `reserve()`.

- *Production edit: This closes https://github.com/godotengine/godot-proposals/discussions/12285.*
- Closes https://github.com/godotengine/godot/issues/102612

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Code looks good to me.

File: core/math/a_star.cpp [hunk 1]
```diff
@@ -259,8 +259,6 @@ int64_t AStar3D::get_point_capacity() const {
 }
 
 void AStar3D::reserve_space(int64_t p_num_nodes) {
-	ERR_FAIL_COND_MSG(p_num_nodes <= 0, vformat("New capacity must be greater than 0, new was: %d.", p_num_nodes));
```
Comment (akien-mga) [inline core/math/a_star.cpp:262]: This should likely be kept, as this condition would still trigger an error in the template, and that's not a clear relationship to the caller of `AStar3D::reserve_space` that it's calling `reserve` on a container and how to interpret this error.

Comment (Ivorforce) [reply core/math/a_star.cpp:262]: Agreed!
