### PR TITLE
Use an enum to represent screen orientation in the Project Settings

### LINKED ISSUE #45422: iOS export is confusing around handling of orientation (configurable both in project settings and export preset)
**Godot version:**
3.2.3 Mono official build.

**OS/device including version:**
macbook Pro running catalina 10.15,6

**Issue description:**
have tried with several simple projects and the .ipa isn'tcreated (see issue 45421)
but when running the xcode project produced the graphics in the start scene are displayed sideways

see screenshots:
project in editor:
editor-sshot

same project in iphone simulator:
orientation-sshot

steps to reproduce: 
1. create a simple project  with a viewport that should  fit any modern  iphone display.
2. select export... from the project menu.
3. select the ios(Runnable) preset
4. enter a valid team id, and bundle id
5. select the  export path to a location outside of the project.
6. select all the required icons, and screens as per the documentation.
7. click the export Project button, enter an ipa filename and click save.
8. open the project in xcode.

expected results:
images displayed in the viewport should  look as they do when running in godot

actual results:
ithe entire viewport  isrotated  ro

tated 90 degrees

**Minimal reproduction project:**

[csharptest_project3.zip](https://github.com/godotengine/godot/files/5863087/csharptest_project3.zip)

### PR DESCRIPTION
**Pull request by Calinou**
`master` version of https://github.com/godotengine/godot/pull/48943 (*not* backwards compatible).

- Tweak the setting property hint to be more informative.
- Make the setting a "basic" setting so it appears when Advanced Settings is disabled.
- Remove redundant orientation setting in the iOS export preset. The project setting is now used (like on Android).

Projects upgrading from a previous version will have to set the screen orientation again in the Project Settings if it wasn't set to the default value ("landscape").

This closes https://github.com/godotengine/godot/issues/45422.

### CODE REVIEW

File: platform/iphone/export/export.cpp [hunk 1]
```diff
@@ -501,18 +496,39 @@ void EditorExportPlatformIOS::_fix_config_file(const Ref<EditorExportPreset> &p_
...
-				orientations += "<string>UIInterfaceOrientationLandscapeLeft</string>\n";
-			}
-			if ((bool)p_preset->get("orientation/landscape_right")) {
-				orientations += "<string>UIInterfaceOrientationLandscapeRight</string>\n";
-			}
-			if ((bool)p_preset->get("orientation/portrait_upside_down")) {
-				orientations += "<string>UIInterfaceOrientationPortraitUpsideDown</string>\n";
+			switch (screen_orientation) {
+				case DisplayServer::SCREEN_LANDSCAPE:
+					orientations += "<string>UIInterfaceOrientationLandscapeLeft</string>\n";
```
Comment (Calinou) [inline platform/iphone/export/export.cpp:504]: Can anyone confirm that `SCREEN_LANDSCAPE` has the left side of the device pointing upwards? I'm just guesstimating here.

File: platform/iphone/export/export.cpp [hunk 2]
```diff
@@ -501,18 +496,39 @@ void EditorExportPlatformIOS::_fix_config_file(const Ref<EditorExportPreset> &p_
...
+					break;
+				case DisplayServer::SCREEN_PORTRAIT:
+					orientations += "<string>UIInterfaceOrientationPortrait</string>\n";
+					break;
+				case DisplayServer::SCREEN_REVERSE_LANDSCAPE:
+					orientations += "<string>UIInterfaceOrientationLandscapeRight</string>\n";
```
Comment (Calinou) [inline platform/iphone/export/export.cpp:510]: Same as above – it should be the opposite.

File: platform/iphone/export/export.cpp (hunk 1 above)
Comment (naithar) [reply platform/iphone/export/export.cpp:504]: https://developer.apple.com/documentation/uikit/uiinterfaceorientation/landscapeleft seems about right. But I can't test it at the moment.

File: core/config/project_settings.cpp [hunk 3]
```diff
@@ -1114,7 +1114,7 @@ ProjectSettings::ProjectSettings() {
 
 	_add_builtin_input_map();
 
-	custom_prop_info["display/window/handheld/orientation"] = PropertyInfo(Variant::STRING, "display/window/handheld/orientation", PROPERTY_HINT_ENUM, "landscape,portrait,reverse_landscape,reverse_portrait,sensor_landscape,sensor_portrait,sensor");
+	custom_prop_info["display/window/handheld/orientation"] = PropertyInfo(Variant::INT, "display/window/handheld/orientation", PROPERTY_HINT_ENUM, "Landscape (Left Side Up),Portrait (Upright),Reverse Landscape (Right Side Up),Reverse Portrait (Upside Down),Sensor Landscape (Left or Right Side Up),Sensor Portrait (Upright or Upside Down),Sensor (Any Orientation)");
```
Comment (m4gr3d) [inline core/config/project_settings.cpp:1117]: I would remove the hint (in parentheses) as on Android the orientation is dependent on the [device's physical dimensions](https://developer.android.com/reference/androidx/browser/trusted/ScreenOrientation) (although it could also be overridden at the manufacturer's discretion.

**Review by m4gr3d — CHANGES_REQUESTED** [review]

**Review by m4gr3d — APPROVED** [review]

File: core/config/project_settings.cpp [hunk 4]
```diff
@@ -1114,7 +1114,7 @@ ProjectSettings::ProjectSettings() {
 
 	_add_builtin_input_map();
 
-	custom_prop_info["display/window/handheld/orientation"] = PropertyInfo(Variant::STRING, "display/window/handheld/orientation", PROPERTY_HINT_ENUM, "landscape,portrait,reverse_landscape,reverse_portrait,sensor_landscape,sensor_portrait,sensor");
+	custom_prop_info["display/window/handheld/orientation"] = PropertyInfo(Variant::INT, "display/window/handheld/orientation", PROPERTY_HINT_ENUM, "Landscape,Portrait,Reverse Landscape,Reverse Portrait,Sensor Landscape,Sensor Portrait,Sensor");
```
Comment (akien-mga) [inline core/config/project_settings.cpp:1117]: Maybe add a comment that the enum values should synced with `DisplayServer.ScreenOrientation` (and possibly add a comment before the enum definition pointing to the `display/window/handheld/orientation` hint).

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
