### PR TITLE
Fix crash on startup when external editor cannot be found.

### LINKED ISSUE #10965: Godot Crashes On Start-Up if External Editor Cannot be Found
**Operating system and Godot version:**
`Win10 x86_64` with `x86 Godot v2.1.4` from steam

**Issue description:**
Godot will crash if the external editor is unable to be located.  I encountered this bug after moving to Visual Studio Code x64.

**Steps to reproduce:**
1. Enable an external editor
1. Move or delete the editor *.exe
1. Run Godot and open a project
1. Editor will freeze and crash

**Fixed by:**
Manually editing the `editor_data/editor_settings.tres`

### PR DESCRIPTION
**Pull request by fodinabor**
Fixes #10965
Is already fixed for 6687484958412ff0f3bd6d97cbc1fcebc7ae64d2

### CODE REVIEW

File: editor/plugins/script_editor_plugin.cpp [hunk 1]
```diff
@@ -520,6 +520,8 @@ void ScriptEditor::_update_modified_scripts_for_external_editor(Ref<Script> p_fo
 	if (!bool(EditorSettings::get_singleton()->get("external_editor/use_external_editor")))
 		return;
 
+	ERR_FAIL_COND(!get_tree());
```
Comment (akien-mga) [inline editor/plugins/script_editor_plugin.cpp]: Is this really sufficient to fix this issue? Or did you forget to commit other files changed in 6687484?

Comment (fodinabor) [reply editor/plugins/script_editor_plugin.cpp]: jup, the other changes are related to the "better user experience" part of the commit.
It crashed at line 527 (now) as get_tree() returned null.
