### PR TITLE
Fix viewport scaling at intermediate resolutions

### LINKED ISSUE #102656: Window content_scale_factor causes jitter in Control size
### Tested versions

Reproducible in 4.4-beta3, 4.3-stable

### System information

Godot v4.4.beta3 - Ubuntu 24.04.1 LTS 24.04 on Wayland - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - integrated Intel(R) UHD Graphics (CML GT2) - Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 threads)

### Issue description

Using the recommended way to scale UI to screen resolution by setting `get_tree().root.content_scale_factor` (either in the project settings or from script) causes Control node pixels to jitter on resizing the window. This is true even when the "Snap Controls to Pixels" option is enabled.

Interestingly, using the node's own scale factor (or scaling a parent node to rescale the entire UI) doesn't exhibit this behaviour, but causes a host of other issues with GUIs so it's not a possible workaround.

Screenshot of misaligned grid pixels from the MRP:

Image

Screenshot of the grid looking perfect at a different resolution:

Image

I also managed to reproduce this in my game with all kinds of control nodes, including fonts. In that case the jitter is a lot more visible even when resizing at high resolutions.

**Update:**

Setting `content_scale_factor = 8.0` shows that this is not even a jitter, the control node's scale is just completely off when resizing to certain resolutions. There's no need for Nearest filtering either, the effect is clearly visible even on Linear filtered textures.

https://github.com/user-attachments/assets/3cf1038a-1958-488d-acf5-fd5148140f8e

### Steps to reproduce

1. Place a control node (Confirmed with: TextureRect, Label).
3. Optionally, set the window resolution to a small value, such as 480x360. For me small window sizes (regardless of the base resolution) greatly exacerbate the effect, but it also happens from time to time on larger window sizes.
4. Set `display/window/stretch/scale` to a larger value, in my case 4.0 is enough, 8.0 makes it super visible.
5. Resize the game window by dragging the corner, and watch the control node size jitter.

### Minimal reproduction project (MRP)

[gui-scale.zip](https://github.com/user-attachments/files/18734113/gui-scale.zip)

### PR DESCRIPTION
**Pull request by KerekesDavid**
Fixes #102656: viewport scale is wrong at resolutions that are not integer multiples of content_scale_factor.

This is done by allowing size_2d_override to be Size2 instead of Size2i. This change is ~propagated to keep the exposed SubViewport consistent with the underlying implementation~ _not propagated_ to SubViewport to keep compatibility for now.

**Note:**
I see the output of `Viewport::get_visible_rect()` get treated as a Rect2i in some places, even though it returns a Rect2. Before this change, this might have been accidentally correct, since it was generated from either `size` or `size_2d_override`, which were both Size2i. It might need a second look to make sure it still works correctly, because I'm not exactly sure what all these code fragments do.

### CODE REVIEW

**Comment by KerekesDavid** [comment]
Pushed a change that would not expose this to SubViewport to avoid the compatibility warnings. (As a side note, these do not pop up in my local tests for some reason, how would I fix this?)

If someone could point me towards some resources on what kind of compatibility are we talking about here, and what is the usual philosophy that the dev team follows, that would be super appreciated. (Is it compatibility for users between versions? Is it API/ABI compatibility?)

**Comment by AThousandShips** [comment]
The compatibility notes doesn't occur locally because it's a dedicated check, but this breaks compatibility because the type changes, and that can't be done trivially

You would probably need to register compatibility methods, see [here](https://docs.godotengine.org/en/latest/contributing/development/handling_compatibility_breakages.html) for instructions

**Comment by KerekesDavid** [comment]
One last try, forgot to revert the property registration itself to Vector2I.

**Comment by AThousandShips** [comment]
The methods will still be registered with the changed type I think, so that will still break compatibility unless the bound methods also don't use `Vector2`

**Comment by KerekesDavid** [comment]
Bound methods should all be Vector2i, only the internals are working with Vector2.

**Review by Calinou — APPROVED** [review]
Tested locally on macOS, it works as expected. There's no more jitter in the MRP when resizing the window from any of its corners.

I think the rationale makes sense, and keeping the exposed property as-is to keep compatibility.

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -5218,12 +5218,12 @@ Size2i SubViewport::get_size() const {
...
 void SubViewport::set_size_2d_override(const Size2i &p_size) {
 	ERR_MAIN_THREAD_GUARD;
-	_set_size(_get_size(), p_size, true);
+	_set_size(_get_size(), Size2(p_size), true);
 }
 
 Size2i SubViewport::get_size_2d_override() const {
 	ERR_READ_THREAD_GUARD_V(Size2i());
-	return _get_size_2d_override();
+	return Size2i(_get_size_2d_override());
```
Comment (OhiraKyou) [inline scene/main/viewport.cpp:5226]: I'm assuming this results in float to int truncation. In my experience, setting a viewport's size from a float vector requires explicit rounding to prevent incorrect results caused by truncation. See my script [here](https://github.com/godotengine/godot/issues/77149#issuecomment-1813783014) for an example of when this was needed from gdscript to achieve correct results while scaling a viewport.

Comment (KerekesDavid) [reply scene/main/viewport.cpp:5226]: I was thinking along the lines of there's no public way to set this value to a non-integer equivalent, but you are right, it's probably better to round here just in case the engine uses the protected _set method somewhere.

Honestly I'd just want to expose this all the way through so you could set pixel-correct subviewport sizes from the user side, but changing the type of the property seems to be a comp break. Do you know if there's a way to handle this with some compatibility getter-setters or something?

If not, I've pushed a change with your suggested change and a comment.

Comment (OhiraKyou) [reply scene/main/viewport.cpp]: I haven't worked with the editor code itself. So, I can't be of much help there. That said, data serialization might complicate compatibility beyond script binding.

Incidentally, some research I've done since suggests that the round function may have some subtle quirks that can be avoided by adding half a vector and flooring instead. [This code search](https://github.com/search?q=repo%3Agodotengine%2Fgodot+is_snap_2d_transforms_to_pixel_enabled&type=code) reveals that various classes use that.

```cpp
value = (value + Vector2(0.5, 0.5)).floor();
```

Comment (KerekesDavid) [reply scene/main/viewport.cpp]: Math::round (that Vector2.round() calls internally) is also used in the window class for calculating projections, and in a bunch of other places in the code. What in particular is wring with it? Shouldn't we fix the entire function then instead of adding workarounds everywhere we want to use it?

Comment (KerekesDavid) [reply scene/main/viewport.cpp]: If it looks ok to you, would you mind approving your review?

**Comment by KerekesDavid** [comment]
I think this one is only waiting for a review and merge now :)

File: scene/main/viewport.h [hunk 2]
```diff
@@ -492,10 +492,10 @@ class Viewport : public Node {
 	void _window_start_resize(SubWindowResize p_edge, Window *p_window);
 
 protected:
-	bool _set_size(const Size2i &p_size, const Size2i &p_size_2d_override, bool p_allocated);
+	bool _set_size(const Size2i &p_size, const Size2 &p_size_2d_override, bool p_allocated);
 
 	Size2i _get_size() const;
-	Size2i _get_size_2d_override() const;
+	Size2 _get_size_2d_override() const;
```
Comment (OhiraKyou) [inline scene/main/viewport.h:498]: Suggesting reversion. The MRP is fixed without `size_2d_override` being a `Size2`.

```suggestion
	Size2i _get_size_2d_override() const;
```

File: scene/main/viewport.h [hunk 3]
```diff
@@ -252,7 +252,7 @@ class Viewport : public Node {
 	Transform2D stretch_transform;
 
 	Size2i size = Size2i(512, 512);
-	Size2i size_2d_override;
+	Size2 size_2d_override;
```
Comment (OhiraKyou) [inline scene/main/viewport.h:255]: Suggesting reversion. The MRP is fixed without `size_2d_override` being a `Size2`.

```suggestion
	Size2i size_2d_override;
```

File: scene/main/viewport.cpp [hunk 4]
```diff
@@ -5218,12 +5218,15 @@ Size2i SubViewport::get_size() const {
...
+	_set_size(_get_size(), Size2(p_size), true);
 }
 
 Size2i SubViewport::get_size_2d_override() const {
 	ERR_READ_THREAD_GUARD_V(Size2i());
-	return _get_size_2d_override();
+	// Rounding will cause offset issues with the
+	// exact positioning of subwindows, but changing the
+	// type of size_2d_override would break compatibility.
+	return Size2i((_get_size_2d_override() + Size2(0.5, 0.5)).floor());
```
Comment (OhiraKyou) [inline scene/main/viewport.cpp:5229]: Suggesting reversion. The MRP is fixed without `size_2d_override` being a `Size2`.

```suggestion
	return _get_size_2d_override();
```

**Review by OhiraKyou — CHANGES_REQUESTED** [review]
I set up a dev environment and tested the changes locally. I found that only two of the changes (plus a function signature header update) needed to be included to fix the MRP. So, my reversion suggestions are based on the assumption that this would be merged as a fix for the jitter, with any additional work being pushed to an optional future PR.

Minimum necessary changes:

- In `Window::_update_viewport_size`, `final_size_override` must be a `Size2`
	- This is because it is divided by the `content_scale_factor` on lines [1155](https://github.com/godotengine/godot/blob/6e4610640ec42271a87a27baeef7625cd3d3ad25/scene/main/window.cpp#L1155) and [1236](https://github.com/godotengine/godot/blob/6e4610640ec42271a87a27baeef7625cd3d3ad25/scene/main/window.cpp#L1236), resulting in float values that need to be preserved.
- In `Viewport::_set_size`, `p_size_2d_override` must be a `Size2` (with the redundant `Size2` conversion removed).
	- This is because `Window` passes in `final_size_override` on [line 1257](https://github.com/godotengine/godot/blob/6e4610640ec42271a87a27baeef7625cd3d3ad25/scene/main/window.cpp#L1257).

In other words, the math on `Window`'s `final_size_override` is what results in float values. Everywhere else, 2D size overrides are only given integer values. So, changing them to floats doesn't do anything without additional work.

Edit: Actually, as discussed later, because `p_size_2d_override` is saved to the `Viewport`'s `size_2d_override` in `Viewport::_set_size`, the value will be out of sync with the calculated `stretch_transform` if `size_2d_override` is not also a `Size2`.

File: scene/main/viewport.h (hunk 3 above)
Comment (KerekesDavid) [reply scene/main/viewport.h:255]: This would mean that the size_2d_override that we can get from the Viewport class, and the size_2d_override that we are actually using for that viewport does not match up anymore.

I already hate leaving the code in a state where this is not exposed to the users, but also not exposing it to engine internals just makes it worse in my opinion.

File: scene/main/viewport.cpp [hunk 5]
```diff
@@ -5218,12 +5218,15 @@ Size2i SubViewport::get_size() const {
 
 void SubViewport::set_size_2d_override(const Size2i &p_size) {
 	ERR_MAIN_THREAD_GUARD;
-	_set_size(_get_size(), p_size, true);
+	_set_size(_get_size(), Size2(p_size), true);
```
[the remark this answers is not in the document]
Comment (KerekesDavid) [reply scene/main/viewport.cpp:5221]: Fair, removed the redundant conversion.

File: scene/main/viewport.h (hunk 3 above)
Comment (OhiraKyou) [reply scene/main/viewport.h:255]: That's not quite right. The `final_size_override` that is passed to `_set_size` is a result of math (division of size by content scale) rather than explicit intent. So, there is nothing to match to or expose in the first place. And, it's the only consideration for fixing the MRP.

So, `final_size_override` and the `_set_size` function that it's passed to are the only necessary changes. Anything else is beyond the scope of fixing the MRP and can be considered in a future PR.

Comment (KerekesDavid) [reply scene/main/viewport.h:255]: No, the reason it needs to be a float is because the original assumption that size_2d_override (aka the size of the viewport in render-space) can be described as a Vector2i just doesn't hold in general. A side effect of this is the bug that we are fixing in the first place.

By changing only that one part where the bug manifests leaves the class in an inconsistent state, where certain assumptions that you would expect won't be correct anymore.

For example, stretch_transform.scale != size/size_2d_override which is a very reasonable thing to expect, that other code might depend on.

Comment (OhiraKyou) [reply scene/main/viewport.h:255]: That's a good point. `_set_size` saves the passed in override to the `Viewport`'s `size_2d_override` (truncated, if only the parameter is `Size2`) after it's used to calculate the `stretch_transform` scale. So, there would be some data loss there that is out of sync with the new `stretch_transform`.

**Review by OhiraKyou — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉

**Comment by KerekesDavid** [comment]
> Thanks! Congratulations on your first merged contribution! 🎉

Thanks, happy to help! :)
