### PR TITLE
Fix game crashes when adding color preset after clearing presets in another control

### LINKED ISSUE #104224: Game crashes when adding color preset after clearing presets in another control
### Tested versions

- Reproducible in: 4.4 (and previous 4.4.dev builds since saving color palettes was introduced #91604)

### System information

Godot v4.4.stable - Windows 11 (build 26100) - Multi-window, 1 monitor - Vulkan (Forward+) - integrated AMD Radeon 780M Graphics (Advanced Micro Devices, Inc.; 32.0.11039.8001) - AMD Ryzen 7 8845HS w/ Radeon 780M Graphics (16 threads)

### Issue description

If you have multiple `ColorPickers` in the scene and one `ColorPicker` uses saved color palette and it was cleared, trying to add color preset in another `ColorPicker`, if that color was added to the presets before, it would crash the game.

https://github.com/user-attachments/assets/1e5da6c7-255e-4d99-9793-721f06493741

### Steps to reproduce

1. Add 2 or more `ColorPicker`s to the scene
2. Assign different colors to each `ColorPicker`
3. Run the game
4. Open Swatches in each `ColorPicker` and add current color to presets
5. Save presets of one `ColorPicker` as color palette (you will see another issue mentioned in #104223)
6. Clear presets in the `ColorPicker` that you saved the palette in
7. In another `ColorPicker`  press the button to add current color to presets without chaning the color before (it should be the same color, as was added to presets for this `ColorPicker` before
8. The game should crash

### Minimal reproduction project (MRP)

[regression-test-project.zip](https://github.com/user-attachments/files/19270277/regression-test-project.zip)

### PR DESCRIPTION
**Pull request by FeniXb3**
Fixes #104224

### CODE REVIEW

File: scene/gui/color_picker.cpp [hunk 1]
```diff
@@ -1138,16 +1138,21 @@ void ColorPicker::add_preset(const Color &p_color) {
...
 	} else {
 		presets.push_back(p_color);
-		preset_cache.push_back(p_color);
 
 		_add_preset_button(_get_preset_size(), p_color);
 	}
 
+	List<Color>::Element *cache_e = preset_cache.find(p_color);
+	if (cache_e) {
+		preset_cache.move_to_back(preset_cache.find(p_color));
```
Comment (AThousandShips) [inline scene/gui/color_picker.cpp:1151]:
```suggestion
		preset_cache.move_to_back(cache_e);
```
Unnecessary to look up twice

File: core/templates/list.h [hunk 2]
```diff
@@ -564,6 +564,7 @@ class List {
 	}
 
 	void move_to_back(Element *p_I) {
+		ERR_FAIL_COND_MSG(p_I == nullptr, "The element is null");
```
Comment (AThousandShips) [inline core/templates/list.h:567]: This should probably be added to all the methods like it if any, but I think we can assume that the pointer is valid generally otherwise

Comment (FeniXb3) [reply core/templates/list.h:567]: It was crashing because null was passed here, that's why I decided to add this to make sure it will not crash but at least give some information to the user.

I agree it that it would be better to have consistency and I would be happy to add it, as it would eliminate more possible crashes like the one I experienced. Yet, I am not sure if you suggest to add it in other places or remove here, in the end. What would be better in your opinion?

Comment (AThousandShips) [reply core/templates/list.h:567]: I think to remove it and just ensure to use it safely, possibly adding it to all in a separate PR

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.4.1.
