### PR TITLE
C#: Set AppContext.BaseDirectory for editor builds

### LINKED ISSUE #72373: C#: Failed to initialize LibVLCSharp on Godot 4
### Godot version

v4.0.beta16.mono.official [518b9e580]

### System information

Windows 11, Vulkan, RTX 2060 (31.0.15.2824)

### Issue description

Only happened when I tried to use LibVLCSharp in godot 4. Used to work flawlessly in godot 3.x.x

.net version: 6.0.13

Here's the C# code:
```cs
using Godot;
using System;
using LibVLCSharp.Shared;

public partial class Testi : Control
{
	public override void _Ready()
	{
		var libvlc = new LibVLC();  // error occurred here
	}

	public override void _Process(double delta)
	{
		
	}
}
```

code above will spit out
```
E 0:00:01:0122   :0 @ System.String System.IO.Path.Combine(System.String , System.String , System.String ): System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
  <C++ Error>    System.ArgumentNullException
  <C++ Source>   :0 @ System.String System.IO.Path.Combine(System.String , System.String , System.String )
  <Stack Trace>  :0 @ System.String System.IO.Path.Combine(System.String , System.String , System.String )
                 :0 @ System.Collections.Generic.List`1[System.ValueTuple`2[System.String,System.String]] LibVLCSharp.Shared.Core.ComputeLibVLCSearchPaths()
                 :0 @ void LibVLCSharp.Shared.Core.LoadLibVLC(System.String )
                 :0 @ void LibVLCSharp.Shared.Core.InitializeDesktop(System.String )
                 :0 @ IntPtr LibVLCSharp.Shared.Helpers.MarshalUtils.CreateWithOptions(System.String[] , System.Func`3[System.Int32,System.IntPtr[],System.IntPtr] )
                 :0 @ IntPtr LibVLCSharp.Shared.LibVLC+<>c__DisplayClass8_0.<.ctor>b__0()
                 :0 @ LibVLCSharp.Shared.Internal..ctor(System.Func`1[System.IntPtr] , System.Action`1[System.IntPtr] )
                 :0 @ LibVLCSharp.Shared.LibVLC..ctor(System.String[] )
                 Testi.cs:11 @ void Testi._Ready()
                 Node.cs:1782 @ Boolean Godot.Node.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 CanvasItem.cs:1369 @ Boolean Godot.CanvasItem.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 Control.cs:2804 @ Boolean Godot.Control.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 Testi_ScriptMethods.generated.cs:31 @ Boolean Testi.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 CSharpInstanceBridge.cs:24 @ Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Call(IntPtr , Godot.NativeInterop.godot_string_name* , Godot.NativeInterop.godot_variant** , Int32 , Godot.NativeInterop.godot_variant_call_error* , Godot.NativeInterop.godot_variant* )
```

### Steps to reproduce

1. Create a new project in godot
2. Choose any kind of root node
3. Attach a C# Script to it
4. Build project to generate .csproj file
5. Navigate to project directory and install LibVLC and LibVLCSharp via ```dotnet add package``` command
6. Use LibVLCSharp inside the script like in the example above
7. Run

### Minimal reproduction project

[csproj and solution File.zip](https://github.com/godotengine/godot/files/10535756/csproj.and.solution.File.zip)

### PR DESCRIPTION
**Pull request by RedworkDE**
Set [AppContext.BaseDirectory](https://learn.microsoft.com/en-us/dotnet/api/system.appcontext.basedirectory?view=net-7.0) for editor builds. For exported projects the runtime already sets this property automatically.

This property can be used to load assemblies or native libraries at runtime.

(Often [Assembly.Location](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assembly.location?view=net-7.0) is used instead, but that cannot be set when loading assemblies from memory; cf. https://github.com/dotnet/runtime/issues/12822)

Fixes #72373 (for editor builds; the fix for exported projects is already merged)

### CODE REVIEW

**Comment by neikeq** [comment]
> Fixes (for editor builds) #72373

To clarify, the issue doesn't exist in exported games, right?

File: modules/mono/glue/GodotSharp/GodotPlugins/PluginLoadContext.cs [hunk 1]
```diff
@@ -21,6 +21,20 @@ public class PluginLoadContext : AssemblyLoadContext
             _resolver = new AssemblyDependencyResolver(pluginPath);
             _sharedAssemblies = sharedAssemblies;
             _mainLoadContext = mainLoadContext;
+
+            if (string.IsNullOrEmpty(AppContext.BaseDirectory))
+            {
+                // See https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/AppContext.AnyOS.cs#L18-L36
+                // but Assembly.Location is unavailable, because we load assemblies from memory.
+                string? baseDirectory = Path.GetDirectoryName(pluginPath);
+                if (baseDirectory != null)
```
Comment (neikeq) [inline modules/mono/glue/GodotSharp/GodotPlugins/PluginLoadContext.cs:30]: Let's print an error when this condition is false, to have context if a library cannot be loaded afterwards.

File: modules/mono/glue/GodotSharp/GodotPlugins/PluginLoadContext.cs [hunk 2]
```diff
@@ -21,6 +21,20 @@ public class PluginLoadContext : AssemblyLoadContext
...
+                {
+                    if (!Path.EndsInDirectorySeparator(baseDirectory))
+                        baseDirectory += Path.PathSeparator;
+                    // This SetData call effectively sets AppContext.BaseDirectory
+                    AppDomain.CurrentDomain.SetData("APP_CONTEXT_BASE_DIRECTORY", baseDirectory);
```
Comment (neikeq) [inline modules/mono/glue/GodotSharp/GodotPlugins/PluginLoadContext.cs:35]: Is this documented somewhere? If it's a private implementation, I'm afraid it may be changed later without warning (still be fine if there's no other way).

Comment (RedworkDE) [reply modules/mono/glue/GodotSharp/GodotPlugins/PluginLoadContext.cs:36]: As far as I can tell, it is not documented anywhere that the property can be set at all.

Well https://learn.microsoft.com/en-us/dotnet/api/system.appcontext.basedirectory?view=net-7.0#remarks points to the `BaseDirectory` property of AppDomain which is kinda implied to be able to be set as the `APPBASE` data (https://learn.microsoft.com/en-us/dotnet/api/system.appdomain.basedirectory?view=net-7.0#remarks) but that is (at least for .NET5+) not correct because it simply delegates to AppContext, which reads APP_CONTEXT_BASE_DIRECTORY. (and even on .NET framework, where setting APPBASE works, APP_CONTEXT_BASE_DIRECTORY overrides that.

The only other way to influence the BaseDirectory proeprty is to set the entry assembly (how? idk) and to set Assembly.Location (impossible without locking the assembly file)

I added a comment linking to the source of AppContext.BaseDirectory to explain the source of that constant.

File: modules/mono/glue/GodotSharp/GodotPlugins/PluginLoadContext.cs (hunk 1 above)
Comment (RedworkDE) [reply modules/mono/glue/GodotSharp/GodotPlugins/PluginLoadContext.cs:30]: I added an error, tho the else branch is effectively dead code as `pluginPath` always has a directory name and thus GetDirectoryName never actually returns null. (I only really added the if, because otherwise the compiler complains and the runtime also has it.)

File: modules/mono/glue/GodotSharp/GodotPlugins/PluginLoadContext.cs [hunk 3]
```diff
@@ -21,6 +21,26 @@ public class PluginLoadContext : AssemblyLoadContext
...
+                    if (!Path.EndsInDirectorySeparator(baseDirectory))
+                        baseDirectory += Path.PathSeparator;
+                    // This SetData call effectively sets AppContext.BaseDirectory
+                    // See https://github.com/dotnet/runtime/blob/v6.0.0/src/libraries/System.Private.CoreLib/src/System/AppContext.cs#L21-L25
+                    AppDomain.CurrentDomain.SetData("APP_CONTEXT_BASE_DIRECTORY", baseDirectory);
+                }
+                else
+                {
+                    // TODO: How to log from GodotPlugins? (delegate pointer?)
+                    Console.Error.WriteLine("Failed to set AppContext.BaseDirectory. Dynamic loading of libraries may fail.");
```
Comment (neikeq) [inline modules/mono/glue/GodotSharp/GodotPlugins/PluginLoadContext.cs:41]: Regarding the TODO, `Console.Error` is fine. It's what we currently use in `GodotPlugins/Main.cs` when an exception is caught before returning to native code.

Comment (RedworkDE) [reply modules/mono/glue/GodotSharp/GodotPlugins/PluginLoadContext.cs:41]: Yeah, thats where I copied it from, I included the TODO just so that this line doesn't get lost if someone ever implements butter logging.

**Review by neikeq — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
