### PR TITLE
Fix crash on queue free scene node in editor

### LINKED ISSUE #112171: Editor hard crashes upon loading a scene with a node using queue free
### Tested versions

Issue found in: Godot 4.5.1
Issue present from: 4.4-dev 3
Issue Present up to: 4.6-dev 2 (latest experimental build)

### System information

Godot v4.5.1.stable (f62fdbde1) - Freedesktop SDK 25.08 (Flatpak runtime) on Wayland - X11 display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XT (RADV NAVI31) - AMD Ryzen 7 5700X 8-Core Processor (16 threads) - 31.22 GiB memory

### Issue description

In my project file, no other scene other than this one crashes.
Normally i expect to load a scene and be able to use it without an issue, on this occasion the particular scene (note_splash.tscn) crashes moments after launching the scene.
So I decided to check the logs while running the editor through the terminal, and this error occurred.

```
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.5.1.stable.flathub (f62fdbde15035c5576dad93e586201f4d41ef0cb)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[1] /usr/lib/x86_64-linux-gnu/libc.so.6(+0x424f0) [0x7fe98b4434f0] (??:0)
[2] /app/bin/godot-bin(+0x1fc9894) [0x5587581fc894] (??:0)
[3] /app/bin/godot-bin(+0x2931949) [0x558758b64949] (??:0)
[4] /app/bin/godot-bin(+0x2934fb0) [0x558758b67fb0] (??:0)
[5] /app/bin/godot-bin(+0x29366db) [0x558758b696db] (??:0)
[6] /app/bin/godot-bin(+0x5a393e9) [0x55875bc6c3e9] (??:0)
[7] /app/bin/godot-bin(+0x5a3960f) [0x55875bc6c60f] (??:0)
[8] /app/bin/godot-bin(+0x7d5900) [0x558756a08900] (??:0)
[9] /app/bin/godot-bin(+0x72cfa6) [0x55875695ffa6] (??:0)
[10] /app/bin/godot-bin(+0x6ce677) [0x558756901677] (??:0)
[11] /usr/lib/x86_64-linux-gnu/libc.so.6(+0x2b975) [0x7fe98b42c975] (??:0)
[12] /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x88) [0x7fe98b42ca28] (??:0)
[13] /app/bin/godot-bin(+0x72a935) [0x55875695d935] (??:0)
-- END OF C++ BACKTRACE --
================================================================
```

### Steps to reproduce

-  Run the project file provided on the project's godot version (4.5.1) or on any version mentioned where the issue occurs
-  Go to 2D view
-  Open scenes/game/notes/note_splash.tscn

### Minimal reproduction project (MRP)

[Fazzoc-Funk-Mix_for_issue_debug.zip](https://github.com/user-attachments/files/23214613/Fazzoc-Funk-Mix_for_issue_debug.zip)

### PR DESCRIPTION
**Pull request by xuhuisheng**
- *Fixes https://github.com/godotengine/godot/issues/112171*

## Issue Description

When we try to delete scene root node using `queue_free` in editor, we will meet a crash. The marked node will be freed defer. But the editor still want to redraw relevant plugins for scene root node, then crashed.

It is an abnormal behavior to **delete** a node in editor in `@tool` annotated gdscript. If we delete a child node, we will see the child node disappeared from left `EditorTreeDock` menu. If we delete the root node, the scene cannot display normally.

```
# First, enable gdscript running in editor
@tool
extends Node2D

func _ready() -> void:
	# Second, queue free scene root node 
	queue_free()
```

## MRP

[112171-1.zip](https://github.com/user-attachments/files/23349138/112171-1.zip)

## Solution

Prohibit  `queue_clear` to delete scene root node in editor.

[queue-free.webm](https://github.com/user-attachments/assets/d05e7ce0-37b9-486d-a867-ccc5c5456f64)

### CODE REVIEW

**Review by Ivorforce — COMMENTED** [review]
We discussed this fix in the core meeting.
We agree that the approach you take (rejecting the object deletion in the editor only) is appropriate.

However, there are two changes I think are needed:

- Check for whether it's actually the editor via `Engine::get_singleton()->is_editor_hint()`. Otherwise, the runtime using the editor binary will also reject the deletion, causing a discrepancy in `DEBUG` vs `RELEASE`.
- Move this check to `node.cpp` in the `NOTIFICATION_PREDELETE` handler, right after the `is_main_thread` check. This will prevent the same kind of bug when using `.free()` and `memdelete`. You can reject deletion here using `cancel_free()` (and `return`).

**Comment by xuhuisheng** [comment]
@Ivorforce

Modified as suggestions.
Test passed locally.

File: scene/main/node.cpp [hunk 1]
```diff
@@ -279,7 +279,13 @@ void Node::_notification(int p_notification) {
 				ERR_PRINT("Attempted to free a node that is currently added to the SceneTree from a thread. This is not permitted, use queue_free() instead. Node has not been freed.");
 				return;
 			}
-
+#ifdef TOOLS_ENABLED
+			if (Engine::get_singleton()->is_editor_hint() && data.tree && this == data.tree->get_edited_scene_root()) {
+				cancel_free();
+				ERR_PRINT("Can't queue free scene root in editor.");
```
Comment (Ivorforce) [inline scene/main/node.cpp]:
```suggestion
				ERR_PRINT(vformat("Something attempted to free the root Node of a scene ("%s"). This is not supported inside the editor, so the Node was not freed.", get_name()));
```

**Review by Ivorforce — APPROVED** [review]
Looks good to me, thanks for adjusting.

I tested that this new version still fixes the issue.

File: scene/main/node.cpp [hunk 2]
```diff
@@ -279,7 +279,13 @@ void Node::_notification(int p_notification) {
 				ERR_PRINT("Attempted to free a node that is currently added to the SceneTree from a thread. This is not permitted, use queue_free() instead. Node has not been freed.");
 				return;
 			}
-
+#ifdef TOOLS_ENABLED
+			if (Engine::get_singleton()->is_editor_hint() && data.tree && this == data.tree->get_edited_scene_root()) {
+				cancel_free();
+				ERR_PRINT(vformat("Something attempted to free the root Node of a scene ("%s"). This is not supported inside the editor, so the Node was not freed.", get_name()));
```
Comment (AThousandShips) [inline scene/main/node.cpp]:
```suggestion
				ERR_PRINT(vformat("Something attempted to free the root Node of a scene (\"%s\"). This is not supported inside the editor, so the Node was not freed.", get_name()));
```

File: scene/main/node.cpp [hunk 3]
```diff
@@ -279,7 +279,13 @@ void Node::_notification(int p_notification) {
 				ERR_PRINT("Attempted to free a node that is currently added to the SceneTree from a thread. This is not permitted, use queue_free() instead. Node has not been freed.");
 				return;
 			}
-
+#ifdef TOOLS_ENABLED
+			if (Engine::get_singleton()->is_editor_hint() && data.tree && this == data.tree->get_edited_scene_root()) {
+				cancel_free();
+				ERR_PRINT(vformat("Something attempted to free the root Node of a scene (\"%s\"). This is not supported inside the editor, so the Node was not freed.", get_name()));
+				return;
```
Comment (AThousandShips) [inline scene/main/node.cpp:286]:
```suggestion
				ERR_FAIL_MSG(vformat("Something attempted to free the root Node of a scene (\"%s\"). This is not supported inside the editor, so the Node was not freed.", get_name()));
```
My bad missed this part too

**Review by AThousandShips — APPROVED** [review]

**Comment by kleonc** [comment]
Fixes both #66196 and #68544 which are both reported for `3.x`. After migrating the MRPs to `4.x` they no longer crash with this PR. Not sure if we want to keep the issues open for `3.x` or what.

Fixes #81320 (makes it spam errors instead of crashing as it tries to free the scene root in `_process()`).

**Comment by Ivorforce** [comment]
cc @lawnjelly  ^

**Comment by lawnjelly** [comment]
> Not sure if we want to keep the issues open for 3.x or what.

Generally the method I'm aiming for is this:

* If a bug is open against 3.x and it gets fixed in 4.x but not in 3.x, the bug is still open in 3.x (sadly fixing it in 4.x doesn't magically fix it in 3.x! :grin: )
* If a bug report in 3.x has been "kidnapped" to 4.x, and is fixed in 4.x but not in 3.x, we should aim to change the milestone back to 3.x

In this case though, this fix looks fairly easy to backport, if we've decided this is the best way of addressing it. :+1:

**Comment by Repiteo** [comment]
Thanks!

**Comment by SysError99** [comment]
>  Not sure if we want to keep the issues open for `3.x` or what.

While the reproduction is indeed made with 3.5.3 (which is the version I've been actively using), the issue itself does not specifically mention `3.x` branch and also does apply up to the `master` before it gets patched. I'd say it's fair to close it since the current, actively developed, is `4.x`. I could probably open the issue again for the `3.x` but this is fairly easy to port, might as well skip the issue-opening completely and just do the backport directly.
