### PR TITLE
Fix container minimum size with hidden parent

### LINKED ISSUE #93464: Containers do not correctly resize to their contents when their visibility is toggled
### Tested versions

- Reproducible in: v4.3.beta2.official [b75f0485b] and earlier betas
- Not Reproducible in: v4.2.2.stable.official [15073afe3] and earlier 4.2

### System information

Windows 11 - Forward +

### Issue description

Containers will correctly resize to fit their contents when in the editor and the first time they are made visible while the application is running.  However, if the container is hidden, and then shown again, the container will shrink and not resize properly when shown again.  This is easiest to see with panel containers.
image
image
image

### Steps to reproduce

1. Create a control scene and add a script to this node
2. Add a panel container, a grid container as a child, and buttons as children to the grid container
3. Add a button as the child of the root control node, link its pressed signal to the root script
4. Have the button's signal turn the panel container's visibility on and off
5. Observe that the panel container does not consider its child contents when it determines its size after being shown again

### Minimal reproduction project (MRP)

[container-visibility.zip](https://github.com/user-attachments/files/15936382/container-visibility.zip)

### PR DESCRIPTION
**Pull request by anniryynanen**
Fixes #93464.

MRP for testing the changed containers: [container-visibility.zip](https://github.com/user-attachments/files/16131760/container-visibility.zip)

The minimum size bug can be a bit fickle to reproduce. In the above MRP, if you change the position of a panel by 1 px it stops reproducing until the inner ColorRect's size is reset, the panel's size is reset, and the ColorRect's size is set again.

Graphs and TabContainer use `SortableVisbilityMode::IGNORE`, I didn't change that as they seem like special cases.

### CODE REVIEW

**Comment by anniryynanen** [comment]
EditorInspector also uses `as_sortable_control()` in `get_minimum_size()` for EditorProperty and EditorInspectorSection. I didn't add `SortableVisbilityMode::VISIBLE` there as I'm not sure if the bug reproduces there, or how I'd go about testing it.

File: scene/gui/split_container.cpp [hunk 1]
```diff
@@ -258,7 +258,7 @@ Size2 SplitContainer::get_minimum_size() const {
 	int sep = (dragger_visibility != DRAGGER_HIDDEN_COLLAPSED) ? MAX(theme_cache.separation, vertical ? g->get_height() : g->get_width()) : 0;
 
 	for (int i = 0; i < 2; i++) {
-		if (!_get_sortable_child(i)) {
+		if (!_get_sortable_child(i, SortableVisbilityMode::VISIBLE)) {
```
Comment (KoBeWi) [inline scene/gui/split_container.cpp:261]: It would be nice if this Control was assigned to a variable instead of calling the method again below.

**Review by KoBeWi — APPROVED** [review]
Half of the containers already use VISIBLE mode, so this makes sense.

**Comment by akien-mga** [comment]
Thanks!
