### PR TITLE
[GraphEdit] Make connections a property

### LINKED ISSUE #97015: GraphEdit packedScene serialization issue on MenuHbox and connection_lines
[new-game-project.zip](https://github.com/user-attachments/files/17005084/new-game-project.zip)
### Tested versions

-Reproducable on Godot 4.3.stable

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 Ti (NVIDIA; 32.0.15.6094) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 Threads)

### Issue description

When using a ResourceSaver to save a scene including a GraphEdit, nodes that you reparent to the menu_box as well as all connection_lines are not saved

### Steps to reproduce

1. Create a GraphEdit

2.
```
var node = Button.new()
node.reparent(get_menu_hbox())
```

2.b. As for the connection_lines, just create 2 GraphNodes and connect them
4.
```
self.pack(instance)
ResourceSaver.save(self, "test.tscn")
```

5. open test.tscn in text editor and notice missing button and connection lines

### Minimal reproduction project (MRP)

[new-game-project.zip](https://github.com/user-attachments/files/17005084/new-game-project.zip)

### PR DESCRIPTION
**Pull request by Geometror**
Fixes #97015
After investigating the issue above, I found no obvious reasons why connections shouldn't be a property.

**Main changes:**
- The connections array is now a property and can be modified via the inspector (although that is a bit finicky due to the fact that dead/invalid connections are removed after each update, so can't add connections right now through the inspector). This means connections are now properly serialized/deserialized.

**Additional refactoring/optimization:**
- Use `Vector` instead of `List` internally for connections (this also removes unreadable list element access, e.g. E->get()->...)
- Make names of local variables of type `Ref<Connection>` consistent (`c` -> `conn`)
- Method declaration order

Note: In order to avoid breaking compatibility, I kept the name `get_connection_list` (just for scripting), but since this name is kind of weird and GraphEdit is still experimental we could change it for consistency.

### CODE REVIEW

**Comment by KoBeWi** [comment]
> Use Vector instead of List internally for connections (this also removes unreadable list element access, e.g. E->get()->...)

You can get rid of `E->get()` in list too, List supports the same iteration as Vector.
If the `connections` are local GraphEdit (i.e. not passed anywhere), you can use LocalVector.

**Comment by KoBeWi** [comment]
Editing connections in the inspector is quite buggy. I think the property should either be hidden or readonly.

File: scene/gui/graph_edit.cpp [hunk 1]
```diff
@@ -313,12 +313,12 @@ bool GraphEdit::is_node_connected(const StringName &p_from, int p_from_port, con
...
-			connection_map[p_from].erase(E->get());
-			connection_map[p_to].erase(E->get());
-			E->get()->_cache.line->queue_free();
-			connections.erase(E);
+	for (const Ref<Connection> &conn : connections) {
+		if (conn->from_node == p_from && conn->from_port == p_from_port && conn->to_node == p_to && conn->to_port == p_to_port) {
+			connection_map[p_from].erase(conn);
+			connection_map[p_to].erase(conn);
+			conn->_cache.line->queue_free();
+			connections.erase(conn);
```
Comment (KoBeWi) [inline scene/gui/graph_edit.cpp:321]: You are erasing a connection from the vector you are iterating. It seems to work correctly though, not sure how 🤔

File: scene/gui/graph_edit.cpp [hunk 2]
```diff
@@ -1334,47 +1334,45 @@ void GraphEdit::_draw_minimap_connection_line(const Vector2 &p_from_graph_positi
 
 void GraphEdit::_update_connections() {
 	// Collect all dead connections and remove them.
-	List<List<Ref<Connection>>::Element *> dead_connections;
+	Vector<Ref<Connection>> dead_connections;
```
Comment (KoBeWi) [inline scene/gui/graph_edit.cpp:1337]:
```suggestion
	LocalVector<Ref<Connection>> dead_connections;
```

File: scene/gui/graph_edit.cpp [hunk 3]
```diff
@@ -2211,8 +2209,16 @@ void GraphEdit::remove_valid_left_disconnect_type(int p_type) {
 	valid_left_disconnect_types.erase(p_type);
 }
 
+void GraphEdit::set_connections(const TypedArray<Dictionary> &p_connections) {
+	clear_connections();
+
+	for (const Dictionary d : p_connections) {
```
Comment (KoBeWi) [inline scene/gui/graph_edit.cpp:2215]:
```suggestion
	for (const Dictionary &d : p_connections) {
```
Though it might not work with TypedArray (in which case leave it as is).

Comment (AThousandShips) [reply scene/gui/graph_edit.cpp:2215]: It doesn't as far as I recall implementing it, binding to a cast breaks

File: scene/gui/graph_edit.cpp (hunk 1 above)
Comment (Geometror) [reply scene/gui/graph_edit.cpp:321]: No, I'm iterating over `dead_connections` and erase each dead connection in `connections`.

Comment (KoBeWi) [reply scene/gui/graph_edit.cpp:321]: Am I missing something?
image
`dead_connections` don't exist in this method.

Comment (Geometror) [reply scene/gui/graph_edit.cpp:321]: Oh, sorry, I was looking at the wrong piece of code (which is almost identical)😅

Comment (Geometror) [reply scene/gui/graph_edit.cpp:321]: It's fine here since after the first matching connection is found, that connection gets erased and the function returns.
However, I was puzzled as well until I found the return statement, so rewriting the code like this makes it more readable I think:
```cpp
void GraphEdit::disconnect_node(const StringName &p_from, int p_from_port, const StringName &p_to, int p_to_port) {
	ERR_FAIL_NULL_MSG(connections_layer, "connections_layer is missing.");

	Ref<Connection> conn_to_remove;
	for (const Ref<Connection> &conn : connections) {
		if (conn->from_node == p_from && conn->from_port == p_from_port && conn->to_node == p_to && conn->to_port == p_to_port) {
			conn_to_remove = conn;
		}
	}

	if (conn_to_remove.is_valid()) {
		connection_map[p_from].erase(conn_to_remove);
		connection_map[p_to].erase(conn_to_remove);
		conn_to_remove->_cache.line->queue_free();
		connections.erase(conn_to_remove);

		minimap->queue_redraw();
		queue_redraw();
		connections_layer->queue_redraw();
		callable_mp(this, &GraphEdit::_update_top_connection_layer).call_deferred();
	}
}
```

Comment (KoBeWi) [reply scene/gui/graph_edit.cpp:321]: Ah I also missed the return. It was outside the modified code, so it didn't show.
The new code looks fine, but it's missing a `break`.

Comment (Geometror) [reply scene/gui/graph_edit.cpp:321]: Alright, well, this reminds me that I shouldn't code with a flu :)

File: scene/gui/graph_edit.cpp (hunk 3 above)
Comment (Geometror) [reply scene/gui/graph_edit.cpp:2262]: Although MSVC does not complain, other compilers do:
```
scene/gui/graph_edit.cpp:2262:25: error: loop variable 'd' of type 'const Dictionary &' binds to a temporary constructed from type 'const Variant &' [-Werror,-Wrange-loop-construct]
        for (const Dictionary &d : p_connections) {
                               ^
scene/gui/graph_edit.cpp:2262:7: note: use non-reference type 'Dictionary' to make construction explicit or type 'const Variant &' to prevent copying
        for (const Dictionary &d : p_connections) {
             ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by Geometror** [comment]
Fixed the editing in the inspector via implementing a new connection "property": `keep_alive`. 
Connections which have `keep_alive` set to `true` won't get automatically deleted during redrawing even if they are invalid. This should also be useful in other cases. 
Ideally, I would like to wait with this PR until we have structs as part of the API, but if that happens, we'd need to break compat all over the place (or have another solution at hand) so I guess it doesn't matter. Even with a array of dicts, the editing of connections feels quite nice.

File: doc/classes/GraphEdit.xml [hunk 4]
```diff
@@ -172,7 +174,7 @@
 			<param index="1" name="max_distance" type="float" default="4.0" />
 			<description>
 				Returns the closest connection to the given point in screen space. If no connection is found within [param max_distance] pixels, an empty [Dictionary] is returned.
-				A connection consists in a structure of the form [code]{ from_port: 0, from_node: "GraphNode name 0", to_port: 1, to_node: "GraphNode name 1" }[/code].
+				A connection consists in a structure of the form [code]{ from_port: 0, from_node: "GraphNode name 0", to_port: 1, to_node: "GraphNode name 1", keep_alive: true/false }[/code].
```
Comment (KoBeWi) [inline doc/classes/GraphEdit.xml:177]: Why did you write specific example values for ports and nodes, but `true/false` for alive?

File: doc/classes/GraphEdit.xml [hunk 5]
```diff
@@ -130,8 +130,10 @@
 			<param index="1" name="from_port" type="int" />
 			<param index="2" name="to_node" type="StringName" />
 			<param index="3" name="to_port" type="int" />
+			<param index="4" name="keep_alive" type="bool" default="false" />
 			<description>
 				Create a connection between the [param from_port] of the [param from_node] [GraphNode] and the [param to_port] of the [param to_node] [GraphNode]. If the connection already exists, no connection is created.
+				Connections with [param keep_alive] set to [code]true[/code] are not automatically deleted if invalid during a redraw.
```
Comment (KoBeWi) [inline doc/classes/GraphEdit.xml:136]: I'd reverse this and say that connections with `keep_alive` false may be deleted at redraw if invalid.

**Review by KoBeWi — APPROVED** [review]

File: doc/classes/GraphEdit.xml [hunk 6]
```diff
@@ -288,6 +299,18 @@
...
+		<member name="connections" type="Dictionary[]" setter="set_connections" getter="get_connection_list" default="[]">
+			The connections between [GraphNode]s.
+			A connection is a [Dictionary] in the form of 
+			[codeblock]{ 
+			    from_node: StringName,
+			    from_port: int,
+			    to_node: StringName,
+			    to_port: int,
+			    keep_alive: bool
+			}[/codeblock]
```
Comment (Mickeon) [inline doc/classes/GraphEdit.xml:311]: Same goes for the others
```suggestion
			[codeblock]
			{ 
			    from_node: StringName,
			    from_port: int,
			    to_node: StringName,
			    to_port: int,
			    keep_alive: bool
			}
			[/codeblock]
```

File: doc/classes/GraphEdit.xml [hunk 7]
```diff
@@ -288,6 +299,18 @@
 		<member name="connection_lines_thickness" type="float" setter="set_connection_lines_thickness" getter="get_connection_lines_thickness" default="4.0">
 			The thickness of the lines between the nodes.
 		</member>
+		<member name="connections" type="Dictionary[]" setter="set_connections" getter="get_connection_list" default="[]">
+			The connections between [GraphNode]s.
+			A connection is a [Dictionary] in the form of
```
Comment (Mickeon) [inline doc/classes/GraphEdit.xml:304]: Apply similarly to the others.
```suggestion
			The connections between [GraphNode]s. A connection is represented as a [Dictionary] in the form of:
```

**Comment by Geometror** [comment]
Rebased.

**Comment by Repiteo** [comment]
Thanks!

**Comment by Zylann** [comment]
```diff
-const List<Ref<GraphEdit::Connection>> &GraphEdit::get_connection_list() const {
+const Vector<Ref<GraphEdit::Connection>> &GraphEdit::get_connections() const {
```
Is there a reason this was renamed? This is not renamed in the scripting API, but my module uses it, so it kind of breaks compatibility, in addition to making names different between extensions and core (which we try to keep matching with PRs such as https://github.com/godotengine/godot/pull/98132).

**Comment by Geometror** [comment]
@Zylann I guess we can rename it in the scripting API as GraphEdit is still experimental. What do you think?

**Comment by Zylann** [comment]
If it's ok to break compat, then that would make sense.
