### PR TITLE
Fix deleting selection at the first line do not work with backspace

### LINKED ISSUE #53274: [Godot 4] backspace shortcut doesnt work at `Line 1` when selected
### Godot version

Godot Engine v4.0.dev.custom_build (2d08457f58c21c858923a546a4f29b99640ff800)

### System information

manjaro 21, AMD Radeon r7 200 series, Vulkan, 8GB Memory

### Issue description

Peek 2021-09-30 19-06

As you can see in the gif above, when I select a word in `line 1` it doesnt get deleted when pressing backspace
only if I delete one by one letter.

### Steps to reproduce

* Create a script
* Type anything in line 1
* Select and press backspace
* shouldnt work

### Minimal reproduction project

N/a

### PR DESCRIPTION
**Pull request by jmb462**
Fixes #53274

### Issue

When hitting backspace, the ``_backspace_internal()`` function directly returns if carret was at position 0,0 even if there was a selected text. So the key had no effect in that case.

### Fix proposal

Swap the order of the tests.
Delete selection before testing the carret position.

### Before

135536491-eea4ff6f-50d4-4cf4-a68f-045d5a3bd718

### After

backspace

### CODE REVIEW

File: scene/gui/code_edit.cpp [hunk 1]
```diff
@@ -617,12 +617,12 @@ void CodeEdit::_backspace_internal() {
 	int cc = get_caret_column();
 	int cl = get_caret_line();
 
-	if (cc == 0 && cl == 0) {
+	if (has_selection()) {
+		delete_selection();
 		return;
 	}
```
Comment (Paulb23) [inline scene/gui/code_edit.cpp:623]: Can you move this above line `617` to align with `TextEdit`.

**Review by Paulb23 — CHANGES_REQUESTED** [review]
Looks good, small change commented inline.

Also any chance you can add unit tests for this?

**Comment by jmb462** [comment]
> Looks good, small change commented inline.
> 
> Also any chance you can add unit tests for this?

As I never done that for godot before, I will try to learn this weekend how unit tests work in Godot project and add some relaled to this issue.

**Comment by KoBeWi** [comment]
Adding tests isn't that difficult actually, you can just copy-paste some other test from `tests/test_code_edit.h` and change to your case. Here's info how to compile it: https://docs.godotengine.org/en/latest/development/cpp/unit_testing.html

**Comment by jmb462** [comment]
I've added some test about backspace deletion.
One of them was failing before the fix of this PR.
All tests are now passing correctly.

**Review by Paulb23 — APPROVED** [review]
Good test coverage, LGTM.

**Comment by akien-mga** [comment]
Thanks!
