### PR TITLE
Fix crash when opening a TileSet with invalid tiles

### LINKED ISSUE #77673: Invalid tiles in a TileSet causes Godot to crash
### Godot version

v4.0.3.stable.mono.official [5222a99f5]

### System information

Ubuntu 22.04 LTS

### Issue description

This issue is similar to #61296, but instead of being spammed with errors Godot simply crashes when loading the tileset

I've tried to edit the .tres file to remove the invalid tiles, but the crash still happens.

### Steps to reproduce

- Open the reproduction project in the Godot editor;
- Try to open the Terrain.tres file.

After doing so Godot should crash with the following output:
```shell
Godot Engine v4.0.3.stable.mono.official.5222a99f5 - https://godotengine.org
Vulkan API 1.3.224 - Forward+ - Using Vulkan Device #0: Intel - Intel(R) HD Graphics 5500 (BDW GT2)
 
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:70)
ERROR: The TileSetAtlasSource atlas has no tile at (1, 35).
   at: get_tile_data (scene/resources/tile_set.cpp:4515)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.3.stable.mono.official (5222a99f5d38cd5346254cefed8f65315bca4fcb)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.16/libcoreclr.so(+0x4b674e) [0x7f13c0ddb74e] (??:0)
[2] /usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.16/libcoreclr.so(+0x4b5cd7) [0x7f13c0ddacd7] (??:0)
[3] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f13e49d3520] (??:0)
[4] godot() [0x27187bb] (??:0)
[5] godot() [0x427f8d5] (??:0)
[6] godot() [0x4e6bfa0] (??:0)
[7] /lib/x86_64-linux-gnu/libc.so.6(+0x94b43) [0x7f13e4a25b43] (??:0)
[8] /lib/x86_64-linux-gnu/libc.so.6(+0x126a00) [0x7f13e4ab7a00] (??:0)
-- END OF BACKTRACE --
================================================================
Aborted (core dumped)
```

### Minimal reproduction project

[reproduction-project.zip](https://github.com/godotengine/godot/files/11605655/reproduction-project.zip)

### PR DESCRIPTION
**Pull request by timothyqiu**
Fixes #77673

`get_tile_data()` returns null for invalid identifiers so a check is needed. Checks `has_tile()` and `has_alternative_tile()` first so that `get_tile_data()` won't print errors.

### CODE REVIEW

File: editor/plugins/tiles/tiles_editor_plugin.cpp [hunk 1]
```diff
@@ -108,7 +108,11 @@ void TilesEditorPlugin::_thread() {
 						Vector2i coords = tile_map->get_cell_atlas_coords(0, cell);
 						int alternative = tile_map->get_cell_alternative_tile(0, cell);
 
-						Vector2 center = world_pos - atlas_source->get_tile_data(coords, alternative)->get_texture_origin();
+						Vector2 center = world_pos;
+						if (atlas_source->has_tile(coords) && atlas_source->has_alternative_tile(coords, alternative)) {
+							center -= atlas_source->get_tile_data(coords, alternative)->get_texture_origin();
+						}
+
```
Comment (groud) [inline editor/plugins/tiles/tiles_editor_plugin.cpp:115]: The check should be expanded to the following two lines, otherwise they will spit errors in `get_tile_texture_region`

**Review by groud — CHANGES_REQUESTED** [review]

**Review by groud — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.4.
