### PR TITLE
Fixes Hint label in 2D editor appearing at wrong position

### LINKED ISSUE #57253: Hint label in 2D editor appears at wrong position and pushes zoom controls
### Godot version

1894f3f

### System information

W10

### Issue description

godot windows tools 64_IjMdMcNjru

In 3.x
godot windows opt tools 64_mTBtxwMTvC

### Steps to reproduce

1. Drag Texture to 2D editor

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by emcguirk**
This fixes Issue #57253 by moving the zoom_widget node to position 0 in controls_vb

sprite_drag_fix

*Bugsquad edit:*
- Fixes #57253

### CODE REVIEW

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -5213,6 +5213,7 @@ CanvasItemEditor::CanvasItemEditor(EditorNode *p_editor) {
 
 	zoom_widget = memnew(EditorZoomWidget);
 	controls_vb->add_child(zoom_widget);
+	controls_vb->move_child(zoom_widget, 0);
```
Comment (akien-mga) [inline editor/plugins/canvas_item_editor_plugin.cpp:5216]: That's a bit surprising, what children are present in `controls_vb` before this one? `controls_vb` is created on line 5186 and I don't see any other `controls_vb->add_child()` call before this one.

Comment (KoBeWi) [reply editor/plugins/canvas_item_editor_plugin.cpp:5216]: Other child nodes are added in CanvasItemEditorViewport constructor, which is created before this line. They use `get_controls_container()->add_child()`.

Maybe instead of using `move_child()`, it would be better to move the zoom widget creation before that? It could happen right after `controls_vb` is created.

Comment (akien-mga) [reply editor/plugins/canvas_item_editor_plugin.cpp:5216]: Thanks, that makes sense. Then yeah this code should be moved to right after:
```
	controls_vb = memnew(VBoxContainer);
	controls_vb->set_begin(Point2(5, 5));
```
And the `move_child` wouldn't be needed.

Comment (emcguirk) [reply editor/plugins/canvas_item_editor_plugin.cpp]: I've moved the `zoom_widget` constructor to immediately after the `controls_vb` constructor and removed the call to `move_child`

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 2]
```diff
@@ -5185,6 +5185,10 @@ CanvasItemEditor::CanvasItemEditor(EditorNode *p_editor) {
 
 	controls_vb = memnew(VBoxContainer);
 	controls_vb->set_begin(Point2(5, 5));
+	zoom_widget = memnew(EditorZoomWidget);
+	controls_vb->add_child(zoom_widget);
+	zoom_widget->set_anchors_and_offsets_preset(Control::PRESET_TOP_LEFT, Control::PRESET_MODE_MINSIZE, 2 * EDSCALE);
+	zoom_widget->connect("zoom_changed", callable_mp(this, &CanvasItemEditor::_update_zoom));
```
Comment (akien-mga) [inline editor/plugins/canvas_item_editor_plugin.cpp:5191]:
```suggestion
	controls_vb = memnew(VBoxContainer);
	controls_vb->set_begin(Point2(5, 5));

	zoom_widget = memnew(EditorZoomWidget);
	controls_vb->add_child(zoom_widget);
	zoom_widget->set_anchors_and_offsets_preset(Control::PRESET_TOP_LEFT, Control::PRESET_MODE_MINSIZE, 2 * EDSCALE);
	zoom_widget->connect("zoom_changed", callable_mp(this, &CanvasItemEditor::_update_zoom));
```
It's more readable this way, otherwise it's good.

**Review by akien-mga — APPROVED** [review]

**Review by KoBeWi — APPROVED** [review]
You need to [squash the commits](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html?#the-interactive-rebase).

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
