### PR TITLE
Fix/restore BackBufferCopy

### LINKED ISSUE #56873: SCREEN_TEXTURE is not being updated for subsequent shaders even when BackBufferCopy is used for each of them
### Godot version

master (8958e1b35297baa8ef4f9e03bb4ad105500e3a0c)

### System information

Windows 10, GTX1080Ti (511.23), Vulkan

### Issue description

`SCREEN_TEXTURE` is not being updated for subsequent shaders even when `BackBufferCopy` is used for each of them. In other words, the first captured buffer is always returned when multiple shaders (each `BackBufferCopy`-parented) exist as siblings.

If I understand correctly, on 2D, backbuffer is fetched only once when `SCREEN_TEXTURE` appears for the first time. However, when `BackBufferCopy` is used, backbuffer should be copied every time.

Quoting Godot Contributors Chat [(link)](https://chat.godotengine.org/channel/rendering?msg=ikoPZjBQGRv5EXkRT):
> **&lt;mux213&gt;** saki7: if I recall correctly the back buffer copy is only executed once per frame, right before the very first shader that requires SCREEN_TEXTURE is run. Could that be your issues?
>
> **&lt;reduz&gt;** mux213: for 2D its a bit more fine grained
> for 3D it only does once before drawing transparent objects

| **Expected Result** | **Actual Result** |
|---|---|
| godot_test_expected | godot_test_actual |

#### Shader
```glsl
shader_type canvas_item;

void fragment() {
    vec3 c = texture(SCREEN_TEXTURE, SCREEN_UV).rgb;
    COLOR = vec4(c * 0.7, 1.0);
}
```

### Scene Tree
- PanelContainer
  - BackBufferCopy
    - Sprite2D (icon.png)
  - BackBufferCopy
    - Sprite2D (arbitrary image + shader with `SCREEN_TEXTURE`)
  - BackBufferCopy
    - Sprite2D (arbitrary image + shader with `SCREEN_TEXTURE`)

### Steps
1. Clone `master`, build it, run it
2. Setup a scene tree like above
3. Run the scene
4. You will see the "Actual Result" I posted above
5. On editor's FileSystem panel, click on the `.gdshader` file which is attached to your node
6. You will see multiple errors like below

This one is tracked in #56511:
```
ERROR: Height must be equal or greater than 1 for 2D and 3D textures
   at: (drivers/vulkan/rendering_device_vulkan.cpp:1756)
```

Other errors related to images, uniforms and textures:
(See #50296 for similar reports)
```
ERROR: Image (binding: 0, index 0) is not a valid texture.
   at: (drivers/vulkan/rendering_device_vulkan.cpp:5712)
ERROR: Condition "!uniform_set" is true.
   at: compute_list_bind_uniform_set (drivers/vulkan/rendering_device_vulkan.cpp:7888)
ERROR: Uniforms were never supplied for set (3) at the time of drawing, which are required by the pipeline
   at: (drivers/vulkan/rendering_device_vulkan.cpp:8087)
ERROR: Texture (binding: 0, index 0) is not a valid texture.
   at: (drivers/vulkan/rendering_device_vulkan.cpp:5604)
ERROR: Condition "!uniform_set" is true.
   at: compute_list_bind_uniform_set (drivers/vulkan/rendering_device_vulkan.cpp:7888)
...
... (repeated infinitely)
...
```

7. Choose _**one**_ PR from below, apply it on master, rebuild godot
  **Warning: These are three independent approaches to fix the similar errors, and we only need ONE of them to fix the errors here. That's for you to decide.**
  7-a. #52528 (note that you need to resolve git conflict manually as of current master)
  7-b. #54370
  7-c. #54489 
8. Run the scene again
9. All errors disappear
10. You will still be seeing the "Actual Result", not the "Expected Result"

## Minimal reproduction project

n/a

## Workaround
```diff
--- a/servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp
+++ b/servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp
@@ -1365,7 +1365,7 @@ void RendererCanvasRenderRD::canvas_render_items(RID p_to_render_target, Item *p
                        MaterialData *md = (MaterialData *)storage->material_get_data(material, RendererStorageRD::SHADER_TYPE_2D);
                        if (md && md->shader_data->valid) {
                                if (md->shader_data->uses_screen_texture && canvas_group_owner == nullptr) {
-                                       if (!material_screen_texture_found) {
+                                       if (true || !material_screen_texture_found) { // FIXME: Workaround BackBufferCopy not being refreshed
                                                backbuffer_copy = true;
                                                back_buffer_rect = Rect2();
                                        }
```

By applying this workaround, you will see the "Expected Result".

**Note:** This workaround force-updates all backbuffer when `SCREEN_TEXTURE` is used in a shader, regardless of the existence of `BackBufferCopy`. It will destroy the concept of caching `SCREEN_TEXTURE` in the first place, so this patch should not be used in a production build.

## Related Issues
#50296
#52505
#47504 -- This was the most similar issue, but it was on 3.x branch, and it was correctly resolved by using `BackBufferCopy` for each shader nodes. My issue, however, is on 4.x branch, and it can not be resolved by same approach.

## Other stuff that might be affected
The [Screen-reading shaders example on official documentation](https://docs.godotengine.org/en/latest/tutorials/shaders/screen-reading_shaders.html) will not work until this issue is fixed.

### PR DESCRIPTION
**Pull request by Geometror**
Detailed changes:
- Restores the functionality of BackBufferCopy, which has been broken since Vulkan was introduced
	- Like in 3.x, mipmaps are always generated
- Rename a variable to better reflect what it does

Fixes #56873.

fix2

### CODE REVIEW

File: servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp [hunk 1]
```diff
@@ -1379,7 +1379,7 @@ void RendererCanvasRenderRD::canvas_render_items(RID p_to_render_target, Item *p
 	while (ci) {
 		if (ci->copy_back_buffer && canvas_group_owner == nullptr) {
 			backbuffer_copy = true;
-
+			backbuffer_gen_mipmaps = true;
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:1382]: The backbuffer should only generate mipmaps if they will actually be used.

**Review by clayjohn — COMMENTED** [review]
Looks mostly fine. If you end up making changes in ``renderer_canvas_render_rd.cpp`` then you should make the equivalent changes in GLES3 as well. However, as my comment says below, I don't think generating mipmaps should be forced on by default. They should only be on if they will be used.

**Comment by akien-mga** [comment]
Does this address https://github.com/godotengine/godot/issues/56873?

File: servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp (hunk 1 above)
Comment (Geometror) [reply servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:1382]: With a CanvasItem that has a screen-reading shader you can determine whether mipmaps should be generated (via `shader_data->uses_screen_texture_mipmaps`). I might be wrong, but the problem in this case is that with a `BackBufferCopy` node you can't know if a CanvasItem uses the mipmaps later with our current canvas renderer implementation. If we want control over that we would need a `generate_mipmaps` property, so for now I just enabled it by default since that's what is done in 3.x.

**Comment by Geometror** [comment]
Made the equivalent changes in GLES3.

File: servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp (hunk 1 above)
Comment (clayjohn) [reply servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:1382]: Ah, yes, I see the issue, in other cases we are only really checking if the immediate next canvas item uses mipmaps. So when doing the backbuffercopy we don't know whether mipmaps are needed at the time we do the copy. 

What we should do then is have another condition to check, something like:
```
if (material_screen_texture_cached && !mipmaps_generated && uses_mipmaps) {
    // generate mipmaps
}
```

So at the time of doing the copy, you just generate the base texture (unless you already know you need mipmaps), then once you need mipmaps you generate them. 

I really want to avoid always generating mipmaps. We did it in 3.x, but it introduced a lot of performance overhead and was an issue for a lot of projects.

Comment (Geometror) [reply servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp]: Ok, I implemented your suggestion and tested it.
However, there is an issue which needs to be addressed for this to be effective (maybe in a subsequent PR):
The ShaderCompiler seems to set uses_screen_texture_mipmaps whenever SCREEN_TEXTURE is used, not just when it's used together with textureLod (level > 0). Because of this, the mipmaps are always generated, even with the new logic. Not sure how to solve this elegantly.

**Review by clayjohn — APPROVED** [review]
Looks great! Thank you for updating so quickly.

**Comment by akien-mga** [comment]
Thanks!

File: drivers/gles3/rasterizer_canvas_gles3.cpp [hunk 2]
```diff
@@ -287,7 +290,16 @@ void RasterizerCanvasGLES3::canvas_render_items(RID p_to_render_target, Item *p_
 			texture_storage->render_target_copy_to_back_buffer(p_to_render_target, back_buffer_rect, backbuffer_gen_mipmaps);
 
 			backbuffer_copy = false;
-			material_screen_texture_found = true; //after a backbuffer copy, screen texture makes no further copies
+			backbuffer_gen_mipmaps = false;
+			material_screen_texture_cached = true; // After a backbuffer copy, screen texture makes no further copies.
+			material_screen_texture_mipmaps_cached = backbuffer_gen_mipmaps;
```
Comment (lmurray) [inline drivers/gles3/rasterizer_canvas_gles3.cpp:295]: Should this line be placed here or should it be moved above the `backbuffer_gen_mipmaps = false;` line above? I get the impression that it should be moved upwards so that `material_screen_texture_mipmaps_cached` is set to true if the above `render_target_copy_to_back_buffer()` call generated the mipmaps directly.
