### PR TITLE
Focus EventListener when InputEventConfigurationDialog is opened.

### LINKED ISSUE #67211: Automatically focus the key/gamepad listener on the new input map editor dialog
### Godot version

4.0.beta (0c23a2cfe)

### System information

Fedora 36, AMD Radeon RX 6900 XT

### Issue description

The new input map dialog doesn't focus **Filter by event…** by default, so you can't press a key anymore after making it show up (unlike in 3.x):

image

Most of the time, you want to input a key or gamepad button as soon as you open the dialog. Selecting a key manually is typically only useful for scenarios where you can't press the key on your keyboard layout (e.g. for function keys above <kbd>F12</kbd>).

### Steps to reproduce

- Open Project Settings > Input Map.
- Add an input action.
- Add a key for the input action.
- Notice how you have to click the top field first before being able to press a key to register it.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by EricEzaM**
Closes #67211

Can't just use `grab_focus` as it is, because of the way the EventListener needs to ignore the first input made to it, otherwise clicking into the line edit would override the event.

https://user-images.githubusercontent.com/41730826/195796120-73f9f1b1-c870-40d3-b828-951624435082.mp4

### CODE REVIEW

File: editor/input_event_configuration_dialog.cpp [hunk 1]
```diff
@@ -533,6 +533,9 @@ String InputEventConfigurationDialog::_get_device_string(int p_device) const {
 
 void InputEventConfigurationDialog::_notification(int p_what) {
 	switch (p_what) {
+		case NOTIFICATION_VISIBILITY_CHANGED: {
+			event_listener->grab_focus();
+		}
```
Comment (akien-mga) [inline editor/input_event_configuration_dialog.cpp:538]: Falls through but not marked implicit. Should either end with `break;` or `[[fallthrough]];`.

Comment (EricEzaM) [reply editor/input_event_configuration_dialog.cpp]: Oops.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
