### PR TITLE
Handle the smoothstep degenerate case of empty range

### LINKED ISSUE #68128: smoothstep returning out of range values for 0 length steps
### Godot version

4.0.dev (merge #68060)

### System information

Windows 11

### Issue description

In math_funcs.h the two smoothstep functions return a value clamped between 0.0 and 1.0 except when the from and to values are almost equal, in which case they return the value of from, which could be 7 million for all we know. I'm confident they should return a value between 0.0 and 1.0 instead. Personally I think 0.5 would be a decent compromise.

### Steps to reproduce

I'm not reproducing this I'm just eyeballing the code. It's only 3 lines long.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Malcolmnixon**
This PR fixes issue #68128 by handling the empty-range case as a binary-divisor between 0.0 and 1.0.
It also updates the documentation to describe positive and negative ranges.

Note that it depends on https://github.com/godotengine/godot-docs/pull/9489 to go in first so the graph URL links work.

<i>Bugsquad edit:</i>
- Fix #68128

### CODE REVIEW

File: core/math/math_funcs.h [hunk 1]
```diff
@@ -447,14 +447,14 @@ class Math {
 
 	static _ALWAYS_INLINE_ double smoothstep(double p_from, double p_to, double p_s) {
 		if (is_equal_approx(p_from, p_to)) {
-			return p_from;
+			return p_s <= p_from ? 0.0 : 1.0;
```
Comment (kleonc) [inline core/math/math_funcs.h:450]: Almost equal `p_from > p_to` is still technically a "negative range" hence I'd say it should be treated as such. So e.g. `smoothstep(0.000001, 0.0, 0.0)` should be `1.0`, not `0.0`.
```suggestion
			return p_s <= MIN(p_from, p_to) ? 0.0 : 1.0;
```

Comment (clayjohn) [reply core/math/math_funcs.h:450]: Your example will still return 0.0, even with the modified code as `0.0 <= 0.0` will evaluate to `true`

Comment (Malcolmnixon) [reply core/math/math_funcs.h:450]: I was figuring ranges smaller than is_equals_approx could be treated as a zero-range; however this is a good improvement. If the range is smaller than the is_equals_approx window then the S-curve segment disappears and it turns into a binary comparison. This makes that binary comparison polarity accurate down to the level of the float/double comparison.

**Comment by Malcolmnixon** [comment]
@kleonc I copied your fix for the double implementation over to the float and squashed the commits in preparation for merge.

**Review by kleonc — APPROVED** [review]
LGTM!

But since I've proposed changing it to the current version, another opinion / approval would be good.

+Remainder for before merging:

> Note that it depends on [godotengine/godot-docs#9489](https://github.com/godotengine/godot-docs/pull/9489) to go in first so the graph URL links work.

File: core/math/math_funcs.h [hunk 2]
```diff
@@ -447,14 +447,22 @@ class Math {
 
 	static _ALWAYS_INLINE_ double smoothstep(double p_from, double p_to, double p_s) {
 		if (is_equal_approx(p_from, p_to)) {
-			return p_from;
+			if (p_from <= p_to) {
```
Comment (BastiaanOlij) [inline core/math/math_funcs.h:450]: The more I think of this, the more I wonder if this check makes any sense `p_from` is approximately equal to `p_to`, they could flip order just by a floating point precision error. I think in the case of then being approximately equal we should just do `return p_s <= p_from ? 0.0 : 1.0;`

Comment (Calinou) [reply core/math/math_funcs.h:450]: Consider using `likely()` and `unlikely()` hints to guide the compiler towards doing better optimization.

File: core/math/math_funcs.h [hunk 3]
```diff
@@ -447,14 +447,22 @@ class Math {
...
+				return p_s <= p_to ? 1.0 : 0.0;
+			}
 		}
 		double s = CLAMP((p_s - p_from) / (p_to - p_from), 0.0, 1.0);
 		return s * s * (3.0 - 2.0 * s);
 	}
 	static _ALWAYS_INLINE_ float smoothstep(float p_from, float p_to, float p_s) {
 		if (is_equal_approx(p_from, p_to)) {
-			return p_from;
+			if (p_from <= p_to) {
```
Comment (Calinou) [inline core/math/math_funcs.h:461]:
```suggestion
			if (likely(p_from <= p_to)) {
```

**Comment by Malcolmnixon** [comment]
I updated the PR to match the updated graph in the https://github.com/godotengine/godot-docs/pull/9489 pull request. I would request people review that PR (which just adds the image) in order to get this dependent PR merged.

**Comment by Malcolmnixon** [comment]
The godot-docs image was converted from png to webp to align with the [guidelines](https://docs.godotengine.org/en/stable/contributing/documentation/docs_image_guidelines.html). As such this PR has been updated to refer to the webp image.

File: doc/classes/@GlobalScope.xml [hunk 4]
```diff
@@ -1259,6 +1260,7 @@
 				[/codeblock]
 				Compared to [method ease] with a curve value of [code]-1.6521[/code], [method smoothstep] returns the smoothest possible curve with no sudden changes in the derivative. If you need to perform more advanced transitions, use [Tween] or [AnimationPlayer].
 				[url=https://raw.githubusercontent.com/godotengine/godot-docs/master/img/smoothstep_ease_comparison.png]Comparison between smoothstep() and ease(x, -1.6521) return values[/url]
+				[url=https://raw.githubusercontent.com/godotengine/godot-docs/master/img/smoothstep_range.webp]Smoothstep() return values with positive, zero, and negative ranges[/url]
```
Comment (Calinou) [inline doc/classes/@GlobalScope.xml:1263]: Even if this starts a sentence, `smoothstep()` is always lowercase:

```suggestion
				[url=https://raw.githubusercontent.com/godotengine/godot-docs/master/img/smoothstep_range.webp]smoothstep() return values with positive, zero, and negative ranges[/url]
```

**Review by clayjohn — APPROVED** [review]

**Comment by clayjohn** [comment]
Looks good. Just needs a rebase before merging. Feel free to do that after 4.3 releases so you don't end up having to rebase again (since this needs to wait for 4.4 before merging)

**Comment by Malcolmnixon** [comment]
> Looks good. Just needs a rebase before merging. Feel free to do that after 4.3 releases so you don't end up having to rebase again (since this needs to wait for 4.4 before merging)

Rebased

**Comment by akien-mga** [comment]
Thanks!
