### PR TITLE
Make dialogs exclusive by default, fixes #37732

### LINKED ISSUE #37710: Help window closes when filter is selected
**Godot version:**
4.0.dev.calinou.fafb0ba06

**OS/device including version:**
Kubuntu 19.10, KDE Plasma 5.16.5

**Issue description:**
Help window closes when filter is selected.

**Steps to reproduce:**

**Minimal reproduction project:**
—

### LINKED ISSUE #37731: Creating or choosing a folder when creating a project closes all popups and doesn't create the project
Godot 4 b3310a00743d65d8baa2b5730ecfaed8bf8842a6
Windows 10 64 bits

I try to create a project using the project manager but each time I choose a folder, all popups close and I'm left with the empty project manager, having created no project.
This makes it impossible to create a project.

1) Open project manager
2) Choose New Project
3) Choose Browse to select a folder, then validate: observe all popups close.

I expected the selected folder path to be written to the "Project Path" and be able to resume creating the project.

### LINKED ISSUE #37732: All popups close when the main window is hidden, minimized, moved or resized
Godot 4 b3310a00743d65d8baa2b5730ecfaed8bf8842a6
Windows 10 64 bits

In the project manager, when a popup is opened (to create a project for example), focusing another app or minimizing Godot and then focusing it again will restore popups as they were, but they will immediately all close, instead of being focused back.
It also happens when interacting with the decoration of the main window, and it's quite annoying to have such popups behaving in such a "volatile" way (that no other native app does).

1) Open Project Manager
2) Choose New Project
3) Click on another app (or interact with Godot's main window decoration)
4) Click back onto Godot: the New Project popup closes.

Also reproduces with editor popups, such as project settings.

This did not happen in Godot 3.2.1.

### PR DESCRIPTION
**Pull request by reduz**
Also fix on set_visible, not creating exclusive children as it should.

The idea is that if you open a transient dialog (a dialog that is spawned from a parent window) by default you are not allowed to do changes in the parent window until this dialog is closed. Likewise, the dialog will not close if you focus in/out as it is now an exclusive dialog.

*Bugsquad edit:* Fixes #37732. Also fixes #37731 and fixes #37710

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Meriipu** [comment]
Dialogs work great again now thanks

**Comment by aaronfranke** [comment]
This causes a regression with single-window mode, none of the windows (nor the editor in the background) are clickable and they don't update. The editor isn't frozen, it still updates when resized, but it no longer accepts user input.

This is what happens when I open the editor settings to try and disable single window mode (and then I resized the window so you can see it's not frozen). For the moment it seems like I'm in a chicken-and-egg problem unless I delete my editor settings file.

Screenshot from 2020-06-30 16-16-03

**Comment by dreamsComeTrue** [comment]
Confirming - opening any dialogs on Fedora causes Editor basically to stop receiving any input :(

File: scene/gui/dialogs.h [hunk 1]
```diff
@@ -44,6 +44,7 @@ class LineEdit;
 class AcceptDialog : public Window {
 	GDCLASS(AcceptDialog, Window);
 
+public:
```
Comment (akien-mga) [inline scene/gui/dialogs.h:47]: @reduz Why was this changed BTW? It doesn't seem necessary.

Comment (akien-mga) [reply scene/gui/dialogs.h:47]: Confirmed on IRC that this was a mistake, fixing in #40016.
