### PR TITLE
Fix usage of Enum as constant

### LINKED ISSUE #54018: [GDScript 2.0] Can't assign enum to a constant in GDscript
### Godot version

4.0.dev (f113dc986)

### System information

Windows 10

### Issue description

In Godot 3, you could assign an enum to a constant. This is not possible in 4, you get "Parse Error: Initializer for a constant must be a constant expression.".
You can assign it to a variable instead but then you can't use it for export because you need a constant, so this is annoying.

### Steps to reproduce

Define a named enum, then try to assign that enum to a constant.

### Minimal reproduction project

Just paste this in a script.
```
enum ANIMAL_ENUM {COW, PIG, RABBIT}	#enum
var animal_var = ANIMAL_ENUM	#can assign the enum to a variable
const PIG_CONST = ANIMAL_ENUM.PIG	#can assign a member of the enum to a constant
const ANIMAL_CONST = ANIMAL_ENUM	#can't assign the enum itself to a constant
```

### LINKED ISSUE #70213: GDScript 2.0: Cannot assign external enum as a constant
### Godot version

4.0.dev (10bc1d8)

### System information

Linux (Ubuntu 22.04), Vulkan, Radeon RX Vega 64 (eGPU)

### Issue description

Given the following GDScript file:
```gdscript
extends Node

const External: = preload("res://external.gd")
const MyEnum: = External.MyEnum
```

Godot will return this error:
```
SCRIPT ERROR: Parse Error: Initializer for a constant must be a constant expression.
          at: GDScript::reload **(res://main.gd:4)**
```

It should be possible to assign external enums as constants.

Seems to be a regression caused by https://github.com/godotengine/godot/pull/69907. The issue doesn't exhibit in beta 8.

Similar to #69917, which is about external inner classes.

### Steps to reproduce

1. Open minimal project
2. Open `main.gd`
3. See that Godot returns the previously mentioned error

### Minimal reproduction project

[external_enum_constant.zip](https://github.com/godotengine/godot/files/10252654/external_enum_constant.zip)

### LINKED ISSUE #70495: Accessing keys() dict of an enum defined in a singleton crashes app
### Godot version

beta10

### System information

Windows10

### Issue description

With beta10, when an enum is defined in an autoloaded script, calling the keys() method on the enum crash the app.

Works well if the enum is not defined in a singleton.
Worked well in beta9

### Steps to reproduce

1°) Define an enum in a script and make it as an autoloaded script in your project.
2°) Try to access this enum keys() method from another script
Should work in beta9 but crash in beta10

### Minimal reproduction project

[global_enum_bug.zip](https://github.com/godotengine/godot/files/10297245/global_enum_bug.zip)

### PR DESCRIPTION
**Pull request by vonagam**
Set `reduced_value` so that Enums can be properly used as constants.

The value is Dictionary (code for its creation is from `GDScriptCompiler::_populate_class_members`, just moved to `GDScriptAnalyzer::resolve_class_member`). Saved it in new `EnumNode::dictionary` property so that compiler uses the same one. 

Also fixed that outer Enums were not considered constants - there should be no difference. It also should not matter if an enum is accessed directly, through instance or through class, so removed `if` clause in `reduce_identifier_from_base`.

While at it I saw that case for `GDScriptParser::ClassNode::Member::ENUM:` was the only one that was not having `StringName name` variable for readability, fixed that inconsistent injustice.

Fixes #54018.
Fixes #70213 (continuation from  #70220).
Fixes #70495.

### CODE REVIEW

**Comment by anvilfolk** [comment]
I really like this solution a lot! Make sense to me! It's much smarter & should supersede #70569, so I'll close that!

**Review by anvilfolk — APPROVED** [review]
The only thing thing I would say that since now there's a dictionary holding the enum values inside the node, it would be nice if the unit test made sure that parsing works. So for example, the enum could be `enum OuterEnum { A, B, C = 6, E = B +1 }` or something like that to ensure in the future that the dictionary gets the right values?

I don't see how it wouldn't, but better safe than sorry?

**Comment by vonagam** [comment]
Well, there are other tests that do have that. Like [that one](https://github.com/godotengine/godot/blob/b6e06038f8a373f7fb8d26e92d5f06887e459598/modules/gdscript/tests/scripts/analyzer/features/out_of_order_external.gd) that even has recursive things. And it passes.
But if you have any specific snippets of code for the test - write me in chat and I'll add it.

**Review by adamscott — APPROVED** [review]
Moving the dictionary creation from the compiler to the analyzer was the thing to do. Looks good to me.

**Comment by dalexeev** [comment]
I tested this PR, it works great with other scripts, with inner classes (different levels of nesting), with local constants. Perhaps these cases should also be added to the tests in order to fix these features and reduce the likelihood of regressions.

The only issue I've found is that assigning an enum to a variable doesn't raise an error/warning and doesn't convert the enum to a dictionary. As a result, the behavior is a little strange.

```gdscript
extends Node

func _ready() -> void:
    const E = MyClass.MyEnum
    var e := MyClass.MyEnum
    e = {1: 2, 3: 4}

    print(E) # { "VALUE_A": 0, "VALUE_B": 1, "VALUE_C": 2 }
    print(e) # { 1: 2, 3: 4 }

    const C1 = E.VALUE_A
    const C2 = e.VALUE_A # !!!

    print(C1) # 0
    print(C2) # 0
```

**Comment by anvilfolk** [comment]
Thank you for that @dalexeev!

Hmm, that last example does raise some interesting points. There are lots of places where enums are implicitly considered to be dictionaries, but if we reduce them to that too early, there's a chance that we lose the "enum-ness" of them. So perhaps we really do need to check whether a variable is a meta-type more often, and convert to dictionary mostly at the end?

**Comment by vonagam** [comment]
Strange I cannot reproduce `const C2 = e.VALUE_A` - I do get correct error about it being non-constant expression.

As for `Cannot use enum constant as type hint.` - important omitted part: **local** constant. So this is an issue, but a separate one about lookup.

**Comment by adamscott** [comment]
> So perhaps we really do need to check whether a variable is a meta-type more often, and convert to dictionary mostly at the end?

The difficulty resides in the fact that constants need a `reduced_value` to work properly. Not giving it soon enough makes the engine crash.

**Comment by anvilfolk** [comment]
I think what I was getting at is that a lot of checks maybe shouldn't just be `p_node->is_constant` or `p_node->get_datatype().is_constant`, they should be split into
```if (p_node->get_datatype().is_constant) {
  if (p_node->get_datatype().is_metatype) {
    // Handle ENUM and CLASS
  } else {
    // Handle "true" constants
  }
}
```

My PR was keeping an ENUM as a constant without reduced value all the way through to the compiler. The compiler checked whether it was a metatype, and if it was, I think created the dictionary then.

**Comment by dalexeev** [comment]
> Strange I cannot reproduce `const C2 = e.VALUE_A` - I do get correct error about it being non-constant expression.

[test-enum.zip](https://github.com/godotengine/godot/files/10313970/test-enum.zip)
gcc (Ubuntu 12.2.0-3ubuntu1) 12.2.0

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -966,6 +966,13 @@ void GDScriptAnalyzer::resolve_class_member(GDScriptParser::ClassNode *p_class,
 
 				member.m_enum->set_datatype(enum_type);
 
+				Dictionary dictionary;
+				for (int j = 0; j < member.m_enum->values.size(); j++) {
+					// Needs to be string because Variant::get will convert to String.
+					dictionary[String(member.m_enum->values[j].identifier->name)] = member.m_enum->values[j].value;
+				}
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:973]: I believe this can be done in the same loop that fills the `enum_values` vector to avoid another iteration.

**Comment by vnen** [comment]
I do believe this is a good solution (in fact, I was investigating this earlier and thought about pretty much the same code as this).

@anvilfolk I understand your concern but I fear this check may have to be done in a lot of places, which is prone to errors since it's easy to forget. If we can conflate all to constant values it makes easier to deal with this in general.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 1 above)
Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp]: Done.

**Comment by vonagam** [comment]
Ok, I don't know if it is belongs strictly to this PR but I fixed the issue @dalexeev mentioned.

The fix is that a subscript cannot be typed as constant if a base is not.

Have trouble writing the test for that though. While the project has reproducible error (meaning lack of thereof) in editor (no complaints during editing and no error in runtime), but during testing the same code complains about things being non-constant (as it should) without the change, don't know what the reason for that.

**Comment by vonagam** [comment]
Hm. Reverted that fix. When I said that I don't know if it belongs here I meant that the underlying issue is not about enums specifically and affects classes too. Unfortunately while the fix (I think) is correct there is some difference between classes - some of them are constants and some of them are not. Like identifiers for built-in types are not considered constant. So `Vector3.UP` is a subscript on a non-constant base at the moment.

**Comment by anvilfolk** [comment]
Does this one work? It's an interesting one, because presumably `E` is the same as `MyClass.MyEnum`.

```
extends Node

func test(p : MyClass.MyEnum):
  print(p)

func _ready() -> void:
  const E = MyClass.MyEnum
  var a := E.VALUE_A
  var b: E = E.VALUE_A
  print(a)
  print(b) 
```

After (very sleeeepily) thinking about it a bit more, I don't think there's any issue so long as `E`'s datatype `is_metatype`, `kind = ENUM` and `builtin_type = DICTIONARY`. We don't lose any information in this case, I think, and can still check for metatype. It gets used as a constant anywhere where it's relevant, but the information about it being an enum metatype is still there.

**Comment by vonagam** [comment]
No, this one does not work because `const E` is a local constant and they are not looked at during resolving datatype. If `E` is a member constant instead then yes, it does work.

**Review by vnen — APPROVED** [review]
LGTM

**Comment by vnen** [comment]
I also think the other issues mentioned could be solved in a different PR, especially since this one fixes a crash so it's better to merge earlier rather than later.
