### PR TITLE
Fix undo/redo behavior of ColorPicker and add ability to cancel/confirm color selection

### LINKED ISSUE #45186: When you change color property and close the color popup, the property is set twice upon close
**Godot version:**

2af5723

**Steps to reproduce:**
1. Add a Node2D
2. Click to change `modulate` property
3. Change it to different color
4. Press Escape
5. 
image

First set comes from clicking color, two latter sets are from closing the popup.

This was briefly fixed by #44895, but #45042 reintroduced it. This is very low-priority issue (it was there perhaps since last inspector rewrite and no one reported it) and doesn't really affect anything, but it's strange and redundant that the value is set twice.

### LINKED ISSUE #83642: Undoing color change in Inspector requires two Crtl-Z's (sometimes)
### Godot version

v4.2.beta2.official [f8818f85e]

### System information

Godot v4.2.beta2 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3640) - Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 Threads)

### Issue description

After a color property is changed in Inspector (for example Sprite2D / Visibility / Modulate), undoing it requires pressing Ctrl-Z (in Windows) two times. I tried other kind of properties too, but only color seems to have this feature.

### Steps to reproduce

This is what I see in Output, when I change Sprite2D's Visible property (boolean) and Modulate property (color) and then press Ctrl-Z three times.

```
Set visible
Set modulate
Set modulate
Scene Undo: Set modulate    -> 1. Ctrl-Z, nothing happens
Scene Undo: Set modulate    -> 2. Ctrl-Z, color change is undoed
Scene Undo: Set visible     -> 3. Ctrl-Z, boolean is undoed
```

In that example I used color swatch to select a new color and then I closed the color picker by clicking the same color picker button. 

However, sometimes only one Ctrl-Z is enough to undo. I don't know what it exactly needs, but by doing the "select color and undo it" cycle a few times usually seems to change something and one Ctrl-Z starts working. But if another color (e.g. Self Modulate) is changed next, it again needs two Ctrl-Z's.

### Minimal reproduction project

N/A

### LINKED ISSUE #88607: Color picker dialog has numerous UX issues
### Tested versions

Reproducible in 4.3.dev and 4.2.1 stable.

### System information

Godot v4.3.dev (dd81433c8) - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 31.0.15.5123) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 Threads)

### Issue description

- If any tooltips show in the color picker dialog, they steal focus away from all input fields. This is particularly problematic when clicking on the hex code field, typing, then getting immediately interrupted by the tooltip that pops up from the same field.
- If you quit/cancel out of the dialog while typing in the hex code, your input-in-progress will be committed instead of being canceled.
- If you change the color while in the dialog (using any means), wait for a second or so, then quit out of the dialog, the same color will be committed an additional time, requiring two undos to revert.
- You cannot undo color changes while in the picker dialog. All undo shortcuts get redirected to the input fields in the dialog instead. This is super clunky, especially when you can change colors multiple times while in the dialog. Ideally, the entire dialog session should be only _one_ operation that is either committed or canceled, only when the dialog is dismissed.

The combination of these issues above means you can easily run into this scenario:
- Open a color chooser dialog
- Try out a color
- Change your mind after 1 second and close the dialog
- Now you have to undo _twice_ (with the first undo doing absolutely nothing), even though you never intended to follow through.

### Steps to reproduce

Follow the steps in the issue description with any color picker dialog.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by MajorMcDoom**
### Relevant Issues
- Fixes #88607 
- Fixes #83642 
- Fixes #45186
- Could replace #83786

### Changes
This PR fixes a couple of bugs while at the same time introducing some UX changes:
- There will no longer be multiple undos committed for the same color.
- Operations performed in the popup are no longer individually committed to the undo stack. Rather, only one operation is committed when the popup is dismissed.
- If the popup is closed while the HEX code is being edited, it will no longer retain its (possibly invalid) contents when you re-open the popup.
- You are now able to cancel out of the popup without following through with the color selection, instead of having to commit a value you don't want, and then undo it. The `ui_cancel` action (`ESCAPE` by default) is used to cancel out. Dismissing the popup through other means (like clicking outside of it) still confirms the color change as before.
- You can now additionally use the `ui_accept` action (`ENTER` by default) to dismiss the popup and confirm the color operation.

### UX Impact
- The color picker dialog (as in other software) is designed to be a workspace/context in which the user has tools at their disposal to tweak a color as they wish, while previewing the changes. It would be inconsistent with this intent if each color tweak commits an additional undo operation. With this PR, the UX now aligns with the intent.
- The user is now able to either _confirm_ or _cancel_ their operation via keyboard. Granted, users who have grown accustomed to using `ui_cancel` to *confirm* a color operation would have to get used to now pressing `ui_accept` instead, but the old scheme was an oddity and the new scheme is universally known and consistent with the behaviour of all other dialogs.

### CODE REVIEW

**Comment by MajorMcDoom** [comment]
In the long run, it might make sense to add an ability for `Popup` to set whether it allows `ui_accept` and `ui_cancel` to dismiss it. Right now it just uses `ui_cancel`, but I could definitely see a use case for disabling that, or allowing for both.

For now, the `ColorPicker` just specifies a subclass of `PopupPanel` which adds the `ui_accept` functionality on top.

**Comment by JekSun97** [comment]
Perhaps you could solve this problem #88412

**Comment by MajorMcDoom** [comment]
Noticed that this introduces a bug in a Visual Shader node similar to a previous attempted fix. #44895 
I'm going to take a look at this.

**Comment by MajorMcDoom** [comment]
@aXu-AP @KoBeWi I believe I've found a solution to the big web of issues/PRs surrounding color property changes.

To summarize the situation before:
- `EditorProperty` and its subclasses provide a single point of access for consumers to know about property changes: `property_changed`. This was intentional, and abstracts away the UX details of how said property changes are achieved. Consumers only need to know that it has changed, and what it has changed to. We want to keep this setup.
- `ColorPicker` and `ColorPickerButton` are UI classes, and as such should be completely removed from concerns of property change propagation. They only provides signals to inform of color picking results, and of the popup dismissal. i.e. UX events.
- `EditorPropertyColor` is used in multiple places in the editor, with each use case having different demands for the property propagation scheme. Specifically, the inspector requires live change previews, whereas the shader editor only wants to know about the final commit.

In order to simultaneously achieve these goals, the consumers (inspector and shader editor) still only connect and respond to a single signal from `EditorPropertyColor`: `property_changed`. However, they should be able to tell the `EditorPropertyColor` their preference for property update propagation. As such, my solution was to give `EditorPropertyColor` a `bool live_changes_enabled` (true by default), and the means to set it. The shader editor just has to set this to false.

I've considered other alternatives like editor property hints, and using the `p_changing` param of `property_changed`. However:
- You can only have one hint per property, and `EditorPropertyColor` already has `PROPERTY_HINT_COLOR_NO_ALPHA` taking up that special role.
- `p_changing` isn't very well documented or named. It is currently being used for different purposes, and that should be addressed eventually. But the most _core_ use is in `EditorInspector`, where it affects tree updates. It just also happens to be exposed to the user to respond to UX nuances that sometimes line up with the nuances in tree update requirements. As we can see though, these needs don't always line up. For example, we don't want the color picker to constantly submit undo operations, but the value of `p_changing` doesn't have any bearing on this.

Essentially, I would recommend we lean away from freely using `p_changing`, and instead provide per-type API to tweak the UX preferences of each editor property. Anywho, that is my rationale. This PR seems to address all the issues previously encountered. Let me know your thoughts.

**Comment by KoBeWi** [comment]
> EditorPropertyColor was firing property_changed as part of live changes, but this was undesirable, as it generates undo operations.

It causes live edit to not preview color changes in real time. Continuous undo operations are not really a problem; that's what undoredo merging is for.

File: scene/gui/color_picker.cpp [hunk 1]
```diff
@@ -2009,6 +2018,15 @@ ColorPicker::~ColorPicker() {
 
 /////////////////
 
+void ColorPickerPopupPanel::_input_from_window(const Ref<InputEvent> &p_event) {
+	if (get_flag(FLAG_POPUP) && p_event->is_action_pressed(SNAME("ui_accept"), false, true)) {
```
Comment (KoBeWi) [inline scene/gui/color_picker.cpp:2022]: Is the `get_flag()` check needed?

**Comment by MajorMcDoom** [comment]
> > EditorPropertyColor was firing property_changed as part of live changes, but this was undesirable, as it generates undo operations.
> 
> It causes live edit to not preview color changes in real time. Continuous undo operations are not really a problem; that's what undoredo merging is for.

This PR does not break live previews. Is that what you are seeing?

Also, undo redo merging is not relevant here because the color picker is not only capable of generating multiple successive undo operations that don't merge, they also cannot be undone until you close the dialog, after which you have to undo all your edits you did in the dialog.

**Comment by KoBeWi** [comment]
By live edit I mean syncing scene changes with the running project:

https://github.com/godotengine/godot/assets/2223172/95a1fb94-906a-474e-9528-5d94432963e7

With your PR the changes are synced only once the dialog is closed:

https://github.com/godotengine/godot/assets/2223172/76f55c30-a858-425f-af0e-1aa2483a2cf5

Though not sure how important is that. Otherwise the new behavior is an improvement.

File: scene/gui/color_picker.cpp (hunk 1 above)
Comment (MajorMcDoom) [reply scene/gui/color_picker.cpp:2022]: I'm not sure, I think I just copied it over from a similar dialog and I left it in just in case. My guess was that it is a flag than can still be set separately regardless of the control being a PopupPanel, and thus you wouldn't want it to close automatically when you press enter if POPUP flag was set to false.

If this is an impossibility, we can remove it.

Comment (KoBeWi) [reply scene/gui/color_picker.cpp:2022]: Yeah it's impossible, in a way that nothing is setting this flag and it can't change by itself.

**Comment by MajorMcDoom** [comment]
@AThousandShips The Linux editor build failed with the following message:
``` FATAL ERROR: An incorrectly used memory was found.```
Could it be related to this closed issue? #78749

**Comment by AThousandShips** [comment]
Probably not, will re run and see if it's just a random thing, otherwise it's somehow related to this PR

**Review by KoBeWi — APPROVED** [review]

**Comment by TheSofox** [comment]
Great job. I tried to tackle this a bit ago but couldn't figure out how to fix this while keeping the live preview working. Great to see this resolved.
