### PR TITLE
[Web] Fix issue where focus timer would throw continuously

### LINKED ISSUE #98928: [Web] Editor throws continuously when calling internally `GodotIME.ime.focus()`
### Tested versions

- Not reproducible in https://editor.godotengine.org/releases/4.2.2.stable/
- Reproducible in https://editor.godotengine.org/releases/4.3.stable/ 
- Reproducible on master

### System information

Godot v4.3.stable - Web - GLES3 (Compatibility) - Apple M1, or similar -  (2 Threads)

### Issue description

Repeating error as shown in this screenshot:

Capture d’écran, le 2024-11-07 à 12 58 08

```plain
godot.editor.js:12154 Uncaught TypeError: Cannot read properties of null (reading 'focus')
    at focus_timer (godot.editor.js:12154:20)
```

It relates to this part of the code, `GodotIME.ime` seems to be null, so calling `focus()` on it fails (line 49).

https://github.com/godotengine/godot/blob/77d6283d22731398e23c3f1e1b4eeedd22a93152/platform/web/js/libs/library_godot_input.js#L46-L62

### Steps to reproduce

- Open a project on https://editor.godotengine.org/releases/4.3.stable/ 
- Open the web console

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by adamscott**
Two commits. 

1. The first makes Web IME code return early instead of being inside an all-encompassing if statement.
2. The second fixes #98928

### CODE REVIEW

File: platform/web/js/libs/library_godot_input.js [hunk 1]
```diff
@@ -38,41 +38,57 @@ const GodotIME = {
...
-			if (GodotIME.ime) {
-				if (active) {
-					GodotIME.ime.style.display = 'block';
-					setInterval(focus_timer, 100);
-				} else {
-					GodotIME.ime.style.display = 'none';
-					GodotConfig.canvas.focus();
-					GodotIME.active = false;
+			function focusTimer() {
+				if (GodotIME.ime == null) {
```
Comment (Sticksman) [inline platform/web/js/libs/library_godot_input.js:54]: You can probably just check for `!GodotIME.ime` since all of the falsy values can't call focus anyway

File: platform/web/js/libs/library_godot_input.js [hunk 2]
```diff
@@ -133,10 +150,11 @@ const GodotIME = {
...
 
 		clear: function () {
-			if (GodotIME.ime) {
-				GodotIME.ime.remove();
-				GodotIME.ime = null;
+			if (GodotIME.ime == null) {
+				return;
 			}
+			GodotIME.ime.remove();
+			GodotIME.ime = null;
```
Comment (Sticksman) [inline platform/web/js/libs/library_godot_input.js:157]: You could also call `clearinterval` here as well since we know ime being set to null here (just check that your id exists)

File: platform/web/js/libs/library_godot_input.js [hunk 3]
```diff
@@ -84,20 +100,21 @@ const GodotIME = {
...
-						const ptr = GodotRuntime.allocString(event.data);
-						ime_cb(1, ptr);
-						GodotRuntime.free(ptr);
-					} else if (event.type === 'compositionend') {
-						const ptr = GodotRuntime.allocString(event.data);
-						ime_cb(2, ptr);
-						GodotRuntime.free(ptr);
-						GodotIME.ime.innerHTML = '';
-					}
+				if (GodotIME.ime == null) {
```
Comment (Sticksman) [inline platform/web/js/libs/library_godot_input.js:103]: see above check for falsy

File: platform/web/js/libs/library_godot_input.js [hunk 4]
```diff
@@ -84,20 +100,21 @@ const GodotIME = {
...
+					return;
+				}
+				if (event.type === 'compositionstart') {
```
Comment (Sticksman) [inline platform/web/js/libs/library_godot_input.js:106]: switch might be more readable, but not necessary

**Review by Sticksman — APPROVED** [review]

**Review by bruvzg — APPROVED** [review]
Seems to be working fine (tested IME on macOS and Windows with Firefox and Chromium).

File: platform/web/js/libs/library_godot_input.js (hunk 1 above)
Comment (adamscott) [reply platform/web/js/libs/library_godot_input.js:54]: I will not. Because it's not a check that we expect to do per se.

File: platform/web/js/libs/library_godot_input.js (hunk 4 above)
Comment (adamscott) [reply platform/web/js/libs/library_godot_input.js]: Thanks!
