### PR TITLE
[TextServer] Do not add extra spacing to zero-width glyphs.

### LINKED ISSUE #110301: Having negative glyth extra spacing for FontVariations, breaks the minimum x size of the label
### Tested versions

- Reproducible in all versions after 4.5 beta 3

### System information

Godot v4.5.rc1 - Linux Mint 22.1 (Xia) on X11 - X11 display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti (nvidia; 570.169) - AMD Ryzen 7 5800X 8-Core Processor (16 threads) - 31.24 GiB memory

### Issue description

When using a font variation, with a negative glyth extra spacing number, the minimum size for a label (or rich text label), becomes smaller than the actual font rendered, causing many layout bugs, when trying to update my game to the latest version, wheras in 4.5 beta 3, it was working as expected (I use the extra spacing for a bitmap font, but also applies to standard fonts too)

### Steps to reproduce

1.  Create a variation font, and set it to be used on a text label
2. Set the variation fonts "Extra Spacing" value for glyth, to be a negative number (-8 is the best)
3. See how the minimum size is smaller, than the actual text rendered, causing text to be rendered outside the boundary

Image

### Minimal reproduction project (MRP)

[FontTest.zip](https://github.com/user-attachments/files/22194601/FontTest.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Extra spacing is no longer applied to zero-width glyphs and the last non-zero-width glyph in the string (previously it was not applied to the last glyph only, regardless of it width).

Fixes https://github.com/godotengine/godot/issues/110301
Fixes zero-width space/joiners handling in the fallback text server.

### CODE REVIEW

File: modules/text_server_fb/text_server_fb.cpp [hunk 1]
```diff
@@ -4810,6 +4810,17 @@ bool TextServerFallback::_shaped_text_shape(const RID &p_shaped) {
 			sd->glyphs.push_back(gl);
 		} else {
 			// Text span.
+			int last_non_zeto_w = sd->end - 1;
```
Comment (KoBeWi) [inline modules/text_server_fb/text_server_fb.cpp]:
```suggestion
			int last_non_zero_w = sd->end - 1;
```

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
