### PR TITLE
mbedTLS: Fix concurrency issues with TLS

### LINKED ISSUE #104820: Opening Asset Lib causes TLS handshake errors and potential double free crashes
### Tested versions

Reproducible in 4.4.1 stable
For me, opening the asset library has nearly always caused these errors to be printed.

### System information

Windows 11

### Issue description

Opening Asset Lib causes the following messages to print to the console:
```
 ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -110
 ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -1
 ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -28928
 ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -110
 ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -110
 ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -28928
```
I suspect this happens because I am from Australia and the request times out before reaching me because of high ping?

I tested it multiple times, and the error codes and the order that they appear are different
Test 2:
```
 ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -28928
  ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -110
  ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -29056
  ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -28160
```
Test 3, 4: No errors
Test 5:
```
  ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -28928
  ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -110
  ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -110
  ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -1
  ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -110
  ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -1
  ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -110
  ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -28928
  ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -110
  ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -28928
```
Test 6: No errors
Test 7:
```
  ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -28928
  ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -110
  ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -110
  ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -1
  ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -28928
  ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -110
```
Test 8: No errors
Test 9:
```
  ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -28928
  ERROR: modules/mbedtls/stream_peer_mbedtls.cpp:88 - TLS handshake error: -110
```

### Steps to reproduce

1. Open Godot Editor
2. Click on the Asset Lib tab and wait for it to load.
3. Errors pop up!

If the errors don't pop up, try increasing your inbound/outbound ping by using clumsy.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Faless**
When we first integrated mbedTLS, we decided not to enable MBEDTLS_THREADING_C (which adds mutex locking to calls modifying the state), and instead to simply create separate contexts ("states") for each connection.

This worked fine until recently.
Sadly, mbedTLS 3 added a global state for the new PSA crypto functionalities (which are required to support TLSv1.3), and this change was originally [not properly reported in the docs](https://github.com/Mbed-TLS/mbedtls/issues/10103#issuecomment-2771869231).
This results in TLSv1.3 connections accessing and modifying the global state concurrently when running in threads.

This commit enables MBEDTLS_THREADING_C, and MBEDTLS_THREADING_C_ALT to provide a generic Godot implementation using the engine Mutex class.

Fixes #104820

### CODE REVIEW

File: core/io/resource_uid.cpp [hunk 1]
```diff
@@ -109,6 +109,13 @@ ResourceUID::ID ResourceUID::text_to_id(const String &p_text) const {
 }
 
 ResourceUID::ID ResourceUID::create_id() {
+	// mbedTLS may not be fully initialized when the ResourceUID is created, so we
+	// need to lazily instantiate the random number generator.
+	if (crypto == nullptr) {
+		crypto = memnew(CryptoCore::RandomGenerator);
+		((CryptoCore::RandomGenerator *)crypto)->init();
+	}
+
```
Comment (Faless) [inline core/io/resource_uid.cpp:118]: This is very hacky, but we can't call `init` during the constructor, because mbedTLS won't be fully setup yet (the threading functions are set in module initialization CORE which happens after the creation of the ResourceUID singleton).

I've been thinking on dropping the `CryptoCore` usage completely in this class, and instead use `OS::get_singleton()->get_entropy()`.
This might have some negative impact (as it polls the OS entropy generator every time, instead of just using it to initialize a PRNG).
At the same time, given the amount of entropy bytes is low, and the function is mostly called from the editor it might be a worthy change just to clean it up a bit.

Comment (akien-mga) [reply core/io/resource_uid.cpp:118]: Do we really need cryptographic PRNG to generate UIDs used for resources? Wouldn't PCG be "good enough" and let us avoid this hack?

File: thirdparty/mbedtls/include/godot_module_mbedtls_config.h [hunk 2]
```diff
@@ -49,6 +49,13 @@
 #undef MBEDTLS_DES_C
 #undef MBEDTLS_DHM_C
 
+#ifdef THREADS_ENABLED
+// In mbedTLS 3, the PSA subsystem has an implicit shared context, MBEDTLS_THREADING_C is required to make it thread safe.
```
Comment (akien-mga) [inline thirdparty/mbedtls/include/godot_module_mbedtls_config.h:53]: Did you test how it behaves with `threads=no`?

Comment (Faless) [reply thirdparty/mbedtls/include/godot_module_mbedtls_config.h:53]: I did not, but if threads are disabled, there can be no concurrency issue, so we wouldn't need that.

We might want to build with threads=no just to see if some of the new code spilled there, in theory, that build should be unchanged.

**Comment by Faless** [comment]
> The test suite seems to crash on cleanup:

Fixed, I was deleting the mutexes too soon in the cleanup phase.

**Comment by akien-mga** [comment]
> Is it possible that for some reason you are building with mismatching headers (e.g. os includes are used instead of the bundled ones?)

I suspect that too, but I tried setting some `#error` in `/usr/include/mbedtls/ssl.h` and it didn't show up. I also tried uninstalling `mbedtls-devel` but I still reproduce the issue.

It seems to happen with `scons dev_build=yes` but not `scons`, so it's something to do with `DEV_ENABLED`, no optimization, or debug symbols.

I believe it's orthogonal to this issue/PR, it appeared yesterday in my local builds while what this fixes dates back to 4.4-dev.

I'll test this PR with an optimized build (`scons`) to validate the fix, and debug my local issue further independently.

**Review by akien-mga — APPROVED** [review]
Tested with optimized builds (my issue with dev builds is orthogonal to this change) and I confirm this fixed the issue. I also tested successfully with `threads=no`.

**Comment by Repiteo** [comment]
Thanks!

**Comment by akien-mga** [comment]
Already backported to `3.x` and `3.6` via #108382.

**Comment by akien-mga** [comment]
Cherry-picked for 4.4.2.
