### PR TITLE
Autoloads with UIDs

### LINKED ISSUE #111720: Autoload Script references are not using UIDs
### Tested versions

Present in: v4.5.stable.mono.official [876b29033]

### System information

Godot v4.5.stable.mono - macOS Tahoe (26.0.1) - Single-window, 1 monitor - OpenGL 3 (Compatibility) - Apple M1 Pro - Apple M1 Pro (8 threads) - 32.00 GiB memory

### Issue description

When I add the script as "autoload script" using the project settings, the script reference is saved as a path:
```
[autoload]

Unloadable="*res://Scripts/Unloadable.cs"
```

### Actual
When I change the script path in external IDE the reference is broken.

### Expected
The script reference is serialized using UID which doesn't break on file path changes.

### Steps to reproduce

- Add autoload script
- Change the script path outside the Godot editor
- Run the game

### Minimal reproduction project (MRP)

[bug-repro.zip](https://github.com/user-attachments/files/22950038/bug-repro.zip)

### PR DESCRIPTION
**Pull request by KnifeXRage**
Closes: [#111720](https://github.com/godotengine/godot/issues/111720)

Autoloads can now use UIDs for `Scripts` and `Scenes`.

Screenshot 2025-10-30 154258

Autoload Using UIDs:

[Autoload UIDs](https://github.com/user-attachments/assets/76d9bad5-80f4-438d-9d1a-177f9c75c8ff)

When Autoloads files moved Externally:

[Moving Autoload Files Externally](https://github.com/user-attachments/assets/161c6f31-31e9-456b-8515-a08832f90b08)

### CODE REVIEW

File: core/io/resource_uid.cpp [hunk 1]
```diff
@@ -37,6 +37,10 @@
 #include "core/io/resource_loader.h"
 #include "core/math/random_pcg.h"
 
+#ifdef TOOLS_ENABLED
+#include "editor/settings/editor_autoload_settings.h"
+#endif
```
Comment (KoBeWi) [inline core/io/resource_uid.cpp]: Don't include editor code in core 💀
Why do you even need this?

File: scene/resources/packed_scene.cpp [hunk 2]
```diff
@@ -2451,6 +2451,11 @@ void PackedScene::clear() {
 
 void PackedScene::reload_from_file() {
 	String path = get_path();
+
+	if (path.begins_with("uid://")) {
+		path = ResourceUID::get_singleton()->get_id_path(ResourceUID::get_singleton()->text_to_id(get_path()));
+	}
```
Comment (KoBeWi) [inline scene/resources/packed_scene.cpp]: `resource_path` property is always a filename, so this should be unnecessary.

File: editor/settings/editor_autoload_settings.cpp [hunk 3]
```diff
@@ -426,7 +426,17 @@ Node *EditorAutoloadSettings::_create_autoload(const String &p_path) {
 }
 
 void EditorAutoloadSettings::init_autoloads() {
+	bool clear_fs = false;
 	for (AutoloadInfo &info : autoload_cache) {
+		// Convert UID to actual Path (If Possible)
+		if (info.path.begins_with("uid://")) {
+			info.path = ResourceUID::get_singleton()->get_id_path(ResourceUID::get_singleton()->text_to_id(info.path));
+		}
```
Comment (KoBeWi) [inline editor/settings/editor_autoload_settings.cpp]: If anything
```suggestion
		info.path = ResourceUID.ensure_path(info.path);
```
Although FileAccess supports UIDs, so you don't need to convert it.

File: editor/settings/editor_autoload_settings.cpp [hunk 4]
```diff
@@ -530,7 +544,14 @@ void EditorAutoloadSettings::update_autoload() {
 		item->set_text(0, name);
 		item->set_editable(0, true);
 
-		item->set_text(1, scr_path);
+		//Set Text to show in Autoload Section
+		String real_path = ResourceUID::get_singleton()->uid_to_path(scr_path);
```
Comment (KoBeWi) [inline editor/settings/editor_autoload_settings.cpp]: This is a static method.
```suggestion
		String real_path = ResourceUID::uid_to_path(scr_path);
```

**Review by KoBeWi — COMMENTED** [review]
While the idea is fine, there are some unnecessary changes here. What is the file cache thing for? If you want to cleanup outdated autoloads or something then it should be a separate PR.

File: editor/settings/editor_autoload_settings.cpp [hunk 5]
```diff
@@ -395,14 +395,14 @@ Node *EditorAutoloadSettings::_create_autoload(const String &p_path) {
 		scn.instantiate();
 		scn->set_path(p_path);
 		scn->reload_from_file();
-		ERR_FAIL_COND_V_MSG(scn.is_null(), nullptr, vformat("Failed to create an autoload, can't load from path: %s.", p_path));
+		ERR_FAIL_COND_V_MSG(scn.is_null(), nullptr, vformat("Failed to create an autoload, can't load from uid or path: %s.", p_path));
```
Comment (AThousandShips) [inline editor/settings/editor_autoload_settings.cpp]:
```suggestion
		ERR_FAIL_COND_V_MSG(scn.is_null(), nullptr, vformat("Failed to create an autoload, can't load from UID or path: %s.", p_path));
```

File: editor/settings/editor_autoload_settings.cpp [hunk 6]
```diff
@@ -395,14 +395,14 @@ Node *EditorAutoloadSettings::_create_autoload(const String &p_path) {
...
 
 		if (scn.is_valid()) {
 			n = scn->instantiate();
 		}
 	} else {
 		Ref<Resource> res = ResourceLoader::load(p_path);
-		ERR_FAIL_COND_V_MSG(res.is_null(), nullptr, vformat("Failed to create an autoload, can't load from path: %s.", p_path));
+		ERR_FAIL_COND_V_MSG(res.is_null(), nullptr, vformat("Failed to create an autoload, can't load from uid or path: %s.", p_path));
```
Comment (AThousandShips) [inline editor/settings/editor_autoload_settings.cpp]:
```suggestion
		ERR_FAIL_COND_V_MSG(res.is_null(), nullptr, vformat("Failed to create an autoload, can't load from UID or path: %s.", p_path));
```

File: core/io/resource_uid.cpp (hunk 1 above)
Comment (KnifeXRage) [reply core/io/resource_uid.cpp]: I added this to clear `filesystem_cache`, if a unrecognised UID found in project. Because if you move autoload file externally and not it's UID file then it causes too much unrecognised UID errors and even if you move that uid to it's actual path still error will not solve until unless you manually delete the `filesystem_cache` in ".godot/editor/". This will automatically delete if it Recognises Unrecognised UID and fix that 😅.

Comment (KoBeWi) [reply core/io/resource_uid.cpp]: Huh.
It doesn't sound like something specific to autoloads, so it can be fixed separately.

Comment (KnifeXRage) [reply core/io/resource_uid.cpp]: Yes, 
It's just a bug that I fixed. But if you say, I can remove it.

File: editor/settings/editor_autoload_settings.cpp (hunk 3 above)
Comment (AThousandShips) [reply editor/settings/editor_autoload_settings.cpp]: Should be:
```suggestion
		info.path = ResourceUID::ensure_path(info.path);
```
No?

File: scene/resources/packed_scene.cpp (hunk 2 above)
Comment (KnifeXRage) [reply scene/resources/packed_scene.cpp]: it's necessary, if i remove this i will get this error in Godot editor:

>E 0:00:00:761   instantiate: Failed to instantiate scene state of "uid://udewa3o82q2x", node count is 0. Make sure the PackedScene resource is valid.
  <C++ Error>   Condition "nc == 0" is true. Returning: nullptr
  <C++ Source>  scene\resources\packed_scene.cpp:165 @ instantiate()

Or, i can just do `path = ResourceUID::ensure_path(path);`.

**Comment by KnifeXRage** [comment]
As you said i have done all requested changes. but for `packed_scene.cpp` it's a required to convert UIDs to real path if using scene Autoloads. so i updated it to `path = ResourceUID::ensure_path(path);`. 

And i also removed auto cache clear feature. now if _cache_ cause problems to load Autoloads, now we need to **manually** clear it.

File: editor/settings/editor_autoload_settings.cpp [hunk 7]
```diff
@@ -427,6 +427,7 @@ Node *EditorAutoloadSettings::_create_autoload(const String &p_path) {
 
 void EditorAutoloadSettings::init_autoloads() {
 	for (AutoloadInfo &info : autoload_cache) {
+		info.path = ResourceUID::ensure_path(info.path); // Convert UID to actual Path (If Possible)
```
Comment (KoBeWi) [inline editor/settings/editor_autoload_settings.cpp]:
```suggestion
		info.path = ResourceUID::ensure_path(info.path);
```
That comment is unnecessary.

Although why `info.path` is a path here, but UID elsewhere?

File: scene/resources/packed_scene.cpp [hunk 8]
```diff
@@ -2451,6 +2451,8 @@ void PackedScene::clear() {
 
 void PackedScene::reload_from_file() {
 	String path = get_path();
+	path = ResourceUID::ensure_path(path); //If it's a resource uid, then convert to real path.
```
Comment (KoBeWi) [inline scene/resources/packed_scene.cpp]: Instead of modifying PackedScene, you should make a change in `editor_autoload_settings`:
https://github.com/godotengine/godot/blob/019889d1da32e13dfd3bea0f66f7c38ff90a6eb8/editor/settings/editor_autoload_settings.cpp#L396

File: editor/settings/editor_autoload_settings.cpp [hunk 9]
```diff
@@ -530,7 +531,14 @@ void EditorAutoloadSettings::update_autoload() {
...
 		item->set_editable(0, true);
 
-		item->set_text(1, scr_path);
+		//Set Text to show in Autoload Section
+		String real_path = ResourceUID::uid_to_path(scr_path);
+		if (scr_path.begins_with("uid://")) {
+			item->set_text(1, scr_path + " (PATH: " + real_path + ")");
+		} else {
+			item->set_text(1, scr_path);
+		}
```
Comment (KoBeWi) [inline editor/settings/editor_autoload_settings.cpp]: I'm not sure if displaying UID is useful. It could always just show path.

File: editor/settings/editor_autoload_settings.cpp (hunk 7 above)
Comment (KnifeXRage) [reply editor/settings/editor_autoload_settings.cpp]: `info.path` is saved in UID format in `[Autoload]` section not actual path so if we load Autoload from it then it must be converted back to path to load everything properly. And `ensure_path` is used for that, if project autoload in UID format convert it to path or if already path _(old projects migrated has path directly not UID in Autoload section)_ then leave it as is.

File: editor/settings/editor_autoload_settings.cpp (hunk 9 above)
Comment (KnifeXRage) [reply editor/settings/editor_autoload_settings.cpp]: It is useful for better debugging,

Comment (KoBeWi) [reply editor/settings/editor_autoload_settings.cpp]: But is also less readable.
You could put UID in the tooltip.

File: editor/settings/editor_autoload_settings.cpp (hunk 7 above)
Comment (KoBeWi) [reply editor/settings/editor_autoload_settings.cpp]: What exactly needs a path to load properly? The only problematic part is `reload_from_file()`, which is still handled separately.

Comment (KnifeXRage) [reply editor/settings/editor_autoload_settings.cpp]: To load a path properly we need to convert UID to actual file path in project directory. that's what it does.

Comment (KoBeWi) [reply editor/settings/editor_autoload_settings.cpp]: ResourceLoader can load using UID.

File: scene/resources/packed_scene.cpp (hunk 8 above)
Comment (KnifeXRage) [reply scene/resources/packed_scene.cpp]: >  scn->set_path(p_path); 

I modified this part without doing anything with `PackedScene` but Sorry, i am not able to figure out why it's still showing error when running the project, here `p_path` is actual path of autoload scene but in `get_path()` function it stills returns it's UID somehow, so i kept `ensure_path` function.

File: editor/settings/editor_autoload_settings.cpp (hunk 7 above)
Comment (KnifeXRage) [reply editor/settings/editor_autoload_settings.cpp]: But the path we need to provide in `create_autoload` function's argument is file path not UID

File: scene/resources/packed_scene.cpp (hunk 8 above)
Comment (KoBeWi) [reply scene/resources/packed_scene.cpp]: What `get_path()`?
There are no errors or anything.

File: editor/settings/editor_autoload_settings.cpp (hunk 7 above)
Comment (KoBeWi) [reply editor/settings/editor_autoload_settings.cpp]: No, `_create_autoload()` can work with UID, you only need to ensure path in `set_path()` call.

File: scene/resources/packed_scene.cpp (hunk 8 above)
Comment (KoBeWi) [reply scene/resources/packed_scene.cpp]: Looks like there is more code that initializes autoloads like that:
https://github.com/godotengine/godot/blob/cb3af5afff15669a684ba4f04b9aa5c70dfd09ad/main/main.cpp#L4278
https://github.com/godotengine/godot/blob/cb3af5afff15669a684ba4f04b9aa5c70dfd09ad/modules/gdscript/tests/gdscript_test_runner.cpp#L79
Putting `ensure_path()` there should fix it.

Comment (KnifeXRage) [reply scene/resources/packed_scene.cpp]: > What `get_path()`?

`get_path()` is a function in `packed_scene.cpp` which returns path set by `scn->set_path(info.path);` (according to my code analysis), that's why i directly edited `String path = ResourceUID::ensure_path(get_path());` in `packed_scene.cpp` this resolves all the problem that can be caused, like you said:
>Looks like there is more code that initializes autoloads like that:

Without fixing each `scn->set_path(info.path); ` in source code. it directly applies to path set from any location like: `main.cpp` and `gdscript_test_runner.cpp`.

Comment (KoBeWi) [reply scene/resources/packed_scene.cpp]: Well, yeah, you just shouldn't use `set_path()` with UID. Patching PackedScene is a band aid for a wrong usage.
The relevant `set_path()` calls were introduced in #69079, which fixed autoload bugs. Since your PR also touches autoloads, you should update these calls.

Comment (KnifeXRage) [reply scene/resources/packed_scene.cpp]: So, what's your suggestion now? Should i use `scn->set_path(ResourceUID::ensure_path(info.path));` everywhere instead of just `String path = ResourceUID::ensure_path(get_path());` in `packed_scene.cpp`?

Comment (KoBeWi) [reply scene/resources/packed_scene.cpp]: Yes.

Comment (KnifeXRage) [reply scene/resources/packed_scene.cpp]: Done :)

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
