### PR TITLE
Proper (in)validation of negative values in datetime strings and datetime dicts

### LINKED ISSUE #60192: Incorrect error message when hour in datetime string is negative
### Godot version

3.x (8f4f384) master (788f355)

### System information

Arch Linux, GLES 3, Mesa Intel(R) UHD Graphics (CML GT2)

### Issue description

When hour is negative in the datetime string, `Time.get_unix_time_from_datetime_string()` produces incorrect error message.

* `2022-01-02T99:04:05` reports `Invalid hour value of: 99.`
* `2022-01-02T-99:04:05` reports `Invalid hour value of: 157.`

### Steps to reproduce

Run the script below with `-s`.

### Minimal reproduction project

```gdscript
extends SceneTree


func _test_case(text: String):
	print("%s => %d" % [text, Time.get_unix_time_from_datetime_string(text)])


func _init():
	print("===== Start =====")

	_test_case("2022-01-02T03:04:05")
	_test_case("2022-01-02T99:04:05")
	_test_case("2022-01-02T-99:04:05")

	print("====== End ======")
	quit()
```

### PR DESCRIPTION
**Pull request by laws65**
Resolves #60192. Works by changing type of hour, second, and minute in the PARSE_IS08601_STRING macro from uint8_t to int, allowing it to be read as negative, allowing it to be properly validated in the VALIDATE_YMDHMS macro. The same is done in the EXTRACT_FROM_DICTIONARY macro.

### CODE REVIEW

File: core/os/time.cpp [hunk 1]
```diff
@@ -128,9 +131,9 @@ VARIANT_ENUM_CAST(Time::Weekday);
 	int64_t year = UNIX_EPOCH_YEAR_AD;                            \
 	Month month = MONTH_JANUARY;                                  \
 	uint8_t day = 1;                                              \
-	uint8_t hour = 0;                                             \
-	uint8_t minute = 0;                                           \
-	uint8_t second = 0;                                           \
+	int16_t hour = 0;                                             \
+	int16_t minute = 0;                                           \
+	int16_t second = 0;                                           \
```
Comment (aaronfranke) [inline core/os/time.cpp:136]: Since `split_ints` gives us `int`, we should likely just use `int` here, in case someone tries to parse `32770`.

**Review by aaronfranke — CHANGES_REQUESTED** [review]
We should also do the same for the month and day.

File: core/os/time.h [hunk 2]
```diff
@@ -51,7 +51,7 @@ class Time : public Object {
 public:
 	static Time *get_singleton();
 
-	enum Month : uint8_t {
+	enum Month : int16_t {
```
Comment (aaronfranke) [inline core/os/time.h:54]:
```suggestion
	enum Month {
```

File: core/os/time.cpp [hunk 3]
```diff
@@ -177,8 +179,8 @@ VARIANT_ENUM_CAST(Time::Weekday);
 	/* Get all time values from the dictionary. If it doesn't exist, set the */                   \
 	/* values to the default values for Unix epoch (1970-01-01 00:00:00). */                      \
 	int64_t year = p_datetime.has(YEAR_KEY) ? int64_t(p_datetime[YEAR_KEY]) : UNIX_EPOCH_YEAR_AD; \
-	Month month = Month((p_datetime.has(MONTH_KEY)) ? uint8_t(p_datetime[MONTH_KEY]) : 1);        \
-	uint8_t day = p_datetime.has(DAY_KEY) ? uint8_t(p_datetime[DAY_KEY]) : 1;                     \
+	Month month = Month((p_datetime.has(MONTH_KEY)) ? int16_t(p_datetime[MONTH_KEY]) : 1);        \
+	int16_t day = p_datetime.has(DAY_KEY) ? int16_t(p_datetime[DAY_KEY]) : 1;                     \
```
Comment (aaronfranke) [inline core/os/time.cpp:183]:
```suggestion
	Month month = Month((p_datetime.has(MONTH_KEY)) ? int(p_datetime[MONTH_KEY]) : 1);        \
	int day = p_datetime.has(DAY_KEY) ? int(p_datetime[DAY_KEY]) : 1;                     \
```

File: core/os/time.cpp [hunk 4]
```diff
@@ -174,11 +179,11 @@ VARIANT_ENUM_CAST(Time::Weekday);
...
-	Month month = Month((p_datetime.has(MONTH_KEY)) ? uint8_t(p_datetime[MONTH_KEY]) : 1);        \
-	uint8_t day = p_datetime.has(DAY_KEY) ? uint8_t(p_datetime[DAY_KEY]) : 1;                     \
-	uint8_t hour = p_datetime.has(HOUR_KEY) ? uint8_t(p_datetime[HOUR_KEY]) : 0;                  \
-	uint8_t minute = p_datetime.has(MINUTE_KEY) ? uint8_t(p_datetime[MINUTE_KEY]) : 0;            \
-	uint8_t second = p_datetime.has(SECOND_KEY) ? uint8_t(p_datetime[SECOND_KEY]) : 0;
+	Month month = Month((p_datetime.has(MONTH_KEY)) ? int16_t(p_datetime[MONTH_KEY]) : 1);        \
+	int16_t day = p_datetime.has(DAY_KEY) ? int16_t(p_datetime[DAY_KEY]) : 1;                     \
+	int16_t hour = p_datetime.has(HOUR_KEY) ? int16_t(p_datetime[HOUR_KEY]) : 0;                  \
+	int16_t minute = p_datetime.has(MINUTE_KEY) ? int16_t(p_datetime[MINUTE_KEY]) : 0;            \
+	int16_t second = p_datetime.has(SECOND_KEY) ? int16_t(p_datetime[SECOND_KEY]) : 0;
```
Comment (aaronfranke) [inline core/os/time.cpp:186]:
```suggestion
	int hour = p_datetime.has(HOUR_KEY) ? int (p_datetime[HOUR_KEY]) : 0;                  \
	int minute = p_datetime.has(MINUTE_KEY) ? int (p_datetime[MINUTE_KEY]) : 0;            \
	int second = p_datetime.has(SECOND_KEY) ? int (p_datetime[SECOND_KEY]) : 0;
```

**Comment by aaronfranke** [comment]
This PR needs to be rebased now that #60215 was merged.

File: core/os/time.cpp [hunk 5]
```diff
@@ -97,12 +97,17 @@ VARIANT_ENUM_CAST(Time::Weekday);
...
 	ERR_FAIL_COND_V_MSG(minute > 59, ret, "Invalid minute value of: " + itos(minute) + ".");                                                                              \
+	ERR_FAIL_COND_V_MSG(minute < 0, ret, "Invalid minute value of: " + itos(minute) + ".");                                                                               \
 	ERR_FAIL_COND_V_MSG(second > 59, ret, "Invalid second value of: " + itos(second) + " (leap seconds are not supported).");                                             \
+	ERR_FAIL_COND_V_MSG(second < 0, ret, "Invalid second value of: " + itos(second) + ".");                                                                               \
 	/* Do this check after month is tested as valid. */                                                                                                                   \
-	ERR_FAIL_COND_V_MSG(day == 0, ret, "Invalid day value of: " + itos(month) + ", days are 1-indexed and cannot be 0.");                                                 \
+	ERR_FAIL_COND_V_MSG(day == 0, ret, "Invalid day value of: " + itos(day) + ", days are 1-indexed and cannot be 0.");                                                   \
```
Comment (aaronfranke) [inline core/os/time.cpp:109]: Nice catch!

**Review by aaronfranke — COMMENTED** [review]
This PR needs a [rebase and squash](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html), but otherwise the code looks good.

**Comment by laws65** [comment]
All good, right? GitHub says there's a change requested but I can't see what it is

**Review by aaronfranke — APPROVED** [review]

**Comment by aaronfranke** [comment]
Thanks for your contribution!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.
