### PR TITLE
Fix `Find in Files` Search Results cannot open builtin script

### LINKED ISSUE #74145: `Find/Replace in Files` cannot search inside built-in scripts
### Godot version

4.0 rc5, 3.x

### System information

Manjaro Linux, KDE, Nvidia 2060

### Issue description

Both `Find in Files` (Ctrl+Shift+F) and  `Replace in Files` (Ctrl+Shift+R) cannot search in built-in script inside `tscn` files.
Searching Only performs in `gd`  and `gdshader` files.

### Steps to reproduce

1. create node2d with attach built-in script
2. open script tab
3. `Find in Files` (Ctrl+Shift+F)
4. type "Node2D" and press enter
5. see that No Results

### Minimal reproduction project

[reproducable.zip](https://github.com/godotengine/godot/files/10857551/reproducable.zip)

### PR DESCRIPTION
**Pull request by stmSi**
Fix #74145  
I don't think this is best way to do this but this is all I can come up with.
Suggestions for better way are welcome.

### CODE REVIEW

**Comment by KoBeWi** [comment]
Yeah this is not a correct way to do this.
1. You are instantiating the scene, which is rather overkill. And unreliable, because the script can be inside e.g. exported property or attached to a resource
2. You are not freeing the nodes afterwards (this is easy to fix tho)
3. It doesn't seem to work correctly with multiple scripts in scene. I clicked a result, but it opened me wrong script
4. You still need to open the scene when you open the script. Built-in resources can't be edited outside their scene, because any changes you do won't be saved

The solution isn't really bad, but perfectly it should work without creating the nodes. I don't know if there is any way to load the resources from PackedScene without instantiating it.

However, I once opened a proposal for the same problem: https://github.com/godotengine/godot-proposals/issues/6032
My idea was that built-in GDScripts could be mapped to lines in the file and cached, but tbh I'm not sure where to put that cache. Maybe loading the scene each time is fine, but instead of loading as resource, open it as text instead and manually find the line?

How it could potentially work:
1. User searches for "something"
2. Editor finds it in line 79 of a tscn
3. User clicks that line
4. Editor opens the tscn *as a text file*
5. It travels the file line-by-line and looks for GDScript sub-resource headers
6. If it finds one, it parallelly counts the current line in the script
  a. If it reaches line 79, it opens the scene + script on the counted script line
  b. If it reaches end of the script (line ends with unescaped `"`), it looks for the next script until line 79

**Comment by stmSi** [comment]
@KoBeWi I followed your suggestion and rewrite the logic. Can you check it again? 

> You still need to open the scene when you open the script. Built-in resources can't be edited outside their scene, because any changes you do won't be saved

I could not open both the scene and the script.
 `EditorNode::get_singleton()->load_scene(fpath);` and `ste->goto_line_selection` don't want to work together.

**Comment by KoBeWi** [comment]
> EditorNode::get_singleton()->load_scene(fpath); and ste->goto_line_selection don't want to work together.

Pretty sure this can be solved with `call_deferred()`.

**Comment by stmSi** [comment]
tested `ste->call_deferred(SNAME("goto_line_selection"), line_number, begin, end);` and it doesn't seem to work.
Scene opened. Builtin Script opened. But Line Selection doesn't work.

So I changed back to normal and tested `EditorNode::get_singleton()->call_deferred(SNAME("load_scene"), fpath)`
it doesn't seem to work either.

**Comment by KoBeWi** [comment]
idk I tested and it works, but the editor does not center on the selected line.

File: editor/plugins/script_editor_plugin.cpp [hunk 1]
```diff
@@ -3586,7 +3586,71 @@ void ScriptEditor::_on_find_in_files_result_selected(String fpath, int line_numb
...
+				scr_id = scr_id.get_slice("\"", 0);
+
+				scr_start_line = l + 1;
+				int scr_line_count = 0;
+
+				do {
+					line = f->get_line();
+					l++;
+
+					if (line.length() == 1 && line.begins_with("\"")) {
```
Comment (KoBeWi) [inline editor/plugins/script_editor_plugin.cpp:3620]: This will fail if the script has no newline at the end.

Something like
```suggestion
					String strline = line.strip_edges();
					if (strline .ends("\"") && !strline .ends("\\\"")) {
```
would be more reliable.

File: editor/plugins/script_editor_plugin.cpp [hunk 2]
```diff
@@ -3586,7 +3586,71 @@ void ScriptEditor::_on_find_in_files_result_selected(String fpath, int line_numb
 			shader_editor->get_shader_editor(res)->goto_line_selection(line_number - 1, begin, end);
 			return;
 		} else if (fpath.get_extension() == "tscn") {
+			Ref<FileAccess> f = FileAccess::open(fpath, FileAccess::READ);
+			bool is_script_found = false;
+
+			// starting from top of tscn file
```
Comment (KoBeWi) [inline editor/plugins/script_editor_plugin.cpp:3592]:
```suggestion
			// Starting from top of the tscn file.
```

File: editor/plugins/script_editor_plugin.cpp [hunk 3]
```diff
@@ -3586,7 +3586,71 @@ void ScriptEditor::_on_find_in_files_result_selected(String fpath, int line_numb
...
+					if (line.length() == 1 && line.begins_with("\"")) {
+						// found the end of script
+						break;
+					}
+					scr_line_count++;
+
+				} while (!f->eof_reached());
+
+				if (line_number > scr_start_line + scr_line_count) {
+					// find in another builtin gdscript
```
Comment (KoBeWi) [inline editor/plugins/script_editor_plugin.cpp:3629]:
```suggestion
					// Find in another built-in GDScript.
```

File: editor/plugins/script_editor_plugin.cpp [hunk 4]
```diff
@@ -3586,7 +3586,71 @@ void ScriptEditor::_on_find_in_files_result_selected(String fpath, int line_numb
...
+
+			while (!f->eof_reached()) {
+				line = f->get_line();
+				l++;
+
+				if (!line.begins_with(scr_header)) {
+					continue;
+				}
+
+				// found a builtin script...
```
Comment (KoBeWi) [inline editor/plugins/script_editor_plugin.cpp:3609]:
```suggestion
				// Found a built-in script...
```

File: editor/plugins/script_editor_plugin.cpp [hunk 5]
```diff
@@ -3586,7 +3586,71 @@ void ScriptEditor::_on_find_in_files_result_selected(String fpath, int line_numb
...
+					scr_line_count++;
+
+				} while (!f->eof_reached());
+
+				if (line_number > scr_start_line + scr_line_count) {
+					// find in another builtin gdscript
+					continue;
+				}
+
+				// Real line number of the builtin script
```
Comment (KoBeWi) [inline editor/plugins/script_editor_plugin.cpp:3633]:
```suggestion
				// Real line number of the built-in script.
```

**Comment by KoBeWi** [comment]
I checked the code and it looks fine. I found one minor problem, other suggestions are just comment style fixes.

**Comment by stmSi** [comment]
Thanks for suggestions. Updated.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Can't we use `ResourceFormatText` to parse the tscn and extra the GDScript subresource instead of reimplementing an ad hoc parser?

**Comment by stmSi** [comment]
I will look into it now.

**Comment by KoBeWi** [comment]
Using ResourceFormatLoaderText involves parsing the whole file. The current approach is much faster.

**Comment by stmSi** [comment]
I am experimenting `VariantParser::parse_tag_assign_eof` approach
```

			while(true){

				String assign;
				Variant value;

				Error error = VariantParser::parse_tag_assign_eof(&stream, lines, error_text, next_tag, assign, value, nullptr);
				if(error == Error::ERR_FILE_EOF){
					break;
				}

				if (next_tag.name != "sub_resource") {
					continue;
				}
				if(!next_tag.fields.has("type")){
					continue;
				}

				print_line("TYPE");
				print_line(next_tag.fields["type"]);

				if(next_tag.fields["type"] != "GDScript"){
					continue;
				}

				if(!next_tag.fields.has("id")){
					continue;
				}
				scr_id = next_tag.fields["id"];
```
It can work though.

**Comment by akien-mga** [comment]
Let's go with the current approach then :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.2.
