### PR TITLE
Fixes crash when clearing guides in empty scene

### LINKED ISSUE #34111: Crash when clearing guides in empty scene
**Godot version:** v3.2.beta.custom_build.129a22cd9

**OS/device including version:** macOS Catalina 10.15.1

**Issue description:**
The editor crashes when I click the "Clear Guides" menu item in an empty scene.

**Steps to reproduce:**
1. Open an empty scene (without the root node)
2. Swith to the 2D workspace
3. In the editor toolbar, open the "View" menu, and click "Clear Guides".
4. The editor crashes. 

**Minimal reproduction project:** Any project.

---

The cause is that `EditorNode::get_singleton()->get_edited_scene()`  returns `NULL` for an empty scene, making the `has_meta` function crash.

(The function actually returns the root node of the edited scene instead of the scene itself.)

https://github.com/godotengine/godot/blob/129a22cd905d1163641a56a956a69747e4e3c17a/editor/plugins/canvas_item_editor_plugin.cpp#L4753-L4757

I'd like to make a pull request to fix this. But I have some questions: This `case` block has a lot of repeated `EditorNode::get_singleton()->get_edited_scene()` expression. Is there a technical requirement that they are not extracted into a local variable? If extracting into a local varaible is allowed, could I put that modification in the crash-fixing PR, or do that in a separate PR?

### PR DESCRIPTION
**Pull request by timothyqiu**
This fixes #34111 

* Do the null check before calling `has_meta`
* Extract multiple `EditorNode::get_singleton()->get_edited_scene()` calls into a local variable

### CODE REVIEW

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -4752,19 +4752,21 @@ void CanvasItemEditor::_popup_callback(int p_op) {
 		} break;
 		case CLEAR_GUIDES: {
 
-			if (EditorNode::get_singleton()->get_edited_scene()->has_meta("_edit_horizontal_guides_") || EditorNode::get_singleton()->get_edited_scene()->has_meta("_edit_vertical_guides_")) {
+			Node *const root = EditorNode::get_singleton()->get_edited_scene();
```
Comment (akien-mga) [inline editor/plugins/canvas_item_editor_plugin.cpp]: We usually write `const Node *root`.

Comment (timothyqiu) [reply editor/plugins/canvas_item_editor_plugin.cpp]: `const Node *root` makes `root` a pointer to constant, while `Node *const root` makes the pointer itself constant. They are different types.

Also, the `undo_redo->add_do_method(root, ...)` later won't allow a `Node *const` parameter.

I think it's an existing pattern in the codebase, allowing the compiler to optimize the constant local variable away. For example:

https://github.com/godotengine/godot/blob/fbfd56c2477f1c05077a13533d11467ad3753ee4/editor/script_editor_debugger.cpp#L1257-L1262

Comment (akien-mga) [reply editor/plugins/canvas_item_editor_plugin.cpp]: Thanks for the clarification!

**Comment by akien-mga** [comment]
Thanks!
