### PR TITLE
Fix to ColorPicker behaviour when entering html. Fixing Issue #22714

### LINKED ISSUE #22714: ColorPicker: alpha can still be set in hex value if "edit alpha" is off
**Godot version:**

3.06 stable

**OS/device including version:**

Antergos Linux

**Issue description:**

In a ColorPicker node, after setting "edit alpha" to false, the colour's alpha value can still be set through the hex value. Not sure if this is intentional.

**Steps to reproduce:**
Add Colorpicker node. Set "edit alpha" to false. In the running project, add 00 in front of the hex value.
peek 2018-10-04 13-44

### PR DESCRIPTION
**Pull request by bugfi5h**
Fixes #22714
Problem was, that if "edit alpha" was set to false, it was still possible to change the alpha in game by entering it through the html color code.
Now the function checks, if "edit alpha" is false and if so resets the alpha to the original value.

### CODE REVIEW

File: scene/gui/color_picker.cpp [hunk 1]
```diff
@@ -159,7 +159,10 @@ void ColorPicker::_html_entered(const String &p_html) {
 	if (updating)
 		return;
 
-	color = Color::html(p_html);
+	float last_alpha = color.a;
+  	color = Color::html(p_html);
```
Comment (akien-mga) [inline scene/gui/color_picker.cpp]: You seem to have a mix of tabs and spaces, indentation should be tab-based only.
Can you fix this with `git commit --amend` and update the PR with `git push --force`?

**Comment by akien-mga** [comment]
Thanks!
