### PR TITLE
Fix inconsistent lighting in GLES2

### LINKED ISSUE #26269: Glitchy light behaviour on gridmaps in GLES2 and GLES3.
**Godot version:**
Godot_v3.1-beta7
Retested in 3.1-RC1, same results.

**OS/device including version:**
Linux Mint 19.1
NVIDIA GP106 [GeForce GTX 1060 6GB], Driver version: 415.27

**Issue description:**
Lights (OmniLights in this case), do not seem to render correctly on GridMaps while using GLES2.

**Steps to reproduce:**
Place lights in any scene that has a GridMap in it, and test using GLES2.

Examples:

### LINKED ISSUE #28819: Inconsistent OmniLight energy in GLES2.
**Godot version:**
v3.1.1.stable

**OS/device including version:**
Linux Mint 19.1
NVIDIA GP106 [GeForce GTX 1060 6GB], Driver version: 418.56

**Issue description:**
This may or may not be the same issue as #26269, not sure.
I have set up a small interior scene with a single MeshInstance and 4 OmniLights illuminating it.
When moving the camera through the scene, the OmniLights sometimes turn way brighter than what they should be, as if their energy value is being changed.
This does not happen in GLES3.

Update: It also happens with SpotLights.

Video:
https://gfycat.com/givingunawarekinkajou

**Minimal reproduction project:**
[Minimal reproduction project](https://github.com/godotengine/godot/files/3168311/reproduction.zip)

### PR DESCRIPTION
**Pull request by SonarShroom**
Fixes #28819.
Tested on the editor with the provided minimal production project. Although this fix definitely works, there might be a need to clear all the light_index's from all LightInstances to make sure this wouldn't occur in other renderers. I might be wrong on that though. Thanks @clayjohn for all the help.

Commit description:
- Issue was possibily being caused by duplicating a light even when that light was not in the render_light_instances array.
_bugsquad edit:_ Also closes https://github.com/godotengine/godot/issues/26269

### CODE REVIEW

File: drivers/gles2/rasterizer_scene_gles2.cpp [hunk 1]
```diff
@@ -1133,8 +1133,8 @@ void RasterizerSceneGLES2::_add_geometry_with_material(RasterizerStorageGLES2::G
 
 				LightInstance *li = light_instance_owner.getornull(e->instance->light_instances[i]);
 
-				if (li->light_index >= render_light_instance_count) {
-					continue; // too many
+				if (render_light_instances[li->light_index] != li || li->light_index >= render_light_instance_count) {
```
Comment (clayjohn) [inline drivers/gles2/rasterizer_scene_gles2.cpp]: The order of the bools should be reversed. Otherwise when ``light_index >= render_light_instance_count``, ``render_light_instances[li->light_index]`` will crash because its an out of bounds error  

``if (li->light_index >= render_light_instance_count || render_light_instances[li->light_index] != li)``

**Review by clayjohn — CHANGES_REQUESTED** [review]
I noticed while testing out the behaviour under 3.1.1 that the bug was only present in the editor, and that it was also occurring when selecting different nodes in the editor, not just from moving the camera around. Accordingly, I think that there is something more going on. 

This PR does fix the bug though. So it's probably best to merge it for now and then figure out the underlying cause later.

File: drivers/gles2/rasterizer_scene_gles2.cpp (hunk 1 above)
Comment (SonerSound) [reply drivers/gles2/rasterizer_scene_gles2.cpp]: Will make those changes later today. I was thinking about adding a todo comment regarding what you said in your first comment - should I add it?

Comment (clayjohn) [reply drivers/gles2/rasterizer_scene_gles2.cpp]: No, I dont think so. That was more a note to reduz/akien. We may want to just apply this fix and not worry about the underlying problem.as its gonna be re-written for 4.0 anyway.

**Review by clayjohn — APPROVED** [review]

File: drivers/gles2/rasterizer_scene_gles2.cpp (hunk 1 above)
Comment (SonerSound) [reply drivers/gles2/rasterizer_scene_gles2.cpp]: Condition order changed.

**Comment by akien-mga** [comment]
> This PR does fix the bug though. So it's probably best to merge it for now and then figure out the underlying cause later.

Won't merging this ad hoc fix mean that we will never investigate nor fix the underlying cause, if its symptoms are now hidden?

**Comment by clayjohn** [comment]
> Won't merging this ad hoc fix mean that we will never investigate nor fix the underlying cause, if its symptoms are now hidden?

Likely yes, but also, this will likely need to be rewritten for 4.0. So this is more like a band-aid until then.

**Comment by clayjohn** [comment]
@akien-mga After spending some more time on this, I am confident that this is an equivalent solution to the one used in GLES3. GLES3 does something similar, but because of the implementation, GLES3 has to track an additional variable. Because of the way GLES2 is, we can avoid allocating an extra ``uint64_t`` and keeping track of the additional variable. However, this solution requires that we compare two light isntances, im not sure how fast that is. The other "GLES3" solution may be slightly faster. I have implemented it here https://github.com/clayjohn/godot/commit/188fe8ccdab247c3160b8599713f45a5fa1d76a4

**Comment by akien-mga** [comment]
> Because of the way GLES2 is, we can avoid allocating an extra uint64_t and keeping track of the additional variable. However, this solution requires that we compare two light isntances, im not sure how fast that is. The other "GLES3" solution may be slightly faster. I have implemented it here clayjohn@188fe8c

This reads *slightly* more self-documenting to me, though I don't have a strong preference either way. Both you and @SonerSound spent quite some time on this, so I'll let you decide which solution you prefer and we can merge that :)

**Comment by clayjohn** [comment]
We prefer SonerSounds solution here. Lets merge it. :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.

**Comment by EzraT** [comment]
Thank you!

**Comment by jamie-pate** [comment]
https://streamable.com/22j0z <- gridmap lighting is still weird in GLES3 and GLES2

**Comment by clayjohn** [comment]
@jamie-pate this PR is related to a very specific bug in GLES2 only. If you are having other issues, please open a dedicated issue in the issue tracker. 

Also note, from your video it looks like you are running into the problem of only having 8 max lights per object. 8 lights is a hard cap, if you try to have more than that you will experience issues like in your video.

**Comment by jamie-pate** [comment]
@clayjohn #26269 seems closer to my problem. 

RE lights: I'm pretty sure there aren't 8 (active) lights on this mesh. (but I have no idea how to figure it out) Light culling per gridmap would help so much :(
