### PR TITLE
Fix minor inheritance errors

### LINKED ISSUE #68355: It is possible to define a `script` variable, overloading the Node's main script
### Godot version

f814e15c7f 

### System information

Windows 10

### Issue description

It is possible to define and/or export the `script` variable that exists in node.

In Godot 3.5.1, attempting to declare (or export) this variable would result in the following error:
`Parse Error: The member "script" already exists in a parent class`

So this is a regression in 4.0.

### Steps to reproduce

1. Create a `buggy_script.gd` script with `@export var script : Resource`
2. Assign `buggy_script.gd` to a node
3. Select that node (and check that a new variable `script` appears as part of `buggy_script.gd`)
4. Assign some other script to `buggy_script.gd`'s `script` variable

Watch mayhem ensue :)

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by anvilfolk**
Fixes #68355, and variables overloading functions of the base class.

### Fix one

There are only a couple of minor changes added to this fix. Since neither `Node` nor `Object` export the `script` variable through `ClassDB`, I hacked in the property for native classes in `has_member_name_conflict_in_native_type`. It would be more elegant to declare `script` as a property through `ClassDB`, but I figure that's a big decision with far reaching consequences.

### Fix two

Problem:

```
class_name A

func test():
	pass
```

```
extends A

var test : int

func _ready():
	test()
```

There will be an error when calling `test()`, since it is overloaded by the local variable. This is fixed by only allowing overloading of functions if the thing being declared in the subclass is also a function.

Ultimately, functions should only allow overloading if their signatures match.

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -132,7 +133,7 @@ static GDScriptParser::DataType make_builtin_meta_type(Variant::Type p_type) {
 	return type;
 }
 
-bool GDScriptAnalyzer::has_member_name_conflict_in_script_class(const StringName &p_member_name, const GDScriptParser::ClassNode *p_class) {
+bool GDScriptAnalyzer::has_member_name_conflict_in_script_class(const StringName &p_member_name, const GDScriptParser::ClassNode *p_class, bool p_is_func) {
```
Comment (adamscott) [inline modules/gdscript/gdscript_analyzer.cpp:136]: I'm not sure about the added parameter type. I would pass the type and let the method do the comparison instead of passing a highly specific boolean that is used once.

Comment (anvilfolk) [reply modules/gdscript/gdscript_analyzer.cpp:136]: Haha, I was doing that when I thought `has_member_name_conflict_in_script_class` needed to check for overloaded function signatures, but then reverted to something simpler when that turned out to already be done elsewhere.

But I agree. It is more flexible that way!

Comment (anvilfolk) [reply modules/gdscript/gdscript_analyzer.cpp]: Done!

**Comment by anvilfolk** [comment]
Holy moly, I've been pushing wildly. Apologies for that - trying to bugfix and work with a new codebase while pathologically underslept is messy!

I believe this is finally completely done. Early version of the PR were reimplementing stuff that was already implemented. Then I set about reusing the right ones, and ended up fixing a couple of extra bugs. Finally added some unit tests. Should all be squeaky clean & ready.

**Review by clayjohn — APPROVED** [review]
I did more of a code format/style review. The code looks good to me and makes sense to someone not familiar with GDScript. 

I think this should be good to merge if @adamscott also approves

**Review by adamscott — APPROVED** [review]
@clayjohn I would not qualify myself as a GDScript expert, but the PR seems all good to me.
