### PR TITLE
Revert some instances of `Math::INF` back to 1e20

### LINKED ISSUE #107127: Crash when baking VoxelGI in a specific project since 4.5.dev3
### Tested versions

- Reproducible in: 4.5.dev3, 4.5.dev5
- Not reproducible in: 4.4.1.stable, 4.5.dev2

### System information

Godot v4.5.dev3 - Fedora Linux 42 (KDE Plasma Desktop Edition) on X11 - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 5090 (nvidia; 570.153.02) - AMD Ryzen 9 9950X3D 16-Core Processor (32 threads)

### Issue description

Backtrace:

```
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.5.dev.custom_build (9eee8a9345d85df93877766d9bfef204a821d5a5)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[1] /lib64/libc.so.6(+0x19c30) [0x7efc9fbadc30] (??:0)
[2] bin/godot.linuxbsd.editor.x86_64() [0x8097f05] (/home/hugo/Documents/Git/godotengine/godot/scene/3d/voxelizer.cpp:834)
[3] bin/godot.linuxbsd.editor.x86_64() [0x80983be] (/home/hugo/Documents/Git/godotengine/godot/scene/3d/voxelizer.cpp:897 (discriminator 3))
[4] bin/godot.linuxbsd.editor.x86_64() [0x808262e] (/home/hugo/Documents/Git/godotengine/godot/scene/3d/voxel_gi.cpp:502 (discriminator 1))
[5] bin/godot.linuxbsd.editor.x86_64() [0x6d5d847] (/home/hugo/Documents/Git/godotengine/godot/editor/plugins/voxel_gi_editor_plugin.cpp:80)
[6] bin/godot.linuxbsd.editor.x86_64() [0x6de5f63] (/home/hugo/Documents/Git/godotengine/godot/core/variant/binder_common.h:228)
[7] bin/godot.linuxbsd.editor.x86_64() [0x6ddce97] (/home/hugo/Documents/Git/godotengine/godot/core/variant/binder_common.h:338)
[8] bin/godot.linuxbsd.editor.x86_64() [0x6dbd220] (/home/hugo/Documents/Git/godotengine/godot/core/object/callable_method_pointer.h:107)
[9] bin/godot.linuxbsd.editor.x86_64() [0xa6882e9] (/home/hugo/Documents/Git/godotengine/godot/core/variant/callable.cpp:57)
[10] bin/godot.linuxbsd.editor.x86_64() [0xac7d7d9] (/home/hugo/Documents/Git/godotengine/godot/core/object/object.cpp:1288)
[11] bin/godot.linuxbsd.editor.x86_64() [0x759c5d4] (/home/hugo/Documents/Git/godotengine/godot/scene/main/node.cpp:4286)
[12] bin/godot.linuxbsd.editor.x86_64() [0x3bde44a] (/home/hugo/Documents/Git/godotengine/godot/core/object/object.h:940)
[13] bin/godot.linuxbsd.editor.x86_64() [0x76f2ab6] (/home/hugo/Documents/Git/godotengine/godot/scene/gui/base_button.cpp:195)
[14] bin/godot.linuxbsd.editor.x86_64() [0x76f3562] (/home/hugo/Documents/Git/godotengine/godot/scene/gui/base_button.cpp:234)
[15] bin/godot.linuxbsd.editor.x86_64() [0x76f15e4] (/home/hugo/Documents/Git/godotengine/godot/scene/gui/base_button.cpp:69 (discriminator 2))
[16] bin/godot.linuxbsd.editor.x86_64() [0x77eb2f8] (/home/hugo/Documents/Git/godotengine/godot/scene/gui/control.cpp:1865)
[17] bin/godot.linuxbsd.editor.x86_64() [0x762a2a6] (/home/hugo/Documents/Git/godotengine/godot/scene/main/viewport.cpp:1728)
[18] bin/godot.linuxbsd.editor.x86_64() [0x762c90e] (/home/hugo/Documents/Git/godotengine/godot/scene/main/viewport.cpp:1994 (discriminator 2))
[19] bin/godot.linuxbsd.editor.x86_64() [0x763722e] (/home/hugo/Documents/Git/godotengine/godot/scene/main/viewport.cpp:3426 (discriminator 2))
[20] bin/godot.linuxbsd.editor.x86_64() [0x7664f58] (/home/hugo/Documents/Git/godotengine/godot/scene/main/window.cpp:1837)
[21] bin/godot.linuxbsd.editor.x86_64() [0x76eea7b] (/home/hugo/Documents/Git/godotengine/godot/core/variant/binder_common.h:223 (discriminator 6))
[22] bin/godot.linuxbsd.editor.x86_64() [0x76dfd5c] (/home/hugo/Documents/Git/godotengine/godot/core/variant/binder_common.h:338)
[23] bin/godot.linuxbsd.editor.x86_64() [0x76cb522] (/home/hugo/Documents/Git/godotengine/godot/core/object/callable_method_pointer.h:107)
[24] bin/godot.linuxbsd.editor.x86_64() [0xa6882e9] (/home/hugo/Documents/Git/godotengine/godot/core/variant/callable.cpp:57)
[25] bin/godot.linuxbsd.editor.x86_64() [0x37238ef] (/home/hugo/Documents/Git/godotengine/godot/core/variant/variant.h:944)
[26] bin/godot.linuxbsd.editor.x86_64() [0x3705a2a] (/home/hugo/Documents/Git/godotengine/godot/core/variant/variant.h:870)
[27] bin/godot.linuxbsd.editor.x86_64() [0x370573c] (/home/hugo/Documents/Git/godotengine/godot/platform/linuxbsd/x11/display_server_x11.cpp:4433)
[28] bin/godot.linuxbsd.editor.x86_64() [0xa5f90e2] (/home/hugo/Documents/Git/godotengine/godot/core/input/input.cpp:903)
[29] bin/godot.linuxbsd.editor.x86_64() [0xa5fa50b] (/home/hugo/Documents/Git/godotengine/godot/core/input/input.cpp:1184)
[30] bin/godot.linuxbsd.editor.x86_64() [0x370bd7d] (/home/hugo/Documents/Git/godotengine/godot/core/templates/local_vector.h:406)
[31] bin/godot.linuxbsd.editor.x86_64() [0x36d2a76] (/home/hugo/Documents/Git/godotengine/godot/platform/linuxbsd/os_linuxbsd.cpp:977)
[32] bin/godot.linuxbsd.editor.x86_64() [0x36c6bb1] (/home/hugo/Documents/Git/godotengine/godot/platform/linuxbsd/godot_linuxbsd.cpp:85)
[33] /lib64/libc.so.6(+0x35f5) [0x7efc9fb975f5] (??:0)
[34] /lib64/libc.so.6(__libc_start_main+0x88) [0x7efc9fb976a8] (??:0)
[35] bin/godot.linuxbsd.editor.x86_64() [0x36c69a5] (??:?)
-- END OF C++ BACKTRACE --
```

### Steps to reproduce

- Bake the VoxelGI node under the `A` node in the MRP below.

### Minimal reproduction project (MRP)

[voxelatten.zip](https://github.com/user-attachments/files/19641804/voxelatten.zip)

(from https://github.com/godotengine/godot/issues/80101#issuecomment-2785099688)

### LINKED ISSUE #107134: VoxelGI: spotlights disappear when shadows enabled
### Tested versions

bisected to https://github.com/godotengine/godot/pull/105249

### System information

linux

### Issue description

spotlights with shadows enabled do not show up in voxelGI.

this was originally thought to be a problem with my PR and posted as a comment here https://github.com/godotengine/godot/pull/106673#issuecomment-2942714831, but it's not related to my PR.

I bisected the issue as a regression related to this PR https://github.com/godotengine/godot/pull/105249. the following patch which reverts the change for just `scene/3d/voxelizer.cpp` fixes it, but I'm not sure exactly why, so it might be worth looking at other instances of that PR that insert `Math::INF` because it could have caused other similar bugs.

```diff
diff --git a/scene/3d/voxelizer.cpp b/scene/3d/voxelizer.cpp
index 6dd0fda8cb..fbdc667a6e 100644
--- a/scene/3d/voxelizer.cpp
+++ b/scene/3d/voxelizer.cpp
@@ -816,6 +816,7 @@ Vector<int> Voxelizer::get_voxel_gi_level_cell_count() const {
 // https://prideout.net/blog/distance_fields/
 
 #define square(m_s) ((m_s) * (m_s))
+#define INF 1e20
 
 /* dt of 1d function using squared distance */
 static void edt(float *f, int stride, int n) {
@@ -825,8 +826,8 @@ static void edt(float *f, int stride, int n) {
 
 	int k = 0;
 	v[0] = 0;
-	z[0] = -Math::INF;
-	z[1] = +Math::INF;
+	z[0] = -INF;
+	z[1] = +INF;
 	for (int q = 1; q <= n - 1; q++) {
 		float s = ((f[q * stride] + square(q)) - (f[v[k] * stride] + square(v[k]))) / (2 * q - 2 * v[k]);
 		while (s <= z[k]) {
@@ -837,7 +838,7 @@ static void edt(float *f, int stride, int n) {
 		v[k] = q;
 
 		z[k] = s;
-		z[k + 1] = +Math::INF;
+		z[k + 1] = +INF;
 	}
 
 	k = 0;
@@ -861,7 +862,7 @@ Voxelizer::BakeResult Voxelizer::get_sdf_3d_image(Vector<uint8_t> &r_image, Bake
 	uint32_t float_count = octree_size.x * octree_size.y * octree_size.z;
 	float *work_memory = memnew_arr(float, float_count);
 	for (uint32_t i = 0; i < float_count; i++) {
-		work_memory[i] = Math::INF;
+		work_memory[i] = INF;
 	}
 
 	uint32_t y_mult = octree_size.x;
@@ -944,6 +945,8 @@ Voxelizer::BakeResult Voxelizer::get_sdf_3d_image(Vector<uint8_t> &r_image, Bake
 	return BAKE_RESULT_OK;
 }
 
+#undef INF
+
 void Voxelizer::_debug_mesh(int p_idx, int p_level, const AABB &p_aabb, Ref<MultiMesh> &p_multimesh, int &idx) {
 	if (p_level == cell_subdiv - 1) {
 		Vector3 center = p_aabb.get_center();
```

Image
note that the harsh circle here is probably incorrect behavior which is fixed by my previously mentioned PR, but for the purposes of *this* issue, the problem is the complete lack of light on the right.

### Steps to reproduce

open the MRP, select the ShadowOn/VoxelGI node and click "Bake VoxelGI". note that since it's a problem with the voxelizer, not the renderer, it can appear wrong until you re-bake.

### Minimal reproduction project (MRP)

https://github.com/user-attachments/files/20602345/voxelgi-spotlight-test-2.zip

### PR DESCRIPTION
**Pull request by retrotails**
fixes https://github.com/godotengine/godot/issues/107127
fixes https://github.com/godotengine/godot/issues/107134
reverts a few of the changes from https://github.com/godotengine/godot/pull/105249 that were causing issues

### CODE REVIEW

File: core/math/geometry_3d.cpp [hunk 1]
```diff
@@ -862,6 +862,7 @@ Vector<Vector3> Geometry3D::compute_convex_mesh_points(const Plane *p_planes, in
 }
 
 #define square(m_s) ((m_s) * (m_s))
+#define INF 1e20
```
Comment (akien-mga) [inline core/math/geometry_3d.cpp]: We should also `#undef INF` here, like in voxelizer.

We could also consider renaming it to something else that doesn't sound like it was meant to be actually `INFINITY`.

Comment (retrotails) [reply core/math/geometry_3d.cpp]: so `#undef INF` at geometry_3d.cpp:970?

I found `HUGE_LENGTH` elsewhere in godot's codebase; does renaming to `HUGE_NUM`or just `HUGE` sound fine?

it's also apparently a necessary change because one of the checks failed since I think INF is overlapping with Math:INF

Comment (retrotails) [reply core/math/geometry_3d.cpp]: I chose `BIG_VAL`, because apparently `HUGE_VAL` is a c++ macro and I don't want confusion with that

**Review by akien-mga — APPROVED** [review]

**Review by Repiteo — APPROVED** [review]
A deeper dive into *why* this caused a regression in the first place is probably warranted at some point, but that's understandably outside the scope of this PR

File: core/math/geometry_3d.cpp [hunk 2]
```diff
@@ -862,6 +862,7 @@ Vector<Vector3> Geometry3D::compute_convex_mesh_points(const Plane *p_planes, in
 }
 
 #define square(m_s) ((m_s) * (m_s))
+#define BIG_VAL 1e20
```
Comment (lawnjelly) [inline core/math/geometry_3d.cpp:865]: Just to note these are both awful for global namespace.

If you must use such a define, it is better to `#undef` at the bottom of the file that uses it. But usually you can set as a const e.g. in `Geometry3D` if you want a local const.

Comment (akien-mga) [reply core/math/geometry_3d.cpp:865]: They are both `#undef`ed right after they're no longer needed.

**Comment by retrotails** [comment]
> A deeper dive into _why_ this caused a regression in the first place is probably warranted at some point, but that's understandably outside the scope of this PR

my guess as to what's happening:

`work_memory` is an array that holds light data for the voxels. it gets initialized filled with `1e20` as default values, which are supposed to all get overwritten with the actual light data, as it gets calculated. the very last step, after all the light contribution, converts those floats down into `uint8_t` (after taking the sqrt).
when casting `sqrt(1e20)` (which is `1e10`) into `uint8_t`, c++ ends up with `1410065408` because the conversion overflows. which is probably a bug, but it happens to be a massive value (max is 255 and it gets clamped) so it works.
when 1e20 was instead INFINITY; `sqrt(INFINITY) == INFINITY`. casting `INFINITY` to `uint8_t`, c++ chooses `0`, which I think is a special value in the voxel code. perhaps 0 is empty space and 1-255 are light values.

as to why enabling shadows with spotlights specifically makes this crop up, I'm not sure. perhaps the voxel data ends up with some invalid values that only get read in certain circumstances, hence why baking crashes but only sometimes.

that's a lot of speculation though, I don't know much about the voxel GI stuff or C++ and it's not well documented in the code.

File: core/math/geometry_3d.cpp (hunk 2 above)
Comment (retrotails) [reply core/math/geometry_3d.cpp:865]: with my first commit when it was `#define INF 1e20`, 1/20 tests failed because of Math::INF, and I'm not exactly sure how that happened.
note that it was `#define INF 1e20` for a very long time until recently, I'm just reverting back to how it was. switching to a const would be a new change.
https://github.com/godotengine/godot/actions/runs/15467505867/job/43543736106#annotation:14:2114
```
In file included from core/math/.scu/scu_core_math.gen.cpp:11:
./core/math/geometry_3d.cpp:865:13: error: expected unqualified-id before numeric constant
  865 | #define INF 1e20
      |             ^~~~
./core/math/static_raycaster.h:54:54: note: in expansion of macro 'INF'
   54 |                                 float p_tfar = Math::INF) :
      |                                                      ^~~
scons: *** [core/math/.scu/scu_core_math.gen.linuxbsd.editor.dev.double.x86_64.san.o] Error 1
scons: building terminated because of errors.
```

**Comment by akien-mga** [comment]
Thanks!
