### PR TITLE
Fix validated version of array addition

### LINKED ISSUE #52485: [GDScript 2.0] Adding typed arrays bad logic
### Godot version

4.0.dev

### System information

Windows 10

### Issue description

Adding arrays like this is okay
```
var arr1 = [1, 2, 3]
var arr2 = [4, 5, 6]
arr1 = arr1 + arr2 # [1, 2, 3, 4, 5, 6]
```
But when you specify the variable type is seems to add the fist array to itself
```
var arr1: Array = [1, 2, 3]
var arr2: Array = [4, 5, 6]
arr1 = arr1 + arr2 # [1, 2, 3, 1, 2, 3]
```
The same issue is with typed arrays
```
var arr1: Array[int] = [1, 2, 3]
var arr2: Array[int] = [4, 5, 6]
arr1 = arr1 + arr2 # [1, 2, 3, 1, 2, 3]
```
The issue however disappears if you use +=
```
var arr1: Array[int] = [1, 2, 3]
var arr2: Array[int] = [4, 5, 6]
arr1 += arr2 # [1, 2, 3, 4, 5, 6]
```

Also I noticed that the function Array.append_array() disappeared from Godot 4 docs altrought it still autocompletes to it.
Even if it should still be in engine it fails to append two typed arrays
```
var arr1: Array[int] = [1, 2, 3]
var arr2: Array[int] = [4, 5, 6]
var appended = arr1.append_array(arr2) 
# Attempted to append_array a variable of type 'Array' into a TypedArray of type 'int'.
#  <C++ Error>    Condition "type != p_variant.get_type()" is true. Returning: false
#  <C++ Source>   core/variant/container_type_validate.h:82 @ validate()
```

### Steps to reproduce

Copy paste the code above to any function a run it

### Minimal reproduction project

_No response_

### LINKED ISSUE #53984: Array addition pollutes unrelated arrays
### Godot version

4.0.dev (f4d9749e2)

### System information

macOS 11.6

### Issue description

Adding two arrays sets it as the value of an unrelated array.

### Steps to reproduce

```
var unrelated= []
prints('values:', unrelated)
var array = ['a'] + ['b']
prints('values:', unrelated)
```

Results in the following output:

Screen Shot 2021-10-18 at 11 48 40 PM

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/7370874/test.zip)

### PR DESCRIPTION
**Pull request by cdemirer**
Fixes #53984
Fixes #52485 (except the part about `append_array`, but that's already tracked by #54939)

The issue only happens when the validated version of array addition is performed. 

The following should output `[] [a, b]`, but instead outputs `[a, b] [a, b]`:
```gd
var arr1 = []
var arr2 = ['a'] + ['b'] # validated AddArray
prints(arr1, arr2)
```
But the one below works correctly, since the compiler considers `a` and `b` to be `Variant`s, and the non-validated version ends up being called:
```gd
var a = ['a']
var b = ['b']
var arr1 = []
var arr2 = a + b # non-validated AddArray
prints(arr1, arr2)
```
The buggy behavior can be restored by making `a` and `b` typed:
```gd
var a := ['a']
var b := ['b']
var arr1 = []
var arr2 = a + b # validated AddArray
prints(arr1, arr2)
```

Relevant section of code:
https://github.com/godotengine/godot/blob/3d05b94212d1f587cea72a298027b9330c965236/core/variant/variant_op.h#L758-L768
Note that `sum` is expected to be a valid `Array` reference when `_add_arrays` is called.

https://github.com/godotengine/godot/blob/3d05b94212d1f587cea72a298027b9330c965236/core/variant/variant_op.h#L769-L779
In both cases, `r_ret` points to uninitialized / reused memory on VM stack, so it shouldn't be used directly with `_add_arrays`. This is accounted for in `evaluate`, but not in `validated_evaluate`.

### CODE REVIEW

File: core/variant/variant_op.h [hunk 1]
```diff
@@ -775,6 +775,7 @@ class OperatorEvaluatorAddArray {
 		r_valid = true;
 	}
 	static inline void validated_evaluate(const Variant *left, const Variant *right, Variant *r_ret) {
+		*r_ret = Array{};
```
Comment (vnen) [inline core/variant/variant_op.h:778]: Just a nitpick because we don't use this initialization style anywhere in the codebase.

```suggestion
		*r_ret = Array();
```

**Review by vnen — CHANGES_REQUESTED** [review]

**Review by vnen — APPROVED** [review]

File: core/variant/variant_op.h (hunk 1 above)
Comment (cdemirer) [reply core/variant/variant_op.h]: Done :+1:

**Comment by akien-mga** [comment]
Thanks!
