### PR TITLE
GDScript: Fix compilation of expressions compiling other classes

### LINKED ISSUE #81447: 'Invalid get index' cyclic issues.
### Godot version

Godot v4.2.dev4

### System information

Godot v4.2.dev4 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.3713) - 13th Gen Intel(R) Core(TM) i7-13700K (24 Threads)

### Issue description

I am having a lot of what i think are cyclic issues since using Godot v4.2.dev1 through to Godot v4.2.dev4. Looking through the release notes i suspect it has something to do with #79205. 

Due to how large my project is i am unable to create an mrp so i will do my best to describe what is happening. I also make heavy use of custom classes as i use a lot of RefCounted only which i suspect is causing me issues.

### Steps to reproduce

In the video below you can see that upon loading the editor, the Asset class does not know it is inheriting from Entity. If i remove a referenced class on Entity (Or force it to reload) then it registers that it is now inherited from Entity, at least in the editor.
The problem now though is that when i run the game, once it gets to this script, it will not call any functions on the Entity class. Instead it shows the following error: `Invalid get index 'take_damage' (on base: 'Node2D (Asset)').` (take_damage is a method on Entity.)
If however i put the take_damage method onto the Asset class too, then it will run without throwing the error.

https://github.com/godotengine/godot/assets/8760003/4230317d-3892-4abf-b229-bf41f6f22b8b

This same issue seems to happen for quite a few of my classes so currently i cannot even get my project to run in v4.2.
I also notice on some classes i need to remove references to static classes, ie classes with just static variables and methods which i use for utility classes.
Sometimes i cannot call methods on the class itself either so it seems something is stopping the class from compiling at all. I get no errors in the editor, only when i run the game and it comes to the specific class/method.

### Minimal reproduction project

Unfortunately my project is quite large so i am unable to pinpoint the exact issue to create a Mrp. I was debating if i should file this report because of this reason.

### LINKED ISSUE #81548: Using the class_name of a subclass results in spurious 'nonexistent function' errors at runtime
### Godot version

4.2-dev4

### System information

Godot v4.2.dev4 - Arch Linux #1 SMP PREEMPT_DYNAMIC Sat, 10 Jun 2023 00:35:35 +0000 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 970 (nvidia; 530.41.03) - AMD Ryzen 5 2600 Six-Core Processor (12 Threads)

### Issue description

I tried updating a project from Godot 4.1 to 4.2 using the dev snapshot and encountered this issue.

One of my editor plugins has a class called 'Table', that both preloads and uses the class_name of one of its subclasses (let's call it DerivedTable). This seems to trigger a bug in 4.2 that wasn't present in 4.1. At runtime, the engine reports an error that a static function doesn't exist, when it clearly does.

From the attached reproducer:

table.gd:

```GDScript
extends Resource
class_name Table

static func from_directory(path: String, extension := "tres"):
	return preload("derived_table.gd").some_method()

static func from_array(array: Array):
	var table := DerivedTable.new()
	table.set_data(array)
	return table
```

derived_table.gd:

```GDScript
extends Table
class_name DerivedTable

static func some_method():
	pass
```

Then when you call `Table.from_directory("")`, the engine reports:

```
SCRIPT ERROR: Invalid call. Nonexistent function 'from_directory' in base 'GDScript'.
```

### Steps to reproduce

1. Run the attached reproduction project.

### Minimal reproduction project

[Reproducer](https://github.com/godotengine/godot/files/12578722/4.2-static-methods.zip)

### LINKED ISSUE #81799: "Invalid call. Nonexistent function '_ready'" error when I call super() in child class _ready
### Godot version

v4.2.dev4.official [549fcce5f]

### System information

Godot v4.2.dev4 - Linux Mint 21.1 (Vera) - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (RADV NAVI22) () - 12th Gen Intel(R) Core(TM) i5-12400 (12 Threads)

### Issue description

Switching my project from 4.1.1 to 4.2.dev4, I can't launch it anymore.

I have a BaseClass and an InheritedClass, both implementing _ready. InheritedClass::_ready calls super().
When I launch, I have a `Invalid call. Nonexistent function '_ready'` error on the super() line.

### Minimal reproduction project

[MRP_InvalidCallNonExistentReady.zip](https://github.com/godotengine/godot/files/12643270/MRP_InvalidCallNonExistentReady.zip)

### PR DESCRIPTION
**Pull request by anvilfolk**
This PR is part of ongoing work on fixing cyclic dependency errors in the GDScript compiler. This removes another instance of the compiler triggering compilation of an external class during compilation of the current class, with bad side-effects.

Since more of the GDScript codebase now more fully depends on `GDScriptCache::finish_compiling()`, as it should, I also added dependencies to a couple of `GDScriptCache::get_shallow_script()` calls that did not set those dependencies.

Fixes #81548. Fixes #81447. Fixes #81799.

### CODE REVIEW

File: modules/gdscript/gdscript_compiler.cpp [hunk 1]
```diff
@@ -402,7 +402,8 @@ GDScriptCodeGenerator::Address GDScriptCompiler::_parse_expression(CodeGen &code
 							String global_class_path = ScriptServer::get_global_class_path(identifier);
 							if (ResourceLoader::get_resource_type(global_class_path) == "GDScript") {
 								Error err = OK;
-								res = GDScriptCache::get_full_script(global_class_path, err);
+								// Should not need to pass p_owner since analyzer will already have done it.
+								res = GDScriptCache::get_shallow_script(global_class_path, err, parser->script_path);
```
Comment (anvilfolk) [inline modules/gdscript/gdscript_compiler.cpp:406]: For those curious, this is the fix. The other stuff is just trying to ensure dependencies are properly added in the `GDScriptCache`.

**Review by ryanabx — APPROVED** [review]
LGTM! I love small changes like this that are easy to review. Thanks for taking on cyclic dependency hell 😎 
p.s. nice branch name

**Review by akien-mga — APPROVED** [review]
The changes are pretty self-contained and I trust @anvilfolk's work and @ryanabx's review, so this should be good to merge and test in dev5. If there are regressions, we'll spot them there :)

**Comment by anvilfolk** [comment]
I'll be around to fix any more regressions! I did test this on my other cyclic dependencies tests and it worked properly. It might just be ongoing work to squash all these issues that only crop with with specific cyclic relationships and loading orders which exist in large projects.

**Review by adamscott — APPROVED** [review]
Seems fine to me! Let's mergeeeeee!

**Comment by akien-mga** [comment]
Thanks!
