### PR TITLE
Fix Sprite drag and drop hint mentions invalid option with root node selected

### LINKED ISSUE #69219: Godot suggest to drop sprite as sibling to root node
### Godot version

Godot 4.0 Beta 6

### System information

Windows 10

### Issue description

Godot suggest to drop sprite as sibling to root node, while it is impossible to make it as a sibling. In that case when I hold SHIFT, Godot just ignores it. It probably should not show that suggestion when root node is selected?
image

### Steps to reproduce

-

### Minimal reproduction project

-

### PR DESCRIPTION
**Pull request by nongvantinh**
Fixes #69219

Fix the incorrect hint when dragging and dropping assets into the scene while the root node is selected.

### CODE REVIEW

**Comment by RedMser** [comment]
This breaks translation, I believe you need to include the TTR calls to each line that includes a part of the string.

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -5504,21 +5504,28 @@ void CanvasItemEditorViewport::_create_preview(const Vector<String> &files) cons
 		Ref<Texture2D> texture = Ref<Texture2D>(Object::cast_to<Texture2D>(*res));
 		Ref<PackedScene> scene = Ref<PackedScene>(Object::cast_to<PackedScene>(*res));
 		if (texture != nullptr || scene != nullptr) {
+			bool root_node_selected = EditorNode::get_singleton()->get_editor_selection()->is_selected(EditorNode::get_singleton()->get_edited_scene());
+			String desc = "Drag and drop to add as child of current scene's root node.\nHold Ctrl when dropping to add as child of selected node.\n";
+			if (!root_node_selected) {
+				desc += "Hold Shift when dropping to add as sibling of selected node.\n";
+			}
```
Comment (akien-mga) [inline editor/plugins/canvas_item_editor_plugin.cpp:5511]: Indeed as @RedMser mentioned, `TTR()` should be used with string literals, it won't work to do `TTR(desc)`.

So this should likely be split line by line, even though this will lose some context for the translators (but they should still be able to infer it as the strings will be grouped together). And then to avoid any mistake the newlines should be kept out of the translation strings, so we don't rely on translators keeping them at the end of each line.

As the last line differs based on the conditions, the newlines should be added at the start of any `desc +=` addition, instead of the end of the previous message.

```suggestion
			String desc = TTR("Drag and drop to add as child of current scene's root node.") + "\n" + TTR("Hold Ctrl when dropping to add as child of selected node.");
			if (!root_node_selected) {
				desc += "\n" + TTR("Hold Shift when dropping to add as sibling of selected node.");
			}
```

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 2]
```diff
@@ -5504,21 +5504,28 @@ void CanvasItemEditorViewport::_create_preview(const Vector<String> &files) cons
...
 				Sprite2D *sprite = memnew(Sprite2D);
 				sprite->set_texture(texture);
 				sprite->set_modulate(Color(1, 1, 1, 0.7f));
 				preview_node->add_child(sprite);
 				label->show();
 				label_desc->show();
-				label_desc->set_text(TTR("Drag and drop to add as child of current scene's root node.\nHold Ctrl when dropping to add as child of selected node.\nHold Shift when dropping to add as sibling of selected node.\nHold Alt when dropping to add as a different node type."));
+				desc += "Hold Alt when dropping to add as a different node type\n";
+				label_desc->set_text(TTR(desc));
+
```
Comment (akien-mga) [inline editor/plugins/canvas_item_editor_plugin.cpp:5521]:
```suggestion
				desc += "\n" + TTR("Hold Alt when dropping to add as a different node type.");
				label_desc->set_text(desc);
```

Note: Adding missing dot and removed trailing newline in string.

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 3]
```diff
@@ -5504,21 +5504,28 @@ void CanvasItemEditorViewport::_create_preview(const Vector<String> &files) cons
...
 			} else {
 				if (scene.is_valid()) {
 					Node *instance = scene->instantiate();
 					if (instance) {
 						preview_node->add_child(instance);
 						label_desc->show();
-						label_desc->set_text(TTR("Drag and drop to add as child of current scene's root node.\nHold Ctrl when dropping to add as child of selected node.\nHold Shift when dropping to add as sibling of selected node."));
+						label_desc->set_text(TTR(desc));
```
Comment (akien-mga) [inline editor/plugins/canvas_item_editor_plugin.cpp:5528]:
```suggestion
						label_desc->set_text(desc);
```

**Comment by nongvantinh** [comment]
I was not familiar with TTR; thanks for the suggestion and explanations.

**Comment by akien-mga** [comment]
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by akien-mga** [comment]
Sorry for only noticing it now, could you also amend the commit message to be more explicit? The current commit doesn't really give much context so it's hard to make sense of taken individually. What I used to change the PR title could be a good description for the commit too.

**Review by coppolaemilio — APPROVED** [review]

**Comment by coppolaemilio** [comment]
@akien-mga Tested and ready to merge 👍

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by angstyloop** [comment]
https://gist.github.com/angstyloop/08200c6d816347c82ea1aed56c219f17
