### PR TITLE
Replaced OpenXR operating system alert dialog with a warning log message

### LINKED ISSUE #73141: OpenXR Intrusive alert dialog when OpenXR HMD is not connected
### Godot version

4.0.rc1

### System information

Windows 11Pro 10.0.22000

### Issue description

Starting a project with OpenXR enabled (and otherwise configured as per the documentation) but without an HMD connected, results in an operating system message box indicating that OpenXR was requested but failed to start, and suggests checking if an HMD is connected.

I would expect this message to be a log message in the console (and/or the Output window), The operating system dialog is intrusive (especially after the first time it's experienced) and in my case was an obstacle in my workflow. My workflow involves implementing and testing features outside of VR (game logic, behavior, visual effects, storyboarding, blocking out, etc) and then hopping into VR for usability testing and further adjustments. I had to disable OpenXR (and restart the editor), in order to prevent the OpenXR interface from loading, and had to repeat that step whenever I wanted to jump into VR and examine my work.

And for clarity, the OpenXR can fail to load if the HMD is in standby mode or StreamVR is not running, which can happen when the device is sitting without activity or a while, or Stream is not running, which is not infrequent when developing features.

### Steps to reproduce

Ensure an HMD is not connected, and StreamVR (or alternative OpenXR implementation) is not running.

1. Create a new project
2. Navigate to Project Settings
3. Navigate to the OpenXR section under the XR header
4. Ensure Enabled = On (checked)
5. Navigate to the Shaders section under the XR header
6. Ensure Enabled = On (checked)
7. Restart the editor
8. Create a 3D scene, save the scene, and start the project
9. Observe that an operating system dialog appears (see attached screenshot)

openxr_alert

### Minimal reproduction project

[OpenXRAlertIssue.zip](https://github.com/godotengine/godot/files/10715237/OpenXRAlertIssue.zip)

### PR DESCRIPTION
**Pull request by chutchinson**
Fixes #73141

This pull request replaces (at user discretion) an alert dialog when OpenXR fails to initialize (usually due to StreamVR not running, or an HMD is disconnected or in standby) with a **WARN** log message. A new project setting exists (**Startup Alert**), which defaults to true, and toggles this behavior to account for users with an XR-only device.

### Justification

- Operating system alert dialog is intrusive and harmful to (in my opinion) the development workflow
    - Dialog causes significant delay when starting a project (several seconds)
    - Dialog requires user input before starting the project; making adjustments is painful because the dialog must be dismissed on every run
- The warning message shows up in the Errors tab (editor), in addition to a Console output window (if available), which is consistent behavior when compared to other OpenXR failure modes (eg. **create_instance** failure)
- The impact on the codebase is minimal (one statement, using existing technology)

### Personal Impact

This issue became personal. Godot is incredible software and I was inspired to work on a VR project. The dialog was damaging to my workflow, which I argue is probably not uncommon: my workflow consists of implementing game logic, behavior, visual effects, environments, etc. and then testing and iterating outside of VR (fast feedback loop). I launch and perform testing in an HMD when new features have gone through some iterations, and are ready for testing and feedback.

### Possible Workarounds

It is possible to workaround this issue to some extent, by disabling OpenXR in the project settings; however, this requires the user to restart the editor which is similarly intrusive. If the user desires to perform testing in VR they must modify the project setting again (and restart). 

Another workaround is to ensure an OpenXR runtime is running (SteamVR), and an HMD is connected. My argument against this is that during development it's not uncommon for the HMD to enter standby mode, or to close StreamVR, or to just open Godot and begin working without initializing SteamVR or plugging in an HMD.

It is my opinion that these workarounds are hostile to the user

### Screenshots

Attached are screenshots depicting the warning message in the console window and in the **Errors** tab.

log_example
openxr_errors_tab_example

image

### CODE REVIEW

**Comment by chutchinson** [comment]
A pleasant side effect of this bug fix, besides not having to dismiss a dialog on every project run, is that the delay when running a project is much shorter. There was a significant delay (on my Windows 11 system) before the alert dialog appeared. 

I'm not sure how that could happen, because **OS_Windows::alert** directly calls **MessageBoxW**, but perhaps it's related to loading **user32**, or some low-level Windows behavior (themes, or something?).

**Comment by fire** [comment]
I support this as part of the usability team. The xr failure is not a critical error that the engine can't continue.

**Comment by BastiaanOlij** [comment]
> I support this as part of the usability team. The xr failure is not a critical error that the engine can't continue.

That's not strictly true, on XR only devices, the screen will remain black with the user being unaware of what is going on. An alert that on their device OpenXR is not supported or failed to start is the correct behavior imho.

So I think this should be either a project setting with the default being the alert, or a difference in behavior between runtime and debug.

Other than that, fully agree that suppressing the message should be an option especially to make the development workflow easier.

**Comment by chutchinson** [comment]
@BastiaanOlij I added a project setting for displaying the alert modal on startup (default = true). The warning message prints regardless of the setting. Should that warning be escalated to an error message? The message itself does indicate "failure", so I can understand if that's desirable.

I would appreciate any feedback on the name and/or description (help) for the property.

**Review by BastiaanOlij — APPROVED** [review]

**Comment by BastiaanOlij** [comment]
I think it's great the way it is, thanks!

File: modules/openxr/register_types.cpp [hunk 1]
```diff
@@ -113,10 +114,19 @@ void initialize_openxr_module(ModuleInitializationLevel p_level) {
...
 			if (!openxr_api->initialize(Main::get_rendering_driver_name())) {
-				OS::get_singleton()->alert("OpenXR was requested but failed to start.\n"
-										   "Please check if your HMD is connected.\n"
-										   "When using Windows MR please note that WMR only has DirectX support, make sure SteamVR is your default OpenXR runtime.\n"
-										   "Godot will start in normal mode.\n");
+				const char *init_error_message =
+						"OpenXR was requested but failed to start.\n"
+						"Please check if your HMD is connected.\n"
+						"When using Windows MR please note that WMR only has DirectX support, make sure SteamVR is your default OpenXR runtime.\n"
+						"Godot will start in normal mode.\n";
```
Comment (m4gr3d) [inline modules/openxr/register_types.cpp:121]: The message should be wrapped in the tools translate utility (e.g: `TTR("...")`).

Comment (akien-mga) [reply modules/openxr/register_types.cpp:121]: Note that for `TTR()` to work, it will need to be all on a single line, as the translation strings extraction works line by line and this should all be a single string/paragraph in the translation template.

That being said, I'm not sure we translate this kind of OS alert normally. It's within the realm of error message we want to be easily searchable so it's better if it stays in English, so you can easily find documentation / forum posts / bug reports which mention it.

Comment (BastiaanOlij) [reply modules/openxr/register_types.cpp:121]: yeah I agree that it doesn't make a whole lot of sense to translate this.

**Comment by BastiaanOlij** [comment]
I'm all for merging this btw

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.2.
