### PR TITLE
Prevent errors when using ViewportTexture

### LINKED ISSUE #75740: Can't use paths to reference SubViewport nodes
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10, Compatability

### Issue description

I'm trying to create a Control that will automatically render a thumbnail of a material.  To do this, I've created a TextureRectangle to display the thumbnail and a SubViewport to create a simple 3D scene to render the thumbnail.  Unfortunately this is causing a lot of problems with Godot being unable to resolve the path to the viewport.  I read a few other bug reports I think are related, but the node that is using the SubViewport is a peer of the viewport itself.

https://github.com/godotengine/godot/issues/55818

### Steps to reproduce

Try to run this project.  You will get these errors when Godot tries to resolve the path.

E 0:00:01:0049   get_node: Node not found: "SubViewport" (relative to "Control").
  <C++ Error>    Method/function failed. Returning: nullptr
  <C++ Source>   scene/main/node.cpp:1364 @ get_node()
E 0:00:01:0049   setup_local_to_scene: ViewportTexture: Path to node is invalid.
  <C++ Error>    Condition "!vpn" is true.
  <C++ Source>   scene/main/viewport.cpp:76 @ setup_local_to_scene()

### Minimal reproduction project

[subviewportTrumbnailTest.zip](https://github.com/godotengine/godot/files/11167930/subviewportTrumbnailTest.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
`setup_local_to_scene()` is called right when the texture is initializing. It often fails on the first attempt, because the scene is not fully initialized and the assigned node path is still not valid. This PR ensures that ViewportTexture will only try to setup when the scene is prepared. Also there is no way to reasonably expect the texture to immediately hold correct data (size etc.), so I silenced the errors until the texture is initialized. It was already working correctly with the errors, so this PR just changes it to "intended behavior" and removes error spam.

Fixes #75740 and probably similar issues.

Ah I also had to add `is_ready()` method to Node, to reliably check if the node is ready. Maybe it could be exposed to scripting, because it's useful sometimes (although `is_inside_tree()` is enough in most cases).

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Looks good to me. The change in control flow isn't a large as it appears from the size of the PR and overall it seems quite straightforward.

**Review by mhilbrunner — APPROVED** [review]
The Node change likely needs a look by core?
Otherwise LGTM.

File: scene/main/node.cpp [hunk 1]
```diff
@@ -2782,6 +2782,10 @@ bool Node::is_displayed_folded() const {
 	return data.display_folded;
 }
 
+bool Node::is_ready() const {
+	return !data.ready_first;
+}
```
Comment (akien-mga) [inline scene/main/node.cpp:2787]: Should we expose this to the bindings?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by snoopdouglas** [comment]
I note this has also fixed an (unticketed, to my knowledge) issue where `"proxy.is_valid()" is true` errors would appear when using ViewportTextures.

**Comment by akien-mga** [comment]
Cherry-picked for 4.0.3.
