### PR TITLE
String: Fix default decimals truncation in num and num_real

### LINKED ISSUE #51764: String::num undefined behaviour with decimals = -1
### Godot version

master

### System information

MacOS Big Sur 11.4 (AMD Radeon Pro 5500M 4GB)

### Issue description

```cpp
core/string/ustring.cpp:1399:26: runtime error: -inf is outside the range of representable values of type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior core/string/ustring.cpp:1399:26 in 
core/string/ustring.cpp:1399:19: runtime error: signed integer overflow: 14 - -2147483648 cannot be represented in type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior core/string/ustring.cpp:1399:19 in 
```

### Steps to reproduce

compile with ubsan=yes
run engine
error will throw here during startup

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes undefined behavior, and fixes the logic for negative powers of ten.
Fixes #51764. See the issue for details.

Adds tests to validate the changes and prevent regressions.
Adds docs for `String.num`.

---

@aaronfranke Would be good to add similar tests for `num_real` with handling of `REAL_T_IS_DOUBLE`. I suggest doing it as a follow-up PR if you're interested.

### CODE REVIEW

**Review by aaronfranke — APPROVED** [review]
master:

```gdscript
	print(PI)              # 3.14159265358979
	print(PI * 10)         # 31.4159265358979
	print(PI * 100)        # 314.159265358979
	print(PI * 1000)       # 3141.59265358979
	print(PI / 10)         # 0.314159265358979
	print(PI / 100)        # 0.0314159265358979
	print(PI / 1000)       # 0.00314159265358979
	print(PI / 10000)      # 0.000314159265358979
	print(PI / 100000)     # 0.0000314159265358979
	print(PI / 1000000)    # 0.00000314159265358979
```

This PR:

```gdscript
	print(PI)              # 3.14159265358979
	print(PI * 10)         # 31.4159265358979
	print(PI * 100)        # 314.159265358979
	print(PI * 1000)       # 3141.59265358979
	print(PI / 10)         # 0.31415926535898
	print(PI / 100)        # 0.0314159265359
	print(PI / 1000)       # 0.00314159265359
	print(PI / 10000)      # 0.00031415926536
	print(PI / 100000)     # 0.00003141592654
	print(PI / 1000000)    # 0.00000314159265
```

Either behavior makes sense to me, so I wouldn't call the existing behavior wrong, but I think this PR is better. Anyone who needs more digits can always specify so.

**Comment by akien-mga** [comment]
Right, I didn't think that the original behavior (at least after fixing UB) was to keep the same number of significant digits in all cases (so more decimal points for numbers < 1, less decimal points for numbers >= 10).

It does make sense too, not sure which is best.

Or said otherwise, neither really makes sense :P It's a bit weird that this method uses different logic depending on whether the argument is passed (notably, `num(a) != num(a, 14)`).

File: tests/test_string.h [hunk 1]
```diff
@@ -350,13 +350,37 @@ TEST_CASE("[String] Insertion") {
 }
 
 TEST_CASE("[String] Number to string") {
+	CHECK(String::num(0) == "0");
+	CHECK(String::num(0.0) == "0"); // No trailing zeros.
+	CHECK(String::num(-0.0) == "-0"); // Includes sign even for zero.
 	CHECK(String::num(3.141593) == "3.141593");
 	CHECK(String::num(3.141593, 3) == "3.142");
+	CHECK(String::num(3.14159300) == "3.141593"); // No trailing zeros.
```
Comment (aaronfranke) [inline tests/test_string.h:358]: I don't think this test actually accomplishes anything. The literal `3.14159300` is the exact same as `3.141593`.

Comment (akien-mga) [reply tests/test_string.h:358]: > I don't think this test actually accomplishes anything. The literal `3.14159300` is the exact same as `3.141593`.

Fixed.

> Also, we should consider using `Math_PI` in these tests.

I thought about it but I don't think it's a good idea. The point here is not to have a precise constant, it's just to have a random number to test against. It's harder to see if the right hand side matches the left hand side if the left hand side is a constant and not a literal. I'd soon replace this by `42.424242` than `Math_PI` if you really don't like PI-approximate literals ;)

**Comment by akien-mga** [comment]
For the `3.x` cherrypick I think I'll keep the original logic for negative powers of ten so that it doesn't break compat, in case anyone relied on this behavior.

**Comment by akien-mga** [comment]
Actually there's nothing to cherry-pick for `3.x`, this was a recently introduced bug in #34566 (CC @Heikki00).

There might be more UB in the other uses of `log10` in that PR, this should be reviewed.

And which behavior is considered good from the above discussion is still up for debate, as this is not something that was already used in 3.x, so we can adjust the logic as needed before 4.0.
