### PR TITLE
Avoid possibly showing two Dialogs at the same time

### LINKED ISSUE #55133: SceneTreeDialog complains about transient parent with other exclusive child
### Godot version

4.0dev

### System information

Windows 11 Pro

### Issue description

When picking a node when adding a new node in the animation editor, double-clicking a node in the list causes a "Transient parent has another exclusive child." error to be emitted by `Window::set_visible`.

### Steps to reproduce

1. New scene with a Node2D and an AnimationPlayer
2. Add a new track using the AnimationPlayer's Add Track button (doesn't matter what kind, so long as it's one that has you picking a node in the scene tree)
3. Double click on a node.
4. See output.

Clicking on the _Open_ button does not generate the error.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Rindbee**
Fix #55133.

This signal `selected` of `SceneTreeDialog` may cause another dialog to be displayed, so it is more appropriate to hide at first and then emit the signal.

### CODE REVIEW

File: editor/scene_tree_editor.cpp [hunk 1]
```diff
@@ -1353,8 +1353,8 @@ void SceneTreeDialog::_cancel() {
 
 void SceneTreeDialog::_select() {
 	if (tree->get_selected()) {
-		emit_signal(SNAME("selected"), tree->get_selected()->get_path());
 		hide();
+		emit_signal(SNAME("selected"), tree->get_selected()->get_path());
```
Comment (akien-mga) [inline editor/scene_tree_editor.cpp:1357]: I'd add an explanation so that we don't change it back by mistake:
```suggestion
		// The `selected` signal may cause another dialog to be displayed, so be sure to hide this one first.
		hide();
		emit_signal(SNAME("selected"), tree->get_selected()->get_path());
```

**Review by akien-mga — APPROVED** [review]
Looks good, though I'd add a comment too. And while at it you can fix the typo in the commit message (Didalogs).

**Review by akien-mga — APPROVED** [review]
