### PR TITLE
Use fake audio playing property in editor

### LINKED ISSUE #17309: Cannot animate a AudioStreamPlayer with the property "playing"
**Godot version:**
Godot Engine 3.0.2 Stable Official

**OS/device including version:**
KDE Neon

**Issue description:**
[Sorry my english is bad]
I can not animate a AudioStreamPlayer with the property "playing" with the editor. Not work with AudioStreamPlayer2D to.

**Steps to reproduce:**
I recorded a video: https://youtu.be/YX7P-dqHW8A

### PR DESCRIPTION
**Pull request by ShyRed**
It appears that some time ago users were supposed to be able to include the playback of sound effects in their animations by placing keys on the "playing" property. Back then the key frame editor took the value of the checkbox in the property_editor.

Somewhere / Sometime this behaviour changed and the key frame editor is now reading the actual value from the object instead of relying on the property editor.

This commit introduces a fake active field that is returned when reading the playing property in the editor. While the actual active flag is changed when playback is finished the fake one will stay the same thus allowing the user to take their time with setting the key in the animation editor.

Fixes #17309

**Demo project showing off different ways to "animate" sounds:**
[audioanim.zip](https://github.com/godotengine/godot/files/1794499/audioanim.zip)

### CODE REVIEW

File: scene/2d/audio_stream_player_2d.cpp [hunk 1]
```diff
@@ -313,11 +312,15 @@ void AudioStreamPlayer2D::stop() {
 
 bool AudioStreamPlayer2D::is_playing() const {
 
+#ifdef TOOLS_ENABLED
```
Comment (hpvb) [inline scene/2d/audio_stream_player_2d.cpp]: These should not be under TOOLS_ENABLED, as this would affect running the game from inside the editor also. This should be a check for Engine::get_singleton()->is_editor_hint(). The actual runtime check could still be inside an #ifdef block.

**Review by hpvb — CHANGES_REQUESTED** [review]

**Comment by reduz** [comment]
I would hold on this, as inspector is being re-done and we can include a
proper play button...

**Comment by hpvb** [comment]
@reduz it may still be worth having this for the 3.0 branch though.

**Comment by ShyRed** [comment]
@hpvb Improved the commit. Thank you for the review. :+1:

**Comment by hpvb** [comment]
Thanks! I will test this and if it works this will go into 3.0.3, probably not into master however.

**Comment by reduz** [comment]
@hpvb feel free to merge for 3.0, but for 3.1 it won't be used as we'll put a play button in the inspector instead.

**Comment by hpvb** [comment]
Merged for 3.0.3rc2
