### PR TITLE
Fix folder colors not present in editor dir dialog

### LINKED ISSUE #90649: Folder colors not present in Move/Duplicate menu
### Tested versions

- Reproducible in: 4.3.dev5

### System information

Godot v4.3.dev5 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.5212) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

When right clicking one or multiple files in the FileSystem window and clicking the "Move/Duplicate To..." option, the dialog box that opens will not respect any folder colors that are present in the project.

### Steps to reproduce

- Select one or multiple files in the FileSystem window
- Open the right click menu
- Select "Move/Duplicate To..."
- Notice lack of folder colors present in the project's resources

### Minimal reproduction project (MRP)

Any project with folder colors

### PR DESCRIPTION
**Pull request by Muller-Castro**
Fixes https://github.com/godotengine/godot/issues/90649

### CODE REVIEW

File: editor/gui/editor_dir_dialog.cpp [hunk 1]
```diff
@@ -43,16 +44,35 @@ void EditorDirDialog::_update_dir(TreeItem *p_item, EditorFileSystemDirectory *p
...
 		if (!opened_paths.has(path) && (p_select_path.is_empty() || !p_select_path.begins_with(path))) {
 			p_item->set_collapsed(true);
 		}
 
 		p_item->set_text(0, p_dir->get_name());
+
+		Dictionary assigned_folder_colors = FileSystemDock::get_singleton()->get_assigned_folder_colors();
+		if (assigned_folder_colors.has(path)) {
+			bool editor_is_dark_theme = FileSystemDock::get_singleton()->get_editor_is_dark_theme();
+			const Color &folder_color = FileSystemDock::get_singleton()->get_folder_colors()[assigned_folder_colors[path]];
```
Comment (ajreckof) [inline editor/gui/editor_dir_dialog.cpp:63]: those three values could be set once when the dialogue is made visible as they won't change. In addition dark theme should call directly `EditorThemeManager::is_dark_theme` instead of relying on `FileSystemDock`.

File: editor/gui/editor_dir_dialog.cpp [hunk 2]
```diff
@@ -83,8 +103,7 @@ void EditorDirDialog::config(const Vector<String> &p_paths) {
 }
 
 void EditorDirDialog::reload(const String &p_path) {
-	if (!is_visible()) {
-		must_reload = true;
+	if (!must_reload) {
```
Comment (ajreckof) [inline editor/gui/editor_dir_dialog.cpp:106]: This seems strange if it is not visible there is no reasons to reload it. Moreover this might break reload updates if they happen while it is opened (not sure if it can happen).

**Review by ajreckof — CHANGES_REQUESTED** [review]

File: editor/gui/editor_dir_dialog.cpp (hunk 2 above)
Comment (Muller-Castro) [reply editor/gui/editor_dir_dialog.cpp:106]: Better to remove this condition and always leave the reload available?

Comment (ajreckof) [reply editor/gui/editor_dir_dialog.cpp:106]: No what I meant how the code was structured was when anything it relias on changes it tries to reload imediatly but in cas it is not visible it will mark it as needing to be reload (set `must_reload` to true) and skip it and when made visible it will check if it needs to be reloaded and if it is the case do the reload then. 
The fact is you changed this part of the code and I don't understand why you decided to make that change and what it aims to accomplish. It does not seem like your fix should need any modification to the `must_reload` system that was in place.

Comment (Muller-Castro) [reply editor/gui/editor_dir_dialog.cpp:106]: The dialog won't update unless there's an update in the filesystem dock

https://github.com/godotengine/godot/assets/37383316/ec5d05e5-612a-42ac-b9f5-6ad43f93d2fc

Comment (ajreckof) [reply editor/gui/editor_dir_dialog.cpp:106]: then you need `FileSystemDock` to send a signal when colors are modified (might already exists if not you can create one) and connect this signal to the `reload` function. The connection should be done `_notification` under `NOTIFICATION_ENTER_TREE`.

File: doc/classes/FileSystemDock.xml [hunk 3]
```diff
@@ -51,6 +51,13 @@
 				Emitted when a file is moved from [param old_file] path to [param new_file] path.
 			</description>
 		</signal>
+		<signal name="folder_color_changed">
+			<param index="0" name="chosen_color_name" type="String" />
+			<param index="1" name="selected" type="PackedStringArray" />
+			<description>
+				Emitted when all [param selected] folders change color by given [param chosen_color_name].
```
Comment (KoBeWi) [inline doc/classes/FileSystemDock.xml:58]:
```suggestion
			<param index="0" name="folders" type="PackedStringArray" />
			<param index="1" name="color_name" type="String" />
			<description>
				Emitted when [param folders] change color to the given [param color_name].
```
I'd rework this signal like this.

File: editor/gui/editor_dir_dialog.cpp [hunk 4]
```diff
@@ -32,27 +32,46 @@
...
 #include "editor/directory_create_dialog.h"
 #include "editor/editor_file_system.h"
+#include "editor/filesystem_dock.h"
+#include "editor/themes/editor_theme_manager.h"
 #include "scene/gui/box_container.h"
 #include "scene/gui/tree.h"
 #include "servers/display_server.h"
 
-void EditorDirDialog::_update_dir(TreeItem *p_item, EditorFileSystemDirectory *p_dir, const String &p_select_path) {
+void EditorDirDialog::_update_dir(const Dictionary &assigned_folder_colors, const HashMap<String, Color> &folder_colors, bool is_dark_theme, TreeItem *p_item, EditorFileSystemDirectory *p_dir, const String &p_select_path) {
```
Comment (ajreckof) [inline editor/gui/editor_dir_dialog.cpp:41]: Since all functions will be done with the same values you can jus make them instance variable instead of passing them as function parameters.

**Review by ajreckof — APPROVED** [review]
With the few last details this should be good

File: editor/gui/editor_dir_dialog.cpp [hunk 5]
```diff
@@ -99,6 +116,10 @@ void EditorDirDialog::reload(const String &p_path) {
 void EditorDirDialog::_notification(int p_what) {
 	switch (p_what) {
 		case NOTIFICATION_ENTER_TREE: {
+			if (!FileSystemDock::get_singleton()->is_connected("folder_color_changed", callable_mp(this, &EditorDirDialog::reload))) {
```
Comment (KoBeWi) [inline editor/gui/editor_dir_dialog.cpp:119]: Is the condition necessary? The connection below doesn't have one. Also if you want to make sure it's not already connected, use `NOTIFICATION_READY`.

File: editor/filesystem_dock.cpp [hunk 6]
```diff
@@ -3086,6 +3086,8 @@ void FileSystemDock::_folder_color_index_pressed(int p_index, PopupMenu *p_menu)
 
 	_update_tree(get_uncollapsed_paths());
 	_update_file_list(true);
+
+	emit_signal(SNAME("folder_color_changed"), selected, chosen_color_name ? folder_colors[chosen_color_name] : Color(), chosen_color_name ? chosen_color_name : "default");
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:3090]: Now I don't get this signal. Do I see it right that you send both color and its name? The arguments you send are not even used. What are they for?

File: editor/gui/editor_dir_dialog.cpp [hunk 7]
```diff
@@ -99,6 +116,8 @@ void EditorDirDialog::reload(const String &p_path) {
 void EditorDirDialog::_notification(int p_what) {
 	switch (p_what) {
 		case NOTIFICATION_ENTER_TREE: {
+			FileSystemDock::get_singleton()->connect("folder_color_changed", callable_mp(this, &EditorDirDialog::reload).bind(""));
+
```
Comment (KoBeWi) [inline editor/gui/editor_dir_dialog.cpp:120]:
```suggestion
```
Unnecessary blank line.

**Review by KoBeWi — APPROVED** [review]
