### PR TITLE
Fix popup position of color picker

### LINKED ISSUE #71066: Color Picker popups in wrong direction
### Godot version

4.0 beta 10

### System information

Ubuntu 22.04.1 LTS

### Issue description

image

Since the color is near the top of the inspector, I expect the color picker popup to appear below. However...

image

This is because there is no enough space to add it below, so it adds above, reckless of whether

### Steps to reproduce

Click on a color button that is closer to the top of the inspector, but doesn't have enough space to popup below.

You can for example create a Control node and check it with its Modulate property. Might require a smaller screen though.

### Minimal reproduction project

N/A it's in the editor

### PR DESCRIPTION
**Pull request by MewPurPur**
Fixes #71066

The popup is horizontally centered below the button now, but if there isn't enough space to popup below, then it popups above if the button is in the bottom half of the screen. At least that's the behavior I find the most reasonable, but please inform me if I'm missing something here.

### CODE REVIEW

File: scene/gui/color_picker.cpp [hunk 1]
```diff
@@ -1817,34 +1817,23 @@ void ColorPickerButton::_modal_closed() {
...
-			cp_rect.position.x = get_screen_position().x - MAX(0, (cp_rect.size.x - size.x));
-		}
-
-		if (usable_rect.encloses(cp_rect)) {
-			break;
-		}
+	// Determine in which direction to show the popup. By default popup horizontally centered below the button.
+	// But if the popup doesn't fit below and the button is in the bottom half of the viewport, show above.
+	bool show_above = false;
+	if (get_global_position().y + get_size().y + minsize.y > viewport_height && get_global_position().y * 2 + get_size().y > viewport_height) {
```
Comment (Sauermann) [inline scene/gui/color_picker.cpp:1830]: You are kind of mixing different coordinate systems in a single equation here.
- `get_global_position()`: Canvas coordinate system of the containing Canvas
- `get_size()`: Local coordinate system of the `ColorPickerButton`
- `minsize`: Viewport coordinate system of popup
- `viewport_height`: Viewport coordinates of the containing Viewport (actually I am not entirely sure about that one)

In the editor this is in many cases not a problem, but can you please test, if this still works, if the editor uses a non-default scale?

Comment (Sauermann) [reply scene/gui/color_picker.cpp:1830]: Here is a MRP for stress-testing: [BugColorPicker.zip](https://github.com/godotengine/godot/files/10538275/BugColorPicker.zip)

I can have a look at the implementation regarding improvements, but unfortunately not right away.

Comment (MewPurPur) [reply scene/gui/color_picker.cpp:1830]: Aw, I kind of completely forgot this is a user-exposed thing. I'm honestly not sure what users would expect from it when they use it in their projects. But from a first glance at your test project, it doesn't look more broken than before

Comment (Sauermann) [reply scene/gui/color_picker.cpp:1830]: So it could be a valid approach to fix the editor-issue now and take care of the user-exposed problems at a later time.

**Comment by MewPurPur** [comment]
This bugfix leans on the enhancement side and isn't 100% safe. Should bump the milestone probably.

**Review by KoBeWi — APPROVED** [review]
The new behavior makes sense in the inspector.

**Review by Sauermann — APPROVED** [review]
I have tested this PR and it fixes the linked issue in the editor for me.
As mentioned in the comment above, there is an issue with mixing different coordinate systems, which will need to be fixed for cases where this functionality is used in projects with non-default-transforms. But since these cases are currently also problematic, this PR doesn't make these issues worse.
So all in all this PR improves the situation and fixes the most prominent use-case in the editor.

**Comment by akien-mga** [comment]
Thanks!
