### PR TITLE
Fix code folding when end of block is unindented delimiter

### LINKED ISSUE #55023: Odd and annoying code folding in script editor
### Godot version

v4.0.dev.20211108.official [596865366]

### System information

Windows 11, Ryzen 5 2600x, GTX 1080 TI, Vulkan

### Issue description

Godot 4.0 pre-alpha has weird and unpredictable code folding, It's safe to assume its broken.

The code folding does not respect whitespace, linebreaks or comments etc. 

I find the behavior unpredictable, if i click collapse on a code block, the editor will try and collapse so there is one line break before the next code block, unless there is a comment then it will collapse till there is no newline left.

Indented blocks also don't respect the level of indentation and will collapse code beneath its level.

Here is a video showing the broken behavior aswell as how it should be from another editor:

https://user-images.githubusercontent.com/36038081/141946814-a9d613af-1c62-4994-b877-5baa5544a4d5.mp4

### Steps to reproduce

Try and fold any sort of code, i have shared the test project but any will do.

### Minimal reproduction project

[Script testing.zip](https://github.com/godotengine/godot/files/7544456/Script.testing.zip)

### PR DESCRIPTION
**Pull request by ator-dev**
Fix #55023

I may be misunderstanding how Godot's code folding is supposed to work, but the behaviour implemented here seems fine to me:
- String and comment folding is unchanged apart from a small bug fix (folds from first character to terminating line)
- If not a string or comment, fold until the last line with a greater indent level, before a line with a less than or equal indent level
  - Comments and strings with a less than or equal indent level are ignored
  - Lines only containing whitespace are always ignored

I've tested this in several normal and weird situations, and all of these rules were followed correctly, although of course I could have missed one or two edge-case scenarios.

Please have a look at my description of the behaviour to make sure I'm not messing up Godot code folding, thanks  (;

### CODE REVIEW

**Comment by ator-dev** [comment]
I might need some help with the failing check - I'll have a look at it again later, but I at the moment I don't understand what's wrong. It tests the following code:
```
line1
	line2


	test

line3
```
by folding "line1" and checking if it folds up to "test" but not including "\nline3" afterwards. I have tested this in a working build and in my build, and the current behaviour seems both correct and unchanged by my edits.

**Comment by ator-dev** [comment]
As far as I can tell, the test at test_code_edit:2411 checks that an extra line is folded after the last character, which I think is strange folding behaviour; I have changed it to check that there is an offset of 5 lines (meaning that 4 have been folded) as opposed to 6. I'm not sure if this was the right thing to do, so am happy to change the test back and make the folding work differently if someone objects.

**Comment by Paulb23** [comment]
Could you add some unit tests for this use case?

**Comment by ator-dev** [comment]
I've not had any experience dealing with unit tests before, but I'll give it a go.

**Comment by ator-dev** [comment]
It took some figuring out, but I think I've managed to make some good tests for this  (:
They test for problems noted in #55023 as well as one or two other problems I noticed while implementing the fix. Unfortunately I haven't yet worked out how to run the tests myself, so for now I'll just wait for GitHub to do it automatically.

By the way, I noticed that a lot of the existing tests are same in many aspects but have a few differences, so could be implemented with a subroutine or loop instead. I'm guessing that this is intentional to make them clearer in some way? In any case, I followed the trend and added mine without additional loops.

**Comment by Paulb23** [comment]
Not sure if you've seen it already, but there's some docs on running unit tests locally here: https://docs.godotengine.org/en/latest/development/cpp/unit_testing.html

> By the way, I noticed that a lot of the existing tests are the same in many aspects but have a few differences so could be implemented with a subroutine or loop instead

Yeah most of the similarities are to cover interactions with both strings and comments. If I can remember correctly, I think originally the idea was to treat them as separate things.

**Comment by ator-dev** [comment]
> Not sure if you've seen it already, but there's some docs on running unit tests locally here: https://docs.godotengine.org/en/latest/development/cpp/unit_testing.html
> 
> > By the way, I noticed that a lot of the existing tests are the same in many aspects but have a few differences so could be implemented with a subroutine or loop instead
> 
> Yeah most of the similarities are to cover interactions with both strings and comments. If I can remember correctly, I think originally the idea was to treat them as separate things.

Thank you, I did try to find information on them previously - I'm not sure how I didn't find that page before!
Yeah, I thought it might be to do with testing strings and comments, and presumably it's preferable so you can immediately see which condition failed (i.e. from the line number). The decisions and workflow in Godot are starting to make more sense to me I think (:

File: tests/scene/test_code_edit.h [hunk 1]
```diff
@@ -2596,6 +2620,51 @@ TEST_CASE("[SceneTree][CodeEdit] folding") {
...
+		// Indent level 1->2, comment between lines
+		code_edit->set_text("\tline1\n#test\n\t\tline2\nline3");
+		CHECK(code_edit->can_fold_line(0));
+		CHECK_FALSE(code_edit->can_fold_line(2));
+		code_edit->fold_line(2);
+		CHECK_FALSE(code_edit->is_line_folded(2));
+		code_edit->fold_line(0);
+		CHECK(code_edit->is_line_folded(0));
+		CHECK_FALSE(code_edit->is_line_folded(2));
+		CHECK(code_edit->get_next_visible_line_offset_from(1, 1) == 3);
```
Comment (Paulb23) [inline tests/scene/test_code_edit.h:2667]: Can group with the other single line comment tests line `~2601`. I'll leave up to you whether this should also test single line strings and or multiline or if that's overkill.

File: scene/gui/code_edit.cpp [hunk 2]
```diff
@@ -1419,41 +1419,27 @@ void CodeEdit::fold_line(int p_line) {
...
-			if ((get_indent_level(i) <= start_indent && get_line(i).strip_edges().size() != 0)) {
-				/* Keep an empty line unfolded if any */
-				end_line = i - 1;
-				if (get_line(i - 1).strip_edges().size() == 0 && i - 2 > p_line) {
-					end_line = i - 2;
+			if (get_line(i).strip_edges().size() != 0) {
+				if (get_indent_level(i) > start_indent) {
+					end_line = i;
+					continue;
+				} else if (is_in_string(i) == -1 && is_in_comment(i) == -1) {
```
Comment (Paulb23) [inline scene/gui/code_edit.cpp:1440]: Nit: No need to `else if` can just `if` as we continue above.

File: scene/gui/code_edit.cpp [hunk 3]
```diff
@@ -1419,41 +1419,27 @@ void CodeEdit::fold_line(int p_line) {
...
-				}
-				break;
-			}
-
-			if ((get_indent_level(i) <= start_indent && get_line(i).strip_edges().size() != 0)) {
-				/* Keep an empty line unfolded if any */
-				end_line = i - 1;
-				if (get_line(i - 1).strip_edges().size() == 0 && i - 2 > p_line) {
-					end_line = i - 2;
+			if (get_line(i).strip_edges().size() != 0) {
```
Comment (Paulb23) [inline scene/gui/code_edit.cpp:1436]: Nit: Can invert this

**Review by Paulb23 — COMMENTED** [review]
Couple nit picks, otherwise looks good.

Could you add a more descriptive commit message, something like "Fixed code folding when end of block is un-indented delimiter"

Finally, your commit doesn't seem to have an email address associated with your GitHub account see the [patch](https://github.com/godotengine/godot/commit/e0beab0c3108f865f4cf22d7bbc5356260c27c77.patch). You need to add the email address to your GitHub account or update the commit  with the correct email address, to take ownership of them.

File: scene/gui/code_edit.cpp (hunk 2 above)
Comment (ator-dev) [reply scene/gui/code_edit.cpp:1440]: I actually don't like using `continue` and `break` as I find them less clear than if-elseif statements; it was in there originally and I forgot it was no longer needed. I'll remove that instead and leave the elseif, but tell me if you'd prefer your suggestion anyway (;

File: tests/scene/test_code_edit.h (hunk 1 above)
Comment (ator-dev) [reply tests/scene/test_code_edit.h:2667]: Good idea, I agree that would be better grouping. As for the additional testing - it would be good to fully make sure everything works, but I think cloning of these for multiline and strings would significantly clutter up the tests when these use cases are less common. In my opinion it's unlikely that the behaviour would get broken just for strings (or especially just for multiline).

File: scene/gui/code_edit.cpp (hunk 2 above)
Comment (Paulb23) [reply scene/gui/code_edit.cpp:1440]: That why it's `nit`, for me, `continue` and `break` are clearer :)

File: scene/gui/code_edit.cpp (hunk 3 above)
Comment (ator-dev) [reply scene/gui/code_edit.cpp:1436]: Could you clarify what you mean by this please?

Comment (Paulb23) [reply scene/gui/code_edit.cpp:1436]: Sure, invert the condition so it becomes:
```
...
if (get_line(i).strip_edges().size() == 0) {
    continue;
}
...
```

File: scene/gui/code_edit.cpp (hunk 2 above)
Comment (ator-dev) [reply scene/gui/code_edit.cpp:1440]: Ah, ok. Now changed; I'll make sure to consider them more often when contributing

File: scene/gui/code_edit.cpp (hunk 3 above)
Comment (ator-dev) [reply scene/gui/code_edit.cpp:1436]: Thanks, now added  :)

**Comment by ator-dev** [comment]
@Paulb23 I've just reformatted both loops to improve readability and comply with your style suggestions (which I've also seen in other areas of the engine, making it hopefully more consistent). I had some trouble with the username and email though; I changed it but now it shows up as this:
image
I'll try to work out what's gone wrong, but it might just stay like that for now.

**Review by Paulb23 — APPROVED** [review]
Thanks for the contribution! 

LGTM.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by ator-dev** [comment]
You're welcome, thanks!
I actually had my first merged a few days ago, but I think I messed up my commit email so maybe it didn't get counted.
