### PR TITLE
Fix base 16 hex literal parsing

### LINKED ISSUE #32963: Parser won't accept a Base 16 hex literal with a lower case b
**Godot version:**
Godot Engine v3.2.alpha.custom_build.3e782c78a - https://godotengine.org
OpenGL ES 3.0 Renderer: AMD Radeon R9 M370X OpenGL Engine

**OS/device including version:**
macOS Mojave 10.14.6 

**Issue description:**

Including a lower case b returns this error in the editor and when you run.

`Parser Error: Parse error: Invalid numeric constant at 'b'`

Changing it to an upper case b removes the error.

**Steps to reproduce:**

Assign a hex integer with a lower case b to a variable.

**Minimal reproduction project:**

New Project
Add Node2D
Save as main
Create new script, main.gd

```
extends Node2D

var x = 0xabcdef

```
Save and run to get the error.

If you change it to

```
extends Node2D

var x = 0xaBcdef

```

The project will successfully run.

### PR DESCRIPTION
**Pull request by ffaristocrat**
Fixes #32963

The change to support binary literals resulted in lower case b's in hex literals throwing a parse error.

### CODE REVIEW

File: modules/gdscript/gdscript_tokenizer.cpp [hunk 1]
```diff
@@ -937,8 +937,10 @@ void GDScriptTokenizerText::_advance() {
 								return;
 							}
 							hexa_found = true;
+						} else if (hexa_found && _is_hex(GETCHAR(i))) {
+
 						} else if (GETCHAR(i) == 'b') {
```
Comment (bojidar-bg) [inline modules/gdscript/gdscript_tokenizer.cpp]: What about doing it the same way as the next if? (or alternatively, removing `!hexa_found` from there as well)
```suggestion
						} else if (!hexa_found && GETCHAR(i) == 'b') {
```

Comment (ffaristocrat) [reply modules/gdscript/gdscript_tokenizer.cpp]: Yeah. It's unnecessary right now but better to be explicit in case the order gets changed accidentally.

File: modules/gdscript/gdscript_tokenizer.cpp [hunk 2]
```diff
@@ -937,8 +937,10 @@ void GDScriptTokenizerText::_advance() {
 								return;
 							}
 							hexa_found = true;
-						} else if (GETCHAR(i) == 'b') {
-							if (hexa_found || bin_found || str.length() != 1 || !((i == 1 && str[0] == '0') || (i == 2 && str[1] == '0' && str[0] == '-'))) {
+						} else if (hexa_found && _is_hex(GETCHAR(i))) {
```
Comment (bojidar-bg) [inline modules/gdscript/gdscript_tokenizer.cpp]: Why was this moved though?

Comment (ffaristocrat) [reply modules/gdscript/gdscript_tokenizer.cpp]: One of things that caused this bug is the order of the checks. And if it's already in a hex literal and it's a hex character, better to move on sooner than to spend time on checks later.

**Comment by vnen** [comment]
Looks good to me, but it can be a single commit. So please squash the two commits as described here: http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

You can take the opportunity to reword the commit message too. It should [describe the issue that it's fixing and why it works](https://chris.beams.io/posts/git-commit/#seven-rules), not the code change itself (because we can see the code change anyway in the diff).

**Comment by akien-mga** [comment]
> So please squash the two commits

Bump.

**Comment by ffaristocrat** [comment]
Alright, finally smashed this into one commit.

**Comment by akien-mga** [comment]
Thanks!
