### PR TITLE
C#: Add global class support

### LINKED ISSUE #18: Add first-class custom resource support
**Describe the project you are working on:**
Data-heavy RPG

**Describe how this feature / enhancement will help your project:**
I have a lot of different structures in my game which represent various different things, such as healing items, equipment, party members, item/character stats, enemies, and so on.  To make it easy for designers/modders to add and change this data, these are represented through extending `Resource`, which, combined with `class_name`, allows you to easily create `.tres` files containing exported variables that can be assigned to in the inspector.  So to modify data, one can double-click some file in the file system, glance over to the inspector, and easily change properties this way, leveraging all the various options associated with `export`.

image

This works, but only up to a point.  Let's say, I now want all of my party members, equipment, and enemies to have a set of stats associated with them.  I can write a stats class like so:

```
extends Resource
class_name Stats

export var strength: float
export var defense: float
...more stats
```

And now I can just do the following in all the associated scripts, and get to modify that data as I would with any other resource:
```
export(Stats) var stats = Stats.new()
```

...except, unfortunately, that doesn't work, as Godot will throw an error about not recognizing `Stats` as a `Resource`, though we see that Stats, due to extending Resource, should count as one.  This works with any resource the engine ships with:

```
export(Texture) var tex
export(AudioStream) var stream
export(Shape2D) var shape
```

And you even get a little menu to create a new resource:

image

But, sadly, the engine rejects `Stats` as being something entirely different.  If there was support for this kind of resource, we should be able to see a menu something like this, after the menu to create a new `Stats` resource:

image

Which would alleviate all the work-arounds outlined below.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

```
export(Stats) var stats
or
export var stats: Stats
```

stats_mock

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

In short: no, just the opposite, it requires a lot more code to be written to work around this inhibition, or requires a tedious process to add a custom resource to the inspector.

The fundamental issue is the current inability for the user to simply export a resource of their own creation.  We are left with the following options:

Brute Force
```
#unnamed and unstructured, no guarantees of anything
export(Array, float) var stats
export(Array, Array, String) var combat_messages
#this one's especially painful, where you need multiple types in one array
export(Array) var mixed_data
#...but nothing compares to this, besides the dictionary variation
export(Array, Array) var lots_of_mixed_data

#named but unstructured, and you have to name them for every dictionary added in the latter example, no autocomplete
export(Dictionary) var stats := {"strength" : 0.0, "defense" : 0.0, ...}
export(Array, Dictionary) var god_help_you_if_you_do_this
```

The OmniResource
```
#named, structured, autocompleted (if you cast)
#necessitates a process where you create the custom resource then copy it over (after scrolling through the ginormous list of resources this gives you), or save it to the system and drag and drop
export(Resource) var not_as_it_seems
```
image

Do Repeat Yourself
```
#player_character.gd
export var strength: float
export var defense: float
...

#enemy.gd
export var strength: float
export var defense: float
...

#equipment.gd
export var start_strength: float
export var start_defense: float
...
export var upgraded_strength: float
export var upgraded_defense: float
...
```

Forget About It!
```
#my_character.gd
func get_character() -> PlayerCharacter:
    var player_character = PlayerCharacter.new()
    player_character.stats = Stats.new()
    player_character.stats.strength = 7
    ...
    return player_character

#character_defs.gd
func get_characters() -> Array:
   ...

#loader.gd
func load_character(path_to_json) -> PlayerCharacter:
    ...turning json back into an object logic...
```

There's the opportunity to build an inspector plugin or use `_get_property_list()`, both of which require quite a bit of code and technical know-how, on a per-resource basis.  Based on what people have told me in the discord, it's a painful process (at least with property list) which they seek to avoid in the future.  We could also go into C++ land and build modules for the engine to understand our data types, but again, it's a lot of code, and beyond the skill level of many of us who haven't delved into the engine code (assuming we know C++ at all); even if it were easily understood by anyone, or you know what you're doing, it's still many magnitudes more work than `export var my_res: MyRes` working out of the box.

It takes a lot of code, or unsafe code, or bad programming practices, or a tiresome process to make up for functionality that Godot already provides, leaving many of us to reinvent the wheel time and time again if we want this functionality.  If exporting a custom resource Just Worked, lots of time, energy and headaches would be saved.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I don't believe first-class support for custom resources would constitute as bloat.  I believe it's an essential but missing feature for all games which require any kind of user-created resource type, for anyone who needs to export a bundle of named data with type safety, for anyone who wants to associate their own resource type with their own node type, for anyone who needs complex but easily modified data saved to disk; since virtually every game made with Godot makes use of Resources, every developer would benefit from this, if not by a little, by a lot.

### LINKED ISSUE #26875: Unable to register scripts using C#
**Godot version:**

3.1rc1

**OS/device including version:**

Linux

**Issue description:**

Class name and icon features don't seem to be working with C#/Mono.

**Steps to reproduce:**
I tried adding functions GetClassName() and GetScriptClassIconPath() to a C# script but didn't work (is this how it's supposed to work?).

**Minimal reproduction project:**

### LINKED ISSUE #69795: [C#] Godot can't find C# mainloop
### Godot version

4.0 beta 4 and beta 7

### System information

Windows 10

### Issue description

Godot can't find the C# mainloop, but if create a GDScript variant, then everything works

### Steps to reproduce

Create C# script and inherit it from the mainloop and specify it in the settings.

### Minimal reproduction project

[TestProject.zip](https://github.com/godotengine/godot/files/10192058/TestProject.zip)

### PR DESCRIPTION
**Pull request by raulsntos**
Port of https://github.com/godotengine/godot/pull/63126 originally implemented by @willnationsdev to the current `master`.

Adds support for C# to be able to define global classes using the `[GlobalClass]` attribute and export global script classes using the `[Export]` attribute.

### Differences from the original PR

- The additional `ExportAttribute` constructor is not included.
	- It seems this did not make it in the GDScript version either and I think it may be better as a separate attribute anyway.
- The `[Global]` attribute was renamed to `[GlobalClass]`.
	- I think the original name was a bit too vague, but to be honest I'm also not very happy with the new name either. I'll gladly take suggestions.
- The `[GlobalClass]` attribute always uses the name of the C# class.
	- The original implementation allowed specifying a different name but I don't think that's useful in C# where classes already have names.
- The `[GlobalClass]` attribute does not contain the icon path, a separate `[Icon]` attribute is provided.
	-  The `[Icon]` attribute allows specifying the path to the icon of a C# class similar to the `@icon` annotation in GDScript.
	- This allows specifying an icon even when the class is not registered as a global class.
- The `EditorFileSystem::update_file` call was moved from `CSharpLanguage::reload_assemblies` to `ScriptManagerBridge.LookupScriptsInAssembly`.
	- The original implementation wasn't working properly, global script classes weren't getting registered when they should.
	- @neikeq helped me figure out how to make it work.

### Related issues and PRs

- Fixes https://github.com/godotengine/godot-proposals/issues/18 for C#.
- Closes https://github.com/godotengine/godot/pull/63126 as superseded.
- Fixes https://github.com/godotengine/godot/issues/69795.
- Fixes https://github.com/godotengine/godot/issues/26875.
- Closes https://github.com/godotengine/godot/pull/48056 as superseded.

### CODE REVIEW

**Comment by willnationsdev** [comment]
> The [GlobalClass] attribute always uses the name of the C# class.
> 
> The original implementation allowed specifying a different name but I don't think that's useful in C# where classes already have names.

Haven't had time to actually review it yet, but I will mention now that the reason I had made the mapped Godot name customizable (but defaulting to the C# class name) was because Reduz mentioned having no intention of introducing namespacing into Godot's centralized user types. If people start namespacing their types using underscored prefixes and the like (`MyLib_MyNode`), you don't want that forcing C# users to have to adopt an identical pattern for whatever reason just to create a C# class that follows the same convention as some other library to preserve consistency in the Godot user interface. Hence, the ability for users to manually set the name to whatever they really want it to be should the need arise.

**Comment by raulsntos** [comment]
I haven't thought about that, but assuming the user's class is inside a namespace we could probably combine the class name with its namespace to register it as a global class and that'd be less likely to conflict. We could also add the ability to customize the name in the future without breaking compatibility so I'd prefer not yo add it for the first implementation.

File: modules/mono/glue/runtime_interop.cpp [hunk 1]
```diff
@@ -304,6 +308,14 @@ void godotsharp_internal_new_csharp_script(Ref<CSharpScript> *r_dest) {
 	memnew_placement(r_dest, Ref<CSharpScript>(memnew(CSharpScript)));
 }
 
+void godotsharp_internal_editor_file_system_update_file(const String *p_script_path) {
+#if TOOLS_ENABLED
+	EditorFileSystem::get_singleton()->update_file(*p_script_path);
```
[the remark this answers is not in the document]
Comment (raulsntos) [reply modules/mono/glue/runtime_interop.cpp]: It should be fixed now. I check if `EditorFileSystem::get_singleton()` returns `nullptr` and in that case the method does nothing, because when the `EditorFileSystem` becomes available it will update the files itself, so it should be fine.

[the remark this answers is not in the document]
Comment (RedworkDE) [reply modules/mono/glue/runtime_interop.cpp]: Resolved.

**Comment by RedworkDE** [comment]
Some actual testing later:
1. Things generally seem to work fine.
2. `ResourceLoader.Load<GlobalResource>()`  throws a InvalidCastException when loading a resource:
```cs
[GlobalClass]
public partial class ResCS : Resource
{
	[Export]
	public string Name;
}
```

```cs
try
{
	OS.Alert(ResourceSaver.Save(new ResCS() { Name = "string" }, "res://rcs.tres").ToString());
	OS.Alert(ResourceLoader.Load<ResCS>("res://rcs.tres").Name);
}
catch (Exception ex)
{
	OS.Alert(ex.ToString());
}
```
3. When using custom resource loaders and savers, they will sometimes not get reregistered, but I have not narrowed down what exactly the issue is. It is somewhat related to https://github.com/godotengine/godot/blob/604493eb6ee3def65aca089c1d4bc71ea03ca19a/editor/editor_file_system.cpp#L1582-L1588 because without global classes they always get removed there and never readded, so the build I normally use has those lines commented out. With this PR the loaders (marked as GlobalClass) usually survive the script update, but not always.

**Comment by RedworkDE** [comment]
[OutputTest.zip](https://github.com/godotengine/godot/files/10608334/OutputTest.zip)
Also includes the rest of the project and a GDScript version that (if my understanding of typed GDScript is correct) should be equivalent and works fine.

**Comment by raulsntos** [comment]
OK, I think I understand what you meant now. Your `maincs.cs` script is `[Tool]` so the script is executed in the editor, when opening the main scene that has the script attached the `_Ready` method is invoked. However, because the `RelCS` class is not marked as `[Tool]` it's not recognized by the editor, non-Tool scripts are loaded as `Resource`. This is an existing limitation and not related to this PR. If you want your resource types to be available in the editor you need to annotate them with the `[Tool]` attribute as well.

**Comment by RedworkDE** [comment]
Point 3 also boils down to user error / missing `[Tool]` annotations. For some reason at startup, ResourceFormatLoader / Saver without tool are registered and used; but after a file system reload loaders without tool are not reregistered and their files disappear.

While debugging this I found one additional oddity: The global class list (in the debugger and the contains types not marked as `[GlobalClass]` one derived from `EditorPlugin` and one from `ScriptLanguageExtension`, tho I am unsure if this is an issue or expected behavior.

**Comment by raulsntos** [comment]
> Point 3 also boils down to user error / missing `[Tool]` annotations.

I think global classes should be registered regardless of having the `[Tool]` annotation, I think that's how it works in GDScript, scripts with `class_name` don't need to have the `@tool` annotation to be registered as a global class.

Also, in my testing classes were sometimes unregistered even if they had the `[Tool]` annotation, so it doesn't seem related to me.

> While debugging this I found one additional oddity: The global class list (in the debugger and the new method added on master) contains types not marked as `[GlobalClass]`

That's odd, while testing I have also been able to see some classes without the `[GlobalClass]` attribute added to the global classes list, I have looked at the current GDScript implementation of `get_global_class_name` and I have changed the C# implementation to follow it more closely.

I also realized I wasn't assigning some out parameters in `ScriptManagerBridge.UpdateScriptClassInfo` in the `catch` block. I don't think this is related to the issues mentioned above since I didn't see any exception logged in the console so the `catch` block wasn't reached.

**Comment by dotlogix** [comment]
Does this PR also allow us now to export custom node types as classes or is it an unrelated issue?
It would be really nice to finally be able to do that especially for theming :)

**Comment by raulsntos** [comment]
This PR should allow you to use any C# class derived from `Node` or `Resource` registered with the `[GlobalClass]` attribute in any of the contexts where you can use a GDScript class named with the `class_name` syntax. This means it should show up in the _Add Node_ and _Create Resource_ dialogs. Exporting custom resources (i.e.: a type that derives from `Resource` with the `[GlobalClass]` attribute) should also restrict the types of resource that can be assigned in the inspector and will let you create and load instances of that resource type more easily.

I don't have screenshots from this PR, but these screenshots from the related GDScript PR and the [GDScript documentation for named classes](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#registering-named-classes) should give you an idea of where these C# global classes would show up:

image

image

**Comment by bleuthoot-sven** [comment]
I have been testing this build for a short while and noticed this bug:

- When creating a resource and adding the `[GlobalClass]` attribute to it, doesn't make it available for use in a node `[Export]` variable unless I restart Godot.


https://user-images.githubusercontent.com/25549100/216987831-0d7df275-2bd9-44ff-a05b-2e88db4ea4de.mp4

Project I used:
[CSharp Test.zip](https://github.com/godotengine/godot/files/10663648/CSharp.Test.zip)

**Comment by raulsntos** [comment]
The `EditorFileSystem->update_file` method was being called on `LookupScriptsInAssembly` which is called when the assembly is loaded, but it seems this may be too soon and the script is still not valid and not added to the `ScriptTypeBiMap` so the base ended up empty. I have now added `EditorFileSystem->update_file` calls to the `CSharpScript::reload` and `CSharpScript::reload_registered_script` methods after the script becomes valid.

@bleuthoot-sven Thanks for testing, I think this issue may be fixed now, can you try the latest version of this PR? It's in commit 5f73edd5d94cdf659fd842410f3b605cab73cbc5, also make sure to clear the GodotNuGetFallbackFolder directory.

**Comment by bleuthoot-sven** [comment]
> The `EditorFileSystem->update_file` method was being called on `LookupScriptsInAssembly` which is called when the assembly is loaded, but it seems this may be too soon and the script is still not valid and not added to the `ScriptTypeBiMap` so the base ended up empty. I have now added `EditorFileSystem->update_file` calls to the `CSharpScript::reload` and `CSharpScript::reload_registered_script` methods after the script becomes valid.
> 
> @bleuthoot-sven Thanks for testing, I think this issue may be fixed now, can you try the latest version of this PR? It's in commit [5f73edd](https://github.com/godotengine/godot/commit/5f73edd5d94cdf659fd842410f3b605cab73cbc5), also make sure to clear the GodotNuGetFallbackFolder directory.

Yup, seems to work fine now.

I have one additional question that is very likely not related to this PR.

When adding a resource to a node `[Export]` variable, the field will return to `<empty>` when I reselect the node. This not only happens in C#, but also with GDScript.

Is this intentional or a (known) issue?

**Comment by raulsntos** [comment]
> When adding a resource to a node `[Export]` variable, the field will return to `<empty>` when I re-select the node. This not only happens in C#, but also with GDScript.

If it also happens in GDScript, then it seems like the issue is in the inspector code. So it's out of scope for this PR.

File: modules/mono/csharp_script.cpp [hunk 2]
```diff
@@ -2207,11 +2250,16 @@ void CSharpScript::reload_registered_script(Ref<CSharpScript> p_script) {
 	update_script_class_info(p_script);
 
 	p_script->_update_exports();
+
+#if TOOLS_ENABLED
+	EditorFileSystem::get_singleton()->update_file(p_script->get_path());
```
Comment (RedworkDE) [inline modules/mono/csharp_script.cpp:2255]:
```suggestion
	// If the EditorFileSystem singleton is available, update the file;
	// otherwise, the file will be updated when the singleton becomes available.
	EditorFileSystem *efs = EditorFileSystem::get_singleton();
	if (efs) {
		efs->update_file(p_script->get_path());
	}
```

efs can be null here as well during resource loader initialization.

Not sure the one in reload can also hit this issue, I didn't crash there during my testing.

(Not sure what I am doing to hit all of these)

**Comment by RedworkDE** [comment]
Fixes https://github.com/godotengine/godot/issues/69795

File: modules/mono/csharp_script.cpp (hunk 2 above)
Comment (raulsntos) [reply modules/mono/csharp_script.cpp:2255]: I thought I had tested well enough, but you are right I missed this. I changed the one in `reload` as well, just to be safe.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs [hunk 3]
```diff
@@ -298,6 +298,12 @@ static void LookupScriptForClass(Type type)
 
                 _pathTypeBiMap.Add(scriptPathAttr.Path, type);
 
+                if (Engine.IsEditorHint())
```
Comment (RedworkDE) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:301]: I found another one! This crashes in exported projects because this is reached before `InitializeFromGameProject` returns and managed callbacks get set.

Stack:

```
 	Net7.exe!CSharpLanguage::setup_csharp_script_binding(CSharpScriptBinding & r_script_binding, Object * p_object) Line 1269	C++
 	Net7.exe!CSharpLanguage::get_instance_binding(Object * p_object) Line 1437	C++
 	Net7.exe!godotsharp_internal_unmanaged_get_instance_binding_managed(Object * p_unmanaged) Line 236	C++
 	[Managed to Native Transition]	
 	GodotSharp.dll!Godot.NativeInterop.InteropUtils.UnmanagedGetManaged(System.IntPtr unmanaged) Line 35	C#
 	GodotSharp.dll!Godot.NativeInterop.InteropUtils.EngineGetSingleton(string name) Line 93	C#
 	GodotSharp.dll!Godot.Engine.Singleton.get() Line 122	C#
 	GodotSharp.dll!Godot.Engine.IsEditorHint() Line 526	C#
>	GodotSharp.dll!Godot.Bridge.ScriptManagerBridge.LookupScriptsInAssembly.__LookupScriptForClass|13_0(System.Type type) Line 299	C#
 	GodotSharp.dll!Godot.Bridge.ScriptManagerBridge.LookupScriptsInAssembly(System.Reflection.Assembly assembly) Line 352	C#
 	Net7.dll!GodotPlugins.Game.Main.InitializeFromGameProject(System.IntPtr godotDllHandle, System.IntPtr outManagedCallbacks, System.IntPtr unmanagedCallbacks, int unmanagedCallbacksSize) Line 26	C#
 	[Native to Managed Transition]	
 	Net7.exe!GDMono::initialize() Line 430	C++
 	Net7.exe!CSharpLanguage::init() Line 133	C++
 	Net7.exe!ScriptServer::init_languages() Line 214	C++
 	Net7.exe!Main::setup2(unsigned __int64 p_main_tid_override) Line 2318	C++
 	Net7.exe!Main::setup(const char * execpath, int argc, char * * argv, bool p_second_phase) Line 1848	C++
 	Net7.exe!widechar_main(int argc, wchar_t * * argv) Line 164	C++
 	Net7.exe!_main() Line 205	C++
 	Net7.exe!main(int argc, char * * argv) Line 217	C++
 	[Inline Frame] Net7.exe!invoke_main() Line 102	C++
 	Net7.exe!__scrt_common_main_seh() Line 288	C++
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown
```

Project is nothing specific, just a single scene with a node with a script that does nothing.

**Comment by paulloz** [comment]
Crashes when you try to interact with something using `[GlobalClass]` if there's a generic in the hierarchy. For instance, the following (`[MustBeVariant]` being here or not doesn't make a difference):
```cs
// Foo.cs
public partial class Foo<[MustBeVariant] T> : Resource
{
}

// Bar.cs
[GlobalClass]
public partial class Bar : Foo<string>
{
}
```

Stack trace when trying to open the "New Resource..." window, but also does the same when selecting a node that happen to export `Bar`, etc.:
```
ERROR: Resource file not found: res://.
   at: (core\io\resource_loader.cpp:226)

================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.0.rc.mono.custom_build (25f7ddbf3f285358227c4415955a09f9e8c4b1d8)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] CSharpLanguage::get_global_class_name (E:\Godot Worktree\godot\modules\mono\csharp_script.cpp:552)
[1] CreateDialog::_add_type (E:\Godot Worktree\godot\editor\create_dialog.cpp:251)
[2] CreateDialog::_update_search (E:\Godot Worktree\godot\editor\create_dialog.cpp:190)
[3] CreateDialog::popup_create (E:\Godot Worktree\godot\editor\create_dialog.cpp:59)
[4] FileSystemDock::_file_option (E:\Godot Worktree\godot\editor\filesystem_dock.cpp:2088)
[5] FileSystemDock::_tree_rmb_option (E:\Godot Worktree\godot\editor\filesystem_dock.cpp:1794)
[6] call_with_variant_args_helper<FileSystemDock,int,0> (E:\Godot Worktree\godot\core\variant\binder_common.h:298)
[7] call_with_variant_args<FileSystemDock,int> (E:\Godot Worktree\godot\core\variant\binder_common.h:408)
[8] CallableCustomMethodPointer<FileSystemDock,int>::call (E:\Godot Worktree\godot\core\object\callable_method_pointer.h:105)
[9] Callable::callp (E:\Godot Worktree\godot\core\variant\callable.cpp:51)
[10] Object::emit_signalp (E:\Godot Worktree\godot\core\object\object.cpp:1047)
[11] Object::emit_signal<int> (E:\Godot Worktree\godot\core\object\object.h:869)
[12] PopupMenu::activate_item (E:\Godot Worktree\godot\scene\gui\popup_menu.cpp:1723)
[13] PopupMenu::gui_input (E:\Godot Worktree\godot\scene\gui\popup_menu.cpp:432)
[14] call_with_variant_args_helper<PopupMenu,Ref<InputEvent> const &,0> (E:\Godot Worktree\godot\core\variant\binder_common.h:293)
[15] call_with_variant_args<PopupMenu,Ref<InputEvent> const &> (E:\Godot Worktree\godot\core\variant\binder_common.h:408)
[16] CallableCustomMethodPointer<PopupMenu,Ref<InputEvent> const &>::call (E:\Godot Worktree\godot\core\object\callable_method_pointer.h:105)
[17] Callable::callp (E:\Godot Worktree\godot\core\variant\callable.cpp:51)
[18] Object::emit_signalp (E:\Godot Worktree\godot\core\object\object.cpp:1047)
[19] Object::emit_signal<Ref<InputEvent> > (E:\Godot Worktree\godot\core\object\object.h:869)
[20] Window::_window_input (E:\Godot Worktree\godot\scene\main\window.cpp:1368)
[21] call_with_variant_args_helper<Window,Ref<InputEvent> const &,0> (E:\Godot Worktree\godot\core\variant\binder_common.h:293)
[22] call_with_variant_args<Window,Ref<InputEvent> const &> (E:\Godot Worktree\godot\core\variant\binder_common.h:408)
[23] CallableCustomMethodPointer<Window,Ref<InputEvent> const &>::call (E:\Godot Worktree\godot\core\object\callable_method_pointer.h:105)
[24] Callable::callp (E:\Godot Worktree\godot\core\variant\callable.cpp:51)
[25] DisplayServerWindows::_dispatch_input_event (E:\Godot Worktree\godot\platform\windows\display_server_windows.cpp:2314)
[26] DisplayServerWindows::_dispatch_input_events (E:\Godot Worktree\godot\platform\windows\display_server_windows.cpp:2279)
[27] Input::_parse_input_event_impl (E:\Godot Worktree\godot\core\input\input.cpp:690)
[28] Input::flush_buffered_events (E:\Godot Worktree\godot\core\input\input.cpp:941)
[29] DisplayServerWindows::process_events (E:\Godot Worktree\godot\platform\windows\display_server_windows.cpp:2008)
[30] OS_Windows::run (E:\Godot Worktree\godot\platform\windows\os_windows.cpp:1296)
[31] widechar_main (E:\Godot Worktree\godot\platform\windows\godot_windows.cpp:181)
[32] _main (E:\Godot Worktree\godot\platform\windows\godot_windows.cpp:203)
[33] main (E:\Godot Worktree\godot\platform\windows\godot_windows.cpp:217)
[34] WinMain (E:\Godot Worktree\godot\platform\windows\godot_windows.cpp:231)
[35] __scrt_common_main_seh (d:\a01\_work\43\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[36] <couldn't map PC to fn name>
-- END OF BACKTRACE --
================================================================
```

**Comment by Shadowblitz16** [comment]
Is this still planned for 4.1?
It makes C# pretty useless as a editor language if we can't make global resources and classes

**Comment by Thed13** [comment]
Sorry for the bump, but i saw someone on the discord waiting for this feature.

**Comment by Calinou** [comment]
@Thed13 Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by mazingtech** [comment]
Just out of curious, C# developers has been crying for custom resource almost 5 years(there is a issue opened in 2019), when will they are able to use this [GlobalClass] to make some actually games?

**Comment by akien-mga** [comment]
@mazingtech There was a comment 12 hours before yours explicitly saying not to comment like you did.

Passive aggressive rants don't make PRs magically get reviewed. If you want this to go faster, you can help test it, or review the code.

**Comment by mazingtech** [comment]
> @mazingtech There was a comment 12 hours before yours explicitly saying not to comment like you did.
> 
> Passive aggressive rants don't make PRs magically get reviewed. If you want this to go faster, you can help test it, or review the code.

Sorry about the "Passive aggressive rants". Actually, how disappointed we are now depends on how much we loved godot, 5 years is not a short time after all. All the best.

**Comment by Damnae** [comment]
Sorry to add to the random comments, but what's blocking this right now, is it waiting for review, or for the original contributor to reply to something? Is there something in particular that needs to be solved, outside of the merge conflicts?

**Comment by raulsntos** [comment]
I haven't had much time to work on this lately but I've been slowly getting back to it. I haven't fixed all the issues that were reported yet, specifically the one mentioned in https://github.com/godotengine/godot/pull/72619#discussion_r1103583164.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs (hunk 3 above)
Comment (raulsntos) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs]: To fix this I've added a method to check if the .NET module is initialized (`godotsharp_dotnet_module_is_initialized`).

**Comment by RedworkDE** [comment]
I briefly tested the current state and didn't manage to immediately crash it again (or find any glaring issues), I'll take a deeper look later.

**Comment by markdibarry** [comment]
Tested a few scenarios in a new project and an existing one. No problems. Looks good!
image

File: modules/mono/mono_gd/gd_mono.h [hunk 4]
```diff
@@ -59,6 +59,7 @@ struct PluginCallbacks {
 } // namespace gdmono
 
 class GDMono {
+	bool initialized;
```
Comment (RedworkDE) [inline modules/mono/mono_gd/gd_mono.h:62]: This needs to be initialized in the constructor or the crash this tries to fix happens anyways (at least in asan builds)

Tho I would maybe just move all the zeroing out of the constructor and into member initializers.

**Review by RedworkDE — COMMENTED** [review]
Generally LGTM otherwise, is probably in a state where it could be merged and improved in followups when issues crop up.

I tested with custom resources, nodes, resource loader and main loops.

I encountered two minor somewhat related issues:
```
ERROR: Script does not inherit a CustomResourceLoader: res://res_loader.cs.
   at: (core\io\resource_loader.cpp:1104)
```
Appears a few times when (re-)loading assemblies, but the resource loaded worked just fine anyways.
Loader in question:
```
using Godot;
using System;

[GlobalClass]
[Tool]
public partial class res_loader : ResourceFormatLoader
{
	public override string[] _GetRecognizedExtensions() => new[] { "test_res" };
	public override Variant _Load(string path, string originalPath, bool useSubThreads, int cacheMode) => new res3();
}
```

And one times when exiting the editor I got the error as some scripts apparently survived the language, tho not sure if that is actually related to this PR:
```
ERROR: FATAL: DEV_ASSERT failed  "_first == nullptr" is false.
   at: SelfList<class CSharpScript>::List::~List (C:\dir\godot_3\core/templates/self_list.h:114)

================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.1.dev.mono.custom_build (e46806eb86f3bc0ad65ff303a57456a2185d6c4a)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] SelfList<CSharpScript>::List::~List (C:\dir\godot_3\core\templates\self_list.h:114)
[1] CSharpLanguage::~CSharpLanguage (C:\dir\godot_3\modules\mono\csharp_script.cpp:1235)
[2] CSharpLanguage::`scalar deleting destructor'
[3] uninitialize_mono_module (C:\dir\godot_3\modules\mono\register_types.cpp:74)
[4] uninitialize_modules (C:\dir\godot_4.0.1\modules\register_module_types.gen.cpp:279)
[5] Main::cleanup (C:\dir\godot_3\main\main.cpp:3566)
[6] widechar_main (C:\dir\godot_3\platform\windows\godot_windows.cpp:183)
[7] _main (C:\dir\godot_3\platform\windows\godot_windows.cpp:205)
[8] main (C:\dir\godot_3\platform\windows\godot_windows.cpp:217)
[9] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[10] <couldn't map PC to fn name>
-- END OF BACKTRACE --
================================================================
```

**Comment by GeorgeS2019** [comment]
@raulsntos 

We are trying to create a[ c# binding to GDExtension Google Mediapipe. ](https://github.com/j20001970/GDMP-demo/discussions/6#discussioncomment-6029012)
If I understand correctly, this is the PR

File: modules/mono/glue/runtime_interop.cpp [hunk 5]
```diff
@@ -304,6 +312,19 @@ void godotsharp_internal_new_csharp_script(Ref<CSharpScript> *r_dest) {
...
+void godotsharp_internal_editor_file_system_update_file(const String *p_script_path) {
+#if TOOLS_ENABLED
+	// If the EditorFileSystem singleton is available, update the file;
+	// otherwise, the file will be updated when the singleton becomes available.
+	EditorFileSystem *efs = EditorFileSystem::get_singleton();
+	if (efs) {
+		efs->update_file(*p_script_path);
+	}
+#else
+	CRASH_NOW_MSG("EditorFileSystem is only available when running in the Godot editor.");
```
Comment (akien-mga) [inline modules/mono/glue/runtime_interop.cpp:324]: We could add a `DEV_ASSERT`, but for production user templates is it really worth crashing instead of just erroring out? Or is it impossible to recover once we're here?

**Review by akien-mga — APPROVED** [review]
I'm no expert on the C# integration, but the scope of the changes looks sensible to me, and this was well tested and reviewed by @RedworkDE. 

Would love to get @neikeq's eyes on it too to give more confidence that this is the right approach, but I think we can benefit a lot from merging this this week to include in 4.1 dev 4 for wider testing, so we can polish in the beta phase.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/NativeFuncs.cs [hunk 6]
```diff
@@ -37,6 +37,8 @@ private partial struct UnmanagedCallbacks
 
         // Custom functions
 
+        internal static partial bool godotsharp_dotnet_module_is_initialized();
```
Comment (RedworkDE) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/NativeFuncs.cs:40]:
```suggestion
        internal static partial godot_bool godotsharp_dotnet_module_is_initialized();
```

We had that one a few days ago, lets not reintroduce that type of crash.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs [hunk 7]
```diff
@@ -298,6 +298,13 @@ static void LookupScriptForClass(Type type)
 
                 _pathTypeBiMap.Add(scriptPathAttr.Path, type);
 
+                // This method may be called before initialization.
+                if (NativeFuncs.godotsharp_dotnet_module_is_initialized() && Engine.IsEditorHint())
```
Comment (RedworkDE) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:302]:
```suggestion
                if (NativeFuncs.godotsharp_dotnet_module_is_initialized().ToBool() && Engine.IsEditorHint())
```

File: modules/mono/glue/runtime_interop.cpp (hunk 5 above)
Comment (RedworkDE) [reply modules/mono/glue/runtime_interop.cpp:324]: It is only called behind a IsEditorHint check, so it should be unreachable unless someone messes around with reflection (except that the check would have crashed again, so good that you commented and I double checked)

Thb calling this outside the editor means just that there is a logic error in the caller, so a DEV_ASSERT or just a normal ERR_FAIL would be enough here.

Comment (raulsntos) [reply modules/mono/glue/runtime_interop.cpp]: It is as RedworkDE says, this code path should be unreachable so I used a crash because a user should never see it anyway. But it makes sense to me to use a `DEV_ASSERT` too so I changed it. Let me know if the check is backwards.

**Comment by YuriSizov** [comment]
Congratulations everyone and big thanks to Raul and Will for the work they've put into giving our C# users a powerful feature and parity with GDScript users! Let's catch all the bugs during the bug-fixing phase and send this to everyone in one month with the stable release 🎉

**Comment by cpuccino** [comment]
Bit late to the party but is there any chance we can change the name to something like `RegisteredType` instead - which is what this repo's doing - https://github.com/Atlinx/Godot-Mono-CustomResourceRegistry - `GlobalClass` just sounds a bit weird imo

Either way, really really awesome job everyone :D 🎉 🎉

**Comment by Shadowblitz16** [comment]
Why was C# not compiled directly to a new type?
It's still treated as a script instead of actually using gd-extension
image
