### PR TITLE
Move tile transforms handling cache to TileData

### LINKED ISSUE #83825: Painting a rotated or flipped tile in a Tilemap loses collision
### Godot version

4.2 beta 2

### System information

Pop Os 22.04 lts 12th Gen Intel® Core™ i7-12700H × 20 NVIDIA RTX A2000 8GB 32.0  ram. Tested on Forward+ and Mobile

### Issue description

When painting a tile that is rotated or flipped, it looses its physics layer as demonstrated in this video:  

https://github.com/godotengine/godot/assets/33091666/c10f7325-838f-4112-b90d-0c3d9797d08f

Even though in the video I showed this only happening with one of the tiles, it happens with both of them as long as you rotate or flip it. 

### Steps to reproduce

1. Create a tilemap and a tileset
2. Create a physics layer and set collision_visibility_mode to force show. 
3. Assign just created physics layer to tiles
4. Paint the tiles and use rotate or flip tool. 

### Minimal reproduction project

[TileTest.zip](https://github.com/godotengine/godot/files/13067412/TileTest.zip)

### PR DESCRIPTION
**Pull request by groud**
This PR does multiple things:
- moves the transformed polygons data cache to the TileData object. Since it's part of the TileSet resource, that should avoid further errors like https://github.com/godotengine/godot/issues/83825. It reverts https://github.com/godotengine/godot/pull/84261 and fix the issue in a cleaner way.
- Fix some errors that would be printed when using occluders. We were storing invalid occlusion polygons in the TileSet which caused errors to be printed.
- Fixed baking NavigationRegions with rotated tiles (an island is collision shapes, the other in navigation polygons, both work):  
Screenshot_20231109_123615

*Bugsquad edit:* Fixes #83825

### CODE REVIEW

File: scene/resources/tile_set.cpp [hunk 1]
```diff
@@ -5360,13 +5360,31 @@ int TileData::get_y_sort_origin() const {
...
+	occluders.write[p_layer_id].transformed_occluders.clear();
 	emit_signal(SNAME("changed"));
 }
 
-Ref<OccluderPolygon2D> TileData::get_occluder(int p_layer_id) const {
+Ref<OccluderPolygon2D> TileData::get_occluder(int p_layer_id, bool p_flip_h, bool p_flip_v, bool p_transpose) const {
 	ERR_FAIL_INDEX_V(p_layer_id, occluders.size(), Ref<OccluderPolygon2D>());
-	return occluders[p_layer_id];
+
+	int key = p_flip_h | p_flip_v << 1 | p_transpose << 2;
```
Comment (akien-mga) [inline scene/resources/tile_set.cpp:5371]:
```
'|': unsafe mix of type 'bool' and type 'int' in operation
```

File: scene/resources/tile_set.cpp [hunk 2]
```diff
@@ -5483,11 +5502,30 @@ int TileData::get_collision_polygon_shapes_count(int p_layer_id, int p_polygon_i
...
 }
 
-Ref<ConvexPolygonShape2D> TileData::get_collision_polygon_shape(int p_layer_id, int p_polygon_index, int shape_index) const {
+Ref<ConvexPolygonShape2D> TileData::get_collision_polygon_shape(int p_layer_id, int p_polygon_index, int shape_index, bool p_flip_h, bool p_flip_v, bool p_transpose) const {
 	ERR_FAIL_INDEX_V(p_layer_id, physics.size(), Ref<ConvexPolygonShape2D>());
 	ERR_FAIL_INDEX_V(p_polygon_index, physics[p_layer_id].polygons.size(), Ref<ConvexPolygonShape2D>());
 	ERR_FAIL_INDEX_V(shape_index, (int)physics[p_layer_id].polygons[p_polygon_index].shapes.size(), Ref<ConvexPolygonShape2D>());
-	return physics[p_layer_id].polygons[p_polygon_index].shapes[shape_index];
+
+	int key = p_flip_h | p_flip_v << 1 | p_transpose << 2;
```
Comment (akien-mga) [inline scene/resources/tile_set.cpp:5510]: Same here.

File: scene/resources/tile_set.cpp [hunk 3]
```diff
@@ -5565,13 +5603,46 @@ TileSet::TerrainsPattern TileData::get_terrains_pattern() const {
...
+	navigation.write[p_layer_id].transformed_navigation_polygon.clear();
 	emit_signal(SNAME("changed"));
 }
 
-Ref<NavigationPolygon> TileData::get_navigation_polygon(int p_layer_id) const {
+Ref<NavigationPolygon> TileData::get_navigation_polygon(int p_layer_id, bool p_flip_h, bool p_flip_v, bool p_transpose) const {
 	ERR_FAIL_INDEX_V(p_layer_id, navigation.size(), Ref<NavigationPolygon>());
-	return navigation[p_layer_id];
+
+	int key = p_flip_h | p_flip_v << 1 | p_transpose << 2;
```
Comment (akien-mga) [inline scene/resources/tile_set.cpp:5614]: And here.

**Comment by dsnopek** [comment]
I only looked at the GDExtension compatibility changes, but those look good to me!

File: misc/extension_api_validation/4.1-stable.expected [hunk 4]
```diff
@@ -312,3 +312,10 @@ GH-84419
 Validate extension JSON: API was removed: classes/Node/constants/NOTIFICATION_NODE_RECACHE_REQUESTED
 
 Removed unused NOTIFICATION_NODE_RECACHE_REQUESTED notification. It also used to conflict with CanvasItem.NOTIFICATION_DRAW and Window.NOTIFICATION_VISIBILITY_CHANGED (which still need to be resolved).
+
+GH-84660
```
Comment (AThousandShips) [inline misc/extension_api_validation/4.1-stable.expected:316]:
```suggestion

GH-84660
```

File: misc/extension_api_validation/4.1-stable.expected [hunk 5]
```diff
@@ -312,3 +312,10 @@ GH-84419
...
+--------
+Validate extension JSON: Error: Field 'classes/TileData/methods/get_navigation_polygon/arguments': size changed value in new API, from 1 to 4.
+Validate extension JSON: Error: Field 'classes/TileData/methods/get_occluder/arguments': size changed value in new API, from 1 to 4.
+
+Added optional argument to get_navigation_polygon and get_occluder to specify a polygon transform.
```
Comment (AThousandShips) [inline misc/extension_api_validation/4.1-stable.expected:321]:
```suggestion
Added optional argument to get_navigation_polygon and get_occluder to specify a polygon transform.

```
Missing line termination

File: scene/resources/tile_set.cpp [hunk 6]
```diff
@@ -5995,4 +6094,4 @@ void TileData::_bind_methods() {
 	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "probability"), "set_probability", "get_probability");
 
 	ADD_SIGNAL(MethodInfo("changed"));
-}
+}
```
Comment (AThousandShips) [inline scene/resources/tile_set.cpp:6097]:
```suggestion
}

```

**Review by AThousandShips — APPROVED** [review]
Looks correct otherwise

File: scene/resources/tile_set.cpp [hunk 7]
```diff
@@ -5360,13 +5361,31 @@ int TileData::get_y_sort_origin() const {
...
+	int key = int(p_flip_h) | int(p_flip_v) << 1 | int(p_transpose) << 2;
+	if (key == 0) {
+		return occluders[p_layer_id].occluder;
+	}
+
+	if (occluders[p_layer_id].occluder.is_null()) {
+		return Ref<OccluderPolygon2D>();
+	}
+
+	if (!occluders[p_layer_id].transformed_occluders.has(key)) {
```
Comment (KoBeWi) [inline scene/resources/tile_set.cpp:5381]:
```suggestion
	HashMap<int, Ref<OccluderPolygon2D>>::Iterator I = occluders[p_layer_id].transformed_occluders.find(key);
	if (!I) {
```
Avoids double lookup (although you'd need to tweak the logic a bit).

File: scene/resources/tile_set.cpp [hunk 8]
```diff
@@ -5360,13 +5361,31 @@ int TileData::get_y_sort_origin() const {
...
+	occluders.write[p_layer_id].occluder = p_occluder_polygon;
+	occluders.write[p_layer_id].transformed_occluders.clear();
 	emit_signal(SNAME("changed"));
 }
 
-Ref<OccluderPolygon2D> TileData::get_occluder(int p_layer_id) const {
+Ref<OccluderPolygon2D> TileData::get_occluder(int p_layer_id, bool p_flip_h, bool p_flip_v, bool p_transpose) const {
 	ERR_FAIL_INDEX_V(p_layer_id, occluders.size(), Ref<OccluderPolygon2D>());
-	return occluders[p_layer_id];
+
```
Comment (KoBeWi) [inline scene/resources/tile_set.cpp:5371]: You could add `const OcclusionLayerTileData &layer_tile_data = occluders[p_layer_id];` so the value is fetched only once.

**Review by KoBeWi — APPROVED** [review]
I added some minor optimization suggestions (they apply to physics and navigation too ofc), but otherwise looks fine.

File: scene/resources/tile_set.cpp [hunk 9]
```diff
@@ -5840,7 +5953,7 @@ void TileData::_get_property_list(List<PropertyInfo> *p_list) const {
 		for (int i = 0; i < occluders.size(); i++) {
 			// occlusion_layer_%d/polygon
 			property_info = PropertyInfo(Variant::OBJECT, vformat("occlusion_layer_%d/%s", i, PNAME("polygon")), PROPERTY_HINT_RESOURCE_TYPE, "OccluderPolygon2D", PROPERTY_USAGE_DEFAULT);
-			if (!occluders[i].is_valid()) {
+			if (!occluders[i].occluder.is_valid()) {
```
Comment (kleonc) [inline scene/resources/tile_set.cpp:5956]:
```suggestion
			if (occluders[i].occluder.is_null()) {
```

File: scene/resources/tile_set.cpp [hunk 10]
```diff
@@ -5896,7 +6009,7 @@ void TileData::_get_property_list(List<PropertyInfo> *p_list) const {
 		p_list->push_back(PropertyInfo(Variant::NIL, GNAME("Navigation", ""), PROPERTY_HINT_NONE, "", PROPERTY_USAGE_GROUP));
 		for (int i = 0; i < navigation.size(); i++) {
 			property_info = PropertyInfo(Variant::OBJECT, vformat("navigation_layer_%d/%s", i, PNAME("polygon")), PROPERTY_HINT_RESOURCE_TYPE, "NavigationPolygon", PROPERTY_USAGE_DEFAULT);
-			if (!navigation[i].is_valid()) {
+			if (!navigation[i].navigation_polygon.is_valid()) {
```
Comment (kleonc) [inline scene/resources/tile_set.cpp:6012]:
```suggestion
			if (navigation[i].navigation_polygon.is_null()) {
```

File: modules/navigation/nav_mesh_generator_2d.cpp [hunk 11]
```diff
@@ -608,11 +614,8 @@ void NavMeshGenerator2D::generator_parse_tilemap_node(const Ref<NavigationPolygo
 					Vector<Vector2> traversable_outline;
 					traversable_outline.resize(navigation_polygon_outline.size());
 
-					const Vector2 *navigation_polygon_outline_ptr = navigation_polygon_outline.ptr();
-					Vector2 *traversable_outline_ptrw = traversable_outline.ptrw();
-
 					for (int traversable_outline_index = 0; traversable_outline_index < traversable_outline.size(); traversable_outline_index++) {
-						traversable_outline_ptrw[traversable_outline_index] = tile_transform_offset.xform(navigation_polygon_outline_ptr[traversable_outline_index]);
+						traversable_outline.write[traversable_outline_index] = tile_transform_offset.xform(navigation_polygon_outline[traversable_outline_index]);
```
[the remark this answers is not in the document]
Comment (KoBeWi) [reply modules/navigation/nav_mesh_generator_2d.cpp:618]: Ah, I missed that it's in a loop. Indeed, the previous code was better.

File: doc/classes/TileData.xml [hunk 12]
```diff
@@ -70,15 +70,23 @@
 		<method name="get_navigation_polygon" qualifiers="const">
 			<return type="NavigationPolygon" />
 			<param index="0" name="layer_id" type="int" />
+			<param index="1" name="flip_h" type="bool" default="false" />
+			<param index="2" name="flip_v" type="bool" default="false" />
+			<param index="3" name="transpose" type="bool" default="false" />
 			<description>
 				Returns the navigation polygon of the tile for the TileSet navigation layer with index [param layer_id].
+				[param flip_h], [param flip_v] and [param transpose] allow transforming the returned polygon.
```
Comment (AThousandShips) [inline doc/classes/TileData.xml:78]:
```suggestion
				[param flip_h], [param flip_v], and [param transpose] allow transforming the returned polygon.
```
Oxford comma

File: doc/classes/TileData.xml [hunk 13]
```diff
@@ -70,15 +70,23 @@
...
 		</method>
 		<method name="get_occluder" qualifiers="const">
 			<return type="OccluderPolygon2D" />
 			<param index="0" name="layer_id" type="int" />
+			<param index="1" name="flip_h" type="bool" default="false" />
+			<param index="2" name="flip_v" type="bool" default="false" />
+			<param index="3" name="transpose" type="bool" default="false" />
 			<description>
 				Returns the occluder polygon of the tile for the TileSet occlusion layer with index [param layer_id].
+				[param flip_h], [param flip_v] and [param transpose] allow transforming the returned polygon.
```
Comment (AThousandShips) [inline doc/classes/TileData.xml:89]:
```suggestion
				[param flip_h], [param flip_v], and [param transpose] allow transforming the returned polygon.
```

**Review by AThousandShips — COMMENTED** [review]
Missed in docs

File: modules/navigation/nav_mesh_generator_2d.cpp (hunk 11 above)
[the remark this answers is not in the document]
Comment (groud) [reply modules/navigation/nav_mesh_generator_2d.cpp:618]: I think it's more readable (and less lines) the way it is right now, and the code is not very performance-critical anyway.
I'll revert that anyway. That's one less change, which is probably better.

File: doc/classes/TileData.xml (hunk 12 above)
Comment (groud) [reply doc/classes/TileData.xml:78]: Hmm, is that a thing we do in the whole documentation? I don't mind changing it but I'd rather be sure the documentation team want's the oxford comma to be generally used.

Comment (AThousandShips) [reply doc/classes/TileData.xml:78]: Inses, it's documented [here](https://docs.godotengine.org/en/stable/contributing/documentation/docs_writing_guidelines.html#use-the-oxford-comma-to-enumerate-anything)

**Comment by groud** [comment]
Thanks for the feedback @kleonc and @AThousandShips, should be fixed now :)

**Review by kleonc — APPROVED** [review]
Haven't tested, just looked at the code changes, LGTM!

File: misc/extension_api_validation/4.1-stable.expected
Comment (AThousandShips) [inline misc/extension_api_validation/4.1-stable.expected:1]: Needs to be moved to the 4.2 file now that it exists

**Comment by YuriSizov** [comment]
@groud Could you address the comment above and do the rebase? Otherwise this seems to be good to go based on reviews.

**Comment by YuriSizov** [comment]
Still has conflicts 🙃

**Comment by groud** [comment]
> @groud Could you address the comment above and do the rebase? Otherwise this seems to be good to go based on reviews.

Done.

> Still has conflicts 🙃

Yeah, sorry for that, I forgot to rebase.

**Comment by YuriSizov** [comment]
Thanks!
