### PR TITLE
Fix find highlight when switching scripts

### LINKED ISSUE #92913: Script editor find highlight gets stuck when find panel is closed in another tab
### Tested versions

Reproduces in v4.2-stable and v4.3-beta1.

### System information

Windows 10.0.22631 - Vulkan (Mobile) - dedicated AMD Radeon RX 7700 XT (Advanced Micro Devices, Inc.; 31.0.24027.1012) - AMD Ryzen 7 5700X3D 8-Core Processor (16 Threads)

### Issue description

The find match highlight in script editor sometimes gets stuck visible even though the find panel has been closed. The find panel has to be reopened and closed to reset the highlight.

### Steps to reproduce

Open two script files in the editor. Use CTRL+F to find something in one of them, so that it matches and highlights some text. Then switch to the other script while the find panel is open. Close the find panel and return to the first script.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by kitbdev**
- fixes https://github.com/godotengine/godot/issues/92913

Highlights when switching to another editor. 
Stops highlighting when switching away.

### CODE REVIEW

File: editor/code_editor.cpp [hunk 1]
```diff
@@ -670,8 +671,7 @@ void FindReplaceBar::set_text_edit(CodeTextEditor *p_text_editor) {
 	text_editor = base_text_editor->get_text_editor();
 	text_editor->connect("text_changed", callable_mp(this, &FindReplaceBar::_editor_text_changed));
 
-	_update_results_count();
-	_update_matches_display();
+	_editor_text_changed();
```
Comment (jinyangcruise) [inline editor/code_editor.cpp:674]: It seems that displaying matches is wrong when swiching scripts:

屏幕截图 2024-06-19 101936

It should be "1" in the screen shot.

Comment (kitbdev) [reply editor/code_editor.cpp:674]: I can't reproduce the issue, it seems to work fine for me. Are you hiding / showing the find bar or anything?
If it is visible, `_editor_text_changed()` calls `_search()` which updates the results count and calls `_update_matches_display()`. And if it is not visible then it is only updated when it is next opened. 
So I don't know where the problem is.

Comment (jinyangcruise) [reply editor/code_editor.cpp:674]: I find out that this issue is not from your modification. The old version already has such issue. To reproduce, follow these steps（you can use an old version like 4.3.dev6 or your modificated version）:
1. open two gd scripts (which have some functions)
2. activate 1st script and click text to put the caret anywhere
3. activate 2nd script and Ctrl+F to search the word 'func'
4. activate 1st script and Ctrl+F to search 'func' then you can notice that the first 'func' is **NOT** selected
5. then press `Enter` to continue search, you can notice that the first 'func' is selected while the match information shows that this 'func' is the **SECOND** match.

Comment (jinyangcruise) [reply editor/code_editor.cpp:674]: 6. then Ctrl+F agian, you will find the match information become correct.

Comment (kitbdev) [reply editor/code_editor.cpp:674]: This sounds like a different issue that can be fixed in a separate PR. When testing it, I noticed it does not even need switching scripts to be reproduced, just text already in the search field while the caret isn't selecting a match.

Comment (jinyangcruise) [reply editor/code_editor.cpp:674]: Yes. I will open a separate issue later, maybe tomorrow.

Comment (kitbdev) [reply editor/code_editor.cpp:674]: - Should be fixed in this new pr: https://github.com/godotengine/godot/pull/93674

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Comment by akien-mga** [comment]
Thanks!
