### PR TITLE
Fix editor settings parsing regression on Android

### LINKED ISSUE #113698: Android Editor: State of touch actions panel is not persisted between sessions
### Tested versions

4.6 dev 6

### System information

Android

### Issue description

Unlike other aspects of the editor layout, the position of the touch actions panel on android is not persisted between editor sessions. It defaults to being on the left, so if someone wants it on the right, they have to move it every time a project is opened.

### Steps to reproduce

1. Open a project and move the touch actions panel to the right
2. Reload project
3. The panel is on the left again

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #114016: Android: 4.6 beta 1, Editor settings reset when opening project
### Tested versions

Android 4.6.beta 1

### System information

Android 13

### Issue description

After updating from an earlier 4.6 dev build, opening project showed that all Editor Settings were reset or not loaded.

After clearing the editor dsta through the Android settings, I made some changes and tried again, but it still behaved like it was unconfigured.

I did notice that if you make changes to the settings through the project list without loading a project, they seem to stay until any project is loaded.

### Steps to reproduce

Open a project on Android 4.6.beta 1.

### Minimal reproduction project (MRP)

Any project exhibits this behavior.

### PR DESCRIPTION
**Pull request by syntaxerror247**
- Fixes #114016 
- Fixes #113698

### CODE REVIEW

File: scene/resources/resource_format_text.cpp [hunk 1]
```diff
@@ -419,18 +419,17 @@ Ref<PackedScene> ResourceLoaderText::_parse_node_tag(VariantParser::ResourcePars
 }
 
 void ResourceLoaderText::_count_resources() {
+	Ref<FileAccess> scan_f = FileAccess::open(f->get_path(), FileAccess::READ);
+	if (scan_f.is_null()) {
+		return;
+	}
+
```
Comment (MartinDelille) [inline scene/resources/resource_format_text.cpp:426]: I started implementing it this way but I was warned by @akien-mga regarging Windows I/O:

https://github.com/godotengine/godot/pull/103352#discussion_r2576467212

Comment (syntaxerror247) [reply scene/resources/resource_format_text.cpp:426]: Oh, and the current method is causing parsing error on Android.

I don't have windows so can't test that.

Comment (syntaxerror247) [reply scene/resources/resource_format_text.cpp:426]: I'm currently investigating the root cause. FileAccessUnix is used on both Linux and Android, but the issue is only reproducible on Android. The only difference I've identified so far is that Linux uses glibc, while Android uses bionic. 
To confirm this as a bionic issue, we'd need a MRP, which I haven't been able to create yet.

Comment (akien-mga) [reply scene/resources/resource_format_text.cpp:426]: To be clear, I flagged that this _may_ cause I/O issues on Windows, but I didn't test. If the alternative is breaking Android, then it would be good to check the previous approach and see how it works on Windows.

**Review by akien-mga — APPROVED** [review]
