### PR TITLE
Return the length of the playing stream for AudioStreamRandomizer

### LINKED ISSUE #104684: AudioStreamPlaylist ignores AudioStreamRandomizer
### Tested versions

Reproducible in: v4.4.1.stable.steam [49a5bc7b6], v4.4.beta1.official [d33da79d3]

### System information

Godot v4.4.1.stable (49a5bc7b6) - Windows 11 (build 22000) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 32.0.15.6094) - 12th Gen Intel(R) Core(TM) i3-12100F (8 threads)

### Issue description

AudioStreamPlaylist can play different type of AudioStreams, even another AudioStreamPlaylist, but it ignores and skips AudioStreamRandomizer and does not play them.

### Steps to reproduce

Have at least 2 sounds.

Create AudioStreamPlayer node
Create AudioStreamPlaylist for AudioStreamPlayer->stream
Put sound 1 in Element 0 of streams of playlist
For Element 1 create AudioStreamRandomizer and put sound 2 in it streams list
Element 2 should be sound 1 or another sound that is different from sound 2
Check `playing`. Element 0 plays, Element 2 plays. Element 1 (Randomizer) was skipped.

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #105929: AudioStreamInteractive treats AudioStreamRandomizer as if it has no length.
### Tested versions

Reproducable in v4.4.1.stable.official [49a5bc7b6]

### System information

Godot v4.4.1.stable - Linux Mint 22.1 (Xia) on X11 - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 XT (RADV NAVI23) - AMD Ryzen 5 3600 6-Core Processor (12 threads)

### Issue description

Normally, AudioStreamInteractive should wait for a stream to complete or reach the end of its beat count before progressing to the next clip.

If these clips are replaced with an AudioStreamRandomizer, they'll all play at once, as if they have zero length.

Here's the normal setup:

Image

And the setup that causes this issue:

Image

Ideally, these two setups should produce the same result.

Of note: this works as expected with other streams such as AudioStreamPlaylist. Could be related to https://github.com/godotengine/godot/issues/104684

### Steps to reproduce

1) Create an AudioStreamPlayer
2) Give it an AudioStreamInteractive
3) Put at least two audio clips, with the first having "auto advance" enabled and set to go to the second clip.
4) If you put in two wav or ogg streams, it should behave as expected
5) Replace the clips with AudioStreamRandomizer streams, with the same wav/ogg stream inside it.
6) Play the stream and all streams will play at once.

### Minimal reproduction project (MRP)

[mvp.zip](https://github.com/user-attachments/files/19969265/mvp.zip)

### PR DESCRIPTION
**Pull request by JulianHeuser**
Fixes https://github.com/godotengine/godot/issues/105929
Fixes https://github.com/godotengine/godot/issues/104684

### CODE REVIEW

**Comment by Mickeon** [comment]
Either way, can you actually confirm this fixes https://github.com/godotengine/godot/issues/104684 ? It means that no matter what, both issues stem from this function.

**Comment by JulianHeuser** [comment]
> Either way, can you actually confirm this fixes #104684 ?

Yes, I've tested it and it plays everything in sequence as expected, so it's definitely caused by the same issue.

I see the problem though - It's a bit unclear if get_length changes it value based on if the stream is playing or not, but it also doesn't make sense for it to be static on streams that can have variable length. The same issue is present for AudioStreamInteractive. I think for consistency, it makes more sense to return the length of the currently playing stream rather than the max length, since there are a lot of cases where users will need to use streams of variable length with AudioStreamInteractive. If someone wants to get the max length of all streams, they can do that in code, or we can make a helper function for the types of streams that could use it.

File: servers/audio/audio_stream.cpp [hunk 1]
```diff
@@ -729,7 +729,11 @@ String AudioStreamRandomizer::get_stream_name() const {
 }
 
 double AudioStreamRandomizer::get_length() const {
-	return 0;
+	if (last_playback.is_valid()) {
+		return last_playback->get_length();
+	} else {
+		return 0;
+	}
```
Comment (adamscott) [inline servers/audio/audio_stream.cpp]: I prefer early exiting, but it's nitpicky.

```suggestion
	if (!last_playback.is_valid()) {
		return 0;
	}
	return last_playback->get_length();
```

**Review by adamscott — COMMENTED** [review]
As discussed in the audio meeting, we prefer this solution to the one returning the length of the longest stream.

File: servers/audio/audio_stream.cpp (hunk 1 above)
Comment (JulianHeuser) [reply servers/audio/audio_stream.cpp]: I saw it done like that in other places and assumed it was part of the style - but if I have the go-ahead I also prefer it your way.

**Review by Mickeon — APPROVED** [review]

**Review by adamscott — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
