### PR TITLE
Auto-reload scripts with external editor

### LINKED ISSUE #10946: External script editing does not trigger reload of running game
___

***Bugsquad edit:** This bug has been confirmed several times already. No need to confirm it further.*

___

**Windows 10 Godot 3.0 v3.0.alpha.custom_build.af97525**

**Issue description:**
Editing script file in external file editor with `Sync Script Changes` does not trigger reload

**Steps to reproduce:**
* Create a scene and attach a new script file which prints something every second
* Enable `Sync Script Changes`
* Change message from normal editor - Godot reloads
* Open external editor (for example VSCode) and edit it.
* The file reloads in the Godot file editor if opened, but doesn't reload the project

### PR DESCRIPTION
**Pull request by yjh0502**
The PR allows auto-reload with external editors.
 - It calls `_live_auto_reload_running_scripts` when appropriates.
 - It uses `NOTIFICATION_APPLICATION_FOCUS_IN` events to trigger reload as `NOTIFICATION_WM_WINDOW_FOCUS_IN` is never called on `master` branch. I'm not sure why, probably a bug?

Here's another patch for `3.x` branch. It also fixes error messages when script changed on external editor. (`Another resource is loaded from path` thing). I could create another PR if you prefer: https://gist.github.com/yjh0502/e2cb62f9216c953c8e54541199d7be09

related: #10946

<i>Bugsquad edit</i>: Fix #10946

### CODE REVIEW

File: editor/plugins/script_text_editor.cpp [hunk 1]
```diff
@@ -668,6 +668,10 @@ void ScriptEditor::_update_modified_scripts_for_external_editor(Ref<Script> p_fo
 			script->update_exports();
 		}
 	}
+
+	if (auto_reload_running_scripts) {
+		_live_auto_reload_running_scripts();
```
Comment (Paulb23) [inline editor/plugins/script_text_editor.cpp:673]: Should only call this if a script has been reloaded and `pending_auto_reload == false`

**Review by Paulb23 — CHANGES_REQUESTED** [review]
`NOTIFICATION_WM_WINDOW_FOCUS_IN` not triggering is a bug see also #47176. Not sure it's worth adding workarounds for it.

**Comment by yjh0502** [comment]
> `NOTIFICATION_WM_WINDOW_FOCUS_IN` not triggering is a bug see also #47176. Not sure it's worth adding workarounds for it.

Let's fix the bug first (ref: https://github.com/godotengine/godot/pull/51781). I'll update this PR after merging #51781

**Comment by yjh0502** [comment]
@Paulb23 I tried to address the issue you mentioned. Unfortunately I'm not good at naming, so please feel free to suggest another name :)

**Comment by Paulb23** [comment]
Looks good. No worries :) as far as naming goes perhaps `trigger_live_script_reload`?

**Comment by yjh0502** [comment]
> Looks good. No worries :) as far as naming goes perhaps `_trigger_live_script_reload`?

Thanks for your suggestion, I changed the name.

**Review by Paulb23 — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by rversteegen** [comment]
Very pleased to see this fixed!

> Here's another patch for `3.x` branch. It also fixes error messages when script changed on external editor. (`Another resource is loaded from path` thing). I could create another PR if you prefer: https://gist.github.com/yjh0502/e2cb62f9216c953c8e54541199d7be09

Do I understand that this separate patch is needed to fix the error messages? Will this also get applied? Those errors are annoying and distracting.

**Comment by yjh0502** [comment]
@rversteegen The error message problem was already fixed on master branch, and I fixed the error message issue while back-porting this patch to 3.x branch, which is already merged. See also: https://github.com/godotengine/godot/pull/51828

**Comment by cptchuckles** [comment]
This doesn't quite fix the issue I was having with the editor in #49298, particularly where export vars don't get updated after I save a script and return focus to the Godot editor, unless I close and re-open the scene.  My PR #49473 addresses that but it needs a review
