### PR TITLE
Fix display of large sizes in the editor monitors

### LINKED ISSUE #29610: Memory monitors switch to numbers in bytes after 2GB
**Godot version:**
3.1.1

**OS/device including version:**
macOS 10.14.5

**Issue description:**
Numbers reported in the Monitors tab of the Debugger pane intelligently switch to KB, MB, and GB as the numbers get larger (or smaller). However, after 2GB, the numbers lose the G qualifier, and are simply displayed in bytes (as opposed to gigabytes). See below:

image
image
image

The cutoff seems to be at the maximum value a signed 32-bit integer can hold. Therefore, the issue seems to be due to a 32-bit check, which should be easy to fix by converting it to 64-bits. It looks like some work (https://github.com/godotengine/godot/pull/25494) was done on a related issue, but fell short of fixing the units of the reported numbers.

**Steps to reproduce:**
Keep allocating memory and watch the memory Monitors in Godot.

### PR DESCRIPTION
**Pull request by Calinou**
Unlike the old custom method, the `String::humanize_size()` method works well with file sizes above 2 GB.

This also tweaks the suffixes for spacing consistency and uses the correct acronym for exabytes (EB, according to Wikipedia). We could add zettabytes and yottabytes, but that's for later :wink: 

This closes #29610.

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

File: core/ustring.cpp [hunk 1]
```diff
@@ -3235,7 +3235,7 @@ static int _humanize_digits(int p_num) {
 String String::humanize_size(size_t p_size) {
 
 	uint64_t _div = 1;
-	static const char *prefix[] = { " Bytes", " KB", " MB", " GB", "TB", " PB", "HB", "" };
+	static const char *prefix[] = { " Bytes", " KB", " MB", " GB", " TB", " PB", " EB", "" };
```
Comment (aaronfranke) [inline core/ustring.cpp]: Just a note: if we wanted to continue this farther, there is ZB and YB, though these are beyond the current range of `uint64_t` for bytes.
