### PR TITLE
Make `TabContainer` use `TabBar` internally

### LINKED ISSUE #2514: Make the TabContainer node use Tabs internally, instead of its own implementation
### Describe the project you are working on
The Godot Engine™.

### Describe the problem or limitation you are having in your project
Currently, `TabContainer` has its own tab system implementation, one which basically copies everything from `Tabs`, which means that there is two implementations of the exact same thing, and both need to be updated when adding functionality. This adds unnecessary extra work for their maintenance.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
The solution would be making `TabContainer` use `Tabs` internally, removing the need of two different implementations. That, however, is more complex than it seems, as written in the next section.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Basically, it would happen by adding a `Tabs` node as a child of `TabContainer`, remove the existing code, and pass the commands to that instead. But this brings some problems:
- When using `TabContainer`s, the workflow used by people (and Godot's own codebase) is by using child manipulation functions (`add_child()`, `get_index()`, `get_child_count()`, etc) with it, since it's a `Container` derived node. The problem is that adding `Tabs` to it shoves a wrench in the machine, since those functions can't be relied upon anymore without a bit of extra hacking. This problem could be completely solved if godotengine/godot#30391 was to be merged.
- As the current implementation is a copy of `Tabs`, `TabContainer` also has the same majority of functions and enumerations that the former has, including theme styling. What should be done about that? Just make those link to the `Tabs` node internally, which means two things still need to be updated, even if to a lesser extent? Or expose the node itself, which would open a complete new can of worms?
- The act of dragging and dropping tabs. While I didn't do much digging on that, I assume things will be trick to manage there, since the dragging won't happen in the node itself.

There's the possibility that more problems could come up later, but you get the point. I'm trying to tackle this problem since a long time, but doubts on how to deal with those hurdles stops me in my tracks, so I opened this proposal as a form of discussion on how this could be done (and if the task is worth the trouble to begin with).

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It's something internal, so no.

### Is there a reason why this should be core and not an add-on in the asset library?
It's about a core feature itself.

### LINKED ISSUE #4512: TabContainer should use Tabs instead of reimplementing them
As discussed today on IRC [0], TabContainer `scene/gui/tab_container.cpp` should be modified to rely on Tabs `scene/gui/tabs.cpp` instead of reimplementing tabs itself.

The Tabs class has grown to be feature-rich (though it could still use some cleanup even after #4506), so it should stay as the sole implementation.

[0] http://godot.eska.me/irc-logs/devel/2016-05-01.log

### LINKED ISSUE #56140: After drag and dropping a tab to another dock, it can't be reordered
### Godot version

489f11e

### System information

W10

### Issue description

XnTrOYSOAS
Dropped tabs are always first on the list and can't be moved. You need to use the 3-dots menu to move the tab somewhere else and back.

### Steps to reproduce

1. Move any editor tab to another dock using drag and drop
2. Try reordering the tabs in that dock

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by YeldhamDev**
_Kept you waiting, huh?_

It's finally here, after a long time and a lot of PRs to make `TabBar` work correctly, `TabContainer` can now use it instead of its own implementation! This will considerably improve maintainability and facilitate improvements.

Fixes #56140.
Supersedes #58143.

*Bugsquad edit:*
- Fixes #4512.
- Fixes https://github.com/godotengine/godot-proposals/issues/2514.

### Methods Modified:

- `get_tab_idx_at_point()` exposed for `TabBar`. Just so `TabContainer` and everyone else can use it with ease.
- `get_tab_disabled()` -> `is_tab_disabled()` for `TabContainer` (all methods below are also for that). The naming makes more sense and matches the one in `TabBar`.
- `get_tab_hidden()` -> `is_tab_hidden()`. Same as above.
- `get_tab_idx_from_control()` added. Allows the get the correct tab index, ignoring top-level and internal nodes (very useful for us to use internally, see "Caveats").
- `clip_tabs` member added. Now the clipping can be disabled.
- `set_tab_title()` now returns a tab to its default name (the one of the child) if set to blank.
- `AlignmentMode` constants have been removed from `TabContainer`, now making use of the ones in `TabBar`.

### Caveats:

- This is for you, fellow Godot maintainers: **use *get_tab_idx_from_control()* instead of `child->get_index()` when manipulating controls in a `TabContainer`**. As said before, this method is a helper to get the correct index of the tab.
- `all_tabs_in_front` is now more literal than before. The old behavior always made the selected tab be in front no matter what, now, due to technical limitations, **all** tabs must be either in front or back (the default is back).

### CODE REVIEW

File: scene/gui/tab_bar.cpp [hunk 1]
```diff
@@ -1001,8 +1005,12 @@ Variant TabBar::get_drag_data(const Point2 &p_point) {
 		return Variant();
 	}
 
-	int tab_over = get_tab_idx_at_point(p_point);
+	// Allow for TabContainer to override it.
+	if (has_meta("_tab_container")) {
+		return get_parent()->call("_get_drag_data_fw", p_point);
+	}
```
Comment (YeldhamDev) [inline scene/gui/tab_bar.cpp:1011]: I'm open to ideas on how to make this less hacky.

Comment (KoBeWi) [reply scene/gui/tab_bar.cpp:1011]: Something like `set_drag_forwarding(tab_bar)` in the TabContainer? Not sure if it overrides `get_drag_data()` though.

**Comment by KoBeWi** [comment]
Sooo many bugs
- the most obvious one is Import tab overlapping scene tree at startup
image
- also for some reason, the scene that opens at start is the first tab instead of the last one
- can't switch scene tabs
- if you move e.g. Import tab next to FileSystem and then back, you get this
image
- this button can't be clicked anymore
image
- after adding Controls to TabContainer, they are all visible until you change tab
godot windows tools 64_lH0pQmmwvo
(previously any new control would be auto-hidden)

File: scene/gui/tab_bar.cpp (hunk 1 above)
Comment (YeldhamDev) [reply scene/gui/tab_bar.cpp]: Okay, I used that method, now it's done like this:
```
if (!drag_to_rearrange_enabled) {
	return Control::get_drag_data(p_point); // Allow stuff like TabContainer to override it.
}
```

**Comment by KoBeWi** [comment]
The last bug isn't fully fixed yet. The Control is visible and doesn't get updated immediately after being added in editor:
godot windows tools 64_cYtzMt7Nk6
(hiding it would be enough though)

btw, it might be useful to have `get_tab_bar()` method in the TabContainer. Some compound controls (e.g. ScrollContainer) have such methods.

**Comment by YeldhamDev** [comment]
> btw, it might be useful to have get_tab_bar() method in the TabContainer. Some compound controls (e.g. ScrollContainer) have such methods.

The whole thing depends on `TabBar` to be in perfect sync with the stuff in `TabContainer`, changing anything could easily make it crash. Would that function still be desirable?

**Comment by KoBeWi** [comment]
Well, depends if TabBar has some useful properties that can be customized and aren't available in TabContainer. ScrollContainer will also crash if you free the scroll bars and it's just mentioned in the docs.

**Comment by KoBeWi** [comment]
Minimum size does not work:
godot windows tools 64_qYM5VHkrZC
Regardless of `use_hidden_tabs_for_min_size`.

**Comment by YeldhamDev** [comment]
@KoBeWi Bugs (hopefully) fixed, and docs updated. Thanks for helping me test this, by the way!

**Comment by KoBeWi** [comment]
The `side_margin` still has problems:
godot windows tools 64_hexIScxxr4
For center align it only moves to the right and for right align it moves to a certain point and then tabs mysteriously disappear. Works good with left align.

Is this intended that `get_tab_idx_at_point()` ignores upper bounds? I.e. it returns correct id no matter how high above tab you check. Doesn't happen with other sides.

**Comment by KoBeWi** [comment]
I'm looking at the code and I wonder, should left alignment be default instead of center? Every single TabContainer in editor changes it to left. Also left is used commonly in other software (browsers, code editors, everything uses it). I think it would be better to change it.

btw this PR fixes #56140

**Comment by YeldhamDev** [comment]
> I'm looking at the code and I wonder, should left alignment be default instead of center? Every single TabContainer in editor changes it to left. Also left is used commonly in other software (browsers, code editors, everything uses it). I think it would be better to change it.

Probably, but this should be done in another PR. :wink:

**Comment by KoBeWi** [comment]
Should it? You are modifying all alignment usage anyways. You could remove these lines instead of changing them.

File: scene/gui/tab_container.cpp [hunk 2]
```diff
@@ -883,85 +392,192 @@ void TabContainer::drop_data(const Point2 &p_point, const Variant &p_data) {
...
+Control *TabContainer::get_current_tab_control() const {
+	return get_tab_control(tab_bar->get_current_tab());
+}
+
+int TabContainer::get_tab_idx_at_point(const Point2 &p_point) const {
+	return tab_bar->get_tab_idx_at_point(p_point);
+}
+
+int TabContainer::get_tab_idx_from_control(Control *p_child) const {
+	ERR_FAIL_COND_V(!p_child, -1);
```
Comment (KoBeWi) [inline scene/gui/tab_container.cpp:553]:
```suggestion
	ERR_FAIL_NULL(p_child, -1);
```

File: scene/gui/tab_container.cpp [hunk 3]
```diff
@@ -883,85 +392,192 @@ void TabContainer::drop_data(const Point2 &p_point, const Variant &p_data) {
...
 		} else if (get_tabs_rearrange_group() != -1) {
-			// drag and drop between TabContainers
+			// Drag and drop between TabContainers.
 			Node *from_node = get_node(from_path);
 			TabContainer *from_tabc = Object::cast_to<TabContainer>(from_node);
 			if (from_tabc && from_tabc->get_tabs_rearrange_group() == get_tabs_rearrange_group()) {
 				Control *moving_tabc = from_tabc->get_tab_control(tab_from_id);
 				from_tabc->remove_child(moving_tabc);
-				add_child(moving_tabc, false, INTERNAL_MODE_FRONT);
+				add_child(moving_tabc);
```
Comment (KoBeWi) [inline scene/gui/tab_container.cpp:405]:
```suggestion
				add_child(moving_tabc, true);
```
This prevents weird names in case of conflicts:
image

**Comment by KoBeWi** [comment]
Minimum size calculation still doesn't work correctly. It seems to not take tab size into account:
image
Here, I have 64x64 TextureRect. Minimum size should be tab height + TextureRect size, but it's only the latter.

File: scene/gui/tab_container.cpp [hunk 4]
```diff
@@ -1117,26 +717,28 @@ Size2 TabContainer::get_minimum_size() const {
 		ms.y = MAX(ms.y, cms.y);
```
Comment (KoBeWi) [inline scene/gui/tab_container.cpp:717]: The size problem probably lies here. The MAX should be **added** to `ms` from tabs, not overwrite it. So you probably need two separate sizes - one for tabs and one for controls and then add them.

File: scene/gui/tab_container.cpp [hunk 5]
```diff
@@ -1117,26 +717,28 @@ Size2 TabContainer::get_minimum_size() const {
...
 void TabContainer::set_popup(Node *p_popup) {
-	ERR_FAIL_NULL(p_popup);
-	Popup *popup = Object::cast_to<Popup>(p_popup);
-	popup_obj_id = popup ? popup->get_instance_id() : ObjectID();
-	update();
+	bool had_popup = get_popup();
+
+	if (p_popup) {
+		Popup *popup = Object::cast_to<Popup>(p_popup);
+		popup_obj_id = popup ? popup->get_instance_id() : ObjectID();
```
Comment (KoBeWi) [inline scene/gui/tab_container.cpp:732]: You could do the casting before condition and check `if (popup)` instead.

**Comment by YeldhamDev** [comment]
Changes made.

File: scene/gui/tab_container.cpp [hunk 6]
```diff
@@ -1104,39 +688,59 @@ void TabContainer::get_translatable_strings(List<String> *p_strings) const {
...
 
 void TabContainer::set_popup(Node *p_popup) {
-	ERR_FAIL_NULL(p_popup);
+	bool had_popup = get_popup();
+
 	Popup *popup = Object::cast_to<Popup>(p_popup);
-	popup_obj_id = popup ? popup->get_instance_id() : ObjectID();
-	update();
+	if (popup) {
+		popup_obj_id = popup ? popup->get_instance_id() : ObjectID();
```
Comment (KoBeWi) [inline scene/gui/tab_container.cpp:734]:
```suggestion
		popup_obj_id = popup->get_instance_id();
```
🙃

Comment (YeldhamDev) [reply scene/gui/tab_container.cpp:734]: Oops!

**Review by KoBeWi — APPROVED** [review]
There are a few places where you could add `SNAME()`, but I guess it's not important here.

Overall looks good now. Nice work 😉

**Comment by akien-mga** [comment]
Thanks! Amazing work :)
