### PR TITLE
Save current tab in `TabBar` and `TabContainer`

### LINKED ISSUE #50930: TabContainer resets visibility to first tab in editor
### Godot version

3.3 stable

### System information

linux mint

### Issue description

You're working on a single tab and need to switch to another scene or code. When you go back, whatever tab(s) you had selected is/are removed and the first one is selected.

image

This is really very annoying and forces you to constantly update visibility in the editor or temporarily move your tab (if you are editing just one) to the very top.

btw, It wouldn't be 'as bad' if you could drag items down (but still a pain) but Godot stops you from moving items to the bottom of the list because when at the bottom it eithier changes level to one before or one after, it will not let you move a sibling to be the last one.

### Steps to reproduce

1. create a tab container with multiple tabs
2. select one tab
3. change to another open scene then go back

### Minimal reproduction project

[game.zip](https://github.com/godotengine/godot/files/6888588/game.zip)

### PR DESCRIPTION
**Pull request by kitbdev**
fixes #50930

Removed `PROPERTY_USAGE_EDITOR` from `current_tab`.
For `TabBar`, moved tabs array above other properties (like how `OptionButton` does it).
For `TabContainer`, delayed setting `current_tab` until `ready` so children are added first.

### CODE REVIEW

**Comment by AThousandShips** [comment]
I'd say the rearranging of the tabs is a separate thing and not relevant to the specific change of exposing the property for storage, this should be split into multiple PRs IMO

**Comment by AThousandShips** [comment]
That would indeed be required, as you didn't mention it in the PR either

The rest should be separate to focus the review on just the issue

**Comment by kitbdev** [comment]
added the comment and undid the `tab_alignment` move.

**Comment by AThousandShips** [comment]
Does it only have to be above the current tab? Otherwise I'd say to move it instead, like the other PR did

**Comment by kitbdev** [comment]
In `OptionButton` the array is at the top of all properties, so that's what I did here. I didn't want to have the array in between the properties since it's cleaner when they're together, but I could since it only needs to be above `current_tab`.

**Comment by AThousandShips** [comment]
Just make sure it doesn't affect any other properties

**Comment by kitbdev** [comment]
It looks like no properties are affected by tab count and tab count is not affected by any other properties.  `_update_cache()` and similar are either only called when not in the tree or or called everywhere they are affected, so the order doesn't matter for them.

**Comment by kitbdev** [comment]
made `ensure_tab_visible` run out of the tree so that it properly handles the saved `current_tab`.

File: scene/gui/tab_container.cpp [hunk 1]
```diff
@@ -143,7 +143,14 @@ void TabContainer::_notification(int p_what) {
 			}
 		} break;
 
-		case NOTIFICATION_READY:
+		case NOTIFICATION_READY: {
+			if (setting_up) {
```
Comment (KoBeWi) [inline scene/gui/tab_container.cpp:147]: `NOTIFICATION_READY` is only received once per node, so this won't work correctly when adding the node multiple times.

File: scene/gui/tab_bar.cpp [hunk 2]
```diff
@@ -1485,7 +1485,7 @@ void TabBar::_ensure_no_over_offset() {
 }
 
 void TabBar::ensure_tab_visible(int p_idx) {
-	if (!is_inside_tree() || !buttons_visible) {
```
Comment (KoBeWi) [inline scene/gui/tab_bar.cpp:1488]: You could use something similar to `setting_up` here.

File: scene/gui/tab_container.cpp (hunk 1 above)
Comment (kitbdev) [reply scene/gui/tab_container.cpp:147]: I can use `NOTIFICATION_POST_ENTER_TREE` instead.

Comment (kitbdev) [reply scene/gui/tab_container.cpp:147]: I do need to check the `setting_up` here, otherwise `set_current_tab` will be called even if it wasn't called out of the tree. We don't want this because it can send a signal, and in when `current_tab` is its default of `0` it would call it and cause an index out of range error if there are no children.

File: scene/gui/tab_bar.cpp (hunk 2 above)
Comment (kitbdev) [reply scene/gui/tab_bar.cpp]: I instead call `ensure_tab_visible()` on `NOTIFICATION_ENTER_TREE`.

File: scene/gui/tab_container.h [hunk 3]
```diff
@@ -47,6 +47,8 @@ class TabContainer : public Container {
 	bool theme_changing = false;
 	Vector<Control *> children_removing;
 	bool drag_to_rearrange_enabled = false;
+	bool setting_up = false;
+	int setup_current_tab = 0;
```
Comment (KoBeWi) [inline scene/gui/tab_container.h:51]:
```suggestion
	int setup_current_tab = -1;
```
Instead of `setting_up` you can check if `setup_current_tab >= 0`.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
