### PR TITLE
Fix `Node3D.set_global_rotation()` resetting node scale.

### LINKED ISSUE #74162: Setting the global rotation of a Node3D does not retain its scale
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Ubuntu

### Issue description

Hi,
I'm using GDExtension C++ to change a Node3D's global rotation. I've noticed that if you do something like this:

```c++
    godot::Node3D* m_localPlayer = ...;
    godot::Vector3 scale = m_localPlayer->get_scale(); // (0.05, 0.05, 0.05)
    m_localPlayer->set_global_rotation(godot::Vector3(0,0,0)); // change the rotation
    scale = m_localPlayer->get_scale(); // scale reset to (1, 1, 1)
    // I have to manually add this to reset the scale to its original position
    m_localPlayer->set_scale(godot::Vector3(0.05f, 0.05f, 0.05f)); 
```

This can also be reproduceable in GDScript:
```gdscript
extends Node3D

# Called when the node enters the scene tree for the first time.
func _ready():
	$Adventurer.set_scale(Vector3(0.5, 0.5, 0.5)); 
	print("Current scale: ", $Adventurer.get_scale());
	$Adventurer.set_global_rotation(Vector3(0,35 * (3.1415/180),0));
	print("New scale: ", $Adventurer.get_scale()); // (1, 1, 1)
```

After I do `set_global_rotation`, I noticed it changed the scale from `(0.05, 0.05, 0.05)` to `(1, 1, 1)`. Is this a bug or expected behavior.

Thanks

### Steps to reproduce

Simply run the reproducible project to see the last print statement shows that the scale is reset back to `(1,1,1)`. 

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/10862656/bug.zip)

### PR DESCRIPTION
**Pull request by BMagnu**
Fixes #74162.

The error was caused because the basis for the target global transform was entirely recreated. This process did not account for the scale of the basis of the current global transform.
This PR amends this by scaling the recreated basis for the global transform by the current global scale of the Node3D. Note that this scaling has to be done from the current global scale and not from the local scale of the Node3D.
This is important, otherwise a scaled parent of the Node3D would cause incorrect results on overwriting the global transform basis.

### CODE REVIEW

**Review by ajreckof — APPROVED** [review]
LGTM

**Review by fire — APPROVED** [review]
@aaronfranke I think this is correct?

**Comment by AThousandShips** [comment]
This should be valid to fix, but I wouldn't cherry pick it as it at least mildly breaks compatibility, people might very well rely on it resetting scale and this would break their code

**Comment by BMagnu** [comment]
Agreed, cherry picking it back into 4.2 is dangerous as only a patch-level fix for this reason.
Still, should be fine for the yet-unreleased 4.3

File: scene/3d/node_3d.cpp [hunk 1]
```diff
@@ -293,7 +293,7 @@ Vector3 Node3D::get_global_rotation_degrees() const {
 void Node3D::set_global_rotation(const Vector3 &p_euler_rad) {
 	ERR_THREAD_GUARD;
 	Transform3D transform = get_global_transform();
-	transform.basis = Basis::from_euler(p_euler_rad);
+	transform.basis = Basis::from_euler(p_euler_rad).scaled(transform.basis.get_scale());
```
Comment (aaronfranke) [inline scene/3d/node_3d.cpp:296]:
```suggestion
	transform.basis = Basis::from_euler(p_euler_rad) * Basis::from_scale(transform.basis.get_scale());
```

**Review by aaronfranke — CHANGES_REQUESTED** [review]

**Review by aaronfranke — APPROVED** [review]

**Comment by aaronfranke** [comment]
> This should be valid to fix, but I wouldn't cherry pick it as it at least mildly breaks compatibility, people might very well rely on it resetting scale and this would break their code

I would lean towards cherry-picking this. It is really weird for setting the rotation to change the scale. I would assume most users are using this method with unscaled objects, or else they would've run into this bug before.

**Comment by AThousandShips** [comment]
> or else they would've run into this bug before.

This bug was discovered before 4.0 released so it's absolutely been run into, the report in question is from march last year, so just after 4.0, and there was a report before that with less details from January of the same year, so I don't think this is necessarily unnoticed

**Comment by akien-mga** [comment]
Thanks!
