### PR TITLE
Editor: Fix Tag Container Clipping Project Title and Breaking Project Manager UI

### LINKED ISSUE #118871: Many tags on project breaks Project Manager UI
### Tested versions

- Reproducible in 4.1 and later

### System information

Windows 11 (build 26200) - Multi-window, 1 monitor - Direct3D 12 (Forward+) - dedicated AMD Radeon(TM) R4 Graphics (Advanced Micro Devices, Inc.; 27.20.20912.1002) - AMD A6-9225 RADEON R4, 5 COMPUTE CORES 2C+3G (2 threads) - 11.44 GiB memory

### Issue description

When adding lots of tags, or tags with long names to a project, it clips the Project Title and pushes the sidebar beyond the window size, the window does not resize in response.

Image

### Steps to reproduce

Choose a random project and just create lots of tags and add them to the project.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by unit-tick**
Closes #118871
Closes #113566
Currently, a project with a lot of tags causes the project title text to clip and also pushes the sidebar beyond the Project Manager window size.
tag_unwrapped

This wraps the tags by having them inside an HFlowContainer instead of the default HBoxContainer.
tag_wrapped

It also works properly with longer project titles
long_project_title

Edit 1: This fix won't work for long tag names (or a combination of an overly long project title and tag name), though it is unlikely to encounter such an issue.
Edit 2: The above has been resolved via a maximum size for tags and tooltips that show full tag name.

### CODE REVIEW

**Comment by arkology** [comment]
Unfortunately, this won't work with really long tag names and a minimal window size, but it's highly unlikely that anyone will face it.

**Comment by unit-tick** [comment]
Thanks, forgot to point that out, updated it now. 👍

**Comment by KoBeWi** [comment]
Tags could have maximum size now, trimming if too long. The full text could be in the tooltip.

**Comment by unit-tick** [comment]
@KoBeWi What would be a good maximum size? There are some long genre names like Adventure and Platformer, I think those should absolutely fit.

Edit: Settled on 250px for maximum size (75% scale).

File: editor/project_manager/project_list.h [hunk 1]
```diff
@@ -32,6 +32,7 @@
 
 #include "core/io/config_file.h"
 #include "scene/gui/box_container.h"
+#include "scene/gui/flow_container.h"
```
Comment (AThousandShips) [inline editor/project_manager/project_list.h]: Should be forward declared instead

Comment (unit-tick) [reply editor/project_manager/project_list.h]: How would I do that? (I'm still very new to c++)

Comment (AThousandShips) [reply editor/project_manager/project_list.h]: You remove the include and add `class HFlowContainer;` to the list below that starts with `class AcceptDialog;`

Comment (unit-tick) [reply editor/project_manager/project_list.h]: figured it out.

Comment (AThousandShips) [reply editor/project_manager/project_list.h]: You removed the include from the cpp file as well, it needs to be there still

File: editor/project_manager/project_tag.cpp [hunk 2]
```diff
@@ -69,9 +69,11 @@ ProjectTag::ProjectTag(const String &p_text, bool p_display_close) {
 	add_child(button);
 	button->set_auto_translate_mode(AUTO_TRANSLATE_MODE_DISABLED);
 	button->set_text(p_text.capitalize());
+	button->set_tooltip_text(p_text.capitalize());
 	button->set_focus_mode(FOCUS_ACCESSIBILITY);
 	button->set_accessibility_name(vformat(TTR("Project Tag: %s"), p_text));
 	button->set_icon_alignment(HORIZONTAL_ALIGNMENT_RIGHT);
 	button->set_theme_type_variation(SNAME("ProjectTagButton"));
+	button->set_custom_maximum_size(Vector2(334, -1) * EDSCALE);
```
Comment (KoBeWi) [inline editor/project_manager/project_tag.cpp]:
```suggestion
	button->set_custom_maximum_size(Vector2(334 * EDSCALE, -1));
```
Also I think the button needs a different overrun mode, like OVERRUN_TRIM_ELLIPSIS.

Comment (unit-tick) [reply editor/project_manager/project_tag.cpp]: will do

Comment (unit-tick) [reply editor/project_manager/project_tag.cpp]: setting the overrun breaks the tag.

Comment (KoBeWi) [reply editor/project_manager/project_tag.cpp]: Yeah, I just noticed it. Seems like maximum size is not properly handled in Button. CC @StarryWorm 

For now remove the overrun.

**Review by KoBeWi — APPROVED** [review]

File: editor/project_manager/project_tag.cpp (hunk 2 above)
Comment (StarryWorm) [reply editor/project_manager/project_tag.cpp]: Button didn't get any special attention back then, will give it a proper handling.

**Comment by Repiteo** [comment]
Thanks!
