### PR TITLE
VisualScriptFunctionNodes Improvements

### LINKED ISSUE #26717: Drag & drop creates function node instead of Set or Get
**Godot version:**
v3.1.dev.calinou.1800664

**OS/device including version:**
windows 10 x64

**Issue description:**
In visual script
when drag & drop from Scene tab to visual script area, it shows a list of properties, after select, it create a function node instead of Get or Set node.
when change the function it shows a list of methods.
https://drive.google.com/open?id=1QgBxuP37_D_dvUatKIo32HT4Ar_IgUKX

the correction :
when drag & drop it will show a list of methods.
properties can be added by drag & drop from inspector, or by holding shift and drag & drop from Scene tab to visual script area, then it will show a list of properties and create a Get or Set node.
https://drive.google.com/open?id=1LRnvQsdJsBr8FcoZDTlFjTNmHzRBZgJI

### LINKED ISSUE #49146: Visual Script CollisionShape2D Get Shape node throws "Invalid call" error
**Godot version:**

3.3.2

**OS/device including version:**

macOS

**Issue description:**

Happened: unhelpful error "Invalid call" with no explanation what went wrong.
Expected to get shape from node.
изображение

**Steps to reproduce:**
1) Create in the tree: Area2D, inside - CollisionShape2D, optionally - add RectangleShape2D
2) Drag node into visual script with Get Shape.
3) Use it in function (see repro). Experience error.

**Minimal reproduction project:**

[poolvector2arrayrepro.zip](https://github.com/godotengine/godot/files/6555034/poolvector2arrayrepro.zip)

### PR DESCRIPTION
**Pull request by Gallilus**
This PR improves and streamlines the workflow for VisualScriptFunctionNodes. Call Set Get
Removes redundant method_select popup
And Fix issues with drop offset and instancing Set Get

Supersedes #49184
Supersedes #49172
Fixes #26717
Fixes #49146
Possible Fix #37053

### Editor changes
* Fix issue when of dropposition when in different zoom levels.
* Fix drag in Set and Get.
### VisualScriptFuncNode's changes
* Harmonize and improve the visual representation of the VisualScriptFuncNode's and there different modes.
* Update Functionality of VisualScriptFunctionGet to include pass when using instance mode.

[example project.zip](https://github.com/godotengine/godot/files/6695328/example.project.zip)
[example script.zip](https://github.com/godotengine/godot/files/6695334/example.script.zip)

screeshot
caption = what
text (sequence) = where / object info
I-O's = details 

# Original
image

### CODE REVIEW

**Comment by YeldhamDev** [comment]
Small typo in the commit message: "Imrovements"

**Comment by charlesmlamb** [comment]
ok, 10 / 10, superb . .

**Comment by fire** [comment]
Reviewing.

File: modules/visual_script/visual_script_editor.cpp [hunk 1]
```diff
@@ -3235,18 +3166,62 @@ void VisualScriptEditor::_selected_connect_node(const String &p_text, const Stri
...
+		if (source_node) {
+			n->set_base_type(source_node->get_class());
+			if (source_node->get_script_instance()) {
+				n->set_base_script(source_node->get_script_instance()->get_script()->get_path());
+			}
+		}
 		vnode = n;
 	}
+	source_path = String();
+	source_node = NULL;
```
Comment (fire) [inline modules/visual_script/visual_script_editor.cpp:3224]: Minor:

`NULL` usage is inconsistent with `nullptr`.

File: modules/visual_script/visual_script_editor.h [hunk 2]
```diff
@@ -179,6 +179,9 @@ class VisualScriptEditor : public ScriptEditorBase {
 
 	void connect_data(Ref<VisualScriptNode> vnode_old, Ref<VisualScriptNode> vnode, int new_id);
 
+	NodePath source_path;
+	Node *source_node;
```
Comment (fire) [inline modules/visual_script/visual_script_editor.h:183]: Init to `nullptr`.

**Review by fire — APPROVED** [review]
Improving the situation.

1. Reviewed the code.
2. Reviewed the example photo
3. Still need test with demo projects to see the visual scripting's effect.

Please try further QA and resolve the style changes.

Approved on the design.

Note:
Trying to create a get_position on Node2D crashes. Cannot reproduce again.

**Comment by DavidCambre** [comment]
@fire, sorry I'm confused.
Please try further QA and resolve the style changes. Is this directed at me? 
Do I need to make it with nullptr's? Do you have a example?

**Comment by DavidCambre** [comment]
@fire
Tested even got a few small extras that where overlooked.
Set Basic Type now has sequence ports.
Ready for merge

**Comment by charlesmlamb** [comment]
Thanks, for this, every improvement to Visual script matters to me, Godot 4 will be amazing . .

**Comment by DavidCambre** [comment]
Do I need a new approval before it is possible to merge?
I'm dreaming of getting this to 3.x before 3.3.3

**Comment by Calinou** [comment]
> I'm dreaming of getting this to 3.x before 3.3.3

3.3.x will only get bug fixes; new features will be available in 3.4.

File: modules/visual_script/visual_script_func_nodes.cpp [hunk 3]
```diff
@@ -1036,17 +1045,18 @@ String VisualScriptPropertySet::get_caption() const {
 }
 
 String VisualScriptPropertySet::get_text() const {
+	if (!has_input_sequence_port())
+		return "";
```
Comment (akien-mga) [inline modules/visual_script/visual_script_func_nodes.cpp:1049]:
```suggestion
	if (!has_input_sequence_port()) {
		return "";
	}
```

**Review by akien-mga — APPROVED** [review]
Assign from a small style issue, this seems pretty solid. I'm not very familiar with VisualScript but it seems to improve UX, and we can iterate further from there.

**Comment by akien-mga** [comment]
Once merged, feel free to make a PR to backport the changes to `3.x` for inclusion in 3.4. But please also make sure that the changes do not break compatibility for existing scripts (I think not, but again I don't know much about VisualScript).

**Comment by akien-mga** [comment]
Thanks!

**Comment by DavidCambre** [comment]
Real time support of Remi is Awesome!!
