### PR TITLE
Fix broken layout of asset library page

### LINKED ISSUE #87407: Godot Project Manager Layout is broken when trying to access asset library.
### Tested versions

Tested in 4.2.1 windows 64 bit.

### System information

Windows 10 - Godot 4.2.1 stable 64bit - CPU: i3 2330M - GPU: GT630M

### Issue description

As the title said.

I have record a screen capture.

https://github.com/godotengine/godot/assets/76892624/fc668d38-7f59-4367-8b7e-f0adb835bd4b

### Steps to reproduce

1. Download godot
2. Extract it.
3. Run it.
4. Open asset library.
5. Change the source to community or testing until the library loaded.
6. Look at the layout.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by eugene87222**
While reviewing #87407, I came across two additional problems. I've recorded a demo to help explain.

https://github.com/godotengine/godot/assets/24380544/573fef12-5efe-4e47-8ff9-9a0bb439a3dc

The first issue, as described in #87407, occurs when horizontally scaling the project manager window while on the asset library page, resulting in a broken layout.
image

The second issue occurs when scaling to the point where the third column appears. It becomes evident that the widths of the three columns are not evenly distributed.
image

The third issue occurs when navigating to the asset library page after opening a project and then scaling. As the number of columns in the asset library increases, it becomes impossible to reduce the number of columns. Even attempting to narrow the width of the asset library doesn't work.

My current solution involves fine-tuning the size of `asset_items_columns_width` and performing a clamp operation each time `_update_asset_items_columns` is executed.

Below is the demo video of my solution.

https://github.com/godotengine/godot/assets/24380544/37976075-3304-4c93-b8a3-e01d22609329

Also, I noticed a refactor todo item in the `clamp_width` function. However, I found that refactoring the `LinkButton` to support ellipsing functionality similar to `Button` might not be straightforward for me. I'm also unsure if it would cause some spec changes for `LinkButton`, so I haven't tackled it from that angle.

*Bugsquad edit:*
- Fixes https://github.com/godotengine/godot/issues/87407

### CODE REVIEW

**Comment by KoBeWi** [comment]
I think column problems can also be solved by using HFlowContainer instead of GridContainer, no?

**Comment by eugene87222** [comment]
I see. I'll try it.

**Comment by eugene87222** [comment]
image
Seems not. `HFlowContainer` only stacks items horizontally, without guaranteeing vertical alignment.

**Comment by KoBeWi** [comment]
You could try using EXPAND flag on library items, it might force them to have the same size. Though it will break on rows with less items 🤔
Yeah maybe GridContainer is better here.

File: editor/plugins/asset_library_editor_plugin.cpp [hunk 1]
```diff
@@ -66,16 +68,15 @@ void EditorAssetLibraryItem::configure(const String &p_title, int p_asset_id, co
 
 // TODO: Refactor this method to use the TextServer.
 void EditorAssetLibraryItem::clamp_width(int p_max_width) {
-	int text_pixel_width = title->get_button_font().ptr()->get_string_size(title->get_text()).x * EDSCALE;
-
-	String full_text = title->get_text();
-	title->set_tooltip_text(full_text);
+	int text_pixel_width = title->get_button_font().ptr()->get_string_size(title_text).x * EDSCALE;
```
Comment (KoBeWi) [inline editor/plugins/asset_library_editor_plugin.cpp:71]:
```suggestion
	int text_pixel_width = title->get_button_font()->get_string_size(title_text).x * EDSCALE;
```
This can be removed.

**Review by KoBeWi — APPROVED** [review]
Well the GridContainer works alright and this fixes the issue.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.
