### PR TITLE
Correctly free relevant scripts when closing scene tabs

### LINKED ISSUE #85983: [GodotEditor - Mono] CSharp Script of a Scene Dependency Not Freed when Closing Scene Tab under Certain Condition
### Tested versions

A custom build of Godot 4.2.1.rc.mono, with the following `print_error` line added to the `./modules/mono/csharp_script.cpp`
```cpp
CSharpScript::~CSharpScript() {
#ifdef DEBUG_ENABLED
	MutexLock lock(CSharpLanguage::get_singleton()->script_instances_mutex);
	CSharpLanguage::get_singleton()->script_list.remove(&this->script_list);
#endif

	/*This line ------->*/ print_error("CSharpScript::Delete: " + get_class_name());

	if (GDMonoCache::godot_api_cache_updated) {
		GDMonoCache::managed_callbacks.ScriptManagerBridge_RemoveScriptBridge(this);
	}
}

void CSharpScript::get_members(HashSet<StringName> *p_members) {
#if defined(TOOLS_ENABLED) || defined(DEBUG_ENABLED)
	if (p_members) {
		for (const StringName &member_name : exported_members_names) {
			p_members->insert(member_name);
		}
	}
#endif
}

/*************** RESOURCE ***************/

Ref<Resource> ResourceFormatLoaderCSharpScript::load(const String &p_path, const String &p_original_path, Error *r_error, bool p_use_sub_threads, float *r_progress, CacheMode p_cache_mode) {
	if (r_error) {
		*r_error = ERR_FILE_CANT_OPEN;
	}

	// TODO ignore anything inside bin/ and obj/ in tools builds?

	Ref<CSharpScript> scr;

	/*This line ------->*/ print_error("CSharpScript::Create: " + p_path);

	if (GDMonoCache::godot_api_cache_updated) {
		GDMonoCache::managed_callbacks.ScriptManagerBridge_GetOrCreateScriptBridgeForPath(&p_path, &scr);
	} else {
		scr = Ref<CSharpScript>(memnew(CSharpScript));
	}
```

### System information

Godot v4.2.1.rc.mono (daeb1c729) - Windows 10.0.17763 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4060 Ti (NVIDIA; 31.0.15.4601) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

A CSharp script, as a dependency of a scene, sometimes will not get freed when closing that scene tab, based on the testing result, this issue occurs when:
1. There is more than one scene tab, and the closing scene is not the first scene tab.
2. There is only one scene tab.

I have found this issue in the process of identifying/addressing the [.NET: Failed to unload assemblies](https://github.com/godotengine/godot/issues/78513) issue, specifically the issue that prints the following error:
```
modules/mono/glue/runtime_interop.cpp:1324 - System.ArgumentException: An item with the same key has already been added. Key: Game.WeaponAbilityData
     at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
     at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
     at Godot.Bridge.ScriptManagerBridge.ScriptTypeBiMap.Add(IntPtr scriptPtr, Type scriptType) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.types.cs:line 23
     at Godot.Bridge.ScriptManagerBridge.AddScriptBridge(IntPtr scriptPtr, godot_string* scriptPath) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 419
```

### Steps to reproduce

0. Add the mentioned line to the source code at the corresponding position, then compile the godot source with mono module enabled.
1. Open the included project, close any opened scene, then go to `Project/Reload Current Project`.
2. There are three behaviors this project can produce: `Expected`, `Error - MoreThanOneTab`, `Error - OnlyOneTab`

## Expected:
1. Open `scene_a.tscn`, print: `CSharpScript::Create: res://Script.cs`
2. Open `empty.tscn`
3. Close `scene_a.tscn`, print: `CSharpScript::Dtor: CSharpScript`
4. Close `empty.tscn`
Video:
https://github.com/godotengine/godot/assets/71481700/6c7f29ec-f292-4dea-ae62-cc4496720a14

## Error - MoreThanOneTab:
1. Open `empty.tscn`
2. Open `scene_a.tscn`, print: `CSharpScript::Create: res://Script.cs`
3. Close `scene_a.tscn`, nothing is printed (the script is not freed)
4. Close `empty.tscn`, print: `CSharpScript::Dtor: CSharpScript`, which is an unexpected behavior
Video:
https://github.com/godotengine/godot/assets/71481700/24ae4de6-d369-4479-8c53-398483c10403

## Error - OnlyOneTab:
1. Open `scene_a.tscn`, print: `CSharpScript::Create: res://Script.cs`
2. Close `scene_a.tscn`, nothing is printed (the script is not freed)
3. Close the `[empty]` tab, [nothing is printed (the script is not freed)](print: `CSharpScript::Dtor: CSharpScript`, which is an unexpected behavior)
Video:
https://github.com/godotengine/godot/assets/71481700/6340c65e-a2ac-4feb-85a1-ec6574be3b6f

### Minimal reproduction project (MRP)

[Issue Demo.zip](https://github.com/godotengine/godot/files/13626080/Issue.Demo.zip)

### PR DESCRIPTION
**Pull request by Delsin-Yu**
Fixes #85983 
`EditorNode::_remove_scene` from `editor/editor_node.cpp` calls `editor_data.clear_script_icon_cache()` for cleaning all script icon cache, previously, the implementation inside `_remove_edited_scene(p_change_tab)` loops through all scene tabs including the one we are closing, results in a call to `EditorData::get_script_icon()` on the closing scene tab, and create `Ref<Script>`s to that unloading scene lives inside `_script_icon_cache`.

This issue causes, primarily, the c-sharp scripts not to get freed when closing scene tabs, and might be a cause of #78513.
These wild script references may live inside the `ScriptManagerBridge.ScriptTypeBiMap`, resulting in the duplicate key issue when unloading the assebly.
```
modules/mono/glue/runtime_interop.cpp:1324 - System.ArgumentException: An item with the same key has already been added. Key: Game.WeaponAbilityData
     at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
     at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
     at Godot.Bridge.ScriptManagerBridge.ScriptTypeBiMap.Add(IntPtr scriptPtr, Type scriptType) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.types.cs:line 23
     at Godot.Bridge.ScriptManagerBridge.AddScriptBridge(IntPtr scriptPtr, godot_string* scriptPath) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 419
```

### CODE REVIEW

**Comment by AThousandShips** [comment]
Please give your PR a name that describes what the PR does

**Comment by AThousandShips** [comment]
You should target `master` not `4.2`, changes can then be cherry picked.

If you need more information about the update process please see: [here](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase). If wanted I can fix the branch for you.

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -3516,6 +3516,10 @@ void EditorNode::_remove_scene(int index, bool p_change_tab) {
 	// FIXME: Ideally the cache should never be cleared and only updated on per-script basis, when an icon changes.
 	editor_data.clear_script_icon_cache();
 
+	// Mark the scene tab index as removing, so this scene will get ignored when calling EditorSceneTabs::update_scene_tabs()
```
Comment (AThousandShips) [inline editor/editor_node.cpp:3523]:
```suggestion
	// Mark the scene tab index as removing, so this scene will get ignored when calling EditorSceneTabs::update_scene_tabs().
```
Per the [comment style](https://docs.godotengine.org/en/latest/contributing/development/code_style_guidelines.html#comment-style-guide).

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -3516,6 +3516,10 @@ void EditorNode::_remove_scene(int index, bool p_change_tab) {
...
+	// Previously, script_icon_cache will get re-populate when update_scene_tabs loop through all scene tabs
```
Comment (AThousandShips) [inline editor/editor_node.cpp:3524]:
```suggestion
	// Previously, script_icon_cache will get re-populate when update_scene_tabs loop through all scene tabs.
```

File: editor/gui/editor_scene_tabs.cpp [hunk 3]
```diff
@@ -217,8 +217,12 @@ void EditorSceneTabs::update_scene_tabs() {
 	Ref<Texture2D> script_icon = get_editor_theme_icon(SNAME("Script"));
 	for (int i = 0; i < EditorNode::get_editor_data().get_edited_scene_count(); i++) {
 		Node *type_node = EditorNode::get_editor_data().get_edited_scene_root(i);
+
+		// We should not call get_object_icon if the scene we are working on is a removing scene, since this will populate _script_icon_cache with script reference we just cleared
```
Comment (AThousandShips) [inline editor/gui/editor_scene_tabs.cpp:221]:
```suggestion
		// We should not call get_object_icon if the scene we are working on is a removing scene,
		// since this will populate _script_icon_cache with script reference we just cleared.
```

**Review by AThousandShips — COMMENTED** [review]
Some style fixes (will help as you need to push again to cause CI to run)

**Comment by Delsin-Yu** [comment]
I don't think adding this `removing_scene` field inside `editor_data` is healthy, a better approach would directly modify the logic inside `EditorNode::_remove_edited_scene(bool p_change_tab)` since we just need to find a way for calling `editor_data.remove_scene(old_index)` before `_set_current_scene(new_index)`. However, the program started crashing after modifying the logic there.

#### Original Logic
```cpp
void EditorNode::_remove_edited_scene(bool p_change_tab) {
	// When scene gets closed no node is edited anymore, so make sure the editors are notified before nodes are freed.
	hide_unused_editors(SceneTreeDock::get_singleton());

	int new_index = editor_data.get_edited_scene();
	int old_index = new_index;

	if (new_index > 0) {
		new_index = new_index - 1;
	} else if (editor_data.get_edited_scene_count() > 1) {
		new_index = 1;
	} else {
		editor_data.add_edited_scene(-1);
		new_index = 1;
	}

	if (p_change_tab) {
		_set_current_scene(new_index);
	}
	editor_data.remove_scene(old_index);
	_update_title();
	scene_tabs->update_scene_tabs();
}
```
#### New Logic that Causes Crashing
```cpp
void EditorNode::_remove_edited_scene(bool p_change_tab) {
	// When scene gets closed no node is edited anymore, so make sure the editors are notified before nodes are freed.
	hide_unused_editors(SceneTreeDock::get_singleton());

	int old_index = editor_data.get_edited_scene();

	editor_data.remove_scene(old_index);

	if (p_change_tab) {
		int new_index = editor_data.get_edited_scene();


		if (new_index == 0) {
			if (editor_data.get_edited_scene_count() == 0) {



				editor_data.add_edited_scene(-1);
			}
		} else {
			new_index = new_index - 1;
		}


		_set_current_scene(new_index);
	}

	_update_title();
	scene_tabs->update_scene_tabs();
}
```

#### The Crash Message
```
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.2.1.rc.mono.custom_build (daeb1c7292cbb426fd45c5ca98b1c7da40b390ba)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] Node::get_configuration_warnings_as_string (D:\UnityProject\godot\scene\main\node.cpp:3067)
[1] SceneTreeEditor::_add_nodes (D:\UnityProject\godot\editor\gui\scene_tree_editor.cpp:287)
[2] SceneTreeEditor::_update_tree (D:\UnityProject\godot\editor\gui\scene_tree_editor.cpp:617)
[3] call_with_variant_args_helper<SceneTreeEditor,bool,0> (D:\UnityProject\godot\core\variant\binder_common.h:308)
[4] call_with_variant_args_dv<SceneTreeEditor,bool> (D:\UnityProject\godot\core\variant\binder_common.h:451)
[5] MethodBindT<SceneTreeEditor,bool>::call (D:\UnityProject\godot\core\object\method_bind.h:337)
[6] Object::callp (D:\UnityProject\godot\core\object\object.cpp:775)
[7] Callable::callp (D:\UnityProject\godot\core\variant\callable.cpp:69)
[8] CallQueue::_call_function (D:\UnityProject\godot\core\object\message_queue.cpp:222)
[9] CallQueue::flush (D:\UnityProject\godot\core\object\message_queue.cpp:328)
[10] SceneTree::physics_process (D:\UnityProject\godot\scene\main\scene_tree.cpp:473)
[11] Main::iteration (D:\UnityProject\godot\main\main.cpp:3596)
[12] OS_Windows::run (D:\UnityProject\godot\platform\windows\os_windows.cpp:1474)
[13] widechar_main (D:\UnityProject\godot\platform\windows\godot_windows.cpp:182)
[14] _main (D:\UnityProject\godot\platform\windows\godot_windows.cpp:204)
[15] main (D:\UnityProject\godot\platform\windows\godot_windows.cpp:218)
[16] WinMain (D:\UnityProject\godot\platform\windows\godot_windows.cpp:232)
[17] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[18] <couldn't map PC to fn name>
-- END OF BACKTRACE --
```

**Comment by KoBeWi** [comment]
I checked why the tab updates while deleting and seems like when closing the tab, `update_scene_tabs()` is called at least 3 times, for no reason. I can't reproduce the issue, so I can't test, but #83957 might fix it too.

The fix here looks like a workaround for bad tab management.

**Comment by Delsin-Yu** [comment]
> I checked why the tab updates while deleting and seems like when closing the tab, `update_scene_tabs()` is called at least 3 times, for no reason. I can't reproduce the issue, so I can't test, but #83957 might fix it too.
> 
> The fix here looks like a workaround for bad tab management.

Detailed reproduction steps are written in issue #85983.
I just want to emphasize that this specific fix is targeting the CSharp script system (un-freed (re-referenced) script reference causing issue & module crash on assembly reload), and I agree that #83957 is a better way as long as that resolves the CSharp scripting issue as well.

**Comment by KoBeWi** [comment]
> Detailed reproduction steps are written in issue

I know, I just don't have a C# setup to test. I tried with GDScript and other resources and it doesn't seem to happen.

> I agree that https://github.com/godotengine/godot/pull/83957 is a better way as long as that resolves the CSharp scripting issue as well.

It's already merged, please give it a test.

**Comment by Delsin-Yu** [comment]
> It's already merged, please give it a test.

The test indicates the issue persists to exist.
It looks like the core of this issue is not `calling update_scene_tabs() multiple times`, but `calling update_scene_tabs()` in the middle of deleting a tab will cause a re-reference of script dependencies.

**Comment by Delsin-Yu** [comment]
This is a flowchart for explaining this issue.
Chart

**Comment by KoBeWi** [comment]
Well the issue is still updating the tabs before the old tab was completely removed. So I think a better solution would be delaying tab update.

**Comment by Delsin-Yu** [comment]
> Well the issue is still updating the tabs before the old tab was completely removed. So I think a better solution would be delaying tab update.

I will give that a try

File: editor/editor_node.cpp [hunk 4]
```diff
@@ -3692,7 +3692,7 @@ void EditorNode::_set_current_scene_nocheck(int p_idx) {
 	_edit_current(true);
 
 	_update_title();
-	scene_tabs->update_scene_tabs();
+	scene_tabs->call_deferred(SNAME("update_scene_tabs"));
```
Comment (AThousandShips) [inline editor/editor_node.cpp:3695]:
```suggestion
	callable_mp(scene_tabs, &EditorSceneTabs::update_scene_tabs).call_deferred();
```
This method isn't exposed as far as I can see, so can't be called like this, and this is the preferred method in any case

**Review by KoBeWi — APPROVED** [review]
The tab update now happens after tab is fully removed, so if it fixes the issue, then it's fine.

On unrelated note, I think we should be more conservative with calling tab updates. There are cases like call to `_set_current_scene()` followed by `update_scene_tabs()`, which makes the update happen twice, because `_set_current_scene()` already does this internally. Tab update is now cheaper, but it's still called more than necessary.

**Comment by YuriSizov** [comment]
Could you please squash your commits into one? Make sure that the final commit has a short but descriptive message (the title of this PR is a good option). See [this documentation](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase), if you need help with squashing.

**Comment by YuriSizov** [comment]
Thanks, and congrats on your first merged Godot contribution!
