### PR TITLE
Make nan==nan true for GDScript

### LINKED ISSUE #6947: Godot crashes when a certain gdscript file is in the project folder
Issue experienced on Windows 7 and Windows 10 - Godot version 2.1

Description: When Godot has a certain gdscript somewhere within "res://", it crashes when this file is either previewed in the file browser, opened, or saved within Godot. This problematic .gd file is attached to this issue. A way to prevent the crash is to mess with lines 30 and 31:

```
var x = 200 * cos(2 * PI / (0))
var y = 200 * sin(2 * PI / (0))
```

If either of these lines are deleted, Godot won't crash. If either of these lines are changed enough, Godot won't crash. It makes no sense to me why the editor seems to crash only in the case that these lines are present in a file.

Steps to reproduce:
1. Download the attached file
2. Change the file extension from .txt to .gd
3. Create a new Godot project
4. Put the downloaded .gd file in the Godot project's root directory
5. Open the project
6. Open the .gd file within Godot
7. Try to save the .gd file a number of times

Godot should crash at some point during this process.

[Game.txt](https://github.com/godotengine/godot/files/557495/Game.txt)

### LINKED ISSUE #7354: Vector2 division breaks the editor
**Operating system or device - Godot version:**
2.2.1

**Issue description** (what happened, and what was expected):
Typing out Vector2 division immediately crashes the editor, and opening the project afterwards causes the editor to immediately crash again until you remove the line using some other method.

**Steps to reproduce:**
I wrote this line in the _ready call of an otherwise empty script in an empty scene.

Vector2(5, 0)/Vector2(1, 0)

### PR DESCRIPTION
**Pull request by hpvb**
After discussing this with Reduz this seemed like the best way to
fix #7354. This will make composite values that contain NaN in the same
places as well as the same other values compare as the same.

Additionally non-composite values now also compare equal if they are
both NaN. This breaks IEEE specifications but this is probably what most
users expect. There is a GDScript function check for NaN if the user
needs this information.

This fixes #7354 and probably also fixes #6947

### CODE REVIEW

File: core/variant_op.cpp [hunk 1]
```diff
@@ -322,8 +336,8 @@ void Variant::evaluate(const Operator& p_op, const Variant& p_a, const Variant&
 				DEFAULT_OP_ARRAY_EQ(POOL_INT_ARRAY,int);
 				DEFAULT_OP_ARRAY_EQ(POOL_REAL_ARRAY,real_t);
 				DEFAULT_OP_ARRAY_EQ(POOL_STRING_ARRAY,String);
-				DEFAULT_OP_ARRAY_EQ(POOL_VECTOR2_ARRAY,Vector3);
-				DEFAULT_OP_ARRAY_EQ(POOL_VECTOR3_ARRAY,Vector3);
+				DEFAULT_OP_ARRAY_NANEQ(POOL_VECTOR2_ARRAY,Vector3);
+				DEFAULT_OP_ARRAY_NANEQ(POOL_VECTOR3_ARRAY,Vector3);
```
Comment (bojidar-bg) [inline core/variant_op.cpp]: Not completely sure what you are doing here, but shouldn't you add a `DEFAULT_OP_ARRAY_NANEQ` for `POOL_REAL_ARRAY` (and maybe Int array)?

Comment (hpvb) [inline core/variant_op.cpp]: You are correct. I'll fix this.

**Review by reduz — APPROVED** [review]

**Comment by tagcup** [comment]
I'll think about it but so far I personally like Zylann's ideaw from @7354 that 1) division by zero should raise an error 2) somehow make hashing aware of NaNs. 

But I'm not convinced this PR actually does what it claims to do ("make nan==nan true for GDScript"). There are many other data types such as color, some nodes have float properties etc. surely this doesn't apply to them either.

To me, this seems rather like a problem with GDScript, and the solution shouldn't be pushed onto core/math and every single data structure available to GDScript.

**Comment by tagcup** [comment]
Meanwhile, would you consider undoing this PR?

Either way, there are clearly many many other floats accessible to GDScript, and this PR works around only a handful of cases.

**Comment by hpvb** [comment]
I can add the missing cases, but this was the behavior that @reduz wanted implemented as a fix. I didn't implement this for colors, rect3, transform, and basis as it seemed that there would be no easy way through arithmetic to get a nan in there. But for consistency this should be done. I'll create another PR for that.

As for the other node types, they go through Variant for their arithmetic as far as I'm aware and should all be 'nan == nan' complaint because of it.

As for the speed of this solution I don't know of another way to do the nan check because of C++'s behavior of nan != nan. On my compiler a straight memcmp() seems to work but the nan value is implementation defined and there may be multiple. If you have an idea on how to do this please do let me know.

**Comment by tagcup** [comment]
> I'll create another PR for that.

Please don't. What I'm trying to say is this is just a hack, not a good way of addressing the issue here.

Even if you did, it won't end with just that. Think about all the data structures and node types accessible to GDScript, there are dozens, maybe hundreds of other floats here and there.

NaN isn't equal to NaN per IEEE-754 specification, it is true regardless of the language, at the hardware level. You can try to fight the hardware, but it's going to be really really hard and will no doubt result in hundreds of lines hacks, unnecessary bloat, and more importantly, mathematically wrong results in certain scenarios.

I think this requires a very careful discussion and thinking, and shouldn't be rushed. I'd say the best course is to undo this PR and just fix the editor crashing issue with constant hashing until a proper fix is found.

**Comment by hpvb** [comment]
@tagcup I wasn't too happy about it either but this was the behavior favored by @reduz. 

As for the implementation: the arithmetic for all of these floats will go through gdscript, and through variant. I don't see a way of getting a nan *comparison* into gdscript from the outside where this wouldn't work. Equality of any Variant will have to go through variant_op.cpp. How can you avoid this? Can you show me how to make NaN != Nan from a gdscript function with this PR?

**Comment by reduz** [comment]
I think I misunderstood the problem.. agree that it should be reverted.. I
guess variant should checl for division by zero in vector types instead

**Comment by tagcup** [comment]
@hpvb Zylann identified the issue [here](https://github.com/godotengine/godot/issues/7354#issuecomment-269878828) and while I'm not familiar with the internals of GDScript, to me it seems it should possible to prevent that crash by making local changes in GDScript code. I trust it should be along the lines @reduz recommends.

**Comment by hpvb** [comment]
OK, but we have several issues here that are independent that I tied to fix.

* The crashes mentioned
* The hashing failure in general with nan

Now, I can add the check to variant so we will get an error instead, crashing the game. I don't think this is much better than the current behavior of crashing the engine, this should probably not be fatal in release mode.

For the hashing without a separate equality check that is nan aware I have to get rid of one of the optimisations in it. It does an equally check on existing entries to try to avoid unnecessary hash calculations. This is what causes the crash in the first place.

Implementing this separate equality check in hash alone was rejected by @reduz on IRC saying he wanted 'nan ==nan' to be true for gdscript as a whole.

Even with the /0 check we still need to have a separate nan aware fix for hash because different from comparison nan can appear in floats later accessed by gdscript from c++ easy enough. Just making sure it can't happen from gdscript actually does not fix the underlying issue and is in my opinion more of a hack that only works part of the time than this is.

While I can implement this all by only touching vatiant_op.cpp and the hash class it would mean implementing knowledge of each type in both. If that is preferred over adding another method to the datatypes that's fine but seems to me to be way hackier as it spreads knowledge about the class studied like structure all over the place.

**Comment by tagcup** [comment]
Yes, I understand that @reduz makes the overall decisions, but you also need to understand that he's pretty busy implementing big stuff, so he doesn't have a lot of time to pay a lot of attention to "common" issues.

I would say it's better to handle these issues separately then. The crash sounds like a priority issue, and you already have a solution for that. We can meanwhile think about how the hash map should handle float NaNs.

**Comment by hpvb** [comment]
The crash happens because item comparison fails when there are NaNs in complex types. This is the crash issue. The item comparison has to be removed, or fixed to account for NaNs. The latter should not be done without basically implementing exactly what I did, but by adding it as a different equality check other than OP_EQ.

This was my preferred solution at the beginning.

In *addition* to this we can try to make divide by zero explicitly illegal in GDscript, but I don't think we currently have the error reporting mechanisms in place to make this a runtime detectable error that a game can recover from. We have no exceptions and there's no 'error value' type either. Returning NaN seems entirely reasonable to me.

**Comment by tagcup** [comment]
Can you expand on why you don't think memcmp will work in hash map?

**Comment by hpvb** [comment]
The in-memory representation of 'NaN' is implementation defined and there is no guarantee that two NaN values obtained by different means will have the same bit pattern in RAM. This means that the same crash may reoccur if two constants get created, both with NaN's in them but arrived at by a different path.

**Comment by hpvb** [comment]
Also, note that your link as to the reason why nan != nan talks about old computers lacking an is_nan() function. GDScript DOES have it so as far as how terrible this solution is it's not so bad. And perhaps @reduz wasn't so wrong to want this behavior after all.

**Comment by tagcup** [comment]
> The in-memory representation of 'NaN' is implementation defined and there is no guarantee that two NaN values obtained by different means will have the same bit pattern in RAM. 

I know that. What I'm asking you is, is there any harm in putting those (let's say +0.0/0.0 vs -0.0/0.0) in different bins in practice, for GDScript?

> Also, note that your link as to the reason why nan != nan talks about old computers lacking an is_nan() function.

No, this isn't something tied to x87. The reason you can't compare two NaNs is because you can only compare numbers. You can't compare things that are not (real) numbers. [Hyperreal numbers](https://en.wikipedia.org/wiki/Hyperreal_number)  are not covered by IEEE-754 floats, it only covers real numbers.

Anyway, I think this PR should be undone either for reasons I've explained, and @reduz also agrees.

We can move this discussion about what to do (which is a separate discussion) elsewhere.

**Comment by hpvb** [comment]
I'm sorry, what does the working of the hardware have to do with semantics we choose for gdscript?

**Comment by tagcup** [comment]
Because rolling a new floating point standard that behaves differently than the hardware is error-prone, requires lengthy hacks for *all* IEEE-754 float that GDScript has access, and will result in wrong mathematics in certain cases.

**Comment by hpvb** [comment]
The amount of work that needs to be done to make it work is what's done now. You admitted earlier that you don't know the internals of gdscript. Don't tell me what I did is wrong and then claim ignorance of the subject matter.

None of the maths involved with nan have been changed, only nan equality has been changed. This means that you can't check for nan with if x== x. 

What other operations are going to fail now?

**Comment by tagcup** [comment]
@Akien I'm not going to reply to insults with insults, so I'm done talking to him/her. I gave my reasoning, and @reduz seems to agree with it. See for yourself.

**Comment by reduz** [comment]
OK guys, this argument is going too far. Here's some facts so we can decide
better what to do.

1) Using nan as equality seems valid in Python for dictionary keys:

>>> a = float('nan')
>>> d = { a:2 }
>>> print d
{nan: 2}
>>> print d[a]
2

2) I agree that we should check for nan at compile time and error

**Comment by hpvb** [comment]
How did I insult anyone? You literally said you didn't know about the internals of gdscript, but you do seem to know is that more lengthy hacks are required? This is wrong. You can talk about not liking the semantics, and maybe this should be changed. But on the one hand saying 'i don't know about the internals of gdscript but I know what you did is technically wrong' is pretty belittling in my book.

**Comment by reduz** [comment]
so I suggest the following, what do you think?

1)  we revert the PR at least the part that implies the operators in variant
2)  we make sure dividing by zero is an error in GDScript, be it for scalar
or vector types (I think it already is for scalar)
3)  we add a special equality function for dictionaries, so we can use it
as dictionary key

**Comment by reduz** [comment]
geez, take it easy, too much passion in this argument :)

**Comment by bojidar-bg** [comment]
Dividing by 0 in GDScript is error only for integer types, for floats it makes a `nan` currently.

**Comment by tagcup** [comment]
@reduz, I'd say great as long as the issue is confined within GDScript module :)

Adding a special function for dictionaries will still require adding a new comparison function for *all* data structures out there though, right? Hash maps in other languages typically just do a byte-by-byte memory comparison, which we can also do here I think.

While the side effects of hashing two different NaNs (meaning two different bit patterns) can be argued as a separate subject, after making a few experiments, so far I could only get either 0x7FC00000 or 0xFFC00000 on amd64 (it can range between 0x7FC00000-0x7FFFFFFF or 0xFFC00000 0xFFFFFFFF per IEEE-754 standard). So to me it seems there's only NAN and -NAN (the constant defined in math.h) in practice, which sounds fairly OK.

**Comment by hpvb** [comment]
The hashing already works. It's the item *comparison*. Things hashing to the same value but the comparisons failing is the root of this issue. Your solution does nothing to mitigate that.

We need to remove the comparison optimization or implement the 6 methods to implement nan-based comparison for dict keys and hashmap items.

**Comment by reduz** [comment]
There is also 0 and -0, so probably hashing is kinda broken already in
Variant. So I guess the step would be like

1) improve hashing of floats in Variant, fix those cases to avoid redundancy
2) add a special function in Variant for hash_compare(), which uses the
operators added, checking for nan (or is there a better way to compare?)
3) make Dictionary use that comparison instead of regular one
4) make GDScript fail on vector division by zero

**Comment by hpvb** [comment]
@reduz, ok lets just revert everything then and I'll make several PRs to implement the above described things. I'm not entirely convinced that making a special case for constants being 0 in divisions really helps much. You can probably still get a 0 at runtime.

**Comment by tagcup** [comment]
2) So I was basically asking, can't we simply hash the data as raw bytes (maybe that's how it is already), and compare it as raw bytes in variant?

**Comment by reduz** [comment]
@hpvb the checking for 0 in variant_op is just to filter those mistakes as much as possible, the idea is that we also fix it in Dictionary, to avoid crashes

**Comment by tagcup** [comment]
@reduz: Simply because if you treat them as raw bytes both when hashing and comparing, things that has the same hash will also be equal.

**Comment by reduz** [comment]
@tagcup yeah that might work, but we need to get rid of the redundant info, as in, 0 and -0, nan and -nan. I'm sure there has to be code on the net for float hashing

**Comment by hpvb** [comment]
hashing them as raw bytes would potentially mean that { nan, 2 } != { (1.0/0), 2} for instance. This would seem to me to be rather unintuitive.

**Comment by tagcup** [comment]
@reduz Yes, but that's how it is in other languages too. Go's built-in map behaves exactly like that for example.

**Comment by reduz** [comment]
@hpvp hashing them is unavoidable as raw bytes, but from what i've been reading around, if we get rid of -0 it should work.

**Comment by hpvb** [comment]
@reduz if we get rid of some of the values then we're not just treating it as raw bytes, we need to treat some nan values special. That was what I meant.

**Comment by reduz** [comment]
how many nan values are there?

**Comment by bojidar-bg** [comment]
Citing https://en.wikipedia.org/wiki/IEEE_floating_point
> * Two kinds of NaN: a quiet NaN (qNaN) and a signaling NaN (sNaN). A NaN may carry a payload that is intended for diagnostic information indicating the source of the NaN. The sign of a NaN has no meaning, but it may be predictable in some circumstances.

I guess "Near-infinite" is good as an answer?

**Comment by tagcup** [comment]
@reduz I realized that requiring a float-aware special function like hash_compare() not only places a burden to other GDScript-accessible classes within Godot, but also to user-defined objects (such as modules or plugins).

At this point, preventing NaNs in GDScript as best as possible sounds like the simplest workaround I can think of.
