### PR TITLE
[Windows] Fix icon leak.

### LINKED ISSUE #114496: GDI object leak on Windows with embed_subwindows = false
### Tested versions

- Reproduceable in all tested Godot 4 versions (stable, latest, older version)

### System information

Windows 10

### Issue description

The issue can be reproduced when the project setting `window/subwindows/embed_subwindows` = false.
Every time a window is added to the scene tree and removed, GDI objects are not properly removed and thus leak.

A simple way of observing this is to open the task manager -> details -> add GDI objects to the colums.

https://github.com/user-attachments/assets/ac171791-38c5-4174-8d59-884791757ce6

### Steps to reproduce

- Disable embed_subwindows in project settings.
- Add a window to the scene tree
- queue_free the window

### Minimal reproduction project (MRP)

[gdi-leak.zip](https://github.com/user-attachments/files/24400719/gdi-leak.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/114496
Supersede https://github.com/godotengine/godot/pull/113421
*Bugsquad edit:* Should also fix #113350

### CODE REVIEW

File: platform/windows/display_server_windows.cpp [hunk 1]
```diff
@@ -2451,8 +2451,16 @@ void DisplayServerWindows::_update_window_style(WindowID p_window, bool p_repain
 	SetWindowLongPtr(wd.hWnd, GWL_STYLE, style);
 	SetWindowLongPtr(wd.hWnd, GWL_EXSTYLE, style_ex);
 
-	if (icon.is_valid()) {
-		set_icon(icon);
+	if (icon_big && !icon_small) {
+		SendMessage(wd.hWnd, WM_SETICON, ICON_SMALL, (LPARAM)icon_big);
+		SendMessage(wd.hWnd, WM_SETICON, ICON_SMALL, (LPARAM)icon_big);
```
Comment (Maran23) [inline platform/windows/display_server_windows.cpp]: This is the same call twice. Is that intended?

Comment (bruvzg) [reply platform/windows/display_server_windows.cpp]: No, one should be `ICON_BIG`.

**Review by akien-mga — APPROVED** [review]

File: platform/windows/display_server_windows.cpp [hunk 2]
```diff
@@ -4058,26 +4078,23 @@ void DisplayServerWindows::set_icon(const Ref<Image> &p_icon) {
...
-
-		icon = img;
-
-		// Set the icon for the window.
-		SendMessage(windows[MAIN_WINDOW_ID].hWnd, WM_SETICON, ICON_SMALL, (LPARAM)hicon);
-
-		// Set the icon in the task manager (should we do this?).
-		SendMessage(windows[MAIN_WINDOW_ID].hWnd, WM_SETICON, ICON_BIG, (LPARAM)hicon);
+		for (const KeyValue<WindowID, WindowData> &E : windows) {
+			SendMessage(E.value.hWnd, WM_SETICON, ICON_SMALL, (LPARAM)icon_big);
```
Comment (Maran23) [inline platform/windows/display_server_windows.cpp:4085]: Question just to be sure: This should use `icon_big` and not `icon_small`, right?

**Review by Maran23 — APPROVED** [review]
Looks good to me, just one question.

File: platform/windows/display_server_windows.cpp (hunk 2 above)
Comment (bruvzg) [reply platform/windows/display_server_windows.cpp:4085]: Yes, it is generated icon, so the same is used for both, `icon_small` is not set in this case.
