### PR TITLE
Fix `activate_item_by_event` infinite recursion crash

### LINKED ISSUE #84176: Executing `PopupMenu.activate_item_by_event` function crashes Godot
### Godot version

4.2.beta.custom_build. 914445748

### System information

Ubuntu 22.04 CI

### Issue description

When executing (this code was automatically minimized, so it is possible, that an even more "minimal" project can be created)
```
extends Node
func _process(delta):
	var temp_variable11695 = PopupMenu.new()
	add_child(temp_variable11695)
	temp_variable11695.add_submenu_item("", ".", -18)
	temp_variable11695.activate_item_by_event(InputEventJoypadMotion.new(), false)
```
Godot crashes:
```
Godot Engine v4.2.beta.custom_build.914445748 - https://godotengine.org
Time set to: 0 seconds.
Loaded settings:
modules/gdscript/gdscript_vm.cpp:698:13: runtime error: store to misaligned address 0x61600014e024 for type '<unknown> *', which requires 8 byte alignment
0x61600014e024: note: pointer points here
  01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  0a 00 00 00 02 00 00 00  09 00 00 00 17 00 00 00
              ^ 
modules/gdscript/gdscript_vm.cpp:705:42: runtime error: load of misaligned address 0x61600014e024 for type '<unknown> *', which requires 8 byte alignment
0x61600014e024: note: pointer points here
  01 00 00 00 94 62 f5 e4  19 56 00 00 00 00 00 00  0a 00 00 00 02 00 00 00  09 00 00 00 17 00 00 00
              ^ 
######################## Ending test ########################
Segmentation fault (core dumped)
```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

Memory leaks or asan backtraces are visible when using Godot build with sanitizers support - https://github.com/qarmin/GodotBuilds/actions (linux -> linux-editor-sanitizers)

   

### Steps to reproduce

Above

### Minimal reproduction project

Above

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes #84176

The crash cames from `activate_item_by_event` will call itself on it's submenu item found by name, but if the submenu's name is `.`, it will enter infinite resursion.

I chose to prevent it happen from `add_submenu_item`, but there might be other ways I wasn't aware of. Feel free to correct me.

### CODE REVIEW

File: scene/gui/popup_menu.cpp [hunk 1]
```diff
@@ -1487,6 +1488,7 @@ void PopupMenu::add_icon_radio_check_shortcut(const Ref<Texture2D> &p_icon, cons
 }
 
 void PopupMenu::add_submenu_item(const String &p_label, const String &p_submenu, int p_id) {
+	ERR_FAIL_COND_MSG(p_submenu == SceneStringNames::get_singleton()->dot || p_submenu == SceneStringNames::get_singleton()->doubledot, "Don't use . as submenu's name.");
```
Comment (YuriSizov) [inline scene/gui/popup_menu.cpp:1491]: You should use `String::validate_node_name()` and then compare the result to the original name and see if it matches. See `SceneTreeEditor::_rename_node` for an example on how to handle it (with a more explicit error message too).

**Review by YuriSizov — CHANGES_REQUESTED** [review]
See above.

File: scene/gui/popup_menu.cpp (hunk 1 above)
Comment (jsjtxietian) [reply scene/gui/popup_menu.cpp:1491]: Thanks! There are so many good practices I'm not aware of.

File: scene/gui/popup_menu.cpp [hunk 2]
```diff
@@ -38,6 +38,7 @@
 #include "core/string/print_string.h"
 #include "core/string/translation.h"
 #include "scene/gui/menu_bar.h"
+#include "scene/scene_string_names.h"
```
Comment (YuriSizov) [inline scene/gui/popup_menu.cpp:41]: You don't need this anymore.

**Review by YuriSizov — APPROVED** [review]
Other than one small change, this is good.

File: scene/gui/popup_menu.cpp (hunk 2 above)
Comment (jsjtxietian) [reply scene/gui/popup_menu.cpp:41]: Thanks! I forgot to delete it.

**Comment by akien-mga** [comment]
Thanks!
