### PR TITLE
Fire `ItemList.item_clicked` signal when deselecting multi items with CTRL

### LINKED ISSUE #108228: ItemList Ctrl Click on Multi Selected Items Does Not Emit "item_clicked" Signal - Only Occurs When Deselecting an Item From the List of Selected Items
### Tested versions

- Reproducible in: v4.5-beta2, v4.4.1-stable, v4.4.0, v4.3-stable, v4.2.2-stable, v4.1.2-stable.

### System information

Godot v4.4.1.stable - Windows 11 (build 26100) - Multi-window, 3 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3070 Laptop GPU (NVIDIA; 32.0.15.7602) - Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz (16 threads)

### Issue description

When using an ItemList with `select_mode` set to `multi`, and having selected a few items from the list of choices using `Shift + Left Click`, I find that deselecting a single item from that list (order does not matter) using `Ctrl + Left Click` does not cause the `item_clicked` signal to be emitted.
Even though `Ctrl + Left Click` on an unselected item does cause the `item_clicked` signal to be emitted, I would have imagined that doing the same thing to deselect the item would cause the same signal to be emitted, but it does not.

Image

Gif demonstrates what happens when trying to deselect items in a list of selected items and the prints to the console to visually confirm signal emission.

### Steps to reproduce

- Download, extract and run Minimal Reproduction Project.
- Run the *item_list_test_scene.tscn* scene in the editor.
- `Left Click` on any item in the list.
- `Shift + Left Click` on any other item in the list so that multiple items are now selected.
- Now press `Ctrl + Left Click` on an item in the list and notice how there is no output in the editor console.
- Pressing `Ctrl + Left Click` again on the same item, will show a new print statement in the editor console.

### Minimal reproduction project (MRP)

[itemlist_item_clicked_bug_mrp.zip](https://github.com/user-attachments/files/21029520/itemlist_item_clicked_bug_mrp.zip)

### PR DESCRIPTION
**Pull request by YeldhamDev**
Fixes #108228.

### CODE REVIEW

File: scene/gui/item_list.cpp [hunk 1]
```diff
@@ -788,6 +788,7 @@ void ItemList::gui_input(const Ref<InputEvent> &p_event) {
 			if (select_mode == SELECT_MULTI && items[i].selected && mb->is_command_or_control_pressed()) {
 				deselect(i);
 				emit_signal(SNAME("multi_selected"), i, false);
+				emit_signal(SNAME("item_clicked"), i, get_local_mouse_position(), mb->get_button_index());
```
Comment (KoBeWi) [inline scene/gui/item_list.cpp:791]: This could do
```suggestion
				emit_signal(SNAME("item_clicked"), i, mb->get_position(), mb->get_button_index());
```
but it's currently consistent with other calls, so it's fine either way.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Comment by Repiteo** [comment]
Cherry-picked for 4.6.3.
