### PR TITLE
update algorithm about paking float to vec4 to fix shadow slipping

### LINKED ISSUE #29030: Light2D shadows slipping away from objects in GLES3
**Godot version:**
3.2 or, commit
8b0ea337771a2ec04f8c731601c6a0518187b328

**OS/device including version:**
Ubuntu 18.04, ZOTAC GTX 1050 Mini, Kernel 4.16.18

**Issue description:**
Light2D's shadows slip away from what they're casting on (light occluder 2d's, to be specific); especially with far Light2D->object distances.
GLES2 shadows don't do this. This only happens in GLES3. I've also tested this on Windows 10, and had the same issue, but I can't double check that.

**Steps to reproduce:**
Make a Light2D, move it far away, then make a light occluder 2d.

**Minimal reproduction project:**
[LightsTest.zip](https://github.com/godotengine/godot/files/3198066/LightsTest.zip)

### PR DESCRIPTION
**Pull request by Raphael2048**
Fix https://github.com/godotengine/godot/issues/29030
1 According to this article http://aras-p.info/blog/2009/07/30/encoding-floats-to-rgba-the-final/
 use 255 instead of 256 is more precise.
2 It seems that its default option is not correct, since we should not use rgba_shdow in gles3 when framebuffer_float is supported, and in gles2 we should use rgba_shadow in default to improve preciseness.

### CODE REVIEW

File: drivers/gles2/rasterizer_storage_gles2.cpp [hunk 1]
```diff
@@ -5634,7 +5634,7 @@ void RasterizerStorageGLES2::initialize() {
 	config.multisample_supported = config.extensions.has("GL_EXT_framebuffer_multisample") || config.extensions.has("GL_EXT_multisampled_render_to_texture") || config.extensions.has("GL_APPLE_framebuffer_multisample");
 
 #ifdef GLES_OVER_GL
-	config.use_rgba_2d_shadows = false;
+	config.use_rgba_2d_shadows = true;
```
Comment (clayjohn) [inline drivers/gles2/rasterizer_storage_gles2.cpp]: This should remain false because desktop always supports floating point textures. Floating point textures are preferred, encoding to RGBA is only used as a fallback when floating point isnt available.

**Review by clayjohn — CHANGES_REQUESTED** [review]
After the change above it should be good to merge!

**Comment by aaronfranke** [comment]
I can confirm that it's better to use 255 instead of 256, and this would also be in line with core's color code: https://github.com/godotengine/godot/blob/master/core/color.cpp#L38

**Comment by raphael10241024** [comment]
Resolved

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
