### PR TITLE
Fix FileSystem dock auto translating files

### LINKED ISSUE #89596: Folder names in the file system are translated unexpectedly
### Tested versions

Godot v4.3.dev5.mono

### System information

Godot v4.3.dev5.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 Ti (NVIDIA; 31.0.15.3667) - Intel(R) Core(TM) i5-10200H CPU @ 2.40GHz (8 Threads)

### Issue description

Folder names in the file system are translated unexpectedly, these should not be translated
QQ截图20240317133008

### Steps to reproduce

1. Create a new project
2. Create a new folder, name it "Red"
3. Switch editor language to non-English
4. Folder name is now displayed as translated

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by YeldhamDev**
Addresses https://github.com/godotengine/godot/pull/89032#issuecomment-2000550973.

* *Bugsquad edit, closes: #89596*

### CODE REVIEW

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -72,6 +72,10 @@ Control *FileSystemTree::make_custom_tooltip(const String &p_text) const {
 	return FileSystemDock::get_singleton()->create_tooltip_for_path(item->get_metadata(0));
 }
 
+FileSystemTree::FileSystemTree() {
+	set_auto_translate(false);
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:76]: This method is deprecated 🙃
Also you don't need to create a constructor to set it.

Comment (YeldhamDev) [reply editor/filesystem_dock.cpp:76]: Brain fart. :stuck_out_tongue_closed_eyes:
But, where else do I set it? Unless you mean setting it outside the class by its parent, which feels a wee-bit hacky.

Comment (KoBeWi) [reply editor/filesystem_dock.cpp:76]: > Unless you mean setting it outside the class by its parent

Yes, that's how auto-translation is disabled everywhere else. The fact that FileSystemTree is a custom class does not make it suddenly a bad solution.

Comment (YeldhamDev) [reply editor/filesystem_dock.cpp]: I disagree a little, but it's not a hill worth dying for, change made.

Comment (timothyqiu) [reply editor/filesystem_dock.cpp]: I did something similar in the constructor of `FileSystemList` (#88716)

Most controls are translating by default because they are for general use. For a control that displays filenames, it makes sense to default to not translating.

**Review by KoBeWi — APPROVED** [review]

File: editor/filesystem_dock.cpp (hunk 1 above)
Comment (KoBeWi) [reply editor/filesystem_dock.cpp]: FileSystemList already had a constructor.
Either way, if there is a single instance of the class, it doesn't matter.

**Comment by akien-mga** [comment]
Thanks!
