### PR TITLE
Fix _class_desc_select to handle Variant.Type

### LINKED ISSUE #40290: Variant.Type enum is not properly linked in Editor docs (web version works fine)
**Godot version:** 3.2.2

**OS/device including version:** Solus Linux / Linux Mint 20

**Issue description:** when clicking link to Variant.Type enum (such as under GDScript typeof() function), you get taken to the Variant class page as opposed to the Variant.Type under GlobalScope

Initially found by vonflyhighace2#6347 on Discord.

**Steps to reproduce:** open *in-editor* docs to the GDScript page; navigate to typeof() function; click "Variant.Type"

**Minimal reproduction project:** N/A

### PR DESCRIPTION
**Pull request by snailrhymer**
Fixes #40290 by changing the order of checks in _class_desc_select to first try checking current page and GlobalScope
before resorting to slicing either side of ".". This may change previous search behaviours - previously if both x.y and  @GlobalScope.x.y existed, _class_desc_select would select the former; it will now select the latter. Is this a problem?

An alternative fix is to change `Variant.X` links in the class reference to `@GlobalScope.Variant.X` (this may be desirable anyway for consistency) and replace

```
if (link.contains(".")) {
    emit_signal(SNAME("go_to_help"), topic + ":" + link.get_slice(".", 0) + ":" + link.get_slice(".", 1));
} else {...
```
with
```
if (link.contains(".")) {
	if (link.get_slice_count(".") == 2){
		emit_signal(SNAME("go_to_help"), topic + ":" + link.get_slice(".", 0) + ":" + link.get_slice(".", 1));
	} else if (link.get_slice_count(".") == 3){
		emit_signal(SNAME("go_to_help"), topic + ":" + link.get_slice(".", 0) + ":" + link.get_slice(".", 1) + "." + link.get_slice(".", 2));
	}
} else {...
```
which feels more targeted at this particular bug

***

The bug was caused by the assumption that no enums or constants in @GlobalScope would contain ".", or that no link would contain more than one ".". This is still assumed at multiple other points in the file (example [1](https://github.com/godotengine/godot/blob/5c54770b7cd0be8ed6e9229fd253ae0d98f8b275/editor/editor_help.cpp#L84), [2](https://github.com/godotengine/godot/blob/5c54770b7cd0be8ed6e9229fd253ae0d98f8b275/editor/editor_help.cpp#L1938)) , so there may be other ways to trigger #40290 that this PR doesn't fix. (I'm not confident I understand the context of these well enough to change them.)

### CODE REVIEW

**Comment by snailrhymer** [comment]
Or would it make more sense to rename `Variant.Type` and `Variant.Operator`, removing the "." to bring them in line with the other GlobalScope enums?

File: editor/editor_help.cpp [hunk 1]
```diff
@@ -123,37 +123,34 @@ void EditorHelp::_class_desc_select(const String &p_select) {
...
-					const DocData::ClassDoc &cd = doc->class_list["@GlobalScope"];
-
-					for (int i = 0; i < cd.constants.size(); i++) {
-						if (cd.constants[i].name == link) {
-							// Found in @GlobalScope
-							emit_signal(SNAME("go_to_help"), topic + ":@GlobalScope:" + link);
-							break;
-						}
-					}
+		// Case order is important here to correctly handle edge cases like Variant.Type in @GlobalScope
```
Comment (KoBeWi) [inline editor/editor_help.cpp:126]:
```suggestion
		// Case order is important here to correctly handle edge cases like Variant.Type in @GlobalScope.
```

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by snailrhymer** [comment]
Found a bug backporting, so will backport #61242 instead once it's merged.
