### PR TITLE
3.x Fix "mass" and "weight" properties of the RigidBody (and RigidBody2D) in the Inspector view

### LINKED ISSUE #57226: [3.x] Editor doesn't allow to set mass/weight of RigidBody/RigidBody2D node more than 65535
### Godot version

Godot_v3.4.2-stable_win64

### System information

Windows 10 x64

### Issue description

The mass (and weight) property of RigidBody is a float. But in the Editor it's looks like an unsigned short (2-bytes integer). If you try to set mass of RigidBody more than 65535 in the Inspector view, then value will be clamped to 65535. But in script you can set mass to any positive float value and it will be valid (not clamped and works as expected).

### Steps to reproduce

1. Open/Create any project.
2. Open/Create any scene with RigidBody or RigidBody2D node
3. Try to set mass or weight property to 100000 in Inspector

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Fitch24**
Allow to set any valid values for "mass" and "weight" properties of RigidBody/RigidBody2D node in Inspector. Closes #57226

### CODE REVIEW

**Comment by Chaosus** [comment]
Please squash the commits as required by our pipeline: https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request

File: scene/2d/physics_body_2d.cpp [hunk 1]
```diff
@@ -905,9 +905,9 @@ void RigidBody2D::_bind_methods() {
 	BIND_VMETHOD(MethodInfo("_integrate_forces", PropertyInfo(Variant::OBJECT, "state", PROPERTY_HINT_RESOURCE_TYPE, "Physics2DDirectBodyState")));
 
 	ADD_PROPERTY(PropertyInfo(Variant::INT, "mode", PROPERTY_HINT_ENUM, "Rigid,Static,Character,Kinematic"), "set_mode", "get_mode");
-	ADD_PROPERTY(PropertyInfo(Variant::REAL, "mass", PROPERTY_HINT_EXP_RANGE, "0.01,65535,0.01"), "set_mass", "get_mass");
-	ADD_PROPERTY(PropertyInfo(Variant::REAL, "inertia", PROPERTY_HINT_EXP_RANGE, "0.01,65535,0.01", 0), "set_inertia", "get_inertia");
-	ADD_PROPERTY(PropertyInfo(Variant::REAL, "weight", PROPERTY_HINT_EXP_RANGE, "0.01,65535,0.01", PROPERTY_USAGE_EDITOR), "set_weight", "get_weight");
+	ADD_PROPERTY(PropertyInfo(Variant::REAL, "mass", PROPERTY_HINT_RANGE, "0.01,65535,0.01,or_greater,exp"), "set_mass", "get_mass");
+	ADD_PROPERTY(PropertyInfo(Variant::REAL, "inertia", PROPERTY_HINT_RANGE, "0.01,65535,0.01,or_greater,exp", 0), "set_inertia", "get_inertia");
+	ADD_PROPERTY(PropertyInfo(Variant::REAL, "weight", PROPERTY_HINT_RANGE, "0.01,65535,0.01,or_greater,exp", PROPERTY_USAGE_EDITOR), "set_weight", "get_weight");
```
Comment (akien-mga) [inline scene/2d/physics_body_2d.cpp:910]: I think `,exp` is a 4.0-specific hint, in `3.x` the equivalent is `PROPERTY_HINT_EXP_RANGE` which this diff removes. So this probably makes it no longer be increasing exponentially.

File: scene/2d/physics_body_2d.cpp [hunk 2]
```diff
@@ -905,9 +905,9 @@ void RigidBody2D::_bind_methods() {
 	BIND_VMETHOD(MethodInfo("_integrate_forces", PropertyInfo(Variant::OBJECT, "state", PROPERTY_HINT_RESOURCE_TYPE, "Physics2DDirectBodyState")));
 
 	ADD_PROPERTY(PropertyInfo(Variant::INT, "mode", PROPERTY_HINT_ENUM, "Rigid,Static,Character,Kinematic"), "set_mode", "get_mode");
-	ADD_PROPERTY(PropertyInfo(Variant::REAL, "mass", PROPERTY_HINT_EXP_RANGE, "0.01,65535,0.01"), "set_mass", "get_mass");
-	ADD_PROPERTY(PropertyInfo(Variant::REAL, "inertia", PROPERTY_HINT_EXP_RANGE, "0.01,65535,0.01", 0), "set_inertia", "get_inertia");
-	ADD_PROPERTY(PropertyInfo(Variant::REAL, "weight", PROPERTY_HINT_EXP_RANGE, "0.01,65535,0.01", PROPERTY_USAGE_EDITOR), "set_weight", "get_weight");
+	ADD_PROPERTY(PropertyInfo(Variant::REAL, "mass", PROPERTY_HINT_RANGE_EXP, "0.01,65535,0.01,or_greater"), "set_mass", "get_mass");
+	ADD_PROPERTY(PropertyInfo(Variant::REAL, "inertia", PROPERTY_HINT_RANGE_EXP, "0.01,65535,0.01,or_greater", 0), "set_inertia", "get_inertia");
+	ADD_PROPERTY(PropertyInfo(Variant::REAL, "weight", PROPERTY_HINT_RANGE_EXP, "0.01,65535,0.01,or_greater", PROPERTY_USAGE_EDITOR), "set_weight", "get_weight");
```
Comment (akien-mga) [inline scene/2d/physics_body_2d.cpp:910]: That won't compile, it's `PROPERTY_HINT_EXP_RANGE`, not `PROPERTY_HINT_RANGE_EXP`.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
