### PR TITLE
Prevent shaders from generating code before the constructor finishes.

### LINKED ISSUE #43733: Creating SpatialMaterial in a separate thread  creates invalid shaders (temporarily)
**Godot version:**
3.2.3-stable

**OS/device including version:**

**Issue description:**

When using InteractiveResourceLoader in a background thread, occasionally you will see an error message printed about invalid shaders.

**Steps to reproduce:**

https://docs.godotengine.org/en/stable/_downloads/db6ccb8924e9f1d36c1319e2813e4808/resource_queue.gd

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by tcoxon**
> Fixes #43733: "creating SpatialMaterial in a separate thread creates invalid
> shaders (temporarily)."
> 
> The bug occurred because various setters called in materials' constructors add
> materials to queues that are processed on the main thread. This means that
> when the materials are created in another thread, they can be processed on the
> main thread before the constructor has finished.
> 
> The fix adds a flag to affected materials that prevents them from being added
> to the queue until their constructors have finished initialising all the
> members.

Although the issue was reported on 3.x, this PR is for the master branch. I haven't been able to reproduce the symptoms of the issue on master (it is very sensitive to threads & timing), however inspection of the code leads me to believe it is affected regardless.

### CODE REVIEW

**Comment by clayjohn** [comment]
Because 3.x and 4,0 have diverged, this PR won't be able to be cherrypicked for 3.x. So could you please make another PR with the same changes but for 3.x?

**Comment by tcoxon** [comment]
I've created #52475 for 3.x.

I'll fix the static checks and update the branch tomorrow.

File: scene/resources/canvas_item_material.h [hunk 1]
```diff
@@ -102,6 +102,7 @@ class CanvasItemMaterial : public Material {
 	_FORCE_INLINE_ void _queue_shader_change();
 	_FORCE_INLINE_ bool _is_shader_dirty() const;
 
+	bool is_initialized;
```
Comment (akien-mga) [inline scene/resources/canvas_item_material.h:105]: This should be initialized here instead of in the constructor.

File: scene/resources/canvas_item_material.cpp [hunk 2]
```diff
@@ -159,6 +159,9 @@ void CanvasItemMaterial::flush_changes() {
 }
 
 void CanvasItemMaterial::_queue_shader_change() {
+	if (!is_initialized)
+		return;
```
Comment (akien-mga) [inline scene/resources/canvas_item_material.cpp:163]: Style issue:
```suggestion
	if (!is_initialized) {
		return;
	}
```
(Same for 3D)

**Review by akien-mga — APPROVED** [review]
Aside from style issues (please fix them with `git commit --amend` and force push instead of a separate commit), this looks good to me.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
