### PR TITLE
CanvasItemEditor: Fix snapping grid misalignment

### LINKED ISSUE #70186: Godot 4 b8's UI-Ruler & grid getting corrupted and becomes inaccurate.
### Godot version

Godot 4, beta 8 (.net c# version)

### System information

Windows 11 21H2

### Issue description

When mapping out a simple "level" in my proto-type 2d platformer, have noticed the grid becomes mis-aligned compared to the "2nd" grid provided by the tilemap. The further away from scene origin tiles are placed the greater the mis-alignment is.

### Steps to reproduce

Create a new project in godot 4 b8.
Create a new 2D scene, name it what ever.
Click on "..." configure snap.
Change grid step from it's default to some other number (ex 4px 4px).
Save the empty scene.
Using your operating system, navigate to <testproj>/.godot/editor
Using a text editor open up your scene's "editstate" config file.
Observe under section 2D={} "grid_step": Vector2(4.01, 4.01). -- grid_step is no longer a whole number but now a decimal.
Go back to godot.
Observe that your scene's ruler and grid are now more and more inaccurate the further from origin you go. Also notice your UI-Ruler now has a decimal place instead of whole numbers as markers.
This becomes very evident when placing tiles, a huge mis-alignment begins to occur.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by phnix-dev**
Resolves: #70186
See: #65101

### CODE REVIEW

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -135,7 +137,7 @@ class SnapDialog : public ConfirmationDialog {
 		label->set_h_size_flags(Control::SIZE_EXPAND_FILL);
 
 		grid_step_x = memnew(SpinBox);
-		grid_step_x->set_min(0.01);
+		grid_step_x->set_min(0);
```
Comment (Maran23) [inline editor/plugins/canvas_item_editor_plugin.cpp:140]: Wouldn't it make sense to set this minimum to 1 as well?

Comment (kleonc) [reply editor/plugins/canvas_item_editor_plugin.cpp:140]: Agree, I'd just move `SPIN_BOX_STEP_MIN` to the constructor (and rename it to `SPIN_BOX_GRID_STEP_MIN`) and use it only in the both `set_min` calls. Then the changes in `get_fields` shouldn't be needed anymore, could be reverted.

Comment (MrPhnix) [reply editor/plugins/canvas_item_editor_plugin.cpp]: > Wouldn't it make sense to set this minimum to 1 as well?

Yes, I did not think of that because the minimum value of the range was 0.01.
Thanks 👍, it's fixed now.

**Comment by kleonc** [comment]
@MrPhnix A single commit is preferred so please `rebase` + `squash`/`fixup` your commits. For how-to see [PR worflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) in the docs.

**Comment by MrPhnix** [comment]
Sorry, it should be good now.

**Review by kleonc — APPROVED** [review]

**Review by Maran23 — APPROVED** [review]
Looks good to me too!

**Comment by kleonc** [comment]
@MrPhnix Sorry but I forgot to check the commit message / PR title. Please change them (both PR title and commit message) to be more descriptive. _"Fix grid misalignment"_ is too vague as there are many different grids across the engine. Something like _"CanvasItemEditor Fix snapping grid misalignment"_ should be good enough.

**Review by kleonc — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by iamjoeysox** [comment]
Was this supposed to fix the following issue? If so, I am still seeing this on Mac 13.1, I was really hoping this would be fixed on beta 11... :(

Screenshot on 2023-01-14 at 3 51 52 PM

**Comment by akien-mga** [comment]
You may have to change the grid step manually you have the old value saved.

**Comment by iamjoeysox** [comment]
> You may have to change the grid step manually if you have the old value saved.

Where is that file located on Mac? Thanks for the tip btw.

**Comment by Maran23** [comment]
Just open the grid settings dialog and set a new value manually. This should recalculate the grid and therefore fix this.

**Comment by iamjoeysox** [comment]
> Just open the grid settings dialog and set a new value manually. This should recalculate the grid and therefore fix this.

Yeah, just figured this out when I read the following comment, thanks again for the help!

https://github.com/godotengine/godot/issues/70186#issuecomment-1377709882

**Comment by Torguen** [comment]
What will happen to the objects that have been incorrectly assigned to the grid?
Will they be reassigned correctly or will they be incorrectly assigned and will have to be reassigned manually? that would be crazy.

**Comment by kleonc** [comment]
> What will happen to the objects that have been incorrectly assigned to the grid when this solution is applied in 3.6? Will they be reassigned correctly and automatically or will they be misassigned and will have to be reassigned manually?

Nothing will happen to such objects, they will retain their saved positions however they were originally positioned. This grid snapping is editor-only thing applied when manually drag-positioning the objects within the editor. It results in setting a snapped position for the given object(s) only during such manual positioning, it doesn't make the object be permanently snapped or anything like that. From the object's point of view such snapped position is a postion like any other, the object doesn't know it's snapped, it can be still repositioned freely.
So yes, the saved snapping errors caused be the bug being fixed here will not magically disappear.

>that would be crazy.

Bugs are crazy and can lead to crazy situations indeed. :upside_down_face: What you could do to fix the misalignment is e.g. writing a tool script which would re-snap the meant-to-be-snapped objects (possibly by doing just `position = position.round()` if the objects were meant to be snapped to some integer sized grid).

**Comment by Torguen** [comment]
> > What will happen to the objects that have been incorrectly assigned to the grid when this solution is applied in 3.6? Will they be reassigned correctly and automatically or will they be misassigned and will have to be reassigned manually?
> 
> Nothing will happen to such objects, they will retain their saved positions however they were originally positioned. This grid snapping is editor-only thing applied when manually drag-positioning the objects within the editor. It results in setting a snapped position for the given object(s) only during such manual positioning, it doesn't make the object be permanently snapped or anything like that. From the object's point of view such snapped position is a postion like any other, the object doesn't know it's snapped, it can be still repositioned freely. So yes, the saved snapping errors caused be the bug being fixed here will not magically disappear.
> 
> > that would be crazy.
> 
> Bugs are crazy and can lead to crazy situations indeed. 🙃 What you could do to fix the misalignment is e.g. writing a tool script which would re-snap the meant-to-be-snapped objects (possibly by doing just `position = position.round()` if the objects were meant to be snapped to some integer sized grid).

Ok, thanks for the info!.

**Comment by Torguen** [comment]
Hi, may I ask why this fix has not been included in 3.6 beta 4?

**Comment by akien-mga** [comment]
I haven't had much time to assess all PRs marked with the `cherrypick:3.x` label. I prioritized platform and buildsystem issues for 3.6 beta 4 to get it finally released after 6 months, but there will be more cherry-picks for future builds.
