### PR TITLE
fixed 'A' input not registered in osx script editor

### LINKED ISSUE #18808: Pressing a key in script editor doesnt work
**Godot version:**

v3.1dev.callinou.e744d12

**OS/device including version:**

Mac 10.13.4

**Issue description:**

When using the script editor the a key does not work.

**Steps to reproduce:**
Launch Godot create a node and add a script , edit script, try to type the letter a doesnt appear.

### PR DESCRIPTION
**Pull request by toger5**
on OS X the input of the a key was only registered when alt is pressed...

*Bugsquad edit:* Fixes #18808.

### CODE REVIEW

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -2851,7 +2851,7 @@ void TextEdit::_gui_input(const Ref<InputEvent> &p_gui_input) {
 				}
 				select_all();
 #else
-				if (k->get_alt()) {
+				if (k->get_alt() || (!k->get_shift() && !k->get_command() && !k->get_control())) {
```
Comment (akien-mga) [inline scene/gui/text_edit.cpp]: This code was added in #18003 (cc @sherjilozair), but I'm not sure of the purpose of this `if (k->get_alt())` check.
The new logic may also not be consistent with the `#ifndef` case just above.

**Comment by sherjilozair** [comment]
Yeah, this code worked when I created the PR, but later changes to this file changed the logic. I'd recommend reverting my commit. It would be better to add the new functionality (being able to use ctrl-a and ctrl-e on macos) in the new code rather than fix this bug, imo.

**Comment by toger5** [comment]
I spend some time trying to understand the logic. But it was confusing to me.

It definitly should not only register the a key if alt is pressed.
Now the logic works.
But i dint know if wront modifier + key should result in adding an a, or if not.
I was not really seeing a paddern

**Comment by sherjilozair** [comment]
@toger5 Yes, I agree it's confusing. Did you check if ctrl-a and ctrl-e work? That is by going to start and end of line. Idealyl shift-ctrl-a/e should also work by selecting everything from current cursor to start/end of line.

**Comment by toger5** [comment]
Yea those combinations work

**Comment by hpvb** [comment]
Cherry picked into 3.0.3
