### PR TITLE
Don't allow PathFollow offset outside bounds

### LINKED ISSUE #6202: Offset in PathFollow infinite increment
**Operating system or device - Godot version:**
OSX 2.1 stable

**Issue description** (what happened, and what was expected):
The offset of the PathFollow continues incrementing indefinitely, it should increment until the maximum length of the curve3D. 
**Steps to reproduce:**
`path_follow.set_offset(path_follow.get_offset() + speed)`

**Link to minimal example project** (optional but very welcome):

### PR DESCRIPTION
**Pull request by KoBeWi**
Resolves #6202
When looping is disabled, path is clamped. Otherwise it wraps around.

I also noticed that you could specify offset greater than length, but not lower than 0. That didn't sound useful, so I changed `is_greater` to `is_lesser`. The rationale is that you might want negative offset if you want to set a specific point from end. (another option would be enabling both greater and lesser)

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

File: scene/2d/path_2d.cpp [hunk 1]
```diff
@@ -319,8 +319,24 @@ void PathFollow2D::_bind_methods() {
...
+	if (path) {
+		if (path->get_curve().is_valid() && path->get_curve()->get_baked_length()) {
+			float path_length = path->get_curve()->get_baked_length();
+
+			if (loop) {
+				while (offset > path_length)
+					offset -= path_length;
+
+				while (offset < 0)
+					offset += path_length;
```
Comment (akien-mga) [inline scene/2d/path_2d.cpp]: I think this is equivalent to `fposmod(offset, path_length)`.

File: scene/2d/path_2d.cpp [hunk 2]
```diff
@@ -319,8 +319,24 @@ void PathFollow2D::_bind_methods() {
...
+
+			} else {
+				offset = CLAMP(offset, 0, path_length);
```
Comment (akien-mga) [inline scene/2d/path_2d.cpp]: Maybe `wrapf` could help solve #35485? @KoBeWi

File: scene/2d/path_2d.cpp (hunk 1 above)
Comment (KoBeWi) [reply scene/2d/path_2d.cpp]: Yep, although it might wrap 1 to 0, which was the problem solved by #34012

File: scene/2d/path_2d.cpp (hunk 2 above)
Comment (KoBeWi) [reply scene/2d/path_2d.cpp]: No, this is correct here, because we clamp the value if looping is disabled (which is irrelevant to #35485, because it uses loops).
