### PR TITLE
C#: Add abstract class support

### LINKED ISSUE #78244: C#: CSharpScript.CanInstantiate() returns true for abstract classes but .New() throws at runtime
### Godot version

v4.1.beta1.mono.official [828ec2c5d]

### System information

Windows 11

### Issue description

When I call `.CanInstantiate()` on a CSharpScript object it returns true even though it can't be instantiated via `.New()` when the class is abstract. I get a runtime exception: `MemberAccessViolation: Cannot create an abstract class.` (see attachment)
image

I would expect that `.CanInstantiate()` only returns true when I actually can instantiate it.

### Steps to reproduce

* Get some kind of CSharpScript (e.g. via ResourceLoader)
* Call `.CanInstantiate()` on it / print it
* Call `.New()` on it
* Get exception

### Minimal reproduction project

[CanInstantiateBug.zip](https://github.com/godotengine/godot/files/11750566/CanInstantiateBug.zip)

### PR DESCRIPTION
**Pull request by 398utubzyt**
At the moment, Godot internally does not support abstract scripts. This poses an issue when trying to create abstract classes in languages such as C#, because it has no way of knowing that trying to instantiate an abstract class is an invalid operation.

Abstract scripts appearing in the create dialog can no longer be instantiated as is the case with built-in classes such as `CanvasItem`. This also allows global abstract classes to remain untouched and functional. Furthermore, non-global C# classes no longer throw an error about an empty inheriting script path.

- Supersedes #80304.
- Fixes #78244.

image

### CODE REVIEW

File: modules/gdscript/gdscript.h [hunk 1]
```diff
@@ -196,6 +196,7 @@ class GDScript : public Script {
 	void clear(GDScript::ClearData *p_clear_data = nullptr);
 
 	virtual bool is_valid() const override { return valid; }
+	virtual bool is_abstract() const override { return false; /* false until #67777 gets merged */ }
```
Comment (raulsntos) [inline modules/gdscript/gdscript.h:199]: Not sure if we want to add a comment that references a specific PR https://github.com/godotengine/godot/pull/67777, but there's no issue or proposal AFAIK.

File: modules/mono/csharp_script.cpp [hunk 2]
```diff
@@ -551,8 +551,11 @@ bool CSharpLanguage::handles_global_class_type(const String &p_type) const {
 
 String CSharpLanguage::get_global_class_name(const String &p_path, String *r_base_type, String *r_icon_path) const {
 	Ref<CSharpScript> scr = ResourceLoader::load(p_path, get_type());
-	if (!scr.is_valid() || !scr->valid || !scr->global_class) {
-		// Invalid script or the script is not a global class.
+	// The script is allowed to not be a global class
+	// See modules/gdscript/gdscript.cpp:2499
```
Comment (raulsntos) [inline modules/mono/csharp_script.cpp:555]: This is correct, but the String returned must be empty if it's not a global class. As I understand it, this method should always return the correct `r_base_type` so the early returns are incorrect.

Consider changing the comment to something like:

```suggestion
	// This method must always return the r_base_type for every script, even if the script is
	// not a global class. But if the script is not a global class it must return an empty string
	// since it should not have a name.
```

Also, you will need to make two more changes to this method:

- Remove the next [if that checks if the name is empty and early returns](https://github.com/godotengine/godot/blob/541674d10692cf608f1245d7eede459bdc96b74f/modules/mono/csharp_script.cpp#L560-L562).
- Add a check [before returning the name](https://github.com/godotengine/godot/blob/541674d10692cf608f1245d7eede459bdc96b74f/modules/mono/csharp_script.cpp#L587) like:

```c++
if (!scr->global_class) {
	return String();
}
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs [hunk 3]
```diff
@@ -131,6 +131,9 @@ internal static void FrameCallback()
                 // Performance is not critical here as this will be replaced with source generators.
                 Type scriptType = _scriptTypeBiMap.GetScriptType(scriptPtr);
 
+                if (scriptType.IsAbstract)
+                    return godot_bool.False;
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:135]: Is this really needed? I don't think this method should be called for non-instantiable classes so this should never be reachable.

And if it's called for an abstract class, wouldn't it be better to let it throw an exception when it tries to instantiate the abstract class?

**Review by raulsntos — CHANGES_REQUESTED** [review]
Thanks a lot! I've been meaning to add proper support for abstract classes to C#.

This is a review of the code only, I haven't had a chance to build and test it yet.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs (hunk 3 above)
Comment (398utubzyt) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:135]: I tried to do a little bit of searching (which consists just of skimming through the function calls in `csharp_script.cpp`, not sure how much it's called elsewhere) and it doesn't seem like there are any safety checks to make sure that a class is instantiable.

I agree though that an exception may be better in this case, but I would rather throw it right after the check for the extra clarity instead of waiting for the constructor to be called. Maybe something like this?
```suggestion
                if (scriptType.IsAbstract)
                    throw new ArgumentException(
                        $"Cannot create script instance. The class '{scriptType.FullName}' is abstract.");
```

Comment (398utubzyt) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs]: Alright, I think that sounds good.

**Review by raulsntos — COMMENTED** [review]
I have built and tested the PR and looks great, but the inspector's resource picker still lets you choose abstract classes. You'll have to modify `EditorResourcePicker` to ignore abstract classes so they don't show up:

https://github.com/godotengine/godot/blob/bc88dca176cef6b8943ded58c68a60f7c127baea/editor/editor_resource_picker.cpp#L512

However, it has crossed my mind that maybe we should change `ClassDB::can_instantiate` instead, so it considers abstract global classes non-instantiable. The related PR https://github.com/godotengine/godot/pull/67777 makes similar changes but it changes `ClassDB::is_virtual`.

**Comment by 398utubzyt** [comment]
#67777 seems to make a claim about `ClassDB` virtual classes being the same as abstract classes. Should there be a similar change to `ClassDB::is_virtual` as well?

File: core/object/class_db.cpp [hunk 4]
```diff
@@ -394,7 +402,9 @@ bool ClassDB::is_virtual(const StringName &p_class) {
 		if (!ScriptServer::is_global_class(p_class)) {
 			ERR_FAIL_V_MSG(false, "Cannot get class '" + String(p_class) + "'.");
 		}
-		return false;
+		String path = ScriptServer::get_global_class_path(p_class);
+		Ref<Script> scr = ResourceLoader::load(path);
+		return scr.is_valid() && scr->is_valid() && scr->is_abstract();
```
Comment (398utubzyt) [inline core/object/class_db.cpp:407]: > Should there be a similar change to `ClassDB::is_virtual` as well?

For example, this.

**Comment by 398utubzyt** [comment]
Sounds good. I'll write those ideas down for future PRs. I went ahead and added the check to `ClassDB::is_virtual` in my previous commit, so it should be good for review as is.

**Comment by 398utubzyt** [comment]
Forgot to expose `Script::is_abstract` through `ClassDB`.

**Review by raulsntos — APPROVED** [review]
Looks good, I tested it and works as expected. Needs a rebase after https://github.com/godotengine/godot/pull/80184.

File: modules/mono/csharp_script.cpp [hunk 5]
```diff
@@ -551,13 +551,13 @@ bool CSharpLanguage::handles_global_class_type(const String &p_type) const {
...
 String CSharpLanguage::get_global_class_name(const String &p_path, String *r_base_type, String *r_icon_path) const {
 	Ref<CSharpScript> scr = ResourceLoader::load(p_path, get_type());
-	if (!scr.is_valid() || !scr->valid || !scr->global_class) {
-		// Invalid script or the script is not a global class.
-		return String();
-	}
+	// Always assign r_base_type and r_icon_path, even if the script
+	// is not a global one. In the case that it is not a global script,
+	// return an empty string AFTER assigning the return parameters.
+	// See modules/gdscript/gdscript.cpp:2499
```
Comment (AThousandShips) [inline modules/mono/csharp_script.cpp:557]: I'd suggest adding a permalink here or similar as this line reference isn't going to remain stable

File: doc/classes/ScriptExtension.xml [hunk 6]
```diff
@@ -141,6 +141,11 @@
 			<description>
 			</description>
 		</method>
+		<method name="_is_abstract" qualifiers="virtual const">
+			<return type="bool" />
+			<description>
```
[the remark this answers is not in the document]
Comment (398utubzyt) [reply doc/classes/ScriptExtension.xml:146]: I don't really have a good reference for how GDExtension docs should be written, so I've just copied what I wrote for `Script::is_abstract`. I'm not sure if it needs to be anything more.

**Comment by aaronfranke** [comment]
> So, maybe `CreateDialog` should be checking if a script is instantiable instead of checking if the script is abstract. But there may be undesirable consequences to doing this change that I can't think of right now.

It's better the way it is now, since we don't want to present creating virtual/abstract classes to the user. This is the entire purpose of marking it as virtual/abstract. Whether it can be technically instantiated on the C++ or C# side is a secondary concern, we do of course want those to be forbidden too, but CreateDialog needs to consider more than that.

**Comment by 398utubzyt** [comment]
> Since this PR has overlap with #67777, I wonder if #67777 should be merged first.

Since this PR goes a bit further than just `CreateDialog`, I'm not sure if merging #67777 first would be desirable. Instead, I believe this PR would provide a good base for #67777 simply because it is focused on providing internal logic for abstract classes in order to fix pre-existing bugs with C# rather than implementing a new GDScript feature.

Plus, there are some changes I've made regarding the GDExtension implementation and a few `ClassDB` methods after @raulsntos' review that I think would also need to be made in #67777 in order to make it work in other places (such as `EditorResourcePicker`) and also not break GDExtension compat.

I would certainly love to see what others think, though.


> So, maybe CreateDialog should be checking if a script is instantiable instead of checking if the script is abstract. But there may be undesirable consequences to doing this change that I can't think of right now.

To add onto what @aaronfranke mentioned, `Script::can_instantiate` returns `false` while inside the editor unless it's called on a tool script (in which case it always returns `true` prior to this PR) which can lead to undesirable results when used as a method for checking abstractness.

File: core/object/class_db.cpp [hunk 7]
```diff
@@ -377,7 +378,14 @@ bool ClassDB::can_instantiate(const StringName &p_class) {
...
 	ClassInfo *ti = classes.getptr(p_class);
-	ERR_FAIL_COND_V_MSG(!ti, false, "Cannot get class '" + String(p_class) + "'.");
+	if (!ti) {
+		if (!ScriptServer::is_global_class(p_class)) {
+			ERR_FAIL_V_MSG(false, "Cannot get class '" + String(p_class) + "'.");
+		}
+		String path = ScriptServer::get_global_class_path(p_class);
+		Ref<Script> scr = ResourceLoader::load(path);
+		return scr.is_valid() && scr->is_valid() && !scr->is_abstract();
+	}
```
Comment (dsnopek) [inline core/object/class_db.cpp:388]: I guess it makes sense why this is needed, and there is code that checks `ScriptServer::is_global_class()` already in `ClassDB::is_virtual()`, so there's a precedent for handling this sort of thing in `ClassDB`.

But it's not ideal that calling a method on `ClassDB` leads to running `ResourceLoader::load()`. For the most part, `ClassDB` is just updating and querying collections of data, where as this could lead to parsing and compiling a script!

I don't know if this has already been discussed, but is there a way for `ScriptServer` to keep track of which global classes are abstract so that we don't need to invoke the resource loader here?

File: core/object/class_db.cpp (hunk 4 above)
Comment (dsnopek) [inline core/object/class_db.cpp:407]: Same general thoughts here as well

**Comment by dsnopek** [comment]
I didn't test, but the GDExtension code in this PR looks good to me!

File: core/object/class_db.cpp (hunk 7 above)
Comment (398utubzyt) [reply core/object/class_db.cpp:388]: > is there a way for ScriptServer to keep track of which global classes are abstract so that we don't need to invoke the resource loader here?

I discussed with @raulsntos earlier about moving some of this logic to `ScriptServer` for consistency, but I'm not sure it would be possible to check for abstractness without loading the script itself. Especially in the case of C#, [where it needs a loaded script](https://github.com/godotengine/godot/blob/0bca4242392992840b0b891acde6422c49712e3e/modules/mono/csharp_script.cpp#L2295) in order to check for abstractness and other details in the first place. I believe [the resource loader should cache the script anyway](https://github.com/godotengine/godot/blob/0bca4242392992840b0b891acde6422c49712e3e/core/io/resource.cpp#L82), so [it only has to do all the expensive loading once](https://github.com/godotengine/godot/blob/0bca4242392992840b0b891acde6422c49712e3e/core/io/resource_loader.cpp#L465) if it wasn't already loaded in the first place.

I do think it would be nice to have a sort of lightweight script metadata system so that this kind of loading isn't necessary, but that would be out of scope for this PR.

Comment (dsnopek) [reply core/object/class_db.cpp:388]: > I discussed with @raulsntos earlier about moving some of this logic to `ScriptServer` for consistency, but I'm not sure it would be possible to check for abstractness without loading the script itself.

I think it's fine to load the script _at some point_, to check if it's abstract. What I don't personally like here is that calling a method on `ClassDB` may trigger the loading of the script right then.

Some other mechanism is already telling `ScriptServer` about each global class. Could that same mechanism also tell the `ScriptServer` whether they are abstract or not? Or, maybe the `ScriptLanguage` could periodically check all its global classes and update `ScriptServer` to tell it if they are each abstract or not? We could even trigger that to happen when the "Create node" dialog opens.

Comment (398utubzyt) [reply core/object/class_db.cpp:388]: > Could that same mechanism also tell the ScriptServer whether they are abstract or not?

At the moment, I don't think that this would be possible, or at the very least reasonable for this PR. [This is what is stored about a global class](https://github.com/godotengine/godot/blob/0bca4242392992840b0b891acde6422c49712e3e/core/object/script_language.h#L59-L63) in `ScriptServer` -- the bare minimum. In order to get anything else about a class (validity, tool-ness, abstractness, etc.) a call to `ResourceLoader::load` is required. I've tried to find the code which adds classes to the global class list and the best I could find is in [the editor file system](https://github.com/godotengine/godot/blob/0bca4242392992840b0b891acde6422c49712e3e/editor/editor_file_system.cpp#L1548C30-L1548C30), though that could very well be my editor being lazy and me not fully comprehending this system. In any case, that's not the focus of this PR and even if it was, I do not see a simple solution to passing arbitrary script information like this to `ScriptServer`. I would love to explore this idea further in future PRs, however.

> Or, maybe the `ScriptLanguage` could periodically check all its global classes and update `ScriptServer` to tell it if they are each abstract or not?

This would also require a `ResourceLoader::load` since a `ScriptLanguage` does not keep track of global classes on its own (see [C#](https://github.com/godotengine/godot/blob/0bca4242392992840b0b891acde6422c49712e3e/modules/mono/csharp_script.cpp#L550-L586) and [GDScript](https://github.com/godotengine/godot/blob/0bca4242392992840b0b891acde6422c49712e3e/modules/gdscript/gdscript.cpp#L2531-L2633) implementations of `ScriptLanguage::get_global_class_name`). This would instead lead to every single script being loaded within the project periodically instead of only when needed, which I do not think is a good optimization.

> We could even trigger that to happen when the "Create node" dialog opens.

I believe the `CreateDialog` [already calls `ResourceLoader::load`](https://github.com/godotengine/godot/blob/0bca4242392992840b0b891acde6422c49712e3e/editor/create_dialog.cpp#L221-L238) on script classes, and because it builds a tree of every type the engine is aware of, I think it's safe to say that it already does this. The problem with this idea though, is that this needs to happen every time we want to check for abstractness. Which means every script must _also_ be loaded in, for example, `EditorResourcePicker`, [where we only want to check abstractness for a single type](https://github.com/godotengine/godot/blob/0bca4242392992840b0b891acde6422c49712e3e/editor/editor_resource_picker.cpp#L496-L527).

I personally do not see an issue with calling `ResourceLoader::load` here in `ClassDB` since most likely the result is already going to be cached. If it isn't, that just means a few microseconds of load time saved in the near future. Besides, this is load call only ever called on global classes, which means that built in types and non-global scripts _never_ have to deal with a random resource load.

**Review by reduz — APPROVED** [review]
Looks good on my side, but make sure both the GDScript and Mono teams approve.

File: core/object/class_db.cpp (hunk 7 above)
Comment (dsnopek) [reply core/object/class_db.cpp:388]: I think you're misunderstanding what I'm suggesting. Using `ResourceLoader::load()` is fine to determine if the class is abstract. I'm just saying that I think it'd be better if wasn't triggered by calling a `ClassDB` function. Running a function before you call `ClassDB::can_instantiate()` that updates which global classes are abstract (by using the resource loader) would be fine.

In any case, if the core team is fine with calling a `ClassDB` function triggering the resource loader than it's fine! I just personally think it muddies `ClassDB` as a neutral data store that all parts of Godot can interact with while remaining decoupled.

Comment (398utubzyt) [reply core/object/class_db.cpp:388]: Ohh okay, I think I better understand now.
> I think it'd be better if wasn't triggered by calling a `ClassDB` function . . . it muddies `ClassDB` as a neutral data store that all parts of Godot can interact with while remaining decoupled.

I 100% agree here, but I'm not sure how else it could be implemented at this time without creating a massive headache. This is something I will try to look into in the future, though.

For now, however, it seems like the core team is fine with the current implementation and it appears to work correctly, so I'm going to go ahead and mark this as resolved unless there are any other thoughts.

Comment (aaronfranke) [reply core/object/class_db.cpp:388]: For #67777 I ended up moving the logic into CreateDialog instead of ClassDB, but I'm not sure what is the best place for it.

Comment (398utubzyt) [reply core/object/class_db.cpp:388]: I would probably use something like `ScriptServer` since this would be used throughout various unrelated parts of the engine. The only issue is that `ClassDB::can_instantiate` and `ClassDB::is_virtual` both have the same fallback return value, `false`, which means that an invalid script could lead to both being returning `false`. Trying to centralize this into a single function would mean that the fallback return value now differs if it were defined like so:

```cpp
bool ScriptServer::is_abstract(const StringName &p_class) {
    if (!ScriptServer::is_global_class(p_class)) {
        ERR_FAIL_V_MSG(false, "Cannot get class '" + String(p_class) + "'.");
    }
    String path = ScriptServer::get_global_class_path(p_class);
    Ref<Script> scr = ResourceLoader::load(path);
    return scr.is_valid() && scr->is_valid() && scr->is_abstract();
}

// ClassDB::can_instantiate
if (!ti) {
    // Returns true on invalid script
    return !ScriptServer::is_abstract(p_class);
}

// ClassDB::is_virtual
if (!ti) {
    // Returns false on invalid script
    return ScriptServer::is_abstract(p_class);
}
```

Which I suppose then means that there should be _two_ `ScriptServer` functions (`can_instantiate` and `is_virtual`/`is_abstract`) or some sort of boolean return parameter which is only `true` when an error is called, but I don't really like either solution.

This could probably allow for that `ResourceLoader::load` call to be removed from those `ClassDB` functions, but since these two sets of functions would most likely always be called together, I more see this as unnecessary refactoring.

Comment (aaronfranke) [reply core/object/class_db.cpp:388]: What about something like this?

```cpp
bool ScriptServer::is_abstract(const String &p_type) const {
	if (ClassDB::class_exists(p_type)) {
		return !ClassDB::can_instantiate(p_type) || ClassDB::is_virtual(p_type);
	}
	if (ScriptServer::is_global_class(p_type)) {
		String path = ScriptServer::get_global_class_path(p_type);
		Ref<Script> scr = ResourceLoader::load(path, "Script");
		return scr->is_abstract();
	}
	return false;
}
```

Comment (398utubzyt) [reply core/object/class_db.cpp:388]: I don't know if `ScriptServer` should be used like this since it only manages script types, not built-in types. However, I do think this is a good idea. Only thing I would do is move the `ClassDB` checks to be run when `ScriptServer::is_global_class` returns `false` as to avoid unnecessary `ClassDB` searching. If the global class code is moved out of those `ClassDB` functions, an error would be thrown when `p_type` is not a global or built-in type.

Again, though, this would then require all `ClassDB::can_instantiate` usages to be modified to use this new function in order to retain functionality (except in cases where only built-in types are meant to be handled, but I'm not sure when or even if that would be necessary), which feels a little out of scope for this PR.

Comment (aaronfranke) [reply core/object/class_db.cpp:388]: Then it seems like having this be in ClassDB is the right call then.

**Comment by 398utubzyt** [comment]
Rebased after #81487.

**Comment by 398utubzyt** [comment]
I realized it may be beneficial to add an error message to `Object::set_script` since it doesn't seem like there is a way to filter abstract scripts out of the file dialog. See changes [here](https://github.com/godotengine/godot/pull/81101/files#diff-7b1b6d9ebe2a4eabbafa4ee69f0aad4bf988539e4fe84c0f5f3bcfec78d9a8d2L883-R886).

image

**Comment by 398utubzyt** [comment]
> make sure both the GDScript and Mono teams approve.

Just want to clarify, is GDScript approval necessary here? Afaik the only change I made there is an [override of `Script::is_abstract`](https://github.com/godotengine/godot/pull/81101/files#diff-5e2034a07792f8479d359666a3d297e7a9106263288d8033d9162cf299c9c14cR198) which only returns `false` due to GDScript not supporting abstraction yet.

@reduz

**Comment by akien-mga** [comment]
Thanks!
