### PR TITLE
Fixed node scaling arrows being wrong

### LINKED ISSUE #27155: Rotated Node2D resizing cursor points unnaturally
**Godot version:**

3.1

**OS/device including version:**

Manjaro x86_64

**Issue description:**

Expected: up-down arrow when dragging right handle of a ~90 degrees rotated node
Happened: left-right arrow appears
image

Compared to LibreOffice:
image

**Steps to reproduce:**
1. new Node2D
2. rotate
3. grab a handle and resize

### PR DESCRIPTION
**Pull request by SekoiaTree**
Fixes https://github.com/godotengine/godot/issues/27155. Node scaling arrows pointed the wrong way when nodes were rotated.

image
with patch

image
without patch

### CODE REVIEW

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -2599,6 +2599,9 @@ void CanvasItemEditor::_gui_input_viewport(const Ref<InputEvent> &p_event) {
 
 void CanvasItemEditor::_update_cursor() {
 	CursorShape c = CURSOR_ARROW;
+	bool should_switch = false;
+	if (drag_selection.size() != 0)
+		should_switch = abs(fmod(drag_selection[0]->_edit_get_rotation(), M_PI)) >= M_PI_4 && abs(fmod(drag_selection[0]->_edit_get_rotation(), M_PI)) <= M_PI - M_PI_4;
```
Comment (TwistedTwigleg) [inline editor/plugins/canvas_item_editor_plugin.cpp:2604]: If you replace `M_PI` with `Math_PI`, the CI should build without any issues. For `M_PI_4`, you'll need to use something like `Math_PI / 4.0`. I mentioned this on the IRC, but was too slow in my reply and I do not use Discord, so I thought I'd mention it here.

Also: You will likely need to squish your commits. There is a page on the [documentation](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html?highlight=rebase#the-interactive-rebase) that helps explain how to do this.

Outside of those two minor things, the changes looks good to me! :+1:

Comment (SekoiaTree) [reply editor/plugins/canvas_item_editor_plugin.cpp:2604]: Alright, thanks! Will do!

Comment (SekoiaTree) [reply editor/plugins/canvas_item_editor_plugin.cpp]: Done!

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 2]
```diff
@@ -2599,6 +2599,9 @@ void CanvasItemEditor::_gui_input_viewport(const Ref<InputEvent> &p_event) {
 
 void CanvasItemEditor::_update_cursor() {
 	CursorShape c = CURSOR_ARROW;
+	bool should_switch = false;
+	if (drag_selection.size() != 0)
+		should_switch = abs(fmod(drag_selection[0]->_edit_get_rotation(), Math_PI)) >= Math_PI / 4 && abs(fmod(drag_selection[0]->_edit_get_rotation(), Math_PI)) <= Math_PI - Math_PI / 4;
```
Comment (akien-mga) [inline editor/plugins/canvas_item_editor_plugin.cpp:2604]:
```suggestion
	if (drag_selection.size() != 0) {
		should_switch = abs(fmod(drag_selection[0]->_edit_get_rotation(), Math_PI)) >= Math_PI / 4 && abs(fmod(drag_selection[0]->_edit_get_rotation(), Math_PI)) <= Math_PI - Math_PI / 4;
	}
```
There's probably a simpler way to know if it's flipped using dot product or similar, but I'm too tired to think it through now ;)
CC @groud @aaronfranke

Comment (aaronfranke) [reply editor/plugins/canvas_item_editor_plugin.cpp:2604]: Yes, something like `should_switch = abs(x.normalized().dot(Vector2(1, 0))) < Math_SQRT12;` should do it, where `x` is the X vector of the transformation matrix.

Comment (SekoiaTree) [reply editor/plugins/canvas_item_editor_plugin.cpp:2604]: I feel like using the transformation and the dot product is a lot less readable, and not especially faster. If you insist, I'll change it, but I think I have a clearer way with fmod being on Math_PI / 4 (I'll commit it later, really busy atm)

Comment (aaronfranke) [reply editor/plugins/canvas_item_editor_plugin.cpp:2604]: Is calling `_edit_get_rotation` an efficient operation? Also, why `fmod` with `Math_PI / 4` (quarter turn)? I don't see how that would help, since it means that one eighth turn behaves the same as zero turns and the same as one quarter turn.

Comment (SekoiaTree) [reply editor/plugins/canvas_item_editor_plugin.cpp:2604]: I figured out the correct formula that's a chunk shorter. I'll put it in tomorrow (again, super busy. In the middle of exams)

**Review by groud — APPROVED** [review]

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 3]
```diff
@@ -2599,6 +2599,11 @@ void CanvasItemEditor::_gui_input_viewport(const Ref<InputEvent> &p_event) {
 
 void CanvasItemEditor::_update_cursor() {
 	CursorShape c = CURSOR_ARROW;
+	bool should_switch = false;
+	if (drag_selection.size() != 0) {
+		float angle = drag_selection[0]->_edit_get_rotation();
+		should_switch = abs(Vector2(1, 0).rotated(angle).dot(Vector2(1, 0))) < abs(Vector2(1, 0).rotated(angle).dot(Vector2(0, 1)));
```
Comment (aaronfranke) [inline editor/plugins/canvas_item_editor_plugin.cpp:2605]: We don't need to perform the dot product twice, the values on each side are inversely related, matching up at `Math_SQRT12`. So we can just compare with `Math_SQRT12`.

```suggestion
		should_switch = abs(Vector2(1, 0).rotated(angle).dot(Vector2(1, 0))) < Math_SQRT12;
```

**Review by aaronfranke — CHANGES_REQUESTED** [review]

File: editor/plugins/canvas_item_editor_plugin.cpp (hunk 3 above)
Comment (groud) [reply editor/plugins/canvas_item_editor_plugin.cpp:2605]: Oh yes, you are right. That's a good suggestion.

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 4]
```diff
@@ -2599,6 +2599,11 @@ void CanvasItemEditor::_gui_input_viewport(const Ref<InputEvent> &p_event) {
 
 void CanvasItemEditor::_update_cursor() {
 	CursorShape c = CURSOR_ARROW;
+	bool should_switch = false;
+	if (drag_selection.size() != 0) {
+		float angle = drag_selection[0]->_edit_get_rotation();
+		should_switch = abs(Vector2(1, 0).rotated(angle).dot(Vector2(1, 0))) < Math_SQRT12;
```
Comment (aaronfranke) [inline editor/plugins/canvas_item_editor_plugin.cpp:2605]: Sorry for the many reviews telling you to change your code, but I thought of an even better solution:

```suggestion
		should_switch = abs(Math::cos(angle)) < Math_SQRT12;
```

**Review by aaronfranke — CHANGES_REQUESTED** [review]

File: editor/plugins/canvas_item_editor_plugin.cpp (hunk 4 above)
Comment (SekoiaTree) [reply editor/plugins/canvas_item_editor_plugin.cpp:2605]: I'm usually pretty good at trigonometry, I don't know why I didn't think of that... Anyway, thanks. It makes sense and it's fast. Comitting.

**Review by aaronfranke — APPROVED** [review]
The code is good, but this needs a [squash](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html) before it can be merged (bonus points if you rebase at the same time).

**Review by groud — APPROVED** [review]

**Comment by SekoiaTree** [comment]
Done! Totally didn't have to delete my local version twice to figure it out!

**Comment by akien-mga** [comment]
> Done! Totally didn't have to delete my local version twice to figure it out!

xkcd Git

Otherwise, you can have a look at our [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) documentation on interactive rebase :)

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged contribution :tada:

**Comment by groud** [comment]
Congrats ! :)

**Comment by SekoiaTree** [comment]
Thanks! :D :tada:

**Comment by aaronfranke** [comment]
@SekoiaTree If you would like to try out a graphical Git client, I made a video on how to use GitKraken to contribute to Godot: https://www.youtube.com/watch?v=0XKy8YpP5Ww

**Comment by SekoiaTree** [comment]
I'm trying to get used to console git, and I have github desktop as a backup. Thanks for the vid though :)

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Comment by SekoiaTree** [comment]
That means this is going to get merged into 3.2.4 right?

**Comment by akien-mga** [comment]
That means it has been cherry-picked in the `3.2` which is currently `3.2.4.beta`, and should thus be in the final release unless it's reverted.

**Comment by SekoiaTree** [comment]
Cool, thanks!
