### PR TITLE
Fix alternative tile popup menu not being openable

### LINKED ISSUE #64600: The alternative tile popup menu can't be opened
### Godot version

v4.0.alpha.custom_build [2e24b76535dceb9cf18ab8ece3304ed92948c1b5]

### System information

Windows 10

### Issue description

The alternative tile popup menu is not openable anymore, when you right click on an alternative tile inside a TileSet, nothing happens.

### Steps to reproduce

1. Create a tile set
2. Create an alternative tile
3. Right click on the alternative tile

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by MinusKube**
Fixes #64600

This fixes the alternative tile popup menu which was not openable anymore, due to a regression from #62629.

### CODE REVIEW

File: editor/plugins/tiles/tile_set_atlas_source_editor.cpp [hunk 1]
```diff
@@ -1920,6 +1918,8 @@ void TileSetAtlasSourceEditor::_tile_alternatives_control_gui_input(const Ref<In
 				drag_type = DRAG_TYPE_MAY_POPUP_MENU;
 				drag_start_mouse_pos = alternative_tiles_control->get_local_mouse_position();
 			} else if (drag_type == DRAG_TYPE_MAY_POPUP_MENU) {
+				drag_type = DRAG_TYPE_NONE;
```
Comment (groud) [inline editor/plugins/tiles/tile_set_atlas_source_editor.cpp:1921]: I think we should set `drag_type = DRAG_TYPE_NONE` even if `drag_type != DRAG_TYPE_MAY_POPUP_MENU`. As a safety measure.
Thus the logic should likely be changed to:
```
if (mb->is_pressed()) {
   ...
} else {
   if (drag_type == DRAG_TYPE_MAY_POPUP_MENU) {
      ...
   }
   drag_type = DRAG_TYPE_NONE;
}
```

That will make it 100% sure that dragging is "released" when mouse is released.

**Review by groud — CHANGES_REQUESTED** [review]

**Review by groud — APPROVED** [review]
Needs for CI to pass, but LGTM otherwise. Thanks!

**Comment by akien-mga** [comment]
Thanks!
