### PR TITLE
Remove disabled shapes from physics 2D calculations

### LINKED ISSUE #17015: Should RayCast2D detect disabled collision shapes?
**Godot version:**

Godot 3.0

**OS/device including version:**

Arch Linux
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)

**Issue description:**

Should a `RayCast2D` detect collisions with disabled collision shapes?
This happens when toggling disabled in the editor or calling `shape_owner_set_disabled`.

**Steps to reproduce:**
1. Create any one of `KinematicBody2D`, `RigidBody2D`, `StaticBody2D` or `Area2D`.
2. Add a `CollisionShape2D` and add a shape to it.
3. Disable the `CollisionShape2D` with `disabled` set to true.
4. Create a `RayCast2D` intersecting the collision shape.
5. Test the `RayCast2D` for collisions; reports `true`.

**Minimal reproduction project:**

[Example](https://github.com/arccoza/godot-bug-examples/tree/bugx/raycast2d-disabled-collider-detection/adrien)

### PR DESCRIPTION
**Pull request by ShyRed**
Disabling a shape removes it from physics calculations. Enabling a shape adds it back to the physics calculations.

This speeds up the physics system (tested with example project from #17099 ) and prevents disabled shapes from being detected by raycasts ( see #17015 ).

Fixes #17015 and speeds up #17099

### CODE REVIEW

File: servers/physics_2d/collision_object_2d_sw.cpp [hunk 1]
```diff
@@ -73,6 +73,29 @@ void CollisionObject2DSW::set_shape_transform(int p_index, const Transform2D &p_
...
+
+	if (!space)
+		return;
+
+	if (p_disabled && shape.bpid != 0) {
+		space->get_broadphase()->remove(shape.bpid);
+		shape.bpid = 0;
+		_update_shapes();
+	}
+	else if (!p_disabled && shape.bpid == 0) {
```
Comment (akien-mga) [inline servers/physics_2d/collision_object_2d_sw.cpp]: There's a style issue here: https://travis-ci.org/godotengine/godot/jobs/347916013

Could you amend the commit to fix it? See also http://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html on how to setup code style checks locally.

Comment (ShyRed) [reply servers/physics_2d/collision_object_2d_sw.cpp]: Working on it! :)

Comment (ShyRed) [reply servers/physics_2d/collision_object_2d_sw.cpp]: Fixed code style and rebased. Also installed the ClangFormat plugin for Visual Studio, so this should not become an issue again in future ... hopefully :smile:

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.
