### PR TITLE
Fix default value count checking for inherited function

### LINKED ISSUE #59131: Empty dictionary as default value causes issue with inheritance
### Godot version

4.0 alpha 4

### System information

Windows 11

### Issue description

When setting an empty dictionary as a default value for a function parameter, editor shows an error in an extending script:
_The function signature doesn't match the parent. Parent signature is (...)._

### Steps to reproduce

1. Open attached minimal project in Godot 4.0 alpha 4
2. Open **bugged_script.gd** in editor

### Minimal reproduction project

[InheritanceBug.zip](https://github.com/godotengine/godot/files/8243685/InheritanceBug.zip)

edit: version update...

### PR DESCRIPTION
**Pull request by Chaosus**
Fix https://github.com/godotengine/godot/issues/59131

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -1133,8 +1137,12 @@ void GDScriptAnalyzer::resolve_function_signature(GDScriptParser::FunctionNode *
...
 #endif // DEBUG_ENABLED
 #ifdef TOOLS_ENABLED
-		if (p_function->parameters[i]->default_value && p_function->parameters[i]->default_value->is_constant) {
-			p_function->default_arg_values.push_back(p_function->parameters[i]->default_value->reduced_value);
+		if (p_function->parameters[i]->default_value) {
+			default_value_count++;
+
+			if (p_function->parameters[i]->default_value->is_constant) {
+				p_function->default_arg_values.push_back(p_function->parameters[i]->default_value->reduced_value);
+			}
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:1145]: This seems to be wrong, it should put all the default values. It doesn't work properly like this, since the consumer won't be able to tell which values belong to each parameter. But for what I know, this is only used in the generated documentation, that's probably why nobody noticed.

I know this isn't your code, it's just what was there before, but I wanted to point it out. I can't think of a good fix for now, so let's leave it like this. I'll make a note in my list to test and open an issue about it.

**Review by vnen — APPROVED** [review]
LGTM

**Comment by akien-mga** [comment]
Thanks!
