### PR TITLE
[4.4] Update UID upgrade tool dialog message

### LINKED ISSUE #103066: Clicking on "Cancel" when asked about UIDs update does not cancel anything
### Tested versions

4.4 beta4

### System information

Godot v4.4.beta4 - Windows 11 (build 22631) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 32.0.15.6119) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 threads)

### Issue description

When I opened my project I got this message:

Image

As I did not do a backup, I chose "Cancel" and went to my Git client. I can see that uid files were already created.

Also, once we click on "Cancel", the message does not reappear when restarting the project.

**Suggested Solutions:**
- Make sure that "Cancel" prevents any change to the project to allow the user to make a backup
- Make sure the message is still there when the user has done their backup and are ready to click on "Restart and Upgrade"

### Steps to reproduce

Open a 4.3 project with 4.4.

### Minimal reproduction project (MRP)

Any 4.3 projects.

### PR DESCRIPTION
**Pull request by adamscott**
> [!NOTE]
> The new wording reads:
> > As of Godot 4.4, scenes and resources use UIDs to reference scripts and shaders. Upgrades apply on the next save of each scene/resource.
> > 
> > To save time, this tool can open and save each of these files. Depending on the project size, it may take several minutes.

This PR clarifies what the tool does and reduce greatly the verbosity of it. This also adds a (missing) title to the dialog.

| Before | After |
| :---: | :---: |
| image | image |

Fixes #103066

### CODE REVIEW

**Review by aaronfranke — APPROVED** [review]

File: editor/uid_upgrade_tool.cpp [hunk 1]
```diff
@@ -98,7 +98,7 @@ UIDUpgradeTool::~UIDUpgradeTool() {
 }
 
 void UIDUpgradeDialog::popup_on_demand() {
-	const String confirmation_message = TTR("As of Godot 4.4, scenes and resources use UIDs to reference scripts and shaders.\n\nNormally, this update is applied to a single scene or resource once you save it in Godot 4.4 for the first time. If you have a lot of scenes and/or resources, doing this manually may be time-consuming. This tool will update all of the project's scenes and resources at once.\n\nClick \"Restart & Upgrade\" to restart the editor and update all of the scenes and resources in this project. Depending on the project size, it may take several minutes.\n\nNote: Please make sure you have your project backed up before running the tool, to avoid the possibility of data loss. Additionally, make sure to commit all .uid files into version control (and do not add them to ignore-lists like .gitignore).");
+	const String confirmation_message = TTR("As of Godot 4.4, scenes and resources use UIDs to reference scripts and shaders. This upgrade will be done on scenes and resources next save.\n\nTo save time, this tool can open and save each of these project files. Depending on the project size, it may take several minutes.");
```
Comment (tetrapod00) [inline editor/uid_upgrade_tool.cpp:101]:
```suggestion
	const String confirmation_message = TTR("As of Godot 4.4, scenes and resources use UIDs to reference scripts and shaders. This upgrade will be done on scenes and resources next time each is saved.\n\nTo save time, this tool can open and save each of these project files. Depending on the project size, it may take several minutes.");
```
Possibly something like this. Current wording seems slightly ambiguous. I'm not sure if it means that the whole project will be upgraded or just the specific files.

Comment (adamscott) [reply editor/uid_upgrade_tool.cpp:101]: I asked an AI as I'm not a native English speaker and it gave me this short sentence (in bold).

> As of Godot 4.4, scenes and resources use UIDs to reference scripts and shaders. **Upgrades apply on the next individual save of each scene/resource.**

How is it?

Comment (tetrapod00) [reply editor/uid_upgrade_tool.cpp:101]: > Upgrades apply on the next save of each individual scene/resource.
Seems fine, I'd prefer this so "individual" emphasizes the resource rather than the act of saving

**Comment by adamscott** [comment]
The new wording reads:
> As of Godot 4.4, scenes and resources use UIDs to reference scripts and shaders. Upgrades apply on the next save of each scene/resource.
> 
> To save time, this tool can open and save each of these files. Depending on the project size, it may take several minutes.

**Comment by KoBeWi** [comment]
The new message is fine, but the change will erase all translations for this dialog.

**Comment by akien-mga** [comment]
Yeah this would invalidate translations for all these languages:
```
$ rg -g'*.po' --sort=path "As of Godot 4.4," -l
translations/editor/cs.po
translations/editor/es.po
translations/editor/fr.po
translations/editor/ja.po
translations/editor/pl.po
translations/editor/uk.po
translations/editor/zh_CN.po
```

Since this is a dialog all users would see, I think breaking translations just before the stable release isn't a good idea.

IIUC the main issue fixed here is that the "Note:" advising to make a backup is wrong as it's already too late at this stage. So I'll make an alternative that just removes that note and edit the translations manually to drop their last paragraph.

**Comment by akien-mga** [comment]
Actually I don't think this is improving things that much, and won't solve #103066, just might reduce a tiny bit of the wrong expectation.

It removes some important information that `.uid` files are not optional and shouldn't be gitignore'd for example.

**Comment by adamscott** [comment]
> It removes some important information that `.uid` files are not optional and shouldn't be gitignore'd for example.

It is not the responsibility of the tool, IMHO. The tool just exists to save existing resources, not prevent the upgrade.

**Comment by KoBeWi** [comment]
btw I have a PR that completely replaces the dialog: #103044

**Comment by akien-mga** [comment]
> > It removes some important information that `.uid` files are not optional and shouldn't be gitignore'd for example.
> 
> It is not the responsibility of the tool, IMHO. The tool just exists to save existing resources, not prevent the upgrade.

Well as it stands this dialog does two things:

- Inform users about UIDs. There's even a "Learn More" button that should point to more information about that change in 4.4.
- Offer running a tool that updates everything to use UIDs.

I think both are important first-time user information, though I agree the UX and wording aren't the best.

**Comment by adamscott** [comment]
> > > It removes some important information that `.uid` files are not optional and shouldn't be gitignore'd for example.
> > 
> > 
> > It is not the responsibility of the tool, IMHO. The tool just exists to save existing resources, not prevent the upgrade.
> 
> Well as it stands this dialog does two things:
> 
>     * Inform users about UIDs. There's even a "Learn More" button that should point to more information about that change in 4.4.
> 
>     * Offer running a tool that updates everything to use UIDs.
> 
> 
> I think both are important first-time user information, though I agree the UX and wording aren't the best.

Yes, I totally agree. The first is to explain the second, where the latter is the main focus of the popup. Where I disagree is about advising users to not add their .uid files to .gitignore, as it doesn't have anything to do with the second point, ie. the main idea behind the popup.

**Review by lyuma — APPROVED** [review]

**Comment by lyuma** [comment]
My worry is if you start explaining too much about UIDs in the upgrade dialog, and we have a cancel button, the users are going to say "oh this is too complicated, I don't want this UID stuff" and hit cancel, not knowing that the UIDs are there regardless and the dialog is just to facilitate the transition.

We could have some "What's new?" popup that just has an OK button and explains some of the changes related to UIDs.
But also, if a user sees a "what's new" dialog, they will probably mash OK without reading it.

File: editor/uid_upgrade_tool.cpp [hunk 2]
```diff
@@ -120,6 +120,7 @@ void UIDUpgradeDialog::_notification(int p_what) {
 }
 
 UIDUpgradeDialog::UIDUpgradeDialog() {
+	set_title(TTR("Upgrade scenes and resources to use UIDs"));
```
Comment (akien-mga) [inline editor/uid_upgrade_tool.cpp:123]:
```suggestion
	set_title(TTR("Re-save all scenes and resources to use UIDs"));
```

**Comment by akien-mga** [comment]
This would need to be retargeted for the `4.4` branch as the upgrade tool was made generic in 4.5 and no longer refers to UID changes.

File: editor/uid_upgrade_tool.cpp [hunk 3]
```diff
@@ -98,7 +98,7 @@ UIDUpgradeTool::~UIDUpgradeTool() {
 }
 
 void UIDUpgradeDialog::popup_on_demand() {
-	const String confirmation_message = TTR("As of Godot 4.4, scenes and resources use UIDs to reference scripts and shaders.\n\nNormally, this update is applied to a single scene or resource once you save it in Godot 4.4 for the first time. If you have a lot of scenes and/or resources, doing this manually may be time-consuming. This tool will update all of the project's scenes and resources at once.\n\nClick \"Restart & Upgrade\" to restart the editor and update all of the scenes and resources in this project. Depending on the project size, it may take several minutes.\n\nNote: Please make sure you have your project backed up before running the tool, to avoid the possibility of data loss. Additionally, make sure to commit all .uid files into version control (and do not add them to ignore-lists like .gitignore).");
+	const String confirmation_message = TTR("As of Godot 4.4, scenes and resources use UIDs to reference scripts and shaders. Upgrades apply on the next save of each scene/resource.\n\nTo save time, this tool can open and save each of these files. Depending on the project size, it may take several minutes.");
```
[the remark this answers is not in the document]
Comment (adamscott) [reply editor/uid_upgrade_tool.cpp:101]: It doesn't accept links, I tried.

**Comment by adamscott** [comment]
> This would need to be retargeted for the `4.4` branch as the upgrade tool was made generic in 4.5 and no longer refers to UID changes.

Done!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
