### PR TITLE
Fix crash when trying to load an invalid mp3 file

### LINKED ISSUE #55457: Double-clicking an invalid `.mp3` file within Godot's file system crashes the program
### Godot version

3.4stable

### System information

Windows 10, GLES2,  Intel(R) UHD Graphics 630

### Issue description

When I double click an audio file (.mp3 for me) in the file system in the Godot editor. It just crashes Godot without a trace. I could not find any logs or anything.

### Steps to reproduce

Add an .mp3 file into your project and double click it in the file system within the window.

### Minimal reproduction project

[mp3 bug.zip](https://github.com/godotengine/godot/files/7622011/mp3.bug.zip)
Run the project window inside Godot.

### PR DESCRIPTION
**Pull request by DeleteSystem32**
This should fix https://github.com/godotengine/godot/issues/55457 by adding an additional check for mp3 file validity.  
Additionally, minimp3 is updated to the newest version.

### CODE REVIEW

**Comment by akien-mga** [comment]
Looks good! Please also update the commit hash for minimp3 in `thirdparty/README.md`.

File: modules/minimp3/audio_stream_mp3.cpp [hunk 1]
```diff
@@ -165,7 +161,7 @@ void AudioStreamMP3::set_data(const Vector<uint8_t> &p_data) {
 
 	mp3dec_ex_t mp3d;
 	int err = mp3dec_ex_open_buf(&mp3d, src_datar, src_data_len, MP3D_SEEK_TO_SAMPLE);
-	ERR_FAIL_COND(err != 0);
+	ERR_FAIL_COND(err || mp3d.info.hz == 0);
```
Comment (akien-mga) [inline modules/minimp3/audio_stream_mp3.cpp:164]: Maybe this can be given an explicit error message with the `_MSG` variant of the macro, as otherwise this might be a bit cryptic to users (especially as this often would happen in a chain reaction of failed loading errors).

**Review by akien-mga — APPROVED** [review]

File: modules/minimp3/audio_stream_mp3.cpp (hunk 1 above)
Comment (DeleteSystem32) [reply modules/minimp3/audio_stream_mp3.cpp]: Good point! I've gone ahead and updated the commit; should hopefully be all good now.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

I only cherry-picked the library update + the new error check, as the refactoring seemed not to be valid in `3.x`, where the data is allocated via the AudioServer: 8a4c58353875796e5a3032956e29b2e92ebded0a.

For `master`, I've noticed some differences between the implementation of `AudioStreamMP3` initially ported from `3.x` and the one of other streams like `AudioStreamOGGVorbis`, might be worth giving it another check to further sync to the current design of audio streams (e.g. there's no `set_data()`, `get_data()` and `clear_data()`, I guess things are now done differently?).

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.1.

**Comment by DeleteSystem32** [comment]
> For master, I've noticed some differences between the implementation of AudioStreamMP3 initially ported from 3.x and the one of other streams like AudioStreamOGGVorbis, might be worth giving it another check to further sync to the current design of audio streams (e.g. there's no set_data(), get_data() and clear_data(), I guess things are now done differently?).

I was wondering about that as well at first, but I think it's just due to how the new implementation of `AudioStreamOGGVorbis` works. It stores its data as a `OGGPacketSequence` now, so the accessors are just named differently. `AudioStreamSample` still has the raw data accessors as well.
