### PR TITLE
[3.x] Clear freed RIDs to fix disappearing meshes and id_map errors

### LINKED ISSUE #53374: Mesh Instances randomly not rendering (regression since 3.3)
### Godot version

3.3.4 official

### System information

Win 10/64 NVIDIA GeForce GTX 1060/PCIe/SSE2

### Issue description

Too frequently some meshes won't render in the editor, and sometimes in game. Switching to another scene and switching back, or closing and reopening will temporarily fix it.

We were developing on 3.2.1 and I never had the issue. As we explored the 3.3 branch I started noticing this error. It's frequent enough that it's a problem. It could have happened any time from 3.2.2. 

@Arnklit Already reported this in #47051, and provided a test project, but it was closed prematurely. Though since it's intermittent I doubt the core devs will see it until they start making a large scene with tons of objects. @mbrlabs also confirmed the problem in that ticket. 

It happens to all sorts of meshes. It has also affected @Zylann's heightmap terrain, one time, in the editor. One quad (say 5mx5m) was invisible and I couldn't get it to become visible until reloading the scene (prior to any of my gdnative work).

Here I'm building a house from a kit. I already had this scene open. I was in another scene, then switched back to it and saw this. I moved the camera closer for the shot:

image

I switched to the other scene, then came back, and the two meshes rendered again:

image

The floor is a fairly simple mesh with one wood material. The wall is more complex. Notice in the first picture you can see the shutter and glass. Here is the full object:

image

This wall object has separate glass and shutter meshes. The mesh that disappeared includes two materials, the same wood used on all objects in all of these pictures, and a rusty metal frame. Both materials on the mesh didn't render, and both materials are visible on all the other meshes.

The mesh instances have their mesh data stored in the `tscn` file. They were originally imported from fbx, but that file has already been deleted. The textures are separate dds files. The materials are separate binary files, though most of our other materials are `tres`. Here we are using MTLOD and an immediate geometry node, however I've experienced this on our meshes that are not using MTLOD. These shots are all close enough that we're only looking at LOD0. 

I do not believe this is not an issue with LOD, file types or materials. It decides whether it is going to render these objects when the scene opens. Nothing I can do in the scene will get it to render. Not selecting it, moving it, changing visibility, or moving the camera. Only by switching or reopening scenes fixes (or breaks) these meshes.

My console is full of these errors, which repeat when I switch back and forth between my scenes sometimes. 
```
ERROR: get: Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null
   At: ./core/rid.h:150
ERROR: instance_set_transform: Condition "!instance" is true.
   At: servers/visual/visual_server_scene.cpp:713
ERROR: get: Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null
   At: ./core/rid.h:150
ERROR: instance_set_scenario: Condition "!instance" is true.
   At: servers/visual/visual_server_scene.cpp:629
ERROR: get: Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null
   At: ./core/rid.h:150
ERROR: instance_set_visible: Condition "!instance" is true.
   At: servers/visual/visual_server_scene.cpp:780
ERROR: get: Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null
   At: ./core/rid.h:150
ERROR: instance_attach_skeleton: Condition "!instance" is true.
   At: servers/visual/visual_server_scene.cpp:913
```

### Steps to reproduce

Build out a complex scene for a game with a lot of objects to greatly increase your likelihood of seeing the error.
Now at least 3 known gamedevs experience this problem.

### Minimal reproduction project

Look in https://github.com/godotengine/godot/issues/47051

### PR DESCRIPTION
**Pull request by TokisanGames**
## Background
#53374 highlights an issue of disappearing meshes and error spam.

The root cause is when RIDs are freed, they leave a dangling pointer. Freed RIDs are not safe to free again, at least by the `VisualServer` or `PhysicsServer`. Doing so may randomly free other mesh instances if the invalid pointer matches one already in use by another RID. 

Some areas in the engine, such as `SpatialEditor` continually spam `VisualServer::free(RID)` with already freed RIDs, so though uncommon, freeing RIDs that other classes own occurs far too frequently.

## Changes

* This PR manually clears RIDs wherever they are freed by `VisualServer` or `PhysicsServer` in the engine, and possibly reused (i.e. not freed in the destructor) with `rid = RID();`.

---

Fixes #53374, #44642, #38229, #48433, #47356, #44712
Probably fixes: #41360, #50630

### CODE REVIEW

File: core/rid.h [hunk 1]
```diff
@@ -61,6 +59,8 @@ class RID {
 public:
 	_FORCE_INLINE_ RID_Data *get_data() const { return _data; }
 
+	//_FORCE_INLINE_ void erase(RID &p_rid) { _data = nullptr; } // Useful to have?
```
Comment (tinmanjuggernaut) [inline core/rid.h:62]: Would it be helpful to have this function?
I don't really need it as the friend, RID_OwnerBase has access to clear the RID.

File: editor/plugins/animation_player_editor_plugin.cpp [hunk 2]
```diff
@@ -1292,7 +1292,7 @@ void AnimationPlayerEditor::_allocate_onion_layers() {
 void AnimationPlayerEditor::_free_onion_layers() {
 	for (int i = 0; i < onion.captures.size(); i++) {
 		if (onion.captures[i].is_valid()) {
-			VS::get_singleton()->free(onion.captures[i]);
+			VS::get_singleton()->free(onion.captures.get(i));
```
Comment (tinmanjuggernaut) [inline editor/plugins/animation_player_editor_plugin.cpp:1295]: Vector[] is const which doesn't like the passing by reference. get is not

File: core/rid.h [hunk 3]
```diff
@@ -78,7 +78,16 @@ class RID {
...
+	_FORCE_INLINE_ uint32_t get_id() const {
+		if (_data) {
+			try {
+				return _data->get_id();
+			} catch (...) {
+				ERR_FAIL_V_MSG(0, "RID points to memory that has already been freed.");
+			}
+		}
+		return 0;	// An invalid or uninitialized state
+	}
```
Comment (tinmanjuggernaut) [inline core/rid.h:90]: Is it necessary for me to `try` here? Or are exceptions handled elsewhere? Since gdscript can still create dangling pointers, it's possible get_id() will reference invalid memory. I tried freeing an RID, then getting it's ID in gdscript, in another build of the engine. I got a non-zero number, but no crash or error message.

File: editor/plugins/spatial_editor_plugin.cpp [hunk 4]
```diff
@@ -5860,9 +5860,16 @@ void SpatialEditor::_finish_indicators() {
 }
 
 void SpatialEditor::_finish_grid() {
-	for (int i = 0; i < 3; i++) {
-		VisualServer::get_singleton()->free(grid_instance[i]);
-		VisualServer::get_singleton()->free(grid[i]);
+	for (int a = 0; a < 3; a++) {
+		if(grid_enable[a]) {
+			int c = (a + 2) % 3;
+			if (grid_instance[c].is_valid() && grid_instance[c].get_id() > 0) {
```
Comment (tinmanjuggernaut) [inline editor/plugins/spatial_editor_plugin.cpp:5866]: This silly bit of arcana is exactly how SpatialEditor populates these arrays.

File: core/rid.h [hunk 5]
```diff
@@ -78,7 +78,16 @@ class RID {
 	}
 	_FORCE_INLINE_ bool is_valid() const { return _data != nullptr; }
 
-	_FORCE_INLINE_ uint32_t get_id() const { return _data ? _data->get_id() : 0; }
+	_FORCE_INLINE_ uint32_t get_id() const {
+		if (_data) {
+			try {
+				return _data->get_id();
```
Comment (tinmanjuggernaut) [inline core/rid.h:84]: Is it necessary for me to `try` here? Or are exceptions handled elsewhere? Since gdscript can still create dangling pointers, it's possible get_id() will reference invalid memory. I tried freeing an RID, then getting it's ID in gdscript, in another build of the engine. I got a non-zero number, but no crash or error message.

File: modules/bullet/bullet_physics_server.cpp [hunk 6]
```diff
@@ -1519,7 +1523,7 @@ void BulletPhysicsServer::free(RID p_rid) {
 		space_owner.free(p_rid);
 		bulletdelete(space);
 	} else {
-		ERR_FAIL_MSG("Invalid ID.");
+		ERR_FAIL_MSG("Invalid RID.");
```
Comment (tinmanjuggernaut) [inline modules/bullet/bullet_physics_server.cpp:1526]: This should be removed if we go with the silent fail like on VisualServer. There's another instance elsewhere.

File: core/rid.h (hunk 5 above)
Comment (tinmanjuggernaut) [reply core/rid.h:84]: Some of the mobile platform builds say `error: cannot use 'try' with exceptions disabled`. So should I not `try`?

**Comment by lawnjelly** [comment]
I haven't examined in great details the VisualServer multithread wrapping / queue system as it contains a bunch of macro magic, but as far as I understand it, the `free` calls for the RIDs pass through this. This afaik is why the majority of fast functions have no return value (as that could potentially stall such a queue).

I'm sure RandomShaper will be more familiar but to me it seems there is a potential danger of the ordering not being as expected:
Client code:
```
1) Call free on RID
2) Delete RID
```
Server code
```
3) Receives free call for deleted RID object
4) accesses freed memory etc... crash / corruption
```
Whereas with the existing system of passing the RID by value this danger is avoided. This could easily happen if a RID is used e.g. as a local variable.

File: core/rid.h [hunk 7]
```diff
@@ -92,63 +101,41 @@ class RID_OwnerBase {
...
-#endif
 public:
 	_FORCE_INLINE_ RID make_rid(T *p_data) {
 		RID rid;
 		_set_data(rid, p_data);
-
-#ifdef DEBUG_ENABLED
-		id_map.insert(p_data);
-#endif
-
```
Comment (lawnjelly) [inline core/rid.h:132]: If you get rid of the `id_map`, does the RID_Owner system still do anything? i.e. Is it just a debug system for keeping RIDs together and checking, but if these are all pass throughs in your PR it becomes redundant?

File: core/rid.h [hunk 8]
```diff
@@ -92,63 +101,41 @@ class RID_OwnerBase {
...
 		p_data->_id = refcount.get();
-#ifndef DEBUG_ENABLED
 		p_data->_owner = this;
-#endif
 	}
 
-#ifndef DEBUG_ENABLED
+	_FORCE_INLINE_ void _free(RID &p_rid) {
+		p_rid._data = nullptr;
+	}
```
Comment (lawnjelly) [inline core/rid.h:110]: This name seems confusing, you aren't freeing anything, you are setting a pointer to NULL.

File: core/rid.h (hunk 5 above)
Comment (RandomShaper) [reply core/rid.h:84]: I see here the bigges problem with this approach.

In Godot we're not using exceptions (some 3rd-prty code may be, but Godot's own codebase isn't), so `try/catch` is forbidden. However, let's consider for a moment if the use case here is strong enough. If I'm not mistaken, what you are attempting to catch here is a segfault (i.e., accessing memory no longer owned by the process), being that a way to detect an `RID` is dangling. But wouldn't it be possible that a future `RID` data ends up being alocated at the same (or overlapping) memory address, rendering that sort of check useless?

That's a bit like the dangling `Variant` issue we use to have.

Comment (tinmanjuggernaut) [reply core/rid.h:84]: The PR is not dependent upon try/catch. This bit is optional to prevent potential issues in gdscript, though as I said it doesn't seem to matter. The key part that fixed the dangling pointer is _free() where _data is set to nullptr.

File: core/rid.h (hunk 8 above)
Comment (tinmanjuggernaut) [reply core/rid.h:110]: `RID_OwnerBase::_free()` is only called by `RID_Owner::free()`, which is the current API in both 3.x and 4.x. What name would you suggest?

**Comment by lawnjelly** [comment]
Just to keep up to date on this, I've discussed this with @RandomShaper and I'm trying out an implementation in 3.x with handles. This may end up being a better approach for RIDs overall in 3.x (similar to 4.x), or for just for bug finding in a specific build.. we'll know better soon, but don't spend too much time on this in the meantime.

What would be useful though if you are interested is if you can track down the bugs in the spatial editor and do a fix PR for these only. This will be useful whatever approach we use for the RIDs, and it's good practice anyway to have one fix per PR (as is there seems to be two things in this PR).

**Comment by tinmanjuggernaut** [comment]
@lawnjelly has rewritten RID to use handles as is done in 4.0 with PR #54907. Once that PR is merged, I'll redo this PR to address the other issues in VisualServer and SpatialEditor (# 3 in OP, 1,2,4 are replaced.).

**Comment by tinmanjuggernaut** [comment]
@lawnjelly @RandomShaper I reworked this PR. It reverts RID to its original state and manually clears RIDs where they are freed throughout the engine by VisualServer and PhysicsServer. I updated the original post above. https://github.com/godotengine/godot/pull/54650#issue-1046315282

One decision that needs to be made is, when `VisualServer::free()` cannot find the RID it fails silently. `PhysicsServer::free()` however prints an error, and the documentation notes this. I think these should be consistent. Which way should we go?

Please review and let me know any changes you'd like. Then I'll update the error message above and squash.

**Comment by lawnjelly** [comment]
I can now confirm that setting the RIDs to NULL in spatial_editor_plugin does seem to solve the bug there (in terms of the RIDs), see https://github.com/godotengine/godot/issues/44642#issuecomment-988618651 , I have details of a reliable replication and reports with the `rids=tracked_handles` build.

To move forward this PR needs the commits squashing so it can be reviewed.

**Comment by tinmanjuggernaut** [comment]
Squash fixed. I just didn't notice it. Thanks for alerting me.

> Probably tolerating being sent a NULL makes the most sense imo, but it needs discussing with other contributors.

I now check for this in VS/PS free(), so it's not a concern (though freeing dangling pointers still is). My question is about the different behavior between VS and PS::free(). 

Both return void. VS ignores invalid and not found RIDs silently. PS also does nothing about them, then prints an error to the console. I think they should behave the same and lean towards being silent. I can change that in this PR.

The last time I asked reduz, about RIDs he said ask @RandomShaper .

**Comment by lawnjelly** [comment]
I think on balance it would be better to just fix setting the RIDs to NULL in this PR, you can add `if not NULL` checks if the free is not tolerant for now, then that can be changed in a later PR. Once this is done it can be approved and merged.

We generally prefer to keep as small a change as possible in each PR till they are indivisible. Sometimes we end up with more than one thing in a PR, but it's to be avoided where possible. Case in point the tolerance of NULL frees is a different issue and requires consideration in its own right (which may delay the PR) and I can sort this if we decide to do it (there may be some considerations you are not familiar with). Also separate PRs means each can easily be reverted etc in its own right.

File: drivers/gles2/rasterizer_storage_gles2.cpp [hunk 9]
```diff
@@ -5837,8 +5837,8 @@ bool RasterizerStorageGLES2::free(RID p_rid) {
 		memdelete(t);
 		render_target_owner.free(p_rid);
 		memdelete(rt);
-
 		return true;
+
 	} else if (texture_owner.owns(p_rid)) {
```
Comment (lawnjelly) [inline drivers/gles2/rasterizer_storage_gles2.cpp:5842]: These minor formatting changes are considered 'noise' in the commit and these should be removed, in general the policy is to only change the places you are changing code.

File: editor/plugins/spatial_editor_plugin.cpp [hunk 10]
```diff
@@ -5856,15 +5862,27 @@ void SpatialEditor::_init_grid() {
...
 	_finish_grid();
 }
 
 void SpatialEditor::_finish_grid() {
-	for (int i = 0; i < 3; i++) {
-		VisualServer::get_singleton()->free(grid_instance[i]);
-		VisualServer::get_singleton()->free(grid[i]);
+	for (int a = 0; a < 3; a++) {
+		if (grid_enable[a]) {
+			int c = (a + 2) % 3;
```
Comment (lawnjelly) [inline editor/plugins/spatial_editor_plugin.cpp:5875]: This `if (grid_enable)` is new - just wondering why is this needed (sorry I'm not super familiar with this code)?

**Comment by lawnjelly** [comment]
> @lawnjelly This PR has now been stripped down to only resetting the RIDs that were freed. I'm creating a second PR for changes to the servers and their documentation.

Yup sure it looks great I was about to approve, but I just spotted the `if (grid_enable)` bit and want to check the reasoning for that to make sure it is the right thing to do.

**Comment by tinmanjuggernaut** [comment]
@lawnjelly I responded to you on the thread. You can compare the iteration scheme for the calculation of a and c with the functions I listed and it should be identical.

**Comment by lawnjelly** [comment]
> @lawnjelly I responded to you on the thread.

Sorry I don't understand, have you got a link to this?

**Comment by tinmanjuggernaut** [comment]
Scroll up to where  you commented on the code and wrote `This if (grid_enable) is new - just wondering why is this needed (sorry I'm not super familiar with this code)?`. You created a code review thread. I responded to you directly on that thread. It should have sent you an email as well. Also you can click the `Files Changed` tab and a page down where you commented on the code my response is immediately below.

**Comment by akien-mga** [comment]
@tinmanjuggernaut It's not visible to me either, I guess it wasn't sent. Maybe it's in a pending review?

**Comment by tinmanjuggernaut** [comment]
@akien-mga It does say "Pending" but I have no option to have it not pend.

@lawnjelly Here is my comment:

The old code freed every grid_instance and grid, every tick, regardless of whether they were in use or not, and valid or not.

Now it only considers the ones that are enabled, using the same wonky iteration scheme defined in `SpatialEditor::_init_grid()` here:

https://github.com/godotengine/godot/blob/30033e7670346b705a10ffe0253d813c1c1db8a7/editor/plugins/spatial_editor_plugin.cpp#L5752

Where the RIDs are created in the two paragraphs here:
https://github.com/godotengine/godot/blob/30033e7670346b705a10ffe0253d813c1c1db8a7/editor/plugins/spatial_editor_plugin.cpp#L5846

**Comment by lawnjelly** [comment]
Ah sorry for confusion, it may be some moderation thing just until your first PR is merged, something like that. :slightly_smiling_face: 

I'm not sure the `if grid_enabled` is wise to add in this PR. Reason being that it opens up potential for leaks, either now or in future. Consider if someone changes `grid_enabled[i]` while a RID still exists.

So I would go for simply setting to NULL here, and we can evaluate improvements in another PR?

As an aside the whole grid thing here I can see a few potential problems so it could do with an overhaul, but it would be nice to just get the immediate bugs fixed first.

**Review by lawnjelly — APPROVED** [review]
Look good! :smile:
Sorry for being picky it's always traumatic especially with first PRs. Great work on finding this! :+1:

**Comment by tinmanjuggernaut** [comment]
Alright, but stand by. I'm putting in a few more if... is_valid checks() that should be in these files.

**Comment by akien-mga** [comment]
BTW is the list of fixed issues in the OP still up-to-date with the current state of this PR?

**Comment by lawnjelly** [comment]
> BTW is the list of fixed issues in the OP still up-to-date with the current state of this PR?

Ah yes this is correct the commit message needs to be properly filled out. See:
https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md

**Comment by tinmanjuggernaut** [comment]
Ok. I added more `is_valid` checks to every instance where they were missing. I also adjusted the commit message.

It should fix all of the Fixes I listed. The probablies and bugsquad add are unknown.

File: editor/plugins/spatial_editor_plugin.cpp [hunk 11]
```diff
@@ -3191,16 +3191,39 @@ void SpatialEditorViewport::_init_gizmo_instance(int p_idx) {
...
-		VS::get_singleton()->free(move_gizmo_instance[i]);
-		VS::get_singleton()->free(move_plane_gizmo_instance[i]);
-		VS::get_singleton()->free(rotate_gizmo_instance[i]);
-		VS::get_singleton()->free(scale_gizmo_instance[i]);
-		VS::get_singleton()->free(scale_plane_gizmo_instance[i]);
+		if (move_gizmo_instance[i].is_valid()) {
+			VS::get_singleton()->free(move_gizmo_instance[i]);
+		}
+		move_gizmo_instance[i] = RID();
+
```
Comment (lawnjelly) [inline editor/plugins/spatial_editor_plugin.cpp:3198]: As this PR has grown again, it's probably more important to do this a bit more sensibly. These setting of the values to RID() only need to occur inside the if statement:
```
		if (move_gizmo_instance[i].is_valid()) {
			VS::get_singleton()->free(move_gizmo_instance[i]);
		        move_gizmo_instance[i] = RID();
		}
```
This applies to all these cases. Aside from that it looks fine to me, I don't know if @akien-mga is okay with the commit message, he is expert in that area. :slightly_smiling_face: 

It's also worth using "may fix" rather than "fix" (if you are not sure via a reproduction project). And also sometimes it can be good to write the fix aspects outside the commit message itself, just in case we later find it doesn't fix one of the issues. Depends how certain you are it fixes them I guess! :smile:

**Comment by tinmanjuggernaut** [comment]
I have moved the assignments inside the if statements. I have limited the commit message to only fixing my bug report.

**Review by lawnjelly — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.1.

**Comment by EzraT** [comment]
Thank you!
