### PR TITLE
Combine `TileMapLayer` debug quadrant shapes to a surface

### LINKED ISSUE #105076: 4.5 Chunked tilemap physics results in large surface count on meshes with holes
### Tested versions

Tested in 4.5dev1 mono.

### System information

Linux Mint 22.1 - Godot 4.5dev1 mono - Vulkan (Forward+)

### Issue description

After the new TileMapLayer collision chunking system has been added relatively simple collision polygons I have been using for a terrain are now spamming the error  

`ERROR: servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:263 - Condition "mesh->surface_count == RenderingServer::MAX_MESH_SURFACES" is true.`

With only a handful of terrain tiles using relatively simple collision polygon shapes using default physics_quadrant_size of 16. The polygon shapes do result in a mesh with a lot of square holes:

Image

And after drawing only around 38 tiles I start to get the error that the mesh exceeds the max number of surfaces:

Image

Here are how the polygons are set up in the TileSet:

Image

HOWEVER if I make one small change to the polygons and delete the extra inside corner vertices:

Image

This still results in a mesh with square holes that are rotated 45 degrees and the same number of vertices BUT significantly fewer surfaces in the mesh (not even close):

Image

Because the resulting number of surfaces from the physics chunking is wildly different based on small modifications to the collision polygons (and still very similar shapes/number of vertices) it looks like the algorithm is inconsistent at the moment or at the very least is not well optimized with holes in the mesh. 

### Steps to reproduce

1. Create a TileSet with a physics layer and default value of 16 (or larger) for physics_quadrant_size.
2. Create some tiles using the same physics layer that when placed next to each other will result in a collision mesh with "holes"
in it (in my case fences with corner, cross and t shapes when connected and will result in "holes" when connected in squares).

### Minimal reproduction project (MRP)

[mrp---chunking-bug.tar.gz](https://github.com/user-attachments/files/19618901/mrp---chunking-bug.tar.gz)

This MRP has a TileMapLayer with view_collision_shapes enabled and collision_visibility_mode set to force shown. It contains a TileSet that has a very simple "waffle" shape and matching collision shapes that result in a mesh that has holes in it as above. I have drawn several sizes of squares filled with the tiles to show how the number of surfaces in the mesh grows exponentially even for very simple collision shapes and exceeds the max number of surfaces with relatively few tiles.

If the square corner vertices are removed resulting in 45 chamfer on the collision polygons as shown below the number of surfaces is drastically reduced even though the "holes" only seem to have rotated 45 degrees:

Image

### PR DESCRIPTION
**Pull request by smix8**
Create a combined mesh surface for all mesh faces and mesh lines in the TileMapLayer debug quadrant. Before it created a new mesh surface for each shape crashing into the mesh surface limit of 256 quickly.

Fixes https://github.com/godotengine/godot/issues/105076

### CODE REVIEW

File: scene/2d/tile_map_layer.cpp [hunk 1]
```diff
@@ -1085,56 +1098,112 @@ void TileMapLayer::_physics_draw_quadrant_debug(const RID &p_canvas_item, DebugQ
...
-						PackedColorArray face_color_array;
-						face_color_array.resize(outline.size() + 1);
-						PackedInt32Array face_index_array;
-						face_index_array.resize((outline.size() - 2) * 3);
+						// Adds debug mesh lines.
 
-						PackedColorArray line_color_array;
-						line_color_array.resize(outline.size() + 1);
+						for (int i = 0; i < outline_size; i++) {
+							const Vector2 vertex1 = outline_xform.xform(outline[i % outline_size]);
```
Comment (kiroxas) [inline scene/2d/tile_map_layer.cpp:1119]: You can remove the `%` here.

File: scene/2d/tile_map_layer.cpp [hunk 2]
```diff
@@ -1085,56 +1098,112 @@ void TileMapLayer::_physics_draw_quadrant_debug(const RID &p_canvas_item, DebugQ
...
+							const Vector2 vertex2 = outline_xform.xform(outline[(i + 1) % outline_size]);
 
-						for (int i = 0; i < outline.size() + 1; i++) {
-							Vector2 vertex = (body_to_quadrant * shape_xform).xform(outline[i % outline.size()]);
-							vertex_array.write[i] = vertex;
-							face_color_array.write[i] = random_variation_color;
-							line_color_array.write[i] = random_variation_color.lightened(0.2);
+							line_vertex_array.push_back(vertex1);
```
Comment (kiroxas) [inline scene/2d/tile_map_layer.cpp:1122]: You can probably resize above the loop for line_vertex_array and line_color_array with  2 * outline_size

File: scene/2d/tile_map_layer.cpp [hunk 3]
```diff
@@ -1085,56 +1098,112 @@ void TileMapLayer::_physics_draw_quadrant_debug(const RID &p_canvas_item, DebugQ
...
 
-						PackedColorArray face_color_array;
-						face_color_array.resize(outline.size() + 1);
-						PackedInt32Array face_index_array;
-						face_index_array.resize((outline.size() - 2) * 3);
+						// Adds debug mesh lines.
 
-						PackedColorArray line_color_array;
-						line_color_array.resize(outline.size() + 1);
+						for (int i = 0; i < outline_size; i++) {
```
Comment (kiroxas) [inline scene/2d/tile_map_layer.cpp:1118]: This is usually better with some `Vector2 prev = outline_xform.xform(outline[outline_size - 1]);` outside of the loop, and then just assign prev to the current one. Remove the % and the xform each loop.

File: scene/2d/tile_map_layer.cpp [hunk 4]
```diff
@@ -1085,56 +1098,112 @@ void TileMapLayer::_physics_draw_quadrant_debug(const RID &p_canvas_item, DebugQ
...
 					if (type == PhysicsServer2D::SHAPE_CONVEX_POLYGON) {
 						PackedVector2Array outline = ps->shape_get_data(shape);
+						const int outline_size = outline.size();
+						if (outline_size < 3) {
+							continue;
+						}
 
-						PackedVector2Array vertex_array;
-						vertex_array.resize(outline.size() + 1);
+						const Color outline_random_variation_color = random_variation_color.lightened(0.2);
```
Comment (kiroxas) [inline scene/2d/tile_map_layer.cpp:1113]: This could be outside the loop

**Comment by smix8** [comment]
So considering this was a loop to update all the dirty debug physics quadrants, potentially hundreds of them, I decided to switch the debug logic a little.

I moved the entire arrays used in the buildup for the debug geometry to `LocalVectors` and `AHashMap` outside the loop. We can clear those at the start of each new quadrant starting fresh while keeping all the memory allocated from the previous quadrant build speeding things up. The push_back() on an already allocated LocalVector is dirty cheap compared to packed Vector.

Only at the very end we convert to the needed packed Vector arrays for the mesh surface arrays which would create a CoW copy anyway. This removes the need for some convoluted index and resize logic for some marginal performance gains with packed vector. Imo the better solution to combine both codestyle and performance.

**Review by kiroxas — APPROVED** [review]

**Review by groud — APPROVED** [review]
The new code is a bit harder to read IMO, but I think it fix the issue nicely enough.
So it's fine by me.

**Comment by Repiteo** [comment]
Thanks!
