### PR TITLE
GDScript: Add constant `Array` and `Dictionary` constructors

### LINKED ISSUE #66949: Can't use a inital dictionary like in Godot3
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

windows 10

### Issue description

Migrating my plugin and run into this issue.

**[Parse Error: Initializer for a constant must be a constant expression.](res://testScene.gd:4 - Parse Error: Initializer for a constant must be a constant expression.)**

The error line is also invalid, the error occurs at line 23 for `TYPE_DICTIONARY: Dictionary(),`

I used a static/const dictionary to predefine default object for each type like
```
const DEFAULT_VALUES_BY_TYPE := {
	TYPE_NIL: null,
	TYPE_BOOL: false,
	TYPE_INT: 0,
	TYPE_FLOAT: 0.0,
	TYPE_STRING: "",
	TYPE_VECTOR2: Vector2.ZERO,
	TYPE_RECT2: Rect2(),
	TYPE_VECTOR3: Vector3.ZERO,
	TYPE_TRANSFORM2D: Transform2D(),
	TYPE_PLANE: Plane(),
	TYPE_QUATERNION: Quaternion(),
	TYPE_AABB: AABB(),
	TYPE_BASIS: Basis(),
	TYPE_TRANSFORM3D: Transform3D(),
	TYPE_COLOR: Color(),
	TYPE_NODE_PATH: NodePath(),
	TYPE_RID: RID(),
	TYPE_OBJECT: null,
	TYPE_DICTIONARY: Dictionary(),
	TYPE_ARRAY: Array(),
	TYPE_PACKED_BYTE_ARRAY: PackedByteArray(),
}
```
The last three entries produces the issue.
I can replace by
```
	TYPE_DICTIONARY: {},
	TYPE_ARRAY: [],
```
But thats inconsistent to the other used values e.i. `TYPE_RECT2: Rect2(),`
And `TYPE_PACKED_BYTE_ARRAY: PackedByteArray(),` cant be fixed at the moment

This is blocking me from migrating my plugin, I want to have static pre-initialized dictionaries used by my tools to access them through static functions.

### Steps to reproduce

create a gd script and put in
```


const DEFAULT_VALUES_BY_TYPE := {
	TYPE_NIL: null,
	TYPE_BOOL: false,
	TYPE_INT: 0,
	TYPE_FLOAT: 0.0,
	TYPE_STRING: "",
	TYPE_VECTOR2: Vector2.ZERO,
	TYPE_RECT2: Rect2(),
	TYPE_VECTOR3: Vector3.ZERO,
	TYPE_TRANSFORM2D: Transform2D(),
	TYPE_PLANE: Plane(),
	TYPE_QUATERNION: Quaternion(),
	TYPE_AABB: AABB(),
	TYPE_BASIS: Basis(),
	TYPE_TRANSFORM3D: Transform3D(),
	TYPE_COLOR: Color(),
	TYPE_NODE_PATH: NodePath(),
	TYPE_RID: RID(),
	TYPE_OBJECT: null,
	TYPE_DICTIONARY: Dictionary(),
	TYPE_ARRAY: Array(),
	TYPE_PACKED_BYTE_ARRAY: PackedByteArray()
}
```

or 
```
const x1 = []
const x2 = Rect2()
const x3 = PackedByteArray()
```

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by dalexeev**
* Closes #66949.

Some people prefer `Array()` and `Dictionary()` instead of `[]` and `{}` for some reason. This PR adds support for using the `Array` and `Dictionary` constructors as constant initializers, as long as the constructors' arguments are constant expressions.

* Note that constant expressions still don't support packed arrays, this is a core issue, see #67873.
* The verbose typed array constructor also works, but it looks like some improvements are needed.
* I also noticed a bug with constant sharing, but it looks like this is another compiler issue, not related to the analyzer. See also #44459 and #48038.

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -4467,6 +4472,53 @@ Variant GDScriptAnalyzer::make_subscript_reduced_value(GDScriptParser::Subscript
...
+			type = Variant::ARRAY;
+		} else if (p_call->function_name == SNAME("Dictionary")) {
+			type = Variant::DICTIONARY;
+		} else {
+			return Variant();
+		}
+
+		Vector<Variant> args;
+		args.resize(p_call->arguments.size());
+		const Variant **argptrs = (const Variant **)alloca(sizeof(const Variant **) * args.size());
```
Comment (dalexeev) [inline modules/gdscript/gdscript_analyzer.cpp:4488]: I don't know if there is a better way, just copied this to appease the compiler.

File: modules/gdscript/tests/scripts/analyzer/features/const_array_and_dictionary_constructors.gd [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+const A3 = [Array()]
+const A4 = [[]]
+
+const IA = Array([1, 2, 3], TYPE_INT, &"", null)
+
+const D = Dictionary()
+const D1 = Dictionary(Dictionary())
+const D2 = Dictionary({})
+const D3 = {d = Dictionary()}
+const D4 = {d = {}}
```
Comment (kleonc) [inline modules/gdscript/tests/scripts/analyzer/features/const_array_and_dictionary_constructors.gd:13]: Would be good to add `var` counterparts ensuring they don't end up being readonly when initialized the same way (unless that's already tested elsewhere).

Comment (dalexeev) [reply modules/gdscript/tests/scripts/analyzer/features/const_array_and_dictionary_constructors.gd:13]: Done.

**Comment by Mickeon** [comment]
So, is this PR still good to have?

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` https://github.com/godotengine/godot/commit/dbddc9ef29bca54dce76ec8b13fa2192b22c7dc2), it works as expected. Code looks good to me.

**Comment by Repiteo** [comment]
Thanks!
