### PR TITLE
[Windows] Fix `OS.open_dynamic_library`

### LINKED ISSUE #96231: 4.4.dev: .NET SDK detection is broken
### Tested versions

- Reproducible in 622393c1156e6ee349a2636c28183021b1442cbc
- Reproducible in da230f384b90360ec108ce1be2347a327d68ca07
- Not Reproducible in 4e051ff6f7fee918b90e1871b4bc36c9f6fa7142

### System information

Godot v4.4.dev.mono (4e051ff6f) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 32.0.15.6094) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description

When attempting to run the Godot Editor built with the mono module enabled, the notification is shown that no .NET SDK is detected. Attempting to load a project hard crashes the editor.

net error

I am very certain that this issue is related to [da230f384b90360ec108ce1be2347a327d68ca07] as this is the first commit at which it fails. 

### Steps to reproduce

- Attempt to run Godot with the mono module enabled and create / load a project.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes incorrect rebase of https://github.com/godotengine/godot/pull/91902 after https://github.com/godotengine/godot/pull/96192 (dll directory was used instead of name).

Fixed https://github.com/godotengine/godot/issues/96231

### CODE REVIEW

File: modules/mono/editor/hostfxr_resolver.cpp [hunk 1]
```diff
@@ -260,7 +260,7 @@ bool get_dotnet_self_registered_dir(String &r_dotnet_root) {
 		return false;
 	}
 
-	r_dotnet_root = String::utf16((const char16_t *)buffer.ptr());
+	r_dotnet_root = String::utf16((const char16_t *)buffer.ptr()).replace("\\", "/");
```
Comment (bruvzg) [inline modules/mono/editor/hostfxr_resolver.cpp:263]: Note: this change is not necessary (everything will work without it), but makes path cleaned (had mixed `\` and `/`).

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
