### PR TITLE
Fix Offset with OptionButton Popup

### LINKED ISSUE #18441: PopupMenus cannot be opened outside of the world-space screen rectangle
Godot 3.0.2

I tried to open a PopupMenu somewhere in my scene, but if it is at negative coordinates it gets snapped back to the positive range.
It looks like it's impossible for a PopupMenu to appear outside of the area that represents the screen, even if the menu is placed in the "world" (I have a camera looking elsewhere, which is why the menu may appear at arbitrary world positions and not just on screen).

Sorry I don't have a minimal project because I'm out of time, but here is the code I used:
```gdscript
func _open_context_menu(pos):
	if _context_menu != null:
		_context_menu.queue_free()
	_context_menu = PopupMenu.new()
	add_child(_context_menu)
	_context_menu.rect_position = pos
	_context_menu.popup()
```
And my scene at runtime:
image

image

However I may fallback on opening the menu on a separate layer because my app has zoom and I don't want the menu to scale with it. I thought I would mention this behaviour because it might be unwanted in some cases.

### LINKED ISSUE #31098: Option Button Popup is displaced
**Godot version:**

3.1

**Issue description:**

Moving an Options Button displaced the Popup that appears once you click it. The displacement becomes more severe the further the button is moved from _an arbitrary, yet fixed_ point.

**Steps to reproduce:**
Create an Option Button, implement the ability to move it by dragging. Observe how the popup begins appearing in increasingly wrong locations.

In my case the button is contained within a panel container which implements the drag movement.

```
func _gui_input(event: InputEvent) -> void:
	if event is InputEventMouseMotion:
		if Input.is_mouse_button_pressed(BUTTON_LEFT):
			rect_position += event.relative
```

### PR DESCRIPTION
**Pull request by codecustard**
Fixes the offset issue with the OptionButton's popup.

The popup of an OptionButton offsets itself to stay within the viewport bounds. When the viewport position is not zero, the offset is incorrect because it does not check the viewport position when offsetting.

Example project with two scenes (one with a camera and one without a camera)
http://s000.tinyupload.com/index.php?file_id=49870689348996793563

Closes: #31098 and closes #18441

### CODE REVIEW

File: scene/gui/popup.cpp [hunk 1]
```diff
@@ -75,16 +75,17 @@ void Popup::_fix_size() {
 	Point2 pos = get_global_position();
 	Size2 size = get_size() * get_scale();
 	Point2 window_size = get_viewport_rect().size;
+	Point2 vpos = get_viewport_transform().get_origin();
 
-	if (pos.x + size.width > window_size.width)
-		pos.x = window_size.width - size.width;
-	if (pos.x < 0)
-		pos.x = 0;
+	if (pos.x + size.width > window_size.width - vpos.x)
```
Comment (akien-mga) [inline scene/gui/popup.cpp]: You should get the same by simply subtracting `vpos` to `pos` at the end of the calculations instead of doing it separately in all checks and coordinate assignments, no?

Comment (sparkart) [reply scene/gui/popup.cpp]: Yes, you're right... however by window_size, not pos.

**Comment by akien-mga** [comment]
Thanks!
