### PR TITLE
Limit Physics Process FPS above 0

### LINKED ISSUE #19734: Certian editor functionality breaks when Phsyics FPS is 0
**Godot version:**
3.0.2, 3.0.3, and 3.0.4 all seem affected by this

**OS/device including version:**
Surface Pro 4, running Windows 10 Home v1709 (Fall Creator's Update)

**Issue description:**
Setting Physics Process FPS in the project settings to 0 or lower causes issues, both in the game and in the editor. Notable issues I noticed:

* Cannot close the editor or game without closing the console window attached to those
* While the Project Settings window appears, the actual settings list never appear, making it impossible to edit settings. Same goes for Editor Settings.
* Quit to Project List sort of works. It brings up the project list as normal, but the editor that was supposed to quit, does not.

There may be other issues that I haven't noticed. My intent with setting its FPS to 0 is to prevent the physics system from running at all, as I'm building a tool which won't need physics, and so it'd be a waste of CPU usage to leave it on, even at 1 FPS.

Out of curiousity, I set the Physics FPS to 1, and it appears that the things I described above will happen at the physics framerate. I'm not sure why they happen when a physics frame comes and not just immediately, but...

**Steps to reproduce:**
1. Open up any existing project or create a new one.
2. Once the editor loads, go to Project Settings -> Physics -> Common and set the Physics Process FPS to 0.
3. Save the project and quit.
4. Reopen the editor, and reload the project.
5. The issue occurs, as described above.

To fix the issue, just in case you're affected by this:
1. Open up your project's project.godot file.
2. Look for the `[physics]` section.
3. The key you're looking for is `common/physics_fps`. Either set that back to where you want it, or delete it to default to 60 Physics FPS.

**Minimal reproduction project:**
[Bug Report - Physics FPS 0 causes editor glitches.zip](https://github.com/godotengine/godot/files/2129993/Bug.Report.-.Physics.FPS.0.causes.editor.glitches.zip)

### PR DESCRIPTION
**Pull request by codecustard**
Resolves: #19734

### CODE REVIEW

File: core/engine.cpp [hunk 1]
```diff
@@ -38,7 +38,7 @@
 
 void Engine::set_iterations_per_second(int p_ips) {
 
-	ips = p_ips;
+	ips = p_ips > 0 ? p_ips : 1;
```
Comment (akien-mga) [inline core/engine.cpp]: I would make it throw an error instead of overriding the value silently (users would wonder why it still runs at 1 FPS even though they asked for 0 or -42):
```
ERR_FAIL_COND(p_ips <= 0);
```

File: main/main.cpp [hunk 2]
```diff
@@ -1020,6 +1020,7 @@ Error Main::setup(const char *execpath, int argc, char *argv[], bool p_second_ph
 	}
 
 	Engine::get_singleton()->set_iterations_per_second(GLOBAL_DEF("physics/common/physics_fps", 60));
+	ProjectSettings::get_singleton()->set_custom_property_info("physics/common/physics_fps", PropertyInfo(Variant::INT, "physics/common/physics_fps", PROPERTY_HINT_RANGE, "1,120,1,or_greater"));
```
Comment (akien-mga) [inline main/main.cpp]: 144 Hz is already a common refresh rate for some monitors, so I guess the range should go up to 144. (With `or_greater` it's already possible to go beyond, but I would expect the default slider range to include all common monitor refresh rates.)

Comment (akien-mga) [reply main/main.cpp]: Though I see `force_fps` is limited to 120 below too, so I guess it's fine as is :)

File: core/engine.cpp [hunk 3]
```diff
@@ -39,6 +39,7 @@
 void Engine::set_iterations_per_second(int p_ips) {
 
 	ips = p_ips;
+	ERR_FAIL_COND(p_ips <= 0);
```
Comment (akien-mga) [inline core/engine.cpp]: This should be before `ips = p_ips;`, as it will cause an early return and thus prevent setting `ips` to an invalid value.

**Comment by akien-mga** [comment]
Thanks!
