### PR TITLE
Only reset the tooltip timer when the mouse has actually moved

### LINKED ISSUE #94189: Tooltips do not display on hover on multi-monitor setups
### Tested versions

Reproducible in: v4.3.beta3.mono, v4.2.2.stable.mono, Godot v4.2.1.stable.mono, Godot v4.2.stable.mono

### System information

Godot v4.2.2.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 (NVIDIA; 32.0.15.5599) - AMD Ryzen 7 7700X 8-Core Processor (16 Threads)

### Issue description

Tooltips fails to appear in the editor interface when hovering over editor buttons.

I have examined the Signals tab, Scene tab, and Movement Controls tab, but tooltips do not display in any of these areas.

Tooltips function correctly on a Linux laptop, suggesting the problem may be specific to Windows or related to my multi-monitor configuration

### Steps to reproduce

- Run Godot
- Hover mouse over an editor tile where tooltip is expected to show

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #95845: Tooltips may fail to display due to spurious zero-motion WM_MOUSEMOVE events on Windows
### Tested versions

Reproduced in 4.1, 4.2, 4.3, and 4.4 builds from master branch.

### System information

Windows 10.0.22631

### Issue description

Before displaying a tooltip, Godot sets a `SceneTreeTimer` and waits for `gui/timers/tooltip_delay_sec` before showing the tooltip. Any received `InputEventMouseMotion` event resets this timer. On Windows, Godot translates every OS level `WM_MOUSEMOVE` event into a an internal `InputEventMouseMotion` event.

On Windows, `WM_MOUSEMOVE` is not guaranteed to only fire from mouse motion. For example, it may be generated as part of `WM_NCHITTEST` events from other applications. In my case, the application ElevenClock will generate a constant stream of `WM_NCHITTEST` and  `WM_MOUSEMOVE` events to other applications. In the case of Godot, this will prevent tooltips from ever appearing. Winamp is also known to have this behavior.

Here's a Chromium bug from 2014 that similarly discovered and had to deal with spurious `WM_MOUSEMOVE` events on Windows: https://issues.chromium.org/issues/41118169

Additionally, Godot itself will generate `InputEventMouseMotion` without any actual mouse motion on any operating system, such as when the cursor changes shape. It's simply not safe to assume that `InputEventMouseMotion` means that the mouse has moved without inspecting relative position.

The timer should only be reset when the relative position is non-zero. The documentation for `InputEventMouseMotion` should also probably be updated to note this caveat.

### Steps to reproduce

Reliable reproduction requires running the editor with other software that's known to regularly run hit tests against other windows, such as [ElevenClock](https://github.com/marticliment/ElevenClock). When running the Godot editor next to such an application, tooltips will be broken throughout the editor regardless of the current project.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by jadoc**
`InputEventMouseMotion` isn't guaranteed to fire only on actual mouse movement. It's not uncommon for the underlying OS motion event to be sent either by the OS itself or another application even though the mouse hasn't moved.  Godot will generate such zero-motion `InputEventMouseMotion` events itself for things like cursor shape changes.

This fixes #95845. There's a chance this could also fix #94189.

### CODE REVIEW

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -1933,7 +1933,7 @@ void Viewport::_gui_input_event(Ref<InputEvent> p_event) {
 					}
 				}
 
-				if (!is_tooltip_shown && over->can_process()) {
+				if (!is_tooltip_shown && over->can_process() && mm->get_relative() != Vector2()) {
```
Comment (KoBeWi) [inline scene/main/viewport.cpp:1936]:
```suggestion
				if (!is_tooltip_shown && over->can_process() && !mm->get_relative().is_zero_approx()) {
```

Comment (Mickeon) [reply scene/main/viewport.cpp:1936]: Makes me wonder if it's a good time to reconsider whether resetting the tooltip at the slightest movement is a good idea. Most software I have used only resets it when moving outside of the "control" that caused it.

Comment (jadoc) [reply scene/main/viewport.cpp:1936]: This only resets the timer for initial display of the tooltip. Once the tooltip is displayed, it will only be removed after the mouse moves outside of the relevant Control.

**Comment by Calinou** [comment]
I wonder if the same approach can be used to fix https://github.com/godotengine/godot/issues/32990 in 3.x.

File: scene/main/viewport.cpp (hunk 1 above)
Comment (jadoc) [reply scene/main/viewport.cpp]: Switched to is_zero_approx().

**Comment by jadoc** [comment]
> I wonder if the same approach can be used to fix #32990 in 3.x.

I tested 3.x and it has the same issue as 4.x. I prepared a backport to 3.x of the fix: jadoc/godot@c5f72a9208e015a7669a459a84fea1207b5acafc

I will create a pull request for 3.x after this pull request is merged. I don't know if this fixes everything going on in #32990.

**Review by bruvzg — COMMENTED** [review]
Seems OK, but it probably should have some threshold not just zero, like `&& mm->get_relative().length() > 5.0` (5 px distance is used for double-click detection on some platforms).

**Comment by jadoc** [comment]
> Seems OK, but it probably should have some threshold not just zero, like `&& mm->get_relative().length() > 5.0` (5 px distance is used for double-click detection on some platforms).

This is a good idea, but  can't be substituted directly because it might suppress the initial starting of the timer. Conditional logic is necessary that depends on whether the timer has started or not. I have added a commit that includes that slightly convoluted logic. If people are happy with it, I will rebase.

**Comment by jadoc** [comment]
Note that a fixed threshold of 5 pixels will fail to take into account UI scaling. If desired, I can attempt to scale the threshold with the UI.

**Comment by jadoc** [comment]
There doesn't appear to be a general way to determine UI scale outside of the editor, and the code in question isn't specific to the editor. To support scaling the tooltip movement threshold with the UI, either the threshold would  need to be user-configurable (putting the onus back on the user), or there would have to be a general engine-wide concept of UI scale (not just window scale) beyond the editor. Both  are beyond the scope of this pull request.

I'm going to go ahead and rebase so that this is ready to merge if there are no more comments.

**Review by bruvzg — APPROVED** [review]

File: scene/main/viewport.cpp [hunk 2]
```diff
@@ -1933,7 +1933,12 @@ void Viewport::_gui_input_event(Ref<InputEvent> p_event) {
 					}
 				}
 
-				if (!is_tooltip_shown && over->can_process()) {
+				// If the tooltip timer isn't running, start it.
+				// Otherwise, only reset the timer if the mouse has moved more than 5 pixels.
+				if (!is_tooltip_shown && over->can_process() &&
+						(!gui.tooltip_timer.is_valid() ||
```
Comment (AThousandShips) [inline scene/main/viewport.cpp:1939]:
```suggestion
						(gui.tooltip_timer.is_null() ||
```

**Comment by Calinou** [comment]
> There doesn't appear to be a general way to determine UI scale outside of the editor

See https://github.com/godotengine/godot-proposals/issues/6836 and its PR implementing it: https://github.com/godotengine/godot/pull/80965

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by jadoc** [comment]
> > There doesn't appear to be a general way to determine UI scale outside of the editor
> 
> See [godotengine/godot-proposals#6836](https://github.com/godotengine/godot-proposals/issues/6836) and the PR implementing that proposal: #80965

Your proposal seems to deal with window scale, not necessarily UI scale. Maybe I'm trying to make a distinction that doesn't exist in Godot, but I think I see the need for both. For example, you could have a game with both GUI controls and a HUD. As you resize the window, you would want to resize the HUD to match, but you may not necessarily want to change the size of the GUI controls. A lot of strategy games with complex UIs make this distinction (e.g. Stellaris, Total War). By default, I think you would want to scale the UI based on a scale factor in the display server with optional UI override by the user.

In your proposal, do you intend to replace `EDSCALE` with `Window.get_final_scale_factor()`? If not, is there some other generic way one should be getting UI scale instead of `EDSCALE`, like from a `Theme`?

Anyway, it seems to me that behavior associated with controls (such as tooltips) should scale with the size of the UI controls, not necessarily the window.
