### PR TITLE
Mono: Fix MonoPosixHelper not being found

### LINKED ISSUE #25129: MonoPosixHelper is missing in Windows
**Godot version:**
Godot 3.1 beta 2

**OS/device including version:**
Windows 10 Pro 64bit

**Issue description:**
If using a C# method which requires the MonoPosixHelper Library (e.g. DeflateStream like in issue #24917 ), the game will crash with console log:

```
Unhandled Exception:
System.DllNotFoundException: MonoPosixHelper
at ....
```

**Steps to reproduce:**
Create a Mono Godot Project, add a C# Script to a node and, for example, try to unzip a file.

**Solution:**
Include in GodotSharp/Mono/lib/mono/4.5/ the file MonoPosixHelper.dll. It is currently not included in the Godot download - I have copied the file from one of my steam games and it has run flawless.

### PR DESCRIPTION
**Pull request by neikeq**
Fixes #25129

This PR add the method `OS::set_environment(String, String)`.

### CODE REVIEW

File: platform/uwp/os_uwp.cpp [hunk 1]
```diff
@@ -739,6 +739,11 @@ String OSUWP::get_environment(const String &p_var) const {
 	return "";
 };
 
+bool OSUWP::set_environment(const String &p_var, const String &p_value) const {
+
+	return false;
+}
+
```
Comment (neikeq) [inline platform/uwp/os_uwp.cpp]: I left this like this because the other environment methods are not implemented either. Is there a reason for that? Shouldn't the same implementation as `OS_Windows` work for `OSUWP` in this case?

Comment (vnen) [reply platform/uwp/os_uwp.cpp]: AFAIK UWP does not have access to the environment variables. Unless that changed since I last looked.
