### PR TITLE
Metal: Ensure stencil-only rendering is supported

### LINKED ISSUE #106652: Metal: Stencil buffer not working when depth buffer is disabled
### Tested versions

- v4.4.stable.official [4c311cbee]
- v4.5.dev4.official [209a446e3]

### System information

Godot v4.5.dev4 - macOS Sequoia (15.5.0) - Multi-window, 2 monitors - Metal (Forward+) - integrated Apple M4 Max (Apple9) - Apple M4 Max (16 threads)

### Issue description

Using RenderingDevice to construct a pipeline that only enables stencil support does not generate the expected output.

### Steps to reproduce

Run the attached MRP.

| output | expected output |
| :---- | :---- |
| Image | Image |

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/20356476/mrp.zip)

### PR DESCRIPTION
**Pull request by stuartcarnie**
Closes #106652

| before | after |
| :---- | :---- |
| Image | Image |

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]

File: drivers/metal/metal_objects.mm [hunk 1]
```diff
@@ -597,19 +597,26 @@
 	MDRenderPass const &pass = *render.pass;
 	MDSubpass const &subpass = render.get_subpass();
 
-	// First determine attachments that should be cleared.
-	LocalVector<RDD::AttachmentClear> clears;
-	clears.reserve(subpass.color_references.size() + /* possible depth stencil clear */ 1);
+	uint32_t ds_index = subpass.depth_stencil_reference.attachment;
+	bool shouldClearDepth = (ds_index != RDD::AttachmentReference::UNUSED && pass.attachments[ds_index].shouldClear(subpass, false));
+	bool shouldClearStencil = (ds_index != RDD::AttachmentReference::UNUSED && pass.attachments[ds_index].shouldClear(subpass, true));
```
Comment (Calinou) [inline drivers/metal/metal_objects.mm:602]: Use snake_case for variable names:

```suggestion
	uint32_t ds_index = subpass.depth_stencil_reference.attachment;
	bool should_clear_depth = (ds_index != RDD::AttachmentReference::UNUSED && pass.attachments[ds_index].shouldClear(subpass, false));
	bool should_clear_stencil = (ds_index != RDD::AttachmentReference::UNUSED && pass.attachments[ds_index].shouldClear(subpass, true));
```

File: drivers/metal/metal_objects.mm [hunk 2]
```diff
@@ -597,37 +597,40 @@
...
 
-	for (uint32_t i = 0; i < subpass.color_references.size(); i++) {
+	uint32_t color_count = subpass.color_references.size();
+	uint32_t clear_count = color_count + (clear_depth || clear_stencil ? 1 : 0);
+	if (clear_count == 0) {
+		return;
+	}
+
+	RDD::AttachmentClear *clears = ALLOCA_ARRAY(RDD::AttachmentClear, clear_count);
+	uint32_t clears_idx = 0;
```
Comment (stuartcarnie) [inline drivers/metal/metal_objects.mm:611]: This change didn't fix the bug, but is an optimisation to avoid allocating a `LocalVector` on the heap, as the number of clears will be 10 or less (max 8 for colour buffers, 1 depth and 1 stencil)

**Comment by Repiteo** [comment]
Thanks!

**Comment by stuartcarnie** [comment]
NOTE: If this is back ported, it will need to be paired with #106694
