### PR TITLE
[Editor] Fix threading problems with `TileMap` preview

### LINKED ISSUE #86226: Crash when editing/opening a huge tileset atlas
### Tested versions

4.2.1

### System information

Windows 11 Godot 4.2.1

### Issue description

there seems to be a bug where it crashes when editing and opening a tile set with a huge set of textures

### Steps to reproduce

Create a new tileset -> Drag and drop the given atlas for editting = either going to be laggy, or crash

13_School_32x32

### Minimal reproduction project (MRP)
none

### PR DESCRIPTION
**Pull request by AThousandShips**
As investigated in #87458 this is due to threading problems in the editor, specifically the preview generation, this solves this by handling deferred calls on a separate queue, rather than adding thread safety mechanisms to `TileMapLayer` which I'd say aren't necessary otherwise due to thread safety guarantees, I also suspect there are other possible race conditions here that won't be solved by adding those thread safety features, instead I suggest removing the thread safety from the equation entirely by controlling the timing

The general topic of thread safety of nodes not on the tree is a problem and other nodes suffer from problems due to deferred calls AFAIK, so a broader investigation of that and how `TileMap` and `TileMapLayer` relates to this should be done as well, but I think the pressing concern here is the editor related crash

* Fixes: https://github.com/godotengine/godot/issues/86226

Alternative to:
* https://github.com/godotengine/godot/pull/87458

### CODE REVIEW

File: editor/plugins/tiles/tiles_editor_plugin.cpp [hunk 1]
```diff
@@ -127,6 +130,8 @@ void TilesEditorUtils::_thread() {
 				// Add the viewport at the last moment to avoid rendering too early.
 				callable_mp((Node *)EditorNode::get_singleton(), &Node::add_child).call_deferred(viewport, false, Node::INTERNAL_MODE_DISABLED);
 
+				MessageQueue::get_singleton()->flush();
```
Comment (AThousandShips) [inline editor/plugins/tiles/tiles_editor_plugin.cpp:133]: Unsure if the better style is this or:
```suggestion
				queue.flush();
```

Comment (RandomShaper) [reply editor/plugins/tiles/tiles_editor_plugin.cpp:133]: An interesting question. I'd favor the cumbersome syntax, because, even if in this case you have the pseudo-singleton variable at hand, a more explicit syntax is more consistent with the typical usage of message queues.

**Review by RandomShaper — APPROVED** [review]
Notwithstanding the idea of further investigation, and with the disclaimer that I haven't checked the details, this looks like the right thing to do.

**Comment by YuriSizov** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.
