### PR TITLE
Fix a default shader specular render mode to `SCHLICK_GGX`

### LINKED ISSUE #46838: Spatial Shader with no render_mode set appears to default to "specular_disabled" rather than "specular_schlick_ggx"
**Godot version:**

3.2.4.rc4

**OS/device including version:**

NA

**Issue description:**

When no specular rendermode is specified, Spatial Shaders appear to default to specular_disabled. The manual says that specular_schlick_ggx is supposed to be the default. specular_schlick_ggx also is set both when converting a Spatial Material to a shader and making a visual shader, so it appears it should be the default everywhere?
https://docs.godotengine.org/en/stable/tutorials/shading/shading_reference/spatial_shader.html#render-modes
image

**Steps to reproduce:**
See screebshot above

**Minimal reproduction project:**

See screebshot above

### PR DESCRIPTION
**Pull request by Chaosus**
Makes shader pipeline use `SPECULAR_SCHLICK_GGX`(desktop) and `SPECULAR_BLINN`(mobile) - parameter by default (and if the user didn't define `render_mode` directly).

revert #41533

*Bugsquad edit:* Fixes #46838.

### CODE REVIEW

**Comment by Chaosus** [comment]
Rewrited it completly - now the default render_mode is depends on `rendering/shading/overrides/force_blinn_over_ggx parameter` parameter in Project Settings.

File: servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp [hunk 1]
```diff
@@ -2342,6 +2342,10 @@ RenderForwardMobile::RenderForwardMobile(RendererStorageRD *p_storage) :
 
 		scene_state.lightmap_buffer = RD::get_singleton()->storage_buffer_create(sizeof(LightmapData) * scene_state.max_lightmaps);
 	}
+	bool force_blinn = GLOBAL_GET("rendering/shading/overrides/force_blinn_over_ggx.mobile");
```
Comment (akien-mga) [inline servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp:2345]: `.mobile` here doesn't mean the mobile renderer, but it's a feature override to know if we're running on desktop or mobile. So users can use the mobile renderer, but have different values configured for `force_blinn_over_ggx` depending on the platform.

So you shouldn't check the value with the `.mobile` suffix (I'm not even sure that works). The `.<feature>` part is checked by the engine as an override and will be applied to any use of `"rendering/shading/overrides/force_blinn_over_ggx"` (including the clustered one if running on mobile).

File: servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp [hunk 2]
```diff
@@ -639,7 +639,8 @@ void SceneShaderForwardMobile::init(RendererStorageRD *p_storage, const String p
 
 		actions.render_mode_defines["sss_mode_skin"] = "#define SSS_MODE_SKIN\n";
 
-		bool force_blinn = GLOBAL_GET("rendering/shading/overrides/force_blinn_over_ggx");
+		bool force_blinn = GLOBAL_GET("rendering/shading/overrides/force_blinn_over_ggx.mobile");
```
Comment (akien-mga) [inline servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp:642]: Same here.

File: servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp (hunk 1 above)
Comment (Chaosus) [reply servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp:2345]: TY, didn't knew that

File: servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp (hunk 2 above)
Comment (Chaosus) [reply servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp]: Fixed back

**Comment by reduz** [comment]
I would really prefer to not add so much stuff in the shaders, what was the original problem?

**Comment by Chaosus** [comment]
> what was the original problem?

https://github.com/godotengine/godot/issues/46838

**Review by BastiaanOlij — APPROVED** [review]
I would be fine with the change as shown, my only remark was that the setting between GGX/BLINN was over kill so I am happy with the current solution to make GGX the default on desktop and BLINN the default on mobile. The check at the top of the shader makes it very clear to anyone reading the code what the desired behavior is.

Do need to make sure this is properly documented.

**Comment by Calinou** [comment]
> I would be fine with the change as shown, my only remark was that the setting between GGX/BLINN was over kill so I am happy with the current solution to make GGX the default on desktop and BLINN the default on mobile. The check at the top of the shader makes it very clear to anyone reading the code what the desired behavior is.
> 
> Do need to make sure this is properly documented.

According to https://github.com/godotengine/godot/issues/22637, Blinn and Phong could be removed entirely since GGX has the same number of instructions.

**Comment by Chaosus** [comment]
@Calinou Ok changed to schilck in both cases.

**Comment by clayjohn** [comment]
As a note to whoever merges this #46838 is a 3.x issue and should not be closed by this PR.

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
