### PR TITLE
Fix First Ctrl+R and Ctrl+F not showing long name variables correctly

### LINKED ISSUE #26982: First Ctrl+R and Ctrl+F not showing long name variables correctly
**Godot version:**
3.1 rc2

**OS/device including version:**
Windows 10 x64

**Issue description:**
When trying to replace a long name variable for the first time section in GDScript editor, the cursor positioned at the end but the displayed name is shifted to the left and not appear correctly.
Pressing Ctrl+R again, it shows correctly.

**Steps to reproduce:**

1. Double click on a variable with a long name
image

2. Press Ctrl+R
image

3. Press Ctrl+R again
image

**Minimal reproduction project:**

[New Game Project.zip](https://github.com/godotengine/godot/files/2958674/New.Game.Project.zip)

### PR DESCRIPTION
**Pull request by theoniko**
Fixes #26982

### CODE REVIEW

**Comment by theoniko** [comment]
@akien-mga / @YeldhamDev: I would like to ask request a review of my pull request. Could you please review my changes or assign a reviewer to my pull request?

**Comment by theoniko** [comment]
@akien-mga, @YeldhamDev : Any update for this pull request?

**Review by YeldhamDev — APPROVED** [review]
LGTM

File: scene/gui/line_edit.cpp [hunk 1]
```diff
@@ -613,9 +613,7 @@ void LineEdit::_notification(int p_what) {
 #endif
 		case NOTIFICATION_RESIZED: {
 
-			if (expand_to_text_length) {
-				window_pos = 0; //force scroll back since it's expanding to text length
-			}
+			window_pos = 0; //force scroll back since it's expanding to text length
```
Comment (akien-mga) [inline scene/gui/line_edit.cpp]: The comment is no longer accurate.

Comment (theoniko) [reply scene/gui/line_edit.cpp]: Yes you are right. Could you please remove it from master since it is already merged there?

@akien-mga , @YeldhamDev Thank you for reviewing my pull request.

Comment (YeldhamDev) [reply scene/gui/line_edit.cpp]: I've removed it in this pull: #28913.

And you're very welcome!
