### PR TITLE
Fix "Game embedding not available" message on Wayland

### LINKED ISSUE #102819: "Game Embedding not available on your OS" EndeavorOS Hyprland
### Tested versions

Reproducible in: 4.4.beta3

### System information

Godot v4.4.beta3 - EndeavourOS #1 SMP PREEMPT_DYNAMIC Sun, 02 Feb 2025 01:02:29 +0000 on Wayland - Wayland display driver, Single-window, 1 monitor - Vulkan (Forward+) - integrated Intel(R) HD Graphics 500 (APL 2) - Intel(R) Celeron(R) CPU N3350 @ 1.10GHz (2 threads)

### Issue description

Was going to test for the first time the game embedding from 4.4 and was surprised to seed it did not work, the devlogs said it was available for linux so that got me wondering if it was a Hyprland issue, but I could not find anything online, or on the issues, easily available.

### Steps to reproduce

- Create any new project
- Run any scene
- Open game tab

### Minimal reproduction project (MRP)

Any godot project

### PR DESCRIPTION
**Pull request by Hilderin**
- Fixes #102819

This PR only adjusts the warning message to "Game Embedding not available on your OS" when using Wayland, making it more specific. The previous message was not entirely accurate since the embedding is available on Linux but not on Wayland.

This is the new warning message, I think it could be better but I'm not inspired:
image

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
I think the message is fine. Its clear and tells the user what to do to avoid the problem

**Comment by Hilderin** [comment]
@akien-mga 
That is an excellent question!! Nobody though about this situation before!! I tested and even on Windows when the selected display server is 'headless', the Embedded Window was trying to embbed a non existant window.

I added another warning message when the Display Server in project setting is `headless` or `wayland`:
image

File: editor/plugins/game_view_plugin.h [hunk 1]
```diff
@@ -108,6 +108,7 @@ class GameView : public VBoxContainer {
 		EMBED_NOT_AVAILABLE_MAXIMIZED,
 		EMBED_NOT_AVAILABLE_FULLSCREEN,
 		EMBED_NOT_AVAILABLE_SINGLE_WINDOW_MODE,
+		EMBED_NOT_AVAILABLE_PROJECT_DISPLAY_DRIVER
```
Comment (AThousandShips) [inline editor/plugins/game_view_plugin.h:111]:
```suggestion
		EMBED_NOT_AVAILABLE_PROJECT_DISPLAY_DRIVER,
```

Comment (Hilderin) [reply editor/plugins/game_view_plugin.h]: done!

File: editor/plugins/game_view_plugin.cpp [hunk 2]
```diff
@@ -489,7 +493,14 @@ void GameView::_update_ui() {
...
 		case EMBED_NOT_AVAILABLE_FEATURE_NOT_SUPPORTED:
-			state_label->set_text(TTR("Game embedding not available on your OS."));
+			if (DisplayServer::get_singleton()->get_name() == "Wayland") {
+				state_label->set_text(TTR("Game embedding not available on Wayland.\nWayland can be disabled in the Editor Settings (Run > Platforms > Linux/*BSD > Prefer Wayland)."));
+			} else {
+				state_label->set_text(TTR("Game embedding not available on your OS."));
+			}
+			break;
+		case EMBED_NOT_AVAILABLE_PROJECT_DISPLAY_DRIVER:
+			state_label->set_text(vformat(TTR("Game embedding not available for the Display Server: '%s'.\nDisplay Server can be modified in the Project Settings (Display > Driver Server)."), GLOBAL_GET("display/display_server/driver")));
```
Comment (akien-mga) [inline editor/plugins/game_view_plugin.cpp:503]:
```suggestion
			state_label->set_text(vformat(TTR("Game embedding not available for the Display Server: '%s'.\nDisplay Server can be modified in the Project Settings (Display > Display Server > Driver)."), GLOBAL_GET("display/display_server/driver")));
```

Comment (Hilderin) [reply editor/plugins/game_view_plugin.cpp]: Good eye, I read the message 10 times and never saw the error!!

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
