### PR TITLE
obj: Avoid empty names and meshes

### LINKED ISSUE #70539: OBJ files imported as Scene crashes when selecting the mesh in import settings.
### Godot version

4.0 Beta10

### System information

Ubuntu 22.04 (Tuxedo OS)

### Issue description

After importing an *.obj file as a scene, if you click on the mesh in the import settings Godot crashes.

Screenshot from 2022-12-24 14-38-23

I the above screenshot, clicking in the circled area will crash Godot.

### Steps to reproduce

Import .obj file into a project.
Select the file.
Go to import setting.
Change OBJ As Mesh to Scene.
Click Reimport.
Click Save Scenes, Re-Import, and Restart.
Once restarted, open the advanced import settings on the object.
Click the are circled in the description, or in the meshes tab.

### Minimal reproduction project

N/A

Specifically, I lack the distribution rights of the .obj files I am using.  Any .obj file should do, this happened to me on at least 4 different .obj files.

### PR DESCRIPTION
**Pull request by rsjtdrjgfuzkfg**
This PR updates the obj importer to properly name imported meshes and permits it to skip meshes that do not contain geometry. This fixes at least one crash (#70539) and several warnings and avoids unnecessary meshes being generated when importing obj files that do not contain geometry that is not assigned to a named object (such as when exporting from Blender).

Fixes #70539

### CODE REVIEW

File: editor/import/resource_importer_obj.cpp [hunk 1]
```diff
@@ -217,7 +217,8 @@ static Error _parse_obj(const String &p_path, List<Ref<Mesh>> &r_meshes, bool p_
 	Vector<Vector3> vertices;
 	Vector<Vector3> normals;
 	Vector<Vector2> uvs;
-	String name;
+	const String default_name = "Mesh";
+	String name = default_name;
```
Comment (fire) [inline editor/import/resource_importer_obj.cpp:221]: I would use the class name of the mesh.

Comment (rsjtdrjgfuzkfg) [reply editor/import/resource_importer_obj.cpp:221]: The default name will be used for multiple classes throughout the import process (`ArrayMesh`, `ImporterMesh` and `ImporterMeshInstance3D`), so I'm not sure if adding significant complexity to use the name of each individual class if no name is set is a good idea.

**Comment by rsjtdrjgfuzkfg** [comment]
@Riteo can you make an example? "Proper" empty objects like the one in Blender are very useful (as they have a position and orientation), but in obj empty objects don't really have anything?

Also, Godot does not really like empty meshes and prints various error messages if a mesh gets empty. So these empty meshes may cause serious issues down the road.

That said, if it helps some use case, I'm happy to only skip over whitespace before the first object. That is the main practical issue imho: every obj file that consists solely of named objects gets an additional, unnamed and empty mesh. I can't imagine that one being of use to anybody?

**Comment by fire** [comment]
There seems to be disagreement so I can't suggest a merge.

**Comment by rsjtdrjgfuzkfg** [comment]
@fire I don't see disagreement at the moment, so I'm unsure what could move this forward. (Other than rebasing, but I will only do that if there is a chance for the PR to get merged.)

The reason why I propose to generally ignore empty meshes is that `ImporterMesh` considers it an error to have empty meshes (https://github.com/godotengine/godot/blame/master/scene/resources/importer_mesh.cpp#L677, you wrote that error message yourself), so I would expect them to cause issues down the road. This commit thus fixes that error being caused by most obj files generated from tools like Blender. If there should be any use case for empty objects in obj files, I would assume that a separate patch is needed to import them as non-mesh nodes. Any use case we support should not spam the console with error messages (imho).

That said, I can also split this into two PRs (default name here, empty objects in a new PR) and make the second PR only skip the creation of empty objects that clearly are not intended to be there. That would fix the issues I see in my projects, while preserving the current behaviour (including error messages and potential issues down the road) whenever the user intentionally adds empty objects.

**Comment by realkotob** [comment]
@Riteo I reacted with a thumbs up to your doubt because I was also wondering if using empty objects as a pivot is a usecase.

It was only a few days before your comment that I was working with an artist importing an FBX into godot and the objects had the wrong pivot, so your comment got me thinking if using empty objects is a potential workaround, but honestly I have not explored that workaround and I do not think supporting empty objects is the best way to fix pivots.

I would prefer we open a separate issue for incorrect object pivots and I can try to make a PR to fix that properly, not using this hacky empty objects way.

**Comment by fire** [comment]
FBX pivot baking enhancement is being tracked here https://github.com/godotengine/FBX2glTF/issues/25

**Review by akien-mga — APPROVED** [review]
Seems consensual enough in the end, just needs a rebase.

**Comment by rsjtdrjgfuzkfg** [comment]
@akien-mga done

**Comment by akien-mga** [comment]
Thanks!
