### PR TITLE
Fix audio player not resetting after wav finishes

### LINKED ISSUE #36816: Inspector:  Audio playback is playing only once
**Godot version:** 3.2.stable

**OS/device including version:**Win64

**Issue description:** 
Audio playback in the Inspector is playing only once. User has to press stop or double click the file in the Filebrowser to be able to play again.

playback_audiofile

Instead I would expect if the playback finished, simply clicking on the playbutton should suffice to start playback again.

**Steps to reproduce:** 

1. double click an audiofile in the Filebrowser
2. go to the Inspector and click the playbutton 
3. after the playback finished, click the play button again.

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #36816
Supersedes/closes #36903

I also moved initialization of some variables to the header, as there aren't many.

### CODE REVIEW

File: editor/plugins/audio_stream_editor_plugin.cpp [hunk 1]
```diff
@@ -105,6 +105,7 @@ void AudioStreamEditor::_audio_changed() {
 
 void AudioStreamEditor::_play() {
 	if (_player->is_playing()) {
+		_pausing = true;
```
Comment (Calinou) [inline editor/plugins/audio_stream_editor_plugin.cpp:108]: It might be good to add a comment as to *why* we are setting `_pausing` to `true` here. It doesn't seem obvious to me.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.
