### PR TITLE
Store velocity in userdata, use `VELOCITY` to pass to copy shader

### LINKED ISSUE #84227: GPU Particles 2D/3D Interpolation doesn't seem to consider Animated Velocities
### Godot version

v4.2.beta3; v4.2.beta.custom_build [8c7e20d97]

### System information

Windows 10.0.19045 - Vulkan (Forward+, Mobile) - GLES3 (Compatibility) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.4592) - Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 Threads)

### Issue description

When particles use any of the animated velocities, they will feel like there is no interpolation.

It gets worse with lower fps and also with higher velocity forces. Although it's hard to see, it also happens on the default 30fps.

When applying an initial velocity to the particles it feels like ~~I'm seeing Flash trying to phase through a wall~~ the particles are jittering back and forth between a place they think they should be and the place they actually are supposed to be.

Using higher FPSs like 60 or 0 makes the issue go away. Disabling interpolation also stops any jittering.

### Steps to reproduce

The reproduction project has "main_2d" and "main_3d" scenes that show the issue, even in the editor.

### Minimal reproduction project

[GPUParticles Velocity Jitter.zip](https://github.com/godotengine/godot/files/13211105/GPUParticles.Velocity.Jitter.zip)

### PR DESCRIPTION
**Pull request by QbieShay**
Closes https://github.com/godotengine/godot/issues/84227
Closes https://github.com/godotengine/godot/issues/89449

Probably a lot more of issues with interpolation.

This is a dangerous change and will probably break stuff, at the same time i feel like feature freeze is the perfect time for a fix like this, because i need testers. worst case we can just revert

Tested on MRP and particles demo project, seems to work

### CODE REVIEW

**Comment by QbieShay** [comment]
Done some performance testing, those are the numbers i have:

image

Most notable, GLES3 doesn't seem to have any loss of performance, likely we're in memory alignment shenanigans territory.


Forward seems to have a slight loss of performance, between 2% and 7% depending on particle count. This is expected as memory usage grows linearly with particle count per-particle system.

I consider this an acceptable tradeoff, but I'm willing to hear otherwise.

Here's the test project I've used: [userdata-bench.zip](https://github.com/user-attachments/files/24192138/userdata-bench.zip)

File: scene/resources/particle_process_material.cpp [hunk 1]
```diff
@@ -1010,24 +1010,24 @@ void ParticleProcessMaterial::_update_shader() {
...
-		code += "		// Apply friction only to VELOCITY across the surface (effectively decouples friction and bounce behavior).\n";
-		code += "		VELOCITY = mix(VELOCITY, vec3(0.0), clamp(collision_friction, 0.0, 1.0));\n";
-		code += "		// Add bounce velocity to VELOCITY.\n";
-		code += "		VELOCITY -= COLLISION_NORMAL * collision_response * (collision_bounce * slide_to_bounce_trigger);\n";
+		code += "		// Remove all components of USERDATA1.xyz that are not tangential to COLLISION_NORMAL.\n";
+		code += "		USERDATA1.xyz -= COLLISION_NORMAL * collision_response;\n";
+		code += "		// Apply friction only to USERDATA1.xyz across the surface (effectively decouples friction and bounce behavior).\n";
+		code += "		USERDATA1.xyz = mix(USERDATA1.xyz, vec3(0.0), clamp(collision_friction, 0.0, 1.0));\n";
+		code += "		// Add bounce velocity to USERDATA1.xyz.\n";
+		code += "		USERDATA1.xyz -= COLLISION_NORMAL * collision_response * (collision_bounce * slide_to_bounce_trigger);\n";
```
Comment (blueskythlikesclouds) [inline scene/resources/particle_process_material.cpp]: The comments here with USERDATA1.xyz don't make much sense anymore.

**Review by blueskythlikesclouds — COMMENTED** [review]
Looks fine to me. It'd be nice if you could add a few comments in the code explaining what USERDATA1 is used for.

**Review by blueskythlikesclouds — APPROVED** [review]
