### PR TITLE
Fix AudioStreamPlayer3D autoplay and internal notifications

### LINKED ISSUE #87730: AudioStreamPlayer3D autoplay does not work after AudioStreamPlayerInternal refactor
### Tested versions

4.3-dev master as of today 51991e20143a39e9ef0107163eaf283ca0a761ea (happens on any commit after https://github.com/godotengine/godot/pull/87061)

### System information

macOS 14.2.1, Apple M1 Pro

### Issue description

AudioStreamPlayer3D's autoplay property does not work as of https://github.com/godotengine/godot/pull/87061

The ENTER_TREE notification is never run for the 3D node:

```cpp
void AudioStreamPlayerInternal::notification(int p_what) {
	switch (p_what) {
		case Node::NOTIFICATION_ENTER_TREE: {
			print_line("enter tree");
```

The audio plays correctly if I use the remote scene tree to set playing to true.

Commits before #87061 work fine, and if I revert #87061 it works fine.

### Steps to reproduce

1. Open the minimal reproduction project.
2. Set different audio player nodes as autoplay.
3. Observe the following:
    - In master after 87061, AudioStreamPlayer3D autoplay does not work, but it works for 0D and 2D.
    - Before 87061, autoplay works on all players: 0D, 2D, and 3D.

### Minimal reproduction project (MRP)

[AudioStreamPlayerAutoPlayBroken.zip](https://github.com/godotengine/godot/files/14093872/AudioStreamPlayerAutoPlayBroken.zip)

### PR DESCRIPTION
**Pull request by aaronfranke**
Fixes #87730. This line is present for 0D and 2D but was missing for 3D.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Review by fire — APPROVED** [review]

**Review by MJacred — APPROVED** [review]

File: scene/3d/audio_stream_player_3d.cpp [hunk 1]
```diff
@@ -240,6 +240,7 @@ float AudioStreamPlayer3D::_get_attenuation_db(float p_distance) const {
 }
 
 void AudioStreamPlayer3D::_notification(int p_what) {
+	internal->notification(p_what);
 	switch (p_what) {
```
Comment (KoBeWi) [inline scene/3d/audio_stream_player_3d.cpp:244]:
```suggestion
	internal->notification(p_what);

	switch (p_what) {
```

If we wanted to be more consistent with AudioStreamPlayer2D.

**Review by KoBeWi — APPROVED** [review]

File: scene/3d/audio_stream_player_3d.cpp (hunk 1 above)
Comment (aaronfranke) [reply scene/3d/audio_stream_player_3d.cpp:244]: I tend to avoid empty lines that do nothing, also it's more consistent with this code:

```cpp
void AudioStreamPlayer3D::_calc_output_vol(const Vector3 &source_dir, real_t tightness, Vector<AudioFrame> &output) {
	unsigned int speaker_count = 0; // only main speakers (no LFE)
	switch (AudioServer::get_singleton()->get_speaker_mode()) {
```

**Comment by akien-mga** [comment]
Thanks!
