### PR TITLE
Fixed Show in file system should clear current search

### LINKED ISSUE #32262: Show in file system should clear current search
**Godot version:**
72d87cfbce137b8012e86f678c27f0f19a9771cf

**Issue description:**
When you right-click a resource in the inspector or scene tab etc. you have an option to show it in the file system.
image
However if you search something in the filesystem dock (i.e. name filter is enabled), this option won't work... visibly. You need to cancel search to see your file.
image
Obviously this should happen automatically.

### PR DESCRIPTION
**Pull request by CorattiS86**
I add a new method for `FileSystemDock `class, that's `clear_file_list_search_box()`
it allow to clear the `file_list_search_box` inside `FileSystemDock`

Now when you right-click a resource in the inspector or scene tab etc. and select option to show it in the file system, then the search box will be clean then `FileSystemDock `will navigate for that resource

Fixes #32262

### CODE REVIEW

**Review by groud — DISMISSED** [review]
You do not need a new public function for that, this should be directly done inside the FileSystemDock.navigate_to_path() function.

File: editor/editor_properties.cpp [hunk 1]
```diff
@@ -2213,6 +2213,7 @@ void EditorPropertyResource::_menu_option(int p_which) {
 			RES res = get_edited_object()->get(get_edited_property());
 
 			FileSystemDock *file_system_dock = EditorNode::get_singleton()->get_filesystem_dock();
+			file_system_dock->clear_file_list_search_box();
```
Comment (groud) [inline editor/editor_properties.cpp]: You forgot to remove this line. :)

Comment (CorattiS86) [reply editor/editor_properties.cpp]: Sorry, I update now

**Comment by akien-mga** [comment]
Changes seem good, but the commits should be squashed into one. See [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase).

**Comment by groud** [comment]
The PR looks good, once the commits are squashed it is good to merge for me :)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
