### PR TITLE
Fix hint_range for GLES2 shader uniforms

### LINKED ISSUE #27690: Shader uniform float hint_range does not work in GLES2
**Godot version:**
3.1 stable

**OS/device including version:**
Windows 10

**Issue description:**
hint_range does not limit the uniform parameter's range in the editor. This only happens in GLES2, in GLES3 the value is properly limited.

`uniform float value : hint_range(0.0, 1.0);`

### PR DESCRIPTION
**Pull request by JFonS**
Closes #27690.

### CODE REVIEW

File: drivers/gles2/rasterizer_storage_gles2.cpp [hunk 1]
```diff
@@ -3737,7 +3741,8 @@ void RasterizerStorageGLES2::light_set_param(RID p_light, VS::LightParam p_param
 			light->version++;
 			light->instance_change_notify(true, false);
 		} break;
-		default: {}
+		default: {
```
Comment (akien-mga) [inline drivers/gles2/rasterizer_storage_gles2.cpp]: Does your IDE or `clang-format` do that? If the latter, what version do you have? 7.0.1 doesn't modify this code for me.

Comment (JFonS) [reply drivers/gles2/rasterizer_storage_gles2.cpp]: I got that from the clang-format git hook. Looks like I have version 8.0 installed.

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.1.
