### PR TITLE
OpenXR: Add support for retrieving play area

### LINKED ISSUE #85049: OpenXR missing Boundary/Guardian API
### Godot version

4.2.dev 80de898d721f952dac0b102d48bb73d6b02ee1e8

### System information

OpenXR

### Issue description

The Godot 3 OpenXR plugin supported obtaining boundary/guardian information in order to obtain play space logic. While we do have a function in the `XRInterface` in Godot 4 that is supposed to retrieve this information (`get_play_area`) it is not implemented on the Godot 4 `OpenXRInterface`.

This logic needs to be ported.

### Steps to reproduce

Call `get_play_area`, be amazed by it not returning data :P

### Minimal reproduction project

Any XR project.

### PR DESCRIPTION
**Pull request by BastiaanOlij**
This PR implements the `get_play_area` feature on `OpenXRInterface`. This allows the user to retrieve the are within which they can safely move before encountering the guardian boundary.

This re-introduces the `get_play_space` feature in Godot 3s OpenXR support.

Closes: #85049

### CODE REVIEW

File: modules/openxr/openxr_interface.cpp [hunk 1]
```diff
@@ -690,6 +690,47 @@ bool OpenXRInterface::set_play_area_mode(XRInterface::PlayAreaMode p_mode) {
...
+		Vector3(-0.5f, 0.0f, -0.5f),
+		Vector3(0.5f, 0.0f, -0.5f),
+		Vector3(0.5f, 0.0f, 0.5f),
+		Vector3(-0.5f, 0.0f, 0.5f),
+	};
+
+	sides[0] = Vector3(-0.5f, 0.0f, -0.5f);
+	sides[1] = Vector3(0.5f, 0.0f, -0.5f);
+	sides[2] = Vector3(0.5f, 0.0f, 0.5f);
+	sides[3] = Vector3(-0.5f, 0.0f, 0.5f);
```
Comment (m4gr3d) [inline modules/openxr/openxr_interface.cpp:708]: Isn't this duplicating the declaration above?

File: modules/openxr/openxr_interface.cpp [hunk 2]
```diff
@@ -690,6 +690,47 @@ bool OpenXRInterface::set_play_area_mode(XRInterface::PlayAreaMode p_mode) {
 	return false;
 }
 
+PackedVector3Array OpenXRInterface::get_play_area() const {
```
[the remark this answers is not in the document]
Comment (BastiaanOlij) [reply modules/openxr/openxr_interface.cpp:693]: It is through the `XRInterface`, it's a virtual method

File: modules/openxr/openxr_interface.cpp (hunk 1 above)
Comment (BastiaanOlij) [reply modules/openxr/openxr_interface.cpp:708]: Yes it is... weird I overlooked that, we must already have this double in our 3.5 plugin

**Review by m4gr3d — APPROVED** [review]

File: modules/openxr/openxr_interface.cpp [hunk 3]
```diff
@@ -690,6 +690,42 @@ bool OpenXRInterface::set_play_area_mode(XRInterface::PlayAreaMode p_mode) {
...
+
+	if (openxr_api != nullptr && openxr_api->is_initialized()) {
+		Size2 extends = openxr_api->get_play_space_bounds();
+		if (extends.width != 0.0 && extends.height != 0.0) {
+			Transform3D reference_frame = xr_server->get_reference_frame();
+
+			for (int i = 0; i < 4; i++) {
+				Vector3 coord = sides[i];
+
+				// scale it up
```
Comment (AThousandShips) [inline modules/openxr/openxr_interface.cpp:713]:
```suggestion
				// Scale it up.
```

File: modules/openxr/openxr_interface.cpp [hunk 4]
```diff
@@ -690,6 +690,42 @@ bool OpenXRInterface::set_play_area_mode(XRInterface::PlayAreaMode p_mode) {
...
+				coord.x *= extends.width;
+				coord.z *= extends.height;
+
+				// now apply our reference
```
Comment (AThousandShips) [inline modules/openxr/openxr_interface.cpp:717]:
```suggestion
				// Now apply our reference.
```

File: modules/openxr/openxr_api.cpp [hunk 5]
```diff
@@ -2072,6 +2073,25 @@ void OpenXRAPI::set_foveation_dynamic(bool p_foveation_dynamic) {
 	}
 }
 
+Size2 OpenXRAPI::get_play_space_bounds() const {
+	Size2 ret;
+
+	ERR_FAIL_COND_V(session == XR_NULL_HANDLE, Size2());
+
+	XrExtent2Df extends;
```
Comment (AThousandShips) [inline modules/openxr/openxr_api.cpp:2081]:
```suggestion
	XrExtent2Df extents;
```
Assuming this was meant, "the size", as opposed to "instances extending"

File: modules/openxr/openxr_interface.cpp [hunk 6]
```diff
@@ -690,6 +690,42 @@ bool OpenXRInterface::set_play_area_mode(XRInterface::PlayAreaMode p_mode) {
...
+
+	Vector3 sides[4] = {
+		Vector3(-0.5f, 0.0f, -0.5f),
+		Vector3(0.5f, 0.0f, -0.5f),
+		Vector3(0.5f, 0.0f, 0.5f),
+		Vector3(-0.5f, 0.0f, 0.5f),
+	};
+
+	if (openxr_api != nullptr && openxr_api->is_initialized()) {
+		Size2 extends = openxr_api->get_play_space_bounds();
```
Comment (AThousandShips) [inline modules/openxr/openxr_interface.cpp:706]:
```suggestion
		Size2 extents = openxr_api->get_play_space_bounds();
```
Same

File: modules/openxr/openxr_interface.cpp [hunk 7]
```diff
@@ -690,6 +690,42 @@ bool OpenXRInterface::set_play_area_mode(XRInterface::PlayAreaMode p_mode) {
...
+				// scale it up
+				coord.x *= extends.width;
+				coord.z *= extends.height;
+
+				// now apply our reference
+				Vector3 out = reference_frame.xform(coord);
+				arr.push_back(out);
+			}
+		} else {
+			WARN_PRINT_ONCE("OpenXR: No extends available.");
```
Comment (AThousandShips) [inline modules/openxr/openxr_interface.cpp:722]:
```suggestion
			WARN_PRINT_ONCE("OpenXR: No extents available.");
```

**Review by AThousandShips — APPROVED** [review]
Looks good otherwise for style

File: modules/openxr/openxr_api.cpp (hunk 5 above)
Comment (BastiaanOlij) [reply modules/openxr/openxr_api.cpp]: Yeah, my broken dyslectic English... it even spells it correctly in the type name and I don't see it... :P

**Comment by YuriSizov** [comment]
Thanks!
