### PR TITLE
Fix get_node() and $ autocompletion when using single quotes

### LINKED ISSUE #9056: Allow path auto-completion for single-quote delimited strings in the editor (for node paths and file paths)
**Operating system or device - Godot version:**
Fedora 25 - Godot 3.0 master

**Issue description:**
Auto-Completion of path strings in the editor is limited to double quotes, which require an unnecessary trip to the Shift key. With the addition of the scalar ($) symbol as syntactic sugar, this inconvenience has become much more pronounced.

As far as I know GDScript does not distinguish between single and double quotes for strings (e.g. literals in bash and char data types in C). This is the pull request [that added single quotes](https://github.com/godotengine/godot/pull/823/files), and it seems to handle the two equally.

The discussion from [this solved issue](https://github.com/godotengine/godot/issues/468) makes me think this is just an oversight and should be at least added for consistency.

**Steps to reproduce:**
`get_node('Spatial')` works as intended, but the editor does not provide completion suggestions for the path.

**Link to minimal example project:**
n/a

### PR DESCRIPTION
**Pull request by mhilbrunner**
This fixes autocompletion when using single quotes as discussed in issue #9056.

Additionally, this adds the following new utility methods to `ustring`:

`bool String::is_enclosed_in(string)`
Returns whether the string starts and ends with the given string

`bool String::is_quoted()`
Returns whether the string is enclosed in either single or double quotes

`String String::quote(String quotechar)`
Returns the String enclosed by the given string, double quotes by default

`String String::unquote()`
Removes single or double quotes if the String is enclosed by them

No idea how to expose those to GDScript, though, any pointers?
They clean up the code in some places for the engine source though :)

Fixes  #9056.

### CODE REVIEW

**Comment by mhilbrunner** [comment]
Demo:
Autocomplete

**Comment by karroffel** [comment]
I personally would split it in two commits - one where the `is_quoted` method gets added and one where you make use of that method throughout the codebase. But that's just git-nitpicking. Rest looks fine!

**Comment by mhilbrunner** [comment]
@karoffel: Sure, I can do that. Is there anything on how to expose `is_quoted` to GDScript?

**Comment by mhilbrunner** [comment]
@karroffel : Sure, I can do that. Is there anything on how to expose `is_quoted` to GDScript?

As far as I can see, other string methods seem to appear in `core/variant_call.cpp`, `modules/gdnative/gdnative/string.cpp`, `modules/gdnative/include/gdnative/string.h`, `modules/gdnative/gdnative_api.json` and in various `modules/mono/` files. Is this autogenerated, especially the JSON?

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -4489,7 +4489,13 @@ void TextEdit::_update_completion_candidates() {
 	completion_index = 0;
 	completion_base = s;
 	Vector<float> sim_cache;
+	bool singleQuote = s.begins_with("'");
```
Comment (akien-mga) [inline scene/gui/text_edit.cpp]: Please use `snake_case` for identifiers in Godot's code.

**Comment by mhilbrunner** [comment]
@akien-mga Fixed terrible not-snake-caseyness ;-)

**Comment by mhilbrunner** [comment]
NB: It was decided to leave it as it is and not to expose those new String methods to GDScript/Mono.

**Review by akien-mga — APPROVED** [review]
