### PR TITLE
Fixes Android FileDialog

### LINKED ISSUE #8151: Directories cannot be entered by selecting items from a FileDialog on Android
**Operating system or device - Godot version:**
OS: Android 7.1.1 / LineageOS 14.1
Godot: Godot 2.1.2

**Issue description:**

There is no way for me to choose a folder from the directory listing and make it the current directory. If I want to change the current directory I need to enter the directory name in the top bar.

**Steps to reproduce:**
1) Make a new project with just one scene that is a FileDialog, set to filesystem access and MODE_OPEN_FILE.
2) Go to the export menu for Android and make sure to enable the "Read External Storage" permission.
3) Deploy the project to an Android device.
4) Make sure the app has been given its permissions.
5) Open the app.
6) If the currently displayed directory is empty or only contains the parent directory link, use the top bar to navigate to "/sdcard" for on-device storage.
7) Try to change the current directory to one of the listed directories by choosing it from the menu. I have tried tapping, double tapping, and hitting "Open" after tapping a directory. None of these have changed the current directory.

**Link to minimal example project:**

[filetest.zip](https://github.com/godotengine/godot/files/870390/filetest.zip) (ZIP-exported Godot project)
[filetest-apk.zip](https://github.com/godotengine/godot/files/870391/filetest-apk.zip) (Contains an exported APK)

### LINKED ISSUE #31872: Can't double-tap on Linux touchscreen device
Possibly related: #8151

**Godot version:**
3.1.1 Stable

**OS/device including version:**
Ubuntu 19.04 on a Surface Pro 4
I'm also using a kernel patch from https://github.com/jakeday/linux-surface for more consistent touchscreen support on this device.

**Issue description:**
Can't double-tap to open items in any dialog provided by Godot. I've tested the Project Manager, an "Open a File" dialog in the editor settings, and a FileDialog object running inside a game.
What happened:
I double-tap an entry in a dialog using my touchscreen. On the first tap the item is highlighted, and any further taps have no effect.
What was expected:
I double-tap an entry in a dialog using my touchscreen. On the first tap the entry is highlighted, and on the second tap that entry is loaded/opened.

**Steps to reproduce:**
1. Open the Godot Project Manager
2. Double-tap on a project using the touchscreen
3. The project is highlighted but doesn't open

A key difference between this issue and #8151 is that I don't have any problem tapping "open" to open the file in the dialog, as was reported there.

### PR DESCRIPTION
**Pull request by AlexHolly**
- Go up was not working, simplify was used one time too much
- Added GestureHandler
  - Added doubleTap to recognize open dir
  - Fixed scroll where sometimes the scroll jumped between start and end when pointer was outside or on the edge of the scroll area

closes: https://github.com/godotengine/godot/issues/31872
closes: https://github.com/godotengine/godot/issues/8151

related:
https://github.com/godotengine/godot/pull/25474

### CODE REVIEW

**Review by m4gr3d — COMMENTED** [review]
Looks good! just a few minor changes to address.

**Review by m4gr3d — APPROVED** [review]

File: platform/android/java/lib/src/org/godotengine/godot/input/GodotGestureHandler.java [hunk 1]
```diff
@@ -0,0 +1,106 @@
+/*************************************************************************/
+/*  GodotGestureHandler.java                                               */
```
Comment (akien-mga) [inline platform/android/java/lib/src/org/godotengine/godot/input/GodotGestureHandler.java]: Style issue for the command, it's not properly aligned to the right.

File: platform/android/os_android.h [hunk 2]
```diff
@@ -187,6 +188,8 @@ class OS_Android : public OS_Unix {
 	void process_gyroscope(const Vector3 &p_gyroscope);
 	void process_touch(int p_what, int p_pointer, const Vector<TouchPos> &p_points);
 	void process_hover(int p_type, Point2 p_pos);
+	void process_doubleTap(Point2 p_pos);
```
Comment (akien-mga) [inline platform/android/os_android.h]: I think this should be `process_double_tap`, we use snake case for identifiers (unless this is specifically to match an upstream naming).

**Comment by akien-mga** [comment]
Thanks!
