### PR TITLE
`EditorExportPlugin`: Call `_export_file` for all resource types

### LINKED ISSUE #93823: `EditorExportPlugin`: Skipping a scene in `_customize_scene` gives error message
### Tested versions

v4.3.beta2.official [b75f0485b]

### System information

Godot v4.3.beta2 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 980 Ti (NVIDIA; 31.0.15.3699) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

When skipping a packed scene in the `_customize_scene` function of an `EditorExportPlugin`, the following error message is given:

```
Can't open file from path ''.
```

This error message is not given when the packed scene is skipped in the `_export_file` function.

I suspect this issue was introduced in #90365.

### Steps to reproduce

1. Create an `EditorExportPlugin`
2. Call `skip()` from its `_customize_scene` function
3. Add a scene to the project
4. Export the project or a PCK/ZIP

Alternatively:
1. Open MRP
2. Export the project or a PCK/ZIP

### Minimal reproduction project (MRP)

[Testxport-skip-scene.zip](https://github.com/user-attachments/files/16056797/Testxport-skip-scene.zip)

### LINKED ISSUE #93825: `EditorExportPlugin`: Error when customizing "Keep File" resources
### Tested versions

- Reproducable in v4.3.beta2.official [b75f0485b], v4.2.1.stable.official [b09f793f5], v4.0.stable.official [92bee43ad]

### System information

Godot v4.3.beta2 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 980 Ti (NVIDIA; 31.0.15.3699) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

When customizing resources (returning `true` from `_begin_customize_resources` of an `EditorExportPlugin`), resources that are imported as "Keep File (exported as is)" cause the following sort of error message:

```
Resource file not found:  (expected type: )
Failed loading resource: res://test-icon.svg. Make sure resources have been imported by opening the project in the editor at least once.
editor/export/editor_export_platform.cpp:832 - Condition "res.is_null()" is true. Returning: p_path
```

### Steps to reproduce

1. Create an `EditorExportPlugin`
2. Return `true` from `_begin_customize_resources`
3. Change a `Texture2D`'s import configuration to Import As: Keep File (exported as is)
4. Export the project or a PCK/ZIP

Alternatively:
1. Open MRP
2. Export the project or a PCK/ZIP

### Minimal reproduction project (MRP)

[Testxport-keep-file-error.zip](https://github.com/user-attachments/files/16057522/Testxport-keep-file-error.zip)

### PR DESCRIPTION
**Pull request by allenwp**
- Alternate fix to #67844 that calls `_export_file` for all resource types instead of implementing `skip()` for customize functions.
- This reverts the other previous fix, #90365.
- Fixes #93823.
- Fixes #93825.
- Also fixes an issue that I suspect might exist where progress bars during export were incorrect due to imported files in the project that are configured as "Keep" or "Skip".

If this PR is merged, it supersedes #93820 because that PR is based on the other previous fix that is reverted by this PR.

I'm currently keeping this in draft with separate commits for the purpose of review. I can switch this over to a final pull request and squash the commits into one when others have had a moment to look at the changes. (Or leave some as separate, like the revert for example. Not sure what the preferred practice would be.)

### CODE REVIEW

**Comment by allenwp** [comment]
I've tested this with all the scenarios I can think of... It seems that remapping imported resources in the `_export_file` function works as expected (the same as it works for non-imported resources). It's not a use case that I expect people will want because the file you can remap to won't be imported, so I've added a note about exactly that in the documentation.

Testing is very welcome, of course!

**Comment by AThousandShips** [comment]
Has #90365 really been reverted? Can you link the PR reverting it? It hasn't been marked as reverted or linked in any revert PR

**Comment by allenwp** [comment]
> Has #90365 really been reverted? Can you link the PR reverting it? It hasn't been marked as reverted or linked in any revert PR
> 
> Edit: Or do you mean that this reverts that PR?

Yes, I meant that this PR reverts that other PR. I’ve updated the PR comment to have more clear wording about this.

File: editor/export/editor_export_platform.cpp [hunk 1]
```diff
@@ -1132,33 +1124,97 @@ Error EditorExportPlatform::export_project_files(const Ref<EditorExportPreset> &
...
+				}
+			}
+
+			for (int j = 0; j < export_plugins[i]->extra_files.size(); j++) {
+				err = p_func(p_udata, export_plugins[i]->extra_files[j].path, export_plugins[i]->extra_files[j].data, idx, total, enc_in_filters, enc_ex_filters, key);
+				if (err != OK) {
+					return err;
+				}
+				if (export_plugins[i]->extra_files[j].remap) {
+					do_export = false; // if remap, do not
```
Comment (KoBeWi) [inline editor/export/editor_export_platform.cpp:1177]:
```suggestion
					do_export = false; // If remap, do not.
```

File: editor/export/editor_export_platform.cpp [hunk 2]
```diff
@@ -1282,66 +1311,24 @@ Error EditorExportPlatform::export_project_files(const Ref<EditorExportPreset> &
...
-					if (err != OK) {
-						return err;
-					}
-					if (export_plugins[i]->extra_files[j].remap) {
-						do_export = false; //if remap, do not
-						path_remaps.push_back(path);
-						path_remaps.push_back(export_plugins[i]->extra_files[j].path);
-					}
-				}
+			//just store it as it comes
```
Comment (KoBeWi) [inline editor/export/editor_export_platform.cpp:1314]:
```suggestion
			// Just store it as it comes.
```

File: editor/export/editor_export_platform.cpp [hunk 3]
```diff
@@ -1282,66 +1311,24 @@ Error EditorExportPlatform::export_project_files(const Ref<EditorExportPreset> &
...
 
-				if (export_plugins[i]->skipped) {
-					do_export = false;
-				}
-				export_plugins.write[i]->_clear();
+			// Customization only happens if plugins did not take care of it before
```
Comment (KoBeWi) [inline editor/export/editor_export_platform.cpp:1316]:
```suggestion
			// Customization only happens if plugins did not take care of it before.
```

File: editor/export/editor_export_platform.cpp [hunk 4]
```diff
@@ -1282,66 +1311,24 @@ Error EditorExportPlatform::export_project_files(const Ref<EditorExportPreset> &
...
+			bool force_binary = convert_text_to_binary && (path.get_extension().to_lower() == "tres" || path.get_extension().to_lower() == "tscn");
+			String export_path = _export_customize(path, customize_resources_plugins, customize_scenes_plugins, export_cache, export_base_path, force_binary);
 
-				if (!do_export) {
-					break; //apologies, not exporting
-				}
+			if (export_path != path) {
+				// Add a remap entry
```
Comment (KoBeWi) [inline editor/export/editor_export_platform.cpp:1321]:
```suggestion
				// Add a remap entry.
```

**Review by KoBeWi — APPROVED** [review]
I did some testing and the files are correctly skipped or included. Could be nice to test some plugins that use customization (I don't have one).

**Comment by allenwp** [comment]
I've left the commit that reverts the 4.3 beta 2 approach as a separate commit. Please let me know if I should squash this to be a part of my commit or if it would be better for a maintainer to revert it separate from my PR (not sure what the best practice is for Godot).

**Comment by akien-mga** [comment]
Thanks!
