### PR TITLE
Move initialization check for CanvasMaterial

### LINKED ISSUE #112331: Cannot convert `Sky` `Material`s to `ShaderMaterial`
### Tested versions

v4.5.1.stable.official [f62fdbde1]
v.4.6 dev (9b54928054290b5b320ce6b7b719d97e78d735d3)

### System information

macOS Tahoe 26.0 (25A354)

### Issue description

It is theoretically possible to convert `Sky` materials (like `ProceduralSky`) to `ShaderMaterial` with the right click menu:

Image

However, this currently fails with the following lines printed:

```
ERROR: editor/scene/material_editor_plugin.cpp:633 - Condition "!mat->_is_initialized()" is true. Returning: Ref<Resource>()
Set sky_material
```

In 4.6 dev (current `master`), the error log changes to:

```
  ERROR: editor/scene/material_editor_plugin.cpp:55 - Condition "!p_from->_is_initialized()" is true. Returning: Ref<ShaderMaterial>()
```

It is notably possible to convert `StandardMaterial3D` to `ShaderMaterial`.

### Steps to reproduce

- Create `WorldEnvironment`
- Set "Background" to mode "Sky"
- Create a `Sky`
- Create a `ProdecuralSkyMaterial` (but `PanoramaSkyMaterial` and `PhysicalSkyMaterial` will also work)
- Right click the `ProceduralSkyMaterial`
- Select "Convert to ShaderMaterial"

### Minimal reproduction project (MRP)

Not needed, but just in case, here it is.

[new-game-project-2.zip](https://github.com/user-attachments/files/23293044/new-game-project-2.zip)

### LINKED ISSUE #113647: Converting Panorama Sky Material to a shader Material results in error
### Tested versions

-Reproducible in 4.5.1
-Reproducible in 4.6.dev.custom_build [dec5a373d]

### System information

Godot v4.6.dev (dec5a373d) - Ubuntu 25.10 25.10 on Wayland - X11 display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated Quadro P1000 (nvidia; 580.95.05) - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 threads) - 31.19 GiB memory

### Issue description

When right clicking a panorama sky material in the filesystem and attempting to convert it to a shader material, the following error is given:
```
 ERROR: editor/scene/material_editor_plugin.cpp:55 - Condition "!p_from->_is_initialized()" is true. Returning: Ref<ShaderMaterial>()
  ERROR: editor/docks/filesystem_dock.cpp:1904 - Condition "converted_res.is_null()" is true.
```

### Steps to reproduce

1) Create Panorama Sky Material
2) Right Click In filesystem> Convert to ShaderMaterial

### Minimal reproduction project (MRP)

[testproj.zip](https://github.com/user-attachments/files/23970388/testproj.zip)

### PR DESCRIPTION
**Pull request by AdelynneBrito**
Materials all had a mandatory initialization check despite CanvasMaterials being the only ones that required initialization. This led to issues with material conversion, this PR moves the initialization check so that it only checks CanvasMaterials
- Closes #113647 
- Closes #112331

Supersedes #112458
CC @ColinSORourke

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Makes sense. 

This is only needed by CanvasItemMaterials because they queue up their shader updates using `Material::_mark_initialized()`

File: editor/scene/material_editor_plugin.cpp
Comment (ColinSORourke) [inline editor/scene/material_editor_plugin.cpp]: Is `((Ref<ShaderMaterial>)p_resource)->_is_initialized()` a safe de-reference? I had the check after the null check, to guarantee we would fail on that null check before trying to de-reference a Null passed as p_resource.

**Comment by ColinSORourke** [comment]
@clayjohn I would add "Cherrypick 4.4", @Repiteo did tag the change this is fixing for 4.4 as well

**Comment by clayjohn** [comment]
> @clayjohn I would add "Cherrypick 4.4", @Repiteo did tag the change this is fixing for 4.4 as well

Good thinking!

File: editor/scene/material_editor_plugin.cpp [hunk 1]
```diff
@@ -497,5 +496,6 @@ bool CanvasItemMaterialConversionPlugin::handles(const Ref<Resource> &p_resource
 }
 
 Ref<Resource> CanvasItemMaterialConversionPlugin::convert(const Ref<Resource> &p_resource) const {
+	ERR_FAIL_COND_V(!((Ref<ShaderMaterial>)p_resource)->_is_initialized(), Ref<CanvasItemMaterial>());
```
Comment (AThousandShips) [inline editor/scene/material_editor_plugin.cpp]: This is guaranteed to be called with a `ShaderMaterial`? If not this will segfault, to fix that you can do:
```suggestion
	ERR_FAIL_COND_V(Object::cast_to<ShaderMaterial>(p_resource) && !Object::cast_to<ShaderMaterial>(p_resource)->_is_initialized(), Ref<CanvasItemMaterial>());
```

Comment (AdelynneBrito) [reply editor/scene/material_editor_plugin.cpp]: All the conversion plugins assume the resource is the correct type so I dont believe this is necessary

Comment (AdelynneBrito) [reply editor/scene/material_editor_plugin.cpp]: For example here
image

Comment (AdelynneBrito) [reply editor/scene/material_editor_plugin.cpp]: Although in this case, it should be casted as a CanvasItemMaterial not a shader material

File: editor/scene/material_editor_plugin.cpp [hunk 2]
```diff
@@ -497,5 +496,6 @@ bool CanvasItemMaterialConversionPlugin::handles(const Ref<Resource> &p_resource
 }
 
 Ref<Resource> CanvasItemMaterialConversionPlugin::convert(const Ref<Resource> &p_resource) const {
+	ERR_FAIL_COND_V(!((Ref<CanvasItemMaterial>)p_resource)->_is_initialized(), Ref<CanvasItemMaterial>());
```
Comment (AThousandShips) [inline editor/scene/material_editor_plugin.cpp]: So it's guaranteed to be a valid argument and be of the correct type? I'd make the check safe just in case or this will cause some hard to diagnose errors, like so:
```suggestion
	ERR_FAIL_COND_V(Object::cast_to<CanvasItemMaterial>(p_resource) && !Object::cast_to<CanvasItemMaterial>(p_resource)->_is_initialized(), Ref<CanvasItemMaterial>());
```
Or, if we require it to be `CanvasItemMaterial`
```suggestion
	ERR_FAIL_COND_V(!Object::cast_to<CanvasItemMaterial>(p_resource) || !Object::cast_to<CanvasItemMaterial>(p_resource)->_is_initialized(), Ref<CanvasItemMaterial>());
```

Comment (AdelynneBrito) [reply editor/scene/material_editor_plugin.cpp]: Fair enough, doing this would require dereferencing though since the CanvasItemMaterial is inside a Ref. I'll submit a commit

**Comment by akien-mga** [comment]
Squashed the commits so it's ready to merge.

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.5.2.
