### PR TITLE
Fix TileSet editor workspace breaking

### LINKED ISSUE #52760: Tileset editor breaks if you open and close it enough times (3.4beta regression)
### Godot version

3.4-beta4

### System information

Windows 10

### Issue description

See title. By breaks, I mean that the grid is gone and it's impossible to select tiles or add new ones. And by times, I mean like three.

### Steps to reproduce

1. Make a TileSet
2. Open and close the editor until it breaks

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #52760

### CODE REVIEW

File: editor/plugins/tile_set_editor_plugin.cpp [hunk 1]
```diff
@@ -3336,7 +3336,7 @@ void TileSetEditor::update_workspace_minsize() {
 		}
 	}
 
-	workspace->set_custom_minimum_size(workspace_min_size + WORKSPACE_MARGIN * 2);
+	workspace->call_deferred("set_custom_minimum_size", workspace_min_size + WORKSPACE_MARGIN * 2);
```
Comment (akien-mga) [inline editor/plugins/tile_set_editor_plugin.cpp:3339]: If you know why this fixes it, might be worth adding a comment to document it.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.1.
