### PR TITLE
Several fixes for TouchScreenButton

### LINKED ISSUE #7948: Hidden buttons stay processing input when overlapped by an active button
**Operating system or device - Godot version:**
Godot 2.1.2, Linux XUbuntu 16.04.1

**Issue description:**

When you hide an button and when you show another button overlapping the first, the hidden button takes the input from the second (not hidden).
NOTE: I'm speaking of the TouchScreenButton node

**Steps to reproduce:**
See the test

**Link to minimal example project:**
[TouchButtonBug.zip](https://github.com/godotengine/godot/files/818959/TouchButtonBug.zip)
Just click in the green button, and then click in the area from "Click Here" label of the X button. See the output in editor.

### PR DESCRIPTION
**Pull request by RandomShaper**
Fixes #7948.

### CODE REVIEW

File: scene/2d/screen_button.cpp [hunk 1]
```diff
@@ -135,7 +135,7 @@ void TouchScreenButton::_notification(int p_what) {
 			update();
 
 			if (!get_tree()->is_editor_hint())
-				set_process_input(true);
+				set_process_input(is_visible());
```
Comment (Hinsbart) [inline scene/2d/screen_button.cpp]: I think this should be `is_visible_in_tree()`.
Otherwise it will still keep processing when the button itself is "visible" but implicitly hidden via a hidden parent node.

**Review by 27thLiz — CHANGES_REQUESTED** [review]

File: scene/2d/screen_button.cpp (hunk 1 above)
Comment (RandomShaper) [inline scene/2d/screen_button.cpp]: Good catch, my friend! Now fixed.

**Review by 27thLiz — APPROVED** [review]

**Comment by bojidar-bg** [comment]
@RandomShaper Can you squash the commits together? (I would assume you know how, but drop by on IRC if not)

**Comment by RandomShaper** [comment]
Squashed this and the 2.1 version.
