### PR TITLE
Fix Actions mapped to triggers not using the full range

### LINKED ISSUE #44178: Xbox controller trigger input is wrong.
**Godot version:**
4.0 master
3.2.3 stable

**OS/device including version:**
WIN 10, using Wired Xbox 360 controller.

**Issue description:**
Godot treats trigger input incorrectly.
The for the Right trigger, first half of the trigger pull is "Joystick 2 Up", and the second half if "Joystick 2 Down", but you can only set one of these axes as the input value. This means that the first half of the trigger pull is ignored, and you essentially always have a deadzone of 50%...

Here is an example with a utility that reads what the actual input is. As you can see, Godot thinks the input starts at 50%. Note I have the deadzone set to 0% here (does deadzone even work anway??).
controller_input_trigger_wrong

**Steps to reproduce:**
Make an input action with a joystick input event.
Print or set a label text to `Input.get_action_strength("my_action")`
Play the scene and press the right trigger.
The label will only go above 0 when the trigger is half pressed.

**Minimal reproduction project:**
For 3.2
[XboxTriggersWrong.zip](https://github.com/godotengine/godot/files/5656084/XboxTriggersWrong.zip)

### PR DESCRIPTION
**Pull request by madmiraal**
Currently, `Input::joy_axis()` takes a `struct JoyAxisValue` as a parameter. This `struct` contains the variable `min` which is either set to `0` or `-1` to indicate whether the variable `value` is in the range `0` to `1` or `-1` to `1` respectively. This leads one to assume that triggers with a natural range of `0` to `1` should be setting `min` to `0` to indicate that it's a trigger. However, `min` is not used to signal that the axis is a trigger. Instead, all values are simply converted to a value between `-1` and `1`. The reason is that on the `linuxbsd` platform, there is no way to tell whether an axis is a trigger. If there is an SDL mapping, the SDL mapping can be used to determine which axes are triggers.

This PR removes the misleading `struct JoyAxisValue` and ensures that all platforms calling `Input::joy_axis()` simply send a `float` between `-1` and `1` for all axes. Then, after the SDL mapping identifies the triggers, trigger axes' values are converted to a value between `0` and `1`.

Fixes #44178

### CODE REVIEW

File: core/input/input.cpp [hunk 1]
```diff
@@ -915,40 +915,25 @@ void Input::joy_button(int p_device, JoyButton p_button, bool p_pressed) {
...
-	} else if (ABS(last) > 0.5 && last * p_value.value <= 0) {
-		JoyAxisValue jx;
-		jx.min = p_value.min;
-		jx.value = last > 0 ? 0.1 : -0.1;
-		joy_axis(p_device, p_axis, jx);
-	}
-
-	joy.last_axis[(size_t)p_axis] = p_value.value;
-	float val = p_value.min == 0 ? -1.0f + 2.0f * p_value.value : p_value.value;
+	joy.last_axis[(size_t)p_axis] = p_value;
```
Comment (madmiraal) [inline core/input/input.cpp:929]: I've removed this code (introduced in #6504 and 3bea3256f5def126b2b6d639ed70c4ddc3990344) because it was made redundant when it was properly fixed in #18428.

**Comment by akien-mga** [comment]
The rationale makes sense, and the code refactoring looks good to me.
We need to make sure that it works well on all platforms (CC @bruvzg @Faless).

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
