### PR TITLE
ParticlesGizmo solid box now follows actual visibility_aabb position.

### LINKED ISSUE #16768: Particles AABB is broken
**Godot version: 3 stable**

**Issue description:**
Moving Particles AABB or changing the size does not work as it used to, before stable.

brokenaabb

The grid representing the AABB on the editor is also broken.

**Steps to reproduce:**
Try to move and resize the particles AABB.

### PR DESCRIPTION
**Pull request by JFonS**
ParticlesGizmo had a solid mesh but it didn't move along with the actual visibility AABB, it just stayed centered on the node. I'm not sure this is the best way to modify the vertexes of a mesh, if anyone knows a better one please let me know.

_Bugsquad edit: fixes #16768_

### CODE REVIEW

File: editor/spatial_editor_gizmos.cpp [hunk 1]
```diff
@@ -299,13 +299,24 @@ void EditorSpatialGizmo::add_handles(const Vector<Vector3> &p_handles, bool p_bi
...
 }
 
-void EditorSpatialGizmo::add_solid_box(Ref<Material> &p_material, Vector3 p_size) {
+void EditorSpatialGizmo::add_solid_box(Ref<Material> &p_material, Vector3 p_size, Vector3 p_position) {
 	ERR_FAIL_COND(!spatial_node);
 
 	CubeMesh cubem;
 	cubem.set_size(p_size);
+
+	Array arrays =  cubem.surface_get_arrays(0);
```
Comment (akien-mga) [inline editor/spatial_editor_gizmos.cpp]: There's a code style issue here because you used two spaces instead of one after the `=` operator.

File: editor/spatial_editor_gizmos.cpp [hunk 2]
```diff
@@ -2419,7 +2430,7 @@ void ParticlesGizmo::redraw() {
 
 		gizmo_color.a = 0.1;
 		Ref<Material> solid_material = create_material("particles_solid_material", gizmo_color);
-		add_solid_box(solid_material, aabb.get_size());
+		add_solid_box(solid_material, aabb.get_size(), aabb.get_position() + aabb.get_size()/2.0);
```
Comment (akien-mga) [inline editor/spatial_editor_gizmos.cpp]: Style issue here as there should be a space on each side of the `/` operator. See http://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html

Comment (JFonS) [reply editor/spatial_editor_gizmos.cpp]: Sorry for the inconvinience, it should be ok now. I have set up the formatting git hook.

**Comment by akien-mga** [comment]
Looks good, thanks. Would you be able to squash the two commits together? See [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase) for instructions.

**Comment by JFonS** [comment]
On it :)
