### PR TITLE
EditorInterface: Add `get_open_scene_roots` to retrieve all opened scenes root nodes

### LINKED ISSUE #10895: Add a method to retrieve all opened scenes' root nodes instead of scene paths
### Describe the project you are working on

RTX rendering for Godot 4.X

### Describe the problem or limitation you are having in your project

I can't believe this was issued at 2020 and still there's no fix for it : https://github.com/godotengine/godot-proposals/issues/1314
Issue is when you need to apply changes to opened scenes you can't access them directly, Only way is to save all and use `reload_scene_from_path` which leads to crash on object unloading randomly which is another bug that been addressed multiple times and still there's no fix for it.

More importantly if a scene be temporary and not save on disk it returns empty string
"scene1.tscn"
"scene2.tscn"
""
""
"scene3.tscn"

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

EditorInterface::get_singleton()->get_open_scenes() must returns a array or vector of Node* as roots of opened scenes.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The fix to this issue is very easy I did it on my own Godot version but I need it to be globalized because I'm working on a Extension that others can use.
It can be done in two ways, Changing [current function](https://github.com/akien-mga/godot/blob/a1b081f45c3330fb7c84d49c1c57bb631800eb56/editor/editor_interface.cpp#L430) to 
```CPP
	PackedStringArray get_open_scenes() const;
	Array get_open_scenes_roots() const; // Added This
	Node *get_edited_scene_root() const;
```

```CPP
Array EditorInterface::get_open_scenes_roots() const {
	Array ret;
	Vector<EditorData::EditedScene> scenes = EditorNode::get_editor_data().get_edited_scenes();

	int scns_amount = scenes.size();
	for (int idx_scn = 0; idx_scn < scns_amount; idx_scn++) {
		if (scenes[idx_scn].root == nullptr) {
			continue;
		}
		ret.append(scenes[idx_scn].root);
	}
	return ret;
}
```
```CPP
ClassDB::bind_method(D_METHOD("get_open_scenes_roots"),&EditorInterface::get_open_scenes_roots);
```
```XML
		<method name="get_open_scenes_roots" qualifiers="const">
			<return type="Array" />
			<description>
				Returns an [Array] with the root nodes of the currently opened scenes.
			</description>
		</method>
```

or keep current and rename it to something like `get_open_scenes_files` and use get_open_scenes to return roots.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's easy to fix but Not in Script.

### Is there a reason why this should be core and not an add-on in the asset library?

Yes? This is a very important feature yet easy to fix.

### PR DESCRIPTION
**Pull request by CycloneRing**
Added a single API `get_open_scenes_roots ` to `EditorInterface` to retrieve all opened scenes root nodes instead of scene file paths.

- Changes applied to **editor_interface.h** and **editor_interface.cpp**
- Documentation added to **EditorInterface.xml**

Credit : [TheAenema](https://github.com/TheAenema)
*Bugsquad edit:* Closes https://github.com/godotengine/godot-proposals/issues/10895

### CODE REVIEW

**Comment by Chaosus** [comment]
Thanks for contribution. Please squash the commits as it's required by our pipeline (see https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html).

**Comment by CycloneRing** [comment]
@Chaosus Done, I'm not sure if I did it correctly, This was my first time :D Let me know if ther's still a problem.

**Comment by CycloneRing** [comment]
Can we get this change merged? :)

**Comment by akien-mga** [comment]
> Sorry to ping, Can we get this PR merged?

We're currently in feature freeze for Godot 4.4, so we're not merging any new feature for the time being, even minor ones like this.

This still needs to be approved by contributors familiar with the EditorInterface API (cc @KoBeWi @passivestar ) and then it should be mergeable for 4.5.

**Comment by KoBeWi** [comment]
What's the use-case for this method? The implementation is fine (though it should return `TypedArray<Node>`), but there is no proposal.

**Comment by passivestar** [comment]
Seems fine as far as API goes to have this in addition to the already existing `get_edited_scene_root()` method.

It's hard for me to understand the practical use-case though because I'm not familiar with the framework that you mentioned. Why does it need to hot-reload scenes in inactive tabs? Wouldn't it be better to do it lazily when a scene becomes active (i.e there's a `EditorPlugin.scene_changed` signal)?

**Comment by CycloneRing** [comment]
> Seems fine as far as API goes to have this in addition to the already existing `get_edited_scene_root()` method.
> 
> It's hard for me to understand the practical use-case though because I'm not familiar with the framework that you mentioned. Why does it need to hot-reload scenes in inactive tabs? Wouldn't it be better to do it lazily when a scene becomes active (i.e there's a `EditorPlugin.scene_changed` signal)?

@passivestar I'm not the developer so i can't explain in detail but since the project brings incredible c++ scripting and hot-reloading, it require to update C++ nested nodes in opened scenes if it doesn't it lead to a crash as those pointers are gone after hot reload.

This is video from their channel showing hot-reloading:
https://github.com/user-attachments/assets/5522afe3-309e-47cf-9800-1f566bf2db35

File: editor/editor_interface.h [hunk 1]
```diff
@@ -162,6 +162,7 @@ class EditorInterface : public Object {
 	void reload_scene_from_path(const String &scene_path);
 
 	PackedStringArray get_open_scenes() const;
+	Array get_open_scenes_roots() const;
```
Comment (KoBeWi) [inline editor/editor_interface.h:165]: TypedArray should be preferred when type is known.
```suggestion
	TypedArray<Node> get_open_scenes_roots() const;
```

**Review by passivestar — APPROVED** [review]
Tested, works as expected

**Comment by CycloneRing** [comment]
@KoBeWi @akien-mga Can we get this PR merged now? :)

**Comment by akien-mga** [comment]
It needs a rebase to pass CI, the macOS builds failed (the logs aren't available anymore so I assume this was a temporary CI fluke and not a bug in this PR).

@KoBeWi's suggestion to use `TypedArray<Node>` as return value is also good and should be included.

**Comment by CycloneRing** [comment]
> It needs a rebase to pass CI, the macOS builds failed (the logs aren't available anymore so I assume this was a temporary CI fluke and not a bug in this PR).
> 
> @KoBeWi's suggestion to use `TypedArray<Node>` as return value is also good and should be included.

Yes, It first passed all checks and bugged out on second commit I did. Other forks that merged this change have successful build on all platforms. I agree with `TypedArray<Node>` as well, Btw, Should I do anything?

**Comment by akien-mga** [comment]
Well as I mentioned:
- You should rebase the PR on current `master`
- You should amend the commit to use `TypedArray<Node>`

But I guess I'll do it myself and tweak the commit message for clarity along the way.

**Review by akien-mga — APPROVED** [review]

File: editor/editor_interface.h [hunk 2]
```diff
@@ -171,6 +171,7 @@ class EditorInterface : public Object {
 	void reload_scene_from_path(const String &scene_path);
 
 	PackedStringArray get_open_scenes() const;
+	TypedArray<Node> get_open_scenes_roots() const;
```
Comment (AThousandShips) [inline editor/editor_interface.h:174]:
```suggestion
	TypedArray<Node> get_open_scene_roots() const;
```
The noun here is singular in English (think "dog catchers")

**Review by AThousandShips — APPROVED** [review]

**Comment by CycloneRing** [comment]
> Well as I mentioned:
> 
>     * You should rebase the PR on current `master`
> 
>     * You should amend the commit to use `TypedArray<Node>`
> 
> 
> But I guess I'll do it myself and tweak the commit message for clarity along the way.

Awesome, looks like everything works as expected. I tested the binaries from action and they all working.

**Comment by CycloneRing** [comment]
@akien-mga @AThousandShips Can this PR be merged? Everything looks good and they just added compatibility for new Godot release and I want to migrate from 4.3 soon as possible...
image

**Comment by akien-mga** [comment]
Please have some patience, we just released 4.4-stable and we're focusing on merging bug fixes right now and preparing a 4.4.1 bugfix release.
This will be merged soon, it's slated for 4.5-dev1. If you want to use it, you can merge it in your own local branch, you'd need to do compile from source anyway once it's merged.

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
