### PR TITLE
Strip edges on node rename in SceneTreeDock

### LINKED ISSUE #41992: Disallow leading or trailing spaces for node names. (Trim string)
**Godot version:**
3.2.2 Default 64bit (GDScript)

**OS/device including version:**
Windows 10 - GTX 2070 Super - GLES3

**Issue description:**
Currently it is possible to have e.g. trailing spaces for a node name. e.g. for "Camera".
It's not really a bug, but can cause problems. I wasted time to find it. It's not easy to find hidden characters like spaces.

**Steps to reproduce:**
Just rename a node and leave spaces on the name like: "`Camera `" or "`  Spatial   `".
And now try to use `$Camera` or using `get_node(...)`. You'll get a null reference.
Yes you can use e.g. `$"Camera "` but anyway. The string should be trimmed on enter / change.

### PR DESCRIPTION
**Pull request by Leleat**
Closes #41992.

### CODE REVIEW

File: editor/scene_tree_editor.cpp [hunk 1]
```diff
@@ -777,6 +777,8 @@ void SceneTreeEditor::_renamed() {
 		return;
 	}
 
+	new_name = new_name.strip_edges();
```
Comment (Calinou) [inline editor/scene_tree_editor.cpp:780]:
```suggestion
    // Trim leading/trailing whitespace to prevent node names from containing accidental whitespace, which would make it impossible to get the node via `get_node()`.
	new_name = new_name.strip_edges();
```

Comment (Leleat) [reply editor/scene_tree_editor.cpp:781]: Thanks.

Comment (Leleat) [reply editor/scene_tree_editor.cpp:781]: I used githubs "Commit suggestion" button, which created a new commit. I think I need to "squash" these commits now, right? I'll look into it.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
