### PR TITLE
Use temp dirs instead of cache dirs for export

### LINKED ISSUE #95897: Cannot export project when $HOME is readonly
### Tested versions

- Tested on Godot 4.3-stable [77dcf97d8]

### System information

Godot v4.3.stable - NixOS #1-NixOS SMP PREEMPT_DYNAMIC Wed Aug 14 11:59:04 UTC 2024 - Wayland - Vulkan (Forward+) - integrated Intel(R) HD Graphics 4600 (HSW GT2) - Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz (4 Threads)

### Issue description

When $HOME is readonly or otherwise invalid (e.g /var/empty, /dev/null) exporting a project fails.
Command ran `godot --headless --export-debug "Linux"`

This matters for CI builds where build users may set $HOME to /var/empty to avoid using the root user.

### Steps to reproduce

Create the default Linux export template
Set $HOME to a readonly/invalid path (/var/empty, /dev/null both tested to fail)
Execute `godot --headless --export-debug "Linux"`

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by ArchercatNEO**
Fixes #95897
During CI scenarios $HOME may be set to an invalid value (such as `/var/empty`).
Using temp dirs fits better with godot's usage of these paths and is independent from the user's $HOME.

### CODE REVIEW

**Review by m4gr3d — APPROVED** [review]
The Android section looks good.

**Comment by adamscott** [comment]
Happy to see my feature getting some use!

File: platform/web/export/export_plugin.cpp [hunk 1]
```diff
@@ -817,7 +817,7 @@ Error EditorExportPlatformWeb::run(const Ref<EditorExportPreset> &p_preset, int
 }
 
 Error EditorExportPlatformWeb::_export_project(const Ref<EditorExportPreset> &p_preset, int p_debug_flags) {
-	const String dest = EditorPaths::get_singleton()->get_cache_dir().path_join("web");
+	const String dest = EditorPaths::get_singleton()->get_temp_dir().path_join("web");
```
Comment (Faless) [inline platform/web/export/export_plugin.cpp:820]: `platform/web/export/editor_http_server.cpp` also needs updating to preserve the "Run in browser" functionality.

**Comment by Summersay415** [comment]
But wait, temp dir can be mounted in RAM, so if project is too big it will not fit in memory. But this is an edge case, so overall it's OK?

**Comment by ArchercatNEO** [comment]
How large would a project actually have to be to reach this limit? With 16GB ram and saying we have about 8GB usable ram I believe this is still quite a lot of usable space. Very large 3D projects that might actually use all this ram but I think would be very painful to develop on a low end system and would probably already have higher usable ram counts.

If this is a bigger problem than expected and the ram limit is actually significant I wouldn’t recommend reverting back to cache dirs because that would break homeless exports again, instead I’d recommend using the project’s `.godot` dir because that is independent of the home.

Of course that is only if the ram limit is a problem and there is not some trivial way to reduce the memory footprint during export.
