### PR TITLE
Fix `TextEdit.get_rect_at_line_column returning` negative pos even though cursor is in viewable area of the control

### LINKED ISSUE #81349: `TextEdit.get_rect_at_line_column` returns negative pos even though cursor is in viewable area of the control
### Godot version

3.5.2, 4.1.1

### System information

Godot v3.5.2.stable and v4.1.1.stable - Ubuntu 20.04.6 LTS (Focal Fossa) - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 970 (nvidia; 525.125.06) - Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz (16 Threads)

### Issue description

* What does not work: accurately returning the x and y pixel positions of the active cursor in TextEdit
* What did you expect: return position of cursor while it is inside of the viewable area of the control

Note: as `get_pos_at_line_column` calls `get_rect_at_line_column`, it is affected as well.

**In Godot 3:**  
Always incorrect for last column.

**In Godot 4:**  
Always incorrect if the line has only 0 or 1 characters.  
And starting with second line when there's exactly 1 character.

Pinging @YuriSizov and @Paulb23, as they worked on the Godot 4 version.
* https://github.com/godotengine/godot/pull/55102
* https://github.com/godotengine/godot/pull/60438

### Steps to reproduce

Read pixel rect/pos of cursor while cursor is in last column of line

Currently, the result in Godot **3.5.2** is:

[Godot 3](https://github.com/godotengine/godot/assets/6639237/b12e6d8a-5bbc-4e98-b4bc-bc8fd501176b)

Recorded while using `get_pos_at_line_column`, but MRP uses `get_rect_at_line_column`

In Godot **4.1.1**:

[textedit-bug_godot-4.webm](https://github.com/godotengine/godot/assets/6639237/6883919c-69b1-4257-b78b-bbd5f08cf3dd)

### Minimal reproduction project

Godot 3.5.2

[textedit-bug.tar.gz](https://github.com/godotengine/godot/files/12525602/textedit-bug.tar.gz)

for project migration to Godot 4, change line 24 to `l.text = var_to_str(pos)`. Beware: terrible performance in Godot 4

### PR DESCRIPTION
**Pull request by MJacred**
Sister PR of https://github.com/godotengine/godot/pull/81352 (for Godot 3.x)

When both are merged, https://github.com/godotengine/godot/issues/81349 can be closed

_Production edit: Fixes https://github.com/godotengine/godot/issues/81349_

Before fix:

[textedit-bug_godot-4.webm](https://github.com/godotengine/godot/assets/6639237/6883919c-69b1-4257-b78b-bbd5f08cf3dd)

After fix:

[after.webm](https://github.com/godotengine/godot/assets/6639237/6dffab26-793e-45f1-a7a5-1cfad7288906)

### CODE REVIEW

**Comment by MJacred** [comment]
@AThousandShips: done, ready for review

**Review by Paulb23 — APPROVED** [review]
Changes look okay to me, would be good to add a unit test to capture this behaviour

**Comment by MJacred** [comment]
I would do it, but this does not make any sense in my head: if you drag the mouse from column 1 to 7 you should get `his is`. But apparently you even land in line 1, not 0... Similar confusion with other uses of `get_pos_at_line_column` in test_text_edit.h

```c++
text_edit->set_text("this is some text\nfor selection");
text_edit->grab_focus();
MessageQueue::get_singleton()->flush();

SEND_GUI_MOUSE_BUTTON_EVENT(text_edit->get_pos_at_line_column(0, 1), MouseButton::LEFT, MouseButtonMask::LEFT, Key::NONE);
SEND_GUI_MOUSE_MOTION_EVENT(text_edit->get_pos_at_line_column(0, 7), MouseButtonMask::LEFT, Key::NONE);
CHECK(text_edit->has_selection());
CHECK(text_edit->get_selected_text() == "for s");
```

File: tests/scene/test_text_edit.h [hunk 1]
```diff
@@ -3241,6 +3241,15 @@ TEST_CASE("[SceneTree][TextEdit] mouse") {
...
 
 	text_edit->set_size(Size2(800, 200));
+
+	CHECK(text_edit->get_rect_at_line_column(0, 0).get_position() == Point2i(0, 0));
+
+	text_edit->set_line(0, "A");
+	MessageQueue::get_singleton()->flush();
+	CHECK(text_edit->get_rect_at_line_column(0, 1).get_position().x > 0);
+
+	text_edit->clear(); // Necessary, else the following test cases fail.
```
Comment (AThousandShips) [inline tests/scene/test_text_edit.h:3251]:
```suggestion
	text_edit->clear(); // Necessary, otherwise the following test cases fail.
```

Comment (MJacred) [reply tests/scene/test_text_edit.h]: Done!

**Review by AThousandShips — APPROVED** [review]
Style looks good!

File: scene/gui/text_edit.cpp [hunk 2]
```diff
@@ -4348,6 +4349,11 @@ Rect2i TextEdit::get_rect_at_line_column(int p_line, int p_column) const {
 	ERR_FAIL_COND_V(p_column < 0, Rect2i(-1, -1, 0, 0));
 	ERR_FAIL_COND_V(p_column > text[p_line].length(), Rect2i(-1, -1, 0, 0));
 
+	if (text.size() == 1 && text[0].length() == 0) {
+		// The TextEdit is empty.
+		return Rect2i(0, 0, 0, 0);
```
Comment (AThousandShips) [inline scene/gui/text_edit.cpp:4354]:
```suggestion
		return Rect2i();
```

Comment (MJacred) [reply scene/gui/text_edit.cpp]: Dpme

**Review by Paulb23 — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
