### PR TITLE
Make gizmo plugin handle `SpriteBase3D` instead of `Sprite3D`

### LINKED ISSUE #82873: Cannot select an AnimatedSprite3D node by clicking on it in the scene view
### Godot version

Godot v4.1.1.stable.mono

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3742) - 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz (12 Threads)

### Issue description

An AnimatedSprite3D node (with a SpriteFrames) cannot be selected by clicking on its sprite in the scene view.

It can be selected by clicking on it in the node hierarchy. This issue is essentially about usability/QOL.
The use case would be, for example, making a 2.5D-style game where a lot of AnimatedSprite3Ds are its main actors and props.

It is still possible to select a Sprite3D node by clicking on it in the scene view, which is why I'm reporting this as a bug.

### Steps to reproduce

In the reproduction project,

1. Open the scene named node_3d.tscn => It should have an AnimatedSprite3D visible at the origin.
2. In the scene view, click on the sprite => The node is not selected.

### Minimal reproduction project

[AnimatedSprite3DBug.zip](https://github.com/godotengine/godot/files/12821341/AnimatedSprite3DBug.zip)

### PR DESCRIPTION
**Pull request by kleonc**
Fixes #82873. There was no gizmo plugin handling `AnimatedSprite3D`... :upside_down_face:

Replaces `Sprite3DGizmoPlugin` with `SpriteBase3DGizmoPlugin` (rename + changed handled type from `Sprite3D` to `SpriteBase3D`).

Removes redundant `AnimatedSprite3D::centered` member which was always `false`. It was used only in `AnimatedSprite3D::get_item_rect()` where it was incorrectly checked instead of `SpriteBase3D::centered` (which is `private` and hence needs to be checked with `SpriteBase3D::is_centered()`). This buggy check wasn't affecting anything before this PR as `AnimatedSprite3D::get_item_rect()` is called only within `SpriteBase3D::generate_triangle_mesh()` which was never called for an `AnimatedSprite3D` as there was no gizmo plugin handling it. With a gizmo plugin handling `AnimatedSprite3D` added it was making it selectable by the non-centered area regardless of the `centered` property value.

### CODE REVIEW

File: editor/plugins/gizmos/sprite_base_3d_gizmo_plugin.cpp [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /**************************************************************************/
-/*  sprite_3d_gizmo_plugin.cpp                                            */
+/*  sprite_base_3d_gizmo_plugin.cpp                                            */
 /**************************************************************************/
```
Comment (akien-mga) [inline editor/plugins/gizmos/sprite_base_3d_gizmo_plugin.cpp:3]:
```suggestion
/*  sprite_base_3d_gizmo_plugin.cpp                                       */
/**************************************************************************/
```

Comment (akien-mga) [reply editor/plugins/gizmos/sprite_base_3d_gizmo_plugin.cpp:3]: Same in header.

**Review by akien-mga — APPROVED** [review]
I think the rename wasn't absolutely necessary, but shouldn't hurt either. It's technically more accurate.

**Comment by kleonc** [comment]
> I think the rename wasn't absolutely necessary, but shouldn't hurt either. It's technically more accurate.

Initially I've changed only the handled type but seeing other gizmo plugins for base classes like `CollisionObject3DGizmoPlugin` or `CollisionShape3DGizmoPlugin` the rename made more sense / seemed more consistent.

**Comment by akien-mga** [comment]
Thanks!

**Comment by lorenzokerbrat** [comment]
Thanks @kleonc ! That was fast.
