### PR TITLE
Fix new projects always being created with OpenGL

### LINKED ISSUE #54488: New Project uses OpenGL3 driver when Vulkan-Clustered is selected
### Godot version

a57de3b81849a4cb5eadcccb837d787c7744ab8b

### System information

Windows 10, GTX1060, 496.49

### Issue description

Attempting to create a run a new project will freeze the engine. Seems like it's somehow related to sky rendering. The existed projects are run but without sky and with lots of console errors.

```
Godot Engine v4.0.dev.custom_build.a57de3b81 - https://godotengine.org
Vulkan API 1.2.189 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1060 6GB

Project is missing: C:/GD4/project.godot
Editing project: C:/GD4/BrandNewProject (C:::GD4::BrandNewProject)
Godot Engine v4.0.dev.custom_build.a57de3b81 - https://godotengine.org
USER ERROR: Property not found: rendering/quality/2d/use_nvidia_rect_flicker_workaround
   at: ProjectSettings::_get (core\config\project_settings.cpp:246) - Property not found: rendering/quality/2d/use_nvidia_rect_flicker_workaround
USER ERROR: Property not found: rendering/quality/shading/force_lambert_over_burley
   at: ProjectSettings::_get (core\config\project_settings.cpp:246) - Property not found: rendering/quality/shading/force_lambert_over_burley
USER ERROR: Property not found: rendering/quality/shading/force_blinn_over_ggx
   at: ProjectSettings::_get (core\config\project_settings.cpp:246) - Property not found: rendering/quality/shading/force_blinn_over_ggx
OpenGL Renderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
USER ERROR: Condition "!props.has(p_prop)" is true.
   at: ProjectSettings::set_custom_property_info (core\config\project_settings.cpp:977) - Condition "!props.has(p_prop)" is true.
USER ERROR: Condition "!props.has(p_prop)" is true.
   at: ProjectSettings::set_custom_property_info (core\config\project_settings.cpp:977) - Condition "!props.has(p_prop)" is true.
USER ERROR: Property not found: rendering/quality/2d/use_software_skinning
   at: ProjectSettings::_get (core\config\project_settings.cpp:246) - Property not found: rendering/quality/2d/use_software_skinning
USER ERROR: Property not found: rendering/quality/2d/ninepatch_mode
   at: ProjectSettings::_get (core\config\project_settings.cpp:246) - Property not found: rendering/quality/2d/ninepatch_mode

USER ERROR: Condition "!version" is true. Returning: false
   at: ShaderGLES3::bind (drivers\gles3\shader_gles3.cpp:90) - Condition "!version" is true. Returning: false
USER ERROR: Condition "!version" is true. Returning: false
   at: ShaderGLES3::bind (drivers\gles3\shader_gles3.cpp:90) - Condition "!version" is true. Returning: false
USER ERROR: Condition "!version" is true. Returning: false
   at: ShaderGLES3::bind (drivers\gles3\shader_gles3.cpp:90) - Condition "!version" is true. Returning: false
USER ERROR: Condition "!version" is true. Returning: false
   at: ShaderGLES3::bind (drivers\gles3\shader_gles3.cpp:90) - Condition "!version" is true. Returning: false
USER ERROR: Condition "!version" is true. Returning: false
   at: ShaderGLES3::bind (drivers\gles3\shader_gles3.cpp:90) - Condition "!version" is true. Returning: false
USER ERROR: Condition "!version" is true. Returning: false
   at: ShaderGLES3::bind (drivers\gles3\shader_gles3.cpp:90) - Condition "!version" is true. Returning: false
USER ERROR: Condition "!version" is true. Returning: false
   at: ShaderGLES3::bind (drivers\gles3\shader_gles3.cpp:90) - Condition "!version" is true. Returning: false
USER ERROR: Condition "!version" is true. Returning: false
   at: ShaderGLES3::bind (drivers\gles3\shader_gles3.cpp:90) - Condition "!version" is true. Returning: false
USER ERROR: Condition "!version" is true. Returning: false
   at: ShaderGLES3::bind (drivers\gles3\shader_gles3.cpp:90) - Condition "!version" is true. Returning: false
USER ERROR: Condition "!version" is true. Returning: false
   at: ShaderGLES3::bind (drivers\gles3\shader_gles3.cpp:90) - Condition "!version" is true. Returning: false
USER ERROR: Condition "!version" is true. Returning: false
   at: ShaderGLES3::bind (drivers\gles3\shader_gles3.cpp:90) - Condition "!version" is true. Returning: false
USER ERROR: Condition "!version" is true. Returning: false
   at: ShaderGLES3::bind (drivers\gles3\shader_gles3.cpp:90) - Condition "!version" is true. Returning: false
USER ERROR: Condition "!version" is true. Returning: false
   at: ShaderGLES3::bind (drivers\gles3\shader_gles3.cpp:90) - Condition "!version" is true. Returning: false
USER ERROR: Condition "!version" is true. Returning: false
   at: ShaderGLES3::bind (drivers\gles3\shader_gles3.cpp:90) - Condition "!version" is true. Returning: false
USER ERROR: Condition "!version" is true. Returning: false
   at: ShaderGLES3::bind (drivers\gles3\shader_gles3.cpp:90) - Condition "!version" is true. Returning: false
USER ERROR: Condition "!version" is true. Returning: false
   at: ShaderGLES3::bind (drivers\gles3\shader_gles3.cpp:90) - Condition "!version" is true. Returning: false
USER ERROR: Condition "!version" is true. Returning: false
   at: ShaderGLES3::bind (drivers\gles3\shader_gles3.cpp:90) - Condition "!version" is true. Returning: false
USER ERROR: Condition "!version" is true. Returning: false
   at: ShaderGLES3::bind (drivers\gles3\shader_gles3.cpp:90) - Condition "!version" is true. Returning: false
USER ERROR: Condition "!version" is true. Returning: false
   at: ShaderGLES3::bind (drivers\gles3\shader_gles3.cpp:90) - Condition "!version" is true. Returning: false
USER ERROR: Condition "!version" is true. Returning: false
   at: ShaderGLES3::bind (drivers\gles3\shader_gles3.cpp:90) - Condition "!version" is true. Returning: false
USER ERROR: Condition "!version" is true. Returning: false
   at: ShaderGLES3::bind (drivers\gles3\shader_gles3.cpp:90) - Condition "!version" is true. Returning: false
1
2 // NOTE: Shader automatically converted from Godot Engine 4.0.dev's ProceduralSkyMaterial.
3
4 shader_type sky;
5
6 uniform vec4 sky_top_color : hint_color = vec4(0.35, 0.46, 0.71, 1.0);
7 uniform vec4 sky_horizon_color : hint_color = vec4(0.55, 0.69, 0.81, 1.0);
8 uniform float sky_curve : hint_range(0, 1) = 0.09;
9 uniform float sky_energy = 1.0;
10 uniform vec4 ground_bottom_color : hint_color = vec4(0.12, 0.12, 0.13, 1.0);
11 uniform vec4 ground_horizon_color : hint_color = vec4(0.37, 0.33, 0.31, 1.0);
12 uniform float ground_curve : hint_range(0, 1) = 0.02;
13 uniform float ground_energy = 1.0;
14 uniform float sun_angle_max = 1.74;
15 uniform float sun_curve : hint_range(0, 1) = 0.05;
16
17 void sky() {
18      float v_angle = acos(clamp(EYEDIR.y, -1.0, 1.0));
19      float c = (1.0 - v_angle / (PI * 0.5));
20      vec3 sky = mix(sky_horizon_color.rgb, sky_top_color.rgb, clamp(1.0 - pow(1.0 - c, 1.0 / sky_curve), 0.0, 1.0));
21      sky *= sky_energy;
22
23      if (LIGHT0_ENABLED) {
24              float sun_angle = acos(dot(LIGHT0_DIRECTION, EYEDIR));
25              if (sun_angle < LIGHT0_SIZE) {
26                      sky = LIGHT0_COLOR * LIGHT0_ENERGY;
27              } else if (sun_angle < sun_angle_max) {
28                      float c2 = (sun_angle - LIGHT0_SIZE) / (sun_angle_max - LIGHT0_SIZE);
29                      sky = mix(LIGHT0_COLOR * LIGHT0_ENERGY, sky, clamp(1.0 - pow(1.0 - c2, 1.0 / sun_curve), 0.0, 1.0));
30              }
31      }
32
33      if (LIGHT1_ENABLED) {
34              float sun_angle = acos(dot(LIGHT1_DIRECTION, EYEDIR));
35              if (sun_angle < LIGHT1_SIZE) {
36                      sky = LIGHT1_COLOR * LIGHT1_ENERGY;
37              } else if (sun_angle < sun_angle_max) {
38                      float c2 = (sun_angle - LIGHT1_SIZE) / (sun_angle_max - LIGHT1_SIZE);
39                      sky = mix(LIGHT1_COLOR * LIGHT1_ENERGY, sky, clamp(1.0 - pow(1.0 - c2, 1.0 / sun_curve), 0.0, 1.0));
40              }
41      }
42
43      if (LIGHT2_ENABLED) {
44              float sun_angle = acos(dot(LIGHT2_DIRECTION, EYEDIR));
45              if (sun_angle < LIGHT2_SIZE) {
46                      sky = LIGHT2_COLOR * LIGHT2_ENERGY;
47              } else if (sun_angle < sun_angle_max) {
48                      float c2 = (sun_angle - LIGHT2_SIZE) / (sun_angle_max - LIGHT2_SIZE);
49                      sky = mix(LIGHT2_COLOR * LIGHT2_ENERGY, sky, clamp(1.0 - pow(1.0 - c2, 1.0 / sun_curve), 0.0, 1.0));
50              }
51      }
52
53      if (LIGHT3_ENABLED) {
54              float sun_angle = acos(dot(LIGHT3_DIRECTION, EYEDIR));
55              if (sun_angle < LIGHT3_SIZE) {
56                      sky = LIGHT3_COLOR * LIGHT3_ENERGY;
57              } else if (sun_angle < sun_angle_max) {
58                      float c2 = (sun_angle - LIGHT3_SIZE) / (sun_angle_max - LIGHT3_SIZE);
59                      sky = mix(LIGHT3_COLOR * LIGHT3_ENERGY, sky, clamp(1.0 - pow(1.0 - c2, 1.0 / sun_curve), 0.0, 1.0));
60              }
61      }
62
63      c = (v_angle - (PI * 0.5)) / (PI * 0.5);
64      vec3 ground = mix(ground_horizon_color.rgb, ground_bottom_color.rgb, clamp(1.0 - pow(1.0 - c, 1.0 / ground_curve), 0.0, 1.0));
65      ground *= ground_energy;
66
67      COLOR = mix(ground, sky, step(0.0, EYEDIR.y));
68 }
69
USER ERROR: Unknown identifier in expression: EYEDIR
   at: (null) (:18) - Unknown identifier in expression: EYEDIR
```

### Steps to reproduce

Create and run a new project.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Calinou**
Only Vulkan is fully implemented for now, so OpenGL isn't available in the project manager yet.

This also makes the rendering driver checks use lowercase names everywhere for consistency.

This closes https://github.com/godotengine/godot/issues/54488.

### CODE REVIEW

File: platform/android/export/export_plugin.cpp [hunk 1]
```diff
@@ -1612,11 +1612,11 @@ Vector<String> EditorExportPlatformAndroid::get_enabled_abis(const Ref<EditorExp
 
 void EditorExportPlatformAndroid::get_preset_features(const Ref<EditorExportPreset> &p_preset, List<String> *r_features) {
 	String driver = ProjectSettings::get_singleton()->get("rendering/driver/driver_name");
-	if (driver == "OpenGL3") {
+	if (driver == "opengl3") {
```
Comment (akien-mga) [inline platform/android/export/export_plugin.cpp:1615]: Shouldn't we use `etc2` for GLES3? This was likely done this way when it was GLES2 but this changed since then.

Comment (akien-mga) [reply platform/android/export/export_plugin.cpp:1615]: Can be looked into in another PR though, all export preset features need to be rechecked.

**Review by akien-mga — APPROVED** [review]

File: platform/android/export/export_plugin.cpp (hunk 1 above)
Comment (Calinou) [reply platform/android/export/export_plugin.cpp:1615]: Indeed, this may be better left to a future PR.

I think we'll be able to remove ETC1 support entirely and focus on ETC2 as a baseline, which will simplify things a lot. That is, if no blocker bugs are found in mobile/web support of ETC2-compressed textures…

**Comment by akien-mga** [comment]
Thanks!
