### PR TITLE
HTML5: Make locale string match other platforms

### LINKED ISSUE #63029: HTML5: `OS.get_locale()` uses hyphens instead of underscores
### Godot version

 v3.5.beta.custom_build [6d9cbcb05faabd03d0eb95dad39503cb2d5a9938]

### System information

Windows 10, Chrome 103

### Issue description

According to the docs, `OS.get_locale()` should return a string of the form `language_Script_COUNTRY_VARIANT@extra` (notice the underscores). This isn't the case in HTML5 exports, where it returns a string that uses hyphens.
This also breaks `OS.get_locale_language()` because it expects underscores.

Windows:
```gdscript
print(OS.get_locale()) # en_US
print(OS.get_locale_language()) # en
```

HTML5:
```gdscript
print(OS.get_locale()) # en-US
print(OS.get_locale_language()) # en-
```

It seems that adding `locale = locale.replace("-", "_")` [here](https://github.com/pattlebass/godot/blob/5fec0d232a41a6e99bf4e00222a88bce719637cc/platform/javascript/js/engine/config.js#L336) solves the issue.
If this fix is good I can open a PR.

### Steps to reproduce

See above.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by pattlebass**
Fixes #63029.
Tested on 3.x as I couldn't get master to work with HTML5 exports.

### CODE REVIEW

File: platform/javascript/js/engine/config.js [hunk 1]
```diff
@@ -334,6 +334,7 @@ const InternalConfig = function (initConfig) { // eslint-disable-line no-unused-
 			locale = navigator.languages ? navigator.languages[0] : navigator.language;
 			locale = locale.split('.')[0];
 		}
+		locale = locale.replace("-", "_");
```
Comment (Faless) [inline platform/javascript/js/engine/config.js:337]:
```suggestion
		locale = locale.replace('-', '_');
```

Comment (pattlebass) [reply platform/javascript/js/engine/config.js]: Fixed it!

**Review by Faless — APPROVED** [review]

**Comment by Faless** [comment]
Thanks! :trophy:

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.
