### PR TITLE
Fix transparency background issue on Android

### LINKED ISSUE #106703: Android GodotFragment can't have a transparent background
### Tested versions

- Reproducible in: 4.5-dev4, 4.2.2-stable

### System information

Godot v4.2.2.stable.mono - Linux Mint 21.3 (Virginia) - X11 - GLES3 (Compatibility) - AMD Radeon RX 6800 (navi21, LLVM 15.0.7, DRM 3.57, 6.8.0-57-generic) () - AMD Ryzen 5 7600 6-Core Processor (12 Threads)

### Issue description

A `GodotFragment` in an Android app can't be given a transparent background with `android:background="@android:color/transparent"` as well as having the Godot project allow per-pixel transparency with the following project settings enabled:

- `display/window/per_pixel_transparency`
- `display/window/size/transparent`
- `rendering/viewport/transparent_background`

Running the Godot project from the editor, I correctly get a transparent background on Linux:

Image

However, on Android the background shows as black (I've added an image behind the Godot fragment container so I should be able to see it if Godot's background is transparent):

Image

### Steps to reproduce

1. Clone my [fork](https://github.com/lonevox/Godot-Android-Samples) of the GLTF Viewer.
2. In Android Studio, sync Gradle.
3. Run the `apps.gltf_viewer` run configuration.
4. Observe that the image of the Godot icon isn't visible behind the `GodotFragment`, and instead the area that should be transparent is black.

### Minimal reproduction project (MRP)

I've modified the [GLTF Viewer](https://github.com/m4gr3d/Godot-Android-Samples) referenced in the [docs](https://docs.godotengine.org/en/stable/tutorials/platform/android/android_library.html#embedding-godot-in-existing-android-projects) with these changes. My fork can be found [here](https://github.com/lonevox/Godot-Android-Samples).

### PR DESCRIPTION
**Pull request by m4gr3d**
Updates the logic to detect when transparency is required on Android using `display/window/per_pixel_transparency/allowed`, `display/window/size/transparent`, and `rendering/viewport/transparent_background`, which updates the render view configuration and the app's theme.

The requirement to update the app's theme means the feature is only available to `gradle` build exports.

Fixes https://github.com/godotengine/godot/issues/106703

Before

https://github.com/user-attachments/assets/29a1ebc0-e7f8-486a-b639-d797b791c3a3

After

https://github.com/user-attachments/assets/9caa0946-8d7f-4c2a-b508-0a9eedaa9db8

### CODE REVIEW

File: platform/android/export/export_plugin.cpp [hunk 1]
```diff
@@ -1037,9 +1037,14 @@ void EditorExportPlatformAndroid::_write_tmp_manifest(const Ref<EditorExportPres
 	store_string_at_path(manifest_path, manifest_text);
 }
 
+bool EditorExportPlatformAndroid::_should_be_transparent(const Ref<EditorExportPreset> &p_preset) const {
+	return (bool)get_project_setting(p_preset, "display/window/per_pixel_transparency/allowed") &&
+			(bool)get_project_setting(p_preset, "display/window/size/transparent") &&
+			(bool)get_project_setting(p_preset, "rendering/viewport/transparent_background");
```
Comment (bruvzg) [inline platform/android/export/export_plugin.cpp:1043]: `rendering/viewport/transparent_background` check is probably excessive, on desktop platforms setting `display/window/size/transparent`  (or `transparent` flag for the `Window`) will automatically set viewport background to transparent regardless of this setting.

**Comment by m4gr3d** [comment]
Switching to draft until https://github.com/godotengine/godot/pull/106724 is merged.

**Review by Alex2782 — COMMENTED** [review]
Test project: [godot-demo-projects/.../window_management](https://github.com/godotengine/godot-demo-projects/tree/master/misc/window_management)

`DisplayServer.has_feature(DisplayServer.FEATURE_WINDOW_TRANSPARENCY)`

https://github.com/godotengine/godot/blob/de376274041cb30ad71fd3bd8f7ec674c67187d6/platform/android/display_server_android.cpp#L79

Can we activate that now too? Or evaluate `android:windowIsTranslucent` there?

**Review by Alex2782 — COMMENTED** [review]
Test project: [godot-demo-projects/.../window_management](https://github.com/godotengine/godot-demo-projects/tree/master/misc/window_management)

`display/window/size/transparent = true` and disabled `DisplayServer.has_feature` check:
```gdscript
func _on_transparent_check_button_toggled(button_pressed: bool) -> void:
	#if not DisplayServer.has_feature(DisplayServer.FEATURE_WINDOW_TRANSPARENCY):
	#	OS.alert("Window transparency is not supported by the current display server (%s)." % DisplayServer.get_name())
	#	return
	get_viewport().transparent_bg = button_pressed
	DisplayServer.window_set_flag(DisplayServer.WINDOW_FLAG_TRANSPARENT, button_pressed)

```

On Android 13, Samsung Tab S7 (Adreno 650).

<details><summary>OpenGL</summary>

https://github.com/user-attachments/assets/87341d7b-d7f2-4011-842c-05f888482115

</details>

<details><summary>Vulkan (Mobile)</summary>

https://github.com/user-attachments/assets/dc3a4b88-3a96-425a-bf55-f8775f54019d

</details>


<details><summary>on MacOS, Metal (Mobile) for comparison</summary>


https://github.com/user-attachments/assets/4f1d1a4c-830d-44aa-844f-06bbf50b65c9


</details>

----------

At first glance OpenGL Renderer works correctly / as it should.
But after switching back and forth for the second time, the 3D scene is no longer rendered. 
But these are other issues that have nothing to do with this PR. (i think)
image

File: platform/android/export/export_plugin.cpp [hunk 2]
```diff
@@ -1038,6 +1038,11 @@ void EditorExportPlatformAndroid::_write_tmp_manifest(const Ref<EditorExportPres
 	store_string_at_path(manifest_path, manifest_text);
 }
 
+bool EditorExportPlatformAndroid::_should_be_transparent(const Ref<EditorExportPreset> &p_preset) const {
+	return (bool)get_project_setting(p_preset, "display/window/per_pixel_transparency/allowed") &&
```
Comment (Alex2782) [inline platform/android/export/export_plugin.cpp:1042]:
```suggestion
	return (bool)get_project_setting(p_preset, "display/window/per_pixel_transparency/allowed")
```

**Review by Alex2782 — COMMENTED** [review]
Test project: [godot-demo-projects/.../window_management](https://github.com/godotengine/godot-demo-projects/tree/master/misc/window_management)

In the test project, `display/window/size/transparent` isn't enabled, so I tried without it and didn't encounter any problems. Or is there anything wrong with that?  

---------

_removed `size/transparent` from `export_plugin.cpp`_
```cpp
bool EditorExportPlatformAndroid::_should_be_transparent(const Ref<EditorExportPreset> &p_preset) const {
	return (bool)get_project_setting(p_preset, "display/window/per_pixel_transparency/allowed");
}
```

 _and  `Godot.kt`_

```kotlin
// Check whether the render view should be made transparent
val shouldBeTransparent = java.lang.Boolean.parseBoolean(GodotLib.getGlobal("display/window/per_pixel_transparency/allowed"))

```

**Review by Alex2782 — APPROVED** [review]
Test project: [godot-demo-projects/.../window_management](https://github.com/godotengine/godot-demo-projects/tree/master/misc/window_management)

Tried again on the Samsung Tab S7 and the Pixel 4a. It looks fine during startup/initialization. 

_The Pixel 4a OpenGLES has other rendering issues; the 2D scene (UI) fades out after switching back and forth several times._

**Comment by syntaxerror247** [comment]
I am running the demo directly from Android Editor and having the same issue in opengl renderer but also having issues in vulkan renderer.


https://github.com/user-attachments/assets/d9c7aa52-d4f1-4e68-b017-3a9bfe5543bc

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Alex2782** [comment]
Can these 2 issue reports for Godot 3.x also be closed?

https://github.com/godotengine/godot/issues/52725
https://github.com/godotengine/godot/issues/36860

... or `cherrypick` necessary?

**Comment by syntaxerror247** [comment]
> Can these 2 issue reports for Godot 3.x also be closed?
> 
> #52725 #36860
> 
> ... or `cherrypick` necessary?

Cherry picking is not possible because it uses a new method for adding custom theme attributes during export. So, that would need to be implemented in 3.x first.
