### PR TITLE
Fix wrong `AnimationTrackKeyEdit` update timing

### LINKED ISSUE #69154: `AnimationTrackKeyEdit` can't edit correctly
### Godot version

4.0.dev

### System information

any

### Issue description

At the moment the value is set, the editor is regenerated and unfocused. This is a regression by https://github.com/godotengine/godot/pull/68902.

https://user-images.githubusercontent.com/61938263/203899144-28d424b2-9304-4ed4-8d23-142e008f39cf.mp4

### Steps to reproduce

Set key value with AnimationTrackKeyEdit

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by TokageItLab**
Fixed #69154, regression by #68902.

Updating KeyEdit should be avoided while KeyEdit is being edited.

### CODE REVIEW

File: editor/animation_track_editor.cpp [hunk 1]
```diff
@@ -4653,8 +4653,7 @@ void AnimationTrackEditor::_animation_changed() {
 		return; // All will be updated, don't bother with anything.
 	}
 
-	if (key_edit) {
-		_update_key_edit();
+	if (key_edit && !key_edit->setting) {
```
Comment (fire) [inline editor/animation_track_editor.cpp:4656]: The entire clause is empty.

Comment (TokageItLab) [reply editor/animation_track_editor.cpp]: yep I still working

**Comment by TokageItLab** [comment]
@fire Okay, ready to review.

File: editor/animation_track_editor.cpp [hunk 2]
```diff
@@ -5352,9 +5352,12 @@ void AnimationTrackEditor::_select_at_anim(const Ref<Animation> &p_anim, int p_t
 	ki.pos = p_pos;
 
 	selection.insert(sk, ki);
+	_update_key_edit();
 }
 
 void AnimationTrackEditor::_move_selection_commit() {
+	_clear_key_edit();
```
Comment (TokageItLab) [inline editor/animation_track_editor.cpp:5359]: This is still kinda hackey. I'll look into it.

**Comment by TokageItLab** [comment]
@fire Alright, I believe the regression has been fixed for now.
There is a problem that after changing the time from AnimationTrackKeyEdit, the new key is not deleted by undo, but this seems to be a problem that has existed for a long time, not regression. I will investigate later as a separate issue/PR.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
