### PR TITLE
Port robust signal (dis)connection to `ShapeCast2D`

### LINKED ISSUE #75233: Signal already connected error when instantiating scene with root node `ShapeCast2D`  when shape is "Local to Scene"
### Godot version

4.0.1

### System information

Fedora 37, Forward+, Intel(R) UHD Graphics 620 (WHL GT2)

### Issue description

When a scene has a `ShapeCast2D` as root node, and the shape of the `ShapeCast2D` is set to be "Local to Scene", if you try to instantiate this scene (either by script or just by placing it in another scene), and run this scene, the following error comes up:

```
E 0:00:00:0406   connect: Signal 'changed' is already connected to given callable 'ShapeCast2D::_redraw_shape' in that object.
  <C++ Error>    Method/function failed. Returning: ERR_INVALID_PARAMETER
  <C++ Source>   core/object/object.cpp:1270 @ connect()
```

The game seems to keep working as normal, however I'm not sure if there are other side effects to this error.

The expected behavior is for the game to run without errors.

### Steps to reproduce

1. Create a new scene -> `Other Node` -> `ShapeCast2D`
2. Add a `RectangleShape2D` (or any other shape) as shape to `ShapeCast2D` from the inspector
3. Open the `RectangleShape2D` -> `Resource` -> Enable `Local to scene`
4. Save this scene
5. Create a 2D scene and save it
6. Add the `ShapeCast2D` scene (created earlier) to this 2D scene
7. Run the project (use 2D scene as the main scene)
8. Error

### Minimal reproduction project

[ShapeCast2D.zip](https://github.com/godotengine/godot/files/11043144/ShapeCast2D.zip)

### PR DESCRIPTION
**Pull request by rburing**
Ported from `ShapeCast3D`. Fixes https://github.com/godotengine/godot/issues/75233.

### CODE REVIEW

File: scene/2d/shape_cast_2d.cpp [hunk 1]
```diff
@@ -151,9 +151,17 @@ bool ShapeCast2D::is_enabled() const {
...
+		return;
+	}
+	if (!shape.is_null()) {
+		shape->disconnect(CoreStringNames::get_singleton()->changed, callable_mp(this, &ShapeCast2D::_shape_changed));
+	}
 	shape = p_shape;
+	if (!shape.is_null()) {
+		shape->connect(CoreStringNames::get_singleton()->changed, callable_mp(this, &ShapeCast2D::_shape_changed));
+	}
 	if (p_shape.is_valid()) {
```
Comment (bruvzg) [inline scene/2d/shape_cast_2d.cpp:164]:
```suggestion
	if (shape.is_valid()) {
		shape->connect(CoreStringNames::get_singleton()->changed, callable_mp(this, &ShapeCast2D::_shape_changed));
```

File: scene/2d/shape_cast_2d.cpp [hunk 2]
```diff
@@ -151,9 +151,17 @@ bool ShapeCast2D::is_enabled() const {
 }
 
 void ShapeCast2D::set_shape(const Ref<Shape2D> &p_shape) {
+	if (p_shape == shape) {
+		return;
+	}
+	if (!shape.is_null()) {
```
Comment (bruvzg) [inline scene/2d/shape_cast_2d.cpp:157]:
```suggestion
	if (shape.is_valid()) {
```

**Review by YuriSizov — APPROVED** [review]

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.2.
