### PR TITLE
Separate 2D grid visibility and grid snap

### LINKED ISSUE #34386: Can't disable 2D grid when grid snapping is turned on in Godot 3.2
**Godot version:**
3.2 Beta 2 mono

**OS/device including version:**
MXLinux19 64bits

**Issue description:**
When grid snapping is enabled the grid can't be turned off, there's an option to always show the grid but not one to hide it.

**Steps to reproduce:**
Enable grid snapping.

### PR DESCRIPTION
**Pull request by timothyqiu**
Splits "Always Show Grid" option into a submenu:

* Show
    * Always show grid.
* Show when snapping:
    * Show when grid snapping is on.
    * Name taken from https://github.com/godotengine/godot/issues/34386#issuecomment-578439879
* Hide
    * Always hide grid.
* Toggle Grid
    * Go to the least restrictive option possible.
    * Follows logic from https://github.com/godotengine/godot/issues/34386#issuecomment-578437218
    * The default shortcut (NumberSign `#`) may not work because it conflicts with the "zoom 12.5%" shortcut. This is an existing issue. Please change the shortcut if you want to test it.

ksnip_20220209-180301

Closes #34386
Supersedes #35565

### CODE REVIEW

**Comment by akien-mga** [comment]
> * The default shortcut (NumberSign `#`) may not work because it conflicts with the "zoom 12.5%" shortcut. This is an existing issue. Please change the shortcut if you want to test it.

It would be good to find another shortcut. I guess I can _see_ why `#` was used (looks like a grid) but er, I would never expect this :P

**Comment by timothyqiu** [comment]
It was changed from `Ctrl+G` to `#` during a shortcut rearrangement in #50038. And later `Shift+3` is added as a short cut for 12.5% zoom in #50498, but it's unfortunately equal to `#` at least on QWERTY keyboards :joy:

**Comment by timothyqiu** [comment]
Resolved conflicts and changed shortcut to `CTRL+'` (`COMMAND+'` on macOS). Photoshop uses this shortcut for Grid toggle.

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -938,6 +938,59 @@ void CanvasItemEditor::_reset_create_position() {
...
+			case GRID_VISIBILITY_SHOW:
+				grid_visibility = GRID_VISIBILITY_SHOW_WHEN_SNAPPING;
+				break;
+			case GRID_VISIBILITY_SHOW_WHEN_SNAPPING:
+			case GRID_VISIBILITY_HIDE:
+				grid_visibility = GRID_VISIBILITY_SHOW;
+				break;
+		}
+	}
+}
```
Comment (KoBeWi) [inline editor/plugins/canvas_item_editor_plugin.cpp:992]: Need to update viewport here (after using Toggle Grid shortcut).

Comment (timothyqiu) [reply editor/plugins/canvas_item_editor_plugin.cpp:992]: Ah, that's why I had to release the shortcut inorder to see changes happen. Thank you for pointing that out :tada:

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
