### PR TITLE
Prompt user to terminate if quitting while project is running

### LINKED ISSUE #6915: Confirm keyboard quit
### Describe the project you are working on

Day-to-day godot usage

### Describe the problem or limitation you are having in your project

I often use CMD+Q to quit the running app.

Quite often the window will appear and then disappear as the game crashes because of some code bug.

In this case if I hit CMD+Q the whole godot editor exits.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Please add a confirm to quit

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When I try to quit the editor using a shortcut, it will ask me if I'm sure I want to quit

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

It's Godot

### PR DESCRIPTION
**Pull request by hhhapz**
Here's the prompt message:
image

One thing that is technically problematic is if you make changes while the project is running and don't have 'save before running' checked, you could technically lose unsaved progress if you click to terminate.

Closes: https://github.com/godotengine/godot-proposals/issues/6915

CC: @Calinou

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -2983,6 +2983,19 @@ void EditorNode::_menu_option_confirm(int p_option, bool p_confirmed) {
 			}
 
 			if (!p_confirmed) {
+				if (project_run_bar->is_playing()) {
+					if (p_option == RELOAD_CURRENT_PROJECT) {
+						confirmation->set_text(TTR("Terminate project before reloading?"));
+						confirmation->set_ok_button_text(TTR("Terminate & Reload"));
+					} else {
+						confirmation->set_text(TTR("Terminate project before closing?"));
+						confirmation->set_ok_button_text(TTR("Terminate & Quit"));
```
Comment (Calinou) [inline editor/editor_node.cpp:2992]: We use the "stop" term elsewhere, so I suggest also using it here for consistency:

```suggestion
						confirmation->set_text(TTR("Stop project before reloading?"));
						confirmation->set_ok_button_text(TTR("Stop & Reload"));
					} else {
						confirmation->set_text(TTR("Stop project before closing?"));
						confirmation->set_ok_button_text(TTR("Stop & Quit"));
```

**Comment by hhhapz** [comment]
this pr is ready for review!

**Comment by Calinou** [comment]
Sorry for the delayed response. This fails to build when rebased on top of current `master`:

```
Ranlib Library scene/libscene.linuxbsd.editor.x86_64.a ...
In file included from editor/scu/scu_editor_4.gen.cpp:2:
./editor/editor_node.cpp: In member function 'void EditorNode::_menu_option_confirm(int, bool)':
./editor/editor_node.cpp:3049:57: error: 'RELOAD_CURRENT_PROJECT' was not declared in this scope; did you mean 'PROJECT_RELOAD_CURRENT_PROJECT'?
 3049 |                                         if (p_option == RELOAD_CURRENT_PROJECT) {
      |                                                         ^~~~~~~~~~~~~~~~~~~~~~
      |                                                         PROJECT_RELOAD_CURRENT_PROJECT
```

Can you look into rebasing and fixing the build?

**Comment by hhhapz** [comment]
Updated the pr + tested with master, should be working again.

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` https://github.com/godotengine/godot/commit/5da6deaaca27f3d4ec5281d5b791408570919f15), it works as expected.

image

Note that when using a floating game window (with or without embedding) and you close the editor while the game window is in the foreground, the popup will show behind the floating window if the floating window is at the center of the screen. However, when the game window is embedded in the editor window, the popup is visible as expected.

**Review by Hilderin — APPROVED** [review]
Tested on Windows 11 with embedded floating, non floating and without embedding and works as expected when using Close menu, Alt-F4, the Window close icon and le Reload project menu.
Code sounds good to me!!

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by KoBeWi** [comment]
For some reason I see "Don't Save" button:
image
I don't even have unsaved changes.

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -3045,6 +3045,19 @@ void EditorNode::_menu_option_confirm(int p_option, bool p_confirmed) {
 			}
 
 			if (!p_confirmed) {
+				if (project_run_bar->is_playing()) {
+					if (p_option == PROJECT_RELOAD_CURRENT_PROJECT) {
+						confirmation->set_text(TTR("Stop running project before reloading the current project?"));
+						confirmation->set_ok_button_text(TTR("Stop & Reload"));
+					} else {
+						confirmation->set_text(TTR("Stop running project before exiting the editor?"));
+						confirmation->set_ok_button_text(TTR("Stop & Quit"));
```
Comment (KoBeWi) [inline editor/editor_node.cpp:3054]: This should use TTRC.

Comment (hhhapz) [reply editor/editor_node.cpp:3054]: @KoBeWi Sounds good, but what's happening here specifically? I notice that both TTR and TTRC are used in the file in different places 🤔

Comment (KoBeWi) [reply editor/editor_node.cpp:3054]: TTR marks a string for translation and translates string in place.
TTRC only marks it, but does nothing otherwise.
("marked" strings are extracted by an automated script that does regex on the codebase)

Godot has auto-translation system, which wasn't active in the editor in the past, but it was changed recently. Thus TTR strings are subject to translation twice (by TTR function and then auto-translation). Using TTRC allows for auto-translation only, which makes it easier to switch languages (see #102562).
