### PR TITLE
Detect when primusrun/optirun is in use

### LINKED ISSUE #25629: Cannot start with optirun/primusrun
**Godot version:*master*
16d402147b9057c9f7d43ef9b46eb8654e5483cc

**OS/device including version:Linux / 4.19.14-1-MANJARO**
GPU: Nvidia 960m (with bumblebee)
CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz

**Issue description:**
Since my last Pull ~ End of January, i cannot start Godot with optirun:
Following errors are thrown 
`XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":8"
      after 7 requests (7 known processed) with 0 events remaining.
XIO:  fatal IO error 2 (No such file or directory) on X server ":8"
      after 7 requests (7 known processed) with 0 events remaining.
`
Current Beta3 works
**Steps to reproduce:**
+ git pull 
+ scons platform=x11 -j7
+ optirun ./godot.x11.tools.64

### PR DESCRIPTION
**Pull request by hpvb**
It seems that bumblebee doesn't like us creating multiple GL contexts
to avoid this we now detect whether we're running with this software
and don't do anything.

This fixes #25629

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: platform/x11/os_x11.cpp [hunk 1]
```diff
@@ -253,6 +274,7 @@ Error OS_X11::initialize(const VideoMode &p_desired, int p_video_driver, int p_a
 		}
 	}
 
+
```
Comment (akien-mga) [inline platform/x11/os_x11.cpp]: Style issue :)

**Comment by akien-mga** [comment]
Thanks!
