### PR TITLE
Take eye offset into account for depth in StandardMaterial3D

### LINKED ISSUE #73404: Parallax mapping not rendering in stereoscopic 3D in VR
### Godot version

4.0 rc2

### System information

Windows 10, Vulkan, GTX 1070

### Issue description

Parallax occlusion mapping does not show in stereoscopic 3D, the shader seems to not be using individual eye positions like it does in 3.5. 

### Steps to reproduce

See attached project

### Minimal reproduction project

[VR test scene.zip](https://github.com/godotengine/godot/files/10750730/VR.test.scene.zip)

### PR DESCRIPTION
**Pull request by BastiaanOlij**
When using depth in `StandardMaterial3D` the eye offset wasn't taken into account giving the material a flat look when viewed in stereoscopic.

Note that eye_offset is set to `vec3(0, 0, 0)` for normal rendering and should just end up being ignored.

Fixes #73404

### CODE REVIEW

File: scene/resources/material.cpp [hunk 1]
```diff
@@ -1139,7 +1139,7 @@ void BaseMaterial3D::_update_shader() {
 
 	if (!RenderingServer::get_singleton()->is_low_end() && features[FEATURE_HEIGHT_MAPPING] && !flags[FLAG_UV1_USE_TRIPLANAR]) { //heightmap not supported with triplanar
 		code += "	{\n";
-		code += "		vec3 view_dir = normalize(normalize(-VERTEX)*mat3(TANGENT*heightmap_flip.x,-BINORMAL*heightmap_flip.y,NORMAL));\n"; // binormal is negative due to mikktspace, flip 'unflips' it ;-)
+		code += "		vec3 view_dir = normalize(normalize(-VERTEX+EYE_OFFSET)*mat3(TANGENT*heightmap_flip.x,-BINORMAL*heightmap_flip.y,NORMAL));\n"; // binormal is negative due to mikktspace, flip 'unflips' it ;-)
```
Comment (akien-mga) [inline scene/resources/material.cpp:1142]: That's a pre-existing problem, but for a future refactoring pass, we try to format generated shader code the same way that our .glsl files are formatted. So this line needs a lot more spaces, and it will make it a lot more readable too :)

Comment (BastiaanOlij) [reply scene/resources/material.cpp]: Added some spaces, let me know if that was what you had in mind?

**Review by clayjohn — APPROVED** [review]

File: scene/resources/material.cpp (hunk 1 above)
Comment (akien-mga) [reply scene/resources/material.cpp]: Yeah that looks good.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.1.
