### PR TITLE
Fix animation blending for value track `UPDATE_DISCRETE` and `UPDATE_TRIGGER` mode

### LINKED ISSUE #68261: `UPDATE_DISCRETE` & `UPDATE_TRIGGER` aren't blended correctly
### Godot version

4.0.beta3

### System information

MacOS 13 (Ventura)

### Issue description

I have setup a animation tree with a BlendTree as it's root. When I connect two `Transition` nodes together, the second one is unable to play animations that modify the `region_rect` property on Sprite2Ds.

### Steps to reproduce

1. Create a new project with a AnimationTree
2. Add an AnimationNodeBlendTree as it's root
3. Add two transition nodes
4. Connect one's output to another's input
5. The second one will not work.

**Example:**
https://user-images.githubusercontent.com/32573897/200008069-0f99b428-ac8d-4b50-8856-c1a598db1bdb.mov

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by TokageItLab**
Fixes #68261.

`UPDATE_DISCRETE` and `UPDATE_TRIGGER` do not blend values, but set values to objects on the fly, but this will be overwritten by the blended values.

This PR prevents overwriting by skipping the normal process of applying blend values if the blend contains `UPDATE_DISCRETE` or `UPDATE_TRIGGER` tracks. For blending, `INTERPOLATION_NEAREST` should be used instead. I will update the documentation about the blending later.

### CODE REVIEW

File: scene/animation/animation_tree.h [hunk 1]
```diff
@@ -233,6 +233,7 @@ class AnimationTree : public Node {
 		Variant init_value;
 		Variant value;
 		Vector<StringName> subpath;
+		bool is_discreted = false;
```
Comment (akien-mga) [inline scene/animation/animation_tree.h:236]:
```suggestion
		bool is_discrete = false;
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
