### PR TITLE
ScrollContainer: Fix RTL on follow focus

### LINKED ISSUE #94620: ScrollContainer follow focus is not taking scrollbar in to account when layout_direction is set to Right-to-Left
### Tested versions

Godot v4.3.beta3

### System information

Godot v4.3.beta3 - Fedora Linux 40 (KDE Plasma) - Wayland - Vulkan (Forward+) - (software emulation on CPU) llvmpipe (LLVM 18.1.6, 256 bits) 

### Issue description

ScrollContainer follow focus is not taking scrollbar in to account when layout_direction is set to Right-to-Left

First image is LtR, control is aligned with the scrollbar.
Screenshot_20240722_144408

If layout_direction is set to RtL, control is under the scrollbar.
Screenshot_20240722_144427

### Steps to reproduce

Switch between RtL and LtR on the ScrollContainer

### Minimal reproduction project (MRP)

[rtl-scrollcontainer-.zip](https://github.com/user-attachments/files/16333462/rtl-scrollcontainer-.zip)

### PR DESCRIPTION
**Pull request by Giganzo**
Believe this should fix: https://github.com/godotengine/godot/issues/94620

### CODE REVIEW

File: scene/gui/scroll_container.cpp [hunk 1]
```diff
@@ -282,7 +282,7 @@ void ScrollContainer::ensure_control_visible(Control *p_control) {
 	float right_margin = v_scroll->is_visible() ? v_scroll->get_size().x : 0.0f;
 	float bottom_margin = h_scroll->is_visible() ? h_scroll->get_size().y : 0.0f;
 
-	Vector2 diff = Vector2(MAX(MIN(other_rect.position.x, global_rect.position.x), other_rect.position.x + other_rect.size.x - global_rect.size.x + (!is_layout_rtl() ? right_margin : 0.0f)),
+	Vector2 diff = Vector2(MAX(MIN(other_rect.position.x - (is_layout_rtl() ? right_margin : 0.0f), global_rect.position.x), other_rect.position.x + other_rect.size.x - global_rect.size.x + (!is_layout_rtl() ? right_margin : 0.0f)),
```
Comment (bypie5) [inline scene/gui/scroll_container.cpp:285]: This is pretty minor, but I think it might be more clear to remain `right_margin` to `side_margin`. Since it's used to adjust the position based on the presence of a side scrollbar, perhaps `side_margin` would be more descriptive.

Comment (Giganzo) [reply scene/gui/scroll_container.cpp]: That makes sense.

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
