### PR TITLE
Assign the project manager title to the node instead of DisplayServer

### LINKED ISSUE #100727: Project Manager shows `(DEBUG)` as title
### Tested versions

v4.4.dev7.official [46c8f8c5c]

### System information

Godot v4.4.dev7 - Arch Linux #​1 SMP PREEMPT_DYNAMIC Mon, 09 Dec 2024 14:31:57 +0000 on X11 - X11 display driver, Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3060 Ti (nvidia; 565.77) - 13th Gen Intel(R) Core(TM) i5-13400F (16 threads)

### Issue description

The title is the correct `Godot Engine - Project Manager` when loading (showing the splash screen). It turns into `(DEBUG)` when loading is done:

Image

### Steps to reproduce

Open the project manager.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by mdelorme**
Fixes #100727 

Project Manager title is directly given to the `DisplayServer` at initialization. 

With the changes of ff6eea5 auto-translation triggers the renaming of the window and leading to the bug since the `title` attribute of the scene root was not defined.

This fix gives the title to the root of the `SceneTree` which solves the problem.

### CODE REVIEW

**Review by timothyqiu — CHANGES_REQUESTED** [review]
The title is now `Godot Engine - Project Manager (DEBUG)`.

The main window's title always has this `(DEBUG)` suffix for debug builds. The same goes for official builds too since debugging features are enabled when compiling the editor.

I think that's why the title was set on `DisplayServer` instead of `Window`.

**Comment by mdelorme** [comment]
I'm sorry, is that not wanted behavior ?
Should we aim for `Godot Engine - Project Manager` without the `(DEBUG)` even in debug builds ?

**Comment by mdelorme** [comment]
@timothyqiu I proposed a fix, can you tell me if that sounds correct to you. If that's ok, I'll squash everything.

File: scene/main/window.cpp [hunk 1]
```diff
@@ -1435,7 +1435,7 @@ void Window::_notification(int p_what) {
 
 			tr_title = atr(title);
 #ifdef DEBUG_ENABLED
-			if (window_id == DisplayServer::MAIN_WINDOW_ID) {
+			if (window_id == DisplayServer::MAIN_WINDOW_ID && !Engine::get_singleton()->is_project_manager_hint()) {
 				// Append a suffix to the window title to denote that the project is running
 				// from a debug build (including the editor). Since this results in lower performance,
```
Comment (timothyqiu) [inline scene/main/window.cpp:1440]: I'm not sure if this comment needs to be changed.

**Review by timothyqiu — APPROVED** [review]
Works as expected.

File: scene/main/window.cpp (hunk 1 above)
Comment (mdelorme) [reply scene/main/window.cpp:1440]: I can add a word on the project manager in the comment

**Comment by mdelorme** [comment]
I have added a comment on excluding the project manager for the `(DEBUG)` suffix and I've included the fix to `set_title` so that everything is done correctly everywhere.

**Comment by Repiteo** [comment]
Thanks!
