### PR TITLE
[3.x] Fix nested resources being cached if no-cache argument used

### LINKED ISSUE #59686: ResourceLoader setting `noCache` is ignored for nested resources
### Godot version

v3.4.4.stable.mono.official [419e713a2]

### System information

Manjaro Linux

### Issue description

Assume you have a custom resource that contains nested resources:

```csharp
public class SomeResource : Resource
{
    [Export()]
    public NestedResource NestedResource {get; set;}
}

public class NestedResource : Resource
{
        [Export]
        // this is a Godot dictionary
        public Dictionary<string, string> Foo = new Dictionary<string, string>();
}
```
When you load such a resource like this:

```csharp
private static SomeResource DoLoad()
{
    return ResourceLoader.Load("res://narf.tres", noCache: true) as SomeResource;
}
```
then the nested resource will still be cached even if `noCache`  is set to `true`. 

### Steps to reproduce

Run `save_load_test.tscn` in the attached project. It will do the following things:

1. Create an instance if `SomeResource` and fill its nested resource with values.
2. Save this instance to a `.tres`  file with `ResourceSaver`.
3. Load the resource again with `noCache` true and compare the values.
4. Create another instance of `SomeResource`  and fill its nested resource with different values.
5. Save this instance over the same `.tres`  file as in step 2.
6. Load the resource again with `noCache` true and compare the values.

In step 6 the comparison will fail as the nested resource is still cached and has the values from step 1 instead the values from step 4.

### Minimal reproduction project

C#
[cache.zip](https://github.com/godotengine/godot/files/8377885/cache.zip)

GDScript
[cache_test_gdscript.zip](https://github.com/godotengine/godot/files/8386361/cache_test_gdscript.zip)

### LINKED ISSUE #59752: ResourceLoader.has_cached() giving unexpected output when ResourceLoader.load() called with no_cache=true
### Godot version

3.3.stable, 3.4.4.stable

### System information

Linux Mint 20.3

### Issue description

```gdscript
func _ready():
	var res = Resource.new()
	var path = "res://test.tres"
	ResourceSaver.save(path, res)
	for i in range(10):
		res = ResourceLoader.load(path, "", true) # no_cache=true
		print(ResourceLoader.has_cached(path))
```
This code gives the following output
```
True
False
True
False
True
False
True
False
True
False
```
It should be all False.

### Steps to reproduce

- Save a resource using `ResourceSaver.save()` at a path.
- Load it using `ResourceLoader.load()` with `no_cache = true`.
- Use `ResourceLoader.has_cached()` on the path.
- Repeat step 2 & 3 few times.

### Minimal reproduction project

[Minimal.zip](https://github.com/godotengine/godot/files/8391373/Minimal.zip)

### PR DESCRIPTION
**Pull request by Razoric480**
Adds the `p_no_subresource_cache` optional argument to the `load()` and `load_interactive()` methods of ResourceFormatLoader, which is why this touches so many other classes. This ties into the `p_no_cache` argument of ResourceLoader, which went unused for nested resources in text/binary custom resources. This resulted in cached resources not being updated despite the cache being told to be skipped.

I am told this is already fixed in 4.0, so this is for 3.x only.

Fixes #59686, fixes #59752

### CODE REVIEW

File: core/io/image_loader.h [hunk 1]
```diff
@@ -72,7 +72,7 @@ class ImageLoader {
 
 class ResourceFormatLoaderImage : public ResourceFormatLoader {
 public:
-	virtual RES load(const String &p_path, const String &p_original_path = "", Error *r_error = nullptr);
+	virtual RES load(const String &p_path, const String &p_original_path = "", Error *r_error = nullptr, bool p_no_subresource_cache = false);
```
Comment (willnationsdev) [inline core/io/image_loader.h:75]: I'm not familiar with how the coding standards would decide on this (or *who* could confirm for you), but I'd want to double-check whether output variables should always be at the end of method definitions (in which case, `p_no_subresource_cache` would be preferred to be before `r_error`). On the other hand, doing so would require you to also refactor all uses of this loader in the codebase to ensure that it uses the proper ordering of arguments, so it'd be a lot more involved.

File: doc/classes/ResourceLoader.xml [hunk 2]
```diff
@@ -67,9 +67,11 @@
 			<return type="ResourceInteractiveLoader" />
 			<argument index="0" name="path" type="String" />
 			<argument index="1" name="type_hint" type="String" default="&quot;&quot;" />
+			<argument index="2" name="no_cache" type="bool" default="false" />
 			<description>
 				Starts loading a resource interactively. The returned [ResourceInteractiveLoader] object allows to load with high granularity, calling its [method ResourceInteractiveLoader.poll] method successively to load chunks.
 				An optional [code]type_hint[/code] can be used to further specify the [Resource] type that should be handled by the [ResourceFormatLoader]. Anything that inherits from [Resource] can be used as a type hint, for example [Image].
+				If [code]no_cache[/code] is [code]true[/code], the resource cache will be bypassed and the resource will be loaded anew. Otherwise, the cached resource will be returned if it exists.
```
Comment (willnationsdev) [inline doc/classes/ResourceLoader.xml:74]: Needs comma after `bypassed`.

**Review by willnationsdev — APPROVED** [review]
I'm not the greatest expert on resource handling yet, but from what I've learned thus far, all of these changes look quite safe to me. Not sure if they want someone else with more practiced eyes to review these changes too.

File: core/io/image_loader.h (hunk 1 above)
Comment (raulsntos) [reply core/io/image_loader.h:75]: Since this is 3.x I think it needs to be at the end, otherwise it'd be a compatibility breaking change.

Comment (Razoric480) [reply core/io/image_loader.h:75]: Compatibility is the main reason this was made into an optional parameter, yeah.

File: doc/classes/ResourceLoader.xml (hunk 2 above)
Comment (Razoric480) [reply doc/classes/ResourceLoader.xml:74]: I copy pasted the line from `load()`'s description just above it. Shoud I change both?

File: core/io/resource_loader.h [hunk 3]
```diff
@@ -41,6 +41,8 @@ class ResourceInteractiveLoader : public Reference {
 	Thread::ID path_loading_thread;
 
 protected:
+	bool no_subresource_cache;
```
Comment (akien-mga) [inline core/io/resource_loader.h:44]: Should be initialized, otherwise it's UB whether this is true or false.

**Comment by akien-mga** [comment]
This seems to _partially_ fix #59752 too (CC @AdwaithHSivam) but maybe not fully, could you check? For me it prints:
```
True
False
False
False
False
False
False
False
False
False
```
even though the method is always called with `no_cache=True`.

I also tried #43990 (CC @Flavelius) but the explanations are harder to follow for me and there's quite a bit of C# code to unpack to get to the root issue, so I couldn't manage to see if this changes things.

**Comment by Razoric480** [comment]
Hm, I get the same true-false-false-false pattern. I'l have to take a look.

**Comment by Razoric480** [comment]
There we go.
image

File: core/io/resource_format_binary.cpp [hunk 4]
```diff
@@ -287,7 +287,7 @@ Error ResourceInteractiveLoaderBinary::parse_variant(Variant &r_v) {
 				case OBJECT_INTERNAL_RESOURCE: {
 					uint32_t index = f->get_32();
 					String path = res_path + "::" + itos(index);
-					RES res = ResourceLoader::load(path);
+					RES res = ResourceLoader::load(path, "", no_subresource_cache);
```
Comment (reduz) [inline core/io/resource_format_binary.cpp:290]: IMO internal resources should be cached in some internal Map<> and loaded from there. This is actually always using the resource cache, so it will not work.

File: core/io/resource_format_binary.cpp [hunk 5]
```diff
@@ -674,7 +674,7 @@ Error ResourceInteractiveLoaderBinary::poll() {
 
 	RES res = RES(r);
 
-	r->set_path(path);
+	r->set_path(path, no_subresource_cache);
```
Comment (reduz) [inline core/io/resource_format_binary.cpp:677]: This is likely not a good idea, If you are loading without cache I would simply not set the path. The problem is, of course, the internal resources because in Godot 3 they are loaded into the cache, so I think they would need to be set into some sort of `Map<subindex,resource>` and loaded from there.

**Review by reduz — CHANGES_REQUESTED** [review]

File: core/io/resource_format_binary.cpp (hunk 5 above)
Comment (Razoric480) [reply core/io/resource_format_binary.cpp:677]: Would something like:
```c++
uint32_t index = f->get_32();
String path = res_path + "::" + itos(index);
IntResource sub{ path, index };
RES res;
if (internal_resources_cache.has(sub)) {
	res = internal_resources_cache[sub];
}
else {
	res = ResourceLoader::load(path, "", no_subresource_cache);
	internal_resources_cache.insert(sub, res);
}
```
work suitably?

File: doc/classes/ResourceLoader.xml (hunk 2 above)
Comment (willnationsdev) [reply doc/classes/ResourceLoader.xml:74]: Yeah, they would both be incorrect then. `If...true[/code],` is a dependent phrase, `the resource....bypassed` is an independent phrase, and then `the resource...anew` is a second independent phrase. Two independent phrases have to be conjoined with a conjunction preceded by a comma, so both paragraphs are missing the comma.

File: core/io/resource_format_binary.cpp (hunk 5 above)
Comment (reduz) [reply core/io/resource_format_binary.cpp:677]: I think I would just have something like `Map<int,RES>` for internal resources and use this always, but only load it from the cache in the main function when it first parses it.

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
Looks ok to me, definitely 3.6 material because it needs more testing.

**Comment by akien-mga** [comment]
Thanks!

**Comment by Zylann** [comment]
It broke my plugin apparently https://github.com/Zylann/godot_heightmap_plugin/issues/338

File: core/io/image_loader.h (hunk 1 above)
Comment (Zylann) [reply core/io/image_loader.h:75]: It's not compatible if addon plugins have to include a new parameter (it's optional on call, not on override). It makes them break compat with older versions of Godot.

**Comment by KoBeWi** [comment]
Yeah I noticed that `class_name` types don't work in tool scripts, but didn't really look deeper into it. Maybe it's related. That would be 3rd regression from this PR xd

**Comment by Rubonnek** [comment]
I wonder if that issue with tool scripts and `class_name` types is also related to #40584. I'm not familiar with how `filesystem_cache6` is related to `Resource` objects but it seems like all of this is tied together somehow.

**Comment by Razoric480** [comment]
I'll take a look, @Zylann , as it shouldn't need a change in signature. Thanks for the recreation.

**Comment by Razoric480** [comment]
I've appended a fix to #64298 since it's still pending that fixes it. However, it will require a signature fix in the resource format loader due to a change in API in 3.6.

Doesn't fix #40584 however. I don't think it's related, especially since it was already there in 3.2.

**Comment by marcinn** [comment]
Hi. 

[Qodot](https://github.com/QodotPlugin/qodot-plugin) is not working anymore - there are no buttons on the toolbar for QodotMap node, so map cannot be generated. When I forced to display these buttons, Qodot generated nodes but with wrong scripts attached. 

Bisecting shows 2ceb93bbeff6f5c7b6eed4ea79aff5f0574f4f92 as a first "bad" commit.

**Comment by Razoric480** [comment]
> Hi.
> 
> [Qodot](https://github.com/QodotPlugin/qodot-plugin) is not working anymore - there are no buttons on the toolbar for QodotMap node, so map cannot be generated. When I forced to display these buttons, Qodot generated nodes but with wrong scripts attached.
> 
> Bisecting shows [2ceb93b](https://github.com/godotengine/godot/commit/2ceb93bbeff6f5c7b6eed4ea79aff5f0574f4f92) as a first "bad" commit.

If you merge in #64298, does the issue persist?

**Comment by marcinn** [comment]
> 



> If you merge in #64298, does the issue persist?

No. This patch solves the issue, and there are no more output messages as described in godotengine/godot#64280
Thanks.
