### PR TITLE
Mark fma function as high end so it isn't used with the gl_compatibility renderer

### LINKED ISSUE #72881: Shader fma function (used by Visual Shader UVFunc node) not defined in Compatibility renderer
### Godot version

4.0b17

### System information

macOS 13.2

### Issue description

The shader function fma, used by the visual shader UVFunc node generated code:
```
// UVFunc:5
vec2 n_in5p1 = vec2(6.00000, 6.00000);
vec2 n_in5p2 = vec2(0.50000, 0.50000);
vec2 n_out5p0 = fma((UV - n_in5p2), n_in5p1, n_in5p2);
```
Does not seem to be defined in the Compatibility renderer, causing shader compilation to fail if it's used with a lot of errors and debug output (10000+ messages as it prints out a lot of engine shader code?). Ending with the relevant errors:
 ```
drivers/gles3/shader_gles3.cpp:242 - SceneShaderGLES3: Fragment shader compilation failed:
  ERROR: 0:928: Invalid call of undeclared identifier 'fma'
  ERROR: 0:930: Use of undeclared identifier 'm_n_out5p0'
  
  drivers/gles3/shader_gles3.cpp:342 - Method/function failed.
```

Simple shader using fma in Mobile:
Screenshot 2023-02-08 at 09 52 38

Switch to Compatibility renderer:
Screenshot 2023-02-08 at 09 53 27

### Steps to reproduce

- Start a project in Mobile
- Make a shader where you use the fma function, for example the shader below in the reproduction field. Or a visual shader using the UVFunc node.
- Assign the shader to a shader material and apply this to a visible mesh, observe it renders
- Switch project to Compatibility renderer
- See errors and failed shader compilation

### Minimal reproduction project

Minimal test shader, use in Compatibility renderer:

```
shader_type spatial;

void fragment() {
	vec2 n_in5p1 = vec2(6.00000, 6.00000);
	vec2 n_in5p2 = vec2(0.50000, 0.50000);
	vec2 n_out5p0 = fma((UV - n_in5p2), n_in5p1, n_in5p2);

	ALBEDO = vec3(1,0,0);
}

```

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/72881

``fma()`` is not available in GLSL 330 or GLSL ES 300 so it should not be exposed to the gl_compatibility renderer. Therefore we mark it as "high end" only and remove the places where it is used by visual shaders. All GLSL compilers will turn ``(a * b + c)`` into a single FMA instruction anyway

### CODE REVIEW

File: scene/resources/visual_shader_nodes.cpp [hunk 1]
```diff
@@ -7482,6 +7482,9 @@ String VisualShaderNodeMultiplyAdd::get_output_port_name(int p_port) const {
 }
 
 String VisualShaderNodeMultiplyAdd::generate_code(Shader::Mode p_mode, VisualShader::Type p_type, int p_id, const String *p_input_vars, const String *p_output_vars, bool p_for_preview) const {
+	if (OS::get_singleton()->get_current_rendering_method() == "gl_compatibility") {
+		return "	" + p_output_vars[0] + " = " + p_input_vars[0] + " * " + p_input_vars[1] + " + " + p_input_vars[2] + ";\n";
```
Comment (akien-mga) [inline scene/resources/visual_shader_nodes.cpp:7486]: Is there a risk that the input vars could be expressions? If so it might need parentheses.

Comment (clayjohn) [reply scene/resources/visual_shader_nodes.cpp]: I'm not sure. I don't think so. I can't see special handling in case of expressions elsewhere, but I have updated with parentheses anyway

File: scene/resources/visual_shader_nodes.cpp [hunk 2]
```diff
@@ -7482,6 +7482,9 @@ String VisualShaderNodeMultiplyAdd::get_output_port_name(int p_port) const {
 }
 
 String VisualShaderNodeMultiplyAdd::generate_code(Shader::Mode p_mode, VisualShader::Type p_type, int p_id, const String *p_input_vars, const String *p_output_vars, bool p_for_preview) const {
+	if (OS::get_singleton()->get_current_rendering_method() == "gl_compatibility") {
```
Comment (Chaosus) [inline scene/resources/visual_shader_nodes.cpp:7485]: In visual shader, this function could simply be replaced by `(a * b + c)` code (for compatibility profile) - no need to restrict user experience.

**Review by Chaosus — APPROVED** [review]
Looks good and correct.

**Comment by akien-mga** [comment]
Thanks!
