### PR TITLE
Complain if casting a freed object in a debug session

### LINKED ISSUE #50968: Casting a Deleted Object should return an error in debug mode
### Godot version

3.3.stable

### System information

Windows 10

### Issue description

This issue is connected to https://github.com/godotengine/godot/issues/35488, and https://github.com/godotengine/godot/issues/32383, but can be fixed separately.

When casting a `Deleted Object` of type `T` to type `U`, the same rules apply as if the `Object `was not deleted. Namely, if `T` is a built-in type and the cast fails, an error is raised. If the cast is successful, the `Deleted Object` is returned.

As described in the above issues, a reference to a `Deleted Object` can return a different `Object `in release mode, and importantly, one of a different type. So casting a `Deleted Object` is fine in debug mode, but can crash in release mode.

I think that to prevent the user falling into this trap, casting a Deleted Object should always result in an error.

### Steps to reproduce

Consider this snippet, adapted from https://github.com/godotengine/godot/issues/35488
```
func _ready():
	var a = []
	var c = MarginContainer.new()
	a.append(c)
	print(a[0])
	print(a[0] as MarginContainer)
	c.free()
	print(a[0])
	print(a[0] as MarginContainer)
	TextureRect.new()
	print(a[0] as MarginContainer)  # The TextureRect is allocated at the same address the MarginContainer was.
```

In debug mode this code produces no errors, and prints

```
[MarginContainer:1197]
[MarginContainer:1197]
[Deleted Object]
[Deleted Object]
[Deleted Object]
```

whereas in release mode it crashes, due to an invalid cast from `TextureRect ` to `MarginContainer`.

### Minimal reproduction project

Not needed

### PR DESCRIPTION
**Pull request by RandomShaper**
The idea is to give the user a chance to realize a mistake that will cause a crash in a release build (or with no debugger attached).

Fixes #50968.

**NOTE:** The version for 3.x is #51095.

### CODE REVIEW

**Comment by reduz** [comment]
Looks good to me, I guess @vnen should approve though.

File: modules/gdscript/gdscript_vm.cpp [hunk 1]
```diff
@@ -1231,6 +1231,13 @@ Variant GDScriptFunction::call(GDScriptInstance *p_instance, const Variant **p_a
 
 				GD_ERR_BREAK(to_type < 0 || to_type >= Variant::VARIANT_MAX);
 
+#ifdef DEBUG_ENABLED
+				if (EngineDebugger::is_active() && src->get_type() == Variant::OBJECT && !src->operator ObjectID().is_ref_counted() && ObjectDB::get_instance(src->operator ObjectID()) == nullptr) {
```
Comment (vnen) [inline modules/gdscript/gdscript_vm.cpp:1235]: Is there any reason to check `EngineDebugger::is_active()`? Shouldn't this be checked in any debug build, even if not actively debugging? In that case the user can still see an error being reported in the output.

**Comment by vnen** [comment]
Besides my question it looks good to me.

File: modules/gdscript/gdscript_vm.cpp (hunk 1 above)
Comment (RandomShaper) [reply modules/gdscript/gdscript_vm.cpp:1235]: I did it that way to match the similar checks present in `Variant`. However, I can see that other entities (like `Callable`) perform such checks regardless the debugger being active or not. So, the only real clue about keeping or removing that part of the condition will be what you tell me you want for GDScript.

Comment (vnen) [reply modules/gdscript/gdscript_vm.cpp:1235]: I'd say to not check for the debugger. It's somewhat common to test without a debugger attached, especially on mobile, so it's better to see a full error message in the log when it happens instead of when it hits something else.

Comment (RandomShaper) [reply modules/gdscript/gdscript_vm.cpp]: Done! (Also to the counterpart PR for 3.x.)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
