### PR TITLE
Fixes engine runs into an infinite loop when searching using FindBar

### LINKED ISSUE #64962: Godot 4 Alpha 14 - Crash upon searching class documentation
### Godot version

4.0 alpha 14

### System information

Windows 11 x64, RTX 2070 Max-Q, Vulcan mobile

### Issue description

Editor crashes when searching for `custom` in `TileSetAtlasSource` class documentation.

### Steps to reproduce

1. Create an empty project and a Node2D scene.
2. Add a script to it, and add the following line to it:
`var tile_set_atlas_source: TileSetAtlasSource`
3. Ctrl+Left Click on `TileSetAtlasSource` so you can get redirected to the class documentation.
4. Ctrl+F Search for `custom` and press `Enter`

### Minimal reproduction project

[godot4_alpha14_doc_search_crash.zip](https://github.com/godotengine/godot/files/9438356/godot4_alpha14_doc_search_crash.zip)

### PR DESCRIPTION
**Pull request by nongvantinh**
The exact commit that cause the bug is: 8ab13f8acefef73a0d68560c6866639d9ca0dc80 
In file `rich_text_label.cpp`
method `bool RichTextLabel::search(const String &p_string, bool p_from_selection, bool p_search_previous) {`

The loop inside that function:
```
	// Search remainder of the file
	while (current_line != ending_line) {
		// Wrap around
		if (current_line < 0) {
			current_line = main->lines.size() - 1;
		} else if (current_line >= main->lines.size()) {
			current_line = 0;
		}

		if (_search_line(main, current_line, p_string, char_idx, p_search_previous)) {
			scroll_to_line(current_line);
			update();
			return true;
		}
		p_search_previous ? current_line-- : current_line++;
	}
```
The special case is `ending_line = 0`
When the statement `else if (current_line >= main->lines.size()) {` is true: the `current_line` is set to 0
but the line `p_search_previous ? current_line-- : current_line++;` continue to execute and program ran into `infinite loop`

_Production edit: Fixes #64962_

### CODE REVIEW

File: scene/gui/rich_text_label.cpp [hunk 1]
```diff
@@ -4622,7 +4622,9 @@ bool RichTextLabel::search(const String &p_string, bool p_from_selection, bool p
 			queue_redraw();
 			return true;
 		}
-		p_search_previous ? current_line-- : current_line++;
+
+		if (current_line != ending_line)
+			p_search_previous ? current_line-- : current_line++;
```
Comment (YuriSizov) [inline scene/gui/rich_text_label.cpp:4627]:
```suggestion
		if (current_line != ending_line) {
			p_search_previous ? current_line-- : current_line++;
		}
```

To follow our codestyle, conditionals need to have both curly braces around their body (with the opening one on the same line as the condition).

**Comment by YuriSizov** [comment]
Also please amend the commit message and the PR title to describe what the change does with more detail (but not too much detail, just enough to answer the question "What does this commit do").

**Comment by nongvantinh** [comment]
My time was 1:39 a.m. I'm tired but unable to sleep.

So, instead of pretending to sleep, I decided to assist in the bug-fixing process.

That explains why I forgot about all the conventions. Please excuse me.

**Comment by KoBeWi** [comment]
If fixes the crash, but needs a check from @bruvzg

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
