### PR TITLE
[TextEdit] Use actual indentation offset instead of space width for wrapped lines.

### LINKED ISSUE #101062: CodeEdit (TextEdit?) linewrap indentation is wrong if font hinting is set to "Normal"
### Tested versions

4.4dev7

### System information

Godot v4.4.dev7 - Windows 10 (build 19045) - Multi-window, 2 monitors - OpenGL 3 (Compatibility) - AMD Radeon RX 6800 (Advanced Micro Devices, Inc.; 32.0.12033.1030) - AMD Ryzen 5 7600X 6-Core Processor (12 threads)

### Issue description

If font hinting is "normal" then the artificially indented wrapped text of a wrapping, wrap-indenting CodeEdit is misaligned with its parent line's indentation level.

Image

The issue goes away if subpixel positioning and rounding-remainders are both disabled.

Image

Something similar happens regardless of hinting level if Subpixel Positioning is disabled but rounding-remainders is left enabled, but the version with rounding-remainders applies to unindented/unwrapped text too, but is probably not noticeable with non-monospace fonts.

Image

### Steps to reproduce

Set up a CodeEdit with some long indented text, turn on wrapping and wrap indentation, make it wrap, set the font to something where you can configure the hinting, switch between Normal and the other settings. The indentation level of the wrapped text will likely be wrong with Normal mode (might be font-sensitive).

### Minimal reproduction project (MRP)

[wrapbugrepro.zip](https://github.com/user-attachments/files/18296976/wrapbugrepro.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes indentation offset when using non-monospaced font (hinting or subpixel positioning enabled) and spaces.

Fixes https://github.com/godotengine/godot/issues/101062

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Needs rebase.

File: tests/scene/test_text_edit.h [hunk 1]
```diff
@@ -7355,9 +7355,9 @@ TEST_CASE("[SceneTree][TextEdit] multicaret") {
 		CHECK(text_edit->get_caret_line(1) == 1);
 		CHECK(text_edit->get_caret_column(1) == 1);
 		CHECK(text_edit->get_caret_line(2) == 0);
-		CHECK(text_edit->get_caret_column(2) == 8);
+		CHECK(text_edit->get_caret_column(2) == 7);
 		CHECK(text_edit->get_caret_line(3) == 0);
-		CHECK(text_edit->get_caret_column(3) == 4);
+		CHECK(text_edit->get_caret_column(3) == 2);
```
Comment (bruvzg) [inline tests/scene/test_text_edit.h:7360]: Note: this test uses default non-monospaced font (there's no exact above position) and extremely small width (which make it pretty useless to test real control usage), so numbers are pretty arbitrary. New values look reasonable if test conditions recreated manually:
Screenshot 2025-03-19 at 12 56 14

**Comment by akien-mga** [comment]
Thanks!
