### PR TITLE
LineEdit: Now double click to select a word, and triple click to sele…

### LINKED ISSUE #46259: Double/triple click in LineEdit not working as expected
**Godot version:**

3.2 branch (f15f5b45781eb3de8e5811400f654e3e49580149)

**OS/device including version:**

macOS 10.14.6

**Issue description:**

When double-clicking in a LineEdit, I would expect it to select by word. Instead it selects the entire contents of the LineEdit. I would expect triple click to select the entire contents. (This is the way applications on macOS generally work as well.)

TextEdit and the script editor work properly - line edits are not consistent with them which is confusing (and frustrating).

**Steps to reproduce:**

1. Select any node with an exported var that shows up as a line edit in the inspector.
2. Change the contents to "Foo bar blat".
3. Double-click on "bar" == the entire contents are selected instead of just "bar".

### PR DESCRIPTION
**Pull request by kuruk-mm**
…ct all the content

Fix #46259

I used the code from `TextEdit` to make this one.

### CODE REVIEW

File: scene/gui/line_edit.cpp [hunk 1]
```diff
@@ -255,11 +255,36 @@ void LineEdit::_gui_input(Ref<InputEvent> p_event) {
...
+
+						while (beg > 0 && text[beg - 1] > 32 && (symbol == is_symbol(text[beg - 1]))) {
+							beg--;
+						}
+						while (end < text.length() && text[end + 1] > 32 && (symbol == is_symbol(text[end + 1]))) {
+							end++;
+						}
+						if (end < text.length()) {
+							end += 1;
+						}
```
Comment (bruvzg) [inline scene/gui/line_edit.cpp:282]: This should use `Vector<Vector2i> words = TS->shaped_text_get_word_breaks(text_rid);` instead of `is_symbol` and `> 32` to correctly detect words in the languages which do not use spaces, see `_move_cursor_left`, `_move_cursor_right` functions for example.

Comment (bruvzg) [reply scene/gui/line_edit.cpp:282]: But the current approach is fine for 3.2 version.

Comment (kuruk-mm) [reply scene/gui/line_edit.cpp:282]: Nice, I will update this PR doing that on `LineEdit` and `TextEdit` and open a new PR with this code for 3.2.

Comment (kuruk-mm) [reply scene/gui/line_edit.cpp]: Done

File: scene/gui/line_edit.cpp [hunk 2]
```diff
@@ -255,11 +255,28 @@ void LineEdit::_gui_input(Ref<InputEvent> p_event) {
...
+					} else if (b->is_doubleclick()) {
+						// Double-click select word.
+						Vector<Vector2i> words = TS->shaped_text_get_word_breaks(text_rid);
+						for (int i = 0; i < words.size(); i++) {
+							if (words[i].x < cursor_pos && words[i].y > cursor_pos) {
+								selection.enabled = true;
+								selection.begin = words[i].x;
+								selection.end = words[i].y;
+								selection.doubleclick = true;
+								selection.last_dblclk = OS::get_singleton()->get_ticks_msec();
```
Comment (bruvzg) [inline scene/gui/line_edit.cpp:275]:
```suggestion
								selection.last_dblclk = OS::get_singleton()->get_ticks_msec();
								cursor_pos = selection.end;
```

I would move the cursor to the end of the word, for consistency with TextEdit and other text editors.

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by christinoleo** [comment]
@kuruk-mm Thanks for the contribution!
I noticed that due to commit 06ae77a320ba7b83616e4a30b1f40152bd1d3a82 the method "shaped_text_get_word_breaks" now breaks on underscores (aka _ ), which means that a doubleclick on the editor window on a variable with_underscores_like_this will only select part of it (word by word split by the underscores) instead of the whole variable. Is this intended with your commit? I did some patch on my local godot to be able to select the entire variable name for myself and just want to know if this is something I should open an issue or PR about.. Thanks!

**Comment by groud** [comment]
>I noticed that due to commit 06ae77a the method "shaped_text_get_word_breaks" now breaks on underscores (aka _ ), which means that a doubleclick on the editor window on a variable with_underscores_like_this will only select part of it (word by word split by the underscores) instead of the whole variable.

Ah yeah, I had the same issue. This is quite annoying.
