### PR TITLE
Fix remembering of an unsaved scene on exit

### LINKED ISSUE #33326: When you don't save unsaved scene on exit, it's not remembered
**Godot version:**
3.2 alpha3

**Issue description:**
This is similar to #28263

**Steps to reproduce:**
1. Open multiple scenes
2. Edit one of them
3. Make sure "Restore Scenes on Load" in Editor Settings is enabled
4. Close the editor
5. The one edited scene will ask if you want to save
6. Don't
7. When you reload the project, the scene is not automatically opened

Works correctly if you choose save instead.

### PR DESCRIPTION
**Pull request by Dodoveloper**
So, take 2.

The problem was that the actual flow does not include this possibility: if the save popup appears, the editor always closes the scene by calling `_remove_scene(tab_closing)`.

Obviously, at first I tried to stop the editor from indistinctly removing the scenes, but then it wouldn't work with more than one unsaved scene. I tried different approaches, but every solution broke something else. AFAIK the bottom line is: `_remove_scene` has to be called. So that's why this  fix reopens scenes that have just been closed if the user wants to restore the scene tabs. 

This honestly looks like the best solution to me, it works fine and does not mess around with the flow too much. It's not the most efficient, but the flow would probably need a rework otherwise.
I'd be very interested to know what more experienced developers think about this.

Fixes #33326

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -2161,6 +2161,8 @@ void EditorNode::_menu_option_confirm(int p_option, bool p_confirmed) {
 
 			if (!p_confirmed) {
 				tab_closing = p_option == FILE_CLOSE ? editor_data.get_edited_scene() : _next_unsaved_scene(false);
+				_scene_tab_changed(tab_closing);
+				_update_scene_tabs();
```
Comment (KoBeWi) [inline editor/editor_node.cpp:2165]: What is this code for? I removed it and it still works fine.

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -2825,6 +2827,9 @@ void EditorNode::_discard_changes(const String &p_str) {
 			_update_scene_tabs();
 
 			if (current_option == FILE_CLOSE_ALL_AND_QUIT || current_option == FILE_CLOSE_ALL_AND_RUN_PROJECT_MANAGER) {
+				// if restore tabs, reopen the scene that has just been closed
```
Comment (KoBeWi) [inline editor/editor_node.cpp:2830]:
```suggestion
				// If restore tabs is enabled, reopen the scene that has just been closed, so it's remembered properly.
```

**Comment by KoBeWi** [comment]
This bug is annoying me, so I decided to make a proper review for this PR (sorry that it's so late). The solution isn't perfect, because when you have a very big scene open it might make the editor exiting much longer. Buuut, I realized that you don't often close with many big unsaved scenes (especially as Godot by default saves on each run), so this is not that bad. Definitely better than the original issue this tries to solve.

Make the changes I requested and I can approve the PR.

File: editor/editor_node.cpp (hunk 1 above)
Comment (Dodoveloper) [reply editor/editor_node.cpp:2165]: This is more of a quality of life improvement. 
Say you have two unsaved scenes open (_tab1*_, _tab2*_) and you're focused on the tab to the right (_tab2*_). When you exit the editor, the popup asks you if you want to save. Since Godot scans the unsaved scenes from left to right, the popup will ask what you want to do with _tab1*_, but it's still focused on _tab2*_. You save/discard, _tab1_ gets closed and then reopened by this fix, but it's appended on the right. So now you have _tab2*_ and _tab1_, popup asks for _tab2*_ but the editor is focused on _tab1_.
These lines make the editor focus on the tab the popup is asking you what to do with, otherwise Godot will always focus on the latest one to the right, so the user can't really see the tab Godot is asking him to do something with, and it's impossible to select it when the popup is present.
I thought it's better to let the user see the tab, so that he can better see if it's to be saved or not.
Actually, I checked the code and it's pointless to call `_update_scene_tabs()`, because it will get called anyway if necessary, but `_scene_tab_changed` has to be called to fix the issue I've just explained.

Comment (KoBeWi) [reply editor/editor_node.cpp:2296]: Ok the `_scene_tab_changed()` call is ok, but if `_update_scene_tabs()` is unnecessary then remove it.

**Review by KoBeWi — APPROVED** [review]

File: editor/editor_node.cpp (hunk 1 above)
Comment (Dodoveloper) [reply editor/editor_node.cpp]: Ok, I applied everything and squashed the commits in a single one. It should be fine now

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by Dodoveloper** [comment]
Thanks! Glad to contribute 😃

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
