### PR TITLE
Move logic for saving project features to ProjectSettings save_custom

### LINKED ISSUE #55302: Running debug process pollutes project.godot and forces to show a confirm dialog after closing
### Godot version

e49b127b41a425fadc47d09d375624c5511f1f06

### System information

Windows 10

### Issue description

bug

### Steps to reproduce

Run to debug any project and close it.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by aaronfranke**
Hotfix for #31171 that only showed up on at-least-somewhat-complex projects.

The old code written by over-2-years-ago-me was just badly designed code. It was saving on load, and there were two places where it tried to do this. I shouldn't have trusted myself. #31171 appears fine if it's only tested for a short time, but breaks down in any complex situation. This PR should make it work much better. Testing appreciated.

<i>Bugsquad edit:</i> Fix #55302

### CODE REVIEW

**Comment by Chaosus** [comment]
This is a fix for https://github.com/godotengine/godot/issues/55302?

File: core/config/project_settings.cpp [hunk 1]
```diff
@@ -923,6 +918,34 @@ Error ProjectSettings::_save_custom_bnd(const String &p_file) { // add other par
...
+	// Check the rendering API.
+	const String rendering_api = get("rendering/quality/driver/driver_name");
+	if (rendering_api != "") {
+		// Add the rendering API as a project feature if it doesn't already exist.
+		if (!project_features.has(rendering_api)) {
+			project_features.append(rendering_api);
+		}
+	}
+	// Check for the existence of a csproj file.
+	if (FileAccess::exists(get_resource_path().plus_file(String(get("application/config/name")) + ".csproj"))) {
```
Comment (akien-mga) [inline core/config/project_settings.cpp:935]: That's clever, though might need double checking that it's the exact same code used to generate the `.csproj` (I can imagine there's a validation step as some characters allowed in the project name might not be allowed in file names).

I guess that also means you might not need to rely on `MODULE_MONO_ENABLED` anymore?

Comment (akien-mga) [reply core/config/project_settings.cpp:935]: (I see this is code just moved around, I missed it in the original PR. So this doesn't need to be changed in this hotfix PR.)

**Comment by aaronfranke** [comment]
@Chaosus Yes, it should be. I'd appreciate testing on this PR though.

File: core/config/project_settings.cpp (hunk 1 above)
Comment (aaronfranke) [reply core/config/project_settings.cpp:935]: `MODULE_MONO_ENABLED` is used to check if the current build of Godot supports C#, but this code is checking if a project has a C# project file (I do need to double check that it's the same logic).

Comment (aaronfranke) [reply core/config/project_settings.cpp]: It wasn't the same logic. I updated the PR to have a copy of the logic from the Mono module. We might want to make this a method on ProjectSettings and use it in Mono too. I guess it's kind of worth doing in a separate PR but since it's urgent I think that I've talked myself into doing it in this PR...

File: modules/mono/csharp_script.cpp [hunk 2]
```diff
@@ -788,11 +788,7 @@ bool CSharpLanguage::is_assembly_reloading_needed() {
 
 	GDMonoAssembly *proj_assembly = gdmono->get_project_assembly();
 
-	String appname = ProjectSettings::get_singleton()->get("application/config/name");
-	String appname_safe = OS::get_singleton()->get_safe_dir_name(appname);
-	if (appname_safe.is_empty()) {
-		appname_safe = "UnnamedProject";
-	}
+	String appname_safe = ProjectSettings::get_singleton()->get_safe_project_name();
```
Comment (akien-mga) [inline modules/mono/csharp_script.cpp:791]: That's a good chance but I'd have left it out of this PR to focus on the save fix (my mistake for commenting in the wrong context). I can see more places which currently rely on `get_safe_dir_name` to sanitize `application/config/name` - e.g. `OS_Unix::get_user_data_dir()` - so it would be worth refactoring them all in a dedicated PR).

Comment (akien-mga) [reply modules/mono/csharp_script.cpp:791]: But OK it's probably late for you on Thanksgiving's eve, so we can also merge this as is and do further tweaks (such as exposing this to scripting, and using in more places) in a follow-up PR later.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
