### PR TITLE
Change `VariantUtility` to prevent undef `print_verbose`

### LINKED ISSUE #101966: `print_verbose` makes build fail when `scu_build=yes`
### Tested versions

- 4.4.beta

### System information

Windows 11

### Issue description

The `print_verbose` macro is causing one of the CI jobs that uses `scu_build=yes` to fail in my PR although I didn't modify the file calling it.
https://github.com/godotengine/godot/actions/runs/12934119444/job/36074414239

My local build also fails when I use `scu_build=yes` but works fine otherwise.
```sh
[100%] godot\core/debugger/remote_debugger_peer.cpp(172): error C3861: 'print_verbose': identifier not found
```

By the way, it works if I replace it with `WARN_VERBOSE`.

### Steps to reproduce

- Checkout https://github.com/godotengine/godot/pull/100516
- I changed calls to `print_verbose`  in `core/debugger/remote_debugger_peer.cpp` to `WARN_VERBOSE` to fix CI. Change it back to `print_verbose`. 
- Build it with `scons scu_build=yes`.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by lawnjelly**
Changes the `VariantUtility` function from `print_verbose` to `_print_verbose`, eliminating the need for undefining the `print_verbose` macro, which caused compilation problems.

Fixes #101966

## Notes
* Although the problem was seen occurring in a SCU build, the problem was not directly related to SCU, but rather the fact that `variant_utility.h` undefined `print_verbose`.
* This meant that any code compiled _after_ this include would fail to compile `print_verbose`.
* Feel free to suggest any variations on the macro name / func name, these were just a quick guess.

## Discussion
`VariantUtility` contained a `print_verbose` function for binding (with gdscript etc) which conflicted with the global definition of `print_verbose`. This had been worked around by undefining `print_verbose` in these files, which was a little hacky, and had the side effect of breaking compilation in any later file that tried to use `print_verbose`.

The more sensible solution was to give the `VariantUtility` function a different name. @Calinou informed me that it was possible to bind a function with a different name exposed to gdscript than the c++ function, and this (hopefully) provides the simplest solution.

### CODE REVIEW

**Review by Ivorforce — COMMENTED** [review]
Your implementation is perfectly fine.
As a proposed solution to the problem, it's acceptable, but I think the solution I'd prefer would be to change the `print_verbose` macro to a function:
```c++
template <typename... Args>
void print_verbose(const Variant &p_var, Args... p_args) {
	if (is_print_verbose_enabled()) {
		print_line(p_var, p_args...);
	}
}
```

I have no idea why the snippet was made a macro in the first place (premature optimization?), but we can see now that it being one has led to awkward workarounds.

**Comment by Ivorforce** [comment]
Right. That makes sense (although it probably still is prematurely optimized).
In any case, then I would say the best solution would be a full project find and replace of `print_verbose` -> `PRINT_VERBOSE`. The reason macros are usually uppercase is precisely to avoid this kind of issue, where it interferes with normal function usage.

**Comment by lawnjelly** [comment]
I do agree on capitalization for macros, mind you that approach might be subject to more push back (as the change is less localized), and will require rebasing existing PRs that use `print_verbose`.

I wouldn't be surprised if this was historically a function and later changed to a macro for the string concat efficiency.

Probably better for a separate PR though, so preferred approach can be chosen in a meeting.

**Review by Ivorforce — APPROVED** [review]
> I do agree on capitalization for macros, mind you that approach might be subject to more push back (as the change is less localized), and will require rebasing existing PRs that use print_verbose.

Agreed.
I see no reason to block this PR over there being another, possibly contentious solution. Your solution is self contained and unproblematic. The priority is fixing the bug, so I'm happy to approve.

> I wouldn't be surprised if this was historically a function and later changed to a macro for the string concat efficiency.

I looked it up, that's correct!

> Probably better for a separate PR though, so preferred approach can be chosen in a meeting.

Agreed!

File: core/variant/variant_utility.cpp [hunk 1]
```diff
@@ -1625,6 +1623,50 @@ static _FORCE_INLINE_ Variant::Type get_ret_type_helper(void (*p_func)(P...)) {
...
+		static void call(Variant *r_ret, const Variant **p_args, int p_argcount, Callable::CallError &r_error) { \
+			r_error.error = Callable::CallError::CALL_OK;                                                        \
+			VariantUtilityFunctions::m_func_cname(p_args, p_argcount, r_error);                                  \
+		}                                                                                                        \
+		static void validated_call(Variant *r_ret, const Variant **p_args, int p_argcount) {                     \
+			Callable::CallError c;                                                                               \
+			VariantUtilityFunctions::m_func_cname(p_args, p_argcount, c);                                        \
+		}                                                                                                        \
+		static void ptrcall(void *ret, const void **p_args, int p_argcount) {                                    \
+			Vector<Variant> args;                                                                                \
```
Comment (kiroxas) [inline core/variant/variant_utility.cpp:1638]: push_back in a loop :s . ould be better to resize + direct assignment, to ensure only one allocation.

File: core/variant/variant_utility.cpp [hunk 2]
```diff
@@ -1625,6 +1623,50 @@ static _FORCE_INLINE_ Variant::Type get_ret_type_helper(void (*p_func)(P...)) {
...
+			for (int i = 0; i < p_argcount; i++) {                                                               \
+				args.push_back(PtrToArg<Variant>::convert(p_args[i]));                                           \
+			}                                                                                                    \
+			Vector<const Variant *> argsp;                                                                       \
```
Comment (kiroxas) [inline core/variant/variant_utility.cpp:1642]: same here, and could be folded in previous loop

**Review by kiroxas — APPROVED** [review]

**Comment by akien-mga** [comment]
> Then I would say the best solution would be a full project find and replace of `print_verbose` -> `PRINT_VERBOSE`. The reason macros are usually uppercase is precisely to avoid this kind of issue, where it interferes with normal function usage.

There is already a PR to do exactly that: #100224.

But indeed, as I commented there, `print_verbose` is meant to look and feel like a function because it's similar to the `print_line` and `print_error` functions.

But its argument can often be costly to compute, hence why it was made a macro to avoid paying that cost. That makes it possible to use `print_verbose` relatively liberally without worrying too much that this will have a performance impact in production builds.

Whether that's a premature optimization, this would likely be worth testing.

File: core/variant/variant_utility.cpp (hunk 1 above)
Comment (lawnjelly) [reply core/variant/variant_utility.cpp:1638]: Agreed, but this is copied as is from `FUNCBINDVARARGV` (the only change is the c++ function name), so any improvements to efficiency here is out of scope.

Actually looking at it, it might be better to call this new macro from `FUNCBINDVARARGV`, to reduce the code duplication and make it clearer, so I'll change this.

**Comment by lawnjelly** [comment]
Realized it would be better to call this new macro from FUNCBINDVARARGV, to reduce the code duplication and make it clearer, have re-pushed, should be clearer now what is going on.

**Comment by lawnjelly** [comment]
> Whether that's a premature optimization, this would likely be worth testing.

The macro approach is definitely worth doing - I was doing some profiling a couple of days ago with a similar logging macro, and the cost of concatenating strings that will never be printed is indeed significant.

**Comment by Ivorforce** [comment]
When I brought up premature optimization i failed to consider that the argument evaluation could be deferred; i thought it may only try to avoid a call. It being a macro makes more sense to me now!

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
