### PR TITLE
Fixes the right and center alignment bug of rich text label

### LINKED ISSUE #38846: [center] and [right] bbcode align tags in RichTextLabel causes text to overlap itself
**Godot version:** 3.2.1 (stable release)

**OS/device including version:** Windows 10 Pro Version 1809 (build 17763.1217)

**Issue description:**
When using either the [center] or [right] align tags in a RichTextLabel, it will sometimes cause the last line to overlap the previous one under certain conditions. Both the length of the bbcode text string (after tags are parsed) and the size of the Rect are variables in causing this to happen. Additionally, the two tags do not act like their alignment counterparts in a regular Label, as seen in the attached screenshot:

richtextlabel overlap bug

_RichTextLabel on the left, plain Label on the right. Along with the overlapping issue, the RichTextLabel [center] is not a true center as displayed in the regular Label; it appears to be left aligned and simply shifted toward the middle._

**Steps to reproduce:**
-Create a RichTextLabel
-Enable BB Code
-In the BB Code Text field, type a string preceded by either the [center] or [right] tag
-Adjust the size of the Rect until the displayed text overlaps itself

**Minimal reproduction project:**
[RichTextLabel Overlap Bug.zip](https://github.com/godotengine/godot/files/4648142/RichTextLabel.Overlap.Bug.zip)

### PR DESCRIPTION
**Pull request by theoway**
Fixes #38846 
**Bug**:- `[right]` and `[center]` alignment tags of BBCode in RichTextLabel were not aligning properly like they were supposed to, and the text would overlap when the label was resized.
**Reason**:- Offset cache of the lines was not getting updated.

I've used center alignment for demonstration.
**Before the fix**:-
Godot Engine - RichTextLabel Overlap Bug - Main Scene tscn (_) 2020-05-30 14-10-31

**After the fix**:-
Godot Engine - RichTextLabel Overlap Bug - Main Scene tscn (_) 2020-05-30 14-06-08_Trim

### CODE REVIEW

File: scene/gui/rich_text_label.cpp [hunk 1]
```diff
@@ -256,6 +256,10 @@ int RichTextLabel::_process_line(ItemFrame *p_frame, const Vector2 &p_ofs, int &
 			lh = line < l.height_caches.size() ? l.height_caches[line] : 1;                                                                                     \
 			line_ascent = line < l.ascent_caches.size() ? l.ascent_caches[line] : 1;                                                                            \
 			line_descent = line < l.descent_caches.size() ? l.descent_caches[line] : 1;                                                                         \
+			if (p_mode == PROCESS_DRAW) {																														\
+				if (line < l.offset_caches.size()) 																											    \
+					wofs = l.offset_caches[line];																												\
+			}																																					\
```
Comment (pouleyKetchoupp) [inline scene/gui/rich_text_label.cpp:262]: Thanks for fixing this! I don't know about the logic in this part of code, but I just want to point out that `\` characters are not properly aligned.
I'm going to run some tests on my side for the fix itself.

Comment (pouleyKetchoupp) [reply scene/gui/rich_text_label.cpp:262]: And brackets are also missing for the second condition to follow the coding rules :)

**Comment by pouleyKetchoupp** [comment]
Great job!

This PR also fixes #34308.

I've tested different cases with left/center/right align, some images and different fonts and everything works fine so far.

File: scene/gui/rich_text_label.cpp (hunk 1 above)
Comment (theoway) [reply scene/gui/rich_text_label.cpp]: I've added the brackets with the second condition. But still can't properly align the '\'. In my IDE, they're properly aligned, but here they're not aligned. Don't know what to do

**Comment by theoway** [comment]
> Great job!
> 
> This PR also fixes #34308.
> 
> I've tested different cases with left/center/right align, some images and different fonts and everything works fine so far.

Thanks for running the tests.

File: scene/gui/rich_text_label.cpp (hunk 1 above)
Comment (akien-mga) [reply scene/gui/rich_text_label.cpp]: Your IDE probably uses more or less than 4 spaces for tabs.
You can fix alignment using `clang-format`: https://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html#header-includes

Comment (theoway) [reply scene/gui/rich_text_label.cpp]: I'm getting this error while formatting in visual studio 17 : Unknown key 'JavaImportGroups'

Comment (akien-mga) [reply scene/gui/rich_text_label.cpp]: That means that your clang-format version is probably too old. You need 8.0 or later.

File: scene/gui/rich_text_label.cpp [hunk 2]
```diff
@@ -256,6 +256,10 @@ int RichTextLabel::_process_line(ItemFrame *p_frame, const Vector2 &p_ofs, int &
 			lh = line < l.height_caches.size() ? l.height_caches[line] : 1;                                                                                     \
 			line_ascent = line < l.ascent_caches.size() ? l.ascent_caches[line] : 1;                                                                            \
 			line_descent = line < l.descent_caches.size() ? l.descent_caches[line] : 1;                                                                         \
+			if (p_mode == PROCESS_DRAW) {                                                                                                                       \
+				if (line < l.offset_caches.size())                                                                                                              \
```
Comment (akien-mga) [inline scene/gui/rich_text_label.cpp:260]: Use braces around `if` statement blocks.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.
