### PR TITLE
Make `fdialog_project` up to become the child of `ProjectManager` instead of child of `ProjectDialog`

### LINKED ISSUE #94081: Project Manager looks like it is reporting an error when importing a new project
### Tested versions

- Reproducible in v4.3.dev5.official [89f70e98d] onward
- Not reproducible in v4.3.dev4.official [df78c0636] and earlier

Looking at the commit log, I suspect that this change might have been introduced by https://github.com/godotengine/godot/commit/2130f1121a4d4bbc8c812ac6bea78cae1203c7ad

### System information

Godot v4.3.beta2 - Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 980 Ti (NVIDIA; 31.0.15.3598) - 13th Gen Intel(R) Core(TM) i7-13700K (24 Threads)

### Issue description

When first clicking the Import button on the Project Manager, it appears as if an error message with red text is presented to the user, but then is quickly covered by the file selection window.

In previous versions of Godot, this error message and its red text was not shown until after a folder was selected:

https://github.com/godotengine/godot/assets/17506573/c091ddf7-b1eb-4d47-881e-dc87e4582aab

Personally, the red text of this error message caught my eye and made me think that there was an error happening with the project manager. This was not an issue previously because the red text error message would only appear after the user selected an invalid project or folder.

### Steps to reproduce

- Click the Import button in the Project Manager

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes https://github.com/godotengine/godot/issues/94081

### CODE REVIEW

**Comment by KoBeWi** [comment]
To keep the code in ProjectDialog you can create the file dialog in `NOTIFICATION_READY` and use `add_sibling()` instead.

**Comment by jsjtxietian** [comment]
> To keep the code in ProjectDialog you can create the file dialog in `NOTIFICATION_READY` and use `add_sibling()` instead.

I think it's a better way, but when I do this the `fdialog_project` won't popup, it there anything I did wrong? 

Here is the diff

```C++
diff --git a/editor/project_manager/project_dialog.cpp b/editor/project_manager/project_dialog.cpp
index be5fa8745c..1fb97beb08 100644
--- a/editor/project_manager/project_dialog.cpp
+++ b/editor/project_manager/project_dialog.cpp
@@ -389,6 +389,8 @@ void ProjectDialog::_browse_install_path() {
 }
 
 void ProjectDialog::_project_path_selected(const String &p_path) {
+	show_dialog();
+
 	if (create_dir->is_pressed() && (mode == MODE_NEW || mode == MODE_INSTALL)) {
 		// Replace parent directory, but keep target dir name.
 		project_path->set_text(p_path.path_join(project_path->get_text().get_file()));
@@ -686,8 +688,6 @@ void ProjectDialog::set_project_path(const String &p_path) {
 }
 
 void ProjectDialog::ask_for_path_and_show() {
-	// Workaround: for the file selection dialog content to be rendered we need to show its parent dialog.
-	show_dialog();
 	_browse_project_path();
 }
 
@@ -787,6 +787,14 @@ void ProjectDialog::_notification(int p_what) {
 			project_browse->set_icon(get_editor_theme_icon(SNAME("FolderBrowse")));
 			install_browse->set_icon(get_editor_theme_icon(SNAME("FolderBrowse")));
 		} break;
+		case NOTIFICATION_READY: {
+			fdialog_project = memnew(EditorFileDialog);
+			fdialog_project->set_previews_enabled(false); //Crucial, otherwise the engine crashes.
+			fdialog_project->set_access(EditorFileDialog::ACCESS_FILESYSTEM);
+			fdialog_project->connect("dir_selected", callable_mp(this, &ProjectDialog::_project_path_selected));
+			fdialog_project->connect("file_selected", callable_mp(this, &ProjectDialog::_project_path_selected));
+			add_sibling(fdialog_project);
+		} break;
 	}
 }
 
@@ -967,21 +975,14 @@ ProjectDialog::ProjectDialog() {
 	Control *spacer = memnew(Control);
 	spacer->set_h_size_flags(Control::SIZE_EXPAND_FILL);
 	default_files_container->add_child(spacer);
-
-	fdialog_project = memnew(EditorFileDialog);
-	fdialog_project->set_previews_enabled(false); //Crucial, otherwise the engine crashes.
-	fdialog_project->set_access(EditorFileDialog::ACCESS_FILESYSTEM);
 	fdialog_install = memnew(EditorFileDialog);
 	fdialog_install->set_previews_enabled(false); //Crucial, otherwise the engine crashes.
 	fdialog_install->set_access(EditorFileDialog::ACCESS_FILESYSTEM);
-	add_child(fdialog_project);
 	add_child(fdialog_install);
 
 	project_name->connect(SceneStringName(text_changed), callable_mp(this, &ProjectDialog::_project_name_changed).unbind(1));
 	project_path->connect(SceneStringName(text_changed), callable_mp(this, &ProjectDialog::_project_path_changed).unbind(1));
 	install_path->connect(SceneStringName(text_changed), callable_mp(this, &ProjectDialog::_install_path_changed).unbind(1));
-	fdialog_project->connect("dir_selected", callable_mp(this, &ProjectDialog::_project_path_selected));
-	fdialog_project->connect("file_selected", callable_mp(this, &ProjectDialog::_project_path_selected));
 	fdialog_install->connect("dir_selected", callable_mp(this, &ProjectDialog::_install_path_selected));
 	fdialog_install->connect("file_selected", callable_mp(this, &ProjectDialog::_install_path_selected));
 

```

**Comment by jsjtxietian** [comment]
Yes I forgot to check the output, sorry :)

File: editor/project_manager/project_dialog.cpp [hunk 1]
```diff
@@ -787,6 +787,14 @@ void ProjectDialog::_notification(int p_what) {
 			project_browse->set_icon(get_editor_theme_icon(SNAME("FolderBrowse")));
 			install_browse->set_icon(get_editor_theme_icon(SNAME("FolderBrowse")));
 		} break;
+		case NOTIFICATION_READY: {
+			fdialog_project = memnew(EditorFileDialog);
+			fdialog_project->set_previews_enabled(false); //Crucial, otherwise the engine crashes.
```
Comment (KoBeWi) [inline editor/project_manager/project_dialog.cpp:792]:
```suggestion
			fdialog_project->set_previews_enabled(false); // Crucial, otherwise the engine crashes.
```

**Review by KoBeWi — APPROVED** [review]

File: editor/project_manager/project_dialog.cpp (hunk 1 above)
Comment (jsjtxietian) [reply editor/project_manager/project_dialog.cpp:792]: Thanks

**Comment by akien-mga** [comment]
Thanks!
