### PR TITLE
Show a warning toast when saving a large text-based scene

### LINKED ISSUE #29381: Add warning/docs for .res/.tres for binary files
We use the PckPacker in our project to add image resources at runtime, but they waste a lot of space when not compressed.

There should be a way to compress the .pck files made with PckPacker, like the .pck files made with the editor.

### LINKED ISSUE #33379: An abnormal increase in scene size when saving binary data in text scene file (often as a result of making resources like FontFile unique)
**Godot version:** 3.2 alpha 3

**Issue description:** I use a blender 2.8 and a standard exporter of gltf.
At the output, the scene.glb size is 1.6 mb. But while maintaining the scene.tscn, the same scene weighs 20 mb!

**Steps to reproduce:** Open scene.glb and save scene.tscn

**Minimal reproduction project:** 
[Example.zip](https://github.com/godotengine/godot/files/3812374/Example.zip)

### PR DESCRIPTION
**Pull request by Calinou**
Text-based scenes that contain large amounts of Base64-encoded binary data are slower to save and load. Their binary resources should be moved to separate files, or the binary `.scn` format should be used instead.

The size threshold is defined at 500 KB. It's technically possible for a text-based scene with no embedded binary data to be larger than that, but it's unlikely.

This closes https://github.com/godotengine/godot/issues/29381 and closes https://github.com/godotengine/godot/issues/33379. See also https://github.com/godotengine/godot/issues/50029.

**Testing project:** [test_voxelgi.zip](https://github.com/godotengine/godot/files/7323822/test_voxelgi.zip)

## Preview

image

## TODO

- [ ] ~~Only display this warning dialog once per saved scene in an editor session.~~
  - Skipped for now, as we now have a project setting to disable the warning.
- [x] Make this warning disableable in the Project Settings in case a large text-based scene is actually needed.
  - This is in the Project Settings so that all team members automatically have the warning disabled if desired.

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -1728,6 +1728,17 @@ void EditorNode::_save_scene(String p_file, int idx) {
 		}
 		editor_data.set_scene_modified_time(idx, FileAccess::get_modified_time(p_file));
 
+		if (p_file.ends_with(".tscn") || p_file.ends_with(".tres")) {
```
Comment (KoBeWi) [inline editor/editor_node.cpp:1731]: You can use `get_extension()`.

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -1728,6 +1728,17 @@ void EditorNode::_save_scene(String p_file, int idx) {
...
+			FileAccessRef f = FileAccess::open(p_file, FileAccess::READ);
+			const int file_size = f->get_length();
+			if (file_size >= 524'288) {
+				// File is larger than 500 KB, likely because it contains binary data serialized as Base64.
+				// This is slow to save and load, so warn the user.
+				show_warning(
+						vformat(TTR("The text-based scene at path \"%s\" is large on disk (%d KB), likely because it has embedded binary data.\nThis slows down scene saving and loading.\nConsider saving its binary subresource(s) to a binary `.res` file or saving the scene as a binary `.scn` file."), p_file, file_size / 1024));
```
Comment (KoBeWi) [inline editor/editor_node.cpp:1738]: Not sure why is it broken into 2 lines like this.

File: editor/editor_node.cpp [hunk 3]
```diff
@@ -1728,6 +1728,17 @@ void EditorNode::_save_scene(String p_file, int idx) {
 		}
 		editor_data.set_scene_modified_time(idx, FileAccess::get_modified_time(p_file));
 
+		if (p_file.ends_with(".tscn") || p_file.ends_with(".tres")) {
+			FileAccessRef f = FileAccess::open(p_file, FileAccess::READ);
+			const int file_size = f->get_length();
+			if (file_size >= 524'288) {
+				// File is larger than 500 KB, likely because it contains binary data serialized as Base64.
+				// This is slow to save and load, so warn the user.
```
Comment (KoBeWi) [inline editor/editor_node.cpp:1736]: Doesn't this comment basically repeat the warning message?

**Comment by KoBeWi** [comment]
I agree there should be a project setting, you could even add a checkbox like I did in #53400

As for doing it once per scene per session, it's easy to implement, but I imagine people will either fix their scene or ignore this warning forever. So either it should not be limited or you should be able to disable it permanently for a scene (you could store the info in the project metadata). But I'd leave it like now and wait until someone requests it to be changed.

**Comment by lyuma** [comment]
Just wondering... It has OK and Copy Text. shouldn't there be a Cancel button?

Otherwise how can you go back and extract the resources from your scene that should be binary?

**Comment by KoBeWi** [comment]
This is just a default information dialog, it doesn't do anything.

**Comment by Calinou** [comment]
> Just wondering... It has OK and Copy Text. shouldn't there be a Cancel button?
> 
> Otherwise how can you go back and extract the resources from your scene that should be binary?

The dialog is displayed *after* the scene is saved, as we don't know in advance how large the saved file will be.

**Comment by reduz** [comment]
I am still unsure whether this should be done or we should simply scan for specific nodes in the scene tree that may contain binary data (like MeshInstance, or VoxelGI/Lightmap without embedded resource) and warn the user which actual nodes/resources have large binary data, because sometimes this is done by mistake and then its not clear why it happens.

**Comment by Zireael07** [comment]
@reduz  why not both?

**Comment by Calinou** [comment]
Rebased and tested again, it works as expected. See OP for updated screenshots.

File: editor/editor_node.cpp [hunk 4]
```diff
@@ -1839,6 +1839,19 @@ void EditorNode::_save_scene(String p_file, int idx) {
...
 
+		if (GLOBAL_GET("editor/general/warn_on_saving_large_text_resources")) {
+			if (p_file.ends_with(".tscn") || p_file.ends_with(".tres")) {
+				Ref<FileAccess> fa = FileAccess::open(p_file, FileAccess::READ);
+				const uint64_t file_size = fa->get_length();
+				if (file_size >= 524'288) {
+					// File is larger than 500 KB, likely because it contains binary data serialized as Base64.
+					// This is slow to save and load, so warn the user.
+					EditorToaster::get_singleton()->popup_str(
+							vformat(TTR("The text-based scene or resource at path \"%s\" is large on disk (%d KB), likely because it has embedded binary data.\nThis slows down scene saving and loading.\nConsider saving its binary subresource(s) to a binary `.res` file or saving the scene as a binary `.scn` file.\nThis warning can be disabled in the Project Settings (Editor > General > Warn On Saving Large Text Resources)."), p_file, file_size / 1024), EditorToaster::SEVERITY_WARNING);
```
Comment (aaronfranke) [inline editor/editor_node.cpp:1850]: The text here should be changed to be more similar to the doc text in ProjectSettings.xml, with a mention of moving binary resources outside of the scene as the first solution.

**Comment by Zireael07** [comment]
The issue this is aiming to fix keeps popping up - can this be merged sooner rather than later?

**Review by KoBeWi — APPROVED** [review]
The biggest scene in my project is over 1 MB big, due to huge TileMapLayer. Only around 1% of the scenes are big enough to trigger the warning though, so I think the threshold is fine. Maybe it's different in 3D projects, idk.

It's a returning issue and this PR is fine as initial solution (even if we don't improve it afterwards).

**Comment by akien-mga** [comment]
The class ref is out of ordering, needs to be moved around.

I'm noting this is creating the `editor/general` Project Settings category which didn't exist previously (so it will be the only setting in it). It's not ideal, but I don't have a better suggestion currently.

This does feel like something that might be better suited as an actual editor setting, with project setting override optionally, but to do it properly that would require #69012 to be merged first.
Maybe we can make a note of it and if #69012 gets merged before 4.4, we move this one to an editor setting?

**Comment by KoBeWi** [comment]
Everything under `editor/` category should likely be editor setting, so it tracks itself right now.

**Comment by fire** [comment]
> Show a warning dialog

Can this be a toast? It would not be fun to use this on trees of large assets.

**Comment by RedMser** [comment]
> This does feel like something that might be better suited as an actual editor setting, with project setting override optionally, but to do it properly that would require https://github.com/godotengine/godot/pull/69012 to be merged first.
> Maybe we can make a note of it and if https://github.com/godotengine/godot/pull/69012 gets merged before 4.4, we move this one to an editor setting?

Per-project overrides of editor settings were merged, so maybe this setting should be moved to be an editor setting now.

**Comment by Calinou** [comment]
> Per-project overrides of editor settings were merged, so maybe this setting should be moved to be an editor setting now.

I changed the PR to use an editor setting and [`FileAccess::get_size()`](https://github.com/godotengine/godot/pull/83538) as an optimization.

File: doc/classes/EditorSettings.xml [hunk 5]
```diff
@@ -783,6 +783,10 @@
 			If [code]true[/code], when saving a file, the editor will rename the old file to a different name, save a new file, then only remove the old file once the new file has been saved. This makes loss of data less likely to happen if the editor or operating system exits unexpectedly while saving (e.g. due to a crash or power outage).
 			[b]Note:[/b] On Windows, this feature can interact negatively with certain antivirus programs. In this case, you may have to set this to [code]false[/code] to prevent file locking issues.
 		</member>
+		<member name="filesystem/on_save/warn_on_saving_large_text_resources" type="bool" setter="" getter="">
+			If [code]true[/code], displays a warning toast message when saving a text-based scene or resource that is larger than 500 KB on disk. This is typically caused by binary subresources being embedded as text, which results in slow and inefficient conversion to text. This in turn impacts scene saving and loading times.
```
Comment (AThousandShips) [inline doc/classes/EditorSettings.xml]:
```suggestion
			If [code]true[/code], displays a warning toast message when saving a text-based scene or resource that is larger than 500 kB on disk. This is typically caused by binary subresources being embedded as text, which results in slow and inefficient conversion to text. This in turn impacts scene saving and loading times.
```
For kilo the SI prefix is k, or use `KiB` as that's what it checks

**Review by AThousandShips — APPROVED** [review]

**Comment by Repiteo** [comment]
Needs rebase

**Comment by Calinou** [comment]
Rebased and tested again, it works as expected. The warning now correctly shows up for resources, not just scenes.

**Comment by Repiteo** [comment]
Thanks!
