### PR TITLE
Fix children visibility check

### LINKED ISSUE #59003: Controls not laid properly with FlowContainer in another container
### Godot version

7866c98

### System information

W10

### Issue description

When you have e.g. HFlowContainer inside VBoxContainer, other nodes will overlap the HFlow in specific cases:
godot windows tools 64_0dvXTtSTuV
This is somewhat similar to #58630, but applies only to FlowContainer and also happens on master.

CC @geom

### Steps to reproduce

1. Put FlowContainer into another container
2. Put another node in the container
3. Toggle visibility of their parent

### Minimal reproduction project

[Control.tscn.txt](https://github.com/godotengine/godot/files/8227808/Control.tscn.txt)
Scene from the GIF.

### PR DESCRIPTION
**Pull request by taigi100**
Bugfix for #59003.

Seems to work by checking if the child is simply visible instead of visible in tree. Not sure what other effects this might have, need some guidance :) 

@Geometror

*Bugsquad edit:*
- Fixes #59003

### CODE REVIEW

**Review by Geometror — APPROVED** [review]
Tested and it looks like your PR fixes the issue.
The only problem with this solution is that if a parent of a child node is invincible(e.g. the flow container itself), the minimum size of the flow container's children is still calculated, which should be avoided considering performance.
But I guess this isn't too bad, so this could be merged it for now(@KoBeWi Whats your opinion on this?). I was thinking about changing how/at which point the cached_size is calculated (or whether we should cache the size at all). Unfortunately, I can't work on that right now (probably in about two weeks).

**Comment by taigi100** [comment]
If you have any more specific ideas on how to improve performance, I can attempt an implementation a bit earlier I guess, however I'd need a lot more guidance I think :-?

As a very fast look at it (on how to fix it, not how to maybe improve the overall implementation) - I'd somehow add a check to ignore children of invisible parents which are located under the FlowContainer (e.g. HBoxContainer in my pic) - however, i have no clue how to do that and if it would be worth the performance tradeoff.

**Comment by KoBeWi** [comment]
Looks like some visibility propagation magic. The fix is correct. You can add this at the beginning of the `_resort()`:
```C++
if (!is_visible_in_tree()) {
	return;
}
```
It will avoid resorting when container is invisible, but still works correctly.

File: scene/gui/flow_container.cpp [hunk 1]
```diff
@@ -39,6 +39,11 @@ struct _LineData {
 };
 
 void FlowContainer::_resort() {
+	// avoid resorting if invisible.
```
Comment (KoBeWi) [inline scene/gui/flow_container.cpp:42]:
```suggestion
	// Avoid resorting if invisible.
```

**Comment by KoBeWi** [comment]
> There is still a small issue (not sure if it is one): If all the children of the HFlowContainer are invisible, then the flow container still seems to take space (around 1px)

This is caused by separation property in BoxContainer. It's 4px by default.

**Review by KoBeWi — APPROVED** [review]
Looks good. Remember to [squash the commits](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase).

We could do the same in BoxContainer actually, even if it doesn't really need it. But that's for another PR.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.
