### PR TITLE
Fixes folding of blank lines

### LINKED ISSUE #13339: code folding folds last empty lines
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
master 6aa331e

**Issue description:**

1. code folding folds last empty lines
    * should not fold empty lines
2. can't click unfold icons
    * last line should be visible beyond scroll bar

**Steps to reproduce:**
code folding

**Link to minimal example project:**

### PR DESCRIPTION
**Pull request by groud**
Fixes #13339 (Only the first point but the second one is a duplicate)

Warning: I renamed get_whitespace_level to get_ident_level as it makes more sense. I break a little bit the compatibility but TextEdit is more an editor class that a truely useful in project class.

### CODE REVIEW

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -4491,16 +4491,17 @@ int TextEdit::num_lines_from(int p_line_from, int unhidden_amount) const {
 	return num_total;
 }
 
-int TextEdit::get_whitespace_level(int p_line) const {
```
Comment (MoriMalandro) [inline scene/gui/text_edit.cpp]: Is this needed?

Comment (MoriMalandro) [reply scene/gui/text_edit.cpp]: (Since Noshyaar keeps closing this, I am going to continue to post it until one thread remains visible for discussion, no need to censor)



Lead developer sent this message after a user was giving his honest feedback via this [reddit thread](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqk9nel/).

They also said (I kid you not) -- giving feedback is "**bullying**",  a "**professional whiner**", and "**ranting**". Reduz's passive aggressive tone and insulting behavior is rampant there.  I already terminated my patreon account because of this, and not saying you should either (FLOSS projects) are great, however, for the lead developer to act like this towards people giving feedback.. is not okay!

Let me re-iterate, not saying that you should stop giving feedback, but I just want this message to be seen across github and reach as far as possible. Because this kind of communication and how the lead developer treats a regular Godot developer is not right at all. I've never seen this behavior from a FLOSS project lead developer.  It's a shame, because the guy giving feedback is just a random person anyway, and the way the project managers and lead developers took it so personally like it was an attack (when it wasn't), means the lead developers/contributors are possibly not viewing your issues with the right mindset.  

Also, after reading the last paragraph from [this post by akien](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqlqj2v/)
> From here on, we will avoid responding to xxx's threads on the various Godot communities, and focus instead on the huge amount of constructive feedback and bug reports that we get from other users. This will likely overlap with some of the issues mentioned above, which will thus be fixed eventually, but we won't accept being bullied into working on them now when we have different priorities. Users are free to disagree with our priorities, but in the end the contributors are the ones making the call.

He's saying they will now favor/prioritize issues based on the user reporting it, and not the issue itself. (Extreme prejudice), which will not be good for the project because the issue should be irrelevant to the user reporting it. Just because if a user who has a snotty attitude that is reporting a huge client crash error, doesn't mean that client crash error should not be taken lightly.



He's also stating that anyone giving hard feedback is now "bullying" them. Which is not true whatsoever.

Just wanting to post this to get the word out there, hopefully some things change. @reduz @akien-mga  This is just unbelievable :(
