### PR TITLE
VisualScript: Fix mislabeled logic operators #49412

### LINKED ISSUE #49412: Visual Script - Godot 4 - Logic Operators Mislabeled
**Godot version:**

v4.0.dev.calinou.cb8244273

**OS/device including version:**

Ubuntu 20.10/Atermiter dual Xeon motherboard, gtx 970 nvidia package 460

**Issue description:**

Pulled in a logic operator and it did not match selection. See attached GIF. 

**Steps to reproduce:**
Pull in logic operators and, or, not,  etc and notice the wrong operator gets dragged in.

**Minimal reproduction project:**

Will create if needed.
logic_operators_bug

### PR DESCRIPTION
**Pull request by m44615**
Fix #49412

Logic operators appeared with a wrong label.

### CODE REVIEW

File: modules/visual_script/visual_script_nodes.cpp [hunk 1]
```diff
@@ -946,39 +946,69 @@ static const char *op_names[] = {
 };
 
 String VisualScriptOperator::get_caption() const {
-	static const char32_t *op_names[] = {
+	switch (op){
```
Comment (Calinou) [inline modules/visual_script/visual_script_nodes.cpp:949]: Fix code style to comply with the guidelines (otherwise, static checks will fail on CI):

```suggestion
	switch (op) {
```

**Review by Calinou — DISMISSED** [review]

File: modules/visual_script/visual_script_nodes.cpp [hunk 2]
```diff
@@ -946,39 +946,68 @@ static const char *op_names[] = {
...
+			return U"A or B";
+		case Variant::OP_XOR:
+			return U"A xor B";
+		case Variant::OP_NOT:
+			return U"not A";
+		case Variant::OP_IN:
+			return U"A in B";
+
+		default:
+			return U"Unknown node";
```
Comment (qarmin) [inline modules/visual_script/visual_script_nodes.cpp:1009]: Here should be probably `ERR_FAIL` which will show an error/

**Review by qarmin — APPROVED** [review]

File: modules/visual_script/visual_script_nodes.cpp [hunk 3]
```diff
@@ -946,39 +946,71 @@ static const char *op_names[] = {
...
+		case Variant::OP_DIVIDE:
+			return U"A \u00F7 B";
+		case Variant::OP_NEGATE:
+			return U"\u00AC A";
+		case Variant::OP_POSITIVE:
+			return U"+ A";
+		case Variant::OP_MODULE:
+			return U"A mod B";
+		/*case Variant::OP_STRING_CONCAT:
+				return U"A .. B";*/
```
Comment (akien-mga) [inline modules/visual_script/visual_script_nodes.cpp:980]: You can remove that one if it's no longer in Variant.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
