### PR TITLE
Fix inability to use ResourceLoader in C# after threaded load in GDScript

### LINKED ISSUE #92798: Unable to use ResourceLoader in C# after threaded load in GDScript
### Tested versions

- Reproducible in: 4.2.2.mono, 4.3-beta1.mono

### System information

Godot v4.3.beta1.mono - Windows 10.0.26120 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.5222) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Originally reported here: https://discord.com/channels/212250894228652034/389794884585914368/1247671144983564370

After loading a resource with `ResourceLoader.load_threaded_request`. `load_threaded_get_status` and `load_threaded_get` in GDScript, `ResourceLoader` becomes unusable in .NET, failing with 

```
ERROR: System.TypeInitializationException: The type initializer for 'Godot.ResourceLoader' threw an exception.
 ---> Godot.GodotObject+NativeMethodBindNotFoundException: Unable to find the native method bind. (Method 'ResourceLoader.load_threaded_get_status')
   at Godot.GodotObject.ClassDB_get_method_with_compatibility(StringName type, StringName method, UInt64 hash) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/GodotObject.base.cs:line 258
   at Godot.ResourceLoader..cctor() in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/ResourceLoader.cs:line 80
   --- End of inner exception stack trace ---
   at Godot.ResourceLoader.Load(String path, String typeHint, CacheMode cacheMode) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/ResourceLoader.cs:line 118
   at Godot.ResourceLoader.Load[T](String path, String typeHint, CacheMode cacheMode) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Extensions/ResourceLoaderExtensions.cs:line 27
   at Godot.GD.Load[T](String path) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs:line 129
   at GodotDotnetThreadedLoad.SceneToLoad._Ready() in C:\Users\x-i-l\source\repos\_godot_bugs\godot-dotnet-threaded-load\SceneToLoad.cs:line 9
   at Godot.Node.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Node.cs:line 2401
   at GodotDotnetThreadedLoad.SceneToLoad.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in C:\Users\x-i-l\source\repos\_godot_bugs\godot-dotnet-threaded-load\.godot\mono\temp\obj\Debug\Godot.SourceGenerators\Godot.SourceGenerators.ScriptMethodsGenerator\GodotDotnetThreadedLoad.SceneToLoad_ScriptMethods.generated.cs:line 40
   at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 24
   at: void Godot.NativeInterop.ExceptionUtils.LogException(System.Exception) (/root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:113)
```

Can be worked around by mentioning `ResourceLoader` beforehand (for example in an autoload)

### Steps to reproduce

- Do threaded loading in GDScript before C#'s ResourceLoader type was ever mentioned (so initialized)
- Try to use C# ResourceLoader
- Observe the `TypeInitializationException` error message

### Minimal reproduction project (MRP)

https://github.com/xill47/godot-dotnet-threaded-load

Workaround: https://github.com/xill47/godot-dotnet-threaded-load/tree/workaround

### PR DESCRIPTION
**Pull request by Hilderin**
Fixes #92798 

As @raulsntos pointed out, the problem was from the modification of the default array. The hash of the method changed after the first call in GDScript.

I modified the method `ResourceLoader::load_threaded_get_status` to never modify the default array.

I search for `DEFVAL(Array())` through all the code base and only found one another place where the default array was modified: `OS::execute`. I modified this method as well.

I was able to reproduce the problem and tested the correction with with the MRP project.

### CODE REVIEW

File: core/core_bind.cpp [hunk 1]
```diff
@@ -55,8 +55,11 @@ Error ResourceLoader::load_threaded_request(const String &p_path, const String &
 ResourceLoader::ThreadLoadStatus ResourceLoader::load_threaded_get_status(const String &p_path, Array r_progress) {
 	float progress = 0;
 	::ResourceLoader::ThreadLoadStatus tls = ::ResourceLoader::load_threaded_get_status(p_path, &progress);
-	r_progress.resize(1);
-	r_progress[0] = progress;
+	// Default array should never be modified, it causes hash of the method to change.
+	if (r_progress != DEFVAL(Array())) {
```
Comment (AThousandShips) [inline core/core_bind.cpp:59]: Why the use of `DEFVAL` here? It's just a helper macro it has no special meaning

**Comment by AThousandShips** [comment]
I don't think this is an appropriate solution to this problem, there's no way to detect if it's the default argument as it's not just an empty array but a specific instance

This will break compatibility, as the method is clearly intended to support empty arrays (or the resize wouldn't be there) so this requires a different solution

**Comment by Hilderin** [comment]
You are so right @AThousandShips, sorry for that, still learning!! I was misleading big time by the `DEFVAL`, the `== operator` redefined in `Array` and the way default value were passed in GDScript.

As an alternative solution, I created a static `_default_array` class in `ResourceLoader` and `OS` and used it as default parameter for the method and `ClassDB::bind_method`. After that, I created the method `is_same_instance` in `Array` and used it to verify if the Array received is the default value.

What do you think?

**Comment by AThousandShips** [comment]
I don't think this is a valid solution either, this should be solved on the script and engine side not the local site IMO, it's occurring in various places probably

**Comment by Hilderin** [comment]
I understand that is not a perfect solution, but maybe a temporary solution? The alternative solution would be to have multiple overloads of the methods which seems a lot of work?!? Or maybe detect in GDScript that the default parameter is an empty array and create a new instance? That seems pretty specific.

Maybe you can point me in the direction for a better solution??

**Comment by AThousandShips** [comment]
I don't know a better solution sorry, this is not a simple problem, but this is a very ad-hoc and temporary solution in my opinion and I don't think it is an appropriate one, but I'll update the tags and we'll see what the core and GDScript teams say, but I feel this is too hacky to be a proper solution

File: core/core_bind.cpp [hunk 2]
```diff
@@ -570,6 +577,7 @@ String OS::get_unique_id() const {
 }
 
 OS *OS::singleton = nullptr;
+Array OS::_default_array = Array();
```
Comment (RandomShaper) [inline core/core_bind.cpp:580]:
```suggestion
Array OS::_default_array;
```

File: core/core_bind.h [hunk 3]
```diff
@@ -50,6 +50,8 @@ namespace core_bind {
 class ResourceLoader : public Object {
 	GDCLASS(ResourceLoader, Object);
 
+	static Array _default_array;
```
Comment (RandomShaper) [inline core/core_bind.h:53]:
```suggestion
	static Array default_array;
```

File: core/core_bind.h [hunk 4]
```diff
@@ -123,6 +125,8 @@ class OS : public Object {
 
 	mutable HashMap<String, bool> feature_cache;
 
+	static Array _default_array;
```
Comment (RandomShaper) [inline core/core_bind.h:128]:
```suggestion
	static Array default_array;
```

File: core/core_bind.cpp [hunk 5]
```diff
@@ -47,6 +47,7 @@ namespace core_bind {
 ////// ResourceLoader //////
 
 ResourceLoader *ResourceLoader::singleton = nullptr;
+Array ResourceLoader::_default_array = Array();
```
Comment (RandomShaper) [inline core/core_bind.cpp:50]:
```suggestion
Array ResourceLoader::_default_array;
```

**Comment by RandomShaper** [comment]
> I don't know a better solution sorry, this is not a simple problem, but this is a very ad-hoc and temporary solution in my opinion and I don't think it is an appropriate one, but I'll update the tags and we'll see what the core and GDScript teams say, but I feel this is too hacky to be a proper solution

I've added a few style suggestions, just out of inertia. However, speaking about the issue itself, I totally agree with @AThousandShips. This needs to be discussed very carefully.

**Comment by Hilderin** [comment]
All the suggestions should be done. Let me known if more changes are needed.

**Comment by AThousandShips** [comment]
I'll try analyse this but I still think this isn't the way to solve this

**Comment by RandomShaper** [comment]
The issue is about optional output parameters. On a deeper thought, it may not be that bad to have the sort of idiom being used here for cases like this, where the bindings allow to default output parameters. As long as we are consistent, it may be a fix, at least short-term.

Ideally, though. the binding system would allow to be told an parameter is output so it automatically provides different instances if defaulted. That's pretty much the same this PR does, but making it more generic.

Ther may be other less error-prone alternatives that could be discussed.

File: core/core_bind.cpp [hunk 6]
```diff
@@ -47,6 +47,7 @@ namespace core_bind {
 ////// ResourceLoader //////
 
 ResourceLoader *ResourceLoader::singleton = nullptr;
+Array ResourceLoader::default_array;
```
Comment (raulsntos) [inline core/core_bind.cpp:50]: The default array should probably be read-only to prevent mutating the array, and if we accidentally try to mutate it we'd get an error.

Also, since all these `default_array` instances are the same (empty arrays), instead of having a different instance for each class, we can re-use the same instance everywhere. Maybe we can put it in `Array` (i.e.: `Array::default` or `Array::empty`).

Comment (Hilderin) [reply core/core_bind.cpp]: Finally took the time to update this PR with your suggestions. I had some difficulties to call `make_read_only` on a static field without static constructors so I added a static method `Array::create_read_only` and used it to create `Array::default`. If you know a better way, I'll be glad to implement it.

File: core/variant/array.cpp [hunk 7]
```diff
@@ -49,6 +49,10 @@ class ArrayPrivate {
 	ContainerTypeValidate typed;
 };
 
+// Array to use in optional parameters on methods.
+// Ex: DEFVAL(Array::default_array)
+Array Array::default_array = Array::create_read_only();
```
Comment (RandomShaper) [inline core/variant/array.cpp:54]: I'd suggest declaring this instead in a file belonging to the binding system, renamed to `default_out_array_arg`, so instead of having the somewhat blurry concept of a default array, we'd have the concept of array-for-default-arguments-in-bindings.

Then, there could be a macro like this, that can be used in bindings to make the syntax a bit less jarring:
`#define DEF_OUT_ARRAY DEFVAL(default_out_array_arg)`

The names are just a suggestion to illustrate my point. I'm not advocating for them as they are exactly written here.

Comment (Hilderin) [reply core/variant/array.cpp]: I moved the default array in ClassBD. I'm not that familiar with the binding system but it's seems a good place.

I create the `DEFVAL_ARRAY` macro. I did not used `OUT` in the name because it could be used as an input default parameter also.

Also, putting the code in `ClassDB` made a lot more sense to create the function `ClassDB::is_default_array_arg` which could be used to verify if an array is the default value.

Let me know what you think about these changes.

Comment (RandomShaper) [reply core/variant/array.cpp]: Looks great!

**Comment by Hilderin** [comment]
Rebased to fix conflict with master.

**Review by RandomShaper — APPROVED** [review]
Reiterating a better solution may be worked on in the future, this is fine to me as it's clean enough and fixes a pretty unfortunate issue.

**Review by AThousandShips — APPROVED** [review]

File: core/core_bind.cpp [hunk 8]
```diff
@@ -55,8 +56,11 @@ Error ResourceLoader::load_threaded_request(const String &p_path, const String &
 ResourceLoader::ThreadLoadStatus ResourceLoader::load_threaded_get_status(const String &p_path, Array r_progress) {
 	float progress = 0;
 	::ResourceLoader::ThreadLoadStatus tls = ::ResourceLoader::load_threaded_get_status(p_path, &progress);
-	r_progress.resize(1);
-	r_progress[0] = progress;
+	// Default array should never be modified, it causes hash of the method to change.
```
[the remark this answers is not in the document]
Comment (Hilderin) [reply core/core_bind.cpp]: Done!

**Comment by akien-mga** [comment]
Thanks!
