### PR TITLE
Fix "Make Scene Root" deleting previous root whenever focusing another scene

### LINKED ISSUE #24484: Make Scene Root deletes other nodes from the scene
**Godot version:** 3.1 alpha 3

**OS/device including version:** Windows 10 64-bit

**Issue description:** Using "Make Scene Root" deletes other nodes from the scene.

**Steps to reproduce:**

Create any scene with one node. Instantiate it in some other scene. Create other random node in the first scene. Click "Make Scene Root". Everything looks good so far. Save the scene, switch to another scene, switch back to this scene and all other nodes but the root node are gone.

### LINKED ISSUE #27222: disapperaring nodes after reparenting
**Godot version:**
3.1

**OS/device including version:**
Windows 7 SP1

**Issue description:**
Editor issue | Persiting node | Reparenting | saving scene | High impact | reproducable

Child nodes dissapears after reparenting Character scene.
 Should not delete nodes after reparenting

**Steps to reproduce:**
1, Open Main and Character scene.
2, Select Character scene. Add child node Position2d to character.
3, Select Position2d - Make scene root.
4, Save Character scene. - Important step
5, Switch to Main scene and switch back to character.
6, Character scene will be empty. Only Position2d node will be available.

Note: I reparented couple of times and saved the scene. Godot crashed :(
Thank you.

[Snow31_disappearingNodes.zip](https://github.com/godotengine/godot/files/2981792/Snow31_disappearingNodes.zip)

### PR DESCRIPTION
**Pull request by bojidar-bg**
Hopefully fixes #24484 and fixes #27222.

### CODE REVIEW

File: editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -728,14 +727,13 @@ void SceneTreeDock::_tool_selected(int p_tool, bool p_confirm_override) {
...
 			editor_data->get_undo_redo().add_undo_method(node->get_parent(), "add_child", node);
+			editor_data->get_undo_redo().add_undo_method(node->get_parent(), "move_child", node, node->get_index());
 			editor_data->get_undo_redo().add_undo_method(root, "set_owner", (Object *)NULL);
 			editor_data->get_undo_redo().add_undo_method(node, "set_owner", root);
-
 			_node_replace_owner(root, root, root, MODE_UNDO);
 
 			editor_data->get_undo_redo().add_do_method(scene_tree, "update_tree");
 			editor_data->get_undo_redo().add_undo_method(scene_tree, "update_tree");
-			editor_data->get_undo_redo().add_undo_reference(root);
```
Comment (bojidar-bg) [inline editor/scene_tree_dock.cpp]: This line was the main culprit: the other are mostly stylistic/correctness changes.

`add_undo_reference` adds a reference which should persist as long as the undo history does. Unfortunately, the `root` node is preserved, not scrapped, so it actually "outlives" the undo history.

A cool side effect of this was that doing "Make Scene Root" twice, once on a node and then again on the old root node, followed by changing the scene would crash the editor.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.
