### PR TITLE
Fix theming for `EditorPropertyArray` icons

### LINKED ISSUE #116085: VisualShader IntParameter node  hint: Enum issues
### Tested versions

- Reproducible in: v4.7.dev.custom_build [56f3e2611], v4.6.stable.official [89cea1439], v4.5.1.stable.official [f62fdbde1], v4.4.1.stable.official [49a5bc7b6]

I've not tested older ones

### System information

Godot v4.6.stable - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Fri, 30 Jan 2026 23:06:21 +0000 on Wayland - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4080 SUPER (nvidia; 590.48.01) - AMD Ryzen 9 7950X3D 16-Core Processor (32 threads) - 61.90 GiB memory

### Issue description

The visual shader `IntParameter` node `hint: Enum` shows broken icons in the `PackedStringArray` property editor and the input fields lose focus each keystroke

Image

### Steps to reproduce

Create a visual shader and add an `IntParameter` node with `hint: Enum`

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Chaosus**
- Fix https://github.com/godotengine/godot/issues/116085

### CODE REVIEW

File: editor/inspector/editor_properties_array_dict.cpp [hunk 1]
```diff
@@ -774,6 +774,19 @@ Node *EditorPropertyArray::get_base_node() {
 
 void EditorPropertyArray::_notification(int p_what) {
```
Comment (bruvzg) [inline editor/inspector/editor_properties_array_dict.cpp:775]: `EditorPropertyDictionary` likely should have the same change, since it's also using buttons with icons inside its slots.

Comment (Chaosus) [reply editor/inspector/editor_properties_array_dict.cpp:775]: Done!

**Review by KoBeWi — APPROVED** [review]
Looks like the icons are assigned both when creating the buttons and when receiving the theme changed, however only one of them is happening at a time (I guess it depends on the order things are done). This can be properly solved only by using `NOTIFICATION_THEME_CHANGED` of the buttons themselves; this fix is fine for now.
