### PR TITLE
Fixes issue where failed start of OpenXR causes issues

### LINKED ISSUE #64584: Project refuses to start when using openxr in linux
### Godot version

4.0.alpha14

### System information

Arch linux, AMD 5700xt, swaywm/wayland

### Issue description

I enabled xr support per the current latest documentation: https://docs.godotengine.org/en/latest/tutorials/xr/setting_up_xr.html

A pop up window  says 
```
"Your video card driver does not support any of the supported Vulkan or OpenGL versions.
Please update your drivers or if you have a very old or integrated GPU, upgrade it.
If you have updated your graphics drivers recently, try rebooting." 
```
I have rebooted since my last update.

The output in terminal says:
```
 ~/src/ITF  on main ⇡1 !5  godot4                                                                  255 ↵  took 9s
VR Server (v1659988962)

Using breakpad crash handler
Setting breakpad minidump AppID = 250820
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
OpenXR: Running on OpenXR runtime:  SteamVR/OpenXR   0.1.0
Godot Engine v4.0.alpha14.official.106b68050 - https://godotengine.org
OpenXR: XrGraphicsRequirementsVulkan2KHR:
 - minApiVersionSupported:  1.0.0
 - maxApiVersionSupported:  1.2.0
OpenXR: Failed to obtain vulkan physical device [ XR_ERROR_RUNTIME_FAILURE ]
ERROR: Condition "err != OK" is true. Returning: ERR_CANT_CREATE
   at: _window_create (drivers/vulkan/vulkan_context.cpp:1444)
ERROR: Can't create a Vulkan window
   at: _create_window (platform/linuxbsd/display_server_x11.cpp:4554)
```

This does not happen if XR-->Shaders is enabled but XR->OpenXR is still disabled

### Steps to reproduce

Written above

### Minimal reproduction project

_No response_

### LINKED ISSUE #71266: [Beta 11] `Your video card driver does not support selected Vulkan version.` error given when OpenXR is enabled.
### Godot version

4.0 Beta 11

### System information

Windows 10 version 22H2, GeForce Game Ready Driver Version 528.02, GTX 1070

### Issue description

Since Beta 11 this error is given whenever a project is run in the forward+ renderer with OpenXR enabled. This error is not present with Beta 10 and previous versions.
image

I've tested with projects created in previous versions as well as the current version (Beta 11)

### Steps to reproduce

Create project, enable OpenXR in project settings, and run.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by BastiaanOlij**
We recently changed the way OpenXR manages extensions. This resulted in graphics API extension not being cleaned up if OpenXR was requested but failed to start. When using the Vulkan graphics API this results in the Vulkan hooks remaining in place causing a number of flow on issues.

We're now properly cleaning up the graphics API extension on failure and presenting a message to the user that while OpenXR was requested, it failed to start.

OpenXR will fail to start if:
- No OpenXR runtime is installed
- SteamVR is used but no headset is connected
- WMR is used natively as it only supports DirectX.

This likely fixes #71266 and fixes #64584

### CODE REVIEW

File: modules/openxr/register_types.cpp [hunk 1]
```diff
@@ -111,6 +111,10 @@ void initialize_openxr_module(ModuleInitializationLevel p_level) {
 			ERR_FAIL_NULL(openxr_api);
 
 			if (!openxr_api->initialize(Main::get_rendering_driver_name())) {
+				OS::get_singleton()->alert("OpenXR was requested but failed to start.\n"
+										   "Please check if your HMD is connected.\n"
+										   "When using Windows MR please note that WMR only has DirectX support, make sure SteamVR is your default OpenXR runtime.\n"
+										   "Godot will start in normal mode.\n");
```
Comment (BastiaanOlij) [inline modules/openxr/register_types.cpp:117]: We may wish a setting whether Godot should start without XR support, or just exit. 
Exiting may be a better default.

**Comment by BastiaanOlij** [comment]
Ping @akien-mga , should probably merge this one?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
