### PR TITLE
Fixed ctrl+up/down shortcut no longer working in scene tree

### LINKED ISSUE #7736: Godot 3 (editor) Ctrl+Up/Down (move  node) : focus goes to other control before moving node
**Operating system or device - Godot version:**
Linux / Godot 3.0 ( 5cc63de )

**Issue description:**

Editor : Focus on scene panel , Ctrl+Up/Down is use move up/down the node.
What happen is the focus goes to other control ( [+] , [node filter edit],  ...) before actually moving the node

**Steps to reproduce:**
In scene node hierachy, select to down child node , hit Ctrl+Up 4times before selected node actually move. 

**Link to minimal example project:**
:

### PR DESCRIPTION
**Pull request by Piet-G**
Fixed ctrl+up/down shortcut no longer working in scene tree.

I'm not super happy with the way this was solved, if someone has a better idea please comment.

This fixes #7736

BTW the problem is related to #18793

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -2239,13 +2239,13 @@ void Tree::_gui_input(Ref<InputEvent> p_event) {
 			_go_left();
 		}
 
-	} else if (p_event->is_action("ui_up") && p_event->is_pressed()) {
+	} else if (p_event->is_action("ui_up") && p_event->is_pressed() && !k->get_control()) {
```
Comment (reduz) [inline scene/gui/tree.cpp]: Fix is fine, but use get_command instead of get_control, so it works for OSX users too.

**Review by reduz — DISMISSED** [review]

**Comment by DualMatrix** [comment]
Changed it to get_command instead of get_control

**Comment by akien-mga** [comment]
Thanks!
