### PR TITLE
Fix Atlas Merge Tool crash

### LINKED ISSUE #101132: Atlas Merge Tool crashes when selecting entries to merge 2
### Tested versions

Godot v4.3.stable (77dcf97d8) - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce GTX 980 Ti (NVIDIA; 32.0.15.6094) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### System information

Godot v4.3.stable (77dcf97d8) - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce GTX 980 Ti (NVIDIA; 32.0.15.6094) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

Godot crashes when I select multiple atlases to merge using the Atlas Merge Tool.  

I found [this closed issue from 2023](https://github.com/godotengine/godot/issues/75354) that seemed like the same problem.  I downloaded the MRP and everything worked fine so this doesn't seem to be the same issue.

I suspect it only crashes when you try to merge atlases that have already had their properties changed and/or used in a TileMapLayer.

### Steps to reproduce

1. Load several atlases into a Tile Set resource

2a. Define collision shapes for several tiles
and/or
2b. Setup animations for several tiles
and/or
2c. Setup terrain sets for several tiles
and/or
2d. Use tiles in a TileMapLayer node

4. Open Atlas Merge Tool

5. Hold shift and select multiple atlases

### Minimal reproduction project (MRP)

The assets used for the MRP are CC0.  They are from here: https://kevins-moms-house.itch.io/

[atlas merge bug.zip](https://github.com/user-attachments/files/18307593/atlas.merge.bug.zip)

### PR DESCRIPTION
**Pull request by nattyrice**
Fixes #101132
The fix exposed broken merging logic of atlases with animations.  
Merging now properly copies animation frame locations 
as well as correct sizing from input atlases to the merged atlas.

### CODE REVIEW

**Comment by nattyrice** [comment]
Any chance this fix could be backported to 4.3?

File: editor/plugins/tiles/atlas_merging_dialog.cpp [hunk 1]
```diff
@@ -75,15 +75,24 @@ void AtlasMergingDialog::_generate_merged(const Vector<Ref<TileSetAtlasSource>>
 
 				Rect2i new_tile_rect_in_atlas = Rect2i(atlas_offset + tile_id, atlas_source->get_tile_size_in_atlas(tile_id));
 
+				Vector2i separation = atlas_source->get_tile_animation_separation(tile_id);
+				// Because `separation` is just the space between,
+				// the vector is off by 1 in one(or both) component(s).
+				separation.x += (separation.x) ? 1 : 0;
```
Comment (groud) [inline editor/plugins/tiles/atlas_merging_dialog.cpp:81]: Those two lines look a bit weird to me. I think the rationale is kind ok but I don't understand why there's a check on whether or not `separation.x` or `separation.y` are 0. Wouldn't be `seperation += Vector2i(1,1)` be enough?

**Review by groud — CHANGES_REQUESTED** [review]
Thanks! Aside from my small comment it looks good.

File: editor/plugins/tiles/atlas_merging_dialog.cpp (hunk 1 above)
Comment (nattyrice) [reply editor/plugins/tiles/atlas_merging_dialog.cpp:81]: ~~We only need to add 1 to the animation frame movements that are intended.  For example, if there is 0 separation for the y component then we aren't selecting any frames to the left and right at all, so adding 1 to it would alter that behavior and not be what we want.~~

As I was writing the above I realize I hadn't checked the 0 separation case's result in the editor, and I should probably do that.  Sure enough,  it fails.  I haven't been reasoning about this properly.  I am leaving my crossed out comment there to hopefully explain my original train of thought.  I should have remembered to test the normal cases as well.

The use of x, y, and combined with column count isn't my normal mental model for animation sequences.  However, always adding (1,1) to `separation` doesn't quite work either.  It results in the destination position moving in a diagonal - which does match my original intuitions.

I am working out how to take the `src_rect`'s position, adjusting it to be tile coords and then multiplying it to align with the new atlas size.  

Something like this:
```
	Rect2i src_rect = atlas_source->get_tile_texture_region(tile_id, frame);
	Size2i src_size = src_rect.get_size();				
	Vector2i new_position = Vector2i(
		src_rect.position.x / src_size.width * new_texture_region_size.width,
		src_rect.position.y / src_size.height * new_texture_region_size.height
	);
```
But that isn't quite working right yet either - though I think I am on the right trail.  It leaves worrying about the frame(and separation) to the `get_tile_texture_region()` call.

If it weren't for the fact that the two merging atlases could use different sized tiles it would be a simple 1 to 1 copy.

Comment (nattyrice) [reply editor/plugins/tiles/atlas_merging_dialog.cpp:81]: I got it working.  I'll amend this PR sometime later today when I get time.  

Here is the solution I came up with:

```
for (int tile_index = 0; tile_index < atlas_source->get_tiles_count(); tile_index++) {
	Vector2i tile_id = atlas_source->get_tile_id(tile_index);
	atlas_size = atlas_size.max(tile_id + atlas_source->get_tile_size_in_atlas(tile_id));

	Rect2i new_tile_rect_in_atlas = Rect2i(atlas_offset + tile_id, atlas_source->get_tile_size_in_atlas(tile_id));

	// Copy the texture.
	for (int frame = 0; frame < atlas_source->get_tile_animation_frames_count(tile_id); frame++) {
		Rect2i src_rect = atlas_source->get_tile_texture_region(tile_id, frame);
		Vector2i new_position = new_tile_rect_in_atlas.position * new_texture_region_size;
		if (frame > 0) {
			new_position.x = src_rect.position.x / src_rect.size.width * new_texture_region_size.width;
			new_position.y = src_rect.position.y / src_rect.size.height * new_texture_region_size.height;
			atlas_size.x = MAX(frame + 1, atlas_size.x);
		}
		Rect2 dst_rect_wide = Rect2i(new_position, new_tile_rect_in_atlas.size * new_texture_region_size);
		// Enlarge image if the destination boundary falls outside its current dimensions.
		if (
			dst_rect_wide.get_end().x > output_image->get_width() 
			|| dst_rect_wide.get_end().y > output_image->get_height()) {
			output_image->crop(
				MAX(dst_rect_wide.get_end().x, output_image->get_width()), MAX(dst_rect_wide.get_end().y, 
				output_image->get_height())
			);
		}
		output_image->blit_rect(input_image, src_rect, dst_rect_wide.get_center() - src_rect.size / 2);
	}

	// Add to the mapping.
	merged_mapping[source_index][tile_id] = new_tile_rect_in_atlas.position;
}
```

Comment (nattyrice) [reply editor/plugins/tiles/atlas_merging_dialog.cpp:81]: It occurred to me to check tilesets with margins.

Comment (nattyrice) [reply editor/plugins/tiles/atlas_merging_dialog.cpp]: I was _not_ on the right trail with my last comment.  This time I took heavy inspiration from `get_tile_texture_region()` and realized a few areas where I was mistaken before.  

With that said, unfortunately I just found a new issue in my last round of checks where it fails to properly merge 4 of my larger tilesets.  I will have to look deeper into it tomorrow.

Comment (nattyrice) [reply editor/plugins/tiles/atlas_merging_dialog.cpp]: > I just found a new issue in my last round of checks where it fails to properly merge 4 of my larger tilesets. 

This issue has now been fixed.  It wasn't properly enlarging the merged atlas vertical size when a tileset had vertical animation sequences.  This has now been addressed.

Comment (nattyrice) [reply editor/plugins/tiles/atlas_merging_dialog.cpp]: @groud You were right that the the conditional addition to `separation` was weird. I was nearly completely off with how I understood things to work.  Thank you for catching that.  I believe I have the right solution now.

The addition of (1,1) could now be thought of as being handled by the `size_in_atlas` variable in [this line](https://github.com/godotengine/godot/pull/101407/commits/c028ce6511c507fce0c1274d9105b9115ee0515e#diff-e538adc7d2e82409c29dfff82a7c03b59b0e146badc4e9b1f3f0f0503a359a2aR96)

Comment (nattyrice) [reply editor/plugins/tiles/atlas_merging_dialog.cpp]: Not sure if I am the one with the authority to "resolve" this but github has it a an option and I believe I've addressed it.

**Comment by nattyrice** [comment]
> Thanks! Aside from my small comment it looks good.

I've made the changes requested(as much as they apply after several realizations) and marked it as resolved from my end. Is there anything else I need to do?

**Comment by Repiteo** [comment]
Could you rebase your PR & squash your commits? See our [pull request guidelines](https://contributing.godotengine.org/en/latest/organization/pull_requests/creating_pull_requests.html#the-interactive-rebase) for more information

**Comment by nattyrice** [comment]
> Could you rebase your PR & squash your commits? See our [pull request guidelines](https://contributing.godotengine.org/en/latest/organization/pull_requests/creating_pull_requests.html#the-interactive-rebase) for more information

My experience with git is quite limited.  I am using github desktop.  It was giving me a bunch of guff but I think I managed to get it to cooperate in the end.  

I've been waiting so long for someone to reach back on this I've completely brain dumped everything regarding it.

**Comment by AThousandShips** [comment]
The branch is still not squashed, you probably didn't force push your branch at the end with `git push --force`

**Comment by nattyrice** [comment]
> The branch is still not squashed, you probably didn't force push your branch at the end with `git push --force`

That seems to have done it.  Thank you!

**Review by Repiteo — APPROVED** [review]
Great job! All that you need to do now is change the commit message to the GitHub title, as we want to avoid directly listing issue/PR links in them (they'll cause unwanted messages otherwise)

**Comment by AThousandShips** [comment]
Seems you missed to force push again

**Comment by AThousandShips** [comment]
The commit message still references the issue and repeats it twice, please remove all of the message except "Fix Atlas Merge Tool Crash"

**Comment by AThousandShips** [comment]
@groud do you still have reservations about this? Can you approve otherwise?

**Review by groud — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉

**Comment by nattyrice** [comment]
> Congratulations on your first merged contribution! 🎉

Thanks!  I appreciate all the help through my fumbling with this.

**Comment by akien-mga** [comment]
Cherry-picked for 4.5.2.
