### PR TITLE
TextEdit scaled selection

### LINKED ISSUE #15245: TextEdit selection after scaling
**Godot version:**

Godot 3.0 (d9f7fa4)

**Issue description:**

This issue is regarding the use of TextEdit in scenes. When using full screen and stretch mode = 2D, TextEdit text selection is not working properly. Clicking on a text line in the editor puts the caret at the correct position, but selecting text seems to use mouse cursor position with an offset that gives the wrong selection.

**Steps to reproduce:**
1. Create new scene with only TextEdit element sized 
2. Select Fullscreen and set stretch mode to 2D in project settings
3. Run scene
4. Enter some text in TextEdit node
5. Select parts of the text

**Minimal reproduction project:**

[TextEditScaling.zip](https://github.com/godotengine/godot/files/1596179/TextEditScaling.zip)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

### PR DESCRIPTION
**Pull request by gabrii**
Fixes #15245

I ended up using get_viewport_transform().get_scale() *  get_global_transform().get_scale()  to manually scale mouse_position, for some reason the transform's xfrom didn't give the desired result.

It also fixes word selection and line selection, which also appeared with an offset when resized. 
And fixes a similar bug that happened when the TextEdit itself had a scale applied.

### CODE REVIEW

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -416,9 +416,10 @@ void TextEdit::_click_selection_held() {
 
 void TextEdit::_update_selection_mode_pointer() {
 	Point2 mp = Input::get_singleton()->get_mouse_position() - get_global_position();
+	Vector2 vs = get_viewport_transform().get_scale() *  get_global_transform().get_scale();
```
Comment (aaronfranke) [inline scene/gui/text_edit.cpp]: Your PR has a minor style error here, as Travis noted. Remove the second space after the `*`.

Comment (gabrii) [reply scene/gui/text_edit.cpp]: Done

**Comment by aaronfranke** [comment]
Good job, but you should squash these commits together. 

`git rebase -i HEAD~2`, change the other commits from "pick" to "fixup", then force push.

**Comment by gabrii** [comment]
Nice! Thanks! I squashed my other pull request too

**Comment by reduz** [comment]
This fix is pretty overkill, I'm surprised it got so far without being found/fixed properly. The problem is this:
```
void TextEdit::_update_selection_mode_pointer() {
	Point2 mp = Input::get_singleton()->get_mouse_position() - get_global_position();

```

Which is broken for the reasons mentioned in this PR.

However, the right way to fix it is simply replacing it by:

```
Point2 mp = get_local_mouse_pos();
```

**Comment by JA-Developer** [comment]
Hello, I have a similar error.
I just added a textedit node to the scene, I scaled it and I changed the size.
I also changed the window to 2d mode.

Then, When I try to select text on the textedit (On windows), that acts very strange.

Here is my project:

https://mega.nz/#!bd03FTrR!FOg4V7FEonIhtceqkXffoCyRnPXeHRPjuzGVxIFTgZg
