### PR TITLE
Fix separating axes for 3D cylinder-face collisions

### LINKED ISSUE #57476: [GodotPhysics] CharacterBody3D gets stuck on flat ends of static cylinders
### Godot version

4.0

### System information

Windows 10

### Issue description

Moving a CharacterBody3D along the flat end of a cylinder does not behave the same as sliding along a flat wall. The CharacterBody3D can even become stuck in place and unable to move away form the cylinder once it reaches the edges of the cylinder's flat surface
CylinderIssue
.

### Steps to reproduce

- Place a CharacterBody3D on a flat surface
- Place a cylindrical StaticBody3D collider near the CharacterBody3D, and rotate it 90° along the X axis so the bottom or top of the cylinder becomes a wall.
- In play mode move the character so that it collides with the flat end of the cylinder, and try to slide along it diagonally like a wall.

(For some reason if the cylinder has its scale set to (2.8, 2, 2.8) and is placed about 1 unit above the surface of the floor the issue is more present)

### Minimal reproduction project

[CharacterAndCylinderIssue.zip](https://github.com/godotengine/godot/files/7968362/CharacterAndCylinderIssue.zip)

### LINKED ISSUE #72198: Cylinder gets stuck on seams of static body while sliding against it.
### Godot version

v4.0.beta.custom_build [705273140]

### System information

windows 10

### Issue description

Sliding a cylinder shape against a static body will cause it to get stuck against the seams in the mesh.
stuck

### Steps to reproduce

run project and move cylinder against the static body

### Minimal reproduction project

[moveSlideStuck_beta16.zip](https://github.com/godotengine/godot/files/10522271/moveSlideStuck_beta16.zip)

### PR DESCRIPTION
**Pull request by Mknsri**
I'm not a 100% this is the correct fix, I would appreciate if someone who knows the SAT equations or the physics system better would look it over. However as far as I can see this fixes the issue and does not cause any additional ones (as far as I can see :) )

I think the issue is because when checking for lateral surfaces of a cylinder against the points on a face, the axis projection does not remove the cylinder position. This results in the axis pointing to the wrong direction and reports collisions when there shouldn't be.

I included a test scene to exhibit the issue and fix
- sandbox scene contains only the cylinder, that gets stuck without this commit
- sandbox_all scene contains a bunch of shapes rubbing against corners to make sure nothing else is broken
[sandbox.zip](https://github.com/godotengine/godot/files/14782013/sandbox.zip)

*Physics squad edit:*

- Fixes https://github.com/godotengine/godot/issues/72198

### CODE REVIEW

File: servers/physics_3d/godot_collision_solver_3d_sat.cpp [hunk 1]
```diff
@@ -1962,7 +1962,7 @@ static void _collision_cylinder_face(const GodotShape3D *p_a, const Transform3D
 
 	// Points of B, cylinder lateral surface.
 	for (int i = 0; i < 3; i++) {
-		const Vector3 &point = vertex[i];
+		const Vector3 &point = vertex[i] - p_transform_a.origin;
```
Comment (AThousandShips) [inline servers/physics_3d/godot_collision_solver_3d_sat.cpp:1965]:
```suggestion
		const Vector3 point = vertex[i] - p_transform_a.origin;
```
Can't take a reference to an expression safely

**Comment by rburing** [comment]
Great find! This fixes cylinder-trimesh collisions (cylinder against `ConcavePolygonShape3D` and cylinder against CSG shapes with collision enabled); in your PR's description I've added a link to an issue that this PR fixes.

The issue https://github.com/godotengine/godot/issues/57476 that you originally linked (which is about cylinder-cylinder) is not fixed as far as I can tell; probably you were referring to some other cases mentioned in the comments on that issue.

Here is an explanation why your fix works, for completeness: When testing for collisions between a cylinder and a triangle face, the SAT solver constructs several axes in 3D space, and for each axis it checks if it is a [*separating axis*](https://en.wikipedia.org/wiki/Hyperplane_separation_theorem). Three of the axes that are supposed to be constructed are those pointing specifically from the cylinder's tubular surface to the points of the triangle, in the normal direction of the tubular surface. If a point P belongs to the plane that (i) passes through the cylinder's center and (ii) is normal to the cylinder's axis, then the axis-to-test is given by the direction vector from the cylinder's center to the point P (which will be perpendicular to the cylinder's tubular surface). If you move the point P along the direction of the cylinder's axis, then the axis-to-test (normal to the tubular surface, pointing at P) does not change, so in general you can project P to the aforementioned plane, and take the direction vector from the center of the cylinder to the projection of P on the plane. The issue was that the plane was constructed in coordinates centered at the cylinder's origin, so the `point` should be constructed in the same way, as is done in this PR (or alternatively, the plane should be constructed in coordinates centered at the world origin, but your approach is probably better).

Please apply the change suggested by @AThousandShips (and squash your commits), and then we can happily merge this.

The same issue seems to affect box-cylinder here:

https://github.com/godotengine/godot/blob/29b3d9e9e538f0aa8effc8ad8bf19a2915292a89/servers/physics_3d/godot_collision_solver_3d_sat.cpp#L1330-L1331

As well as box-capsule here:

https://github.com/godotengine/godot/blob/29b3d9e9e538f0aa8effc8ad8bf19a2915292a89/servers/physics_3d/godot_collision_solver_3d_sat.cpp#L1216-L1222

Please try testing and fixing those in the same way, if you have time (in this PR or another, with me as [coauthor](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) if you like).

File: servers/physics_3d/godot_collision_solver_3d_sat.cpp (hunk 1 above)
Comment (Mknsri) [reply servers/physics_3d/godot_collision_solver_3d_sat.cpp]: Good point! I fixed the commit

**Comment by Mknsri** [comment]
Thanks for the thorough explanation @rburing. I've made the changes per your suggestion. I will have a look a the other cases as well. I need some time to get test scene to reproduce the bugs so I will open a new PR if I'll fix  them.

**Review by rburing — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by Mknsri** [comment]
> Thanks! And congrats for your first merged Godot contribution 🎉

Thanks, happy to help 🥳

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.
