### PR TITLE
Warning dialog is now shown if trying to set Node name to empty string

### LINKED ISSUE #23376: Godot show error when name of node is set as empty instead popup like in filesystem dock
**Godot version:**
3.1 aeddb30

**OS/device including version:**
Windows 10

**Issue description:**
When I try to set empty name to node this error message is shown:
>ERROR: set_name: Condition ' name == "" ' is true.
   At: scene/main/node.cpp:930

but when I try to set empty name to file in file system dock then a popup with this message is appear:
>Warning!
No name provided

which is better and clearer message for user

**Steps to reproduce:**
https://streamable.com/qt1cs

### LINKED ISSUE #23378: When name one node name to space(" "), then rename node, space will disappare.
**Godot version:**
dev.calinou.942e0c4

**OS/device including version:**
win10

**Issue description:**
When name one node name to space(" "), then rename node, space will disappare.

**Steps to reproduce:**
1 name one node name to space(" ").
2 rename node.
3 space will disappare.

### PR DESCRIPTION
**Pull request by silvanocerza**
If the user tried to change a Node name to an empty string in the Scene Tree Editor an error would be returned to console, now a warning dialog is shown with a clear message.

Fixes #23376 and fixes #23378.

### CODE REVIEW

File: editor/scene_tree_editor.cpp [hunk 1]
```diff
@@ -645,6 +645,13 @@ void SceneTreeEditor::_rename_node(ObjectID p_node, const String &p_name) {
 	TreeItem *item = _find(tree->get_root(), n->get_path());
 	ERR_FAIL_COND(!item);
 
+	// Nodes must have a non empty name, so resets it to previous text and show warning
+	if (p_name.empty()) {
```
Comment (akien-mga) [inline editor/scene_tree_editor.cpp]: You should check `p_name.strip_edges().empty()`, spaces only are also illegal.

File: editor/scene_tree_editor.cpp [hunk 2]
```diff
@@ -645,6 +645,13 @@ void SceneTreeEditor::_rename_node(ObjectID p_node, const String &p_name) {
...
+		item->set_text(0, n->get_name());
```
Comment (akien-mga) [inline editor/scene_tree_editor.cpp]: I don't think this is needed, it's already the existing text normally. You can also move the whole `if` test at the start of the method to avoid needless node fetching and casting.

File: editor/scene_tree_editor.cpp [hunk 3]
```diff
@@ -645,6 +645,13 @@ void SceneTreeEditor::_rename_node(ObjectID p_node, const String &p_name) {
...
+		EditorNode::get_singleton()->show_warning(TTR("No name provided"));
```
Comment (akien-mga) [inline editor/scene_tree_editor.cpp]: Maybe be a bit more explicit? "Empty node names are not allowed."

File: editor/scene_tree_editor.cpp (hunk 1 above)
Comment (Alien1993) [reply editor/scene_tree_editor.cpp]: Right, I forgot.

File: editor/scene_tree_editor.cpp (hunk 2 above)
Comment (Alien1993) [reply editor/scene_tree_editor.cpp]: The TreeItem at this points has already an empty name, if I don't reset its text it would remain empty. The Node name instead is still unmodified that's why I use its name to reset the TreeItem text.

If the TreeItem text wasn't modified I could have put this at the start of the method.

File: editor/scene_tree_editor.cpp (hunk 3 above)
Comment (Alien1993) [reply editor/scene_tree_editor.cpp]: Thanks for the suggestion. :)

Comment (volzhs) [reply editor/scene_tree_editor.cpp]: "Node name must have at least 1 visible letter." ?

Comment (Alien1993) [reply editor/scene_tree_editor.cpp]: "Empty node names are not allowed." sounds better I think, you also include any character that's not 0 width this way.

**Comment by Alien1993** [comment]
@akien-mga I've found a more suitable place to check if name is empty, so I avoid lots of casting.

**Comment by akien-mga** [comment]
Thanks!
