### PR TITLE
TabContainer: Fix error on removing top-level Control child, Remove _get_tab method

### LINKED ISSUE #35741: Freeing TabContainer with direct child of type AnimationPlayer produces Error
**Godot version:** 3.2 Stable

**OS/device including version:** Win 10

**Issue description:**
Freeing TabContainer with direct child of type AnimationPlayer produces following Error
``` 
_disconnect: Nonexistent signal 'renamed' in [AnimationPlayer:3588].
  <C++ Error>   Condition "!s" is true.
  <C++ Source>  core/object.cpp:1518 @ _disconnect()
```

If AnimationPlayer is a grandchild of TabContainer, error does not come up.
**Steps to reproduce:**
Run Attached Project, main scene has two instanced child scenes, one with direct child AnimationPlayer which produces error on queue_free, and one with AnimationPlayer as grandchild ( a Control inbetween ) which produces no error on queue_free.

**Minimal reproduction project:**
[animationplayerbug.zip](https://github.com/godotengine/godot/files/4134326/animationplayerbug.zip)

### PR DESCRIPTION
**Pull request by kleonc**
Fixes error on removing top-level child `Control` from `TabContainer`. In #45123 only a check against `Control` was added but a non-top-level `Control` is also not considered as a tab and thus it's not connected to `renamed` signal in the first place.
Errors can still arise if user would change `top_level` property of a child `Control` of a `TabContainer` because in such situation logic from `add_child_notify()`/`remove_child_notify()` wouldn't be applied and thus `renamed` signal could be correctly/incorrectly connected/not connected to the callback. But it's rather uncommon case. To prevent/solve it properly something like https://github.com/godotengine/godot-proposals/issues/3081 would be needed.
Fixes #35741.

Removes private `_get_tab()` method as `get_tab_control()` does exactly the same thing.

In `move_child_notify()` prevents updating tabs when a non-tab child `Node` was moved (as suggested in https://github.com/godotengine/godot/pull/45123#issuecomment-758548517). Also there's no need to defer the call to `_update_current_tab()` because `move_child_notify()` is called after child was already moved (contrary to `remove_child_notify` which is called before removal happens).

Does some other cleanup.

### CODE REVIEW

File: scene/gui/tab_container.cpp [hunk 1]
```diff
@@ -682,7 +681,7 @@ Vector<Control *> TabContainer::_get_tabs() const {
 	Vector<Control *> controls;
 	for (int i = 0; i < get_child_count(); i++) {
 		Control *control = Object::cast_to<Control>(get_child(i));
-		if (!control || control->is_top_level_control()) {
+		if (!control || control->is_set_as_top_level()) {
```
Comment (kleonc) [inline scene/gui/tab_container.cpp:684]: This one looks like a typo made in https://github.com/godotengine/godot/commit/fc9077a213e8a73137855b41fda99819e7d1af85, everywhere else `is_set_as_top_level` is used.

**Comment by Calinou** [comment]
This will likely need a dedicated PR for `3.x`, since it won't apply cleanly there.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
