### PR TITLE
Fix editing exported nodes in array as text.

### LINKED ISSUE #89065: Can't edit exported nodes in array as text
### Tested versions

4.3 dev4
But likely existed since much earlier.

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When using the Edit option from NodePath's `⋮` menu, when the property is an Array of Nodes
image
submitting the text results in an error
```
  Attempted to set a variable of type 'NodePath' into a TypedArray of type 'Object'.
  core/variant/array.cpp:413 - Condition "!_p->typed.validate(value, "set")" is true.
```

### Steps to reproduce

1. `@export var a: Array[Node]
2. In the inspector, add element to array
3. Use Edit option from `⋮` menu
4. Type something and press Enter

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #93808: Using "Edit" on an exported node property in the inspector permanently breaks the reference
### Tested versions

Reproducible in 4.3.beta2

### System information

Godot v4.3.beta2 - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 32.0.15.5599) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 Threads)

### Issue description

Manually editing the node path of an exported node will result in the reference being permanently broken. "Permanent" in this case means until you manually reassign the reference through selection, which isn't possible for hidden children of scene instances. The property field will correctly display the referenced node, but at runtime, it will be `null`.

This breakage happens even if you do not actually change the node path (just click edit, and hit enter or escape).

The breakage happens because the `node_paths` part of the node that contains the reference gets wiped out. For example, in the context of the attached project, the correct version of the scene file shows this for the root node (the node containing the reference):
```[node name="test" type="Node" node_paths=PackedStringArray("box")]```
But the broken version of the scene file shows this:
```[node name="test" type="Node"]```

### Steps to reproduce

- Open the attached project and run the scene.
- Note the console prints out the box referenced by the root node.
- Stop the scene.
- Select the root node, and use the `Edit` option on its exported `Box` property.
- Hit `[Enter]`.
- Run the scene again.
- Note that the console now prints out `<null>`.

### Minimal reproduction project (MRP)

[bug-report.zip](https://github.com/user-attachments/files/16052744/bug-report.zip)

### PR DESCRIPTION
**Pull request by ajreckof**
Fixes #89065
Fixes #93808

### CODE REVIEW

File: editor/editor_properties.cpp [hunk 1]
```diff
@@ -2727,7 +2727,7 @@ void EditorPropertyNodePath::_node_selected(const NodePath &p_path) {
 		path = get_tree()->get_edited_scene_root()->get_path_to(to_node);
 	}
 
-	if (base_node) { // for AnimationTrackKeyEdit
+	if (p_absolute & (bool)base_node) { // for AnimationTrackKeyEdit
```
Comment (AThousandShips) [inline editor/editor_properties.cpp:2730]:
```suggestion
	if (p_absolute && base_node) { // for AnimationTrackKeyEdit
```

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
