### PR TITLE
Fix issue where editable children of 3D nodes would be selected

### LINKED ISSUE #84764: Can't select nodes behind a locked node in editor
### Godot version

v4.1.3.stable.mono.official [f06b6836a]

### System information

Godot v4.1.3.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti with Max-Q Design (NVIDIA; 31.0.15.3640) - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 Threads)

### Issue description

When I lock a node in the editor, I expect to be able to click and select things behind it. Instead, clicks are ignored.

I have a game where your typical view (as the player and when editing using Godot) is an isometric camera and the player is inside a building. There's a ceiling, represented by a plane, with the "front" of the ceiling mesh is pointed down towards the player, leaving the backface to be culled/invisible. The player is able to carry a camera that renders into a viewport in the UI, but this handheld camera (and Camera3D) render from the first person perspective -- that is, below the ceiling, which is why it's there in the first place. That is, the ceiling should be invisible to the bird's eye camera, but not to the first-person camera.

Basically in the editor there's this giant invisible plane covering the entire visible map that, even when locked, blocks my attempts to select anything else in the scene. My workaround is to hide the plane and wire the `ready` event to the `show()` method as a one-shot, but this is crude.

### Steps to reproduce

1. Create any two meshes, with one mesh interposed between the other and the editor camera. In my case, one of the meshes is a large plane that sits between the rest of the scene and the editor camera.
2. Mark the mesh closer to the camera as Locked.
3. Try to click the further mesh.

In the repro project attached, notice that it's quite hard to actually select the "Player" node.

### Minimal reproduction project

[LockBlockRepro.zip](https://github.com/godotengine/godot/files/13326210/LockBlockRepro.zip) -- does not require the C# build.

### LINKED ISSUE #96764: Top-level 3d nodes unable to be selected if their children have "editable children" toggled on
### Tested versions

- Bisected the issue to bf9fdc5b (#84831)
- Issue not present in 4.3.stable
- Issue present in 4.4.dev1
- Issue still present on 4.4.dev (master)

### System information

Godot v4.4.dev (27552a2f2) - macOS 14.6.1 - Metal (Forward+) - integrated Apple M3 Max (Apple9) - Apple M3 Max (16 Threads)

### Issue description

When selecting a 3D node, it selects the MeshInstance3D underlying instead of top the parent node, even when "editable children" is not toggled on.

### Steps to reproduce

1. Import a 3D model
2. Create an "editable" scene
3. Create a "non-editable" scene
4. In the "editable" scene, drag the 3d model inside it and toggle on "editable children"
5. In the "non-editable" scene, drag the 3d model inside it and do nothing else
6. Load both of these scenes in a main scene
7. Discover that you cannot select directly the "editable" scene node, as it selects the underlying `MeshInstance3D`. But there's no such issue when clicking on the "non-editable" scene node.

### Minimal reproduction project (MRP)

~~[node3d-select.zip](https://github.com/user-attachments/files/16934368/node3d-select.zip)~~
[node3d-select.zip](https://github.com/user-attachments/files/16934633/node3d-select.zip)

### PR DESCRIPTION
**Pull request by adamscott**
Fixes #96764

Reverts in some way https://github.com/godotengine/godot/pull/84831, but still fixes #84764, the issue that PR fixed.

Need to see if this conflicts with https://github.com/godotengine/godot/pull/87615 though.

### CODE REVIEW

**Comment by AThousandShips** [comment]
Doesn't look like it conflicts, will test this in a moment

**Review by AThousandShips — APPROVED** [review]
Can confirm that this solves the problem, and I think the use of `_select_ray` is appropriate here, but needs some additional feedback on that part

**Comment by adamscott** [comment]
@AThousandShips It shouldn't conflict. The fact that your PR fixed https://github.com/godotengine/godot/issues/96764 is more incidental to what you're doing and the fact that https://github.com/godotengine/godot/pull/84831 used `_find_items_at_pos()` (which seems overkill to select only one) instead of the previously used `_select_ray()` that I restored.

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -1557,7 +1557,7 @@ void Node3DEditorViewport::_surface_focus_exit() {
 	view_menu->set_disable_shortcuts(true);
 }
 
-bool Node3DEditorViewport ::_is_node_locked(const Node *p_node) {
```
Comment (AThousandShips) [inline editor/plugins/node_3d_editor_plugin.cpp:1560]: I have not a single clue how this got through CI

**Comment by akien-mga** [comment]
Thanks!
