### PR TITLE
Fix Unique Resources from Inherited Scenes

### LINKED ISSUE #115645: [Make unique bug] unable to be selected for CollisionShape3D child of scripted node and camera node
### Tested versions

Reproducible in version 4.6 does not work as previous version. 

Non-reproducible in version 4.5.1 works as intended.

### System information

Godot v4.6.stable - Windows 11 (build 26200) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 (NVIDIA; 32.0.15.6094) - 12th Gen Intel(R) Core(TM) i5-12600KF (16 threads) - 31.83 GiB memory

### Issue description

The camera node was set as a separate scene, has a child with a custom script known as "camera switch area", that node has a child CollisionShape3D. In order to edit the collision shape the camera was made local then editable children was selected. Make unique was attempted to be selected but it was grayed out and unable to be used as intended, unfortunately.

Image

Image

Image

Image

Image

### Steps to reproduce

Create a camera as a root in a new scene, set a child of area 3d, attach a script to area 3d, create collision shape 3d child of area 3d, select box shape. Copy the camera root.
Create new scene, paste camera into the new scene, select editable children and/or make local, unable to make unique.

### Minimal reproduction project (MRP)

Attempting to reproduce the issue in a fresh project replicates the issue. The relevant code is included in the project itself.

[Make unique bug.zip](https://github.com/user-attachments/files/24969368/Make.unique.bug.zip)

### PR DESCRIPTION
**Pull request by nhold**
Using the analysis by @skyace65 (https://github.com/godotengine/godot/issues/115416#issuecomment-3815261908) I took the original commit from the PR: #114901 and reverted it, then added the special case for if it's an external resource.

This might allow other scenarios that I'm not aware of, but at least doesn't break inherited scenes or external resources.

Additionally it looks like `en->` was not being used consistently throughout the method so I partially updated that.

I would recommend this fix as a candidate for 4.6.1, my understanding is that inherited scenes and unique resources is a fairly common workflow.

Fixes:

- fixes https://github.com/godotengine/godot/issues/115416
- fixes https://github.com/godotengine/godot/issues/115645

### CODE REVIEW

File: editor/inspector/editor_resource_picker.cpp [hunk 1]
```diff
@@ -1399,16 +1399,19 @@ bool EditorResourcePicker::_is_uniqueness_enabled(bool p_check_recursive) {
...
+		return node_list.size() != en->get_resource_count(edited_resource) || !internal_to_scene;
 	}
 
 	if (!internal_to_scene) {
-		if (parent_resource.is_valid() && parent_resource->is_built_in() && (!EditorNode::get_singleton()->is_resource_internal_to_scene(parent_resource) || en->get_resource_count(parent_resource) > 1)) {
+		if (parent_resource.is_valid() && (!en->is_resource_internal_to_scene(parent_resource) || en->get_resource_count(parent_resource) > 1)) {
+			if (!parent_resource->is_built_in()) {
+				return true;
+			}
 			return false;
```
Comment (KoBeWi) [inline editor/inspector/editor_resource_picker.cpp]:
```suggestion
			return !parent_resource->is_built_in();
```

**Review by KoBeWi — APPROVED** [review]
