### PR TITLE
Fix internal editor not updating when using external editor via LSP

### LINKED ISSUE #59115: GD Scripts changed externally not properly reloaded
### Godot version

v4.0.alpha4.official [f47097973]

### System information

macOS Monterey 12.2.1, Macbook Pro M1Max

### Issue description

If a script is changed externally (e.g. in a different editor) Godot detects this and ask if the script should be reloaded.  When clicking "reload" the editor window is **not** updated with the new changes. The old version is retained even if I close and reopen the (internal) code editor window. Selecting File >> Soft Reload Script  is is also not updating the editor. 

When running the project, the updated script is used so it seems to be an issue with the code editor only.

### Steps to reproduce

1. Create new project
2. Add a scene and a node
3. Attach a script to the node and save
4. Edit the script in an external editor (e.g. vim, vscode)
5. Switch back to Godot and click reload script

### Minimal reproduction project

_No response_

### LINKED ISSUE #69485: Godot4 Editor not picking up external editing changes with LSP
### Godot version

4.0.beta7.official [0bb1e89fb]

### System information

Ubuntu 18.04

### Issue description

I believe there is an issue with the Godot editor's script editor not picking up changes whenever a file is changed from an editor that has an LSP integration.

### Steps to reproduce

1. Create a new project in Godot 4.0 (e.g. `zz-godot-4-editor-test`)
2. Create a new node (e.g. a `Control`), attach a script file to it, (e.g. `Test.gd`).
3. Add a `print("Hello World!")` to the `_ready` function in `Test.gd`
4. Run with `<F5>` and confirm it runs and prints out
5. Open `Test.gd` in either Emacs with `gdscript-mode` enabled (https://github.com/godotengine/emacs-gdscript-mode) or VSCode with godot-tools (https://marketplace.visualstudio.com/items?itemName=geequlim.godot-tools), change line to something like `print("Hello World from emacs")`
6. Switch back to Godot Editor. **Script file does not get updated with the above change**
   * The way to get this updated to close the script with `<Ctrl-w>` and reopen it

The script does reload properly if:
  * The extension is disabled (godot-tools in VSCode/emacs-gdscript-mode in Emacs)
  * The file is edited using an editor without LSP (e.g. Vim)
   
Performed the above on Ubuntu 18.04 machine with Godot 4 beta7 but I've observed it since first trying out Godot4 which was around beta4.

Having a quick look at open PRs, this one (https://github.com/godotengine/godot/pull/66658) looks like it could be relevant but it hasn't been updated for a while.

### Minimal reproduction project

```
extends Control

# Called when the node enters the scene tree for the first time.
func _ready():
	print("Hello World from VSCode")
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass
```

### PR DESCRIPTION
**Pull request by Rindbee**
Fix #69485, fix #59115.

In addition, `update_exports` was called in `ScriptTextEditor` before, which may require script to be open in a  `ScriptTextEditor` to update the export variable.

Fix external modification of text files causing tabs opened in the internal editor to lose their names.

#66658, #66916, #66880 seem to have missed the best time.

### CODE REVIEW

**Comment by Rindbee** [comment]
I don't know why the CI always fails, my local tests seem to pass.

<details>
  <summary>Messages</summary>

```bash
$ ./bin/godot.linuxbsd.editor.dev.x86_64.llvm --test
[doctest] doctest version is "2.4.9"
[doctest] run with "--help" for options
===============================================================================
./tests/core/object/test_class_db.h:837:
TEST SUITE: [ClassDB]
TEST CASE:  [ClassDB] Add exposed classes, builtin types, and global enums

./tests/core/object/test_class_db.h:490: MESSAGE: Ignoring class 'GDScriptEditorTranslationParserPlugin' because it's not exposed.

./tests/core/object/test_class_db.h:490: MESSAGE: Ignoring class 'IPUnix' because it's not exposed.

./tests/core/object/test_class_db.h:490: MESSAGE: Ignoring class 'MovieWriterMJPEG' because it's not exposed.

./tests/core/object/test_class_db.h:490: MESSAGE: Ignoring class 'MovieWriterPNGWAV' because it's not exposed.

./tests/core/object/test_class_db.h:490: MESSAGE: Ignoring class 'ResourceFormatImporterSaver' because it's not exposed.

ERROR: Caret column exceeds line length.
   at: _filter_code_completion_candidates_impl (scene/gui/code_edit.cpp:2859)
ERROR: Parameter "RenderingServer::get_singleton()" is null.
   at: ~Path3D (scene/3d/path_3d.cpp:43)
ERROR: Parameter "RenderingServer::get_singleton()" is null.
   at: ~Path3D (scene/3d/path_3d.cpp:43)
ERROR: Parameter "RenderingServer::get_singleton()" is null.
   at: ~Path3D (scene/3d/path_3d.cpp:43)
ERROR: Parameter "RenderingServer::get_singleton()" is null.
   at: ~Path3D (scene/3d/path_3d.cpp:43)
===============================================================================
[doctest] test cases:     747 |     747 passed | 0 failed | 1 skipped
[doctest] assertions: 2306278 | 2306278 passed | 0 failed |
[doctest] Status: SUCCESS!
ERROR: Profiler not registered: multiplayer:bandwidth
   at: unregister_profiler (core/debugger/engine_debugger.cpp:54)
ERROR: Profiler not registered: multiplayer:rpc
   at: unregister_profiler (core/debugger/engine_debugger.cpp:54)
ERROR: Profiler not registered: multiplayer:replication
   at: unregister_profiler (core/debugger/engine_debugger.cpp:54)
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:1980)
```
</details>

c3539b456

https://user-images.githubusercontent.com/30386067/213904484-e90ae17f-2c97-4216-b604-79b8113de212.mp4

This PR

https://user-images.githubusercontent.com/30386067/213904502-2ac1c842-eff6-4935-bea1-cfc4f9932151.mp4

This PR mainly solves the problem that the script text is not updated when using lsp.

**Comment by Rindbee** [comment]
This PR will call `update_exports()` after a successful reload, which fixes the issue mentioned in #71843.

File: editor/plugins/script_editor_plugin.cpp [hunk 1]
```diff
@@ -2538,11 +2538,7 @@ void ScriptEditor::reload_scripts(bool p_refresh_only) {
 
 			Ref<TextFile> text_file = edited_res;
 			if (text_file != nullptr) {
```
Comment (akien-mga) [inline editor/plugins/script_editor_plugin.cpp:2540]: I think this check is useless, `Ref<T>` is never nullptr afaik. It should use `text_file.is_valid()` to check the actual pointer.

**Comment by akien-mga** [comment]
The CI has these errors before the crash:
```
modules/gdscript/gdscript.cpp:685:39: runtime error: member call on null pointer of type 'struct GDScript'
modules/gdscript/gdscript.cpp:685:39: runtime error: member access within null pointer of type 'struct GDScript'
```

**Comment by Rindbee** [comment]
There seems to be a recursive call. Issues with updating exports will be addressed in another commit. So I reverted the relevant code.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
