### PR TITLE
Fix visibility issue with zoom label

### LINKED ISSUE #42986: Zoom Level with light theme nearly invisible
Windows 10, Godot Engine v3.2.3.stable

Switch to light theme, open a new empty scene and look at the zoom level. The zoom level is only a little bit darker as the background. 
Zwischenablage01

### PR DESCRIPTION
**Pull request by rsubtil**
Fixes #42986

### CODE REVIEW

**Comment by akien-mga** [comment]
This should likely be done here instead, so it changes when you change the theme:
https://github.com/godotengine/godot/blob/99172b9f33700edc53defaa28bc83143d2882953/editor/plugins/canvas_item_editor_plugin.cpp#L4007

**Comment by Ev1lbl0w** [comment]
So, should I just move my changes, or do I need to do it in a different way?

**Comment by akien-mga** [comment]
Just moving it should be sufficient.

**Comment by Ev1lbl0w** [comment]
For some reason, this **doesn't work** when the code is inside `_notification`. I'll see if I can figure out why.

**Comment by Ev1lbl0w** [comment]
So, the way I got it to work is kinda heavy:
```cpp
Theme t = Theme();
t.copy_default_theme();
zoom_reset->add_theme_color_override("font_color", t.get_color("font_color", "Label"));
```
Is it okay, or would a hardcoded `Color(1, 1, 1)` here be acceptable?

**Comment by YeldhamDev** [comment]
If the value is just a pure white color, I don't think there's much harm in putting it directly.

**Comment by Ev1lbl0w** [comment]
Alright, I've hardcoded the value, and can confirm it's working now :slightly_smiling_face:

**Review by YeldhamDev — APPROVED** [review]

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -4090,6 +4090,8 @@ void CanvasItemEditor::_notification(int p_what) {
 		anchors_popup->add_icon_item(get_theme_icon("ControlAlignWide", "EditorIcons"), TTR("Full Rect"), ANCHORS_PRESET_WIDE);
 
 		anchor_mode_button->set_icon(get_theme_icon("Anchor", "EditorIcons"));
+
+		zoom_reset->add_theme_color_override("font_color", Color(1, 1, 1));
```
Comment (akien-mga) [inline editor/plugins/canvas_item_editor_plugin.cpp:4094]: Ah now that I think about it, if it's meant to *always* be white and not dynamic, then it's fine to change it in the constructor instead of here. Changing in `NOTIFICATION_EDITOR_SETTINGS_CHANGED` is for stuff that depends on the theme and thus needs to be redone each time you change theme.

That being said, I guess this only works as long as you use a dark default clear color in the project settings. If you set a light color as clear color, you'd get the same issue again.

Comment (YeldhamDev) [reply editor/plugins/canvas_item_editor_plugin.cpp:4094]: Maybe we could make the font outline for this label thicker, so it's visible on any color?

Comment (Ev1lbl0w) [reply editor/plugins/canvas_item_editor_plugin.cpp:4094]: Huum, that is true, I didn't remember the "clear color" property. Then it's better to implement a solution similar to #36530 and draw a semi-opaque box behind.

Comment (KoBeWi) [reply editor/plugins/canvas_item_editor_plugin.cpp:4094]: How about something like #36530? (we could use the `_draw_text_with_backdrop` method if that was merged)

Comment (Ev1lbl0w) [reply editor/plugins/canvas_item_editor_plugin.cpp:4094]: @KoBeWi I though about it, but `zoom_reset` is a Button, so it wouldn't work. On the other hand *(because it is a Button)*, we can just re-enable it's background panel. However adding an outline to the text also works pretty well, and is less distracting *(however it might not be very visible in some cases)*

Here's the text with outline, and with the button background, for comparision.

image

Which one do you guys think looks best?

Comment (YeldhamDev) [reply editor/plugins/canvas_item_editor_plugin.cpp:4094]: @Ev1lbl0w The second one, which I have been suggesting from the beginning.

**Comment by Ev1lbl0w** [comment]
Alright, added an outline to the zoom label :slightly_smiling_face: 
image

**Comment by Ev1lbl0w** [comment]
Aaaand fixed the static checks, hopefully my last force push here :stuck_out_tongue:

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 2]
```diff
@@ -5642,6 +5643,11 @@ CanvasItemEditor::CanvasItemEditor(EditorNode *p_editor) {
 	zoom_reset = memnew(Button);
 	zoom_reset->set_flat(true);
 	zoom_hb->add_child(zoom_reset);
+	Ref<DynamicFont> font = Object::cast_to<DynamicFont>(*(zoom_reset->get_theme_font("font")->duplicate(false)));
```
Comment (akien-mga) [inline editor/plugins/canvas_item_editor_plugin.cpp:5646]: KISS ;)
```suggestion
	Ref<DynamicFont> font = zoom_reset->get_theme_font("font")->duplicate(false);
```

Comment (Ev1lbl0w) [reply editor/plugins/canvas_item_editor_plugin.cpp]: Fixed :slightly_smiling_face:

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Comment by akien-mga** [comment]
Undid the cherry-pick as it crashes on `3.2`:
```
[1] /lib64/libc.so.6(+0x3a4e0) [0x7fd4e8c404e0] (??:0)
[2] DynamicFont::set_outline_size(int) (/home/akien/Projects/godot/godot-3.2/scene/resources/dynamic_font.cpp:750)
[3] CanvasItemEditor::CanvasItemEditor(EditorNode*) (/home/akien/Projects/godot/godot-3.2/editor/plugins/canvas_item_editor_plugin.cpp:5602)
[4] CanvasItemEditorPlugin::CanvasItemEditorPlugin(EditorNode*) (/home/akien/Projects/godot/godot-3.2/editor/plugins/canvas_item_editor_plugin.cpp:5943)
[5] EditorNode::EditorNode() (/home/akien/Projects/godot/godot-3.2/editor/editor_node.cpp:6772)
[6] Main::start() (/home/akien/Projects/godot/godot-3.2/main/main.cpp:1801)
[7] godot-3.2(main+0xe7) [0x1439739] (/home/akien/Projects/godot/godot-3.2/platform/x11/godot_x11.cpp:55)
[8] /lib64/libc.so.6(__libc_start_main+0xea) [0x7fd4e8c2ccda] (??:0)
[9] godot-3.2(_start+0x2a) [0x14395aa] (??:?)
-- END OF BACKTRACE --
Aborted (core dumped)
```

Haven't looked into it but I suspect the font resource might not be valid yet in the constructor.

**Comment by Ev1lbl0w** [comment]
Huuum, I'll take a look at this

**Comment by Ev1lbl0w** [comment]
So, I took another shot at this problem, and can't seem to fix it. The core problem *(and what's causing the crash)*, is here:

```cpp
Ref<DynamicFont> font = zoom_reset->get_theme_font("font")->duplicate(false);
```

What happens is that this cast that is being made *(from `Font` to `DynamicFont`)* evaluates to `0x00`. From what I understand, this means to an invalid cast, so `default_font` is not type `DynamicFont`, but actually `BitmapFont`; and looking at where it's [initialized](https://github.com/godotengine/godot/blob/fd6b3060c1cca10754c47ad04a4e50d49ca838b7/scene/resources/default_theme/default_theme.cpp#L123), it does look like it.

But in that case, I don't understand how this even worked for the `master` branch; AFAIK there are not many changes on how the default font is created, and all things point to it being a `BitmapFont` as well. If that's true, then I don't understand how the cast succeeds. So, I really have no clue how to fix this for 3.2 :confused:

**Comment by akien-mga** [comment]
Fonts changed in master, both bitmap and dynamic fonts are now the same Font resource. CC @bruvzg

**Comment by bruvzg** [comment]
Indeed in master all fonts use the same class and are fully interchangeable. But editor fonts should be Dynamic in 3.2 as well. If zoom label use Bitmap font, something is wrong with the theme propagation (in master it's using correct font, I was testing it with eastern Arabic numerals which aren't available in default theme font).

**Comment by akien-mga** [comment]
Backported via #49274.
