### PR TITLE
[VisualShader] Remove invalid graph connections when ports are removed

### LINKED ISSUE #79417: No disconnect when changing node type with less joints in visual shader editor
### Godot version

4.1.stable

### System information

Ubuntu 22.04

### Issue description

Visual shader editor should disconnect (at least visually) when we change the number of joints

before changing the type
image

after
image
image

this one break things
image

### Steps to reproduce

You can see what to do to reproduce the bug in the screenshot

### Minimal reproduction project

A visual shader, two nodes.

### PR DESCRIPTION
**Pull request by Geometror**
Supercedes #80312. (partial salvage, the undo/redo stuff had to be redone)
Fixes #79417.

invalid-conns-fix

### CODE REVIEW

File: editor/plugins/visual_shader_editor_plugin.cpp [hunk 1]
```diff
@@ -6747,8 +6747,35 @@ class VisualShaderNodePluginDefaultEditor : public VBoxContainer {
...
+		vsnode_new->set(p_property, p_value);
+		const int input_port_count = vsnode_new->get_input_port_count();
+		const int output_port_count = vsnode_new->get_output_port_count();
+
+		List<VisualShader::Connection> conns;
+		editor->get_visual_shader()->get_node_connections(shader_type, &conns);
+		VisualShaderGraphPlugin *graph_plugin = editor->get_graph_plugin();
+		bool undo_node_already_updated = false;
+		for (const VisualShader::Connection &c : conns) {
+			if (unlikely((c.from_node == node_id && c.from_port >= output_port_count) || (c.to_node == node_id && c.to_port >= input_port_count))) {
```
Comment (paddy-exe) [inline editor/plugins/visual_shader_editor_plugin.cpp:6766]: Did you benchmark the `unlikely` usage? I am a cpp novice but just reading some information about it, it seems it should be used with caution in terms of optimization

Comment (Geometror) [reply editor/plugins/visual_shader_editor_plugin.cpp:6766]: In this specific case I don't think using `unlikely` will have a significant performance advantage, but I kept it in anyways since in theory it might have (and keeping it shouldn't have any downsides). Unlikely should only be used if you're sure that the condition will we false let's say 90-95% of all times (oversimplified!), which is definitely the case here: It's only true when an invalid connection is found and after all of them were removed the condition is always true. And currently the code will be executed for every VS node property change.
`unlikely` only gives a hint to the compiler, what the compiler actually does with it depends on many different things. E.g. "large" branches can be entirely pulled out of a loop so that it fits better in loop buffers.
Currently we have our own Linux-style branch prediction macros, which are only effective for GNU compilers.
Disclaimer: I'm not an expert on this topic and the above is about it regarding my understanding, so others might provide better insight.

**Review by paddy-exe — APPROVED** [review]
Works as expected. Can't say much about the usage of the `unlikely` keyword but the explanation makes sense

File: editor/plugins/visual_shader_editor_plugin.cpp [hunk 2]
```diff
@@ -6747,8 +6747,35 @@ class VisualShaderNodePluginDefaultEditor : public VBoxContainer {
 		undo_redo->add_do_property(node.ptr(), p_property, p_value);
 		undo_redo->add_undo_property(node.ptr(), p_property, node->get(p_property));
 
+		Ref<VisualShaderNode> vsnode = editor->get_visual_shader()->get_node(shader_type, node_id);
+		ERR_FAIL_COND(!vsnode.is_valid());
```
Comment (AThousandShips) [inline editor/plugins/visual_shader_editor_plugin.cpp:6751]:
```suggestion
		ERR_FAIL_COND(vsnode.is_null());
```

File: editor/plugins/visual_shader_editor_plugin.h [hunk 3]
```diff
@@ -555,7 +555,10 @@ class VisualShaderEditor : public VBoxContainer {
 	void update_custom_type(const Ref<Resource> &p_resource);
 
 	virtual Size2 get_minimum_size() const override;
+
 	void edit(VisualShader *p_visual_shader);
+	Ref<VisualShader> get_visual_shader() { return visual_shader; }
```
Comment (AThousandShips) [inline editor/plugins/visual_shader_editor_plugin.h:560]:
```suggestion
	Ref<VisualShader> get_visual_shader() const { return visual_shader; }
```

**Review by AThousandShips — APPROVED** [review]

File: editor/plugins/visual_shader_editor_plugin.cpp (hunk 1 above)
Comment (AThousandShips) [reply editor/plugins/visual_shader_editor_plugin.cpp:6766]: `unlikely` only matters either way in a performance critical part, the penalty for an incorrect one is as negligible as the benefit from a correct one, I'd say it's unnecessary here as it's not a tight place, but it's harmless

Comment (AThousandShips) [reply editor/plugins/visual_shader_editor_plugin.cpp:6766]: I'd remove it, it serves essentially no purpose here as it's not performance critical, and hurts readability IMO

**Comment by akien-mga** [comment]
@Geometror There are a couple code style/quality comments to address, then it should be good to merge.

**Comment by akien-mga** [comment]
Thanks!
