### PR TITLE
Fix Plugin Scripts load twice on startup

### LINKED ISSUE #100750: Godot 4.4 throws errors when using `await` on EditorPlugin
### Tested versions

- Reproducible: 4.4-dev1 and 4.4-dev7
- Not Reproducible: 4.3-stable

### System information

Godot v4.4.dev7 - Windows 10 (build 19045) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 32.0.15.6603) - Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 threads)

### Issue description

When the editor starts up, calling code from an Autoload to an EditorPlugin with a function that uses `while` and `await` will result in either:
- Working fine.
- Throwing a Bad Address Index error.
- Throwing an Internal Script error with opcode 0, 1 or 99.
- Crashing to desktop.

Image

### Steps to reproduce

The MRP will throw the error when opening the project. If it doesn't, use "Project > Reload Current Project" as sometimes it may simply work.

This problem seems to require a combination of a few situations to happen:
- The EditorPlugin must be enabled. The issue vanishes when disabled, even if there are no changes in the script execution.
- The function must be called from the Autoloader to the EditorPlugin, if called from inside the EditorPlugin, it works fine.
- the EditorPlugin class must be loaded inside the function using `load()`. Works fine with a preloaded variable on the class scope.
- The `await` must be inside the `while` loop.

Some background on why I'm running code like this:
- To isolate editor access to only inside the EditorPlugin class.
- My plugin checks for a resource file, if it doesn't exist, creates the file and updates the FileSystem if it's in editor mode.
- After v4.2 or v4.3, the FileSystem takes a while to load and during that time any new files or requests to update are ignored.
- I can't use `preload()` because EditorPlugin classes are not exported to runtime.

### Minimal reproduction project (MRP)

[project_bad_address.zip](https://github.com/user-attachments/files/18223024/project_bad_address.zip)

### PR DESCRIPTION
**Pull request by Hilderin**
- Fixes #100750

Thanks to @HolonProduction for helping fix this issue.!!

The issue was caused by the plugin script being loaded twice on startup when the same script is used in the plugin's `ready` method and as an autoload. Autoloads are created before plugins, triggering the first load. When the plugin is enabled, the script is loaded again with `CACHE_MODE_IGNORE`, causing it to reload while `await` calls are still running.  

I changed the cache mode to `CACHE_MODE_REUSE` when enabling plugins on editor startup (while the first scan is running).

I tested this with the MRP from #100750, and as suggested by @HolonProduction, I also retested the MRP from **#70667**. Godot's startup process has changed quite a bit since this issue was first reported. Since #92667, scripts that reference resources can now load even before the first scan, allowing the project to load without any errors or warnings on the first startup without the `.godot` folder.  

I have kept `CACHE_MODE_IGNORE` when the editor is not in startup mode to prevent potential side effects.

### CODE REVIEW

**Comment by HolonProduction** [comment]
I think you meant to link to #100750, not my PR :sweat_smile:

**Comment by Hilderin** [comment]
Totally right! I changed it. Thanks!

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -3710,7 +3710,9 @@ void EditorNode::set_addon_plugin_enabled(const String &p_addon, bool p_enabled,
 	// Only try to load the script if it has a name. Else, the plugin has no init script.
 	if (script_path.length() > 0) {
 		script_path = addon_path.get_base_dir().path_join(script_path);
-		scr = ResourceLoader::load(script_path, "Script", ResourceFormatLoader::CACHE_MODE_IGNORE);
+		// We should use the cached version on startup to prevent a script reload
+		// if it is already loaded and potentially running from autoloads.
```
Comment (HolonProduction) [inline editor/editor_node.cpp:3714]:
```suggestion
		// We should use the cached version on startup to prevent a script reload
		// if it is already loaded and potentially running from autoloads. See godotengine/godot#100750
```
I don't think the full context of the issue is fully understandable from just the comment.

Comment (Ivorforce) [reply editor/editor_node.cpp:3714]: While we're here, I've been told the appropriate issue reference format would be GH-100750 :)

Comment (HolonProduction) [reply editor/editor_node.cpp:3714]: Good to know, never knew we had guidelines for this. Let's hope no one ever wants to link a proposal :sweat_smile:

Comment (Hilderin) [reply editor/editor_node.cpp]: Same here! Did not know that! Thanks!
And my comment was wrong... it should have been: `// We should not use the cached versionn on startup...`

**Review by HolonProduction — APPROVED** [review]
Tested with #100750 and couldn't reproduce any errors in ~20 attempts. I was experiencing the issue around every three tries before, so quite confident that this is fixed.

Wasn't able to reproduce #70667 with this as well.

Also think it makes sense to still reload after the initial scan, since that's usually triggered by explicit user actions.

**Comment by Repiteo** [comment]
Thanks!
