### PR TITLE
Fix shadow mesh recursion.

### LINKED ISSUE #93486: No warning on recursion of mesh in array mesh
### Tested versions

- Reproductible in: v4.3-beta2, v4.2.2

### System information

Godot v4.3.beta2 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 32.0.15.5599) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

Godot lets you use an array mesh as its own shadow mesh, therby allowing recurtion. When opening the inspector on that perticular mesh instance 3d the editor hangs and eventualy closes without any explenation in the logs.

### Steps to reproduce

1. Create a project
2. Make a scene and add a MeshInstance3D node to it
3. Set the mesh to be an array mesh
4. In a toolscript set the shadow_mesh to be the mesh
```gdscript
$MeshInstance3D.mesh.shadow_mesh = $MeshInstance3D.mesh
```
5. Run the script
6. Open the MeshInstance3D in the inspector
7. Crash

### Minimal reproduction project (MRP)

[crashoncyclicmesh.zip](https://github.com/user-attachments/files/15938238/crashoncyclicmesh.zip)

### PR DESCRIPTION
**Pull request by radiantgurl**
closes #93486

### CODE REVIEW

File: servers/rendering/rendering_server_default.h [hunk 1]
```diff
@@ -313,7 +313,16 @@ class RenderingServerDefault : public RenderingServer {
 	FUNC2(mesh_set_path, RID, const String &)
 	FUNC1RC(String, mesh_get_path, RID)
 
-	FUNC2(mesh_set_shadow_mesh, RID, RID)
+	virtual void mesh_set_shadow_mesh(RID p1, RID p2) override {
+		ERR_FAIL_COND_MSG(p1 == p2, "Cannot put the mesh itself as its own shadow mesh.");
```
Comment (clayjohn) [inline servers/rendering/rendering_server_default.h:317]: This should be added to the implemented of `mesh_set_shadow_mesh` instead of adding a shim here.

File: drivers/gles3/storage/mesh_storage.cpp [hunk 2]
```diff
@@ -743,6 +743,7 @@ String MeshStorage::mesh_get_path(RID p_mesh) const {
 }
 
 void MeshStorage::mesh_set_shadow_mesh(RID p_mesh, RID p_shadow_mesh) {
+	ERR_FAIL_COND_MSG(p_mesh == p_shadow_mesh, "Cannot put the mesh itself as its own shadow mesh.");
```
Comment (clayjohn) [inline drivers/gles3/storage/mesh_storage.cpp:746]:
```suggestion
	ERR_FAIL_COND_MSG(p_mesh == p_shadow_mesh, "Cannot set a mesh as its own shadow mesh.");
```

**Review by clayjohn — CHANGES_REQUESTED** [review]
I think this is fine as a stopgap solution for now. I have suggested a language change for the error message to fix the english grammar. 

Ultimately, this only pushes back the issue by one level of recursion as the problem could still be reproduced with the following:
1. MeshA has shadow mesh set to MeshB
2. MeshB has shadow mesh set to MeshA

I think this is fine to merge as-is though as it fixes the reported issue and comes with very little cost. Ultimately, the problem lies in the editor itself not handling recursion as pointed out here: https://github.com/godotengine/godot/issues/93486#issuecomment-2187348151 That is a much larger problem that I don't think is worth tackling yet

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.
