### PR TITLE
Fix bug related to multicursor and backspacing with brackets

### LINKED ISSUE #89417: Backspacing with active multicursor moves the cursors in wrong position if on opening bracket or quotation marks
### Tested versions

4.2.1.stable.official

### System information

Windows 11

### Issue description

When using multiple cursors with the CTRL+D shortcut, if you have the cursors just after a bracket, as follows

selection_1

If you backspace to delete the bracket, it gets deleted fine, but the cursors move asynchronously (should be between `s` and the number, the one on the right has moved a character too much to the left)
 
selection_2

Please note that

- I've only tested this in Gdscript
- In my tests, I've only found out this to happen when the deleted character is `(`, `[`, `{`, `"`, or `'`, not with any other character, not even closing brackets
- The amount of excessive movement to the left stacks along the same line
- The amount of excessive movement to the left resets along multiple columns

selection_4

- The stacked amount of excessive movement doesn't seem to have a limit

### Steps to reproduce

- Write
```gdscript
random[0] = random[1]
```

- Select the first `[` character
- Activate multiple cursors with "CTRL + D"
- Click "right arrow" to remove the active selection without removing the multiple cursor
- Click "backspace"

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by garrettgu10**
Fixes #89417. 

The root of the issue is that when removing an opening brace `remove_text` is sometimes called with just `cc` (when the opening and closing brace are not next to each other), but `adjust_carets_after_edit` was always being called assuming that the closing brace was removed as well.

### CODE REVIEW

File: scene/gui/code_edit.cpp [hunk 1]
```diff
@@ -732,15 +732,19 @@ void CodeEdit::_backspace_internal(int p_caret) {
...
 				prev_column = cc - auto_brace_completion_pairs[idx].open_key.length();
 
+				int new_cc;
 				if (_get_auto_brace_pair_close_at_pos(cl, cc) == idx) {
-					remove_text(prev_line, prev_column, cl, cc + auto_brace_completion_pairs[idx].close_key.length());
+					new_cc = cc + auto_brace_completion_pairs[idx].close_key.length();
 				} else {
-					remove_text(prev_line, prev_column, cl, cc);
+					new_cc = cc;
 				}
```
Comment (akien-mga) [inline scene/gui/code_edit.cpp:740]: Could be simplified to:
```cpp
int new_cc = cc;
if (_get_auto_brace_pair_close_at_pos(cl, cc) == idx) {
	new_cc += auto_brace_completion_pairs[idx].close_key.length();
}
```

**Comment by kitbdev** [comment]
- Also fixed by https://github.com/godotengine/godot/pull/86978

File: scene/gui/code_edit.cpp (hunk 1 above)
Comment (akien-mga) [reply scene/gui/code_edit.cpp]: `cc` is still used further down in other branches and iterations of the loop, so modifying it might change behavior. Does it fix further bugs by doing so or actually risk introducing bugs?

Comment (kitbdev) [reply scene/gui/code_edit.cpp]: There is a `continue` after this, and it is re-set on the next loop iteration, so it doesn't affect any other uses.

Comment (akien-mga) [reply scene/gui/code_edit.cpp]: Ah indeed :+1:

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
