### PR TITLE
Fix editor crash when creating a custom resource from create dialog

### LINKED ISSUE #39939: Editor crashes when creating a custom resource from the filesystem tab
**Godot version:**

Godot Engine v4.0.dev.custom_build.481151be0
Commit 481151be09108a30002ae0a9df118eeddd3987be

**OS/device including version:**

Mac OS 10.15.5 Catalina

**Issue description:**

When creating a custom resource from the filesystem tab, the editor crashes after clicking 'Create' with the resource type selected.
image

The resource code:
```GDScript
#my_resource.gd
extends Resource
class_name MyResource

export var name : String
```

**Steps to reproduce:**

1. Create a custom resource script
2. Create a new resource of that type

Creating a resource and assigning the script manually does not cause a crash, but changing the script after has caused one. I could not reproduce this error.

**Minimal reproduction project:**

[Custom Resource Crash.zip](https://github.com/godotengine/godot/files/4844823/Custom.Resource.Crash.zip)
[crash.log](https://github.com/godotengine/godot/files/4844826/crash.log)

### PR DESCRIPTION
**Pull request by Xrayez**
Fixes #39939.

### CODE REVIEW

File: editor/create_dialog.cpp [hunk 1]
```diff
@@ -425,7 +425,6 @@ Object *CreateDialog::instance_selected() {
 			if (n) {
 				n->set_name(custom);
 			}
-			obj = n;
```
Comment (Xrayez) [inline editor/create_dialog.cpp:428]: The object is instantiated above. We only need cast to node to set its name.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
