### PR TITLE
GLES3: Ensure all ShaderData is properly initialized in `set_code`

### LINKED ISSUE #84418: Warning spam in Compatibility renderer: Attempting to use a shader that requires tangents with a mesh that doesn't contain tangents.
### Godot version

Godot v4.2.beta (5ee983188)

### System information

 - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.3699) - 12th Gen Intel(R) Core(TM) i7-12700F (20 Threads)

### Issue description

When create a new scene and add any mesh instance 3d to it, the following warning spams: 
```
drivers\gles3\rasterizer_scene_gles3.cpp:265 - Attempting to use a shader that requires tangents with a mesh that doesn't contain tangents. Ensure that meshes are imported with the 'ensure_tangents' option. If creating your own meshes, add an `ARRAY_TANGENT` array (when using ArrayMesh) or call `generate_tangents()` (when using SurfaceTool). (User)
```

This doen't happen in forward plus or mobile.

image

### Steps to reproduce

1. Create a new project with Compatibility renderer
2. create a new scene and add a mesh instance 3d to it
3. observe the warning spam

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by akien-mga**
- Fixes #84418 (at least it should, didn't test yet as this needs an optimized build).
- Supersedes #84599.

I refactored the code to be clearer and hopefully prevent such errors in the future, but it's still quite error prone. The config booleans could maybe be moved to an internal struct that would always be zero'ed in `set_code`, so this can all be done in a single line instead of listing them all one by one.

I noticed that `version` doesn't get reset when calling `set_code`; I suppose this is intended.

Some ShaderData implementations initialized most of their booleans before the early return with empty `code`, while others did them after declaring `gen_code`. I unified to be like the former which seems to be the least bug prone (doesn't assume that none of these will be accessed when `valid = false`), but I could refactor the other way around if preferred.

### CODE REVIEW

**Comment by akien-mga** [comment]
I can't reliably trigger the warning locally with GCC builds, so would be good if @jsjtxietian or @chrisl8 could confirm that it fixes the issue for them.

**Comment by chrisl8** [comment]
Will test later today.

**Comment by chrisl8** [comment]
@akien-mga  Yes, this appears to fix the issue entirely:

v4.2.beta.custom_build [e38686f85]
image

v4.2.beta.custom_build [0e0420329]
image

File: drivers/gles3/storage/material_storage.h [hunk 1]
```diff
@@ -316,10 +326,7 @@ struct SceneShaderData : public ShaderData {
 	bool uses_bones;
 	bool uses_weights;
 
-	uint64_t vertex_input_mask = 0;
-
-	uint64_t last_pass = 0;
-	uint32_t index = 0;
```
Comment (YuriSizov) [inline drivers/gles3/storage/material_storage.h:322]: I can see that they are probably unused, but are you sure?

**Review by YuriSizov — APPROVED** [review]
Superficially it looks okay, but I would wait for the rendering team to confirm. The composition and order in the header may matter, and can't judge if your changes there are safe.

File: drivers/gles3/storage/material_storage.h (hunk 1 above)
Comment (akien-mga) [reply drivers/gles3/storage/material_storage.h:322]: It wouldn't compile if they were used anywhere.

**Comment by jsjtxietian** [comment]
> Yes, this appears to fix the issue entirely:

Same for me.

**Review by clayjohn — APPROVED** [review]
Looks great to me! In theory it doesn't matter if we initialize before or after the early return as we set valid to false (so the shader should be ignored anyway). But I think its  safer to initialize before to ensure everything is default and we aren't accidentally relying on old state.
