### PR TITLE
Fix mixed smoothed and non-smoothed face normals computation for CSG shapes

### LINKED ISSUE #49800: CSGCylinder3D has incorrect normals compared to the CylinderMesh primitive
*See also https://github.com/godotengine/godot/issues/19143.*

### Godot version

4.0.dev (6d98f84ab), 3.3.2

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 465.31)

### Issue description

CSGCylinder3D has incorrect normals compared to the CylinderMesh primitive.

CSGTorus3D also has unexpected normals compared to a torus exported from Blender (due to a sharp line in the middle), but it's not as bad.

*Top: CSG nodes (torus, box, sphere, cylinder) or meshes (Suzannes, sharp cylinder).
Bottom: MeshInstances with primitive meshes (box, sphere, smooth cyulinder) or OBJs exported from Blender (torus, Suzannes, sharp cylinder).*

image

This also occurs on 3.3.2. CSGCylinder on top, MeshInstance with CylinderMesh at the bottom:

image

### Steps to reproduce

- Create a CSGCylinder node and set the number of sides to 64 to match a CylinderMesh.
- Create a MeshInstance node, add a CylinderMesh to it.
- Place the MeshInstance above/below the CSGCylinder and compare the lighting on both.

### Minimal reproduction project

- `master`: [test_csg_normals.zip](https://github.com/godotengine/godot/files/6687192/test_csg_normals.zip)
- `3.x`: [test_csg_normals_3.x.zip](https://github.com/godotengine/godot/files/6687266/test_csg_normals_3.x.zip)

### PR DESCRIPTION
**Pull request by MythTitans**
When computing smoothed normals on CSG shapes, the normals from all the faces sharing a vertex are averaged together to compute the smoothed "shared" normal between the faces.

I don't think the behavior is correct, because it means that even faces that are not smoothed participate to the computation of their smooth neighbor's faces.

The problem is particularly visible when substracting a sphere or a torus from a box, at the edge between them :

**Before**
smooth_normals_before

**After**
smooth_normals_after

and also on the cylinder which has a strange shading (and a small glitch is visible at the bottom left) :

**Before**
cylinder_bottom_before

**After**
cylinder_bottom_after

This is related to some comments in #49800.

Bugsquad edit:
- Fixes #49800

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @hoontee

File: modules/csg/csg_shape.cpp [hunk 1]
```diff
@@ -303,17 +303,20 @@ void CSGShape3D::_update_shape() {
...
-				add += p.normal;
-			} else {
-				add = p.normal;
+			for (int j = 0; j < 3; j++) {
+				Vector3 v = n->faces[i].vertices[j];
+				Vector3 add;
+				if (vec_map.lookup(v, add)) {
+					add += p.normal;
+				}
+				else {
```
Comment (hoontee) [inline modules/csg/csg_shape.cpp:315]: Works as it should! Be sure to fix this extra newline though. :)

**Review by hoontee — CHANGES_REQUESTED** [review]

**Comment by hoontee** [comment]
Fixes #49800.

**Comment by akien-mga** [comment]
After fixing the style issue, be sure to rebase to squash the commits into one (see https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase).

**Comment by Calinou** [comment]
By the way, this likely supersedes https://github.com/godotengine/godot-proposals/issues/1862. Great work :slightly_smiling_face:

**Comment by MythTitans** [comment]
@akien-mga Thanks, I'll read and try that

**Comment by hoontee** [comment]
> By the way, this likely supersedes [godotengine/godot-proposals#1862](https://github.com/godotengine/godot-proposals/issues/1862). Great work 🙂

No, there are still instances where angle based smoothing would be appreciable. Note the odd lighting on the cylinder due to a lack of hard edges around the sphere negation:
image

**Review by hoontee — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.4.
