### PR TITLE
Fix crash when saving resources with circular references

### LINKED ISSUE #60590: Segmentation fault when setting exported value to self in imported resource
### Godot version

3.4.4

### System information

Linux

### Issue description

When writing a custom importer plugin that imports a resource which sets a member to `self` Godot crashes with a segmentation fault. This happens when the value is set to `self` directly, or when used inside another datatype like a dictionary or array.

This is expected to fail, but should not lead to a segfault.

### Steps to reproduce

Write a resource importer and set a member to `self` in the imported resource.

```gdscript
extends Resource

export var value: Resource

func _init() -> void:
	value = self
	# segfault
```

### Minimal reproduction project

This project crashes when trying to import `test.json`.

[Dictionary Crash.zip](https://github.com/godotengine/godot/files/8584820/Dictionary.Crash.zip)

### PR DESCRIPTION
**Pull request by maximkulkin**
When saving resources, marking of already seen resources was done too late, causing infinite loop traversing referenced resources and eventual stack overflow. The change marks traversed resource before descending to it's children, thus when this resource is encountered again, it is already marked as seen and traversal stops.

Fixes #60590

### CODE REVIEW

**Comment by fire** [comment]
Any idea why the build tests are failing?

**Comment by maximkulkin** [comment]
I haved pulled back support for saving circular references as it can cause memory leaks. Instead I narrowed this change down to fixing crash when saving resources with circular references.

File: scene/resources/resource_format_text.cpp [hunk 1]
```diff
@@ -1812,8 +1814,7 @@ void ResourceFormatSaverTextInstance::_find_resources(const Variant &p_variant,
 				I = I->next();
 			}
 
-			resource_set.insert(res); //saved after, so the children it needs are available when loaded
-			saved_resources.push_back(res);
+			saved_resources.push_back(res);  //saved after, so the children it needs are available when loaded
```
Comment (akien-mga) [inline scene/resources/resource_format_text.cpp:1817]:
```suggestion
			saved_resources.push_back(res); // Saved after, so the children it needs are available when loaded.
```

**Comment by akien-mga** [comment]
Looks good to me overall, but needs a review from @reduz to make sure it's correct.
As this is sensitive code and fixes a rare problem, we can wait for after the 4.0 release (and cherry-pick the fix to 4.0.x eventually).

**Review by RandomShaper — APPROVED** [review]
To me, looks good to go and be tested in early 4.2 dev releasese.

**Comment by YuriSizov** [comment]
I rebased and force-pushed it on your behalf because it's been many months since the last update. Just in case there may be problems or new checks on CI.

**Comment by YuriSizov** [comment]
Thanks!
