### PR TITLE
Fix TextureButton's click mask texture size ignored if missing normal texture

### LINKED ISSUE #91898: TextureButton click mask doesn't scale correctly without other textures present
### Tested versions

Found in v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19045 - GLES3 (Compatibility) - Intel(R) HD Graphics (Intel Corporation; 20.19.15.4835) - Intel(R) Pentium(R) CPU G3258 @ 3.20GHz (2 Threads)

### Issue description

A TextureButton has several texture slots, including Normal, Pressed, Hover, and Click Mask.

It looks like the texture scaling options (e.g. "Keep Aspect Covered") only work correctly for the Click Mask if there is another texture slot filled with a texture, AND if that slot is currently being used.

For example, if you only put a texture into Hover and Click Mask, then the Click Mask texture will be incorrectly scaled until the mouse enters the (incorrect) Click Mask area, at which point the Hover texture gets enabled, and the Click Mask is then scaled correctly. This potentially results in the mouse now being outside the clickable area, in which case the hover state will flicker rapidly between entered and exited as you move the mouse around.

If you have a button with a Normal texture, then the Click Mask is always scaled correctly, so the issue doesn't occur:

image

### Steps to reproduce

No scripting required. 

Create a TextureButton with a Hover texture and a Click Mask bitmap. Set the scaling options to ignore texture size, and keep aspect covered. The click mask will only be scaled correctly when the button is in the hovered state. 

See MRP - there are two TextureButtons which are identical - the only difference between them is that the top one has a Normal texture, so its click mask is always scaled correctly. The second button does not, and so the click mask is not scaled correctly. If you copy and paste the normal texture from the top button to the bottom button then it will start working correctly.

### Minimal reproduction project (MRP)

[Click mask minimal.zip](https://github.com/godotengine/godot/files/15292823/Click.mask.minimal.zip)

### PR DESCRIPTION
**Pull request by semensanyok**
* fixes #91898

~~although click/hover now works correctly, precisely detecting expected borders, it logs error for abscent "normal" texture.~~
```
scene\main\canvas_item.cpp:785 - Condition "p_texture.is_null()" is true
```
~~not sure what to do with that message yet, and if it needs to be fixed or not. is error message in case of missing normal texture expected?~~
fixed error log message https://github.com/godotengine/godot/pull/92222/files#diff-d9ffa969dbdabac1b846bcdcddd360802270fcabb040bae52bde2a3ab549c423#241:~:text=%7D%20else%20if%20(texdraw.is_valid())%20%7B

### CODE REVIEW

File: scene/gui/texture_button.cpp [hunk 1]
```diff
@@ -124,6 +124,10 @@ void TextureButton::_notification(int p_what) {
 			DrawMode draw_mode = get_draw_mode();
 
 			Ref<Texture2D> texdraw;
+			Ref<BitMap> texdraw_bitmap;
```
Comment (KoBeWi) [inline scene/gui/texture_button.cpp:127]: What's the purpose of this variable if it's never re-assigned? Why not just use `click_mask`?

File: scene/gui/texture_button.cpp [hunk 2]
```diff
@@ -178,13 +182,16 @@ void TextureButton::_notification(int p_what) {
 				texdraw = focused;
 			}
 
-			if (texdraw.is_valid()) {
-				size = texdraw->get_size();
-				_texture_region = Rect2(Point2(), texdraw->get_size());
+			if (texdraw.is_valid() || texdraw_bitmap.is_valid()) {
+				Size2 texdraw_size = texdraw.is_valid() ? texdraw->get_size() : Size2(texdraw_bitmap->get_size());
```
Comment (KoBeWi) [inline scene/gui/texture_button.cpp:186]:
```suggestion
				const Size2 texdraw_size = texdraw.is_valid() ? texdraw->get_size() : Size2(texdraw_bitmap->get_size());
```

File: scene/gui/texture_button.cpp [hunk 3]
```diff
@@ -178,13 +182,16 @@ void TextureButton::_notification(int p_what) {
...
+				float texdraw_height = texdraw.is_valid() ? texdraw->get_height() : texdraw_size.height;
+				float texdraw_width = texdraw.is_valid() ? texdraw->get_width() : texdraw_size.width;
```
Comment (KoBeWi) [inline scene/gui/texture_button.cpp:188]: These variables don't make sense. You can just always use `texdraw_size.height`.

**Comment by KoBeWi** [comment]
I don't like how this makes an empty draw just to calculate texture size 🤔 But it's a pre-existing logic, so for now it works I guess.

File: scene/gui/texture_button.cpp (hunk 1 above)
Comment (semensanyok) [reply scene/gui/texture_button.cpp:127]: Because its used to get size, its meaning as "click_mask" is not relevant in this context. Its only used as `BitMap` to fallback to, to get button region size. I've created it because I couldnt cast Bitmap to Texture2D, nor find common general type. So I've decided to logically link it to `Ref<Texture2D> texdraw;`. Mostly for clarity's sake, not necessary.

Comment (KoBeWi) [reply scene/gui/texture_button.cpp:127]: If it's not necessary then remove it. It doesn't help clarity that much.

Comment (semensanyok) [reply scene/gui/texture_button.cpp:127]: Also thought that it might be assigned some other bitmap, not only click_mask, to fallback to some other object

Comment (KoBeWi) [reply scene/gui/texture_button.cpp:127]: When that happens the new variable can be added. Right now it's redundant.

Comment (semensanyok) [reply scene/gui/texture_button.cpp]: ok, removed

File: scene/gui/texture_button.cpp (hunk 2 above)
Comment (semensanyok) [reply scene/gui/texture_button.cpp]: applied

File: scene/gui/texture_button.cpp (hunk 3 above)
Comment (semensanyok) [reply scene/gui/texture_button.cpp]: true, although not that apparent, applied suggestion

**Review by KoBeWi — APPROVED** [review]

File: scene/gui/texture_button.cpp [hunk 4]
```diff
@@ -217,10 +217,9 @@ void TextureButton::_notification(int p_what) {
 					} break;
 					case STRETCH_KEEP_ASPECT_COVERED: {
 						size = get_size();
-						Size2 tex_size = texdraw->get_size();
-						Size2 scale_size(size.width / tex_size.width, size.height / tex_size.height);
+						Size2 scale_size(size.width / texdraw_size.width, size.height / texdraw_size.height);
```
Comment (AThousandShips) [inline scene/gui/texture_button.cpp:220]:
```suggestion
						Size2 scale_size = size / texdraw_size;
```
Simplification

**Review by AThousandShips — APPROVED** [review]

File: scene/gui/texture_button.cpp (hunk 4 above)
Comment (semensanyok) [reply scene/gui/texture_button.cpp]: applied

**Comment by akien-mga** [comment]
Thanks!
