### PR TITLE
Fix drive selection issue on Android

### LINKED ISSUE #64809: Can't switch to SD card in file dialogs in the Android editor
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

3.5 Stable

### System information

ChromeOS, Pentium 7505

### Issue description

the file manager within Godot on android is unable to be switched to my SD card, despite giving android apps access to SD card files

### Steps to reproduce

launch godot
click new project
Click browse on project path
at the top, click the drive dropdown, and attempt to switch to SD_Card

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by syntaxerror247**
Fixes https://github.com/godotengine/godot/issues/64809

### CODE REVIEW

**Comment by Alex2782** [comment]
On which devices have you tested it so far? (+Android version)

**Comment by syntaxerror247** [comment]
> On which devices have you tested it so far? (+Android version)

Moto g9 play Android 11 and Android 16 emulator.

**Comment by syntaxerror247** [comment]
Note: getDrive() method only works on API 30+ because `storageVolume.getDirectory()` is added in API 30 and I couldn't find any other reliable way to get the drive path on older versions.

File: platform/android/java/lib/src/org/godotengine/godot/io/directory/FilesystemDirectoryAccess.kt [hunk 1]
```diff
@@ -159,7 +159,11 @@ internal class FilesystemDirectoryAccess(private val context: Context, private v
 		}
 
 		val storageVolume = storageManager.storageVolumes[drive]
-		return storageVolume.getDescription(context)
+		return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
+			storageVolume.directory?.absolutePath ?: ""
+		} else {
+			""
```
Comment (Alex2782) [inline platform/android/java/lib/src/org/godotengine/godot/io/directory/FilesystemDirectoryAccess.kt:165]: I tested without SD card (only internal storage).
I also have a Chromebook where I could try to test an external USB hard drive


```suggestion
			storageVolume.getDescription(context)
```

---------------

Node: `FileDialog`
`access` = `File System`

---------------

Empty String looks strange in FileDialog.
_(I think on Android 7 to 10 devices we can continue to display the name as it was before.)_


<details><summary>Video: empty String</summary>

https://github.com/user-attachments/assets/38884628-0bf5-4361-a33f-576f29b11f62

</details>

`storageVolume.directory?.absolutePath ?: ""`

When exactly can `directory` be `null` here? The dropdown list would also look strange.

-------------

`storageVolume.getDescription(context)`
Most Android users are more familiar with the localized name.

image


-------------

This PR: `storageVolume.directory?.absolutePath`

It also looks odd having it appear twice, in the input field and the selection list. 
Isn't there another better solution to resolve the selection issues? 

The correct approach would be to evaluate the volume index number (new API `get_drive_path`), but more changes would probably be needed in the core and the GD API. I think `DirAccess.get_drive_name` should continue to return the name as it did before.

image

**Review by Alex2782 — CHANGES_REQUESTED** [review]

File: platform/android/java/lib/src/org/godotengine/godot/io/directory/FilesystemDirectoryAccess.kt (hunk 1 above)
Comment (syntaxerror247) [reply platform/android/java/lib/src/org/godotengine/godot/io/directory/FilesystemDirectoryAccess.kt:165]: I believe that it should return empty string instead of description. There's no point of returning description and showing a available drive if we can't switch to that drive. That would create confusion.

Comment (syntaxerror247) [reply platform/android/java/lib/src/org/godotengine/godot/io/directory/FilesystemDirectoryAccess.kt:165]: > When exactly can directory be null here? The dropdown list would also look strange.

If volume is not mounted, getDirectory() would return null, so `DisplayServer.get_drive_name()` would return empty string.

Comment (syntaxerror247) [reply platform/android/java/lib/src/org/godotengine/godot/io/directory/FilesystemDirectoryAccess.kt:165]: I think it's an issue with FileDialog that it isn't able to properly handle the empty string. It should just hide the drive switching node.

Comment (syntaxerror247) [reply platform/android/java/lib/src/org/godotengine/godot/io/directory/FilesystemDirectoryAccess.kt:165]: > It also looks odd having it appear twice, in the input field and the selection list.
Isn't there another better solution to resolve the selection issues?
> 
> The correct approach would be to evaluate the volume index number (new API get_drive_path), but more changes would probably be needed in the core and the GD API. I think DirAccess.get_drive_name should continue to return the name as it did before.

Yeah, it looks a bit odd to directly show the path for drive but that's how it's done for other platforms too. We can create a new method for getting path, or we can modify the get_drive_name() to return a array instead of string, eg. [drive_name, drive_path].
But these changes warrent a discussion with other platforms first and won't be able to be merged for 4.5 now. I wanted to fix this in 4.5 itself so folks won't have to wait for another release for this fix and fortunately current fix is simple and safe.

**Review by Alex2782 — APPROVED** [review]
Tested on Samsung Tab S7, Android 13, changing path to an SD card worked.

I was able to find a code for Android 7-10 to read paths ([link](https://gist.github.com/PauloLuan/4bcecc086095bce28e22?permalink_comment_id=2609277#gistcomment-2609277)), but changing the path didn't work. (see below) If anyone knows the cause, we can create a new PR.


------------

<details><summary>FileDialog test on MacOS</summary>

I checked the behavior more closely under macOS with several external USB hard drives; `FileDialog::_select_drive` requires a path and doesn't work with a name. 


```cpp
void FileDialog::_select_drive(int p_idx) {
	String d = drives->get_item_text(p_idx);
	_change_dir(d);
	filename_edit->set_text("");
	_push_history();
}
```

</details>

--------------

<details><summary>Code for Android 7 - 10 </summary>

```kotlin
	override fun getDrive(drive: Int): String {
		if (drive < 0 || drive >= storageManager.storageVolumes.size) {
			return ""
		}

		val storageVolume = storageManager.storageVolumes[drive]
		return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
			storageVolume.directory?.absolutePath ?: ""
		} else {
			@SuppressLint("DiscouragedPrivateApi")
			try {
				val method = storageVolume.javaClass.getMethod("getPath")
				method.invoke(storageVolume) as? String ?: ""
			} catch (e: Exception) {
				""
			}
		}
	}

```



image

image


</details>

**Comment by Repiteo** [comment]
Thanks!
