### PR TITLE
Fix various missing rendering parameter checks

### LINKED ISSUE #65964: Executing `MultiMesh.set_buffer` crashes Godot 4 with GLES 3
### Godot version

4.0.alpha.custom_build. 4b164b8e4

### System information

Ubuntu 22.04 - Nvidia GTX 970, Gnome shell 42 X11

### Issue description

When executing
```
	var temp_variable1568 = MultiMesh.new()
	temp_variable1568.set_use_custom_data(true)
	temp_variable1568.set_instance_count(63)
	temp_variable1568.set_buffer(PackedFloat32Array([-34.0615577697754, 16.3072357177734, 72.6118927001953, 23.3701820373535, 36.1846084594727, 52.9697532653809, 80.0455932617188, -60.7722778320312, -75.6709136962891, 0, -88.4446563720703, -95.5857696533203, 57.1156387329102, -72.9740600585938, 47.3331680297852, 57.8901901245117, -61.8709106445312, 53.0345916748047, 98.7736358642578, -71.5628433227539, -88.2134552001953, -97.6910247802734, -25.4826774597168, -2.17281579971313, 15.4755830764771]))
```

Godot crashes with this backtrace
```
=================================================================
==23986==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60d0008a2750 at pc 0x00000b38f84f bp 0x7fff07283b20 sp 0x7fff07283b10
READ of size 4 at 0x60d0008a2750 thread T0
    #0 0xb38f84e in GLES3::MeshStorage::multimesh_set_buffer(RID, Vector<float> const&) drivers/gles3/storage/mesh_storage.cpp:1321
    #1 0x1840bb23 in RenderingServerDefault::multimesh_set_buffer(RID, Vector<float> const&) servers/rendering/rendering_server_default.h:334
    #2 0x15b3b7fb in MultiMesh::set_buffer(Vector<float> const&) scene/resources/multimesh.cpp:198
    #3 0x15799d0c in void call_with_variant_args_helper<__UnexistingClass, Vector<float> const&, 0ul>(__UnexistingClass*, void (__UnexistingClass::*)(Vector<float> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) core/variant/binder_common.h:262
    #4 0x1579689a in void call_with_variant_args_dv<__UnexistingClass, Vector<float> const&>(__UnexistingClass*, void (__UnexistingClass::*)(Vector<float> const&), Variant const**, int, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:409
    #5 0x15793648 in MethodBindT<Vector<float> const&>::call(Object*, Variant const**, int, Callable::CallError&) core/object/method_bind.h:320
    #6 0x1ca93fb0 in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:733
    #7 0x1c05d78d in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1048
    #8 0x5c76974 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1555
    #9 0x56ae799 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1627
    #10 0x11e04887 in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:237
    #11 0x11d6a350 in Node::_notification(int) scene/main/node.cpp:56
    #12 0x445ea1f in Node::_notificationv(int, bool) scene/main/node.h:45
    #13 0x1ca9548d in Object::notification(int, bool) core/object/object.cpp:790
    #14 0x11ec4df8 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:917
    #15 0x11eb5ad5 in SceneTree::process(double) scene/main/scene_tree.cpp:465
    #16 0x282bf39 in Main::iteration() main/main.cpp:2992
    #17 0x265ddef in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:538
    #18 0x2644b8f in main platform/linuxbsd/godot_linuxbsd.cpp:72
    #19 0x7f876b3c3d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
    #20 0x7f876b3c3e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f)
    #21 0x264462d in _start (/usr/bin/godot4s+0x264462d)

0x60d0008a2750 is located 0 bytes to the right of 144-byte region [0x60d0008a26c0,0x60d0008a2750)
allocated by thread T0 here:
    #0 0x7f876c014868 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x1b46ee35 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x3c91f51 in CowData<float>::_copy_on_write() core/templates/cowdata.h:236
    #3 0x4544450 in CowData<float>::ptrw() core/templates/cowdata.h:124
    #4 0x4532460 in Vector<float>::ptrw() core/templates/vector.h:82
    #5 0xb38d5cf in GLES3::MeshStorage::multimesh_set_buffer(RID, Vector<float> const&) drivers/gles3/storage/mesh_storage.cpp:1293
    #6 0x1840bb23 in RenderingServerDefault::multimesh_set_buffer(RID, Vector<float> const&) servers/rendering/rendering_server_default.h:334
    #7 0x15b3b7fb in MultiMesh::set_buffer(Vector<float> const&) scene/resources/multimesh.cpp:198
    #8 0x15799d0c in void call_with_variant_args_helper<__UnexistingClass, Vector<float> const&, 0ul>(__UnexistingClass*, void (__UnexistingClass::*)(Vector<float> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) core/variant/binder_common.h:262
    #9 0x1579689a in void call_with_variant_args_dv<__UnexistingClass, Vector<float> const&>(__UnexistingClass*, void (__UnexistingClass::*)(Vector<float> const&), Variant const**, int, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:409
    #10 0x15793648 in MethodBindT<Vector<float> const&>::call(Object*, Variant const**, int, Callable::CallError&) core/object/method_bind.h:320
    #11 0x1ca93fb0 in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:733
    #12 0x1c05d78d in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1048
    #13 0x5c76974 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1555
    #14 0x56ae799 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1627
    #15 0x11e04887 in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:237
    #16 0x11d6a350 in Node::_notification(int) scene/main/node.cpp:56
    #17 0x445ea1f in Node::_notificationv(int, bool) scene/main/node.h:45
    #18 0x1ca9548d in Object::notification(int, bool) core/object/object.cpp:790
    #19 0x11ec4df8 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:917
    #20 0x11eb5ad5 in SceneTree::process(double) scene/main/scene_tree.cpp:465
    #21 0x282bf39 in Main::iteration() main/main.cpp:2992
    #22 0x265ddef in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:538
    #23 0x2644b8f in main platform/linuxbsd/godot_linuxbsd.cpp:72
    #24 0x7f876b3c3d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

SUMMARY: AddressSanitizer: heap-buffer-overflow drivers/gles3/storage/mesh_storage.cpp:1321 in GLES3::MeshStorage::multimesh_set_buffer(RID, Vector<float> const&)


```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

### Steps to reproduce

Run Godot 4 with GLES 3 
```
godot4s --rendering-driver opengl3
```

### Minimal reproduction project

_No response_

### LINKED ISSUE #66374: Executing `RenderingServer.texture_2d_update` crashes GLES3 Godot 4
### Godot version

4.0.alpha.custom_build. 4b164b8e4

### System information

Ubuntu 22.04 - Nvidia GTX 970, Gnome shell 42 X11

### Issue description

When executing
```
var temp_variable1 = RID()
var temp_variable2 = null
var temp_variable3 = 68858
RenderingServer.texture_2d_update(temp_variable1,temp_variable2,temp_variable3)

```

Godot crashes with backtrace
```
drivers/gles3/storage/texture_storage.cpp:715:7: runtime error: member access within null pointer of type 'struct Texture'

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta.custom_build (b809b6d97e94d6c15760146117525398034abeb8)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[1] godot4s() [0x2625930] (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/crash_handler_linuxbsd.cpp:56)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f1dadcc4520] (??:0)
[3] Ref<Image>::unref() (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/object/ref_counted.h:220)
[4] GLES3::TextureStorage::texture_2d_update(RID, Ref<Image> const&, int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/drivers/gles3/storage/texture_storage.cpp:717)
[5] RenderingServerDefault::texture_2d_update(RID, Ref<Image> const&, int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/servers/rendering/rendering_server_default.h:185 (discriminator 2))
[6] void call_with_variant_args_helper<__UnexistingClass, RID, Ref<Image> const&, int, 0ul, 1ul, 2ul>(__UnexistingClass*, void (__UnexistingClass::*)(RID, Ref<Image> const&, int), Variant const**, Callable::CallError&, IndexSequence<0ul, 1ul, 2ul>) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:262 (discriminator 8))
[7] void call_with_variant_args_dv<__UnexistingClass, RID, Ref<Image> const&, int>(__UnexistingClass*, void (__UnexistingClass::*)(RID, Ref<Image> const&, int), Variant const**, int, Callable::CallError&, Vector<Variant> const&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:380)
[8] MethodBindT<RID, Ref<Image> const&, int>::call(Object*, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/object/method_bind.h:320)
[9] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/gdscript/gdscript_vm.cpp:1644 (discriminator 1))
[10] GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/gdscript/gdscript.cpp:1629)
[11] Object::callp(StringName const&, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/object.cpp:711 (discriminator 1))
[12] Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/variant/variant_call.cpp:1048)
[13] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/gdscript/gdscript_vm.cpp:1554)
[14] GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/gdscript/gdscript.cpp:1629)
[15] bool Node::_gdvirtual__process_call<false>(double) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/node.h:237 (discriminator 5))
[16] Node::_notification(int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/node.cpp:57)
[17] Node::_notificationv(int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./scene/main/node.h:45 (discriminator 14))
[18] Object::notification(int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/object.cpp:792)
[19] SceneTree::_notify_group_pause(StringName const&, int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/scene_tree.cpp:867)
[20] SceneTree::process(double) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/scene_tree.cpp:465 (discriminator 4))
[21] Main::iteration() (/home/runner/work/GodotBuilds/GodotBuilds/godot/main/main.cpp:3125)
[22] OS_LinuxBSD::run() (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/os_linuxbsd.cpp:575)
[23] godot4s(main+0x49e) [0x2622bc4] (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/godot_linuxbsd.cpp:74)
[24] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f1dadcabd90] (??:0)
[25] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f1dadcabe40] (??:0)
[26] godot4s(_start+0x2e) [0x262266e] (??:?)
-- END OF BACKTRACE --
================================================================
Aborted (core dumped)


```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### LINKED ISSUE #67067: Executing `RenderingServer.bake_render_uv2` crashes Godot
### Godot version

4.0.beta.custom_build. 1baefceab

### System information

Ubuntu 22.04 - Nvidia GTX 970, Gnome shell 42 X11

### Issue description

When executing
```
	var temp_variable1886 = RID()
	var temp_variable1887 = Array([Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([])])
	var temp_variable1888 = Vector2i(-2, -1)
	RenderingServer.bake_render_uv2(temp_variable1886,temp_variable1887,temp_variable1888)
```
Godot crashes with this backtrace

```
ERROR: Unable to convert array index 0 from 'Array' to 'RID'.
   at: _assign (core/variant/array.cpp:234)
ERROR: vmaCreateImage failed with error -3.
   at: texture_create (drivers/vulkan/rendering_device_vulkan.cpp:1876)
ERROR: vmaCreateImage failed with error -3.
   at: texture_create (drivers/vulkan/rendering_device_vulkan.cpp:1876)
ERROR: vmaCreateImage failed with error -3.
   at: texture_create (drivers/vulkan/rendering_device_vulkan.cpp:1876)
ERROR: vmaCreateImage failed with error -3.
   at: texture_create (drivers/vulkan/rendering_device_vulkan.cpp:1876)
ERROR: vmaCreateImage failed with error -3.
   at: texture_create (drivers/vulkan/rendering_device_vulkan.cpp:1876)

================================================================
handle_crash: Program crashed with signal 8
Engine version: Godot Engine v4.0.beta.custom_build (18177828ad97286ca88cbdcfb763c967858d051b)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[1] godot4s() [0x263d160] (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/crash_handler_linuxbsd.cpp:56)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7fe957e86520] (??:0)
[3] /lib/x86_64-linux-gnu/libnvidia-glcore.so.515.65.01(+0x9db2c2) [0x7fe933bdb2c2] (??:0)
[4] /lib/x86_64-linux-gnu/libnvidia-glcore.so.515.65.01(+0x9db7f4) [0x7fe933bdb7f4] (??:0)
[5] /lib/x86_64-linux-gnu/libnvidia-glcore.so.515.65.01(+0x9db8a9) [0x7fe933bdb8a9] (??:0)
[6] /lib/x86_64-linux-gnu/libnvidia-glcore.so.515.65.01(+0x122f1d0) [0x7fe93442f1d0] (??:0)
[7] /lib/x86_64-linux-gnu/libnvidia-glcore.so.515.65.01(+0x129d85a) [0x7fe93449d85a] (??:0)
[8] /lib/x86_64-linux-gnu/libnvidia-glcore.so.515.65.01(+0x129f7b2) [0x7fe93449f7b2] (??:0)
[9] godot4s(vmaFindMemoryTypeIndexForImageInfo+0x917) [0xc32501d] (/home/runner/work/GodotBuilds/GodotBuilds/godot/thirdparty/vulkan/vk_mem_alloc.h:16392)
[10] RenderingDeviceVulkan::texture_create(RenderingDevice::TextureFormat const&, RenderingDevice::TextureView const&, Vector<Vector<unsigned char> > const&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/drivers/vulkan/rendering_device_vulkan.cpp:1870)
[11] RendererSceneRenderRD::bake_render_uv2(RID, TypedArray<RID> const&, Vector2i const&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/servers/rendering/renderer_rd/renderer_scene_render_rd.cpp:1268 (discriminator 2))
[12] RendererSceneCull::bake_render_uv2(RID, TypedArray<RID> const&, Vector2i const&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/servers/rendering/renderer_scene_cull.cpp:4006)
[13] RenderingServerDefault::bake_render_uv2(RID, TypedArray<RID> const&, Vector2i const&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/servers/rendering/rendering_server_default.h:797 (discriminator 2))
[14] void call_with_variant_args_ret_helper<__UnexistingClass, TypedArray<Image>, RID, TypedArray<RID> const&, Vector2i const&, 0ul, 1ul, 2ul>(__UnexistingClass*, TypedArray<Image> (__UnexistingClass::*)(RID, TypedArray<RID> const&, Vector2i const&), Variant const**, Variant&, Callable::CallError&, IndexSequence<0ul, 1ul, 2ul>) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:680 (discriminator 10))
[15] void call_with_variant_args_ret_dv<__UnexistingClass, TypedArray<Image>, RID, TypedArray<RID> const&, Vector2i const&>(__UnexistingClass*, TypedArray<Image> (__UnexistingClass::*)(RID, TypedArray<RID> const&, Vector2i const&), Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:464)
[16] MethodBindTR<TypedArray<Image>, RID, TypedArray<RID> const&, Vector2i const&>::call(Object*, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/object/method_bind.h:489)
[17] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/gdscript/gdscript_vm.cpp:1644 (discriminator 1))
[18] GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/gdscript/gdscript.cpp:1629)
[19] bool Node::_gdvirtual__process_call<false>(double) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/node.h:237 (discriminator 5))
[20] Node::_notification(int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/node.cpp:57)
[21] Node::_notificationv(int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./scene/main/node.h:45 (discriminator 14))
[22] Object::notification(int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/object.cpp:792)
[23] SceneTree::_notify_group_pause(StringName const&, int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/scene_tree.cpp:867)
[24] SceneTree::process(double) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/scene_tree.cpp:465 (discriminator 4))
[25] Main::iteration() (/home/runner/work/GodotBuilds/GodotBuilds/godot/main/main.cpp:3135)
[26] OS_LinuxBSD::run() (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/os_linuxbsd.cpp:573)
[27] godot4s(main+0x49e) [0x263a3f4] (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/godot_linuxbsd.cpp:74)
[28] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fe957e6dd90] (??:0)
[29] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7fe957e6de40] (??:0)
[30] godot4s(_start+0x2e) [0x2639e9e] (??:?)
-- END OF BACKTRACE --
================================================================

```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by dzil123**
Fixes #65964
Fixes #66374
Fixes #67067

### CODE REVIEW

File: servers/rendering/renderer_rd/renderer_scene_render_rd.cpp [hunk 1]
```diff
@@ -1244,6 +1244,8 @@ float RendererSceneRenderRD::screen_space_roughness_limiter_get_limit() const {
 }
 
 TypedArray<Image> RendererSceneRenderRD::bake_render_uv2(RID p_base, const TypedArray<RID> &p_material_overrides, const Size2i &p_image_size) {
+	ERR_FAIL_COND_V_MSG(p_image_size.width <= 0, TypedArray<Image>(), "Image width must be greater than 0.");
+	ERR_FAIL_COND_V_MSG(p_image_size.height <= 0, TypedArray<Image>(), "Image height must be greater than 0.");
```
Comment (akien-mga) [inline servers/rendering/renderer_rd/renderer_scene_render_rd.cpp:1248]: As seen on #67067 it would likely also crash with width or height higher than Vulkan's `maxFramebufferWidth`, which was 16384 on your Nvidia setup.

I don't know what's the max for other APIs and other drivers but we might want to add a safeguard here too.
Maybe this can or should be queried from the RenderingDevice API. @clayjohn 

But hardcoding 16384 for safety is maybe not a bad idea either to keep it simple.

Comment (clayjohn) [reply servers/rendering/renderer_rd/renderer_scene_render_rd.cpp:1248]: Maximum size can be quered with ``limit_get()``, ``LIMIT_MAX_FRAMEBUFFER_HEIGHT``, and ``LIMIT_MAX_FRAMEBUFFER_WIDTH``

That being said, I think the check should be in ``RD::texture_create()`` which is where the crash is happening. We only validate to ensure the size is at least 1, we should also validate to ensure the size is less than the max:
https://github.com/godotengine/godot/blob/0aba659891f5947d9b55ce7c70aa4d7209369717/drivers/vulkan/rendering_device_vulkan.cpp#L1699

Again, ``limit_get()`` can be used, but with ``LIMIT_MAX_TEXTURE_SIZE_*``

Comment (dzil123) [reply servers/rendering/renderer_rd/renderer_scene_render_rd.cpp:1248]: The largest working texture size is not necessarily `LIMIT_MAX_TEXTURE_SIZE_*` (which comes from Vulkan's `maxImageDimension*`).

According to the spec, any given image type could have a max image size greater than `maxImageDimension*`: 
> [Some combinations of image parameters (format, usage, etc.) may allow support for larger dimensions](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap45.html)
> [Allowed Extent Values Based On Image Type](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap47.html#features-extentperimagetype)

In addition, certain image usage flags use `maxFramebufferWidth/Height`, which may be smaller than `maxImageDimension*`:
> [VUID-VkImageCreateInfo-usage-00964](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap12.html#VUID-VkImageCreateInfo-usage-00964)
> [VUID-VkImageCreateInfo-Format-02536](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap12.html#VUID-VkImageCreateInfo-Format-02536)

I think enforcing a limit of `LIMIT_MAX_TEXTURE_SIZE_*` would forbid some otherwise-valid usecases, and possibly miss other restrictions.

Comment (clayjohn) [reply servers/rendering/renderer_rd/renderer_scene_render_rd.cpp:1248]: Its probably worth investigating what kind of limitation we would be putting on people if we just used ``maxImageDimension``. My guess is that in most cases all image types have the same size limitation. 

However, if there is a big difference I guess we can query max size on a case-by-case basis using [``vkGetPhysicalDeviceImageFormatProperties()``](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap47.html#vkGetPhysicalDeviceImageFormatProperties)

**Review by clayjohn — APPROVED** [review]
It looks like this stalled on us discussing how to properly add a maximum texture size. Since we don't have an obvious solution (and it is kind of beyond the scope of this PR anyway), let's merge this PR in the meantime.

**Comment by akien-mga** [comment]
Thanks!
