### PR TITLE
GDScript: Improve highlighting of types

### LINKED ISSUE #82506: Variant in for loop is not colour coded.
### Godot version

v4.2.dev5.official [e3e2528ba]

### System information

Godot v4.2.dev5 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.3742) - 13th Gen Intel(R) Core(TM) i7-13700K (24 Threads)

### Issue description

When using Variant in a for loop, it does not use the correct colour. (It is grey instead of green)

It is also worth noting that ctrl and clicking on a Variant type does not take you to the docs page.

### Steps to reproduce

Do a for loop and use Variant as the type.

```GDScript

for i: Variant in loop:
    pass
```

### Minimal reproduction project

N/A

### LINKED ISSUE #82775: Missing cases of Variant type syntax highlighting
### Godot version

v4.2.dev6.official [57a6813bb]

### System information

Godot v4.2.dev6 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (NVIDIA; 31.0.15.3742) - Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 Threads)

### Issue description

The type Variant is does not get highlighting in the following situations:

```
signal my_signal(arg:Variant)
```
image

```
func _ready() -> void:
	var _x := func(a:Variant) -> void:
		prints(a)
```

image

### Steps to reproduce

In any script declare a signal with a explicitly typed Variant parameter, or declare an anonymous "lambda" method with a Variant parameter as shown above, and observe the lack of syntax highlighting for the Variant token.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by dalexeev**
* Fixes #82506.
* Fixes #82775.

1. Fix highlighting of `for` loop variable type.
2. Highlight `void`, `bool`, `int`, and `float` as types, not as keywords. This is especially good when there is another keyword next to the type (like `if a is int or a is float`).
3. Fix highlighting of type chains (like `Variant.Type`).
4. Add <kbd>Ctrl+Click</kbd> for `Variant`.

### CODE REVIEW

**Comment by Calinou** [comment]
This also resolves https://github.com/godotengine/godot/issues/44922 :slightly_smiling_face:

**Comment by MewPurPur** [comment]
#82326 is still relevant and not superseded.

**Review by MewPurPur — APPROVED** [review]
Code looks good to me. I'm surprised to see `void` highlighted as a type - it both makes and doesn't make sense to me as a user. Given the context it always pops up in, I think it's better this way.

**Comment by Mickeon** [comment]
Good lord, thank you for making the numeric types green, it was bothering me for so long.

File: modules/gdscript/gdscript.cpp [hunk 1]
```diff
@@ -2368,62 +2368,60 @@ void GDScriptLanguage::frame() {
 
 /* EDITOR FUNCTIONS */
 void GDScriptLanguage::get_reserved_words(List<String> *p_words) const {
-	// TODO: Add annotations here?
 	static const char *_reserved_words[] = {
-		// operators
+		// Control flow.
```
Comment (Scoppio) [inline modules/gdscript/gdscript.cpp:2372]: Please, avoid this kind of reorder, since it does not improve anything and just make the PR artifically bigger and adds confusion on "why" it was done.
No need to fix it, just a thing to keep in mind for the future.

File: modules/gdscript/gdscript.cpp [hunk 2]
```diff
@@ -2368,62 +2368,60 @@ void GDScriptLanguage::frame() {
...
-		"match",
-		"while",
-		"when",
 		// These keywords are not implemented currently, but reserved for (potential) future use.
 		// We highlight them as keywords to make errors easier to understand.
 		"trait",
 		"namespace",
 		"yield",
-		nullptr
+		nullptr,
```
Comment (Scoppio) [inline modules/gdscript/gdscript.cpp:2424]: keep the standard in the project where the last item does not have a trailing comma.

File: modules/gdscript/gdscript.cpp [hunk 3]
```diff
@@ -2432,27 +2430,20 @@ void GDScriptLanguage::get_reserved_words(List<String> *p_words) const {
...
-
-	for (const StringName &E : functions) {
-		p_words->push_back(String(E));
-	}
 }
 
 bool GDScriptLanguage::is_control_flow_keyword(String p_keyword) const {
-	return p_keyword == "break" ||
-			p_keyword == "continue" ||
+	return p_keyword == "if" ||
```
Comment (Scoppio) [inline modules/gdscript/gdscript.cpp:2436]: Why this was changed? There was no need to reorder things here, and it creates no benefit, again, no need to change this PR, but there was also no need to change anything here.

**Review by Scoppio — APPROVED** [review]

File: modules/gdscript/gdscript.cpp (hunk 1 above)
Comment (MewPurPur) [reply modules/gdscript/gdscript.cpp:2372]: There's no confusion IMO, it was done because the comments were used to categorize keywords, and multiple items were wrong

File: modules/gdscript/gdscript.cpp (hunk 2 above)
Comment (dalexeev) [reply modules/gdscript/gdscript.cpp:2424]: As far as I know, there is no such standard. You can check this with a regular expression `,\n\t+}`. You'll find many arrays and enums with a trailing comma, even if no new elements are expected to be added after the last element. For example `MAX,\n\t+}` found 107 matches.

Comment (YuriSizov) [reply modules/gdscript/gdscript.cpp:2424]: I'd say if there is an enforceable rule it would be to add comma always. This is the most VCS-friendly style.

File: modules/gdscript/gdscript.cpp [hunk 4]
```diff
@@ -2432,27 +2430,20 @@ void GDScriptLanguage::get_reserved_words(List<String> *p_words) const {
 		p_words->push_back(*w);
 		w++;
 	}
-
-	List<StringName> functions;
-	GDScriptUtilityFunctions::get_function_list(&functions);
-
-	for (const StringName &E : functions) {
-		p_words->push_back(String(E));
-	}
```
Comment (YuriSizov) [inline modules/gdscript/gdscript.cpp:2441]: What's the justification for removing utility functions from the reserved list with regards to this PR? Also the same question about `float`, `int`, and `bool`, with only `void` being kept out of those types.

Does this affect the highlighter somehow? And what else does this affect.

Comment (dalexeev) [reply modules/gdscript/gdscript.cpp:2441]: > Does this affect the highlighter somehow?

No, the result should be the same, except for intentional changes.

> And what else does this affect.

`get_reserved_words()` is used for code highlighting and to check an identifier in [`EditorAutoloadSettings`](https://github.com/godotengine/godot/blob/19890614c6a78ec36030ce65c7da05f07fcdb9ed/editor/editor_autoload_settings.cpp#L144-L156). I've only left here the keywords listed in [`GDScriptTokenizer`](https://github.com/godotengine/godot/blob/19890614c6a78ec36030ce65c7da05f07fcdb9ed/modules/gdscript/gdscript_tokenizer.cpp#L44) (although [some of them](https://github.com/godotengine/godot/blob/19890614c6a78ec36030ce65c7da05f07fcdb9ed/modules/gdscript/gdscript_tokenizer.cpp#L185-L201) are valid identifiers).

> What's the justification for removing utility functions from the reserved list

Highlighter checks them [separately](https://github.com/godotengine/godot/blob/5052b202385224cf632d58deb717132c16ddc86b/modules/gdscript/editor/gdscript_highlighter.cpp#L704-L713), and utility function names are valid identifiers (`class_name range` is valid).

> Also the same question about `float`, `int`, and `bool`, with only `void` being kept out of those types.

`void` is in the tokenizer, the rest are not. Built-in types are taken into account both in the [highlighter](https://github.com/godotengine/godot/blob/5052b202385224cf632d58deb717132c16ddc86b/modules/gdscript/editor/gdscript_highlighter.cpp#L678-L689) and in [`EditorAutoloadSettings`](https://github.com/godotengine/godot/blob/19890614c6a78ec36030ce65c7da05f07fcdb9ed/editor/editor_autoload_settings.cpp#L124-L132).

**Comment by tokengamedev** [comment]
Is it possible to look into this also, if not let me know, I can create a separate issue.

`set` and `get `are not colored.
image

Thanks

**Comment by dalexeev** [comment]
> Is it possible to look into this also

Given the way highlighter works, the only solution I see is to highlight all `set` and `get` identifiers as method calls. This won't affect identifier parts (like `set_name`), string literals, comments, etc., but `set` and `get` will be highlighted as method calls even without parentheses (if you pass them as `Callable`s). But I think it has more pros than cons.

**Comment by tokengamedev** [comment]
I think get and set are not keywords because they can be method names.
In that case it is ok.
Ideally I thought get and set when not methods(without parentheses) should be treated(highlight only) like keywords

File: modules/gdscript/gdscript.cpp (hunk 1 above)
Comment (akien-mga) [reply modules/gdscript/gdscript.cpp:2372]: Reodering for clarity seems good to me, but I want to make sure the logic used is consistent.

What's the logic used here for both the categories and the order of keywords within each category?
I see e.g. that `token_names` in `gdscript_tokenizer.cpp` has similar but not fully matching categories, and there the tokens are listed alphabetically within each category - like it used to be done here before this change.

If this is based on an enum somewhere, it should be referenced in a comment, ideally in both places so we know what to update whenever the enum changes.

**Comment by dalexeev** [comment]
Highlighting `set` and `get` as keywords or as method definitions depending on the context is possible, but it is more difficult. I think the simple solution looks good for now.

File: modules/gdscript/gdscript.cpp (hunk 1 above)
Comment (dalexeev) [reply modules/gdscript/gdscript.cpp:2373]: I sorted them alphabetically and added comments.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
