### PR TITLE
Fix incorrect cast when animating `int`

### LINKED ISSUE #81289: C# method tweens can't handle 64 bit integer types
### Godot version

v4.2.dev3.mono.official [013e8e3af]

### System information

Windows 11, Godot 4.2-dev3

### Issue description

I wanted to create a Tween that interpolates a method in value range of a long type (64 bit). When the tweened method gets called with values outside the "classical" 32 bit number range (-2147483647 till 2147483647) the method gets only a constant value of -2147483647.

Surprisingly the last call of the tween passes in the correct value then.

### Steps to reproduce

Use the code snippet on any Node C# script (it was a control node in my case):
```
public partial class CurrencyView : Control
{
	public override void _Ready()
	{
		this.SetValue(long.MaxValue);
	}
	
	
	public void SetValue(long value)
	{
		Tween tween = this.CreateTween();
		tween.TweenMethod(new Callable(this, MethodName.OnValueTweener), 0L, value, 0.8d);
	}


	private void OnValueTweener(long value)
	{
		GD.Print(value);
	}
}
```

Then just run any scene with a node in it that has this script attached.
You should see log with the wrong numbers:
```
-2147483648
-2147483648
-2147483648
-2147483648
-2147483648
-2147483648
9223372036854775807
```

### Minimal reproduction project

[tween-bug-project.zip](https://github.com/godotengine/godot/files/12508074/tween-bug-project.zip)

### PR DESCRIPTION
**Pull request by AThousandShips**
Type was cast to `int` rather than `int64_t`

* Fixes: #81289

### CODE REVIEW

File: scene/resources/animation.cpp [hunk 1]
```diff
@@ -5677,7 +5677,7 @@ Variant Animation::interpolate_variant(const Variant &a, const Variant &b, float
 		}
 		case Variant::INT: {
 			const int64_t va = a.operator int64_t();
-			return int(va + ((b.operator int64_t()) - va) * c);
+			return int64_t(va + ((b.operator int64_t()) - va) * c);
 		}
 		case Variant::FLOAT: {
 			const real_t va = a.operator real_t();
```
Comment (akien-mga) [inline scene/resources/animation.cpp:5683]: Related issue: This should be `double`, not `real_t`. `Variant::FLOAT` is always `double`, but it's a common misunderstanding from contributors that it should be `real_t`.

`real_t` is only used for vector types (Vector2*, Transform, etc.).

Comment (akien-mga) [reply scene/resources/animation.cpp:5683]: The whole file seems to use `real_t` for scalars. It could be that it's intentional, or a bug. Maybe best left for a separate issue/PR.

Comment (AThousandShips) [reply scene/resources/animation.cpp:5683]: Will take a look!

Comment (AThousandShips) [reply scene/resources/animation.cpp]: Also found another quirk with the size iteration, fixed

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Comment by YuriSizov** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.3.
