### PR TITLE
Blocking updating in SceneTreeEditor when an item was selected

### LINKED ISSUE #44163: Cannot rename Path node
**Godot version:**
3.2.3.stable

**OS/device including version:**
Windows 10.0.19042.630

**Issue description:**
I added a Path node and a PathFollow node as a child. When I try to rename the Path node, I can edit the name but after I hit enter it reverts to the name "Path". This only seems to happen on a particular scene that I have, I've tried with other scenes and it seems to work fine.

**Steps to reproduce:**
1. Open the project.
2. Open the scene "Main".
3. Click on the node "Path" to rename it,
4. Rename it.
5. Hit enter.

**Minimal reproduction project:**
[squash_the_creeps_start_1.1.0.zip](https://github.com/godotengine/godot/files/5652814/squash_the_creeps_start_1.1.0.zip)

### PR DESCRIPTION
**Pull request by gongpha**
Fixes #44163

The problem is SceneTreeEditor will update itself when warnings had changed. It also will clean itself. So the editing action gets ignored because the selected TreeItem will get cleaned too.

### CODE REVIEW

File: editor/scene_tree_editor.cpp [hunk 1]
```diff
@@ -1088,8 +1088,9 @@ void SceneTreeEditor::_rmb_select(const Vector2 &p_pos) {
 }
 
 void SceneTreeEditor::_warning_changed(Node *p_for_node) {
-	//should use a timer
-	update_timer->start();
+	if (!get_selected())
```
Comment (akien-mga) [inline editor/scene_tree_editor.cpp:1091]: Should use brackets.

**Comment by akien-mga** [comment]
I see how this would prevent the issue, but doesn't it cause other issues? If you edit properties of a selected node in a way that make its configuration invalid, this would cause that the warnings will not appear until you de-select the node/select another one, no?

**Comment by gongpha** [comment]
Oh, I see it. That will cause another problem too. Let me modify it.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
Undid cherry-pick for now as the code for `Tree` changed since `3.x` and the `is_editing()` implementation doesn't compile. Not sure what to replace it with given that `3.x` has `text_editor`, `value_editor` and `popup_menu`.
