### PR TITLE
Windows: Implement native menu close callback

### LINKED ISSUE #100978: PopupMenu with prefer_native_menu=true does not emit popup_hide signal on Windows
### Tested versions

v4.3.stable.mono.official [77dcf97d8]

### System information

Godot v4.3.stable.mono - Windows 10.0.26100 - Vulkan (Forward+) - dedicated AMD Radeon RX 6800M (Advanced Micro Devices, Inc.; 32.0.12033.1030) - AMD Ryzen 9 5980HX with Radeon Graphics (16 Threads)

### Issue description

- When using PopUpMenu to create a right click context menu with prefer_native_menu set to true the popup_hide signal is not emitted. 
- On MacOS with prefer_native_menu set to true the popup_hide signal is emitted as expected. 
- Also when prefer_native_menu is set to false the popup_hide signal is emitted as expected.

### Steps to reproduce

- Create empty project
- Add some Buttons
- Add a PopUpMenu with prefer_native_menu=true
- Add a script that when right click on button calls the PopUpMenu popup() mthod
- In the same script connect the popup_hide signal to a function
- Dismiss the PopUpMenu by clicking somewhere else
- Signal should be emitted

### Minimal reproduction project (MRP)

[bug-popup-menu.zip](https://github.com/user-attachments/files/18282528/bug-popup-menu.zip)

I also recorded a video to better explain the issue.
https://github.com/user-attachments/assets/db3bec37-dbdf-4edb-ba74-f96efda158bb

### PR DESCRIPTION
**Pull request by marcelovbcfilho**
First ever PR to the project, need some help to know if something is wrong and/or if I missed some sort of commit or code style.

This fixes an issue I opened earlier: #100978 where the Windows native menu does not emit the popup_hide signal. The issue has a simple project where you can reproduce the issue and validate that this fixes it.

Video 1: example with the 4.3 stable release

https://github.com/user-attachments/assets/7eb442a5-4504-4bac-95f8-dc9281c61458

Video 2: example with this fix

https://github.com/user-attachments/assets/81db8300-73cd-4d5f-9c8f-78408f967798

*Bugsquad edit:*
- Fixes #100978

### CODE REVIEW

File: platform/windows/native_menu_windows.cpp [hunk 1]
```diff
@@ -177,6 +177,16 @@ void NativeMenuWindows::popup(const RID &p_rid, const Vector2i &p_position) {
 	}
 	SetForegroundWindow(hwnd);
 	TrackPopupMenuEx(md->menu, flags, p_position.x, p_position.y, hwnd, nullptr);
+
+	if (md && md->close_cb.is_valid()) {
```
Comment (bruvzg) [inline platform/windows/native_menu_windows.cpp:181]:
```suggestion
	if (md->close_cb.is_valid()) {
```

It's already checked.

**Review by bruvzg — APPROVED** [review]
Seems to be working fine. Docs should be updated to indicate windows support was added.

```diff
diff --git a/doc/classes/NativeMenu.xml b/doc/classes/NativeMenu.xml
index 2b9e414106..e9e5fee1b6 100644
--- a/doc/classes/NativeMenu.xml
+++ b/doc/classes/NativeMenu.xml
@@ -366,7 +366,7 @@
 			<param index="0" name="rid" type="RID" />
 			<description>
 				Returns global menu close callback.
-				b]Note:[/b] This method is implemented only on macOS.
+				[b]Note:[/b] This method is implemented on macOS and Windows.
 			</description>
 		</method>
 		<method name="get_popup_open_callback" qualifiers="const">
@@ -708,7 +708,7 @@
 			<description>
 				Registers callable to emit when the menu is about to show.
 				[b]Note:[/b] The OS can simulate menu opening to track menu item changes and global shortcuts, in which case the corresponding close callback is not triggered. Use [method is_opened] to check if the menu is currently opened.
-				[b]Note:[/b] This method is implemented only on macOS.
+				[b]Note:[/b] This method is implemented on macOS and Windows.
 			</description>
 		</method>
 		<method name="set_popup_open_callback">
```

File: platform/windows/native_menu_windows.cpp (hunk 1 above)
Comment (marcelovbcfilho) [reply platform/windows/native_menu_windows.cpp]: Fixed, forget that in previous line we are using it.

**Comment by bruvzg** [comment]
Please squash the commits, see [Pull request workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for details.

**Comment by marcelovbcfilho** [comment]
Hey followed the docs instruction, is this how is was supposed to be?

**Comment by bruvzg** [comment]
> is this how is was supposed to be?

Yes, everything looks good.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
