### PR TITLE
Fix crash when trying to undo SpriteFrames animation rename

### LINKED ISSUE #92600: AnimatedSprite2D bottom panel closes when adding/removing animation
### Tested versions

Only in 4.3 dev 6 and 4.3-beta-1
This not happens in 4.2.x

### System information

Godot v4.3.beta1 - openSUSE Tumbleweed 20240524 - Wayland - Vulkan (Mobile) - dedicated AMD Radeon RX 6600 (RADV NAVI23) () - AMD Ryzen 7 5700G with Radeon Graphics (16 Threads)

### Issue description

When creates a new Animation in AnimatedSprite2D, closes the bottom panel. I thought it was Wayland so, switched to original config, and still.

### Steps to reproduce

- Create a new AnimatedSprite2D
- Click in SpriteFrames <empty>
- New SpriteFrames
- Click in SpriteFrames to show the botton panel SpriteFrames
- Here, After click: Add Animation or Delete Animation, Closes the Botton panel "Sprite Frames".

image

### Minimal reproduction project (MRP)

With a new project

### LINKED ISSUE #93079: Crash when trying to undo SpriteFrames animation rename
### Tested versions

4.3 beta1
4.3 dev6
Not sure when it started.

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

```
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.3.beta.custom_build (2fb296a5cd83bfa7a234cfcaae78a63da3556fb8)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] HashMap<StringName,SpriteFrames::Anim,HashMapHasherDefault,HashMapComparatorDefault<StringName>,DefaultTypedAllocator<HashMapElement<StringName,SpriteFrames::Anim> > >::_lookup_pos (C:\godot_source\core\templates\hash_map.h:100)
[1] HashMap<StringName,SpriteFrames::Anim,HashMapHasherDefault,HashMapComparatorDefault<StringName>,DefaultTypedAllocator<HashMapElement<StringName,SpriteFrames::Anim> > >::_lookup_pos (C:\godot_source\core\templates\hash_map.h:100)
[2] HashMap<StringName,SpriteFrames::Anim,HashMapHasherDefault,HashMapComparatorDefault<StringName>,DefaultTypedAllocator<HashMapElement<StringName,SpriteFrames::Anim> > >::has (C:\godot_source\core\templates\hash_map.h:311)
[3] SpriteFrames::has_animation (C:\godot_source\scene\resources\sprite_frames.cpp:107)
[4] SpriteFramesEditor::_select_animation (C:\godot_source\editor\plugins\sprite_frames_editor_plugin.cpp:956)
[5] call_with_variant_args_helper<SpriteFramesEditor,String const &,bool,0,1> (C:\godot_source\core\variant\binder_common.h:304)
[6] call_with_variant_args_dv<SpriteFramesEditor,String const &,bool> (C:\godot_source\core\variant\binder_common.h:452)
[7] MethodBindT<SpriteFramesEditor,String const &,bool>::call (C:\godot_source\core\object\method_bind.h:347)
[8] Object::callp (C:\godot_source\core\object\object.cpp:841)
[9] Callable::callp (C:\godot_source\core\variant\callable.cpp:69)
[10] CallableCustomBind::call (C:\godot_source\core\variant\callable_bind.cpp:153)
[11] Callable::callp (C:\godot_source\core\variant\callable.cpp:58)
[12] UndoRedo::_process_operation_list (C:\godot_source\core\object\undo_redo.cpp:366)
[13] UndoRedo::undo (C:\godot_source\core\object\undo_redo.cpp:431)
[14] EditorUndoRedoManager::undo_history (C:\godot_source\editor\editor_undo_redo_manager.cpp:285)
[15] EditorUndoRedoManager::undo (C:\godot_source\editor\editor_undo_redo_manager.cpp:272)
[16] EditorNode::_menu_option_confirm (C:\godot_source\editor\editor_node.cpp:2801)
[17] EditorNode::_menu_option (C:\godot_source\editor\editor_node.cpp:1423)
[18] call_with_variant_args_helper<EditorNode,int,0> (C:\godot_source\core\variant\binder_common.h:309)
[19] call_with_variant_args<EditorNode,int> (C:\godot_source\core\variant\binder_common.h:419)
[20] CallableCustomMethodPointer<EditorNode,int>::call (C:\godot_source\core\object\callable_method_pointer.h:104)
[21] Callable::callp (C:\godot_source\core\variant\callable.cpp:58)
[22] Object::emit_signalp (C:\godot_source\core\object\object.cpp:1221)
[23] Node::emit_signalp (C:\godot_source\scene\main\node.cpp:3891)
[24] Object::emit_signal<int> (C:\godot_source\core\object\object.h:936)
[25] PopupMenu::activate_item (C:\godot_source\scene\gui\popup_menu.cpp:2426)
[26] PopupMenu::activate_item_by_event (C:\godot_source\scene\gui\popup_menu.cpp:2348)
[27] MenuBar::shortcut_input (C:\godot_source\scene\gui\menu_bar.cpp:166)
[28] Node::_call_shortcut_input (C:\godot_source\scene\main\node.cpp:3357)
[29] SceneTree::_call_input_pause (C:\godot_source\scene\main\scene_tree.cpp:1244)
[30] Viewport::_push_unhandled_input_internal (C:\godot_source\scene\main\viewport.cpp:3298)
[31] Viewport::push_input (C:\godot_source\scene\main\viewport.cpp:3259)
[32] Window::_window_input (C:\godot_source\scene\main\window.cpp:1689)
[33] call_with_variant_args_helper<Window,Ref<InputEvent> const &,0> (C:\godot_source\core\variant\binder_common.h:304)
[34] call_with_variant_args<Window,Ref<InputEvent> const &> (C:\godot_source\core\variant\binder_common.h:419)
[35] CallableCustomMethodPointer<Window,Ref<InputEvent> const &>::call (C:\godot_source\core\object\callable_method_pointer.h:104)
[36] Callable::callp (C:\godot_source\core\variant\callable.cpp:58)
[37] Callable::call<Ref<InputEvent> > (C:\godot_source\core\variant\variant.h:876)
[38] DisplayServerWindows::_dispatch_input_event (C:\godot_source\platform\windows\display_server_windows.cpp:3510)
[39] DisplayServerWindows::_dispatch_input_events (C:\godot_source\platform\windows\display_server_windows.cpp:3481)
[40] Input::_parse_input_event_impl (C:\godot_source\core\input\input.cpp:774)
[41] Input::flush_buffered_events (C:\godot_source\core\input\input.cpp:1053)
[42] DisplayServerWindows::process_events (C:\godot_source\platform\windows\display_server_windows.cpp:2978)
[43] OS_Windows::run (C:\godot_source\platform\windows\os_windows.cpp:1686)
[44] widechar_main (C:\godot_source\platform\windows\godot_windows.cpp:181)
[45] _main (C:\godot_source\platform\windows\godot_windows.cpp:206)
[46] main (C:\godot_source\platform\windows\godot_windows.cpp:220)
[47] WinMain (C:\godot_source\platform\windows\godot_windows.cpp:234)
[48] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[49] <couldn't map PC to fn name>
-- END OF BACKTRACE --
```

### Steps to reproduce

1. Create AnimatedSprite2D
2. Add SpriteFrames
3. In the SpriteFrames tab, rename the default animation
4. The bottom panel closes for no reason
5. Press Ctrl+Z

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Hilderin**
Fixes #93079 
*Bugsquad edit:* Also fixes #92600

The problem was introduced by PR #90815. As suggested by KoBeWi in that PR, I modified the verification to check if the new SpriteFrames is different. I removed the method `is_editing` because I found it redundant with `get_sprite_frames`.

Tested with renaming animations, Ctrl-Z, adding animations, and removing animations.

### CODE REVIEW

**Comment by matheusmdx** [comment]
This pr also fixes #92600

File: editor/plugins/sprite_frames_editor_plugin.cpp [hunk 1]
```diff
@@ -2337,7 +2337,11 @@ bool SpriteFramesEditorPlugin::handles(Object *p_object) const {
 	if (animated_sprite_3d && *animated_sprite_3d->get_sprite_frames()) {
 		return true;
 	}
-	return !frames_editor->is_editing() && Object::cast_to<SpriteFrames>(p_object);
+	SpriteFrames *frames = Object::cast_to<SpriteFrames>(p_object);
+	if (frames && (frames_editor->get_sprite_frames().is_null() || frames_editor->get_sprite_frames() == frames)) {
```
Comment (KoBeWi) [inline editor/plugins/sprite_frames_editor_plugin.cpp:2341]: I don't get the last condition. "if the new SpriteFrames is the same as already edited SpriteFrames then edit them again" is basically what this means, unless I'm missing something.
This could mean that the old reference is not cleared properly and/or the editor tries to edit the same resource twice.

Comment (Hilderin) [reply editor/plugins/sprite_frames_editor_plugin.cpp:2341]: When renaming an animation, the `frames` variable in `frames_editor` is still there with the current SpriteFrames. So the problem was that the previous `is_edited` method was returning true, causing the plugin to close. Maybe `frames` should have been cleared on a rename?

Comment (KoBeWi) [reply editor/plugins/sprite_frames_editor_plugin.cpp:2341]: Renaming an animation will update the inspector, which leads to `handles()` + `edit()` and then another `handles()` call. So I guess the original assumption that the editor won't check the same resource twice was wrong. It correctly edits it only once though, so it's fine.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
