### PR TITLE
Fix constants scope in extended or inner GDScript classes

### LINKED ISSUE #69586: [GDScript 2.0] Constants declared in a parent class cannot be used as typing type in an extended class
### Godot version

4.0.dev (015dc49)

### System information

Linux (Ubuntu 22.04), Vulkan, Radeon RX Vega 64 (eGPU)

### Issue description

```gdscript
# a.gd
extends Resource
```

```gdscript
# base.gd
extends Resource
const A: = preload("res://a.gd")
```

```gdscript
# extend.gd
extends "base.gd"

static func test(a: A) -> void:
	print(A)
```

The editor will complain with this error in `extend.gd`: `Error at (4, 19): "A" was not found in the current scope.`.

But removing the typing from `test()` (`static func test(a) -> void:`), the following line will print without any issues.
`<GDScript#-9223372009658908249>`

It's not possible too to declare something like `const A: = preload("res://a.gd")` inside `extend.gd` as it will result with this error: `The member "A" already exists in parent class res://base.gd.`

Extended classes should be able to use constants declared inside the base class the same way it is possible to use them inside that said base class.

### Steps to reproduce

1. Create a base class
2. Create an extend class
3. Declare a constant that preloads a class in the base class
4. Try to use that constant as a type inside the extend class

### Minimal reproduction project

[69586.zip](https://github.com/godotengine/godot/files/10149562/69586.zip)

### PR DESCRIPTION
**Pull request by adamscott**
**~~This PR depends on #69865~~ Merged, thanks**

Especially when checking the typing, the gdscript parser doesn't seem to pass through the code to set the right `script_class->outer` value for a given `GDScriptParser::ClassNode`. It is available though inside `script_class->base_type.class_type` in `GDScriptAnalyzer::resolve_datatype()`.

~~So this PR uses `script_class->base_type.class_type` if the `script_class->outer` is a `nullptr`.~~

Edit: I updated the logic! It now checks for outer classes and their extended classes, without the need of adding one more loop. I prioritized the outer classes first, as this was the logic as for now.

This code now works:

```gdscript
# `base.gd` declares `A`
extends "base.gd"

const OuterDeclared: = "OuterDeclared"

static func test(a: A) -> void:
	print(A)  # prints <GDScript #...>

# `base_inner.gd` declares `B`
class InnerBaseClass extends "base_inner.gd":
	static func test_a(a: A) -> void:
		print(OuterDeclared)  # prints "OuterDeclared"
		print(A)  # prints <GDScript #...>

	static func test_b(b: B) -> void:
		print(B)  # prints <GDScript #...>
```

It makes the constants of base class available as typing inside the extended classes.

Fixes #69586

### CODE REVIEW

**Comment by adamscott** [comment]
CC @anvilfolk @rune-scape

**Comment by anvilfolk** [comment]
Generally makes sense - haven't be able to dig deeply.

Is it possible to both have an outer class as well as a base class? If so, both ought to be checked right? Right now it's prioritizing the outer class over the base class.

So something like:

```
class_name OuterClass

class A:
  const a = preload(...)

class B extends A:
  func _ready():
    print(A.a)
```

Would this work, or would class `B` look straight to `BaseClass`?

**Comment by adamscott** [comment]
> Would this work, or would class `B` look straight to `BaseClass`?

Gonna test this at once.

**Comment by rune-scape** [comment]
i think you'll need 2 loops, one for checking base class, and one for checking each bases outer classes, look at `reduce_identifier_from_base`, the same code exists there, i think this whole search current class thing should really use `reduce_identifier_from_base`, instead of duplicated code, but thats much more work

**Comment by adamscott** [comment]
I updated the logic! It now checks for outer classes and their extended classes.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -2891,10 +2907,20 @@ void GDScriptAnalyzer::reduce_identifier_from_base(GDScriptParser::IdentifierNod
...
+		RBSet<GDScriptParser::ClassNode *> script_classes;
+		if (base_class->outer != nullptr) {
+			// Prioritize outer classes over extended classes
+			GDScriptParser::ClassNode *current = base_class->outer;
+			while (current != nullptr) {
+				script_classes.insert(current);
+				current = current->outer;
+			}
+		}
+		while (script_classes.size() > 0) {
```
Comment (rune-scape) [inline modules/gdscript/gdscript_analyzer.cpp:2919]: i think ideally this would just call `reduce_identifier_from_base` recursively on outer classes, and check if the passed base is part of the current classes hierarchy to see if it can access its `self`, but maybe thats just ideally
it would make the logic of searching a tree much simpler

File: modules/gdscript/gdscript_analyzer.cpp [hunk 2]
```diff
@@ -2925,8 +2951,14 @@ void GDScriptAnalyzer::reduce_identifier_from_base(GDScriptParser::IdentifierNod
 						break;
 				}
 			}
-			outer = outer->outer;
+			if (script_class->outer != nullptr) {
+				script_classes.insert(script_class->outer);
```
Comment (rune-scape) [inline modules/gdscript/gdscript_analyzer.cpp:2955]: i don't know how to request changes, but i'm pretty sure this should be a loop inside the next if statement, collecting only this outer class's bases outer classes (the terminology is so confusing), same in `resolve_datatype`

**Review by rune-scape — CHANGES_REQUESTED** [review]

File: modules/gdscript/gdscript_analyzer.cpp [hunk 3]
```diff
@@ -2891,10 +2907,20 @@ void GDScriptAnalyzer::reduce_identifier_from_base(GDScriptParser::IdentifierNod
 		}
 		// Check outer constants.
 		// TODO: Allow outer static functions.
-		GDScriptParser::ClassNode *outer = base_class->outer;
-		while (outer != nullptr) {
-			if (outer->has_member(name)) {
-				const GDScriptParser::ClassNode::Member &member = outer->get_member(name);
+		RBSet<GDScriptParser::ClassNode *> script_classes;
```
[the remark this answers is not in the document]
Comment (adamscott) [reply modules/gdscript/gdscript_analyzer.cpp:2910]: I don't want doubles entries in the vector. But it could work with vectors, with some checks.

**Comment by anvilfolk** [comment]
Look at these amazing MSPaint skills!

image

But in all seriousness, inner classes need to check outer classes (blue) as well as base classes (red). I was thinking about this and it isn't really a tree - I think @adamscott is right that we need to worry about checking things twice, and about the possibility of cyclic dependencies.

In that sense, having a `has_been_checked` set of some sort makes a lot of sense to me.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 1 above)
Comment (adamscott) [reply modules/gdscript/gdscript_analyzer.cpp:2919]: I don't really visualize how to use `reduce_identifier_from_base` there as you do.

**Comment by adamscott** [comment]
I updated the branch. Replaced `RBSet` with `Vector`. Added a `Vector<GDScriptParser::ClassNode *> checked_script_classes` as @anvilfolk suggested.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (adamscott) [reply modules/gdscript/gdscript_analyzer.cpp]: Used Vectors as suggested.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 1 above)
Comment (rune-scape) [reply modules/gdscript/gdscript_analyzer.cpp:2920]: i think it wouldn't have the information to avoid inf recursion, so looping is probably a better idea

File: modules/gdscript/gdscript_analyzer.cpp [hunk 4]
```diff
@@ -2891,10 +2912,21 @@ void GDScriptAnalyzer::reduce_identifier_from_base(GDScriptParser::IdentifierNod
 		}
 		// Check outer constants.
 		// TODO: Allow outer static functions.
-		GDScriptParser::ClassNode *outer = base_class->outer;
-		while (outer != nullptr) {
-			if (outer->has_member(name)) {
-				const GDScriptParser::ClassNode::Member &member = outer->get_member(name);
+		Vector<GDScriptParser::ClassNode *> checked_script_classes;
```
Comment (rune-scape) [inline modules/gdscript/gdscript_analyzer.cpp:2915]: this should be moved outside of the base class loop and also collect the base classes of the `base`

File: modules/gdscript/gdscript_analyzer.cpp [hunk 5]
```diff
@@ -2925,8 +2957,18 @@ void GDScriptAnalyzer::reduce_identifier_from_base(GDScriptParser::IdentifierNod
 						break;
 				}
 			}
-			outer = outer->outer;
+			GDScriptParser::ClassNode *outer = script_class->outer;
+			while (outer != nullptr) {
+				script_classes.append(outer);
+				outer = outer->outer;
+			}
```
Comment (rune-scape) [inline modules/gdscript/gdscript_analyzer.cpp:2964]: i think maybe this and the next loop should be instead something like this:
```cpp
GDScriptParser::ClassNode *outer_base_class = script_class->base_type.class_type;
if (outer_base_class != nullptr) {
    script_classes.append(outer_base_class);
    GDScriptParser::ClassNode *outer_base_outer_class = outer_base_class->outer;
    while (outer_base_outer_class != nullptr) {
        script_classes.append(outer_base_outer_class );
        outer = outer_base_outer_class ->outer;
    }
}
```
and each run is one of the blue circles:
image

Comment (rune-scape) [reply modules/gdscript/gdscript_analyzer.cpp:2964]: wait no, the bases of each outer need to be searched first...
i think i'm back to thinking recursion is the least complicated way to do this, and just have `checked_script_classes` as a member of the analyzer

Comment (adamscott) [reply modules/gdscript/gdscript_analyzer.cpp:2964]: @rune-scape If you want to make a PR with your recursive changes and add me as a co-author, go for it! You seem to have an idea to fix this.

File: modules/gdscript/gdscript_cache.cpp [hunk 6]
```diff
@@ -158,6 +158,10 @@ void GDScriptCache::remove_script(const String &p_path) {
 
 	MutexLock lock(singleton->mutex);
 
+	if (singleton->destructing) {
+		return;
+	}
+
```
Comment (adamscott) [inline modules/gdscript/gdscript_cache.cpp:164]: For some reason, without this, the tests will result in a `heap-use-after-free` error with the address sanitizer.

**Comment by trollodel** [comment]
Does this supersedes #57510?

**Comment by adamscott** [comment]
@trollodel Didn't know that there was an existing PR about the same issue. I searched the issue tracker before starting, didn't think about searching the pull requests too.

**Comment by adamscott** [comment]
> Does this supersedes #57510?

I would say yes. I just tested your PR and it doesn't pass, unfortunately, my added unit test.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 7]
```diff
@@ -219,6 +219,22 @@ Error GDScriptAnalyzer::check_class_member_name_conflict(const GDScriptParser::C
 	return OK;
 }
 
+void GDScriptAnalyzer::get_script_classes(GDScriptParser::ClassNode *p_node, RBSet<GDScriptParser::ClassNode *> &p_set) {
+	if (p_set.has(p_node)) {
+		return;
+	}
+	p_set.insert(p_node);
+
+	// Prioritize node base type over its outer class
```
Comment (anvilfolk) [inline modules/gdscript/gdscript_analyzer.cpp:228]: I'm not 100% on red-black trees, but don't they reorder stuff around? If that's the case, then this wouldn't actually prioritize by insertion order.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 8]
```diff
@@ -219,6 +219,22 @@ Error GDScriptAnalyzer::check_class_member_name_conflict(const GDScriptParser::C
 	return OK;
 }
 
+void GDScriptAnalyzer::get_script_classes(GDScriptParser::ClassNode *p_node, RBSet<GDScriptParser::ClassNode *> &p_set) {
```
Comment (anvilfolk) [inline modules/gdscript/gdscript_analyzer.cpp:222]: The name implies you are getting all classes that are defined in scripts, but nothing else. Something about the name `script_classes` makes it a little hard for me to understand what it does. Would it make more sense to say something like `get_context_classes` or `get_outer_and_base_classes` or something more in line with its intent? Those names are terrible too :P

If nothing else, perhaps some comments explaining exactly what the function does would be nice for future readers :)

It also seems like it doesn't really check for native/builtin classes? Should it?

File: modules/gdscript/gdscript_analyzer.cpp (hunk 7 above)
Comment (adamscott) [reply modules/gdscript/gdscript_analyzer.cpp:228]: Maybe. I'll use a vector instead.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 8 above)
Comment (adamscott) [reply modules/gdscript/gdscript_analyzer.cpp:222]: I'll name the function `get_class_node_current_scope_classes()`.

Comment (anvilfolk) [reply modules/gdscript/gdscript_analyzer.cpp]: I love the name!!!! That's perfect.

And just making sure: native/builtin class checks are already made going all the way up outer-class & extends hierarchy? Because maybe we're looking for an enum, say, somewhere in `Object`, and you might need to follow up a few GDScript classes before you get there?

File: modules/gdscript/gdscript_analyzer.cpp (hunk 7 above)
Comment (anvilfolk) [reply modules/gdscript/gdscript_analyzer.cpp:228]: Are there ordered hash sets in Godot? I think that'd be the ideal so the check isn't O(n), but honestly, this vector is never going to be very big so I think efficiency is not paramount :)

**Comment by trollodel** [comment]
> I would say yes. I just tested your PR and it doesn't pass, unfortunately, my added unit test.
@adamscott ok. I want to test this PR in my personal project, if I'll find some time for that. But your tests are bigger than mine, so it's probably good.

**Comment by anvilfolk** [comment]
@trollodel it's always frustrating when this happens - so I personally really appreciate everyone's graciousness here <3

There's a couple active GDScript contributors right now, which didn't use to be the case and explains why your PR wasn't reviewed at the time. Please feel free to hop on RocketChat or tag any of us for GDScript PRs.

We've been trying to review each other's PRs and make sure GDScript changes move along, and you'd be very welcome if you wanted to join these efforts again <3

**Comment by trollodel** [comment]
@anvilfolk Thanks for your words, but I don't feel frustrated (quite the contrary TBH).
I use #57510 in my personal fork anyway, so I don't really care when it would be reviewed.

>  There's a couple active GDScript contributors right now, which didn't use to be the case and explains why your PR wasn't reviewed at the time. Please feel free to hop on RocketChat or tag any of us for GDScript PRs.
> 
> We've been trying to review each other's PRs and make sure GDScript changes move along, and you'd be very welcome if you wanted to join these efforts again <3

I'm already in the GDScript channel on RC, but I don't have anything to say or PR stalled now.

**Comment by adamscott** [comment]
Updated the PR to use lists instead of vectors

File: modules/gdscript/gdscript_cache.cpp (hunk 6 above)
Comment (anvilfolk) [reply modules/gdscript/gdscript_cache.cpp:164]: That is so confusing! I don't see why these changes would do that.

Could it be a regression from elsewhere that shows up for you if you've rebased from master?

**Comment by anvilfolk** [comment]
I just realized something that I hadn't realized before, so I thought I would make it clear here - especially since I think the PR doesn't fall into this trap! :)

The treatment of outer classes and base classes _is meant to be different. We should not do all the context checks we do for base classes to outer classes as well.

**Comment by adamscott** [comment]
> ```
> 
> ```
> 
> 
>     
>   
> 
> I was worried that this was was doing base&outer class recursion for `check_instance_and_class_members()`, but nope! Smart PR author is smart! Everything checks out still!!

I'm doing things that I didn't even knew I was doing. :upside_down_face:

File: modules/gdscript/gdscript_analyzer.cpp [hunk 9]
```diff
@@ -219,6 +219,22 @@ Error GDScriptAnalyzer::check_class_member_name_conflict(const GDScriptParser::C
 	return OK;
 }
 
+void GDScriptAnalyzer::get_class_node_current_scope_classes(GDScriptParser::ClassNode *p_node, List<GDScriptParser::ClassNode *> *p_list) {
+	if (p_list->find(p_node) != nullptr) {
+		return;
+	}
+	p_list->push_back(p_node);
+
+	// Prioritize node base type over its outer class
```
Comment (adamscott) [inline modules/gdscript/gdscript_analyzer.cpp:228]: Just to be sure @anvilfolk, this prioritizes the node base type over its outer class

Comment (anvilfolk) [reply modules/gdscript/gdscript_analyzer.cpp:228]: Yes, you are right! And it should prioritize all base classes before even the first outer class.

And then it prioritizes the first outer class's base classes (all the way up) before moving on to first outer class's outer class, and so forth.

It gets pretty confusing, but honestly if somebody is looking this deep into the class hierarchy for names that are reused everywhere, they should just refactor their code, hehehe :)

Comment (anvilfolk) [reply modules/gdscript/gdscript_analyzer.cpp:228]: It should also add native/builtin classes and everything from what I can tell! :)

**Review by anvilfolk — APPROVED** [review]

File: modules/gdscript/gdscript_cache.cpp (hunk 6 above)
Comment (rune-scape) [reply modules/gdscript/gdscript_cache.cpp:164]: i'm suspicious of this part, but the rest looks great!

**Review by rune-scape — APPROVED** [review]

File: modules/gdscript/gdscript_cache.cpp (hunk 6 above)
Comment (adamscott) [reply modules/gdscript/gdscript_cache.cpp:164]: I'll create a new PR for that part, it doesn't belong in this PR.

**Comment by adamscott** [comment]
Removed all the `GDScriptCache` additions to create instead PR #69865.

**Comment by adamscott** [comment]
@akien-mga The PR doesn't build because I split off the code that made this PR build to #69865.

Once #69865 merged, it should fix the current sanitizers issues.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by anvilfolk** [comment]
Congraaaats!
