### PR TITLE
Fix read-only dictionaries adding missing keys

### LINKED ISSUE #74726: Read-only dictionaries can still have keys added
### Godot version

4.0 (c1128e911ccd6f1e8c35646df804d894652a58f1)

### System information

Arch Linux

### Issue description

Read-only dictionaries can still have new keys added. The value for the new key isn't set (it is kept `null`).

This is caused by `Dictionary::operator[]` not checking if the key exists when it is read only mode. Accessing a key in the underlying HashMap will create if it does not exist. The actual value isn't set because it only returns a dummy reference.

### Steps to reproduce

Run the following snippet:

```gdscript
var dict = {}
dict.make_read_only()
prints("dict", dict) # {}
dict.foo = "hi"
prints("dict", dict) # { "foo": <null> }
```

### Minimal reproduction project

[DictReadOnlyAddKey.zip](https://github.com/godotengine/godot/files/10943387/DictReadOnlyAddKey.zip)

### PR DESCRIPTION
**Pull request by MarioLiebisch**
When querying a non-existing key on a read-only dictionary, the key was still added (albeit never set).

This fixes #74726.

### CODE REVIEW

File: core/variant/dictionary.cpp [hunk 1]
```diff
@@ -83,7 +83,12 @@ Variant &Dictionary::operator[](const Variant &p_key) {
...
 			const StringName *sn = VariantInternal::get_string_name(&p_key);
-			*_p->read_only = _p->variant_map[sn->operator String()];
+			const String &key = sn->operator String();
+			if (_p->variant_map.has(key)) {
+				*_p->read_only = _p->variant_map[key];
+			} else {
+				*_p->read_only = Variant();
+			}
 		} else {
 			*_p->read_only = _p->variant_map[p_key];
```
Comment (akien-mga) [inline core/variant/dictionary.cpp:93]: What about this one?

Comment (MarioLiebisch) [reply core/variant/dictionary.cpp:93]: Oh, you're right, I confused that one with the non-const version!

**Comment by vnen** [comment]
I think it would be nice to add a test case for this BTW. It could be done in `tests/core/variant/test_dictionary.h`, doesn't need to be included in GDScript tests.

**Comment by MarioLiebisch** [comment]
> I think it would be nice to add a test case for this BTW.

Done.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
