### PR TITLE
Fix multiline items drawing in `Tree`

### LINKED ISSUE #76507: Problems rendering multiline items in Tree.
### Godot version

4.1.dev

### System information

Ubuntu 22.04.1 LTS

### Issue description

image

When I click one of the items it becomes normal, but the little line on the left doesn't match the icon:

image

### Steps to reproduce

Go to the Node tab in the editor.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by dalexeev**
Closes #76507.

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -1907,6 +1905,7 @@ void Tree::update_item_cell(TreeItem *p_item, int p_col) {
 		font_size = theme_cache.font_size;
 	}
 	p_item->cells.write[p_col].text_buf->add_string(valtext, font, font_size, p_item->cells[p_col].language);
+	p_item->cells.write[p_col].text_buf->set_break_flags(TextServer::BREAK_MANDATORY | TextServer::BREAK_WORD_BOUND | TextServer::BREAK_ADAPTIVE);
```
Comment (bruvzg) [inline scene/gui/tree.cpp:1908]: Wrap mode probably should be exposed as item property (similar to `Label` and other controls).

**Comment by dalexeev** [comment]
I haven't been able to reproduce this in a test project, it only happens in the editor. I copied the editor theme to the project, but the error still doesn't appear.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
