### PR TITLE
Fix moving directories in filesystem

### LINKED ISSUE #77689: Can't move directories in filesystem dock
### Godot version

4.1 dev3

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Trying to move a folder results in moving error and it's not moved.
Regression from #75330

A fix already exists, but I'm opening an issue so it's not lost (the PR isn't ready and not very active).

### Steps to reproduce

1. Add 2 folders in filesystem
2. Move one folder into another one

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by KoBeWi**
Supersedes #76271
Fixes #77689
Fixes unreported (?) bug when moving folder to the same path (similar to #23778)

### CODE REVIEW

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -1790,17 +1790,11 @@ void FileSystemDock::_overwrite_dialog_action(bool p_overwrite) {
...
-
-		String old_path = (p_item.is_file || p_item.path.ends_with("/")) ? p_item.path : (p_item.path + "/");
-		String new_path = (p_item.is_file || p_new_path.ends_with("/")) ? p_new_path : (p_new_path + "/");
+	for (const FileOrFolder &item : to_move) {
+		String old_path = item.path.trim_suffix("/");
+		String new_path = to_move_path.path_join(old_path.get_file());
 
-		if ((p_item.is_file && FileAccess::exists(new_path)) ||
-				(!p_item.is_file && DirAccess::exists(new_path))) {
+		if ((item.is_file && FileAccess::exists(new_path)) || (!item.is_file && DirAccess::exists(new_path))) {
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:1797]: This change turned out unrelated, but it simplifies the code, so I left it.

**Comment by theraot** [comment]
I've tested the Windows build, I can confirm it fixes the issues with dragging and dropping folders in the FileSystem dock. Using "Move/Duplicate to..." to move folders also works.

Note: Godot will ask about overwriting when using "Move/Duplicate to..." to move a folder to the same location where it is.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
