### PR TITLE
Fix undoredo handling in some dialogs

### LINKED ISSUE #10062: Add Undo / Redo support to Animation Library Editing
### Describe the project you are working on

A game in production

### Describe the problem or limitation you are having in your project

When editing animation libraries it is easy to make a mistake and loose work due to it not supporting undo redo.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Implement undo / redo in the Animation Library

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

You should be able to undo deleting / creating / renaming / copying animations in the "Edit Animations Libraries" view.
image

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Undo / Redo missing cannot be worked around with a script

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving the editor workflow out of the box

### LINKED ISSUE #88412: [4.x] Undo/Redo does not work in the UV editor
### Tested versions

This problem occurs in all versions starting from 4.0+, but is not observed in 3.5+

### System information

Windows 10, Radeon RX 560 Series

### Issue description

When editing UVs in the Polygon2D editor, you cannot undo any action when pressing Ctrl+Z

### Steps to reproduce

Open the UV editor, move the points and try to return them to their original place

### Minimal reproduction project (MRP)

Too easy to check, not required

### PR DESCRIPTION
**Pull request by KoBeWi**
Looks like dialogs are blocking input from passing to the editor, so undo/redo shortcut has to be handled manually when relevant. I improved handling in some dialogs and fixed animation dialog, but there might be more dialogs that need fixing.

Fixes https://github.com/godotengine/godot-proposals/issues/10062

https://github.com/godotengine/godot/assets/2223172/f6905f00-7158-4967-a0a9-c03134636fb0

Fixes #88412

### CODE REVIEW

**Comment by JekSun97** [comment]
Also fixes #88412 ?

**Comment by akien-mga** [comment]
> @KoBeWi Also fixes #88412 ?

Judging by the code, I don't think so, but this would be another case of a dialog that needs to be handled like done here for the AnimationLibrary editor.

**Comment by KoBeWi** [comment]
Added fix for UV edit.

**Review by akien-mga — APPROVED** [review]

File: editor/plugins/polygon_2d_editor_plugin.cpp [hunk 1]
```diff
@@ -52,6 +52,31 @@
 #include "scene/gui/texture_rect.h"
 #include "scene/gui/view_panner.h"
 
+class UVEditDialog : public AcceptDialog {
+	GDCLASS(UVEditDialog, AcceptDialog);
+
+	void UVEditDialog::shortcut_input(const Ref<InputEvent> &p_event) override {
```
Comment (akien-mga) [inline editor/plugins/polygon_2d_editor_plugin.cpp:58]:
```suggestion
	void shortcut_input(const Ref<InputEvent> &p_event) override {
```

**Comment by akien-mga** [comment]
Thanks!
