### PR TITLE
Fix tooltips don't appear for PopupMenus

### LINKED ISSUE #49077: Tooltips don't appear for PopupMenus
**Godot version:**
v4.0.dev.custom_build.b6f381475

**OS/device including version:**
Windows 10

**Issue description:**
Tooltips don't appear for PopupMenus, but they appear for other node types. This happens inside of the editor and in projects. This happens with single window mode on or off

**Steps to reproduce:**
Hover over any of the items in a PopupMenu that are meant to have a tooltip (like the gizmos), and the tooltip won't pop up. This also happens for PopupMenus placed inside of projects, not just in the editor, so creating a PopupMenu and setting tooltip for it's items won't show the tooltip (like in the minimal reproduction project)

image

**Minimal reproduction project:**
[PopupMenuTooltipTest.zip](https://github.com/godotengine/godot/files/6541862/PopupMenuTooltipTest.zip)

### PR DESCRIPTION
**Pull request by requizm**
Fixed #49077

I can't say that the change I made on viewport.cpp is very good, but the system here needs to change. Read this for explanation: https://github.com/godotengine/godot/issues/49077#issuecomment-902343554

https://user-images.githubusercontent.com/12533045/130163857-9c2c6ba9-3594-4105-8a78-c409fe2645ef.mp4

### CODE REVIEW

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -1104,6 +1105,12 @@ String Viewport::_gui_get_tooltip(Control *p_control, const Vector2 &p_pos, Cont
 	while (p_control) {
 		tooltip = p_control->get_tooltip(pos);
 
+		//Temporary solution for PopupMenus
+		if (this->get_class_name() == "PopupMenu") {
```
Comment (EricEzaM) [inline scene/main/viewport.cpp:1109]: Why bother with this? Can't you just do

```cpp
if (PopupMenu *menu = Object::cast_to<PopupMenu>(this)){
	tooltip = menu->get_tooltip(pos);
}
```

Comment (akien-mga) [reply scene/main/viewport.cpp:1109]: Note that we prefer to avoid assignments in `if` conditionals, so this hould be:
```cpp
PopupMenu *menu = Object::cast_to<PopupMenu>(this);
if (menu) {
	menu->get_tooltip(pos);
}
```

Comment (requizm) [reply scene/main/viewport.cpp]: You're right. I may have such mistakes as I am new to the project. Thank you info.

**Comment by requizm** [comment]
Updated commit message.

**Review by YeldhamDev — APPROVED** [review]
