### PR TITLE
Exit early in `TextEdit::_get_column_pos_of_word` to improve highlight performance

### LINKED ISSUE #80801: Editor crashes if trying to highlight part of a really long line of text.
### Godot version

4.1

### System information

Windows 10

### Issue description

I have this config file and thought I'd try and edit it. The editor opens the .cfg file with no issue but highlighting the text crashes the editor.
Also adding and deleting text is very delayed.

This is probably a performance issue, I'm not sure if the editor would unfreeze if I waited a while.

Note:
The text highlights fine but crashes when I let go of the mouse.

### Steps to reproduce

Try highlighting some of the text from this file, I dare you!
[AStar Data.zip](https://github.com/godotengine/godot/files/12387133/AStar.Data.zip)

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by jsjtxietian**
This pr fixes #80801
If in the while loop inside `_get_column_pos_of_word`, `string.find` or `findn` can't find any match words, we can just early break the while loop to imporove cpu performance. 
In the origin logic without early break, `p_from_column` will only plus 1 every loop,  this means basically this function will do the `string.find` or `findn` for `p_search.length` times, this is way too slow for a long `p_search` string.

### CODE REVIEW

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -7000,6 +7000,11 @@ int TextEdit::_get_column_pos_of_word(const String &p_key, const String &p_searc
 				col = p_search.findn(p_key, p_from_column);
 			}
 
+			// if can't find any, just early break to improve performance
```
Comment (AThousandShips) [inline scene/gui/text_edit.cpp:7003]:
```suggestion
			// If not found, just break early to improve performance.
```
Per the [comment style](https://docs.godotengine.org/en/latest/contributing/development/code_style_guidelines.html#comment-style-guide), and grammar

**Review by AThousandShips — APPROVED** [review]
Fix makes sense, haven't tested myself though

Just a style thing to fix

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
