### PR TITLE
Add size check in Control::_edit_set_state()  to fix crash

### LINKED ISSUE #46017: Executing `Control.new()._edit_set_state({})` crashes Godot
**Godot version:**
Godot 3.2.4 rc 2

**Issue description:**
Executing
```
Control.new()._edit_set_state({})
```

crashes with backtrace
```
ERROR: operator[]: FATAL: Index p_index = 0 is out of bounds (((Vector<T> *)(this))->_cowdata.size() = 0).
   At: ./core/vector.h:49.
handle_crash: Program crashed with signal 4
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f2653bdd210] (??:0)
[2] VectorWriteProxy<Variant>::operator[](int) (/mnt/Miecz/godot3.2/./core/vector.h:49 (discriminator 7))
[3] Array::operator[](int) (/mnt/Miecz/godot3.2/core/array.cpp:76)
[4] Control::_edit_set_state(Dictionary const&) (/mnt/Miecz/godot3.2/scene/gui/control.cpp:80)
[5] MethodBind1<Dictionary const&>::call(Object*, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/./core/method_bind.gen.inc:775 (discriminator 12))
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/core/object.cpp:919 (discriminator 1))
[7] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/mnt/Miecz/godot3.2/core/variant_call.cpp:1129 (discriminator 1))
[8] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript_function.cpp:1089)
[9] GDScriptInstance::_ml_call_reversed(GDScript*, StringName const&, Variant const**, int) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript.cpp:1269)
[10] GDScriptInstance::call_multilevel_reversed(StringName const&, Variant const**, int) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript.cpp:1278)
[11] Node::_notification(int) (/mnt/Miecz/godot3.2/scene/main/node.cpp:152)
[12] Node::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/main/node.h:46 (discriminator 14))
[13] CanvasItem::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/2d/canvas_item.h:166 (discriminator 3))
[14] Node2D::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/2d/node_2d.h:38 (discriminator 3))
[15] Object::notification(int, bool) (/mnt/Miecz/godot3.2/core/object.cpp:931)
[16] Node::_propagate_ready() (/mnt/Miecz/godot3.2/scene/main/node.cpp:197)
[17] Node::_propagate_ready() (/mnt/Miecz/godot3.2/scene/main/node.cpp:186 (discriminator 2))
[18] Node::_set_tree(SceneTree*) (/mnt/Miecz/godot3.2/scene/main/node.cpp:2560)
[19] SceneTree::init() (/mnt/Miecz/godot3.2/scene/main/scene_tree.cpp:464)
[20] OS_X11::run() (/mnt/Miecz/godot3.2/platform/x11/os_x11.cpp:3628)
[21] /usr/bin/godot(main+0x125) [0x16d2e6b] (/mnt/Miecz/godot3.2/platform/x11/godot_x11.cpp:57)
[22] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f2653bbe0b3] (??:0)
[23] /usr/bin/godot(_start+0x2e) [0x16d2c8e] (??:?)
```

### PR DESCRIPTION
**Pull request by sps1112**
fixes #46017
add size check to prevent crash when executing ```Control.new()._edit_set_state({})```

### CODE REVIEW

**Comment by KoBeWi** [comment]
This method will also crash when the passed Dictionary is missing any of the used keys, e.g. `Control.new()._edit_set_state({"test": 1})` will still crash.

So to fix this properly, you'd have to add a check for each existence of each key. I wonder if it's worth it though, the method isn't visible in documentation. It's mean for internal use only (see https://github.com/godotengine/godot-proposals/issues/2285) and we didn't have crash reports from editor usage (and even if we had, the error doesn't help much as it still needs to be fixed).

**Review by KoBeWi — APPROVED** [review]

File: scene/gui/control.cpp [hunk 1]
```diff
@@ -73,6 +73,13 @@ Dictionary Control::_edit_get_state() const {
 }
 
 void Control::_edit_set_state(const Dictionary &p_state) {
+	ERR_FAIL_COND(p_state.size() <= 0);
+	ERR_FAIL_COND(p_state["rotation"].is_null());
+	ERR_FAIL_COND(p_state["scale"].is_null());
+	ERR_FAIL_COND(p_state["pivot"].is_null());
+	ERR_FAIL_COND(p_state["anchors"].is_null());
+	ERR_FAIL_COND(p_state["offsets"].is_null());
```
Comment (akien-mga) [inline scene/gui/control.cpp:81]: Maybe we can chain the conditions with `||` to avoid having 6 separate checks for this unlikely error?

Comment (sps1112) [reply scene/gui/control.cpp]: Done

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Comment by akien-mga** [comment]
Reverted (and undid cherry-pick before pushing) as the change is wrong:
```
ERROR: Condition "(p_state.size() <= 0) || p_state["rotation"].is_null() || p_state["scale"].is_null() || p_state["pivot"].is_null() || p_state["anchors"].is_null() || p_state["offsets"].is_null()" is true.
   at: _edit_set_state (scene/gui/control.cpp:76)
```

`Variant::is_null()` checks if the Variant is a null Object, that's not the right way to validate the existence of dictionary keys.

**Comment by KoBeWi** [comment]
Right, I didn't test it in the editor before approving and was surprised it works .-.

This should be `p_state.has("rotation")` etc.
