### PR TITLE
Fix crash when ProgressDialog is outside tree

### LINKED ISSUE #102205: Saving a previously invalid compute shader from an external editor crashes the Godot editor
### Tested versions

- Reproducible in: v4.4.beta2.official.a013481b0
- Not reproducible in: v4.3.stable.official.77dcf97d8

### System information

Godot v4.4.beta2 - Windows 11 (build 26100) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 (NVIDIA; 32.0.15.6636) - AMD Ryzen 5 5600X 6-Core Processor (12 threads)

### Issue description

Saving a `.glsl` file containing a compute shader in an external editor after said compute shader failed to compile once results in a crash of the Godot editor.

The following error appears in the console:

```
Godot Engine v4.4.beta2.official.a013481b0 - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 566.36 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce RTX 4060

Editing project: [...]/test-cellular-automaton
Godot Engine v4.4.beta2.official.a013481b0 - https://godotengine.org
Vulkan 1.3.289 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce RTX 4060

ERROR: Parameter "p_parent" is null.
   at: reparent (scene/main/node.cpp:1958)

================================================================
CrashHandlerException: Program crashed with signal 11
Engine version: Godot Engine v4.4.beta2.official (a013481b0911e59cc3f3dea7ebb732450c3e1460)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
```

Here is the compute shader I use:

```glsl
#[compute]
#version 450

// Invocations in the (x, y, z) dimension
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0, std140) uniform Parameters {
    vec4 p; // p.x -> height
}
parameters;

// Input buffer
layout(set = 0, binding = 1, std430) restrict readonly buffer Previous {
    int data[];
}
previous;

// Output buffer
layout(set = 0, binding = 2, std430) restrict writeonly buffer Next {
    int data[];
}
next;

// The code we want to execute in each invocation
void main() {
    uint idx = gl_GlobalInvocationID.x * uint(parameters.p.x) + gl_GlobalInvocationID.y;
    next.data[idx] *= previous.data[idx];
}

```

### Steps to reproduce

Starting from an new empty project.

- Open the Godot project folder in an external editor (VS Code).
- Add a new `test.glsl` compute shader with probably any content. Mine is provided below.
- Save, go in godot, it is correctly imported.
- Make a valid modification, save, go to Godot, it is re-imported and everything works fine.
- Go back to the external editor and make an **invalid** modification resulting in a failed compilation.
- Go back to Godot, you are notified of the issue with your shader.
- Now go back to the external editor and do any modification (valid or not) and save. Going back to Godot, the editor will simply crash.

### Minimal reproduction project (MRP)

[test-cellular-automaton-4.4.zip](https://github.com/user-attachments/files/18607934/test-cellular-automaton-4.4.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #102205

### CODE REVIEW

**Review by AThousandShips — APPROVED** [review]
LGTM

**Comment by Chaosus** [comment]
The fix is ok, but we need to prevent this error from happening at all (I mean prevent emit error when modify the compute shader externally).

File: editor/progress_dialog.cpp [hunk 1]
```diff
@@ -166,7 +166,8 @@ void ProgressDialog::_popup() {
 
 	center_panel->set_custom_minimum_size(ms);
 
-	Window *current_window = get_last_exclusive_window();
+	Window *current_window = SceneTree::get_singleton()->get_root()->get_last_exclusive_window();
+	ERR_FAIL_NULL(current_window);
```
Comment (Chaosus) [inline editor/progress_dialog.cpp:170]: Are you sure you want to distract the user using unnecessary errors? Maybe just write:

```
if(!current_window) {
	return;
}
```

**Comment by KoBeWi** [comment]
> The fix is ok, but we need to prevent this error from happening at all

And that's what the fix does. The ERR_FAIL is just extra safeguard. If we ever see this error, it means something is wrong and needs a further fix.

File: editor/progress_dialog.cpp (hunk 1 above)
Comment (KoBeWi) [reply editor/progress_dialog.cpp:170]: See my comment below.

**Review by Hilderin — APPROVED** [review]
Sounds good to me!

**Comment by Repiteo** [comment]
Thanks!
