### PR TITLE
Remove `EDSCALE` dependency from GUI nodes

### LINKED ISSUE #36761: ColorPicker's size theme constants don't have effect
**Godot version:**
3.2

**Issue description:**
So there's stuff like `h_width`, `sv_width` and `sv_height` in ColorPicker, but changing them does nothing.

**Steps to reproduce:**
1. Add a ColorPicker
2. Set `sv_width` to some insane value like 100000
3. Run the game
4. The ColorPicker still has default size

### PR DESCRIPTION
**Pull request by YuriSizov**
See https://github.com/godotengine/godot/issues/53295#issuecomment-932203107. This PR is split into 3 commits for better readability of individual changes.

* First, I reorganized the `Theme` resource's code and added some grouping comments to better explain this huge file and what it consists of. It was a good base for the rest of the work done here. It shouldn't contain any changes to the code, but I removed one unused include.
* Second, I've added the base scale factor to the theme resource and exposed the necessary API for it, and for `Control` nodes to work with it. Here as well similar treatment was performed on default font and default font size of each theme to make them more usable from controls.
* Third, I've updated the GUI nodes which used `EDSCALE` to use theme's base scale factor instead. It was trivial for some, but not for everything. I've also removed it from one place (I'll leave "review" comments below for the interesting parts).

Overall, with 3 commits it should be easier to review it, because there are some moving parts in various places involved.

There may be some visible changes in the projects, as the base scale for the default theme now takes HiDPI into account, as that value was already available and in use for generating the theme. Now it's exposed as a Theme property and those same controls which previously used `EDSCALE` will also respect it in projects running on default theme.

This is breaking in its nature, so a 3.x port is unlikely. But I can make a dedicated 3.x PR to reorganize the theme resource for easier cherrypicks in future. Can probably expose the new default font methods too.

-----
Incidentally, I was in the area, so this fixes https://github.com/godotengine/godot/issues/36761 by superseding https://github.com/godotengine/godot/pull/37419. That PR wasn't updated after my review anyway, so this way we will be able to merge it quicker.

### CODE REVIEW

File: scene/gui/color_picker.cpp [hunk 1]
```diff
@@ -71,18 +60,39 @@ void ColorPicker::_notification(int p_what) {
...
+			wheel_margin->add_theme_constant_override("margin_bottom", 8 * get_theme_default_base_scale());
+
 			for (int i = 0; i < 4; i++) {
+				labels[i]->set_custom_minimum_size(Size2(get_theme_constant(SNAME("label_width")), 0));
 				set_offset((Side)i, get_offset((Side)i) + get_theme_constant(SNAME("margin")));
 			}
+
+			if (Engine::get_singleton()->is_editor_hint()) {
+				// Adjust for the width of the "Script" icon.
+				text_type->set_custom_minimum_size(Size2(28 * get_theme_default_base_scale(), 0));
```
Comment (pycbouh) [inline scene/gui/color_picker.cpp:82]: I kept the editor hint condition here because this seems to be aimed specifically at the editor-available icon, but I don't really like this.

File: scene/gui/dialogs.cpp [hunk 2]
```diff
@@ -363,8 +362,7 @@ Button *ConfirmationDialog::get_cancel_button() {
 
 ConfirmationDialog::ConfirmationDialog() {
 	set_title(TTRC("Please Confirm..."));
-#ifdef TOOLS_ENABLED
-	set_min_size(Size2(200, 70) * EDSCALE);
-#endif
+	set_min_size(Size2(200, 70));
```
Comment (pycbouh) [inline scene/gui/dialogs.cpp:365]: I just plain removed the scale here. I get that we lose scaling for the default size of the dialog, but I don't know what a proper solution can be here. Classes that extend this dialog or reuse this dialog already lose that scaling and need to carry for it themselves. In user projects running with HiDPI this is also a problem.

And we can't read the scale here because there is no theme yet, as we are not in the tree yet. Maybe a scaling factor should be a part of the base Window class and be applied automatically on top of the min size?

File: scene/gui/gradient_edit.cpp [hunk 3]
```diff
@@ -297,6 +288,12 @@ void GradientEdit::_notification(int p_what) {
 			picker->connect("color_changed", callable_mp(this, &GradientEdit::_color_changed));
 		}
 	}
+
+	if (p_what == NOTIFICATION_ENTER_TREE || p_what == NOTIFICATION_THEME_CHANGED) {
+		draw_spacing = 3 * get_theme_default_base_scale();
+		draw_point_width = 8 * get_theme_default_base_scale();
```
Comment (pycbouh) [inline scene/gui/gradient_edit.cpp:294]: Maybe should've kept the default values as consts or defines?

File: scene/resources/default_theme/default_theme.cpp [hunk 4]
```diff
@@ -1036,9 +1036,16 @@ void make_default_theme(bool p_hidpi, Ref<Font> p_font) {
...
+
+	float default_scale = 1.0;
+	if (p_hidpi) {
+		default_scale = 2.0;
+	}
+
+	fill_default_theme(t, default_font, large_font, default_icon, default_style, default_scale);
 
 	Theme::set_default(t);
+	Theme::set_default_base_scale(default_scale);
```
Comment (pycbouh) [inline scene/resources/default_theme/default_theme.cpp:1048]: This is can create some problems with the default theme looks, or at least change it in some ways. But I feel like it should've already been the thing.

File: scene/resources/theme.cpp [hunk 5]
```diff
@@ -29,427 +29,234 @@
 /*************************************************************************/
 
 #include "theme.h"
-#include "core/io/file_access.h"
```
Comment (pycbouh) [inline scene/resources/theme.cpp:32]: This seemed unused.

File: scene/gui/graph_edit.cpp [hunk 6]
```diff
@@ -436,6 +432,8 @@ void GraphEdit::_notification(int p_what) {
 		snap_button->set_icon(get_theme_icon(SNAME("snap")));
 		minimap_button->set_icon(get_theme_icon(SNAME("minimap")));
 		layout_button->set_icon(get_theme_icon(SNAME("layout")));
+
+		zoom_label->set_custom_minimum_size(Size2(48, 0) * get_theme_default_base_scale());
```
Comment (pycbouh) [inline scene/gui/graph_edit.cpp:436]: In general for cases like this I assumed it is okay to update the min size on theme changes as the nodes are internal and unlikely to be touched by users in a very specific way. But this may be a problem for some cases. And this is definitely not going to work what setting up the minimal size of the control node itself like in the ConfirmationDialog's case above.

**Review by fire — COMMENTED** [review]
Ping when ready to review. Removing EDSCALE is a good enhancement!

**Comment by pycbouh** [comment]
> Ping when ready to review. Removing EDSCALE is a good enhancement!

@fire It is ready for review. All GUI nodes are currently handled by this PR.

**Comment by fire** [comment]
Ah, I wasn't sure because of the unresolved review comments.

**Comment by pycbouh** [comment]
> Ah, I wasn't sure because of the unresolved review comments.

Those are mine to highlight some parts that may need a second look 🙃

**Review by bruvzg — APPROVED** [review]
Haven't tested everything, but hiDPI mode on macOS seems to be working fine.

File: scene/resources/theme.cpp [hunk 7]
```diff
@@ -1605,6 +1642,7 @@ void Theme::_bind_methods() {
 	ClassDB::bind_method(D_METHOD("merge_with", "other"), &Theme::merge_with);
 	ClassDB::bind_method(D_METHOD("clear"), &Theme::clear);
 
+	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "default_base_scale"), "set_default_base_scale", "get_default_base_scale");
```
Comment (akien-mga) [inline scene/resources/theme.cpp:1645]: Maybe add a property hint for easy edition? E.g. "0.01,4.0,0.01,or_greater" maybe?
That's going a bit low in the sub-1.0 range but with a step of 0.01 I don't think it makes much sense to impose an arbitrary limit on e.g. "0.25", or "0.1".

File: scene/resources/theme.cpp [hunk 8]
```diff
@@ -236,6 +241,24 @@ void Theme::set_default_font_size(int p_font_size) {
 }
 
 // Fallback values for theme item types, configurable per theme.
+void Theme::set_default_theme_base_scale(float p_base_scale) {
```
Comment (akien-mga) [inline scene/resources/theme.cpp:244]: Should there be validation against using say negative scales, or 0?

File: scene/gui/color_picker.cpp (hunk 1 above)
Comment (akien-mga) [reply scene/gui/color_picker.cpp:82]: Yeah it would be good if we could get rid of it. I guess `28` is a magic number of the size of the Script icon?

Looking at the code, this `text_type` seems to be used to allow writing a constructor in the LineEdit, but only in the editor version of the control. In projects, this turns into a flat button which can't be clicked.

It's a bit messy, but also not the only editor-specific hack in this class, so I guess it can be left as is in this PR, and revisited in a future issue/PR.

For example, I'm not sure this feature is actually useful. It was maybe added to allow copy pasting the constructor to use in scripts, but then it might be just as good to have a Copy button for this.

File: scene/gui/dialogs.cpp (hunk 2 above)
Comment (akien-mga) [reply scene/gui/dialogs.cpp:365]: For the record, this also means that ConfirmationDialog in projects will now have this min size of `200x70`. It might be a weirdly specific magic number but well, it's better than zero.

> And we can't read the scale here because there is no theme yet, as we are not in the tree yet. Maybe a scaling factor should be a part of the base Window class and be applied automatically on top of the min size?

That might make sense yeah, and solve many issues where this had to be hardcoded in editor code. Might be for a follow-up PR maybe to keep the scope manageable here.

File: scene/gui/gradient_edit.cpp (hunk 3 above)
Comment (akien-mga) [reply scene/gui/gradient_edit.cpp:294]: Yeah having them as constants in the header would make sense IMO.

File: scene/gui/text_edit.cpp [hunk 9]
```diff
@@ -1173,12 +1169,7 @@ void TextEdit::_notification(int p_what) {
 						}
 					}
 
-					// Carets
```
Comment (akien-mga) [inline scene/gui/text_edit.cpp:1176]: That comment should be kept, it's for the whole chunk of code that handles carets.

**Review by akien-mga — APPROVED** [review]
Changes look good to me. I tested locally on 4K laptop and it seems to work well.

The second commit could use a check by @reduz for Control/Window changes.

File: scene/gui/color_picker.cpp (hunk 1 above)
Comment (pycbouh) [reply scene/gui/color_picker.cpp:82]: I would like to split the color picker up and tidy it at some point, so I can indeed revisit this in a future PR. it's too monstrous at the moment, does too much stuff.

File: scene/resources/theme.cpp (hunk 8 above)
Comment (pycbouh) [reply scene/resources/theme.cpp:244]: Values at 0.0 and below are not going to be considered valid if the provided API is used (`has_*` methods). We can disallow values below 0.0 here anyway if needed, but 0.0 should be allowed so that the value can be unset from the validity standpoint.

I haven't added any checks because we don't have any checks for font and font size neither, and it works fine for them.

File: scene/gui/text_edit.cpp (hunk 9 above)
Comment (pycbouh) [reply scene/gui/text_edit.cpp:1176]: Oh, I probably removed it by accident. Will restore.

File: scene/resources/theme.cpp (hunk 7 above)
Comment (pycbouh) [reply scene/resources/theme.cpp:1645]: I'd cap the upper limit at `2.0`. That's the value we use for HiDPI and that's the maximum provided value for the editor scale, 200%. `or_greater` will handle the rest nicely.

Comment (akien-mga) [reply scene/resources/theme.cpp:1645]: That's fine until 8K becomes mainstream :P
