### PR TITLE
Fix scroll to symbol's documentation

### LINKED ISSUE #100087: Editor help doesn't scroll to where it should
### Tested versions

v4.4.dev6.official [1f47e4c4e]

### System information

Godot v4.4.dev6 - macOS 15.1.0 - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M1 Max (Apple7) - Apple M1 Max (10 threads)

### Issue description

I use help search all the time and never had any problems with it until recently, so I assume https://github.com/godotengine/godot/pull/96449 broke it

No matter what I search it always scrolls to the very bottom:

https://github.com/user-attachments/assets/5113f8e6-d00c-4ec9-8ff1-6b38ba4da849

### Steps to reproduce

Search help. I don't know why it's reproducable for some people but not for other, so just opening an issue for now

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by ydeltastar**
- Fix: https://github.com/godotengine/godot/issues/100087

Same fix as https://github.com/godotengine/godot/pull/90035 but for a different code path.
A doc page goes through this code path the first time it opens but depending on the device it will execute too early so the correct offsets weren't calculated yet.

### CODE REVIEW

**Comment by passivestar** [comment]
Works on my end, thanks

File: editor/editor_help.cpp [hunk 1]
```diff
@@ -215,7 +215,7 @@ void EditorHelp::_search(bool p_search_previous) {
 
 void EditorHelp::_class_desc_finished() {
 	if (scroll_to >= 0) {
-		class_desc->scroll_to_paragraph(scroll_to);
+		class_desc->connect("draw", callable_mp(class_desc, &RichTextLabel::scroll_to_paragraph).bind(scroll_to), CONNECT_ONE_SHOT | CONNECT_DEFERRED);
```
Comment (akien-mga) [inline editor/editor_help.cpp:218]:
```suggestion
		class_desc->connect(SceneStringName(draw), callable_mp(class_desc, &RichTextLabel::scroll_to_paragraph).bind(scroll_to), CONNECT_ONE_SHOT | CONNECT_DEFERRED);
```

**Comment by akien-mga** [comment]
> Same fix as #90035 but for a different code path.

Seems like this was changed further in #96449.

CC @Maran23 @KoBeWi @kitbdev

File: editor/editor_help.cpp (hunk 1 above)
Comment (Maran23) [reply editor/editor_help.cpp:218]: I wonder if a `call_deferred()` is enough now, without connect to the `draw` signal.

**Comment by passivestar** [comment]
> I also start to wonder if this might be related to the refresh rate of the screen as suggested in the issue. I have a 240 Hz screen and never got this issue after my fix again

I use a 120hz one. I get it every time I use search in dev6

**Comment by ydeltastar** [comment]
> Seems like this was changed further in #96449.

From what I debugged, https://github.com/godotengine/godot/pull/90035 didn't fix the issue because the offsets were already calculated in that code path. Having it or reverting it didn't have any effect.

This PR affects another code path when the documentation is loaded and processed for the first time. When `scroll_to_paragraph` is called, the offsets aren't calculated yet.

> My fix removed code that was calling the whole help logic twice, so it fixed a problem, but the scrolling is still not stable (enough). For now, I wonder if simply calling `call_deferred()` is enough here, doing the scrolling at the end of the frame.
> 
> EDIT: What is weird is that the `finished` signal is called, then the `vscroll` might get hidden, then `queue_redraw` is called. I wonder, if we rather want to emit the `finished` signal after the redraw instead (Or at least after `_validate_line_caches` is called, which seems to be done right after).

Yes, the main issue is that `RichTextLabel.finished` is emitted before the offsets are calculated in `_validate_line_caches` which happens in `NOTIFICATION_DRAW`.

https://github.com/godotengine/godot/blob/a372214a4a047ccf63d23c4406337b30e55ff60b/scene/gui/rich_text_label.cpp#L1899-L1902

I think it makes sense since these calculations are dependent on theme changes and only relevant when drawing. So connecting to the `draw` signal which happens after `NOTIFICATION_DRAW ` sounds like the best fix here.

**Comment by akien-mga** [comment]
Note that AFAIK, the RichTextLabel for the editor help updates on a thread, so there might be race conditions. CC @bruvzg

**Comment by passivestar** [comment]
> @passivestar Does CTRL+Left Click works for you?

yeah it does

File: editor/editor_help.cpp (hunk 1 above)
Comment (bruvzg) [reply editor/editor_help.cpp:218]: Thread can't directly update scrollbars, so it is done in the draw. This change is correct (scrolling after `finished` and first redraw), but we might want to add another signal instead of directly connecting to the `draw` (`finished` probably should not be changed, since other code might expect it to fire even for hidden RTL that will never redraw).

Comment (akien-mga) [reply editor/editor_help.cpp]: @ydeltastar WDYT about the above suggestion? Do you want to implement that?

Comment (ydeltastar) [reply editor/editor_help.cpp]: Sounds good. I added a signal that triggers after loading, processing, and validation for drawing. It also needed an equivalent method for 'is_finished()' so the `EditorHelp` could use the signal correctly.

Comment (Mickeon) [reply editor/editor_help.cpp]: I'm very perplexed on the addition of another signal. It sounds "needlessly" confusing. I'd be wary as developers may use one or the other without understanding the difference.

Comment (ydeltastar) [reply editor/editor_help.cpp]: Yeah, all it does is simulate a one-shot connection to `draw`. It is very specific, can only happen in the first draw after `finished` so it could be just a note in the documentation as well.

Comment (KoBeWi) [reply editor/editor_help.cpp]: Maybe you can connect to `finished` and then in the callback connect to `draw`?

Comment (ydeltastar) [reply editor/editor_help.cpp]: It's what I did in the first iteration. I reverted the PR to it and added a note to the `finished` signal.

Comment (KoBeWi) [reply editor/editor_help.cpp]: Yeah, simpler solutions are better. No point in adding a signal if it does the same.

**Review by KoBeWi — APPROVED** [review]
Fixes the bug.

**Comment by Repiteo** [comment]
Thanks!
