### PR TITLE
Fix synchronization of global class name

### LINKED ISSUE #75388: Plugins & Autoloaded scripts breaks project if classes missing from global_script_class_cache.cfg
### Godot version

4.0, 4.0.1

### System information

Windows 11/64, RTX 3070, Vulkan

### Issue description

This will break our game and give hundreds of errors without our workarounds. It appears that autoloaded scripts are loaded before `global_script_class_cache.cfg` is populated, yet Godot only loads class names from that file. So, if a class isn't registered in the file, the autoload fails.

```gdscript
# ItemDB.gd:  <- Autoloaded
extends Node

var stats: Stats

func _ready():
	Util.test()
```

```gdscript
# Stats.gd
class_name Stats
extends Resource
```

```gdscript
# Util.gd
class_name Util

static func test():
	pass
```

Autoload ItemDB.gd, then close Godot, delete `global_script_class_cache.cfg` and reload. It will break with these errors:

```
SCRIPT ERROR: Parse Error: Could not find type "Stats" in the current scope.
          at: GDScript::reload (res://ItemDB.gd:3)
SCRIPT ERROR: Parse Error: Identifier "Util" not declared in the current scope.
          at: GDScript::reload (res://ItemDB.gd:6)
ERROR: Script does not inherit from Node: res://ItemDB.gd.
   at: (editor/editor_autoload_settings.cpp:423)
```

Stats and Util are two examples of the same problem. They can be tested independently. It is also an issue with any derivative classes. If ItemDB has an Item, which has a Stats, which is our set up, this also causes the issue.

It's not just a problem with an empty cache file. If someone on a team makes a change to these classes and saves the new class locally, those changes will not get to other team members via git, because Godot does not generate the new cache properly. We have some autoloaded base classes, so when this breaks, we get hundreds of error messages across many scripts.

Workarounds include:
* Manually open each gdscript file in Godot and resave without changes, one at a time. This will populate the local `global_script_class_cache.cfg`. Opening all, then saving all does not do it.
* Copy `global_script_class_cache.cfg` from another computer
* Store `global_script_class_cache.cfg` in git. In spite of the name, it is NOT a cache. We ended up doing this to work around this bug.

This bug has been present for a long while. We worked around it for a while, but finally discovered the exact circumstances today.

In my game, I have received this error message, though I don't get it in the MRP or while debugging. It may provide a clue:
```
ERROR: Condition "!base->is_valid() && !base->reloading" is true. Returning: ERR_BUG
   at: _populate_class_members (modules/gdscript/gdscript_compiler.cpp:2318)
```

The script cache can be added to .gitignore without adding the whole directory with this
```
/project/.godot/*
!/project/.godot/global_script_class_cache.cfg
```

### Minimal reproduction project

[test_gdscript_cache.zip](https://github.com/godotengine/godot/files/11077941/test_gdscript_cache.zip)

_Bugsquad edit: used syntax highlighting for example gdscript code_

### LINKED ISSUE #76380: Class names stop working after a while
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10, Compatability

### Issue description

I'm getting a problem where class names that I define in GDScript just stop working after a while.  I'm not sure what is causing this.  I am just noticing that when I'm working on a project where I've defined a lot of classes using `class_name MyClassName` the name will just stop being recognized after a while.  Sometimes if I restart the editor two times it will become available again.  

Sometimes a class name that I had been using for a long time just stops working and I have to append a '2' to the class name to be able to use the class again.  This is not due to name collisions - these are the only classes in my project with this name and they're complicated enough that I doubt they are part of the core GDScript api.

I suspect the Godot editor is caching something that is persisting between sessions, and whatever that is is interfering with the ability of the script to compile 

### Steps to reproduce

I'm not sure what causes this.  It might be related to duplicating a .gd resource and then editing it, but not always.  I'm just noticing that after working on a project for a while, some class names just stop being recognized.

### Minimal reproduction project

N/A

### LINKED ISSUE #81615: Using other scripts by their class_name in an import plugin causes import to fail
### Godot version

4.1.1-stable

### System information

Godot v4.1.1.stable (fabd7c89d) - Arch Linux #1 SMP PREEMPT_DYNAMIC Sat, 10 Jun 2023 00:35:35 +0000 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 970 (nvidia; 530.41.03) - AMD Ryzen 5 2600 Six-Core Processor (12 Threads)

### Issue description

I have been encountering a strange issue where builds of my project created and exported from a fresh clone of the repo are missing their translations. I've narrowed this down to a weird quirk of import plugin scripts (my project uses a custom editor plugin to import translations). It seems as though global script class names don't exist during the initial import.

The reproducer project contains a CSV file `translations/example.csv` and its corresponding .import set up to be imported using the "Translation Plus" plugin.

If the two lines at the top of `addons/translation_plus/import_plugin.gd` that shadow the global class names `TranslationSet` and `TranslationPlus` are commented out, and the project's hidden .godot directory is removed, then the next time the project is opened, importing example.csv fails.

### Steps to reproduce

1. Download the attached reproducer.
2. Open the project in Godot and notice `translation/example.csv` is imported as `Translation Plus`.
3. Open the script `addons/translation_plus/import_plugin.gd`
4. Comment the two lines (these lines should not be necessary as TranslationSet and TranslationPlus are global script class names):
```GDScript
const TranslationSet = preload("translation_set.gd")
const TranslationPlus = preload("translation_plus.gd")
```

5. Close the project
6. Erase the .godot directory so that the editor does a clean reimport next time it opens the project.
7. Open the project and observe that example.csv fails to import and instead Godot imports it as `CSV Translation`. Errors are logged:

```
res://addons/translation_plus/import_plugin.gd:84 - Parse Error: Identifier "TranslationSet" not declared in the current scope.
  res://addons/translation_plus/import_plugin.gd:84 - Parse Error: Cannot infer the type of "xset" variable because the value doesn't have a set type.
  res://addons/translation_plus/import_plugin.gd:92 - Parse Error: Identifier "TranslationPlus" not declared in the current scope.
  res://addons/translation_plus/import_plugin.gd:92 - Parse Error: Cannot infer the type of "t" variable because the value doesn't have a set type.
  res://addons/translation_plus/import_plugin.gd:96 - Parse Error: Could not find type "TranslationPlus" in the current scope.
  res://addons/translation_plus/import_plugin.gd:98 - Parse Error: Identifier "TranslationPlus" not declared in the current scope.
  res://addons/translation_plus/plugin.gd:7 - Invalid call. Nonexistent function 'new' in base 'GDScript'.
  editor/editor_file_system.cpp:2280 - Condition "!importer.is_valid()" is true. Continuing.
```

### Minimal reproduction project

[csv-import-plugin.zip](https://github.com/godotengine/godot/files/12598671/csv-import-plugin.zip)

### LINKED ISSUE #92054: Pulling GDScript changes that introduce a new `class_name` results in errors
### Tested versions

Reproducible in: 4.3.dev [bd2300d77]

### System information

Windows 11 (10.0.22631)

### Issue description

This is tangentially related to #75388, except this issue does not necessarily need to involve autoloads or plugins.

When you're doing something like pulling in changes to your project from another Git repository, and those changes contain a new GDScript class with a `class_name`, which is then used in another GDScript file (existing or otherwise) you will be met with errors like this:

```
res://main.gd:5 - Parse Error: Identifier "SomeNewThing" not declared in the current scope.
modules\gdscript\gdscript.cpp:2895 - Failed to load script "res://main.gd" with error "Parse error". (User)
```

If you then reload the current project, you'll find that everything parses just fine.

The reason for this seems quite simple. Scripts are loaded and fully parsed as part of `EditorFileSystem::_update_scan_actions`, and the updating of the global `class_name` cache happens as part of `EditorFileSystem::_update_pending_script_classes`, which happens after `_update_scan_actions`, as seen [here](https://github.com/godotengine/godot/blob/bd2300d77a6008167043f23fd91bcc562cde0a19/editor/editor_file_system.cpp#L1278-L1279).

So the global `class_name` cache would presumably need to be updated before scripts are fully parsed somehow.

### Steps to reproduce

1. Open the MRP.
2. Once loaded, run `git checkout b64a4b4dd`.
3. Note the errors shown in the editor's Output pane.
4. Reload the project.
5. Note the absence of any errors.

(To go back to the initial commit, do `git checkout f4f9e9d17`.)

### Minimal reproduction project (MRP)

[ClassNamePullErrors.zip](https://github.com/godotengine/godot/files/15353961/ClassNamePullErrors.zip)

### PR DESCRIPTION
**Pull request by Hilderin**
This should fix the issues #76380, #75388, #81615 and #92054

This should manage these situations:
- At startup, the global_script_class_cache.cfg is missing or incomplete but the filesystem cache is present
- At startup, the global_script_class_cache.cfg and the system cache are missing
- At startup, the global_script_class_cache.cfg is missing classes but are present on disk
- At startup, the global_script_class_cache.cfg has a class that does not exists on disk
- At startup, the path for class name in global_script_class_cache.cfg has changed
- In the editor if the user duplicates a script with a class name and change the class name after
- In the editor if the user changes the class name for an existing class name and change it again
- In the editor if the user deletes a folder containing a script with a class name that is used by another script
- Exporting project from command line that uses global class names in addons without or with an invalid global_script_class_cache.cfg
- Updating scripts from outside the Editor that uses new global class name

The global class name are now loaded from the scripts at the editor startup, always recreating the global_script_class_cache.cfg. When not in the editor, the global_script_class_cache.cfg is used for performance when the project runs.

<i>Bugsquad edit:</i>
- Fix #76380
- Fix #75388
- Fix #81615 
- Fix #92054

<i>Edited: Adding modifications for the issue #81615 </i>
<i>Edited: Updating for the modifications loading class name at startup from scripts. </i>
<i>Edited: Adding modifications for the issue #92054 </i>
<i>Edited: Adding fix for deletion of folders </i>

### CODE REVIEW

**Comment by donn-xx** [comment]
If this works, you will be a God amongst ots! :D

File: editor/editor_autoload_settings.cpp [hunk 1]
```diff
@@ -419,6 +419,10 @@ Node *EditorAutoloadSettings::_create_autoload(const String &p_path) {
 
 		Ref<Script> scr = res;
 		if (scr.is_valid()) {
+			if (!scr->is_valid()) {
+				autoload_invalid_scripts.push_back(scr);
+			}
+			ERR_FAIL_COND_V_MSG(!scr->is_valid(), nullptr, vformat("Failed to create an autoload, script '%s' is not compiling.", p_path));
```
Comment (AThousandShips) [inline editor/editor_autoload_settings.cpp:425]: Move up as `ERR_FAIL_V_MSG`

**Comment by Hilderin** [comment]
I added some modifications to fix the issue #81615
I tested with the MRP project from this issue when starting the projet in the editor and exporting from the command line.

**Comment by Hilderin** [comment]
Found a problem in the is_ready condition in editor_node. Last commit should fix that.

**Comment by mihe** [comment]
While I'm sure this change will be of help to many people, since it does seem to resolve the issue of scripts ending up in a perpetual state of error and needing to be resaved one at a time, it obviously does not change the actual order of `global_script_class_cache.cfg` being populated after the initial load of the autoloads, so you'll still see errors from that initial broken compilation of the autoloads that reference any `class_name`, although it will (mostly) only output to the command-line (i.e. `stderr`) with this change, since `EditorLog` has yet to initialize when autoloads are first loaded.

This does however mean that importing from the command-line using `--headless`, through something like a CI job, either explicitly through the new `--import` option or implicitly through `--export-debug`/`--export-release`, will still emit errors. I'm able to reproduce this by exporting the repro project in #75388 for example, even with the latest commit as of this comment.

There's also the issue of the more or less official [plugin pattern](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html#registering-autoloads-singletons-in-plugins) where you have a `@tool` script that registers a potentially new autoload using `add_autoload_singleton` in its `_enter_tree`. In such a case `add_autoload_singleton` will trigger `update_autoload`, which kicks off another broken (assuming it depends on some other `class_name`) autoload compilation, which this time actually emits to the editor log, since `EditorLog` is up and running by that point. You'll see that in this repro that I just made: [autoload-plugin-errors.zip](https://github.com/godotengine/godot/files/15436861/autoload-plugin-errors.zip)

Both of these are of course largely "cosmetic" issues (as far as I can tell), since these errors seem to eventually get dealt with by your `recompile_invalid_autoload_scripts`, but any non-trivial project that uses `class_name` or a plugin autoload (like [GodotLogger](https://godotengine.org/asset-library/asset/1975)) in a widespread manner will still end up with hundreds/thousands of errors in these two scenarios if there's no valid `global_script_class_cache.cfg`.

Anyway, again, I'm not saying this change shouldn't be merged, and I shouldn't be the judge of that in the first place, but I figured I'd bring this up in case it hadn't been considered already, or if there's some discussion to be had about a more holistic solution.

**Comment by Hilderin** [comment]
Thanks @mihe for your detailed response and to take the time to test my modifications. I'll try your autoload-plugin-errors.zip and see if I can do something about the error messages.

If I understand correctly, with this fix, you have error messages in the console and output panel (and potentially a lot of them), but with the `recompile_invalid_autoload_scripts`, at some point they are working without having to resave them manualy?

**Comment by donn-xx** [comment]
A holistic solution is vital. If class_name is not immediately and always respected, then what is the point of class_name? All class_names, no matter their origins, must be known at all times.

**Comment by Hilderin** [comment]
I totally agree with that. Actually, the way I see it, the only way to really do that would be to remove completely the global_script_class_cache.cfg and reload all the class on startup from the code. I don't why it was not done like that from the beginning, maybe for performance issue?

Just today I think I saw 2-3 news issues linked to global script class.

I can try to implement it that way if everyone thinks that's a good idea? I'm a pretty new contributor, I usually try to limit the amount of code I touch, but I'm welling to try!

**Comment by donn-xx** [comment]
I don't know why there's a cache file either, but I guess it was for speed. 

Perhaps moving it out of the dot-godot directory could be an answer; but that would involve merging it with other class caches that come from plugins and general project churn. That sounds like hell.

The simplest way feels like, on startup, grepping all the resource and gdscript files for 'class_name' and thence into a hash map.

**Comment by Hilderin** [comment]
I took your advice @mihe and @donn-xx and I’m pretty happy with the result.

This commit removes the need for `global_script_class_cache.cfg` when starting the editor. It loads class_name from the scripts on disk at startup and rewrites the `global_script_class_cache.cfg`. I kept the `global_script_class_cache.cfg` for exported project and when running the project to be sure that the start time is not affected. Doing it like that, I was able to remove the `recompile_invalid_autoload_scripts` after the first full file scan, preventing potential double error messages.

I tested with a project having 3000 gdscripts of 22ko each. At first, it took 10 sec to parse every file at startup. After a bit of debugging I found out that the complete file was parsed just to find the class_name and the icon. I added a new parameter to the `GDScriptParser.parse` to only parse the script header. After this modification, it took in a debug build only around 400ms to read all the 3000 files on my Intel i5-11600 3.9Ghz on Nvme. It’s not extensive testing but I think it’s good enough, it will append only on startup of the editor.

With this modification the test project from @mihe loads without any error or warning event if the .godot folder is missing or the 
`global_script_class_cache.cfg` missing or invalid.

**Comment by Hilderin** [comment]
I also tested the MRP from #75388 and #92054 with these news modifications, and everything seems to work fine, even on fresh git clone (no .godot folder).

**Comment by donn-xx** [comment]
I am holding my breath! So excite!

**Comment by donn-xx** [comment]
While this fix is underway, it might be a good time to raise the issue of the `classDB` object *not* having access to these user scripted classes.

There is this convo about it: https://github.com/godotengine/godot/pull/71665 and this comment sums-up my feelings on it: https://github.com/godotengine/godot/pull/71665#issuecomment-1399369620

**Comment by AThousandShips** [comment]
That's not relevant to this so please stay on topic

File: core/object/script_language.cpp [hunk 2]
```diff
@@ -261,40 +306,118 @@ void ScriptServer::init_languages() {
...
-	{
-		MutexLock lock(languages_mutex);
-		for (int i = 0; i < _language_count; i++) {
-			if (_languages[i]) {
-				langs_to_init.insert(_languages[i]);
+	da->list_dir_end();
+
+	for (List<String>::Element *E = dirs.front(); E; E = E->next()) {
+		String name = E->get();
+		if (da->change_dir(name) == OK) {
```
[the remark this answers is not in the document]
Comment (Hilderin) [reply core/object/script_language.cpp]: Good catch for the `change_dir`. This should be fixed now .

I search the base code for another way to get all the project file and I was only 2 places:
`GDScriptWorkspace::list_script_files` and `EditorFileSystem::_scan_filesystem`. Both places are not easy to encapsulate and reuse. I can create something somewhere and reuse it in both places, like creating a ProjectDirAccess ??
I'm open to suggestion.

**Comment by mihe** [comment]
I also just tried #92054 with this PR, and I'm not seeing it fixed like you mentioned above, @Hilderin.

What seems to happen is that `_update_scan_actions` runs, where `_update_script_classes` does nothing, because no script classes have been queued up yet, then the script classes do get queued up due to being in `scan_actions`, and because one of them is added to the `reloads` list then `resources_reload` signal is fired at the end of `_update_scan_actions` which invokes `EditorNode::_resources_changed` which in turn causes a full parse of the file before any global class names have had a chance to be added.

**Comment by Hilderin** [comment]
I'll look into this, thanks for testing.

**Comment by Hilderin** [comment]
@mihe I just retested the project from #92054, I did not realized that you were running the editor when you do the git checkout. I'll look into it later today.

**Comment by Hilderin** [comment]
@KoBeWi I tested your addon. These are the error I get:
image

I don't see any error from missing global class. I think, these errors are due to addons being loaded before the resources. This PR should fix this problem: https://github.com/godotengine/godot/pull/86453
You probably need both fixes to make it work. I'll try later creating a branch with both fixes to test it.

**Comment by Hilderin** [comment]
@KoBeWi I merge my PR and the PR from https://github.com/godotengine/godot/pull/86453 and no, it does not fix the problem. The https://github.com/godotengine/godot/pull/86453 was only focused on addons script dans not autoload from what I understand. Do you have a issue open for that, maybe I can take a look in another PR.

**Comment by KoBeWi** [comment]
> Do you have a issue open for that, maybe I can take a look in another PR.

I opened https://github.com/godotengine/godot/issues/92493

**Review by SudeySjan — APPROVED** [review]
@losinggeneration

File: modules/mono/csharp_script.cpp [hunk 3]
```diff
@@ -443,7 +443,9 @@ bool CSharpLanguage::handles_global_class_type(const String &p_type) const {
 
 String CSharpLanguage::get_global_class_name(const String &p_path, String *r_base_type, String *r_icon_path) const {
 	String class_name;
-	GDMonoCache::managed_callbacks.ScriptManagerBridge_GetGlobalClassName(&p_path, r_base_type, r_icon_path, &class_name);
+	if (gdmono && gdmono->is_runtime_initialized() && GDMonoCache::godot_api_cache_updated) {
```
Comment (raulsntos) [inline modules/mono/csharp_script.cpp:446]: I feel like the runtime is guaranteed to be initialized at this point. Did the changes in this PR make Godot try to get the global class name of C# scripts before initialization?

Comment (Hilderin) [reply modules/mono/csharp_script.cpp]: I think you are right, that was my first tentative to fix a crash in the CI pipeline with `--generate-mono-glue`. I was not able to reproduce on my computer, but since, I added a check if `ProjectSettings::get_singleton()->is_project_loaded()` is true before loading class names from disk.
I removed the check, we will see if CI pipeline passes.

**Comment by lostminds** [comment]
This should also fix/close #83395

**Comment by Hilderin** [comment]
Rebased following merge conflicts.

**Comment by reduz** [comment]
I did a review and I am not very found of the approach. The manual filesystem scan in ScriptServer is likely overkill. EditorFileSystem is specially optimized to only scan files and directories that change, which allows for the editor to remain snappy even with very large projects. This PR goes against that.

The way I would solve this is directly inside EditorFileSystem by having a more layered way to scan the files. Probably something like:


1. Scan all changes
2. Instead of doing changes immediately, build a list of things that changed.
3. Pre process scripts first in the list.
4. Process everything else.

**Comment by KoBeWi** [comment]
> EditorFileSystem is specially optimized to only scan files and directories that change, which allows for the editor to remain snappy even with very large projects.

Eh, that's not entirely true. FileSystemDock rescans all files on pretty much every operation. It's nice that EditorFileSystem was designed this way, but it's not used this way.

**Comment by reduz** [comment]
@KoBeWi look again, it uses EditorFileSystem:

https://github.com/godotengine/godot/blob/e2fc6d38cb240ea23bd5700514f8a8ce7011e89c/editor/filesystem_dock.cpp#L230

**Comment by reduz** [comment]
@KoBeWi And in EditorFileSystem, only directories that change are scanned:

https://github.com/godotengine/godot/blob/e2fc6d38cb240ea23bd5700514f8a8ce7011e89c/editor/editor_file_system.cpp#L981

**Comment by KoBeWi** [comment]
I only looked at what happens in the editor, and what happens is that in a big project renaming or doing anything with a file/folder makes FileSystemDock turn into scanning mode for few seconds as it processes every single file, so e.g. duplicating and renaming a file, instead of taking 2-3 seconds, takes 30. See #50576

**Comment by reduz** [comment]
@KoBeWi No idea about this, it may be an unrelated bug, but remember that renaming needs to change all dependencies to the file. When we complete the transition to using UIDs then this may not be needed anymore.

**Comment by Hilderin** [comment]
Just to be sure it's clear, the full scan of scripts to load the global class names is done only at the startup, not on very full scan (ex: renaming a file in the FileSystem Dcock). On large project, it could be very slow.

**Comment by reduz** [comment]
@Hilderin There is only full scan on first startup. Even for subsequent startups, EditorFileSystem keeps a file with a cache. This is why ideally, what you are trying to do probably should happen there.

**Comment by Hilderin** [comment]
Exactly!  The problem identified by the users is that the .godot folder is not always up to date or present on CI servers or on user computers. When multiple users are working on the same project. On pull or checkout from git, if Godot is not running, the global_script_class_cache.cfg is not updated, causing problems on startup.

I'll have to think about your suggestion:
>Scan all changes
>Instead of doing changes immediately, build a list of things that changed.
>Pre process scripts first in the list.
>Process everything else.

I like your suggestion to find only the changed scripts while scanning for changes in the first scan. I guess we will also need to remove global class names that no longer exist. My concern is the plugins that are loaded before the first scan. These plugins need the global class names to be loaded. If we do it, we will need to move the plugins loading after the Pre process of scripts (reading Global class names) and before the processing of everything else.

That seems a lot of modifications, what do you think?

**Comment by Hilderin** [comment]
I tried to implement the suggestion of @reduz but my I have serious problem:
The comparison of the files and the hash to validate the filesystem_cache8 on the first scan uses the importers. Importers can be customized by plugins. I don't think it's possible to accurately check if the file changed without validating the .import file. And revalidating the .import files without the plugins loaded seems not possible also. If I load the plugins before global class names, they could fail. I don't see right now how the suggestion "Instead of doing changes immediately, build a list of things that changed" could be done without the plugins loaded.

One approach could be:
- First scan: load the `new_filesystem` for all the files but validate only the scripts and call `_queue_update_script_class` if modified
- Update global class names
- Create autoloads
- Init plugins
- Validate all the other file in `new_filesystem` and build `scan_actions` if modified
- Execute `_update_scan_actions` as usual

I'll try that tomorrow!

There is a branch of a new draft: https://github.com/Hilderin/godot/tree/fix-synchronization-global-class-name-v2
Commit: https://github.com/Hilderin/godot/commit/a27547e15f680a948340ec7e1db018837451fa08

**Comment by reduz** [comment]
@Hilderin I would suggest something as follows:

1. Modify the [scan filesystem function](https://github.com/godotengine/godot/blob/master/editor/editor_file_system.cpp#L214) to instead just return a list of files that have to be checked/updated/scanned.
2. Once you have the list, try to go through it a couple of times by priority, such as:
   * Scan all scripts for class names
   * Check add-ons and load them. I think we could probably, worst case, add some API to add ons that they are adding importers? so they are parsed first.
   * If add-ons added new importers (We could kind of do this by checking the amount of them before and after doing this step), goto 1. (redo scanning)
   
I think this should work for the most part. As I mentioned, the main issue is how we handle importers, so this may need to change in the engine (maybe new API to expose those?).

**Comment by Hilderin** [comment]
Thanks for your feedback @reduz really appreciated. I'll check that tonight.

**Comment by donn-xx** [comment]
Thanks @Hilderin for working on this problem. It sounds thorny, but is totally essential!

**Comment by Hilderin** [comment]
I just pushed a new version for this PR following the recommendation of @reduz.

### Modifications:
- This new version reverts all the modifications in ScriptServer and puts the management of the `global_script_class_cache.cfg` back in ProjectSettings.
- All scans are now done directly in EditorFileSystem as it should be.
- The loading of autoloads and plugins have been moved to the first scan.
- The first part of the first scan is done in the new method `_first_scan_filesystem`.
- `_scan_new_dir` only discovers the directories and files and calculates the file types.
- A new method `_process_file_system` validates the files and creates actions for updates/reimportations. It has two modes:
  - Script Only: Used in `_first_scan_filesystem` to process only scripts to load global class names.
  - All: Processes all the files. This mode is used after the global class names, autoloads, and plugins are loaded.
- The progress bar in FileSystemDock has been fixed while processing files.

### Algorithm:
- On the first scan, call `_first_scan_filesystem`:
  - Discover all the files (`_scan_new_dir`).
  - Process all the scripts.
  - Load autoloads.
  - Load plugins.
  - If new importers have been added:
    - Rediscover all the files (`_scan_new_dir`): new extensions or resource types could have been added/updated from custom importers.
    - Process all the discovered files (`_process_file_system`).

- On subsequent scans:
  - Discover all the files (`_scan_new_dir`).
  - Process all the discovered files (`_process_file_system`).


### Test cases
It took my a while but I retested all these test cases with different MRP from issues:
- At startup, the global_script_class_cache.cfg is missing or incomplete but the filesystem cache is present
- At startup, the global_script_class_cache.cfg and the system cache are missing
- At startup, the global_script_class_cache.cfg is missing classes but are present on disk
- At startup, the global_script_class_cache.cfg has a class that does not exists on disk
- At startup, the path for class name in global_script_class_cache.cfg has changed
- In the editor if the user duplicates a script with a class name and change the class name after
- In the editor if the user changes the class name for an existing class name and change it again
- In the editor if the user deletes a folder containing a script with a class name that is used by another script
- Exporting project from command line that uses global class names in addons without or with an invalid global_script_class_cache.cfg
- Updating scripts from outside the Editor that uses new global class name

**Comment by Hilderin** [comment]
Just rebased from master after new conflicts.

File: modules/gdscript/gdscript_parser.h [hunk 4]
```diff
@@ -1560,7 +1561,7 @@ class GDScriptParser {
 #endif // TOOLS_ENABLED
 
 public:
-	Error parse(const String &p_source_code, const String &p_script_path, bool p_for_completion);
+	Error parse(const String &p_source_code, const String &p_script_path, bool p_for_completion, bool p_parse_body = true);
```
Comment (adamscott) [inline modules/gdscript/gdscript_parser.h:1564]: Instead of having a short-circuit parameter, I would just create a new method for the class.

Comment (Hilderin) [reply modules/gdscript/gdscript_parser.h:1564]: Just to be sure I understand correctly, you would prefer a new method like `parse_header` that only takes the parameters `p_source_code` and `p_script_path`, and remove the parameter `p_parse_body` from `parse`?

I suggest renaming the current `parse` to `_parse` and making it private, then creating a new method `parse` that calls `_parse` with `p_parse_body` set to true.
Like that:
```cpp
private:
Error _parse(const String &p_source_code, const String &p_script_path, bool p_for_completion, bool p_parse_body = true);
public:
Error parse(const String &p_source_code, const String &p_script_path, bool p_for_completion);
Error parse_header(const String &p_source_code, const String &p_script_path);
```
Does it sounds a good idea? I don't want to duplicate the code from `parse` method.

File: editor/editor_autoload_settings.cpp [hunk 5]
```diff
@@ -436,6 +434,35 @@ Node *EditorAutoloadSettings::_create_autoload(const String &p_path) {
...
+			memdelete(info.node);
+			info.node = nullptr;
+		}
+	}
+
+	for (const AutoloadInfo &info : autoload_cache) {
+		if (info.node && info.in_editor) {
+			callable_mp((Node *)get_tree()->get_root(), &Node::add_child).call_deferred(info.node, false, Node::INTERNAL_MODE_DISABLED);
+		}
+	}
```
[the remark this answers is not in the document]
Comment (Hilderin) [reply editor/editor_autoload_settings.cpp:463]: I ask myself the same think. Before this PR, it was done at different places in the code. I just want to be sure every autoload nodes are created and `ScriptServer::get_language(i)->add_named_global_constant(info.name, info.node);` is done for every node before adding them in the tree to be as close as possible to current behavior. I guess 2 autoloads can use each other global constant name??

File: editor/editor_node.cpp [hunk 6]
```diff
@@ -858,6 +842,23 @@ void EditorNode::_update_update_spinner() {
...
+	}
+
+	for (int i = 0; i < addons.size(); i++) {
+		set_addon_plugin_enabled(addons[i], true);
+	}
+	_initializing_plugins = false;
+
+	if (!pending_addons.is_empty()) {
+		EditorFileSystem::get_singleton()->connect("script_classes_updated", callable_mp(this, &EditorNode::_enable_pending_addons));
+	}
```
[the remark this answers is not in the document]
Comment (Hilderin) [reply editor/editor_node.cpp:859]: I really asked myself this exact question. I did not understand it, so I left it there.

**Comment by Hilderin** [comment]
@reduz
I think I finally managed to do only one disk scan and use it twice, the first time in `_first_scan_process_scripts` and the second time in `_scan_filesystem` on the first scan.

I just push some modifications:
- `_scan_new_dir` loads all the files in a `ScannedDirectory` object.
- `_first_scan_process_scripts` uses `ScannedDirectory` to process all the scripts. No needs to queue them with `_queue_update_script_class`, I call directly `_register_global_class_script`. The full process of scripts is done in `_update_scan_actions`.
- `_first_scan_filesystem` does not need to check for new custom importers since it does not load a EditorFileSystemDirectory.  All scans are done with `ScannedDirectory`.
- `_process_file_system` always process all files, so the parametre `p_process_step` (script only or full) has been removed.
- `_update_extensions` have been moved after `_first_scan_filesystem` to be sure extensions are correctly loaded before `_scan_filesystem`.

Algorithm:
- On the first scan, call `_first_scan_filesystem`:
  - Discover all the files (`_scan_new_dir`) and keep it in `first_scan_root_dir`.
  - Process all the scripts (`_first_scan_process_scripts`).
  - Load autoloads.
  - Load plugins.
  - Update extensions (`_update_extensions`).
  - Scan files (`_scan_filesystem`):
    - Use files in `first_scan_root_dir`.
    - Process all the discovered files (_process_file_system).
- On subsequent full scans (ex: renaming files):
  - Discover all the files (_scan_new_dir).
  - Process all the discovered files (_process_file_system).

**Comment by Hilderin** [comment]
I moved the removal of invalid global class names in `_first_scan_filesystem` to fix the crash from #93410
Even if this fix the problem, I created another PR #93575 just to add a validation in GDScriptAnalyzer that cloud be merged more easily.

File: editor/editor_node.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (KoBeWi) [reply editor/editor_node.cpp:859]: Yeah I just confirmed that this is still needed.

File: editor/editor_autoload_settings.cpp [hunk 7]
```diff
@@ -419,6 +414,9 @@ Node *EditorAutoloadSettings::_create_autoload(const String &p_path) {
 
 		Ref<Script> scr = res;
 		if (scr.is_valid()) {
+			if (!scr->is_valid()) {
```
Comment (KoBeWi) [inline editor/editor_autoload_settings.cpp:417]: This condition does not make sense.

Comment (Hilderin) [reply editor/editor_autoload_settings.cpp:417]: Strangely `.is_valid` and `->is_valid` does not valid the same thing. `.is_valid` checks if the resource exists and `->is_valid` checks if the script is valid (compiles). The problem I tried to fixe here is the wrong error message that was displayed when the script is invalid at startup: "Failed to create an autoload, script '%s' does not inherit from 'Node'" which is not necessarily true. Maybe there's a better way to do that?

Comment (KoBeWi) [reply editor/editor_autoload_settings.cpp:417]: Ah yeah I didn't notice `.` and `->`, they are indeed different. So I guess this is correct.

File: editor/editor_autoload_settings.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (KoBeWi) [reply editor/editor_autoload_settings.cpp:463]: Yeah if autoloads were added in the first loop, trying to access another autoload can yield null, depending on order. This way it's a bit more friendly.

I'm surprised that autoload references seem to be order-independent. I remember wrong order could cause script parsing errors, but it's not the case now (even without this PR).

File: editor/editor_file_system.h [hunk 8]
```diff
@@ -159,11 +159,22 @@ class EditorFileSystem : public Node {
 		EditorFileSystemDirectory::FileInfo *new_file = nullptr;
 	};
 
+	class ScannedDirectory {
+		friend class EditorFileSystem;
```
Comment (KoBeWi) [inline editor/editor_file_system.h:163]: You can instead change this class to `struct` and put it under `private:`, though it's a cosmetic change.

Comment (Hilderin) [reply editor/editor_file_system.h:163]: I'll change for a struct to be like the other structs in EditorFileSystem but what do you mean by "put it under private:", there is no 'private:' section in EditorFileSystem, I can add one still.

Comment (Hilderin) [reply editor/editor_file_system.h]: I changed it for a struct.

File: core/object/script_language.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (Hilderin) [reply core/object/script_language.cpp]: This code does not exists anymore.

File: editor/editor_file_system.cpp [hunk 9]
```diff
@@ -1894,31 +2088,34 @@ HashSet<String> EditorFileSystem::get_valid_extensions() const {
...
-	int index = -1;
-	EditorFileSystemDirectory *efd = find_file(p_search_path, &index);
-
-	if (!efd || index < 0) {
-		// The file was removed
-		return;
-	}
-
-	if (!efd->files[index]->script_class_name.is_empty()) {
+	if (!p_script_class_name.is_empty()) {
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:2094]: You could change this to early return.

File: editor/editor_file_system.cpp [hunk 10]
```diff
@@ -1894,31 +2088,34 @@ HashSet<String> EditorFileSystem::get_valid_extensions() const {
...
+	}
+}
+
+void EditorFileSystem::register_global_class_script(const String &p_search_path, const String &p_target_path) {
+	int index_file;
+	EditorFileSystemDirectory *efsd = find_file(p_search_path, &index_file);
+	if (efsd) {
+		EditorFileSystem::get_singleton()->_register_global_class_script(p_search_path, p_target_path, efsd->files[index_file]->type, efsd->files[index_file]->script_class_name, efsd->files[index_file]->script_class_extends, efsd->files[index_file]->script_class_icon_path);
+	} else {
+		EditorFileSystem::get_singleton()->_register_global_class_script(p_search_path, p_target_path, "", "", "", "");
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:2118]: This will just remove the script, no? You could call `remove_global_class_by_path()` directly.

File: editor/editor_file_system.cpp [hunk 11]
```diff
@@ -1894,31 +2088,34 @@ HashSet<String> EditorFileSystem::get_valid_extensions() const {
...
+		EditorNode::get_editor_data().script_class_set_icon_path(p_script_class_name, p_script_class_icon_path);
+		EditorNode::get_editor_data().script_class_set_name(p_target_path, p_script_class_name);
+	}
+}
+
+void EditorFileSystem::register_global_class_script(const String &p_search_path, const String &p_target_path) {
+	int index_file;
+	EditorFileSystemDirectory *efsd = find_file(p_search_path, &index_file);
+	if (efsd) {
+		EditorFileSystem::get_singleton()->_register_global_class_script(p_search_path, p_target_path, efsd->files[index_file]->type, efsd->files[index_file]->script_class_name, efsd->files[index_file]->script_class_extends, efsd->files[index_file]->script_class_icon_path);
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:2116]: You could add `const FileInfo *fi = efsd->files[index_file]`, to avoid accessing the vector for every variable.

File: editor/editor_file_system.cpp [hunk 12]
```diff
@@ -215,8 +216,63 @@ EditorFileSystemDirectory::~EditorFileSystemDirectory() {
 	}
 }
 
+EditorFileSystem::ScannedDirectory::~ScannedDirectory() {
+	for (int i = 0; i < subdirs.size(); i++) {
+		memdelete(subdirs[i]);
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:221]:
```suggestion
	for (ScannedDirectory *dir : subdirs) {
		memdelete(dir);
```

File: editor/editor_file_system.cpp (hunk 9 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp]: Done!

File: editor/editor_file_system.cpp (hunk 10 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp]: Done!

File: editor/editor_file_system.cpp (hunk 11 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp]: Done! I did that in a couple of other places to make the code more readable.

File: editor/editor_file_system.cpp (hunk 12 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp]: Done! Did the same thing in `~EditorFileSystemDirectory`  just above.

File: editor/editor_file_system.cpp [hunk 13]
```diff
@@ -206,17 +207,72 @@ EditorFileSystemDirectory::EditorFileSystemDirectory() {
...
+
+EditorFileSystem::ScannedDirectory::~ScannedDirectory() {
+	for (ScannedDirectory *dir : subdirs) {
+		memdelete(dir);
+	}
+}
+
+void EditorFileSystem::_first_scan_filesystem() {
+	Ref<DirAccess> d = DirAccess::create(DirAccess::ACCESS_RESOURCES);
+	d->change_dir("res://");
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:227]: The `change_dir()` is unnecessary, `ACCESS_RESOURCES` already sets this path.

Comment (Hilderin) [reply editor/editor_file_system.cpp]: Done, also made the same modification in `_scan_filesystem`.

File: editor/editor_file_system.cpp [hunk 14]
```diff
@@ -206,17 +207,71 @@ EditorFileSystemDirectory::EditorFileSystemDirectory() {
...
+}
+
+void EditorFileSystem::_first_scan_process_scripts(const ScannedDirectory *p_scan_dir, const String p_dir_path, HashSet<String> &p_existing_class_names) {
+	String dir_full_path = p_dir_path.path_join(p_scan_dir->name);
+
+	for (ScannedDirectory *scan_sub_dir : p_scan_dir->subdirs) {
+		_first_scan_process_scripts(scan_sub_dir, dir_full_path, p_existing_class_names);
+	}
+
+	for (String scan_file : p_scan_dir->files) {
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:255]:
```suggestion
	for (const String &scan_file : p_scan_dir->files) {
```

File: editor/editor_file_system.cpp [hunk 15]
```diff
@@ -206,17 +207,71 @@ EditorFileSystemDirectory::EditorFileSystemDirectory() {
...
+		String path = dir_full_path.path_join(scan_file);
+		String type = ResourceLoader::get_resource_type(path);
+
+		if (ClassDB::is_parent_class(type, SNAME("Script"))) {
+			String script_class_extends;
+			String script_class_icon_path;
+			String script_class_name = _get_global_script_class(type, path, &script_class_extends, &script_class_icon_path);
+			_register_global_class_script(path, path, type, script_class_name, script_class_extends, script_class_icon_path);
+
+			if (!script_class_name.is_empty() && !p_existing_class_names.has(script_class_name)) {
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:265]: What's this condition for?
Especially the latter one, which is unnecessary for Set.

File: editor/editor_file_system.cpp [hunk 16]
```diff
@@ -1179,19 +1298,63 @@ void EditorFileSystem::_delete_internal_files(const String &p_file) {
...
 		sp.progress = &pr;
-		sp.hi = 1;
-		sp.low = 0;
+		sp.hi = efs->nb_files_total;
 		efs->_scan_fs_changes(efs->filesystem, sp);
 	}
 	efs->scanning_changes_done.set();
 }
 
+void EditorFileSystem::_remove_invalid_global_class_name(const HashSet<String> &p_existing_class_names) {
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:1331]:
```suggestion
void EditorFileSystem::_remove_invalid_global_class_names(const HashSet<String> &p_existing_class_names) {
```
It removes multiple classes.

File: editor/editor_file_system.cpp [hunk 17]
```diff
@@ -816,55 +898,59 @@ void EditorFileSystem::_scan_new_dir(EditorFileSystemDirectory *p_dir, Ref<DirAc
...
+		EditorFileSystemDirectory *sub_dir = memnew(EditorFileSystemDirectory);
+		sub_dir->parent = p_dir;
+		sub_dir->name = scan_sub_dir->name;
+		p_dir->subdirs.push_back(sub_dir);
+		_process_file_system(scan_sub_dir, sub_dir, p_progress);
 	}
 
-	for (List<String>::Element *E = files.front(); E; E = E->next(), idx++) {
-		String ext = E->get().get_extension().to_lower();
+	for (String scan_file : p_scan_dir->files) {
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:942]:
```suggestion
	for (const String &scan_file : p_scan_dir->files) {
```

File: modules/gdscript/gdscript_parser.h (hunk 4 above)
Comment (KoBeWi) [reply modules/gdscript/gdscript_parser.h:1564]: I don't see why adding an optional parameter in an unexposed method would be a problem. Unless it's used with `callable_mp()` somewhere.

File: editor/filesystem_dock.cpp [hunk 18]
```diff
@@ -537,7 +537,7 @@ void FileSystemDock::_notification(int p_what) {
 
 			_update_display_mode();
 
-			if (EditorFileSystem::get_singleton()->is_scanning()) {
+			if (EditorFileSystem::get_singleton()->is_scanning() || EditorFileSystem::get_singleton()->doing_first_scan()) {
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:540]: Doesn't `doing_first_scan()` imply `is_scanning()`?

File: editor/editor_node.cpp [hunk 19]
```diff
@@ -860,6 +844,23 @@ void EditorNode::_update_update_spinner() {
...
 
+void EditorNode::init_plugins() {
+	_initializing_plugins = true;
+	Vector<String> addons;
+	if (ProjectSettings::get_singleton()->has_setting("editor_plugins/enabled")) {
+		addons = GLOBAL_GET("editor_plugins/enabled");
+	}
+
+	for (int i = 0; i < addons.size(); i++) {
+		set_addon_plugin_enabled(addons[i], true);
```
Comment (KoBeWi) [inline editor/editor_node.cpp:855]:
```suggestion
	for (const String &addon : addons) {
		set_addon_plugin_enabled(addon true);
```

File: editor/editor_node.cpp [hunk 20]
```diff
@@ -860,6 +844,23 @@ void EditorNode::_update_update_spinner() {
...
+	}
+	_initializing_plugins = false;
+
+	if (!pending_addons.is_empty()) {
+		EditorFileSystem::get_singleton()->connect("script_classes_updated", callable_mp(this, &EditorNode::_enable_pending_addons));
```
Comment (KoBeWi) [inline editor/editor_node.cpp:860]:
```suggestion
		EditorFileSystem::get_singleton()->connect("script_classes_updated", callable_mp(this, &EditorNode::_enable_pending_addons), CONNECT_ONE_SHOT);
```
It should be like this actually.

**Comment by KoBeWi** [comment]
When opening a big project, the FileSystem dock changes into scanning mode, then stops at ~99% and the editor becomes unresponsive.
image
I compared it with the behavior without this PR and there is no scanning mode, however it has no impact on startup time, which is more or less the same. At least the progress bar gives some better feedback on what is happening. Though it would be nice if it stopped at 100% consistently 🤔 (does not need to be fixed now)

File: editor/editor_file_system.cpp [hunk 21]
```diff
@@ -206,17 +207,71 @@ EditorFileSystemDirectory::EditorFileSystemDirectory() {
...
+}
+
+void EditorFileSystem::_first_scan_filesystem() {
+	Ref<DirAccess> d = DirAccess::create(DirAccess::ACCESS_RESOURCES);
+
+	first_scan_root_dir = memnew(ScannedDirectory);
+
+	nb_files_total = _scan_new_dir(first_scan_root_dir, d);
+
+	HashSet<String> existing_class_names;
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:232]: This code could use some better grouping, as there is too many empty lines.

File: editor/editor_file_system.cpp [hunk 22]
```diff
@@ -816,55 +898,59 @@ void EditorFileSystem::_scan_new_dir(EditorFileSystemDirectory *p_dir, Ref<DirAc
...
+	}
+
+	p_dir->files = files;
+	nb_files_total_scan += files.size();
+
+	return nb_files_total_scan;
+}
+
+void EditorFileSystem::_process_file_system(const ScannedDirectory *p_scan_dir, EditorFileSystemDirectory *p_dir, const ScanProgress &p_progress) {
+	String dir_full_path = p_dir->get_path();
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:931]: `get_path()` computes the path by traversing its parent folders, and also does so in a very suboptimal way.
I wonder of it's worth to cache the full path String at the time of creation. Or at least `get_path()` could be changed to use StringBuilder.

File: editor/editor_file_system.cpp (hunk 14 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp]: Done!

File: editor/editor_file_system.cpp (hunk 15 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp]: Wow, I was not aware of the fact that the insert method does not fail if the key already exists.
Done!

File: editor/editor_file_system.cpp (hunk 16 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp]: Done!

File: editor/editor_file_system.cpp (hunk 17 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp]: Done!

File: editor/filesystem_dock.cpp (hunk 18 above)
Comment (Hilderin) [reply editor/filesystem_dock.cpp]: I was not sure if `EditorFileSystem::get_singleton()->is_scanning()` was still necessary. I guess not, I don't think it's possible to get a ready notification while scanning but not being the first scan.
Done!

File: editor/editor_node.cpp (hunk 19 above)
Comment (Hilderin) [reply editor/editor_node.cpp]: Done!

File: editor/editor_node.cpp (hunk 20 above)
Comment (Hilderin) [reply editor/editor_node.cpp]: Done!

File: editor/editor_file_system.cpp (hunk 21 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp]: Done!

File: editor/editor_file_system.cpp (hunk 22 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp]: I added a full_path member to ScannedDirectory and it is calculated in `_scan_new_dir`. I was able to remove the path has a parameter of `_first_scan_process_scripts`.
Done!

File: editor/filesystem_dock.cpp (hunk 18 above)
Comment (KoBeWi) [reply editor/filesystem_dock.cpp]: I meant it other way around, i.e. if `doing_first_scan()` is true, it means a scan is in progress, so `is_scanning()` should also be true. Checking both is redundant.

**Comment by Hilderin** [comment]
For the progression that does not go all away to 100%, I think it's because the scan is done before the main iteration can rerender the progress bar. After that, it's `_update_scan_actions` that is executed on the main thread that cause the editor to freeze.
Il worked on that on the PR #93064.
There are several missing progress popup to prevent the editor to freeze while loading.
At least, with this PR, we get the progress bar. I suggest I work on editor freezing and the progress bar in the PR #93064 when this one is merged.

File: editor/filesystem_dock.cpp (hunk 18 above)
Comment (Hilderin) [reply editor/filesystem_dock.cpp]: In fact, before, it was only `is_scanning()` but it caused the problem of not displaying le progress bar because on ready of the FileSystemDock, `is_scanning` returns false. `first_scan` is set to true on the creation of `EditorFileSystem` while `scanning` is set to true only when `scan` is call which is on a deferred call from `EditorNode`.
Maybe `scanning` should be true by default??

Comment (KoBeWi) [reply editor/filesystem_dock.cpp]: Once again I missed the point of this condition .-.
`is_scanning()` could have an added check for `first_scan`, but not sure if it won't break things. You can go back to the double check like before, as it was working correctly.

Comment (Hilderin) [reply editor/filesystem_dock.cpp]: I see your point, effectively, `is_scanning` should returns true when `first_scan` is true. I'm just worry about `ResourceImporterTexture::update_imports()` that checks `is_scanning`. Could adding `first_scan` in `is_scanning` have unwanted side effects?

Comment (Hilderin) [reply editor/filesystem_dock.cpp]: I tested it and I think your suggestion makes a lot of sense. It prevents updating texture imports while first scan is running. I changed `is_scanning` to include `first_scan` and used `is_scanning` in `FileSystemDock`.

File: editor/editor_node.cpp [hunk 23]
```diff
@@ -954,7 +955,8 @@ void EditorNode::_fs_changed() {
 	// FIXME: Move this to a cleaner location, it's hacky to do this in _fs_changed.
 	String export_error;
 	Error err = OK;
-	if (!export_defer.preset.is_empty() && !EditorFileSystem::get_singleton()->is_scanning()) {
+	// It's important to wait for the first scan to finish; otherwise, scripts or resources might not be imported.
+	if (!export_defer.preset.is_empty() && !EditorFileSystem::get_singleton()->is_scanning() && !EditorFileSystem::get_singleton()->doing_first_scan()) {
```
Comment (KoBeWi) [inline editor/editor_node.cpp:959]:
```suggestion
	if (!export_defer.preset.is_empty() && !EditorFileSystem::get_singleton()->is_scanning()) {
```
Unnecessary after `is_scanning()` change.

File: editor/editor_file_system.h [hunk 24]
```diff
@@ -172,8 +182,11 @@ class EditorFileSystem : public Node {
 	float scan_total;
 	String filesystem_settings_version_for_import;
 	bool revalidate_import_files = false;
+	int nb_files_total;
```
Comment (KoBeWi) [inline editor/editor_file_system.h:185]:
```suggestion
	int nb_files_total = 0;
```

File: editor/editor_file_system.h [hunk 25]
```diff
@@ -202,11 +215,10 @@ class EditorFileSystem : public Node {
 	HashSet<String> dep_update_list;
 
 	struct ScanProgress {
-		float low = 0;
-		float hi = 0;
+		mutable float hi = 0;
+		mutable int current = 0;
 		mutable EditorProgressBG *progress = nullptr;
```
Comment (KoBeWi) [inline editor/editor_file_system.h:220]: I wonder why it was designed like this. `increment()` is `const`, but it's not used in `const` context from what I see, so it's an inherently mutating method made constant for no reason.

Comment (Hilderin) [reply editor/editor_file_system.h:220]: I don't known, I found it weird too, I just went with what it was already there. I think it's to be able to pass `ScanProgress` as a const pointer in methods.

Comment (KoBeWi) [reply editor/editor_file_system.h:220]: Yeah but the pointer has no reason to be const if it's being changed 🤔

File: editor/editor_file_system.cpp [hunk 26]
```diff
@@ -711,6 +788,10 @@ bool EditorFileSystem::_update_scan_actions() {
 		_save_filesystem_cache();
 	}
 
+	// Moving the processing of pending updates before the resources_reload event to be sure all global class names
+	// are updated. Script.cpp listens on resources_reload and reloads updated scripts.
+	_process_update_pending();
```
[the remark this answers is not in the document]
Comment (Hilderin) [reply editor/editor_file_system.cpp:793]: I'm not sure I understand what you mean.

File: editor/editor_file_system.h (hunk 24 above)
Comment (Hilderin) [reply editor/editor_file_system.h]: Done!

File: editor/editor_node.cpp (hunk 23 above)
Comment (Hilderin) [reply editor/editor_node.cpp]: Done!

File: editor/editor_autoload_settings.cpp [hunk 27]
```diff
@@ -419,6 +419,9 @@ Node *EditorAutoloadSettings::_create_autoload(const String &p_path) {
...
+				ERR_FAIL_V_MSG(nullptr, vformat("Failed to create an autoload, script '%s' is not compiling.", p_path));
+			}
```
[the remark this answers is not in the document]
Comment (Hilderin) [reply editor/editor_autoload_settings.cpp]: Done!

File: editor/editor_file_system.cpp [hunk 28]
```diff
@@ -1173,19 +1294,89 @@ void EditorFileSystem::_delete_internal_files(const String &p_file) {
...
+		if (fi->script_class_name == p_class_name) {
+			r_file_info = fi;
+			return p_dir->get_path().path_join(fi->file);
+		}
+	}
+
+	for (EditorFileSystemDirectory *sub_dir : p_dir->subdirs) {
+		String file = _get_file_by_class_name(sub_dir, p_class_name, r_file_info);
+		if (!file.is_empty())
+			return file;
```
[the remark this answers is not in the document]
Comment (Hilderin) [reply editor/editor_file_system.cpp]: Done!

File: editor/editor_file_system.h (hunk 25 above)
Comment (Hilderin) [reply editor/editor_file_system.h]: Done!

File: editor/editor_file_system.cpp (hunk 26 above)
[the remark this answers is not in the document]
Comment (KoBeWi) [reply editor/editor_file_system.cpp:793]: Well nevermind.

File: editor/editor_file_system.cpp [hunk 29]
```diff
@@ -1399,11 +1558,14 @@ bool EditorFileSystem::_find_file(const String &p_file, EditorFileSystemDirector
 
 	EditorFileSystemDirectory *fs = filesystem;
 
+	String full_path = "res://";
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:1561]: Unused.

File: editor/editor_file_system.cpp [hunk 30]
```diff
@@ -1624,14 +1786,41 @@ void EditorFileSystem::_update_files_icon_path(EditorFileSystemDirectory *edp) {
 }
 
 void EditorFileSystem::_update_script_classes() {
+	if (update_script_paths.is_empty()) {
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:1789]: You could add the same early return in `_update_scene_groups()`.
I was going to open a PR for that, but it would overlap with yours.

**Review by KoBeWi — APPROVED** [review]
The changes look fine overall. I tested it in various scenarios and a complex project and the script cache works correctly.

Aside from the last comments I left, there code could get more `const`s for some pointers/Strings, but it's not really important.

File: editor/editor_file_system.cpp (hunk 29 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp]: Done!

File: editor/editor_file_system.cpp (hunk 30 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp:1786]: Done!

File: editor/editor_file_system.cpp [hunk 31]
```diff
@@ -206,17 +207,68 @@ EditorFileSystemDirectory::EditorFileSystemDirectory() {
...
+}
+
+EditorFileSystem::ScannedDirectory::~ScannedDirectory() {
+	for (ScannedDirectory *dir : subdirs) {
+		memdelete(dir);
+	}
+}
+
+void EditorFileSystem::_first_scan_filesystem() {
+	Ref<DirAccess> d = DirAccess::create(DirAccess::ACCESS_RESOURCES);
```
Comment (adamscott) [inline editor/editor_file_system.cpp:226]: We should refrain using single letter variables.

**Comment by adamscott** [comment]
@Hilderin Don't hesitate to come chat in the [developers chat](https://chat.godotengine.org/)! Especially for such a big PR! :)

**Comment by akien-mga** [comment]
I've made some test builds to help validate this PR, in hope that some Godot users could try it out on their projects before we include it in the next 4.3 beta.

I built the editor for Windows, macOS, and Linux, with:
- Current `master` branch (7907ef8) as point of comparison: https://downloads.tuxfamily.org/godotengine/testing/4.3-beta-7907ef8/
- This PR (#92303) rebased on top of 7907ef8: https://downloads.tuxfamily.org/godotengine/testing/4.3-beta-pr92303/

To test and help validate this PR:

- Make a copy of your Godot project(s) you want to test with
- Delete `.godot` folder
- Open the project in the 7907ef8 build, take note of potential errors that may not be present in the version you were using (to be reported separately as general 4.3 bugs). Try usual workarounds like restarting the editor once after the initial import, and check if your game works as intended.
- Close editor
- Delete `.godot` folder
- Open the project in the #92303 build and see if it performs better, using the same steps as with the 7907ef8 build. Ideally there should be a lot less errors about class names not being found, though some may still appear if using addons (this will be tackled later in another PR).

If your project generally works well in current 4.3-beta / 7907ef8, try to use the build from #92303 to do some development work like creating new global classes, renaming some, etc., to find potential bugs.

File: editor/editor_file_system.cpp (hunk 31 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp:226]: I'll fix that as soon as I come back from vacation middle of next week.

**Review by akien-mga — APPROVED** [review]
Did some testing on various projects and it seems to work well for me.

I also got reports from various users testing it and they either saw improvements, or no new issue in their daily workflow, which is also a good sign.

So let's give it a spin and see how it fares in 4.3-beta3.

**Comment by akien-mga** [comment]
Thanks! Amazing work :tada:

**Comment by Hilderin** [comment]
Thanks for your help and support!!

**Comment by donn-xx** [comment]
Sorry for being away. Have just done my first few tests for this fix and it's looking real good. I'll poke at my addon project and keep notes.
