### PR TITLE
[Core] Disconnect one-shot signals before calling callbacks

### LINKED ISSUE #28857: OneShot signal firing twice when retriggered in the signal's own callback
**Godot version:**
3.1.1 (Mono)

**Issue description:**
Under a rather specific scenario, I am able to get a one-shot signal to fire twice. On the second firing it will trigger the following error (presumably from trying to automatically disconnect the one-shot signal, but it's already been disconnected following the first firing).

    E 0:00:01:0299   Nonexistent signal: resized
      <C Source>     core/object.cpp:1533 @ _disconnect()

This behaviour only happens when using a C# version of the script. A functionally equivalent GDScript does not trigger the error.

**Steps to reproduce:**

1. With a base Control node, add a child HBoxContainer
2. Add a number of children to the container with some size. I used ColorRects. The bug seems to require a minimum of at least 2 children, or it will not fire. 
3. Connect to the "resized" signal of the container, with the one-shot flag set.
4. During the receiver for the resized signal, move the container, *and* set a custom separation. Performing just one of these in isolation is not enough to trigger the bug.
5. The resize event will fire again and trigger the error. 

**Minimal reproduction project:**
[Testing-OneShot.zip](https://github.com/godotengine/godot/files/3174155/Testing-OneShot.zip)
Project includes C# and GDScript versions of the same script to show it's C# only.

### LINKED ISSUE #84254: SignalAwaiter acts weirdly if same signal is emited synchronously
### Godot version

v4.1.2.stable.mono.official [399c9dc39]

### System information

Godot v4.1.2.stable.mono - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 2060 SUPER (NVIDIA; 31.0.15.3623) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

Consider code below with two buttons. Click Start button and then Fire button.

I would expect to see these lines in Output panel:
```
Start button clicked
Waiting
Awaited
Re-emitted
```

However, it prints this:
```
Start button clicked
Waiting
Awaited
**Waiting**
Re-emitted
```

Seems like SignalAwaiter callback is called once more even though it has finished waiting and weirdly invokes WaitForAsync once more. Also later an exception is likely to happen.
If I include `await Task.Yield()`, then it works as expected.

```cs
public partial class root : Node2D
{
	[Signal]
	public delegate void TestEventHandler();
	
	void _on_start_button_pressed()
	{
		GD.Print("Start button clicked");
		await WaitForAsync();
	}
	
	async Task WaitForAsync()
	{
		GD.Print("Waiting");
		await ToSignal(this, SignalName.Test);
		GD.Print("Awaited");
		//await Task.Yield();
		EmitSignal(SignalName.Test);
		GD.Print("Re-emitted");
	}
	
	void _on_fire_button_pressed()
	{
		EmitSignal(SignalName.Test);
	}
}
```

### Steps to reproduce

Run attached sample, first click Start button and then Fire.

### Minimal reproduction project

[tosignalpossiblebug.zip](https://github.com/godotengine/godot/files/13218654/tosignalpossiblebug.zip)

### LINKED ISSUE #89439: Errors when firing a signal just after awaiting on that signal
### Tested versions

4.2.stable

### System information

MacOS, M2

### Issue description

Errors are logged when firing a signal just after awaiting on that signal. It seems that the await object is not properly cleaned up and is still partly waiting on the signal.

```
extends Node2D

signal my_signal()

func _ready() -> void:
	await my_signal
	my_signal.emit()

func _process(_delta: float) -> void:
	my_signal.emit()
	set_process(false)
```

gives 

```
E 0:00:00:0589   Node2D.gd:8 @ _ready(): Resumed function '_ready()' after await, but script is gone. At script: res://Node2D.gd:7
  <Erreur C++>   Method/function failed. Returning: Variant()
  <Source C++>   modules/gdscript/gdscript_function.cpp:197 @ resume()
  <Pile des appels>Node2D.gd:8 @ _ready()
                 Node2D.gd:13 @ _process()

E 0:00:00:0589   Node2D.gd:13 @ _process(): Attempt to disconnect a nonexistent connection from 'Node2D:<Node2D#26793215177>'. Signal: 'my_signal', callable: 'GDScriptFunctionState::_signal_callback'.
  <Erreur C++>   Condition "!s->slot_map.has(*p_callable.get_base_comparator())" is true. Returning: false
  <Source C++>   core/object/object.cpp:1420 @ _disconnect()
  <Pile des appels>Node2D.gd:13 @ _process()
```

### Steps to reproduce

Run the project below or the code sample above.

### Minimal reproduction project (MRP)

[await_signal_twice_fired.zip](https://github.com/godotengine/godot/files/14585959/await_signal_twice_fired.zip)

### PR DESCRIPTION
**Pull request by AThousandShips**
Edit: Removed the recursion fix and can add it back in separately if desired, I still think it's an improvement but it makes this easier to merge and cherry-pick, keeping things as simple as possible for this case

This solves the issue, though I'd say some of the handling of `await` needs to be improved, see for example, so some further fixing of that side is likely needed:
* https://github.com/godotengine/godot/issues/79637

---

* Fixes: https://github.com/godotengine/godot/issues/89439
* Fixes #28857
* Fixes #84254

### CODE REVIEW

**Comment by kleonc** [comment]
>Removed the recursion fix

I'd say if anything it should be opened as a separate PR anyway, it seems a separate thing to the disconnecting change.

---

Also if this gets approved as us (just the disconnecting part) then I think we should be careful with cherry-picking it to 4.2, I'd say that's a change which is likely to introduce some regressions we haven't thought about.

---

I'm not sure if the change is safe. It's core-core so I'd say it needs to be assesed by **reduz** anyway, so let's wait for such assesment. :slightly_smiling_face:

**Comment by BimDav** [comment]
Thanks for looking into this!

File: core/object/object.cpp [hunk 1]
```diff
@@ -1163,10 +1163,31 @@ Error Object::emit_signalp(const StringName &p_name, const Variant **p_args, int
 		uint32_t idx = 0;
```
Comment (reduz) [inline core/object/object.cpp:1163]: Just as a note, we should replace this LocalVector<Connection> by an alloca() for performance, so we use the stack for this and not allocate memory every single time signals are emitted, which is very inefficient.

**Review by reduz — CHANGES_REQUESTED** [review]
Left some notes on making the implementation more efficient

File: core/object/object.cpp [hunk 2]
```diff
@@ -1163,10 +1163,31 @@ Error Object::emit_signalp(const StringName &p_name, const Variant **p_args, int
...
+				_ObjectSignalDisconnectData dd;
+				dd.signal = p_name;
+				dd.callable = slot_kv.value.conn.callable;
+				disconnect_data.push_back(dd);
+			}
 		}
 		DEV_ASSERT(idx == s->slot_map.size());
 	}
 
+	while (!disconnect_data.is_empty()) {
```
Comment (reduz) [inline core/object/object.cpp:1184]: Sorry for some reason this comment was erased from the review. I meant that since the for loop below iterates over a copy anyway, there is no need to make the disconnect_data list anyway, could do just simply before calling in the loop below.

**Review by reduz — CHANGES_REQUESTED** [review]

File: core/object/object.cpp (hunk 2 above)
Comment (reduz) [reply core/object/object.cpp:1184]: er could do the erasing, sorry

**Comment by AThousandShips** [comment]
Will update tomorrow, thank you!

File: core/object/object.cpp [hunk 3]
```diff
@@ -1153,78 +1148,74 @@ Error Object::emit_signalp(const StringName &p_name, const Variant **p_args, int
...
-	{
-		uint32_t idx = 0;
-		for (const KeyValue<Callable, SignalData::Slot> &slot_kv : s->slot_map) {
-			slot_conns[idx++] = slot_kv.value.conn;
+	Callable *slot_callables = (Callable *)alloca(sizeof(Callable) * s->slot_map.size());
+	uint32_t *slot_flags = (uint32_t *)alloca(sizeof(uint32_t) * s->slot_map.size());
+	uint32_t slot_count = 0;
+
+	for (const KeyValue<Callable, SignalData::Slot> &slot_kv : s->slot_map) {
+		memnew_placement(&slot_callables[slot_count], Callable(slot_kv.value.conn.callable));
```
Comment (AThousandShips) [inline core/object/object.cpp:1158]: `memnew` is required here to handle the uninitialized memory

File: core/object/object.cpp [hunk 4]
```diff
@@ -1153,78 +1148,74 @@ Error Object::emit_signalp(const StringName &p_name, const Variant **p_args, int
...
 
 	OBJ_DEBUG_LOCK
 
 	Error err = OK;
 
-	for (const Connection &c : slot_conns) {
-		if (!c.callable.is_valid()) {
+	for (uint32_t i = 0; i < slot_count; ++i) {
+		const Callable &callable = slot_callables[i];
+		const uint32_t &flags = slot_flags[i];
```
Comment (AThousandShips) [inline core/object/object.cpp:1185]: Added these for convenience, I ended up changing all the code below anyway as `c` went away but still neater

**Comment by AThousandShips** [comment]
Gonna add a GDScript test for this case and will push after CI has finished

File: core/object/object.cpp (hunk 3 above)
Comment (AThousandShips) [reply core/object/object.cpp:1158]: Gotta fix memory management here

**Comment by kleonc** [comment]
> Gonna add a GDScript test for this case and will push after CI has finished

While at it probably good idea to also add some test specifically for the fixed `await` usage, something like in https://github.com/godotengine/godot/issues/89439#issuecomment-1995097758.

**Comment by AThousandShips** [comment]
Will test out writing one!

File: core/object/object.cpp (hunk 3 above)
Comment (AThousandShips) [reply core/object/object.cpp:1158]: If there's a better way to handle the lifetime here do tell, I don't have an asan setup at the moment so can't test efficiently for leaks

**Review by reduz — APPROVED** [review]
Looks fantastic, great work!

**Comment by AThousandShips** [comment]
Thank you!

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank *you*!
