### PR TITLE
Fix Camera3D `project_*` methods not accounting for frustum offset

### LINKED ISSUE #61174: Camera3D project_* methods not accounting for frustum offset
### Godot version

4.0.dev

### System information

Arch Linux 5.16.14

### Issue description

When using a `Camera3D`'s `project_ray_origin`, `project_ray_normal`, `project_position` and `unproject_position` to translate between world and screen coordinates, if the camera is set to frustum projection, the projected position does not match the screen position.
In this example I set up two viewports, one with a frustum camera and an one with an overview perspective camera for debugging. I had a simple script converting positions from `InputEventMouseButton`s into ray origin and normal, then using a `RayCast3D` to intersect with the scene (the three prisms have static bodies)

The expected result (and the one I got with perspective projection, orthographic projection and frustum projection with no offset) is that the green cylinder (that indicates the world position gotten from the conversion) should point to the box in the back, but instead it points at the wall.

Looking into the source, the error is obvious. None of the methods handles frustum projections, there's just a 
```c++
if (mode == PROJECTION_PERSPECTIVE) {
    // stuff for perspective
} else {
    // stuff for orthographic (and implicitly frustum)
}
```
or
```c++
if (mode == PROJECTION_ORTHOGRAPHIC) {
    // stuff for orthographic
} else {
    // stuff for perspective (and implicitly frustum)
}
```

### Steps to reproduce

Set up a 3D scene with a frustum camera with a non-zero offset. Set up a script that uses a world-space position generated from to screen positions using one of the aforementioned methods. I recommend moving a 3D object to the position gotten from a click, as it's the easiest way to see the difference.

### Minimal reproduction project

Sorry for the messy layout. It's the same project as the screenshot.
Change the settings of the `Camera3D` in `Node3D.tscn` to test that indeed it does work on

[debug_program.zip](https://github.com/godotengine/godot/files/8721829/debug_program.zip)

### PR DESCRIPTION
**Pull request by bcmpinc**
I extracted the duplicated code into a new function `Camera3D::_get_camera_projection(p_near)` and then added support for the `PROJECTION_FRUSTUM` mode. This partially addresses #61174. 

Additionally I added `Camera3D::get_camera_projection()` which returns the Camera's projection matrix, ~~but is currently unused. I think it is useful to expose that method to GDScript as well (currently there's no practical way to get the camera's projection matrix). How would I do that? Should this method be virtual (just like `get_camera_transform()`)?~~ and added GDScript bindings.

I still have to add unit tests, probably merge some of the commits and improve the commit messages. Is there anything else that I need to do for this PR to be accepted?

### CODE REVIEW

**Comment by bcmpinc** [comment]
I noticed it currently only works properly if the camera size is set to 1.

**Comment by bcmpinc** [comment]
So to fix `project_ray_normal` I'd plan to use the projection matrix, as that makes the code a lot easier and work independently of what projection method is used. 

I would like to give `project_ray_origin` the same treatment, however that would change how that method works for perspective. Instead of returning the position of the camera, it would return the point on the near-plane of the camera's frustum. This would be more in line with its documentation though:

> `Vector3 project_ray_origin ( Vector2 screen_point ) const`
> Returns a 3D position in world space, that is the result of projecting a point on the Viewport rectangle by the inverse camera projection. This is useful for casting rays in the form of (origin, normal) for object intersection or picking.

This relates to issue #41872 solving that issue in a different manner.

The documentation of the [ray-tracing tutorial](https://docs.godotengine.org/en/stable/tutorials/physics/ray-casting.html) would also need to be updated.

**Comment by YuriSizov** [comment]
Could you please squash your commits into one? Make sure that the final commit has a short but descriptive message (the title of this PR is a good option). See [this documentation](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase), if you need help with squashing.

**Comment by bcmpinc** [comment]
I've squashed the commits. It fixes the issues with the `project_*` methods, except for `project_ray_normal`.

I'm currently not working on a fix for `project_ray_origin`, so if someone else wants to give that a try then leave a comment here.

**Comment by akien-mga** [comment]
There seems to be two issues remaining:
- The methods should be ordered alphabetically in the XML, so the new `get_camera_projection` should go before `get_camera_rid`.
- The test project we run on CI is crashing when calling `Camera3D.new().get_camera_projection()`.

**Comment by bcmpinc** [comment]
I've added a condition check to ensure that the Camera3D is part of the scene tree. I've moved the documentation entry  in the XML file and added information about it requiring to be part of the scene tree.

File: scene/3d/camera_3d.cpp [hunk 1]
```diff
@@ -170,6 +170,30 @@ Transform3D Camera3D::get_camera_transform() const {
...
+		case PROJECTION_FRUSTUM: {
+			cm.set_frustum(size, viewport_size.aspect(), frustum_offset, p_near, far);
+		} break;
+	}
+
+	return cm;
+}
+
+Projection Camera3D::get_camera_projection() const {
+	ERR_FAIL_COND_V_MSG(!is_inside_tree(), Projection(), "Camera is not inside scene.");
```
Comment (YuriSizov) [inline scene/3d/camera_3d.cpp:193]:
```suggestion
	ERR_FAIL_COND_V_MSG(!is_inside_tree(), Projection(), "Camera is not inside the scene tree.");
```

File: doc/classes/Camera3D.xml [hunk 2]
```diff
@@ -17,6 +17,12 @@
 				If this is the current camera, remove it from being current. If [param enable_next] is [code]true[/code], request to make the next camera current, if any.
 			</description>
 		</method>
+		<method name="get_camera_projection" qualifiers="const">
+			<return type="Projection" />
+			<description>
+				Returns the projection matrix that this camera uses to render to its associated viewport. The camera must be part of the scene tree to funcion.
```
Comment (YuriSizov) [inline doc/classes/Camera3D.xml:23]:
```suggestion
				Returns the projection matrix that this camera uses to render to its associated viewport. The camera must be part of the scene tree to function.
```

**Review by YuriSizov — APPROVED** [review]
Superficially this makes sense and the clean up is nice, but I'm no expert. cc @Calinou @clayjohn

**Comment by Calinou** [comment]
I've tested this PR locally (rebased against `master`) but the original issue with the MRP from https://github.com/godotengine/godot/issues/61174 remains:

image

The red cross denotes my click position, similar to the MRP.

The MRP uses `project_ray_origin()` and `project_ray_normal()` though, so I assume this is expected given the PR's description.

> The expected result (and the one I got with perspective projection, orthographic projection and frustum projection with no offset) is that the green cylinder (that indicates the world position gotten from the conversion) should point to the box in the back, but instead it points at the wall.

**Review by Calinou — APPROVED** [review]

**Comment by YuriSizov** [comment]
> The MRP uses `project_ray_origin()` and `project_ray_normal()` though, so I assume this is expected given the PR's description.

So our recommendation for the author of the issue would be to implement it differently after the fix is merged?

**Comment by clayjohn** [comment]
Taking a look at the code and running locally. The code changes seem fine and appear to be an improvement, however, the problem identified in https://github.com/godotengine/godot/issues/61174 remains and the MRP is not fixed. So there must be an additional change needed somewhere to make this complete.

**Comment by YuriSizov** [comment]
@clayjohn I think this is what Calinou points to?

**Comment by clayjohn** [comment]
> @clayjohn I think this is what Calinou points to?

yep

**Comment by bcmpinc** [comment]
The MRP relies on `project_ray_origin()` and `project_ray_normal()`. I did not feel confident enough to change those without unit tests. However, I ran into a lot of issues trying to get debugging to work and was unable to write those tests.

The projection matrix being exposed does allow a workaround to be written in GDScript though.

**Comment by clayjohn** [comment]
> The MRP relies on `project_ray_origin()` and `project_ray_normal()`. I did not feel confident enough to change those without unit tests. However, I ran into a lot of issues trying to get debugging to work and was unable to write those tests.
> 
> The projection matrix being exposed does allow a workaround to be written in GDScript though.

Thanks for the clarification. That makes sense. I was a bit confused because `project_ray_normal()` is fixed somewhat by switching to using ``set_frustum()`` instead of always ``set_perspective()`` but it seems that isn't enough to fix the MRP. 

What sort of issues were you running into? Maybe we can help you get unit tests working so you can take the next step in fixing the MRP. If you aren't interested in taking this further, that is also understandable. I think we can go ahead and merge as is without closing the original bug report.

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.1.
