### PR TITLE
Fix vertical scroll/zoom for precision touchpad on windows

### LINKED ISSUE #51313: Vertical scroll/zoom erratic with precision touchpad on Windows
### Godot version

master

### System information

Windows 10

### Issue description

Vertical scrolling and zooming in various views and lists in the editor is unusable with a precision touchpad on Windows, lists instantly scroll to the end without much touch input, zooming in 2D/3D views allow no fine control.

This issue is present in stable and master on Windows.

 

### Steps to reproduce

Scroll/zoom vertically on a precision touchpad

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by georgwacker**
This fix adds the factor data for the vertical mousewheel event, much like the horizontal mousewheel event, where this is already present.

With this fix, vertical scroll/zoom with a precision touchpad on windows is smooth and allows for fine grain control.
The code to support precision touchpad input is already present, but not used correctly.

Mousewheel events for other devices are not affected and are functioning as expected (tested with regular mouse).

It would be great if this could be cherrypicked for stable.

Fixes #51313

### CODE REVIEW

File: platform/windows/display_server_windows.cpp [hunk 1]
```diff
@@ -2442,8 +2442,10 @@ LRESULT DisplayServerWindows::WndProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARA
 
 					if (motion > 0) {
 						mb->set_button_index(MOUSE_BUTTON_WHEEL_UP);
+						mb->set_factor(fabs((double)motion / (double)WHEEL_DELTA));
 					} else {
 						mb->set_button_index(MOUSE_BUTTON_WHEEL_DOWN);
+						mb->set_factor(fabs((double)motion / (double)WHEEL_DELTA));
```
Comment (akien-mga) [inline platform/windows/display_server_windows.cpp:2448]: If it's the same call for both branches, it can go outside the `if`.

Comment (georgwacker) [reply platform/windows/display_server_windows.cpp]: Right, I cleaned up the code for the horizontal mousewheel event as well now. Do I need to squash the commits?

Comment (akien-mga) [reply platform/windows/display_server_windows.cpp]: Yes, please do.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.3.
