### PR TITLE
Fix discarded input event metadata in `xformed_by`

### LINKED ISSUE #95205: Event metadata is missing in `_input()` when events are passed through `Input.parse_input_event()`
### Tested versions

v4.3.rc2.official [3978628c6]

### System information

Ubuntu 20.04 LTS

### Issue description

See title.

### Steps to reproduce

Create a node, attach the following script, and run
``` gdscript
func _ready():  
  var test = InputEventMouseButton.new()
  test.set_meta("test", 123)
  Input.parse_input_event(test)

func _input(event: InputEvent):
  if event is InputEventMouseButton:
    print(event.get_meta("test", "(nothing)"))
```

Output:
```
(nothing)
```

**Note**
This occurs due to the event being cloned with `xformed_by()` (like [here](https://github.com/godotengine/godot/blob/master/scene/main/viewport.cpp#L1328) and [here](https://github.com/godotengine/godot/blob/master/scene/main/viewport.cpp#L1760)), but `xformed_by()` does not copy the metadata.
Some overrides of `xformed_by` [copy the pointer](https://github.com/godotengine/godot/blob/master/core/input/input_event.cpp#L94) (this is technically a bug, since it looks like callers expect a new instance), while others do a copy but forget to copy the metadata, like [InputEventMouseButton::xformed_by](https://github.com/godotengine/godot/blob/master/core/input/input_event.cpp#L736)

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by yelloweennnn**
This pull request fixes an issue where event metadata is lost when events are passed through `Input.parse_input_event()` due to the way `xformed_by()` handles clones.

- Modified `input_event.cpp` and `input_event.h` to implement a function that copies metadata.
- Ensured that metadata is correctly copied when passed through the `xformed_by()` overrides.

The changes were tested by following the reproduction steps provided in the issue, ensuring that each `xformed_by()` override properly preserves the event metadata.

Fixes #95205

### CODE REVIEW

File: core/input/input_event.cpp [hunk 1]
```diff
@@ -107,6 +107,17 @@ bool InputEvent::is_action_type() const {
 	return false;
 }
 
+void InputEvent::copy_metadata(const Ref<InputEvent> &target) const {
```
Comment (Sauermann) [inline core/input/input_event.cpp:110]: Can you please check, if you could reuse `Object::merge_meta_from`?

https://github.com/godotengine/godot/blob/1f47e4c4e3a09a422e96880a7918d986dd575a63/core/object/object.cpp#L1028-L1034

**Comment by Sauermann** [comment]
Looks good to me. The final step before the PR can be merged is to squash all the commits together so that the whole PR only contains 1 big commit with all your changes. We like to merge one commit at a time to keep the git history clean and navigable. 

If you don't know how to do that, we have a helpful tutorial in the official documentation https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase

**Review by Sauermann — APPROVED** [review]
I have tested the implementation and can confirm that it resolves the bug for mouse button input events.
The code looks correct.

File: core/input/input_event.cpp [hunk 2]
```diff
@@ -32,6 +32,7 @@
 
 #include "core/input/input_map.h"
 #include "core/input/shortcut.h"
+#include "core/object/object.h"
```
Comment (AThousandShips) [inline core/input/input_event.cpp:35]:
```suggestion
```
Unnecessary

**Review by Alexizx00789999 — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉

**Comment by Sauermann** [comment]
Deleting the branch can be seen as good practice in order to keep your repository clean, so yes, go ahead.

**Comment by Yelloween10** [comment]
I tried using `git branch -d fix-input-event-metadata`, and it gave me this error:
`the branch 'fix-input-event-metadata' is not fully merged`
I checked `git branch --merged` and my branch isn't listed.
Would it be safe to use -D?

**Comment by Sauermann** [comment]
@Yelloween10 
This message indicates, that in your local copy of the git-repository, your PR is not yet included in the master branch.

I get this message, when I forget to update my local master branch. You could update your local master branch and fetch the most recent master-branch from github. Afterwards deleting the branch with "-d" no longer gives that error.

As you mentioned, an alternative would be to use "-D" to force the removal of your local "fix-input-event-metadata" branch. Since your PR is already merged in master, I don't see any negative effects. When one of my PRs is discarded without getting merged, I use "-D" to delete it locally.

The local repository also contains a remote branch (for example recently I had "my-remote/fix-mouse-over-viewport-in-texturerect").
I delete that one too with "git branch -dr my-remote/fix-mouse-over-viewport-in-texturerect"
