### PR TITLE
Fix resource shared when duplicating an instanced scene

### LINKED ISSUE #45350: resource_local_to_scene copies the reference when you duplicate an instance.
**Godot version:**
3.2.3

**OS/device including version:**
Windows 10

**Issue description:**
If you get a resource, add it to a scene and set resource_local_to_scene to true, you should be able to instance it in a scene however you want and edit that resource separately for each instance. This works when you use the instance button in the editor but not when you duplicate a node.

**Steps to reproduce:**
Add a resource to a scene and set resource_local_to_scene to true.
Instance that scene in another scene.
Set a value, it should be different than in the original scene.
Duplicate it the instanced scene.
They share the same resource instead of using a new unique one for themselves.

### LINKED ISSUE #47918: ViewportTexture in duplicated instanced scene still refer to old viewport
**Godot version:** 3.2.3 / 3.3 RC9

**OS/device including version:** macOS 11.2.3 (not graphics-related)

**Issue description:**

I have a scene that contains a `Viewport` and a `Sprite`. The `Sprite` uses a `ViewportTexture` that references the viewport.

tree

The scene is instanced in another scene. After the instanced scene is duplicated (CTRL-D), both the `ViewportTexture`s show the content of the original viewport (the one inside first `Scene` node). They correctly refer to their own viewport after reopening the `Main` scene.

instanced

Setting up `ViewportTexture` on current master (c7a4e21) generates a `Condition "proxy.is_valid()" is true` error, and the `ViewportTexture` is all black. So I failed to test this on it.

**Steps to reproduce:**

1. Open the `Main.tscn` in MRP
    * There is a red godot icon in the scene
2. Duplicate the node called `Scene`, and move the node down
    * Now, there are two red godot icons
3. Change the `Color` script variable of `Scene2` to white via the inspector.
    * Nothing changes, both the icons are red
4. Change the `Color` script variable of `Scene` to green via the inspector.
    * Both the icons become green
 5. Save & close the scene, then reopen it
    * The color of icons are correct: `Scene` is green, and `Scene2` is white

**Minimal reproduction project:** [ViewportTexture.zip](https://github.com/godotengine/godot/files/6317675/ViewportTexture.zip)

### PR DESCRIPTION
**Pull request by Rindbee**
Fix #45350, fix #47918.
Depends on #65011.

For resources with `resource_local_to_scene` enabled in the subscene, the resource is already set when the subscene is instantiated, so does not need to be set again.

### CODE REVIEW

File: scene/main/node.cpp [hunk 1]
```diff
@@ -2193,10 +2196,22 @@ Node *Node::_duplicate(int p_flags, HashMap<const Node *, Node *> *r_duplimap) c
...
+					HashMap<Ref<Resource>, Ref<Resource>> tmp;
+					current_res->configure_for_local_scene(node, tmp);
+					current_res->setup_local_to_scene();
+					continue;
+				}
+				if (E.usage & PROPERTY_USAGE_DO_NOT_SHARE_ON_DUPLICATE) {
 					current_node->set(name, res->duplicate());
+				} else {
+					current_node->set(name, value);
 				}
```
Comment (RandomShaper) [inline scene/main/node.cpp:2215]:
```suggestion
				} else {
					if (E.usage & PROPERTY_USAGE_DO_NOT_SHARE_ON_DUPLICATE) {
						current_node->set(name, res->duplicate());
					} else {
						current_node->set(name, value);
					}
				}
```

**Review by RandomShaper — CHANGES_REQUESTED** [review]
Looks good. There's just the comment about structure to improve readability.

**Review by RandomShaper — APPROVED** [review]

**Comment by Rindbee** [comment]
There is also a similar situation here https://github.com/godotengine/godot/pull/64999#issuecomment-1229569123

File: scene/main/node.cpp [hunk 2]
```diff
@@ -2193,16 +2197,43 @@ Node *Node::_duplicate(int p_flags, HashMap<const Node *, Node *> *r_duplimap) c
...
+					// Find the shared copy of the source resource.
+					HashMap<Ref<Resource>, Ref<Resource>>::Iterator R = resources_local_to_sub_scene.find(res);
+					if (R) {
+						current_node->set(name, R->value);
+					} else {
+						Ref<Resource> current_res = current_node->get(name);
+						if (current_res.is_valid() && current_res->is_local_to_scene()) {
+							// For local-to-scene resources in sub-scene, the old instance needs to be preserved to
+							// prevent sharing from being broken. Just update it with the data from the source resource.
+							current_res->copy_from(res, resources_local_to_sub_scene, true);
```
Comment (Rindbee) [inline scene/main/node.cpp:2212]: The modified `copy_from` in #65011 is used here

**Comment by akien-mga** [comment]
The build seems to fail.

**Comment by Rindbee** [comment]
Yes, here uses the `copy_from` after the modified in #65011.

**Comment by RandomShaper** [comment]
@Rindbee, you may want to rebase this PR on top of the other one this depends on so CI build passes. When the other one is merged, this one will get automatically trimmed down to the only additional commit.

**Comment by Rindbee** [comment]
I think there are fewer records about the correlation between resources between tscn.

All the related (merged and not yet merged) PRs are based on a judgment: Resources with local-to-scene enabled on the same property of the same object that recorded in the main scene, is  a copy of the source resource which recorded in the sub-scene. 

In most cases, this may be correct. But in fact, this situation cannot be ruled out: Really hope to use new resources to cover the resources on the scene.

File: core/io/resource.cpp [hunk 3]
```diff
@@ -181,8 +181,39 @@ Error Resource::copy_from(const Ref<Resource> &p_resource) {
...
+				if (R) {
+					value = R->value;
+				} else {
+					Ref<Resource> sub_res = get(E.name);
+					if (sub_res.is_valid() && sub_res->is_local_to_scene()) {
+						// Simply copy the data from the source resource to update the resource that was previously set.
+						sub_res->copy_from(sub_res_of_from, p_remap_cache, true);
+						p_remap_cache[sub_res_of_from] = sub_res;
+						value = sub_res;
+					} else { // A copy of the source resource is required to overwrite the previous one
```
Comment (AThousandShips) [inline core/io/resource.cpp:202]:
```suggestion
					} else { // A copy of the source resource is required to overwrite the previous one.
```
Code style nitpick, same elsewhere

File: scene/main/node.cpp [hunk 4]
```diff
@@ -2513,14 +2517,36 @@ Node *Node::_duplicate(int p_flags, HashMap<const Node *, Node *> *r_duplimap) c
...
+						} else { // A copy of the source resource is required to overwrite the previous one.
+							Ref<Resource> dupe = res->duplicate_for_local_scene(node, resources_local_to_sub_scene);
+							resources_local_to_sub_scene[res] = dupe;
+							value = dupe;
+						}
+					}
+				} else if (E.usage & PROPERTY_USAGE_ALWAYS_DUPLICATE) {
+					value = res->duplicate();
 				}
+			}
```
Comment (KoBeWi) [inline scene/main/node.cpp:2543]: It's the third time you are writing this code (first two were in #64487). Can it be moved to some method?

File: core/io/resource.h [hunk 5]
```diff
@@ -81,13 +81,14 @@ class Resource : public RefCounted {
...
-	static void (*_update_configuration_warning)(); //used by editor
+	static Node *(*_get_local_scene_func)(); //Used by editor.
+	static void (*_update_configuration_warning)(); //Used by editor.
 
 	void update_configuration_warning();
 	virtual bool editor_can_reload_from_file();
-	virtual void reset_state(); //for resources that use variable amount of properties, either via _validate_property or _get_property_list, this function needs to be implemented to correctly clear state
-	virtual Error copy_from(const Ref<Resource> &p_resource);
+	virtual void reset_state(); //For resources that use variable amount of properties, either via _validate_property or _get_property_list, this function needs to be implemented to correctly clear state.
+	static Ref<Resource> get_remap_resource(const Ref<Resource> &p_resource, HashMap<Ref<Resource>, Ref<Resource>> p_remap_cache, const Ref<Resource> p_fallback, Node *p_for_scene);
```
Comment (KoBeWi) [inline core/io/resource.h:90]: This method shouldn't be mixed in here. You could put it under the static methods above.

**Review by KoBeWi — APPROVED** [review]

**Comment by YuriSizov** [comment]
Your PR currently contains 2 commits with the same description.

**Comment by KoBeWi** [comment]
#65011 should be merged first as this PR builds on top.

**Comment by YuriSizov** [comment]
Yes, but the second commit here is still wrong 🙃

File: core/io/resource.h [hunk 6]
```diff
@@ -81,13 +81,14 @@ class Resource : public RefCounted {
...
+	static Node *(*_get_local_scene_func)(); //Used by editor.
+	static void (*_update_configuration_warning)(); //Used by editor.
+	static Ref<Resource> get_remap_resource(const Ref<Resource> &p_resource, HashMap<Ref<Resource>, Ref<Resource>> &remap_cache, const Ref<Resource> &p_fallback, Node *p_for_scene);
 
 	void update_configuration_warning();
 	virtual bool editor_can_reload_from_file();
-	virtual void reset_state(); //for resources that use variable amount of properties, either via _validate_property or _get_property_list, this function needs to be implemented to correctly clear state
-	virtual Error copy_from(const Ref<Resource> &p_resource);
+	virtual void reset_state(); //For resources that use variable amount of properties, either via _validate_property or _get_property_list, this function needs to be implemented to correctly clear state.
+	virtual Error copy_from(const Ref<Resource> &p_resource, HashMap<Ref<Resource>, Ref<Resource>> &remap_cache, bool p_keep_local_to_scene_resource_instance = false);
```
Comment (reduz) [inline core/io/resource.h:91]: I would honestly make a different function like `copy_from_with_remap` or something like this, so other places that don't need to use this logic don't  get the code polluted unnecesarily. In fact, if this is only used in packed_scene, I would just make this a local function of packed_scene.

**Review by reduz — CHANGES_REQUESTED** [review]

File: core/io/resource.h [hunk 7]
```diff
@@ -81,13 +81,14 @@ class Resource : public RefCounted {
...
-	static void (*_update_configuration_warning)(); //used by editor
+	static Node *(*_get_local_scene_func)(); //Used by editor.
+	static void (*_update_configuration_warning)(); //Used by editor.
+	static Ref<Resource> get_remap_resource(const Ref<Resource> &p_resource, HashMap<Ref<Resource>, Ref<Resource>> &remap_cache, const Ref<Resource> &p_fallback, Node *p_for_scene);
 
 	void update_configuration_warning();
 	virtual bool editor_can_reload_from_file();
-	virtual void reset_state(); //for resources that use variable amount of properties, either via _validate_property or _get_property_list, this function needs to be implemented to correctly clear state
-	virtual Error copy_from(const Ref<Resource> &p_resource);
+	virtual void reset_state(); //For resources that use variable amount of properties, either via _validate_property or _get_property_list, this function needs to be implemented to correctly clear state.
```
Comment (AThousandShips) [inline core/io/resource.h:90]:
```suggestion
	virtual void reset_state(); // For resources that use variable amount of properties, either via _validate_property or _get_property_list, this function needs to be implemented to correctly clear state.
```

File: core/io/resource.h [hunk 8]
```diff
@@ -81,13 +81,14 @@ class Resource : public RefCounted {
 	void _take_over_path(const String &p_path);
 
 public:
-	static Node *(*_get_local_scene_func)(); //used by editor
-	static void (*_update_configuration_warning)(); //used by editor
+	static Node *(*_get_local_scene_func)(); //Used by editor.
+	static void (*_update_configuration_warning)(); //Used by editor.
```
Comment (AThousandShips) [inline core/io/resource.h:85]:
```suggestion
	static void (*_update_configuration_warning)(); // Used by editor.
```

File: core/io/resource.h [hunk 9]
```diff
@@ -81,13 +81,14 @@ class Resource : public RefCounted {
 	void _take_over_path(const String &p_path);
 
 public:
-	static Node *(*_get_local_scene_func)(); //used by editor
-	static void (*_update_configuration_warning)(); //used by editor
+	static Node *(*_get_local_scene_func)(); //Used by editor.
```
Comment (AThousandShips) [inline core/io/resource.h:84]:
```suggestion
	static Node *(*_get_local_scene_func)(); // Used by editor.
```

File: scene/main/node.cpp [hunk 10]
```diff
@@ -2498,6 +2498,9 @@ Node *Node::_duplicate(int p_flags, HashMap<const Node *, Node *> *r_duplimap) c
 
 	for (List<const Node *>::Element *N = node_tree.front(); N; N = N->next()) {
 		Node *current_node = node->get_node(get_path_to(N->get()));
+		if (instantiated && node != current_node) {
```
Comment (reduz) [inline scene/main/node.cpp:2501]: This should only be the case if the scene has editable children disabled. If enabled, you need to do property duplication in the children.

**Review by reduz — COMMENTED** [review]
Looks OK overall, but make sure to check the comment I left.

**Comment by reduz** [comment]
Sorry, I misunderstood the PR, as this is only the change in node. In this case, Its as I mentioned, you have to duplicate the children nodes manually if they have editable children flag set.

File: scene/main/node.cpp (hunk 10 above)
Comment (Rindbee) [reply scene/main/node.cpp]: This case was indeed missed before.

**Comment by Rindbee** [comment]
Okay, the cases of enabling/disabling **Editable Children** has been completed for scene initialization and node duplication. I think it's ready to be reviewed again.

**Comment by Rindbee** [comment]
`Node::_duplicate()` does not seem to be a suitable place to remap resources. It seems more appropriate to modify the mapping logic in `SceneTreeDock::paste_nodes()`.

I'll try to modify the mapping logic there later.

File: scene/resources/packed_scene.cpp [hunk 11]
```diff
@@ -78,18 +78,28 @@ static Array _sanitize_node_pinned_properties(Node *p_node) {
...
-	HashMap<Ref<Resource>, Ref<Resource>>::Iterator R = remap_cache.find(p_resource);
+	HashMap<Ref<Resource>, Ref<Resource>>::Iterator R = remap_cache[p_for_scene].find(p_resource);
 	if (R) {
-		remap_resource = R->value;
-	} else if (p_fallback.is_valid() && p_fallback->is_local_to_scene() && p_fallback->get_class() == p_resource->get_class()) {
-		// Simply copy the data from the source resource to update the fallback resource that was previously set.
+		return R->value;
+	}
+
+	bool reuse_fallback = p_fallback.is_valid() && p_fallback->is_local_to_scene() && p_fallback->get_class() == p_resource->get_class();
```
Comment (KoBeWi) [inline scene/resources/packed_scene.cpp]:
```suggestion
	bool reuse_fallback = p_fallback.is_valid() && p_fallback->is_local_to_scene() && p_fallback->get_class_name() == p_resource->get_class_name();
```
Returns StringName instead of String.

**Review by KoBeWi — APPROVED** [review]
Gave it some testing and it seems to work correctly.

Might need core re-review after latest changes.

File: editor/docks/scene_tree_dock.cpp [hunk 12]
```diff
@@ -956,6 +958,14 @@ void SceneTreeDock::_tool_selected(int p_tool, bool p_confirm_override) {
 
 			undo_redo->commit_action();
 
+			for (KeyValue<Node *, HashMap<Ref<Resource>, Ref<Resource>>> &KV : resources_local_to_scenes) {
+				for (KeyValue<Ref<Resource>, Ref<Resource>> &R : KV.value) {
+					if (R.value->is_local_to_scene()) {
+						R.value->setup_local_to_scene();
+					}
+				}
+			}
```
Comment (Rindbee) [inline editor/docks/scene_tree_dock.cpp:967]: This ensures that local-to-scene resources in newly copied child scene instances are effective when **Editable Children** is enabled.

The cache is now only cleared only when a new copy begins. As users edit the scene, it may lead to the use of released node instances as keys.

**Comment by Repiteo** [comment]
Thanks!
