### PR TITLE
Inline edit for FileSystem dock in SPLIT_MODE

### LINKED ISSUE #77527: Cannot rename items in the FileSystem dock
### Godot version

v4.1.dev3.official [a67d37f7c]

### System information

Windows 10 64-bit

### Issue description

When trying to rename anything (a scene, script, folder, etc) instead of selecting the item itself, it highlights the current folder in the FileSystem tab instead.

Upon pressing enter or confirm the name change a Warning dialogue appears with the following text:

> This file extension is not recognized by the editor.
If you want to rename it anyway, use your operating system's file manager.
After renaming to an unknown extension, the file won't be shown in the editor anymore.

If no new text is entered, the warning box instead states

> Name contains invalid characters.

Upon pressing Ok, the folder name in the FileSystem tab is visually changed to match the name of the item you attempted to rename (regardless of the entered text) including the extension if any. The folder name remains the same in the file system, but visually in the editor it is the name of the item.
In the output log, there is a message
> scene/main/viewport.cpp:3005 - Condition "!is_inside_tree()" is true.

sample

### Steps to reproduce

1. Create or open a project
2. Rename any item (scene, script, folder, etc) by right clicking or pressing F2 (or corresponding shortcut for rename)

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Wiwip**
Permits the renaming of files and folders inline for items in the FileSystemDock.

This is a continuation of: https://github.com/godotengine/godot/pull/76794 which didn't consider DISPLAY_MODE_SPLIT.
Fixes: https://github.com/godotengine/godot/issues/77527 and https://github.com/godotengine/godot-proposals/issues/4933.

*Bugsquad edit:* Supersedes #77589

### CODE REVIEW

**Comment by Wiwip** [comment]
I have chosen to use the class FileSystemList : public ItemList { } instead of modifying the ItemList class. FileSystemList already exists and ItemList is used everywhere. The way the item is edited mirrors the Tree class edit_Selected(bool) for string items.

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -76,6 +76,99 @@ Control *FileSystemList::make_custom_tooltip(const String &p_text) const {
...
+	popup_editor->add_child(popup_editor_vb);
+
+	line_editor = memnew(LineEdit);
+	line_editor->set_v_size_flags(SIZE_EXPAND_FILL);
+	popup_editor_vb->add_child(line_editor);
+	line_editor->connect("text_submitted", callable_mp(this, &FileSystemList::_line_editor_submit));
+	popup_editor->connect("popup_hide", callable_mp(this, &FileSystemList::_text_editor_popup_modal_close));
+}
+
+FileSystemList::~FileSystemList() {
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:169]: No need for empty destructor.

File: editor/filesystem_dock.h [hunk 2]
```diff
@@ -57,7 +57,24 @@ class FileSystemTree : public Tree {
 };
 
 class FileSystemList : public ItemList {
-	virtual Control *make_custom_tooltip(const String &p_text) const;
+	GDCLASS(FileSystemList, ItemList);
+	VBoxContainer *popup_editor_vb = nullptr;
```
Comment (KoBeWi) [inline editor/filesystem_dock.h:61]:
```suggestion
	GDCLASS(FileSystemList, ItemList);

	VBoxContainer *popup_editor_vb = nullptr;
	
```

File: editor/filesystem_dock.h [hunk 3]
```diff
@@ -193,7 +210,6 @@ class FileSystemDock : public VBoxContainer {
 	Vector<FileOrFolder> to_move;
 	String to_move_path;
 	bool to_move_or_copy = false;
-
```
Comment (KoBeWi) [inline editor/filesystem_dock.h:196]: Why remove.

File: editor/filesystem_dock.cpp [hunk 4]
```diff
@@ -76,6 +76,99 @@ Control *FileSystemList::make_custom_tooltip(const String &p_text) const {
...
+void FileSystemList::_line_editor_submit(String p_text) {
+	popup_editor->hide();
+
+	emit_signal(SNAME("item_edited"));
+	queue_redraw();
+}
+
+bool FileSystemList::edit_selected() {
+	int s = get_current();
+	ERR_FAIL_COND_V_MSG(!is_anything_selected(), false, "No item selected.");
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:88]: Unless there is some reason not to, the error check should be at the top.

File: editor/filesystem_dock.cpp [hunk 5]
```diff
@@ -76,6 +76,99 @@ Control *FileSystemList::make_custom_tooltip(const String &p_text) const {
...
+	ensure_current_is_visible();
+
+	Rect2 rect;
+	Rect2 popup_rect;
+	Vector2 ofs;
+
+	int icon_width = get_item_icon(s)->get_width();
+	int icon_height = get_item_icon(s)->get_height();
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:96]: Can be replaced with
```suggestion
	Vector2 icon_size = get_item_icon(s)->get_size();
```

**Review by KoBeWi — APPROVED** [review]
The implementation looks alright and it works from my testing.
I left some comments that should be addressed.

File: editor/filesystem_dock.h (hunk 3 above)
Comment (Wiwip) [reply editor/filesystem_dock.h:196]: No reasons, reverting the change.

**Comment by Wiwip** [comment]
I have made the changes and pushed the updated version.

File: editor/filesystem_dock.h (hunk 2 above)
Comment (KoBeWi) [reply editor/filesystem_dock.h]: Sorry I didn't notice there is an extra line in my suggestion. I edited it .-.

File: editor/filesystem_dock.cpp [hunk 6]
```diff
@@ -76,6 +76,94 @@ Control *FileSystemList::make_custom_tooltip(const String &p_text) const {
...
+	_line_editor_submit(line_editor->get_text());
+}
+
+void FileSystemList::_bind_methods() {
+	ADD_SIGNAL(MethodInfo("item_edited"));
+}
+
+FileSystemList::FileSystemList() {
+	popup_editor = memnew(Popup);
+	add_child(popup_editor, false);
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:153]:
```suggestion
	add_child(popup_editor);
```

**Comment by akien-mga** [comment]
Thanks!
