### PR TITLE
Fix unexpected behaviors of using Duplicate To on folders

### LINKED ISSUE #81436: Using Duplicate To for folders in the filesystem dock may cause unexpected behavior
### Godot version

v4.2.dev4.official [549fcce5f]

### System information

Godot v4.2.dev4 - Linux Mint 21.2 (Victoria) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (nvidia; 535.86.05) - Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 Threads)

### Issue description

Select a folder A in the FileSystem dock, right-click to open the context menu, select **Move/Duplicate To...**, select another folder B in the popup dialog, and check **Copy File(s)** , click the **Copy** button to copy:
1. if A is an empty directory, duplication has no effect.
2. If B already contains A, trying the **Keep Both** option will result in a path like `B/A (2)/A/`.

https://github.com/godotengine/godot/assets/30386067/06514c43-8806-4d3c-b10f-206fd9a2f843

The second case above also applies to Move To.

https://github.com/godotengine/godot/assets/30386067/f7a86a92-8144-4b59-ab21-846d3938c08d

### Steps to reproduce

See above.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Rindbee**
Fix folder not being copied when empty.
Fix Keep Both would generate wrong paths when copying folders.

Fix #81436.

### CODE REVIEW

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -1890,22 +1892,15 @@ void FileSystemDock::_move_operation_confirm(const String &p_to_path, bool p_cop
 		if (p_overwrite == OVERWRITE_RENAME) {
 			new_paths.write[i] = _get_unique_name(to_move[i], p_to_path);
 		} else {
-			new_paths.write[i] = p_to_path.path_join(to_move[i].path.get_file());
+			new_paths.write[i] = p_to_path.path_join(to_move[i].is_file ? to_move[i].path.get_file() : to_move[i].path.left(-1).get_file());
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:1895]:
```suggestion
			new_paths.write[i] = p_to_path.path_join(to_move[i].to_move[i].trim_suffix("/").get_file());
```
Simpler and does the same.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
