### PR TITLE
Fix removing a folder that contains a file is not removed from the FileSystem Dock

### LINKED ISSUE #93097: Editor shows non-existent folders based on dependencies
### Tested versions

4.3 beta1
Did not test other versions.

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

This is shown in the editor:
image
While the project's contents are:
image
One of the scenes has missing dependencies and Godot tries to satisfy them by hallucinating non-existent folders, or something.
Sometimes the fake folder turns into duplicate:
image

### Steps to reproduce

Just open the MRP

### Minimal reproduction project (MRP)

[godotai.zip](https://github.com/user-attachments/files/15810070/godotai.zip)

### LINKED ISSUE #94431: Removing a folder that contains a file is not removed from the FileSystem Dock
### Tested versions

- Reproducible in 4.3.beta.mono (97b8ad1af)
- Reproducible in 4.3 beta 3
- Not reproducible in 4.3 beta 2
- Not reproducible in 4.3 beta 1
- Not reproducible in 4.2.1

### System information

Godot v4.3.beta3 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3742) - 11th Gen Intel(R) Core(TM) i5-11600KF @ 3.90GHz (12 Threads)

### Issue description

When deleting a folder using the FileSystem Dock, if the folder contains a file, everything is deleted on the disk, but in the FileSystem in the editor, onyl the file disappear. I need to restart the editor for the folder to disappear.

### Steps to reproduce

- Create a folder
- Create a scene in it
- Delete the folder in Godot

### Minimal reproduction project (MRP)

Any project.

### PR DESCRIPTION
**Pull request by Hilderin**
- Fixes #94431
- Fixes #93097

The issue is a side-effect from #92303. To be able to manage correctly the removing of scripts with global class names, I added all removed files in `scan_actions` with the action `ACTION_FILE_REMOVE`. But in `_update_scene_groups` or `_update_script_documentation` the method `find_file` is called, which calls `_find_file`. The method `_find_file` recreates the parent folder of the searched file if it does not exist in `filesystem`.

I added a check to prevent adding a folder in `filesystem` that does not exist on the disk.

### CODE REVIEW

File: editor/editor_file_system.cpp [hunk 1]
```diff
@@ -1594,7 +1594,10 @@ bool EditorFileSystem::_find_file(const String &p_file, EditorFileSystemDirector
 		}
 
 		if (idx == -1) {
-			//does not exist, create i guess?
+			// Only create a the missing directory in memory when it exists on disk.
```
Comment (AThousandShips) [inline editor/editor_file_system.cpp:1597]:
```suggestion
			// Only create a missing directory in memory when it exists on disk.
```

**Review by AThousandShips — APPROVED** [review]
LGTM

**Comment by KoBeWi** [comment]
Might also fix #93097

**Comment by Hilderin** [comment]
I confirm, I tested the MRP from #93097 before an after the fix and this PR solves #93097 also.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
