### PR TITLE
Correctly register editor-only `OpenXR*` classes' `api_type`

### LINKED ISSUE #103867: GDExtension: editor-only `OpenXR*` classes declared with `api_type == "core"`
### Tested versions

4.4-dev, b5bdb88062a31a982c8f3bf4b820188edd53c6c5
against 4.4 GDExtension API

### System information

Linux

### Issue description

In GDExtension, the following classes are advertised with `api_type == "core"`:
- `OpenXRInteractionProfileEditorBase`
- `OpenXRBindingModifierEditor`
- `OpenXRInteractionProfileEditor`

The problem is, these classes are only available in the editor, not in release/export builds. So trying to access them in an exported project fails at runtime.

Same issue as https://github.com/godotengine/godot/issues/86206.

---

I think the `api_type` should be set to `"editor"` instead, like it is the case with other editor-only classes.

It looks like those are registered here. I'm not sure if there's a reason this happens in that file and not in [register_editor_types.cpp](https://github.com/godotengine/godot/blob/master/editor/register_editor_types.cpp):
https://github.com/godotengine/godot/blob/b5bdb88062a31a982c8f3bf4b820188edd53c6c5/modules/openxr/register_types.cpp#L227-L233

### Steps to reproduce

Access one of the mentioned classes in an extension running under a Godot release build.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Bromeon**
Fixes https://github.com/godotengine/godot/issues/103867, by registering the three following classes with `api_type = "editor"` instead of `"core"`:

- `OpenXRInteractionProfileEditorBase`
- `OpenXRBindingModifierEditor`
- `OpenXRInteractionProfileEditor`

Follows the same approach as https://github.com/godotengine/godot/pull/86209.

### CODE REVIEW

**Comment by AJ213** [comment]
Hi, would just like to also mention that this is a very important bug in 4.4 stable. I am lucky that I am in the godot-rust community and they are amazing and fixed the issue via a workaround, but before that I was unable to export my game. I would almost consider this a regression as I was fully capable of exporting my godot-rust project prior to 4.4 stable. This pull request would fix that.

Besides exporting projects to release on Steam/Itch.io, exporting projects is also used to do profiling analysis which is important for GDExtension as Godot does not support profiling other languages.

**Review by akien-mga — APPROVED** [review]

**Comment by AJ213** [comment]
> Can you clarify how this issue impacts exporting your game? I would expect that as long as you don't use those classes, they "wrong" API type shouldn't impact the rest of the API?

The error will occur even if I don't use the wrong APIs. I do not use OpenXR or anything like that. The project itself will export, but none of my classes will load due to an error relating to these OpenXR classes. I had this issue occur in my project on Windows and Linux, and in Godot-Rust we have replicated it with just a basic "spinning godot icon" sample project https://github.com/godot-rust/gdext/issues/1067

File: modules/openxr/register_types.cpp [hunk 1]
```diff
@@ -225,10 +225,16 @@ void initialize_openxr_module(ModuleInitializationLevel p_level) {
...
+		// Register as "editor", not "core".
+		ClassDB::APIType prev_api = ClassDB::get_current_api();
+		ClassDB::set_current_api(ClassDB::API_EDITOR);
+
 		GDREGISTER_ABSTRACT_CLASS(OpenXRInteractionProfileEditorBase);
 		GDREGISTER_CLASS(OpenXRInteractionProfileEditor);
 		GDREGISTER_CLASS(OpenXRBindingModifierEditor);
 
+		ClassDB::set_current_api(prev_api);
+
```
Comment (dsnopek) [inline modules/openxr/register_types.cpp:237]: Why mess with `ClassDB::set_current_api()` rather than putting this stuff in a new `if (p_level == MODULE_INITIALIZATION_LEVEL_EDITOR) { ... }` block?

Comment (Bromeon) [reply modules/openxr/register_types.cpp:237]: As mentioned, I took inspiration from https://github.com/godotengine/godot/pull/86209/files.

Should that one be changed, too?

Comment (dsnopek) [reply modules/openxr/register_types.cpp:237]: If there isn't a technical reason to do it that way, then, yeah, that one should be changed too, since that's not how the API is intended to be used. (We don't need to do that on this PR, though.)

Comment (akien-mga) [reply modules/openxr/register_types.cpp:237]: We seem to have a bunch of cases that need to be cleaned up in a follow up PR:
```
$ rg -g'register_types.cpp' -l API_EDITOR 
fbx/register_types.cpp
gltf/register_types.cpp
minimp3/register_types.cpp
gdscript/register_types.cpp
vorbis/register_types.cpp
```

And many of those (and maybe others) don't seem to use the `p_level` consistently. Doesn't this actually lead to registering classes multiple times when this is called for each initialization level?

Comment (akien-mga) [reply modules/openxr/register_types.cpp:237]: I'll merge this now to include in my tentative build for 4.4.1-rc1, but we can improve registration of modules in a follow-up.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.4.1.

File: modules/openxr/register_types.cpp (hunk 1 above)
Comment (dsnopek) [reply modules/openxr/register_types.cpp:237]: I just made PR https://github.com/godotengine/godot/pull/104084 to register these editor classes in the correct way. (We can keep that in 4.5 if we want - the code in 4.4 works fine, even if it's using the API incorrectly.)

> And many of those (and maybe others) don't seem to use the `p_level` consistently. Doesn't this actually lead to registering classes multiple times when this is called for each initialization level?

It looks like those only register their classes once. Some just have this at the start of their register function:

```
	if (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {
		return;
	}
```
