### PR TITLE
Disabled re-assigning 'self'

### LINKED ISSUE #33604: 'self' can be re-assigned
**Godot version:**

3.1.1 Stable Mono

**OS/device including version:**

Windows 8.1

**Issue description:**

`self` can be assigned to another value. The type checker will try to prevent this because `self` is of type `self` and can't be another type, but you can assign it any value that doesn't have a known type.

**Steps to reproduce:**

Assign `self` to any value without an inferred type.

```gdscript
self = [5.0][0]
```
```gdscript
var nothing
self = nothing
```

This is all the code in the minimal reproduction project:

```gdscript
var _self := self
$AnotherNode.pause_mode = PAUSE_MODE_STOP

#self = 5  # Does not work (good)
self = [5][0]

#print(self + 5)  # Does not work (good)
print([self][0] + 5)  # 10

self = [AnotherScript][0]

#print(self.some_func())  # Does not work (good)
print([self][0].some_func())  # Hello World

self = [null][0]

#print($AnotherNode)  # Does not work (bad)
self = _self
print($AnotherNode)

var another_node = $AnotherNode
self = another_node

print(pause_mode == self.pause_mode)  # False

print(self.owner == owner.get_node(name))  # True
print(self.owner == owner.get_node(self.name))  # False
```

**Minimal reproduction project:**

[self-issue.zip](https://github.com/godotengine/godot/files/3843227/self-issue.zip)

### PR DESCRIPTION
**Pull request by DaividFrank**
Added the same checks that were done on constants to self by it's type to prevent it from being re-assigned

Fixes: #33604 
Although there are some examples they give which I'm not sure what should be done about them, though I'm willing to try whatever solution might be agreed upon. (i.e. "print([self][0] + 5)  # 10")

### CODE REVIEW

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -8152,6 +8156,11 @@ void GDScriptParser::_check_block_types(BlockNode *p_block) {
 							break;
 						}
 
+						if (op->arguments[0]->type == Node::TYPE_SELF) {
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp]: I don't think this second check is needed. It'll have already given an error in the first one.

**Comment by vnen** [comment]
> Although there are some examples they give which I'm not sure what should be done about them, though I'm willing to try whatever solution might be agreed upon. (i.e. "print([self][0] + 5) # 10")

There's really nothing to do about this, it is correct. Since arrays aren't typed in GDScript, there's no static-check that can be done there (well, we could still apply inference since we can see the actual value, but that's another discussion). The only issue there is the possibility to reassign `self`, which is corrected by this PR.

File: modules/gdscript/gdscript_parser.cpp (hunk 1 above)
Comment (DaividFrank) [reply modules/gdscript/gdscript_parser.cpp]: I assumed it'll be necessary since it's checked for constants in both locations, is the constant check also redundant?

Comment (vnen) [reply modules/gdscript/gdscript_parser.cpp]: No, because the constant check here is for typed stuff, which aren't understood by the tokenizer (so it catches `const`s defined on script, or engine-defined such as `Node`). 

In fact, we could also make `self` as constant by adding `node_type.is_constant = true;` to: https://github.com/godotengine/godot/blob/ff7e7bd260f8541d4c3303a8c82ae438402e71c3/modules/gdscript/gdscript_parser.cpp#L6289-L6293

Which would be enough to disallow reassign to `self`. Though I prefer your change anyway since the error message is clearer. Feel free to include this suggestion in the commit. But this second check is still redundant.

**Comment by akien-mga** [comment]
Note that to edit the PR based on the feedback, you should amend the commit with `git commit --amend` and update the remote with `git push --force`. See [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html) for details.

There's a typo in `gdscript_pareser.cpp` in the commit log, I'd suggest to replace it by `GDScript:`. The affected file is already clear from the diff.

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
