### PR TITLE
Fix tooltip appearing in old place, on movement

### LINKED ISSUE #96707: Tooltip sometimes appears at old mouse position
### Tested versions

4.4 dev 5675c76
Not reproducible in 4.3

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

If you move cursor before hovering over something with tooltip, the tooltip can appear at older mouse position.

https://github.com/user-attachments/assets/27982e1e-b547-422b-a14b-cae7c34d26c1

### Steps to reproduce

1. Hover scene tree node while moving your cursor fast

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by aXu-AP**
Fixes #96707

Also fixes tooltip appearing even if mouse is in steady motion (now accepts max 5 px movement).
tooltip2

### CODE REVIEW

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -1935,19 +1935,18 @@ void Viewport::_gui_input_event(Ref<InputEvent> p_event) {
 
 				// If the tooltip timer isn't running, start it.
 				// Otherwise, only reset the timer if the mouse has moved more than 5 pixels.
-				if (!is_tooltip_shown && over->can_process() &&
-						(gui.tooltip_timer.is_null() ||
-								Math::is_zero_approx(gui.tooltip_timer->get_time_left()) ||
-								mm->get_relative().length() > 5.0)) {
-					if (gui.tooltip_timer.is_valid()) {
-						gui.tooltip_timer->release_connections();
-						gui.tooltip_timer = Ref<SceneTreeTimer>();
```
Comment (aXu-AP) [inline scene/main/viewport.cpp:1944]: Am I missing something here or is this line unnecessary? The property gets overwritten anyways in few lines further so I removed this one.

File: scene/main/viewport.cpp [hunk 2]
```diff
@@ -1935,19 +1935,18 @@ void Viewport::_gui_input_event(Ref<InputEvent> p_event) {
 
 				// If the tooltip timer isn't running, start it.
 				// Otherwise, only reset the timer if the mouse has moved more than 5 pixels.
-				if (!is_tooltip_shown && over->can_process() &&
-						(gui.tooltip_timer.is_null() ||
-								Math::is_zero_approx(gui.tooltip_timer->get_time_left()) ||
```
Comment (jadoc) [inline scene/main/viewport.cpp:1940]: I don't think we want to remove the check for a stopped timer. The goal of the minimum distance test is to prevent the timer from from being reset by small mouse movements, _not_ to prevent the timer from being started in the first place. With the proposed change, a user may be confused by a tooltip not displaying just because they haven't moved their mouse enough. This could happen if their mouse had been sitting just a few pixels away from the control of interest before they moved to it.

Also, the proposed change no longer matches the comments describing the desired behavior above.

File: scene/main/viewport.cpp (hunk 1 above)
Comment (jadoc) [reply scene/main/viewport.cpp:1944]: I agree that this is unnecessary.

File: scene/main/viewport.cpp (hunk 2 above)
Comment (aXu-AP) [reply scene/main/viewport.cpp:1940]: I see. I think checking for the stopped timer also doesn't resolve that problem. Eg. mouse is moved to near the control, then it's moved inside the control before the timer stops => no triggering.

I think the solution is to check if there's a new control under the mouse and restart the timer in that case.

Comment (jadoc) [reply scene/main/viewport.cpp:1940]: Yes, we could reset the timer if `over` doesn't match `gui.tooltip_control`.

File: scene/main/viewport.cpp [hunk 3]
```diff
@@ -1933,19 +1933,18 @@ void Viewport::_gui_input_event(Ref<InputEvent> p_event) {
 
 				// If the tooltip timer isn't running, start it.
```
Comment (jadoc) [inline scene/main/viewport.cpp:1934]: Please fix these comments to match the new behavior. We only restart the timer whenever the control changes or the mouse moves too much.

Comment (aXu-AP) [reply scene/main/viewport.cpp]: Good catch. Let's keep the comments up to date.

**Review by timothyqiu — APPROVED** [review]
Tested locally and it solves the said issue.

The 5 pixel minimum requirement still makes the result feel a bit off, most UI toolkits don't seem to use this logic (or have a smaller min). But that's out of the scope of this PR I think :P

**Review by akien-mga — APPROVED** [review]

**Review by KoBeWi — APPROVED** [review]

**Review by Sauermann — APPROVED** [review]
The implementation of the position calculation looks correct.

**Comment by akien-mga** [comment]
Thanks!
