### PR TITLE
Fix export of `Array[Node]`

### LINKED ISSUE #77641: Exported node arrays only work when debugging in the editor, but not with exported projects
### Godot version

4.1.dev3

### System information

Tested with Linux and Android

### Issue description

Since #73256 you can now export a typed array of nodes which holds references to the nodes assigned in the inspector. However, if you export the project you just get an empty array.

### Steps to reproduce

Export a project that makes use of exported node arrays.

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/11596494/test.zip)

### LINKED ISSUE #78150: Exported typed array in instanced child scene gets empty elements added and crashes editor
### Godot version

4.1.beta1

### System information

macOS 13.3.1

### Issue description

If you have a scene (ChildScene) with a node that has an exported typed array, for example
`@export var export_array:Array[Node]`
use the inspector to add a number of child nodes as the elements of this array and then instance this scene in another scene (ParentScene) the editor becomes prone to crashing, seemingly every time it tries to load or save ParentScene. This reliably crashes the editor, and also when opening the project after the crash, the export_array array now has added empty elements, same as the number of elements it originally had. 

### Steps to reproduce

Set up a child scene with a node with a typed export array, and set up a few child nodes to set as the items in the array in the inspector.
Screenshot 2023-06-12 at 19 09 42

Instanciate the childScene in another scene parentScene
Screenshot 2023-06-12 at 19 13 02

Now, go back to the childScene and save it again (with or without modification) open the parent scene and the editor will crash. When opening the editor again after the crash you can see that the array in both the instance in parentScene and the original in childScene has added empty elements (but not in the same places!). 

If you change the child scene, removing the empty rows and try to go to the parentScene you'll crash again. Open the project and the empty elements will be back. If you don't remove them and crash again, additional empty elements will have been added.

https://github.com/godotengine/godot/assets/17763524/373ef395-178a-4206-9a73-fec55e2b5a68

You can also get a warning this is happening if when you save a scene you get a bunch of errors:
`scene/main/node.cpp:1988 - Condition "!common_parent" is true. Returning: NodePath()`
Since having typed export arrays with empty items apparently causes this error (maybe this is also a bug?) so you can see that something has gone wrong and empty items have been added to your exported array.

### Minimal reproduction project

[ExportArrayTest.zip](https://www.lostminds.com/godot/ExportArrayTest.zip)

### LINKED ISSUE #78208: Exported array gets emptied when saving scene script
### Godot version

v4.1.beta1.official [828ec2c5d]

### System information

Godot v4.1.beta1 - Windows 10.0.23475 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3550) - AMD Ryzen 5 5500 (12 Threads)

### Issue description

I have an exported array for a given type I created with class_name

```
extends Node3D
class_name Enemy
```

It is exported as follow

```
@export var rollable_hazards: Array[Enemy]
```

I populate it using the editor and it works fine, but sometimes it gets emptied after saving the exporting scene. Not sure if it relates with #62916 and/or #77735.

Here's a screen recording I did showing the issue

https://github.com/godotengine/godot/assets/8123916/09d5df4e-83af-4459-b46b-1c62f78c2bb5

Please let me know if you need any additional information.

### Steps to reproduce

1. Export an array from a scene script
2. Populate it with other nodes 
3. Edit the exporting script and save it

### Minimal reproduction project

If you check this branch out, commit [327d03d](https://github.com/lazaromenezes/dungeon-explorer-godot/commit/327d03da6c995ed586b8bc8764bdb051bb42bf7b) was the base for the changes I had into the screen recording.

### LINKED ISSUE #78330: Crash with typed array of objects
### Godot version

4.1 beta 2

### System information

Godot v4.1.beta2 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 5700 (Advanced Micro Devices, Inc.; 31.0.14057.5006) - AMD Ryzen 5 2600 Six-Core Processor (12 Threads)

### Issue description

I have just changed a filename and the class name associated. Following that Godot crashed (not the first time 4.1 beta 2 crashed on a save actually). However, this time I was not able to load the project again. Godot crashes at load.  There has also been many successful file saves without any issue.

I tried loading the project back in 4.0.3 (there's no vital component that are dependent on downgrade and upgrade so far in the project afaik) and it works perfectly and the classes are functional and working.

### Steps to reproduce

I unfortunately don't even have the slightest idea what triggered the bug. It might very well be a documented bug but since I'm basically left with no clue all I can do is link my project and a screen of the log at crash :
Capture
I did confirm by running in the Command Prompt that no further bugs were reported. I can try uploading a log but I can't seem to be able to redirect Godot's output to a log file during the project load. No log file is generated in the project's normal log folder either (all are dated hours before from now)

### Minimal reproduction project

[FlickGame_repro.zip](https://github.com/godotengine/godot/files/11770232/FlickGame_repro.zip)

### PR DESCRIPTION
**Pull request by AThousandShips**
The check was backwards, appending if the size was greater than or equal to the index, causing it to append at the end instead. 

Not sure if we should just use a resize to be safe (I assume the indices are in order, so it never technically is greater than only equal, so probably safe)

* Fixes: #77641
* Fixes: #78150 (needs further testing, [but appears to solve crash](https://github.com/godotengine/godot/issues/78150#issuecomment-1587957215))
* Fixes: #78330 (https://github.com/godotengine/godot/issues/78330#issuecomment-1594667888)
* Fixes: #78208 (confirmed https://github.com/godotengine/godot/issues/78208#issuecomment-1597738393)

### CODE REVIEW

**Comment by RedworkDE** [comment]
The indices are always in order, every index is always included and all the values of one array are always consecutive, so this fix should work unless the previously existing array is larger than the new array, in which case the tail end will remain whatever it was before.

TBH the handling on Node array in this methods seems like a really weird and unnecessary hack (these `/indices/` string are not serialized anywhere, they are generated a bit further up in the same method) so I would probably just simplify that whole mess a bit, for example like:

```diff
diff --git a/scene/resources/packed_scene.cpp b/scene/resources/packed_scene.cpp
index 4d690bd3b1c..b5fbb32fa07 100644
--- a/scene/resources/packed_scene.cpp
+++ b/scene/resources/packed_scene.cpp
@@ -240,35 +240,11 @@ Node *SceneState::instantiate(GenEditState p_edit_state) const {
 						uint32_t name_idx = nprops[j].name & (FLAG_PATH_PROPERTY_IS_NODE - 1);
 						ERR_FAIL_UNSIGNED_INDEX_V(name_idx, (uint32_t)sname_count, nullptr);
 
-						const StringName &prop_name = snames[name_idx];
-						const Variant &prop_variant = props[nprops[j].value];
-
-						if (prop_variant.get_type() == Variant::ARRAY) {
-							const Array &array = prop_variant;
-							if (Engine::get_singleton()->is_editor_hint()) {
-								if (array.get_typed_builtin() == Variant::NODE_PATH) {
-									// If editor, simply set the original array of NodePaths.
-									node->set(prop_name, prop_variant);
-									continue;
-								}
-							}
-							for (int k = 0; k < array.size(); k++) {
-								DeferredNodePathProperties dnp;
-								dnp.path = array[k];
-								dnp.base = node;
-								// Use special property name to signify an array. This is only used in deferred_node_paths.
-								dnp.property = String(prop_name) + "/indices/" + itos(k);
-								deferred_node_paths.push_back(dnp);
-							}
-
-						} else {
-							// Do an actual deferred set of the property path.
-							DeferredNodePathProperties dnp;
-							dnp.path = prop_variant;
-							dnp.base = node;
-							dnp.property = prop_name;
-							deferred_node_paths.push_back(dnp);
-						}
+						DeferredNodePathProperties dnp;
+						dnp.value = props[nprops[j].value];
+						dnp.base = node;
+						dnp.property = snames[name_idx];
+						deferred_node_paths.push_back(dnp);
 						continue;
 					}
 
@@ -435,24 +411,23 @@ Node *SceneState::instantiate(GenEditState p_edit_state) const {
 
 	for (const DeferredNodePathProperties &dnp : deferred_node_paths) {
 		// Replace properties stored as NodePaths with actual Nodes.
-		Node *other = dnp.base->get_node_or_null(dnp.path);
-
-		const String string_property = dnp.property;
-		if (string_property.contains("/indices/")) {
-			// For properties with "/indices/", the replacement takes place inside an Array.
-			const String base_property = string_property.get_slice("/", 0);
-			const int index = string_property.get_slice("/", 2).to_int();
-
-			Array array = dnp.base->get(base_property);
-			if (array.size() >= index) {
-				array.push_back(other);
-			} else {
-				array.set(index, other);
+		if (dnp.value.get_type() == Variant::ARRAY) {
+			Array paths = dnp.value;
+			if (Engine::get_singleton()->is_editor_hint()) {
+				if (paths.get_typed_builtin() == Variant::NODE_PATH) {
+					// If editor, simply set the original array of NodePaths.
+					dnp.base->set(dnp.property, dnp.value);
+					continue;
+				}
 			}
-
-			dnp.base->set(base_property, array);
+			Array array = dnp.base->get(dnp.property);
+			array.resize(paths.size());
+			for (int k = 0; k < array.size(); k++) {
+				array.set(k, dnp.base->get_node_or_null(paths[k]));
+			}
+			dnp.base->set(dnp.property, array);
 		} else {
-			dnp.base->set(dnp.property, other);
+			dnp.base->set(dnp.property, dnp.base->get_node_or_null(dnp.value));
 		}
 	}
 
diff --git a/scene/resources/packed_scene.h b/scene/resources/packed_scene.h
index 5c53ffdb456..44443dde0a8 100644
--- a/scene/resources/packed_scene.h
+++ b/scene/resources/packed_scene.h
@@ -72,7 +72,7 @@ class SceneState : public RefCounted {
 	struct DeferredNodePathProperties {
 		Node *base = nullptr;
 		StringName property;
-		NodePath path;
+		Variant value;
 	};
 
 	Vector<NodeData> nodes;
```

**Comment by AThousandShips** [comment]
Thank you for your suggestions, will take a better look today and see!

**Comment by AThousandShips** [comment]
Can confirm that this works, with some minor tweaks, but ran into a separate issue that I'll try and identify, after export it erases the array in the editor, unsure why

**Comment by AThousandShips** [comment]
Added fix, will squash if the more elaborate fix is approved

File: scene/resources/packed_scene.cpp [hunk 1]
```diff
@@ -435,24 +411,22 @@ Node *SceneState::instantiate(GenEditState p_edit_state) const {
...
-				array.push_back(other);
-			} else {
-				array.set(index, other);
+		if (dnp.value.get_type() == Variant::ARRAY) {
+			Array paths = dnp.value;
+			if (Engine::get_singleton()->is_editor_hint()) {
+				// If editor, simply set the original array of NodePaths.
+				dnp.base->set(dnp.property, dnp.value);
+				continue;
 			}
```
Comment (ajreckof) [inline scene/resources/packed_scene.cpp:420]: This breaks `@tool` and should be removed entirely. I had kept it with the second test as I was unsure if normal array of `NodePath` could reach here. This wasn't great but as this was never called it did not have any impact. But without the second check it will always pass in editor and node will never be set in editor.
```suggestion

```

**Review by ajreckof — CHANGES_REQUESTED** [review]
The rest seems legit. I tried to replicate the bug you mentioned but I couldn't at least with the modification I suggested. If you are still able to reproduce, it might just be that I'm dumb and I did't understand what you describe or that it is platform dependent.

File: scene/resources/packed_scene.cpp (hunk 1 above)
Comment (AThousandShips) [reply scene/resources/packed_scene.cpp:420]: Will remove tomorrow!

**Review by ajreckof — APPROVED** [review]

**Comment by KoBeWi** [comment]
Modifying the script seems to clear the variables:

https://github.com/godotengine/godot/assets/2223172/f5b7300e-cf8c-4bb6-8464-17d7fe082ab6

File: scene/resources/packed_scene.cpp [hunk 2]
```diff
@@ -465,27 +441,20 @@ Node *SceneState::instantiate(GenEditState p_edit_state) const {
...
-		if (string_property.contains("/indices/")) {
-			// For properties with "/indices/", the replacement takes place inside an Array.
-			const String base_property = string_property.get_slice("/", 0);
-			const int index = string_property.get_slice("/", 2).to_int();
+		if (dnp.value.get_type() == Variant::ARRAY) {
+			Array paths = dnp.value;
 
 			bool valid;
-			Array array = dnp.base->get(base_property, &valid);
+			Array array = dnp.base->get(dnp.property, &valid);
```
Comment (ajreckof) [inline scene/resources/packed_scene.cpp:448]: Just realised something this should be duplicated first. This was not present previously and is causing another kind of bug where the default value gets modified instead of anew instance. Since You're modifying I felt like it could be included here directly but I can make a separate PR if needed.

Comment (AThousandShips) [reply scene/resources/packed_scene.cpp:448]: Put the duplication below after the validity check

Comment (ajreckof) [reply scene/resources/packed_scene.cpp:448]: yeah that was a good idea

Comment (ajreckof) [reply scene/resources/packed_scene.cpp:448]: Yeah this is right we are never using the value we are getting from there. What still needs to be acounted for is the typing of the array but since we know for sure this is a `Array[Node]` this should be easy. This might also fix the disappearrence because in fact if the value was invalid it would never set the array which would make Nodes dissapear. 
Overall I think this is a really good idea.

Comment (AThousandShips) [reply scene/resources/packed_scene.cpp:448]: I'll leave it the way it is for now and if desired we can modify it later, unless it's considered significant here

**Comment by AThousandShips** [comment]
Unless I'm missing something this now also fixes #78208, can someone else confirm?

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!
