### PR TITLE
[3.x] Check duplicate keys in dictionary literals: enums and const variables

### LINKED ISSUE #7034: GDScript ignores duplicate keys in dictionaries
If you type something like the following:

```gdscript
var d = {
    'key': 'value1',
    'key': 'value2'
}
print(d.key)
```

It will print `value2`, overriding the first definition.

This a problem because a typo can lead to hard to find bugs. The user might even think this is some "feature" and expect it to work with multiple keys in some way.

It's something that should be detected at parse-time and show as error right in the script editor when typing.

### LINKED ISSUE #50971: Duplicate dictionary keys are allowed if the keys are enum
### Godot version

3.3.2

### System information

Windows 10

### Issue description

Although duplicate dictionary keys are not allowed if the keys are constant, duplication does not cause compilation and runtime errors when using enumerations

### Steps to reproduce

This one is invalid:

```gdscript
const D: Dictionary = {
	1: "a",
	1: "b"
}
```

But this one is valid:

```gdscript
enum e {
	one = 1
}

const D: Dictionary = {
	e.one: "a",
	e.one: "b"
}
```

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by kdiduk**
**Implement checking of identifiers (const variables and unnamed enums) and named enums when parsing dictionary literals whether the keys are not duplicated.**

In case of duplicate key is encountered, highlight the line with it and print error message:
`Duplicate key "foo" found in Dictionary literal`

This commit is a logical continuation of the commit https://github.com/godotengine/godot/commit/dab73c701a9785be443977a613e57600d1e136c8 which implemented such checks only for literal keys and fixed #7034.

Apart from that, this commit also fixes the issue that the line below the duplicated key was highlighted with the error in case it was the last one in the dictionary literal and there was no hanging comma. That is, in the following example:
```gdscript
var foo = {
	1: "1",
	2: "2",
	1: "3"
}
```
the last line (with the `}`) was highlighted as the error instead of the line abobe with `1: "3"`. Now it's fixed.

Also, the format of the error message has been changed so that now the error message also contains the value of the key which is duplicated. Instead of:
`Duplicate key found in Dictionary literal`
now it prints
`Duplicate key "<value>" found in Dictionary literal`

Fixes #50971

Some of the tests for this PR are in [this Gist](https://gist.github.com/kdiduk/af087ee60eed0290cad19f6d281b08d6)

### CODE REVIEW

**Comment by kdiduk** [comment]
Please, note that in this PR I've changed the error message so that now it also prints the value of the hey which is duplicated. That is, instead of:
`Duplicate key found in Dictionary literal`
now it will prints
`Duplicate key "<value>" found in Dictionary literal`

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -1077,14 +1077,15 @@ GDScriptParser::Node *GDScriptParser::_parse_expression(Node *p_parent, bool p_s
 						}
 						expecting = DICT_EXPECT_COMMA;
 
-						if (key->type == GDScriptParser::Node::TYPE_CONSTANT) {
-							Variant const &keyName = static_cast<const GDScriptParser::ConstantNode *>(key)->value;
-
-							if (keys.has(keyName)) {
-								_set_error("Duplicate key found in Dictionary literal");
+						const Variant *key_value = _try_to_find_constant_value_for_expression(key);
+						if (key_value) {
```
Comment (lawnjelly) [inline modules/gdscript/gdscript_parser.cpp:1081]: Presumably this is rare that the error flags, and I'm guessing the processing in `_try_to_find_constant_value_for_expression()` is more than the old `if (keys.has(keyName))`?

If that is the case would it be an idea to do a quick reject with the old `if (keys.has(keyName))` before calling `_try_to_find_constant_value_for_expression()`?

**Comment by lawnjelly** [comment]
This looks okay to me as far as I can see, but I'm not familiar with the gdscript parser at all.

@vnen would you be able to take a quick look to confirm this is okay (am guessing you are familiar)?

**Comment by AThousandShips** [comment]
Needs a rebase, just in case

File: modules/gdscript/gdscript_parser.cpp (hunk 1 above)
Comment (kdiduk) [reply modules/gdscript/gdscript_parser.cpp:1081]: No, there is no need to do that. If you check the definition of  `_try_to_find_constant_value_for_expression()`, it first checks whether the current token is a constant and returns it's value. 

In fact, `_try_to_find_constant_value_for_expression()` is not a replacement of old `if (keys.has(keyName))`, it's meaning is to correctly evaluate the value of the token, so in fact it just improves that if-condition (it's still there, just few lines below).

**Comment by kdiduk** [comment]
Rebase done

**Review by lawnjelly — APPROVED** [review]
This looks ok to me, I'm not a gdscript maintainer though, so it would be nice to have a review from @godotengine/gdscript .

I guess we can merge in few days if no further response (they may have been busy with GDC).

**Comment by lawnjelly** [comment]
Thanks!

No response from gdscript team, but this looks fairly straightforward and I'm satisfied if there are problems we can revert and fix. :+1:
