### PR TITLE
GDScript: Add error message when a GDScript resource fails to load.

### LINKED ISSUE #78230: Autoload scripts compile error are not reported (except confusing "Script does not inherit from Node")
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Win 10

### Issue description

When Autoload scripts have compile errors, the error is not printed to Output. Instead, they fail when Running with an error completely unrelated to what's wrong:

```
USER ERROR: Script does not inherit from Node: res://thetrouble.gd.
   at: start (main/main.cpp:2776)
```

There's no other information. I assume this message is because their failure to compile means they don't get associated as a Node child (related to #75388?)? But I don't understand why they don't have any errors reported. I think it only occurs if they were added to Autoload before they got compiled/used?

I am using an external editor (gvim) and godot's LSP support. That correctly shows the error, but only when I'm editing the broken file which makes it unclear what's wrong. (When I first encountered this problem, I looked at the files, saw they were extending Node2D and didn't understand the problem. It's possible the lsp was failing to show any errors, but it shows errors now.)

### Steps to reproduce

1. New project, add scene
2. Add script "thetrouble.gd"
3. Add thetrouble.gd as an Autoload
4. Add invalid code to thetrouble.gd (two variables named `seq`) 
  * **Expected**: compile error reported
  * **Actual**: No output
5. Run project
  * **Expected**: compile error reported
  * **Actual**: Script does not inherit from Node: res://thetrouble.gd.
6. Add valid code to thetrouble.gd (assign a value to `seq`) 
  * **Expected**: compile error reported
  * **Actual**: No output

Note: If you mix up steps 2 and 3, the issue will not occur.

Workaround: Edit Autoloads and disable and re-enable thetrouble's autoload state and error messages appear. New errors even appear after this point.

### Minimal reproduction project

[repro.zip](https://github.com/godotengine/godot/files/11747339/repro.zip)

### PR DESCRIPTION
**Pull request by anvilfolk**
Currently, GDScripts who are only loaded through `ResourceLoader::load()`, like Autoloads, do not have a pathway to announce there is an error in their code. This contributes to significant confusion when errors occur in projects when autoloads are involved. At least partially closes #78230.

### CODE REVIEW

File: modules/gdscript/gdscript.cpp [hunk 1]
```diff
@@ -2698,6 +2698,10 @@ Ref<Resource> ResourceFormatLoaderGDScript::load(const String &p_path, const Str
 	Error err;
 	Ref<GDScript> scr = GDScriptCache::get_full_script(p_path, err, "", p_cache_mode == CACHE_MODE_IGNORE);
 
+	if (err) {
+		ERR_PRINT(vformat(R"(Failed to load script at path "%s". Error code %d.)", p_path, err));
```
Comment (anvilfolk) [inline modules/gdscript/gdscript.cpp:2702]: Need to check whether `ERR_PRINT_ED` also writes an error to the console, or even whether, when autoloads get loaded, these errors would be visible.

Comment (Rindbee) [reply modules/gdscript/gdscript.cpp:2702]: Here it is possible to distinguish what period the error is, see https://github.com/godotengine/godot/pull/76954#issue-1705988639:


```suggestion
		if (scr.is_valid()){  
			// Errors during compilation.
		}else{ 
			// Errors during loading.
		}
```

Comment (adamscott) [reply modules/gdscript/gdscript.cpp:2702]: Great suggestion, @Rindbee

**Comment by OmarShehata** [comment]
Recently encountered this, and wanted to open a PR to fix but found this. @anvilfolk are you still working on this? Looks like it's ready, just needs the suggested patch applied?

Happy to help test or contribute if any help is needed here

**Comment by anvilfolk** [comment]
> Recently encountered this, and wanted to open a PR to fix but found this. @anvilfolk are you still working on this? Looks like it's ready, just needs the suggested patch applied?
> 
> Happy to help test or contribute if any help is needed here

Sorry, life's been a bit of a mess. I'm hoping to have a little more time in the coming weeks and want to work on this again, yes :)

@Rindbee so if `!scr->is_valid()`, then the error is usually that the file was not found? Whereas if `scr->is_valid()`, then the file was found, but there may be some parsing/analyzing/compilation error? Does that sound right?

**Comment by Rindbee** [comment]
> @Rindbee so if `!scr->is_valid()`, then the error is usually that the file was not found? 

This usually means an error occurred in `GDScript::load_source_code()`.

https://github.com/godotengine/godot/blob/3fa8fad26b97a8af20e7996b7e17d8f23fc04b89/modules/gdscript/gdscript_cache.cpp#L257-L260

Other than that, it's a valid script.

**Comment by anvilfolk** [comment]
A couple of notes:
- I'm using `ERR_PRINT_ED` in an attempt to generate a visible error in the editor, but unfortunately when autoloads are loaded, the editor isn't quite open yet so the error does not appear.
- `ERR_PRINT_ED` does still print an error to the console, so when you load your project in the editor, the OS console will have the error log.
- When you run your game from the editor, the errors will show up in the editor console.
- This approach results in "duplicate" errors, e.g. Godot will still complain about the auloload not inheriting from Node, but will now also print another error stating why (parse error, for example).
- Will only print errors if we are not passing the error back to the caller - that means it's `ResourceFormatLoaderGDScript::load`'s responsibility to report the error.

I don't think we can get around the "duplicated" errors, since `ResourceLoader::load()` specifically does not want to fail due to GDScript parsing errors, and will return `OK` if the parsing fails.

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.
