### PR TITLE
Fix radiance for sky in GLES stereo rendering

### LINKED ISSUE #84598: OpenGL: Sky contribution fails in VR
### Godot version

4.2.dev 5ee983188de97ae027f9b9c1443438063f708a7e

### System information

Windows 10 - Compatibility renderer 

### Issue description

When running a VR project sky contribution is not working in the compatibility renderer:

image

It is working fine in normal mode. Can be worked around by setting sky contribution to 0 and providing an ambient color.

### Steps to reproduce

Try any project with a proper sky setup in XR, just switch to compatibility renderer.

### Minimal reproduction project

I'll try and create an MVP soon that can be used without XR hardware, but for now this can be used:
https://github.com/BastiaanOlij/godot_openxr_demo

### PR DESCRIPTION
**Pull request by BastiaanOlij**
This took me waaaaaaaaaaaaaaaaaaaaaaay too long to figure out.

In OpenGL everything is output upside down compared to Vulkan, that means that our culling order is reversed, see 
```
	if (!flip_y) {
		// If we're rendering right-side up, then we need to change the winding order.
		glFrontFace(GL_CW);
	}
```
in `RasterizerSceneGLES3::render_scene`.

However, when we output to OpenXR (or webXR), the compositor expects us to deliver images with the same orientation and thus we change things up and render things "upside down", and only flip the image on output to screen. So we keep to the same culling order.

The problem then is that our sky radiance map update code runs after we do this optional flip. This logic renders a full screen triangle to perform a full screen effect. The order of the vertices of this triangle is defined on the assumption we are doing our flip.

In normal mode, we render our triangle and thus our radiance map is rendered.
In XR mode we cull our triangle and thus our radiance map remains black.

The simple answer is to disable culling as we don't care for culling in this case.

This PR cleans up a few related issues and code that assumes state is retained when it's not.

Fixes #84598

### CODE REVIEW

**Comment by decacis** [comment]
It's working fine now!

| Master | This PR |
|--------|---------|
|Killifish-Ripe-Composed|Gossamerwingedbutterfly-Unwilling-Distant|

**Review by dsnopek — APPROVED** [review]
Great catch! The code changes look good to me, but probably should be reviewed by someone who knows rendering a little better than me :-)

File: drivers/gles3/rasterizer_scene_gles3.cpp [hunk 1]
```diff
@@ -1054,11 +1062,13 @@ void RasterizerSceneGLES3::_filter_sky_radiance(Sky *p_sky, int p_base_layer) {
 
 	CubemapFilterShaderGLES3::ShaderVariant mode = CubemapFilterShaderGLES3::MODE_DEFAULT;
 
-	if (p_base_layer == 0) {
+#ifdef GL_API_ENABLED
+	if (RasterizerGLES3::is_gles_over_gl() && p_base_layer == 0) {
```
Comment (clayjohn) [inline drivers/gles3/rasterizer_scene_gles3.cpp:1066]: I don't think this is correct. We need the mipmaps generated because we want to use the mipmapped version of the base layer for calculating the radiance map. This is the "pre-filtering" part of pre-filtered importance sampling

Comment (BastiaanOlij) [reply drivers/gles3/rasterizer_scene_gles3.cpp:1066]: Ah my bad, we do this check in `_update_dirty_skys` probably because `glTexImage2D` isn't supported under GLES. It is interesting here that for GLES `glGenerateMipmap` is also skipped (that might be a bug in those places as it won't allocate space for the mipmaps)

I made the same change here to test if it would fix the issue and fall back on the old approach of filtering, I didn't change it back.

Would be good to have a discussion on why this is working the way it does in `_update_dirty_skys`

Comment (BastiaanOlij) [reply drivers/gles3/rasterizer_scene_gles3.cpp]: Definitely works fine on my Quest with this returned the way it was.

**Review by clayjohn — APPROVED** [review]
Looks great!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.

**Comment by YuriSizov** [comment]
Can't be cherry-picked for 4.1 because it depends on changes from https://github.com/godotengine/godot/pull/77496.
