### PR TITLE
Fix bottom panel dock layout popup position

### LINKED ISSUE #113333: Dock Position popup for the bottom panel appears at the wrong position
### Tested versions

v4.6.dev.custom_build [7ed0b6167]

### System information

Godot v4.6.dev (7ed0b6167) - Arch Linux #1 SMP PREEMPT_DYNAMIC Mon, 24 Nov 2025 15:21:09 +0000 on X11 - X11 display driver, Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3060 Ti (nvidia; 580.105.08) - 13th Gen Intel(R) Core(TM) i5-13400F (16 threads) - 15.37 GiB memory

### Issue description

https://github.com/user-attachments/assets/4a9f7a78-42cf-44a1-b6a4-3e24fbffb451

This does not happen if the bottom panel is not open:

https://github.com/user-attachments/assets/7796ce13-351d-4a83-84b6-81e9e417bcd7

### Steps to reproduce

1. Make sure that the editor window is not fullscreen and the bottom panel is open.
2. Right click on any of the tabs in the bottom panel.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by aaronp64**
Update `EditorDockManager::_dock_container_popup` to consistently use tab bar position to determine popup position, rather than combining tab bar and container positions.  This handles cases where the tabs are on the bottom of the container, like for the bottom panel.

Fixes #113333

### CODE REVIEW

**Review by kitbdev — APPROVED** [review]
Tested, fixes the issue.

File: editor/docks/editor_dock_manager.cpp [hunk 1]
```diff
@@ -298,7 +298,7 @@ void EditorDockManager::_dock_container_popup(int p_tab_idx, TabContainer *p_doc
 
 	// Right click context menu.
 	dock_context_popup->set_dock(hovered_dock);
-	dock_context_popup->set_position(p_dock_container->get_tab_bar()->get_screen_position() + p_dock_container->get_local_mouse_position());
+	dock_context_popup->set_position(p_dock_container->get_screen_position() + p_dock_container->get_local_mouse_position());
```
Comment (KoBeWi) [inline editor/docks/editor_dock_manager.cpp]: Alternatively
```suggestion
	dock_context_popup->set_position(p_dock_container->get_tab_bar()->get_screen_position() + p_dock_container->get_tab_bar()->get_local_mouse_position());
```
(relevant for #113051)

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
