### PR TITLE
[Net] Fix IP address resolution incorrectly locking the main thread.

### LINKED ISSUE #51181: HTTPRequest freezes when hostname resolution stalls due to broken connectivity.
### Godot version

3.4 beta 2

### System information

Mac OSX

### Issue description

When making an HTTP request in the new beta, sometimes the app can pause.

This only happens when the WiFi has a connection, but the WiFi is not connected to the internet.

This bug is not present in 3.2.2 stable, it could be related to the new [HTTPRequest Gzip compression](https://github.com/godotengine/godot/pull/48651)?

### Steps to reproduce

1. Clone [this repository](https://github.com/tavurth/godot-internet-bug)

2. Disconnect your WiFi from the internet (pull the cable)

3. Run the project

4. Your app should freeze

In Godot 3.3.2 stable, the app does not freeze and instead shows a message in the console, as well as a connection warning.

### Minimal reproduction project

https://github.com/tavurth/godot-internet-bug

### PR DESCRIPTION
**Pull request by Faless**
This seems to be a pretty old bug, older then originally reported (at least under certain circumstances).

The IP singleton uses a resolve queue so developers can queue hostnames for resolution in a separate while keeping the main thread unlocked (address-resolution OS functions are blocking, and could block for a long time in case of network disruption).

In most places though, the address resolution function was called with the mutex locked, causing other functions (querying status, queueing another hostname, ecc) to block until that resolution ended.

This commit ensures that all calls to OS address resolution are done with the mutex unlocked.

Fixes #51181 . Note: wile in the issue this is described as a regression, this is a very old issue (according to my tests), according to my tests on Linux, and can be found [even to `2.1`](https://github.com/godotengine/godot/blob/2.1/core/io/ip.cpp#L94-L101). I suspect testing it is just tricky due to OS/router DNS caches.

[`3.x` version here](https://github.com/Faless/godot/tree/net/3.x_ip_lock)

### CODE REVIEW

**Comment by tavurth** [comment]
Wow so fast 🎉

File: core/io/ip.cpp [hunk 1]
```diff
@@ -178,13 +206,12 @@ IP::ResolverID IP::resolve_hostname_queue_item(const String &p_hostname, IP::Typ
 IP::ResolverStatus IP::get_resolve_item_status(ResolverID p_id) const {
 	ERR_FAIL_INDEX_V(p_id, IP::RESOLVER_MAX_QUERIES, IP::RESOLVER_STATUS_NONE);
 
-	MutexLock lock(resolver->mutex);
```
Comment (RandomShaper) [inline core/io/ip.cpp:181]: I'm not sure this lock should be removed. To me, it makes sense to enter a critical section every time the queue is accessed. That also leads to something else: the `status` field may not need to be a `SafeNumeric` (formerly `volatile`).
What do you think?

Comment (Faless) [reply core/io/ip.cpp:181]: I actually removed the lock because it was a `SafeNumeric` and the queue is a fixed array so its size can't change.
I agree the status could no longer be `SafeNumeric`, but in any case the function probably does not need the mutex.

The queue has fixed size, so the elements memory pointer can't change.
Even if we lock in the function, as long as we return we are no longer locked (so the state can change between the return and whatever the usage of that returned value).

Comment (RandomShaper) [reply core/io/ip.cpp:181]: Makes sense.

**Review by RandomShaper — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
> Fixes #51181 . Note: wile in the issue this is described as a regression, this is a very old issue (according to my tests), according to my tests on Linux, and can be found [even to `2.1`](https://github.com/godotengine/godot/blob/2.1/core/io/ip.cpp#L94-L101). I suspect testing it is just tricky due to OS/router DNS caches.

Isn't this a regression from #49026? If so that would explain why it's present in `2.1`, as this change was made in `2.1` and not `master` until #49026, which was then backported to `3.x`.

If so, the `3.3` branch shouldn't be affected (and indeed the fix doesn't seem to cherry-pick cleanly at least).

**Comment by Faless** [comment]
`3.2` seems to also have the underlying bug, though maybe harder to get to (would still break if you had to `HTTPRequest` at least):

https://github.com/godotengine/godot/blob/3.2/core/io/ip.cpp#L99-L106
