### PR TITLE
Fix collision shape update when changing shape properties

### LINKED ISSUE #45090: Editing the extents of a CollisionShape2D via script causes the one-way collision to stop working
**Godot version:**

3.2.4-beta5 (but the bug exists in other versions too)

**OS/device including version:**

Windows 8, nvidia

**Issue description:**

If you change the size of a CollisionShape2D extents via script, the one-way collision will stop working, although this will keep saying that it is enable when you print the `CollisionShape2D.one_way_collision`.

* Either way, the one-way collision can work again if you set the one_way_collision property as true again with `collider.one_way_collision = true` right after editing the extents.

**Steps to reproduce:**
Just edit the values of a ColisionShape2D extents via script, this will cause the one-way collision to stop working even if it says it is enabled.

**Minimal reproduction project:**

[one-way-collision-extents-bug.zip](https://github.com/godotengine/godot/files/5794128/one-way-collision-extents-bug.zip)

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
This change does two things:

1. Properly update the internal shape data using `_update_in_shape_owner` when updating a shape (in 2D it was resetting one way collision because of clearing and re-adding shapes without calling this method)

2. Avoid unnecessary updates when calling `set_shape` with the same shape, which happens each time a shape property is modified (e.g `shape.extents.x = ...`)

Fixes #45090

### CODE REVIEW

File: scene/3d/collision_shape_3d.cpp [hunk 1]
```diff
@@ -185,6 +188,7 @@ void CollisionShape3D::set_shape(const Ref<Shape3D> &p_shape) {
 		if (shape.is_valid()) {
 			parent->shape_owner_add_shape(owner_id, shape);
 		}
+		_update_in_shape_owner();
```
Comment (AndreaCatania) [inline scene/3d/collision_shape_3d.cpp:191]: It looks good, just a question regarding `_update_in_shape_owner();` - why this is needed here? According to `shape_owner_add_shape` it should already updated what is needed.

Comment (pouleyKetchoupp) [reply scene/3d/collision_shape_3d.cpp:191]: I was trying to make it consistent with 2D and with `NOTIFICATION_PARENTED`, but you're right, it doesn't actually update anything in this case. I will remove it from here and `NOTIFICATION_PARENTED` as well.

Comment (pouleyKetchoupp) [reply scene/3d/collision_shape_3d.cpp]: Done!

**Review by AndreaCatania — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
