### PR TITLE
[.NET] Add a preload hook to load .NET assemblies from the APK

### LINKED ISSUE #103915: Regression: Godot 4.4 (C#/Mono) Android game exports sometimes crash during startup on Meta Quest 2/3
### Tested versions

# Tested on Godot versions
Did a "binary search" to figure out the version which introduced the issue. It seems to be `4.4-dev3_mono` based on my tests. Here is an overview of the editors tested:
- v4.4-stable_mono_win64 (with godotxrvendors v3.1.2) -bad
- v4.4-stable_mono_win64 (with godotxrvendors v4.0.0-beta1) - bad
- v4.4-rc3_mono_win64 - not tested
- v4.4-rc2_mono_win64 - not tested
- v4.4-rc1_mono_win64 (with godotxrvendors v4.0.0-beta1) - bad
- v4.4-beta4_mono_win64 - not tested
- v4.4-beta3_mono_win64 - not tested
- v4.4-beta2_mono_win64 - not tested
- v4.4-beta1_mono_win64 (with godotxrvendors v4.0.0-beta1) -bad
- v4.4-dev7_mono_win64 - not tested
- v4.4-dev6_mono_win64 - not tested
- v4.4-dev5_mono_win64 - not tested
- v4.4-dev4_mono_win64 (with godotxrvendors v3.1.2) -bad
- v4.4-dev3_mono_win64 (with godotxrvendors v3.1.2) - bad <-- (First bad version)
- v4.4-dev2_mono_win64 (with godotxrvendors v3.1.2) -good
- v4.4-dev1_mono_win64 - not tested
- v4.3-stable_mono_win64 (with godotxrvendors v3.1.2) - good

### System information

Built from Windows 11, tested thoroughly on Quest 2 (and reproduced on 3). Godot versions in description.

### Issue description

# Description
Games built for android and running on Meta Quest crashes sometimes at startup. Tested on Quest 2 and 3
Reproducible with a minimal setup, described below.
This only seems to happen if the project is using C#

### Steps to reproduce

# Development environment
- OpenJDK 17 (as recommended in docs)
- Android SDK setup (also from docs): `sdkmanager --sdk_root=<android_sdk_path> "platform-tools" "build-tools;34.0.0" "platforms;android-34" "cmdline-tools;latest" "cmake;3.10.2.4988404" "ndk;23.2.8568313"`

# Project setup
These are the steps I followed to reproduce the problem for each godot version:
- [ ] *Create new project in the Godot mono version*
- [ ] *Install Godot XR Vendors plugin v3.1.2*
- [ ] *Add export preset*
	- [ ] *Set texture compression as suggested*
	- [ ] *Use gradle build*
	- [ ] *Use meta quest plugin*
	- [ ] *Use OpenXR*
	- [ ] *Set package name*
- [ ] *Add android build template*
- [ ] *Project settings - enable OpenXR*
- [ ] *Project settings -Enable shaders*
- [ ] *Add XR setup to main scene*
- [ ] *Add meshes to hands*
- [ ] *Add env and light*
- [ ] *Add XR init script*
- [ ] *Set main scene*
- [ ] *Add C# solution*
- [ ] *Add C# script*
- [ ] *Make sure C# solution builds*
- [ ] *Export, Install to quest 2 or 3 and Run*

# Crash log example (this one is from the 4.4-dev3 build, but they were all similar)
```
03-10 16:46:29.649 19945 20075 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xe in tid 20075 (GLThread 30), pid 19945 (4dev3xrvendors3)
03-10 16:46:29.861 20171 20171 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-10 16:46:29.861 20171 20171 F DEBUG   : Build fingerprint: 'oculus/hollywood/hollywood:12/SQ3A.220605.009.A1/51272100125100150:user/release-keys'
03-10 16:46:29.861 20171 20171 F DEBUG   : Revision: '0'
03-10 16:46:29.861 20171 20171 F DEBUG   : ABI: 'arm64'
03-10 16:46:29.861 20171 20171 F DEBUG   : Timestamp: 2025-03-10 16:46:29.696200408+0100
03-10 16:46:29.861 20171 20171 F DEBUG   : Process uptime: 1s
03-10 16:46:29.861 20171 20171 F DEBUG   : Diagnostic-Collection-Type: Tombstone Proto
03-10 16:46:29.861 20171 20171 F DEBUG   : Has-Diagnostic-Summary: Yes
03-10 16:46:29.861 20171 20171 F DEBUG   : APK-Location: /data/app/~~YgIEf2D7bgwNxo8PHlryIg==/dk.madsbangh.openxrgodot44dev3xrvendors3-gcPC0D20JLREx-pKLKAYbw==/base.apk
03-10 16:46:29.861 20171 20171 F DEBUG   : Debugging: No
03-10 16:46:29.861 20171 20171 F DEBUG   : Has-Waited-For-Debugger: No
03-10 16:46:29.861 20171 20171 F DEBUG   : Last-Activity-Time: 3705734
03-10 16:46:29.861 20171 20171 F DEBUG   : Process-Runtime: 853
03-10 16:46:29.861 20171 20171 F DEBUG   : Waiting-To-Kill:
03-10 16:46:29.861 20171 20171 F DEBUG   : Killed-By-AM: No
03-10 16:46:29.861 20171 20171 F DEBUG   : Removed: No
03-10 16:46:29.861 20171 20171 F DEBUG   : Wanted-ANR-Ui: No
03-10 16:46:29.861 20171 20171 F DEBUG   : Killed: No
03-10 16:46:29.861 20171 20171 F DEBUG   : OOM-Score-Adj: 0
03-10 16:46:29.861 20171 20171 F DEBUG   : Wanted-Error-Ui: No
03-10 16:46:29.861 20171 20171 F DEBUG   : Kill-Time: 0
03-10 16:46:29.861 20171 20171 F DEBUG   : State: TOP
03-10 16:46:29.861 20171 20171 F DEBUG   : Foreground: Yes
03-10 16:46:29.861 20171 20171 F DEBUG   : Executable: /system/bin/app_process64
03-10 16:46:29.861 20171 20171 F DEBUG   : Cmdline: dk.madsbangh.openxrgodot44dev3xrvendors3
03-10 16:46:29.861 20171 20171 F DEBUG   : pid: 19945, tid: 20075, name: GLThread 30  >>> dk.madsbangh.openxrgodot44dev3xrvendors3 <<<
03-10 16:46:29.861 20171 20171 F DEBUG   : uid: 10102
03-10 16:46:29.861 20171 20171 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xe
03-10 16:46:29.861 20171 20171 F DEBUG   : Cause: null pointer dereference
03-10 16:46:29.861 20171 20171 F DEBUG   :     x0  0000000000000000  x1  0000000000000000  x2  000000763ea69040  x3  0000007590d3c3b0
03-10 16:46:29.861 20171 20171 F DEBUG   :     x4  0000000000000000  x5  0000000000000000  x6  6e636e461f656e1f  x7  7f7f7f7f7f7f7f7f
03-10 16:46:29.861 20171 20171 F DEBUG   :     x8  793d8440c7cab653  x9  793d8440c7cab653  x10 0000000000000002  x11 0000000000000100
03-10 16:46:29.861 20171 20171 F DEBUG   :     x12 8000000000000000  x13 0000000000000001  x14 0000000000000005  x15 00000000341555ac
03-10 16:46:29.861 20171 20171 F DEBUG   :     x16 00000076ddf10c78  x17 00000076ddf00b48  x18 00000075ac160000  x19 00000075acb77ab0
03-10 16:46:29.861 20171 20171 F DEBUG   :     x20 b4000075909d9f28  x21 b400007590d84080  x22 0000000000000000  x23 0000000000000000
03-10 16:46:29.861 20171 20171 F DEBUG   :     x24 0000000000000000  x25 b400007590b8f420  x26 00000075acb78c40  x27 0000000000000001
03-10 16:46:29.861 20171 20171 F DEBUG   :     x28 0000000000000000  x29 00000075acb77a00
03-10 16:46:29.861 20171 20171 F DEBUG   :     lr  00000075863b7308  sp  00000075acb77910  pc  00000075863b730c  pst 0000000060001000
03-10 16:46:29.861 20171 20171 F DEBUG   : backtrace:
03-10 16:46:29.861 20171 20171 F DEBUG   :       #00 pc 00000000000f630c  /data/app/~~YgIEf2D7bgwNxo8PHlryIg==/dk.madsbangh.openxrgodot44dev3xrvendors3-gcPC0D20JLREx-pKLKAYbw==/base.apk!libmonosgen-2.0.so (BuildId: 8856ea79579fb852f0145221b525a360d7448dc6)
03-10 16:46:29.861 20171 20171 F DEBUG   :       #01 pc 0000000000290130  /data/app/~~YgIEf2D7bgwNxo8PHlryIg==/dk.madsbangh.openxrgodot44dev3xrvendors3-gcPC0D20JLREx-pKLKAYbw==/base.apk!libmonosgen-2.0.so (BuildId: 8856ea79579fb852f0145221b525a360d7448dc6)
03-10 16:46:29.861 20171 20171 F DEBUG   :       #02 pc 00000000016bcaf4  /data/app/~~YgIEf2D7bgwNxo8PHlryIg==/dk.madsbangh.openxrgodot44dev3xrvendors3-gcPC0D20JLREx-pKLKAYbw==/base.apk!libgodot_android.so
03-10 16:46:29.861 20171 20171 F DEBUG   :       #03 pc 00000000016a80d0  /data/app/~~YgIEf2D7bgwNxo8PHlryIg==/dk.madsbangh.openxrgodot44dev3xrvendors3-gcPC0D20JLREx-pKLKAYbw==/base.apk!libgodot_android.so
03-10 16:46:29.861 20171 20171 F DEBUG   :       #04 pc 0000000003d4dbdc  /data/app/~~YgIEf2D7bgwNxo8PHlryIg==/dk.madsbangh.openxrgodot44dev3xrvendors3-gcPC0D20JLREx-pKLKAYbw==/base.apk!libgodot_android.so
03-10 16:46:29.861 20171 20171 F DEBUG   :       #05 pc 0000000000f7ba34  /data/app/~~YgIEf2D7bgwNxo8PHlryIg==/dk.madsbangh.openxrgodot44dev3xrvendors3-gcPC0D20JLREx-pKLKAYbw==/base.apk!libgodot_android.so
03-10 16:46:29.861 20171 20171 F DEBUG   :       #06 pc 0000000000f45740  /data/app/~~YgIEf2D7bgwNxo8PHlryIg==/dk.madsbangh.openxrgodot44dev3xrvendors3-gcPC0D20JLREx-pKLKAYbw==/base.apk!libgodot_android.so (Java_org_godotengine_godot_GodotLib_step+100)
03-10 16:46:29.861 20171 20171 F DEBUG   :       #07 pc 0000000000222244  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: 627076cb02d4f95f833890d812b0a59c)
03-10 16:46:29.861 20171 20171 F DEBUG   :       #08 pc 0000000000211608  /apex/com.android.art/lib64/libart.so (nterp_helper+152) (BuildId: 627076cb02d4f95f833890d812b0a59c)
03-10 16:46:29.861 20171 20171 F DEBUG   :       #09 pc 000000000025428c  [anon:dalvik-classes.dex extracted in memory from /data/app/~~YgIEf2D7bgwNxo8PHlryIg==/dk.madsbangh.openxrgodot44dev3xrvendors3-gcPC0D20JLREx-pKLKAYbw==/base.apk] (org.godotengine.godot.gl.GodotRenderer.onDrawFrame+20)
03-10 16:46:29.861 20171 20171 F DEBUG   :       #10 pc 00000000002132e4  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 627076cb02d4f95f833890d812b0a59c)
03-10 16:46:29.861 20171 20171 F DEBUG   :       #11 pc 00000000002534f2  [anon:dalvik-classes.dex extracted in memory from /data/app/~~YgIEf2D7bgwNxo8PHlryIg==/dk.madsbangh.openxrgodot44dev3xrvendors3-gcPC0D20JLREx-pKLKAYbw==/base.apk] (org.godotengine.godot.gl.GLSurfaceView$GLThread.guardedRun+1034)
03-10 16:46:29.861 20171 20171 F DEBUG   :       #12 pc 00000000002124c4  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 627076cb02d4f95f833890d812b0a59c)
03-10 16:46:29.861 20171 20171 F DEBUG   :       #13 pc 0000000000253a30  [anon:dalvik-classes.dex extracted in memory from /data/app/~~YgIEf2D7bgwNxo8PHlryIg==/dk.madsbangh.openxrgodot44dev3xrvendors3-gcPC0D20JLREx-pKLKAYbw==/base.apk] (org.godotengine.godot.gl.GLSurfaceView$GLThread.run+52)
03-10 16:46:29.861 20171 20171 F DEBUG   :       #14 pc 0000000000218964  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 627076cb02d4f95f833890d812b0a59c)
03-10 16:46:29.861 20171 20171 F DEBUG   :       #15 pc 0000000000284060  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+184) (BuildId: 627076cb02d4f95f833890d812b0a59c)
03-10 16:46:29.861 20171 20171 F DEBUG   :       #16 pc 00000000006181e8  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+460) (BuildId: 627076cb02d4f95f833890d812b0a59c)
03-10 16:46:29.861 20171 20171 F DEBUG   :       #17 pc 00000000006667f0  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1164) (BuildId: 627076cb02d4f95f833890d812b0a59c)
03-10 16:46:29.861 20171 20171 F DEBUG   :       #18 pc 00000000000eb810  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204) (BuildId: 3bbdd75b86bd9c27dace601261a1a6b1)
03-10 16:46:29.861 20171 20171 F DEBUG   :       #19 pc 000000000008b06c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 3bbdd75b86bd9c27dace601261a1a6b1)
03-10 16:46:29.910 19945 20075 F libc    : FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x75ba58af98)
```

### Minimal reproduction project (MRP)

I've attached the project made with Godot v4.4-stable (mono)

[repro-godot-4.4-stable.zip](https://github.com/user-attachments/files/19166599/repro-godot-4.4-stable.zip)

### LINKED ISSUE #104721: [4.4.1-stable][.NET] Android app crashes at startup
### Tested versions

Tested Versions:

4.4.1-stable
4.4.1-rc2

.NET 9
.NET 8

### System information

Godot v4.4.1.stable.mono - Windows 11 (build 26100) - Vulkan (Forward+) 

### Issue description

Android app crashes at startup

### Steps to reproduce

When the Android app crashes at startup, it happens unexpectedly for the first time.  After the 1st crash, subsequent loading of the app also crashes at startup.  After the 1st crash, even rebuilding and doing subsequent remote deploying with Gradle build, the app also crashes on the Android.  To fix the crashing at startups, I would have to manually uninstall the app from the Android device, and then do a remote deploy.

There is a certain odd behavior that I noticed when the 1st crash happens.  Using remote deploy with Gradle build  when developing throughout the day, the app works fine.  But when I disconnect the Android device from my computer at the end of the day, and then try to start the app the next morning (8+ hours had passed), that is when the 1st crash happens.  This behavior has happened twice.

Here are some of the logs from the command 'adb logcat|grep godot'

==== Crash Example 1
> 03-26 22:01:36.698 15584 15714 I godot   : Vulkan 1.1.128 - Forward Mobile - Using Device #0: Qualcomm - Adreno (TM) 618
03-26 22:01:38.341 15584 15714 I godot   :
03-26 22:01:38.766 15584 15714 E godot   : ERROR: BUG: Unreferenced static string to 0: current_animation_changed
03-26 22:01:38.766 15584 15714 E godot   :    at: unref (core/string/string_name.cpp:142)
03-26 22:01:38.769 15584 15714 E godot   : ERROR: BUG: Unreferenced static string to 0: autoshrink_changed
03-26 22:01:38.769 15584 15714 E godot   :    at: unref (core/string/string_name.cpp:142)
03-26 22:01:38.770 15584 15714 E godot   : ERROR: BUG: Unreferenced static string to 0: interface_added
03-26 22:01:38.770 15584 15714 E godot   :    at: unref (core/string/string_name.cpp:144)
03-26 22:01:38.777 15584 15714 E godot   : ERROR: BUG: Unreferenced static string to 0: bus_renamed
03-26 22:01:38.777 15584 15714 E godot   :    at: unref (core/string/string_name.cpp:144)
03-26 22:01:38.777 15584 15714 E godot   : ERROR: BUG: Unreferenced static string to 0: bus_layout_changed
03-26 22:01:38.777 15584 15714 E godot   :    at: unref (core/string/string_name.cpp:144)
03-26 22:01:38.779 15584 15714 E godot   : ERROR: BUG: Unreferenced static string to 0: node_changed
03-26 22:01:38.779 15584 15714 E godot   :    at: unref (core/string/string_name.cpp:142)
03-26 22:01:38.783 15584 15714 E godot   : ERROR: BUG: Unreferenced static string to 0: animation_player_changed
03-26 22:01:38.783 15584 15714 E godot   :    at: unref (core/string/string_name.cpp:142)
03-26 22:01:38.785 15584 15714 E godot   : ERROR: BUG: Unreferenced static string to 0: animation_libraries_updated
03-26 22:01:38.785 15584 15714 E godot   :    at: unref (core/string/string_name.cpp:142)
03-26 22:01:38.785 15584 15714 E godot   : ERROR: BUG: Unreferenced static string to 0: mixer_applied
03-26 22:01:38.785 15584 15714 E godot   :    at: unref (core/string/string_name.cpp:142)
03-26 22:01:38.785 15584 15714 E godot   : ERROR: BUG: Unreferenced static string to 0: mixer_updated
03-26 22:01:38.785 15584 15714 E godot   :    at: unref (core/string/string_name.cpp:142)
03-26 22:01:38.785 15584 15714 E godot   : ERROR: BUG: Unreferenced static string to 0: animation_list_changed
03-26 22:01:38.785 15584 15714 E godot   :    at: unref (core/string/string_name.cpp:142)
03-26 22:01:38.785 15584 15714 E godot   : ERROR: BUG: Unreferenced static string to 0: caches_cleared
03-26 22:01:38.785 15584 15714 E godot   :    at: unref (core/string/string_name.cpp:142)
03-26 22:01:38.790 15584 15714 E godot   : ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketLargeE
03-26 22:01:38.790 15584 15714 E godot   :    at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
03-26 22:01:38.790 15584 15714 E godot   : ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools12BucketMediumE
03-26 22:01:38.790 15584 15714 E godot   :    at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
03-26 22:01:38.790 15584 15714 E godot   : ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketSmallE
03-26 22:01:38.790 15584 15714 E godot   :    at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
03-26 22:01:38.791 15584 15714 E godot   : ERROR: 6 RID allocations of type '23NavMeshGeometryParser3D' were leaked at exit.

==== Crash Example 2
> 03-27 20:49:05.239 14944 14986 I godot   : Vulkan 1.1.128 - Forward Mobile - Using Device #0: Qualcomm - Adreno (TM) 618
03-27 20:49:06.390 14944 14986 I godot   :
03-27 20:49:06.955 14944 14986 E godot   : ERROR: BUG: Unreferenced static string to 0: current_animation_changed
03-27 20:49:06.955 14944 14986 E godot   :    at: unref (core/string/string_name.cpp:142)
03-27 20:49:06.958 14944 14986 E godot   : ERROR: BUG: Unreferenced static string to 0: autoshrink_changed
03-27 20:49:06.958 14944 14986 E godot   :    at: unref (core/string/string_name.cpp:142)
03-27 20:49:06.958 14944 14986 E godot   : ERROR: BUG: Unreferenced static string to 0: interface_added
03-27 20:49:06.958 14944 14986 E godot   :    at: unref (core/string/string_name.cpp:144)
03-27 20:49:06.965 14944 14986 E godot   : ERROR: BUG: Unreferenced static string to 0: bus_renamed
03-27 20:49:06.965 14944 14986 E godot   :    at: unref (core/string/string_name.cpp:144)
03-27 20:49:06.965 14944 14986 E godot   : ERROR: BUG: Unreferenced static string to 0: bus_layout_changed
03-27 20:49:06.965 14944 14986 E godot   :    at: unref (core/string/string_name.cpp:144)
03-27 20:49:06.966 14944 14986 E godot   : ERROR: BUG: Unreferenced static string to 0: node_changed
03-27 20:49:06.966 14944 14986 E godot   :    at: unref (core/string/string_name.cpp:142)
03-27 20:49:06.970 14944 14986 E godot   : ERROR: BUG: Unreferenced static string to 0: animation_player_changed
03-27 20:49:06.970 14944 14986 E godot   :    at: unref (core/string/string_name.cpp:142)
03-27 20:49:06.972 14944 14986 E godot   : ERROR: BUG: Unreferenced static string to 0: animation_libraries_updated
03-27 20:49:06.972 14944 14986 E godot   :    at: unref (core/string/string_name.cpp:142)
03-27 20:49:06.972 14944 14986 E godot   : ERROR: BUG: Unreferenced static string to 0: mixer_applied
03-27 20:49:06.972 14944 14986 E godot   :    at: unref (core/string/string_name.cpp:142)
03-27 20:49:06.972 14944 14986 E godot   : ERROR: BUG: Unreferenced static string to 0: mixer_updated
03-27 20:49:06.972 14944 14986 E godot   :    at: unref (core/string/string_name.cpp:142)
03-27 20:49:06.972 14944 14986 E godot   : ERROR: BUG: Unreferenced static string to 0: animation_list_changed
03-27 20:49:06.972 14944 14986 E godot   :    at: unref (core/string/string_name.cpp:142)
03-27 20:49:06.972 14944 14986 E godot   : ERROR: BUG: Unreferenced static string to 0: caches_cleared
03-27 20:49:06.972 14944 14986 E godot   :    at: unref (core/string/string_name.cpp:142)
03-27 20:49:06.976 14944 14986 E godot   : ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketLargeE
03-27 20:49:06.976 14944 14986 E godot   :    at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
03-27 20:49:06.976 14944 14986 E godot   : ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools12BucketMediumE
03-27 20:49:06.976 14944 14986 E godot   :    at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
03-27 20:49:06.976 14944 14986 E godot   : ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketSmallE
03-27 20:49:06.976 14944 14986 E godot   :    at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
03-27 20:49:06.976 14944 14986 E godot   : ERROR: 6 RID allocations of type '23NavMeshGeometryParser3D' were leaked at exit.

==== Crash Example (subsequent crashes after the 1st crashes)
> 03-27 20:52:42.993 15303 15354 I godot   : Vulkan 1.1.128 - Forward Mobile - Using Device #0: Qualcomm - Adreno (TM) 618
03-27 20:52:44.262 15303 15354 I godot   :
03-27 20:52:44.627 15303 15354 E godot   : ERROR: BUG: Unreferenced static string to 0: current_animation_changed
03-27 20:52:44.627 15303 15354 E godot   :    at: unref (core/string/string_name.cpp:142)

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #105142: ERROR: .NET: Failed to get GodotPlugins initialization function pointer  5745  5772 E godot : at: initialize_coreclr_and_godot_plugins (modules/mono/mono_gd/gd_mono.cpp:485)
### Tested versions

4.4 stable.mono.official

### System information

Android 13 / Fedora 42

### Issue description

After exporting an android .apk and testing on a android device I noticed sometimes the application just launches to the splash screen then closes itself. (well specifically seems to minimise itself and is still in the android menu), sometimes it launches ok and you can use the app as intended.

I enabled debugging on my android device, device connects to adb, enabled debugging `adb logcat -s godot` and this is the output, when launching the application:

```
--------- beginning of main
04-08 17:09:17.553  5745  5772 I godot   : Godot Engine v4.4.stable.mono.official.4c311cbee - https://godotengine.org
04-08 17:09:17.734  5745  5772 I godot   : OpenGL API OpenGL ES 3.2 v1.r40p0-01eac0.40e4defc2c2be7601a8ecd13c8057aa1 - Compatibility - Using Device: ARM - Mali-G57
04-08 17:09:17.759  5745  5772 I godot   : 
04-08 17:09:19.660  5745  5772 E godot   : ERROR: .NET: Failed to get GodotPlugins initialization function pointer
04-08 17:09:19.660  5745  5772 E godot   :    at: initialize_coreclr_and_godot_plugins (modules/mono/mono_gd/gd_mono.cpp:485)
04-08 17:09:19.660  5745  5772 E godot   : ERROR: .NET: Failed to load hostfxr
04-08 17:09:19.660  5745  5772 E godot   :    at: initialize (modules/mono/mono_gd/gd_mono.cpp:549)
04-08 17:09:20.257  5745  5772 E godot   : ERROR: BUG: Unreferenced static string to 0: current_animation_changed
04-08 17:09:20.257  5745  5772 E godot   :    at: unref (core/string/string_name.cpp:142)
04-08 17:09:29.910  5813  5841 I godot   : Godot Engine v4.4.stable.mono.official.4c311cbee - https://godotengine.org
04-08 17:09:30.039  5813  5841 I godot   : OpenGL API OpenGL ES 3.2 v1.r40p0-01eac0.40e4defc2c2be7601a8ecd13c8057aa1 - Compatibility - Using Device: ARM - Mali-G57
04-08 17:09:30.061  5813  5841 I godot   : 
04-08 17:09:30.597  5813  5841 E godot   : ERROR: .NET: Failed to get GodotPlugins initialization function pointer
04-08 17:09:30.597  5813  5841 E godot   :    at: initialize_coreclr_and_godot_plugins (modules/mono/mono_gd/gd_mono.cpp:485)
04-08 17:09:30.597  5813  5841 E godot   : ERROR: .NET: Failed to load hostfxr
04-08 17:09:30.597  5813  5841 E godot   :    at: initialize (modules/mono/mono_gd/gd_mono.cpp:549)
04-08 17:09:31.709  5813  5841 E godot   : ERROR: BUG: Unreferenced static string to 0: current_animation_changed
04-08 17:09:31.709  5813  5841 E godot   :    at: unref (core/string/string_name.cpp:142)
04-08 17:09:47.868  5865  5895 I godot   : Godot Engine v4.4.stable.mono.official.4c311cbee - https://godotengine.org
04-08 17:09:47.988  5865  5895 I godot   : OpenGL API OpenGL ES 3.2 v1.r40p0-01eac0.40e4defc2c2be7601a8ecd13c8057aa1 - Compatibility - Using Device: ARM - Mali-G57
04-08 17:09:48.011  5865  5895 I godot   : 
04-08 17:09:48.542  5865  5895 E godot   : ERROR: .NET: Failed to get GodotPlugins initialization function pointer
04-08 17:09:48.542  5865  5895 E godot   :    at: initialize_coreclr_and_godot_plugins (modules/mono/mono_gd/gd_mono.cpp:485)
04-08 17:09:48.542  5865  5895 E godot   : ERROR: .NET: Failed to load hostfxr
04-08 17:09:48.542  5865  5895 E godot   :    at: initialize (modules/mono/mono_gd/gd_mono.cpp:549)
04-08 17:09:49.664  5865  5895 E godot   : ERROR: BUG: Unreferenced static string to 0: current_animation_changed
04-08 17:09:49.665  5865  5895 E godot   :    at: unref (core/string/string_name.cpp:142)
04-08 17:09:58.124  5984  6012 I godot   : Godot Engine v4.4.stable.mono.official.4c311cbee - https://godotengine.org
04-08 17:09:58.259  5984  6012 I godot   : OpenGL API OpenGL ES 3.2 v1.r40p0-01eac0.40e4defc2c2be7601a8ecd13c8057aa1 - Compatibility - Using Device: ARM - Mali-G57
04-08 17:09:58.295  5984  6012 I godot   : 
04-08 17:09:58.838  5984  6012 E godot   : ERROR: .NET: Failed to get GodotPlugins initialization function pointer
04-08 17:09:58.838  5984  6012 E godot   :    at: initialize_coreclr_and_godot_plugins (modules/mono/mono_gd/gd_mono.cpp:485)
04-08 17:09:58.838  5984  6012 E godot   : ERROR: .NET: Failed to load hostfxr
04-08 17:09:58.838  5984  6012 E godot   :    at: initialize (modules/mono/mono_gd/gd_mono.cpp:549)
04-08 17:09:59.917  5984  6012 E godot   : ERROR: BUG: Unreferenced static string to 0: current_animation_changed
04-08 17:09:59.917  5984  6012 E godot   :    at: unref (core/string/string_name.cpp:142)
04-08 17:10:02.078  6036  6064 I godot   : Godot Engine v4.4.stable.mono.official.4c311cbee - https://godotengine.org
04-08 17:10:02.207  6036  6064 I godot   : OpenGL API OpenGL ES 3.2 v1.r40p0-01eac0.40e4defc2c2be7601a8ecd13c8057aa1 - Compatibility - Using Device: ARM - Mali-G57
...
```

On the last attempt the .apk launched and ran as intended.

### Steps to reproduce

I'm really not too sure how to reliably reproduce but I welcome debugging suggestions. 

But essentially:
1) Export  an Android .apk as `arm64-v8a` with a target `SDK of 34`
2) Launch the application on android device
3) Close it (Swipe Up)
4) Keep opening and closing until the issue appears.

### Minimal reproduction project (MRP)

.

### PR DESCRIPTION
**Pull request by raulsntos**
Avoids using assemblies extracted to a temporary directory in Android.

- Fixes https://github.com/godotengine/godot/issues/103915
- Fixes https://github.com/godotengine/godot/issues/104721
- Fixes https://github.com/godotengine/godot/issues/105142

---

| :robot: Android templates for testing |
|:-:|
| [Godot_v4.5-android-no-copy_mono_export_templates.tpz](https://github.com/raulsntos/godot/releases/download/android-nocopy/Godot_v4.5-android-no-copy_mono_export_templates.tpz) |

### CODE REVIEW

**Review by dsnopek — APPROVED** [review]
Thanks!

I'm not really qualified to review the code, but this does appear to fix the issue in my testing. I just tried launch my test project 20 more times using a build from this PR, and didn't get a single crash :-)

File: modules/mono/thirdparty/mono_delegates.h [hunk 1]
```diff
@@ -0,0 +1,38 @@
+// Adapted from monovm.h and assembly-functions.h to match coreclr_delegates.h.
+
+// https://github.com/dotnet/runtime/blob/27a7fe5c4bbe0762c231b2a46162e60ee04f3cde/src/mono/mono/mini/monovm.h
+// https://github.com/dotnet/runtime/blob/27a7fe5c4bbe0762c231b2a46162e60ee04f3cde/src/native/public/mono/metadata/details/assembly-functions.h
+
+#ifndef _MONO_DELEGATES_H_
+#define _MONO_DELEGATES_H_
```
Comment (syntaxerror247) [inline modules/mono/thirdparty/mono_delegates.h:7]: It should be now `#pragma once`

Comment (syntaxerror247) [inline modules/mono/thirdparty/mono_delegates.h:7]: I guess it should be changed, we now use `#pragma once`.

**Review by syntaxerror247 — APPROVED** [review]
Looks good to me! 
I’m not much familiar with .NET, but I did a general code review, and `load_assembly_from_pck` seems good. Also based on the testing from @dsnopek and @cyberschema https://github.com/godotengine/godot/issues/104721#issuecomment-2798861466, it fixes the issue.

File: modules/mono/thirdparty/mono_delegates.h (hunk 1 above)
Comment (raulsntos) [reply modules/mono/thirdparty/mono_delegates.h:7]: From what I can see we still use `#ifndef #define` in thirdparty code. I guess we usually avoid modifying thirdparty code too much. Should I still change this?

Comment (syntaxerror247) [reply modules/mono/thirdparty/mono_delegates.h:7]: Since we have this in other thirdparty code as well, I suppose it's fine.

**Comment by Repiteo** [comment]
Thanks!
