### PR TITLE
Make FileSystem dock set its path to the base folder of files after changes

### LINKED ISSUE #45842: Deleting or moving a file causes the FileSystem browser to jump to the res:// directory
**Godot version:**
3.2.4 RC 1

**OS/device including version:**
Windows 10

**Issue description:**
Deleting or moving a file causes the `FileSystem` browser to jump to the `res://` directory.
This is a regression from 3.2.4 Beta 6.
The `FileSystem` should stay in the same folder when something is deleted or moved.

**Steps to reproduce:**
1. Create some nested sub-folders.
2. Delete or move the most deeply-nested folder.
3. Watch the `FileSystem` jump to the `res://` directory.

**Minimal reproduction project:**
[Deletion Bug.zip](https://github.com/godotengine/godot/files/5948995/Deletion.Bug.zip)

### PR DESCRIPTION
**Pull request by YeldhamDev**
Changed it from the previous behavior of always setting it to `res://`, to the base directory of the first selected file.

Closes #45842.

### CODE REVIEW

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -1411,14 +1411,28 @@ void FileSystemDock::_make_scene_confirm() {
 void FileSystemDock::_file_removed(String p_file) {
 	emit_signal("file_removed", p_file);
 
-	path = "res://";
+	// Find the closest parent directory available, in case multiple items were deleted along the same path.
+	path = p_file.get_base_dir();
+	DirAccess *da = DirAccess::create(DirAccess::ACCESS_RESOURCES);
```
Comment (akien-mga) [inline editor/filesystem_dock.cpp:1416]: Use `DirAccessRef`, then you don't need to `memdelete()` it.

Comment (YeldhamDev) [reply editor/filesystem_dock.cpp]: Done!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
