### PR TITLE
Make InputEventAction as_text() return the text of the first valid event for the action.

### LINKED ISSUE #67715: InputEventAction does not persist inside Shortcut for MenuButton's Popup
### Godot version

4.0 beta 3

### System information

Windows 10, Vulkan, Intel(R) UHD Graphics and NVIDIA GeForce RTX 3060 Laptop GPU

### Issue description

I'm trying to add a shortcut to an item in a MenuButton's popup in Godot 4 Beta 3. Using an object of the type InputEventAction causes the following message to appear instead of the expected "Ctrl + O".

image

The work-around was to use InputEventKey instead.

### Steps to reproduce

Create an action called "file_open" in the input map.
Script attached to a MenuButton:
```gdscript
func _ready():
	var shortcut_open = Shortcut.new()
	var input_event_action = InputEventAction.new()
	input_event_action.action = "file_open"
	shortcut_open.events = [input_event_action ]
	
	var popup = get_popup()
	popup.set_item_shortcut(1, shortcut_open, false)
```
I also tried keeping the shortcut_open and input_event_action at the top of the script, outside the scope of _ready().

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by EricEzaM**
Fixes #67715

image

Not sure if `to_string()` should get the same treatment.

### CODE REVIEW

File: core/input/input_event.cpp [hunk 1]
```diff
@@ -1356,7 +1356,18 @@ bool InputEventAction::action_match(const Ref<InputEvent> &p_event, bool p_exact
...
+	const List<Ref<InputEvent>> *events = InputMap::get_singleton()->action_get_events(action);
+	if (!events) {
+		return String();
+	}
+
+	for (const List<Ref<InputEvent>>::Element *E = events->front(); E; E = E->next()) {
+		if (E->get().is_valid()) {
+			return E->get()->as_text();
+		}
+	}
```
Comment (Sauermann) [inline core/input/input_event.cpp:1368]: Couldn't this loop be simplified to:
``` C++
	for (Ref<InputEvent> E : *events) {
		if (E.is_valid()) {
			return E->as_text();
		}
	}
```

Comment (EricEzaM) [reply core/input/input_event.cpp:1368]: Yep, used the old way for some reason here...

**Review by bruvzg — APPROVED** [review]
I'm not entirely sure about empty strings, maybe it should return `(Empty action)` or something like this? Otherwise, seems good.

**Review by groud — APPROVED** [review]
Approved in PR review meeting. It should be good to merge.

**Comment by EricEzaM** [comment]
I agree with bruvzg and will make that change before merge. Hopefully ~10hrs from the time of this comment.

**Comment by EricEzaM** [comment]
Actually on the other hand, if someone has a bunch of items in a popup menu (like the issue) and they are bound to an InputEventAction, and it has no events I think it is better to display as blank rather than all being "(Empty Action)".

So for that reason I am ok to leave it as it is.

**Comment by groud** [comment]
On a side note, I forgot to mention we also discussed about renaming the function. It's not clear that "as_text" is only used to display an event as a "shortcut string". It is kind of conflicting with `InputEvent::to_string()` too.

Personally, I think we could rename the function somehow like `as_shortcut_string()`.

**Comment by akien-mga** [comment]
Thanks!
