### PR TITLE
Fix packed scene translation parser missing strings.

### LINKED ISSUE #74194: Localization POT generation does not regognize text on instanced nodes.
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Arch Linux

### Issue description

Localization POT generation does not regognize text on instanced nodes.

### Steps to reproduce

1. Create a 2D main scene
2. Create a scene with a button as the single node
3. Add the button scene as a instance to the main scene and edit the button instances text
4. Add a button node (not the instance) to the main scene and edit the buttons text
5. Go to Project Settings -> Localization -> POT generation, Add the main scene and generate POT file
6. observe the POT file and see there is no localization ID for the instanced buttons text

### Minimal reproduction project

[localization_instances.zip](https://github.com/godotengine/godot/files/10865767/localization_instances.zip)

### LINKED ISSUE #79144: POT generation with saved scenes loaded from another scene doesn't work
### Godot version

v4.1.stable.official [970459615]

### System information

Windows 11

### Issue description

Godot doesn't recognize `auto_translate` nodes if they are from a saved scened.

### Steps to reproduce

Write a scene with two labels: the built-in `Label` and a custom scene that inherits from `Label`. Then try to generate the `.pot` file.

### Minimal reproduction project

[gettext_test.zip](https://github.com/godotengine/godot/files/11979493/gettext_test.zip)

### LINKED ISSUE #88017: Menu- and OptionButton item text strings don't get included in POT generation
### Tested versions

Probably reproducible in all Godot version , tested 4.0.3 , 4.2.2rc
Also looked at 3.5 and found the old scene file format that the POT generator is trying to use, bot no POT generator.

### System information

Windows 10

### Issue description

The POT generator is not including item texts from `MenuButton` or `OptionButton`, because its expecting an old scene file format. It's trying to find a `items` property with an array of items, which doesn't exist since 4.0. 

Old scene format POT gen is built for:
```gd
[node name="MenuButton" type="MenuButton" parent="."]
margin_right = 147.0
margin_bottom = 20.0
items = [ "Hello world!", null, 0, false, false, 0, 0, null, "", false ]
```
New scene format that POT gen doesn't know about:
```gd
[node name="MenuButton" type="MenuButton" parent="."]
layout_mode = 0
offset_right = 8.0
offset_bottom = 8.0
item_count = 1
popup/item_0/text = "Hello world!"
popup/item_0/id = 0
```
The solution would be to include properties that match the pattern "popup/*/text".

Relevant source code:
https://github.com/godotengine/godot/blob/d3352813ea44447bfbf135efdec23acc4d1d3f89/editor/plugins/packed_scene_translation_parser_plugin.cpp#L149
Note: Simply putting this in a check `if (!property_name.match("popup/*/text"))` fixes the problem, because it will find the property as a string value.
https://github.com/godotengine/godot/blob/d3352813ea44447bfbf135efdec23acc4d1d3f89/editor/plugins/packed_scene_translation_parser_plugin.cpp#L95-L97
https://github.com/godotengine/godot/blob/d3352813ea44447bfbf135efdec23acc4d1d3f89/editor/plugins/packed_scene_translation_parser_plugin.cpp#L111-L119

### Steps to reproduce

Make a MenuButton or OptionButton with items, include the scene in POT generation and generate POT.
-> The generated POT will not include item texts.

### Minimal reproduction project (MRP)

Not really needed but here is a simple MRP:
[MenuButton POT MRP.zip](https://github.com/godotengine/godot/files/14180566/MenuButton.POT.MRP.zip)

### PR DESCRIPTION
**Pull request by Kiisu-Master**
This is my attempt to fix the POT generator missing strings. 

- Made a special case for when the node type is empty, it will open the scene and get the type from there. It might even make sense to parse the whole instanced scene too, but it's possible to work around by just adding it to the files list.
(fixes #74194, probably fixes #79144)
- Removed the `MenuButton` and `OptionButton` case, as it's attempting to parse the old 3.x scene format.
- Added a function that will tell if the property of the node should be included. It will now match the property name against all properties in the lookup list, which allows wildcard for `popup/item_0/text` property of the nodes with popup menus.
(fixes #88017)

I'm planning to add the lookup and exclude properties in the project settings, but i don't know how to do that yet.
This is my first time really working with c++ so **i have no idea really what im doing.**
It might be that the variable names im using are wrong.
I ported this code from a custom translation parser i made in gdscript.

### CODE REVIEW

File: editor/plugins/packed_scene_translation_parser_plugin.h [hunk 1]
```diff
@@ -43,6 +43,7 @@ class PackedSceneEditorTranslationParserPlugin : public EditorTranslationParserP
 
 public:
 	virtual Error parse_file(const String &p_path, Vector<String> *r_ids, Vector<Vector<String>> *r_ids_ctx_plural) override;
+	bool match_property(String &property_name, String &node_type);
```
Comment (AThousandShips) [inline editor/plugins/packed_scene_translation_parser_plugin.h:46]:
```suggestion
	bool match_property(const String &property_name, const String &node_type);
```

**Comment by AThousandShips** [comment]
> as it's attempting to parse the old 3.x scene format.

What do you mean by this? This isn't a backwards compatible feature as far as I can tell

**Review by YeldhamDev — APPROVED** [review]
> It might even make sense to parse the whole instanced scene too

I would recommend against that, since it could lead to parsing of unwanted strings. :wink:

Overall, nice job!

File: editor/plugins/packed_scene_translation_parser_plugin.cpp [hunk 2]
```diff
@@ -167,14 +168,33 @@ Error PackedSceneEditorTranslationParserPlugin::parse_file(const String &p_path,
 	return OK;
 }
 
+bool PackedSceneEditorTranslationParserPlugin::match_property(const String &p_property_name, const String &p_node_type) {
+	for (const KeyValue<String, Vector<String>> &exception : exception_list) {
+		String exception_node_type = exception.key;
```
Comment (AThousandShips) [inline editor/plugins/packed_scene_translation_parser_plugin.cpp:173]:
```suggestion
		const String &exception_node_type = exception.key;
```

File: editor/plugins/packed_scene_translation_parser_plugin.cpp [hunk 3]
```diff
@@ -167,14 +168,33 @@ Error PackedSceneEditorTranslationParserPlugin::parse_file(const String &p_path,
...
+		if (ClassDB::is_parent_class(p_node_type, exception_node_type)) {
+			Vector<String> exception_properties = exception.value;
+			for (int p = 0; p < exception_properties.size(); p++) {
+				String exception_property = exception_properties[p];
```
Comment (AThousandShips) [inline editor/plugins/packed_scene_translation_parser_plugin.cpp:177]:
```suggestion
			const Vector<String> &exception_properties = exception.value;
			for (const String &exception_property : exception_properties) {
```

**Review by AThousandShips — APPROVED** [review]

**Comment by Kiisu-Master** [comment]
> > It might even make sense to parse the whole instanced scene too
> 
> I would recommend against that, since it could lead to parsing of unwanted strings. 😉
> 
> Overall, nice job!

BTW the same could happen with the inclusion of all `*_text` properties. It will include more strings from nodes inheriting `AcceptDialog`, but also user created nodes which might use this name ending for other purposes. I know there is some properties that end with `_text` that arent strings, but that's taken care of with the type check. I hope it doesn't cause problems.

File: editor/plugins/packed_scene_translation_parser_plugin.cpp [hunk 4]
```diff
@@ -58,6 +58,15 @@ Error PackedSceneEditorTranslationParserPlugin::parse_file(const String &p_path,
 		String node_type = state->get_node_type(i);
 		String parent_path = state->get_node_path(i, true);
 
+		// Handle instanced scenes.
+		if (node_type.is_empty()) {
+			Ref<PackedScene> instance = state->get_node_instance(i);
+			if (!instance.is_valid()) {
```
Comment (AThousandShips) [inline editor/plugins/packed_scene_translation_parser_plugin.cpp:64]:
```suggestion
			if (instance.is_valid()) {
```

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
