### PR TITLE
Fix hiDPI scaling support in `get_real_window_size` and `set_window.size`

### LINKED ISSUE #26947: get_window_size and set_window_size don't work correctly with hiDPI enabled
**Godot version:**
3.1.rc2.official

**OS/device including version:**
MacOS Mojave 10.14.13
MacBook Pro 2015 13"

**Issue description:**
I decided to save screen size and position on exit, and restore their values on start. This doesn't work when using HiDPI, since OS.get_window_size gives pixel size, and OS_set_window_size expects HiDPI values.
Kapture 2019-03-12 at 0 09 17

**Steps to reproduce:**
While configuring your project with HiDPI support:
`OS.set_window_size(OS.get_window_size())
`

**Minimal reproduction project:**

[New Game Project.zip](https://github.com/godotengine/godot/files/2955015/New.Game.Project.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Also fixes `set_window_maximized` and `center_window` behaviour on retina displays.

Fixes #26947

### CODE REVIEW

File: platform/osx/os_osx.mm [hunk 1]
```diff
@@ -2270,12 +2270,12 @@ static int get_screen_index(NSScreen *screen) {
...
 
 	NSRect frame = [window_object frame];
-	return Size2(frame.size.width, frame.size.height);
+	return Size2(frame.size.width, frame.size.height) * _display_scale();
 }
 
 void OS_OSX::set_window_size(const Size2 p_size) {
 
-	Size2 size = p_size;
+	Size2 size = p_size / _display_scale();
```
Comment (samgreen) [inline platform/osx/os_osx.mm]: I believe that `setFrame` will handle the `contentScaleFactor` of the `NSWindow`. The way this is written, if I'm on a retina display to get 1080, I must `set_window_size` with `3840, 2160` which seems unintuitive to me.

Comment (bruvzg) [reply platform/osx/os_osx.mm]: `setFrame` do, but currently all other window position and size do this kind of scaling (only is project is configured to support hiDPI), we should either add it to these two or remove it everywhere else. Also, all internal measurements and input events use real pixel coordinates.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.1.
