### PR TITLE
GIProbe::bake(): special handling of spatial

### LINKED ISSUE #28508: Bake() Method of GIProbe has no effect on runtime
**Godot version:**
3.1 release

**OS/device including version:**
Current Windows 10

**Issue description:**
My goal was to experiment with the GI capability of the engine. The experiment was if it can bake not-moving objects (with not moving light sources) at runtime (not in the editor).

*Result:*

Baking from GDScript of a dynamic scene is currently not possible.

I expected that it would at least bake it at runtime.

**Steps to reproduce:**

* add GIProbe
* add light source (with GI contribution >0.0)
* add GDScript which spawns scene objects where the "Use In Baked" attribute is enabled and calls the .Bake() method of the GIProbe in the scene

### PR DESCRIPTION
**Pull request by PtrMan**
I expected that the engine would use dynamically placed meshes for the baking of the GI.

A issue was that embeded scene Nodes are simply ignored, because they have no owner.

So this PR fixes this by just checking for this special case.

Fixes #28508

### CODE REVIEW

**Comment by akien-mga** [comment]
Some comments from IRC:
```
16:36 <Akien> reduz: Can you make sense of this bugfix? #28526 I don't understand why Spatial needs a special case
16:36 <IssueBot> #28526: GIProbe::bake(): special handling of spatial | https://git.io/fjG5X
16:39 <reduz> Akien: i don't understand it either
16:40 <reduz> oh because it misses the owners
16:40 <reduz> i am still not sure why you would want to use that in runtime, with the changes jfons is doing, it will definitely not work
```

WDYT @JFonS?

**Comment by JFonS** [comment]
Sorry for the extremely late response.

I'm not 100% sure of the use case either, but I think we can safely remove the owner check.

File: scene/3d/gi_probe.cpp [hunk 1]
```diff
@@ -387,8 +387,10 @@ void GIProbe::_find_meshes(Node *p_at_node, List<PlotMesh> &plot_meshes) {
 	for (int i = 0; i < p_at_node->get_child_count(); i++) {
 
 		Node *child = p_at_node->get_child(i);
-		if (!child->get_owner())
-			continue; //maybe a helper
+		if (!Object::cast_to<Spatial>(child)) { // test for Spatial special case is required to allow for dynamically added Scenes at runtime
+			if (!child->get_owner())
+				continue; //maybe a helper
+		}
```
Comment (JFonS) [inline scene/3d/gi_probe.cpp]: I would just remove this whole check. 

`_find_meshses()` only cares about MeshInstances, which inherit from Spatial, so disabling the owner check for Spatials is the same as disabling it for any type of Node. I can't think of any case where un-owned Nodes would break baking, so I think it's safe to just remove the ownership test.

**Comment by akien-mga** [comment]
Force pushed the changes requested by @JFonS.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
