### PR TITLE
Use circular fade instead of linear fade for distance fade

### LINKED ISSUE #53853: Material distance fade is based on depth not distance
### Godot version

3.3.3

### System information

Windows 7

### Issue description

The spatial material distance fade is dependent on the facing angle of the camera, not the distance of the object. I believe this is because the distance fade is going on the depth rather than the distance:
image
This can be an issue in particular if distance fade is used to obscure objects from the player unless very close to them, as the distance of visibility changes drastically depending on the angle it's viewed from.

### Steps to reproduce

Set the distance fade on a spatial material, rotate the camera and observe it become less faded the closer to the edge of the screen and more faded the closer to the center of the screen.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Calinou**
`master` version of https://github.com/godotengine/godot/pull/69959.

This makes distance fade look the same regardless of the camera angle, for all distance fade modes (Pixel Alpha, Pixel Dither, Object Dither). Distance fade now behaves like fog in this regard.

This has a minimal performance cost, but the quality increase is worth it. When viewing a plane that fully covers the screen, I get 215 FPS instead of 218 FPS with Pixel Dither in 4K, but this does not reflect the typical use case of distance fade (which is for LOD purposes). Besides, there are likely other ways to improve dithering efficiency (such as reducing branching or using [interleaved gradient noise](https://github.com/godotengine/godot/pull/50297)).

Thanks to @mrjustaguy for providing the formula here: https://github.com/godotengine/godot-proposals/issues/2963#issuecomment-876559516

This can be cherry-picked without conflicts to the `3.x` branch. I tested this PR on the `3.x` branch on both GLES3 and [GLES2](https://github.com/godotengine/godot/pull/50295), and it works as expected there too. This PR can be merged independently of https://github.com/godotengine/godot/pull/50297 as both can work together.

This closes https://github.com/godotengine/godot/issues/53853 and partially addresses https://github.com/godotengine/godot-proposals/issues/2963.

**Testing project:** [test_distance_fade_circular.zip](https://github.com/godotengine/godot/files/9407071/test_distance_fade_circular.zip)

## Preview

***Note:** These images should be viewed on a desktop device at 1:1 resolution by clicking them. Otherwise, they will not look as expected due to the nature of dithering.*

### Pixel Alpha

Pixel Alpha

### Pixel Dither

Pixel Dither

### CODE REVIEW

File: scene/resources/material.cpp [hunk 1]
```diff
@@ -1104,14 +1104,17 @@ void BaseMaterial3D::_update_shader() {
...
+		// object instead of Z distance), so that the fade is always the same
+		// regardless of the camera angle.
+		// This has a small performance cost, but the quality increase is worth it.
 		if ((distance_fade == DISTANCE_FADE_OBJECT_DITHER || distance_fade == DISTANCE_FADE_PIXEL_DITHER)) {
 			if (!RenderingServer::get_singleton()->is_low_end()) {
 				code += "\t{\n";
 				if (distance_fade == DISTANCE_FADE_OBJECT_DITHER) {
-					code += "\t\tfloat fade_distance = abs((INV_CAMERA_MATRIX * WORLD_MATRIX[3]).z);\n";
-
+					code += "\t\tfloat fade_distance = sqrt(pow((INV_CAMERA_MATRIX * WORLD_MATRIX[3]).z, 2) + pow((INV_CAMERA_MATRIX * WORLD_MATRIX[3]).x, 2) + pow((INV_CAMERA_MATRIX * WORLD_MATRIX[3]).y, 2));\n";
```
Comment (Calinou) [inline scene/resources/material.cpp:1115]: The `sqrt()` is needed to make the effective fade distance about the same as before.

**Comment by PolyVector** [comment]
Orthographic projections should still use a linear fade, or it will cause artifacts while panning.

**Comment by Calinou** [comment]
> Orthographic projections should still use a linear fade, or it will cause artifacts while panning.

I guess I have to apply the same `if` statement as done here: https://github.com/godotengine/godot/blob/a71169c0e0ed7644b959189522535337bdb6cb2b/scene/resources/material.cpp#L678-L680

**Review by clayjohn — CHANGES_REQUESTED** [review]
My suggested changes are functionally equivalent to your code except shorter and much faster.

**Comment by Calinou** [comment]
Rebased and tested again, it works as expected for Pixel Alpha and Pixel Dither. However, Object Dither no longer seems to be faded irrespective of camera angle. Rotating the camera will change the entire object's opacity, which is unexpected.

File: scene/resources/material.cpp (hunk 1 above)
Comment (clayjohn) [reply scene/resources/material.cpp]: Ah, this change seems wrong. The ``.z`` should not be here. Including the ``.z`` makes it the exact same as the original (functionally speaking, it actually produces worse instructions than the original). Removing the ``.z`` makes it the same as your original edit.

<details>
<summary><b>shader ISA disassembly</b></summary>

Disassembly produced in Radeon GPU Analyzer for ``abs(float)``:

```
  v_cvt_pkrtz_f16_f32  v0, abs(s0), lit(0x3ecccccd)     // 000000000028: D52F0100 0001FE00 3ECCCCCD
```

Disassembly produced for ``length(float)``:
```
  v_mul_legacy_f32  v0, s0, s0                          // 000000000028: D5070000 00000000 // this is multiply a variable by itself
  v_sqrt_f32    v0, v0                                  // 000000000030: 7E006700 // then take the sqrt (for a float this is functionally the same as abs() but takes 2 more instructions
  v_cvt_pkrtz_f16_f32  v0, v0, lit(0x3ecccccd)          // 000000000034: D52F0000 0001FF00 3ECCCCCD
```

as you can see abs is just an input modifier so it gets packed into the 32-16 bit conversion function and is basically free, whereas length emits a multiply and sqrt instruction.
</details>

File: scene/resources/material.cpp [hunk 2]
```diff
@@ -1273,15 +1273,18 @@ void BaseMaterial3D::_update_shader() {
 	}
 
 	if (distance_fade != DISTANCE_FADE_DISABLED) {
+		// For all distance fade modes, use circular fade (distance to the
+		// object instead of Z distance), so that the fade is always the same
+		// regardless of the camera angle.
+		// This has a small performance cost, but the quality increase is worth it.
```
Comment (clayjohn) [inline scene/resources/material.cpp:1279]:
```suggestion
```

This comment won't be helpful after this PR is merged as readers won't be able to see the old code. A comment like this is more appropriate for the commit message and/or the PR itself. As that is what users will see when they traverse the history.

**Comment by elvisish** [comment]
Could this be reviewed again for 3.6?

File: scene/resources/material.cpp (hunk 2 above)
Comment (akien-mga) [reply scene/resources/material.cpp:1279]: Well the comment's verbosity could be reduced a bit but I think it's still useful to clarify that we're using circular fade and not linear on purpose.
Could be:
```
// We use the slight more expensive circular face (distance to the object) instead of linear
// (Z distance), so that the fade is always the same regardless of the camera angle.
```

**Review by clayjohn — COMMENTED** [review]
The code changes are fine. My only concern is with the comment which will quickly become out of date. 

I am fine with substituting Akien's suggested comment above.

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
> This can be cherry-picked without conflicts to the `3.x` branch. I tested this PR on the `3.x` branch on both GLES3 and [GLES2](https://github.com/godotengine/godot/pull/50295), and it works as expected there too.

This has significant conflicts now, so would be worth a dedicated backport.

**Comment by elvisish** [comment]
> > This can be cherry-picked without conflicts to the `3.x` branch. I tested this PR on the `3.x` branch on both GLES3 and [GLES2](https://github.com/godotengine/godot/pull/50295), and it works as expected there too.
> 
> 
> 
> This has significant conflicts now, so would be worth a dedicated backport.

I thought this _was_ for 3.x? This was started before 4.0 was even released.

**Comment by Calinou** [comment]
> I thought this was for 3.x? This was started before 4.0 was even released.

The code in this PR changed quite a bit compared to its first revision, and `master` started diverging more and more too.

**Comment by elvisish** [comment]
> > I thought this was for 3.x? This was started before 4.0 was even released.
> 
> 
> 
> The code in this PR changed quite a bit compared to its first revision, and `master` started diverging more and more over time. The more time goes on, the fewer PRs can be cleanly cherry-picked from `master` to `3.x`.

There were some original pushes last year that never made it, surely those would have been relevant for 3.x then as they would be now? @clayjohn did a revision at some point, what caused it to be shelved until 3.x became non-priority?
