### PR TITLE
[3.x] CPU lightmapper environment energy fixes.

### LINKED ISSUE #47785: BakedLightmap ignores environmental light energy settings
Godot 3.2.3 and 3.3rc8
Nvidia GTX 980 with driver version 450 on Ubuntu 18.04
GLES2 renderer (not tested with GLES3)

Issue #23948 might be related.

**Issue description:**
Baking environmental light does not work as expected.  I created a scene with only environmental light using the default environment, set the background and ambient light energies to 0, and baked using BakedLightmap.  In Godot 3.3rc8, the resulting images are not black with BakedLightmap.environment_mode set to "Scene".  Godot 3.2.3 does not have the environment_mode property, and it behaves like "Scene" in the newer version.  In 3.3rc8, setting environment_mode to "disable" gives me a black image, as expected.

In 3.3rc8, seting the sky, sun, and ground energies of the default ProceduralSky to 0 gets me a black image, but this is counterintuitive.  The documentation does not discuss this either.

I have also noted that the viewport display doesn't always update after baking light.  Sometimes I have to close and re-open the scene.

For additional context, see [this question](https://gamedev.stackexchange.com/questions/191503/godot-engine-why-is-baking-light-making-my-scene-darker) on StackOverflow.

**Steps to reproduce:**
See the attached project.

**Minimal reproduction project:**
[baking_bug.zip](https://github.com/godotengine/godot/files/6291064/baking_bug.zip)

### PR DESCRIPTION
**Pull request by JFonS**
* Better handling of the scene's environment energy in the lightmapper bakes. Fixes #47785.
* Fixed a bug where `ProceduralSky::get_panorama()` returned a reference instead of a copy.
* Removed includes to Embree's internal header files. Should allow for linking against system-packaged Embree, see #48073.

### CODE REVIEW

**Comment by akien-mga** [comment]
> Fixed a bug where `ProceduralSky::get_panorama()` returned a reference instead of a copy.

It's only used in `BakedLightmap` so it's probably fine (not exposed to the scripting API), but isn't it uncommon in Godot for a getter to actually return a copy instead of a reference?

`PanoramaSky` does have a public `panorama` property which is a reference as expected. Maybe `ProceduralSky`'s getter should be `get_panorama_copy()` to avoid confusion?

**Comment by JFonS** [comment]
Yeah, I added the function just so I could use it in `BakedLightmap` so the issue was only there. 

The difference between `PanoramaSky` and `ProceduralSky` is that the former takes a user defined image and uses it, while `ProceduralSky` generates it from a set of parameters, so it should be read-only.

I think `ProceduralSky::get_data()` sounds better and aligns with `Texture::get_data()` which also returns a copy (although it was renamed to `get_image()` in master, so maybe `PanoramaSky::get_image()`??).

**Comment by akien-mga** [comment]
I guess `get_data()` for `3.x` and `get_image()` if there's an equivalent in `master` now or in the future :)

**Comment by JFonS** [comment]
Makes sense, I will update the PR in a bit.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.1.

File: scene/3d/baked_lightmap.cpp [hunk 1]
```diff
@@ -1254,14 +1254,25 @@ Ref<Image> BakedLightmap::_get_irradiance_from_sky(Ref<Sky> p_sky, Vector2i p_si
 
 	sky_image->convert(Image::FORMAT_RGBF);
 	sky_image->resize(p_size.x, p_size.y, Image::INTERPOLATE_CUBIC);
+
+	if (p_energy != 1.0) {
```
Comment (kalbfled) [inline scene/3d/baked_lightmap.cpp:1258]: With floating point numbers, should this be a tolerance test?
`if (abs(p_energy - 1.0) > TOLERANCE)`

Comment (JFonS) [reply scene/3d/baked_lightmap.cpp:1258]: The check is only a shortcut optimization when the energy value is exactly 1, since `x * 1 = x`. Any other value would give a different result.
