### PR TITLE
Fix editor settings still displayed when replaced

### LINKED ISSUE #94577: "Always closes output on exit" option not work (replaced by new option)
### Tested versions

v4.3.beta3.official [82cedc83c]

### System information

w10 64

### Issue description

There's not much to say, the option doesn't work.

https://github.com/user-attachments/assets/2dcb87e2-9861-490f-9e9c-e165698eaca1

### Steps to reproduce

...

### Minimal reproduction project (MRP)

...

### PR DESCRIPTION
**Pull request by Hilderin**
- Fixes #94577

Even though no consensus was achieved about what to do with removed or replaced settings in the editor settings, I suggest this PR to fix the problem where old settings `run/output/always_open_output_on_play` and `run/output/always_close_output_on_stop` are displayed in the editor settings if the user migrates from an earlier version of Godot.

This PR adds the `EditorSettings::_remove_deprecated_settings` method and calls it when loading editor settings. It's the easiest way to fix the problem and can be used for future removal or replacement of editor settings.

### CODE REVIEW

File: editor/editor_settings.cpp [hunk 1]
```diff
@@ -998,6 +998,11 @@ const String EditorSettings::_get_project_metadata_path() const {
 	return EditorPaths::get_singleton()->get_project_settings_dir().path_join("project_metadata.cfg");
 }
 
+void EditorSettings::_remove_deprecated_settings() {
+	erase("run/output/always_open_output_on_play");
+	erase("run/output/always_close_output_on_stop");
+}
```
Comment (akien-mga) [inline editor/editor_settings.cpp:1004]: This should be enclosed in `#ifndef DISABLE_DEPRECATED` (same for the declaration and the place where it's used).

**Review by KoBeWi — APPROVED** [review]

**Comment by KoBeWi** [comment]
There might be more settings to handle this way.

File: editor/editor_settings.cpp (hunk 1 above)
Comment (Hilderin) [reply editor/editor_settings.cpp:1005]: Done!
Did not know that even existed, thanks!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
