### PR TITLE
Fix `empty_clicked` signal in Tree when using `hide_root`

### LINKED ISSUE #83928: empty_clicked signal doesn't fire if Tree has hide_root enabled
### Godot version

4.1.2.stable.mono

### System information

Windows 10 - Forward+ Vulkan

### Issue description

In GDScript, `empty_clicked` signal doesn't fire if Tree has `hide_root` enabled. Have not tested C#.

### Steps to reproduce

1) Make a scene with a tree. Add a root item. Connect `empty_clicked` signal to a print or something. It should print when empty space is clicked
2) Set `hide_root` to true. It no longer prints when empty space is clicked.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by voylin**
Fixes #83928

This PR fixes the `empty_clicked` function of the node `Tree`. Right clicking did not work when hide_root was active. Added an extra if statement with a command emitting the signal.

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -3868,6 +3868,9 @@ void Tree::gui_input(const Ref<InputEvent> &p_event) {
 				}
 
 				if (!root || (!root->get_first_child() && hide_root)) {
+					if (hide_root) {
```
Comment (KoBeWi) [inline scene/gui/tree.cpp:3871]: This condition should be removed.
The signal is not emitted when `hide_root` is disabled and there are no items.

Comment (voylin) [reply scene/gui/tree.cpp]: Removed the if statement so now it should trigger when there are items and no items

**Review by KoBeWi — APPROVED** [review]

**Comment by KoBeWi** [comment]
Needs to be squashed into 1 commit.

**Comment by voylin** [comment]
> Needs to be squashed into 1 commit.

Squashed ;)

**Comment by akien-mga** [comment]
Thanks!
