### PR TITLE
Persist fullscreen setting on Android Editor

### LINKED ISSUE #105521: Toggle FullScreen Doesn't Keep After Restart.
### Tested versions

4.4.1

### System information

Android 

### Issue description

On Android editor **tuggle fullscren** doesn't keep after restart the editor. It need to tuggle everytime I open the editor. The settings should be keep 

### Steps to reproduce

Open Android Editor
In **Editor** section tuggle the `tuggle fullscreen`
Reopen the editor

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by syntaxerror247**
Closes https://github.com/godotengine/godot/issues/105521

### CODE REVIEW

**Review by m4gr3d — APPROVED** [review]

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -860,6 +860,10 @@ void EditorNode::_notification(int p_what) {
 			get_tree()->set_auto_accept_quit(false);
 #ifdef ANDROID_ENABLED
 			get_tree()->set_quit_on_go_back(false);
+			bool is_fullscreen = EDITOR_GET("_is_editor_fullscreen");
```
Comment (KoBeWi) [inline editor/editor_node.cpp]:
```suggestion
			bool is_fullscreen = EDITOR_DEF("_is_editor_fullscreen");
```
Otherwise you will get errors about non-existent setting.

Comment (KoBeWi) [reply editor/editor_node.cpp]: Sorry, it needs some default value:
```suggestion
			bool is_fullscreen = EDITOR_DEF("_is_editor_fullscreen", false);
```

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
