### PR TITLE
[TextServerAdvanced] Keep dynamically loaded ICU data in memory.

### LINKED ISSUE #83810: Chinese line breaks in Label are incorrect on iOS
### Godot version

v4.2.beta2.official [f8818f85e]

### System information

macOS 13.4.0 - Vulkan (Mobile) - dedicated AMD Radeon Pro 560X - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 Threads)

### Issue description

Line breaks in Chinese is incorret with errors in logs on iOS devices even when autowrap mode is set to word(smart).

Following is rendered in edior. This is correct.
图片

Following is rendered on iOS device. It is incorrect.
IMG_29ADA52A9126-1

And when the app runs on iOS device, following error repeats.

`USER ERROR: U_FILE_ACCESS_ERROR
   at: _spoof_check (modules/text_server_adv/text_server_adv.cpp:6654)`

Sometimes the app will crash with EXC_BAD_ACCESS at 

`#0	0x00000001031f2164 in offsetTOCLookupFn(UDataMemory const*, char const*, int*, UErrorCode*) ()`

I tried autowrap mode 'Word' and v4.1.1. Never get it work on iOS.

### Steps to reproduce

Create a label, set its text '中字 什么时候换行。', set autowrap mode 'Word(Smart)', resize it to see autowrap in effect. 

Open project settings, set internationalization/rendering/text_driver = ICU/Harfbuzz/Graphite, set internationalization/locale/include_text_server_data = On

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Moves ICU data to static variable to keep it in memory during the whole app lifecycle. Fixes https://github.com/godotengine/godot/issues/83810

### CODE REVIEW

File: modules/text_server_adv/text_server_adv.h [hunk 1]
```diff
@@ -158,6 +158,7 @@ class TextServerAdvanced : public TextServerExtension {
 	// ICU support data.
 
 	static bool icu_data_loaded;
+	static PackedByteArray icu_data;
```
Comment (akien-mga) [inline modules/text_server_adv/text_server_adv.h:161]: Does it need to be cleared manually in the destructor, or this is implicit?

Comment (bruvzg) [reply modules/text_server_adv/text_server_adv.h:161]: It's `PackedByteArray`, so it will be freed on exit.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
