### PR TITLE
Fix cpuparticles randomness regression

### LINKED ISSUE #101859: CPUParticles2D are not random anymore
### Tested versions

Reproducible in 4.4 beta1
Not reproducible in 4.4 dev7

### System information

W10

### Issue description

https://github.com/user-attachments/assets/3c1ca89c-d1b2-44c2-98dd-e47922e6f944

These are 2 particle systems with the same settings, left one is CPU particles, right one is GPU. The CPU ones are not random.

I suspect it's caused by #92089, specifically the change from `Math::randf()` to `rand_from_seed()`. I think the class should still use `randf()`, just from a seeded RNG instance.

### Steps to reproduce

Run MRP scene.

### Minimal reproduction project (MRP)

[particlebug.tscn.txt](https://github.com/user-attachments/files/18483037/particlebug.tscn.txt)

### PR DESCRIPTION
**Pull request by QbieShay**
Closes https://github.com/godotengine/godot/issues/101859

* *Bugsquad edit, regression from: #92089*

### CODE REVIEW

File: scene/2d/cpu_particles_2d.h [hunk 1]
```diff
@@ -179,6 +180,8 @@ class CPUParticles2D : public Node2D {
 
 	Vector2 gravity = Vector2(0, 980);
 
+	Ref<RandomNumberGenerator> _rng;
```
Comment (KoBeWi) [inline scene/2d/cpu_particles_2d.h:183]:
```suggestion
	Ref<RandomNumberGenerator> rng;
```
We don't underscore private variables.

File: scene/2d/cpu_particles_2d.h [hunk 2]
```diff
@@ -31,6 +31,7 @@
 #ifndef CPU_PARTICLES_2D_H
 #define CPU_PARTICLES_2D_H
 
+#include "core/math/random_number_generator.h"
```
Comment (KoBeWi) [inline scene/2d/cpu_particles_2d.h:34]: Use forward declaration instead of include.

File: scene/2d/cpu_particles_2d.cpp [hunk 3]
```diff
@@ -769,30 +769,30 @@ void CPUParticles2D::_particles_process(double p_delta) {
...
+				p.start_color_rand = color_initial_ramp->get_color_at_offset(_rng->randf());
 			} else {
 				p.start_color_rand = Color(1, 1, 1, 1);
 			}
 
-			real_t angle1_rad = direction.angle() + Math::deg_to_rad((rand_from_seed(_seed) * 2.0 - 1.0) * spread);
+			real_t angle1_rad = direction.angle() + Math::deg_to_rad((_rng->randf() * 2.0 - 1.0) * spread);
 			Vector2 rot = Vector2(Math::cos(angle1_rad), Math::sin(angle1_rad));
-			p.velocity = rot * Math::lerp(parameters_min[PARAM_INITIAL_LINEAR_VELOCITY], parameters_max[PARAM_INITIAL_LINEAR_VELOCITY], (real_t)rand_from_seed(_seed));
+			p.velocity = rot * Math::lerp(parameters_min[PARAM_INITIAL_LINEAR_VELOCITY], parameters_max[PARAM_INITIAL_LINEAR_VELOCITY], (real_t)_rng->randf());
```
Comment (KoBeWi) [inline scene/2d/cpu_particles_2d.cpp:787]:
```suggestion
			p.velocity = rot * Math::lerp(parameters_min[PARAM_INITIAL_LINEAR_VELOCITY], parameters_max[PARAM_INITIAL_LINEAR_VELOCITY], _rng->randf());
```
`randf()` already returns `real_t`, so not sure what the cast was for.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
