### PR TITLE
Fix AnimationPlayer finished state in the editor

### LINKED ISSUE #106095: `AnimationPlayer` animation skips to the beginning and changes the values when finished in the editor
### Tested versions

- Reproducible in 4.5-dev3 and current master [1cf573f44de045ee73fd938fbf2bdccc0e31b7bb]
- Not reproducible in 4.5-dev2

### System information

Godot v4.5.dev.mono (d2964eab7) - Ubuntu 24.04.2 LTS 24.04 on Wayland - X11 display driver, Multi-window, 3 monitors - Vulkan (Forward+) - integrated AMD Radeon Graphics (RADV RENOIR) - AMD Ryzen 7 5800H with Radeon Graphics (16 threads)

### Issue description

When a non-looping animation is played in the editor, it 'jumps' to the beginning of the animation and sets the animated properties to the average? of the start and end values (I haven't tested this in detail - so it might be different for different animated tracks/properties).
It does only happen in the editor, not in the running game.

### Steps to reproduce

The mrp contains an animation that moves a `Sprite2D` from `(10, 0)` to `(100, 0)`. When the animation is played in the editor, the timeline-cursor jumps to the start and sets the position to `(55, 0)` when it's finished.

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/20040295/mrp.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
- Fixes #106095
- Supersedes/Closes https://github.com/godotengine/godot/pull/107010

Avoid resetting by determining the case based on the signal when the timeline ends.

### CODE REVIEW

File: editor/plugins/animation_player_editor_plugin.cpp [hunk 1]
```diff
@@ -1210,6 +1211,9 @@ void AnimationPlayerEditor::edit(AnimationMixer *p_node, AnimationPlayer *p_play
 		if (player->is_connected(SNAME("animation_list_changed"), callable_mp(this, &AnimationPlayerEditor::_animation_libraries_updated))) {
 			player->disconnect(SNAME("animation_list_changed"), callable_mp(this, &AnimationPlayerEditor::_animation_libraries_updated));
 		}
+		if (player->is_connected(SNAME("animation_finished"), callable_mp(this, &AnimationPlayerEditor::_animation_finished))) {
```
Comment (AThousandShips) [inline editor/plugins/animation_player_editor_plugin.cpp]:
```suggestion
		if (player->is_connected(SceneStringName(animation_finished), callable_mp(this, &AnimationPlayerEditor::_animation_finished))) {
```

File: editor/plugins/animation_player_editor_plugin.cpp [hunk 2]
```diff
@@ -1210,6 +1211,9 @@ void AnimationPlayerEditor::edit(AnimationMixer *p_node, AnimationPlayer *p_play
...
+			player->disconnect(SNAME("animation_finished"), callable_mp(this, &AnimationPlayerEditor::_animation_finished));
```
Comment (AThousandShips) [inline editor/plugins/animation_player_editor_plugin.cpp]:
```suggestion
			player->disconnect(SceneStringName(animation_finished), callable_mp(this, &AnimationPlayerEditor::_animation_finished));
```

File: editor/plugins/animation_player_editor_plugin.cpp [hunk 3]
```diff
@@ -1237,6 +1241,9 @@ void AnimationPlayerEditor::edit(AnimationMixer *p_node, AnimationPlayer *p_play
 		if (!player->is_connected(SNAME("animation_list_changed"), callable_mp(this, &AnimationPlayerEditor::_animation_libraries_updated))) {
 			player->connect(SNAME("animation_list_changed"), callable_mp(this, &AnimationPlayerEditor::_animation_libraries_updated), CONNECT_DEFERRED);
 		}
+		if (!player->is_connected(SNAME("animation_finished"), callable_mp(this, &AnimationPlayerEditor::_animation_finished))) {
```
Comment (AThousandShips) [inline editor/plugins/animation_player_editor_plugin.cpp]:
```suggestion
		if (!player->is_connected(SceneStringName(animation_finished), callable_mp(this, &AnimationPlayerEditor::_animation_finished))) {
```

File: editor/plugins/animation_player_editor_plugin.cpp [hunk 4]
```diff
@@ -1237,6 +1241,9 @@ void AnimationPlayerEditor::edit(AnimationMixer *p_node, AnimationPlayer *p_play
...
+			player->connect(SNAME("animation_finished"), callable_mp(this, &AnimationPlayerEditor::_animation_finished));
```
Comment (AThousandShips) [inline editor/plugins/animation_player_editor_plugin.cpp]:
```suggestion
			player->connect(SceneStringName(animation_finished), callable_mp(this, &AnimationPlayerEditor::_animation_finished));
```

File: scene/animation/animation_mixer.cpp [hunk 5]
```diff
@@ -2473,8 +2473,8 @@ void AnimationMixer::_bind_methods() {
 
 	ADD_SIGNAL(MethodInfo(SNAME("animation_list_changed")));
 	ADD_SIGNAL(MethodInfo(SNAME("animation_libraries_updated")));
-	ADD_SIGNAL(MethodInfo(SNAME("animation_finished"), PropertyInfo(Variant::STRING_NAME, "anim_name")));
-	ADD_SIGNAL(MethodInfo(SNAME("animation_started"), PropertyInfo(Variant::STRING_NAME, "anim_name")));
+	ADD_SIGNAL(MethodInfo(SceneStringName(animation_finished), PropertyInfo(Variant::STRING_NAME, "anim_name")));
+	ADD_SIGNAL(MethodInfo(SceneStringName(animation_started), PropertyInfo(Variant::STRING_NAME, "anim_name")));
```
Comment (AThousandShips) [inline scene/animation/animation_mixer.cpp]: These are incorrect, `MethodInfo` takes `String`

**Review by fire — APPROVED** [review]
State machines tend to be convoluted so I hope it works without systematically diagramming and looking for missing cases. Approved.

**Comment by akien-mga** [comment]
Thanks!
