### PR TITLE
Respect HDR option

### LINKED ISSUE #14895: Turning off HDR in settings/quality affects only the editor.
**Godot version:**

tested on Master, Beta and Alpha 2

**OS/device including version:**

Manjaro 64bit, GT540M NVIDIA Driver Version: 384.90

**Issue description:**

Turning off HDR in settings/quality affects only the editor.

In editor
hdr_1

Running
hdr_2

Also when opening the project, the editor looks like it have enabled HDR, but if you go to settings you can see that it is disabled. Turning it on and then off will give the results in the editor.

**Steps to reproduce:**

**Minimal reproduction project:**

[hdr.zip](https://github.com/godotengine/godot/files/1579136/hdr.zip)

### PR DESCRIPTION
**Pull request by volzhs**
Fix #14895

### CODE REVIEW

File: main/main.cpp [hunk 1]
```diff
@@ -1445,6 +1445,11 @@ bool Main::start() {
 			Viewport::Usage usage = Viewport::Usage(int(GLOBAL_GET("rendering/quality/intended_usage/framebuffer_allocation")));
 			sml->get_root()->set_usage(usage);
 
+			int msaa_mode = GLOBAL_GET("rendering/quality/filters/msaa");
```
Comment (reduz) [inline main/main.cpp]: this code is already in SceneTree::initialize(), I wonder why it may not have any effect if this is the case

Comment (volzhs) [reply main/main.cpp]: I will check that.

Comment (volzhs) [reply main/main.cpp]: I think there was a mistake for testing msaa option.
it respects msaa well.
