### PR TITLE
Increase float precision in the editor inspector for Quaternions

### LINKED ISSUE #98090: Changing bone euler rotation sets non-normalized quaternion
### Tested versions

Reproducible in:
* v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Debian GNU/Linux trixie/sid trixie - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7600 (RADV NAVI33) - AMD Ryzen 5 7600 6-Core Processor (12 Threads)

### Issue description

If one has a model rigged with a `Skeleton3D`, and changes a bone's rotation by typing values in the temporary Euler inputs, the resultant quaternion will often be non-normalized.
While this appears to work just fine on the skeleton's pose, it will cause an error (and reset of bone rotation) if animation keyframes are played using such a non-normalized quaternion:

> AnimationPlayer: 'AnimationPlayer', Animation: '', 3D Rotation Track:  'characterMedium/Root/Skeleton3D:RightUpLeg' contains unnormalized Quaternion key.
> The end quaternion (-0.968029, 0.072789, 0.005684, 0.237784) must be normalized.

This also happens if you manually alter the values of the quaternion's inputs. The quaternion ends up non-normalized and fails during animations, but works fine for statically posing the skeleton.

As a possible workaround, if you mouse-drag the euler values (click-hold on the x|y|z label, and drag the mouse left or right to gradually change the values), instead of manually entering values, this seems to cause the resultant quaternion to be normalized.

Though TBH I'm not sure if the issue here should be "editing bone rotation can produce non-normalized quaternions" or "bone animation tracks reject non-normalized quaternions, even though they work for static poses". :confused: 

### Steps to reproduce

The attached MRP includes a rigged model and an `AnimationPlayer`. The included animation sets the rotation for both legs, but only the left leg works.

You can experiment with ways of changing the rotation value of the `RightUpLeg` bone, setting its keyframe in the animation, and then seeing if the animation plays.

### Minimal reproduction project (MRP)

[animate-quaternion.zip](https://github.com/user-attachments/files/17343575/animate-quaternion.zip)

### PR DESCRIPTION
**Pull request by aaronfranke**
Made in response to #106335. For Quaternions, it's better to display more digits in the inspector for precision, beyond the usual float step found in the editor settings in `"interface/inspector/default_float_step"`. Note that property hints can still override the step to a different value, this change only overrides the editor setting.

This PR also adjusts the `EditorSpinSlider` code to clamp the step used for dragging to a minimum of 0.001. Without this change, clicking and dragging on Quaternion elements becomes very slow. I didn't even test double precision, but imagine how slow that would be too. This may affect editor plugins that expect this behavior, but I don't think it's good behavior. It's bad to discourage users from using high precision because the usability is worse. Perhaps there needs to be separate settings for drag step and the actual number step, but that's a larger proposal...

_Bugsquad Edited:_
- Fixes https://github.com/godotengine/godot/issues/98090

### CODE REVIEW

File: editor/gui/editor_spin_slider.cpp [hunk 1]
```diff
@@ -109,16 +109,18 @@ void EditorSpinSlider::gui_input(const Ref<InputEvent> &p_event) {
 					pre_grab_value = get_max();
 				}
 
+				// Prevent dragging properties with very precise steps from being agonizingly slow.
+				const double drag_step = get_step() > 0.001 ? get_step() : 0.001;
```
Comment (KoBeWi) [inline editor/gui/editor_spin_slider.cpp:113]:
```suggestion
				const double drag_step = MAX(get_step(), 0.001);
```

**Review by TokageItLab — CHANGES_REQUESTED** [review]
At any rate, I confirmed that this solves the https://github.com/godotengine/godot/issues/98090 problem after setting Quaternion with EulerEditor.

As a request, the `EditorPropertyQuaternion` is reused in the `BonePropertiesEditor`, so the step there needs to be changed as well.

> Perhaps there needs to be separate settings for drag step and the actual number step, but that's a larger proposal...

I agree that ideally this is the best way.

This may not be much of a concern, but as commented in https://github.com/godotengine/godot/pull/106335#issuecomment-2875934305, if anyone copy values from other Editors, such as the normalized Plane Editor, or from a user-created Quaternion Editor with a step of `0.001`, and paste them into the Quaternion editor, there is no guarantee that they are normalized.

I feel there needs to be documentation somewhere about normalization in Quaternion with more detail.

**Review by TokageItLab — APPROVED** [review]

**Comment by TokageItLab** [comment]
I would like confirmation of approving on the direction in addition to mine. Probably @lawnjelly ?

**Comment by lawnjelly** [comment]
@TokageItLab If this is to address the problem of non-normalized quats, I would tend to think https://github.com/godotengine/godot/issues/98090#issuecomment-2899945933 is the best approach to fix (and I think you basically alluded to this in your quote I made there).

These other approaches seem like some kind of bodge to avoid fixing the inspector to deal with these normalized values properly. But maybe I'm misunderstanding.

**Comment by TokageItLab** [comment]
@lawnjelly The essence and cause of the problem is that when normalized values are entered into the inspector, as shown in script https://github.com/godotengine/godot/pull/106335, they are no longer normalized due to rounding(snapping).

```gdscript
extends Node3D

func _process(delta: float) -> void:
	var q: Quaternion = Quaternion(randf_range(-1, 1), randf_range(-1, 1), randf_range(-1, 1), randf_range(-1, 1)).normalized()
	q = Quaternion(snappedf(q.x, 0.001), snappedf(q.y, 0.001), snappedf(q.z, 0.001), snappedf(q.w, 0.001))

	if !q.is_normalized(): # <- Frequently detecting unnormalized
		print(str(q))
```

I don't know if it is possible in the EditorInspector to separate the displayed value from the internal value. Is there another similar place to do this?

Also I concern that that method may unintentionally flip the positive and negative of each element internally, especially in cases where the user has intentionally flipped the phase of the quaternion, which would require cautionary ventilation for the user besides accuracy.

So I think we basically need to keep the values using this PR approach, without internal normalization. If we were not to synchronize the internal and external display, we would just omit the digits.

**Comment by lawnjelly** [comment]
> I think we need to change the fundamental behavior of the inspector when object is updated for that.

Well, yes, that's what I'm suggesting.
If you aren't confident in this area, you could ask some of the more editor orientated contributors if they can help?

> Also, in the case of sequential input of normalized elements one at a time, if internal normalization is performed on each input, the final input will not match the value that was originally intended. This means that the user will never be able to enter arbitrary values into Quaternion. This is what I said during the https://github.com/godotengine/godot/pull/98308#pullrequestreview-2379047909 (case 2) review.

I didn't write anything about normalizing _editor_ elements one element at a time.

You explicitly cannot do this for any class that is normalized, because it would prevent entering anything sensible in the editor. What I was suggesting is that the _internal_ quat is normalized, the _editor_ quat is a different variable. If you re-read what I wrote in the original comment hopefully this will make sense.

**Comment by TokageItLab** [comment]
After all, currently the editor Quaternion is supposed to immediately reflect the value returned by the object after it is set to the object, so we need to change the editor fundamental behavior, but which is not an easy task since the scope of influence is quite large.

Also, a second PR is needed to implement the internal normalization after changing the editor fundamental behavior. It is probably ideal, but definitely not something that can be done in time for 4.5 at this stage, no matter who does it.

So I consider this PR to be fine as a tentative bugfix. If in the future we include the editor Quaternion separation and internal normalization, there should be no compatibility concerns with the project itself although the editor input workflow for user may bit change.

**Comment by lawnjelly** [comment]
Sure, if this fixes some issues on general editing of quaternions due to giving more accuracy etc than that is fine to proceed too.

I'm only questioning whether this actually does fix #98090 , or whether it actually addressed normalization of quats _at all_. Also maybe there should be two separate issues:
* editing eulers -> quat (should normalize)
* editing quats -> quat (the more interesting case, where a go between temporary may be needed)

**Comment by TokageItLab** [comment]
https://github.com/godotengine/godot/issues/98090 is definitely corrected by this PR. Since EulerEditor will input its composed normalized Quaternion value into QuaternionEditor but the problem occurs due to snapping in the spinbox.

**editor_properties.cpp**
```cpp
void EditorPropertyQuaternion::_custom_value_changed(double val) {
	edit_euler.x = euler[0]->get_value();
	edit_euler.y = euler[1]->get_value();
	edit_euler.z = euler[2]->get_value();

	Vector3 v;
	v.x = Math::deg_to_rad(edit_euler.x);
	v.y = Math::deg_to_rad(edit_euler.y);
	v.z = Math::deg_to_rad(edit_euler.z);

	Quaternion temp_q = Quaternion::from_euler(v);
	spin[0]->set_value_no_signal(temp_q.x);
	spin[1]->set_value_no_signal(temp_q.y);
	spin[2]->set_value_no_signal(temp_q.z);
	spin[3]->set_value_no_signal(temp_q.w);
	_value_changed(-1, "");
}
```

**Comment by lawnjelly** [comment]
I wrote a quick example of using a temporary for editing quaternions in #106821 .
Probably a bit Dunning Kruger on my part but it doesn't look too tricky, might be possible to make it more generic.

**Comment by fire** [comment]
Can you update the pull request so it's rebased?

**Comment by lawnjelly** [comment]
I wasn't intending to block this PR, but just spur some questioning on best way of editing normalized values (to prevent problems like the linked issue).

From memory the problem is, if you make the inspector value the "current always normalized master value", then it makes the usability very bad if you want to e.g. type in a specific quaternion (or vector3 etc).

Afaik in this PR you are trying to make the inspector "master value" more accurate here, to make it more likely to be normalized.

My thoughts are, that in a way it is irrelevant whether the inspector value is normalized (that's just a display for easy editing). Only the internal value needs to be normalized, so decouple the two. I'm not keen to approve something which I'm not yet convinced is a good approach.

It might be a good idea to bring it up in a rendering(?) meeting to get approval / thoughts, as a lot of the rendering guys are familiar with quaternions / normalization issues (and more familiar with 4.x than myself), and this is relevant not just for quaternions.

File: editor/gui/editor_spin_slider.cpp [hunk 2]
```diff
@@ -120,7 +120,9 @@ void EditorSpinSlider::gui_input(const Ref<InputEvent> &p_event) {
 					pre_grab_value = get_max();
 				}
 
-				double new_value = pre_grab_value + get_step() * grabbing_spinner_dist_cache;
+				// Prevent dragging properties with very precise steps from being agonizingly slow.
+				const double drag_step = MAX(get_step(), 0.001);
```
Comment (clayjohn) [inline editor/gui/editor_spin_slider.cpp]: Shouldn't this use `interface/inspector/default_float_step` in order to maintain the current behaviour?

**Review by clayjohn — COMMENTED** [review]
We discussed this with @TokageItLab and @lyuma in a rendering meeting. It makes sense to me to have a much lower step size for quaternions if the default is always too granular and causes issues with even copy-pasting in quaternions. 

I understand Lawnjelly's concern that there are probably _further_ usability concerns with editing normalized quarternions. But I think this makes sense as a stopgap solution to make the current behaviour at least somewhat usable. 

I am concerned about the behaviour change to the default spin slider drag step size. I think it should likely use the size configured in the editor to avoid a needless behaviour change.

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
