### PR TITLE
Display an error message if no version control systems are available

### LINKED ISSUE #32135: VCS selection menu dropdown uses dummy option as placeholder
**Godot version:**
3.2 alpha

**Issue description:**
image

The dropdown default value/placeholder is an option itself. Should be shown as a placeholder or not at all.

**Steps to reproduce:**
1. Select Project > Version Control > Set Up Version Control.
2. Expand the dropdown container to see the default value listed in too.

**Minimal reproduction project:**
Fresh Godot Project

### PR DESCRIPTION
**Pull request by Calinou**
This removes the need for a dedicated placeholder entry.

This closes #32135.

cc @IronicallySerious – Please test for possible regressions :slightly_smiling_face:

### CODE REVIEW

**Comment by IronicallySerious** [comment]
Thanks! Although I am seeing a crash at version_control_editor_plugin.cpp:127 while using the Git addon. Seems like the id is returned 0 at https://github.com/IronicallySerious/godot/blob/24e1039eb6fe32115e8d1a62a84965e9be19a2ed/editor/plugins/version_control_editor_plugin.cpp#L116
And I think this id (id = 0 + 1) doesn't exist at that time because there is only one element in the dropdown.

This is the project that I am using for testing: https://github.com/godotengine/godot-git-plugin/tree/master/demo (can't upload the complete project here, too big)
To reproduce the crash, load the project and select initialize from the VCS menu.

**Comment by IronicallySerious** [comment]
This could be held till https://github.com/godotengine/godot/pull/32134 is merged because this PR requires Godot to select the VCS addons available first to raise errors if Godot can't find any.

Right now Godot doesn't select any global script and it just lists all of them in the VCS addon selection dropdown.

File: editor/plugins/version_control_editor_plugin.cpp [hunk 1]
```diff
@@ -95,19 +84,22 @@ VersionControlEditorPlugin *VersionControlEditorPlugin::get_singleton() {
...
-		set_up_init_button->set_disabled(true);
-	}
+		_populate_available_vcs_names();
 
-	_populate_available_vcs_names();
+		set_up_dialog->popup_centered_clamped(popup_size * EDSCALE);
+	} else {
 
-	set_up_dialog->popup_centered_clamped(popup_size * EDSCALE);
+		EditorNode::get_singleton()->show_warning(TTR("No VCS plugins are available."), TTR("Error"));
```
Comment (IronicallySerious) [inline editor/plugins/version_control_editor_plugin.cpp]: The plugins were agreed upon to be called 'VCS addons' instead of plugins because they are made to be swappable and removable. This is a nitpick though

File: editor/plugins/version_control_editor_plugin.cpp [hunk 2]
```diff
@@ -120,7 +112,8 @@ void VersionControlEditorPlugin::_initialize_vcs() {
 		return;
 	}
 
-	int id = set_up_choice->get_selected_id();
+	// There's no placeholder option, so add 1 to the real value
+	const int id = set_up_choice->get_selected_id() + 1;
```
Comment (IronicallySerious) [inline editor/plugins/version_control_editor_plugin.cpp]: Replacing with `const int id = set_up_choice->get_selected_id();` seems to get rid of the crash and select the addon properly

**Comment by IronicallySerious** [comment]
Tested for regression :)
Should be tested again after https://github.com/godotengine/godot/pull/32134 is merged

**Comment by akien-mga** [comment]
>  Should be tested again after #32134 is merged

Merged, so can be tested again.

**Comment by IronicallySerious** [comment]
@akien-mga Tested again. Seems fine to merge in.

**Comment by akien-mga** [comment]
Thanks!
