### PR TITLE
Fix reimporting assets with csv in the project

### LINKED ISSUE #83200: (Re)importing Assets breaks apart on GLB/GLTF materials at clean project import because of an CSV file
### Godot version

4.1.2-stable

### System information

Windows 11

### Issue description

The auto (Re)Importing of assets breaks apart, when a CSV file is re-imported in a project?

I noticed that, when a clean git checkout of an project is made (without the .godot folder), the auto (re)import breaks apart at GLB/GLTF textures/materials. After some time i could narrow down the suspect to an CSV file in my project and the corresponding autogenerated `.csv.import` file. When the `.csv.import file` does not exist in the repo/project it gets successfuly imported, the file gets created and everything is fine. The problem starts when it gets commited and someone else checks it out and tries to rebuild the .godot folder. 

This will result in following error (MRP example red texture cube model):
`WARNING: glTF: Image index '0' couldn't be loaded with the name: Image_0. Skipping it.`
Screenshot of it:

The material is broken (at this state, only a manual reimport by hand can fix this):

And here how the model looks when the csv files does not exist:

### Steps to reproduce

* Run both MRP projects
* MeshImportBug_OK should run fine and show a red textured cube at the dummy scene and the MeshImportBug_Broken one not.

### Minimal reproduction project

[MeshImportBug_OK.zip](https://github.com/godotengine/godot/files/12884441/MeshImportBug_OK.zip)
[MeshImportBug_Broken.zip](https://github.com/godotengine/godot/files/12884444/MeshImportBug_Broken.zip)

### PR DESCRIPTION
**Pull request by Hilderin**
This should fix #83200

The problem was that the `DebugDialogue.csv.import` is invalid according to Godot because it’s missing the `path` line. Because of this the importer was not mark multithread and a counter was not incremented between threaded and non threaded reimportation. I fixed the increment problem in `editor_file_system._reimport_file`.

The problem with the invalid `.import file` was caused because `ResourceImporterCSVTranslation` is the only importer that has no extension. It does not write any file in the .godot folder. I fixed that adding a check in `_get_path_and_type` before returning ERR_FILE_CORRUPT.

### CODE REVIEW

File: core/io/resource_importer.cpp [hunk 1]
```diff
@@ -118,9 +118,22 @@ Error ResourceFormatImporter::_get_path_and_type(const String &p_path, PathAndTy
 	}
 #endif
 
-	if (r_path_and_type.path.is_empty() || r_path_and_type.type.is_empty()) {
+	if (r_path_and_type.type.is_empty()) {
 		return ERR_FILE_CORRUPT;
 	}
+	if (r_path_and_type.path.is_empty()) {
+		// Le ResourceImporterCSVTranslation does not write files in the .godot folder
```
Comment (AThousandShips) [inline core/io/resource_importer.cpp:125]:
```suggestion
		// The ResourceImporterCSVTranslation does not write files in the .godot folder
```
Assuming accidentally untranslated

File: core/io/resource_importer.cpp [hunk 2]
```diff
@@ -118,9 +118,22 @@ Error ResourceFormatImporter::_get_path_and_type(const String &p_path, PathAndTy
...
+		// it's normal if the path is empty.
+		if (r_path_and_type.importer.is_empty()) {
+			return ERR_FILE_CORRUPT;
+		}
+
+		// It's only invalid if the extension for the importer is not empty.
+		Ref<ResourceImporter> importer = get_importer_by_name(r_path_and_type.importer);
+		if (!importer.is_valid() || !importer->get_save_extension().is_empty()) {
```
Comment (AThousandShips) [inline core/io/resource_importer.cpp:133]:
```suggestion
		if (importer.is_null() || !importer->get_save_extension().is_empty()) {
```

**Comment by Hilderin** [comment]
This last commit included modifications to fix #85130 and the comments from @RandomShaper
I added another `from = i + 1` if the reimport_file is in groups_to_reimport.
I don't known how to test it, I don't even known what are the groups for importation.

File: core/io/resource_importer.cpp [hunk 3]
```diff
@@ -118,9 +118,22 @@ Error ResourceFormatImporter::_get_path_and_type(const String &p_path, PathAndTy
 	}
 #endif
 
-	if (r_path_and_type.path.is_empty() || r_path_and_type.type.is_empty()) {
+	if (r_path_and_type.type.is_empty()) {
 		return ERR_FILE_CORRUPT;
 	}
+	if (r_path_and_type.path.is_empty()) {
+		// The ResourceImporterCSVTranslation does not write files in the .godot folder
```
Comment (KoBeWi) [inline core/io/resource_importer.cpp:125]: I think the comment should be more general, like "Some importers may not write files to the .godot folder, so the path can be empty."

File: core/io/resource_importer.cpp [hunk 4]
```diff
@@ -118,9 +118,22 @@ Error ResourceFormatImporter::_get_path_and_type(const String &p_path, PathAndTy
...
+		// it's normal if the path is empty.
+		if (r_path_and_type.importer.is_empty()) {
+			return ERR_FILE_CORRUPT;
+		}
+
+		// It's only invalid if the extension for the importer is not empty.
+		Ref<ResourceImporter> importer = get_importer_by_name(r_path_and_type.importer);
+		if (importer.is_null() || !importer->get_save_extension().is_empty()) {
```
Comment (KoBeWi) [inline core/io/resource_importer.cpp:133]:
```suggestion
		if (importer.is_null() || importer->get_save_extension().is_empty()) {
```
If it's supposed to be non-empty...

File: editor/editor_file_system.cpp [hunk 5]
```diff
@@ -2398,18 +2398,22 @@ void EditorFileSystem::reimport_files(const Vector<String> &p_files) {
...
 				if (from - i == 0) {
 					// Single file, do not use threads.
 					pr.step(reimport_files[i].path.get_file(), i);
 					_reimport_file(reimport_files[i].path);
 				} else {
 					Ref<ResourceImporter> importer = ResourceFormatImporter::get_singleton()->get_importer_by_name(reimport_files[from].importer);
-					ERR_CONTINUE(!importer.is_valid());
+					if (!importer.is_valid()) {
+						from = i + 1;
+						ERR_CONTINUE(!importer.is_valid());
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:2415]:
```suggestion
						ERR_CONTINUE(true);
```
If it's intended to always fail. No need to check this twice.

File: core/io/resource_importer.cpp (hunk 4 above)
Comment (Hilderin) [reply core/io/resource_importer.cpp:133]: On the contrary, the ERR_FILE_CORRUPT should be raised only if the importer has an extension (not is_empty). If no extension, we want to return OK.

File: editor/editor_file_system.cpp (hunk 5 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp:2415]: It's ok to just pass "true"? The problem is that the error message will be something like `Condition "false" is true. Continuing.` instead of `Condition "!importer.is_valid()" is true. Continuing.`

I don't see anywhere else where only true or false was passed to `ERR_CONTINUE`.

You are right that checking the condition twice is not ideal, but I don't see an easy way to increment the counter and call ERR_CONTINUE to have the right error message.

File: core/io/resource_importer.cpp (hunk 4 above)
Comment (KoBeWi) [reply core/io/resource_importer.cpp:132]: I misread the comment.

File: editor/editor_file_system.cpp (hunk 5 above)
Comment (KoBeWi) [reply editor/editor_file_system.cpp:2415]: `ERR_CONTINUE_MSG`

File: editor/editor_file_system.cpp [hunk 6]
```diff
@@ -2398,18 +2398,22 @@ void EditorFileSystem::reimport_files(const Vector<String> &p_files) {
...
-			if (i + 1 == reimport_files.size() || reimport_files[i + 1].importer != reimport_files[from].importer) {
+			if (i + 1 == reimport_files.size() || reimport_files[i + 1].importer != reimport_files[from].importer || groups_to_reimport.has(reimport_files[i + 1].path)) {
 				if (from - i == 0) {
 					// Single file, do not use threads.
 					pr.step(reimport_files[i].path.get_file(), i);
 					_reimport_file(reimport_files[i].path);
 				} else {
 					Ref<ResourceImporter> importer = ResourceFormatImporter::get_singleton()->get_importer_by_name(reimport_files[from].importer);
-					ERR_CONTINUE(!importer.is_valid());
+					if (!importer.is_valid()) {
```
Comment (AThousandShips) [inline editor/editor_file_system.cpp:2413]:
```suggestion
					if (importer.is_null()) {
```

File: editor/editor_file_system.cpp (hunk 5 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp]: Of course!! Thanks! Did not known that one.

File: editor/editor_file_system.cpp (hunk 6 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp]: Changed. Should I change all the `![object].is_valid` to `.is_null` when I change code around it? I saw a good number of `![object].is_valid` in Godot code base.

File: editor/editor_file_system.cpp [hunk 7]
```diff
@@ -2398,18 +2398,22 @@ void EditorFileSystem::reimport_files(const Vector<String> &p_files) {
...
 				if (from - i == 0) {
 					// Single file, do not use threads.
 					pr.step(reimport_files[i].path.get_file(), i);
 					_reimport_file(reimport_files[i].path);
 				} else {
 					Ref<ResourceImporter> importer = ResourceFormatImporter::get_singleton()->get_importer_by_name(reimport_files[from].importer);
-					ERR_CONTINUE(!importer.is_valid());
+					if (importer.is_null()) {
+						from = i + 1;
+						ERR_CONTINUE_MSG(true, vformat("Invalid importer for \"%s\".", reimport_files[from].importer));
```
Comment (AThousandShips) [inline editor/editor_file_system.cpp:2415]:
```suggestion
						ERR_CONTINUE_MSG(true, vformat("Invalid importer for \"%s\".", reimport_files[from].importer));
						from = i + 1;
```
I'm assuming, as the checked importer is the earlier `from`

Comment (Hilderin) [reply editor/editor_file_system.cpp:2415]: From my perspective, if the `from = i + 1;` is done after the ERR_CONTINUE_MSG, it will not be executed and next resource (which likely does not have the same importer) will be imported with the previous invalid importer. That was exactly the problem in https://github.com/godotengine/godot/pull/85130 .

Comment (AThousandShips) [reply editor/editor_file_system.cpp:2415]: That's true, then you need to fetch the old value instead, my bad, but you need to handle that, because this will print the wrong message

Comment (Hilderin) [reply editor/editor_file_system.cpp:2415]: Oh!! That's totally right! I'll fix that!

Comment (AThousandShips) [reply editor/editor_file_system.cpp:2415]:
```suggestion
						ERR_PRINT(true, vformat("Invalid importer for \"%s\".", reimport_files[from].importer));
						from = i + 1;
						continue;
```

Comment (AThousandShips) [reply editor/editor_file_system.cpp:2415]: Corrected as the original had a leftover `true`

Comment (Hilderin) [reply editor/editor_file_system.cpp]: Done

**Comment by KoBeWi** [comment]
- [ ] This reintroduces #91009, except it also happens in English now. We might need to re-think the dialog, because it's getting too many tabs.

- [ ] When creating extension and typing a name, there is a noticeable delay between each letter (at least in debug build), likely caused by field updating. There could be some debouncing applied here.

https://github.com/godotengine/godot/assets/2223172/b05a041e-8276-4ea4-9505-598dedbe0c5a

- [ ] While performing initial compilation the editor is completely unresponsive. The compilation should run in an independent process, to not stall the editor. You could display indeterminate progress bar, or if you are ambitions, you can show compilation progress and output in real time, using the new `execute_with_pipe()` method.

- [ ] After compiling finishes, the new GDExtension does not appear in the list until you click the window. Seems like editor ends unfocused somehow and clicking it refreshes the list or something. (might need further testing)

Despite these minor problems, the extension is created correctly and is usable out-of-the-box, which is very nice.

**Review by AThousandShips — APPROVED** [review]
Haven't tested but the code looks good to me (can't speak for the last line of change that's discussed though)

**Comment by Hilderin** [comment]
Sorry, @AThousandShips  I'm not sure what you are referencing with: 
> can't speak for the last line of change that's discussed though

Everything should be good, I think.

File: editor/editor_file_system.cpp [hunk 8]
```diff
@@ -2439,6 +2439,10 @@ void EditorFileSystem::reimport_files(const Vector<String> &p_files) {
 		} else {
 			pr.step(reimport_files[i].path.get_file(), i);
 			_reimport_file(reimport_files[i].path);
+
+			// We need to increment the counter, maybe the next file is multithreaded
+			// and don't have the same importer.
+			from = i + 1;
```
[the remark this answers is not in the document]
Comment (Hilderin) [reply editor/editor_file_system.cpp:2450]: This have been addressed in this commit: https://github.com/godotengine/godot/commit/4f55118f400e999ed37c6537c39af8a4e0a4a703
I should have been clearer in my comment below.

File: editor/editor_file_system.cpp [hunk 9]
```diff
@@ -2439,6 +2444,10 @@ void EditorFileSystem::reimport_files(const Vector<String> &p_files) {
 		} else {
 			pr.step(reimport_files[i].path.get_file(), i);
 			_reimport_file(reimport_files[i].path);
+
+			// We need to increment the counter, maybe the next file is multithreaded
+			// and don't have the same importer.
```
Comment (akien-mga) [inline editor/editor_file_system.cpp:2449]:
```suggestion
			// and doesn't have the same importer.
```
or "they don't" if referring to both files.

Comment (Hilderin) [reply editor/editor_file_system.cpp]: Done!

**Comment by akien-mga** [comment]
Welp I merged this inadvertently because I was testing it in my `master` branch before making a merge batch :D

But I guess it's a good way to confirm whether it's working or not, let's see how it fares from now to when I'd need to make beta3 builds.

---

Thanks!
