### PR TITLE
Fix HTTPClient _request using wrong size

### LINKED ISSUE #75866: HTTPClient doesn't work with a body containing special characters
### Godot version

Godot 4

### System information

Linux

### Issue description

When using HTTPClient from GDScript having non ASCII characters like "안녕하세요" causes the request to fail/not work correctly. This only affects HTTPClient and not HTTPRequest. Issue is it using the size before converting to utf8 for the request body in the _request method.

### Steps to reproduce

see mrp. Just use HttpClient and put some unicode characters that are not ascii characters in the request body.

### Minimal reproduction project

[http_client_unicode_issue.zip](https://github.com/godotengine/godot/files/11186119/http_client_unicode_issue.zip)

### PR DESCRIPTION
**Pull request by tefusion**
Fixes #75866

### CODE REVIEW

File: core/io/http_client.cpp [hunk 1]
```diff
@@ -63,8 +63,9 @@ Error HTTPClient::_request_raw(Method p_method, const String &p_url, const Vecto
 }
 
 Error HTTPClient::_request(Method p_method, const String &p_url, const Vector<String> &p_headers, const String &p_body) {
-	int size = p_body.length();
-	return request(p_method, p_url, p_headers, size > 0 ? (const uint8_t *)p_body.utf8().get_data() : nullptr, size);
+	CharString cs = p_body.utf8();
```
Comment (RedworkDE) [inline core/io/http_client.cpp:66]:
```suggestion
	CharString body_utf8 = p_body.utf8();
```
For more descriptive names

Comment (tefusion) [reply core/io/http_client.cpp:66]: I looked up CharString and saw most people just call it 'cs'. So I figured I'd copy that too. Since it only shows up in the two lines below, such a short name should still be fine here as well imo. I'll wait for further review so checks don't rerun just for this.

Comment (YuriSizov) [reply core/io/http_client.cpp:66]: It's an old habit, but generally names should be indeed descriptive. It's not a huge deal in such a small method, but if you could update it, it would be great.

Comment (tefusion) [reply core/io/http_client.cpp]: ok, updated it. Thanks for the better name suggestion Redwork.

**Review by RedworkDE — APPROVED** [review]

**Review by Faless — APPROVED** [review]
LGTM :rocket:

**Comment by Faless** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.4.
