### PR TITLE
Fix `EditorNode::disambiguate_filenames` freeze

### LINKED ISSUE #65122: EditorFileDialog freezes the editor
### Godot version

v4.0.alpha.custom_build [8fa9d1ae4]

### System information

Linux (Fedora 36)

### Issue description

When opening a file dialog in certain projects the editor freezes while maxing out a CPU thread. It only happens if recent directories contains two of the same directory, one with a slash at the end and one without. Which is something that happens sometimes, I don't know if there's already an issue open for that or how to reproduce it.
From doing a `git bisect` this seems to be a regression caused by #63552. That PR involves some `for` loops so I think it's getting stuck in an infinite loop, but I couldn't figure out where.

### Steps to reproduce

1. Open the MRP (contains a `.godot/editor/recent_dirs` file that will cause the bug)
2. Right click on FileSystem -> New Resource and select any resource type (or open an EditorFileDialog by some other means)
3. Blank window pops up, editor freezes and maxes out a CPU core

### Minimal reproduction project

[EditorStuck.zip](https://github.com/godotengine/godot/files/9457734/EditorStuck.zip)

### PR DESCRIPTION
**Pull request by RedMser**
Fix #65122 

Had to apply the new "trailing slash normalization" in a second, duplicate code snippet as well x_x

Simplifies the normalization logic, since all the code cares about here is the length *difference* (so it doesn't matter if we add or remove a trailing slash).

I also made it clearer that the code is duplicated by re-ordering the if checks to be the same as above (this has no functional changes) and copying the comments as well.

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -301,14 +301,23 @@ void EditorNode::disambiguate_filenames(const Vector<String> p_full_paths, Vecto
...
 				}
-				if (scene_name.rfind(".") >= 0) {
-					scene_name = scene_name.substr(0, scene_name.rfind("."));
+
+				// Normalize trailing slashes when normalizing directory names.
+				if (scene_name.rfind("/") == scene_name.length() - 1 && path.rfind("/") != path.length() - 1) {
+					path = path + "/";
+				} else if (scene_name.rfind("/") != scene_name.length() - 1 && path.rfind("/") == path.length() - 1) {
+					scene_name = scene_name + "/";
 				}
```
Comment (akien-mga) [inline editor/editor_node.cpp:321]: Simpler?
```suggestion
				// Normalize trailing slashes when normalizing directory names.
				scene_name = scene_name.trim_suffix("/");
				path = path.trim_suffix("/");
```

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -301,14 +301,23 @@ void EditorNode::disambiguate_filenames(const Vector<String> p_full_paths, Vecto
...
 
 				// We can proceed iff the full path is longer than the scene name,
```
Comment (akien-mga) [inline editor/editor_node.cpp:323]: Typo at `iff`, might be worth fixing.

File: editor/editor_node.cpp (hunk 1 above)
Comment (RedMser) [reply editor/editor_node.cpp]: Could actually be applied to both places I think? Will test.

**Comment by RedMser** [comment]
Looked at the code again, seems like the path and name are only ever used for length comparison in both cases. So adding/removing trailing slash yields identical results, making the trim syntax a much shorter alternative.

Thanks for the suggestion!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
