### PR TITLE
Fix null values for local const in debugger

### LINKED ISSUE #96834: const local variables show as null in the debugger
### Tested versions

Reproducible in: 4.4.dev2, 4.3 stable, 4.2.2 stable, 4.1.4 stable, 4.0.4 stable
Not reproducible in 3.6 stable because of error: `Error parsing expression, misplaced: const`

### System information

Godot v4.4.dev2.mono - Linux Mint 21.3 (Virginia) - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 6800 (RADV NAVI21) - AMD Ryzen 5 7600 6-Core Processor (12 Threads)

### Issue description

const local variables display as null in the debugger. I expected to see the actual value of the const, like you can see for consts that are declared as fields in the script.

### Steps to reproduce

This issue can be easily encountered with the following code:
```gdscript
extends Node

const my_field_const := 100

func _ready() -> void:
	const my_const := 10
	print("my_const is: " + str(my_const))
	print("The above statement printed 10, but my_const shows as null in the debugger!")
```
Placing a breakpoint on one of the print lines and looking in the debugger will show the `my_field_const` const displayed correctly under the "Constants" heading in the inspector window, and the local `my_const` const displayed as null under the "Locals" heading in the stack trace window.

### Minimal reproduction project (MRP)

[const-are-null-in-debugger.zip](https://github.com/user-attachments/files/16957264/const-are-null-in-debugger.zip)

### PR DESCRIPTION
**Pull request by Scrawach**
- Fixes: https://github.com/godotengine/godot/issues/96834

## Example

| Before | After |
|---|---|
| before_fix | after_fix |

## Details

By default, debugger get any local variables using stack. However, constant values are not in this stack. As a result, we get `null` when trying to get a constant value from stack.

## Fix

When setup function with constant values, I also added field with mapping constant names to values. And during debug get stack locals just use this values from constant map. I'm not sure how optimal this solution is. Perhaps there's another way without additional fields that would allow pushing constant value to stack immediately...

### CODE REVIEW

**Review by dalexeev — APPROVED** [review]
Looks good to me. :+1:

File: modules/gdscript/gdscript_function.h [hunk 1]
```diff
@@ -479,6 +479,7 @@ class GDScriptFunction {
 	Vector<int> code;
 	Vector<int> default_arguments;
 	Vector<Variant> constants;
+	HashMap<StringName, Variant> constant_map;
```
Comment (HolonProduction) [inline modules/gdscript/gdscript_function.h:482]: If this is only used for the debugger shouldn't we wrap it into an `#ifdef`?

Comment (dalexeev) [reply modules/gdscript/gdscript_function.h:482]: Similar fields aren't wrapped into an `#ifdef`. We also have a project setting to track locals even in release builds.
