### PR TITLE
Fix LIGHT compilation for canvas shader

### LINKED ISSUE #40425: [vulkan] Light2d overrides unshaded canvas_item
**Godot version:**
4.0.dev.calinou.3ed5ff244

**OS/device including version:**
Windows 10.0.18362.900, NVIDIA / Vulkan

**Issue description:**
I made a simple unshaded canvas_item shader. The color output by fragment is overridden by the light texture if no light() function is implemented.

This may be a duplicate of: https://github.com/godotengine/godot/issues/36112 - but the issue in this case is with unshaded objects which should not be interacting with light at all.

image

The bottom 3 objects assign to LIGHT= in the canvas_item shader, which causes a different bug

**Steps to reproduce:**
1. Create object with a simple shader, set to unshaded.
2. Create a small Light2d object.
3. Drag the Light2d around and notice that it covers the unshaded object.

**Minimal reproduction project:**
[CanvasLightingBug.zip](https://github.com/godotengine/godot/files/4927179/CanvasLightingBug.zip)

### LINKED ISSUE #40426: [vulkan] canvas_item shaders fail to compile if LIGHT= is assigned from void light()
**Godot version:**
4.0.dev.calinou.3ed5ff244

**OS/device including version:**
Windows 10.0.18362.900, NVIDIA / Vulkan

**Issue description:**
I made a simple unshaded canvas_item shader with a simple light() function that outputs to LIGHT. If I do this, it causes a vulkan 
[parse error in the console (attached)](https://github.com/godotengine/godot/files/4927223/v4.0.dev.calinou.3ed5ff244_output.txt)

image

The top 3 objects *do not* assign to LIGHT= in the shader, and thus compile correctly.

**Steps to reproduce:**
1. Create object with a simple shader, set to unshaded.
2. Implement a void light() function.
2. Optionally: create a small Light2d object, and drag it around. However, the error happens regardless.

**Minimal reproduction project:**
[CanvasLightingBug.zip](https://github.com/godotengine/godot/files/4927179/CanvasLightingBug.zip)

### PR DESCRIPTION
**Pull request by Chaosus**
Fix #40426 
Fix #40425
Supersedes #42754

### CODE REVIEW

File: servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp [hunk 1]
```diff
@@ -2506,7 +2506,7 @@ RendererCanvasRenderRD::RendererCanvasRenderRD(RendererStorageRD *p_storage) {
 		actions.renames["FRAGCOORD"] = "gl_FragCoord";
 		actions.renames["POINT_COORD"] = "gl_PointCoord";
 
-		actions.renames["LIGHT_POSITION"] = "light_pos";
+		actions.renames["LIGHT_POSITION"] = "light_position";
```
Comment (Chaosus) [inline servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:2509]: For info: It's renamed to conform with the parameter name in the `light_compute` function. Without it using LIGHT_POSITION leads to a shader crash.

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
