### PR TITLE
Prevent crash and error spam related to Sprite2D with a region

### LINKED ISSUE #84349: Crash when deleting Sprite2D with region, undoing
### Godot version

v4.2.beta4.official [93cdacbb0]

### System information

Windows 10

### Issue description

When I convert Sprite2D to mesh/polygon via sprite tools, undoing crashes the editor. It's not a big problem as it requires quite specific steps to trigger and converting a sprite with region doesn't seem to be fully supported anyway.
Error message:
```
Exception thrown at 0x00007FF7B0562753 in godot.windows.editor.x86_64.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
```

### Steps to reproduce

* Edit Sprite2D's region with region editor (note: manually setting region doesn't trigger the crash)
* ~~Convert to MeshInstance2D or Polygon2D~~ Delete the Sprite2D
* Undo x 2
crash

### Minimal reproduction project

N/A, happens on a clean project.

### PR DESCRIPTION
**Pull request by YuriSizov**
Fixes https://github.com/godotengine/godot/issues/84349 and a couple other problems.

1. The reported issue is related to deleting the node that was previously edited by the region editor, and then undoing this. Normally, UndoRedo actions should be attached to the edited objects themselves, but in this case the action is a part of the region editor, which no longer has a valid reference to work with. I made sure we don't handle invalid values, which leads to crashes, but there may be a further improvement possible in there. We could make sure that the historical reference to the edited object is preserved and used by the editor method. But for now fixing the crash should be good enough, and there should be no visible issues to the user.
2. Related to UndoRedo there was also an error message due to poor handling on the signal handlers. I adjusted the code to correctly disconnect them when the node disappears.
3. While testing the linked issue I noticed that regions don't work with the Sprite 2D editor, namely when converting sprites to 2D meshes. If the region is smaller than the texture, [the crop is misaligned](https://github.com/godotengine/godot/assets/11782833/f492b1db-46a7-4891-b7c8-b16201af1cfb). If the region is bigger than the texture, [there is error spam](https://github.com/godotengine/godot/assets/11782833/90c4d1d0-3d2d-4da4-a270-dde0969f5532) related to trying to access a bad pixel coordinate. I could probably fix it properly, but this close to the release I don't want to cause any further regressions. So I simply removed the region handling code, and it is for now simply ignored. It was introduced like that in the original PR in 9e3a1e5401f9f807085547de0ecc3f527610daa4, so it probably never worked.

While working on the third point I also cleaned up error handling logic, so error popups should now appear correctly, won't be obscured by the useless Sprite 2D editor, and excessive checks won't run on each update (since they don't validate anything that the user can change from the dialog anyway).

### CODE REVIEW

File: editor/plugins/sprite_2d_editor_plugin.cpp [hunk 1]
```diff
@@ -127,72 +127,67 @@ void Sprite2DEditor::_menu_option(int p_option) {
...
 		return;
 	}
 
+	_update_mesh_data();
+	debug_uv_dialog->popup_centered();
+	debug_uv->queue_redraw();
+}
+
+void Sprite2DEditor::_update_mesh_data() {
+	ERR_FAIL_COND(!node);
```
Comment (AThousandShips) [inline editor/plugins/sprite_2d_editor_plugin.cpp:178]:
```suggestion
	ERR_FAIL_NULL(node);
```

**Comment by aXu-AP** [comment]
I was also planning to fix the point no. 3. Do you want to add support for regions in converter afterwards or shall I try?

**Comment by YuriSizov** [comment]
@aXu-AP Feel free!

File: editor/plugins/texture_region_editor_plugin.cpp [hunk 2]
```diff
@@ -950,8 +950,9 @@ Rect2 TextureRegionEditor::_get_edited_object_region() const {
 		region = res_atlas_texture->get_region();
 	}
 
-	if (region == Rect2()) {
-		region = Rect2(Vector2(), _get_edited_object_texture()->get_size());
+	Ref<Texture2D> object_texture = _get_edited_object_texture();
```
Comment (KoBeWi) [inline editor/plugins/texture_region_editor_plugin.cpp:953]:
```suggestion
	const Ref<Texture2D> object_texture = _get_edited_object_texture();
```

**Review by KoBeWi — APPROVED** [review]

**Review by AThousandShips — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks for reviews!
