### PR TITLE
Fix unit suffix for `HingeJoint3D`'s target velocity

### LINKED ISSUE #80505: HingeJoint3D has wrong inspector unit type.
### Godot version

4.1

### System information

Win10

### Issue description

The unit is meters per second, rather than radians per second.
image

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by ElMikosch**
Fix #80505

I changed the suffix for HingeJoint3D/Motor/TargetVelocity to °/s as suggested in the Issue.

image

* *Bugsquad edit, alternative to: #80531*

### CODE REVIEW

**Comment by MewPurPur** [comment]
Did the issue not suggest radians?

**Comment by AThousandShips** [comment]
I don't think radians is appropriate, see my comment there, and also the fact that I don't think the range make sense as radians, 200 radians is 31 tuens

File: scene/3d/joint_3d.cpp [hunk 1]
```diff
@@ -310,7 +310,7 @@ void HingeJoint3D::_bind_methods() {
 	ADD_PROPERTYI(PropertyInfo(Variant::FLOAT, "angular_limit/relaxation", PROPERTY_HINT_RANGE, "0.01,16,0.01"), "set_param", "get_param", PARAM_LIMIT_RELAXATION);
 
 	ADD_PROPERTYI(PropertyInfo(Variant::BOOL, "motor/enable"), "set_flag", "get_flag", FLAG_ENABLE_MOTOR);
-	ADD_PROPERTYI(PropertyInfo(Variant::FLOAT, "motor/target_velocity", PROPERTY_HINT_RANGE, "-200,200,0.01,or_greater,or_less,suffix:m/s"), "set_param", "get_param", PARAM_MOTOR_TARGET_VELOCITY);
+	ADD_PROPERTYI(PropertyInfo(Variant::FLOAT, "motor/target_velocity", PROPERTY_HINT_RANGE, U"-200,200,0.01,or_greater,or_less,suffix:\u00B0/s"), "set_param", "get_param", PARAM_MOTOR_TARGET_VELOCITY);
```
Comment (AThousandShips) [inline scene/3d/joint_3d.cpp:313]:
```suggestion
	ADD_PROPERTYI(PropertyInfo(Variant::FLOAT, "motor/target_velocity", PROPERTY_HINT_RANGE, U"-200,200,0.01,or_greater,or_less,radians,suffix:\u00B0/s"), "set_param", "get_param", PARAM_MOTOR_TARGET_VELOCITY);
```
The data underlyingly seems to be radians, this change will make the value presented in degrees, without changing th stored value in the file

Comment (ElMikosch) [reply scene/3d/joint_3d.cpp]: changes done as suggested

File: scene/3d/joint_3d.cpp [hunk 2]
```diff
@@ -310,7 +310,7 @@ void HingeJoint3D::_bind_methods() {
 	ADD_PROPERTYI(PropertyInfo(Variant::FLOAT, "angular_limit/relaxation", PROPERTY_HINT_RANGE, "0.01,16,0.01"), "set_param", "get_param", PARAM_LIMIT_RELAXATION);
 
 	ADD_PROPERTYI(PropertyInfo(Variant::BOOL, "motor/enable"), "set_flag", "get_flag", FLAG_ENABLE_MOTOR);
-	ADD_PROPERTYI(PropertyInfo(Variant::FLOAT, "motor/target_velocity", PROPERTY_HINT_RANGE, "-200,200,0.01,or_greater,or_less,suffix:m/s"), "set_param", "get_param", PARAM_MOTOR_TARGET_VELOCITY);
+	ADD_PROPERTYI(PropertyInfo(Variant::FLOAT, "motor/target_velocity", PROPERTY_HINT_RANGE, U"-200,200,0.01,or_greater,or_less,radians,suffix:\u00B0/s"), "set_param", "get_param", PARAM_MOTOR_TARGET_VELOCITY);
```
Comment (AThousandShips) [inline scene/3d/joint_3d.cpp:313]:
```suggestion
	ADD_PROPERTYI(PropertyInfo(Variant::FLOAT, "motor/target_velocity", PROPERTY_HINT_RANGE, U"-200,200,0.01,or_greater,or_less,radians_as_degrees,suffix:\u00B0/s"), "set_param", "get_param", PARAM_MOTOR_TARGET_VELOCITY);
```
New syntax

Comment (YuriSizov) [reply scene/3d/joint_3d.cpp:313]: Yeah, I'll force-push in a second.

Comment (AThousandShips) [reply scene/3d/joint_3d.cpp:313]: Good, was aimed at the OP and wasn't sure if they were active

**Review by YuriSizov — APPROVED** [review]

**Review by AThousandShips — APPROVED** [review]
LGTM, unsure if the range is reasonable but can investigate that as a future change, along with other physics properties

File: scene/3d/joint_3d.cpp (hunk 2 above)
Comment (YuriSizov) [reply scene/3d/joint_3d.cpp]: Same, which is why I decided to do this cosmetic change myself. Besides, it's not their fault we renamed it 🙂

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
