### PR TITLE
Fix Viewport root order after Node2D raise

### LINKED ISSUE #44138: When Control nodes have Node2D as parents, the input events don't propagate correctly according to their index in their parent scene
**Godot version:**

3.2.3.stable.official

**OS/device including version:**

Windows 10 64bit

**Issue description:**

When two Control nodes which have a Node2D parent overlap, and one of them has been raised, the input events will still be received by the one that **used** to be the higher index node.

**Steps to reproduce:**

Create a scene with a Node2D and add a Panel node. Instance two copies of this scene overlapping in another node2d scene. raise() the lower index one. Now the input events and relevant signals (like mouse_entered) will be still received by the node which used to the the lower, even though it now has a lower index.

**Minimal reproduction project:**

[index_mouse_entered_bug.zip](https://github.com/godotengine/godot/files/5648151/index_mouse_entered_bug.zip)

In this project, you can mouse over each of the rectangles and it will highlight. Click on the bottom one to raise it. Now when you move in their overlapping area, the "bottom" one (i.e. the one with lower index) will highlight.

### PR DESCRIPTION
**Pull request by Sauermann**
fix #44138

After raising a `Node2D`, the Viewport root nodes need to be recalculated.

Updated 2022-10-22: remove need for friend class by making `gui_set_root_order_dirty` public; rebase to master.
Updated 2022-11-02: resolve merge conflict with #59479.

### CODE REVIEW

File: scene/main/viewport.h [hunk 1]
```diff
@@ -395,6 +395,7 @@ class Viewport : public Node {
 	Ref<InputEvent> _make_input_local(const Ref<InputEvent> &ev);
 
 	friend class Control;
+	friend class Node2D;
```
Comment (Sauermann) [inline scene/main/viewport.h:398]: An alternative would be to make _gui_set_root_order_dirty public.

File: scene/2d/node_2d.cpp [hunk 2]
```diff
@@ -366,6 +368,17 @@ bool Node2D::is_y_sort_enabled() const {
 	return y_sort_enabled;
 }
 
+void Node2D::_notification(int p_notification) {
+	switch (p_notification) {
+		case NOTIFICATION_MOVED_IN_PARENT: {
+			Viewport *viewport = get_viewport();
+			if (viewport) {
+				viewport->_gui_set_root_order_dirty();
```
Comment (Sauermann) [inline scene/2d/node_2d.cpp:376]: Would it make sense, to check, if the Node2D has a Control as a descendant?

File: scene/main/viewport.h (hunk 1 above)
Comment (Sauermann) [reply scene/main/viewport.h]: I believe that it is better to not add a friend class.

File: scene/2d/node_2d.cpp (hunk 2 above)
Comment (Sauermann) [reply scene/2d/node_2d.cpp]: Likely not a performance concern.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
