### PR TITLE
iOS: Fix loading of xcframework dynamic libraries.

### LINKED ISSUE #112783: Godot GDExtension loader has incorrect baked-in assumptions for iOS preventing xcframework from working
### Tested versions

4.5.stable and master as of bd2ca13c6f3a5198eac035c855dcd1759e077313

### System information

MacOS 26.0

### Issue description

The `GDExtensionLibraryLoader` has a special codepath for iOS that is used to determine whether a GDExtension is a static library, and thus should be resolved from the internal map of registered addresses of symbols or if it should attempt to call the platform dynamic loading capability.

This comes in the form of determining if this is a static library (`is_static_library`) based on the filename, and currently the test depends on whether the filename ends in ".a" or in ".xcframework" -  which is incorrect as .xcframework files can contain dynamic libraries - which the platform loader knows how to locate properly (Xcode upon deployment moves the libraries to a different location).

This information is later used to determine whether to perform an in-memory symbol lookup or to delegate to the system loader, but since the determination was incorrect at the start, the code that loads a dynamic library is never invoked, as we end up with a failure.

This prevents a project that references an add-on binary like this from working:

```
[libraries]
ios.debug = res://addons/MyAddon/MyAddon.xcframework
```

If such xcframework contains a dynamic library instead of a static library.

### Steps to reproduce

You can use my test case here, and export the game to iOS. 

To workaround, you need to follow the additional steps in the README:

https://github.com/migueldeicaza/SwiftGodotAppleTemplate

Use commit 51fb1424912ecba7af913e5caf13531e0522b971 in case I update that sample with additional workarounds.

### Minimal reproduction project (MRP)

https://github.com/migueldeicaza/SwiftGodotAppleTemplate

### PR DESCRIPTION
**Pull request by migueldeicaza**
The logic used to determine whether to invoke the in-memory registration or to
delegate the loading of a library is incorrect for xcframework packages - as
these can contain either static or dynamic libraries.  

This change instead lets the operating system handle the library request, and if
it fails, it attempts to load from the internal registry.

With this change, xcframeworks containing dynamic libraries work without
workarounds on iOS.

This fixes https://github.com/godotengine/godot/issues/112783

### CODE REVIEW

File: core/extension/gdextension_library_loader.cpp [hunk 1]
```diff
@@ -195,16 +195,21 @@ Error GDExtensionLibraryLoader::open_library(const String &p_path) {
...
+		}
 	}
 
 	return OK;
 }
 
 Error GDExtensionLibraryLoader::initialize(GDExtensionInterfaceGetProcAddress p_get_proc_address, const Ref<GDExtension> &p_extension, GDExtensionInitialization *r_initialization) {
-#ifdef TOOLS_ENABLED
+	printf("Hello World\n");
+	#ifdef TOOLS_ENABLED
```
Comment (akien-mga) [inline core/extension/gdextension_library_loader.cpp]:
```suggestion
#ifdef TOOLS_ENABLED
```

**Comment by akien-mga** [comment]
Could you amend the commit message to start with a single-line summary (like the PR's title)? Currently it starts directly with a long paragraph which doesn't work great with git log or GitHub to get an idea of what a commit does at a glance.

File: core/extension/gdextension_library_loader.cpp [hunk 2]
```diff
@@ -195,16 +195,21 @@ Error GDExtensionLibraryLoader::open_library(const String &p_path) {
 		&abs_dependencies_paths, // library_dependencies
 	};
 
-	err = OS::get_singleton()->open_dynamic_library(is_static_library ? String() : abs_path, library, &data);
+	// Apple has a complex lookup system which goes beyond looking up the filename, so we try that first
```
Comment (akien-mga) [inline core/extension/gdextension_library_loader.cpp]: Nitpick, not a blocker:
```suggestion
	// Apple has a complex lookup system which goes beyond looking up the filename, so we try that first.
```

**Review by akien-mga — APPROVED** [review]
Aside from the debug print and style formatting issue, looks good to me.

File: core/extension/gdextension_library_loader.cpp [hunk 3]
```diff
@@ -195,16 +195,21 @@ Error GDExtensionLibraryLoader::open_library(const String &p_path) {
...
+	err = OS::get_singleton()->open_dynamic_library(abs_path, library, &data);
```
Comment (bruvzg) [inline core/extension/gdextension_library_loader.cpp:199]: `open_dynamic_library` has `ERR_FAIL_COND_V(!FileAccess::exists(path), ERR_FILE_NOT_FOUND);`, so it will print unnecessary errors, probably better to add a silent return for `xcframeworks`, or directly fallback to loading static lib.

Might also worth adding few extra file path checks for xcframework with dylibs (exporter should convert these to frameworks, but won't hurt to have it just ion case it's added manually after project export or by editor plugin).

```diff
diff --git a/core/extension/gdextension_library_loader.cpp b/core/extension/gdextension_library_loader.cpp
index 0841443eba..5a842e3c4a 100644
--- a/core/extension/gdextension_library_loader.cpp
+++ b/core/extension/gdextension_library_loader.cpp
@@ -195,7 +195,7 @@ Error GDExtensionLibraryLoader::open_library(const String &p_path) {
                &abs_dependencies_paths, // library_dependencies
        };

-       err = OS::get_singleton()->open_dynamic_library(is_static_library ? String() : abs_path, library, &data);
+       err = OS::get_singleton()->open_dynamic_library(abs_path, library, &data);
        if (err != OK) {
                return err;
        }
@@ -361,8 +361,6 @@ Error GDExtensionLibraryLoader::parse_gdextension_file(const String &p_path) {
                return ERR_FILE_NOT_FOUND;
        }

-       is_static_library = library_path.ends_with(".a") || library_path.ends_with(".xcframework");
-
        if (!library_path.is_resource_file() && !library_path.is_absolute_path()) {
                library_path = p_path.get_base_dir().path_join(library_path);
        }
diff --git a/core/extension/gdextension_library_loader.h b/core/extension/gdextension_library_loader.h
index 75ad0ebedf..d416c83da7 100644
--- a/core/extension/gdextension_library_loader.h
+++ b/core/extension/gdextension_library_loader.h
@@ -49,8 +49,6 @@ private:
        String library_path;
        String entry_symbol;

-       bool is_static_library = false;
-
 #ifdef TOOLS_ENABLED
        bool is_reloadable = false;
 #endif
diff --git a/drivers/apple_embedded/os_apple_embedded.mm b/drivers/apple_embedded/os_apple_embedded.mm
index eab16ead8b..53c5f093b2 100644
--- a/drivers/apple_embedded/os_apple_embedded.mm
+++ b/drivers/apple_embedded/os_apple_embedded.mm
@@ -279,6 +279,11 @@ Rect2 fit_keep_aspect_covered(const Vector2 &p_container, const Vector2 &p_rect)
                path = get_framework_executable(get_executable_path().get_base_dir().path_join(p_path.get_file().get_basename() + ".framework"));
        }

+       if (!FileAccess::exists(path)) {
+               // Load .dylib from within the executable path.
+               path = get_framework_executable(get_executable_path().get_base_dir().path_join(p_path.get_file().get_basename() + ".dylib"));
+       }
+
        if (!FileAccess::exists(path)) {
                // Load .dylib or framework from a standard iOS location.
                path = get_framework_executable(get_executable_path().get_base_dir().path_join("Frameworks").path_join(p_path.get_file()));
@@ -289,7 +294,16 @@ Rect2 fit_keep_aspect_covered(const Vector2 &p_container, const Vector2 &p_rect)
                path = get_framework_executable(get_executable_path().get_base_dir().path_join("Frameworks").path_join(p_path.get_file().get_basename() + ".framework"));
        }

-       ERR_FAIL_COND_V(!FileAccess::exists(path), ERR_FILE_NOT_FOUND);
+       if (!FileAccess::exists(path)) {
+               // Load .dylib from a standard iOS location.
+               path = get_framework_executable(get_executable_path().get_base_dir().path_join("Frameworks").path_join(p_path.get_file().get_basename() + ".dylib"));
+       }
+
+       if (!FileAccess::exists(path) && (p_path.ends_with(".a") || p_path.ends_with(".xcframework"))) {
+               path = String(); // Try loading static library.
+       } else {
+               ERR_FAIL_COND_V(!FileAccess::exists(path), ERR_FILE_NOT_FOUND);
+       }

        p_library_handle = dlopen(path.utf8().get_data(), RTLD_NOW);
        ERR_FAIL_NULL_V_MSG(p_library_handle, ERR_CANT_OPEN, vformat("Can't open dynamic library: %s. Error: %s.", p_path, dlerror()));
```

File: core/extension/gdextension_library_loader.cpp (hunk 1 above)
Comment (migueldeicaza) [reply core/extension/gdextension_library_loader.cpp]: Oops, my secret debugging technique has been leaked.

Fixing.

File: core/extension/gdextension_library_loader.cpp (hunk 3 above)
Comment (migueldeicaza) [reply core/extension/gdextension_library_loader.cpp:199]: Good catch on the error spam.

**Comment by migueldeicaza** [comment]
Incorporated all of the changes and tested against the sample to validate.

**Comment by Repiteo** [comment]
Thanks!

**Comment by van800** [comment]
I am seeing that this call `err = OS::get_singleton()->open_dynamic_library(String(), library, &data);`
``
https://github.com/godotengine/godot/pull/112784/files#diff-e2d7d89fb250a3270c869172ceda504df5eb1f49801a1ba1cd4d2ff34e1f05ccR201

on **Windows** is giving confusing error messages, which can masks the real problem.
```
  ERROR: Can't open dynamic library: C:/Users/Ivan.Shakhov/RiderProjects/Godot4/addons/Godot4Ext/bin/./windows/Godot4Ext.windows.template_debug.x86_64.dll. Error: Error 126: The specified module could not be found..
  ERROR: platform/windows/os_windows.cpp:487 - Condition "!FileAccess::exists(path)" is true. Returning: ERR_FILE_NOT_FOUND
  ERROR: GDExtension dynamic library not found: 'res://addons/Godot4Ext/bin/Godot4Ext.gdextension'.
```

In this message, the line 
```
ERROR: platform/windows/os_windows.cpp:487 - Condition "!FileAccess::exists(path)" is true. Returning: ERR_FILE_NOT_FOUND
```
is the misleading one, which should not be shown.

**Comment by van800** [comment]
I guess this would be better
https://github.com/godotengine/godot/pull/119510
