### PR TITLE
Fix enum autocompletion for core classes

### LINKED ISSUE #88858: Autocompletion does not suggest enum names for core classes
### Tested versions

- Reproducible in: 4.3.dev [99addd6d9c04e38da27c9001376dce920a1b690a] and before

### System information

Windows 11

### Issue description

The completion misses enum names. For example, in Control class there are constant names presented, but not enum names where these constants placed (Anchor, CursorShape etc):

изображение

It's wrong because such code is correct and must be a subject for autocompletion:

изображение

### Steps to reproduce

^^

### Minimal reproduction project (MRP)

No need - too trivial to reproduce.

### PR DESCRIPTION
**Pull request by dcaoc03**
While writing a gdscript, autocompletion wouldn't suggest Enum names for core classes and also wouldn't suggest Enum Values even after the Enum name had been typed. This has now been fixed.

Now, while finding identifiers in a class, enumeration names are also fetched and enumeration constants are now suggested as well.

Fixes #88858.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @HolonProduction

File: modules/gdscript/gdscript_editor.cpp [hunk 1]
```diff
@@ -1198,13 +1198,14 @@ static void _find_identifiers_in_base(const GDScriptCompletionIdentifier &p_base
 					return;
 				}
 
+				List<StringName> enums;
+				ClassDB::get_enum_list(type, &enums);
+				for (const StringName &E : enums) {
+					ScriptLanguage::CodeCompletionOption option(E, ScriptLanguage::CODE_COMPLETION_KIND_ENUM);
```
Comment (HolonProduction) [inline modules/gdscript/gdscript_editor.cpp:1204]: The option should also get a location

File: modules/gdscript/gdscript_editor.cpp [hunk 2]
```diff
@@ -1264,7 +1265,19 @@ static void _find_identifiers_in_base(const GDScriptCompletionIdentifier &p_base
...
-			case GDScriptParser::DataType::ENUM:
+			case GDScriptParser::DataType::ENUM: {
+				String type_str = base_type.native_type;
+				StringName type = type_str.substr(0, type_str.find("."));
+				StringName type_enum = base_type.enum_type;
+
+				List<StringName> enum_values;
+				ClassDB::get_enum_constants(type, type_enum, &enum_values);
+				for (const StringName &E : enum_values) {
+					ScriptLanguage::CodeCompletionOption option(E, ScriptLanguage::CODE_COMPLETION_KIND_CONSTANT);
```
Comment (HolonProduction) [inline modules/gdscript/gdscript_editor.cpp:1276]: And here as well a location is needed.

(If you don't know how, have a look at how the other locations are constructed. Should be quite similar here.)

**Review by HolonProduction — CHANGES_REQUESTED** [review]
I can confirm, that the changes solve the issue :+1:

Still the location should get set correctly as well. Otherwise we might run into sorting problems.

Besides that it would be nice to have tests to ensure this working. Would be nice if you could add them. (The whole [testing system for autocompletion](https://github.com/godotengine/godot/tree/master/modules/gdscript/tests#gdscript-autocompletion-tests), is quite new and might have some rough edges. So if you don't know how, feel free to ask, or just don't do it and I'll put the issue on my todo list.)

**Comment by dcaoc03** [comment]
Sure thing! I'll be sure to add the locations and try to do some tests.

**Comment by dcaoc03** [comment]
@HolonProduction just to be sure I understood the autocompletion test syntax. A very simple test could look like this:

enum_values_autocompletion.gd
```
extends Control

func _ready():
    AStarGrid2D.Heuristic.➡

``` 

enum_values_autocompletion.cfg
```
[output]
include=[
    {"display": "HEURISTIC_MAX"},
    {"display": "HEURISTIC_OCTILE"},
]
``` 
Please feel free to correct me, I'll be sure to fix anything before committing any new changes.

**Comment by dcaoc03** [comment]
@HolonProduction sorry to bother again, but I'm not sure on how I should be testing the value of location. In my test, I'm autocompleting a node of type `BaseButton` (which inherits from Control) and my .cfg looks like this:
```
[output]
include=[
    {"display": "DrawMode",
     "location": },
    {"display": "Anchor",
     "location": },
]
```
In this case, the location of `DrawMode` should be `LOCATION_OTHER` and the location of `Achor` should be `LOCATION_OTHER + 1`, but it seems that I can't directly define "location" as `LOCATION_OTHER `in the .cfg.

File: modules/gdscript/gdscript_editor.cpp [hunk 3]
```diff
@@ -1264,7 +1265,19 @@ static void _find_identifiers_in_base(const GDScriptCompletionIdentifier &p_base
 				}
 				return;
 			} break;
-			case GDScriptParser::DataType::ENUM:
+			case GDScriptParser::DataType::ENUM: {
+				String type_str = base_type.native_type;
+				StringName type = type_str.substr(0, type_str.find("."));
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_editor.cpp:1270]:
```suggestion
				StringName type = type_str.get_slicec('.', 0);
```
Better method for this specific use

File: modules/gdscript/gdscript_editor.cpp [hunk 4]
```diff
@@ -1264,7 +1265,19 @@ static void _find_identifiers_in_base(const GDScriptCompletionIdentifier &p_base
...
+				StringName type_enum = base_type.enum_type;
+
+				List<StringName> enum_values;
+				ClassDB::get_enum_constants(type, type_enum, &enum_values);
+				for (const StringName &E : enum_values) {
+					ScriptLanguage::CodeCompletionOption option(E, ScriptLanguage::CODE_COMPLETION_KIND_CONSTANT);
+					r_result.insert(option.display, option);
+				}
+			}
+				[[fallthrough]];
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_editor.cpp:1280]: Put after the bracket directly, cleaner

**Comment by HolonProduction** [comment]
> In this case, the location of `DrawMode` should be `LOCATION_OTHER` and the location of `Achor` should be `LOCATION_OTHER + 1`, but it seems that I can't directly define "location" as `LOCATION_OTHER `in the .cfg.

From the code `LOCATION_OTHER` is `1 << 10` or `1024`.

File: modules/gdscript/gdscript_editor.cpp (hunk 4 above)
Comment (dcaoc03) [reply modules/gdscript/gdscript_editor.cpp]: I did this and the "Style checks via pre-commit" test didn't allow it, shall I put it back as it was?

Comment (AThousandShips) [reply modules/gdscript/gdscript_editor.cpp:1297]: Sorry for missing this, yes, but odd too, I've seen it like that too

**Review by HolonProduction — APPROVED** [review]
Gave it another test and seems to work well with the sorting. Code makes sense as well and the tests seem to pass. LGTM

Still needs approval from the GDScript Core team though

**Review by vnen — COMMENTED** [review]
LGTM

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
