### PR TITLE
Ignore the classes in the recent and favorite panels of the create dialog if they are disabled

### LINKED ISSUE #33420: Manage Editor Features does not removes nodes from Recent list
**Godot version:**
3.2 beta
**OS/device including version:**
Windows 7
**Issue description:**
I have disabled 3D editor features and Spatial nodes.
image
image

But Spatial nodes are still present in recent list
image

**Steps to reproduce:**
1.Disable Spatial nodes
2. See Recent in new node dialog
**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by PucklaJ**
Fixes #33420

Now when opening a create node dialog the classes that will potentially added to the recent panel get checked whether they are disabled through the editor manage features dialog.

Also it seems that when checking if a class is disabled. The classes parents weren't checked. This means that you could disable Spatial, but if you call is_class_disabled on Camera, it would still return false.

### CODE REVIEW

File: editor/create_dialog.cpp [hunk 1]
```diff
@@ -37,6 +37,7 @@
 #include "editor_node.h"
 #include "editor_settings.h"
 #include "scene/gui/box_container.h"
+#include "editor_feature_profile.h"
```
Comment (akien-mga) [inline editor/create_dialog.cpp]: Includes should be ordered alphabetically, see http://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html#header-includes

File: editor/editor_feature_profile.cpp [hunk 2]
```diff
@@ -64,7 +64,10 @@ void EditorFeatureProfile::set_disable_class(const StringName &p_class, bool p_d
 }
 
 bool EditorFeatureProfile::is_class_disabled(const StringName &p_class) const {
-	return disabled_classes.has(p_class);
+	if(!ClassDB::class_exists(p_class)) {
```
Comment (akien-mga) [inline editor/editor_feature_profile.cpp]: There should be a space between `if` and `(`, see http://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html

**Comment by PucklaMotzer09** [comment]
Fixed crashing of the editor when no profile is set.

**Comment by akien-mga** [comment]
I had forgotten about this PR and merged a new one that only addresses part of the problem (#34898). Would you be able to rebase this PR on the current master branch so that we can also merge the part that fixes the favorite?

**Comment by PucklaMotzer09** [comment]
I will work on that

**Comment by PucklaMotzer09** [comment]
I rebased and the PR is ready to be merged.

**Comment by akien-mga** [comment]
Thanks!
