### PR TITLE
Return only scenes for script owners on LSP completion

### LINKED ISSUE #36680: LSP Completion an script that extends another script crashs Godot
**Godot version:**
3.2 branch with this https://github.com/godotengine/godot/pull/36521

**OS/device including version:**
Arch Linux 5.5.5

**Issue description:**
LSP crashes Godot when a script inherits another script.

**Steps to reproduce:**
Create two scripts and make one inherits another (character -> player), open the base script (character) and try auto-completion over LSP.

**Backtrace**
```
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x3bd70) [0x7fbcacedad70] (??:0)
[2] Ref<SceneState>::operator->() const (/home/delboni/Workspace/godot/./core/reference.h:117)
[3] PackedScene::instance(PackedScene::GenEditState) const (/home/delboni/Workspace/godot/scene/resources/packed_scene.cpp:1695)
[4] GDScriptWorkspace::_get_owner_node(String) (/home/delboni/Workspace/godot/modules/gdscript/language_server/gdscript_workspace.cpp:416)
[5] GDScriptWorkspace::completion(lsp::CompletionParams const&, List<ScriptCodeCompletionOption, DefaultAllocator>*) (/home/delboni/Workspace/godot/modules/gdscript/language_server/gdscript_workspace.cpp:430 (discriminator 1))
[6] GDScriptTextDocument::completion(Dictionary const&) (/home/delboni/Workspace/godot/modules/gdscript/language_server/gdscript_text_document.cpp:152 (discriminator 3))
[7] MethodBind1R<Array, Dictionary const&>::call(Object*, Variant const**, int, Callable::CallError&) (/home/delboni/Workspace/godot/./core/method_bind.gen.inc:961 (discriminator 9))
[8] Object::call(StringName const&, Variant const**, int, Callable::CallError&) (/home/delboni/Workspace/godot/core/object.cpp:903 (discriminator 1))
[9] Object::callv(StringName const&, Array const&) (/home/delboni/Workspace/godot/core/object.cpp:811)
[10] JSONRPC::process_action(Variant const&, bool) (/home/delboni/Workspace/godot/modules/jsonrpc/jsonrpc.cpp:125 (discriminator 1))
[11] JSONRPC::process_string(String const&) (/home/delboni/Workspace/godot/modules/jsonrpc/jsonrpc.cpp:160 (discriminator 1))
[12] GDScriptLanguageProtocol::process_message(String const&) (/home/delboni/Workspace/godot/modules/gdscript/language_server/gdscript_language_protocol.cpp:140)
[13] GDScriptLanguageProtocol::LSPeer::handle_data() (/home/delboni/Workspace/godot/modules/gdscript/language_server/gdscript_language_protocol.cpp:95)
[14] GDScriptLanguageProtocol::poll() (/home/delboni/Workspace/godot/modules/gdscript/language_server/gdscript_language_protocol.cpp:243)
[15] GDScriptLanguageServer::_notification(int) (/home/delboni/Workspace/godot/modules/gdscript/language_server/gdscript_language_server.cpp:63)
[16] GDScriptLanguageServer::_notificationv(int, bool) (/home/delboni/Workspace/godot/modules/gdscript/language_server/gdscript_language_server.h:39 (discriminator 14))
[17] Object::notification(int, bool) (/home/delboni/Workspace/godot/core/object.cpp:915)
[18] SceneTree::_notify_group_pause(StringName const&, int) (/home/delboni/Workspace/godot/scene/main/scene_tree.cpp:988)
[19] SceneTree::idle(float) (/home/delboni/Workspace/godot/scene/main/scene_tree.cpp:526 (discriminator 3))
[20] Main::iteration() (/home/delboni/Workspace/godot/main/main.cpp:2062)
[21] OS_X11::run() (/home/delboni/Workspace/godot/platform/x11/os_x11.cpp:3321)
[22] /home/delboni/Workspace/godot/bin/godot.x11.tools.64(main+0x121) [0x16fa8c7] (/home/delboni/Workspace/godot/platform/x11/godot_x11.cpp:57)
[23] /usr/lib/libc.so.6(__libc_start_main+0xf3) [0x7fbcacec6023] (??:0)
[24] /home/delboni/Workspace/godot/bin/godot.x11.tools.64(_start+0x2e) [0x16fa6ee] (??:?)
-- END OF BACKTRACE --

```

### PR DESCRIPTION
**Pull request by rafaeldelboni**
Fix: #36680

### CODE REVIEW

**Comment by rafaeldelboni** [comment]
@akien-mga when merged, this should be cherry-picked thoghether with this https://github.com/godotengine/godot/pull/36521

**Comment by Geequlim** [comment]
You can check the type of the loaded resource is `PackedScene` instead of force extention to `.tscn` as scenes may be `.scn`, `.res`, `.tres`.

File: modules/gdscript/language_server/gdscript_workspace.cpp [hunk 1]
```diff
@@ -396,24 +396,26 @@ void GDScriptWorkspace::_get_owners(EditorFileSystemDirectory *efsd, String p_pa
...
-	_get_owners(EditorFileSystem::get_singleton()->get_filesystem(), p_path, owners);
+	_get_owner_scenes(EditorFileSystem::get_singleton()->get_filesystem(), p_path, owner_scenes);
 
-	if (owners.size() > 0) {
-		NodePath owner_path = owners[0];
-		Ref<PackedScene> owner_res = ResourceLoader::load(owner_path);
-		owner_node = owner_res->instance(PackedScene::GEN_EDIT_STATE_DISABLED);
+	if (owner_scenes.size() > 0) {
+		NodePath owner_scene_path = owner_scenes[0];
+		Ref<PackedScene> owner_scene_res = ResourceLoader::load(owner_scene_path);
```
Comment (Geequlim) [inline modules/gdscript/language_server/gdscript_workspace.cpp]: Check `owner_scene_res ` is valid here.
If it is not valid check next path in the vector you filled.

**Review by Geequlim — CHANGES_REQUESTED** [review]

File: modules/gdscript/language_server/gdscript_workspace.cpp (hunk 1 above)
Comment (rafaeldelboni) [reply modules/gdscript/language_server/gdscript_workspace.cpp]: @Geequlim Could you help me with this one? How can I do this check, is there any props in the PackedScene I could look into?

Comment (rafaeldelboni) [reply modules/gdscript/language_server/gdscript_workspace.cpp]: Can't we do something like this:
https://github.com/godotengine/godot/blob/master/main/main.cpp#L1460

Comment (rafaeldelboni) [reply modules/gdscript/language_server/gdscript_workspace.cpp]: Ok nvm, I figured out gonna send a new commit soon

**Comment by rafaeldelboni** [comment]
@Geequlim could you check again?

File: modules/gdscript/language_server/gdscript_workspace.cpp [hunk 2]
```diff
@@ -401,19 +401,23 @@ void GDScriptWorkspace::_get_owners(EditorFileSystemDirectory *efsd, String p_pa
...
 	_get_owners(EditorFileSystem::get_singleton()->get_filesystem(), p_path, owners);
 
-	if (owners.size() > 0) {
-		NodePath owner_path = owners[0];
-		Ref<PackedScene> owner_res = ResourceLoader::load(owner_path);
-		owner_node = owner_res->instance(PackedScene::GEN_EDIT_STATE_DISABLED);
+	for (int i = 0; i < owners.size(); i++) {
+		NodePath owner_path = owners[i];
+		RES owner_res = ResourceLoader::load(owner_path);
+		if (owner_res->get_class() == "PackedScene") {
```
Comment (Geequlim) [inline modules/gdscript/language_server/gdscript_workspace.cpp]: Using `Object::cast_to<PackedScene>(owner_res.ptr())` instead of the name of the class for type checking should be better for future refactor.

**Review by Geequlim — CHANGES_REQUESTED** [review]

**Review by Geequlim — APPROVED** [review]

**Comment by rafaeldelboni** [comment]
@akien-mga I think this is ready to merge into master 😀

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.
