### PR TITLE
Properly report missing nodes in LightmapGI

### LINKED ISSUE #104229: Error spam from LightmapGI when the baked scene changes
### Tested versions

v4.4.1.rc1.official [daa4b058e]
Was happening before 4.4 as well

### System information

Godot v4.4.1.rc1 - macOS Sequoia (15.1.0) - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M1 Max (Apple7) - Apple M1 Max (10 threads)

### Issue description

When you're working on a scene it's normal for it to change a lot. Reimporting a big external scene with hundreds of nodes gives an enormous wall of errors that makes it hard to see other error messages that are actually meaningful.

It would be better for it to fail silently when it can't find previously baked nodes

https://github.com/user-attachments/assets/8001c6eb-c521-43d0-a000-802673b0c782

### Steps to reproduce

Open the MRP, delete some meshes, save, restart editor (or just reopen/reload the scene)

### Minimal reproduction project (MRP)

[mrp_lightmap_errors.zip](https://github.com/user-attachments/files/19270778/mrp_lightmap_errors.zip)

### PR DESCRIPTION
**Pull request by passivestar**
Closes #104229

| Before | After |
|--------|--------|
| before | after |

### CODE REVIEW

**Review by lander-vr — APPROVED** [review]
Tested and works as expected. ~~I'm curious if the warning itself is still needed though? I'm not sure I see a practical use for it, I feel like it would be fine to just handle this entirely silently.~~

https://github.com/user-attachments/assets/e9f689f6-d83d-4aeb-9f50-9272b4453909

Edit: 
Nevermind, I just realised it leaves a single warning, and not one for each node! This seems perfectly fine as is!

**Review by clayjohn — APPROVED** [review]

File: scene/3d/lightmap_gi.cpp [hunk 1]
```diff
@@ -1525,12 +1532,25 @@ void LightmapGI::_assign_lightmaps() {
...
 	}
+
+	if (!missing_node_paths.is_empty()) {
+		String missing_paths_text;
+		if (missing_node_paths.size() <= 3) {
+			missing_paths_text = String(", ").join(missing_node_paths);
+		} else {
+			missing_paths_text = vformat("%s and %d more", String(", ").join(missing_node_paths.slice(0, 3)), missing_node_paths.size() - 3);
+		}
+		WARN_PRINT(vformat("%s couldn't find previously baked nodes and needs a rebake (Missing nodes: %s).", get_name(), missing_paths_text));
```
Comment (Calinou) [inline scene/3d/lightmap_gi.cpp:1543]:
```suggestion
		WARN_PRINT(vformat("%s couldn't find previously baked nodes and needs a rebake (missing nodes: %s).", get_name(), missing_paths_text));
```

**Review by Calinou — APPROVED** [review]
Code looks good to me.

**Comment by Repiteo** [comment]
Thanks!
