### PR TITLE
OS: Add `unset_environment`, better validate input

### LINKED ISSUE #57403: Vulkan: MangoHud breaks rendering unless single-window mode is enabled
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

EndeavourOS(Arch linux) KDE, AMD Ryzen 5 3400g Vega11, AMDVLK 2022.Q1.1-1 64bit on Vulkan API 1.2.203

### Issue description

After opening Godot' projects lists there is dialog box asking about downloading projects from asset library or creating on your own and it doesn't load properly making UI basically useless, doesn't happen on 32bit version of the editor.
logs from the terminal:
```
Godot Engine v4.0.alpha1.official.31a7ddbf8 - https://godotengine.org
ERROR: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        loader_scanned_icd_add: Driver /usr/lib/amdvlk64.so says it supports interface version 6 but still exports core entrypoints (Policy #LDP_DRIVER_6)
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 128156400
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:157)
[2022-01-29 15:10:24.472] [MANGOHUD] [info] [config.cpp:114] skipping config: '/home/boomer/Download/MangoHud.conf' [ not found ]
[2022-01-29 15:10:24.472] [MANGOHUD] [info] [config.cpp:114] skipping config: '/home/boomer/.config/MangoHud/Godot_v4.0-alpha1_linux.64.conf' [ not found ]
[2022-01-29 15:10:24.472] [MANGOHUD] [info] [config.cpp:119] parsing config: '/home/boomer/.config/MangoHud/MangoHud.conf'
Vulkan API 1.2.203 - Using Vulkan Device #0: AMD - AMD Radeon Vega 11 Graphics
[2022-01-29 15:10:24.569] [MANGOHUD] [info] [overlay.cpp:678] Uploading is disabled (permit_upload = 0)
```
 
HAPPEN ON THE RADEON DRIVER TOO!

### Steps to reproduce

Run 64bit of Godot 4.0 and load empty projects list

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by akien-mga**
Instead of returning an undocumented boolean error code, we do the validation checks that should ensure a successful result.

Based on:
- https://linux.die.net/man/3/setenv
- https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setenvironmentvariable

---

Use case: To fix #57403, I need to be able to unset the `DISABLE_MANGOHUD` environment variable on Linux. Setting it to 0 or an empty value isn't enough, it needs to be fully unset and we didn't have a method to do this in a cross-platform way.

### CODE REVIEW

File: platform/windows/os_windows.cpp [hunk 1]
```diff
@@ -1166,8 +1166,14 @@ String OS_Windows::get_environment(const String &p_var) const {
 	return "";
 }
 
-bool OS_Windows::set_environment(const String &p_var, const String &p_value) const {
-	return (bool)SetEnvironmentVariableW((LPCWSTR)(p_var.utf16().get_data()), (LPCWSTR)(p_value.utf16().get_data()));
+void OS_Windows::set_environment(const String &p_var, const String &p_value) const {
+	ERR_FAIL_COND_MSG(p_var.is_empty() || p_var.contains("="), vformat("Invalid environment variable name '%s', cannot be empty or include '='.", p_var));
+	ERR_FAIL_COND_V_MSG(p_value.length() > 32767, vformat("Invalid value for environment variable '%s', cannot exceed 32767 characters.", p_var));
```
Comment (akien-mga) [inline platform/windows/os_windows.cpp:1171]: Might need testing @bruvzg, I just based this off the docs.

Comment (bruvzg) [reply platform/windows/os_windows.cpp:1171]: Probably should `p_value.utf16().length()`, it's `32,767 characters` in docs, and usually it this is the number of UTF-16 code points. Also, it's probably a combined limit for both name and value + "=" + null terminator (`Var1=Value1\0`).

Comment (bruvzg) [reply platform/windows/os_windows.cpp]: Maybe something like this to avoid double conversion and string concat.

```
	ERR_FAIL_COND_MSG(p_var.is_empty() || p_var.contains("="), vformat("Invalid environment variable name '%s', cannot be empty or include '='.", p_var));
	Char16String var = p_var.utf16();
	Char16String value = p_value.utf16();
	ERR_FAIL_COND_MSG(var.length() + value.leght() + 2 > 32767, vformat("Invalid definition for environment variable '%s', cannot exceed 32767 characters.", p_var));
	SetEnvironmentVariableW((LPCWSTR)(var.get_data()), (LPCWSTR)(value.get_data()));
```

Comment (akien-mga) [reply platform/windows/os_windows.cpp]: Thanks, used that and improved the doc as I could.

> On Windows, there is a 32767 characters limit for the combined length of [param variable], [param value], and the [code]=[/code] and null terminator characters that will be registered in the environment block.

I think we have better docs than MSDN for this now :P

**Review by reduz — APPROVED** [review]
