### PR TITLE
Remove Unnecessary __meta__ added to scene

### LINKED ISSUE #58940: Unnecessary __meta__ added to scene
### Godot version

v4.0.alpha4

### System information

Windows 10

### Issue description

Maybe similar to this bug about _edit_use_anchors_:
https://github.com/godotengine/godot/issues/57862

if i make a new Control scene, add a ColorRect, drag it, and save this gets added to the scene
seem like it is the default values so maybe not needed again
thanks

	__meta__ = {
	"_edit_layout_mode": 0,
	"_edit_use_custom_anchors": false
	}

### Steps to reproduce

- new project, Control scene, and ColorRect
- drag ColorRect and save
- inspect scene file

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by NeilKleistGao**
related issue: #58940 
Remove metadata `_edit_layout_mode` and `_edit_use_custom_anchors` if they have default values.
Now moving control nodes will not lead to an unnecessary __meta__ in the scene file.

*Bugsquad edit:* Fixes #58940

### CODE REVIEW

File: scene/gui/control.cpp [hunk 1]
```diff
@@ -1508,7 +1508,10 @@ void Control::_set_layout_mode(LayoutMode p_mode) {
 		set_meta("_edit_layout_mode", (int)p_mode);
 
 		if (p_mode == LayoutMode::LAYOUT_MODE_POSITION) {
-			set_meta("_edit_use_custom_anchors", false);
+			remove_meta("_edit_layout_mode");
+			if (has_meta("_edit_use_custom_anchors")) {
```
Comment (KoBeWi) [inline scene/gui/control.cpp:1512]: The check is not necessary. Removing non-existent meta simply does nothing.

**Review by KoBeWi — APPROVED** [review]
There is another case of unnecessary meta when you set to Anchor mode then select Custom and return to non-Custom. It would be nice if you could fix that too.

Still, the PR fixes the issue, so it's ok.

**Review by Calinou — APPROVED** [review]
Thanks!
