### PR TITLE
Fix the text editor confusing resource files of class JSON with json files.

### LINKED ISSUE #109473: JSON Resource gets "unknown error getting token" when opening in the editor
### Tested versions

v4.4.1.stable
v4.5 beta 5

### System information

Godot v4.4.1.stable - Windows 11 (build 26100) - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - Quadro T2000 - Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 threads)

### Issue description

Upon opening a JSON .tres Resource in the editor after restarting/opening the editor, data does not show with "Unknown error getting token" showing up. The data field in the inspector also gets set to null.
Image
Data is still accessible in file location, but unable to be accessed in the editor.

### Steps to reproduce

- Open MRP
- Try to open test_json.tres in the FileSystem

### Minimal reproduction project (MRP)

[mrp_json_resource_issue.zip](https://github.com/user-attachments/files/21702227/mrp_json_resource_issue.zip)

### PR DESCRIPTION
**Pull request by jroprohehe**
Fixes #109473

### CODE REVIEW

File: editor/script/script_editor_plugin.cpp [hunk 1]
```diff
@@ -2525,6 +2525,12 @@ bool ScriptEditor::edit(const Ref<Resource> &p_resource, int p_line, int p_col,
 	if (p_resource.is_null()) {
 		return false;
 	}
+	// This is here to stop resource files of class JSON from getting confused
+	//	with json files and being opened in the text editor.
+	// See https://github.com/godotengine/godot/issues/109473
+	if (p_resource->get_class() == JSON::get_class_static() && p_resource->get_path().get_extension().to_lower() != "json") {
+		return false;
+	}
```
Comment (Rindbee) [inline editor/script/script_editor_plugin.cpp]: A more appropriate place to do this is in `ScriptEditorPlugin::handles()`.

Comment (jroprohehe) [reply editor/script/script_editor_plugin.cpp]: True

**Review by kitbdev — APPROVED** [review]
Fixes the issue. This will need to be [squashed](https://contributing.godotengine.org/en/latest/organization/pull_requests/creating_pull_requests.html#the-interactive-rebase) into a single commit.

**Comment by jroprohehe** [comment]
Bump. I squashed the commits into one.

File: editor/script/script_editor_plugin.cpp [hunk 2]
```diff
@@ -4645,7 +4645,11 @@ bool ScriptEditorPlugin::handles(Object *p_object) const {
 	}
 
 	if (Object::cast_to<JSON>(p_object)) {
-		return true;
+		// This is here to stop resource files of class JSON from getting confused
+		//      with json files and being opened in the text editor.
```
Comment (AThousandShips) [inline editor/script/script_editor_plugin.cpp]:
```suggestion
		// with json files and being opened in the text editor.
```
Doe readability

Comment (jroprohehe) [reply editor/script/script_editor_plugin.cpp]: k

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
