### PR TITLE
Fix LSP parsing get_node only from the scene root

### LINKED ISSUE #291: Relative path for get_node is wrong
My hierarchy looks like this:
image

In the script on the `UI` node, I have the following code:
```gdscript
var p = get_node("../Player")
```

Which works, but the type of `p` is not known by the extension unless I do this:
```gdscript
var p = get_node("Player")
```

In which case, `p` is always null because `get_node` gets its relative path from inside of the node that the script is on.

I have not been using Godot for very long, so I might be misunderstanding some concepts, but I have a suspicion that this is a bug.

Although perhaps the extension is unaware of context in this case and it might not even be possible (or make sense) to fix this?

### LINKED ISSUE #51282: LSP's completion parses get_node() from scene root regardless of node position
### Godot version

4.0.dev, 3.x

### System information

Windows 10

### Issue description

Calling `get_node()` in an external editor connecting to the LSP parses the scene tree only from the root of the scene that the script is being called from. As reported in godotengine/godot-vscode-plugin#291

### Steps to reproduce

Scene:
```
Node
    Node1 (test.gd)
    Node2
```
test.gd
```gdscript
extends Node

func _ready():
    get_node("../Node2") # will not detect the node even if it's right
    get_node("Node2") # will detect the node even though it's wrong
```

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Razoric480**
Fixes #51282 and fixes godotengine/godot-vscode-plugin#291

### CODE REVIEW

File: modules/gdscript/language_server/gdscript_workspace.cpp [hunk 1]
```diff
@@ -520,8 +520,29 @@ void GDScriptWorkspace::completion(const lsp::CompletionParams &p_params, List<S
 
 	if (const ExtendGDScriptParser *parser = get_parse_result(path)) {
 		Node *owner_scene_node = _get_owner_scene_node(path);
+
+		Array stack;
+		Node *current;
```
Comment (akien-mga) [inline modules/gdscript/language_server/gdscript_workspace.cpp:525]:
```
modules/gdscript/language_server/gdscript_workspace.cpp: In member function 'void GDScriptWorkspace::completion(const lsp::CompletionParams&, List<ScriptCodeCompletionOption>*)':
modules/gdscript/language_server/gdscript_workspace.cpp:525:9: error: 'current' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  525 |   Node *current;
      |         ^~~~~~~
```

Probably not true unless `push_back` can fail, but you can initialize to `nullptr` anyway.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.3.
