### PR TITLE
Fix decimal and hex ranges not working with image fonts

### LINKED ISSUE #92025: Monospace image font import completely broken in 4.3.dev6
### Tested versions

- Reproducible in 4.3.dev6

### System information

Godot v4.3.dev6 - Windows 10.0.19045 - GLES3 (Compatibility) - AMD Radeon R7 M440 (Advanced Micro Devices, Inc.; 27.20.20913.2000) - Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 Threads)

### Issue description

Monospace image fonts completely fail to import under v4.3.dev6.  All characters are placeholder rectangles.  No error in output.  Image fonts from a previous version work fine, but break when re-imported in v4.3.dev6.

### Steps to reproduce

1. import a monospace image font in v4.3.dev6
2. observe the font failing to appear

### Minimal reproduction project (MRP)

[monospace-image-font-import-test-for-v4.3.dev6.zip](https://github.com/godotengine/godot/files/15339226/monospace-image-font-import-test-for-v4.3.dev6.zip)

### PR DESCRIPTION
**Pull request by Gaktan**
Importing an image as a font was broken. Following the documentation, the range must be specified:
https://docs.godotengine.org/en/stable/tutorials/ui/gui_using_fonts.html

This was not working with simple ranges such as "0-127", or "0x0-0x7F".

*Bugsquad edit:*
- Fixes #92025

### CODE REVIEW

File: editor/import/resource_importer_imagefont.cpp [hunk 1]
```diff
@@ -156,17 +156,16 @@ Error ResourceImporterImageFont::import(const String &p_source_file, const Strin
...
-							if ((c <= range.length() - 2) && range[c + 1] == 'x') {
-								token = String();
-								if (step == STEP_START_BEGIN) {
-									step = STEP_START_READ_HEX;
-								} else {
-									step = STEP_END_READ_HEX;
-								}
-								c++; // Skip "x".
-								continue;
+						} else if (range[c] == '0' && (c + 1 < range.length()) && range[c + 1] == 'x') {
```
Comment (bruvzg) [inline editor/import/resource_importer_imagefont.cpp:159]:
```suggestion
						} else if (range[c] == '0' && (c <= range.length() - 2) && range[c + 1] == 'x') {
```
For consistency with the rest.

File: editor/import/resource_importer_imagefont.cpp [hunk 2]
```diff
@@ -253,7 +251,12 @@ Error ResourceImporterImageFont::import(const String &p_source_file, const Strin
...
 			}
 			if (end == -1) {
-				end = start;
+				if (step == STEP_END_READ_HEX) {
+					end = token.hex_to_int();
+				}
+				if (step == STEP_END_READ_DEC) {
+					end = token.to_int();
+				}
 			}
```
Comment (bruvzg) [inline editor/import/resource_importer_imagefont.cpp:260]: This should check for all decode condition (both start and end), since it not always a range:
```c++
if (step == STEP_START_READ_HEX) {
	start = token.hex_to_int();
} else if (step == STEP_START_READ_DEC) {
	start = token.to_int();
} else if (step == STEP_END_READ_HEX) {
	end = token.hex_to_int();
} else if (step == STEP_END_READ_DEC) {
	end = token.to_int();
}

if (end == -1) {
	end = start;
}
```

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
