### PR TITLE
Abort running if --path does not exist

### LINKED ISSUE #57194: Command line not prompting error on invalid path
### Godot version

3.4, 4.0a (supposedly)

### System information

Windows 10, AMD Ryzen 2700x, Nvidia 1070ti

### Issue description

Running godot from command line, having godot in PATH, running `godot -e --path <some invalid path>` with invalid path just opens the project manager, not prompting what is wrong in terminal. To make matters worse it starts in low DPI, which looks awful.

### Steps to reproduce

1. Add godot to PATH
2. run `godot -e --path <some invalid path>`
3. Observe incorrect behavior

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #57194

The original behavior seems to have been intended, but it made no sense.

### CODE REVIEW

File: main/main.cpp [hunk 1]
```diff
@@ -1045,9 +1045,10 @@ Error Main::setup(const char *execpath, int argc, char *argv[], bool p_second_ph
 			if (I->next()) {
 				String p = I->next()->get();
 				if (OS::get_singleton()->set_cwd(p) == OK) {
-					//nothing
+					// Directory exists.
```
Comment (akien-mga) [inline main/main.cpp:1048]: Remove the empty branch maybe.

**Review by mhilbrunner — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
