### PR TITLE
Move grid snapping to an independent button

### LINKED ISSUE #16046: use snap button not working when option snap to grid is off
**Godot version:**
Godot 3 RC3

**OS/device including version:**
Windows 7

snap_bug

I expect the "use snap (s)" button to control the option snap to grid and turn it on or off automatically.

### PR DESCRIPTION
**Pull request by groud**
I think this is a good usability improvement. Grid snapping is likely more common than the other ones, so it makes sense to make it its own button. :)
toto

Closes #16046

### CODE REVIEW

**Comment by akien-mga** [comment]
I'm not against it, but the CanvasItemEditor already has a pretty big min width due to this top bar, which is worse when another plugin adds extra items like the TileMap editor, so I'm not sure about adding yet another icon.

That being said, the issue of having too many icons on a single line forcing a min width could likely be solved in different ways (wrap to two lines on small widths for example).

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -284,7 +284,7 @@ Point2 CanvasItemEditor::snap_point(Point2 p_target, unsigned int p_modes, unsig
 	snap_target[0] = SNAP_TARGET_NONE;
 	snap_target[1] = SNAP_TARGET_NONE;
 
-	bool is_snap_active = snap_active ^ Input::get_singleton()->is_key_pressed(KEY_CONTROL);
+	bool is_snap_active = smart_snap_active ^ Input::get_singleton()->is_key_pressed(KEY_CONTROL);
```
Comment (akien-mga) [inline editor/plugins/canvas_item_editor_plugin.cpp]: Unused variable -- bug?
https://travis-ci.org/godotengine/godot/jobs/596230566

Comment (groud) [reply editor/plugins/canvas_item_editor_plugin.cpp]: I will have a look

**Comment by KoBeWi** [comment]
This could close #16046 probably

**Comment by groud** [comment]
Yes I agree

**Comment by akien-mga** [comment]
Thanks!
