### PR TITLE
FBX: Fix material colors

### LINKED ISSUE #90527: ufbx material colors are not converted to sRGB
### Tested versions

- Reproducible in 4.3 (using ufbx)
- Not reproducible in 4.2.x or older

### System information

Godot v4.3.dev (655e93d58) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

Material colors on imported fbx seem to not be converted to srgb.
For example, the RightEar material should be color `#e711a5` but is instead imported as `#cc0160`

Note: I am not talking about vertex colors, which should be tested separately. In this issue, all of the colors on the imported fbx come strictly from materials.

It is important to fix before the release of 4.3, because otherwise we will be forced to break compat in terms of material colors in the future.

### Steps to reproduce

1. Open the project. fbx_vs_ufbx_test.tscn contains two copies of the identical .fbx file: one is imported with ufbx, and the other with legacy FBX2glTF
2. The FBX2glTF version has colors which match other programs (blender, unity)
3. The ufbx version near origin has the incorrect colors, saturated and darker

### Minimal reproduction project (MRP)

[fbx_material_sorting.zip](https://github.com/godotengine/godot/files/14945136/fbx_material_sorting.zip)

### PR DESCRIPTION
**Pull request by bqqbarbhg**
Fixes #90527

Using ufbx test case to validate importing: https://github.com/ufbx/ufbx/blob/picort-refactor/data/maya_material_chart_7700_ascii.fbx 
This test case consists of a 4x3 grid of planes, all with different materials, which should resolve to the same color in a correct renderer.

Reference image: All squares should be the same color (not accounting for some minor quantization inaccuarcies)
reference_ufbx_render

Godot ufbx before: Emissive textures were not imported correctly and linear material colors were not converted to sRGB:
reference_godot_previous

Godot ufbx with this PR: Base color factors are currently ignored in Godot if textures are connected, as some files may contain garbage factors:
reference_godot_no_factor

Godot ufbx with factor support (see note below):
reference_godot_fixes

The following diff would fix the factor support, but it is unclear if it is worth it as it may break other files. One approach would be to add an import option for it but it's probably a too fringe case to support.

```diff
// Combined textures and factors are very unreliable in FBX
- material->set_albedo(Color(1, 1, 1));
+ Color albedo_factor = Color(1, 1, 1);
+ if (fbx_material->pbr.base_factor.has_value) {
+     albedo_factor *= (float)fbx_material->pbr.base_factor.value_real;
+ }
+ material->set_albedo(albedo_factor.linear_to_srgb());
```

Test project: [ufbx_material_chart.zip](https://github.com/godotengine/godot/files/14952821/ufbx_material_chart.zip)

### CODE REVIEW

File: modules/fbx/fbx_document.cpp [hunk 1]
```diff
@@ -1266,7 +1266,7 @@ Error FBXDocument::_parse_cameras(Ref<FBXState> p_state) {
 			camera->set_fov(Math::deg_to_rad(real_t(fbx_camera->field_of_view_deg.y)));
 		} else {
 			camera->set_perspective(false);
-			camera->set_size_mag(real_t(fbx_camera->orthographic_size.y));
+			camera->set_size_mag(real_t(fbx_camera->orthographic_size.y * 0.5f));
```
Comment (bqqbarbhg) [inline modules/fbx/fbx_document.cpp:1269]: This change is fully orthogonal to this PR, I just included it as it fixes the test case here.

Let me know if you would rather have such things in a separate PR.

Comment (lyuma) [reply modules/fbx/fbx_document.cpp:1269]: I think it's okay to include multiple bugfixes here. It's clear they are fixing different issues because they are separate commits.

**Comment by bqqbarbhg** [comment]
One further thing, the example project includes the following script:

```gd
func _ready() -> void:
    for child in self.get_children():
        # Disable speculars for all meshes
        var mesh = child as MeshInstance3D
        if mesh:
            var mat = mesh.get_active_material(0) as StandardMaterial3D
            mat.specular_mode = BaseMaterial3D.SPECULAR_DISABLED
        
        # The light is configured to have intensity of PI, which is then
        # compensated by the 1/PI normalization of the BRDF.
        # However, Godot seems to not do this?
        var light = child as Light3D
        if light:
            light.light_energy = 1.0
```

In the test case I had configured the light intensity to PI to compensate for the 1/PI factor in normalized Lambertian diffuse. The top row contains emissive colors with zero diffuse. If the light intensity is not hacked the diffuse planes are quite a bit brighter:

image

Both Arnold and ufbx's test path tracer result in the correct image with the PI-intensity light, so it seems that Godot is doing something different here. FBX2glTF also seems to import the light intensity as-is, so it's probably for the best not to touch it, even though it will result in brighter scenes than in other renderers.

Also, speaking of FBX2glTF, here is what the test scene looks like using that, after the following fixes:

* Directional light was rotated by 90 degrees
* Orthographic camera units were not scaled, resulting in a 100x too large camera

image

I couldn't get the emissive and diffuse materials to match up using FBX2glTF, either with PI-intensity and 1-intensity directional light. This does mean that ufbx will produce different results than FBX2glTF, so it might be worth it to look a bit deeper whether ufbx is doing the correct thing after all.

**Comment by bqqbarbhg** [comment]
Follow-up observation comparing the FBX2glTF (left) and ufbx (right) result:

image

It looks like FBX2glTF does take the base color factor into account by default, so for compatibility it would probably make sense to do that in the ufbx importer as well. On the other hand, many authoring programs default the base color factor to `0.8`, so users may get darker textures than they would expect, but that would already be an issue with FBX2glTF.

**Review by fire — APPROVED** [review]
Fixing materials colors is great work. Let us know if this is ready to merge.

File: modules/fbx/fbx_document.cpp [hunk 2]
```diff
@@ -1178,7 +1178,11 @@ Error FBXDocument::_parse_materials(Ref<FBXState> p_state) {
 			}
 
 			// Combined textures and factors are very unreliable in FBX
-			material->set_albedo(Color(1, 1, 1));
+			Color albedo_factor = Color(1, 1, 1);
+			if (fbx_material->pbr.base_factor.has_value) {
+				albedo_factor *= (float)fbx_material->pbr.base_factor.value_real;
+			}
+			material->set_albedo(albedo_factor.linear_to_srgb());
```
Comment (bqqbarbhg) [inline modules/fbx/fbx_document.cpp:1185]: I enabled base color factor unconditionally for now. This matches the behavior of FBX2glTF and also Unity (even though there the factor is broken by an sRGB factor).

**Comment by bqqbarbhg** [comment]
As long as everyone is in agreement of using the albedo factor with albedo textures, I'd say I'm fine with getting this merged as-is.

**Comment by fire** [comment]
I don't know why this fails randomly, but it feels unrelated.


```
./tests/scene/test_navigation_region_3d.h:79: ERROR: CHECK_EQ( navigation_mesh->get_polygon_count(), 0 ) is NOT correct!
  values: CHECK_EQ( 2, 0 )

./tests/scene/test_navigation_region_3d.h:80: ERROR: CHECK_EQ( navigation_mesh->get_vertices().size(), 0 ) is NOT correct!
  values: CHECK_EQ( 4, 0 )
```

**Comment by akien-mga** [comment]
Thanks!
