### PR TITLE
Select save dialog file name after popup

### LINKED ISSUE #56329: Save dialogs' file name does not start selected anymore
### Godot version

4.0 28174d531b7128f0281fc2b88da2f4962fd3513e

### System information

Windows 10 64 bits GLES3 GeForce GTX 1060 6GB/PCIe/SSE2

### Issue description

In Godot 3, opening a save dialog to save anything (a scene, resource, script...) starts with the file name selected:
image

In Godot 4, this is no longer the case. So everytime, the user has to manually select to rewrite the intented file name, it is a usability regression:
image

### Steps to reproduce

"Save As" anything: current scene, inspector resource, script

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by gerhean**
Fixes #56329

This behavior is caused by `EditorFileDialog::popup_file_dialog` causing all GUI elements to be unfocused.
As such, I decided to refocus the save dialog file name after it was defocused by `EditorFileDialog::popup_file_dialog`.

### CODE REVIEW

**Comment by Chaosus** [comment]
Please, squash all commits as required by our pipeline (see  https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request).

**Comment by gerhean** [comment]
#Chaosus I have rebased the code as you mentioned.

**Comment by Chaosus** [comment]
This is not correct squashing obviously ^^

**Comment by Chaosus** [comment]
Yeah, seems good now ^^

File: editor/editor_file_dialog.cpp [hunk 1]
```diff
@@ -52,6 +52,15 @@ EditorFileDialog::RegisterFunc EditorFileDialog::unregister_func = nullptr;
 
 void EditorFileDialog::popup_file_dialog() {
 	popup_centered_clamped(Size2(1050, 700) * EDSCALE, 0.8);
+	focus_file_text();
+}
+
+void EditorFileDialog::focus_file_text() {
+	int lp = (file->get_text()).rfind(".");
```
Comment (akien-mga) [inline editor/editor_file_dialog.cpp:59]: The extra parentheses are not necessary:
```suggestion
	int lp = file->get_text().rfind(".");
```

**Comment by akien-mga** [comment]
There is similar code in `FileDialog` (`scene/gui/file_dialog.cpp`, the version used by Godot projects which need it), would it make sense to do the same changes there?

**Comment by gerhean** [comment]
@akien-mga may I know where FileDialog is used? To ensure that FileDialog also has the same problem.

**Comment by akien-mga** [comment]
It's a node part of the public API, so you would use it directly in your own project (added via the scene tree dock or from script).

**Comment by gerhean** [comment]
@akien-mga I have made the requested changes, however I was unable to drag FileDialog into the scene for some reason, so I was unable to test.

**Comment by pycbouh** [comment]
Does the new method need to be public? It seems to only be used internally, so I think it should be kept private.

**Comment by gerhean** [comment]
@pycbouh I have made the methods private.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
