### PR TITLE
Fix Skeleton3D edit mode usability issues

### LINKED ISSUE #114749: Skeleton3D node Edit Mode is almost unusable
### Tested versions

Reproducible in: v4.6.beta3.official [76dda5c6c]

Did not try any other versions

### System information

Godot v4.6.beta3 - Windows 11 (build 26200) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated AMD Radeon RX 5700 XT (Advanced Micro Devices, Inc.; 32.0.21037.1004) - 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz (12 threads) - 15.86 GiB memory

### Issue description

Skeleton3D node edit mode has a lot of issues and flaws

You cannot select a bone in transform mode, only in select mode, that adds frustrating necessity to change modes
Bone button's hitbox is too small, it's even smaller than its icon
There is no undo/redo after you transform bone

Also, I think it should unselect Skeleton3D node if you clicked past AABB boundaries

Also, maybe there should be Insert Key that is only adding tracks for changed transform bones, or just that adds tracks for selected bone

### Steps to reproduce

Select Skeleton3D node
Turn on edit mode
Try selecting any bone in transform mode (It does not work)
Try selecting any bone in select mode, notice how hard it is to select a bone
Go back to transform mode
Transform bone in anyway
Try undoing that transform (It does not work)

### Minimal reproduction project (MRP)

[skeleton-3d-edit-mode.zip](https://github.com/user-attachments/files/24498942/skeleton-3d-edit-mode.zip)

### PR DESCRIPTION
**Pull request by mxtherfxcker**
## Description

Improves the usability of `Skeleton3D` edit mode by fixing bone selection and undo/redo functionality.

## Problem

`Skeleton3D` edit mode had several usability issues:

1. Bones could only be selected in Select mode, requiring constant mode switching
2. Bone selection hitbox was too small (4px), making it difficult to click on bones
3. Undo/redo didn't work after transforming bones because original state wasn't captured correctly
4. Transform tool mode wasn't properly supported

## Related Issues

Fixes #114749

### CODE REVIEW

File: editor/scene/3d/skeleton_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -1705,25 +1736,35 @@ void Skeleton3DGizmoPlugin::commit_subgizmos(const EditorNode3DGizmo *p_gizmo, c
 
 	EditorUndoRedoManager *ur = EditorUndoRedoManager::get_singleton();
 	ur->create_action(TTR("Set Bone Transform"));
-	if (ne->get_tool_mode() == Node3DEditor::TOOL_MODE_SELECT || ne->get_tool_mode() == Node3DEditor::TOOL_MODE_MOVE) {
+
+	if (p_cancel) {
 		for (int i = 0; i < p_ids.size(); i++) {
```
Comment (AThousandShips) [inline editor/scene/3d/skeleton_3d_editor_plugin.cpp]:
```suggestion
		for (int id : p_ids) {
```

File: editor/scene/3d/skeleton_3d_editor_plugin.cpp [hunk 2]
```diff
@@ -1705,25 +1736,35 @@ void Skeleton3DGizmoPlugin::commit_subgizmos(const EditorNode3DGizmo *p_gizmo, c
...
-			ur->add_do_method(skeleton, "set_bone_pose_position", p_ids[i], skeleton->get_bone_pose_position(p_ids[i]));
-			ur->add_undo_method(skeleton, "set_bone_pose_position", p_ids[i], se->get_bone_original_position());
+			ur->add_do_method(skeleton, "set_bone_pose_position", p_ids[i], se->get_bone_original_position());
+			ur->add_do_method(skeleton, "set_bone_pose_rotation", p_ids[i], se->get_bone_original_rotation());
+			ur->add_do_method(skeleton, "set_bone_pose_scale", p_ids[i], se->get_bone_original_scale());
+			ur->add_undo_method(skeleton, "set_bone_pose_position", p_ids[i], skeleton->get_bone_pose_position(p_ids[i]));
+			ur->add_undo_method(skeleton, "set_bone_pose_rotation", p_ids[i], skeleton->get_bone_pose_rotation(p_ids[i]));
+			ur->add_undo_method(skeleton, "set_bone_pose_scale", p_ids[i], skeleton->get_bone_pose_scale(p_ids[i]));
```
Comment (AThousandShips) [inline editor/scene/3d/skeleton_3d_editor_plugin.cpp]:
```suggestion
			ur->add_do_method(skeleton, "set_bone_pose_position", id, se->get_bone_original_position());
			ur->add_do_method(skeleton, "set_bone_pose_rotation", id, se->get_bone_original_rotation());
			ur->add_do_method(skeleton, "set_bone_pose_scale", id, se->get_bone_original_scale());
			ur->add_undo_method(skeleton, "set_bone_pose_position", id, skeleton->get_bone_pose_position(id));
			ur->add_undo_method(skeleton, "set_bone_pose_rotation", id, skeleton->get_bone_pose_rotation(id));
			ur->add_undo_method(skeleton, "set_bone_pose_scale", id, skeleton->get_bone_pose_scale(id));
```

File: editor/scene/3d/skeleton_3d_editor_plugin.cpp [hunk 3]
```diff
@@ -1705,25 +1736,35 @@ void Skeleton3DGizmoPlugin::commit_subgizmos(const EditorNode3DGizmo *p_gizmo, c
...
-	if (ne->get_tool_mode() == Node3DEditor::TOOL_MODE_SELECT || ne->get_tool_mode() == Node3DEditor::TOOL_MODE_ROTATE) {
-		for (int i = 0; i < p_ids.size(); i++) {
-			ur->add_do_method(skeleton, "set_bone_pose_rotation", p_ids[i], skeleton->get_bone_pose_rotation(p_ids[i]));
-			ur->add_undo_method(skeleton, "set_bone_pose_rotation", p_ids[i], se->get_bone_original_rotation());
+	} else {
+		Node3DEditor::ToolMode tool_mode = ne->get_tool_mode();
+		if (tool_mode == Node3DEditor::TOOL_MODE_SELECT || tool_mode == Node3DEditor::TOOL_MODE_MOVE || tool_mode == Node3DEditor::TOOL_MODE_TRANSFORM) {
+			for (int i = 0; i < p_ids.size(); i++) {
+				ur->add_do_method(skeleton, "set_bone_pose_position", p_ids[i], skeleton->get_bone_pose_position(p_ids[i]));
+				ur->add_undo_method(skeleton, "set_bone_pose_position", p_ids[i], se->get_bone_original_position());
```
Comment (AThousandShips) [inline editor/scene/3d/skeleton_3d_editor_plugin.cpp]:
```suggestion
			for (int id : p_ids) {
				ur->add_do_method(skeleton, "set_bone_pose_position", id, skeleton->get_bone_pose_position(id));
				ur->add_undo_method(skeleton, "set_bone_pose_position", id, se->get_bone_original_position());
```

File: editor/scene/3d/skeleton_3d_editor_plugin.cpp [hunk 4]
```diff
@@ -1705,25 +1736,35 @@ void Skeleton3DGizmoPlugin::commit_subgizmos(const EditorNode3DGizmo *p_gizmo, c
...
-		for (int i = 0; i < p_ids.size(); i++) {
-			// If the axis is swapped by scaling, the rotation can be changed.
-			ur->add_do_method(skeleton, "set_bone_pose_rotation", p_ids[i], skeleton->get_bone_pose_rotation(p_ids[i]));
-			ur->add_undo_method(skeleton, "set_bone_pose_rotation", p_ids[i], se->get_bone_original_rotation());
-			ur->add_do_method(skeleton, "set_bone_pose_scale", p_ids[i], skeleton->get_bone_pose_scale(p_ids[i]));
-			ur->add_undo_method(skeleton, "set_bone_pose_scale", p_ids[i], se->get_bone_original_scale());
+		if (tool_mode == Node3DEditor::TOOL_MODE_SELECT || tool_mode == Node3DEditor::TOOL_MODE_ROTATE || tool_mode == Node3DEditor::TOOL_MODE_TRANSFORM) {
+			for (int i = 0; i < p_ids.size(); i++) {
+				ur->add_do_method(skeleton, "set_bone_pose_rotation", p_ids[i], skeleton->get_bone_pose_rotation(p_ids[i]));
+				ur->add_undo_method(skeleton, "set_bone_pose_rotation", p_ids[i], se->get_bone_original_rotation());
```
Comment (AThousandShips) [inline editor/scene/3d/skeleton_3d_editor_plugin.cpp]:
```suggestion
			for (int id : p_ids) {
				ur->add_do_method(skeleton, "set_bone_pose_rotation", id, skeleton->get_bone_pose_rotation(id));
				ur->add_undo_method(skeleton, "set_bone_pose_rotation", id, se->get_bone_original_rotation());
```

File: editor/scene/3d/skeleton_3d_editor_plugin.cpp [hunk 5]
```diff
@@ -1705,25 +1736,35 @@ void Skeleton3DGizmoPlugin::commit_subgizmos(const EditorNode3DGizmo *p_gizmo, c
...
+			}
+		}
+		if (tool_mode == Node3DEditor::TOOL_MODE_SCALE || tool_mode == Node3DEditor::TOOL_MODE_TRANSFORM) {
+			for (int i = 0; i < p_ids.size(); i++) {
+				ur->add_do_method(skeleton, "set_bone_pose_scale", p_ids[i], skeleton->get_bone_pose_scale(p_ids[i]));
+				ur->add_undo_method(skeleton, "set_bone_pose_scale", p_ids[i], se->get_bone_original_scale());
```
Comment (AThousandShips) [inline editor/scene/3d/skeleton_3d_editor_plugin.cpp]:
```suggestion
			for (int id : p_ids) {
				ur->add_do_method(skeleton, "set_bone_pose_scale", id, skeleton->get_bone_pose_scale(id));
				ur->add_undo_method(skeleton, "set_bone_pose_scale", id, se->get_bone_original_scale());
```

File: editor/scene/3d/skeleton_3d_editor_plugin.cpp [hunk 6]
```diff
@@ -1518,15 +1518,49 @@ EditorPlugin::AfterGUIInput Skeleton3DEditorPlugin::forward_3d_gui_input(Camera3
...
+					}
+				}
+
+				if (closest_idx >= 0) {
+					se->select_bone(closest_idx);
+					se->update_bone_original();
+
+					Vector<Ref<Node3DGizmo>> gizmos = skeleton->get_gizmos();
+					for (int i = 0; i < gizmos.size(); i++) {
+						Ref<EditorNode3DGizmo> seg = gizmos[i];
```
Comment (AThousandShips) [inline editor/scene/3d/skeleton_3d_editor_plugin.cpp]:
```suggestion
					for (Ref<EditorNode3DGizmo> seg : gizmos) {
```

**Comment by mxtherfxcker** [comment]
@AThousandShips done.

**Comment by mxtherfxcker** [comment]
@TokageItLab Can you do a review in your free time?

**Review by TokageItLab — APPROVED** [review]
https://github.com/godotengine/godot/issues/114749 issue seems to be a regression that depends on the implementation of Selection mode. I strongly recommend merging it into 4.6.

File: editor/scene/3d/skeleton_3d_editor_plugin.cpp [hunk 7]
```diff
@@ -1518,15 +1518,48 @@ EditorPlugin::AfterGUIInput Skeleton3DEditorPlugin::forward_3d_gui_input(Camera3
...
+					Vector2 joint_pos_2d = p_camera->unproject_position(joint_pos_3d);
+					real_t dist_3d = ray_from.distance_to(joint_pos_3d);
+					real_t dist_2d = mb->get_position().distance_to(joint_pos_2d);
+					if (dist_2d < grab_threshold && dist_3d < closest_dist) {
+						closest_dist = dist_3d;
+						closest_idx = i;
+					}
+				}
+
+				if (closest_idx >= 0) {
```
Comment (TokageItLab) [inline editor/scene/3d/skeleton_3d_editor_plugin.cpp:1525]:
```suggestion
		if (mb.is_valid() && mb->get_button_index() == MouseButton::LEFT && mb->is_pressed()) {
			Skeleton3D *skeleton = se->get_skeleton();
			if (skeleton) {
				int closest_idx = Skeleton3DGizmoPlugin::skeleton_intersect_ray(skeleton, p_camera, mb->get_position());
				if (closest_idx >= 0) {
```

To avoid duplication.

**skeleton_3d_editor_plugin.h**
```cpp
	static int skeleton_intersect_ray(const Skeleton3D *p_skeleton, Camera3D *p_camera, const Vector2 &p_point);
	virtual int subgizmos_intersect_ray(const EditorNode3DGizmo *p_gizmo, Camera3D *p_camera, const Vector2 &p_point) const override;
	virtual Transform3D get_subgizmo_transform(const EditorNode3DGizmo *p_gizmo, int p_id) const override;
	virtual void set_subgizmo_transform(const EditorNode3DGizmo *p_gizmo, int p_id, Transform3D p_transform) override;
	virtual void commit_subgizmos(const EditorNode3DGizmo *p_gizmo, const Vector<int> &p_ids, const Vector<Transform3D> &p_restore, bool p_cancel) override;
```

**skeleton_3d_editor_plugin.cpp**
```cpp
int Skeleton3DGizmoPlugin::subgizmos_intersect_ray(const EditorNode3DGizmo *p_gizmo, Camera3D *p_camera, const Vector2 &p_point) const {
	Skeleton3D *skeleton = Object::cast_to<Skeleton3D>(p_gizmo->get_node_3d());
	ERR_FAIL_NULL_V(skeleton, -1);
	Skeleton3DEditor *se = Skeleton3DEditor::get_singleton();
	if (!se || !se->is_edit_mode()) {
		return -1;
	}
	int closest_idx = skeleton_intersect_ray(skeleton, p_camera, p_point);
	if (closest_idx >= 0) {
		se->select_bone(closest_idx);
		se->update_bone_original();
		return closest_idx;
	}
	se->select_bone(-1);
	return -1;
}

int Skeleton3DGizmoPlugin::skeleton_intersect_ray(const Skeleton3D *p_skeleton, Camera3D *p_camera, const Vector2 &p_point) {
	real_t grab_threshold = 8 * EDSCALE;
	Vector3 ray_from = p_camera->get_global_transform().origin;
	Transform3D gt = p_skeleton->get_global_transform();
	int closest_idx = -1;
	real_t closest_dist = 1e10;
	const int bone_count = p_skeleton->get_bone_count();
	for (int i = 0; i < bone_count; i++) {
		Vector3 joint_pos_3d = gt.xform(p_skeleton->get_bone_global_pose(i).origin);
		Vector2 joint_pos_2d = p_camera->unproject_position(joint_pos_3d);
		real_t dist_3d = ray_from.distance_to(joint_pos_3d);
		real_t dist_2d = p_point.distance_to(joint_pos_2d);
		if (dist_2d < grab_threshold && dist_3d < closest_dist) {
			closest_dist = dist_3d;
			closest_idx = i;
		}
	}
	return closest_idx;
};
```

**Review by TokageItLab — APPROVED** [review]

**Comment by kawandev2025** [comment]
If I try to start another animation within the animation in the Animation Player, it crashes, and every time I go back into the engine it keeps crashing.
