### PR TITLE
Editor: Ensure font image rows/columns are positive

### LINKED ISSUE #91812: Crash when importing image as FontData if setting rows to 0
### Tested versions

- Reproducible in: 4.3-dev6, 4.2.1

### System information

Windows 10.0.22631 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700S (Advanced Micro Devices, Inc.; 31.0.24031.5001) - AMD Ryzen 9 6900HS with Radeon Graphics (16 Threads)

### Issue description

When importing an image as FontData, setting "rows" to 0 in the Import tab and reimporting crashes the editor

### Steps to reproduce

- Open the attacked MRP
- In the Filesystem dock select "TimerNumbers_10.png"
- Go to the Import tab
- Set rows to 0
- Reimport
Expected: An error is shown into the console since 0 is an invalid value
Actual: The editor crashes and the invalid value gets saved in the .import file

This is just an example, you can cause the same crash by setting columns to 0

Other errors, like having a total character range exceeding rows*columns show properly without causing any crashes

### Minimal reproduction project (MRP)

[fontdata-mrp.zip](https://github.com/godotengine/godot/files/15279355/fontdata-mrp.zip)

### PR DESCRIPTION
**Pull request by alesliehughes**
Add a check on the import for valid Rows/Columns.
Add some restrictions to the GUI to disallow values <= 0.

Fixes #91812

### CODE REVIEW

File: editor/import/resource_importer_imagefont.cpp [hunk 1]
```diff
@@ -94,6 +94,7 @@ Error ResourceImporterImageFont::import(const String &p_source_file, const Strin
 	Error err = ImageLoader::load_image(p_source_file, img);
 	ERR_FAIL_COND_V_MSG(err != OK, ERR_FILE_CANT_READ, vformat("Can't load font texture: \"%s\".", p_source_file));
 
+	ERR_FAIL_COND_V_MSG(columns <= 0 || rows <= 0, ERR_FILE_CANT_READ, vformat("Columns (%d) and rows (%d) cannot be zero.", columns, rows) );
```
Comment (AThousandShips) [inline editor/import/resource_importer_imagefont.cpp:97]:
```suggestion
	ERR_FAIL_COND_V_MSG(columns <= 0, ERR_FILE_CANT_READ, vformat("Columns (%d) must be positive.", columns));
	ERR_FAIL_COND_V_MSG(rows <= 0, ERR_FILE_CANT_READ, vformat("Rows (%d) must be positive.", rows));
```
Clearer and more correct error message

**Comment by AThousandShips** [comment]
Did you forget to add your changes? You pushed an empty update

**Comment by alesliehughes** [comment]
Pushed the correct change this time.

**Review by bruvzg — APPROVED** [review]

**Review by AThousandShips — APPROVED** [review]
LGTM, except for the code style that needs fixing

File: editor/import/resource_importer_imagefont.cpp [hunk 2]
```diff
@@ -94,6 +94,8 @@ Error ResourceImporterImageFont::import(const String &p_source_file, const Strin
 	Error err = ImageLoader::load_image(p_source_file, img);
 	ERR_FAIL_COND_V_MSG(err != OK, ERR_FILE_CANT_READ, vformat("Can't load font texture: \"%s\".", p_source_file));
 
+	ERR_FAIL_COND_V_MSG(columns <= 0, ERR_FILE_CANT_READ, vformat("Columns (%d) must be positive.", columns) );
+	ERR_FAIL_COND_V_MSG(rows <= 0, ERR_FILE_CANT_READ, vformat("Rows (%d) must be positive.", rows) );
```
Comment (AThousandShips) [inline editor/import/resource_importer_imagefont.cpp:98]:
```suggestion
	ERR_FAIL_COND_V_MSG(columns <= 0, ERR_FILE_CANT_READ, vformat("Columns (%d) must be positive.", columns));
	ERR_FAIL_COND_V_MSG(rows <= 0, ERR_FILE_CANT_READ, vformat("Rows (%d) must be positive.", rows));
```

**Comment by akien-mga** [comment]
Thanks!
