### PR TITLE
[3.x] Fix `glGet` overflows by using 64 bit versions

### LINKED ISSUE #75913: GLES3 Renderer fails on linux devices when testing browser exports.
### Godot version

3.5.2 and 3.5.1 Both Don't Work

### System information

Fedora / X11 Desktop Renderer / Chromium Latest / AMD GPU

### Issue description

GLES3 Exports fail to render meshes on web exports running on linux machines, tested on mobile android devices and this issue is not present. Tested Godot versions 3.5.1 and 3.5.2 both seem to fail. Tested multiple projects with and without textures the issue persists and no meshes are rendered. I think the GLES3 Shader fails to compile when running in a web environment since the rendering is fine when done locally through the play/play scene buttons. Tested multiple browsers including chromium and opera.
Screenshot from 2023-04-11 01-41-03

Screenshot from 2023-04-11 01-40-43

### Steps to reproduce

Create an empty project, add in any basic mesh instance and a camera to view it, export for HTML5 and test the game export in any browser on a linux machine (I'm running fedora but I assume they all have similar rendering pipelines) Other WEBGL 2.0 features work fine on the machine for the browser.

### Minimal reproduction project

Any basic project will suffice.

This issue might be related -> https://github.com/godotengine/godot/issues/73799 
This too if it uses a similar pipeline -> https://github.com/godotengine/godot/issues/75054

### PR DESCRIPTION
**Pull request by lawnjelly**
Certain glGet operations require 64 bit versions according to the GLES spec. The previous code was susceptible to overflow bugs,  especially running under ANGLE.

May fix #75913

## Notes
* Supersedes #82921
* Also fixes a theoretical bug in `gl_wrapper` by placing an upper limit on texture image units.
* Is basically a slightly more in depth version of #80909 .

### CODE REVIEW

File: drivers/gles2/shader_gles2.cpp [hunk 1]
```diff
@@ -559,6 +559,7 @@ void ShaderGLES2::setup(
 	}
 
 	glGetIntegerv(GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS, &max_image_units);
+	max_image_units = MIN(max_image_units, 64);
```
Comment (akien-mga) [inline drivers/gles2/shader_gles2.cpp:562]: Shouldn't use you `safe_gl_get_integer` for consistency? Can be made `static` I guess.

Comment (lawnjelly) [reply drivers/gles2/shader_gles2.cpp:562]: Yes this is partly why still draft so I can figure if there is a better way. Ideally it would be good to access the same `max_image_units` as used in storage, as the upper limit should be the same in both cases, and manual syncing is a bug waiting to happen.

**Comment by lawnjelly** [comment]
Let me know if there are any more than get spotted that should be 64 bit from the spec, I've tried to catch the ones from #80909 .

For the shaders, instead of reading `max_image_units` directly I've exposed the maximum desired so the calculations will be the same. We could alternatively e.g. make `max_image_units` static, or make storage readable from the shader file, or copy this value in the shader `setup()`, but it looks like more code for something that only needs a simple solution.

File: drivers/gles3/rasterizer_storage_gles3.cpp [hunk 2]
```diff
@@ -152,6 +152,13 @@ void RasterizerStorageGLES3::GLWrapper::reset() {
 	texture_unit_table.blank();
 }
 
+int32_t RasterizerStorageGLES3::safe_gl_get_integer(unsigned int p_gl_param_name, int32_t p_max_accepted) {
```
Comment (jasonwinterpixel) [inline drivers/gles3/rasterizer_storage_gles3.cpp:155]: Seems odd to use glGetInteger64v but then take an int32 as the max accepted.

File: drivers/gles3/rasterizer_scene_gles3.cpp [hunk 3]
```diff
@@ -5152,8 +5152,29 @@ void RasterizerSceneGLES3::initialize() {
...
+		// but the true hardware GPU max may be lower, but we have no way
+		// of querying this hardware supported value.
+		// We also ideally want to take advantage of GPUs that *do* support large uniform
+		// blocks in hardware (although this is probably not taken advantage of in Godot 3.x currently).
+
+		// This logic is thus a compromise.
+		int max_ubo_size = RasterizerStorageGLES3::safe_gl_get_integer(GL_MAX_UNIFORM_BLOCK_SIZE);
+
+		// If UBO size if very large, we are likely under ANGLE and it is reporting system memory.
+		if (max_ubo_size >= INT32_MAX) {
```
Comment (jasonwinterpixel) [inline drivers/gles3/rasterizer_scene_gles3.cpp:5167]: This is probably unnecessary. Just using the int64 is good enough and matches the spec. This is pretty complex, untested by defintion and an overreaction to the error that I precisely identified and rectified.

Comment (jasonwinterpixel) [reply drivers/gles3/rasterizer_scene_gles3.cpp:5167]: Actually, this is incorrect. INT32_MAX is what my GPU reports on desktop, we should consider that valid.

Comment (jasonwinterpixel) [reply drivers/gles3/rasterizer_scene_gles3.cpp:5167]: Removing this check will make the PR valid, but it's complexity obfuscates mistakes like this. IMO this PR is too aggressive. Godot 3 is a legacy project, it needs to be treated more conservatively.

I'd like to add that I vastly respect the work you've put in Lawn Jelly, and respect how willing you are to make ambitious changes.

File: drivers/gles3/rasterizer_storage_gles3.cpp (hunk 2 above)
Comment (lawnjelly) [reply drivers/gles3/rasterizer_storage_gles3.cpp:155]: There is no need for `int64_t` as the maximum as we do not use more than the 32 bit range in 3.x. This means that the calling code can store the results as 32 bit, which ensures existing code still works as is.

File: drivers/gles3/rasterizer_scene_gles3.cpp (hunk 3 above)
Comment (lawnjelly) [reply drivers/gles3/rasterizer_scene_gles3.cpp:5167]: See https://github.com/godotengine/godot/pull/83031#issuecomment-1752690501 for reasoning.

It is admittedly controversial either way, there is no ideal, so I'm really waiting to see what @clayjohn thinks, as the discussion is relevant for 4.x.

I did waver between the two versions myself :thinking: , initially just using the large value as is, but as there is significant danger of blowing the GPU limit (in theory), I'm currently of the opinion that the reduction to the minimum in this case is the lesser of the evils. But either should be fine.

Comment (lawnjelly) [reply drivers/gles3/rasterizer_scene_gles3.cpp:5167]: Sounds good, will fix that up in the morning! :slightly_smiling_face:

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
