### PR TITLE
Fix error where update wouldn't reconnect the signal it should have reconnected and led to errors and crash.

### LINKED ISSUE #78372: changing the type of the root node can wipe the whole scene tree in certain cases
### Godot version

v4.1.beta.custom_build [b5f0ca1e5]

### System information

macOS 13.3.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

So if you have a scene that contains a instanced child scene that has a script on its root node, and you change the type of its root node then the whole scene tree gets deleted. 

https://github.com/godotengine/godot/assets/66184050/87e71953-7343-479a-8214-5445016684c9

For now I could not find any workaround that would not lose data.

### Steps to reproduce

1. Create two scene
2. add a script to the root node of one and instanciate the same one into the other
3. change the type of the root of the second one

### Minimal reproduction project

Start at step 3 with MRP
[Test.zip](https://github.com/godotengine/godot/files/11779601/Test.zip)

### LINKED ISSUE #89425: Godot crashes, when you change root node to something unpredictable
### Tested versions

4.2.1 Steam version

### System information

Windows 10

### Issue description

I changed Sprite3D to subviewport, while it was root node and godot just closed instantly

### Steps to reproduce

1. Create scene with Sprite3D as a root node
2. Give it a texture and enable billboard
3. Change Sprite3D to sub-viewport

### Minimal reproduction project (MRP)

It happened once, I tried to make it again, but everything is fine

### PR DESCRIPTION
**Pull request by ajreckof**
Fixes #78372 fixes #89425 
The second issue is half a duplicate as it is the same issue but the symptoms degenerated over time from simple errors to a full crash.

### CODE REVIEW

File: editor/editor_data.cpp [hunk 1]
```diff
@@ -721,8 +721,11 @@ bool EditorData::check_and_update_scene(int p_idx) {
 		}
 
 		new_scene->set_scene_file_path(edited_scene[p_idx].root->get_scene_file_path());
-
-		memdelete(edited_scene[p_idx].root);
+		Node *old_root = edited_scene[p_idx].root;
+		for (int i = 0; i < old_root->get_child_count(); i++) {
+			memdelete(old_root->get_child(i));
+		}
+		old_root->replace_by(new_scene);
```
Comment (KoBeWi) [inline editor/editor_data.cpp:728]: `replace_by()` does not delete the node, so unless it's still referenced somewhere, this will cause a leak.

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -3836,6 +3828,14 @@ void EditorNode::_set_current_scene_nocheck(int p_idx) {
 	if (tabs_to_close.is_empty()) {
 		callable_mp(this, &EditorNode::_set_main_scene_state).call_deferred(state, get_edited_scene()); // Do after everything else is done setting up.
 	}
+
+	if (editor_data.check_and_update_scene(p_idx)) {
+		if (editor_data.get_scene_path(p_idx) != "") {
```
Comment (KoBeWi) [inline editor/editor_node.cpp:3833]:
```suggestion
		if (!editor_data.get_scene_path(p_idx).is_empty()) {
```
(I know it was like this originally)

File: editor/editor_data.cpp (hunk 1 above)
Comment (ajreckof) [reply editor/editor_data.cpp:728]: yeah you are right I forgot to delete it as I always forget that it does not delete the node :(

File: editor/editor_node.cpp [hunk 3]
```diff
@@ -3836,6 +3828,14 @@ void EditorNode::_set_current_scene_nocheck(int p_idx) {
 	if (tabs_to_close.is_empty()) {
 		callable_mp(this, &EditorNode::_set_main_scene_state).call_deferred(state, get_edited_scene()); // Do after everything else is done setting up.
```
Comment (KoBeWi) [inline editor/editor_node.cpp:3829]: This comment might need rewording, as it's no longer the last action.

**Review by KoBeWi — APPROVED** [review]

File: editor/editor_node.cpp (hunk 3 above)
Comment (ajreckof) [reply editor/editor_node.cpp:3829]: no it is still done after everything because the call is deferred I think the commentary was about why it is deferred and not just a direct call and not about being at the end of the function

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Removing cherry-pick for now as this introduces a regression, see:
* #89877
