### PR TITLE
Fix Sprite3D texture bleed when not wrapping

### LINKED ISSUE #82044: Sprite3D texture wrapping causing pixel lines on border
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2080 Ti (NVIDIA; 31.0.15.3734) - Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 Threads)

### Issue description

Sprite3D has pixel lines which appear to be the texture wrapping. There are no options on Sprite3D to disable wrapping.

image

Some troubleshooting for this issue has been carried out in my [Reddit thread.](https://old.reddit.com/r/godot/comments/16nobpu/new_to_godot_and_loving_it_any_idea_how_i_can/)

Tested on 4.1.1 and 4.2dev5

### Steps to reproduce

1. Create Sprite3D node
2. Import texture with lossless compression (or any compression, nothing I tried made a difference)
3. Apply texture to Sprite3D

### Minimal reproduction project

[Sprite3D_bug_21-09-23.zip](https://github.com/godotengine/godot/files/12684098/Sprite3D_bug_21-09-23.zip)

### PR DESCRIPTION
**Pull request by cadence-s**
Fixes #82044.

Texture wrapping is now turned off by default in 2D-in-3D, except for the case where a Sprite3D has a defined region larger than the texture size. According to @clayjohn this was discussed as a good solution in a rendering meeting (https://github.com/godotengine/godot/pull/82193#issuecomment-1996597424).

### CODE REVIEW

**Comment by etherealxx** [comment]
Will this be in 4.4.1?

**Comment by AThousandShips** [comment]
This hasn't been merged yet and won't be cherry-picked until after it has been merged, so probaly won't be in 4.4.1 as we are planning to release that pretty soon

File: scene/3d/sprite_3d.cpp [hunk 1]
```diff
@@ -770,10 +770,13 @@ void Sprite3D::_draw() {
 	}
 
 	Rect2 base_rect;
+	bool texture_repeat;
 	if (region) {
 		base_rect = region_rect;
+		texture_repeat = (region_rect.size.x > texture->get_width()) || (region_rect.size.y > texture->get_height());
```
Comment (kleonc) [inline scene/3d/sprite_3d.cpp:776]: This check is incorrect, repeat should be true if the region anyhow exceeds the texture.

This should do:
```suggestion
		texture_repeat = !Rect2(Vector2(), tsize).encloses(region_rect.abs());
```
I've used `region_rect.abs()` there so regions with negative sizes would be handled according to the current behavior for them (`encloses` expects non-negative-size rects).

In v4.4.1.stable.official [49a5bc7b6]:
qiSIIgzkdk|TeW8IyUXNi
-|-

**Comment by tehKaiN** [comment]
Hi,

What's the status of this PR? The feature is important for my team. I see that it was pushed back to 4.5 and now to 4.6. Is it a manner of positive review, or is something else still needing work?

File: scene/3d/sprite_3d.cpp [hunk 2]
```diff
@@ -1027,7 +1030,7 @@ void AnimatedSprite3D::_draw() {
 
 	Rect2 dst_rect(ofs, tsize);
 
-	draw_texture_rect(texture, dst_rect, src_rect);
+	draw_texture_rect(texture, dst_rect, src_rect, false);
```
Comment (kleonc) [inline scene/3d/sprite_3d.cpp]: Relooking at this, AnimatedSprite3D's texture could also exceed the texture bounds (in which case it should have repeat enabled), as it could be using an AtlasTexture with its region exceeding the texture. So I think a better solution would be to remove `bool p_texture_repeat` parameter from `SpriteBase3D::draw_texture_rect`, and instead deduce the repeat flag within `SpriteBase3D::draw_texture_rect` based on whether the final UV rect exceeds the 0..1 bounds.

So right after:
https://github.com/godotengine/godot/blob/7716a4cba0e4d96e170488bd4f332d22395f7bdb/scene/3d/sprite_3d.cpp#L142-L147
something like:
```cpp
bool texture_repeat = (uvs[0].x < 0.0) || (uvs[0].y < 0.0) || (uvs[2].x > 1.0) || (uvs[2].y > 1.0);
```
or, if `final_src_rect.size` might be negative (I haven't checked that):
```cpp
bool texture_repeat = (MIN(uvs[0].x, uvs[2].x) < 0.0) || (MIN(uvs[0].y, uvs[2].y) < 0.0) || (MAX(uvs[0].x, uvs[2].x) > 1.0) || (MAX(uvs[0].y, uvs[2].y) > 1.0);
```

And this way the calling code in Sprite3D/AnimatedSprite3D would remain unchanged.

**Review by kleonc — COMMENTED** [review]
> What's the status of this PR? The feature is important for my team. I see that it was pushed back to 4.5 and now to 4.6. Is it a manner of positive review, or is something else still needing work?

AFAICT it's awaiting a review from @godotengine/rendering.
But currently it's also outdated / it has conflicts with the current `master` branch. So would need to be rebased as well.

Seems there's also #90202 which aims to resolve the same issue, but AFAICT this PR is more aligned with [what the rendering team wanted the solution to be](https://github.com/godotengine/godot/pull/82193#issuecomment-1996597424). Hence I'm leaving my review here.

File: scene/3d/sprite_3d.cpp (hunk 2 above)
Comment (cadence-s) [reply scene/3d/sprite_3d.cpp]: Is this a case that ever actually happens? I get that it should be robust, but I'm having trouble imagining what it means to have repeat enabled on an AtlasTexture. It does make sense to use the final UVs, but I'm a bit nervous about changing it when I haven't touched this in a long time.

**Comment by AThousandShips** [comment]
You used a merge commit to update your branch, please use rebase in the future instead, see [here](https://contributing.godotengine.org/en/latest/organization/pull_requests/creating_pull_requests.html#the-interactive-rebase)

File: scene/3d/sprite_3d.cpp (hunk 2 above)
Comment (kleonc) [reply scene/3d/sprite_3d.cpp]: > Is this a case that ever actually happens?

I'd say for an AnimatedSprite3D probably very unlikely, but it's possible. Here's a working example in v4.5.1.stable.official [f62fdbde1]:

https://github.com/user-attachments/assets/81829093-8183-47e6-9b9c-8341eabc59de

(the non-repeating preview in the SpriteFrames editor is a separate thing; similarily the preview uses nearest texture filter while the AnimtedSprite3D uses linear texture filter)

And here's the current version of this PR:
godot windows editor dev x86_64_3BNHrAgnwY

Now I've also realized that the current version of this PR would break using such AtlasTexture also for Sprite3D, not just AnimatedSprite3D. And I'd guess using an AtlasTexture in a Sprite3D is a more probable use case.
Anyway, I see no reason to break these potential use cases. It's not like the solution I've suggested in my previous comment is performance heavy or something like that.

v4.5.1.stable.official [f62fdbde1]| This PR
-|-
KZWOVc4bwB|UGFY8APSqC

Comment (cadence-s) [reply scene/3d/sprite_3d.cpp]: Thanks for your help with this, it seems to be working well with the change

**Comment by cadence-s** [comment]
This should be all cleaned up now

**Review by kleonc — APPROVED** [review]
LGTM, fixes the issue.

[As the rendering team wanted](https://github.com/godotengine/godot/pull/82193#issuecomment-1996597424) the repeat flag is being enabled/disabled automatically. However, according to my suggestion, it's done in a slightly different manner than originally suggested, as it's based on the final UV region used instead of solely based on the `Sprite3D.region` (this makes it work e.g. for AtlasTextures). Nevertheless, this should get an approval from the rendering team before merging.

**Comment by OeilDeLance** [comment]
I am looking to test this in our custom 4.5 build.
What do you think will that merge fine into 4.5.1 ?

**Comment by cadence-s** [comment]
> I am looking to test this in our custom 4.5 build. What do you think will that merge fine into 4.5.1 ?

There shouldn't be any problems with merging it into 4.5; the relevant code hasn't changed in a long time.

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
