### PR TITLE
Fix allocation size overflow check in `CowData`

### LINKED ISSUE #81911: No nullptr check in cowdata - crash to desktop
### Godot version

v4.2.dev.custom_build.ba54c3455

### System information

macOS M1

### Issue description

In `cowdata.h` line 314:

https://github.com/godotengine/godot/blob/571cd0eb791b37e9a8adda9f909251138170f6b7/core/templates/cowdata.h#L314

We can see:

`*_get_size() = p_size;`

The function `_get_size()` may return nullptr:

```
	_FORCE_INLINE_ uint32_t *_get_size() const {
		if (!_ptr) {
			return nullptr;
		}

		return reinterpret_cast<uint32_t *>(_ptr) - 1;
	}
```

I discovered this when investigating the issue: #63534

This is the cause of the issue and the cause of the crash.

Since I don't understand Copy-On-Write logic, I don't know how to fix it. So I leave it to you guys.

### Steps to reproduce

1. Get #63534 project (download the example)
2. Open (double click in godot editor)`res://godot_4_alpha_12_tileset_issue_2.log`
3. Crash into desktop

### Minimal reproduction project

Get #63534 project (download the example)

### PR DESCRIPTION
**Pull request by AThousandShips**
For large input data, the next power of two check can return 0, causing the allocation size to not be valid, this ensures that it fails if that is the case.

Will look into adding error checks to code that uses `resize` on things and then depends on it being successful, but taking that in a separate PR

* Fixes: https://github.com/godotengine/godot/issues/81911 (This partially fixes it, the specific case will still crash as the internal string operations do not check for errors after resize, can add that too but felt this was a specific fix to core)

### CODE REVIEW

File: core/templates/cowdata.h [hunk 1]
```diff
@@ -90,6 +90,10 @@ class CowData {
 	}
 
 	_FORCE_INLINE_ bool _get_alloc_size_checked(size_t p_elements, size_t *out) const {
+		if (p_elements == 0) {
```
Comment (RandomShaper) [inline core/templates/cowdata.h:93]:
```suggestion
		if (unlikely(p_elements == 0)) {
```

**Review by RandomShaper — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.4.
