### PR TITLE
Fix that `ViewportTexture` cannot be setup again after failed setup

### LINKED ISSUE #77678: ViewportTexture remains bright pink in some projects after upgrade to 4.0.3-stable
### Godot version

4.0.3-stable

### System information

Windows 10

### Issue description

In some projects ViewportTexture remains pink and doesn't render viewport content after upgrading from 4.0.2-stable to 4.0.3-stable. If a pair of files viewport.h/viewport.cpp are downgraded back to what they were in 4.0.2-stable, problem goes away.

This is how it looks in 4.0.3-stable:
4 0 3_stable_viewport_4 0 3

And this is how it looks if viewport.h/viewport.cpp are downgraded back to what they were in 4.0.2-stable.
4 0 3_stable_viewport_4 0 2

### Steps to reproduce

Unfortunately, I cannot come up wit a simple demo project reproducing the problem. It exists in some projects and doesn't exist in others.

### Minimal reproduction project

Cannot produce a simple project reproducing the problem. In simple projects it works fine.

### PR DESCRIPTION
**Pull request by Rindbee**
`vp_pending` is a flag indicating to wait for `ViewportTexture::_setup_local_to_scene` to be called. Once this method is called, no matter whether the setup will fail or not, it needs to be reset to `false`.

Fix #77678.

### CODE REVIEW

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -170,6 +170,11 @@ Ref<Image> ViewportTexture::get_image() const {
 }
 
 void ViewportTexture::_setup_local_to_scene(const Node *p_loc_scene) {
+	_setup_local_to_scene_imp(p_loc_scene);
+	vp_pending = false;
```
Comment (akien-mga) [inline scene/main/viewport.cpp:174]: I would add a comment as otherwise it's not clear why this needs to be here instead of at the end of the `setup_local_to_scene_imp` mthod.
```suggestion
	// Always reset this, even if previous call fails with an error.
	vp_pending = false;
```

File: scene/main/viewport.cpp [hunk 2]
```diff
@@ -170,6 +170,11 @@ Ref<Image> ViewportTexture::get_image() const {
...
+}
+
+void ViewportTexture::_setup_local_to_scene_imp(const Node *p_loc_scene) {
```
Comment (akien-mga) [inline scene/main/viewport.cpp:177]: I think we tend to name those with `_impl` suffix.

**Review by clayjohn — APPROVED** [review]
The change looks reasonably safe to me ``vp_pending`` is a flag used to indicate whether we are waiting on ``_setup_local_to_scene()`` being called later this frame. Once ``_setup_local_to_scene()``, there is no purpose to keep ``vp_pending`` ``true``

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
