### PR TITLE
Change message of unknown joypad property from error to verbose

### LINKED ISSUE #72732: parse_mapping error on Steam Deck
### Godot version

v3.5.1.stable.official [6fed1ffa3]

### System information

Steam OS Holo, Steam Deck

### Issue description

Running any game in the Godot editor (even a brand new empty project) prints the following error:
```
E 0:00:00.419   parse_mapping: Unrecognised output string "crc" in mapping:
03000000de2800000512000011010000,Steam Deck,a:b3,b:b4,x:b5,y:b6,back:b11,guide:b13,start:b12,leftstick:b14,rightstick:b15,leftshoulder:b7,rightshoulder:b8,dpup:b16,dpdown:b17,dpleft:b18,dpright:b19,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a9,righttrigger:a8,crc:17f6,platform:Linux
  <C++ Error>   Condition "output_button == JOY_INVALID_OPTION && output_axis == JOY_INVALID_OPTION" is true. Continuing.
  <C++ Source>  main/input_default.cpp:1182 @ parse_mapping()
```

I'm not sure when this started happening, but it happens consistently.  It doesn't seem to matter whether the Steam Deck is docked or not.

### Steps to reproduce

1. Download the official Godot distribution via Steam.
2. Switch to Desktop mode.
3. Launch Godot.
4. Run any project.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by rsubtil**
Closes https://github.com/godotengine/godot/issues/72732

Unrecognized parameters in joypad strings show up as errors despite being skipped internally. This changes it to a verbose message as to not confuse users.

### CODE REVIEW

File: core/input/input.cpp [hunk 1]
```diff
@@ -1365,10 +1365,12 @@ void Input::parse_mapping(String p_mapping) {
 
 		JoyButton output_button = _get_output_button(output);
 		JoyAxis output_axis = _get_output_axis(output);
-		ERR_CONTINUE_MSG(output_button == JoyButton::INVALID && output_axis == JoyAxis::INVALID,
-				vformat("Unrecognized output string \"%s\" in mapping:\n%s", output, p_mapping));
-		ERR_CONTINUE_MSG(output_button != JoyButton::INVALID && output_axis != JoyAxis::INVALID,
-				vformat("Output string \"%s\" matched both button and axis in mapping:\n%s", output, p_mapping));
```
Comment (akien-mga) [inline core/input/input.cpp:1371]: I'm not too familiar with the code but isn't this one still one situation which should never happen? If so, keep it as an error message makes sense to me.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.2.

File: core/input/input.cpp [hunk 2]
```diff
@@ -1365,8 +1365,9 @@ void Input::parse_mapping(String p_mapping) {
 
 		JoyButton output_button = _get_output_button(output);
 		JoyAxis output_axis = _get_output_axis(output);
-		ERR_CONTINUE_MSG(output_button == JoyButton::INVALID && output_axis == JoyAxis::INVALID,
-				vformat("Unrecognized output string \"%s\" in mapping:\n%s", output, p_mapping));
+		if (output_button == JoyButton::INVALID && output_axis == JoyAxis::INVALID) {
+			print_verbose(vformat("Unrecognized output string \"%s\" in mapping:\n%s", output, p_mapping));
+		}
```
Comment (akien-mga) [inline core/input/input.cpp:1370]: I noticed thanks to a static analyzer that we should have kept a `continue;` here.
The further logic will be broken as it won't be able to assign a valid `outputType` to the mapping. (I'm making a PR.)
