### PR TITLE
MultiNodeEdit now only shows properties with the exact same PropertyInfo data

### LINKED ISSUE #30345: MultiNodeEdit shows properties that are of the same name but not the same type between all selected nodes
**Godot version:**
current master

**Issue description:**
Currently, MultiNodeEdit only shows properties when the property name is present in all selected nodes. However, it fails to take into account the property type. Thus, it will show a property i.e. `location` even if one node defines it as a string and another defines it as a Vector2. I have not tested what will happen if you attempt to change a property like that, but I don't think I need to in order to show how much havok that can cause.

I think the easiest solution, if one were to be implemented, is to simply make sure that the property is the same type across all selected nodes, although ideally all the property data should be the same between all selected nodes for it to show. Though looking through the source code, this may require a rewrite of [MultiNodeEdit's `_get_property_list` method](https://github.com/godotengine/godot/blob/d897131ac555de84afe9ca6845abf87c26957895/editor/multi_node_edit.cpp#L119-L169).

**Steps to reproduce:**
1. Have `export(String) var location` in one node's script
2. Have `export(Vector2) var location` in another node's script
3. Select both in the scene tree and note that the property `location` will appear in the editor inspector.

### PR DESCRIPTION
**Pull request by LikeLakers2**
Fixes #30345.

~~I considered making it only check for type, but I felt that might still create conflict, so I have it check the hint, hint_string, and usage as well.~~ It now makes sure the two `PropertyInfo`s are the same.

### CODE REVIEW

File: editor/multi_node_edit.cpp [hunk 1]
```diff
@@ -152,7 +152,12 @@ void MultiNodeEdit::_get_property_list(List<PropertyInfo> *p_list) const {
 				datas.push_back(usage.getptr(F->get().name));
 			}
 
-			usage[F->get().name].uses++;
+			// Make sure only properties with the same exact PropertyInfo data will appear
+			if (usage[F->get().name].info.type == F->get().type &&
+					usage[F->get().name].info.hint == F->get().hint &&
+					usage[F->get().name].info.hint_string == F->get().hint_string &&
+					usage[F->get().name].info.usage == F->get().usage)
+				usage[F->get().name].uses++;
```
Comment (LikeLakers2) [inline editor/multi_node_edit.cpp]: Before this is merged, I'd like to ask if I should leave the comparison this way, or if I should move it to an `operator==` function inside PropertyInfo, or if perhaps I should truncate the comparisons down to just the type.

Also, I tried using `.operator Dictionary()` on both sides and comparing the two dictionaries, but that ended up never showing any of the properties. I don't know what's going on there.

File: editor/multi_node_edit.cpp [hunk 2]
```diff
@@ -152,7 +152,12 @@ void MultiNodeEdit::_get_property_list(List<PropertyInfo> *p_list) const {
 				datas.push_back(usage.getptr(F->get().name));
 			}
 
-			usage[F->get().name].uses++;
+			// Make sure only properties with the same exact PropertyInfo data will appear
+			if (usage[F->get().name].info.type == F->get().type &&
+					usage[F->get().name].info.hint == F->get().hint &&
+					usage[F->get().name].info.hint_string == F->get().hint_string &&
+					usage[F->get().name].info.usage == F->get().usage)
```
Comment (LikeLakers2) [inline editor/multi_node_edit.cpp]: Before this is merged, I'd like to ask if I should leave the comparison this way, or if I should move it to an `operator==` function inside PropertyInfo, or if perhaps I should truncate the comparisons down to just the type comparison.

Also, I tried using `.operator Dictionary()` on both sides and comparing the two dictionaries, but that ended up never showing any of the properties. I don't know what's going on there.

**Comment by akien-mga** [comment]
Thanks!
