### PR TITLE
Fix UV issues in Compatibility renderer

### LINKED ISSUE #86746: Inconsistant `UV` coordinates between `Forward+` and `Compatibility`
### Tested versions

v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.2.1.stable.mono - Arch Linux #1 SMP PREEMPT_DYNAMIC Thu, 21 Dec 2023 19:01:01 +0000 - Wayland - Vulkan (Forward+) - integrated Intel(R) UHD Graphics 630 (CFL GT2) () - Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 Threads)

### Issue description

This simple shader looks different between `Forward+` and `Compatibility`

```glsl
void fragment() {
	COLOR =vec4(1.0)-vec4( smoothstep(0.5, 0.5 , length(UV - vec2(0.5))) );
}
```
image
image

### Steps to reproduce

1. Create a simple Spirit2D with a canvas texture and set its material shader above.
2. Switch between `Forward+` and `Compatibility`
3. They look different, and I think `Compatibility` is bugged.

### Minimal reproduction project (MRP)

[bugreport.zip](https://github.com/godotengine/godot/files/13819005/bugreport.zip)

### PR DESCRIPTION
**Pull request by moonpirates**
Fixes a bug where CanvasTexture's UVs were off when using the Compatibility mode's renderer.

Fixes #86746

### CODE REVIEW

File: drivers/gles3/rasterizer_canvas_gles3.cpp [hunk 1]
```diff
@@ -2295,13 +2295,17 @@ void RasterizerCanvasGLES3::_prepare_canvas_texture(RID p_texture, RS::CanvasIte
 
 	GLES3::Texture *texture = texture_storage->get_texture(ct->diffuse);
 	Size2i size_cache;
+
+	// Cache default white resource ID
```
Comment (AThousandShips) [inline drivers/gles3/rasterizer_canvas_gles3.cpp:2299]:
```suggestion
	// Cache default white resource ID.
```
Per the [comment style](https://docs.godotengine.org/en/latest/contributing/development/code_style_guidelines.html#comment-style-guide).

File: drivers/gles3/rasterizer_canvas_gles3.cpp [hunk 2]
```diff
@@ -2295,13 +2295,17 @@ void RasterizerCanvasGLES3::_prepare_canvas_texture(RID p_texture, RS::CanvasIte
...
+	const RID default_texture_id = texture_storage->texture_gl_get_default(GLES3::DEFAULT_GL_TEXTURE_WHITE);
+
+	// If no texture is assigned, assign default white
```
Comment (AThousandShips) [inline drivers/gles3/rasterizer_canvas_gles3.cpp:2302]:
```suggestion
	// If no texture is assigned, assign default white.
```

File: drivers/gles3/rasterizer_canvas_gles3.cpp [hunk 3]
```diff
@@ -2295,13 +2295,17 @@ void RasterizerCanvasGLES3::_prepare_canvas_texture(RID p_texture, RS::CanvasIte
...
-		ct->diffuse = texture_storage->texture_gl_get_default(GLES3::DEFAULT_GL_TEXTURE_WHITE);
-		GLES3::Texture *tex = texture_storage->get_texture(ct->diffuse);
-		size_cache = Size2i(tex->width, tex->height);
-	} else {
-		size_cache = Size2i(texture->width, texture->height);
-	}
+		ct->diffuse = default_texture_id;
+	} 
+	
+	// Enforce a 1x1 size if default white texture
```
Comment (AThousandShips) [inline drivers/gles3/rasterizer_canvas_gles3.cpp:2307]:
```suggestion
	// Enforce a 1x1 size if default white texture.
```

File: drivers/gles3/rasterizer_canvas_gles3.cpp [hunk 4]
```diff
@@ -2295,13 +2295,17 @@ void RasterizerCanvasGLES3::_prepare_canvas_texture(RID p_texture, RS::CanvasIte
...
+	// If no texture is assigned, assign default white 
 	if (!texture) {
-		ct->diffuse = texture_storage->texture_gl_get_default(GLES3::DEFAULT_GL_TEXTURE_WHITE);
-		GLES3::Texture *tex = texture_storage->get_texture(ct->diffuse);
-		size_cache = Size2i(tex->width, tex->height);
-	} else {
-		size_cache = Size2i(texture->width, texture->height);
-	}
+		ct->diffuse = default_texture_id;
+	}
```
Comment (AThousandShips) [inline drivers/gles3/rasterizer_canvas_gles3.cpp:2305]:
```suggestion
	}
```
Trailing whitespace

**Comment by AThousandShips** [comment]
I'd suggest against breaking up the if/else block, it makes sense as it were, just fixing the size in the default case, like so:
```cpp
if (!texture) {
	ct->diffuse = texture_storage->texture_gl_get_default(GLES3::DEFAULT_GL_TEXTURE_WHITE);
	size_cache = Size2i(1, 1);
} else {
	size_cache = Size2i(texture->width, texture->height);
}
```
And remove the rest

**Comment by moonpirates** [comment]
@AThousandShips the problem with that is that the diffuse slot, upon a subsequent iteration, is assigned to a texture (the default white), making it end up in the else statement, which will fall back to the 4x4 size.

Thanks for your feedback, I'll fix that!

File: drivers/gles3/rasterizer_canvas_gles3.cpp [hunk 5]
```diff
@@ -2295,13 +2295,17 @@ void RasterizerCanvasGLES3::_prepare_canvas_texture(RID p_texture, RS::CanvasIte
...
+	// If no texture is assigned, assign default white.
 	if (!texture) {
-		ct->diffuse = texture_storage->texture_gl_get_default(GLES3::DEFAULT_GL_TEXTURE_WHITE);
-		GLES3::Texture *tex = texture_storage->get_texture(ct->diffuse);
-		size_cache = Size2i(tex->width, tex->height);
-	} else {
-		size_cache = Size2i(texture->width, texture->height);
+		ct->diffuse = default_texture_id;
 	}
+
```
Comment (AThousandShips) [inline drivers/gles3/rasterizer_canvas_gles3.cpp:2306]: You have a tab here, needs to be empty 🙂

Comment (moonpirates) [reply drivers/gles3/rasterizer_canvas_gles3.cpp:2306]: Going to use this as an opportunity to install the formatter ;)

**Review by clayjohn — APPROVED** [review]
Looks great!

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
