### PR TITLE
Fix crash caused by stale owner

### LINKED ISSUE #78736: Errors and Crash with queue_free() in certain conditions
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Godot v4.0.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 (NVIDIA; 31.0.15.1694) - Intel(R) Core(TM) i5-10600KF CPU @ 4.10GHz (12 Threads)

### Issue description

Calling `queue_free()` in certain conditions cause the following error to be thrown, and occasionally cause errorless crashes.
```
erase: Condition "p_I->data != this" is true. Returning: false
  <C++ Source>   ./core/templates/list.h:223 @ erase()
```
The exact conditions aren't clear: commenting out almost any line or awaiting a frame almost anywhere prevents the error, so maybe some there's some race condition?

The error also isn't super consistent, but I've managed to create a minimal reproduction project that causes the error more >50% of the time.

Call stack on crash:
<details> godot.windows.editor.dev.x86_64.exe!List<Node *,DefaultAllocator>::erase(const List<Node *,DefaultAllocator>::Element * p_I) Line 431 (c:\Users\Hayden\Documents\Godot\Source\godot\core\templates\list.h:431)
godot.windows.editor.dev.x86_64.exe!Node::_propagate_after_exit_tree() Line 265 (c:\Users\Hayden\Documents\Godot\Source\godot\scene\main\node.cpp:265)
godot.windows.editor.dev.x86_64.exe!Node::remove_child(Node * p_child) Line 1227 (c:\Users\Hayden\Documents\Godot\Source\godot\scene\main\node.cpp:1227)
godot.windows.editor.dev.x86_64.exe!Node::_notification(int p_notification) Line 168 (c:\Users\Hayden\Documents\Godot\Source\godot\scene\main\node.cpp:168)
godot.windows.editor.dev.x86_64.exe!Node::_notificationv(int p_notification, bool p_reversed) Line 46 (c:\Users\Hayden\Documents\Godot\Source\godot\scene\main\node.h:46)
godot.windows.editor.dev.x86_64.exe!Object::notification(int p_notification, bool p_reversed) Line 792 (c:\Users\Hayden\Documents\Godot\Source\godot\core\object\object.cpp:792)
godot.windows.editor.dev.x86_64.exe!Object::_predelete() Line 197 (c:\Users\Hayden\Documents\Godot\Source\godot\core\object\object.cpp:197)
godot.windows.editor.dev.x86_64.exe!predelete_handler(Object * p_object) Line 1826 (c:\Users\Hayden\Documents\Godot\Source\godot\core\object\object.cpp:1826)
godot.windows.editor.dev.x86_64.exe!memdelete<Object>(Object * p_class) Line 105 (c:\Users\Hayden\Documents\Godot\Source\godot\core\os\memory.h:105)
godot.windows.editor.dev.x86_64.exe!SceneTree::_flush_delete_queue() Line 1065 (c:\Users\Hayden\Documents\Godot\Source\godot\scene\main\scene_tree.cpp:1065)
godot.windows.editor.dev.x86_64.exe!SceneTree::process(double p_time) Line 476 (c:\Users\Hayden\Documents\Godot\Source\godot\scene\main\scene_tree.cpp:476)
godot.windows.editor.dev.x86_64.exe!Main::iteration() Line 3169 (c:\Users\Hayden\Documents\Godot\Source\godot\main\main.cpp:3169)
godot.windows.editor.dev.x86_64.exe!OS_Windows::run() Line 1295 (c:\Users\Hayden\Documents\Godot\Source\godot\platform\windows\os_windows.cpp:1295)
godot.windows.editor.dev.x86_64.exe!widechar_main(int argc, wchar_t * * argv) Line 181 (c:\Users\Hayden\Documents\Godot\Source\godot\platform\windows\godot_windows.cpp:181)
godot.windows.editor.dev.x86_64.exe!_main() Line 203 (c:\Users\Hayden\Documents\Godot\Source\godot\platform\windows\godot_windows.cpp:203)
godot.windows.editor.dev.x86_64.exe!main(int argc, char * * argv) Line 217 (c:\Users\Hayden\Documents\Godot\Source\godot\platform\windows\godot_windows.cpp:217)
godot.windows.editor.dev.x86_64.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 231 (c:\Users\Hayden\Documents\Godot\Source\godot\platform\windows\godot_windows.cpp:231)
[Inline Frame] godot.windows.editor.dev.x86_64.exe!invoke_main() Line 102 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:102)
godot.windows.editor.dev.x86_64.exe!__scrt_common_main_seh() Line 288 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
kernel32.dll!00007ff8b1a67614() (Unknown Source:0) </details>

### Steps to reproduce

Simply run the provided MRP. The error doesn't show up every time it is run, nor does it cause a crash everytime, so you may need to run it more than once.

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/11878305/MRP.zip)

### PR DESCRIPTION
**Pull request by Sauermann**
Adjust `NOTIFICATION_PREDELETE` in `Node` to clean up owned nodes.
Also print a warning, when the owner becomes invalid.
resolve #78736

Updated 2023-11-17: Rebased

### CODE REVIEW

**Comment by RandomShaper** [comment]
I see cases where this is needed, but I think there's still a case to fix: in the MRP in #78736, shouldn't the `child_node.reparent(self)` break the ownership of `child_node` by `owner_node`?

**Comment by Sauermann** [comment]
I have investigated this case and I was unable to create a crash by reparenting after the changes of this PR.
Still I believe, that there is a bug, that currently reparenting allows a Node to have an owner, that is not an ancestor (which contradicts the `owner`-description).
I was unable to finish this investigation yesterday and intend to look into this again.

**Comment by Sauermann** [comment]
I have updated the PR with an additional verification, that the owner is always an ancestor and added a warning about this case.

I have also considered as a more strict alternative in `Node::add_child`, but would consider it as too restrictive:
``` c++
	ERR_FAIL_COND_MSG(p_child->data.owner && p_child->data.owner != this && !p_child->data.owner->is_ancestor_of(this), vformat("Can't add child '%s' to '%s', owner '%s' would no longer be an ancestor.", p_child->get_name(), get_name(), p_child->data.owner->get_name()));
```

I have also considered as a less strict alternative to adjust the documentation of `Node.owner`, but had the impression that this would find not enough attention and users might not easily find the reason, why their node's owner became `null`:
```
[b]Note:[/b] The owner of the [Node] is automatically erased, if the node is moved to a place in the scene tree where its owner is no longer an ancestor.
```

**Comment by RandomShaper** [comment]
I agree with that approach.

I'm wondering if it should be expected that a node still has owned nodes by the time the destructor is run. Shouldn't all the previous mechanics of the owner and/or owned nodes (pre-delete, exit tree notifications, etc., etc.) have cleaned things up?

**Comment by Sauermann** [comment]
One of the MRPs in the linked issue sets the owner of a Node, while that node is not in the tree. So tree-notifications don't help in these cases.
Also when handling this during tree-notifications, the owner would always be removed when a Node is relocated in the scene tree, which would be bad for usability.

I was not aware of pre-delete, thanks for bringing this to my attention. 
During `NOTIFICATION_PREDELETE` currently only `data.owner` is cleared, but not `data.owned`.
I believe, that it would be conceptually better, if I move the `data.owned`-clean-up code from `~Node` to `NOTIFICATION_PREDELETE`.

**Comment by YuriSizov** [comment]
Slightly relevant here: we now have a PR that changes how reparenting works https://github.com/godotengine/godot/pull/81506.
But I guess that wouldn't completely eliminate invalid cases we are trying to prevent here? I would err on the side of caution at this point and bump this to 4.3.

 But an approval from @RandomShaper would still be appreciated so we can merge it as soon as the next dev cycle starts 🙂

File: scene/main/node.cpp [hunk 1]
```diff
@@ -1363,6 +1368,12 @@ void Node::_add_child_nocheck(Node *p_child, const StringName &p_name, InternalM
 
 	p_child->data.parent = this;
 
+	if (p_child->data.owner && !p_child->data.owner->is_ancestor_of(p_child)) {
+		// Owner of p_child must be ancestor of p_child.
+		WARN_PRINT(vformat("Adding '%s' as child to '%s' would make owner '%s' inconsistent. Erasing owner. Consider removing the owner beforehand.", p_child->get_name(), get_name(), p_child->data.owner->get_name()));
+		p_child->_clean_up_owner();
+	}
+
```
Comment (YuriSizov) [inline scene/main/node.cpp:1376]: I don't think this scenario should ever be possible. If it's possible, guards are missing elsewhere. But if you want to be extra sure, maybe this should only happen in editor builds?

Comment (RandomShaper) [reply scene/main/node.cpp:1376]: I'd move this check to `add_child()` instead, which is anyway the only caller of `_add_child_nocheck()` (possibly, to a counterpart of `_validate_child_name()` named `_validate_child_future_ownership(node, intended_new_parent)`). That way, `_add_child_nocheck()` still honors its name (althought the _no check_ part was about names, but now we're validating owners, it's good to extend that notion).

Aside, I think that with this we would be catching every possibility of a wrong owner. That said, given that this _may_ have a performance impact, I see value in restricting the check to debug builds, and making it just a check. I mean, keep the owner (even if invalid), not to change behavior across debug and non-debug. After all, I don't think owner chain integrity is an internal requisite of the engine (engine won't crash or misbehave due to an inconsitency there; only the user may get unexpected results).

Finally, I'd suggest changing the wording so _erasing/removing owner_ is expressed as _unsetting the owner_ instead, for enhanced clarity.

Comment (Sauermann) [reply scene/main/node.cpp]: I have moved the validation of the owner to `add_child()` within a `DEBUG_ENABLED` section.

Please note that `_add_child_nocheck()` is additionally called from `SceneState::instantiate`. But since this function deals with instantiating nodes, my guess would be, that it's unnecessary to add checks there.

I would prefer to completely prohibit inconsistent states (so that the user no longer gets unexpected results), but based on the performance-argument, I assume that a warning can be considered sufficient.

For good measure, I have also checked, that the MRP in the linked issue still crashes in v4.2.rc.custom_build [80de898d7] and gets fixed by this PR.

**Review by RandomShaper — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.
