### PR TITLE
Fix tileset editor visiblity and selection context

### LINKED ISSUE #56413: TileSet editor doesn't open right after creating TileSet
### Godot version

bc2445d

### System information

W10

### Issue description

When you create a fresh new TileMap, right click `tile_set` property and create a new TileSet, the resource is created, but then nothing happens. You need to click the TileSet resource for the TileSet bottom editor to appear.

This could make sense if not the fact that you can deselect TileMap node and select it again for the TileSet to appear again. Whenever you do something with TileMap, both TileSet and TileMap editors are always automatically visible. The only exception is when you create a new TileMap and click it when it doesn't have any TileSet. I got used so much to having both editors always visible that it actually confused me.

When a new TileSet is created in TileMap, the TileSet editor tab should be immediately visible.

### Steps to reproduce

1. Create new TileMap node
2. Create new TileSet for that TileMap
3. Where editor
image

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by SaracenOne**
Makes sure the tileset editor is automatically selected when editing a tileset by clicking on it from the tilemap property in the insepctor. Also makes sure the tileset editor button's visibility is immediately toggled when a tileset is assigned or unassigned from a currently selected tilemap node.

Closes #56413

### CODE REVIEW

**Comment by SaracenOne** [comment]
Wait, need to change something...

**Comment by SaracenOne** [comment]
Okay, should be sorted now. Silly oversight on my behalf

File: editor/plugins/tiles/tiles_editor_plugin.cpp [hunk 1]
```diff
@@ -172,10 +175,13 @@ void TilesEditorPlugin::_notification(int p_what) {
 	switch (p_what) {
 		case NOTIFICATION_INTERNAL_PROCESS: {
 			if (tile_map_changed_needs_update) {
-				TileMap *tile_map = Object::cast_to<TileMap>(ObjectDB::get_instance(tile_map_id));
-				if (tile_map) {
-					tile_set = tile_map->get_tileset();
+				if (is_visible) {
```
Comment (groud) [inline editor/plugins/tiles/tiles_editor_plugin.cpp:178]: I don't feel this is right. What is this check for exactly?
If the TileMap changed, and the TileSet was changed for another one, I don't get why the visibility of the editor would have an impact on that. Is this for optimization?

**Comment by SaracenOne** [comment]
Updated to be a tad less hacky

File: editor/plugins/tiles/tiles_editor_plugin.cpp [hunk 2]
```diff
@@ -158,6 +158,9 @@ void TilesEditorPlugin::_update_editors() {
 	// Update the viewport.
 	CanvasItemEditor::get_singleton()->update_viewport();
 
+	// Make sure the tile set editor is visible if we have one assigned.
+	tileset_editor_button->set_visible(is_visible && tile_set.is_valid());
```
Comment (groud) [inline editor/plugins/tiles/tiles_editor_plugin.cpp:162]: I am not sure I understand why this is needed. Wasn't this already working?
Reading what is in make_visible() it seems like this is already done.

Comment (SaracenOne) [reply editor/plugins/tiles/tiles_editor_plugin.cpp:162]: @groud Sorry, I completely forgot about this, but I remember it now because I'm doing another pass over all the editor plugins at the moment. With regards to this visibility check, it needs both checks to be successful otherwise the tileset button will still be visible even when you aren't highlighting a tileset node.

**Review by akien-mga — APPROVED** [review]
Approved in PR review meeting.

**Comment by akien-mga** [comment]
Thanks!
