### PR TITLE
Correctly display tooltips for buttons in Tree when they overlap cell content (reverted)

### LINKED ISSUE #79629: Editor : Scene Tree icons' tooltips dont match icon when narrow
### Godot version

4.1.stable

### System information

Windows 11 (x64), Intel(R) Core(TM) i5-9400 CPU, Vulkan,  NVIDIA GeForce GTX 1660 Ti driver version 528.24

### Issue description

When resizing the Scene Tree view, making it narrow, the tooltips of the icons no longer match the position of the icons. 
The tooltip rect is pushed off to the side.
Video showing bug:

https://github.com/godotengine/godot/assets/104696964/bc9918a0-4f4c-4722-aee3-7887d0e3dd5d

### Steps to reproduce

Make your Scene Tree view narrow. Hover over the icons. The tooltip activation area does not match the icon.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Miguel0312**
Closes #79629 

I copied the 3.x behavior for the SceneTree: once the width becomes too small, the overflowing text of the node's name is hidden.

TooltipBug

The way I found to do this is by creating a second column in the TreeItem and adding the buttons to this column to make sure that there is no overlap. I also set the clip property of the first column to false in order to hide the overflow

### CODE REVIEW

**Comment by YuriSizov** [comment]
That doesn't really solve the problem and also introduces an ugly visual bug. If buttons that overlap text don't show their tooltips and instead the text content's tooltip is shown, then we should make sure that the elements which are visually on top contribute to the tooltip ahead of the elements which are below. See `Tree::get_tooltip` and check if it tests for buttons too late instead.

**Comment by Miguel0312** [comment]
I found the bug. The get_tooltip function didn't take into account the fact that when we have an h_bar the button is not at the end of the TreeItem. I just had to take the offset between the size of the item and the size of the element being displayed. Now we have the following:
TooltipBug2

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -5329,10 +5329,12 @@ String Tree::get_tooltip(const Point2 &p_pos) const {
 				pos.x -= get_column_width(i);
 			}
 
+			int buttonOffset = h_scroll->get_max() - h_scroll->get_page() - h_scroll->get_value();
```
Comment (YuriSizov) [inline scene/gui/tree.cpp:5332]: I'm not entirely sure about the logic yet, but at the very least the variable should be named with the under_score style.

**Comment by YuriSizov** [comment]
Okay, so after looking through the logic and the suggested change I think that the solution should be to add position to the `Button` struct and cache it during the drawing step. Then use it here to determine if we are over the button or not. The logic for determining the exact placement of each button is rather complex and it's counter-productive to try and replicate it or approximate its values by some other means.

The change needs to happen in `Tree::draw_item` around the code that draws the button texture, as that's where we have the exact position and size. We can even cache entire `Rect2`, as the size can also be limited by other factors and not come from the texture itself. Then the check in the `get_tooltip` method can just try to see if this rect includes our position.

**Review by YuriSizov — CHANGES_REQUESTED** [review]
See above.

**Comment by Miguel0312** [comment]
I modified the implementation to use the cache as explained on the comment above. The result is the same as before (it also works for vertical-scrolling):
TooltipBug3

**Review by YuriSizov — CHANGES_REQUESTED** [review]
Almost ready, but you've removed a bit too much. Make sure to test with multicolumn Trees.

I would also recommend rebasing against the current master, as your base commit is over a month old.

Edit: Oh, and please amend the commit message. The title of the PR is a good option.

File: scene/gui/tree.cpp [hunk 2]
```diff
@@ -37,6 +37,7 @@
 #include "core/os/os.h"
 #include "core/string/print_string.h"
 #include "core/string/translation.h"
+#include "core/variant/variant.h"
```
Comment (AThousandShips) [inline scene/gui/tree.cpp:40]: Why was this added? This is already included, or was there some issue?

Comment (Miguel0312) [reply scene/gui/tree.cpp]: It is not necessary. It was an auto inserted by the IDE at some point and I didn't realize. I recompiled and it worked just fine.

**Review by YuriSizov — APPROVED** [review]
LGTM.

There are still some inconsistencies regarding buttons' position when we detect clicks, but it's a pre-existing issue that's unrelated to this. I'll take a look as a follow-up to this PR.

**Comment by akien-mga** [comment]
Thanks!
