### PR TITLE
Fix rotated 2D movement gizmo

### LINKED ISSUE #62732: 2D movement gizmos always work in global coordinates despite being rotated
### Godot version

4e7223c

### System information

Windows 10 x64

### Issue description

godot windows tools 64_VeecI3EiEe
They should either not rotate or properly move in local space.

This does not happen with scale gizmos.

### Steps to reproduce

1. Rotate a 2D node
2. Enable move tool
3. Move the node

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #62732

I noticed that move tools has a weird logic where it resets the node's position and then moves it as a delta of initial position + delta. Well, the reset part allowed me to use `get_local_mouse_position()`, which made it trivial to fix the rotated behavior 🤷‍♂️

https://github.com/godotengine/godot/assets/2223172/92dabd07-3728-45c4-a394-59a8fcfa97c7

### CODE REVIEW

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -2056,27 +2056,31 @@ bool CanvasItemEditor::_gui_input_move(const Ref<InputEvent> &p_event) {
...
+				const CanvasItem *selected = drag_selection.front()->get();
+				if (drag_type == DRAG_MOVE_X) {
+					new_pos = Vector2(selected->get_local_mouse_position().x, 0);
+				} else {
+					new_pos = Vector2(0, selected->get_local_mouse_position().y);
+				}
+				new_pos = selected->get_transform().xform(new_pos);
+			} else {
+				new_pos = previous_pos + (drag_to - drag_from);
 			}
```
Comment (kleonc) [inline editor/plugins/canvas_item_editor_plugin.cpp:2082]: Using `get_local_mouse_position()` seems hackish, no? :thinking:

AFAICT looking at that code `new_pos` is supposed to be in the coordinate space of the `selected`'s parent. So (in case it's preferred to not use `get_local_mouse_position` like that) I think all that needs to be done is something like this (hopefully it will just work, haven't tested or anything :smile:):

```suggestion
			Vector2 drag_delta = drag_to - drag_from;
			if (drag_selection.size() == 1 && (drag_type == DRAG_MOVE_X || drag_type == DRAG_MOVE_Y)) {
				// Drag by local axis, so transform the drag to local space, then zero an axis, then transform back to parent space.
				const CanvasItem *selected = drag_selection.front()->get();
				drag_delta = selected->get_transform().affine_inverse().basis_xform(drag_delta);
				if (drag_type == DRAG_MOVE_X) {
					drag_delta.y = 0;
				} else {
					drag_delta.x = 0;
				}
				drag_delta = selected->get_transform().basis_xform(drag_delta);
			}
			new_pos = previous_pos + drag_delta;
```

Comment (KoBeWi) [reply editor/plugins/canvas_item_editor_plugin.cpp]: It works, thx.
Using `get_local_mouse_position()` isn't really a hack, but your code would make it easier to remove the "reset" behavior I mentioned.

**Review by kleonc — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
