### PR TITLE
Make `PopupMenu` respect `max_size`

### LINKED ISSUE #111790: Potential PopupMenu bug/regression in Godot 4.5.x - property min_size gets overwritten
### Tested versions

Reproducible in: v4.5.stable.official [876b29033]
Not reproducible in: v4.4.1.stable.official [49a5bc7b6]

### System information

Windows 10 (build 19045) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 (NVIDIA; 32.0.15.6094) - 12th Gen Intel(R) Core(TM) i5-12400F (12 threads) - 63.86 GiB memory

### Issue description

PopupMenu nodes with a lot of items, that are the child of a MenuBar node, do not adhere to the max_size set for them. The property is ignored, because something keeps overwriting the min_size property during run time. As a result the popup menu spans the entire window. Setting the min_size to a fixed value and wrap_controls to false does not prevent this from happening. 

This unexpected behavior occurs in Godot 4.5 and 4.5.1. 
Image

In Godot 4.4.1 the PopupMenu node works as expected.
Image

### Steps to reproduce

Create a scene with a MenuBar node as the main node. Through the editor or code add a PopupMenu node as a child and set max_size, min_size and wrap_controls. Add an amount of items to the PopupMenu node that would exceed the size of the window, e.g.:

```gdscript
extends MenuBar

func _ready() -> void:
	var popup = PopupMenu.new()
	popup.wrap_controls = false
	popup.min_size = Vector2(50,50)
	popup.max_size = Vector2(200,100)
	add_child(popup)
	for counter in range(1,50):
		popup.add_item(str(counter))
	pass
```

### Minimal reproduction project (MRP)

N/A but I already made one

[test.zip](https://github.com/user-attachments/files/22984684/test.zip)

### PR DESCRIPTION
**Pull request by scgm0**
Fix #111790
Meanwhile, if `wrap_controls` is set to false, `PopupMenu` will no longer reset `min_size` and `size`. Given that `Popup` defaults `wrap_controls` to true, this change should have minimal impact on existing projects. Users who manually set `wrap_controls` to false are expected to manage the size of `PopupMenu` themselves.

### CODE REVIEW

File: scene/gui/popup_menu.cpp [hunk 1]
```diff
@@ -3230,14 +3230,16 @@ void PopupMenu::_pre_popup() {
...
-	minsize.height = Math::ceil(minsize.height); // Ensures enough height at fractional content scales to prevent the v_scroll_bar from showing.
-	real_t max_h = get_max_size().height;
-	if (max_h > 0) {
-		minsize.height = MIN(minsize.height, max_h);
+	if (is_wrapping_controls()) {
+		Size2 minsize = get_contents_minimum_size() * popup_scale;
+		Size2 maxsize = get_max_size();
+		if (maxsize.height > 0 && maxsize.width > 0) {
+			minsize = minsize.min(maxsize);
+		}
```
Comment (bruvzg) [inline scene/gui/popup_menu.cpp]: Should be two separate ifs, since width and height can be set independently.
```suggestion
		if (maxsize.height > 0) {
			minsize.height = MIN(minsize.height, maxsize.height);
		}
		if (maxsize.width > 0) {
			minsize.width = MIN(minsize.width, maxsize.width);
		}
```

Comment (scgm0) [reply scene/gui/popup_menu.cpp]: Done.

**Review by bruvzg — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
