### PR TITLE
OpenGL: Unconditionally do `glDisable(GL_FRAMEBUFFER_SRGB)` because we do our own sRGB conversion

### LINKED ISSUE #95313: OpenXR composition layers perform sRGB conversion on android, when color space is already sRGB
### Tested versions

- Tested on v4.3-rc2

### System information

Oculus Quest 2, Compatibility GL

### Issue description

When using the new composition layers in VR, it seems like the Quest performs sRGB conversion when it shouldn't. This only happens on android (Meta Quest 2) and it works correctly on PC. I don't know if this happens with other headsets or even with other Quest devices.

| What it looks like | What it should look like |
|-------------------|--------------------------|
| Xiaosaurus-Bouncy-Regular | Amethystsunbird-Forked-Darkolivegreen |

I can more or less confirm this is the issue because I wrote a shader that essentially reverts the sRGB conversion, and with that shader it looks ok. Shader:

```
shader_type canvas_item;
render_mode unshaded;

uniform sampler2D screen : source_color, hint_screen_texture, filter_linear, repeat_enable;


void fragment() {
	vec4 screen_texture = texture(screen, SCREEN_UV);
	screen_texture.rgb = pow(screen_texture.rgb, vec3(1.0 / 0.45));
	COLOR = screen_texture;
}
```

And here's a video of me enabling/disabling the shader:

https://github.com/user-attachments/assets/29f1a763-b280-4b2e-96e9-71d58392b4a5

### Steps to reproduce

- Create a SubViewport with a simple `TextureRect` with an image as a child.
- Create a `OpenXRCompositionLayerQuad`

### Minimal reproduction project (MRP)

The issue is easily reproducible, and adding the vendors plugin would make the project too big to upload.

### PR DESCRIPTION
**Pull request by dsnopek**
Fixes https://github.com/godotengine/godot/issues/95313

I think this is the right thing to do, because:

- OpenGL will only do the linear to sRGB conversion enabled via `glEnable(GL_FRAMEBUFFER_SRGB)` on FBO's that have a color attachment which uses an sRGB internal format. So, it will do the conversion on `GL_SRGB8_ALPHA8`, but _not_ on `GL_RGBA8`
- Godot's renderer doesn't normally use any sRGB internal formats for render buffers, because we do the linear to sRGB conversion ourselves in our shaders
- We're only using `GL_SRGB8_ALPHA8` in OpenXR, because if we don't, the OpenXR compositor will assume the content is linear, and it'll do another linear to sRGB conversion. So, we're forced to use that as the internal format, in order to signal that we're giving it sRGB data
- It should be safe to do `glDisable(GL_FRAMEBUFFER_SRGB)` unconditionally, because Godot's OpenGL renderer isn't even relying on that anyway (as explained above in my second point in this list)

~~The main thing I'm not sure about, is if doing this in `RasterizerGLES3::begin_frame()` is the right place to do it? We don't actually need to do it every frame, but I couldn't find an obvious central place to do it, It works fine in `GLES3::Config::Config()` which only runs once, but we're only querying config there, not setting it, so it seemed inappropriate. I'd appreciate any advice about this!~~

**UPDATE:** Moved to `RasterizerGLES3::RasterizerGLES3()` based on advice from Clay.

This PR also partially reverts the changes from https://github.com/godotengine/godot/pull/74892, which did `glDisable(GL_FRAMEBUFFER_SRGB)`, but only when rendering viewports with `use_xr` set to `true` (which doesn't help the composition layers). With this PR doing it unconditionally, that is no longer necessary.

### CODE REVIEW

File: drivers/gles3/rasterizer_gles3.cpp [hunk 1]
```diff
@@ -99,6 +103,9 @@ void RasterizerGLES3::begin_frame(double frame_step) {
 	GLES3::Utilities *utils = GLES3::Utilities::get_singleton();
 	utils->_capture_timestamps_begin();
 
+	// Disable OpenGL linear to sRGB conversion, because Godot will always do this conversion itself.
+	glDisable(GL_FRAMEBUFFER_SRGB);
```
Comment (clayjohn) [inline drivers/gles3/rasterizer_gles3.cpp:107]: I would prefer to do this in `RasterizerGLES3::RasterizerGLES3()` if its not going to change at runtime.

Comment (dsnopek) [reply drivers/gles3/rasterizer_gles3.cpp]: Thanks! I don't know how that didn't occur to me. :-) Moved there in latest push!

**Review by clayjohn — APPROVED** [review]
Looks great to me!

**Comment by decacis** [comment]
I can confirm this fixes #95313 I tested both on Quest native and with Quest Link.

| 4.3-rc3 | This PR |
|---------|--------|
| godot_4 3-rc3 | godot_4 3-rc3_95433 |

And it's supposed to look like this PR :)

**Review by devloglogan — APPROVED** [review]
Tested this out by making a few changes/comparisons in the meta composition layer sample, looks good to me!

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.
