### PR TITLE
Only allow absolute paths in XDG environment variables

### LINKED ISSUE #48370: Overriding file paths with `XDG_*_HOME` environment variables will break if the path is relative
**Godot version:** 3.3 (likely also applies to `master`)

**OS/device including version:** Fedora 33, GeForce GTX 1080 (NVIDIA 465.24.02)

**Issue description:**

Overriding file paths with `XDG_*_HOME` environment variables will break if the path is relative.

### Absolute paths (working)

```
~
❯ XDG_CONFIG_HOME="$PWD/stuff/config" XDG_DATA_HOME="$PWD/stuff/data" XDG_CACHE_HOME="$PWD/stuff/cache" godot
Godot Engine v3.3.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce GTX 1080/PCIe/SSE2
OpenGL ES Batching: ON
^C

~
❯ tree stuff
stuff
├── cache
│   └── godot
├── config
│   ├── godot
│   │   ├── editor_settings-3.tres
│   │   ├── feature_profiles
│   │   ├── projects
│   │   │   └── hugo-b29ad6b3636da9a2475883fd013a7425
│   │   ├── script_templates
│   │   │   ├── empty.gd
│   │   │   └── no_comments.gd
│   │   └── text_editor_themes
│   └── pulse
│       └── cookie
└── data
    └── godot
        └── templates
```

### Relative paths (broken)

```
~
❯ XDG_CONFIG_HOME="stuff/config" XDG_DATA_HOME="stuff/data" XDG_CACHE_HOME="stuff/cache" godot
Godot Engine v3.3.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce GTX 1080/PCIe/SSE2
OpenGL ES Batching: ON
 
ERROR: save: Cannot save file 'stuff/config/godot/editor_settings-3.tres'.
   At: scene/resources/resource_format_text.cpp:1475.
ERROR: save: Error saving editor settings to stuff/config/godot/editor_settings-3.tres
   At: editor/editor_settings.cpp:1114.
^C

~
❯ tree stuff
stuff
├── config
│   └── pulse
│       └── cookie
└── data
    └── godot
        ├── stuff
        │   └── cache
        │       └── godot
        │           └── stuff
        │               └── config
        │                   └── godot
        │                       ├── feature_profiles
        │                       ├── projects
        │                       │   └── hugo-b29ad6b3636da9a2475883fd013a7425
        │                       ├── script_templates
        │                       │   ├── empty.gd
        │                       │   └── no_comments.gd
        │                       └── text_editor_themes
        └── templates
```

This is quite low-priority as it's easy to work around using the `$PWD` environment variable, but we can still fix this by converting the relative paths to absolute paths internally.

**However**, the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) states:

> All paths set in these environment variables must be absolute. If an implementation encounters a relative path in any of these variables it should consider the path invalid and ignore it.

Therefore, it may be better to ignore relative paths (falling back to the default) and print a warning message when a relative path is encountered in the XDG environment variables.

This issue was confirmed by matthewcroughan on Discord.

**Steps to reproduce:**

Run the following command with `godot` binary placed somewhere in your `PATH` environment variable:

```
XDG_CONFIG_HOME="stuff/config" XDG_DATA_HOME="stuff/data" XDG_CACHE_HOME="stuff/cache" godot
```

**Minimal reproduction project:** N/A

### PR DESCRIPTION
**Pull request by Calinou**
The XDG Base Directory specification does not allow using relative paths (which broke things in Godot anyway). If a relative path is detected, it should be ignored.

This closes https://github.com/godotengine/godot/issues/48370.

### CODE REVIEW

File: platform/linuxbsd/os_linuxbsd.cpp [hunk 1]
```diff
@@ -164,7 +164,12 @@ bool OS_LinuxBSD::_check_internal_feature_support(const String &p_feature) {
 
 String OS_LinuxBSD::get_config_path() const {
 	if (has_environment("XDG_CONFIG_HOME")) {
-		return get_environment("XDG_CONFIG_HOME");
+		if (get_environment("XDG_CONFIG_HOME").is_absolute()) {
+			return get_environment("XDG_CONFIG_HOME");
+		} else {
+			WARN_PRINT_ONCE("`XDG_CONFIG_HOME` is a relative path. Ignoring its value and falling back to `$HOME/.config` or `.` per the XDG Base Directory specification.");
+			return has_environment("HOME") ? get_environment("HOME").plus_file(".config") : ".";
```
Comment (Calinou) [inline platform/linuxbsd/os_linuxbsd.cpp:171]: I'm repeating the logic below here (also in the other functions and classes), but I'm not sure how to avoid it. It might be very obvious, but I can't see how to do it…

**Comment by akien-mga** [comment]
```
platform/osx/os_osx.mm:193:42: error: no member named 'is_absolute' in 'String'
                if (get_environment("XDG_CONFIG_HOME").is_absolute()) {
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
platform/osx/os_osx.mm:209:40: error: no member named 'is_absolute' in 'String'
                if (get_environment("XDG_DATA_HOME").is_absolute()) {
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
platform/osx/os_osx.mm:223:41: error: no member named 'is_absolute' in 'String'
                if (get_environment("XDG_CACHE_HOME").is_absolute()) {
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
```

Should be `is_abs_path()` no?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

File: platform/linuxbsd/os_linuxbsd.cpp (hunk 1 above)
Comment (akien-mga) [reply platform/linuxbsd/os_linuxbsd.cpp:171]: I missed this, but here's how: #48922.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.
