### PR TITLE
Optimize AnimationMixer blend process

### LINKED ISSUE #92693: AnimationPlayer/AnimationTree high process large framedrops
### Tested versions
Confirmed by me:
- Large frame drops in any build past 4.2.x (4.3 (be56cab58c056c074d1e02cd0b38641204e39f41))
- FPS heavily inconsistent in 4.2.2/4.2.1

Confirmed by other people:
- Godot v4.3.dev5 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (Advanced Micro Devices, Inc.; 31.0.24027.1012) - Intel(R) Xeon(R) CPU E5-2637 v2 @ 3.50GHz (16 Threads) - Large frame drops
### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 (NVIDIA; 31.0.15.4629) - AMD Ryzen 5 1600 Six-Core Processor (12 Threads)

### Issue description

Upon the creation of many animation players + animation trees (in this case 1024) with animation indexes, but no actual keyframes the engine proceeds to drop frames or fps becomes incredibly unstable due to high process call ms being added (goes from 16ms to 25-30ms)

### Steps to reproduce

Create a new object, put give it an AnimationPlayer + AnimationTree (keep the animation running) and animate it, but remove the actual keyframe, and duplicate it 1024 times, fps becomes unstable or process ms doubles and causes consistent framedrops.

Disabling animation playback returns to stable 60fps.

### Minimal reproduction project (MRP)

[AnimationTimer.zip](https://github.com/user-attachments/files/15526017/AnimationTimer.zip)
This simply duplicates a pre-made character 1024 times to sit in a 3D scene, with an animation with 0 keyframes running and performance begins to hurt in master branch.

Disabling animation playback returns to stable 60fps.

### PR DESCRIPTION
**Pull request by Nazarwadim**
This PR is created to optimize the AnimaionMixer `_process_animation`. 
```c++
void AnimationMixer::_process_animation(double p_delta, bool p_update_only) {
	_blend_init();
	if (_blend_pre_process(p_delta, track_count, track_map)) {
		_blend_capture(p_delta);
		_blend_calc_total_weight();             
		_blend_process(p_delta, p_update_only);
		_blend_apply();
		_blend_post_process();
		emit_signal(SNAME("mixer_applied"));
	};
	clear_animation_instances();
}
```

# Benchmarking methods:

I made some benchmarks of how long each of these methods takes for one 3D model, using animation_tree.

Some explanations to understand the results.
Units of measurement: usec.
is_process = _blend_pre_process
weight = _blend_calc_total_weight    

Master:

You can see here that the `_blend_process`, `_blend_pre_process` and `_blend_calc_total_weight` methods take the most time.

I will show the results that are in this PR.

You can see that `blend_process` has improved by 30%, blend `calc_total_weight` has improved by 15% and `_blend_pre_process` has improved by 50%.

# Real project benchmarks:

Master:
Project FPS: 56 (17.85 mspf)
Project FPS: 56 (17.85 mspf)
Project FPS: 56 (17.85 mspf)
Project FPS: 56 (17.85 mspf)
Project FPS: 55 (18.18 mspf)
Project FPS: 55 (18.18 mspf)

Current PR:
Project FPS: 68 (14.70 mspf)
Project FPS: 69 (14.49 mspf)
Project FPS: 66 (15.15 mspf)
Project FPS: 66 (15.15 mspf)
Project FPS: 68 (14.70 mspf)

Here you can see a pretty good + 22%. Note that #92554 also improves animation performance, which with this PR adds 40% to performance.

# How to test:
Here #92554 in the benchmark section is Animation_test.zip project. After opening, fps will be output to the console.

# What was done:

**Animation:**

- For enums, the size was reduced from 4 to 1 byte.
- Added the get_tracks method.

**AnimationTree:**

- I made track_map a pointer in order not to copy maps. 

**AnimationMixer:**

- The first is to use getptr instead of has + operator[].
- The second is to use `int count = a->get_track_count();` In order to store in a register the number of iterations.
- Used the method already created in animation.h to take the array. `const Vector<Animation::Track *> tracks = a->get_tracks();`
- In the method `post_process_key_value` I cache whether there is GDVIRTUAL_CALL. That is, there will be only 1 check per _blend_process call.

Probably closes: #92693

### CODE REVIEW

File: scene/resources/animation.h [hunk 1]
```diff
@@ -45,7 +45,7 @@ class Animation : public Resource {
 
 	static inline String PARAMETERS_BASE_PATH = "parameters/";
 
-	enum TrackType {
+	enum TrackType : uint8_t {
```
Comment (AThousandShips) [inline scene/resources/animation.h:48]: I'm not sure how much this improves, the original data type would have been `int` but the alignment and other factors prevent significant optimization generally

Comment (Nazarwadim) [reply scene/resources/animation.h:48]: This was done in order to reduce the size of the `Track` from 40 to 32 bytes. You can check using sizeof.

File: scene/animation/animation_mixer.cpp [hunk 2]
```diff
@@ -1073,15 +1076,18 @@ void AnimationMixer::_blend_calc_total_weight() {
 		real_t weight = ai.playback_info.weight;
 		Vector<real_t> track_weights = ai.playback_info.track_weights;
 		Vector<int> processed_indices;
```
Comment (fire) [inline scene/animation/animation_mixer.cpp:1078]: I suggest using LocalVector instead of caching the write pointer.

Comment (Nazarwadim) [reply scene/animation/animation_mixer.cpp:1078]: See this PR https://github.com/godotengine/godot/pull/92257

**Comment by Saul2022** [comment]
I would say that by itself it won’t be enough but with the pr you mentioned it might close it as it reduces it cost a lot more(40% as you stated when combining it )

Either way this is great job and hopefully it gets merged quick in 4.4  along with your other great optimizations pr’s.

**Comment by JekSun97** [comment]
> Either way this is great job and hopefully it gets merged quick in 4.4 along with your other great optimizations pr’s.

There are no compatibility problems or any major innovations here, this is just an optimization of what already exists.
So I think this would work well for 4.3 as well

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` https://github.com/godotengine/godot/commit/292e50e17e3f6e2509d3178a00204f964a907460), it works as expected. Great work :slightly_smiling_face: 

## Benchmark

Using an optimized editor build (`optimize=speed lto=full`) for all tests. Project is kept at its default window size and the camera isn't moved after startup. The editor is **not** running in the background.

<details open>

<summary>PC specifications</summary>

- **CPU:** Intel Core i9-13900K
- **GPU:** NVIDIA GeForce RTX 4090
- **RAM:** 64 GB (2×32 GB DDR5-5800 C30)
- **SSD:** Solidigm P44 Pro 2 TB
- **OS:** Linux (Fedora 39)
</details>

Using [Animation_test.zip](https://github.com/godotengine/godot/files/15501000/Animation_test.zip):

`master` | This PR | https://github.com/godotengine/godot/pull/92554 | This PR + https://github.com/godotengine/godot/pull/92554 [^1]
-|-|-|-
90 FPS (11.11 mspf) | 116 FPS (8.62 mspf) | 113 FPS (8.84 mspf) | 123 FPS (8.13 mspf)

[^1]: This required trivial code changes to get it to compile, since there's a small merge conflict when rebasing https://github.com/godotengine/godot/pull/92554 on top of this PR. Visual results still looked correct after doing so.

**Review by TokageItLab — COMMENTED** [review]
I recall our earlier discussion that we should use GDREGISTER_VIRTUAL_CLASS for some Animation related classes.

File: scene/animation/animation_mixer.cpp [hunk 3]
```diff
@@ -965,6 +957,17 @@ Variant AnimationMixer::_post_process_key_value(const Ref<Animation> &p_anim, in
...
+	if (is_GDVIRTUAL_CALL_post_process_key_value) {
+		Variant res;
+		if (GDVIRTUAL_CALL(_post_process_key_value, p_anim, p_track, p_value, p_object_id, p_object_sub_idx, res)) {
+			return res;
+		}
+		is_GDVIRTUAL_CALL_post_process_key_value = false;
+	}
+	return _post_process_key_value(p_anim, p_track, p_value, p_object_id, p_object_sub_idx);
+}
+
```
Comment (TokageItLab) [inline scene/animation/animation_mixer.cpp:970]: Maybe this change would not be necessary if AnimationMixer were registered as GDREGISTER_VIRTUAL_CLASS instead of GDREGISTER_ABSTRACT_CLASS? cc @reduz
This is also applicable to the AnimationNode.

File: scene/animation/animation_mixer.cpp [hunk 4]
```diff
@@ -1073,15 +1076,18 @@ void AnimationMixer::_blend_calc_total_weight() {
 		real_t weight = ai.playback_info.weight;
 		Vector<real_t> track_weights = ai.playback_info.track_weights;
 		Vector<int> processed_indices;
-		for (int i = 0; i < a->get_track_count(); i++) {
-			if (!a->track_is_enabled(i)) {
+		const Vector<Animation::Track *> tracks = a->get_tracks();
```
Comment (TokageItLab) [inline scene/animation/animation_mixer.cpp:1079]:
```suggestion
		const Vector<Animation::Track *> tracks = a->get_tracks();
```

I remember we always saying that we should use `LocalVector` whenever possible. There are several other places in the animation code where `Vector` is used besides here, but as long as it doesn't use `has()`, `sort()`, etc., I think it can be migrated to `LocalVector`.

Comment (Nazarwadim) [reply scene/animation/animation_mixer.cpp:1080]: Using `LocalVector` can result in many copies. Also, if it is changed, it will be necessary to make many changes in the already existing code. For example, with `int` in for loop, replace it with `uint32_t` so that there are no warnings from the compiler.
In order to remove the performance overhead, I used `ptr`.

File: scene/animation/animation_mixer.cpp (hunk 3 above)
Comment (Nazarwadim) [reply scene/animation/animation_mixer.cpp:970]: It is still necessary. I don't know what is happening in the GDVIRTUAL_CALL method, but I know that it is slow no matter how this class was registered. And so this variable caches the return result of this method if it returned false.

Comment (Nazarwadim) [reply scene/animation/animation_mixer.cpp:970]: Also, for some reason, the performance decreased when the registration was changed to GDREGISTER_VIRTUAL_CLASS

**Comment by WOLFxxxxxx** [comment]
GLEcxYwW4AA8ufD (1)
GLEcGh1XkAA2-YX (1)


Animation does not support multi-core

**Comment by TokageItLab** [comment]
@WOLFxxxxxx It has nothing to do with this PR you are talking about. This PR is an optimization for several allocations in the blending process and does not address multithreading. That will have to be done in another PR. Please confine the discussion here to the topic of the implementation that this PR does.

**Comment by JekSun97** [comment]
I think it's time to merge it with 4.4, no conflicts related to this PR have been found

**Review by TokageItLab — APPROVED** [review]
Looking at the code, there should be no change in the essential behavior. I guess there are places where we can be optimized more, but I think this PR is fine for now.

**Comment by akien-mga** [comment]
Thanks!
