### PR TITLE
Fix Illegible text in audio bus editor

### LINKED ISSUE #50583: Illegible texts in audio bus editor when using a light theme
### Godot version

3.3.2, 3.x(9636deac55), 4.0.dev (b76dfde329)

### System information

macOS 11.4

### Issue description

When using light themes, name of the Master audio bus is hard to read. I think it's even using the same color as the background when in focus:

name

In 3.x, no matter which theme you use, the volume preview tooltip shown when dragging the volume handle is also using a similar color as the background:

tooltip

### Steps to reproduce

For the master bus name, change editor theme to Light.

Drag the volume handle in audio bus editor to see the tooltip, note that it's different from the hover tooltip.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by SirQuartz**
This pull request fixes an issue with the audio bus editor where the text would be illegible regardless of the theme being used.

Resolves: #50583

### CODE REVIEW

File: scene/resources/default_theme/default_theme.cpp [hunk 1]
```diff
@@ -143,7 +143,7 @@ void fill_default_theme(Ref<Theme> &theme, const Ref<Font> &default_font, const
 
 	// Font Colors
 
-	Color control_font_color = Color(0.88, 0.88, 0.88);
+	Color control_font_color =  Color(0.55, 0.55, 0.55);
```
Comment (LightningAA) [inline scene/resources/default_theme/default_theme.cpp:146]:
```suggestion
	Color control_font_color = Color(0.55, 0.55, 0.55);
```

**Comment by pycbouh** [comment]
I'm not sure why you would need to change anything in the default theme. You just need to change to related color in the editor theme based the dark theme flag. If there is no color constant for some reason, it needs to be defined.

File: scene/resources/default_theme/default_theme.cpp [hunk 2]
```diff
@@ -143,7 +143,7 @@ void fill_default_theme(Ref<Theme> &theme, const Ref<Font> &default_font, const
 
 	// Font Colors
 
-	Color control_font_color = Color(0.88, 0.88, 0.88);
+	Color control_font_color = Color(0.55, 0.55, 0.55);
```
Comment (LightningAA) [inline scene/resources/default_theme/default_theme.cpp:146]: Not very familiar with the code here, but won't this affect all/a lot of text, not just the tooltips in the audio bus editor?

**Comment by SirQuartz** [comment]
> I'm not sure why you would need to change anything in the default theme. You just need to change the related color in the editor theme based on the dark theme flag. If there is no color constant specific to the bus name for some reason, it needs to be defined.
> 
> This also isn't the greatest color in general, midtones are still not very readable, on either theme preset. And the empty line is unnecessary.

Yeah, the problem is that the audio bus just uses a hardcoded font color irrespective of the current theme.

on line 413 we have: `theme->set_color("font_uneditable_color", "LineEdit", Color(control_font_color.r, control_font_color.g, control_font_color.b, 0.5f));`

The master audio bus uses `font_unedtible_color)` to grey out the name of it, but it's irrespective of the current theme being used. So it looks ok on the default theme, but on lighter themes, it becomes practically unreadable.

**Comment by pycbouh** [comment]
@SirQuartz That just means that there are definitions in the editor theme missing. Those definitions are only created in the `editor_themes.cpp` file. The `default_theme.cpp` files should not be touched to fix an issue with the editor theme, because it does not contain the editor theme. It contains the default engine theme, the one you see in the projects.

If you think that every `LineEdit` in the editor, provided they are set to not be `editable`, is affected by this you need to create or adjust definitions for `font_uneditable_color` in the editor theme definitions. Somewhere around here:

https://github.com/godotengine/godot/blob/e3a86d54c3be39982384a5e89c151ecfefc62b00/editor/editor_themes.cpp#L1022-L1032

 There is likely already a good color available that respects the color scheme that you can use here.

Alternatively we can consider swapping the `LineEdit` for a `Label` when it's not editable and using some other color.

**Comment by SirQuartz** [comment]
Ok, I've fixed everything, and this should be a much cleaner implementation.

default_theme (2)
light_theme (2)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
It seems like `font_uneditable_color` doesn't exist in `3.x` so a different fix would be needed there.

**Comment by SirQuartz** [comment]
> It seems like `font_uneditable_color` doesn't exist in `3.x` so a different fix would be needed there.

I see, I look into a solution for 3.x as well.

**Comment by SirQuartz** [comment]
> Thanks!

@akien-mga  See: #50646
