### PR TITLE
Ensure excluded GDExtension files are not included in `extension_list.cfg`

### LINKED ISSUE #97207: Export of GDExtension files that were excluded still appears in extension_list.cfg resulting in errors during startup
### Tested versions

Problem found on v4.3.stable.official [77dcf97d8]
This problem appears to have existed in earlier version as well

### System information

Godot v4.3.stable - Ubuntu 24.04.1 LTS 24.04 - Wayland - Vulkan (Forward+) - integrated Intel(R) UHD Graphics 770 (ADL-S GT1) - 12th Gen Intel(R) Core(TM) i7-12700K (20 Threads)

### Issue description

When an export is performed with a GDExtension that extension is listed in the extension_list.cfg file in res://.godot

Even if the files that go into that extension are excluded from export (such as would be done for the Git plugin (which is editor only)) this file causes the exported binary to look for that extension.  It cannot be found and an error is output.

This has been reported against the godot-git-plugin, but the real issue is the way an export ignores the exclusion filters for the contents of the extension_list.cfg

### Steps to reproduce

1. Create a project that includes a GD Extension that is for the editor only (such as the official Git plugin), 
2. Export that project and exclude the plugin folder by doing Resources->Export Mode = "Export all resources in the project except resources checked below", and clicking "addons/godot-git-plugin" folder
3. Run the exported project and observe the error: "ERROR: Error loading GDExtension configuration file: res://addons/godot-git-plugin/git_plugin.gdextension"

### Minimal reproduction project (MRP)

There are 2 cases 
1. Where the only GDExtension is the add-on that is excluded
2. Where there is a GDExtension in addition to the add-on that is excluded.
[one-extension.zip](https://github.com/user-attachments/files/17067456/one-extension.zip)
[gdextension_example_cpp.zip](https://github.com/user-attachments/files/17067478/gdextension_example_cpp.zip)

### PR DESCRIPTION
**Pull request by markeel**
The implemented solution to the problem of the error message appearing when an excluded GDExtension in an export of a project, is to filter the lines in the extension_list.cfg file to only include those that are in the paths actually included for export.  If there are no entries remaining, don't write the file at all.

* *Bugsquad edit, fixes: #97207*

### CODE REVIEW

**Comment by markeel** [comment]
I implemented what seems like a straightforward way to address this error message, by filtering out the files in the extension_list.cfg file during the process of exporting.  This seems pretty low risk, but I welcome more eyes on the change.  I tested with both a project with only one extension (which was excluded), and one with two extensions (one of which was excluded) per the minimal reproduction projects supplied in the issue.

File: editor/export/editor_export_platform.cpp [hunk 1]
```diff
@@ -1407,6 +1407,12 @@ Error EditorExportPlatform::export_project_files(const Ref<EditorExportPreset> &
 	Vector<String> forced_export = get_forced_export_files();
 	for (int i = 0; i < forced_export.size(); i++) {
 		Vector<uint8_t> array = FileAccess::get_file_as_bytes(forced_export[i]);
+		if (GDExtension::get_extension_list_config_file() == forced_export[i]) {
+			array = _filter_extension_list_config_file(forced_export[i], paths);
+			if (array.size() == 0) {
+				continue;
+			}
+		}
```
Comment (dsnopek) [inline editor/export/editor_export_platform.cpp:1415]: This ends up reading the `extension_list.cfg` twice. Maybe this could be refactored like:

```suggestion
		Vector<uint8_t> array;
		if (GDExtension::get_extension_list_config_file() == forced_export[i]) {
			array = _filter_extension_list_config_file(forced_export[i], paths);
			if (array.size() == 0) {
				continue;
			}
		} else {
			array = FileAccess::get_file_as_bytes(forced_export[i]);
		}
```

**Review by dsnopek — COMMENTED** [review]
Thanks!

I didn't test this, but looking at the code, this seems like a good approach overall :-)

I only have the one note below...

File: editor/export/editor_export_platform.cpp (hunk 1 above)
Comment (markeel) [reply editor/export/editor_export_platform.cpp:1415]: Yes, that seems like it would be more efficient in the case where the extension list config file is being updated.  

I'm not sure there is a performance difference between constructing the array from an other array at the original line 1409, and doing an empty initialization and assignment at the new 1409 and 1416.  Almost all files being copied are NOT the extension list config file, so line 1409 and then 1416 in your revised version (doing an assignment into the array after previous initialization) is the code executed for almost every file.

I think when I wrote it originally I was going for the least impact to existing code, and only having extra code being executed for the one extension list config file, and hoping that would make the merge easier.

If you or other reviewers think it is worth updating and redoing the pull request, I'll work on it later this week.

Comment (markeel) [reply editor/export/editor_export_platform.cpp]: Took a while for me to get back to it, but I implemented the requested change and fixed a merge problem.  Hopefully this will allow it to make it into 4.4

**Review by dsnopek — APPROVED** [review]
Thanks! The latest changes look good to me. I haven't re-tested, but I don't think anything has changed functionally since the last time I tested

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉

**Comment by KoBeWi** [comment]
Does not work for me. I excluded all extension's files with EditorExportPlugin and it's still included in the extension list and prints errors on launch.
Looks like this only covers the case where files are excluded via the Export dialog.

**Comment by markeel** [comment]
> Does not work for me. I excluded all extension's files with EditorExportPlugin and it's still included in the extension list and prints errors on launch. Looks like this only covers the case where files are excluded via the Export dialog.

I definitely didn't test with EditorExportPlugin, only the traditional Export dialog, so there must be something else when you are using that class.  I didn't even know about that class, so that's a bit of new learning for me.  I'm curious though, so I'll see if I can see what that class does differently.  Do you have an example EditorExportPlugin I could test with?

**Comment by KoBeWi** [comment]
Check this comment: https://github.com/godotengine/godot-git-plugin/issues/77#issuecomment-2212343975

**Comment by markeel** [comment]
I looked at this and see that the list of paths to process is not updated if a EditorExportPlugin uses the skip() method to drop it from the export list.  I'll write a separate issue and see if there is a way to generalize this.  

If you are are using the EditorExportPlugin just to exclude the git plugin, the easier way is to just use the export resource options and select the directories without using a plugin.

Screenshot from 2024-11-25 09-36-17

**Comment by markeel** [comment]
I created the following issue: https://github.com/godotengine/godot/issues/99698
I have a relatively simple update to the original change in #97207 that should address this as well.

**Comment by markeel** [comment]
Well, after doing some additional testing on my "fix" I realized that there were other changes in 4.4 that make supporting an editor export plugin excluding a GDExtensionPlugin like the Git plugin pointless.  I closed issue: 99698

The root problem is that there are two export plugins competing for control of the same files, and there is no guarantee of the order they will run in, and the GDExtensionPlugin has now implemented additional warnings without the knowledge of any other editor export plugins running.

Oh well.

**Comment by akien-mga** [comment]
I haven't looked into the details, but I just want to make sure we're not adding workarounds to solve a symptom instead of handling the root problem properly.

The Git plugin is obviously a type of extension that nobody would want included in exports. So the extension system needs to have support for extension authors to register their extensions as editor only / no export, and this should be used for the Git plugin.

End users shouldn't have to manually exclude its files from the export presets.

**Comment by markeel** [comment]
Well that is the current strategy to prevent the files for an addon that is only for the editor out of the package when they export their game.  That is independent of whether it had an extension or not.  In the case where there was an extension there was an extra twist to keep out just the line for that unwanted addon from extension_list.cfg.

Are you suggesting to add an option into plugin.cfg that would describe this plugin as being for the editor only?  

That seems like it would make all the user's lives considerably easier.

**Comment by dsnopek** [comment]
> The Git plugin is obviously a type of extension that nobody would want included in exports. So the extension system needs to have support for extension authors to register their extensions as editor only / no export, and this should be used for the Git plugin.

I think adding some sort of "no export" key to `.gdextension` files could make sense! However, there is some overlap between that and the ideas about global extensions that have been going around. Once we support global extensions, the Git plugin would almost certainly become one. So, I'd want to be careful not to add a key in such a way that would cause conflicts or confusion later.

**Comment by markeel** [comment]
> > The Git plugin is obviously a type of extension that nobody would want included in exports. So the extension system needs to have support for extension authors to register their extensions as editor only / no export, and this should be used for the Git plugin.
> 
> I think adding some sort of "no export" key to `.gdextension` files could make sense! However, there is some overlap between that and the ideas about global extensions that have been going around. Once we support global extensions, the Git plugin would almost certainly become one. So, I'd want to be careful not to add a key in such a way that would cause conflicts or confusion later.

Sounds like this discussion should be tied into whatever proposal is tracking this potential feature.  In the meantime people will just have to manually exclude this type of addon.  Is there a link to the global extension proposal?

**Comment by dsnopek** [comment]
> Is there a link to the global extension proposal?

Here's [the proposal](https://github.com/godotengine/godot-proposals/issues/831) but I don't think it captures all of the discussion that has gone on around this
