### PR TITLE
[3.x] Fix zero scale in particle shader

### LINKED ISSUE #80863: Particles aren't emiting when scale_curve begins from zero
### Godot version

v3.6.beta3.official [21ab700f2]

### System information

Linux Ubuntu 22.04, GeForce 1060

### Issue description

`Particles` stops emitting when the first point of `Scale Curve` in `Process Material`  is zero, like with "Linear preset".
Another fact is that setting `flag_disable_z` or `flag_disable_z` cancels this effect (emitting works).

The same setup in Godot_v3.5.2-stable works without problems.

### Steps to reproduce

Just any `Particles` set up as described in Issue description

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by lawnjelly**
Fixes the lower bounding of scale when given zero input.

The previous bug was due to `sign` returning 0 with 0.0 input, rather than 1.

Fixes #80863

## Notes
* Regression introduced in #53852
* There are also proposals to introduce special `abs_sign` function to deal with this (https://github.com/godotengine/godot-proposals/issues/6854) but I've just fixed in place for now
* There might be some slightly more efficient way of doing this to avoid the branch

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: scene/resources/particles_material.cpp [hunk 1]
```diff
@@ -659,8 +659,15 @@ void ParticlesMaterial::_update_shader() {
 	}
 	//scale by scale
 	code += "	float base_scale = tex_scale * mix(scale, 1.0, scale_random * scale_rand);\n";
+
 	// Prevent zero scale (which can cause rendering issues).
-	code += "	base_scale = sign(base_scale) * max(abs(base_scale), 0.000001);\n";
+	code += "	if (base_scale >= 0.0) {\n";
+	code += "		base_scale = max (base_scale, 0.000001);\n";
+	code += "	}\n";
+	code += "	else {\n";
```
Comment (akien-mga) [inline scene/resources/particles_material.cpp:667]:
```suggestion
	code += "	} else {\n";
```
Following the Godot style guide all the way into shader land.

File: scene/resources/particles_material.cpp [hunk 2]
```diff
@@ -659,8 +659,15 @@ void ParticlesMaterial::_update_shader() {
 	}
 	//scale by scale
 	code += "	float base_scale = tex_scale * mix(scale, 1.0, scale_random * scale_rand);\n";
+
 	// Prevent zero scale (which can cause rendering issues).
-	code += "	base_scale = sign(base_scale) * max(abs(base_scale), 0.000001);\n";
+	code += "	if (base_scale >= 0.0) {\n";
+	code += "		base_scale = max (base_scale, 0.000001);\n";
```
Comment (akien-mga) [inline scene/resources/particles_material.cpp:665]:
```suggestion
	code += "		base_scale = max(base_scale, 0.000001);\n";
```

File: scene/resources/particles_material.cpp [hunk 3]
```diff
@@ -659,8 +659,15 @@ void ParticlesMaterial::_update_shader() {
...
+	code += "	}\n";
+	code += "	else {\n";
+	code += "		base_scale = min (base_scale, -0.000001);\n";
```
Comment (akien-mga) [inline scene/resources/particles_material.cpp:668]:
```suggestion
	code += "		base_scale = min(base_scale, -0.000001);\n";
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
