### PR TITLE
Fix loss of gdextension on editor startup

### LINKED ISSUE #97735: Extension singleton not found when running project after exporting with another Godot instance
### Tested versions

Reproducible in 4.4 dev3
Might be a regression, but I didn't test earlier versions.

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

I'm exporting project from command line. When I do it while editor is running, the extension gets broken and it won't work when running the project from the editor. In the extension's folder there are some changes with `~` files.

### Steps to reproduce

1. Open the MPR
2. Run it; should be fine
3. Open a terminal in the project's directory (don't close the editor)
4. Export the project with `godot --export-debug "Windows Desktop" --headless`
5. You will see errors in the console about "Failed to open", "Error copying library", "Can't open GDExtension dynamic library" etc.
6. Go back to the editor and run the project
7. Godot complains that singleton does not exist

### Minimal reproduction project (MRP)

[bugstension.zip](https://github.com/user-attachments/files/17231072/bugstension.zip)

### LINKED ISSUE #97900: extension_list.cfg in .godot folder is deleted when opening a project
### Tested versions

- Reproducible in: v4.4.dev3.official [f4af8201b]
- Not reproducible in: v4.4.dev2

### System information

Godot v4.4.dev3 - macOS 14.5.0 - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M1 (Apple7) - Apple M1 (8 threads)

### Issue description

When opening a project that has a GDExtension addon, the extension_list.cfg file in the .godot folder is deleted.

If running the project, it will throw errors if the addon is referenced in a script. The deletion of the extension_list.cfg file only happens every other time the project is opened. If the project is closed and opened again, the extension_list.cfg file is generated, and the addon works as expected. If the project is closed, and then opened again, the extension_list.cfg file is once again deleted. This can be consistently reproduced, where every _even session recreates the config file_ and _every odd session deletes it_. 

When opening the project in a session that deletes the extension_list.cfg file, it also throws the following errors and warning when the editor is opened:

Skjermbilde 2024-10-06 kl  20 40 50

### Steps to reproduce

1. Create a new project in 4.4-dev3
2. Open the AssetLib
3. Download and install a GDExtension addon (in this case I tried with Debug Draw 3D 4.1.4+)
4. Save the project and close Godot
5. Open the project again
6. Repeat closing and opening the project and observe the extension_list.cfg be deleted and generated

### Minimal reproduction project (MRP)

[extension-list-config-file.zip](https://github.com/user-attachments/files/17270668/extension-list-config-file.zip)

### LINKED ISSUE #97962: Custom GDExtensiom `MainLoop` does not work if .godot is already generated
### Tested versions

4.4-dev3 

### System information

Godot v4.4.dev3 - Windows 10.0.19045 - Single-window, 1 monitor - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 4050 Laptop GPU (NVIDIA; 32.0.15.6070) - 13th Gen Intel(R) Core(TM) i5-13500HX (20 threads)

### Issue description

After the .godot folder is already generated, exiting the editor and entering it again and then running the game does not allow the MainLoop to be detected

### Steps to reproduce

1. Ensure .godot is not generated
2. Run the project, it works fine
image
3. Exit the editor and reopen
4. Notice no errors about GDExtension are printed in console
5. Run the game
image
6. Notice the error

### Minimal reproduction project (MRP)

[New Compressed (zipped) Folder.zip](https://github.com/user-attachments/files/17286971/New.Compressed.zipped.Folder.zip)

### LINKED ISSUE #98056: Android gdextension fails to load
### Tested versions

Reproduced in 4.3.dev [e7c39efdb15eaaeb133ed8d0ff0ba0891f8ca676]

### System information

Linux Pop OS 22.04

### Issue description

NOTE: This PR fixes it: https://github.com/godotengine/godot/pull/98041

Android builds fail to load gdextensions.  At the very least, rust gdextensions.  I have not tested other languages.  Fortunately it appears a PR has been put in that fixes this: https://github.com/godotengine/godot/pull/98041

I tested this PR on my fork and can confirm that this indeed fixes the issue.  I noticed that it mentioned fixing ".godot" and "editor" related issues, but I figured I would test it for my Android issue since the description sounded similar and it fixed it! :)  I'm simply adding this so it is tracked and completed by the PR

### Steps to reproduce

1. Compile a godot-rust gdextension: https://github.com/godot-rust/gdext
2. Export an apk
3. Install on android
4. See that the gdextension doesn't load

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Hilderin**
- Fixes #97900
- Fixes #97962
- Fixes #98056
- Fixes #97735

The GDExtension files were not processed in `EditorFileSystem::_first_scan_process_scripts` following optimization in #95678.

Thanks to @NetroScript to pinpoint the problem and find the solution. This PR is based on it's suggested modifications. That's why I added him as Coauthor.

I think your approach to use `ResourceLoader::get_recognized_extensions_for_type` is the right one. It's sounds like a bug to me that the method returns `.res` and `.tres` for GDExtension. I'm not an expert of the GDExtensions but I'm pretty sure `.res` and `.tres` are not supported for GDExtensions. If you check into `GDExtensionLibraryLoader::parse_gdextension_file`, it only supports a ConfigFile format and not a resource file. It does not seems easy to modify `ResourceLoader::get_recognized_extensions_for_type` to not return `.res` and `.tres` for GDExtension and I'm worry about side effects so I think that excluding `.res` and `.tres` extensions in `_first_scan_filesystem` seems the right way to me.

Edited: Adding #97962 in the fixed issue list.
Edited: Adding #98056 in the fixed issue list.

### CODE REVIEW

**Comment by FireCatMagic** [comment]
This should also fix https://github.com/godotengine/godot/issues/97962

**Comment by NetroScript** [comment]
Thanks for the fast PR. When I checked it out I also found no way to exclude `res` and `tres`. As all resource loaders get iterated to find extensions the `ResourceFormatLoaderBinary` for example also is iterated, [which returns true for all handled types ](https://github.com/godotengine/godot/blob/4c4e67334412f73c9deba5e5d29afa8651418af2/core/io/resource_format_binary.cpp#L1294)(there in theory it would be possible to add an exclusion from my uneducated observations), which causes `res` to be added.

**Comment by Hilderin** [comment]
Exactly! We will see what reviewers think about that.

**Comment by TCROC** [comment]
This also fixes gdextensions not loading on android: https://github.com/godotengine/godot/issues/98056

**Comment by fire** [comment]
I think we should rename and attempt to modify ResourceLoader::get_recognized_extensions_for_type to not return .res and .tres for GDExtension

Or at least see that its too difficult

File: editor/editor_file_system.cpp [hunk 1]
```diff
@@ -293,24 +301,29 @@ void EditorFileSystem::_first_scan_process_scripts(const ScannedDirectory *p_sca
...
+				}
+			}
+		}
 
-			if (!script_class_name.is_empty()) {
-				p_existing_class_names.insert(script_class_name);
+		// Check for GDExtensions.
+		if (p_gdextension_extensions.find(ext)) {
+			String path = p_scan_dir->full_path.path_join(scan_file);
+			String type = ResourceLoader::get_resource_type(path);
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:323]:
```suggestion
			const String path = p_scan_dir->full_path.path_join(scan_file);
			const String type = ResourceLoader::get_resource_type(path);
```

**Review by KoBeWi — APPROVED** [review]
The code seems fine.
This fixes a few GDExtension regressions, so it would be nice to get it merged soon.

> It's sounds like a bug to me that the method returns .res and .tres for GDExtension.

It's *not exactly* a bug. ResourceFormatLoaderText/Binary handle any type of Resource (because you can save/load everything as .res or .tres), and that's where these extensions come from.

**Comment by dsnopek** [comment]
> It's not exactly a bug. ResourceFormatLoaderText/Binary handle any type of Resource

I haven't tested it, but I don't think re-saving a `.gdextension` file as `.tres`/`.res` would result in a working GDExtension, because the `GDExtension` resource class doesn't keep all its data in registered properties. If there's a way to prevent re-saving as a `.tres`/`.res` we should probably do that - although, that's not in scope for this PR.

**Comment by KoBeWi** [comment]
It's similar issue to #34080

**Review by dsnopek — APPROVED** [review]
This fixes issue https://github.com/godotengine/godot/issues/97900 in my testing!

Skimming the code, it looks good to me, but I don't know `EditorFileSystem` as well as @Hilderin or @KoBeWi - I trust their judgement :-)

**Review by m4gr3d — APPROVED** [review]

File: editor/editor_file_system.cpp (hunk 1 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp]: Done and added `const` to a couple other Strings.

**Comment by Hilderin** [comment]
As suggested by @fire, I modified code to prevent `ResourceLoader::get_recognized_extensions_for_type` returning `res` and `tres` extensions for `GDExtension`. I little if added in `ResourceFormatLoaderBinary::get_recognized_extensions_for_type` and `ResourceFormatLoaderText::get_recognized_extensions_for_type` did the trick.

**Comment by Repiteo** [comment]
Thanks!
