### PR TITLE
C#: Deprecate accessor methods and generate correct int and float types

### LINKED ISSUE #28393: randi() of RandomGenerator returns signed int instead of unsigned int
**Godot version:**

? - 3.1

**Issue description:**

Native randi() and GD.Randi() in C# returns uint. But RandomGenerator.Randi() returns int.
Also wrong: Docs and https://github.com/godotengine/godot/blob/master/doc/classes/RandomNumberGenerator.xml#L42

### PR DESCRIPTION
**Pull request by neikeq**
- Methods that act as accessors for properties in the same class (like `GetPosition` and `SetPosition` are for `Position`) are now marked as obsolete. They will be made private in the future.
- The C# bindings generator correct integer and floating point types (no more int and float everything). Closes #28393

### CODE REVIEW

File: core/object.h [hunk 1]
```diff
@@ -140,6 +140,21 @@ struct PropertyInfo {
...
+		METADATA_INT_IS_I16,
+		METADATA_INT_IS_I32,
+		METADATA_INT_IS_I64,
+		METADATA_INT_IS_UI8,
+		METADATA_INT_IS_UI16,
+		METADATA_INT_IS_UI32,
+		METADATA_INT_IS_UI64,
+		METADATA_REAL_IS_FLOAT,
+		METADATA_REAL_IS_DOUBLE
+	};
```
Comment (neikeq) [inline core/object.h]: @reduz Are you fine with this?

**Comment by neikeq** [comment]
@karroffel The int/float commit may be of use for GDNative.

File: core/object.h (hunk 1 above)
Comment (reduz) [reply core/object.h]: Nope, please do the following:

* use a property usage for signed
* use another property usage for 64 bits

There is no point at all in supporting 8 and 16 bits. I prefer this rather than adding yet another field to property info (which is used everywhere), which is just bloat for something so core, and confusing/annoying to anyone reading the code.

**Review by reduz — CHANGES_REQUESTED** [review]

File: core/object.h (hunk 1 above)
Comment (neikeq) [reply core/object.h]: I can see the point in avoiding the bloat of adding a field to a struct that is used everywhere. What if we surround it with `#ifdef DEBUG_METHODS_ENABLED`?
I can't take the second statement seriously. This code couldn't be simpler. I can't imagine anyone getting confused by it, let alone annoyed.

Comment (reduz) [reply core/object.h]: I'm very serious about it, a PR like this won't go through. My first priority will always be to keep bloat out of core and this is an extremely core class. If for you this inconsistency is unacceptable, I prefer to remove the 4 occurrences of the < 32 bits arguments so there are no longer any functions using them.

**Review by reduz — CHANGES_REQUESTED** [review]

File: core/object.h (hunk 1 above)
Comment (neikeq) [reply core/object.h]: Does that mean surrounding `#ifdef DEBUG_METHODS_ENABLED` is not an option? If not, I'm thinking of an alternative to having the field in `PropertyInfo`.

Comment (reduz) [reply core/object.h]: No, please let's not add hack to that. Definitely go the property usage way and let's get rid of 8/16 bit access if you need them.

Comment (reduz) [reply core/object.h]: Even modern processors don't really support this type of access, it's a thing of the past.

**Comment by neikeq** [comment]
Tried it in a different way as a last attempt. Let me know if you don't like this one either.

**Comment by reduz** [comment]
I really still think you are over complicating it. That will make it more difficult for those writing binders to understand what it is, and it will add strings to everything that has bindings (I know they are stringnames so it's just a pointer, but still.). The doc generators or code completion may also get confused (or need to take this into consideration) with this given they also use it.

I keep insisting on the approach I proposed and drop 8 and 16 bits. I can remove them from the API if you want, as they are useless.

**Comment by neikeq** [comment]
> That will make it more difficult for those writing binders to understand what it is

This change doesn't affect any existing binders. If they don't decide to use it, nothing changes for them.

> and it will add strings to everything that has bindings (I know they are stringnames so it's just a pointer, but still.).

I don't understand what you mean. This code is not using String nor StringName at all. All the code in this commit that uses StringName is in the C# bindings generator.

> The doc generators or code completion may also get confused (or need to take this into consideration) with this given they also use it.

The doc generators and code completion won't use this AFAIK. GDScript only supports int (64bit integer) so there is no point in using this, and as I said this doesn't break any existing code, it's a completely opt-in thing.

**Comment by neikeq** [comment]
I would rather do it this way, but I don't really mind doing it the way you suggested if you ultimately decide so (there are only a few places using byte and short any way). I just don't understand these points.

**Comment by reduz** [comment]
Nevermind, I misread the PR. I guess this is OK.

**Comment by akien-mga** [comment]
Thanks!

**Comment by karroffel** [comment]
This does not change the way `ptrcall` receives arguments, right? I'm a bit confused what this does then apart from documentation purposes?

**Comment by neikeq** [comment]
@karroffel It does not change anything in ptrcall. This is metadata you can optionally use when generating bindings for a language.

If a C# method has a parameter of type `short`, this parameter has to be stored in a variable of the correct type in order to pass it to `ptrcall`. In the case of any integral type that would be `int64_t`, as defined in [core/method_ptrcall.h](https://github.com/godotengine/godot/blob/master/core/method_ptrcall.h).
