### PR TITLE
Fix Directory Open Check

### LINKED ISSUE #40146: Deleting a user:// folder with an invalid path deletes top level project files
**Godot version:**
3.2.2

**OS/device including version:**
Windows 10 64bit

**Issue description:**
When using the Directory class to delete folders/files within the user:// path if a variable is used to concatenate paths together and the variable has not been defined, rather than failing Godot seems to delete the top level files within the project folder. I believe including a typo without a var does not appear to produce this issue.

I came across this issue while working on save deletions within my game, I believe the variable I'm using is defined, however this is the only way I've been able to reproduce this in a minimum project.

My assumption is the user:// path within Godot doesn't know about or have access to the project files and so this is very odd behaviour.

**Steps to reproduce:**
1. Create new files/folders within the user:// directory
2. Delete the files/folders and include an undefined variable to concatenate the paths
3. Watch the project files get deleted :(

**Minimal reproduction project:**
[Delete-Test.zip](https://github.com/godotengine/godot/files/4875846/Delete-Test.zip)

I've managed to reproduce this minimal project, it includes three buttons:
- The first will setup a basic folder structure with some dummy files inside
- The second will try and delete those files using an undefined `name` variable, clicking this button will delete some of the files and also the project's own source files
- The third button will do the same as the second but with the `name` variable defined, this would have the expected behaviour

### PR DESCRIPTION
**Pull request by nathanfranke**
Fixes #40146 

All the error checks were simply checking if the `DirAccess* d` was defined, when in reality it is always defined, even if a file is not open.

### CODE REVIEW

File: drivers/windows/dir_access_windows.cpp [hunk 1]
```diff
@@ -67,7 +67,11 @@ Error DirAccessWindows::list_dir_begin() {
 	list_dir_end();
 	p->h = FindFirstFileExW((current_dir + "\\*").c_str(), FindExInfoStandard, &p->fu, FindExSearchNameMatch, nullptr, 0);
 
-	return (p->h == INVALID_HANDLE_VALUE) ? ERR_CANT_OPEN : OK;
+	if (p->h == INVALID_HANDLE_VALUE) {
+		return ERR_CANT_OPEN;
+	}
+
+	return OK;
```
Comment (nathanfranke) [inline drivers/windows/dir_access_windows.cpp:74]: Hopefully this change is okay, I just wanted to make this more readable.

File: core/bind/core_bind.h [hunk 2]
```diff
@@ -457,13 +457,16 @@ VARIANT_ENUM_CAST(_File::CompressionMode);
 class _Directory : public Reference {
 	GDCLASS(_Directory, Reference);
 	DirAccess *d;
+	bool dir_open;
```
Comment (akien-mga) [inline core/bind/core_bind.h:460]: Missing initialization.

File: core/bind/core_bind.cpp [hunk 3]
```diff
@@ -1619,12 +1619,17 @@ Error _Directory::open(const String &p_path) {
...
 	return OK;
 }
 
+bool _Directory::is_open() const {
+	return dir_open;
+}
+
 Error _Directory::list_dir_begin(bool p_skip_navigational, bool p_skip_hidden) {
-	ERR_FAIL_COND_V_MSG(!d, ERR_UNCONFIGURED, "Directory must be opened before use.");
+	ERR_FAIL_COND_V_MSG(!is_open(), ERR_UNCONFIGURED, "Directory must be opened before use.");
```
Comment (akien-mga) [inline core/bind/core_bind.cpp:1632]: These checks are meant to prevent a null pointer dereference, which could still happen as far as I know. `d` is indeed initialized in the constructor, but this init could fail, or be removed in the future.

Right now it should be safe enough with `dir_open` (once properly initialized to `false`), but I think it might be safer to check `dir_open && d` in `is_open()`. (Or a single `ERR_FAIL_NULL_V(d, false)` in `is_open()` maybe?

File: drivers/windows/dir_access_windows.cpp (hunk 1 above)
Comment (akien-mga) [reply drivers/windows/dir_access_windows.cpp:74]: That's fine.

File: core/bind/core_bind.h (hunk 2 above)
Comment (Xrayez) [inline core/bind/core_bind.h:460]:
```suggestion
	bool dir_open = false;
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.
