### PR TITLE
Windows: Normalize slashes in return of `OS.get_temp_dir()`

### LINKED ISSUE #102008: OS directory slashes on Windows are inconsistent with temp as \ and the rest are /
### Tested versions

v4.4.beta1.official [d33da79d3]

### System information

Godot v4.4.beta1 - Windows 10 (build 19045) - Multi-window, 9 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3070 (NVIDIA; 32.0.15.6636) - 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 threads)

### Issue description

The OS directory values having either \ or / work with a shell open, but when printing their values out:
the temp dir is \\
the rest are /

### Steps to reproduce

Print the various OS directory commands:
	print(OS.get_temp_dir())
	print(OS.get_cache_dir())
	print(OS.get_data_dir())
	print(OS.get_config_dir())
	print(OS.get_user_data_dir())

output is:
C:\Users\profile\AppData\Local\Temp\
C:/Users/profile/AppData/Local
C:/Users/profile/AppData/Roaming
C:/Users/profile/AppData/Roaming
C:/Users/profile/AppData/Roaming/Godot/app_userdata/MRP directory slashes

The censor_user function I made to not show my profile name for the example picture

Image

### Minimal reproduction project (MRP)

[mrp_directory_slashes.zip](https://github.com/user-attachments/files/18544707/mrp_directory_slashes.zip)

### PR DESCRIPTION
**Pull request by Eddy-Rogers**
Added Backslash replacement in OS.get_temp_dir() function for consistency with other OS file path functions.

Fixes https://github.com/godotengine/godot/issues/102008

### CODE REVIEW

**Review by bruvzg — APPROVED** [review]

**Review by Calinou — COMMENTED** [review]
Tested locally, it works as expected.

```gdscript
func _ready() -> void:
	print(OS.get_cache_dir())
	print(OS.get_temp_dir())
	print(OS.get_data_dir())
	print(OS.get_user_data_dir())
	print(OS.get_config_dir())
	print(OS.get_system_dir(OS.SYSTEM_DIR_DOCUMENTS))
	print(OS.get_system_font_path("Arial"))
```

Results in:

```
C:/Users/Hugo/AppData/Local
C:/Users/Hugo/AppData/Local/Temp/
C:/Users/Hugo/AppData/Roaming
C:/Users/Hugo/AppData/Roaming/Godot/app_userdata/Test String Replace
C:/Users/Hugo/AppData/Roaming
C:/Users/Hugo/Documents
C:/WINDOWS/FONTS/arial.ttf
```

While we're at it, we'll want to trim the trailing slash from the path as it's not present in any other path.

File: platform/windows/os_windows.cpp [hunk 1]
```diff
@@ -2168,7 +2168,7 @@ String OS_Windows::get_temp_path() const {
 			temp_path_cache = get_config_path();
 		}
 	}
-	return temp_path_cache;
+	return temp_path_cache.replace("\\", "/");
```
Comment (Calinou) [inline platform/windows/os_windows.cpp:2171]:
```suggestion
	return temp_path_cache.replace("\\", "/").trim_suffix("/");
```

**Review by akien-mga — APPROVED** [review]
I squashed the commits, this should be ready to merge.

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
