### PR TITLE
Fix Visual Script's jump to function relative to zoom

### LINKED ISSUE #58849: Jump to function (double-click at function name) doesn't work correctly when Visual Script's canvas zooming ratio isn't at 100%
### Godot version

v4.0.alpha3.official [256069eaf], v3.4.3.stable.official [242c05d12]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

Jump to function (double-click at function name) doesn't work correctly when Visual Script's canvas zooming ratio isn't at 100%, as shown in the screen recordings below:

**Godot 4:**

https://user-images.githubusercontent.com/1403194/156947676-c0559836-9424-4340-a356-fb9467f8160b.mp4

**Godot 3:**

https://user-images.githubusercontent.com/1403194/156947727-78eebae9-4115-4457-824b-a6bd63e3e2c2.mp4

I expect this feature to work correctly regardless of any zooming ratio.

### Steps to reproduce

1. Create a function in Visual Script.
2. Zoom in or zoom out the canvas, then jump to the function. The focus function won't be in the view.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by SirQuartz**
When double-clicking on a function name the graph will now correctly jump to the function relative to the zoom ratio.

https://user-images.githubusercontent.com/62965063/162406169-c55e2b6a-c440-4a92-a910-5fe495fd8337.mp4

Resolves: #58849

### CODE REVIEW

**Review by fire — APPROVED** [review]

**Comment by fire** [comment]
@theoway @Gallilus If you wanted to review.

**Comment by theoway** [comment]
@fire LGTM
@SirQuartz Can you squash the two commits into one?

File: modules/visual_script/editor/visual_script_editor.cpp [hunk 1]
```diff
@@ -2727,7 +2727,7 @@ void VisualScriptEditor::_center_on_node(int p_id) {
 
 	if (gn) {
 		gn->set_selected(true);
-		Vector2 new_scroll = gn->get_position_offset() - graph->get_size() * 0.5 + gn->get_size() * 0.5;
+		Vector2 new_scroll = Vector2(gn->get_position_offset().x * graph->get_zoom() - graph->get_size().x / 2 + gn->get_size().x * 0.5, gn->get_position_offset().y * graph->get_zoom() - graph->get_size().y / 2 + gn->get_size().y * 0.5);
```
Comment (akien-mga) [inline modules/visual_script/editor/visual_script_editor.cpp:2730]: Why not use the Vector2 operators like the previous code? This would be much more readable.
```suggestion
		Vector2 new_scroll = gn->get_position_offset() * graph->get_zoom() - graph->get_size() * 0.5 + gn->get_size() * 0.5;
```

**Comment by akien-mga** [comment]
I squashed the commits myself to make this ready to merge.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.5.
