### PR TITLE
Keep processing Graphics if there are pending operations

### LINKED ISSUE #90017: When the window is minimized (hidden), the MeshArray causes a memory leak.
### Tested versions

- 4.2.stable

### System information

Godot v4.2.stable - macOS 14.3.1 - Vulkan (Forward+) - integrated Apple M2 Max - Apple M2 Max (12 Threads)

### Issue description

Dynamically generated mesh instances are discarded when they become unnecessary.
However, when the window is minimized, the deletion does not occur and continues to consume memory.
The allocated memory is released when the window is restored, but it can cause a crash in some cases.

This can be reproduced with the following code:

```gdscript
extends Node2D


func _process(_delta):
    var ary: Array = []
    ary.resize(Mesh.ARRAY_MAX)
    ary[Mesh.ARRAY_VERTEX] = PackedVector3Array([Vector3(0, 0, 0)])

    var ary_mesh: ArrayMesh = ArrayMesh.new()
    ary_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_POINTS, ary)
```

mleak_mesh_array

> This issue was discovered during the investigation of the following issue:
> https://github.com/godotengine/godot/issues/89651

### Steps to reproduce

To reproduce this issue, execute the _mleak_mesh_array.tscn_ file included in the attached project.

While the application is running, open the **Debugger/Monitors** in the Editor and pay attention to the value of **Memory/Static**.

This value will gradually increase while the application being debugged is minimized.
When the application is restored from minimization, the increased memory is released.

### Minimal reproduction project (MRP)

[mleak_mesh_array.zip](https://github.com/godotengine/godot/files/14804644/mleak_mesh_array.zip)

### LINKED ISSUE #90030: Memory Leaks in SubViewport When Window is Minimized
### Tested versions

4.2.stable

### System information

Godot v4.2.stable - macOS 14.3.1 - Vulkan (Forward+) - integrated Apple M2 Max - Apple M2 Max (12 Threads)

### Issue description

I've observed that memory leaks occur when explicit initialization (setting to transparent_bg) is performed every time when using SubViewport.
This issue could lead to significant performance issues and needs to be resolved.

> Additional Information:
This issue is not specifically related to whether the SubViewport is connected to a node.
It seems to occur regardless of the node connection status of the SubViewport.

This can be reproduced with the following code:

```gdscript
extends Node2D

var v: SubViewport

func _ready():
    v = SubViewport.new()
    
func _process(_delta):
    v.transparent_bg = true
```

mleak_vp_transparent_bg

> This issue was discovered during the investigation of the following issue:
> https://github.com/godotengine/godot/issues/89651
> https://github.com/godotengine/godot/issues/90017

### Steps to reproduce

To reproduce this issue, execute the mleak_vp_transparent_bg.tscn file included in the attached project.

While the application is running, open the Debugger/Monitors in the Editor and pay attention to the value of Memory/Static.

This value will gradually increase while the application being debugged is minimized.
When the application is restored from minimization, the increased memory is released.

### Minimal reproduction project (MRP)

[mleak_vp_transparent_bg.zip](https://github.com/godotengine/godot/files/14809551/mleak_vp_transparent_bg.zip)

### LINKED ISSUE #98044: `RenderingDevice` cannot release texture resource when window is minimized
### Tested versions

4.3.stable.mono

### System information

Godot v4.3.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 (NVIDIA; 31.0.15.3161) - AMD Ryzen 9 7900X 12-Core Processor (24 Threads)

### Issue description

When the game window is minimized, the texture created by `RenderingDevice.create_texture()` won't be freed by calling `RenderingDevice.free_rid()`. 

image
when the game window is not minimized

image
when the game window is minimized after a while

BTW, the Memory inspected by Editor Debugger grows much slower than inspected by Windows Task Manager, when this bug is triggered. 
image
not minimized
image
minimized after a while

### Steps to reproduce

```gdscript
extends Node2D

var rd : RenderingDevice;
var texture : RID;

func _ready() -> void:
	rd = RenderingServer.get_rendering_device()

func _process(delta: float) -> void:
	#RenderingServer.call_on_render_thread(create_texture);
	create_texture()

func create_texture() -> void:
	if texture.is_valid():
		rd.free_rid(texture)
	
	var format = RDTextureFormat.new()
	format.width = 1024
	format.height = 1024
	format.depth = 1
	format.format = RenderingDevice.DATA_FORMAT_R8G8B8A8_UNORM
	format.array_layers = 1
	format.mipmaps = 1
	format.usage_bits = RenderingDevice.TEXTURE_USAGE_SAMPLING_BIT | RenderingDevice.TEXTURE_USAGE_CAN_UPDATE_BIT | RenderingDevice.TEXTURE_USAGE_STORAGE_BIT
	
	texture = rd.texture_create(format, RDTextureView.new(), [])
```

1. This script will create a texture pre frame and release the texture created last frame. 
2. Attach it to a node and run the scene.
3. Minimize the game window (not editor). (just hide this window below other windows won't trigger this bug)

### Minimal reproduction project (MRP)

See 'Steps to reproduce'

### PR DESCRIPTION
**Pull request by darksylinc**
Fixes #90017
Fixes #90030
Fixes #98044

This PR makes the following changes:

# Force processing of GPU commands for frame_count frames

The variable `frames_pending_resources_for_processing` is added to track this.

The ticket #98044 suggested to use `_flush_and_stall_for_all_frames()` while minimized.

Technically this works and is a viable solution.

However I noticed that this issue was happening because Logic/Physics continue to work "business as usual" while minimized(\*). Only Graphics was being deactivated (which caused commands to accumulate until window is restored).

To continue this behavior of "business as usual", I decided that GPU work should also "continue as usual" by buffering commands in a double or triple buffer scheme until all commands are done processing (if they ever stop coming). This is specially important if the app specifically intends to keep processing while minimized.

Calling `_flush_and_stall_for_all_frames()` would fix the leak, but it would make  Godot's behavior different while minimized vs while the window is presenting.

(\*) `OS::add_frame_delay` _does_ consider being minimized, but it just throttles CPU usage. Some platforms such as Android completely disable processing because the higher level code stops being called when the app goes into background. But this seems like an implementation-detail that diverges from the rest of the platforms (e.g. Windows, Linux & macOS continue to process while minimized).

# Rename p_swap_buffers for p_present

**This is potentially a breaking change** (if it actually breaks anything, I ignore. But I strongly suspect it doesn't break anything).

"Swap Buffers" is a concept carried from OpenGL, where a frame is "done" when `glSwapBuffers()` is called, which basically means "present to the screen".

However it _also_ means that OpenGL internally swaps its internal buffers in a double/triple buffer scheme (in Vulkan, we do that ourselves and is tracked by `RenderingDevice::frame`).

Modern APIs like Vulkan differentiate between "submitting GPU work" and "presenting".

Before this PR, calling `RendererCompositorRD::end_frame(false)` would literally do nothing. This is often undesired and the cause of the leak. After this PR, calling `RendererCompositorRD::end_frame(false)` will now process commands, swap our internal buffers in a double/triple buffer scheme **but avoid presenting to the screen**.

Hence the rename of the variable from `p_swap_buffers` to `p_present` (which slightly alters its behavior).
If we want `RendererCompositorRD::end_frame(false)` to do nothing, then we should not call it at all.

This PR reflects such change: When we're minimized **_and_** `has_pending_resources_for_processing()` returns false, we don't call `RendererCompositorRD::end_frame()` at all.

But if `has_pending_resources_for_processing()` returns true, we will call it, but with `p_present = false` because we're minimized.

There's still the issue that Godot keeps processing work (logic, scripts, physics) while minimized, which we shouldn't do by default. But that's work for follow up PR.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Looks great!

There are two places where we call `draw(false)`. Both are in editor classes (resource preview and onion skinning). In both cases we are just forcing the rendering server to redraw a viewport without needing to wait for vsync and draw to the main screen. So I don't think either one will regress with this change. In fact, this might be an improvement in both cases as it seems like they wouldn't properly end the frame previously.

File: servers/rendering/rendering_device.cpp [hunk 1]
```diff
@@ -5868,6 +5870,9 @@ void RenderingDevice::_free_pending_resources(int p_frame) {
 
 		frames[p_frame].buffers_to_dispose_of.pop_front();
 	}
+
+	if (frames_pending_resources_for_processing > 0u)
+		--frames_pending_resources_for_processing;
```
Comment (AThousandShips) [inline servers/rendering/rendering_device.cpp:5875]:
```suggestion
	if (frames_pending_resources_for_processing > 0u) {
		--frames_pending_resources_for_processing;
	}
```
Always use brackets

**Comment by Repiteo** [comment]
Thanks!
