### PR TITLE
HTTPRequest add timeout

### LINKED ISSUE #30276: HTTPRequest request timeout cannot be configured
**Godot version:**
v.3.1.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
Connection never times out when connecting with a host that does not exist. I think it only happens when trying to connect with ip hosts, status is indefinitely `STATUS_CONNECTING` (3). I'm not sure if that is expected behavior so for now i'v created a `Timer` `Node` and i cancel the request on timeout of the timer.
What i was expecting is the request to timeout at some point and call the `request_complete` signal. Also i was expecting to find out some `timeout` property or parameter in case we need to timeout the connection manualy.

**Steps to reproduce:**
Request anything from an unrelovable ip, example:
```
request("http://10.10.10.10:1234"
request("http://127.0.0.1:1234"
request("http://1.1.1.1:1234"
```
Any of these should be able to reproduce it as long as there is no server running on these ips/ports.

### PR DESCRIPTION
**Pull request by zakstam**
Although this should have been implemented in HTTPClient calls instead of HTTPRequest, i realized that halfway through. I can rewrite it for HTTPClient instead if desired.
Also, timeout could have been a parameter for the request() method instead of a property but i figured out that there is no reason setting the timeout for each request.

**EDIT:** A custom response code should be added for this one? Like RESPONSE_CUSTOM_TIMEOUT since its not a standard socket error, we are forcefully closing the connection after the timeout is reached.
@Faless please review.

This should close #30276

### CODE REVIEW

**Comment by akien-mga** [comment]
The first commit is from an unrelated PR and should be removed.

**Comment by zaksnet** [comment]
> The first commit is from an unrelated PR and should be removed.

Sorry, working on it. No idia how it was added here.

**Comment by Faless** [comment]
I think this probably needs to go into `StreamPeerTCP`.

**Comment by zaksnet** [comment]
> I think this probably needs to go into `StreamPeerTCP`.
> 
> EDIT: Of course, there you can't use timers, but need to use the OS timing function during poll (`OS::get_singleton()->get_ticks_msec()`).

Sorry, I'm a bit confused on how i would go about implementing this one. Should timeout property be in stream_peer_tcp class? If so, i should have a set_timeout method in all http_client, http_request and stream_peer_tcp classes?

**Comment by Faless** [comment]
@zaksnet well, I would say we need to first define what problem we are trying to solve.
And please bear with me because I'm still trying to wrap my mind about this.

If I understand the problem correctly, windows does not seem to timeout during the connection phase, but it does timeout correctly an already established connection. So, we should only check for timeout "manually" during the TCP `connect` phase to at least normalize behaviour across OSes.
Timing out an HTTP connection where data is flowing is another matter, and while it's an interesting point, you might probably want a separate timeout value for that. You need to take into account how much data you need to transfer, how good the user connection is, etc.

So, this PR do cover the second problem, and it might be okay. But I don't think it solves the underlying one for which we probably need another PR. That said, this one is good enough for the "request is taking too long" use case, I'll go on and review it.

**Review by Faless — CHANGES_REQUESTED** [review]
See my above comments. I also agree we could add a new `RESULT_TIMED_OUT` or `RESULT_TIMEOUT` to the `Result` enum and use that to signal that a timeout has been reached.

**Comment by zaksnet** [comment]
>Timing out an HTTP connection where data is flowing is another matter, and while it's an interesting point, you might probably want a separate timeout value for that. You need to take into account how much data you need to transfer, how good the user connection is, etc.

@Faless Sorry my fault, i only want to timeout a connection when the status is `connecting` and not when it is `connected` (because as you pointed out, it times out correctly while connected). I just forgot to cancel the timer when the status changes to `connected` 😳 . In my use case, even if the timeout worked as expected and dropped the connection after 5, 8, 10 min it would still not be enough, I'd need a much smaller number (something like 20 sec).

>If I understand the problem correctly, windows does not seem to timeout during the connection phase, but it does timeout correctly an already established connection. So, we should only check for timeout "manually" during the TCP connect phase to at least normalize behaviour across OSes.

Correct me if i'm wrong but i think what you want is to normalize timeout across platforms internally so i assume there will be no setter/getter, the connection will be dropped after a fixed `timeout`. Although i understand the use case for this, I'm afraid it would not fit my needs.

Canceling the timer once a connection is established would be enough to please my needs, but as you said it will not fix the root problem.

(This is in general for sockets, not just http):
Also, a timeout message could be useful as it could be used to `ping` idle connections (or to send any other message to idle clients).

**Comment by zaksnet** [comment]
Or maybe have 2 timeout enums. One for while connecting and one while connected. RESULT_TIMEOUT_WHILE_CONNECTING and RESULT_TIMEOUT to be more explicit.

**Comment by zaksnet** [comment]
After reading my comments, i realized that they seem a bit selfish. For that reason pushed another commit that i feel will fit everyone's needs. 
Instead of forcefully closing the connection on timeout, we can emit a "timeout" signal. Users can take that signal and do whatever they want with it, some might want to close the connection, others might want to load another link (in case this one was broken), others might want to reset the timeout for another `x` seconds. Also, the signal will emit the most useful info (instead of empty arrays and strings, which is what a failed request_complete emitted), the host, port, url body and status.

So with this, in my use case, i can just check the status and if its 3 (still trying to connect) then i can close the connection.

**Comment by Faless** [comment]
My thoughts about this:

- Timeout should affect the whole request, not just the connect part. for that, #30422 is IMO a better fix.
- Timeout should close the connection, no point in emitting signal and forcing the user to still write code for it.
- Timeout should be the maximum time the dev expects the `HTTPRequest` will take before completion. I.e. no matter if partial data is transmitted, if that amount of time has elapsed, the request will stop.

**Comment by zaksnet** [comment]
> My thoughts about this:
> 
> * Timeout should affect the whole request, not just the connect part. for that, #30422 is IMO a better fix.
> * Timeout should close the connection, no point in emitting signal and forcing the user to still write code for it.
> * Timeout should be the maximum time the dev expects the `HTTPRequest` will take before completion. I.e. no matter if partial data is transmitted, if that amount of time has elapsed, the request will stop.

Alright, here is why i switched to a signal instead:
First of all, I changed the logic of the timeout, it no longer occurs only when the `connecting` part happens. It will occur after the specified amount of time no matter what the connection state is. For that reason, this PR does not conflict with #30422 .
- A signal is better because you can use coding logic in there, like checking for broken links and loading new ones from a list.
- You can check the state of the connection and the url and either reset the timeout or close the connection.
- The user will probably only have to write 1 line of code in case all they want is to close the connection on timeout.

**Comment by Faless** [comment]
>     * A signal is better because you can use coding logic in there, like checking for broken links and loading new ones from a list.

You can do that when you get the request done signal with result = timeout error.

>     * You can check the state of the connection and the url and either reset the timeout or close the connection.

Do you have a use case for that? Can't you, in that rare case simply raise the timeout and make the request again? What would the difference be?

>     * The user will probably only have to write 1 line of code in case all they want is to close the connection on timeout.

Yeah, so for very common cases we would require you to write code, just because we want to make very rare cases slightly easier. It doesn't seem like a good idea for me.

**Comment by zaksnet** [comment]
@Faless , I'll do some testing with the test you provided in #30422 and come back to this.

**Comment by zaksnet** [comment]
I still feel the timeout signal would be handy, for the same reason HTTPRequest exists (and many other classes), to simplify things.

File: scene/main/http_request.cpp [hunk 1]
```diff
@@ -272,6 +279,7 @@ bool HTTPRequest::_update_connection() {
 		} break;
 		case HTTPClient::STATUS_CONNECTED: {
 
+			timer->stop();
```
Comment (Faless) [inline scene/main/http_request.cpp]: Didn't we agree not to stop the timer on connection but leave it as a timeout on the whole request?

**Review by Faless — CHANGES_REQUESTED** [review]
See my comment. You also need to add:
`BIND_ENUM_CONSTANT(RESULT_TIMEOUT);` in `_bind_methods`

File: scene/main/http_request.cpp (hunk 1 above)
Comment (zaksnet) [reply scene/main/http_request.cpp]: Sorry, missed that 😳

**Comment by Faless** [comment]
One last thing, could you apply this to make the timeout property in the editor a limited range 0 to 86400, and prevent users from setting negative values?
```diff
diff --git a/scene/main/http_request.cpp b/scene/main/http_request.cpp
index 7c9983cec..05bd91101 100644
--- a/scene/main/http_request.cpp
+++ b/scene/main/http_request.cpp
@@ -488,6 +488,7 @@ int HTTPRequest::get_body_size() const {
 
 void HTTPRequest::set_timeout(int p_timeout) {
 
+       ERR_FAIL_COND(p_timeout < 0);
        timeout = p_timeout;
 }
 
@@ -536,7 +537,7 @@ void HTTPRequest::_bind_methods() {
        ADD_PROPERTY(PropertyInfo(Variant::BOOL, "use_threads"), "set_use_threads", "is_using_threads");
        ADD_PROPERTY(PropertyInfo(Variant::INT, "body_size_limit", PROPERTY_HINT_RANGE, "-1,2000000000"), "set_body_size_limit", "get_body_size_limit");
        ADD_PROPERTY(PropertyInfo(Variant::INT, "max_redirects", PROPERTY_HINT_RANGE, "-1,64"), "set_max_redirects", "get_max_redirects");
-       ADD_PROPERTY(PropertyInfo(Variant::INT, "timeout"), "set_timeout", "get_timeout");
+       ADD_PROPERTY(PropertyInfo(Variant::INT, "timeout", PROPERTY_HINT_RANGE, "0,86400"), "set_timeout", "get_timeout");
 
        ADD_SIGNAL(MethodInfo("request_completed", PropertyInfo(Variant::INT, "result"), PropertyInfo(Variant::INT, "response_code"), PropertyInfo(Variant::POOL_STRING_ARRAY, "headers"), PropertyInfo(Variant::POOL_BYTE_ARRAY, "body")));
 
```

**Review by Faless — APPROVED** [review]
Good work! I'll merge when CI is done

**Comment by Faless** [comment]
Thanks!
