### PR TITLE
Validate theme type name input in Add Theme Type dialog

### LINKED ISSUE #104297: Support non-English characters in "Theme type variations"
### Tested versions

- Reproducible in: 4.4-stable

### System information

Godot v4.4.stable - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 (NVIDIA; 31.0.15.3129) - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 threads)

### Issue description

**Issue**:  
When adding variations to a DIY node in the UI editor:  
1. Naming the variation **in Chinese** results in **no changes being applied** and console report error.  
  ```
  ERROR: Invalid type name: '啊啊'
  ERROR: Invalid type name: '啊啊'
  ERROR: Invalid type name: '啊啊'
  ERROR: Invalid type name: '啊啊'
  ERROR: Invalid type name: '啊啊'
  ERROR: Invalid type name: '啊啊'
  ```
2. **English names** work without issues.  

**Expected Behavior**:  
Non-English characters (e.g., Chinese, Cyrillic, emojis) should be fully supported for node/variation names, as the UI implies this is allowed. Currently, this appears to be a localization or character encoding bug.  

### Steps to reproduce

1. First open a ui resource
Image
2. Then add a new node with chinese naming
Image
3. Console report bug
Image
```--- GDScript language server started on port 6005 ---
  ERROR: Invalid type name: '啊啊'
  ERROR: Invalid type name: '啊啊'
  ERROR: Invalid type name: '啊啊'
  ERROR: Invalid type name: '啊啊'
  ERROR: Invalid type name: '啊啊'
  ERROR: Invalid type name: '啊啊'
```
4. Try eng naming
Image
5. no problem

### Minimal reproduction project (MRP)

[bugreport.zip](https://github.com/user-attachments/files/19305174/bugreport.zip)

### PR DESCRIPTION
**Pull request by timothyqiu**
Closes #104297

There are four places where users can provide the name of a theme type:

1. Clicking "+" button in the Theme bottom panel to add a new theme type.
2. Clicking "I" button in the Theme bottom panel to rename an existing theme type.
3. Clicking "+" button in the Manage Theme Items dialog to add a new theme type.
4. Double clicking an theme type list item in the Manage Theme Items dialog to rename an existing theme type.

Currently, place 1 does no check while the others mistakenly prohibit the use of names beginning with numbers.

This PR fixes the validation and adds the missing check in place 1.

p.s. Also optimized `Theme::is_valid_type_name()` and `Theme::is_valid_item_name()`.

### CODE REVIEW

File: editor/scene/gui/theme_editor_plugin.cpp [hunk 1]
```diff
@@ -77,6 +77,14 @@ static void _rename_theme_type(EditorUndoRedoManager *p_ur, Theme *p_theme, cons
 	}
 }
 
+static String _validate_theme_type_name_input(const String &p_name) {
+	const String &type_name = p_name.strip_edges();
+	if (type_name.is_empty()) {
+		return type_name; // An empty string is a special theme type.
+	}
+	return type_name.validate_ascii_identifier();
```
Comment (dalexeev) [inline editor/scene/gui/theme_editor_plugin.cpp]: Note that theme type names are not strictly speaking identifiers: the first character may be a digit.

https://github.com/godotengine/godot/blob/8a17c2ac6e0f37b00e9659ff7c04c5ab258645e5/scene/resources/theme.cpp#L178-L185

**Comment by timothyqiu** [comment]
OK fixed. I think this PR can now also be considered a bugfix and I moved it to 4.5. The current logic for the other three places did not take type names starting with numbers into account.

File: editor/scene/gui/theme_editor_plugin.cpp [hunk 2]
```diff
@@ -77,6 +77,24 @@ static void _rename_theme_type(EditorUndoRedoManager *p_ur, Theme *p_theme, cons
 	}
 }
 
+static String _validate_theme_type_name_input(const String &p_name) {
```
Comment (dalexeev) [inline editor/scene/gui/theme_editor_plugin.cpp]: In my opinion, it is best to place this function next to `Theme::is_valid_type_name()`, as a public static method.

File: editor/scene/gui/theme_editor_plugin.cpp [hunk 3]
```diff
@@ -77,6 +77,24 @@ static void _rename_theme_type(EditorUndoRedoManager *p_ur, Theme *p_theme, cons
...
+	String type_name = p_name.strip_edges();
+
+	// An empty string is a special theme type.
+	if (type_name.is_empty()) {
+		return type_name; // Return early to avoid unnecessary COW.
+	}
```
Comment (dalexeev) [inline editor/scene/gui/theme_editor_plugin.cpp]: This part is a bit redundant, since in case of an empty name the loop will be empty too. I'm not saying that early checking is not needed, I'm just noting the inconsistency with `Theme::is_valid_type_name()`.

Comment (timothyqiu) [reply editor/scene/gui/theme_editor_plugin.cpp]: This is to avoid triggering copy-on-write due to `ptrw()`. But indeed, copying an empty string shouldn't cause any harm :smile:

File: scene/resources/theme.cpp [hunk 4]
```diff
@@ -196,6 +196,18 @@ bool Theme::is_valid_item_name(const String &p_name) {
 	return true;
 }
 
+String Theme::validate_type_name(const String &p_name) {
+	String type_name = p_name.strip_edges();
+	int len = type_name.length();
+	char32_t *buffer = type_name.ptrw();
```
Comment (dalexeev) [inline scene/resources/theme.cpp:206]: Does it make sense to also optimize `Theme::is_valid_type_name()` and `Theme::is_valid_item_name()`? Or is it only needed because you are modifying the buffer?

**Review by dalexeev — APPROVED** [review]

File: scene/resources/theme.cpp (hunk 4 above)
Comment (timothyqiu) [reply scene/resources/theme.cpp:206]: It's mainly for modifying string content in place. I think those two methods could theoretically be slightly more performant if they accessed pointers directly, since that would eliminate some repetitive boundary checks.

**Comment by Repiteo** [comment]
Thanks!
