### PR TITLE
Fix 2D shader preview draws over uniform

### LINKED ISSUE #76337: Editor: 2D shader preview draws over uniform
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Kubuntu 22.10

### Issue description

image
Just a small bug, but kinda annoying.
Change the preview Rect draw order should fix it.

### Steps to reproduce

1.  Create a custom Canvas Item Shader.
2. 
```
void vertex()
{
    VERTEX.y += 200.0;
}
```

### Minimal reproduction project

[Canvas shader preview Bug.zip](https://github.com/godotengine/godot/files/11300522/Canvas.shader.preview.Bug.zip)

### PR DESCRIPTION
**Pull request by Tetane**
Fixes #76337.

I've put the CanvasItem shader preview inside a SubViewport the same way it is done for the Spatial shader preview.

### CODE REVIEW

**Comment by clayjohn** [comment]
We have a helpful tutorial in the official documentation for rebasing a pull request and removing extraneous commits! https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase

**Comment by Tetane** [comment]
Ok, thanks, I think I fixed it. Sorry again for not following the guidelines.

File: editor/plugins/material_editor_plugin.cpp [hunk 1]
```diff
@@ -164,9 +164,22 @@ void MaterialEditor::_button_pressed(Node *p_button) {
...
 
+	vc_2d = memnew(SubViewportContainer);
+	vc_2d->set_stretch(true);
+	add_child(vc_2d);
+	vc_2d->set_anchors_and_offsets_preset(PRESET_FULL_RECT);
+
+	viewport_2d = memnew(SubViewport);
+	Ref<World3D> world_2d;
+	world_2d.instantiate();
+	viewport_2d->set_world_3d(world_2d); //use own world
```
Comment (clayjohn) [inline editor/plugins/material_editor_plugin.cpp:175]: Since you aren't rendering any 3D objects, you don't need to create a unique world 3D. By default Viewports will only render 2D objects that are their children.

**Review by clayjohn — CHANGES_REQUESTED** [review]
Looks good now! I just left a comment on some code you can remove. 

I tested locally and this works great!

File: editor/plugins/material_editor_plugin.cpp (hunk 1 above)
Comment (Tetane) [reply editor/plugins/material_editor_plugin.cpp]: Thanks! I was not aware of that. I modified my commit accordingly. :)

**Review by clayjohn — APPROVED** [review]
Looks great now, thanks!

**Comment by kleonc** [comment]
> This fixes the issue #76337.

@Tetane Note writing it like this won't automatically link the issue to be closed on merging the PR. See [Linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) (I've already edited it so it's linked properly).

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thank you! Merged.

**Comment by akien-mga** [comment]
Cherry-picked for 4.0.3.
