### PR TITLE
Polish & fix editor help cache generation

### LINKED ISSUE #82817: GDExtension documentation no longer updating
### Godot version

4.2.dev6

### System information

Reproducible on Windows 10 & MacOS Sonoma

### Issue description

After updating from 4.1.1 stable to 4.2.dev6 the auto generated documentation for GDExtension classes is no longer updated after adding/changing/removing functions, enums, or properties. 

At first I thought this had because of an oversight in the new hot reload functionality (this is great by the way), but the documentation is not updated even after restarting the editor. I have not yet found a way to get the documentation to update in 4.2.

### Steps to reproduce

1. View documentation for a GDExtension class
2. Bind a new function to that class
3. View the documentation again and notice that no new entry has been added for that function

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by RandomShaper**
- Isolated the generation of extensions's docs. They're now not cached and refreshed as needed.
- Removed superfluous sorting of the class list.
- Removed some superfluous/unused elements.
- Renamed some items for clarity.

Fixes #82817.

### CODE REVIEW

**Comment by akien-mga** [comment]
The Mono glue generation is crashing: https://github.com/godotengine/godot/actions/runs/6731199052/job/18295441262?pr=84354

It reports that it's missing GlobalScope, not sure if that's the source of the crash.

**Comment by RandomShaper** [comment]
Should be fixed now.

File: editor/editor_help.cpp [hunk 1]
```diff
@@ -2415,14 +2419,15 @@ void EditorHelp::_gen_doc_thread(void *p_udata) {
 	}
 }
 
+void EditorHelp::_gen_extensions_docs() {
```
Comment (YuriSizov) [inline editor/editor_help.cpp:2422]: I think this can be a public method (called `generate_extension_docs`), and I think to fully support extensions this needs to be called whenever the GDExtension manager hot reloads any library. IIUC, this right now only loads extension docs when loading the cache or generating it anew.

Comment (dsnopek) [reply editor/editor_help.cpp:2422]: In @Riteo's PR to allow GDExtensions to add fuller documentation, he's got a separate `DocTools *` just for the extension documentation in order to keep track of which is from extensions:

https://github.com/godotengine/godot/pull/83747/files#diff-7f898e9b24837a348e2209c5a7e5d2b686d91580787069a6bab6ea78a5d38dba

Perhaps that approach could work here?

(May not actually make sense, I don't know the documentation system that well :-))

Comment (YuriSizov) [reply editor/editor_help.cpp:2422]: I don't think this would be necessary for this particular purpose (and besides, when we generate everything anew, we don't differentiate between sources of each class). ClassDB already has the API type stored, we can just read it and add it to the documentation entry.

**Review by YuriSizov — APPROVED** [review]
I can confirm this fixes the issue, if we don't consider hot reloading. Code changes also look good to me.

I think hot reloading can be fixed separately in a future PR (for 4.3 + maybe a 4.2.x cherry-pick). The implementation would be pretty straightforward, IMO. We can utilize `DocTools::remove_doc` and remove all docs related to extensions at the start of `GDExtensionManager::reload_extension`, and then regenerate them all after it is done. A bit excessive, but will get the job done.

We could probably use `DocTools::remove_doc` on individual classes before we reload the extension, if we can figure out which classes belong to it. But I believe a full (extension only) regen would be quick enough here already. If we do manage to remove individual classes, though, we should also make sure to regenerate only the newly added classes.

**Comment by YuriSizov** [comment]
Thanks!
