### PR TITLE
Fix custom resource icons in FileSystem

### LINKED ISSUE #32706: Custom resources don't use icon for file in filesystem
**Godot version:**
3.2 alpha-1 (custom build)
**OS/device including version:**
ArcoLinux
**Issue description:**
Practically all of Godot's resource types use a special icon to help the user determine what sort of file they're dealing with, assuming the file extension isn't enough (and a lot of resources use .tres/.res anyway.)  However, custom resources, though an icon can be supplied for them via `class_name`, do not use that icon in the filesystem, despite it working most everywhere else it would be used.

```
class_name Actor, "res://System/Icons/actor_icon.png" extends Resource
```

image
Works in the inspector

image
And in the Create New Resource dialogue

image
And when creating a new resource in a property

image
But, sadly, just a generic file icon used here, the same icon used for all other custom resources.

Ideally the user would be able to identify the resource, wherever it may be, by the icon, much like they do most other resources; this inconsistency breaks that reliance, and makes it considerably more difficult to determine at a glance what kind of file you're dealing with.

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #32706
Supersedes #73611

### CODE REVIEW

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -256,10 +263,11 @@ bool FileSystemDock::_create_tree(TreeItem *p_parent, EditorFileSystemDirectory
 		// Build the tree.
 		for (const FileInfo &fi : file_list) {
 			TreeItem *file_item = tree->create_item(subdirectory_item);
+			String file_metadata = lpath.path_join(fi.name);
 			file_item->set_text(0, fi.name);
 			file_item->set_structured_text_bidi_override(0, TextServer::STRUCTURED_TEXT_FILE);
-			file_item->set_icon(0, _get_tree_item_icon(!fi.import_broken, fi.type));
-			String file_metadata = lpath.path_join(fi.name);
+			file_item->set_icon(0, _get_tree_item_icon(!fi.import_broken, file_metadata, fi.type));
+			file_item->set_icon_max_width(0, 16 * EDSCALE);
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:270]: I think instead of hard-coding 16 we could use width of an existing icon, but for that it would be better to use some cached one (and there is no theme cache yet). I could leave a TODO comment maybe? (or add theme cache I guess)

Comment (YuriSizov) [reply editor/filesystem_dock.cpp:270]: You should use `get_theme_constant(SNAME("class_icon_size"), SNAME("Editor"))` instead.

File: editor/filesystem_dock.cpp [hunk 2]
```diff
@@ -254,12 +261,15 @@ bool FileSystemDock::_create_tree(TreeItem *p_parent, EditorFileSystemDirectory
 		_sort_file_info_list(file_list);
 
 		// Build the tree.
+		int icon_size = get_theme_constant(SNAME("class_icon_size"), SNAME("Editor"));
```
Comment (YuriSizov) [inline editor/filesystem_dock.cpp:264]: Can probably be a const variable.

**Comment by YuriSizov** [comment]
Yeah, the branch name is very fitting 🙃 This approach is going to read and parse the file for each stored resources every time we need to figure out its icon. Even if this information doesn't change, we would still parse the file, at least partially, to fetch the type information.

This definitely needs some cache, and that's what reduz wanted as well, I believe. To utilize the editor file system somehow, and only update the information when the underlying data, like the type or the script, changes. This way we would only have to run this expensive operation on change rather than on fetch.

I believe that the PR this one is supposed to supersede was going this route. After a lot of discussion they've hooked into the preview generator process, since it already needs to run for a changed resource. Maybe it's not the best place to hook into, but at least it creates an accessible cache for us to use on the file tree refreshes.

So in the end, I would not merge this in its current state and look for a more optimal approach using some sort of cache.

**Comment by KoBeWi** [comment]
I think the icons can be cached locally, we already do this with scene tree (see #60789). I'll look into that, I thought `get_class_icon()` already uses it...

**Comment by KoBeWi** [comment]
Ok rebased and updated. I used EditorFileSystem's cache to get resource icon, but it has caveats:
- it assumes the first dependency in the file is its Script
- it checks whether that dependency is actually a Script (not sure how fast is that)

I added a temporary HashMap that stores cache for each script path, so it shouldn't be *too slow*, but testing appreciated.

File: editor/filesystem_dock.cpp [hunk 3]
```diff
@@ -173,14 +173,48 @@ FileSystemList::FileSystemList() {
...
+String FileSystemDock::_get_entry_script_icon(const EditorFileSystemDirectory *p_dir, int p_file) {
+	const PackedStringArray &deps = p_dir->get_file_deps(p_file);
+	if (deps.is_empty()) {
+		return String();
+	}
+
+	const String &script_path = deps[0]; // Assuming the first dependency is a script.
+	if (script_path.is_empty() || !ClassDB::is_parent_class(ResourceLoader::get_resource_type(script_path), SNAME("Script"))) {
+		return String();
+	}
```
Comment (adamscott) [inline editor/filesystem_dock.cpp:202]: Maybe loop through the dependencies for the first script?

**Review by adamscott — APPROVED** [review]
Other than my comment, everything seems fine! I tested it and it works.

Thanks @KoBeWi !

File: editor/filesystem_dock.cpp (hunk 3 above)
Comment (KoBeWi) [reply editor/filesystem_dock.cpp:202]: That would be slower though 🤔
I'd change this only if it proves unreliable.

**Comment by akien-mga** [comment]
Thanks!

**Comment by z4gon** [comment]
@KoBeWi I'm seeing this issue in this build:
```
Godot Engine v4.3.beta1.official.a4f2ea91a - https://godotengine.org
OpenGL API 4.1 Metal - 88 - Compatibility - Using Device: Apple - Apple M1 Pro
```
Screenshot 2024-06-07 at 6 34 48 PM
Screenshot 2024-06-07 at 6 34 43 PM
Screenshot 2024-06-07 at 6 34 04 PM
