### PR TITLE
Fix progress dialog steals focus

### LINKED ISSUE #90944: Reimporting a resource makes godot open the script editor
### Tested versions

v4.3.dev.custom_build [4a0160241]

### System information

Godot v4.3.dev (4a0160241) - macOS 14.4.0 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

Reimporting an asset opens the script editor. If an external editor is used it opens the external editor (brings it on top)

This is distracting as it is by itself (if I have them opened side by side and want to quickly see the changes in editor I need to switch back to 3D every time I change something), and it's also a big problem when using an external editor and trying to hot-reload assets in a running game, because vscode keeps maximizing and needs to be constantly minimized

https://github.com/godotengine/godot/assets/60579014/7152dc05-94c2-452d-b328-0895322128fc

### Steps to reproduce

Open the MRP, the scene inside of it and the script, and try re-exporting the cube

### Minimal reproduction project (MRP)

[MRP_reimport_script_editor.zip](https://github.com/godotengine/godot/files/15048396/MRP_reimport_script_editor.zip)

### LINKED ISSUE #93481: Pressing Cancel while exporting project does nothing
### Tested versions

4.3 beta2 and earlier

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/92740b33-0803-4287-98a4-0c3401072961

There is no way to cancel the export. You have to kill the editor and restart.

### Steps to reproduce

1. Export the project
2. Press Cancel while exporting is in progress

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #96994: Editor window steals focus multiple times while launching
### Tested versions

4.4 dev2

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

After #93064 the editor will show multiple progress dialogs while launching. Each time new dialog appears, the main window will steal focus, making it almost impossible to do anything while a project is loading. It's especially annoying during long reimports, because the window is focused multiple times with long intervals between operation.

The editor should not steal window focus while doing its background tasks. It's useless and disturbing.

### Steps to reproduce

0. Delete .godot folder for better result
1. Open a medium/big project that takes a while to launch
2. Minimize Godot and try to do something else
3. Godot will keep interrupting whatever else you are trying to do

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by KoBeWi**
Same as #97009, but I made the dialog appear on currently focused window.

Fixes #96994
Fixes #90944

### CODE REVIEW

**Comment by JekSun97** [comment]
I sometimes see window focus issues when opening a project, is it possible to carry this over to importing a project?

**Comment by Hilderin** [comment]
I'm using Godot with this PR for a couple of days and it works great. It's very nice that Godot can reimport assets in the background without stealing the focus!

The only issue I got so far is in the Export window. While exporting, the buttons are still available. I was able to close the export window during the exportation which seems to pause the exportation. It resumed when reopening the export window.

**Comment by Hilderin** [comment]
I'm using this PR for the last couple of days and it works great so far. It's very nice to be able to import assets in the background without Godot stealing the focus.

The only issue so far is the "Export Project..." button in the Export window. I need to do it twice for the exportation to run. Also, if I press only one time, select the file and close the window, the next time the Export window is opened, the exportation is executed.

**Comment by KoBeWi** [comment]
Should be fixed now, although I had to modify EditorFileDialog to emit `file_selected` before hiding. This might break some code.

**Comment by Hilderin** [comment]
> Should be fixed now, although I had to modify EditorFileDialog to emit file_selected before hiding. This might break some code.

I'm really worry about this modification, that means that the editor file dialog will still be opened when saving a scene or when opening almost anything in the editor.

Just to be sure, I reverted locally the modifications in `ProjectExportDialog` and everything seems to work fine. What was the problem you encountered in this particular popup exactly?

**Comment by KoBeWi** [comment]
Ok I reverted the EditorExport/FileDialog changes. The issue I had before doesn't seem to be happening anymore.

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -340,6 +340,19 @@ void EditorNode::_update_title() {
...
+	// only when the progress dialog is visible.
+	// We need to discard all key events to disable all shortcuts while the progress
+	// dialog is displayed, simulating an exclusive popup. Mouse events are
+	// captured by a full-screen container in front of the EditorNode in ProgressDialog,
+	// allowing interaction with the actual dialog where a Cancel button may be visible.
+	Ref<InputEventKey> k = p_event;
+	if (k.is_valid()) {
+		get_tree()->get_root()->set_input_as_handled();
+	}
+}
```
Comment (akien-mga) [inline editor/editor_node.cpp:354]: How does this work if you're trying to press the Cancel button of ProgressDialog with key events?

Comment (KoBeWi) [reply editor/editor_node.cpp:354]: Looks like you can't.
However canceling was broken before (at least during export: #93481) and now you can cancel with mouse, so it's still an improvement.

**Comment by Hilderin** [comment]
I detected another wierd side effect. When a sub scene is used in a main scene and both scenes are opened, when switching back to the main scene, the progress "Updating scene" appears and after that the first right click displays and context menu of the scene tab. My guess is that `get_tree()->get_root()->set_input_as_handled();` causes the focus out of the scene tab from being triggered.
I tested on Godot master without this PR and I'm not able to reproduce.


https://github.com/user-attachments/assets/292faf80-2f17-45b4-9da5-901ba3fee13e

**Comment by KoBeWi** [comment]
No idea what causes it. Hiding the dialog and removing all input/processing overrides does not fix the issue. It's like it's caused by the existence of the dialog alone.

**Comment by Hilderin** [comment]
The issue is caused because `Viewport::_gui_input_event` does not process the button release and `gui.mouse_focus` is never reset to null.
I'm not sure why, but when I comment the line `DisplayServer::get_singleton()->process_events();`  in `ProgressDialog::_update_ui` is issue is fixed. Is that line still needed? I'm not sure but this line seems to drop events.

**Comment by KoBeWi** [comment]
It's part of the code that manually processes SceneTree. It's probably supposed to keep the dialog responsive and allow to cancel during processing.
...Except it doesn't work. I don't know what changed, but #93481 stays unresolved (it was being fixed in my previous tests).

I'll just remove this line.

**Comment by Hilderin** [comment]
Nice, it fixes the issue. I'll continue working in Godot using this PR to see if I spot other side effects.

**Comment by Hilderin** [comment]
Unfortunately, the last modification brings a "semi-bad" side effect. The editor window is unresponsive while the progress dialog is displayed. I retested after readding the `DisplayServer::get_singleton()->process_events();` and the editor is responsive with the line.
image

**Comment by Hilderin** [comment]
Ok, I found a workaround... The issue is that `gui.mouse_focus` is still set in the `ViewPort`. I saw that there's a private method: `Viewport::_drop_mouse_focus()` that resets it.
And `Viewport::_drop_mouse_focus()` is called in `set_disable_input`.

So adding these lines in `ProgressDialog::_popup` fixes the issue of the right click after the save of a used scene and changing to the main scene:
```cpp
...
reparent(current_window);

bool window_is_input_disabled = current_window->is_input_disabled();
current_window->set_disable_input(!window_is_input_disabled);
current_window->set_disable_input(window_is_input_disabled);

show();
```

Note that there's probably a more elegant way to fix the issue but it works.

**Review by Hilderin — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
