### PR TITLE
Fix various memory leaks and errors

### LINKED ISSUE #17767: Memory leak in SceneTree setting fallback environment
**Godot version:**
`master` branch commit 928cdb4f8a72c2de5751cddd3205c2a3c09e6f6d

**Issue description:**
Just by opening and closing the editor, there are three calls to:
https://github.com/godotengine/godot/blob/928cdb4f8a72c2de5751cddd3205c2a3c09e6f6d/drivers/gles3/rasterizer_scene_gles3.cpp#L783-L788

that are currently leaking.

These currently show up in `valgrind`:

```
==27093== 384 bytes in 1 blocks are definitely lost in loss record 199 of 309
==27093==    at 0x4C2CEDF: malloc (vg_replace_malloc.c:299)
==27093==    by 0x1C6F931: Memory::alloc_static(unsigned long, bool) (memory.cpp:83)
==27093==    by 0x935969: RasterizerSceneGLES3::environment_create() (rasterizer_scene_gles3.cpp:785)
==27093==    by 0x196876F: VisualServerWrapMT::environment_create() (visual_server_wrap_mt.h:406)
==27093==    by 0x16F3F70: Environment::Environment() (environment.cpp:1181)
==27093==    by 0xFF7C2C: Object* ClassDB::creator<Environment>() (class_db.h:142)
==27093==    by 0x17199C1: ResourceInteractiveLoaderText::poll() (scene_format_text.cpp:556)
==27093==    by 0x1CD5261: ResourceFormatLoader::load(String const&, String const&, Error*) (resource_loader.cpp:138)
==27093==    by 0x1CD4ABA: ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) (resource_loader.cpp:173)
==27093==    by 0x1CD4DF0: ResourceLoader::load(String const&, String const&, bool, Error*) (resource_loader.cpp:218)
==27093==    by 0x1093622: SceneTree::SceneTree() (scene_tree.cpp:2367)
==27093==    by 0x2DBE00: Main::start() (main.cpp:1365)
==27093== 
==27093== 384 bytes in 1 blocks are definitely lost in loss record 200 of 309
==27093==    at 0x4C2CEDF: malloc (vg_replace_malloc.c:299)
==27093==    by 0x1C6F931: Memory::alloc_static(unsigned long, bool) (memory.cpp:83)
==27093==    by 0x935969: RasterizerSceneGLES3::environment_create() (rasterizer_scene_gles3.cpp:785)
==27093==    by 0x196876F: VisualServerWrapMT::environment_create() (visual_server_wrap_mt.h:406)
==27093==    by 0x16F3F70: Environment::Environment() (environment.cpp:1181)
==27093==    by 0xE474F0: SpatialEditor::SpatialEditor(EditorNode*) (spatial_editor_plugin.cpp:4966)
==27093==    by 0xE4CDE7: SpatialEditorPlugin::SpatialEditorPlugin(EditorNode*) (spatial_editor_plugin.cpp:5346)
==27093==    by 0xB1397B: EditorNode::EditorNode() (editor_node.cpp:5772)
==27093==    by 0x2DD4D3: Main::start() (main.cpp:1449)
==27093==    by 0x2BE295: main (godot_x11.cpp:54)
==27093== 
==27093== 384 bytes in 1 blocks are definitely lost in loss record 201 of 309
==27093==    at 0x4C2CEDF: malloc (vg_replace_malloc.c:299)
==27093==    by 0x1C6F931: Memory::alloc_static(unsigned long, bool) (memory.cpp:83)
==27093==    by 0x935969: RasterizerSceneGLES3::environment_create() (rasterizer_scene_gles3.cpp:785)
==27093==    by 0x196876F: VisualServerWrapMT::environment_create() (visual_server_wrap_mt.h:406)
==27093==    by 0x16F3F70: Environment::Environment() (environment.cpp:1181)
==27093==    by 0xFF7C2C: Object* ClassDB::creator<Environment>() (class_db.h:142)
==27093==    by 0x17199C1: ResourceInteractiveLoaderText::poll() (scene_format_text.cpp:556)
==27093==    by 0x1CD5261: ResourceFormatLoader::load(String const&, String const&, Error*) (resource_loader.cpp:138)
==27093==    by 0x1CD4ABA: ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) (resource_loader.cpp:173)
==27093==    by 0x1CD4DF0: ResourceLoader::load(String const&, String const&, bool, Error*) (resource_loader.cpp:218)
==27093==    by 0x1B9BB1E: Resource::reload_from_file() (resource.cpp:130)
==27093==    by 0xAF416B: EditorNode::_fs_changed() (editor_node.cpp:455)
```

### LINKED ISSUE #30224: Memory leak shown by DocData::generate
**Godot version:**
3.2.dev.custom_build. d40dbd6d1

**Issue description:**
Latest docdata changes shows two leaks:
```
160 bytes in 1 blocks are definitely lost in loss record 110 of 152
   at 0x5A2874F: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x384EAEF: Memory::alloc_static(unsigned long, bool) (memory.cpp:85)
   by 0x384EA98: operator new(unsigned long, char const*) (memory.cpp:42)
   by 0x1E944FA: RasterizerStorageGLES3::gi_probe_create() (rasterizer_storage_gles3.cpp:5672)
   by 0x34AB0F4: VisualServerRaster::gi_probe_create() (visual_server_raster.h:345)
   by 0x34E6021: VisualServerWrapMT::gi_probe_create() (visual_server_wrap_mt.h:281)
   by 0x2C57206: GIProbe::GIProbe() (gi_probe.cpp:569)
   by 0x291833C: Object* ClassDB::creator<GIProbe>() (class_db.h:146)
   by 0x368CE71: ClassDB::instance(StringName const&) (class_db.cpp:540)
   by 0x3691C56: ClassDB::class_get_default_property_value(StringName const&, StringName const&, bool*) (class_db.cpp:1415)
   by 0x23041BD: DocData::generate(bool) (doc_data.cpp:255)
   by 0x200F89C: EditorHelp::generate_doc() (editor_help.cpp:1419)

240 bytes in 1 blocks are definitely lost in loss record 117 of 152
   at 0x5A28DBF: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x1796A2C: BulletPhysicsServer::soft_body_create(bool) (bullet_physics_server.cpp:885)
   by 0x2D29D32: SoftBody::SoftBody() (soft_body.cpp:702)
   by 0x2918CA1: Object* ClassDB::creator<SoftBody>() (class_db.h:146)
   by 0x368CE71: ClassDB::instance(StringName const&) (class_db.cpp:540)
   by 0x3691C56: ClassDB::class_get_default_property_value(StringName const&, StringName const&, bool*) (class_db.cpp:1415)
   by 0x23041BD: DocData::generate(bool) (doc_data.cpp:255)
   by 0x200F89C: EditorHelp::generate_doc() (editor_help.cpp:1419)
   by 0x2078293: EditorNode::EditorNode() (editor_node.cpp:5255)
   by 0x13DB841: Main::start() (main.cpp:1613)
   by 0x13A06AD: main (godot_x11.cpp:54)

Conditional jump or move depends on uninitialised value(s)
   at 0x2C98270: Particles::set_emitting(bool) (particles.cpp:51)
   by 0x2C9D0EE: Particles::Particles() (particles.cpp:414)
   by 0x2918481: Object* ClassDB::creator<Particles>() (class_db.h:146)
   by 0x368CE71: ClassDB::instance(StringName const&) (class_db.cpp:540)
   by 0x3691C56: ClassDB::class_get_default_property_value(StringName const&, StringName const&, bool*) (class_db.cpp:1415)
   by 0x23041BD: DocData::generate(bool) (doc_data.cpp:255)
   by 0x200F89C: EditorHelp::generate_doc() (editor_help.cpp:1419)
   by 0x2078293: EditorNode::EditorNode() (editor_node.cpp:5255)
   by 0x13DB841: Main::start() (main.cpp:1613)
   by 0x13A06AD: main (godot_x11.cpp:54)

Conditional jump or move depends on uninitialised value(s)
   at 0x2E59606: Particles2D::set_emitting(bool) (particles_2d.cpp:45)
   by 0x2E5E0FC: Particles2D::Particles2D() (particles_2d.cpp:413)
   by 0x291A0B0: Object* ClassDB::creator<Particles2D>() (class_db.h:146)
   by 0x368CE71: ClassDB::instance(StringName const&) (class_db.cpp:540)
   by 0x3691C56: ClassDB::class_get_default_property_value(StringName const&, StringName const&, bool*) (class_db.cpp:1415)
   by 0x23041BD: DocData::generate(bool) (doc_data.cpp:255)
   by 0x200F89C: EditorHelp::generate_doc() (editor_help.cpp:1419)
   by 0x2078293: EditorNode::EditorNode() (editor_node.cpp:5255)
   by 0x13DB841: Main::start() (main.cpp:1613)
   by 0x13A06AD: main (godot_x11.cpp:54)

Conditional jump or move depends on uninitialised value(s)
   at 0x381A50F: VariantWriter::write(Variant const&, Error (*)(void*, String const&), void*, String (*)(void*, Ref<Resource> const&), void*) (variant_parser.cpp:1585)
   by 0x381F38C: VariantWriter::write_to_string(Variant const&, String&, String (*)(void*, Ref<Resource> const&), void*) (variant_parser.cpp:1958)
   by 0x37A0643: Variant::get_construct_string() const (variant.cpp:3234)
   by 0x2304368: DocData::generate(bool) (doc_data.cpp:270)
   by 0x200F89C: EditorHelp::generate_doc() (editor_help.cpp:1419)
   by 0x2078293: EditorNode::EditorNode() (editor_node.cpp:5255)
   by 0x13DB841: Main::start() (main.cpp:1613)
   by 0x13A06AD: main (godot_x11.cpp:54)
```
** Steps to reproduce**
1. Open new Godot project

### PR DESCRIPTION
**Pull request by bojidar-bg**
Fixes #30224.
Likely fixes #17767 as well.
Addresses leaks in https://github.com/godotengine/godot/issues/27265#issuecomment-496263636. 
Fixes `set_process_priority` error introduced by #29980.
Also, fix a random leak from `GDNativeLibrary`, by rewriting the Map similar to `ClassDB::default_values`.

And that's about it!

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: modules/gdnative/gdnative.cpp [hunk 1]
```diff
@@ -48,7 +48,7 @@ static const bool default_reloadable = true;
 // Defined in gdnative_api_struct.gen.cpp
 extern const godot_gdnative_core_api_struct api_struct;
 
-Map<String, Vector<Ref<GDNative> > > *GDNativeLibrary::loaded_libraries = NULL;
```
Comment (hbina) [inline modules/gdnative/gdnative.cpp]: What was the rationale behind using a variable this way?
Just trying to learn :)

Comment (bojidar-bg) [reply modules/gdnative/gdnative.cpp]: I'm not sure exactly. Both usages use almost the same amount of memory, and while the previous approach defers the allocation to when it is actually needed, the size of an empty Map is pretty small.

I would guess that the writer of the initial code got confused by the way constructors of static variables are run, and decided to just write it with a pointer.

(CC @karroffel)

Comment (karroffel) [reply modules/gdnative/gdnative.cpp]: I think I did it this way because I had problems with static initialization at the time, apparently I did something weird as it seems to work here properly.

**Comment by akien-mga** [comment]
Thanks!
