### PR TITLE
Fix crash in `command_queue_mt` due to destruction of wrong object

### LINKED ISSUE #113445: Threaded loading is broken in several ways
### Tested versions

- Reproducible in v4.6.dev5.official [f5918a9d3]
- Not reproducible in v4.6.dev4.official [bd2ca13c6]

### System information

Godot v4.6.dev5 - Arch Linux #1 ZEN SMP PREEMPT_DYNAMIC Mon, 24 Nov 2025 15:21:16 +0000 on Wayland - Wayland display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 570 Series (RADV POLARIS10) - AMD Ryzen 7 5700X 8-Core Processor (16 threads) - 31.24 GiB memory

### Issue description

When using `ResourceLoader.load_threaded_*` functions to load scenes with WorldEnvironment, one of the following may happen:

1. Glow effect breaks, causing it to look heavily overexposed (and sometimes whites out the clusters completely, making it look pixelated)
2. Glow effect breaks, causing it to not work at all
3. The project crashes when loading the scene with no error in the Output dock, even if verbose stdout is enabled

### Steps to reproduce

1. Open MRP
2. Start the project a couple of times. It will load `to_load.tscn` using `ResourceLoader.load_threaded_request` after a second of delay. See `load_second_scene.gd` for details
3. You might get all of these in a row, or just one, depending on your luck
4. In `load_second_scene.gd`, replace the functions with the commented-out versions that just use `load` and try again
5. Everything should work as expected

### Minimal reproduction project (MRP)

[bloomtest_2025-12-02_15-08-39.zip](https://github.com/user-attachments/files/23880432/bloomtest_2025-12-02_15-08-39.zip)

### PR DESCRIPTION
**Pull request by brycehutchings**
This is a possible way to fix the issue in #113445.

I narrowed the problem down to the usage of this method being queued on the command_queue:

```c++
void environment_set_glow(RID p_env, bool p_enable, Vector<float> p_levels, float p_intensity, float p_strength, float p_mix, float p_bloom_threshold, RS::EnvironmentGlowBlendMode p_blend_mode, float p_hdr_bleed_threshold, float p_hdr_bleed_scale, float p_hdr_luminance_cap, float p_glow_map_strength, RID p_glow_map)
```

What I believe was happening was the `Command` was getting memcpy'd into a temporary buffer but the invocation of the callback uses std::move which can cause these parameters to become mutated:

```cpp
_FORCE_INLINE_ R call_impl(IndexSequence<I...>) {
	// Move out of the Tuple, this will be destroyed as soon as the call is complete.
	return (instance->*method)(std::move(get<I>())...);
                               ^^^^^^^^^
}
```

And so the Vector<float> in the copied memory was getting mutated by this std::move, but the original copy in `command_mem` was not updated and so when it was destroyed it also tried to free the memory pointed to by the Vector not knowing it had already been freed.

To handle this, we need to follow the rules for relocating objects and destroy the new copy of the Command object and not the original one.

I tested this both with the MRP and with TPS demo. I also ran the unit tests with `--test -ts="[CommandQueue]"`

Fixes https://github.com/godotengine/godot/issues/113445

### CODE REVIEW

File: core/templates/command_queue_mt.h [hunk 1]
```diff
@@ -101,6 +106,10 @@ class CommandQueueMT {
 		// This method exists so we can call it in the parameter pack expansion in call_impl.
 		template <size_t I>
 		_FORCE_INLINE_ auto &get() { return ::tuple_get<I>(args); }
+
+		CommandBase *move_to(void *p_dst) override {
+			return new (p_dst) CommandRet(std::move(*this));
```
Comment (Ivorforce) [inline core/templates/command_queue_mt.h]: Please use `memnew_placement` (in other places as well):

```suggestion
			return memnew_placement(p_dst, CommandRet(std::move(*this)));
```

File: core/templates/command_queue_mt.h [hunk 2]
```diff
@@ -164,46 +173,43 @@ class CommandQueueMT {
...
-
 			// Protect against race condition between this thread
 			// during the call to the command and other threads potentially
 			// invalidating the pointer due to reallocs.
-			memcpy(cmd_backup, (char *)cmd, size);
+			CommandBase *cmd_copy;
+			{
+				CommandBase *cmd = reinterpret_cast<CommandBase *>(&command_mem[flush_read_ptr]);
+				cmd_copy = cmd->move_to(&cmd_copy_mem);
+				cmd->~CommandBase();
```
Comment (Ivorforce) [inline core/templates/command_queue_mt.h]: If you're just using `std::move`, and then calling the destructor, that means any access of `command_mem` as `CommandBase *` is now invalid (because the destructor has already been called).

In this case, you might as well use relocation semantics (call `memcpy` and don't call the destructor). Which would put us back to where we started.

Can you explain why changing to move semantics here should help if `command_mem` is never accessed as `CommandBase *` after this anyway?

Comment (brycehutchings) [reply core/templates/command_queue_mt.h]: From what I understood, only "trivially copyable" types can be memcpy'd safely according to C++ standard. See https://en.cppreference.com/w/cpp/types/is_trivially_copyable.html:

> Objects of trivially-copyable types that are not potentially-overlapping subobjects are the only C++ objects that may be safely copied with [std::memcpy](https://en.cppreference.com/w/cpp/string/byte/memcpy.html) [...]

Since command_queue_mt is handling non-trivially copyable types, I didn't think any solution that involves memcpy is technically correct. I can imagine a C++ object that would not work correctly with memcpy (imagine one that has a member field that points to another member field. after a memcpy, that pointer will still point to the old location and not the new location). So I wanted to make a fix that stayed away from "undefined behavior" territory. 

However, in researching things to reply here, I see that it looks like Godot uses `realloc` which I would not have considered safe with C++ types since it's essentially doing a memcpy under the hood. So I am wondering if Godot types are generally written in a way that allows for memcpy to work in practice?

All that to say, I think what you say is in line with how Godot is written and I can change this to memcpy and not destroy the original copy.

Comment (Ivorforce) [reply core/templates/command_queue_mt.h]: > From what I understood, only "trivially copyable" types can be memcpy'd safely according to C++ standard. See https://en.cppreference.com/w/cpp/types/is_trivially_copyable.html:

This isn't totally true. Another use-case for `memcpy` is [trivial relocation](https://open-std.org/JTC1/SC22/WG21/docs/papers/2020/p1144r5.html), a concept that has only recently been formalized.

For Godot, we have made the decision to assume all (non-heap) objects must be trivially relocatable to make use of `memcpy` for improved speed (see https://github.com/godotengine/godot/issues/100509).

Comment (brycehutchings) [reply core/templates/command_queue_mt.h]: Thank you for explaining! I'll get this PR fixed up shortly

File: core/templates/command_queue_mt.h (hunk 1 above)
Comment (brycehutchings) [reply core/templates/command_queue_mt.h]: Thanks I updated this!

File: core/templates/command_queue_mt.h [hunk 3]
```diff
@@ -164,44 +164,39 @@ class CommandQueueMT {
 			return;
 		}
 
-		char cmd_backup[MAX_COMMAND_SIZE];
+		char cmd_local_mem[MAX_COMMAND_SIZE];
```
Comment (blueskythlikesclouds) [inline core/templates/command_queue_mt.h]: Is this guaranteed to be aligned to what the commands need?

Comment (brycehutchings) [reply core/templates/command_queue_mt.h]: I'm not sure if it is guaranteed so I have added it. It looks like padding is added to the end of each command to ensure 8 byte/uint64_t alignment so I matched that here.

**Review by RandomShaper — APPROVED** [review]
Excellent catch!

I also like the renames and I'm happy the 'handle potential realloc' statements are no longer needed.

File: core/templates/command_queue_mt.h [hunk 4]
```diff
@@ -164,44 +164,39 @@ class CommandQueueMT {
 			return;
 		}
 
-		char cmd_backup[MAX_COMMAND_SIZE];
+		alignas(uint64_t) char cmd_local_mem[MAX_COMMAND_SIZE];
```
Comment (Ivorforce) [inline core/templates/command_queue_mt.h:167]: Why not use `alignas(CommandBase)`?

Comment (RandomShaper) [reply core/templates/command_queue_mt.h:167]: I think `uint64_t` is conceptually closer to what is done in `create_command()`, which is aligning to 8 raw bytes. I'd say both would ideally stay in that "conceptual sync," so if we change one, we should also change the other as well.

Comment (akien-mga) [reply core/templates/command_queue_mt.h:167]: I'll merge as is to fix the regression for dev6 (planning a build today), but this can be tweaked further later if needed.

**Comment by akien-mga** [comment]
Thanks!
