### PR TITLE
Make `--doctool` create directories if they don't exist

### LINKED ISSUE #17297: --doctool should create directories if they don't exist
Running `godot --doctool` outside the build directory has this output:

```
Loading docs..
Loading docs from: ./modules/gdnative/doc_classes
Loading docs from: ./modules/stb_vorbis/doc_classes
Loading docs from: ./modules/opus/doc_classes
Loading docs from: ./modules/bullet/doc_classes
Loading docs from: ./modules/gdscript/doc_classes
Loading docs from: ./modules/gridmap/doc_classes
Loading docs from: ./modules/mobile_vr/doc_classes
Loading docs from: ./modules/enet/doc_classes
Loading docs from: ./modules/regex/doc_classes
Loading docs from: ./modules/theora/doc_classes
Loading docs from: ./modules/webm/doc_classes
Loading docs from: ./modules/visual_script/doc_classes
Loading docs from: ./doc/classes
Merging docs..
Erasing old docs at: ./doc/classes
Erasing old docs at: ./modules/bullet/doc_classes
Erasing old docs at: ./modules/enet/doc_classes
Erasing old docs at: ./modules/gdnative/doc_classes
Erasing old docs at: ./modules/gdscript/doc_classes
Erasing old docs at: ./modules/gridmap/doc_classes
Erasing old docs at: ./modules/mobile_vr/doc_classes
Erasing old docs at: ./modules/opus/doc_classes
Erasing old docs at: ./modules/regex/doc_classes
Erasing old docs at: ./modules/stb_vorbis/doc_classes
Erasing old docs at: ./modules/theora/doc_classes
Erasing old docs at: ./modules/visual_script/doc_classes
Erasing old docs at: ./modules/webm/doc_classes
Generating new docs..
ERROR: save_classes: Can't write doc file: ./doc/classes/@GDScript.xml
   At: editor/doc/doc_data.cpp:964.
```
It gives up if one of the directory paths doesn't exist, so I have to manually create all of them just to get the command to succeed. Is there any reason why the directories aren't created automatically?

### PR DESCRIPTION
**Pull request by Calinou**
This prevents errors due to missing directories when generating engine documentation.

This closes #17297.

### CODE REVIEW

File: main/main.cpp [hunk 1]
```diff
@@ -1399,6 +1398,11 @@ bool Main::start() {
 		}
 
 		String index_path = doc_tool.plus_file("doc/classes");
+		// Create the directory if it doesn't exist
+		DirAccess *da = DirAccess::create_for_path(index_path);
```
Comment (Calinou) [inline main/main.cpp]: Is this the "best" way to create directories in this situation? I saw a `DirAccessRef` instance in a block a few lines above, but here, I based it on the `make_dir_recursive()` implementation in https://github.com/Calinou/godot/blob/888c9b3066b170cb9d1e7171a1700b5c2b654948/core/bind/core_bind.cpp#L2260-L2271

Comment (akien-mga) [reply main/main.cpp]: It seems to be done this way in various places indeed, so that seems fine.

Comment (akien-mga) [reply main/main.cpp]: Though I don't know if we should always attempt to recreate the directory even if it already exists. And a similar operation would be needed for modules doc directories in the for loop above. Last I played around with this I got crashes and gave up :P

**Comment by akien-mga** [comment]
Should be rebased to solve merge conflicts, and it also needs extra code to create module-specific doc folders if declared but missing.

**Comment by akien-mga** [comment]
Thanks!
