### PR TITLE
Accept global classes  for `MainLoop` type in project settings

### LINKED ISSUE #35822: Project Setting application/run/main_loop_type: existing classes not found
**Godot version:** 3.2

**OS/device including version:** Win 8.1

**Issue description:**

It appears as if the project setting `application/run/main_loop_type` can't be set to any valid custom class. Any setting will result in the error message "Error: MainLoop type doesn't exist: `main_loop_type`" and a crash.

The script checks for the existence of the class in ClassDB. Maybe not all scripts have been loaded to ClassDB at this point of time?

**Steps to reproduce:**

1. Create Project.
2. Create class extending MainLoop. Exmple:

```
extends SceneTree

class_name MyClass


var time_elapsed = 0

func _initialize():
	print("Initialized:")
	print("  Starting time: %s" % str(time_elapsed))
```
3. Set project setting `application/run/main_loop_type` to `MyClass`.
4. Run.

### PR DESCRIPTION
**Pull request by Xrayez**
Fixes #35822.
Helps godotengine/godot-proposals#1349.

The `application/run/main_loop_type` setting can handle custom global classes now (classes exposed with `class_name` keyword).  For instance: `MySceneTree`.

The setting's default is changed from empty to `SceneTree` as to give some hint of what kind of input is accepted for the main loop type.

Main Loop Type

Tested on both editor and release builds.

Some custom scene tree class:
```gdscript
class_name MySceneTree extends SceneTree

func _initialize():
	print("MySceneTree startup!")

func _finalize():
	print("MySceneTree cleanup!")

func _iteration(_delta):
	return false

func _drop_files(files, from_screen):
	print(files, " ", from_screen)
```

Test project:

[global_class_main_loop.zip](https://github.com/godotengine/godot/files/5058401/global_class_main_loop.zip)

### CODE REVIEW

**Comment by dalexeev** [comment]
Note that you can do this:

```gdscript
get_tree().set_script(preload("res://my_scene_tree.gd"))
```

```gdscript
# my_scene_tree.gd
extends SceneTree

func change_scene(path):
    print("--- %s ---" % path)
    return .change_scene(path)
```

This will work as expected.

**Comment by Xrayez** [comment]
`get_tree` has to be already initialized to do this. You'd miss the ability to receive the `_initialize` callback:

https://github.com/godotengine/godot/blob/dc90b17691b574967895546568e2966e655f9cd0/core/os/main_loop.cpp#L63-L71

If your script inherits directly from `MainLoop` (not `SceneTree`), then `get_tree()` is likely to return `null` as well, so there would be hardly a way to override this via script.

File: main/main.cpp [hunk 1]
```diff
@@ -1855,9 +1855,23 @@ bool Main::start() {
 		} else {
 			return false;
 		}
-
-	} else {
-		main_loop_type = GLOBAL_DEF("application/run/main_loop_type", "");
+	} else { // Not based on script path.
+		if (!editor && !ClassDB::class_exists(main_loop_type) && ScriptServer::is_global_class(main_loop_type)) {
```
Comment (Xrayez) [inline main/main.cpp:1859]:
```suggestion
		if (!ClassDB::class_exists(main_loop_type) && ScriptServer::is_global_class(main_loop_type)) {
```

Technically it's possible to override the main loop of the editor itself upon restart, but if there are any errors (wrong base type, invalid script etc), then the editor will always crash with an alert (you'd have to modify `project.godot` to revert to previous behavior). 😅

**Comment by akien-mga** [comment]
Thanks!

**Comment by eon-s** [comment]
Can this be added to 3.x too or this depends on GDScript changes?

**Comment by Xrayez** [comment]
@eon-s I've tried to apply the same patch to 3.2, patch fails, so needs a dedicated PR for 3.2. If @akien-mga is fine about these changes for 3.2, I could certainly make one. 🙂

I think nothing has changed fundamentally in terms of global classes in 4.0.

**Comment by RimaitosLab** [comment]
Hi @Xrayez,
I'm currently trying to run a piece of code before any Node entered the Scene Tree.
In search of a solution, I stumbled upon the possibility to set your own MainLoop. I wanted to set a MainLoop which extends SceneTree but overrides the _initialize() method.
But I receive the error "Error: MainLoop type doesn't exist: MySceneTree".

I'm running Godot v3.3.2.stable on Linux.

I tried to run your example which failed to parse the project.godot file because the '@' raised a "ConfigFile parse error at [omitted]/project.godot:6: Unexpected character.". After manually editing the project.godot file, the example throws the same error as my previous try.

I hope you can help me with that.
Thanks in advance!

**Comment by Xrayez** [comment]
> I'm running Godot v3.3.2.stable on Linux.

@RimaitosLab this feature was not backported to Godot `3.x` branch, that's why you receive the error, but this is currently implemented in Godot 4.x (which is in development, not released yet).

As I said earlier, it's possible to backport the feature, but I need an approval from the maintainers before doing the backport. 🙂

**Comment by RimaitosLab** [comment]
oh sorry, it seems like I misunderstood the conversation.
Well it seems like I'm gonna learn how to compile Godot 😃

**Comment by tommyZZM** [comment]
hello @Xrayez @RimaitosLab @eon-s ~

I've tried to backport this feature to 3.x,  And it works fine successfully for me. 😄 

I've created a pull request here (https://github.com/godotengine/godot/pull/52438)
