### PR TITLE
Fix editor crash when shader has incorrect global array declaration

### LINKED ISSUE #90683: Editor Crash When Using Invalid Array Initialization in Shader
### Tested versions

- Reproducible in: v4.2.1.stable.mono

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.5186) - 12th Gen Intel(R) Core(TM) i7-12700 (20 Threads)

### Issue description

Having this file shown in the code editor will immediately crash the entire editor. 

### Steps to reproduce

1. Create a Shader with the following content:
```
shader_type spatial;
const bool array[1] = bool[];;
```
2. Open it in the code editor
2. Profit(?)

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/godotengine/godot/files/14974062/MRP.zip)

### PR DESCRIPTION
**Pull request by jsjtxietian**
Trying to fix https://github.com/godotengine/godot/issues/90683

The crash happens around the change in `shader_compiler.cpp`, in that condition, `cnode->array_declarations[0].initializer` has size 0 and thus use `i=1` to index it will crash the editor. I leave it as a safe guard there.

Note that `const bool array[1] = bool[];;` will cause the crash but `const bool array[1] = bool[];` won't (just trigger `Expected a ',' or ';'`), the changes I made in `shader_language.cpp` prevent this by simply don't allow a global const array to be defined without initialization, I checked the doc it didn't say whether it's legal or not, so it might not be a good idea. Feel free to correct me.

### CODE REVIEW

File: servers/rendering/shader_compiler.cpp [hunk 1]
```diff
@@ -1107,7 +1107,11 @@ String ShaderCompiler::_dump_node_code(const SL::Node *p_node, int p_level, Gene
 					} else {
 						code += "";
 					}
-					code += _dump_node_code(cnode->array_declarations[0].initializer[i], p_level, r_gen_code, p_actions, p_default_actions, p_assigning);
+					if (cnode->array_declarations[0].initializer.size() < i + 1) {
+						code += "";
+					} else {
+						code += _dump_node_code(cnode->array_declarations[0].initializer[i], p_level, r_gen_code, p_actions, p_default_actions, p_assigning);
+					}
```
Comment (RandomShaper) [inline servers/rendering/shader_compiler.cpp:1114]:
```suggestion
					if (i < cnode->array_declarations[0].initializer.size()) {
						code += _dump_node_code(cnode->array_declarations[0].initializer[i], p_level, r_gen_code, p_actions, p_default_actions, p_assigning);
					}
```

Comment (jsjtxietian) [reply servers/rendering/shader_compiler.cpp:1114]: Thanks!

File: servers/rendering/shader_language.cpp [hunk 2]
```diff
@@ -9383,6 +9383,9 @@ Error ShaderLanguage::_parse_shader(const HashMap<StringName, FunctionInfo> &p_f
 										_set_error(RTR("Array size mismatch."));
 										return ERR_PARSE_ERROR;
 									}
+								} else {
+									_set_expected_error("(,{");
```
Comment (Chaosus) [inline servers/rendering/shader_language.cpp:9387]:
```suggestion
									_set_expected_error("(");
```

`curly` is handled by previous `if` + this is incorrect pass of multiple arguments to `_set_expected_error`.

**Review by Chaosus — CHANGES_REQUESTED** [review]
Also, please add

```
else {
_set_expected_error("(");
}
```

after the 

https://github.com/godotengine/godot/blob/4e5ed0bbfb56f0a71eb61c868f965476652c23df/servers/rendering/shader_language.cpp#L7359-L7402

(its local function case of the same problem)

File: servers/rendering/shader_language.cpp (hunk 2 above)
Comment (jsjtxietian) [reply servers/rendering/shader_language.cpp:9387]: Thanks!

**Review by Chaosus — APPROVED** [review]

File: servers/rendering/shader_compiler.cpp [hunk 3]
```diff
@@ -1107,7 +1107,9 @@ String ShaderCompiler::_dump_node_code(const SL::Node *p_node, int p_level, Gene
 					} else {
 						code += "";
 					}
-					code += _dump_node_code(cnode->array_declarations[0].initializer[i], p_level, r_gen_code, p_actions, p_default_actions, p_assigning);
+					if (i < cnode->array_declarations[0].initializer.size()) {
+						code += _dump_node_code(cnode->array_declarations[0].initializer[i], p_level, r_gen_code, p_actions, p_default_actions, p_assigning);
+					}
```
Comment (Chaosus) [inline servers/rendering/shader_compiler.cpp:1112]: To be honest, I would leave as it is for now in this PR, and fix it in other places where initializer used in separate PR. Also, maybe this need to be wrapped with `ERR_FAIL_COND` eg.  `if (ERR_FAIL_COND(i >= cnode->array_declarations[0].initializer.size())`

Comment (Chaosus) [inline servers/rendering/shader_compiler.cpp:1112]: I would remove this check - if it fails - it's signification that something bad on the shader_language side, and it needs to be fixed there.

Comment (jsjtxietian) [reply servers/rendering/shader_compiler.cpp:1112]: Done

**Comment by akien-mga** [comment]
Thanks!
