### PR TITLE
Fixes `OS.get_unique_id()` string not getting printed properly

### LINKED ISSUE #61023: [Godot4] OS.get_unique_id() bug?
### Godot version

v4.0.alpha8.official [cc3ed63af]

### System information

Windows 10, 64bit

### Issue description

In Godot 4:
捕获
In Godot 3.4:
捕获2

### Steps to reproduce

Please run the reproduction project.

### Minimal reproduction project

[GetUniqueIdTest.zip](https://github.com/godotengine/godot/files/8692359/GetUniqueIdTest.zip)

### PR DESCRIPTION
**Pull request by MaxIsJoe**
Fixes #61023

Changing it back to how it's done on the 3.x branch fixed the text not being printed properly.

### CODE REVIEW

File: platform/windows/os_windows.cpp [hunk 1]
```diff
@@ -953,7 +953,7 @@ String OS_Windows::get_user_data_dir() const {
 String OS_Windows::get_unique_id() const {
 	HW_PROFILE_INFO HwProfInfo;
 	ERR_FAIL_COND_V(!GetCurrentHwProfile(&HwProfInfo), "");
-	return String::utf16((const char16_t *)(HwProfInfo.szHwProfileGuid), HW_PROFILE_GUIDLEN);
+	return String((HwProfInfo.szHwProfileGuid), HW_PROFILE_GUIDLEN);
```
Comment (bruvzg) [inline platform/windows/os_windows.cpp:956]:
```c++
	HW_PROFILE_INFOA HwProfInfo;
	ERR_FAIL_COND_V(!GetCurrentHwProfileA(&HwProfInfo), "");
	return String((HwProfInfo.szHwProfileGuid), HW_PROFILE_GUIDLEN);
```

Probably better to explicitly specify it's an ASCII version to avoid any future mistakes. (or use `W` versions and `::utf16(...)`, but in this case it's GUID, so extra conversion is not necessary).

**Review by bruvzg — APPROVED** [review]

File: platform/windows/os_windows.cpp (hunk 1 above)
Comment (akien-mga) [reply platform/windows/os_windows.cpp]: Amended the commit as suggested here.

**Comment by akien-mga** [comment]
Thanks!
