### PR TITLE
Avoid several null-dereferences of ApiContextRD

### LINKED ISSUE #86436: Null pointer dereference in X11 initialization error message
### Tested versions

master (9d1cbab1c432b6f1d66ec939445bec68b6af519e)

### System information

n/a

### Issue description

https://github.com/godotengine/godot/blob/9d1cbab1c432b6f1d66ec939445bec68b6af519e/platform/linuxbsd/x11/display_server_x11.cpp#L6032-L6034

### Steps to reproduce

Didn't actually try to trigger this, but my compiler warned about it.

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by RandomShaper**
Fixes #86436.

### CODE REVIEW

**Review by AThousandShips — APPROVED** [review]
LGTM, logical changes (assuming the `get_api_name` doesn't have some memory concerns in its turn)

**Review by deralmas — APPROVED** [review]

File: platform/android/display_server_android.cpp [hunk 1]
```diff
@@ -538,9 +538,9 @@ void DisplayServerAndroid::reset_window() {
 #endif
 
 		if (context_rd->window_create(MAIN_WINDOW_ID, last_vsync_mode, display_size.width, display_size.height, &wpd) != OK) {
+			ERR_FAIL_MSG(vformat("Failed to reset %s window.", context_rd->get_api_name()));
 			memdelete(context_rd);
 			context_rd = nullptr;
```
Comment (akien-mga) [inline platform/android/display_server_android.cpp:543]: `ERR_FAIL_MSG` returns, so that's a memory leak.

Should be `ERR_PRINT` and then a return at the end.

**Review by akien-mga — CHANGES_REQUESTED** [review]

File: platform/android/display_server_android.cpp (hunk 1 above)
Comment (RandomShaper) [reply platform/android/display_server_android.cpp]: Good catch! Otherwise, this PR was trading one kind of error for another. Done.

File: platform/windows/display_server_windows.cpp [hunk 2]
```diff
@@ -4344,10 +4344,11 @@ DisplayServer::WindowID DisplayServerWindows::_create_window(WindowMode p_mode,
 			}
 #endif
 			if (context_rd->window_create(id, p_vsync_mode, WindowRect.right - WindowRect.left, WindowRect.bottom - WindowRect.top, &wpd) != OK) {
+				ERR_PRINT(INVALID_WINDOW_ID, vformat("Failed to create %s Window.", context_rd->get_api_name()));
```
Comment (AThousandShips) [inline platform/windows/display_server_windows.cpp:4347]:
```suggestion
				ERR_PRINT(vformat("Failed to create %s Window.", context_rd->get_api_name()));
```

File: platform/windows/display_server_windows.cpp [hunk 3]
```diff
@@ -4344,10 +4344,11 @@ DisplayServer::WindowID DisplayServerWindows::_create_window(WindowMode p_mode,
...
 				memdelete(context_rd);
 				context_rd = nullptr;
 				windows.erase(id);
-				ERR_FAIL_V_MSG(INVALID_WINDOW_ID, vformat("Failed to create %s Window.", context_rd->get_api_name()));
+				return;
```
Comment (AThousandShips) [inline platform/windows/display_server_windows.cpp:4351]:
```suggestion
				return INVALID_WINDOW_ID;
```

**Review by AThousandShips — APPROVED** [review]

**Comment by RandomShaper** [comment]
@AThousandShips, thanks for helping me fixing the loose ends my eyesight seems not to want to detect. Hope it's OK now.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
