### PR TITLE
Merge `uid_cache.bin` and `global_script_class_cache.cfg` after mounting PCKs

### LINKED ISSUE #82061: Mounting PCK/ZIP files does not appear to load/merge uid_cache.bin or global_script_class_cache.cfg
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - macOS 13.4.1 - Vulkan (Mobile) - integrated Apple M1 Pro - Apple M1 Pro (10 Threads)

### Issue description

# Issue

When mounting DLC content (via PCK or ZIP archive) the loading code mounts the files, but does not re-index any global caches (such as `.godot/global_script_class_cache.cfg` and `.godot/uid_cache.bin`).

For `global_script_class_cache.cfg` (included in PCK files by default) this results in any DLC class that exposes `class_name MyBaseControl` not being resolvable by other code unless that script is explicitly loaded first. This makes it impossible to use named DLC classes via `extends MyBaseControl` or as a resource class in a `.tres` file. This appears to be the case no matter if the use is within the same PCK or within another one that depends on it. 

Workaround: For `extends` it's still possible to use the `res://` syntax instead of the global class name. **However, for the `.tres` case it always fails** because the fallback from script_class is uid which also does not work (see below).

`uid_cache.bin` is also included in all PCK files by default, but appears to be ignored during mounting as well. This mostly results in warnings being emitted as seen below. 
```
W 0:00:01:0163   open: res://dlc/frontend/frontend-main.tscn: In external resource #2, invalid UID: uid://glss85r4a4qa - using text path instead: res://dlc/frontend/ui/location.tscn
  <C++ Source>   core/io/resource_format_binary.cpp:1053 @ open()
```
Most cases using UIDs have a fallback to full path (which still works, albeit less efficiently) but a notable exception is the `.tres` file format which uses the global class name followed by UID without a res field (perhaps this is another issue?).
```
[gd_resource type="Resource" script_class="MyResourceClass" load_steps=2 format=3 uid="uid://bl1m18r3skrb8"]
```

NOTE: after examining `get_forced_export_files` in C++ I think there may be a similar issue with the internationalization files, but I don't know enough about that system to say for sure.

## Assessment:
If these caches aren't meant to be used then we shouldn't pack them into PCK files generated by `--export-pack` since those are not meant to be main pck files (project.binary is also included which is just bloat in these DLC files, probably everything in `EditorExportPlatform::get_forced_export_files` should be examined). 
However, I don't think things like `class_name` will work without them so it would make more sense to make merging the values with the existing runtime global class map and UID cache part of mounting.

## Proposed Fix:
After mounting a PCK, load the UID, global_class, and Internationalization files again and merge anything found with what's already in memory.

### Steps to reproduce

# Repro:
- Create an initial project `initial-proj` with nothing in it. This represents the initial (shipped) state of the project.
    - add a new scene called `main_scene.tscn`
        - give it a custom script `main_scene.gd` which extends Control
    - add a default scene called `start_scene.tscn` (set this as the default for the project)
        - add code to load `res://DLC.pck` (if it exists) and then change to `main_scene.tscn` (whether DLC was found or not)
- Copy your initial project to another directory called `dlc-proj`. This will represent the post-release (DLC) version of the project.
- In the copied DLC project
    - create a Control class (exposed with `class_name MyBaseControl`) called `my_base.gd`
    - change `main_scene.gd` to extend MyBaseControl instead of Control
    - create an export config for your current platform
        - restrict the export config to export `main_scene.tscn` and dependencies.
        - use the GUI to export DLC.pck and place it in `initial-proj` 
- Go back to the initial project and run it (now with DLC)
(minimal reproduction project attached)

## Expected Result
The DLC should load properly in `initial-proj` and the `main_scene.tscn` should spawn using the updated version (derived from `MyBaseControl`). This should be the same behavior as observed when running `dlc-proj`.

## Actual Result
When running `dlc-proj` everything works.

However, upon running `initial-proj` (with `DLC.pak` present) the `main_scene.gd` script fails to load with the error:
```
Parser Error: Could not find base class "MyBaseClass".
```

### Minimal reproduction project

[pck-issue.zip](https://github.com/godotengine/godot/files/12689026/pck-issue.zip)

### PR DESCRIPTION
**Pull request by ogapo**
## Fix for uid_cache.bin and global_script_class_cache.cfg not taking into account DLC mounting

The global script and UID caches were not getting updated after PCK files mount. This resulted in scripts using global `class_name` not being able to resolve properly as well as UID->resource path mappings not getting stored. I added methods to ProjectSettings and ResourceUID that allow merging in newly updated copies of these global caches. These functions intentionally merge rather than replace to account for the case where multiple DLC/MODs may have independent information, but not contain eachother's information.

This fixes #82061.

## Removed some unnecessary files from non-main PCKs

In addition, non-main PCK files presently include a lot of cruft that can't be used after startup and just bloats DLC. It's desirable for downloaded content to be as small as possible. This change avoids bloating non-main pack files with new versions of resources that are all read on startup and never used again. These have no effect if replaced after startup:
- project.godot/project.binary file
- extension_list.cfg
- app icon and boot_splash
- .ico and .icns files (these can still be opted in for DLC by listing them explicitly in the include filter)

## Added a missing error feedback to PCK export

Finally, while I was in here I noticed the --export-pack command doesn't provide any feedback if you accidentally use a non-supported extension (other than .pck or .zip) so I error messaging and set the status code properly.

### CODE REVIEW

**Comment by ghmart** [comment]
Not a reviewer, but I tested this fork with my project and can confirm that this fix makes all UIDs valid.

No more need to use workaround like what was mentioned in https://github.com/godotengine/godot/issues/82061.

Thank you for this fix! Hope to see it merged with master soon.

File: editor/export/editor_export_platform.cpp [hunk 1]
```diff
@@ -831,29 +831,34 @@ String EditorExportPlatform::_get_script_encryption_key(const Ref<EditorExportPr
...
 
-	String icon = GLOBAL_GET("application/config/icon");
-	String splash = GLOBAL_GET("application/boot_splash/image");
-	if (!icon.is_empty() && FileAccess::exists(icon)) {
-		files.push_back(icon);
-	}
-	if (!splash.is_empty() && FileAccess::exists(splash) && icon != splash) {
-		files.push_back(splash);
+		String splash = GLOBAL_GET("application/boot_splash/image");
+		if (!splash.is_empty() && FileAccess::exists(splash) && icon != splash) {
```
Comment (AThousandShips) [inline editor/export/editor_export_platform.cpp:845]:
```suggestion
		if (!splash.is_empty() && icon != splash && FileAccess::exists(splash)) {
```
Put cheaper condition before more expensive ones

**Comment by rsubtil** [comment]
This should close https://github.com/godotengine/godot/issues/61556 and superseed my fix for UIDs at https://github.com/godotengine/godot/pull/79076 (also closing https://github.com/godotengine/godot-proposals/issues/7181)

It seems though this will only work with packs loaded with `replace_files` enabled, and so I think those two files need to be fetched regardless of that setting, in order to work on all scenarios.

**Comment by ogapo** [comment]
@rsubtil Good observation about when `replace_files=false`.

I started to try and handle this as feedback, but unfortunately I am not sure my approach can work at all in the case where we're not replacing files. If we don't replace, then some files may not get their new versions mounted which means some of the UIDs in the UID cache, and some of the classes in the class cache may not be correct. 

Without a more extensive change (possibly to those files themselves) I'm not sure the behavior would be better than leaving it as is. Seems like having no data in the cache would be better than wrong data. I think it might be best to leave it as a known issue and try to address this case in a follow-up PR.

File: core/object/script_language.cpp [hunk 2]
```diff
@@ -268,12 +268,23 @@ void ScriptServer::global_classes_clear() {
 
 void ScriptServer::add_global_class(const StringName &p_class, const StringName &p_base, const StringName &p_language, const String &p_path) {
 	ERR_FAIL_COND_MSG(p_class == p_base || (global_classes.has(p_base) && get_global_class_native_base(p_base) == p_class), "Cyclic inheritance in script class.");
-	GlobalScriptClass g;
-	g.language = p_language;
-	g.path = p_path;
-	g.base = p_base;
-	global_classes[p_class] = g;
-	inheriters_cache_dirty = true;
+	if (GlobalScriptClass *existing = global_classes.getptr(p_class)) {
```
Comment (AThousandShips) [inline core/object/script_language.cpp:271]:
```suggestion
	GlobalScriptClass *existing = global_classes.getptr(p_class);
	if (existing) {
```
We usually don't use this syntax as it's less readable

**Comment by ogapo** [comment]
Squashed commits per https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html

**Comment by AThousandShips** [comment]
You haven't squashed your commits

**Comment by AThousandShips** [comment]
You've included several of the commit messages after the body of your message, please remove them to restrict it to:
```
Distinguish between main pack and DLC packs.
It's desirable to downloaded content to be as small as possible. This change avoids bloating non-main pack files with new versions of resources that are all read on startup and never used again. They have no effect if loaded after startup.
- project.godot/project.binary file
- extension_list.cfg
- app icon and boot_splash
- .ico and .icns files (these can still be opted in for DLC by listing them explicitly in the include filter)
```

**Comment by ogapo** [comment]
@AThousandShips My bad. Had some `git` aggro haha. I believe it's in the correct state now.

**Comment by AThousandShips** [comment]
It still contains what looks like random comments on bug fixes you did:
```
Refresh the global class list after loading a PCK

merge in the new uid cache when a PCK file loads

call add_global_class for all cases because base/language/path may change.
modified add_global_class to only set inheriters_cache_dirty if something actually updates since StringName comparisons are cheap
```
The commit message should be brief and specific :)

**Comment by ogapo** [comment]
Ok, I've cleaned that up a bit. Let me know if you'd like further changes. That first quote doesn't fully summarize the change. Main fix is the merging of the global class and UID cache, the restriction of files is complimentary.

**Comment by AThousandShips** [comment]
LGTM

A commit message doesn't have to explain the PR generally, just give a basic idea of what's done, the code and the PR should convey the real details most of the time

File: core/config/project_settings.cpp [hunk 3]
```diff
@@ -469,6 +469,12 @@ bool ProjectSettings::_load_resource_pack(const String &p_pack, bool p_replace_f
 		return false;
 	}
 
+	// this pack may have declared new global classes (make sure they are picked up)
```
Comment (akien-mga) [inline core/config/project_settings.cpp:472]:
```suggestion
	// This pack may have declared new global classes (make sure they are picked up).
```
Make sure to apply this style to all comments (starts with a capital letter, ends with a dot).

File: editor/export/editor_export_platform.cpp [hunk 4]
```diff
@@ -831,29 +831,34 @@ String EditorExportPlatform::_get_script_encryption_key(const Ref<EditorExportPr
...
 	}
 
-	String extension_list_config_file = GDExtension::get_extension_list_config_file();
-	if (FileAccess::exists(extension_list_config_file)) {
-		files.push_back(extension_list_config_file);
-	}
-
 	// Store text server data if it is supported.
 	if (TS->has_feature(TextServer::FEATURE_USE_SUPPORT_DATA)) {
 		bool use_data = GLOBAL_GET("internationalization/locale/include_text_server_data");
```
Comment (akien-mga) [inline editor/export/editor_export_platform.cpp:864]: Should this be in each pck too, or only the main pack?

If only the main pack, this is starting to look like it should just be two separate functions as there's little overlap between the two scenarios.

Comment (ogapo) [reply editor/export/editor_export_platform.cpp:864]: To be honest, I wasn't sure how this worked. Conceptually, if this is a translation DB, then it probably needs to be in all PCKs since they could potentially introduce new strings. That said, it probably would need a similar merge process as the UID cache and global script class cache to work properly. I'm not really comfortable enough with the localization system to attempt that fix. 

In lieu of that, I can either pack it in the main pck only (trimming something that's possibly unused) or keep it in all pcks (preserving current behavior). Thoughts? Happy to split this function in two if the call is to main-pck it.

Comment (akien-mga) [reply editor/export/editor_export_platform.cpp:864]: I believe it's a dictionary that's not specific to the game translations / pck strings, but @bruvzg should be able to confirm.

**Comment by YuriSizov** [comment]
Let's be cautious about it and consider this for early 4.3 dev cycle. But reviews are welcome in the meantime.

**Comment by Stalker2106x** [comment]
Looking forward for this to be merged!
There is no actual way to use class_name imports after loading a PCK in the current 4.1.x release

**Comment by dreed-sd** [comment]
I tried a custom build with this fix, but the clients I export with it fail as if there was no global script class cache at all. Even without applying any packages, scripts fail to parse with 'Identifier X not declared in the current scope', when they work with Godot proper.

**Review by mihe — CHANGES_REQUESTED** [review]
In the interest of hopefully moving this PR forward I've spent some time reviewing the proposed changes, as well as tried to consider any potential ramifications, and in general I would say LGTM, apart from the mostly minor/cosmetic suggestions in this review.

There might be some discussion to be had with regards to allowing internationalization data to be bundled in non-main PCKs as talked about previously in this PR, but seeing as how it's currently only loaded at startup anyway, and seemingly tied into initialization in the case of ICU, I don't think it needs to hold up this PR.

**Comment by ogapo** [comment]
Applied the suggested changes (thanks @mihe).

**Review by mihe — APPROVED** [review]
LGTM. You'll need to squash it all into a single commit, in order for it to be merged.

**Comment by ogapo** [comment]
Squashed.

@mihe is there anything else you need from me? Github still says merging is blocked (pending an approving review) but it looks like you approved it. Just trying to wrap my head around the process here.

**Comment by AThousandShips** [comment]
No maintainers have approved this yet :)

**Comment by ogapo** [comment]
> No maintainers have approved this yet :)

Oh derp. Sorry I just got a notification and assumed heh. **waits patiently**

**Review by akien-mga — APPROVED** [review]
Code changes look good to me in the latest version, and I trust @mihe's and @dreed-sd's testing.

Could be good to have maybe @bruvzg check it too, but overall I don't see blockers to merge soon.

**Comment by akien-mga** [comment]
Thanks!

**Comment by aaronfranke** [comment]
This PR caused a serious regression where PCK files do not work anymore: https://github.com/godotengine/godot/issues/89825

**Comment by mihe** [comment]
A fix is lined up in #89928 already, but I guess it needs a review and/or test from someone else.

If the UX changes in that one are considered too much at this stage we can simply revert the trimming part of this PR, make it a part of #89928 instead and save that one for 4.4 I guess.

Thoughts?

**Comment by akien-mga** [comment]
> If the UX changes in that one are considered too much at this stage we can simply revert the trimming part of this PR, make it a part of #89928 instead and save that one for 4.4 I guess.

I think we can still agree on changes for 4.3, but for the next dev snapshot that approach sounds good to me.

**Comment by mihe** [comment]
The revert can be found in #90476.
