### PR TITLE
[Editor] Fix dictionary editor removing wrong keys and not updating key labels.

### LINKED ISSUE #98206: Deleting a key from a dictionary in a resource from the editor deletes the last value
### Tested versions

4.4-dev3

### System information

Windows 11

### Issue description

I attach an image. Pressing the trash button deletes the last key in the dictionary, not the key associated with the button.
The key associated with the button should be deleted.

### Steps to reproduce

Create a resource with a @export var my_dictionary: Dictionary[int, int]. Add multiple keys to the dictionary. Press the delete button.

### Minimal reproduction project (MRP)

bug

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/98206

### CODE REVIEW

File: editor/editor_properties_array_dict.cpp [hunk 1]
```diff
@@ -1173,6 +1173,11 @@ void EditorPropertyDictionary::update_property() {
 				new_prop->set_h_size_flags(SIZE_EXPAND_FILL);
 				new_prop->set_read_only(is_read_only());
 				slot.set_prop(new_prop);
+			} else if (slot.index != EditorPropertyDictionaryObject::NEW_KEY_INDEX && slot.index != EditorPropertyDictionaryObject::NEW_VALUE_INDEX) {
```
Comment (KoBeWi) [inline editor/editor_properties_array_dict.cpp:1176]: What's this for?

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
