### PR TITLE
Fix infinite recursion when seeking Ogg Vorbis file

### LINKED ISSUE #57020: Crash when playing Ogg Vorbis file with very long metadata
### Godot version

4.0.dev (c13319db8)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 495.46)

### Issue description

Importing this Ogg Vorbis file does not crash the editor, but playing it (by checking AudioStreamPlayer's **Autoplay** and running the project) does. This also affects the editor itself when you try to quit it.

This does not occur in `3.x` 322ba882b – the file plays just fine there. A MP3 or WAV file converted from the same FLAC source (using Clementine's transcoding feature) also plays back fine in `master`.

Backtrace:

```
bt Thread 1 "godot.linuxbsd." received signal SIGSEGV, Segmentation fault.
#0  0x000000000480686c in CowData<Vector<Vector<unsigned char> > >::_get_size (this=0xcaaf080)
    at ./core/templates/cowdata.h:81
No locals.
#1  0x0000000004d496d5 in CowData<Vector<Vector<unsigned char> > >::size (this=0xcaaf080)
    at ./core/templates/cowdata.h:139
        size = 0x0
#2  0x0000000004d4a9d5 in CowData<Vector<Vector<unsigned char> > >::get (this=0xcaaf080, p_index=1)
    at ./core/templates/cowdata.h:163
No locals.
#3  0x0000000004d477bf in Vector<Vector<Vector<unsigned char> > >::operator[] (this=0xcaaf078, p_index=1)
    at ./core/templates/vector.h:92
No locals.
#4  0x0000000004d46931 in OGGPacketSequencePlayback::seek_page_internal (this=0xdaf0450, granule=0, 
    after_page_inclusive=0, before_page_inclusive=3) at modules/ogg/ogg_packet_sequence.cpp:173
        test_page = 1
        actual_middle_page = 1
        bisection_page = 4294967295
        bisection_granule_pos = 212529296
#5  0x0000000004d46a50 in OGGPacketSequencePlayback::seek_page_internal (this=0xdaf0450, granule=0, 
    after_page_inclusive=0, before_page_inclusive=3) at modules/ogg/ogg_packet_sequence.cpp:195
        actual_middle_page = 1
        bisection_page = 3
        bisection_granule_pos = 0
#6  0x0000000004d46a50 in OGGPacketSequencePlayback::seek_page_internal (this=0xdaf0450, granule=0, 
    after_page_inclusive=0, before_page_inclusive=3) at modules/ogg/ogg_packet_sequence.cpp:195
        actual_middle_page = 1
        bisection_page = 3
        bisection_granule_pos = 0
#7  0x0000000004d46a50 in OGGPacketSequencePlayback::seek_page_internal (this=0xdaf0450, granule=0, 
    after_page_inclusive=0, before_page_inclusive=3) at modules/ogg/ogg_packet_sequence.cpp:195
        actual_middle_page = 1
        bisection_page = 3
        bisection_granule_pos = 0
#8  0x0000000004d46a50 in OGGPacketSequencePlayback::seek_page_internal (this=0xdaf0450, granule=0, 
    after_page_inclusive=0, before_page_inclusive=3) at modules/ogg/ogg_packet_sequence.cpp:195
        actual_middle_page = 1
        bisection_page = 3
        bisection_granule_pos = 0
#9  0x0000000004d46a50 in OGGPacketSequencePlayback::seek_page_internal (this=0xdaf0450, granule=0, 
    after_page_inclusive=0, before_page_inclusive=3) at modules/ogg/ogg_packet_sequence.cpp:195
        actual_middle_page = 1
        bisection_page = 3
        bisection_granule_pos = 0
#10 0x0000000004d46a50 in OGGPacketSequencePlayback::seek_page_internal (this=0xdaf0450, granule=0, 
    after_page_inclusive=0, before_page_inclusive=3) at modules/ogg/ogg_packet_sequence.cpp:195
        actual_middle_page = 1
        bisection_page = 3
        bisection_granule_pos = 0
#11 0x0000000004d46a50 in OGGPacketSequencePlayback::seek_page_internal (this=0xdaf0450, granule=0, 
    after_page_inclusive=0, before_page_inclusive=3) at modules/ogg/ogg_packet_sequence.cpp:195
        actual_middle_page = 1
        bisection_page = 3
        bisection_granule_pos = 0
#12 0x0000000004d46a50 in OGGPacketSequencePlayback::seek_page_internal (this=0xdaf0450, granule=0, 
    after_page_inclusive=0, before_page_inclusive=3) at modules/ogg/ogg_packet_sequence.cpp:195
        actual_middle_page = 1
        bisection_page = 3
        bisection_granule_pos = 0
#13 0x0000000004d46a50 in OGGPacketSequencePlayback::seek_page_internal (this=0xdaf0450, granule=0, 
    after_page_inclusive=0, before_page_inclusive=3) at modules/ogg/ogg_packet_sequence.cpp:195
--Type <RET> for more, q to quit, c to continue without paging--
```

The full backtrace extends to `#10000` and beyond, which means a recursion limit may be hit in `OGGPacketSequencePlayback::seek_page_internal()`.

`ffprobe` of the Ogg Vorbis file in question:

```
Input #0, ogg, from 'lq_Cloudkicker - Subsume - 03 He would be riding on the subway or writing formulas on the blackboard or having a meal or (as now) sitting and talking to someone across a table, a.ogg':
  Duration: 00:08:48.70, start: 0.000000, bitrate: 111 kb/s
  Stream #0:0: Audio: vorbis, 44100 Hz, stereo, fltp, 112 kb/s
    Metadata:
      TITLE           : He would be riding on the subway or writing formulas on the blackboard or having a meal or (as now) sitting and talking to someone across a table, and it would envelop him like a soundless tsunami.
      ARTIST          : Cloudkicker
      DATE            : 2013
      COMMENT         : Visit http://cloudkicker.bandcamp.com
      ALBUM           : Subsume
      track           : 3
      album_artist    : Cloudkicker
  Stream #0:1: Video: mjpeg (Baseline), yuvj444p(pc, bt470bg/unknown/unknown), 700x700 [SAR 72:72 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (front)
```

### Steps to reproduce

- Try to open the minimal reproduction project linked below in the editor, then run the project from the editor.
- Watch the running project either crash or freeze indefinitely.

### Minimal reproduction project

`master` with Ogg Vorbis (broken): [test_ogg_long_metadata_master.zip](https://github.com/godotengine/godot/files/7909035/test_ogg_long_metadata_master.zip)
`3.x` with Ogg Vorbis (working): [test_ogg_long_metadata_3.x.zip](https://github.com/godotengine/godot/files/7909024/test_ogg_long_metadata_3.x.zip)

`master` with MP3 (working):[test_mp3_long_metadata_master.zip](https://github.com/godotengine/godot/files/7909081/test_mp3_long_metadata_master.zip)

### PR DESCRIPTION
**Pull request by timothyqiu**
Fixes #57020

When seeking the stream, bisection search midpoint `bisection_page` was moved in order to settle on a page that contains data. Infinite recursion may occur when `bisection_page` settles on `before_page_inclusive`:

https://github.com/godotengine/godot/blob/d02db6306ebcb57296dece3e8d990ae188b39aad/modules/ogg/ogg_packet_sequence.cpp#L191-L196

### CODE REVIEW

**Comment by ellenhp** [comment]
This is so complicated. I didn't leave enough comments to understand what I was doing. Do you think there's a way to simplify the code at all? I'm still reviewing, it's just the first time I think someone has modified this code so I wanted to ask.

**Comment by timothyqiu** [comment]
Not including empty pages when importing works too, but I'm not sure if it's the right way to go.

File: modules/ogg/ogg_packet_sequence.cpp [hunk 1]
```diff
@@ -175,6 +175,9 @@ uint32_t OGGPacketSequencePlayback::seek_page_internal(int64_t granule, uint32_t
 			break;
 		}
 	}
+	if (bisection_page == before_page_inclusive && granule <= (int64_t)ogg_packet_sequence->page_granule_positions[bisection_page]) {
```
Comment (ellenhp) [inline modules/ogg/ogg_packet_sequence.cpp:178]: I don't think this is the right solution. It seems like any time that `bisection_page == before_page_inclusive` automatically becomes a failure case because the method is called again with `bisection_page + 1` as `after_page_inclusive` which means the base case of `before_page_inclusive == after_page_inclusive` is never triggered because in that scope, `before_page_inclusive` is greater than `after_page_inclusive`. Satisfying that constraint is impossible. Could we try making the base case `before_page_inclusive >= after_page_inclusive` instead of using `==`?

If we do that though, it's not immediately clear to me whether we should return `before_page_inclusive` or `after_page_inclusive` in the base case. It could cause problems if we return the wrong one, because it could possibly be an empty page. Although, an empty page isn't the end of the world because playback should handle those gracefully.

I'm really sorry for how confusing this code is. My head is spinning trying to understand it now, months later.

Comment (ellenhp) [reply modules/ogg/ogg_packet_sequence.cpp:178]: Another option is modifying the loop to maybe be `test_page < before_page_inclusive` instead of `test_page <= before_page_inclusive`? I haven't tested either of these ideas but they seem like where I'd start. Thank you so much for figuring out where the problem is, by the way.

Comment (timothyqiu) [reply modules/ogg/ogg_packet_sequence.cpp:178]: In the MRP, it's kind of like searching for 0 inside range `[0, 2]`:

| idx | pos | size |
|------|------|-------|
| 0     | 0     | 1     |
| 1     | 0     | 0     |
| 2     | 0     | 1     |

In this case, `bisection_page` first picks 2, and recurreset it to -1, and then searches forward and picks 0.

**Comment by timothyqiu** [comment]
@ellenhp Since you're working on a more comprehensive solution, should I close this PR?

**Comment by ellenhp** [comment]
> @ellenhp Since you're working on a more comprehensive solution, should I close this PR?

To be honest I have very little energy for Godot right now. Doing code reviews is easy and fun because it's just 15 minutes here and 30 minutes there, but I don't think I can sit down and actually fix this bug right now. :( Maybe we can include this fix as a temporary solution with a comment describing what it's trying to accomplish and acknowledging that it might miss some cases? In general this method needs to be commented better, I think.

I'm not opposed to merging something like this, I just wanted to suggest some other things too.

**Comment by timothyqiu** [comment]
I changed the loop condition to `test_page < before_page_inclusive` as you suggested. It looks cleaner. My additional checks were redundant since `seek_page_internal` is always used by a controlled caller.

**Comment by ellenhp** [comment]
> I changed the loop condition to `test_page < before_page_inclusive` as you suggested. It looks cleaner. My additional checks were redundant since `seek_page_internal` is always used by a controlled caller.

Looks good to me. Did you test it with the MRP to make sure it fixes things? I can't do testing myself right now.

**Comment by timothyqiu** [comment]
Yes, I've tested the MRP and the file can now be played normally.

**Review by ellenhp — APPROVED** [review]

**Comment by ellenhp** [comment]
I think this is small enough and audio-specific enough that I can merge without further review. Thank you for the fix, I really appreciate it. :)
