### PR TITLE
Use dedicated canvas item to properly cull tree items

### LINKED ISSUE #114123: Invalid Tree margin when scrolling
### Tested versions

4.6 beta1
Not reproducible in 4.5.1

### System information

W10

### Issue description

When scrolling a Tree, notably the FileSystem dock, the Tree might display invalid margin at the bottom.

https://github.com/user-attachments/assets/e1b51d7e-f0c1-4f2e-a8f3-1d9b9c0cc2cc

A similar margin at the top was fixed by #112830, but it caused a regression.

### Steps to reproduce

1. Have many files in the project
2. Scroll FileSystem (tree view) very slowly

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by boozee**
This PR fixes #114123 following the advice given [here](https://github.com/godotengine/godot/issues/114117#issuecomment-3667174249) by the reporter @KoBeWi.

The culling window for tree items has been restricted to the proper rect up to the bottom of the tree, fixing the early exit that didn't account for the bottom margin and thus the issue itself.

That itself was not enough, as the same problem was showing on the top of the `FileSystem tab`, which lead me do find out it was a workaround to prevent items from rendering beyond the column headers.

So, as suggested in the linked comment, I introduced a separate `canvas item` for column headers in order to separate item culling from those, no matter the size of the item.

I'm attaching some videos as proof of the solution.
<details><summary>Details</summary>

https://github.com/user-attachments/assets/afa4af62-8655-42e8-9965-002dfe3ef3b3

https://github.com/user-attachments/assets/9ce7526d-5622-436b-9775-99e85e772252

https://github.com/user-attachments/assets/31df16bf-e638-461e-8210-0ae483a424bd

</details> 

*Bugsquad edit:* Fixes #114140

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -3747,6 +3755,47 @@ Rect2 Tree::_get_content_rect() const {
...
+	rs->canvas_item_set_z_as_relative_to_parent(header_ci, is_z_relative());
+	rs->canvas_item_set_modulate(header_ci, get_modulate());
+	rs->canvas_item_set_self_modulate(header_ci, get_self_modulate());
+	rs->canvas_item_set_light_mask(header_ci, get_light_mask());
+	rs->canvas_item_set_visibility_layer(header_ci, get_visibility_layer());
+	rs->canvas_item_set_default_texture_filter(header_ci, static_cast<RenderingServer::CanvasItemTextureFilter>(get_texture_filter_in_tree()));
+
+	if (get_use_parent_material()) {
+		rs->canvas_item_set_use_parent_material(header_ci, true);
+		rs->canvas_item_set_material(header_ci, RID());
```
Comment (KoBeWi) [inline scene/gui/tree.cpp]: You can just always enable `canvas_item_set_use_parent_material()` on the `header_ci` and it will automatically use Tree's current material.

EDIT:
See my comment below.

File: scene/gui/tree.cpp [hunk 2]
```diff
@@ -6875,6 +6945,9 @@ Tree::Tree() {
 
 	set_focus_mode(FOCUS_ALL);
 
+	header_ci = RenderingServer::get_singleton()->canvas_item_create();
+	header_ci_parent = RID();
```
Comment (KoBeWi) [inline scene/gui/tree.cpp]: Couldn't the Tree be parent of `header_ci`? It would be easier to keep in sync.

Comment (boozee) [reply scene/gui/tree.cpp]: That would indeed be easier from a logical PoV, however then the clipping of Tree would apply to `header_ci` too and we would be back to square one.

One alternative would be bringing the rows in a different CI with its own clipping. but from my understanding that would require much bigger changes due to `CELL_MODE_CUSTOM ` callbacks which draw on Tree itself.
I'm not sure that's desirable now, especially in a bugfix PR, but please correct me in case.

Another alternative would be using `canvas_item_add_clip_ignore` around the header but seems a dangerous path to follow instead of maintaining parenting clipping.

According to your opinions on this, I'll act on the other points you opened.

Comment (KoBeWi) [reply scene/gui/tree.cpp]: > from my understanding that would require much bigger changes due to CELL_MODE_CUSTOM  callbacks which draw on Tree itself.

Drawing on Tree should still be functional, it just wouldn't be clipped (so, the same as now...).

The main problem is that delegating whole TreeItem drawing to a different CanvasItem would require many of changes. They could be less complex if that CanvasItem was a sub-node of the Tree, but that's still quite a few changed lines (more than now).

Either way, this PR in it's current form is not acceptable as it brings new regressions. The changes should fix the issue _and_ make sure there are no new bugs. Feel free to pick a solution, as long as it works correctly and does not significantly hurt performance.

File: scene/gui/tree.cpp [hunk 3]
```diff
@@ -5069,19 +5122,33 @@ void Tree::_notification(int p_what) {
...
-
 			int tbh = _get_title_button_height();
 
 			draw_ofs.y += tbh;
 			draw_size.y -= tbh;
 
+			const real_t clip_top = show_column_titles ? draw_ofs.y : 0.0f; // Start clipping below headers when they are visible
+			const real_t bottom_margin = theme_cache.panel_style->get_margin(SIDE_BOTTOM);
+			const real_t clip_bottom = draw_ofs.y + draw_size.y + bottom_margin; // End clip after the bottom margin
+			const Rect2 main_clip_rect = Rect2(Point2(0.0f, clip_top), Size2(get_size().x, clip_bottom - clip_top));
```
Comment (AThousandShips) [inline scene/gui/tree.cpp]:
```suggestion
			const Rect2 main_clip_rect = Rect2(0.0f, clip_top, get_size().x, clip_bottom - clip_top);
```

File: scene/gui/tree.cpp (hunk 2 above)
Comment (boozee) [reply scene/gui/tree.cpp]: Both issues you spotted should now be fixed and I couldn't spot more of them.
In the end I went with items drawing as a child of the Tree for clear separation from the header, both are kept in sync with the tree.

**Comment by KoBeWi** [comment]
Scroll hints have wrong color:
image
Likely from #114751, you need to rebase and fix your branch.

File: scene/gui/tree.h [hunk 4]
```diff
@@ -543,6 +543,10 @@ class Tree : public Control {
 
 	bool popup_edit_committed = true;
 	RID accessibility_scroll_element;
+	RID header_ci; // Separate canvas item for drawing column headers
+	RID header_ci_parent; // Tracks the current parent RID
+	RID content_ci; // Separate canvas item for drawing tree rows
+	RID content_ci_parent; // Tracks the current parent RID for content_ci
```
Comment (KoBeWi) [inline scene/gui/tree.h]: What are parent RIDs for? They seem always be assigned to the Tree's RID and not even used.

File: scene/gui/tree.cpp [hunk 5]
```diff
@@ -3755,6 +3753,65 @@ Rect2 Tree::_get_content_rect() const {
...
+	rs->canvas_item_set_use_parent_material(header_ci, true);
+	rs->canvas_item_set_material(header_ci, RID());
+
+	// Header clip to the Tree's visible rect
+	const Rect2 header_rect = Rect2(Point2(), get_size());
+	rs->canvas_item_set_custom_rect(header_ci, !is_visibility_clip_disabled(), header_rect);
+	rs->canvas_item_set_clip(header_ci, true);
+}
+
+void Tree::_update_content_canvas_item(const bool p_visible) {
```
Comment (KoBeWi) [inline scene/gui/tree.cpp]: I don't get the purpose of this method.
Now that the internal CanvasItems use Tree as parent, setting most of these properties is unnecessary, because they are inherited.
And then you are also setting constant values, in a method that's called multiple times. Useless. Just set them once when creating the RIDs.

File: scene/gui/tree.cpp [hunk 6]
```diff
@@ -4901,6 +4963,10 @@ void Tree::_notification(int p_what) {
 				col.accessibility_col_element = RID();
 			}
 			accessibility_scroll_element = RID();
+			if (p_what == NOTIFICATION_EXIT_TREE) {
+				_update_header_canvas_item(false);
+				_update_content_canvas_item(false);
```
Comment (KoBeWi) [inline scene/gui/tree.cpp]: What? None of this is relevant once the Tree exits scene.

File: scene/gui/tree.cpp [hunk 7]
```diff
@@ -5172,10 +5276,22 @@ void Tree::_notification(int p_what) {
...
 }
 
+void Tree::set_self_modulate(const Color &p_self_modulate) {
+	if (get_self_modulate() == p_self_modulate) {
+		return;
+	}
+
+	CanvasItem::set_self_modulate(p_self_modulate);
+	_update_header_canvas_item(show_column_titles);
+	_update_content_canvas_item(true);
```
Comment (KoBeWi) [inline scene/gui/tree.cpp]: Just set the self modulate instead of doing full update.

File: scene/gui/tree.cpp [hunk 8]
```diff
@@ -4988,6 +5054,8 @@ void Tree::_notification(int p_what) {
 
 		case NOTIFICATION_VISIBILITY_CHANGED: {
 			drag_touching = false;
+			_update_header_canvas_item(show_column_titles);
+			_update_content_canvas_item(true);
```
Comment (KoBeWi) [inline scene/gui/tree.cpp]: Not needed. Child CanvasItems automatically inherit visibility.

**Review by KoBeWi — COMMENTED** [review]
I skimmed over the code. You are performing lots of unnecessary updates for the internal CanvasItems. You should only set what is necessary (and do it once if it does not change), most of the stuff like visibility, modulate, transform is just inherited from Tree.

File: scene/gui/tree.cpp [hunk 9]
```diff
@@ -2114,7 +2114,7 @@ void Tree::draw_item_rect(const TreeItem::Cell &p_cell, const Rect2i &p_rect, co
 			break;
 	}
 
-	RID ci = get_canvas_item();
+	RID ci = p_canvas_item;
```
Comment (KoBeWi) [inline scene/gui/tree.cpp]:
```suggestion
	RID ci = content_ci;
```
Does not really need to be passed as argument, if it's always the same one.
Same in other methods.

File: scene/gui/tree.cpp [hunk 10]
```diff
@@ -2258,16 +2258,20 @@ void Tree::update_item_cache(TreeItem *p_item) const {
...
 
-int Tree::draw_item(const Point2i &p_pos, const Point2 &p_draw_ofs, const Size2 &p_draw_size, TreeItem *p_item, int &r_self_height) {
-	if (p_pos.y - theme_cache.offset.y > (p_draw_size.height)) {
-		return -1; // Draw no more!
+int Tree::draw_item(const Point2i &p_pos, const Point2 &p_draw_ofs, const Size2 &p_draw_size, TreeItem *p_item, int &r_self_height, RID p_canvas_item) {
+	const real_t bottom_margin = theme_cache.panel_style->get_margin(SIDE_BOTTOM); // Extra stylebox space below the content
+	const real_t draw_height = p_draw_size.height + bottom_margin; // Visible height including bottom margin
+
+	// Cull item if it's beyond the bottom of the visible area.
+	if (static_cast<real_t>(p_pos.y) - theme_cache.offset.y > draw_height) {
```
Comment (KoBeWi) [inline scene/gui/tree.cpp]: Are the static casts necessary? Unless it silences some warning, implicit conversion should be enough.

**Review by KoBeWi — COMMENTED** [review]
Tested, works fine overall. Though you are unnecessarily passing the canvas items as arguments to methods. They always use the same one.

Though before doing further changes, apply this patch:

[0001-Fixup.patch](https://github.com/user-attachments/files/24543526/0001-Fixup.patch)

It removes some unnecessary code and disables clipping of custom drawing (it wasn't clipped in previous versions, so no reason to do it).

File: scene/gui/tree.cpp (hunk 10 above)
Comment (boozee) [reply scene/gui/tree.cpp]: Not necessary, personal preference. But if it's idiomatic in Godot code to implicitly promote int -> real, I'm sticking to it.

File: scene/gui/tree.cpp (hunk 9 above)
Comment (boozee) [reply scene/gui/tree.cpp]: Applied your patch (thanks!) and also removed the unneccessary arguments, indeed they were unneeded.

File: scene/gui/tree.cpp [hunk 11]
```diff
@@ -5077,13 +5085,40 @@ void Tree::_notification(int p_what) {
...
+					const real_t header_right = header_clip_rect.get_end().x;
+					header_clip_rect.position.x = v_scroll_rect.get_end().x;
+					header_clip_rect.size.x = MAX(0.0f, header_right - header_clip_rect.position.x);
+				} else if (v_scroll_rect.position.x < header_clip_rect.get_end().x) {
+					header_clip_rect.size.x = MAX(0.0f, v_scroll_rect.position.x - header_clip_rect.position.x);
+				}
+			}
+			rendering_server->canvas_item_clear(header_ci);
+			rendering_server->canvas_item_set_custom_rect(header_ci, !is_visibility_clip_disabled(), header_clip_rect);
+			rendering_server->canvas_item_set_clip(header_ci, true);
```
Comment (KoBeWi) [inline scene/gui/tree.cpp:5116]: Setting clip here should also be unnecessary, but from my testing it seems you have to set it every time for some reason. No idea how it works.

**Review by KoBeWi — APPROVED** [review]
Looks good now.
