### PR TITLE
Fix drag-dropping nodes to parent with internal nodes

### LINKED ISSUE #78810: Incorrect behaviour when reordering TabContainer children
### Godot version

v4.1.rc1.official [1f9e540f1]

### System information

Windows 10

### Issue description

Attempting to reorder the children of a TabContainer results in an unintended ordering and incorrect undo states.

Also happens in v4.0.3.stable.official [5222a99f5].

https://github.com/godotengine/godot/assets/3820082/2c2458e3-88ad-46d9-8a04-f289a049984a

### Steps to reproduce

1. Add a new TabContainer
2. Add a few children to it
3. Drag and drop to erroneously reorder them
4. Attempt to undo the change

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by kleonc**
When reparenting nodes (or moving within the same parent) within the SceneTreeDock all indexes were taking into account internal nodes. However, `Node::move_child` does move the child only within the group of nodes the given node belongs to (internal-front / non-internal / internal-back), its parameter is supposed to be such relative index. Hence an absolute index (including internal nodes) shouldn't be passed to it.

This PR makes the `SceneTreeDock::_do_reparent` method ensure only non-internal nodes are being moved, and changes all indexes to not take internal nodes into account (hopefully I haven't missed any :upside_down_face:; please double check the changes).

Fixes #78810 (`TabContainer` has internal `TabBar` node).

### CODE REVIEW

File: editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -1898,8 +1898,9 @@ void SceneTreeDock::_do_reparent(Node *p_new_parent, int p_position_in_parent, V
 		if (p_nodes[ni] == p_new_parent) {
 			return; // Attempt to reparent to itself.
 		}
+		ERR_FAIL_COND_MSG(p_nodes[ni]->get_internal_mode() != Node::INTERNAL_MODE_DISABLED, "Trying to reparent internal node, this is a bug.");
```
Comment (KoBeWi) [inline editor/scene_tree_dock.cpp:1901]: *Technically* a user may add an internal node and set its owner, so it's both internal and appears in the scene tree.
I think blocking moving of internal nodes is fine, but attempting to move them is not strictly a bug.

Comment (KoBeWi) [reply editor/scene_tree_dock.cpp:1901]: Also this is not needed:
```suggestion
		ERR_FAIL_COND_MSG(p_nodes[ni]->get_internal_mode() != INTERNAL_MODE_DISABLED, "Trying to reparent internal node, this is a bug.");
```
(not sure if we have any guideline for inherited enums)

**Comment by KoBeWi** [comment]
> hopefully I haven't missed any 🙃

You did. Search the file for `get_index()`, seems like they all cause problem. Note that here
https://github.com/godotengine/godot/blob/46424488edc341b65467ee7fd3ac423e4d49ad34/editor/scene_tree_dock.cpp#L2627
you also need to do `get_child_count(false)`.

**Comment by kleonc** [comment]
> > hopefully I haven't missed any upside_down_face
> 
> You did. Search the file for `get_index()`, seems like they all cause problem. Note that here
> 
> https://github.com/godotengine/godot/blob/46424488edc341b65467ee7fd3ac423e4d49ad34/editor/scene_tree_dock.cpp#L2627
> 
> you also need to do `get_child_count(false)`.

Ah, saw that and concluded it's fine... but indeed it could result in finding a `lower_sibling` which is a back internal node. Which shouldn't happen.

File: editor/scene_tree_dock.cpp (hunk 1 above)
Comment (kleonc) [reply editor/scene_tree_dock.cpp]: Also changed `"Trying to reparent internal node` to `"Trying to move internal node` as `_do_reparent` can act within the same parent. :upside_down_face:

**Comment by KoBeWi** [comment]
By "they all cause problem" I actually meant all calls in scene tree dock. Deleting nodes, changing node to root or instantiating all have the same bug.

**Comment by kleonc** [comment]
> By "they all cause problem" I actually meant all calls in scene tree dock. Deleting nodes, changing node to root or instantiating all have the same bug.

Ok, I've restricted some more code to non-internal nodes only. Haven't tested it at all though, just went with find-read-update manner (again, not sure if I've handled everything). :upside_down_face:

Alternatively I guess I could maybe add a method like `Node::get_internal_index` so its result could be passed to `Node::move_child` (and nodes could be readded with the same internal mode as they had).

Current combination of how `Node::get_index`/`Node::move_child` work is unfortunate, I see no way to obtain internal node's "internal index" aka index only within the front/back internal nodes (for front ones it's the same as the absolute index but back ones are problematic). And that's what's needed for moving.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
