### PR TITLE
Fix `GridMap` Move Action Undo/Redo/Cancel

### LINKED ISSUE #109860: When using Gridmap's Move tool, ESC key does not cancel the operation correctly
### Tested versions

4.5beta5

### System information

Godot v4.5.beta5 - Windows 11 (build 26100) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 32.0.15.6119) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 threads) - 15.84 GiB memory

### Issue description

See video:

https://github.com/user-attachments/assets/f8c1e4f1-5f4e-4edb-9699-3c4695ab055d

We expect the blocks to go back to where they were instead of disappearing.

This is probably linked to the fact that we need to press CTRL+Z (Undo) twice to get the blocks back to where they were.

### Steps to reproduce

- Have a Gridmap
- Select a set of tiles/cells
- Press X and move them
- Press ESC

### Minimal reproduction project (MRP)

Easy to replicate.

### PR DESCRIPTION
**Pull request by ryevdokimov**
Fixes: https://github.com/godotengine/godot/issues/109860

~~Requires and Includes: https://github.com/godotengine/godot/pull/108743~~

This fix includes having to press undo twice to undo a move action. This now only register a single action into the undo/redo system. 

https://github.com/user-attachments/assets/f30dacc3-3acd-434f-8286-10c13ac8fd94

### CODE REVIEW

File: modules/gridmap/editor/grid_map_editor_plugin.cpp [hunk 1]
```diff
@@ -460,6 +466,21 @@ bool GridMapEditor::do_input_action(Camera3D *p_camera, const Point2 &p_point, b
 	return false;
 }
 
+void GridMapEditor::_delete_selection_cells() {
+	if (!selection.active) {
+		return;
+	}
+
+	for (int i = selection.begin.x; i <= selection.end.x; i++) {
```
Comment (fire) [inline modules/gridmap/editor/grid_map_editor_plugin.cpp:473]: Is there a better way than three for loops?

File: modules/gridmap/editor/grid_map_editor_plugin.cpp [hunk 2]
```diff
@@ -675,6 +718,11 @@ EditorPlugin::AfterGUIInput GridMapEditor::forward_spatial_input_event(Camera3D
 		// Hard key actions:
 		if (k->get_keycode() == Key::ESCAPE) {
 			if (input_action == INPUT_PASTE) {
+				for (const ClipboardItem &item : clipboard_items) {
+					Vector3 original_position = paste_indicator.begin + item.grid_offset;
+					node->set_cell_item(Vector3i(original_position), item.cell_item, item.orientation);
```
Comment (Nodragem) [inline modules/gridmap/editor/grid_map_editor_plugin.cpp]: this `grid_offset` makes me think that we should make sure that this PR works after this PR is merged: https://github.com/godotengine/godot/pull/108743

File: modules/gridmap/editor/grid_map_editor_plugin.cpp (hunk 1 above)
Comment (ryevdokimov) [reply modules/gridmap/editor/grid_map_editor_plugin.cpp:473]: This is mostly a copy/paste from an existing way of handling cell deletions just without undo/redo, I couldn't find a clean way to exactly reuse the code, so I created a dedicated method. 

https://github.com/godotengine/godot/blob/3defc856b0f1c727b4346e60615b2b2451916837/modules/gridmap/editor/grid_map_editor_plugin.cpp#L470-L478

File: modules/gridmap/editor/grid_map_editor_plugin.cpp (hunk 2 above)
Comment (ryevdokimov) [reply modules/gridmap/editor/grid_map_editor_plugin.cpp]: I can just rebase on top of yours and give it a try since yours seems ready to merge

File: modules/gridmap/editor/grid_map_editor_plugin.cpp (hunk 1 above)
Comment (Nodragem) [reply modules/gridmap/editor/grid_map_editor_plugin.cpp:473]: no, there is no other way, @ryevdokimov is deleting the content in the selection cube, hence he needs to iterate on each axis (X,Y,Z) as seen in `_delete_selection()`.

One thing I am not sure of is the name `_delete_selection_cells()`, maybe it would be better named as `_delete_selection_without_undo()`, or rename the other one as `_delete_selection_with_undo`. I don't know.

File: modules/gridmap/editor/grid_map_editor_plugin.cpp (hunk 2 above)
Comment (ryevdokimov) [reply modules/gridmap/editor/grid_map_editor_plugin.cpp]: Done. Everything still seems fine.

File: modules/gridmap/editor/grid_map_editor_plugin.cpp (hunk 1 above)
Comment (ryevdokimov) [reply modules/gridmap/editor/grid_map_editor_plugin.cpp:473]: >or rename the other one as _delete_selection_with_undo

Went with this.

**Comment by ryevdokimov** [comment]
Rebased since https://github.com/godotengine/godot/pull/108743 got merged.

**Comment by Nodragem** [comment]
I tested the PR as requested by @smix8, I tried the following:
- select tiles, press X, then move, then press ESC
- select tiles, press X, click to confirm, then CTRL+Z
- select tiles, press C, then move, then press ESC
- select tiles, press C, click to confirm, then CTRL+Z
I also checked that https://github.com/godotengine/godot/pull/108743 was still effective while performing these operations.

I can confirm that all the operations above are now working as expected; this PR fix https://github.com/godotengine/godot/issues/109860 and the broken Undo of cutting tiles.

Looking the code, the changes are minimal and to the point. There is a small redundancy between the undo code in `_do_paste()` and the cancel code in `_cancel_pending_move()`, but I am not sure how we could avoid it.

**Review by smix8 — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
