### PR TITLE
Fix some -Wmaybe-uninitialized warnings

### LINKED ISSUE #37352: -Wmaybe-uninitialized warnings with GCC 9.3.0 and target=release_debug
**Godot version:**
Master (64470ef6395eb110c3cdd0757e2dfabd517d54de)

**OS/device including version:**
Linux, GCC 9.3.0

**Issue description:**
When building with `warnings=extra tools=no target=release_debug` (and in this case also `disable_3d=yes`, if it makes a difference -- *Edit:* Tested, same warnings without `disable_3d=yes`, so it's not involved), I get quite a few `-Wmaybe-uninitialized` warning which don't seem to appear with `target=debug`.

I fixed some in #37351, but others seem to be false positives so I don't see how to fix them:
```
modules/csg/csg_shape.cpp: In member function 'virtual CSGBrush* CSGMesh::_build_brush()':
modules/csg/csg_shape.cpp:796:22: warning: 'uvr' may be used uninitialized in this function [-Wmaybe-uninitialized]
  796 |       uv[k] = uvr[idx];
      |                      ^
modules/csg/csg_shape.cpp:793:25: warning: 'nr' may be used uninitialized in this function [-Wmaybe-uninitialized]
  793 |       normal[k] = nr[idx];
      |                         ^
```
```
scene/resources/mesh_data_tool.cpp: In member function 'Error MeshDataTool::commit_to_surface(const Ref<ArrayMesh>&)':
scene/resources/mesh_data_tool.cpp:269:17: warning: 'we' may be used uninitialized in this function [-Wmaybe-uninitialized]
  269 |     we[i * 4 + 0] = vtx.weights[0];
      |                 ^
scene/resources/mesh_data_tool.cpp:277:17: warning: 'bo' may be used uninitialized in this function [-Wmaybe-uninitialized]
  277 |     bo[i * 4 + 0] = vtx.bones[0];
      |                 ^
scene/resources/mesh_data_tool.cpp:265:12: warning: 'col' may be used uninitialized in this function [-Wmaybe-uninitialized]
  265 |     col[i] = vtx.color;
      |     ~~~~~~~^~~~~~~~~~~
scene/resources/mesh_data_tool.cpp:263:12: warning: 'uv2' may be used uninitialized in this function [-Wmaybe-uninitialized]
  263 |     uv2[i] = vtx.uv2;
      |     ~~~~~~~^~~~~~~~~
scene/resources/mesh_data_tool.cpp:261:11: warning: 'uv' may be used uninitialized in this function [-Wmaybe-uninitialized]
  261 |     uv[i] = vtx.uv;
      |     ~~~~~~^~~~~~~~
scene/resources/mesh_data_tool.cpp:257:17: warning: 'ta' may be used uninitialized in this function [-Wmaybe-uninitialized]
  257 |     ta[i * 4 + 2] = vtx.tangent.normal.z;
      |                 ^
scene/resources/mesh_data_tool.cpp:253:11: warning: 'nr' may be used uninitialized in this function [-Wmaybe-uninitialized]
  253 |     nr[i] = vtx.normal;
      |     ~~~~~~^~~~~~~~~~~~
scene/resources/mesh_data_tool.cpp: In member function 'Error MeshDataTool::create_from_surface(const Ref<ArrayMesh>&, int)':
scene/resources/mesh_data_tool.cpp:108:36: warning: 'we' may be used uninitialized in this function [-Wmaybe-uninitialized]
  108 |    v.weights.push_back(we[i * 4 + 1]);
      |                                    ^
scene/resources/mesh_data_tool.cpp:116:34: warning: 'bo' may be used uninitialized in this function [-Wmaybe-uninitialized]
  116 |    v.bones.push_back(bo[i * 4 + 1]);
      |                                  ^
scene/resources/mesh_data_tool.cpp:103:12: warning: 'col' may be used uninitialized in this function [-Wmaybe-uninitialized]
  103 |    v.color = col[i];
      |    ~~~~~~~~^~~~~~~~
scene/resources/mesh_data_tool.cpp:101:10: warning: 'uv2' may be used uninitialized in this function [-Wmaybe-uninitialized]
  101 |    v.uv2 = uv2[i];
      |    ~~~~~~^~~~~~~~
scene/resources/mesh_data_tool.cpp:99:9: warning: 'uv' may be used uninitialized in this function [-Wmaybe-uninitialized]
   99 |    v.uv = uv[i];
      |    ~~~~~^~~~~~~
scene/resources/mesh_data_tool.cpp:97:49: warning: 'ta' may be used uninitialized in this function [-Wmaybe-uninitialized]
   97 |    v.tangent = Plane(ta[i * 4 + 0], ta[i * 4 + 1], ta[i * 4 + 2], ta[i * 4 + 3]);
      |                                                 ^
scene/resources/mesh_data_tool.cpp:95:13: warning: 'nr' may be used uninitialized in this function [-Wmaybe-uninitialized]
   95 |    v.normal = nr[i];
      |    ~~~~~~~~~^~~~~~~
```
```
./core/typedefs.h: In member function 'Ref<Mesh> Mesh::create_outline(float) const':
./core/typedefs.h:116:2: warning: 'ir' may be used uninitialized in this function [-Wmaybe-uninitialized]
  116 |  x = y;
      |  ^
scene/resources/mesh.cpp:375:8: note: 'ir' was declared here
  375 |   int *ir;
      |        ^~
```

All those are guarded by booleans to only be accessed when they have been set, so I wonder if it's a GCC bug. CC @marxin

**Steps to reproduce:**
```
/usr/bin/scons LINKFLAGS=-fuse-ld=gold -j7 p=linuxbsd warnings=extra disable_3d=yes tools=no target=release_debug 2>&1 | tee -a build.log
```
(There might be a more minimal set of options that triggers those warnings, it's just the one I've used for the above report.)

### PR DESCRIPTION
**Pull request by akien-mga**
Namely:
```
modules/basis_universal/register_types.cpp: In function 'Ref<Image> basis_universal_unpacker(const Vector<unsigned char>&)':
modules/basis_universal/register_types.cpp:266:15: warning: 'imgfmt' may be used uninitialized in this function [-Wmaybe-uninitialized]
  266 |  image->create(info.m_width, info.m_height, info.m_total_levels > 1, imgfmt, gpudata);
      |  ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
modules/basis_universal/register_types.cpp:255:39: warning: 'format' may be used uninitialized in this function [-Wmaybe-uninitialized]
  255 |    bool ret = tr.transcode_image_level(ptr, size, 0, i, dst + ofs, level.m_total_blocks - i, format);
      |               ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

```
servers/visual_server.cpp: In member function 'Error VisualServer::_surface_set_data(Array, uint32_t, uint32_t*, uint32_t, Vector<unsigned char>&, int, Vector<unsigned char>&, int, AABB&, Vector<AABB>&)':
servers/visual_server.cpp:636:15: warning: 'iw' may be used uninitialized in this function [-Wmaybe-uninitialized]
  636 |       copymem(&iw[i * 2], &v, 2);
      |               ^
```

```
./servers/visual/rasterizer_rd/render_pipeline_vertex_format_cache_rd.h: In member function 'void RasterizerSceneHighEndRD::_render_list(RenderingDevice::DrawListID, RenderingDevice::FramebufferFormatID, RasterizerSceneHighEndRD::RenderList::Element**, int, bool, RasterizerSceneHighEndRD::PassMode, bool, RID, RID)':
./servers/visual/rasterizer_rd/render_pipeline_vertex_format_cache_rd.h:83:73: warning: 'vertex_format' may be used uninitialized in this function [-Wmaybe-uninitialized]
   83 |   result = _generate_version(p_vertex_format_id, p_framebuffer_format_id);
      |                                                                         ^
servers/visual/rasterizer_rd/rasterizer_scene_high_end_rd.cpp:858:22: note: 'vertex_format' was declared here
  858 |   RD::VertexFormatID vertex_format;
      |                      ^~~~~~~~~~~~~
servers/visual/rasterizer_rd/rasterizer_scene_high_end_rd.cpp:812:17: warning: 'shader_version' may be used uninitialized in this function [-Wmaybe-uninitialized]
  812 |   ShaderVersion shader_version;
      |                 ^~~~~~~~~~~~~~
```

```
core/image.cpp: In member function 'Error Image::generate_mipmap_roughness(Image::RoughnessChannel, const Ref<Image>&)':
core/image.cpp:1683:11: warning: 'roughness' may be used uninitialized in this function [-Wmaybe-uninitialized]
 1683 |     float roughness;
      |           ^~~~~~~~~
```

----

The weird part is that those warnings aren't raised in all builds (and especially noted raised by our CI builds).

I got them when doing a build with `tools=no target=release_debug disable_3d=yes`:
```
/usr/bin/scons LINKFLAGS=-fuse-ld=gold -j7 p=linuxbsd warnings=extra disable_3d=yes tools=no target=release_debug 2>&1 | tee -a build.log
```

*Edit:* `disable_3d=yes` is not involved, the warnings appear without it too.

I also get more which appear to be false positives. Using GCC 9.3.0.

----

This and #37354 fix #37352.

### CODE REVIEW

File: core/image.cpp [hunk 1]
```diff
@@ -1680,7 +1680,7 @@ Error Image::generate_mipmap_roughness(RoughnessChannel p_roughness_channel, con
 				int pixel_ofs = y * w + x;
 				Color c = _get_color_at_ofs(ptr, pixel_ofs);
 
-				float roughness;
+				float roughness = 0;
```
Comment (akien-mga) [inline core/image.cpp]: This is a false positive as we handle all possible enum values in the switch... unless `p_roughness_channel` can be passed with a value outside the enum, in which case this is correct, but should we then add a `default: ERR_FAIL_V("Bug");` to all our switches...?

File: modules/basis_universal/register_types.cpp [hunk 2]
```diff
@@ -174,7 +174,8 @@ static Ref<Image> basis_universal_unpacker(const Vector<uint8_t> &p_buffer) {
 				//format = basist::transcoder_texture_format::cTFETC1; // get this from renderer
 				//imgfmt = Image::FORMAT_RGTC_RG;
 			} else {
-				//decompress
+				// FIXME: There wasn't anything here, but then imgformat is used uninitialized.
+				ERR_FAIL_V(image);
```
Comment (akien-mga) [inline modules/basis_universal/register_types.cpp]: If there's an actual valid image `format` and `imgfmt` that should be used here, please advise @reduz.

File: servers/visual/rasterizer_rd/rasterizer_scene_high_end_rd.cpp [hunk 3]
```diff
@@ -809,20 +808,18 @@ void RasterizerSceneHighEndRD::_render_list(RenderingDevice::DrawListID p_draw_l
 			}
 		}
 
-		ShaderVersion shader_version;
+		ShaderVersion shader_version = SHADER_VERSION_MAX; // Assigned to silence wrong -Wmaybe-initialized.
```
Comment (akien-mga) [inline servers/visual/rasterizer_rd/rasterizer_scene_high_end_rd.cpp]: Same as for roughness, this should never be used uninitialized unless `p_pass_mode` could be given an int value outside the enum.

File: servers/visual/rasterizer_rd/rasterizer_scene_high_end_rd.cpp [hunk 4]
```diff
@@ -855,7 +852,7 @@ void RasterizerSceneHighEndRD::_render_list(RenderingDevice::DrawListID p_draw_l
 
 		pipeline = &shader->pipelines[cull_variant][primitive][shader_version];
 
-		RD::VertexFormatID vertex_format;
+		RD::VertexFormatID vertex_format = 0;
```
Comment (akien-mga) [inline servers/visual/rasterizer_rd/rasterizer_scene_high_end_rd.cpp]: That one is a valid bug, this variable and the next two can end up uninitialized if `mesh_surface_get_arrays_and_format` errors out.

File: servers/visual_server.cpp [hunk 5]
```diff
@@ -617,6 +617,7 @@ Error VisualServer::_surface_set_data(Array p_arrays, uint32_t p_format, uint32_
 			} break;
 			case VS::ARRAY_INDEX: {
 
+				ERR_FAIL_NULL_V(iw, ERR_INVALID_DATA);
```
Comment (akien-mga) [inline servers/visual_server.cpp]: That also seems to be a valid bug, `iw` is only set at line 338 when `r_index_array.size() > 0`.
