### PR TITLE
Fixes issue that a viewport texture doesn't work with particle shader

### LINKED ISSUE #18984: Can't use viewport texture in particle shader
**Godot version:**
Last nights master

**OS/device including version:**
n/a

**Issue description:**
When using a viewport texture as the input for a sampler2D uniform in a particle shader, it doesn't give any results. 

Having a quick chat with @reduz he believes its due to the proxy texture that was introduced not long ago.

I'll have a look after work if I can fix it myself but in case someone else beats me to it or I forget.... :)

**Steps to reproduce:**
Create a viewport, render something meaningful to it.
Create a particle shader, add a sampler2D, do something that effects the particles based on the contents of the texture
Assign a viewport texture linked to the viewport to the uniform.

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Simple fix that makes viewport textures work with shaders

Fixes #18984

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @karroffel in case it's relevant for the gles2 renderer too.

File: drivers/gles3/rasterizer_storage_gles3.cpp [hunk 1]
```diff
@@ -5895,7 +5895,10 @@ void RasterizerStorageGLES3::update_particles() {
 							tex = resources.white_tex;
 						} break;
 					}
+				} else if (t->proxy && t->proxy->tex_id) {
 
+					target = t->proxy->target;
+					tex = t->proxy->tex_id;
 				} else {
 
 					target = t->target;
```
Comment (karroffel) [inline drivers/gles3/rasterizer_storage_gles3.cpp]: You could have used `t->get_ptr()->target` here instead, not adding a new else path. The `get_ptr()` checks if a proxy exists and returns it in that case, otherwise returns `this`. I think that is used in some other places as well, so might be worth using that instead.

Comment (BastiaanOlij) [reply drivers/gles3/rasterizer_storage_gles3.cpp]: ah, that explains why I could only find the fix in the sky shader.
I'm about to go to sleep, if no-one has fixed this by tomorrow I'll change both the sky shader and this to use get_ptr()
