### PR TITLE
Make particles with DISABLE_Z active respect ALIGN_Y. Fixes #12865

### LINKED ISSUE #12865: flag_align_y in 2D particles has no effect
**Operating system or device, Godot version:** Ubunt 16.04, Godot 3 Alpha 2 Snapshot

**Issue description:** Trying to align particles to their velocity vector in 2D doesn't appear to be working. They don't react to the flag_align_y prop, unless I disable flag_disable_z. When Disable Z is not set, however, they appear to almost immediately be clippped away.

In the code I noticed how flag_align_y is only ever read when flag_disable_z is false, which could have been an oversight when introducing GPU particles?
Relevant piece of code: https://github.com/godotengine/godot/blob/045bf23207754f17184770ad4371cf7bff582468/scene/3d/particles.cpp#L837
Relevant commit: https://github.com/godotengine/godot/commit/95560e02c5eed3561996ed2b1d1e47e26e8bb81c#diff-a63a9c2c6f9e0e94d178968a9fd8ab36L754

**Steps to reproduce:** Use a line as particle texture, enable spread in process material, try toggling the align flags.

**Minimal sample:** [particle-bug-12865.zip](https://github.com/godotengine/godot/files/1464882/particle-bug-12865.zip)

### PR DESCRIPTION
**Pull request by tom95**
This fixes bug #12865, I essentially just copied the code that handles `FLAG_ALIGN_Y` from the else-branch of `FLAG_DISABLE_Z` and adjusted it to leave the z coordinate untouched.

### CODE REVIEW

File: scene/3d/particles.cpp [hunk 1]
```diff
@@ -836,9 +836,15 @@ void ParticlesMaterial::_update_shader() {
 
 	if (flags[FLAG_DISABLE_Z]) {
 
-		code += "	TRANSFORM[0] = vec4(cos(CUSTOM.x),-sin(CUSTOM.x),0.0,0.0);\n";
-		code += "	TRANSFORM[1] = vec4(sin(CUSTOM.x),cos(CUSTOM.x),0.0,0.0);\n";
-		code += "	TRANSFORM[2] = vec4(0.0,0.0,1.0,0.0);\n";
+		if (flags[FLAG_ALIGN_Y_TO_VELOCITY]) {
+			code += "	if (length(VELOCITY) > 0.0) { TRANSFORM[1].xyz = normalize(VELOCITY); } else { TRANSFORM[1].xyz = normalize(TRANSFORM[1].xyz); }\n";
+			code += "	TRANSFORM[0].xyz = normalize(cross(normalize(TRANSFORM[1].xyz),normalize(TRANSFORM[2].xyz)));\n";
```
Comment (tagcup) [inline scene/3d/particles.cpp]: Just a single normalize should suffice here

Comment (tom95) [reply scene/3d/particles.cpp]: Thank you, missed that!

**Comment by Noshyaar** [comment]
Thank you for contributing! Changes LGTM. Could you please squash commits together? ([PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request))

**Comment by tom95** [comment]
Done! Thanks for handling this so swiftly!

File: scene/3d/particles.cpp [hunk 2]
```diff
@@ -836,9 +836,15 @@ void ParticlesMaterial::_update_shader() {
 
 	if (flags[FLAG_DISABLE_Z]) {
 
-		code += "	TRANSFORM[0] = vec4(cos(CUSTOM.x),-sin(CUSTOM.x),0.0,0.0);\n";
-		code += "	TRANSFORM[1] = vec4(sin(CUSTOM.x),cos(CUSTOM.x),0.0,0.0);\n";
-		code += "	TRANSFORM[2] = vec4(0.0,0.0,1.0,0.0);\n";
+		if (flags[FLAG_ALIGN_Y_TO_VELOCITY]) {
+			code += "	if (length(VELOCITY) > 0.0) { TRANSFORM[1].xyz = normalize(VELOCITY); } else { TRANSFORM[1].xyz = normalize(TRANSFORM[1].xyz); }\n";
+			code += "	TRANSFORM[0].xyz = cross(normalize(TRANSFORM[1].xyz),TRANSFORM[2].xyz);\n";
```
Comment (tagcup) [inline scene/3d/particles.cpp]: I meant normalize should be the last step, like
`TRANSFORM[0].xyz = normalize(cross(TRANSFORM[1].xyz,TRANSFORM[2].xyz));`
to ensure the result is a unit vector

Comment (tom95) [reply scene/3d/particles.cpp]: I can see how that's more future proof, so I changed it accordingly.

In the current usage though, the statement could not have resulted in an unormalized value if TRANSFORM[1] gets normalized.
