### PR TITLE
Fix shader for SkeletonGizmo to follow renderer's reversed-z change

### LINKED ISSUE #92773: Skeleton gizmo is hidden behind the Node
### Tested versions

Reproduced in 4.3.beta1
Not reproduced in 4.2.stable

### System information

Any

### Issue description

When a skeleton is selected, the bone gizmo should be drawn, but it is drawn behind the object.

image

### Steps to reproduce

Select Skeleton3D / Enter bone edit mode

### Minimal reproduction project (MRP)

[SkeletonProj.zip](https://github.com/user-attachments/files/15570132/SkeletonProj.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
- Fixes https://github.com/godotengine/godot/issues/92773

Co-authored-by: @lyuma 

Renderer has make coordinate of the z inverted to adopt reversed-z, so the skeleton gizmo shader must follow the change.

image

### CODE REVIEW

**Review by fire — APPROVED** [review]

File: editor/plugins/skeleton_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -922,7 +922,7 @@ void vertex() {
 
 	VERTEX = VERTEX;
 	POSITION = PROJECTION_MATRIX * VIEW_MATRIX * MODEL_MATRIX * vec4(VERTEX.xyz, 1.0);
-	POSITION.z = mix(POSITION.z, 0.0, 0.999);
+	POSITION.z = mix(POSITION.z, POSITION.w, 0.999);
```
Comment (clayjohn) [inline editor/plugins/skeleton_3d_editor_plugin.cpp:925]:
```suggestion
	POSITION.z = mix(POSITION.z, 1.0, 0.999);
```

File: editor/plugins/skeleton_3d_editor_plugin.cpp [hunk 2]
```diff
@@ -1201,7 +1201,7 @@ void vertex() {
 	}
 	VERTEX = VERTEX;
 	POSITION = PROJECTION_MATRIX * VIEW_MATRIX * MODEL_MATRIX * vec4(VERTEX.xyz, 1.0);
-	POSITION.z = mix(POSITION.z, 0, 0.998);
+	POSITION.z = mix(POSITION.z, POSITION.w, 0.998);
```
Comment (clayjohn) [inline editor/plugins/skeleton_3d_editor_plugin.cpp:1204]:
```suggestion
	POSITION.z = mix(POSITION.z, 1.0, 0.998);
```

File: editor/plugins/skeleton_3d_editor_plugin.cpp (hunk 1 above)
Comment (lyuma) [reply editor/plugins/skeleton_3d_editor_plugin.cpp:925]: I believe it is correct to mix towards POSITION.w. The GPU will perform a perspective divide internally, effectively POSITION.xyz /= POSITION.w
The goal is to produce a value close to 1.0 post-perspective divide, so we want the GPU to calculate POSITION.z = 1.0 * POSITION.w / POSITION.w

Comment (clayjohn) [reply editor/plugins/skeleton_3d_editor_plugin.cpp:925]: That's right

**Review by clayjohn — APPROVED** [review]

File: editor/plugins/skeleton_3d_editor_plugin.cpp (hunk 1 above)
Comment (TokageItLab) [reply editor/plugins/skeleton_3d_editor_plugin.cpp:925]: If apply it, the order seems to be reversed.

before:
image

apply it:
image

**Comment by akien-mga** [comment]
Thanks!
