### PR TITLE
ImporterMesh: Validate triangle indices array size is a multiple of 3

### LINKED ISSUE #98519: export big 400mb glb file 99% crash
### Tested versions

[4.4 dev3](https://godotengine.org/download/archive/4.4-dev3)

### System information

win10 21H2,Vulkan API 1.2.0

### Issue description

B`}0_G%H8QZC3B3Q}UFUW{D

```
Godot Engine v4.4.dev3.official.f4af8201b - https://godotengine.org
libpng warning: iCCP: cHRM chunk does not match sRGB
Vulkan 1.3.242 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce RTX 3080

ERROR: Basis [X: (1, 0, 0), Y: (0, 0, 0), Z: (0, 0, 1)] must be normalized in order to be casted to a Quaternion. Use get_rotation_quaternion() or call orthonormalized() if the Basis contains linearly independent vectors.
   at: (core/math/basis.cpp:725)
ERROR: FATAL: Index p_index = 620 is out of bounds (count = 620).
   at: operator[] (./core/templates/local_vector.h:177)

================================================================
CrashHandlerException: Program crashed with signal 4
Engine version: Godot Engine v4.4.dev3.official (f4af8201bac157b9d47e336203d3e8a8ef729de2)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] error(-1): no debug info in PE/COFF executable
[2] error(-1): no debug info in PE/COFF executable
[3] error(-1): no debug info in PE/COFF executable
[4] error(-1): no debug info in PE/COFF executable
[5] error(-1): no debug info in PE/COFF executable
[6] error(-1): no debug info in PE/COFF executable
[7] error(-1): no debug info in PE/COFF executable
[8] error(-1): no debug info in PE/COFF executable
[9] error(-1): no debug info in PE/COFF executable
[10] error(-1): no debug info in PE/COFF executable
[11] error(-1): no debug info in PE/COFF executable
[12] error(-1): no debug info in PE/COFF executable
[13] error(-1): no debug info in PE/COFF executable
[14] error(-1): no debug info in PE/COFF executable
[15] error(-1): no debug info in PE/COFF executable
[16] error(-1): no debug info in PE/COFF executable
[17] error(-1): no debug info in PE/COFF executable
[18] error(-1): no debug info in PE/COFF executable
[19] error(-1): no debug info in PE/COFF executable
[20] error(-1): no debug info in PE/COFF executable
[21] error(-1): no debug info in PE/COFF executable
[22] error(-1): no debug info in PE/COFF executable
[23] error(-1): no debug info in PE/COFF executable
[24] error(-1): no debug info in PE/COFF executable
[25] error(-1): no debug info in PE/COFF executable
[26] error(-1): no debug info in PE/COFF executable
[27] error(-1): no debug info in PE/COFF executable
-- END OF BACKTRACE --
================================================================

```

### Steps to reproduce

1. create new project
2. export  glb file
3. 99% crash

### Minimal reproduction project (MRP)

sry. github file size too big is 25MB.  Please rename it, otherwise it cannot be opened.

### PR DESCRIPTION
**Pull request by aaronfranke**
This PR fixes https://github.com/godotengine/godot/issues/98519. That test file is very invalid, but Godot still shouldn't crash when trying to import it. The cause of the crash was trying to generate LODs on a mesh with an indices array with a size that was not a multiple of 3, which crashes the `meshoptimizer` library which expects a multiple of 3 size (the library already has asserts for this, but those aren't compiled in with Godot). The test file now looks like this when imported:

Screenshot 2025-08-16 at 1 04 35 AM

Only a single line change in this PR is actually required to prevent the crash, this of code line added to `ImporterMesh::generate_lods`:

```cpp
ERR_FAIL_COND_MSG(index_count % 3 != 0, "ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got " + itos(index_count) + " indices. Cannot generate LODs for this invalid mesh.");
```

Here is the console output with just that single line change:
<details>

```
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 173 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 174 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 175 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 176 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 184 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 185 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 186 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 187 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 195 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 196 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 197 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 198 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 206 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 207 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 208 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 209 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 217 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 218 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 219 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 220 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 228 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 229 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 230 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 231 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 239 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 240 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 241 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 242 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 250 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 251 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 252 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 253 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 261 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 262 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 263 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 264 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 272 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 273 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 274 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 275 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 283 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 284 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 285 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 286 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 294 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 295 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 296 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 297 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 305 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 306 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 307 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 308 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 316 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 317 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 318 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 319 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 327 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 328 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 329 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 330 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 338 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 339 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 340 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 341 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 349 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 350 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 351 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 352 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 360 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 361 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 362 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 363 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 371 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 372 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 373 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 374 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 382 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 383 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 384 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 385 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 393 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 394 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 395 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 396 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 404 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 405 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 406 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 407 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 415 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 416 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 417 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 418 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 426 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 427 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 428 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 429 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 437 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 438 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 439 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 440 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 448 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 449 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 450 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 451 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 497 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 498 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 499 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 500 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 525 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 526 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 527 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 528 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 620 indices. Cannot generate LODs for this invalid mesh.
  ERROR: scene/resources/3d/importer_mesh.cpp:672 - Index index = 620 is out of bounds (vertex_count = 620).
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 419 indices. Cannot generate LODs for this invalid mesh.
  ERROR: scene/resources/3d/importer_mesh.cpp:672 - Index index = 419 is out of bounds (vertex_count = 419).
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 445 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 433 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 424 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 439 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 521 indices. Cannot generate LODs for this invalid mesh.
  ERROR: scene/resources/3d/importer_mesh.cpp:672 - Index index = 521 is out of bounds (vertex_count = 521).
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 646 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 605 indices. Cannot generate LODs for this invalid mesh.
  ERROR: scene/resources/3d/importer_mesh.cpp:672 - Index index = 605 is out of bounds (vertex_count = 605).
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 322 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 4834 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 13394 indices. Cannot generate LODs for this invalid mesh.
  ERROR: scene/resources/3d/importer_mesh.cpp:672 - Index index = 13394 is out of bounds (vertex_count = 13394).
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 18391 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 13394 indices. Cannot generate LODs for this invalid mesh.
  ERROR: scene/resources/3d/importer_mesh.cpp:672 - Index index = 13394 is out of bounds (vertex_count = 13394).
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 4834 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 18391 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 13394 indices. Cannot generate LODs for this invalid mesh.
  ERROR: scene/resources/3d/importer_mesh.cpp:672 - Index index = 13394 is out of bounds (vertex_count = 13394).
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 4375 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 5699 indices. Cannot generate LODs for this invalid mesh.
  ERROR: scene/resources/3d/importer_mesh.cpp:672 - Index index = 5699 is out of bounds (vertex_count = 5699).
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 18391 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 4375 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 18391 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 13394 indices. Cannot generate LODs for this invalid mesh.
  ERROR: scene/resources/3d/importer_mesh.cpp:672 - Index index = 13394 is out of bounds (vertex_count = 13394).
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 18391 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 18391 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 18391 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 18391 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 18391 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 13394 indices. Cannot generate LODs for this invalid mesh.
  ERROR: scene/resources/3d/importer_mesh.cpp:672 - Index index = 13394 is out of bounds (vertex_count = 13394).
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 5699 indices. Cannot generate LODs for this invalid mesh.
  ERROR: scene/resources/3d/importer_mesh.cpp:672 - Index index = 5699 is out of bounds (vertex_count = 5699).
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 4834 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 4375 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 1171 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 18391 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 18391 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 18391 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 18391 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 18391 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 18391 indices. Cannot generate LODs for this invalid mesh.
  ERROR: ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got 484 indices. Cannot generate LODs for this invalid mesh.
```

</details>

However, I also added some code in GLTFDocument to check for invalid meshes, catching the problem earlier, and entirely skips including broken meshes in the scene (rather than just skipping LOD generation for them).

Here is the console output with all the changes in this PR:
<details>

```
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 173 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 174 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 175 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 176 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 184 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 185 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 186 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 187 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 195 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 196 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 197 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 198 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 206 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 207 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 208 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 209 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 217 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 218 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 219 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 220 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 228 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 229 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 230 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 231 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 239 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 240 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 241 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 242 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 250 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 251 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 252 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 253 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 261 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 262 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 263 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 264 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 272 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 273 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 274 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 275 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 283 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 284 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 285 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 286 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 294 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 295 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 296 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 297 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 305 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 306 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 307 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 308 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 316 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 317 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 318 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 319 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 327 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 328 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 329 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 330 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 338 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 339 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 340 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 341 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 349 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 350 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 351 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 352 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 360 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 361 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 362 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 363 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 371 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 372 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 373 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 374 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 382 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 383 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 384 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 385 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 393 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 394 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 395 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 396 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 404 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 405 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 406 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 407 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 415 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 416 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 417 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 418 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 426 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 427 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 428 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 429 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 437 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 438 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 439 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 440 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 448 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 449 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 450 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 451 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 497 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 498 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 499 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 500 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 525 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 526 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 527 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:1053 - glTF import: Invalid accessor count 0 for accessor at index 528 while importing file 'Quarry_Slate'. Accessor count must be greater than 0.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 31 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 620 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 38 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 419 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 40 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 445 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 41 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 433 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 43 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 424 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 44 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 439 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 47 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 521 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 48 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 646 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 49 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 605 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 50 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 322 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 51 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 4834 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 52 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 13394 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 53 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 18391 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 54 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 13394 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 56 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 4834 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 57 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 18391 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 58 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 13394 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 59 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 4375 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 60 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 5699 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 61 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 18391 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 62 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 4375 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 63 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 18391 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 64 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 13394 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 81 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 18391 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 82 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 18391 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 84 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 18391 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 85 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 18391 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 90 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 18391 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 91 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 13394 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 93 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 5699 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 94 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 4834 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 95 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 4375 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 96 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 1171 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 97 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 18391 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 98 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 18391 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 99 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 18391 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 100 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 18391 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 101 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 18391 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 103 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 18391 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 112 surface 0 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 484 vertices.
  ERROR: modules/gltf/gltf_document.cpp:3565 - glTF import: Mesh 112 surface 1 in file Quarry_Slate is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got 484 vertices.
```

</details>

### CODE REVIEW

**Review by fire — APPROVED** [review]

**Comment by fire** [comment]
Philosophically should we fail to import or import with missing shapes?

**Comment by Repiteo** [comment]
I would assume this should cause an early return with `ERR_PARSE_ERROR`, rather than just printing an error. But I'm also not as familiar with this portion of code, so maybe it's warranted in this context to just truncate and move on? Would appreciate some insight here!

**Comment by fire** [comment]
Philosophically I think we fail to import since there's an assumption that an import will have everything loaded...

File: modules/gltf/gltf_document.cpp [hunk 1]
```diff
@@ -3340,13 +3340,17 @@ Error GLTFDocument::_parse_meshes(Ref<GLTFState> p_state) {
 			Vector<int> indices_vec4_mapping;
 			if (mesh_prim.has("indices")) {
 				indices = _decode_accessor_as_ints(p_state, mesh_prim["indices"], false);
-				const int is = indices.size();
+				const int index_count = indices.size();
 
 				if (primitive == Mesh::PRIMITIVE_TRIANGLES) {
+					if (index_count % 3 != 0) {
+						ERR_PRINT("glTF import: Mesh " + itos(i) + " surface " + itos(j) + " in file " + p_state->filename + " is invalid. Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got " + itos(index_count) + " indices.");
```
Comment (AThousandShips) [inline modules/gltf/gltf_document.cpp]:
```suggestion
						ERR_PRINT("glTF import: Mesh " + itos(i) + " surface " + itos(j) + " in file " + p_state->filename + " is invalid. Indexed triangle meshes MUST have an index array with a size that is a multiple of 3, but got " + itos(index_count) + " indices.");
```
No plural here in English

File: modules/gltf/gltf_document.cpp [hunk 2]
```diff
@@ -3556,11 +3560,15 @@ Error GLTFDocument::_parse_meshes(Ref<GLTFState> p_state) {
 				// Generate indices because they need to be swapped for CW/CCW.
 				const Vector<Vector3> &vertices = array[Mesh::ARRAY_VERTEX];
 				ERR_FAIL_COND_V(vertices.is_empty(), ERR_PARSE_ERROR);
-				const int vs = vertices.size();
-				indices.resize(vs);
+				const int vertex_count = vertices.size();
+				if (vertex_count % 3 != 0) {
+					ERR_PRINT("glTF import: Mesh " + itos(i) + " surface " + itos(j) + " in file " + p_state->filename + " is invalid. Non-indexed triangle meshes MUST have a vertices array with a size that is a multiple of 3, but got " + itos(vertex_count) + " vertices.");
```
Comment (AThousandShips) [inline modules/gltf/gltf_document.cpp]:
```suggestion
					ERR_PRINT("glTF import: Mesh " + itos(i) + " surface " + itos(j) + " in file " + p_state->filename + " is invalid. Non-indexed triangle meshes MUST have a vertex array with a size that is a multiple of 3, but got " + itos(vertex_count) + " vertices.");
```

File: scene/resources/3d/importer_mesh.cpp [hunk 3]
```diff
@@ -322,6 +322,7 @@ void ImporterMesh::generate_lods(float p_normal_merge_angle, Array p_bone_transf
 		if (index_count == 0) {
 			continue; //no lods if no indices
 		}
+		ERR_FAIL_COND_MSG(index_count % 3 != 0, "ImporterMesh::generate_lods: Indexed triangle meshes MUST have an indices array with a size that is a multiple of 3, but got " + itos(index_count) + " indices. Cannot generate LODs for this invalid mesh.");
```
Comment (AThousandShips) [inline scene/resources/3d/importer_mesh.cpp]:
```suggestion
		ERR_FAIL_COND_MSG(index_count % 3 != 0, "ImporterMesh::generate_lods: Indexed triangle meshes MUST have an index array with a size that is a multiple of 3, but got " + itos(index_count) + " indices. Cannot generate LODs for this invalid mesh.");
```

**Review by AThousandShips — APPROVED** [review]

**Comment by aaronfranke** [comment]
Changed to an error as requested:

Screenshot 2025-08-18 at 6 36 10 AM

**Comment by Repiteo** [comment]
Thanks!
