### PR TITLE
Fixed PackedByteArray GDScript functions

### LINKED ISSUE #36611: Project crash when using PackedByteArray.compress
**Godot version:**
4.0.dev.custom_build. ed0f1940c

**OS/device including version:**
Ubuntu 19.10

**Issue description:**
Invalid read from Address Sanitizer(later cause crash)
```
==16673==ERROR: AddressSanitizer: heap-use-after-free on address 0x60d000681154 at pc 0x000001810264 bp 0x7ffefdac85c0 sp 0x7ffefdac85b0
READ of size 4 at 0x60d000681154 thread T0
    #0 0x1810263 in CowData<unsigned char>::size() const core/cowdata.h:128
    #1 0x191f621 in Vector<unsigned char>::size() const core/vector.h:84
    #2 0xfa5fdb1 in _VariantCall::_call_PackedByteArray_compress(Variant&, Variant&, Variant const**) core/variant_call.cpp:624
    #3 0xfa25704 in _VariantCall::FuncData::call(Variant&, Variant&, Variant const**, int, Callable::CallError&) core/variant_call.cpp:121
    #4 0xf9370d9 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Callable::CallError&) core/variant_call.cpp:1235
    #5 0x41098bb in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1102
    #6 0x3f6a251 in GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1305
    #7 0xf65992d in Object::call(StringName const&, Variant const**, int, Callable::CallError&) core/object.cpp:883
    #8 0xf936df7 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Callable::CallError&) core/variant_call.cpp:1222
    #9 0x41098bb in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1102
    #10 0x3f6a76a in GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1321
    #11 0xa116359 in Node::_notification(int) scene/main/node.cpp:63
    #12 0x1927d39 in Node::_notificationv(int, bool) scene/main/node.h:46
    #13 0x192a1e3 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #14 0xba47fa3 in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:38
    #15 0xf65a252 in Object::notification(int, bool) core/object.cpp:913
    #16 0xa234b87 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:988
    #17 0xa224db2 in SceneTree::idle(float) scene/main/scene_tree.cpp:527
    #18 0x17bb12e in Main::iteration() main/main.cpp:2062
    #19 0x16c5a60 in OS_X11::run() platform/x11/os_x11.cpp:3321
    #20 0x1641889 in main platform/x11/godot_x11.cpp:56
    #21 0x7fadc3a5d1e2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x271e2)
    #22 0x164149d in _start (/usr/bin/godots+0x164149d)

0x60d000681154 is located 4 bytes inside of 144-byte region [0x60d000681150,0x60d0006811e0)
freed by thread T0 here:
    #0 0x7fadc4ce36ef in __interceptor_free (/lib/x86_64-linux-gnu/libasan.so.5+0x10d6ef)
    #1 0xfc50995 in Memory::free_static(void*, bool) core/os/memory.cpp:178
    #2 0x164229c in CowData<wchar_t>::_unref(void*) core/cowdata.h:213
    #3 0x1641e56 in CowData<wchar_t>::~CowData() core/cowdata.h:370
    #4 0x1641ca9 in String::~String() core/ustring.h:126
    #5 0x100e45c2 in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:350
    #6 0xce0ae44 in ResourceInteractiveLoaderText::_parse_ext_resource(VariantParser::Stream*, Ref<Resource>&, int&, String&) scene/resources/resource_format_text.cpp:172
    #7 0xce6d293 in ResourceInteractiveLoaderText::_parse_ext_resources(void*, VariantParser::Stream*, Ref<Resource>&, int&, String&) scene/resources/resource_format_text.h:77
    #8 0xfb44423 in VariantParser::parse_value(VariantParser::Token&, Variant&, VariantParser::Stream*, int&, String&, VariantParser::ResourceParser*) core/variant_parser.cpp:880
    #9 0xfb4dd34 in VariantParser::parse_tag_assign_eof(VariantParser::Stream*, int&, String&, VariantParser::Tag&, String&, Variant&, VariantParser::ResourceParser*, bool) core/variant_parser.cpp:1449
    #10 0xce0f4c8 in ResourceInteractiveLoaderText::_parse_node_tag(VariantParser::ResourceParser&) scene/resources/resource_format_text.cpp:274
    #11 0xce28271 in ResourceInteractiveLoaderText::poll() scene/resources/resource_format_text.cpp:629
    #12 0x100db6ee in ResourceFormatLoader::load(String const&, String const&, Error*) core/io/resource_loader.cpp:197
    #13 0x100e10d2 in ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) core/io/resource_loader.cpp:270
    #14 0x100e3d8a in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:401
    #15 0x17b395e in Main::start() main/main.cpp:1892
    #16 0x16417b9 in main platform/x11/godot_x11.cpp:55
    #17 0x7fadc3a5d1e2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x271e2)

previously allocated by thread T0 here:
    #0 0x7fadc4ce3f1e in __interceptor_realloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10df1e)
    #1 0xfc5051f in Memory::realloc_static(void*, unsigned long, bool) core/os/memory.cpp:137
    #2 0x2d86f6e in CowData<wchar_t>::resize(int) core/cowdata.h:283
    #3 0x6c5cd79 in String::resize(int) core/ustring.h:154
    #4 0xf871919 in String::operator+=(String const&) core/ustring.cpp:283
    #5 0xf8715cc in String::operator+(String const&) const core/ustring.cpp:259
    #6 0xf893047 in String::simplify_path() const core/ustring.cpp:3314
    #7 0xf6bef27 in ProjectSettings::localize_path(String const&) const core/project_settings.cpp:65
    #8 0x100e2fd8 in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:354
    #9 0xce0ae44 in ResourceInteractiveLoaderText::_parse_ext_resource(VariantParser::Stream*, Ref<Resource>&, int&, String&) scene/resources/resource_format_text.cpp:172
    #10 0xce6d293 in ResourceInteractiveLoaderText::_parse_ext_resources(void*, VariantParser::Stream*, Ref<Resource>&, int&, String&) scene/resources/resource_format_text.h:77
    #11 0xfb44423 in VariantParser::parse_value(VariantParser::Token&, Variant&, VariantParser::Stream*, int&, String&, VariantParser::ResourceParser*) core/variant_parser.cpp:880
    #12 0xfb4dd34 in VariantParser::parse_tag_assign_eof(VariantParser::Stream*, int&, String&, VariantParser::Tag&, String&, Variant&, VariantParser::ResourceParser*, bool) core/variant_parser.cpp:1449
    #13 0xce0f4c8 in ResourceInteractiveLoaderText::_parse_node_tag(VariantParser::ResourceParser&) scene/resources/resource_format_text.cpp:274
    #14 0xce28271 in ResourceInteractiveLoaderText::poll() scene/resources/resource_format_text.cpp:629
    #15 0x100db6ee in ResourceFormatLoader::load(String const&, String const&, Error*) core/io/resource_loader.cpp:197
    #16 0x100e10d2 in ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) core/io/resource_loader.cpp:270
    #17 0x100e3d8a in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:401
    #18 0x17b395e in Main::start() main/main.cpp:1892
    #19 0x16417b9 in main platform/x11/godot_x11.cpp:55
    #20 0x7fadc3a5d1e2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x271e2)

SUMMARY: AddressSanitizer: heap-use-after-free core/cowdata.h:128 in CowData<unsigned char>::size() const
```
**Steps to reproduce:**

**Minimal reproduction project:**
[QQQQ.zip](https://github.com/godotengine/godot/files/4263342/QQQQ.zip)

### PR DESCRIPTION
**Pull request by Wavesonics**
It looks like with the switch to PackedByteArray from the PoolArray types, the GDScript functions weren't updated correctly.
`p_self._data.packed_array` needs to be used instead of `p_self._data._mem`

These functions are now fixed:
- _call_PackedByteArray_get_string_from_ascii
- _call_PackedByteArray_get_string_from_utf8
- _call_PackedByteArray_compress
- _call_PackedByteArray_decompress
- _call_PackedByteArray_hex_encode

Edit: Fixes #36611

### CODE REVIEW

**Comment by Wavesonics** [comment]
Tested with this script:
```GDScript
var data: PackedByteArray

func _ready():
	data = PackedByteArray()
	for i in 20:
		data.append(72)
		data.append(101)
		data.append(108)
		data.append(108)
		data.append(111)
	data.append(0)
	
	var plain := "Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  Test PBA functions  "
	var utf8Bytes := plain.to_utf8()
	print(utf8Bytes)
	print("utf8Bytes: %d" % utf8Bytes.size())
	
	var xStr := utf8Bytes.get_string_from_utf8()
	print("xStr: " + xStr)
	
	var compressedBytes := utf8Bytes.compress(File.COMPRESSION_GZIP)
	
	print("compressedBytes: %d" % compressedBytes.size())
	
	var decompressedBytes := compressedBytes.decompress(utf8Bytes.size(), File.COMPRESSION_GZIP)
	
	print("decompressedBytes: %d" % decompressedBytes.size())
	
	var decStr := decompressedBytes.get_string_from_utf8()
	print("decStr: %d" % decStr.length())
	print("'%s'" % decStr)
	
	var decStrAscii := decompressedBytes.get_string_from_ascii()
	print("decStr: %d" % decStrAscii.length())
	print("'%s'" % decStrAscii)
```

File: core/variant_call.cpp [hunk 1]
```diff
@@ -596,47 +596,50 @@ struct _VariantCall {
...
 	static void _call_PackedByteArray_get_string_from_utf8(Variant &r_ret, Variant &p_self, const Variant **p_args) {
-		PackedByteArray *ba = reinterpret_cast<PackedByteArray *>(p_self._data._mem);
+		Variant::PackedArrayRef<uint8_t> *ba = reinterpret_cast<Variant::PackedArrayRef<uint8_t> *>(p_self._data.packed_array);
+
 		String s;
-		if (ba->size() > 0) {
-			const uint8_t *r = ba->ptr();
-			s.parse_utf8((const char *)r, ba->size());
+		if (ba->array.size() > 0) {
+			print_line("BA size OK");
```
Comment (Faless) [inline core/variant_call.cpp:618]: Leftover `print_line`.

Comment (Wavesonics) [reply core/variant_call.cpp]: removed it

**Review by Faless — APPROVED** [review]
Great job :medal_sports: !

**Comment by Faless** [comment]
Thanks!

**Comment by asheraryam** [comment]
Would be nice if this can be cherry-picked to 3.2.x in the next few months as I'm using these compression functions in production atm.

**Comment by nathanfranke** [comment]
Can't be cherry picked, because `Packed` ≠ `Pool`. Is this same issue in 3.2? Someone can make a PR specifically for 3.2

**Comment by asheraryam** [comment]
Well now that you mention it, I think this isn't an issue on 3.x, I just mixed up between projects.

I'll open a new issue if it comes up with the 3.x branch instead of master.
