### PR TITLE
Metal: Ensure position invariance is captured from SPIRV-Cross

### LINKED ISSUE #99029: World Triplanar broken on Mac - 4.4.dev3+
### Tested versions

Reproducible in 4.4.dev3 and 4.4.dev4. Not reproducible in 4.3 stable.

### System information

Godot v4.4.dev4 - macOS 14.5.0 - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M1 Max (Apple7) - Apple M1 Max (10 threads)

### Issue description

Using world Triplanar on spatial material results in black artifacts.

### Steps to reproduce

- Create a new project in Godot 4.4.dev3+
- Create a new 3d scene
- Add new MeshInstance with plane
- Assign a new material override
- Set the Triplanar and world Triplanar flags on material
- Move Camera in editor. Issue persists as well during runtime.

### Minimal reproduction project (MRP)

[world-triplanar-4.4.zip](https://github.com/user-attachments/files/17692408/world-triplanar-4.4.zip)

### PR DESCRIPTION
**Pull request by stuartcarnie**
Closes #99029

This PR ensures that position invariance is captured from SPIRV-Cross and subsequently used as a compilation option to the Metal shader compiler.

### CODE REVIEW

File: drivers/metal/rendering_device_driver_metal.mm [hunk 1]
```diff
@@ -2293,6 +2302,8 @@ void deserialize(BufReader &p_reader) {
 
 		ShaderStageData stage_data;
 		stage_data.stage = v.shader_stage;
+		stage_data.is_position_invariant = compiler.is_position_invariant();
+		stage_data.supports_fast_math = !entry_point.flags.get(spv::ExecutionModeSignedZeroInfNanPreserve);
```
Comment (clayjohn) [inline drivers/metal/rendering_device_driver_metal.mm:2306]: I assume this is unrelated, but safe?

**Review by clayjohn — APPROVED** [review]
Looks good to me! Great work tracking this down

File: drivers/metal/rendering_device_driver_metal.mm (hunk 1 above)
Comment (stuartcarnie) [reply drivers/metal/rendering_device_driver_metal.mm:2306]: It is, and incidentally, MoltenVK defaults to always enabling fast math, so I've done the same.
