### PR TITLE
LSP: Don't poll during editor setup

### LINKED ISSUE #108128: Error on Godot editor load if external editor is attached to Godot LSP: "Attempt to call a method on a placeholder instance. Check if the script is in tool mode."
### Tested versions

- Godot Version 4.4.1 stable
- Godot Version 4.4.0 stable

_(I believe 4.3 also exhibited this behavior.)_

Note this happens on my Windows _and_ my macOS machine.

### System information

Godot v4.4.1.stable - macOS Sequoia (15.5.0) - Multi-window, 2 monitors - Metal (Forward+) - integrated Apple M1 Max (Apple7) - Apple M1 Max (10 threads)

### Issue description

Related to this Terrain3D issue: https://github.com/TokisanGames/Terrain3D/issues/681#issuecomment-3017490763

**However, I am very sure this is _not_ a Terrain3D issue, but rather a Godot / Godot LSP issue.**

When I have an external editor attached to the Godot LSP (I've tested both Cursor/VSCode with `godot-tools` and Sublime Text with [SublimeGodot](https://github.com/dementive/SublimeGodot)), and I reload a project, it gives this error:

```
ERROR: res://addons/terrain_3d/src/editor_plugin.gd:55
Invalid call function 'initialize' in base 'PanelContainer (asset_dock.gd)':
Attempt to call a method on a placeholder instance. Check if the script is in tool mode.
```

If I reload the project _without_ the LSP client attached (Cursor/Sublime Text not running), it loads just fine.

Additionally, if I add a class_name to the [`asset_dock.gd` file](https://github.com/TokisanGames/Terrain3D/blob/main/project/addons/terrain_3d/src/asset_dock.gd#L4) and update the [`editor_plugin.gd`](https://github.com/TokisanGames/Terrain3D/blob/9e846e53a1fc93c6b9c4985befd0e1e210096049/project/addons/terrain_3d/src/editor_plugin.gd#L27) file to use that new class name, it loads just fine.

This makes me think it's some sort of load order issue when the LSP has a client attached, and by specifying the dependency, it loads in the correct order. But if there's no LSP attached, it loads just fine either way.

### Steps to reproduce

1. Download the [Terrain3D 1.0.1 demo zip file](https://github.com/TokisanGames/Terrain3D/releases/tag/v1.0.1)
2. Unzip it
3. Open the demo in Godot 4.4.x
4. Now open an external editor that can connect to the Godot LSP (e.g. VS Code or Cursor with the `godot-tools` extension or Sublime Text with the `SublimeGodot` plugin) and ensure it connects
5. Now go to Project -> Reload Project
6. Observe the error
7. Repeat a couple times to show it's consistent
8. Now make the minor tweaks in ./addons/Terrain3D/src/asset_dock.gd and editor_plugin.gd that I specified above (add a class_name, and specify it in the asset_dock export)
9. Now go to Project -> Reload Project
10. Observe no error
11. Repeat a couple times to show it's consistent

### Minimal reproduction project (MRP)

The Terrain3D demo project replicates this behavior just fine.

[Terrain3D 1.0.1 demo zip file](https://github.com/TokisanGames/Terrain3D/releases/tag/v1.0.1)

### PR DESCRIPTION
**Pull request by HolonProduction**
Fixes https://github.com/godotengine/godot/issues/108128

### CODE REVIEW

File: modules/gdscript/language_server/gdscript_language_server.cpp [hunk 1]
```diff
@@ -45,19 +45,21 @@ GDScriptLanguageServer::GDScriptLanguageServer() {
...
-		} break;
-
 		case NOTIFICATION_EXIT_TREE: {
 			stop();
 		} break;
 
 		case NOTIFICATION_INTERNAL_PROCESS: {
+			if (!started && EditorNode::get_singleton()->is_editor_ready()) {
+				start();
+			}
```
Comment (vnen) [inline modules/gdscript/language_server/gdscript_language_server.cpp:61]: Feels odd to me having to check this every frame. But it should be fine.

**Review by vnen — APPROVED** [review]

File: modules/gdscript/language_server/gdscript_language_server.cpp (hunk 1 above)
Comment (jamonholmgren) [reply modules/gdscript/language_server/gdscript_language_server.cpp:61]: Dumb question: does it ever make sense to add a notification `NOTIFICATION_EDITOR_READY` to not have to poll?

**Comment by Repiteo** [comment]
Thanks!
