### PR TITLE
GLES2 2D batching - item reordering, light joining and light modulate fix

### LINKED ISSUE #9913: Tilemap/draw_rect random flickering with Nvidia drivers
**Operating system or device - Godot version:**
Windows 10, godot3.0alpha1

**Issue description:**
I made a kinematicbody2D and a tilemap, moving the kinematic body around worked as normal however occasionally one of the tiles on the tilemap would vanish faster than any screen recording software could capture. sometimes 2 would vanish, they would get redrawn however

**Steps to reproduce:**
Make a tilemap, load some tiles in, make a kinematic body
move the body around the game, keep your eyes open, dont blink, watch as some tiles vanish from rendering and quickly come back

### LINKED ISSUE #38260: GLES2 Batching - custom multi-rect modulate bug with lights
**Godot version:**
3.2.2 beta

**Issue description:**
Just while adding some optimizations to the batching for lights, I've noticed a slight oversight - When drawing the light passes, the correct modulate is not being used when there is more than one modulate on a set of rects within an item.

This is because the final modulate used for the non light pass takes into account things like canvas_modulate, but the light passes do not, hence the baked colors need to be different.

This doesn't seem to normally appear in typical use with tilemaps / sprites etc (indeed no one has reported it), but it can exhibit when using custom drawing with multiple rects for an item (node), under a light, particularly when using a canvas modulate.

I should be able to fix this as part of the lighting optimizations, so this is just a note for anyone who sees it in the mean time.

### LINKED ISSUE #38291: GLES2 2D light pass can draw in wrong position
**Godot version:**
GLES2 but not GLES3
3.1 stable - 3.2.2 beta
(may occur earlier versions too)

**OS/device including version:**
Linux Mint but will probably affect all

**Issue description:**
While working on the batching and fixing regressions in lighting, I noticed one regression that was actually correct in the batching but incorrect in the old renderer.

When using the custom _draw() function to draw rects manually, in some situations the locations of the alpha blended versions in the light pass are incorrect.

The minimum reproduction project shows as seen in this screenshot, without light on the left (5 rects) and with light on the right (appears as 6 rects):

light_position_bug

**Steps to reproduce:**
Use custom draw with lots of transforms, I haven't pinned down exactly which causes it.

**Minimal reproduction project:**
[Light_Position_Bug.zip](https://github.com/godotengine/godot/files/4545675/Light_Position_Bug.zip)

Note that this appears fixed in my current (soon to be pushed) version of the batching, so there is less pressing need to fix this in the legacy renderer. I suspect it is an extra_matrix bug (where the GPU extra matrix gets out of sync with the logic CPU side).

It doesn't occur in GLES3, presumably because it uses a single pass for lighting.

### PR DESCRIPTION
**Pull request by lawnjelly**
_This PR contains a mix of 2 optimizations, and several bug fixes. I would have ideally done some separately but they are quite interlinked._

# Background
Although 2D draws in painters order with strict ordering, in certain circumstances items can be reordered to increase batching / decrease state changes, without affecting the end result. This can be determined by an overlap test.

In situation with item:
A-B-A
providing the third item does not overlap the second, they can be reordered:
A-A-B

Luckily, items already contain a calculated AABB (from the visual server) which can be exploited for this overlap test.

## Item Reordering
To utilise this, I have implemented item reordering (only for single rects for now), with the lookahead adjustable in project settings. This can increase performance in situations where items may not be grouped in the scene tree by texture. It can also be switched off (by setting lookahead to 0). This is very basic for now but may be able to be expanded.

Note that this optimization won't make much difference for most games, but could be very important for games with large number of interleaved items (e.g. sprites) of different texture.

## Lit item joining
This same trick can be used to help join items that are lit. Lit items previously would prevent joining completely, thus missing out on performance gains other than multi-command items such as tilemaps. This improvement can thus be massively important in games with lighting, as it enables acceleration to approach the levels seen in non-lit games.

To do this, lights are assigned as bits in a bitfield (up to 64, the optimization is disabled above this), and on each try_item (for joining), the bitfield for lights and shadows is constructed and compared with the previous items. If these match the 2 items can potentially be joined. However, this can only be done without changing the rendered result if an overlap test is successful.

This overlap test can be adjusted to join items up to a specific number of item references, selectable in project settings, or turned off.

### Single Rect Fallback
The legacy uniform single rect drawing routine seems to have been identified as the source of flicker, particularly on nvidia. However, it can also be up to 2x as fast. Because of the speed the batching contains a fallback where it can use the legacy single rect method, but I have now added a project setting to make this switchable. In most cases with batching it should not be necessary (as single rects are drawn less frequently) and thus the flickering can be totally avoided.

May fix #9913 at least for GLES2.

### Color modulate bug in light passes
Fixes #38260.
This is a color modulate bug when drawing light passes, in certain situations (particularly custom _draw routines with multiple rects).

### Light pass rect position bug
Fixes #38291 (at least in the batching renderer).
This was a pre-existing bug in the legacy renderer where light passes could draw rects in wrong position.

## Notes
* Both `item_reordering_lookahead` and `light_max_join_items` could potentially be set to 0 (switched off) as default, but many users would never change these settings. So instead I've opted for conservative settings that will yield good benefit while having minimal costs in situations where they don't improve performance. These defaults can be changed in the PR depending on reviewers preferences.
* `single_rect_fallback` (which is faster) was previously always on, but now we have identified that it is probably the cause of the nvidia flickering, I have made it optional, and defaulted to off, as in many games it will offer very little performance difference.

### CODE REVIEW

**Comment by lawnjelly** [comment]
On suggestion from @akien-mga I added a line to disable `nvidia_workaround` when batching is being used, as it makes no sense:

When batching, the only reason to use `single_rect_workaround` is the speed increase from the uniform buffer drawing technique. The speed of the nvidia workaround technique is approximately the same as the batching draw method (indexed primitive + VB upload), and it should be faster and less drawing methods to debug to just have 2 options rather than 3.

File: drivers/gles2/rasterizer_canvas_gles2.cpp [hunk 1]
```diff
@@ -2042,10 +2268,92 @@ bool RasterizerCanvasGLES2::try_join_item(Item *p_ci, RenderItemState &r_ris, bo
...
+			int light_count = -1;
+			while (light) {
+				light_count++;
+				uint64_t light_bit = 1 << light_count;
+
+				// use the bounding rect of the joined items, NOT only the bounding rect of the first item.
+				// note this is a cost of batching, the light culling will be less effective
+
+				if (p_ci->light_mask & light->item_mask && r_ris.item_group_z >= light->z_min && r_ris.item_group_z <= light->z_max) {
+					//&& p_ci->global_rect_cache.intersects_transformed(light->xform_cache, light->rect_cache)) {
```
Comment (clayjohn) [inline drivers/gles2/rasterizer_canvas_gles2.cpp:2294]: Can remove old commented out code

File: drivers/gles2/rasterizer_canvas_gles2.h [hunk 2]
```diff
@@ -258,9 +298,11 @@ class RasterizerCanvasGLES2 : public RasterizerCanvasBaseGLES2 {
 	// high level batch funcs
 	void canvas_render_items_implementation(Item *p_item_list, int p_z, const Color &p_modulate, Light *p_light, const Transform2D &p_base_transform);
 	void render_joined_item(const BItemJoined &p_bij, RenderItemState &r_ris);
+	void record_items(Item *p_item_list, int p_z);
 	void join_items(Item *p_item_list, int p_z);
+	void join_sorted_items();
 	bool try_join_item(Item *p_ci, RenderItemState &r_ris, bool &r_batch_break);
-	void render_joined_item_commands(const BItemJoined &p_bij, Item *p_current_clip, bool &r_reclip, RasterizerStorageGLES2::Material *p_material);
+	void render_joined_item_commands(const BItemJoined &p_bij, Item *p_current_clip, bool &r_reclip, RasterizerStorageGLES2::Material *p_material, bool lit);
```
Comment (clayjohn) [inline drivers/gles2/rasterizer_canvas_gles2.h:305]: Same as before lit->p_lit

**Review by clayjohn — CHANGES_REQUESTED** [review]

File: doc/classes/ProjectSettings.xml [hunk 3]
```diff
@@ -975,12 +975,21 @@
...
+		</member>
 		<member name="rendering/gles2/batching/light_scissor_area_threshold" type="float" setter="" getter="" default="1.0">
 			Sets the proportion of the screen area that must be saved by a scissor operation in order to activate light scissoring. This can prevent parts of items being rendered outside the light area. Lower values scissor more aggressively. A value of 1 scissors none of the items, a value of 0 scissors every item. This can reduce fill rate requirements in scenes with a lot of lighting.
 		</member>
 		<member name="rendering/gles2/batching/max_join_item_commands" type="int" setter="" getter="" default="16">
 			Sets the number of commands to lookahead to determine whether to batch render items. A value of 1 can join items consisting of single commands, 0 turns off joining. Higher values are in theory more likely to join, however this has diminishing returns and has a runtime cost so a small value is recommended.
 		</member>
+		<member name="rendering/gles2/batching/single_rect_fallback" type="bool" setter="" getter="" default="false">
```
[the remark this answers is not in the document]
Comment (lawnjelly) [reply doc/classes/ProjectSettings.xml:990]: They could possibly be combined, I'm open to suggestions on how to do this. Also at the moment, they default to different values. Without batching, the default is to use nvidia workaround, and with batching, the default is to not use any fallback for single rects (which is analogous, but not the same, as using nvidia workaround, because it uses the normal batching indexed primitive path).

I think we should take the opportunity to switch the default towards using non-uniform method of drawing single rects (unless we can fix it). We could perhaps combine them if we change the default nvidia workaround to ON, and change the name of the setting so it represents the dual role.

File: drivers/gles2/rasterizer_canvas_gles2.cpp (hunk 1 above)
Comment (lawnjelly) [reply drivers/gles2/rasterizer_canvas_gles2.cpp:2294]: Ah yes, this is interesting actually. I left this in (especially during development) because I wasn't clear on whether the best choice for this may vary according to the situation, so I was continuously flipping between the 2 versions.

In my benchmark (which I must post here actually for you to try, it was essentially the sprite test I had posted earlier, but with a big 2d light over the central area), I found that with the random positions of sprites, the benefits of batching due to joining them irrespective of whether they were in the light area outweighed the cost of removing them from rendering if they were outside.

However there could be situations where doing this AABB test is better (I just haven't found any yet). This is something that may be revisited, I think it would be better to put a comment to this effect. I'm wary of making it a project setting at this stage, as it may not be necessary, and we already have a lot of settings.

File: doc/classes/ProjectSettings.xml (hunk 3 above)
[the remark this answers is not in the document]
Comment (clayjohn) [reply doc/classes/ProjectSettings.xml:990]: Ah, your right. This is best for now. I forgot that we don't have to have a single rect fallback and could just have a single rect batch. 

I'm a bit wary of changing the behaviour outside of batching for the 3.2 branch. But it is something we should strongly consider when porting.

File: drivers/gles2/rasterizer_canvas_gles2.cpp [hunk 4]
```diff
@@ -1614,7 +1620,7 @@ void RasterizerCanvasGLES2::render_batches(Item::Command *const *p_commands, Ite
 	bdata.reset_flush();
 }
 
-void RasterizerCanvasGLES2::render_joined_item_commands(const BItemJoined &p_bij, Item *p_current_clip, bool &r_reclip, RasterizerStorageGLES2::Material *p_material) {
+void RasterizerCanvasGLES2::render_joined_item_commands(const BItemJoined &p_bij, Item *p_current_clip, bool &r_reclip, RasterizerStorageGLES2::Material *p_material, bool lit) {
```
[the remark this answers is not in the document]
Comment (lawnjelly) [reply drivers/gles2/rasterizer_canvas_gles2.cpp]: Done.

File: drivers/gles2/rasterizer_canvas_gles2.h (hunk 2 above)
Comment (lawnjelly) [reply drivers/gles2/rasterizer_canvas_gles2.h]: Done.

File: drivers/gles2/rasterizer_canvas_gles2.cpp (hunk 1 above)
Comment (lawnjelly) [reply drivers/gles2/rasterizer_canvas_gles2.cpp]: Ok I've cleared up the comments and made them a bit more sensible. :+1:

**Review by clayjohn — APPROVED** [review]
Looks good to me! Subject to CI passing of course.

**Comment by akien-mga** [comment]
Thanks!

**Comment by avencherus** [comment]
Introduces sprite flickering.  https://github.com/godotengine/godot/issues/38458
