### PR TITLE
[macOS] Fix `warp_mouse` in game mode.

### LINKED ISSUE #108746: [4.5-beta3] Input.warp_mouse() is not working with embedded game window on macOS
### Tested versions

- Reproducible in: v4.5.beta3.official [4d1f26e1f] up to v4.5.dev4.official [209a446e3]
- Reproducible only on `macOS`

### System information

Godot v4.5.beta3 - macOS Sequoia (15.5.0) - Multi-window, 2 monitors - Metal (Forward+) - integrated Apple M1 Pro (Apple7) - Apple M1 Pro (10 threads) - 16.00 GiB memory

### Issue description

The function appears ineffective when used with embedded game window on macOS. I have also tested this on the main branch to include recent fixes related to the embedded window. 

### Steps to reproduce

- Open the MRP
- Make sure "Embed game on next play" is **on** (floating or not)
- Press play from the top right menu
- Observe mouse did not warped into the bracket

### Minimal reproduction project (MRP)

[mrp-embed-mouse-warp.zip](https://github.com/user-attachments/files/21316440/mrp-embed-mouse-warp.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/108746

Also fixes missing DS feature flags.

### CODE REVIEW

File: platform/macos/editor/embedded_game_view_plugin.mm [hunk 1]
```diff
@@ -116,6 +116,14 @@
 	return true;
 }
 
+bool GameViewDebuggerMacOS::_msg_warp_mouse(const Array &p_args) {
+	ERR_FAIL_COND_V_MSG(p_args.size() != 1, false, "warp_mouse: invalid number of arguments");
```
Comment (AThousandShips) [inline platform/macos/editor/embedded_game_view_plugin.mm]:
```suggestion
	ERR_FAIL_COND_V_MSG(p_args.size() != 1, false, "warp_mouse: invalid number of arguments.");
```

**Review by clayjohn — APPROVED** [review]
Looks great! I'm not familiar with this area, but it would be good to fix the issue that this fixes

**Review by AThousandShips — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
