### PR TITLE
Fix flickering issues with low processor mode on Android

### LINKED ISSUE #19304: OS.low_processor_usage_mode in Android makes problems to Anim, Tween, and CheckButton nodes
**Godot version:**
Godot 3.0.2 stable

**OS/device including version:**
Windows 10 Pro
Exporting to Android 6.0, Samsung Galaxy J2 Prime

**Issue description:**
When being played in the project, OS.low_processor_usage_mode made my animations not smooth, which is very normal for me. But when being exported and run in Android, it made weird and actually funny problems to my animations, tweens, and checkbuttons. Every scene of mine has its own anims and tweens, where some scenes only had their anims affected and the others had their tweens affected. The settings scene is the only one who has CheckButtons and those nodes were also affected. It is really hard to explain the problem so I just provide a video: https://youtu.be/nSS_nzAhR6g

Notice in the video that I tested the game before enabling low usage mode, then something weird happened after I turned it on. (It is when I enabled power saving)

Note: I used Tweens only for moving the cards and the buttons in the bottom of the screen. Other motions besides them are made using AnimationPlayers

### LINKED ISSUE #58932: Black screen on Android when low processor mode was enabled
### Godot version

4.0 alpha-4

### System information

Android 9 (phone), Android 11 (tablet)

### Issue description

When the low processor mode is enabled, leave the game temporary and then go back, it will be black screen until the frame is updated

https://user-images.githubusercontent.com/65079334/157463423-738fb95d-b343-4835-b426-211e20d7218a.mp4

.

### Steps to reproduce

1. create a project
2. enable low processor mode
3. export apk
4. install on phone
5. open the game
6. leave the game with home button
7. go back to the game

### Minimal reproduction project

[tested.zip](https://github.com/godotengine/godot/files/8215524/tested.zip)

### PR DESCRIPTION
**Pull request by m4gr3d**
As pointed out by @Relintai in https://github.com/godotengine/godot/pull/55604#issuecomment-1077590602, the cause of the flickers when enabling low processor mode is that the framebuffers are swapped automatically even when nothing is rendered.

To resolve the issue, I forked `GLSurfaceView` so that the Godot Android logic can specify when the framebuffers should be swapped.

Fixes https://github.com/godotengine/godot/issues/19304
Fixes https://github.com/godotengine/godot/issues/58932

*Bugsquad edit:* `master` version of #59606.

### CODE REVIEW

File: platform/android/java_godot_lib_jni.cpp [hunk 1]
```diff
@@ -243,9 +243,12 @@ JNIEXPORT void JNICALL Java_org_godotengine_godot_GodotLib_step(JNIEnv *env, jcl
 	DisplayServerAndroid::get_singleton()->process_magnetometer(magnetometer);
 	DisplayServerAndroid::get_singleton()->process_gyroscope(gyroscope);
 
-	if (os_android->main_loop_iterate()) {
+	bool should_swap_buffers;
```
Comment (RandomShaper) [inline platform/android/java_godot_lib_jni.cpp:246]: I think we've favoring the defensive initialization style now, so it'd be good to initialize this one.

File: platform/android/java/nativeSrcsConfigs/CMakeLists.txt [hunk 2]
```diff
@@ -17,4 +17,4 @@ target_include_directories(${PROJECT_NAME}
         SYSTEM PUBLIC
         ${GODOT_ROOT_DIR})
 
-add_definitions(-DUNIX_ENABLED -DVULKAN_ENABLED -DTOOLS_ENABLED)
+add_definitions(-DUNIX_ENABLED -DVULKAN_ENABLED -DANDROID_ENABLED)
```
Comment (RandomShaper) [inline platform/android/java/nativeSrcsConfigs/CMakeLists.txt:20]: This is a nitpick: I fell like changes of this kind should be in their own commit since they are not really part of the main task. For me, it'd be fine the alternative of just adding a line in the commit message telling that there are some additional little fixes unrelated to the main goal.

**Review by RandomShaper — COMMENTED** [review]
I've added a few comments about not very important things.

Besides them, my only real concern is the maintainability of the forked stuff. I'd suggest to follow the closest that is possible to the scheme followed for other 3rd-party code. Being Java files I'm not sure if they can be put under ´thirdparty/´, but at least it would be good to check out the changes as patch files for easier upgrading.

File: platform/android/java/nativeSrcsConfigs/CMakeLists.txt (hunk 2 above)
Comment (m4gr3d) [reply platform/android/java/nativeSrcsConfigs/CMakeLists.txt:20]: @RandomShaper This change is mostly cosmetic and doesn't affect the engine logic.
That CMake file is only used by Android Studio to properly show the native engine code, and so has no effects on anything else.

**Comment by m4gr3d** [comment]
> I've added a few comments about not very important things.
> 
> Besides them, my only real concern is the maintainability of the forked stuff. I'd suggest to follow the closest that is possible to the scheme followed for other 3rd-party code. Being Java files I'm not sure if they can be put under ´thirdparty/´, but at least it would be good to check out the changes as patch files for easier upgrading.

In the past for java code, we've departed from the `thirdparty` approach (also because I don't think that would work) and included forked files in the `lib` directory (see https://github.com/godotengine/godot/tree/master/platform/android/java/lib/src/com/google/android/vending). 

I'm also not very concerned about maintainability given the forked files have been stable for quite a while (`GLSurfaceView` has been part of the Android apis since the very beginning), and are unlikely to change anytime soon (especially as Google has adopted the pattern of providing enhanced functionality in external libraries rather than updating the core apis).

**Review by RandomShaper — APPROVED** [review]
Fair enough.
