### PR TITLE
Avoid creating any useless undo action when dragging nodes in place

### LINKED ISSUE #80707: Dragging node in place creates useless undo action
### Godot version

4.2 f7bc653

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/1f014ed1-771e-4fc1-b889-b366b8a0397c

Nothing changed, but the scene was "modified".

### Steps to reproduce

1. Have at least 2 nodes on a scene
2. Drag one node on the position between the nodes (doesn't work if drop position is too close to the center)

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by garychia**
Fixes #80707

Update: the solution is updated for situations where multiple nodes are dragged in place.

### CODE REVIEW

File: editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -1919,7 +1919,9 @@ void SceneTreeDock::_do_reparent(Node *p_new_parent, int p_position_in_parent, V
 		// `move_child` + `get_index` doesn't really work for internal nodes.
 		ERR_FAIL_COND_MSG(p_nodes[ni]->get_internal_mode() != INTERNAL_MODE_DISABLED, "Trying to move internal node, this is not supported.");
 
-		if (p_nodes[ni]->get_parent() != p_new_parent || p_position_in_parent + ni != p_nodes[ni]->get_index(false)) {
+		const bool same_parent = p_nodes[ni]->get_parent() == p_new_parent;
+		const int new_index = p_position_in_parent > -1 ? p_position_in_parent + ni : p_new_parent->get_child_count(false) + ni;
+		if (!same_parent || new_index != p_nodes[ni]->get_index(false) && (new_index - 1 < 0 || new_index - 1 >= p_new_parent->get_child_count(false) || p_new_parent->get_child(new_index - 1, false) != p_nodes[ni])) {
```
Comment (AThousandShips) [inline editor/scene_tree_dock.cpp:1924]: Parentheses required to clear up ambiguity of grouping here, is it:
```suggestion
		if (!same_parent || new_index != p_nodes[ni]->get_index(false) && (new_index - 1 < 0 || (new_index - 1 >= p_new_parent->get_child_count(false) || p_new_parent->get_child(new_index - 1, false) != p_nodes[ni]))) {
```
Or
```suggestion
		if ((!same_parent || new_index != p_nodes[ni]->get_index(false)) && (new_index - 1 < 0 || new_index - 1 >= p_new_parent->get_child_count(false) || p_new_parent->get_child(new_index - 1, false) != p_nodes[ni])) {
```

File: editor/scene_tree_dock.cpp [hunk 2]
```diff
@@ -1919,7 +1919,10 @@ void SceneTreeDock::_do_reparent(Node *p_new_parent, int p_position_in_parent, V
 		// `move_child` + `get_index` doesn't really work for internal nodes.
 		ERR_FAIL_COND_MSG(p_nodes[ni]->get_internal_mode() != INTERNAL_MODE_DISABLED, "Trying to move internal node, this is not supported.");
 
-		if (p_nodes[ni]->get_parent() != p_new_parent || p_position_in_parent + ni != p_nodes[ni]->get_index(false)) {
+		const int new_index = p_position_in_parent > -1 ? p_position_in_parent + ni : p_new_parent->get_child_count(false) + ni;
+		const bool same_parent = p_nodes[ni]->get_parent() == p_new_parent;
+		const bool same_position = new_index == p_nodes[ni]->get_index(false) || (new_index - 1 >= 0 && new_index - 1 < p_new_parent->get_child_count(false) && p_new_parent->get_child(new_index - 1, false) == p_nodes[ni]);
```
Comment (AThousandShips) [inline editor/scene_tree_dock.cpp:1924]: Still present here, you can't mix `||` and `&&` without parentheses

**Comment by KoBeWi** [comment]
Can still happen with multiple nodes.

https://github.com/godotengine/godot/assets/2223172/2695264c-aa62-4b3c-93c8-bd820cc5570b

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
