### PR TITLE
Fixed user being unable to delete root Node if is an inherited Scene

### LINKED ISSUE #23007: Can't remove instanced scene if it's the root
**Godot version:**
v3.0.6.stable.official.8314054

<br>

**Issue description:**
If you instance a scene from the button in the "Scene" tab as the root of an empty scene, when you try to delete it you're presented an error "Can't operate on nodes the current scene inherits from!"

<br>

**Steps to reproduce:**
* Save a scene with at least a node within it
* Create a new empty scene
* Instance the scene in the first step in this new scene, using the "instance a scene file as a Node" button. So that instanced scene is the root of the new scene.
* Try to remove the instanced scene, you'll see that it's not possible

### PR DESCRIPTION
**Pull request by silvanocerza**
User wasn't able to delete the root Node because it was being treated as
a foreign Node since it was an inherited Scene

Fixes #23007

### CODE REVIEW

File: editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -1307,6 +1307,13 @@ bool SceneTreeDock::_validate_no_foreign() {
 			return false;
 		}
 
+		// When edited_scene inherits from another one the root Node will be the parent Scene,
+		// we don't want to consider that Node a foreign one otherwise we would not be able to
+		// delete it
+		if (edited_scene->get_scene_inherited_state().is_valid() &&  edited_scene->get_path_to(E->get()) == NodePath(".")) {
```
Comment (LikeLakers2) [inline editor/scene_tree_dock.cpp]:
```suggestion
		if (edited_scene->get_scene_inherited_state().is_valid() && edited_scene->get_path_to(E->get()) == NodePath(".")) {
```
https://travis-ci.org/godotengine/godot/jobs/445311207#L534

File: editor/scene_tree_dock.cpp [hunk 2]
```diff
@@ -1307,6 +1307,13 @@ bool SceneTreeDock::_validate_no_foreign() {
 			return false;
 		}
 
+		// When edited_scene inherits from another one the root Node will be the parent Scene,
+		// we don't want to consider that Node a foreign one otherwise we would not be able to
+		// delete it
+		if (edited_scene->get_scene_inherited_state().is_valid() && edited_scene->get_path_to(E->get()) == NodePath(".")) {
```
Comment (akien-mga) [inline editor/scene_tree_dock.cpp]: I think `edited_scene` is the root node already, so you could likely do `E->get() == edited_scene` instead of comparing NodePaths (not tested though, might be wrong).

**Comment by akien-mga** [comment]
Thanks!
