### PR TITLE
GDScript: Reset local variables on exit from block

### LINKED ISSUE #76569: Uninitialized variables not null in loops with branching
### Godot version

v4.0.2.stable.custom_build (nixpkgs version)

### System information

NixOS

### Issue description

The [docs](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#variables) seem to specify that uninitialized variables are null (as noted in this comment on the related issue: https://github.com/godotengine/godot/issues/56223#issuecomment-1175794500):
`var a # Data type is 'null' by default.`

This isn't always the case inside branches within loops. Instead, the variables can take on values from other branches.

### Related
- https://github.com/godotengine/godot/issues/56223

### Steps to reproduce

```
@tool
extends EditorScript

func _run():
	for i in 5:
		if i % 2:
			var j = i
			print("i = %s, j = %s" % [i, j])
		else:
			var k
			print("i = %s, k = %s" % [i, k])
```

Running this prints:
```
i = 0, k = <null>
i = 1, j = 1
i = 2, k = 1
i = 3, j = 3
i = 4, k = 3
```

This version also gives the exact same result:
```
@tool
extends EditorScript

func _run():
	for i in 5:
		match i % 2:
			1:
				var j = i
				print("i = %s, j = %s" % [i, j])
			0:
				var k
				print("i = %s, k = %s" % [i, k])
```

In addition, behavior similar to that described in https://github.com/godotengine/godot/issues/56223#issuecomment-1000996579 can still be reproduced as follows:
```
@tool
extends EditorScript

func _run():
	for i in 3:
		if i % 2:
			for j in range(1, 6, 3):
				pass
			print("i = %s" % i)
		else:
			var k
			var l
			var m
			print("i = %s, k = %s, l = %s, m = %s" % [i, k, l, m])
```
Which prints:
```
i = 0, k = <null>, l = <null>, m = <null>
i = 1
i = 2, k = 4, l = 7, m = (1, 6, 3)
```

### Minimal reproduction project

N/A

### LINKED ISSUE #77666: [GDScript 2] Reference leaking inside IF scope
### Godot version

v4.0.3.stable.official [5222a99f5]
Master [6101240231600c871f5c5473872532c68ea3268c] (confirmed by https://github.com/godotengine/godot/issues/77666#issuecomment-1568952502)

### System information

Window 10

### Issue description

References are not unreferenced at the end of `if` scopes.

### Steps to reproduce

Copy, paste and run the snippet below, check the results:

```gdscript
extends Node


func _ready() -> void:
  var ref := RefCounted.new()
  var ref_count : int

  # OK
  ref_count = ref.get_reference_count()
  print('Expected: 1, Result: %d' % ref_count)

  # OK
  if true:
    var temp := ref
    temp = null

  ref_count = ref.get_reference_count()
  print('Expected: 1, Result: %d' % ref_count)

  # FAIL
  if true:
    var temp := ref

  ref_count = ref.get_reference_count()
  print('Expected: 1, Result: %d' % ref_count)
```

Output example:

```
Expected: 1, Result: 1
Expected: 1, Result: 1
Expected: 1, Result: 2
```

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by dalexeev**
Closes #76569.
Closes #77666.

### CODE REVIEW

File: modules/gdscript/gdscript_compiler.cpp [hunk 1]
```diff
@@ -1664,25 +1664,38 @@ GDScriptCodeGenerator::Address GDScriptCompiler::_parse_match_pattern(CodeGen &c
...
+		addresses.push_back(codegen.add_local(p_block->locals[i].name, _gdtype_from_datatype(p_block->locals[i].get_datatype(), codegen.script)));
 	}
+	return addresses;
 }
 
-Error GDScriptCompiler::_parse_block(CodeGen &codegen, const GDScriptParser::SuiteNode *p_block, bool p_add_locals) {
+// Avoid keeping in the stack long-lived references to objects, which may prevent RefCounted objects from being freed.
+void GDScriptCompiler::_clear_addresses(CodeGen &codegen, const List<GDScriptCodeGenerator::Address> &p_addresses) {
+	for (const List<GDScriptCodeGenerator::Address>::Element *E = p_addresses.front(); E; E = E->next()) {
+		// If not an object, no need to clear.
```
Comment (dalexeev) [inline modules/gdscript/gdscript_compiler.cpp:1682]: It can be an array or a dictionary. :thinking:

**Comment by adamscott** [comment]
CC @vnen

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
