### PR TITLE
Fix KinematicBody2D motion issues + KinematicBody2D.test_move_from() (2.1)

### LINKED ISSUE #7951: KinematicBody2D.move() doesn't work as intended
**Operating system or device - Godot version:**
~~Present from at least 2.1, surely in 3.0 as well~~
~~Only relevant for 2.1 3.0 has its own issue.~~
More relevant for 2.1. Affectation for 3.0 is to be more deeply analyzed.

**Issue description:**
The typical use case for kinematic bodies is to call move() and if a collision is detected, call move() again with the slide vector.

The problem is that subsequent calls to move() during the same fixed frame don't take into account the accumulated position. In other words, the movement for any call to move() is considered to depart from wherever the body was at the fixed step.

I think such a big thing is barely noticeable because of the usual gravity keeping the body on the ground and some subtleties of the implementation.

Anyway, if I'm right that's a big bug that makes things not work as smoothly as they should. Furthermore, problems arise when one tries to make multiple motion attempts for more complex behavior (that's how I realized something wasn't working properly).

Maybe the 3D counterpart is also affected. Please someone confirm.

**The issue on 3.0:**

UPDATE: The 3.0 version has this somehow alleviated due to the "from" parameter for motion tests. But the implementation is still getting the AABBs of the shapes with the transform thas was applied at the beginning of the fixed step.

Since the shapes' AABB cache is not updated until the `NOTIFICATION_TRANSFORM_CHANGED` received per frame, they are out-dated on a subsequent call to the motion methods.

(See https://github.com/godotengine/godot/blob/f13e87e25799aafa4462779650c7d6222c782b31/servers/physics_2d/space_2d_sw.cpp#L613)

Untransforming the shapes AABBs with the current known transform and then applying the "from" transform to them at that point in code should do the trick.

What do you think? A better way?

**Solution:**

~~I have a PR almost ready and it seems to work well both for my game and for the kinematic character example but I want to hear opinions as soon as possible.~~

~~For 2.1 probably the wrong behavior should be left as the default to avoid breaking things so the fix comes as an optional thing.~~

EDIT: PR already submitted for 2.1.

**Steps to reproduce:**
(to be done)

### PR DESCRIPTION
**Pull request by RandomShaper**
~~Adds `KinematicBody2D.set_enable_motion_accumulation()` so subsequent calls to `move()`, `move_to()` and `revert_motion()` during the same fixed frame get accumulated. (See #7951 for more info.)~~

~~Motion accumulation is disabled by default so everything works as always unless this fixing behavior is explicitly enabled.~~

~~Also adds some APIs to the physics servers and the kinematic body for finer control.~~

~~Fixes #7951.~~

UPDATE: Cleaner solution:

Got part of the fix from 5fc084c28e912c54bf64645df3e6cf2cd2c30be6 (but there in _master_ is still something broken that will get a PR)
Added an engine setting to enable the fix (__physics_2d/motion_fix_enabled__) which is false by default so the default behavior is the same as always
Added `KinematicBody2D.test_move_from()` to have in 2.1 an useful method as the plain `move()` is for 3.0, whch already has the `from` parameter

### CODE REVIEW

File: scene/2d/physics_body_2d.cpp [hunk 1]
```diff
@@ -1099,17 +1110,15 @@ Vector2 KinematicBody2D::move(const Vector2& p_motion) {
 
 	bool collided=false;
 	uint32_t mask=0;
-	if (collide_static)
+	if (true)
```
Comment (akien-mga) [inline scene/2d/physics_body_2d.cpp]: Hm? That part is commented out anyway, why change it?

**Comment by RandomShaper** [comment]
That's from the cherry-pick. I applied it and worked on top of it trying to
keep everything as close as possible to master.

But I'm unsure about what would have been the right decision here.

**Comment by akien-mga** [comment]
Ok, then I guess it's ok, the blame would be on reduz :P
