### PR TITLE
Avoid duplicating signals from scene instances into packed scenes (reverted)

### LINKED ISSUE #48064: When packing a PackedScene into a scene, signals and scripts of that PackedScene are duplicated into the parent scene
**Godot version:**
3.2.3

**OS/device including version:**
Windows 10

**Issue description:**
I was working on a level editor for my game, and I decided to use PackedScenes for the tested levels since scenes are the default format for my original levels.
I also have PackedScenes within those scenes, though. Those are the tiles, hazards, orbs, player, etc. They all obviously have scripts attached to them (except for the regular tiles). And the hazards and orbs' body_entered are connected to themselves (in their own scene) to detect if the player touched them or not.
When I play the level, it shows this error:
```
E 0:01:28.051   connect: Signal 'body_shape_entered' is already connected to given method '_on_Hazard_body_shape_entered' in that object.
  <C++ Error>   Method failed. Returning: ERR_INVALID_PARAMETER
  <C++ Source>  core/object.cpp:1515 @ connect() # I am not even using the connect() method, haha...
  <Stack Trace> CustomLevel.gd:75 @ _on_PlayButton_pressed()
```
It appears to be blaming this line in the CustomLevel node's (The main parent node for all the elements in the level editor) script:
`	get_tree().change_scene_to(GlobalVariables.level) # The variable in a singleton which the CustomLevel node packs into.`

Of course, it isn't crashing or breaking my game, but it is annoying to see this error for _each_ node pop up every time I go to this scene or reload it. The scene would probably also take slightly more time to load due to this error. I would also want to focus on some real issues, too.

This is the code in the CustomLevel script to pack everything (since the CustomLevel node isn't the root node, all the children won't be packed if I don't set the owner to itself):
```
func saveLevel():
	position = Vector2(0,0)
	descendants = get_children() + [UI] # the variable "UI" stands for the UI node of the game which is a child of a CanvasLayer.
	for i in descendants:
		i.owner = self
	GlobalVariables.level.pack(self)

func _on_PlayButton_pressed():
	UI.show()
	saveLevel()
#	ResourceSaver.save("glitchedLevel.tscn", GlobalVariables.level) # I wanted to test what it looked like as a .tscn file
	get_tree().change_scene_to(GlobalVariables.level)
	GlobalVariables.editor = false
	GlobalVariables.editor_playing = true
```
I decided to save it as a .tscn file to see what it looked like and it seemed to have the same signals and scripts as the nodes already have in their source scenes... Hence why it is showing the error. I edited the files to remove those signals and scripts and it still works perfectly... so those extra bytes of data are unnecessary.

I am assuming this might be a core problem and probably can't be fixed with a script? Maybe it can, but with a complicated workaround. I also took a look at `core/object.cpp:1515` but it is just the emit_signal() method which is not helpful, I'm pretty sure since I am not using connect() or emit_signal() in the first place. I am connecting the signals through the editor (in their own scenes)

**Steps to reproduce:**
Have a root Node, then add a child to that Node (Node0 in this case). This second Node will be the parent of all the other nodes. Make one or two nodes the children of this Node. Then make a new scene, make a Node (Node3 in this case), add a script to it. Then connect any signal (it can be a custom signal) to itself in the local scene, then make it print something in _ready() when the node is emitted (just to know if it is working).
Go back to the original scene and instance Node3 to Node0. Add a script to Node0 and make a PackedScene.new() variable like "level". Then in _ready(), put something like this:
```
for i in get_children():
	i.owner = self
level.pack(self)
get_tree().change_scene_to(level)
```
The error will appear.

**Minimal reproduction project:**
[PackedSceneProblem.zip](https://github.com/godotengine/godot/files/6352598/PackedSceneProblem.zip)
(For some reason, this is glitching out (it is printing "hello" every frame even though it is only supposed to be emitted once at _ready(). It might have to do with this bug, but I am not sure.)

### LINKED ISSUE #86532: PackedScene Instantiate from Tool Script is preserving Signals when saved
### Tested versions

- Reproductible in:
v4.2.1.stable.mono.official [b09f793f5]
Godot v4.1.3 stable mono
Godot v4.1 stable mono

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.4592) - Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz (20 Threads)

### Issue description

I'm experiencing unusual behaviour with tool script and packed scene instantiation.
When instantiating a PackedScene that has signals connection, the signals are saved to the scene file.
The nodes themselves saved, only the signals are.

### Steps to reproduce

Download [TestBugSignal.zip](https://github.com/godotengine/godot/files/13773798/TestBugSignal.zip)
1: open the project in either the mono version or the normal version.
2: open the scene Node2D(C#) or Test2(GDScript)
3: wait for the 10 number to print in the console
4: open the previously opened scene file in a text editor
5: notice the 10 signal connection in the file

### Minimal reproduction project (MRP)

[TestBugSignal.zip](https://github.com/godotengine/godot/files/13773798/TestBugSignal.zip)
or
Create a scene that as any signal connection in it.
Create a scene that as a script that has this code:
```gdscript
@tool
extends Node2D

@export var test: PackedScene:
	set(value):
		test = value
		refresh()

func _ready() -> void:
	refresh()

func refresh():
	if not test:
		return

	for i in 10:
		add_child(test.instantiate())
		print(str(i))
```
follow Steps to reproduce

### PR DESCRIPTION
**Pull request by cixil**
#### EDIT: This PR was partially reverted by https://github.com/godotengine/godot/pull/100235 so the issues are not fixed. https://github.com/godotengine/godot/pull/100965 has been created as a follow up

Fixes #48064 and fixes #86532

When packing a tree of nodes to a  `PackedScene`, signal connections originating from the root node of a scene instance within that tree would get duplicated into the PackedScene and cause "duplicate signal" errors when instantiating it.

### CODE REVIEW

**Comment by cixil** [comment]
I think this also fixes #85372

**Comment by AThousandShips** [comment]
You used a merge commit to update your branch, please use rebase in the future instead, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase), this put a lot of commits with the wrong commit in your branch, to fix do:
```
git reset --hard e0cf91d
git rebase -i master
git push --force
```

**Comment by AThousandShips** [comment]
Your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

File: core/object/object.h [hunk 1]
```diff
@@ -572,7 +572,7 @@ class Object {
 		CONNECT_PERSIST = 2, // hint for scene to save this connection
 		CONNECT_ONE_SHOT = 4,
 		CONNECT_REFERENCE_COUNTED = 8,
-		CONNECT_INHERITED = 16, // Used in editor builds.
+		CONNECT_INHERITED = 16, // Whether or not the connection is in an instance of a scene
```
Comment (KoBeWi) [inline core/object/object.h:575]:
```suggestion
		CONNECT_INHERITED = 16, // Whether or not the connection is in an instance of a scene.
```

File: scene/resources/packed_scene.cpp [hunk 2]
```diff
@@ -1034,6 +1034,7 @@ Error SceneState::_parse_node(Node *p_owner, Node *p_node, int p_parent_idx, Has
 }
 
 Error SceneState::_parse_connections(Node *p_owner, Node *p_node, HashMap<StringName, int> &name_map, HashMap<Variant, int, VariantHasher, VariantComparator> &variant_map, HashMap<Node *, int> &node_map, HashMap<Node *, int> &nodepath_map) {
+	// Ignore nodes that are within a scene instance
```
Comment (KoBeWi) [inline scene/resources/packed_scene.cpp:1037]:
```suggestion
	// Ignore nodes that are within a scene instance.
```

File: scene/resources/packed_scene.cpp [hunk 3]
```diff
@@ -1054,7 +1055,14 @@ Error SceneState::_parse_connections(Node *p_owner, Node *p_node, HashMap<String
 		for (const Node::Connection &F : conns) {
 			const Node::Connection &c = F;
 
-			if (!(c.flags & CONNECT_PERSIST)) { //only persistent connections get saved
+			// Don't save connections that are not persistent
+			if (!(c.flags & CONNECT_PERSIST)) {
```
Comment (KoBeWi) [inline scene/resources/packed_scene.cpp:1059]:
```suggestion
			// Don't save connections that are not persistent.
			if (!bool(c.flags & CONNECT_PERSIST)) {
```
Consistent with the one below.

File: scene/resources/packed_scene.cpp [hunk 4]
```diff
@@ -1054,7 +1055,14 @@ Error SceneState::_parse_connections(Node *p_owner, Node *p_node, HashMap<String
...
+				continue;
+			}
+
+			// Don't include signals that are from scene instances
+			// (They are already saved in the scenes themselves)
```
Comment (KoBeWi) [inline scene/resources/packed_scene.cpp:1064]:
```suggestion
			// Don't include signals that are from scene instances
			// (they are already saved in the scenes themselves).
```

File: scene/resources/packed_scene.cpp [hunk 5]
```diff
@@ -1220,9 +1228,10 @@ Error SceneState::_parse_connections(Node *p_owner, Node *p_node, HashMap<String
 		}
 	}
 
+	// Recursively parse child connections
```
Comment (KoBeWi) [inline scene/resources/packed_scene.cpp:1231]:
```suggestion
	// Recursively parse child connections.
```

File: tests/scene/test_packed_scene.h [hunk 6]
```diff
@@ -32,7 +32,6 @@
 #define TEST_PACKED_SCENE_H
 
 #include "scene/resources/packed_scene.h"
-
```
Comment (KoBeWi) [inline tests/scene/test_packed_scene.h:35]: This should stay here.

**Review by KoBeWi — APPROVED** [review]

File: tests/scene/test_packed_scene.h [hunk 7]
```diff
@@ -32,7 +32,6 @@
 #define TEST_PACKED_SCENE_H
 
 #include "scene/resources/packed_scene.h"
```
Comment (cixil) [inline tests/scene/test_packed_scene.h:34]:
```suggestion
#include "scene/resources/packed_scene.h"

```

File: tests/scene/test_packed_scene.h [hunk 8]
```diff
@@ -56,6 +56,67 @@ TEST_CASE("[PackedScene] Pack Scene and Retrieve State") {
...
+		//subscene root to subscene root (connected within main scene)
+		sub_scene_root->connect("ready", callable_mp(sub_scene_root, &Node::is_ready), main_flags);
+
+		// Pack the scene.
+		PackedScene packed_scene;
+		const Error err = packed_scene.pack(main_scene_root);
+		CHECK(err == OK);
+
+		// Make sure the right connections are in packed scene
+		Ref<SceneState> state = packed_scene.get_state();
```
Comment (AThousandShips) [inline tests/scene/test_packed_scene.h:94]:
```suggestion
		Ref<PackedScene> packed_scene;
		packed_scene.instantiate();
		const Error err = packed_scene->pack(main_scene_root);
		CHECK(err == OK);

		// Make sure the right connections are in packed scene.
		Ref<SceneState> state = packed_scene->get_state();
```
Use `Ref` for RefCounted for correctness

File: tests/scene/test_packed_scene.h [hunk 9]
```diff
@@ -56,6 +56,67 @@ TEST_CASE("[PackedScene] Pack Scene and Retrieve State") {
...
+		//subscene root to subscene root (connected within sub scene)
+		sub_scene_root->connect("ready", callable_mp(sub_scene_root, &Node::is_ready), subscene_flags);
+
+		// Pack the scene.
+		PackedScene packed_scene;
+		const Error err = packed_scene.pack(main_scene_root);
+		CHECK(err == OK);
+
+		// Make sure the right connections are in packed scene
+		Ref<SceneState> state = packed_scene.get_state();
```
Comment (AThousandShips) [inline tests/scene/test_packed_scene.h:113]:
```suggestion
		Ref<PackedScene> packed_scene;
		packed_scene.instantiate();
		const Error err = packed_scene->pack(main_scene_root);
		CHECK(err == OK);

		// Make sure the right connections are in packed scene.
		Ref<SceneState> state = packed_scene->get_state();
```

**Review by AThousandShips — DISMISSED** [review]

**Comment by jitspoe** [comment]
Thanks for working on this!  The error flood from this issue has made it difficult to spot real errors in my project.

File: tests/scene/test_packed_scene.h [hunk 10]
```diff
@@ -56,6 +56,69 @@ TEST_CASE("[PackedScene] Pack Scene and Retrieve State") {
 	memdelete(scene);
 }
 
+TEST_CASE("[PackedScene] Test That Correct Signals are Preserved when Packing Scene") {
```
Comment (akien-mga) [inline tests/scene/test_packed_scene.h:59]:
```suggestion
TEST_CASE("[PackedScene] Signals Preserved when Packing Scene") {
```

File: scene/resources/packed_scene.cpp [hunk 11]
```diff
@@ -1054,7 +1055,14 @@ Error SceneState::_parse_connections(Node *p_owner, Node *p_node, HashMap<String
...
 
-			if (!(c.flags & CONNECT_PERSIST)) { //only persistent connections get saved
+			// Don't save connections that are not persistent.
+			if (!bool(c.flags & CONNECT_PERSIST)) {
+				continue;
+			}
+
+			// Don't include signals that are from scene instances
+			// (they are already saved in the scenes themselves).
+			if (bool(c.flags & CONNECT_INHERITED)) {
```
Comment (akien-mga) [inline scene/resources/packed_scene.cpp:1065]: I don't think the `bool` cast is necessary, it's a very common pattern to check bitmasks/flags like this and the results is always used as an inferred boolean check.
```suggestion
			// Don't save connections that are not persistent.
			if (!(c.flags & CONNECT_PERSIST)) {
				continue;
			}

			// Don't include signals that are from scene instances
			// (they are already saved in the scenes themselves).
			if (c.flags & CONNECT_INHERITED) {
```

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
