### PR TITLE
Better handle infinite Tween loops

### LINKED ISSUE #57339: (4.0) Game freezes if you free() Tween target object when Tween is still running
### Godot version

4.0 alpha 1

### System information

Doesn't matter (Windows 10)

### Issue description

(Sorry for bad english, also new Tweening system is just fcking amazing overall, so simple to use - love it)

There is a small bug. I've created Tween in tree get_tree().create_tween() and set it on loop. When I tried to queue_free() node that was object target under that Tween game just stopped responding. @KoBeWi said that it should auto-kill itself when the target object is queue_free(). That's why I am creating this issue.

Here is gif:
Godot_v4 0-alpha1_win64_iXj9cgbzcr

There are 2 solutions, for now, to prevent the game from crashing (28.01.2022).

1. Kill tween before queue_free() it's target node.
2. Create tween under the node that you are going to queue_free(). That way it will be killed with it.

### Steps to reproduce

Try this code with this tree. Connecting signal via editor gives the same result.

Node2D (here is script)
-> Button
-> Sprite2D

```
extends Node2D

func _ready():
	var tween = get_tree().create_tween().set_loops()
	tween.tween_property($Sprite2D, "scale", Vector2(1.25, 1.25), .25).set_ease(Tween.EASE_OUT_IN).set_trans(Tween.TRANS_SINE)
	tween.tween_property($Sprite2D, "position", Vector2(100, 0), .1).as_relative()
	tween.tween_property($Sprite2D, "scale", Vector2(1.5, 1), .1).set_ease(Tween.EASE_OUT_IN).set_trans(Tween.TRANS_LINEAR)
	tween.tween_property($Sprite2D, "position", Vector2(-100, 0), .1).as_relative()
	tween.tween_property($Sprite2D, "scale", Vector2(1, 1), .1).set_ease(Tween.EASE_OUT_IN).set_trans(Tween.TRANS_LINEAR)
	$Button.pressed.connect(tween_test)
	
func tween_test():
	$Sprite2D.queue_free()
```

### Minimal reproduction project

[test23.zip](https://github.com/godotengine/godot/files/7956907/test23.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Resolves #57339
Instead of freezing, now you will get infinite error spam:
godot windows tools 64_TRYYv00ygK
I could make the error appear once, but it's easy to overlook.

Only available in debug builds.

### CODE REVIEW

File: scene/animation/tween.cpp [hunk 1]
```diff
@@ -312,6 +316,12 @@ bool Tween::step(float p_delta) {
 				start_tweeners();
 			}
 		}
+		
+#ifdef DEBUG_ENABLED
+		if (Math::is_equal_approx(rem_delta, prev_delta) && running && loops <= 0) {
+			ERR_FAIL_V_MSG(true, "Infinite loop detected. Check set_loops() description for more info.");
```
Comment (akien-mga) [inline scene/animation/tween.cpp:322]: Wouldn't it be worth returning `false` here to make it abort?
Spamming with errors can make very big log files and fill users' disks.

Comment (KoBeWi) [reply scene/animation/tween.cpp:322]: That's what I did at first, but it finished the tweening abruptly and a single error is hard to miss; it thought it could be confusing. But yeah, considering the logs, it's better not to spam.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
