### PR TITLE
Fix crash when inserting keyframes with empty properties array

### LINKED ISSUE #98751: Crash when inserting rotation keyframe
### Tested versions

Godot Engine v4.3.stable.flathub

### System information

Godot v4.3.stable (77dcf97d8) - Freedesktop SDK 24.08 (Flatpak runtime) - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (RADV NAVI23) - 12th Gen Intel(R) Core(TM) i5-12600K (16 Threads)

### Issue description

crash occurs when attempting to insert a rotation keyframe on a bone in this hierarchy 
spine -> spine.001 -> spine.002 -> spine.003 -> upper_arm.L
the skeleton and model mesh are imported from an FBX i downloaded off of itch.io
here: [https://dblob-ua.itch.io/low-poly-characterchar-ronin-01](url)

### Steps to reproduce

1. download the file and import it to godot
2. open it as a new inherited scene
3. place the animation track as a child to Skeleton3D
4. create a new animation
5. add upper_arm.L and upper_arm.R rotation to the track
6. insert a keyframe

godot will crash.

### Minimal reproduction project (MRP)

[keyframe_crash.zip](https://github.com/user-attachments/files/17605539/keyframe_crash.zip)

### LINKED ISSUE #99249: Crash on clicking Animation track key.
### Tested versions

673f396677654220d7e1d5b6fb5ed3b50126b4e6 - reproducible
4.3 stable - not reproducible

### System information

Arch Linux

### Issue description

Crash on clicking Animation track key.

Possibly a regression from a recent commit.

Here's the backtrace:

```cpp
#0  0x0000555557b77d4e in CowData<String>::get (this=<optimized out>, p_index=<optimized out>) at ./core/templates/cowdata.h:205
#1  0x00005555590e2b5b in Vector<String>::operator[] (this=0x55557857d508, p_index=0) at ./core/templates/vector.h:97
#2  EditorInspector::_parse_added_editors (this=this@entry=0x5555687fdc60, current_vbox=0x5555688144b0, p_section=p_section@entry=0x0, ped=...) at editor/editor_inspector.cpp:2727
#3  0x00005555590e38f9 in EditorInspector::update_tree (this=this@entry=0x5555687fdc60) at editor/editor_inspector.cpp:2910
#4  0x00005555590e85a2 in EditorInspector::edit (this=0x5555687fdc60, p_object=p_object@entry=0x55557e342340) at editor/editor_inspector.cpp:3765
#5  0x0000555559147193 in EditorNode::_edit_current (this=this@entry=0x555561327490, p_skip_foreign=p_skip_foreign@entry=false, p_skip_inspector_update=p_skip_inspector_update@entry=false) at editor/editor_node.cpp:2596
#6  0x000055555914763f in EditorNode::push_item (this=this@entry=0x555561327490, p_object=<optimized out>, p_property=..., p_inspector_only=p_inspector_only@entry=false) at editor/editor_node.cpp:2373
#7  0x0000555559958af8 in AnimationTrackEditor::_update_key_edit (this=this@entry=0x55556b0db4a0) at editor/animation_track_editor.cpp:5756
#8  0x000055555995b665 in AnimationTrackEditor::_key_selected (this=0x55556b0db4a0, p_key=0, p_single=true, p_track=<optimized out>) at editor/animation_track_editor.cpp:5660
#9  0x000055555997acc5 in call_with_variant_args_helper<AnimationTrackEditor, int, bool, int, 0ul, 1ul, 2ul> (p_instance=<optimized out>, p_method=<optimized out>, p_args=0x7fffffffd3a0, r_error=...) at ./core/variant/binder_common.h:304
#10 0x000055555997ad0f in call_with_variant_args<AnimationTrackEditor, int, bool, int> (p_instance=<optimized out>, p_method=<optimized out>, p_args=<optimized out>, p_argcount=<optimized out>, r_error=...) at ./core/variant/binder_common.h:418
#11 0x000055555997add4 in CallableCustomMethodPointer<AnimationTrackEditor, void, int, bool, int>::call (this=0x5555730ebe20, p_arguments=<optimized out>, p_argcount=<optimized out>, r_return_value=..., r_call_error=...) at ./core/object/callable_method_pointer.h:107
#12 0x000055555b1cab84 in Callable::callp (this=this@entry=0x55557e2e06b0, p_arguments=p_arguments@entry=0x7fffffffd3a0, p_argcount=3, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:57
#13 0x000055555b1cbaa4 in CallableCustomBind::call (this=0x55557e2e06a0, p_arguments=<optimized out>, p_argcount=2, r_return_value=..., r_call_error=...) at core/variant/callable_bind.cpp:150
#14 0x000055555b1cab84 in Callable::callp (this=this@entry=0x555560654860, p_arguments=p_arguments@entry=0x7fffffffd490, p_argcount=p_argcount@entry=2, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:57
#15 0x000055555b3d71b7 in CallQueue::_call_function (this=this@entry=0x55555ee575b0, p_callable=..., p_args=p_args@entry=0x555560654878, p_argcount=2, p_show_error=true) at core/object/message_queue.cpp:220
#16 0x000055555b3d73d9 in CallQueue::flush (this=0x55555ee575b0) at core/object/message_queue.cpp:268
#17 0x0000555559cd7bd9 in SceneTree::physics_process (this=0x5555612b53d0, p_time=0.016666666666666666) at scene/main/scene_tree.cpp:546
#18 0x0000555557bf264e in Main::iteration () at main/main.cpp:4384
#19 0x0000555557b7839e in OS_LinuxBSD::run (this=this@entry=0x7fffffffd6c0) at platform/linuxbsd/os_linuxbsd.cpp:962
#20 0x0000555557b767be in main (argc=<optimized out>, argv=0x7fffffffdd28) at platform/linuxbsd/godot_linuxbsd.cpp:85
```

### Steps to reproduce

Open project, click on AnimationPlayer on the Scene tree and click on the only key on the Animation track.

### Minimal reproduction project (MRP)

[ClickAnimationKeyToCrash.zip](https://github.com/user-attachments/files/17757989/ClickAnimationKeyToCrash.zip)

### PR DESCRIPTION
**Pull request by TopherBriggs**
# Fix crash when inserting keyframes with empty properties array

*Bugsquad edit:*
- ~Fixes (for 4.4) #98751 (Crash when inserting rotation keyframe)~
  Doesn't seem to be the case, the issue just sounds related.
- Fixes #99249.

## Description

When inserting rotation keyframes in the animation editor, clicking on the keyframe would cause the editor to crash due to an Array out-of-bound error. Upon further inspection using coredumpctl it seems to be crashing from a out-of-bounds index on editor_inspector.cpp:2727, with accessing `F.properties[0]` without checking if the properties array is empty could cause a crash. This is accessed to see if the property is in the favorites list. However, if an element such as AnimationTrackKeyEdit does not have any properties that can be favorited. This PR adds a safety check to prevent accessing an empty array.

## Modified Files

- `editor/editor_inspector.cpp`

## Changes

The following changes prevent the crash by adding an empty check before accessing the properties array:

```cpp
EditorProperty ***ep = Object::cast_to<EditorProperty>(F.property_editor);
- if (ep && current_favorites.has(F.properties[0])) {
+ if (ep && !F.properties.is_empty() && current_favorites.has(F.properties[0])) {
    ep->favorited = true;
    favorites_vbox->add_child(F.property_editor);
} else {
    current_vbox->add_child(F.property_editor);
}
```

## Testing

Tested with the provided reproduction case:
1. Imported the FBX model from the reproduction case
2. Created a new inherited scene
3. Added animation track as child to Skeleton3D
4. Created new animation
5. Added upper_arm.L and upper_arm.R rotation to track
6. Successfully inserted keyframe without crash

Tested on:
- Godot v4.4.dev
- Arch Linux x86_64 GNOME 47.1 Kernel: 6.11.6-arch1-1
- CPU: 12th Gen Intel i7-1260P (16) @ 4.700GHz 
- GPU: Intel Alder Lake-P GT2 [Iris Xe Graphics]

## Notes

The crash occurred because the properties array could be empty when attempting to insert certain types of keyframes in the animation editor. This fix ensures we check for empty arrays before accessing their elements, following proper array bounds checking practices.

### CODE REVIEW

**Comment by TokageItLab** [comment]
Can you provide a video capture of the detailed reproduction procedure for https://github.com/godotengine/godot/issues/98751 first? Since the crash does not occur in my environment.

Also, the code you are trying to fix has been no longer exist in master. So check again if the problem occurs on the latest master branch.

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -2724,7 +2724,7 @@ void EditorInspector::_parse_added_editors(VBoxContainer *current_vbox, EditorIn
 	for (const EditorInspectorPlugin::AddedEditor &F : ped->added_editors) {
 		EditorProperty *ep = Object::cast_to<EditorProperty>(F.property_editor);
 
-		if (ep && current_favorites.has(F.properties[0])) {
+		if (ep && !F.properties.is_empty() &&current_favorites.has(F.properties[0])) {
```
Comment (TokageItLab) [inline editor/editor_inspector.cpp:2727]:
```suggestion
		if (ep && !F.properties.is_empty() && current_favorites.has(F.properties[0])) {
```

**Review by TokageItLab — CHANGES_REQUESTED** [review]

**Review by fire — APPROVED** [review]
The logic to check for empty properties to avoid the crash makes sense. Also, the crash has been confirmed. Thirdly, I don't see how it will break the code even if it's wrong, so the risk of merging is low and the benefit of fixing a crash is high.

**Comment by TopherBriggs** [comment]
Here's the video capture of the crash reported by #98751 replicated on my machine:

https://github.com/user-attachments/assets/bb98a0ad-dcb0-4fb1-b8f4-d54835bbd6a5

With the change in this PR the crash no longer occurs:

https://github.com/user-attachments/assets/dd0da419-215a-4ec2-bf83-9d9421b34961

I also added the requested formatting change

**Comment by AThousandShips** [comment]
Need to confirm that the 4.3 crash is related so unlocking the issue until we can confirm a dedicated 4.3 version fixes this as the code is different

**Review by TokageItLab — APPROVED** [review]
I cannot reproduce the crash in my environment when I perform the same operation as in the video, so it may be an environment-dependent (Linux?) issue.

What I am concerned about is that this fix is not directly related to the animation, but is a check on the processing timing of the inspector plugin.

Considering that the inspector is displayed correctly after the fix, is it possible that the inspector plugin is being called multiple times and somewhere along the way null accesses are occurring? I think we need to take a closer look at why the property is missing there.

Well, as fire's comment says, it should be a safe change, so I think it's okay with merging it to prevent crashes for now.

**Comment by akien-mga** [comment]
I think #98751 was wrongly flagged as being the issue this solves, though I need to see if I can reproduce it to confirm.

This seems to be solving a very recent regression in `master` which is tracked in #99249. This one is reproducible for me in latest `master` but not 4.4-dev4 or 4.3-stable, and fixed by this PR.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Confirmed to be fixed a bug introduced by #97415 so it's not fixing #98751.
