### PR TITLE
Fixed ParseError when calling Object.new()

### LINKED ISSUE #41462: GDSCript: Object.new() throws Parse Error
**Godot version:**
3.2.2.stable.official

**OS/device including version:**
Windows 10, PC

**Issue description:**
An attempt to create an instance of `Object` by calling `Object.new()` ends with the following error:
`Parse Error: Static constant  'new' not present in built-in type Object`
This contradicts the documentation of Object that mentions the following:
> You can construct Objects from scripting languages, using `Object.new()` in GDScript, `new Object` in C#, or the "Construct Object" node in VisualScript.

**Steps to reproduce:**
Put the following in to `object-new.gd`:
```
extends MainLoop

func _init():
    var o = Object.new()
```

Then run:
```
godot --no-window --script object-new.gd
```

**Minimal reproduction project:**
[object-new-bug-report.zip](https://github.com/godotengine/godot/files/5113157/object-new-bug-report.zip)

### PR DESCRIPTION
**Pull request by Lunatoid**
Fixes #41462

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -2256,8 +2256,10 @@ void GDScriptAnalyzer::reduce_identifier(GDScriptParser::IdentifierNode *p_ident
...
 	p_identifier->source = GDScriptParser::IdentifierNode::UNDEFINED_SOURCE;
 
-	// Check globals.
-	if (GDScriptParser::get_builtin_type(name) < Variant::VARIANT_MAX) {
+	// Check globals. We make an exception for Variant::OBJECT because it's the base class for
+	// non-builtin types so we allow doing e.g. Object.new()
+	Variant::Type builtin_type = GDScriptParser::get_builtin_type(name);
+	if (builtin_type != Variant::OBJECT && builtin_type < Variant::VARIANT_MAX) {
 		if (can_be_builtin) {
 			p_identifier->set_datatype(make_builtin_meta_type(GDScriptParser::get_builtin_type(name)));
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:2264]: Since you're caching the value it makes sense to use it here too:
```suggestion
			p_identifier->set_datatype(make_builtin_meta_type(builtin_type);
```

**Review by vnen — CHANGES_REQUESTED** [review]
I added a suggestion to keep code consistency. Otherwise it looks fine.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 1 above)
Comment (Lunatoid) [reply modules/gdscript/gdscript_analyzer.cpp]: Good catch, will commit

**Comment by vnen** [comment]
Looks good, just need to squash the commits (see the [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase)). No need to keep me as co-author.

**Comment by aaronfranke** [comment]
@vnen Can you take a look at this? It seems good and has been rebased/squashed.

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
I marked this for cherry-picking but this code doesn't exist in the `3.2` branch.

If @Lunatoid or anyone else wants to fix #41462 in the `3.2` branch, and dedicated PR might be needed.

**Comment by Lunatoid** [comment]
I took a glance at it and the parsing seems to happen in `gdscript_parser.gd` around line 631. It looks like the function `new` doesn't exist on `Object`. Things like `Node` get parsed differently because that's considered an `IDENTIFIER` instead of a `BUILTIN_TYPE`.

I tried to add a condition ` || identifier == "new"` at line 649 but that just resulted in `Attempt to call function 'new' in base 'null instance' on a null instance`, so that didn't work.

I would suggest someone with more knowledge regarding the scripting implementation takes a look at it.
