### PR TITLE
Tween: Always remove the desired InterpolateData when finished

### LINKED ISSUE #21030: Tween.interpolate_callback does not call some of calls with reversed delay time
**Godot version:**

3.1.dev da157744c

**OS/device including version:**

not related

**Issue description:**

`Tween.interpolate_callback` does not call some of calls with reversed delay time.
It worked fine but not with recently.

**Steps to reproduce:**
```gdscript
func _ready():
	var tw = Tween.new()
	add_child(tw)
	
	for i in 10:
		var delay = 1 - 0.1 * i
		prints(i, "delay=", delay)
		tw.interpolate_callback(self, delay, "tween_test", i)
	tw.start()

func tween_test(p_value):
	printt("tween_test", p_value)
```
result on output panel
```
0 delay= 1
1 delay= 0.9
2 delay= 0.8
3 delay= 0.7
4 delay= 0.6
5 delay= 0.5
6 delay= 0.4
7 delay= 0.3
8 delay= 0.2
9 delay= 0.1
tween_test	9
tween_test	8
tween_test	7
tween_test	6
tween_test	5
```
some of calls are removed

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by gotnospirit**
Hi,
This is intended to fix #21030.
After many tries, I ended up adding a unique identifier in the InterpolateData struct in order to be sure which ones are removed.
Feel free to comment this PR, especially the implementation of `Tween::_push_interpolate_data`!

### CODE REVIEW

**Comment by volzhs** [comment]
Thank you for such great and fast work. :+1:

File: scene/animation/tween.cpp [hunk 1]
```diff
@@ -797,16 +798,50 @@ void Tween::_remove(Object *p_object, StringName p_key, bool first_only) {
...
+		}
+	}
+}
+
+void Tween::_push_interpolate_data(InterpolateData &p_data) {
+	pending_update++;
+	int uid = 0;
+	if (!interpolates.empty()) {
+		// We are looking for the first available uid
+		while (true) {
```
Comment (bojidar-bg) [inline scene/animation/tween.cpp]: This is going to be a performance-intensive loop if you make many tweens, since it is going to loop N * N / 2 times for N tweens if none are removed.

It might be better if the tween keeps an `private: int uid` field, and increments it every time. The int might wraparound, but it is expected when running ~2¹⁶ tweens at once.

Comment (gotnospirit) [reply scene/animation/tween.cpp]: Yes, I was expecting a performance issue here.
`Tween::remove_all` is ok, but do you think we should try to find the lowest uid at the end of `Tween::_remove` & `Tween::_remove_by_uid`?

Comment (bojidar-bg) [reply scene/animation/tween.cpp]: No, since the lowest uid might have some uid-s high than it which are already taken. No one would make that many tweens on a single node as to overflow the int anyway.

Comment (gotnospirit) [reply scene/animation/tween.cpp]: Ok, great!

File: scene/animation/tween.cpp [hunk 2]
```diff
@@ -778,14 +779,14 @@ bool Tween::resume_all() {
 }
 
 bool Tween::remove(Object *p_object, StringName p_key) {
-	_remove(p_object, p_key, false);
+	_remove(p_object, p_key);
```
Comment (akien-mga) [inline scene/animation/tween.cpp]: What's the point of having both `remove` and `_remove` if the only different is that the former already returns true (which is not particularly useful...)?

Seems to me like `_remove` could be merged into `remove` and removed :)
Ideally it should be `void Tween::remove` since the return value is meaningless, but to avoid breaking compatibility it's probably best to keep it as `bool Tween::remove`.

Comment (gotnospirit) [reply scene/animation/tween.cpp]: You're right, I will merge them and keep `bool Tween::remove`.

**Comment by akien-mga** [comment]
Thanks!

**Comment by eligt** [comment]
Hey guys, this seems to add the same function that I added in my tween-sequences branch: https://github.com/godotengine/godot/pull/20934

My branch adds 'handles' for individual animation which can then be used to refer to them uniquely to create sequences and spawners (and to remove them) and they serve the same purpose as the 'uid' here. In-fact, this particular commit created conflicts with my branch. I'm planning on keeping my 'handle' concept because that's a value that is actually exposed to scripts, what do you think?
