### PR TITLE
PopupMenu: Fix inconsistency setting text/xl_text in add_* methods

### LINKED ISSUE #25519: MenuButton Label dissapears when a shortcut is set.
**Godot version:**
Latest from: https://hugo.pro/projects/godot-builds/ (v3.1.beta.calinou.c21ca98)

**OS/device including version:**
Windows 10

**Issue description:**
MenuButton items lose the label when a shortcut is set.

**Steps to reproduce:**
1. Create new scene with a Control node as the root
2. Add MenuButton node
3. Add this code to the root node:
```
extends Control

func _ready():
	# Add items
	$MenuButton.get_popup().add_item("I'm a regular item")
	$MenuButton.get_popup().add_item("I am not")
	
	# Create the shortcut
	var shortcut = ShortCut.new()
	var inputeventkey = InputEventKey.new()
	inputeventkey.set_scancode(KEY_Q)
	inputeventkey.control = true
	shortcut.set_shortcut(inputeventkey)
	
	# Set shortcut
	$MenuButton.get_popup().set_item_shortcut(1, shortcut, true)
```

4. Run project and check how the label on the second menu item is gone.

**Minimal reproduction project:**
[MenuButtonItemBug.zip](https://github.com/godotengine/godot/files/2818183/MenuButtonItemBug.zip)

### PR DESCRIPTION
**Pull request by akien-mga**
- **Part 1, cleanup:** Reorder `add_*` methods in more natural order
  Also adds `add_icon_radio_check_shortcut` matching `add_icon_radio_check_item`,
  binds them for scripting languages, and binds `add_multistate_item`.

- **Part 2, bugfix for #25519:** Fix missing `text`/`xl_text` when using `add_shortcut`
  Use macros to ensure that `text`, `xl_text` and `id` are always set
  using the same logic.

  Fixes #25519.

  Also fixes up #26914 when `p_id == -1` handling was only added for a
  couple methods instead of all of them. (upcoming)

For the reference the second commit is basically the same as #25841 (which was reverted), but together with a proper fix for the editor bug it exposed back then (#25900).

BTW, this PopupMenu API is a complete mess :o)
We shouldn't need to have so many duplicated methods to add items with specific configuration changes.

### CODE REVIEW

File: scene/gui/popup_menu.cpp [hunk 1]
```diff
@@ -685,75 +679,68 @@ void PopupMenu::add_icon_check_item(const Ref<Texture> &p_icon, const String &p_
...
 	minimum_size_changed();
 }
 
-void PopupMenu::add_shortcut(const Ref<ShortCut> &p_shortcut, int p_id, bool p_global) {
-
-	ERR_FAIL_COND(p_shortcut.is_null());
+#define ITEM_SETUP_WITH_SHORTCUT(p_shortcut, p_id, p_global)                           \
+	ERR_FAIL_COND_MSG(p_shortcut.is_null(), "Cannot add item with invalid ShortCut."); \
+	_ref_shortcut(p_shortcut);                                                         \
+	item.text = p_shortcut->get_name();                                                \
```
Comment (akien-mga) [inline scene/gui/popup_menu.cpp]: This is the main logic change, where `add_shortcut*` methods will now properly set the `Item`'s `text` and `xl_text` to the ShortCut's name.

**Review by YeldhamDev — APPROVED** [review]

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2. (Only commit 58dd5d0.)
