### PR TITLE
Disable thread-unsafe EditorProgress for navmesh baking

### LINKED ISSUE #57815: Calling NavigationRegion3D.bake_nav_mesh() in the editor from an EditorPlugin causes the editor to crash
### Godot version

4.0, 254778327afe7ffe389284fb09398c9ea810a2ba

### System information

Arch Linux

### Issue description

Calling [bake_navigation_mesh](https://docs.godotengine.org/en/latest/classes/class_navigationregion3d.html#class-navigationregion3d-method-bake-navigation-mesh) on a NavigationRegion3D causes the engine to randomly crash, even if you await for the bake_finished signal. Sometimes it just works, so I believe it might be a race condition.

### Steps to reproduce

From an EditorPlugin create a NavigationRegion3D add it to the tree, put your geometry as a child of it and call the bake_nav_mesh method, it will randomly crash.

### Minimal reproduction project

[NavigationRegionBug.zip](https://github.com/godotengine/godot/files/8027684/NavigationRegionBug.zip)

Open the "Bug" tab and press the magic button:

imagen

### Backtrace

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.alpha.custom_build (a79dc77033c75a719e4eb44197d80232ef1d4029)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x3cda0) [0x7f56f1b5eda0] (??:0)
[2] Callable::get_object() const (??:0)
[3] MessageQueue::statistics() (??:0)
[4] MessageQueue::push_callable(Callable const&, Variant const**, int, bool) (??:0)
[5] MessageQueue::push_call(ObjectID, StringName const&, Variant const**, int, bool) (??:0)
[6] MessageQueue::push_call(ObjectID, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:0)
[7] MessageQueue::push_call(Object*, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:0)
[8] CanvasItem::update() (??:0)
[9] Button::set_text(String const&) (??:0)
[10] EditorLog::LogFilter::set_message_count(int) (??:0)
[11] EditorLog::_process_message(String const&, EditorLog::MessageType) (??:0)
[12] EditorLog::add_message(String const&, EditorLog::MessageType) (??:0)
[13] EditorNode::_print_handler(void*, String const&, bool) (??:0)
[14] __print_line(String) (??:0)
[15] MessageQueue::push_callable(Callable const&, Variant const**, int, bool) (??:0)
[16] MessageQueue::push_call(ObjectID, StringName const&, Variant const**, int, bool) (??:0)
[17] MessageQueue::push_call(ObjectID, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:0)
[18] MessageQueue::push_call(Object*, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:0)
[19] Object::call_deferred(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:0)
[20] EditorToaster::popup_str(String, EditorToaster::Severity, String) (??:0)
[21] EditorToaster::_error_handler(void*, char const*, char const*, int, char const*, char const*, bool, ErrorHandlerType) (??:0)
[22] _err_print_error(char const*, char const*, int, char const*, char const*, bool, ErrorHandlerType) (??:0)
[23] _err_print_error(char const*, char const*, int, char const*, bool, ErrorHandlerType) (??:0)
[24] RendererCanvasRenderRD::_render_item(long, RID, RendererCanvasRender::Item const*, long, Transform2D const&, RendererCanvasRender::Item*&, RendererCanvasRender::Light*, RendererCanvasRenderRD::PipelineVariants*) (??:0)
[25] RendererCanvasRenderRD::_render_items(RID, int, Transform2D const&, RendererCanvasRender::Light*, bool) (??:0)
[26] RendererCanvasRenderRD::canvas_render_items(RID, RendererCanvasRender::Item*, Color const&, RendererCanvasRender::Light*, RendererCanvasRender::Light*, Transform2D const&, RenderingServer::CanvasItemTextureFilter, RenderingServer::CanvasItemTextureRepeat, bool, bool&) (??:0)
[27] RendererCanvasCull::_render_canvas_item_tree(RID, RendererCanvasCull::Canvas::ChildItem*, int, RendererCanvasCull::Item*, Transform2D const&, Rect2 const&, Color const&, RendererCanvasRender::Light*, RendererCanvasRender::Light*, RenderingServer::CanvasItemTextureFilter, RenderingServer::CanvasItemTextureRepeat, bool) (??:0)
[28] RendererCanvasCull::render_canvas(RID, RendererCanvasCull::Canvas*, Transform2D const&, RendererCanvasRender::Light*, RendererCanvasRender::Light*, Rect2 const&, RenderingServer::CanvasItemTextureFilter, RenderingServer::CanvasItemTextureRepeat, bool, bool) (??:0)
[29] RendererViewport::_draw_viewport(RendererViewport::Viewport*) (??:0)
[30] RendererViewport::draw_viewports() (??:0)
[31] RenderingServerDefault::_draw(bool, double) (??:0)
[32] RenderingServerDefault::draw(bool, double) (??:0)
[33] Main::iteration() (??:0)
[34] ProgressDialog::task_step(String const&, String const&, int, bool) (??:0)
[35] EditorNode::progress_task_step(String const&, String const&, int, bool) (??:0)
[36] EditorProgress::step(String const&, int, bool) (??:0)
[37] NavigationMeshGenerator::_build_recast_navigation_mesh(Ref<NavigationMesh>, EditorProgress*, rcHeightfield*, rcCompactHeightfield*, rcContourSet*, rcPolyMesh*, rcPolyMeshDetail*, Vector<float>&, Vector<int>&) (??:0)
[38] NavigationMeshGenerator::bake(Ref<NavigationMesh>, Node*) (??:0)
[39] GodotNavigationServer::region_bake_navmesh(Ref<NavigationMesh>, Node*) const (??:0)
[40] _bake_navigation_mesh(void*) (??:0)
[41] Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) (??:0)
[42] void std::__invoke_impl<void, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*>(std::__invoke_other, void (*&&)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*&&, Thread::Settings&&, void (*&&)(void*), void*&&) (??:0)
[43] std::__invoke_result<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*>::type std::__invoke<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*>(void (*&&)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*&&, Thread::Settings&&, void (*&&)(void*), void*&&) (??:0)
[44] void std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >::_M_invoke<0ul, 1ul, 2ul, 3ul, 4ul>(std::_Index_tuple<0ul, 1ul, 2ul, 3ul, 4ul>) (??:0)
[45] std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >::operator()() (??:0)
[46] std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> > >::_M_run() (??:0)
[47] /usr/lib/libstdc++.so.6(+0xd33c4) [0x7f56f1f203c4] (??:0)
[48] /usr/lib/libpthread.so.0(+0x9259) [0x7f56f207f259] (??:0)
[49] /usr/lib/libc.so.6(clone+0x43) [0x7f56f1c205e3] (??:0)
-- END OF BACKTRACE --
================================================================
```

### PR DESCRIPTION
**Pull request by smix8**
As discussed in devchat disables navmesh baking EditorProgress for now until EditorProgress is reworked to be thread-safe.

Fixes #57815 and other random reported navmesh baking crashes when using threads and a tool build.

EditorProgress is currently not thread-safe and uses hacks and Main::iteration() for steps() which can result in random crashes when baking navmesh on a thread (which is enabled by default). Should be enabled again when EditorProgress is fixed so left a FIXME note.

### CODE REVIEW

File: modules/navigation/navigation_mesh_generator.cpp [hunk 1]
```diff
@@ -631,7 +631,12 @@ void NavigationMeshGenerator::bake(Ref<NavigationMesh> p_nav_mesh, Node *p_node)
 
 #ifdef TOOLS_ENABLED
 	EditorProgress *ep(nullptr);
-	if (Engine::get_singleton()->is_editor_hint()) {
+	// FIXME
+	// After discussion on devchat disabled EditorProgress for now as it is not thread-safe and uses hacks and Main::iteration() for steps.
+	// EditorProgress randomly crashes the Engine when the bake function is used with a thread e.g. inside Editor with a tool script and procedural navigation
+	// This was not a problem in older versions as previously Godot was unable to (re)bake NavigationMesh at runtime.
+	// If EditorProgress is fixed and made thread-safe this should be enabled again.
+	if (Engine::get_singleton()->is_editor_hint() && false) {
```
Comment (akien-mga) [inline modules/navigation/navigation_mesh_generator.cpp:639]: Instead of adding `false` (some compilers might raise a warning that it's a tautological condition) I'd move the comment before the `#ifdef` and change it to a `#if 0`, so you skip the whole EP specific code.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by smix8** [comment]
@akien-mga
No EditorProgress is the same in 3.5 so 3.5 also has the same issues since the backported new Navigation that made baking threaded by default.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.
