### PR TITLE
Fix is_move_and_slide_on_wall, make move_and_slide floor angle configurable

### LINKED ISSUE #7313: is_move_and_slide_on_wall() and is_move_and_slide_on_ceiling()  Issue
Windows 7- Godot 2.2 alpha 

is_move_and_slide_on_wall() doesn't work at all, always returns false, and is_move_and_slide_on_ceiling() works like if you were using "is_move_and_slide_on_wall()", if you collide with a wall returns true. 

image

### PR DESCRIPTION
**Pull request by bojidar-bg**
Fixes #7313

### CODE REVIEW

File: scene/2d/physics_body_2d.cpp [hunk 1]
```diff
@@ -1189,7 +1189,7 @@ Vector2 KinematicBody2D::move_and_slide(const Vector2 &p_linear_velocity, const
 				//all is a wall
 				move_and_slide_on_wall = true;
 			} else {
-				if (get_collision_normal().dot(p_floor_direction) > Math::cos(Math::deg2rad((float)45))) { //floor
+				if (get_collision_normal().dot(p_floor_direction) >= Math::cos(Math::deg2rad(p_floor_max_angle))) { //floor
```
Comment (akien-mga) [inline scene/2d/physics_body_2d.cpp]: Is the equality case really meaningful when working with floats?

Comment (tagcup) [inline scene/2d/physics_body_2d.cpp]: It is meaningful on the hardware level (cmpsd sets the comparison predicate to 0 for equality), although it shouldn't matter much in practice since our errors are most likely larger than a single ULP.

**Comment by tagcup** [comment]
Math functions work with radians, so I think `deg2rad` should be called by the user if desired.

File: scene/2d/physics_body_2d.cpp [hunk 2]
```diff
@@ -1198,7 +1198,7 @@ Vector2 KinematicBody2D::move_and_slide(const Vector2 &p_linear_velocity, const
 						revert_motion();
 						return Vector2();
 					}
-				} else if (get_collision_normal().dot(p_floor_direction) < Math::cos(Math::deg2rad((float)45))) { //ceiling
+				} else if (get_collision_normal().dot(p_floor_direction) <= -Math::cos(Math::deg2rad(p_floor_max_angle))) { //ceiling
```
Comment (tagcup) [inline scene/2d/physics_body_2d.cpp]: Just a matter of style, but I think it would read nicer if you negate the floor direction (which would correspond to ceiling normal) rather than cosine.

Also, you're assuming the ceiling and ground are always parallel to each other, but this can also be relaxed by introducing a ceiling direction parameter.

File: scene/2d/physics_body_2d.cpp (hunk 1 above)
Comment (bojidar-bg) [inline scene/2d/physics_body_2d.cpp]: @akien-mga Well, it you pass `0` as `p_floor_max_angle`, you still want to get matches for exactly perpendicular walls. From my quick testing, it felt much more natural that way.

File: scene/2d/physics_body_2d.cpp (hunk 2 above)
Comment (bojidar-bg) [inline scene/2d/physics_body_2d.cpp]: @tagcup What would you do about this though? 0.785398 isn't a really intuitive default value...
image

Comment (tagcup) [inline scene/2d/physics_body_2d.cpp]: Oh, right. How about we write that the default value is π/4 in the documentation?

Comment (bojidar-bg) [inline scene/2d/physics_body_2d.cpp]: Done.

**Comment by tagcup** [comment]
So do you want to keep the assumption that floor and ceiling must be parallel?

**Comment by reduz** [comment]
I think its fine they are parallel, but different angles for floot and
ceiling may be desired..

On Apr 4, 2017 1:36 PM, "Ferenc Arn" <notifications@github.com> wrote:

So do you want to keep the assumption that floor and ceiling must be
parallel?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/pull/8259#issuecomment-291557801>,
or mute
the thread

**Comment by bojidar-bg** [comment]
Ok, feel free to purpose an API which would feel good, and I can implement it...

**Comment by tagcup** [comment]
I was thinking of something like

```cpp
move_and_slide(const Vector2 &p_linear_velocity, const Vector2 &p_floor_normal, const Vector2 &p_ceiling_normal, float p_max_angle, float p_slope_stop_min_velocity, int p_max_bounces)
```

```cpp
move_and_slide(const Vector2 &p_linear_velocity, const Vector2 &p_floor_normal, float p_max_floor_angle, const Vector2 &p_ceiling_normal, float p_max_ceiling_angle, float p_slope_stop_min_velocity, int p_max_bounces)
```

but I think @reduz means something like this
```cpp
move_and_slide(const Vector2 &p_linear_velocity, const Vector2 &p_floor_normal, float p_max_floor_angle, float p_max_ceiling_angle, float p_slope_stop_min_velocity, int p_max_bounces)
```

(we can still break compatibility, so it should be fine to change the ordering of parameters to a more sensible one)

**Comment by akien-mga** [comment]
Merging that fix as a first step. Further API enhancements could come in another commit.
