### PR TITLE
Fix shader compiler asan out of bounds

### LINKED ISSUE #68623: [Godot 4 Beta 4] FogMaterial shader compilation causes a global buffer overflow
### Godot version

4.0 beta 4 asan

### System information

Windows 10

### Issue description

While trying to identify why my game was crashing suddenly, I compiled Godot with ASAN enabled, and found that ASAN kills the game when it tries to compile shaders for FogMaterials used by FogVolumes. This doesn't crash the game when not compiled with ASAN, and ultimately it does look and behave as expected.

The ASAN crash report is below:
```
=================================================================
==4364==ERROR: AddressSanitizer: global-buffer-overflow on address 0x7ff71b4a2d68 at pc 0x7ff71459402c bp 0x00f4371ea730 sp 0x00f4371ea738
READ of size 4 at 0x7ff71b4a2d68 thread T0
    #0 0x7ff71459402b in ShaderLanguage::get_scalar_type(enum ShaderLanguage::DataType) C:\Users\thePG\Documents\Godot\Entombed\build\godot\servers\rendering\shader_language.cpp:4314
    #1 0x7ff7145b0afe in ShaderLanguage::_validate_function_call(struct ShaderLanguage::BlockNode *, struct ShaderLanguage::FunctionInfo const &, struct ShaderLanguage::OperatorNode *, enum ShaderLanguage::DataType *, class StringName *) C:\Users\thePG\Documents\Godot\Entombed\build\godot\servers\rendering\shader_language.cpp:3062
    #2 0x7ff7145bd672 in ShaderLanguage::_parse_expression(struct ShaderLanguage::BlockNode *, struct ShaderLanguage::FunctionInfo const &) C:\Users\thePG\Documents\Godot\Entombed\build\godot\servers\rendering\shader_language.cpp:5154
    #3 0x7ff7145d0bf6 in ShaderLanguage::_parse_and_reduce_expression(struct ShaderLanguage::BlockNode *, struct ShaderLanguage::FunctionInfo const &) C:\Users\thePG\Documents\Godot\Entombed\build\godot\servers\rendering\shader_language.cpp:6679
    #4 0x7ff7145df679 in ShaderLanguage::_parse_block(struct ShaderLanguage::BlockNode *, struct ShaderLanguage::FunctionInfo const &, bool, bool, bool) C:\Users\thePG\Documents\Godot\Entombed\build\godot\servers\rendering\shader_language.cpp:7714
    #5 0x7ff7145fc0b0 in ShaderLanguage::_parse_shader(class HashMap<class StringName, struct ShaderLanguage::FunctionInfo, struct HashMapHasherDefault, struct HashMapComparatorDefault<class StringName>, class DefaultTypedAllocator<struct HashMapElement<class StringName, struct ShaderLanguage::FunctionInfo>>> const &, class Vector<struct ShaderLanguage::ModeInfo> const &, class HashSet<class String, struct HashMapHasherDefault, struct HashMapComparatorDefault<class String>> const &) C:\Users\thePG\Documents\Godot\Entombed\build\godot\servers\rendering\shader_language.cpp:9547
    #6 0x7ff7145fe49c in ShaderLanguage::compile(class String const &, struct ShaderLanguage::ShaderCompileInfo const &) C:\Users\thePG\Documents\Godot\Entombed\build\godot\servers\rendering\shader_language.cpp:9764
    #7 0x7ff7146790a9 in ShaderCompiler::compile(enum RenderingServer::ShaderMode, class String const &, struct ShaderCompiler::IdentifierActions *, class String const &, struct ShaderCompiler::GeneratedCode &) C:\Users\thePG\Documents\Godot\Entombed\build\godot\servers\rendering\shader_compiler.cpp:1363
    #8 0x7ff7147d3971 in RendererRD::Fog::FogShaderData::set_code(class String const &) C:\Users\thePG\Documents\Godot\Entombed\build\godot\servers\rendering\renderer_rd\environment\fog.cpp:350
    #9 0x7ff7147b2342 in RendererRD::MaterialStorage::shader_set_code(class RID, class String const &) C:\Users\thePG\Documents\Godot\Entombed\build\godot\servers\rendering\renderer_rd\storage_rd\material_storage.cpp:2425
    #10 0x7ff714310e2b in RenderingServerDefault::shader_set_code(class RID, class String const &) C:\Users\thePG\Documents\Godot\Entombed\build\godot\servers\rendering\rendering_server_default.h:226
    #11 0x7ff71390ef75 in FogMaterial::_update_shader(void) C:\Users\thePG\Documents\Godot\Entombed\build\godot\scene\resources\fog_material.cpp:145
    #12 0x7ff71391354f in FogMaterial::get_rid(void) const C:\Users\thePG\Documents\Godot\Entombed\build\godot\scene\resources\fog_material.cpp:103
    #13 0x7ff7133a682b in FogVolume::set_material(class Ref<class Material> const &) C:\Users\thePG\Documents\Godot\Entombed\build\godot\scene\3d\fog_volume.cpp:85
    #14 0x7ff7133ab89d in call_with_variant_args_helper<class FogVolume, class Ref<class Material> const &, 0>(class FogVolume *, void (__cdecl FogVolume::*)(class Ref<class Material> const &), class Variant const **, struct Callable::CallError &, struct IndexSequence<0>) C:\Users\thePG\Documents\Godot\Entombed\build\godot\core\variant\binder_common.h:262
    #15 0x7ff7133aaf4a in call_with_variant_args_dv<class FogVolume, class Ref<class Material> const &>(class FogVolume *, void (__cdecl FogVolume::*)(class Ref<class Material> const &), class Variant const **, int, struct Callable::CallError &, class Vector<class Variant> const &) C:\Users\thePG\Documents\Godot\Entombed\build\godot\core\variant\binder_common.h:409
    #16 0x7ff7133b01ae in MethodBindT<class FogVolume, class Ref<class Material> const &>::call(class Object *, class Variant const **, int, struct Callable::CallError &) C:\Users\thePG\Documents\Godot\Entombed\build\godot\core\object\method_bind.h:318
    #17 0x7ff71587825f in ClassDB::set_property(class Object *, class StringName const &, class Variant const &, bool *) C:\Users\thePG\Documents\Godot\Entombed\build\godot\core\object\class_db.cpp:1071
    #18 0x7ff71565d2c5 in Object::set(class StringName const &, class Variant const &, bool *) C:\Users\thePG\Documents\Godot\Entombed\build\godot\core\object\object.cpp:249
    #19 0x7ff7109668f6 in SceneState::instantiate(enum SceneState::GenEditState) const C:\Users\thePG\Documents\Godot\Entombed\build\godot\scene\resources\packed_scene.cpp:331
    #20 0x7ff710970593 in PackedScene::instantiate(enum PackedScene::GenEditState) const C:\Users\thePG\Documents\Godot\Entombed\build\godot\scene\resources\packed_scene.cpp:1749
    #21 0x7ff70e6d2c65 in Main::start(void) C:\Users\thePG\Documents\Godot\Entombed\build\godot\main\main.cpp:2973
    #22 0x7ff70e58bc3c in widechar_main(int, wchar_t **) C:\Users\thePG\Documents\Godot\Entombed\build\godot\platform\windows\godot_windows.cpp:178
    #23 0x7ff70e58bf26 in _main(void) C:\Users\thePG\Documents\Godot\Entombed\build\godot\platform\windows\godot_windows.cpp:203
    #24 0x7ff70e58bfa1 in main C:\Users\thePG\Documents\Godot\Entombed\build\godot\platform\windows\godot_windows.cpp:217
    #25 0x7ff70e58ad9c in WinMain C:\Users\thePG\Documents\Godot\Entombed\build\godot\platform\windows\godot_windows.cpp:230
    #26 0x7ff717531d09 in invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:102
    #27 0x7ff717531d09 in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #28 0x7ffa700c74b3  (C:\Windows\System32\KERNEL32.DLL+0x1800174b3)
    #29 0x7ffa709226a0  (C:\Windows\SYSTEM32\ntdll.dll+0x1800526a0)

0x7ff71b4a2d68 is located 8 bytes to the right of global variable '`ShaderLanguage::get_scalar_type'::`2'::scalar_types' defined in 'shader_language.cpp:4287:23' (0x7ff71b4a2d00) of size 96
SUMMARY: AddressSanitizer: global-buffer-overflow C:\Users\thePG\Documents\Godot\Entombed\build\godot\servers\rendering\shader_language.cpp:4314 in ShaderLanguage::get_scalar_type(enum ShaderLanguage::DataType)
Shadow bytes around the buggy address:
  0x126ab4f14550: 00 00 01 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x126ab4f14560: 00 00 00 01 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x126ab4f14570: 00 00 00 04 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x126ab4f14580: 00 00 06 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x126ab4f14590: 00 04 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
=>0x126ab4f145a0: 00 00 00 00 00 00 00 00 00 00 00 00 f9[f9]f9 f9
  0x126ab4f145b0: f9 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x126ab4f145c0: 00 00 00 00 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x126ab4f145d0: 00 00 00 00 00 00 00 00 01 f9 f9 f9 f9 f9 f9 f9
  0x126ab4f145e0: f9 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 02 f9
  0x126ab4f145f0: f9 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==4364==ABORTING
```

### Steps to reproduce

1. Create a new project, with a 3D scene
2. Add a FogVolume and a camera to the scene
3. Give the FogVolume a FogMaterial
4. Add a WorldEnvironment to the scene, and enable volumetric fog
5. Run the project with an ASAN-enabled build of Godot

### Minimal reproduction project

[FogMaterial.zip](https://github.com/godotengine/godot/files/9998079/FogMaterial.zip)

### PR DESCRIPTION
**Pull request by dzil123**
Fixes #68623

`ShaderLanguage::get_scalar_type` and `ShaderLanguage::get_cardinality` index into an array, but as new elements were added to `enum DataType` these arrays have not been updated.
An UB out of bounds read occurs if any type > `TYPE_SAMPLER2DARRAY` is passed as arguments to a function, including *Sampler2DArray, *Sampler3D, SamplerCube(Array), and Struct.

Examples of shaders producing this bug (4.0 and 3.x):
```glsl
shader_type spatial;

uniform sampler3D tex;

void fragment() {
    ALBEDO = texture(tex, vec3(0.0)).rgb;
}
```
```glsl
shader_type spatial;

struct Foo {
        float bar;
};

float get_bar(Foo foo) {
        return foo.bar;
}

void fragment() {
        Foo foo = Foo(0.5);
        ALBEDO = vec3(get_bar(foo));
}
```

The fix is to add the missing values, and add a check to ensure that the length of the array matches the number of types. I tried to match the values, but as far as I can tell from how `get_scalar_type` and `get_cardinality` are used, if the type doesn't have a constructor then the exact values don't matter, as long as `get_scalar_type(type) != type`.

This PR is compatible with 3.x, once `TYPE_MAX` is added to `enum DataType`.

### CODE REVIEW

**Comment by Chaosus** [comment]
> An UB out of bounds read occurs if any type > TYPE_SAMPLER2DARRAY is passed as arguments to a function

Why not simply detect where it's doing in the fog pipeline and fix that? Or simply limit it by adding ERR_FAIL_INDEX to the beginning of `get_scalar_type` and `get_cardinality`?

**Comment by dzil123** [comment]
This bug is not in the fog pipeline, it is a bug in ShaderLanguage that occurs while parsing any gdshader that calls a function with a Sampler or Struct argument.

I suppose this could be fixed with a CLAMP, but then `get_scalar_type(TYPE_USAMPLER3D)` would return `TYPE_FLOAT` while `get_scalar_type(TYPE_USAMPLER2D)` would return `TYPE_UINT`. The commit that introduced `get_scalar_type`, 850eaf7e, makes it clear to me that there is intended to be a 1:1 mapping of [DataType](https://github.com/godotengine/godot/blob/850eaf7ed796d2f2d9a35c6bc4ba9a4e69f5ca1d/servers/visual/shader_language.h#L152) to [get_scalar_type](https://github.com/godotengine/godot/blob/850eaf7ed796d2f2d9a35c6bc4ba9a4e69f5ca1d/servers/visual/shader_language.cpp#L2125).

File: servers/rendering/shader_language.cpp [hunk 1]
```diff
@@ -4309,8 +4309,18 @@ ShaderLanguage::DataType ShaderLanguage::get_scalar_type(DataType p_type) {
 		TYPE_INT,
 		TYPE_UINT,
 		TYPE_FLOAT,
+		TYPE_INT,
+		TYPE_UINT,
+		TYPE_FLOAT,
+		TYPE_INT,
+		TYPE_UINT,
+		TYPE_FLOAT,
+		TYPE_FLOAT,
```
Comment (Chaosus) [inline servers/rendering/shader_language.cpp:4318]: I would simply replace all of them with TYPE_VOID, since they cannot be represented by a scalar value.

Comment (dzil123) [reply servers/rendering/shader_language.cpp:4318]: I was trying to match the original commit, which assigned TYPE_SAMPLER2D -> TYPE_FLOAT, TYPE_ISAMPLER2D -> TYPE_INT, and TYPE_USAMPLER2D -> TYPE_UINT. I'm not sure, but I don't think this is required anywhere, so I guess yes all samplers can be set to TYPE_VOID.

**Comment by Chaosus** [comment]
> This bug is not in the fog pipeline, it is a bug in ShaderLanguage that occurs while parsing any gdshader that calls a function with a Sampler or Struct argument.

> I suppose this could be fixed with a CLAMP, but then get_scalar_type(TYPE_USAMPLER3D) would return TYPE_FLOAT while get_scalar_type(TYPE_USAMPLER2D) would return TYPE_UINT. The commit that introduced get_scalar_type, https://github.com/godotengine/godot/commit/850eaf7ed796d2f2d9a35c6bc4ba9a4e69f5ca1d, makes it clear to me that there is intended to be a 1:1 mapping of [DataType](https://github.com/godotengine/godot/blob/850eaf7ed796d2f2d9a35c6bc4ba9a4e69f5ca1d/servers/visual/shader_language.h#L152) to [get_scalar_type](https://github.com/godotengine/godot/blob/850eaf7ed796d2f2d9a35c6bc4ba9a4e69f5ca1d/servers/visual/shader_language.cpp#L2125).

You are right, never mind, I just not completely awakened

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by dzil123** [comment]
Do we still want to set all the sampler types to TYPE_VOID? I tested an asan build and it appears to work.
