### PR TITLE
Fix TextEdit VScroll max tolerance

### LINKED ISSUE #104466: TextEdit Scroll Repeats Last Line and Text Pops In
### Tested versions

- Reproducible in 4.4 Stable, 4.3 Stable, 4.2.2 Stable, 4.2 Stable
- Not Reproducible in 4.1.4 Stable

### System information

Godot v4.2.stable - macOS 14.5.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (10 Threads)

### Issue description

For certain heights, the `TextEdit` displays text only displays when the line is fully visible, like a popping into existence effect. This also causes the last line to appear to repeat twice when scrolling down.

For one line; the following heights have issues: 15-21, 23-24, 26-29, 31-32, 34 px

https://github.com/user-attachments/assets/82f8544a-3491-44d5-9da7-ca0a70ed694b

### Steps to reproduce

1. Create a scene with a TextEdit Node
2. Set the text to "0"
3. Set the size to (100, 32)
4. Run the scene, and scroll down on the TextEdit

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/user-attachments/files/19400545/MRP.zip)

### PR DESCRIPTION
**Pull request by BrotherShort**
fix #104466

### CODE REVIEW

**Comment by lodetrick** [comment]
It seems like #14848 introduced those two lines that you edited. I don't have time right now, but we should make sure that this doesn't revert any changes that were intended by that PR. I am somewhat confused by their inclusion for now.

**Comment by BrotherShort** [comment]
On the before editing version, vscroll max is total lines added a offset value from the partial line. 

>`v_scroll->set_max(total_rows + _get_visible_lines_offset());`
>`v_scroll->set_page(visible_rows + _get_visible_lines_offset());`

So when the vscroll scrolls down to the bottom, the top of the visible area exactly shows a full line, and the scroll value is a integer.

image

But the offset value brought a error. If the control height is less than one line, the whole visible area will be treated as offset.So you can see when you scroll down, the last text line will go outside of the top of the visible area. After you scroll down to the bottom, the visible line index is over flow, and the scroll oft is back to 0, so the last text line will show again. #104466

scroll



On my version, vscroll max is total lines. 

>`v_scroll->set_max(total_rows);`
>`v_scroll->set_page(visible_rows + 1 - _get_visible_lines_offset());`

Scrolling will stop after the last line is visible. 

scroll2

But at this moment, the top of the visible area don't show a full line, and the scroll value is not a integer.

image

The unit test is based on the before editing version. My version do not pass the unit test.

**Comment by BrotherShort** [comment]
CC @kitbdev

**Comment by lodetrick** [comment]
I think a cause of this is the slider's value being greater than or equal to the total_rows. When I modified the editor to uncap the slider's max value, the behavior of text popping in occurred continuously.

I wonder if it would be better to instead change line 8056: `if (scroll_past_end_of_file_enabled && !fit_content_height) {` to `if ((scroll_past_end_of_file_enabled && !fit_content_height) || visible_rows == 0) {`, because this issue happens when the visible_rows is zero, so the slider's page is set to the offset, allowing the slider's value to be exactly the total_rows (because it can be at most max - page), leading to the issue seen.

Including this change instead keeps the previous changes (from #14848), and also decreases the largest value that the slider can achieve by one (the if statement adds visible_rows - 1), which should prevent it from becoming greater than or equal to the total_rows.

**Comment by kitbdev** [comment]
That PR was from a long time ago and TextEdit changed a lot since. All the changes from that were because the scrolling system needed to be completely changed to support word wrapping and scrolling only part of a line.

The top of the visible area needs to shows exactly one full line for when `scroll_past_end_of_file_enabled` is true, which this PR currently breaks.
I think the same logic is used when it is false for consistency and so the first line can be whole, but this may not be needed. If we do make it so the top line doesn't need to be whole, it may be smoother when resizing vertically.
The test looks like it is making sure that disabling `scroll_past_end_of_file_enabled` doesn't change the actual scroll position. This behavior seems strange to me, but we can probably just change the test.

So we can either change the logic similar to what you have currently but only when `scroll_past_end_of_file_enabled` is false, or we can have a special case when there is less than 1 visible row, either way seems fine to me.

**Comment by BrotherShort** [comment]
> I wonder if it would be better to instead change line 8056: `if (scroll_past_end_of_file_enabled && !fit_content_height) {` to `if ((scroll_past_end_of_file_enabled && !fit_content_height) || visible_rows == 0) {`, because this issue happens when the visible_rows is zero, so the slider's page is set to the offset, allowing the slider's value to be exactly the total_rows (because it can be at most max - page), leading to the issue seen. This is not usually an issue because the visible rows would be at least one, meaning that the slider's value could never be equal to the total_rows.
I chose your solution which would not change scroll behavior. I added a test case.

File: tests/scene/test_text_edit.h [hunk 1]
```diff
@@ -7920,6 +7920,18 @@ TEST_CASE("[SceneTree][TextEdit] viewport") {
...
+	TextEdit *text_edit = memnew(TextEdit);
+	SceneTree::get_singleton()->get_root()->add_child(text_edit);
+
+	text_edit->set_size(Size2(800, 32));
+	text_edit->set_text("0\n1\n2");
+	MessageQueue::get_singleton()->flush();
+
+	text_edit->set_v_scroll(100);
+	CHECK(text_edit->get_v_scroll() < 3);
+}
```
Comment (kitbdev) [inline tests/scene/test_text_edit.h:7933]:
```suggestion
	memdelete(text_edit);
}
```

This needs to be deleted.

**Review by kitbdev — APPROVED** [review]
Code looks good and the issue with small heights is fixed.
The draw_amount changes also fixes an issue where the last line may be cut off when smooth scrolling is disabled.

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
