### PR TITLE
Use separate WorkThreadPool for shader compiler.

### LINKED ISSUE #102812: Crash when clicking Play in TPS demo on macOS
### Tested versions

- Reproducible in: 4.4.beta 1a0bf5467
- Not reproducible in: 4.3.stable, 4.4.beta3

### System information

Godot v4.4.beta (1a0bf5467) - macOS Sequoia (15.2.0) - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M4 Max (Apple9) - Apple M4 Max (16 threads)

### Issue description

I get a crash when clicking Play in TPS demo on macOS:

```
Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x19d6ee6ec __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x19d72c894 _pthread_cond_wait + 1204
2   libc++.1.dylib                	       0x19d662578 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   godot.macos.editor.arm64      	       0x10ae3a0d0 Semaphore::wait() const + 68 (semaphore.h:79) [inlined]
4   godot.macos.editor.arm64      	       0x10ae3a0d0 WorkerThreadPool::wait_for_group_task_completion(long long) + 272 (worker_thread_pool.cpp:694)
5   godot.macos.editor.arm64      	       0x103c0bafc RaycastOcclusionCull::RaycastHZBuffer::update_camera_rays(Transform3D const&, Vector3 const&, Vector2 const&, float, bool) + 4176 (raycast_occlusion_cull.cpp:104)
6   godot.macos.editor.arm64      	       0x103c14b70 RaycastOcclusionCull::buffer_update(RID, Transform3D const&, Projection const&, bool) + 808 (raycast_occlusion_cull.cpp:602)
7   godot.macos.editor.arm64      	       0x10936a6dc RendererSceneCull::render_camera(Ref<RenderSceneBuffers> const&, RID, RID, RID, Vector2, unsigned int, float, RID, Ref<XRInterface>&, RenderingMethod::RenderInfo*) + 3752 (renderer_scene_cull.cpp:2773)
8   godot.macos.editor.arm64      	       0x1093ae6d0 RendererViewport::_draw_3d(RendererViewport::Viewport*) + 688 (renderer_viewport.cpp:295)
9   godot.macos.editor.arm64      	       0x1093aede0 RendererViewport::_draw_viewport(RendererViewport::Viewport*) + 1492 (renderer_viewport.cpp:361)
10  godot.macos.editor.arm64      	       0x1093b60f8 RendererViewport::draw_viewports(bool) + 6064 (renderer_viewport.cpp:868)
11  godot.macos.editor.arm64      	       0x1095aff58 RenderingServerDefault::_draw(bool, double) + 424 (rendering_server_default.cpp:85)
12  godot.macos.editor.arm64      	       0x1095b4460 RenderingServerDefault::draw(bool, double) + 248 (rendering_server_default.cpp:415)
13  godot.macos.editor.arm64      	       0x10129a710 Main::iteration() + 1824 (main.cpp:4521)
14  godot.macos.editor.arm64      	       0x1011b7b9c OS_MacOS::run() + 252 (os_macos.mm:839)
15  godot.macos.editor.arm64      	       0x10121f5ec main + 568 (godot_main_macos.mm:84)
16  dyld  
```

Full report: [report.txt](https://github.com/user-attachments/files/18786611/report.txt)

I can reproduce this on `master` but not 4.4.beta3, even if I compile it myself. I couldn't manage to bisect this though (all commits crash).

Note that in 4.4.beta3, the demo will freeze at the end of the loading screen but it won't crash. 4.4.beta2 is the last one where the demo plays correctly.

This occurs with both Metal and Vulkan rendering drivers, in Forward+ and Mobile. This does not occur when using Compatibility.

### Steps to reproduce

- Run the TPS demo on macOS (with or without the editor in the background) and click **Play**.

### Minimal reproduction project (MRP)

https://github.com/godotengine/tps-demo

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/102812
Supersede https://github.com/godotengine/godot/pull/103299

Creates dedicated thread pool for `ShaderRD` compilation.

Not a perfect solution, but seems to be working pretty reliably (I was not able to get it crash or deadlock a single time).

### CODE REVIEW

File: core/object/worker_thread_pool.cpp [hunk 1]
```diff
@@ -832,10 +841,33 @@ void WorkerThreadPool::_bind_methods() {
...
+	WorkerThreadPool **pool_ptr = named_pools.getptr(p_name);
+	if (pool_ptr) {
+		return *pool_ptr;
+	} else {
+		WorkerThreadPool *pool = memnew(WorkerThreadPool(false));
+		pool->init();
+		named_pools[p_name] = pool;
+		return pool;
+	}
+}
```
Comment (stuartcarnie) [inline core/object/worker_thread_pool.cpp:854]: I would advocate for a separate API to create a named pool and have this API fail if the pool doesn't exist.

Comment (bruvzg) [reply core/object/worker_thread_pool.cpp:854]: If it was a public API and intended for generic use, I would agree. But it's only intended for a single case only, and in general should be avoided.

**Comment by DarioSamo** [comment]
I'm a fan of the concept of named pools, but does this implementation mean that it'll double up the available thread count from whatever the user configured? I've looked at the PR and didn't see if we have any logic to handle on how to respect that setting.

It's still an acceptable hotfix in my eyes as the workload for shader compilation doesn't come in that frequently.

**Review by DarioSamo — APPROVED** [review]
Overall I think this does the job considering this is a hotfix for a critical issue that has presented itself with 4.4, but I think we should consider extending WorkerThreadPool to work with a design where we're just allowed to create pools locally to the context of what we want to use. This is not entirely necessary for this PR given the nature of the issue at the moment.

For example, instead of a name, we'd just make the object inside ShaderRD's global context instead, which would make it a bit more natural and it could allow us to specify a thread count specifically for shader compilation easily.

**Comment by bruvzg** [comment]
> I'm a fan of the concept of named pools, but does this implementation mean that it'll double up the available thread count from whatever the user configured?

Yes, it is doubling the number of threads (we do not want to constantly spawn new threads, but simply having 2 threads per core should not cuase any problems).

**Comment by clayjohn** [comment]
I am a little bit unclear about the tradeoffs here. We are spawning a bunch of extra threads that will ultimately sit idle. Will they consume any resources once we finish compiling shaders? Are their any OS limitations we need to be wary of (especially on Mobile/Web)?

**Review by clayjohn — APPROVED** [review]
Thanks for answering my questions! I think this makes sense as a workaround for now. 

I am concerned that this named WTP system will get blindly expanded in the future into some sort of generic feature, but I think for now we should go forward with this PR

**Comment by bruvzg** [comment]
> I am concerned that this named WTP system will get blindly expanded in the future into some sort of generic feature, but I think for now we should go forward with this PR

That's the main reason I do not want to create a nice API for it, and implemented it as a single function. It won't prevent it from being used, but at least have more chances for a comment advising not to use it to be noticed.

**Comment by Repiteo** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.4.1.
