### PR TITLE
TileMap: _update_dirty_quadrants() cancel pending update pre return

### LINKED ISSUE #5076: Tilemap not showing tiles when tileset are added by code
**Operating system or device - Godot version:**
Windows 7 64bit
release version 2.0.2 or 2.1 alpha custom build

**Issue description** (what happened, and what was expected):
var ts = TileSet.new()
tilemap.set_tileset(ts)
only show tiles in Tilemap when he has a dummy tileset added by hand

**Steps to reproduce:**
1. create a scene (*.TSCN or *.SCN)
2. add a tilemap node
3. create tileset by gdscript and add it with set_tileset() to tilemap node

```
func _ready():
    var ts = TileSet.new()
    for i in range(10):
        ts.create_tile(i)
        ts.tile_set_texture(i,newTexture(imageSize))
        ts.tile_set_name(i,str(i))
    get_node("TileMap").set_tileset(ts)
    for i in range(10):
        for j in range(10):
            get_node("TileMap").set_cell(5+i,5+j,j,false,false,false)
    get_node("TileMap").set_cell_size(imageSize)
```
1. play scene
2. nothing is displayed
3. stop scene
4. click on tilemap node
5. chose Tile Set --> New TileSet
6. play scene
7. everything works
   bug_with_set_tileset

### PR DESCRIPTION
**Pull request by neikeq**
Fixes #5076

### CODE REVIEW

File: scene/2d/tile_map.cpp [hunk 1]
```diff
@@ -270,8 +270,10 @@ void TileMap::_update_dirty_quadrants() {
 		return;
 	if (!is_inside_tree())
 		return;
```
Comment (bojidar-bg) [inline scene/2d/tile_map.cpp]: Well, it is set to true by various other functions, which might _potentially_ run before `enter_tree` -- I guess it is better to be save than sorry, especially when it is just one if statement :smiley:

**Review by bojidar-bg — APPROVED** [review]
Looks good to me at least

File: scene/2d/tile_map.cpp (hunk 1 above)
Comment (neikeq) [inline scene/2d/tile_map.cpp]: Fine then
