### PR TITLE
Fix autocomplete persisting at the beginning of a line and throwing errors

### LINKED ISSUE #73341: Autocompletion popup remains when you backspace to the beginning of a line
### Godot version

4.0.rc2

### System information

Ubuntu 22.04.1 LTS

### Issue description

The autocomplete popup stays when you prompt it, then keep it while you backspace to the beginning of a line. Errors are also thrown.

### Steps to reproduce

1. Place your caret on an empty line
2. Type "r" and let autocompletion pop up
3. Backspace
4. Watch autocomplete persist even though you're on an empty line, and also some error spam in Output.

Backspacing on more empty lines causes more "Caret column exceeds line length." errors

### Minimal reproduction project

Any script

### PR DESCRIPTION
**Pull request by MewPurPur**
The index check is done incorrectly and errors out when the caret is in the 0th column. In fact, all of the logic below ensures that the caret isn't at column 0 when checking the previous char.

Fix #73341

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: scene/gui/code_edit.cpp [hunk 1]
```diff
@@ -2856,7 +2856,7 @@ void CodeEdit::_filter_code_completion_candidates_impl() {
 	const int caret_line = get_caret_line();
 	const int caret_column = get_caret_column();
 	const String line = get_line(caret_line);
-	ERR_FAIL_INDEX_MSG(caret_column - 1, line.length(), "Caret column exceeds line length.");
+	ERR_FAIL_INDEX_MSG(caret_column, line.length() + 1, "Caret column exceeds line length.");
```
Comment (akien-mga) [inline scene/gui/code_edit.cpp:2859]: Are you sure about the `line.length() + 1`? Won't this lead to out of bound access when on the last column?

Comment (MewPurPur) [reply scene/gui/code_edit.cpp:2859]: Yes, for example in a line with 3 chars, the caret's column can be 0 (before all chars), 1, 2, or 3 (after all chars)

**Comment by akien-mga** [comment]
Thanks!
