### PR TITLE
Fix particle not re-randomizing every emission

### LINKED ISSUE #102885: (4.4.beta3) GPUParticles3D spawn angle does not work when particle one_shot is true.
### Tested versions

- Reproducible in 4.4.beta3.
-  Not reproducible in 4.3.stable

### System information

Godot v4.4.beta3 - Windows 10 (build 19045) - Multi-window, 3 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 32.0.15.6636) - Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz (16 threads)

### Issue description

When one_shot is true in a GPUParticles3D node, spawn angle has no effect. If one_shot is false, spawn angle works correctly. 

### Steps to reproduce

-Add GPUParrticles3D node
-Add new particle process material
- Spawn -> angle -> min 0 to max 360
- (optional: set acceleration -> gravity to zero for clarity)
- Add quadmesh as draw pass 1 
- Add new standard material 3d to material slot in draw pass 1 quadmesh
- In material, Albedo -> texture -> icon.svg
- In material, Billboard -> mode -> Particle Billboard (also does not work with particle flags rotate y and disable z per documentation)
- Back at top, set lifetime to .05 and amount to 1
- test emitting with both one_shot enabled and disabled and you will see that no random rotation is applied if one_shot = true 
- (not reproducible in 4.3.stable)

### Minimal reproduction project (MRP)

[one_shot_mrp.zip](https://github.com/user-attachments/files/18809321/one_shot_mrp.zip)

### PR DESCRIPTION
**Pull request by QbieShay**
Fixes https://github.com/godotengine/godot/issues/102885

Supersedes https://github.com/godotengine/godot/pull/103008

And probably creates a million problems for me down the line 🥲

### CODE REVIEW

File: scene/2d/gpu_particles_2d.cpp [hunk 1]
```diff
@@ -41,6 +41,9 @@
 void GPUParticles2D::set_emitting(bool p_emitting) {
 	// Do not return even if `p_emitting == emitting` because `emitting` is just an approximation.
 
+	if (p_emitting && p_emitting != emitting && !use_fixed_seed) {
```
Comment (arkology) [inline scene/2d/gpu_particles_2d.cpp:44]:
```suggestion
	if (p_emitting && !emitting && !use_fixed_seed) {
```
Looks like it could be simplified, right? The same is valid below.

File: scene/2d/cpu_particles_2d.cpp [hunk 2]
```diff
@@ -45,10 +45,22 @@ void CPUParticles2D::set_emitting(bool p_emitting) {
...
+		_set_emitting();
+	}
+}
+
+void CPUParticles2D::_set_emitting() {
+	active = true;
+	set_process_internal(true);
+	// first update before rendering to avoid one frame delay after emitting starts
+	if (time == 0) {
+		_update_internal();
```
Comment (clayjohn) [inline scene/2d/cpu_particles_2d.cpp:63]: This logic is carried over from CPUParticles3D. It seems correct to me, so let's keep it

**Review by clayjohn — APPROVED** [review]
Looks good to me. We want to get this into RC1 which we are building momentarily, so let's merge as is

**Comment by akien-mga** [comment]
Thanks @QbieShay :heart:
