### PR TITLE
Not to be slow when select multiple files

### LINKED ISSUE #12576: Selecting multiple files in the FileSystem dock is slow the more files you select
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master https://github.com/godotengine/godot/commit/79f81b77e2160fd4fb490b9e8e05636de70174bf

**Issue description:**

Selecting multiple files in the FileSystem dock is slow the more files you select. And the file type also seems to be an issue.

Videos:
[*.gltf and *.material](https://streamable.com/ehgrv)
[*.png](https://streamable.com/tri4q)

I didn't try to select all the *.gltf and *.material because it basically freezes the editor.

**Steps to reproduce:**
1. Select multiple files in the filesystem dock
2. Stare at the screen

**Link to minimal example project:**

[test.zip](https://github.com/godotengine/godot/files/1436539/test.zip)
Tiles and models from https://kenney.nl/

### PR DESCRIPTION
**Pull request by volzhs**
when multiple files are selected, `_file_multi_selected()` is called by number of selected files.
and `_file_multi_selected()` calls `_file_selected()`.
so, import dock is eventually updated too many times.

Fixes #12576

### CODE REVIEW

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -1543,6 +1546,11 @@ void FileSystemDock::_file_multi_selected(int p_index, bool p_selected) {
 
 void FileSystemDock::_file_selected() {
 
+	file_selected = true;
+	set_process(true);
```
Comment (akien-mga) [inline editor/filesystem_dock.cpp]: It took me some time to understand why you're doing this, but I see now that it's to defer the `_update_import_dock` call so that it happens only once thanks to the bool. Still, it feels a bit hackish to use processing for that.

How about instead:
```cpp
void FileSystemDock::_file_multi_selected() {
    import_dock_needs_update = true;
    call_deferred("_update_import_dock");
}

void FileSystemDock::_file_selected() {
    import_dock_needs_update = true;
    _update_import_dock();
}

void FileSystemDock::_update_import_dock() {
    if (!import_dock_needs_update)
        return;
[...]
    import_dock_needs_update = false;
}
```

Though maybe it's still as hackish, I don't know :P

Comment (volzhs) [reply editor/filesystem_dock.cpp]: yeap. it's a bit hackish but couldn't find a better way without touching `ItemList`
I will try it in that way too.

Comment (volzhs) [reply editor/filesystem_dock.cpp]: @akien-mga your suggestion works as expected also, and I think it's better.
so I updated PR. :)

**Comment by akien-mga** [comment]
Sorry for the delay, there's no reason to hold this one.
