### PR TITLE
[C#] Fix building with `deprecated=no`

### LINKED ISSUE #84426: C# module compilation fail with `deprecated=no` compile flag
### Godot version

Master branch, 5ee983188de97ae027f9b9c1443438063f708a7e

### System information

Gentoo - Linux 6.1.57

### Issue description

Following this instructions, https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_with_dotnet.html#example-linux-bsd with the exception that I was testing with deprecated=no

The compilation fails with these errors:
```
Running MSBuild:  /usr/bin/dotnet msbuild /home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp.sln /restore /t:Build /p:Configuration=Debug /p:NoWarn=1591
MSBuild version 17.7.3+8ec440e68 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  Godot.SourceGenerators.Internal -> /home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/Godot.SourceGenerators.Internal/bin/Debug/netstandard2.0/Godot.SourceGenerators.Internal.dll
/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/Compat.cs(33,12): error CS0246: The type or namespace name 'AnimationMethodCallMode' could not be found (are you missing a using directive or an assembly reference?) [/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/Compat.cs(49,12): error CS0246: The type or namespace name 'AnimationProcessCallback' could not be found (are you missing a using directive or an assembly reference?) [/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/TextEdit.cs(746,34): warning CS0108: 'TextEdit.TextDirection' hides inherited member 'Control.TextDirection'. Use the new keyword if hiding was intended. [/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/Compat.cs(60,12): error CS0246: The type or namespace name 'AnimationProcessCallback' could not be found (are you missing a using directive or an assembly reference?) [/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/RichTextLabel.cs(399,34): warning CS0108: 'RichTextLabel.TextDirection' hides inherited member 'Control.TextDirection'. Use the new keyword if hiding was intended. [/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/ArrayMesh.cs(64,32): warning CS0108: 'ArrayMesh.BlendShapeMode' hides inherited member 'Mesh.BlendShapeMode'. Use the new keyword if hiding was intended. [/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/GltfAccessor.cs(280,18): warning CS0108: 'GltfAccessor.GetType()' hides inherited member 'object.GetType()'. Use the new keyword if hiding was intended. [/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/GltfAccessor.cs(569,43): warning CS0108: 'GltfAccessor.MethodName.GetType' hides inherited member 'object.GetType()'. Use the new keyword if hiding was intended. [/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Button.cs(170,34): warning CS0108: 'Button.TextDirection' hides inherited member 'Control.TextDirection'. Use the new keyword if hiding was intended. [/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Label.cs(244,34): warning CS0108: 'Label.TextDirection' hides inherited member 'Control.TextDirection'. Use the new keyword if hiding was intended. [/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/LineEdit.cs(608,34): warning CS0108: 'LineEdit.TextDirection' hides inherited member 'Control.TextDirection'. Use the new keyword if hiding was intended. [/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/LinkButton.cs(85,34): warning CS0108: 'LinkButton.TextDirection' hides inherited member 'Control.TextDirection'. Use the new keyword if hiding was intended. [/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/MenuBar.cs(77,34): warning CS0108: 'MenuBar.TextDirection' hides inherited member 'Control.TextDirection'. Use the new keyword if hiding was intended. [/home/leandrobg/Projects/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
```

### Steps to reproduce

Compile like this:

1. `scons  p=linuxbsd target=editor deprecated=no  module_mono_enabled=yes`
2. `bin/godot.li nuxbsd.editor.dev.x86_64.llvm.mono --headless --generate-mono-glue modules/mono/glue`
3. `./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --godot-platform=linuxbsd`

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Drako**
This fixes [GH-84426](https://github.com/godotengine/godot/issues/84426).

I added the option `--no-deprecated` to `build_assemblies.py`, which needs to be used, if the editor was built with `deprecated=no module_mono_enabled=yes`.

This conditionally disables code in `Compat.cs` which references deprecated classes or functions.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Makes sense to me. I'm not too familiar with C# buildsystem stuff though so I'll let @raulsntos double check.

**Comment by AThousandShips** [comment]
You used a merge commit to update your branch, please use rebase in the future instead, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

You will need to squash your commits before this can be merged (though that can wait until the team has reviewed), see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) 

But make sure not to use merge commits in the future

**Comment by Drako** [comment]
I don't see any merge commits ;)

File: modules/mono/glue/GodotSharp/GodotSharp/Compat.cs [hunk 1]
```diff
@@ -30,13 +30,15 @@ public double BlendNode(StringName name, AnimationNode node, double time, bool s
 
 partial class AnimationPlayer
 {
+#if !DISABLE_DEPRECATED
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Compat.cs:33]: We'd want to disable the entire `Compat.cs` file, since all of these APIs only exist for compatibility.

**Review by raulsntos — CHANGES_REQUESTED** [review]
Makes sense to me, but we'd want to disable the entire `Compat.cs` and also do the same in the `GodotSharpEditor` assembly.

**Comment by Drako** [comment]
Makes sense to me. I also considered excluding Compat.cs first, but wasn't sure, if there was stuff in it which is still needed.
Anyway I conditionally excluded both Compat.cs files now and it seems to be working so far.

**Review by raulsntos — APPROVED** [review]
Looks good to me, thanks!

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
