### PR TITLE
Fixing blinking particles at 0 initial velocity.

### LINKED ISSUE #10183: 3D particles blink when set a velocity of 0
Godot 3.0 alpha1
Windows 10 64 bits
nVidia geforce 940M

When I set a velocity of 0 for particles in the process material, particles spawn and disappear one frame after, though lifetime is set to 1 second.

### PR DESCRIPTION
**Pull request by H4kor**
Fixes #10183
Normalizing zero vectors caused undefined behavior.

### CODE REVIEW

File: scene/3d/particles.cpp [hunk 1]
```diff
@@ -753,18 +753,20 @@ void ParticlesMaterial::_update_shader() {
 		code += "    pos.z=0.0; \n";
 	}
 	code += "    //apply linear acceleration\n";
-	code += "    force+=normalize(VELOCITY) * (linear_accel+tex_linear_accel)*mix(1.0,rand_from_seed(alt_seed),linear_accel_random);\n";
+	code += "    force+= length(VELOCITY) > 0.0 ? normalize(VELOCITY) * (linear_accel+tex_linear_accel)*mix(1.0,rand_from_seed(alt_seed),linear_accel_random) : vec3(0);\n";
```
Comment (reduz) [inline scene/3d/particles.cpp]: should be vec(0.0) in GLES2, otherwise it might not compile in some platforms

**Review by reduz — DISMISSED** [review]
