### PR TITLE
Fix particle spread values affecting particle velocity

### LINKED ISSUE #85744: GPU particles 2D spread issue
### Godot version

4.2

### System information

Windows 11 Vulkan forward+

### Issue description

It seems to me that when spread is set to 180 and there is no random distribution set in any other parameters the particles should move towards random points on the edge of the circle with the same speed. But now it looks like particle distribution randomness is entangled with a speed so speed of the initial particle is also random. Also it seems that particle fail to form a circle at the end of the path.

### Steps to reproduce

1. Create GPUParticles2D node.
2. Set spread to 180.
3. Set initial texture.
4. Remove gravity.
5. Set initial speed to 75 (min and max).
6. Set damping to 35,
7. Set explosiveness to 1.
8. Set duration to 3.

Expected result:
All particles end their path at the edge of the circle.

Actual:
Particles distribute randomly in the area that is resembling rectangle with rounded edges.

### Minimal reproduction project

[GPUParticlesBug.zip](https://github.com/godotengine/godot/files/13545562/GPUParticlesBug.zip)

### PR DESCRIPTION
**Pull request by Rudolph-B**
Resolves #85744 and partially #85620

The spread direction vector for a particle had affected the particles velocity. This was caused by `spread_direction` not being normalized before it was returned from `get_random_direction_from_spread()`. A compounding issue to this was that `get_random_direction_from_spread()` still generated a 3D `spread_direction` even when `PARTICLE_FLAG_DISABLE_Z` is set.

I made changes to `get_random_direction_from_spread()` so that it:
- Uses a dedicated 2D spread calculation (used in the 4.1 release)
- Normalize the 3D `spread_direction` before returning it.

### CODE REVIEW

File: scene/resources/particle_process_material.cpp [hunk 1]
```diff
@@ -740,26 +740,33 @@ void ParticleProcessMaterial::_update_shader() {
...
+		code += "	// rotate spread to direction\n";
+		code += "	vec3 binormal = cross(vec3(0.0, 1.0, 0.0), direction_nrm);\n";
+		code += "	if (length(binormal) < 0.0001) {\n";
+		code += "		// direction is parallel to Y. Choose Z as the binormal.\n";
+		code += "		binormal = vec3(0.0, 0.0, 1.0);\n";
+		code += "	}\n";
+		code += "	binormal = normalize(binormal);\n";
+		code += "	vec3 normal = cross(binormal, direction_nrm);\n";
+		code += "	spread_direction = binormal * spread_direction.x + normal * spread_direction.y + direction_nrm * spread_direction.z;\n";
+		code += "	return normalize(spread_direction);\n";
```
Comment (clayjohn) [inline scene/resources/particle_process_material.cpp:768]: This line introduces a slight change in behaviour from 4.1 which didn't normalize the spread direction:
https://github.com/godotengine/godot/blob/2d3b2abcf6edcc9b02a9b1894ba43f79845ad2f4/scene/resources/particle_process_material.cpp#L491C9-L491C9

In your testing, did you notice any difference? Perhaps the normalize ends up being a no-op

**Comment by clayjohn** [comment]
Other than my comment, everything else looks good. The rest matches what we had in 4.1. So this PR should be good to go as long as we aren't introducing a behaviour change to 3D now

File: scene/resources/particle_process_material.cpp [hunk 2]
```diff
@@ -740,26 +740,33 @@ void ParticleProcessMaterial::_update_shader() {
...
-	code += "		// direction is parallel to Y. Choose Z as the binormal.\n";
-	code += "		binormal = vec3(0.0, 0.0, 1.0);\n";
-	code += "	}\n";
-	code += "	binormal = normalize(binormal);\n";
-	code += "	vec3 normal = cross(binormal, direction_nrm);\n";
-	code += "	spread_direction = binormal * spread_direction.x + normal * spread_direction.y + direction_nrm * spread_direction.z;\n";
-	code += "	return spread_direction;\n";
-
+	if (particle_flags[PARTICLE_FLAG_DISABLE_Z]) {
+		// spread calculation for 2D
```
Comment (AThousandShips) [inline scene/resources/particle_process_material.cpp:745]:
```suggestion
		// Spread calculation for 2D.
```
Per the [comment style](https://docs.godotengine.org/en/latest/contributing/development/code_style_guidelines.html#comment-style-guide).

File: scene/resources/particle_process_material.cpp [hunk 3]
```diff
@@ -740,26 +740,33 @@ void ParticleProcessMaterial::_update_shader() {
...
+		code += "	float angle1_rad = rand_from_seed_m1_p1(alt_seed) * spread_rad;\n";
+		code += "	angle1_rad += direction.x != 0.0 ? atan(direction.y, direction.x) : sign(direction.y) * (pi / 2.0);\n";
+		code += "	vec3 spread_direction = vec3(cos(angle1_rad), sin(angle1_rad), 0.0);\n";
+		code += "	return spread_direction;\n";
+	} else {
+		// spread calculation for 3D
```
Comment (AThousandShips) [inline scene/resources/particle_process_material.cpp:751]:
```suggestion
		// Spread calculation for 3D.
```

File: scene/resources/particle_process_material.cpp (hunk 1 above)
Comment (Rudolph-B) [reply scene/resources/particle_process_material.cpp:768]: I did. I setup a 3DGPUParticle with a spread of 180 and zero other variation with an initial velocity. This should just shoot out all particle in a sphere. The result without the normalize looks like this:
image
It definitely looks a bit oblong.

After adding the normalize:
image
Change is not super dramatic though.

File: scene/resources/particle_process_material.cpp (hunk 2 above)
Comment (Rudolph-B) [reply scene/resources/particle_process_material.cpp]: I did a force push with the update comments

File: scene/resources/particle_process_material.cpp (hunk 3 above)
Comment (Rudolph-B) [reply scene/resources/particle_process_material.cpp]: I did a force push with the update comments

**Comment by QbieShay** [comment]
Would superseed https://github.com/godotengine/godot/pull/86233

**Comment by YuriSizov** [comment]
@QbieShay Please help me out here. https://github.com/godotengine/godot/pull/84977 is superseded by https://github.com/godotengine/godot/pull/86233, and https://github.com/godotengine/godot/pull/86233 is superseded by this PR?

Should we close the other two?

**Comment by QbieShay** [comment]
Yep sorry. I have seen this PR only after opening my PR that supersedes the other one. I havent tested this one yet

**Comment by Rudolph-B** [comment]
@QbieShay Is there anything tests in particular that I can run that can help?

**Comment by georgwacker** [comment]
I tested this PR with my particle system from 4.1.2 and #85620 looks to be fixed.

Did you have a 2D test case where there are still issues compared to 4.1.x?

**Comment by Rudolph-B** [comment]
This is the original MRP for #85744 
[GPUParticlesBug.zip](https://github.com/godotengine/godot/files/14493672/GPUParticlesBug.zip)

File: scene/resources/particle_process_material.cpp (hunk 1 above)
Comment (clayjohn) [reply scene/resources/particle_process_material.cpp:768]: makes sense to normalize since this should be returning a direction

**Review by clayjohn — APPROVED** [review]
Let's merge this for 4.3! 

We should cherrypick this for 4.2 as well since the original bug was a regression in 4.2

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
