### PR TITLE
GDScript: Fix non-static call is allowed in static var lambda body

### LINKED ISSUE #83468: Opcode 88 when making a Dictionary with Callable values in GDScript
### Godot version

4.1.2

### System information

Linux Mint 21.3

### Issue description

I have a Dictionary of ints to Callables. When this dictionary has more than one entry, I consistently get the error "Internal Script Error! Opcode: 88 (please report)".

The associated error message is this:

```
E 0:00:01:0088   player.gd:9 @ @static_initializer(): Condition ' p_instance == nullptr ' is true. Breaking..:
  <C++ Source>   modules/gdscript/gdscript_vm.cpp:2452 @ call()
  <Stack Trace>  player.gd:9 @ @static_initializer()

```
The exact GDScript that seems to be causing the issue is this:

```
static var flavor_fire_def : Dictionary = {
	Gummy.Flavor.UNFLAVORED : (func():
		pass),
	Gummy.Flavor.ORANGE : func():
		var bullet = preload("res://bullet.tscn").instantiate()
		get_parent().add_child(bullet)
		bullet.linear_velocity = -$Mesh/BulletSource.global_transform.basis.z * 3.0
		bullet.global_position = $Mesh/BulletSource.global_position
}
```

Unless I'm making a syntactical error somewhere, my only workaround is going to be assigning functions directly.

### Steps to reproduce

The above code should theoretically be enough on my version, and perhaps OS.

### Minimal reproduction project

The above data should cover it, I've seen no evidence that another part of my project is involved.

### PR DESCRIPTION
**Pull request by dalexeev**
* Fixes #83468.

### CODE REVIEW

File: modules/gdscript/gdscript_parser.h [hunk 1]
```diff
@@ -918,6 +918,7 @@ class GDScriptParser {
 		Vector<IdentifierNode *> captures;
 		HashMap<StringName, int> captures_indices;
 		bool use_self = false;
+		bool is_in_static_context = false; // For analyzer. Just for don't modify `FunctionNode::is_static`.
```
Comment (dalexeev) [inline modules/gdscript/gdscript_parser.h:921]: I'm not sure about this, but `FunctionNode::is_static` is more of a parser flag that indicates whether there is `static` before `func`.

Comment (vnen) [reply modules/gdscript/gdscript_parser.h:921]: I don't think it would be a big deal to use the `FunctionNode::is_static` for this, as the lambdas cannot have the `static` keyword anyway, but it's probably clearer to have a dedicated flag for it.

**Review by vnen — APPROVED** [review]
LGTM

File: modules/gdscript/gdscript_parser.h (hunk 1 above)
Comment (akien-mga) [reply modules/gdscript/gdscript_parser.h:921]: There's a grammar issue in the comment, do you mean this?
```suggestion
		bool is_in_static_context = false; // For analyzer, to avoid modifying `FunctionNode::is_static`.
```

File: modules/gdscript/gdscript_analyzer.cpp [hunk 2]
```diff
@@ -1582,10 +1582,20 @@ void GDScriptAnalyzer::resolve_function_signature(GDScriptParser::FunctionNode *
...
+		}
+	}
+
 	GDScriptParser::FunctionNode *previous_function = parser->current_function;
 	parser->current_function = p_function;
 	bool previous_static_context = static_context;
 	static_context = p_function->is_static;
+	if (p_is_lambda && p_function->source_lambda) {
+		static_context = p_function->source_lambda->is_in_static_context;
+	}
```
Comment (dalexeev) [inline modules/gdscript/gdscript_analyzer.cpp:1598]: Just added this. A function parameter initializer can also contain a lambda.

File: modules/gdscript/gdscript_parser.h (hunk 1 above)
Comment (dalexeev) [reply modules/gdscript/gdscript_parser.h:921]: That's not exactly what I meant. This is for distinguish between `static func` syntax (which is not allowed for lambdas) and a flag that a lambda is in static context (so it cannot use non-static things).

```suggestion
		bool is_in_static_context = false; // Dedicated flag for lambdas, dont't confuse with `FunctionNode::is_static`.
```

I'm still not sure if we should differentiate this, maybe one flag is better. We can simply add a comment that the static flag of regular functions is determined by the explicit `static` keyword in the parser, and the static flag of lambdas is determined implicitly, from the context (you can't specify it explicitly).

**Comment by akien-mga** [comment]
Thanks!
