### PR TITLE
Fix Find in Files

### LINKED ISSUE #18303: "Find in files" is broken
**Godot version:**
df79cc8

**Issue description:**
When trying to search for something using "Find in files":
- If used on the res:// directory, it will find nothing,
- When used in a subdirectory of it, it will crash the editor, with this backtrace:
```
[1] /usr/lib/libc.so.6(+0x348e0) [0x7f123cf258e0] (??:0)
[2] FindInFiles::_scan_file(String) (??:0)
[3] FindInFiles::_iterate() (??:0)
[4] FindInFiles::_process() (??:0)
[5] FindInFiles::_notification(int) (??:0)
[6] FindInFiles::_notificationv(int, bool) (??:0)
[7] Object::notification(int, bool) (??:0)
[8] SceneTree::_notify_group_pause(StringName const&, int) (??:0)
[9] SceneTree::idle(float) (??:0)
[10] Main::iteration() (??:0)
[11] OS_X11::run() (??:0)
[12] /home/michael/git/godot/bin/godot.x11.tools.64(main+0xd5) [0x562929b1261f] (??:0)
[13] /usr/lib/libc.so.6(__libc_start_main+0xea) [0x7f123cf11f4a] (??:0)
[14] /home/michael/git/godot/bin/godot.x11.tools.64(_start+0x2a) [0x562929b1246a] (??:0)
```

### PR DESCRIPTION
**Pull request by Zylann**
- FileAccess was accessed null (remains of GDScript port)
- `_current_file` wasn't going up correctly in case a scanned directory had no subdirectories (race condition I didn't foresee when testing, ugh)
- Paths stored in `_files_to_scan` were not full paths

Fixes #18303

### CODE REVIEW

**Comment by YeldhamDev** [comment]
Could you also make so that the "Filter" option is disabled if using non-mono build?

**Comment by Zylann** [comment]
How do I do that? Also, is it really relevant since it just means there are no C# files anyways? (there could also be more formats to search in the future anyways)

**Comment by Zylann** [comment]
I have no idea how to detect if it's a mono build :|

**Comment by ShyRed** [comment]
The pull request is fine the way it is in my opinion.

The filter should be handled in a separate issue as this is a non-trivial new feature: the filter should not only support gd and cs, but also dynamically show all other languages that are added via plugins / modules. The filter would need to be exposed to the plugins so that they can register their extensions. Would then be the responsibility of C# to register its cs extension.

**Comment by Hinsbart** [comment]
@ShyRed this is already possible without exposing anything new, and also pretty trivial.
In pseudo-code:
```
for i in ScriptServer::get_language_count:
    lang = ScriptServer::get_language(i)
    filter.add(lang.get_extension())
```

File: editor/find_in_files.cpp [hunk 1]
```diff
@@ -150,19 +150,19 @@ void FindInFiles::_iterate() {
 			pop_back(folders_to_scan);
 
 			_current_dir = _current_dir.plus_file(folder_name);
+			//print_line(String("Scanning ") + _current_dir);
```
Comment (akien-mga) [inline editor/find_in_files.cpp]: I agree that such commented line should be removed. It's easy enough to add a print or a breakpoint when you do want the output, but leaving unused commented out debug code all over the place just makes things harder to read.

Comment (Zylann) [reply editor/find_in_files.cpp]: I removed them.

**Comment by akien-mga** [comment]
Actually not relevant in 3.0 since this feature was not included.
