### PR TITLE
Correct DST errors on Windows

### LINKED ISSUE #37571: OS.get_time_zone_info() does not adjust bias during DST
**Godot version:** 3.2

**OS/device including version:** Windows 10

**Issue description:** When calling OS.get_time_zone_info() during part of the year when DST is active, the bias field returned does not take daylight saving time into account, so for instance, Mountain Daylight Time reads as a bias of 420 (7 hours) instead of 360 (6 hours). A bias of 420 would be correct for the standard time part of the year, but is incorrect when DST is active.

**Steps to reproduce:** Call OS.get_time_zone_info(), print the result to console, and observe the incorrect bias.

**Minimal reproduction project:** Any project will do.

### LINKED ISSUE #59214: Windows does not report DST correctly in OS.get_datetime()
### Godot version

3.4.3.stable

### System information

Windows 11, Windows 10

### Issue description

When running OS.get_datetime() on Windows, it appears to always return false. We are currently in DST, but it returns "dst":false. This does not happen on MacOS. Due to the combined issue #37571, it makes RTC features very difficult.

### Steps to reproduce

This line appears to always have this error on windows in my testing.

### Minimal reproduction project

[DSTBroken.zip](https://github.com/godotengine/godot/files/8274787/DSTBroken.zip)

### PR DESCRIPTION
**Pull request by ztc0611**
The DST code on Windows for both was set to always return false in OS.get_datetime(), and reported the incorrect DST bias.

Fixes #59214 and Fixes #37571 for 4.0.

"Duplicate" due to me being confused as to how PRs work on multi-branch Github projects and submitting the other for 3.x.

### CODE REVIEW

File: platform/windows/os_windows.cpp [hunk 1]
```diff
@@ -295,16 +302,19 @@ OS::TimeZoneInfo OS_Windows::get_time_zone_info() const {
...
 	}
 
+	// Daylight Bias needs to be added to the bias if DST is in effect, or else it will not properly update.
 	TimeZoneInfo ret;
 	if (daylight) {
 		ret.name = info.DaylightName;
+		ret.bias = info.Bias+info.DaylightBias;
 	} else {
 		ret.name = info.StandardName;
+		ret.bias = info.Bias;
```
Comment (bruvzg) [inline platform/windows/os_windows.cpp:312]:
```suggestion
		ret.bias = info.Bias + info.StandardBias;
```

Should we add it as well? AFAIK, it's currently zero for all zones, but it might change.

File: platform/windows/os_windows.cpp [hunk 2]
```diff
@@ -295,16 +302,19 @@ OS::TimeZoneInfo OS_Windows::get_time_zone_info() const {
 		daylight = true;
 	}
 
+	// Daylight Bias needs to be added to the bias if DST is in effect, or else it will not properly update.
 	TimeZoneInfo ret;
 	if (daylight) {
 		ret.name = info.DaylightName;
+		ret.bias = info.Bias+info.DaylightBias;
```
Comment (bruvzg) [inline platform/windows/os_windows.cpp:309]:
```suggestion
		ret.bias = info.Bias + info.DaylightBias;
```

File: platform/windows/os_windows.cpp [hunk 3]
```diff
@@ -264,12 +264,19 @@ OS::Date OS_Windows::get_date(bool p_utc) const {
 		GetLocalTime(&systemtime);
 	}
 
+	//Get DST information from Windows.
+	TIME_ZONE_INFORMATION info;
+	bool daylight = false;
+	if (GetTimeZoneInformation(&info) == TIME_ZONE_ID_DAYLIGHT) {
+		daylight = true;
+	}
```
Comment (bruvzg) [inline platform/windows/os_windows.cpp:272]: Probably should not be done if `p_utc` is `true`.

Comment (ztc0611) [reply platform/windows/os_windows.cpp:272]: I believe that it it is impossible for this to incorrectly return it's daylight time in UTC? I may be incorrect though. [Documentation.](https://docs.microsoft.com/en-us/windows/win32/api/timezoneapi/nf-timezoneapi-gettimezoneinformation)

Comment (bruvzg) [reply platform/windows/os_windows.cpp:272]: That's if your time zone is UTC.

In this case, if `p_utc` parameter is `true`, it's gonna use UTC data from `GetSystemTime` and time zone info from your local timezone.

Comment (ztc0611) [reply platform/windows/os_windows.cpp:272]: Ohhhhh, my bad. Correcting this now.

File: platform/windows/os_windows.cpp (hunk 1 above)
Comment (ztc0611) [reply platform/windows/os_windows.cpp:312]: In my limited testing this doesn't seem to introduce any errors so sounds good.

File: platform/windows/os_windows.cpp [hunk 4]
```diff
@@ -264,12 +264,19 @@ OS::Date OS_Windows::get_date(bool p_utc) const {
 		GetLocalTime(&systemtime);
 	}
 
+	//Get DST information from Windows, but only if p_utc is false.
+	TIME_ZONE_INFORMATION info;
+	bool daylight = false;
+	if (p_utc == false && GetTimeZoneInformation(&info) == TIME_ZONE_ID_DAYLIGHT) {
```
Comment (bruvzg) [inline platform/windows/os_windows.cpp:270]:
```suggestion
	if (!p_utc && GetTimeZoneInformation(&info) == TIME_ZONE_ID_DAYLIGHT) {
```

**Review by bruvzg — APPROVED** [review]
You'll need to squash the commits into one (see https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html).

**Comment by ztc0611** [comment]
Alright, I'll read how to do that, one moment. Severe apologies for how bad I am at PRs, this is my first time trying to contribute to a project of this scale.

File: platform/windows/os_windows.cpp (hunk 1 above)
Comment (ztc0611) [reply platform/windows/os_windows.cpp]: Should this be done if `daylight` is true as well?

Comment (bruvzg) [reply platform/windows/os_windows.cpp]: No, `StandardBias` seems to be for non-DST only.

**Comment by ztc0611** [comment]
Gah, I clearly messed up the rebase somewhere. I didn't want it to automatically flag for review yet.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.4.
