### PR TITLE
Fix setting animation save paths on import breaking on Windows

### LINKED ISSUE #86279: Set Animation Save Paths fails on animations containing "|" characters
### Tested versions

Tested in 4.1.3, 4.2, 4.2.1
Seems to work fine in 4,1,3 but not in 4.2 or 4.2.1

### System information

Windows 10, Godot 4.2

### Issue description

I imported a few animations from blender (from mixamo) and godot doesn't let me change anything about them.
I know i'm supposed to enable save to file. i did that, but it doesn't seem to work. I tried restarting godot between every step because who knows, but still
I do have to restart it at least one in any version. After importing, i can't open a new inherited scene without a restart. Theres a red x as an icon in the filesystem window

I hope it's something simple that im doing wrong but i don't think so

### Steps to reproduce

Just import the 'zombie' glb, restart godot, open inherited scene, then open scene (still the glb one), go to the meshes tab, and on each mesh enable save to file

I believe that is what i'm supposed to do, right?
After doing all of that, i still can't even change the name of the animations in the animations tools from that bottom menu

### Minimal reproduction project (MRP)

In the file i already imported the glb and followed all the steps, but ill include the glb separately in case i'm doing something out of order or something. Maybe someone can figure that out

Nevermind? The zipped folder is 56mb. idk if im doing something wrong, but maybe 25mb is too small for something like this no?

I guess ill just include the animation glb

[Zombie.zip](https://github.com/godotengine/godot/files/13698344/Zombie.zip)

### PR DESCRIPTION
**Pull request by AlexOtsuka**
Fixes https://github.com/godotengine/godot/issues/86279.

Blender uses the | (pipe or vertical bar) character in its animation names which is forbidden in Windows file names. My fix simply replaces those with a _ (underscore) in the automatic path suggestion code when using the "Set Animation Save Paths" option.

There are other possible approaches to this, such as:

- Immediately renaming all the strings containing a | character on import => probably breaks compatibility with older projects
- Renaming ALL strings containing a | character when saving => probably breaks compatibility with older projects
- Making this change Windows only => would create discrepancies between different operating systems
- Using a different character => I'm open to suggestions

I chose to go for this as it seems like a safe, convenient fix with no obvious downsides.

### CODE REVIEW

File: editor/import/3d/scene_import_settings.cpp [hunk 1]
```diff
@@ -1448,7 +1448,8 @@ void SceneImportSettingsDialog::_save_dir_callback(const String &p_path) {
 					item->set_metadata(0, E.key);
 					item->set_editable(0, true);
 					item->set_checked(0, true);
-					String path = p_path.path_join(name);
+					// Replacing | (pipe) with _ (underscore) for compatibility with the Windows file system.
+					String path = p_path.path_join(name.replace("|", "_"));
```
Comment (lyuma) [inline editor/import/3d/scene_import_settings.cpp:1452]: I would consider using `String::validate_filename()` instead of specifically replacing `|` with `_`. Basically, there are many illegal filename characters and we should replace all of them.

the validate_filename will replace characters with _ so it should work the same for the case you did.

**Review by lyuma — APPROVED** [review]
Fixes an important bug on windows, so I'm approving this because 99% of the problem cases are covered by the change as written and I want to make sure it gets in.

Just a comment but should we check if material and mesh extraction has the same problem? perhaps we should validate_filename() in all cases

I think this problem stemmed because the Extract window doesn't offer a way to rename the extracted animations. I don't think people ever want their animations to be named "Armature|" or "Armature_" or "Take 001", but it's hard to edit from the extract dialog.

Anyway, improving the extraction flow would require an updated design, and it's important to get this bug fixed, so I think this is a good change.

File: editor/import/3d/scene_import_settings.cpp (hunk 1 above)
Comment (AlexOtsuka) [reply editor/import/3d/scene_import_settings.cpp:1452]: Thank you for your replies.

As far as I know, this only automatically happens in animation names in Blender, but I guess anyone could actually insert | in whatever they decide to name their material and meshes names.

I agree `String::validate_filename()` is better, I didn't know it existed and it's perfect for the use case. I guess I'll change that and wrap both the material and mesh names in the method as well.

A cool addition to this imo would be to display an error message or a pop-up whenever a user is trying to save their resources using invalid characters, as the previous error was a little cryptic. I don't know how much value there is in letting non-windows users use those characters in filenames either. What do you think would be the most appropriate solution?

For now, I'm gonna make the quick changes you mentioned and force-push them asap!

**Review by lyuma — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Comment by akien-mga** [comment]
Cherry-picked for 4.1.4.
