### PR TITLE
Fix blend animation to solve TRS track bug & blend order inconsistency

### LINKED ISSUE #34694: Add3's +add and -add act differently
the documentation isn't particularly detailed but I can't see any reason why +add and -add should act any differently for the same animation. I'm also not sure why it appears to act more like blend than add in this instance, shouldn't it move sideways and up/down with both -1 and 1?
tested on 3.1, 3.1.2 and master in linux X11

out

[test_anim2.zip](https://github.com/godotengine/godot/files/4008799/test_anim2.zip)

### LINKED ISSUE #46038: AnimationTree: Improper blending of bone location when blending more than two animations
**Godot version:**
Godot 3.2.4 rc1

**OS/device including version:**
Windows 10 version 1909

**Issue description:**

When blending more than two animations using two separate Animation Nodes (such as a Blend2 being consumed by another Blend2), the location of bones isn't properly interpolated if more than 2 animations are being blended together. 
This is most noticeable when transitioning from a Blend Amount less than 1 to exactly 1, which causes a noticeable "snapping", because values arbitrarily close to 1 have a noticeably different location.  It seems rotations are interpolated smoothly.
I've also tested this with a BlendSpace2D within a BlendSpace1D, and using transitions to have a similar effect.  Both have the same problem, where there's a jarring transition when reaching an animation.
However, here's a strange exception: if the blended node is put into the `in` slot of a Blend2 and the third animation the `blend` slot, it works fine.

[video of the problem](https://youtu.be/DfG5J60m7wU)

**Steps to reproduce:**

1. Create a model with three skeletal animations.  For two of them, translate one or more bones (make sure to not just rotate them).  
2. Import the model and animations and create an AnimationTree using the model's AnimationPlayer.  Set its root as an AnimationNodeBlendTree
3. Create a Blend2 of the translated animations. I also tested with a BlendSpace1D and BlendSpace2D.  Set the blend_amount between 0 and 1 (exclusive)
4. Create another Blend2.  Set the `in` slot to use the third, non-translated animation, and set `blend` to the translated animation blend.  
     - (Important info: if you swap the `in` and `blend` inputs, the problem goes away in this example.  This could be a useful workaround, unless you're blending between two blending nodes, which is my real use case, in which case the issue is present regardless of the input order).
7. Slowly move the blend_amount of this new node from 0 to 1
8. Watch as the animation snaps into place when going from 0.99 to 1

**Minimal reproduction project:**

[project.zip](https://github.com/godotengine/godot/files/5979454/project.zip)

Things to do in this project:
- Open the AnimationTree and slowly move the blend amount of `problem_blend` from 0 to 1.  The box will snap when going from 0.99 to 1 and back.
- Set the blend amount of `down` to 0 or 1 and repeat the previous step.  The problem disappears
- Swap the inputs of `in` and `blend` for `problem_blend` and repeat step 1.  The problem disappears

### LINKED ISSUE #54407: Animations not blending properly in AnimationTree. Vertical position of the skeleton is affected.
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0.dev

### System information

Windows 10 - 64 bit

### Issue description

The vertical position of a character seems to have some kind of offset when two different animations are blended together inside an Animation Tree. This is not exclusive to the Blend3 node.

ezgif-1-c62e8a3e6dc8

This behavior is not present in previous versions. I tested the same configuration using Godot 3.4 (beta 6). 
I imported the character model using the .glb file from the TPS Demo. The problem is present in custom characters too.

### Steps to reproduce

The following reproduction project showcases this behavior.

 - Open the "TPS Demo Robot Scene"

### Minimal reproduction project

[gODOT TEST.zip](https://github.com/godotengine/godot/files/7445608/gODOT.TEST.zip)

### LINKED ISSUE #55838: AnimationTree AnimationNodeBlendTree skeleton scaling issue with Blend2 and Blend3
### Godot version

4.0 dev

### System information

Win10, GLES3, RTX 2070 mobile

### Issue description

In 4.0 latest nightly dev build (as of 11 Dec) there is an issue with skeleton scaling when using Blend2 or Blend3 in a AnimationNodeBlendTree in AnimationTree. When blending between 2 animations the skeleton weirdly scales (looks like it's scaling down the root bone in between the blended animations). This issue was not present in Godot 3.4 stable. I used the same gltf import from Blender (skeleton with animations) in 4.0 as in 3.4.

See here: https://www.youtube.com/watch?v=WX0F99OoLQk

### Steps to reproduce

1. Import a gltf character with animations (I used one from Mixamo)
2. Create AnimationTree
3. Select NewAnimationBlendTree
4. Create 2 or 3 Animation nodes
5. Create a Blend2 or a Blend3 node
6. Connect the 2 or 3 animations into the Blend node and to the output
7. Link AnimationTree to AnimationPlayer that have the character animations (inside the imported gltf)
8. Activate the AnimationTree in editor
9. Scrub the Blend back and forth - you will see the skeleton scaling when blending; example here: https://www.youtube.com/watch?v=WX0F99OoLQk

### Minimal reproduction project

Don't have one, just follow the steps above.

### PR DESCRIPTION
**Pull request by TokageItLab**
Fix blending errors in TRS tracks and inconsistencies due to blending order (also fix the problem of triangle blending in Blend2D). This is a result of several discussions with @Shnazzy in #46038.

~With this change, if animation A has track X and animation B does not have track X, the internal value of track X in animation B in their blend will be the initial value that the type has. To avoid this, I have implemented the initial value to refer to the RESET track, if it exists. And for Bone3D, if there is no RESET track, it is implicitly based on bone_rest.~ RESET track is no longer used, just it use rest track as default value.

When using this initial value, blending with the initial value is required even when the blend value is 0, so I changed place the check from the blend process whether the blend value is 0 or not. Without it, the value isn't updated when the blend amount to be rapidly set to 0 or 1. This causes a temporary inconsistency in the blending results and after an unintentional abrupt change in the value occurs when the blend amount is changed.

This PR supersede #34134. Also, it solves the problem to a greater extent than #54205, but the changes are larger, so if you need to make minimal fix for TRS track, use #54205.

Fixed #46038. Fixed #54407. Fixed #55838. Fixed #34694.

### CODE REVIEW

**Comment by Shnazzy** [comment]
Looks good so far in the test projects I was using, but I'll keep testing other things to see if more complex stuff breaks anything.

**Comment by TokageItLab** [comment]
The only concern I have is Quaternion blending, and I have avoided the problem of slerp() with initial Quaternion by referring to the Reset track or bone_rest. In character models, it is almost rare to animate a joint more than 180 degrees, so this implementation is generally fine.

The problem may occur when the object is rotated more than 180 degrees, but I am not sure if blending should be used in such a case.

If we really need to solve the problem, we will need to interpolate using an accumulator, but we will need to experiment to ensure that the interpolation is consistent with slerp() in the normal case. Related: https://github.com/godotengine/godot/issues/40592#issuecomment-1022100826.

And perhaps it should be implemented as a selectable option. This is because we want the bones of the character model to have a behavior that prevents them from rotating more than 180 degrees, but for other objects we want them to rotate in the shortest path without preventing it.

**Comment by Shnazzy** [comment]
It also probably would make sense to animate the rotation according to what rotation mode the object is using.  Like a propeller on a helicopter model might want to animate from -180 to +180, and in such cases, it would be easier to describe that with Eulers than Quaternions, just by my guess at least.

**Comment by TokageItLab** [comment]
There are animations that rotate more than 180 degrees, but I can't think of many use cases for blending them. I think propeller rotation should be controlled by scripts rather than animations, and for cases like turrets that always face the character, I think IK should be used instead of blend trees.

One example that comes to mind is the animation of a robot that rotates its face 180 degrees to express its emotions. In any case, I think the current broken blends need to be fixed as soon as possible, as I think that fix/enhancement can be done later.

**Comment by Shnazzy** [comment]
I agree.  I have no issues with the current proposed changes as I'm not a rotation calculation expert by any means.

**Comment by fire** [comment]
What results did slerpni() give?

**Comment by TokageItLab** [comment]
By using RESETTrack and bone_rest as initial values instead of Quaternion(0,0,0;1), slerpni() produces unstable results.
Even when the initial value is Quaternion(0,0,0;1), it might have generated unstable results somewhere, but maybe it just didn't show up in my test case in past.

**Comment by TokageItLab** [comment]
After more experimentation, I concluded that the results from slerp() are difficult to predict because they are sparse depending on the direction of the axis. For now, I adopt the accumulator that @Shnazzy suggested. This will ensure that the rotation is done consistently and in the shortest distance.

**Comment by TokageItLab** [comment]
Sorry, I take back my previous statement, the reason why slerp()'s limit was unpredictable was because an RESET track was unintentionally inserted. And the my theory seems to be correct.

> Perhaps in the current slerp() produces the consistent result is that only blends that cross 180 degrees (e.g. between Y:179 and Y:-179 in Euler) from the initial value, go back through the initial value, but I want more test cases.

Also, the accumulator probably does the same thing as slerpni(), which could create unintended rotations.

I'm going to finalize using slerp() as a tentative solution.

**Comment by Shnazzy** [comment]
On the subject of blending quaternions to work with 3 or more weighted values, I've found a couple different suggestions.  I'm not a linear algebra major so I can only understand a very small portion of why this works, but I'll link them here:

https://stackoverflow.com/questions/12374087/average-of-multiple-quaternions
https://math.stackexchange.com/questions/61146/averaging-quaternions/3435296
http://www.acsu.buffalo.edu/~johnc/ave_quat07.pdf
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.16.5040&rep=rep1&type=pdf

**Comment by TokageItLab** [comment]
I did an experiment on Exponential Map just yesterday (https://github.com/godotengine/godot/issues/57951#issuecomment-1036844786). I didn't get very good results on cubic interpolation due to the prediction of pre and post value, but I predict weighted blending will work well.

File: scene/animation/animation_tree.cpp [hunk 1]
```diff
@@ -540,6 +540,11 @@ bool AnimationTree::_update_caches(AnimationPlayer *player) {
 	List<StringName> sname;
 	player->get_animation_list(&sname);
 
+	Ref<Animation> reset_anim;
+	bool has_reset_anim = player->has_animation("RESET");
```
Comment (reduz) [inline scene/animation/animation_tree.cpp:544]: Reset is not ensured to exist and even if it does, the rest poses are not ensured to exist either, so I am not sure this is a good solution.

**Comment by reduz** [comment]
My feeling is that the right solution to multiple rotation blendings is that we will need to have, per track, something like this:

```C++
enum {
  MAX_BLENDS=8
}
struct RotationBlend {
      Quaternion rotation;
      float contribution;
};
RotationBlend blends[MAX_BLENDS];
uint32_t blend_count;
```

And just add the blends one after another. If more than MAX_BLENDS, then just find the one with the minimum contribution and see if greater and replace it.

Afterwards, do as described [here](https://web.archive.org/web/20200707210941/http://wiki.unity3d.com/index.php/Averaging_Quaternions_and_Vectors).

File: scene/animation/animation_tree.cpp (hunk 1 above)
Comment (TokageItLab) [reply scene/animation/animation_tree.cpp:544]: @reduz If we don't have ResetPose or RestPose, we will have the problem of going through Quaternion(0,0,0;1) only for rotation, but on the other hand, if we have ResetPose, we can blend without penetrating the body, as in the video above, so this feature may not need to be the default, but it needs to be there somewhere.

**Comment by TokageItLab** [comment]
@reduz We've been experimenting with @fire for the past few weeks to see if we should use Exponential Map, since direct addition of Quaternion elements is not really slerp. Ref: #57951.

**Comment by TokageItLab** [comment]
Memo - I and @lyuma discussion log from Rocket Chat:

- `pose_override` should be local
- In `set_bone_pose_override()`, implement the `amount` to lerp as an argument (the amount will be used temporally for lerp, not be stored)
- `pose_override` does not have to be an array. Blending should be done externally in IK, PhysicalBone, etc. and only the final result should be stored in `pose_override`
- replace `set_bone_pose_override_enabled()` with `clear_bone_pose_override()`
- rename `get_bone_pose_no_override()` to `get_bone_pose_base()`
- rename `get_bone_pose()` to `get_bone_pose_overridden()` 

cc: @reduz

**Comment by TokageItLab** [comment]
I understand now that the problem with slerp from Initial Quaternion is that the Quaternion used to determine if the Quaternion should be flipped is the Initial Quaternion. So I think the right way to implement this is to use the current Quaternion to determine the flip (but not the blend). I'll experiment later.

**Comment by TokageItLab** [comment]
I experimented with exp map. The results show that blending with Exp map works, but it does not seem to be relevant to the shortest path problem. Moreover, in the triangular blend, the results were not that different from slerp.

In order to get the shortest path, we need to use a reference quaternion and invert the positive and negative of another quaternion. The current implementation of this PR uses the value of RESET or REST, or if they are not present, the value of Quaternion(0,0,0;1).

To make the flip reference the current pose, we could use the final result Quaternion of the previous frame, but that did not seem pretty for the character model. Since the blending result changes depending on the playback position of the animation.

https://user-images.githubusercontent.com/61938263/156890242-68d3deee-7ede-47ce-897b-2610a9ca70ab.mov

Another possible approach is to use the first value of the blend as the reference value, but this is not acceptable because it would cause inconsistencies in the blend order.

After experimentation, I tentatively implemented this PR to get the shortest path based on RESET or REST.

File: scene/animation/animation_tree.h [hunk 2]
```diff
@@ -197,9 +197,13 @@ class AnimationTree : public Node {
 		bool loc_used = false;
 		bool rot_used = false;
 		bool scale_used = false;
+		Vector3 init_loc = Vector3();
+		Quaternion init_rot = Quaternion();
+		Quaternion init_rot_accum = Quaternion();
```
Comment (TokageItLab) [inline scene/animation/animation_tree.h:202]: I wondered if `Quaternion init_rot_accum` was necessary as a member, but since `init_rot.log()` calculation is required for this every time at line 1164 of animation_tree.cpp, I defined it to reduce the calculation cost.

**Comment by TokageItLab** [comment]
More optimized by removing unnecessary calculations during the blending process.

**Comment by TokageItLab** [comment]
Fixed `exp()` to explicitly return `Quaternion(0, 0, 0, 1)` instead of `Quaternion()` when theta is very small.

**Comment by reduz** [comment]
I would suggest getting rid of references to RESET animation since this is not really warranted to exist (and is pretty hacky) and just use the bone rest. From there it may look like this could work for merging.

This will also make the PR simpler so you can only really bother about rotation tracks (what really matters) and do not change anything else.

**Comment by TokageItLab** [comment]
@reduz Fixed, the implementation for the RESET track has been removed. For TRS tracks, rest should be used as default value: init_loc/init_rot/init_scl, because unneeded tracks will be deleted by the optimizer or not exported from the source.

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
Fantastic job! Apologies for the delay in the reviews as this code is not that simple and the past weeks were super busy for me.

**Comment by akien-mga** [comment]
Thanks!

**Comment by macryc** [comment]
At last. Is this merge going into alpha 5? Assuming so, when's alpha 5 due out?

**Comment by macryc** [comment]
This did not fix the root bone rotation and scaling problem (when using animation blend tree). The y position of the root bone seems to be fixed but the root bone still scales up and down when blending animations via a blend node.

**Comment by lyuma** [comment]
@macryc would it be possible for you to provide a reproduction case / demo project possibly as a separate bug so it can be tracked more easily.

Take note that Godot's skeleton bone visualization is extremely confusing because rather than drawing bones, they draw lines connecting each bone to its parent, so the "scale" and rotation of each joint will appear to change as they move, especially noticeable on root motion bones.
