### PR TITLE
Oculus requires apps with line when head tracking

### LINKED ISSUE #30854: Exported oculus quest games treated as go games
**Godot version:**

e4ec59b6ae7ba4da8a57d35a4763192fd84fa358

**OS/device including version:**

 Arch Linux

**Issue description:**

Exported android game is missing extra android feature line in the manifest needed for the oculus quest to give the game 6dof tracking on the controllers: https://www.reddit.com/r/OculusQuest/comments/chjpu5/fix_for_sideloadedhomebrew_apps_and_games_with/

**Steps to reproduce:**
1. Follow steps on the [oculus mobile github](https://github.com/GodotVR/godot_oculus_mobile) to export for oculus quest
2. Modify the demo to include controllers with a simple meshinstance as children for visualization
3. Controller tracking does not work due to the missing line in the manifest. 

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by creikey**
Exporting the option in Godot's settings is unnecessary as in the option the head tracking feature is marked not required for use. 
Fixes #30854

### CODE REVIEW

**Comment by m4gr3d** [comment]
@creikey The [Android documentation](https://developers.google.com/vr/develop/android/3dof-to-6dof) states that the tag **must** be omitted if the app doesn't support 6dof at all, so we should make it optional to not affect Godot regular android games.

**Comment by creikey** [comment]
With the latest WIP commit, it seems to be exporting correctly, and `apktool d` then inspecting the manifest file shows a correct file, however, upon uploading the APK  to a device, it complains about the binary being invalid without saying why. I'm looking into it right now.

**Comment by creikey** [comment]
All of the bugs seem to be worked out now

File: platform/android/export/export.cpp [hunk 1]
```diff
@@ -847,6 +847,135 @@ class EditorExportPlatformAndroid : public EditorExportPlatform {
 					uint32_t name = decode_uint32(&p_manifest[iofs + 12]);
 					String tname = string_table[name];
 
+					int dof_index = p_preset->get("graphics/degrees_of_freedom"); // 0: none, 1: 3dof and 6dof, 2: 6dof
+
+					if (tname == "uses-feature" && dof_index > 0) {
```
Comment (m4gr3d) [inline platform/android/export/export.cpp]: This should also check if 'Oculus Mobile VR' is selected as Xr mode, since that tag is only valid for Oculus devices at the moment.

File: platform/android/export/export.cpp [hunk 2]
```diff
@@ -847,6 +847,135 @@ class EditorExportPlatformAndroid : public EditorExportPlatform {
...
+						ofs += 24; // skip over end tag
```
Comment (m4gr3d) [inline platform/android/export/export.cpp]: Can the logic be extended similar to what's done with the permissions, so that we can have a list of `uses-features` tag that would be iterated through and added as specified by the user.

Comment (creikey) [reply platform/android/export/export.cpp]: I'm not exactly sure how this could be done as the 6dof option and the 3dof plus 6dof option are mutually exclusive.

File: platform/android/export/export.cpp (hunk 1 above)
Comment (creikey) [reply platform/android/export/export.cpp]: Rather than silently not adding the tag if it's not an oculus mobile device, I was hoping that in the godot_oculus_mobile docs it'd just specify to have the dropdown selected to the 6dof option if targeting the oculus quest.

Comment (m4gr3d) [reply platform/android/export/export.cpp]: One of the most important UX learning is that typical users never read the documentation, and so, if a feature has the potential to have a negative impact, then that feature should be placed behind a check to ensure that the feature is not accidentally enabled by the user.

This applies here as well since based on the [Google docs](https://developers.google.com/vr/develop/android/3dof-to-6dof) the tag **must** not be included for apps with no 6DoF features.

As you mentioned, we'll include a description of the dropdown's purpose in the docs, but a check is also needed in case the user doesn't read the doc or forget about it.

File: platform/android/export/export.cpp (hunk 2 above)
Comment (m4gr3d) [reply platform/android/export/export.cpp]: I was referring to other features besides 3dof/6dof that also necessitate the insertion of the `uses-features` tag.
For example, the [ARCore PR](https://github.com/godotengine/godot/pull/26221/files#diff-b39419f9be37c6f37a62e693300244d1R19) needs to include the `android.hardware.camera.ar` `uses-features` tag.

Feel free to punt on this though since it won't be needed until that PR is ready to be reviewed, at which time, we can expand on the current insertion logic.

File: platform/android/export/export.cpp (hunk 1 above)
Comment (creikey) [reply platform/android/export/export.cpp]: I've added a check then a warning print if the user forgets to set the xr mode.

File: platform/android/export/export.cpp (hunk 2 above)
Comment (creikey) [reply platform/android/export/export.cpp]: I'm working on this feature now.

Comment (creikey) [reply platform/android/export/export.cpp]: Given that to add a general purpose features list would require changing some engine code that I cannot find currently where the Tree is constructed with checkboxes for features to allow setting android version and GL version etc, and the manifest line for the oculus quest is highly customized, this should be punted until that is done in a separate PR. As of right now, oculus quest support along with non 6dof oculus devices like the oculus go is completely broken without this modification, so it should be merged now.

Comment (m4gr3d) [reply platform/android/export/export.cpp]: Sounds good to me. Once you squashed the commits, it should be good to go.
Great work by the way!

**Comment by m4gr3d** [comment]
@akien-mga The PR is ready for merging (once the commits are squashed), unless you have additional feedback.

**Comment by m4gr3d** [comment]
cc @BastiaanOlij

**Comment by BastiaanOlij** [comment]
Looks good to me!

**Comment by creikey** [comment]
I've squashed the commits in the latest force push.

**Comment by akien-mga** [comment]
Thanks!
