### PR TITLE
Fix chain assignment bug with jump_if_shared

### LINKED ISSUE #62484: Assigning a value to specified vector component does not working
### Godot version

5ab59ee7df1d344dccc9deef375faa46deb63b8d

### System information

Windows 11

### Issue description

The following code does not assign a correct position to `MeshInstance` node:

```
extends Node3D

@onready var mi = $MeshInstance3D

func _ready():
	var v = Vector3(1, 2, 3)
	mi.position.x = v.x
	mi.position.y = v.y
	mi.position.z = v.z
	print(mi.position)
```

It's printing (0, 0, 0) while it should be (1, 2, 3).
Seems like a recent regression.

### Steps to reproduce

^^

### Minimal reproduction project

[VectorComponentBug.zip](https://github.com/godotengine/godot/files/9000575/VectorComponentBug.zip)

### PR DESCRIPTION
**Pull request by cdemirer**
Fixes #62484

Fixes a regression from #62462 and adds a test case.

### CODE REVIEW

File: modules/gdscript/gdscript_compiler.cpp [hunk 1]
```diff
@@ -1059,22 +1059,22 @@ GDScriptCodeGenerator::Address GDScriptCompiler::_parse_expression(CodeGen &code
...
 						} else {
 							gen->write_set_named(info.base, info.name, assigned);
 						}
+						if (!known_type) {
+							gen->write_end_jump_if_shared();
+						}
 					}
-					if (!known_type) {
-						gen->write_end_jump_if_shared();
+					if (key.mode == GDScriptCodeGenerator::Address::TEMPORARY) {
```
Comment (vnen) [inline modules/gdscript/gdscript_compiler.cpp:1076]: I guess this does need to be moved out of the `if`, but it needs to be checked if it's not named (if it is, then it doesn't have `key`) and it's the `info.key` since standalone`key` is something else.

```suggestion
					if (!info.is_named && info.key.mode == GDScriptCodeGenerator::Address::TEMPORARY) {
```

**Review by vnen — CHANGES_REQUESTED** [review]

**Review by vnen — APPROVED** [review]
Looks good to me now.
