### PR TITLE
Fix gizmos without visible geometry not being selectable

### LINKED ISSUE #68935: gizmo.add_collision_triangles() & gizmo.add_collision_segments() Only Work When add_mesh() Is Called
### Godot version

v4.0.beta4.official [e6751549c]

### System information

Windows 10

### Issue description

I noticed that `add_collision_triangles()` and/or `add_collision_segments()` only work if `add_mesh()` is used in the same `_redraw(gizmo):` function. I don't want to render a mesh, so I guess I could make the material not render at all, but I would still like to have a selectable collider for the gizmo.

### Steps to reproduce

Download the plugin, enable it, and place a `Test Node` into a 3D scene. The `gizmo.add_mesh()` function is located in the `test_gizmo_plguin.gd` script. If you comment it out, the gizmo's collider mesh is no longer selectable in the scene view.

### Minimal reproduction project

[gizmo_selection_issue.zip](https://github.com/godotengine/godot/files/10050794/gizmo_selection_issue.zip)

### PR DESCRIPTION
**Pull request by juanjp600**
Fixes godotengine/godot#68935.

The issue was that Node3DEditorViewport was using the render server's BVH to filter out nodes, which is not correct for gizmos that have no renderable components, or have collision triangles that exceed the bounds of their renderable components.

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected.

I made a complete MRP from #68935 for easier testing: [gizmo_selection_issue.zip](https://github.com/user-attachments/files/16323095/gizmo_selection_issue.zip)

**Review by AThousandShips — APPROVED** [review]

File: editor/plugins/node_3d_editor_gizmos.cpp [hunk 1]
```diff
@@ -244,6 +246,32 @@ void EditorNode3DGizmo::add_mesh(const Ref<Mesh> &p_mesh, const Ref<Material> &p
...
 }
 
+void EditorNode3DGizmo::_update_bvh() {
+	ERR_FAIL_NULL(spatial_node);
+
+	Transform3D transform = spatial_node->get_global_transform();
+
+	float effective_icon_size = selectable_icon_size > 0.0f ? selectable_icon_size : 0.0f;
+	Vector3 icon_size_vector3 = Vector3(effective_icon_size, effective_icon_size, effective_icon_size);
+	AABB aabb(spatial_node->get_position() - icon_size_vector3, icon_size_vector3);
```
Comment (juanjp600) [inline editor/plugins/node_3d_editor_gizmos.cpp:256]: Bounding box doesn't match the one defined [here](https://github.com/godotengine/godot/blame/e25f3c0d38d457b15a63720240736f564ce0501b/editor/plugins/node_3d_editor_gizmos.cpp#L348), will fix

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.
