### PR TITLE
`PinJoint2D`: fix inertia tensor, taking center of mass into account

### LINKED ISSUE #58802: pinjoint2d staticbody to rigidbody2d behaving strangely
### Godot version

4.0 dev alpha 3

### System information

mac book pro 2019 15" current os

### Issue description

enabling collisions on my rigid body, even though it does not collide with my staticbody in any way, causes the rigidbody to fly off into oblivion, ultimately reporting NaN,NaN as its location.

### Steps to reproduce

run the included project.  works 'fine' when collisions aren't enabled on the rigidbody.  does not work when collision is enabled.

tried removing all the layers from the collisions, this had no beneficial effect.

### Minimal reproduction project

Screen Shot 2022-03-05 at 2 20 40 PM

[pin.zip](https://github.com/godotengine/godot/files/8191417/pin.zip)

### PR DESCRIPTION
**Pull request by rburing**
The same inertia tensor calculation is actually repeated in the `k_tensor` function in the same file, used by the `GrooveJoint2D`. In that function, the center of mass of each body was already taken into account:

https://github.com/godotengine/godot/blob/d3f983262fbc272c66c20d03f82b6dc658e37f4b/servers/physics_2d/godot_joints_2d.cpp#L239-L240

This PR takes the center of mass into account in the inertia tensor calculation for `PinJoint2D` in exactly the same way.

Fixes https://github.com/godotengine/godot/issues/58802.

The two calculations of the inertia tensor could be refactored into one function in the future.

### CODE REVIEW

**Comment by Calinou** [comment]
It might be worth checking whether this issue occurs in 3D as well (with GodotPhysics).

**Comment by rburing** [comment]
> It might be worth checking whether this issue occurs in 3D as well (with GodotPhysics).

It's probably not an issue there:

https://github.com/godotengine/godot/blob/d3f983262fbc272c66c20d03f82b6dc658e37f4b/servers/physics_3d/joints/godot_pin_joint_3d.cpp#L71-L72

File: servers/physics_2d/godot_joints_2d.cpp [hunk 1]
```diff
@@ -118,22 +118,25 @@ bool GodotPinJoint2D::setup(real_t p_step) {
 	K1[0].y = 0.0f;
 	K1[1].y = A->get_inv_mass() + B_inv_mass;
 
+	Vector2 r1 = rA - A->get_center_of_mass();
+	Vector2 r2 = B ? rB - B->get_center_of_mass() : rB;
```
Comment (akien-mga) [inline servers/physics_2d/godot_joints_2d.cpp:122]: This seems used only in `if (B)`, so maybe it can move there and the ternary check can be removed.

Comment (rburing) [reply servers/physics_2d/godot_joints_2d.cpp]: Indeed, thanks.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.
