### PR TITLE
Warn and return when attempting to load invalid MP3s

### LINKED ISSUE #45995: Executing `AudioStreamMP3.new().set_data(PoolByteArray([]))` crashes Godot
**Godot version:**
Godot 3.2.4 rc 2

**Issue description:**
Executing
```
AudioStreamMP3.new().set_data(PoolByteArray([]))
```

crashes with backtrace
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7efe56278210] (??:0)
[2] /lib/x86_64-linux-gnu/libc.so.6(cfree+0x20) [0x7efe562cf870] (??:0)
[3] /usr/bin/godot(mp3dec_ex_close+0x66) [0x1c5ccc1] (/mnt/Miecz/godot3.2/thirdparty/minimp3/minimp3_ex.h:1390)
[4] AudioStreamMP3::set_data(PoolVector<unsigned char> const&) (/mnt/Miecz/godot3.2/modules/minimp3/audio_stream_mp3.cpp:170)
[5] MethodBind1<PoolVector<unsigned char> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/./core/method_bind.gen.inc:775 (discriminator 12))
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/core/object.cpp:919 (discriminator 1))
[7] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/mnt/Miecz/godot3.2/core/variant_call.cpp:1129 (discriminator 1))
[8] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript_function.cpp:1089)
[9] GDScriptInstance::_ml_call_reversed(GDScript*, StringName const&, Variant const**, int) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript.cpp:1269)
[10] GDScriptInstance::call_multilevel_reversed(StringName const&, Variant const**, int) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript.cpp:1278)
[11] Node::_notification(int) (/mnt/Miecz/godot3.2/scene/main/node.cpp:152)
[12] Node::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/main/node.h:46 (discriminator 14))
[13] CanvasItem::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/2d/canvas_item.h:166 (discriminator 3))
[14] Node2D::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/2d/node_2d.h:38 (discriminator 3))
[15] Object::notification(int, bool) (/mnt/Miecz/godot3.2/core/object.cpp:931)
[16] Node::_propagate_ready() (/mnt/Miecz/godot3.2/scene/main/node.cpp:197)
[17] Node::_propagate_ready() (/mnt/Miecz/godot3.2/scene/main/node.cpp:186 (discriminator 2))
[18] Node::_set_tree(SceneTree*) (/mnt/Miecz/godot3.2/scene/main/node.cpp:2560)
[19] SceneTree::init() (/mnt/Miecz/godot3.2/scene/main/scene_tree.cpp:464)
[20] OS_X11::run() (/mnt/Miecz/godot3.2/platform/x11/os_x11.cpp:3628)
[21] /usr/bin/godot(main+0x125) [0x16d2e6b] (/mnt/Miecz/godot3.2/platform/x11/godot_x11.cpp:57)
[22] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7efe562590b3] (??:0)
[23] /usr/bin/godot(_start+0x2e) [0x16d2c8e] (??:?)
```
Address Sanitizer shows
```
==55932==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x7f6ec93610e0 in thread T0
    #0 0x7f6ec8a2d1b7 in __interceptor_free (/lib/x86_64-linux-gnu/libasan.so.6+0xb01b7)
    #1 0x34d6537 in mp3dec_ex_close thirdparty/minimp3/minimp3_ex.h:1386
    #2 0x34dcf8e in AudioStreamMP3::set_data(PoolVector<unsigned char> const&) modules/minimp3/audio_stream_mp3.cpp:168
    #3 0x34f9ae4 in MethodBind1<PoolVector<unsigned char> const&>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:775
    #4 0x1130e5d9 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:919
    #5 0x1158f5b5 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1129
    #6 0x1d4c957 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1086
    #7 0x1b7d3f9 in GDScriptInstance::_ml_call_reversed(GDScript*, StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1269
    #8 0x1b7d6ac in GDScriptInstance::call_multilevel_reversed(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1276
    #9 0xbeee184 in Node::_notification(int) scene/main/node.cpp:149
    #10 0x1a29b69 in Node::_notificationv(int, bool) scene/main/node.h:46
    #11 0x1a2bfde in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #12 0xd9bcc2a in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:38
    #13 0x1130ea73 in Object::notification(int, bool) core/object.cpp:929
    #14 0xbef0101 in Node::_propagate_ready() scene/main/node.cpp:196
    #15 0xbeef967 in Node::_propagate_ready() scene/main/node.cpp:188
    #16 0xbf3c6f8 in Node::_set_tree(SceneTree*) scene/main/node.cpp:2557
    #17 0xbfff620 in SceneTree::init() scene/main/scene_tree.cpp:463
    #18 0x178042f in OS_X11::run() platform/x11/os_x11.cpp:3621
    #19 0x16ee466 in main platform/x11/godot_x11.cpp:56
    #20 0x7f6ec77370b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #21 0x16ee07d in _start (/usr/bin/godots+0x16ee07d)

Address 0x7f6ec93610e0 is a wild pointer.
```

### PR DESCRIPTION
**Pull request by ellenhp**
Fixes #45995

This also adds a warning for unspecified MP3 loading error codes, even though no action is taken. Looking at the code for mp3dec_ex_open_buf, It's not clear how other error codes should be handled, so I've elected to preserve previous behavior but warn to assist with debugging if developers have issues.

To test, run the following in a node's `_ready` method or something like that:

```
var stream = AudioStreamMP3.new()
stream.data = []
```

### CODE REVIEW

File: modules/minimp3/audio_stream_mp3.cpp [hunk 1]
```diff
@@ -159,7 +159,13 @@ void AudioStreamMP3::set_data(const Vector<uint8_t> &p_data) {
 	const uint8_t *src_datar = p_data.ptr();
 
 	mp3dec_ex_t mp3d;
-	mp3dec_ex_open_buf(&mp3d, src_datar, src_data_len, MP3D_SEEK_TO_SAMPLE);
+	int err = mp3dec_ex_open_buf(&mp3d, src_datar, src_data_len, MP3D_SEEK_TO_SAMPLE);
+	if (err == MP3D_E_PARAM) {
+		WARN_PRINT("mp3dec_ex_open_buf returned error code MP3D_E_PARAM");
+		return;
```
Comment (akien-mga) [inline modules/minimp3/audio_stream_mp3.cpp:165]: This should be an error and not a warning IMO, as it effectively aborts the operation.
So that would typically be:
```
ERR_FAIL_COND(err == MP3D_E_PARAM);
```

which will generate an error like:
```
set_data: Condition "err == MP3D_E_PARAM" is true. Breaking.
At:   modules/minimp3/audio_stream_mp3.cpp:163.
```

Or `ERR_FAIL_COND_MSG` if you want to give a custom message, but IMO unless we explain what `MP3D_E_PARAM` means, the default message is good enough (lets you know where to put a breakpoint if you want to debug what's wrong).

Comment (akien-mga) [reply modules/minimp3/audio_stream_mp3.cpp:165]: I'd make it error out on all minimp3 errors though, looking at the list they all seem critical apart from `MP3D_E_USER`, but that one has specifically handling to *not* error out in `mp3dec_ex_open_buf`:
```
/* return error codes */
#define MP3D_E_PARAM   -1
#define MP3D_E_MEMORY  -2
#define MP3D_E_IOERROR -3
#define MP3D_E_USER    -4  /* can be used to stop processing from callbacks without indicating specific error */
#define MP3D_E_DECODE  -5  /* decode error which can't be safely skipped, such as sample rate, layer and channels change */
```

**Comment by akien-mga** [comment]
While this is a good addition to sanitize mp3 input, the actual fix for #45995 should be further up: passing an empty array as data should not attempt to then decode this data at all. It should either throw an error (`ERR_FAIL_COND()`), or if we think this is a valid use case, it should clear the data and reset things to an empty stream (`clear_data()` I guess, maybe more member variables that need resetting?).

**Comment by ellenhp** [comment]
My tendency would generally be to let the mp3 library decide what's a valid mp3 and what isn't instead of special-casing the empty array, because it's possible that there are other invalid MP3s users may want to provide. Nothing against special-casing the empty array but I think that this free-before-allocation should probably be caught either way. I'll make the rest of the changes though and hopefully it'll look a bit less like a hack after that. Thanks for the tip about `ERR_FAIL_COND`. New to godot and all :)

**Comment by ellenhp** [comment]
Hopefully this is better. Rather than check each individual error code I just fail when `err != 0`. Let me know if you think I should handle empty arrays in a nicer way than this.

**Comment by akien-mga** [comment]
The current change is good (we should handle the error that minimp3 gives us), but I still think that we could also add an earlier check to prevent even passing an empty buffer to the thirdparty library.

How to decide to make a special case here? IMO the main principle is usability. Godot is a high level game engine and many of its users will use MP3 without having any notions of the underlying library used, and won't necessarily know what to make of an error that refers to a decoding failure in some thirdparty code. Is it a corrupt MP3? Is it a bug in the library?

In this case, passing an empty array to a property exposed by Godot is something which is fairly easy to do and which might even happen by mistake (pass a variable which happens to be empty even if you intended it to hold actual MP3 data). Rule of thumb is, if the user can shoot themselves in the foot relatively easily, then it might be worth making a special case to prevent them from doing so.

All that being said, I check what is currently done for other stream formats:
- No check for OGG, so it will fail with `ERROR: set_data: Condition "ogg_stream == __null" is true.` here: https://github.com/godotengine/godot/blob/f14008b600ff091a07d9dcb53780e9374f36d47f/modules/stb_vorbis/audio_stream_ogg_vorbis.cpp#L190
- There's a check for WAV, but no error, it handles an empty array as a way to clear pre-existing data: https://github.com/godotengine/godot/blob/f14008b600ff091a07d9dcb53780e9374f36d47f/scene/resources/audio_stream_sample.cpp#L489

So all in all that's material for another issue/PR to make sure that we use the same kind of rationale for all formats (and possibly compare with image loaders to see how they handle empty buffers).

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
