### PR TITLE
Camera2D: Update scrolls when the Viewport is resized

### LINKED ISSUE #46826: Camera2D does not stay centered when resizing the window and smoothing is false.
**Godot version:**
Godot 3.2.4 RC4

**OS/device including version:**
Win10

**Issue description:**
When a Camera2D is not set to smoothing and the window is resized the Camera2D does not stay centered. In RC3 and before the camera stayed centered, and while smoothing is enabled the camera stays centered.

**Steps to reproduce:**
Have a Camera2D in the scene, see minimal project.

**Minimal reproduction project:**
Run the game and resize the window, the Godot logo should stay in the center, but it does not. If you enable smoothing the logo will stay centered as intended.
[camera_bug_test.zip](https://github.com/godotengine/godot/files/6109324/camera_bug_test.zip)

### PR DESCRIPTION
**Pull request by akien-mga**
Factored the `viewport`/`custom_viewport` setup code which was used in two
locations to ensure consistency.

Fixes #46826.

### CODE REVIEW

File: scene/2d/camera_2d.cpp [hunk 1]
```diff
@@ -75,6 +75,22 @@ void Camera2D::_update_process_mode() {
...
+		viewport = get_viewport();
+	}
+
+	RID vp = viewport->get_viewport_rid();
+	group_name = "__cameras_" + itos(vp.get_id());
+	canvas_group_name = "__cameras_c" + itos(canvas.get_id());
+	add_to_group(group_name);
+	add_to_group(canvas_group_name);
+
+	viewport->connect("size_changed", this, "_update_scroll");
```
Comment (akien-mga) [inline scene/2d/camera_2d.cpp:91]: Note that this will call `_update_scroll()` on viewport resize, regardless of whether we have smoothing enabled or not (and with smoothing on the update will also be done by processing). But I assumed it's not a big deal for this situation.

Comment (lawnjelly) [reply scene/2d/camera_2d.cpp:91]: I think it should be fine even if called twice in this situation. :+1:

**Review by lawnjelly — APPROVED** [review]
Looks good to me (haven't tested though).

Only bit I'd double check is whether it is possible by setting a custom viewport to leave it connected to 2 viewports, and leak one (but I'm not really familiar with signals etc).

**Comment by akien-mga** [comment]
> Only bit I'd double check is whether it is possible by setting a custom viewport to leave it connected to 2 viewports, and leak one (but I'm not really familiar with signals etc).

You're right, I need to disconnect the signal when setting a custom viewport if there was a valid viewport before.

**Comment by akien-mga** [comment]
Did some further testing today with the [2D platformer](https://github.com/godotengine/godot-demo-projects/tree/master/2d/platformer), everything seems to behave as expected.

I found an issue when toggling smoothing from the remote inspector while running the game, but it's not caused by this issue and seems to be a more general sync issue between editor and runtime.
