### PR TITLE
Make `NinePatchRect` listen to texture changes

### LINKED ISSUE #78210: Nine patch rect doesn't update when texture atlas region is updated
### Godot version

v4.1.beta1.mono.official [828ec2c5d]

### System information

Kubuntu 22.04 Compatability

### Issue description

As funky as it sounds I tried using a atlas texture as the texture for a nice patch and discovered that the nine patch is not updated in the scene when the atlas texture region is changed 

### Steps to reproduce

- Add a altas texture to the nice patch node
- Mess with the atlas texture's region property (not the nice slices region property)
- See it doesn't update in the scene

### Minimal reproduction project

I will upload one if needed as it stand it seems like a very simple thing to reproduce

### PR DESCRIPTION
**Pull request by AThousandShips**
Tried to look but can't see any other cases of textures not being connected when they are singular (not counting things like the icons in `TabBar` which I'm not sure what to do with) 

* Fixes #78210

### CODE REVIEW

File: scene/gui/nine_patch_rect.cpp [hunk 1]
```diff
@@ -89,11 +90,27 @@ void NinePatchRect::_bind_methods() {
 	BIND_ENUM_CONSTANT(AXIS_STRETCH_MODE_TILE_FIT);
 }
 
+void NinePatchRect::_texture_changed() {
+	queue_redraw();
+	update_minimum_size();
+	emit_signal(SceneStringNames::get_singleton()->texture_changed);
```
Comment (AThousandShips) [inline scene/gui/nine_patch_rect.cpp:96]: Wasn't sure if this should be called each time, but the documentation says "when the texture changes" so included it

**Review by akien-mga — APPROVED** [review]

File: scene/gui/nine_patch_rect.cpp (hunk 1 above)
Comment (KoBeWi) [reply scene/gui/nine_patch_rect.cpp:96]: I think it's more expected that the signal gets emitted only when the texture property changes to a different texture. The description just isn't very precise.

Although I wonder why this signal even exists. Other control nodes don't have anything like that.

Comment (AThousandShips) [reply scene/gui/nine_patch_rect.cpp:96]: Will update tomorrow if desired

Comment (AThousandShips) [reply scene/gui/nine_patch_rect.cpp]: Done!

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!
