### PR TITLE
Fix drawing of slot icons in `GraphNode` when slots are not continuous

### LINKED ISSUE #107298: `GraphNode` `set_slot_custom_icon_` function uses the order on which ports were enabled instead of the slot index.
### Tested versions

Reproducible in:
- v4.3.stable.official [77dcf97d8]
- v4.4.1.stable.official [49a5bc7b6]
- v4.5.dev5.official [64b09905c]

### System information

Godot v4.4.1.stable - Windows 10 (build 19045) - Multi-window, 3 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce GTX 750 Ti (NVIDIA; 32.0.15.7247) - Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 threads)

### Issue description

Using the function `GraphNode.set_slot_custom_icon_right` (and left too) will act differently depending on what order the port was enabled at.
So if the slot index 0 was enabled thrid, to change its icon I'll have to call `GraphNode.set_slot_custom_icon_right(2, icon)` instead of the correct `GraphNode.set_slot_custom_icon_right(0, icon)`

https://github.com/user-attachments/assets/cfc9551d-c669-4494-94e0-59ba761e59e0

### Steps to reproduce

1. Create a GraphNode with 2 or more children
2. Enable only the second left/right port of the slot 1 (and up)
3. Change the icon of slot index 0 via code
4. Icon of slot index 1 (or whichever you enabled first) changes instead.

This behaviour is similar if you create the objects via code. If the third children (slot index 2) you added is the first one to have the right slot enabled, to change the icon you'll have to use 0 instead of it's actual port index of 2

### Minimal reproduction project (MRP)

[bug_testing_4-4.zip](https://github.com/user-attachments/files/20648428/bug_testing_4-4.zip)

### PR DESCRIPTION
**Pull request by detomon**
Fixes: #107298

### CODE REVIEW

File: scene/gui/graph_node.cpp [hunk 1]
```diff
@@ -673,28 +673,25 @@ void GraphNode::_notification(int p_what) {
...
+							Rect2 child_rect = child->get_rect();
+							child_rect.position.x = sb_panel->get_margin(SIDE_LEFT);
+							child_rect.size.width = width;
+							draw_style_box(sb_slot, child_rect);
 						}
-						Rect2 child_rect = child->get_rect();
-						child_rect.position.x = sb_panel->get_margin(SIDE_LEFT);
-						child_rect.size.width = width;
-						draw_style_box(sb_slot, child_rect);
 					}
```
Comment (detomon) [inline scene/gui/graph_node.cpp:694]: I rearranged this part to remove the `continue`, which may lead to code being skipped below this block by accident (if something is added below in the future).

**Review by kleonc — APPROVED** [review]
LGTM, fixes the issue.

**Comment by akien-mga** [comment]
Thanks!
