### PR TITLE
Editor Feature Profile: Only rebuild selected TreeItem and all children when a property is edited

### LINKED ISSUE #92132: Editor Feature Profiles: Selection of CheckBox in Tree does not remember folding
### Tested versions

Godot v4.3.beta (daa81bbb7)

### System information

Godot v4.3.beta (daa81bbb7) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 6900 XT (Advanced Micro Devices, Inc.; 31.0.24033.1003) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Checkout the Video:

https://github.com/godotengine/godot/assets/66004280/0b6f4ef2-b4b0-4958-9e82-71b4b97f8c16

This makes working with the dialog not so easy.

### Steps to reproduce

1. Editor -> Manage Editor Feature Profiles
2. Collapse some Options
3. Select another `CheckBox`
4. Verify that the whole `Tree` seems to rebuild, without remembering the folding state

### Minimal reproduction project (MRP)

Not needed

### PR DESCRIPTION
**Pull request by Maran23**
Fixes: https://github.com/godotengine/godot/issues/92132

Before, the whole `Tree` was rebuild when a property was changed. 
This is not just a bad idea for performance reasons, but also does not retain any folds that were previously done by the user on any other `TreeItem`.

This PR improves that by only rebuilding the selected class `TreeItem` and all children, which improves the performance but also retain any folds that were previously done to other `TreeItem`s.

For that, we now always call `_update_profile_tree_from` when something was edited instead of `_update_selected_profile`, which does a full rebuild.

https://github.com/godotengine/godot/assets/66004280/2523a2a5-185f-45e1-85fb-7e707f701ec9

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: editor/editor_feature_profile.h [hunk 1]
```diff
@@ -147,7 +147,8 @@ class EditorFeatureProfileManager : public AcceptDialog {
 	String current_profile;
 	void _update_profile_list(const String &p_select_profile = String());
 	void _update_selected_profile();
-	void _fill_classes_from(TreeItem *p_parent, const String &p_class, const String &p_selected);
+	void _update_profile_tree_from(TreeItem *p_edited);
+	void _fill_classes_from(TreeItem *p_parent, const String &p_class, const String &p_selected, const int p_class_insert_index = -1);
```
Comment (AThousandShips) [inline editor/editor_feature_profile.h:151]:
```suggestion
	void _fill_classes_from(TreeItem *p_parent, const String &p_class, const String &p_selected, int p_class_insert_index = -1);
```
No `const` for simple types

File: editor/editor_feature_profile.cpp [hunk 2]
```diff
@@ -497,8 +497,8 @@ void EditorFeatureProfileManager::_hide_requested() {
 	_cancel_pressed(); // From AcceptDialog.
 }
 
-void EditorFeatureProfileManager::_fill_classes_from(TreeItem *p_parent, const String &p_class, const String &p_selected) {
-	TreeItem *class_item = class_list->create_item(p_parent);
+void EditorFeatureProfileManager::_fill_classes_from(TreeItem *p_parent, const String &p_class, const String &p_selected, const int p_class_insert_index) {
```
Comment (AThousandShips) [inline editor/editor_feature_profile.cpp:500]:
```suggestion
void EditorFeatureProfileManager::_fill_classes_from(TreeItem *p_parent, const String &p_class, const String &p_selected, int p_class_insert_index) {
```

Comment (Maran23) [reply editor/editor_feature_profile.cpp]: done.

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
