### PR TITLE
Fix load subtask not being registered leading to false progress values.

### LINKED ISSUE #90076: ResourceLoader.load_threaded_get_status always returns [0] progress
### Tested versions

- Reproducible in: 4.2.2rc2, 4.3.dev5
- Not reproducible in: 4.2.1.stable

### System information

Godot v4.2.2.rc2 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Ti (NVIDIA; 31.0.15.5186) - 13th Gen Intel(R) Core(TM) i7-13700K (24 Threads)

### Issue description

The same problem as here https://github.com/godotengine/godot/issues/56882, which returned after https://github.com/godotengine/godot/pull/87711, I guess.
ResourceLoader.load_threaded_get_status always return progress with [0] and returns [1] at the end.

**4.2.1**

https://github.com/godotengine/godot/assets/1756388/536ec4ea-b7e9-4345-b5c1-87757354f8cf

4.2.1 also has a bug, that after 49% it drops to 41%

**4.2.2 and 4.3.dev**

https://github.com/godotengine/godot/assets/1756388/4e1ab051-1a30-46c8-92ac-4644c90646e6

### Steps to reproduce

1) Load packed scene with ResourceLoader.load_threaded_request
2) Try to get progress with ResourceLoader.load_threaded_get_status
3) Progress always [0]

### Minimal reproduction project (MRP)

[resource-loader-bug.zip](https://github.com/godotengine/godot/files/14817027/resource-loader-bug.zip)

1) Extract project
2) Copy `Bistro_v5_2` to the project (https://developer.nvidia.com/orca/amazon-lumberyard-bistro)
3) Press load

### PR DESCRIPTION
**Pull request by ajreckof**
Fixes #90076 

I'm clearly not 100% sure about my solution but it works. See https://github.com/godotengine/godot/issues/90076#issuecomment-2029203547 and the previous comment for a bit more depth on why this is working

### CODE REVIEW

**Comment by AlexOtsuka** [comment]
Hey, I just tested this, and as far as I can tell, it solves all the issues from https://github.com/godotengine/godot/issues/90076 while maintaining the improvements from https://github.com/godotengine/godot/pull/87711 in elegant fashion.

For added context, here are a few outputs from my testing:

**Case 1:**

```
core\io\resource_loader.cpp:251 - p_path: res://Bistro_v5_2/BistroExterior.fbx
core\io\resource_loader.cpp:252 - p_original_path: 
core\io\resource_loader.cpp:253 - original_path: res://Bistro_v5_2/BistroExterior.fbx
core\io\resource_loader.cpp:254 - parent_task_path: res://scene.tscn
core\io\resource_loader.cpp:259 - INSERTED
```

In the regression, an empty `String` been inserted in the `sub_tasks` HashSet. Here, `original_path` is set to the correct value and the sub task's progress is tracked properly.

**Case 2:**

```
core\io\resource_loader.cpp:251 - p_path: res://.godot/imported/BistroExterior.fbx-2cc48855b7169211933e362848048fa2.scn
core\io\resource_loader.cpp:252 - p_original_path: res://Bistro_v5_2/BistroExterior.fbx
core\io\resource_loader.cpp:253 - original_path: res://Bistro_v5_2/BistroExterior.fbx
core\io\resource_loader.cpp:254 - parent_task_path: res://Bistro_v5_2/BistroExterior.fbx
core\io\resource_loader.cpp:262 - NOT INSERTED
```

This is the scenario https://github.com/godotengine/godot/pull/87711 was meant to fix in the first place. We correctly choose `p_original_path` over `p_path`, but inserting it in `sub_tasks` would result in a stack overflow crash later on due to it sharing its local path with its parent task path. This new PR correctly checks for this and skips it as needed.

**Case 3** would be similar to **Case 2**, but with `original_path != parent_task_path`. I can't test it now, but this is supposedly what happens in the exported build and it looks to me like that should go through with no issues as well.

Thank you for your contribution and great work!!

File: core/io/resource_loader.cpp [hunk 1]
```diff
@@ -242,16 +242,18 @@ ResourceLoader::LoadToken::~LoadToken() {
 }
 
 Ref<Resource> ResourceLoader::_load(const String &p_path, const String &p_original_path, const String &p_type_hint, ResourceFormatLoader::CacheMode p_cache_mode, Error *r_error, bool p_use_sub_threads, float *r_progress) {
+	String original_path = p_original_path.is_empty() ? p_path : p_original_path;
```
Comment (RandomShaper) [inline core/io/resource_loader.cpp:245]:
```suggestion
	const String &original_path = p_original_path.is_empty() ? p_path : p_original_path;
```

File: core/io/resource_loader.cpp [hunk 2]
```diff
@@ -242,16 +242,18 @@ ResourceLoader::LoadToken::~LoadToken() {
...
 	load_nesting++;
 	if (load_paths_stack->size()) {
 		thread_load_mutex.lock();
-		HashMap<String, ThreadLoadTask>::Iterator E = thread_load_tasks.find(load_paths_stack->get(load_paths_stack->size() - 1));
-		if (E) {
-			E->value.sub_tasks.insert(p_original_path);
+		String parent_task_path = load_paths_stack->get(load_paths_stack->size() - 1);
```
Comment (RandomShaper) [inline core/io/resource_loader.cpp:249]:
```suggestion
		const String &parent_task_path = load_paths_stack->get(load_paths_stack->size() - 1);
```

File: core/io/resource_loader.cpp [hunk 3]
```diff
@@ -242,16 +242,18 @@ ResourceLoader::LoadToken::~LoadToken() {
...
+		HashMap<String, ThreadLoadTask>::Iterator E = thread_load_tasks.find(parent_task_path);
+		if (E && original_path != parent_task_path) {
```
Comment (RandomShaper) [inline core/io/resource_loader.cpp:251]: Regarding this comparison, I think it helps because it avoids registering both a resource and its imported counterpart as subtasks, when the former is known to be almost an empty shell. Do you think that's the case? I'm asking because it would be a good idea to add a comment explaining that or, much preferred, make the code explicitly check for that somehow (notwithstanding adding a comment anyway).

**Review by RandomShaper — CHANGES_REQUESTED** [review]
Asking a few changes. Besides that, the changes make a lot of sense.

File: core/io/resource_loader.cpp (hunk 3 above)
Comment (ajreckof) [reply core/io/resource_loader.cpp:251]: Yes this is the idea. I can add a comment for that. For the part of checking for that directly I'm not sure how to do that.

File: core/io/resource_loader.cpp (hunk 1 above)
Comment (RandomShaper) [reply core/io/resource_loader.cpp:245]: I just realized I may be a good idea to reason about this change request. As you may already know, `String` is backed by a copy-on-write container, with a reference counter. This counter is updated atomically, which may or may not be bad for performance depending on how hot the code path is, CPU architecture, etc. In any case, my motto here is, "Why taking the risk?". If you know you just want to keep the temporary string alive, a const reference would do that without involving a copy, which would deal with the refcount.

**Review by RandomShaper — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
