### PR TITLE
Clamp Gradient and Curve Textures in ParticlesMaterial

### LINKED ISSUE #60032: Vulkan: Particle ramp textures are set to repeat, causing visual artifacts when they restart
This is my first issue report ever so I hope everything is correct.
English is not my mother tongue so please understand..

Godot 4 Alpha 6

Issue description:
So there are a few Bugs with the GPUParticles2D.
**I recommend to look in the project because it's very hard to descripe the bugs.**

1. If you use a colored gradient with transparent at the end, then the particles at the end of their lifetime are suddenly displayed again in the color that is at the beginning of the gradient
2. At the start the particles have the last Color from the gradient. This happens when you have a high amount of particles.
3. If the FPS are set to 30 in the particles and you change the amount, there are a lot of visual glitches happening

Here is the 3. issue in my project: https://twitter.com/proj_Aetheria/status/1512212234952491014

I created an example object with all the things + A video.
[Project.zip](https://github.com/godotengine/godot-docs/files/8453343/Project.zip)

I also have a small improvement suggestion for the gradient handling.
If you drag the slider in the gradient, for example, from the far left to the far right with the mouse and you want to undo it, then you have to press ctrl+z 1000 times because it tracks every color on the way. Maybe the retraction point should be where you started with the mouse?

Edit:

I thought of 2 new things that I had the last few days

1. When I first add the Color Gradient to the Particle - Nothing happend. Reload the Scene fixed it. This happens everytime when I create a new Particle with Gradient
2. I'm using an Animated Texture in the "texture" property. Sometimes in the Editor the animation doesn't work. When I run the game everything is ok. This only happens sometimes in the Editor. Fix -> Restart Godot

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/60032

This PR disables repeat on LUTs in ParticlesMaterial so that the values do not wrap around. In 3.x repeat was disabled by default as it was a property of the texture itself.

### CODE REVIEW

File: scene/resources/particles_material.cpp [hunk 1]
```diff
@@ -233,48 +233,48 @@ void ParticlesMaterial::_update_shader() {
 	code += "uniform vec3 gravity;\n";
 
 	if (color_ramp.is_valid()) {
-		code += "uniform sampler2D color_ramp;\n";
+		code += "uniform sampler2D color_ramp: repeat_disable;\n";
```
Comment (Calinou) [inline scene/resources/particles_material.cpp:236]: Just a syntactic note: I've typically seen shader hints written like this:

```glsl
uniform sampler2D color_ramp : repeat_disable;
```

As opposed to this:

```glsl
uniform sampler2D color_ramp: repeat_disable;
```

The [Godot shader language style guide](https://docs.godotengine.org/en/latest/tutorials/shaders/shaders_style_guide.html) doesn't make a recommendation on this yet, but we should figure one out.

**Review by Calinou — APPROVED** [review]

File: scene/resources/particles_material.cpp (hunk 1 above)
Comment (fire-forge) [reply scene/resources/particles_material.cpp:236]: The example in the shading language docs does it this way:

```gdscript
shader_type spatial;

uniform vec4 color : hint_color;
uniform float amount : hint_range(0, 1);
uniform vec4 other_color : hint_color
```

Comment (clayjohn) [reply scene/resources/particles_material.cpp]: I don't have an opinion either way. I updated it to have the space like:
```glsl
uniform sampler2D color_ramp : repeat_disable;
```

**Review by fire-forge — APPROVED** [review]
