### PR TITLE
Mark thread name setup safe for nodes

### LINKED ISSUE #77928: Starting a thread in GDScript that calls function with arguments will print error message in recent Godot build
### Godot version

Godot 4.1-dev (ed63b9ea23)

### System information

Manjaro Gnome

### Issue description

`thread.start(test.bind(0))` prints the following error:

```
ERROR: Caller thread can't call this function in this node. Use call_deferred() or call_thread_group() instead.
   at: get_script (scene/main/node.cpp:3536)
```

### Steps to reproduce

```
func _ready() -> void:
	var thread := Thread.new()
	thread.start(test.bind(0))

func test(i: int) -> void:
	pass
```

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by RandomShaper**
Fixes #77928.

### CODE REVIEW

File: core/core_bind.cpp [hunk 1]
```diff
@@ -1187,7 +1187,11 @@ void Thread::_start_func(void *ud) {
 		ERR_FAIL_MSG(vformat("Could not call function '%s' on previously freed instance to start thread %s.", t->target_callable.get_method(), t->get_id()));
 	}
 
+	// Finding out a suitable name for the thread can involve querying a node, if the target is one.
+	// We now this is safe (unless the user is causing life cycle race conditions, which would be a bug on their part).
```
Comment (clayjohn) [inline core/core_bind.cpp:1191]:
```suggestion
	// We know this is safe (unless the user is causing life cycle race conditions, which would be a bug on their part).
```

**Comment by bitsawer** [comment]
This PR seems to fix the reported issue, but I think I found a minor extra problem. This code snippet works in 4.0.3:

```gdscript
extends MeshInstance3D

var thread := Thread.new()

func _ready() -> void:
    thread.start(test)

func test() -> void:
    print(self)
```


and prints something like `MeshInstance3D:<MeshInstance3D#26373784710>`. However, in master + this PR it doesn't print anything and gives the error:
```

E 0:00:00:0936   to_string: Caller thread can't call this function in this node. Use call_deferred() or call_thread_group() instead.
  <C++ Error>    Condition "!is_accessible_from_caller_thread()" is true. Returning: (String())
  <C++ Source>   scene\main\node.cpp:2376 @ to_string()
```

Looks like accessing `self` and in this case calling its `to_string()` in the thread functions can also encounter these problems. I guess in many cases this makes sense with the new threading check, but it can be pretty inconvenient.

**Comment by RandomShaper** [comment]
I see. The fix for that will come in a separate PR.

**Review by akien-mga — APPROVED** [review]
