### PR TITLE
Deselect multi caret when alt clicking on it

### LINKED ISSUE #80895: Multi carets cannot be deselected
### Godot version

4.1

### System information

Windows

### Issue description

Being able to have multiple cursors similarly to vscode is a great feature, however it's only possible to add carets, not remove them. By left clicking you can remove all extra cursors but you cannot remove a specific one so after selecting multiple lines a single missclick, you have to reselect them all again. Looking at the original pr there was a remove_caret function added so it would make sense to be able to remove carets when clicking again, like in vscode.

image

### Steps to reproduce

- Alt click to add multiple carets
- Alt click on the same position again
- Nothing happens

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by MarcusElg**
Fixes #80895

If a caret can't be added it checks if it already exists and then removes it. So now it works similarly to vscode when alt clicking once adds a caret, and alt clicking again removes it.

It does loop through the carets twice but preventing that would require changing the return value of add_caret and therefore break compatibility. The amount of carets are always quite low so the performance impact should be neglectable.

### CODE REVIEW

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -1759,6 +1759,15 @@ void TextEdit::gui_input(const Ref<InputEvent> &p_gui_input) {
 
 						caret = add_caret(row, col);
 						if (caret == -1) {
+							// Remove caret at clicked location
```
Comment (MewPurPur) [inline scene/gui/text_edit.cpp:1762]: Add punctuation here.

**Review by MewPurPur — APPROVED** [review]
I like this implementation, in all honesty I wonder why this wasn't part of the initial implementation.

**Review by KoBeWi — APPROVED** [review]

**Review by AThousandShips — APPROVED** [review]
LGTM, the comment punctuation needs to be fixed though

**Review by Calinou — COMMENTED** [review]
Tested locally (rebased on top of `master` 6758a7f8c07d1f4c8ec4f052ded6d26402967ebe), it mostly works as expected.

However, with this PR, unlike in VS Code, it's not possible to deselect a character/word selection by holding Alt and clicking the selection or the caret:


https://github.com/godotengine/godot/assets/180032/678b8c06-2a9a-467e-8706-ab75ea20b256

File: scene/gui/text_edit.cpp (hunk 1 above)
Comment (MarcusElg) [reply scene/gui/text_edit.cpp]: Fixed

**Review by Paulb23 — COMMENTED** [review]
LGTM, would be nice to add a unit test :)

**Comment by MarcusElg** [comment]
@Calinou fixed, you can now deselect by clicking its selection

**Review by Paulb23 — CHANGES_REQUESTED** [review]

File: scene/gui/text_edit.cpp [hunk 2]
```diff
@@ -1752,11 +1752,27 @@ void TextEdit::gui_input(const Ref<InputEvent> &p_gui_input) {
...
-				if (!is_mouse_over_selection() && !mb->is_double_click() && !is_triple_click) {
+				if (!mb->is_double_click() && !is_triple_click) {
 					if (mb->is_alt_pressed()) {
 						prev_line = row;
 						prev_col = col;
 
+						// Remove caret at clicked location.
+						if (carets.size() > 1) {
+							for (int i = 0; i < carets.size(); i++) {
+								// Deselect if clicked on caret or its selection.
```
Comment (AThousandShips) [inline scene/gui/text_edit.cpp:1763]:
```suggestion
								// Deselect if clicked on caret or its selection.
```

**Review by Paulb23 — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
