### PR TITLE
Fix Tree Mouse hover position

### LINKED ISSUE #102194: Tree button click detection is off
### Tested versions

Godot v4.4.beta2 

### System information

Fedora Linux 40 (KDE Plasma) on Wayland - X11 display driver, Multi-window

### Issue description

Tree button click detection is off. 
Mouse is over one button but you click on another. 
In some cases it draws hover state for one button but clicks on another.

https://github.com/user-attachments/assets/0a4e895d-eb4a-46db-878e-2f057e2df852

### Steps to reproduce

Have multiple buttons in a column.
Try to interact with them.

### Minimal reproduction project (MRP)

[treemouse.zip](https://github.com/user-attachments/files/18604902/treemouse.zip)

### PR DESCRIPTION
**Pull request by Hilderin**
- Fixes #102194

This PR should fixes the hovered, tooltip and click position for trees button.

The PR includes:
- A simplification of the `_determine_hovered_item` to use the `_find_button_at_pos` method which tried to do exactly the same thing, aka finding the button at a position.
- The space used by the scrollbar was not correctly calculated. At first, I tried to simply add the missing `scrollbar_h_separation` but there's some calculations in `_get_content_rect` that manage a situation where the scrollbar is inside the panel margin (when theme `scrollbar_margin_right` is >= 0). I simply used `_get_content_rect` directly like a lot of other places in the tree code. This fix was added in `_range_click_timeout`, `gui_input`, and `_find_button_at_pos`.
- The condition to check if the mouse position was hover a button was always off 2 pixels to the right because of a missing >= and a -1 needed because is a comparaison between a zero based position and a size. This fix was added in `_find_button_at_pos` and `propagate_mouse_event`.
- The margin area of the scrollbar was considered the last column and button.
- In RTL mode, the panel offset was calculated before the adjustment to `pos.x` in `_find_button_at_pos` causing an offset of a couple of pixels in RTL mode.
- Finally, I added -1 when adjusting the position in RTL mode in `_find_button_at_pos` to have the exact position. Ex: If the position is 99,0 and the size is 100,0 the actual position to use is 0,0. If the position is 0,0, the actual position to use is 99,0. I changed every place in the Tree code where these adjustments were present.

I tested in Window with the MRP from the issue and with different settings. I'm not familiar with the Tree control so I strongly suggest more test are done.

Note: There still some duplicate code between `_find_button_at_pos` and `propagate_mouse_event` but everything seems to work fine as is, I'm really not confident I can refactor this without any side effect, especially just before a new release.

https://github.com/user-attachments/assets/b6cac137-e7ad-4687-9585-7184fce5c63b

### CODE REVIEW

**Comment by Hilderin** [comment]
It seems I missed little detail, in the editor Scene Tree, it's still off a couple pixels... I'll debug that...

**Comment by Hilderin** [comment]
I fixed the issue by reusing the `_get_content_rect` instead of trying to recalculate the correct scrollbar size.

But, I found out an other issue that the last button is considered hovered and is clicable from the margin around the scrollbar:

https://github.com/user-attachments/assets/382ccb36-605d-40a5-b836-2a46f211180e


I tested in Godot 4.3 stable and turns out that this behaviour existed in the version (minus the hover which did not exist in 4.3):

https://github.com/user-attachments/assets/e9a76b9f-ea9a-4ee6-8d93-ef8505dff49f


I fixed it anyway by adding a check for the position vs the content area (`x_limit`) in `_find_button_at_pos` and `propagate_mouse_event`.

**Comment by KoBeWi** [comment]
The original bug is still there:

https://github.com/user-attachments/assets/041e15c6-7311-4a3b-8b0a-dfe76fc75494

Different buttons are hovered and clicked.

**Comment by Hilderin** [comment]
Indeed, there's was still some difference between `propagate_mouse_event` and `_find_button_at_pos` when the button were under the scrollbar or when the tree was scrolled to the right.

To prevent any difference between the two, I moved the commun parts in a new method called `_find_column_and_button_at_pos`. This method returns a new struct `FindColumnButtonResult` which contains all the info needed in `propagate_mouse_event` to work as before.

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -5619,53 +5452,99 @@ void Tree::_find_button_at_pos(const Point2 &p_pos, TreeItem *&r_item, int &r_co
...
+		} else {
+			col_width -= theme_cache.h_separation;
+			limit_w -= theme_cache.h_separation;
+			x -= theme_cache.h_separation;
+		}
+
+		if (!cache.rtl && !p_item->cells[col].buttons.is_empty()) {
+			int button_w = 0;
+			for (int j = p_item->cells[col].buttons.size() - 1; j >= 0; j--) {
+				Ref<Texture2D> b = p_item->cells[col].buttons[j].texture;
```
Comment (KoBeWi) [inline scene/gui/tree.cpp:5517]:
```suggestion
				const Ref<Texture2D> &b = p_item->cells[col].buttons[j].texture;
```

File: scene/gui/tree.cpp [hunk 2]
```diff
@@ -5619,53 +5452,99 @@ void Tree::_find_button_at_pos(const Point2 &p_pos, TreeItem *&r_item, int &r_co
...
+			col_width = MAX(button_w, MIN(limit_w, col_width));
+		}
+
+		// Cell button detection code.
+		// The first half of the button margin will be applied to the left button,
+		// and the other half to the right button.
+		const int offset_button_width = theme_cache.button_margin / 2;
+		const TreeItem::Cell &c = p_item->cells[col];
+		for (int j = c.buttons.size() - 1; j >= 0; j--) {
+			Ref<Texture2D> b = c.buttons[j].texture;
```
Comment (KoBeWi) [inline scene/gui/tree.cpp:5530]:
```suggestion
			const Ref<Texture2D> &b = c.buttons[j].texture;
```

**Review by KoBeWi — APPROVED** [review]
Works correctly now.

File: scene/gui/tree.cpp (hunk 1 above)
Comment (Hilderin) [reply scene/gui/tree.cpp]: Done!

File: scene/gui/tree.cpp (hunk 2 above)
Comment (Hilderin) [reply scene/gui/tree.cpp]: Done!

**Comment by akien-mga** [comment]
Thanks!
