### PR TITLE
[3.x] Add type validations when setting basic type

### LINKED ISSUE #53456: `VisualScriptFunctionCall.set_basic_type` not validating input which later cause crash
### Godot version

3.4.beta.custom_build. 01ae4888e

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

When executing
```
	var temp_variable12807 = VisualScriptFunctionCall.new()
	temp_variable12807.set_call_mode(3)
	temp_variable12807.set_basic_type(-32)
	temp_variable12807._get_default_input_values()
```

Godot crashes with backtrace
```
modules/visual_script/visual_script_func_nodes.cpp:133:68: runtime error: load of value 4294967264, which is not a valid value for type 'Type'

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v3.4.beta.custom_build (e848da3a5d535f9df56613b7a2ad2371327b511a)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] godots() [0x17d812a] (/mnt/Miecz/godot3.2/platform/x11/crash_handler_x11.cpp:56)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x41040) [0x7f931ec11040] (??:0)
[3] Map<StringName, _VariantCall::FuncData, Comparator<StringName>, DefaultAllocator>::find(StringName const&) const (/mnt/Miecz/godot3.2/./core/map.h:509)
[4] Variant::get_method_argument_types(Variant::Type, StringName const&) (/mnt/Miecz/godot3.2/core/variant_call.cpp:1395)
[5] VisualScriptFunctionCall::get_input_value_port_count() const (/mnt/Miecz/godot3.2/modules/visual_script/visual_script_func_nodes.cpp:134)
[6] VisualScriptNode::_get_default_input_values() const (/mnt/Miecz/godot3.2/modules/visual_script/visual_script.cpp:99)
[7] MethodBind0RC<Array>::call(Object*, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/./core/method_bind.gen.inc:593 (discriminator 4))
[8] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/core/object.cpp:918 (discriminator 1))
[9] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/mnt/Miecz/godot3.2/core/variant_call.cpp:1175 (discriminator 1))
[10] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript_function.cpp:1049)
[11] GDScriptInstance::_ml_call_reversed(GDScript*, StringName const&, Variant const**, int) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript.cpp:1199)
[12] GDScriptInstance::call_multilevel_reversed(StringName const&, Variant const**, int) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript.cpp:1207)
[13] Node::_notification(int) (/mnt/Miecz/godot3.2/scene/main/node.cpp:149)
[14] Node::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/main/node.h:45 (discriminator 14))
[15] CanvasItem::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/2d/canvas_item.h:163 (discriminator 3))
[16] Node2D::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/2d/node_2d.h:37 (discriminator 3))
[17] Object::notification(int, bool) (/mnt/Miecz/godot3.2/core/object.cpp:929)
[18] Node::_propagate_ready() (/mnt/Miecz/godot3.2/scene/main/node.cpp:188)
[19] Node::_propagate_ready() (/mnt/Miecz/godot3.2/scene/main/node.cpp:178 (discriminator 2))
[20] Node::_set_tree(SceneTree*) (/mnt/Miecz/godot3.2/scene/main/node.cpp:2560)
[21] SceneTree::init() (/mnt/Miecz/godot3.2/scene/main/scene_tree.cpp:465)
[22] OS_X11::run() (/mnt/Miecz/godot3.2/platform/x11/os_x11.cpp:3636)
[23] godots(main+0x326) [0x17cedac] (/mnt/Miecz/godot3.2/platform/x11/godot_x11.cpp:57)
[24] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xd5) [0x7f931ebf8565] (??:0)
[25] godots(_start+0x2e) [0x17ce9ce] (??:?)

```

Code is here and p_type should be between 0(Variant::Nil) and Variant::Max
https://github.com/godotengine/godot/blob/a7ba22763139b29d825e0f4ef3e718533da069ea/modules/visual_script/visual_script_func_nodes.cpp#L299-L307

This example was found by fuzzer, so I don't recommend trying understand in what situation such code could be used in real project, because such situation probably doesn't exists.

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by LATRio**
fixes #53456

### CODE REVIEW

**Review by akien-mga — COMMENTED** [review]
The VisualScript fixes are good, but I'm not sure about the changes to Variant. It changes behavior as now it those functions will throw an error if the method doesn't exist, while previously they would handle it silently. Needs @godotengine/core review.

**Comment by akien-mga** [comment]
Also, #53456 should be checked against the `master` branch as it might be reproducible there too.

File: core/variant_call.cpp [hunk 1]
```diff
@@ -1390,45 +1390,41 @@ bool Variant::has_method(const StringName &p_method) const {
...
 
 Vector<Variant::Type> Variant::get_method_argument_types(Variant::Type p_type, const StringName &p_method) {
+	ERR_FAIL_INDEX_V(p_type, Variant::VARIANT_MAX, Vector<Variant::Type>());
 	const _VariantCall::TypeFunc &tf = _VariantCall::type_funcs[p_type];
 
 	const Map<StringName, _VariantCall::FuncData>::Element *E = tf.functions.find(p_method);
-	if (!E) {
-		return Vector<Variant::Type>();
-	}
+	ERR_FAIL_COND_V(!E, Vector<Variant::Type>());
```
Comment (akien-mga) [inline core/variant_call.cpp:1397]: We discussed this in a review meeting, the `ERR_FAIL_INDEX_V` are good, but we're not confident that the change from `if (!E)` to an error condition is good. There's a risk that these methods might actually be used with non-existing methods at times and the code expects it to return an empty/default value.

Since it's not part of the fix for the reported bug, it's probably best to leave this part alone (same in other methods, only validate `p_type`).

Comment (LATRio) [reply core/variant_call.cpp]: Removed changes.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
