### PR TITLE
Fix .NET exporting in Linux

### LINKED ISSUE #56450: Godot 4 cannot export project with C# "Target platform not supported"
### Godot version

4.0.dev.mono

### System information

Windows 10

### Issue description

When trying to export a project with a C# script you get the error "Target platform not supported." The exe and pck files are still created but the data folder is not.
From my testing it seems like in https://github.com/godotengine/godot/blob/master/modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs#L387 the feature "windows" is passed in, but OS.PlatformNameMap.TryGetValue seems to expect "Windows" instead.
Changing the foreach loop in https://github.com/godotengine/godot/blob/master/modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs#L387 to below allows project to be exported.
```C#
foreach (var feature in features)
{
    string f = feature.Length > 0 ? $"{feature[0].ToString().ToUpper()}{feature.Substring(1)}" : feature;

    if (OS.PlatformNameMap.TryGetValue(f, out platform))
        return true;
}
```

### Steps to reproduce

1. Clone from master.
2. Build:
    - ```scons -j12 p=windows tools=yes module_mono_enabled=yes mono_glue=no```
    - ```bin\godot.windows.tools.64.mono --generate-mono-glue modules/mono/glue```
    - ```scons -j12 p=windows target=release_debug tools=yes module_mono_enabled=yes```
    - ```scons -j12 p=windows target=release_debug tools=no module_mono_enabled=yes```
    - ```scons -j12 p=windows target=release tools=no module_mono_enabled=yes```
3. Move and rename export templates.
4. Export project.

### Minimal reproduction project

[TestProject.zip](https://github.com/godotengine/godot/files/7799848/TestProject.zip)

### LINKED ISSUE #64983: C#: Exported games fail to load hostfxr
### Godot version

1f9b992d85fb974c7aa1fadaf2d1b4ff59850137

### System information

Windows 10

### Issue description

Hey 😄 

With the mono module, exported games crash as soon as they start. This happens with templates compiled in `release` and in `release_debug`. My editor itself is built in `debug`.  
Running them through the console script yields the following errors.
```
ERROR: Can't open dynamic library: C:/Users/paulloz/Desktop/Builds/Sandbox/data_Sandbox-G4NET6/hostfxr.dll, error: Error 193: %1 is not a valid Win32 application.
   at: (platform\windows\os_windows.cpp:257)
ERROR: Can't open dynamic library: C:/Users/paulloz/Desktop/Builds/Sandbox/data_Sandbox-G4NET6/Sandbox-G4NET6.dll, error: Error 193: %1 is not a valid Win32 application.
   at: (platform\windows\os_windows.cpp:257)
ERROR: .NET: Failed to load hostfxr
   at: (modules\mono\mono_gd\gd_mono.cpp:435)
```

I believe @raulsntos was saying the same kind of thing occurs on Linux regarding hostfxr. However, the two first errors here may not have their counterpart on other platforms.  

I must note that specifically on Windows 10 (x86_64), exports templates weren't compiling at first. I had to apply the following patch, that I'm not confident is valid, especially the second part.

```diff
diff --git a/modules/mono/mono_gd/gd_mono.cpp b/modules/mono/mono_gd/gd_mono.cpp
index 0532cc915b..16bbc6a672 100644
--- a/modules/mono/mono_gd/gd_mono.cpp
+++ b/modules/mono/mono_gd/gd_mono.cpp
@@ -270,7 +270,7 @@ load_assembly_and_get_function_pointer_fn initialize_hostfxr_self_contained(
        int i = 1;
        for (const String &E : cmdline_args) {
                HostFxrCharString &stored = argv_store.push_back(str_to_hostfxr(E))->get();
-               argv.write[i] = stored.ptr();
+               argv.write[i] = (const char_t *)stored.ptr();
                i++;
        }

@@ -356,7 +356,7 @@ godot_plugins_initialize_fn initialize_hostfxr_and_godot_plugins(bool &r_runtime
        print_verbose(".NET: hostfxr initialized");

        int rc = load_assembly_and_get_function_pointer(get_data(assembly_path),
-                       str_to_hostfxr("GodotPlugins.Game.Main, " + assembly_name),
+                       get_data(str_to_hostfxr("GodotPlugins.Game.Main, " + assembly_name)),
                        HOSTFXR_STR("InitializeFromGameProject"),
                        UNMANAGEDCALLERSONLY_METHOD,
                        nullptr,
```
This is an attempt to fix the following compilation errors.
```
modules\mono\mono_gd\gd_mono.cpp(273): error C2440: '=': cannot convert from 'const char16_t *' to 'T'
        with
        [
            T=const char_t *
        ]
modules\mono\mono_gd\gd_mono.cpp(273): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast)
modules\mono\mono_gd\gd_mono.cpp(359): error C2664: 'int (const char_t *,const char_t *,const char_t *,const char_t *,void *,void **)': cannot convert argument n from '`anonymous-namespace'::HostFxrCharString' to 'const char_t *'
modules\mono\mono_gd\gd_mono.cpp(359): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
```

### Steps to reproduce

Should be really easy to reproduce:
* Create a project
* Add a C# script
* Export
* Run the exported game

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by raulsntos**
- Fix platform detection after Linux OS name was renamed from `LinuxBSD` to `Linux`
	- Follow up to #61352
	- Fixes https://github.com/godotengine/godot/issues/56450
- Fix arch detection after renaming `64` to `x86_64`
	- Follow up to #55778
	- Partially fixes #64983
- Fix typo in `find_hostfxr`

### CODE REVIEW

**Comment by paulloz** [comment]
> May fix #64983 but would need someone on Windows to test it

I'm not sure. It still does not compile because of the errors defined in the linked issue. If I apply the same patch I describe and compile, it crashes, but not because of the same errors. I'm pasting the backtrace below. Given it crashes where I modified stuff to get it to compile, I wouldn't be surprised if my *"fix"* was completely wrong.
```
================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.0.alpha.mono.custom_build (e9b22ae1c0e2d984e02e84fdf11a9783a7f6e41a)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] hostfxr_close
[1] hostfxr_initialize_for_dotnet_command_line
[2] `anonymous namespace'::initialize_hostfxr_self_contained (E:\Godot Worktree\godot\modules\mono\mono_gd\gd_mono.cpp:277)
[3] `anonymous namespace'::initialize_hostfxr_and_godot_plugins (E:\Godot Worktree\godot\modules\mono\mono_gd\gd_mono.cpp:350)
[4] GDMono::initialize (E:\Godot Worktree\godot\modules\mono\mono_gd\gd_mono.cpp:443)
[5] ScriptServer::init_languages
[6] Main::setup2 (E:\Godot Worktree\godot\main\main.cpp:2159)
[7] Main::setup (E:\Godot Worktree\godot\main\main.cpp:1678)
[8] widechar_main (E:\Godot Worktree\godot\platform\windows\godot_windows.cpp:162)
[9] _main (E:\Godot Worktree\godot\platform\windows\godot_windows.cpp:203)
[10] main (E:\Godot Worktree\godot\platform\windows\godot_windows.cpp:215)
[11] __scrt_common_main_seh (d:\a01\_work\43\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[12] BaseThreadInitThunk
-- END OF BACKTRACE --
================================================================
```

File: modules/mono/editor/GodotTools/GodotTools/Utils/OS.cs [hunk 1]
```diff
@@ -70,7 +70,7 @@ public static class DotNetOS
         {
             ["Windows"] = Platforms.Windows,
             ["macOS"] = Platforms.MacOS,
-            ["LinuxBSD"] = Platforms.LinuxBSD,
+            ["Linux"] = Platforms.LinuxBSD,
             // "X11" for compatibility, temporarily, while we are on an outdated branch
             ["X11"] = Platforms.LinuxBSD,
```
Comment (neikeq) [inline modules/mono/editor/GodotTools/GodotTools/Utils/OS.cs:75]: We may want to remove this already.

File: modules/mono/editor/GodotTools/GodotTools/Build/BuildSystem.cs [hunk 2]
```diff
@@ -176,8 +176,9 @@ private static void BuildPublishArguments(BuildInfo buildInfo, Collection<string
                 arguments.Add("--no-restore");
 
             // Incremental or rebuild
-            if (buildInfo.Rebuild)
-                arguments.Add("--no-incremental");
+            // TODO: Not supported in `dotnet publish` (https://github.com/dotnet/sdk/issues/11099)
+            // if (buildInfo.Rebuild)
+            //     arguments.Add("--no-incremental");
```
Comment (neikeq) [inline modules/mono/editor/GodotTools/GodotTools/Build/BuildSystem.cs:181]: Weird, we shouldn't be using Rebuild when publishing.

File: modules/mono/editor/GodotTools/GodotTools/Utils/OS.cs [hunk 3]
```diff
@@ -70,7 +70,7 @@ public static class DotNetOS
         {
             ["Windows"] = Platforms.Windows,
             ["macOS"] = Platforms.MacOS,
-            ["LinuxBSD"] = Platforms.LinuxBSD,
+            ["Linux"] = Platforms.LinuxBSD,
```
Comment (neikeq) [inline modules/mono/editor/GodotTools/GodotTools/Utils/OS.cs:73]: So I assume this was throwing `Target platform not supported`, right?

Comment (raulsntos) [reply modules/mono/editor/GodotTools/GodotTools/Utils/OS.cs:73]: Yeah

File: modules/mono/editor/GodotTools/GodotTools/Build/BuildSystem.cs (hunk 2 above)
Comment (raulsntos) [reply modules/mono/editor/GodotTools/GodotTools/Build/BuildSystem.cs:181]: Oh it wasn't, I just noticed that the option doesn't exist in `dotnet publish`

**Comment by raulsntos** [comment]
The exported game crashes with `SIGSEGV: invalid address (fault address: 0x0)`, it seems to be in this line:

https://github.com/godotengine/godot/blob/f38ea254f334ffa02fb501b336b1a60374c7f945/modules/mono/csharp_script.cpp#L2663

Backtrace:

```
* thread #1, name = 'export_te', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
  * frame #0: 0x0000000000000000
    frame #1: 0x00007fff4dfbe4dd
    frame #2: 0x00007fff4dfbe401
    frame #3: 0x00007fff4dfbe329
    frame #4: 0x00007fff4dfbdbe1
    frame #5: 0x00005555587d3393 export_test.x86_64`ResourceFormatLoaderCSharpScript::load(this=0x000055555e601690, p_path=0x000055555ec580b8, p_original_path=0x000055555ec580b8, r_error=0x000055555ec580d4, p_use_sub_threads=false, r_progress=0x000055555ec580c8, p_cache_mode=CACHE_MODE_REUSE) at csharp_script.cpp:2663:3
    frame #6: 0x000055555b24c916 export_test.x86_64`ResourceLoader::_load(p_path=0x000055555ec580b8, p_original_path=0x00007fffffffaf78, p_type_hint=0x000055555ec580c0, p_cache_mode=CACHE_MODE_REUSE, r_error=0x000055555ec580d4, p_use_sub_threads=false, r_progress=0x000055555ec580c8) at resource_loader.cpp:213:34
    frame #7: 0x000055555b24ce19 export_test.x86_64`ResourceLoader::_thread_load_function(p_userdata=0x000055555ec58098) at resource_loader.cpp:240:23
    frame #8: 0x000055555b24fa6c export_test.x86_64`ResourceLoader::load(p_path=0x00007fffffffbdc0, p_type_hint=0x00007fffffffbdb0, p_cache_mode=CACHE_MODE_REUSE, r_error=0x0000000000000000) at resource_loader.cpp:568:3
    frame #9: 0x0000555559f5f60e export_test.x86_64`ResourceLoaderText::load(this=0x00007fffffffbf38) at resource_format_text.cpp:480:24
    frame #10: 0x0000555559f6fda4 export_test.x86_64`ResourceFormatLoaderText::load(this=0x000055555c3cff20, p_path=0x000055555eae7538, p_original_path=0x000055555eae7538, r_error=0x000055555eae7554, p_use_sub_threads=false, r_progress=0x000055555eae7548, p_cache_mode=CACHE_MODE_REUSE) at resource_format_text.cpp:1568:15
    frame #11: 0x000055555b24c916 export_test.x86_64`ResourceLoader::_load(p_path=0x000055555eae7538, p_original_path=0x00007fffffffc2f8, p_type_hint=0x000055555eae7540, p_cache_mode=CACHE_MODE_REUSE, r_error=0x000055555eae7554, p_use_sub_threads=false, r_progress=0x000055555eae7548) at resource_loader.cpp:213:34
    frame #12: 0x000055555b24ce19 export_test.x86_64`ResourceLoader::_thread_load_function(p_userdata=0x000055555eae7518) at resource_loader.cpp:240:23
    frame #13: 0x000055555b24fa6c export_test.x86_64`ResourceLoader::load(p_path=0x00007fffffffcbf0, p_type_hint=0x00007fffffffcaf8, p_cache_mode=CACHE_MODE_REUSE, r_error=0x0000000000000000) at resource_loader.cpp:568:3
    frame #14: 0x00005555580eccb6 export_test.x86_64`Main::start() at main.cpp:2759:34
    frame #15: 0x0000555558085e31 export_test.x86_64`main(argc=1, argv=0x00007fffffffdec8) at godot_linuxbsd.cpp:71:6
    frame #16: 0x00007ffff7a29d90 libc.so.6`__libc_start_call_main(main=(export_test.x86_64`main at godot_linuxbsd.cpp:43), argc=1, argv=0x00007fffffffdec8) at libc_start_call_main.h:58:16
    frame #17: 0x00007ffff7a29e40 libc.so.6`__libc_start_main_impl(main=<unavailable>, argc=1, argv=<unavailable>, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffdeb8) at libc-start.c:392:3
    frame #18: 0x0000555558085ba5 export_test.x86_64`_start + 37
```

**Comment by paulloz** [comment]
Looks related to where I'm at on Windows?
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Godot.NativeInterop.NativeFuncs.godotsharp_internal_new_csharp_script(Godot.NativeInterop.godot_ref*)
   at Godot.Bridge.ScriptManagerBridge.CreateScriptBridgeForType(System.Type, Godot.NativeInterop.godot_ref*)
   at Godot.Bridge.ScriptManagerBridge.GetOrCreateScriptBridgeForType(System.Type, Godot.NativeInterop.godot_ref*)
   at Godot.Bridge.ScriptManagerBridge.GetOrCreateScriptBridgeForPath(Godot.NativeInterop.godot_string*, Godot.NativeInterop.godot_ref*)
```

**Comment by neikeq** [comment]
I fixed the crash in #65046.

File: modules/mono/editor/GodotTools/GodotTools/Build/BuildSystem.cs (hunk 2 above)
Comment (neikeq) [reply modules/mono/editor/GodotTools/GodotTools/Build/BuildSystem.cs:181]: My bad, I didn't notice the comment about the issue and that this was the `BuildPublishArguments` method.

**Review by neikeq — APPROVED** [review]

**Comment by neikeq** [comment]
I think this can be merged now, but I'll wait for confirmation, as it's still marked as draft.

**Comment by raulsntos** [comment]
I was keeping it a draft because I wanted to look into the issue you solved :)
