### PR TITLE
Visual glitch when dragging keyframes #15285

### LINKED ISSUE #15285: Visual glitch when dragging keyframes
**Godot version:** from 2.1 till at least 6188279

**OS/device including version:**
Win 7 64 bits

**Issue description:**
Keyframes jump one track up while being dragged. It only happens when there are enough tracks to make the vertical scrollbar appear. It doesn't happen when the scrollbar is in the topmost or bottommost position.

**Steps to reproduce:**
1 - open animation dock
2 - add enough channels so that a vertical scrollbar appears
3 - put the scrollbar in any position other than complete top or bottom
4 - drag one or a selection of keyframes

**Minimal reproduction project:**
Here's a video showing the issue. The first part shows the issue and after 00:11 it shows how it doesn't happen with the scrollbar on top or bottom position.

[15285-keyframe-dragging-gltich.zip](https://github.com/godotengine/godot/files/1600460/15285-keyframe-dragging-gltich.zip)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

### PR DESCRIPTION
**Pull request by thomaslynge**
The drag key glitch in the animation editor should be fixed with this pr.

*Bugsquad edit:* Closes #15285.

### CODE REVIEW

File: editor/animation_editor.cpp [hunk 1]
```diff
@@ -1533,7 +1533,7 @@ void AnimationKeyEditor::_track_editor_draw() {
 			for (Map<SelectedKey, KeyInfo>::Element *E = selection.front(); E; E = E->next()) {
 
 				int idx = E->key().track;
-				int i = idx - v_scroll->get_value();
+				int i = idx - Math::floor(v_scroll->get_value());
```
Comment (akien-mga) [inline editor/animation_editor.cpp]: Is there a specific reason to use floor instead of round in this case?

Comment (thomaslynge) [reply editor/animation_editor.cpp]: It has to use floor otherwise the offset is wrong, if the value is 0.5 etc. I have just changed the Math::floor to (int). Hope that is fine.

**Comment by akien-mga** [comment]
Oops, shouldn't have merged that on the phone, this needed a rebase to squash into a single commit... Too late now, but please read http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html for future PRs.

**Comment by thomaslynge** [comment]
Okay, sorry about that. I'll look into rebasing the next time.
