### PR TITLE
Add fixed fog to the sky in the Compatibility renderer

### LINKED ISSUE #66456: OpenGL: Environment fog does not affect sky rendering
### Godot version

4.0.beta (53d2a9acd)

### System information

Fedora 36, GeForce GTX 1080 (NVIDIA 515.65.01)

### Issue description

Unlike in Vulkan, environment fog does not affect sky rendering when using the OpenGL renderer. Fog Sky Affect's value is ignored.

### Steps to reproduce

- Switch to the OpenGL driver in the Project Settings.
  - Make sure to start the editor with single-window mode enabled afterwards. This can be done by enabling **Single Window Mode** in the Editor Settings before changing the driver, or by opening the project in the editor directly with the `--single-window` [command line argument](https://docs.godotengine.org/en/latest/tutorials/editor/command_line_tutorial.html).
- Add a WorldEnvironment node, a Camera3D node and a MeshInstance3D in front of the camera.
- Enable fog. Increase density to 0.05 or more to make a visible difference in the scene.

### Minimal reproduction project

[test_opengl_fog_sky_affect.zip](https://github.com/godotengine/godot/files/9648583/test_opengl_fog_sky_affect.zip)

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/66456

The entire implementation was missing. Some of the infrastructure was already there and just needed to be plugged in and finished

### CODE REVIEW

File: drivers/gles3/rasterizer_scene_gles3.cpp [hunk 1]
```diff
@@ -777,7 +777,6 @@ void RasterizerSceneGLES3::_draw_sky(RID p_env, const Projection &p_projection,
 	ERR_FAIL_COND(p_env.is_null());
 
 	Sky *sky = sky_owner.get_or_null(environment_get_sky(p_env));
-	ERR_FAIL_NULL(sky);
```
Comment (clayjohn) [inline drivers/gles3/rasterizer_scene_gles3.cpp:780]: When doing a custom sky pass for fog we can continue without the sky. This is used when you have fog, but are using a custom color background.

**Review by Calinou — COMMENTED** [review]
Tested locally with https://github.com/godotengine/godot/issues/66456's MRP, it mostly works as expected. There seems to be a sRGB/linear color conversion issue though:

Forward+ | Mobile | Compatibility 
-|-|-
Screenshot_20240817_194256 | Screenshot_20240817_194242 | Screenshot_20240817_194228

With tonemapping set to Linear in the MRP:

Forward+ | Mobile | Compatibility 
-|-|-
Screenshot_20240817_194456 | Screenshot_20240817_194510 | Screenshot_20240817_194523

With tonemapping set to Linear in the MRP and fog density set to 1 (so you can compare the actual fog color):

Forward+ | Mobile | Compatibility 
-|-|-
Screenshot_20240817_194720 | Screenshot_20240817_194705 | Screenshot_20240817_194651

Sky colors with Linear tonemapping:

Forward+ | Mobile | Compatibility
-|-|-
`#858c9c` | `#b5c1d3` | `#3b4354`

The Mobile rendering method has a similar issue, but the sky color is too bright instead of being too dark.

**Comment by clayjohn** [comment]
@Calinou Oh! good catch there, I was testing with white fog, so it looked the same in all backends to me. 

I think I know what is wrong in the mobile backend, the code looked a little funny to me, but I left it alone as it was out of scope. I can probably do a quick fix for both

**Comment by clayjohn** [comment]
Pushed a fix for your comment.

_Before_
| Forward+ | Mobile | Compatibility |
| - | - | - |
|Screenshot from 2024-08-17 23-29-52|Screenshot from 2024-08-17 23-30-13|Screenshot from 2024-08-17 23-30-48|

_After_
|Forward+|Mobile|Compatibility|
|-|-|-|
|Screenshot from 2024-08-17 23-33-00|Screenshot from 2024-08-17 23-32-41|Screenshot from 2024-08-17 23-32-20|

**Review by Calinou — APPROVED** [review]
Works great now :slightly_smiling_face: 

### Fog Density = 0.05

Forward+ | Mobile | Compatibility
-|-|-
Screenshot_20240818_184214 png webp | Screenshot_20240818_184228 png webp | Screenshot_20240818_184239 png webp

### Fog Density = 1.0

Forward+ | Mobile | Compatibility
-|-|-
Screenshot_20240818_184418 png webp | Screenshot_20240818_184432 png webp | Screenshot_20240818_184440 png webp

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.
