### PR TITLE
Remove all elements from monitored_bodies and monitored_areas when processed

### LINKED ISSUE #44632: regression in Area2D monitoring which results in callbacks missing
**Godot version:** appears since 3.2.3 and still exists in head of 3.2 branch; 3.2.2 does **not** have this issue; I've done git bisect and it points at this commit, which does looks relevant: https://github.com/godotengine/godot/commit/ccdfaf24912c3c73a514e9ad8cba38c8b6a0a9b3

**Issue description:**
I noticed unexpected missing area_entered callbacks when playing around with Godot book example code from https://github.com/vnen/Godot-24-Hours/tree/master/Godot-Hour5/finished-project-with-exercises

I've narrowed down the issue to the attached repro project that doesn't need any human input to observe the issue.

There is whole bunch of stuff happening to the scene tree and the monitored areas in the project, which results in that sometimes the _on_player_area_entered callback is not called when asteroid's area enters player's area.

The scene is setup that player (i.e. ship) periodically spawns the shots that immediately queue_free() themselves - key here seems to be that they are spawned overlapping the ship's area. If shots do not overlap then there is no issue. Then asteroids are periodically spawned and move towards the ship. They are expected to trigger _on_player_area_entered, which then will draw an explosion around the ship. Before commit ccdfaf24912c3c73a514e9ad8cba38c8b6a0a9b3 it happens consistently for every asteroid. After commit ccdfaf24912c3c73a514e9ad8cba38c8b6a0a9b3 it does NOT happed for every asteroid.

**Steps to reproduce:**
Open attached project in 3.2.3 and hit play button. Observe that sometimes there is no explosion around the ship as asteroid hits it. For comparison, open it in 3.2.2 and observe that there is consistently an explosion around the ship as asteroids hit it.

**Minimal reproduction project:**
[repro-20201223.zip](https://github.com/godotengine/godot/files/5737195/repro-20201223.zip)

### PR DESCRIPTION
**Pull request by madmiraal**
Fixes #44632

### CODE REVIEW

File: servers/physics_2d/area_2d_sw.cpp [hunk 1]
```diff
@@ -215,7 +215,9 @@ void Area2DSW::call_queries() {
 
 		for (Map<BodyKey, BodyState>::Element *E = monitored_bodies.front(); E;) {
 			if (E->get().state == 0) { // Nothing happened
-				E = E->next();
+				Map<BodyKey, BodyState>::Element *next = E->next();
```
Comment (snaar) [inline servers/physics_2d/area_2d_sw.cpp:218]: What about moving these new 3 lines in front of the if statement and then removing duplicated lines below? Since you are erasing them every iteration now anyway.

File: servers/physics_2d/area_2d_sw.cpp [hunk 2]
```diff
@@ -215,7 +215,9 @@ void Area2DSW::call_queries() {
 
 		for (Map<BodyKey, BodyState>::Element *E = monitored_bodies.front(); E;) {
```
Comment (snaar) [inline servers/physics_2d/area_2d_sw.cpp:216]: Just to understand the logic for me here, the previous commit mentioned that you wanted to handle case where new monitored bodies/areas are added inside the callbacks. I'm not sure how various things in the engine work yet, so just want to learn something.

When new bodies are added while iteration is happening, do you expect them to be processed in the same iteration or next one? I.e. do you expect monitored_bodies to have elements remaining in case callbacks add more monitored bodies?

File: servers/physics_2d/area_2d_sw.cpp (hunk 1 above)
Comment (snaar) [reply servers/physics_2d/area_2d_sw.cpp:218]: I guess you'd have to change a bit more surrounding code then, so maybe not worth it.

Comment (madmiraal) [reply servers/physics_2d/area_2d_sw.cpp:218]: The problem is we can't assign `E` until we've erased it, and we can't erase `E` until we've extracted the information from it. We also don't want to extract the information from `E` if its `state` is 0. So at best we can move the assign `next` line before the `if` statement. However, I think it's clearer if the assigning `next` is kept close to assigning `E` to `next`, even if it means the line is duplicated later.

File: servers/physics_2d/area_2d_sw.cpp (hunk 2 above)
Comment (madmiraal) [reply servers/physics_2d/area_2d_sw.cpp:216]: It depends on the order they're processed in. If the body or area has already been processed, it will be processed again next time, if not, it will be processed in this iteration. The previous problem was, when they had already been processed, they were not being processed on the next iteration.

**Review by pouleyKetchoupp — APPROVED** [review]
Looks good!

**Comment by akien-mga** [comment]
Thanks!
