### PR TITLE
Fix some crashes, overflows and using variables without  values

### LINKED ISSUE #31140: Error -127 is outside the range of representable values of type 'unsigned char' in visual_server.cpp
**Godot version:**
3.2.dev.custom_build 7126654ea

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
logs
```
servers/visual_server.cpp:514:17: runtime error: -127 is outside the range of representable values of type 'unsigned char'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior servers/visual_server.cpp:514:17 in 
servers/visual_server.cpp:515:17: runtime error: -12.4482 is outside the range of representable values of type 'unsigned char'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior servers/visual_server.cpp:515:17 in 
servers/visual_server.cpp:513:17: runtime error: -2.42852 is outside the range of representable values of type 'unsigned char'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior servers/visual_server.cpp:513:17 in 
```
This code
https://github.com/godotengine/godot/blob/4188b0c139dc71b425528db97afdc1e54c2fb5b4/servers/visual_server.cpp#L512-L517
should probably look like a little above(uint_8 -> int_8)
https://github.com/godotengine/godot/blob/4188b0c139dc71b425528db97afdc1e54c2fb5b4/servers/visual_server.cpp#L477-L482
or clamp should have this values CLAMP(value,0,255)

### LINKED ISSUE #32723: Godot crashes when using AnimationNodeBlendSpace1D::remove_blend_point or AnimationNodeBlendSpace2D::remove_blend_point
**Godot version:**
3.2.alpha.custom_build. ed9fe4587
**OS/device including version:**
Ubuntu 19.04
**Issue description:**
Backtrace
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f0961be8f60] (??:0)
[2] HashMap<StringName, Object::Signal, HashMapHasherDefault, HashMapComparatorDefault<StringName>, (unsigned char)3, (unsigned char)8>::getptr(StringName const&) (/home/rafal/Pulpit/godot/./core/hash_map.h:314)
[3] Object::_disconnect(StringName const&, Object*, StringName const&, bool) (/home/rafal/Pulpit/godot/core/object.cpp:1517 (discriminator 2))
[4] Object::disconnect(StringName const&, Object*, StringName const&) (/home/rafal/Pulpit/godot/core/object.cpp:1513)
[5] AnimationNodeBlendSpace1D::remove_blend_point(int) (/home/rafal/Pulpit/godot/scene/animation/animation_blend_space_1d.cpp:160 (discriminator 4))
[6] MethodBind1<int>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:775 (discriminator 12))
[7] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:921 (discriminator 1))
[8] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1083 (discriminator 1))
[9] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1085)
[10] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1180)
[11] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[12] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[13] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[14] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[15] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:933)
[16] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:964)
[17] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:516 (discriminator 3))
[18] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1978)
[19] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3192)
[20] /usr/bin/godot(main+0x128) [0x13e361a] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:57)
[21] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f0961bcbb6b] (??:0)
[22] /usr/bin/godot(_start+0x2a) [0x13e343a] (??:?)
```
**Steps to reproduce:**
Read project manual - https://github.com/qarmin/The-worst-Godot-test-project#the-worst-godot-test-project
Run project
**Minimal reproduction project:**
[The-worst-Godot-test-project.zip](https://github.com/godotengine/godot/files/3714026/The-worst-Godot-test-project.zip)

### PR DESCRIPTION
**Pull request by qarmin**
Fixes #32723
Fixes #31140 - I checked and seems that src[i]. always(or almost) return value (-1;1) and uint_t was a typo

Added function uitos to String, to prevent overflow Core and Editor API

Added to VisualShaderNodeCubeMap, RayShape and VisualScript value to some variables to prevent spam every time I open editor(I usually open it with sanitizer support which show error when using variables without values)

In Image::shrink_x2 and FileAccessUnix::store_buffer checks  should prevent using null pointers

### CODE REVIEW

File: scene/resources/ray_shape.cpp [hunk 1]
```diff
@@ -90,6 +90,11 @@ void RayShape::_bind_methods() {
...
 
-	set_length(1.0);
-	set_slips_on_slope(false);
+	length = 1.0;
+	slips_on_slope = false;
+
+	_update_shape();
+	notify_change_to_owners();
+	_change_notify("length");
+	_change_notify("slips_on_slope");
```
Comment (akien-mga) [inline scene/resources/ray_shape.cpp]: There should be a comment to explain why the setter code is being duplicated here.

**Comment by akien-mga** [comment]
Thanks!
