### PR TITLE
Check PHashTranslation generate p_from is valid

### LINKED ISSUE #46001: Executing `PHashTranslation.new().generate(BoxShape)` crashes Godot
**Godot version:**
Godot 3.2.4 rc 2

**Issue description:**
Executing
```
var aa = BoxShape.new()
PHashTranslation.new().generate(aa)
```

crashes with backtrace
```
core/compressed_translation.cpp:49:26: runtime error: member call on null pointer of type 'const struct Translation'
core/compressed_translation.cpp:49:26: runtime error: member access within null pointer of type 'const struct Translation'
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] godots() [0x16f757a] (/mnt/Miecz/godot3.2/platform/x11/crash_handler_x11.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f6f4e264210] (??:0)
[3] PHashTranslation::generate(Ref<Translation> const&) (/mnt/Miecz/godot3.2/core/compressed_translation.cpp:49)
[4] MethodBind1<Ref<Translation> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/./core/method_bind.gen.inc:775 (discriminator 12))
[5] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/core/object.cpp:919 (discriminator 1))
[6] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/mnt/Miecz/godot3.2/core/variant_call.cpp:1129 (discriminator 1))
[7] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript_function.cpp:1089)
[8] GDScriptInstance::_ml_call_reversed(GDScript*, StringName const&, Variant const**, int) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript.cpp:1269)
[9] GDScriptInstance::call_multilevel_reversed(StringName const&, Variant const**, int) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript.cpp:1278)
[10] Node::_notification(int) (/mnt/Miecz/godot3.2/scene/main/node.cpp:152)
[11] Node::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/main/node.h:46 (discriminator 14))
[12] CanvasItem::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/2d/canvas_item.h:166 (discriminator 3))
[13] Node2D::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/2d/node_2d.h:38 (discriminator 3))
[14] Object::notification(int, bool) (/mnt/Miecz/godot3.2/core/object.cpp:931)
[15] Node::_propagate_ready() (/mnt/Miecz/godot3.2/scene/main/node.cpp:197)
[16] Node::_propagate_ready() (/mnt/Miecz/godot3.2/scene/main/node.cpp:186 (discriminator 2))
[17] Node::_set_tree(SceneTree*) (/mnt/Miecz/godot3.2/scene/main/node.cpp:2560)
[18] SceneTree::init() (/mnt/Miecz/godot3.2/scene/main/scene_tree.cpp:464)
[19] OS_X11::run() (/mnt/Miecz/godot3.2/platform/x11/os_x11.cpp:3628)
[20] godots(main+0x331) [0x16ee467] (/mnt/Miecz/godot3.2/platform/x11/godot_x11.cpp:57)
[21] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f6f4e2450b3] (??:0)
[22] godots(_start+0x2e) [0x16ee07e] (??:?)

```

### PR DESCRIPTION
**Pull request by MaxStgs**
Fixes #46001.

In this example **aa** is not valid reference for `Ref<Translation>` in this way we got null-value at **p_from**.
```
var aa = BoxShape.new()
PHashTranslation.new().generate(aa)
```

### CODE REVIEW

File: core/compressed_translation.cpp [hunk 1]
```diff
@@ -46,6 +46,7 @@ struct _PHashTranslationCmp {
 void PHashTranslation::generate(const Ref<Translation> &p_from) {
 #ifdef TOOLS_ENABLED
 	List<StringName> keys;
+	ERR_FAIL_COND(p_from.is_null());
```
Comment (akien-mga) [inline core/compressed_translation.cpp:49]: This should go before `List<StringName> keys;`.

**Comment by akien-mga** [comment]
This fix should also be done in the `master` branch (the file is `core/string/optimized_translation.cpp` there).

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

File: core/compressed_translation.cpp (hunk 1 above)
Comment (MaxStgs) [reply core/compressed_translation.cpp:48]: Can you explain why should it be done in these way? In my mind it is good solution because while we are reading function we are does not think about things that are does not need us right now(at this line or few later) but in this situation I has been confused because we use this in "few later".

Comment (akien-mga) [reply core/compressed_translation.cpp:48]: It was not "wrong" initially but the code is more readable this way, and avoids needlessly allocating memory in the case where we would trigger an error:

- First we check that the parameter is valid. If not, there's nothing to do so we should return right away.
- If the parameter is valid, then we can proceed with the normal logic: create a `List`, fill it, etc.

Sometimes it does make sense to do an `ERR_FAIL_COND` check before the first use of what needs to be validated before de-referencing, but here an invalid `p_from` means that the whole method is useless, so it's cleaner to return as early as possible.

Sometimes we might have situations like this:

```
void some_func(const Ref<T> &p_arg) {
    // do some very expensive calculations which don't use p_arg, and don't impact the global state.
    Variant local_var = ...;
    ERR_FAIL_NULL(p_arg);
    p_arg->some_method(local_var);
```

If we put the error before `p_arg`, we would calculate the expensive `local_var` stuff needlessly.

Comment (MaxStgs) [reply core/compressed_translation.cpp:48]: Okay. Thank you.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.1.
