### PR TITLE
Delegate handling `mouse_mode` to the `DisplayServer`

### LINKED ISSUE #100758: [Web] Input.mouse_mode returns wrong value
### Tested versions

- Reproducible in v4.4.dev4.official [36e6207bb]
- Reproducible in v4.4.dev7.official [46c8f8c5c]
- Not reproducible in v4.4.dev3.official [f4af8201b]

### System information

Godot v4.4.dev4 - CachyOS Linux #1 SMP PREEMPT_DYNAMIC Thu, 19 Dec 2024 21:23:18 +0000 on Wayland - X11 display driver, Multi-window, 1 monitor - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 2070 SUPER (nvidia; 565.77) - Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 threads), Web export tested under Firefox 133.0.3 (64-bit)

### Issue description

In **web exports** `Input.mouse_mode` sometimes returns `MouseMode.MOUSE_MODE_VISIBLE` despite setting it to `MouseMode.MOUSE_MODE_CAPTURED` and behaving like it is captured.

### Steps to reproduce

1. open "Window Management" from [official demo projects](https://github.com/godotengine/godot-demo-projects/tree/master/misc/window_management)
2. add web export, run the project in browser (Remote Debug)
3. click on the MOUSE_MODE_CAPTURED button or press <kbd>F3</kbd>
4. Extra hints should appear below all the MouseModes buttons:

> ESC: Deactivate MOUSE_MODE_CAPTURED
> W, S: Move forward, backward
> A, D: Strafe left, right

At least they do in v4.4.dev3 but not in v4.4.dev4 anymore since the condition `Input.get_mouse_mode() == Input.MOUSE_MODE_CAPTURED` evaluates to `false`.

There is a case, when this evaluates to `true`:
1. run the project in browser anew or refresh the page
2. click somewhere inside the window, on the cube for example
3. press <kbd>F3</kbd>, <kbd>F1</kbd>, <kbd>F3</kbd> in that order.
4. Notice extra hints being shown also in `v4.4.dev4` or `v4.4.dev7`
 

### Minimal reproduction project (MRP)

"Window Management" official demo project (https://github.com/godotengine/godot-demo-projects/tree/master/misc/window_management)

### PR DESCRIPTION
**Pull request by adamscott**
This PR delegates from `Input` to the `DisplayServer` the task of handling `mouse_mode` and its override. (it was more or less the behavior before #97257)

`Input` was caching the result of `mouse_mode`, expecting that setting the mouse mode was synchronous on all platforms. As it isn't on the Web, it created some issues.

See [the discussion](https://chat.godotengine.org/channel/core?msg=bLJJC9vLjjtAH58kY) about the fix and why the mouse mode can't be cached and why we shouldn't make (for now) async handlers.

This PR also adds `MOUSE_MODE_MAX` and various index checks.

Fixes #100758
Supersedes #101849

### CODE REVIEW

File: core/input/input.cpp [hunk 1]
```diff
@@ -77,6 +77,8 @@ Input *Input::singleton = nullptr;
 
 void (*Input::set_mouse_mode_func)(Input::MouseMode) = nullptr;
 Input::MouseMode (*Input::get_mouse_mode_func)() = nullptr;
+void (*Input::set_mouse_mode_override_func)(Input::MouseMode) = nullptr;
+void (*Input::set_mouse_mode_override_enabled_func)(bool) = nullptr;
 void (*Input::warp_mouse_func)(const Vector2 &p_position) = nullptr;
 Input::CursorShape (*Input::get_current_cursor_shape_func)() = nullptr;
 void (*Input::set_custom_mouse_cursor_func)(const Ref<Resource> &, Input::CursorShape, const Vector2 &) = nullptr;
```
Comment (bruvzg) [inline core/input/input.cpp:84]: Is there any reason why these are using separate function pointers and wrappers in the `DisplayServer`, instead of calling `DisplayServer::get_singleton()->mouse_???_mode`?

File: servers/display_server.h [hunk 2]
```diff
@@ -280,10 +282,13 @@ class DisplayServer : public Object {
 		MOUSE_MODE_CAPTURED,
 		MOUSE_MODE_CONFINED,
 		MOUSE_MODE_CONFINED_HIDDEN,
+		MOUSE_MODE_MAX,
 	};
 
 	virtual void mouse_set_mode(MouseMode p_mode);
 	virtual MouseMode mouse_get_mode() const;
+	virtual void mouse_set_mode_override(MouseMode p_mode);
+	virtual void mouse_set_mode_override_enabled(bool p_enabled);
```
Comment (bruvzg) [inline servers/display_server.h:291]: `mouse_get/set_mode` mode are exposed to scripting, so these probably should be as well.

**Review by bruvzg — COMMENTED** [review]
Seems to be working as expected.

File: servers/display_server.h (hunk 2 above)
Comment (YeldhamDev) [reply servers/display_server.h:291]: Don't think so. This is used by the Game view when using the free camera override in 3D to hide the cursor, the user shouldn't be playing around with it.

File: core/input/input.cpp (hunk 1 above)
Comment (adamscott) [reply core/input/input.cpp:84]: That's a great question.

Comment (bruvzg) [reply core/input/input.cpp:84]: I guess this might be to avoid including headers from the `servers` in the `core`.

**Review by Repiteo — DISMISSED** [review]
Missing documentation for the new binds.

**Comment by adamscott** [comment]
I realized that I forgot to add some functions, such as `get_mouse_mode_override()` and `is_mouse_mode_override_enabled()`.

I removed bindings with ClassDB for the mouse_mode_override stuff, following the same reasoning as @YeldhamDev found here: https://github.com/godotengine/godot/pull/101924#discussion_r1926545334

@bruvzg, I think we could expose these methods if people really have good arguments. But there's no urgency, IMHO.

**Review by Calinou — APPROVED** [review]
Tested locally on Windows 11 24H2 on https://github.com/godotengine/godot-demo-projects/tree/master/misc/window_management, it works as expected. Code looks good to me.

**Comment by Sauermann** [comment]
Moving `mouse_mode` to the display server is a good idea. The concept is based solely on display server ideas and I don't see any reason for keeping it in Input.
I suggest to move it completely from Input to DisplayServer when compatibiliy breaking changes can be made.

I have noticed other DisplayServer functions, that are accessible from Input, which should in my opinion also be removed from Input (e.g.: `Input::warp_mouse`).

File: core/input/input.h [hunk 3]
```diff
@@ -53,6 +53,7 @@ class Input : public Object {
 		MOUSE_MODE_CAPTURED,
 		MOUSE_MODE_CONFINED,
 		MOUSE_MODE_CONFINED_HIDDEN,
+		MOUSE_MODE_MAX,
 	};
```
Comment (bruvzg) [inline core/input/input.h:57]: Since this can't be directly linked to `DisaplyServer` header, it might be worth adding `// Keep synced with "DisplayServer::MouseMode" enum.` comment.

File: servers/display_server.h [hunk 4]
```diff
@@ -280,10 +284,15 @@ class DisplayServer : public Object {
 		MOUSE_MODE_CAPTURED,
 		MOUSE_MODE_CONFINED,
 		MOUSE_MODE_CONFINED_HIDDEN,
+		MOUSE_MODE_MAX,
```
Comment (bruvzg) [inline servers/display_server.h:287]: Or linking it in the opposite way, since `Input` is already include here:

```
		MOUSE_MODE_VISIBLE = Input::MOUSE_MODE_VISIBLE,
		MOUSE_MODE_HIDDEN = Input::MOUSE_MODE_HIDDEN,
		MOUSE_MODE_CAPTURED = Input::MOUSE_MODE_CAPTURED,
		MOUSE_MODE_CONFINED = Input::MOUSE_MODE_CONFINED,
		MOUSE_MODE_CONFINED_HIDDEN = Input::MOUSE_MODE_CONFINED_HIDDEN,
		MOUSE_MODE_MAX = Input::MOUSE_MODE_MAX,
```

**Review by bruvzg — APPROVED** [review]

File: core/input/input.h (hunk 3 above)
Comment (adamscott) [reply core/input/input.h:57]: I followed your next suggestion.

File: servers/display_server.h (hunk 4 above)
Comment (adamscott) [reply servers/display_server.h]: Done!

File: core/input/input.h (hunk 3 above)
Comment (adamscott) [reply core/input/input.h:57]: Well, I'll do both.

**Comment by Repiteo** [comment]
Thanks!

**Comment by FeralBytes** [comment]
@adamscott please see my newest comment on #100758 when you have time.
