### PR TITLE
[Windows] Implement OneCore TTS support using C++/WinRT (no deps).

### LINKED ISSUE #69788: DisplayServer tts_get_voices() does not load all installed voices on Windows
### Godot version

4.0 beta 7

### System information

Windows 10

### Issue description

The current implementation of tts_get_voices seems to only load voices that are referenced inside the registry under

"Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens"

But many of windows voices are located under:

"Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens"

Providing the path to these voices to tts_speak however, doesnt seem to work at the moment...

### Steps to reproduce

Call tts_get_voices() and compare it to your installed voices and registry

### Minimal reproduction project

[TTS_Bug.zip](https://github.com/godotengine/godot/files/10191015/TTS_Bug.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/69788

Alternative version of https://github.com/godotengine/godot/pull/116126, without bundled dependencies, WinRT part is optional and can be downloaded using script (MinGW only, MSVC always has it).

### CODE REVIEW

File: platform/windows/tts_driver.h [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
+/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
+/**************************************************************************/
+
+#pragma once
+
+#include "core/string/ustring.h"
+#include "core/variant/array.h"
+
+#include "core/object/object.h"
```
Comment (AThousandShips) [inline platform/windows/tts_driver.h]:
```suggestion
```

**Review by akien-mga — APPROVED** [review]
Looks great to me.
Likely needs a rebase to handle clang-format/include changes.
