### PR TITLE
Fix editor shortcuts overrides overwriting user configured shortcuts.

### LINKED ISSUE #61468: Pressing Option + 4 to enter `$` opens asset library tab on macOS
### Godot version

4.0 beta8

### System information

MacOS Monterey Radeon Pro 555 2 GB

### Issue description

When I press Option+4 for the $ character in the script editor in the engine, it switches to the asset library window. I delete this shortcut from Editor->Editor Settings->Shortcuts, when I restart the editor, the old shortcut comes back. Doesn't save shortcuts

### Steps to reproduce

Go to Editor -> Editor Settings -> Shortcuts
Type Open Asset Library in the search box.
Delete the shortcut with the X icon. Restart the engine. You'll see it's back to the way it was

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes #61468

### CODE REVIEW

File: editor/editor_settings.cpp [hunk 1]
```diff
@@ -1475,7 +1475,10 @@ void ED_SHORTCUT_OVERRIDE_ARRAY(const String &p_path, const String &p_feature, c
 	}
 
 	// Directly override the existing shortcut.
-	sc->set_events(events);
+	if (Shortcut::is_event_array_equal(sc->get_events(), sc->get_meta("original"))) {
+		sc->set_events(events);
+	}
```
Comment (akien-mga) [inline editor/editor_settings.cpp:1480]: Might warrant adding a comment.
```suggestion
	// Override the existing shortcut only if it wasn't customized by the user (i.e. still "original").
	if (Shortcut::is_event_array_equal(sc->get_events(), sc->get_meta("original"))) {
		sc->set_events(events);
	}
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
