### PR TITLE
Resource UID fixes and improvements

### LINKED ISSUE #99221: Image loading is broken in editor
### Tested versions

- Reproducible in master: v4.4.dev.custom_build [76fa7b291]
- Not reproducible in v4.4.dev4

### System information

Windows 11

### Issue description

I am cannot load images in editor.
I tried setting adaptive icons in android export and boot splash in project setting, both failed with similar error: `load_image: Error opening file 'uid://bjaelxrg45jgj'`

### Steps to reproduce

- Go to project settings
- Set a boot splash image (clear it if already set and select again)
- Run your project and see error in debugger.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by KoBeWi**
- Added new static helper methods to ResourceUID
  - `uid_to_path(uid)` - converts `uid://` to `res://`
  - `path_to_uid(path)` - opposite of the above
  - `ensure_path(uid_or_path)` - returns a path, converts UID when necessary
- Fixed #99221

In a follow-up I plan to make use of the helper methods where applicable.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by reduz** [comment]
copy/paste from what I wrote on RC:

I think UIDs should only be for resource loading, not the file access
IMO the more we can separate the resource layer from the file layer the best
As technically vast majority of users should be fine using only the resource layer





plus doc should be changed in FileAccess and DirAccess that the resource layer should be used instead unless specifically needed

File: core/io/file_access.cpp [hunk 1]
```diff
@@ -71,7 +71,7 @@ void FileAccess::_set_access_type(AccessType p_access) {
 
 Ref<FileAccess> FileAccess::create_for_path(const String &p_path) {
 	Ref<FileAccess> ret;
-	if (p_path.begins_with("res://")) {
+	if (p_path.begins_with("res://") || p_path.begins_with("uid://")) {
```
Comment (reduz) [inline core/io/file_access.cpp:74]: I really think file layer should have nothing to do with UIDs, the extentof UIDs should be only resources.

File: core/io/image.cpp [hunk 2]
```diff
@@ -2611,23 +2611,25 @@ Image::AlphaMode Image::detect_alpha() const {
 }
 
 Error Image::load(const String &p_path) {
+	String path = ResourceUID::ensure_path(p_path);
 #ifdef DEBUG_ENABLED
-	if (p_path.begins_with("res://") && ResourceLoader::exists(p_path)) {
```
Comment (reduz) [inline core/io/image.cpp:2615]: This function is kind of tricky, but I think if you supply an UID it should just not work.

Comment (KoBeWi) [reply core/io/image.cpp:2615]: See the linked issue.
The expectation is different apparently.

**Comment by KoBeWi** [comment]
Removed the FileAccess change.

**Comment by Repiteo** [comment]
Thanks!
