### PR TITLE
Fixes popup_centered_* methods, dialogs with wrong sizes and visual script editor

### LINKED ISSUE #16069: "popup_centered_minsize" doesn't center the popup
**Godot version:**
0181681

**Issue description:**
When showing a popup using the `popup_centered_minsize` method, the popup will not be correctly centered. Here is a image with a centered button used to trigger it:
screenshot1

### LINKED ISSUE #18940: GUI Control sizing/positioning initially incorrect
**Godot version:**
e62e7fd768467aad9452cacf7331caee7f730020

**Issue description:**
Several parts of my UI/menu screens are now placed/sized incorrectly.
In most cases it appears to be containers being sized as if they have no contents, but I'm not sure at the moment.

Similar problems can be seen in a couple of places in the editor UI:

In the project settings, the first time you select a property with a horizontal slider, the slider appears lower down. Reselecting it will put the slider in the right place.
project_properties

On the Help->About screen, the details do not appear on the first three tabs (Authors, Donors and License) until the tab is visited a second time. I suspect part of the UI is being sized as if it was empty.
The content of the Thirdparty License tab overflows its parent the first time it's viewed:
about_page_overflow

The smallest related example I've found so far is Popup.popup_centered() will position the popup incorrectly the first time. The top left of the popup will be in the center of the screen.
See example project below:

**Minimal reproduction project:**
[gui_testing.zip](https://github.com/godotengine/godot/files/2010455/gui_testing.zip)
Press 'p' for the popup. Note the first time it appears it is not correctly centered.

### LINKED ISSUE #19267: Visual Script Editor is broken since the new Inspector
**Godot version:**
Godot Master

**Issue description:**
As you can see that the VS editor is now broken. Made this issue just to remind people of the issue. So that it's not forgotten for long.

image

### LINKED ISSUE #19292: Popup spawned from EditorPlugin has size (0,0)
**Godot version:**
10cab25

**Issue description:**
Sometime between the build specified and one from about a week ago (sorry, don't know the exact commit!), the popup in my plugin now seems to spawn into the editor with an incorrect size.  It's launched nearly immediately after activating the plugin, using popup_centered().  No min size set, default rect size of (800,480).  Perhaps one of the recent tweaks to make sure certain UI elements don't fly out of bounds are responsible?

image

**Steps to reproduce:**
Make an EditorPlugin spawn a popup of a certain expected size.  (Toss some controls on it to see what's going on maybe)

### LINKED ISSUE #19441: Wrong minimum size of Control node
**Godot version:**

3.1.dev f35115309

**OS/device including version:**

not related

**Issue description:**

Wrong minimum size of Control node.

**Steps to reproduce:**
master

comparing to 3.0.2 official

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by guilhermefelipecgs**
Fix #16069, Fix #19292, Fix #19267, Fix #18940.

- Fix slider in the project settings; 
- Fix all tabs in about dialog ~**except for the licence thirdparty**~ (Fixed now, the problem was caused by label autowrap with zero width. fix [here](https://github.com/godotengine/godot/pull/19334/files#diff-406898b6f6403046f6e22a8aba832784R191));
- Fix `popup_centered` incorrectly positioned the first time.
- Fix assetlib dialogs not resizing when preview texture is updated (https://github.com/godotengine/godot/issues/18940#issuecomment-389638767)]

This pr also fix batch rename dialog with wrong size in the first time it appears.

Edit:
Fix this https://github.com/godotengine/godot/pull/19188#issuecomment-394847634 too.

Edit2:
Fix #19441.

### CODE REVIEW

File: scene/gui/control.cpp [hunk 1]
```diff
@@ -452,10 +453,8 @@ void Control::_notification(int p_notification) {
 
 		} break;
 		case NOTIFICATION_POST_ENTER_TREE: {
```
Comment (guilhermefelipecgs) [inline scene/gui/control.cpp]: @reduz Can I remove `NOTIFICATION_POST_ENTER_TREE`? this is used only here then I don't know why do you create this. I can move this two lines above to `NOTIFICATION_ENTER_TREE`.

Comment (guilhermefelipecgs) [reply scene/gui/control.cpp]: See here: https://github.com/godotengine/godot/search?q=NOTIFICATION_POST_ENTER_TREE&unscoped_q=NOTIFICATION_POST_ENTER_TREE

Comment (reduz) [reply scene/gui/control.cpp]: No, because computing size with out of tree controls should never happen, and children nodes receive that notification after the parent, so for cases like this it's needed.

Comment (guilhermefelipecgs) [reply scene/gui/control.cpp]: Ok, makes sense, thanks for explain. :+1:

**Comment by guilhermefelipecgs** [comment]
I discovered how to fix the last issue about "licence thirdparty".
