### PR TITLE
Apply `set_read_only()` to child classes of `EditorProperty` elements

### LINKED ISSUE #45769: set_read_only() in EditorProperties doesn't work correctly
**Godot version:**
4.0

**OS/device including version:**
All

**Issue description:**
There are extended class of EditorProperty such as `EditorPropertyVectorXXX` that has multiple `SpinBoxes` for `Vector2`, `Vector3`, etc.
As you can see in editor_propaties.cpp, `set_read_only()` does not make sense because `set_read_only()` does not propagate to all properties that the EditorProperties class has.

### PR DESCRIPTION
**Pull request by TokageItLab**
Fixed #45769.

The `read_only` flag is in `EditorProperty`, so you can use it in the child classes of `EditorProperty`. According to the [description](https://docs.godotengine.org/ja/stable/classes/class_editorproperty.html#class-editorproperty-property-read-only), the `read_only` flag prevents operations in the inspector. However, if you don't set `read_only` for each GUI element implemented in the child class, they can manipulate the value in the inspector even if `read_only == true`.

Currently, it seems that the `read_only` flag is not commonly used, but for example, in #45699, it is necessary that `read_only` works correctly to prevent handling BonePose in RestMode. Also, the `read_only` flag can only be set in C++ currently, but it may be used in GDScript in the future with some way. So I fixed this.

https://user-images.githubusercontent.com/61938263/129532740-8c7fdd61-aad8-407b-a91e-ce834507b924.mov

### CODE REVIEW

File: scene/gui/check_box.cpp [hunk 1]
```diff
@@ -34,9 +34,7 @@
 
 Size2 CheckBox::get_icon_size() const {
 	Ref<Texture2D> checked = Control::get_theme_icon(SNAME("checked"));
-	Ref<Texture2D> checked_disabled = Control::get_theme_icon(SNAME("checked_disabled"));
 	Ref<Texture2D> unchecked = Control::get_theme_icon(SNAME("unchecked"));
-	Ref<Texture2D> unchecked_disabled = Control::get_theme_icon(SNAME("unchecked_disabled"));
```
Comment (KoBeWi) [inline scene/gui/check_box.cpp:39]: Instead of removing these lines, it's better to handle them properly below.

Comment (TokageItLab) [reply scene/gui/check_box.cpp]: Sure, I fixed it. Since there are so many of them, I changed it to iterate, but is this okay for null checking?
```cpp
Size2 CheckBox::get_icon_size() const {
	Vector<Ref<Texture2D>> icons;
	icons.push_back(Control::get_theme_icon(SNAME("checked")));
	icons.push_back(Control::get_theme_icon(SNAME("unchecked")));
	icons.push_back(Control::get_theme_icon(SNAME("radio_checked")));
	icons.push_back(Control::get_theme_icon(SNAME("radio_unchecked")));
	icons.push_back(Control::get_theme_icon(SNAME("checked_disabled")));
	icons.push_back(Control::get_theme_icon(SNAME("unchecked_disabled")));
	icons.push_back(Control::get_theme_icon(SNAME("radio_checked_disabled")));
	icons.push_back(Control::get_theme_icon(SNAME("radio_unchecked_disabled")));

	Size2 tex_size = Size2(0, 0);
	for (int i = 0; i < icons.size(); ++i) {
		if (icons[i].is_null()) {
			continue;
		}
		tex_size = Size2(MAX(tex_size.width, icons[i]->get_width()), MAX(tex_size.height, icons[i]->get_height()));
	}
	return tex_size;
}
```

Comment (KoBeWi) [reply scene/gui/check_box.cpp]: Yeah it's ok. But I'm concerned with performance of this approach. AFAIK pushing to Vector will re-allocate memory and `get_icon_size()` is a method that might be called relatively often. It would be better if you resized the Vector beforehand and assigned the icons for each index. Or you could use LocalVector, but I'm not sure how it works exactly.

Comment (TokageItLab) [reply scene/gui/check_box.cpp:39]: You have a point. It will look redundant, but I reverted to the original style for performance reasons.

File: editor/editor_properties.cpp [hunk 2]
```diff
@@ -328,12 +345,24 @@ EditorPropertyTextEnum::EditorPropertyTextEnum() {
...
+		return;
+	}
 	emit_changed(get_edited_property(), p_path);
 	update_property();
 }
 
 void EditorPropertyPath::_path_pressed() {
+	if (is_read_only()) {
+		return;
+	}
```
Comment (KoBeWi) [inline editor/editor_properties.cpp:365]: Will this ever be called when the property is disabled? The button is disabled, so it can't emit the signal connected to this method.

File: editor/editor_properties.cpp [hunk 3]
```diff
@@ -328,12 +345,24 @@ EditorPropertyTextEnum::EditorPropertyTextEnum() {
...
+void EditorPropertyPath::set_read_only(bool p_read_only) {
+	path->set_editable(!p_read_only);
+	path_edit->set_disabled(p_read_only);
+	EditorProperty::set_read_only(p_read_only);
+};
+
 void EditorPropertyPath::_path_selected(const String &p_path) {
+	if (is_read_only()) {
+		return;
+	}
```
Comment (KoBeWi) [inline editor/editor_properties.cpp:357]: This can only happen when the property gets disabled while the dialog is visible, which is very unlikely.

File: editor/editor_properties.cpp [hunk 4]
```diff
@@ -628,6 +678,13 @@ EditorPropertyEnum::EditorPropertyEnum() {
 
 ///////////////////// FLAGS /////////////////////////
 
+void EditorPropertyFlags::set_read_only(bool p_read_only) {
+	for (int i = 0; i < flags.size(); i++) {
```
Comment (KoBeWi) [inline editor/editor_properties.cpp:682]: You can use `for (Checkbox *check : flags)`.

File: editor/editor_properties.cpp [hunk 5]
```diff
@@ -936,6 +993,11 @@ class EditorPropertyLayersGrid : public Control {
 	}
 };
 
+void EditorPropertyLayers::set_read_only(bool p_read_only) {
+	button->set_disabled(p_read_only);
+	EditorProperty::set_read_only(p_read_only);
+};
```
Comment (KoBeWi) [inline editor/editor_properties.cpp:999]: This is not enough to disable this control, there's still the grid of clickable buttons.

**Comment by KoBeWi** [comment]
Disabled properties should have revert arrow unavailable probably.

File: editor/editor_properties.cpp [hunk 6]
```diff
@@ -1198,6 +1275,11 @@ EditorPropertyFloat::EditorPropertyFloat() {
 
 ///////////////////// EASING /////////////////////////
 
+void EditorPropertyEasing::set_read_only(bool p_read_only) {
+	spin->set_read_only(p_read_only);
+	EditorProperty::set_read_only(p_read_only);
+};
```
Comment (KoBeWi) [inline editor/editor_properties.cpp:1281]: This doesn't seem to have any effect, the `spin` is still editable after it appears. Might be some bug.

But there is another thing. The curve box is still editable. You should probably ignore the input if the property is readonly. This will also fix the spin slider problem, because it will never appear.

File: editor/editor_properties.cpp (hunk 2 above)
Comment (TokageItLab) [reply editor/editor_properties.cpp:365]: I remember that `path_selected` was checked `is_read_only()` because the event fired even after the button was disabled. Rather, check why the event fires and I should probably fix that one.

File: editor/editor_properties.cpp (hunk 3 above)
Comment (TokageItLab) [reply editor/editor_properties.cpp:357]: same above

File: editor/editor_spin_slider.cpp [hunk 7]
```diff
@@ -243,7 +246,7 @@ void EditorSpinSlider::_draw_spin_slider() {
 
 	int vofs = (size.height - font->get_height(font_size)) / 2 + font->get_ascent(font_size);
 
-	Color fc = get_theme_color(SNAME("font_color"), SNAME("LineEdit"));
+	Color fc = is_read_only() ? get_theme_color(SNAME("font_uneditable_color"), SNAME("LineEdit")) : get_theme_color(SNAME("font_color"), SNAME("LineEdit"));
```
Comment (KoBeWi) [inline editor/editor_spin_slider.cpp:249]:
```suggestion
	Color fc = get_theme_color(is_read_only() ? SNAME("font_uneditable_color") : SNAME("font_color"), SNAME("LineEdit"));
```
Just like above.

File: editor/editor_properties.cpp (hunk 2 above)
Comment (TokageItLab) [reply editor/editor_properties.cpp:365]: I didn't input the value for setup properly when testing, so it seems that another factor was causing the crash. So I think it's OK to omit it.

**Comment by TokageItLab** [comment]
The revert button is now hidden when `is_read_only()==true`.

As for LayerGrid and Ease, the input processing is implemented in `editor_properties.cpp`, soI change the input processing is controlled by the value of `is_read_only()`.

> Also I don't see any way to disable selected properties, only whole inspector can be disabled. This would be useful.

I think it is necessary to separate methods such as `is_all_read_only()` and `is_read_only(idx)` in order to control them separately. What do you think?

The rest is a matter of design. As for Easing, I used `font_uneditable_color` for the number value color, but the line color is not changed. The base color of the LayerGrid should also be changed. I think it is debatable.

File: editor/editor_properties.cpp [hunk 8]
```diff
@@ -712,6 +764,14 @@ class EditorPropertyLayersGrid : public Control {
 	Vector<String> names;
 	Vector<String> tooltips;
 
+	void set_read_only(bool p_read_only) {
+		read_only = p_read_only;
+	}
+
+	bool is_read_only() {
+		return read_only;
+	}
```
Comment (KoBeWi) [inline editor/editor_properties.cpp:773]: This method is not necessary, as the readonly is checked only internally in this class. Thus you could just do `if (read_only)`.

File: editor/editor_spin_slider.cpp [hunk 9]
```diff
@@ -222,6 +222,9 @@ void EditorSpinSlider::_draw_spin_slider() {
 	Vector2 size = get_size();
 
 	Ref<StyleBox> sb = get_theme_stylebox(SNAME("normal"), SNAME("LineEdit"));
+	if (is_read_only()) {
+		sb = get_theme_stylebox(SNAME("read_only"), SNAME("LineEdit"));
+	}
```
Comment (KoBeWi) [inline editor/editor_spin_slider.cpp:227]: Why didn't you use `? :` like everywhere else?

**Comment by KoBeWi** [comment]
> I think it is necessary to separate methods such as is_all_read_only() and is_read_only(idx) (also set_read_only()) in order to control them separately. What do you think about it?

After second though, `set_read_only()` is the method to disable property, bruh. The problem is that the inspector will overwrite all properties' readonly state inside `update_tree()`. The only solution I can think of is for EditorProperty to have a "global" readonly flag (set by inspector) and internal one. The property would be readonly if either of them is true.

File: doc/classes/EditorProperty.xml [hunk 10]
```diff
@@ -50,13 +50,34 @@
 				Must be implemented to provide a custom tooltip to the property editor.
 			</description>
 		</method>
+		<method name="is_read_only">
+			<return type="bool" />
+			<description>
+				If either [code]global_read_only[/code] or [code]read_only[/code] is [code]true[/code], returns [code]true[/code].
```
Comment (KoBeWi) [inline doc/classes/EditorProperty.xml:56]:
```suggestion
				Returns [code]true[/code] if either [code]global_read_only[/code] or [code]read_only[/code] is [code]true[/code].
```
(this is more consistent with how such methods are usually documented)

File: doc/classes/EditorProperty.xml [hunk 11]
```diff
@@ -50,13 +50,34 @@
...
 			<description>
 				Puts the [code]editor[/code] control below the property label. The control must be previously added using [method Node.add_child].
 			</description>
 		</method>
+		<method name="set_global_read_only">
+			<return type="void" />
+			<argument index="0" name="read_only" type="bool" />
+			<description>
+				Used by the inspector, set to [code]true[/code] when the property is read-only.
+				Note: The inspector will set all property to readonly by iterating, so if you want to set property to readonly individually, use [method set_read_only].
```
Comment (KoBeWi) [inline doc/classes/EditorProperty.xml:71]:
```suggestion
				[b]Note[/b]: The inspector will set all property to readonly by iterating, so if you want to set property to readonly individually, use [method set_read_only].
```

**Comment by TokageItLab** [comment]
@KoBeWi I got it right, I was mislead to think that you want to readonly `x` in `Vector3` for example yesterday.
After rethinking, I've implemented `global_read_only` for the problem of the inspector overwriting all properties in update, please check if I'm understanding it correctly. So, I've split the commit for that, but I will squash it in final.

**Comment by KoBeWi** [comment]
Yeah, it's good now.

Although the `_set_read_only()` method being empty is rather meh. We could bind a virtual method  (with `BIND_VMETHOD`) and call it:
```C++
void EditorProperty::_set_read_only(bool p_read_only) {
	if (get_script_instance() && get_script_instance()->has_method("_set_read_only")) {
		get_script_instance()->call("_set_read_only", p_type);
	}
}
```
This way the behavior could be customized from plugins. (and it also means that you'd need to restore the base method calls...)

Also the method should be `protected`.

File: editor/editor_inspector.cpp [hunk 12]
```diff
@@ -901,6 +913,8 @@ void EditorProperty::_bind_methods() {
 	ClassDB::bind_method(D_METHOD("set_label", "text"), &EditorProperty::set_label);
 	ClassDB::bind_method(D_METHOD("get_label"), &EditorProperty::get_label);
 
+	ClassDB::bind_method(D_METHOD("_set_read_only", "read_only"), &EditorProperty::_set_read_only);
```
Comment (KoBeWi) [inline editor/editor_inspector.cpp:916]: It should be
`BIND_VMETHOD(MethodInfo("_set_read_only", PropertyInfo(Variant::BOOL, "readonly"))`
and after all methods.

File: editor/editor_inspector.cpp [hunk 13]
```diff
@@ -901,6 +913,8 @@ void EditorProperty::_bind_methods() {
...
+	ClassDB::bind_method(D_METHOD("set_global_read_only", "read_only"), &EditorProperty::set_global_read_only);
```
Comment (KoBeWi) [inline editor/editor_inspector.cpp:917]: This method is meant to be used only by the inspector, so I'd remove the binding.

File: editor/editor_properties.h [hunk 14]
```diff
@@ -62,6 +62,7 @@ class EditorPropertyText : public EditorProperty {
 	static void _bind_methods();
 
 public:
+	virtual void _set_read_only(bool p_read_only) override;
```
Comment (KoBeWi) [inline editor/editor_properties.h:65]: This should be in `protected` field (next to `_bind_methods()`). Same in all classes.

File: doc/classes/EditorProperty.xml [hunk 15]
```diff
@@ -50,13 +57,26 @@
...
 			<argument index="0" name="editor" type="Control" />
 			<description>
 				Puts the [code]editor[/code] control below the property label. The control must be previously added using [method Node.add_child].
 			</description>
 		</method>
+		<method name="set_read_only">
+			<return type="void" />
+			<argument index="0" name="read_only" type="bool" />
+			<description>
+				Set the property to read-only with calling [method _set_read_only].
```
Comment (KoBeWi) [inline doc/classes/EditorProperty.xml:77]: I'd change it to something like
```suggestion
				If [code]true[/code], the property can't be edited.
```

File: doc/classes/EditorProperty.xml [hunk 16]
```diff
@@ -9,6 +9,13 @@
 	<tutorials>
 	</tutorials>
 	<methods>
+		<method name="_set_read_only" qualifiers="virtual">
+			<return type="void" />
+			<argument index="0" name="readonly" type="bool" />
+			<description>
+				This virtual function make all items uneditable which may be manipulated by the user in the inspector.
```
Comment (KoBeWi) [inline doc/classes/EditorProperty.xml:16]:
```suggestion
				Called when the property's [code]read_only[/code] state changes. Override this method to disable or enable underlying controls.
```

**Review by KoBeWi — APPROVED** [review]
Seems all good now. Though needs a review from @groud before merging.

**Comment by TokageItLab** [comment]
@KoBeWi Thank you for all your help!

File: editor/editor_inspector.cpp [hunk 17]
```diff
@@ -382,12 +382,24 @@ void EditorProperty::update_property() {
 	GDVIRTUAL_CALL(_update_property);
 }
 
+void EditorProperty::_set_read_only(bool p_read_only) {
```
Comment (groud) [inline editor/editor_inspector.cpp:385]: I think this is pointless. I believe it might make sense to have this as the base implementation (in the EditorProperty class itself), but there no point in having it in all children classes. You should simply override `set_read_only(bool p_read_only)` on the children classes. 

Most functions in the engine don't check for scripts for performance reason, we only expose the ones that have a clear use case.

File: editor/editor_inspector.cpp [hunk 18]
```diff
@@ -382,12 +382,24 @@ void EditorProperty::update_property() {
...
+	if (get_script_instance() && get_script_instance()->has_method("_set_read_only")) {
+		get_script_instance()->call("_set_read_only", p_read_only);
+	}
+}
+
+void EditorProperty::set_global_read_only(bool p_read_only) {
```
Comment (groud) [inline editor/editor_inspector.cpp:391]: No, this does not make a lot of sense, it's not up the EditorProperty class to handle something that's part of the EditorInspector.

It's up to the EditorInspector itself to handle this, setting all children EditorProperty to read_only when the inspector itself is set to read_only, or only the correct ones when it's not.

**Review by groud — CHANGES_REQUESTED** [review]

File: editor/editor_inspector.cpp (hunk 18 above)
Comment (TokageItLab) [reply editor/editor_inspector.cpp:391]: If there is only one flag, it is not possible to decide whether it is readonly by the inspector or property itself. For example, in the use case #30623, some properties will be readonly individually, but when the inspector becomes `readonly==true` due to other factors, and then the inspector itself becomes `readonly==false`, the readonly flag of all properties is set to `false`, so the individual property's readonly becomes meaningless.

File: editor/editor_inspector.cpp (hunk 17 above)
Comment (TokageItLab) [reply editor/editor_inspector.cpp:385]: Does this mean that these are meaningless?
https://github.com/godotengine/godot/pull/51722#issuecomment-903175425

File: editor/editor_inspector.cpp (hunk 18 above)
Comment (groud) [reply editor/editor_inspector.cpp:391]: > but when the inspector becomes readonly==true due to other factors, and then the inspector itself becomes readonly==false, the readonly flag of all properties is set to false, so the individual property's readonly becomes meaningless.

No, that's not how it should work. When changing the inspector's read_only status, you can simply re-create the whole tree to solve the problem by calling `update_tree()`. It's not the most efficient way but performance here is not a problem (changing the inspector read_only status is not something done very often). `update_tree()` should then set the property to read_only when either the property is set to read only or if the inspector is set to read_only.

File: editor/editor_inspector.cpp (hunk 17 above)
Comment (groud) [reply editor/editor_inspector.cpp:385]: I guess. I think allowing custom behavior makes sense for the base class (most, if not all, scripts will inherit from EditorProperty directly) but not for the children one.

**Comment by TokageItLab** [comment]
@groud In other words, the only thing we need to implement here is a virtual function called `set_uneditable()`, for example, and in `update_tree()`
```cpp
if (EditorProperty->is_readonly() || EditorInspector->is_readonly()) {
  EditorProperty->set_uneditable();
}
```
Does this mean that I should do this?

**Comment by groud** [comment]
> @groud In other words, the only thing we need to implement here is a virtual function called set_uneditable(), for example, and in update_tree()
if (EditorProperty->is_readonly() || EditorInspector->is_readonly()) {
  EditorProperty->set_uneditable();
}
should I do this, right?

Not really, no.

To make it clear, this PR has a lot of collisions with https://github.com/godotengine/godot/pull/30623. That PR adds a PROPERTY_USAGE_READ_ONLY flag that is used to determine if a property is read_only or not. You should add it in this PR too, and then, when building the tree, you should do something like:
```
bool property_read_only = (p.usage & PROPERTY_USAGE_CATEGORY) || read_only;
...
ep->set_read_only(property_read_only);
```

**Comment by TokageItLab** [comment]
@groud `PROPERTY_USAGE_READ_ONLY` flag in #30623 is implemented in the `Control` object, and the flag is implemented with hardcoding. With that implementation, I think it cannot to make it readonly individually by referring to a child class of `EditorProperty` from outside. As use case
> in #45699, it is necessary that read_only works correctly to prevent handling BonePose in RestMode.

**Comment by groud** [comment]
> @groud PROPERTY_USAGE_READ_ONLY flag in #30623 is implemented in the Control object, and the flag is implemented with hardcoding and private.

I am not sure what you mean, the flag is added to `object.h, so that any object can set its property to read_only if needed.
BTW, the `_validate_property(PropertyInfo &property)` function is here for that, it is called when listing the object properties so that you can dynamically update the flags of a property. (depending on a property's value, some fields might be disabled for example).

> With that implementation, I think it cannot to make it readonly individually by referring to a child class of EditorProperty from outside.

I don't think why you would need that anyway. It's not a reliable way to identify EditorProperty nodes (at least in the inspector). If you need something more complex than using the default way the inspector does things (by creating EditorProperties out of the list of property), then you need to code the logic inside an inspector plugin. Otherwise, simply updating the nodes properties with the correct flags (in `_validate_property(PropertyInfo &property)`) should be fine.

**Comment by TokageItLab** [comment]
@groud Thank you for the explanation, now I understood it somehow. For example, the current `SkeletonGizmo` needs to be set to readonly by a specific edit mode instead of specific object state. In that case, it should implement `_validate_property()` in `skeleton_3d.cpp` to get the edit mode and set the flag, is it correct?

Fixed:
- The `_set_read_only()` remains as a virtual function to control each handling in child classes, but it no longer to call the base method.
- `global_read_only` has been omitted.
- `PROPERTY_USAGE_READ_ONLY` flag is now implemented, and the inspector determines from the object property and the inspector whether it is readonly or not, and controls the handling with `EditorProperty`.

**Comment by groud** [comment]
> In that case, it should implement _validate_property() in skeleton_3d.cpp to get the edit mode and set the flag, is it correct?

It seems correct. I am not very familiar with how `skeleton_3d.cpp` work, but if you have a way to know in which mode you are editing (I guess it would set a property on Skeleton3D, maybe the "pose" one ?). Then it should be quite easy to implement.

Otherwise you may add a setter for a new property within Skeleton3D, that would only impact whether or not part of its properties are read-only.

File: editor/editor_inspector.cpp [hunk 19]
```diff
@@ -1954,7 +1962,8 @@ void EditorInspector::update_tree() {
 					ep->set_checked(checked);
 					ep->set_keying(keying);
 
-					ep->set_read_only(read_only);
+					bool property_read_only = (p.usage & PROPERTY_USAGE_READ_ONLY) || read_only;
```
Comment (groud) [inline editor/editor_inspector.cpp:1965]: You can move this out of the `for (Ref<EditorInspectorPlugin> &ped : valid_plugins)` loop, similar to how it's done for `checked` and `checkable`

**Review by groud — APPROVED** [review]
Alright, LGTM

**Comment by groud** [comment]
Thanks!
