### PR TITLE
Fix interpolation in XR

### LINKED ISSUE #103232: Physics interpolation is broken on XR nodes and XRServer
### Tested versions

- Reproducible in v4.4 (0e3dbba6a)

### System information

Godot v4.4.rc.mono (0e3dbba6a) - Windows 11 (build 26100) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 32.0.15.7247) - AMD Ryzen 9 7950X3D 16-Core Processor (32 threads)

### Issue description

Physics interpolation is broken in XR in general, causing the following issues:
- `XROrigin3D` updates `XRServer::world_origin` only when the transform changes, which means `XRServer::world_origin` never has the interpolated value for the transform on each render frame. `XRServer::world_origin` is used to know where the camera is in the world and to render properly, if it isn't also interpolated then there's is a mismatch between the active `XROrigin3D` transform and what `XRServer` has saved. This results in the following behavior:

https://github.com/user-attachments/assets/5e9d7764-7c03-4a29-bc98-de86d0451f9f

- All XR nodes that have a `XRPositionalTracker` will update their position every time the `"pose_changed"` signal is triggered. This happens every time `XRServer::_process` gets called because it asks the active XR interface to poll events and it happens every render frame. Tracked nodes being updated every frame make sense because if we instead poll events on each physics frame and interpolate them the motion sickness on something like the HMD would be unreal, and you don't want your hand trackers to lag behind your real hands. However, when interpolation is enabled the engine really doesn't want you to be updating your transforms on render frame and this causes the childs of those tracked nodes to jitter a bit.

Here is an example in the attached MRP, when the "hand" is interpolated, it follows the parent just fine but the childs aren't smooth at all (also spams in the console the warning that an interpolated transform was set outside physics process)

https://github.com/user-attachments/assets/4f32e267-3b35-41c2-8659-c5fbe2b96330

Disabling interpolation in the hand results in really smooth child movement but then when it comes to following the parent everything falls apart:

https://github.com/user-attachments/assets/51271cb6-32ee-4773-b4d9-4141c55fd1a9

I created a WIP pull request (https://github.com/godotengine/godot/pull/103233) with a fix for the `XRServer::world_origin` interpolation where it works as expected:

https://github.com/user-attachments/assets/107ca829-afc1-4875-827d-a34c7602ee83

However for the second issue I'm out of ideas about how to proceed. Disabling interpolation on the tracked node makes it jitter because it will now follow the non interpolated transform of the parent even if the parent is set as interpolated.

### Steps to reproduce

Enable interpolation in a project and make XROrigin3D a child of any physics object

### Minimal reproduction project (MRP)

It can be reproduced on the official `openxr_character_centric_movement` demo, modifying `start_vr.gd` to remove the line `Engine.physics_ticks_per_second = current_refresh_rate` so the physics FPS can be different than the target framerate
https://github.com/godotengine/godot-demo-projects/tree/master/xr/openxr_character_centric_movement
However here I include a modified version that just adds a moving platform where you can easily see the problem

[MRP.zip](https://github.com/user-attachments/files/18934793/MRP.zip)

Here is an MRP to test the tracker issue with a fake hand for anyone who wants to test without XR hardware:

[tracking_mrp.zip](https://github.com/user-attachments/files/18947247/tracking_mrp.zip)

### PR DESCRIPTION
**Pull request by Asaduji**
Fixes #103232 

~This is currently WIP as it only fixes the problem with `XRServer::world_origin` not being interpolated.
I'm out of ideas about how to fix the second part of the issue of the tracked XR nodes, please read the issue for more info.~
The PR has been updated and fixes all the issues I found.

Any tips are appreciated as this is my first PR and I'm sure there are things to improve.

### CODE REVIEW

**Comment by Asaduji** [comment]
Looks like XRNode3D and XRCamera3D are returning the wrong non-updated transforms when you try to access it from physics process with this approach, will add a fix soon

**Comment by lawnjelly** [comment]
Firstly I've noticed you've used `get_global_transform_interpolated()` for `XROrigin`, `XRCamera` and `XRNode`. I have very little familiarity with XR and I may have misunderstood your description of `XROrigin`, I had somehow got the impression earlier that there was only one that was always on, but the docs say there may be multiple.

For Cameras and likely XRNodes (I'm guessing like hand markers?) you may need to have better control over the prev/curr xforms and may end up needing to handle this data manually as in `Camera3D`. I suspect now this may also be the case in `XROrigin`.

To be clear, using `get_global_transform_interpolated()` is easier to use and easy to get going with, but there are subtle issues to do with the need for _priming_ of the data stream before use in order to prevent glitches when turning nodes on and off (e.g. Cameras), so you may end up having to go with the longhand approach.

If we end up needing several nodes with full client interpolation, it's possible we can "genericize" some of the boiler plate to make it easier and less bug prone to add to nodes.

## Combining interpolated and non-interpolated on same node
My first impressions are the approach of trying to have `XRCamera` and `XRNode` both interpolated AND non-interpolated seems a bit hacky - there's no other node that does this. It is likely to introduce physics interpolation warnings and send incorrect / superfluous data to `VisualServer`.

Nodes are currently intended to be *either* physics interpolated (operating on the physics tick) *or* non-interpolated (operating on the frame) but *not both*. You are essentially in uncharted waters here, other parts of Godot may not work correctly.

I suspect this needs a proper discussion of what problems are trying to be solved to be sure that this is the correct avenue to solve them, probably via a proposal.

I must apologize as you are on a difficult boundary here - effectively I'm the goto guy for interpolation, but I don't have a clue how the current XR stuff works, and I don't have XR equipment, so you have to explain it like to a newbie and explain what problems you are trying to solve.

### Essentially the current paradigm for 3D interpolation in the engine is this in a nutshell:

* Root node and branches leading from it are interpolated (operating on physics ticks)
* Some specific edge case nodes towards the end of branches (such as Cameras) can be non-interpolated, and do a client side (scene tree) manual interpolation of their parent node or target in order to achieve consistent look with the interpolated scene (there will be one tick of lag), but also allowing some zero lag control (e.g. mouse look)
* Branches that are non-interpolated cannot then be later set back to interpolated further on in the branch, as the tick based xforms are no longer there (or rather they are, but 1 tick behind)
* Any interpolated node that you use to follow another independent non-interpolated target, is going to introduce a one tick lag

Now, there may be some specific leeway to move outside this if a specific use case requires it, but there isn't *existing* code to work outside this framework.

### How XR is meant to work (at a guess)
At a guess for how things are meant to operate with XR:
* You want these XR nodes to take their xform from the hardware and reflect that in the nodes in as near realtime as possible, so you don't get lag
* You want to get some of the benefits of physics interpolation where possible

If this is correct:

* You want a main branch of the scene tree that is interpolated
* A branch with the XR origin and an XRCamera, that is used to view the interpolated scene
* You may want some XR objects totally defined by their XR xform and non interpolated (say a gun)
* You may want an arm to line up to this XR node via e.g. IK (we have a similar issue open for IK)
* You may want to perform some physics tests on an object that approximates the xform of the XR node

This is just trying to explain some of how things currently work interpolation-wise, but I think I would need some further description / research into how XR currently works in order to come up with some coherent design here.

**Comment by Asaduji** [comment]
> Firstly I've noticed you've used `get_global_transform_interpolated()` for `XROrigin`, `XRCamera` and `XRNode`. I have very little familiarity with XR and I may have misunderstood your description of `XROrigin`, I had somehow got the impression earlier that there was only one that was always on, but the docs say there may be multiple.

There can be several of them but only one will be active at a time: https://docs.godotengine.org/en/stable/classes/class_xrorigin3d.html#class-xrorigin3d-property-current

> For Cameras and likely XRNodes (I'm guessing like hand markers?) you may need to have better control over the prev/curr xforms and may end up needing to handle this data manually as in `Camera3D`. I suspect now this may also be the case in `XROrigin`.
> 
> To be clear, using `get_global_transform_interpolated()` is easier to use and easy to get going with, but there are subtle issues to do with the need for _priming_ of the data stream before use in order to prevent glitches when turning nodes on and off (e.g. Cameras), so you may end up having to go with the longhand approach.

I went with this approach due to this comment: https://github.com/godotengine/godot/issues/103232#issuecomment-2677870843

> My first impressions are the approach of trying to have `XRCamera` and `XRNode` both interpolated AND non-interpolated seems a bit hacky - there's no other node that does this. It is likely to introduce physics interpolation warnings and send incorrect / superfluous data to `VisualServer`.
> 
> Nodes are currently intended to be _either_ physics interpolated (operating on the physics tick) _or_ non-interpolated (operating on the frame) but _not both_. You are essentially in uncharted waters here, other parts of Godot may not work correctly.
> 
> I suspect this needs a proper discussion of what problems are trying to be solved to be sure that this is the correct avenue to solve them, probably via a proposal.

This approach comes from this comment: https://github.com/godotengine/godot/issues/103232#issuecomment-2679463246
The local position of `XRCamera3D` and `XRNode3D` isn't interpolated and it's polled every render frame, however we need them to "follow" the interpolated parent, the reason was explained here: https://github.com/godotengine/godot/issues/103232#issue-2873626889
If we just disable interpolation entirely for `XRNode3D` the hands will just jitter as soon as you move the parent, if you do the intended approach and only update the hands on physics frame and interpolate, it's practically unusable due to the latency.

> * You want these XR nodes to take their xform from the hardware and reflect that in the nodes in as near realtime as possible, so you don't get lag
> * You want to get some of the benefits of physics interpolation where possible

This is correct, the benefit from physics interpolation being: interpolate the global transform so it follows the parent correctly while not interpolating the local transform so the tracked movement is in realtime.

This current approach works fine because it just acts as any other non interpolated node, but setting its global position to follow the interpolated transform of the parent. This shouldn't have any side effect as it's the same as changing the transform of an non interpolated node inside `_process`. All childs of these nodes will also act as any non-interpolated node following its parent on every render frame.

The only issue is the transform being updated on physics frame by one of the interpolated ancestors changing its own transform, but this is a separate issue that happens outside of XR as you already know: https://github.com/godotengine/godot/pull/103351

File: scene/3d/xr_nodes.cpp [hunk 1]
```diff
@@ -72,7 +72,49 @@ void XRCamera3D::_removed_tracker(const StringName &p_tracker_name, int p_tracke
...
+			if (!is_inside_tree() || is_physics_interpolated() || Engine::get_singleton()->is_editor_hint()) {
+				break;
+			}
+
+			Node3D *parent = Object::cast_to<Node3D>(get_parent());
+
+			// If we want interpolated physics nodes like RayCast3D to follow this node properly,
+			// the transform must be relative to the non interpolated parent when we're on physics process
+			if (parent && parent->is_physics_interpolated_and_enabled() && !is_set_as_top_level()) {
+				set_transform(pose_offset);
```
Comment (lawnjelly) [inline scene/3d/xr_nodes.cpp:115]: To be clear, this is the (imo) contentious area I am referring to - setting transforms on BOTH the frame and the physics tick.

Imo the issue of trying to get `RayCast3D` to work is a separate issue and should be fixed in a separate follow up PR, for all the nodes you are changing.

In general we try and keep PRs as self-contained and non-divisible as possible, and focused on fixing one bug at a time.

If we get a decent implementation for the xforms for display I can approve that, but architectural changes as above will probably need further discussion with other maintainers, as there are a number of alternative (perhaps less hacky) ways of addressing that problem.

As is I can see a number of potential pitfalls with this approach, and it needs a full discussion in its own right.

**Comment by lawnjelly** [comment]
I think there are some language issues between us (I admit it's quite difficult to put across in words so apologies for any confusion :grin: ), I wasn't clear on the definitions I was using, and now I can see it was ambiguous, so to be more clear:

When I mention "interpolated / non-interpolated" I was trying to refer to the _physics interpolation mode_ of the node.

### Interpolated
By saying a node that is interpolated I was meaning `interpolation_mode` ON / inherited ON.
Nodes with `interpolation_mode` ON should be moved and have transform set on the TICK.

### Non-interpolated
A node that is non-interpolated is a node that is `interpolation_mode` OFF / inherited OFF.
Nodes with `interpolation_mode` OFF should be moved and have transform set on the FRAME.


An `interpolation_mode` OFF node can therefore use e.g. `get_global_transform_interpolated()` on the frame to follow / derive an interpolated transform from another node, such as a parent, or a target node (if following a target).

From now on I'll try and refer to the `physics_interpolation_mode` to make this clearer.

File: scene/3d/xr_nodes.cpp (hunk 1 above)
Comment (Asaduji) [reply scene/3d/xr_nodes.cpp:115]: > To be clear, this is the (imo) contentious area I am referring to - setting transforms on BOTH the frame and the physics tick.
> 
> Imo the issue of trying to get `RayCast3D` to work is a separate issue and should be fixed in a separate follow up PR, for all the nodes you are changing.
> 
> In general we try and keep PRs as self-contained and non-divisible as possible, and focused on fixing one bug at a time.
> 
> If we get a decent implementation for the xforms for display I can approve that, but architectural changes as above will probably need further discussion with other maintainers, as there are a number of alternative (perhaps less hacky) ways of addressing that problem.
> 
> As is I can see a number of potential pitfalls with this approach, and it needs a full discussion in its own right.

Oh so this is what you meant, now I get it
I totally forgot I was updating the transform in both render frame and physics frame 😅
The reason behind this change is because the order of execution is this:
- Pose update received
- Physics update
- Render update (we apply the interpolated transform of the parent here)

Because we're setting the transform at render frame, which happens *after* physics, when you try to access the transform of the node inside physics it has a transform that hasn't been updated yet.
It's also possible that the node being relative to the interpolated transform of the parent at the time of a physics frame might have an impact too, since `get_global_transform_interpolated` returns the non-interpolated transform when called inside physics frame it might also be helping with that, but I'm not completely sure.

I agree that it's a bit hacky and to be honest I was just waiting for review to see if anyone here could suggest something better, maybe if we go the `top_level` route this can be avoided but I still have the doubt I commented here: https://github.com/godotengine/godot/issues/103232#issuecomment-2689095414
Doing that would prevent users from using `top_level` in the intended way as the node would always follow the parent

**Comment by Asaduji** [comment]
> I think there are some language issues between us (I admit it's quite difficult to put across in words so apologies for any confusion 😁 ), I wasn't clear on the definitions I was using, and now I can see it was ambiguous, so to be more clear:
> 
> When I mention "interpolated / non-interpolated" I was trying to refer to the _physics interpolation mode_ of the node.
> 
> ### Interpolated
> By saying a node that is interpolated I was meaning `interpolation_mode` ON / inherited ON. Nodes with `interpolation_mode` ON should be moved and have transform set on the TICK.
> 
> ### Non-interpolated
> A node that is non-interpolated is a node that is `interpolation_mode` OFF / inherited OFF. Nodes with `interpolation_mode` OFF should be moved and have transform set on the FRAME.
> 
> An `interpolation_mode` OFF node can therefore use e.g. `get_global_transform_interpolated()` on the frame to follow / derive an interpolated transform from another node, such as a parent, or a target node (if following a target).
> 
> From now on I'll try and refer to the `physics_interpolation_mode` to make this clearer.
> 
> ### `get_global_transform_interpolated()`
> In terms of the pros and cons of this I highly recommend reading the c++ functions in `Node3d`: `_get_global_transform_interpolated()` `update_client_physics_interpolation_data()` which includes timeouts (and the reason for the need for priming)

I misunderstood you, yeah, sorry 😅
I didn't know you were talking about me changing the transform inside both physics and render frame (or tick and frame as you referred here), I replied to that here: https://github.com/godotengine/godot/pull/103233#discussion_r1976774051

**Comment by lawnjelly** [comment]
Been discussing and learning a bit more how XR works with @BastiaanOlij on rocket chat (where the data comes in before the ticks etc). I'm kind of coming around to your idea of setting the transform on the ticks as a bodge for XR as being a possibility (best of a difficult situation) but would be good to discuss on a follow up PR.

In particular it might even be possible to do a light version of `set_transform()` that doesn't invoke the heavy machinery (propagation etc) but gets the benefit required. Not sure yet.

**Comment by Asaduji** [comment]
> Been discussing and learning a bit more how XR works with @BastiaanOlij on rocket chat (where the data comes in before the ticks etc). I'm kind of coming around to your idea of setting the transform on the ticks as a bodge for XR as being a possibility (best of a difficult situation) but would be good to discuss on a follow up PR.
> 
> In particular it might even be possible to do a light version of `set_transform()` that doesn't invoke the heavy machinery (propagation etc) but gets the benefit required. Not sure yet.

I've just read the conversation, I want to point out that the reason why I'm doing it also on the camera is because childs have the same problem as in the hands when following it, for example a raycast.

About possible alternatives to setting the transform at physics process I'm all ears 🫡
I will investigate too and I can test possible solutions since you don't have XR equipment, feel free to let me know when needed.

About a followup PR, you want me to separate this into 2 PRs one for the `world_origin` and one for the nodes, or you mean a new PR with possible alternatives like making a light `set_transform`

**Comment by lawnjelly** [comment]
> About a followup PR, you want me to separate this into 2 PRs one for the world_origin and one for the nodes, or you mean a new PR with possible alternatives like making a light set_transform

Essentially only setting the transform on the frame for this PR. I understand that this means some physics aspects may not work correctly with physics interpolation.

That's fine, a PR doesn't have to fix all outstanding bugs. The engine is (as I understand it) broken already with physics interpolation, so we are just making it slightly less broken.

**Comment by Asaduji** [comment]
I've updated the PR to remove what was requested.
As a workaround, this works fine:
```py
extends Node3D

@onready var controller: XRController3D = $".."

var origin: XROrigin3D

func _ready() -> void:
	set_physics_interpolation_mode(Node.PHYSICS_INTERPOLATION_MODE_ON)
	
	if controller.get_parent() is XROrigin3D:
		origin = controller.get_parent() as XROrigin3D

	# set as top level to ignore parent transform!!!
	top_level = true
	pass

func _physics_process(delta: float) -> void:
	if !origin || !controller || !controller.get_pose():
		return
	
	global_transform = origin.global_transform * controller.get_pose().transform
	pass
```
This can be added to a node child of the `XRNode3D` (or camera) we want to follow, in this case a controller (`XRController3D`).
This node will be interpolated and only update its transform on physics process as intended, all childs of it will follow just fine.
Here is a demo of it working, left is without the workaround, you can see how it easily gets behind. Right is with the workaround, following the hand perfectly.
It's running at 10 ticks/s that's why the physics are a bit choppy but it's easier to see the behavior this way.


https://github.com/user-attachments/assets/65389c60-766c-43d0-aeba-38ba6cede3e8

**Review by lawnjelly — APPROVED** [review]
This looks fine to me although will need a second pass by an XR guy, and maybe a check for style.

Just to throw a spanner in the works (sorry! :grin: ), partly as a result of this XR issue and IK and ragdoll, I've revisited the overall 3D physics interpolation design.

After doing some testbed work today and speaking with other maintainers, we've decided to evaluate changing the 3D physics interpolation paradigm to scene side rather than server side.

If this works out ok, it will make this XR code much easier to do and simpler for XR maintainers to understand (and will need to be remodified), but I don't think there's a major problem with this version being available in the interim. (Alternatively you guys may be happy with the workaround, but this PR is fine too.)

The current provisional plan is to try out new version in 3.x then if successful, look at porting to 4.x.

**Comment by Asaduji** [comment]
I will wait for @BastiaanOlij to review so I can make a final commit and don't trigger CI/CD for a comment change

File: scene/3d/xr_nodes.cpp [hunk 2]
```diff
@@ -400,7 +431,13 @@ void XRNode3D::_removed_tracker(const StringName &p_tracker_name, int p_tracker_
 
 void XRNode3D::_pose_changed(const Ref<XRPose> &p_pose) {
 	if (p_pose.is_valid() && p_pose->get_name() == pose_name) {
-		set_transform(p_pose->get_adjusted_transform());
+		Node3D *parent = Object::cast_to<Node3D>(get_parent());
+
+		if (is_inside_tree() && parent && parent->is_physics_interpolated_and_enabled() && !is_set_as_top_level() && !is_physics_interpolated()) {
+			pose_offset = p_pose->get_adjusted_transform();
```
Comment (BastiaanOlij) [inline scene/3d/xr_nodes.cpp:437]: My worry here with not setting the pose at this stage, is that any of the logic that needs to be done during physics process that uses the nodes location, won't have it until the interpolated version is set in internal process.

Maybe that is an unavoidable consequence of using interpolation and it may have no real impact as user who turn interpolation will likely need to stay away from such processes anyway.

**Review by BastiaanOlij — APPROVED** [review]
Sorry it took me awhile to get to this.

I think this is as good as we'll get it, it solves the core problem and the only question mark I have is related to a scenario that wouldn't work well with interpolation anyway (using physics following hand tracking).

It is also important to note that the approach used in XR Tools, and described in the [OpenXR origin centric movement demo](https://github.com/godotengine/godot-demo-projects/tree/master/xr/openxr_origin_centric_movement) will not play nice with interpolation regardless of what we do.

Users must use the [OpenXR character centric movement](https://github.com/godotengine/godot-demo-projects/tree/master/xr/openxr_character_centric_movement) approach, which is superior anyway.

We may wish to add a remark around this to the [room scale page in the manual](https://docs.godotengine.org/en/stable/tutorials/xr/xr_room_scale.html) that details the two approaches.

File: scene/3d/xr_nodes.cpp (hunk 2 above)
Comment (Asaduji) [reply scene/3d/xr_nodes.cpp:437]: > My worry here with not setting the pose at this stage, is that any of the logic that needs to be done during physics process that uses the nodes location, won't have it until the interpolated version is set in internal process.
> 
> Maybe that is an unavoidable consequence of using interpolation and it may have no real impact as user who turn interpolation will likely need to stay away from such processes anyway.

Initially the PR addressed this issue by setting the transform on physics process too, but I removed it by request of @lawnjelly , because in the current interpolation implementation you shouldn't process a non-interpolared node inside physics_process. They're planning to change the behavior of the interpolation system in a way that shouldn't be a problem anymore.

In the meantime there is a workaround I'm using that works perfectly fine for things like physics based hands that follow the `XRController3D` node, you can see it here: https://github.com/godotengine/godot/pull/103233#issuecomment-2695251731 😀

**Comment by lawnjelly** [comment]
Looks like it needs a rebase.

Also reminder to anyone that can to review #103685, as the sooner we get that merged in 3.x the sooner we can get it in 4.x and it should make the XR stuff a lot easier and perhaps open up opportunities to do things with less lag.

**Comment by Repiteo** [comment]
You'll need to squash the commits, a single commit is preferred. See [PR workflow docs](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for how-to.

**Comment by Asaduji** [comment]
> You'll need to squash the commits, a single commit is preferred. See [PR workflow docs](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for how-to.

Fixed.
I did 2 commits on purpose because I thought it would be more clear the 2 changes being done here, will do just 1 commit next time 🫡

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 4.4.1.
