### PR TITLE
Draw tilemap coordinate and rectangle size on the screen when using the TileMapLayer's Terrains plugin

### LINKED ISSUE #101634: 2D Tilemap coordinates disappear when on "Terrains" Mode
### Tested versions

Tested Version: v4.3.stable.official [77dcf97d8]

### System information

Windows 10

### Issue description

On the editor, when using the tilemap in "Tiles" mode, you can see your tile coords in the lower left corner. If you switch to "Terrains" mode when you no longer see the tilemap coordinates where your cursor is.

Image

### Steps to reproduce

Create a new 2D TilemapLayer. Hover over the field, you can see your coords in the lower left of the game field. Switch to Terrains, coords disappear.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by btgs-0**
Fixes #101634.

I've extracted the code that draws these strings into two methods. I've also made these methods as stateless as possible. Hopefully that's acceptable.

### CODE REVIEW

**Comment by btgs-0** [comment]
Sorry, took me a few minutes to figure out how to squash my commits into one after fixing the codespell check failure :)

File: editor/plugins/tiles/tile_map_layer_editor.cpp [hunk 1]
```diff
@@ -50,6 +50,69 @@ TileMapLayer *TileMapLayerSubEditorPlugin::_get_edited_layer() const {
...
+	}
+
+	Ref<TileSet> tile_set = edited_layer->get_tile_set();
+	if (tile_set.is_null()) {
+		return;
+	}
+
+	if (!edited_layer->is_visible_in_tree()) {
+		return;
+	}
```
Comment (KoBeWi) [inline editor/plugins/tiles/tile_map_layer_editor.cpp:70]: These conditions are already part of the methods that call this method, so no need to check them again.

File: editor/plugins/tiles/tile_map_layer_editor.cpp [hunk 2]
```diff
@@ -50,6 +50,69 @@ TileMapLayer *TileMapLayerSubEditorPlugin::_get_edited_layer() const {
 	return Object::cast_to<TileMapLayer>(ObjectDB::get_instance(edited_tile_map_layer_id));
 }
 
+/// <summary>
+/// Draws a tilemap tile coordinate string on the provided overlay.
+/// </summary>
+/// <param name="p_overlay">The overlay to draw on.</param>
```
Comment (KoBeWi) [inline editor/plugins/tiles/tile_map_layer_editor.cpp:56]:
```suggestion
```
We don't add documentation comments for methods and you can't randomly start adding them. It would require a proposal.

**Comment by KoBeWi** [comment]
By extracting the code you somehow added more duplication.
You could merge the 2 methods into 1 and add a parameter for whether to show rectangle or not.

File: editor/plugins/tiles/tile_map_layer_editor.cpp (hunk 1 above)
Comment (btgs-0) [reply editor/plugins/tiles/tile_map_layer_editor.cpp:70]: Thanks for reviewing this. I will remove these unneeded checks.

File: editor/plugins/tiles/tile_map_layer_editor.cpp (hunk 2 above)
Comment (btgs-0) [reply editor/plugins/tiles/tile_map_layer_editor.cpp:56]: Sure, I will remove them.

**Comment by btgs-0** [comment]
> By extracting the code you somehow added more duplication. You could merge the 2 methods into 1 and add a parameter for whether to show rectangle or not.

Thanks, I will combine the two methods into one and pass in the required dependencies as parameters.

File: editor/plugins/tiles/tile_map_layer_editor.cpp [hunk 3]
```diff
@@ -50,6 +50,27 @@ TileMapLayer *TileMapLayerSubEditorPlugin::_get_edited_layer() const {
...
+
+	if (show_rectangle_size) {
+		Vector2i rect_size = tile_set->local_to_map(edited_layer->get_local_mouse_position()) - tile_set->local_to_map(rectangle_origin);
+		text += vformat(" %s (%dx%d)", TTR("Drawing Rect:"), ABS(rect_size.x) + 1, ABS(rect_size.y) + 1);
+	}
+
+	draw_text_over_viewport(p_overlay, text, msgpos);
+}
+
+void TileMapLayerSubEditorPlugin::draw_text_over_viewport(Control *p_overlay, String text, Point2 position) {
```
Comment (KoBeWi) [inline editor/plugins/tiles/tile_map_layer_editor.cpp:65]: No need to have a method that's called only once.
It can always be extracted if it's needed in the future. Now it's not.

Comment (btgs-0) [reply editor/plugins/tiles/tile_map_layer_editor.cpp]: Thanks, I've removed it.

File: editor/plugins/tiles/tile_map_layer_editor.h [hunk 4]
```diff
@@ -68,6 +68,7 @@ class TileMapLayerSubEditorPlugin : public Object {
 	virtual void forward_canvas_draw_over_viewport(Control *p_overlay) {}
 	virtual void tile_set_changed() {}
 	virtual void edit(ObjectID p_tile_map_layer_id) {}
+	virtual void draw_tile_coords_over_viewport(Control *p_overlay, const TileMapLayer *edited_layer, Ref<TileSet> tile_set, bool show_rectangle_size, Vector2i rectangle_origin);
```
Comment (KoBeWi) [inline editor/plugins/tiles/tile_map_layer_editor.h:71]:
```suggestion
	virtual void draw_tile_coords_over_viewport(Control *p_overlay, const TileMapLayer *p_edited_layer, Ref<TileSet> p_tile_set, bool p_show_rectangle_size, Vector2i p_rectangle_origin);
```

**Review by KoBeWi — APPROVED** [review]

**Comment by btgs-0** [comment]
I've pushed up the suggested changes and sorted the style issue. Thanks for reviewing my pull request

File: editor/plugins/tiles/tile_map_layer_editor.h [hunk 5]
```diff
@@ -68,6 +68,7 @@ class TileMapLayerSubEditorPlugin : public Object {
 	virtual void forward_canvas_draw_over_viewport(Control *p_overlay) {}
 	virtual void tile_set_changed() {}
 	virtual void edit(ObjectID p_tile_map_layer_id) {}
+	virtual void draw_tile_coords_over_viewport(Control *p_overlay, const TileMapLayer *p_edited_layer, Ref<TileSet> p_tile_set, bool p_show_rectangle_size, Vector2i p_rectangle_origin);
```
Comment (AThousandShips) [inline editor/plugins/tiles/tile_map_layer_editor.h:71]:
```suggestion
	virtual void draw_tile_coords_over_viewport(Control *p_overlay, const TileMapLayer *p_edited_layer, Ref<TileSet> p_tile_set, bool p_show_rectangle_size, const Vector2i &p_rectangle_origin);
```

File: editor/plugins/tiles/tile_map_layer_editor.cpp [hunk 6]
```diff
@@ -50,6 +50,23 @@ TileMapLayer *TileMapLayerSubEditorPlugin::_get_edited_layer() const {
 	return Object::cast_to<TileMapLayer>(ObjectDB::get_instance(edited_tile_map_layer_id));
 }
 
+void TileMapLayerSubEditorPlugin::draw_tile_coords_over_viewport(Control *p_overlay, const TileMapLayer *p_edited_layer, Ref<TileSet> p_tile_set, bool p_show_rectangle_size, Vector2i p_rectangle_origin) {
```
Comment (AThousandShips) [inline editor/plugins/tiles/tile_map_layer_editor.cpp:53]:
```suggestion
void TileMapLayerSubEditorPlugin::draw_tile_coords_over_viewport(Control *p_overlay, const TileMapLayer *p_edited_layer, Ref<TileSet> p_tile_set, bool p_show_rectangle_size, const Vector2i &p_rectangle_origin) {
```

**Review by AThousandShips — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Comment by btgs-0** [comment]
Thanks for accepting my pull request
