### PR TITLE
Fix Android debug/run (2.1)

### LINKED ISSUE #8581: Running on android device installs but does not run
**Ubuntu 17.04 - Godot version: 2.1.3**

**Issue description:**
Debug-running on Android device installs the game but does not run it.
On 2.1.2 the project runs automatically after installed on the device when running from the editor.

**Steps to reproduce:**
Configure Android export and try to run the project on the Android device on 2.1.3.

**Link to minimal example project:**
Any project should be fine.

ps: Templates are ok, tested with clean editor settings too.

### PR DESCRIPTION
**Pull request by RandomShaper**
Same as _master_'s 0ae3336a329b1fd14b66bb26707c2461b66e5aa8; namely:
- Prefix all __adb__ commands with device specification to avoid errors when multiple devices connected.
- Include Android release in device data collection.
- Force system user:.
    - Ability to enable/disable.
    - Apply only if OS release >= 17 (when multiuser was introduced.
    - Fix argument passing.
- Rename local variable `port` to `dbg_port` to better match its partner `fs_port`.
- Fix typo in error message.

But adds:
- Get the debug port from the editor settings, where it lives now.

Fixes #8581.

### CODE REVIEW

File: platform/android/export/export.cpp [hunk 1]
```diff
@@ -1831,6 +1845,7 @@ void register_android_exporter() {
 	//EDITOR_DEF("android/release_keystore","");
 	//EDITOR_DEF("android/release_username","");
 	//EditorSettings::get_singleton()->add_property_hint(PropertyInfo(Variant::STRING,"android/release_keystore",PROPERTY_HINT_GLOBAL_FILE,"*.keystore"));
+	EDITOR_DEF("android/force_system_user", false);
```
Comment (volzhs) [inline platform/android/export/export.cpp]: this `android/force_system_user` default value is different from L1692.
shouldn't it have the same default value?

Comment (RandomShaper) [inline platform/android/export/export.cpp]: Indeed! Fixed now.

**Review by volzhs — APPROVED** [review]
