### PR TITLE
Make `TextureButton` and `Button` update on texture change

### LINKED ISSUE #63801: MeshTexture behaves poorly when used as icon on Button
### Godot version

5ecd61a3150f87a433dd5a7ff49a842b72516640

### System information

Fedora Silverblue 36, Ryzen 2400G

### Issue description

There are several issues when using `MeshTexture` as icon in a `Button`.

* After assigning texture as icon, editor preview does not update until another unrelated property on button is changed
* Icon is completely misaligned
* `expand_icon` setting hides texture (or makes it zero size)

Demonstration:

https://user-images.githubusercontent.com/347965/182269987-3dcb56bc-2640-4202-a936-2772dc0547b5.mov

### Steps to reproduce

1. Add button
2. Assign a MeshTexture as icon

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by AThousandShips**
Fixes: #63801 (partially)

Using the approach from #75532

Does not work for `click_mask` as `BitMap` does not use the `changed` signal, out of scope for this PR to add that

### CODE REVIEW

File: scene/gui/texture_button.cpp [hunk 1]
```diff
@@ -369,6 +346,32 @@ void TextureButton::set_texture_focused(const Ref<Texture2D> &p_focused) {
...
 };
 
+void TextureButton::_set_texture(Ref<Texture2D> *p_destination, const Ref<Texture2D> &p_texture, bool p_update_size) {
+	DEV_ASSERT(p_destination);
+	Ref<Texture2D> &destination = *p_destination;
+	if (destination == p_texture) {
+		return;
+	}
+	if (destination.is_valid()) {
+		destination->disconnect(CoreStringNames::get_singleton()->changed, callable_mp(this, p_update_size ? &TextureButton::_texture_changed : &TextureButton::queue_redraw));
```
[the remark this answers is not in the document]
Comment (AThousandShips) [reply scene/gui/texture_button.cpp:356]: Reworking this and will push soon

**Comment by AThousandShips** [comment]
Ping, can this get a review?

File: scene/gui/texture_button.cpp [hunk 2]
```diff
@@ -369,6 +356,28 @@ void TextureButton::set_texture_focused(const Ref<Texture2D> &p_focused) {
 	focused = p_focused;
 };
 
+void TextureButton::_set_texture(Ref<Texture2D> *p_destination, const Ref<Texture2D> &p_texture) {
+	DEV_ASSERT(p_destination);
```
Comment (groud) [inline scene/gui/texture_button.cpp:360]: It's not  a problem with this PR specifically as this was done in TextureProgressBar too, but DEV_ASSERT isn't very commonly used in the database. Maybe a `EFF_FAIL_COND` would be better for consistency ?

**Review by groud — APPROVED** [review]
Looks good to me, good job! I've added a comment but I am not 100% it is relevant.
Thanks!

File: scene/gui/texture_button.cpp (hunk 2 above)
Comment (AThousandShips) [reply scene/gui/texture_button.cpp:360]: Sure thing! Makes sense

Comment (groud) [reply scene/gui/texture_button.cpp:360]: If you amend this PR, I think you can modify the test in `TextureProgressBar` too. I don't think we need another PR just for that. :)

Comment (AThousandShips) [reply scene/gui/texture_button.cpp:360]: Will do to, will use `ERR_FAIL_NULL`

Comment (KoBeWi) [reply scene/gui/texture_button.cpp]: The dev assert was used here, because it's internal method and null can only come from wrong usage. Dev assert checks are only done in dev builds AFAIK, null check in any other build is pointless in this case. The argument is property pointer.

File: scene/gui/texture_button.cpp [hunk 3]
```diff
@@ -294,41 +295,28 @@ void TextureButton::_bind_methods() {
...
 		return;
 	}
-
+	if (disabled.is_valid()) {
+		disabled->disconnect(CoreStringNames::get_singleton()->changed, callable_mp((CanvasItem *)this, &CanvasItem::queue_redraw));
+	}
 	disabled = p_disabled;
+	if (disabled.is_valid()) {
+		disabled->connect(CoreStringNames::get_singleton()->changed, callable_mp((CanvasItem *)this, &CanvasItem::queue_redraw));
+	}
```
Comment (YuriSizov) [inline scene/gui/texture_button.cpp:319]: Why is disabled texture handled differently?

Comment (AThousandShips) [reply scene/gui/texture_button.cpp:319]: Because it does not affect the size, see above `get_minimum_size`

Comment (YuriSizov) [reply scene/gui/texture_button.cpp:319]: That seems like an issue with the min size calculation. Why wouldn't it? Also, my god, that method is awful...

Comment (AThousandShips) [reply scene/gui/texture_button.cpp:319]: Should this be handled separately? I'm not quite sure how this should be fixed or what the right approach is

Comment (AThousandShips) [reply scene/gui/texture_button.cpp:319]: Should I pre-emptively make the disabled texture also update the size? Or should that be done in such a PR?

Comment (YuriSizov) [reply scene/gui/texture_button.cpp]: I think you already do that with the current version of the PR. Any further changes can be done in a follow-up by anyone.

**Review by YuriSizov — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks! That should actually address some editor issues with custom type icons too.

**Comment by AThousandShips** [comment]
Thank you!

**Comment by AThousandShips** [comment]
Should I go ahead and cherry-pick this one as #75016 is getting a 3.x version?

**Comment by YuriSizov** [comment]
@AThousandShips Yes, sure, I think we can backport both changes.

**Comment by AThousandShips** [comment]
Then I'll open, tested it out and code works
