### PR TITLE
Fix `AudioServer.get_time_since_last_mix()` returning incorrect value when accessing from another thread

### LINKED ISSUE #45025: When accessing AudioServer.get_time_since_last_mix() from multiple threads it sometimes (rarely) returns an insanely large number
**Godot version:** v3.2.4.beta4.official

**OS/device including version:** Windows 10 Build 18363.1256

**Issue description:**

`AudioServer.get_time_since_last_mix()` sometimes returns a crazy huge result when using multiple threads. Here's some output:

```
DEBUG: Time since last mix: 18446744073709.551
```

I have two threads running analyzing a song as it plays to synchronize gameplay to audio. As part of this I have a function that both threads call fairly regularly:

```
func get_background_playback_position():
	playback_pos_mutex.lock()
	var pos = backAudioPlayer.get_playback_position()
	var time_since_last_mix = AudioServer.get_time_since_last_mix()
	playback_pos_mutex.unlock()

	if pos > 1000:
		print("DEBUG: pos: ", pos)
	if time_since_last_mix > 1.0:
		print("DEBUG: Time since last mix: ", time_since_last_mix)
	
	return pos + time_since_last_mix
```

Initially I was not using the `playback_pos_mutex` like I am now. Adding the mutex has not fixed the issue (I'm pretty sure the `AudioServer` is thread-safe anyway according to docs.

**Steps to reproduce:**

1. Create two threads that poll the time since last mix for the audio server
2. Log when time_since_last_mix is large

I found I can more reliably reproduce the behavior if I click out of the main game window. When it doesn't have focus it seems like the bug happens more often but otherwise it's seemingly random.

**Minimal reproduction project:** See attached zip below. You'll need the 3.2.4.beta4 for MP3 support. Run the game, select a song and then click out of the window so it no longer has focus. This is not required to reproduce the bug however it makes it happen more reliably.

[bug_time_since_last_mix.zip](https://github.com/godotengine/godot/files/5788979/bug_time_since_last_mix.zip)

### PR DESCRIPTION
**Pull request by laplante-sean**
- Changes `AudioDriver::_last_mix_time` and `AudioDriver::_last_mix_frames` to be atomic `uint64_t` variables
 - Modifies `get_time_since_last_mix()` and `get_time_to_next_mix()` to make a local copy of each `_last_mix_time` and `_last_mix_frames` prior to `get_ticks_usec` to ensure they are always smaller.

<i>Bugsquad edit</i>: Fix #45025

### CODE REVIEW

**Comment by Chaosus** [comment]
You need to squash commits together as described in https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request and required by our workflow

**Comment by vix597** [comment]
Done. Sorry about that.

**Comment by RandomShaper** [comment]
I have a couple of reasons to do the synchronization differently:
- In general, we are not using modern C++, like atomics, unless where it's strictly necessary to build a higher level primitive based on them.
- `AudioDriver` already provides a sync. mechanism (`lock()` and `unlock()`), that can be used here. It will also prevent race condition between both variables.

I believe this PR could be modified to be based on `lock()` and `unlock()`. Also, adapting it for 3.2 would be nice.

**Comment by vix597** [comment]
That's an easy change. I can switch it to use lock and unlock no problem. This is my first time working with Godot source code and I didn't notice those were available.

Beyond switching to lock/unlock, what needs to be done to adapt this PR for 3.2? Should I make a separate PR for the 3.2 branch or will simply switching away from `std::atomic` allow it to be cherry picked to 3.2?

**Comment by RandomShaper** [comment]
No worries at all!

If the code affected by a PR has not changed enough between 3.2 and master, you can just PR for master and specify that the fix is also good for 3.2. You can check by trying to merge the PR locally into 3.2. If there are no conflicts or are trivial to solve, you know you don't need a separate PR.

File: servers/audio_server.cpp [hunk 1]
```diff
@@ -65,19 +65,28 @@ void AudioDriver::audio_server_process(int p_frames, int32_t *p_buffer, bool p_u
 }
 
 void AudioDriver::update_mix_time(int p_frames) {
+	lock();
```
Comment (RandomShaper) [inline servers/audio_server.cpp:68]: This is called from `audio_server_process()`, where the lock is already held, so I think it's better not trying to relock here. Should be fine, provided the mutex is recursive, but anyway.

File: servers/audio_server.cpp [hunk 2]
```diff
@@ -1079,11 +1088,11 @@ double AudioServer::get_output_latency() const {
 	return AudioDriver::get_singleton()->get_latency();
 }
 
-double AudioServer::get_time_to_next_mix() const {
```
Comment (RandomShaper) [inline servers/audio_server.cpp:1082]: Is it really needed to remove the `const`?

File: servers/audio_server.cpp (hunk 1 above)
Comment (vix597) [reply servers/audio_server.cpp:68]: Oh neat, so I don't actually have to lock in update_mix_time, just in the two `get_*` methods. Easy fix.

File: servers/audio_server.cpp (hunk 2 above)
Comment (vix597) [reply servers/audio_server.cpp:1082]: No, I don't HAVE to remove const on the `AudioServer` but I do have to remove it from `AudioDriver` - I removed it because I didn't find any other example of a `const` `AudioServer` method calling a non-const `AudioDriver` method, however I can put it back.

Comment (RandomShaper) [reply servers/audio_server.cpp:1082]: I don't think we have a strong coding standard for these cases. However, since these functions are conceptually constant, let's keep the `const`.

Comment (vix597) [reply servers/audio_server.cpp]: Done.

**Comment by vix597** [comment]
I was able to cherry-pick this commit on branch `3.2` and it builds fine. There is one super minor conflict simply because it appears the style of the 3.2 branch is to have a newline at the beginning of every method while the style of master is not to have that blank line there.

**Review by RandomShaper — APPROVED** [review]

**Comment by RandomShaper** [comment]
Thanks for your patience. I've added the _cherrypick:3.2_ label.

Another solution would have been to mark the mutex as `mutable`, but I think there's no big reason to prefer one over the other, so I can say this is fine now.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
