### PR TITLE
Wayland: Implement the xdg-toplevel-icon-v1 protocol

### LINKED ISSUE #87747: Editor does not use Godot icon on Wayland (uses default Wayland icon instead)
### Tested versions

- Reproducible in: 4.3.dev cae759949

### System information

Godot v4.3.dev (cae759949) - Fedora Linux 39 (KDE Plasma) - Wayland - GLES3 (Compatibility) - NVIDIA GeForce RTX 4090 (nvidia; 545.29.06) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

The editor doesn't use Godot icon on Wayland; it uses the default Wayland icon instead. This is printed when the editor starts:

```
WARNING: Icon not supported by this display server.
     at: set_icon (servers/display_server.cpp:587)
```

This isn't printed when running the project directly with the `--path` command line argument.

See the editor icon in top-left corner (default Wayland icon), project icon in bottom-right corner:

image

### Steps to reproduce

Use a Wayland session, enable the **Prefer Wayland** editor setting then restart the editor.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by ArchercatNEO**
Closes #87747
~~Requires libdecor=no to work and~~ Requires a compositor which supports it. As of this commit only KWin supports this protocol.

~~Really not sure when libdecor actually sets the xdg_toplevel so with it enabled I couldn't get it to work but I can confirm that without libdecor on KWin this does work~~
Screenshot_20250603_195429

Works with project icons too
Screenshot_20250603_201132

Adding a name to the icon is for icon themes, if a system theme has an icon called "godot" it will be used instead of whatever godot actually submits in the buffer (I'm guessing a bit here, I don't know of an icon theme that themes godot so I haven't tested. That also means there's a bug where the running app will get themed like it's the godot editor but not sure what the icon name should be in that case)

UPD 1: added libdecor=yes support

### CODE REVIEW

**Comment by deralmas** [comment]
Hi, thank you for the contribution!

I gave a quick look at the patch and at the protocol itself and I'm afraid that some more work might be needed here, mainly in regards to memory/instance management. Because of this and because it's not working on libdecor I'd recommend to mark this PR as a draft.

I'll make a more thorough review soon™ with my concerns in detail and how to fix them.

File: platform/linuxbsd/wayland/wayland_thread.cpp [hunk 1]
```diff
@@ -4081,6 +4110,60 @@ void WaylandThread::window_set_app_id(DisplayServer::WindowID p_window_id, const
...
+	uint32_t *buffer_data = (uint32_t *)mmap(nullptr, data_size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
+
+	// Create the Wayland buffer.
+	struct wl_shm_pool *shm_pool = wl_shm_create_pool(registry.wl_shm, fd, data_size);
+	icon_buffer = wl_shm_pool_create_buffer(shm_pool, 0, icon_size.width, icon_size.height, icon_stride, WL_SHM_FORMAT_ARGB8888);
+	wl_shm_pool_destroy(shm_pool);
+
+	// Fill the cursor buffer with the image data.
+	for (uint32_t index = 0; index < (uint32_t)(icon_size.width * icon_size.height); index++) {
+		int row_index = std::floor(index / icon_size.width);
```
Comment (AThousandShips) [inline platform/linuxbsd/wayland/wayland_thread.cpp]:
```suggestion
		int row_index = Math::floor(index / icon_size.width);
```
Please use the engine methods

File: platform/linuxbsd/wayland/wayland_thread.h [hunk 2]
```diff
@@ -543,6 +547,9 @@ class WaylandThread {
 
 	List<Ref<Message>> messages;
 
+	xdg_toplevel_icon_v1 *xdg_icon;
+	wl_buffer *icon_buffer;
```
Comment (AThousandShips) [inline platform/linuxbsd/wayland/wayland_thread.h]:
```suggestion
	xdg_toplevel_icon_v1 *xdg_icon = nullptr;
	wl_buffer *icon_buffer = nullptr;
```

**Comment by ArchercatNEO** [comment]
Works with libdecor=yes now

**Comment by ArchercatNEO** [comment]
Added an Engine::is_editor_hint() condition for setting the icon name.

Effectively what setting an icon name does, is if you have an icon theme that overrides the godot icon then even if compiled locally the icon from the icon theme will be used instead of the default godot icon (ie no `.desktop` entry requirede). With an icon named `godot.png` in my `~/.local/share/icons/` I managed to get a different icon for godot which is not the one we provided.

Screenshot_20250605_193137

The change is that now running games will not get godot's icon override.

The only people not having an icon name could affect are app developers who somehow have an icon theme for their own app which they prefer over the actual icon of the app which won't be applied when running locally. Users will hopefully have `.desktop` entries if they're getting to the point of theming icons and just setting the buffer will work for everyone else.

File: platform/linuxbsd/wayland/wayland_thread.cpp [hunk 3]
```diff
@@ -29,6 +29,7 @@
 /**************************************************************************/
 
 #include "wayland_thread.h"
+#include "core/config/engine.h"
```
Comment (AThousandShips) [inline platform/linuxbsd/wayland/wayland_thread.cpp:33]:
```suggestion

#include "core/config/engine.h"
```

**Comment by ArchercatNEO** [comment]
Prevent memory leaks when setting icon multiple times

**Comment by ArchercatNEO** [comment]
Rebased to use `generate_from_xml` in SCsub

**Comment by deralmas** [comment]
Hi, I see that this PR is still marked as a draft. Is there anything missing or is it ready for review?

**Comment by ArchercatNEO** [comment]
@deralmas ready for review

**Comment by deralmas** [comment]
Oops I forgot :sweat_smile:

Thanks for the ping, I'll review this shortly!

File: platform/linuxbsd/wayland/wayland_thread.cpp [hunk 4]
```diff
@@ -4081,6 +4116,80 @@ void WaylandThread::window_set_app_id(DisplayServer::WindowID p_window_id, const
...
+
+	Size2i icon_size = p_icon->get_size();
+	ERR_FAIL_COND(icon_size.width != icon_size.height);
+
+	if (!registry.xdg_toplevel_icon_manager) {
+		return;
+	}
+
+	if (xdg_icon) {
+		xdg_toplevel_icon_v1_destroy(xdg_icon);
```
Comment (deralmas) [inline platform/linuxbsd/wayland/wayland_thread.cpp:4133]: Mhh, I wonder, since we're making a new icon every time anyways, wouldn't it be cleaner to just make it, set it and then destroy it in one go?

It looks like it's not required for the icon object to persist after being set, according to [the documentation](https://wayland.app/protocols/xdg-toplevel-icon-v1#xdg_toplevel_icon_v1:request:destroy):

> Destroys the 'xdg_toplevel_icon_v1' object. The icon must still remain set on every toplevel it was assigned to, until the toplevel icon is reset explicitly.

I haven't tried this approach though (did we already discuss this?), lemme know if you already considered it :D

Comment (ArchercatNEO) [reply platform/linuxbsd/wayland/wayland_thread.cpp:4133]: It's possible to create, set and destroy all in one method. The issue comes because in `WaylandThread::window_create`  we need to have an `xdg_icon` available to set the icon when it's created.

Comment (deralmas) [reply platform/linuxbsd/wayland/wayland_thread.cpp:4133]: Ohhh aight. Makes sense! Resolving then.

File: platform/linuxbsd/wayland/wayland_thread.cpp [hunk 5]
```diff
@@ -4081,6 +4116,80 @@ void WaylandThread::window_set_app_id(DisplayServer::WindowID p_window_id, const
...
+		// Games will get icons with the protocol and themed icons with .desktop entries.
+		// NOTE: should be synced with the icon name in misc/dist/linuxbsd/Godot.desktop
+		xdg_toplevel_icon_v1_set_name(xdg_icon, "godot");
+	}
+
+	for (KeyValue<DisplayServer::WindowID, WindowState> &pair : windows) {
+		WindowState &ws = pair.value;
+#ifdef LIBDECOR_ENABLED
+		if (ws.libdecor_frame) {
+			xdg_toplevel *toplevel = libdecor_frame_get_xdg_toplevel(ws.libdecor_frame);
```
Comment (deralmas) [inline platform/linuxbsd/wayland/wayland_thread.cpp:4186]: I'd add an `ERR_FAIL_NULL` just in case. If for whatever reason the thing returns NULL (unmapped windows?) it's going to get null dereferenced and crash in an ugly way:

```suggestion
			xdg_toplevel *toplevel = libdecor_frame_get_xdg_toplevel(ws.libdecor_frame);
			ERR_FAIL_NULL(toplevel);
```

**Review by deralmas — CHANGES_REQUESTED** [review]
One tiny nitpick left. I haven't tested this code but it otherwise looks great!

File: platform/linuxbsd/wayland/wayland_thread.cpp (hunk 5 above)
Comment (ArchercatNEO) [reply platform/linuxbsd/wayland/wayland_thread.cpp:4186]: Would the null check also be needed in `window_create`?

File: platform/linuxbsd/wayland/wayland_thread.cpp (hunk 1 above)
Comment (ArchercatNEO) [reply platform/linuxbsd/wayland/wayland_thread.cpp]: Replacing `std::floor` with `Math::floor` causes a compilation failure (likely because there isn't an overload for integers). If I just remove the call to floor entirely c++ does just default to integer division and correctly loads the icon.

Would removing the call to floor still be clear enough or is this interger division behaviour not reliable across compilers?

Comment (AThousandShips) [reply platform/linuxbsd/wayland/wayland_thread.cpp]: Since there's no actual floating point operation using `floor` is misleading, I'd suggest:
```suggestion
		int row_index = Math::floor(index / (float)icon_size.width);
```
If it's not intended to do integer division and
```suggestion
		int row_index = index / icon_size.width;
```
Otherwise

File: platform/linuxbsd/wayland/wayland_thread.cpp (hunk 5 above)
Comment (deralmas) [reply platform/linuxbsd/wayland/wayland_thread.cpp:4186]: Yea. Although TBH I'm not really sure where in window create you want to add it :sweat_smile:

File: platform/linuxbsd/wayland/wayland_thread.cpp (hunk 1 above)
Comment (deralmas) [reply platform/linuxbsd/wayland/wayland_thread.cpp]: For context, this code got lifted from the custom cursor logic, which has the same quirk.

I think that we should unify this logic in a single method; I can make a follow-up PR once this gets merged.

**Review by deralmas — APPROVED** [review]
Looks good!

**Comment by Repiteo** [comment]
Thanks!

**Comment by sockeye-d** [comment]
Should documentation be added to `DisplayServer::FEATURE_ICON` to indicate it now has Wayland support? It still just says `Windows, macOS, Linux (X11)`
https://github.com/godotengine/godot/blob/14e840dd752884c4d98cb16f5f6f5fb1604c1e3d/doc/classes/DisplayServer.xml#L2575-L2577

**Comment by deralmas** [comment]
Hi, yes, we definitely need to update the docs. It happens, I constantly forget to do that myself xD

Thank you for catching that!
