### PR TITLE
Print warnings when using a Rect2 or AABB with a negative size

### LINKED ISSUE #23711: CanvasItem.draw_rect() culling problems
_bugsquad edit:_ The root of the problem was recognized in this comment: https://github.com/godotengine/godot/issues/23711#issuecomment-439017673

-------
**Godot version:**
3.1 alpha 2

**OS/device including version:**
Windows 10

**Issue description:**
Take a look at the gif below first:

draw_rect

So each box consists of 2 rectangles that are drawn using `draw_rect()`. However when I move the camera so they are positioned at either top or left edge, if one of those rects is outside, both of them disappear. The rects can even be separated, doesn't matter. This even happened at the rightmost edge of screen.

On Discord we suspected it's because of culling. But it doesn't make sense to cull anything because there are visible parts on the screen.

I've tried drawing a lot of rects and got mixed results, but I was unable to understand how exactly it works. Feel free to play around in the minimal reproduction project.

**Minimal reproduction project:**
[draw_rect invisible.zip](https://github.com/godotengine/godot/files/2582779/draw_rect.invisible.zip)

### LINKED ISSUE #25829: Rect2.clip returns incorrect results when using Rect2 containing negative size values
**Godot version:**
Godot 3.1 beta

**OS/device including version:**
Windows 10 Home build 17763.195

**Issue description:**
Using `Rect2.clip` returns incorrect results if one of the `Rect2` objects has a `size` containing negative values.
Other systems using `Rect2` seem to work fine with them, like `draw_rect`.

**Steps to reproduce:**
Here is a simple code example:
```
            var rectA = Rect2(0, 0, 8, 8)
            var rectB = Rect2(2, 2, 8, 8)
            var overlap_AB_OK = rectA.clip(rectB) # Returns Rect2(2, 2, 6, 6)
            var rectC = Rect2(10, 10, -8, -8) # Equivalent to rectB
            var overlap_AC_wrong = rectA.clip(rectC) # Returns Rect2(0, 0, 0, 0)
            var overlap_AC_OK = rectA.clip(rectC.abs()) # Returns the correct value, same as overlap_AB_OK 
```

### LINKED ISSUE #37617: Rect2D .has_point() breaks with negative size values
**Godot version:**
3.2
**OS/device including version:**
MacOS Catalina 10.5.3

**Issue description:**
Rectangles .has_point() returns false when it should return true. In my case, I'm calculating a rectangle based on two points. This is done with subtraction, which results in the rectangle having negative size when one of the points is above or to the left of the other.

**Minimal reproduction project:**
```
var rect = Rect2D(Vector2(100, 100), Vector2(-100, -100));
if rect.has_point(Vector2(50, 50)):
    print("This should print");
else:
    print("But this prints instead");
```

### PR DESCRIPTION
**Pull request by aaronfranke**
Fixes #23711, fixes #25829, fixes #37617 (or at the very least, mitigates them by showing a warning).

One idea mentioned in #37617 is to make the code in Rect2 automatically correct this, but that would be bad for a number of reasons, including performance and the fact that `abs()` might not actually be the desired solution. I think the best idea is to print a warning, letting the user know something's up.

Note 1: I didn't actually test if the warnings show up *specifically* for each of the above bugs, but I would be surprised if they didn't (and if so, they can just be re-opened).

Note 2: I noticed that there were a few typos of `Point2` being used in place of `Point2i`, I fixed them.

Part of this is mutually exclusive with #38310, so if this is merged then #38310 should be closed.

### CODE REVIEW

**Comment by groud** [comment]
I don't think this is a good idea. If I am not mistaking, the negative scale for Rect2 is purposefully used in sprite regions to allow for textures flips, which does make sense.

Generally, adding warning is not a good thing. They add noise for use cases where people might do something on purpose. Either the API is not good, and then we forbid negative scale (which I don't think is a good) idea, either we throw an error. There should not be an "in-between" behavior where you do things almost right.

Also, if a behavior is "undefined", we should define it in the documentation. We don't fix things by just throwing a warning.

**Comment by aaronfranke** [comment]
I don't get what you mean by defining it in the documentation. For some methods, like "has_point", it fails with negative size. How is documenting "It doesn't work" better than having a warning?

> We don't fix things by just throwing a warning.

Well, this is a common approach in many pieces of software. Giving up and throwing errors was one of the unique things that Unix did to stay lean and performant.

Maybe the warnings need to only show up for some methods, to allow some uses without yelling at the user? I'll add "needs testing" then.

**Comment by groud** [comment]
> I don't get what you mean by defining it in the documentation. For some methods, like "has_point", it fails with negative size. How is documenting "It doesn't work" better than having a warning?

If it does not work consistently with negative scales, then it is a bug, which should be fixed. And if it has an undefined behavior, then we should instead document the behavior in the documentation. Adding a warning stating "this behavior is undefined" instead of fixing the problem itself, when the problem is easy to solve, is probably the worst solution to the problem.

> Well, this is a common approach in many pieces of software. Giving up and throwing errors was one of the unique things that Unix did to stay lean and performant.

When the program crashes, it's not a problem to throw logs to explain why. When it does not crashes, like Godot does, we should avoid warning as much as possible, especially when there is a valid use case to the feature.

> Maybe the warnings need to only show up for some methods, to allow some uses without yelling at the user? I'll add "needs testing" then.

No, as I said it is definitely better to implement a correct version of all functions there, and document the behavior in such case. If it needs to automatically transform the rect to a positive scale, then it should be stated in the documentation.

File: core/math/rect2.h [hunk 1]
```diff
@@ -43,11 +43,23 @@ struct Rect2 {
 	const Vector2 &get_position() const { return position; }
 	void set_position(const Vector2 &p_pos) { position = p_pos; }
 	const Vector2 &get_size() const { return size; }
-	void set_size(const Vector2 &p_size) { size = p_size; }
+	void set_size(const Vector2 &p_size) {
+		size = p_size;
+#ifdef MATH_CHECKS
```
Comment (reduz) [inline core/math/rect2.h:48]: this check does not need to be here, all others seem good

**Review by mhilbrunner — COMMENTED** [review]
PR meeting:
1. This is good and we want to merge.
2. This should be an error, not a warning
3. It needs an `unlikely` added to the if checks
4. We need to make sure docs state negative sizes aren't supported
5. It should say unsupported, not undefined

Thank you for contributing!

**Comment by aaronfranke** [comment]
2. Done
3. Done
4. I wasn't sure if I should add this for each method or just on the struct description. I added it to the struct description.
5. Done

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Merged as discussed in the PR meeting.
Thanks for the doing the changes!

**Comment by lawnjelly** [comment]
Didn't realise this was being cherry picked for 3.x. Could be a bad idea as canvas renderers extensively use negative sizes for flipping purposes.

**Comment by akien-mga** [comment]
There are various issues caused by this change (linked above) which warrant more discussion on whether this was a good idea.

For now I'm reverting it in `3.x` (thus fixing #56509) and we can decide what to do for `master` (and eventually do the same for `3.x`).
