### PR TITLE
Fix script used as type gone too early (3.2)

### LINKED ISSUE #43042: Error "opcode #38 (report please)" when to a custom class
I found another report of opcode 38: #43023

**Godot version:**
3.2.4.beta1

**OS/device including version:**
Windows 10

**Issue description:**
I created a scene with root node with a script attached that has a custom class. I instantiated the scene, and tried to cast to the custom class. Expected the cast to succeed. Got the following error:

```
Internal Script Error! - opcode #38 (report please).
```

Errors panel says:

```
E 0:00:00.757   call: Condition ' !base_type ' is true. Breaking..:
  <Fuente C++>  modules/gdscript/gdscript_function.cpp:938 @ call()
  <Stack Trace> Core.gd:6 @ _ready()
```

**Steps to reproduce:**

1. Create a new project. Add two (2D) scenes. Let us call them "Main.tscn" and "Item.tscn"
2. In Item.tscn, attach a script to the root note (A Node2D), with this code:

```
extends Node2D

class_name Item
```

3. In Main.tscn, add a node with an attached script, with this code:

```
extends Node2D

onready var item = load("Item.tscn");

func _ready():
    var created_item = item.instance() as Item; #error here
    add_child(created_item);
```

This can be worked around by not casting. Without casting, we can still use `call` et.al. to interact with the script.

**Minimal reproduction project:**

[Test.zip](https://github.com/godotengine/godot/files/5431493/Test.zip)

### LINKED ISSUE #43166: == returns false for references to the same object, sometimes.
**Godot version:**
3.2.4 beta

**OS/device including version:**
macOS Catalina 10.15.6

**Issue description:**

When running the tests for the GUT framework using 3.2.4 beta I found some tests failing when checking to see if two references to an object were the same.  When printed out though, the `str` of both objects shows the  same object.  

When run against earlier versions of Godot these tests pass.  Some of the tests that are failing have been passing for a couple years now.

**Steps to reproduce:**
I have not been able to reproduce the issue outside of the GUT project.  I've tried to create a standalone script that would replicate the issue but I've not been able to.  If I put the same "failing" code from a test into a standalone script it works as expected.  

Here is the simplest test case I was able to create.  This tries to minimize the use of GUT.  GUT should only be creating an instance of this script and running the `test_using_local_copy_of_connection_check_logic` method in this case.  GUT does A LOT of other things though, so it's still feasible that GUT is doing something bad, but that seems unlikely given this code has worked for a long time now.
```python
extends 'res://addons/gut/test.gd'

const SIGNAL_NAME = 'test_signal'
const METHOD_NAME = 'test_signal_connector'

class Signaler:
	signal test_signal

class ConnectTo:
	func test_signal_connector():
		pass

# Simulates the check used by assert_connected when a method name is
# not specified.  Checks for a connection between the two objects for
# the given signal without caring about what method it is connected to.
func _check_if_connected(signaler_obj, connect_to_obj, signal_name):
	var connections = signaler_obj.get_signal_connection_list(signal_name)
	for conn in connections:
		print('source/signaler:  ', conn.source, '==', signaler_obj, ' is ', conn.source == signaler_obj)
		print('target/connect_to:  ', conn.target, '==', connect_to_obj, ' is ', conn.target == connect_to_obj)
		if((conn.source == signaler_obj) and (conn.target == connect_to_obj)):
			return true
	return false

func test_using_local_copy_of_connection_check_logic():
	var s = Signaler.new()
	var c = ConnectTo.new()
	s.connect(SIGNAL_NAME, c, METHOD_NAME)
	print('check result = ', _check_if_connected(s, c, SIGNAL_NAME))
```
which  generates the output:
```
res://test/integration/test_345_beta_issues_simple.gd
* test_using_local_copy_of_connection_check_logic
source/signaler:  [Reference:2619]==[Reference:2619] is False
target/connect_to:  [Reference:2620]==[Reference:2620] is False
check result = False
```
The print statements in `_check_if_connected` shows both references are the same in both cases (2619 = 2619 and 2620 = 2620) but the `==` check shows `false`.

**Note** This does not happen just when checking connections.  This was just the simplest example I was able to come up with.  Another area where tests were failing had to do with creating dynamic objects that have a dictionary of instances set using `instance_from_id`.  I tried recreating the issue using dictionaries b/c that started to smell like the problem but was not able to recreate the issue in a standalone script.

**Minimal reproduction project:**

I'm happy to try to create a more simplified example if needed.  After putting a couple hours into this I figured it was time to stop unless you need more information.

I created a branch that has some tests and examples in it.
https://github.com/bitwes/Gut/tree/godot_324_bugs

If you run this command after downloading the branch you'll see the failing tests:
```
<path-to-godot> -s res://addons/gut/gut_cmdln.gd  -d   -gselect=test_345_beta_issues_simple.gd
```

You can run all the tests with this command:
```
<path-to-godot> -s res://addons/gut/gut_cmdln.gd  -d
```
The related failing tests are (there are around 19 tests that are supposed to fail, the ones below should not):
* test_when_target_connected_to_source_connected_passes_without_method_name
* test_spy_is_set_in_metadata
* test_doubled_have_ref_to_stubber
* test_double_sets_stubber_for_doubled_class

## Bug related files:
The test script shown above
https://github.com/bitwes/Gut/blob/godot_324_bugs/test/integration/test_345_beta_issues_simple.gd

Ported test code to a standalone script which acts as expected.  This script also calls the test script code directly which also acts as expected.
https://github.com/bitwes/Gut/blob/godot_324_bugs/scratch/324_simple.gd
run with `<path-to-godot> --path $PWD -s scratch/324_simple.gd`

A mangled mess trying to replicate the issue in a standalone script.  None of which worked.
https://github.com/bitwes/Gut/blob/godot_324_bugs/scratch/324_bugs.gd

### PR DESCRIPTION
**Pull request by RandomShaper**
Following up on what I explained in #42323, it seems that the problem with `Variant`'s `Object *` constructor was very needed. The only thing that was preventing me from doing it is that GDScript was leveraging the wrong behavior. However, it seems that @vnen already fixed that.

I've cherry-picked the commit that removes that naughtiness from GDScript and the definitive fix for `Variant` has become possible. `Variant` will now manage the lifetime of a `Reference` nicely even if it's assigned via the `Object *` constructor. As I explained in the mentioned PR, without that fix, two incompatible reference counting mechanisms were being used simultaneously, which was nothing else than summoning the most terrible forces in a cold and stormy night.

**NOTE:** 4.0 already gets this right.

Fixes #43042.

**UPDATE:** Fixes #43166.

### CODE REVIEW

**Comment by akien-mga** [comment]
Release builds fail with:
```
core/variant.cpp:2347:14: error: no member named 'rc' in 'Variant::ObjData'
                _get_obj().rc = NULL;
                ~~~~~~~~~~ ^
1 error generated.
```

**Comment by ChainedLupine** [comment]
I'm still researching what is going on (still pretty new to Godot internals) but I think this is causing problems if I try to use duplicate with a GDScript class only meant to hold data.  I am using the Resource::duplicate() to make copies at points and I am getting an unhandled exception in Object::set.

I've applied this PR on top of a fresh copy of 3.2.4 beta 1 BTW.

**Comment by RandomShaper** [comment]
@ChainedLupine, a minimal reproduction project would be appreciated.

**Comment by ChainedLupine** [comment]
> 
> 
> @ChainedLupine, a minimal reproduction project would be appreciated.

Here you go!

[PR43049.zip](https://github.com/godotengine/godot/files/5448269/PR43049.zip)

File: modules/gdscript/gdscript_function.cpp [hunk 1]
```diff
@@ -269,6 +269,7 @@ Variant GDScriptFunction::call(GDScriptInstance *p_instance, const Variant **p_a
 	r_err.error = Variant::CallError::CALL_OK;
 
 	Variant self;
+	Variant static_ref;
```
Comment (vnen) [inline modules/gdscript/gdscript_function.cpp:272]: It seems this is not being set. If you cherry-picked my commit directly you also have to pick the fixup: https://github.com/godotengine/godot/commit/0f1da724924fc494bfd316c57757e0e1d7b90143

**Review by vnen — CHANGES_REQUESTED** [review]

File: modules/gdscript/gdscript_function.cpp (hunk 1 above)
Comment (RandomShaper) [reply modules/gdscript/gdscript_function.cpp:272]: Alright. Done!

**Comment by RandomShaper** [comment]
I've cherry-picked a fixup by @vnen that was needed.

@ChainedLupine, I don't have time now to test your project. Could you test this PR again on it?

**Review by vnen — APPROVED** [review]

**Comment by ChainedLupine** [comment]
Just to verify I reverted to 2e073ecbeaf5b502c2b8c3c0510e4a22a56db58 and I'm not getting the crash.  It's definitely something in this PR which is causing a problem with duplicate().

**Comment by akien-mga** [comment]
I can confirm that with the latest `3.2` commit (318ae4d047ccde74c2a1e2b3af7f030c35cb108e) (+ local cherry-picks unrelated to GDScript) I don't get any issue with the project in https://github.com/godotengine/godot/pull/43049#issuecomment-717559858.

Haven't tried with the PR yet but this needs to be addressed before merging.

**Comment by ChainedLupine** [comment]
I've narrowed it down to the changes in variant.cpp.  For some reason, when Object::set_script occurs in the cloned Resource, the script_instance seems to refer to a ScriptInstance with no implementation.  So when script_instance::set occurs, there's an unhandled exception.

**Comment by RandomShaper** [comment]
I've been investigating this. The same happens in 4.0, where `Variant::Variant(Object *)` "detects" `Reference`s, as this PR does.

The problem is that if a `Reference` which has not gotten it's ref. count initialized is assigned to a `Variant`, it will initialize it and then decrement it at destruction. The result is that the object is released.

That is happening to the `self` variable in `GDScriptFunction::call()`, when called during the duplication of the resource. The moment the `script` property is copied and such script is called on a still-unreferenced `Reference` which is the duplicate `Resource`.

I can think of two ways to fix this:
1. Modify `Resource::duplicate()` so that the `Ref<Resource>(r)` is created from the very beginning.
2. Modify `Variant` so it doesn't increment/decrement the ref. count of a `Reference` if it's not already initialized when it's assigned.

I'd like to hear @vnen's opinion again. I'm not sure if option 2) would have unintended side effects. We could just do 1) and consider an error assigning a not yet referenced `Reference` to `Variant`.

**Comment by RandomShaper** [comment]
@ChainedLupine, by the way, thanks for the test project and your insights!

**Comment by ChainedLupine** [comment]
Aha!  That explains why the self reference is hollowed out after it finishes running the initializer during set_script, because it's pointing to just the abstract class and not a real object.  Now I understand what is going on.

@RandomShaper Thanks for figuring it out, I am so glad I could help!

**Comment by RandomShaper** [comment]
To recap on the situation:
- What this PR does seem to be correct.
- If fixes some issues that were introduced by "the dangling `Variant` fix".
- However, since this PR makes `Variant` more clever (the same way it is in 4.0), it uncovers a bug that is both on 3.2 and 4.0, which I explained in a comment above.
- The plan could be getting the issue common to 3.2 and 4.0 fixed and then merge this, or if the benefits this PR provide are considered bigger than the uncovered issue, merge it right away and file a bug for such issue, which anyway needs to be addressed before the next release.

**Review by akien-mga — APPROVED** [review]
Let's merge to fix the identified regressions, and open a new bug report to track the regression already present in the `master` branch and which this PR is exposing to 3.2.

**Comment by akien-mga** [comment]
Thanks!
