### PR TITLE
Fix missing gizmo update when selection changes outside of 3D view

### LINKED ISSUE #106713: Editor Light Gizmos bug when switching to code and back
### Tested versions

- Present in 4.4.1

### System information

Godot v4.4.1.stable - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 32.0.15.6614) - AMD Ryzen 9 3900X 12-Core Processor (24 threads)

### Issue description

Light gizmos disappear or appear at the last seen place when you switch from 3D to Script and back to 3D

https://github.com/user-attachments/assets/57e2b5d8-1c16-4fa4-b7df-e87997998994

### Steps to reproduce

1. Create some DirectionalLight3Ds or SpotLight3Ds on a 3D scene
2. Select one of them
3. Switch to Script
4. Select a different light
5. Go back to 3D 

### Minimal reproduction project (MRP)

[bugreport.zip](https://github.com/user-attachments/files/20385992/bugreport.zip)

### PR DESCRIPTION
**Pull request by kilian-hu**
Fixes https://github.com/godotengine/godot/issues/106713

### CODE REVIEW

**Comment by fire** [comment]
If we want to get this merged for Godot Engine 4.5, there cannot be branch conflicts.

**Review by Rudolph-B — APPROVED** [review]
I tested locally, the issue is resolved for me. I'm unfamiliar with the editor codebase, so I can't really speak about the implementation.

>Godot v4.5.beta (2f8683006) - Ubuntu 24.04.2 LTS 24.04 on X11 - X11 display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (nvidia; 575.64.03) - AMD Ryzen 7 3700X 8-Core Processor (16 threads) - 14.76 GiB memory

File: editor/scene/3d/node_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -8043,6 +8043,15 @@ void Node3DEditor::_selection_changed() {
...
 		selected = nullptr;
 	}
+
+	const List<Node *> &top_selected = editor_selection->get_top_selected_node_list();
+	if (top_selected.size() == 1) {
+		Node3D *new_selected = Object::cast_to<Node3D>(top_selected.back()->get());
+		if (new_selected != selected) {
+			edit(new_selected);
+		}
+	}
```
Comment (Calinou) [inline editor/scene/3d/node_3d_editor_plugin.cpp]: It might be worth adding a comment above the added block to explain why it's there:

```suggestion
	// Ensure gizmo updates are performed when the selection changes
	// outside of the 3D view (see GH-106713).
	const List<Node *> &top_selected = editor_selection->get_top_selected_node_list();
	if (top_selected.size() == 1) {
		Node3D *new_selected = Object::cast_to<Node3D>(top_selected.back()->get());
		if (new_selected != selected) {
			edit(new_selected);
		}
	}
```

**Comment by Calinou** [comment]
@KoBeWi Does this approach look correct?

**Comment by KoBeWi** [comment]
It doesn't. When 3D editor is visible, it will cause double edits.
Although not sure how to solve it better. The problem is that 3D editor needs `edit()` call to update gizmos, but Script Editor blocks it when it's visible (to prevent losing focus).

Either we need to prevent double edits (by making `spatial_editor->edit()` queued), or adding something like `gizmos_dirty` bool, which would be enabled when selection changes while 3D editor is inactive, and cause gizmos to refresh when the editor becomes visible.

**Comment by kilian-hu** [comment]
@Calinou @KoBeWi thanks, I changed it according to your suggestions. Does it look correct now? My manual tests looked fine.

File: editor/scene/3d/node_3d_editor_plugin.cpp [hunk 2]
```diff
@@ -8043,9 +8043,35 @@ void Node3DEditor::_selection_changed() {
 		selected->update_gizmos();
 		selected = nullptr;
 	}
+
+	// Ensure gizmo updates are performed when the selection changes
+	// outside of the 3D view (see GH-106713).
+	const List<Node *> &top_selected = editor_selection->get_top_selected_node_list();
```
Comment (KoBeWi) [inline editor/scene/3d/node_3d_editor_plugin.cpp]: You could probably skip this if editor is visible.

**Review by KoBeWi — APPROVED** [review]

File: editor/scene/3d/node_3d_editor_plugin.cpp (hunk 2 above)
Comment (kilian-hu) [reply editor/scene/3d/node_3d_editor_plugin.cpp]: Good idea. I changed it and manually tested it. Still works fine.

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
