### PR TITLE
[3.x] fix crash in Variant::get_method_default_arguments when wrong type is passed

### LINKED ISSUE #53120: Crash when duplicating `VisualScriptFunctionCall`
### Godot version

3.4 beta 3

### System information

Ubuntu 21.04, Intel HD 3000

### Issue description

```
	var temp_variable2509 = VisualScriptFunctionCall.new()
	temp_variable2509.set_basic_type(-16)
	temp_variable2509.set_call_mode(3)
	temp_variable2509.duplicate(false)
```
crashes Godot with this backtrace(when compiling with ubsan/asan)
```
modules/visual_script/visual_script_func_nodes.cpp:562:50: runtime error: load of value 4294967280, which is not a valid value for type 'Type'
modules/visual_script/visual_script_func_nodes.cpp:612:47: runtime error: load of value 4294967280, which is not a valid value for type 'Type'
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] godots() [0x17bd100] (/home/rafal/Pulpit/godot/platform/x11/crash_handler_x11.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x41040) [0x7f7f6f0b6040] (??:0)
[3] Map<StringName, _VariantCall::FuncData, Comparator<StringName>, DefaultAllocator>::find(StringName const&) const (/home/rafal/Pulpit/godot/./core/map.h:509)
[4] Variant::get_method_default_arguments(Variant::Type, StringName const&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1441)
[5] VisualScriptFunctionCall::_validate_property(PropertyInfo&) const (/home/rafal/Pulpit/godot/modules/visual_script/visual_script_func_nodes.cpp:612)
[6] ClassDB::get_property_list(StringName, List<PropertyInfo, DefaultAllocator>*, bool, Object const*) (/home/rafal/Pulpit/godot/core/class_db.cpp:947)
[7] VisualScriptFunctionCall::_get_property_listv(List<PropertyInfo, DefaultAllocator>*, bool) const (/home/rafal/Pulpit/godot/modules/visual_script/visual_script_func_nodes.h:37 (discriminator 15))
[8] Object::get_property_list(List<PropertyInfo, DefaultAllocator>*, bool) const (/home/rafal/Pulpit/godot/core/object.cpp:648)
[9] Resource::duplicate(bool) const (/home/rafal/Pulpit/godot/core/resource.cpp:209)
[10] MethodBind1RC<Ref<Resource>, bool>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:1333 (discriminator 9))
[11] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:918 (discriminator 1))
[12] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1173 (discriminator 1))
[13] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1037)
[14] GDScriptInstance::_ml_call_reversed(GDScript*, StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1199)
[15] GDScriptInstance::call_multilevel_reversed(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1207)
[16] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:149)
[17] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:45 (discriminator 14))
[18] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:162 (discriminator 3))
[19] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:37 (discriminator 3))
[20] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:929)
[21] Node::_propagate_ready() (/home/rafal/Pulpit/godot/scene/main/node.cpp:188)
[22] Node::_propagate_ready() (/home/rafal/Pulpit/godot/scene/main/node.cpp:178 (discriminator 2))
[23] Node::_set_tree(SceneTree*) (/home/rafal/Pulpit/godot/scene/main/node.cpp:2560)
[24] SceneTree::init() (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:465)
[25] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3635)
[26] godots(main+0x326) [0x17b3d8c] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:57)
[27] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xd5) [0x7f7f6f09d565] (??:0)
[28] godots(_start+0x2e) [0x17b39ae] (??:?)

```

### Steps to reproduce

above

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by LATRio**
fixes #53120

### CODE REVIEW

File: core/variant_call.cpp [hunk 1]
```diff
@@ -1438,13 +1438,12 @@ Variant::Type Variant::get_method_return_type(Variant::Type p_type, const String
...
+	ERR_FAIL_INDEX_V(p_type, Variant::VARIANT_MAX, Vector<Variant>());
 	const _VariantCall::TypeFunc &tf = _VariantCall::type_funcs[p_type];
 
 	const Map<StringName, _VariantCall::FuncData>::Element *E = tf.functions.find(p_method);
-	if (!E) {
-		return Vector<Variant>();
-	}
-
+	ERR_FAIL_COND_V(!E, Vector<Variant>());
+
```
Comment (akien-mga) [inline core/variant_call.cpp:1446]: There seems to be trailing whitespace on this line, according to style checks.

File: core/variant_call.cpp [hunk 2]
```diff
@@ -1438,13 +1438,12 @@ Variant::Type Variant::get_method_return_type(Variant::Type p_type, const String
...
 Vector<Variant> Variant::get_method_default_arguments(Variant::Type p_type, const StringName &p_method) {
+	ERR_FAIL_INDEX_V(p_type, Variant::VARIANT_MAX, Vector<Variant>());
 	const _VariantCall::TypeFunc &tf = _VariantCall::type_funcs[p_type];
 
 	const Map<StringName, _VariantCall::FuncData>::Element *E = tf.functions.find(p_method);
-	if (!E) {
-		return Vector<Variant>();
-	}
-
+	ERR_FAIL_COND_V(!E, Vector<Variant>());
```
Comment (akien-mga) [inline core/variant_call.cpp:1445]: I don't know why the original code was this way but are we sure that this should always be an error condition? Or are there valid cases in which `p_method` wouldn't be found but we want to handle it gracefully instead of printing an error?

Comment (LATRio) [reply core/variant_call.cpp:1445]: reduz put it there on master, so decided to copy it as is

File: core/variant_call.cpp (hunk 1 above)
Comment (LATRio) [reply core/variant_call.cpp]: fixed

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
