### PR TITLE
Change sort_custom/bsearch_custom to use Callables

### LINKED ISSUE #22523: Array sort_custom should show a warning or error if the function doesn't exist.
**Godot version:**
3.0 / 3.1

**Issue description:**
There should be a warning or error message when the `sort_custom` fails because of the function not existing, like in the example below. I had a misspelled function name and it took me a while to figure out why it wasn't sorting.

```GDScript
array.sort_custom(self, "non_existent_function")
```

### PR DESCRIPTION
**Pull request by KoBeWi**
Resolves #22523

btw the example code in the docs could be changed to `MyCustomSorter.sort_ascending` after #41919 is fixed

### CODE REVIEW

File: core/variant/array.cpp [hunk 1]
```diff
@@ -371,25 +372,24 @@ void Array::sort() {
...
-	StringName func;
+	Callable func;
 
 	_FORCE_INLINE_ bool operator()(const Variant &p_l, const Variant &p_r) const {
 		const Variant *args[2] = { &p_l, &p_r };
 		Callable::CallError err;
-		bool res = obj->call(func, args, 2, err);
+		Variant res;
+		func.call(args, 2, res, err);
 		if (err.error != Callable::CallError::CALL_OK) {
```
Comment (akien-mga) [inline core/variant/array.cpp:382]: You could make this:
```
ERR_FAIL_COND_V_MSG(err.error != Callable::CallError::CALL_OK, false,
		 "Error calling sorting method: " + Variant::get_callable_error_text(func, args, 1, err));
```

File: doc/classes/Array.xml [hunk 2]
```diff
@@ -553,7 +549,7 @@
 				        return false
 
 				var my_items = [[5, "Potato"], [9, "Rice"], [4, "Tomato"]]
-				my_items.sort_custom(MyCustomSorter, "sort_ascending")
+				my_items.sort_custom(Callable(MyCustomSorter, "sort_ascending"))
```
Comment (akien-mga) [inline doc/classes/Array.xml:552]: Isn't this the whole point of Callables?
```suggestion
				my_items.sort_custom(MyCustomSorter.sort_ascending)
```

File: core/variant/array.cpp [hunk 3]
```diff
@@ -371,25 +372,24 @@ void Array::sort() {
...
-			res = false;
+			ERR_FAIL_V_MSG(false, "Error calling sorting method: " + Variant::get_callable_error_text(func, args, 1, err));
 		}
 		return res;
 	}
 };
-void Array::sort_custom(Object *p_obj, const StringName &p_function) {
-	ERR_FAIL_NULL(p_obj);
+void Array::sort_custom(Callable p_callable) {
```
Comment (akien-mga) [inline core/variant/array.cpp:388]: Could add a separation line before this to make it nicer to read.

File: core/variant/array.cpp [hunk 4]
```diff
@@ -371,25 +372,24 @@ void Array::sort() {
...
+	ERR_FAIL_COND(p_callable.is_null());
```
Comment (akien-mga) [inline core/variant/array.cpp:389]: Is users can pass `Callable()` from script, we might want to add an actual error message here to let them know that it's invalid in nicer words than the default message.

Comment (KoBeWi) [reply core/variant/array.cpp:389]: This check might be unnecessary actually, because it's also checked in `call()` and it only fails if both method and object are null.

File: doc/classes/Array.xml (hunk 2 above)
Comment (KoBeWi) [reply doc/classes/Array.xml:552]: This won't work because of #41919, I already mentioned it above. Should the example be written regardless of this bug?

Comment (akien-mga) [reply doc/classes/Array.xml]: Ah I had missed your comment, I guess if there's a bug you were right to do it this way.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
