### PR TITLE
[3.x] Check thread func in base scripts for argument info

### LINKED ISSUE #62438: Thread.start() doesn't accept default parameter?
### Godot version

Godot_v3.4.4-stable

### System information

Windows 10

### Issue description

I coding like this:

Run my project and press Enter key, it report error:

It's like because of subclass!

### Steps to reproduce

Please run my reprocution project.

### Minimal reproduction project

[ThreadTest.zip](https://github.com/godotengine/godot/files/8988205/ThreadTest.zip)

### PR DESCRIPTION
**Pull request by timothyqiu**
Fixes #62438

In addition to the base-class case, currently `Thread.start()` also complains about mismatched argument number if you try to call a method of built-in class when a script exists.

`master` now uses `Callable` for `Thread.start()` so it's not relevant.

### CODE REVIEW

File: core/bind/core_bind.cpp [hunk 1]
```diff
@@ -2693,12 +2693,18 @@ void _Thread::_start_func(void *ud) {
...
+		while (script.is_valid()) {
+			if (script->has_method(t->target_method)) {
+				MethodInfo mi = script->get_method_info(t->target_method);
+				target_param_count = mi.arguments.size();
+				target_default_arg_count = mi.default_arguments.size();
+				break;
+			}
+			script = script->get_base_script();
+		}
+		if (script.is_null()) {
```
Comment (RandomShaper) [inline core/bind/core_bind.cpp:2707]: Won't this be always false?

Comment (timothyqiu) [reply core/bind/core_bind.cpp:2707]: It'll be false if the method is found in any script (the `break` above is hit).

Comment (RandomShaper) [reply core/bind/core_bind.cpp:2707]: Oh, I must be blind.

**Review by RandomShaper — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
