### PR TITLE
Make 'Line/TextEdit's context menus hide their editing options when in readonly mode

### LINKED ISSUE #28243: LineEdit with editable set to false will always display all actions in the context menu
**Godot version:**
3.1.stable.official

**OS/device including version:**
Mac OS High Sierra (latest)

**Issue description:**
Add a LineEdit control to a scene and set editable to false. Next, enter a default text for the control or just leave it empty.

**Steps to reproduce:**
Run the project. Now right click into the line edit.

As you can see, the options that allow the user to manipulate the content, including undo and redo, are still available.

image

### PR DESCRIPTION
**Pull request by YeldhamDev**
Fixes #28243.

### CODE REVIEW

File: scene/gui/line_edit.cpp [hunk 1]
```diff
@@ -1318,6 +1318,23 @@ void LineEdit::select_all() {
 void LineEdit::set_editable(bool p_editable) {
 
 	editable = p_editable;
+
+	// Reorganize context menu.
```
Comment (akien-mga) [inline scene/gui/line_edit.cpp]: Maybe add a
```
if (editable == p_editable)
	return;
```
to prevent clearing the menu needlessly. Same for TextEdit.

Comment (YeldhamDev) [reply scene/gui/line_edit.cpp]: Done.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
