### PR TITLE
Stop EditorNode from refreshing the current scene tab when not needed

### LINKED ISSUE #97021: UI: Reimporting asset unfocuses it in the inspector
### Tested versions

- Reproducible in: 4.3.stable, presumably all others

### System information

Godot v4.3.stable - macOS 14.6.1 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

Quite simply, when going into the "Import" settings for an asset file, (ex: a jpeg file) the following behaviour occurs:

1. Changing any setting (or not) and clicking the "Reimport" button unfocuses the currently selected asset in the Godot inspector. 
2. To refocus, you have to double click the asset once again.

This is unintuitive and nonsensical, so it's almost certainly a bug, not an intended feature. For example, after reimporting an image with different settings, you almost always want to check what the result looks like, which this bug makes more annoying.

Included is a recording of the behaviour:

https://github.com/user-attachments/assets/e76c7aba-016d-473b-9832-b83a52b8b97e

### Steps to reproduce

Manually reimport any currently selected asset

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by chocola-mint**
Fixes https://github.com/godotengine/godot/issues/97021

This PR refocuses the currently-focused asset in the inspector after pressing the reimport button.

https://github.com/user-attachments/assets/b9613783-f7a0-4781-84fc-a51936aa6df5

### CODE REVIEW

**Review by karaarslancagri — APPROVED** [review]

File: editor/import_dock.cpp [hunk 1]
```diff
@@ -633,6 +633,10 @@ void ImportDock::_advanced_options() {
 }
 
 void ImportDock::_reimport() {
+	//get the current object in the inspector
```
Comment (Calinou) [inline editor/import_dock.cpp:636]:
```suggestion
	// Get the current object in the inspector.
```

File: editor/import_dock.cpp [hunk 2]
```diff
@@ -685,12 +689,25 @@ void ImportDock::_reimport() {
 		}
 
 		config->save(params->paths[i] + ".import");
+
+		//if the list of resources to import includes the currently-edited object in the inspector, save its path so we can load its reimported version later.
```
Comment (Calinou) [inline editor/import_dock.cpp:693]:
```suggestion
		// If the list of resources to import includes the currently-edited object in the inspector,
		// save its path so we can load its reimported version later.
```

File: editor/import_dock.cpp [hunk 3]
```diff
@@ -685,12 +689,25 @@ void ImportDock::_reimport() {
...
+		}
 	}
 
 	EditorFileSystem::get_singleton()->reimport_files(params->paths);
 	EditorFileSystem::get_singleton()->emit_signal(SNAME("filesystem_changed")); //it changed, so force emitting the signal
 
 	_set_dirty(false);
+
+	//load the reimported version of the edited resource and push it to EditorNode
+	//this needs to be deferred because the scene tree will also try to regain focus after reimport
```
Comment (Calinou) [inline editor/import_dock.cpp:706]:
```suggestion
	// Load the reimported version of the edited resource and push it to EditorNode.
	// This needs to be deferred because the scene tree will also try to regain focus after reimport.
```

**Review by Calinou — COMMENTED** [review]
The approach makes sense to me and code looks good, but I can't vouch as for whether it's a clean way to achieve this.

File: editor/import_dock.cpp [hunk 4]
```diff
@@ -633,6 +633,10 @@ void ImportDock::_advanced_options() {
 }
 
 void ImportDock::_reimport() {
+	//get the current object in the inspector
+	Object *inspector_current_object = ObjectDB::get_instance(EditorNode::get_singleton()->get_editor_selection_history()->get_current());
```
Comment (akien-mga) [inline editor/import_dock.cpp:637]: This seems a bit convoluted, we might have an easier way to access the currently edited object (@KoBeWi might know).

File: editor/import_dock.cpp (hunk 2 above)
Comment (AThousandShips) [reply editor/import_dock.cpp:693]: I'd remove the hyphen as well:
```suggestion
		// If the list of resources to import includes the currently edited object in the inspector, save its path so we can load its reimported version later.
```

File: editor/import_dock.cpp (hunk 4 above)
Comment (KoBeWi) [reply editor/import_dock.cpp:637]: `InspectorDock::get_inspector_singleton()->get_edited_object()`

File: editor/import_dock.cpp [hunk 5]
```diff
@@ -685,12 +690,26 @@ void ImportDock::_reimport() {
 		}
 
 		config->save(params->paths[i] + ".import");
+
+		// If the list of resources to import includes the currently edited object in the inspector,
+		// save its path so we can load its reimported version later.
```
Comment (AThousandShips) [inline editor/import_dock.cpp:695]:
```suggestion
		// Save its path so we can load its reimported version later.
```

**Comment by WhalesState** [comment]
This will also be useful for `Advanced Font Import Settings`.

**Comment by KoBeWi** [comment]
After clicking Reimport, inspector's `edit()` is called 3 times: for the imported object, for the currently selected node and for the imported object again (added in this PR). This is indeed a hacky solution that adds yet another inspector update to cover a deeper bug. Instead it's better to prevent the second inspector update.

**Comment by chocola-mint** [comment]
Sorry for the two-month delay. I've been busy to say the least.

Anyway, from what I can see, the root cause seems to be that `EditorNode` always refreshes the current scene tab on resource imports, which shouldn't be necessary outside of the case where the current scene itself is reimported. I've changed my fix accordingly.

File: editor/editor_node.cpp [hunk 6]
```diff
@@ -1111,6 +1111,17 @@ void EditorNode::_resources_reimported(const Vector<String> &p_resources) {
 		ap->stop(true);
 	}
 
+	// Only refresh the current scene tab if it's been reimported.
+	// Otherwise the scene tab will try to grab focus unnecessarily.
+	bool should_refresh_current_scene_tab = false;
+	String current_scene_tab = editor_data.get_scene_path(current_tab);
```
Comment (KoBeWi) [inline editor/editor_node.cpp:1117]:
```suggestion
	const String current_scene_tab = editor_data.get_scene_path(current_tab);
```

File: editor/editor_node.cpp [hunk 7]
```diff
@@ -1111,6 +1111,17 @@ void EditorNode::_resources_reimported(const Vector<String> &p_resources) {
...
+	for (const String &E : scenes_reimported) {
+		if (E == current_scene_tab) {
```
Comment (KoBeWi) [inline editor/editor_node.cpp:1119]:
```suggestion
	for (const String &scene : scenes_reimported) {
		if (scene == current_scene_tab) {
```

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
