### PR TITLE
Better error display in debugger panel

### LINKED ISSUE #67451: 4.0.x C# error messages needlessly obfuscated
### Godot version

4.0.x + .NET (all versions until at least beta3 inclusive)

### System information

any .NET-supporting (Windows e.g.)

### Issue description

As of 4.0.x, the errors emitted by .NET runtime are wrapped with C++ exception and reported as such. Although the usual information from the C# exception is available, it's not directly visible, and the 1st-order culprit is always the `Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Call(IntPtr , Godot.NativeInterop.godot_string_name* , Godot.NativeInterop.godot_variant** , Int32 , Godot.NativeInterop.godot_variant_call_error* , Godot.NativeInterop.godot_variant* ): `, which is completely redundant in the logs:

image

All the useful information is hidden under the tree:

image

Since this is a debugging message, it should be as clear and useful as possible. Current opening line hardly says anything, and since 99% of the runtime errors in case of a Godot app with C# scripting will be reported this way, In 3.5.x (and previous), this was a lot more sane:

image

, which could be expanded to

image

Basically, the expected fix would be to change the reported debugging error message from

```
Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Call(IntPtr , Godot.NativeInterop.godot_string_name* , Godot.NativeInterop.godot_variant** , Int32 , Godot.NativeInterop.godot_variant_call_error* , Godot.NativeInterop.godot_variant* ): System.NullReferenceException: Object reference not set to an instance of an object.
  <C++ Error>    Exception
  <C++ Source>   C:\Codes\Godot\_Projects\SolitaireWarrior\scripts\Logic\BattleSceneController.cs:24 @ SolitaireWarrior.Logic.BattleSceneController..ctor(SolitaireWarrior.Logic.BattleScene )()
  <Stack Trace>  BattleSceneController.cs:24 @ SolitaireWarrior.Logic.BattleSceneController..ctor(SolitaireWarrior.Logic.BattleScene )()
                 BattleSceneNode.cs:9 @ void SolitaireWarrior.Nodes.BattleSceneNode._Ready()()
                 Node.cs:1809 @ Boolean Godot.Node.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Int32 , Godot.NativeInterop.godot_variant& )()
                 Node3D.cs:1016 @ Boolean Godot.Node3D.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Int32 , Godot.NativeInterop.godot_variant& )()
                 SolitaireWarrior.Nodes.BattleSceneNode_ScriptMethods_Generated.cs:26 @ Boolean SolitaireWarrior.Nodes.BattleSceneNode.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Int32 , Godot.NativeInterop.godot_variant& )()
                 CSharpInstanceBridge.cs:24 @ Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Call(IntPtr , Godot.NativeInterop.godot_string_name* , Godot.NativeInterop.godot_variant** , Int32 , Godot.NativeInterop.godot_variant_call_error* , Godot.NativeInterop.godot_variant* )()
```

into e.g.

```
SolitaireWarrior.Logic.BattleSceneController..ctor(SolitaireWarrior.Logic.BattleScene )(): System.NullReferenceException: Object reference not set to an instance of an object.
  <C++ Error>    Exception
  <C++ Source>   C:\Codes\Godot\_Projects\SolitaireWarrior\scripts\Logic\BattleSceneController.cs:24 @ SolitaireWarrior.Logic.BattleSceneController..ctor(SolitaireWarrior.Logic.BattleScene )()
  <Stack Trace>  BattleSceneController.cs:24 @ SolitaireWarrior.Logic.BattleSceneController..ctor(SolitaireWarrior.Logic.BattleScene )()
                 BattleSceneNode.cs:9 @ void SolitaireWarrior.Nodes.BattleSceneNode._Ready()()
                 Node.cs:1809 @ Boolean Godot.Node.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Int32 , Godot.NativeInterop.godot_variant& )()
                 Node3D.cs:1016 @ Boolean Godot.Node3D.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Int32 , Godot.NativeInterop.godot_variant& )()
                 SolitaireWarrior.Nodes.BattleSceneNode_ScriptMethods_Generated.cs:26 @ Boolean SolitaireWarrior.Nodes.BattleSceneNode.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Int32 , Godot.NativeInterop.godot_variant& )()
                 CSharpInstanceBridge.cs:24 @ Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Call(IntPtr , Godot.NativeInterop.godot_string_name* , Godot.NativeInterop.godot_variant** , Int32 , Godot.NativeInterop.godot_variant_call_error* , Godot.NativeInterop.godot_variant* )()
```

If, for whatever reason, the current (4.0.x) behaviour would be considered useful (although I don't see how), there could be a config option to select the type of log message emitted.

### Steps to reproduce

1. create any C# project with a runtime error,
2. run,
3. look at the error message

### PR DESCRIPTION
**Pull request by paulloz**
For starters, I found it very weird that we were using the least deep stack frame as the main error message in red (and only info when the stack is closed), so I used the right (IMHO) one instead.  
I also got rid of the odd doubled parenthesis we had in C# errors, so I got rid of them. I imagine it's here for other languages that don't have them already baked in the error.  
Last, for C# exceptions, I added the actual exception type where we simply had "Exception" hard coded before.  

I'd like to change the **C++ Error** and **C++ Source** labels when we're not dealing with C++ errors, but I didn't find a way to do it that didn't feel too hacky. I'm open to suggestions if someone wants to push me in the right direction.

Before:
godot windows editor dev x86_64 mono_gbBklhVeAS
After:
godot windows editor dev x86_64 mono_1G61NJ8Rwc

- Closes https://github.com/godotengine/godot/issues/67451

### CODE REVIEW

**Comment by raulsntos** [comment]
> I'd like to change the **C++ Error** and **C++ Source** labels when we're not dealing with C++ errors, but I didn't find a way to do it that didn't feel too hacky. I'm open to suggestions if someone wants to push me in the right direction.

How about this? I haven't tested it though.

```diff
diff --git a/modules/mono/glue/runtime_interop.cpp b/modules/mono/glue/runtime_interop.cpp
index f0ea0313ea..48cd3ebaee 100644
--- a/modules/mono/glue/runtime_interop.cpp
+++ b/modules/mono/glue/runtime_interop.cpp
@@ -31,6 +31,7 @@
 #include "runtime_interop.h"
 
 #include "core/config/engine.h"
+#include "core/config/project_settings.h"
 #include "core/debugger/engine_debugger.h"
 #include "core/debugger/script_debugger.h"
 #include "core/io/marshalls.h"
@@ -45,6 +46,7 @@
 #include "modules/mono/managed_callable.h"
 #include "modules/mono/mono_gd/gd_mono_cache.h"
 #include "modules/mono/signal_awaiter_utils.h"
+#include "modules/mono/utils/path_utils.h"
 
 #ifdef __cplusplus
 extern "C" {
@@ -84,7 +86,8 @@ void godotsharp_stack_info_vector_destroy(
 void godotsharp_internal_script_debugger_send_error(const String *p_func,
 		const String *p_file, int32_t p_line, const String *p_err, const String *p_descr,
 		bool p_warning, const Vector<ScriptLanguage::StackInfo> *p_stack_info_vector) {
-	EngineDebugger::get_script_debugger()->send_error(*p_func, *p_file, p_line, *p_err, *p_descr,
+	const String file = "res://" + path::relative_to(*p_file, ProjectSettings::get_singleton()->get_project_data_path());
+	EngineDebugger::get_script_debugger()->send_error(*p_func, file, p_line, *p_err, *p_descr,
 			true, p_warning ? ERR_HANDLER_WARNING : ERR_HANDLER_ERROR, *p_stack_info_vector);
 }
 

```

**Comment by paulloz** [comment]
> How about this?

Yep, it works to get rid of the **C++ Source** one. The **C++ Error**, though, is here because we re-use a field that's supposed to be populated only for C++ errors, if I understand correctly. Arguably, it only repeats the information we have on the line above. IDK, it feels nice to have, but it feels weird to have it mislabelled.

File: modules/mono/glue/runtime_interop.cpp [hunk 1]
```diff
@@ -84,7 +86,8 @@ void godotsharp_stack_info_vector_destroy(
 void godotsharp_internal_script_debugger_send_error(const String *p_func,
 		const String *p_file, int32_t p_line, const String *p_err, const String *p_descr,
 		bool p_warning, const Vector<ScriptLanguage::StackInfo> *p_stack_info_vector) {
-	EngineDebugger::get_script_debugger()->send_error(*p_func, *p_file, p_line, *p_err, *p_descr,
+	const String file = "res://" + path::relative_to(*p_file, ProjectSettings::get_singleton()->get_project_data_path());
```
Comment (neikeq) [inline modules/mono/glue/runtime_interop.cpp:89]: What is this needed for? Would it be possible to do this only for paths that are actually part of the project? Clicking one of the stack frames should open that location in the text editor. Currently, this works with files outside the project as well. It would be a pity to lose that.

**Review by neikeq — COMMENTED** [review]
I can't review much else here, as the changes are mainly outside the dotnet module and could affect other languages.

File: modules/mono/glue/runtime_interop.cpp (hunk 1 above)
Comment (paulloz) [reply modules/mono/glue/runtime_interop.cpp:89]: Honestly, this can be scrapped out of the PR. In my humble opinion, this should be handled on the editor side instead. Where we shouldn't just hard-code **C++ Source**.

Comment (neikeq) [reply modules/mono/glue/runtime_interop.cpp:89]: I think this would do the job:

```suggestion
	const String file = ProjectSettings::get_singleton()->localize_path(p_file->simplify_path());
```

Comment (paulloz) [reply modules/mono/glue/runtime_interop.cpp]: Tested with files inside and outside `res://` and it works fine.

**Review by neikeq — APPROVED** [review]
C# side looks good, but this needs more eyes as it can affect other areas.

File: editor/debugger/script_editor_debugger.cpp [hunk 2]
```diff
@@ -901,6 +904,13 @@ void ScriptEditorDebugger::_breakpoint_tree_clicked() {
 	}
 }
 
+String ScriptEditorDebugger::_format_frame_text(const ScriptLanguage::StackInfo *info) {
+	String text = info->file.get_file() + ":" + itos(info->line) + " @ " + info->func;
+	if (!text.ends_with(")"))
+		text += "()";
```
Comment (akien-mga) [inline editor/debugger/script_editor_debugger.cpp:910]: We mandate braces even around single line `if` statements in C++ (not in C# I think).

**Review by akien-mga — APPROVED** [review]
Seems good. The commits should be squashed.

**Comment by paulloz** [comment]
Squashed.

And sorry, I made additional changes in `script_editor_debugger.cpp` 😅

File: editor/debugger/script_editor_debugger.cpp [hunk 3]
```diff
@@ -530,13 +530,24 @@ void ScriptEditorDebugger::_parse_message(const String &p_msg, const Array &p_da
...
+				source_language_name = script_language->get_name();
+				break;
+			}
+		}
+
 		if (!oe.error_descr.is_empty()) {
 			// Add item for C++ error condition.
 			TreeItem *cpp_cond = error_tree->create_item(error);
-			cpp_cond->set_text(0, "<" + TTR("C++ Error") + ">");
+			cpp_cond->set_text(0, "<" + source_language_name + " " + TTR("Error") + ">");
```
Comment (akien-mga) [inline editor/debugger/script_editor_debugger.cpp:547]: This breaks localization, in French it would become "<C++ Erreur>" when it should be "<Erreur C++>" or similar.

You need to use the `%s` substitution to let translators move it around - and likely add a translator comment to clarify the meaning.
Like:
```
# TRANSLATORS: %s is the name of a language, e.g. C++.
cpp_cond->set_text(0, "<" + vformat(TTR("%s Error"), source_language_name) + " " + TTR("Error") + ">");

Same below.

File: editor/debugger/script_editor_debugger.cpp [hunk 4]
```diff
@@ -547,14 +558,17 @@ void ScriptEditorDebugger::_parse_message(const String &p_msg, const Array &p_da
...
+			}
 		}
 
 		TreeItem *cpp_source = error_tree->create_item(error);
-		cpp_source->set_text(0, "<" + (source_is_project_file ? TTR("Source") : TTR("C++ Source")) + ">");
+		cpp_source->set_text(0, "<" + source_language_name + " " + TTR("Source") + ">");
 		cpp_source->set_text(1, source_txt);
 		cpp_source->set_text_alignment(0, HORIZONTAL_ALIGNMENT_LEFT);
-		tooltip += (source_is_project_file ? TTR("Source:") : TTR("C++ Source:")) + " " + source_txt + "\n";
+		tooltip += source_language_name + " " + TTR("Source") + " " + source_txt + "\n";
```
Comment (akien-mga) [inline editor/debugger/script_editor_debugger.cpp:571]: You removed the colon here but not for "C++ Error", that seems inconsistent.

File: editor/debugger/script_editor_debugger.cpp (hunk 3 above)
Comment (akien-mga) [inline editor/debugger/script_editor_debugger.cpp:547]: This might break the "Open C++ Source on GitHub" right click option. See https://github.com/godotengine/godot/pull/66977.
You should also see if this option is shown for C# and what happens when it's selected.

**Comment by akien-mga** [comment]
> And sorry, I made additional changes in `script_editor_debugger.cpp` sweat_smile

Well, that might have been better for another PR as the rest was ready but the new changes aren't ;)

**Comment by paulloz** [comment]
> Well, that might have been better for another PR as the rest was ready but the new changes aren't ;)

I shouldn't reply to PR late, now I feel bad wasting your time. I'll fix everything tomorrow.

**Comment by akien-mga** [comment]
Don't worry, I was being facetious :) The changes seem fine overall, we can take the time needed to polish them.

File: editor/debugger/script_editor_debugger.cpp (hunk 3 above)
Comment (paulloz) [reply editor/debugger/script_editor_debugger.cpp]: Still works fine for C++ sources (nothing basically didn't change for them). For C# we used to open a 404 and now shows the toast error. It's very weird to open the right click menu on C# files anyway because you usually have an external editor set, and even the right click opens the file in the external editor. Might be a good thing to fix in a subsequent PR.

**Review by akien-mga — APPROVED** [review]
Looks great!

**Comment by akien-mga** [comment]
Thanks!

**Comment by Flavelius** [comment]
Is this fix in beta17 ?
(If so, then its still an issue):
grafik
If not, then ignore this.

**Comment by paulloz** [comment]
@Flavelius Can you show one of those errors unrolled? It's still possible to have this kind of message if the error originates from the generated code and not "your" code itself. Not sure about how we could improve that.

**Comment by Flavelius** [comment]
Some are, some are not:
grafik
I noticed that this seems to apply only to warnings though. Errors are logged without the extra stacktrace info
