### PR TITLE
GDScript: Fix typing of iterator in for loop

### LINKED ISSUE #61727: for loop iterator untyped when not using range function
### Godot version

4.0.alpha9.official [fc18891db]

### System information

Linux Arch

### Issue description

The Iterator of a for loop is untyped when writing `for i in 100` instead of `for i in range(100)`

### Steps to reproduce

Create a new script
create a for loop like this:
```swift
for current in 10
    maxi(current, 10)
```
and see that the line number of the maxi() function call is not highlighted in green.
Showing that current is a variant instead of an int

but when writing a for loop like this:
```swift
for current in range(10)
    maxi(current, 10)
```
the same line is highlighted in green, showing that current is typed correctly as an int

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by vonagam**
Fixed missing typings for for-loop iterator:
```gdscript
for i in 1: # i is int
for i in 1.0: # i is float
for i in 'abc': # i is string
for i in custom_iterator: # i is return type of _iter_get
```

Fixed `iter_init` and `iter_next` of float Variant to match that of codegen behaviour:
```gdscript
for i in 1.0:
  print(typeof(i) == TYPE_FLOAT) # currently true
  
var variant_float: Variant = 1.0
for i in variant_float: 
  print(typeof(i) == TYPE_FLOAT) # currently false, now true
```

Marked for-in input as unsafe when variant/weak type is used. 

If a strong non-matching input is provided now an error is produced at analysis stage.

Made level of certainty for an iterator to match that of a provided input, so if an input has a weak type then an iterator will be weak too.

_Bugsquad edit:_ Fix #61727

### CODE REVIEW

**Comment by vonagam** [comment]
Second, will add type for iterator of string. And error message if hard wrong type.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -1722,21 +1722,38 @@ void GDScriptAnalyzer::resolve_for(GDScriptParser::ForNode *p_for) {
...
+			variable_type = list_type.get_container_element_type();
+			variable_type.type_source = list_type.type_source;
+		} else if (list_type.is_typed_container_type()) {
+			variable_type = list_type.get_typed_container_type();
+			variable_type.type_source = list_type.type_source;
+		} else if (list_type.builtin_type == Variant::INT || list_type.builtin_type == Variant::FLOAT || list_type.builtin_type == Variant::STRING) {
+			variable_type.type_source = list_type.type_source;
+			variable_type.kind = GDScriptParser::DataType::BUILTIN;
+			variable_type.builtin_type = list_type.builtin_type;
+		} else if (list_type.builtin_type == Variant::VECTOR2I || list_type.builtin_type == Variant::VECTOR3I) {
```
Comment (adamscott) [inline modules/gdscript/gdscript_analyzer.cpp:1745]: What about [`Vector4`](https://docs.godotengine.org/en/latest/classes/class_vector4.html) and [`Vector4i`](https://docs.godotengine.org/en/latest/classes/class_vector4i.html)?

Comment (adamscott) [inline modules/gdscript/gdscript_analyzer.cpp:1745]: What about [`Vector4`](https://docs.godotengine.org/en/latest/classes/class_vector4.html) and [`Vector4i`](https://docs.godotengine.org/en/latest/classes/class_vector4i.html)?

Comment (adamscott) [reply modules/gdscript/gdscript_analyzer.cpp:1745]: Oh, ok!

Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp:1745]: Yeah, that's why I asked in chat if it is a known feature.

**Comment by kleonc** [comment]
> ```gdscript
> for i in 1: # i is int
> for i in 1.0: # i is float
> for i in 'abc': # i is string
> for i in Vector2i(0, 1): # i is int
> for i in Vector3i(0, 1, 1): # i is int
> for i in Vector2(0.0, 1.0): # i is float
> for i in Vector3(0.0, 1.0, 1.0): # i is float
> ```

@vonagam Not sure about `i` being a float cases. As you've mentioned these are supposed to be equivalent to `range` with relevant args passed in (at least that's how I've always thought of these). And `range` always returns ints (check out the tests I've added in #68125). So if these are meant to be just a shorthands for `range` then I don't think `i` should end up being a float.

(BTW while you're at this and typed arrays maybe you'd want to look into / give any feedback on #67025)

**Comment by vonagam** [comment]
Yes, `range` does convert everything to int. And for-loop resolves it to constant value of `int`, `Vector2i` or `Vector3i` if it is used as loop's list value. But currently on master:
```gdscript
for i in 1.0:
  print(typeof(i) == TYPE_FLOAT) # true
for i in Vector2(0.0, 1.0):
  print(typeof(i) == TYPE_FLOAT) # true
for i in Vector3(0.0, 1.0, 1.0):
  print(typeof(i) == TYPE_FLOAT) # true
```
I removed mention of vectors from description so that not confuse people - I would have assumed that iteration happens on vector elements and not on `range`-like call. It feels like a hack.

Preexisting support for float iterators (in codegen, vm and core) theoretically can be used to provide `rangef` helper.

**Comment by kleonc** [comment]
Hmm, I thought support for iterating over `Vector2`/`Vector3` was kinda just a leftover from the 3.x where there was no integer counterparts and hence `for`-looping over a `range` was resolved it to a constant `Vector2`/`Vector3`, not to `Vector2i`/`Vector3i` like it currently is. In such case I'd see no reason for it to be allowed at all. But seeing it now actually does behave like a potential `rangef` (instead of just ignoring the fractional parts like in 3.x):
```gdscript
for i in Vector3(0.1, 1.0, 0.3):
	print(i)

# Output:
0.10000000149012
0.40000001341105
0.70000002533197
```
then it does make perfect sense for the iterator to be a `float`.

But I think we should add `rangef` function in a subsequent PR, otherwise this will be kinda an invisible feature. AFAICT most users are not aware of being able to iterate over a vector like that. And the fact they don't know about it is not really a bad thing because it's unintuitive. Like `for i in range(1, 5, 2)` vs `for i in Vector3i(1, 5, 2)`. The former you can just check in the docs in case of doubt, the latter is just confusing... what does it mean to iterate over a vector (a geometric one, not a container)? On the other hand iterating over an `int` (or a `float`) is well known / widely used because it does shorten the code (contrary to vector cases). So with `rangef` added it should also be easier to e.g. explain / understand why `for i in some_float` behaves differently than `for i in some_int`.

**Comment by vonagam** [comment]
Just to be clear, this PR is complete and ready for review, there are no plans for implementing `rangef` on my part.

**Review by adamscott — APPROVED** [review]
Looks good to me! Great job for the extensive tests that come with this PR!

**Comment by aaronfranke** [comment]
For the record, using floating-point vectors for iteration has been supported as of #37020, so it makes sense to allow it for standalone floats too.

**Review by vnen — APPROVED** [review]
LGTM

**Comment by akien-mga** [comment]
Thanks!
