### PR TITLE
Replace QuickHull with Bullet's convex hull computer.

### LINKED ISSUE #44090: Lag spike when creating collision shape for mesh instance
**Godot version:**
v3.2.3

**OS/device including version:**

Renderer: GLES3 Renderer,
OS: Ubuntu 20.04.1 LTS
Graphics: NVIDIA Corporation TU106 [GeForce RTX 2060 Rev. A]
Processor: AMD® Ryzen 7 2700x eight-core processor × 16

Using steam version of godot

**Issue description:**
When using the auto-created mesh instance thingy (the "mesh" button you get in the 3d tool bar) and selecting single convex it creates a 1-2 min freeze, then the environment proceeds to be SUPER laggy, especially when the mesh instance is slected 

**Steps to reproduce:**
1. Make an new scene with a rigid body as the scene root
2. get a mesh instance
4. Set radius to 0.05 and mid height to 0.1
5. hit the mesh button
6. Select single convex sibling

**Minimal reproduction project:**

[minimal.zip](https://github.com/godotengine/godot/files/5644110/minimal.zip)

### LINKED ISSUE #45946: QuickHull generates bad hull sometimes when multiple triangles share the same plane.
**Godot version:**
3.2.3
3.2.4.rc2

**OS/device including version:**
Windows 10

**Issue description:**
QuickHull fails to merge edges sometimes and results in generating multiple of the same plane and wrong geometry.  Errors printed to the log include things like:
 core\math\quick_hull.cpp:402 - Condition "O == 0" is true. Continuing.
 core\math\quick_hull.cpp:399 - Condition "!F" is true. Continuing.
 core\math\quick_hull.cpp:428 - Condition "!F2" is true. Continuing.

Example:
image
Edit: Just tried in 3.2.4.rc2, and the result was slightly different, but still broken:
image
(Should just be an octagon)

**Steps to reproduce:**
Generate a convex collision from something like a cylinder or another object that has many triangles on the same face, preferably at some odd angle.  Doesn't always reproduce.

**Notes:**
I've stepped through the QuickHull::build() function, and the problem seems to reside in the logic to merge faces and remove edges on a single plane.  It makes some assumptions about the structure/order of vertices.  If things overlap instead of being next to each other, the algorithm falls apart.  When the errors happen, extra planes are left in the hull that shouldn't be there.

It might be better to just generate the the planes, ignoring edges and verts, then generate the edges and verts at the end based on plane intersections.  It would also be nice if the edge generation was optional, because it's only necessary when displaying the hull, not when using it for collision purposes.

**Minimal reproduction project:**
[test_quickull.zip](https://github.com/godotengine/godot/files/5975048/test_quickull.zip)

### PR DESCRIPTION
**Pull request by mortarroad**
The same as https://github.com/godotengine/godot/pull/48533, but ported to master.

*Bug squad edit:* fixes #44090, fixes #45946

### CODE REVIEW

File: core/math/convex_hull.cpp [hunk 1]
```diff
@@ -0,0 +1,2276 @@
...
+
+#include <string.h>
+
+#include "aabb.h"
+#include "convex_hull.h"
+
+#include "core/error/error_macros.h"
+#include "core/math/math_defs.h"
+#include "core/os/memory.h"
+#include "core/templates/paged_allocator.h"
```
Comment (akien-mga) [inline core/math/convex_hull.cpp:53]:
```suggestion
#include "convex_hull.h"

#include "core/error/error_macros.h"
#include "core/math/aabb.h"
#include "core/math/math_defs.h"
#include "core/os/memory.h"
#include "core/templates/paged_allocator.h"

#include <string.h>
```

File: core/templates/paged_allocator.h [hunk 2]
```diff
@@ -89,8 +89,10 @@ class PagedAllocator {
 		allocs_available++;
 	}
 
-	void reset() {
-		ERR_FAIL_COND(allocs_available < pages_allocated * page_size);
+	void reset(bool p_allow_unfreed = false) {
+		if (!p_allow_unfreed || !std::is_trivially_destructible<T>::value) {
```
Comment (akien-mga) [inline core/templates/paged_allocator.h:93]: Needs `<type_traits>` too?

**Comment by pouleyKetchoupp** [comment]
This PR just needs to be synced with the latest changes from #48533 and it will be good to go.

**Review by pouleyKetchoupp — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks for the amazing work!

File: core/math/convex_hull.cpp [hunk 3]
```diff
@@ -0,0 +1,2290 @@
...
+
+#include <string.h>
+
+//#define DEBUG_CONVEX_HULL
+//#define SHOW_ITERATIONS
+
+// -- GODOT start --
+// Assembly optimizations are not used at the moment.
+//#define USE_X86_64_ASM
+// -- GODOT end --
```
Comment (aaronfranke) [inline core/math/convex_hull.cpp:75]: Why? Not objecting, just curious.

Comment (pouleyKetchoupp) [reply core/math/convex_hull.cpp:75]: It would take more time to test on different platforms, and set conditions to enable it only on supported compilers so it's easier to just leave it disabled for now. It's already much faster than QuickHull.

But if inlined assembly does make a measurable difference for performance and someone is up for doing the work, it would be nice to have.

Comment (mortarroad) [reply core/math/convex_hull.cpp:75]: I doubt it makes any difference. If the compiler does not already generate optimal code, maybe it can be adjusted such that it does without using assembly.
If anything, I'd replace it with intrinsics instead.
