### PR TITLE
Fix debugger not opening built-in scripts

### LINKED ISSUE #51594: Built-in scripts don't open when clicking errors in debugger
### Godot version

a98589a

### System information

W10

### Issue description

When you have error in built-in script and it appears in the debugger, the script won't show up if the scene containing it is not opened.

### Steps to reproduce

1. Have error in built-in script
2. Have its scene closed
3. Click the error in debugger

### Minimal reproduction project

[ReproductionProject.zip](https://github.com/godotengine/godot/files/6978927/ReproductionProject.zip)

### LINKED ISSUE #58683: Named built-in scripts can't be opened from debugger
### Godot version

2d210fe

### System information

W10

### Issue description

Regression from #54889
When trying to open script, the debugger will just use the script string it was provided with. In case of built in scripts, the name is scene::id and works ok, but if the script is named, the pattern changes to name (scene)::id and ResourceLoader doesn't know what to do.

### Steps to reproduce

1. Create a built-in script
2. Give it a name
3. Make error in code
4. Run
5. The error script/line will not be selected on error

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by KoBeWi**
Looks like resource loader requires the scene to be opened to load a built-in resource. The fix I did ensures the scene is in memory when trying to open the script, and it actually works.

Fixes #51594
Apparently the same bug exists in 3.x, so not sure how I never noticed it.

EDIT:
Fixes #58683

### CODE REVIEW

File: editor/debugger/editor_debugger_node.cpp [hunk 1]
```diff
@@ -145,7 +146,13 @@ void EditorDebuggerNode::_text_editor_stack_goto(const ScriptEditorDebugger *p_d
...
 		return;
 	}
-	stack_script = ResourceLoader::load(file);
+	if (file.is_resource_file()) {
+		stack_script = ResourceLoader::load(file);
+	} else {
+		// If the script is built-in, it can be opened only if the scene is loaded in memory.
+		Ref<PackedScene> ps = ResourceLoader::load(file.get_slice("::", 0));
+		stack_script = ResourceLoader::load(file);
+	}
```
Comment (akien-mga) [inline editor/debugger/editor_debugger_node.cpp:155]: Could maybe be simplified?
```suggestion
	if (!file.is_resource_file()) {
		// If the script is built-in, it can be opened only if the scene is loaded in memory.
		Ref<PackedScene> ps = ResourceLoader::load(file.get_slice("::", 0));
	}
	stack_script = ResourceLoader::load(file);
```

Comment (akien-mga) [reply editor/debugger/editor_debugger_node.cpp:155]: Nevermind, after posting it I realized that `ps` then goes out of scope and bringing it to the outer scope is meh.

**Review by akien-mga — APPROVED** [review]

**Comment by KoBeWi** [comment]
Looks like this does not handle the case where script is named (#58683)

**Comment by KoBeWi** [comment]
Ok fixed. I had to modify what #54889 did. Now the whole path will be included after name:
image
I used some string magic to extract the path, not sure if there is better way to do it (like sending script name and path separately).

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Needs a dedicated backport PR for `3.x`, the editor debugger is different.

**Comment by KoBeWi** [comment]
Eh, I tried backporting it and the issue doesn't actually happen in the 3.x branch. The script doesn't open on error, but it opens fine when you click the stack trace. Also the script name doesn't even display, so #54889 cherry-pick had no effect? idk

If it works, let's not touch the 3.x branch anymore :/
