### PR TITLE
Ensure Bullet HeightMapShape3D data width and depth are at least 2.

### LINKED ISSUE #40636: Engine crashes when failing assert inside btHeightfieldTerrainShape.cpp
**Godot version:**

4.0.dev.custom_build. 9e34ba485

**OS/device including version:**

Ubuntu 20.04

**Issue description:**

When I run project, then assertion in bullet code crashes project
```
godot4: thirdparty/bullet/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.cpp:59: void btHeightfieldTerrainShape::initialize(int, int, const void*, btScalar, btScalar, btScalar, int, PHY_ScalarType, bool): Assertion `heightStickLength > 1' failed.
```

**Steps to reproduce:**
1. Run project

**Minimal reproduction project:**

[TheWorstGodotTestProject.zip](https://github.com/godotengine/godot/files/4967639/TheWorstGodotTestProject.zip)

**Code**
```
extends Node2D

var q_HeightMapShape3D: HeightMapShape3D = HeightMapShape3D.new()


func _process(delta) -> void:

	if randi() % 2 == 1:
		q_HeightMapShape3D = HeightMapShape3D.new()
	if randi() % 2 == 1:
		q_HeightMapShape3D.set_map_width(get_int())
	if randi() % 2 == 1:
		q_HeightMapShape3D.set_map_depth(get_int())
	if randi() % 2 == 1:
		q_HeightMapShape3D.set_map_data(get_packedfloat32array())


const RANGE : int = 100


func get_int() -> int:
	return randi() % RANGE - RANGE / 2

func get_float() -> float:
	return randf() * RANGE - RANGE / 2
	
	
func get_packedfloat32array() -> PackedFloat32Array:
	var pra : PackedFloat32Array = PackedFloat32Array([])
	for i in range(randi() % 10):
		pra.append(get_float())
	return pra
```

### PR DESCRIPTION
**Pull request by madmiraal**
Fixes #40636.

### CODE REVIEW

File: modules/bullet/shape_bullet.cpp [hunk 1]
```diff
@@ -504,6 +504,8 @@ void HeightMapShapeBullet::set_data(const Variant &p_data) {
 	int l_width = d["width"];
 	int l_depth = d["depth"];
 
+	ERR_FAIL_COND(l_width < 2 || l_depth < 2);
```
Comment (akien-mga) [inline modules/bullet/shape_bullet.cpp:507]: Since it can be caused by invalid user input, there should be a `_MSG` explanation I think.

Comment (madmiraal) [reply modules/bullet/shape_bullet.cpp:507]: I agree, but there are currently no messages for the rest of the checks in this function. I can add messages to them too as part of this PR, but I thought it best to focus on fixing the issue and leave adding messages to a separate PR.

Comment (akien-mga) [reply modules/bullet/shape_bullet.cpp:507]: I haven't looked into details, but given the API of `HeightMapShape3D`:
```
                <member name="map_data" type="PackedFloat32Array" setter="set_map_data" getter="get_map_data" default="PackedFloat32Array( 0, 0, 0, 0 )">
                        Height map data, pool array must be of [member map_width] * [member map_depth] size.
                </member>
                <member name="map_depth" type="int" setter="set_map_depth" getter="get_map_depth" default="2">
                        Depth of the height map data. Changing this will resize the [member map_data].
                </member>
                <member name="map_width" type="int" setter="set_map_width" getter="get_map_width" default="2">
                        Width of the height map data. Changing this will resize the [member map_data].
                </member>
```

I think that the validation of the Dictionary's content is validating internal engine code, so the previous checks are more sanity checks for engine developers (if they fail, it means there's a bug in the engine, and thus we don't need a clear message as the source code is the clearest we have already).

But this one here can fail based on user input (e.g. `map_width = 1`), so this needs to be handled with a user-facing explanation. At least that's where I set the cursor myself.

Comment (akien-mga) [reply modules/bullet/shape_bullet.cpp:507]: Though it's true that `ERR_FAIL_COND(l_min_height > l_max_height);` might also be something that can be triggered by user scripts (again, didn't look into implementation details to confirm).

Comment (madmiraal) [reply modules/bullet/shape_bullet.cpp]: Updated with `ERR_FAIL_COND_MSG`.

**Review by AndreaCatania — APPROVED** [review]
Approved, however I would put a crash condition here and move the ERR_FAIL into the `CollisionShape` node: in this way the error is more naturally taken into account and allows GodotPhysics to doesn't fall into the issue too.

**Comment by madmiraal** [comment]
Although I agree that catching it earlier i.e. when the user tries to assign the value would be good, `HeightMapShape3D` currently only has an expectation that `width` and `depth` are `> 0`. And, although I agree a `HeightMap` of width or depth of 1 doesn't make sense, I didn't want this fix to constraint it for Godot too, in case there is a use case there. Admittedly, the Godot version doesn't work at all, see #40664.

Finally, we should only use `CRASH_COND` when there is no way to recover. In this case it makes more sense to simply not set the data and print an error.

**Comment by akien-mga** [comment]
> Finally, we should only use `CRASH_COND` when there is no way to recover. In this case it makes more sense to simply not set the data and print an error.

Yes I'm against the use of `CRASH_COND` in situations where we can recover. Sure, it's useful for *devs*, but so are normal `ERR_FAIL_COND` if you don't ignore them and fix them. On the other hand, if a `CRASH_COND` ends up triggered in a user project, that's a showstopper. And if we're 100% confident it can't happen in a user project, then we don't need to put a check in the first place.

**Comment by Xrayez** [comment]
I think this should also help #32217, but won't resolve all errors completely because the module is disabled in my case.

**Comment by akien-mga** [comment]
Thanks!

**Comment by AndreaCatania** [comment]
@akien-mga @madmiraal  `CRASH_COND` is a really good way to tell that at a certain point a thing is not supposed to be in a particular state. It's exactly like an assert but not a replacement of `ERR_COND`.

This is nice because, most of the time, the alternative is not check a variable at all:
See this as example https://github.com/godotengine/godot/pull/40604 it was not obvious that `scenario` was not supposed to be `null`, at that point, and only reduz (who did it) knew that - and so was able to fix it.

**Comment by akien-mga** [comment]
IMO `ERR_FAIL_COND` is completely sufficient to point a thing which is not supposed to be in a particular state.

If you get an ERROR message, that's a *bug*, and you should put a breakpoint in the err handler and fix the bug (or just go to the referenced line and fix the issue from context if a backtrace is not needed). A crash cond only saves you the work of setting a breakpoint, it's overkill.

The engine should *never* crash in a stable release.

**Comment by AndreaCatania** [comment]
Yep, for this reason I think that `CRASH_COND` should do nothing in release mode. The issue with `ERR_FAIL_COND` is that you never want to fill the code with such "extra" also "avoidable" checks. So you don't use it, in reality.
While you would use a `CRASH_COND`, which should then elided in release.

So the use of `CRASH_COND` that I immagine is:
```cpp
void set_triangle_count(int p_count){
    ERR_FAIL_COND(p_count <= 0);
    vertices = p_count * 3;
    CRASH_COND(vertices <= 3);
    CRASH_COND(vertices / 3 != p_count);
}
```
The above code could never crash, and explicitly says that the code should be in that way - no matter what.

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.
