### PR TITLE
[iOS export] Restore one-click deploy device enumeration using Xcode.

### LINKED ISSUE #103586: iOS One-Click Deploy not detecting iPhone (but does detect Android)
### Tested versions

- Worked fine in 4.4dev3 this morning, Android + iOS
- 4.4 full release only Android works.

### System information

MacOS 15.1.1, Apple Macbook Air M1, using Mobile renderer

### Issue description

Possible regression: 
As of 4.4dev3 iOS one-click deploy worked fine, after 4.4 installed and exports all updated it no longer detects an iPhone being connected, but XCode does still detect the iPhone and and deploy to it. 

Everything works as it did before using Android devices.

Sorry I don't have any more information

### Steps to reproduce

Follow the iOS export instructions, one-click deploy button remains inactive.

### Minimal reproduction project (MRP)

Sorry no disk space for another project atm

### PR DESCRIPTION
**Pull request by bruvzg**
Regression from https://github.com/godotengine/godot/pull/102179 (it was incorrectly marked as simulator in the comment and accidentally removed).

Fixes https://github.com/godotengine/godot/issues/103586

### CODE REVIEW

File: platform/ios/export/export_plugin.cpp [hunk 1]
```diff
@@ -2735,6 +2735,42 @@ void EditorExportPlatformIOS::_check_for_changes_poll_thread(void *ud) {
...
+		// Enum devices (via Xcode).
+		if (ea->has_runnable_preset.is_set() && _check_xcode_install() && (FileAccess::exists("/usr/bin/xcrun") || FileAccess::exists("/bin/xcrun"))) {
+			String devices;
+			List<String> args;
+			args.push_back("devicectl");
+			args.push_back("list");
+			args.push_back("devices");
+			args.push_back("-j");
+			args.push_back("-");
+			args.push_back("-q");
```
Comment (Calinou) [inline platform/ios/export/export_plugin.cpp:2747]: I believe this can use the list initializer syntax (`List<String> args = { ... }`).

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.4.1.
