### PR TITLE
[Visual Shader] Fix nodes' relative positions changed in a different display scale.

### LINKED ISSUE #97484: Visual Shader looks messy after changed display scale factor
### Tested versions

4.3.stable.mono.official

### System information

Windows 11

### Issue description

I have done a visual shader with a display with 1080p resolution, 100% scaling as this:
图片
But after I switched to another display with 200% scaling, all nodes looks like just enlarged 2x but stay on they orginal position.
It makes nodes look messy and hard to edit.
Screenshot after changed Display Scaling to 200%

### Steps to reproduce

1. Make a Visual Shader in a 1080P, 100% scale display.
2. Close godot project.
3. Set another 2160P, 200% scale display to primary display.
4. Reopen godot project.

### Minimal reproduction project (MRP)

[project.zip](https://github.com/user-attachments/files/17146264/project.zip)

### PR DESCRIPTION
**Pull request by meokit**
Node positions are not affected by theme scale but their sizes are. Fix this by multiplying GraphElements' positions by the theme scale.

Fix #97484 .

It is worth discussing whether is GraphEdit responsible for maintaining a consistent relative distance between GraphElements under different DPIs.

But in any case, before GraphEdit makes such compatibility-breaking changes, it is worthwhile to make Visual Shader Editor work properly at different DPIs.

## Before:

Graph with 100% display scale:

屏幕截图 2024-09-29 231628

Graph with 200% display scale:

屏幕截图 2024-09-29 231955

## After

Graph with 200% display scale:

屏幕截图 2024-09-29 231715

### CODE REVIEW

**Comment by jj11hh** [comment]
accidently closed by renaming branch, reopen now

**Review by Geometror — COMMENTED** [review]
I was concerned that the positions of each node would change in the resource file each time your scale changes (problematic for teams), but this is not the case. However, the size does change. In case you have the time, could you check why this is happening? Otherwise I think it would be fine to merge without the size fix.

**Comment by jj11hh** [comment]
> I was concerned that the positions of each node would change in the resource file each time your scale changes (problematic for teams), but this is not the case. However, the size does change. In case you have the time, could you check why this is happening? Otherwise I think it would be fine to merge without the size fix.

The positions in the resource file will not change by display scale with or without this fix. The editor stores the top-left position to file. But, with a bigger scale, all nodes will be rendered larger, which makes them overlap with each other.

Which makes the same graph look very different on different display scales. Shaders made by creators with a larger scale (may have a hiDPI display) show more sparse than normal on a smaller display scale and vice versa.

This fix makes no change to the **stored** position but applies scale to the nodes' position on canvas to avoid this case.

**Comment by jj11hh** [comment]
> I was concerned that the positions of each node would change in the resource file each time your scale changes (problematic for teams), but this is not the case. However, the size does change. In case you have the time, could you check why this is happening? Otherwise I think it would be fine to merge without the size fix.

I have figured out that the node size is affected by multiple reasons.
The most important thing may be font size. And it is scaled by EDSCALE(editor_fonts.cpp:153.).

image
Window after change editor_fonts.cpp from 
```cpp
	p_theme->set_default_font_size(default_font_size);
```
to
```cpp
	p_theme->set_default_font_size(default_font_size / EDSCALE);
```
Where default_font_size was set to
```cpp
// editor_fonts.cpp:153
	const int default_font_size = int(EDITOR_GET("interface/editor/main_font_size")) * EDSCALE;
```

The editor's theme's base scale is set to EDSCALE(editor_theme_manager.cpp:561).

EDSCALE and theme base scale (In an editor, they are the same thing) are used to determine minimal control size and some line width and content margin, they also affect node size.

That is why this fix works.

**Review by Geometror — COMMENTED** [review]
Sorry for the long wait.
Looks like the display size of resizable nodes (inheriting from VisualShaderNodeResizableBase) also changes, which causes e.g. the expression node to be much bigger than it should at 200% editor scale:
|100% scale|200% scale|
|--------------|----------------|
| Screenshot_20241120_191443 | Screenshot_20241120_191613 |

File: editor/plugins/visual_shader_editor_plugin.h [hunk 1]
```diff
@@ -281,6 +281,8 @@ class VisualShaderEditor : public ShaderEditor {
 	VBoxContainer *param_vbox = nullptr;
 	VBoxContainer *param_vbox2 = nullptr;
 
+	float cached_theme_base_scale = 1.0f;
```
Comment (Geometror) [inline editor/plugins/visual_shader_editor_plugin.h:284]: Why not just use `EDSCALE` instead of this separately cached scale?

Comment (jj11hh) [reply editor/plugins/visual_shader_editor_plugin.h:284]: Well, I think eventually we will remove the EDSCALE macro for DPI per-monitor awareness

**Comment by OeilDeLance** [comment]
This is a really good fix for a problem that is recurrent when more that one person is working on the same visual script.
Node positioning is a really important thing for a readable script and this bug makes it impossible to work at different DisplayScales.

I would really appreciate it if someone would retarget this to 4.5 or 4.6. I would very much like to integrate it to my own Godot build, even if it is not quite finished.

**Comment by meokit** [comment]
> This is a really good fix for a problem that is recurrent when more that one person is working on the same visual script. Node positioning is a really important thing for a readable script and this bug makes it impossible to work at different DisplayScales.
> 
> I would really appreciate it if someone would retarget this to 4.5 or 4.6. I would very much like to integrate it to my own Godot build, even if it is not quite finished.

Done, you can test it.

**Comment by OeilDeLance** [comment]
We will very soon try to test this out on 4.5.1.
Will that merge fine ? Or is it more of a 4.6 retarget ?

**Comment by AThousandShips** [comment]
This might be merged for 4.6, it's currently on the 4.x milestone, it will probably be cherry-picked for a 4.5.x version like 4.5.2

**Comment by OeilDeLance** [comment]
Thanks for the quick answer, I did not know there was a 4.5.2.
Ok So we'll cherry pick and hope it's not gonna be too hard :)

**Review by Geometror — APPROVED** [review]
Retested, still works.
There is still the problem with VS nodes derived from `VisualShaderNodeResizableBase` like Expression (see my earlier comment), however this isn't a regression, so I think we can merge as is. As others have mentioned, this is a rather important fix for larger teams where several people work on the same VisualShader.

**Comment by meokit** [comment]
Godot's Editor UI still handles DisplayScale in a very messy way. The best approach may be to use density-independent pixels at the GUI framework level.

This fix isn't perfect. As it stands, a major overhaul of the GUI is needed to remove the use of pixels as the unit of measurement for UI components. We also need to remove the EDSCALE macro to support per-monitor Display Scale.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.5.2.
