### PR TITLE
Fix theme propagation in various parts of the editor

### LINKED ISSUE #65090: EditorFileDialog has missing icons (4.0.alpha15 regression)
### Godot version

4.0.dev (889c522a)

### System information

Windows 10

### Issue description

Export template file browser dialog has error icons everywhere. Other dialogs of same kind (like "Open Scene") work fine.

image

Maybe related to the EditorFileDialog access mode `ACCESS_FILESYSTEM` used here?

### Steps to reproduce

- Open Project -> Export dialog
- Create e.g. windows export target
- Open file browser for custom template

### Minimal reproduction project

_No response_

### LINKED ISSUE #65114: Integrated docs (Editor Help) display is broken in 4.0 alpha 15
### Godot version

4.0 alpha 15

### System information

linux

### Issue description

| alpha 14                                                                                                        | alpha 15                                                                                                        |
|-----------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| image | image |

This happens regardless of the project.
While testing back and forth with a14 and a15 I got *once* a15 to display docs correctly (if I remember correctly) but was not able to reproduce since.

### Steps to reproduce

Open the docs in 4.0.alpha15

### Minimal reproduction project

_No response_

### LINKED ISSUE #65180: Text garbling happens when the editor's language is set to Japanese
### Godot version

4.0alpha15

### System information

Windows 10, Vulkan,  NVIDIA Quadro P2000

### Issue description

When the editor's language is set to Japanese, some characters are garbled in certain windows, such as:

1. FileDialog
image[
The FileDialog window looks like this in the editor view as well as when you use a FileDialog node in `@tool` scripts. It doesn't seem to happen when you actually *run* the scene containing a FileDialog node.

2. Docs
image

It's probably due to the font used in these cases not supporting Japanese characters. Also, the issue didn't happen in the older versions.
Perhaps this occurs in some other languages, especially those that use CJK characters, although I haven't tested yet.

### Steps to reproduce

1. Set the editor's language to Japanese and restart the engine
2. Create a scene, add FileDialog node and see how it looks

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by YuriSizov**
Fixes https://github.com/godotengine/godot/issues/65090 (including the issue reported in comments).
Fixes https://github.com/godotengine/godot/issues/65114.
Likely fixes https://github.com/godotengine/godot/issues/65180.

Follow-up to https://github.com/godotengine/godot/pull/65156 and https://github.com/godotengine/godot/pull/65192 (depends on both of them, and for the moment includes commits from both of them). In this part we're starting to fix parts of the editor which were exposed by https://github.com/godotengine/godot/pull/62845. I'll be targeting specific regressions here, and a more broad code clean-up can happen in a later PR (and by anyone, really, once the first two are merged).

Currently this PR updates the code of:
- `RichTextLabel` (didn't touch `EditorHelp` to fix the docs regression);
- `MaterialEditor` and `MeshEditor`;
- `EditorFileDialog`;

As well as other small touch ups.

Marking it as a draft for the moment. Feel free to comment with more related theme propagation regressions. (I think @groud said there was something in the tile editor?)

### CODE REVIEW

**Comment by Rindbee** [comment]
IMO, just make sure the theme-related data is set before entering the tree. And `NOTIFICATION_PARENTED` happens just before `NOTIFICATION_ENTER_TREE`. So, maybe we can try to put that propagation code in `NOTIFICATION_PARENTED`.
https://github.com/godotengine/godot/blob/8c7be63588bf3e4ef4b780ff57936c68db5939c7/scene/main/node.cpp#L1122-L1131

**Comment by YuriSizov** [comment]
> IMO, just make sure the theme-related data is set before entering the tree.

Theme-related data cannot be set before entering the tree, because it is provided by parent controls.

**Comment by Rindbee** [comment]
> Theme-related data cannot be set before entering the tree, because it is provided by parent controls.

I mean for the propagation code in `add_child_notify`, put them in `notification(NOTIFICATION_PARENTED)` instead. During `NOTIFICATION_PARENTED`, although it is not in the tree, it has been able to get the parent. And `_propagate_theme_changed` does not require the node to be in the tree.

https://github.com/godotengine/godot/blob/c6fd311da0d0052bb11237662ec528f9fab1b7dd/scene/gui/control.cpp#L3092-L3098

**Comment by YuriSizov** [comment]
> I mean for the propagation code in `add_child_notify`, put them in `notification(NOTIFICATION_PARENTED)` instead. During `NOTIFICATION_PARENTED`, although it is not in the tree, it has been able to get the parent.

Yes, that's a good idea and make sense. We can replace `add_child_notify` with handling `NOTIFICATION_PARENTED` and `remove_child_notify` with `NOTIFICATION_UNPARENTED`. Should be more or less the same, except it gets called before ENTER_TREE so we don't need to defer the call.

**Comment by Rindbee** [comment]
I have made a try in #65222.

File: editor/editor_file_dialog.cpp [hunk 1]
```diff
@@ -86,7 +123,9 @@ void EditorFileDialog::_notification(int p_what) {
 					if (preview_wheel_index >= 8) {
 						preview_wheel_index = 0;
 					}
-					Ref<Texture2D> frame = item_list->get_theme_icon("Progress" + itos(preview_wheel_index + 1), SNAME("EditorIcons"));
+
+					Ref<Texture2D> progress[] = { theme_cache.progress_1, theme_cache.progress_2, theme_cache.progress_3, theme_cache.progress_4, theme_cache.progress_5, theme_cache.progress_6, theme_cache.progress_7, theme_cache.progress_8 };
```
Comment (akien-mga) [inline editor/editor_file_dialog.cpp:127]: Constructing this array each time in process seems a bit wasteful. Maybe the theme cache could have the array directly instead of these 8 individual members.

File: editor/plugins/material_editor_plugin.cpp [hunk 2]
```diff
@@ -40,33 +40,37 @@
...
 #include "scene/resources/sky_material.h"
 
-void MaterialEditor::_notification(int p_what) {
-	switch (p_what) {
-		case NOTIFICATION_READY: {
-			//get_scene()->connect("node_removed",this,"_node_removed");
-
-			if (first_enter) {
-				//it's in propertyeditor so.. could be moved around
+void MaterialEditor::_update_theme_item_cache() {
```
Comment (akien-mga) [inline editor/plugins/material_editor_plugin.cpp:43]: Missing `Control::` super call?

File: editor/plugins/mesh_editor_plugin.cpp [hunk 3]
```diff
@@ -49,20 +49,20 @@ void MeshEditor::gui_input(const Ref<InputEvent> &p_event) {
 	}
 }
 
+void MeshEditor::_update_theme_item_cache() {
```
Comment (akien-mga) [inline editor/plugins/mesh_editor_plugin.cpp:52]: Missing `SubViewportContainer` super call.

File: scene/gui/rich_text_label.cpp [hunk 4]
```diff
@@ -1676,7 +1668,47 @@ int RichTextLabel::_find_first_line(int p_from, int p_to, int p_vofs) const {
 }
 
 _FORCE_INLINE_ float RichTextLabel::_calculate_line_vertical_offset(const RichTextLabel::Line &line) const {
-	return line.get_height(get_theme_constant(SNAME("line_separation")));
+	return line.get_height(theme_cache.line_separation);
+}
+
+void RichTextLabel::_update_theme_item_cache() {
```
Comment (akien-mga) [inline scene/gui/rich_text_label.cpp:1674]: Super call.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
