### PR TITLE
ResourceLoader: Add thread-aware resource changed mechanism

### LINKED ISSUE #96115: Race condition in `Resource::connect_changed`
### Tested versions

4.3

### System information

Windows 11

### Issue description

62d9ce6445283d2bc1daa973350f91df56a826bf changed `Resource::connect_changed` to delay signal connection if the `ResourceLoader` is currently loading. This leads to issues if a ResourceLoader creates a `PackedScene` with eg a `MeshInstance3D` or `CollisionShape3D` on a thread other than the main thread.

```
<core\object\object.cpp(1369): Object::connect> Condition "!p_callable.is_valid()" is true. Returning: ERR_INVALID_PARAMETER:
Cannot connect to 'changed': the provided callable is not valid: MeshInstance3D::_mesh_changed

<core\object\object.cpp(1369): Object::connect> Condition "!p_callable.is_valid()" is true. Returning: ERR_INVALID_PARAMETER:
Cannot connect to 'changed': the provided callable is not valid: Node3D::update_gizmos
```

### Steps to reproduce

- create a loader that creates a `PackedScene` with `MeshInstance3D` and sets a mesh
- load a resource with the loader via `ResourceLoader::load_threaded_requet

### Minimal reproduction project (MRP)

-

### PR DESCRIPTION
**Pull request by RandomShaper**
- **ResourceLoader: Simplify handling of unregistered tasks** (Preliminary work for the other commit)

The unregistered task mechnaism is used to isolate a uncached load from a cached one with the same path. This commit simplifies how unregistered loads are handled.

That brings the benefit of more code shared between both, which removes the constraint of uncached loads having to complete synchronously.

- **ResourceLoader: Add thread-aware resource changed mechanism**

Signals are not thread-safe. Therefore, resource loaders shouldn't deal with them. However, there's a special signal in `Resource`, `changed`, which is a common need during resource loading. Fortunately, it has its own API.

This commit lets the `ResourceLoader` intervene that API during threaded loading so the handling of the `changed` signal can happen in a safe manner.

The general idea is that during loads, only the resources known to a loader thread participate in the signal. When a load is awaited by another, the awaited one propagates its record of connections to the awaiter, which can happen recursively. The awaited one keeps its records until it dies, so they are available to any other load chaining with it. Finally, when a leaf task is awaited, the connections are migrated to the standard signal mechanism on the main thread.

This replaces the current attempt at thread-safe `changed` signaling, which wasn't good enough because 1) it tried to achieve safety by deferring the calls within a load thread, which changed the expected flow too much; and 2) it couldn't avoid multiple load threads from dealing with the connection maps of the objects involved, therefore not being as robust as desirable. That said, the mechanism in this PR is much more resilient, but, at the end of the day, signals are not thread-safe in Godot, so it can only guarantee correctness within its realm (resource loading).

The implementation tries to be simple in these ways:
- Linear search (no hashing). Should be good enough for the relatively small amount of cases expected. In case it's found to be a problem, a hashmap can be used instead.
- No connection flags implemented. In cases where, e.g., `CONNECT_REFERENCE_COUNTED` is used, like `AnimationNodeBlendTree`, or other flags, this implementation will forward them to the standard signal mechanism, but won't honor them during loads.

---

Fixes #96115.

### CODE REVIEW

**Comment by RandomShaper** [comment]
Cherry-pick for 4.3 included in #96606.

File: core/io/resource_loader.cpp [hunk 1]
```diff
@@ -816,6 +821,39 @@ Ref<Resource> ResourceLoader::_load_complete_inner(LoadToken &p_load_token, Erro
...
+				// On non-main threads, we have to queue and call it done when processed.
+				if (!load_task_ptr->resource_changed_connections.is_empty()) {
+					for (const ThreadLoadTask::ResourceChangedConnection &rcc : load_task_ptr->resource_changed_connections) {
+						if (rcc.callable.is_valid()) {
+							MessageQueue::get_main_singleton()->push_callable(callable_mp(rcc.source, &Resource::connect_changed).bind(rcc.callable, rcc.flags));
+						}
+					}
+					core_bind::Semaphore done;
+					MessageQueue::get_main_singleton()->push_callable(callable_mp(&done, &core_bind::Semaphore::post));
+					done.wait();
```
Comment (akien-mga) [inline core/io/resource_loader.cpp:851]: It seems a bit weird for me that we're using `core_bind::Semaphore` here instead of the main `Semaphore`, why do we need to `core_bind`? My understanding is that `core_bind` is only for binding core APIs to scripting, not for use in the rest of the C++ engine.

Comment (AThousandShips) [reply core/io/resource_loader.cpp:851]: `Semaphore` isn't an `Object`, don't think you can `callable_mp` non-`Object`s

**Review by akien-mga — APPROVED** [review]
