### PR TITLE
Fix errors on pressing autoplay in sprite frames editor

### LINKED ISSUE #91826: Pressing "AutoPlay on Load" button of the sprite frames editor emit error to the output
### Tested versions

4.3: 2ba22d1554ded08094e3869a83bd87487266ad38

### System information

Windows 11

### Issue description

sprite_frames_editor_bug

### Steps to reproduce

Create and save a `SpriteFrames` as a separate resource, open it and check the bug.

### Minimal reproduction project (MRP)

[spriteframesbug.zip](https://github.com/godotengine/godot/files/15282376/spriteframesbug.zip)

### PR DESCRIPTION
**Pull request by Chaosus**
Fix https://github.com/godotengine/godot/issues/91826, I think the errors emits because the history changed but not for a correct object (`SpriteFrames` rather than `AnimatedSprite` itself), in other places it behaves correctly.

### CODE REVIEW

**Review by TokageItLab — APPROVED** [review]

**Review by KoBeWi — APPROVED** [review]

**Comment by Chaosus** [comment]
Also found the same bug when renaming/removing the animation.

File: editor/plugins/sprite_frames_editor_plugin.cpp [hunk 1]
```diff
@@ -1034,7 +1034,7 @@ void SpriteFramesEditor::_animation_name_edited() {
 	edited->set_text(0, name);
 
 	EditorUndoRedoManager *undo_redo = EditorUndoRedoManager::get_singleton();
-	undo_redo->create_action(TTR("Rename Animation"), UndoRedo::MERGE_DISABLE, frames.ptr());
+	undo_redo->create_action(TTR("Rename Animation"), UndoRedo::MERGE_DISABLE);
```
Comment (KoBeWi) [inline editor/plugins/sprite_frames_editor_plugin.cpp:1037]: Does it really fix something?
It should have the same effect.

Comment (Chaosus) [reply editor/plugins/sprite_frames_editor_plugin.cpp]: ah, yes it really doesn't have an effect, reverted...

**Comment by Chaosus** [comment]
I've just reverted https://github.com/godotengine/godot/pull/91830 for rename/delete/autoplay actions, so they will work without errors.

File: editor/plugins/sprite_frames_editor_plugin.cpp [hunk 2]
```diff
@@ -1034,7 +1034,7 @@ void SpriteFramesEditor::_animation_name_edited() {
 	edited->set_text(0, name);
 
 	EditorUndoRedoManager *undo_redo = EditorUndoRedoManager::get_singleton();
-	undo_redo->create_action(TTR("Rename Animation"), UndoRedo::MERGE_DISABLE, frames.ptr());
+	undo_redo->create_action(TTR("Rename Animation"), UndoRedo::MERGE_DISABLE, EditorNode::get_singleton()->get_edited_scene());
```
Comment (KoBeWi) [inline editor/plugins/sprite_frames_editor_plugin.cpp:1037]: This is wrong. It forces undo action for edited scene when editing external resources.

Comment (Chaosus) [reply editor/plugins/sprite_frames_editor_plugin.cpp]: Ok, I better revert these changes in this PR, to prevent further regressions.

**Comment by KoBeWi** [comment]
The problem with rename is that it tries to modify both the resource and nodes. `_rename_node_animation()` should probably be undo operation itself, not the node changes. But it's something for another PR.

**Comment by akien-mga** [comment]
Thanks!
