### PR TITLE
Fixes #19845 no 3d Compilation issue

### LINKED ISSUE #19845: Compiling template w/o 3d and bullet
**Godot version:**

Godot 3.1.dev (eeab3502d)

**OS/device including version:**

Macosx 10.13.4

**Issue description:**

I'm trying to compile the minimal godot 2d template for android. I disabled many modules. My actual building command is: 
```
scons platform=android target=release android_neon=no deprecated=no xml=no disable_3d=yes android_stl=yes game_center=no store_kit=no icloud=no module_bmp_enabled=no module_bullet_enabled=no module_dds_enabled=no module_mobile_vr_enabled=no module_opus_enabled=no module_pvr_enabled=no module_svg_enabled=no module_tga_enabled=no module_theora_enabled=no module_visual_script_enabled=no module_webm_enabled=no verbose=no ndk_platform=android-24 -j12
```
And it fails with error:
```
[ 83%] progress_finish(["progress_finish"], [])
[ 91%] Linking Shared Library ==> bin/libgodot.android.opt.armv7.so
[ 91%] clang++: warning: argument unused during compilation: '-dynamiclib'
scene/libscene.android.opt.armv7.a(skeleton.android.opt.armv7.o):scene/3d/skeleton.cpp:function _pb_stop_simulation(Node*): error: undefined reference to 'PhysicalBone::set_simulate_physics(bool)'
scene/libscene.android.opt.armv7.a(skeleton.android.opt.armv7.o):scene/3d/skeleton.cpp:function _pb_stop_simulation(Node*): error: undefined reference to 'PhysicalBone::set_static_body(bool)'
scene/libscene.android.opt.armv7.a(skeleton.android.opt.armv7.o):scene/3d/skeleton.cpp:function _pb_stop_simulation(Node*): error: undefined reference to 'typeinfo for PhysicalBone'
scene/libscene.android.opt.armv7.a(skeleton.android.opt.armv7.o):scene/3d/skeleton.cpp:function _pb_start_simulation(Skeleton const*, Node*, Vector<int> const&): error: undefined reference to 'PhysicalBone::set_simulate_physics(bool)'
scene/libscene.android.opt.armv7.a(skeleton.android.opt.armv7.o):scene/3d/skeleton.cpp:function _pb_start_simulation(Skeleton const*, Node*, Vector<int> const&): error: undefined reference to 'PhysicalBone::set_simulate_physics(bool)'
scene/libscene.android.opt.armv7.a(skeleton.android.opt.armv7.o):scene/3d/skeleton.cpp:function _pb_start_simulation(Skeleton const*, Node*, Vector<int> const&): error: undefined reference to 'PhysicalBone::set_static_body(bool)'
scene/libscene.android.opt.armv7.a(skeleton.android.opt.armv7.o):scene/3d/skeleton.cpp:function _pb_start_simulation(Skeleton const*, Node*, Vector<int> const&): error: undefined reference to 'typeinfo for PhysicalBone'
scene/libscene.android.opt.armv7.a(skeleton.android.opt.armv7.o):scene/3d/skeleton.cpp:function _physical_bones_add_remove_collision_exception(bool, Node*, RID): error: undefined reference to 'typeinfo for CollisionObject'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [bin/libgodot.android.opt.armv7.so] Error 1
scons: building terminated because of errors.
```
I think that 3d/skeleton.cpp should be disabled by flag `disable_3d=yes`. It wants to PhysicalBody and when I enable bullet module it requires enabling full 3d support.
So I can not build android template without any 3d and bullet physics.

**Steps to reproduce:**

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by AndreaCatania**

### CODE REVIEW

File: scene/3d/skeleton.cpp [hunk 1]
```diff
@@ -691,6 +693,8 @@ void Skeleton::physical_bones_remove_collision_exception(RID p_exception) {
 	_physical_bones_add_remove_collision_exception(false, this, p_exception);
 }
 
+#endif _3D_DISABLED
```
Comment (akien-mga) [inline scene/3d/skeleton.cpp]: I'm not sure `#endif` can take a named define? Usually we put `#endif // _3D_DISABLED`

**Comment by AndreaCatania** [comment]
​​
​​
You true, I had copied it just for a mistake, I've already updated it
