### PR TITLE
Fix Time.get_datetime_string_from_dict() does not validate input

### LINKED ISSUE #60195: `Time.get_datetime_string_from_dict()` does not validate input
### Godot version

3.x (8f4f384) master (788f355)

### System information

Arch Linux, GLES 3, Mesa Intel(R) UHD Graphics (CML GT2)

### Issue description

`get_unix_time_from_datetime_dict()` complains about invalid values in input dict. But `get_datetime_string_from_dict()` uses invalid input directly.

For example, `{year=2022, month=99, hour=-99}` produces `2022-99-01T157:00:00` without any error.

### Steps to reproduce

Run this script with `-s`:

```gdscript
extends SceneTree


func _init():
	print("===== Start =====")

	var dt := {year=2022, month=99, hour=-99}
	print("%s timestamp=> %s" % [dt, Time.get_unix_time_from_datetime_dict(dt)])
	print("%s    string=> %s" % [dt, Time.get_datetime_string_from_dict(dt, false)])

	print("====== End ======")
	quit()
```

It will output:

```
===== Start =====
ERROR: Invalid month value of: 99. See the Time.Month enum for valid values.
   at: get_unix_time_from_datetime_dict (core/os/time.cpp:289)
{hour:-99, month:99, year:2022} timestamp=> 0
{hour:-99, month:99, year:2022}    string=> 2022-99-01T157:00:00
====== End ======
```

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by RedHeadphone**
fixes #60195

### CODE REVIEW

File: core/os/time.cpp [hunk 1]
```diff
@@ -95,16 +95,16 @@ VARIANT_ENUM_CAST(Time::Weekday);
...
+	ERR_FAIL_COND_MSG(hour > 23, "Invalid hour value of: " + itos(hour) + ".");                                                                                    \
+	ERR_FAIL_COND_MSG(minute > 59, "Invalid minute value of: " + itos(minute) + ".");                                                                              \
+	ERR_FAIL_COND_MSG(second > 59, "Invalid second value of: " + itos(second) + " (leap seconds are not supported).");                                             \
+	/* Do this check after month is tested as valid. */                                                                                                            \
+	ERR_FAIL_COND_MSG(day == 0, "Invalid day value of: " + itos(month) + ", days are 1-indexed and cannot be 0.");                                                 \
+	uint8_t days_in_this_month = MONTH_DAYS_TABLE[IS_LEAP_YEAR(year)][month - 1];                                                                                  \
+	ERR_FAIL_COND_MSG(day > days_in_this_month, "Invalid day value of: " + itos(day) + " which is larger than the maximum for this month, " + itos(days_in_this_month) + ".");
```
Comment (bruvzg) [inline core/os/time.cpp:107]: Not sure if this is a good idea, it will only print an error, but won't return a default value.

Maybe it's better to add a return argument to the macro:

```c++
#define VALIDATE_YMDHMS(ret)                                                                                                                                              \
	ERR_FAIL_COND_V_MSG(month == 0, ret, "Invalid month value of: " + itos(month) + ", months are 1-indexed and cannot be 0. See the Time.Month enum for valid values."); \
	ERR_FAIL_COND_V_MSG(month > 12, ret, "Invalid month value of: " + itos(month) + ". See the Time.Month enum for valid values.");                                       \
	ERR_FAIL_COND_V_MSG(hour > 23, ret, "Invalid hour value of: " + itos(hour) + ".");                                                                                    \
	ERR_FAIL_COND_V_MSG(minute > 59, ret, "Invalid minute value of: " + itos(minute) + ".");                                                                              \
	ERR_FAIL_COND_V_MSG(second > 59, ret, "Invalid second value of: " + itos(second) + " (leap seconds are not supported).");                                             \
	/* Do this check after month is tested as valid. */                                                                                                                   \
	ERR_FAIL_COND_V_MSG(day == 0, ret, "Invalid day value of: " + itos(month) + ", days are 1-indexed and cannot be 0.");                                                 \
	uint8_t days_in_this_month = MONTH_DAYS_TABLE[IS_LEAP_YEAR(year)][month - 1];                                                                                         \
	ERR_FAIL_COND_V_MSG(day > days_in_this_month, ret, "Invalid day value of: " + itos(day) + " which is larger than the maximum for this month, " + itos(days_in_this_month) + ".");
```

And then use `VALIDATE_YMDHMS("")` in `get_datetime_string_from_dict`, and `VALIDATE_YMDHMS(0)` in the rest of places.

Comment (RedHeadphone) [reply core/os/time.cpp:107]: oh nice fix, I will implement that

**Review by timothyqiu — APPROVED** [review]

**Comment by akien-mga** [comment]
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Review by aaronfranke — COMMENTED** [review]
✅ This fix is good, it makes sense to not hard-code the return value.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.
