### PR TITLE
Fix drag and drop on LineEdit

### LINKED ISSUE #54744: LineEdit.editable = false can be edited with double click.
### Godot version

3.4.stable

### System information

Win10. Shouldn't matter.

### Issue description

You can edit the text in a `editable = false` LineEdit by doubling clicking a word, holding the 2nd click, and dragging.

### Steps to reproduce

In a `TextEdit` with `readonly=true` you can double click the text, hold the 2nd click, and drag. This lets you mark full words without needing to be careful about word edges. This is expected behavior.

However, in a `LineEdit` with `editable=false` doing the same double click, hold 2nd click, and drag the word you originally clicked moves along with it.

### Minimal reproduction project

[Line Edit Error.zip](https://github.com/godotengine/godot/files/7493657/Line.Edit.Error.zip)

### PR DESCRIPTION
**Pull request by ConteZero**
LineEdit contains the code to handle drag and drop but it never gets executed, I don't know if it's excluded on purpose or it's a bug.
I have improved the existing code to make it possible to cut and paste the selection (the current code only makes a copy).
I don't know if this is the best way to implement this functionality, but from my tests it works and with some tweaks it could be used for the TextEdit node as well.

*Bugsquad edit:* Fixes #54744.

### CODE REVIEW

**Comment by KoBeWi** [comment]
Nice feature, I'd definitely like to see it in TextEdit too.

Dropping doesn't properly support undo/redo though:
avYh133jW5

**Comment by ConteZero** [comment]
> Nice feature, I'd definitely like to see it in TextEdit too.
> 
> Dropping doesn't properly support undo/redo though

Yes, you are right, I force-pushed a change that should fix undo/redo.

File: scene/gui/line_edit.cpp [hunk 1]
```diff
@@ -268,7 +268,9 @@ void LineEdit::gui_input(const Ref<InputEvent> &p_event) {
 				return;
 			}
 
-			shift_selection_check_pre(b->is_shift_pressed());
+			if (b->is_shift_pressed()) {
+				shift_selection_check_pre(b->is_shift_pressed());
+			}
```
Comment (KoBeWi) [inline scene/gui/line_edit.cpp:273]: What is this change about?
Also if anything, you should do `shift_selection_check_pre(true)`, because you are checking it in the condition before.

File: scene/gui/line_edit.cpp [hunk 2]
```diff
@@ -369,6 +371,11 @@ void LineEdit::gui_input(const Ref<InputEvent> &p_event) {
 				selection_fill_at_caret();
 			}
 		}
+
+		if (drag_action && Input::get_singleton()->get_current_cursor_shape() == Input::CURSOR_CAN_DROP) {
```
Comment (KoBeWi) [inline scene/gui/line_edit.cpp:375]: Checking cursor shape isn't probably very reliable. It can be changed via script etc.
Not sure how it could be done better though. Can't you just use `drop_data()`?

File: scene/gui/line_edit.cpp (hunk 1 above)
Comment (ConteZero) [reply scene/gui/line_edit.cpp]: `shift_selection_check_pre` execute a `deselect()` when you pass a false value.

Then the ` if (selection.enabled)` condition is never executed:

```
if ((caret_column < selection.begin) || (caret_column > selection.end) || !selection.enabled) {
	deselect();
	selection.start_column = caret_column;
	selection.creating = true;
} else if (selection.enabled) {
	selection.drag_attempt = true;
}
```

File: scene/gui/line_edit.cpp (hunk 2 above)
Comment (ConteZero) [reply scene/gui/line_edit.cpp]: I've changed the code to use
`get_viewport()->gui_get_drag_data()`
for the check.

File: scene/gui/line_edit.cpp [hunk 3]
```diff
@@ -369,6 +371,11 @@ void LineEdit::gui_input(const Ref<InputEvent> &p_event) {
 				selection_fill_at_caret();
 			}
 		}
+
+		if (drag_action && is_editable() && get_viewport()->gui_get_drag_data().get_type() == Variant::STRING) {
```
Comment (KoBeWi) [inline scene/gui/line_edit.cpp:375]: Actually if you have access to the drag data (I didn't actually know it's available like that...), you could just use `can_drop_data(get_viewport()->gui_get_drag_data())`.

So the condition would become
```
if (drag_action && can_drop_data(get_viewport()->gui_get_drag_data()))
```

File: scene/gui/line_edit.cpp [hunk 4]
```diff
@@ -934,6 +958,29 @@ void LineEdit::_notification(int p_what) {
...
+					deselect();
+				} else if (deselect_on_focus_loss_enabled) {
+					deselect();
+				}
+			}
+		} break;
+		case Control::NOTIFICATION_DROP_DATA_FAIL: {
+			if (selection.drag_attempt) {
+				selection.drag_attempt = false;
+			}
```
Comment (KoBeWi) [inline scene/gui/line_edit.cpp:982]: The condition here is not necessary, you could just always set it to `false`. Although not sure which option is theoretically better for performance.

**Review by KoBeWi — APPROVED** [review]
Seems ok, but core changes need additional review.

btw, the unreported issue fixed by this PR is actually a regression, because drag and drop works in 3.x (except undo/redo is broken).

**Comment by ConteZero** [comment]
> Seems ok, but core changes need additional review.
> 
> btw, the unreported issue fixed by this PR is actually a regression, because drag and drop works in 3.x (except undo/redo is broken).

Are you sure? I've tested in 3.3.4 and drag and drop in lineedit does not work for me, and this is confirmed by looking at the code, the `shift_selection_check_pre` that causes the deselect is still there so the condition
```
} else if (selection.enabled) {
	selection.drag_attempt = true;
}
```
is never executed.

**Comment by ConteZero** [comment]
I've added some lines of code to LineEdit::drop_data to handle the case where deselect_on_focus_loss_enabled is false.
I've tried to mimic the behavior of classic cut and paste, so if you drag the selection in a different lineedit that have already a text selected, then the grabbed text will replace the one in the existing selection.

**Comment by KoBeWi** [comment]
> Are you sure?

8SgLrJpUbz
3.4 rc1

**Comment by ConteZero** [comment]
Well, I think we can call it the "Schrödinger's Drag and Drop", it works and doesn't work at the same time.
If you do a double or triple click and you keep the left mouse button pressed on your last click then you can grab the selection.
If you don not keep the left mouse button pressed or if you try to only select some letters of a word than the grab operation does not start.
In your example try to drag only a part of the word "test", like "st" for example.

File: scene/gui/line_edit.cpp [hunk 5]
```diff
@@ -569,22 +576,46 @@ bool LineEdit::can_drop_data(const Point2 &p_point, const Variant &p_data) const
...
+				delete_text(selection.begin, selection.end);
+				deselect();
 
-		insert_text_at_caret(p_data);
-		selection.begin = caret_column - selected;
-		selection.end = caret_column;
+				set_caret_column(caret_column_tmp);
+				insert_text_at_caret(p_data);
+			}
+		} else if (!deselect_on_focus_loss_enabled && selection.enabled && caret_column >= selection.begin && caret_column <= selection.end) {
```
Comment (Paulb23) [inline scene/gui/line_edit.cpp:600]: Doesn't `selection.enabled` tell us if `deselect_on_focus_loss_enabled` is enabled?

File: scene/gui/line_edit.cpp [hunk 6]
```diff
@@ -934,6 +965,27 @@ void LineEdit::_notification(int p_what) {
...
+		case Control::NOTIFICATION_DRAG_END: {
+			drag_action = false;
+			drag_caret_force_displayed = false;
+		} break;
+		case Control::NOTIFICATION_DROP_DATA_SUCCESS: {
+			if (selection.drag_attempt) {
+				selection.drag_attempt = false;
+				if (is_editable()) {
+					delete_text(selection.begin, selection.end);
+					deselect();
```
[the remark this answers is not in the document]
Comment (ConteZero) [reply scene/gui/line_edit.cpp]: done

File: scene/gui/line_edit.cpp (hunk 5 above)
Comment (ConteZero) [reply scene/gui/line_edit.cpp]: fixed

File: scene/gui/line_edit.cpp [hunk 7]
```diff
@@ -569,22 +576,46 @@ bool LineEdit::can_drop_data(const Point2 &p_point, const Variant &p_data) const
...
+				int caret_column_tmp = caret_column;
+				if (caret_column_tmp > selection.end) {
+					caret_column_tmp = caret_column_tmp - (selection.end - selection.begin);
+				}
+				delete_text(selection.begin, selection.end);
+				deselect();
 
-		insert_text_at_caret(p_data);
-		selection.begin = caret_column - selected;
-		selection.end = caret_column;
```
[the remark this answers is not in the document]
Comment (ConteZero) [reply scene/gui/line_edit.cpp:587]: I've restored the previous behavior and I've also fixed a bug in the undo/redo code by adding a deselect()

File: scene/gui/line_edit.cpp [hunk 8]
```diff
@@ -268,7 +268,9 @@ void LineEdit::gui_input(const Ref<InputEvent> &p_event) {
 				return;
 			}
 
-			shift_selection_check_pre(b->is_shift_pressed());
+			if (b->is_shift_pressed()) {
+				shift_selection_check_pre(true);
+			}
```
[the remark this answers is not in the document]
Comment (ConteZero) [reply scene/gui/line_edit.cpp:273]: Moving the control inside shift_selection_check_pre might not cause unwanted side effects?

File: scene/gui/line_edit.cpp [hunk 9]
```diff
@@ -569,22 +576,51 @@ bool LineEdit::can_drop_data(const Point2 &p_point, const Variant &p_data) const
...
+		} else if (selection.enabled && caret_column >= selection.begin && caret_column <= selection.end) {
+			caret_column_tmp = selection.begin;
+			delete_text(selection.begin, selection.end);
+			deselect();
+			set_caret_column(caret_column_tmp);
+			insert_text_at_caret(p_data);
+			grab_focus();
+		} else {
+			deselect();
```
Comment (Paulb23) [inline scene/gui/line_edit.cpp:608]: Can remove this call to `deselect` as we're immediately selecting afterwords.

File: scene/gui/line_edit.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (Paulb23) [reply scene/gui/line_edit.cpp:273]: Shouldn't do as this is the only call that is used for the mouse, though that does raise a good point, we should probably prevent any another input whilst dragging text.

[the remark this answers is not in the document]
Comment (ConteZero) [reply scene/gui/line_edit.cpp:273]: Yes, preventing other input while dragging will avoid unwanted behavior, but I believe this needs to be done in another pull request because it should be done in a generic way, not limited to just Lineedit.

File: scene/gui/line_edit.cpp [hunk 10]
```diff
@@ -569,22 +576,51 @@ bool LineEdit::can_drop_data(const Point2 &p_point, const Variant &p_data) const
...
-		insert_text_at_caret(p_data);
-		selection.begin = caret_column - selected;
-		selection.end = caret_column;
+				set_caret_column(caret_column_tmp);
+				insert_text_at_caret(p_data);
+			}
+		} else if (selection.enabled && caret_column >= selection.begin && caret_column <= selection.end) {
+			caret_column_tmp = selection.begin;
+			delete_text(selection.begin, selection.end);
+			deselect();
```
[the remark this answers is not in the document]
Comment (ConteZero) [reply scene/gui/line_edit.cpp]: fixed

File: scene/gui/line_edit.cpp [hunk 11]
```diff
@@ -569,22 +576,51 @@ bool LineEdit::can_drop_data(const Point2 &p_point, const Variant &p_data) const
...
-		_shape();
+		int caret_column_tmp = caret_column;
+		if (selection.drag_attempt) {
+			selection.drag_attempt = false;
+			if (caret_column < selection.begin || caret_column > selection.end) {
+				if (caret_column_tmp > selection.end) {
+					caret_column_tmp = caret_column_tmp - (selection.end - selection.begin);
+				}
+				delete_text(selection.begin, selection.end);
+				deselect();
```
[the remark this answers is not in the document]
Comment (ConteZero) [reply scene/gui/line_edit.cpp]: fixed

File: scene/gui/line_edit.cpp [hunk 12]
```diff
@@ -569,22 +576,51 @@ bool LineEdit::can_drop_data(const Point2 &p_point, const Variant &p_data) const
...
+		} else {
+			deselect();
+			insert_text_at_caret(p_data);
+			grab_focus();
+		}
+		if (selecting_enabled) {
+			selection.enabled = true;
+			selection.begin = caret_column_tmp;
+			selection.end = caret_column;
+		}
```
[the remark this answers is not in the document]
Comment (ConteZero) [reply scene/gui/line_edit.cpp]: fixed

File: scene/gui/line_edit.cpp (hunk 9 above)
Comment (ConteZero) [reply scene/gui/line_edit.cpp]: fixed

**Comment by akien-mga** [comment]
Be sure to check how it behaves with non `editable` LineEdits too (see #54744).

**Comment by ConteZero** [comment]
> Be sure to check how it behaves with non `editable` LineEdits too (see #54744).

[https://github.com/godotengine/godot/issues/54744](https://github.com/godotengine/godot/issues/54744) should be fixed by this this commit.
If this pull request will be accepted my plan is to do a backport to 3.x

File: scene/gui/line_edit.cpp [hunk 13]
```diff
@@ -569,22 +576,44 @@ bool LineEdit::can_drop_data(const Point2 &p_point, const Variant &p_data) const
...
 
-	return p_data.get_type() == Variant::STRING;
+	return is_editable() && p_data.get_type() == Variant::STRING;
 }
 
 void LineEdit::drop_data(const Point2 &p_point, const Variant &p_data) {
 	Control::drop_data(p_point, p_data);
 
-	if (p_data.get_type() == Variant::STRING) {
+	if (is_editable() && p_data.get_type() == Variant::STRING) {
```
Comment (Paulb23) [inline scene/gui/line_edit.cpp:585]: Nit: Can invert this.

**Review by Paulb23 — COMMENTED** [review]
Line edit changes look okay.

However, I'm not sure on the new `NOTIFICATION`s, kind of makes `NOTIFICATION_DRAG_END` redundant. We can also handle quite easily inside of `LineEdit` rather then pushing up to `viewport`, though I can see the use case for it. 

Would need some other opinions on this.

**Comment by akien-mga** [comment]
> However, I'm not sure on the new `NOTIFICATION`s, kind of makes `NOTIFICATION_DRAG_END` redundant. We can also handle quite easily inside of `LineEdit` rather then pushing up to `viewport`, though I can see the use case for it.

Indeed, I don't see much added value for those notifications, and changing the core like this requires thorougher design review than only ad-hoc LineEdit changes. See https://docs.godotengine.org/en/latest/community/contributing/best_practices_for_engine_contributors.html#prefer-local-solutions

The two new notifications only serve to say "drag end with success" or "drag end with failure", and success or failure is determined by a method implemented in LineEdit. So LineEdit already knows if it's drag is a success or a failure, and can pass this information (e.g. via a member variable) to the existing `NOTIFICATION_DRAG_END` notification. All the Viewport changes seem unnecessary here.

**Comment by ConteZero** [comment]
> The two new notifications only serve to say "drag end with success" or "drag end with failure", and success or failure is determined by a method implemented in LineEdit. So LineEdit already knows if it's drag is a success or a failure, and can pass this information (e.g. via a member variable) to the existing `NOTIFICATION_DRAG_END` notification. All the Viewport changes seem unnecessary here.

I've not understood what you are suggesting when you talk about a member variable, you mean a member variable of Lineedit?
If this is the case, it will not work when you want to drag and drop from different nodes, as example from two Lineedit nodes, or from Lineedit and Textedit.
Currently the node where the drag operation starts do not know if at the end of the drag the drop is successful or not, this is only known from the node where the drop happens (or from the Viewport that handle the drag and drop at a higher level).
Without this information it is impossible to react accordingly, in case of Lineedit you do not know if you can delete the selected text or not.
Perhaps I'm missing something obvious, but I've not found a way to get this info without passing from Viewport.

**Comment by ConteZero** [comment]
> However, I'm not sure on the new `NOTIFICATION`s, kind of makes `NOTIFICATION_DRAG_END` redundant. We can also handle quite easily inside of `LineEdit` rather then pushing up to `viewport`, though I can see the use case for it.

As I've tried to explain in the previous comment I don't think it is possible to handle the drag and drop operation without using Viewport.

**Comment by ConteZero** [comment]
I'll try to make it clearer with an example, suppose we have two LineEdit nodes 

LineEdit_A contains textA
LineEdit_B contains textB

This is what happens during a drag and drop operation (only relevant method calls are shown):

```
# select "textA" on LineEdit_A and press Left Mouse Button
LineEdit_A --> selection.drag_attempt = true

# start Mouse Move
Viewport::_gui_input_event
LineEdit_A --> LineEdit::get_drag_data

# move mouse on LineEdit_B and release Left Mouse Button with caret at the end of "textB"
Viewport::_gui_input_event
Viewport::_gui_drop
LineEdit_B --> LineEdit::can_drop_data --> LineEdit::drop_data

# now LineEdit_B contains "textBtextA" but LineEdit_A do not know what to do until it receives the NOTIFICATION_DROP_DATA_SUCCESS
# LineEdit_A only know that the drag operation is started (selection.drag_attempt variable)
# if we send NOTIFICATION_DROP_DATA_SUCCESS from Viewport
# then LineEdit_A can delete "textA" and the drag and drop operation is completed
```

**Comment by Paulb23** [comment]
An alternative solution, which already has a precedent in `Viewport` is `gui.dragging`, with a getter `gui_is_dragging`. 

So we could add `gui.drag_successful` with a getter `gui_drag_successful()`, and a wrapper in `Control` to call `get_viewport()->gui_drag_successful()`. Then check that in `LineEdit` on `NOTIFICATION_DRAG_END`.

This way we don't have to touch notifications.

**Comment by ConteZero** [comment]
> An alternative solution, which already has a precedent in `Viewport` is `gui.dragging`, with a getter `gui_is_dragging`.
> 
> So we could add `gui.drag_successful` with a getter `gui_drag_successful()`, and a wrapper in `Control` to call `get_viewport()->gui_drag_successful()`. Then check that in `LineEdit` on `NOTIFICATION_DRAG_END`.
> 
> This way we don't have to touch notifications.

At first I thought about using a getter, but then I chose to create the two new notifications because it seemed simpler to implement and easier for users to understand.

If you think that the getter is a better choice I can modify the code to use it instead of notifications, in the end the thing that interests me most is to have a drag and drop functionality that works (especially for the 3.x branch which  is what I use for my projects).

**Comment by ConteZero** [comment]
@Paulb23 I've removed the notifications and added the getter as you suggested

**Review by akien-mga — APPROVED** [review]
Looks good to me as far as `Control`/`Viewport` changes are concerned.

**Review by Paulb23 — APPROVED** [review]
LGTM.

**Comment by akien-mga** [comment]
Thanks!
