### PR TITLE
Enforce zero width spaces and joiners with missing font. Do not warn about missing non-visual characters.

### LINKED ISSUE #111354: Rendering issue of empty labels in bitmap fonts
### Tested versions

- Reproducible in: 4.5.stable
- Not reproducible in: 4.4.1.stable
- git bisect identified 6c34f48c90adb14f8d3f621c8eb9b37db15ccaf1 (#108959) as the first bad commit.

### System information

Godot v4.5.stable.mono - macOS Sequoia (15.6.1) - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M1 Max (Apple7) - Apple M1 Max (10 threads) - 32.00 GiB memory

### Issue description

After upgrading my project to v4.5.stable.mono and testing it, I encountered issues with font rendering.

Working (v4.4.1.stable.mono):
Image

Broken (v4.5.stable.mono):
Image

Broken (master, v4.6.dev.mono.custom_build.c01c7b800):
Image

### Steps to reproduce

After applying a custom bitmap font, creating an empty label results in a letterbox labeled “20 06”.

### Minimal reproduction project (MRP)

[font-issue-mrp 2.zip](https://github.com/user-attachments/files/22735814/font-issue-mrp.2.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/111354

Adds missing case to https://github.com/godotengine/godot/pull/111014, when no suitable font were found for rendering.

### CODE REVIEW

File: modules/text_server_adv/text_server_adv.cpp [hunk 1]
```diff
@@ -6734,6 +6734,11 @@ void TextServerAdvanced::_shape_run(ShapedTextDataAdvanced *p_sd, int64_t p_star
 						p_sd->descent = MAX(p_sd->descent, Math::round(get_hex_code_box_size(fs, gl.index).x * 0.5));
 					}
 				}
+				bool zero_w = (p_sd->preserve_control) ? (p_sd->text[i] == 0x200B || p_sd->text[i] == 0xFEFF) : (p_sd->text[i] >= 0x200B && p_sd->text[i] <= 0x200D) || p_sd->text[i] == 0x2060 || p_sd->text[i] == 0xFEFF;
```
Comment (AThousandShips) [inline modules/text_server_adv/text_server_adv.cpp]:
```suggestion
				bool zero_w = (p_sd->preserve_control) ? (p_sd->text[i] == 0x200B || p_sd->text[i] == 0xFEFF) : ((p_sd->text[i] >= 0x200B && p_sd->text[i] <= 0x200D) || p_sd->text[i] == 0x2060 || p_sd->text[i] == 0xFEFF);
```
I'd make this explicit to prevent any confusion

File: modules/text_server_adv/text_server_adv.cpp [hunk 2]
```diff
@@ -6877,7 +6882,7 @@ void TextServerAdvanced::_shape_run(ShapedTextDataAdvanced *p_sd, int64_t p_star
 #endif
 
 			gl.index = glyph_info[i].codepoint;
-			bool zero_w = (p_sd->preserve_control) ? (p_sd->text[glyph_info[i].cluster] == 0x200B || p_sd->text[glyph_info[i].cluster] == 0xFEF) : (p_sd->text[glyph_info[i].cluster] >= 0x200B && p_sd->text[glyph_info[i].cluster] <= 0x200D) || p_sd->text[glyph_info[i].cluster] == 0x2060 || p_sd->text[glyph_info[i].cluster] == 0xFEFF;
+			bool zero_w = (p_sd->preserve_control) ? (p_sd->text[glyph_info[i].cluster] == 0x200B || p_sd->text[glyph_info[i].cluster] == 0xFEFF) : (p_sd->text[glyph_info[i].cluster] >= 0x200B && p_sd->text[glyph_info[i].cluster] <= 0x200D) || p_sd->text[glyph_info[i].cluster] == 0x2060 || p_sd->text[glyph_info[i].cluster] == 0xFEFF;
```
Comment (AThousandShips) [inline modules/text_server_adv/text_server_adv.cpp]:
```suggestion
			bool zero_w = (p_sd->preserve_control) ? (p_sd->text[glyph_info[i].cluster] == 0x200B || p_sd->text[glyph_info[i].cluster] == 0xFEFF) : ((p_sd->text[glyph_info[i].cluster] >= 0x200B && p_sd->text[glyph_info[i].cluster] <= 0x200D) || p_sd->text[glyph_info[i].cluster] == 0x2060 || p_sd->text[glyph_info[i].cluster] == 0xFEFF);
```
Same for this existing code

**Comment by AThousandShips** [comment]
Should this not be cherry picked for 4.5?

**Comment by bruvzg** [comment]
> Should this not be cherry picked for 4.5?

Yes.

**Review by akien-mga — APPROVED** [review]

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.5.1.
