### PR TITLE
Fix debug shape of `ShapeCast3D` not updating on `Shape` change

### LINKED ISSUE #68304: `ShapeCast3D` Debug Shape is not updating when changing `Shape` property
### Godot version

4.0 beta4 (but also present at master ``Nov 8``)

### System information

Windows 10

### Issue description

ShapeCast3D should be updated when changing Shape property
anim

### Steps to reproduce

Add ```ShapeCast3D``` to ```Spatial``` node
Change ```Shape``` 
Debug shape is only changed if changing ```ShapeCast3D``` `s properties 

### Minimal reproduction project

at prefabs/player.tscn
[RPGSample.zip](https://github.com/godotengine/godot/files/9944660/RPGSample.zip)

### PR DESCRIPTION
**Pull request by Jasuse**
Fixes #68304 

Added ```_shape_changed``` callback
Added ```is_editor``` check to ensure debug shape is updated while in editor

### CODE REVIEW

**Comment by MewPurPur** [comment]
Since this is a small PR, make sure to squash your commits into a single one to not clutter the git history. https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase

**Comment by MewPurPur** [comment]
I'm not familiar with 3D, but is the editor check really necessary? Wouldn't it prevent the gizmo from updating on runtime when Debug Collision Shapes is enabled and the shape changes?

**Comment by PrecisionRender** [comment]
> Wouldn't they prevent the gizmo from updating on runtime when Debug Collision Shapes is enabled and the shape changes?

Actually, the debug gizmos do only run in the editor. At runtime, the ShapeCast uses a self-created MeshInstance3D to display its gizmo, same as Raycast3D. I do believe that the `is_editor` check prevents the callbacks from trying to update an editor gizmo that doesn't exist.

**Comment by Jasuse** [comment]
> Since this is a small PR, make sure to squash your commits into a single one to not clutter the git history. https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase

Fixed! (Sorry, looked it through first time at docs, but missed the point, now I see)




> Actually, the debug gizmos do only run in the editor. At runtime, the ShapeCast uses a self-created MeshInstance3D to display its gizmo, same as Raycast3D. I do believe that the `is_editor` check prevents the callbacks from trying to update an editor gizmo that doesn't exist.

As far as I could see, the ```is_debugging_collisions_hint``` (```Visible Collision Shapes``` in Debug tab), used in run-time is ignored in editor and thus prevents updating debug shape. So, `is_editor` forces debug shape to update whatever conditions are(we are in editor afterall), but doesn`t when we are in the game, unless collision debug is active  

Here how it works basically
fixanim

File: scene/3d/shape_cast_3d.h [hunk 1]
```diff
@@ -32,6 +32,7 @@
 #define SHAPE_CAST_3D_H
 
 #include "scene/3d/node_3d.h"
+#include "core/core_string_names.h"
```
Comment (akien-mga) [inline scene/3d/shape_cast_3d.h:35]: This is used in the .cpp, so that's where it should be included.

File: scene/3d/shape_cast_3d.cpp [hunk 2]
```diff
@@ -318,25 +318,36 @@ void ShapeCast3D::resource_changed(Ref<Resource> p_res) {
 	update_gizmos();
 }
 
+
+void ShapeCast3D::_shape_changed() {
```
Comment (akien-mga) [inline scene/3d/shape_cast_3d.cpp:322]: There should only be one empty line between method definitions.

**Comment by akien-mga** [comment]
Is this needed for ShapeCast2D too?

**Comment by Jasuse** [comment]
> Is this needed for ShapeCast2D too?

Nope, debug shape is behaving correctly in 2D

**Review by rburing — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
