### PR TITLE
Fix draw_rect

### LINKED ISSUE #32279: Missing pixel when using draw_rect
**Godot version:**
3.2-dev (https://github.com/godotengine/godot/commit/5ffae0d299aa799c7787e01f3cfe5e377b78a411)

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
A small issue, but an issue nevertheless. When drawing with the `draw_rect` function, there is a missing pixel in the lower left corner. If using fill, the bug doesn't introduce itself. This happens on both GLES3 and GLES2.

missing_pixel

**Steps to reproduce:**
Just put this script to a Node2D: 
```
extends Node2D

func _draw():
	draw_rect(Rect2(1, 1, 100, 100), Color(0.5, 0.8, 0.5), false)
```

**Minimal reproduction project:**
[DrawRectBug.zip](https://github.com/godotengine/godot/files/3642497/DrawRectBug.zip)

### PR DESCRIPTION
**Pull request by ptrojahn**
OpenGL uses the diamond exit rule to rasterize lines. If we don't shift
the points down and to the right by 0.5, the line can sometimes miss a
pixel when it shouldn't. The final fragment of a line isn't drawn. By
drawing the lines clockwise, we can avoid a missing pixel in the rectangle.
See section 3.4.1 in the OpenGL 1.5 specification.
Fixes #32279

### CODE REVIEW

**Comment by clayjohn** [comment]
Changes look good. Can you check that the spec is the same for 2.1 and 3.3?

**Review by Calinou — COMMENTED** [review]
I think it'd be good to write a comment to explain why `0.5` is being added to the values :slightly_smiling_face:

File: scene/2d/canvas_item.cpp [hunk 1]
```diff
@@ -784,22 +784,22 @@ void CanvasItem::draw_rect(const Rect2 &p_rect, const Color &p_color, bool p_fil
 				p_antialiased);
 		VisualServer::get_singleton()->canvas_item_add_line(
 				canvas_item,
-				p_rect.position + Point2(0, offset),
-				p_rect.position + Size2(0, p_rect.size.height - offset),
+				p_rect.position + Point2(p_rect.size.width, offset),
+				p_rect.position + Size2(p_rect.size.width, p_rect.size.height - offset),
```
Comment (akien-mga) [inline scene/2d/canvas_item.cpp]: The order used to be "add `Point2` then add `Size2`, but now it's no longer consistent, you have `Point2`/`Size2` here, but `Size2`/`Point2` for the next two calls.
It's the same typedef so it doesn't matter so much, but the inconsistency looks weird.

**Comment by ptrojahn** [comment]
The idea of diamond exit is explained here: https://docs.microsoft.com/en-us/windows/win32/direct3d11/d3d10-graphics-programming-guide-rasterizer-stage-rules. (This is for directx, but it should be the same in OpenGL.)To make sure that the first pixel of a line is drawn, it should start at the x in the center(0.5, 0.5) of the pixel area. If we start to draw at the top left(0,0), the line might never cut the diamond pattern of the first pixel, leaving a gap at the corner. This works fine on my nvidia GPU, but on my integrated intel haswell gpu it doesn't(At least the missing pixel is now consistently at the top right). I don't think it's possible to create cross platform pixel perfect lines with OpenGL. The algorithm is in the specification for OpenGL 2.1 and 3.3, but vendors are allowed to use slightly different algorithms. It might be interesting if someone with a AMD GPU or more modern intel GPU could test this.

File: scene/2d/canvas_item.cpp (hunk 1 above)
Comment (ptrojahn) [reply scene/2d/canvas_item.cpp]: Yes. Size2 for all probably makes more sense semantically.

**Comment by hbina** [comment]
More resources here, explained pretty succinctly. http://graphics-software-engineer.blogspot.com/2012/04/rasterization-rules.html

**Comment by akien-mga** [comment]
> I think it'd be good to write a comment to explain why `0.5` is being added to the values 

Changes seem good to me, but I agree that adding a short comment in both GLES2 and GLES3 before the `verts` definition would be good to make things explicit.

**Comment by ptrojahn** [comment]
For future reference:
image

**Comment by akien-mga** [comment]
Thanks!

**Comment by AlexHolly** [comment]
It this change causing this issue?

Fills my control fully - all good
```
func _draw():
	draw_rect(Rect2(Vector2(), Vector2(32,32)), Color.red, true)
```
But drawing only the outline has an offset
```
func _draw():
	draw_rect(Rect2(Vector2(), Vector2(32,32)), Color.red, false)
```
image

**Comment by ptrojahn** [comment]
Can't reproduce with your code. Would be helpful if you could add a minimal reproduction project.

**Comment by AlexHolly** [comment]
Can you try to scale the Control by 16,16 this is what I do in my case

**Comment by reduz** [comment]
I understand why this was added, but this is not the right way and it will likely need to be reverted. The reason is that lines can be used with a canvas scale and this will break them.

Researching a better solution is probably a better idea, or likely attempting to implement it in 4.0, which supplies the separate canvas matrices.

**Comment by reduz** [comment]
I suggest doing the pixel shifting at matrix level instead for lines.

**Comment by akien-mga** [comment]
Pushing a partial revert of the line shifting in #33427, as @reduz mentioned that the clockwise draw in CanvasItem is otherwise fine.
