### PR TITLE
Fix AHashMap realloc cause AnimationPlayer crash, second try

### LINKED ISSUE #112038: Engine crashes on animation name with a float
### Tested versions

I am using version 4.5.1.

### System information

Godot v4.5.1.stable - Ubuntu 24.04.3 LTS 24.04 on X11 - X11 display driver, Multi-window, 2 monitors - OpenGL 3 (Compatibility) - Mesa Intel(R) UHD Graphics 630 (CFL GT2) - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 threads) - 15.24 GiB memory

### Issue description

I am manually creating an animation in the following form:

```gdscript
func _ready() -> void:
	var adjustment = randf_range(-0.3, 0.3)
	var animation = Animation.new()
	var track_index = animation.add_track(Animation.TYPE_VALUE)
	animation.track_set_path(track_index, ":position:y")
	animation.track_insert_key(track_index, 0.0, -10)
	animation.track_insert_key(track_index, 1.0 + adjustment, 0)
	animation.length = 1.0 + adjustment
	var library = $AnimationPlayer.get_animation_library("global")
	var name = "rise_" + str(adjustment)
	print(name)
	library.add_animation(name, animation)
	$AnimationPlayer.play("global/" + name)
```

This leads to a crash. I attach a sample of names:

```
rise_0.13513279836257
rise_-0.24190951726188
rise_-0.01806726535611
rise_-0.21182971002127
rise_0.20171917486071
rise_0.02601517296699
rise_0.190256156346
rise_0.06735320351299
rise_0.08413656086737
rise_-0.03430272418879
rise_0.23699314709116

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.5.1.stable.official (f62fdbde15035c5576dad93e586201f4d41ef0cb)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x45330) [0x795488445330] (??:0)
[2] /home/gru/Programs/Godot_v4.5.1-stable_linux.x86_64() [0x3218d5c] (??:0)
[3] /home/gru/Programs/Godot_v4.5.1-stable_linux.x86_64() [0x323da14] (??:0)
[4] /home/gru/Programs/Godot_v4.5.1-stable_linux.x86_64() [0x321bcc7] (??:0)
[5] /home/gru/Programs/Godot_v4.5.1-stable_linux.x86_64() [0x47ab201] (??:0)
[6] /home/gru/Programs/Godot_v4.5.1-stable_linux.x86_64() [0x288a02f] (??:0)
[7] /home/gru/Programs/Godot_v4.5.1-stable_linux.x86_64() [0x288b19f] (??:0)
[8] /home/gru/Programs/Godot_v4.5.1-stable_linux.x86_64() [0x2858f11] (??:0)
[9] /home/gru/Programs/Godot_v4.5.1-stable_linux.x86_64() [0x53e479] (??:0)
[10] /home/gru/Programs/Godot_v4.5.1-stable_linux.x86_64() [0x42d2b7] (??:0)
[11] /lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca) [0x79548842a1ca] (??:0)
[12] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x79548842a28b] (??:0)
[13] /home/gru/Programs/Godot_v4.5.1-stable_linux.x86_64() [0x46ca2a] (??:0)
-- END OF C++ BACKTRACE --
================================================================
```

These might be potentially illegal names, but I don't think they should crash the engine, but throw instead.

### Steps to reproduce

As shown above

### Minimal reproduction project (MRP)

1. Mesh node + Animation player as a scene with the script I attached above
2. In another scene instantiate the other scene

### PR DESCRIPTION
**Pull request by xuhuisheng**
- Fixes: https://github.com/godotengine/godot/issues/112038
- Related: https://github.com/godotengine/godot/pull/113039
- Related: https://github.com/godotengine/godot/issues/113165

# Issue Description

As mentioned in #113039, It is possible to rellocate memory when auto growing using `AHashMap`. So we shouldnot using `AHashMap` to store reference.

And as metioned in  [the comments of #113039](https://github.com/godotengine/godot/pull/113039#pullrequestreview-3503262891). We decided to keep `AHashMap` to improve performance and let `AHashMap` store `animation_name` except the reference of animation.

# Test Cases

https://github.com/godotengine/godot/issues/112038#issuecomment-3541837783

[anim-map-crash-1.webm](https://github.com/user-attachments/assets/894d1176-01ad-4fbf-96d0-d090152583f1)

https://github.com/godotengine/godot/issues/113165#issue-3664653936

[anim-map-crash-2.webm](https://github.com/user-attachments/assets/2c5f8f93-1e85-4707-b90e-aeda9a822403)

# Etc

After testing some projects, I find we need not check `animation_name` equals `stop`.  Please give me some suggestions. @TokageItLab

### CODE REVIEW

File: scene/animation/animation_player.cpp [hunk 1]
```diff
@@ -455,11 +457,11 @@ void AnimationPlayer::play_section(const StringName &p_name, double p_start_time
 
 	Playback &c = playback;
 
-	if (c.current.from) {
+	if (!c.current.animation_name.is_empty()) {
```
Comment (TokageItLab) [inline scene/animation/animation_player.cpp]: Changing null checks to string checks is risky, as I mentioned before. In my opinion, the allocation issue should be resolvable by having a single bool member like `bool is_enabled` in `c.current` and storing the result of the null check into it. Same with other lines.

Comment (xuhuisheng) [reply scene/animation/animation_player.cpp]: I added a `is_enabled` property, and replaced previous null pointer checker with `is_enabled`.

**Review by TokageItLab — APPROVED** [review]
Tested, it should be worked correctly.
