### PR TITLE
Fix `Control.set_position` resizes offsets/anchors (reverted)

### LINKED ISSUE #100536: `GraphNode` doesn't shrink automatically
### Tested versions

v4.4.dev.custom_build [abf47965f]

### System information

Debian Linux X11

### Issue description

`GraphNode` doesn't shrink automatically when
- `size_flags_vertical = SIZE_SHRINK_CENTER`
- the size of child Control nodes decreases

I would expect, that a container node with `SIZE_SHRINK_CENTER` automatically shrinks, when the size of their child nodes decreases.

### Steps to reproduce

1. Load and run MRP
2. Drag the top `HSlider` to the right to increase the vertical size of the labels.
3. Drag the top `HSlider` to the left to decrease the vertical size of the labels.

After 3:
- The label inside the GraphNode became smaller, but the GraphNode didn't adjust its size and appears too big
- For comparison there is a working example on the right side of the scene with a HBoxContainer, that adjusts its vertical size automatically (indicated by the red color)

### Minimal reproduction project (MRP)

[bug-graph-edit-resize.zip](https://github.com/user-attachments/files/18172298/bug-graph-edit-resize.zip)

### PR DESCRIPTION
**Pull request by FilipeAlexCosta**
Fixes #100536
Currently, the Control set_position method uses the object's "size_cache" field in order to recompute its anchors/offsets. However, the size_cache is set in _size_changed() to be at least as large as the combined minimum size of the Control, meaning that setting its position while the combined minimum size is larger than the the bounding rectangle given by the offsets and anchors essentially resizes it.
This makes the Control unable to automatically shrink as seen with the GraphNode in the original issue this addresses. The issue focused mostly on the GraphEdit and GraphNode, but it can actually occur with other kinds of object as illustrated here (the rectangle on the left is a HBoxContainer):

https://github.com/user-attachments/assets/c6ec0e65-eef3-4a58-b5fe-c6b0bcd7010f

To fix this, I made it so set_position is based solely on the size obtained through the offsets and anchors instead of the size_cache:

https://github.com/user-attachments/assets/e1a0c836-8801-4d2e-a586-1f515c51cc2c

I have also added a new test case to make sure Control objects are able to shrink in this scenario.

### CODE REVIEW

**Comment by FilipeAlexCosta** [comment]
@KoBeWi

File: tests/scene/test_control.h [hunk 1]
```diff
@@ -990,6 +990,38 @@ TEST_CASE("[SceneTree][Control] Anchoring") {
...
 
+TEST_CASE("[SceneTree][Control] Set position does not cause size side-effects") {
+	Control *test_control = memnew(Control);
+	test_control->set_size(Size2(1, 1));
+	test_control->set_custom_minimum_size(Size2(2, 2));
+	Window *root = SceneTree::get_singleton()->get_root();
+	root->add_child(test_control);
+
+	SUBCASE("Shrinks after setting position and smaller custom minimum size (without keeping offsets)") {
+		test_control->set_position(Point2(0, 0), false);
```
Comment (KoBeWi) [inline tests/scene/test_control.h:1001]: It should change position to some non-default value. Usually setting something to the same value has no effect (it has in case of this method, but it may change).

**Review by KoBeWi — APPROVED** [review]
Looks fine.  Not sure about cherry-picking it though.

File: tests/scene/test_control.h (hunk 1 above)
Comment (FilipeAlexCosta) [reply tests/scene/test_control.h:1001]: Makes sense! I'll push the changes soon. Thanks for the feedback.

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
