### PR TITLE
Fix C# Solution Directory Project Settings

### LINKED ISSUE #68381: Project settings for C# solution directory and project directory not working correctly
### Godot version

3.5.1.stable.mono.official, 4.0.beta4.mono.official

### System information

Windows 10, VS 2022 Community, dotNet CLI and MSBuild (VS)

### Issue description

I'm attempting to use project settings "Mono->Project->Solution Directory" and "Mono->Project->C# Project Directory" to get .sln and .csproj files to be created in, or used from, specified subdirectories, rather than the Godot project root (see [this proposal and the pulls resolving it](https://github.com/godotengine/godot-proposals/issues/1575)).  In 4.0-beta4, these settings are relabeled Dotnet->Project->... and require the "Advanced Settings" toggle to be turned on.

On my machine (W10/VS2022/VS MSBuild or dotNet CLI), however, Godot 3.5.1 and 4.0-beta4 ignore these settings or encounter project-breaking bugs when they are used. This is both for initially creating the .sln and .csproj files, and when populating the settings and moving the .sln and .csproj files after initial creation. Failure modes include creating solution files in the wrong directory, re-creating solution files in the wrong directory, and build and/or runtime errors depending on version.

### To reproduce initial creation of the files in the wrong directory:
1. Create a new Godot project.
2. Create a subdirectory for the solution and a sub-subdirectory for the C# project.
3. Open Project Settings and edit the "Solution Directory" and "C# Project Directory" settings to indicate the subdirectories you created.
4. Create a basic scene and set it as the project's main scene. Attach a C# script and place it in the C# project sub-subdirectory.

**Expected behavior:** Godot will create .sln and .csproj files in the indicated subdirectories.
**Observed:** Godot will create .sln and .csproj files in the project root directory, instead of the indicated subdirectories. 

### To reproduce re-creation of files in the wrong directory:
1. Follow steps above, populating the project settings for "Solution Directory"  and "C# Project Directory" either before or after initial creation of the C# script.
2. Close Visual Studio if open.
3. Without closing Godot, move the .sln and .csproj files to the correct directories.
4. In Godot, press the "Build" button.

**Expected behavior:** Godot will read the .sln and .csproj files from the indicated directories.
**Observed:** Godot creates new .sln and .csproj files in the project root. Additionally, there is an output message reading "scene/gui/popup_menu.cpp:1191 - Index p_idx = -1 is out of bounds (items.size() = 0)." (In 4.0-beta4, the indicated line number in popup_menu.cpp is 1723.)

### To reproduce build errors after moving .sln and .csproj files:
1. Follow steps above to create a project, attach a C# script, and populate project settings for solution and C# project directories.
2. Close Visual Studio and Godot.
3. Move the .sln and .csproj files to the correct directories.
4. Reopen Godot, open the project, and press the "Build" button.

**Expected behavior:** Godot will read the .sln and .csproj files from the indicated directories.
**Observed:** Godot fails to build the C# solution, apparently looking for the .csproj file in the same directory as the .sln file (possibly because the .sln file was created referring to a .csproj file in the same directory and has not been updated to reflect that they are in different directories?). The full error (in my 3.5.1 test project) reads:

> C:\Users\Mark\Documents\Godot\DirectoriesBug6\src\DirectoriesBug6.sln" (Restore target) (1) ->
>        (_FilterRestoreGraphProjectInputItems target) -> 
>          C:\Program Files\dotnet\sdk\6.0.402\NuGet.targets(369,5): error MSB3202: The project file "C:\Users\Mark\Documents\Godot\DirectoriesBug6\src\DirectoriesBug6.csproj" was not found. [C:\Users\Mark\Documents\Godot\DirectoriesBug6\src\DirectoriesBug6.sln]

### To reproduce build/runtime errors after updating .sln file to point to correct .csproj location:
_Note, this bug displays different behaviors in 3.5.1 and 4.0-beta4._

1. Follow steps above to create a project, attach a C# script, and populate project settings for solution and C# project directories.
2. Close Visual Studio and Godot.
3. Move the .sln and .csproj files to the correct directories.
4. Open the .sln file in Visual Studio. It will complain that the .csproj was not found. Remove the outdated reference to the .csproj and use "Add Existing Project" to add it back at its new location.

At this point, 3.5.1 and 4.0-beta4 diverge in their behavior. 3.5.1 continues to experience build errors, while 4.0-beta4 encounters a runtime error.

**Expected behavior:** Visual Studio and Godot build the solution from the correct location.

**Observed, 3.5.1:** At this point, Godot sees and reads the relocated .sln file, but neither Visual Studio nor Godot will build the project without errors. Visual Studio shows broken dependencies on the GodotSharp assemblies and throws build errors indicating "type or namespace not found" for Godot dependencies:
VSBrokenGodotAssemblies
VSBuildMessages

Godot will show the same errors:
GodotBuildMessages

**Observed, 4.0-beta4:** Visual Studio initially flags the GodotSharp packages as broken when the .csproj is added from its new location, but it corrects them and successfully builds the solution:
VSFixedGodotSharpv4

Godot also successfully builds the project. However, when the Godot project runs, although it does not crash, Godot's debugger displays the following error, and nothing in the script is executed (e.g., a GD.Print("Hello world"); in _Ready() does not produce output):

> E 0:00:01:0793   can_instantiate: Cannot instance script because the associated class could not be found. Script: 'res://src/DirectoriesBug4-v4/Root.cs'.
>   <C++ Error>    Method/function failed. Returning: false
>   <C++ Source>   modules/mono/csharp_script.cpp:2288 @ can_instantiate()
> 

**Additional troubleshooting attempts/information for 3.5.1 after updating the .sln to point to the new location for the .csproj:**
- From Godot, using the "Clean Solution" option from the Build menu produces an error indicating that Godot is trying to read the node's script file from the project root, despite the node's properties correctly pointing to the C# file in the subdirectory. The same build errors as above persist on the next build attempt:
GodotWrongCSharpFileLocation
GodotCorrectCSharpFileLocation

- As a naive attempt with no real understanding of the internals, I'm able to get Visual Studio to build the solution by copying the .mono directory from the project root into the solution directory. However, this doesn't resolve build errors within Godot (output is identical to the post-clean errors showing incorrect script location, as in the previous bullet), so I'm guessing that folder copy can't actually function as a fix and there are other things that need to be adjusted.

### Minimal reproduction project

"DirectoriesBug1" is a v3.5.1 project with the correct configuration to reproduce the bug in initial creation of sln and csproj files -- it has a basic main scene, subdirectories to contain the C# solution and project, and the settings to place the solution and project configured. Adding a C# script to the "Root" scene will cause the .sln and .csproj files to be populated in the project root; moving them and attempting to build while leaving Godot open will cause the files to be re-created at the project root.

"DirectoriesBug2" is the same, but after adding the C# script and moving the sln/csproj files to the correct locations, but without manually updating the sln to point to the csproj. The script, sln, and csproj files are in the correct locations with respect to the Godot project settings, but attempting to build in Godot will give the error that the csproj file is not found (looking in the sln directory).

"DirectoriesBug3" is the same, but with the .sln and .csproj files moved to the correct subdirectories and the .sln file updated with the new .csproj location. Godot 3.5.1 will see the .sln file in its new location but it will not build the project correctly, showing errors about missing Godot assemblies.

"DirectoriesBug3Beta" is the same as DirectoriesBug3, but for v4.0-beta4. It will build correctly in VS or Godot, but will show a runtime error in the debugger about instancing a script (see above in "Steps to reproduce"), and will not execute the print statement in the main scene's _Ready() method.

[DirectoriesBug1.zip](https://github.com/godotengine/godot/files/9941816/DirectoriesBug1.zip)
[DirectoriesBug2.zip](https://github.com/godotengine/godot/files/9953585/DirectoriesBug2.zip)
[DirectoriesBug3.zip](https://github.com/godotengine/godot/files/9953611/DirectoriesBug3.zip)
[DirectoriesBug3Beta.zip](https://github.com/godotengine/godot/files/9953673/DirectoriesBug3Beta.zip)

### PR DESCRIPTION
**Pull request by NeilKleistGao**
Related Issue: #68381

he C# editor plugin would not load the change of project settings, so it always generates files in the default directory. I added a function  `RefreshProjectLocation` to force it reloading the settings.

The `dll` compiled would be generated where the `sln` file is, so the engine could not find it correctly. I added `BaseOutputPath` and `OutputPath` in the `csproj` file to re-indicate that dotnet should output results in the default place.

In the default case, a C# script would be compiled only if it is located at the same/the sub directory of the `csproj`. To make all scripts reachable, I also added`Compile Include` in `csproj`.

Since the `GodotProjectDir` in `modules\mono\editor\Godot.NET.Sdk\Godot.NET.Sdk\Sdk\Sdk.props` depends on the `sln` file's path, rather than `res://`, scripts' pathes in the `dll` file would be incorrect after the `sln` file has been moved. So I rewrote the `GodotProjectDir` in the `csproj`.

It runs well on my device. Feel free to tell me if something goes wrong or something needs to be changed. :smiley: 

*Bugsquad edit:*
- Fixes #68381

### CODE REVIEW

File: modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs [hunk 1]
```diff
@@ -57,24 +57,24 @@ private bool CreateProjectSolution()
             {
                 pr.Step("Generating C# project...".TTR());
 
-                string resourceDir = ProjectSettings.GlobalizePath("res://");
-
-                string path = resourceDir;
+                GodotSharpDirs.RefreshProjectLocation();
```
Comment (neikeq) [inline modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs:60]: This should not be called manually. Instead, it should be called when the `EditorPlugin.ProjectSettingsChanged` signal is emitted (`GodotSharpEditor` inherits `EditorPlugin`).

File: modules/mono/editor/GodotTools/GodotTools/Internals/GodotSharpDirs.cs [hunk 2]
```diff
@@ -76,10 +81,14 @@ static string DetermineProjectName()
...
             if (string.IsNullOrEmpty(slnParentDir))
                 slnParentDir = "res://";
+            else if (!slnParentDir.StartsWith("res://"))
+                slnParentDir = "res://" + slnParentDir;
 
             string csprojParentDir = (string)ProjectSettings.GetSetting("dotnet/project/c#_project_directory");
             if (string.IsNullOrEmpty(csprojParentDir))
                 csprojParentDir = "res://";
+            else if (!csprojParentDir.StartsWith("res://"))
+                csprojParentDir = "res://" + csprojParentDir;
```
Comment (neikeq) [inline modules/mono/editor/GodotTools/GodotTools/Internals/GodotSharpDirs.cs:91]: What is this needed for?

File: modules/mono/editor/GodotTools/GodotTools.ProjectEditor/ProjectGenerator.cs [hunk 3]
```diff
@@ -25,6 +25,19 @@ public static ProjectRootElement GenGameProject(string name)
...
+
+                string basePath = Path.Combine("$(GodotProjectDir)", ".godot", "mono", "temp", "bin");
+
+                mainGroup.AddProperty("BaseOutputPath", basePath);
+                mainGroup.AddProperty("OutputPath", Path.Combine(basePath, "$(Configuration)"));
+
+                var itemGroup = root.AddItemGroup();
+                itemGroup.AddItem("Compile", Path.Combine(projectDir, "*.cs"));
+            }
+
```
Comment (neikeq) [inline modules/mono/editor/GodotTools/GodotTools.ProjectEditor/ProjectGenerator.cs:40]: No, this should not be generated as part of the C# project file. This problem should be fixed in the Sdk:

https://github.com/godotengine/godot/blob/cd491c6e47bb41ccf596189676c0c5d4a72226cc/modules/mono/editor/Godot.NET.Sdk/Godot.NET.Sdk/Sdk/Sdk.props#L15-L16

Can you check if changing those two lines to the following works?

```csproj
<GodotProjectDir Condition=" '$(GodotProjectDir)' == '' ">$(MSBuildProjectDirectory)</GodotProjectDir>
```

**Review by neikeq — CHANGES_REQUESTED** [review]

File: modules/mono/editor/GodotTools/GodotTools/Internals/GodotSharpDirs.cs (hunk 2 above)
Comment (NeilKleistGao) [reply modules/mono/editor/GodotTools/GodotTools/Internals/GodotSharpDirs.cs:91]: I added these two checks to make sure that if users forgot to add `"res://"` in front of the path, the editor could also get the correct path.

File: modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs (hunk 1 above)
Comment (NeilKleistGao) [reply modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs]: I connected it with the `EditorPlugin.ProjectSettingsChanged`. Should I also need to disconnect when the plugin is disabled? Since we didn't override the `_DisablePlugin`, I'm not very sure if it is necessary.

File: modules/mono/editor/GodotTools/GodotTools.ProjectEditor/ProjectGenerator.cs (hunk 3 above)
Comment (NeilKleistGao) [reply modules/mono/editor/GodotTools/GodotTools.ProjectEditor/ProjectGenerator.cs:40]: Seems not. `$(MSBuildProjectDirectory)` indicates the path of `csproj` files. If users don't put the `csproj` file in the default directory, the engine still could not find the `dll` file.

Comment (neikeq) [reply modules/mono/editor/GodotTools/GodotTools.ProjectEditor/ProjectGenerator.cs:40]: Do you have any project with the `csproj` in a different location? Do you know anyone else doing that? I think it was a mistake from my part to allow that, so I'm considering reverting it. Allowing to change the solution location is fine, but the `csproj` should be in the same folder as `project.godot`. The setting should only allow changing the project name, not the project directory.

Comment (NeilKleistGao) [reply modules/mono/editor/GodotTools/GodotTools.ProjectEditor/ProjectGenerator.cs:40]: > Do you have any project with the `csproj` in a different location? Do you know anyone else doing that?

Of course no. 

I agree with putting `csproj` where `project.godot` is. That might be the best solution so far. I will revoke this part of modification sooner.

File: modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs (hunk 1 above)
Comment (NeilKleistGao) [reply modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs]: OK! Thank you for your explaining! 😄

File: modules/mono/editor/GodotTools/GodotTools.ProjectEditor/ProjectGenerator.cs (hunk 3 above)
Comment (NeilKleistGao) [reply modules/mono/editor/GodotTools/GodotTools.ProjectEditor/ProjectGenerator.cs]: I also removed `csproj` settings. Maybe we need to change the title of this PR.

File: modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs [hunk 4]
```diff
@@ -375,6 +378,8 @@ public override void _EnablePlugin()
         {
             base._EnablePlugin();
 
+            Connect("project_settings_changed", new Callable(this, "RefreshProjectLocation"));
```
Comment (neikeq) [inline modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs:381]: Is the setting not available as an event?

```suggestion
            ProjectSettingsChanged += GodotSharpDirs.DetermineProjectLocation;
```

File: modules/mono/editor/GodotTools/GodotTools.ProjectEditor/ProjectGenerator.cs (hunk 3 above)
Comment (neikeq) [reply modules/mono/editor/GodotTools/GodotTools.ProjectEditor/ProjectGenerator.cs]: Looks good!

File: modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs (hunk 4 above)
Comment (NeilKleistGao) [reply modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs]: Oops. Sorry. It is of course. :no_mouth:

File: modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs [hunk 5]
```diff
@@ -51,30 +51,33 @@ private bool CreateProjectSolutionIfNeeded()
             return true;
         }
 
+        private void RefreshProjectLocation()
+        {
+            GodotSharpDirs.DetermineProjectLocation();
+        }
+
```
Comment (neikeq) [inline modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs:58]: Forgot to remove this unused method

**Review by neikeq — APPROVED** [review]

File: modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs (hunk 5 above)
Comment (NeilKleistGao) [reply modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs]: Removed.

**Comment by akien-mga** [comment]
Thanks!

File: modules/mono/editor/GodotTools/GodotTools.ProjectEditor/ProjectGenerator.cs (hunk 3 above)
Comment (markawilson) [reply modules/mono/editor/GodotTools/GodotTools.ProjectEditor/ProjectGenerator.cs]: Hi, I'm just one person and I'm prepared to be misunderstanding this decision, or wrong about my approach, or an uncommon case that's not worth the effort. However, I am actually putting (or trying to put) the csproj in a different location than the godot project, because I'm creating multiple csprojs in a solution and I'm used to organizing multiple projects in subdirectories of a solution. (E.g., [this example](https://gist.github.com/davidfowl/ed7564297c61fe9ab814) of a solution layout.)

I appreciate the fix, but I guess I don't understand what the purpose of moving the sln would be, if you can't also move the csproj. You end up with the sln, which is the organizational root, in a subdirectory, but the csproj, which is below the sln in the solution hierarchy, above the sln in the directory structure. To me this seems like it undermines good solution organization, especially if you have other csprojs that will live in sub-subdirectories under the sln.

Thanks for the fix and all the other work developing Godot!

Comment (raulsntos) [reply modules/mono/editor/GodotTools/GodotTools.ProjectEditor/ProjectGenerator.cs]: The example solution layout that you shared should still work, no need to change the csproj location.

Maybe take a look at the layout in issue https://github.com/godotengine/godot/issues/69225 for an example that should work for multi-project scenarios.

I think your misunderstanding comes from using the Godot project directory as the root, when it should be just one more C# project in the solution.

File: modules/mono/editor/GodotTools/GodotTools/Internals/GodotSharpDirs.cs [hunk 6]
```diff
@@ -52,10 +52,9 @@ public static void RegisterProjectSettings()
         {
             GlobalDef("dotnet/project/assembly_name", "");
             GlobalDef("dotnet/project/solution_directory", "");
-            GlobalDef("dotnet/project/c#_project_directory", "");
```
Comment (avilches) [inline modules/mono/editor/GodotTools/GodotTools/Internals/GodotSharpDirs.cs:55]: Why this setting was removed? Before this change, the main project could be located in a different folder, which was one of the new features Godot 4 offered. But now, the main csproj should be located in the same folder, so it's not possible to have

```
/project.godot
/Game.sln
/Src/Game.csproj
/Src/**/*.cs
```

I guess this PR is solving more issues, so my question is: why the csproj should be in the same folder as project.godot?

Comment (raulsntos) [reply modules/mono/editor/GodotTools/GodotTools/Internals/GodotSharpDirs.cs:55]: Think of the Godot project as one more C# project in your solution. Usually you'd have the solution file (`.sln`) in the root directory and then subdirectories for each C# project (`.csproj`). See issue https://github.com/godotengine/godot/issues/69225 for an example of a valid folder structure.

Moving the `.csproj` can cause issues. For example, Godot allows you to attach any `.cs` file in the Godot project directory as a script to a Node, this means you can end up in a situation where the `.cs` file is not included in the `.csproj` compilation but it's still attached to a Node.

I don't think there are strong use cases to justify the complexities of supporting moving the `.csproj` so, after discussion, it was decided to remove the setting. I think keeping the `.csproj` in the same directory as the `project.godot` file should cover most cases, and allowing to move the `.sln` should be enough to support multi-project scenarios.

Comment (avilches) [reply modules/mono/editor/GodotTools/GodotTools/Internals/GodotSharpDirs.cs:55]: Interesting, so the final idea for a multiproject solution is:
```
/Root.sln
/Game/project.godot
/Game/Game.csproj
/Game/**/*.(tscn|png|ogg|...)
/Game/**/*.cs
/Tool1/Tool1.csproj
/Tool1/**/*.cs
/Tool2/Tool2.csproj
/Tool2/**/*.cs
```
Right? If this is the case, then resources, scenes and plugins must be located and mixed along with the main godot project C# classes. I thought this is one of the things we wanted to avoid. I can live with this (this is what we had in Godot 3), but I think having assets and classes in different folders is a more clean approach:

```
/Root.sln
/project.godot
/**/*.(tscn|png|ogg|...)
/Game/Game.csproj
/Game/**/*.cs
/Tool1/Tool1.csproj
/Tool1/**/*.cs
/Tool2/Tool2.csproj
/Tool2/**/*.cs
```
But, of course, this is just an opinion. I can't find where all discussions have taken place. I feel that we, the beta testes, are using different folder layouts and we have been opening issues, changing this behaviour during the beta multiple times. Not sure what's the best approach, but having more settings to configure this and allow us to use any layout could be awesome, but I understand it could end up in more issues

Comment (neikeq) [reply modules/mono/editor/GodotTools/GodotTools/Internals/GodotSharpDirs.cs:55]: You can still choose to put all your scripts in a sub-folder, even if the csproj is at root.

It was a mistake on my part to allow changing the C# project location. It should never have been done. I meant to provide a setting for the C# project name, to avoid issues when changing the Godot project name, but I went too far.

Raul explained one of the problems with it: you could have a script attached to a node and that script may not be part of the C# project, which could be confusing.

Another reason is that it broke our build code. Our MSBuild files need a way to know the location of the Godot project root. We can do this by assuming it's the same as either the solution directory or the C# project directory. If both of these can change, then we can no longer locate it.

I'm sure there could be other ways to fix the last problem, but considering the first one about scripts, I thought it was better to just lock the csproj location.

Perhaps we can re-introduce this setting in the future, but it would have to be done properly, making sure it doesn't cause any issue.

Comment (avilches) [reply modules/mono/editor/GodotTools/GodotTools/Internals/GodotSharpDirs.cs:55]: Ok, now I understand the decision was made to avoid confusion and bugs for the users, which is very legitimate. I guess we can expect no more behaviour changes on this side. Thanks for the answer. :)
