### PR TITLE
Fix OpenGL `_shadow_atlas_find_shadow` error when light instance is freed

### LINKED ISSUE #84747: OpenGL: _shadow_atlas_find_shadow: Condition "!sli" is true. Continuing.
### Godot version

4.2 beta 5

### System information

Godot v4.2.beta5 - Linux Mint 21.2 (Victoria) - X11 - GLES3 (Compatibility) - GeForce GT 525M (nvidia; 390.157) - Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 Threads)

### Issue description

Getting error when using Shadows in SpotLight3D:

E 0:00:55:0236   _shadow_atlas_find_shadow: Condition "!sli" is true. Continuing.
  <C++ Source>   drivers/gles3/storage/light_storage.cpp:954 @ _shadow_atlas_find_shadow()

### Steps to reproduce

Screenshot from 2023-11-11 13-28-48

### Minimal reproduction project

https://we.tl/t-FpjcvyZYws

### PR DESCRIPTION
**Pull request by Arthas92t**
- Fixes #84747

In file light_storage.cpp, when engine free a light instance, it didn't free the shadow atlas and set owner of it to RID(). 
https://github.com/godotengine/godot/blob/master/drivers/gles3/storage/light_storage.cpp#L366-L384
So the next time engine try to find a useable shadow atlas, it will have this issue
I think we can just ignore the case sli == null and return the shadow atlas when we meet it, since the light instance of that atlas already freed

### CODE REVIEW

File: drivers/gles3/storage/light_storage.cpp [hunk 1]
```diff
@@ -1064,7 +1064,12 @@ bool LightStorage::_shadow_atlas_find_shadow(ShadowAtlas *shadow_atlas, int *p_i
 
 		for (int j = 0; j < sc; j++) {
 			LightInstance *sli = light_instance_owner.get_or_null(sarr[j].owner);
-			ERR_CONTINUE(!sli);
+			if (!sli) {
+				// Found a released light instance.
+				found_used_idx = j;
+				min_pass = -1;
```
Comment (clayjohn) [inline drivers/gles3/storage/light_storage.cpp:1070]: Since we are breaking, we don't need to set the min_pass.

**Review by clayjohn — COMMENTED** [review]
Looks great! I left a small comment to clean up a line we don't need. Otherwise this looks great

**Comment by Arthas92t** [comment]
> Looks great! I left a small comment to clean up a line we don't need. Otherwise this looks great

Thank you, you was right. I removed that line.

**Review by clayjohn — APPROVED** [review]
Looks great! Thank you!

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.
