### PR TITLE
C#: Add checks to Android export

### LINKED ISSUE #82013: .NET Android export should validate that the TargetFramework is `net7.0`, and that only supported architectures are selected (i.e. `x64` or `arm64-v8a`)
### Godot version

v4.2-dev5_mono_win64 (and 4.2-dev4_mono_win64)

### System information

Godot v4.2.dev5.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 with Max-Q Design (NVIDIA; 31.0.15.3161) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)

### Issue description

Android export fails because of a non-existent NuGet package that can't be restored:
image

Manually trying to add this package to my project reports that the closest version available is 7.0.0, and that the platform is incompatible with the generated csproj file.
```
dotnet add package Microsoft.NETCore.App.Runtime.linux-bionic-x64 --version 6.0.21
  Determining projects to restore...
  Writing C:\Users\Mikey\AppData\Local\Temp\tmp1057.tmp
info : X.509 certificate chain validation will use the default trust store selected by .NET for code signing.
info : X.509 certificate chain validation will use the default trust store selected by .NET for timestamping.
info : Adding PackageReference for package 'Microsoft.NETCore.App.Runtime.linux-bionic-x64' into project 'C:\Projects.temp\Project1\Project1.csproj'.
info : Restoring packages for C:\Projects.temp\Project1\Project1.csproj...
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.runtime.linux-bionic-x64/index.json
warn : NU1603: Project1 depends on Microsoft.NETCore.App.Runtime.linux-bionic-x64 (>= 6.0.21) but Microsoft.NETCore.App.Runtime.linux-bionic-x64 6.0.21 was not found. An approximate best match of Microsoft.NETCore.App.Runtime.linux-bionic-x64 7.0.0 was resolved.
error: NU1213: The package Microsoft.NETCore.App.Runtime.linux-bionic-x64 7.0.0 has a package type DotnetPlatform that is incompatible with this project.
error: Package 'Microsoft.NETCore.App.Runtime.linux-bionic-x64' is incompatible with 'all' frameworks in project 'C:\Projects.temp\Project1\Project1.csproj'.
```

running `dotnet --list-sdks` reports that I have both 6.0 and 7.0 installed:
```
dotnet --list-sdks
6.0.317 [C:\Program Files\dotnet\sdk]
7.0.400 [C:\Program Files\dotnet\sdk]
```

### Steps to reproduce

1. On Windows 11 (yes I'm running 11 -- not 10 as the system info states) -- Download and run Godot 4.2-dev4 or 4.2-dev5, and create a new project.
2. Create a simple scene with some CSG boxes, and a camera, attach a working C# script to one of the nodes.
3. Generate the C# project files, and using visual studio 2022, add some code to the script.
4. Attempt to export the APK using the automatically downloaded template.
5. It fails with the above error about the missing nuget package and incompatible framework.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by raulsntos**
- Add .NET 7.0 TFM when the platform is Anroid to the created csproj.
- Prevent exporting to Android when the architecture is not supported.
- Fixes https://github.com/godotengine/godot/issues/82013.

The intention is to communicate the limitations of the current experimental Android exports to users and hopefully simplify the process.

### CODE REVIEW

File: modules/mono/editor/GodotTools/GodotTools.ProjectEditor/ProjectGenerator.cs [hunk 1]
```diff
@@ -23,6 +23,8 @@ public static ProjectRootElement GenGameProject(string name)
 
             var mainGroup = root.AddPropertyGroup();
             mainGroup.AddProperty("TargetFramework", "net6.0");
+            var net70 = mainGroup.AddProperty("TargetFramework", "net7.0");
+            net70.Condition = " '$(GodotTargetPlatform)' == 'android' ";
```
Comment (raulsntos) [inline modules/mono/editor/GodotTools/GodotTools.ProjectEditor/ProjectGenerator.cs:27]: I'm not so sure about this change, this would only be added to newly created projects so users still need to modify their csproj manually in existing projects.

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Comment by akien-mga** [comment]
Thanks!
