### PR TITLE
Restored antialiased lines by emulation using triangle strips

### LINKED ISSUE #40845: canvas_item_add_polyline does not handle width
**Godot version:**
https://github.com/godotengine/godot/commit/00e1175b7dcd01be9b13c8fe852af68a916f45e6

**OS/device including version:**

Nvidia gtx 2080 series

**Issue description:**

Expect being able to draw polylines with width.

A polyline is drawn without width.

**Steps to reproduce:**

Call:

void RenderingServerCanvas::canvas_item_add_polyline(RID p_item, const Vector<Point2> &p_points, const Vector<Color> &p_colors, float p_width)

with a width.

Width is not set.

image

**Minimal reproduction project:**

No reproduction project, but the effect can be seen in this pr. https://github.com/godotengine/godot/pull/40513

### PR DESCRIPTION
**Pull request by Chaosus**
I decided to try to restore them since the current thin lines look pretty ugly:

image

I restored the antialiasing in `canvas_item_add_polyline` and the called methods `draw_arc`, `draw_polyline`, `draw_polyline_colors`, and through them, enables it in `GraphEdit`.

I think the final result looks good (it looks identical to 3.2):
lines

Fix #40845

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Looks good to me!

**Comment by Chaosus** [comment]
Ah, and this PR also superseding: #40866, the difference is - I just using 
triangle strips (instead of list) and implement antialiasing

**Comment by reduz** [comment]
Lets discuss this a bit on IRC because I am unsure about some things.

File: servers/rendering/rendering_server_canvas.cpp [hunk 1]
```diff
@@ -531,59 +531,86 @@ void RenderingServerCanvas::canvas_item_add_line(RID p_item, const Point2 &p_fro
...
+				t = (p_points[i + 1] - p_points[i]).normalized().tangent();
+				if (i == 0) {
+					prev_t = t;
+				}
 			}
+
+			Vector2 tangent = ((t + prev_t).normalized()) * p_width * 0.5;
+			Vector2 pos = p_points[i];
+
+			points.append(pos + tangent);
```
Comment (reduz) [inline servers/rendering/rendering_server_canvas.cpp:579]: I suggest if possible to resize the arrays, then get the pointer to Vector2* via ptrw() and write directly as it will most likely be much faster than appending.

Comment (Chaosus) [reply servers/rendering/rendering_server_canvas.cpp]: Fixed

**Review by reduz — APPROVED** [review]
