### PR TITLE
C#: Always show "Create C# solution" option

### LINKED ISSUE #60940: Project/Tools/C# shows no options
### Godot version

v3.4.4.stable.mono.official [419e713a2]

### System information

Windows 10, GLES3

### Issue description

I followed the tutorial https://gist.github.com/paulloz/30ae499c1fc580a2f3ab9ecebe80d9ba to get code completion for VSCode, and got stuck in step 3.

When I click on "Project", and hover over "Tools", then "C#", no options are showing up. Obviously there shouldn't be an empty menu slot, even if maybe there no longer are these options. Or maybe they still exist, but are not showing up for me.

image

I was able to reproduce it with a minimal setup, but got a slightly different appearance:
image

This bug occurs on my desktop PC with Ryzen 5 2600, RTX 3070 and my laptop with Ryzen 7 4700U, integrated GPU; both are running Windows 10.

### Steps to reproduce

- create a new project
- create a new script via the built-in file explorer
  - use C# as type
- click on the menus, and go to Tools/C#
- the box is now empty

### Minimal reproduction project

This is one of the project, where the issue occurs for me:
[TestProject2.zip](https://github.com/godotengine/godot/files/8667641/TestProject2.zip)

### PR DESCRIPTION
**Pull request by raulsntos**
Prevents ending up with an empty C# menu.
The option to create the C# solution no longer disappears, to avoid confusing users. I think always showing the option is less confusing than hiding the C# menu when it's empty.
If an user tries to use it when a C# solution already exists they are warned that it will override their `.sln` and `.csproj` files.

- Fixes https://github.com/godotengine/godot/issues/60940.

### CODE REVIEW

**Review by neikeq — APPROVED** [review]

File: modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs [hunk 1]
```diff
@@ -122,8 +122,17 @@ private void _MenuOptionPressed(long id)
             switch ((MenuOptions)id)
             {
                 case MenuOptions.CreateSln:
-                    CreateProjectSolution();
+                {
+                    if (File.Exists(GodotSharpDirs.ProjectSlnPath))
```
Comment (RedworkDE) [inline modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs:126]:
```suggestion
                    if (File.Exists(GodotSharpDirs.ProjectSlnPath) || File.Exists(GodotSharpDirs.ProjectCsProjPath))
```
This also overwrites the project file,

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.1.
