### PR TITLE
Fix NavigationAgent reparent issues

### LINKED ISSUE #54812: Reparenting a NavigationAgent2D into a SubViewport causes navigation to fail
### Godot version

v4.0.dev.20211108.official [596865366]

### System information

Windows 10

### Issue description

On project run I reparent a container Node2D containing a TileMap and an Enemy with a NavigationAgent2D child into a SubViewport. This causes the NavigationAgent2D to fail at finding a parent.

https://user-images.githubusercontent.com/3820082/140990387-5d88acba-977e-4bce-ac86-a01895b498ce.mp4

This can be fixed in these ways:

a) Have the container Node2D parented to the SubViewport in the scene beforehand (you can not edit the SubViewport's children in the editor this way.)

b) Create a NavigationAgent2D on the Enemy after it's been moved into the SubViewport.

My expectation is that the NavigationAgent2D's world would be updated upon reparenting so that navigation still works. I also don't see a way to update the agent's world in GDScript.

### Steps to reproduce

Open the attached MRP in a recent Godot 4.0 pre-alpha build and run the default scene. To disable the reparent, select the Node of the default scene and toggle the exported Reparent bool, then run the scene again.

### Minimal reproduction project

[nav-reparent-mrp.zip](https://github.com/godotengine/godot/files/7507380/nav-reparent-mrp.zip)

### PR DESCRIPTION
**Pull request by smix8**
This pr fixes (all?) the (re)parenting issues that NavigationAgent Nodes have.

Calling NavigationAgent setup with a get_parent() function only once in _ready() was troubesome. What if agent is moved or removed from tree and rejoins? what if parent is switched, what if agent is created with scripts, ... and so many options to mess NavigationAgents parents up.

Fixes #54812

Supersedes #54904 which was stale and used another ready notification to fix some of this but calling _ready() twice is too dangerous with user scripts.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Could you make a backport PR for `3.x`? The conflicts don't seem too hard to resolve but I'm a bit busy this week.

File: scene/2d/navigation_agent_2d.cpp [hunk 1]
```diff
@@ -96,16 +96,30 @@ void NavigationAgent2D::_bind_methods() {
...
 		} break;
 
+		case NOTIFICATION_PARENTED: {
+			if (is_inside_tree() && (get_parent() != agent_parent)) {
+				// only react to PARENTED notifications when already inside_tree and parent changed, e.g. users switch nodes around
+				// PARENTED notification fires also when Node is added in scripts to a parent
+				// this would spam transforms fails and world fails while Node is outside SceneTree
+				// when node gets reparented when joining the tree POST_ENTER_TREE takes care of this
+				set_agent_parent(get_parent());
+				set_physics_process_internal(true);
```
Comment (AaronRecord) [inline scene/2d/navigation_agent_2d.cpp:113]: @smix8 Does this code ever get called? It looks like `NOTIFICATION_PARENTED` always gets called before the node has its tree assigned:
https://github.com/godotengine/godot/blob/0c815022178ca23fa55085981384caa749f7f18a/scene/main/node.cpp#L1130-L1134

and as far as I know there's no way to reparent a node without removing it from the tree first

Comment (smix8) [reply scene/2d/navigation_agent_2d.cpp:113]: I dont remember the details but there was a specific issue where a user managed to corrupt the agent connection with the wrong parent due to shuffling node parents with subscenes and this fixed it. Thats also why I left such a large comment so I wouldn't remove it myself in a few months because I would also assume it wouldn't ever be triggered.
