### PR TITLE
Fix autocompletion of static methods in built-in types in GDScript

### LINKED ISSUE #58826: [4.0] Autocomplete does not work for static functions
### Godot version

4.0 (compiled today)

### System information

Windows 10

### Issue description

4.0 added static functions for built-in types. However this doesn't seam to work with the autocomplete system within the built-in script editor, it never suggests the functions, not even when it already has been used elsewhere in the file.

Example:
image

### Steps to reproduce

1. Create a new script
2. Try to autocomplete one of Color static functions

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Chaosus**
Added autocompletion for static functions of built-in types:

gds_completion

Fix https://github.com/godotengine/godot/issues/58826

### CODE REVIEW

**Comment by KoBeWi** [comment]
The method should be inserted with `(`, like with normal method completion.

**Comment by Chaosus** [comment]
> The method should be inserted with (, like with normal method completion.

@KoBeWi I think I'm done with it:
gds_completion2

File: core/variant/variant.h [hunk 1]
```diff
@@ -531,7 +531,8 @@ class Variant {
 	static bool is_builtin_method_const(Variant::Type p_type, const StringName &p_method);
 	static bool is_builtin_method_static(Variant::Type p_type, const StringName &p_method);
 	static bool is_builtin_method_vararg(Variant::Type p_type, const StringName &p_method);
-	static void get_builtin_method_list(Variant::Type p_type, List<StringName> *p_list);
+	static void get_builtin_method_list(Variant::Type p_type, List<StringName> &r_list);
+	static void get_builtin_static_method_list(Variant::Type p_type, List<StringName> &r_list);
```
Comment (vnen) [inline core/variant/variant.h:535]: Is there any particular reason to change these from pointer to reference?

File: modules/gdscript/gdscript_editor.cpp [hunk 2]
```diff
@@ -2421,6 +2421,32 @@ static void _find_call_arguments(GDScriptParser::CompletionContext &p_context, c
 	} else if (callee_type == GDScriptParser::Node::SUBSCRIPT) {
 		const GDScriptParser::SubscriptNode *subscript = static_cast<const GDScriptParser::SubscriptNode *>(call->callee);
 
+		const GDScriptParser::IdentifierNode *base_identifier = static_cast<const GDScriptParser::IdentifierNode *>(subscript->base);
```
Comment (vnen) [inline modules/gdscript/gdscript_editor.cpp:2424]: It's not guaranteed that the base will always be an `IdentifierNode`, so you need to check if it actually is (checking the node type) before casting.

File: core/variant/variant.h (hunk 1 above)
Comment (Chaosus) [reply core/variant/variant.h:535]: I thought it was a good idea, since these functions are useless without passing a list parameter (and there is no place in code where it happened). Passing a reference is less error-prone than passing a pointer (which requires a null checking anyway).

File: modules/gdscript/gdscript_editor.cpp (hunk 2 above)
Comment (Chaosus) [reply modules/gdscript/gdscript_editor.cpp]: Fixed!

File: core/variant/variant.h (hunk 1 above)
Comment (Chaosus) [reply core/variant/variant.h]: Removed this change.

**Review by vnen — APPROVED** [review]
LGTM. Might need a review from the core team about the new method in Variant.

File: core/variant/variant.h [hunk 3]
```diff
@@ -532,6 +532,7 @@ class Variant {
 	static bool is_builtin_method_static(Variant::Type p_type, const StringName &p_method);
 	static bool is_builtin_method_vararg(Variant::Type p_type, const StringName &p_method);
 	static void get_builtin_method_list(Variant::Type p_type, List<StringName> *p_list);
+	static void get_builtin_static_method_list(Variant::Type p_type, List<StringName> *p_list);
```
Comment (reduz) [inline core/variant/variant.h:535]: I am not sure if this is really needed. You should be able to request the method list and check whether they are static. For autocompletion purposes it will probably make no difference.

**Comment by akien-mga** [comment]
Thanks!
