### PR TITLE
Fix case where `h_separation` might not work in `Button`

### LINKED ISSUE #64140: [3 to 4 regression] Button `h_separation` is not included in minimum size calculation.
### Godot version

v4.0.alpha.custom_build [7355dfb50]

### System information

Arch on 5.18.16-arch1-1

### Issue description

image

### Steps to reproduce

1) Create a button with an icon and text
2) Set `h_separation` to ~20 or higher.

### Minimal reproduction project

[empty.zip](https://github.com/godotengine/godot/files/9287038/empty.zip)

### LINKED ISSUE #64371: Inspector buttons are missing padding on the right side
### Godot version

v4.0.alpha14.official [106b68050]

### System information

Windows 10

### Issue description

Inspector buttons are missing padding on the right side of the text.

| Alpha 13 | Alpha 14 |
---|---
| image | image |
| image | image |
| image | image |

### Steps to reproduce

* Select a node.
* Look at the Add Metadata button at the bottom of the inspector.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Rindbee**
Fix #64140.
*Bugsquad edit:* Fixes #64371

| Before | After |
| :-------: | :-----: |
|| |

~~Split from #59340.~~

There are still issues with the drawing and will be fixed in another PR.

Edit:
This patch mainly solves two things:
1. The typo of `h_separation`;
2. Negative values of `h_separation` will be treated as `0` when used, to prevent the button's minimum `width` from being reduced by `h_separation`.

### CODE REVIEW

File: scene/gui/button.cpp [hunk 1]
```diff
@@ -342,16 +340,21 @@ Size2 Button::get_minimum_size_for_text_and_icon(const String &p_text, Ref<Textu
 		minsize.width = 0;
 	}
 
-	if (!expand_icon && !p_icon.is_null()) {
-		minsize.height = MAX(minsize.height, p_icon->get_height());
+	if (!p_icon.is_null()) {
```
Comment (KoBeWi) [inline scene/gui/button.cpp:343]:
```suggestion
	if (p_icon.is_valid()) {
```

File: scene/gui/button.cpp [hunk 2]
```diff
@@ -342,16 +340,21 @@ Size2 Button::get_minimum_size_for_text_and_icon(const String &p_text, Ref<Textu
...
+			minsize.height = MAX(minsize.height, p_icon->get_height());
+			_icon_width_cached = p_icon->get_width();
+		}
 
 		if (icon_alignment != HORIZONTAL_ALIGNMENT_CENTER) {
-			minsize.width += p_icon->get_width();
+			minsize.width += _icon_width_cached;
 			if (!xl_text.is_empty() || !p_text.is_empty()) {
-				minsize.width += get_theme_constant(SNAME("hseparation"));
+				minsize.width += MAX(0, get_theme_constant(SNAME("h_separation")));
```
Comment (KoBeWi) [inline scene/gui/button.cpp:354]: This change makes it impossible to have negative `h_separation`. I don't think it's necessary to limit it (or at least the limitation should be documented).

**Review by KoBeWi — APPROVED** [review]
Looks good.

File: scene/gui/button.cpp (hunk 2 above)
Comment (Rindbee) [reply scene/gui/button.cpp:354]: A negative value of `h_separation` is meaningless, otherwise, it may make `minsize.width` smaller, become `0` or even a **negative** value (even if there is an icon or text). In some cases this can result in insufficient visible space for drawing.

Comment (KoBeWi) [reply scene/gui/button.cpp:354]: It makes the text overlap icon. Weird, but maybe someone wants it.
Limit it is fine too, I guess. But as I said, it should be documented in the property description.

**Comment by KoBeWi** [comment]
You added me as co-author (GitHub does this automatically when you accept a suggestion).

**Review by KoBeWi — DISMISSED** [review]

**Comment by Rindbee** [comment]
Sorry, `h_separation` should be ignored when `expand_icon` is enabled.

**Comment by KoBeWi** [comment]
Uh why should it be ignored? It's just a space between icon and text. If you expand icon and resize to 0, it's still there and separation should take effect. The previous behavior was alright.

**Comment by KoBeWi** [comment]
Ah seems like CheckBox etc. apply the separation twice for their own icon.
image
In this case ignoring separation makes sense.

But there is still no reason to ignore it in Button. You could either add a virtual method that tells whether this should be ignored or, more simple but not much used in the codebase, some `protected bool` property.

**Comment by Rindbee** [comment]
| version | picture |
| :-------: | :-------: |
|   v4.0.alpha13.official [82811367c] | alpha13|
| v4.0.alpha.custom_build [317ced820] |  |
| v4.0.alpha.custom_build [323d611a6] |  |

The table above is a comparison of the minimum size between versions. In the picture, the right node is a copy of the left node with `expand_icon` enabled.

I hope I have understood correctly what the expectation is like.

**Comment by Rindbee** [comment]
I seem to be getting more and more deviated from the original intention. Now I only fix typo and restrict `h_separation` from being negative.

**Comment by KoBeWi** [comment]
OptionButton minimum size seems broken:
godot windows tools 64_3hNJ8pA3rH

CheckBox center alignment makes the text go into separation area:
godot windows tools 64_FkKmFR9U8f
The worst part is that it's more to the left than Left alignment. CheckButton has similar problem.

**Comment by Rindbee** [comment]
> OptionButton minimum size seems broken.

I guess it has something to do with `fit_to_longest_item`, switching `expand_icon` doesn't update the cache.
Steps to reproduce it:
1. Make `h_separation` larger, such as `200`;
2. Let `fit_to_longest_item` be disabled and `expand_icon` be enabled;
3. Then `enable fit_to_longest_item`;
4. Enable `expand_icon again`.

Currently, changes in factors affecting `get_minimum_size` do not update the `OptionButton` cache. I think it's better to disable `fit_to_longest_item` first and then test, finally, solve the problem of `fit_to_longest_item` cache update in other PRs.

> CheckBox center alignment makes the text go into separation area. The worst part is that it's more to the left than Left alignment. CheckButton has similar problem.

This should be a drawing issue, which will be resolved in #64351, where there is a set of comparison images with alpha13.

**Review by KoBeWi — APPROVED** [review]
I assume https://github.com/godotengine/godot/pull/64218#issuecomment-1211818278 is addressed in #64351?

**Comment by Rindbee** [comment]
I guess no, both patches are trying to get back to alpha13. Except that a negative `h_separation` is treated as `0`, and limits the extent to which the `text`/`icon` can be drawn. These changes between alpha13 should be intuitively found from comparing `png`s in #64351.

This issue in https://github.com/godotengine/godot/pull/64218#issuecomment-1211818278 also exists in alpha13. 

I'm a little unclear on what exactly it should look like. So had to use alpha13 as a reference. If there is something wrong in alpha13, I will fix it later. I'm a little concerned about over-modification causing other regressions.

It might be better to figure out what it should look like first.


1. internal element (`i_icon`)
  1.1 existence
2. custom elements
  2.1. custom icon (`icon`)
    2.1.1. existence
    2.1.2. `expand_icon`
    2.1.3. `icon_alignment`
  2.2. custom text (`text`)
    2.2.1. existence 
    2.2.2. `clip_text`
    2.2.3. text `alignment`
  2.3. separation between custom elements (`s1`)
3. separation between internal element and custom elements (`s0`)

The above will directly and indirectly affect the minimum size.
In alpha13, if there are only `icon` and `i_icon`, `s0` is ignored. It's a little different when if `i_icon`, `icon`, `text` all exists.

captrue




I haven't looked into the button's design criteria, the documentation's description, the actual drawing, and your suggestions are all inconsistent.

However, this patch is intended to fix typo to get it back to a slightly better state.

**Comment by akien-mga** [comment]
Thanks!
