### PR TITLE
Redo of Message Queue

### LINKED ISSUE #35653: Change MessageQueue to a page allocator to prevent overflow
**Godot version:**
Master (3cfb67e0f)

**OS/device including version:**
Any

**Issue description:**
As discussed a few times on IRC, and exemplified by many bug reports, our current fixed size for the Message Queue is problematic.

It currently defaults to `1024` (see `memory/limits/message_queue/max_size_kb`), and many users need to increase it to prevent overflow when handling a large amount of messages (which can happen easily in the editor when using e.g. large TileSets #29238 or Skeletons #35652).

As discussed with @reduz, Message Queue should be changed to use a page allocator so that its size can grow as needed, preventing overflows.

Situations which can cause a Message Queue overflow like #29238 or #35652 should however be fixed in the Inspector itself, as even increasing the MQ will just make things functional again, but it will still freeze a long time while populating all those controls.

### PR DESCRIPTION
**Pull request by reduz**
* Functionality moved to a base class CallQueue, which will be used for inter-thread communication within the scene.
* MessageQueue now uses growing pages, starts from a single 4k page.
* Limit still exists, but because its not allocated by default, it can be much higher.

- Fixes #35653
- Supersedes #62303 and #65740.

### CODE REVIEW

**Comment by YuriSizov** [comment]
You're missing an empty line before the closing header guard :) This prevents the rest of the builds from running.

File: core/object/message_queue.h [hunk 1]
```diff
@@ -33,26 +33,44 @@
 
 #include "core/object/object_id.h"
 #include "core/os/thread_safe.h"
+#include "core/templates/local_vector.h"
+#include "core/templates/paged_allocator.h"
 #include "core/variant/variant.h"
-
```
Comment (akien-mga) [inline core/object/message_queue.h:37]: Keep separation between includes and forward declares.

File: core/object/message_queue.h [hunk 2]
```diff
@@ -33,26 +33,44 @@
...
 class Object;
 
-class MessageQueue {
-	_THREAD_SAFE_CLASS_
-
+class CallQueue {
+public:
 	enum {
-		DEFAULT_QUEUE_SIZE_KB = 4096
+		QUEUE_PAGE_SIZE = 4096 // PAGE_SIZE seems like a reserved identifier on some Linux.
```
Comment (akien-mga) [inline core/object/message_queue.h:44]: I don't know if we'll really care about this trivia once it's merged and we wouldn't consider renaming it anyway :P

File: core/object/message_queue.cpp [hunk 3]
```diff
@@ -291,54 +262,203 @@ void MessageQueue::flush() {
...
+		memdelete(allocator);
+	}
+}
+
+//////////////////////
+
+MessageQueue *MessageQueue::singleton = nullptr;
+
+MessageQueue::MessageQueue() :
+		CallQueue(nullptr, int(GLOBAL_DEF_RST(PropertyInfo(Variant::INT, "memory/limits/message_queue/max_size_mb", PROPERTY_HINT_RANGE, "1,512,1,or_greater"), 32)) * 1024 * 1024 / QUEUE_PAGE_SIZE, "Message queue out of memory. Try increasing 'memory/limits/message_queue/max_size_kb' in project settings.") {
```
Comment (akien-mga) [inline core/object/message_queue.cpp:457]:
```suggestion
		CallQueue(nullptr, int(GLOBAL_DEF_RST(PropertyInfo(Variant::INT, "memory/limits/message_queue/max_size_mb", PROPERTY_HINT_RANGE, "1,512,1,or_greater"), 32)) * 1024 * 1024 / QUEUE_PAGE_SIZE, "Message queue out of memory. Try increasing \"memory/limits/message_queue/max_size_mb\" in project settings.") {
```
All this in a constructor call is pretty unreadable though :(

File: core/object/message_queue.cpp [hunk 4]
```diff
@@ -35,94 +35,53 @@
...
 
-	int room_needed = sizeof(Message) + sizeof(Variant) * p_argcount;
+	_ensure_first_page();
 
-	if ((buffer_end + room_needed) >= buffer_size) {
-		ERR_PRINT("Failed method: " + p_callable + ". Message queue out of memory. Try increasing \"memory/limits/message_queue/max_size_kb\" in project settings.");
-		statistics();
-		return ERR_OUT_OF_MEMORY;
+	if ((page_offset + room_needed) > uint32_t(PAGE_SIZE_BYTES)) {
+		if (room_needed > uint32_t(PAGE_SIZE_BYTES) || pages_used == max_pages) {
```
Comment (lawnjelly) [inline core/object/message_queue.cpp:71]: Am wondering, can any of these pushed messages require more than 4096 bytes (including parameters)?

Comment (reduz) [reply core/object/message_queue.cpp:71]: I think the 4096 bytes limit is sensible. Variants are normally 20-40 bytes depending on whether you compile floats to doubles, and messages as a base are about the same size. This means that the only way you  could exceed this is with a call with more than 100 arguments, which is probably unreasonable and unlikely.

File: core/object/message_queue.h [hunk 5]
```diff
@@ -33,26 +33,45 @@
...
 	};
 
+	Mutex mutex;
+	typedef PagedAllocator<Page, true> Allocator;
+
+	Allocator *allocator = nullptr;
+	bool allocator_is_custom = false;
+
+	LocalVector<Page *> pages;
+	LocalVector<uint32_t> page_messages;
```
Comment (RandomShaper) [inline core/object/message_queue.h:69]: I believe that some arithmetic involving `pages_used`, page size and `page_offset` could replace the use cases of this array.

**Review by RandomShaper — COMMENTED** [review]
Looks good, besides a few comments I've added.

File: core/object/message_queue.cpp [hunk 6]
```diff
@@ -291,54 +262,205 @@ void MessageQueue::flush() {
...
+}
+
+//////////////////////
+
+MessageQueue *MessageQueue::singleton = nullptr;
+
+MessageQueue::MessageQueue() :
+		CallQueue(nullptr,
+				int(GLOBAL_DEF_RST(PropertyInfo(Variant::INT, "memory/limits/message_queue/max_size_mb", PROPERTY_HINT_RANGE, "1,512,1,or_greater"), 32)) * 1024 * 1024 / PAGE_SIZE_BYTES,
+				"Message queue out of memory. Try increasing 'memory/limits/message_queue/max_size_kb' in project settings.") {
```
[the remark this answers is not in the document]
Comment (reduz) [reply core/object/message_queue.cpp:459]: oh thanks, I totally missed this one

File: core/object/message_queue.h [hunk 7]
```diff
@@ -115,13 +135,22 @@ class MessageQueue {
...
 
 	bool is_flushing() const;
-
 	int get_max_buffer_usage() const;
 
+	CallQueue(Allocator *p_custom_allocator = 0, uint32_t p_max_pages = 8192, const String &p_error_text = String());
+	virtual ~CallQueue();
+};
+
+class MessageQueue : public CallQueue {
```
[the remark this answers is not in the document]
Comment (reduz) [reply core/object/message_queue.h:149]: That makes sense, in fact, it could be renamed to MainThreadMessageQueue, but it requires touching a lot of other code for the PR, so I think its probably better to leave this for a separate PR renaming it.

File: core/object/message_queue.cpp [hunk 8]
```diff
@@ -133,89 +92,95 @@ Error MessageQueue::push_callablep(const Callable &p_callable, const Variant **p
...
+	uint32_t room_needed = sizeof(Message) + sizeof(Variant);
 
-	uint32_t read_pos = 0;
-	while (read_pos < buffer_end) {
-		Message *message = (Message *)&buffer[read_pos];
+	_ensure_first_page();
 
-		Object *target = message->callable.get_object();
+	if ((page_offset + room_needed) > uint32_t(PAGE_SIZE_BYTES)) {
+		if (room_needed > uint32_t(PAGE_SIZE_BYTES) || pages_used == max_pages) {
```
[the remark this answers is not in the document]
Comment (reduz) [reply core/object/message_queue.cpp:115]: This makes sense, in fact this check is only needed for the callablep, and not for notification or set. I will specialcase it there.

File: core/object/message_queue.cpp [hunk 9]
```diff
@@ -35,94 +35,53 @@
...
 }
 
-Error MessageQueue::push_callablep(const Callable &p_callable, const Variant **p_args, int p_argcount, bool p_show_error) {
-	_THREAD_SAFE_METHOD_
+Error CallQueue::push_callablep(const Callable &p_callable, const Variant **p_args, int p_argcount, bool p_show_error) {
+	mutex.lock();
+	uint32_t room_needed = sizeof(Message) + sizeof(Variant) * p_argcount;
 
-	int room_needed = sizeof(Message) + sizeof(Variant) * p_argcount;
+	_ensure_first_page();
```
Comment (lawnjelly) [inline core/object/message_queue.cpp:68]: Can this be done at construction? (Maybe there's a reason for the non-message queues not to have the fixed penalty of 4Kb)

File: core/object/message_queue.h (hunk 5 above)
Comment (reduz) [reply core/object/message_queue.h:69]: It could, and one alternative is to rework the message format and use a terminator case (as an extra value of the message type enum) but it would make the code more complex, so I think this is just simpler.

**Comment by lawnjelly** [comment]
Also looks fine to me.

File: core/object/message_queue.cpp [hunk 10]
```diff
@@ -291,54 +264,208 @@ void MessageQueue::flush() {
...
+int CallQueue::get_max_buffer_usage() const {
+	return pages.size() * PAGE_SIZE_BYTES;
+}
+
+CallQueue::CallQueue(Allocator *p_custom_allocator, uint32_t p_max_pages, const String &p_error_text) {
+	if (p_custom_allocator) {
+		allocator = p_custom_allocator;
+		allocator_is_custom = true;
+	} else {
+		allocator = memnew(Allocator(16)); // 16 pages per allocator page, 64kb per allocator page. Anything small will do, though.
```
Comment (RandomShaper) [inline core/object/message_queue.cpp:439]:
```suggestion
		allocator = memnew(Allocator(16)); // 16 elements per allocator page, 64kb per allocator page. Anything small will do, though.
```

**Review by RandomShaper — APPROVED** [review]
Added new comments about minor things. Good to go in any case.

File: core/object/message_queue.h (hunk 5 above)
Comment (RandomShaper) [reply core/object/message_queue.h:69]: Not the end of the world. I was just thinking about cache pollution, etc., but you never know until you measure in practice.

File: core/object/message_queue.h [hunk 11]
```diff
@@ -33,26 +33,45 @@
...
 class Object;
 
-class MessageQueue {
-	_THREAD_SAFE_CLASS_
-
+class CallQueue {
+public:
 	enum {
-		DEFAULT_QUEUE_SIZE_KB = 4096
+		PAGE_SIZE_BYTES = 4096
```
[the remark this answers is not in the document]
Comment (RandomShaper) [reply core/object/message_queue.h:45]: Well, that's more or less addressed in the constructor, but that sentence at the top of the code would be great regardless.

File: core/object/message_queue.cpp (hunk 10 above)
Comment (RandomShaper) [reply core/object/message_queue.cpp]: 16 PagedAllocator pages = 16 x 4 KiB = 64 KiB

The code could be a bit more explicit, like:
```
const uint32_t CallQueue::memnew(Allocator(TARGET_ALLOCATOR_PAGE_SIZE_BYTES = 64 * 1024;

// [...]

allocator = memnew(Allocator(TARGET_ALLOCATOR_PAGE_SIZE_BYTES / PAGE_SIZE_BYTES)); 
```

**Comment by akien-mga** [comment]
Thanks!
