### PR TITLE
Fix GPU particles not emitting at some configured rates when scale curve is zero

### LINKED ISSUE #103140: GPU particles not emitting at some configured rates when scale curve is zero
### Tested versions

- Reproducible in: v4.4.beta4.official [93d270693]

### System information

Godot v4.4.beta4 - Fedora Linux 41 (Workstation Edition) on Wayland - X11 display driver, Single-window, 1 monitor - OpenGL 3 (Compatibility) - AMD Radeon RX 560 Series (radeonsi, polaris11, LLVM 19.1.0, DRM 3.60, 6.12.15-200.fc41.x86_64) - Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 threads)

### Issue description

At certain emission rates (`3` and `6`, at least), GPU particles appear to emit at a rate of 1 instead of the configured emission amount.

The `GPUParticles3D` instances in the MRP and the following video are lined up with incrementing emission values, from 1 to 6. Observe that emission values of 1, 3, and 6 emit at the same rate.

https://github.com/user-attachments/assets/41d56cdb-447d-441e-85d1-c1505eae47b5

#### Related

New pull request:

- https://github.com/godotengine/godot/pull/103121

Related:

- https://github.com/godotengine/godot/issues/83699

Old issues:

- https://github.com/godotengine/godot/issues/68809
- https://github.com/godotengine/godot/issues/80863

Old pull requests:

- https://github.com/godotengine/godot/pull/81913
- https://github.com/godotengine/godot/pull/81902

### Steps to reproduce

1. Load `test_scene_1.tscn` of the attached project in a current master build (4.4-beta4, as of writing).
2. Observe that the GPU particle instances that are set to emission amounts `3` and `6` are emitting at the same rate as the instance set to an emission amount of `1`. It's possible that results vary here based on GPU.
3. Load the project in a build of Godot that includes this PR's changes.
4. Observe that each GPU particle in the sequence emits 1 more than the previous, as expected from their configured emission amounts.

### Minimal reproduction project (MRP)

[godot-4_4-gpu-particle-scale-bug.zip](https://github.com/user-attachments/files/18904604/godot-4_4-gpu-particle-scale-bug.zip)

### PR DESCRIPTION
**Pull request by OhiraKyou**
Fixes https://github.com/godotengine/godot/issues/103140

This PR re-fixes GPU particles not emitting at the configured rate when using a scale curve that starts or ends at a value of 0.

### Demonstration

Master:

https://github.com/user-attachments/assets/41d56cdb-447d-441e-85d1-c1505eae47b5

This PR:

https://github.com/user-attachments/assets/35c4d336-0522-48d1-b0b5-455f61159257

### Explanation

The cause was the use of `sign()`, under the expectation that it would result in a value that is exclusively either `-1` or `1`. However, `sign()` returns `0` when given `0`. So, when that was multiplied by the minimum value, instead of applying the sign of the original scale (which had no sign), it just nullified the minimum value entirely. So, the whole expression did nothing at all.

This has been fixed before (see the related section in [the associated issue](https://github.com/godotengine/godot/issues/103140)). So, I added a descriptive comment to give this a better chance of staying fixed.

### CODE REVIEW

**Comment by clayjohn** [comment]
This PR breaks negative scales since it always assumes a positive scale. 

Do you have an MRP that reproduces the bug? We are generally pretty careful about merging code to fix unreported bugs.

**Comment by OhiraKyou** [comment]
This does not break negative scale, because the minimum value is only applied when scale is equal to `0`. Effectively, this PR is the equivalent of pretending that `sign(0)` returns `1`. It doesn't; it returns `0`, which is why the expression this PR replaces did nothing.

There's an MRP that you may have missed in the description, including steps to reproduce it. I also included previous issues and PRs that attempted to fix the issue. But, those were later replaced by clever combinations of `sign()`, `max()`, and `abs()` (as seen in the code this PR replaces) that don't actually do anything as a result of `sign()` returning 0 when given 0.

**Comment by OhiraKyou** [comment]
Actually, I do need to change one important thing, though; I forgot to multiply the scale parameter at the end. Will fix.

**Comment by OhiraKyou** [comment]
Fixed. If the scale is `0`, the values are multiplied by a minimum positive value (`0.001`). Otherwise, they are multiplied by the scale parameter (which can be positive or negative).

File: scene/resources/particle_process_material.cpp [hunk 1]
```diff
@@ -1121,9 +1121,12 @@ void ParticleProcessMaterial::_update_shader() {
 		code += "		params.scale *= texture(scale_over_velocity_curve, vec2(0.0)).rgb;\n";
 		code += "	}\n";
 	}
-	code += "	TRANSFORM[0].xyz *= sign(params.scale.x) * max(abs(params.scale.x), 0.001);\n";
-	code += "	TRANSFORM[1].xyz *= sign(params.scale.y) * max(abs(params.scale.y), 0.001);\n";
-	code += "	TRANSFORM[2].xyz *= sign(params.scale.z) * max(abs(params.scale.z), 0.001);\n";
+	// Zero scale results in no emission at some amounts (including 3 and 6).
+	// Do not use `sign(scale) * max(abs(scale), 0.001)`, for this, because sign() returns 0 for 0.
+	// So, it ends up multiplying the minimum value of 0.001 by 0, nullifying the guard entirely.
+	code += "	TRANSFORM[0].xyz *= params.scale.x == 0.0 ? 0.001 : params.scale.x;\n";
```
Comment (clayjohn) [inline scene/resources/particle_process_material.cpp:1127]: This looks much better now. I am a bit worried about the floating point comparison though. Floating point comparisons are fine for values that are set directly, but if the scale is the result of some intermediate calculations, there are cases where params.scale.x should be 0 but is slightly larger or smaller. 

The old logic had a (rather high) epsilon built in to the calculation. I'm not sure if it is necessary though. Did you look into the source of `params.scale.x` to see if floating point error is possible?

If there is a risk of floating point error, then we should replace `params.scale.x == 0.0` with `abs(params.scale.x) < 0.001` to match the old behaviour.

Comment (OhiraKyou) [reply scene/resources/particle_process_material.cpp]: I have amended the fix to simply replace `sign(scale)` with a manual sign calculation that evaluates to `1` (instead of `0`) when given a scale of `0`. This should preserve the original code intent while fixing the issue.

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 4.4.1.
