### PR TITLE
Optimize mesh generation by preventing unneeded shape recalculations

### LINKED ISSUE #99414: huge speedup possible: meshes are regenerated unnecessarily when settings (eg radius) are set to their existing value
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Ubuntu 22.04

### Issue description

Mesh (such as a Sphere) is regenerated, wasting work, when the result will be exactly the same.

### Steps to reproduce

Add this to a _process():
> mesh.radius = 0.5

(in a real-world app, the value is calculated every frame based on user settings, but when the value is not changing, it still rebuilds the mesh)

### Minimal reproduction project (MRP)

https://github.com/godotengine/godot/blob/fd4c29a189e53a1e085df5b9b9a05cac9351b3ef/scene/resources/3d/primitive_meshes.cpp#L1904

I'm wondering if a line like this would be appropriate:
> if is_equal_approx(radius, p_radius) { return }

Otherwise, the app has to do it in GDScript, which is much slower than C++, duplicated work across godot apps, etc.

I think this easy optimization should be added everywhere in Godot when changing a setting triggers heavy work.

If this is not implemented, then the docs should be updated to warn about the performance hit "even if setting to the same value".

### PR DESCRIPTION
**Pull request by carsonetb**
Currently whenever a value of a PrimitiveMesh is set in GDScript it will completely regenerate the entire mesh. This is fine in most cases, but in the case that the set variable is the same as the current variable (p_radius == radius), there's no need to regenerate the mesh. In some cases we could get a big performance boost by just returning the function if the set variable is the same as the current one.

This PR fixes #99414

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected with all primitive mesh types.

Code looks good to me.

File: scene/resources/3d/primitive_meshes.cpp [hunk 1]
```diff
@@ -194,6 +195,9 @@ Mesh::PrimitiveType PrimitiveMesh::surface_get_primitive_type(int p_idx) const {
 }
 
 void PrimitiveMesh::surface_set_material(int p_idx, const Ref<Material> &p_material) {
+	if (p_material == material) {
+		return;
+	}
```
Comment (clayjohn) [inline scene/resources/3d/primitive_meshes.cpp:200]: This check is redundant because `set_material` already calls it

**Review by clayjohn — COMMENTED** [review]
I've just got one little suggestion. Otherwise, this looks great!

When you make the change, you can also take the opportunity to squash your commits together before merging. We like to have only one commit per PR when we merge to keep the git history clean. 

If you don't know how to do that, we have a helpful tutorial in the official documentation https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase

File: scene/resources/3d/primitive_meshes.cpp (hunk 1 above)
Comment (carsonetb) [reply scene/resources/3d/primitive_meshes.cpp:200]: Thanks! I was waiting too make sure no one had any suggestions to squash the commits. I'll make the change and squash them now!

**Comment by carsonetb** [comment]
This should be ready to merge!

**Review by clayjohn — APPROVED** [review]
Thank you!

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉

**Comment by lighttroupe** [comment]
Fantastic work, @carsonetb

I was surprised to read on your profile that you're a middle schooler.  Your communication on the original issue and here, use of git, PR naming, is all excellent.  Keep it up; you're going to go far!

**Comment by elouangrimm** [comment]
Congrats @carsonetb! :)
