### PR TITLE
Account for physics interpolation and transform snapping when Y-sorting

### LINKED ISSUE #92982: 2D Physics interpolation not working with Y-Sort enabled
### Tested versions

Tested in Godot v4.3.beta1

### System information

Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.4592) - 13th Gen Intel(R) Core(TM) i7-13700F (24 Threads)

### Issue description

Just as title describes, with parent Node2D's y-sort enabled, a child node will not be smoothed when its y-sort is enabled.

https://github.com/godotengine/godot/assets/33864304/05cc327a-0831-4c84-82b6-a6ba66d86549

### Steps to reproduce

1. Open and Run MRP
2. The CharacterBody2D disables y-sort by default. use directional keys to move around and the movement is smooth.
3. Press SPACE key and move the CharacterBody2D  again, the movement will not be smoothed.

### Minimal reproduction project (MRP)

[2d_interp_mrp.zip](https://github.com/user-attachments/files/15775700/2d_interp_mrp.zip)

### PR DESCRIPTION
**Pull request by kleonc**
Makes the transforms used for Y-sorting canvas items match the transforms used for such items in `RendererCanvasCull::_cull_canvas_item`, aka it accounts for physics interpolation and transform snapping.

Fixes #92982.

This is done in the first commit as a simple change which results in calculating physics interpolation and transform snapping twice for each y-sorted item: when determining transforms used for y-sorting while gathering to-be-y-sorted items, and when actually handling them after they're y-sorted (also note that calculating transforms twice introduces a chance of using different transforms for sorting/rendering in case there's some mismatch in calculations).

---

The second commit makes the transform calculations (physics interpolation, transform snapping) happen once for each y-sorted item, before y-sorting (so it's sorted according to the position used later for rendering).

For reviewing the second commit I recommend looking at combined first+second commits diff, should be simpler.

In more detail:

`RendererCanvasCull::Item::ysort_xform` was previously storing a transform from the parent of the given item to the y-sorted subtree's root, now it's changed to store a transform from the given item to the y-sorted subtree's root instead.
Meaning previously y-sorted `item`'s final transform was `ysorted_subtree_root.final_xform * item.ysort_xform * item.self_xform`, now it's `ysorted_subtree_root.final_xform * item.ysort_xform` as `item.self_xform` is calculated before y-sorting and it's included into `item.ysort_xform` to not need to recalculate it later.

As a result `RendererCanvasCull::Item::ysort_pos` was removed as no longer needed, now `item.ysort_xform.origin` is the exact same position (the item's position in y-sorted subtree's root coordinate space) which can be used for sorting instead.

Renamed `RendererCanvasCull::_cull_canvas_item`'s `p_allow_y_sort` parameter to `p_is_already_y_sorted` as it seemed more intuitive to me, given it's usage (and negated the passed value everywhere).

So now when `p_is_already_y_sorted == true` the item's final transform was already calculated during y-sorting, and it's passed as `p_parent_xform` to `RendererCanvasCull::_cull_canvas_item` (kinda disliking this naming/behavior discrepancy but oh well). Thus in such case self/local transform is not being recalculated, and thus it's not available (only the final transform is passed).

Also extracted the count-only part of `RendererCanvasCull::_collect_ysort_children` into separate `RendererCanvasCull::_count_ysort_children` as with the transform calculations added it seemed too "ify".
And moved `_mark_ysort_dirty` into `RendererCanvasCull` as well.

I guess that's it, feel free to ask for any further explanation/clarification in case something is unclear.

Oh, and I'd understand if the second commit is considered too risky for cherry-picking into 4.3.stable etc. so of course I could split it into 2 PRs or whatever else is desired.

### CODE REVIEW

**Comment by lawnjelly** [comment]
I'll take a look.

I vaguely remember doing something to fix y-sorting at some point but maybe it's not working in 3.x too, I'll check the issue and see if I can reproduce in 3.x.

**Comment by kleonc** [comment]
> I can't seem to reproduce so far in 3.x, but then the Y sort works quite differently there. (I'm not super familiar with how 4.x does y sorting.)

IIRC in 3.x the canvas item with `sort_y = true` is treated as a grouping-only item, it's not drawn itself (the VisualServer implementation seems to be done specifically with YSort node in mind, assuming YSort doesn't draw itself - hence e.g. #49165). I'd guess that's something about that. But yeah, I haven't looked in detail into 3.x in quite a while (we complement each othere here :smile:).

> Key things is probably making sure it isn't doing more work than necessary, ideally shouldn't be interpolating transforms twice.

Yes, currently it indeed does interpolate twice per y-sorted item, I'm well aware of that and I do dislike it. Was focusing on conceptually fixing the transform calculations here (in fact I haven't tested it much in action, only in the MRP from #92982; was fixing purely from the code standpoint; so testing further welcomed).
But I think I already know how to avoid this double computation, later today I will probably push a second commit in here (such change seems more regression prone so I think leaving it as a separate commit would make sense).

**Comment by markdibarry** [comment]
@kleonc Oof! I never even imagined anyone would use a parallax effect with y-sorting... and I still can't think of a use case, but I'm sure someone can and will be very upset! I tried it on the master branch and it seems to remove all repeats, but everything else seems to be working so I guess that's the only thing we'll need to suss out.

**Comment by kleonc** [comment]
@markdibarry Firstly let's clarify of what behavior of y-sorting + repeating we're talking.
y-sorted<br>no repeat|(1) repeats y-sorted separately|(2) repeats y-sorted as one item together with the original one
-|-|-
0KjXYYPuxB|FZRM99Soau|iLqJg4yWrX

Knowing a little how these work I intuitively was thinking about (2) but I guess someone could expect (1).

(1) seems not feasible performance-wise to me, as it would require each repeat to basically become its own item to be ordered separately (thus in case of items' different materials more batching breaking etc.; way costlier/slower).

(2) should be easy to achieve. Actually it already works in some cases. :upside_down_face:

Also given it's questionable whether it has a use case I'd

> I tried it on the master branch and it seems to remove all repeats due to `_cull_canvas_item()` using a completely different culling approach when y-sorting and (from the look of it) removing all parent/child relationships...

I've looked into the repeating code and main issue is that for all y-sorted items `_cull_canvas_item()` is called with `repeat_size` and `repeat_times` of the y-sorted subtree's root item. While y-sorted repeat source items (`repeat_source == true`) will override these for themselves, their original children won't get such values. And that's pretty much all what's preventing (2) from just working.

Meaning it already works e.g. if Parallax2D is the first y-sorted node (the root of the y-sorted subtree) and there are no nested Parallax2Ds involved etc.

In v4.3.beta1.official [a4f2ea91a]:

Godot_v4 3-beta1_win64_FNPIqs7Gyk|53JutCf33X
-|-

Fixing it would be pretty much the same as what's done in this PR, aka it's a matter of propagating proper `repeat_size` and `repeat_times` when preparing y-sorting, and skip the current code determining these in case we're dealing with an already y-sorted item.

There are some other little issues with the repeating I can see in code, but it's offtopic here.

In general I dislike how now things need to be duplicated codewise to be done before y-sorting, so I'm thinking `_cull_canvas_item` should likely be splitted / refactored a little, but this I consider as for after 4.3. But again, out of scope of this PR, it was meant to be asimple fix. :upside_down_face:

**Comment by markdibarry** [comment]
@kleonc Thanks for the advice! Made an issue and PR here: #93182

**Comment by kleonc** [comment]
Rebased (#93182 was merged).

**Comment by akien-mga** [comment]
Needs a rebase, and then an approval would be great :)

**Comment by kleonc** [comment]
Rebased (pretty much no changes compared to the pre-rebase version).

File: servers/rendering/renderer_canvas_cull.cpp [hunk 1]
```diff
@@ -79,45 +79,71 @@ void RendererCanvasCull::_render_canvas_item_tree(RID p_to_render_target, Canvas
...
-					abs_z = CLAMP(p_z + child_items[i]->z_index, RS::CANVAS_ITEM_Z_MIN, RS::CANVAS_ITEM_Z_MAX);
-				} else {
-					abs_z = child_items[i]->z_index;
-				}
+			if (snapping_2d_transforms_to_pixel) {
+				child_xform.columns[2] = child_xform.columns[2].round();
+			}
+
+			r_items[r_index] = child_items[i];
+			child_items[i]->ysort_xform = p_canvas_item->ysort_xform * child_xform;
```
Comment (rburing) [inline servers/rendering/renderer_canvas_cull.cpp:102]: I think the original code was intentionally only doing a `Transform2D * Vector2` (only transforming the origin) to save doing some unnecessary operations, so I think that should be restored if possible.

**Review by rburing — CHANGES_REQUESTED** [review]

**Comment by rburing** [comment]
Besides the above comment the code looks fine to me.

File: servers/rendering/renderer_canvas_cull.cpp (hunk 1 above)
Comment (kleonc) [reply servers/rendering/renderer_canvas_cull.cpp:102]: Originally the same calculation was done when calling `_collect_ysort_children` (original line 114). So it's not a new additional calculation, it was already present before and was only moved to be performed here. Because of that (and slightly different interpretation of the stored transform; mentioned in the PR description) now such transform is no longer needed to be passed to `_collect_ysort_children`, and the mentioned `Transform2D * Vector2` is not needed as well as the equivalent is already stored as `ysort_xform.origin`.

**Review by rburing — APPROVED** [review]

**Comment by lawnjelly** [comment]
Am happy that @rburing has checked properly, I've had a little look through and it looked fine but I didn't follow it completely. :grin:

**Comment by Repiteo** [comment]
Thanks!

**Comment by KeyboardDanni** [comment]
Hmm, this change replaces the `floor + 0.5` math with `round`, basically undoing #93740. Was this intended?

**Comment by kleonc** [comment]
> Hmm, this change replaces the `floor + 0.5` math with `round`, basically undoing #93740. Was this intended?

Absolutely not. It was like that originally and I must have overlooked this while rebasing, my bad. Thanks for spotting it out!

**Comment by kleonc** [comment]
Note: if/when cherry-picking, should be done together with #98195.
