### PR TITLE
Fixed viewport node error on editor

### LINKED ISSUE #12781: ViewportTexture errors when loading a scene.
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Window 10 64bit - Godot 3.0 9a78efc7c

**Issue description:**
When a scene is opened with a Viewport and a Sprite that uses the ViewportTexture, these errors show up. `Node not found: Viewport` and `ViewportTexture: Path to node is invalid`. The other error about `There is another space` I think is related to the Viewport using "own_world".

Errors

Even though these errors show up, everything still seems to work correctly. The viewport texture still shows up just fine in-game.

**Link to minimal example project:**
[viewport_errors.zip](https://github.com/godotengine/godot/files/1458175/viewport_errors.zip)

### PR DESCRIPTION
**Pull request by AndreaCatania**
Fixed resource setup handling

Fixes #12781

### CODE REVIEW

File: scene/resources/packed_scene.cpp [hunk 1]
```diff
@@ -245,8 +246,8 @@ Node *SceneState::instance(GenEditState p_edit_state) const {
 											value = local_dupe;
 										}
 
-										//this here may reference nodes not iniialized so this line is commented and used after loading all nodes
-										//res->setup_local_to_scene();
+										// Since may be some uninitialized resources that may be required the setup will be done later
```
Comment (reduz) [inline scene/resources/packed_scene.cpp]: would it not be simpler to just put:
```
resources_local_to_scene[res] = res;
```
a few lines above below:

```
res->configure_for_local_scene(base, resources_local_to_scene);

```

**Comment by AndreaCatania** [comment]
@reduz I did it

**Comment by jpate-fortinet** [comment]
Still getting this on 3.0.2 which appears to have that patch applied :(
If I create a sub-scene with a viewport in it, the ViewportTexture keeps getting removed (e.g. when I click 'Save All Scenes')

vptest_notworking
vptest_scene
vptest_rootscene
vptest_working
[viewport_test.zip](https://github.com/godotengine/godot/files/1989270/viewport_test.zip)
