### PR TITLE
Fix avoidance calculation on NO_THREADS build

### LINKED ISSUE #66793: NavigationAgent2D's velocity_computed signal always returns Vector(0, 0) when multiple agents are present (HTML5 only, Desktop works fine)
### Godot version

3.5.1

### System information

Windows 10, GLSE3

### Issue description

When exporting the project to HTML5, the two KinematicBody2D agents don't move. In the desktop version, they move without problems.
The velocity_computed signal always returns Vector(0, 0) when multiple agents are present, but only in the HTML5 version of the project.
When removing one agent, or disabling avoidance and moving them normally, it works in HTML5, too.

I expected it to work in HTML5 just as it works in the desktop version.

### Steps to reproduce

- Create a new Navigation2D Node with a NavigationPolygonInstance.
- Add two or more KinematicBody2D as a child to Navigation2D and give it a NavigationAgent2D with avoidance enabled.
- Add a sprite and collision shape
- Attach a script in which the NavigationAgent2D's velocity_computed function gets connected to a new function move
- The move function has move_and_slide(velocity)
- Set a target location far away and use the agents set_velocity to set the speed according to the agens next location

### Minimal reproduction project

[webtest.zip](https://github.com/godotengine/godot/files/9693867/webtest.zip)

### PR DESCRIPTION
**Pull request by smix8**
Fixes #66793

Adds fallback for avoidance calculation on NO_THREADS builds e.g. HTML5 with no threads enabled.

### CODE REVIEW

File: modules/navigation/nav_map.cpp [hunk 1]
```diff
@@ -698,6 +699,13 @@ void NavMap::step(real_t p_deltatime) {
 				this,
 				&NavMap::compute_single_step,
 				controlled_agents.ptr());
+#endif // !NO_THREADS
+#ifdef NO_THREADS
```
Comment (akien-mga) [inline modules/navigation/nav_map.cpp:703]:
```suggestion
#else
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Might be worth adding a comment in the documentation too, e.g.:
```diff
diff --git a/doc/classes/NavigationAgent.xml b/doc/classes/NavigationAgent.xml
index 5f8eed4619..e4b0f55dbd 100644
--- a/doc/classes/NavigationAgent.xml
+++ b/doc/classes/NavigationAgent.xml
@@ -6,6 +6,7 @@
 	<description>
 		3D agent that is used in navigation to reach a location while avoiding static and dynamic obstacles. The dynamic obstacles are avoided using RVO (Reciprocal Velocity Obstacles) collision avoidance. The agent needs navigation data to work correctly. By default this node will register to the default [World] navigation map. If this node is a child of a [Navigation] node it will register to the navigation map of the navigation node or the function [method set_navigation] can be used to set the navigation node directly. [NavigationAgent] is physics safe.
 		[b]Note:[/b] After [method set_target_location] is used it is required to use the [method get_next_location] function once every physics frame to update the internal path logic of the NavigationAgent. The returned vector position from this function should be used as the next movement position for the agent's parent Node.
+		[b]Note:[/b] By default, the expensive calculations for avoidance are done in a thread. In HTML5 exports without thread support, they will be done on the main thread, which can lead to performance issues.
 	</description>
 	<tutorials>
 	</tutorials>
```

(I don't know if it's the best place for it, and it should be replicated in 2D if it is.)

**Comment by smix8** [comment]
It is 2D and 3D so if added to the docs should be added for both.

**Review by akien-mga — APPROVED** [review]

**Comment by timothyqiu** [comment]
Cherry-picked for 3.5.2
