### PR TITLE
Fix editor crash when middle mouse button is clicked on empty space in scene tabs

### LINKED ISSUE #106123: [4.x] Editor Crashes When Middle Mouse Button Is Clicked on Empty Space in `scene_tabs`
### Tested versions

- Reproducible in v4.5.dev [1a1cc0f7b] Master branch
- Not Reproducible in v4.4.1.stable.official [49a5bc7b6]

### System information

Godot v4.5.dev (1a1cc0f7b) - Windows 11 (build 26100) - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 4050 Laptop GPU (NVIDIA; 32.0.15.7628) - AMD Ryzen 5 7640HS w/ Radeon 760M Graphics (12 threads)

### Issue description

Editor Crashes When Middle Mouse Button Is Clicked on Empty Space in `scene_tabs`

the error:
```
ERROR: FATAL: Index p_index = -1 is out of bounds (size() = 2).
   at: CowData<struct EditorData::EditedScene>::get (D:\Dev\godot\core/templates/cowdata.h:204)
```

### Steps to reproduce

- Open / Create a project
- Click middle mouse button on empty space in `scene_tabs`

### Minimal reproduction project (MRP)

Click middle mouse button on empty space in `scene_tabs` on any project

### PR DESCRIPTION
**Pull request by SaNeOr**
fix #106123

### CODE REVIEW

**Comment by RedMser** [comment]
I wonder if this is the proper fix, or is it just working around the underlying problem?

https://github.com/godotengine/godot/blob/717df3ee883d59ee5df036d95109009f3488b64c/scene/gui/tab_bar.cpp#L201-L212

Tab bar's close button logic explicitly filters out the `-1` index, but the `close_with_middle_mouse` case does not. Maybe it should?

**Comment by SaNeOr** [comment]
> Also some callers to `_scene_tab_closed` have an error check via `ERR_FAIL_COND(tab_idx < 0);` prepended. Maybe that can be moved into where you're currently doing an early return, since the `_scene_tab_closed` method should never be called with negative values.

Indeed, it should be so. I’ve adjusted the fix accordingly.

**Comment by illlustr** [comment]
> Indeed, it should be so. I’ve adjusted the fix accordingly.

Thanks for solving it! I’ve confirmed that [637e3388] indeed fix the issue. However, the overwrite [daff81c8] introduced a problem where I can no longer close tabs in `scene_tabs` using the middle mouse button.

File: scene/gui/tab_bar.cpp [hunk 1]
```diff
@@ -208,7 +208,9 @@ void TabBar::gui_input(const Ref<InputEvent> &p_event) {
 		}
 
 		if (close_with_middle_mouse && mb->is_pressed() && mb->get_button_index() == MouseButton::MIDDLE) {
-			emit_signal(SNAME("tab_close_pressed"), hover);
+			if (cb_hover != -1) {
```
Comment (illlustr) [inline scene/gui/tab_bar.cpp:211]: i think it should be a `hover` instead of `cb_hover`

Comment (illlustr) [reply scene/gui/tab_bar.cpp:211]: it fix the problem i mention earlier

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Review by illlustr — COMMENTED** [review]
🎉
