### PR TITLE
Disconnect TileSet from source editor if no sources

### LINKED ISSUE #60887: Crash when changing tile size after undoing tile atlas addition
### Godot version

1199123

### System information

Windows 10 x64

### Issue description

```
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.0.alpha.custom_build (6b2976188658c674aa9dba099f919ef0ee526a29)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] TileSetAtlasSourceEditor::_update_fix_selected_and_hovered_tiles (C:\godot_source\editor\plugins\tiles\tile_set_atlas_source_editor.cpp:552)
[1] TileSetAtlasSourceEditor::_notification (C:\godot_source\editor\plugins\tiles\tile_set_atlas_source_editor.cpp:2293)
[2] TileSetAtlasSourceEditor::_notificationv (C:\godot_source\editor\plugins\tiles\tile_set_atlas_source_editor.h:43)
[3] Object::notification (C:\godot_source\core\object\object.cpp:849)
[4] SceneTree::_notify_group_pause (C:\godot_source\scene\main\scene_tree.cpp:857)
[5] SceneTree::process (C:\godot_source\scene\main\scene_tree.cpp:454)
[6] Main::iteration (C:\godot_source\main\main.cpp:2745)
[7] OS_Windows::run (C:\godot_source\platform\windows\os_windows.cpp:700)
[8] widechar_main (C:\godot_source\platform\windows\godot_windows.cpp:175)
[9] _main (C:\godot_source\platform\windows\godot_windows.cpp:197)
[10] main (C:\godot_source\platform\windows\godot_windows.cpp:211)
[11] WinMain (C:\godot_source\platform\windows\godot_windows.cpp:225)
[12] __scrt_common_main_seh (D:\a01\_work\26\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[13] BaseThreadInitThunk
-- END OF BACKTRACE --
```

### Steps to reproduce

1. Create Tilemap and Tileset
2. In TileSet editor, add any tile atlas source (just drop any texture in the source list)
3. Undo it
4. In TileSet inspector, edit tile size property.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #60887
Also fixes the errors in https://github.com/godotengine/godot/issues/60887#issuecomment-1120445405

Normally the source editor will edit the tileset when a first source is added. The problem is that it never stops processing the tileset, even if there are no sources anymore. It just keeps happily accessing all the properties it shouldn't be touching. I don't know exactly why the crash was happening, because it was triggered only in specific circumstances, but the errors signalled that something is wrong, even if it appeared to be working.

btw I noticed the source editor does some funky stuff with the sources. TileSetAtlasSource is a Resource but is passed using a pointer and never validated. It's also not added as "do reference" in UndoRedo actions. It's surprisingly stable given all that 🤔

### CODE REVIEW

File: editor/plugins/tiles/tile_set_atlas_source_editor.cpp [hunk 1]
```diff
@@ -2043,6 +2043,13 @@ void TileSetAtlasSourceEditor::_tile_alternatives_control_unscaled_draw() {
 }
 
 void TileSetAtlasSourceEditor::_tile_set_changed() {
+	if (tile_set->get_source_count() == 0) {
+		// No sources, so nothing to do here anymore.
+		tile_set->disconnect("changed", callable_mp(this, &TileSetAtlasSourceEditor::_tile_set_changed));
+		tile_set = nullptr;
```
Comment (akien-mga) [inline editor/plugins/tiles/tile_set_atlas_source_editor.cpp:2049]: Fails build, should like be an empty Ref.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
