### PR TITLE
Fix C# delegate signal not disconnected when Object is destroyed

### LINKED ISSUE #66319: Signal connected through C# delegate does not disconnect when receiver is destroyed
### Godot version

v4.0.beta1.mono.official [4ba934bf3]

### System information

Windows 11 / macOS 12.6

### Issue description

If I connect a node to a signal through a C# EventHandler, it continues to receive that signal even after it has been destroyed, causing undesired behavior (removed nodes shouldn't receive signals) and a System.ObjectDisposedException.

The signal does get properly disconnected if I construct a Callable with the node object and the name of the method.

I originally encountered this bug when changing scenes and handling signals from an autoloaded singleton, but reproducing it is even simpler than that.

### Steps to reproduce

Just build and run the project, and watch the output. Here's the relevant code:
```csharp
using Godot;

public partial class Node1 : Node
{
    public override void _Ready()
    {
        GetTree().ProcessFrame += OnProcessFrame;

        // equivalent to
        // GetTree().Connect("process_frame", new Callable(OnProcessFrame));

        // this works as expected
        // GetTree().Connect("process_frame", new Callable(this, "OnProcessFrame"));
    }

    public void OnProcessFrame()
    {
        GD.Print("node1: received signal");
        QueueFree();
    }
}
```

### Minimal reproduction project

[gd4_signal_bug.zip](https://github.com/godotengine/godot/files/9636900/gd4_signal_bug.zip)

### PR DESCRIPTION
**Pull request by pkdawson**
Fixes #66319

This just implements a TODO comment by neikeq, which helpfully described the solution to a bug I encountered:
https://github.com/godotengine/godot/blob/56563ef09e779b9f4b105fea0e5a1a8e59c7cfe8/modules/mono/managed_callable.cpp#L82

If the delegate target is an Object, the connected signal will be registered in that object instead of the middleman. So when that object is destroyed, the signal will be properly disconnected.

This is quite a simple change, but it needs to touch a lot of files to pass along the additional parameter.

### CODE REVIEW

**Comment by neikeq** [comment]
I'll be reviewing this later, but from a quick look, the delegate target is not necessarily a Godot Object. It can be any type.

**Comment by pkdawson** [comment]
> I'll be reviewing this later, but from a quick look, the delegate target is not necessarily a Godot Object. It can be any type.

Right, that's why I used the "as" operator, so if it's not a Godot.Object the target just becomes null. Then the middleman will still be used.

I did test this with static methods, and methods on non-Object classes, and that still works fine.

**Comment by neikeq** [comment]
My bad, I did not read this well. Can you include this part in the commit message?:

> If the delegate target is an Object, the connected signal will be registered in that object instead of the middleman. So when that object is destroyed, the signal will be properly disconnected.

File: modules/mono/managed_callable.h [hunk 1]
```diff
@@ -66,7 +67,7 @@ class ManagedCallable : public CallableCustom {
 
 	void release_delegate_handle();
 
-	ManagedCallable(GCHandleIntPtr p_delegate_handle);
+	ManagedCallable(GCHandleIntPtr p_delegate_handle, ObjectID p_object);
```
Comment (neikeq) [inline modules/mono/managed_callable.h:70]: For clarity:

```suggestion
	ManagedCallable(GCHandleIntPtr p_delegate_handle, ObjectID p_object_id);
```

Same for all other occurrences in this PR.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/Marshaling.cs [hunk 2]
```diff
@@ -721,8 +721,9 @@ public static godot_callable ConvertCallableToNative(in Callable p_managed_calla
             if (p_managed_callable.Delegate != null)
             {
                 var gcHandle = CustomGCHandle.AllocStrong(p_managed_callable.Delegate);
+                ulong objectId = p_managed_callable.Target?.GetInstanceId() ?? 0;
```
Comment (neikeq) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/Marshaling.cs:724]: For performance, it's better to pass the object pointer to the native function and get the instance id from there:

```suggestion
                IntPtr objectPtr = p_managed_callable.Target != null ? Object.GetPtr(p_managed_callable.Target) : IntPtr.Zero;
```

**Review by neikeq — CHANGES_REQUESTED** [review]

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Callable.cs [hunk 3]
```diff
@@ -72,7 +72,7 @@ public Callable(Object target, StringName method)
         /// <param name="delegate">Delegate method that will be called.</param>
         public Callable(Delegate @delegate)
         {
-            _target = null;
+            _target = @delegate.Target as Object;
```
Comment (kleonc) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Callable.cs:75]: The passed in `@delegate` can be `null`.
```suggestion
            _target = @delegate?.Target as Object;
```

**Review by neikeq — APPROVED** [review]

**Comment by neikeq** [comment]
Thanks!
