### PR TITLE
Fix FileSystem dock won't show any file folders while loading large projects (v2)

### LINKED ISSUE #47053: Large projects seem frozen/crashed for several minutes on startup with poor editor feedback
**Godot version:**
v3.2.4.rc4.official
v4.x vulkan

**OS/device including version:**
Win10 64x

**Issue description:**
The editor seems to have a real struggle with very large Godot projects (50+ gb) ones per day on first startup.
I just clocked, the editor appears completely frozen/crashed for 7+ minutes on startup.

There is no feedback in both editor or console for users what is going on after the class_names and autoload scripts are successfully loaded.

There seems to be an issue with the file scanthread implementation. It seems the file scanthread has the desire to not only read all scriptfiles for changes but also open every single file each new day for no practical reason. As long as the scanthread is busy it blocks the entire editor until finished instead of working behind the scene.

The result is that the project appears nearly empty in the editor for a long time (shock moment, where are my files?) and also the editor stays unresponsive for several minutes as if it had a crash.

**How to solve?**

- Give continues, visual feedback to user about project load progress.
- Make file scanthread behave like a real, subtle background thread and not a nuisance by blocking editor startup until finished.
- Stop scanthread from opening all unchanged and very large asset files each day for no apparent, practical reason.

**Steps to reproduce:**
Create large Godot projects

**Minimal reproduction project:**
project size issue

### LINKED ISSUE #85082: When loading a project, the editor shows an empty scene before actually showing the last edited scene
### Godot version

4.2 beta5, beta6 and rc1

### System information

Windows 10 - Vulkan (Forward+) - RTX 3060 laptop - AMD Ryzen 5 5600H - 24GB RAM

### Issue description

Every time a project is loaded, after the boot splash, an empty scene like the one below appears:

image

After some time, the last edited scene is finally shown as expected.

I took the time to see after which version this occurs and I concluded that **this glitch is only present in 4.2 beta5, beta6 and rc1**. Godot 4.2beta4 and before works as expected

### Steps to reproduce

Just open a project with at least one saved scene. If the scene takes time to load, the glitch is more noticeable

### Minimal reproduction project

[glitchBlankScene.zip](https://github.com/godotengine/godot/files/13403038/glitchBlankScene.zip)

Just a simple scene with some high-poly count CSGMesh3D to make loading time big.  I didn't delete the .godot folder because that doesn't make Godot load the last edited scene. Anyway you can delete the .godot folder yourself and reopen the project a second time to see the glitch

### LINKED ISSUE #92335: FileSystem dock won't show any file / folders, and has performance issues when loading large folders
### Tested versions

Tested in 4.2.2 stable, 4.3 beta 5, 4.3 beta 6.

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.5186) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

I tried loading this sprite database : https://github.com/PMDCollab/SpriteCollab/tree/master/sprite
It's around ~1Go of .png (1025 pokemons + shinies, all in pixel art), saved in 1025 folders.

Here's the exhaustive list of what I encountered while trying to import that across three versions:
- It took any version tested 10+ minutes to import everything
- IF the import is successful, I need to Alt+F4 / task manager to exit godot
- While open, the editor seems to run fine. I can create empty new scenes, save, load and play them.
- I don't see any file nor folder in the FileSystem Dock, but I see them using the load window.

image
image

- Reloading the whole project fixes this last issue, but takes 10+ minutes of reimport and I need to do that every time I open godot.
- Alternatively, creating a folder will trigger a scan (taking again ~10min) and it will fix the problem, until you need to close / reopen the engine

image

- When the issue is fixed after reimporting, the filesystem dock will lag & jitter, making it hard to use
---

**Expected behaviour :** 
- Load the big folder (takes some time to import, but should be less than 10 minutes)
- After import, all the files can be seen in the filesystem dock without decreased performance
- We can close the engine whithout relying on task manager

### Steps to reproduce

- Create an empty project
- Try to import the sprite folder from provided link : https://github.com/PMDCollab/SpriteCollab/tree/master/sprite
- If successful, either godot will crash, or you won't be able to see the folder architecture after import
- If that's not the case, close godot and reopen it : all the folders should be gone from the filesystem dock

### Minimal reproduction project (MRP)

I can't upload the project here, as it weight too much.
It's an empty project with just the mentioned file above, no scripts, no editor settings, no scenes.

### PR DESCRIPTION
**Pull request by Hilderin**
Fixes #92335, Fixes #47053 and Fixes #85082
This is a new PR for the reverted PR #92650.

This PR improves:
- FileSystem Dock not showing progress bar on first file scanning
- Better progression (%) for scanning large projects with a lot of folders and files
- Performance optimization on scanning project files for large projects
- Add progression popup for _update_scan_actions step (instead of Editor freeze)
- Add progression popup for _update_script_classes step (instead of Editor freeze)
- Add progression popup for loading editor layout and reopening scenes (instead of Editor freeze)

I tested these modifications with a project having all the files from https://github.com/PMDCollab/SpriteCollab/tree/master/sprite (more than 125000 files and 385Mb).

Before:
FileSystem was empty without any feedback for a couple of minutes and after that the editor was just frozen:

image

After modifications:
image
image

**Performance optimization on project scanning before asset importation**
For a 30000 files project, it took around 2m50s on startup to scan the project.
After a couple of optimizations, it now takes 1m30s for the same project.

Before:
image

After:
image

Causes:
- The FileAccess:exists was calling the open method which has a couple of overhead over file_exists.
- The _scan_new_dir was double sorting the folders.
- The reimport_files was recalculating the import_groupe_file even if _update_scan_actions did that just before.

### CODE REVIEW

File: editor/editor_file_system.cpp [hunk 1]
```diff
@@ -749,28 +769,50 @@ void EditorFileSystem::scan() {
...
+	}
+
+	float old_estimated = estimated;
+	estimated = real + nb_file_to_scan + (nb_dir_to_scan * average * p_depth);
+	if (estimated < old_estimated * 0.95) {
+		estimated = old_estimated * 0.95;
+	}
+	if (estimated <= real + average) {
+		estimated = real + average;
+	}
```
Comment (RandomShaper) [inline editor/editor_file_system.cpp:812]:
```suggestion
	float min_estimated = MAX(old_estimated * 0.95f, real + average);
	float new_estimated = real + nb_file_to_scan + (nb_dir_to_scan * average * p_depth);
	estimated = MAX(min_estimated, new_estimated);
```

Please double-check the logic is equivalent, though.

File: editor/editor_file_system.cpp [hunk 2]
```diff
@@ -749,28 +769,50 @@ void EditorFileSystem::scan() {
...
 }
 
-void EditorFileSystem::ScanProgress::update(int p_current, int p_total) const {
-	float ratio = low + ((hi - low) / p_total) * p_current;
-	progress->step(ratio * 1000);
-	EditorFileSystem::singleton->scan_total = ratio;
+void EditorFileSystem::ScanProgress::increment() {
+	real++;
+	nb_file_to_scan--;
+	current = CLAMP(real / estimated, current, 1);
```
Comment (RandomShaper) [inline editor/editor_file_system.cpp:781]:
```suggestion
	current = CLAMP(real / estimated, current, 1.0f);
```

File: editor/editor_file_system.cpp [hunk 3]
```diff
@@ -749,28 +769,50 @@ void EditorFileSystem::scan() {
...
-	ScanProgress sp = *this;
-	float slice = (sp.hi - sp.low) / p_total;
-	sp.low += slice * p_current;
-	sp.hi = slice;
-	return sp;
+void EditorFileSystem::ScanProgress::update_estimated(int p_depth, int p_nb_sub_dirs, int p_nb_files) {
+	// The algorithm calculates an estimated value for the progress of scanning directories and files.
+	// It adjusts the estimate based on the number of directories and files discovered so far,
+	// and ensures the estimated value does not decrease drastically between updates.
+	float average = 10;
```
Comment (RandomShaper) [inline editor/editor_file_system.cpp:790]:
```suggestion
```

File: editor/editor_file_system.cpp [hunk 4]
```diff
@@ -749,28 +769,50 @@ void EditorFileSystem::scan() {
...
+		nb_dir_to_scan--;
+	}
+	nb_dir_to_scan += p_nb_sub_dirs;
+	nb_file_to_scan += p_nb_files;
+
+	if (directories_processed > 2) {
+		average = (real + nb_file_to_scan) / directories_processed;
+		if (average < 10) {
+			average = 10;
+		}
```
Comment (RandomShaper) [inline editor/editor_file_system.cpp:802]:
```suggestion
	float average = 10.0f;
	if (directories_processed > 2) {
		average = MAX(average, (real + nb_file_to_scan) / directories_processed);
```

File: editor/editor_node.cpp [hunk 5]
```diff
@@ -5124,11 +5126,19 @@ void EditorNode::_load_editor_layout() {
...
+	ep.step("Reopening scenes...", 2, true);
 	_load_open_scenes_from_config(config);
+
+	ep.step("Loading central editor layout...", 3, true);
 	_load_central_editor_layout_from_config(config);
 
+	ep.step("Loading plugin window layout...", 4, true);
 	editor_data.set_plugin_window_layout(config);
+
+	ep.step("Editor layout ready.", 5, true);
```
Comment (Chaosus) [inline editor/editor_node.cpp:5141]:
```suggestion
	ep.step(TTR("Loading docks..."), 1, true);
	editor_dock_manager->load_docks_from_config(config, "docks");

	ep.step(TTR("Reopening scenes..."), 2, true);
	_load_open_scenes_from_config(config);

	ep.step(TTR("Loading central editor layout..."), 3, true);
	_load_central_editor_layout_from_config(config);

	ep.step(TTR("Loading plugin window layout..."), 4, true);
	editor_data.set_plugin_window_layout(config);

	ep.step(TTR("Editor layout ready."), 5, true);
```

File: editor/editor_file_system.cpp (hunk 1 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp]: Yes, it seems to be equivalent. Done!

**Comment by Hilderin** [comment]
All the correction should be done. Thanks for the review.

File: editor/editor_node.cpp [hunk 6]
```diff
@@ -5103,6 +5103,8 @@ void EditorNode::save_editor_layout_delayed() {
 }
 
 void EditorNode::_load_editor_layout() {
+	EditorProgress ep("loading_editor_layout", TTR("Loading editor"), 5);
+	ep.step("Loading editor layout...", 0, true);
```
Comment (Chaosus) [inline editor/editor_node.cpp:5107]:
```suggestion
	ep.step(TTR("Loading editor layout..."), 0, true);
```

Comment (Hilderin) [reply editor/editor_node.cpp]: done!

**Comment by Hilderin** [comment]
I think it's important to note that some issues that this PR fixes have also been addressed by #92303, but in a different way. I suggest merging #92303 before this one, and then I will rebase and adjust this PR.

**Comment by Hilderin** [comment]
I rebased from master and reworked this PR.

With the modifications from #92303, I was able to simply this PR a lot. It's now almost only adding `EditorProgress` at different places during first startup and importation process.

I also kept some optimizations like the `FileAccess::exists`, `ResourceFormatImporter::get_resource_import_info` and `ResourceLoader::_path_remap`.

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` https://github.com/godotengine/godot/commit/97b8ad1af0f2b4a216f6f1263bef4fbc69e56c7b) on various official demos, it works as expected. The `--import` command line argument still works correctly too.

Code looks good to me.

**Comment by Hilderin** [comment]
Rebased to fix conflict with master.

File: core/io/file_access.cpp [hunk 7]
```diff
@@ -59,11 +59,9 @@ bool FileAccess::exists(const String &p_name) {
 		return true;
 	}
 
-	Ref<FileAccess> f = open(p_name, READ);
-	if (f.is_null()) {
-		return false;
-	}
-	return true;
+	// Using file_exists because it's faster then trying to open the file.
```
Comment (akien-mga) [inline core/io/file_access.cpp:62]:
```suggestion
	// Using file_exists because it's faster than trying to open the file.
```

File: core/io/resource_loader.cpp [hunk 8]
```diff
@@ -1060,36 +1060,39 @@ String ResourceLoader::_path_remap(const String &p_path, bool *r_translation_rem
...
-				next_tag.name = String();
-
-				err = VariantParser::parse_tag_assign_eof(&stream, lines, error_text, next_tag, assign, value, nullptr, true);
-				if (err == ERR_FILE_EOF) {
-					break;
-				} else if (err != OK) {
-					ERR_PRINT("Parse error: " + p_path + ".remap:" + itos(lines) + " error: " + error_text + ".");
-					break;
-				}
+		// Usually, there's no remap file and FileAccess::exists() is faster then FileAccess::open().
```
Comment (akien-mga) [inline core/io/resource_loader.cpp:1063]:
```suggestion
		// Usually, there's no remap file and FileAccess::exists() is faster than FileAccess::open().
```

**Comment by akien-mga** [comment]
I'll try to test it a bit next week, but this should be ready for a merge soon.

File: core/io/resource_loader.cpp (hunk 8 above)
Comment (Hilderin) [reply core/io/resource_loader.cpp]: Done!

File: core/io/file_access.cpp (hunk 7 above)
Comment (Hilderin) [reply core/io/file_access.cpp]: Done!

**Comment by Saul2022** [comment]
Testing on  https://github.com/PMDCollab/SpriteCollab/tree/master now without the pr that heavily improves initial anlysis  before scanning files dialog, because of curiosity to see what's going on. 

Initial transition from godot logo to editor scan( over 15 minutes( luckily with the load project pr is down to 1:30 or 3 minutes, so i thank that.).

Then on godot scan, update action and preparing for import dialog 11:30 minutes. Though on preparing for import it gets stuck at 99% which seems to still freeze with no additional progress bar, and atm it still going now with over 12  minutes and still going 

Aside from this something i thought could be done in the godot dialog, which i would guess it might freeze too after the circle wheel dissapears , is make it have a progress bar that says what it doing, because it pretty weird how the editor gets staring  without seeing  anything going on, which might make people thing it got frozen..

**Comment by Hilderin** [comment]
Wow, thank you to have tested it, I found why it's stuck before the reimportation. All the resources must pass in `EditorNode::_resources_reimporting` and `EditorNode::_resources_reimported` and for each one `ResourceLoader::get_resource_type(res_path)` is called forcing to open the asset file a couple of times each. I did another modification to optimize this process by using the resource type already calculated in `EditorFileSystem` and I added another progress step while doing in.

Time on reimporting and reimported (each):
Before: 90sec
After: 8sec

**Comment by Hilderin** [comment]
> Aside from this something i thought could be done in the godot dialog, which i would guess it might freeze too after the circle wheel dissapears , is make it have a progress bar that says what it doing, because it pretty weird how the editor gets staring without seeing anything going on, which might make people think it got frozen.

Are you speaking about the Godot splash screen at startup? If I understand correctly you suggest to add a progress bar here?
image

**Comment by Saul2022** [comment]
>  If I understand correctly you suggest to add a progress bar here?

 Yea, as there's no visual indication to the user , of whats going on , like staying 1:30 minutes staring at the godot logo, without knowing what's going on , might make people think it got frozen.

**Comment by Hilderin** [comment]
Thanks again for all your benchmarks, very appreciated.

> Yea, as there's no visual indication to the user , of whats going on , like staying 1:30 minutes staring at the godot logo, without knowing what's going on , might make people think it got frozen.

It's challenging technically to add a progress bar on the logo splash screen, but, I added another progress popup while executing the first scan. That way, the splash screen will disappear sooner when the first scan starts and as a bonus, I added steps in the progress bar for the creation of autoload scripts and plugins which could take a while if you have a lot of autoloads or plugins.

> though in general what would be the general speed improvement on all the asset reimport/reimported after the preparing import dialog is done ( like what you tested with the sprites of your linked project)?

This optimization should affect all asset types. When reimporting a small number of assets, the difference will be minimal, but in large quantity, removing the need to read the asset should improve performance in the same magnitude for any kind of asset. Still better, I just pushed another little modification and I was able to cut the processing time in `EditorNode::_resources_reimported` just by caching the resource types calculated in `EditorNode::_resources_reimporting`.

> Atp what is just left to do would be fix the cache thing as Juan suggested, and maybe cache the scenes that were opened before closing., as they only seem to be cached upon switching scenes, so when opening they load way faster.

I'm working on it.

**Comment by Calinou** [comment]
> It's challenging technically to add a progress bar on the logo splash screen

We could display a loading percentage in the window title, but it'll be missed by those having the editor in fullscreen while the editor is loading (which is unlikely).

**Comment by Hilderin** [comment]
> We could display a loading percentage in the window title, but it'll be missed by those having the editor in fullscreen while the editor is loading (which is unlikely).

That could be a brilliant idea!! Right now, I added a `EditorProgress` in `_first_scan_filesystem` which should do the trick. Also, on Android the window title is not displayed :(

**Comment by Saul2022** [comment]
>. Also, on Android the window title is not displayed :(

That  is weird  , if you mean your project like how it appears at the bottom left on windows, ut normal for it to not appear on android.

Else if you mean godot engine logo it there 
Screenshot_20240821_040002

Either way this changes are really appreciated , so thank you for this amazing job.

**Comment by Hilderin** [comment]
I think Calinou was referring to the window title bar that we have on desktop:
image

**Comment by Saul2022** [comment]
Final update on it  17: mins for initial scan , 6 minutes for scan, 7 for action scans, then 4 on preimport preratation , 6  for exectuting reimport precess and 2 hours for reimport to get to 50%  using  sprite collab whole project.  
 
Some notes( though this is for a future pr, as this  one is pretty well as it is, and is not a regression of 4.3) : i think this is now pretty much  max speed this can get though maybe for some stuff like action scan  or reimport could use some improvements like as the pngs reimport  is instant, i think  what is limiting here is that it going over 1 by 1    like you reimported this image now? Ok then go for the next one ,add up to that , that this files are just some kb ( not even getting to 1 mbs )..and the burden here being that there are tons and tons of them and while the import of each is instant, having so many  and just importing one at a time instead of say 10 and then  pass over to other ten and go on until import is over. It pretty confusing like this so i might create a issue later, though this  might pretty much affect models too., or i might get too crazy and is just that  multi threading  bug or lack of it for import.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
