### PR TITLE
Prioritize points in polygon editor hover

### LINKED ISSUE #34600: it's  not possible to select a point on line.
**Godot version:**
3.1.2

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**
1.add a Line2D
2.draw some points
Screen Shot 2019-12-28 at 7 13 12 PM
3. drag point 3 onto the line
Screen Shot 2019-12-28 at 7 13 31 PM
4. now, it's impossible to select point 3
Screen Shot 2019-12-28 at 7 14 01 PM

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #34600

https://github.com/godotengine/godot/assets/2223172/2d710c13-8d88-4f52-8a76-4fbf71fc3c4a

### CODE REVIEW

**Comment by fire** [comment]
I like the feature, but haven't reviewed the "Prioritize points in polygon editor hover" code yet.

**Review by akien-mga — APPROVED** [review]
Seems ok from a glance.

File: editor/plugins/abstract_polygon_2d_editor.cpp [hunk 1]
```diff
@@ -437,24 +434,28 @@ bool AbstractPolygon2DEditor::forward_gui_input(const Ref<InputEvent> &p_event)
...
-					canvas_item_editor->update_viewport();
-				}
+			}
 
-				const PosVertex new_hover_point = closest_point(gpoint);
-				if (hover_point != new_hover_point) {
-					hover_point = new_hover_point;
+			bool edge_hover = false;
+			if (!hover_point.valid()) {
+				const PosVertex onEdgeVertex = closest_edge_point(gpoint);
```
Comment (AThousandShips) [inline editor/plugins/abstract_polygon_2d_editor.cpp:445]: Do we want to fix the naming of this while were here?

Comment (akien-mga) [reply editor/plugins/abstract_polygon_2d_editor.cpp:445]: Usually I'd say no as it would make the diff needlessly hard to compare, but here it seems to be the only occurrence of camelCase in surrounding code, so might be worth fixing yeah.

**Comment by akien-mga** [comment]
Thanks!
