### PR TITLE
Fix `display_placeholder` not persisting

### LINKED ISSUE #110673: TileMapLayer, TileSet display_placeholder are not working
### Tested versions

Godot v4.5.stable (876b29033) - Windows 10 (build 19045) - Multi-window, 1 monitor - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 2060 SUPER (NVIDIA; 32.0.15.7216) - Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz (8 threads) - 15.85 ГиБ memory

### System information

Godot v4.5.stable (876b29033) - Windows 10 (build 19045) - Multi-window, 1 monitor - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 2060 SUPER (NVIDIA; 32.0.15.7216) - Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz (8 threads) - 15.85 ГиБ memory

### Issue description

After restarting the project, display_placeholder switches true to false.
Is this the expected behavior? The scene has nodes, but they are all transparent, I can't see anything, this marker helps me, but it's sad that it resets after exiting

### Steps to reproduce

1) display_placeholder = true. (manually, not a code)
2) restart project.
It works with a TileSet saved on disk and without saving

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #110673

### CODE REVIEW

File: scene/resources/2d/tile_set.cpp [hunk 1]
```diff
@@ -5882,6 +5882,7 @@ bool TileSetScenesCollectionSource::_set(const StringName &p_name, const Variant
 			if (!has_scene_tile_id(scene_id)) {
 				create_scene_tile(p_value, scene_id);
```
Comment (kleonc) [inline scene/resources/2d/tile_set.cpp]:
```suggestion
				create_scene_tile(Ref<PackedScene>(), scene_id);
```

**Review by kleonc — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
