### PR TITLE
Fix SoftDynamicBody3D normals

### LINKED ISSUE #56541: SoftDynamicBody3D's surface is flickering
### Godot version

4.0.dev (2c7fcdd7f94307a8dbf9436edc3294aaa6f87a88)

### System information

linuxbsd,Vulkan

### Issue description

For old version, the format of normal is 3*float, for 4.0 the format is A2B10G10R10. The problem is that, for SoftDynamicBody3D, the code is still based on the old version vertex format.

In function SoftDynamicBodyRenderingServerHandler::set_normal(int p_vertex_id, const void *p_vector3), 
about this line: memcpy(&write_buffer[p_vertex_id * stride + offset_normal], p_vector3, sizeof(float) * 3);
I found that the normal data is only 4 byte (uint_32), not 3*4 byte (3*float). So, the correct one is:
memcpy(&write_buffer[p_vertex_id * stride + offset_normal], p_vector3, sizeof(uint32_t));

And the place where function set_normal is called should also be fixed.

### Steps to reproduce

Just create a SoftDynamicBody3D, (In my case, I used a plane mesh). Add a light and camera. Make SoftDynamicBody3D touching something, in order to make it uneven.
Run the scene, you will find the surface of SoftDynamicBody3D flicking, due to the normals are changing with high frequency.

### Minimal reproduction project

[demo.zip](https://github.com/godotengine/godot/files/7818859/demo.zip)

### PR DESCRIPTION
**Pull request by rburing**
Fixes https://github.com/godotengine/godot/issues/56541.

softbody_normals_before+after

### CODE REVIEW

**Review by reduz — APPROVED** [review]

File: scene/3d/soft_dynamic_body_3d.cpp [hunk 1]
```diff
@@ -83,7 +83,15 @@ void SoftDynamicBodyRenderingServerHandler::set_vertex(int p_vertex_id, const vo
...
+	Vector3 n;
+	memcpy(&n, p_vector3, sizeof(Vector3));
+	n *= Vector3(0.5, 0.5, 0.5);
+	n += Vector3(0.5, 0.5, 0.5);
+	uint32_t value = 0;
+	value |= CLAMP(int(n.x * 1023.0), 0, 1023);
+	value |= CLAMP(int(n.y * 1023.0), 0, 1023) << 10;
+	value |= CLAMP(int(n.z * 1023.0), 0, 1023) << 20;
+	memcpy(&write_buffer[p_vertex_id * stride + offset_normal], &value, sizeof(uint32_t));
 }
```
Comment (Calinou) [inline scene/3d/soft_dynamic_body_3d.cpp:95]: That code seems pretty cryptic, maybe it should have some comments?

**Review by Calinou — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
