### PR TITLE
[3.x] Fix race condition on `script_binding` in C#

### LINKED ISSUE #37652: Memory allocator crashes or spews infamous _set_color error
**Godot version:** v3.2.1.stable.mono.official (64 bit)

**OS/device including version:** Windows 10 Home N (10.0.18362 Build 18362)

**Issue description:** The underlying custom allocator in Godot is having trouble with high-frequency allocations. I believe this is due to a race condition in `core/map.h`. Given a high frequency of allocs/deallocs (bound by a cap, see reproduction project) the allocator fails and the process either crashes or spews this infamous error:
> ERROR: _set_color: Condition "p_node == _data._nil && p_color == RED" is true.
> At: ./core/map.h:154

I say _infamous_ because there are few similar bug reports surrounding this evasive error, all of which involve a multi-threaded physics server. In the reproduction project linked below, you'll find my replication of this bug **without** any multi-threaded physics server.

Related & not duplicate:
https://github.com/godotengine/godot/issues/8630
https://github.com/godotengine/godot/issues/6512

**Steps to reproduce:**
1: (Recommended) Disable vsync to show greater discrepancy among idle_frame, _Process, and _PhysicsProcess. If vsync is enabled, the bug will take longer to reproduce.
2: Create a queue of thousands of object references, managed by Godot's custom allocator
3: Repeatedly dequeue old references and enqueue new references using any of Godot's life-cycle functions (fastest reproduction is in the idle frame, vsync disabled)
4: If you are using the idle frame (with vsync disabled), reproducing should only take a few seconds. View the logger to witness a crash or spewing of the infamous error. If you are using _Process or _PhysicsProcess, it may take a couple minutes, but the crash/spew always occurs.
5: (Optional): Build from source, set a breakpoint on map.h:154 and run the project. Assuming there is no crash, wait for the errors to spew. Once the spewing starts, attach the debugger and analyze the params. Look for condition `p_node == _data._nil && p_color == RED`, and check that it is truthy. If it is truthy, repeatedly step over, and you should see the "Finalizer" thread is stuck in an infinite loop as it attempts to balance the RB-Tree in `map.h`.

**Minimal reproduction project:** 
[reproduction-project.zip](https://github.com/godotengine/godot/files/4442831/reproduction-project.zip)

### PR DESCRIPTION
**Pull request by omegachysis**
I believe this simple change fixes #37652 by fixing a race condition on `script_bindings`. I have a version of this change for `master` but I can't reproduce the issue in 4.0 so I think something else was changed that covers the issue up; that's why I'm opening this as 3.2-specific. I'm hoping someone with more knowledge about this can tell if this should also have a lock in v4.0. I suspect it would still be a problem in 4.0 to allocate C# wrapper objects from multiple threads at once without this lock, but I haven't verified that.

### CODE REVIEW

**Comment by Chaosus** [comment]
Please, follow our rules and merge all commits into one:  https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request Thanks!

**Comment by omegachysis** [comment]
> Please, follow our rules and merge all commits into one: https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request Thanks!

Have no idea why a one line change became three commits, oops. Should be one now.

**Review by neikeq — CHANGES_REQUESTED** [review]
The caller should be the one that locks before it reads, creates and inserts the binding, so instead the lock should be added here in `GDMonoInternals::tie_managed_to_unmanaged`:

https://github.com/godotengine/godot/blob/0a54dcb54f7e7855c7eb0b63b3cccf5d9d0251ea/modules/mono/mono_gd/gd_mono_internals.cpp#L71

**Comment by timothyparez** [comment]
What's preventing this from getting merged?
Because this is a showstopper.

**Comment by omegachysis** [comment]
> What's preventing this from getting merged?
> Because this is a showstopper.

I've had other commitments and I haven't been able to find out the right way to move the scoped mutex. @neikeq indicates the mutex needs to be locked by the calling function instead, but I doubt the `language_bind_mutex` is exposed to `GDMonoInternals` so it needs to be added as a friend class, or the mutex needs to be extracted completely out. Hoping someone more familiar with these details knows the right way to do it. I doubt this is the only race condition in the C# script instancing system.

**Comment by timothyparez** [comment]
@omegachysis I honestly don't know anything about this stuff, sorry.
The only thing I know is that without this my app crashes after a few minutes while with it
it ran for 48 hours without end. But from what you've said it seems like there's much more to it.

Thnx for the quick reply!

**Comment by timothyparez** [comment]
I have to ask, because right now I'm stuck between a rock and a hard place,
is there anything I can do to prevent these race conditions in 3.2.3?

- I have a gdscript version of my app which leaks memory
- I have a csharp version which does not leak memory but crashes because of this issue
- I cannot build a custom version because `godot-mono-builds` fails to build

**Comment by swift502** [comment]
Just encountered this error as well. If it was beneficial, I volunteer to test if these commits solve the issue.

**Comment by neikeq** [comment]
This is still pending my requested change. Putting the scoped lock in the line I linked instead of inside the method should be enough:
https://github.com/godotengine/godot/blob/0a54dcb54f7e7855c7eb0b63b3cccf5d9d0251ea/modules/mono/mono_gd/gd_mono_internals.cpp#L71

**Comment by omegachysis** [comment]
@neikeq I'll have this in pretty soon, I just defended a thesis and had some other life events that have gotten in the way. I'll have time to set my environment up again to make these changes and get them in.

**Comment by neikeq** [comment]
Sure, no hurries. I commented again because I was re-requested a review so I thought there could have been a confusion.

**Comment by omegachysis** [comment]
@neikeq Should be done now. I haven't tested this with the latest version of 3.x since my branch is a bit out of date. I tested it with the state of Godot when this was originally raised and it still works there.

**Review by neikeq — APPROVED** [review]

**Comment by akien-mga** [comment]
There are some style issues: https://github.com/godotengine/godot/pull/43889/checks?check_run_id=2161611504

And it doesn't build, it's based on a too old `3.2` branch which is not compatible with current `3.x` / upcoming Godot 3.3.

**Comment by omegachysis** [comment]
> There are some style issues: https://github.com/godotengine/godot/pull/43889/checks?check_run_id=2161611504
> 
> And it doesn't build, it's based on a too old `3.2` branch which is not compatible with current `3.x` / upcoming Godot 3.3.

Done, please ignore the 3.2 base branch name on my fork, this is integrated with 3.x now. Thank you for bringing the issues to my attention

File: modules/mono/mono_gd/gd_mono_internals.cpp [hunk 1]
```diff
@@ -30,6 +30,8 @@
 
 #include "gd_mono_internals.h"
 
+#include "core/os/os.h"
+
```
Comment (akien-mga) [inline modules/mono/mono_gd/gd_mono_internals.cpp:34]: I guess this include is no longer needed?

Comment (omegachysis) [reply modules/mono/mono_gd/gd_mono_internals.cpp]: Apparently not! It's removed now.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada: 

Could you do the matching PR for `master`? The Mutex code is similar there so it likely needs the same change.

**Comment by swift502** [comment]
It works! No more crashing with 3.3 rc7. Thanks a lot @omegachysis 🙏.
