### PR TITLE
Fix tooltip message of button that opens groups/signals dock

### LINKED ISSUE #97681: Wrong message on the Groups Icon in the Scene View
### Tested versions

The Icon next to the Node if it is in some sort of group says `Click to show signals dock` instead of `Click to show groups dock`

image

### System information

Linux Mint Cinnamon 21.3

### Issue description

The Icon next to the Node if it is in some sort of group says `Click to show signals dock` instead of `Click to show groups dock`

image

It could be a bit misleading cause clicking the icon takes to the group dock instead of the signals dock. It says otherwise.

### Steps to reproduce

Add a node to the scene tree.

Add a group to the node.

Hover on the group icon that appears

### Minimal reproduction project (MRP)

None

### PR DESCRIPTION
**Pull request by ghost**
Fixes #97681

### CODE REVIEW

File: editor/gui/scene_tree_editor.cpp [hunk 1]
```diff
@@ -369,26 +369,26 @@ void SceneTreeEditor::_add_nodes(Node *p_node, TreeItem *p_parent) {
...
-				msg_temp += "\n";
-			}
-			msg_temp += TTR("Click to show signals dock.");
+		} else {
+			msg_temp += "\n";
 		}
 
 		Ref<Texture2D> icon_temp;
 		SceneTreeEditorButton signal_temp = BUTTON_SIGNALS;
+		auto msg_temp_ = TTR("Click to show signals dock.");
```
Comment (AThousandShips) [inline editor/gui/scene_tree_editor.cpp:378]:
```suggestion
		String msg_temp_end = TTR("Click to show signals dock.");
```
`auto` is [not allowed](https://docs.godotengine.org/en/stable/contributing/development/cpp_usage_guidelines.html#auto-keyword), also needs a better name

File: editor/gui/scene_tree_editor.cpp [hunk 2]
```diff
@@ -369,26 +369,26 @@ void SceneTreeEditor::_add_nodes(Node *p_node, TreeItem *p_parent) {
...
 				}
 			}
-		}
-		if (num_connections >= 1 || num_groups >= 1) {
-			if (num_groups < 1) {
-				msg_temp += "\n";
-			}
-			msg_temp += TTR("Click to show signals dock.");
+		} else {
+			msg_temp += "\n";
```
Comment (AThousandShips) [inline editor/gui/scene_tree_editor.cpp:373]: This adds the new line regardless, not sure that is correct, I'd just add the new line before adding the ending below, like so:
```c++
msg_temp += "\n" + msg_temp_end;
```

Comment (dustdfg) [reply editor/gui/scene_tree_editor.cpp:373]: I also don't know...  But if node doesn't have any groups we doesn't need to add `\n` because it will become unnecessary empty line. If we have groups we will get the `\n` along with `msg_temp += String::utf8("•  ") + String(E.name) + "\n";`

**Comment by aryan-11825114** [comment]
I was wondering what would be the case if both group and signal is present, wouldn't it be better if it said "Click to show in node dock"  for signal and group both?

Screenshot from 2024-10-04 18-13-02

**Comment by dustdfg** [comment]
> I was wondering what would be the case if both group and signal is present, wouldn't it be better if it said "Click to show node dock" for signal and group both?
> 

I also though about it but anyway by clicking on the you will open one of the tabs and you'd better to show user exactly what tab you will open

**Comment by aryan-11825114** [comment]
> > I was wondering what would be the case if both group and signal is present, wouldn't it be better if it said "Click to show node dock" for signal and group both?
> 
> I also though about it but anyway by clicking on the you will open one of the tabs and you'd better to show user exactly what tab you will open

I see, it seems logically good that way 👍

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
