### PR TITLE
Fix consistency of translated/scaled/rotated in Transform2D and Transform3D

### LINKED ISSUE #1336: Enable transform chaining by making scaled/rotated/translated consistent
**Describe the project you are working on:**

A guitar practicing application ([here](https://www.youtube.com/watch?v=odWXE5Dv9HQ) is an old version but in VR).

I suspect the reasons why I'm facing this issue more than others are:
- Almost all geometry/meshes are procedurally generated.
- Because of usage of `MultiMeshInstance` I can't rely less on node hierarchies, but have to compute complex transformation chains manually.
- I like fluent interfaces ;)

However the issue I'm facing is a fairly fundamental one, and can affect almost any project.

**Describe the problem or limitation you are having in your project:**

Basically every time I try to chain `.scaled`/`.rotated`/`.translated` I end up with a bug. I had raised this issue before https://github.com/godotengine/godot/issues/34329, which has been closed by adding a line to the documentation. This line didn't help much, I still run into the same problem a lot. I finally had the time to analyze why that is, and since 4.0 is the chance to get things right, here is my proposal.

Note: I'm discussing the topic based on `Transform`, but both the problem and solution would also apply for `Transform2D` as far as I can see.

Also feel free to read the much shorter proposal (down below) first, and only dive into the lengthy reasoning behind it (above) if need be ;).

## Terminology

Chaining transformation always requires to be aware of left-to-right or right-to-left thinking, because the "mathematical reading order" is typically opposite to the "transformation order". For instance
```
x' = C · B · A · x
```
first transforms `x` by `A`, then by `B`, then by `C`, opposite to how the mathematical equation is typically written. Put another way:

- Transform left multiplication
  ```
  M' = A · M
  ```
  means that `A` is applied _after_ `M` is applied.

- Transform right multiplication
  ```
  M' = M · A
  ```
  means that `A` is applied _before_ `M` is applied.

## Current behavior

Currently the behavior is a mix of left and right multiplication.

- Scaled:
  ```
  var M_new = M.scaled(... S ...)
  ```
  has **left** multiplication semantics (i.e., happens _after_ in transformation order):
  ```
  M_new = S · M
  ```

- Rotated:
  ```
  var M_new = M.rotated(... R ...)
  ```
  has **left** multiplication semantics (i.e., happens _after_ in transformation order):
  ```
  M_new = R · M
  ```

- Translated:
  ```
  var M_new = M.translated(... T ...)
  ```
  has **right** multiplication semantics (i.e., happens _before_ in transformation order):
  ```
  M_new = M · T
  ```

## Issue 1: Hard to read

Because of mixing left and right multiplication, I find it fairly hard to look at chained expressions and come up with the underlying mathematical order. Going from the code to the mathematical expression cannot be done by just reading in one direction, but rather requires to switch between left-to-right and right-to-left thinking. For instance:

```gdscript
var M = Transform.IDENTITY\
    .scaled(... S ...)\
    .translated(... T ...)\
    .rotated(... R ...)
```
is equivalent to (if I didn't get it wrong again)
```
M = R · S · T
```
Note how `R` has moved from last to first, `S` has moved to the middle, and `T` ended up at the end. The result feels almost like a random shuffle of the order written in the code. Doing such transformations on longer expressions is a challenging (and unnecessary) mental exercise.

## Issue 2: Hard to write

The problem is even more tricky the other way around, when trying to convert a mathematical expression into code.

_Example 1_: Imagine your goal is to write the following purely with chaining:
```
M = S · T · R
```
As far as I can see this actually cannot be written purely with chaining, because having the `.translated` in the middle breaks the right-to-left flow, and there is no way get the `R` in the right position.

The only way to write it is in a non-chained way, for instance:
```gdscript
var M = Transform.IDENTITY\
    .scaled(... S ...)
    .translated(... T ...)
M *= Transform.IDENTITY.rotated(... R ...)
```

_Example 2_: Imagine implementing longer transform chains like:
```
M = R_2 · T_2 · R_1 · S_2 · T_1 · S_1
```
Trying to work out the code becomes more and more awkward, because it is necessary to split the expression into subgroups at each `T_*`, which break the right-to-left flow. The individual groups can be assembled right-to-left, but need to be assembled
in an outer multiplication left-to-right. An alternative is to manually implement translation left multiplication with the trick to use `temporary.offset += T_*`. In any case the resulting code is much less clear than a full chaining expression (if `.translated` would do left-multiplication as well):
```gdscript
var M = Transform.IDENTITY\
    .scaled(... S_1 ...)\
    .translated(... T_1 ...)\
    .scaled(... S_2 ...)\
    .rotated(... R_1 ...)\
    .translated(... T_2 ...)\
    .rotated(... R_2 ...)
```

## Issue 3: Performance aspects

In general writing transforms as chains is faster than using full `transform1 * transform2` expressions, because the implementation can exploit the particular matrix properties of `.scaled`/`.rotated`/`.translated`. However, because of the error prone chaining semantics, I have basically replaced many transform chains by transform product expressions, which has performance drawbacks.

I had to refresh my memory about the differences, in case you are interested in the details:

<details>
<summary>All possible transform operations</summary>

### Translation

**Left multiply**

Translation_lm

**Right multiply**

Translation_rm

### Scale

**Left multiply**

Scale_lm

**Right multiply**

Scale_rm

### Rotation

**Left multiply**

Rotation_lm

**Right multiply**

Rotation_rm

### Generic transform

**Left multiply (rhs only)**

Transform_lm

**Right multiply (rhs only)**

Transform_rm

</details>

Counting the number of floating point operations gives:

| Operation                     | # Floating point operations | available |
|-------------------------------|----------------------------:|:---------:|
| Translation (left multiply)   |                           3 |           |
| Translation (right multiply)  |                          18 |     *     |
| Scale (left multiply)         |                          12 |     *     |
| Scale (right multiply)        |                           9 |           |
| Rotation (left multiply)      |                          60 |     *     |
| Rotation (right multiply)     |                          45 |           |
| Full transform multiplication |                          60 |     *     |

It is interesting to see how much more costly a full `transform1 * transform2` (60 ops) is compared to a simple translation left multiply (3 ops). The other aspect I vaguely remembered: For scale/rotate the faster operation is right multiplication, whereas for translation it is left multiplication. If performance is critical, it can be helpful to build a transform exactly in the way that minimizes floating point operations. Unfortunately, the interface in Godot is not only inconsistent, but also offers only the less efficient variants.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

The solution I'm proposing is to make the interface consistent and offer all possible operations:

- `.scaled` performs **left** multiplication
- `.rotated` performs **left** multiplication
- `.translated` performs **left** multiplication
- `.pre_scaled` performs **right** multiplication
- `.pre_rotated` performs **right** multiplication
- `.pre_translated` performs **right** multiplication

This is also the solution chosen by [Eigen](https://eigen.tuxfamily.org/dox/group__TutorialGeometry.html) (possibly the most famous library in that area) just the other way around because of using participles instead of infinitives, and to be less of a breaking change. What "pre" means is a matter of convention anyway, and up to the documentation to communicate.

Thus, in terms of documentation it is key to clearly describe what these functions do mathematically. Currently the docs do not even clearly say whether they are performing left or right multiplication, I only figured it out after reading the C++ sources. I could contribute some of the stuff above to the docs.

In terms of breaking changes this would add one item to the Godot 4.0 migration guide: Replace `translated` by `pre_translated`.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Should be covered by the section above.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

It affects `Transform` / `Transform2D` so the enhancement is probably used often.

**Is there a reason why this should be core and not an add-on in the asset library?:**

Mainly to avoid headaches for others.

### PR DESCRIPTION
**Pull request by bluenote10**
This PR implements https://github.com/godotengine/godot-proposals/issues/1336 or more specifically the refinement by @tagcup2 in https://github.com/godotengine/godot/pull/48769#issuecomment-844585736. His last paragraph summarizes this PR quite well:

> To make the API consistent, _local versions of these functions should be added (similar to the way Basis works). In Transform2D and Transform3D, translated should be renamed as translated_local, and a global version (which does t.origin += v) should be added.

This only differs from https://github.com/godotengine/godot-proposals/issues/1336 in the naming convention of the functions `..._local` vs `pre_...`. Since `Basis` already uses the `_local` suffix and it has a more intuitive interpretation, using `..._local` is obviously much better and nicely matches the existing code in `Basis`.

Note that this is a breaking change, but with a simple search/replace fix pattern for users: replace `translated` by `translated_local`.

A few detailed remarks:

- I first refactored `translated` to `translated_local` with the help of an IDE and made sure that everything was compiling and all tests were running **before** introducing the new implementation of `translated` that performs global frame transformation. I hope this can produce some confidence having refactored all usages. I'm only a little bit worried about usages behind `#ifdef` switches.
- In many cases the refactoring from `translated` to `translate_local` was actually irrelevant, because it was applied to an identity transform, in which case both versions do the same anyway. I nevertheless went for strictly renaming all instances for the sake of completeness.
- I decided against adding mutable in-place versions of all variants, because they are not exposed to users anyway, and would be dead code as of now. If this becomes useful at some point internally, it can be done later of course. I did rename the existing in-place versions of `translate` though because otherwise it would be hugely confusing that they are inconsistent with `translated`.
- Previously the implementation of some of the `translated`/`rotated`/`scaled` functions were based on temporaries with post-construction in-place modification. In some places I got rid of it, because it makes the code more symmetric regarding the two versions, and it can avoid the unnecessary memory initialization.
- To make sure I didn't get the math wrong, I've added new tests for `Transform2D` and `Transform3D` with a focus on the new functionality. The idea of the test is to simply compare all of the 6 functions against explicit left or right multiplication as a source of truth.

And again as a small convenience for reviewing:

<details>

<summary>Formula Cheat Sheet</summary>

### Translation

**Left multiply**

Translation_lm

**Right multiply**

Translation_rm

### Scale

**Left multiply**

Scale_lm

**Right multiply**

Scale_rm

### Rotation

**Left multiply**

Rotation_lm

**Right multiply**

Rotation_rm

</details>

Closes godotengine/godot-proposals#1336
Resolves https://github.com/godotengine/godot/pull/48769

### CODE REVIEW

**Comment by fire** [comment]
@TokageItLab You have more experience with transforms. What do you think?

**Comment by TokageItLab** [comment]
It is true that matrix multiplication gives different results for right and left multiplication.The same can be said for quaternions, a concept that compiles matrices.

Actually, I never paid much attention to it because most of the time I directly multiply Basis and Quaternion when I need those transforms.

I can support this PR in terms of consistency. However, considering that people who understand linear algebra math may not use these methods much, it may not be a necessary change.

Moreover, there is a compatibility concern in that all the old `translate()` will be replaced by `translate_local()`. It make me it is out of my hands, so I think @reduz 's judge is important.

**Comment by bluenote10** [comment]
> I can agree this PR in terms of consistency. However, considering that people who understand linear algebra math may not use these methods much (since multiplication using a mathematical formula is sufficient)

Do you mean by simply creating each transform on its own and multiplying them? E.g., instead of `.translated(...).scaled(...).rotated(...)` creating the corresponding `T = ...`, `S = ...`, `R = ...` and computing `R · S · T`? Mathematically that is fine of course, but has obvious downsides:

- syntactically more verbose, in particular not writable as a single expression,
- creates unnecessary temporary transform objects,
- performs much more floating point operations than necessary, because a full transform multiplication requires 63 ops, whereas specialized variants can get away with much fewer ops:

<details>

<summary>Ops comparison</summary>

| Operation                     | # Floating point operations | available |
|-------------------------------|----------------------------:|:---------:|
| Translation (left multiply)   |                           3 |           |
| Translation (right multiply)  |                          18 |     *     |
| Scale (left multiply)         |                          12 |     *     |
| Scale (right multiply)        |                           9 |           |
| Rotation (left multiply)      |                          60 |     *     |
| Rotation (right multiply)     |                          45 |           |
| Full transform multiplication |                          63 |     *     |

</details>

> Moreover, there is a compatibility concern in that all the old translate() will be replaced by translate_local().

I think the concern can be broken down into two aspects:
- **Breaking change for users**: Since only the immutable variant of `translated` is exposed to users, the Godot 4.0 migration guide could contain a plain simple rule: Rename your usages of `translated` to `translated_local`. And again: In many situations it wouldn't even make a difference, since (like some occurrences I came across in the engine) they may be applied to the identity anyway.
- **Breaking change internally in Godot**: This is more tricky, because internally there are also in-place versions of `translate`, and we indeed have to make sure that we refactor them all properly. What I can offer to make this more systematically: I can create a supplementary PR that **only** applies the renaming from `translate` to `translate_local`. If this then passes all GitHub CI pipelines without compilation/test errors, we can be confident that all usages of `translate` and `translated` have been identified and refactored, i.e., we cannot accidentally use the "new" translate. After that refactoring PR is merged, I could rebase this PR so that it only contains the changes related to new functionality.

Godot 4.0 is the opportunity the get these things right, please give it a chance :wink:

**Comment by TokageItLab** [comment]
> syntactically more verbose, in particular not writable as a single expression,

Whether it is redundant or not depends on the person. At least in scripting, I don't like to have long lines due to method chains.

> creates unnecessary temporary transform objects,

Temporary transformation objects are also created in those functions.

> performs much more floating point operations than necessary, because a full transform multiplication requires 60 ops, whereas specialized variants can get away with much fewer ops:

It's not always about computing Transform3D to each other. In some cases, we just add the Vector3 to the matrix. In those calculations, I assume it is an edge case that requires 60 ops each time.

---

To be honest, I don't care much about compatibility myself. Maybe it's because I don't use those functions much.

I think consistency is important, and I would never block this PR of my own volition, but I guess it all comes down to whether or not these are compatible with the Godot concept, so I'll leave it all to reduz.

**Comment by bluenote10** [comment]
> Temporary transformation objects are also created in those functions.

Not in all cases. Look at e.g. how `translated` and `translated_local` are implemented. They can directly construct the resulting transform, only applying the appropriate offset to the origin.

> I assume it is a special case if it requires 60 ops each time.

I just meant that if you construct two "standalone" transforms `a` and `b` and multiply them, the multiplication operator cannot assume that any of the elements is 0, so internally you end up computing something like:

image

If I'm counting correctly and the origin on the left actually isn't zero, it's 63 operations even. With dedicated translate/scale/transform functions it is possible to exploit the particular shape of the matrices and their zero values, which makes it faster in general.

**Comment by TokageItLab** [comment]
> Not in all cases.

The same can be said for formulas.

> I just meant that if you construct two "standalone" transforms a and b and multiply them

What I mean is that it is a special case that we need to multiply Transform3D every time.

**Comment by TokageItLab** [comment]
One thought I had was that GDScript has a problem with calculation speed. If we need a high level of math to affect performance, we mostly use Native to get around it, but using those methods might also speed things up.
If that can be tested and verified, that would be the strong reason for merging this PR.

**Comment by madmiraal** [comment]
I agree there needs to be consistency.

However, as I tried to demonstrate in https://github.com/godotengine/godot/pull/48769#issuecomment-845567486 and @andre-caldas has tried to describe [here](https://github.com/godotengine/godot-proposals/issues/1336#issuecomment-841750876), [here](https://github.com/godotengine/godot-proposals/issues/1336#issuecomment-841801805) and in his counter proposal (https://github.com/godotengine/godot-proposals/issues/2738) the intuitive behaviour of `translate()`, `rotate()` and `scale()` should be in the local reference frame. In other words, a chained `translate().rotate().scale()` should behave the same way as setting these values in the Inspector does.

If there is an argument for `translate()`, `rotate()` and `scale()` to be in the parent reference frame (and I'm not convinced there is) then I agree with the original proposal that these should be prefixed with `pre_`.

**Comment by bluenote10** [comment]
> However, as I tried to demonstrate in #48769 (comment) and @andre-caldas has tried to describe here, here and in his counter proposal (godotengine/godot-proposals#2738) the intuitive behaviour of translate(), rotate() and scale() should be in the local reference frame.

Proposal godotengine/godot-proposals#2738 isn't really a counter proposal. From what I can see it is largely in line with the changes, and many of his proposed changes like proper naming using 2D and 3D suffixes consistently have already been implemented. Here is a quick comparison:

@andre-caldas starts by raising the question _what do we mean by `var r = t.translated(Vector2D(1,1))`?_ which nicely discusses the two possible meanings of such operations. He is correctly arguing that both versions are meaningful: The one we typically call "global" is useful when looking from the "outside" perspective, the other one we typically call "local" is useful when looking at it, well, locally.

He then moves on to rotations, where he correctly states: _There is one very natural point someone might be interested in rotating an object about: the **local origin**._ But there is also another very natural point someone might be interested in rotating the object about: the **parent/global origin**. Imaging modelling a "spinning cups ride":

image

The local rotation is useful to rotate the cups themselves around their local origin. i.e., spinning the cups itself. The parent/global rotation is useful to rotate the cup around some parent origin, i.e., spinning it around the coffeepot. For some reason he says _I don't think "rotation about the non-local origin should be an implemented method._ This is the only part I cannot fully agree (and what a breaking change that would be, because this function exists and is widely used!). In my use case (this [guitar music visualizing](https://www.youtube.com/watch?v=odWXE5Dv9HQ) thingy that requires lots of procedural geometry), I definitely had a need for applying global rotations/scales as well.

> There may be an argument for translate(), rotate() and scale() to be in the global reference frame, but I don't see an easy way to achieve this.

To clarify: When speaking of "global" I'm using @tagcup2's terminology meaning "parent", or @andre-caldas's "from the outside". The "absolute global frame" is just a special case of this, i.e., where the parent is the root.

> I agree there needs to be consistency.

Great :wink: So as far as I can see we have two options:
1. Defaulting to "global" versions in `translated`/`scaled`/`rotated`, and adding `..._local` variants.
2. Defaulting to "local" versions in `translated`/`scaled`/`rotated`, and adding `..._global` variants.

Even though I find (1) more intuitive, I personally wouldn't mind going the other path as well. However, you have to consider the amount of breaking in Godot. When going down the path of (2) we will brake **two** of the existing fundamental transform functions, whereas we only break **one** with (1). Also, `Basis` already follows (1): Its non-suffixed transform functions currently have "global" semantics, and there are suffixed `_local` versions. So going down the path of (2) would imply even more breaking changes from breaking `Basis`.

Therefore I think if we want to convince @reduz to fix this inconsistency, (1) is our best option. Perfection is the enemy of progress.

**Comment by bluenote10** [comment]
I should also mention that my use cases are mainly in the area of **procedural mesh generation** where I don't have Godot's node hierarchy system available. I.e., the meshes I'm using are generated from various mesh primitive fragments, assembled to bigger meshes using purely transforms. Imagine for instance modelling above spinning cup ride as a huge mesh without relying on nodes.

**Comment by Zireael07** [comment]
@bluenote10: Got a link to the project? I happen to be making two games that are 90% proc-gen meshes and I'd love to take a look!

**Comment by bluenote10** [comment]
> @bluenote10: Got a link to the project?

@Zireael07 Unfortunately not yet ready for prime time :wink:

**Comment by andre-caldas** [comment]
The teacups with all those kids inside, do not turn themselves about the parent's origin. Let me call the parent `wheel`. The parent rotates itself and all its contents. I would call `wheel::rotate(angle)`, and have all them rotated by just changing their parent's coordinate system. In this complex system, I would implement things independently:
> /* Whole wheel code */
> function update (dt):
>     rotate(angular_speed * dt)
>
> /* Each teacup code */
> function update (dt):
>     rotate(angular_speed * dt)
This is how such a toy works. Everything is local!!! Each object is very isolated from their relatives. The `wheel`'s `angular_speed` depends on the park staff controlling the toy. And the `teacup`'s `angular_speed`, depend on the kids riding it. :-)

IMHO, the objects `Transform2D` and `Transform3D` should be considered. I remember @redux already told me that it is not his intentions to expose the `Node::transform`. But then, each node with its own coordinate system should be treated **as if** it was inherited from `TransformXD`. As I have emphasized, those objects are not one transformation. They are a coordinate system with origin. It would be very, very clear what one means by `transform.rotate_object(object, angle)`. Or maybe, `transform.rotate_node(node, angle, origin)`.

If one calls `rotate_par` from inside the node, it means to me that the node is aware of something it should not be. The design is not isolating the node from its parent. The scenario I see for, from inside a node, calling `rotate_par` is like this:
> /* Parent pseudo-code */
> foreach node in children:
>     node.rotate_par(angle)
The `Node2D::rotate_par` would then access it's parent's origin and proceed with rotation about the parent node.

IMHO, it would make much more sense if the parent rotates the child node. Just like the tea cups:
> /* Parent pseudo-code */
> for each node in children:
>     rotate_node(node, angle)

Or even:
> /* Parent pseudo-code */
> for each node in children:
>     rotate_node(node, angle, fixed_point)

There is no ambiguity here. No `_local`, no `_global`. Everything is in parent node's coordinate system. The teapot can rotate itself and the wheel can rotate itself or be rotated by someone.

**Comment by bluenote10** [comment]
@andre-caldas Again, this is about pure transform usage for mesh generation where there is no node system. Within the hierarchical node system, chaining transform is indeed exotic, and using `set_translate`/`set_rotate`/`set_scale` is typically sufficient. So scratch the example with the spinning cups ride, because it apparently makes everyone think in node hierarchies again :wink: Rather imagine you'd have to generate a complete static mesh of such a scene procedurally. You will see that first shifting something away from the origin and rotating it afterwards around the parent/global can be a useful tool. The cup placement would actually work similar to the first mesh example, and it would be much more awkward if we wouldn't have the option to rotate about the parent/global origin.

File: core/math/transform_2d.h [hunk 1]
```diff
@@ -78,8 +78,8 @@ struct Transform2D {
 
 	void scale(const Size2 &p_scale);
 	void scale_basis(const Size2 &p_scale);
-	void translate(const real_t p_tx, const real_t p_ty);
-	void translate(const Vector2 &p_translation);
+	void translate_local(const real_t p_tx, const real_t p_ty);
```
Comment (reduz) [inline core/math/transform_2d.h:81]: Even though I think the rename can be ok in this context, I believe would also keep translate (and specially translated) as a global version (just offset the origin). There is merit to to having this version too when you want to move the positioning of an object but not its rotation.

In other words, all the code in this PR being ok, but also add back translate/translated() as global.

**Review by reduz — DISMISSED** [review]

**Comment by reduz** [comment]
Maybe we should just have versions named _global and _local ? (or _origin and _local).
I understand both point of views but its true that for one or the other this can be confusing, so maybe being fully explicit is a better solution in the end.

File: core/math/transform_2d.h (hunk 1 above)
Comment (bluenote10) [reply core/math/transform_2d.h:81]: > also add back translate/translated() as global.

`translated` in a global version is already there, right? I've only grouped them below to make them better recognizable as a group. See also unit tests to show that all 6 exist.

In can surely add an in-place `translate` (= global) variant as well. The main reason I didn't is that it is C++ only anyway and not exposed to GDScript.

**Comment by bluenote10** [comment]
> Maybe we should just have versions named _global and _local ? (or _origin and _local).

That would work as well, but then we have the biggest breaking change, because users must change all existing usages of translated/scaled/rotated. Considering that this affects quite a bit of user code, I'd have limited to 1 breaking function change.

**Comment by reduz** [comment]
@bluenote10 Yeah I think I agree that your PR as is (with my suggestion to keep translated as global) may be the way to go. Its a worth breaking change to make it consistent.

**Comment by madmiraal** [comment]
> Maybe we should just have versions named _global and _local ? (or _origin and _local).
I understand both point of views but its true that for one or the other this can be confusing, so maybe being fully explicit is a better solution in the end.

@reduz The problem with `*_global` is that they don't happen in the global reference frame. They only happen in the parent reference frame. The problem with the parent reference frame is that it's generally not what the user expects (see the examples I presented here: https://github.com/godotengine/godot/pull/48769#issuecomment-845567486). Therefore, in my opinion, they are not equal and we should be helping the user by not prefixing or suffixing the one most likely to be used by the user i.e. in the one in the local reference frame should not have a prefix or suffix.

**Comment by bluenote10** [comment]
@madmiraal

> The problem with *_global is that they don't happen in the global reference frame. They only happen in the parent reference frame.

Fully agreed. If we would go for an all-suffixed API I'd rather suggest `_parent` instead of `_global`.

> The problem with the parent reference frame is that it's generally not what the user expects

That's an assumption, and it is _very difficult_ to know what the average Godot user really expects :wink:. The discussion has showed that many users expect the opposite already. There are certainly reasons why the non-suffixed versions should be the local transforms:

- It is what Eigen does.
- It is what GLM does.
- Your example regarding consistency with the inspector.

On the other hand there are also good reasons why the non-suffixed versions should be the parent/global transform:

- Graphic programming and robotic books typically encourage thinking right-to-left as the mental model. When going from e.g. a robot's head to world space, a typical way of seeing it is: Place the head w.r.t. the robot, place the robot w.r.t. a house, place the house w.r.t. a city, place the city w.r.t. to the world. Of course, one can just as well use the inverted mental model, but in the books I've studied, the mental model is most often presented in right-to-left fashion.
- In graphic engines that don't have a node tree, the right-to-left mental model is often pervasive as well.
- Since libraries like Eigen/GLM default to the opposite, it is common to see code that "fights the wrong defaults". For instance I've seen Eigen code that mainly uses `prerotate` instead of `rotate` (and their siblings) because apparently these functions align better to the mental model of the developer. A good example of that is also [this chapter](https://paroj.github.io/gltut/Positioning/Tut06%20Fun%20with%20Matrices.html) of the [Learning Modern 3D Graphics Programming](https://paroj.github.io/gltut/index.html) book. The chaper first introduces the concept of transform chaining in a right-to-left fashion, because the author feels like this is more natural. When it comes to the implementation, he suddenly has to invert the order stating: 
image
Comments like this indicate that the library API default is against the expected semantics.
- The existing `scaled` and `rotated` in Godot are already in parent/global frame, so that would make it somewhat likely that some Godot users already have developed the expectancy that Godot transforms w.r.t. parent/global frames.
- The inconsistency in the inspector could also be fixed by renaming it there to "local".
- The amount of breakage, as discussed.

Overall there is probably no way to prove what users expect, but my gut feeling is that Godot's API may be even closer to what many users expect due to the pervasiveness of right-to-left thinking.

**Comment by Zireael07** [comment]
> The problem with the parent reference frame is that it's generally not what the user expects

As long as the functions are named _global, them using the parent reference frame will definitely NOT be what the user expects based on the function's name. Names should match what they do, so a +1 to changing _global to _parent.

**Comment by andre-caldas** [comment]
Since there are many conflicting opinions, I would like to suggest that we solve this once and for all through this method:
https://github.com/godotengine/godot/pull/48769#issuecomment-1119423803

**Comment by andre-caldas** [comment]
Making things simple
  =

  I am just talking about `Transform2D`... but the same principle applies in other places.

  **The example below on "rotating a person" is very important!**

  I will list what IMO is reasonable to have as built in operations. Other effects can be achieved by manipulating what **unfortunately is called** `column[0]`, `column[1]` and `column[2]`.

  What I describe bellow is basically how `Node2D` works. And I see no reason to have things behaving in different ways in `Node2D` and `Transform2D`.


  `translate` and `translate_local`
  -

  Very good. Agreed. I do think `translate_local` is a symptom of bad design, but it does has its place.



  `scale`, `scale_local` and `basis_scale`
  -

  This is very weird.

  There should be **only** the `scale_local`, and it should simply be called `scale`. What does it do? It takes the axis `column[0]` and `column[1]` and stretches them (multiplies by the given values).

  Or, better yet, there could be only uniform scaling: multiply both by the same number.

  Different kinds of scaling can be achieved by manipulating `column[0]` and `column[1]` to scale *"in place"*; and manipulating `column[2]` to allow the scaling to drag the object while scaling. I do think that scaling `column[2]` is bad design:

  > You should probably put the set of things you want to be drifted along in a common container and then simply scale the container.



  `rotate`, `rotate_local`
  -

  **More important than those two** is what you might want to call `basis_rotate`. You simply apply a rotation to `column[0]` and `column[1]`.

  The important issue on rotation is not if it is "from the left" or "from the right". The important issue is if the rotation is about the object's origin or about the "parent coordinate origin". That translates to:
  - shall `column[2]` be rotated?

  For those who like "left and right", this is rotation applied to the **left**, but only to `column[0]` and `column[1]`, and **NOT** to `column[2]`.

  There should be only this *"basis_rotate"*, and it should be called `rotate`.

  Things applied to the right are, in a sense, applied in reverse order, and **I doubt it is intended**. For example:
> If you `scale_local(3, 1)` a standing person, you get a fat person. If then, you `rotate_local(90 degrees)`, you should have a rotated fat person. But what you get with this patch is a rotated very, very tall person!!!

**This rotating person example is VERY IMPORTANT!** But it only is noticeable if you have `skew` and/or non uniform scaling (ie: `column[0]` and `column[1]` with different sizes).


  What if...?
  -

  Whatever you want to do beyond the things listed above, you can simply manipulate `column[0]`, `column[1]` and `column[2]`.

  It is very hard to say without *use cases*, but more complicated transforms can be obtained by chaining coordinate systems.

  **Real and complete use cases** need to be reported in order to justify this proposal.



  Very easy to understand!!!
  -

  With the exception of `translate_local`, all the other operations **do commute**. In other words, those operations are independent one to the other. Those very basic operations are very hard to cause any confusion.

**Comment by bluenote10** [comment]
> Real and complete use cases need to be reported in order to justify this proposal.

My use case is this [guitar practicing app](https://www.youtube.com/watch?v=odWXE5Dv9HQ&t=9s). In general the proposal targets use cases like custom mesh generation and multi mesh instances, where you **cannot rely on a transform hierarchy**. Your are right that in many cases manual transform chaining isn't needed, because the node system solves it. But you are simply wrong in that there aren't any use cases for that. I know that there are ugly work-arounds by manipulating the transform elements manually. But not only is that significantly slower when done in GDScript, it also leads to totally ugly syntax, poor re-usability, and bad readability. A library is supposed to be ergonomic and cover relevant use cases. It is unfair of you to constantly question if these use cases exist just because you personally have never encountered them :disappointed: . I recommend you work on a project that uses procedural geometry entirely and you will come across these use cases.


> I doubt it is intended

If you want a use case: In my guitar app, I'm for instance using a left-multiplication scale to adjust the size of the guitar fretboard. Of course I could also locally scale all the submeshes (frets, inlays, ...) that make up the fretboard, but it is just easier and more performant to scale it all in one go. Obviously, global scale manipulations are typically uniform to avoid deformations, but there are also use cases for applying a non-uniform global scale e.g. when procedurally generating "squished" shapes like ellipsoids, or when the model has certain structural symmetries that can be exploited. For instance a very common use case: For geometries that have an axial symmetry you often want to apply a global scale with different values for the axial and and the radial dimensions.

-------------

There are also practical issues with what you are proposing: The global `scaled` function already exists in Godot. There are maybe thousands of usages of it out there in the wild. We cannot just remove a valid existing function because you personally don't like it. How should we even document that? _Please everyone replace all your usages of `scaled` by this snippet of (non-chainable) manual transform manipulation._ It doesn't make sense to remove valid functionality.


It's a practical fact that there are always **two** ways to apply any of these operations. Sometimes the local one is the preferred one, sometimes the global one. Any claim in the direction "you never need this operation in local/global" is strictly wrong, because it is easy to construct a counter example where the operation is the natural one, and I can show you existing source code relying on it. Furthermore, the argument that users should just implement them manually when necessary is absurd for performance reasons, code-reusability reasons, and because a library should strive for being ergonomic and complete. Also, entirely removing existing functionality is highly non-practical from the perspective of breaking existing code. For all these reasons, it is much more sensible to offer **all six** operations with consistent global vs local semantics.

**Comment by andre-caldas** [comment]
> It's a practical fact that there are always **two** ways to apply any of these operations.

Nope. This is exactly what you have been ignoring. There are **three** ways (rotation and scaling):
1. From the left applied to `column[0]`, `column[1]` and `column[2]`.
2. From the left applied to `column[0]` and `column[1]`. (this is what I think you want)
3. From the right. (this is what you are doing)

Actually, you might even want to apply the transform **only** to `column[2]`!!!


> My use case is this [guitar practicing app](https://www.youtube.com/watch?v=odWXE5Dv9HQ&t=9s).

I have seen this video. It is really amazing! :-)
But it is not a use case as **there is no code**.


I do agree!
-

Just to be clear, I do agree that current implementation is quite confusing and totally not consistent. But you all seem to be ignoring that there are **three** ways to apply the operations and **not only two**. Some times, there are **four** natural ways!!!

With current implementation, **_the order of operations are reversed_**. It probably **not a problem for you**, because you don't chain rotation with non uniform scaling or skewed transforms.

But I do have a strong believe that the following pseudo-code gives an **unexpected result**:
```
  # Operations to be applied to a standing person.
  t.scale(3,1);
  # at this point, the thing is stretched in **its** $x$ direction.
  # The person should get really fat.

  t.rotate(90 degrees);
  # Your intention, I dare to say, is to have a "fat person laying down".
  # But what you really get is a "**very tall person** laying down".
```

What happens in the example above:
> Person P is rotated AND THEN stretched in the $x$ direction.

This is because of the matrix operation from the right:
> S R P.

Where person $P$ is **first** rotated by operation $R$ and only then scaled by operation $S$. **I doubt very much this is the intended behaviour**.


There are three ways!!!
-

> It's a practical fact that there are always two ways to apply any of these operations.

What you fail to account is that there are **three ways** to do things. Sometimes, **four** natural ways!

I dare to say that most of the time one does a `_local` transform, **this person does not want the order of operations to be reversed**. (except for scaling)

> If you want a use case: In my guitar app, I'm for instance using a left-multiplication scale to adjust the size of the guitar fretboard. Of course I could also locally scale all the submeshes (frets, inlays, ...) that make up the fretboard, but it is just easier and more performant to scale it all in one go.

This is exactly what I wrote in my previous comment! In my opinion, scaling and **only scaling** should be done with right multiplication. Which simply accounts to multiplying `column[0]` and `column[1]`.

What I do not agree is **rotation**!!! If you **first** scale and only then rotate, you do not want the rotation to be applied first. That is what your `_local` code does!



> Furthermore, the argument that users should just implement them manually when necessary is absurd for performance reasons, code-reusability reasons, and because a library should strive for being ergonomic and complete.

So, I suppose you are advocating for **three versions** (or **four**!) of each function, since there are **THREE DIFFERENT WAYS** to do things.

From what you say, I suppose we also need a `rotate_only_position` function that rotates the position but does not rotate the object, like in a *Ferris wheel*.


Not an ideal world, I know
-

> We cannot just remove a valid existing function [...]

Yes, it is not an ideal world, and I do not mind. I am just showing you that **there are three different** ways to apply those transforms.

I think it is **very important** that people **be very clear** on what each function does before **jumping to implementation**. Especially, if it is going to change working stuff and introduce some *standard*.

> [...] because you personally don't like it.

I am very worried about the **VERY WRONG** assumption you make that **local = from the right**. You are making fun of me because you do not understand what my worries are.

I do not advocate for eliminating non uniform scales. But Godot's implementation copes very badly with non uniform scaling and, in special, skews (as can be seen in many parts of the `Transform2D` and `Transform3D` code).

Maybe (I am not advocating for this), some one *matrix oriented* would like to do things in the line:
```
  // FOUR DIFFERENT ROTATIONS.
  my_transform = Transform2D::rotation(90) * my_transform;
  my_transform = Basis2D::rotation(90) * my_transform; // Keep column[2] as it is.
  my_transform = my_transform * Transform2D::rotation(90);
  my_transform.column[2] *= Basis2D::rotation(90);
```

The problem with non uniform scales (and skews) is that **your patch does not cope well with it**.


Is it intended???
-

Take the picture of a standing person and:
1. First stretch the $x$ direction (and make the person fat).
2. After that rotate the "fat person" 90 degrees.

If any one states that the **INTENDED RESULT** is to have a **very tall thin person** rotated, then I do agree with this patch.

**Is this intended??? If it is not, it is a bug in this patch!!!**

**Comment by bluenote10** [comment]
Your interpretation of the implementation seems to be the exact opposite to what it is. The example

```
t.scaled(3, 1).rotated(90 degrees)
```

has exactly the behavior you expect it to have. Mathematically the resulting transformation is `R · S`. Reading it in the usual right-to-left-fashion (how a vector gets transformed) the semantics become exactly: (1) first the person gets scaled to be "fat", and then (2) it gets rotated, i.e., resulting in the "fat lying" person as you expected.

And all this PR offers is to allow both. So if someone wants to generate the "tall lying" person they could either flip the operations or write:

```
t.scaled_local(3, 1).rotated_local(90 degrees)
```

Mathematically this will then be the `S · R` case. By applying the local rotation "later" (in code!) means that it precedes the existing transform, i.e., it comes "earlier" (in transformation order!). Semantically this means (1) first the person gets rotated (i.e., lies down), (2) and then stretching it along x makes it tall.

Note the difference: With the first version "earlier in code" corresponds to "earlier in transformation order", whereas with the local version it is flipped, i.e., "earlier in code" corresponds to "later in transformation order". For this reason I actually see people often prefer the first version in practice.

---

And again, it is just a mathematical fact that there are 6 versions. We have 3 operations `translated`, `rotated`, `scaled`. From the perspective of affine geometry each of these operations corresponds to an augmented transformation matrix, let's call it `T`. If we have an existing transformation `T_orig` and we apply any of these operations, math simply leaves us two possible choices: `T_orig · T` and `T · T_orig`. This makes a total of 3 * 2 = 6 operations that are mathematically possible and all are meaningful and have their use cases. If you look around in famous existing math libraries you will notice that they all offer these 6 variants.

**Comment by andre-caldas** [comment]
> `t.scaled_local(3, 1).rotated_local(90 degrees)`

I am talking about this "local version". I misused the name `rotated` and `scaled`. I was coding as if it was `Node2D`... sorry. I never get used to the fact that this "fix of consistency" is **not consistent** with `Node2D`.

Finally!!!
-

> Mathematically this will then be the S · R case. By applying the local rotation "later" (in code!) means that it precedes the existing transform, i.e., it comes "earlier" (in transformation order!). Semantically this means (1) first the person gets rotated (i.e., lies down), (2) and then stretching it along x makes it tall.

So, **you are saying that**
```
  t = t.scaled_local(3, 1)
  t = t.rotated_local(90 degrees)
```
should mean
1. First rotate 90 degrees.
2. And **after that**, do scaling.

Well, if people do agree that this is the **expected behaviour**, I rest my case. :-)

If people agree that the so called `_local` transforms should be made in the **REVERSE** order... the patch is perfect.

If Godot's maintainers believe that taking the picture of a standing person, stretching it in the $x$ direction (making it fat) and then rotating this person should result in a **very thin and very tall person rotated**, then the patch work as expected, indeed.

But "local" operations can be made from the left, keep the order they were called (natural?) by just applying the changes to `column[0]` and `column[1]`, without applying them to `column[2]`. Personally, I do not understand why would anyone prefer to revert the order... unless s/he is really into this *"matrix multiplication world"*.

**Comment by andre-caldas** [comment]
> And again, it is just a mathematical fact that there are 6 versions. We have 3 operations `translated`, `rotated`, `scaled`. From the perspective of affine geometry each of these operations corresponds to an augmented transformation matrix, let's call it `T`. If we have an existing transformation `T_orig` and we apply any of these operations, math simply leaves us two possible choices: `T_orig · T` and `T · T_orig`. This makes a total of 3 * 2 = 6 operations that are mathematically possible and all are meaningful and have their use cases. If you look around in famous existing math libraries you will notice that they all offer these 6 variants.

I don't know how you can say that there are only six, when I present you at least four just for rotation!!! There is a bunch more for scaling, exactly the same way. **As a mathematician myself**, I do not agree when you imply (do not say, but imply) that *it is a mathematical fact that there is NO MORE then 6 ways to do those operations*. It is a very bold and (meta-)mathematically **incorrect** statement.

1. Rotate everything from the left.
2. Rotate only `column[0]` and `column[1]` form the left.
3. Rotate only `column[2]` form the left. (Ferris wheel)
4. Rotate from the right.

Since you really like matrices... I do find it pointless to use augmented matrices for this... but:

$\displaystyle\begin{bmatrix}\cos(\theta) & -\sin(\theta) & -x\cdot\cos(\theta)+y\cdot\sin(\theta)+x\\\sin(\theta) & \cos(\theta) & -x\cdot\sin(\theta)-y\cdot\cos(\theta)+y \\\\ 0&0&1\end{bmatrix}$,

where $x = \mathrm{column[2]}.x$ and $y = \mathrm{column[2]}.y$. Gives you another option! And it is done from the left! And it does keep the natural order: the order which the methods were called, in the first place.

See [this article on MathStackExchange](https://math.stackexchange.com/questions/2093314/rotation-matrix-of-rotation-around-a-point-other-than-the-origin) for more information.

Of course, this is just the same as applying the rotation only to `column[0]` and `column[1]`, and it would be really dumb to do this using *augmented matrix multiplication*.

**Comment by bluenote10** [comment]
Agreed, one can introduce new / non-fundamental transformation operations to make it more than 6. I was referring to the three existing ones in Godot. In any case, every transformation that can be expressed as an augmented matrix `T` comes in pairs, because it can be applied either `T_orig · T` or `T · T_orig`.

**Comment by akien-mga** [comment]
This can be rebased (or redone from scratch, whichever is easiest) now that #57698 has been merged.

From a quick review, I noticed that the commit messages don't mention `scaled` and `rotated`, this should likely be amended.

And as of this PR, we'll have this set of methods:
- `translate_local` | `translated` and `translated_local`
- `rotate` | `rotated` and `rotated_local`
- `scale` | `scaled` and `scaled_local`
  
Do we need/want to add `translate`, `rotate_local` and `scale_local`, or is it best kept as is? (This might have been discussed already but I didn't review the full discussion in depth, just clarifying before we merge once it has been rebased.)

**Comment by reduz** [comment]
@akien-mga for the exposed API it makes not much of a difference because these types are immutable, but we could have them for consistency.

**Comment by reduz** [comment]
@madmiraal I ran a poll a while ago to ask for preference (with an explanation of what each is for those who dont get it), and then asked people over different social media to have a better understanding on what the expected behavior is and the result is virtual tie on what users expect. So given that contributors appear to prefer having pre transform as default and local transform the alternative one (which reflects the nodes), I think those changes are fine.

https://twitter.com/reduzio/status/1490257961121427457

**Comment by madmiraal** [comment]
@reduz The problem is the current `rotate()` and `scale()` transforms (and with this PR, the `translate()` transform too) do not take place in the global reference frame they take place in the parent reference frame, which is not what the poll asked, and I doubt would be the preferred frame of reference.

It's also worth adding, I don't think there is an easy way to do the transforms in the global reference frame, even if this is what is desired.

**Comment by andre-caldas** [comment]
> https://twitter.com/reduzio/status/1490257961121427457

The poll associates global to "left" and local to "right", giving only two options.

The way that `Node2D` does rotations, for example, is none of those two!!! What `Node2D` does is rotation *left to right", but it only applies it to `column[0]` and `column[1]`, leaving `column[2]` untouched.

If you do it "right to left", the order of operations are reversed:
> t = t.scaled_local(3, 1)
> t = t.rotated_local(90 degrees)

would in practice mean:
1. First rotate 90 degrees.
 2. And after that, do scaling.

I guess `Node2D` is the "natural" approach. It is equivalent to one (not me!) might like to call `basis_rotate`. What <a href="https://github.com/godotengine/godot/blob/edb503cd00614391d14759777c38d8be6d0f20aa/core/math/transform_2d.cpp#L86">`Node2D` uses is `set_rotation`</a>.

**Comment by bluenote10** [comment]
> From a quick review, I noticed that the commit messages don't mention scaled and rotated, this should likely be amended.

I've just rebased and clean-up the history.

Also I've added the corresponding C# implementations, which where missing so far. Is there a unit test suite where I can add something similar to the tests I've added on C++ side to make sure everything is correct? I haven't written any C# in a long time and I'm not super confident I got everything right without any means of checking.

> Do we need/want to add translate, rotate_local and scale_local, or is it best kept as is?

So far only the immutable API (i.e., the past participle "-ed" verbs) is exposed to GDScript, but not the mutable API (the present verb forms), right? I don't have a strong opinion, but for now I'd probably leave the mutable API internal to C++, which means they wouldn't been necessary.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Transform3D.cs [hunk 2]
```diff
@@ -231,11 +263,21 @@ private void SetLookAt(Vector3 eye, Vector3 target, Vector3 up)
...
+            return new Transform3D(basis, origin + offset);
+        }
+
+        /// <summary>
+        /// Translates the transform by the given <paramref name="offset"/>.
+        /// The operation is done in the local frame, equivalent to
+        /// multiplying the matrix from the right.
         /// </summary>
         /// <param name="offset">The offset to translate by.</param>
         /// <returns>The translated matrix.</returns>
```
Comment (bluenote10) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Transform3D.cs:283]: I'm actually a bit surprised by the implementation of `TransledLocal` (a few lines down, I can only comment here). I'm not super familiar with C#, but doesn't the implementation mutate `this` because it writes to `origin`. Since this API is supposed to be an immutable API, I'm wondering if/why it also mutates. It feels like it should be just `+` instead of `+=` or even just `origin + basis.Xform(offset)` instead of manually constructing the three vector elements.

@aaronfranke What's your opinion on that?

Comment (aaronfranke) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Transform3D.cs:283]: @bluenote10 You're right, that's a critical bug that needs fixing.

This bug may have been hidden from us before because if you write `myNode.Transform.Translated(offset)` then C# will operate on a *copy* of the transform. But, if you are working with a local variable, this bug would show up.

Comment (akien-mga) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Transform3D.cs:283]: Needs a rebase after that fix.

**Review by aaronfranke — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]
We agreed to merge this in PR review meeting.

There still seems to be some disagreement from some users on the approach and this might warrant more discussion, but we think what this PR does is a good baseline for further discussion (notably if there's discrepancy between math operations in Transforms and in Nodes).

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Transform3D.cs (hunk 2 above)
Comment (bluenote10) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Transform3D.cs:283]: @akien-mga Sure, done! Just to avoid confusion: The conflict was actually a result of this commit instead https://github.com/godotengine/godot/commit/a4ad1dfa517cf995f8aa5b913ac9726abca620f7 

@aaronfranke's fix was in Transfrom3D.cs not the Transform2D.cs, so I was confused at first...

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Transform2D.cs [hunk 3]
```diff
@@ -307,7 +309,21 @@ public Transform2D Rotated(real_t angle)
...
+        /// Rotates the transform by <paramref name="angle"/> (in radians).
+        /// The operation is done in the local frame, equivalent to
+        /// multiplying the matrix from the right.
+        /// </summary>
+        /// <param name="angle">The angle to rotate, in radians.</param>
+        /// <returns>The rotated transformation matrix.</returns>
+        public Transform2D RotatedLocal(real_t phi)
+        {
+            return new Transform2D(phi, new Vector2()) * this;
+        }
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Transform2D.cs:321]:
```suggestion
        public Transform2D RotatedLocal(real_t angle)
        {
            return new Transform2D(angle, new Vector2()) * this;
        }
```

**Review by raulsntos — CHANGES_REQUESTED** [review]

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Transform3D.cs [hunk 4]
```diff
@@ -207,6 +226,19 @@ public Transform3D Scaled(Vector3 scale)
...
+        /// <summary>
+        /// Scales the transform by the given 3D <paramref name="scale"/> factor.
+        /// The operation is done in the local frame, equivalent to
+        /// multiplying the matrix from the right.
+        /// </summary>
+        /// <param name="scale">The scale to introduce.</param>
+        /// <returns>The scaled transformation matrix.</returns>
+        public Transform3D ScaledLocal(Vector3 scale)
+        {
+            Basis tmpBasis = new Basis(new Vector3(scale.x, 0, 0), new Vector3(0, scale.y, 0), new Vector3(0, 0, scale.z))
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Transform3D.cs:238]: CI is complaining about this line, missed a semicolon.

```suggestion
            Basis tmpBasis = new Basis(new Vector3(scale.x, 0, 0), new Vector3(0, scale.y, 0), new Vector3(0, 0, scale.z));
```

Comment (bluenote10) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Transform3D.cs]: Thanks for the hint, I just realized the mistake as well ;)

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Transform2D.cs (hunk 3 above)
Comment (bluenote10) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Transform2D.cs]: Indeed, I missed that replacement of `phi` => `angle`. I've committed it locally to allow for `--amend` instead of extra commit.

**Review by raulsntos — APPROVED** [review]

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Transform3D.cs [hunk 5]
```diff
@@ -207,6 +226,19 @@ public Transform3D Scaled(Vector3 scale)
...
+        /// <summary>
+        /// Scales the transform by the given 3D <paramref name="scale"/> factor.
+        /// The operation is done in the local frame, equivalent to
+        /// multiplying the matrix from the right.
+        /// </summary>
+        /// <param name="scale">The scale to introduce.</param>
+        /// <returns>The scaled transformation matrix.</returns>
+        public Transform3D ScaledLocal(Vector3 scale)
+        {
+            Basis tmpBasis = new Basis(new Vector3(scale.x, 0, 0), new Vector3(0, scale.y, 0), new Vector3(0, 0, scale.z));
```
Comment (aaronfranke) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Transform3D.cs:238]: Sorry about not having this in sooner, but we could replace this with `Basis.FromScale(scale)` once https://github.com/godotengine/godot/pull/63848 is merged.

**Comment by akien-mga** [comment]
Thanks!
