### PR TITLE
Fixes to 2D viewport

### LINKED ISSUE #40553: Camera3D view visible in 2D editor
**Godot version:**

173ebe487

**Issue description:**

Title.
image
image

**Minimal reproduction project:**

[ReproductionProject.zip](https://github.com/godotengine/godot/files/4950381/ReproductionProject.zip)

### PR DESCRIPTION
**Pull request by reduz**
* Editor 2D viewport now uses embedded subwindows (windows no longer pop up)
* Restored the ability to disable 3D on the 2D viewport (makes 3D not display on 2D when there is a camera on the scene)

*Bugsquad edit:* Fixes #40553

### CODE REVIEW

**Comment by Calinou** [comment]
> Restored the ability to disable 3D on the 2D viewport (makes 3D not display on 2D when there is a camera on the scene)

We may want to expose an option in the 2D editor for this, since seeing a 3D background can sometimes be useful for designing HUDs in real world conditions. This can be done in a future PR.

**Review by clayjohn — APPROVED** [review]

**Comment by KoBeWi** [comment]
> Editor 2D viewport now uses embedded subwindows (windows no longer pop up)

Is it supposed to fix dialog display? Dialogs don't appear at all and windows are like this
image

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -929,6 +929,14 @@ bool Viewport::is_audio_listener_2d() const {
 	return audio_listener_2d;
 }
 
+void Viewport::set_disable_3d(bool p_disable) {
+	disable_3d = p_disable;
+	RenderingServer::get_singleton()->viewport_set_disable_3d(viewport, disable_3d);
+}
+bool Viewport::is_3d_disabled() const {
```
Comment (KoBeWi) [inline scene/main/viewport.cpp:936]:
```suggestion
}

bool Viewport::is_3d_disabled() const {
```

**Comment by reduz** [comment]
@KoBeWi This is mostly because it does not have anything to draw and there is no default theme for embedded windows. Additionally, subwindows/dialogs are not editable(I don't think they ever were). Would be nice if they were but likely all this is material for a separate PR.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
