### PR TITLE
Fixes editor crashing when editing autotiles

### LINKED ISSUE #24004: Godot crashes when editing autotiles
**Godot version:**
3.0.6 stable

**OS/device including version:**
Ubuntu 16.04
GPU:nvidia 750 ti driver: 384.130

**Issue description:**
Program crashes

**Steps to reproduce:**
1. go to Autotiles window
2. select collision tab
3. click the shape button to draw a shape
4. start drawing a shape but don't close it
5. go to bitmask tab
6. go back to collision tab <--- program crashes

 ERROR: operator[]: FATAL: Index p_index=-1 out of size (size()=0)
   At: ./core/dvector.h:505.
handle_crash: Program crashed with signal 4
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7f11ffc814b0] (??:0)
[2] /home/david/godot/Godot_v3.0.6-stable_x11.64() [0xa92857] (??:?)
[3] /home/david/godot/Godot_v3.0.6-stable_x11.64() [0xfe30ab] (<artificial>:?)
[4] /home/david/godot/Godot_v3.0.6-stable_x11.64() [0x700699] (??:?)
[5] /home/david/godot/Godot_v3.0.6-stable_x11.64() [0x1b4ffc3] (??:?)
[6] /home/david/godot/Godot_v3.0.6-stable_x11.64() [0x1b3c9a9] (??:?)
[7] /home/david/godot/Godot_v3.0.6-stable_x11.64() [0x1b3d6c9] (??:?)
[8] /home/david/godot/Godot_v3.0.6-stable_x11.64() [0x1486e24] (<artificial>:?)
[9] /home/david/godot/Godot_v3.0.6-stable_x11.64() [0x700699] (??:?)
[10] /home/david/godot/Godot_v3.0.6-stable_x11.64() [0x1b4ffc3] (??:?)
[11] /home/david/godot/Godot_v3.0.6-stable_x11.64() [0x1ec9a9a] (??:?)
[12] /home/david/godot/Godot_v3.0.6-stable_x11.64() [0x187bf0f] (??:?)
[13] /home/david/godot/Godot_v3.0.6-stable_x11.64() [0x11e0ea6] (??:?)
[14] /home/david/godot/Godot_v3.0.6-stable_x11.64() [0x770eaf] (??:?)
[15] /home/david/godot/Godot_v3.0.6-stable_x11.64() [0x6e97dd] (??:?)
[16] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f11ffc6c830] (??:0)
[17] /home/david/godot/Godot_v3.0.6-stable_x11.64() [0x6f61ce] (??:?)
-- END OF BACKTRACE --

### PR DESCRIPTION
**Pull request by dakennedyd**
Fixes #24004

### CODE REVIEW

File: editor/plugins/tile_set_editor_plugin.cpp [hunk 1]
```diff
@@ -599,7 +599,9 @@ void TileSetEditor::_on_textures_added(const PoolStringArray &p_paths) {
 	}
 }
 
-void TileSetEditor::_on_edit_mode_changed(int p_edit_mode) {
+void TileSetEditor::_on_edit_mode_changed(int p_edit_mode) {
```
Comment (akien-mga) [inline editor/plugins/tile_set_editor_plugin.cpp]: You added a trailing tab here, `clang-format` will complain. See http://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html

**Comment by akien-mga** [comment]
Thanks!
