### PR TITLE
Fix slider handle being hard to select

### LINKED ISSUE #24124: colorpicker's slider is hard to click
**Godot version:**
8dd00ed1762c4956b3231d709ce0d01ee9b306c8

**OS/device including version:**
win 10, 64-bit 

**Issue description:**
when trying to click on the colorpicker's slider, your mouse has to be over the tiny white ball.

example:

imo it'd be a lot easier if the entire circle detected the mouse, not just the inner circle. also, visually your mind thinks it's over the entire ball (but it's not, because it has to be over the inner white circle), makes it harder to click

### PR DESCRIPTION
**Pull request by mawenzy**
Changed the minimum size of a Slider so it depends on the icon used for the grabber. This prevents the behaviour in the issue #24124.

The horizontal/vertical size for a horizontal/vertical slider are kept the same, so the intended sliding behaviour will not be changed.

*Bugsquad edit:* Fixes #24124.

### CODE REVIEW

File: scene/gui/slider.cpp [hunk 1]
```diff
@@ -134,7 +141,10 @@ void Slider::_gui_input(Ref<InputEvent> p_event) {
 void Slider::_notification(int p_what) {
 
 	switch (p_what) {
-
+		case NOTIFICATION_THEME_CHANGED: {
+			minimum_size_changed();
+			update();
+		}
```
Comment (guilhermefelipecgs) [inline scene/gui/slider.cpp]: Missing `break;` here.

**Review by toger5 — APPROVED** [review]
Other than the e-mail it looks good.

**Comment by mawenzy** [comment]
e-mail updated

**Comment by akien-mga** [comment]
Thanks!
