### PR TITLE
Let editor workaround a case of inconsistency in compound scenes

### LINKED ISSUE #26390: It's possible to create two children with the same name
**Godot version:**
3.1 beta8

**Issue description:**
Godot normally auto-renames nodes, so that each child has an unique name. But there's a trick (which I unfortunately discovered in legit way), which allows to create two children with the same name. This leads to weird behaviors, like inability to delete one of them or that selecting one selects both.

**Steps to reproduce:**
1. Create a scene
2. Create another scene (2)
3. Add instance of scene 2 to scene 1
4. Add a child to scene 2's instance in scene 1
5. In scene 2, add a child and name it the same as the instance's child in scene 1
6. Go to scene 1 and now the instance of scene 2 has 2 children of the same name

This is how it looks after enabling editable children:
image

Yeah, I know it's complicated, but as I said, I stumbled into it by accident, so it's not impossible to do unintentionally.

EDIT:
Also possible with inherited scenes.

EDIT:
Another way is to meddle with owners. See #59625

### LINKED ISSUE #77430: Crash on exit in SceneShaderForwardClustered destructor
### Godot version

4.1.dev (094e88416ab84cc4e391703453fb46528739cd69)

### System information

Mageia 9, Linux

### Issue description

I'm seeing a crash on exit in one of my test projects, which seems to be a recent regression.

The crash happens when quitting the 3D gameplay in https://github.com/team-godog/NGJ2023_Godog

There are errors about leaking `GodotBody3D` and `GodotShape3D`, and then leaking two shaders:

```
ERROR: 5 RID allocations of type 'P11GodotBody3D' were leaked at exit.
ERROR: 4 RID allocations of type 'P12GodotShape3D' were leaked at exit.
ERROR: Pages in use exist at exit in PagedAllocator: N33RendererSceneRenderImplementation22RenderForwardClustered32GeometryInstanceSurfaceDataCacheE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
ERROR: Pages in use exist at exit in PagedAllocator: N33RendererSceneRenderImplementation22RenderForwardClustered32GeometryInstanceForwardClusteredE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
ERROR: 2 shaders of type SceneForwardClusteredShaderRD were never freed
   at: ~ShaderRD (servers/rendering/renderer_rd/shader_rd.cpp:708)
ERROR: FATAL: DEV_ASSERT failed  "_first == nullptr" is false.
   at: ~List (./core/templates/self_list.h:114)

Thread 1 "godot-git" received signal SIGILL, Illegal instruction.
0x0000000009c2e943 in SelfList<RendererSceneRenderImplementation::SceneShaderForwardClustered::ShaderData>::List::~List (this=0xd048958, __in_chrg=<optimized out>) at ./core/templates/self_list.h:114
114                             DEV_ASSERT(_first == nullptr);

(gdb) bt
#0  0x0000000009c2e943 in SelfList<RendererSceneRenderImplementation::SceneShaderForwardClustered::ShaderData>::List::~List (this=0xd048958, __in_chrg=<optimized out>) at ./core/templates/self_list.h:114
#1  0x0000000009c29747 in RendererSceneRenderImplementation::SceneShaderForwardClustered::~SceneShaderForwardClustered (this=0xd048958, __in_chrg=<optimized out>)
    at servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp:473
#2  0x0000000009c0fc10 in RendererSceneRenderImplementation::RenderForwardClustered::~RenderForwardClustered (this=0xd046d40, __in_chrg=<optimized out>)
    at servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:4026
#3  0x0000000009b60da2 in memdelete<RendererSceneRenderRD> (p_class=0xd046d40) at ./core/os/memory.h:109
#4  0x0000000009b5f396 in RendererCompositorRD::finalize (this=0xcc78be0) at servers/rendering/renderer_rd/renderer_compositor_rd.cpp:149
#5  0x0000000009a64601 in RenderingServerDefault::_finish (this=0xcc368b0) at servers/rendering/rendering_server_default.cpp:217
#6  0x0000000009a64839 in RenderingServerDefault::finish (this=0xcc368b0) at servers/rendering/rendering_server_default.cpp:244
#7  0x000000000584fee4 in finalize_display () at main/main.cpp:313
#8  0x0000000005868d56 in Main::cleanup (p_force=false) at main/main.cpp:3597
#9  0x00000000057dae8a in main (argc=1, argv=0x7fffffffd688) at platform/linuxbsd/godot_linuxbsd.cpp:75
```

The crash is on a `DEV_ASSERT` (so `dev_build=yes`), might not happen in a non-dev build.

Doesn't happen in 4.0.3-stable, and I don't remember seeing it a couple of weeks ago, so I expect this is a recent regression.

### Steps to reproduce

- Clone https://github.com/team-godog/NGJ2023_Godog
- Edit it with latest Godot `master`, game commit 212feb11867bb4468b357e96756fef40d904e614
- Press "Play", watch the intro (or skip with Esc), wait for the gameplay to start (takes a while to load in a dev build)
- When in game (sliding dog on a slope), press Esc to show the pause menu, and press Quit - it should crash

### Minimal reproduction project

See Steps to reproduce. It's not really minimal, I might try to narrow it down further but this is a relatively simple open source project and I think the regression can be easily pinpointed to recent changes to shader freeing.

CC @BastiaanOlij @clayjohn

### PR DESCRIPTION
**Pull request by RandomShaper**
Fixes #77430.
Fixes #26390.

Marked as _Needs testing_, so please TIWAGOS.

### CODE REVIEW

**Comment by RedworkDE** [comment]
When looking into that issue I also got confused about where the elements of `shader_list` get removed again; it is the `SelfList<>` destructor which is exactly the same as a `remove_from_list` call, so this change does nothing.

Also it definitely doesn't do anything about the core issue of nodes overwriting each other and getting leaked, so I would say this doesn't really fix the issue either way.

**Comment by RandomShaper** [comment]
OK, OK. So I misunderstood what the real issue here is. I'll try harder.

**Comment by RandomShaper** [comment]
@RedworkDE, I've reworked the PR, addressing the actual issue.

Now, unless we are able to identify if there's a broken workflow in Godot that can lead to the inconsistency, this PR is just a way of allowing users to notice and fix and resave their broken scenes. In order not to pay at runtime the cost of working around an odd issue, only the editor will apply the fix.

File: scene/resources/packed_scene.cpp [hunk 1]
```diff
@@ -380,7 +380,27 @@ Node *SceneState::instantiate(GenEditState p_edit_state) const {
...
-						parent->_add_child_nocheck(node, snames[n.name]);
+						Node *existing = nullptr;
+						if (Engine::get_singleton()->is_editor_hint()) {
+							existing = parent->get_node_or_null((String)snames[n.name]);
+						}
+						if (existing) {
+							// There's already a node in the same parent with the same name.
+							// This means that somehow the node was added both to the scene being
+							// loaded and another one instantiated in the former, maybe because of
+							// manual edition, or a bug in scene saving, or a loophole in the workflow
```
Comment (RedworkDE) [inline scene/resources/packed_scene.cpp:391]:
```suggestion
							// manual editing, or a bug in scene saving, or a loophole in the workflow
```

Not which is (more) correct

File: scene/resources/packed_scene.cpp [hunk 2]
```diff
@@ -380,7 +380,27 @@ Node *SceneState::instantiate(GenEditState p_edit_state) const {
...
+							// (with any of the bugs possibly already fixed).
+							// Bring consistency back by letting it be assigned a non-clashing name,
+							// regardless the (broken) intent was not to have a new node, but merely
```
Comment (RedworkDE) [inline scene/resources/packed_scene.cpp:394]: this sentence also seems kinda broken after the regardless

File: scene/resources/packed_scene.cpp [hunk 3]
```diff
@@ -380,7 +380,27 @@ Node *SceneState::instantiate(GenEditState p_edit_state) const {
...
+							// override properties of another one.
+							// This workarouud at least avoids leaks and helps the user realize
```
Comment (RedworkDE) [inline scene/resources/packed_scene.cpp:396]:
```suggestion
							// This workaround at least avoids leaks and helps the user realize
```

**Review by RedworkDE — APPROVED** [review]
Looks good, it is probably fine to not do this check at runtime as you can't instantiate a scene into an existing node anyway and scenes like this shouldn't exist.

One usability nit which I don't think can easily be fixed is that the scene that has been changed to resolve the conflict is not marked as having unsaved changes.

Otherwise works as expected and solved the problem.

File: scene/resources/packed_scene.cpp [hunk 4]
```diff
@@ -380,7 +380,27 @@ Node *SceneState::instantiate(GenEditState p_edit_state) const {
 				//if node was not part of instance, must set its name, parenthood and ownership
 				if (i > 0) {
 					if (parent) {
-						parent->_add_child_nocheck(node, snames[n.name]);
+						Node *existing = nullptr;
+						if (Engine::get_singleton()->is_editor_hint()) {
```
[the remark this answers is not in the document]
Comment (RandomShaper) [reply scene/resources/packed_scene.cpp:384]: `Engine::get_singleton()->is_editor_hint()` is a trivial `return false` if non-tools build. I'd be surprised that compilers wouldn't be able to trim the non-reachable code away.

File: scene/resources/packed_scene.cpp (hunk 2 above)
Comment (RandomShaper) [reply scene/resources/packed_scene.cpp:394]: I've removed that sentence, which is not especially important. But, for the records, this is a rewording of what I meant:
```
// An alternative would be to try to recover the likely original
// intention that the extra node is a reference to another one in an
// instance, and thus is there just to override property values.
```

File: scene/resources/packed_scene.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (RandomShaper) [reply scene/resources/packed_scene.cpp:384]: In any case, I've reformulated the code a bit to augment the chances that the optimization happens.

**Comment by RandomShaper** [comment]
> One usability nit which I don't think can easily be fixed is that the scene that has been changed to resolve the conflict is not marked as having unsaved changes.

That's a very good idea. I'll keep it in my mental _TODO_ list.

File: scene/resources/packed_scene.cpp [hunk 5]
```diff
@@ -380,7 +380,26 @@ Node *SceneState::instantiate(GenEditState p_edit_state) const {
...
+							if (parent->_get_child_by_name(snames[n.name])) {
+								// There's already a node in the same parent with the same name.
+								// This means that somehow the node was added both to the scene being
+								// loaded and another one instantiated in the former, maybe because of
+								// manual editing, or a bug in scene saving, or a loophole in the workflow
+								// (with any of the bugs possibly already fixed).
+								// Bring consistency back by letting it be assigned a non-clashing name.
+								// This simple workaround at least avoids leaks and helps the user realize
+								// something awkward has happened.
+								WARN_PRINT(vformat("Node %s clashes with another one in the scene. It will be renamed. Please fix and re-save the scene.", existing->get_name()).ascii().get_data());
```
Comment (RedworkDE) [inline scene/resources/packed_scene.cpp:394]:
```suggestion
								ERR_PRINT(vformat("Node %s clashes with another one in the scene. It will be renamed. Please fix and re-save the scene '%s'.", existing->get_name(), path));
```
1. I'd say this is an error that requires action to fix and not just a warning that can be ignored
2. Just including the scene path in this error might be enough to make it clear what scene is affected
```
void (*method)(const String &) = ([](const String &p_path) {
	EditorUndoRedoManager::get_singleton()->set_history_as_unsaved(EditorNode::get_singleton()->get_editor_data().get_scene_history_id_from_path(p_path));
});
callable_mp_static(method).call_deferred(path);
```
marks the scene as unsaved, tho it is kinda eh that the call has to be deferred, otherwise I would have said definitely include that line
3. you deleted the `existing` variable that is still used here
4. the `.ascii().data()` is not needed the error macros have overloads that take `String`

Comment (RandomShaper) [reply scene/resources/packed_scene.cpp]: I've changed the way the error is reported so there's no need for a dependency between `packed_scene.*` and editor code.

The new change also kicks off a framework for further polishing in that regard.

File: editor/editor_node.h [hunk 6]
```diff
@@ -731,6 +731,7 @@ class EditorNode : public Node {
 	static bool has_unsaved_changes() { return singleton->unsaved_cache; }
 	static void disambiguate_filenames(const Vector<String> p_full_paths, Vector<String> &r_filenames);
 	static void add_io_error(const String &p_error);
+	static void add_io_warning(const String &p_warning); // For non-fatal errors; also marks scene as unsaved.
```
[the remark this answers is not in the document]
Comment (akien-mga) [reply editor/editor_node.h:734]: Ah I see this PR actually renames the conflicting node, so it needs to be saved.

It seems a bit weird to me to tie this to a generic method to show an I/O warning, as there might be other warnings in the future which don't modify the scene.

[the remark this answers is not in the document]
Comment (RandomShaper) [reply editor/editor_node.h:734]: Indeed. I made it too _ad hoc_. Will refactor.

**Comment by akien-mga** [comment]
CC @KoBeWi who might be interested in this kind of issue too.

I remember past bug report(s) about similar issues getting two siblings with the same name when an instantiated scene also has new children added in its parent scene. But it's a pretty hard combination of generic words to search for, GH search is failing me.

File: editor/editor_node.h (hunk 6 above)
[the remark this answers is not in the document]
Comment (akien-mga) [reply editor/editor_node.h:734]: The comment should be removed too :)

File: scene/resources/packed_scene.cpp [hunk 7]
```diff
@@ -380,7 +384,33 @@ Node *SceneState::instantiate(GenEditState p_edit_state) const {
...
+								// There's already a node in the same parent with the same name.
+								// This means that somehow the node was added both to the scene being
+								// loaded and another one instantiated in the former, maybe because of
+								// manual editing, or a bug in scene saving, or a loophole in the workflow
+								// (with any of the bugs possibly already fixed).
+								// Bring consistency back by letting it be assigned a non-clashing name.
+								// This simple workaround at least avoids leaks and helps the user realize
+								// something awkward has happened.
+								if (instantiation_warn_notify) {
+									instantiation_warn_notify(vformat("An incoming node's name clashes with %s already in the scene (presumably, from a more nested instance).\n"
```
Comment (akien-mga) [inline scene/resources/packed_scene.cpp:401]:
```suggestion
									instantiation_warn_notify(vformat("An incoming node's name clashes with \"%s\" already in the scene (presumably, from a more nested instance).\n"
```

File: scene/resources/packed_scene.cpp [hunk 8]
```diff
@@ -380,7 +384,33 @@ Node *SceneState::instantiate(GenEditState p_edit_state) const {
...
+																	  "The less nested node will be renamed. Please fix and re-save the scene.",
```
Comment (akien-mga) [inline scene/resources/packed_scene.cpp:402]:
```suggestion
																	  "The less nested node has been automatically renamed to resolve the conflict. Please review the changes and re-save the scene.",
```

**Review by akien-mga — APPROVED** [review]
Seems to work well for this use case at least, testing the MRP and the more complex projects from https://github.com/godotengine/godot/issues/77430.

image

File: scene/resources/packed_scene.cpp (hunk 7 above)
Comment (akien-mga) [inline scene/resources/packed_scene.cpp:401]: The message should be enclosed in `RTR()` so it can be extracted and translated.

I believe it doesn't support line breaks so you'll have to keep it all on a single line so it's properly extracted as a single msgid:
```
instantiation_warn_notify(vformat(RTR("An incoming node's name clashes with \"%s\" already in the scene (presumably, from a more nested instance).\nThe less nested node has been automatically renamed to resolve the conflict. Please review the changes and re-save the scene."),
		ret_nodes[0]->get_path_to(existing)));
```

Comment (RandomShaper) [reply scene/resources/packed_scene.cpp]: Added the `RTR()`. However, I've kept the line break since there should be no issue with it; quoting https://en.cppreference.com/w/cpp/language/string_literal:
> String literals placed side-by-side are concatenated at translation phase 6 (after the preprocessor). That is, "Hello,"  " world!" yields the (single) string "Hello, world!".

Comment (RandomShaper) [reply scene/resources/packed_scene.cpp]: I've changed my mind. One thing is C++; another one is the string extractor tool, which I can't find so I verify if this is compatible or not. I will just follow your advice.

File: editor/editor_node.h (hunk 6 above)
[the remark this answers is not in the document]
Comment (akien-mga) [reply editor/editor_node.h:734]: Seems like you missed this one @RandomShaper

File: scene/resources/packed_scene.cpp (hunk 7 above)
Comment (akien-mga) [reply scene/resources/packed_scene.cpp]: Yes the string extraction is done via a Python script which parses line by line: https://github.com/godotengine/godot-editor-l10n/blob/main/scripts/extract_editor.py#L51

Comment (RedworkDE) [reply scene/resources/packed_scene.cpp]: Shouldn't this be `TTR` tho? While it is not in a `#ifdef TOOLS_ENABLED` it is in a `if (is_editor_hint)` so this is still a tools only string. (I may also just be missing something about the translations, in which case disregard this comment)

Comment (akien-mga) [reply scene/resources/packed_scene.cpp]: I think it could be either, both source their translations from the editor translations in priority. I think as a rule we use `RTR` for all `scene` to prevent mistakes where `TTR` would end up used for strings used at runtime.

File: editor/editor_node.h (hunk 6 above)
[the remark this answers is not in the document]
Comment (RandomShaper) [reply editor/editor_node.h]: Done.

File: scene/resources/packed_scene.cpp (hunk 7 above)
Comment (RandomShaper) [reply scene/resources/packed_scene.cpp]: I've changed it to `TTR` since in the latest iterations it's within `#ifdef TOOLS_ENABLED`.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
