### PR TITLE
Double click on scene tree element to focus currently selected node

### LINKED ISSUE #5788: Keyboard shortcut [F] (Center Selection) does not work.
**Operating system or device - Godot version:**
Windows 10 insider preview. Godot steam version (regular version - opt out from betas)

**Issue description** (what happened, and what was expected):
Keyboard shortcut **\[F\]** (Center Selection) does not work. Although it **does** seem to work when "view" menu is opened before using shortcut. **\[Ctrl+F\]** (Frame Selection) works perfectly fine.

**Steps to reproduce:**
focus_misbehaviour

### PR DESCRIPTION
**Pull request by djrm**
In 3D it will focus in the first viewport
Enable double click for trees
closes #5788

### CODE REVIEW

**Comment by vnen** [comment]
Also closes #5791.

File: scene/gui/tree.h [hunk 1]
```diff
@@ -527,6 +530,9 @@ friend class TreeItem;
 
 	void set_value_evaluator(ValueEvaluator *p_evaluator);
 
+	void set_delayed_text_editor_enabled(bool enabled);
+	bool get_delayed_text_editor_enabled() const;
```
Comment (akien-mga) [inline scene/gui/tree.h]: Looking at the rest of the API, I think those names would be better: `set_delayed_text_editor(bool enabled)` and `is_delayed_text_editor_enabled()` (or directly `is_delayed_text_editor` if it's clear enough).
See e.g. http://docs.godotengine.org/en/latest/classes/class_httpclient.html?highlight=enabled#class-httpclient-is-blocking-mode-enabled or http://docs.godotengine.org/en/latest/classes/class_graphedit.html?highlight=enabled#class-graphedit-is-right-disconnects-enabled

**Comment by akien-mga** [comment]
Code looks good, I'll let @djrm reply to my above suggestion but otherwise it can be merged IMO.

File: scene/gui/tree.h (hunk 1 above)
Comment (djrm) [inline scene/gui/tree.h]: well those are shorter and basically used only in the engine so will change to the proposed ones

Comment (reduz) [inline scene/gui/tree.h]: i think there is another option in tree, where you can choose if you want
doubleclick to edit, maybe we should make an enum with options like

EDITOR_ON_CLICK
EDITOR_ON_CLICK_SELECTED
EDITOR_ON_CLICK_SELECTED_DELAYED

Comment (djrm) [inline scene/gui/tree.h]: something like
Tree::set_trigger_edit_mode()

Comment (akien-mga) [inline scene/gui/tree.h]: @djrm Do you still want to change those, or should we merge as is?

Comment (djrm) [inline scene/gui/tree.h]: @akien-mga  mm yeah i changed the functions according to your suggestions but i didn't understand what reduz said, so i will push my changes
