### PR TITLE
Fix infinite call loop on theme change.

### LINKED ISSUE #91553: Changing editor font or theme, cause stack overflow
### Tested versions

4.3 dev (03e6fbb010c3546593bd91a0dabc045a9882705a)

### System information

Windows 11

### Issue description

Changing Main Font or Code Font resulting a crash with the following call stack:

```
>	godot.windows.editor.dev.x86_64.exe!Variant::recursive_hash(int recursion_count) Line 2953	C++
 	godot.windows.editor.dev.x86_64.exe!Variant::hash() Line 2928	C++
 	godot.windows.editor.dev.x86_64.exe!VariantHasher::hash(const Variant & p_variant) Line 826	C++
 	godot.windows.editor.dev.x86_64.exe!HashMap<Vector2i,TextServerAdvanced::FontForSizeAdvanced *,VariantHasher,VariantComparator,DefaultTypedAllocator<HashMapElement<Vector2i,TextServerAdvanced::FontForSizeAdvanced *>>>::_hash(const Vector2i & p_key) Line 85	C++
 	godot.windows.editor.dev.x86_64.exe!HashMap<Vector2i,TextServerAdvanced::FontForSizeAdvanced *,VariantHasher,VariantComparator,DefaultTypedAllocator<HashMapElement<Vector2i,TextServerAdvanced::FontForSizeAdvanced *>>>::_lookup_pos(const Vector2i & p_key, unsigned int & r_pos) Line 106	C++
 	godot.windows.editor.dev.x86_64.exe!HashMap<Vector2i,TextServerAdvanced::FontForSizeAdvanced *,VariantHasher,VariantComparator,DefaultTypedAllocator<HashMapElement<Vector2i,TextServerAdvanced::FontForSizeAdvanced *>>>::has(const Vector2i & p_key) Line 311	C++
 	godot.windows.editor.dev.x86_64.exe!TextServerAdvanced::_ensure_cache_for_size(TextServerAdvanced::FontAdvanced * p_font_data, const Vector2i & p_size) Line 1352	C++
 	godot.windows.editor.dev.x86_64.exe!TextServerAdvanced::_font_get_descent(const RID & p_font_rid, __int64 p_size) Line 2645	C++
 	godot.windows.editor.dev.x86_64.exe!TextServerAdvanced::font_get_descent(const RID & arg1, __int64 arg2) Line 817	C++
 	godot.windows.editor.dev.x86_64.exe!Font::get_height(int p_font_size) Line 197	C++
 	godot.windows.editor.dev.x86_64.exe!EditorProperty::get_minimum_size() Line 72	C++
 	godot.windows.editor.dev.x86_64.exe!Control::_update_minimum_size_cache() Line 1652	C++
 	godot.windows.editor.dev.x86_64.exe!Control::get_combined_minimum_size() Line 1663	C++
 	godot.windows.editor.dev.x86_64.exe!Control::_size_changed() Line 1681	C++
 	godot.windows.editor.dev.x86_64.exe!Control::_notification(int p_notification) Line 3299	C++
 	godot.windows.editor.dev.x86_64.exe!Control::_notificationv(int p_notification, bool p_reversed) Line 48	C++
 	godot.windows.editor.dev.x86_64.exe!Container::_notificationv(int p_notification, bool p_reversed) Line 37	C++
```

### Steps to reproduce

Change Code Font or Main Font in the editor settings.

### Minimal reproduction project (MRP)

No need, requires latest 4.3 build of Godot

### PR DESCRIPTION
**Pull request by ajreckof**
Fixes #91553
Based on [this comment](https://github.com/godotengine/godot/pull/75482#discussion_r1582862095) I had removed `updating_theme` but it seems it is still necessary even with `bulk_theme_override`.

### CODE REVIEW

**Comment by Chaosus** [comment]
Works fine but when switching theme not all elements switching correctly (I don't observe that on 4.3 dev 6):

изображение

**Review by Chaosus — APPROVED** [review]
Perhaps it would be helpful as a quick fix.

**Comment by ajreckof** [comment]
> Works fine but when switching theme not all elements switching correctly (I don't observe that on 4.3 dev 6):
> 
> изображение

Not related to the crash but fixed it as it was also introduced by my modification. While testing realized that `editorPropertyCategory` background is not updated on theme change, tested and it happened even before my modification so left it for later/ maybe there is already a issue / PR for it.

**Comment by KoBeWi** [comment]
Yeah so the reason this is necessary is that EditorPropertyResource adds theme overrides inside its own `NOTIFICATION_THEME_CHANGED` and adding overrides will emit that notification again, resulting in infinite recursion.

I don't think it's valid to set theme overrides inside `NOTIFICATION_THEME_CHANGED` of the same object. The node could connect to `theme_changed` signal of parent inspector instead, to avoid calling theme changes on itself.

File: editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -4354,7 +4354,6 @@ SceneTreeDock::SceneTreeDock(Node *p_scene_root, EditorSelection *p_editor_selec
 	scene_tree->set_v_size_flags(SIZE_EXPAND | SIZE_FILL);
 	scene_tree->connect("rmb_pressed", callable_mp(this, &SceneTreeDock::_tree_rmb));
 
-	scene_tree->connect("node_selected", callable_mp(this, &SceneTreeDock::_node_selected), CONNECT_DEFERRED);
```
Comment (KoBeWi) [inline editor/scene_tree_dock.cpp:4357]: What is this change for?

**Review by KoBeWi — APPROVED** [review]

File: editor/scene_tree_dock.cpp (hunk 1 above)
Comment (ajreckof) [reply editor/scene_tree_dock.cpp]: I pushed a fix to the wrong branch sorry :(

**Comment by ajreckof** [comment]
I updated it to use the parent `theme_changed` signal and since it was becoming too big to do separetly on each `EditorProperty` needing it I implemented it with a simple bool indicating wether it should have borders. it is only implemented to be set at init time. Should I comment on it or should I just make it work at any time with a dedicated setter?

File: editor/editor_inspector.cpp [hunk 2]
```diff
@@ -405,6 +405,17 @@ void EditorProperty::_notification(int p_what) {
...
 		} break;
+		case NOTIFICATION_ENTER_TREE: {
+			if (has_borders) {
+				get_parent()->connect("theme_changed", callable_mp(this, &EditorProperty::_update_property_bg));
+				_update_property_bg();
+			}
+		} break;
+		case NOTIFICATION_EXIT_TREE: {
+			if (has_borders) {
+				get_parent()->disconnect("theme_changed", callable_mp(this, &EditorProperty::_update_property_bg));
```
Comment (KoBeWi) [inline editor/editor_inspector.cpp:416]:
```suggestion
				get_parent()->connect(SNAME("theme_changed"), callable_mp(this, &EditorProperty::_update_property_bg));
				_update_property_bg();
			}
		} break;
		case NOTIFICATION_EXIT_TREE: {
			if (has_borders) {
				get_parent()->disconnect(SNAME("theme_changed"), callable_mp(this, &EditorProperty::_update_property_bg));
```

Comment (ajreckof) [reply editor/editor_inspector.cpp:416]: I'm assuming this is what you meant as the code you suggested didn't seem to work `SceneStringNames::get_singleton()->theme_changed`. Please correct me if this was not what you were suggesting.

Comment (AThousandShips) [reply editor/editor_inspector.cpp]: No I suggested exactly what I suggested, it requires a rebase

Comment (ajreckof) [reply editor/editor_inspector.cpp]: ok it was merged two hours ago that is why I didn't have it. Thanks for clarifying.

**Comment by KoBeWi** [comment]
Property backgrounds don't refresh:
image

**Comment by ajreckof** [comment]
Fixed thanks

**Comment by akien-mga** [comment]
Thanks!
