### PR TITLE
Fix laxist collision detection on one way shapes

### LINKED ISSUE #23491: Adjacent one way collision tiles get deactivated
Godot 3.0

Linux Mint 19.0 GTX 1060 (driver 396.54)

Hi everyone, 
There seems to be an issue when a one way collision shape is attached a tile. When we drop a rigidbody vertically such as it touches two adjacent tiles with a one way collision shape, one of the two tiles gets deactivated and the rigidbody can pass through it.
What is expected is that *both* tiles are activated and rigidbody cannot pass through them. It is worth noting that the tile that gets deactivated seems to be the one that has the largest 'contact surface' with the rigibody.

To reproduce this bug, follow the [TileMap tutorial](https://docs.godotengine.org/en/latest/tutorials/2d/using_tilemaps.html) and just activate 'One Way Collision' to the collision shape that is attached to the second tile (from the left). Then, add a rigibody to the final scene and let it fall on the ground.

Here is a small project that meets this bug.

[TileMaps.zip](https://github.com/godotengine/godot/files/2545392/TileMaps.zip)

### PR DESCRIPTION
**Pull request by Cevantime**
This PR fixes #23491 and possibly others.

The problem was actually more global than indicated in the mentionned issue as the moving body only had to collide and gain some rotation to pass through _any_ one way static body (not only adjacent with an other one and not only in a TileMap).

### CODE REVIEW

**Comment by akien-mga** [comment]
For the reference, this partially reverts 32b1b472af379b3ea3b155a38158f08aed1e92e1 (@reduz), which was a fix for #1854.

File: servers/physics_2d/body_pair_2d_sw.cpp [hunk 1]
```diff
@@ -257,7 +257,7 @@ bool BodyPair2DSW::setup(real_t p_step) {
 	}
 	//faster to set than to check..
```
Comment (madmiraal) [inline servers/physics_2d/body_pair_2d_sw.cpp:259]: While we're about it, I would delete this comment that is not relevant.

**Review by madmiraal — APPROVED** [review]
It definitely solves the issue. :+1:

I can't work out why it was disabled in the first place.

PS As far as I can test, it also does not appear to cause a regression of #1854.

File: servers/physics_2d/body_pair_2d_sw.cpp (hunk 1 above)
Comment (akien-mga) [reply servers/physics_2d/body_pair_2d_sw.cpp:259]: Pushed an amend to do so.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.
