### PR TITLE
Fix GDScript placeholder fallback

### LINKED ISSUE #5603: export vars are lost/reset upon saving a script with a syntax error
**Operating system or device - Godot version:**

Ubuntu 16.04

**Issue description** (what happened, and what was expected):

If you restart the project with an error in the script, then the reset value of the variable in the Inspector.

**Steps to reproduce:**
1. `export var test = 'a'`
2. The inspector 'a' change to 'b'
3. Add a string to simulate errors.
4. `export var test = 'a'
x`
5. Save the project and restart the project.

### PR DESCRIPTION
**Pull request by neikeq**
Fixes #5603

### CODE REVIEW

File: core/script_language.cpp [hunk 1]
```diff
@@ -563,7 +563,8 @@ Variant PlaceHolderScriptInstance::property_get_fallback(const StringName &p_nam
 PlaceHolderScriptInstance::PlaceHolderScriptInstance(ScriptLanguage *p_language, Ref<Script> p_script, Object *p_owner) :
 		owner(p_owner),
 		language(p_language),
-		script(p_script) {
+		script(p_script),
+		build_failed(false) {
```
Comment (neikeq) [inline core/script_language.cpp]: Now that I think of it, It could be a good idea to change `build_failed` to an abstract method in `Script`. It might be cleaner this way, avoiding the loops for updating its value in placeholders.

**Comment by Zireael07** [comment]
Yaaaay! (Yes I do use export vars a lot and in conjunction with tool script, I've been running into the issue this fixes A LOT)

File: core/script_language.cpp (hunk 1 above)
Comment (akien-mga) [reply core/script_language.cpp]: Makes sense to me. CC @vnen

**Comment by akien-mga** [comment]
Thanks!
