### PR TITLE
Handle warped mouse motion as floating point

### LINKED ISSUE #88246: Mouse Input under Wayland misses slow movement
### Tested versions

- Reproducible in: Godot 4.2 dev3 on Gnome Wayland in Fedora 39

### System information

Godot v4.3.dev3.mono - Fedora Linux 39 (Workstation Edition) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (RADV NAVI22) () - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

- I have a Corsair high DPI mouse that is set to high DPI and the movement speed in the OS is reduced.
- When holding right mouse button to nevigate the editor scene and moving the mouse slowly the movement seems to be filtered, like if an float to int conversion is missing all values bellow 1.0.

### Steps to reproduce

1. Setup Mouse with high dpi settings and reduce movement speed in OS.
2. Open Godot with --display-driver wayland.
3. Right click on scene to navigate 
4. move mouse slowly.
5. Then move mouse fast to see that some movement is registered if its fast enough.

### Minimal reproduction project (MRP)

No project is needed to reproduce this issue.

### PR DESCRIPTION
**Pull request by deralmas**
Fixes #88246.

Fixes certain issues where sub-pixel motions would get discarded while the mouse is captured, such as when free look is enabled in the editor (at least when turned on while holding right click).

Very slightly compat breaking, as actual public APIs are changed, although with "compatible" types (Point2i->Point2).

### CODE REVIEW

**Review by bruvzg — COMMENTED** [review]
The rest of the mouse position/movement functions use `Vector2`, so this is more consistent and should not break anything.

But it's strange that sub-pixel mouse movement is possible, is it something related to hiDPI?

File: core/input/input.cpp [hunk 1]
```diff
@@ -865,14 +865,14 @@ Point2i Input::warp_mouse_motion(const Ref<InputEventMouseMotion> &p_motion, con
 	// detect the warp: if the relative distance is greater than the half of the size of the relevant rect
 	// (checked per each axis), it will be considered as the consequence of a former pointer warp.
 
-	const Point2i rel_sign(p_motion->get_relative().x >= 0.0f ? 1 : -1, p_motion->get_relative().y >= 0.0 ? 1 : -1);
-	const Size2i warp_margin = p_rect.size * 0.5f;
-	const Point2i rel_warped(
+	const Point2 rel_sign(p_motion->get_relative().x >= 0.0f ? 1 : -1, p_motion->get_relative().y >= 0.0 ? 1 : -1);
```
Comment (Sauermann) [inline core/input/input.cpp:868]: I am wondering, why `Vector2::sign` is not used (`rel_sign = p_motion->get_relative().sign()`). Perhaps because `0.0f` is not wanted as a output value.

**Review by Sauermann — APPROVED** [review]
I don't see, how this PR is compatibility breaking, because neither `Input::warp_mouse_motion` nor `Node3DEditorViewport::_get_warped_mouse_motion` is exposed to scripting.
Note, that the function `Input::warp_mouse` is exposed to scripting.

Changes make sense to me, but I haven't tested them though.

**Comment by Sauermann** [comment]
> Note that this PR does not change its type. It's related to a different issue reported later.
> 
> Update: I can do that here if you're ok.

I would say, let's keep that for a separate PR.

**Comment by akien-mga** [comment]
Thanks!

**Comment by elvisish** [comment]
I'm using this in 3.5 to ensure mouselook is consistent between window sizes (thanks @kleonc) :
```swift
func xform_the_mouse(event):
	var root: Viewport = get_tree().root
	var input_pre_xform := Transform2D().translated(-OS.window_position).scaled(root.size / OS.get_window_size())
	var transform_to_apply: Transform2D = input_pre_xform.affine_inverse() * root.get_final_transform()
	var event_to_save_the_data_from: InputEvent = event.xformed_by(transform_to_apply)
	return event_to_save_the_data_from.relative
	```
It feels a little like sub-pixel precision is lost when using this instead of the `event.relative` directly, would this be caused by this? And is it only being fixed on the 4.x branch?

**Comment by Calinou** [comment]
> I'm using this in 3.5 to ensure mouselook is consistent between window sizes (thanks @kleonc) :

In 4.3 and later, `event.screen_relative` should be used instead of `event.relative` to get this behavior automatically: https://github.com/godotengine/godot-demo-projects/pull/1055

**Comment by elvisish** [comment]
> > I'm using this in 3.5 to ensure mouselook is consistent between window sizes (thanks @kleonc) :
> 
> 
> 
> In 4.3 and later, `event.screen_relative` should be used instead of `event.relative` to get this behavior automatically: https://github.com/godotengine/godot-demo-projects/pull/1055

Thanks, that's really good to know. I'm still finishing up a project with 3.x so not sure if this will be backported to 3.6 or not.
