### PR TITLE
Mark GDScript and shader warnings for translation

### LINKED ISSUE #107505: Some project settings and export preset settings can't be localized (GDScript and shader warnings, Android export permissions)
### Tested versions

Any version Godot 4, For example Godot 4.4 or Godot 4.5

### System information

Android 11, 2/32 GB Meditek Hello A22, PowerVR G8300, Godot 4.5 dev5

### Issue description

Hello developers, I have a question.
I found even more unfinished translations in your engine. Godot Engine, this is not only for setting up a project for debugging code, but also for exporting to any platform where the application's permission is found.
If anything, I have already fixed this error myself with the reference to the class related to the non-working button in Godot Reference Class, I hope it will work after this change, as I have already done a full check for the reference to the class, and have already fixed it.
So be kind if you can, I'll give you more screenshots than before, because there's still a lot of untranslated text, or it has some unknown errors, or something.Weblate doesn't notice the lines, so I hope you fixed this mistake, because I did my job, so I thank you early.

- anything, I'll give as many screenshots as I can.

- Image

- Image

- Image

- Image

Image

- Image

### Steps to reproduce

Where the project settings, debugging in the scripts, I found unfinished translation of texts.
And also in the export platform, for example Android, I noticed there are still untranslated text from the app permissions, even on any platform where the lines are not translated

### Minimal reproduction project (MRP)

I wasn't on the project itself, because I was on the website, or I noticed it myself on the editor.

### PR DESCRIPTION
**Pull request by KoBeWi**
Resolves #107505

### CODE REVIEW

File: modules/gdscript/gdscript_warning.cpp [hunk 1]
```diff
@@ -194,50 +194,50 @@ String GDScriptWarning::get_name_from_code(Code p_code) {
...
+		PNAME("CONFUSABLE_IDENTIFIER"),
+		PNAME("CONFUSABLE_LOCAL_DECLARATION"),
+		PNAME("CONFUSABLE_LOCAL_USAGE"),
+		PNAME("CONFUSABLE_CAPTURE_REASSIGNMENT"),
+		PNAME("INFERENCE_ON_VARIANT"),
+		PNAME("NATIVE_METHOD_OVERRIDE"),
+		PNAME("GET_NODE_DEFAULT_WITHOUT_ONREADY"),
+		PNAME("ONREADY_WITH_EXPORT"),
 #ifndef DISABLE_DEPRECATED
 		"PROPERTY_USED_AS_FUNCTION",
```
Comment (KoBeWi) [inline modules/gdscript/gdscript_warning.cpp:242]: These are deprecated, so not sure if it's worth touching.

Comment (akien-mga) [reply modules/gdscript/gdscript_warning.cpp:242]: If they're still emitted, they should likely be included too.
If they're no-op and just kept for compat in the enum then yeah we don't need to translate them.

File: platform/android/export/export_plugin.cpp [hunk 2]
```diff
@@ -62,158 +62,158 @@
...
-	"WRITE_PROFILE",
-	"WRITE_SECURE_SETTINGS",
-	"WRITE_SETTINGS",
-	"WRITE_SMS",
-	"WRITE_SOCIAL_STREAM",
-	"WRITE_SYNC_SETTINGS",
-	"WRITE_USER_DICTIONARY",
+	PNAME("ACCESS_CHECKIN_PROPERTIES"),
+	PNAME("ACCESS_COARSE_LOCATION"),
+	PNAME("ACCESS_FINE_LOCATION"),
```
Comment (akien-mga) [inline platform/android/export/export_plugin.cpp]: Does this mean that users will be translating `ACCESS_CHECKIN_PROPERTIES` or the humanized `Access Checkin Properties`? The former is actual code and should likely be kept as is but the user facing Title Cased string would be nice to localize.

Comment (m4gr3d) [reply platform/android/export/export_plugin.cpp]: The Android permissions should not be translated. Those are taken directly from the Android documentation, where they are also no translated regardless of the selected language.

https://developer.android.com/reference/android/Manifest.permission

If that's possible, we should also disable the humanized version of it, and just show the permissions as is.

**Review by m4gr3d — DISMISSED** [review]

File: platform/android/export/export_plugin.cpp (hunk 2 above)
Comment (KoBeWi) [reply platform/android/export/export_plugin.cpp]: The translation applies to humanized version.

File: modules/gdscript/gdscript_warning.cpp (hunk 1 above)
Comment (KoBeWi) [reply modules/gdscript/gdscript_warning.cpp:242]: They don't do anything, but they appear in the settings.
I wonder why do they even exist. It's not like deleting them would break something.

**Comment by KoBeWi** [comment]
Removed Android changes. We don't have a way to disable humanized names for only some properties in the inspector, I think it could be achieved with a new hint.

File: modules/gdscript/gdscript_warning.cpp (hunk 1 above)
Comment (dalexeev) [reply modules/gdscript/gdscript_warning.cpp:242]: Removing a warning code could potentially break someone's script if used in `@warning_ignore`. This is a rather hypothetical case, but still. We decided not to remove deprecated warning codes just in case, at least for now.

But could we try hiding them from Project Settings without removing the warning codes themselves?

Comment (KoBeWi) [reply modules/gdscript/gdscript_warning.cpp:242]: They can be marked as internal, though it has to be hard-coded.

**Comment by akien-mga** [comment]
In #107505 there are also Shader language warnings which seem not to be translated, I assume they can get the same treatment?

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
