### PR TITLE
Make file part of errors/warnings clickable in Output panel

### LINKED ISSUE #1628: Make script paths in Editor Output error messages clickable
**Describe the project you are working on:**
Godot editor plugins (gdscript)

**Describe the problem or limitation you are having in your project:**
clickable

I often get errors in `Output`, which point to scripts with errors, but I need to manually go to these scripts (for example in this case I need to manually find `x.gd` and script list or filesystem and scroll to line 2), which is not convenient.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Making scripts paths clickable in error messages in `Output` would be more convenient than open the script manually.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
One could click on a script path in `Output` and then the script would be opened and scrolled to line specified in the error message.
This could be implemented with adding clickable metas in `case MSG_TYPE_ERROR: {` block of [EditorLog.cpp](https://github.com/godotengine/godot/blob/master/editor/editor_log.cpp#L108), maybe in `MSG_TYPE_WARNING` as well

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No it can't

**Is there a reason why this should be core and not an add-on in the asset library?:**
I tried to make a gdscript plugin that does this.
But this always looked ugly since there are some missing API methods for that.
There is no `get_editor_log()` method
There are no signals to find out if an error is printed.
etc

### LINKED ISSUE #10000: Make console file path errors clickable
### Describe the project you are working on

Any godot project

### Describe the problem or limitation you are having in your project

When Godot detects an error it prints to the console something along the lines of:
> res://addons/phantom_camera/scripts/panel/viewfinder/viewfinder.gd:177 - Parse Error: Identifier "PhantomCameraManager" not declared in the current scope.

I then need to hunt down the file in filesystem (or use quick open shortcut). This is cumbersome.

image

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Support file path links clickable in the console.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Holding control key while hovering mouse over the console should add underlines to file paths and turn them into clickable links. For project paths with line numbers, this should open the linked resource directly at the line specified. For external links, a warning should pop up confirming that the link is external and asking if the user would like to continue.

There are many examples of this being how links are treated in other apps - probably the biggest example being Microsoft Office.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

- Highlight JUST the portion of the file path between res:// and :<line_number>, press ctrl+alt+o and paste then manually scroll to the line number you hopefully remember.
- If you don't know about the Quick Open Script shortcut, painstakingly navigate through all your folders until you find the file in question, manually scroll to the line number you hopefully remember.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a convenience feature for working with errors. It's not project-specific.

### PR DESCRIPTION
**Pull request by mihe**
Fixes godotengine/godot-proposals#1628.
Fixes godotengine/godot-proposals#10000.
Relates to #57896.
Relates to #87216.

This makes the file and line part of error messages in the Output panel clickable, by simply wrapping both in a `[url]` BBCode tag, parsing those URIs in `EditorLog::_meta_clicked` and then opening the file in much the same way as the editor normally would, either in the built-in script editor or external editor, depending on the user's editor settings.

This PR takes a more conservative approach compared to #57896, by not trying to find every possible URL in the log and instead only concerning itself with the thing we already know is a file path, which saves us from any costly/error-prone parsing of the log itself.

One potentially controversial change here is that `EditorLog::_meta_clicked` will now early-out if it gets passed an invalid URI, meaning anything that doesn't start with something like `res:`, `file:`, `mailto:` or whatever else. The reason for this being that errors/warnings emitted from C++ will include relative file paths (e.g. `editor/editor_log.cpp:201`) which I couldn't see an easy way to deal with, and forwarding those to `OS::shell_open` will typically open the user's browser at that (bogus) path, so I opted to have it do nothing instead.

We could of course just not wrap the relative C++ paths in `[url]` to begin with, but again, I wanted to avoid any type of costly/error-prone parsing during logging if possible.

I'm happy to change it back to default to `OS::shell_open` for all non-URIs, but I figure since the express intent of #87216 was to allow for things like `file:` and `mailto:` then this behavior might be desirable anyway.

---

**Contributed by [W4 Games](https://w4games.com)** 🍀

### CODE REVIEW

**Comment by hsvfan-jan** [comment]
This seems to also close https://github.com/godotengine/godot-proposals/issues/10000 I think

edit: seems like you added that to the description while I was making my comment :D

File: editor/editor_log.cpp [hunk 1]
```diff
@@ -196,7 +199,23 @@ void EditorLog::_load_state() {
 }
 
 void EditorLog::_meta_clicked(const String &p_meta) {
-	OS::get_singleton()->shell_open(p_meta);
+	Ref<RegExMatch> uri_match = RegEx(R"(^([a-zA-Z][a-zA-Z0-9+.-]*):(?://)?(.+?)(?::([0-9]+))?$)").search(p_meta);
+	if (!uri_match.is_valid()) {
```
Comment (AThousandShips) [inline editor/editor_log.cpp]:
```suggestion
	if (uri_match.is_null()) {
```

**Comment by ydeltastar** [comment]
> only concerning itself with the thing we already know is a file path

Does this also work for `print_debug()`?

**Comment by mihe** [comment]
> Does this also work for `print_debug()`?

No. Those paths are not added (or otherwise parsed) in `EditorLog`, so would require parsing of the log messages. Same goes for `print_stack()`.

I'd prefer to keep this PR limited to errors/warnings, since that's what the two proposals are about.

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected. Code looks good to me.

image

However, note this only applies to the Output tab. Errors/warnings are only visible if they were printed by the editor, which means only `@tool` scripts will benefit from this change (as errors/warnings printed in the running project appear in the **Debugger > Errors** tab instead).

Also, links to C++ source files will appear to be clickable, but will do nothing when clicked.

**Comment by mihe** [comment]
> which means only `@tool` scripts will benefit from this change

The main motivation for this was being able to click the paths of GDScript parse errors, where this also applies.

> errors/warnings printed in the running project appear in the **Debugger > Errors** tab instead

Indeed, and those are clickable already.

> Also, links to C++ source files will appear to be clickable, but will do nothing when clicked.

Yes, that would be the "potentially controversial change" mentioned in the PR description.

I was toying with the idea of maybe being able to open up GitHub links to the actual file and line for C++ errors, since we should have the commit and everything, but that probably gets messy very quickly, especially when you start involving custom forks, custom modules and godot-cpp errors and whatever else there might be.

**Comment by mihe** [comment]
I forgot to escape `[` in the other `err_str` case. Should be fixed now.

**Comment by KoBeWi** [comment]
> C++ will include relative file paths (e.g. editor/editor_log.cpp:201) which I couldn't see an easy way to deal with, and forwarding those to OS::shell_open will typically open the user's browser at that (bogus) path, so I opted to have it do nothing instead.

`shell_open()` will open the file in default program. You could check if the file exists before making it clickable. Opening cpp files is useful for custom builds.

**Comment by mihe** [comment]
> You could check if the file exists before making it clickable. Opening cpp files is useful for custom builds.

By "before making it clickable" do you mean adding not adding `[url]` to it if it fails the `file_exists` check? Adding I/O (or even syscalls in general) to every logged message seems questionable, even if we're talking about error messages.

If you mean only having it passed to `shell_open` in `_meta_clicked` if it passes `file_exist` there, then sure. They likely wouldn't be absolute paths though, and assuming that the working directory is the root of the source tree seems questionable as well. I've had mine set to either `bin` or the project directory for years now, just to give one example.

I suppose it's easy enough to make the URI scheme optional in the `_meta_clicked` regex and prepend `OS::_execpath` and `..` and test for that path instead. You wouldn't be able to make use of the line number with `shell_open` though, I assume.

**Review by AThousandShips — APPROVED** [review]

**Comment by KoBeWi** [comment]
> By "before making it clickable" do you mean adding not adding [url] to it if it fails the file_exists check? Adding I/O (or even syscalls in general) to every logged message seems questionable, even if we're talking about error messages.

It would only affect messages with file paths. Would it be that expensive? 🤔 For repeating errors it could be cached and the cache can be cleared when clearing output.

**Comment by mihe** [comment]
> For repeating errors it could be cached and the cache can be cleared when clearing output.

Is it really worth the trouble though? I don't find it particularly strange that they're underlined/clickable without anything happening when you click it.

Either way, I'd prefer if that was done in a follow-up PR, assuming it's not deemed a blocker for this one.

**Comment by KoBeWi** [comment]
Ok, I see what's the problem with shell open - the path includes line number. It'd have to be stripped to work properly.

**Comment by Repiteo** [comment]
Thanks!

File: editor/editor_log.cpp [hunk 2]
```diff
@@ -196,7 +199,23 @@ void EditorLog::_load_state() {
 }
 
 void EditorLog::_meta_clicked(const String &p_meta) {
-	OS::get_singleton()->shell_open(p_meta);
+	Ref<RegExMatch> uri_match = RegEx(R"(^([a-zA-Z][a-zA-Z0-9+.-]*):(?://)?(.+?)(?::([0-9]+))?$)").search(p_meta);
+	if (uri_match.is_null()) {
+		return;
+	}
```
Comment (KoBeWi) [inline editor/editor_log.cpp:205]: Why the regex is used here?

Comment (mihe) [reply editor/editor_log.cpp:205]: I'm not quite sure what you're asking. It's used for making sure that we're dealing with a URI (with a line number at the end) and to then parse out the individual components from that URI further down.

Comment (KoBeWi) [reply editor/editor_log.cpp:205]: But this can be achieved without regex, like check if line begins with `res://` and has a colon or whatever. It's not like the log can contain lots of different metas (unless you consider `print_raw()`, but putting URLs is pointless, since they can't be handled on the user side).

II'm asking, because the regex can't handle relative paths and is blocking #111805. I was considering replacing this logic, unless you can provide a regex that works with relative paths 🙃

Comment (mihe) [reply editor/editor_log.cpp:205]: > It's not like the log can contain lots of different metas

The file part of the meta can be in whatever format is used by the error reporter, which is exposed to GDExtension, so can theoretically be anything. Even the format of `__FILE__` (as used by the `ERR_*` macros) is not guaranteed to be consistent across compilers, which I guess you've seen already.

The point of the regex was also in part to fulfill what I assumed #87216 aimed for this meta handler to actually do when it was first added, which was to handle URIs like `file://` and `mailto:`, so I figured anything that isn't a proper URI should be dismissed, as talked about in the PR description. If that's changing with #111805 then by all means change or replace the regex. I have no strong feelings about it.

The fact that Windows absolute paths are slipping through the URI validation to begin with is a bug. I should have disallowed backslashes.
