### PR TITLE
[3.x] Do not fire VisibilityNotifier `screen_entered` and `screen_exited` signals in the Editor

### LINKED ISSUE #40310: Engine crash when VisibilityNotifier::screen_exit() is connected to the parents queue_free()
**Godot version:**
3.2.2

**OS/device including version:**
Win 64

**Issue description:**
Let's say you want a node to despawn when it leaves the screen. So you just add a VisibilityNotifier as a child and connect the screen_exited() signal directly to the queue_free() method of the parent. 
Well apparently that gets called inside the editor or something since as soon as you click on a different tab the engine crashes silently. No erros, not even on verbose mode. 

**Steps to reproduce:**
- Create a scene(tested with an Area root node)
- Add a VisibilityNotifier child
- With the VisibilityNotifier selected choose connect on the screen_exited() signal, click on advanced, select the root of the scene and type queue_free as receiving method
- Switch to a different tab

Expected:
 - The selected tab is beautifully displayed on the viewport

Actual:
 - After a few seconds your desktop background is beautifully displayed, or whatever was behind the editor cause it's gone. 

**Minimal reproduction project:**
[VisibilityCrash.zip](https://github.com/godotengine/godot/files/4908183/VisibilityCrash.zip)

### PR DESCRIPTION
**Pull request by Rubonnek**
Fixes #40310

Update: the linked issue is not present on `master`.

### CODE REVIEW

File: scene/3d/visibility_notifier.cpp [hunk 1]
```diff
@@ -42,6 +42,10 @@ void VisibilityNotifier::_enter_camera(Camera *p_camera) {
 	ERR_FAIL_COND(cameras.has(p_camera));
 	cameras.insert(p_camera);
 
+	if (is_inside_tree() && Engine::get_singleton()->is_editor_hint()) {
+		return;
+	}
+
```
Comment (lawnjelly) [inline scene/3d/visibility_notifier.cpp:48]: These can be wrapped in `#ifdef TOOLS_ENABLED` I think, as this can be compiled out in release non-tools builds.

**Comment by lawnjelly** [comment]
Does it need the `is_inside_tree()`?
Maybe we can just disallow these in editor completely?

File: scene/3d/visibility_notifier.cpp (hunk 1 above)
Comment (Rubonnek) [reply scene/3d/visibility_notifier.cpp:48]: Makes sense. I'll update accordingly.

**Comment by Rubonnek** [comment]
I've updated the PR and also wrapped other code blocks requiring `Engine::get_singleton()->is_editor_hint()` with `TOOLS_ENABLED` to avoid compiling these in release builds.

**Comment by lawnjelly** [comment]
I suspect this would be better as two PRs, one for 3D and one for 2D, which will make these easier to review etc.

Assuming this one stays as 3D, you might simply be able to avoid adding the notifiers to the world in `NOTIFICATION_ENTER_WORLD`, which will prevent a bunch of the processing (and might mean you don't need other checks).

**Comment by Rubonnek** [comment]
@lawnjelly Would you mind reviewing again?

**Review by lawnjelly — APPROVED** [review]
Looks okay from the code. (not tested though).

**Comment by Rubonnek** [comment]
I've tested and I'm not able to reproduce the issue.

**Comment by akien-mga** [comment]
Thanks!
