### PR TITLE
C#: Avoid GodotSharp as project assembly name

### LINKED ISSUE #63041: Naming a project GodotSharp casuses c# scripts not to work.
### Godot version

v3.4.4.stable.mono.official [419e713a2]

### System information

Windows 10

### Issue description

Trying out the c# functionality of Godot I created a project called GodotSharp.
I added a node with a simple c# script.

Upon pressing play in the editor i get the following error in the CMD window and the Debugger>Errors view:
`
E 0:00:02.359   can_instance: Cannot instance script because the class 'Circling' could not be found. Script: 'res://Circling.cs'.
  <C++ Error>   Method failed. Returning: __null
  <C++ Source>  modules/mono/csharp_script.cpp:2892 @ can_instance()
`

### Steps to reproduce

1. Create a new project with the name GodotSharp. 
2. Create a root node and attach a C# script to it.
3. Press Play in the editor.
4. See the error in the console.

Discord user 'the31' figured out that this is due to a clash with a built in DLL.
Changing the project name fixes the issue. 

It would be helpful with better error messaging or even declining to create a project with this name.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by raulsntos**
- The name GodotSharp conflicts with the name of the Godot assembly, this causes a cyclic dependency.
- Fixes https://github.com/godotengine/godot/issues/63041.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by raulsntos** [comment]
That's true, I was thinking it'd be nice to refactor this logic so it's in a single place and then I remembered that you have a similar PR (https://github.com/godotengine/godot/pull/74516).

File: modules/mono/utils/path_utils.cpp [hunk 1]
```diff
@@ -232,10 +232,12 @@ String relative_to(const String &p_path, const String &p_relative_to) {
...
 }
 
+const Vector<String> reserved_assembly_names = { "GodotSharp", "GodotSharpEditor", "Godot.SourceGenerators" };
+
 String get_csharp_project_name() {
-	String name = ProjectSettings::get_singleton()->get_setting_with_override("dotnet/project/assembly_name");
+	String name = GLOBAL_GET("dotnet/project/assembly_name");
 	if (name.is_empty()) {
-		name = ProjectSettings::get_singleton()->get_setting_with_override("application/config/name");
+		name = GLOBAL_GET("application/config/name");
```
Comment (akien-mga) [inline modules/mono/utils/path_utils.cpp:240]: Is there a specific reason not to respect the feature overrides here?

**Review by akien-mga — APPROVED** [review]
Looks great!

**Comment by akien-mga** [comment]
Thanks!
