### PR TITLE
Fixed 6DOF set/get check for the path starting with joint_constraints

### LINKED ISSUE #44320: PhysicalBone 6DOF set/get doesn't check if a property starts with joint_constraints
**Godot version:**
```
3.2.3.stable.custom_build.662455ee8
```

**OS/device including version:**
```
$ uname -a
Linux pc 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
```

**Issue description:**
`PhysicalBone` doesn't check whether the first part of a property is `"joint_constraints"` in `set` and `get` if `joint_type == JOINT_TYPE_6DOF`

https://github.com/godotengine/godot/blob/0762484473c1330c5d524d5cc3644d5e2b2e557c/scene/3d/physics_body_3d.cpp#L1712-L1866

https://github.com/godotengine/godot/blob/0762484473c1330c5d524d5cc3644d5e2b2e557c/scene/3d/physics_body_3d.cpp#L1868-L1938

**Steps to reproduce:**
Change `PhysicalBone` to `PhysicalBone3D` for Godot 4.0

```gdscript
extends SceneTree


var bone = PhysicalBone.new()
var t = 0


func _init():
	bone.joint_type = bone.JOINT_TYPE_6DOF
	root.add_child(bone)


func _idle(_delta):
	var x = bone.get("blahblah/x/angular_limit_upper")
	print(x)
	t += 1
	bone.set("foo/x/angular_limit_upper", t)
```

**Minimal reproduction project:**
See above

### PR DESCRIPTION
**Pull request by HipsterPenguin**
New code simply checks whether or not property has joint_constraints as the first part of a property's path.
This fixes the bug mentioned in #44320.

*Bugsquad edit:* fixes #44320.

### CODE REVIEW

File: scene/3d/physics_body_3d.cpp [hunk 1]
```diff
@@ -1716,6 +1716,9 @@ bool PhysicalBone3D::SixDOFJointData::_set(const StringName &p_name, const Varia
 
 	String path = p_name;
 
+	if (path.get_slicec('/', 0) != "joint_constraints")
+		return false;
```
Comment (akien-mga) [inline scene/3d/physics_body_3d.cpp:1720]: You should use braces around the `if`'s block.

**Comment by akien-mga** [comment]
Could you squash the two commits into one? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase)).

**Review by pouleyKetchoupp — CHANGES_REQUESTED** [review]
This works well! I would just use `if (!path.begins_with("joint_constraints/"))` instead for the condition. It's an exact equivalent, but it avoids constructing a new `String` (return value from `get_slicec`) and doing an extra String comparison.

**Comment by HipsterPenguin** [comment]
Alright, I think I squashed the commits, sorry about any issues as I am new to this. (I'm sure you could tell). Let me know if there is anything else to fix and thank you for your reviews!

**Review by pouleyKetchoupp — APPROVED** [review]

**Review by AndreaCatania — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
