### PR TITLE
Keep property values when extending script

### LINKED ISSUE #4415: Don't clear export vars of a scene/node on new script
### Describe the project you are working on

A 2D UI driven RPG game with focus on deep progression.

### Describe the problem or limitation you are having in your project

When in a scene-tree i have a scene/node that has a script attached to it and on that node i have data in the exported vars of that script. Now when i Drag a new script on this (which maybe has the same base-parent) or right click and do a "Extend script" all the data i added to the node is cleared.

At this point i then have to either go and type everything into the fields in the exporter again or use my VCS tool to revert the deletion of those lines in the .tscn:

https://user-images.githubusercontent.com/24807557/163812942-55729e1d-2fcc-4f8f-acce-9cbd15350c66.mp4

This is cumbersome and just creates extra steps. Especially painful when i didnt push/commit my changes for a bit and i do it on a scene thats not in the vcs yet, then all the input data is just lost.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The current behaviour:
1 attached new script to a node 
2 clear all script-vars

The expected/preferred behaviour:
1 attached new script to a node
2 check if the new script extends the old script -> keep the values in the .tscn
3 clear unneeded/unused vars from the .tscn

Alternatively:
- check if the new script has fields/vars which fit with the saved vars from the previous script (but this could create some different problems) -> here there could be a popup of like "Hey, do you want to keep the previous script-vars?" which would popup when the player does extend the script or attach a new script via drag and drop.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See the step above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not as far as i know of.

### Is there a reason why this should be core and not an add-on in the asset library?

It improves the editor-flow and feels like an artificial/unnecessary bump in the development-process. So maybe there could be an addon that lessens the problem or creates workarounds, but none that i know of.

### LINKED ISSUE #37480: Extending a GDScript on a node clears the exported script variables.
**Godot version:** 3.2.1 / master (a2da99f40cf2123c0906c734a2eb01e9b65a45a2)

**OS/device including version:** Windows 10

**Issue description:**
Using Extend Script on a node with an attached script (notably scripts with `class_name`s and hence appearing as types in Add Child dialogs) clears the existing script variables on the node.

**Steps to reproduce:**
* Provided Reproduction
  * Create a script with `class_name`s (`A`).
  * Create a new node with with the type
* Extend the node with the attached script.

**Minimal reproduction project:** [TempTest.zip](https://github.com/godotengine/godot/files/4412229/TempTest.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Closes #37480
EDIT: Closes https://github.com/godotengine/godot-proposals/issues/4415

~~This can also trigger when replacing a script for one node. Making it work only with script extending would make the code more complicated, because the editor doesn't really differentiate between extending and attaching. I don't think this is a big issue.~~

I added 2 methods in EditorNode:
`store_object_properties()` and `apply_object_properties()`. The first one gets properties from the script instance and stores it in EditorNode, the second one applies it to the new instance, to the properties that have matching name and type. The intended usage is that you call these methods as part of a UndoRedo action that changes script and the exported values are carried to the new script.

The values will be preserved when:
- extending script
- making script unique
- attaching a new script
- if you know any other action that can potentially clear exported variables, please comment

### CODE REVIEW

**Comment by KoBeWi** [comment]
I rebased and improved the PR.

Aside from extending script, the properties will now be kept when making the script unique or attaching a new one (regardless if it's the same script or a completely different one; properties with the same name will keep values).

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -2099,6 +2099,29 @@ void EditorNode::edit_item(Object *p_object) {
 	}
 }
 
+void EditorNode::store_object_properties(Object *p_object) {
```
Comment (reduz) [inline editor/editor_node.cpp:2102]: I think you cold put this in InspectorDock rather than EditorNode to avoid further bloating this.

Comment (reduz) [reply editor/editor_node.cpp:2102]: I think the function could also be renamed to store_script_properties?

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -2099,6 +2099,29 @@ void EditorNode::edit_item(Object *p_object) {
...
+	ERR_FAIL_NULL(p_object);
+	if (ScriptInstance *si = p_object->get_script_instance()) {
```
Comment (reduz) [inline editor/editor_node.cpp:2104]: Lets avoid assignments in if conditions, they look really confusing.

File: editor/editor_node.cpp [hunk 3]
```diff
@@ -5808,6 +5831,9 @@ void EditorNode::_bind_methods() {
 	ClassDB::bind_method("_close_messages", &EditorNode::_close_messages);
 	ClassDB::bind_method("_show_messages", &EditorNode::_show_messages);
 
+	ClassDB::bind_method("store_object_properties", &EditorNode::store_object_properties);
```
Comment (reduz) [inline editor/editor_node.cpp:5834]: IMO This function should only be called if you have a script, so the intention is better. Otherwise you have to go to the function and see that it does nothing if it has a script.

**Review by reduz — CHANGES_REQUESTED** [review]

File: editor/editor_node.cpp (hunk 2 above)
Comment (KoBeWi) [reply editor/editor_node.cpp:2104]: :(

File: editor/editor_node.cpp (hunk 3 above)
Comment (KoBeWi) [reply editor/editor_node.cpp:5834]: Nah, the function is supposed to store available script properties. If there is no script, it just has no properties to store.

It makes the code much simpler. Otherwise I'd have to wrap each call and make it less readable.

**Review by reduz — APPROVED** [review]

File: editor/inspector_dock.cpp [hunk 4]
```diff
@@ -452,6 +452,9 @@ void InspectorDock::_bind_methods() {
 	ClassDB::bind_method("_menu_expandall", &InspectorDock::_menu_expandall);
 
 	ClassDB::bind_method("edit_resource", &InspectorDock::edit_resource);
+
```
Comment (akien-mga) [inline editor/inspector_dock.cpp:455]: Trailing whitespace?

**Comment by akien-mga** [comment]
Thanks!

**Comment by timothyqiu** [comment]
Cherry-picked for 3.6

File: editor/scene_tree_dock.cpp [hunk 5]
```diff
@@ -1952,17 +1952,36 @@ void SceneTreeDock::_script_created(Ref<Script> p_script) {
...
+			editor_data->get_undo_redo().add_undo_method(InspectorDock::get_singleton(), "store_script_properties", E->get());
+			editor_data->get_undo_redo().add_do_method(E->get(), "set_script", p_script);
+			editor_data->get_undo_redo().add_undo_method(E->get(), "set_script", existing);
+			editor_data->get_undo_redo().add_do_method(InspectorDock::get_singleton(), "apply_script_properties", E->get());
+			editor_data->get_undo_redo().add_undo_method(InspectorDock::get_singleton(), "apply_script_properties", E->get());
+			editor_data->get_undo_redo().add_do_method(this, "_update_script_button");
+			editor_data->get_undo_redo().add_undo_method(this, "_update_script_button");
+		}
+		editor_data->get_undo_redo().commit_action();
 	}
```
Comment (timothyqiu) [inline editor/scene_tree_dock.cpp:1983]: When cherry-picking, I noticed that this `if` branch seems unnecessary. The for loop also works when `selected` has only one element.
