### PR TITLE
Fix downsampled radiance map generation

### LINKED ISSUE #113676: Stretch marks and artifacts on environment octmaps
### Tested versions

- Reproducible in 4.6-dev6

### System information

Godot v4.6.dev6 - Windows 10 (build 19045) - Multi-window, 2 monitors - Direct3D 12 (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti (NVIDIA; 32.0.15.6636) - AMD Ryzen 9 5900X 12-Core Processor (24 threads) - 63.91 GiB memory

### Issue description

The new octahedral environment maps exhibit visible stretch/dot-like artifacts on rough materials, despite texture array reflections being enabled:

Image
Image

The radiance map as seen in RenderDoc:
Image

### Steps to reproduce

- Open the MRP,
- Open node_3d.tscn

### Minimal reproduction project (MRP)

[radiance-bad.zip](https://github.com/user-attachments/files/23981388/radiance-bad.zip)

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/113676
The "high quality" mode was mostly fixed by https://github.com/godotengine/godot/pull/114279 and this fixes the issue that @BlueCube3310 noted with the fast filter path

There were a couple of problems with the fast filter path introduced by https://github.com/godotengine/godot/pull/107902:
1. The downsampled radiance map had too many mipmaps leading to the lowest level having really poor quality
2. The fast filter path didn't use the high quality path, so extremely bright pixels had a random chance of bleeding through
3. The Jacobian approximation used the wrong input coordinates, so it wasn't helpful at all

This PR looks scary, but most of the code changes are just removing the `DOWNSAMPLER_MODE_FLAG_HIGH_QUALITY` since we should always use the more advanced mipmapping approach (as we did previously). For high frequency skies (like in https://github.com/godotengine/godot/issues/114750) it is absolutely necessary. 

_Before_

Screenshot from 2026-01-12 21-12-42

fast-filter-before

_After_

Screenshot from 2026-01-12 21-14-19

fast-filter-after

### CODE REVIEW

File: servers/rendering/renderer_rd/environment/sky.cpp [hunk 1]
```diff
@@ -340,7 +340,7 @@ void SkyRD::ReflectionData::update_reflection_data(int p_size, int p_mipmaps, bo
 	tf.format = p_texture_format;
 	tf.width = p_low_quality ? 160 : p_size >> 1; // Always 160x160 when using REALTIME.
 	tf.height = p_low_quality ? 160 : p_size >> 1;
-	tf.mipmaps = p_low_quality ? 7 : mipmaps - 1;
+	tf.mipmaps = p_low_quality ? 5 : mipmaps - 1;
```
Comment (blueskythlikesclouds) [inline servers/rendering/renderer_rd/environment/sky.cpp:343]: Just double checking, does this value here have any relevancy to the one updated in #114281?

Comment (clayjohn) [reply servers/rendering/renderer_rd/environment/sky.cpp:343]: Kind of. Its not directly related in the sense that it should have been updated in https://github.com/godotengine/godot/pull/114281, but the mip sizes here do correspond to mip levels 2-6 of the main radiance texture. 

The sizes should basically align with the main texture, but there is no requirement that they have the same number of mips or anything. Hypothetically, this one _could_ have more or less and still function fine. The only requirement is that we use the same border width ratio

**Review by BlueCube3310 — APPROVED** [review]
Looks really good, while there are still some artifacts on highly contrasting HDRi, the 'patches' no longer appear:
Before:
old

After:
new

**Comment by BlueCube3310** [comment]
It's this one: https://polyhaven.com/a/rosendal_park_sunset

**Comment by akien-mga** [comment]
Thanks!
