### PR TITLE
Validate physical light units in GI classes.

### LINKED ISSUE #65586: Vulkan: Broken colors when baking LightmapGI
### Godot version

4.0.dev (ce6f284e5ff16794658db4ccd265b9c71f6b62b2)

### System information

Windows 10 64-bit, Vulkan Clustered, NVIDIA RTX 2080, Driver version 497.09

### Issue description

I was trying to debug another issue related to lightmap baking. I created a simple MRP which creates a very broken bake texture:
image

### Steps to reproduce

- Create a simple .blend file for the scene - mark it for lightmap bake
- Add directional light node to be baked
- Create LightmapGI, set camera attributes, reduce quality to Low
- Bake and look at the results

### Minimal reproduction project

[lightmap_corruption.zip](https://github.com/godotengine/godot/files/9538122/lightmap_corruption.zip)

### PR DESCRIPTION
**Pull request by clayjohn**
Add checks for physical light units in a few more places to ensure they aren't used when disabled.

Fixes: https://github.com/godotengine/godot/issues/65586

### CODE REVIEW

File: scene/3d/lightmap_gi.cpp [hunk 1]
```diff
@@ -1001,10 +1001,16 @@ LightmapGI::BakeError LightmapGI::bake(Node *p_from_node, String p_image_data_pa
 				lightmapper->add_directional_light(light->get_bake_mode() == Light3D::BAKE_STATIC, -xf.basis.get_column(Vector3::AXIS_Z).normalized(), linear_color, energy, l->get_param(Light3D::PARAM_SIZE), l->get_param(Light3D::PARAM_SHADOW_BLUR));
 			} else if (Object::cast_to<OmniLight3D>(light)) {
 				OmniLight3D *l = Object::cast_to<OmniLight3D>(light);
-				lightmapper->add_omni_light(light->get_bake_mode() == Light3D::BAKE_STATIC, xf.origin, linear_color, energy * (1.0 / (Math_PI * 4.0)), l->get_param(Light3D::PARAM_RANGE), l->get_param(Light3D::PARAM_ATTENUATION), l->get_param(Light3D::PARAM_SIZE), l->get_param(Light3D::PARAM_SHADOW_BLUR));
+				if (GLOBAL_GET("rendering/lights_and_shadows/use_physical_light_units")) {
```
Comment (BastiaanOlij) [inline scene/3d/lightmap_gi.cpp:1004]: Do I read this change correctly and was physical lighting the default before? Or should there be a calculation applied to energy when physical lighting is turned off?

**Comment by BastiaanOlij** [comment]
We're already doing this everywhere but I wonder if there is a better way to access our setting then copying the `GLOBAL_GET("rendering/lights_and_shadows/use_physical_light_units")` code everywhere. I was always told to prevent this and instead have a method that can be called to retrieve the value and retrieve it in one place. No idea if that is practical here..

**Review by BastiaanOlij — APPROVED** [review]
I don't know if the calculation is what it should be but code wise this looks fine to me to merge.

File: scene/3d/lightmap_gi.cpp (hunk 1 above)
Comment (clayjohn) [reply scene/3d/lightmap_gi.cpp:1004]: There should not be a calculation applied when physical lighting is turned off. I accidently left the unit conversion in when making the original PR. But the unit conversion is only applicable when using physical light units. This bug resulted in OmniLights appearing too dark in baked lighting when PLU is turned off.

**Comment by akien-mga** [comment]
Thanks!
