### PR TITLE
Disallow clicking to toggle the checkbox of a theme override of type `Resource` to checked

### LINKED ISSUE #109389: Default font theme override always embeds itself as sub-resource
### Tested versions

- Reproducible in: 4.5.beta [65eb6643522abbe8ebce6428fe082167a7df14f9], 4.5.dev [3bc2821e261cc1e53ac2fcfd3ad930ae35b59b17]
- Not reproducible in: 4.4.1.stable, 4.5.dev [1d8fa8b58a081b677dea42d16eb8d1361171ed71]

### System information

Godot v4.5.beta (65eb66435) - Fedora Linux 42 (Adams) on Wayland - X11 display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 9070 XT (RADV GFX1201) - AMD Ryzen 9 9950X3D 16-Core Processor (32 threads) - 60.39 GiB memory

### Issue description

We've run into a couple of cases now where content creators will end up pushing hundreds of kilobytes (and sometimes megabytes) of font data as part of their scene files without realizing it. Upon further investigation it would seem that the thing they have in common is they all embed/sub-resource the Open Sans SemiBold font (i.e. `thirdparty/fonts/OpenSans_SemiBold.woff2`) that Godot uses as its default font, and that it's always attached to the `theme_override_fonts/font` property of something like a `Label`.

We're not totally clear on how these font properties were left at their default values, but there's a fairly straight-forward repro for this, which is to simply check the "Font" checkbox under "Theme Overrides" for any `Control` and then save the scene without actually picking a different font. This leads to the default font being embedded as a sub-resource in the scene.

This would seem to be a regression caused by #102372, which made it so that you could actually see the effective defaults for the theme overrides, and also made it so you could just check the override checkboxes without actually setting a value first. This is unlike Godot 4.4 where you had to pick a font in order to enable the font override.

### Steps to reproduce

1. Open any scene in any project.
2. Create one or more `Label`.
3. Check their "Font" checkbox under the "Theme Overrides" properties.
4. Save the scene.
5. Open the scene in a text editor.
6. Note how you have one `sub_resource type="FontFile"` for every `Label`.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Rindbee**
These resources are external, but can be further categorized as follows:

1. Imported resource;
2. Embedded resource (no resource path, provided by the engine);
3. Other text-based resource.

Resources of different categorie may need different strategies.

Currently, for resource types, it is up to the user to decide what to do next.  Clicking to toggle checkboxes is not allowed, but you can still manipulate resources through the `EditorResourcePicker`'s context menu (right-click on a resource in the inspector or click the down arrow icon next to the resource to open the menu).

Fix #109389.

### CODE REVIEW

**Comment by mihe** [comment]
While this is arguably better than not letting the user know at all, I suspect this change will instead lead to content creators seeing a warning every time they go to change the font on something like a `RichTextLabel`, because they will likely always check the override checkbox before going to select the font. This strikes me as a somewhat unfortunate user experience, and I would be surprised if not more people start complaining if/when we merge this, given that the theme override is the de facto way you typically change fonts for something like `RichTextLabel`.

The messages themselves could probably be phrased in some better way as well. I don't think people will necessarily know/understand that manually checking the override checkbox for resource-backed properties ends up duplicating the entire resource, so a warning message mentioning some attempt to copy an embedded resource and asking them to save it somewhere else, when all you did was check the override checkbox, might not get through.

I can't help but feel like the better short-term change is to disallow the manual checking of the override checkbox for resource-backed properties altogether. If somebody absolutely wants a copy of the resource embedded/sub-resourced then they could presumably use Make Unique on the default/fallback resource. That would however mean that there's a somewhat weird discrepancy between non-resource properties and resource-backed properties, but that still feels like the "lesser evil" here.

**Comment by Rindbee** [comment]
Perhaps in the future we can consider applying different hints (icons or colors) to these categories in `EditorResourcePicker` instead of using `resource_path` for judgment.

**Comment by mihe** [comment]
These latest changes do seem a lot better, to me at least.

The fact that resource properties now behave differently from non-resource properties does (as mentioned already) seem a bit weird, but seeing as how this was largely the behavior of the theme override properties pre-4.5 then I assume it shouldn't be too jarring for people already familiar with them at least.

(You might want to edit the PR description to reflect these changes.)

**Comment by KoBeWi** [comment]
It would be nice if pressing the checkbox did not register undo action and mark the scene as modified. It's confusing if you click the button (with click feedback), but nothing really happens. Maybe a toast warning could show at least.

**Comment by Rindbee** [comment]
https://github.com/user-attachments/assets/cb9ebe91-aaae-487a-8279-75b8e4409b17

Already modified as suggested.

File: editor/inspector/editor_inspector.cpp [hunk 1]
```diff
@@ -29,6 +29,7 @@
 /**************************************************************************/
 
 #include "editor_inspector.h"
+#include "editor/gui/editor_toaster.h"
```
Comment (AThousandShips) [inline editor/inspector/editor_inspector.cpp]: Goes below with the other includes, the includes at the top should just be the base header and a possible compat include

File: editor/inspector/editor_inspector.cpp [hunk 2]
```diff
@@ -1080,6 +1091,17 @@ void EditorProperty::gui_input(const Ref<InputEvent> &p_event) {
 void EditorProperty::_accessibility_action_click(const Variant &p_data) {
 	select();
 	if (checkable) {
+		if (!checked && Object::cast_to<Control>(object) && property_path.begins_with("theme_override_")) {
+			List<PropertyInfo> pinfo;
+			object->get_property_list(&pinfo);
+			for (const PropertyInfo &E : pinfo) {
+				if (E.name == property_path && E.type == Variant::OBJECT) {
```
Comment (KoBeWi) [inline editor/inspector/editor_inspector.cpp]: Cheaper first.
```suggestion
				if (E.type == Variant::OBJECT && E.name == property_path) {
```

File: editor/inspector/editor_inspector.cpp [hunk 3]
```diff
@@ -1080,6 +1091,17 @@ void EditorProperty::gui_input(const Ref<InputEvent> &p_event) {
...
+					EditorToaster::get_singleton()->popup_str(TTR("Disallow clicking to toggle the checkbox of type Resource to checked. Please assign the value through other means."), EditorToaster::SEVERITY_WARNING);
```
Comment (KoBeWi) [inline editor/inspector/editor_inspector.cpp]:
```suggestion
					EditorToaster::get_singleton()->popup_str(TTR("Toggling the checkbox is disabled for Resource properties. Modify the property via resource picker instead."), EditorToaster::SEVERITY_WARNING);
```

**Review by KoBeWi — APPROVED** [review]

File: editor/inspector/editor_inspector.cpp [hunk 4]
```diff
@@ -5176,6 +5190,7 @@ void EditorInspector::_property_checked(const String &p_path, bool p_checked) {
 					}
 				}
 			}
+
```
Comment (AThousandShips) [inline editor/inspector/editor_inspector.cpp]: Unrelated and noisy in git history, please restore

File: editor/inspector/editor_inspector.cpp [hunk 5]
```diff
@@ -1062,6 +1063,16 @@ void EditorProperty::gui_input(const Ref<InputEvent> &p_event) {
 
 		if (check_rect.has_point(mpos)) {
 			accept_event();
+			if (!checked && Object::cast_to<Control>(object) && property_path.begins_with("theme_override_")) {
+				List<PropertyInfo> pinfo;
+				object->get_property_list(&pinfo);
+				for (const PropertyInfo &E : pinfo) {
+					if (E.type == Variant::OBJECT && E.name == property_path) {
+						EditorToaster::get_singleton()->popup_str(TTR("Toggling the checkbox is disabled for Resource properties. Modify the property via resource picker instead."), EditorToaster::SEVERITY_WARNING);
```
Comment (AThousandShips) [inline editor/inspector/editor_inspector.cpp]:
```suggestion
						EditorToaster::get_singleton()->popup_str(TTR("Toggling the checkbox is disabled for Resource properties. Modify the property using the resource picker instead."), EditorToaster::SEVERITY_WARNING);
```

File: editor/inspector/editor_inspector.cpp [hunk 6]
```diff
@@ -1080,6 +1091,17 @@ void EditorProperty::gui_input(const Ref<InputEvent> &p_event) {
 void EditorProperty::_accessibility_action_click(const Variant &p_data) {
 	select();
 	if (checkable) {
+		if (!checked && Object::cast_to<Control>(object) && property_path.begins_with("theme_override_")) {
+			List<PropertyInfo> pinfo;
+			object->get_property_list(&pinfo);
+			for (const PropertyInfo &E : pinfo) {
+				if (E.type == Variant::OBJECT && E.name == property_path) {
+					EditorToaster::get_singleton()->popup_str(TTR("Toggling the checkbox is disabled for Resource properties. Modify the property via resource picker instead."), EditorToaster::SEVERITY_WARNING);
```
Comment (AThousandShips) [inline editor/inspector/editor_inspector.cpp]:
```suggestion
					EditorToaster::get_singleton()->popup_str(TTR("Toggling the checkbox is disabled for Resource properties. Modify the property using the resource picker instead."), EditorToaster::SEVERITY_WARNING);
```

**Review by AThousandShips — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
