### PR TITLE
Propagate errors when creating an OpenGL context fails in X11

### LINKED ISSUE #74522: Godot crashing after failing to obtain an OpenGL context when OpenGL 3.3 is not supported
### Godot version

4.0

### System information

ubuntu 22.04 x64 intel dual core 4gb ram

### Issue description

Godot Engine v4.0.stable.official.92bee43ad - https://godotengine.org
```
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  0 ()
  Serial number of failed request:  29
  Current serial number in output stream:  29
ERROR: BUG: Unreferenced static string to 0: interface_added
   at: unref (core/string/string_name.cpp:131)
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  0 ()
  Serial number of failed request:  29
  Current serial number in output stream:  29
ERROR: BUG: Unreferenced static string to 0: interface_added
   at: unref (core/string/string_name.cpp:131)
ERROR: Condition "ctxErrorOccurred || !gl_display.context->glx_context" is true. Returning: ERR_UNCONFIGURED
   at: _create_context (platform/linuxbsd/x11/gl_manager_x11.cpp:176)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.stable.official (92bee43adba8d2401ef40e2480e53087bcb1eaf1)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f98ec842520] (??:0)
[2] ./Godot_v4.0-stable_linux.x86_64() [0xe8cad5] (??:0)
[3] ./Godot_v4.0-stable_linux.x86_64() [0xe9b06d] (??:0)
[4] ./Godot_v4.0-stable_linux.x86_64() [0xe9bf3e] (??:0)
[5] ./Godot_v4.0-stable_linux.x86_64() [0x49e3051] (??:0)
[6] ./Godot_v4.0-stable_linux.x86_64() [0xe09825] (??:0)
[7] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f98ec829d90] (??:0)
[8] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f98ec829e40] (??:0)
[9] ./Godot_v4.0-stable_linux.x86_64() [0xe2286e] (??:0)
-- END OF BACKTRACE --
================================================================
Abortado
```

### Steps to reproduce

$ ./Godot_v4.0-stable_linux.x86_64

### Minimal reproduction project

no

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/74522

We silently ignored the error return by ``_create_context()`` so window initialization continued even when we failed to create an OpenGL 3.3 context. This PR propagates the error up the chain so that our existing error handling can properly stop initialization and alert the user. 

So now, instead of crashing, users will see:

Screenshot from 2023-03-07 09-22-58

### CODE REVIEW

File: platform/linuxbsd/x11/display_server_x11.cpp [hunk 1]
```diff
@@ -4873,7 +4873,9 @@ DisplayServerX11::WindowID DisplayServerX11::_create_window(WindowMode p_mode, V
 
 #ifdef GLES3_ENABLED
 	if (gl_manager) {
-		visualInfo = gl_manager->get_vi(x11_display);
+		Error err;
+		visualInfo = gl_manager->get_vi(x11_display, err);
+		ERR_FAIL_COND_V_MSG(err != OK, INVALID_WINDOW_ID, "Can't aquire visual info from display.");
```
Comment (akien-mga) [inline platform/linuxbsd/x11/display_server_x11.cpp:4878]:
```suggestion
		ERR_FAIL_COND_V_MSG(err != OK, INVALID_WINDOW_ID, "Can't acquire visual info from display.");
```

**Review by akien-mga — APPROVED** [review]

File: platform/linuxbsd/x11/display_server_x11.cpp (hunk 1 above)
Comment (clayjohn) [reply platform/linuxbsd/x11/display_server_x11.cpp]: Fixed! Thanks

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.1.
