### PR TITLE
Fix default `Environment` project setting and loading

### LINKED ISSUE #99732: Default `Environment` in project settings resets after project reloads and give errors
### Tested versions

- 4.4.dev
- Probably an effect of https://github.com/godotengine/godot/pull/97352 or https://github.com/godotengine/godot/pull/99286

### System information

Windows 11

### Issue description

Project settings `rendering/environment/defaults/default_environment` resets when the project is reloaded.

After the project opens, the text field will be blank but the setting is still there in the `project.godot` pointing to an `uid://...`. The `Environment` is not applied in the 3D scene though. I get errors:
> core\io\resource_uid.cpp:133 - Condition "!unique_ids.has(p_id)" is true. Returning: String()
> Resource file not found:  (expected type: )

Doesn't seem to happen with other path settings like `gui/theme/custom`.

### Steps to reproduce

It only happens when the project has a lot of files so the editor takes a while on the first filesystem scan.

- Set a default `Environment` resource in `Project Settings` > `rendering/environment/defaults/default_environment`.
- Reload the project.
- Errors are printed, the environment is not applied in the scenes, and the field is blank in the settings.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by ydeltastar**
- Fix: https://github.com/godotengine/godot/issues/99732

When a project opens, the scene tree tries to load the default `Environment` while the editor is still scanning the filesystem. This causes issues and errors since the `uid://` may not have been mapped yet.

This PR ensures it only tries to load when it is mapped.

### CODE REVIEW

File: scene/main/scene_tree.cpp [hunk 1]
```diff
@@ -610,23 +610,29 @@ bool SceneTree::process(double p_time) {
...
+		// the case if the editor is still scanning the filesystem.
+		ResourceUID::ID id = ResourceUID::get_singleton()->text_to_id(env_path);
+		if (ResourceUID::get_singleton()->has_id(id)) {
+			String cpath;
+			Ref<Environment> fallback = get_root()->get_world_3d()->get_fallback_environment();
+			if (fallback.is_valid()) {
+				cpath = fallback->get_path();
+			}
+
+			env_path = ResourceUID::get_singleton()->ensure_path(env_path.strip_edges()); //user may have added a space or two
```
Comment (KoBeWi) [inline scene/main/scene_tree.cpp:623]:
```suggestion
			env_path = ResourceUID::get_singleton()->get_id_path(id);
```

File: scene/main/scene_tree.cpp [hunk 2]
```diff
@@ -610,23 +610,29 @@ bool SceneTree::process(double p_time) {
...
-		}
-		if (cpath != env_path) {
-			if (!env_path.is_empty()) {
-				fallback = ResourceLoader::load(env_path);
-				if (fallback.is_null()) {
-					//could not load fallback, set as empty
-					ProjectSettings::get_singleton()->set("rendering/environment/defaults/default_environment", "");
+		// Ensure the uid path is mapped to a resource, which could not be
+		// the case if the editor is still scanning the filesystem.
+		ResourceUID::ID id = ResourceUID::get_singleton()->text_to_id(env_path);
```
Comment (KoBeWi) [inline scene/main/scene_tree.cpp:615]: This won't work if the value is stored as path (which can happen if it was set before dev5). Though seems like environment will display correctly in either case, so not sure what does it do.

Comment (ydeltastar) [reply scene/main/scene_tree.cpp:615]: It's because on scene tree initialization it calls `ResourceLoader::load` and it works.. I supposed it uses the `uid_cache.bin` in `.godot` or something. I will just reuse it.

https://github.com/godotengine/godot/blob/bbc54692c05ff6a85a6aeefbf5b9c87de91983d8/scene/main/scene_tree.cpp#L1941-L1972

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
