### PR TITLE
Fix `ViewPanner` panning-mouse-warp

### LINKED ISSUE #100438: `ViewPanner` panning-mouse-warp doesn't work in SubViewports or embedded Windows
### Tested versions

- reproducible in v4.0.stable.official [92bee43ad] and v4.4.dev.custom_build [b9437c393]

### System information

Debian Linux X11

### Issue description

Using a `GraphEdit` in a `SubViewport` or in an embedded `Window` has currently the problem, that panning doesn't work, when moving the mouse out of the `GraphEdit` area. In that case, the mouse cursor jumps in unexpected ways:
- In a `SubViewport`, this leads the mouse to be shifted by the distance from the top-left corner of the root window to the top-left corner of the SubViewportContainer.
- In an embedded `Window`, this leads the mouse to be constantly jumping around.

I would expect, that the mouse reappears on the other side of the GraphEdit area without lateral movement.

https://github.com/user-attachments/assets/7a4fd227-fe27-44d3-ba62-ecf53f240c45

I have tracked this to:

https://github.com/godotengine/godot/blob/b9437c393871c377b5ece131afaf831e78dfb6f8/scene/gui/view_panner.cpp#L113

`Input::get_singleton()->warp_mouse_motion` assumes, that its argument are in root-viewport coordinates, which they are not.

### Steps to reproduce

1. Load and run MRP
2. Try panning with the middle mouse button as shown in the video above

### Minimal reproduction project (MRP)

[viewpanner-in-subviewport.zip](https://github.com/user-attachments/files/18141183/viewpanner-in-subviewport.zip)

### PR DESCRIPTION
**Pull request by Sauermann**
Currently the mouse cursor jumps in unexpected ways, when a `ViewPanner` is used in SubViewports or embedded Windows.

This is caused by providing wrong coordinate systems to Input::warp_mouse_motion.

This PR replaces the use of `Input::warp_mouse_motion` with `Viewport::wrap_mouse_in_rect` and makes sure, that the correct coordinate systems are used.

This change makes it necessary, that all classes, that currently use ViewPanner, need to provide the correct Viewport to ViewPanner (necessary changes are included in this PR).

The obligatory before and after:

https://github.com/user-attachments/assets/7a4fd227-fe27-44d3-ba62-ecf53f240c45

https://github.com/user-attachments/assets/33d39f96-1a2b-4211-85c2-d27b23a2e1c5

- resolve #100438

One long-term goal of this PR is to move `Input::warp_mouse_motion` from Input to Viewport. It doesn't directly require any functionality of the `Input` class and so it makes sense to move it to a class that is not in core.

- updated 2024-12-16: rename replacement-function to `Viewport::wrap_mouse_in_rect`

### CODE REVIEW

File: scene/debugger/scene_debugger.cpp [hunk 1]
```diff
@@ -1250,6 +1250,7 @@ void RuntimeNodeSelect::_setup(const Dictionary &p_settings) {
 	int pan_speed = p_settings.get("editors/panning/2d_editor_pan_speed", 20);
 	Array keys = p_settings.get("canvas_item_editor/pan_view", Array()).operator Array();
 	panner->setup(panning_scheme, DebuggerMarshalls::deserialize_key_shortcut(keys), simple_panning);
+	panner->set_viewport(root);
```
Comment (Sauermann) [inline scene/debugger/scene_debugger.cpp:1253]: If it's possible, that the panner is displayed not in the root window, but in a separate window, then this needs to be adjusted.

Comment (Geometror) [reply scene/debugger/scene_debugger.cpp:1253]: I would say it's fine for now, as RuntimeNodeSelect only works for the root window.

**Review by Geometror — COMMENTED** [review]
Tested locally on Windows 11 after I realized that mouse warping doesn't work on Wayland currenlty (although unrelated to this PR). 
Works great! Implementation looks fine too, although I would call the new method `Viewport::wrap_mouse_in_rect` instead of `Viewport::warp_mouse_into_rect`
(wrap not warp, no typo here ;) Since wrapping more accurately/commonly describes the concept of something going out of bounds on one side and appearing on the other; so *wrapping* the mouse pointer in[side] the rect is done via *warping* it to specific position at the right time. Besides that, "wrap...into" implies that it just moves the mouse into a rectangle).

**Comment by Sauermann** [comment]
Makes sense. I have updated the function name.

**Review by Geometror — APPROVED** [review]

File: editor/plugins/sprite_2d_editor_plugin.cpp [hunk 2]
```diff
@@ -566,6 +566,8 @@ void Sprite2DEditor::_notification(int p_what) {
 			options->get_popup()->set_item_icon(MENU_OPTION_CONVERT_TO_POLYGON_2D, get_editor_theme_icon(SNAME("Polygon2D")));
 			options->get_popup()->set_item_icon(MENU_OPTION_CREATE_COLLISION_POLY_2D, get_editor_theme_icon(SNAME("CollisionPolygon2D")));
 			options->get_popup()->set_item_icon(MENU_OPTION_CREATE_LIGHT_OCCLUDER_2D, get_editor_theme_icon(SNAME("LightOccluder2D")));
+
+			panner->set_viewport(get_viewport());
```
Comment (KoBeWi) [inline editor/plugins/sprite_2d_editor_plugin.cpp:570]: I'd move this to ENTER_TREE and add break. Handling both ENTER_TREE and THEME_CHANGED [is redundant](https://github.com/godotengine/godot/pull/89746).

File: scene/gui/view_panner.h [hunk 3]
```diff
@@ -63,6 +64,8 @@ class ViewPanner : public RefCounted {
 	bool enable_rmb = false;
 	bool simple_panning_enabled = false;
 
+	Viewport *viewport;
```
Comment (KoBeWi) [inline scene/gui/view_panner.h:67]:
```suggestion
	Viewport *viewport = nullptr;
```

**Comment by KoBeWi** [comment]
Does `set_viewport()` need updating or the viewport could be part of `setup()` maybe?

**Comment by Sauermann** [comment]
When moving the node to a different location in the scene tree, it's possible, that setting a different viewport is required. So I believe, that `ENTER_TREE` is the right place to include it.

File: editor/plugins/texture_region_editor_plugin.cpp [hunk 4]
```diff
@@ -826,6 +826,7 @@ void TextureRegionEditor::_notification(int p_what) {
 
 		case NOTIFICATION_READY: {
 			panner->setup((ViewPanner::ControlScheme)EDITOR_GET("editors/panning/sub_editors_panning_scheme").operator int(), ED_GET_SHORTCUT("canvas_item_editor/pan_view"), bool(EDITOR_GET("editors/panning/simple_panning")));
+			panner->set_viewport(get_viewport());
```
Comment (Sauermann) [inline editor/plugins/texture_region_editor_plugin.cpp:829]: Originally, I placed the new code side-by-side to `setup`, but I have noticed that here it is in `NOTIFICATION_READY`. Would it be better, to move `setup` and `set_viewport` to `NOTIFICATION_ENTER_TREE`?

Comment (KoBeWi) [reply editor/plugins/texture_region_editor_plugin.cpp:829]: It can be moved.

**Review by KoBeWi — APPROVED** [review]
Overall looks fine.

File: scene/gui/view_panner.h (hunk 3 above)
Comment (Sauermann) [reply scene/gui/view_panner.h]: Thanks for your comments. I have included all your changes.
For future reference, should I generally follow the rule to initialize all pointers with `nullptr`?

**Comment by Repiteo** [comment]
Thanks!
