### PR TITLE
Bounds fixes in `TextureAtlas` import

### LINKED ISSUE #68350: Certain images are ignored when creating AtlasTextures with Import Mode set to 'Mesh2D'
### Godot version

v4.0.beta4.official [e6751549c]

### System information

Windows 11

### Issue description

If we create an AtlasTexture from sprites, and set the 'Import Mode' to Mesh2D, certain sprites will be ignored, and these sprites will show up as empty frames if you try to use them in an AnimatedSprite2D. 

I've tested this, and it seems only certain images are being ignored, though I'm not sure why. For certain animations, images are ignored, whereas for others 0 are ignored. The same images are ignored every time, making me think that it is some property of the images themselves. 

### Steps to reproduce

Import sprites into project. 

Create AtlasTexture with import mode 'Mesh2D'

Some images will be missing if you try to use them in an AnimatedSprite2D. 

### Minimal reproduction project

[MRP_AtlasTexture.zip](https://github.com/godotengine/godot/files/9947164/MRP_AtlasTexture.zip)

### PR DESCRIPTION
**Pull request by AThousandShips**
Fixes Importing of TextureAtlas in Mesh2D mode, adding settings for the generation of the triangulation which was not optimal, using the same options as used in Sprite2D editor

There is still a problem with gaps in the texture (see #68350) and if I find a way to solve that I will add that here but otherwise I will leave that for someone else I currently cannot see a solution.

Currently not fixing the errors in rasterisation, will investigate further later or let someone else solve that (added a note about this).

* Fixes #68350 (partially)

### CODE REVIEW

**Comment by AThousandShips** [comment]
Still seeing some issues so will test further before this is fully resolved

File: editor/import/resource_importer_texture_atlas.cpp [hunk 1]
```diff
@@ -240,17 +248,37 @@ Error ResourceImporterTextureAtlas::import_group_file(const String &p_group_file
...
+			}
+
+			if (grow_mask > 0) {
+				bit_map->grow_mask(grow_mask, rect);
+			}
+
+			Vector<Vector<Vector2>> polygons = bit_map->clip_opaque_to_polygons(rect, simplification);
+
+			for (int i = 0; i < polygons.size(); ++i) {
+				polygons.write[i] = Sprite2DEditor::expand(polygons[i], rect, simplification);
```
Comment (kleonc) [inline editor/import/resource_importer_texture_atlas.cpp:272]: Not sure what's the justification for using `Sprite2DEditor::expand`. I'd guess it hides the mentioned issue with `BitMap::clip_opaque_to_polygons` for some specific test case and thus you've added it. But I'm not sure it's really needed / it fixes anything. And if it would indeed be needed then probably it would make sense to extract this method elsewhere from the `Sprite2DEditor` as `ResourceImporterTextureAtlas` shouldn't be dependant on `Sprite2DEditor`. But again, not sure why / what for it's used.

File: editor/import/resource_importer_texture_atlas.cpp [hunk 2]
```diff
@@ -126,7 +134,7 @@ static void _plot_triangle(Vector2i *vertices, const Vector2i &p_offset, bool p_
 	double dx_low = double(x[2] - x[1]) / (y[2] - y[1] + 1);
 	double xf = x[0];
 	double xt = x[0] + dx_upper; // if y[0] == y[1], special case
-	int max_y = MIN(y[2], height - p_offset.y - 1);
+	int max_y = y[2];
```
Comment (kleonc) [inline editor/import/resource_importer_texture_atlas.cpp:137]: Would you mind explaining the reasoning for this change?

File: editor/editor_atlas_packer.cpp [hunk 3]
```diff
@@ -59,7 +59,7 @@ void EditorAtlasPacker::chart_pack(Vector<Chart> &charts, int &r_width, int &r_h
 
 		Ref<BitMap> src_bitmap;
 		src_bitmap.instantiate();
-		src_bitmap->create(aabb.size / divide_by);
+		src_bitmap->create((aabb.size / divide_by).max(Vector2i(1, 1)));
```
Comment (kleonc) [inline editor/editor_atlas_packer.cpp:62]: I get this gets rid of the zero-size errors. But does the algorithm work as it's supposed to in such cases? Or was made just to silence the errors?

**Review by kleonc — COMMENTED** [review]
Adding new options for importing TextureAtlas in a Mesh2D mode seems like a good idea to me, but I don't think that's an actual bugfix. With the new options now the user would need to find the parameters which would result in a not buggy import. So as an enhancement it makes sense but I don't think it's an actual bugfix.

The actual problem seems to be the `BitMap::clip_opaque_to_polygons` method:

- It can produce lists of points not representing actual polygons. For these triangulation will fail and in the relevant step in the atlas packer it would result in a mesh with `n` vertices and `0` faces. Most likely caused by [the `reduce()` step](https://github.com/godotengine/godot/blob/a499f7bdc4be5877c75bd898e040937a02b99b85/scene/resources/bit_map.cpp#L510). Besides potentially fixing it to always produce valid polygons, it's probably a good idea to check whether the triangulation succeeded and error / somehow inform the user about the fail.
- It can produce kinda duplicated polygons (maybe overlapping too? :thinking:). For example for [this image from the MRP](https://user-images.githubusercontent.com/9283098/200564187-c12f17af-3675-436b-a8d8-b467a23ca538.png) this script:
```gdscript
@tool
extends EditorScript

func _run():
	var texture_path: String = ...
	var out_path: String = ...
	
	var img: Image = load(texture_path).get_image()	
	var f := FileAccess.open(out_path, FileAccess.WRITE)
	
	for alpha_threshold in [0.0, 0.1]:
		var bm := BitMap.new()
		bm.create_from_image_alpha(img, alpha_threshold)
		
		bm.convert_to_image().save_png("bit_mask_alpha_threshold_%.1f.png" % [alpha_threshold])
		
		var whole_rect: Rect2i = Rect2(Vector2.ZERO, bm.get_size())
		var simplification_epsilon := 0.0		
		var polys: Array[PackedVector2Array] = bm.opaque_to_polygons(whole_rect, simplification_epsilon)		
		
		f.store_line("alpha_threshold = %.1f" % [alpha_threshold])
		for i in polys.size():
			var p = polys[i]
			f.store_line("  polys[%d] size=%d" % [i, p.size()])
			f.store_line("    %s" % [p])
			f.store_line("")
```
outputs:
[bit_mask_alpha_threshold_0.0.png](https://user-images.githubusercontent.com/9283098/200570668-3562e7fa-0a95-4005-850d-df3eeffda005.png)
[bit_mask_alpha_threshold_0.1.png](https://user-images.githubusercontent.com/9283098/200570673-8ec634cf-8049-45a4-b5e1-db26d5308333.png)
```
alpha_threshold = 0.0
  polys[0] size=2052
    [(709, 398), (708, 398), (708, 414), (709, 414), (709, 423), (708, 423), (708, 424), (707, 424), (707, 426), (706, 426), (706, 430), (705, 430), (705, 435), (704, 435), (704, 440), (703, 440), (703, 445), (702, 445), (702, 451), (701, 451), (701, 454), (700, 454), (700, 457), (699, 457), (699, 460), (698, 460), (698, 464), (697, 464), (697, 467), (696, 467), (696, 471), (695, 471), (695, 476), (694, 476), (694, 485), (693, 485), (693, 489), (692, 489), (692, 487), (691, 487), (691, 486), (690, 486), (690, 484), (689, 484), (689, 483), (688, 483), (688, 482), (687, 482), (687, 480), (686, 480), (686, 478), (685, 478), (685, 476), (684, 476), (684, 472), (683, 472), (683, 470), (682, 470), (682, 469), (681, 469), (681, 467), (680, 467), (680, 466), (679, 466), (679, 465), (678, 465), (678, 463), (677, 463), (677, 461), (676, 461), (676, 458), (675, 458), (675, 455), (674, 455), (674, 453), (672, 453), (672, 451), (671, 451), (671, 450), (670, 450), (670, 449), (669, 449), (669, 448), (668, 448), (668, 447), (667, 447), (667, 446), (666, 446), (666, 445), (665, 445), (665, 444), (664, 444), (664, 443), (663, 443), (663, 441), (662, 441), (662, 440), (661, 440), (661, 439), (660, 439), (660, 438), (659, 438), (659, 437), (658, 437), (658, 436), (657, 436), (657, 434), (656, 434), (656, 431), (655, 431), (655, 428), (654, 428), (654, 426), (652, 426), (652, 428), (653, 428), (653, 429), (652, 429), (652, 428), (651, 428), (651, 426), (650, 426), (650, 424), (649, 424), (649, 423), (647, 423), (647, 424), (646, 424), (646, 425), (645, 425), (645, 427), (644, 427), (644, 471), (645, 471), (645, 476), (646, 476), (646, 479), (647, 479), (647, 484), (648, 484), (648, 495), (649, 495), (649, 504), (650, 504), (650, 512), (651, 512), (651, 519), (652, 519), (652, 530), (653, 530), (653, 536), (646, 536), (646, 535), (648, 535), (648, 534), (638, 534), (638, 533), (633, 533), (633, 532), (622, 532), (622, 531), (618, 531), (618, 530), (612, 530), (612, 529), (606, 529), (606, 528), (596, 528), (596, 527), (587, 527), (587, 526), (581, 526), (581, 525), (571, 525), (571, 524), (568, 524), (568, 525), (567, 525), (567, 526), (569, 526), (569, 527), (571, 527), (571, 528), (570, 528), (570, 529), (568, 529), (568, 530), (567, 530), (567, 531), (565, 531), (565, 530), (566, 530), (566, 529), (563, 529), (563, 530), (562, 530), (562, 531), (560, 531), (560, 532), (556, 532), (556, 533), (555, 533), (555, 535), (553, 535), (553, 536), (551, 536), (551, 537), (549, 537), (549, 538), (547, 538), (547, 539), (545, 539), (545, 540), (544, 540), (544, 542), (542, 542), (542, 543), (541, 543), (541, 545), (539, 545), (539, 546), (537, 546), (537, 547), (536, 547), (536, 548), (534, 548), (534, 549), (532, 549), (532, 550), (530, 550), (530, 551), (524, 551), (524, 552), (514, 552), (514, 553), (512, 553), (512, 554), (511, 554), (511, 555), (509, 555), (509, 556), (502, 556), (502, 557), (499, 557), (499, 558), (497, 558), (497, 559), (495, 559), (495, 560), (493, 560), (493, 561), (492, 561), (492, 562), (491, 562), (491, 563), (490, 563), (490, 564), (487, 564), (487, 565), (484, 565), (484, 564), (478, 564), (478, 565), (477, 565), (477, 566), (475, 566), (475, 570), (476, 570), (476, 571), (478, 571), (478, 572), (477, 572), (477, 573), (483, 573), (483, 575), (481, 575), (481, 576), (478, 576), (478, 577), (474, 577), (474, 578), (471, 578), (471, 579), (469, 579), (469, 580), (467, 580), (467, 585), (468, 585), (468, 586), (469, 586), (469, 587), (471, 587), (471, 588), (473, 588), (473, 589), (479, 589), (479, 588), (486, 588), (486, 590), (485, 590), (485, 592), (486, 592), (486, 594), (487, 594), (487, 595), (488, 595), (488, 602), (491, 602), (491, 601), (492, 601), (492, 603), (494, 603), (494, 602), (495, 602), (495, 600), (496, 600), (496, 598), (497, 598), (497, 597), (498, 597), (498, 594), (499, 594), (499, 591), (500, 591), (500, 589), (501, 589), (501, 586), (502, 586), (502, 590), (503, 590), (503, 593), (504, 593), (504, 595), (505, 595), (505, 589), (504, 589), (504, 588), (503, 588), (503, 585), (504, 585), (504, 583), (505, 583), (505, 585), (506, 585), (506, 589), (507, 589), (507, 591), (508, 591), (508, 593), (509, 593), (509, 595), (510, 595), (510, 598), (511, 598), (511, 599), (514, 599), (514, 598), (515, 598), (515, 597), (516, 597), (516, 596), (517, 596), (517, 585), (518, 585), (518, 584), (521, 584), (521, 582), (522, 582), (522, 580), (523, 580), (523, 579), (524, 579), (524, 578), (526, 578), (526, 577), (529, 577), (529, 576), (531, 576), (531, 575), (532, 575), (532, 574), (533, 574), (533, 573), (534, 573), (534, 572), (536, 572), (536, 573), (535, 573), (535, 574), (534, 574), (534, 575), (533, 575), (533, 576), (535, 576), (535, 577), (536, 577), (536, 576), (537, 576), (537, 575), (538, 575), (538, 574), (539, 574), (539, 573), (541, 573), (541, 572), (544, 572), (544, 571), (545, 571), (545, 572), (546, 572), (546, 573), (547, 573), (547, 574), (549, 574), (549, 573), (552, 573), (552, 572), (554, 572), (554, 571), (556, 571), (556, 570), (558, 570), (558, 571), (559, 571), (559, 572), (560, 572), (560, 573), (561, 573), (561, 574), (562, 574), (562, 579), (564, 579), (564, 578), (565, 578), (565, 579), (566, 579), (566, 581), (565, 581), (565, 583), (564, 583), (564, 584), (563, 584), (563, 586), (562, 586), (562, 587), (561, 587), (561, 588), (560, 588), (560, 603), (561, 603), (561, 604), (563, 604), (563, 603), (564, 603), (564, 602), (565, 602), (565, 601), (566, 601), (566, 600), (567, 600), (567, 599), (568, 599), (568, 598), (569, 598), (569, 597), (570, 597), (570, 596), (571, 596), (571, 595), (572, 595), (572, 594), (573, 594), (573, 597), (574, 597), (574, 599), (575, 599), (575, 593), (576, 593), (576, 592), (577, 592), (577, 593), (578, 593), (578, 594), (579, 594), (579, 597), (580, 597), (580, 605), (581, 605), (581, 606), (583, 606), (583, 615), (584, 615), (584, 618), (585, 618), (585, 620), (586, 620), (586, 622), (587, 622), (587, 623), (588, 623), (588, 626), (589, 626), (589, 628), (590, 628), (590, 631), (591, 631), (591, 635), (592, 635), (592, 638), (593, 638), (593, 641), (594, 641), (594, 644), (595, 644), (595, 648), (596, 648), (596, 651), (597, 651), (597, 670), (596, 670), (596, 676), (595, 676), (595, 679), (596, 679), (596, 680), (598, 680), (598, 677), (599, 677), (599, 674), (600, 674), (600, 672), (601, 672), (601, 670), (602, 670), (602, 668), (603, 668), (603, 667), (604, 667), (604, 665), (605, 665), (605, 664), (606, 664), (606, 663), (607, 663), (607, 662), (608, 662), (608, 660), (609, 660), (609, 659), (610, 659), (610, 658), (611, 658), (611, 657), (612, 657), (612, 656), (613, 656), (613, 655), (614, 655), (614, 654), (615, 654), (615, 653), (616, 653), (616, 652), (617, 652), (617, 651), (618, 651), (618, 649), (619, 649), (619, 648), (620, 648), (620, 647), (621, 647), (621, 646), (622, 646), (622, 645), (623, 645), (623, 644), (625, 644), (625, 643), (626, 643), (626, 642), (627, 642), (627, 641), (628, 641), (628, 640), (629, 640), (629, 639), (630, 639), (630, 638), (632, 638), (632, 637), (634, 637), (634, 636), (636, 636), (636, 635), (638, 635), (638, 634), (641, 634), (641, 633), (643, 633), (643, 632), (645, 632), (645, 631), (647, 631), (647, 630), (650, 630), (650, 629), (652, 629), (652, 628), (654, 628), (654, 627), (656, 627), (656, 626), (658, 626), (658, 625), (660, 625), (660, 624), (661, 624), (661, 623), (663, 623), (663, 622), (665, 622), (665, 621), (667, 621), (667, 620), (669, 620), (669, 619), (671, 619), (671, 618), (673, 618), (673, 617), (674, 617), (674, 616), (676, 616), (676, 615), (678, 615), (678, 614), (679, 614), (679, 613), (683, 613), (683, 612), (685, 612), (685, 611), (687, 611), (687, 610), (688, 610), (688, 609), (690, 609), (690, 608), (695, 608), (695, 607), (698, 607), (698, 606), (700, 606), (700, 605), (702, 605), (702, 604), (704, 604), (704, 603), (707, 603), (707, 605), (708, 605), (708, 611), (709, 611), (709, 613), (708, 613), (708, 614), (707, 614), (707, 615), (706, 615), (706, 616), (705, 616), (705, 618), (707, 618), (707, 617), (708, 617), (708, 616), (711, 616), (711, 617), (712, 617), (712, 618), (713, 618), (713, 619), (715, 619), (715, 620), (716, 620), (716, 621), (718, 621), (718, 622), (721, 622), (721, 621), (724, 621), (724, 622), (726, 622), (726, 623), (728, 623), (728, 624), (730, 624), (730, 625), (731, 625), (731, 626), (733, 626), (733, 627), (734, 627), (734, 628), (736, 628), (736, 629), (738, 629), (738, 630), (741, 630), (741, 631), (745, 631), (745, 632), (746, 632), (746, 636), (747, 636), (747, 645), (746, 645), (746, 647), (745, 647), (745, 653), (744, 653), (744, 659), (743, 659), (743, 662), (742, 662), (742, 665), (741, 665), (741, 667), (740, 667), (740, 669), (739, 669), (739, 673), (738, 673), (738, 676), (737, 676), (737, 679), (736, 679), (736, 681), (735, 681), (735, 684), (734, 684), (734, 686), (733, 686), (733, 688), (732, 688), (732, 690), (733, 690), (733, 692), (736, 692), (736, 693), (743, 693), (743, 694), (744, 694), (744, 695), (745, 695), (745, 694), (747, 694), (747, 695), (746, 695), (746, 697), (745, 697), (745, 700), (744, 700), (744, 703), (746, 703), (746, 700), (747, 700), (747, 697), (748, 697), (748, 695), (749, 695), (749, 694), (750, 694), (750, 695), (751, 695), (751, 696), (752, 696), (752, 697), (754, 697), (754, 698), (756, 698), (756, 699), (760, 699), (760, 700), (761, 700), (761, 702), (760, 702), (760, 704), (759, 704), (759, 706), (758, 706), (758, 707), (757, 707), (757, 708), (756, 708), (756, 709), (755, 709), (755, 710), (754, 710), (754, 714), (753, 714), (753, 716), (752, 716), (752, 717), (751, 717), (751, 719), (750, 719), (750, 720), (749, 720), (749, 721), (748, 721), (748, 722), (747, 722), (747, 724), (746, 724), (746, 725), (745, 725), (745, 726), (744, 726), (744, 727), (743, 727), (743, 729), (742, 729), (742, 731), (741, 731), (741, 734), (740, 734), (740, 736), (739, 736), (739, 737), (738, 737), (738, 739), (737, 739), (737, 741), (736, 741), (736, 742), (735, 742), (735, 744), (734, 744), (734, 745), (732, 745), (732, 746), (731, 746), (731, 747), (730, 747), (730, 748), (729, 748), (729, 750), (728, 750), (728, 751), (727, 751), (727, 752), (726, 752), (726, 753), (725, 753), (725, 754), (724, 754), (724, 755), (723, 755), (723, 756), (722, 756), (722, 757), (721, 757), (721, 758), (720, 758), (720, 760), (719, 760), (719, 761), (718, 761), (718, 762), (717, 762), (717, 763), (716, 763), (716, 765), (715, 765), (715, 766), (714, 766), (714, 768), (713, 768), (713, 770), (712, 770), (712, 772), (711, 772), (711, 775), (710, 775), (710, 778), (709, 778), (709, 779), (708, 779), (708, 781), (707, 781), (707, 782), (706, 782), (706, 783), (705, 783), (705, 785), (704, 785), (704, 786), (703, 786), (703, 787), (702, 787), (702, 789), (701, 789), (701, 790), (700, 790), (700, 791), (699, 791), (699, 792), (698, 792), (698, 794), (697, 794), (697, 795), (696, 795), (696, 798), (695, 798), (695, 799), (694, 799), (694, 801), (693, 801), (693, 805), (694, 805), (694, 804), (696, 804), (696, 803), (697, 803), (697, 802), (699, 802), (699, 801), (701, 801), (701, 800), (702, 800), (702, 799), (704, 799), (704, 798), (706, 798), (706, 797), (707, 797), (707, 796), (709, 796), (709, 795), (711, 795), (711, 794), (713, 794), (713, 793), (715, 793), (715, 792), (716, 792), (716, 791), (718, 791), (718, 790), (719, 790), (719, 789), (723, 789), (723, 788), (724, 788), (724, 789), (723, 789), (723, 791), (722, 791), (722, 794), (721, 794), (721, 797), (720, 797), (720, 801), (719, 801), (719, 804), (718, 804), (718, 808), (717, 808), (717, 812), (716, 812), (716, 815), (715, 815), (715, 817), (714, 817), (714, 820), (713, 820), (713, 822), (712, 822), (712, 825), (711, 825), (711, 828), (710, 828), (710, 831), (709, 831), (709, 834), (708, 834), (708, 824), (707, 824), (707, 818), (705, 818), (705, 821), (704, 821), (704, 824), (703, 824), (703, 827), (702, 827), (702, 837), (703, 837), (703, 848), (704, 848), (704, 850), (703, 850), (703, 853), (702, 853), (702, 856), (701, 856), (701, 860), (700, 860), (700, 866), (699, 866), (699, 870), (698, 870), (698, 874), (697, 874), (697, 877), (696, 877), (696, 880), (695, 880), (695, 884), (694, 884), (694, 888), (693, 888), (693, 895), (692, 895), (692, 901), (691, 901), (691, 904), (690, 904), (690, 907), (689, 907), (689, 909), (688, 909), (688, 912), (687, 912), (687, 914), (686, 914), (686, 916), (685, 916), (685, 918), (684, 918), (684, 919), (683, 919), (683, 921), (682, 921), (682, 923), (681, 923), (681, 924), (680, 924), (680, 926), (679, 926), (679, 928), (678, 928), (678, 930), (677, 930), (677, 932), (676, 932), (676, 934), (675, 934), (675, 936), (674, 936), (674, 938), (673, 938), (673, 939), (672, 939), (672, 940), (670, 940), (670, 941), (669, 941), (669, 943), (668, 943), (668, 946), (667, 946), (667, 947), (666, 947), (666, 948), (665, 948), (665, 950), (664, 950), (664, 951), (663, 951), (663, 953), (662, 953), (662, 957), (661, 957), (661, 958), (659, 958), (659, 959), (658, 959), (658, 961), (657, 961), (657, 963), (656, 963), (656, 965), (655, 965), (655, 967), (654, 967), (654, 969), (653, 969), (653, 970), (652, 970), (652, 972), (651, 972), (651, 973), (650, 973), (650, 974), (649, 974), (649, 975), (648, 975), (648, 977), (647, 977), (647, 978), (646, 978), (646, 979), (645, 979), (645, 980), (644, 980), (644, 981), (640, 981), (640, 984), (641, 984), (641, 985), (654, 985), (654, 986), (657, 986), (657, 987), (661, 987), (661, 988), (664, 988), (664, 989), (666, 989), (666, 990), (668, 990), (668, 991), (671, 991), (671, 992), (678, 992), (678, 991), (710, 991), (710, 992), (739, 992), (739, 993), (820, 993), (820, 994), (821, 994), (821, 995), (823, 995), (823, 996), (839, 996), (839, 995), (845, 995), (845, 994), (851, 994), (851, 993), (855, 993), (855, 992), (860, 992), (860, 991), (864, 991), (864, 990), (872, 990), (872, 989), (884, 989), (884, 988), (892, 988), (892, 987), (903, 987), (903, 986), (905, 986), (905, 985), (907, 985), (907, 984), (911, 984), (911, 983), (934, 983), (934, 982), (973, 982), (973, 979), (974, 979), (974, 980), (975, 980), (975, 981), (976, 981), (976, 982), (977, 982), (977, 983), (978, 983), (978, 985), (979, 985), (979, 986), (980, 986), (980, 987), (981, 987), (981, 989), (982, 989), (982, 990), (983, 990), (983, 989), (984, 989), (984, 988), (985, 988), (985, 986), (983, 986), (983, 987), (982, 987), (982, 985), (981, 985), (981, 984), (980, 984), (980, 982), (979, 982), (979, 981), (978, 981), (978, 980), (977, 980), (977, 979), (976, 979), (976, 978), (975, 978), (975, 977), (974, 977), (974, 976), (973, 976), (973, 973), (972, 973), (972, 971), (968, 971), (968, 970), (964, 970), (964, 969), (963, 969), (963, 968), (961, 968), (961, 967), (959, 967), (959, 966), (958, 966), (958, 965), (956, 965), (956, 964), (955, 964), (955, 963), (954, 963), (954, 962), (953, 962), (953, 961), (952, 961), (952, 960), (950, 960), (950, 959), (949, 959), (949, 958), (948, 958), (948, 957), (947, 957), (947, 956), (945, 956), (945, 955), (944, 955), (944, 954), (942, 954), (942, 953), (941, 953), (941, 952), (938, 952), (938, 951), (934, 951), (934, 950), (932, 950), (932, 949), (930, 949), (930, 948), (928, 948), (928, 947), (927, 947), (927, 946), (926, 946), (926, 945), (924, 945), (924, 944), (923, 944), (923, 943), (922, 943), (922, 942), (921, 942), (921, 941), (920, 941), (920, 940), (919, 940), (919, 939), (918, 939), (918, 938), (917, 938), (917, 937), (916, 937), (916, 936), (915, 936), (915, 935), (914, 935), (914, 933), (913, 933), (913, 932), (912, 932), (912, 930), (911, 930), (911, 929), (910, 929), (910, 927), (909, 927), (909, 926), (908, 926), (908, 924), (907, 924), (907, 922), (906, 922), (906, 921), (905, 921), (905, 919), (904, 919), (904, 917), (903, 917), (903, 915), (902, 915), (902, 913), (901, 913), (901, 910), (900, 910), (900, 908), (899, 908), (899, 905), (898, 905), (898, 903), (897, 903), (897, 900), (896, 900), (896, 898), (895, 898), (895, 895), (894, 895), (894, 892), (893, 892), (893, 889), (892, 889), (892, 886), (891, 886), (891, 883), (890, 883), (890, 880), (889, 880), (889, 876), (888, 876), (888, 873), (887, 873), (887, 870), (886, 870), (886, 867), (885, 867), (885, 863), (884, 863), (884, 860), (883, 860), (883, 853), (884, 853), (884, 851), (885, 851), (885, 822), (886, 822), (886, 797), (887, 797), (887, 791), (888, 791), (888, 789), (889, 789), (889, 787), (890, 787), (890, 786), (891, 786), (891, 785), (892, 785), (892, 783), (893, 783), (893, 782), (894, 782), (894, 781), (895, 781), (895, 779), (896, 779), (896, 778), (897, 778), (897, 776), (898, 776), (898, 774), (899, 774), (899, 772), (900, 772), (900, 770), (901, 770), (901, 768), (902, 768), (902, 766), (903, 766), (903, 764), (904, 764), (904, 762), (905, 762), (905, 759), (906, 759), (906, 757), (907, 757), (907, 755), (908, 755), (908, 752), (909, 752), (909, 749), (910, 749), (910, 746), (911, 746), (911, 738), (909, 738), (909, 737), (907, 737), (907, 738), (906, 738), (906, 739), (905, 739), (905, 741), (904, 741), (904, 744), (903, 744), (903, 747), (902, 747), (902, 750), (901, 750), (901, 752), (900, 752), (900, 755), (899, 755), (899, 757), (898, 757), (898, 759), (897, 759), (897, 762), (896, 762), (896, 764), (895, 764), (895, 766), (894, 766), (894, 768), (893, 768), (893, 770), (892, 770), (892, 772), (891, 772), (891, 774), (890, 774), (890, 777), (889, 777), (889, 772), (890, 772), (890, 766), (891, 766), (891, 760), (892, 760), (892, 754), (893, 754), (893, 749), (894, 749), (894, 743), (895, 743), (895, 738), (896, 738), (896, 737), (897, 737), (897, 740), (898, 740), (898, 741), (899, 741), (899, 742), (900, 742), (900, 744), (901, 744), (901, 745), (902, 745), (902, 743), (903, 743), (903, 742), (902, 742), (902, 741), (901, 741), (901, 740), (900, 740), (900, 738), (898, 738), (898, 736), (900, 736), (900, 735), (901, 735), (901, 734), (903, 734), (903, 733), (904, 733), (904, 732), (906, 732), (906, 731), (908, 731), (908, 730), (909, 730), (909, 729), (911, 729), (911, 728), (912, 728), (912, 727), (914, 727), (914, 728), (915, 728), (915, 727), (916, 727), (916, 726), (917, 726), (917, 725), (918, 725), (918, 724), (919, 724), (919, 725), (918, 725), (918, 726), (917, 726), (917, 729), (916, 729), (916, 731), (917, 731), (917, 730), (920, 730), (920, 729), (921, 729), (921, 723), (922, 723), (922, 722), (930, 722), (930, 723), (937, 723), (937, 722), (940, 722), (940, 721), (943, 721), (943, 720), (945, 720), (945, 719), (946, 719), (946, 718), (947, 718), (947, 717), (948, 717), (948, 715), (950, 715), (950, 714), (951, 714), (951, 712), (953, 712), (953, 711), (955, 711), (955, 710), (956, 710), (956, 709), (957, 709), (957, 708), (958, 708), (958, 704), (957, 704), (957, 703), (956, 703), (956, 702), (955, 702), (955, 701), (953, 701), (953, 699), (952, 699), (952, 697), (951, 697), (951, 696), (950, 696), (950, 695), (949, 695), (949, 694), (947, 694), (947, 693), (945, 693), (945, 692), (935, 692), (935, 693), (933, 693), (933, 694), (931, 694), (931, 693), (927, 693), (927, 692), (922, 692), (922, 691), (919, 691), (919, 690), (917, 690), (917, 689), (916, 689), (916, 688), (915, 688), (915, 686), (914, 686), (914, 685), (913, 685), (913, 683), (912, 683), (912, 681), (911, 681), (911, 680), (910, 680), (910, 678), (909, 678), (909, 677), (908, 677), (908, 675), (907, 675), (907, 674), (906, 674), (906, 672), (905, 672), (905, 671), (904, 671), (904, 670), (903, 670), (903, 665), (902, 665), (902, 664), (901, 664), (901, 663), (900, 663), (900, 662), (898, 662), (898, 661), (895, 661), (895, 660), (893, 660), (893, 659), (890, 659), (890, 658), (891, 658), (891, 657), (893, 657), (893, 656), (894, 656), (894, 655), (891, 655), (891, 656), (888, 656), (888, 657), (885, 657), (885, 656), (883, 656), (883, 650), (884, 650), (884, 647), (882, 647), (882, 649), (881, 649), (881, 651), (880, 651), (880, 655), (879, 655), (879, 656), (878, 656), (878, 655), (877, 655), (877, 654), (875, 654), (875, 652), (876, 652), (876, 650), (877, 650), (877, 649), (878, 649), (878, 645), (879, 645), (879, 637), (880, 637), (880, 636), (882, 636), (882, 635), (884, 635), (884, 632), (883, 632), (883, 630), (882, 630), (882, 629), (881, 629), (881, 627), (880, 627), (880, 625), (879, 625), (879, 623), (878, 623), (878, 621), (877, 621), (877, 619), (876, 619), (876, 618), (875, 618), (875, 616), (874, 616), (874, 614), (873, 614), (873, 613), (872, 613), (872, 611), (871, 611), (871, 606), (870, 606), (870, 599), (871, 599), (871, 598), (873, 598), (873, 600), (874, 600), (874, 601), (879, 601), (879, 600), (881, 600), (881, 599), (883, 599), (883, 598), (885, 598), (885, 597), (886, 597), (886, 595), (887, 595), (887, 593), (888, 593), (888, 590), (889, 590), (889, 589), (890, 589), (890, 588), (888, 588), (888, 589), (887, 589), (887, 590), (883, 590), (883, 591), (881, 591), (881, 592), (880, 592), (880, 593), (878, 593), (878, 594), (876, 594), (876, 593), (877, 593), (877, 592), (878, 592), (878, 591), (879, 591), (879, 590), (880, 590), (880, 589), (881, 589), (881, 588), (882, 588), (882, 587), (883, 587), (883, 586), (884, 586), (884, 584), (885, 584), (885, 583), (886, 583), (886, 581), (887, 581), (887, 577), (888, 577), (888, 575), (889, 575), (889, 574), (890, 574), (890, 573), (893, 573), (893, 572), (895, 572), (895, 571), (897, 571), (897, 570), (899, 570), (899, 569), (900, 569), (900, 568), (901, 568), (901, 566), (902, 566), (902, 560), (901, 560), (901, 557), (902, 557), (902, 555), (903, 555), (903, 553), (904, 553), (904, 551), (905, 551), (905, 550), (906, 550), (906, 548), (907, 548), (907, 546), (908, 546), (908, 543), (909, 543), (909, 539), (908, 539), (908, 538), (906, 538), (906, 537), (903, 537), (903, 536), (902, 536), (902, 535), (899, 535), (899, 534), (890, 534), (890, 533), (884, 533), (884, 532), (880, 532), (880, 531), (878, 531), (878, 530), (876, 530), (876, 529), (874, 529), (874, 528), (873, 528), (873, 527), (872, 527), (872, 526), (871, 526), (871, 525), (870, 525), (870, 524), (869, 524), (869, 523), (868, 523), (868, 522), (867, 522), (867, 520), (866, 520), (866, 518), (865, 518), (865, 517), (864, 517), (864, 515), (863, 515), (863, 514), (862, 514), (862, 513), (853, 513), (853, 514), (848, 514), (848, 513), (847, 513), (847, 512), (845, 512), (845, 511), (843, 511), (843, 510), (842, 510), (842, 509), (841, 509), (841, 507), (840, 507), (840, 506), (839, 506), (839, 505), (838, 505), (838, 504), (837, 504), (837, 503), (836, 503), (836, 502), (835, 502), (835, 501), (833, 501), (833, 500), (832, 500), (832, 499), (830, 499), (830, 498), (829, 498), (829, 497), (827, 497), (827, 496), (825, 496), (825, 495), (823, 495), (823, 494), (818, 494), (818, 493), (816, 493), (816, 494), (812, 494), (812, 495), (810, 495), (810, 496), (808, 496), (808, 497), (807, 497), (807, 498), (806, 498), (806, 499), (805, 499), (805, 500), (800, 500), (800, 501), (797, 501), (797, 502), (794, 502), (794, 503), (792, 503), (792, 498), (791, 498), (791, 495), (790, 495), (790, 493), (789, 493), (789, 492), (788, 492), (788, 491), (786, 491), (786, 490), (785, 490), (785, 488), (783, 488), (783, 487), (782, 487), (782, 488), (781, 488), (781, 489), (777, 489), (777, 490), (775, 490), (775, 491), (773, 491), (773, 492), (772, 492), (772, 493), (771, 493), (771, 494), (770, 494), (770, 495), (769, 495), (769, 494), (767, 494), (767, 493), (766, 493), (766, 492), (765, 492), (765, 490), (764, 490), (764, 488), (763, 488), (763, 487), (761, 487), (761, 486), (759, 486), (759, 485), (754, 485), (754, 483), (753, 483), (753, 482), (749, 482), (749, 483), (748, 483), (748, 484), (747, 484), (747, 486), (745, 486), (745, 482), (744, 482), (744, 480), (743, 480), (743, 477), (742, 477), (742, 474), (741, 474), (741, 471), (740, 471), (740, 468), (739, 468), (739, 465), (738, 465), (738, 462), (737, 462), (737, 459), (736, 459), (736, 456), (735, 456), (735, 453), (734, 453), (734, 450), (733, 450), (733, 447), (732, 447), (732, 445), (731, 445), (731, 442), (730, 442), (730, 440), (729, 440), (729, 437), (728, 437), (728, 435), (727, 435), (727, 432), (726, 432), (726, 430), (725, 430), (725, 427), (724, 427), (724, 425), (723, 425), (723, 423), (722, 423), (722, 421), (721, 421), (721, 419), (720, 419), (720, 417), (719, 417), (719, 415), (718, 415), (718, 413), (717, 413), (717, 411), (716, 411), (716, 409), (715, 409), (715, 406), (714, 406), (714, 404), (713, 404), (713, 401), (712, 401), (712, 397), (711, 397), (711, 396), (709, 396)]

  polys[1] size=4
    [(484, 563), (485, 563), (485, 561), (484, 561)]

  polys[2] size=4
    [(900, 748), (901, 748), (901, 747), (900, 747)]

  polys[3] size=8
    [(699, 839), (698, 839), (698, 842), (699, 842), (699, 841), (700, 841), (700, 837), (699, 837)]

  polys[4] size=28
    [(674, 876), (675, 876), (675, 877), (676, 877), (676, 878), (677, 878), (677, 880), (678, 880), (678, 881), (679, 881), (679, 883), (680, 883), (680, 886), (682, 886), (682, 883), (681, 883), (681, 881), (680, 881), (680, 879), (679, 879), (679, 878), (678, 878), (678, 877), (677, 877), (677, 875), (676, 875), (676, 874), (674, 874)]

alpha_threshold = 0.1
  polys[0] size=2050
    [(709, 399), (708, 399), (708, 411), (709, 411), (709, 423), (708, 423), (708, 425), (707, 425), (707, 427), (706, 427), (706, 431), (705, 431), (705, 435), (704, 435), (704, 440), (703, 440), (703, 446), (702, 446), (702, 451), (701, 451), (701, 455), (700, 455), (700, 458), (699, 458), (699, 461), (698, 461), (698, 464), (697, 464), (697, 467), (696, 467), (696, 471), (695, 471), (695, 482), (694, 482), (694, 485), (693, 485), (693, 489), (692, 489), (692, 488), (691, 488), (691, 486), (690, 486), (690, 485), (689, 485), (689, 483), (688, 483), (688, 482), (687, 482), (687, 480), (686, 480), (686, 478), (685, 478), (685, 476), (684, 476), (684, 474), (683, 474), (683, 471), (682, 471), (682, 470), (681, 470), (681, 469), (680, 469), (680, 467), (679, 467), (679, 466), (678, 466), (678, 464), (677, 464), (677, 461), (676, 461), (676, 458), (675, 458), (675, 455), (674, 455), (674, 453), (671, 453), (671, 451), (670, 451), (670, 450), (669, 450), (669, 448), (668, 448), (668, 447), (667, 447), (667, 446), (666, 446), (666, 445), (665, 445), (665, 444), (664, 444), (664, 443), (663, 443), (663, 442), (662, 442), (662, 440), (661, 440), (661, 439), (660, 439), (660, 438), (659, 438), (659, 437), (658, 437), (658, 436), (657, 436), (657, 434), (656, 434), (656, 431), (655, 431), (655, 429), (654, 429), (654, 427), (652, 427), (652, 428), (653, 428), (653, 430), (652, 430), (652, 429), (651, 429), (651, 427), (650, 427), (650, 426), (649, 426), (649, 424), (647, 424), (647, 425), (646, 425), (646, 426), (645, 426), (645, 428), (644, 428), (644, 470), (645, 470), (645, 475), (646, 475), (646, 479), (647, 479), (647, 482), (648, 482), (648, 493), (649, 493), (649, 502), (650, 502), (650, 510), (651, 510), (651, 518), (652, 518), (652, 528), (653, 528), (653, 536), (644, 536), (644, 535), (646, 535), (646, 534), (637, 534), (637, 533), (633, 533), (633, 532), (622, 532), (622, 531), (617, 531), (617, 530), (611, 530), (611, 529), (605, 529), (605, 528), (594, 528), (594, 527), (586, 527), (586, 526), (580, 526), (580, 525), (570, 525), (570, 524), (568, 524), (568, 525), (567, 525), (567, 526), (569, 526), (569, 527), (571, 527), (571, 528), (570, 528), (570, 529), (569, 529), (569, 530), (567, 530), (567, 531), (565, 531), (565, 529), (564, 529), (564, 530), (562, 530), (562, 531), (560, 531), (560, 532), (558, 532), (558, 533), (557, 533), (557, 534), (555, 534), (555, 535), (553, 535), (553, 536), (551, 536), (551, 537), (549, 537), (549, 538), (547, 538), (547, 539), (545, 539), (545, 540), (544, 540), (544, 542), (542, 542), (542, 544), (541, 544), (541, 545), (539, 545), (539, 546), (538, 546), (538, 547), (536, 547), (536, 548), (534, 548), (534, 549), (532, 549), (532, 550), (530, 550), (530, 551), (526, 551), (526, 552), (515, 552), (515, 553), (514, 553), (514, 554), (512, 554), (512, 555), (510, 555), (510, 556), (502, 556), (502, 557), (499, 557), (499, 558), (497, 558), (497, 559), (495, 559), (495, 560), (494, 560), (494, 561), (493, 561), (493, 562), (492, 562), (492, 563), (490, 563), (490, 564), (487, 564), (487, 565), (483, 565), (483, 564), (478, 564), (478, 565), (477, 565), (477, 566), (475, 566), (475, 569), (476, 569), (476, 570), (477, 570), (477, 571), (478, 571), (478, 573), (484, 573), (484, 574), (486, 574), (486, 575), (482, 575), (482, 576), (478, 576), (478, 577), (475, 577), (475, 578), (471, 578), (471, 579), (469, 579), (469, 580), (467, 580), (467, 585), (468, 585), (468, 586), (469, 586), (469, 587), (471, 587), (471, 588), (473, 588), (473, 589), (477, 589), (477, 588), (485, 588), (485, 587), (486, 587), (486, 592), (487, 592), (487, 595), (488, 595), (488, 601), (489, 601), (489, 602), (491, 602), (491, 601), (492, 601), (492, 603), (494, 603), (494, 602), (495, 602), (495, 600), (496, 600), (496, 598), (497, 598), (497, 596), (498, 596), (498, 593), (499, 593), (499, 591), (500, 591), (500, 588), (501, 588), (501, 586), (502, 586), (502, 585), (503, 585), (503, 583), (504, 583), (504, 581), (505, 581), (505, 584), (506, 584), (506, 588), (507, 588), (507, 591), (508, 591), (508, 592), (509, 592), (509, 595), (510, 595), (510, 598), (511, 598), (511, 599), (513, 599), (513, 598), (515, 598), (515, 597), (516, 597), (516, 596), (517, 596), (517, 587), (516, 587), (516, 586), (517, 586), (517, 585), (518, 585), (518, 583), (520, 583), (520, 582), (518, 582), (518, 580), (519, 580), (519, 579), (520, 579), (520, 578), (521, 578), (521, 577), (522, 577), (522, 576), (523, 576), (523, 575), (524, 575), (524, 574), (525, 574), (525, 573), (527, 573), (527, 574), (525, 574), (525, 576), (524, 576), (524, 577), (526, 577), (526, 576), (530, 576), (530, 575), (531, 575), (531, 574), (533, 574), (533, 572), (537, 572), (537, 573), (536, 573), (536, 574), (534, 574), (534, 576), (536, 576), (536, 575), (537, 575), (537, 574), (538, 574), (538, 573), (540, 573), (540, 572), (543, 572), (543, 571), (546, 571), (546, 572), (547, 572), (547, 573), (551, 573), (551, 572), (554, 572), (554, 571), (555, 571), (555, 570), (558, 570), (558, 571), (559, 571), (559, 572), (560, 572), (560, 573), (561, 573), (561, 574), (562, 574), (562, 575), (563, 575), (563, 577), (562, 577), (562, 578), (563, 578), (563, 579), (564, 579), (564, 577), (565, 577), (565, 579), (566, 579), (566, 581), (565, 581), (565, 583), (564, 583), (564, 585), (563, 585), (563, 586), (562, 586), (562, 587), (561, 587), (561, 589), (560, 589), (560, 603), (561, 603), (561, 604), (563, 604), (563, 603), (564, 603), (564, 602), (565, 602), (565, 601), (566, 601), (566, 600), (567, 600), (567, 599), (568, 599), (568, 598), (569, 598), (569, 597), (570, 597), (570, 596), (571, 596), (571, 595), (572, 595), (572, 594), (573, 594), (573, 596), (575, 596), (575, 592), (576, 592), (576, 591), (578, 591), (578, 593), (579, 593), (579, 594), (580, 594), (580, 597), (581, 597), (581, 605), (582, 605), (582, 606), (583, 606), (583, 609), (584, 609), (584, 610), (583, 610), (583, 615), (584, 615), (584, 618), (585, 618), (585, 620), (586, 620), (586, 621), (587, 621), (587, 623), (588, 623), (588, 625), (589, 625), (589, 628), (590, 628), (590, 631), (591, 631), (591, 634), (592, 634), (592, 637), (593, 637), (593, 641), (594, 641), (594, 644), (595, 644), (595, 647), (596, 647), (596, 651), (597, 651), (597, 655), (598, 655), (598, 658), (597, 658), (597, 671), (596, 671), (596, 677), (595, 677), (595, 679), (596, 679), (596, 680), (598, 680), (598, 677), (599, 677), (599, 674), (600, 674), (600, 672), (601, 672), (601, 670), (602, 670), (602, 668), (603, 668), (603, 667), (604, 667), (604, 665), (605, 665), (605, 664), (606, 664), (606, 663), (607, 663), (607, 661), (608, 661), (608, 660), (609, 660), (609, 659), (610, 659), (610, 658), (611, 658), (611, 657), (612, 657), (612, 656), (613, 656), (613, 655), (614, 655), (614, 654), (615, 654), (615, 652), (616, 652), (616, 651), (617, 651), (617, 650), (618, 650), (618, 649), (619, 649), (619, 648), (620, 648), (620, 647), (621, 647), (621, 646), (622, 646), (622, 645), (623, 645), (623, 644), (624, 644), (624, 643), (625, 643), (625, 642), (626, 642), (626, 641), (628, 641), (628, 640), (629, 640), (629, 639), (630, 639), (630, 638), (631, 638), (631, 637), (633, 637), (633, 636), (636, 636), (636, 635), (638, 635), (638, 634), (640, 634), (640, 633), (643, 633), (643, 632), (645, 632), (645, 631), (647, 631), (647, 630), (649, 630), (649, 629), (651, 629), (651, 628), (653, 628), (653, 627), (655, 627), (655, 626), (657, 626), (657, 625), (659, 625), (659, 624), (661, 624), (661, 623), (663, 623), (663, 622), (665, 622), (665, 621), (667, 621), (667, 620), (669, 620), (669, 619), (670, 619), (670, 618), (672, 618), (672, 617), (674, 617), (674, 616), (676, 616), (676, 615), (677, 615), (677, 614), (679, 614), (679, 613), (682, 613), (682, 612), (685, 612), (685, 611), (687, 611), (687, 610), (688, 610), (688, 609), (690, 609), (690, 608), (694, 608), (694, 607), (697, 607), (697, 606), (700, 606), (700, 605), (702, 605), (702, 604), (704, 604), (704, 603), (705, 603), (705, 602), (707, 602), (707, 604), (708, 604), (708, 606), (709, 606), (709, 613), (708, 613), (708, 614), (707, 614), (707, 615), (706, 615), (706, 617), (708, 617), (708, 616), (709, 616), (709, 615), (710, 615), (710, 616), (711, 616), (711, 617), (712, 617), (712, 618), (713, 618), (713, 619), (715, 619), (715, 620), (716, 620), (716, 621), (721, 621), (721, 620), (722, 620), (722, 621), (724, 621), (724, 622), (727, 622), (727, 623), (728, 623), (728, 624), (730, 624), (730, 625), (731, 625), (731, 626), (733, 626), (733, 627), (735, 627), (735, 628), (737, 628), (737, 629), (739, 629), (739, 630), (742, 630), (742, 631), (745, 631), (745, 632), (746, 632), (746, 635), (747, 635), (747, 645), (746, 645), (746, 650), (745, 650), (745, 658), (744, 658), (744, 662), (743, 662), (743, 664), (742, 664), (742, 666), (741, 666), (741, 669), (740, 669), (740, 671), (739, 671), (739, 674), (738, 674), (738, 677), (737, 677), (737, 679), (736, 679), (736, 681), (735, 681), (735, 684), (734, 684), (734, 686), (733, 686), (733, 691), (734, 691), (734, 692), (737, 692), (737, 693), (743, 693), (743, 694), (747, 694), (747, 695), (746, 695), (746, 697), (745, 697), (745, 700), (744, 700), (744, 703), (745, 703), (745, 702), (746, 702), (746, 699), (747, 699), (747, 697), (748, 697), (748, 694), (749, 694), (749, 693), (750, 693), (750, 694), (751, 694), (751, 695), (752, 695), (752, 696), (753, 696), (753, 697), (754, 697), (754, 698), (757, 698), (757, 699), (760, 699), (760, 700), (761, 700), (761, 702), (760, 702), (760, 704), (759, 704), (759, 706), (758, 706), (758, 707), (757, 707), (757, 708), (756, 708), (756, 709), (755, 709), (755, 710), (754, 710), (754, 711), (755, 711), (755, 714), (754, 714), (754, 715), (753, 715), (753, 717), (752, 717), (752, 718), (751, 718), (751, 720), (750, 720), (750, 721), (749, 721), (749, 722), (748, 722), (748, 723), (747, 723), (747, 725), (746, 725), (746, 726), (745, 726), (745, 727), (744, 727), (744, 728), (743, 728), (743, 731), (742, 731), (742, 733), (741, 733), (741, 735), (740, 735), (740, 737), (739, 737), (739, 738), (738, 738), (738, 740), (737, 740), (737, 741), (736, 741), (736, 743), (735, 743), (735, 744), (734, 744), (734, 745), (733, 745), (733, 746), (732, 746), (732, 747), (731, 747), (731, 748), (730, 748), (730, 749), (729, 749), (729, 750), (728, 750), (728, 751), (727, 751), (727, 752), (726, 752), (726, 753), (725, 753), (725, 754), (724, 754), (724, 755), (723, 755), (723, 756), (722, 756), (722, 757), (721, 757), (721, 759), (720, 759), (720, 760), (719, 760), (719, 761), (718, 761), (718, 762), (717, 762), (717, 763), (716, 763), (716, 765), (715, 765), (715, 767), (714, 767), (714, 768), (713, 768), (713, 770), (712, 770), (712, 773), (711, 773), (711, 776), (710, 776), (710, 778), (709, 778), (709, 780), (708, 780), (708, 781), (707, 781), (707, 782), (706, 782), (706, 784), (705, 784), (705, 785), (704, 785), (704, 786), (703, 786), (703, 787), (702, 787), (702, 789), (701, 789), (701, 790), (700, 790), (700, 791), (699, 791), (699, 793), (698, 793), (698, 794), (697, 794), (697, 796), (696, 796), (696, 798), (695, 798), (695, 800), (694, 800), (694, 801), (693, 801), (693, 804), (696, 804), (696, 803), (697, 803), (697, 802), (699, 802), (699, 801), (700, 801), (700, 800), (702, 800), (702, 799), (704, 799), (704, 798), (705, 798), (705, 797), (707, 797), (707, 796), (709, 796), (709, 795), (711, 795), (711, 794), (713, 794), (713, 793), (714, 793), (714, 792), (716, 792), (716, 791), (717, 791), (717, 790), (719, 790), (719, 789), (723, 789), (723, 788), (724, 788), (724, 789), (723, 789), (723, 792), (722, 792), (722, 795), (721, 795), (721, 798), (720, 798), (720, 801), (719, 801), (719, 805), (718, 805), (718, 809), (717, 809), (717, 812), (716, 812), (716, 815), (715, 815), (715, 818), (714, 818), (714, 820), (713, 820), (713, 823), (712, 823), (712, 826), (711, 826), (711, 829), (710, 829), (710, 832), (709, 832), (709, 835), (708, 835), (708, 826), (707, 826), (707, 820), (705, 820), (705, 823), (704, 823), (704, 826), (703, 826), (703, 829), (702, 829), (702, 835), (703, 835), (703, 846), (704, 846), (704, 850), (703, 850), (703, 854), (702, 854), (702, 857), (701, 857), (701, 861), (700, 861), (700, 868), (699, 868), (699, 871), (698, 871), (698, 874), (697, 874), (697, 877), (696, 877), (696, 881), (695, 881), (695, 885), (694, 885), (694, 889), (693, 889), (693, 896), (692, 896), (692, 902), (691, 902), (691, 905), (690, 905), (690, 907), (689, 907), (689, 910), (688, 910), (688, 912), (687, 912), (687, 915), (686, 915), (686, 916), (685, 916), (685, 918), (684, 918), (684, 920), (683, 920), (683, 921), (682, 921), (682, 923), (681, 923), (681, 925), (680, 925), (680, 926), (679, 926), (679, 928), (678, 928), (678, 930), (677, 930), (677, 932), (676, 932), (676, 934), (675, 934), (675, 936), (674, 936), (674, 939), (672, 939), (672, 940), (670, 940), (670, 941), (669, 941), (669, 943), (668, 943), (668, 946), (667, 946), (667, 948), (666, 948), (666, 949), (665, 949), (665, 951), (664, 951), (664, 953), (663, 953), (663, 956), (662, 956), (662, 957), (661, 957), (661, 958), (660, 958), (660, 959), (659, 959), (659, 960), (658, 960), (658, 962), (657, 962), (657, 964), (656, 964), (656, 966), (655, 966), (655, 968), (654, 968), (654, 969), (653, 969), (653, 971), (652, 971), (652, 972), (651, 972), (651, 973), (650, 973), (650, 975), (649, 975), (649, 976), (648, 976), (648, 977), (647, 977), (647, 978), (646, 978), (646, 979), (645, 979), (645, 980), (644, 980), (644, 981), (643, 981), (643, 982), (641, 982), (641, 985), (657, 985), (657, 986), (660, 986), (660, 987), (663, 987), (663, 988), (665, 988), (665, 989), (666, 989), (666, 990), (668, 990), (668, 991), (672, 991), (672, 992), (676, 992), (676, 991), (687, 991), (687, 990), (690, 990), (690, 991), (720, 991), (720, 992), (740, 992), (740, 993), (820, 993), (820, 994), (822, 994), (822, 995), (824, 995), (824, 996), (837, 996), (837, 995), (844, 995), (844, 994), (850, 994), (850, 993), (854, 993), (854, 992), (859, 992), (859, 991), (863, 991), (863, 990), (870, 990), (870, 989), (882, 989), (882, 988), (889, 988), (889, 987), (902, 987), (902, 986), (903, 986), (903, 985), (905, 985), (905, 984), (907, 984), (907, 983), (915, 983), (915, 982), (966, 982), (966, 981), (973, 981), (973, 979), (975, 979), (975, 981), (976, 981), (976, 982), (977, 982), (977, 983), (978, 983), (978, 984), (979, 984), (979, 986), (980, 986), (980, 987), (981, 987), (981, 988), (982, 988), (982, 989), (984, 989), (984, 988), (985, 988), (985, 986), (983, 986), (983, 987), (982, 987), (982, 986), (981, 986), (981, 984), (980, 984), (980, 983), (979, 983), (979, 981), (978, 981), (978, 980), (977, 980), (977, 979), (976, 979), (976, 978), (975, 978), (975, 977), (974, 977), (974, 976), (973, 976), (973, 974), (972, 974), (972, 972), (971, 972), (971, 971), (966, 971), (966, 970), (964, 970), (964, 969), (963, 969), (963, 968), (961, 968), (961, 967), (959, 967), (959, 966), (957, 966), (957, 965), (956, 965), (956, 964), (954, 964), (954, 963), (953, 963), (953, 962), (952, 962), (952, 961), (951, 961), (951, 960), (950, 960), (950, 959), (948, 959), (948, 958), (947, 958), (947, 957), (945, 957), (945, 956), (944, 956), (944, 955), (943, 955), (943, 954), (941, 954), (941, 953), (939, 953), (939, 952), (937, 952), (937, 951), (934, 951), (934, 950), (932, 950), (932, 949), (930, 949), (930, 948), (928, 948), (928, 947), (927, 947), (927, 946), (925, 946), (925, 945), (924, 945), (924, 944), (923, 944), (923, 943), (922, 943), (922, 942), (921, 942), (921, 941), (920, 941), (920, 940), (919, 940), (919, 939), (918, 939), (918, 938), (917, 938), (917, 937), (916, 937), (916, 936), (915, 936), (915, 935), (914, 935), (914, 933), (913, 933), (913, 932), (912, 932), (912, 931), (911, 931), (911, 929), (910, 929), (910, 927), (909, 927), (909, 926), (908, 926), (908, 924), (907, 924), (907, 923), (906, 923), (906, 921), (905, 921), (905, 919), (904, 919), (904, 917), (903, 917), (903, 915), (902, 915), (902, 913), (901, 913), (901, 911), (900, 911), (900, 908), (899, 908), (899, 906), (898, 906), (898, 903), (897, 903), (897, 901), (896, 901), (896, 898), (895, 898), (895, 895), (894, 895), (894, 892), (893, 892), (893, 889), (892, 889), (892, 886), (891, 886), (891, 883), (890, 883), (890, 880), (889, 880), (889, 877), (888, 877), (888, 874), (887, 874), (887, 871), (886, 871), (886, 867), (885, 867), (885, 864), (884, 864), (884, 860), (883, 860), (883, 856), (882, 856), (882, 855), (883, 855), (883, 853), (884, 853), (884, 850), (885, 850), (885, 817), (886, 817), (886, 794), (887, 794), (887, 790), (888, 790), (888, 789), (889, 789), (889, 787), (890, 787), (890, 786), (891, 786), (891, 784), (892, 784), (892, 783), (893, 783), (893, 782), (894, 782), (894, 780), (895, 780), (895, 779), (896, 779), (896, 778), (897, 778), (897, 776), (898, 776), (898, 774), (899, 774), (899, 772), (900, 772), (900, 770), (901, 770), (901, 768), (902, 768), (902, 766), (903, 766), (903, 764), (904, 764), (904, 761), (905, 761), (905, 759), (906, 759), (906, 757), (907, 757), (907, 754), (908, 754), (908, 752), (909, 752), (909, 749), (910, 749), (910, 745), (911, 745), (911, 739), (910, 739), (910, 738), (906, 738), (906, 740), (905, 740), (905, 742), (904, 742), (904, 745), (903, 745), (903, 747), (902, 747), (902, 750), (901, 750), (901, 753), (900, 753), (900, 755), (899, 755), (899, 758), (898, 758), (898, 760), (897, 760), (897, 762), (896, 762), (896, 764), (895, 764), (895, 766), (894, 766), (894, 768), (893, 768), (893, 770), (892, 770), (892, 772), (891, 772), (891, 774), (890, 774), (890, 778), (889, 778), (889, 781), (888, 781), (888, 776), (889, 776), (889, 771), (890, 771), (890, 765), (891, 765), (891, 759), (892, 759), (892, 753), (893, 753), (893, 748), (894, 748), (894, 742), (895, 742), (895, 738), (896, 738), (896, 737), (898, 737), (898, 736), (899, 736), (899, 735), (901, 735), (901, 734), (903, 734), (903, 733), (904, 733), (904, 732), (906, 732), (906, 731), (908, 731), (908, 730), (909, 730), (909, 729), (910, 729), (910, 728), (912, 728), (912, 727), (913, 727), (913, 726), (916, 726), (916, 725), (917, 725), (917, 724), (918, 724), (918, 723), (919, 723), (919, 722), (920, 722), (920, 723), (919, 723), (919, 725), (918, 725), (918, 727), (917, 727), (917, 730), (918, 730), (918, 729), (920, 729), (920, 728), (921, 728), (921, 723), (922, 723), (922, 722), (924, 722), (924, 721), (927, 721), (927, 722), (931, 722), (931, 723), (936, 723), (936, 722), (940, 722), (940, 721), (942, 721), (942, 720), (944, 720), (944, 719), (946, 719), (946, 718), (947, 718), (947, 716), (948, 716), (948, 715), (949, 715), (949, 714), (950, 714), (950, 713), (951, 713), (951, 712), (953, 712), (953, 711), (955, 711), (955, 710), (956, 710), (956, 709), (957, 709), (957, 708), (958, 708), (958, 704), (957, 704), (957, 703), (956, 703), (956, 702), (954, 702), (954, 701), (953, 701), (953, 700), (952, 700), (952, 698), (951, 698), (951, 696), (950, 696), (950, 695), (949, 695), (949, 694), (947, 694), (947, 693), (945, 693), (945, 692), (936, 692), (936, 693), (933, 693), (933, 694), (931, 694), (931, 693), (926, 693), (926, 692), (922, 692), (922, 691), (919, 691), (919, 690), (916, 690), (916, 688), (915, 688), (915, 687), (914, 687), (914, 685), (913, 685), (913, 683), (912, 683), (912, 682), (911, 682), (911, 680), (910, 680), (910, 678), (909, 678), (909, 677), (908, 677), (908, 675), (907, 675), (907, 674), (906, 674), (906, 673), (905, 673), (905, 671), (904, 671), (904, 670), (903, 670), (903, 666), (902, 666), (902, 664), (901, 664), (901, 663), (899, 663), (899, 662), (897, 662), (897, 661), (895, 661), (895, 660), (892, 660), (892, 659), (890, 659), (890, 658), (891, 658), (891, 657), (892, 657), (892, 656), (889, 656), (889, 657), (884, 657), (884, 656), (883, 656), (883, 650), (884, 650), (884, 647), (882, 647), (882, 649), (881, 649), (881, 651), (880, 651), (880, 656), (878, 656), (878, 655), (876, 655), (876, 654), (875, 654), (875, 651), (876, 651), (876, 650), (877, 650), (877, 648), (878, 648), (878, 643), (879, 643), (879, 636), (880, 636), (880, 635), (883, 635), (883, 634), (884, 634), (884, 633), (883, 633), (883, 631), (882, 631), (882, 629), (881, 629), (881, 627), (880, 627), (880, 625), (879, 625), (879, 623), (878, 623), (878, 621), (877, 621), (877, 620), (876, 620), (876, 618), (875, 618), (875, 616), (874, 616), (874, 615), (873, 615), (873, 613), (872, 613), (872, 612), (871, 612), (871, 607), (870, 607), (870, 599), (871, 599), (871, 598), (872, 598), (872, 596), (873, 596), (873, 600), (875, 600), (875, 601), (878, 601), (878, 600), (881, 600), (881, 599), (883, 599), (883, 598), (884, 598), (884, 597), (885, 597), (885, 596), (886, 596), (886, 595), (887, 595), (887, 593), (888, 593), (888, 590), (889, 590), (889, 588), (888, 588), (888, 589), (887, 589), (887, 590), (884, 590), (884, 591), (881, 591), (881, 592), (880, 592), (880, 593), (878, 593), (878, 594), (876, 594), (876, 593), (877, 593), (877, 592), (878, 592), (878, 591), (879, 591), (879, 590), (880, 590), (880, 589), (881, 589), (881, 588), (882, 588), (882, 587), (883, 587), (883, 585), (884, 585), (884, 584), (885, 584), (885, 583), (886, 583), (886, 581), (887, 581), (887, 577), (888, 577), (888, 575), (889, 575), (889, 574), (890, 574), (890, 573), (892, 573), (892, 572), (895, 572), (895, 571), (897, 571), (897, 570), (899, 570), (899, 569), (900, 569), (900, 568), (901, 568), (901, 565), (902, 565), (902, 561), (901, 561), (901, 556), (902, 556), (902, 555), (903, 555), (903, 553), (904, 553), (904, 551), (905, 551), (905, 549), (906, 549), (906, 547), (907, 547), (907, 545), (908, 545), (908, 542), (909, 542), (909, 540), (908, 540), (908, 538), (903, 538), (903, 536), (901, 536), (901, 535), (899, 535), (899, 534), (889, 534), (889, 533), (883, 533), (883, 532), (880, 532), (880, 531), (878, 531), (878, 530), (876, 530), (876, 529), (874, 529), (874, 528), (873, 528), (873, 527), (872, 527), (872, 526), (870, 526), (870, 525), (869, 525), (869, 523), (868, 523), (868, 522), (867, 522), (867, 521), (866, 521), (866, 519), (865, 519), (865, 517), (864, 517), (864, 515), (863, 515), (863, 514), (861, 514), (861, 513), (854, 513), (854, 514), (848, 514), (848, 513), (846, 513), (846, 512), (845, 512), (845, 511), (843, 511), (843, 510), (842, 510), (842, 509), (841, 509), (841, 508), (840, 508), (840, 506), (839, 506), (839, 505), (838, 505), (838, 504), (837, 504), (837, 503), (836, 503), (836, 502), (834, 502), (834, 501), (833, 501), (833, 500), (831, 500), (831, 499), (830, 499), (830, 498), (828, 498), (828, 497), (827, 497), (827, 496), (825, 496), (825, 495), (822, 495), (822, 494), (812, 494), (812, 495), (810, 495), (810, 496), (809, 496), (809, 497), (807, 497), (807, 498), (806, 498), (806, 500), (801, 500), (801, 501), (797, 501), (797, 502), (795, 502), (795, 503), (792, 503), (792, 499), (791, 499), (791, 495), (790, 495), (790, 494), (789, 494), (789, 492), (787, 492), (787, 491), (786, 491), (786, 490), (785, 490), (785, 488), (783, 488), (783, 487), (782, 487), (782, 488), (781, 488), (781, 489), (778, 489), (778, 490), (775, 490), (775, 491), (774, 491), (774, 492), (772, 492), (772, 493), (771, 493), (771, 494), (770, 494), (770, 495), (768, 495), (768, 494), (767, 494), (767, 493), (765, 493), (765, 490), (764, 490), (764, 489), (763, 489), (763, 488), (762, 488), (762, 487), (761, 487), (761, 486), (759, 486), (759, 485), (754, 485), (754, 483), (752, 483), (752, 482), (749, 482), (749, 483), (748, 483), (748, 484), (747, 484), (747, 486), (746, 486), (746, 489), (745, 489), (745, 483), (744, 483), (744, 480), (743, 480), (743, 477), (742, 477), (742, 474), (741, 474), (741, 471), (740, 471), (740, 468), (739, 468), (739, 465), (738, 465), (738, 462), (737, 462), (737, 459), (736, 459), (736, 457), (735, 457), (735, 454), (734, 454), (734, 451), (733, 451), (733, 448), (732, 448), (732, 445), (731, 445), (731, 443), (730, 443), (730, 440), (729, 440), (729, 438), (728, 438), (728, 435), (727, 435), (727, 433), (726, 433), (726, 430), (725, 430), (725, 428), (724, 428), (724, 426), (723, 426), (723, 423), (722, 423), (722, 421), (721, 421), (721, 419), (720, 419), (720, 417), (719, 417), (719, 415), (718, 415), (718, 413), (717, 413), (717, 411), (716, 411), (716, 409), (715, 409), (715, 407), (714, 407), (714, 405), (713, 405), (713, 403), (712, 403), (712, 400), (711, 400), (711, 397), (710, 397), (710, 396), (709, 396)]

  polys[1] size=2050
    [(564, 530), (562, 530), (562, 531), (560, 531), (560, 532), (558, 532), (558, 533), (557, 533), (557, 534), (555, 534), (555, 535), (553, 535), (553, 536), (551, 536), (551, 537), (549, 537), (549, 538), (547, 538), (547, 539), (545, 539), (545, 540), (544, 540), (544, 542), (542, 542), (542, 544), (541, 544), (541, 545), (539, 545), (539, 546), (538, 546), (538, 547), (536, 547), (536, 548), (534, 548), (534, 549), (532, 549), (532, 550), (530, 550), (530, 551), (526, 551), (526, 552), (515, 552), (515, 553), (514, 553), (514, 554), (512, 554), (512, 555), (510, 555), (510, 556), (502, 556), (502, 557), (499, 557), (499, 558), (497, 558), (497, 559), (495, 559), (495, 560), (494, 560), (494, 561), (493, 561), (493, 562), (492, 562), (492, 563), (490, 563), (490, 564), (487, 564), (487, 565), (483, 565), (483, 564), (478, 564), (478, 565), (477, 565), (477, 566), (475, 566), (475, 569), (476, 569), (476, 570), (477, 570), (477, 571), (478, 571), (478, 573), (484, 573), (484, 574), (486, 574), (486, 575), (482, 575), (482, 576), (478, 576), (478, 577), (475, 577), (475, 578), (471, 578), (471, 579), (469, 579), (469, 580), (467, 580), (467, 585), (468, 585), (468, 586), (469, 586), (469, 587), (471, 587), (471, 588), (473, 588), (473, 589), (477, 589), (477, 588), (485, 588), (485, 587), (486, 587), (486, 592), (487, 592), (487, 595), (488, 595), (488, 601), (489, 601), (489, 602), (491, 602), (491, 601), (492, 601), (492, 603), (494, 603), (494, 602), (495, 602), (495, 600), (496, 600), (496, 598), (497, 598), (497, 596), (498, 596), (498, 593), (499, 593), (499, 591), (500, 591), (500, 588), (501, 588), (501, 586), (502, 586), (502, 585), (503, 585), (503, 583), (504, 583), (504, 581), (505, 581), (505, 584), (506, 584), (506, 588), (507, 588), (507, 591), (508, 591), (508, 592), (509, 592), (509, 595), (510, 595), (510, 598), (511, 598), (511, 599), (513, 599), (513, 598), (515, 598), (515, 597), (516, 597), (516, 596), (517, 596), (517, 587), (516, 587), (516, 586), (517, 586), (517, 585), (518, 585), (518, 583), (520, 583), (520, 582), (518, 582), (518, 580), (519, 580), (519, 579), (520, 579), (520, 578), (521, 578), (521, 577), (522, 577), (522, 576), (523, 576), (523, 575), (524, 575), (524, 574), (525, 574), (525, 573), (527, 573), (527, 574), (525, 574), (525, 576), (524, 576), (524, 577), (526, 577), (526, 576), (530, 576), (530, 575), (531, 575), (531, 574), (533, 574), (533, 572), (537, 572), (537, 573), (536, 573), (536, 574), (534, 574), (534, 576), (536, 576), (536, 575), (537, 575), (537, 574), (538, 574), (538, 573), (540, 573), (540, 572), (543, 572), (543, 571), (546, 571), (546, 572), (547, 572), (547, 573), (551, 573), (551, 572), (554, 572), (554, 571), (555, 571), (555, 570), (558, 570), (558, 571), (559, 571), (559, 572), (560, 572), (560, 573), (561, 573), (561, 574), (562, 574), (562, 575), (563, 575), (563, 577), (562, 577), (562, 578), (563, 578), (563, 579), (564, 579), (564, 577), (565, 577), (565, 579), (566, 579), (566, 581), (565, 581), (565, 583), (564, 583), (564, 585), (563, 585), (563, 586), (562, 586), (562, 587), (561, 587), (561, 589), (560, 589), (560, 603), (561, 603), (561, 604), (563, 604), (563, 603), (564, 603), (564, 602), (565, 602), (565, 601), (566, 601), (566, 600), (567, 600), (567, 599), (568, 599), (568, 598), (569, 598), (569, 597), (570, 597), (570, 596), (571, 596), (571, 595), (572, 595), (572, 594), (573, 594), (573, 596), (575, 596), (575, 592), (576, 592), (576, 591), (578, 591), (578, 593), (579, 593), (579, 594), (580, 594), (580, 597), (581, 597), (581, 605), (582, 605), (582, 606), (583, 606), (583, 609), (584, 609), (584, 610), (583, 610), (583, 615), (584, 615), (584, 618), (585, 618), (585, 620), (586, 620), (586, 621), (587, 621), (587, 623), (588, 623), (588, 625), (589, 625), (589, 628), (590, 628), (590, 631), (591, 631), (591, 634), (592, 634), (592, 637), (593, 637), (593, 641), (594, 641), (594, 644), (595, 644), (595, 647), (596, 647), (596, 651), (597, 651), (597, 655), (598, 655), (598, 658), (597, 658), (597, 671), (596, 671), (596, 677), (595, 677), (595, 679), (596, 679), (596, 680), (598, 680), (598, 677), (599, 677), (599, 674), (600, 674), (600, 672), (601, 672), (601, 670), (602, 670), (602, 668), (603, 668), (603, 667), (604, 667), (604, 665), (605, 665), (605, 664), (606, 664), (606, 663), (607, 663), (607, 661), (608, 661), (608, 660), (609, 660), (609, 659), (610, 659), (610, 658), (611, 658), (611, 657), (612, 657), (612, 656), (613, 656), (613, 655), (614, 655), (614, 654), (615, 654), (615, 652), (616, 652), (616, 651), (617, 651), (617, 650), (618, 650), (618, 649), (619, 649), (619, 648), (620, 648), (620, 647), (621, 647), (621, 646), (622, 646), (622, 645), (623, 645), (623, 644), (624, 644), (624, 643), (625, 643), (625, 642), (626, 642), (626, 641), (628, 641), (628, 640), (629, 640), (629, 639), (630, 639), (630, 638), (631, 638), (631, 637), (633, 637), (633, 636), (636, 636), (636, 635), (638, 635), (638, 634), (640, 634), (640, 633), (643, 633), (643, 632), (645, 632), (645, 631), (647, 631), (647, 630), (649, 630), (649, 629), (651, 629), (651, 628), (653, 628), (653, 627), (655, 627), (655, 626), (657, 626), (657, 625), (659, 625), (659, 624), (661, 624), (661, 623), (663, 623), (663, 622), (665, 622), (665, 621), (667, 621), (667, 620), (669, 620), (669, 619), (670, 619), (670, 618), (672, 618), (672, 617), (674, 617), (674, 616), (676, 616), (676, 615), (677, 615), (677, 614), (679, 614), (679, 613), (682, 613), (682, 612), (685, 612), (685, 611), (687, 611), (687, 610), (688, 610), (688, 609), (690, 609), (690, 608), (694, 608), (694, 607), (697, 607), (697, 606), (700, 606), (700, 605), (702, 605), (702, 604), (704, 604), (704, 603), (705, 603), (705, 602), (707, 602), (707, 604), (708, 604), (708, 606), (709, 606), (709, 613), (708, 613), (708, 614), (707, 614), (707, 615), (706, 615), (706, 617), (708, 617), (708, 616), (709, 616), (709, 615), (710, 615), (710, 616), (711, 616), (711, 617), (712, 617), (712, 618), (713, 618), (713, 619), (715, 619), (715, 620), (716, 620), (716, 621), (721, 621), (721, 620), (722, 620), (722, 621), (724, 621), (724, 622), (727, 622), (727, 623), (728, 623), (728, 624), (730, 624), (730, 625), (731, 625), (731, 626), (733, 626), (733, 627), (735, 627), (735, 628), (737, 628), (737, 629), (739, 629), (739, 630), (742, 630), (742, 631), (745, 631), (745, 632), (746, 632), (746, 635), (747, 635), (747, 645), (746, 645), (746, 650), (745, 650), (745, 658), (744, 658), (744, 662), (743, 662), (743, 664), (742, 664), (742, 666), (741, 666), (741, 669), (740, 669), (740, 671), (739, 671), (739, 674), (738, 674), (738, 677), (737, 677), (737, 679), (736, 679), (736, 681), (735, 681), (735, 684), (734, 684), (734, 686), (733, 686), (733, 691), (734, 691), (734, 692), (737, 692), (737, 693), (743, 693), (743, 694), (747, 694), (747, 695), (746, 695), (746, 697), (745, 697), (745, 700), (744, 700), (744, 703), (745, 703), (745, 702), (746, 702), (746, 699), (747, 699), (747, 697), (748, 697), (748, 694), (749, 694), (749, 693), (750, 693), (750, 694), (751, 694), (751, 695), (752, 695), (752, 696), (753, 696), (753, 697), (754, 697), (754, 698), (757, 698), (757, 699), (760, 699), (760, 700), (761, 700), (761, 702), (760, 702), (760, 704), (759, 704), (759, 706), (758, 706), (758, 707), (757, 707), (757, 708), (756, 708), (756, 709), (755, 709), (755, 710), (754, 710), (754, 711), (755, 711), (755, 714), (754, 714), (754, 715), (753, 715), (753, 717), (752, 717), (752, 718), (751, 718), (751, 720), (750, 720), (750, 721), (749, 721), (749, 722), (748, 722), (748, 723), (747, 723), (747, 725), (746, 725), (746, 726), (745, 726), (745, 727), (744, 727), (744, 728), (743, 728), (743, 731), (742, 731), (742, 733), (741, 733), (741, 735), (740, 735), (740, 737), (739, 737), (739, 738), (738, 738), (738, 740), (737, 740), (737, 741), (736, 741), (736, 743), (735, 743), (735, 744), (734, 744), (734, 745), (733, 745), (733, 746), (732, 746), (732, 747), (731, 747), (731, 748), (730, 748), (730, 749), (729, 749), (729, 750), (728, 750), (728, 751), (727, 751), (727, 752), (726, 752), (726, 753), (725, 753), (725, 754), (724, 754), (724, 755), (723, 755), (723, 756), (722, 756), (722, 757), (721, 757), (721, 759), (720, 759), (720, 760), (719, 760), (719, 761), (718, 761), (718, 762), (717, 762), (717, 763), (716, 763), (716, 765), (715, 765), (715, 767), (714, 767), (714, 768), (713, 768), (713, 770), (712, 770), (712, 773), (711, 773), (711, 776), (710, 776), (710, 778), (709, 778), (709, 780), (708, 780), (708, 781), (707, 781), (707, 782), (706, 782), (706, 784), (705, 784), (705, 785), (704, 785), (704, 786), (703, 786), (703, 787), (702, 787), (702, 789), (701, 789), (701, 790), (700, 790), (700, 791), (699, 791), (699, 793), (698, 793), (698, 794), (697, 794), (697, 796), (696, 796), (696, 798), (695, 798), (695, 800), (694, 800), (694, 801), (693, 801), (693, 804), (696, 804), (696, 803), (697, 803), (697, 802), (699, 802), (699, 801), (700, 801), (700, 800), (702, 800), (702, 799), (704, 799), (704, 798), (705, 798), (705, 797), (707, 797), (707, 796), (709, 796), (709, 795), (711, 795), (711, 794), (713, 794), (713, 793), (714, 793), (714, 792), (716, 792), (716, 791), (717, 791), (717, 790), (719, 790), (719, 789), (723, 789), (723, 788), (724, 788), (724, 789), (723, 789), (723, 792), (722, 792), (722, 795), (721, 795), (721, 798), (720, 798), (720, 801), (719, 801), (719, 805), (718, 805), (718, 809), (717, 809), (717, 812), (716, 812), (716, 815), (715, 815), (715, 818), (714, 818), (714, 820), (713, 820), (713, 823), (712, 823), (712, 826), (711, 826), (711, 829), (710, 829), (710, 832), (709, 832), (709, 835), (708, 835), (708, 826), (707, 826), (707, 820), (705, 820), (705, 823), (704, 823), (704, 826), (703, 826), (703, 829), (702, 829), (702, 835), (703, 835), (703, 846), (704, 846), (704, 850), (703, 850), (703, 854), (702, 854), (702, 857), (701, 857), (701, 861), (700, 861), (700, 868), (699, 868), (699, 871), (698, 871), (698, 874), (697, 874), (697, 877), (696, 877), (696, 881), (695, 881), (695, 885), (694, 885), (694, 889), (693, 889), (693, 896), (692, 896), (692, 902), (691, 902), (691, 905), (690, 905), (690, 907), (689, 907), (689, 910), (688, 910), (688, 912), (687, 912), (687, 915), (686, 915), (686, 916), (685, 916), (685, 918), (684, 918), (684, 920), (683, 920), (683, 921), (682, 921), (682, 923), (681, 923), (681, 925), (680, 925), (680, 926), (679, 926), (679, 928), (678, 928), (678, 930), (677, 930), (677, 932), (676, 932), (676, 934), (675, 934), (675, 936), (674, 936), (674, 939), (672, 939), (672, 940), (670, 940), (670, 941), (669, 941), (669, 943), (668, 943), (668, 946), (667, 946), (667, 948), (666, 948), (666, 949), (665, 949), (665, 951), (664, 951), (664, 953), (663, 953), (663, 956), (662, 956), (662, 957), (661, 957), (661, 958), (660, 958), (660, 959), (659, 959), (659, 960), (658, 960), (658, 962), (657, 962), (657, 964), (656, 964), (656, 966), (655, 966), (655, 968), (654, 968), (654, 969), (653, 969), (653, 971), (652, 971), (652, 972), (651, 972), (651, 973), (650, 973), (650, 975), (649, 975), (649, 976), (648, 976), (648, 977), (647, 977), (647, 978), (646, 978), (646, 979), (645, 979), (645, 980), (644, 980), (644, 981), (643, 981), (643, 982), (641, 982), (641, 985), (657, 985), (657, 986), (660, 986), (660, 987), (663, 987), (663, 988), (665, 988), (665, 989), (666, 989), (666, 990), (668, 990), (668, 991), (672, 991), (672, 992), (676, 992), (676, 991), (687, 991), (687, 990), (690, 990), (690, 991), (720, 991), (720, 992), (740, 992), (740, 993), (820, 993), (820, 994), (822, 994), (822, 995), (824, 995), (824, 996), (837, 996), (837, 995), (844, 995), (844, 994), (850, 994), (850, 993), (854, 993), (854, 992), (859, 992), (859, 991), (863, 991), (863, 990), (870, 990), (870, 989), (882, 989), (882, 988), (889, 988), (889, 987), (902, 987), (902, 986), (903, 986), (903, 985), (905, 985), (905, 984), (907, 984), (907, 983), (915, 983), (915, 982), (966, 982), (966, 981), (973, 981), (973, 979), (975, 979), (975, 981), (976, 981), (976, 982), (977, 982), (977, 983), (978, 983), (978, 984), (979, 984), (979, 986), (980, 986), (980, 987), (981, 987), (981, 988), (982, 988), (982, 989), (984, 989), (984, 988), (985, 988), (985, 986), (983, 986), (983, 987), (982, 987), (982, 986), (981, 986), (981, 984), (980, 984), (980, 983), (979, 983), (979, 981), (978, 981), (978, 980), (977, 980), (977, 979), (976, 979), (976, 978), (975, 978), (975, 977), (974, 977), (974, 976), (973, 976), (973, 974), (972, 974), (972, 972), (971, 972), (971, 971), (966, 971), (966, 970), (964, 970), (964, 969), (963, 969), (963, 968), (961, 968), (961, 967), (959, 967), (959, 966), (957, 966), (957, 965), (956, 965), (956, 964), (954, 964), (954, 963), (953, 963), (953, 962), (952, 962), (952, 961), (951, 961), (951, 960), (950, 960), (950, 959), (948, 959), (948, 958), (947, 958), (947, 957), (945, 957), (945, 956), (944, 956), (944, 955), (943, 955), (943, 954), (941, 954), (941, 953), (939, 953), (939, 952), (937, 952), (937, 951), (934, 951), (934, 950), (932, 950), (932, 949), (930, 949), (930, 948), (928, 948), (928, 947), (927, 947), (927, 946), (925, 946), (925, 945), (924, 945), (924, 944), (923, 944), (923, 943), (922, 943), (922, 942), (921, 942), (921, 941), (920, 941), (920, 940), (919, 940), (919, 939), (918, 939), (918, 938), (917, 938), (917, 937), (916, 937), (916, 936), (915, 936), (915, 935), (914, 935), (914, 933), (913, 933), (913, 932), (912, 932), (912, 931), (911, 931), (911, 929), (910, 929), (910, 927), (909, 927), (909, 926), (908, 926), (908, 924), (907, 924), (907, 923), (906, 923), (906, 921), (905, 921), (905, 919), (904, 919), (904, 917), (903, 917), (903, 915), (902, 915), (902, 913), (901, 913), (901, 911), (900, 911), (900, 908), (899, 908), (899, 906), (898, 906), (898, 903), (897, 903), (897, 901), (896, 901), (896, 898), (895, 898), (895, 895), (894, 895), (894, 892), (893, 892), (893, 889), (892, 889), (892, 886), (891, 886), (891, 883), (890, 883), (890, 880), (889, 880), (889, 877), (888, 877), (888, 874), (887, 874), (887, 871), (886, 871), (886, 867), (885, 867), (885, 864), (884, 864), (884, 860), (883, 860), (883, 856), (882, 856), (882, 855), (883, 855), (883, 853), (884, 853), (884, 850), (885, 850), (885, 817), (886, 817), (886, 794), (887, 794), (887, 790), (888, 790), (888, 789), (889, 789), (889, 787), (890, 787), (890, 786), (891, 786), (891, 784), (892, 784), (892, 783), (893, 783), (893, 782), (894, 782), (894, 780), (895, 780), (895, 779), (896, 779), (896, 778), (897, 778), (897, 776), (898, 776), (898, 774), (899, 774), (899, 772), (900, 772), (900, 770), (901, 770), (901, 768), (902, 768), (902, 766), (903, 766), (903, 764), (904, 764), (904, 761), (905, 761), (905, 759), (906, 759), (906, 757), (907, 757), (907, 754), (908, 754), (908, 752), (909, 752), (909, 749), (910, 749), (910, 745), (911, 745), (911, 739), (910, 739), (910, 738), (906, 738), (906, 740), (905, 740), (905, 742), (904, 742), (904, 745), (903, 745), (903, 747), (902, 747), (902, 750), (901, 750), (901, 753), (900, 753), (900, 755), (899, 755), (899, 758), (898, 758), (898, 760), (897, 760), (897, 762), (896, 762), (896, 764), (895, 764), (895, 766), (894, 766), (894, 768), (893, 768), (893, 770), (892, 770), (892, 772), (891, 772), (891, 774), (890, 774), (890, 778), (889, 778), (889, 781), (888, 781), (888, 776), (889, 776), (889, 771), (890, 771), (890, 765), (891, 765), (891, 759), (892, 759), (892, 753), (893, 753), (893, 748), (894, 748), (894, 742), (895, 742), (895, 738), (896, 738), (896, 737), (898, 737), (898, 736), (899, 736), (899, 735), (901, 735), (901, 734), (903, 734), (903, 733), (904, 733), (904, 732), (906, 732), (906, 731), (908, 731), (908, 730), (909, 730), (909, 729), (910, 729), (910, 728), (912, 728), (912, 727), (913, 727), (913, 726), (916, 726), (916, 725), (917, 725), (917, 724), (918, 724), (918, 723), (919, 723), (919, 722), (920, 722), (920, 723), (919, 723), (919, 725), (918, 725), (918, 727), (917, 727), (917, 730), (918, 730), (918, 729), (920, 729), (920, 728), (921, 728), (921, 723), (922, 723), (922, 722), (924, 722), (924, 721), (927, 721), (927, 722), (931, 722), (931, 723), (936, 723), (936, 722), (940, 722), (940, 721), (942, 721), (942, 720), (944, 720), (944, 719), (946, 719), (946, 718), (947, 718), (947, 716), (948, 716), (948, 715), (949, 715), (949, 714), (950, 714), (950, 713), (951, 713), (951, 712), (953, 712), (953, 711), (955, 711), (955, 710), (956, 710), (956, 709), (957, 709), (957, 708), (958, 708), (958, 704), (957, 704), (957, 703), (956, 703), (956, 702), (954, 702), (954, 701), (953, 701), (953, 700), (952, 700), (952, 698), (951, 698), (951, 696), (950, 696), (950, 695), (949, 695), (949, 694), (947, 694), (947, 693), (945, 693), (945, 692), (936, 692), (936, 693), (933, 693), (933, 694), (931, 694), (931, 693), (926, 693), (926, 692), (922, 692), (922, 691), (919, 691), (919, 690), (916, 690), (916, 688), (915, 688), (915, 687), (914, 687), (914, 685), (913, 685), (913, 683), (912, 683), (912, 682), (911, 682), (911, 680), (910, 680), (910, 678), (909, 678), (909, 677), (908, 677), (908, 675), (907, 675), (907, 674), (906, 674), (906, 673), (905, 673), (905, 671), (904, 671), (904, 670), (903, 670), (903, 666), (902, 666), (902, 664), (901, 664), (901, 663), (899, 663), (899, 662), (897, 662), (897, 661), (895, 661), (895, 660), (892, 660), (892, 659), (890, 659), (890, 658), (891, 658), (891, 657), (892, 657), (892, 656), (889, 656), (889, 657), (884, 657), (884, 656), (883, 656), (883, 650), (884, 650), (884, 647), (882, 647), (882, 649), (881, 649), (881, 651), (880, 651), (880, 656), (878, 656), (878, 655), (876, 655), (876, 654), (875, 654), (875, 651), (876, 651), (876, 650), (877, 650), (877, 648), (878, 648), (878, 643), (879, 643), (879, 636), (880, 636), (880, 635), (883, 635), (883, 634), (884, 634), (884, 633), (883, 633), (883, 631), (882, 631), (882, 629), (881, 629), (881, 627), (880, 627), (880, 625), (879, 625), (879, 623), (878, 623), (878, 621), (877, 621), (877, 620), (876, 620), (876, 618), (875, 618), (875, 616), (874, 616), (874, 615), (873, 615), (873, 613), (872, 613), (872, 612), (871, 612), (871, 607), (870, 607), (870, 599), (871, 599), (871, 598), (872, 598), (872, 596), (873, 596), (873, 600), (875, 600), (875, 601), (878, 601), (878, 600), (881, 600), (881, 599), (883, 599), (883, 598), (884, 598), (884, 597), (885, 597), (885, 596), (886, 596), (886, 595), (887, 595), (887, 593), (888, 593), (888, 590), (889, 590), (889, 588), (888, 588), (888, 589), (887, 589), (887, 590), (884, 590), (884, 591), (881, 591), (881, 592), (880, 592), (880, 593), (878, 593), (878, 594), (876, 594), (876, 593), (877, 593), (877, 592), (878, 592), (878, 591), (879, 591), (879, 590), (880, 590), (880, 589), (881, 589), (881, 588), (882, 588), (882, 587), (883, 587), (883, 585), (884, 585), (884, 584), (885, 584), (885, 583), (886, 583), (886, 581), (887, 581), (887, 577), (888, 577), (888, 575), (889, 575), (889, 574), (890, 574), (890, 573), (892, 573), (892, 572), (895, 572), (895, 571), (897, 571), (897, 570), (899, 570), (899, 569), (900, 569), (900, 568), (901, 568), (901, 565), (902, 565), (902, 561), (901, 561), (901, 556), (902, 556), (902, 555), (903, 555), (903, 553), (904, 553), (904, 551), (905, 551), (905, 549), (906, 549), (906, 547), (907, 547), (907, 545), (908, 545), (908, 542), (909, 542), (909, 540), (908, 540), (908, 538), (903, 538), (903, 536), (901, 536), (901, 535), (899, 535), (899, 534), (889, 534), (889, 533), (883, 533), (883, 532), (880, 532), (880, 531), (878, 531), (878, 530), (876, 530), (876, 529), (874, 529), (874, 528), (873, 528), (873, 527), (872, 527), (872, 526), (870, 526), (870, 525), (869, 525), (869, 523), (868, 523), (868, 522), (867, 522), (867, 521), (866, 521), (866, 519), (865, 519), (865, 517), (864, 517), (864, 515), (863, 515), (863, 514), (861, 514), (861, 513), (854, 513), (854, 514), (848, 514), (848, 513), (846, 513), (846, 512), (845, 512), (845, 511), (843, 511), (843, 510), (842, 510), (842, 509), (841, 509), (841, 508), (840, 508), (840, 506), (839, 506), (839, 505), (838, 505), (838, 504), (837, 504), (837, 503), (836, 503), (836, 502), (834, 502), (834, 501), (833, 501), (833, 500), (831, 500), (831, 499), (830, 499), (830, 498), (828, 498), (828, 497), (827, 497), (827, 496), (825, 496), (825, 495), (822, 495), (822, 494), (812, 494), (812, 495), (810, 495), (810, 496), (809, 496), (809, 497), (807, 497), (807, 498), (806, 498), (806, 500), (801, 500), (801, 501), (797, 501), (797, 502), (795, 502), (795, 503), (792, 503), (792, 499), (791, 499), (791, 495), (790, 495), (790, 494), (789, 494), (789, 492), (787, 492), (787, 491), (786, 491), (786, 490), (785, 490), (785, 488), (783, 488), (783, 487), (782, 487), (782, 488), (781, 488), (781, 489), (778, 489), (778, 490), (775, 490), (775, 491), (774, 491), (774, 492), (772, 492), (772, 493), (771, 493), (771, 494), (770, 494), (770, 495), (768, 495), (768, 494), (767, 494), (767, 493), (765, 493), (765, 490), (764, 490), (764, 489), (763, 489), (763, 488), (762, 488), (762, 487), (761, 487), (761, 486), (759, 486), (759, 485), (754, 485), (754, 483), (752, 483), (752, 482), (749, 482), (749, 483), (748, 483), (748, 484), (747, 484), (747, 486), (746, 486), (746, 489), (745, 489), (745, 483), (744, 483), (744, 480), (743, 480), (743, 477), (742, 477), (742, 474), (741, 474), (741, 471), (740, 471), (740, 468), (739, 468), (739, 465), (738, 465), (738, 462), (737, 462), (737, 459), (736, 459), (736, 457), (735, 457), (735, 454), (734, 454), (734, 451), (733, 451), (733, 448), (732, 448), (732, 445), (731, 445), (731, 443), (730, 443), (730, 440), (729, 440), (729, 438), (728, 438), (728, 435), (727, 435), (727, 433), (726, 433), (726, 430), (725, 430), (725, 428), (724, 428), (724, 426), (723, 426), (723, 423), (722, 423), (722, 421), (721, 421), (721, 419), (720, 419), (720, 417), (719, 417), (719, 415), (718, 415), (718, 413), (717, 413), (717, 411), (716, 411), (716, 409), (715, 409), (715, 407), (714, 407), (714, 405), (713, 405), (713, 403), (712, 403), (712, 400), (711, 400), (711, 397), (710, 397), (710, 396), (709, 396), (709, 399), (708, 399), (708, 411), (709, 411), (709, 423), (708, 423), (708, 425), (707, 425), (707, 427), (706, 427), (706, 431), (705, 431), (705, 435), (704, 435), (704, 440), (703, 440), (703, 446), (702, 446), (702, 451), (701, 451), (701, 455), (700, 455), (700, 458), (699, 458), (699, 461), (698, 461), (698, 464), (697, 464), (697, 467), (696, 467), (696, 471), (695, 471), (695, 482), (694, 482), (694, 485), (693, 485), (693, 489), (692, 489), (692, 488), (691, 488), (691, 486), (690, 486), (690, 485), (689, 485), (689, 483), (688, 483), (688, 482), (687, 482), (687, 480), (686, 480), (686, 478), (685, 478), (685, 476), (684, 476), (684, 474), (683, 474), (683, 471), (682, 471), (682, 470), (681, 470), (681, 469), (680, 469), (680, 467), (679, 467), (679, 466), (678, 466), (678, 464), (677, 464), (677, 461), (676, 461), (676, 458), (675, 458), (675, 455), (674, 455), (674, 453), (671, 453), (671, 451), (670, 451), (670, 450), (669, 450), (669, 448), (668, 448), (668, 447), (667, 447), (667, 446), (666, 446), (666, 445), (665, 445), (665, 444), (664, 444), (664, 443), (663, 443), (663, 442), (662, 442), (662, 440), (661, 440), (661, 439), (660, 439), (660, 438), (659, 438), (659, 437), (658, 437), (658, 436), (657, 436), (657, 434), (656, 434), (656, 431), (655, 431), (655, 429), (654, 429), (654, 427), (652, 427), (652, 428), (653, 428), (653, 430), (652, 430), (652, 429), (651, 429), (651, 427), (650, 427), (650, 426), (649, 426), (649, 424), (647, 424), (647, 425), (646, 425), (646, 426), (645, 426), (645, 428), (644, 428), (644, 470), (645, 470), (645, 475), (646, 475), (646, 479), (647, 479), (647, 482), (648, 482), (648, 493), (649, 493), (649, 502), (650, 502), (650, 510), (651, 510), (651, 518), (652, 518), (652, 528), (653, 528), (653, 536), (644, 536), (644, 535), (646, 535), (646, 534), (637, 534), (637, 533), (633, 533), (633, 532), (622, 532), (622, 531), (617, 531), (617, 530), (611, 530), (611, 529), (605, 529), (605, 528), (594, 528), (594, 527), (586, 527), (586, 526), (580, 526), (580, 525), (570, 525), (570, 524), (568, 524), (568, 525), (567, 525), (567, 526), (569, 526), (569, 527), (571, 527), (571, 528), (570, 528), (570, 529), (569, 529), (569, 530), (567, 530), (567, 531), (565, 531), (565, 529), (564, 529)]

  polys[2] size=8
    [(502, 590), (503, 590), (503, 592), (504, 592), (504, 589), (503, 589), (503, 588), (502, 588)]

  polys[3] size=18
    [(897, 740), (898, 740), (898, 741), (899, 741), (899, 742), (900, 742), (900, 743), (901, 743), (901, 744), (902, 744), (902, 741), (901, 741), (901, 740), (900, 740), (900, 739), (899, 739), (899, 738), (897, 738)]

  polys[4] size=4
    [(699, 840), (700, 840), (700, 839), (699, 839)]

  polys[5] size=22
    [(675, 877), (676, 877), (676, 878), (677, 878), (677, 879), (678, 879), (678, 881), (679, 881), (679, 883), (680, 883), (680, 885), (681, 885), (681, 881), (680, 881), (680, 880), (679, 880), (679, 878), (678, 878), (678, 877), (677, 877), (677, 875), (675, 875)]

```

For bit mask for `alpha_threshold = 0.0` it works fine. For bit mask for `alpha_threshold = 0.1` the `polys[0]` and `polys[1]` are the same polygon, the vertices are just cyclically shifted (`polys[0][0] == polys[1][1860]` and so on). If `simplification_epsilon > 0` would be passed to `opaque_to_polygons` then the resulting polygons would diverge (how much depends on the passed value), as they would be simplified according to their different vertices order.

So I think the first proper step (maybe there are more steps) is to fix `BitMap::clip_opaque_to_polygons`.

**Comment by AThousandShips** [comment]
The bug is solved with a grow of 2 for the cases tested on, and the options brings it in line with Sprite2D mesh construction, but I can just use the grow of two across the board if that's better

With that setting the MRP generates no degenerate polygons any longer

There could very well be some inherent bug in the BitMap code but as far as I can tell the current setup solves the bug

File: editor/editor_atlas_packer.cpp (hunk 3 above)
Comment (AThousandShips) [reply editor/editor_atlas_packer.cpp:62]: It does as far as I can tell, this is for the cells for checking overlap as far as I can tell, and polygons with a AABB smaller than 4 on a side (the standard cell size) should still be valid input I think

File: editor/import/resource_importer_texture_atlas.cpp (hunk 2 above)
Comment (AThousandShips) [reply editor/import/resource_importer_texture_atlas.cpp:137]: The check was faulty, at least in that form, might be that it should instead be based on the transposed status will check

Comment (AThousandShips) [reply editor/import/resource_importer_texture_atlas.cpp:137]: Changing it to take transposed into account resolves the problem, adding that

File: editor/import/resource_importer_texture_atlas.cpp (hunk 1 above)
Comment (AThousandShips) [reply editor/import/resource_importer_texture_atlas.cpp:272]: It does not seem to be helpful with correctly generated polygons, removing

**Comment by AThousandShips** [comment]
Adding a failure condition if there are no polygons generated

**Comment by AThousandShips** [comment]
Correction, there are still issues when comparing with the original textures

**Comment by AThousandShips** [comment]
But agreed there's absolutely something odd going on in BitMap, taking a deeper look

**Comment by AThousandShips** [comment]
I have identified some errors in the marching squares behavior, and I have some ides for solutions, will investigate and open a separate PR for this issue

**Comment by LakshayaG73** [comment]
> I have identified some errors in the marching squares behavior, and I have some ides for solutions, will investigate and open a separate PR for this issue

Hi. Is there a separate PR open?

**Comment by AThousandShips** [comment]
Not yet, I think I'm getting close to a solution though and will see about implementing it soon

**Comment by LakshayaG73** [comment]
Please keep me posted. Thanks : )

Let me know if I can help in any way

**Comment by AThousandShips** [comment]
PR for bitmap fixes is now up:
#68732

**Comment by LakshayaG73** [comment]
Great! Thank you so much. 

So, I should merge this PR and #68732 to test it out?

**Comment by AThousandShips** [comment]
Go ahead, note that I have yet to solve the gaps problem, will take that on when the BitMap stuff is done

**Comment by AThousandShips** [comment]
Now that that is merged I'll get back to the triangle drawing soon hopefully

**Comment by LakshayaG73** [comment]
Is there an issue open for the remaining piece of the puzzle? : )

**Comment by AThousandShips** [comment]
@LakshayaG73 not that I know of, I'm aiming to solve it as part of this PR but I haven't had time to look at it lately or right now, hopefully soon

**Comment by AThousandShips** [comment]
Added a new triangle raster code, still tweaking with it and will see how it turns out, this method is probably less efficient than the original, but it works (as far as I can tell) with this input, no gaps, will experiment with one closer to the original that works over a smaller area, but I don't think this method is any problem from a performance perspective.

**Comment by AThousandShips** [comment]
@LakshayaG73 it should work now for the drawing, check if you can see any errors with your work

**Comment by LakshayaG73** [comment]
What valalues should I use here? 

image

**Comment by LakshayaG73** [comment]
I tested this and running into a weird issue. 

The frames are showing up properly in the spriteframes inspector, but when I try to play the same animation there are gaps where the sprite dissapears.

**Comment by LakshayaG73** [comment]
What is the purpose of those parameters? 

As an end user, I prefer to have a working atlastexture. That's pretty much it. If tweaking that is going to give me a better result, I'd rather just stick to Region2D's instead of Meshes.

**Comment by AThousandShips** [comment]
For the specific parameters you should just see what works for you, as with anything, the grow mask should be combined with the simplification as the simplification can otherwise clip into the visible area

I thought the issue for you was the loss of the space improvements with the mesh, but what ever works best with your workflow, there's really no difference between doing this and the way it was before other than you now have more control over the way it generates the meshes, it depends on the scale of the mesh and the details of your images. The setting of zero for all parameters results in a mesh that isn't clipped at all, but one that is possibly more complex than needed.

I fail to see your issue here with having to tweak with settings, if the default settings works then use them?

I can not replicate your gaps in the playing animation in your MRP, have you reimported the textures and reloaded the scene?

**Comment by LakshayaG73** [comment]
I am grossly unaware of what these settings do. My understanding was that only certain settings will enable me to use Mesh2D's for atlas textures, and if that is the case, finding the right settings will be cumbersome. 

I also saw that these options were added to the .import file for all added group files, not sure if that is the plan. 

I added new textures, created a new atlastexture, and created a new animation from the same. In the editor itself, you could see a frame erroring out. Let me try this again in a fresh project with your latest changes.

**Comment by AThousandShips** [comment]
It is not the case that specific settings are required to make it work, that was mentioned as an issue above with the initial solution before the bugs with the polygon generation were fixed!

All settings are added like that, but good that you pointed out, could be looked into separately.

If the error persists please upload a MRP here that has the bug so I can investigate.

**Comment by LakshayaG73** [comment]
Hello! This does seem to fix it for the MRP provided. 

If you could update this, I would love to try with the latest master?

**Comment by AThousandShips** [comment]
It'd be best if you rebased it yourself, haven't worked on this lately and will come back to it when I've solved some other stuff and don't want to needlessly update the CI

**Comment by AThousandShips** [comment]
If desired I'll remove the parameters again as they originally were added to deal with the bitmap errors, which are (largely) resolved

**Comment by AThousandShips** [comment]
Now using ceil instead of treating the zero case special, can someone take a look at that, makes more sense to me than either truncation (which happens here) or rounding

File: editor/editor_atlas_packer.cpp [hunk 4]
```diff
@@ -59,7 +59,7 @@ void EditorAtlasPacker::chart_pack(Vector<Chart> &charts, int &r_width, int &r_h
 
 		Ref<BitMap> src_bitmap;
 		src_bitmap.instantiate();
-		src_bitmap->create(aabb.size / divide_by);
+		src_bitmap->create((Vector2(aabb.size) / divide_by).ceil());
```
Comment (AThousandShips) [inline editor/editor_atlas_packer.cpp:62]: Now using ceil instead of treating the zero case special, can someone take a look at that, makes more sense to me than either truncation (which happens here) or rounding

**Comment by AThousandShips** [comment]
Can split off the new settings to a separate PR if desired

File: editor/import/resource_importer_texture_atlas.cpp [hunk 5]
```diff
@@ -240,10 +255,25 @@ Error ResourceImporterTextureAtlas::import_group_file(const String &p_group_file
...
 
+			const int shrink_mask = options["shrink_mask"];
+			const int grow_mask = options["grow_mask"];
+			const float simplification = options["simplification"];
+
 			Ref<BitMap> bit_map;
 			bit_map.instantiate();
-			bit_map->create_from_image_alpha(image);
-			Vector<Vector<Vector2>> polygons = bit_map->clip_opaque_to_polygons(Rect2(0, 0, image->get_width(), image->get_height()));
+			bit_map->create_from_image_alpha(image, 0);
```
Comment (AThousandShips) [inline editor/import/resource_importer_texture_atlas.cpp:264]: The change to 0 threshold is as the default of 0.1 can create sharp edges of the transparent gradient

**Comment by AThousandShips** [comment]
Removed the new options and will possibly add them in a feature improvement PR, but keeping it simple for now

**Review by kleonc — APPROVED** [review]
LGTM. Should be fine to include in 4.1, seems like "simple" fixes. :+1:

@AThousandShips Sorry for the late review and thanks for all the patience! :upside_down_face:

**Comment by AThousandShips** [comment]
No worries! Been in my backlog and happy to see it merged!

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!
