### PR TITLE
Removed unnecessary error from _area_inout

### LINKED ISSUE #28022: Error when moving an Area2D that monitors but isn't monitorable out of another Area2D
**Godot version:**
3.1.stable.mono.official

**OS/device including version:**
Windows 10 Home 1809

**Issue description:**
When I moved an Area2D that monitors but isn't monitorable outside of another Area2D , the error `Condition ' !area_in && !E ' is true.` was thrown. I expected nothing to happen.

**Steps to reproduce:**
Have two Area2Ds intersecting, with both monitoring, but only one monitorable.
 Move one in the remote scene so the two Area2Ds no longer intersect.

**Minimal reproduction project:**

[Area2D Error.zip](https://github.com/godotengine/godot/files/3077755/Area2D.Error.zip)

### PR DESCRIPTION
**Pull request by CatThingy**
The error was previously removed from _body_inout
for the same reason. Fixes #28022.

### CODE REVIEW

File: scene/2d/area_2d.cpp [hunk 1]
```diff
@@ -261,8 +261,9 @@ void Area2D::_area_inout(int p_status, const RID &p_area, int p_instance, int p_
 
 	Map<ObjectID, AreaState>::Element *E = area_map.find(objid);
 
-	ERR_FAIL_COND(!area_in && !E);
-
+	if (!body_in && !E) {
```
Comment (akien-mga) [inline scene/2d/area_2d.cpp]: Should be `area_in`. This doesn't build.

Comment (CatThingy) [reply scene/2d/area_2d.cpp]: My bad, fixed

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.1.
