### PR TITLE
Enhance bindings of deep resource duplication

### LINKED ISSUE #107138: `ResourceDeepDuplicateMode` enum is wrongly formatted as a global enum in `extension_api.json` in method definitions.
### Tested versions

- Introduced in: https://github.com/godotengine/godot/pull/100673, https://github.com/godotengine/godot/commit/63dff62948f94c966ad6349a098bb39c88cc342a
- Still persist in `978b38797` (current master).

### System information

Any.

### Issue description

In `extension_api.json` `ResourceDeepDuplicateMode` enum is being marked as a global EngineEnum (enum::ResourceDeepDuplicateMode) instead of class enum (i.e. it should be something along the lines of: `enum::Resource.ResourceDeepDuplicateMode`).

Usually class enums in methods are marked as:

<details>
<summary> Example of properly marked class & global enums in method signature in extension api dump. </summary>

```json
{
	"name": "load_threaded_request",
	"is_const": false,
	"is_vararg": false,
	"is_static": false,
	"is_virtual": false,
	"hash": 3614384323,
	"hash_compatibility": [
		1939848623
	],
	"return_value": {
		"type": "enum::Error"
	},
	"arguments": [
		{
			"name": "path",
			"type": "String"
		},
		{
			"name": "type_hint",
			"type": "String",
			"default_value": "\"\""
		},
		{
			"name": "use_sub_threads",
			"type": "bool",
			"default_value": "false"
		},
		{
			"name": "cache_mode",
			"type": "enum::ResourceLoader.CacheMode",
			"default_value": "1"
		}
	]
},
```

```json
{
	"name": "push_paragraph",
	"is_const": false,
	"is_vararg": false,
	"is_static": false,
	"is_virtual": false,
	"hash": 3089306873,
	"hash_compatibility": [
		3218895358
	],
	"arguments": [
		{
			"name": "alignment",
			"type": "enum::HorizontalAlignment"
		},
		{
			"name": "base_direction",
			"type": "enum::Control.TextDirection",
			"default_value": "0"
		},
		{
			"name": "language",
			"type": "String",
			"default_value": "\"\""
		},
		{
			"name": "st_parser",
			"type": "enum::TextServer.StructuredTextParser",
			"default_value": "0"
		},
		{
			"name": "justification_flags",
			"type": "bitfield::TextServer.JustificationFlag",
			"default_value": "163"
		},
		{
			"name": "tab_stops",
			"type": "PackedFloat32Array",
			"default_value": "PackedFloat32Array()"
		}
	]
},
```

</details>

While `ResourceDeepDuplicateMode` is being specified as:

<details>

```json
{
	"name": "duplicate_deep",
	"is_const": true,
	"is_vararg": false,
	"is_static": false,
	"is_virtual": false,
	"hash": 1807532819,
	"return_value": {
		"type": "Resource"
	},
	"arguments": [
		{
			"name": "deep_subresources_mode",
			"type": "enum::ResourceDeepDuplicateMode",
			"default_value": "1"
		}
	]
}
```

</details>

---------------------

[This broke our codegen](https://github.com/godot-rust/gdext/issues/1181).

Said enum is bound as:
image

Instead of, for example
image

which desugars to:

```cpp
#define BIND_ENUM_CONSTANT(m_constant) \
    ::ClassDB::bind_integer_constant(get_class_static(), __constant_get_enum_name(m_constant, #m_constant), #m_constant, m_constant);
```

https://github.com/godotengine/godot/blob/99f5a3d665cfcc517b0b4b55d8668c2116effb69/core/variant/type_info.h#L207-L210

https://github.com/godotengine/godot/blob/99f5a3d665cfcc517b0b4b55d8668c2116effb69/core/object/class_db.cpp#L1111

### Steps to reproduce

1. Dump extension API: `./godot_editor --headless --dump-extension-api`
2. Analyze the dump.

### Minimal reproduction project (MRP)

`./godot_editor --headless --dump-extension-api`.

### PR DESCRIPTION
**Pull request by RandomShaper**
Two changes:
1. `Variant.duplicate_deep()` argument is now told to be of the type `enum::Resource.DeepDuplicateMode`, instead of the wrong seemingly global `enum::Resource.DeepDuplicateMode`. See the excerpt below.
2. A few renames are made in the bindings, to remove the redundant 'resource' word. This is why I marked this PR as compat breaking. However, let's bear in mind this is compat breakage compared to prev 4.5 releases. Renames are these:
   - `Resource.ResourceDeepDuplicateMode` -> `Resource.DeepDuplicateMode`
   - `Resource.RESOURCE_DEEP_DUPLICATE_*` -> `Resource.DEEP_DUPLICATE_*`

---

Now, `Variang::deep_duplicate()` looks like this in the API JSON:
```js
{
	"name": "duplicate_deep",
	// [...]
	"arguments": [
		{
			"name": "deep_subresources_mode",
			"type": "enum::Resource.DeepDuplicateMode", // <-- This is the improvement.
			"default_value": "1"
		}
	]
}
```

Fixes #107138.

### CODE REVIEW

**Review by AThousandShips — APPROVED** [review]
Makes sense to me

File: core/io/resource.cpp [hunk 1]
```diff
@@ -724,12 +728,13 @@ void Resource::_bind_methods() {
...
 
 	ClassDB::bind_method(D_METHOD("duplicate", "deep"), &Resource::duplicate, DEFVAL(false));
-	ClassDB::bind_method(D_METHOD("duplicate_deep", "deep_subresources_mode"), &Resource::duplicate_deep, DEFVAL(RESOURCE_DEEP_DUPLICATE_INTERNAL));
+	ClassDB::bind_method(D_METHOD("duplicate_deep", "deep_subresources_mode"), &Resource::_duplicate_deep_bind, DEFVAL(RESOURCE_DEEP_DUPLICATE_INTERNAL));
 
 	// For the bindings, it's much more natural to expose this enum from the Variant realm via Resource.
-	ClassDB::bind_integer_constant(get_class_static(), StringName("ResourceDeepDuplicateMode"), "RESOURCE_DEEP_DUPLICATE_NONE", RESOURCE_DEEP_DUPLICATE_NONE);
-	ClassDB::bind_integer_constant(get_class_static(), StringName("ResourceDeepDuplicateMode"), "RESOURCE_DEEP_DUPLICATE_INTERNAL", RESOURCE_DEEP_DUPLICATE_INTERNAL);
-	ClassDB::bind_integer_constant(get_class_static(), StringName("ResourceDeepDuplicateMode"), "RESOURCE_DEEP_DUPLICATE_ALL", RESOURCE_DEEP_DUPLICATE_ALL);
+	// Therefore, we can't use BIND_ENUM_CONSTANT here because it would
```
Comment (akien-mga) [inline core/io/resource.cpp]: Missing the end of this sentence.

Wouldn't it make sense to just duplicate (heh) this enum in Resource so it can be exposed normally, and just cast it to the Variant one where relevant?

Comment (RandomShaper) [reply core/io/resource.cpp]: I guess so. On the one hand, this case is already very special (the enum is global in C++ but scoped to `Resource` for scripting), so a little bit of special binding code doesn't seem out of place and makes the "bridging" very explicit. Not having to repeat the enum with the `RESOURCE_` prefixes removed is an upside as well. On the other hand, what you suggest is more similar to what is already happening with certain enums in `core_bind.h`. If you ask me, I'd take the opposite direction, that is, integrating those duplicates.

I don't really have a strong opinion beyond personal taste.

In the meantime, I've fixed the sentence.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
