### PR TITLE
Fix for stopping the Undo History being desynchronized from actual Undo queue

### LINKED ISSUE #83945: Using the Color Picker screws up/desynchronises Undo History
### Godot version

v4.2.beta2.official 

### System information

Windows 10

### Issue description

The Colour Picker seems to add Undo steps that do not appear in the Undo history. This can lead to you undoing several colour changes that you did while the Colour Picker was open, while your position in the Undo History moved onto events you did before even opening the Colour Picker.

Discovered while investigating Issue #83642

### Steps to reproduce

1. Create a 2D scene and add a simple sprite.
2. Open up the history tab (maybe move it so it and the Inspector are both visible at the same time)
3. Do some standard manipulation to the sprite (moving, visibility toggle, etc), observing how the actions get added in the History tab.
4. The open the color picker, and with the picker open, change the Modulate colour a several times, try different swatches, hues, etc.
5. Close the color picker.
6. Try to undo and redo the last few operations. While keeping an eye on the History windows

Expected:
Your position in the History list should correspond to the actions you are doing/undoing.

Actual:
Things get desynched. Somehow the history queue only lists about 2 modulate actions (despite only opening up the picker once). Yet you can undo through several different colour changes that you did while the picker was open. This leads to the history queue listing that you are undoing a move or visiblity operation, when you're still undoing modulate colour changes.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by TheSofox**
Fix for Issue #83945 

The Undo History was getting desynched from the actual Undo queue. The reason is that the editor_undo_redo_manager.cpp (which handles History) and undo_redo.cpp (which handles actual Undo functionality) did their own parallel checks for whether the latest action should be merged with the previous one.

My fix eliminates the checks in editor_undo_redo_manager.cpp and simply queries undo_redo as to whether it merged the latest action. If so, it doesn't create a new action in the History list.

This ensures the two don't get desynched from different ideas about merging, and also future proofs it. Since all the rules for merging are in undo_redo.cpp, they can be changed there without having to also change the rules in editor_undo_redo_manager.cpp (DRY principal)

_Production edit: Fixes https://github.com/godotengine/godot/issues/83945_

### CODE REVIEW

File: editor/editor_undo_redo_manager.cpp [hunk 1]
```diff
@@ -248,42 +249,16 @@ void EditorUndoRedoManager::commit_action(bool p_execute) {
...
-					is_committing = false;
-					emit_signal(SNAME("history_changed"));
-					return;
-				}
-			} break;
-		}
+	if(merging) {
+		pending_action = Action();
+		is_committing = false;
+		emit_signal(SNAME("history_changed"));
```
Comment (AThousandShips) [inline editor/editor_undo_redo_manager.cpp:255]: Move these two shared lines out of the statement

File: editor/editor_undo_redo_manager.cpp [hunk 2]
```diff
@@ -248,42 +249,16 @@ void EditorUndoRedoManager::commit_action(bool p_execute) {
...
-				const Action &prev_action = history.undo_stack.back()->get();
-				if (pending_action.merge_mode == prev_action.merge_mode && pending_action.action_name == prev_action.action_name) {
-					pending_action = Action();
-					is_committing = false;
-					emit_signal(SNAME("history_changed"));
-					return;
-				}
-			} break;
-		}
+	if(merging) {
```
Comment (AThousandShips) [inline editor/editor_undo_redo_manager.cpp:252]:
```suggestion
	if (merging) {
```

File: editor/editor_undo_redo_manager.cpp (hunk 1 above)
Comment (TheSofox) [reply editor/editor_undo_redo_manager.cpp:255]: Will push change in a sec.

Comment (TheSofox) [reply editor/editor_undo_redo_manager.cpp]: Change made

File: editor/editor_undo_redo_manager.cpp [hunk 3]
```diff
@@ -248,39 +249,10 @@ void EditorUndoRedoManager::commit_action(bool p_execute) {
...
-				const Action &prev_action = history.undo_stack.back()->get();
-				if (pending_action.merge_mode == prev_action.merge_mode && pending_action.action_name == prev_action.action_name) {
-					pending_action = Action();
-					is_committing = false;
-					emit_signal(SNAME("history_changed"));
-					return;
-				}
-			} break;
-		}
+	if(false == merging) {
```
Comment (AThousandShips) [inline editor/editor_undo_redo_manager.cpp:252]:
```suggestion
	if (!merging) {
```

File: core/object/undo_redo.cpp [hunk 4]
```diff
@@ -510,6 +514,7 @@ void UndoRedo::_bind_methods() {
 
 	ClassDB::bind_method(D_METHOD("has_undo"), &UndoRedo::has_undo);
 	ClassDB::bind_method(D_METHOD("has_redo"), &UndoRedo::has_redo);
+	ClassDB::bind_method(D_METHOD("is_merging"), &UndoRedo::is_merging);
```
Comment (KoBeWi) [inline core/object/undo_redo.cpp:517]: You don't need to bind the method, it can be internal.

Comment (TheSofox) [reply core/object/undo_redo.cpp]: Removed the binding

**Review by KoBeWi — APPROVED** [review]
I can't believe it was always this simple to handle 🤦‍♂️

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
