### PR TITLE
Fix native popup menus position in embedded windows.

### LINKED ISSUE #102060: Native MenuPopup Within MenuBar shows in random location
### Tested versions

v4.3.stable.steam [77dcf97d8]

### System information

Godot v4.3.stable (77dcf97d8) - Windows 10.0.26100 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 32.0.11027.1003) - AMD Ryzen 7 2700 Eight-Core Processor (16 Threads)

### Issue description

When creating a MenuBar with a PopupMenu that has `prefer_native_menu=ture`, the menu doesn't show in the correct location (Under the selected menu item). In the attached project it is showing above the window, in my actual application it is showing to the right of my window. I have tested all options of `system_menu_id`, but none seem to affect the position.

Image

Not sure if this is related to #93622, as this happens all the time, and not just after the first time. Also this doesn't use an code.

### Steps to reproduce

- Create a new scene
- Create a `Node` as the scene root
- Add a `MenuBar` as a child of the root
- Add a `MenuPopup` as a child of `MenuBar`
- Set `prefer_native_menu` to `true` on the `MenuPopup` in the Inspector

### Minimal reproduction project (MRP)

[native-menu.zip](https://github.com/user-attachments/files/18550543/native-menu.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/102060

### CODE REVIEW

File: scene/gui/popup_menu.cpp [hunk 1]
```diff
@@ -2967,7 +2967,15 @@ void PopupMenu::popup(const Rect2i &p_bounds) {
 #endif
 
 	if (native) {
-		NativeMenu::get_singleton()->popup(global_menu, (p_bounds != Rect2i()) ? p_bounds.position : get_position());
+		Point2i popup_pos = (p_bounds != Rect2i()) ? p_bounds.position : get_position();
+		if (is_embedded()) {
+			popup_pos = get_embedder()->get_screen_transform().xform(popup_pos); // Note: for embedded windows "screen transform" is transform relative to embedder not the actual screen.
+			DisplayServer::WindowID wid = get_window_id() != DisplayServer::INVALID_WINDOW_ID ? get_window_id() : DisplayServer::MAIN_WINDOW_ID;
```
Comment (KoBeWi) [inline scene/gui/popup_menu.cpp:2973]: `get_window_id()` isn't exactly trivial, so it would be better to avoid needlessly calling it twice.

File: scene/gui/popup_menu.cpp [hunk 2]
```diff
@@ -2995,7 +3003,15 @@ void PopupMenu::set_visible(bool p_visible) {
...
-			NativeMenu::get_singleton()->popup(global_menu, get_position());
+			Point2i popup_pos = get_position();
+			if (is_embedded()) {
+				popup_pos = get_embedder()->get_screen_transform().xform(popup_pos); // Note: for embedded windows "screen transform" is transform relative to embedder not the actual screen.
+				DisplayServer::WindowID wid = get_window_id() != DisplayServer::INVALID_WINDOW_ID ? get_window_id() : DisplayServer::MAIN_WINDOW_ID;
+				popup_pos += DisplayServer::get_singleton()->window_get_position(wid);
+			}
+			float win_scale = get_parent_visible_window()->get_content_scale_factor();
+			NativeMenu::get_singleton()->set_minimum_width(global_menu, get_size().x * win_scale);
+			NativeMenu::get_singleton()->popup(global_menu, popup_pos);
```
Comment (KoBeWi) [inline scene/gui/popup_menu.cpp:3014]: Duplicate code, could be a method.

**Review by KoBeWi — APPROVED** [review]
Fixes the bug on Windows.

File: scene/gui/popup_menu.cpp (hunk 2 above)
Comment (bruvzg) [reply scene/gui/popup_menu.cpp]: Moved it to `_native_popup` method.

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected on Windows 11 24H2.

image

`canvas_items` scaling:

image

`canvas_items` scaling + 150% Windows scale:

image

Note that changes to the Windows display scale only affect Godot after a restart. This applies to its native popups, but also its window border. Compare this with Windows Explorer which updates its scale instantly:

image

**Comment by Repiteo** [comment]
Thanks!
