### PR TITLE
[HTTP] Implement streaming decompression.

### LINKED ISSUE #65635: HTTPRequest saves broken files when compressed response
### Godot version

Godot_v4.0-alpha16_linux.x86_64

### System information

Ubuntu 22.04

### Issue description

Using HTTPRequest to download a file that comes compressed (indicating compression on the headers "Content-Encoding: gzip" ) results on a damaged file.

### Steps to reproduce

```
func _ready():
    var http_request_content = HTTPRequest.new()
    add_child(http_request_content)
    http_request_content.download_file = "res://model.glb"
    http_request_content.request("https://peer-ec1.decentraland.org/content/contents/Qme9A3srMJdvgoeVp4B7xeQZKhvZ4R1ngEzPdU2jbsBYqD")
```
    
After running the script the file `model.glb` should be a valid glTF file, but is not

Workaround: adding the line `http_request_content.accept_gzip = false`

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Faless**
In this PR:
- Adds a `StreamPeerGZIP` (currently exposed, but might need discussion on the API, so we could decide to skip registration for now).
- HTTPRequest now decompress the body on the fly, this involves extra copying in some cases, and might result in higher memory footprint for small files, but will result in dramatically lower memory usage for bigger files since it does not require allocating the whole file in memory twice.
- Some refactor to HTTPRequest to only use on `SNAME`.

Supersedes #55946 .

Draft status:
- ~Documentation if we decide to expose it.~
  Documentation added, but let me know if we should unexpose it.

Stream test:

```gdscript
func _ready():
	var text = "TestTestTestTestTestTestTestTestTestTestTestTest"
	var bytes = text.to_utf8_buffer()
	var deflate = false
	var compression = File.COMPRESSION_DEFLATE if deflate else File.COMPRESSION_GZIP
	var compressor = StreamPeerGZIP.new()
	compressor.start_compression(deflate)
	# Add some
	print(compressor.put_data(bytes))
	# Add some more
	print(compressor.put_data(bytes))
	# Write end of stream
	print(compressor.finish())
	# Read all
	var buf = compressor.get_data(compressor.get_available_bytes())[1]
	# Compare
	var cmp = PackedByteArray(); cmp.append_array(bytes); cmp.append_array(bytes)
	assert(Array(buf) == Array(cmp.compress(compression)))

	# Write to file (check the content with an advanced editor like vim)
	var f = File.new()
	f.open("test.gz", File.WRITE)
	f.store_buffer(buf)
	f.close()

	# Decompress
	compressor.clear()
	compressor.start_decompression(deflate)
	print(buf.size())
	compressor.put_data(buf)
	var out = compressor.get_data(compressor.get_available_bytes())[1]
	print(out.get_string_from_utf8())
```

HTTP Test:
```gdscript
extends HTTPRequest

func _ready():
	download_file = "./index.html"
	request("https://www.wikipedia.org/")
	request_completed.connect(self._completed)


func _completed(status, code, headers, body):
	var f = File.new()
	f.open(download_file, File.READ)
	printt(get_downloaded_bytes(), f.get_length(), body.size())
```

Fixes #65635 .
Possible solution for #28999 (can open gzip and stream-decompress, though it does not really fix the open_compressed issue itself).

### CODE REVIEW

File: core/io/stream_peer_gzip.h [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+
+#include "core/core_bind.h"
+#include "core/io/compression.h"
+#include "core/templates/ring_buffer.h"
+
+class StreamPeerGZIP : public StreamPeer {
+	GDCLASS(StreamPeerGZIP, StreamPeer);
+
+private:
+	void *ctx = nullptr; // Will hold our z_stream insteance.
```
Comment (akien-mga) [inline core/io/stream_peer_gzip.h:44]:
```suggestion
	void *ctx = nullptr; // Will hold our z_stream instance.
```

File: scene/main/http_request.cpp [hunk 2]
```diff
@@ -375,88 +391,74 @@ bool HTTPRequest::_update_connection() {
 			}
 
 			PackedByteArray chunk = client->read_response_body_chunk();
+			downloaded.add(chunk.size());
+
+			// Decompress chunk if needed
```
Comment (akien-mga) [inline scene/main/http_request.cpp:396]: Nitpick:
```suggestion
			// Decompress chunk if needed.
```

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Comment by akien-mga** [comment]
Sorry it's really picky :P
```diff
diff --git a/doc/classes/StreamPeerGZIP.xml b/doc/classes/StreamPeerGZIP.xml
index 663992d..71dd361 100644
--- a/doc/classes/StreamPeerGZIP.xml
+++ b/doc/classes/StreamPeerGZIP.xml
@@ -1,5 +1,5 @@
 <?xml version="1.0" encoding="UTF-8" ?>
-<class name="StreamPeerGZIP" inherits="StreamPeer" version="4.0" is_experimental="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
+<class name="StreamPeerGZIP" inherits="StreamPeer" is_experimental="true" version="4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
 	<brief_description>
 		Stream peer handling GZIP and deflate compression/decompresison.
 	</brief_description>
```
(Another argument for refactoring this so it's defined via a macro and not manually in the XML.)

**Comment by akien-mga** [comment]
Thanks!
