### PR TITLE
Fix safe area regression on older Android versions

### LINKED ISSUE #109768: Godot4.5 safe area is incorrect on Android 7
### Tested versions

4.5 beta5
Android 7.1.2
Redmi 5

### System information

Godot v4.5.beta5 - macOS Sonoma (14.5.0) - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - AMD Radeon Pro 560X OpenGL Engine - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 threads) - 16.00 GiB memory

### Issue description

DisplayServer.get_display_safe_area() returns a rect which excludes the hidden system bar. In export settings, immersive mode is on, edge to edge is off. My device has no cutout. The safe area should cover the whole screen as v4.4 did. This only occurs on my Android 7 device.

It works fine on my Android 10 and 15 devices. 

### Steps to reproduce

Create empty scene and print DisplayServer.get_display_safe_area()
Export Android
Run on Android 7 device

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by syntaxerror247**
Fixes https://github.com/godotengine/godot/issues/109768

### CODE REVIEW

File: platform/android/java/lib/src/org/godotengine/godot/GodotIO.java [hunk 1]
```diff
@@ -225,7 +225,12 @@ public int[] getDisplaySafeArea() {
 		}
 
 		if (topView != null) {
-			int insetTypes = WindowInsetsCompat.Type.systemBars() | WindowInsetsCompat.Type.displayCutout();
+			int insetTypes;
+			if (godot.isInImmersiveMode() && Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/GodotIO.java]: Why the check for versions less than Q?

Comment (syntaxerror247) [reply platform/android/java/lib/src/org/godotengine/godot/GodotIO.java]: As reported in the issue, it's working as expected on Android 10 and newer. It likely issue with API because Type.SystemBars() should return 0 here. So, I am keeping it only for affected versions.

Comment (syntaxerror247) [reply platform/android/java/lib/src/org/godotengine/godot/GodotIO.java]: It'd help to identify that it can be removed if we stop supporting older versions.

**Comment by llama-nl** [comment]
Do you have any test project?

**Comment by syntaxerror247** [comment]
> Do you have any test project?

Just export an empty project with immersive enabled.

@llama-nl [safe_area_test.zip](https://github.com/user-attachments/files/21917045/safe_area_test.zip)

File: platform/android/java/lib/src/org/godotengine/godot/GodotIO.java (hunk 1 above)
Comment (m4gr3d) [reply platform/android/java/lib/src/org/godotengine/godot/GodotIO.java]: @syntaxerror247 Using the Android emulator I get the same bug on newer versions of Android, so I think we should remove the version check and just check for the display cutout when in immersive mode.

Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/GodotIO.java]:
```suggestion
			if (godot.isInImmersiveMode()) {
```

**Review by m4gr3d — CHANGES_REQUESTED** [review]

File: platform/android/java/lib/src/org/godotengine/godot/GodotIO.java (hunk 1 above)
Comment (syntaxerror247) [reply platform/android/java/lib/src/org/godotengine/godot/GodotIO.java]: Hm.. that's interesting because I can't reproduce it on my Android 11 and 15 device (haven't tested on emulator). Can you please let me know on what version you reproduced it?

I've removed the checks though

**Review by m4gr3d — APPROVED** [review]

File: platform/android/java/lib/src/org/godotengine/godot/GodotIO.java (hunk 1 above)
Comment (m4gr3d) [reply platform/android/java/lib/src/org/godotengine/godot/GodotIO.java]: So you're right; it's not reproducible on Android 11 and higher, but it's reproducible on Android 10 (API 29).

So your previous logic would have worked with the following update:
```
if (godot.isInImmersiveMode() && Build.VERSION.SDK_INT <= Build.VERSION_CODES.Q)
```

But I think this version is better regardless.

Comment (syntaxerror247) [reply platform/android/java/lib/src/org/godotengine/godot/GodotIO.java]: I assumed it was fine on Android 10 since @abcjjy mentioned it wasn’t reproducible there (https://github.com/godotengine/godot/issues/109768). But since you’re able to reproduce it on Android 10, it seems the current version is indeed the safer approach.

**Comment by Repiteo** [comment]
Thanks!
