### PR TITLE
Add permission request for Apple embedded platforms, fix microphone input

### LINKED ISSUE #12563: Godot's iOS support does not have support for request_permission
### Tested versions

Godot 4.4 and 4.5

### System information

iOS

### Issue description

Adding this bug so this can be referenced from other issues.

iOS has a comprehensive list of features that are gated behind the user allowing the operation to take place. 

In the context of Godot, the following would be necessary for parity with Android:

* Microphone access

But it might also be useful to define the support for accessing other elements like the camera, the media library, photos, and location services.

### Steps to reproduce

No steps, the feature does not exist and it is not possible for applications to request microphone access

### Minimal reproduction project (MRP)

I used this one
https://github.com/godotengine/godot-demo-projects/tree/master/audio/mic_record

### LINKED ISSUE #33885: AudioStreamMicrophone is broken on iOS hardware
**Godot version:**
v3.1.1.stable.official

**OS/device including version:**
iOS 13.1

**Issue description:**
The audio input (Microphone) on iOS hardware does not work. It works on the simulator.

There are three separate issues causing this:
  1. no microphone permission string in info.plist in XCode export by default (already reported in issue #30307)
  2. the incorrect AVAudioSession.AudioSessionCategory is set at startup in app_delegate.mm. It works when changed to AVAudioSessionCategoryPlayAndRecord, ie:
```[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord error:nil]; ```
Maybe this should be configurable from the Godot export settings, or inferred from the sound bus usage?

3. a "-50" error from AudioUnitRender in audio_driver_coreaudio.cpp whenever microphone input is enabled. This is because bufferList.mBuffers[0].mDataByteSize is too small, since there is a mismatch between the capture buffer format and the audio device.

**Steps to reproduce:**
 1. Download minimal reproduction project below
 2. Disable mute on the bus panel in Godot to ensure audio input and output occurs simultaneously.
 3. Export to iOS build
 4. Install .ipa on iOS hardware, and the app will fail to start or record.
 5. Open XCode and install on simulator - observe that audio recording works properly.

**Minimal reproduction project:**
This project will trigger it on iOS hardware (but works fine on the simulator). You may need to unmute audio on the "Record" bus, so that audio is input and output simultaneously:
https://github.com/godotengine/godot-demo-projects/tree/master/audio/mic_record

### PR DESCRIPTION
**Pull request by paddy-exe**
Supersedes https://github.com/godotengine/godot/pull/107233 
Fixes https://github.com/godotengine/godot-proposals/issues/12563 
Fixes https://github.com/godotengine/godot/issues/33885

Superseding Miguel's PR to get it in during the beta stage.

@bruvzg I applied the patch file you suggested to @migueldeicaza 's PR.

### CODE REVIEW

File: drivers/apple_embedded/os_apple_embedded.mm [hunk 1]
```diff
@@ -733,4 +734,35 @@ Rect2 fit_keep_aspect_covered(const Vector2 &p_container, const Vector2 &p_rect)
...
+				// Permission already granted, you can start recording.
+				return true;
+			} else if (permission == AVAudioApplicationRecordPermissionDenied) {
+				// Permission denied, or not yet granted
+				return false;
+			} else {
+				// Request the permission, but for now return false as documented
+				[AVAudioApplication requestRecordPermissionWithCompletionHandler:^(BOOL granted) {
+					get_main_loop()->emit_signal(SNAME("on_request_permissions_result"), p_name, granted);
+				}];
```
Comment (akien-mga) [inline drivers/apple_embedded/os_apple_embedded.mm]:
```suggestion
			} else if (permission == AVAudioApplicationRecordPermissionDenied) {
				// Permission denied, or not yet granted.
				return false;
			} else {
				// Request the permission, but for now return false as documented.
				[AVAudioApplication requestRecordPermissionWithCompletionHandler:^(BOOL granted) {
					get_main_loop()->emit_signal(SNAME("on_request_permissions_result"), p_name, granted);
				}];
```

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
