### PR TITLE
Fix shader uniforms has null as default value

### LINKED ISSUE #44454: Shader uniforms has null as default value
**Godot version:**

3.2.4 beta4

**Steps to reproduce:**
1. Create a 2D node with shader material
2. Paste this code
```
shader_type canvas_item;

uniform mat4 test;
```
3. Save the scene
4. Open the tscn in a text editor
5.
```
[sub_resource type="ShaderMaterial" id=2]
shader = SubResource( 1 )
shader_param/test = null
```

### PR DESCRIPTION
**Pull request by Chaosus**
- Closes #44454

### CODE REVIEW

File: servers/rendering/shader_language.cpp [hunk 1]
```diff
@@ -4086,6 +4086,286 @@ Variant ShaderLanguage::constant_value_to_variant(const Vector<ShaderLanguage::C
...
+			if (array_size > 0) {
+				PackedInt32Array array;
+				for (int i = 0; i < array_size; i++) {
+					array.push_back(false);
+				}
+				value = Variant(array);
+			} else {
+				value = Variant(false);
+			}
+			break;
```
Comment (akien-mga) [inline servers/rendering/shader_language.cpp:4104]: Don't we already have code for this in core / Variant to generate default initialized variants of each type? Seems like it could simplify the code a lot to reuse that (see `VariantDefaultInitializer` etc.).

Comment (Chaosus) [reply servers/rendering/shader_language.cpp:4104]: It doesn't work, it still fill it with a null value. Strange.

Comment (Chaosus) [reply servers/rendering/shader_language.cpp:4104]: Looks like VariantDefaultInitializer just change a raw memory but does not change a type of Variant.

File: servers/rendering/shader_language.cpp [hunk 2]
```diff
@@ -4498,6 +4498,297 @@ Variant ShaderLanguage::constant_value_to_variant(const Vector<Scalar> &p_value,
...
+				PackedInt32Array array;
+				for (int i = 0; i < array_size; i++) {
+					array.push_back(false);
+				}
+				value = Variant(array);
+			} else {
+				VariantInitializer<bool>::init(&value);
+				VariantDefaultInitializer<bool>::init(&value);
+			}
+			break;
```
Comment (akien-mga) [inline servers/rendering/shader_language.cpp:4517]: TL;DR: I looked into how to improve this code myself but in the end I gave up.

I was still wondering if there isn't a simpler way to do this. There must exist a pre-existing method in the codebase to construct a Variant with a given type and default initialize it.

From a quick look, I found:
```cpp
void Variant::construct(Variant::Type p_type, Variant &base, const Variant **p_args, int p_argcount, Callable::CallError &r_error);
```
Which I think you would use like this:
```
Callable::CallError ce;
Variant value;
Variant::construct(variant_type, value, nullptr, 0, ce);
```

This would allow to simplify the cases quite a bit, like:
```
	switch (p_type) {
		case ShaderLanguage::TYPE_BOOL:
			if (array_size > 0) {
				type = Variant::PACKED_INT32_ARRAY;
			} else {
				type = Variant::BOOL;
			}
			break;
		case ShaderLanguage::TYPE_BVEC2:
			if (array_size > 0) {
				type = Variant::PACKED_INT32_ARRAY;
				array_size *= 2;
			} else {
				type = Variant::INT;
			}
			break;
		...
		}
	}

	Callable::CallError ce;
	Variant value;
	Variant::construct(variant_type, value, nullptr, 0, ce);
	
	if (array_size > 0) {
		// Figure out a way to resize the array in Variant and `zero()` it.
	}
```

But I finally noticed that this is pretty much adapted from `ShaderLanguage::constant_value_to_variant` and so keeping a consistent format might be worth it. The type conversions are also less trivial than I thought with types not natively compatible with Variant like `bvec2`.

And so at this point I gave up on trying to make this better :P

**Review by akien-mga — APPROVED** [review]

**Comment by Chaosus** [comment]
@akien-mga Done

**Comment by Repiteo** [comment]
Thanks!
