### PR TITLE
Use IDs instead of hashes for TrackCache keys

### LINKED ISSUE #116231: Animation path hash collisions in 4.6.1 (animations applied to wrong property even after previous fix)
### Tested versions

- Reproducible in: 4.6.1-rc1
- Also reproducible in earlier versions (e.g. 4.6) but the hashing algorithm is different. See #115473. (So this is not technically a "regression" as 4.6.1 is an improvement over 4.6, but I am demonstrating that the issue is still possible.)

### System information

Godot v4.6.1.rc1 - Windows 11 (build 26200) - Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 4080 (NVIDIA; 32.0.15.9174) - AMD Ryzen 7 5700X 8-Core Processor (16 threads) - 15.92 GiB memory

### Issue description

I am following up on #115407: in 4.6 animation track paths (i.e. `node_path:property_name`) could be applied to the wrong node or property due to a hash collision. This was fixed in #115473 by changing the hashing algorithm from a simple XOR to using the more convoluted hashing library, thus making trivial collisions (e.g. `A:B` and `B:A` resulting in the same hash) not possible.

However, the fundamental issue remains: if two track paths have a hash collision, they will affect each other in weird ways. It is still fairly easy to find a hash collision, as the hashing algorithm isn't a cryptographic one, it just isn't trivial to do by accident. However, a large collection of procedurally generated nodes with incrementing integer names will eventually result in a collision (having ~100,000 objects named "SomethingX" where X is an incrementing integer will typically result in two objects having the same hash). What happens when they collide is very unpredictable since the two tracks seem to have their values summed rather than one overwriting the other.

This was mentioned by @beicause in [this related discussion](https://github.com/godotengine/godot/pull/110400#issuecomment-3278706272):
> Any hash algorithm may have collisions. If a value with the same hash already exists in the container, we should handle hash collisions (comparing if the values are actually equal always, placing elements with the same hash into a bucket when inserting).
>
> It seems we are not doing so, using hash directly as a key seems problematic, which may be a separate issue.

### Steps to reproduce

I have written a little Python script to find two names that hash the same: `Char23288:position` and `Char104673:position`. The script is attached should anyone want to play with it:

[hashcollide.py](https://github.com/user-attachments/files/25276743/hashcollide.py)

Steps to reproduce are therefore:

1. Create two Node2D or Node3D nodes called `Char23288` and `Char104673`. (Note that this could happen naturally if a game was creating thousands and thousands of objects procedurally.)
2. Create an AnimationPlayer and animate both objects' `position` properties. In my example, I made a white square that is supposed to move down and up, and a black square that is supposed to move right and left.
3. Play the animation in the editor or in the running game.

Note that this **only** reproduces in 4.6.1. Previous versions used a different hashing algorithm so while it's still a problem, it won't work with these exact names.

Expected behaviour: the white square moves down and up; the black square moves right and left. (You can get this behaviour by renaming either of the nodes.)

https://github.com/user-attachments/assets/0c8162ff-be75-440c-a051-d5dceb49de2d

Observed behaviour: the white square moves diagonally down-right and up-left (it is summing the transform from both tracks). The black square does not move at all.

https://github.com/user-attachments/assets/8a3577f7-b857-4228-9909-e200c355e092

### Minimal reproduction project (MRP)

[wrong_animations_repro_4.6.1.zip](https://github.com/user-attachments/files/25276790/wrong_animations_repro_4.6.1.zip)

### PR DESCRIPTION
**Pull request by ugursoy**
Fixes: https://github.com/godotengine/godot/issues/116231

Hello, 

I've been tracking this issue since `4.6.0-stable` made it apparent. This is a solution that implements re-hashing on hash collisions for `track_cache`. As far as I'm aware, using `StringName` for hash was the latest solution proposed here (https://github.com/godotengine/godot/pull/110439) by @beicause for hash collisions. I pulled the last commit there and tested it, and found it decreasing the performance a bit. `uint32_t` comparisons are faster so I wanted to keep them.

In order to both fix the collision issue and keep using `uint32_t`, I made 3 implementations and tested them:
1. Dynamic double hash (Using double `AHashMap`)
	- `track_cache` holds `(TypeHash, HashBucket *)` pairs where `HashBucket` contains a `union` that is either a `TrackCache *` or another `AHashMap`
2. Adding a linked list in `TrackCache` struct
	- the `struct` simply holds `next` and `prev` pointers
	- adds to the list in case of collisions and iterates the whole list per lookup
3. Re-hashing the hash that collides with a `uint32_t probe` value until it no longer collides within the `track_cache`
	- Nothing changes, just the `thash` value is probed when a collision is detected
	- All hashes are inserted into a static `AHashMap` and that map is checked during insertion

These solutions are either proposed or mentioned in other hash related PR discussions: ([the one referenced above](https://github.com/godotengine/godot/pull/110439) and https://github.com/godotengine/godot/pull/110400)(https://github.com/godotengine/godot/pull/110439).

I tried not to touch other parts of the code and only focus on hash. My benchmark results for the provided MRP in (https://github.com/godotengine/godot/pull/110474) with my system (Ryzen5 1600, RTX2060) is as follows:

  | Stable | Dynamic Double Hash | Rehash | Linked List | StringName
-- | -- | -- | -- | -- | --
Avg FPS | 127.72 | 116.38 | 127.5 | 124.84 | 110.04
Avg MSPF | 7.83 | 8.59 | 7.84 | 8.01 | 9.08

Since that mrp does not contain any hash collisions, these can be considered as amortized performance. 

All except rehashing, requires additional checks to see if the hash key maps to a unique track or a bucket; and another lookup after that in case of collisions. So as expected, their runtime performances are worse (more than I expected). Also, collisions occur very rarely, so making additional checks that costs a few frames for a very rare case made no sense to me. Therefore, moving the cost to track creation time seemed like the best option. 

My implementation is not exactly what @TokageItLab proposed (with deferred calls and all) because I didn't understand how to do that :laughing:.

I tested this PR with [mrp-rehash.zip](https://github.com/user-attachments/files/25722014/mrp-rehash.zip) . It contains 3 tracks in animation player that generates the same hash in v4.6. Adding/removing, undo/redo, works fine in my tests. I tested these only in 2D.

### CODE REVIEW

**Comment by TokageItLab** [comment]
As I mentioned before, since the cost per frame doesn't change, I assume re-hashing is the right direction.

Looking at the current implementation in this PR, checking collision is performed every single time the track path changes. This means that assuming no collisions occur, adding 1000 tracks results in 1000! iterations in single frame.

> My implementation is not exactly what @TokageItLab proposed (with deferred calls and all) because I didn't understand how to do that 😆.

What I recommend is implementing a dirty flag and performing the rehash iteration only once within the `call_deferred()` and `AnimationMixer::_update_caches()` functions.

```cpp
void Animation::_track_update_hash(int p_track) {
	const NodePath &track_path = tracks[p_track]->path;
	const TrackType track_cache_type = get_cache_type(tracks[p_track]->type);
	tracks[p_track]->thash = HashMapHasherDefault::hash(Pair<const NodePath &, TrackType>(track_path, track_cache_type));
	_make_dirty();
}

void Animation::_make_dirty() {
	if (dirty) {
		return;
	}
	dirty = true;
	callable_mp(this, &Animation::ensure_hashes).call_deferred();
}

void Animation::ensure_hashes() {
	if (dirty) {
		return; // Avoid duplicated call between call_deferred and _update_caches.
	}

	while () {
		// Process re-hashing to avoid collision.
	}

	dirty = false;
}
```

```cpp
bool AnimationMixer::_update_caches() {
~~~
	for (const StringName &E : sname_list) {
		Ref<Animation> anim = get_animation(E);
		anim.ensure_hashes();

		for (int i = 0; i < anim->get_track_count(); i++) {
			if (!anim->track_is_enabled(i)) {
				continue;
			}
~~~
}
```

**Comment by ugursoy** [comment]
> Looking at the current implementation in this PR, checking collision is performed every single time the track path changes. This means that assuming no collisions occur, adding 1000 tracks results in 1000! iterations in single frame.

Oh, you include the hashmap lookup cost too. I understand.

> What I recommend is implementing a dirty flag and performing the rehash iteration only once within the `call_deferred()` and `AnimationMixer::_animation_set_cache_update()` functions.

Allright makes sense, I'll see what I can do and update this. Thanks.

**Comment by ugursoy** [comment]
I think this covers the case. Can you check @TokageItLab ?

The old PR had some other issues as well. This fixes all the problems I could find and think of. Let me know if there are more.

Tested with the same mrp, still same fps as the master branch.

File: scene/resources/animation.cpp [hunk 1]
```diff
@@ -32,6 +32,7 @@
 #include "animation.compat.inc"
 
 #include "core/io/marshalls.h"
+#include "core/object/callable_method_pointer.h"
```
Comment (AThousandShips) [inline scene/resources/animation.cpp]:
```suggestion
```
Already included

File: scene/resources/animation.h [hunk 2]
```diff
@@ -251,6 +253,28 @@ class Animation : public Resource {
...
+			nodepath = p_track->path;
+		}
+		TrackHashRef(const TrackHashRef *p_t) {
+			references = p_t->references;
+			nodepath = p_t->nodepath;
+			next_probe = p_t->next_probe;
+		}
+	};
+	static inline HashMap<TypeHash, TrackHashRef *> track_hash_map; // common list for thashes among all animations
+	void unref_or_erase(Track *p_track, const TypeHash thash);
```
Comment (AThousandShips) [inline scene/resources/animation.h]:
```suggestion
	void unref_or_erase(Track *p_track, const TypeHash p_thash);
```

File: scene/resources/animation.cpp [hunk 3]
```diff
@@ -1063,9 +1066,103 @@ Animation::TrackType Animation::get_cache_type(TrackType p_type) {
...
-	tracks[p_track]->thash = HashMapHasherDefault::hash(Pair<const NodePath &, TrackType>(track_path, track_cache_type));
+	dirty_tracks.insert(p_track);
+	if (track_hash_is_dirty) {
+		return;
+	}
+	track_hash_is_dirty = true;
+	callable_mp(this, &Animation::ensure_hashes).call_deferred();
+}
+
+void Animation::unref_or_erase(Track *p_track, const TypeHash thash) {
```
Comment (AThousandShips) [inline scene/resources/animation.cpp]:
```suggestion
void Animation::unref_or_erase(Track *p_track, const TypeHash p_thash) {
```

File: scene/resources/animation.cpp (hunk 1 above)
Comment (ugursoy) [reply scene/resources/animation.cpp]: I've re-added this line because all the workflows throw the same error: `callable_mp not found`. My own fork compiles just fine so I assume something is changed in master.

File: scene/resources/animation.cpp [hunk 4]
```diff
@@ -1062,15 +1065,86 @@ Animation::TrackType Animation::get_cache_type(TrackType p_type) {
...
+			references->push_back(tracks[track]);
+			track_cache_id_map.insert(new_track_cache_id, references);
+		} else {
+			unique_id = index + 1; // +1 to prevent id = 0.
+			references = track_cache_id_map.get_by_index(index).value;
+			references->push_back(tracks[track]);
+		}
+		tracks[track]->track_cache_id = new_track_cache_id;
+	}
+
```
Comment (TokageItLab) [inline scene/resources/animation.cpp]: This feels a bit complicated. Assuming the ID can be discarded each time, it might be better to iterate through all tracks without retaining previous IDs, checking only if the same cache type exists.

One way to do this, I though it might be a bit of a hack, but you can convert every concatenated path to StringName first, then use only the memory address of the StringName as the int ID. In other words, it guarantees no duplication by allocating all StringName objects in memory only during iteration, then releases the StringName area after using them as IDs.

Comment (ugursoy) [reply scene/resources/animation.cpp]: Allright I tested the `StringName` approach, correct me if I misunderstood. [Here](https://github.com/ugursoy/godot/tree/track-cache-stringname) is the branch for it and here is the snippet:

scene/resources/animation.h
```c++
// keeps StringNames until all ids are assigned for all animations
// during ensure_unique_ids() call to prevent deallocation
static inline LocalVector<StringName> track_cache_id_list;
// counter for required ensure_unique_ids() calls before deallocation
static inline int track_update_counter = 0;
bool update_track_cache_ids = false;
```

scene/resources/animation.cpp
```c++
void Animation::_track_update_unique_ids(int p_track) {
       if (update_track_cache_ids) {
               return;
       }
       track_update_counter++;
       update_track_cache_ids = true;
       callable_mp(this, &Animation::ensure_unique_ids).call_deferred();
}

void Animation::ensure_unique_ids() {
       if (!update_track_cache_ids) {
               return;
       }

       for (Track *track : tracks) {
               const NodePath &track_path = track->path;
               const TrackType track_cache_type = get_cache_type(track->type);

               StringName id = StringName(String(track_path) + itos(track_cache_type));
               track->unique_id = (TypeTrackId)id.data_unique_pointer();
               track_cache_id_list.push_back(id); // Keep StringName object alive
       }

       update_track_cache_ids = false;
       track_update_counter--;
       if (track_update_counter == 0) {
               // All IDs are assigned so StringNames can be freed
               track_cache_id_list.clear();
       }
}
``` 

This works too, I did not see any issues in my tests. Just that the `ensure_unique_ids()` overhead is greater (1.75ms compared to 1.24ms in current approach, for 1000 tracks).

Even though this approach is simpler, I would prefer the one in this PR.

> Assuming the ID can be discarded each time, it might be better to iterate through all tracks without retaining previous IDs, checking only if the same cache type exists.

I don't think IDs need to be discarded. It is not necessary and the alternative is inefficient. Only the changed tracks need to have their IDs reassigned to prevent looping through tracks.

> One way to do this, I though it might be a bit of a hack, but you can convert every concatenated path to StringName first, then use only the memory address of the StringName as the int ID. 

I dislike this `StringName` approach. You need to recreate IDs for all tracks from scratch each time. Even node/track rename would trigger the whole loop. (for a smaller cost, because concatanated `StringName` parts are created already). According to my measurements, 1.75ms becomes 1ms on a node rename here, whereas it costs 0.01ms for the current PR version (for 1000 tracks). The overall overhead is greater.

Also, this forces `TypeTrackId` (prior `TypeHash`) to be `uint64_t`, which is slightly slower than `uint32_t` for lookups (in animation mixer).

Comment (TokageItLab) [reply scene/resources/animation.cpp]: Well, I understand it should work. I'll ask others for their opinions to see if there's a better approach, and if this is acceptable, we can proceed with the merge. Do you have any idea @Ryan-000 @Ivorforce ?

Comment (Ryan-000) [reply scene/resources/animation.cpp]: If the issue is hash collisions, I would use `TrackCacheId` (the  `Pair<NodePath, TrackType>`) in `AnimationMixer::track_cache` so it would look like this `AHashMap<TrackCacheId, TrackCache *>`.

Since https://github.com/godotengine/godot/pull/116394 changes the implementation of `AnimationMixer::_blend_calc_total_weight`  and removes `thread_local HashSet<Animation::TypeHash, HashHasher> processed_hashes;` (assuming that makes it in), then the per frame performance shouldn't really change. 

Code related to `AnimatedValuesBackup` like `AnimationMixer::_build_backup_track_cache()` might be a bit slower, but that should be ok since its editor code.

And `AnimationMixer::_update_caches()` also might get a bit slower, but since it not called every frame, it also should be fine.

Comment (Ryan-000) [reply scene/resources/animation.cpp]: Also, `Animation::track_cache_id_map` is not thread safe and will cause issues in projects using [group-based threaded scene processing](https://github.com/godotengine/godot-proposals/issues/6424), or `ResourceLoader.load_threaded_request` and C# projects that reference animation objects (since the resource may be freed on the .NET Finalizer thread).

Comment (TokageItLab) [reply scene/resources/animation.cpp]: > If the issue is hash collisions, I would use TrackCacheId (the Pair<NodePath, TrackType>) in AnimationMixer::track_cache so it would look like this AHashMap<TrackCacheId, TrackCache *>.

> Since https://github.com/godotengine/godot/pull/116394 changes the implementation of AnimationMixer::_blend_calc_total_weight and removes thread_local HashSet<Animation::TypeHash, HashHasher> processed_hashes; (assuming that makes it in), then the per frame performance shouldn't really change.

If it's after https://github.com/godotengine/godot/pull/116394 change, wouldn't StringName suffice as long as the speed remains unchanged between `uint32_t` vs `Pair<NodePath, TrackType>`?

Comment (ugursoy) [reply scene/resources/animation.cpp]: > Also, `Animation::track_cache_id_map` is not thread safe and will cause issues in projects using [group-based threaded scene processing](https://github.com/godotengine/godot-proposals/issues/6424), or `ResourceLoader.load_threaded_request` and C# projects that reference animation objects (since the resource may be freed on the .NET Finalizer thread).

Will adding a mutex to the methods that utilize `Animation::track_cache_id_map`; namely: `ensure_unique_id()` and `_track_cache_unref_or_erase()`, be enough to make it thread safe?

Comment (Ryan-000) [reply scene/resources/animation.cpp]: > If it's after https://github.com/godotengine/godot/pull/116394 change, wouldn't StringName suffice as long as the speed remains unchanged between uint32_t vs Pair<NodePath, TrackType>?

`StringName` would work well. We can just replace `TypeHash thash = 0; // Hash by Path + SubPath + TrackType.` with something like `StringName path_with_type // path+type`.

> Will adding a mutex to the methods that utilize Animation::track_cache_id_map; namely: ensure_unique_id() and _track_cache_unref_or_erase(), be enough to make it thread safe?

I would avoid adding any global mutable state in `Animation` since it will slow everything down since you would have to guard it behind a mutex. If you still need something like `track_cache_id_map`, I would keep it in `AnimationMixer` instead, so its only scoped to the relevant animations.

Comment (ugursoy) [reply scene/resources/animation.cpp]: > StringName would work well. We can just replace TypeHash thash = 0; // Hash by Path + SubPath + TrackType. with something like StringName path_with_type // path+type.

I tested this along with `Pair<NodePath, TrackType>` with the current master (using thash). Again, using the same mrp:


|  | Master (uint32_t thash) | Master (uint64_t thash) | Pair | StringName |
|--------|------------|--------|--------|--------|
| FPS | 124.44 | 119.06 | 89.94 | 114.55 |
| MSPF | 8.03 | 8.4 | 11.12 | 8.73 | 


I just changed the `typedef` for `Pair`. So I think using the `Pair` is out of question (and maybe it was the culprit for the previous ID assignment overhead).

For StringName, I kept the `StringName path_with_type` in the track to make it stay in the memory and used its pointer as key (casted to `uint64_t`). In the PR description, I provided my initial benchmarks which included StringName as key (not the pointer), therefore I did not make another benchmark for it, assuming it would be worse anyways.

I didn't want to give up any performance, but at this point I don't think it can be avoided. The thread safety ruins everything. Now I'm leaning towards `StringName` as well.

As `uint64_t` version of master performs better, I think with some tweaks, the `StringName` pointer can give a similar performance as well. More importantly, it should eliminate thread safety concerns. Is this OK?

Comment (ugursoy) [reply scene/resources/animation.cpp]: I should apologize. I think I messed up.

```
AHashMap<Animation::TypeHash, AnimationMixer::TrackCache *, HashHasher> track_cache
```

In my latest benchmark for Pair, I had to remove `HashHasher` from the `track_cache` to proceed. Then I branched off from that for StringName test, without `HashHasher`. Turns out, `HashHasher` greatly improves `uint64_t` hashing in `AHashMap`, the StringName method now surpasses the master. 

Here is the patch if you want to check it yourselves: [stringname.patch](https://github.com/user-attachments/files/25788910/stringname.patch)

I am sorry for the misleading benchmark. Here is the updated one:

|          | Master (uint32_t) | Master (uint64_t) | StringName |
|--------|--------|--------|----|
| FPS | 124.65 | 124.91 | 127.33 |
| MSPF | 8.01 | 8.00 | 7.85 |

If this is preferable, I will update the PR.

Edit: Added uint64_t (master) results. StringName is faster than that as well but one would expect the same result since both are the same type. So the only explanation I can think of is the standard deviation of the values. Pointers are close in value, whereas hashes are diverse. So that pumps up the performance in `AHashMap`, I guess?

Comment (Ryan-000) [reply scene/resources/animation.cpp]: > Here is the patch if you want to check it yourselves: [stringname.patch](https://github.com/user-attachments/files/25788910/stringname.patch)

Looks good to me so far.

My only concern at this point is `AnimatedValuesBackup`. Right now it relies on `TypeHash`, but with this change `TypeHash` is effectively based on `StringName::data_unique_pointer()`, so it is only stable for as long as the backing `StringName` remains alive.

I think this could break in a case like this:
- `AnimationMixer::make_backup()` stores values keyed by `TypeHash`.
- Later, the relevant `Animation` resources are unloaded, along with their `Track`s and possibly the backing `StringName`s.
- If those animations are loaded again, `path_with_cache_type` may end up with a different `data_unique_pointer()`.
- At that point, `AnimationMixer::restore()` could be working with stale keys from `AnimatedValuesBackup` that no longer match the current mixer state.

Because of that, I think `AnimatedValuesBackup` should eventually use a stable identifier across unload/reload, such as `StringName` itself or `Pair<NodePath, TrackType>`, instead of `TypeHash`.

That said, I think this can be handled later once we have @TokageItLab's opinion on the current approach and when the PR is updated.

Comment (TokageItLab) [reply scene/resources/animation.cpp]: I agree @Ryan-000 as we choose the way of [stringname.patch](https://github.com/user-attachments/files/25788910/stringname.patch).

File: scene/resources/animation.h [hunk 5]
```diff
@@ -40,7 +41,7 @@ class Animation : public Resource {
 	RES_BASE_EXTENSION("anim");
 
 public:
-	typedef uint32_t TypeHash;
+	typedef uint64_t TypeTrackId;
```
Comment (TokageItLab) [inline scene/resources/animation.h]: Nitpick, if there's a name to indicate the role, I think  `TrackCacheID` would be better name.

**Comment by ugursoy** [comment]
Rebased to upstream/master.

Here is the updated benchmarks for MRP in (https://github.com/godotengine/godot/pull/110474) with my system (Ryzen5 1600, RTX2060):

|  | Master | PR |
|--------|--------|--------|
| Avg FPS | 144.92 | 145.82 |
| Avg MSPF | 6.90 | 6.85 |

File: scene/resources/animation.h [hunk 6]
```diff
@@ -109,9 +109,16 @@ class Animation : public Resource {
 		InterpolationType interpolation = INTERPOLATION_LINEAR;
 		bool loop_wrap = true;
 		NodePath path; // Path to something.
-		TypeHash thash = 0; // Hash by Path + SubPath + TrackType.
+		StringName stringname_path; // Path + SubPath combination instead of hash
```
Comment (TokageItLab) [inline scene/resources/animation.h]:
```suggestion
		StringName concatenated_path;
```
Clarify variable name and tweak comment since we no longer need to comment for hash.

**Review by TokageItLab — APPROVED** [review]
