### PR TITLE
Fix missing options in Project Import Defaults

### LINKED ISSUE #89379: glTF's Naming Version and Embedded Image Handling import options can't be overridden in Project Settings Import Defaults
### Tested versions

Should be an issue with all versions 4.3 and higher

On 4.2 and below, it worked because *all* Scene importers show the gltf/embedded_image_handling setting.

### System information

Godot v4.3.dev (c5c6f8d43) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

There is a setting for glb embedded textures that projects may wish to change to basis universal (or uncompressed) for certain workflows. The default value extracts textures without asking, and there is no way to change this default in project settings:
image

This is the setting in the import dock which I want changed.
image

This means, the only way to include glb files in the project and use their textures embedded is to add them to the project, let it extract the textures, wait for godot to compress the extracted textures, then change the import setting to Embed as Basis Universal, then reimport, and finally delete the extracted textures.
Due tot his issue, this process must be repeated for every single glb in the project, or avoid using glb files.

The one upside is the difficulty in changing this setting encourages users to avoids some workflow pitfalls: Basis Universal has had some issues; uncompressed textures are bad for many reasons; and embedded textures will cause memory duplication when extracting meshes and materials. So maybe it's a good thing that this setting is hard to change ;-)

I believe the same issue is likely to affect blend import settings as well as fbx-specific settings.

On Godot 4.2.x and earlier, it was possible to change gltf settings on all scenes, including ESCN, Blend, FBX and glTF:
ESCN sample

The blend settings never showed up in import defaults. only the gltf option seems to be global.

### Steps to reproduce

1. Go to Project Settings -> Import Defaults.
2. Choose "Scene"
3. There is no way to change the default value of Extract Tex

### Minimal reproduction project (MRP)

This is an issue with project settings, so it happens even in a blank project.

### PR DESCRIPTION
**Pull request by Hilderin**
- Fixes #89379

Some modifications were made in https://github.com/godotengine/godot/commit/04d43947bff4de9db8d7005862a1d895b6703fbc that lead to remove some options in Project Settings. Also, some options like Blender specific parameters were never in the Project Import Defaults, which I guess was an error.

The premise I took was to put every options possible for all different file extension in the Project Import Defaults. This was the case in 4.2 except for .blend.

### Modifications:
- Fixed `ResourceImporterScene::get_option_visibility` to check all plugins and importers. Previously, the method would return the result from `get_option_visibility` at the first importer, leading to only processing the first plugin or importer. Now, all are processed until a return value of false is encountered.
- `EditorSceneFormatImporterFBX2GLTF::get_option_visibility` returned false for only one the ufbx options if FBX2GLTF is enabled.
- The validations that determine if an option is available or not has been moved in `get_import_options` methods and always returns all the option when the path is empty (aka Project Import Defaults).
- The missing options for FBX and GLTF are now available in Scene and Animation Library in Project Import Defaults.
- Blender options are now available in Project Import Defaults.
- Fixed 'Set as Default for Scene' where options not displayed were reverted.

### Others found issues:
- Edited, these options does not makes sense for Blender: ~~When importing from Blender, the options `gltf/naming_version` and `gltf/embedded_image_handling` are not used even if they were shown in 4.2. I could add these options for Blender, at least `embedded_image_handling` like it was done for ufbx??~~
- When changing a value in the options (Project settings and file Import options), `get_option_visibility` are not recalled so that means that to see the effects of `EditorSceneFormatImporterBlend::get_option_visibility` or `EditorSceneFormatImporterFBX2GLTF::get_option_visibility`, the user needs to close the panel and reopen it. That could cause error if the user change the fbx/importer from FBX2GLTF to ufbx and tries to reimport. The 2 missing options will cause an error during importation.

### Project settings:
4.2
image

This PR:
image
image

### FBX Import options
4.2
image

This PR
image

EDIT: stroked out the issue with Blender options.

### CODE REVIEW

**Comment by Hilderin** [comment]
I found another problem that was probably always there with the default import settings of Scene.
If you set the Default from the Import Panel, only the visible setting are save and the other are reverted. That can cause if in the problem there are different file types or if some fbx uses ufbx and others fbx2gltf. Maybe the best courses of action should be to keep the non visible options while saving the defaults?

image

**Comment by lyuma** [comment]
Looks reasonable at first glance. Seems better than the kludgy hack I was thinking of doing. I'll have to play with it a bit.

The magic is the `p_path.is_empty() ||` clause since project settings uses an empty path.

> Maybe the best courses of action should be to keep the non visible options while saving the defaults?

Nice catch. I also believe this is correct.

One thing I noticed is that there is something odd about the `fbx/embedded_image_handling` when FBX2glTF is used. It would be good to verify compatibility against 4.2 imported meshes which used the `gltf/embedded_image_handling` since this will be a common case for users upgrading their projects.

**Comment by Hilderin** [comment]
I tested in debug with the 4.2 branch code and the settings `gltf/naming_version` and `gltf/embedded_image_handling` were never used in 4.2.
The `EditorSceneFormatImporterGLTF` is not used for fbx file (it's the only place were these settings are used). `EditorSceneFormatImporterFBX` call directly `GLTFDocument::generate_scene`.

File: modules/fbx/editor/editor_scene_importer_ufbx.cpp [hunk 1]
```diff
@@ -76,9 +76,6 @@ Node *EditorSceneFormatImporterUFBX::import_scene(const String &p_path, uint32_t
 	if (p_options.has(SNAME("nodes/import_as_skeleton_bones")) ? (bool)p_options[SNAME("nodes/import_as_skeleton_bones")] : false) {
 		state->set_import_as_skeleton_bones(true);
 	}
-	if (p_options.has(SNAME("nodes/import_as_skeleton_bones")) ? (bool)p_options[SNAME("nodes/import_as_skeleton_bones")] : false) {
```
Comment (Hilderin) [inline modules/fbx/editor/editor_scene_importer_ufbx.cpp:79]: Was duplicated just over.

File: modules/gltf/editor/editor_scene_importer_gltf.cpp [hunk 2]
```diff
@@ -84,8 +84,12 @@ Node *EditorSceneFormatImporterGLTF::import_scene(const String &p_path, uint32_t
...
-	r_options->push_back(ResourceImporterScene::ImportOption(PropertyInfo(Variant::INT, "gltf/embedded_image_handling", PROPERTY_HINT_ENUM, "Discard All Textures,Extract Textures,Embed as Basis Universal,Embed as Uncompressed", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_UPDATE_ALL_IF_MODIFIED), GLTFState::HANDLE_BINARY_EXTRACT_TEXTURES));
+	String file_extension = p_path.get_extension().to_lower();
+	// Returns all the options when path is empty because that means it's for the Project Settings.
+	if (p_path.is_empty() || file_extension == "gltf" || file_extension == "glb") {
+		r_options->push_back(ResourceImporterScene::ImportOption(PropertyInfo(Variant::INT, "gltf/naming_version", PROPERTY_HINT_ENUM, "Godot 4.1 or 4.0,Godot 4.2 or later"), 1));
+		r_options->push_back(ResourceImporterScene::ImportOption(PropertyInfo(Variant::INT, "gltf/embedded_image_handling", PROPERTY_HINT_ENUM, "Discard All Textures,Extract Textures,Embed as Basis Universal,Embed as Uncompressed", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_UPDATE_ALL_IF_MODIFIED), GLTFState::HANDLE_BINARY_EXTRACT_TEXTURES));
```
Comment (lyuma) [inline modules/gltf/editor/editor_scene_importer_gltf.cpp:91]: I'm still apprehensive about hiding these options because options like "naming version" are supposed to be used for .blend and .fbx via FBX2glTF, though if you're 100% sure they are currently being ignored in those cases, I guess it's okay.

**Review by lyuma — APPROVED** [review]
I think it's the best change we can make for now. I'm most worried about the hardcoded file extension checks, but that was already an issue before.

We should merge this and then look into overhauling this option system some in 4.4

File: modules/gltf/editor/editor_scene_importer_gltf.cpp (hunk 2 above)
Comment (Hilderin) [reply modules/gltf/editor/editor_scene_importer_gltf.cpp:91]: I confirm that these options are used only in `EditorSceneFormatImporterGLTF::import_scene` and this method is used only on `gltf` and `glb` files.

**Comment by akien-mga** [comment]
Thanks!
