### PR TITLE
Fixes LOD scaling issues on skinned meshes.

### LINKED ISSUE #57895: Vulkan: Incorrect glTF mesh rendering due to automatic LOD kicking in too early with scaled bones
### Godot version

4.0 Alpha 2

### System information

Windows 11, Vulkan, AMD Radeon RX 5700 XT

### Issue description

Screenshot 2022-02-09 175650
Screenshot 2022-02-09 175628

### Steps to reproduce

Import a GLTF Mesh into a 3D Scene

### Minimal reproduction project

(https://drive.google.com/file/d/1-CfrKX1gIe6pAInUdzXSVZg63TRjLkzU/view?usp=sharing)

### LINKED ISSUE #58570: LOD causes bones skinning errors with GLTF import
### Godot version

4.0, all versions

### System information

Linux mint, vulkan

### Issue description

When you import a skinned mesh it will not show the last bone and the bone information is missing too. In older versions of godot, the last bones was not show in the editor but the bone worked correctly. Now, it only works on the importing view, but will not work at all in the editor, missing all the bone information as is shown below:

The model on the 3D importer, working right:
imagen

The model on the editor: all info about the last bone is missing:
imagen

### Steps to reproduce

Import any kind of skinned mesh in .glb format.

### Minimal reproduction project

[Example.tar.gz](https://github.com/godotengine/godot/files/8147331/Example.tar.gz)

### PR DESCRIPTION
**Pull request by SaracenOne**
Adds a new function to the import pipeline which applies skinning bindposes from the rest to the underlying meshes. Fixes LOD creation issues on meshes where the mesh's size does not match the skinning.

*Bugsquad edit:*
- Fixes #57895
- Fixes #58570

### CODE REVIEW

**Comment by Calinou** [comment]
Does this resolve https://github.com/godotengine/godot/issues/57895?

**Comment by fire** [comment]
This resolves https://github.com/godotengine/godot/issues/57895 and others. See https://github.com/godotengine/godot/pull/63812

**Comment by SaracenOne** [comment]
Reduz requested a change of approach in how we fix this, so let me put it on hold for now while I re-evaluate

File: editor/import/resource_importer_scene.cpp [hunk 1]
```diff
@@ -1891,6 +1891,40 @@ void ResourceImporterScene::_replace_owner(Node *p_node, Node *p_scene, Node *p_
...
+	const Ref<Skin> skin = p_src_mesh_node->get_skin();
+	if (skin.is_valid()) {
+		NodePath skeleton_path = p_src_mesh_node->get_skeleton_path();
+		const Node *node = p_src_mesh_node->get_node_or_null(skeleton_path);
+		const Skeleton3D *skeleton = Object::cast_to<Skeleton3D>(node);
+		if (skeleton) {
+			int bone_count = skeleton->get_bone_count();
+			int bind_count = skin->get_bind_count();
+
+			if (bone_count == bind_count) {
```
Comment (reduz) [inline editor/import/resource_importer_scene.cpp:1907]: This comparison is not needed, its expected the numbers may differ when coming from Maya.

File: editor/import/resource_importer_scene.cpp [hunk 2]
```diff
@@ -1891,6 +1891,40 @@ void ResourceImporterScene::_replace_owner(Node *p_node, Node *p_scene, Node *p_
...
+				for (int i = 0; i < bind_count; i++) {
+					Transform3D bind_pose = skin->get_bind_pose(i);
+					String bind_name = skin->get_bind_name(i);
```
Comment (reduz) [inline editor/import/resource_importer_scene.cpp:1910]: These two lines should be rewritten as follows:
```c++
String bind_name = skin->get_bind_name(i);
int bone_idx = bind_name.is_empty ? skin->get_bind_bone(i) : skeleton->find_bone(bind_name);
```

**Comment by reduz** [comment]
It looks great though!

**Review by reduz — APPROVED** [review]
