### PR TITLE
Avoid double handling of rename in the file system dock

### LINKED ISSUE #90473: Renaming a file sometimes shows an error popup
### Tested versions

can happen in v4.3.dev.custom_build [a7b860250]

### System information

linux

### Issue description

https://github.com/godotengine/godot/assets/71937306/bb13f73d-9f4a-45c5-a59e-6edc88f09c41

- as you can see in this clip, renaming a file to an unused name still reports that the name is used in a popup. (the operation doesn't fail though)
- it is not consistent (happened for a while on a test file and then, after writing the report, it stopped happening within the same editor instance)

### Steps to reproduce

rename a file

### Minimal reproduction project (MRP)

any

### LINKED ISSUE #91648: Crash on folder capitalization change
### Tested versions

- Reproducible in 4.3-dev6

### System information

Windows 11, geForce 4080, Godot 4.3-dev6, Forward+

### Issue description

Changing the capitalization of an empty folder crashes Godot.

### Steps to reproduce

I started on a blank, fresh project.

- Created a folder named 'OneSHots'
- Right click - rename to 'OneShots'
- Godot crashes.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by RandomShaper**
Fixes #90473.
*Bugsquad edit:* Fixes #91648

In that issue, certain change in `DisplayServerWindows` seems to be the cause of the issue on Windows. However, the report is about Linux. The fact that the issue is cross-platform makes sense if you think about what this PR does.

The floating text box used for rename can be confirmed via closing the popup containing it or via actually confirming the input. Since the latter involves the former, there's some code to avoid handling the user will twice. However, it's such a brittle deambiguation mechanism; namely, if certain keys are down, we assume the text input was already handled. It only makes sense that such a handling is subject to break with subtle changes in input event management across display servers. In fact, that's the problem: the rename operation is attempted twice because the current mechanism fails to block the second event.

This PR reimplements the involved handlers in a more robust way so the issue is gone and very unlikely to inadvertedly reappear again. That said, I'm not super happy with how _ad hoc_ this is even in the new version. Maybe `LineEdit` could have a property, such as `submit_on_parent_close` that makes the intended behavior an opt-in feature of it. This PR fixes the issue in the meantime anyway.

Lastly, `Tree` seems to have a similar deambiguation code, but that one seems to still work with the current `DisplayServer` implementations. That said, it'd warrant similar love. (CC @bruvzg, that may want to review this PR and later improve the state of affairs.)

**2024-05-01:** This is now based on #91361, which fixes the underlying issue on Windows. However, sine this issue was not Window-specific and I'd still want to have a more solid mechanism here, I've reworked this PR doing so.

### CODE REVIEW

**Comment by KoBeWi** [comment]
Apparently there is another regression 🤔 Closing name edit with Escape will accept it. It's the same before this PR though, but not in dev5.

**Comment by RandomShaper** [comment]
Fixed. In the end, some not-very-elegant check has been needed. At least, it's based on an action and not on specific keys. I guess it's good enough until the time where this all is implemented as as first-class feature.

**Comment by KoBeWi** [comment]
Renaming in tree mode is now broken.

**Comment by RandomShaper** [comment]
Pushed with a different approach. (Please see the added note to the PR description.)

**Review by KoBeWi — APPROVED** [review]
Seems to work correctly now, tested on Windows.

**Comment by RandomShaper** [comment]
Thank you very much for your continuous help testing this!

File: platform/windows/display_server_windows.cpp [hunk 1]
```diff
@@ -3740,8 +3740,13 @@ LRESULT DisplayServerWindows::WndProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARA
...
 		} break;
 		case WM_ACTIVATE: {
-			_process_activate_event(window_id, wParam, lParam);
-			return 0; // Return to the message loop.
+			// Activation can happen just after the window has been created, even before the callbacks are set.
+			// Therefore, it's safer to defer the delivery of the event.
+			if (!windows[window_id].activate_timer_id) {
+				windows[window_id].activate_timer_id = SetTimer(windows[window_id].hWnd, 1, USER_TIMER_MINIMUM, (TIMERPROC) nullptr);
+			}
+			windows[window_id].activate_state = GET_WM_ACTIVATE_STATE(wParam, lParam);
```
Comment (bruvzg) [inline platform/windows/display_server_windows.cpp:3748]: I'm not sure if `GET_WM_ACTIVATE_STATE` is a standard Windows macro, I think it's defined only in WinTab API, might be better to use `LOWORD(wParam)` (which is equivalent).

**Review by bruvzg — APPROVED** [review]

File: platform/windows/display_server_windows.cpp (hunk 1 above)
Comment (RandomShaper) [reply platform/windows/display_server_windows.cpp:3748]: I used it because it was already there in the former code.

Besides, I see it's defined in `windowsx.h`, inside this region:
```
#pragma region Desktop Family
#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)
```

Comment (bruvzg) [reply platform/windows/display_server_windows.cpp:3748]: > Besides, I see it's defined in windowsx.h, inside this region:

Then it's OK.

**Comment by akien-mga** [comment]
Thanks!
