### PR TITLE
Use ObjectID in ProgressDialog Window list

### LINKED ISSUE #113276: Crash when saving after closing a floating dock
### Tested versions

4.6 7ed0b61

### System information

W10

### Issue description

```
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.6.dev.custom_build (7ed0b6167618f9c8c5df87c7e83da6003c081368)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[0] Node::is_inside_tree (C:\godot_source\scene\main\node.h:553)
[1] Viewport::set_input_as_handled (C:\godot_source\scene\main\viewport.cpp:3907)
[2] ShortcutBin::shortcut_input (C:\godot_source\editor\gui\window_wrapper.cpp:70)
[3] Node::_call_shortcut_input (C:\godot_source\scene\main\node.cpp:3570)
[4] SceneTree::_call_input_pause (C:\godot_source\scene\main\scene_tree.cpp:1466)
[5] Viewport::_push_unhandled_input_internal (C:\godot_source\scene\main\viewport.cpp:3556)
[6] Viewport::push_input (C:\godot_source\scene\main\viewport.cpp:3518)
[7] Window::_window_input (C:\godot_source\scene\main\window.cpp:1850)
[8] call_with_variant_args_helper<Window,Ref<InputEvent> const &,0> (C:\godot_source\core\variant\binder_common.h:224)
[9] call_with_variant_args<Window,Ref<InputEvent> const &> (C:\godot_source\core\variant\binder_common.h:338)
[10] CallableCustomMethodPointer<Window,void,Ref<InputEvent> const &>::call (C:\godot_source\core\object\callable_method_pointer.h:103)
[11] Callable::callp (C:\godot_source\core\variant\callable.cpp:57)
[12] Callable::call<Ref<InputEvent> > (C:\godot_source\core\variant\variant.h:951)
[13] DisplayServerWindows::_dispatch_input_event (C:\godot_source\platform\windows\display_server_windows.cpp:4469)
[14] DisplayServerWindows::_dispatch_input_events (C:\godot_source\platform\windows\display_server_windows.cpp:4439)
[15] Input::_parse_input_event_impl (C:\godot_source\core\input\input.cpp:987)
[16] Input::flush_buffered_events (C:\godot_source\core\input\input.cpp:1292)
[17] DisplayServerWindows::process_events (C:\godot_source\platform\windows\display_server_windows.cpp:3830)
[18] OS_Windows::run (C:\godot_source\platform\windows\os_windows.cpp:2345)
[19] widechar_main (C:\godot_source\platform\windows\godot_windows.cpp:99)
[20] _main (C:\godot_source\platform\windows\godot_windows.cpp:125)
[21] main (C:\godot_source\platform\windows\godot_windows.cpp:139)
[22] WinMain (C:\godot_source\platform\windows\godot_windows.cpp:153)
[23] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[24] ShimMainCRTStartup (C:\godot_source\platform\windows\cpu_feature_validation.c:74)
[25] <couldn't map PC to fn name>
-- END OF C++ BACKTRACE --
```
See below.

EDIT:
Actually there seem to be 2 crashes with the same reproduction steps?
```
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.6.dev.custom_build (7ed0b6167618f9c8c5df87c7e83da6003c081368)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[0] SceneTree::is_suspended (C:\godot_source\scene\main\scene_tree.cpp:1148)
[1] Node::can_process (C:\godot_source\scene\main\node.cpp:903)
[2] Node::set_process_mode (C:\godot_source\scene\main\node.cpp:674)
[3] ProgressDialog::_popup (C:\godot_source\editor\gui\progress_dialog.cpp:160)
[4] ProgressDialog::add_task (C:\godot_source\editor\gui\progress_dialog.cpp:217)
[5] EditorNode::progress_add_task (C:\godot_source\editor\editor_node.cpp:5682)
[6] EditorProgress::EditorProgress (C:\godot_source\editor\editor_node.cpp:223)
[7] EditorNode::_save_scene_with_preview (C:\godot_source\editor\editor_node.cpp:2145)
[8] EditorNode::_menu_option_confirm (C:\godot_source\editor\editor_node.cpp:3316)
[9] EditorNode::_menu_option (C:\godot_source\editor\editor_node.cpp:1935)
[10] call_with_variant_args_helper<EditorNode,int,0> (C:\godot_source\core\variant\binder_common.h:224)
[11] call_with_variant_args<EditorNode,int> (C:\godot_source\core\variant\binder_common.h:338)
[12] CallableCustomMethodPointer<EditorNode,void,int>::call (C:\godot_source\core\object\callable_method_pointer.h:103)
[13] Callable::callp (C:\godot_source\core\variant\callable.cpp:57)
[14] Object::emit_signalp (C:\godot_source\core\object\object.cpp:1342)
[15] Node::emit_signalp (C:\godot_source\scene\main\node.cpp:4171)
[16] Object::emit_signal<int> (C:\godot_source\core\object\object.h:979)
[17] PopupMenu::activate_item (C:\godot_source\scene\gui\popup_menu.cpp:2884)
[18] PopupMenu::activate_item_by_event (C:\godot_source\scene\gui\popup_menu.cpp:2806)
[19] MenuBar::shortcut_input (C:\godot_source\scene\gui\menu_bar.cpp:175)
[20] Node::_call_shortcut_input (C:\godot_source\scene\main\node.cpp:3570)
[21] SceneTree::_call_input_pause (C:\godot_source\scene\main\scene_tree.cpp:1484)
[22] Viewport::_push_unhandled_input_internal (C:\godot_source\scene\main\viewport.cpp:3556)
[23] Viewport::push_input (C:\godot_source\scene\main\viewport.cpp:3518)
[24] Window::_window_input (C:\godot_source\scene\main\window.cpp:1850)
[25] call_with_variant_args_helper<Window,Ref<InputEvent> const &,0> (C:\godot_source\core\variant\binder_common.h:224)
[26] call_with_variant_args<Window,Ref<InputEvent> const &> (C:\godot_source\core\variant\binder_common.h:338)
[27] CallableCustomMethodPointer<Window,void,Ref<InputEvent> const &>::call (C:\godot_source\core\object\callable_method_pointer.h:103)
[28] Callable::callp (C:\godot_source\core\variant\callable.cpp:57)
[29] Callable::call<Ref<InputEvent> > (C:\godot_source\core\variant\variant.h:951)
[30] DisplayServerWindows::_dispatch_input_event (C:\godot_source\platform\windows\display_server_windows.cpp:4469)
[31] DisplayServerWindows::_dispatch_input_events (C:\godot_source\platform\windows\display_server_windows.cpp:4439)
[32] Input::_parse_input_event_impl (C:\godot_source\core\input\input.cpp:987)
[33] Input::flush_buffered_events (C:\godot_source\core\input\input.cpp:1292)
[34] DisplayServerWindows::process_events (C:\godot_source\platform\windows\display_server_windows.cpp:3830)
[35] OS_Windows::run (C:\godot_source\platform\windows\os_windows.cpp:2345)
[37] _main (C:\godot_source\platform\windows\godot_windows.cpp:125)
[38] main (C:\godot_source\platform\windows\godot_windows.cpp:139)
[39] WinMain (C:\godot_source\platform\windows\godot_windows.cpp:153)
[40] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[41] ShimMainCRTStartup (C:\godot_source\platform\windows\cpu_feature_validation.c:74)
[42] <couldn't map PC to fn name>
-- END OF C++ BACKTRACE --
```
There might be difference between side and bottom docks.

### Steps to reproduce

1. Make any dock floating.
2. Close it.
3. Spam Ctrl+S while the window is being closed.
4. Crash.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #113276

Progress dialog has a LocalVector of pointers to Windows (nodes, not the OS lol). The `window` is a child of WindowWrapper. The condition in WindowWrapper's destructor was always false, because the Window is freed before the wrapper, and so the ObjectID was invalid. For the purpose of removing a pointer from a vector, it does not matter if it's valid or not, so that check just didn't make sense.

Funny how ObjectID is normally supposed to prevent crashes 🤦‍♂️

### CODE REVIEW

**Comment by kitbdev** [comment]
It looks like the ObjectID was preventing a heap-use-after-free.
I think we could instead move it to predelete notification, or make Progress dialog use ObjectID.

**Comment by KoBeWi** [comment]
> heap-use-after-free.

What. How exactly it's "used"? Does passing the pointer as an argument trigger it? How it can be ignored?

**Comment by AThousandShips** [comment]
It's used to detect if the pointer is valid, it's not preventing it but the `ObjectDB` call validates the pointer

**Comment by KoBeWi** [comment]
Well, I know that, but pointer validity is not relevant here.

**Comment by AThousandShips** [comment]
Yes because the method called performs a null check which triggers use after free:
https://github.com/godotengine/godot/blob/dec5a373d97cbadce5e1fabe6095ae9957ff3aa6/editor/gui/progress_dialog.cpp#L270-L273

**Comment by KoBeWi** [comment]
This error is just stupid. Why does it care whether the pointer is freed or not? I only want to use the address, not whatever it's pointing to. How to tell the sanitizer that I know that the pointer is invalid and it doesn't matter here? I could just convert it to integer or whatever, but that probably also counts as "use".

**Comment by kitbdev** [comment]
The address sanitizer checks when passing into a function apparently. There are function attributes like `__attribute__((no_sanitize("address")))` that can be used but they depend on compiler and disable it for the whole function.

It should work if it is moved to predelete or enter/exit tree, right?

**Comment by KoBeWi** [comment]
Predelete is too late, not sure about exit tree.
But it would be nice if I could avoid making the changes more complex just to "fix" some false positive in CI :/

**Review by bruvzg — COMMENTED** [review]
This check was not doing anything useful, `host_window` store pointers, and it doesn't matter if pointer is valid. And removing invalid pointers is actually necessary.

So change looks good. But since sanitizer is not happy, I would change `host_window` and related functions to store `ObjectID`s instead of pointers. It's also safer in case some methods accessing `host_window` content is called after `Window` is freed but before pointer is removed.

```diff
diff --git a/editor/gui/progress_dialog.cpp b/editor/gui/progress_dialog.cpp
index b82b3549fc..bf3c571fe0 100644
--- a/editor/gui/progress_dialog.cpp
+++ b/editor/gui/progress_dialog.cpp
@@ -156,8 +156,11 @@ void ProgressDialog::_popup() {
        // will discard every key input.
        EditorNode::get_singleton()->set_process_input(true);
        // Disable all other windows to prevent interaction with them.
-       for (Window *w : host_windows) {
-               w->set_process_mode(PROCESS_MODE_DISABLED);
+       for (ObjectID wid : host_windows) {
+               Window *w = ObjectDB::get_instance<Window>(wid);
+               if (w) {
+                       w->set_process_mode(PROCESS_MODE_DISABLED);
+               }
        }

        Size2 ms = main->get_combined_minimum_size();
@@ -254,21 +257,22 @@ void ProgressDialog::end_task(const String &p_task) {
        if (tasks.is_empty()) {
                hide();
                EditorNode::get_singleton()->set_process_input(false);
-               for (Window *w : host_windows) {
-                       w->set_process_mode(PROCESS_MODE_INHERIT);
+               for (ObjectID wid : host_windows) {
+                       Window *w = ObjectDB::get_instance<Window>(wid);
+                       if (w) {
+                               w->set_process_mode(PROCESS_MODE_INHERIT);
+                       }
                }
        } else {
                _popup();
        }
 }

-void ProgressDialog::add_host_window(Window *p_window) {
-       ERR_FAIL_NULL(p_window);
+void ProgressDialog::add_host_window(ObjectID p_window) {
        host_windows.push_back(p_window);
 }

-void ProgressDialog::remove_host_window(Window *p_window) {
-       ERR_FAIL_NULL(p_window);
+void ProgressDialog::remove_host_window(ObjectID p_window) {
        host_windows.erase(p_window);
 }

diff --git a/editor/gui/progress_dialog.h b/editor/gui/progress_dialog.h
index 17deeac79c..4e51f9e3bf 100644
--- a/editor/gui/progress_dialog.h
+++ b/editor/gui/progress_dialog.h
@@ -79,7 +79,7 @@ class ProgressDialog : public CenterContainer {
        PanelContainer *center_panel = nullptr;
        VBoxContainer *main = nullptr;

-       LocalVector<Window *> host_windows;
+       LocalVector<ObjectID> host_windows;

        Size2 main_border_size;

@@ -101,8 +101,8 @@ public:
        bool task_step(const String &p_task, const String &p_state, int p_step = -1, bool p_force_redraw = true);
        void end_task(const String &p_task);

-       void add_host_window(Window *p_window);
-       void remove_host_window(Window *p_window);
+       void add_host_window(ObjectID p_window);
+       void remove_host_window(ObjectID p_window);

        ProgressDialog();
 };
diff --git a/editor/gui/window_wrapper.cpp b/editor/gui/window_wrapper.cpp
index 055a4361f0..e97780280d 100644
--- a/editor/gui/window_wrapper.cpp
+++ b/editor/gui/window_wrapper.cpp
@@ -383,13 +383,11 @@ WindowWrapper::WindowWrapper() {
        window_background->set_anchors_and_offsets_preset(PRESET_FULL_RECT);
        window->add_child(window_background);

-       ProgressDialog::get_singleton()->add_host_window(window);
+       ProgressDialog::get_singleton()->add_host_window(window_id);
 }

 WindowWrapper::~WindowWrapper() {
-       if (ObjectDB::get_instance(window_id)) {
-               ProgressDialog::get_singleton()->remove_host_window(window);
-       }
+       ProgressDialog::get_singleton()->remove_host_window(window_id);
 }

 // ScreenSelect
```

**Comment by kitbdev** [comment]
It is still happening, so it must be the ProgressDialog itself that is used after it is freed.

File: editor/gui/window_wrapper.cpp [hunk 1]
```diff
@@ -383,13 +383,11 @@ WindowWrapper::WindowWrapper() {
...
 
-	ProgressDialog::get_singleton()->add_host_window(window);
+	ProgressDialog::get_singleton()->add_host_window(window_id);
 }
 
 WindowWrapper::~WindowWrapper() {
-	if (ObjectDB::get_instance(window_id)) {
-		ProgressDialog::get_singleton()->remove_host_window(window);
-	}
+	ProgressDialog::get_singleton()->remove_host_window(window_id);
```
Comment (akien-mga) [inline editor/gui/window_wrapper.cpp]: Guarding on `ProgressDialog::get_singleton() != nullptr` here might solve the sanitizers issue.

Comment (KoBeWi) [reply editor/gui/window_wrapper.cpp]: Didn't help.

**Review by akien-mga — APPROVED** [review]
Seems to pass CI now!

(Android builds failed due to Maven repos being flaky, should be restarted later.)
