### PR TITLE
Export: Unify settings for PC texture formats, removed obsoleted ETC feature

### LINKED ISSUE #7230: Add warning about export missing BPTC texture format (or change export settings)
### Describe the project you are working on

A 3d game exported to multiple platforms, with VRAM compressed textures

### Describe the problem or limitation you are having in your project

I'm not familiar with the details, but it seems that in 4.1 some things changed under the hood regarding compressed VRAM textures and the resource loader. For desktop there is a project setting that should be enabled (there's a nice warning for it) to enable S3TC/BPTC textures, and it seems that if you check the "high quality" checkbox on the texture import settings it will be compressed using BPTC, otherwise S3TC.

The issue is that in the export settings for Windows and Linux you can enable/disable BPTC and S3TC texture exports separately (not on macOS exports though?). 
Screenshot 2023-07-07 at 12 12 13
And previous to 4.1 I think the default was that S3TC was enabled and BPTC disabled, and this worked fine. At least that was the export settings I had configured and used in 4.0.x previously.

However, if you try to export in 4.1 to windows without BPTC enabled in these settings the game will crash on launch if you have any textures with the "high quality" import option enabled. There will be a lot of logged errors (see example below) about the resourceloader failing to load the textures with "high quality" checked in the import settings shown scrolling by very fast for a second before the game crashes and it disappears. 

Screenshot 2023-07-07 at 12 26 01

In other words, an export configuration that worked in 4.0.x will now produce a result that crashes on launch in a way where it's pretty difficult to understand what is going wrong. 

There could very well be some sort of bug here as well, as it's at least not handling the missing texture formats very gracefully. But I'm not sure of this, so I'm putting this as a proposal to make it easier to configure the exports correctly, instead of handling the incorrect configuration better. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

At least add a warning about not having both BPTC and S3TC enabled, and perhaps an error on export time if you have textures with the high quality setting set and S3TC/BPTC enabled in the settings.

Or perhaps if they will now always be used together make the export setting a single checkbox for both S3TC and BPTC like the project setting. 

Or, even better maybe not have this export setting for texture formats at all, and just let the export destination and project settings control what texture formats are included in the export so the user can't make mistakes. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Just show the warning if S3TC is checked but not BPTC as this may cause problems.

Output an error to the log during export if a texture is encountered that is BPTC compressed but BPTC is not enabled in the export settings.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

It's export configuration settings

### LINKED ISSUE #81234: Resource is not exported correctly to PCK file
### Godot version

4.1.1.stable and previous

### System information

Windows 10

### Issue description

During working on my big project I have noticed that Godot cannot export project correctly to pck or exe file.

After running project using release template on Windows I got following error:

```
G:\Godot>Godot Engine v4.1.1.stable.official.bd6af8e0e - https://godotengine.org
Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1070

ERROR: No loader found for resource: .
   at: (core/io/resource_loader.cpp:281)
ERROR: Failed loading resource: res://gfx/cwirka.png. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:273)
ERROR: Can't load dependency: res://gfx/cwirka.png.
   at: (core/io/resource_format_binary.cpp:458)
ERROR: Failed loading resource: res://.godot/exported/133200997/export-f582aaee991195987df126394c37c52f-level_3.scn. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:273)
ERROR: Failed loading scene: res://scenes/level_3.tscn
   at: (main/main.cpp:3223)
ERROR: 2 RID allocations of type 'N10RendererRD12LightStorage11ShadowAtlasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N10RendererRD12LightStorage15ReflectionAtlasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N10RendererRD14TextureStorage12RenderTargetE' were leaked at exit.
ERROR: 2 RID allocations of type 'N10RendererRD14TextureStorage7TextureE' were leaked at exit.
ERROR: 1 RID allocations of type 'N18RendererCanvasCull6CanvasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N16RendererViewport8ViewportE' were leaked at exit.
ERROR: 1 RID allocations of type 'N17RendererSceneCull8ScenarioE' were leaked at exit.
WARNING: 4 RIDs of type "Texture" were leaked.
     at: finalize (drivers/vulkan/rendering_device_vulkan.cpp:9441)
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:2047)
```

But running application from editor works fine without errors or warnings on console:

obraz

### Steps to reproduce

I am unable to reproduce it manually but I am attaching minimal project. It was reduced from bigger project.

Attached project is made of:
- single Scene3D with Camera3D and PlaneMesh. 
- StandardMaterial3D is attached to this plane.
- StandardMaterial3D has albedo_texture set from provided texture.

### Minimal reproduction project

[export.zip](https://github.com/godotengine/godot/files/12499900/export.zip)

### LINKED ISSUE #86317: Exported game crashes due to missing resources while in-editor it runs fine
### Tested versions

- Reproducible in `v4.2.1.stable.official.b09f793f5` (December 2023)
- Not reproducible in `v4.0.3.stable.official.5222a99f5` (May 2023)
- Was a problem for 12+ months already some time before May 2023, most likely before 4.0 stable release.

### System information

Arch Linux, KDE 5, Radeon RX6800XT, X11

### Issue description

Testing my game from the editor works fine. But after exporting a game build from a template, the build throws errors about missing stuff and boots the game to a gray screen, with almost nothing working.

Swapping the engine runtime for the Godot editor doesn't make a change.
The only way to make a playable release of the game is to package all the game files together with the Godot runtime and distributing that - which is what I was doing for (I think) at least a year when a similar problem was present in Godot game exports.

It seems like the problem is strictly with the generated `.pck` or `.zip` file (I tested both).

This is the last game build I made that didn't have this problem:
image
You can download it here: https://libla.st/downloads/Liblast_dev.zip (it might be replaced in the future with a newer version so check the modification dates inside of the ZIP file).

I unfortunately can't test the exact same project in an older version of Godot, but the older versions of the game can be accessed from Liblast's git repository on Codeberg:

http://code.libla.st

So presumably if you clone and checkout the `main` branch at a commit from circa May 2023 it should build fine in Godot 4.0.3 stable. I didn't test this yet - anybody is welcome to try! Just remember to **clone** the repository - **not download ZIP** - Git LFS-stored files are essential for the game to work and will not be included in a source code archive download, making it a red herring. I wish I could disable that option...

I think this must be a regression at least in some degree, At first I thought maybe it's a bug in the feature to export only selected resources, but after switching to exporting everything the game build still fails in the same way.

Here's complete console output as I run the game, open it's internal console (the only feature of the game that works) and stop the game from there:

```
❯ ./Liblast.x86_64
Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org
Vulkan API 1.3.255 - Forward+ - Using Vulkan Device #0: AMD - AMD Radeon RX 6800 XT (RADV NAVI21)
 
ERROR: No loader found for resource:  (expected type: CompressedTexture2D)
   at: _load (core/io/resource_loader.cpp:282)
ERROR: Failed loading resource: res://Assets/Characters/CharacterHeavy_ID_Mask_Processed.png. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:274)
ERROR: Can't load dependency: res://Assets/Characters/CharacterHeavy_ID_Mask_Processed.png.
   at: parse_variant (core/io/resource_format_binary.cpp:459)
ERROR: Failed loading resource: res://.godot/exported/133200997/export-f77c830eaf23cebf5c54d514cb2310e1-CharacterBodyShader.res. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:274)
ERROR: No loader found for resource:  (expected type: CompressedTexture2D)
   at: _load (core/io/resource_loader.cpp:282)
ERROR: Failed loading resource: res://Assets/Characters/CharacterHeavy_ID_Mask_Processed.png. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:274)
ERROR: Can't load dependency: res://Assets/Shaders/Characters/CharacterBodyShader.tres.
   at: parse_variant (core/io/resource_format_binary.cpp:459)
ERROR: Failed loading resource: res://.godot/exported/133200997/export-fccab72fc104c99a9db8ddc636649342-CharacterBody.res. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:274)
ERROR: Can't load dependency: res://Assets/Materials/Characters/CharacterBody.tres.
   at: parse_variant (core/io/resource_format_binary.cpp:459)
ERROR: Error when trying to parse Variant.
   at: parse_variant (core/io/resource_format_binary.cpp:503)
ERROR: Error when trying to parse Variant.
   at: parse_variant (core/io/resource_format_binary.cpp:490)
ERROR: Failed loading resource: res://.godot/exported/133200997/export-acf2a845315cc13706608f268e070e12-Character.scn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:274)
Log file name: 2023-12-18_231655.log
 · 2023-12-18 23:16:55          658 | Liblast log start
WARNING: UPnP didn't find a Gateway
     at: push_warning (core/variant/variant_utility.cpp:1111)
ERROR: Failed to instantiate scene state of "res://Assets/Characters/Character.tscn", node count is 0. Make sure the PackedScene resource is valid.
   at: instantiate (scene/resources/packed_scene.cpp:141)
ERROR: Failed to load scene dependency: "res://Assets/Characters/Character.tscn". Make sure the required scene is valid.
   at: instantiate (scene/resources/packed_scene.cpp:222)
ERROR: Failed to load scene dependency: "res://Assets/Menu/CharacterProfilePreview.tscn". Make sure the required scene is valid.
   at: instantiate (scene/resources/packed_scene.cpp:222)
ERROR: Failed to load scene dependency: "res://Assets/Menu/UserProfileMenu.tscn". Make sure the required scene is valid.
   at: instantiate (scene/resources/packed_scene.cpp:222)
ERROR: Failed to load scene dependency: "res://Assets/Menu/MainMenu.tscn". Make sure the required scene is valid.
   at: instantiate (scene/resources/packed_scene.cpp:222)
ERROR: Parameter "p_child" is null.
   at: add_child (scene/main/node.cpp:1409)
 · 2023-12-18 23:17:25        31246 | console command: quit
 · 2023-12-18 23:17:25        31253 | Liblast log finish
 · 2023-12-18 23:17:25        31253 | stopping server
Cleaning up game state
 · 2023-12-18 23:17:25        31253 | cleaning up game state
WARNING: Trying to free a non-existing GameState
     at: push_warning (core/variant/variant_utility.cpp:1111)
ERROR: 1 RID allocations of type 'P11GodotBody3D' were leaked at exit.
ERROR: 13 RID allocations of type 'P12GodotShape3D' were leaked at exit.
ERROR: Pages in use exist at exit in PagedAllocator: N33RendererSceneRenderImplementation22RenderForwardClustered32GeometryInstanceForwardClusteredE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
ERROR: 17 shaders of type SceneForwardClusteredShaderRD were never freed
   at: ~ShaderRD (servers/rendering/renderer_rd/shader_rd.cpp:841)
ERROR: 2 RID allocations of type 'N10RendererRD5SkyRD3SkyE' were leaked at exit.
ERROR: 2 RID allocations of type 'N26RendererEnvironmentStorage11EnvironmentE' were leaked at exit.
ERROR: 2 shaders of type CanvasShaderRD were never freed
   at: ~ShaderRD (servers/rendering/renderer_rd/shader_rd.cpp:841)
ERROR: 4 shaders of type ParticlesShaderRD were never freed
   at: ~ShaderRD (servers/rendering/renderer_rd/shader_rd.cpp:841)
ERROR: 15 RID allocations of type 'N10RendererRD12LightStorage11ShadowAtlasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N10RendererRD12LightStorage23ReflectionProbeInstanceE' were leaked at exit.
ERROR: 2 RID allocations of type 'N10RendererRD12LightStorage15ReflectionAtlasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N10RendererRD12LightStorage15ReflectionProbeE' were leaked at exit.
ERROR: 1 RID allocations of type 'N10RendererRD12LightStorage13LightInstanceE' were leaked at exit.
ERROR: 1 RID allocations of type 'N10RendererRD12LightStorage5LightE' were leaked at exit.
ERROR: 24 RID allocations of type 'N10RendererRD11MeshStorage4MeshE' were leaked at exit.
ERROR: 39 RID allocations of type 'N10RendererRD15MaterialStorage8MaterialE' were leaked at exit.
ERROR: 23 RID allocations of type 'N10RendererRD15MaterialStorage6ShaderE' were leaked at exit.
ERROR: 13 RID allocations of type 'N10RendererRD14TextureStorage12RenderTargetE' were leaked at exit.
ERROR: 123 RID allocations of type 'N10RendererRD14TextureStorage7TextureE' were leaked at exit.
ERROR: 180 RID allocations of type 'N18RendererCanvasCull4ItemE' were leaked at exit.
ERROR: 13 RID allocations of type 'N18RendererCanvasCull6CanvasE' were leaked at exit.
ERROR: 13 RID allocations of type 'N16RendererViewport8ViewportE' were leaked at exit.
ERROR: 3 RID allocations of type 'N17RendererSceneCull8InstanceE' were leaked at exit.
fish: Job 1, './Liblast.x86_64' terminated by signal SIGSEGV (Address boundary error)
```

### Steps to reproduce

1. Access the game project via git.

You can follow the paragraph in our README: https://codeberg.org/liblast/liblast#_how_to_edit_the_game , or (if you're on Linux) just execute this:

```
cd ~/
git clone https://codeberg.org/Liblast/Liblast.git`
cd Liblast
git lfs install
git lfs pull
```

3. Now load the game project located in `Liblast/Game/project.godot` using Godot 4.2.1.
4. Play the game from the editor (hit F5 after the project loads)
5. Do you see and hear things outside of a gray void?
6. Now export the game (ensure you have the export templates first, like you always do).
7. Run the exported game build.
8. Do you see and hear things outside of a gray void?

### Minimal reproduction project (MRP)

:man_shrugging:

### PR DESCRIPTION
**Pull request by akien-mga**
S3TC and BPTC should always be used together, and likewise for ETC2 and ASTC.

Also removes obsolete ETC support code since we removed that format.

- Supersedes #84913, implementing https://github.com/godotengine/godot/pull/84913#issuecomment-1851613110.
- Fixes #81234.
- Fixes #86317.
- Closes https://github.com/godotengine/godot-proposals/issues/7230.

---

I didn't add compatibility code yet, it would be a bit convoluted in `EditorExportPreset::_set` which currently has its own logic for some visibility update. Could be done but I'm not sure it's worth the bother, when handling this minor compat breakage just requires ensuring that the proper formats are toggled in the settings. The default behavior for the new options is also to export S3TC/BPTC, which is the most likely combinations that users need.

Haven't tested much yet.

For a potential 4.2.x cherry-pick we might consider going with the approach in #84913 to be more conservative.

### CODE REVIEW

File: editor/export/editor_export_platform_pc.cpp [hunk 1]
```diff
@@ -237,9 +239,8 @@ void EditorExportPlatformPC::set_logo(const Ref<Texture2D> &p_logo) {
 }
 
 void EditorExportPlatformPC::get_platform_features(List<String> *r_features) const {
-	r_features->push_back("pc"); //all pcs support "pc"
-	r_features->push_back("s3tc"); //all pcs support "s3tc" compression
```
Comment (akien-mga) [inline editor/export/editor_export_platform_pc.cpp:241]: Removed this, which is redundant with the above logic, and also wrong if users for some reason decide to export ETC2/ASTC and not S3TC/BPTC.

File: modules/basis_universal/register_types.cpp [hunk 2]
```diff
@@ -190,9 +190,6 @@ static Ref<Image> basis_universal_unpacker_ptr(const uint8_t *p_data, int p_size
 			} else if (RS::get_singleton()->has_os_feature("s3tc")) {
 				format = basist::transcoder_texture_format::cTFBC1; // get this from renderer
 				imgfmt = Image::FORMAT_DXT1;
-			} else if (RS::get_singleton()->has_os_feature("etc")) {
```
Comment (BlueCube3310) [inline modules/basis_universal/register_types.cpp:193]: Note that this will break BasisU transcoding for opaque images on mobile, this could probably be changed to something like:
```cpp
else if (RS::get_singleton()->has_os_feature("etc2")) {
	format = basist::transcoder_texture_format::cTFETC1; // get this from renderer
	imgfmt = Image::FORMAT_ETC2_RGB8;
}
```

In theory this should work correctly since BasisU transcodes ETC2 RGBA as EAC alpha + ETC1 block anyways, though it would still need testing on a mobile device.

Comment (akien-mga) [reply modules/basis_universal/register_types.cpp:193]: Ah indeed, I forgot that this check I changed in the renderer code means both `etc` and `etc2` are defined and synonymous:
```cpp
if (p_feature == "etc" || p_feature == "etc2") {
	return config->etc2_supported;
}
```

For this PR, I could just replace `etc` by `etc2` and keep the format as is, which would in theory be equivalent to the status quo, and then actually changing the format could be evaluated in a follow-up?

Or I'm happy to try your version here, but indeed we need to confirm it works well.

Comment (akien-mga) [reply modules/basis_universal/register_types.cpp:193]: Updated with your snippet, thanks!

File: modules/ktx/texture_loader_ktx.cpp [hunk 3]
```diff
@@ -287,8 +287,6 @@ static Ref<Image> load_from_file_access(Ref<FileAccess> f, Error *r_error) {
 							ktxfmt = KTX_TTF_BC7_RGBA;
 						} else if (RS::get_singleton()->has_os_feature("s3tc")) {
 							ktxfmt = KTX_TTF_BC1_RGB;
-						} else if (RS::get_singleton()->has_os_feature("etc")) {
-							ktxfmt = KTX_TTF_ETC1_RGB;
```
Comment (akien-mga) [inline modules/ktx/texture_loader_ktx.cpp:291]: Based on https://github.com/godotengine/godot/pull/88325/files#r1489704307, I guess this should also be reintroduced, but with proper ETC2 support if it exists.

File: modules/ktx/texture_loader_ktx.cpp [hunk 4]
```diff
@@ -287,7 +287,7 @@ static Ref<Image> load_from_file_access(Ref<FileAccess> f, Error *r_error) {
 							ktxfmt = KTX_TTF_BC7_RGBA;
 						} else if (RS::get_singleton()->has_os_feature("s3tc")) {
 							ktxfmt = KTX_TTF_BC1_RGB;
-						} else if (RS::get_singleton()->has_os_feature("etc")) {
+						} else if (RS::get_singleton()->has_os_feature("etc2")) {
 							ktxfmt = KTX_TTF_ETC1_RGB;
```
Comment (akien-mga) [inline modules/ktx/texture_loader_ktx.cpp:291]: I kept `KTX_TTF_ETC1_RGB` here as we seem to handle only RGB here.
The options are:
```
        // ETC1-2
        KTX_TTF_ETC1_RGB = 0,
            /*!< Opaque only. Returns RGB or alpha data, if
                 KTX_TF_TRANSCODE_ALPHA_DATA_TO_OPAQUE_FORMATS flag is
                 specified. */
        KTX_TTF_ETC2_RGBA = 1,
            /*!< Opaque+alpha. EAC_A8 block followed by an ETC1 block. The
                 alpha channel will be opaque for textures without an alpha
                 channel. */

        // Values for automatic selection of RGB or RGBA depending if alpha
        // present.
        KTX_TTF_ETC = 22,
            /*!< Automatically selects @c KTX_TTF_ETC1_RGB or
                 @c KTX_TTF_ETC2_RGBA according to presence of alpha. */
```

Comment (BlueCube3310) [reply modules/ktx/texture_loader_ktx.cpp:291]: The color data encoding is ETC1 for all of them anyway, so there should not be any quality difference.

**Comment by fire** [comment]
I took a initial look at this, but we probably need to try the pr on all the devices on platforms we support like:

- [ ] Web
- [ ] Windows
- [ ] Linux
- [ ] Mac (Apple Silicon)
- [ ] ios
- [ ] android (arm64)

**Review by clayjohn — APPROVED** [review]
Looks great to me!
