### PR TITLE
Handle potential platform-specific `Window` mouse-enter/exit bugs gracefully

### LINKED ISSUE #80335: Crash when dragging the mouse in the inspector to modify a value
### Godot version

v4.2.dev.custom_build [16a93563b]

### System information

Godot v4.2.dev (16a93563b) - Linux Mint 21.2 (Victoria) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (nvidia; 525.125.06) - Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 Threads)

### Issue description

https://github.com/godotengine/godot/assets/30386067/335cd974-1261-4c88-829c-159a771eaae3

When dragging the mouse in the inspector to modify a value, the editor would crash if the left mouse button was released.

```
ERROR: FATAL: DEV_ASSERT failed  "!root->gui.windowmanager_window_over" is false.
   at: _event_callback (scene/main/window.cpp:675)
```

<details><summary>Crash log</summary>

```
================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.2.dev.custom_build (16a93563bfd3b02ca0a8f6df2026f3a3217f5571)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f765fc42520] (??:0)
[2] Window::_event_callback(DisplayServer::WindowEvent) (/opt/godot/godot-editor-l10n/godot/scene/main/window.cpp:675)
[3] void call_with_variant_args_helper<Window, DisplayServer::WindowEvent, 0ul>(Window*, void (Window::*)(DisplayServer::WindowEvent), Variant const**, Callable::CallError&, IndexSequence<0ul>) (/opt/godot/godot-editor-l10n/godot/./core/variant/binder_common.h:308)
[4] void call_with_variant_args<Window, DisplayServer::WindowEvent>(Window*, void (Window::*)(DisplayServer::WindowEvent), Variant const**, int, Callable::CallError&) (/opt/godot/godot-editor-l10n/godot/./core/variant/binder_common.h:418)
[5] CallableCustomMethodPointer<Window, DisplayServer::WindowEvent>::call(Variant const**, int, Variant&, Callable::CallError&) const (/opt/godot/godot-editor-l10n/godot/./core/object/callable_method_pointer.h:105)
[6] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (/opt/godot/godot-editor-l10n/godot/core/variant/callable.cpp:51)
[7] DisplayServerX11::_send_window_event(DisplayServerX11::WindowData const&, DisplayServer::WindowEvent) (/opt/godot/godot-editor-l10n/godot/platform/linuxbsd/x11/display_server_x11.cpp:3771)
[8] DisplayServerX11::mouse_set_mode(DisplayServer::MouseMode) (/opt/godot/godot-editor-l10n/godot/platform/linuxbsd/x11/display_server_x11.cpp:383)
[9] DisplayServer::_input_set_mouse_mode(Input::MouseMode) (/opt/godot/godot-editor-l10n/godot/servers/display_server.cpp:944)
[10] Input::set_mouse_mode(Input::MouseMode) (/opt/godot/godot-editor-l10n/godot/core/input/input.cpp:90)
[11] EditorSpinSlider::gui_input(Ref<InputEvent> const&) (/opt/godot/godot-editor-l10n/godot/editor/gui/editor_spin_slider.cpp:81)
[12] Control::_call_gui_input(Ref<InputEvent> const&) (/opt/godot/godot-editor-l10n/godot/scene/gui/control.cpp:1806)
[13] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (/opt/godot/godot-editor-l10n/godot/scene/main/viewport.cpp:1562)
[14] Viewport::_gui_input_event(Ref<InputEvent>) (/opt/godot/godot-editor-l10n/godot/scene/main/viewport.cpp:1831)
[15] Viewport::push_input(Ref<InputEvent> const&, bool) (/opt/godot/godot-editor-l10n/godot/scene/main/viewport.cpp:3128)
[16] Window::_window_input(Ref<InputEvent> const&) (/opt/godot/godot-editor-l10n/godot/scene/main/window.cpp:1482)
[17] void call_with_variant_args_helper<Window, Ref<InputEvent> const&, 0ul>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (/opt/godot/godot-editor-l10n/godot/./core/variant/binder_common.h:303)
[18] void call_with_variant_args<Window, Ref<InputEvent> const&>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, int, Callable::CallError&) (/opt/godot/godot-editor-l10n/godot/./core/variant/binder_common.h:418)
[19] CallableCustomMethodPointer<Window, Ref<InputEvent> const&>::call(Variant const**, int, Variant&, Callable::CallError&) const (/opt/godot/godot-editor-l10n/godot/./core/object/callable_method_pointer.h:105)
[20] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (/opt/godot/godot-editor-l10n/godot/core/variant/callable.cpp:51)
[21] DisplayServerX11::_dispatch_input_event(Ref<InputEvent> const&) (/opt/godot/godot-editor-l10n/godot/platform/linuxbsd/x11/display_server_x11.cpp:3751)
[22] DisplayServerX11::_dispatch_input_events(Ref<InputEvent> const&) (/opt/godot/godot-editor-l10n/godot/platform/linuxbsd/x11/display_server_x11.cpp:3723)
[23] Input::_parse_input_event_impl(Ref<InputEvent> const&, bool) (/opt/godot/godot-editor-l10n/godot/core/input/input.cpp:721)
[24] Input::flush_buffered_events() (/opt/godot/godot-editor-l10n/godot/core/input/input.cpp:979)
[25] DisplayServerX11::process_events() (/opt/godot/godot-editor-l10n/godot/platform/linuxbsd/x11/display_server_x11.cpp:4819)
[26] OS_LinuxBSD::run() (/opt/godot/godot-editor-l10n/godot/platform/linuxbsd/os_linuxbsd.cpp:908)
[27] /opt/godot/godot/bin/godot.linuxbsd.editor.dev.x86_64.llvm(main+0x1fe) [0x560f366a986e] (/opt/godot/godot-editor-l10n/godot/platform/linuxbsd/godot_linuxbsd.cpp:74)
[28] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f765fc29d90] (??:0)
[29] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f765fc29e40] (??:0)
[30] /opt/godot/godot/bin/godot.linuxbsd.editor.dev.x86_64.llvm(_start+0x25) [0x560f366a95a5] (??:?)
-- END OF BACKTRACE --
================================================================
```
</details> 

This seems to be a regression from #67791.

### Steps to reproduce

1. Click on the number field with the left mouse button;
2. Drag the mouse to change the value;
3. The editor will crash when the left mouse button is released.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Sauermann**
Also replace `DEV_ASSERT` by `ERR_FAIL`.

followup to #67791
implement comment https://github.com/godotengine/godot/pull/67791#issuecomment-1661646618
based on #80156
fix #80335

### CODE REVIEW

**Review by lawnjelly — APPROVED** [review]

**Review by RandomShaper — APPROVED** [review]

**Comment by Sauermann** [comment]
After giving it some thought, I'm no longer sure, if ERR_FAIL is needed, because with this change, `Window` handles all possible cases.

File: scene/main/window.cpp [hunk 1]
```diff
@@ -672,16 +672,21 @@ void Window::_event_callback(DisplayServer::WindowEvent p_event) {
...
 			notification(NOTIFICATION_VP_MOUSE_ENTER);
 			if (DisplayServer::get_singleton()->has_feature(DisplayServer::FEATURE_CURSOR_SHAPE)) {
 				DisplayServer::get_singleton()->cursor_set_shape(DisplayServer::CURSOR_ARROW); //restore cursor shape
 			}
+			ERR_FAIL_COND_MSG(previous_over, "Entering a window while a window is hovered should never happen.");
 		} break;
 		case DisplayServer::WINDOW_EVENT_MOUSE_EXIT: {
 			Window *root = get_tree()->get_root();
-			DEV_ASSERT(root->gui.windowmanager_window_over); // Exiting a window, while no window is hovered should never happen.
+			ERR_FAIL_NULL_MSG(root->gui.windowmanager_window_over, "Exiting a window, while no window is hovered should never happen.");
```
Comment (akien-mga) [inline scene/main/window.cpp:689]:
```suggestion
			ERR_FAIL_NULL_MSG(root->gui.windowmanager_window_over, "Exiting a window while no window is hovered should never happen.");
```

But "should never happen" is still the kind of message that one would use for a `DEV_ASSERT`.

If it can be triggered by user code, and thus require an `ERR_FAIL` for graceful handling, then it does actually happen and the message should clarify what went wrong so that the user can fix it on their side.

Comment (akien-mga) [reply scene/main/window.cpp:689]: Though I guess here the "user" can be a platform port that does things wrong in its window handling? So I guess it makes sense as is.

File: scene/main/window.cpp [hunk 2]
```diff
@@ -672,16 +672,21 @@ void Window::_event_callback(DisplayServer::WindowEvent p_event) {
 		case DisplayServer::WINDOW_EVENT_MOUSE_ENTER: {
 			_propagate_window_notification(this, NOTIFICATION_WM_MOUSE_ENTER);
 			Window *root = get_tree()->get_root();
-			DEV_ASSERT(!root->gui.windowmanager_window_over); // Entering a window while a window is hovered should never happen.
+			Window *previous_over = root->gui.windowmanager_window_over;
```
Comment (bruvzg) [inline scene/main/window.cpp:675]: If `mouse exit` was not received, `windowmanager_window_over` might be an invalid pointer to the deleted `Window` (the same might happen in `Viewport._update_mouse_over()`). Maybe `ObjectID` should be stored instead.

**Review by bruvzg — COMMENTED** [review]
> After giving it some thought, I'm no longer sure, if ERR_FAIL is needed, because with this change, Window handles all possible cases.

Probably not, I'm sure, if arrival of system move event messages is always guaranteed, and error won't be useful for users. It should be OK to simply ignore duplicate mouse enter/exit events.

**Review by Sauermann — COMMENTED** [review]
> Probably not, I'm sure, if arrival of system move event messages is always guaranteed, and error won't be useful for users. It should be OK to simply ignore duplicate mouse enter/exit events.

So for me this boils down to the following question:
- Should platform-implementations be forced to adhere to the same behavior regarding send mouse-enter window-events or
- should platform-implementations be allowed to be vague about mouse-enter window-events and catch all possible cases in the `Window`-class?

Personally I believe that the goal should be to align the behavior of all platform-implementations.

File: scene/main/window.cpp (hunk 2 above)
Comment (Sauermann) [reply scene/main/window.cpp:674]: I have tried multiple ways to cause a crash on X11 based on stale `gui.windowmanager_window_over`
- situations, that crashed without this fix
- explicitly freeing (queue_free and free)

But I wasn't able to cause a crash. However I can't rule out, that it is possible to cause a crash this way.

**Comment by clayjohn** [comment]
Testing this locally. It fixes the crash caused by the dev assert. But every single time I interact with the 3D viewport I get the "Entering a window while hovering it should never happen." error.

**Comment by lawnjelly** [comment]
Maybe a `WARN_PRINT_ONCE` might be better if it is spamming until the bug causing this is fixed?

**Comment by Sauermann** [comment]
Had the same idea about `WARN_PRINT_ONCE`. Will update the PR.

**Review by akien-mga — APPROVED** [review]
Seems good as a stopgap solution.
