### PR TITLE
Fix `FileAccess.seek_end` behavior on Android

### LINKED ISSUE #115553: FileAccess.seek_end has platform dependent seek behavior
### Tested versions

- Reproducible in: 4.6 stable

I'm only able to test since the introduction of Storage Access Framework, but I find it likely that this is not a regression, or it at least spans across several versions.

### System information

Godot v4.6.stable - Windows 10 (build 19044) - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3050 Laptop GPU (NVIDIA; 31.0.15.1659) - AMD Ryzen 7 5800H with Radeon Graphics (16 threads) - 13.85 GiB memory

### Issue description

On Windows and Linux, `position` is passed down as a negative number, according to documentation.

On Android (tested on Huawei TGR-W09), the seek direction is flipped, breaking my game. When I pass a positive number instead, it works as intended.

Additionally, it seems that this specific line is the root cause of the bug:
https://github.com/godotengine/godot/blob/5ad8b27d8db0776700c2b08bf68fbea5e0a4680d/platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/DataAccess.kt#L206

### Steps to reproduce

```gdscript
# on a non-empty file
func test(file: FileAccess) -> void:
	var size := file.get_length()
	file.seek_end(-1)
	var pos := file.get_position()
	assert(pos < size, "huh")
```

### Minimal reproduction project (MRP)

[seekbug.zip](https://github.com/user-attachments/files/24925231/seekbug.zip)

### PR DESCRIPTION
**Pull request by syntaxerror247**
- Fixes #115553

### CODE REVIEW

File: platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/DataAccess.kt [hunk 1]
```diff
@@ -203,7 +203,7 @@ internal abstract class DataAccess {
 	abstract fun write(buffer: ByteBuffer): Boolean
 
 	fun seekFromEnd(positionFromEnd: Long) {
-		val positionFromBeginning = max(0, size() - positionFromEnd)
+		val positionFromBeginning = max(0, size() + positionFromEnd)
```
Comment (m4gr3d) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/DataAccess.kt]: We should constrain the value to be within `0 <= x <= size()` otherwise if a positive number is passed, then the logic will be seeking past the end of the file.

Could you also add unit tests to validate the behavior.

**Review by m4gr3d — CHANGES_REQUESTED** [review]

File: platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/DataAccess.kt (hunk 1 above)
Comment (syntaxerror247) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/DataAccess.kt]: > otherwise if a position number is passed, then the logic will be seeking past the end of the file.

I kept it like this to match the behaviour I observed on linux. 
```
file.seek_end(10)
print(file.get_length()) # returns 16
print(file.get_position()) # returns 26
```

Not sure what should be expected behaviour.

cc @deralmas @bruvzg

Comment (AThousandShips) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/DataAccess.kt]: Based on the documentation the method is only supposed to support negative values, but that might be incorrect

Comment (AThousandShips) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/DataAccess.kt]: It works the same way on Windows as on Linux

Comment (deralmas) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/DataAccess.kt]: Adding to ATS' findings, code-wise, on Linux/BSD, `FileAccessUnix::seek_end` does _no_ checks for this. It just passes the offset to `fseeko` with `SEEK_END`, which simply adds the offset to the end-of-file.

POSIX manual says:

> The new position, measured in bytes from the beginning of the file, shall be obtained by adding offset to the position specified by whence. The specified point is the beginning of the file for SEEK_SET, the current value of the file-position indicator for SEEK_CUR, or end-of- file for SEEK_END.

`core/io/file_access.h` says `///< seek from the end of file with negative offset` but apparently the negative offset is supposed to be provided by the user.

So this looks like intended behavior, probably as a result of mirroring system APIs.

Comment (AThousandShips) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/DataAccess.kt]: Windows also does no checking, though the documentation for the windows API file it uses doesn't seem to specify anything

Edit: the standard library `std::fstream` system also supports seeking this way

Comment (syntaxerror247) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/DataAccess.kt]: How should we proceed then?

Comment (AThousandShips) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/DataAccess.kt]: I'd say the documentation should be fixed and the behavior made to match on all platforms, changing the behavior would break compatibility as I'd say it's generally expected since other libraries work this way (generally extending the file from the end)

Comment (syntaxerror247) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/DataAccess.kt]: updated class reference

Comment (m4gr3d) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/DataAccess.kt]: I'm good to go with this approach to match the behavior on other platforms. Can you add unit tests to validate the behavior.

Comment (syntaxerror247) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/DataAccess.kt]: @m4gr3d On desktop platforms, seeking to a position below zero doesn't clamp the value to 0. It simply ignores the call and does nothing. Then we shouldn't clamp to 0 on Android?

~@AThousandShips, could you check how this behaves on Windows?~ Oh, CI already do unit tests for Windows too.

**Review by m4gr3d — APPROVED** [review]
