### PR TITLE
Don't strip whitespace when converting 3to4.

### LINKED ISSUE #74204: The --convert-3to4 flag removes spaces around commas
### Godot version

4.0-stable

### System information

Linux

### Issue description

The [style guide](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_styleguide.html#whitespace) says 

> Always use one space around operators and after commas

However, the 3to4 tool will remove these spaces when converting `connect` and `init`

```diff
-               timer.connect("timeout", visual, "queue_free")
+               timer.connect("timeout",Callable(visual,"queue_free"))

-       func _init(section: String, key: String, default: int, bounds: PoolIntArray).(section, key, default) -> void:
+       func _init(section: String,key: String,default: int,bounds: PackedInt32Array,section,key,default):

```

### Steps to reproduce

```extends Node

func _ready() -> void:
        connect("visibility_changed",Callable(self,"_on_visibility_changed"))

func _on_visibility_changed():
        pass
```

Write this to Example.gd in a godot3 project, then run `godot4 --convert-3to4`

### Minimal reproduction project

[example.zip](https://github.com/godotengine/godot/files/10867152/example.zip)

### PR DESCRIPTION
**Pull request by rcorre**
Fixes #74204.

The style guide says

> Always use one space around operators and after commas

The 3to4 conversion tool currently strips space in certain scenarios.
I've updated it to add space whenever it is generating new code.
In any case where it substitutes existing code, it leaves it as-is.

For example, connect(a,b,c) becomes `connect(a, callable(b, c))`, because the converter is adding new commads/parens.

However, `xform(Vector3(a,b,c))` becomes `Transform * Vector3(a,b,c)` because it uses the user's original Vector3 string whole. If the user originally had `xform(Vector3(a, b, c))`, then it becomes `Transform * Vector3(a, b, c)`.

Ideally we'd always preserve original formatting, but this seems quite difficult, so I tried to preserve it where we can, but air on the side of following the style guide whenever we're transforming code.

### CODE REVIEW

File: editor/project_converter_3_to_4.cpp [hunk 1]
```diff
@@ -304,7 +304,7 @@ bool ProjectConverter3To4::convert() {
 	maximum_line_length = 10000; // Use only for tests bigger value, to not break them.
 
 	ERR_FAIL_COND_V_MSG(!test_array_names(), false, "Cannot start converting due to problems with data in arrays.");
-	ERR_FAIL_COND_V_MSG(!test_conversion(reg_container), false, "Cannot start converting due to problems with converting arrays.");
+	ERR_FAIL_COND_V_MSG(!test_conversion(reg_container), false, "Cannot start converting due to problems with converting.");
```
Comment (akien-mga) [inline editor/project_converter_3_to_4.cpp:307]: That error message isn't very clear :D

**Review by akien-mga — APPROVED** [review]

File: editor/project_converter_3_to_4.cpp (hunk 1 above)
Comment (rcorre) [reply editor/project_converter_3_to_4.cpp:307]: True :laughing:. I wasn't sure what to call it. It wasn't specifically "arrays", more just "converting stuff in general".

Comment (rcorre) [reply editor/project_converter_3_to_4.cpp:307]: "Can't start converting due to the errors above", maybe, since there should be at least one preceding error that explains the issue?

Comment (akien-mga) [reply editor/project_converter_3_to_4.cpp:307]: Maybe "Aborting conversion due to validation tests failing."?

Comment (rcorre) [reply editor/project_converter_3_to_4.cpp:307]: Updated the message.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.1.
