### PR TITLE
Fix Camera 2D position not updating correctly

### LINKED ISSUE #56336: Camera2D limits doesn't work well if limit_smoothed is enabled
### Godot version

3.4.2 stable

### System information

Windows 10, GLES2, Intel HD Graphics 610

### Issue description

Since godot version 3.4.1 the camera limits stop working properly if `limit_smoothed` is enabled, while in previous versions it never gave problems. When starting the scene, you notice a movement of the camera as if it was being moved:

https://user-images.githubusercontent.com/30391210/147719762-52a1872f-0db4-495f-be4c-41a1abe9b6ef.mp4

And sometimes when setting certain limits, the camera moves slightly.

In 3.3.3 works fine:

https://user-images.githubusercontent.com/30391210/147719778-4460e59f-c7de-482e-9e9f-0b5d74b13d09.mp4

But this happens with 3.4.1 and 3.4.2

https://user-images.githubusercontent.com/30391210/147719804-4fffaf9e-42c5-4f31-9702-fa1da4f1e101.mp4

### Steps to reproduce

Enable `limit_smoothed` and `smoothing_enabled` to `true` on Camera2D.

### Minimal reproduction project

[TestCamera2DLimits.zip](https://github.com/godotengine/godot/files/7791377/TestCamera2DLimits.zip)

### LINKED ISSUE #56913: [3.4] When limit smoothing and smoothing are enabled simultaneously and the Camera2D is outside of the limits, there is a one frame delay before the smoothing starts.
### Godot version

3.4.stable

### System information

Ubuntu 20.04.3 LTS

### Issue description

When Camera2D has limit smoothing enabled, smoothing enabled, and is outside of the limits, it starts sliding to the new limits one frame late.
This behavior did not exist in 3.3, since the camera would always immediately snap into the limits in that version, which was changed in #49409
It also does not occur for smoothing in general, even if Camera2D has the same properties. If position is changed and then reset_smoothing is called in the same function, the camera will immediately slide there. The behavior outside of limits is inconsistent in this regard.

### Steps to reproduce

1. Create a Camera2D and set its limits to small numbers
2. Enable Limit Smoothing and Smoothing
3. Move the Camera2D outside of the limits.
4. Run the project

Since it's just a one frame delay, to make the bug visible would take a bit more, in my minimal reproduction project I did the following:
1. Create a script
2. Call reset_smoothing on the Camera2D
3. Pause the tree in the same function to see the delay.

### Minimal reproduction project

[Camera issue.zip](https://github.com/godotengine/godot/files/8750422/Camera.issue.zip)
(Comment and uncomment the line that pauses the tree to see the jump clearly)

### PR DESCRIPTION
**Pull request by madmiraal**
Currently, `SceneTree`'s initial `physics_process_time` and `process_time` are set to `1` second. So early calls to `get_process_delta_time()` or `get_physics_process_delta_time()` return unreasonably large values, which causes incorrect calculations. Most notably in `Camera2D`'s initial position when smoothing is enabled:
https://github.com/godotengine/godot/blob/5a6b13b8bb128a0e10cccab8f212b1ed15cea425/scene/2d/camera_2d.cpp#L158-L161

In addition, when a `Camera2D`'s limits are updated, the camera's position is not updated. This is requiring users to unnecessarily, manually call the hidden `_update_scroll()` method.

This PR fixes both these issues by setting `SceneTree`'s initial process times to `0` and calling `_update_scroll()` when setting limits. It also fixes `scene_tree.h`'s clang formatting, required to make changes to `scene_tree.h` and a `TestEdit` test that depends on `SceneTree`'s initial process times being arbitrarily greater than `0`.

Fixes #56336
Fixes #56913

### CODE REVIEW

File: scene/main/scene_tree.h [hunk 1]
```diff
@@ -236,7 +236,9 @@ class SceneTree : public MainLoop {
 		GROUP_CALL_UNIQUE = 4,
 	};
 
-	_FORCE_INLINE_ Window *get_root() const { return root; }
+	_FORCE_INLINE_ Window *get_root() const {
+		return root;
+	}
```
Comment (akien-mga) [inline scene/main/scene_tree.h:241]: This is actually a bug in clang-format 14, it shouldn't do that. https://github.com/llvm/llvm-project/issues/54901
It's fixed but only in the unreleased clang-format 15 :(

File: scene/main/scene_tree.h [hunk 2]
```diff
@@ -90,8 +90,8 @@ class SceneTree : public MainLoop {
 	Window *root = nullptr;
 
 	uint64_t tree_version = 1;
-	double physics_process_time = 1.0;
-	double process_time = 1.0;
+	double physics_process_time = 0;
+	double process_time = 0;
```
Comment (akien-mga) [inline scene/main/scene_tree.h:94]: We try to write doubles with the decimal too to be explicit, so this should be `0.0`.

File: tests/scene/test_text_edit.h [hunk 3]
```diff
@@ -3139,7 +3139,7 @@ TEST_CASE("[SceneTree][TextEdit] viewport") {
 	v_scroll = text_edit->get_v_scroll();
 	SEND_GUI_MOUSE_BUTTON_EVENT(text_edit, Point2i(10, 10), MouseButton::WHEEL_DOWN, MouseButton::WHEEL_DOWN, Key::NONE);
 	text_edit->notification(TextEdit::NOTIFICATION_INTERNAL_PHYSICS_PROCESS);
-	CHECK(text_edit->get_v_scroll() > v_scroll);
+	CHECK(text_edit->get_v_scroll() >= v_scroll);
```
Comment (akien-mga) [inline tests/scene/test_text_edit.h:3142]: Nitpick, but this commit should likely come before the SceneTree change in the commit history, otherwise it means we have 2 commits with failing tests that would end up merged.

File: scene/main/scene_tree.h (hunk 1 above)
Comment (akien-mga) [reply scene/main/scene_tree.h:241]: You might be able to drop this commit and still fool clang-format 14 btw, so far I've managed to not commit these bogus changes from that version.

Comment (madmiraal) [reply scene/main/scene_tree.h:241]: I can run `git commit` with `--no-verify`.

Comment (madmiraal) [reply scene/main/scene_tree.h]: I've dropped the commit and static checks have passed.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
