### PR TITLE
Persisting view mode for new scene

### LINKED ISSUE #36339: Orthogonal mode in 3D viewport is not sustained
**Godot version:** 3.2.stable

**OS/device including version:** Windows 10 v1909

**Issue description:**
When adding a new scene, the 3D viewport is in Perspective mode, despite last scene being set to Orthogonal and the option being "selected".

ezgif-2-f714517f21c7

**Steps to reproduce:**
1. Set viewport mode to Orthogonal.
2. Add a new scene.
3. Observe that viewport is in Perspective mode but Orthogonal mode is selected in viewport menu.

**Minimal reproduction project:**
[orthogonal.zip](https://github.com/godotengine/godot/files/4222420/orthogonal.zip)

### PR DESCRIPTION
**Pull request by Janglee123**
Fixes #36339 
Persistence the view mode for a new scene, but don't change the view for the already opened scene. It might be confusing as view mode doesn't persistent for all scenes. 
Peek 2020-02-19 12-55
PS: Sorry for flickering.

### CODE REVIEW

File: editor/plugins/spatial_editor_plugin.cpp [hunk 1]
```diff
@@ -163,6 +163,7 @@ void SpatialEditorViewport::_update_camera(float p_interp_delta) {
 			camera->set_perspective(get_fov(), get_znear(), get_zfar());
 
 		update_transform_gizmo_view();
+
```
Comment (akien-mga) [inline editor/plugins/spatial_editor_plugin.cpp]: This is not necessary.

File: editor/plugins/spatial_editor_plugin.cpp [hunk 2]
```diff
@@ -2119,9 +2120,12 @@ void SpatialEditorViewport::_notification(int p_what) {
 
 		bool visible = is_visible_in_tree();
 
+
```
Comment (akien-mga) [inline editor/plugins/spatial_editor_plugin.cpp]: This will add a style issue, as `clang-format` ensures that we don't have more than 1 consecutive empty lines. See http://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html

**Review by JFonS — APPROVED** [review]
Style issues aside, looks good to me! Thanks.

**Comment by akien-mga** [comment]
I missed that this was targeting the `3.2` branch. PRs should be made against the `master` branch, we do the backports to 3.2 or earlier when relevant.

You can create a new branch based on `master`, cherrypick this commit, amend it for style fixes, and force push the new branch to your PR to update it. You can then edit the PR on GitHub to change the target branch to `master`. Alternatively, it's fine to close it and create a new PR for `master` directly.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Looks great, thanks!

Looks like the CI checks got confused by the branch change, so you might need to force push an empty edit to force a restart of the builds. You might want to slightly improve the commit message while doing it, e.g.:
```
Make orthogonal view mode persistent in new scene

Fixes #36339.
```

**Comment by Janglee123** [comment]
Done. I should focus on commits. :sweat_smile:

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.1.
