### PR TITLE
Fix no mouse if touch device present in X11

### LINKED ISSUE #14427: Mouse input in editor not working
**Operating system and version:**
x64 Ubuntu 17.10 (using X.org not Wayland), master@2c6af835a1fa5518e95d874559bdcd90ce5cb24e

**Issue description:**
The editor has recently stopped registering any mouse input events (clicks, mouse over). Keyboard works fine.

I've tracked the issue down to the following commit: [b87abeb9f9976b2b4559753de3a3b95e29ce043c](https://github.com/godotengine/godot/commit/b87abeb9f9976b2b4559753de3a3b95e29ce043c)
The issue does not occur when compiling master before that.

**Steps to reproduce:**
Compile from master (Options used: platform=x11 target=debug)
Start editor
Mouse input should already be broken in project selector.

### PR DESCRIPTION
**Pull request by RandomShaper**
Plus several improvements in this area.

Sadly, grabbing has been disabled until a better solution is found.

Fixes #14427.

### CODE REVIEW

File: platform/x11/os_x11.cpp [hunk 1]
```diff
@@ -215,7 +214,7 @@ void OS_X11::initialize(const VideoMode &p_desired, int p_video_driver, int p_au
 			XIFreeDeviceInfo(info);
 
 			if (!touch.devices.size()) {
-				fprintf(stderr, "No suitable touch device found\n");
+				fprintf(stderr, "No touch devices found\n");
```
Comment (akien-mga) [inline platform/x11/os_x11.cpp]: This is quite verbose btw. Godot is sadly not so well equipped to handle proper info logging that could be toggled via switch, but you could put this behind the verbose mode flag.

Comment (akien-mga) [reply platform/x11/os_x11.cpp]: Also, remember that you can use `ERR_PRINT`, `ERR_PRINTS`, etc. when relevant (not suitable for this one as it's not an actual error, but for the above ones I guess it may be).

Comment (RandomShaper) [reply platform/x11/os_x11.cpp]: Since I plan to revisit this very soon, I'll improve all that.
