### PR TITLE
DirectX DescriptorsHeap pooling on CPU

### LINKED ISSUE #102463: [DirectX12] [CRASH/LAG] CreateDescriptorHeap fails when using more than few GPUParticles3D
### Tested versions

-Reproducible in 4.4.beta2, 4.3.stable

### System information

Windows 10 , GeForce RTX 3080 Ti, DirectX12

### Issue description

We are running into issues with the DirectX12 backend where using the [GPUParticles3D](https://docs.godotengine.org/en/stable/classes/class_gpuparticles3d.html) type of node.

It seems that creating more than a magic number of particle emitters the DirectX12 backend leads to a crash/error, depending on how these are used.
If the heightmap entity is used this almost directly leads to crashes as there are some code paths there which do not survive a failed allocation.

Otherwise it can lead to GPU memory corruption in serve cases.

[CreateDescriptorHeap](https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12device-createdescriptorheap) returns [E_OUTOFMEMORY](https://learn.microsoft.com/en-us/windows/win32/direct3d12/d3d12-graphics-reference-returnvalues). Even if the GPU/CPU still has free memory available. 

```
ERROR: CreateDescriptorHeap failed with error 0x8007000e.
   at: (drivers\d3d12\rendering_device_driver_d3d12.cpp:347)
ERROR: Method/function failed. Returning: UniformSetID()
   at: uniform_set_create (drivers\d3d12\rendering_device_driver_d3d12.cpp:3884)
ERROR: Condition "!driver_uniform_set" is true. Returning: RID()
   at: uniform_set_create (servers\rendering\rendering_device.cpp:3151)
```

If run with **Vulkan** there does not seem to be such a limit and one can spawn an almost endless amount of particle emitters. 

If using lots of particle emitters with an existing game, this bug seem to trigger after a while depending on how many emitters are active at once but it seems like some resource is also cumulated over time. 
Once this "state" triggers there is nothing we can do to fix it but to restart the game.

Increasing [max_resource_descriptors_per_frame](https://docs.godotengine.org/de/4.x/classes/class_projectsettings.html#class-projectsettings-property-rendering-rendering-device-d3d12-max-resource-descriptors-per-frame) or similar does not seem to change the amount of particle emitters allowed.

We are still getting traces from players >1h  into the game even if we limit the amount of concurrent particle emitters to the absolute minimum. No other backend experiences the same issues.

### Steps to reproduce

Run the example project on a Windows machine it will default to DirectX 12. Notice the errors after a while.

Create a specific amount of GPUParticles3D without deleting them. 
In case of our local GPUs this number seems to be fixed to <800 but this could be a Nvidia specific settings.  From bug reports we know that it affects all GPU vendors. 

In more complex settings it seems that this can also somehow either happen over time, or the number can become way smaller if a game is running instead of only particle emitters.

### Minimal reproduction project (MRP)

[particlebugminimal.zip](https://github.com/user-attachments/files/18676903/particlebugminimal.zip)

### PR DESCRIPTION
**Pull request by lrahmann**
This PR refactors/improves the RenderingDeviceDriverD3D12::DescriptorsHeap implementation by:

- Seperating ``RenderingDeviceDriverD3D12::DescriptorsHeap`` into ``RenderingDeviceDriverD3D12::CPUDescriptorsHeap`` and ``RenderingDeviceDriverD3D12::GPUDescriptorsHeap``
- Implementing a fixed size pool for ``RenderingDeviceDriverD3D12::CPUDescriptorsHeap`` to prevent ``RenderingDeviceDriverD3D12::CPUDescriptorsHeap::allocate`` from failing.
- Adding a "fallback" CPUDescriptorsHeap if the allocate ever fails. While this is not good, its better than the slow heap corruption which will happen otherwise. This may be optional as the above fixed the issue from my side.

With this CPUDescriptorsHeap will be allocated with a minimal size of 1024 elements, which is then spread in fixed size blocks.
This massively reduces the number of ``ID3D12DescriptorHeap`` allocated. 

This addresses descriptor allocation failures and heap corruption in D3D12, specifically fixing issues like #102463 and #103501. The primary issue was ``DescriptorsHeap::allocate`` failing for CPU only descriptor heaps, which this PR solves.
It is somewhat inspired by the SDL3 way of just allocating one CPUDescriptorHeap with 1024 entries and distributing this. 

While my minimal example in #102463 seems to work now even without this PR, local game testing confirms these changes prevent the allocation failures and subsequent corruption. I will try to make another example if this is needed.

As I am neither a C++ or DirectX expert/developer, further review and refinement by experienced developers would be appreciated.

_Bugsquad edit: Fixes: #102463 Fixes #103501 _

### CODE REVIEW

**Comment by lrahmann** [comment]
> > The primary issue was DescriptorsHeap::allocate failing for CPU only descriptor heaps
> 
> What was the reason behind the failure?

I honestly have no idea.  Probably just the fact that nobody else is doing this so they don't test their drivers accordingly? We do have crashes with this stack traces across all vendors. 

When debugging it locally the nvidia driver is  spewing E_OUT_OF_MEMORY exceptions whenever you try to allocate a new DescriptorHeap (non shader visible) after hitting this limit.  I can send you driver stacktraces if you are intrested in those. 

This then results in broken uniform buffers and their likes, and somewhere later a segmentation fault. 
If needed I can try to make another minimal viable example. 
Getting it to crash needs a somewhat more complex scene, as this doesn't happen directly.

But this is really affecting us, preventing us from using DirectX as a default backend.

**Comment by lrahmann** [comment]
@DarioSamo 

it bugs me aswell, but the exception does come from one of the nvidia_driver dlls. That is probably the reason why its not documented anywhere. 

If you check out 4.3 the example from me is more or less doing this in #102463.  Its basically a few line GDScript creating new GPUParticle3Ds, after a certain count these errors will pop up on the d3d12 backend. This was fixed with 4.5.master but I'm  not sure why, probably because some optimization is preventing the uniform sets from being created.

I don't know enough of modern graphic apis to build an example outside of godot.

**Comment by lrahmann** [comment]
> > When debugging it locally the nvidia driver is spewing E_OUT_OF_MEMORY exceptions whenever you try to allocate a new DescriptorHeap (non shader visible) after hitting this limit. I can send you driver stacktraces if you are intrested in those.
> 
> I think the part that bugs me about it is that non-shader visible descriptor heaps are mostly CPU-side structures. Would the reason be that the driver is unable to create heaps past a certain amount (e.g. not the total amount of descriptors but rather, the amount of heaps)? It'd be easy to verify this if you just allocate them linearly until it fails during initialization.

To reply to your edit, its definitly amount of heaps no amount descriptors. Basically this PR reduces the amount of heaps we need to allocate in total but increases the amount of descriptors. In fact I first tried simply pooling the heaps instead of recreating them all the time, that did not fix the issue. 

If we do not need linear CPU descriptor sets later on we can make this more optimal by distributing the DescriptorHandles seperatly but I'm not sure what perfomance impact that would entail.

File: drivers/d3d12/rendering_device_driver_d3d12.cpp [hunk 1]
```diff
@@ -319,56 +319,203 @@ const RenderingDeviceDriverD3D12::D3D12Format RenderingDeviceDriverD3D12::RD_TO_
...
+Error RenderingDeviceDriverD3D12::CPUDescriptorsHeapPools::allocate(ID3D12Device *p_device, const D3D12_DESCRIPTOR_HEAP_DESC &p_desc, CPUDescriptorsHeapHandle &result) {
+	ERR_FAIL_COND_V(p_desc.NodeMask != 0 || p_desc.Flags != 0, ERR_INVALID_PARAMETER);
+
+	// bin number of descriptors to the next power of two
+	uint32_t num_rounded_pow2 = to_next_pow2(p_desc.NumDescriptors);
+	uint32_t hash_table_key = num_rounded_pow2 * D3D12_DESCRIPTOR_HEAP_TYPE_NUM_TYPES;
+	hash_table_key += p_desc.Type;
+
+	// is locking needed here ?
+	MutexLock lock(mutex);
```
Comment (DarioSamo) [inline drivers/d3d12/rendering_device_driver_d3d12.cpp:414]: Presumably it's not, but only because RenderingDevice itself declares uniform set creation as a thread safe method, something that may very well go away in the future. I'd keep it.

**Comment by DarioSamo** [comment]
It took me a while but I do get the scheme the proposed allocator goes for. That said, it seems like it leads to a lot of potential fragmentation and wasted descriptor space if the numbers don't happen to line up well to powers of two.

I don't think we create uniform sets often enough to warrant an allocator that optimizes so much for speed so I think we should go with a solution that prioritizes packing descriptors together more, especially if the amount of total descriptor heaps we're allowed is limited.

**Comment by lrahmann** [comment]
@DarioSamo 
Alternative to that would be to go down the SDL route and simply only hand out single ones. 

I can also look into implementing a variable size allocation manager there but only if there is a realistic chance of this getting merged afterwards.  As this creates a way more complex data structure, and we don't really care about the extra memory used here but it makes the code a bit less complicated than implementing a manger.  (from my measurements for our game the additional memory needs are negligible).

I also rechecked the minimal example from #102463 using the current master, in fact is still printing an error message for me, but only if I pipe stdout somewhere else.

**Comment by DarioSamo** [comment]
>  As this creates a way more complex data structure, and we don't really care about the extra memory used here

My concern isn't really the memory used up by it, just that we're dealing with an unknown amount of limited descriptors handled by the driver and that users will keep finding ways to run into that limit, so we may have to go back to this at some point if we fail to optimize for the problem properly, the problem being that the amount of descriptors, either total or heaps, seems to be limited.

> but only if there is a realistic chance of this getting merged afterwards

While I can't guarantee that, I'd say there's a high chance considering it fixes a critical runtime error.

File: drivers/d3d12/rendering_device_driver_d3d12.cpp [hunk 2]
```diff
@@ -319,56 +319,278 @@ const RenderingDeviceDriverD3D12::D3D12Format RenderingDeviceDriverD3D12::RD_TO_
...
+	OffsetTableType::Iterator block = free_blocks_by_offset.end();
+
+	if (smallest_free_block == free_blocks_by_size.end()) {
+		D3D12_DESCRIPTOR_HEAP_DESC descr_copy = p_desc;
+
+		// allow for more than 1024 descriptors, we could also do a exponential growth here to further reduce
+		descr_copy.NumDescriptors = MAX(p_desc.NumDescriptors, 1024u);
+
+		ID3D12DescriptorHeap *heap;
+		HRESULT res = p_device->CreateDescriptorHeap(&descr_copy, IID_PPV_ARGS(&heap));
```
[the remark this answers is not in the document]
Comment (lrahmann) [reply drivers/d3d12/rendering_device_driver_d3d12.cpp:363]: As with my comment below and above, this crash happens on the master branch aswell. 
The heap is not growable, DescriptorHeaps can not be resized, I just allocate a new one instead.

**Comment by DarioSamo** [comment]
As far as I can tell, under the current implementation, it seems like it's just unable to allocate more than 1024 descriptors per type or whatever size might be bigger if an allocation reached it first that was bigger than that.

Once that's done, it has no way to grow it, so it makes sense you reach the limit pretty quickly.

**Comment by lrahmann** [comment]
@DarioSamo 
see my comment, I can allocate new blocks. Its just done in chunks of 1024.
I tested this PR our game and against the minimal example from the issue before. It allocates a lot more than 1024 handles.

I just checked again the error being spammed to the console is 
ERROR: Can't create buffer of size: 768, error 0x887a0005.
   at: (drivers\d3d12\rendering_device_driver_d3d12.cpp:844)
the crash happens afterwards. 
This happens on ***master*** and on this PR.  
Error 0x887a0005  is dxgi_error_device_removed which to seems like something else messed up with the rendering pipeline before.

**Comment by DarioSamo** [comment]
Yeah my bad, I understood it now. It threw me off a bit there's no mechanism for storing and freeing the heaps afterwards so I was under the impression there was only one of them.

**Comment by lrahmann** [comment]
Okay my bad, the crash on master was related to a version mismatch in the agility sdk. 
Now both editors run fine.

**Comment by lrahmann** [comment]
will fix the issue with the CI asap. 
there are a few open questions from my side:
- Is crashing inside the functions a good way to fail on error messages
- When trying to clean up the data structure, it seems like all the heaps are destroyed when the ID3D12Device gets destroyed.  At least calling ->Release() on those results in an exception, when inside the destructor. 
- Do we want to deallocate DescriptorHeaps no longer in use ?

**Comment by DarioSamo** [comment]
> Is crashing inside the functions a good way to fail on error messages

The preferred way is to use the error macros (ERR_FAIL, ERR_FAIL_COND, etc).

>     * When trying to clean up the data structure, it seems like all the heaps are destroyed when the ID3D12Device gets destroyed.  At least calling ->Release() on those results in an exception, when inside the destructor.

The application _should_ be properly releasing all uniform sets so this doesn't happen, see next point.

> Do we want to deallocate DescriptorHeaps no longer in use ?

Yes, Godot actively uses manual resource management. You'll get an explicit free for every uniform set. When uniform sets are deleted, they should deallocate their respective chunk from the descriptor heap pool. When the pool is free, we can choose to also delete the heap if it no longer has any allocations.

The pools should be freed by the driver when shutting down and we can issue a warning if allocations are still present in the pool despite reaching the shutdown time.

File: drivers/d3d12/rendering_device_driver_d3d12.cpp [hunk 3]
```diff
@@ -319,56 +319,275 @@ const RenderingDeviceDriverD3D12::D3D12Format RenderingDeviceDriverD3D12::RD_TO_
...
+Error RenderingDeviceDriverD3D12::CPUDescriptorsHeapPools::allocate(ID3D12Device *p_device, const D3D12_DESCRIPTOR_HEAP_DESC &p_desc, CPUDescriptorsHeapHandle &result) {
+	ERR_FAIL_COND_V(p_desc.NodeMask != 0 || p_desc.Flags != 0 || p_desc.Type >= D3D12_DESCRIPTOR_HEAP_TYPE_NUM_TYPES, ERR_INVALID_PARAMETER);
+
+	CPUDescriptorsHeapPool &pool = pools[p_desc.Type];
+	return pool.allocate(p_device, p_desc, result);
+}
+
+void RenderingDeviceDriverD3D12::CPUDescriptorsHeapPool::verify() {
+#ifdef DEBUG_ENABLED
+	uint32_t lastSize = std::numeric_limits<uint32_t>::max();
```
Comment (AThousandShips) [inline drivers/d3d12/rendering_device_driver_d3d12.cpp]:
```suggestion
	uint32_t last_size = std::numeric_limits<uint32_t>::max();
```
Please use `snake_case`

**Comment by lrahmann** [comment]
> Yes, Godot actively uses manual resource management. You'll get an explicit free for every uniform set. When uniform sets are deleted, they should deallocate their respective chunk from the descriptor heap pool. When the pool is free, we can choose to also delete the heap if it no longer has any allocations.

There are also a few other things using CPU bound descriptor heaps not only uniform sets.
I currently manage all of them in a single pool by using a unified global address space.  
 
> The pools should be freed by the driver when shutting down and we can issue a warning (there's another macro for this) if allocations are still present in the pool despite reaching the shutdown time.

This already happens, the only thing left to clean up are the D3D12DescriptorHeap* objects. As I currently do not free unused DescriptorHeaps like before. This can simply be added.

Anyway give it a review in its current state, and I'll check back next week. 
Thank you for your effort.

**Comment by DarioSamo** [comment]
I gave it another look and I'm a bit confused by the usage of the concept of a global offset. I figured it'd be more straightforward to just store the block indices along with a vector of the currently allocated blocks and reference them directly that way instead of needing to access the map and do a search for the closest offset.

It's not exactly a performance concern, just a bit of a barrier to understanding the code and how it lays out the descriptors across the allocated blocks, because the "global offsets" are also a bit arbitrarily placed and all the blocks seem to share the same map for the free blocks according to this.

Apart from that, it seems there's work pending to clean up the comments and implement proper error handling, as there's a lot of crash conditions remaining, which are not usually how we handle errors. If you wish to catch errors with the implementation that should never happen at runtime if the code is correct, `DEV_ASSERT` is preferred. Under other circumstances, it should use the error macros and propagate it accordingly.

**Comment by lrahmann** [comment]
Hey Dario,

thanks for taking time to check, I have little availability  so excuse the late reply.

> I gave it another look and I'm a bit confused by the usage of the concept of a global offset. I figured it'd be more straightforward to just store the block indices along with a vector of the currently allocated blocks and reference them directly that way instead of needing to access the map and do a search for the closest offset. 

Not sure what you mean, you would still need to search for the closest offset because blocks can be broken down, so the code would look almost the same there would just be a set of pools per type instead of a single one.  This is what DilligentEngine is doing in documentation you pointed me at. See https://diligentgraphics.com/diligent-engine/architecture/d3d12/managing-descriptor-heaps/#CPU-Descriptor-Heap
For clarity I can also to a page table like approach where e.g. the lower 10 bits will always be within the same block. 
But this would mean that we need a maximum allocation size. 

> 
> It's not exactly a performance concern, just a bit of a barrier to understanding the code and how it lays out the descriptors across the allocated blocks, because the "global offsets" are also a bit arbitrarily placed and all the blocks seem to share the same map for the free blocks according to this.
> 
It's actually slightly more performant that way because we can skip the linear search trough all allocations to see which one has free blocks. But that should have no impact because I don't expect there to be more than a few of these.

> Apart from that, it seems there's work pending to clean up the comments and implement proper error handling, as there's a lot of crash conditions remaining, which are not usually how we handle errors. If you wish to catch errors with the implementation that should never happen at runtime if the code is correct, `DEV_ASSERT` is preferred. Under other circumstances, it should use the error macros and propagate it accordingly.

Yeah that was what my question before was referring to, if there are any guidelines on how to handle error cases. Almost all of the error cases I have mean that the data structure was likely corrupted and can't be recovered. These could be under a DEV_ASSERT. Open question is what the expected behaviour of a failed allocation should be, as the current one in master will lead to heap corruption later on.

**Comment by lrahmann** [comment]
Hey @DarioSamo ,

is this fix still intended to be merged? It has been running on our export template for quite a while now.

**Comment by DarioSamo** [comment]
> Hey @DarioSamo ,
> 
> is this fix still intended to be merged? It has been running on our export template for quite a while now.

We definitely should have the fix, but the PR itself definitely needs another pass to clean up the commented code, adjust the code to the style and remove the usage of crash conditions. It's not how we traditionally handle errors.

- Use DEV_ASSERT to catch errors that could happen from implementation errors and you want to be sure to catch pre-conditions or situations that should never happen if the code is implemented correctly.
- Use the error macros to propagate and handle failures that could happen at runtime. We don't really use crashes for those scenarios.

**Comment by DarioSamo** [comment]
I'm in need of this PR as well. Do you mind if I take it over and finish polishing the points I brought up?

**Comment by lrahmann** [comment]
@DarioSamo 
I don't mind, I can probably finish this off end of this week/ next week but not sure if I'll manage to fix all the issues you had. Sorry for the delay.
Lukas

**Comment by DarioSamo** [comment]
> @DarioSamo I don't mind, I can probably finish this off end of this week/ next week but not sure if I'll manage to fix all the issues you had. Sorry for the delay. Lukas

No worries, I'll take a look at it tomorrow and push the changes I wanted directly.

**Comment by DarioSamo** [comment]
I rebased and pushed an extra commit on top to indicate the changes I wanted to add.

I'll do a functionality review next to make sure there's no implementation errors or if we can simplify it a bit. If you're okay with the changes, I'll just rebase and squash into a single commit.

**Review by DarioSamo — APPROVED** [review]
I believe the PR should be in a good spot now.

The PR is pretty essential to using bigger projects with D3D12, so its merging shouldn't be too delayed, but it is not critical if we deem it too big of a change for 4.5.0. If it can't make it on this milestone, it should be considered for 4.5.1.

**Comment by DarioSamo** [comment]
I'll wait for OP to confirm whether the changes are fine and squash it.

**Comment by lrahmann** [comment]
Seems good, thanks for your help. You can squash if you like.

**Comment by DarioSamo** [comment]
Should be squashed now.

**Review by AThousandShips — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉

**Comment by Repiteo** [comment]
Cherry-picked to 4.5

File: drivers/d3d12/rendering_device_driver_d3d12.cpp [hunk 4]
```diff
@@ -337,52 +343,253 @@ const RenderingDeviceDriverD3D12::D3D12Format RenderingDeviceDriverD3D12::RD_TO_
...
+		// Connects to the previous block.
+		remove_from_size_map(previous->value);
+		previous->value.size += p_result.count;
+		new_block = previous;
+	} else if (next != free_blocks_by_offset.end()) {
+		// Connects to the next block.
+		remove_from_size_map(next->value);
+		free_blocks_by_offset.erase(next->value.global_offset);
+
+		next->value.global_offset -= p_result.count;
```
Comment (tomspilman) [inline drivers/d3d12/rendering_device_driver_d3d12.cpp:494]: Note for anyone cherry picking this commit to fix your game.  This block is broken.

It erases the node in like 492, then continues to use it below... which causes bad global_offset values being inserted into the free_blocks_by_offset.  My fix was:

```
		// Connects to the next block.
		auto value = next->value;
		remove_from_size_map(value);
		free_blocks_by_offset.erase(value.global_offset);

		value.global_offset -= p_result.count;
		value.size += p_result.count;

		DEV_ASSERT(!free_blocks_by_offset.has(value.global_offset));
		new_block = free_blocks_by_offset.insert(value.global_offset, value);
```

Comment (clayjohn) [reply drivers/d3d12/rendering_device_driver_d3d12.cpp:494]: For future reference, this same issue was fixed by https://github.com/godotengine/godot/pull/113000

Comment (tomspilman) [reply drivers/d3d12/rendering_device_driver_d3d12.cpp:494]: Good to know.  I was looking at the code in the 4.5 branch and saw it wasn't fix there (and the code removed in 4.6) and thought it never was.

https://github.com/godotengine/godot/blob/4.5/drivers/d3d12/rendering_device_driver_d3d12.cpp#L491
