### PR TITLE
Use the original canvas to calculate light positioning

### LINKED ISSUE #63101: Wrong PointLight2D position on parallax layers when camera is active
### Godot version

v4.0.alpha12.official [2c11e6d9e]

### System information

macOS, Linux and Windows 10

### Issue description

The PointLight2D position on parallax layers is off when a camera is active.

In my example, a flashlight is attached to the player.

When camera is disabled the light illuminate the parallax layer at the right position:
Capture d’écran 2022-07-17 à 09 48 33

When camera is enabled the light position is off:
Capture d’écran 2022-07-17 à 09 48 49

Video of the minimal reproduction project:

https://user-images.githubusercontent.com/1422403/179389256-7b54426c-4857-4525-87da-0ed712e618e9.mov

### Steps to reproduce

How to use the minimal reproduction project:

- 'arrows' to move player
- 'enter' to toggle on/off the camera

### Minimal reproduction project

[parallax-light2d-camera-bug.zip](https://github.com/godotengine/godot/files/9127203/parallax-light2d-camera-bug.zip)

### PR DESCRIPTION
**Pull request by NewDefectus**
#63101 is caused due to the ParallaxBackground's canvas layer transform being used to position lighting, rather than that of the original canvas layer the light is from. Because the ParallaxBackground transform is fixed in place without regard to the camera (unless `follow_viewport_enabled` is on), this causes the light's position on its canvas layer to be misaligned.

This commit fixes this for the general case (including other canvas layers such as UI) by fixing the canvas layer whose transform is used to calculate the light's position to be the one the light is in. This way the light's appearance will be consistent across all canvas layers.

*Bugsquad edit:* Fixes #63101

### CODE REVIEW

**Comment by YuriSizov** [comment]
Should fix this for 4.0. Reviews are welcome.

File: servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp [hunk 1]
```diff
@@ -1252,13 +1252,12 @@ void RendererCanvasRenderRD::canvas_render_items(RID p_to_render_target, Item *p
...
 				ERR_CONTINUE(!clight);
 			}
-			Transform2D to_light_xform = (p_canvas_transform * l->light_shader_xform).affine_inverse();
 
 			Vector2 canvas_light_pos = p_canvas_transform.xform(l->xform.get_origin()); //convert light position to canvas coordinates, as all computation is done in canvas coords to avoid precision loss
 			state.light_uniforms[index].position[0] = canvas_light_pos.x;
 			state.light_uniforms[index].position[1] = canvas_light_pos.y;
 
-			_update_transform_2d_to_mat2x4(to_light_xform, state.light_uniforms[index].matrix);
+			_update_transform_2d_to_mat2x4(l->light_shader_xform.affine_inverse(), state.light_uniforms[index].matrix);
```
Comment (akien-mga) [inline servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:1260]: There seems to be the same code in the OpenGL renderer in `drivers/gles3/rasterizer_canvas_gles3.cpp`, so I assume this needs to be changed too.

Comment (NewDefectus) [reply servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:1260]: Yup, thanks for the heads-up. Compatibility mode works as well now too

**Comment by akien-mga** [comment]
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

**Review by clayjohn — APPROVED** [review]
Looks good!

**Comment by NewDefectus** [comment]
Oh, I think godotengine/3d-nodes got requested for review by mistake. I accidentally added an unrelated commit in the first force-push and fixed it only after the request was made.

**Comment by akien-mga** [comment]
Thanks!
