### PR TITLE
[macOS export] Set correct external file attributes, and creation time.

### LINKED ISSUE #39931: 3.2.2 Linux headless version exports invalid Mac app
**Godot version:**

3.2.2 Linux Headless

**OS/device including version:**

Ubuntu 18.04 for building, Mac OS Catalina (10.15.5) for running the app

**Issue description:**

When exporting a Mac build with the Linux headless version of Godot 3.2.2 the result is an `.app` file that cannot be run.

I'm using my [GitHub workflow](https://github.com/firebelley/godot-export) that runs the Linux headless version of Godot to export projects. After updating the workflow to use Godot 3.2.2, this workflow no longer outputs a valid Mac app. When attempting to run the app on my Mac I receive a dialog that states:

Screen Shot 2020-06-29 at 8 18 42 AM

Exporting the Mac app from the Windows version of Godot 3.2.2 produces an app that can be run without issue.

**Steps to reproduce:**
1. Create an empty project
1. Create a minimal Mac export
1. Using the Linux Headless version of 3.2.2, export the Mac app from the command line
1. Attempt to run the app on a Mac, observe the error

**Minimal reproduction project:**

[ActionsTest-master.zip](https://github.com/godotengine/godot/files/4843312/ActionsTest-master.zip) **Please note** that the standard project is the `project` directory. You can also try with the mono project in `project-mono` to see the same result.

If it helps, here is the output app for the **standard** build: https://drive.google.com/file/d/16aYbNx7ovtIKkqvgd_SAZ7ya-7uo6L93/view?usp=sharing

And here is the output app for the **mono** build: https://drive.google.com/file/d/1-HJnBxJ3-n8XokI-NBsz0QA3xBncPL7P/view?usp=sharing

This issue originally stated this was a mono-specific issue. After some more troubleshooting it was found that the issue also applies to the standard version.

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes file creation date (TM month range is 0…11, `OS::get_date()` month range is 1…12).
Fixes file attributes (lost +x flag, and broken files when extracting with macOS `Archive Utility`), do it like info-zip do: 
[unix/unix.c#L382](https://github.com/cysin/info-zip/blob/b4b2ab3c5ae0dce0a7c3884f364ad1fd15854d90/unix/unix.c#L382)

Fixes: #39931

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

File: platform/osx/export/export.cpp [hunk 1]
```diff
@@ -825,14 +825,15 @@ void EditorExportPlatformOSX::_zip_folder_recursive(zipFile &p_zip, const String
...
-			zipfi.tmz_date.tm_mon = date.month;
+			zipfi.tmz_date.tm_mon = date.month - 1; // Note: "tm" month range - 0..11, Godot month range - 1..12, http://www.cplusplus.com/reference/ctime/tm/
 			zipfi.tmz_date.tm_sec = time.sec;
 			zipfi.tmz_date.tm_year = date.year;
 			zipfi.dosDate = 0;
 			// 0100000: regular file type
 			// 0000755: permissions rwxr-xr-x
 			// 0000644: permissions rw-r--r--
-			zipfi.external_fa = (is_executable ? 0100755 : 0100644) << 16L;
+			uint32_t _mode = (is_executable ? 0100755 : 0100644);
```
Comment (follower) [inline platform/osx/export/export.cpp:835]: A comment along the lines of "Bit-wise operators on signed integers are undefined and probably made the result compiler specific." from https://github.com/godotengine/godot/issues/39931#issuecomment-651611035 seems like it would be valuable here as an explanation for why this is implemented in this manner.

**Comment by follower** [comment]
Re: "(lost +x flag, and broken files when extracting with macOS Archive Utility)"

AFAICT the latest issue wasn't specific to Archive Utility extraction?

Also, given that currently 3.2.2 export to Mac `.zip` is broken on *all* platforms due to this issue, does this fix warrant a "hot fix" or similar release for 3.2.2?

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.
