### PR TITLE
LSP: Fix file URI handling + warn about workspace project mismatch

### LINKED ISSUE #103565: Errors & malformed paths opening scripts in external editor (VSCode) on v4.4
### Tested versions

Started after upgrading from 4.3 to v4.4.stable.official [4c311cbee]

### System information

M1 MacBook Pro - macOS Sequoia 15.3.1

### Issue description

After upgrading my project to v4.4, going through the UID upgrader and all that, Visual Studio Code now throws the following error on **every** class that I have defined:

Image

I haven't found a single class that doesn't report this error, except those defined as `class MyClassName` - that means, stand alone classes which don't extend from `RefCounted` or anything like that.

---

On the Godot side, I see the following in the console:

```
  ERROR: Attempt to open script 'file:res:/res:/res:/Usersres:/pablores:/Projectsres:/Prototypesres:/Particle_Cityres:/SimUnitsres:/SimUnit.gd' resulted in error 'File not found'.
  ERROR: Failed loading resource: file:res:/res:/res:/Usersres:/pablores:/Projectsres:/Prototypesres:/Particle_Cityres:/SimUnitsres:/SimUnit.gd. Make sure resources have been imported by opening the project in the editor at least once.
```

Looks like malformed paths: `file:res:/res:/res:/...`

Saving still works just fine - Godot detects the changes and all - but it doesn't feel like I can trust errors anymore to continue coding.

Thoughts? Thank you!

### Steps to reproduce

Occurred upgrading a project from v4.3 to v4.4

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #105000: Godot's LSP does not return correct path for `uid://` resources for `textDocument/documentLink` command.
### Tested versions

Not a problem before Godot 4.4

[https://godotengine.org/article/uid-changes-coming-to-godot-4-4/](https://godotengine.org/article/uid-changes-coming-to-godot-4-4/)

### System information

Windows 11 - Godot 4.4.1 Stable

### Issue description

This is linked to the following issue on godot-vscode-plugin:
[https://github.com/godotengine/godot-vscode-plugin/issues/840](https://github.com/godotengine/godot-vscode-plugin/issues/840)

Godot's LSP does not return the correct `target` if a resource is referenced using `uid://` scheme, as can be seen below:

Image

This causes `uid://` references to break when using VSCode with `godot-vscode-plugin` which i've currently worked around by discarding `uid://` references coming from the LSP.
Image

A potential fix is by overriding `GDScriptWorkplace::get_file_uri` `p_path` with the `res://` path if `p_path` starts with `uid://`, as can be seen in this diff:

(applied to commit [1f56d96cf2c768c3844c68ccb504dfeee841ae15](https://github.com/godotengine/godot/commit/1f56d96cf2c768c3844c68ccb504dfeee841ae15))

```diff
diff --git a/modules/gdscript/language_server/gdscript_workspace.cpp b/modules/gdscript/language_server/gdscript_workspace.cpp
index b2e52b7425..c3f99cc42d 100644
--- a/modules/gdscript/language_server/gdscript_workspace.cpp
+++ b/modules/gdscript/language_server/gdscript_workspace.cpp
@@ -567,6 +567,9 @@ String GDScriptWorkspace::get_file_path(const String &p_uri) const {
 
 String GDScriptWorkspace::get_file_uri(const String &p_path) const {
 	String uri = p_path;
+	if (p_path.begins_with("uid://")) {
+		uri = ResourceUID::uid_to_path(p_path);
+	}
 	uri = uri.replace("res://", root_uri + "/");
 	return uri;
 }
```

Image

### Steps to reproduce

1. Use godot with VSCode for editing scripts, using [godot-vscode-plugin](https://github.com/godotengine/godot-vscode-plugin)
2. `ctrl+click` on `uid://` references
3. `godot-vscode-plugin` fails to resolve the reference due to the LSP not returning a valid target and shows an error

### Minimal reproduction project (MRP)

not project dependent, but here you go anyway:
[lsp-repro.zip](https://github.com/user-attachments/files/19597990/lsp-repro.zip)

### PR DESCRIPTION
**Pull request by HolonProduction**
Fixes https://github.com/godotengine/godot/issues/103565
Fixes https://github.com/godotengine/godot/issues/92248
Fixes #105000

Might have an influence on:
https://github.com/godotengine/godot-vscode-plugin/issues/649
https://github.com/godotengine/godot-vscode-plugin/issues/650

This PR does two things:

- Replaces the file URI handling from the language server with an implementation based on rfc3986 and rfc8089. So that the URI is properly read and decoded.

- Do stuff to convert the absolute URI path to a valid res path, taking into account projects in symlinked directories and case insensitive file systems. This should solve a lot of problems with duplicate class name errors when using the language server.

Also adds a warning if the root location of the workspace does not match the project which is open in Godot.

TODO:
- [x] Test on windows (drive letters might need special handling, since the absolute path from the URI might contain a leading slash before the drive letter. We might need to strip it).

> This was only briefly tested on a Windows VM. Further Windows testing might be helpful.

> This PR changes the behavior of exposed methods. I'm working under the assumption that the language server is experimental (not the feature, but the exposed API). See #105016

### CODE REVIEW

**Comment by Nallebeorn** [comment]
Tested this on Windows. I still get the #103565 error about "Hides a global script class" in VS Code, and I see the new warning even when editing the opened project (I launched VS Code from Godot in fact).

`get_file_path` returns a path like `/c:/Users/Name/dev/project-name`, just like you said.

**Comment by HolonProduction** [comment]
Thanks for testing! Sounds a bit like Godot could load such paths, but not make them local to the project. I'll spin up a VM and take a look I guess.

**Comment by HolonProduction** [comment]
The actual hard part wasn't the leading slash, but dealing with the case insensitive file system. I made some adjustments so that paths should now be correctly mapped to the casing with which they are known to Godot. I did some basic testing in a VM but another round of testing by actual windows users would be appreciated.

File: editor/editor_file_system.cpp [hunk 1]
```diff
@@ -1930,9 +1930,16 @@ bool EditorFileSystem::_find_file(const String &p_file, EditorFileSystemDirector
...
+		if (fs_case_sensitive) {
+			if (fs->files[i]->file == file) {
+				cpos = i;
+				break;
+			}
+		} else {
+			if (fs->files[i]->file.to_lower() == file.to_lower()) {
+				cpos = i;
+				break;
+			}
```
Comment (AThousandShips) [inline editor/editor_file_system.cpp:1946]:
```suggestion
		} else if (fs->files[i]->file.to_lower() == file.to_lower()) {
			cpos = i;
			break;
```

**Comment by HolonProduction** [comment]
I'll mark this as ready for review since I'm done on the code side of things, and my limited testing seemed to work.

**Comment by resty-daze** [comment]
This is working in my project under windows and resolved the annoying error using vscode. Thanks for your work

File: modules/gdscript/language_server/gdscript_workspace.cpp [hunk 2]
```diff
@@ -558,17 +558,99 @@ Error GDScriptWorkspace::parse_local_script(const String &p_path) {
...
 }
 
-String GDScriptWorkspace::get_file_path(const String &p_uri) const {
-	String path = p_uri.uri_file_decode();
-	String base_uri = root_uri.uri_file_decode();
-	path = path.replacen(base_uri + "/", "res://");
-	return path;
+String GDScriptWorkspace::get_file_path(const String &p_uri) {
+	int port;
+	String scheme, host, encoded_path, fragment;
```
Comment (AThousandShips) [inline modules/gdscript/language_server/gdscript_workspace.cpp]:
```suggestion
	String scheme;
	String host;
	String encoded_path;
	String fragment;
```

File: modules/gdscript/language_server/gdscript_language_protocol.cpp [hunk 3]
```diff
@@ -171,6 +171,28 @@ void GDScriptLanguageProtocol::_bind_methods() {
 Dictionary GDScriptLanguageProtocol::initialize(const Dictionary &p_params) {
 	LSP::InitializeResult ret;
 
+	{
+		// Warn if the workspace root does not match with the project that is currently open in Godot,
+		// since it might lead to unexpected behavior, like wrong warnings about duplicate class names.
+
+		String root = "";
+		Variant root_uri_var = p_params["rootUri"];
+		Variant root_var = p_params["rootUri"];
```
Comment (akien-mga) [inline modules/gdscript/language_server/gdscript_language_protocol.cpp]: You're getting `rootUri` twice so the logic seems redundant, I assume one is a typo.

File: modules/gdscript/language_server/gdscript_language_protocol.cpp [hunk 4]
```diff
@@ -171,6 +171,28 @@ void GDScriptLanguageProtocol::_bind_methods() {
 Dictionary GDScriptLanguageProtocol::initialize(const Dictionary &p_params) {
 	LSP::InitializeResult ret;
 
+	{
+		// Warn if the workspace root does not match with the project that is currently open in Godot,
+		// since it might lead to unexpected behavior, like wrong warnings about duplicate class names.
+
+		String root = "";
```
Comment (akien-mga) [inline modules/gdscript/language_server/gdscript_language_protocol.cpp]: String is default initialized.
```suggestion
		String root;
```

File: modules/gdscript/language_server/gdscript_language_protocol.cpp (hunk 3 above)
Comment (HolonProduction) [reply modules/gdscript/language_server/gdscript_language_protocol.cpp]: Yeah, should be `rootPath` for the second one :+1:

File: modules/gdscript/language_server/gdscript_workspace.cpp [hunk 5]
```diff
@@ -562,17 +562,99 @@ Error GDScriptWorkspace::parse_local_script(const String &p_path) {
...
+
+	// Don't use the returned error, the result isn't OK for URIs that are not valid web URLs.
+	p_uri.parse_url(scheme, host, port, encoded_path, fragment);
+
+	// TODO: Make the parsing RFC-3986 compliant.
+	if (scheme != "file" && scheme != "file:" && scheme != "file://") {
+		ERR_PRINT("LSP: The language server does only support the file protocol: " + p_uri);
```
Comment (kitbdev) [inline modules/gdscript/language_server/gdscript_workspace.cpp]:
```suggestion
		ERR_PRINT("LSP: The language server only supports the file protocol: " + p_uri);
```

File: modules/gdscript/language_server/gdscript_workspace.cpp [hunk 6]
```diff
@@ -562,17 +562,99 @@ Error GDScriptWorkspace::parse_local_script(const String &p_path) {
...
+		return "";
```
Comment (kitbdev) [inline modules/gdscript/language_server/gdscript_workspace.cpp]:
```suggestion
		return String();
```

Same for the others.

File: modules/gdscript/language_server/gdscript_workspace.cpp [hunk 7]
```diff
@@ -562,17 +562,99 @@ Error GDScriptWorkspace::parse_local_script(const String &p_path) {
...
+
+	// If query or fragment are present, the URI is not a valid file URI as per RFC-8089.
+	// We currently don't handle the query and it will be part of the path. However,
+	// this should not be a problem for a correct file URI.
+	if (fragment != "") {
+		ERR_PRINT("LSP: Received malformed file URI: " + p_uri);
+		return "";
+	}
+
+	String canonical_res = ProjectSettings::get_singleton()->globalize_path("res://");
```
Comment (kitbdev) [inline modules/gdscript/language_server/gdscript_workspace.cpp]: I think this is the same as `ProjectSettings::get_singleton()->get_resource_path()`.

File: modules/gdscript/language_server/gdscript_workspace.cpp [hunk 8]
```diff
@@ -562,17 +562,99 @@ Error GDScriptWorkspace::parse_local_script(const String &p_path) {
...
-	return path;
+String GDScriptWorkspace::get_file_path(const String &p_uri) {
+	int port;
+	String scheme, host, encoded_path, fragment;
+
+	// Don't use the returned error, the result isn't OK for URIs that are not valid web URLs.
+	p_uri.parse_url(scheme, host, port, encoded_path, fragment);
+
+	// TODO: Make the parsing RFC-3986 compliant.
+	if (scheme != "file" && scheme != "file:" && scheme != "file://") {
```
Comment (kitbdev) [inline modules/gdscript/language_server/gdscript_workspace.cpp]: Sometimes Godot prints errors when I'm using VSCode, usually when I ctrl+hover over `preload` or other things.
Apparently the p_uri can be empty, not sure how it should be handled.

image

**Review by kitbdev — COMMENTED** [review]
Tested on Windows, works fine for the most part. I couldn't reproduce 'Hides a global script class' errors, but the others are fixed. This also fixes using certain symbols in filenames.

I don't know much about the EditorFileSystem, but it uses threads itself and EditorHelp seems to use parts of it in a thread, so it is probably fine.

File: modules/gdscript/language_server/gdscript_workspace.cpp (hunk 8 above)
Comment (HolonProduction) [reply modules/gdscript/language_server/gdscript_workspace.cpp]: Should be checked before calling `get_file_path`. I added a check to the one place where a potentially empty uri was passed in (there is no file for builtin members). All other URI's come directly from the client and should be fine.

**Comment by HolonProduction** [comment]
> I couldn't reproduce 'Hides a global script class' errors, but the others are fixed.

I think I was able to reproduce this, by checking the paths which VSCode sends and then opening Godot via CMD at the same path but with a different capitalization of the drive letter.

**Review by akien-mga — APPROVED** [review]

File: modules/gdscript/language_server/gdscript_workspace.cpp [hunk 9]
```diff
@@ -562,17 +562,99 @@ Error GDScriptWorkspace::parse_local_script(const String &p_path) {
...
+		ERR_PRINT("LSP: The language server only supports the file protocol: " + p_uri);
+		return String();
+	}
```
Comment (AThousandShips) [inline modules/gdscript/language_server/gdscript_workspace.cpp]:
```suggestion
	ERR_FAIL_COND_V_MSG(scheme != "file" && scheme != "file:" && scheme != "file://", String(), "LSP: The language server only supports the file protocol: " + p_uri);
```

File: modules/gdscript/language_server/gdscript_workspace.cpp [hunk 10]
```diff
@@ -562,17 +562,99 @@ Error GDScriptWorkspace::parse_local_script(const String &p_path) {
...
+
+	// Treat host like authority for now and ignore the port. It's an edge case for invalid file URI's anyway.
+	if (host != "" && host != "localhost") {
+		ERR_PRINT("LSP: The language server does not support nonlocal files: " + p_uri);
+		return String();
+	}
```
Comment (AThousandShips) [inline modules/gdscript/language_server/gdscript_workspace.cpp]:
```suggestion
	ERR_FAIL_COND_V_MSG(host != "" && host != "localhost", String(), "LSP: The language server does not support nonlocal files: " + p_uri);
```

File: modules/gdscript/language_server/gdscript_workspace.cpp [hunk 11]
```diff
@@ -562,17 +562,99 @@ Error GDScriptWorkspace::parse_local_script(const String &p_path) {
...
+
+	// If query or fragment are present, the URI is not a valid file URI as per RFC-8089.
+	// We currently don't handle the query and it will be part of the path. However,
+	// this should not be a problem for a correct file URI.
+	if (fragment != "") {
+		ERR_PRINT("LSP: Received malformed file URI: " + p_uri);
+		return String();
+	}
```
Comment (AThousandShips) [inline modules/gdscript/language_server/gdscript_workspace.cpp]:
```suggestion
	ERR_FAIL_COND_V_MSG(fragment != "", String(), "LSP: Received malformed file URI: " + p_uri);
```

**Review by AThousandShips — APPROVED** [review]

File: modules/gdscript/language_server/gdscript_workspace.cpp (hunk 10 above)
Comment (KoBeWi) [reply modules/gdscript/language_server/gdscript_workspace.cpp]:
```suggestion
	ERR_FAIL_COND_V_MSG(!host.is_empty() && host != "localhost", String(), "LSP: The language server does not support nonlocal files: " + p_uri);
```

File: modules/gdscript/language_server/gdscript_workspace.cpp (hunk 11 above)
Comment (KoBeWi) [reply modules/gdscript/language_server/gdscript_workspace.cpp]:
```suggestion
	ERR_FAIL_COND_V_MSG(!fragment.is_empty(), String(), "LSP: Received malformed file URI: " + p_uri);
```

File: modules/gdscript/language_server/gdscript_workspace.cpp (hunk 10 above)
Comment (AThousandShips) [reply modules/gdscript/language_server/gdscript_workspace.cpp]: I'd say the original comparison is more clear (also there are some performance concerns or at least was with `is_empty` for `String` making it not be a perfect replacement, and why i didn't suggest it, beyond that it has worse readability)

File: modules/gdscript/language_server/gdscript_workspace.cpp (hunk 11 above)
Comment (AThousandShips) [reply modules/gdscript/language_server/gdscript_workspace.cpp]: Same here

File: modules/gdscript/language_server/godot_lsp.h [hunk 12]
```diff
@@ -405,6 +424,25 @@ static const int Full = 1;
 static const int Incremental = 2;
 }; // namespace TextDocumentSyncKind
 
+namespace MessageType {
```
Comment (KoBeWi) [inline modules/gdscript/language_server/godot_lsp.h:427]: Why it's not an enum?

Comment (HolonProduction) [reply modules/gdscript/language_server/godot_lsp.h:427]: All existing code does it. I think there are two reasons:

- The LSP spec uses namespaces over enums. (Worth noting though that this is only the case for the specification which uses typescript types. A typescript enum cannot have a number associated with the value. In the [meta model](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/metaModel/metaModel.json) (which AFAIK didn't exist when LSP was first implemented in Godot) those are called enums.)
- Also C++ enums can reference the value without the enum name. We don't want `lsp::Error` to be valid. (This could be solved using enum classes AFAIK, but I'm not sure whether they are approved for usage in Godot?)

Anyway, this might be worth a discussion but certainly not one to be had in a bugfix PR

File: editor/editor_file_system.cpp (hunk 1 above)
Comment (HolonProduction) [reply editor/editor_file_system.cpp:1946]: I personally don't think this is an improvement in this context:
```c++
if (fs_case_sensitive) {
	if (fs->files[i]->file == file) {
		cpos = i;
		break;
	}
} else {
	if (fs->files[i]->file.to_lower() == file.to_lower()) {
		cpos = i;
		break;
	}
}
```
The two inner conditions fulfill the same purpose, which IMHO is much easier to read if they are on the same indentation level.

For reference an analogous condition in this style already exists [here](https://github.com/HolonProduction/godot/blob/a1edb9ca3862dc36a084d282ea6de32befb52fdd/editor/editor_file_system.cpp#L1893-L1903).

But yeah, not my decision to make I guess :shrug:

File: modules/gdscript/language_server/gdscript_workspace.cpp (hunk 9 above)
Comment (HolonProduction) [reply modules/gdscript/language_server/gdscript_workspace.cpp]: I will change this, but it feels a bit inconsistent to me, that we don't allow declaring of multiple variables on one line, while enforcing three comparisons + one return value + one error message including string coercion on one line. 
I don't think this does anything for readability, but yeah I'll change it I guess.

File: modules/gdscript/language_server/godot_lsp.h (hunk 12 above)
Comment (KoBeWi) [reply modules/gdscript/language_server/godot_lsp.h:427]: > (This could be solved using enum classes AFAIK, but I'm not sure whether they are approved for usage in Godot?)

They are.

File: modules/gdscript/language_server/gdscript_workspace.cpp (hunk 9 above)
Comment (AThousandShips) [reply modules/gdscript/language_server/gdscript_workspace.cpp]: I think we should use the macros when we can

File: editor/editor_file_system.cpp (hunk 1 above)
Comment (AThousandShips) [reply editor/editor_file_system.cpp:1946]: That's fine, I just think nested if statements are really hard to read and they should, IMO, indicate that that there's some code *outside* the inner statement

Comment (AThousandShips) [reply editor/editor_file_system.cpp:1946]: But these are style *suggestions*, not orders

File: modules/gdscript/language_server/godot_lsp.h (hunk 12 above)
Comment (HolonProduction) [reply modules/gdscript/language_server/godot_lsp.h:427]: Good to know :+1: For now I don't want to have this inconsistent in this file though.

I think the LSP types need a makeover but it's only worth the effort if we change to generating those types from the meta model, or if we get optional/union support in core (or permission to use std for LSP).

Hope you don't mind me marking this as resolved for now.

File: modules/gdscript/language_server/gdscript_workspace.cpp (hunk 9 above)
Comment (HolonProduction) [reply modules/gdscript/language_server/gdscript_workspace.cpp]: Yeah in most cases I agree, I think three conditions is kind-of the limit for me. Anyway it now uses the macros.

If we ever get RFC-3986 compliant URI parsing this should be simplified to one condition anyway.

Comment (AThousandShips) [reply modules/gdscript/language_server/gdscript_workspace.cpp]: In this case the alternative is to do:
```cpp
	if (scheme != "file" && scheme != "file:" && scheme != "file://") {
		ERR_FAIL_V_MSG(String(), "LSP: The language server only supports the file protocol: " + p_uri);
	}
```
But `ERR_PRINT` should not be combined with `return` immediately after

File: editor/editor_file_system.cpp (hunk 1 above)
Comment (HolonProduction) [reply editor/editor_file_system.cpp:1946]: Admittedly I might be treating you a bit like a human linter for the Godot code style :sweat: I'll keep this one as is then. And seriously you are doing a great job with those suggestions and in 99% of cases I'm like "Why didn't I see that". Thanks!

Comment (AThousandShips) [reply editor/editor_file_system.cpp:1946]: Thank you, and no worries I'm sorry for the confusion!

**Comment by Repiteo** [comment]
Thanks!
