### PR TITLE
Fix CollisionObject3D Gizmo not updated after calling `shape_owner_*` functions

### LINKED ISSUE #84540: CollisionObject3D Gizmo not updated after changing collision with shape_owner_* functions in a @tool script
### Godot version

v4.1.2.stable.arch_linux

### System information

Arch Linux

### Issue description

When using `shape_owner_*` functions to add/remove collision shapes on a CollisionObject3D (and classes derived from it) in a tool mode script, the new shape is not visible in the editor until after deselecting & reselecting the node, or after the scene (tree) is reloaded. (Either by closing and reopening it, or by switching scene tabs.)

Most likely because the gizmo that handles showing this shape (CollisionObject3DGizmoPlugin) is not redrawn when the shape owners and their shapes change. The function responsible for drawing the shapes is:
https://github.com/godotengine/godot/blob/4c96e9676b66d0cc9a25022b019b78f4c20ddc60/editor/plugins/gizmos/collision_object_3d_gizmo_plugin.cpp#L60-L86

### Steps to reproduce

1. In a new scene, create a CollisionObject3D derived node (Like StaticBody3D) and attach the following script to it:
```gdscript
@tool
extends CollisionObject3D

var shape_owner:int
var shape
@export var collision:Shape3D:
    get:
        return shape
    set(value):
        shape = value
        if get_shape_owners().size() == 0: shape_owner = create_shape_owner(self)
        shape_owner_clear_shapes(shape_owner)
        if shape: shape_owner_add_shape(shape_owner, shape)
```
2. Set the exported variable in the editor by adding a collision shape.
    - Notice how the visualization of the collision shape has not changed
3. Deselect and reselect the node, or change scene tab between another scene and this scene, or save, close and reopen the scene
    - Notice that the new collision shape is now visible

### Minimal reproduction project

[collisionobject3d-gizmo-test.zip](https://github.com/godotengine/godot/files/13270399/collisionobject3d-gizmo-test.zip)

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes #84540

Two things to disscuss:
1. potential performance problem because of additional calls to `update_gizmo`
2. Is there any other defered gizmo update call be immediate

### CODE REVIEW

File: scene/3d/collision_object_3d.cpp [hunk 1]
```diff
@@ -621,6 +621,8 @@ void CollisionObject3D::shape_owner_add_shape(uint32_t p_owner, const Ref<Shape3
 	total_subshapes++;
 
 	_update_shape_data(p_owner);
+
+	update_gizmos();
```
Comment (KoBeWi) [inline scene/3d/collision_object_3d.cpp:625]:
```suggestion
	_update_shape_data(p_owner);
	update_gizmos();
```

**Review by KoBeWi — APPROVED** [review]
> potential performance problem because of additional calls to update_gizmo

`update_gizmos()` code only runs in editor builds, so it's a non-issue.

File: scene/3d/collision_object_3d.cpp (hunk 1 above)
Comment (akien-mga) [reply scene/3d/collision_object_3d.cpp:625]: Nitpick, but worth changing for consistency with other such "grouped" updates in other classes. CC @jsjtxietian

Comment (jsjtxietian) [reply scene/3d/collision_object_3d.cpp:625]: Yes absolutely, thanks !

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.
