### PR TITLE
Track groups in Animation tab hover highlight

### LINKED ISSUE #112065: Track groups in Animation tab are missing hover highlight
### Tested versions

4.5

### System information

W10

### Issue description

In Animation tab, when grouping is enabled you can click nodes to highlight them in the Scene dock:

https://github.com/user-attachments/assets/2a85bbab-6f0c-4a63-b372-875278f2e2c9

However, despite being clickable, they don't have hover style. It hurts the discoverability of this feature.

### Steps to reproduce

1. Create AnimationPlayer
2. Add new animation and some animation tracks from different nodes
3. Click the nodes like in the video above

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by carterwilson1337**
Fixes: #112065 

This fixes a usability bug in the Animation tab,. The track groups did not have a hover style, despite being clickable.

### CODE REVIEW

**Comment by Giganzo** [comment]
Also made a PR for this (didn't have time to push it), one thing I was thinking about:

Currently you can only select the node by clicking on the name part of the timeline and not the full row. Would probably feel strange if the hover state was showing for the full row.
So what I did was making the hover state only show when mouse was over this area. Either that or make the full row clickable. What would be best?

**Comment by carterwilson1337** [comment]
> Also made a PR for this (didn't have time to push it), one thing I was thinking about:
> 
> Currently you can only select the node by clicking on the name part of the timeline and not the full row. Would probably feel strange if the hover state was showing for the full row. So what I did was making the hover state only show when mouse was over this area. Either that or make the full row clickable. What would be best?

This is a good point, I see what you mean about it feeling strange. IMO, reducing the hover state to only show when over the portion with text is better like you did. I think it's equally valid to make the full row clickable for the sake of discoverability. I'm not sure which would be better.

**Comment by KoBeWi** [comment]
I think reducing hover area is better. The sections are clearly separated, so it makes that only node part is clickable. It's also less visual noise.
Also the hover style needs to be changed. It should be highlight over the selected section, not a general outline.

**Comment by carterwilson1337** [comment]
> I think reducing hover area is better. The sections are clearly separated, so it makes that only node part is clickable. It's also less visual noise. Also the hover style needs to be changed. It should be highlight over the selected section, not a general outline.

I believe I fixed the behavior. I checked different themes as well and they looked good to me.

https://github.com/user-attachments/assets/292936a4-341c-472f-a936-071b399b342c

Thank you @Giganzo and @KoBeWi for the feedback.

**Comment by carterwilson1337** [comment]
Is anything more needed on my end to get this merged? I'm happy to make any necessary fixes, please let me know if I am missing anything. Thank you!!

File: editor/animation/animation_track_editor.cpp [hunk 1]
```diff
@@ -3838,6 +3847,12 @@ void AnimationTrackEditGroup::_notification(int p_what) {
 				draw_line(Point2(px, 0), Point2(px, get_size().height), accent, Math::round(2 * EDSCALE));
 			}
 		} break;
+
+		case NOTIFICATION_MOUSE_EXIT:
+			hovered = false;
+			// When the mouse cursor exits the AnimationTrackEditGroup, we're no longer hovering the group.
+			queue_redraw();
+			break;
```
Comment (TokageItLab) [inline editor/animation/animation_track_editor.cpp]:
```suggestion

		case NOTIFICATION_MOUSE_EXIT: {
			hovered = false;
			// When the mouse cursor exits the AnimationTrackEditGroup, we're no longer hovering the group.
			queue_redraw();
		} break;
```
as Godot c++ style

File: editor/animation/animation_track_editor.cpp [hunk 2]
```diff
@@ -3838,6 +3847,12 @@ void AnimationTrackEditGroup::_notification(int p_what) {
 				draw_line(Point2(px, 0), Point2(px, get_size().height), accent, Math::round(2 * EDSCALE));
 			}
 		} break;
+
+		case NOTIFICATION_MOUSE_EXIT: {
+			hovered = false;
+			// When the mouse cursor exits the AnimationTrackEditGroup, we're no longer hovering the group.
+			queue_redraw();
```
Comment (KoBeWi) [inline editor/animation/animation_track_editor.cpp]: This should be called only if it was hovered.

File: editor/animation/animation_track_editor.cpp [hunk 3]
```diff
@@ -3764,6 +3766,13 @@ void AnimationTrackEditGroup::_notification(int p_what) {
 
 			draw_style_box(stylebox_header, Rect2(Point2(), get_size()));
 
+			if (hovered) {
+				// Draw hover feedback for AnimationTrackEditGroup.
+				//Add a limit to just show hover over portion with text
```
Comment (KoBeWi) [inline editor/animation/animation_track_editor.cpp]:
```suggestion
				// Add a limit to just show hover over portion with text.
```

**Review by KoBeWi — APPROVED** [review]

**Comment by carterwilson1337** [comment]
I squashed all commits and rebased. Thank you again everyone for the feedback. Please let me know if I can do anything else related to this PR. I'm happy to help!

**Review by TokageItLab — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
