### PR TITLE
Fixed block indent inconsistency, issue #3803

### LINKED ISSUE #3803: Code editor block indent
Indenting lines is picky with the first and last selected lines. The **first** lines tab is inserted  where the selection begins. The **last** lines tab is inserted at the beginning, but only if the selection goes past the first character.
I expected the tab characters to be inserted at the beginning of each line touched by the selection.

### PR DESCRIPTION
**Pull request by Paulb23**
Fixed block indent inconsistency, closes #3803. It now works similar to sublime text and intellij.

### CODE REVIEW

**Comment by neikeq** [comment]
Does this PR fixes the mentioned issue? If that's the case, then you can use [keywords for closing issues](https://help.github.com/articles/closing-issues-via-commit-messages/) automatically when the PR gets merged.
This keywords can go in the PR main message (not the title) or in the commit message.

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -1229,6 +1229,58 @@ void TextEdit::backspace_at_cursor() {
...
 }
 
+void TextEdit::indent_selection_right() {
+
+	if (!is_selection_active()) {
+		return;
+	}
+	begin_complex_operation();
+
+		int start_line = get_selection_from_line();
```
Comment (neikeq) [inline scene/gui/text_edit.cpp]: This block is wrongly indented. Is it because of the calls to _begin/end_complex_operation_? If so, I don't know if it fits our code standards (do we even have coding standards? :P ).

**Comment by neikeq** [comment]
Code looks good.

**Comment by Paulb23** [comment]
Cool, didn't realize that, just need to fix a minor issue with the ending column selection being off by one, that was in the original implementation. Then i'll squash the commits and update the message.

File: scene/gui/text_edit.cpp [hunk 2]
```diff
@@ -1229,6 +1229,66 @@ void TextEdit::backspace_at_cursor() {
 
 }
 
+void TextEdit::indent_selection_right() {
+
+	if (!is_selection_active()) {
+		return;
+	}
+	begin_complex_operation();
+		int start_line = get_selection_from_line();
```
Comment (akien-mga) [inline scene/gui/text_edit.cpp]: I agree with @neikeq that's the additional indentation here is a bit strange when compared to the rest of the code.

**Comment by Paulb23** [comment]
Should be all good now.

**Comment by akien-mga** [comment]
Thanks :)
