### PR TITLE
macOS: Fix embedded window scaling issues when hiDPI is disabled

### LINKED ISSUE #116120: UI scaling issues in embedded game mode with MacOS Metal renderer
### Tested versions

Reproducible in 4.5 -> 4.6 (versions supporting macOS game mode embedding)

### System information

Godot v4.6.stable - macOS Tahoe (26.2.0) - Multi-window, 2 monitors - Metal (Forward+) - integrated Apple M1 (Apple7) - Apple M1 (8 threads) - 16.00 GiB memory

### Issue description

There seems to be an error with how the embedded game mode renders when using Metal. Most clearly, there are scaling artifacting issues present when looking at text or other UI elements. These issues go away when you don't use embedded game mode, or when you switch the renderer to Vulkan. Issues not present on Windows or Linux editors.

Please view these images as large as you can to see the issue - text and UI elements show improper scaling and clipping.

**EMBEDDED:**
Image

**NOT EMBEDDED:**
Image

**EMBEDDED:**
Image

**NOT EMBEDDED:**
Image

Changing scaling modes gives no improvement.

### Steps to reproduce

- Create new project
- Stretch mode set to canvas_items
- Aspect set to expand
- hiDPI enabled
- Create Control scene with text or other assets visible
- Run the scene in embedded, and again without embedding to compare

### Minimal reproduction project (MRP)

[MetalScalingBug.zip](https://github.com/user-attachments/files/25199480/MetalScalingBug.zip)

### LINKED ISSUE #116563: "Allow hiDPI" setting ignored in Game View / embedded game window on macOS
### Tested versions

- Reproducible in 4.6.1 stable
- Reproducible in 4.7 dev 1
- Likely reproducible in every version that has the embedded game window

### System information

Godot v4.6.1.stable - macOS Sequoia (15.7.4) - Multi-window, 3 monitors - Metal (Forward+) - integrated Apple M3 Max (Apple9) - Apple M3 Max (16 threads) - 64.00 GiB memory

### Issue description

When using the embedded Game view (either the floating window, or the docked game view tab in the Godot editor), incorrect scaling is applied to the game.

I suspect this is related to this issue: https://github.com/godotengine/godot/issues/116120

But this report is specifically about the fact that the 'Allow hiDPI' setting specifically is totally ignored by the embedded game window / view. It appears to always behave as if the setting is turned on - the rendered view appears half the size it should be, and everything is scaled down accordingly.

Image

### Steps to reproduce

1. Create a default project in any affected Godot version.
2. Enter Project Settings > Display > Window, and turn **OFF** the "Allow hiDPI" setting.
3. Create a new scene with a Control node as the root.
4. Add a GraphEdit node, Label node, or any other Control-derived node with which the scaling issue can be seen.
5. Save the scene, and Run Project using this new scene as the startup scene (or "Run Current Scene").
6. Observe the rendered game is much smaller than it appears in the editor, and any nodes with text / other graphics are drawing at half the expected size.
7. Optionally, turn "Allow hiDPI" back **ON**, and try running the game embedded again - the size and render scale are unchanged.
8. If the "Embed Game on Next Play" setting is disabled, and the project is run again, the 'Allow hiDPI' setting being on or off will affect the size of that un-embedded window.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by stuartcarnie**
Closes #116120
Closes #116563

> [!NOTE]
>
> 🤖 AI Disclosure
>
> I used AI to diagnose and write code to fix the issue. I have verified the fixes.

## Testing

- [x] Verify OpenGL and the modern renderers
- [x] Verify mouse event normalisation using the Control Gallery demo
- [x] Verify mouse pan and motion event normalisation

### CODE REVIEW

File: platform/macos/display_server_macos_embedded.mm [hunk 1]
```diff
@@ -725,6 +744,12 @@
 		}
 #endif
 	}
+	if (state.screen_max_scale != old_scale) {
+		// Recover source pixel size from current bounds using the old display scale.
+		CGSize bounds_size = layer.bounds.size;
+		Size2i source_size((int)(bounds_size.width * old_scale), (int)(bounds_size.height * old_scale));
+		_window_set_size(source_size, DisplayServerEnums::MAIN_WINDOW_ID);
+	}
```
Comment (stuartcarnie) [inline platform/macos/display_server_macos_embedded.mm:754]: This ensures the layer is updated when the scale changes

**Review by bruvzg — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
