### PR TITLE
Fix crash by ensuring selected node is a descendant of the edited scene

### LINKED ISSUE #94844: Subviewport creates duplicate node that persists between scenes. Hard crash when interacting with the editor viewport.
### Tested versions

- Reproducible in v4.3.rc1.mono.official, v4.2.1.stable.mono.official

### System information

Godot v4.3.rc1.mono - Arch Linux 6.10.1.arch1-1 Wed, 24 Jul 2024 22:25:43 +0000 - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT - AMD Ryzen 5 5600G with Radeon Graphics (12 Threads)

### Issue description

I am gonna be honest here. I do not know why this happens.

I'm currently creating a plugin that has a dedicated main screen, which includes a SubViewport.
That SubViewport has a Camera3D & MeshInstance3D as children.
When the plugin loads, a sort of "phantom node" gets created.
A mesh gets rendered on screen, at the same location as the world location of the plugin's MeshInstance3D.
It does not show up in the node tree, and when the viewport gets clicked on, it hard crashes.

Running it through the terminal threw this out when it crashed:
```
Godot Engine v4.3.rc1.mono.official.e343dbbcc - https://godotengine.org
Inconsistent value (1) for DRI_PRIME. Should be < 1 (GPU devices count). Using: 0
OpenGL API 4.6 (Core Profile) Mesa 24.1.4-arch1.2 - Compatibility - Using Device: AMD - AMD Radeon RX 6700 XT (radeonsi, navi22, LLVM 18.1.8, DRM 3.57, 6.10.1-arch1-1)

Editing project: /home/thestickmahn/Godot Projects/imgonnafuckingkms
Godot Engine v4.3.rc1.mono.official.e343dbbcc - https://godotengine.org
Vulkan 1.3.280 - Forward+ - Using Device #0: AMD - AMD Radeon RX 6700 XT

ERROR: Condition "!is_ancestor_of(p_start_node)" is true. Returning: p_start_node
   at: get_deepest_editable_node (scene/main/node.cpp:2525)
ERROR: Condition "!is_ancestor_of(p_node)" is true. Returning: false
   at: is_editable_instance (scene/main/node.cpp:2518)
ERROR: Condition "!is_ancestor_of(p_node)" is true. Returning: false
   at: is_editable_instance (scene/main/node.cpp:2518)
ERROR: Condition "!is_ancestor_of(p_node)" is true. Returning: false
   at: is_editable_instance (scene/main/node.cpp:2518)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.3.rc1.mono.official (e343dbbcc1030f04dc5833f1c19d267a17332ca9)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.6/libcoreclr.so(+0x4a0c15) [0x7c6d68ea0c15] (??:0)
[2] /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.6/libcoreclr.so(+0x4a0255) [0x7c6d68ea0255] (??:0)
[3] /usr/lib/libc.so.6(+0x3d1d0) [0x7c6d9fa371d0] (??:0)
[4] /home/thestickmahn/.local/share/applications/godot/Godot_v4.3-rc1_mono_linux_x86_64/Godot_v4.3-rc1_mono_linux.x86_64() [0x40ca4a] (??:0)
[5] /home/thestickmahn/.local/share/applications/godot/Godot_v4.3-rc1_mono_linux_x86_64/Godot_v4.3-rc1_mono_linux.x86_64() [0x1aad20b] (??:0)
[6] /home/thestickmahn/.local/share/applications/godot/Godot_v4.3-rc1_mono_linux_x86_64/Godot_v4.3-rc1_mono_linux.x86_64() [0x1ad7429] (??:0)
[7] /home/thestickmahn/.local/share/applications/godot/Godot_v4.3-rc1_mono_linux_x86_64/Godot_v4.3-rc1_mono_linux.x86_64() [0x436d5d1] (??:0)
[8] /home/thestickmahn/.local/share/applications/godot/Godot_v4.3-rc1_mono_linux_x86_64/Godot_v4.3-rc1_mono_linux.x86_64() [0x25365dd] (??:0)
[9] /home/thestickmahn/.local/share/applications/godot/Godot_v4.3-rc1_mono_linux_x86_64/Godot_v4.3-rc1_mono_linux.x86_64() [0x23ba825] (??:0)
[10] /home/thestickmahn/.local/share/applications/godot/Godot_v4.3-rc1_mono_linux_x86_64/Godot_v4.3-rc1_mono_linux.x86_64() [0x240ea62] (??:0)
[11] /home/thestickmahn/.local/share/applications/godot/Godot_v4.3-rc1_mono_linux_x86_64/Godot_v4.3-rc1_mono_linux.x86_64() [0x2412076] (??:0)
[12] /home/thestickmahn/.local/share/applications/godot/Godot_v4.3-rc1_mono_linux_x86_64/Godot_v4.3-rc1_mono_linux.x86_64() [0x242a759] (??:0)
[13] /home/thestickmahn/.local/share/applications/godot/Godot_v4.3-rc1_mono_linux_x86_64/Godot_v4.3-rc1_mono_linux.x86_64() [0x4a7277e] (??:0)
[14] /home/thestickmahn/.local/share/applications/godot/Godot_v4.3-rc1_mono_linux_x86_64/Godot_v4.3-rc1_mono_linux.x86_64() [0x4bd16f] (??:0)
[15] /home/thestickmahn/.local/share/applications/godot/Godot_v4.3-rc1_mono_linux_x86_64/Godot_v4.3-rc1_mono_linux.x86_64() [0x40c47c7] (??:0)
[16] /home/thestickmahn/.local/share/applications/godot/Godot_v4.3-rc1_mono_linux_x86_64/Godot_v4.3-rc1_mono_linux.x86_64() [0x40c60ff] (??:0)
[17] /home/thestickmahn/.local/share/applications/godot/Godot_v4.3-rc1_mono_linux_x86_64/Godot_v4.3-rc1_mono_linux.x86_64() [0x4c41e5] (??:0)
[18] /home/thestickmahn/.local/share/applications/godot/Godot_v4.3-rc1_mono_linux_x86_64/Godot_v4.3-rc1_mono_linux.x86_64() [0x41ff23] (??:0)
[19] /usr/lib/libc.so.6(+0x25e08) [0x7c6d9fa1fe08] (??:0)
[20] /usr/lib/libc.so.6(__libc_start_main+0x8c) [0x7c6d9fa1fecc] (??:0)
[21] /home/thestickmahn/.local/share/applications/godot/Godot_v4.3-rc1_mono_linux_x86_64/Godot_v4.3-rc1_mono_linux.x86_64() [0x43e4ca] (??:0)
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

I, for the life of me do not know.

### Minimal reproduction project (MRP)

[Project ZIP: imgonnafuckingkms.zip](https://github.com/user-attachments/files/16401237/imgonnafuckingkms.zip)

I will provide further information as required.

### LINKED ISSUE #95356: Crash In Node3DEditorPlugin Selecting On Viewport
### Tested versions

- Reproducable in 4.3-rc2, rc3, 88f3b5f9d52f740b24fabfb8bc01b8b7026ba279
- Not reproducable in 4.2.2-stable

### System information

Windows 11/64, RTX 3070, Vulkan

### Issue description

Downstream bug report: https://github.com/TokisanGames/Terrain3D/issues/449

Drawing a selection box in the viewport can cause a crash under certain conditions. Does not affect 4.2.2-stable. The script errors are mine and of no consequence. I'm looking for what conditions in my code flushes out the engine bug.

```
Godot Engine v4.3.rc.custom_build.88f3b5f9d (2024-08-09 21:25:56 UTC) - https://godotengine.org
Vulkan 1.3.278 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce RTX 3070 Laptop GPU

SCRIPT ERROR: Invalid call. Nonexistent function 'get_camera' in base 'Nil'.
          at: update_decal (res://addons/terrain_3d/src/ui.gd:269)
SCRIPT ERROR: Invalid call. Nonexistent function 'get_camera' in base 'Nil'.
          at: update_decal (res://addons/terrain_3d/src/ui.gd:269)
SCRIPT ERROR: Invalid call. Nonexistent function 'get_camera' in base 'Nil'.
          at: update_decal (res://addons/terrain_3d/src/ui.gd:269)
ERROR: Condition "!is_ancestor_of(p_start_node)" is true. Returning: p_start_node
   at: Node::get_deepest_editable_node (scene\main\node.cpp:2525)
WARNING: Terrain3D#3596:_notification: NOTIFICATION_CRASH
     at: VariantUtilityFunctions::push_warning (core\variant\variant_utility.cpp:1112)

================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.3.rc.custom_build (88f3b5f9d52f740b24fabfb8bc01b8b7026ba279)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] Node3DEditorViewport::_select_region (C:\GD\godot\editor\plugins\node_3d_editor_plugin.cpp:1085)
[1] Node3DEditorViewport::_sinput (C:\GD\godot\editor\plugins\node_3d_editor_plugin.cpp:1951)
[2] CallableCustomMethodPointer<Node3DEditorViewport,Ref<InputEvent> const &>::call (C:\GD\godot\core\object\callable_m)[3] Callable::callp (C:\GD\godot\core\variant\callable.cpp:58)
[4] Object::emit_signalp (C:\GD\godot\core\object\object.cpp:1190)
[5] Node::emit_signalp (C:\GD\godot\scene\main\node.cpp:3896)
[6] Control::_call_gui_input (C:\GD\godot\scene\gui\control.cpp:1818)
[7] Viewport::_gui_call_input (C:\GD\godot\scene\main\viewport.cpp:1570)
[8] Viewport::_gui_input_event (C:\GD\godot\scene\main\viewport.cpp:1836)
[9] Viewport::push_input (C:\GD\godot\scene\main\viewport.cpp:3259)
[10] Window::_window_input (C:\GD\godot\scene\main\window.cpp:1680)
[11] CallableCustomMethodPointer<Window,Ref<InputEvent> const &>::call (C:\GD\godot\core\object\callable_method_pointer)[12] Callable::callp (C:\GD\godot\core\variant\callable.cpp:58)
[13] Callable::call<Ref<InputEvent> > (C:\GD\godot\core\variant\variant.h:876)
[14] DisplayServerWindows::_dispatch_input_event (C:\GD\godot\platform\windows\display_server_windows.cpp:3557)
[15] Input::_parse_input_event_impl (C:\GD\godot\core\input\input.cpp:775)
[16] Input::flush_buffered_events (C:\GD\godot\core\input\input.cpp:1056)
[17] DisplayServerWindows::process_events (C:\GD\godot\platform\windows\display_server_windows.cpp:3025)
[18] OS_Windows::run (C:\GD\godot\platform\windows\os_windows.cpp:1666)
[19] widechar_main (C:\GD\godot\platform\windows\godot_windows.cpp:181)
[20] _main (C:\GD\godot\platform\windows\godot_windows.cpp:208)
[21] main (C:\GD\godot\platform\windows\godot_windows.cpp:220)
[22] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[23] <couldn't map PC to fn name>
-- END OF BACKTRACE --
================================================================
```

image

The crash is in [node_3d_editor_plugin.cpp](https://github.com/godotengine/godot/blob/88f3b5f9d52f740b24fabfb8bc01b8b7026ba279/editor/plugins/node_3d_editor_plugin.cpp#L1085) in `void Node3DEditorViewport::_select_region()`

* node is null and it isn't checked
* L1070 `sp` as a Node* is not null, but the Object within is null.
* L1058 `instances.size()` is 1, which is accurate in the steps to produce. Only Terrain3D is in the scene. However the selection box is intentionally empty.

In 4.2 this situation doesn't crash but does report the same error:
`  scene\main\node.cpp:2350 - Condition "!is_ancestor_of(p_start_node)" is true. Returning: p_start_node`

The crash was caused by https://github.com/godotengine/godot/pull/92188

### Steps to reproduce

Setup
* Load the MRP
* Restart when prompted
* In Project settings enable Terrain3D
* Restart a second time

Bug
* Create a new scene
* Add a Terrain3D Node
* In our toolbar, click any tool other than the first (region) so the cursor decal shows on the terrain
* Click Escape to deselect Terrain3D
* Click and drag a selection box in the viewport (doesn't matter on sky/terrain). Upon releasing the mouse Godot will crash.

### Minimal reproduction project (MRP)

Includes a stripped down version of terrain3d from [this specific build](https://github.com/TokisanGames/Terrain3D/actions/runs/10237771326/artifacts/1773892928) w/ windows & linux builds

[test-select-crash.zip](https://github.com/user-attachments/files/16569623/test-select-crash.zip)

### PR DESCRIPTION
**Pull request by TokisanGames**
Fixes #95356, 
Caused by regression #92188
*Bugsquad edit:* Fixes #94844

Previously this section of code allowed selecting nodes not descended from the edited scene, ascending beyond Godot's Window, resulting in a crash calling a function on a null.

This PR fixes that by requiring the selected node be a descendent of the edited scene (also a prereq of `ownership`), and fixes or reduces other aspects.

* Checking `is_ancestor_of` fixes both the error message (affecting 4.2.2-stable) and crash (affecting 4.3) identified in #95356
* Skipping on `node != edited_scene && !get_owner` is consistent with 2D https://github.com/godotengine/godot/blob/8e2141eac534f6984bb0bdbcefbd17de27ae0993/editor/plugins/canvas_item_editor_plugin.cpp#L706

### CODE REVIEW

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -1064,21 +1064,23 @@ void Node3DEditorViewport::_select_region() {
...
-
 		found_nodes.insert(sp);
 
 		Node *node = Object::cast_to<Node>(sp);
+
+		// Selection requires node is or is descended from edited scene, and has an owner
 		if (node != edited_scene) {
+			if (!node->get_owner() || !edited_scene->is_ancestor_of(node)) {
+				continue;
+			}
```
Comment (TokisanGames) [inline editor/plugins/node_3d_editor_plugin.cpp:1075]: * Checking `is_ancestor_of` fixes both the error message (affecting 4.2.2-stable) and crash (affecting 4.3) identified in #95356
* Skipping on `node != edited_scene && !get_owner` is consistent with 2D https://github.com/godotengine/godot/blob/8e2141eac534f6984bb0bdbcefbd17de27ae0993/editor/plugins/canvas_item_editor_plugin.cpp#L706

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 2]
```diff
@@ -1064,21 +1064,23 @@ void Node3DEditorViewport::_select_region() {
 		if (found_nodes.has(sp)) {
 			continue;
 		}
-
 		found_nodes.insert(sp);
 
 		Node *node = Object::cast_to<Node>(sp);
+
+		// Selection requires node is or is descended from edited scene, and has an owner
```
Comment (KoBeWi) [inline editor/plugins/node_3d_editor_plugin.cpp:1071]:
```suggestion
		// Selection requires that the node is the edited scene or its descendant, and has an owner.
```

**Review by KoBeWi — APPROVED** [review]

**Comment by TokisanGames** [comment]
Committed and squashed the suggested changes. Ready to go.

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.
