### PR TITLE
Fix nested TileMapLayers highlight rendering in editor

### LINKED ISSUE #110710: nested tilemaplayers are rendering dark in editor
### Tested versions

-reproducible in 4.5, 4.4.1, and 4.3 

### System information

Windows 11

### Issue description

When working on nested TileMapLayers they are rendered progressively darker as I go deeper.

This does not effect the rendering when selecting an unrelated node and is effecting the editor only i.e. it does not effect the game when played 

### Steps to reproduce

Each of these blue squares is on a separate TileMapLayer, the top most is the parent and the bottom most is the most nested child.
 
1. Image
2. Image
3. Image
4. Image
5. Image

### Minimal reproduction project (MRP)

[nested-tilemap-layer-minimal-example.zip](https://github.com/user-attachments/files/22437034/nested-tilemap-layer-minimal-example.zip)

### PR DESCRIPTION
**Pull request by Ir1ana**
Fixes #110710

Replaces the use of set_modulate in the TileMapLayer highlight rendering to set_self_modulate.

The highlight rendering of TileMapLayer currently uses set_modulate to adjust darkness and alpha of non-selected layers.
When TileMapLayers are nested, as shown in the issue, highlighting a child layer darkens the parents using set_modulate, which also affects children, making them darker.

image

image

### CODE REVIEW

File: scene/2d/tile_map_layer.cpp [hunk 1]
```diff
@@ -412,7 +397,18 @@ void TileMapLayer::_rendering_update(bool p_force_cleanup) {
 			}
 		}
 
-		// Updates on rendering changes.
+		Color layer_self_modulate = get_self_modulate();
```
Comment (groud) [inline scene/2d/tile_map_layer.cpp]: Please bring back the code to the place it was. There's no need to move it around and it just adds noise to the git history (the comment there made sense too, you first do some layer-level processing, then per-quadrant ones).

Comment (Ir1ana) [reply scene/2d/tile_map_layer.cpp]: I moved back the section, but I had to keep sharing the layer_modulate variable with the quadrants section. 

From my previous tests, replacing `rs->canvas_item_set_modulate(get_canvas_item(), layer_modulate)` with `rs->canvas_item_set_self_modulate(get_canvas_item(), layer_modulate)` did not work, so I used the code in the quadrants section.

File: scene/2d/tile_map_layer.cpp [hunk 2]
```diff
@@ -208,19 +208,19 @@ void TileMapLayer::_rendering_update(bool p_force_cleanup) {
...
 
 	// ----------- Layer level processing -----------
-	if (!forced_cleanup) {
-		// Modulate the layer.
-		Color layer_modulate = get_modulate();
+	// Modulate the layer.
+	Color layer_modulate = get_self_modulate();
 #ifdef TOOLS_ENABLED
+	if (!forced_cleanup) {
+		dirty.flags[DIRTY_FLAGS_LAYER_SELF_MODULATE] = true;
```
Comment (groud) [inline scene/2d/tile_map_layer.cpp]: This line should be removed. Such flags are used to know if a property has changed in the layer and trigger an update. Here the self_modulate property is just used, not modified.

Comment (Ir1ana) [reply scene/2d/tile_map_layer.cpp]: I removed the flag, but had to copy part of the quadrants render section to make it work.

Comment (groud) [reply scene/2d/tile_map_layer.cpp]: I mean, this is not normal. The quadrant code should stay where it is. Instead what should be done is the following:
- Add a new `DIRTY_FLAGS_LAYER_HIGHLIGHT_MODE` enum value.
- Set `dirty.flags[DIRTY_FLAGS_LAYER_HIGHLIGHT_MODE] = true;` inside `TileMapLayer::set_highlight_mode`, like it is done for other properties.
- Update the line to check if we need to update all quadrants: 
`if (dirty.flags[DIRTY_FLAGS_TILE_SET] || dirty.flags[DIRTY_FLAGS_LAYER_IN_TREE] || _rendering_was_cleaned_up) {` to
`if (dirty.flags[DIRTY_FLAGS_TILE_SET] || dirty.flags[DIRTY_FLAGS_LAYER_IN_TREE] || dirty.flags[DIRTY_FLAGS_LAYER_HIGHLIGHT_MODE] || _rendering_was_cleaned_up) {`

That should do the trick

Comment (Ir1ana) [reply scene/2d/tile_map_layer.cpp]: I understand, it seems way better indeed.

I implemented the flag as requested, but there is still the `layer_modulate` variable shared with the quadrants code.
This is because, like the previous implementation, we want to highlight a layer without modifying the self_modulate field of the node, that is visible in the editor.

Is it a good solution ?

Thank you for your help, time and patience

Comment (groud) [reply scene/2d/tile_map_layer.cpp]: > I implemented the flag as requested, but there is still the layer_modulate variable shared with the quadrants code.

No that's fine, it's the right way to go.

**Comment by groud** [comment]
Alright, looks good to me now! Please [squash the commits together ](https://contributing.godotengine.org/en/latest/organization/pull_requests/creating_pull_requests.html#the-interactive-rebase) and it should be good to go.

**Review by groud — DISMISSED** [review]
Alright, LGTM now. Thanks a lot!

**Comment by kleonc** [comment]
@groud Note that this makes highlighting no longer affect:
- scene tiles,
- custom drawing (like `draw_circle` etc.) done on the TileMapLayer.

For custom drawing it would be enough to apply the highlighting to `TileMapLayer.self_modulate` as well (not just to quadrants' items).
No idea how to approach the scene tiles though.

**Comment by groud** [comment]
> scene tiles,

Ah that's a good point :thinking: . I probably did it that way for this reason. I don't think there's a way to solve that though, not sure if the current behavior is preferable to this new one then. I guess it could be discussed.

> custom drawing (like draw_circle etc.) done on the TileMapLayer.

I am not sure about this one. Self-modulate should impact those. 
But anyway, if that's true, I think this one we can ignore, as using draw commands on a TileMapLayer is a very rare use case anyway.

File: scene/2d/tile_map_layer.cpp [hunk 3]
```diff
@@ -249,7 +248,7 @@ void TileMapLayer::_rendering_update(bool p_force_cleanup) {
 
 	if (!forced_cleanup) {
 		// List all quadrants to update, recreating them if needed.
-		if (dirty.flags[DIRTY_FLAGS_TILE_SET] || dirty.flags[DIRTY_FLAGS_LAYER_IN_TREE] || _rendering_was_cleaned_up) {
+		if (dirty.flags[DIRTY_FLAGS_TILE_SET] || dirty.flags[DIRTY_FLAGS_LAYER_IN_TREE] || dirty.flags[DIRTY_FLAGS_LAYER_HIGHLIGHT_MODE] || _rendering_was_cleaned_up) {
```
Comment (kleonc) [inline scene/2d/tile_map_layer.cpp]: @groud AFAICT this will result in recreating all the quadrants' items on highlight mode change. Shouldn't this flag be checked and items' `self_modulate` updated here instead:
https://github.com/godotengine/godot/blob/149a4b4ca12e2baf700020fc10f00d5b0a5e9f0d/scene/2d/tile_map_layer.cpp#L415-L429
?

Comment (groud) [reply scene/2d/tile_map_layer.cpp]: Oh yeah that would be better, you're right

**Comment by Ir1ana** [comment]
@kleonc @groud I optimized the code according to @kleonc comment and  added support for scene tiles, in a separate commit for easier diff reading.

As you can see, scene tiles highlight work, but there are some z-index issues which were already present before this PR. It can be fixed by setting the z-index in the editor.

image

I also added `canvas_item_set_self_modulate` in an effort to add support for `draw_circle`, but it didn't work. I left it there anyway just in case. AFAIK, highlight on `draw_circle` does not seem to work in 4.5.

Here my failing test on my branch:

image

File: scene/2d/tile_map_layer.cpp [hunk 4]
```diff
@@ -1572,7 +1580,7 @@ void TileMapLayer::_scenes_clear_cell(CellData &r_cell_data) {
 	r_cell_data.scene = "";
 }
 
-void TileMapLayer::_scenes_update_cell(CellData &r_cell_data) {
+void TileMapLayer::_scenes_update_cell(CellData &r_cell_data, RenderingServer &rs) {
```
Comment (groud) [inline scene/2d/tile_map_layer.cpp]: Passing `RenderingServer` as argument here is unecessary. You can just get it via `RenderingServer *rs = RenderingServer::get_singleton();`.
You can do it in the `TOOLS_ENABLED` part below, that should work.

File: scene/2d/tile_map_layer.cpp [hunk 5]
```diff
@@ -1598,6 +1606,12 @@ void TileMapLayer::_scenes_update_cell(CellData &r_cell_data) {
 						xform.set_origin(tile_set->map_to_local(r_cell_data.coords));
 						scene_as_node2d->set_transform(xform * scene_as_node2d->get_transform());
 					}
+#ifdef TOOLS_ENABLED
+					CanvasItem *scene_as_ci = Object::cast_to<CanvasItem>(scene);
+					if (scene_as_ci) {
+						rs.canvas_item_set_modulate(scene_as_ci->get_canvas_item(), _highlight_color(scene_as_ci->get_modulate()));
```
Comment (groud) [inline scene/2d/tile_map_layer.cpp]: I think this requires to be pre-multiplied by the currently-set modulation of the scene. Otherwise any modulation set by the user won't be visible.

**Review by groud — CHANGES_REQUESTED** [review]

File: scene/2d/tile_map_layer.cpp (hunk 5 above)
Comment (Ir1ana) [reply scene/2d/tile_map_layer.cpp]: Excuse me, I don't understand: I am already using the scene's modulate property.
I have tested modifying the modulate property in editor on the scenes with and without highlight, and it seems to work.
<s>I also discovered that way that modulating a scene in a nested TilemapLayer modulates child TilemapLayers, I think this is a desired behavior.</s> 
Nevermind I was modulating tilemapLayers, but I re-tested modulating the CanvasItem of the scene in the tileset and it was visible both with and without highlighting.

Am I missing something ?

File: scene/2d/tile_map_layer.h [hunk 6]
```diff
@@ -450,6 +451,7 @@ class TileMapLayer : public Node2D {
 	bool _rendering_was_cleaned_up = false;
 	void _rendering_update(bool p_force_cleanup);
 	void _rendering_notification(int p_what);
+	Color _highlight_color(Color modulate) const;
```
Comment (AThousandShips) [inline scene/2d/tile_map_layer.h]:
```suggestion
	Color _highlight_color(const Color &p_modulate) const;
```

File: scene/2d/tile_map_layer.cpp (hunk 5 above)
Comment (groud) [reply scene/2d/tile_map_layer.cpp]: Oh my bad, I read the code a bit quickly. The code is fine indeed!

**Comment by groud** [comment]
Alright, looks good to me now and does not have the drawbacks it had. I believe the two commits should be squashed together as they are both are needed to fix the initial issue, but aside from that, looks great.
Thanks again!

**Comment by kleonc** [comment]
> I also added `canvas_item_set_self_modulate` in an effort to add support for `draw_circle`, but it didn't work. I left it there anyway just in case. AFAIK, highlight on `draw_circle` does not seem to work in 4.5.

Custom drawing is affected by highlighting in 4.5 just fine (with the same nesting problem). In the current version of the PR it works as expected as far as I've tested.

[nested-tilemap-layer-minimal-example_v2.zip](https://github.com/user-attachments/files/22493237/nested-tilemap-layer-minimal-example_v2.zip) (`main.tscn`)

- `v4.5.stable.official` [876b29033]

https://github.com/user-attachments/assets/8fe71168-460c-4d2b-9f8b-8cba87787792

- This PR (`v4.6.dev.gh-110768` [89a9be4e8])

https://github.com/user-attachments/assets/09b1d0a4-749f-4b62-bb20-d5bd1912352b

> Here my failing test on my branch:

So not sure why it didn't work for you.


---

> added support for scene tiles, in a separate commit for easier diff reading.
> 
> As you can see, scene tiles highlight work

Applying highlighting to scene tiles by modifying their roots' modulates like it's being done is not really reliable though, as user might modify scene root's modulate anyhow on their own, and such user-made changes won't trigger the internal update like `TileMapLayer::_scenes_update` where the highlighting would be reapplied. Meaning highlighting might be missing (depending on what changes user makes) between:
- (after) user changing the modulate,
- (before) subsequent internal update of the given cell containing scene tile.

Example of the highlighting breaking:
[nested-tilemap-layer-minimal-example_v2.zip](https://github.com/user-attachments/files/22493237/nested-tilemap-layer-minimal-example_v2.zip) (`main_scenes.tscn`)

Scene tile is a plain Sprite2D with such script (changing modulate on a timer):
```gdscript
@tool
extends Sprite2D

const T := 2.0
var t := T
func _process(delta: float) -> void:
	t -= delta
	if t <= 0.0:
		t = T
		modulate = Color(
			randf_range(0.5, 1.0),
			randf_range(0.5, 1.0),
			randf_range(0.5, 1.0),
			1.0
		)
```
In action (`v4.6.dev.gh-110768` [89a9be4e8]):

https://github.com/user-attachments/assets/98abfb4e-51cd-4ed6-89a4-64e5e718b081

Of course it's a made up example specifically to show it breaking, but the user tweening the modulate etc. is rather not an unexpected use case. Maybe it being done in the editor / `@tool` script is less likely, but still. All I'm saying is that if we ship it like that, I expect it to be reported as a bug, sooner or later.

For the highlighting being applied to the scene roots' modulate to be reliable, we would need to somehow intercept calls / hook to `CanvasItem::set_modulate`. E.g. for TileMapLayer we intercept `CanvasItem::set_self_modulate` to handle the change properly by overriding `CanvasItem::set_self_modulate` (AFAIK it was made `virtual` specifically for that). But not sure how we could intercept `CanvasItem::set_modulate` for scene tile instances. Adding a signal like `modulate_changed` would be a trivial solution, but I suspect it would be not desired performance-wise. So, as already mentioned, I don't know how to tackle this properly.

---

https://github.com/godotengine/godot/blob/3d91a48298f30c34747b9ad9a350be0bd66a87d4/scene/2d/tile_map_layer.cpp#L344

Note this should also use the highlighted `layer_modulate` instead of `get_self_modulate()`. AFAICT a quadrant might be (re)created without any of the flags trigerring the render update being dirty (I think e.g. after placing a new tile).

@Ir1ana And of course thanks for all the efforts! 🙂

**Comment by groud** [comment]
@kleonc We need to be realistic on that one, this is an editor-only feature, it's not a huge problem if it fails to update on that specific situation. Like any updates to the scene tiles, it's ok if they are not updated right away. That being said, I wonder if, when saved, a scene triggers the _changed signal in the TileSetSceneCollectionSource, and thus a redraw of the whole TileMapLayer. If not, that could be an improvement to implement eventually.

> Note this should also use the highlighted layer_modulate instead of get_self_modulate(). AFAICT a quadrant might be (re)created without any of the flags trigerring the render update being dirty (I think e.g. after placing a new tile).

Right, this should be updated too.

**Comment by Ir1ana** [comment]
@kleonc Thank you for your time too ! 🙂

I added the layer_modulate to the quadrants section, like you said.

**Comment by kleonc** [comment]
@groud Sure thing, just wanted to be sure we are aware of the quirks with the current solution.

While the solution in this PR isn't perfect, I do think it has better worst case (some missing highlighting for scene tiles) than the current stable version (cumulated highlighting making TileMapLayer either super dark or almost invisible). So yeah, merging as is makes sense to me.

**Review by kleonc — APPROVED** [review]

**Review by groud — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉

**Comment by Ir1ana** [comment]
Thank you ! 😄
