### PR TITLE
core/command_queue_mt.h: Fix crash/hang when buffer fills up

### LINKED ISSUE #42107: Livelock condition in CommandQueueMT when queue is full and read_ptr == write_ptr ~= COMMAND_MEM_SIZE
**Godot version:**
3.2.3rc (fad1feb), with a fair number of uncommitted changes patched in to allow my game to run.

**OS/device including version:**
GLES3
Microsoft Windows [Version 10.0.18362.1016] Windows 10 Pro, 64-bit.
NVidia GeForce RTX 2080 Ti
Driver version: 452.06 DCH

**Issue description:**
Our multithreaded application randomly triggers a "livelock" type condition when doing multiple skeleton updates per frame on 10 skeletons (updating thousands of bone transforms per frame) while lag also exists.

Note that each bone update message is about 104 bytes large, and thousands of these in the queue will quickly approach the hardcoded CommandQueueMT size of 256kB.

I usually need to leave several copies of the application open for multiple hours and then only some will hit the deadlock.

The stack traces are:

    (Main Thread)
    >	godotx.exe!CommandQueueMT::allocate<CommandQueueMT::Command8<VisualServer,void (__cdecl VisualServer::*)(RID,Rect2 const &,RID,Rect2 const &,Color const &,bool,RID,bool),RID,Rect2,RID,Rect2,Color,bool,RID,bool> >() Line 351	C++
     	godotx.exe!CommandQueueMT::allocate_and_lock<CommandQueueMT::Command8<VisualServer,void (__cdecl VisualServer::*)(RID,Rect2 const &,RID,Rect2 const &,Color const &,bool,RID,bool),RID,Rect2,RID,Rect2,Color,bool,RID,bool> >() Line 389	C++
     	godotx.exe!CommandQueueMT::push<VisualServer,void (__cdecl VisualServer::*)(RID,Rect2 const &,RID,Rect2 const &,Color const &,bool,RID,bool),RID,Rect2,RID,Rect2,Color,bool,RID,bool>(VisualServer * p_instance, void(VisualServer::*)(RID, const Rect2 &, RID, const Rect2 &, const Color &, bool, RID, bool) p_method, RID p1, Rect2 p2, RID p3, Rect2 p4, Color p5, bool p6, RID p7, bool p8) Line 446	C++
     	godotx.exe!VisualServerWrapMT::canvas_item_add_texture_rect_region(RID p1, const Rect2 & p2, RID p3, const Rect2 & p4, const Color & p5, bool p6, RID p7, bool p8) Line 522	C++
    ...
    (Visual Server thread)
    >	ntdll.dll!NtWaitForSingleObject()	Unknown
     	KernelBase.dll!WaitForSingleObjectEx()	Unknown
     	godotx.exe!SemaphoreWindows::wait() Line 40	C++
     	godotx.exe!CommandQueueMT::wait_and_flush_one() Line 459	C++
     	godotx.exe!VisualServerWrapMT::thread_loop() Line 74	C++
     	godotx.exe!VisualServerWrapMT::_thread_callback(void * _instance) Line 59	C++

```

  | Name | Value | Type
-- | -- | -- | --
◢ | this | 0x000000000d3601c0 {command_mem=0x000000000d360380 "Á" read_ptr=262080 write_ptr=262080 ...} | CommandQueueMT *
  | ▶ command_mem | 0x000000000d360380 "Á" | unsigned char *
  | read_ptr | 262080 | unsigned int
  | write_ptr | 262080 | unsigned int
  | dealloc_ptr | 0 | unsigned int
  | ▶ sync_sems | 0x000000000d3601d8 {{sem=0x0000000006c57ed0 {...} in_use=false }, {sem=0x0000000006c57690 {...} in_use=...}, ...} | CommandQueueMT::SyncSemaphore[8]
  | ▶ mutex | 0x0000000006c8b9a0 {...} | Mutex *
  | ▶ sync | 0x00000000069caaa0 {...} | Semaphore *
```

It always gets stuck in the same place.

Note that:
COMMAND_MEM_SIZE_KB = 256,
COMMAND_MEM_SIZE = COMMAND_MEM_SIZE_KB * 1024,

Hence, COMMAND_MEM_SIZE = 262144 and:
262144 - 262080 = 64 , which is not enough to add a new message without wrapping around (and invoking the dealloc logic).

**Steps to reproduce:**
I have not come up with a reproduction case for the default Godot Engine, other than "run a version of my networked application with 10-50 clients and without some optimization fixes applied".

However, I have successfully reproduced the issue very quickly in a multithreaded project, by editing `command_queue_mt.h` and modifying the constants, to set `COMMAND_MEM_SIZE` extremely small. I find 256 to be extremely reliable in reproducing the issue.
```diff
diff --git a/core/command_queue_mt.h b/core/command_queue_mt.h
index e5f93bcc36..60473aec45 100644
--- a/core/command_queue_mt.h
+++ b/core/command_queue_mt.h
@@ -311,8 +311,8 @@ class CommandQueueMT {
        /***** BASE *******/

        enum {
-               COMMAND_MEM_SIZE_KB = 256,
-               COMMAND_MEM_SIZE = COMMAND_MEM_SIZE_KB * 1024,
+               //COMMAND_MEM_SIZE_KB = 256,
+               COMMAND_MEM_SIZE = 256, // COMMAND_MEM_SIZE_KB * 1024,
                SYNC_SEMAPHORES = 8
        };
```

I have tested with smaller queue sizes, including 10k, 1k and those also exhibit similar behavior. At 256 bytes, the problem is almost guaranteed to be reproducible.

Note that while custom shaders may fail to compile on queue sizes too small to contain the shader code, however, most messages (including `skeleton_bone_set_transform` which contains a hefty matrix) can fit snugly within 256 bytes.

**Minimal reproduction project:**
Sorry, haven't boiled down the issue to a reproducible project, but at 256 bytes, the issue happens just by clicking around the main menu in my application.
Note: you cannot reproduce this in the Editor due to multithreading being forced off. You must enable multithreading and play the project.

**Remarks**
While an argument can be made for being more optimal /reducing risk of main thread blocking against the visual server when doing large updates every frame... I do *not* think the correct "fix" to this issue is to increase the Command Queue size, or add a paging mechanism similar to the recent proposal for MessageQueue. (An expandable queue *might* solve this, but may incur locking overhead.)

Rather, this issue is a *correctness* issue in which there exists a condition which I have documented above where the command queue will cease to make forward progress. Even with a larger queue size... if the queue should ever fill up for any reason, it would still be possible to hit this condition and hang.

The immediate cause of the issue is in command_queue_mt.h line 400:
```cpp
	bool flush_one(bool p_lock = true) {
		if (p_lock) lock();
	tryagain:

		// tried to read an empty queue
		if (read_ptr == write_ptr) {
			if (p_lock) unlock();
			return false;
		}
```
That comment is showing the false assumption: I have found a case in which `read_ptr == write_ptr` but the queue is full, not empty.

I'm not fully sure yet how this issue can be best addressed. I *think* the issue may be detectable by checking if read_ptr == write_ptr, and then checking if dealloc_ptr is 0.

Another approaches might be to keep an "epoch" counter which increments once every time the queue wraps, and is either equal (haven't wrapped: queue is empty if `read_ptr == write_ptr`) or not-equal (if `read_ptr == write_ptr` then the queue is full, and there is data to flush. (I think 1 bit might be sufficient, since it must never wrap more than once, so it is only "same" or "different"). There could be other variants of this approach that should work similarly. But this does add complexity and extra state variables, and update order considerations:

One thing to note is this code hinges on the behavior always being correct. If there is a case in which flush_one ever incorrectly returns false, the semaphore will be off by one, and you will from that point forward always be one message behind in processing.

In fact, I'm wondering now if hitting a "return false" condition in flush_one should be an error (at least on Windows): if the queue is guarded by a semaphore, WaitForSingleObjectEx should never return prematurely. 
*phew* ok that's all for tonight.

### PR DESCRIPTION
**Pull request by lyuma**
Addresses issue Fixes: #42107

This patch fixes two related issues. One is the livelock race condition in issue #42107 which is likely to occur when all messages added are the same.
The other is a crash which happens when the reader is lapped near the end of the buffer. 

Furthermore, I have created a unit test, at `tests/test_command_queue.h` . Part of this test requires customizing the command queue size in order to make certain issues more reproducible.  The command queue size can be customized through the use of a new Project Setting:
`memory/limits/command_queue/multithreading_queue_size_kb`
 (analogous to customizable MessageQueue limits at `memory/limits/message_queue/max_size_kb` )

### CODE REVIEW

File: core/command_queue_mt.h [hunk 1]
```diff
@@ -375,12 +379,16 @@ class CommandQueueMT {
...
 				// zero means, wrap to beginning
 
 				uint32_t *p = (uint32_t *)&command_mem[write_ptr];
-				*p = 0;
-				write_ptr = 0;
+				*p = 1;
+				write_ptr_and_epoch = 0 | (1 & ~write_ptr_and_epoch); // Invert epoch.
+				// See if we can get the thread to run and clear up some more space while we wait.
+				// This is required if alloc_size * 2 + 4 > COMMAND_MEM_SIZE
+				if (sync)
```
Comment (akien-mga) [inline core/command_queue_mt.h:390]: Use braces around `if` blocks.

File: core/command_queue_mt.h [hunk 2]
```diff
@@ -348,7 +348,11 @@ class CommandQueueMT {
 		// alloc size is size+T+safeguard
 		uint32_t alloc_size = ((sizeof(T) + 8 - 1) & ~(8 - 1)) + 8;
 
+		// Assert that the buffer is big enough to hold at least two messages.
+		//ERR_FAIL_COND(alloc_size * 2 + sizeof(uint32_t) > COMMAND_MEM_SIZE);
```
Comment (akien-mga) [inline core/command_queue_mt.h:352]: Is this meant to be commented out?

File: tests/test_command_queue.h [hunk 3]
```diff
@@ -0,0 +1,480 @@
...
+
+class ThreadWork {
+	Semaphore thread_sem;
+	Semaphore main_sem;
+	Mutex mut;
+	int threading_errors = 0;
+	enum State { MAIN_START,
+		MAIN_DONE,
+		THREAD_START,
+		THREAD_DONE } state;
```
Comment (akien-mga) [inline tests/test_command_queue.h:55]: I'm surprised that `clang-format` accepts this, but it should be:
```suggestion
	enum State {
		MAIN_START,
		MAIN_DONE,
		THREAD_START,
		THREAD_DONE,
	} state;
```

**Comment by hpvb** [comment]
I tested this and it works. I think for 3.2 this is a fine fix, I do however think that this suggests that we need to invent a newer/better data structure for this work for 4.0.
However: This is good work. And we should use it.

**Review by hpvb — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
@lyuma Would you mind preparing a PR that cherry-picks those changes for `3.2`?
I've had a go at doing it myself and the conflicts are not too hard to resolve, but given how sensitive this code is, I prefer if it's done by someone who understands how that code in the two branches might differ.

**Comment by akien-mga** [comment]
Cherry-pick done via #42981.
