### PR TITLE
Fix running on Xvfb server.

### LINKED ISSUE #43444: Godot 4.0 can't be used with xvfb-run on Linux (BadAtom with X_GetProperty)
**Godot version:**
4.0 efc4d217d

**OS/device including version:**
Ubuntu 20.10 in docker

**Issue description:**
When I tried to run Godot in docker with Lavapipe compiled from source, then Godot crash with this message
```
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
X Error of failed request:  BadAtom (invalid Atom parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Atom id in failed request:  0x0
  Serial number of failed request:  53
  Current serial number in output stream:  53
```
I'm not sure if this is Godot or Lavapipe bug, but it will be good to know when it will be fixed, because this will allow to run Godot 4.0 in CI.

**Steps to reproduce:**
```
docker run -it ubuntu:rolling /bin/bash
```

Sadly PPA doesn't provide for now LavaPipe implementation, so lines with adding it may be omitted.
```
export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
apt update
apt upgrade -y
apt install -y software-properties-common xorg xvfb wget unzip -y
add-apt-repository ppa:oibaf/graphics-drivers -y
apt update
apt upgrade -y

wget https://archive.hugo.pro/builds/godot/master/editor/godot-linux-nightly-x86_64.zip
unzip godot-linux-nightly-x86_64.zip
xvfb-run ./godot -q

sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
apt update
apt build-dep -y mesa
apt install -y git meson ninja-build llvm libxcb-shm0-dev 
git clone https://gitlab.freedesktop.org/mesa/mesa.git
cd mesa
meson build/
ninja -C build/ install
cd ..

xvfb-run ./godot -q
```

### PR DESCRIPTION
**Pull request by bruvzg**
Adds WM_STATE and other Atoms validity check.

Fixes #43444

### CODE REVIEW

File: platform/linuxbsd/display_server_x11.cpp [hunk 1]
```diff
@@ -1943,28 +1951,30 @@ String DisplayServerX11::keyboard_get_layout_name(int p_index) const {
...
 
 	int read_bytes = 1024;
 
 	//Keep trying to read the property until there are no
-	//bytes unread.
-	do {
-		if (ret != nullptr) {
-			XFree(ret);
-		}
+	//bytes unread
```
Comment (akien-mga) [inline platform/linuxbsd/display_server_x11.cpp:1963]: I guess the dot was not removed on purpose, but might as well fix the comment style:
```
// Keep trying to read the property until there are no bytes unread.
```

**Review by pouleyKetchoupp — APPROVED** [review]
Looks fine to me!

**Comment by akien-mga** [comment]
Thanks!
