### PR TITLE
[3.x] Fix AudioStreamPlayer not paused on pause mode change

### LINKED ISSUE #58543: AudioStreamPlayer not paused on pause mode change
### Godot version

3.x 0959ff2

### System information

W10

### Issue description

When you have AudioStreamPlayer and change its `pause_mode`, it will not get paused when it should.

Example code:
(`$AudioStreamPlayer` has `PAUSE_MODE_PROCESS`)
```
func _ready() -> void:
	get_tree().paused = true
	$AudioStreamPlayer.play()
	yield(get_tree().create_timer(0.5), "timeout")
	$AudioStreamPlayer.pause_mode = Node.PAUSE_MODE_STOP # <- should stop playing here
```
Does not happen on master.

### Steps to reproduce

1. Add AudioStreamPlayer
2. Add any long enough sound
3. Set `pause_mode` to `Process`
4. Add a script with the above code
5. Run and observe the player not pausing

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by pfertyk**
Fixes #58543.

### CODE REVIEW

**Comment by pfertyk** [comment]
In that case this method would be called on parent, and `propagate_notification` should send it to the child, right?

**Comment by KoBeWi** [comment]
The notification should be sent to all descendant nodes that inherit pause mode. Something similar to this:
https://github.com/godotengine/godot/blob/234eb83dfec6daf3795e53236be7b408083f6a2d/scene/main/node.cpp#L501-L514

**Comment by pfertyk** [comment]
My solution actually reaches all descendant nodes, because `propagate_notification` contains the loop like the one you've shown. However, we will also reach nodes that don't need to be unpaused/paused, which is not ideal :(

I've modified my solution to reach all descendants who have inherit pause mode. I've reused the method `_propagate_pause_owner`. If you prefer, I can add a custom method with the same loop. I'm also considering a new method for the pausing/unpausing logic, to be reused in both places. What do you think?

File: scene/audio/audio_stream_player.cpp [hunk 1]
```diff
@@ -162,7 +162,9 @@ void AudioStreamPlayer::_notification(int p_what) {
 	}
 
 	if (p_what == NOTIFICATION_UNPAUSED) {
-		set_stream_paused(false);
+		if (can_process()) {
+			set_stream_paused(false);
+		}
```
Comment (KoBeWi) [inline scene/audio/audio_stream_player.cpp:167]: I don't think this check should be necessary. If a node receives this notification, it should be able to process.

Comment (pfertyk) [reply scene/audio/audio_stream_player.cpp]: Removed ;)

File: scene/main/node.cpp [hunk 2]
```diff
@@ -462,10 +462,15 @@ void Node::set_pause_mode(PauseMode p_mode) {
...
 	if (!is_inside_tree()) {
 		return; //pointless
 	}
+	// Changing pause_mode directly can result in pausing/unpausing
+	if (prev_can_process != can_process()) {
+		notification(can_process() ? NOTIFICATION_UNPAUSED : NOTIFICATION_PAUSED);
+	}
 	if ((data.pause_mode == PAUSE_MODE_INHERIT) == prev_inherits) {
 		return; ///nothing changed
 	}
```
Comment (KoBeWi) [inline scene/main/node.cpp:476]: This condition prevents the notification from propagating when pause mode changes between `pause` and `process` (because "inherit" state doesn't change). You can use this simple script for testing:
```GDScript
func _notification(what: int) -> void:
	if what == NOTIFICATION_PAUSED:
		prints(name, "paused")
	elif what == NOTIFICATION_UNPAUSED:
		prints(name, "processed")
```
Maybe adding a new function would indeed be better, to avoid changing the behavior too much.

File: scene/audio/audio_stream_player.cpp (hunk 1 above)
Comment (pfertyk) [reply scene/audio/audio_stream_player.cpp]: I've created a new method. Some classes call `can_process()` when reacting to pause/unpause notification, so I'm calling the new method after propagating pause owner, as it can change the result.

File: scene/main/node.cpp (hunk 2 above)
Comment (pfertyk) [reply scene/main/node.cpp]: I've added a new method that propagates the notification to all descendants with inherit mode. Because some classes call `can_process` when handling pause/unpause notification, I'm calling the new method after propagating pause owner, as it can change the result.

File: scene/main/node.cpp [hunk 3]
```diff
@@ -497,6 +499,16 @@ void Node::_propagate_pause_owner(Node *p_owner) {
...
 }
 
+void Node::_propagate_pause_change(bool can_process) {
+	notification(can_process ? NOTIFICATION_UNPAUSED : NOTIFICATION_PAUSED);
```
Comment (KoBeWi) [inline scene/main/node.cpp:503]: You can just send the notification as a parameter, instead of checking this condition for every call.

**Review by KoBeWi — APPROVED** [review]
Looks like it works now. The docs probably need to be updated after these changes.

Also this needs review from @reduz

**Comment by pfertyk** [comment]
I've renamed the method to `_propagate_pause_change_notification` and used `int` as parameter. In all other methods we name the parameters `p_notifications`, so I repeated that name here. Let me know if you need other changes! :)

**Comment by ellenhp** [comment]
I don't think this needs an audio team review, just core. Going to remove that audio label.

**Comment by pfertyk** [comment]
Hi! How is the review process going? Should I add something to this PR? :)

**Comment by akien-mga** [comment]
It's changing the `Node` API which is very core to the whole engine, so this needs a review by @reduz.

**Comment by MJacred** [comment]
Repeating @akien-mga's request: Could you kindly review, @reduz?

In the meantime, @pfertyk, could you rebase this PR on latest of 3.x branch please?

File: scene/main/node.h [hunk 4]
```diff
@@ -208,6 +208,8 @@ class Node : public Object {
 	void _print_stray_nodes();
 	void _propagate_pause_owner(Node *p_owner);
 	void _propagate_groups_dirty();
+	void _propagate_pause_change_notification(int p_notification);
+>>>>>>> 6eff44dc83 (Fix AudioStreamPlayer not paused on pause mode change)
```
Comment (AThousandShips) [inline scene/main/node.h:212]:
```suggestion
```
Leftover conflict marker

**Comment by lawnjelly** [comment]
I *think* this is fine (enough to try in a beta).

The whole `pause_owner` thing seems a bit bug prone (see the implementation for physics interpolation mode for comparison) as it's a pull mechanism versus a push, but it seems to mostly work ok at the moment.

This PR essentially just seems to send out notifications on changes to the pause mode where necessary, and hopefully doesn't send out e.g. 2 pauses or 2 unpauses in a row (which the client code might not be designed for).

I'm not sure whether the existing system deals with the case of pause mode being changed outside the tree, then adding, but I guess that would be a separate bug if not dealt with.

It could probably do with another rebase if we decide to go ahead (a few things have changed in `Node` recently, so just in case).

**Comment by lawnjelly** [comment]
Thanks!
