### PR TITLE
Fix possible deadlock when creating scripts during a background garbage collection

### LINKED ISSUE #87405: C#: Possible deadlock during `GD.Load()` if the garbage collector disposes a script while the loader tries to register one
### Tested versions

v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 Threads)

### Issue description

There's probably no good way to reproduce this reliably, so I don't know how much value this report has, but there appears to be a possible deadlock in how C# scripts are created and disposed.

When loading a scene via `GD.Load<PackedScene>()`, there seems to be a chance that the .NET Garbage Collector running on a separate thread disposes a resource containing a script while the loading code on the main thread tries to register a new script for the new scene. With a bit of unlucky timing, this can lead to the garbage collector waiting for the main thread to release the `_scriptTypeBiMap.ReadWriteLock` lock while the main thread is waiting for the garbage collector to release the `CSharpLanguage::get_singleton()->script_instances_mutex` mutex, which deadlocks the game.

Here's how this might look like:

**Main Thread**
I can't look into the C++ code from here, but it's presumably waiting on the `CSharpLanguage::get_singleton()->script_instances_mutex` mutex at

https://github.com/godotengine/godot/blob/b09f793f564a6c95dc76acc654b390e68441bd01/modules/mono/csharp_script.cpp#L2816-L2825

after having taken the `_scriptTypeBiMap.ReadWriteLock` lock at

https://github.com/godotengine/godot/blob/b09f793f564a6c95dc76acc654b390e68441bd01/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs#L454-L468

```
[External Code] (Unknown Source:0)
GodotSharp.dll!Godot.NativeInterop.NativeFuncs.godotsharp_internal_new_csharp_script(Godot.NativeInterop.godot_ref* r_dest) Line 162 (Godot.NativeInterop.NativeFuncs.generated.cs:162)
GodotSharp.dll!Godot.Bridge.ScriptManagerBridge.CreateScriptBridgeForType(System.Type scriptType, Godot.NativeInterop.godot_ref* outScript) Line 515 (\root\godot\modules\mono\glue\GodotSharp\GodotSharp\Core\Bridge\ScriptManagerBridge.cs:515)
GodotSharp.dll!Godot.Bridge.ScriptManagerBridge.GetOrCreateScriptBridgeForType(System.Type scriptType, Godot.NativeInterop.godot_ref* outScript) Line 466 (\root\godot\modules\mono\glue\GodotSharp\GodotSharp\Core\Bridge\ScriptManagerBridge.cs:466)
GodotSharp.dll!Godot.Bridge.ScriptManagerBridge.GetOrCreateScriptBridgeForPath(Godot.NativeInterop.godot_string* scriptPath, Godot.NativeInterop.godot_ref* outScript) Line 451 (\root\godot\modules\mono\glue\GodotSharp\GodotSharp\Core\Bridge\ScriptManagerBridge.cs:451)
[External Code] (Unknown Source:0)
GodotSharp.dll!Godot.NativeInterop.NativeFuncs.godotsharp_internal_script_load(Godot.NativeInterop.godot_string p_path, Godot.NativeInterop.godot_ref* r_dest) Line 169 (Godot.NativeInterop.NativeFuncs.generated.cs:169)
GodotSharp.dll!Godot.Bridge.ScriptManagerBridge.GetOrLoadOrCreateScriptForType(System.Type scriptType, Godot.NativeInterop.godot_ref* outScript) Line 502 (\root\godot\modules\mono\glue\GodotSharp\GodotSharp\Core\Bridge\ScriptManagerBridge.cs:502)
GodotSharp.dll!Godot.Bridge.ScriptManagerBridge.UpdateScriptClassInfo(System.IntPtr scriptPtr, Godot.NativeInterop.godot_string* outClassName, Godot.NativeInterop.godot_bool* outTool, Godot.NativeInterop.godot_bool* outGlobal, Godot.NativeInterop.godot_bool* outAbstract, Godot.NativeInterop.godot_string* outIconPath, Godot.NativeInterop.godot_array* outMethodsDest, Godot.NativeInterop.godot_dictionary* outRpcFunctionsDest, Godot.NativeInterop.godot_dictionary* outEventSignalsDest, Godot.NativeInterop.godot_ref* outBaseScript) Line 793 (\root\godot\modules\mono\glue\GodotSharp\GodotSharp\Core\Bridge\ScriptManagerBridge.cs:793)
[External Code] (Unknown Source:0)
GodotSharp.dll!Godot.NativeInterop.NativeFuncs.godotsharp_internal_reload_registered_script(System.IntPtr scriptPtr) Line 175 (Godot.NativeInterop.NativeFuncs.generated.cs:175)
GodotSharp.dll!Godot.Bridge.ScriptManagerBridge.CreateScriptBridgeForType(System.Type scriptType, Godot.NativeInterop.godot_ref* outScript) Line 521 (\root\godot\modules\mono\glue\GodotSharp\GodotSharp\Core\Bridge\ScriptManagerBridge.cs:521)
GodotSharp.dll!Godot.Bridge.ScriptManagerBridge.GetOrCreateScriptBridgeForType(System.Type scriptType, Godot.NativeInterop.godot_ref* outScript) Line 466 (\root\godot\modules\mono\glue\GodotSharp\GodotSharp\Core\Bridge\ScriptManagerBridge.cs:466)
GodotSharp.dll!Godot.Bridge.ScriptManagerBridge.GetOrCreateScriptBridgeForPath(Godot.NativeInterop.godot_string* scriptPath, Godot.NativeInterop.godot_ref* outScript) Line 451 (\root\godot\modules\mono\glue\GodotSharp\GodotSharp\Core\Bridge\ScriptManagerBridge.cs:451)
[External Code] (Unknown Source:0)
GodotSharp.dll!Godot.NativeInterop.NativeFuncs.godotsharp_method_bind_ptrcall(System.IntPtr p_method_bind, System.IntPtr p_instance, void** p_args, void* p_ret) Line 353 (Godot.NativeInterop.NativeFuncs.generated.cs:353)
GodotSharp.dll!Godot.NativeCalls.godot_icall_3_981(System.IntPtr method, System.IntPtr ptr, string arg1, string arg2, int arg3) Line 9004 (\root\godot\modules\mono\glue\GodotSharp\GodotSharp\Generated\NativeCalls.cs:9004)
GodotSharp.dll!Godot.ResourceLoader.Load(string path, string typeHint, Godot.ResourceLoader.CacheMode cacheMode) Line 100 (\root\godot\modules\mono\glue\GodotSharp\GodotSharp\Generated\GodotObjects\ResourceLoader.cs:100)
GodotSharp.dll!Godot.ResourceLoader.Load<Godot.PackedScene>(string path, string typeHint, Godot.ResourceLoader.CacheMode cacheMode) Line 27 (\root\godot\modules\mono\glue\GodotSharp\GodotSharp\Core\Extensions\ResourceLoaderExtensions.cs:27)
GodotSharp.dll!Godot.GD.Load<Godot.PackedScene>(string path) Line 129 (\root\godot\modules\mono\glue\GodotSharp\GodotSharp\Core\GD.cs:129)
```

**GC Finalizer Thread**

Waiting on the `_scriptTypeBiMap.ReadWriteLock` at

https://github.com/godotengine/godot/blob/b09f793f564a6c95dc76acc654b390e68441bd01/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs#L524-L538

after presumably having taken the `CSharpLanguage::get_singleton()->script_instances_mutex` mutex at

https://github.com/godotengine/godot/blob/b09f793f564a6c95dc76acc654b390e68441bd01/modules/mono/csharp_script.cpp#L2827-L2836

```
[Waiting on lock owned by Thread 7844] (Unknown Source:0)
[External Code] (Unknown Source:0)
GodotSharp.dll!Godot.Bridge.ScriptManagerBridge.RemoveScriptBridge(System.IntPtr scriptPtr) Line 529 (\root\godot\modules\mono\glue\GodotSharp\GodotSharp\Core\Bridge\ScriptManagerBridge.cs:529)
[External Code] (Unknown Source:0)
GodotSharp.dll!Godot.NativeInterop.NativeFuncs.godotsharp_internal_refcounted_disposed(System.IntPtr ptr, System.IntPtr gcHandleToFree, Godot.NativeInterop.godot_bool isFinalizer) Line 109 (Godot.NativeInterop.NativeFuncs.generated.cs:109)
GodotSharp.dll!Godot.GodotObject.Dispose(bool disposing) Line 117 (\root\godot\modules\mono\glue\GodotSharp\GodotSharp\Core\GodotObject.base.cs:117)
GodotSharp.dll!Godot.GodotObject.~GodotObject() Line 80 (\root\godot\modules\mono\glue\GodotSharp\GodotSharp\Core\GodotObject.base.cs:80)
[External Code] (Unknown Source:0)
```

**Notes**

From the `#ifdef`s it seems that this only affects DEBUG builds. There apparently is a way to [disable background garbage collection](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/background-gc) in .NET, although performance-wise, it may be preferable to find a way to make script creation and disposal thread-safe. At first glance, it may not be necessary for `~CSharpScript()` to hold on to the mutex while calling `ScriptManagerBridge_RemoveScriptBridge()`.

### Steps to reproduce

None, unfortunately. Requires a project that uses C# scripts, certain circumstances that trigger a garbage collection during a `GD.Load()`, and possibly some unlucky timing. Hopefully, the problem can be diagnosed based on the code and the stack traces.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bs-mwoerner**
Fixes #87405.

I'd really appreciate someone else looking over this, but since holding on to the mutex seems like an oversight (compare with virtually the same code in the constructur) and this change is very localized, this might be a suitable quick fix for a problem that's rare but deadlocks the game and is hard to diagnose if it materializes.

### CODE REVIEW

File: modules/mono/csharp_script.cpp [hunk 1]
```diff
@@ -2862,8 +2862,10 @@ CSharpScript::CSharpScript() {
 
 CSharpScript::~CSharpScript() {
 #ifdef DEBUG_ENABLED
-	MutexLock lock(CSharpLanguage::get_singleton()->script_instances_mutex);
-	CSharpLanguage::get_singleton()->script_list.remove(&this->script_list);
+	{
+		MutexLock lock(CSharpLanguage::get_singleton()->script_instances_mutex);
+		CSharpLanguage::get_singleton()->script_list.remove(&this->script_list);
```
Comment (AThousandShips) [inline modules/mono/csharp_script.cpp:2867]:
```suggestion
		CSharpLanguage::get_singleton()->script_list.remove(&script_list);
```

Comment (bs-mwoerner) [reply modules/mono/csharp_script.cpp:2867]: Should we change that in the constructor, too, while we're at it?

Comment (AThousandShips) [reply modules/mono/csharp_script.cpp:2867]: I was going to look at removing several invalid `this` uses in this file but go ahead here 🙂

**Review by RandomShaper — APPROVED** [review]
I think I made the mistake of not enclosing the lock... like four years ago.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.
