### PR TITLE
Make Tree's `set_selected` check if the TreeItem belongs to the tree

### LINKED ISSUE #84862: Tree's `set_selected()` does not check if TreeItem belongs to the Tree
### Godot version

4.2 beta6

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Tree allows selecting TreeItem from another Tree, resulting in a crash:
```
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.2.beta.custom_build (59457685c18e2d729eea50c751c11f049a7186f0)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] CowData<TreeItem::Cell>::_get_size (C:\godot_source\core\templates\cowdata.h:81)
[1] CowData<TreeItem::Cell>::size (C:\godot_source\core\templates\cowdata.h:134)
[2] VectorWriteProxy<TreeItem::Cell>::operator[] (C:\godot_source\core\templates\vector.h:52)
[3] Tree::select_single_item (C:\godot_source\scene\gui\tree.cpp:2574)
[4] Tree::set_selected (C:\godot_source\scene\gui\tree.cpp:4548)
[5] call_with_variant_args_helper<Tree,TreeItem *,int,0,1> (C:\godot_source\core\variant\binder_common.h:308)
[6] call_with_variant_args_dv<Tree,TreeItem *,int> (C:\godot_source\core\variant\binder_common.h:451)
[7] MethodBindT<Tree,TreeItem *,int>::call (C:\godot_source\core\object\method_bind.h:337)
[8] Object::callp (C:\godot_source\core\object\object.cpp:775)
[9] Variant::callp (C:\godot_source\core\variant\variant_call.cpp:1168)
[10] GDScriptFunction::call (C:\godot_source\modules\gdscript\gdscript_vm.cpp:1705)
[11] GDScriptInstance::callp (C:\godot_source\modules\gdscript\gdscript.cpp:1975)
[12] Node::_gdvirtual__ready_call<0> (C:\godot_source\scene\main\node.h:322)
[13] Node::_notification (C:\godot_source\scene\main\node.cpp:188)
[14] Node::_notificationv (C:\godot_source\scene\main\node.h:49)
[15] Object::notification (C:\godot_source\core\object\object.cpp:840)
[16] Node::_propagate_ready (C:\godot_source\scene\main\node.cpp:232)
[17] Node::_propagate_ready (C:\godot_source\scene\main\node.cpp:223)
[18] Node::_propagate_ready (C:\godot_source\scene\main\node.cpp:223)
[19] Node::_set_tree (C:\godot_source\scene\main\node.cpp:2941)
[20] SceneTree::initialize (C:\godot_source\scene\main\scene_tree.cpp:450)
[21] OS_Windows::run (C:\godot_source\platform\windows\os_windows.cpp:1472)
[22] widechar_main (C:\godot_source\platform\windows\godot_windows.cpp:182)
[23] _main (C:\godot_source\platform\windows\godot_windows.cpp:204)
[24] main (C:\godot_source\platform\windows\godot_windows.cpp:218)
[25] WinMain (C:\godot_source\platform\windows\godot_windows.cpp:232)
[26] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[27] <couldn't map PC to fn name>
-- END OF BACKTRACE --
```

### Steps to reproduce

1. Make a scene with 2 Tree nodes
2. Run this code
```GDScript
func _ready() -> void:
	var item = $Tree.create_item()
	$Tree2.set_selected(item, 0)
```

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes #84862

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -4544,6 +4544,8 @@ TreeItem *Tree::get_selected() const {
 void Tree::set_selected(TreeItem *p_item, int p_column) {
 	ERR_FAIL_INDEX(p_column, columns.size());
 	ERR_FAIL_NULL(p_item);
+	ERR_FAIL_COND_MSG(p_item->get_tree() != this, "Treeitem must belong to its own tree to be set as selected.");
```
Comment (jsjtxietian) [inline scene/gui/tree.cpp:4547]: I feel bad about this message, I need to change it.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
