### PR TITLE
Fix using Resource objects as keys in the `tres` format

### LINKED ISSUE #57506: If a resource is used as a key in a dictionary, it will be replaced by null when saving with ResourceSaver to a .tres file
### Godot version

4.0.alpha1

### System information

Windows 10

### Issue description

If you have a custom resource with exported dictionary in it (let's call it ```ResB```), and you use another custom resource as a key on that dictionary (```ResA```), then try to save it in ```.tres``` format, the resource that was used as a dictionary key will not be saved (replaced by a ```null```) and following message will be printed to console:
```E 0:00:00:0707   _ready: Resource was not pre cached for the resource section, bug?
  <Ошибка C++>   Method/function failed. Returning: "null"
  <Исходный код C++>scene/resources/resource_format_text.cpp:1509 @ _write_resource()
  <Трассировка стека>Main.gd:19 @ _ready()
```
I also found that this error only happens when you try to save to a ```.tres``` file. When I tried to save same resource to a binary ```.res``` everything worked as expected with resource being saved. 

Also found that if you use that same resource (```ResA```) for more than as a dictionary key (say, in an exported variable) in the resource being saved (```ResB```) then the bug does not happen either.

### Steps to reproduce

1. Create two custom resources (```ResA``` and ```ResB```)
2. Make sure ```ResB``` has an exported dictionary which uses instances of ```ResA``` as keys.
3. Add at least 1 entry to the dictionary in ```ResB``` that uses an instance of ```ResA``` as a key.
4. Try to save ```ResB``` to a ```.tres``` file using ```ResourceSaver.save("res://data.tres", ResBInstance)```

### Minimal reproduction project

[ResourcesTest.zip](https://github.com/godotengine/godot/files/7977119/ResourcesTest.zip)
Simply run it. ```res://data.tres``` is the buggy output file, ```res://data.res``` is the same resource but in binary format (and also no bug)

### PR DESCRIPTION
**Pull request by Life4gal**
Version of Godot based on: 
    `v4.0.alpha.custom_build [14f8a54a3]`

The changed files are as follows:
    `godot\scene\resources\resource_format_text.cpp`

The problem solved is as follows:
> Fixes #57506 

The minimal case that can be tested is as follows:
    `https://github.com/godotengine/godot/files/7977119/ResourcesTest.zip`

Precautions:
    `ResourceSaver.save`: now the `first` parameter is `resource` and the `second` is `path`, the code in this case is just the opposite.

Roughly the process of solving the problem:

After many tests, the execution process of saving resources is roughly as follows:
```c++
ResourceSaver::save(const Ref<Resource> &p_resource, const String &p_path, BitField<SaverFlags> p_flags);
ResourceSaver::save(const Ref<Resource> &p_resource, const String &p_path, uint32_t p_flags);
ResourceFormatSaverX->save(p_resource, path, p_flag);
ResourceFormatSaverX::save(const Ref<Resource> &p_resource, const String &p_path, uint32_t p_flags);
ResourceFormatSaverXInstance::save(const String &p_path, const Ref<Resource> &p_resource, uint32_t p_flags);
ResourceFormatSaverXInstance::_find_resources(const Variant &p_variant, bool p_main);
	--> Variant value = res->get(E.name);
 	--> Object::get(const StringName &p_name, bool *r_valid) const;
	--> script_instance->get(p_name, ret); --> OK
```
And the member variables in the script_instance of the incoming p_resource all exist, that is to say, they are the same in terms of parameters.

But I noticed that after the execution of 
```c++
_find_resources(p_resource, true);
```
in
```c++
ResourceFormatSaverTextInstance::save(const String &p_path, const Ref<Resource> &p_resource, uint32_t p_flags);
```
The value of `load_steps` is significantly different(compared to `ResourceFormatSaverBinaryInstance`), and `saved_resources` does not save the resource of the key-value pair with resource as the key. But `ResourceFormatSaverBinaryInstance` doesn't have this problem.

So I checked
```c++
ResourceFormatSaverBinaryInstance::_find_resources(const Variant &p_variant, bool p_main);
```
And found that the key is also cached in the case where p_variant is Variant::DICTIONARY.

So I guess the problem with `ResourceFormatSaverTextInstance` is that it doesn't cache the key.

### CODE REVIEW

**Comment by nathanfranke** [comment]
If your PR fixes an issue, please [link it](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) like this:

> Fixes #57506

File: scene/resources/resource_format_text.cpp [hunk 1]
```diff
@@ -1823,6 +1823,9 @@ void ResourceFormatSaverTextInstance::_find_resources(const Variant &p_variant,
 			List<Variant> keys;
 			d.get_key_list(&keys);
 			for (const Variant &E : keys) {
+				// Of course keys should also be cached, after all we can't prevent users from using resources as keys, right?
+				// See also ResourceFormatSaverBinaryInstance::_find_resources (when p_variant is of type Variant::DICTIONARY)
+				_find_resources(E);
 				Variant v = d[E];
 				_find_resources(v);
```
Comment (nathanfranke) [inline scene/resources/resource_format_text.cpp:1830]: Sorry, didn't read your full explanation, but I doubt this is the right fix. `_find_resources` sounds like an expensive function to call, so we shouldn't call it twice. _If this is not an issue_, I recommend putting another comment that explains _why_ this is called twice.

Comment (Life4gal) [reply scene/resources/resource_format_text.cpp:1830]: `_find_resources` is not an expensive function, on the contrary, it is necessary. The save will fail without the necessary caching of all sub-resources that need to be cached.

**Comment by Life4gal** [comment]
> If your PR fixes an issue, please [link it](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) like this:
> 
> > Fixes #57506
> 
> I also highly recommend checking how other PRs are formatted. 😃
> 
> Once your PR is ready for review again, squash your commits. [PRs should be composed of a single commit, with no merge commits](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#modifying-a-pull-request).

I just force-pushed the commits before merging the master branch, don't know if it's OK. 😃

**Comment by akien-mga** [comment]
There's an issue with the GitHub workflows on this PR (not your fault), just testing a close and reopen to see if that solves it.

**Comment by iamtoaster** [comment]
Any news on this? Would be nice to be able to use custom resources as keys in dictionaries and have them serialize properly.

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
This looks good, but it needs to be fixed to pass CI

**Comment by akien-mga** [comment]
Force pushed a rebase which should fix CI.

**Comment by akien-mga** [comment]
Thanks!
