### PR TITLE
display server window position bug fix

### LINKED ISSUE #37323: Project Manager appears in the corner of the screen
**Godot version:**
5f1107a

**OS/device including version:**
Windows 10

**Issue description:**
When you start Godot, the Project Manager appears in the top-left corner with title bar out of screen, so you can't move it. Resizing the window fixes it.

### PR DESCRIPTION
**Pull request by ThakeeNathees**
Fix: #37323
<s>#37366 is a working fix for windows but **I haven't tested this pr (using windows)** need testing and review (or this pr may helpful for someone trying to fix on their native)</s>

### CODE REVIEW

**Comment by ThakeeNathees** [comment]
@bruvzg could you have a look at this

File: platform/osx/display_server_osx.mm [hunk 1]
```diff
@@ -3524,7 +3524,13 @@ static void keyboard_layout_changed(CFNotificationCenterRef center, void *observ
...
 #endif
 
-	WindowID main_window = _create_window(p_mode, Rect2i(Point2i(), p_resolution));
+	float newDisplayScale = OS_OSX::get_singleton()->is_hidpi_allowed() ? newBackingScaleFactor : 1.0;
+
+	const NSRect contentRect = [wd.window_view frame];
+	Point2i window_position(
+			(contentRect.size.width * newDisplayScale - p_resolution.x) / 2,
+			(contentRect.size.height * newDisplayScale - p_resolution.y) / 2);
+	WindowID main_window = _create_window(p_mode, Rect2i(window_position, p_resolution));
```
Comment (bruvzg) [inline platform/osx/display_server_osx.mm:3533]: WindowData (`wd`) is created inside `_create_window` and it's not available here, neither is `main_window` on Linux. 

And it should be `sceen_size - p_resolution` not `window_size - p_resolution`, cause `p_resolution` is the window size in this case.

Probably something like:
```c++
Point2i window_position(
		(screen_get_size(0).x - p_resolution.x) / 2,
		(screen_get_size(0).y - p_resolution.y) / 2);
```
on both.

**Review by bruvzg — CHANGES_REQUESTED** [review]

File: platform/osx/display_server_osx.mm (hunk 1 above)
Comment (ThakeeNathees) [reply platform/osx/display_server_osx.mm:3530]: sorry for that, the visual studio intelisence  not working on osx file, no auto compilation and every text grayed out. @bruvzg  now I've ammend the commit

File: platform/linuxbsd/display_server_x11.cpp [hunk 2]
```diff
@@ -3603,8 +3603,11 @@ DisplayServerX11::DisplayServerX11(const String &p_rendering_driver, WindowMode
 		}
 	}
 #endif
-
-	WindowID main_window = _create_window(p_mode, p_flags, Rect2i(Point2(), p_resolution));
+	WindowData &main_window = windows[MAIN_WINDOW_ID];
+	Point2i window_position(
+			(main_window.size.width - p_resolution.x) / 2,
+			(main_window.size.height - p_resolution.y) / 2);
```
Comment (bruvzg) [inline platform/linuxbsd/display_server_x11.cpp:3609]: Same here main_window is create later, should be the same code as on macOS.

And probably the same on Windows too, just in case we'll need to create main window on non-primary monitor or add some DPI scaling to the `screen_get_` functions.

**Review by bruvzg — APPROVED** [review]

File: platform/osx/display_server_osx.mm (hunk 1 above)
Comment (ThakeeNathees) [reply platform/osx/display_server_osx.mm:3530]: I've changed 0 to window_get_current_screen(), and the windows display server position also need to changed like this (because of DPI value) and I'll do it ASAP @bruvzg

Comment (bruvzg) [reply platform/osx/display_server_osx.mm:3530]: I do not think `window_get_current_screen()` will work here, there's no any window created, 
it will return `-1` and crash, `0` should be OK for the primary screen.

Comment (bruvzg) [reply platform/osx/display_server_osx.mm:3530]: And won't work without argument either, it's the same as `window_get_current_screen()` but `window_get_current_screen()` is called from the `screen_get_size`.

Comment (ThakeeNathees) [reply platform/osx/display_server_osx.mm:3530]: Oh, I reset the screen to 0 but does it always be 0 (isn't there any enum or something?)

**Comment by ThakeeNathees** [comment]
@bruvzg I've also added windows(os) into this commit and it's working fine. could you review it again, and sorry for my unnecessary commits

File: platform/osx/display_server_osx.mm (hunk 1 above)
Comment (bruvzg) [reply platform/osx/display_server_osx.mm:3530]: It's just sequential display number, AFAIK primary display should be always `0`. 
Enum only have one value - `SCREEN_OF_MAIN_WINDOW = -1`, which means, use `window_get_current_screen()` to get display number.

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
