### PR TITLE
Fix multiple usability issues in the texture region editor

### LINKED ISSUE #75989: Region Editor does shows wrong texture when using Canvas Texture
### Godot version

v4.0.1.stable.official [cacf49999]

### System information

Windows 10

### Issue description

If you use Sprite2D with a regular CompressedTexture and set a Region on it, then use a Sprite2D with a CanvasTexture and a different texture in the diffuse, and try to set a Region, the Region Editor display will show the texture from the first sprite2D node. I would expect it to show the diffuse texture from the current Sprite2D.
image
image

### Steps to reproduce

Make a sprite2D node
add a texture to it 
set Region to Enabled
click Edit Region under 'Region'
set any region

Make another sprite2D node
add a CanvasTexture to it
add a different texture to the Diffuse part
set Region to Enabled
click Edit Region under 'Region'
see wrong texture

### Minimal reproduction project

[RegionEditorBug.zip](https://github.com/godotengine/godot/files/11212626/RegionEditorBug.zip)

### LINKED ISSUE #80403: Region Editor not showing the correct image when using Atlas texture in StyleBoxTexture
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Ubuntu 22.04.2 LTS 22.04 - Vulkan (Forward+) - integrated Intel(R) UHD Graphics 615 (AML-KBL) () - Intel(R) Core(TM) i3-10100Y CPU @ 1.30GHz (4 Threads)

### Issue description

Summary: When editing the subregion of a StyleBoxTexture, it shows me the entire spritesheet of the Atlas texture, instead of the selected portion of the atlas, making it difficult (and non-intuitive) to correctly select the subregion I need. 

What I expect: I understand that the sub-region may be used to emulate the behavior of a nine-patch. So I would expect to see there the subregion that i selected previously from the Atlas as the texture to be shown.

I have only tested this in a Panel Container

### Steps to reproduce

I found this problem when doing these steps:

- Add a PanelContainer node
- In the inspector select Theme Overrrides -> Style -> new StyleBoxTexture
- In the texture of the StyleBoxTexture select new AtlasTexture
- Dropped the spritesheet in the Atlas of the AtlasTexture
- In Region of the AtlasTexture, selected Edit Region and drew the rectangle on the texture i want:
image

- Back in the StyleBoxTexture options, in Sub-Region, clicked on Edit Region to select the nine-patch region i need
- Here is where the region editor shows me the entire spritesheet and not the sub-texture i selected from the atlas. The image below shows the axis correctly positioned for the nine-patch to work, but it is not intuitive because it has to be positioned without seeing the correct texture, making it difficult to finetune for some textures.

image

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by YuriSizov**
Fixes https://github.com/godotengine/godot/issues/75291. Fixes https://github.com/godotengine/godot/issues/80403 (a duplicate, actually). Fixes https://github.com/godotengine/godot/issues/75989 (at least, I can't reproduce it with the PR applied).

Changes include:

- Correctly display atlas textures when they are used by other supported objects (like nodes or styleboxes). We used to draw everything through a `CanvasTexture`, but it can't handle custom drawing logic of textures that it holds, such as `AtlasTexture`. So I reworked it to avoid relying on the `CanvasTexture`.

- Make region handles easier to interact with when editing NinePatchRect and StyleBoxTexture, which also have bars to adjust margins. We used to check handles last, which means bars would steal clicks. Since bars are normally long and can be clicked in plenty of places, and handles are small and located in precise positions, I switched it so handles are checked first.

- While testing I've noticed that a few things weren't properly initialized or restored. To name a couple, the default snap mode from the editor settings wasn't correctly applied, and the panning offset wouldn't completely update when opening the dialog.

- Various code quality changes. Moved all property initializations into the header. Removed unused methods, changed access modifiers of some remaining. Renamed everything. Extracted a few bits of logic into dedicated methods and unified how those are used. And other such changes.

- Add a check to `AtlasTexture::get_image()` to avoid bliting with invalid size values. It spammed a lot in the editor when using the region editor otherwise.

Apparently, you can use Godot's nose to create a nice ninepatch:

NVIDIA_Share_2023-08-08_23-07-11

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Code style looks good.

It's a ton of changes, I didn't review the code in depth.

File: editor/plugins/texture_region_editor_plugin.cpp [hunk 1]
```diff
@@ -38,23 +38,24 @@
...
 #include "scene/gui/check_box.h"
 #include "scene/gui/option_button.h"
+#include "scene/gui/panel_container.h"
 #include "scene/gui/separator.h"
 #include "scene/gui/spin_box.h"
 #include "scene/gui/view_panner.h"
 #include "scene/resources/atlas_texture.h"
 
-void draw_margin_line(Control *edit_draw, Vector2 from, Vector2 to) {
+void draw_margin_line(Control *texture_overlay, Vector2 from, Vector2 to) {
```
[the remark this answers is not in the document]
Comment (YuriSizov) [reply editor/plugins/texture_region_editor_plugin.cpp:47]: I think this was done on purpose (with the original name). This is a class-less method that only exists in the cpp file, and in this case `edit_draw`/`texture_overlay` actually refer to the class member which is passed to this method. For consistency I'll rename the parameters, but I'd like some policy regarding using such helper methods, is it even useful?

File: editor/plugins/texture_region_editor_plugin.cpp [hunk 2]
```diff
@@ -38,64 +38,67 @@
...
+		p_texture_overlay->draw_line(
+				p_from,
+				p_from + line,
 				EditorNode::get_singleton()->get_theme_base()->get_theme_color(SNAME("mono_color"), SNAME("Editor")),
 				Math::round(2 * EDSCALE));
 
-		from += line * 2;
+		p_from += line * 2;
 	}
 }
```
Comment (adamscott) [inline editor/plugins/texture_region_editor_plugin.cpp:66]: There's a lot of magic numbers used. I know that it was in the previous code, but could we use some `constexpr` to express those numbers?

Comment (YuriSizov) [reply editor/plugins/texture_region_editor_plugin.cpp:66]: I can do another code quality pass as a follow up. There are more things that can be improved here, but I'd rather not dilute this PR too much — it's pretty messy as it is (I should've acted with more restraint to begin with).

**Review by adamscott — APPROVED** [review]
As @akien-mga said, this seems fine. Didn't review the code extensively, but it looks good.

File: editor/plugins/texture_region_editor_plugin.cpp (hunk 2 above)
Comment (adamscott) [reply editor/plugins/texture_region_editor_plugin.cpp:66]: Maybe just for that function. It's pretty egregious. Like, what does the 200 mean on line 7? And the `* 2` afterwards.

Comment (YuriSizov) [reply editor/plugins/texture_region_editor_plugin.cpp:66]: The `*2` is because it's a dashed line. We first draw a solid line then draw dashes on top of it with a contrasting color. `line` is the size of the dash, so we draw one unit of `line` and skip another unit of `line`.

As for 200, I'm not completely sure myself.

File: editor/plugins/texture_region_editor_plugin.h [hunk 3]
```diff
@@ -66,45 +67,47 @@ class TextureRegionEditor : public AcceptDialog {
...
 	VScrollBar *vscroll = nullptr;
 	HScrollBar *hscroll = nullptr;
 
 	Vector2 draw_ofs;
-	float draw_zoom = 0.0;
+	float draw_zoom = 1.0;
 	bool updating_scroll = false;
 
-	int snap_mode = 0;
+	int snap_mode = SnapMode::SNAP_NONE;
```
Comment (kleonc) [inline editor/plugins/texture_region_editor_plugin.h:81]: Couldn't it be:
```suggestion
	SnapMode snap_mode = SNAP_NONE;
```
?

**Review by kleonc — COMMENTED** [review]
Skimmed through the code, definitely looks like an improvement! :+1:

File: editor/plugins/texture_region_editor_plugin.cpp (hunk 2 above)
Comment (YuriSizov) [reply editor/plugins/texture_region_editor_plugin.cpp:66]: I've done a little cleanup and added comments to explain the logic.

File: scene/resources/atlas_texture.cpp [hunk 4]
```diff
@@ -248,6 +248,9 @@ Ref<Image> AtlasTexture::get_image() const {
 	if (!atlas.is_valid() || !atlas->get_image().is_valid()) {
 		return Ref<Image>();
 	}
+	if (region.size.x <= 0 || region.size.y <= 0) {
+		return Ref<Image>();
+	}
 
 	return atlas->get_image()->get_region(region);
```
[the remark this answers is not in the document]
Comment (YuriSizov) [reply scene/resources/atlas_texture.cpp:255]: I agree with the suggestion and reasoning for it, made the changes.

For the second half, I don't know how it supposed to work, but I think that for the purposes of the region editor we don't want to have the margin applied. I think it's supposed to be added after the region. But yeah, it's not new to this PR, so I'd leave it for another day if someone has a better idea.

[the remark this answers is not in the document]
Comment (kleonc) [reply scene/resources/atlas_texture.cpp]: > For the second half, I don't know how it supposed to work, but I think that for the purposes of the region editor we don't want to have the margin applied. I think it's supposed to be added after the region. But yeah, it's not new to this PR, so I'd leave it for another day if someone has a better idea.

Yeah, I agree. Margin shouldn't be shown in the region selector, it's indeed "added after region". What would make sense for the margin is e.g. to have a separate "margin editor" dialog (openable by "Edit Margin" button in the inspector) where the already selected region would be shown and it would allow to only drag the margins on top of the region.
But yeah, that's for a different PR.

**Review by kleonc — APPROVED** [review]
I've done some testing, LGTM!
Tried multi-nested AtlasTextures with non-zero margins. Even for these both texture rendering and region selecting is working correctly.
I've also played a little with StyleBoxTexture or NinePatchRect, haven't had any issues.

Note there are still cases where the texture (for which the region is being edited) will be rendered "incorrectly". E.g. when selecting a region for a CanvasTexture with an AtlasTexture assigned to its diffuse texture, such texture would't be rendered "correctly" within the region editor. But such specific combination doesn't work properly even outside of the region editor (I think using AtlasTextures within CanvasTexture is not supported), meaning that's not an issue with the region editor itself. 

AFAICT, what's supported seems to work just fine. :+1:
(haven't tested everything though; but for sure things work better than before :upside_down_face:)

---

There's this small issue when editing a `(0, 0, 0, 0)` region:
godot windows editor x86_64_QwJWiFQR4i
After opening the region editor it shows as if the whole texture was selected as the region:
wgBMFXaxMP
Closing the region editor without changes makes the region remain being `(0, 0, 0, 0)`. This might be surprising given within the texture editor the whole texture was shown to be selected.
Any slight region-drag within the region editor is needed to make the region be set accordingly within the Sprite2D etc. (even when snapping so no effective change):
LMEDXVfCLD
Not sure if anything/what needs to be done about this.

**Comment by YuriSizov** [comment]
> Not sure if anything/what needs to be done about this.

I can revert some changes, because that's on me. I unified some of that logic that used to treat these as special cases (or rather other empty regions as special cases). I think, though, that it's more intuitive for an empty region to equal the whole image. At least it is more user friendly when opening the region editor, in my mind.

But I guess there is a different between an empty region and and empty region with a "use region" toggle. So I dunno. We can keep it as is and see if there are complaints after the change, I guess.

**Comment by akien-mga** [comment]
Thanks!

**Comment by ramireshimself** [comment]
Help. please"
Is there a way I can dock the Region Editor?
image
image
I´m foloing a tutorial and its reali anoying that I can't dock the editor as it is in the video and I have to open and close it every time I change the timeline for each region edit.

**Comment by YuriSizov** [comment]
@ramireshimself You cannot dock it, no. It used to be a contextual editor on the bottom panel, but this was changed in Godot 4.

**Comment by ramireshimself** [comment]
Thanks for the awenser. So there is no simmilar way to do like before? I have to do it one by one, closing, keyfaming and opening again, and edit, etc, etc?

**Comment by KoBeWi** [comment]
You can input the value in the inspector.

**Comment by ramireshimself** [comment]
thnks, I´ll try.
