### PR TITLE
Fix VisibilityEnabler2D behavior on start

### LINKED ISSUE #9321: VisibilityEnabler2D does not take effect when it is added to scene tree.
**Operating system or device - Godot version:**
Godot 2.1.3

**Issue description:**

When a scene with a VisibilityEnabler2D  is add to the scene tree outside of the screen, VisibilityEnabler2D will not take effect, it only take effect when it enter screen and then exit screen. 

**Steps to reproduce:**

**Link to minimal example project:**

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #9321

The bug was caused by parent's `NOTIFICATION_READY` overwriting the `set_process(false)`. Deferring the call helped, but for `_physics_process` I had to use a _little_ hack, because the deferred call happens after physics frame.

### CODE REVIEW

**Comment by EngBraga** [comment]
Will this one be in 3.2?

**Comment by KoBeWi** [comment]
I realized that since `CONNECT_ONESHOT` is a thing, this could be done 99% less hacky. I rebased and fixed the PR and now it's 100% correct and 100% simple.

**Comment by RandomShaper** [comment]
I think that what is needed for the notifier just needs to update the worlds at start. See this function:
```
void Viewport::update_worlds() {

	if (!is_inside_tree())
		return;

	Rect2 abstracted_rect = Rect2(Vector2(), get_visible_rect().size);
	Rect2 xformed_rect = (global_canvas_transform * canvas_transform).affine_inverse().xform(abstracted_rect);
	find_world_2d()->_update_viewport(this, xformed_rect);
	find_world_2d()->_update();

	find_world()->_update(get_tree()->get_frame());
}
```

I'd say there are two options here:
a) Anyone wanting notifications before the physics frame just knows they need to call it manually on whatever `Viewport` they need it to happen (even the root one).
b) This idea is integrated in the notifier code (the relevant part depending on if it's a 2D or 3D notifier) so they do it automatically when entering a `Viewport`.

What do you think?

**Comment by RandomShaper** [comment]
Hmm... Now I think of it that may not be a solution for the original problem.

**Comment by KoBeWi** [comment]
I don't really get the viewports solution >_>
The problem looks like this:
1. The node receives ENTER_TREE
2. The Notifier sets process to false
3. Node receives NOTIFICATION_READY
4. The node has overridden `_process_method` so it automatically sets process to true

It's all because the notifier takes action too early, so deferring the call is correct. Although using the `ready` signal in both cases might be better actually.

**Comment by RandomShaper** [comment]
Yes, definitely what I've suggested is for a different problem. I misread the bug.

To me this fix is fine. I'd only add a comment explaining why it's done that way (the same that is explained here) because it's not evident and it depends on fine details on how frames are processed.

**Comment by RandomShaper** [comment]
Also, this is probably wanted in 3.2, but I'm not sure about a possible compatibility breakage. If projects are already relying on the defective behavior, it may be bad to backport.

But in case it's wanted for 3.2 in the end, a simple cherry-pick won't be enough. It will need a separate PR because of the signal connection code.

**Comment by KoBeWi** [comment]
Ok, added the comment and changed both to use the signal. The formatting looks interesting 🤔

File: scene/2d/visibility_notifier_2d.cpp [hunk 1]
```diff
@@ -252,10 +252,18 @@ void VisibilityEnabler2D::_notification(int p_what) {
 
 		_find_nodes(from);
 
-		if (enabler[ENABLER_PARENT_PHYSICS_PROCESS] && get_parent())
-			get_parent()->set_physics_process(false);
-		if (enabler[ENABLER_PARENT_PROCESS] && get_parent())
-			get_parent()->set_process(false);
+		/*We need to defer the call of set_process and set_physics_process, because	otherwise they are overwritten inside NOTIFICATION_READY.
+		We can't use call_deferred, because it happens after a physics frame.
+		The ready signal is emitted immediately after the NOTIFICATION_READY is finished, so it's perfect here.*/
```
Comment (akien-mga) [inline scene/2d/visibility_notifier_2d.cpp:257]:
```suggestion
		// We need to defer the call of set_process and set_physics_process, otherwise they are
		// overwritten inside NOTIFICATION_READY. We can't use call_deferred, because it happens
		// after a physics frame. The ready signal is emitted immediately after the NOTIFICATION_READY
		// is finished, so it's perfect here.
```

**Comment by EngBraga** [comment]
Thank you guys again for working on this one!

**Comment by akien-mga** [comment]
> Also, this is probably wanted in 3.2, but I'm not sure about a possible compatibility breakage. If projects are already relying on the defective behavior, it may be bad to backport.

IMO that's the situation with most bug fixes - any bug we fix can probably break a project which somehow relied on the behavior being broken.

For each bug fix, we have to gauge how likely it is that users are relying on the bug (knowingly or unknowingly) in their projects. In this case, I would expect that most users would want this fix, and the workarounds that might have implemented already should still work.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.
