### PR TITLE
Fix can't convert to ShaderMaterial in FileSystemDock

### LINKED ISSUE #107833: [4.5] Can't convert `StandardMaterial3D` to `ShaderMaterial` in FileSystemDock
### Tested versions

Reproducible in 4.5.beta1
Not reproduible in 4.4

### System information

Linux

### Issue description

Can't convert `StandardMaterial3D` to `ShaderMaterial` in FileSystemDock in 4.5.

However in inspector converting works well. 

### Steps to reproduce

Create a `StandardMaterial3D`, in FileSystemDock, convert it to `ShaderMaterial` 

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by beicause**
Fixes #107833

Likely a regression from #106041 according to blame history

### CODE REVIEW

**Comment by BlueCube3310** [comment]
Tested locally, the fix only works when the file system dock is in "vertical" mode. When moved to the bottom, it still doesn't work.

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -2112,7 +2112,7 @@ Vector<String> FileSystemDock::_remove_self_included_paths(Vector<String> select
 }
 
 void FileSystemDock::_tree_rmb_option(int p_option) {
-	if (p_option > FILE_MENU_MAX) {
+	if (p_option != CONVERT_BASE_ID && p_option > FILE_MENU_MAX) {
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp]: It should be something more like
```suggestion
	if (p_option > FILE_MENU_MAX && p_option < CONVERT_BASE_ID) {
```
otherwise it will handle only the first available conversion.

**Review by KoBeWi — APPROVED** [review]
Looks good.

I included part of this fix in #106040, but I didn't expect it to be merged first 😅

**Comment by Repiteo** [comment]
Thanks!
