### PR TITLE
Fix WindowWrapper leaking all key inputs to parent

### LINKED ISSUE #104758: Shader editor floating window input passes through to script editor
### Tested versions

reproducible in v4.4.stable.official [4c311cbee]

### System information

Godot v4.4.stable - Windows 11 (build 22631) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 (NVIDIA; 31.0.15.4617) - AMD Ryzen 5 5500 (12 threads)

### Issue description

When editing shaders in floating window, the keyboard input passes through to the script panel of the main window, causing unexpected edits to the code.

https://github.com/user-attachments/assets/f708c0f6-16ff-482b-9354-1fc775248015

_Expected behavior_

the input is consumed by the shader floating window and does not pass through to main window.

### Steps to reproduce

1. Open the script editor and shader editor.
2. Make the shader editor floating, switch to main window and back.
3. With the shader editor focused, press the spacebar to pan or press any key.
4. The input will passthrough to the code editor.

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #108594: Ctrl-c and Ctrl-x malfunctions in script editor window if inspector is focused.
### Tested versions

- Reproducible in 4.4.1 stable
- Reproducible in 4.6 beta1
Did not test other versions yet

### System information

Godot v4.4.1.stable (22a1c1795) - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 32.0.15.6094) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 threads)

Godot v4.6.beta1 - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 32.0.15.6094) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 threads) - 95.93 GiB memory

### Issue description

If I pop out the script editor, and use it, copy and paste does not work consistently.

When an input box is focused in the main Godot Engine editor window, it seems to override any text selected in the Script Editor, leading to possibly losing code when copying code from one file to another.

Another interesting side effect is Ctrl-X will clear the value from the selected inspector field, which could cause unnoticed mistakes later.

What I expect to happen is, if the Script Editor is focused, keyboard shortcuts should not affect the main engine window, with the possible exception of ctrl-S which is supposed to globally save the active scene (as opposed to Ctrl-Alt-S which is local to the script editor window)

### Steps to reproduce

- Pop Script Editor out to a separate window.
- Focus a text box in the inspector, like a float spinbox with value 1.234. Leave the whole number selected.
- Go back to script editor, and write some text.
- Then, attempt to copy and paste the text using ctrl-c and ctrl-v
- The number 1.234 will be pasted.
- Now, go back to the main godot editor and defocus the inspector.
- Now repeat the process of ctrl-c and ctrl-v in the script editor. It now works properly as it should.

### Minimal reproduction project (MRP)

N/A - built into script editor

### PR DESCRIPTION
**Pull request by kitbdev**
- Fixes https://github.com/godotengine/godot/issues/104758
- Fixes https://github.com/godotengine/godot/issues/108594
- Fixes partially https://github.com/godotengine/godot/issues/106285 - the script editor no longer takes the events, but the game doesn't either

This happened with any floating window that didn't accept the input and any node that used key input or non-global shortcuts in the parent window.
The cause was this hack in WindowWrapper:

https://github.com/godotengine/godot/blob/56f3e2611daadb0b1894b46737ee3000e82e33f9/editor/gui/window_wrapper.cpp#L66-L67

WindowWrapper's ShortcutBin was pushing inputs to parent windows for global shortcuts, but this was being treated as normal input for TextEdit and all other nodes. Only shortcuts should be sent to the parent window, and we can't just filter to InputEventShortcut, since InputEventKey is also used for shortcuts.
I added a parameter to Viewport to handle this and logic just for shortcuts. It is not exposed for now, but may be useful generally.
We may also want to use this for popup menus in the future, so global shortcuts can still work when they are open.

I ignore the parent viewport if it doesn't use `handle_input_locally`, since it isn't needed in the Editor.

### CODE REVIEW

File: scene/gui/control.cpp [hunk 1]
```diff
@@ -2041,7 +2041,7 @@ bool Control::is_focus_owner_in_shortcut_context() const {
 	}
 
 	const Node *ctx_node = get_shortcut_context();
-	const Control *vp_focus = get_viewport() ? get_viewport()->gui_get_focus_owner() : nullptr;
+	const Control *vp_focus = get_viewport() && get_viewport()->gui_shortcut_use_focus_owner() ? get_viewport()->gui_get_focus_owner() : nullptr;
```
Comment (AThousandShips) [inline scene/gui/control.cpp]:
```suggestion
	const Control *vp_focus = (get_viewport() && get_viewport()->gui_shortcut_use_focus_owner()) ? get_viewport()->gui_get_focus_owner() : nullptr;
```

**Review by YeldhamDev — APPROVED** [review]
Fixes the issues on my end. But needs a rebase.
