### PR TITLE
Replace `//` with `\\` before sending path to Blender

### LINKED ISSUE #85334: When using the blend importer on a windows network share,
### Godot version

Godot v4.1.3.stable.mono

### System information

Godot v4.1.3.stable.mono - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.4601) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description

When using the `.blend` importer on Windows 10 and the assets are on a network drive, the automatic gltf export and import fails with
`modules/gltf/gltf_document.cpp:7433 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN`

### Steps to reproduce

1. On Windows 10, create a project on a SMB network share with a `\\fileshare\game\asset\` type path.
2. Add a .blend file to project.

### Minimal reproduction project

N/A because the issue is only present when inside a specific OS and filesystem type.

### PR DESCRIPTION
**Pull request by zinefer**
# Why?

I was having an issue using the blend importer and realized it was the fact that I keep my files on a network drive. Using wireshark I was able to see both the http RPC call and the SMB traffic and could tell that Blender was attempting to open a file at `//fileshare/game/fileshare/game/assets/model.blend` and not finding it. I can see that the path sent is `//fileshare/game/assets/model.blend` but unfortunately, without the backslashes, Blender just treats it as a relative path.

Interesting too, because `c_escape()` is being called which says to me that someone expected this to return backslashes.

Then I noticed in [`ProjectSettings`](https://github.com/godotengine/godot/blob/master/core/config/project_settings.cpp#L524) that `\` is replaced with `/`.

# What?

Instead, when the path begins with `//`, replace the first two chars with `\\` which when escaped becomes `\\\\`.

Resolves #85334

### CODE REVIEW

File: modules/gltf/editor/editor_scene_importer_blend.cpp [hunk 1]
```diff
@@ -134,7 +134,19 @@ Node *EditorSceneFormatImporterBlend::import_scene(const String &p_path, uint32_
...
+	String source_global = ProjectSettings::get_singleton()->globalize_path(p_path)
+
+	#ifdef WINDOWS_ENABLED
+		// On Windows, when using a network share path, the above will return a path starting with "//"
+		// which once handed to Blender will be treated like a relative path. So we need to replace the
+		// first two characters with "\\" to make it absolute again
+		if (source_global.is_network_share_path()) {
+			source_global = source_global.replace(0, 2, "\\");
+		}
+	#endif
```
Comment (aaronfranke) [inline modules/gltf/editor/editor_scene_importer_blend.cpp:146]: Per our style, preprocessor directives should not be indented.

File: modules/gltf/editor/editor_scene_importer_blend.cpp [hunk 2]
```diff
@@ -134,7 +134,19 @@ Node *EditorSceneFormatImporterBlend::import_scene(const String &p_path, uint32_
 
 	// Get global paths for source and sink.
 	// Escape paths to be valid Python strings to embed in the script.
-	const String source_global = ProjectSettings::get_singleton()->globalize_path(p_path).c_escape();
+	String source_global = ProjectSettings::get_singleton()->globalize_path(p_path)
```
Comment (aaronfranke) [inline modules/gltf/editor/editor_scene_importer_blend.cpp:137]: You forgot a `;`, so this doesn't even compile.

Comment (zinefer) [reply modules/gltf/editor/editor_scene_importer_blend.cpp:137]: Fixed!

File: modules/gltf/editor/editor_scene_importer_blend.cpp [hunk 3]
```diff
@@ -134,7 +134,19 @@ Node *EditorSceneFormatImporterBlend::import_scene(const String &p_path, uint32_
...
 	// Escape paths to be valid Python strings to embed in the script.
-	const String source_global = ProjectSettings::get_singleton()->globalize_path(p_path).c_escape();
+	String source_global = ProjectSettings::get_singleton()->globalize_path(p_path);
+
+#ifdef WINDOWS_ENABLED
+	// On Windows, when using a network share path, the above will return a path starting with "//"
+	// which once handed to Blender will be treated like a relative path. So we need to replace the
+	// first two characters with "\\" to make it absolute again
+	if (source_global.is_network_share_path()) {
+		source_global = source_global.replace(0, 2, "\\");
```
Comment (AThousandShips) [inline modules/gltf/editor/editor_scene_importer_blend.cpp:144]: There's no such overload for strings, you'd need to instead:
```suggestion
		source_global = "//" + source_global.right(-2);
```
To strip the first two characters

[the remark this answers is not in the document]
Comment (zinefer) [reply modules/gltf/editor/editor_scene_importer_blend.cpp:144]: Oh I see... I'll get this fixed and make sure to figure out how to compile godot locally before pushing any more commits.

[the remark this answers is not in the document]
Comment (AThousandShips) [reply modules/gltf/editor/editor_scene_importer_blend.cpp:144]: You're not using `std::string` but our own string type

Comment (zinefer) [reply modules/gltf/editor/editor_scene_importer_blend.cpp:144]: Oh! This is amazing, thanks so much. My cpp experience is mostly embedded and I'm new here so I need the help.

Comment (AThousandShips) [reply modules/gltf/editor/editor_scene_importer_blend.cpp:144]: To see details see `core/string/ustring.h`

**Comment by zinefer** [comment]
I just wanted to double check, is there anything else I can do to improve this? I considered an integration test but since it's an interaction between Godot, Blender and a Windows file share, it might be more trouble than it's worth.

**Comment by fire** [comment]
@RedMser Looking good?

File: modules/gltf/editor/editor_scene_importer_blend.cpp [hunk 4]
```diff
@@ -134,7 +134,19 @@ Node *EditorSceneFormatImporterBlend::import_scene(const String &p_path, uint32_
...
 	// Escape paths to be valid Python strings to embed in the script.
-	const String source_global = ProjectSettings::get_singleton()->globalize_path(p_path).c_escape();
+	String source_global = ProjectSettings::get_singleton()->globalize_path(p_path);
+
+#ifdef WINDOWS_ENABLED
+	// On Windows, when using a network share path, the above will return a path starting with "//"
+	// which once handed to Blender will be treated like a relative path. So we need to replace the
+	// first two characters with "\\" to make it absolute again
+	if (source_global.is_network_share_path()) {
+		source_global = "//" + source_global.right(-2);
```
Comment (RedMser) [inline modules/gltf/editor/editor_scene_importer_blend.cpp:144]: Typo? Comment and PR description say it needs to be backslashes to work, not forwardslashes.
```suggestion
		source_global = "\\\\" + source_global.right(-2);
```

**Review by RedMser — CHANGES_REQUESTED** [review]

**Comment by RedMser** [comment]
@zinefer Judging by the discussion above, you have not compiled the code to see if your change actually fixes the problem?

If you don't want to build Godot locally (although it's recommended to set that up on your PC for easier testing), you can download a build from GitHub by going to this PR's "Checks" tab at the top, then in the top right there is a dropdown "Artifacts".

**Comment by zinefer** [comment]
> you have not compiled the code to see if your change actually fixes the problem?

I have tested the Blender side by calling the RPC with a modified payload but I have not done E2E testing.

> you can download a build from GitHub by going to this PR's "Checks" tab at the top, then in the top right there is a dropdown "Artifacts".

Great tip! I will report back. Thanks for all the help everyone. 🤩

**Comment by zinefer** [comment]
I have tested it E2E and with the latest fix, things are working! 🎉 

Here's a screen recording:


https://github.com/godotengine/godot/assets/466002/3cb963d7-3aed-47b1-b356-7806d5d99e8c

**Review by RedMser — APPROVED** [review]

File: modules/gltf/editor/editor_scene_importer_blend.cpp [hunk 5]
```diff
@@ -134,7 +134,19 @@ Node *EditorSceneFormatImporterBlend::import_scene(const String &p_path, uint32_
 
 	// Get global paths for source and sink.
 	// Escape paths to be valid Python strings to embed in the script.
-	const String source_global = ProjectSettings::get_singleton()->globalize_path(p_path).c_escape();
+	String source_global = ProjectSettings::get_singleton()->globalize_path(p_path);
+
+#ifdef WINDOWS_ENABLED
+	// On Windows, when using a network share path, the above will return a path starting with "//"
+	// which once handed to Blender will be treated like a relative path. So we need to replace the
+	// first two characters with "\\" to make it absolute again
```
Comment (akien-mga) [inline modules/gltf/editor/editor_scene_importer_blend.cpp:142]:
```suggestion
	// first two characters with "\\" to make it absolute again.
```

File: modules/gltf/editor/editor_scene_importer_blend.cpp [hunk 6]
```diff
@@ -134,7 +134,19 @@ Node *EditorSceneFormatImporterBlend::import_scene(const String &p_path, uint32_
...
+	if (source_global.is_network_share_path()) {
+		source_global = "\\\\" + source_global.right(-2);
```
Comment (akien-mga) [inline modules/gltf/editor/editor_scene_importer_blend.cpp:144]: Had to wrap my head around a bit to under what `right(-2)` would do, I think `substr(2)` is clearer.

**Review by akien-mga — COMMENTED** [review]
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by AThousandShips** [comment]
You didn't squash your commits, you just picked the first one, you need to restore what suggestions were made

**Comment by zinefer** [comment]
Yeah, I see that, I'm working on it! Thanks for the fast assistance!

**Comment by AThousandShips** [comment]
You can do: `git reset --hard dc17496` and try again

**Comment by zinefer** [comment]
Failing style checks now... On it. 😰

**Comment by zinefer** [comment]
Oof! I sure made a mountain out of that molehill. 😅 

I think we're good to go now. A single commit with:
- A period on the end of my long comment
- Properly indented ifdefs
- `substr(2)` over `right(-2)`
- Certified backslashes
- (tbd) Passes style checks
- (tbd) Compiles

Once the pipeline finishes, I'll download the executable and test it against my project just to be extra careful since I have already mucked this up lol.

**Comment by zinefer** [comment]
I just downloaded and successfully tested this build. 🎉

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.
