### PR TITLE
Fix paste value emptying an array on some right click location

### LINKED ISSUE #80974: Paste Value can empty an array depending on right-click location
### Godot version

4.2.dev 6758a7f8c

### System information

Godot v4.2.dev (6758a7f8c) - Fedora Linux 38 (KDE Plasma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 535.98) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

- *Related to https://github.com/godotengine/godot/issues/75124.*

**Paste Value** on an exported Array property can empty the array depending on right-click location:

https://github.com/godotengine/godot/assets/180032/e9cf313b-bb09-4712-95cd-f53481fa33e4

### Steps to reproduce

- Create a script with an exported array property.
- Save the scene (and script) and select the node.
- Add 3 items to the array with any type (`int` is used in this example).
- Set non-default values for each item.
- Right-click an item and choose **Copy Value**.
- Aim to the left of the item's name (near the drag-and-drop reorder icon), right-click another item and choose **Paste Value**.
- Notice how the array's size is reset to 0 and all values are lost (this can be undone).

### Minimal reproduction project

[test_array_paste_value_empty.zip](https://github.com/godotengine/godot/files/12433905/test_array_paste_value_empty.zip)

### PR DESCRIPTION
**Pull request by ajreckof**
Fixes #80974

### CODE REVIEW

**Comment by YuriSizov** [comment]
Is your PR title and commit message missing the word "Fix" in front?

**Comment by ajreckof** [comment]
Yeah thanks

**Review by KoBeWi — APPROVED** [review]

File: editor/editor_properties_array_dict.cpp [hunk 1]
```diff
@@ -254,7 +254,7 @@ void EditorPropertyArray::update_property() {
 		array_type_name = vformat("%s[%s]", array_type_name, type_name);
 	}
 
-	if (array.get_type() == Variant::NIL) {
+	if (!array.is_array()) {
```
Comment (KoBeWi) [inline editor/editor_properties_array_dict.cpp:257]: Not sure what this change is about though.

Comment (ajreckof) [reply editor/editor_properties_array_dict.cpp:257]: When you assign an int in place of the whole array since it is not a `Variant::NIL` it would just go on and assume it is an array try to get the length of it etc which are actions only accessible to variant types that are arrays hence the high amount of errors that are shown. Other places of this class already used `!array.is_array` for example in the `_edit_pressed` function so most likely there had already been problems of the sort and this one was missed / got merged after.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.3.
