### PR TITLE
Fix byte to float color conversion in `DisplayServerWindows::screen_get_pixel`

### LINKED ISSUE #79348: Color Picker Eyedropper does not pick the same Color as getting the Color from the image data
### Godot version

4.1

### System information

Godot v4.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - integrated Intel(R) Iris(R) Xe Graphics (Intel Corporation; 30.0.101.1660) - 12th Gen Intel(R) Core(TM) i7-1260P (16 Threads)

### Issue description

I made an image with only one color and no partially transparent tiles. When I get the list of all colors through code, I get one color. When I use the eyedropper on a color picker to get the same color, the color is different. For example, using a color of 23674e gets me (0.1373, 0.4039, 0.3059, 1) as the color from the image data, and (0.1367, 0.4023, 0.3047, 1) as the color from the color picker eyedropper. This is not close enough for `Color.is_equal_approx` to count it as the same color.

### Steps to reproduce

1. Make an image
2. Get an array of colors from the image via the Image class
3. Get a color from the image via the Color Picker eyedropper
4. The color isn't in the array.

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/12017629/test.zip)

### PR DESCRIPTION
**Pull request by kleonc**
`255` should be mapped to `1.0`, it was mapped to `255.0 / 256.0`.

`byte / 255.0` is how we convert in most places I think (e.g. in `Color` or `Image`).

Fixes #79348.

No incorrect conversion spotted for Linux / MacOS:

https://github.com/godotengine/godot/blob/23318e877890029f35856036b9c4e0bfa09cacc6/platform/linuxbsd/x11/display_server_x11.cpp#L1220-L1220
https://github.com/godotengine/godot/blob/23318e877890029f35856036b9c4e0bfa09cacc6/platform/macos/display_server_macos.mm#L2226-L2228

### CODE REVIEW

**Review by bruvzg — APPROVED** [review]

File: platform/windows/display_server_windows.cpp [hunk 1]
```diff
@@ -618,7 +618,7 @@ Color DisplayServerWindows::screen_get_pixel(const Point2i &p_position) const {
 		COLORREF col = GetPixel(dc, p.x, p.y);
 		if (col != CLR_INVALID) {
 			ReleaseDC(NULL, dc);
-			return Color(float(col & 0x000000FF) / 256.0, float((col & 0x0000FF00) >> 8) / 256.0, float((col & 0x00FF0000) >> 16) / 256.0, 1.0);
+			return Color(float(col & 0x000000FF) / 255.0, float((col & 0x0000FF00) >> 8) / 255.0, float((col & 0x00FF0000) >> 16) / 255.0, 1.0);
```
Comment (aaronfranke) [inline platform/windows/display_server_windows.cpp:621]: Could be better though, if we use float literals we can ensure the calculation is done with float and not with double:

```suggestion
			return Color(float(col & 0x000000FF) / 255.0f, float((col & 0x0000FF00) >> 8) / 255.0f, float((col & 0x00FF0000) >> 16) / 255.0f, 1.0f);
```

**Review by aaronfranke — COMMENTED** [review]
Yes, it should divide by 255 as this PR does.

**Review by aaronfranke — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.
