### PR TITLE
Fetch video adapter driver name and version from OS

### LINKED ISSUE #5032: Add `get_video_driver_name()` and `get_video_driver_version()` methods to RenderingServer
### Describe the project you are working on

Videogame - features **bug reporting**, therefore requires collecting system info

### Describe the problem or limitation you are having in your project

While we can already fetch info on the graphics card itself (`VisualServer.get_video_adapter_name()`, `VisualServer.get_video_adapter_vendor()`), the player's driver (name + version) are unknown.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Knowing the driver and its version can help to choose an alternate shader (in case issues are known to the game developer).  
Or inform player about possible issues with their current driver: Some Godot errors are specific to particular drivers (looking at video-linux with respect to blend shapes in particular, where a switch to video-vesa fixed an issue. not ideal, but better than nothing): detecting the driver name enables the developer to show automatic warning messages to players informing about known rendering issues with their driver and that they should switch drivers, if possible.  
Same is with actual driver versions: Some issues are resolved by simply updating the driver version (or downgrade because of driver regression bugs). Which is kind of the first line of defense, telling the player to "update/downgrade your driver version".

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

in VisualServer / RenderingServer

```gdscript
String get_video_driver_name ( ) const
# Returns the driver used for the system's current graphics card, such as `nvidia`, `nouveau`, `intel`, `amdgpu`.

String get_video_driver_version ( ) const
# Returns the currently used video driver version, e.g. `515.57` for the `nvidia` driver.
```

alternative function name suggestions to prevent name clash with OS.get_video_driver_name():
```gdscript
String get_video_adapter_driver_name ( ) const

String get_video_adapter_driver_version ( ) const
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Cannot be worked around with a few lines. Would require system calls which are OS-specific.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving collecting system info for video games, apps and Godot itself (at least giving Godot the potential to copy&paste system data in github issues - which should be approached in a separate proposal).

### PR DESCRIPTION
**Pull request by MJacred**
Closes https://github.com/godotengine/godot-proposals/issues/5032  
If #65902 is implemented before this, then extend it by this new info

TODO list
* [x] resolve conflicts with master
* [x] check WMI class for Windows
* [x] implement for Windows
* [x] research macOS, iOS
* [x] research Android
* [x] create one method `OS.get_video_adapter_driver_info()` instead of two
* [x] update class docs, that only Linux/BSD and Windows are supported

**only testing for Windows left** (will set everything up on my Windows machine later this week and test, if no one else does it beforehand)

already working for Linux/BSD:
```gdscript
print(OS.get_video_adapter_driver_info())
```

prints
```
["nvidia", "510.85.02"]
```

# Design

* create one method `OS.get_video_adapter_driver_info()` instead of two, which returns a String array of length 2: driver name, driver version :heavy_check_mark: 
  * reasoning: usually, you want name AND version. And on Linux/BSD, fetching the version requires looking up driver name (which requires at least 3 commands to be executed); other OS might have similar expense…
* ~~or keep the two methods, and pass in driver name into `OS.get_video_adapter_driver_version()`~~
  * preferring former one

# Linux/BSD

:heavy_check_mark: 

uses
* `lspci` for fetching driver name
  * part of `pciutils` (must be installed -> is auto-installed on most Linux/BSD distributions)
    * see https://github.com/pciutils/pciids/blob/master/pci.ids for list of device codes/IDs
* `modinfo` for driver version

# Windows

got it working using powershell:
`Get-WmiObject -Class Win32_PnPSignedDriver -Filter "DeviceName = 'NVIDIA GeForce GTX 970'"`
* get DriverName, if empty, return DriverProviderName (on Windows, DriverName is empty on my system -> maybe for most people like this?)
* get DriverVersion: 31.0.15.1659
* DeviceName can be fetched using `RenderingServer::get_singleton()->get_rendering_device()->get_device_name();`
  * in contrast to Linux/BSD, no further manipulation is required; i.e. can use as-is

## using WMI

IWbemServices::GetObject method
* https://learn.microsoft.com/en-us/windows/win32/api/wbemcli/nn-wbemcli-iwbemservices
* https://learn.microsoft.com/en-us/windows/win32/wmisdk/making-a-semisynchronous-call-with-c--
* https://learn.microsoft.com/en-us/windows/win32/wmicoreprov/wdm-provider
* https://learn.microsoft.com/en-us/windows/win32/api/wbemcli/nf-wbemcli-iwbemservices-getobject
* https://learn.microsoft.com/en-us/windows/win32/api/wbemcli/nn-wbemcli-iwbemclassobject
* https://learn.microsoft.com/en-us/windows/win32/api/wbemcli/nn-wbemcli-iwbemlocator

Win32_PnPSignedDriver class
* https://learn.microsoft.com/en-us/previous-versions/windows/desktop/whqlprov/win32-pnpsigneddriver
* Namespace "Root\CIMV2"

# macOS/ iOS

**not supported**, because it's shipped with OS, see https://github.com/godotengine/godot/pull/66102#issuecomment-1252709843

<details>
<summary>Old text</summary>
I'm currently stuck</br>
* there's `sysctlbyname`, but no info on internet if it helps (probably not?)</br>
* IOKit; replaced by **DriverKit**; sems like the right place, but I'm stuck with the limited documentation and no macOS to try it out</br>
  * https://developer.apple.com/documentation/driverkit</br>
  * https://developer.apple.com/documentation/pcidriverkit</br>
  * https://developer.apple.com/documentation/pcidriverkit/iopcidevice</br>
    * use [CopyProperties](https://developer.apple.com/documentation/kernel/ioservice/3180694-copyproperties) to find out what the property names for driver name and version are</br>
  * https://developer.apple.com/documentation/kernel/iocatalogue/1811225-finddrivers</br>
  * https://developer.apple.com/documentation/kernel/iocatalogue/1811242-finddrivers</br>
* there's also `system_profiler` and the `sppcidatatype`. though no idea what it provides</br>
</details>

# Android

**not supported**, because it does not seem to be available

seems to overlap with Linux/BSD
* https://github.com/LineageOS/android_external_pciutils
  * `lspci` -> so you could potentially get the driver name
  * but found no info on `modinfo` command -> so no version

has profiling: https://developer.android.com/agi
* but not for this data

# Web

**not supported**  
not even sure if this is even technically possible (i.e. is this info in the user agent?)

# UWP

**not supported**  
as support might get dropped

### CODE REVIEW

**Comment by bruvzg** [comment]
> not supported, because macOS developer, who can do testing to find out property names, required

On macOS / iOS, GPU driver is part of OS and updated only with the OS.

You can get versions of individual `kext`s from IOKit API or using `kextstat` command, but this information is pretty useless, OS version should be sufficient for any purpose.

`sysctlbyname` is for system config, not device / driver info, `system_profiler SPPCIDataType` will list PCIe devices, but not the drivers, also on Apple Silicon and iOS GPU is not a PCIe device.

File: platform/windows/os_windows.cpp [hunk 1]
```diff
@@ -308,6 +311,83 @@ String OS_Windows::get_version() const {
...
+		return Vector<String>();
+	}
+
+	String object_name = vformat("Win32_PnPSignedDriver.DeviceName = \"%s\"", device_name);
+	// String to wchar_t*
+	char *data = const_cast<char *>(object_name.utf8().get_data());
+	int data_size = sizeof(data) / sizeof(data[0]);
+	int warg_size = MultiByteToWideChar(CP_UTF8, 0, data, data_size, nullptr, 0);
+	wchar_t *object_name_wide = new wchar_t[warg_size];
+	MultiByteToWideChar(CP_UTF8, 0, data, data_size, object_name_wide, warg_size);
```
Comment (bruvzg) [inline platform/windows/os_windows.cpp:348]: In case of Windows, you can convert `String` to `wchar_t *` with built-in `string.utf16().get_data()` (cast result to `LPCWSTR` or whatever API takes).

File: platform/windows/os_windows.cpp [hunk 2]
```diff
@@ -53,6 +53,9 @@
 #include <process.h>
 #include <regstr.h>
 #include <shlobj.h>
+#include <wbemcli.h>
+
+#pragma comment(lib, "wbemuuid.lib")
```
Comment (bruvzg) [inline platform/windows/os_windows.cpp:58]: This should go to the `detect.py` (two places, one for MSVC one for MinGW).

**Review by bruvzg — COMMENTED** [review]
Tested on Windows, and it's not working. I suspect `wbemServices->GetObject()` takes only device path, not a query like `Win32_PnPSignedDriver.DeviceName = "name"`.

`IWbemServices::ExecQuery` probably will work with SQL like query: `SELECT * FROM Win32_PnPSignedDriver WHERE DeviceName="name";`.

**Comment by MJacred** [comment]
I replaced `GetObject` with `ExecQuery`.

Probably works, though I suspect the `HRESULT` of `Next` might be wrong and deliver a more wbem-specific result. The documentation only gives useful feedback if you want more than one result… If this version does not work, then I'll incorporate `WBEM_S_FALSE` and `WBEM_S_TIMEDOUT` ([source](https://learn.microsoft.com/en-us/windows/win32/api/wbemcli/nf-wbemcli-ienumwbemclassobject-next))

File: platform/linuxbsd/os_linuxbsd.cpp [hunk 3]
```diff
@@ -242,6 +246,200 @@ String OS_LinuxBSD::get_version() const {
 	return uts.version;
 }
 
+Vector<String> OS_LinuxBSD::get_video_adapter_driver_info() const {
```
[the remark this answers is not in the document]
Comment (MJacred) [reply platform/linuxbsd/os_linuxbsd.cpp:249]: It won't fail. I use regex as an optional verification. Similar to how it's used for email validation. Not perfect, but better than nothing.  
If regex moduls is disabled, it will simply not verify the return value.

**Comment by MJacred** [comment]
@bruvzg: could you please test on Windows again?

I tried setting up Godot on Windows, but the setup failed and I haven't been able to get it running so far, so testing is currently not possible for me

**Comment by bruvzg** [comment]
> could you please test on Windows again?

It seems to be working, at least with NVIDIA. Retuned value is correct (the same one as in the `Device Manager`), but most users will probably expect driver package version instead (`517.48` in this case, I'm not sure if there is a clean way to get it).

Godot output:
```
["NVIDIA", "31.0.15.1748"]
```

Device Manager:
Screenshot 2022-10-11 061754

NVIDIA Control panel:
Screenshot 2022-10-11 061830

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
> It seems to be working, at least with NVIDIA. Retuned value is correct (the same one as in the `Device Manager`), but most users will probably expect driver package version instead (`517.48` in this case, I'm not sure if there is a clean way to get it).
> 
> Godot output:
> 
> ```
> ["NVIDIA", "31.0.15.1748"]
> ```

The "517.48" version seems to match the last 5 digits of the version reported to Windows. But I don't know if that's stable in future driver versions.

File: platform/linuxbsd/os_linuxbsd.cpp [hunk 4]
```diff
@@ -34,6 +34,10 @@
 #include "main/main.h"
 #include "servers/display_server.h"
 
+#ifdef MODULE_REGEX_ENABLED
```
Comment (akien-mga) [inline platform/linuxbsd/os_linuxbsd.cpp:37]: You need to include `#include "modules/modules_enabled.gen.h"` before this, or it's not guaranteed to be defined.

**Comment by akien-mga** [comment]
Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by MJacred** [comment]
@bruvzg: thanks for testing!  
@akien-mga: included `#include "modules/modules_enabled.gen.h"` beforehand. and commits are squashed

@ both: yeah, no idea why Windows displays the driver version in this format for the user and developer… I think a possible, but quite ugly, workaround would be to check for certain cases, like if the driver name is `nvidia`, then call nvidia control via CLI and request version from there… but not in this PR

**Comment by akien-mga** [comment]
Thanks!

**Comment by Calinou** [comment]
Out of curiosity, why was the method added to OS instead of RenderingServer?

image

**Comment by MJacred** [comment]
I don't remember my reasoning wholly for this, but… thematically speaking, I'd have loved to add it to the RenderingServer.  
The entire reading process depends fully on the operating system, thus I placed it in OS.

The other video adapter info you see in your screenshot is fetched from opengl/vulkan.

Though I'm fully open to moving it to RenderingServer in a way that's non-confusing/-obstrusive. As I'm not that deep into the code architecture, I didn't want to mess with this. Except someone experienced had suggested it while the PR was pending.

**Comment by realkotob** [comment]
@MJacred Great work on this, and my opinion it makes total sense for this to be in on the OS class.

I wouldn't expect the Rendering Server to have an API to show device info for the user, as the OS class already has all the other methods for showing device and OS info.
