### PR TITLE
Highlight selected points in Path3DEditor

### LINKED ISSUE #114686: Curve3D Select Points tool non-functional
### Tested versions

- Reproducible in 4.6.beta2

### System information

macOS 15.0

### Issue description

The `Select Points` tool in the Curve3D toolbar doesn't seem to do anything when I attempt to click+drag on nodes, box select nodes, or shift+click nodes.

- cmd+click to add nodes works
- ctrl+click to delete nodes works

I'm not sure if it's relevant but I'm using a macbook with a trackpad.

### Steps to reproduce

- Add a Path3D to the scene
- Click/click+drag/shift+click furiously to no avail around the points of said path
- Nothing happens
- Sadness

Screen recording of my attempt to click, shift+click, click+drag around nodes to no avail:

https://github.com/user-attachments/assets/599bc21d-2231-4752-b1cd-d51ad812fc3a

### Minimal reproduction project (MRP)

N/A this happens out of the box when creating a Path3D in any empty scene/project, and the fact that there's no open bug for this leads me to believe it's more likely a system-specific issue vs. a general engine bug?

### PR DESCRIPTION
**Pull request by TokageItLab**
- Closes https://github.com/godotengine/godot/issues/114686
- Supersedes/Closes https://github.com/godotengine/godot/pull/114715

In EditMode (behavior dependent on Transform tool), selected points are displayed in blue. Yellow is used for ClosedPath and is difficult to distinguish from white, so I assume blue is fine.

Edit mode with Transform tool:
image

Edit mode with Select tool:
image

Add mode:
image

### CODE REVIEW

File: editor/scene/3d/path_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -103,6 +103,11 @@ void Path3DGizmo::set_handle(int p_id, bool p_secondary, Camera3D *p_camera, con
 		return;
 	}
 
+	Path3DEditorPlugin *pep = Path3DEditorPlugin::singleton;
+	if (!pep) {
```
Comment (AThousandShips) [inline editor/scene/3d/path_3d_editor_plugin.cpp]:
```suggestion
	if (!Path3DEditorPlugin::singleton) {
```
I don't think these temporaries are helpful, it makes it harder to see what `pep` actually is and it doesn't improve any performance, while it technically improves readability by making the lines shorter it worsens it by making you figure out what it is, so I'd say it's a net negative

File: editor/scene/3d/path_3d_editor_plugin.cpp [hunk 2]
```diff
@@ -400,7 +410,11 @@ void Path3DGizmo::redraw() {
 	}
 
 	// 2. Draw handles when selected.
-	if (Path3DEditorPlugin::singleton->get_edited_path() == path) {
+	Path3DEditorPlugin *pep = Path3DEditorPlugin::singleton;
```
Comment (AThousandShips) [inline editor/scene/3d/path_3d_editor_plugin.cpp]: Same here

File: editor/scene/3d/path_3d_editor_plugin.cpp [hunk 3]
```diff
@@ -1021,15 +1048,24 @@ void Path3DGizmoPlugin::redraw(EditorNode3DGizmo *p_gizmo) {
 	ERR_FAIL_NULL(path);
 
 	Ref<Curve3D> curve = path->get_curve();
+	if (curve.is_null()) {
+		return;
+	}
+	Path3DEditorPlugin *pep = Path3DEditorPlugin::singleton;
```
Comment (AThousandShips) [inline editor/scene/3d/path_3d_editor_plugin.cpp]: Same here (especially since not all uses were replaced)

File: editor/scene/3d/path_3d_editor_plugin.cpp [hunk 4]
```diff
@@ -1083,15 +1137,23 @@ int Path3DGizmoPlugin::subgizmos_intersect_ray(const EditorNode3DGizmo *p_gizmo,
...
-				return idx;
+				ret = idx;
+				break;
 			}
 		}
 	}
-	return -1;
+
+	Path3DEditorPlugin *pep = Path3DEditorPlugin::singleton;
+	if (pep) {
```
Comment (AThousandShips) [inline editor/scene/3d/path_3d_editor_plugin.cpp]: Same here

**Comment by ryevdokimov** [comment]
Shouldn't all selected points turn blue or am I missing a reason why only one can be?

**Review by ryevdokimov — APPROVED** [review]
Works, code looks fine to me.

https://github.com/user-attachments/assets/efa7af7e-9748-4f12-9e9c-2a3644c84b90
