### PR TITLE
Fixes sync issue between position_offset and rect_position in GraphNode

### LINKED ISSUE #37780: GraphNode shouldn't allow to change its position (or it should update offset)
**Godot version:**
3.2.1

**Issue description:**
I found it quite confusing that my GraphNode doesn't stay where I put it. Turns out it has `offset` property used for its actual position and changing `rect_position` effectively has no effect (even if it looks like it has). Editing position of this node should be impossible or it should automatically set the `offset`.

### PR DESCRIPTION
**Pull request by theoway**
Fixes #37780 

**Issue**:  `offset` of the graph node wouldn't update and change in the property inspector, when it was moved in editor, only the `position` of `Rect`(property of `Control`) of the graph node changed. As a result, when the scene was played with the graph node in it, the graph node would be positioned according to the unmodified `offset` value.

**Fix**: It turns out when editing in the editor, on moving the graph node, only the `position` was changing, when the `offset` should also have been changing as well. So, I overrode the `_edit_set_position()` method in `Control` class, which is called when `position` of `rect` is changed, and modified it such that it would update the `offset` and notify the change so that the new value of offset will appear in the property inspector as well.

**Results**:
Godot Engine - New Game Project - Control tscn (_) 2020-05-02 18-22-21_Trim

Now the value of the `offset` changes as the graph node is moved/dragged in the editor, along with the change in `position`. And the graph node is positioned according the updated value of offset when the scene is played.

### CODE REVIEW

**Comment by theoway** [comment]
@KoBeWi This branch is building perfectly in my machine without Warning or Errors but Travic-CI is throwing some ambiguous errors. Could you help me with this?

**Comment by KoBeWi** [comment]
You wrapped the declaration using `#ifdef TOOLS_ENABLED`, but you didn't do the same with the `.cpp` file. The failing builds are with TOOLS (editor) disabled.

**Comment by theoway** [comment]
> You wrapped the declaration using `#ifdef TOOLS_ENABLED`, but you didn't do the same with the `.cpp` file. The failing builds are with TOOLS (editor) disabled.

Thank you so much for the prompt reply. So, I have to wrap the definition of the function in `#ifdef TOOLS_ENABLED` then, right?

**Review by KoBeWi — CHANGES_REQUESTED** [review]
The behavior is a bit buggy:
xkwsr059OX
This should be fixed somehow. The edit rectangle should match the node position.

**Comment by theoway** [comment]
@KoBeWi Sorry, I was unavailable for the past few days. I'll make the suggested changes.

**Comment by theoway** [comment]
> Is it me, or do they both look offset from the actual position, just in different, opposite directions?

Yes, there's a constant difference of 40.0f. Weird!

**Comment by theoway** [comment]
The bug was fixed when I had made the pull request. It was a long time back, since then, I can see there have been some changes made to some related modules. That's why, it's showing buggy behavior. Anyways, I'll do some testing and digging and hopefully fix it by tomorrow.

**Comment by theoway** [comment]
@KoBeWi After some digging, `position_offset` and `rect_position` are different things. One should not affect the other.  `position_offset` is relative to `scroll_offset` of `GraphEdit` whereas `rect_position` is relative to `GraphEdit` position. Both are supposed to work differently. In nutshell, I don't think we should consider them one or make them act as one. Your thoughts?

**Comment by pycbouh** [comment]
As stated in the issue this tries to close, `rect_position` doesn't have any effect on a `GraphNode` inside of the `GraphEdit`, and offset must be used. Properly disabling `rect_position` in the Inspector requires https://github.com/godotengine/godot/pull/30623. But what we can fix in this PR is that if the `GraphNode` is moved by hand in the 2D editor and that `GraphNode` is inside of `GraphEdit`, it should update its offset property, not `rect_position`.

**Comment by theoway** [comment]
@pycbouh Yeah, it makes complete sense! Thanks! I'll make the code & documentation changes and update the description of this PR as you've suggested.

**Comment by theoway** [comment]
> xkwsr059OX
@pycbouh Tried working on your suggestion, but it gives rise to this bug. The highlighted rect is drawn with `rect_position`. If it is not updated, it will be stuck at the origin. Although, this will implement what you had in mind, i.e., `position_offset` will be updated and `rect_position` won't be updated, when `GraphNode` is in `GraphEdit`, but it will mess up the drawing of the _editing_ rectangle. 
At this point, I dunno how we should proceed.

**Comment by theoway** [comment]
To solve this issue, we have to update `position_offset` whenever `rect_position` changes. When `rect_position` is updated, `Control` sends this notification: **NOTIFICATION_LOCAL_TRANSFORM_CHANGED**. 
So, I added the piece of code given below to `GraphNode::_notifcation(int)`. 
```
case NOTIFICATION_LOCAL_TRANSFORM_CHANGED: {
			GraphEdit* graph = Object::cast_to<GraphEdit>(get_parent());
			if (graph) {
				position_offset = (get_position() + graph->get_scroll_ofs()) * graph->get_zoom();
			}
		} break;
```
The expected behaviour is when `rect_position` is changed, either via dragging or through typing value in the editor, this should trigger this piece of code, but that is not happening. 
@pycbouh Can you help me with this? If this notification can be received by `GraphNode`, then our problem is solved.

**Comment by KoBeWi** [comment]
@theoway Use `set_notify_local_transform()`

**Comment by pycbouh** [comment]
Okay, https://github.com/godotengine/godot/pull/30623 was actually finally merged, so we can rely on it to prevent rect_position from being edited on GraphNodes inside of GraphEdit for this PR.

**Comment by theoway** [comment]
> Okay, #30623 was actually finally merged, so we can rely on it to prevent rect_position from being edited on GraphNodes inside of GraphEdit for this PR.

Alright, then I'll rebase and start again. Will post my results here.

**Comment by theoway** [comment]
Screenshot (313)_LI

I don't think #30623 is working. I'm still able to edit these properties.

**Comment by KoBeWi** [comment]
#30623 affects children of a container. If you add another node under your GraphNode, it will have disabled properties. The GraphNode itself can be editor normally, because GraphEdit is not a Container.

To prevent GraphNodes position from being edited, you need to check if they are under a GraphEdit and disable the property yourself. However it would still be possible to move them in 2D editor, so you'd have to block that too.

**Comment by theoway** [comment]
**Update**: I've changed the old code and now `position_offset` updates with `rect_position`, correctly according to `scroll_offset` of `GraphEdit`, but the _editing rect_ is showing the same glitchy behaviour, like here:
> xkwsr059OX

**ToDo**: 

- Fix this _edit rectangle_ glitch
- Block direct changes to `rect_position` when `GraphNode` is child of `GraphEdit`.

**PS:** If someone can point out why the edit rectangle is like this, it'll make my job a lil' easy.

**Comment by theoway** [comment]
To make the property read-only, I added this code(given below) to `add_child_notify()` in `GraphEdit.cpp`:
```
#ifdef TOOLS_ENABED
		List<PropertyInfo> *p_list;
		gn->get_property_list(p_list);
		for (List<PropertyInfo>::Element *E = p_list->front(); E; E = E->next()) {
			if (E->get().name == "rect_position") {
				E->get().usage |= PROPERTY_USAGE_READ_ONLY;
				break;
			}
		}
#endif
```

I'm getting a crash as the project is loaded. Kinda stuck here

**Comment by KoBeWi** [comment]
You could use `validate_property()` method for that.

**Comment by theoway** [comment]
> You could use `validate_property()` method for that.

How do I pass the property `rect_position` to `validate_property()`? Is there a _getter_ from which I can get the property reference?

**Comment by KoBeWi** [comment]
`validate_property()` should be called automatically for each property. Then you use the property that it gets as an argument, so in your case you should check if it's `rect_position` and disable it.

File: scene/gui/graph_node.cpp [hunk 1]
```diff
@@ -458,6 +461,27 @@ void GraphNode::_shape() {
 	title_buf->add_string(title, font, font_size, opentype_features, (language != "") ? language : TranslationServer::get_singleton()->get_tool_locale());
 }
 
+#ifdef TOOLS_ENABLED
+void GraphNode::_edit_set_position(const Point2 &p_position) {
+	GraphEdit *graph = Object::cast_to<GraphEdit>(get_parent());
+	if (graph) {
+		Point2 offset = (p_position + graph->get_scroll_ofs()) * graph->get_zoom();
+		set_position_offset(offset);
+		set_position(p_position);
```
Comment (KoBeWi) [inline scene/gui/graph_node.cpp:470]: `set_position()` should be outside this condition, otherwise the node can't be moved if not inside GraphEdit.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
