### PR TITLE
Fix oversampling of DynamicFont fallback fonts

### LINKED ISSUE #22456: Dynamic font oversampling doesn't work with fallback fonts
**Godot version:** 3.1 alpha

**OS/device including version:** Windows 10

**Issue description:**
image

Characters rendered from a fallback font look blurry when scaled up with font oversampling enabled.

Top label uses Noto Sans as the main font and Noto Sans CJK JP as the fallback.
Bottom label uses Noto Sans CJK JP as the main font.

**Steps to reproduce:**
- Enable font oversampling
- Create a dynamic font with a fallback
- Draw a label with characters only present in the fallback font

See attached project for an example.

**Minimal reproduction project:**
[DynFontFallback.zip](https://github.com/godotengine/godot/files/2421516/DynFontFallback.zip)

### PR DESCRIPTION
**Pull request by akerudesu**
Fixes #22456.

### CODE REVIEW

File: scene/resources/dynamic_font.cpp [hunk 1]
```diff
@@ -1083,8 +1083,21 @@ void DynamicFont::update_oversampling() {
 				E->self()->outline_data_at_size->update_oversampling();
 			}
 
+			for (int i = 0; i < E->self()->fallback_data_at_size.size(); i++) {
+				if (E->self()->fallback_data_at_size[i].is_valid()) {
+					DynamicFontAtSize *font = const_cast<DynamicFontAtSize *>(E->self()->fallback_data_at_size[i].ptr());
```
Comment (akien-mga) [inline scene/resources/dynamic_font.cpp]: Is the cast necessary? I think you could use `E->self()->fallback_data_at_size.write[i]->update_oversapling()` instead.

**Comment by akien-mga** [comment]
Thanks!
