### PR TITLE
[RTL] Fix internal process incorrectly disabled on appending text.

### LINKED ISSUE #96701: Using `push_customfx()` after using another `push_[tag]()` causes `char_fx.elapsed_time` to not update
### Tested versions

- Reproducible in v4.4.dev1.official.28a72fa43, v4.3.stable.official

### System information

Godot v4.3.stable - Windows 10.0.19043 - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.21905.1001) - AMD Ryzen 5 5600G with Radeon Graphics (12 Threads)

### Issue description

Pushing a custom rich text effect through code after having already pushed another tag and prior to closing tags with `pop()` or `pop_all()` will cause `char_fx.elapsed_time` to remain 0 for RichTextEffects running in the RichTextLabel the pushes were done to.

### Steps to reproduce

In a script attached to a RichTextLabel, this will cause custom effects that rely on `char_fx.elapsed_time` to not animate:
```gdscript
extends RichTextLabel

func _ready() -> void:
	push_color("green")
	push_customfx(CustomRichtexteffect.new(), {})
	append_text("pushed customfx second")
	pop_all()
```

However, if it's done with `push_customfx()` first, it will work as expected:
```gdscript
extends RichTextLabel

func _ready() -> void:
	push_customfx(CustomRichtexteffect.new(), {})
	push_color("green")
	append_text("pushed customfx first")
	pop_all()
```

### Minimal reproduction project (MRP)

[bug_pushed_customfx.zip](https://github.com/user-attachments/files/16920628/bug_pushed_customfx.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/96701

### CODE REVIEW

**Review by KoBeWi — APPROVED** [review]

**Comment by bruvzg** [comment]
> Is this still needed? (was added in https://github.com/godotengine/godot/pull/39485)

Yes, it's removing `set_process_internal(false)` from `append_text`. #39485 doing it in `append_bbcode`, and doing it inefficiently (disabling it first and scanning for effects after), probably should be changed to remove disabling process as well.

**Comment by bruvzg** [comment]
Updated to remove non-functional https://github.com/godotengine/godot/pull/39485 code, and add similar code to the `remove_paragraph`.

File: scene/gui/rich_text_label.cpp [hunk 1]
```diff
@@ -3412,6 +3412,21 @@ bool RichTextLabel::remove_paragraph(int p_paragraph, bool p_no_invalidate) {
 	selection.click_item = nullptr;
 	selection.active = false;
 
+	if (is_processing_internal()) {
+		set_process_internal(false);
```
Comment (KoBeWi) [inline scene/gui/rich_text_label.cpp:3416]: It's better to do this only when necessary. I'd change the logic to disable process after loop when there is no fx stack.

Comment (bruvzg) [reply scene/gui/rich_text_label.cpp:3416]: Why? This will be less efficient, it will need to run the loop to the end to make sure there are no effects. Currently, it breaks on first effect. And if there were no effects, `is_processing_internal()` will return false, and it will skip the loop at all.

Comment (KoBeWi) [reply scene/gui/rich_text_label.cpp:3416]: Changing process is not trivial.
You can add `bool has_effect`, set it inside the loop and still break. Then only disable process when `has_effect` is false.

**Comment by akien-mga** [comment]
Thanks!
