### PR TITLE
a way to ensure that camera is disabled

### LINKED ISSUE #17570: A way to ensure that camera is disabled completely
**Godot version:**
3.0.1

**Issue description:**
I have implemented split-screen in my game by using viewports and additional cameras.  Each player has its own viewport and camera, and even if only one player is playing, his viewport is in use. The problem is that in my game I have more cameras defined (some of them are for debugging, others are used for raycasting). 
I haven't found any way to disable rendering on main game viewport, so in a result one obsolete camera is rendering completely unnecessary:
disable_cam
_(split screen is scaled down a little, and below can be seen third camera)_

I was expecting that when I will `clear_current` on the camera it will be disabled. And it's true as long as there is only one camera in the main viewport. If there are more cameras in the main viewport then automatically next one will be enabled (so it's simply impossible to disable them all).

**Steps to reproduce:**

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by kubecz3k**
closes #17570 

I think this is the most straightforward way to implement this feature. This pr adds a default parameter to `Camera.clear_current(boolean enable_next_camera = true)`. It can be used to discourage camera from enabling another camera.

### CODE REVIEW

**Comment by robfram** [comment]
You are not conforming your code with the `clang` style which is enforced. If you check out the details of the fail, it states the automatic `clang` formatter want to do this changes for you:
```
-		if(enable_next){
+		if (enable_next) {
```

To be short, you **MUST** separate with a space the parenthesis from the braces.

It is practical add the `hooks` in `git` to have your local `clang` check the code before commiting to ensure `The Travis CI` never fail building. For more info, check the `misc/hooks/` directory in `godot` source code tree.

**Comment by kubecz3k** [comment]
That's quite strange since I have hooks configured and the check said that `Files in this commit comply with the clang-format rules.` Did many prs on this config in the past... will need to investigate this. Thank you

File: scene/3d/camera.cpp [hunk 1]
```diff
@@ -201,15 +201,18 @@ void Camera::make_current() {
 	//get_scene()->call_group(SceneMainLoop::GROUP_CALL_REALTIME,camera_group,"_camera_make_current",this);
 }
 
-void Camera::clear_current() {
+void Camera::clear_current(bool enable_next) {
```
Comment (akien-mga) [inline scene/3d/camera.cpp]: Please name parameters with a `p_` prefix, so `p_enable_next` (also in the header, but not in the binding).

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we don't plan to cherry-pick new features and enhancements to the 3.0 branch, unless there is very strong support in favor of it. Removing cherrypick label for 3.0.
