### PR TITLE
Sort points in a Gradient for color and offset updates.

### LINKED ISSUE #41136: Add new Color points to Gradient in gdscrip results in wrong ramp
**Godot version:**

Godot Engine v3.2.2.stable.mono.official - https://godotengine.org
OpenGL ES 2.0 Renderer: GeForce GTX 980/PCIe/SSE2
OpenGL ES 2.0 Batching: ON

**OS/device including version:**
Windows 10 

**Issue description:**
I try to use Gradient in a godot script to build a Color ramp from  [green]->[red]->[blue]
The result is [green]->[blue]->[red] but should be [green]->[red]->[blue]

**Steps to reproduce:**
```
class TileIdToColorMapper extends Object:
	var _gradient:Gradient = Gradient.new()
	
	func _init():
		_gradient.add_point(0.5, Color.red)
		print(_gradient.get_point_count())
		# set ramp
		_gradient.set_color(0, Color.green)
		_gradient.set_color(1, Color.red)
		_gradient.set_color(2, Color.blue)
		
		
		prints(_gradient.interpolate(_gradient.get_offset(0)), "index", 0, "offset", _gradient.get_offset(0))
		prints(_gradient.interpolate(_gradient.get_offset(1)), "index", 1,"offset", _gradient.get_offset(1))
		prints(_gradient.interpolate(_gradient.get_offset(2)), "index", 2, "offset", _gradient.get_offset(2))
		prints("all offsets:", _gradient.offsets)
```
the output are
```
3
0,1,0,1 index 0 offset 0
0,0,1,1 index 1 offset 0.5
1,0,0,1 index 2 offset 1
all offsets: [0, 0.5, 1]
```
The result is [green]->[blue]->[red] but should be [green]->[red]->[blue]

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by somnathsarkar**
Fixes #41136

Points in a Gradient are now sorted by offset if required for each `get_offset`, `set_offset`, `get_color` and `set_color` call, instead of only during `interpolate` calls.

### CODE REVIEW

**Comment by Calinou** [comment]
Out of curiosity, have you tested the gradient editor after this change? Does it behave as expected? (You can test it by creating a Gradient resource in the Inspector dock.)

File: scene/resources/gradient.cpp [hunk 1]
```diff
@@ -145,13 +145,21 @@ void Gradient::set_offset(int pos, const float offset) {
 	if (points.size() <= pos) {
 		points.resize(pos + 1);
 	}
+	if (!is_sorted) {
+		points.sort();
+		is_sorted = true;
+	}
```
Comment (pouleyKetchoupp) [inline scene/resources/gradient.cpp:151]: Could you put this block in a private method like `update_sorting` to avoid repeating it? In case some changes are needed later it will be just in one place.

**Comment by somnathsarkar** [comment]
@Calinou yes, it appears to behave as expected in the inspector window and using GDScript.

I noticed there is existing code that triggers if there is an attempt to set an offset or color at a position greater than the number of points:

```
if (points.size() <= pos) {
	points.resize(pos + 1);
	is_sorted = false;
}
```

This behaviour doesn't seem very intuitive and works unexpectedly with the "fixed" sorting technique, since the new points created each have an offset of 0. I would think it would be better to throw an error in this case as the `get_color` and `get_offset` methods already do?

File: scene/resources/gradient.cpp (hunk 1 above)
Comment (somnathsarkar) [reply scene/resources/gradient.cpp]: @pouleyKetchoupp I've fixed this and updated the `get_color_at_offset` function to call the new method as well.

**Comment by pouleyKetchoupp** [comment]
> This behaviour doesn't seem very intuitive and works unexpectedly with the "fixed" sorting technique, since the new points created each have an offset of 0. I would think it would be better to throw an error in this case as the get_color and get_offset methods already do?

I agree an error would be better. The way `set_color` works for an index out of bounds doesn't make a lot of sense, even before your changes, and the behavior is not documented anyway. Users should always call `add_point` for this case.

File: scene/resources/gradient.cpp [hunk 2]
```diff
@@ -144,14 +144,16 @@ void Gradient::set_offset(int pos, const float offset) {
 	ERR_FAIL_COND(pos < 0);
 	if (points.size() <= pos) {
 		points.resize(pos + 1);
+		is_sorted = false;
 	}
+	_update_sorting();
```
Comment (pouleyKetchoupp) [inline scene/resources/gradient.cpp:149]: It seems the update should be after `points.write[pos].offset = offset;`, otherwise the offset might be set on the wrong point.

**Comment by somnathsarkar** [comment]
@pouleyKetchoupp Thanks for the update, I've made the necessary changes.

File: scene/resources/gradient.cpp (hunk 2 above)
Comment (somnathsarkar) [reply scene/resources/gradient.cpp:145]: I think calling `_update_sorting()` before setting the point and setting `is_sorted=false` after is the right way to handle this.

File: scene/resources/gradient.cpp [hunk 3]
```diff
@@ -141,35 +141,39 @@ void Gradient::set_points(Vector<Gradient::Point> &p_points) {
...
 	ERR_FAIL_INDEX_V(pos, points.size(), Color());
+	_update_sorting();
 	return points[pos].color;
 }
 
 int Gradient::get_points_count() const {
 	return points.size();
 }
+
+void Gradient::_update_sorting() {
```
Comment (pouleyKetchoupp) [inline scene/resources/gradient.cpp:174]: Could you move `_update_sorting` to the header with `_FORCE_INLINE_` like `get_color_at_offset` does? That would help keeping `get_color_at_offset` optimized.

**Comment by pouleyKetchoupp** [comment]
Just tested a Gradient property in the editor on my side and it works as expected. After this last change for inline it will be good for me.

**Comment by somnathsarkar** [comment]
@pouleyKetchoupp Great, I've made the changes.

**Review by pouleyKetchoupp — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
