### PR TITLE
[46188] fix: get unix from datetime when empty dict

### LINKED ISSUE #46188: Godot freeze when executing OS.get_unix_time_from_datetime({})
**Godot version:**
Godot 3.2.4 rc 2

**Issue description:**
Executing
```
OS.get_unix_time_from_datetime({})
```
freeze entire project, until I kill them

### PR DESCRIPTION
**Pull request by ghost**
As discussed in #46902 , opened on master @Calinou with error message.

Fixing `get_unix_from_datetime` engine freeze when the dictionary is empty. If so, it returns `0`.

*Bugsquad edit:* fixes #46188.

### CODE REVIEW

File: core/core_bind.cpp [hunk 1]
```diff
@@ -373,6 +373,10 @@ Dictionary _OS::get_time(bool utc) const {
  * @return epoch calculated
  */
 int64_t _OS::get_unix_time_from_datetime(Dictionary datetime) const {
+
+	// if datetime is an empty Dictionary throws an error
```
Comment (akien-mga) [inline core/core_bind.cpp:377]: The first empty line should be removed to match the style guide (for `master` - in `3.2` we did use to have such empty lines at the start of functions but we changed that style).

Comment (akien-mga) [reply core/core_bind.cpp:377]: Please do the changes with `git commit --amend` to avoid creating a new commit for this style fix. (And then you can force push to update your branch and this PR.)

Comment (unsignedFoo) [reply core/core_bind.cpp:377]: sure!

Comment (unsignedFoo) [reply core/core_bind.cpp]: done

Comment (unsignedFoo) [reply core/core_bind.cpp]: note that this cannot be cherry-picked to current 3.2.4 because `dictionary.is_empty()` in `master` is `dictionary.empty()` on that release.

Comment (akien-mga) [reply core/core_bind.cpp]: That's fine, I can fix that when cherry-picking.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
