### PR TITLE
More fixes to over plugin handling

### LINKED ISSUE #72738: [v4.0beta17] gizmo stuck when switching between CollisionShape2D instances
### Godot version

v4.0.beta17.mono.official [c40020513]

### System information

Windows11,Godot Mobile backend

### Issue description

https://user-images.githubusercontent.com/15378256/216791307-138e2206-f841-42b4-a9b2-b374da97affc.mp4

When selecting different CollisionShape2Ds, only the first selected gizmo is active and can be used even when selecting different   CollisionShape2D

### Steps to reproduce

Same root, 2 or more CollisionShape2Ds.

Minimal reproduction project uploaded, simply run editor and select between the CollisionShape2Ds.

### Minimal reproduction project

[bug1.zip](https://github.com/godotengine/godot/files/10609753/bug1.zip)

### LINKED ISSUE #72773: EditorPlugin input forwarding unexpected behavior
### Godot version

v4.0.beta17.official [c40020513]

### System information

Windows 10

### Issue description

GDScript-based `EditorPlugin` addons end up forwarding their input in unexpected ways as different nodes are selected. The plugin's input handling remains active despite `_handles()` no longer returning true. Furthermore, duplicate `EditorPlugin._forward_3d_gui_input()` calls (and similar methods) occur when the bug is triggered, piling up each time it happens, and persisting until Godot is rebooted.

Switching the selection between node types handled by different plugins each seems to trigger this issue consistently, and a minimal reproduction project to accomplish this is provided.

### Steps to reproduce

1. Create a new project.
2. Create 2 `EditorPlugin` GDScript addons, and filter their `_handles()` with different node types.
3. Create a few nodes, 2 of which match the aforementioned `_handles()`.
4. Repeatedly switch the selection on the node tree, and measure their input forwarding (For example, by using `_forward_3d_gui_input()`).

### Minimal reproduction project

[EditorPlugin Input Forwarding Bug.zip](https://github.com/godotengine/godot/files/10613798/EditorPlugin.Input.Forwarding.Bug.zip)

Scroll the mousewheel while having a `Marker3D` or a `Path3D` node selected to debug-print, and then switch to the other one and also scroll the mousewheel. Keep switching selections forth and back to keep triggering the bug.

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes yet another issue with "over plugins". I added `_plugin_over_edit()` method, because after checking how these plugins are invoked, they pretty much repeat the same 3 lines every time.

Fixes #72773
Fixes #72738
I can't reproduce #72761 and #72744, but they might get fixed too. CC @smix8

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -2102,8 +2114,7 @@ void EditorNode::edit_item(Object *p_object, Object *p_editing_owner) {
 			if (!item_plugins.has(plugin)) {
 				// Remove plugins no longer used by this editing owner.
 				to_remove.push_back(plugin);
-				plugin->make_visible(false);
-				plugin->edit(nullptr);
+				_plugin_over_edit(plugin, nullptr);
```
Comment (YuriSizov) [inline editor/editor_node.cpp:2117]: I assume it is desirable to remove the plugin here (a new side-effect of using the common method)?

Comment (YuriSizov) [reply editor/editor_node.cpp:2117]: Yes, what I mean, previous version of this bit of code didn't do it. This version does, because `_plugin_over_edit()` does that unconditionally. So I'm just checking that this is a desirable change.

Comment (KoBeWi) [reply editor/editor_node.cpp:2117]: Yes, this was the cause of the first linked issue.

**Comment by akien-mga** [comment]
Thanks!
