### PR TITLE
Fix false positive "Unreachable code" warning for loops

### LINKED ISSUE #35775: False positive "Unreachable code" warning (for loop)
**Godot version:**

3.2.0

**OS/device including version:**

Ubuntu 19.10

**Issue description:**

Having an unconditional return in a for loop triggers an unreachable code warning when there is more code after the loop. This is not correct, because the loop condition may never be fulfilled (e.g. iterating over an empty array).

Note: I am aware that the example code below doesn't make any sense. I simplified it to the bare minimum that still shows the bug.

**Steps to reproduce:**

Paste the following code into any GDScript:

```
func test():
    var a = []
    for b in a:
        return b
    return null
```

**Minimal reproduction project:**

Not useful in this case IMO. Pasting the code into a script is quicker than downloading a project.

### PR DESCRIPTION
**Pull request by yamgent**
Fix #35775. It will fix erroneous reports in these two cases:

```gdscript
func a():
	var arr = []
	for i in arr:
		return i
	# can be reached, but buggy analysis says cannot
	return -1

func b():
	var should_loop = false
	while should_loop:
		return 1
	# can be reached, but buggy analysis says cannot
	return 0
```

### CODE REVIEW

**Comment by cgbeutler** [comment]
Would this, by chance, fix using `continue`s as well? The below give the warning:

```gdscript
for i in 100:
	continue
	return 1
# warning here
return 0
```

**Comment by akien-mga** [comment]
@cgbeutler The warning line might be off by one, the `return 1` in your example *is* unreachable.

**Comment by cgbeutler** [comment]
I did kinda over simplify, but the issue is still there. In my real code I loop over a range of profile IDs in search of a usable one. It looked cleaner to continue from the various fail conditions and only return if all checks passed. Sadly, I get the false warning that makes it not-so-clean.

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -3060,7 +3060,7 @@ void GDScriptParser::_parse_block(BlockNode *p_block, bool p_static) {
 				current_block = p_block;
 				if (error_set)
 					return;
-				p_block->has_return = cf_while->body->has_return;
+				p_block->has_return = false; // while body may never execute
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp]: `has_return` is already `false` by default, you can just remove the line. Resetting it to `false` may be wrong if there was a `return` before the `while` statement.

File: modules/gdscript/gdscript_parser.cpp [hunk 2]
```diff
@@ -3190,7 +3190,7 @@ void GDScriptParser::_parse_block(BlockNode *p_block, bool p_static) {
 
 				if (error_set)
 					return;
-				p_block->has_return = cf_for->body->has_return;
+				p_block->has_return = false; // for body may never execute
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp]: Same as above.

**Review by vnen — CHANGES_REQUESTED** [review]

**Comment by yamgent** [comment]
@vnen Fixed! Apologies for the delay, been pretty busy lately.

 @cgbeutler I tested a variant of your example and it seems to work, so I hope it solves your issue.

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.
