### PR TITLE
Fix addon requires editor restart to become functional

### LINKED ISSUE #92493: Addon requires editor restart to become functional
### Tested versions

4.3 dev6
any version tbh

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Technically part of #84811
I have a plugin with example project. When you download it and open, on first launch it will not be functional. The custom screen is empty and spams errors. You can disable and enable the addon, but it doesn't help.

My current workaround is automatic restart of the editor, as there is no other way to make it work.

### Steps to reproduce

1. Download zip of this branch: https://github.com/KoBeWi/Metroidvania-System/tree/bug_branch
2. Open the included project
3. Once it loads, go to MetSys main screen
4. The screen is empty and spams errors in the output

### Minimal reproduction project (MRP)

See above.

### LINKED ISSUE #94546: Godot 4.3 Beta 3 - Failed loading resource , wav files and assigning it to export var
### Tested versions

- Reproducible in Godot 4.3 beta 3

### System information

Windows 11

### Issue description

When importing wav files and assigning them to export var AudioStreamWAV in script that runs in autoload will cause an error when opening the project without .godot
image

### Steps to reproduce

1. Create a new godot 4.3 beta 3 project
2. Create a Play scene (could be a just control node)
3. Create a folder SoundManager.
4. Create another scene of type control and add a child of type AutoStreamPlayer
5. Add a script to the control node and write these lines
```
extends Node

@export var clockTickingsfx: AudioStreamWAV
@export var clockCompleteSfx: AudioStreamWAV
@export var sfxAudioStream: AudioStreamPlayer
```
6. Create a folder inside SoundManager and import a wav file and assign it to both clockCompleteSfx and clockTickingsfx. and assign AutoStreamPlayer to sfxAudioStream
7. Add in Autoload the control scene and you can call it SoundManager
8. Click on play and select the Play Scene as default sene
9. Save, Close godot , delete .godot folder and open it again.
10. Look at the Output and you will see 
image

### Minimal reproduction project (MRP)

[TestImportCurropted.zip](https://github.com/user-attachments/files/16316703/TestImportCurropted.zip)

### PR DESCRIPTION
**Pull request by Hilderin**
- Fixes #92493
- Fixes #94546

The idea is that some resources are needed on startup before the reimportation of missing resources in cache but we cannot move the addon loading after the reimportation because addons can have custom importers, but what if the ResourceLoader could in that situation import on the fly the missing resources while loading the addons?

I tried that idea with the MRP from https://github.com/KoBeWi/Metroidvania-System/tree/bug_branch (thanks @KoBeWi) and it seems to work. IMPORTANT: to load this project without any errors, you need https://github.com/godotengine/godot/pull/92303. To make it work only with this PR, the global_script_class_cache.cfg must be present in the .godot folder.

Note: This is more a potential workaround from the current circular problem where addons need resources but resource needs addons.

One limitation of this solution is if an addon needs a resource from a custom importer, it will fail or use the default importer.
Another limitation is that there is no progress bar or loading indicator while importing resources before the first scan, so if an addon needs a lot of resources, the editor could be unresponsive for quite some time.

To see it in action:

https://github.com/godotengine/godot/assets/81109165/250191c3-03c0-4465-863c-adf9c9982df9

### CODE REVIEW

**Comment by Hilderin** [comment]
Rebased following merge conflicts.

**Comment by reduz** [comment]
The problem of this approach is that in a large project, scanning everything seems kind of overkill. EditorFileSystem is specially optimized to only scan files that change, so large projects function fine.

Maybe taking a different approach where only modified files reported by EditorFileSystem are scanned?

File: core/error/error_macros.cpp [hunk 1]
```diff
@@ -83,6 +88,9 @@ void _err_print_error(const char *p_function, const char *p_file, int p_line, co
 
 // Main error printing function.
 void _err_print_error(const char *p_function, const char *p_file, int p_line, const char *p_error, const char *p_message, bool p_editor_notify, ErrorHandlerType p_type) {
+	if (!error_log_enabled) {
```
Comment (KoBeWi) [inline core/error/error_macros.cpp:91]: That looks like a hack. Not sure if it's necessary.
Though first scan errors aren't really useful, so it's not like this change is pointless.

File: core/io/resource_importer.cpp [hunk 2]
```diff
@@ -126,22 +129,45 @@ Error ResourceFormatImporter::_get_path_and_type(const String &p_path, PathAndTy
...
 #ifdef TOOLS_ENABLED
 	if (res.is_valid()) {
 		res->set_import_last_modified_time(res->get_last_modified_time()); //pass this, if used
 		res->set_import_path(pat.path);
+	} else if (can_retry && EditorFileSystem::get_singleton()->doing_first_scan()) {
+		can_retry = false;
+		set_error_log_enabled(true);
+		err = EditorFileSystem::get_singleton()->import_file(p_path, false);
+		if (err == OK) {
+			goto retry;
```
Comment (KoBeWi) [inline core/io/resource_importer.cpp:165]: 💀

File: editor/editor_file_system.cpp [hunk 3]
```diff
@@ -2046,14 +2046,20 @@ Error EditorFileSystem::_reimport_group(const String &p_group_file, const Vector
 	return err;
 }
 
-Error EditorFileSystem::_reimport_file(const String &p_file, const HashMap<StringName, Variant> &p_custom_options, const String &p_custom_importer, Variant *p_generator_parameters) {
+Error EditorFileSystem::import_file(const String &p_file, bool p_update_file_system) {
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:2049]: The second argument name does not match declaration.

File: core/io/resource_importer.cpp (hunk 2 above)
Comment (Hilderin) [reply core/io/resource_importer.cpp:165]: I guess you don't like the goto?? I saw that elsewhere in the base code so I used it, but I'll change it!

Comment (KoBeWi) [reply core/io/resource_importer.cpp:165]: Well `goto` is generally frowned upon. The Godot code that uses it is likely very old.

File: core/error/error_macros.cpp (hunk 1 above)
Comment (Hilderin) [reply core/error/error_macros.cpp]: I used `CoreGlobals::print_error_enabled` instead. I found out about that yesterday.

File: core/io/resource_importer.cpp [hunk 4]
```diff
@@ -34,6 +34,9 @@
 #include "core/io/config_file.h"
 #include "core/os/os.h"
 #include "core/variant/variant_parser.h"
+#ifdef TOOLS_ENABLED
+#include "editor/editor_file_system.h"
```
[the remark this answers is not in the document]
Comment (Hilderin) [reply core/io/resource_importer.cpp:38]: Managed to invert to dependency.

File: core/io/resource_importer.cpp (hunk 2 above)
Comment (Hilderin) [reply core/io/resource_importer.cpp]: Used a while instead.

File: editor/editor_file_system.cpp (hunk 3 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp:2057]: Done!

File: core/error/error_macros.cpp (hunk 1 above)
Comment (Hilderin) [reply core/error/error_macros.cpp]: Nope, if I add a check on `CoreGlobals::print_error_enabled` in `_err_print_error`, a lot of unit test fail. I put back `error_log_enabled` but renamed it `print_error_enabled` to be more accurate.

File: core/io/resource_importer.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (KoBeWi) [reply core/io/resource_importer.cpp:38]: The include is still there though...

[the remark this answers is not in the document]
Comment (Hilderin) [reply core/io/resource_importer.cpp]: Oups, my bad, I removed it.

File: core/io/resource_loader.h [hunk 5]
```diff
@@ -254,6 +257,19 @@ class ResourceLoader {
 	static void set_abort_on_missing_resources(bool p_abort) { abort_on_missing_resource = p_abort; }
 	static bool get_abort_on_missing_resources() { return abort_on_missing_resource; }
 
+	static void set_reimport_file_on_failed_load(bool p_reimport_file_on_failed_load) { reimport_file_on_failed_load = p_reimport_file_on_failed_load; }
+	static bool get_reimport_file_on_failed_load() { return reimport_file_on_failed_load; }
+	static void set_reimport_file_func(ResourceLoaderImportFile p_import_file) {
+		import_file = p_import_file;
+	}
+	static Error reimport_file(const String &p_path, bool p_update_file_system) {
```
Comment (KoBeWi) [inline core/io/resource_loader.h:265]: Unused.

**Review by KoBeWi — APPROVED** [review]
Works, but could use some testing in a complex 3D project with import plugins and stuff.

File: core/io/resource_loader.h (hunk 5 above)
Comment (Hilderin) [reply core/io/resource_loader.h]: I removed the reimport_file method and added a check in `ResourceFormatImporter::load` to be sure `ResourceLoader::import_file` is not null before calling it.

**Comment by dsnopek** [comment]
I tested this with a project that has node types from a GDExtension in its main scene. I deleted the `.godot` directory, and then opened in an editor built with this PR and it seems to work! All the nodes were present in the scene, and seemed to work normally (which isn't the case without this PR - I usually need to open the Godot editor twice).

However, I'm still getting a bunch of errors about the GDExtension classes to the console as the editor starts up:

```
ERROR: Cannot get class 'OpenXRFbPassthroughExtensionWrapper'.
   at: set_object_extension_instance (core/object/class_db.cpp:639)
ERROR: Cannot get class 'OpenXRFbRenderModelExtensionWrapper'.
   at: set_object_extension_instance (core/object/class_db.cpp:639)
ERROR: Cannot get class 'OpenXRFbSceneCaptureExtensionWrapper'.
   at: set_object_extension_instance (core/object/class_db.cpp:639)
ERROR: Cannot get class 'OpenXRFbSpatialEntityExtensionWrapper'.
   at: set_object_extension_instance (core/object/class_db.cpp:639)
ERROR: Cannot get class 'OpenXRFbSpatialEntityQueryExtensionWrapper'.
   at: set_object_extension_instance (core/object/class_db.cpp:639)
ERROR: Cannot get class 'OpenXRFbSpatialEntityContainerExtensionWrapper'.
   at: set_object_extension_instance (core/object/class_db.cpp:639)
ERROR: Cannot get class 'OpenXRFbSceneExtensionWrapper'.
   at: set_object_extension_instance (core/object/class_db.cpp:639)
ERROR: Cannot get class 'OpenXRFbHandTrackingAimExtensionWrapper'.
   at: set_object_extension_instance (core/object/class_db.cpp:639)
ERROR: Cannot get class 'OpenXRFbHandTrackingCapsulesExtensionWrapper'.
   at: set_object_extension_instance (core/object/class_db.cpp:639)
ERROR: Cannot get class 'OpenXRFbCompositionLayerSettingsExtensionWrapper'.
   at: set_object_extension_instance (core/object/class_db.cpp:639)
ERROR: Cannot get class 'OpenXRHtcFacialTrackingExtensionWrapper'.
   at: set_object_extension_instance (core/object/class_db.cpp:639)
ERROR: Cannot get class 'OpenXRHtcPassthroughExtensionWrapper'.
   at: set_object_extension_instance (core/object/class_db.cpp:639)
ERROR: GDScript bug: Native class "OpenXRFbRenderModel" not found.
   at: _gdtype_from_datatype (modules/gdscript/gdscript_compiler.cpp:123)
ERROR: GDScript bug: Native class "OpenXRFbRenderModel" not found.
   at: _gdtype_from_datatype (modules/gdscript/gdscript_compiler.cpp:123)
ERROR: GDScript bug: Native class "OpenXRFbRenderModel" not found.
   at: _gdtype_from_datatype (modules/gdscript/gdscript_compiler.cpp:123)
ERROR: GDScript bug: Native class "OpenXRFbRenderModel" not found.
   at: _gdtype_from_datatype (modules/gdscript/gdscript_compiler.cpp:123)
ERROR: GDScript bug: Native class "OpenXRFbRenderModel" not found.
   at: _gdtype_from_datatype (modules/gdscript/gdscript_compiler.cpp:123)
ERROR: GDScript bug: Native class "OpenXRFbRenderModel" not found.
   at: _gdtype_from_datatype (modules/gdscript/gdscript_compiler.cpp:123)
ERROR: GDScript bug: Native class "OpenXRFbRenderModel" not found.
   at: _gdtype_from_datatype (modules/gdscript/gdscript_compiler.cpp:123)
ERROR: Cannot get class 'OpenXRFbHandTrackingMeshExtensionWrapper'.
   at: set_object_extension_instance (core/object/class_db.cpp:639)
ERROR: In Object of type 'OpenXRExtensionWrapperExtension': Attempt to connect nonexistent signal 'openxr_fb_hand_tracking_mesh_data_fetched' to callable '<CallableCustom>'.
   at: connect (core/object/object.cpp:1423)
ERROR: In Object of type 'OpenXRExtensionWrapperExtension': Attempt to connect nonexistent signal 'openxr_fb_hand_tracking_mesh_data_fetched' to callable '<CallableCustom>'.
   at: connect (core/object/object.cpp:1423)
ERROR: In Object of type 'OpenXRExtensionWrapperExtension': Attempt to connect nonexistent signal 'openxr_fb_hand_tracking_mesh_data_fetched' to callable '<CallableCustom>'.
   at: connect (core/object/object.cpp:1423)
```

Everything does still _seem_ to work, though.

**Comment by Hilderin** [comment]
I don't think this PR should fix that, this PR is fixing a problem when an autoload or a plugin tries to access a resource before the first scan. Were you talking about: #93972 ? In the MRP a linked with the PR, there is a node of the type Example from a GDExtension in the main scene and I'm not able to reproduce the problem you mention with the code from #93972.

**Comment by Hilderin** [comment]
Rebased from master to fix a merge conflict.

**Comment by akien-mga** [comment]
Could use a rebase for good measure as we've merged a lot of changes lately. I'll try to test soon myself.

**Comment by Hilderin** [comment]
Rebased done! I retested with the MRP project from the 2 issues linked in the PR descriptions. The project loaded perfectly without any error and I saw that the added code was executed as expected.

**Comment by akien-mga** [comment]
I tested on a few projects and confirmed that this seems to work well :tada: 

I'm slightly concerned that the implementation looks a bit hacky though, with silencing error messages, and retry/loop shenanigans in editor only code. I'm not very familiar with that code so it's hard to assess whether there's a good approach, though. Could be good to have some extra input from @reduz and @RandomShaper.

**Comment by reduz** [comment]
I think on the general level this PR is ok, but I don't feel very comfortable having import logic at core level. Maybe what we could do is have a function pointer that is set to ResourceImporter to do this logic and implement it effectively in EditorFileSystem so we have it a bit more centralized and don't have actual import code in core.

**Comment by Hilderin** [comment]
I made significant refactoring following the suggestions of @reduz. I hope I understood correctly your suggestion.

The logic of the import and retry is now in `EditorFileSystem`. I kept the modifications in `ResourceFormatImporter::load` at the minimum so the code for the retry is executed only on startup during the first scan. I think that way the code is better encapsulated and easier to understand while maintaining the functionality.

File: editor/editor_file_system.cpp [hunk 6]
```diff
@@ -2879,6 +2886,38 @@ Error EditorFileSystem::_resource_import(const String &p_path) {
...
+	// Disable error output to prevent displaying all the errors from accessing resource
+	// that are not yet loaded.
+	set_print_error_enabled(false);
+
+	bool can_retry = true;
+	bool retry = true;
+	while (retry) {
+		retry = false;
+
+		res = p_importer->load_internal(p_path, p_original_path, r_error, p_use_sub_threads, r_progress, p_cache_mode);
```
Comment (akien-mga) [inline editor/editor_file_system.cpp:2902]: Instead of disabling all error print engine wide, can't we pass a bool here that will prevent printing errors in `ResourceLoader::_load`? So we keep the impact to only this code path.

Comment (Hilderin) [reply editor/editor_file_system.cpp:2902]: I tried that and there are error print all over the code. Maybe something the could be done to make it less "hacky" is to transform the toogle that removes error print in a toggle that prints warnings or redirect errors into EditorFileSystem and add a print saying something like "Errors while loading resource for the first time, reimporting and retrying..." ??

File: editor/editor_file_system.cpp [hunk 7]
```diff
@@ -2879,6 +2886,38 @@ Error EditorFileSystem::_resource_import(const String &p_path) {
...
+
+		if (!res.is_valid() && can_retry) {
```
Comment (AThousandShips) [inline editor/editor_file_system.cpp:2904]:
```suggestion
		if (res.is_null() && can_retry) {
```

Comment (Hilderin) [reply editor/editor_file_system.cpp]: Good point, thanks. Done!

**Review by ryevdokimov — APPROVED** [review]
I can confirm this resolves this issue: https://github.com/godotengine/godot/pull/93972#issuecomment-2322319983

@TokisanGames

File: editor/editor_file_system.cpp (hunk 6 above)
Comment (akien-mga) [reply editor/editor_file_system.cpp:2902]: Actually the `FileAccess:::exists` check I put in `ResourceLoader:::_load` could be moved further up the call stack, before trying to call `load_internal` in EditorFileSystem.

If we already know the file doesn't exist at this stage, there's no point involving ResourceLoader.

Comment (Hilderin) [reply editor/editor_file_system.cpp]: I like your suggestion. Usually, the problem was that the file in the `.godot` folder did not exist on startup. There may be other situations where reimportation is necessary to successfully load the resource on startup (e.g., if a custom loader changed or was removed), but in the worst case, an error will be printed, and the project should still load correctly. I'm okay with this suggestion and we will see when users find and report any issues.

To make it work with the MRP from #94546, I adjusted the code to check if `pat.path` exists. `p_path` corresponds to the original `.wav` file, and `pat.path` corresponds to the internal `.sample` file in the `.godot` folder. The check is done after `_get_path_and_type`, which checks if the `.import` file exists. If the `.import` file does not exist, `_get_path_and_type` simply returns an error without printing anything, which is great. Additionally, I ensure that `FileAccess::exists` is only checked if `p_silence_errors` is true, to avoid affecting resource loading performance at runtime.

As suggested, I moved the `FileAccess::exists` check on `p_path` directly to the beginning of `EditorFileSystem::_load_resource_on_startup`, which should prevent attempting to load a resource twice if it does not exist.

I also removed the `p_original_path` parameter in `EditorFileSystem::_load_resource_on_startup` because it was never used in `ResourceFormatImporter::load_internal`. In fact, it's not even used in `ResourceFormatImporter::load`, but I guess that's okay since it's a virtual method.

File: editor/editor_file_system.cpp [hunk 8]
```diff
@@ -2879,6 +2886,33 @@ Error EditorFileSystem::_resource_import(const String &p_path) {
 	return OK;
 }
 
+Ref<Resource> EditorFileSystem::_load_resource_on_startup(ResourceFormatImporter *p_importer, const String &p_path, Error *r_error, bool p_use_sub_threads, float *r_progress, ResourceFormatLoader::CacheMode p_cache_mode) {
+	ERR_FAIL_NULL_V(p_importer, Ref<Resource>());
+
+	if (!FileAccess::exists(p_path)) {
+		ERR_FAIL_V_MSG(Ref<Resource>(), vformat("Failed loading resource: %s. The file doesn't seem to exist.", p_path));
+	}
```
Comment (akien-mga) [inline editor/editor_file_system.cpp:2894]: Is this still needed/relevant given the added check on `pat.path` in `load_internal`?

It does sound relevant to raise an error here if we're attempting to load a source file which doesn't exist at all, but does that situation actually happen on startup load?

Shouldn't hurt to check for good measure anyway as this situation would be a bug, but if we're concerned about the performance impact of a file existence check, this could be reconsidered.

**Review by akien-mga — APPROVED** [review]
Looks great to me! And we really minimized the impact on the core, which is nice :)

Amazing work, this solves such a huge pain point! :tada:

**Comment by akien-mga** [comment]
Thanks!

**Comment by LucaVazz** [comment]
Thank you all for working on this fix 🙁

Would it be possible to backport this fix for a 4.3 patch release?
The underlying issue currently is a blocker to use the 4.3 release in a CI workflow when using addons.

**Comment by GreenCrowDev** [comment]
As already requested earlier, is it posible to cherry pick this for a 4.3 patch?
Has this already been done? I'm not sure how to check.

**Comment by matheusmdx** [comment]
@LucaVazz @GreenCrowDev Generally when the pr can be cherry-picked a tag is add to sign that but in any moment this label was aded so probably this pr is too risky to be cherry-picked, require extra work for do it or simply is incompatible with old versions. From the fact a lot of people worked on that and no one cited nothing about cherry-pick probably this can't be cherry-picked (or everyone just forgot that).

**Comment by domdfcoding** [comment]
I successfully cherry-picked the commit to 4.3 with just one conflict (the line before a change was added in 4.4 and confuses git). Compiles OK and seems to fix the issue with font fallbacks. If anyone other than me still cares about 4.4.
