### PR TITLE
Fix unwanted resource duplication in the theme editor

### LINKED ISSUE #80797: Copying and pasting styles in a `Theme` creates new ones instead of reusing them
### Godot version

4.0.dev [5444afa]

### System information

N/A

### Issue description

When copying and pasting a `StyleBox*` resource from one item to another inside a `Theme` resource, instead of making both items use the same one, it just creates a new replica of it.

### Steps to reproduce

- Create a new `Theme` resource and save it to a file.
- Give any item a `StyleBox*` resource, then copy and paste it to another one.
- Save, and then open the `Theme`'s file, and see that two different resources are in use.

### Minimal reproduction project

N/A, trivially reproducible.

### PR DESCRIPTION
**Pull request by YeldhamDev**
This PR makes use of the `resource_owner` functionality in the `EditorResourcePicker` to check not only if the copied resource is from another scene, but also from another parent resource before automatically making it unique.

Fixes #80797.

### CODE REVIEW

File: editor/inspector/editor_resource_picker.cpp [hunk 1]
```diff
@@ -441,23 +441,36 @@ void EditorResourcePicker::_edit_menu_cbk(int p_which) {
...
+				_resource_changed();
 				return;
 			}
-			_resource_changed();
+
+			[[fallthrough]];
+		}
+
+		case OBJ_MENU_PASTE_AS_UNIQUE: {
+			if (p_which == OBJ_MENU_PASTE_AS_UNIQUE) {
```
Comment (KoBeWi) [inline editor/inspector/editor_resource_picker.cpp]: ??
Why did you make a fallthrough instead of just calling the method?

Comment (YeldhamDev) [reply editor/inspector/editor_resource_picker.cpp]: Yeah, the `fallthrough` here doesn't really make much sense, changed it.

**Review by KoBeWi — APPROVED** [review]

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected. Code looks good to me.

The Paste as Unique action still works correctly.

**Comment by Repiteo** [comment]
Thanks!
