### PR TITLE
[RTL] Use separate paragraph copy for the partially visible paragraphs.

### LINKED ISSUE #110314: RichTextLabel text does not from grow right side when Horizontal Ratio set to Right, while sliding Visible Ratio
### Tested versions

Reproducible in 4.5rc1
Not reproducible in 4.4.1 stable.

### System information

Godot v4.5.rc1 - Windows 11 (build 26100) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 32.0.15.7700) - AMD Ryzen 7 5700X 8-Core Processor (16 threads) - 31.89 GiB memory

### Issue description

This came up in testing after reporting on this bug:
https://github.com/godotengine/godot/issues/108423

In 4.5, If I try to make text appear in a RichTextLabel which has horizontal justification set to RIGHT, and i move the Visible Ratio while text is set to "Characters Before Shaping", it still makes the text appear from the left.  This was not the case in 4.4, which had text appear from the right even as I was growing it with Visible Ratio. 

For the record, only "Characters Before Shaping" achieved the desired effect in 4.4, and trying other modes in both 4.4 and 4.5 did not replicate its functionality.

4.4:
Image
4.5rc1
Image

The same issue applies for Center alignment

4.4:
Image
4.5rc1:
Image

:

The fact that I can no longer achieve the first text affect at all, regardless of setting, appears to be a regression.  

### Steps to reproduce

In 4.4.1, open a new project and create a RichTextLabel node.
Add some text and set the Horizontal Alignment to the right.
Move the visible Ratio Slider back and forth. Notice that the new line grows from the right side of the text box.

Open the same file in 4.5rc1.
Move the visible Ratio Slider back and forth. Notice that the new line doesn't grow from the right as expected.

### Minimal reproduction project (MRP)

[4.4-4.5-text_content_bug.zip](https://github.com/user-attachments/files/22198084/4.4-4.5-text_content_bug.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/110314 while keeping control size calculations and performance improvement.

### CODE REVIEW

File: scene/gui/rich_text_label.cpp [hunk 1]
```diff
@@ -528,6 +579,7 @@ float RichTextLabel::_shape_line(ItemFrame *p_frame, int p_line, const Ref<Font>
 
 	// Clear cache.
 	l.dc_item = nullptr;
+	l.text_buf_disp = nullptr;
```
Comment (KoBeWi) [inline scene/gui/rich_text_label.cpp]:
```suggestion
	l.text_buf_disp = Ref<TextParagraph>();
```

**Review by KoBeWi — APPROVED** [review]

File: doc/classes/TextServer.xml [hunk 2]
```diff
@@ -1687,6 +1694,14 @@
 				Breaks text into words and returns array of character ranges. Use [param grapheme_flags] to set what characters are used for breaking.
 			</description>
 		</method>
+		<method name="shaped_text_has_object" qualifiers="const">
+			<return type="bool" />
+			<param index="0" name="shaped" type="RID" />
+			<param index="1" name="key" type="Variant" />
+			<description>
+				Returns [code]true[/code] if object is embedded in this shaped text buffer.
```
Comment (AThousandShips) [inline doc/classes/TextServer.xml]:
```suggestion
				Returns [code]true[/code] if an object with [param key] is embedded in this shaped text buffer.
```
Or similar

File: doc/classes/TextParagraph.xml [hunk 3]
```diff
@@ -235,6 +241,13 @@
 				Returns the size of the bounding box of the paragraph.
 			</description>
 		</method>
+		<method name="has_object" qualifiers="const">
+			<return type="bool" />
+			<param index="0" name="key" type="Variant" />
+			<description>
+				Returns [code]true[/code] if object is embedded in this paragraph.
```
Comment (AThousandShips) [inline doc/classes/TextParagraph.xml]:
```suggestion
				Returns [code]true[/code] if an object with [param key] is embedded in this shaped text buffer.
```

File: doc/classes/TextLine.xml [hunk 4]
```diff
@@ -119,6 +125,13 @@
 				Returns size of the bounding box of the text.
 			</description>
 		</method>
+		<method name="has_object" qualifiers="const">
+			<return type="bool" />
+			<param index="0" name="key" type="Variant" />
+			<description>
+				Returns [code]true[/code] if object is embedded in this line.
```
Comment (AThousandShips) [inline doc/classes/TextLine.xml]:
```suggestion
				Returns [code]true[/code] if an object with [param key] is embedded in this line.
```

File: doc/classes/TextServerExtension.xml [hunk 5]
```diff
@@ -1655,6 +1662,14 @@
 				Breaks text into words and returns array of character ranges. Use [param grapheme_flags] to set what characters are used for breaking.
 			</description>
 		</method>
+		<method name="_shaped_text_has_object" qualifiers="virtual required const">
+			<return type="bool" />
+			<param index="0" name="shaped" type="RID" />
+			<param index="1" name="key" type="Variant" />
+			<description>
+				Returns [code]true[/code] if object is embedded in this shaped text buffer.
```
Comment (AThousandShips) [inline doc/classes/TextServerExtension.xml]:
```suggestion
				Returns [code]true[/code] if an object with [param key] is embedded in this shaped text buffer.
```

**Review by AThousandShips — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
