### PR TITLE
Editor: Fix `EditorHelpBit` title height is wrong on initialization

### LINKED ISSUE #93031: Editor settings tooltips have a huge bottom margin with compact spacing preset
### Tested versions

Reproduces in:
- v4.3.beta1.official [a4f2ea91a]
- v4.3.dev6.official [89850d553]

Doesn't reproduce in:
- v4.3.dev5.official [89f70e98d]

### System information

Windows 10.0.22631 - GLES3 (Compatibility) - AMD Radeon RX 7700 XT (Advanced Micro Devices, Inc.; 31.0.24033.1003) - AMD Ryzen 7 5700X3D 8-Core Processor (16 Threads)

### Issue description

huge-bottom

### Steps to reproduce

- Open editor settings
- Go to Interface -> Theme
- Select "Compact" in the spacing preset dropdown
- Hover a setting label, for example the "Spacing Preset" text

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by dalexeev**
* Fixes #93031.

The bug is caused by the fact that the `title` label uses `fit_content = true`, unlike the `content` label. At initialization, the width is still 0, which is why the calculated `title` height is too large.

Although this is not entirely true for non-tooltip `EditorHelpBit`s, `512 * EDSCALE` is already used below, so I think it's ok.

https://github.com/godotengine/godot/blob/292e50e17e3f6e2509d3178a00204f964a907460/editor/editor_help.cpp#L3736-L3738

https://github.com/godotengine/godot/blob/292e50e17e3f6e2509d3178a00204f964a907460/editor/editor_help.cpp#L3748-L3750

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: editor/editor_help.cpp [hunk 1]
```diff
@@ -3735,6 +3735,7 @@ EditorHelpBit::EditorHelpBit(const String &p_symbol) {
 
 	title = memnew(RichTextLabel);
 	title->set_theme_type_variation("EditorHelpBitTitle");
+	title->set_custom_minimum_size(Size2(512 * EDSCALE, 0)); // GH-93031. Set the minimum width since `fit_content` is true.
```
Comment (dalexeev) [inline editor/editor_help.cpp:3738]:
```suggestion
	title->set_custom_minimum_size(Size2(512 * EDSCALE, 0)); // GH-93031. Set the minimum width even if `fit_content` is true.
```

Comment (akien-mga) [reply editor/editor_help.cpp:3738]: This is a suggestion to `self`, do you want to make that change or get feedback on whether it would be better?

Both seem fine to me.

Comment (dalexeev) [reply editor/editor_help.cpp]: The comment was misleading. I just wanted to explain the probable reason why I made this mistake. The documentation says `If true, the label's minimum size will be automatically updated to fit its content, matching the behavior of Label.`, but this only applies to the height, not the width.

The minimum width here is needed in both cases, regardless of `fit_content`.

**Comment by akien-mga** [comment]
Thanks!
