### PR TITLE
`Array`: Relax `slice` bound checks to properly handle negative indices

### LINKED ISSUE #56661: Array.slice() negative end inconsistent with other languages (off by one)
### Godot version

4.0.dev (d74647570)

### System information

Linux, Mageia 9 x86_64

### Issue description

Follow-up to PR #35901 and issue #53495.

The behavior of the negative `end` parameter for `Array.slice()` seems inconsistent with how it behaves in other languages. Our implementation uses:
```cpp
        if (p_end < 0) {
                p_end += size() + 1;
        }
```

And this `+ 1` adds an inconsistency with other implementations.

### GDScript

```gdscript
var arr = [1, 2, 3]
print(arr.slice(0, arr.size()))
print(arr.slice(0, -1))
print(arr.slice(0, -2))
```
prints:
```
[1, 2, 3]
[1, 2, 3]
[1, 2]
```

### Python / numpy

```python
import numpy
arr = numpy.array([1, 2, 3])
print(arr[0:])
print(arr[0:-1])
print(arr[0:-2])
```
prints:
```
[1 2 3]
[1 2]
[1]
```

### JavaScript

```js
arr = [1, 2, 3];
console.log(arr.slice(0))
console.log(arr.slice(0, -1))
console.log(arr.slice(0, -2))
```
prints:
```
[1, 2, 3]
[1, 2]
[1]
```
----

We can easily remove the `+1` but then the question is how to make it easy to go from `begin` to the size of the original array without repeating `arr.size()`.

Making the `end` argument optional like in JavaScript could be an option, but I'm not sure it's easily doable in GDScript. Aside from turning the `int end` into `Variant end`, we can't easily make it `null` or use another state to indicate the "go to size()" function. `0` would be a valid `end` for an empty slice, and `-1` should behave like `size() - 1` (wraps around).

And binding a `slice(int begin)` method is not possible either without polymorphism AFAIK.

### Steps to reproduce

```gdscript
var arr = [1, 2, 3]
print(arr.slice(0, arr.size()))
print(arr.slice(0, -1))
print(arr.slice(0, -2))
```

Expected:
```
[1, 2, 3]
[1, 2]
[1]
```
but got:
```
[1, 2, 3]
[1, 2, 3]
[1, 2]
```

### Minimal reproduction project

See above.

### PR DESCRIPTION
**Pull request by akien-mga**
The same is done for `Vector` (and thus `Packed*Array`).

`begin` and `end` can now take any value and will be clamped to
`[-size(), size()]`. Negative values are a shorthand for indexing the array
from the last element upward.

`end` is given a default `INT_MAX` value (which will be clamped to `size()`)
so that the `end` parameter can be omitted to go from `begin` to the max size
of the array.

This makes `slice` works similarly to numpy's and JavaScript's.

Fixes #56661.

----

TODOs:

- [x] Write docs for `Packed*Array`s
- [x] Update/add more unit tests for `slice`
- [x] Review C# and GDNative counterparts, if any

### CODE REVIEW

File: core/templates/vector.h [hunk 1]
```diff
@@ -145,25 +146,31 @@ class Vector {
...
+		}
+		int end = CLAMP(p_end, -s, s);
+		if (end < 0) {
+			end += s;
+		}
 
-		ERR_FAIL_COND_V(p_begin > p_end, result);
+		if (begin > end) {
+			SWAP(begin, end);
+		}
```
Comment (timothyqiu) [inline core/templates/vector.h:165]: I think this assumes that the user put something wrong as the argument.

Python & JavaScript both return an empty array in this case. That makes more sense as there _is_ nothing between the two indices.

**Comment by akien-mga** [comment]
@godotengine/mono I don't see any reference to `Array.slice()` in the Godot glue, is that expected?

**Comment by akien-mga** [comment]
This should be good to review. It works fine, the main question is whether we're fine with relaxing these checks and using `INT_MAX` as default value. I used `INT_MAX` instead of `INT32_MAX` or `INT64_MAX` as array/vector indices use `int`, but since GDScript `int` is explicitly `int64_t` there's a somewhat weird inconsistency here (but that goes through the whole codebase, aside from critical paths which have been improved recently like for FileAccess).

**Review by groud — APPROVED** [review]

**Review by mhilbrunner — APPROVED** [review]
