### PR TITLE
Fix history mismatch

### LINKED ISSUE #73603: History mismatch when editing tile source properties
### Godot version

4.0 9f68d06

### System information

Windows 10 x64

### Issue description

When changing any property of tile source, e.g. name:
image
This error appears in the output:
```
UndoRedo history mismatch: expected 0, got 2.
Set name
```
It means that there is an undo action that starts with a global object and continues with a scene one.

Only happens when the TileSet is built-in and it makes the changes to the tileset being registered as global, i.e. not related to its scene (which results in history inconsistency after closing the scene).

I did some debugging and the action comes from inspector, which edits TileSetAtlasSourceEditor and then TileSetAtlasSource. I don't know what exactly triggers it; the properties should be only set on TileSetAtlasSource.

### Steps to reproduce

1. Add scene
2. Add tilemap
3. Add tileset (don't save it to a file)
4. Edit tileset
5. Add atlas source (e.g. drop icon.svg)
6. Change atlas name
7. Observe output

### Minimal reproduction project

N/A

### LINKED ISSUE #74594: Godot 4 crashes when setting tileset texture region size
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows10,64,OpenGL API 3.3.0 NVIDIA 425.25 - Compatibility - Using Device: NVIDIA Corporation - GeForce MX250

### Issue description

When I change the tileset texture area size, godot crashes with the following error

The tileset contains a 107*35 sprite sheet

```
ERROR: UndoRedo history mismatch: expected 0, got 2.
   at: (editor/editor_undo_redo_manager.cpp:108)
```

### Steps to reproduce

1. create a tilemap node
2. create a tileset
3. click the tileset
4. drag the spritesheet(107*35) into the tileset
5. click yes with "auto create tiles in non-tra... "pop
6. change the tileset texture region size
7. program freezes
8.
 ```
ERROR: UndoRedo history mismatch: expected 0, got 2.
   at: (editor/editor_undo_redo_manager.cpp:108)
```

### Minimal reproduction project

[test1.zip](https://github.com/godotengine/godot/files/10918599/test1.zip)

### PR DESCRIPTION
**Pull request by Rindbee**
There are two cases for the error message, see https://github.com/godotengine/godot/issues/73603#issuecomment-1612509646.

Set the properties of the resource's proxy instead of setting the resource's properties directly. (For action "Set ...")

Update the path of the edited scene when saving the scene. (For action "Add atlas source", see https://github.com/godotengine/godot/issues/73603#issuecomment-1625339382)

Before 

https://github.com/godotengine/godot/assets/30386067/b2734e81-90fe-477b-bc2a-12a30bdf2b62

After 

https://github.com/godotengine/godot/assets/30386067/61d73d65-e649-4d55-9c10-a1c1de320936

Fix #73603, fix #74594.

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -1983,6 +1983,8 @@ void EditorNode::_dialog_action(String p_file) {
 				if (scene_idx != -1) {
 					_discard_changes();
 				}
+
+				editor_data.set_scene_path(scene_idx, p_file); // Update the path of the edited scene.
```
Comment (Rindbee) [inline editor/editor_node.cpp:1987]: This is a fix for the case of action "Add atlas source". See the video for steps to reproduce.

File: editor/editor_data.cpp [hunk 2]
```diff
@@ -867,6 +867,9 @@ String EditorData::get_scene_title(int p_idx, bool p_always_strip_extension) con
 }
 
 void EditorData::set_scene_path(int p_idx, const String &p_path) {
+	if (p_idx == -1) {
```
Comment (groud) [inline editor/editor_data.cpp:870]: This should likely be moved to the calling logic, not here.

**Comment by YuriSizov** [comment]
@groud @KoBeWi Could you review this?

**Review by KoBeWi — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.
