### PR TITLE
Fix expected argument count for `Callable` call errors

### LINKED ISSUE #80826: Strange error message: "Method expected 0 arguments, but called with 0"
### Godot version

Godot v4.1.1.stable

### System information

Windows 10

### Issue description

Get strange error message "Method expected 0 arguments, but called with 0" while generating signal
image
 

### Steps to reproduce

1. clone https://github.com/johnny-byte/godot_issue/tree/master
2. run
3. click mouse button right
4. get error message

### Minimal reproduction project

[BugScene.zip](https://github.com/godotengine/godot/files/12388945/BugScene.zip)

### PR DESCRIPTION
**Pull request by dalexeev**
* Closes #80826.

https://github.com/godotengine/godot/blob/970be7afdc111ccc7459d7ef3560de70e6d08c80/core/variant/callable.h#L57-L70

### CODE REVIEW

**Comment by akien-mga** [comment]
From a cursory look this seems sensible, but I'm surprised that it was wrong in so many places in the codebase. Is that due to an API design change that wasn't properly propagated?

**Comment by dalexeev** [comment]
> Is that due to an API design change that wasn't properly propagated?

I think `argument` was the right property before. Then, after the refactoring, the code was not updated in some places, and perhaps bad cases increased due to copy-paste without looking into the header. See [diff](https://github.com/godotengine/godot/pull/36368/files#diff-1db665b8cbfd8e25c0cf1819c5d0b5a2ae325563d5eed20800574c3cbbe4fae0L336-L348). 

```c++
Error error;
int argument;
Type expected;
```

File: core/object/object.cpp [hunk 1]
```diff
@@ -991,14 +991,17 @@ struct _ObjectSignalDisconnectData {
...
+		r_error.expected = 1;
+		ERR_FAIL_V(Error::ERR_INVALID_PARAMETER);
+	}
 
-	ERR_FAIL_COND_V(p_argcount < 1, Error::ERR_INVALID_PARAMETER);
-	if (p_args[0]->get_type() != Variant::STRING_NAME && p_args[0]->get_type() != Variant::STRING) {
+	if (unlikely(p_args[0]->get_type() != Variant::STRING_NAME && p_args[0]->get_type() != Variant::STRING)) {
 		r_error.error = Callable::CallError::CALL_ERROR_INVALID_ARGUMENT;
 		r_error.argument = 0;
 		r_error.expected = Variant::STRING_NAME;
```
[the remark this answers is not in the document]
Comment (dalexeev) [reply core/object/object.cpp:1003]: Because this is `CALL_ERROR_INVALID_ARGUMENT`, not `CALL_ERROR_TOO_MANY_ARGUMENTS` or `CALL_ERROR_TOO_FEW_ARGUMENTS`.

File: core/object/object.cpp [hunk 2]
```diff
@@ -714,13 +714,13 @@ Variant Object::callp(const StringName &p_method, const Variant **p_args, int p_
...
 		if (p_argcount != 0) {
-			r_error.argument = 0;
 			r_error.error = Callable::CallError::CALL_ERROR_TOO_MANY_ARGUMENTS;
+			r_error.expected = 0;
 			return Variant();
 		}
 		if (Object::cast_to<RefCounted>(this)) {
-			r_error.argument = 0;
 			r_error.error = Callable::CallError::CALL_ERROR_INVALID_METHOD;
+			r_error.argument = 0;
```
Comment (dalexeev) [inline core/object/object.cpp:723]:
```suggestion
```

File: core/variant/variant_utility.cpp [hunk 3]
```diff
@@ -337,6 +337,7 @@ Variant VariantUtilityFunctions::snapped(const Variant &x, const Variant &step,
 	if (x.get_type() != step.get_type() && !((x.get_type() == Variant::INT && step.get_type() == Variant::FLOAT) || (x.get_type() == Variant::FLOAT && step.get_type() == Variant::INT))) {
 		r_error.error = Callable::CallError::CALL_ERROR_INVALID_ARGUMENT;
 		r_error.argument = 1;
+		//r_error.expected = x.get_type();
```
Comment (dalexeev) [inline core/variant/variant_utility.cpp:340]:
```suggestion
		r_error.expected = x.get_type();
```

File: core/variant/variant_utility.cpp [hunk 4]
```diff
@@ -492,7 +493,7 @@ Variant VariantUtilityFunctions::wrap(const Variant &p_x, const Variant &p_min,
 	if (x_type != Variant::INT && x_type != Variant::FLOAT) {
 		r_error.error = Callable::CallError::CALL_ERROR_INVALID_ARGUMENT;
 		r_error.argument = 0;
-		r_error.expected = x_type;
+		r_error.expected = x_type; // ?
```
Comment (dalexeev) [inline core/variant/variant_utility.cpp:496]:
```suggestion
		r_error.expected = Variant::FLOAT;
```

**Review by akien-mga — APPROVED** [review]

File: platform/android/java_class_wrapper.cpp [hunk 5]
```diff
@@ -132,7 +132,7 @@ bool JavaClass::_call_method(JavaObject *p_instance, const StringName &p_method,
 			if (arg_expected != Variant::NIL) {
 				r_error.error = Callable::CallError::CALL_ERROR_INVALID_ARGUMENT;
 				r_error.argument = i;
-				r_error.expected = arg_expected;
+				r_error.expected = arg_expected; // ?
```
Comment (dalexeev) [inline platform/android/java_class_wrapper.cpp:135]:
```suggestion
				r_error.expected = arg_expected;
```

I got it, there is no mistake. The variable should probably be renamed or the code rearranged.

**Comment by dalexeev** [comment]
Perhaps the first mistake was in the comment due to bad copy-paste and the following was intended:

```diff
 	enum Error {
 		CALL_OK,
 		CALL_ERROR_INVALID_METHOD,
 		CALL_ERROR_INVALID_ARGUMENT, // expected is variant type
- 		CALL_ERROR_TOO_MANY_ARGUMENTS, // expected is number of arguments
- 		CALL_ERROR_TOO_FEW_ARGUMENTS, // expected is number of arguments
+ 		CALL_ERROR_TOO_MANY_ARGUMENTS, // argument is number of arguments 
+ 		CALL_ERROR_TOO_FEW_ARGUMENTS, // argument is number of arguments
 		CALL_ERROR_INSTANCE_IS_NULL,
 		CALL_ERROR_METHOD_NOT_CONST,
 	};
```

```diff
 	Error error = Error::CALL_OK;
 	int argument = 0;
- 	int expected = 0;
+ 	Variant::Type expected = Variant::NIL;
```

And then we started changing `argument` to `expected` in the code to match the comment.

In my opinion, the original version (like in 3.x) makes more sense, since the `argument` property is always responsible for the number/number of arguments. Now in #81605 we have to use `switch`:

```c++
switch (r_call_error.error) {
    case Callable::CallError::CALL_ERROR_INVALID_ARGUMENT:
        r_call_error.argument -= captures_amount;
        // ...
        break;
    case Callable::CallError::CALL_ERROR_TOO_MANY_ARGUMENTS:
    case Callable::CallError::CALL_ERROR_TOO_FEW_ARGUMENTS:
        r_call_error.expected -= captures_amount;
        // ...
        break;
    default:
        break;
}
```

I'm not sure if `CallError` is an internal API or if it's also exposed to GDExtension.

**Comment by akien-mga** [comment]
> I'm not sure if `CallError` is an internal API or if it's also exposed to GDExtension.

GDExtension has a similar struct (and the comments are even more wrong as they were capitalized :)).

```c
typedef enum {
	GDEXTENSION_CALL_OK,
	GDEXTENSION_CALL_ERROR_INVALID_METHOD,
	GDEXTENSION_CALL_ERROR_INVALID_ARGUMENT, // Expected a different variant type.
	GDEXTENSION_CALL_ERROR_TOO_MANY_ARGUMENTS, // Expected lower number of arguments.
	GDEXTENSION_CALL_ERROR_TOO_FEW_ARGUMENTS, // Expected higher number of arguments.
	GDEXTENSION_CALL_ERROR_INSTANCE_IS_NULL,
	GDEXTENSION_CALL_ERROR_METHOD_NOT_CONST, // Used for const call.
} GDExtensionCallErrorType;

typedef struct {
	GDExtensionCallErrorType error;
	int32_t argument;
	int32_t expected;
} GDExtensionCallError;
```

If we need to change the meaning of `argument`/`expected`, maybe this might need to be done via a new `GDExtensionCallError2` struct, preserving the compatibility for `GDExtensionCallError` uses somewhat. CC @dsnopek

**Comment by dsnopek** [comment]
> If we need to change the meaning of `argument`/`expected`, maybe this might need to be done via a new `GDExtensionCallError2` struct, preserving the compatibility for `GDExtensionCallError` uses somewhat

Hrm. If we wanted to make a new `GDExtensionCallError2`, then we'd need to also make new versions of every function that deals with `GDExtensionCallError`, which includes some function pointers that are used on _other_ structs, which would need new versions along with all the functions that accept those too. This quickly becomes quite a few changes.

Am I correct in understanding that this just affects the accuracy of some error messages? If so, the worst that could happen, is that a GDExtension compiled for Godot 4.1 but opened in Godot 4.2 could generate some incorrect error messages in some cases. This could maybe just be an acceptable weirdness with using older GDExtensions? It's not a crash, and it's not an error interpreted as a success or vice-versa.

We should also probably make changes similar to those in this PR to godot-cpp, so that it's using `argument` and `expected` correctly too.

**Comment by ParadoxV5** [comment]
> If we need to change the meaning of `argument`/`expected`, maybe this might need to be done via a new `GDExtensionCallError2` struct, preserving the compatibility for `GDExtensionCallError` uses somewhat. 

> Am I correct in understanding that this just affects the accuracy of some error messages? […] This could maybe just be an acceptable weirdness with using older GDExtensions? It's not a crash, and it's not an error interpreted as a success or vice-versa.
> 
> We should also probably make changes similar to those in this PR to godot-cpp, so that it's using `argument` and `expected` correctly too.

Here’s what this GDExtension user thinks. I say no needed, because
* This is a bug (within Godot Engine), not a feature (something intended according to documentation and/or intuition). See @dalexeev[’s comment](#issuecomment-1717302154)
  * My code actually has `error.expected ? error.expected : error.argument` to work this mistake around.
* You folks haven’t promised API stability yet. (e.g., #75779)

**Review by akien-mga — APPROVED** [review]
The PR has been updated to fix the bug without breaking compat, so I think it's good to go.
Similar fixes might be needed in godot-cpp.

**Comment by akien-mga** [comment]
Thanks!
