### PR TITLE
Prevent folder names with trailing periods from being used automatically

### LINKED ISSUE #75516: Project with "." (period) at the end of its name doesn't run from the editor on Windows (and logs/shader cache can't be written)
### Godot version

v4.0.1.stable.official [cacf49999]

### System information

Windows 11

### Issue description

Hi,

Running Godot 4.0.1 official on Windows 11 Pro 64Bit.
Projects with "."(periods) in their names do not run from Windows IDE?

Perhaps add a warning when naming projects so users don't use "." periods?

Jesse

### Steps to reproduce

Create "Hello World!' application and put a "." period in its name.
Then try to run app from within IDE on Windows 11.

### Minimal reproduction project

N.A.

### PR DESCRIPTION
**Pull request by Calinou**
Folder names ending with one or more `.` characters are not allowed on Windows, so this would break writing logs, shader cache and other project-specific files. Trailing periods are now stripped in this case.

On non-Windows platforms, this change still applies in the interest of portability.

This is technically a small breakage on non-Windows platforms because of this, but very few projects had user directory names that ended with `.` anyway (as it didn't work on Windows).

- This closes https://github.com/godotengine/godot/issues/75516.

**Testing project:** [test_project_periods.zip](https://github.com/user-attachments/files/15959791/test_project_periods.zip)

### CODE REVIEW

**Comment by Mickeon** [comment]
Dumb question, what about MacOS or any other build of the engine?

**Comment by Calinou** [comment]
> Dumb question, what about MacOS or any other build of the engine? Is the trailing period already trimmed, or is it plainly allowed? Or does this PR already catch all of them?

It's not currently trimmed, but this PR trims it on all platforms. See the PR's description for rationale.

**Review by aaronfranke — APPROVED** [review]
Makes sense to me. I haven't tested it.

**Review by AThousandShips — APPROVED** [review]

File: platform/windows/os_windows.cpp [hunk 1]
```diff
@@ -1828,7 +1828,9 @@ String OS_Windows::get_user_data_dir() const {
 			}
 			return get_data_path().path_join(custom_dir).replace("\\", "/");
 		} else {
-			return get_data_path().path_join(get_godot_dir_name()).path_join("app_userdata").path_join(appname).replace("\\", "/");
+			// Trim trailing periods from the user directory name as it's not valid on Windows.
+			// This check is still applied on non-Windows platforms so the project directory name is consistent across platforms.
+			return get_data_path().path_join(get_godot_dir_name()).path_join("app_userdata").path_join(appname).replace("\\", "/").rstrip(".");
```
Comment (akien-mga) [inline platform/windows/os_windows.cpp:1833]: Won't the `custom_dir` logic above potentially still have the same problem?

I think it would be better to do this fix in `OS::get_safe_dir_name` (preventing it to end with a dot), which would make sure that both `appname` and `custom_dir` here are valid folder names.

Comment (Calinou) [reply platform/windows/os_windows.cpp]: That makes more sense, I agree. Done :slightly_smiling_face:

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
