### PR TITLE
Fix linear interpolation not working with mixed (int/float) keyframes

### LINKED ISSUE #85858: Linear keyframe interpolation not working for Control anchor offsets
### Tested versions

- Reproducible in: v4.2.stable.official [46dc27791]
- Not reproducible in: v4.1.3.stable

### System information

Godot v4.2.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (Advanced Micro Devices, Inc.; 31.0.21023.2010) - AMD Ryzen 7 5700X 8-Core Processor (16 Threads)

### Issue description

Starting with Godot 4.2, changing a Control node's anchor offsets with an AnimationPlayer node results in the offsets "snapping" to the keyframes, as if Nearest interpolation were used. 

This only applies to the Linear Interpolation Mode; Cubic still works as expected.

resize_interp_fail

I encountered this regression when upgrading my project from 4.1.3 to 4.2. Minimum reproduction project provided below.

### Steps to reproduce

- Create a Control node with a Custom anchor preset.
- Create an AnimationPlayer track for one or more of its anchor offsets, with the Continuous update mode and Linear interpolation.
- Add keyframes to track(s)
- Play animation (either in the editor or in-game)

### Minimal reproduction project (MRP)

[ControlResize.zip](https://github.com/godotengine/godot/files/13589517/ControlResize.zip)

### PR DESCRIPTION
**Pull request by bs-mwoerner**
Fixes #85858.

It is possible in the editor to create both integer and float keyframes on an animation track. With the rework of variant interpolation and blending (#84815), linear interpolation lost its ability to interpolate between such keyframes (cubic interpolation works). This PR restores a special case handling for int/float pairs similar to what was there before the rework.

### CODE REVIEW

File: scene/resources/animation.cpp [hunk 1]
```diff
@@ -5594,7 +5594,10 @@ Variant Animation::array_to_string(const Variant p_value) {
 }
 
 Variant Animation::add_variant(const Variant &a, const Variant &b) {
-	if (a.get_type() != b.get_type() && !a.is_array()) {
+	if (a.is_num() && b.is_num()) {
+		const real_t result = (a.operator real_t()) + (b.operator real_t());
```
Comment (AThousandShips) [inline scene/resources/animation.cpp:5598]: I don't think this should be `real_t`, `Variant` always holds a `double`, there's some confusion over this at times and some times `real_t` is used incorrectly, this was fixed in some places here in #81296

Comment (bs-mwoerner) [reply scene/resources/animation.cpp]: Oh, right, I just copied this from the `FLOAT` case without questioning it but I completely agree. `real_t` is likely to be `float` whereas the value in the `Variant` is always a `double`. I've changed the "float only" cases, too. Cubic interpolation also casts its `FLOAT` `Variants` to `real_t`. Not sure if we should change that, too.

Comment (AThousandShips) [reply scene/resources/animation.cpp]: I'd say to take it one step at a time unless an animation reviewer says otherwise 🙂

Comment (bs-mwoerner) [reply scene/resources/animation.cpp]: Actually, from looking at the PR you linked, I learned that `VARIANT::INT` is supposed to be `int64_t`. In the current code, it is interpolated via `real_t` and then cast to an `int`, so I expect the problem that was fixed there is back. I suppose that warrants a new pull request for fixing issue #81289 again?

Comment (AThousandShips) [reply scene/resources/animation.cpp]: I'd say that should be handled here specifically then

File: scene/resources/animation.cpp [hunk 2]
```diff
@@ -5594,7 +5594,10 @@ Variant Animation::array_to_string(const Variant p_value) {
 }
 
 Variant Animation::add_variant(const Variant &a, const Variant &b) {
-	if (a.get_type() != b.get_type() && !a.is_array()) {
+	if (a.is_num() && b.is_num()) {
```
Comment (AThousandShips) [inline scene/resources/animation.cpp:5597]:
```suggestion
	if ((a.get_type() != b.get_type() && a.is_num() && b.is_num()) {
```
Right? Otherwise why the switch below, this handles `int` and `float` combinations

Comment (bs-mwoerner) [reply scene/resources/animation.cpp:5597]: Yes, I wondered how to best do the conditions here. My reasoning was: Since this is a special case, why not just handle it at the start and otherwise fall back to what would have been done otherwise, especially since the int/int case here looked simpler than the more general conversion in the switch below. But you're right that if `a` is an `INT` or a `FLOAT`, then it is never an array and if `b` is of the same type, then it is always a number, so `case Variant::FLOAT` and `case Variant::INT` should be unreachable now (and could be removed to avoid confusion).

I'm happy to go for whatever you consider more readable/consistent. We could also nest both in the `a.get_type() != b.get_type()` since that's part of both branches then.

```c++
	if (a.get_type() != b.get_type()) {
		if (a.is_num() && b.is_num()) {
			const double result = (a.operator double()) + (b.operator double());
			return cast_from_blendwise(result, a.get_type());
		} else if (!a.is_array()) {
			return a;
		}
	}
```

File: scene/resources/animation.cpp [hunk 3]
```diff
@@ -5594,7 +5594,10 @@ Variant Animation::array_to_string(const Variant p_value) {
...
+		const double result = (a.operator double()) + (b.operator double());
```
Comment (TokageItLab) [inline scene/resources/animation.cpp:5598]: It should not do the calculation here, but change the type of a to Variant::FLOAT to go through, and do the calculation in the switch-case block below. The same is applied to other parts.

**Review by TokageItLab — CHANGES_REQUESTED** [review]

File: scene/resources/animation.cpp (hunk 3 above)
Comment (bs-mwoerner) [reply scene/resources/animation.cpp]: I now changed all these instances to call themselves with arguments converted to `double` (making sure to convert both `a` and `b` to prevent an infinite loop if `b` is `INT`), which essentially takes it to the switch with a new `a` (and possibly `b`), so this now is handled like the individual array elements.

I also changed the `INT` interpolation to go via `double` and `int64_t` which makes it work above `INT_MAX`, although not quite all the way to `INT64_MAX`, because that conversion isn't lossless. So the code in #81289 still does not work with this change, mostly because `subtract_variant(INT64_MAX, 0)` returns `INT64_MIN` instead of `INT64_MAX`. If we want to support that, we may need a dedicated code path for integer math, at least for subtraction.

File: scene/resources/animation.cpp [hunk 4]
```diff
@@ -5594,16 +5594,20 @@ Variant Animation::array_to_string(const Variant p_value) {
 }
 
 Variant Animation::add_variant(const Variant &a, const Variant &b) {
-	if (a.get_type() != b.get_type() && !a.is_array()) {
-		return a;
+	if (a.get_type() != b.get_type()) {
+		if (a.is_num() && b.is_num()) {
+			return add_variant(a.operator double(), b.operator double());
```
Comment (TokageItLab) [inline scene/resources/animation.cpp:5599]:
```suggestion
			return add_variant(cast_to_blendwise(a), cast_to_blendwise(b));
```
Same for the others.

**Review by TokageItLab — CHANGES_REQUESTED** [review]

File: scene/resources/animation.cpp (hunk 4 above)
Comment (bs-mwoerner) [reply scene/resources/animation.cpp]: Done. 👍

**Review by TokageItLab — APPROVED** [review]

File: scene/resources/animation.cpp [hunk 5]
```diff
@@ -5947,17 +5959,21 @@ Variant Animation::blend_variant(const Variant &a, const Variant &b, float c) {
 }
 
 Variant Animation::interpolate_variant(const Variant &a, const Variant &b, float c, bool p_snap_array_element) {
-	if (a.get_type() != b.get_type() && !a.is_array()) {
-		return a;
+	if (a.get_type() != b.get_type()) {
+		if (a.is_num() && b.is_num()) {
+			return interpolate_variant(cast_to_blendwise(a), cast_to_blendwise(b), c);
```
Comment (AThousandShips) [inline scene/resources/animation.cpp:5964]:
```suggestion
			return interpolate_variant(cast_to_blendwise(a), cast_to_blendwise(b), c, p_snap_array_element);
```
Missed argument

Comment (bs-mwoerner) [reply scene/resources/animation.cpp:5964]: Good catch, although at this point we already know that this argument is not going to be used (we've checked that we're dealing with numbers, not arrays), so we can either keep it for consistency or drop it for conciseness. I had the argument there in my earlier commits but then noticed that it isn't passed down in any of the other recursive calls in the method, so I thought I'd follow that lead.

Comment (AThousandShips) [reply scene/resources/animation.cpp:5964]: Good point 🙂

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.
