### PR TITLE
CodeEdit: Fix line number margin

### LINKED ISSUE #98521: (4.4-dev3) Bad spacing in Text Editor when Code Folding is disabled
### Tested versions

4.4-dev3

### System information

Windows 10, Ryzen 3 3300x, 16gb RAM 2666mhz, GTX 1660 6gb.

### Issue description

I'm not sure if this is a bug, or is intended, so I apologize in advance. Either way, I dislike the new look.

When Code Folding is disabled, there's no spacing between the number and the code.

4.4-dev3
image

4.3-stable
image

Also, if possible, I'd like to understand the changes in the overall theme in the editor. Why does everything seem bold and brighter?

4.4-dev3
image

4.3-stable
image

I personally didn't like at all the theme changes.

### Steps to reproduce

Don't apply.

### Minimal reproduction project (MRP)

Don't apply.

### PR DESCRIPTION
**Pull request by rune-scape**
fixes https://github.com/godotengine/godot/issues/98521

### CODE REVIEW

File: scene/gui/code_edit.cpp [hunk 1]
```diff
@@ -1498,9 +1498,9 @@ void CodeEdit::_line_number_draw_callback(int p_line, int p_gutter, const Rect2
 	ofs.y += TS->shaped_text_get_ascent(text_rid);
 
 	if (rtl) {
-		ofs.x = p_region.position.x;
-	} else {
 		ofs.x = p_region.get_end().x - text_size.width;
+	} else {
+		ofs.x = p_region.position.x;
 	}
```
Comment (bruvzg) [inline scene/gui/code_edit.cpp:1504]: Change looks fine.

But I'm not sure why there's RTL case here, East Arabic numerals (١٢٣) are written in the same direction as West Arabic (123), and `CodeEdit` is always in LTR mode.

**Review by bruvzg — APPROVED** [review]

File: scene/gui/code_edit.cpp (hunk 1 above)
Comment (rune-scape) [reply scene/gui/code_edit.cpp:1504]: for some reason CodeEdit actually can be in rtl mode? not normally, but it can be forced. and the gutters would be on the right side of the screen. theres cases for it all over in TextEdit, it just makes the spacing correct if it ever is in rtl mode :confused:
i could just take it out
