### PR TITLE
Fix `EditorSpinSlider` grabber `TextureRect` doesn't follow parent when scrolling.

### LINKED ISSUE #97825: Focus "outline" for sliders moves with scrolling
### Tested versions

Reproducible: v4.0.stable.official [92bee43ad], v4.4.dev.flathub [97ef3c837]
Not reproducible: v3.6.stable.official [de2f0f147]

### System information

Godot v4.4.dev (97ef3c837) - Freedesktop SDK 23.08 (Flatpak runtime) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 570 Series (RADV POLARIS10) - Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz (8 Threads)

### Issue description

Slider focus "indicator" will move with scrolling when it shouldn't.
Yeah, not the greatest explanation, just watch the video:

[Запис з екрана від 2024-10-04 23-10-16.webm](https://github.com/user-attachments/assets/415ecde1-98c8-4a33-b137-d6af9d82acc9)

I didn't tested using in-game nodes, but this consistently happens thought editor, for example, settings window, node inspector, etc.
I tested in both 4.0 and 4.4 versions and it happens there, but not in 3.6:

[3_6.webm](https://github.com/user-attachments/assets/9d658f47-baf5-49b7-bf2e-24566ec39064)

So something changed in 4.0 and onward after that.

### Steps to reproduce

1. Pick scrollbar with cursor pointer (for example, editor settings window or node inspector) and don't release it.
2. Move cursor to any slider ui element (for example, custom ui scale in editor settings)
3. Move cursor up/down and observe how focus "outline" start moving with scrolling (it will disappear when cursor will leave slider "hitbox")

### Minimal reproduction project (MRP)

This can be reproduced in Godot editor itself.

### PR DESCRIPTION
**Pull request by WhalesState**
* Fixes: https://github.com/godotengine/godot/issues/97825

### CODE REVIEW

**Comment by SaracenOne** [comment]
Hmm, the fix seems mostly fine, but I'm a little concerned about hardcoding the z-value to 1. While I don't think the z-value would change for an EditorSpinSlider, wouldn't it still make more sense to make it something like `grabber->set_z_index(get_z_index() + 1);` so it's always relative?

File: editor/gui/editor_spin_slider.cpp [hunk 1]
```diff
@@ -735,7 +735,7 @@ EditorSpinSlider::EditorSpinSlider() {
 	grabber = memnew(TextureRect);
 	add_child(grabber);
 	grabber->hide();
-	grabber->set_as_top_level(true);
+	grabber->set_z_index(1);
```
Comment (SaracenOne) [inline editor/gui/editor_spin_slider.cpp:738]: I feel like this would make more sense to be `grabber->set_z_index(get_z_index() + 1);` so it's always relative.

**Review by SaracenOne — CHANGES_REQUESTED** [review]

**Review by SaracenOne — APPROVED** [review]
My previous feedback was mistaken since all CanvasItems have z_relative set on by default, so this should be fine to merge as is after all 👍

**Comment by Mickeon** [comment]
This is relatively simple and easy to salvage, too.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
