### PR TITLE
FIX CodeTextEditor not respecting focus in _input

### LINKED ISSUE #37807: Input Map Ctrl+D assign issue
**Godot version:**
3.2.1

**OS/device including version:**
Windows 7 Professional 64-bit

**Issue description:**
Assigning Ctrl+D to an action doesn't work while the GDScript editor is open in the background, but assign works when editor is closed.
Noticed this while testing key combo assigns.

**Steps to reproduce:**
Press Ctrl+D when Input Map assign window is open and GDScript editor is open in the background.

**Minimal reproduction project:**

GodotBug

### PR DESCRIPTION
**Pull request by MrRevington**
fixes #37807 by checking if the code editor has keyboard focus before initiating actions based on code editor shortcuts.

### CODE REVIEW

**Review by Paulb23 — COMMENTED** [review]
Code looks good.

However, should be PR'd against master rather then the 3.2 branch.

**Comment by MrRevington** [comment]
That was interesting(simple changing the target branch to master 😄)!
I think I correctly changed it to the master branch now. 

Thanks Paulb23!

**Review by volzhs — APPROVED** [review]

**Comment by volzhs** [comment]
it surely fixed #38922.

**Comment by volzhs** [comment]
@MrRevington I found this does not fix the problem with a certain node.
https://github.com/godotengine/godot/issues/38922#issuecomment-632421249
any idea?

File: editor/code_editor.cpp [hunk 1]
```diff
@@ -657,9 +657,8 @@ FindReplaceBar::FindReplaceBar() {
 // be handled too late if they weren't handled here.
 void CodeTextEditor::_input(const Ref<InputEvent> &event) {
 	const Ref<InputEventKey> key_event = event;
-	if (!key_event.is_valid() || !key_event->is_pressed()) {
+	if (!key_event.is_valid() || !key_event->is_pressed() || !text_editor->has_focus())
```
Comment (akien-mga) [inline editor/code_editor.cpp:660]: Please readd the braces, they are now enforced in our code style.

Comment (MrRevington) [reply editor/code_editor.cpp]: Done! 
I wonder why the clang hook didn't catch that. 🤔

**Comment by akien-mga** [comment]
Thanks!
