### PR TITLE
Fix selection box + scrolling in animation editor.

### LINKED ISSUE #76819: Can't select all Animation keys using rectangular selection
### Godot version

4.01

### System information

Windows

### Issue description

Can't select all keys when scrolling down

https://user-images.githubusercontent.com/16458555/236708294-2f0e7fc4-5e34-4d0f-8ab3-c0efde9781fa.mp4

### Steps to reproduce

try to select all keys like above

### Minimal reproduction project

-

### PR DESCRIPTION
**Pull request by SaracenOne**
Closes #76819

https://github.com/user-attachments/assets/32950993-b599-4386-966b-f01e75fec299

Attempts to fix this by introducing the following changes:
* Disable the panning behaviour when the selection box is active.
* Places the selection box in a clipped container used for the timeline.
* Dynamically repositions the selection box in response to changes to the horizontal and vertical scrollers.

In theory, it should also work with horizontal scrolling too, but I don't have access to a mouse which can do this. If anyone has access to one (I think most Mac computers have a mouse which can do this), please confirm that this fix also works for horizontal scrolling.

### CODE REVIEW

**Comment by KoBeWi** [comment]
> In theory, it should also work with horizontal scrolling too, but I don't have access to a mouse which can do this.

You can scroll horizontally by holding Shift.

File: editor/animation_track_editor.cpp [hunk 1]
```diff
@@ -5724,10 +5728,9 @@ void AnimationTrackEditor::_scroll_input(const Ref<InputEvent> &p_event) {
 		}
 
 		Rect2 rect(from, to - from);
-		Rect2 scroll_rect = Rect2(scroll->get_global_position(), scroll->get_size());
-		rect = scroll_rect.intersection(rect);
-		box_selection->set_position(rect.position);
-		box_selection->set_size(rect.size);
+		Rect2 visual_rect = Rect2(from - scroll->get_global_position(), rect.get_size());
+		box_selection->set_position(visual_rect.position);
+		box_selection->set_size(visual_rect.size);
```
Comment (KoBeWi) [inline editor/animation_track_editor.cpp:5733]: `visual_rect` doesn't look necessary. You can just directly assign values.

File: editor/animation_track_editor.h [hunk 2]
```diff
@@ -498,6 +498,10 @@ class AnimationTrackEditor : public VBoxContainer {
 
 	PropertyInfo _find_hint_for_track(int p_idx, NodePath &r_base_path, Variant *r_current_val = nullptr);
 
+	void _scroll_changed(Vector2 p_val);
```
Comment (KoBeWi) [inline editor/animation_track_editor.h:501]:
```suggestion
	void _scroll_changed(const Vector2 &p_val);
```

File: editor/animation_track_editor.cpp [hunk 3]
```diff
@@ -5747,6 +5750,42 @@ void AnimationTrackEditor::_toggle_bezier_edit() {
 	}
 }
 
+void AnimationTrackEditor::_scroll_changed(Vector2 p_val) {
+	if (box_selecting) {
+		Vector2 scroll_difference = p_val - prev_scroll_position;
```
Comment (KoBeWi) [inline editor/animation_track_editor.cpp:5755]:
```suggestion
		const Vector2 scroll_difference = p_val - prev_scroll_position;
```

File: editor/animation_track_editor.cpp [hunk 4]
```diff
@@ -5747,6 +5750,42 @@ void AnimationTrackEditor::_toggle_bezier_edit() {
...
+		if (from.x > to.x) {
+			SWAP(from.x, to.x);
+		}
+
+		if (from.y > to.y) {
+			SWAP(from.y, to.y);
+		}
+
+		Rect2 rect(from, to - from);
+		Rect2 visual_rect = Rect2(from - scroll->get_global_position(), rect.get_size());
```
Comment (KoBeWi) [inline editor/animation_track_editor.cpp:5771]: Again, unnecessary.

File: editor/animation_track_editor.cpp [hunk 5]
```diff
@@ -7470,8 +7519,8 @@ AnimationTrackEditor::AnimationTrackEditor() {
 	ichb->add_child(insert_confirm_reset);
 
 	box_selection = memnew(Control);
-	add_child(box_selection);
-	box_selection->set_as_top_level(true);
+	box_selection_container->add_child(box_selection);
+	box_selection->set_as_top_level(false);
```
Comment (KoBeWi) [inline editor/animation_track_editor.cpp:7523]: This is default.

Comment (KoBeWi) [inline editor/animation_track_editor.cpp:7523]:
```suggestion
```
This is default.

File: editor/animation_track_editor.cpp [hunk 6]
```diff
@@ -7247,16 +7286,26 @@ AnimationTrackEditor::AnimationTrackEditor() {
...
 	VScrollBar *sb = scroll->get_v_scroll_bar();
 	scroll->remove_child(sb);
 	timeline_scroll->add_child(sb); // Move here so timeline and tracks are always aligned.
 	scroll->set_focus_mode(FOCUS_CLICK);
 	scroll->connect(SceneStringName(gui_input), callable_mp(this, &AnimationTrackEditor::_scroll_input));
 	scroll->connect(SceneStringName(focus_exited), callable_mp(panner.ptr(), &ViewPanner::release_pan_key));
 
+	scroll->get_v_scroll_bar()->connect(SceneStringName(value_changed), callable_mp(this, &AnimationTrackEditor::_v_scroll_changed));
+	scroll->get_h_scroll_bar()->connect(SceneStringName(value_changed), callable_mp(this, &AnimationTrackEditor::_h_scroll_changed));
+	prev_scroll_position = Vector2(0.0, 0.0);
```
Comment (KoBeWi) [inline editor/animation_track_editor.cpp:7307]:
```suggestion
```
Not needed.

**Review by KoBeWi — APPROVED** [review]

**Comment by SaracenOne** [comment]
Updated to fix the issues raised. Regarding the Shift+Mouse scroll thing, I believe this is a feature of the ViewPanner which is attached to the Timeline scrollbox, which also gives other navigation controls like being able to scroll through the timeline by clicking and dragging with the middle mouse button. I modified the behaviour to intentionally 'not' call the panner while the selection box is active due to certain undesired behaviour in the site.

Perhaps it might be worth keeping the panner active instead, but modifying its functionality when the selection box is active to disable certain features. Regardless, I still think we need testing with omnidirectional mouse scrolling, but I think it would also still be okay to merge *as is* since its definitely an improvement on the old behaviour in any capacity.

**Comment by akien-mga** [comment]
Thanks!
