### PR TITLE
Physics interpolation: Fix 2D skinning

### LINKED ISSUE #92872: Physics interpolation doesn't interpolate Skeleton2D animation correctly, resulting in wobbly visuals
- Possibly related to https://github.com/godotengine/godot/issues/71974.

### Tested versions

- Reproducible in: 4.3.dev b7feebefa, 3.6.beta 945a49064f862a939fdfbc12f63e36ecfea0c8d4

### System information

Godot v4.3.dev (b7feebefa) - Fedora Linux 39 (KDE Plasma) - X11 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4090 (nvidia; 550.78) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

Physics interpolation doesn't interpolate Skeleton2D animation correctly, resulting in wobbly visuals.

I've tried disabling interpolation on specific nodes on the SkeletalPlayer scene, but the only thing that fixes the issue is disabling interpolation on the entire CharacterBody2D – which makes any movement not interpolated. I've also tried changing the process mode of the AnimationPlayer and/or AnimationTree to Physics instead of Idle, but that didn't help either.

This issue is still noticeable at 60 tps on a 120 Hz display, so it's not just at low physics FPS.

*All videos were recorded at 60 FPS.*

### 10 ticks per second, physics interpolation enabled

https://github.com/godotengine/godot/assets/180032/0a6ca1fa-c869-4091-be9c-b2e7144cb039

### 10 ticks per second, physics interpolation disabled

*Skeleton updates at the rendered framerate, so does it actually need to be interpolated here? I've tried disabling interpolation on the skeleton/AnimationPlayer/AnimationTree/Polygon2D nodes and it didn't help though. I've also tried changing the process mode of the AnimationPlayer and/or AnimationTree to Physics instead of Idle.*

https://github.com/godotengine/godot/assets/180032/dca4dfb3-a908-4f2f-85e3-bbb4c055bf2f

### 10 ticks per second, physics interpolation enabled, AnimationPlayer + AnimationTree using Physics callback mode

https://github.com/godotengine/godot/assets/180032/d84f7e84-9685-4755-809c-aa79fd4b4727

### 120 ticks per second, physics interpolation enabled

*At this stage, it looks pretty much the same whether interpolation is enabled or not.*

https://github.com/godotengine/godot/assets/180032/093d91df-396a-47f7-9cde-8aa9c8f0e530

### Steps to reproduce

- Create an animation that uses Skeleton2D.
- Enable physics interpolation and set physics ticks per second to 10.

### Minimal reproduction project (MRP)

[skeleton.zip](https://github.com/user-attachments/files/15741150/skeleton.zip)

### PR DESCRIPTION
**Pull request by rburing**
- Fixes https://github.com/godotengine/godot/issues/92872

### CODE REVIEW

**Review by lawnjelly — APPROVED** [review]
That is good, it looks like mostly a straight port fixes the issues in 4.x too, and this keeps the existing notification stack working.

File: scene/2d/skeleton_2d.cpp [hunk 1]
```diff
@@ -29,6 +29,7 @@
 /**************************************************************************/
 
 #include "skeleton_2d.h"
+#include "core/math/transform_interpolator.h"
```
Comment (AThousandShips) [inline scene/2d/skeleton_2d.cpp:32]:
```suggestion

#include "core/math/transform_interpolator.h"
```

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
