### PR TITLE
Don't ignore `audio/driver/output_latency.web`

### LINKED ISSUE #90906: Web audio is distorted when using headphones
### Tested versions

Reproducible: v4.2.dev4.official [549fcce5f], master [9bc49a66bae5e9e506f12df3b3e141c8da13f983]
Not reproducible: v4.1.4.stable.official [fe0e8e557], v4.2.dev3.official [013e8e3af]

### System information

Ubuntu 22.04.4 LTS - Firefox and Chrome

### Issue description

When I connect to bluetooth headphones, I get distorted audio. When using built-in speakers, the audio is correct. Can't reproduce it on other websites.

| 4.2.dev3 | 4.2.dev4 |
|--------|--------|
| <video src="https://github.com/godotengine/godot/assets/118438257/85c28ce8-0a01-4040-96f1-6a38cc454610"> | <video src="https://github.com/godotengine/godot/assets/118438257/03f88bcc-f161-4628-a746-d5eb35d14906"> |

### Steps to reproduce

Connect to bluetooth headphones and play audio on the web export/editor.

### Minimal reproduction project (MRP)

[MRP](https://github.com/godotengine/godot/files/15042856/q.zip)

### PR DESCRIPTION
**Pull request by kus04e4ek**
* Fixes: #90906.
* Introduced by: #78013.

### CODE REVIEW

File: main/main.cpp [hunk 1]
```diff
@@ -2337,13 +2337,16 @@ Error Main::setup(const char *execpath, int argc, char *argv[], bool p_second_ph
...
+	GLOBAL_DEF_RST("audio/driver/output_latency.web", 50);
+
 	Engine::get_singleton()->set_physics_ticks_per_second(GLOBAL_DEF_BASIC(PropertyInfo(Variant::INT, "physics/common/physics_ticks_per_second", PROPERTY_HINT_RANGE, "1,1000,1"), 60));
 	Engine::get_singleton()->set_max_physics_steps_per_frame(GLOBAL_DEF_BASIC(PropertyInfo(Variant::INT, "physics/common/max_physics_steps_per_frame", PROPERTY_HINT_RANGE, "1,100,1"), 8));
 	Engine::get_singleton()->set_physics_jitter_fix(GLOBAL_DEF("physics/common/physics_jitter_fix", 0.5));
 	Engine::get_singleton()->set_max_fps(GLOBAL_DEF(PropertyInfo(Variant::INT, "application/run/max_fps", PROPERTY_HINT_RANGE, "0,1000,1"), 0));
-	Engine::get_singleton()->set_audio_output_latency(GLOBAL_DEF_RST(PropertyInfo(Variant::INT, "audio/driver/output_latency", PROPERTY_HINT_RANGE, "1,100,1"), 15));
-	// Use a safer default output_latency for web to avoid audio cracking on low-end devices, especially mobile.
-	GLOBAL_DEF_RST("audio/driver/output_latency.web", 50);
+	Engine::get_singleton()->set_audio_output_latency(GLOBAL_GET("audio/driver/output_latency"));
```
Comment (akien-mga) [inline main/main.cpp:2349]: I would keep these grouped together. (Define, then set in Engine.)

**Review by akien-mga — APPROVED** [review]
Nice catch!

File: main/main.cpp (hunk 1 above)
Comment (kus04e4ek) [reply main/main.cpp:2349]: Like this?
```patch
diff --git a/main/main.cpp b/main/main.cpp
index ef76c372a63..cc1a1b28ce2 100644
--- a/main/main.cpp
+++ b/main/main.cpp
@@ -2337,15 +2337,15 @@ Error Main::setup(const char *execpath, int argc, char *argv[], bool p_second_ph
 			window_vsync_mode = DisplayServer::VSyncMode::VSYNC_DISABLED;
 		}
 	}
-
-	GLOBAL_DEF_RST(PropertyInfo(Variant::INT, "audio/driver/output_latency", PROPERTY_HINT_RANGE, "1,100,1"), 15);
-	// Use a safer default output_latency for web to avoid audio cracking on low-end devices, especially mobile.
-	GLOBAL_DEF_RST("audio/driver/output_latency.web", 50);
-
 	Engine::get_singleton()->set_physics_ticks_per_second(GLOBAL_DEF_BASIC(PropertyInfo(Variant::INT, "physics/common/physics_ticks_per_second", PROPERTY_HINT_RANGE, "1,1000,1"), 60));
 	Engine::get_singleton()->set_max_physics_steps_per_frame(GLOBAL_DEF_BASIC(PropertyInfo(Variant::INT, "physics/common/max_physics_steps_per_frame", PROPERTY_HINT_RANGE, "1,100,1"), 8));
 	Engine::get_singleton()->set_physics_jitter_fix(GLOBAL_DEF("physics/common/physics_jitter_fix", 0.5));
 	Engine::get_singleton()->set_max_fps(GLOBAL_DEF(PropertyInfo(Variant::INT, "application/run/max_fps", PROPERTY_HINT_RANGE, "0,1000,1"), 0));
+
+	GLOBAL_DEF_RST(PropertyInfo(Variant::INT, "audio/driver/output_latency", PROPERTY_HINT_RANGE, "1,100,1"), 15);
+	// Use a safer default output_latency for web to avoid audio cracking on low-end devices, especially mobile.
+	GLOBAL_DEF_RST("audio/driver/output_latency.web", 50);
+	
 	Engine::get_singleton()->set_audio_output_latency(GLOBAL_GET("audio/driver/output_latency"));
 
 	GLOBAL_DEF("debug/settings/stdout/print_fps", false);
```

Comment (akien-mga) [reply main/main.cpp]: Yep, looks good!

Comment (kus04e4ek) [reply main/main.cpp]: Pushed these changes

**Comment by akien-mga** [comment]
Thanks!
