### PR TITLE
Fixes AssetLib crash when JPG module is disabled

### LINKED ISSUE #28436: AssetLib crashes when JPG module is disabled
**Godot version:**
9ef46996cdd94a596b9b4873c829393caf9e9974

**OS/device including version:**
Win7 x64 SP1

**Issue description:**
editor crashes when when failing to retrieve images from libraries in the AssetLib.

EditorAssetLibrary::_image_request_completed: Error getting image file from URL: https://raw.githubusercontent.com/brunosxs/SMRT-Godot/master/docs/images/big_logo.png
     At: editor\plugins\asset_library_editor_plugin.cpp:828

**Steps to reproduce:**
AssetLib > Category > 3D Tools

**Full trace log:**

[0] ???

[1] ???

[2] EditorAssetLibrary::_image_update (d:\godotproject\engine\editor\plugins\asset_library_editor_plugin.cpp:750)

[3] EditorAssetLibrary::_request_image (d:\godotproject\engine\editor\plugins\asset_library_editor_plugin.cpp:899)

[4] EditorAssetLibrary::_http_request_completed (d:\godotproject\engine\editor\plugins\asset_library_editor_plugin.cpp:1222)

[5] MethodBind4<EditorAssetLibrary,int,int,PoolVector const &,PoolVector const &>::call (d:\godotproject\engine\core\method_bind.gen.inc:2993)

[6] Object::call (d:\godotproject\engine\core\object.cpp:942)

[7] Object::emit_signal (d:\godotproject\engine\core\object.cpp:1228)

[8] HTTPRequest::_request_done (d:\godotproject\engine\scene\main\http_request.cpp:402)

[9] MethodBind4<HTTPRequest,int,int,PoolVector const &,PoolVector const &>::call (d:\godotproject\engine\core\method_bind.gen.inc:2993)

[10] Object::call (d:\godotproject\engine\core\object.cpp:942)

[11] MessageQueue::_call_function (d:\godotproject\engine\core\message_queue.cpp:256)

[12] MessageQueue::flush (d:\godotproject\engine\core\message_queue.cpp:305)

[13] SceneTree::iteration (d:\godotproject\engine\scene\main\scene_tree.cpp:477)

[14] Main::iteration (d:\godotproject\engine\main\main.cpp:1862)

[15] widechar_main (d:\godotproject\engine\platform\windows\godot_windows.cpp:150)

[16] main (d:\godotproject\engine\platform\windows\godot_windows.cpp:185)

[17] __scrt_common_main_seh (d:\agent_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)

[18] BaseThreadInitThunk

-- END OF BACKTRACE --

### PR DESCRIPTION
**Pull request by timothyqiu**
This fixes #28436

JPG module is optional, so check it's existence before using.

To reproduce the crash, build Godot with `module_jpg_enabled=no`, and go to the second page of "3D Tools" category in AssetLib. ([Latoso](https://godotengine.org/asset-library/asset/288) uses a JPEG image as icon.)

### CODE REVIEW

File: editor/plugins/asset_library_editor_plugin.cpp [hunk 1]
```diff
@@ -728,7 +728,7 @@ void EditorAssetLibrary::_image_update(bool use_cache, bool final, const PoolByt
 		if (r.ptr()) {
 			if (memcmp(&r[0], &png_signature[0], 8) == 0) {
 				image->copy_internals_from(Image::_png_mem_loader_func(r.ptr(), len));
-			} else if (memcmp(&r[0], &jpg_signature[0], 3) == 0) {
+			} else if ((memcmp(&r[0], &jpg_signature[0], 3) == 0) && Image::_jpg_mem_loader_func) {
```
Comment (akien-mga) [inline editor/plugins/asset_library_editor_plugin.cpp]: Might be worth adding the same check for PNG. It's not optional right now and unlikely to become, but who knows :)

**Review by bojidar-bg — APPROVED** [review]
Looking good!

Thanks! :smiley:

File: editor/plugins/asset_library_editor_plugin.cpp [hunk 2]
```diff
@@ -726,9 +726,9 @@ void EditorAssetLibrary::_image_update(bool use_cache, bool final, const PoolByt
 		uint8_t jpg_signature[3] = { 255, 216, 255 };
 
 		if (r.ptr()) {
-			if (memcmp(&r[0], &png_signature[0], 8) == 0) {
+			if ((memcmp(&r[0], &png_signature[0], 8) == 0) && Image::_png_mem_loader_func) {
 				image->copy_internals_from(Image::_png_mem_loader_func(r.ptr(), len));
-			} else if (memcmp(&r[0], &jpg_signature[0], 3) == 0) {
+			} else if ((memcmp(&r[0], &jpg_signature[0], 3) == 0) && Image::_jpg_mem_loader_func) {
```
Comment (bojidar-bg) [inline editor/plugins/asset_library_editor_plugin.cpp]: Actually, you don't need to parenthesize `==` here, since `&&` has lower priority.

Comment (timothyqiu) [reply editor/plugins/asset_library_editor_plugin.cpp]: Yes. But I think there are many things going on in this condition expression. Parentheses can make this complex expression easier to read, so the reader won't have to remember the operator precedence thing.

ref:
* https://rules.sonarsource.com/c/RSPEC-864
* https://wiki.sei.cmu.edu/confluence/display/c/EXP00-C.+Use+parentheses+for+precedence+of+operation

Comment (bojidar-bg) [reply editor/plugins/asset_library_editor_plugin.cpp]: Well, you wouldn't parenthesize `a == 4 && c == 6`, would you? Either way, it is fine as-is.

**Comment by akien-mga** [comment]
Thanks!
