### PR TITLE
Fix node name in the SceneTreeEditor allows a node to have no name

### LINKED ISSUE #70981: Godot 4 beta allows a node to have no name
### Godot version

Godot 4 beta 10

### System information

Windows 10, mobile mode

### Issue description

You can give a node a blank name by deleting its name and press enter
image

### Steps to reproduce

1. Create any node
2. Double click it, you should now be able to rename it
3. Backspace, than enter
4. You got a node with no name

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by nongvantinh**
Fixes: #70981

Regression occur at: 3a2abf7486f00005248ece35dc2c0b67afe3119e

When user deletes the name of a newly created node. Which currently has the name of its _class name_ and causes the statement below to **return** but forget to revert the name of the **tree item** in editor to the original state.

https://github.com/godotengine/godot/blob/269fa200d04ae96b0114b788e18df638c5fb164b/editor/scene_tree_editor.cpp#L995-L997

### CODE REVIEW

File: editor/scene_tree_editor.cpp [hunk 1]
```diff
@@ -993,6 +993,10 @@ void SceneTreeEditor::_renamed() {
 	}
 
 	if (new_name == n->get_name()) {
+		if (which->get_text(0).is_empty()) {
```
Comment (KoBeWi) [inline editor/scene_tree_editor.cpp:996]: This can be unconditional I think.

**Review by KoBeWi — APPROVED** [review]

File: editor/scene_tree_editor.cpp (hunk 1 above)
Comment (akien-mga) [reply editor/scene_tree_editor.cpp:996]: Yeah empty `which->get_text(0)` is already handled above:
```cpp
String raw_new_name = which->get_text(0);
if (raw_new_name.strip_edges().is_empty()) {
```

Comment (nongvantinh) [reply editor/scene_tree_editor.cpp:996]: The reason I do that is:

There is the case that the user changes the name of this node in the editor to have the same name as its `class`, so the function basically just **return**.

But if it removes the name of this node and leaves it empty, the function must *revert* to the `class_name`

So the `new_name` here hold its `class_name`:
https://github.com/godotengine/godot/blob/98ed75f9e05f600b8cb5372df424ca3ae2f56ffe/editor/scene_tree_editor.cpp#L971-L981

but it does not classify which case, either because it is `empty` or because it has  `have the same name as its class`:
https://github.com/godotengine/godot/blob/98ed75f9e05f600b8cb5372df424ca3ae2f56ffe/editor/scene_tree_editor.cpp#L995-L1001

I cannot put the logic in this block code:
https://github.com/godotengine/godot/blob/98ed75f9e05f600b8cb5372df424ca3ae2f56ffe/editor/scene_tree_editor.cpp#L971-L972

because there are edge cases, where:
https://github.com/godotengine/godot/blob/98ed75f9e05f600b8cb5372df424ca3ae2f56ffe/editor/scene_tree_editor.cpp#L981
will verify and fix that.

**Comment by akien-mga** [comment]
Thanks!
