### PR TITLE
Show tooltips even when paused or time_scale is 0

### LINKED ISSUE #29101: Tooltips don't appear when `Engine.time_scale` is 0
**Godot version:**
v3.1.stable.mono.official

**OS/device including version:**
Windows 10

**Issue description:**
If i change the parameter timescale to 0 (ex. Engine.SetTimeScale(0f) ). After this, the interface hints are not displayed during the game.

### LINKED ISSUE #29362: Tooltips are not shown when the scene tree is paused.
**Godot version:** master (e9be875)

**OS/device including version:** Arch Linux

**Issue description:** Tooltips are not shown when the scene tree is paused.

This is possibly caused by `tooltip_timer`s being managed in the root viewport's `NOTIFICATION_INTERNAL_PROCESS`. The root viewport likely has a `PAUSE_MODE_INHERIT` by default, so the notification in question won't be sent when the tree is paused.

**Steps to reproduce:**

* Add a control with a tooltip.
* Hover it while unpaused. The tooltip will show up normally.
* Pause the scene tree.
* Hover the control while paused. The tooltip won't show up, regardless of the control's own `pause_mode`.

**Minimal reproduction project:** [pause-tooltip.zip](https://github.com/godotengine/godot/files/3243394/pause-tooltip.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #29101
Fixes #29362

I changed the `gui.tooltip_timer` in Viewport from float to SceneTreeTimer (so it's independent) and added a property `ignore_time_scale` for SceneTreeTimers.

Also I took the chance to move the initialization of SceneTreeTimer variables away from the constructor.

### CODE REVIEW

File: scene/main/scene_tree.h [hunk 1]
```diff
@@ -64,9 +65,12 @@ class SceneTreeTimer : public Reference {
 	void set_pause_mode_process(bool p_pause_mode_process);
 	bool is_pause_mode_process();
 
+	void set_ignore_time_scale(bool p_ignore);
+	bool is_ignore_time_scale();
+
 	void release_connections();
 
-	SceneTreeTimer();
+	SceneTreeTimer(){};
```
Comment (akien-mga) [inline scene/main/scene_tree.h:73]:
```suggestion
	SceneTreeTimer() {}
```

File: scene/main/viewport.cpp [hunk 2]
```diff
@@ -533,15 +533,6 @@ void Viewport::_notification(int p_what) {
 			RS::get_singleton()->viewport_set_active(viewport, false);
 			RenderingServer::get_singleton()->viewport_set_parent_viewport(viewport, RID());
```
Comment (akien-mga) [inline scene/main/viewport.cpp:535]: You can remove that line too.

File: scene/main/scene_tree.h (hunk 1 above)
Comment (KoBeWi) [reply scene/main/scene_tree.h:73]: But the space was removed by clang-format...

Comment (akien-mga) [reply scene/main/scene_tree.h:73]: Yes, but that's because the trailing semicolon is a bug.

**Comment by ShatReal** [comment]
Will this ever be merged? I'd like to see it merged to simplify pausing.

**Comment by Calinou** [comment]
This PR needs to be tested again with the pause mode changes from https://github.com/godotengine/godot/pull/46191.

**Comment by KoBeWi** [comment]
I just rebased and tested it. The pause system change didn't affect this PR, as it relies on SceneTreeTimer.

**Comment by Calinou** [comment]
This PR likely conflicts with https://github.com/godotengine/godot/pull/34544. I'm not sure if we should wait for that one to be merged.

**Review by Calinou — APPROVED** [review]
Looks good to me, but keep in mind https://github.com/godotengine/godot/pull/34544 allows setting an arbitrary time scale factor for Timer nodes (rather than an all-or-nothing "ignore time scale" option). If both PRs are merged, this means SceneTreeTimer will have a different feature set compared to regular Timer nodes. This may or may not be a problem, but I think we should harmonize their feature set as much as possible.

**Comment by KoBeWi** [comment]
Rebased. It would be nice to have this merged before #50780

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by lekoder** [comment]
This fixes "no tooltips on pause screen even if pause mode for pause popup is set to process" bug I was having with ΔV: Rings of Saturn. I detected no side-effects so far.
