### PR TITLE
Fix pressed keys reset when hiding a window on Windows

### LINKED ISSUE #104479: Hold shift to add `environment` and `sun` to scene no longer works on 4.4
### Tested versions

-Reproducible in: v4.4.1.rc2.mono.official [abef5e0d2]
-Reproducible in: 4.4
-Working on: v4.3.stable.mono.official [77dcf97d8]

### System information

Windows 10 - 4.4 - Vulkan (Foward+) NVIDEA GeForce 1070

### Issue description

Holding `Shift` while adding the environment or sun to the scene should be adding both instead of just one.
This feature is stated by the tooltip on the buttons there.
This used to work on 4.3, but stopped working since 4.4. Including the latest 4.4.1-rc2. 

**Not working on 4.4**, holding shift while clicking on the button:

https://github.com/user-attachments/assets/5e834644-8c73-437b-9a6c-74d270875322

**Working on 4.3**, holding shift while clicking on the button:

https://github.com/user-attachments/assets/60154fb1-145e-4460-9e38-8847b58bdf3e

### Steps to reproduce

- Open a new 3D scene.
- Click 3 dots to 'Edit sun and environment settings'
- Hold `shift` and click on the "Add Sun" or "Add Environment" to the scene

Result: Only one is added to the scene.
Expected: Both Sun and Environment are added to the scene.

### Minimal reproduction project (MRP)

No need. Any empty project.

### PR DESCRIPTION
**Pull request by Hilderin**
- Fixes #104479

The problem was introduced in #99010 to fix an issue where the user was unable to resize the floating window or use buttons in the editor when the embedded game was activated on Windows. Prior to #99010, the window needed to be focused in order to be resized using the mouse. The modification, however, introduced a side effect: it reset the pressed keys in `Input` when hiding a window, because deactivation was no longer handled by the timer.

By retaining the timer solely for the deactivation process, the original issue remains resolved, and it also fixes #104479, as the pressed keys are no longer reset immediately when calling the `hide` method on a window.

### CODE REVIEW

File: platform/windows/display_server_windows.cpp [hunk 1]
```diff
@@ -4601,9 +4601,12 @@ LRESULT DisplayServerWindows::WndProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARA
...
 			// The problem with the timer is that the window cannot be resized or the buttons cannot be used correctly
 			// if the window is not activated first. This happens because the code in the activation process runs
-			// after the mouse click is handled. To address this, the timer is now used only when the window is created.
+			// after the mouse click is handled. To address this, the timer is now used only during the window creation,
+			// and only as part of the activation process. We don't want 'Input::release_pressed_events()'
+			// to be called immediately in '_process_activate_event' when the window is not yet activated,
+			// as it would reset the currently pressed keys when hiding a window, which is incorrect behavior.
 			windows[window_id].activate_state = GET_WM_ACTIVATE_STATE(wParam, lParam);
-			if (windows[window_id].first_activation_done) {
+			if (windows[window_id].first_activation_done && windows[window_id].activate_state) {
```
Comment (bruvzg) [inline platform/windows/display_server_windows.cpp]:
```suggestion
			if (windows[window_id].first_activation_done && (windows[window_id].activate_state == WA_ACTIVE || windows[window_id].activate_state == WA_CLICKACTIVE)) {
```

**Review by bruvzg — APPROVED** [review]

File: platform/windows/display_server_windows.cpp (hunk 1 above)
Comment (akien-mga) [reply platform/windows/display_server_windows.cpp]: @Hilderin Are you available to make these changes (and rebase as the last update was many months ago)?

**Comment by Repiteo** [comment]
Rebased to include @bruvzg's suggestion

**Comment by Repiteo** [comment]
Thanks!
