### PR TITLE
Make `backward` be parameter of the `AnimationTree` in the `AnimationNodeAnimation`

### LINKED ISSUE #100018: AnimationTrees' progress with Ping-pong loop are corrupted when there are multiple instantiated same AnimationTrees on the scene
### Tested versions

Reproduced on 4.4 dev 5 and 4.3 Stable

### System information

Godot v4.4.dev5 - Windows 10.0.22631 - Single-window, 1 monitor - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (Advanced Micro Devices, Inc.; 32.0.12019.1028) - Intel(R) Core(TM) i3-10105F CPU @ 3.70GHz (8 threads)

### Issue description

Animation pace is inconsistent, and at times just goes to hell.

The first video showcases the animation pace inconsistency

https://github.com/user-attachments/assets/8c5b12cc-af2c-4c51-9e24-d221b0fe3df9

The second video I've also seen happen in the MRP at times, but only have a video of it happening in my game dummy scene, Observe Walk Calm in animation tree not completely bouncing going between 0 and 1, also at the start it may feel stuttery, but that's because it's a 30 fps video of a 60hz setup, and it's actually not visible but the animation was very aggressively switching back and forth from frame to frame

https://github.com/user-attachments/assets/78787d64-ea68-4e53-85c5-ed574fc494f4

### Steps to reproduce

Inconsistent behavior, with no good steps to reproduce found yet beyond it seeming like it has something to do with the Transition node in Animation Tree. Animation Player animation runs smoothly consistently. the MRP at times may or may not produce the broken results.

### Minimal reproduction project (MRP)

[Bug.zip](https://github.com/user-attachments/files/18012310/Bug.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
- Fixes #100018

Properties that need to be managed for each AnimationTree should be parameterized for the same reason as https://github.com/godotengine/godot/issues/22887.

### CODE REVIEW

File: scene/animation/animation_blend_tree.h [hunk 1]
```diff
@@ -36,6 +36,8 @@
 class AnimationNodeAnimation : public AnimationRootNode {
 	GDCLASS(AnimationNodeAnimation, AnimationRootNode);
 
+	StringName backward = PNAME("backward"); // Only used by pingpong animation.
```
Comment (AThousandShips) [inline scene/animation/animation_blend_tree.h:39]: Isn't this for translation of names for the editor?

Comment (AThousandShips) [reply scene/animation/animation_blend_tree.h]: Saw that it was used to declare a property not just as a placeholder so might have been wrong

Comment (TokageItLab) [reply scene/animation/animation_blend_tree.h]: It is fine to remove PNAME, as the property does not appear in the editor, thanks.

**Comment by mrjustaguy** [comment]
I can confirm this Fixes the broken Ping Pong looping

**Review by akien-mga — APPROVED** [review]

**Review by fire — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
