### PR TITLE
Fix a command buffer leak that occurs in D3D12

### LINKED ISSUE #94251: "Pages in use exist at exit in PagedAllocator" on exit using D3D12
### Tested versions

- Reproducible in 4.3 beta 3
- Reproducible in custom build based on 97b8ad1af0

### System information

Windows 10 - v4.3.beta3.official [82cedc83c]

### Issue description

```
ERROR: Pages in use exist at exit in PagedAllocator: 25VersatileResourceTemplateIJN26RenderingDeviceDriverD3D1210BufferInfoENS0_11TextureInfoES2_S2_NS0_16VertexFormatInfoENS0_17CommandBufferInfoENS0_15FramebufferInfoENS0_10ShaderInfoENS0_14UniformSetInfoENS0_14RenderPassInfoENS0_22TimestampQueryPoolInfoEEE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
```

Backtrace:
```
PagedAllocator<VersatileResourceTemplate<RenderingDeviceDriverD3D12::BufferInfo, RenderingDeviceDriverD3D12::TextureInfo, RenderingDeviceDriverD3D12::TextureI[...]
RenderingDeviceDriverD3D12::~RenderingDeviceDriverD3D12(this=0x00000182abca90b0) at rendering_device_driver_d3d12.cpp:6250:1
void memdelete<RenderingDeviceDriver>(p_class=0x00000182abca90b0) at memory.h:116:13
RenderingContextDriverD3D12::driver_free(this=0x00000182abc7fce0, p_driver=0x00000182abca90b0) at rendering_context_driver_d3d12.cpp:246:2
RenderingDevice::finalize(this=0x00000182abca7430) at rendering_device.cpp:5869:12
RenderingDevice::~RenderingDevice(this=0x00000182abca7430) at rendering_device.cpp:6558:2
void memdelete<RenderingDevice>(p_class=0x00000182abca7430) at memory.h:116:13
DisplayServerWindows::~DisplayServerWindows(this=0x00000182abc5df00) at display_server_windows.cpp:6116:3
void memdelete<DisplayServer>(p_class=0x00000182abc5df00) at memory.h:116:13
finalize_display() at main.cpp:351:2
Main::cleanup(p_force=false) at main.cpp:4330:2
widechar_main(argc=5, argv=0x00000182a8ba8640) at godot_windows.cpp:184:2
_main() at godot_windows.cpp:206:11
main(argc=5, argv=0x00000182a8b27ae0) at godot_windows.cpp:225:9
```

### Steps to reproduce

Run editor with `--rendering-method forward_plus --rendering-driver d3d12` and close it.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by alessand10**
This PR should fix: #94251

Memory allocated for command buffers in DX12 is never freed. In Vulkan, freeing the command pool also frees the command buffers that have been allocated within the pool. This fix mirrors Vulkan behavior by having each command pool track their respective command buffers. When a command pool is freed, its command buffers are as well.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Makes sense to me. 

I would like @DarioSamo or @RandomShaper to take a quick look as well before we merge

**Comment by RandomShaper** [comment]
The rationale makes sense. However, the implementation fails to follow the 'as close to zero allocations as possible' mindset. I think you could use `SelfList` to achieve that.

**Comment by clayjohn** [comment]
@alessand10 Could you make the change requested by RandomShaper? I think after doing that, this should be ready to merge

**Comment by AThousandShips** [comment]
You accidentally wiped your branch when trying to restore, to get back to before the rebase please use `git reset --hard 6ed73b1` and try again

**Comment by alessand10** [comment]
@AThousandShips Sorry for the trouble. Will I need to create a new PR?

File: drivers/d3d12/rendering_device_driver_d3d12.h [hunk 1]
```diff
@@ -458,6 +461,9 @@ class RenderingDeviceDriverD3D12 : public RenderingDeviceDriver {
 	// Leveraging knowledge of actual usage and D3D12 specifics (namely, command lists from the same allocator
 	// can't be freely begun and ended), an allocator per list works better.
 	struct CommandBufferInfo {
+		// Store a self list reference to be used by the command pool
```
Comment (AThousandShips) [inline drivers/d3d12/rendering_device_driver_d3d12.h:464]:
```suggestion
		// Store a self list reference to be used by the command pool.
```
Per the [comment style](https://docs.godotengine.org/en/latest/contributing/development/code_style_guidelines.html#comment-style-guide).

**Review by AThousandShips — APPROVED** [review]

**Comment by clayjohn** [comment]
Looks great! The final step before merging is to squash all the commits together so that the whole PR only contains 1 big commit with all your changes. We like to merge one commit at a time to keep the git history clean and navigable. 

If you don't know how to do that, we have a helpful tutorial in the official documentation https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase

**Comment by alessand10** [comment]
@clayjohn Thank you for your help and guidance!

File: drivers/d3d12/rendering_device_driver_d3d12.h [hunk 2]
```diff
@@ -458,6 +461,9 @@ class RenderingDeviceDriverD3D12 : public RenderingDeviceDriver {
 	// Leveraging knowledge of actual usage and D3D12 specifics (namely, command lists from the same allocator
 	// can't be freely begun and ended), an allocator per list works better.
 	struct CommandBufferInfo {
+		// Store a self list reference to be used by the command pool.
+		SelfList<CommandBufferInfo> command_buffer_info_elem;
```
Comment (RandomShaper) [inline drivers/d3d12/rendering_device_driver_d3d12.h:465]: I think we can do this so you don't need to add a constructor:

```suggestion
		SelfList<CommandBufferInfo> command_buffer_info_elem(this);
```

I'd swear we are already using this pattern somewhere else. Not a big deal, in any case.

**Review by RandomShaper — APPROVED** [review]
Sweet!

Just left a little suggestion, but feel free to ignore it. I consider this is fine the way it already is.

File: drivers/d3d12/rendering_device_driver_d3d12.h (hunk 2 above)
Comment (alessand10) [reply drivers/d3d12/rendering_device_driver_d3d12.h:465]: I'll absolutely make that change. I came across the following use of SelfList while digging through some examples of how to use it and figured that the standard might be to initialize it in a constructor:

https://github.com/godotengine/godot/blob/2b7ea6223bd0bdaa75706849c9dee1a82b2e2d01/core/object/worker_thread_pool.h#L74C1-L97C4

But I'm now realizing that constructor must only exist because of the bit fields.

**Review by clayjohn — APPROVED** [review]
Thanks for your quick responses to feedback! That was a bit of a whirlwind day. But it looks great to merge now

**Comment by alessand10** [comment]
@clayjohn My second PR was definitely more chaotic than I was aiming for, but I appreciate everyone's help and I'm looking forward to learning more about the engine and contribution process. Thanks again!

**Comment by akien-mga** [comment]
Thanks!
