### PR TITLE
Do not attempt deleting local cache in `Resource::_teardown_duplicate_from_variant`.

### LINKED ISSUE #112391: Deep duplication of a dictionary in _validate_property of a resource causes a crash
### Tested versions

4.5-rc2, 4.5, 4.5.1

### System information

Godot v4.5.1.stable - Windows 11 (build 22631) - Multi-window, 3 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XT (Advanced Micro Devices, Inc.; 32.0.11037.4004) - AMD Ryzen Threadripper 7970X 32-Cores (64 threads) - 127.5 GiB memory

### Issue description

While calling duplicate(true) on the dictionary passed in for _validate_properties, it causes a crash. This isn't something I expect others to do, but for our custom version of the engine we modify the property dictionary in such a way that it needs a deep copy. Regardless I don't think calling duplicate on a dictionary should ever cause a crash.

I imagine it's related to https://github.com/godotengine/godot/pull/100673

Relevant section of call stack:
```
    godot.windows.editor.dev.x86_64.exe!_free_base(void * block) Line 105   C++
    godot.windows.editor.dev.x86_64.exe!Memory::free_static(void * p_ptr, bool p_pad_align) Line 201    C++
    godot.windows.editor.dev.x86_64.exe!memdelete<HashMap<Ref<Resource>,Ref<Resource>,HashMapHasherDefault,HashMapComparatorDefault<Ref<Resource>>,DefaultTypedAllocator<HashMapElement<Ref<Resource>,Ref<Resource>>>>>(HashMap<Ref<Resource>,Ref<Resource>,HashMapHasherDefault,HashMapComparatorDefault<Ref<Resource>>,DefaultTypedAllocator<HashMapElement<Ref<Resource>,Ref<Resource>>>> * p_class) Line 142  C++
    godot.windows.editor.dev.x86_64.exe!Resource::_teardown_duplicate_from_variant() Line 589   C++
    godot.windows.editor.dev.x86_64.exe!Dictionary::recursive_duplicate(bool p_deep, ResourceDeepDuplicateMode p_deep_subresources_mode, int recursion_count) Line 620  C++
    godot.windows.editor.dev.x86_64.exe!Dictionary::duplicate(bool p_deep) Line 584 C++
```

### Steps to reproduce

Run the project.

### Minimal reproduction project (MRP)

Run the project.

[dictionary_duplicate_deep_crash_mrp.zip](https://github.com/user-attachments/files/23345208/dictionary_duplicate_deep_crash_mrp.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/112391
Likely regressions from https://github.com/godotengine/godot/pull/100673

`Dictionary::recursive_duplicate` (as well as `Array`) call `Resource::_teardown_duplicate_from_variant` to clean up cache which can be created by `Resource::_duplicate_from_variant` when finished. But if dictionary duplication was triggered in the process of resource duplication, cache is pointing to the local variable of `Resource::duplicate`, so it was trying to `memdelete` memory on stack.

### CODE REVIEW

File: core/io/resource.h [hunk 1]
```diff
@@ -94,6 +94,7 @@ class Resource : public RefCounted {
 
 	using DuplicateRemapCacheT = HashMap<Ref<Resource>, Ref<Resource>>;
 	static thread_local inline DuplicateRemapCacheT *thread_duplicate_remap_cache = nullptr;
+	static thread_local inline bool thread_duplicate_remap_cache_local = false;
```
Comment (Ivorforce) [inline core/io/resource.h]: I think it's easier to think about this in terms of allocations (i.e. inverted)

```suggestion
	static thread_local inline bool thread_duplicate_remap_cache_needs_deallocation = false;
```

**Review by Ivorforce — APPROVED** [review]
The fix makes sense to me.

What I don't understand is why the remap cache isn't _always_ local. Duplication is a tree operation, so why isn't the duplication tracking map initialized and destructed in the top node (RAII style), but instead some operation in the tree is allocating it on the stack on demand?
Since this is an important fix, I'm fine with merging this change as-is, but I think this setup needs further review in the future.

**Review by RandomShaper — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.5.2.
