### PR TITLE
Fix find in files auto search when changing theme

### LINKED ISSUE #112706: Why does changing theme/language trigger `find in files` re-search?
### Tested versions

- Reproducible in v4.6.dev3.official [9d84f3d13]

### System information

Godot v4.6.dev3 - Windows 11 (build 26100) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 32.0.15.7680) - 13th Gen Intel(R) Core(TM) i5-13600KF (20 threads) - 47.84 GiB memory

### Issue description

https://github.com/user-attachments/assets/4746adc3-4b7c-430f-9d99-beb6faf8b559

https://github.com/godotengine/godot/blob/e6aa06d3de372513bedb036d2adb1052a9b4b87f/editor/script/find_in_files.cpp#L864-L876

Search results can keep original information if contents have been modified such as line number, matches count. 
Search results might also contain users' operation traces such as vertical scroll position, highlighted item.
If rebuilding the search tree, these old information will be lost.

On the other hand, there may be many search results (introduced by #104676 ), when the user changes the theme, each of which will rebuild the search tree causing the engine to stutter, maybe.

### Steps to reproduce

1. Search something
2. Change editor theme's `Style` or `Color Preset`
3. FindInFiles result will search automatically.

### Minimal reproduction project (MRP)

NA

### PR DESCRIPTION
**Pull request by jinyangcruise**
Fix #112706.

When NOTIFICATION_THEME_CHANGED occurs, modify:
- Tree's font, 
- Tree's font_size
- TreeItem's text color
- TreeItem's button texture

These 4 'properties' are particularly set in `_on_result_found` to suit FindInFilesPanel, so we only modify them when theme changes.

### CODE REVIEW

File: editor/script/find_in_files.cpp [hunk 1]
```diff
@@ -864,15 +864,7 @@ void FindInFilesPanel::stop_search() {
 void FindInFilesPanel::_notification(int p_what) {
 	switch (p_what) {
 		case NOTIFICATION_THEME_CHANGED: {
-			_search_text_label->add_theme_font_override(SceneStringName(font), get_theme_font(SNAME("source"), EditorStringName(EditorFonts)));
-			_search_text_label->add_theme_font_size_override(SceneStringName(font_size), get_theme_font_size(SNAME("source_size"), EditorStringName(EditorFonts)));
```
Comment (kitbdev) [inline editor/script/find_in_files.cpp:869]: The search label no longer uses the code font, is this intentional?

File: editor/script/find_in_files.cpp [hunk 2]
```diff
@@ -964,6 +956,38 @@ void FindInFilesPanel::_on_result_found(const String &fpath, int line_number, in
...
+		if (_with_replace) {
+			file_item->set_button(0, file_item->get_button_by_id(0, FIND_BUTTON_REPLACE), replace_texture);
+		}
+		file_item->set_button(0, file_item->get_button_by_id(0, FIND_BUTTON_REMOVE), remove_texture);
+
+		TreeItem *result_item = file_item->get_first_child();
+		while (result_item) {
+			if (_with_replace) {
+				result_item->set_button(1, result_item->get_button_by_id(0, FIND_BUTTON_REPLACE), replace_texture);
+				result_item->set_button(1, result_item->get_button_by_id(0, FIND_BUTTON_REMOVE), remove_texture);
```
Comment (kitbdev) [inline editor/script/find_in_files.cpp]: I'm getting errors when changing theme setting with replace results open:
`ERROR: scene\gui\tree.cpp:1444 - Index p_index = -1 is out of bounds (cells[p_column].buttons.size() = 2)`

I think this needs to use column 1 in `get_button_by_id`, and maybe in the one above as well, but not sure.

File: editor/script/find_in_files.cpp (hunk 1 above)
Comment (jinyangcruise) [reply editor/script/find_in_files.cpp:869]: I find there is no difference to particularly set search label font/font_size. And this label is in the same row with some other controls like _status_label, _keep_results_button, _refresh_button, _cancel_button whose font/font_size is not set particularly. So I remove this to let them more consistent.

File: editor/script/find_in_files.cpp (hunk 2 above)
Comment (jinyangcruise) [reply editor/script/find_in_files.cpp]: My bad.

Comment (jinyangcruise) [reply editor/script/find_in_files.cpp]: And maybe the error you saw is realted to #112718.

Comment (jinyangcruise) [reply editor/script/find_in_files.cpp]: I have changed column to 1. Could you check this again?

**Review by kitbdev — APPROVED** [review]
Works as expected.

**Comment by Repiteo** [comment]
Thanks!
