### PR TITLE
Fix collision detection for degenerate capsules

### LINKED ISSUE #59632: Rigidbody several regressions in godot 4.0
### Godot version

4.0 alpha 3

### System information

Linux mint 

### Issue description

Under certain circunstances, the body teleports upwards. Mostly noticiable when the body stop  making contact with the floor and the wall. Is hard to replicate, but i made a project that i think it shows it well

https://user-images.githubusercontent.com/64601424/160404052-6401b2f7-38a5-4aff-a92a-3828119b7c7b.mp4

.

### Steps to reproduce

Create a platform with a collisionbody (Static, kinematic or Rigidbody dont alter the result) and a wall.
move a sphere towards the corner.

### Minimal reproduction project

[BugPhysics.zip](https://github.com/godotengine/godot/files/8362937/BugPhysics.zip)

### PR DESCRIPTION
**Pull request by rburing**
In `GodotCapsuleShape3D::get_supports` and `GodotCapsuleShape2D::get_supports`, return a point instead of an edge of length zero in case the capsule degenerates to a sphere or circle.

Fixes https://github.com/godotengine/godot/issues/59632

### CODE REVIEW

File: servers/physics_2d/godot_shape_2d.cpp [hunk 1]
```diff
@@ -370,7 +370,7 @@ void GodotCapsuleShape2D::get_supports(const Vector2 &p_normal, Vector2 *r_suppo
 
 	real_t d = n.y;
 
-	if (Math::abs(d) < (1.0 - _SEGMENT_IS_VALID_SUPPORT_THRESHOLD)) {
+	if (height > 2.0 * radius && Math::abs(d) < (1.0 - _SEGMENT_IS_VALID_SUPPORT_THRESHOLD)) {
```
Comment (akien-mga) [inline servers/physics_2d/godot_shape_2d.cpp:373]: Might be worth adding some comments, what you explained in the PR/issue isn't immediately obvious when reading this.

Also, what happens if `height < 2.0 * radius`?  Is it valid to handle that as a sphere?

Comment (rburing) [reply servers/physics_2d/godot_shape_2d.cpp:373]: In a capsule there are balls of radius `radius` centered at the centers of end caps of a cylinder with radius `radius`, and the `height` is counted including the balls, so `height >= 2.0 * radius` in general; the only degenerate case is `height == 2.0 * radius`. In Godot the `>=` seems to be enforced (only?) by the inspector: trying to make `height` smaller than `2.0 * radius` will decrease the radius, etc.

I think the code is pretty understandable once you see that there are two cases for the `if` statement and the first case depends on the cylinder (respectively rectangle) part of the capsule having a nonzero (half-)height, so I'll just make `h = height * 0.5 - radius` a local variable to be used in both branches, and add a comment to its definition.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
