### PR TITLE
Clear textures before setting new textures

### LINKED ISSUE #21718: BitmapFont resource leak?
**Godot version:**
3.1a1

**OS/device including version:**
Windows 10 x64
GTX750/PCIe/SSE2

**Issue description:**
Sorry if this bug is very general.  Over the last week or so, my project had been taking longer and longer to build.  Over time, I thought I was having an issue similar to #20566 , but after a while I found the actual culprit:
image

Somehow, this file ballooned in size!  Unable to open it in anything but a hex editor, I saw the problem was with the `textures` key.  It specified something like `textures = [ ExtResource( 1 ), ExtResource( 1 ), ... ]` over and over again.  I nuked this key and everything started to work again as normal.  

**Steps to reproduce:**
I'm afraid I haven't figured out the culprit, as I've so far been unable to get this to happen again.  Will update the issue if I can figure out what happened.

Attached is the resource file and the font itself for reference.

[font - Copy.txt](https://github.com/godotengine/godot/files/2344365/font.-.Copy.txt)
spelunkid_font

### PR DESCRIPTION
**Pull request by LittleWhite-tb**
My attempt to fix #21718.

### CODE REVIEW

File: scene/resources/font.cpp [hunk 1]
```diff
@@ -178,6 +178,7 @@ PoolVector<int> BitmapFont::_get_kernings() const {
 
 void BitmapFont::_set_textures(const Vector<Variant> &p_textures) {
 
+    textures.clear();
```
Comment (akien-mga) [inline scene/resources/font.cpp]: Indentation is wrong, it should be with tabs instead of spaces. Could you amend the commit to fix that? (See [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase))

Otherwise the fix looks correct.

Comment (LittleWhite-tb) [reply scene/resources/font.cpp]: Thank you. Should be fixed now.

**Comment by akien-mga** [comment]
Thanks and congrats for your first Godot code contribution :)
