### PR TITLE
Reduced output spam from rapid property changes

### LINKED ISSUE #84499: Dragging a property spams history messages, causing rapid memory usage increases due to editor output panel being filled with text
### Godot version

v4.1.3.stable.official [f06b6836a]

### System information

Godot v4.1.3.stable - Windows 10.0.19044 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 SUPER (NVIDIA; 31.0.15.3623) - AMD Ryzen 7 5700X 8-Core Processor (16 Threads)

### Issue description

I have a plane mesh with a 2048x2048 PNG texture applied. Changing the albedo colour of the texture results in Godot consuming as much memory as possible until my computer freezes, shortly before Godot crashes.

### Steps to reproduce

1. Create a mesh (CSGMesh3D)
2. Apply a new standard material
3. Under Material -> Albedo, change the material's colour.
4. Rapidly changing the colour results in extreme memory consumption, and won't be cleared until reopening Godot

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by TheSofox**
Fixes #84499 

Previously rapid changes in properties (dragging on colour picker, spinning through the spinner, etc.) would generate a huge amount of Output Log messages in a very short period of time. This would not only flood console, but eat up a lot of RAM.

This change means that the Property change messages use the same system that UndoRedo and History log uses: Identical changes made less than 800 milliseconds apart only give a single output message. Previously, messing around with the colour picker could give hundreds of messages, now it will only give a handful. Since it reuses the same system that , there's both minimal code change and it's consistent.

### CODE REVIEW

File: core/object/undo_redo.cpp [hunk 1]
```diff
@@ -314,7 +316,7 @@ void UndoRedo::commit_action(bool p_execute) {
 	_redo(p_execute); // perform action
 	committing--;
 
-	if (callback && actions.size() > 0) {
+	if (add_message && callback && actions.size() > 0) {
```
Comment (KoBeWi) [inline core/object/undo_redo.cpp:319]:
```suggestion
	if (!merging && callback && actions.size() > 0) {
```
No need for another variable here.

**Review by KoBeWi — APPROVED** [review]
Note that this change assumes that we use the callback only for editor log. Although it was always the case, so it's probably fine 🤔

File: core/object/undo_redo.cpp (hunk 1 above)
Comment (AThousandShips) [reply core/object/undo_redo.cpp:319]: It saves the `merging` state previously, it is cleared on line 306

Comment (KoBeWi) [reply core/object/undo_redo.cpp:319]: Ah I missed it.

**Comment by TheSofox** [comment]
> Note that this change assumes that we use the callback only for editor log. Although it was always the case, so it's probably fine 🤔

If it's a sticking issue, we could add an "action_was_merged" argument to the callback function, pass the variable along and then make the conditional statement of whether to add a message or not inside the callback function ( void EditorLog::_undo_redo_cbk  in editor_log.cpp)

**Comment by akien-mga** [comment]
Thanks!
