### PR TITLE
Fix custom theme outline settings affects the editor theme as well

### LINKED ISSUE #71006: Theme changes outline of the editor labels and buttons
### Godot version

4.0.beta10

### System information

Arch Linux, Vulkan

### Issue description

When i create a theme and set the theme in the project settings, the 'outline_size' is also applied to the editors buttons and labels. Only the outline_size is applied, StyleBoxes or colors are not applied.

### Steps to reproduce

- Create a theme and override the button and label 'outline_size'
- Set the theme in the project settings 'GUI/Theme/Custom'

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Maran23**
Fixes: https://github.com/godotengine/godot/issues/71006

The `font_outline_color` and `outline_size` settings were never set in the default theme.
Because of this, all `outline` changes affected the editor directly, resulting in a very colorful editor when using it on every control. :P

godot_theme_bug1

So this PR sets a default `outline_size` of 0 and a default `font_outline_color`, which for now is transparent since we never use an `outline` in the editor.

Note: While testing I found even more settings which were not set in the default theme and therefore can be overridden for the editor. See the `Buttons` in the screenshot above as an example. I have set the `h_separation` to a much higher value there.

For the sake of simplicity, this PR ONLY touches the two `outline` setting. For the other properties I found, I will submit another PR soon. :)

### CODE REVIEW

**Comment by MewPurPur** [comment]
Does this fully fix #60930 or just one of its flavors?

**Comment by Maran23** [comment]
> Would this series of PRs fix #60930 forever? This issue seems to keep creeping up in new ways

Yeah pretty sure it should.

**Comment by YuriSizov** [comment]
> Would this series of PRs fix #60930 forever? This issue seems to keep creeping up in new ways

In 4.1 I'll implement a feature that will make this sort of issue impossible.

File: editor/editor_themes.cpp [hunk 1]
```diff
@@ -825,6 +827,9 @@ Ref<Theme> create_editor_theme(const Ref<Theme> p_theme) {
 	theme->set_color("font_hover_color", "MenuButton", font_hover_color);
 	theme->set_color("font_hover_pressed_color", "MenuButton", font_hover_pressed_color);
 	theme->set_color("font_focus_color", "MenuButton", font_focus_color);
+	theme->set_color("font_outline_color", "MenuButton", font_outline_color);
+
+	theme->set_constant("outline_size", "MenuButton", 0 * EDSCALE);
```
Comment (bruvzg) [inline editor/editor_themes.cpp:832]:
```suggestion
	theme->set_constant("outline_size", "MenuButton", 0);
```

File: editor/editor_themes.cpp [hunk 2]
```diff
@@ -508,6 +508,7 @@ Ref<Theme> create_editor_theme(const Ref<Theme> p_theme) {
 	const Color font_disabled_color = Color(mono_color.r, mono_color.g, mono_color.b, 0.35);
 	const Color font_readonly_color = Color(mono_color.r, mono_color.g, mono_color.b, 0.65);
 	const Color font_placeholder_color = Color(mono_color.r, mono_color.g, mono_color.b, 0.6);
+	const Color font_outline_color = font_color;
```
Comment (YuriSizov) [inline editor/editor_themes.cpp:511]: It's better to set it to a transparent color. Most controls are written in a way that checks for outline size being over 0 and outline color having alpha over 0.

**Review by bruvzg — COMMENTED** [review]
I guess setting default values is fine. But it's probably should have some way to autofill all values to avoid the same issues in a future.

File: editor/editor_themes.cpp (hunk 1 above)
Comment (Maran23) [reply editor/editor_themes.cpp:832]: I used the `0 * EDSCALE` here to be consistent with the rest, e.g. `check_v_offset`, which has also this style.
But I'm also fine with changing it, then I would alos change `check_v_offset` to be consistent.

File: editor/editor_themes.cpp (hunk 2 above)
Comment (Maran23) [reply editor/editor_themes.cpp]: done.

**Comment by Maran23** [comment]
> In 4.1 I'll implement a feature that will make this sort of issue impossible.

Should we still fix the remaining issues here?
Or is it better to wait until your fix?

**Comment by YuriSizov** [comment]
> Should we still fix the remaining issues here?
> Or is it better to wait until your fix?

It doesn't hurt to fill the gaps for now, but the planned feature would make those default overrides redundant.

**Review by YuriSizov — APPROVED** [review]
I double-checked my own review comment from before, and technically, the default theme has the color at `Color(1, 1, 1)`, except for `TooltipLabel`, which is indeed set to `Color(0, 0, 0, 0)`. But for the editor theme this shouldn't matter.

**Comment by akien-mga** [comment]
Thanks!
