### PR TITLE
Avoid crash on exiting due to late prints

### LINKED ISSUE #79379: Godot 4.1 crashes on simple plugin print statement
### Godot version

v4.1.stable.official [970459615]

### System information

MacOS Big Sure 11.3

### Issue description

I got a bug report on my project and then did a deeper analysis to find the rootcause of Godot crashing on exit.
https://github.com/MikeSchulze/gdUnit4/issues/225

short story
- i removed all classes and resources step by step but still crashs at Godot exit
- finally i find out a simple print statement in the `func _exit_tree():` let the editor crash at exit.

### Steps to reproduce

Step one
- Create a new Project
- Create a new plugin over the editor provided plugin creation tool
- activate and exit ... works

Step two
- open the `plugin.gd` and add a print statement to `func _exit_tree():`

```
@tool
extends EditorPlugin


func _enter_tree():
	# Initialization of the plugin goes here.
	pass


func _exit_tree():
	prints("_exit_tree")
	# Clean-up of the plugin goes here.
	pass

```

- close/restart the editor is crashing at exit

### Minimal reproduction project

n/a

### LINKED ISSUE #79506: Printing in the destructor of a node in the edited scene crashes the editor on exit
### Godot version

Godot 4.1 e709ad4d6407e52dc62f00a471d13eb6c89f2c4c

### System information

Windows 10 64 bits NVIDIA GeForce GTX 1060

### Issue description

I have a `print_line` in the destructor of a custom class derived from `Node3D`. I use it in verbose mode to track when things happen. In previous versions, it worked fine. But in Godot 4.1, closing the editor crashes:

```
Exception has occurred: W32/0xC0000005
Unhandled exception thrown: read access violation.
this was 0xFFFFFFFFFFFFFFFF.

godot.windows.editor.dev.x86_64.exe!CowData<EditorLog::LogMessage>::_get_size() Line 81 (godot4_fork\core\templates\cowdata.h:81)
godot.windows.editor.dev.x86_64.exe!CowData<EditorLog::LogMessage>::size() Line 131 (godot4_fork\core\templates\cowdata.h:131)
godot.windows.editor.dev.x86_64.exe!Vector<EditorLog::LogMessage>::size() Line 93 (godot4_fork\core\templates\vector.h:93)
godot.windows.editor.dev.x86_64.exe!EditorLog::_process_message(const String & p_msg, EditorLog::MessageType p_type) Line 216 (godot4_fork\editor\editor_log.cpp:216)
godot.windows.editor.dev.x86_64.exe!EditorLog::add_message(const String & p_msg, EditorLog::MessageType p_type) Line 243 (godot4_fork\editor\editor_log.cpp:243)
godot.windows.editor.dev.x86_64.exe!EditorNode::_print_handler_impl(const String & p_string, bool p_error, bool p_rich) Line 6651 (godot4_fork\editor\editor_node.cpp:6651)
godot.windows.editor.dev.x86_64.exe!call_with_variant_args_static<String const &,bool,bool,0,1,2>(void(*)(const String &, bool, bool) p_method, const Variant * * p_args, Callable::CallError & r_error, IndexSequence<0,1,2> __formal) Line 777 (godot4_fork\core\variant\binder_common.h:777)
godot.windows.editor.dev.x86_64.exe!call_with_variant_args_static_ret<String const &,bool,bool>(void(*)(const String &, bool, bool) p_method, const Variant * * p_args, int p_argcount, Variant & r_ret, Callable::CallError & r_error) Line 847 (godot4_fork\core\variant\binder_common.h:847)
godot.windows.editor.dev.x86_64.exe!CallableCustomStaticMethodPointerRet<void,String const &,bool,bool>::call(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 309 (godot4_fork\core\object\callable_method_pointer.h:309)
godot.windows.editor.dev.x86_64.exe!Callable::callp(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 51 (godot4_fork\core\variant\callable.cpp:51)
godot.windows.editor.dev.x86_64.exe!CallableCustomBind::call(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 145 (godot4_fork\core\variant\callable_bind.cpp:145)
godot.windows.editor.dev.x86_64.exe!Callable::callp(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 51 (godot4_fork\core\variant\callable.cpp:51)
godot.windows.editor.dev.x86_64.exe!CallQueue::_call_function(const Callable & p_callable, const Variant * p_args, int p_argcount, bool p_show_error) Line 220 (godot4_fork\core\object\message_queue.cpp:220)
godot.windows.editor.dev.x86_64.exe!CallQueue::flush() Line 322 (godot4_fork\core\object\message_queue.cpp:322)
godot.windows.editor.dev.x86_64.exe!Main::cleanup(bool p_force) Line 3562 (godot4_fork\main\main.cpp:3562)
godot.windows.editor.dev.x86_64.exe!widechar_main(int argc, wchar_t * * argv) Line 184 (godot4_fork\platform\windows\godot_windows.cpp:184)
godot.windows.editor.dev.x86_64.exe!_main() Line 204 (godot4_fork\platform\windows\godot_windows.cpp:204)
godot.windows.editor.dev.x86_64.exe!main(int argc, char * * argv) Line 218 (godot4_fork\platform\windows\godot_windows.cpp:218)
godot.windows.editor.dev.x86_64.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 232 (godot4_fork\platform\windows\godot_windows.cpp:232)
godot.windows.editor.dev.x86_64.exe!invoke_main() Line 107 (d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:107)
godot.windows.editor.dev.x86_64.exe!__scrt_common_main_seh() Line 288 (d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
godot.windows.editor.dev.x86_64.exe!__scrt_common_main() Line 331 (d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:331)
godot.windows.editor.dev.x86_64.exe!WinMainCRTStartup(void * __formal) Line 17 (d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_winmain.cpp:17)
kernel32.dll!00007ffdcb657614() (Unknown Source:0)
ntdll.dll!00007ffdcb8c26b1() (Unknown Source:0)
```

### Steps to reproduce

My own case is in C++, but it can be reproduced with GDScript.

Have a scene with a node having the following script on it:

```gdscript
@tool
extends Node3D

func _notification(what):
	if what == NOTIFICATION_PREDELETE:
		print("Destroying ", name)
```

Have that scene open, and close the editor.

Now unfortunately you might not notice anything depending on how your OS handles that (as with many crashes occurring on exit).
I work with debug builds and that definitely makes the crash visible in the debugger. I also use the following command line to build Godot on Windows:
```
scons p=windows target=editor dev_build=yes warnings=all werror=yes debug_crt=yes -j4
```

### Minimal reproduction project

[PrintInNodeDestructor.zip](https://github.com/godotengine/godot/files/12062273/PrintInNodeDestructor.zip)
Open the project, open the scene, then close the editor.

### LINKED ISSUE #80152: Editor deadlock on exit when using Thread/Semaphore in autoloaded tool script
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - macOS 13.4.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

After creating a `@tool` script that is autoloaded and uses Semaphores and a Thread, when exiting the editor it freezes and stops responding on MacOS.

Editor not responding after closing the editor:
image
image

The editor must then be force quit and produces the following error information:
https://gist.github.com/Trikzon/dc3e1ed7a258fa9cc2c363b18b43c353

A full minimal reproducible product is provided, but the important snippets are:
```
@tool
extends Node

var mutex: Mutex
var semaphore: Semaphore
var thread: Thread
var exit_thread := false


func _ready():
    mutex = Mutex.new()
    semaphore = Semaphore.new()
    exit_thread = false
    
    thread = Thread.new()
    thread.start(_thread_function)

func _thread_function():
    while true:
        semaphore.wait()
        
        mutex.lock()
        var should_exit = exit_thread
        mutex.unlock()
        
        if should_exit:
            break
        
       # Actual thread work goes here

func _exit_tree():
    mutex.lock()
    exit_thread = true
    mutex.unlock()
    
    semaphore.post()
    
    thread.wait_to_finish()
```

At first I thought that `_exit_tree()` was not being called when the editor closed, but I found that it is because placing a `ResourceSaver.save()` in `_exit_tree()` creates a file when the editor closes.

### Steps to reproduce

Create a `@tool` script using Semaphores and a Thread and set it as an autoloading script in-editor.

The [Using Multiple Threads#Semaphores](https://docs.godotengine.org/en/stable/tutorials/performance/using_multiple_threads.html#semaphores) guide can be used as a base.

### Minimal reproduction project

[Thread Tools Test.zip](https://github.com/godotengine/godot/files/12237193/Thread.Tools.Test.zip)

Note: I use a mono build of Godot, but this does not contain any C#.

Contains an autoloaded tool script that is a slightly modified version of the [Using Multiple Threads#Semaphores](https://docs.godotengine.org/en/stable/tutorials/performance/using_multiple_threads.html#semaphores) guide.

Also contains a test scene with a tool script where changing a number in-editor will post the semaphore to see that the thread is running correctly in the background.

### PR DESCRIPTION
**Pull request by RandomShaper**
Fixes #80152.

**UPDATE:** Probably fixes #79379.
*Bugsquad edit:* And fixes #79506.

The MRP there adds a message when the `EditorNode` has already been destroyed. The most obvious fix is done here, which is just validating the singleton when a deferred call happens. The problem is that static calls in the message queue can't be validated.

Now, there are potential alternatives to this fix that may be done instead of in addition:

a) Let the static callables have some sort of custom validation.
  For instance, there's this call:
  `callable_mp_static(&EditorNode::_print_handler_impl).bind(p_string, p_error, p_rich).call_deferred();`
  With this approach it could become something like this:
  `callable_mp_static(&EditorNode::_print_handler_impl).bind(p_string, p_error, p_rich).add_validator([]() -> bool{ return EditorNode::get_singleton(); }).call_deferred();`

b) Like a), but using a sentinel pointer:
  `callable_mp_static(&EditorNode::_print_handler_impl).bind(p_string, p_error, p_rich).add_validity_sentinel(&EditorNode::singleton).call_deferred();`

c) Make all deferred calls of this kind via the object instance instead of static. That would enable the current validated call mechanism to do its magic.

### CODE REVIEW

**Comment by AThousandShips** [comment]
Does this fix #79379?

**Comment by RandomShaper** [comment]
> Does this fix #79379?

Very likely.

**Review by akien-mga — APPROVED** [review]
Makes a lot of sense to cleanup the singleton like this.

**Comment by akien-mga** [comment]
CC @KoBeWi for the discussion on static callable validation - but this PR is ready to merge as is IMO.

**Comment by KoBeWi** [comment]
If a static function depends on an instance, it shouldn't be static, no?
Also if it's expected that the instance it involves can be invalidated, the check should be inside the function itself I think.

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -6845,7 +6848,9 @@ EditorNode::EditorNode() {
 		DisplayServer::get_singleton()->cursor_set_custom_image(Ref<Resource>());
 	}
 
-	singleton = this;
+	if (!singleton) {
+		singleton = this;
+	}
```
Comment (akien-mga) [inline editor/editor_node.cpp:6853]: Do we support constructing two EditorNode instances?

Comment (YuriSizov) [reply editor/editor_node.cpp:6853]: There is no reason to, no.

Comment (KoBeWi) [reply editor/editor_node.cpp:6853]: It was considered to make such checks a standard (see #79981)
Though it's rarely necessary/useful IMO.

Comment (RandomShaper) [reply editor/editor_node.cpp:6853]: I added the checks to match how I've seen singleton pointers managed in other cases, future-proofing for cases like the docs generation instantiating the class. However, given that currently that's not the case, I'll just add a check.

Comment (RandomShaper) [reply editor/editor_node.cpp]: Done. By the way, I think this is a legit use of `DEV_ASSERT`.

Comment (akien-mga) [reply editor/editor_node.cpp]: To know if this is a legit use of `DEV_ASSERT`, we need to be able to say whether only engine devs can trigger that bug. So if EditorNode can be constructed from GDScript, C# or GDExtension, this could still lead to issues. If not, `DEV_ASSERT` seems good.

Comment (YuriSizov) [reply editor/editor_node.cpp]: `EditorNode` is not exposed to the API.

**Review by akien-mga — APPROVED** [review]
Still seems good after changes.

**Comment by YuriSizov** [comment]
Thanks!
