### PR TITLE
Unify GDScriptAnalyzer in-editor and runtime autoload checks

### LINKED ISSUE #63045: GDScript 2.0: Passing AutoLoad to function with typed parameter error "argument 1 should be Node but is ."
### Godot version

v4.0.alpha.custom_build [5fec0d232]

### System information

Arch on 5.18.10-arch1-1

### Issue description

```
Parser Error: Invalid argument for "test()" function: argument 1 should be Node but is .
```

### Steps to reproduce

scene.gd:

```gdscript
extends Node

func test(node: Node) -> void:
	print(node)

func _ready() -> void:
	test(Global)

```

### Minimal reproduction project

[test13.zip](https://github.com/godotengine/godot/files/9123446/test13.zip)

### LINKED ISSUE #70127: Autoloads broken: cannot find members
### Godot version

v4.0.beta.custom_build [15631e24f]

### System information

Windows 11, Forward+, Geforce 1660 (526.98)

### Issue description

When I try to get a variable from autoload, I get:
```Parser Error: Cannot find member "audio_player" in base "".```

I think the regression was introduced in 6debf86d5, because on the previous commit (ec4de82ab) MRP works.

### Steps to reproduce

open and run project

### Minimal reproduction project

[var_from_autoload_test.zip](https://github.com/godotengine/godot/files/10240605/var_from_autoload_test.zip)

### PR DESCRIPTION
**Pull request by anvilfolk**
Fixes #63045
Fixes #70127

I dug deeper into #70127, and this together with #70275 should capture a lot more cases!

When running in-editor, `EditorAutoloadSettings` uses `add_named_global_constant()`, whereas when running the game itself, `main.cpp` uses `add_global_constant()`. `GDScriptAnalyzer` was only checking `named_globals`, which weren't present at runtime.

This ensures the analyzer checks both, so it works similarly in-editor and in-game.

This should allow some extra type inferences when running the main game. Particularly, any optimizations related to autoloaded scripts/scenes that are currently possible while in-editor are now possible while running the game. Right now these are only `const`-based optimizations, but maybe in the future it could be more :)

### CODE REVIEW

File: core/object/script_language.h [hunk 1]
```diff
@@ -373,6 +373,8 @@ class ScriptLanguage : public Object {
 	virtual void auto_indent_code(String &p_code, int p_from_line, int p_to_line) const = 0;
 	virtual void add_global_constant(const StringName &p_variable, const Variant &p_value) = 0;
 	virtual void add_named_global_constant(const StringName &p_name, const Variant &p_value) {}
+	virtual bool has_any_global_constant(const StringName &p_name) { return false; };
+	virtual Variant get_any_global_constant(const StringName &p_name) { return Variant(); };
```
Comment (rune-scape) [inline core/object/script_language.h:377]: if this is a virtual method on ScriptLanguage, then csharp and other languages should also implement it,
it should probably be moved to a non-virtual method on GDScriptLanguage like `get_global_map` and `get_named_globals_map`

**Review by rune-scape — CHANGES_REQUESTED** [review]

File: modules/gdscript/gdscript.cpp [hunk 2]
```diff
@@ -1966,6 +1966,17 @@ void GDScriptLanguage::add_named_global_constant(const StringName &p_name, const
 	named_globals[p_name] = p_value;
 }
 
+Variant GDScriptLanguage::get_any_global_constant(const StringName &p_name) {
+	ERR_FAIL_COND_V(!named_globals.has(p_name) && !globals.has(p_name), Variant());
```
Comment (Maran23) [inline modules/gdscript/gdscript.cpp:1970]: Isn't `has` called two times here? First in the check, than below again?

Comment (anvilfolk) [reply modules/gdscript/gdscript.cpp:1970]: Yes, it is - the first time to raise an error, the second time to disambiguate which map it should find the map from.

I did want an error to be raised here, but it is slightly more inefficient this way. That being said, right now this is only used in the gdscript analyzer, which runs once for every script and that's it, so I figured it was OK?

Comment (Maran23) [reply modules/gdscript/gdscript.cpp:1970]: I don't think it is a major problem here, since `has` is very fast in `HashMap`s.
But can't you just raise an error in line 1977, after you tried looking up the value in both `HashMap`?

Comment (anvilfolk) [reply modules/gdscript/gdscript.cpp:1970]: Oh yeah, good point :) I'll do that!

Comment (anvilfolk) [reply modules/gdscript/gdscript.cpp]: Done! And thanks for checking this out! :)

File: modules/gdscript/gdscript.h [hunk 3]
```diff
@@ -491,6 +491,8 @@ class GDScriptLanguage : public ScriptLanguage {
 	virtual void auto_indent_code(String &p_code, int p_from_line, int p_to_line) const override;
 	virtual void add_global_constant(const StringName &p_variable, const Variant &p_value) override;
 	virtual void add_named_global_constant(const StringName &p_name, const Variant &p_value) override;
+	virtual bool has_any_global_constant(const StringName &p_name) { return named_globals.has(p_name) || globals.has(p_name); }
+	virtual Variant get_any_global_constant(const StringName &p_name);
```
Comment (rune-scape) [inline modules/gdscript/gdscript.h:495]: these should probably not be virtual and get moved up to ~line 457 with the `get_global_map()` functions, because they're not a part of the editor functions

Comment (anvilfolk) [reply modules/gdscript/gdscript.h]: Oh, good call, thank you! I wasn't even thinking when I put these there, I just looked around similar functions and didn't notice there were sections!

**Review by rune-scape — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Review by Maran23 — APPROVED** [review]
Looks good to me too.

**Comment by akien-mga** [comment]
Thanks!
