### PR TITLE
Ignore depth draw optimization when using depth draw alpha prepass

### LINKED ISSUE #70881: Depth pre-pass is broken
### Godot version

v4.0.beta.custom_build [96f12040c]

### System information

Windows 11/64, RTX 3070, Vulkan

### Issue description

From beta10 to the current master, depth prepass is broken. 

Alpha
image

Depth Prepass
image

Alpha
image

Depth Prepass `depth_prepass_alpha`
image

Depth Prepass Beta 10
image

Note that the shadows render fine, as does vertex animation.

I also get a lot of vulkan errors that I don't get in b10. Many repeats of these on load, but not continuous:

```
ERROR: Condition "!named_textures.has(key)" is true. Returning: RID()
   at: get_texture_slice (servers/rendering/renderer_rd/storage_rd/render_scene_buffers_rd.cpp:357)
ERROR: Texture (binding: 0, index 0) is not a valid texture.
   at: (drivers/vulkan/rendering_device_vulkan.cpp:5465)
ERROR: Condition "rid.is_null()" is true. Returning: rid
   at: _allocate_from_uniforms (./servers/rendering/renderer_rd/uniform_set_cache_rd.h:129)
ERROR: Condition "!uniform_set" is true.
   at: compute_list_bind_uniform_set (drivers/vulkan/rendering_device_vulkan.cpp:7807)
ERROR: Uniforms were never supplied for set (0) at the time of drawing, which are required by the pipeline
   at: (drivers/vulkan/rendering_device_vulkan.cpp:8006)
ERROR: Condition "!rt" is true. Returning: RID()
   at: render_target_get_override_depth_slice (servers/rendering/renderer_rd/storage_rd/texture_storage.cpp:2688)

```

I'm bisecting now....

### Steps to reproduce

See MRP. Change alpha on the tree.

### Minimal reproduction project

You can use my demo from #63675
https://github.com/godotengine/godot/files/10256553/test_zorder.zip

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/70881

This is necessary as the scene shader still uses alpha in this case so we can't discard fragments that weren't written to the depth buffer

_Before this PR: Master_
Screenshot from 2023-01-03 09-30-40

_After this PR (Beta 10 looks the same)_
Screenshot from 2023-01-03 09-29-49

CC @Ansraer

### CODE REVIEW

File: servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp [hunk 1]
```diff
@@ -309,10 +309,11 @@ void SceneShaderForwardClustered::ShaderData::set_code(const String &p_code) {
 						}
 
 						RD::PipelineDepthStencilState depth_stencil = depth_stencil_state;
-						if (depth_pre_pass_enabled && casts_shadows()) {
+						if (depth_pre_pass_enabled && casts_shadows() && !uses_depth_pre_pass) {
```
Comment (Ansraer) [inline servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp:312]: `uses_depth_pre_pass` needs to be renamed imo. Without looking at L117 I would have never guessed that it had anything to do with alpha pre-passes.

Right now this code reads like it always evaluates as false.

**Review by Ansraer — CHANGES_REQUESTED** [review]
I agree with the changes, but REALLY think that `uses_depth_pre_pass` should be renamed to something like `uses_alpha_depth_pre_pass`.

File: servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp (hunk 1 above)
Comment (clayjohn) [reply servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp:312]: Yes, especially given the comment and the ``depth_pre_pass_enabled`` bool

**Review by akien-mga — APPROVED** [review]

File: servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp (hunk 1 above)
Comment (akien-mga) [reply servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp:312]: (I approved for merge, but will wait for those changes first of course.)

**Comment by TokisanGames** [comment]
Does this also address the new vulkan console errors noted in https://github.com/godotengine/godot/issues/70881? I didn't look when bisecting to see if that PR caused them.

**Comment by clayjohn** [comment]
> Does this also address the new vulkan console errors noted in #70881? I didn't look when bisecting to see if that PR caused them.

No, those errors are unrelated. I also couldn't reproduce them in the MRP

File: servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp (hunk 1 above)
Comment (clayjohn) [reply servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp]: renamed to ``uses_depth_prepass_alpha``

**Review by Ansraer — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
