### PR TITLE
[Windows] Add support for `AdvancedColorInfo` info and change callback.

### LINKED ISSUE #118618: HDR output not activated when enabling HDR mode in Windows
### Tested versions

- Reproducible in v4.7.dev1.official [bf95b6258]
- Reproducible in v4.7.dev4.official [755fa449c]
- Reproducible in `master` [4fe68a9ed4a27047e8b5eab15765430c9cef4610]

NOT reproducible with PR https://github.com/godotengine/godot/pull/118339

### System information

Godot v4.7.dev1 - Windows 11 (build 26200) - Multi-window, 1 monitor - Direct3D 12 (Forward+) - dedicated NVIDIA GeForce RTX 5070 Ti (NVIDIA; 32.0.15.9186) - AMD Ryzen 9 9950X3D 16-Core Processor (32 threads) - 61.64 GiB memory

### Issue description

As some may know, I've done a lot of testing of the Windows HDR output feature on Windows. On one of my computers that used to work flawlessly with HDR output using 4.7 dev 1 onward, a new issue has started to happen: it appears that the `DXGI_OUTPUT_DESC1` is always returning `DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709` when the screen is in HDR mode:

Image

Using `master` with the new game view changes, the game view confirms as well that the game is running in SDR mode:

Image

I do not know what has changed with my system configuration to cause this issue to start happening. It only seems to happen when I start my game when Windows is in SDR mode  and I then switch to HDR mode.

If I open the windows display settings when the bug is happening, suddenly the game correctly switches to HDR mode:
Image

### Steps to reproduce

1. Create a new project with HDR 2D enabled and Request HDR output enabled.
2. Set Windows to SDR mode
3. Run the project
4. Switch Windows to HDR mode using the Win + Alt + B keyboard shortcut
5. Note that Godot is not running in HDR mode, even though Windows is in HDR mode

Currently this is happening about 90% of the time when I run my game. I am running it in debug mode from the editor.

The bug also happens with the game in embedded mode or not embedded mode, but it happens more when not in embedded mode.
Image

### Minimal reproduction project (MRP)

[hdr-output-basic-test.zip](https://github.com/user-attachments/files/26759341/hdr-output-basic-test.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
See https://github.com/godotengine/godot/pull/117837#issuecomment-4204760465

Note: this will not work on Wine and some older Windows 10 versions (pre-1809 / Redstone 5), so we still need to keep polling code for this case.

Fixes https://github.com/godotengine/godot/issues/118618

### CODE REVIEW

File: platform/windows/display_server_windows.cpp [hunk 1]
```diff
@@ -3449,6 +3449,18 @@ DisplayServerWindows::ScreenHdrData DisplayServerWindows::_get_screen_hdr_data(i
 	return data;
 }
 
+void DisplayServerWindows::_winrt_adv_color_info_cb(DisplayServerEnums::WindowID p_id) {
+	WindowData &wd = windows[p_id];
+
+	//if (WinRTUtils::window_has_display_info(wd.wrt_wd)) {
+	//	print_line(WinRTUtils::window_get_advanced_color_info(wd.wrt_wd));
+	//}
```
Comment (bruvzg) [inline platform/windows/display_server_windows.cpp]: Note: I have added a method to get `AdvancedColorInfo` as a Godot Dictionary, but not sure if it's needed for something.

**Comment by allenwp** [comment]
🤩

> but it can be conditionally skipped (using `WinRTUtils::window_has_display_info`).

Any chance this PR can be updated to include this? Although this PR does solve the problem of the reference luminance not updating until the window regains focus, the real high-priority impetus for this change is to improve performance significantly by not needing to poll for changes in colour space and max luminance.

It will also be critically important to test if the `WM_DISPLAYCHANGE` happening before `DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709` problem occurs with this approach. I'd like to test to see if the new advanced colour event happens before `DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709` 100% of the time...

**Comment by allenwp** [comment]
> Any chance this PR can be updated to include this?

Derp. My mistake! I think [this PR already does this](https://github.com/godotengine/godot/pull/118339/changes#diff-b39afbf5546f4c9f98975d98ac464ebec9f8df4098229ad2267c7cba3d82ac4bR3512)!

I'll give this a thorough test. It would be great to have this for 4.7...

**Comment by allenwp** [comment]
I just tested this on my "problematic" computer now. I was able to produce a bug in this PR where the screen would be in HDR output mode (from pressing the Win + Alt + B shortcut), but Godot would think the Window did not support HDR output. This appears to be because a `DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709` colour space was still reported for the moments after the new `_winrt_adv_color_info_cb` was called. This is exactly what happens after the `WM_DISPLAYCHANGE` event, so it's not surprising that it would occur with `AdvancedColorInfoChanged` as well.

But, the new screen information includes a `CurrentAdvancedColorKind`, which can tell us if we should be in HDR mode and will let us fill out the `ScreenHdrData` struct! So I've made a modified version of this PR that fixes the bug. I tested this by running both this PR and my update at the same time to verify this.

https://github.com/allenwp/godot/tree/winrt_color

My branch has some remaining issues. Specifically, I needed to remove the `const` part of `_get_screen_hdr_data`. Not sure how to avoid this, so that needs some work.

Also, in this PR, I'd be fine only including the items we actually will use in the dictionary that `window_get_advanced_color_info` returns instead of filling in all of the other data we'll never use. But I'm not familiar with the preferred code style for this sort of thing.

---

After doing some more testing, I am now no longer able to reproduce the issue with this PR... but the commit just before this PR (`master`) is now entirely broken on my computer and the `DXGI_OUTPUT_DESC1` is always reporting `DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709` until I adjust the SDR content brightness Windows setting or I start Godot with Windows in HDR mode. This doesn't happen with this PR or with my update, which makes no sense to me because I would expect this PR to also have the same issue... So I feel like I'm going a bit crazy here. Either way, I haven't yet seen an issue with my branch.

I'll continue trying to reproduce these two issues to firmly verify what is going on here and that the behaviour in my branch is the best approach for Godot...

**Comment by bruvzg** [comment]
> Specifically, I needed to remove the const part of _get_screen_hdr_data. Not sure how to avoid this, so that needs some work.

What's causing it not to work with `const`, if it's window data access and non-const `WinRTWindowData *` in utils it should be changed to `const` in utils instead, `has`/`get` functions doesn't write to this pointer.

> Also, in this PR, I'd be fine only including the items we actually will use in the dictionary

If we only need color type, `max_luminance`, and `sdr_white_level` it probably would make sense to use return args instead of `Dictionary`. This is unexposed internal API, so there's no specific requirements.

> This doesn't happen with this PR or with my update, which makes no sense to me because I would expect this PR to also have the same issue...

No idea, but it's possible that working WinRT dispatcher queue for the window can result in DirectX getting some extra system events as well.

**Comment by bruvzg** [comment]
I'll apply your changes (+ const fix and change from dict to return args) and retest in a bit later today.

**Comment by bruvzg** [comment]
Updated it and it seems to be working fine. I was not able to reproduce issue with Win + Alt + B switching, all HDR data for new and old method is always the same.

**Comment by allenwp** [comment]
Thanks, if my computer is still producing the weird bug with the dev releases, I’ll post an issue and demonstrate that this PR fixes it. Yesterday, at least, it became very consistent. I must have some funny NVIDIA drivers or something for my 5070 Ti…

**Comment by allenwp** [comment]
I've created a bug report. This PR fixes the bug: https://github.com/godotengine/godot/issues/118618

**Comment by allenwp** [comment]
I've requested review from blueskythlikesclouds, also cc @DarkKilauea. You two are both familiar with this code, so I figure you might want to take a look.

In short, this PR should prevent any of the "legacy" HDR screen info functions from running and instead exclusively use the new WinRT advanced colour info functions and event when they are available. This should improve performance by not needing to poll anything and also seems to fix two bugs that I had been experiencing relating to the colour space that `DXGI_OUTPUT_DESC1` was reporting. Windows emulation and older versions of Windows can use the old legacy method, since this is the only option to make these work.

I have reviewed the changes to `DisplayServerWindows` and they look good to me, but I can't comment on the rest of the files, since I'm not familiar with those. I have not approved this PR yet because it will take quite a bit of testing over the next few days on systems with different configurations before I'm confident that there aren't any unexpected bugs. I'll report back when I've built and exported with MinGW and tested on computers like laptops with built-in HDR screens.

File: platform/windows/winrt_utils.cpp [hunk 2]
```diff
@@ -42,27 +42,184 @@ GODOT_GCC_WARNING_IGNORE("-Wstrict-aliasing")
...
+	}
+}
+
+WinRTWindowData *WinRTUtils::create_wd(HWND p_window, const Callable &p_color_cb, int64_t p_window_id) {
+	WinRTWindowData *wd = memnew(WinRTWindowData);
+
+	wd->id = p_window_id;
+	wd->cb = p_color_cb;
+	if (ApiInformation::IsApiContractPresent(L"Windows.Foundation.UniversalApiContract", 6)) {
+		try {
```
Comment (Calinou) [inline platform/windows/winrt_utils.cpp:173]: This introduces C++ exceptions whereas we didn't use any before, is it an issue? Typically, we want to avoid them due to the added binary size (and performance issues in hot paths).

Searching in the codebase, I noticed there are two uses of `try {} catch {}` in `drivers/metal` as well. There are several in third-party code, but they all appear to be disabled at compile-time through `#ifdef`s.

**Review by Calinou — COMMENTED** [review]
Tested locally on Windows 11 24H2, it works as expected.

I've tested changes to the SDR content brightness slider at runtime, as well as toggling HDR on the system while the project is running (on -> off, or off -> on). Everything updates in real-time (no more need to focus the window to update SDR content brightness).

File: platform/windows/winrt_utils.cpp (hunk 2 above)
Comment (bruvzg) [reply platform/windows/winrt_utils.cpp:173]: WinRT headers internally depends on exceptions, so it is enabled specifically for this few files, same for Metal.

Also, both are C++20.

**Review by blueskythlikesclouds — APPROVED** [review]
Looks good to me. The CPU cost is also basically gone.

File: platform/windows/winrt_utils.cpp (hunk 2 above)
Comment (akien-mga) [reply platform/windows/winrt_utils.cpp:173]: I wonder if there's a significant binary size impact of having some exception handling code just for WinRT and Metal.

Comment (bruvzg) [reply platform/windows/winrt_utils.cpp:173]: I'll check size with and without WinRT enabled in a moment. We can get rid of this specific block, but changing in the headers is not feasible, it used a lot.

Comment (bruvzg) [reply platform/windows/winrt_utils.cpp:173]: Entire WinRT part of the code (this PR, emoji picker, OneCore TTS) adds about 64 KB in both debug editor build, and release template with LTO.

Changing this specific block to non-throwing variant seems to have no effect.

Comment (allenwp) [reply platform/windows/winrt_utils.cpp:173]: > Changing this specific block to non-throwing variant seems to have no effect.

I might be misunderstanding something here… the code has not changed and still has the `try catch`. Was this supposed to be changed? (Specifically changed to use the non-throwing variant so that the try catch aren’t needed anymore?)

Comment (bruvzg) [reply platform/windows/winrt_utils.cpp:173]: > Was this supposed to be changed?

No, I have checked it locally, but did not change the PR since there's no difference.

**Comment by Repiteo** [comment]
Thanks!
