### PR TITLE
Prevent `changed` signal spam on resource reload.

### LINKED ISSUE #102609: Slow reimport of project default font + errors in debug output
### Tested versions

- Reproducible in **4.3**, **4.2.2** (slow w/ errors, haven't tested pre-4.2.2), **4.4-beta3** (slow but no errors)
- Reproducible both in Windows and Linux

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4060 Ti (NVIDIA; 32.0.15.6636) - AMD Ryzen 7 7700X 8-Core Processor (16 Threads), but also happens on Linux!

### Issue description

Font reimporting is slow (and spits out errors before 4.4) when the font in question is set as the project default font (project setting `gui/theme/custom_font`).

Errors (1024+ of these repeating):
```
modules/text_server_adv/text_server_adv.cpp:2608 - Parameter "fd" is null.
modules/text_server_adv/text_server_adv.cpp:2464 - Parameter "fd" is null.
modules/text_server_adv/text_server_adv.cpp:2640 - Parameter "fd" is null.
```
NOTE: The error messages don't seem to appear in 4.4 (tested beta 3), but the slow import remains!

### Steps to reproduce

Open the MRP. If the issue doesn't show itself with the following steps, close the project and try again (I've seen it not happen on initial project import).

1. Open scene `test.tscn` (not necessary, but has these steps written in UI)
2. Note: Project default theme is set to use custom font **"Not Jam UI"**.
3. Try reimporting font **"joystix"**, happens quickly
4. Try reimporting font **"Not Jam UI"**, is slow and spits out errors pre-4.4

### Minimal reproduction project (MRP)

[FontBug.zip](https://github.com/user-attachments/files/18723721/FontBug.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Partially fixes https://github.com/godotengine/godot/issues/102609, now reimporting default theme font will reload theme only 4 times (probably something to do with old font sending changed signals to the new one, will check it later) instead of 20+.

I'm not sure this change is entirely safe, something might rely on getting `changed` signal immediately.

### CODE REVIEW

File: core/io/resource.h [hunk 1]
```diff
@@ -72,6 +72,8 @@ class Resource : public RefCounted {
 	String import_path;
 #endif
 
+	bool freeze_emit_changed = false;
+	bool emit_changed_after_unfreeze = false;
```
Comment (RandomShaper) [inline core/io/resource.h:76]:
```suggestion
    enum EmitChangedState {
        EMIT_CHANGED_UNBLOCKED,
        EMIT_CHANGED_BLOCKED,
        EMIT_CHANGED_UNBLOCKED_PENDING_EMIT,
    };
```

Reasons:
1. Use a more concice single variable with all the needed states, and none else.
2. Use the term "block," that is already used in Godot in similar contexts (i.e., "signals blocked").

Comment (bruvzg) [reply core/io/resource.h]: Changed to single variable and "block".

**Review by RandomShaper — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
