### PR TITLE
Fix read-only state for Skeleton and Inspector

### LINKED ISSUE #110486: No prevention of key insertion into read-only Animation and addition of RESET animations to read-only AnimationLibrary
### Tested versions

- Reproducible 4.3, 4.4, 4.5

### System information

Any

### Issue description

Moving keys or adding tracks is not permitted, but prevention of keying and similar actions are not prevented from inpector.

Image

### Steps to reproduce

Try to add track or key by keying button on inspector or option of SkeletonEditor (top of view port)

### Minimal reproduction project (MRP)

[import_animlib.zip](https://github.com/user-attachments/files/22309949/import_animlib.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
- Fixes https://github.com/godotengine/godot/issues/110486

Add some preventions:
- If you attempt keying from inspector, a dialog box will appear

image

- When the Global Animation Library is read-only, hide the `add RESET` checkbox

image

### CODE REVIEW

File: editor/animation/animation_track_editor.cpp [hunk 1]
```diff
@@ -8268,6 +8336,11 @@ AnimationTrackEditor::AnimationTrackEditor() {
 	track_copy_select->set_hide_root(true);
 	track_copy_vbox->add_child(track_copy_select);
 	track_copy_dialog->connect(SceneStringName(confirmed), callable_mp(this, &AnimationTrackEditor::_edit_menu_pressed).bind(EDIT_COPY_TRACKS_CONFIRM));
+
+	read_only_dialog = memnew(AcceptDialog);
+	read_only_dialog->set_title(TTR("Key Insertion Error"));
+	read_only_dialog->set_text(vformat(TTR("Imported Animation cannot be edited!")));
```
Comment (KoBeWi) [inline editor/animation/animation_track_editor.cpp]:
```suggestion
	read_only_dialog->set_title(TTRC("Key Insertion Error"));
	read_only_dialog->set_text(vformat(TTRC("Imported Animation cannot be edited!")));
```

File: editor/animation/animation_track_editor.cpp [hunk 2]
```diff
@@ -8268,6 +8336,11 @@ AnimationTrackEditor::AnimationTrackEditor() {
 	track_copy_select->set_hide_root(true);
 	track_copy_vbox->add_child(track_copy_select);
 	track_copy_dialog->connect(SceneStringName(confirmed), callable_mp(this, &AnimationTrackEditor::_edit_menu_pressed).bind(EDIT_COPY_TRACKS_CONFIRM));
+
+	read_only_dialog = memnew(AcceptDialog);
```
Comment (KoBeWi) [inline editor/animation/animation_track_editor.cpp:8471]: You could create the dialog on demand in `popup_read_only_dialog()`, it will rarely be needed.

File: editor/animation/animation_track_editor.cpp [hunk 3]
```diff
@@ -3196,11 +3196,14 @@ void AnimationTrackEdit::gui_input(const Ref<InputEvent> &p_event) {
...
 				if (selected || editor->is_selection_active()) {
-					AnimationPlayer *player = AnimationPlayerEditor::get_singleton()->get_player();
-					if ((!player->has_animation(SceneStringName(RESET)) || animation != player->get_animation(SceneStringName(RESET))) && editor->can_add_reset_key()) {
-						menu->add_icon_item(get_editor_theme_icon(SNAME("Reload")), TTR("Add RESET Value(s)"), MENU_KEY_ADD_RESET);
+					AnimationPlayerEditor *ape = AnimationPlayerEditor::get_singleton();
+					if (ape) {
+						AnimationPlayer *ap = ape->get_player();
+						if (ap && editor->can_add_reset_key() && animation != ap->get_animation(SceneStringName(RESET))) {
+							menu->add_separator();
+							menu->add_icon_item(get_editor_theme_icon(SNAME("MoveUp")), TTR("Send Key(s) to RESET"), MENU_KEY_ADD_RESET);
```
Comment (KoBeWi) [inline editor/animation/animation_track_editor.cpp:3206]: "Send Key(s)"? What was wrong with the previous name and icon?

File: editor/animation/animation_track_editor.cpp [hunk 4]
```diff
@@ -4311,6 +4316,10 @@ void AnimationTrackEditor::commit_insert_queue() {
 }
 
 void AnimationTrackEditor::_query_insert(const InsertData &p_id) {
+	if (read_only) {
+		return; // Should have been prevented by dialog, but for safety.
```
Comment (KoBeWi) [inline editor/animation/animation_track_editor.cpp]: Should this be an error maybe? (`ERR_FAIL_COND`)

File: editor/animation/animation_track_editor.cpp (hunk 3 above)
Comment (TokageItLab) [reply editor/animation/animation_track_editor.cpp:3206]: Yes, while “Add RESET Value” could be read as adding the RESET animation value to the current track, the actual behavior is the opposite, so I’ve revised the explanation.

Comment (KoBeWi) [reply editor/animation/animation_track_editor.cpp:3206]: Was there any user confused by that option?
Either way, I'm not sure if MoveUp icon is proper here. You could use UndoRedo icon: image

Comment (TokageItLab) [reply editor/animation/animation_track_editor.cpp:3206]: I'm not sure if the UndoRedo icon is appropriate, but it gives the impression that it sets the current key value to the Reset animation's Value. As I said, the actual behavior is to transfer the value to the currently unseen Reset animation, which is not intuitive.

Although no actual issues have been reported, the main problem is that the Options menu contains a similar “Apply RESET” option. Having two options with arrows indicating reversal is quite confusing.

image

"Apply RESET" takes effect immediately on the current state, so the back arrow is appropriate. However, since “Add RESET Value” does nothing to the current animation, it should not reuse icons that indicate something happening immediately elsewhere.

File: editor/animation/animation_track_editor.cpp (hunk 2 above)
Comment (TokageItLab) [reply editor/animation/animation_track_editor.cpp:8471]: I think it's okay to generate it here for consistency with other dialogs.

**Review by KoBeWi — APPROVED** [review]

File: editor/animation/animation_track_editor.cpp [hunk 5]
```diff
@@ -8293,6 +8359,11 @@ AnimationTrackEditor::AnimationTrackEditor() {
 	track_copy_select->set_hide_root(true);
 	track_copy_vbox->add_child(track_copy_select);
 	track_copy_dialog->connect(SceneStringName(confirmed), callable_mp(this, &AnimationTrackEditor::_edit_menu_pressed).bind(EDIT_COPY_TRACKS_CONFIRM));
+
+	read_only_dialog = memnew(AcceptDialog);
+	read_only_dialog->set_title(TTRC("Key Insertion Error"));
+	read_only_dialog->set_text(vformat(TTRC("Imported Animation cannot be edited!")));
```
Comment (AThousandShips) [inline editor/animation/animation_track_editor.cpp]:
```suggestion
	read_only_dialog->set_text(TTRC("Imported Animation cannot be edited!"));
```

File: editor/animation/animation_track_editor.cpp [hunk 6]
```diff
@@ -4602,6 +4629,29 @@ void AnimationTrackEditor::insert_value_key(const String &p_property, bool p_adv
...
+	if (mixer) {
+		if (!mixer->has_animation_library("")) {
+			return false;
+		} else {
+			al = mixer->get_animation_library("");
+		}
+	}
+	if (al.is_valid()) {
+		String base = al->get_path();
+		int srpos = base.find("::");
```
Comment (lyuma) [inline editor/animation/animation_track_editor.cpp:4683]: This should be part of a core function like in Resource

**Review by lyuma — APPROVED** [review]
Seems good. Just check if we can share code for the read only check

**Comment by Repiteo** [comment]
Needs rebase

**Comment by TokageItLab** [comment]
@Repiteo Alright, rebased.

**Comment by Repiteo** [comment]
Thanks!
