### PR TITLE
Fix camera2d zoom when set to zero (affine_invert: Condition ' det == 0 ' is true)

### LINKED ISSUE #41873: Camera with invalid zoom values: ERROR: affine_invert: Condition ' det == 0 ' is true.
**Godot version:**
3.2.2

**OS/device including version:**
win7-64,GLES2

**Issue description:**
It seems that there are many situations that can cause this error:
https://github.com/godotengine/godot/issues/36642
https://github.com/godotengine/godot/issues/31090
  
I met the camera situation.

**Steps to reproduce:**
create a **Camera** node ,then set **Zoom** property to (0,0) and run the scene. 
you can see many  error as shown below:
```
ERROR: affine_invert: Condition ' det == 0 ' is true.  
ERROR: affine_invert: Condition ' det == 0 ' is true.  
ERROR: affine_invert: Condition ' det == 0 ' is true.  
```
I've tried to make negative numbers legal, like (-1,-1)
So I think the editor should prohibit setting the camera's zoom property to (0, 0),or change it to (1,1).  

  
  
**supplement:**
And I also found another problem with the camera, but I'm not sure if it's a bug. It  doesn't make any serious mistakes.
Correct situation:
If there are two camera nodes in the  **A** scene,Their **Current** properties are enabled.
**A** scene node structure:
```
--Node2D:
----Camera1   // Current is true
----Camera2    // Current is true
```

when the game runs,only one the **Current** properties of  Camera node will be enabled. 
```
--Node2D:
----Camera1   // Current is false
----Camera2    // Current is true
```
the editor can fix this to correct situation.

Feeling abnormal:
If there are two scene **A** and  **B**,each has a camera.Their **Current** properties are enabled.
And the  **A** scene has a  **B** scene instance node.
**A** scene node structure:
```
--Node2D:
----Camera1     // Current is true
----B                 // B scene instance
------Camera2   // Current is true
```

when the game runs,the two **Current** properties of  Camera node will be enabled. 
```
--Node2D:
----Camera1    // Current is true
----B                  // B scene instance
------Camera2    // Current is true
```
the editor not fix this situation.

**Minimal reproduction project:**
Both of the above issues are easy to implement

### PR DESCRIPTION
**Pull request by dreamsComeTrue**
Fixes: #41873
Can be cherry-picked to 3.x

### CODE REVIEW

File: scene/2d/camera_2d.cpp [hunk 1]
```diff
@@ -77,7 +77,18 @@ void Camera2D::_update_process_mode() {
...
+	Vector2 new_zoom = p_zoom;
+
+	// Setting zoom to zero causes 'affine_invert' issues
+	if (Math::is_zero_approx(p_zoom.x)) {
+		new_zoom.x = CMP_EPSILON * SGN(p_zoom.x);
+	}
+
+	if (Math::is_zero_approx(p_zoom.y)) {
+		new_zoom.y = CMP_EPSILON * SGN(p_zoom.y);
+	}
```
Comment (avencherus) [inline scene/2d/camera_2d.cpp:89]: Not sure, but wouldn't clamping be cleaner and have less operations?

Something like:

```
zoom.x = max(abs(p_zoom.x), CMP_EPSILON) * sign(p_zoom.x)
zoom.y = max(abs(p_zoom.y), CMP_EPSILON) * sign(p_zoom.y)
```

Comment (dreamsComeTrue) [reply scene/2d/camera_2d.cpp:89]: I wouldn't recommend to do it that way - because it's allowed to have negative values for a zoom as well. It's just problematic when scale is around zero.

Comment (avencherus) [reply scene/2d/camera_2d.cpp:89]: It works with negatives.  Did I miss something?

**Comment by aaronfranke** [comment]
Maybe this should be an `ERR_FAIL_COND_MSG`? I think we should inform the user if they set an invalid zoom.

**Comment by akien-mga** [comment]
I agree with @aaronfranke, this should be an `ERR_FAIL_COND_MSG()`.

Additonally, maybe a `PROPERTY_HINT_RANGE` could be added to the property to prevent setting `0` (unless negative zooms are supported to flip the camera, in which case there's no real way around it).

**Comment by dreamsComeTrue** [comment]
> 
> 
> Maybe this should be an `ERR_FAIL_COND_MSG`? I think we should inform the user if they set an invalid zoom.

Actually you're right guys - fixed - with that it seems much cleaner and nicer, editor now is basically cutting of any posibilites of setting 'x' or 'y' component to anything lower than 0.001 :)

Thanks for that suggestion!

File: scene/2d/camera_2d.cpp [hunk 2]
```diff
@@ -77,6 +77,9 @@ void Camera2D::_update_process_mode() {
 }
 
 void Camera2D::set_zoom(const Vector2 &p_zoom) {
+	// Setting zoom to zero causes 'affine_invert' issues
+	ERR_FAIL_COND_MSG(Math::is_zero_approx(p_zoom.x) || Math::is_zero_approx(p_zoom.y), "Zoom level must be different than 0 (can be negative).");
```
Comment (akien-mga) [inline scene/2d/camera_2d.cpp:81]: "different from 0" sounds more natural to me (though I checked and both seem to be valid).

Comment (dreamsComeTrue) [reply scene/2d/camera_2d.cpp]: Fixed!

**Review by aaronfranke — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
