### PR TITLE
Make some small enhancements to the ColorPicker

### LINKED ISSUE #21860: Color picker corrupts colors set in RAW mode
**Godot version:**
3.1-alpha - 530704375

**OS/device including version:**
Windows

**Issue description:**
When setting a color in RAW mode (in editor) with value >1, it will be set correctly, but it will be eventually corrupted in subsequent opening of color picker.

**Steps to reproduce:**
1. Create a Node2D
2. Set modulate to raw (5,0,0,1)
3. Blur the color picker
4. Click on the color picker again
5. Blur the color picker without interaction
6. Color has changed

**Expected result:**
Color stays same when I'm inspecting it.

### PR DESCRIPTION
**Pull request by YeldhamDev**
- Make the hexadecimal/code toggle actually look like a clickable button. Also hide it together with color `LineEdit`.
- Make the color `LineEdit` uneditable when in code mode.
- Fix #21860 (for real this time).
- Fix color LineEdit setting all values to 0 when focus is lost in code mode.
- Add some tooltips.

### CODE REVIEW

File: scene/gui/color_picker.cpp [hunk 1]
```diff
@@ -691,31 +695,39 @@ ColorPicker::ColorPicker() :
...
-	vbr->add_child(hhb);
+
 	text_type = memnew(Button);
-	text_type->set_flat(true);
-	text_type->connect("pressed", this, "_text_type_toggled");
 	hhb->add_child(text_type);
+	text_type->set_text("#");
+	text_type->set_tooltip(TTR("Switch between hexadecimal and code values."));
+	if (Engine::get_singleton()->is_editor_hint()) {
+		text_type->set_custom_minimum_size(Size2(28 * EDSCALE, 0)); // Adjust for the width of the "Script" icon.
```
Comment (akien-mga) [inline scene/gui/color_picker.cpp]: `EDSCALE` is only available within `#ifdef TOOLS_ENABLED`.

Comment (YeldhamDev) [reply scene/gui/color_picker.cpp]: Of course, fixed it.

**Comment by akien-mga** [comment]
Normally that's outside the scope of the release freeze, but given that it fixes #21860 I guess we can give it a try :)

**Comment by akien-mga** [comment]
Thanks!
