### PR TITLE
`TileSet` Simplify isometric tile shape polygon to 4 vertices

### LINKED ISSUE #69745: `TileSet` default tile shape creates broken navigation polygons for isometric tiles
### Godot version

v4.0.beta7.mono.official

### System information

Windows 10

### Issue description

The autogenerated navigation polygon has two extra points for isometric TileSets that throws an exception and prevents navigation.

[Related Issue #66283](https://github.com/godotengine/godot/issues/66283)

### Steps to reproduce

In the included project there is a main scene with a TileMap with a TileSet that has not yet had any navigation polygons painted on the walkable tile.

- Navigate to the walkable tile in the TileSet
- Activate Paint properties
- Clear the input
- Reset the input to the default tile shape
- Select the walkable tile to apply the properties
- Run the game

The result is no navigation and a repeated error:
```
_physics_process: Condition "least_cost_id == -1" is true. Breaking.
  <C++ Source>   modules/navigation/nav_map.cpp:261 @ get_path()
  <Stack Trace>  CharacterBody2D.gd:11 @ _physics_process()
```

To get the game running, edit the navigation polygon and remove the bonus points on the east and west sides of the polygon.

image

### Minimal reproduction project

[godot-iso-nav-bug.zip](https://github.com/godotengine/godot/files/10181437/godot-iso-nav-bug.zip)

### PR DESCRIPTION
**Pull request by kleonc**
For isometric tile shape `TileSet::get_tile_shape_polygon` was returning 6-vertex polygon with 2 duplicated vertices. No reason to do so, made it return 4-vertex polygon. AFAICT only `TileMap::draw_cells_outline` was relying on the exact layout of the returned vertices from `TileSet::get_tile_shape_polygon`, updated it appropriately.

Fixes #69745.

Also fixed UndoRedo action names for rotating/flipping tile polygons, they were all created as "Rotate Polygons Left".

Replaced few `append`s with `push_back`s for consistency.

Regarding potential further simplification of the default tile shape polygons: for `TILE_SHAPE_HALF_OFFSET_SQUARE` the currently generated 6-vertex square polygon with 2 of the square sides being divided in halfs is AFAICT desired for the navigation but it might be not needed for physics. Probably a 4-vertex square polygon would be sufficient for physics? :thinking:

### CODE REVIEW

**Comment by smix8** [comment]
Does the 6-vertex even work for navigation? Last I tested it failed due to edge overlap as the `points` array is later used as an outline to create the navigation polygon.

**Comment by kleonc** [comment]
> Does the 6-vertex even work for navigation? Last I tested it failed due to overlap as the `points` array is later used as an outline to create the navigation polygon.

For isometric tiles? It did not. I mean it seems to not fail immediately (no errors) when creating the navigation polygon with such duplicated points but it can fail later when e.g. trying to obtain a path from such created polygon, see https://github.com/godotengine/godot/issues/66283#issuecomment-1256097317. With this PR #66283 no longer happens when using the default shape polygon for isometric tiles (hence it fixes #69745).

The 6-vertex ones for `TILE_SHAPE_HALF_OFFSET_SQUARE` should work just fine. Not sure if changing them to 4-vertex squares would work at all.

How it is currently (neighbor edges match exactly, more points/edges):
vdyL3ebKKj

Alternative (some half-edge matching, less points/edges):
41Q32i4r2W
Haven't tested these, the above is just a mockup with NavigationRegion2Ds. @smix8 Do you think it would work? And if so, could it be better performance-wise than the current 6-vertex polygon?

**Comment by smix8** [comment]
Both 4 or 6 should work in this case.

I think the server has a very slightly easier time with 6-vertex due to this square layout only as it can pair and vertex merge the edges instead of doing the more costly calculations for all the leftover free edges but it matters little.

File: scene/2d/tile_map.cpp [hunk 1]
```diff
@@ -3907,10 +3907,10 @@ void TileMap::draw_cells_outline(Control *p_control, const RBSet<Vector2i> &p_ce
 		} else {
 			if (tile_set->get_tile_offset_axis() == TileSet::TILE_OFFSET_AXIS_HORIZONTAL) {
 				if (shape == TileSet::TILE_SHAPE_ISOMETRIC) {
-					DRAW_SIDE_IF_NEEDED(TileSet::CELL_NEIGHBOR_BOTTOM_RIGHT_SIDE, 3, 4);
-					DRAW_SIDE_IF_NEEDED(TileSet::CELL_NEIGHBOR_BOTTOM_LEFT_SIDE, 2, 3);
+					DRAW_SIDE_IF_NEEDED(TileSet::CELL_NEIGHBOR_BOTTOM_RIGHT_SIDE, 2, 3);
```
Comment (groud) [inline scene/2d/tile_map.cpp:3910]: This seems wrong. If the shape is the same for both mode, then you should not have different code path here. You should move that our of the if (like `TILE_SHAPE_SQUARE`) and make sure each side corresponds to the correct polygon index.

You can test that by selecting tiles in the TileMap if I am not mistaking, if the code is wrong selecting tiles on the TileMap will not work correctly.

File: scene/resources/tile_set.cpp [hunk 2]
```diff
@@ -1458,12 +1460,15 @@ Vector<Vector2> TileSet::get_tile_shape_polygon() {
...
-		points.append(Vector2(0.5, overlap - 0.5));
+		points.push_back(Vector2(0.0, -0.5));
+		points.push_back(Vector2(-0.5, overlap - 0.5));
+		points.push_back(Vector2(-0.5, 0.5 - overlap));
+		points.push_back(Vector2(0.0, 0.5));
+		points.push_back(Vector2(0.5, 0.5 - overlap));
+		points.push_back(Vector2(0.5, overlap - 0.5));
+	}
+
+	if (tile_shape != TileSet::TILE_SHAPE_SQUARE) {
```
Comment (groud) [inline scene/resources/tile_set.cpp:1471]: The half offset axis does not matter anymore here, but I understand it would be needed for the compatibility with the code I mentioned above (which might work in the end :thinking: ).

In any case, for cleaner code, I would simply change that to move that code inside the `else` statement above. And don't apply it to isometric shapes.

**Review by groud — CHANGES_REQUESTED** [review]

File: scene/resources/tile_set.cpp (hunk 2 above)
Comment (kleonc) [reply scene/resources/tile_set.cpp:1471]: Right, swapping xy is no longer needed for isometric tile polygon. I guess I somehow assumed not doing so could break something else, hence I've done it like that. But after rechecking it indeed seems like only `TileMap::draw_cells_outline` relies on that so it should be fine to simplify that.

File: scene/2d/tile_map.cpp (hunk 1 above)
Comment (kleonc) [reply scene/2d/tile_map.cpp:3910]: I tested before that it kept drawing the outlines correctly after my changes and it was working fine. But you're right, there's no longer need to swap xy for isometric tile polygon in case of different offset axis. And not doing so will make this branching not needed indeed.

File: scene/resources/tile_set.cpp (hunk 2 above)
Comment (groud) [reply scene/resources/tile_set.cpp]: Yeah, I've just checked too, I haven't find any other place where the code relies on the order of the vertices, so that should be fine.

Comment (kleonc) [reply scene/resources/tile_set.cpp]: Done, and tested that outlines are still drawn just fine for isometric + horizontal/vertical offset axis.

**Review by groud — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
