### PR TITLE
Fix display of embedded `Window`

### LINKED ISSUE #66809: Windows content is displayed wrong when embedded
### Godot version

v4.0.beta.custom_build [d331b803b] and v4.0.beta2.official

### System information

Linux and Windows

### Issue description

For the following aspect and mode combinations of a window the content is displayed wrong when the window is embedded.
aspect: `CONTENT_SCALE_ASPECT_KEEP`, `CONTENT_SCALE_ASPECT_KEEP_WIDTH`, `CONTENT_SCALE_ASPECT_KEEP_HEIGHT`.
mode: `CONTENT_SCALE_MODE_CANVAS_ITEMS`, `CONTENT_SCALE_MODE_VIEWPORT`

When embedded & When not embedded:
image image

I would expect, that the window content shows the same in both cases.

Since the non embedded version works the same in Linux and Windows and event position align with the non embedded version and the same display effect can be achieved by using `CONTENT_SCALE_ASPECT_IGNORE`, I assume, that this is a bug for embedded windows. So the embedded variant has wrong scaling and is missing the black bars at the top and bottom.

### Steps to reproduce

Have a window `w` with:
```GDScript
	w.set_size(Vector2(100, 200))
	w.set_content_scale_aspect(Window.CONTENT_SCALE_ASPECT_KEEP)
	w.set_content_scale_mode(Window.CONTENT_SCALE_MODE_VIEWPORT)
	w.set_content_scale_size(Vector2(50, 50))
```
It displays wrong when embedded.

1. Load and run the MRP
2. Click on the button to switch between embedding and not embedding mode.

### Minimal reproduction project

This is a MRP for the combination `CONTENT_SCALE_ASPECT_KEEP` and `CONTENT_SCALE_MODE_VIEWPORT`.
[BugWindowDisplayBar.zip](https://github.com/godotengine/godot/files/9696603/BugWindowDisplayBar.zip)

### PR DESCRIPTION
**Pull request by Sauermann**
Fix Rect of texture to take window and stretch transform into account.
resolve #66809
resolve part of #72760

MRP: [WindowsTestbed.zip](https://github.com/godotengine/godot/files/12231066/WindowsTestbed.zip) (run and set "Window height" to 150)

There is no need for `viewport_attach_to_screen` for embedded windows, since their display is handled via `Viewport::_sub_window_update`.

image image

Updated 2023-08-05: Draw black bars at the sides, that aren't covered by the content.
Updated 2024-12-16: Rebased on master for good measure. insert `const` expression, fix rounding issue.

### CODE REVIEW

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -343,7 +343,13 @@ void Viewport::_sub_window_update(Window *p_window) {
 		close_icon->draw(sw.canvas_item, r.position + Vector2(r.size.width - close_h_ofs, -close_v_ofs));
 	}
 
-	RS::get_singleton()->canvas_item_add_texture_rect(sw.canvas_item, r, sw.window->get_texture()->get_rid());
+	Transform2D xform = sw.window->window_transform * sw.window->stretch_transform;
+	Rect2i vr = xform.xform(sw.window->get_visible_rect());
+	vr.position += p_window->get_position();
+	if (vr != r) {
+		RS::get_singleton()->canvas_item_add_rect(sw.canvas_item, r, Color(0.0, 0.0, 0.0));
```
Comment (AThousandShips) [inline scene/main/viewport.cpp:350]:
```suggestion
		RS::get_singleton()->canvas_item_add_rect(sw.canvas_item, r, Color());
```
Equivalent, and briefer

Comment (Sauermann) [reply scene/main/viewport.cpp]: Indeed. Committed this improvement.

File: scene/main/viewport.cpp [hunk 2]
```diff
@@ -343,7 +343,13 @@ void Viewport::_sub_window_update(Window *p_window) {
 		close_icon->draw(sw.canvas_item, r.position + Vector2(r.size.width - close_h_ofs, -close_v_ofs));
 	}
 
-	RS::get_singleton()->canvas_item_add_texture_rect(sw.canvas_item, r, sw.window->get_texture()->get_rid());
+	Transform2D xform = sw.window->window_transform * sw.window->stretch_transform;
+	Rect2i vr = xform.xform(sw.window->get_visible_rect());
+	vr.position += p_window->get_position();
+	if (vr != r) {
+		RS::get_singleton()->canvas_item_add_rect(sw.canvas_item, r, Color());
```
Comment (Geometror) [inline scene/main/viewport.cpp:350]:
```suggestion
		const Color clear_color = RS::get_singleton()->get_default_clear_color();
		RS::get_singleton()->canvas_item_add_rect(sw.canvas_item, r, clear_color);
```
This way it's consistent with the other modes:
(clear color changed via project settings)

image

File: scene/main/viewport.cpp [hunk 3]
```diff
@@ -343,7 +343,13 @@ void Viewport::_sub_window_update(Window *p_window) {
 		close_icon->draw(sw.canvas_item, r.position + Vector2(r.size.width - close_h_ofs, -close_v_ofs));
 	}
 
-	RS::get_singleton()->canvas_item_add_texture_rect(sw.canvas_item, r, sw.window->get_texture()->get_rid());
+	Transform2D xform = sw.window->window_transform * sw.window->stretch_transform;
```
Comment (Geometror) [inline scene/main/viewport.cpp:346]:
```suggestion
	const Transform2D xform = sw.window->window_transform * sw.window->stretch_transform;
```

**Review by Geometror — COMMENTED** [review]
Rebased locally on current master and tested. I can confirm it fixes the linked issue.

File: scene/main/viewport.cpp (hunk 2 above)
Comment (Sauermann) [reply scene/main/viewport.cpp:350]: When changing the clear color and viewing the windows in a not-embedded form, then there are black bars, that aren't affected by the clear color.

image

My understanding is:
- The black color indicates, that in this area, there is no `Viewport`-node
- The clear color indicates, that in this area, there is the background of a `Viewport`-node

So the distinction between black color and clear color helps to visualize, where the `Viewport` ends.

This distinction between Viewport-area and non-Viewport-area would vanish, if these bars would also be set to clear color.

I would prefer to not follow your suggestion, so that this visual distinction is kept for the user and that the display is kept consistent between embedded and non-embedded windows.

File: scene/main/viewport.cpp (hunk 3 above)
Comment (Sauermann) [reply scene/main/viewport.cpp]: Done, thanks!

**Review by Geometror — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
