### PR TITLE
Fix FileSystem dock won't show any file folders (reverted)

### LINKED ISSUE #47053: Large projects seem frozen/crashed for several minutes on startup with poor editor feedback
**Godot version:**
v3.2.4.rc4.official
v4.x vulkan

**OS/device including version:**
Win10 64x

**Issue description:**
The editor seems to have a real struggle with very large Godot projects (50+ gb) ones per day on first startup.
I just clocked, the editor appears completely frozen/crashed for 7+ minutes on startup.

There is no feedback in both editor or console for users what is going on after the class_names and autoload scripts are successfully loaded.

There seems to be an issue with the file scanthread implementation. It seems the file scanthread has the desire to not only read all scriptfiles for changes but also open every single file each new day for no practical reason. As long as the scanthread is busy it blocks the entire editor until finished instead of working behind the scene.

The result is that the project appears nearly empty in the editor for a long time (shock moment, where are my files?) and also the editor stays unresponsive for several minutes as if it had a crash.

**How to solve?**

- Give continues, visual feedback to user about project load progress.
- Make file scanthread behave like a real, subtle background thread and not a nuisance by blocking editor startup until finished.
- Stop scanthread from opening all unchanged and very large asset files each day for no apparent, practical reason.

**Steps to reproduce:**
Create large Godot projects

**Minimal reproduction project:**
project size issue

### LINKED ISSUE #85082: When loading a project, the editor shows an empty scene before actually showing the last edited scene
### Godot version

4.2 beta5, beta6 and rc1

### System information

Windows 10 - Vulkan (Forward+) - RTX 3060 laptop - AMD Ryzen 5 5600H - 24GB RAM

### Issue description

Every time a project is loaded, after the boot splash, an empty scene like the one below appears:

image

After some time, the last edited scene is finally shown as expected.

I took the time to see after which version this occurs and I concluded that **this glitch is only present in 4.2 beta5, beta6 and rc1**. Godot 4.2beta4 and before works as expected

### Steps to reproduce

Just open a project with at least one saved scene. If the scene takes time to load, the glitch is more noticeable

### Minimal reproduction project

[glitchBlankScene.zip](https://github.com/godotengine/godot/files/13403038/glitchBlankScene.zip)

Just a simple scene with some high-poly count CSGMesh3D to make loading time big.  I didn't delete the .godot folder because that doesn't make Godot load the last edited scene. Anyway you can delete the .godot folder yourself and reopen the project a second time to see the glitch

### LINKED ISSUE #92335: FileSystem dock won't show any file / folders, and has performance issues when loading large folders
### Tested versions

Tested in 4.2.2 stable, 4.3 beta 5, 4.3 beta 6.

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.5186) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

I tried loading this sprite database : https://github.com/PMDCollab/SpriteCollab/tree/master/sprite
It's around ~1Go of .png (1025 pokemons + shinies, all in pixel art), saved in 1025 folders.

Here's the exhaustive list of what I encountered while trying to import that across three versions:
- It took any version tested 10+ minutes to import everything
- IF the import is successful, I need to Alt+F4 / task manager to exit godot
- While open, the editor seems to run fine. I can create empty new scenes, save, load and play them.
- I don't see any file nor folder in the FileSystem Dock, but I see them using the load window.

image
image

- Reloading the whole project fixes this last issue, but takes 10+ minutes of reimport and I need to do that every time I open godot.
- Alternatively, creating a folder will trigger a scan (taking again ~10min) and it will fix the problem, until you need to close / reopen the engine

image

- When the issue is fixed after reimporting, the filesystem dock will lag & jitter, making it hard to use
---

**Expected behaviour :** 
- Load the big folder (takes some time to import, but should be less than 10 minutes)
- After import, all the files can be seen in the filesystem dock without decreased performance
- We can close the engine whithout relying on task manager

### Steps to reproduce

- Create an empty project
- Try to import the sprite folder from provided link : https://github.com/PMDCollab/SpriteCollab/tree/master/sprite
- If successful, either godot will crash, or you won't be able to see the folder architecture after import
- If that's not the case, close godot and reopen it : all the folders should be gone from the filesystem dock

### Minimal reproduction project (MRP)

I can't upload the project here, as it weight too much.
It's an empty project with just the mentioned file above, no scripts, no editor settings, no scenes.

### PR DESCRIPTION
**Pull request by Hilderin**
Fixes #92335, Fixes #47053 and Fixes #85082

This PR improves:
- FileSystem Dock not showing progress bar on first file scanning
- Better progression (%) for scanning large projects with a lot of folders and files
- Performance optimization on scanning project files for large projects
- Add progression popup for _update_scan_actions step (instead of Editor freeze)
- Add progression popup for _update_script_classes step (instead of Editor freeze)
- Add progression popup for loading editor layout and reopening scenes (instead of Editor freeze)

I tested these modifications with a project having all the files from https://github.com/PMDCollab/SpriteCollab/tree/master/sprite (more than 125000 files and 385Mb).

Before:
FileSystem was empty without any feedback for a couple of minutes and after that the editor was just frozen:

image

After modifications:
image
image

**Performance optimization on project scanning before asset importation**
For a 30000 files project, it took around 2m50s on startup to scan the project.
After a couple of optimizations, it now takes 1m30s for the same project.

Before:
image

After:
image

Causes:
- The FileAccess:exists was calling the open method which has a couple of overhead over file_exists.
- The _scan_new_dir was double sorting the folders.
- The reimport_files was recalculating the import_groupe_file even if _update_scan_actions did that just before.

** Edit: Add progression popup for loading editor layout and reopening scenes.

### CODE REVIEW

**Comment by Hilderin** [comment]
I need your advise... if you look at the issue #85082, one of the problem was that an empty scene was present during the loading.
With this PR, this empty scene is present but a progress bar is displayed in the FileSystem Dock. My concern is that the user can modify this empty scene and do a lot of things in the editor while the project file scan is in progress.

I can let this that way, at lease now, the user as a feedback from the editor.

An easy fix for that would be to run the first scan on the matin thread, blocking the user from interacting with the editor. Anyway, if there are files to reimport, the editor does it on the main thread. I could display the progression for the scan in a popup instead of the FileSystem, but the empty scene would still be visible.

I guess the perfect solution would be to not show the editor while loading, only progress popups, but I think was would need a lot more work?

**Comment by KoBeWi** [comment]
I tested it with my project. I got FileSystemScan, then some new Scan Actions popup, then scene group scan popup and then an awkward 3 or 4 seconds freeze. Though on subsequent launches only the scan was performed, so I think other actions came from version difference.

> With this PR, this empty scene is present but a progress bar is displayed in the FileSystem Dock. My concern is that the user can modify this empty scene and do a lot of things in the editor while the project file scan is in progress.

That's not really a problem, as the changes are not lost. If we really wanted to prevent that, the simplest solution is displaying a fully transparent Control over the whole editor that will block input.

File: editor/editor_file_system.cpp [hunk 1]
```diff
@@ -900,15 +924,23 @@ void EditorFileSystem::_scan_new_dir(EditorFileSystemDirectory *p_dir, Ref<DirAc
...
 				if (fc->uid == ResourceUID::INVALID_ID) {
 					// imported files should always have a UID, so attempt to fetch it.
 					fi->uid = ResourceLoader::get_resource_uid(path);
 				}
 
 			} else {
-				fi->type = ResourceFormatImporter::get_singleton()->get_resource_type(path);
-				fi->uid = ResourceFormatImporter::get_singleton()->get_resource_uid(path);
-				fi->import_group_file = ResourceFormatImporter::get_singleton()->get_import_group_file(path);
+				// Using get_resource_import_info to prevent calling 3 times ResourceFormatImporter::_get_path_and_type
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:942]:
```suggestion
				// Using get_resource_import_info() to prevent calling 3 times ResourceFormatImporter::_get_path_and_type.
```

**Comment by Hilderin** [comment]
Thanks for the review. I definitively still need time to adjust to Godot standard. I'll try to be more careful next time.
All requested changes should be effective now.

**Comment by Hilderin** [comment]
@KoBeWi thanks for testing this PR.

> I tested it with my project. I got FileSystemScan, then some new Scan Actions popup, then scene group scan popup and then an awkward 3 or 4 seconds freeze.

I'm intrigued with the _**3 or 4 seconds freeze**_, it's sounds like what @Zireael07 or @smix8 was explaining on the first load in #47053. Do you have the freeze after a reboot or the next day? I guess I can't have access to your project? Maybe you can explain to me briefly the amount and type of resources you have in your project so I can try to reproduce. Are you on Windows, Linux or Mac?

**Comment by KoBeWi** [comment]
It might be related to plugins, autoloads and global scripts. Especially plugins, as I have many of them. Though it was a one-time thing, I'll see if it repeats tomorrow and report back.

**Comment by KoBeWi** [comment]
I tested again and it still happened, but only once. Though it's not the same as reported by Zireael and smix, because it's much shorter. I think the original issue with unresponsive editor is covered by the new scan progresses, the remaining time can also come from restoring scenes.

I can send you the project if you want to test it, but it's quite big. DM me on the chat.

**Review by KoBeWi — APPROVED** [review]

**Comment by Hilderin** [comment]
After testing with the project from KoBeWi, I found 2 problems:

First: Update scene groups was triggered during reimportation because the ResourceImporterCSVTranslation is calling ResourceLoader.save() which trigger update_files. I added a condition to prevent updating script and scene groups during importation. It is done at the end of first scan.
That was causing a double progress:
image
image

Second: As KoBeWi suspected, the froze editor was caused by the reopening of the scenes. On my PC, it takes 8 secs processing the first `sources_changed` caused by `EditorNode::_load_editor_layout`. I added another progress popup to prevent the frozen effect.
image
image


That is what is looks now:

https://github.com/godotengine/godot/assets/81109165/ea1ac2b2-22e1-469e-9a9a-0a543bbda229

File: editor/editor_file_system.cpp [hunk 2]
```diff
@@ -1743,9 +1794,13 @@ void EditorFileSystem::update_file(const String &p_file) {
...
 
-		_update_pending_script_classes();
-		_update_pending_scene_groups();
-		call_deferred(SNAME("emit_signal"), "filesystem_changed"); //update later
+		// Preventing update of scripts and scene groups while first scan.
+		// Some ResourceLoader resave files which invoke update_file while loading (ex: ResourceImporterCSVTranslation).
+		if (!first_scan) {
+			_update_pending_script_classes();
+			_update_pending_scene_groups();
+			call_deferred(SNAME("emit_signal"), "filesystem_changed"); //update later
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:1802]:
```suggestion
			call_deferred(SNAME("emit_signal"), "filesystem_changed"); // Update later.
```

Comment (Hilderin) [reply editor/editor_file_system.cpp]: Done!

**Comment by Hilderin** [comment]
Just rebased following conflicts.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Apologies, I jumped the gun on this PR which touches very core parts of the engine, prone to regressions and subtle bugs. I trusted existing reviews and forgot to assess how risky the changes are myself.

I think this should be kept for 4.4 as there will be likely be a number of follow-up issues that will be best handled in the 4.4 dev cycle than now as we try to stabilize 4.3.

So I'll revert the merge for 4.3, and would suggest reopening a PR with the same changes, that will target 4.4 and require more testing before merge.

**Comment by Hilderin** [comment]
No problem @akien-mga , I'll reopen later!
