### PR TITLE
Fix multiline array/dictionary match statements

### LINKED ISSUE #90372: Match statement doesn't support multiline array/dictionary expressions
### Tested versions

- Reproducible in Godot Engine v4.3.dev

### System information

MacOS - Godot Engine v4.3.dev

### Issue description

GDScript's `match` statement, requires dictionary and array case expressions to be in a single line. For any remotely complex case this means that you have lines that exceed the line limit. 

Currently this code results in the following error:  
```gdscript 
var message : Dictionary = {}

match message:
	{
		"metadata" : { "message_type": "session_welcome", ..},
		"payload": {
			"session": { "keepalive_timeout_seconds": var keep_alive, .. },
		},
		..,
	}:
		print("We are welcomed, keep alive = %d" % keep_alive)
```

```
Parse Error: Expected expression as key for dictionary pattern.
```

Given dictionaries could normally be defined over multiple lines, I would expect this to be valid syntax. 

### Steps to reproduce

Copy snippet from above into a new GDScript method to view errors. 

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bitwise-aiden**
Currently array and dictionary expressions cannot be spread over multiple lines in match statements.

Adding mutliline push/pop while parsing the pattern for bracket and brace enables the ability for these to be multiline. This enables more complex patterns to be matched without exceeding line limits.

Fixes #90372

### CODE REVIEW

**Comment by dalexeev** [comment]
Thank you for the PR! Please add test cases for this.

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -2270,28 +2270,31 @@ GDScriptParser::PatternNode *GDScriptParser::parse_match_pattern(PatternNode *p_
...
+					continue;
+				}
+				if (pattern->rest_used) {
+					push_error(R"(The ".." pattern must be the last element in the pattern array.)");
+				} else if (sub_pattern->pattern_type == PatternNode::PT_REST) {
+					pattern->rest_used = true;
+				}
+				pattern->array.push_back(sub_pattern);
+			} while (match(GDScriptTokenizer::Token::COMMA));
+			pop_multiline();
```
Comment (bitwise-aiden) [inline modules/gdscript/gdscript_parser.cpp:2291]: Had to invert the check to properly handle multiline. This is now parity with how dictionary patterns are handled too.

**Comment by bitwise-aiden** [comment]
> Thank you for the PR! Please add test cases for this.

I believe this is good to go, let me know if there is anything else you're after.

File: modules/gdscript/gdscript_parser.cpp [hunk 2]
```diff
@@ -2270,28 +2270,31 @@ GDScriptParser::PatternNode *GDScriptParser::parse_match_pattern(PatternNode *p_
...
 			consume(GDScriptTokenizer::Token::BRACKET_CLOSE, R"(Expected "]" to close the array pattern.)");
```
Comment (dalexeev) [inline modules/gdscript/gdscript_parser.cpp:2292]:
```suggestion
			consume(GDScriptTokenizer::Token::BRACKET_CLOSE, R"(Expected "]" to close the array pattern.)");
			pop_multiline();
```

File: modules/gdscript/gdscript_parser.cpp [hunk 3]
```diff
@@ -2333,6 +2336,7 @@ GDScriptParser::PatternNode *GDScriptParser::parse_match_pattern(PatternNode *p_
 					}
 				}
 			} while (match(GDScriptTokenizer::Token::COMMA));
+			pop_multiline();
 			consume(GDScriptTokenizer::Token::BRACE_CLOSE, R"(Expected "}" to close the dictionary pattern.)");
```
Comment (dalexeev) [inline modules/gdscript/gdscript_parser.cpp:2340]:
```suggestion
			consume(GDScriptTokenizer::Token::BRACE_CLOSE, R"(Expected "}" to close the dictionary pattern.)");
			pop_multiline();
```

**Comment by dalexeev** [comment]
Please [squash commits into one](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase). To do this you need a local git client, GitHub web interface doesn't support it.

File: modules/gdscript/tests/scripts/parser/features/match_array.gd [hunk 4]
```diff
@@ -0,0 +1,33 @@
+func foo(x):
+	match(x):
```
Comment (dalexeev) [inline modules/gdscript/tests/scripts/parser/features/match_array.gd:2]:
```suggestion
	match x:
```

**Review by dalexeev — APPROVED** [review]

File: modules/gdscript/tests/scripts/parser/features/match_array.gd (hunk 4 above)
Comment (dalexeev) [reply modules/gdscript/tests/scripts/parser/features/match_array.gd:2]: Here and in `match_dictionary.gd`.

Comment (akien-mga) [reply modules/gdscript/tests/scripts/parser/features/match_array.gd]: Amended the commit with this fixup.

**Comment by akien-mga** [comment]
Thanks!
