### PR TITLE
Preserve original name in shader params cache

### LINKED ISSUE #50936: [Godot4] shader param not effect
### Godot version

v4.0.dev.calinou [e6a544c16]

### System information

Window10

### Issue description

shader param not effect

### Steps to reproduce

run reproduction project

### Minimal reproduction project

[ShaderParamTest.zip](https://github.com/godotengine/godot/files/6884947/ShaderParamTest.zip)

### PR DESCRIPTION
**Pull request by aaronfranke**
Fixes #50936, which was a regression from #50511.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]

**Comment by Chaosus** [comment]
Thanks! :)

File: scene/resources/shader.cpp [hunk 1]
```diff
@@ -76,8 +76,9 @@ void Shader::get_param_list(List<PropertyInfo> *p_params) const {
 		if (default_textures.has(pi.name)) { //do not show default textures
 			continue;
 		}
+		String original_name = pi.name;
 		pi.name = "shader_param/" + pi.name;
-		params_cache[pi.name] = pi.name;
+		params_cache[pi.name] = original_name;
```
Comment (akien-mga) [inline scene/resources/shader.cpp:81]: I'm not sure this fix restores the original behavior of the code prior to #50511.

It used to be:
```cpp
for (List<PropertyInfo>::Element *E = local.front(); E; E = E->next()) {
		PropertyInfo pi = E->get();
		pi.name = "shader_param/" + pi.name;
		params_cache[pi.name] = E->get().name;
```
i.e. `pi` was a copy which got its named modified.

With the new code, `pi` is a reference, so we're modifying the name of `local`'s copy of the param list IINM.

I don't know if it's a problem, but that's worth noting.

Comment (Chaosus) [reply scene/resources/shader.cpp:81]: Yep, sorry about the quick merge - but I've really quite tired of this bug, and this PR really fixes it.

Comment (clayjohn) [reply scene/resources/shader.cpp:81]: @akien-mga in either case ``pi`` is modified before it is stored in p_params. So that is likely not an issue. The real issue is that the copy of the Property info stored in local  (e.g. the copy returned by ``RenderingServer::get_singleton()->shader_get_param_list(shader, &local);``) will be incorrectly changed. 

Although, now that I think about it. I remember JFons talking about this new iterator approach creating copies unless we added const or something. Perhaps this iterator is making a copy of ``pi`` anyway?
