### PR TITLE
Disable unsupported SSR, SSS, DoF on transparent viewports

### LINKED ISSUE #73817: SSR causes opaque meshes inside a subviewport with transparent bg to get invisible
### Godot version

4.0 RC3

### System information

Windows 10, Vulkan

### Issue description

Enabling SSR in the environment causes opaque objects placed inside subviewport with transparent backround enabled disappear, they are not being rendered.

### Steps to reproduce

- Create subviewport in the scene with camera in it and place it inside subviewport container.
- Create mesh instances inside and set its layer to be rendered only by the subviewport
- Enable SSR in the scene's environment

### Minimal reproduction project

[Subviewport transparent bg.zip](https://github.com/godotengine/godot/files/10813996/Subviewport.transparent.bg.zip)

### PR DESCRIPTION
**Pull request by Calinou**
- Follow-up to https://github.com/godotengine/godot/pull/107232 (can be merged independently).

For technical reasons, transparent viewports cannot support screen-space reflections, subsurface scattering and depth of field. Previously, enabling any of these would turn transparent viewports invisible.

- This closes https://github.com/godotengine/godot/issues/73817.

## Preview

image

### CODE REVIEW

File: servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp [hunk 1]
```diff
@@ -1900,6 +1904,11 @@ void RenderForwardClustered::_render_scene(RenderDataRD *p_render_data, const Co
 
 	bool using_sss = rb_data.is_valid() && !is_reflection_probe && scene_state.used_sss && ss_effects->sss_get_quality() != RS::SUB_SURFACE_SCATTERING_QUALITY_DISABLED;
 
+	if (using_sss && p_render_data->transparent_bg) {
+		WARN_PRINT_ONCE("Sub-surface scattering is not supported in viewports with a transparent background. Disabling SSS in transparent viewport.");
+		using_sss = false;
+	}
+
 	if ((using_sss || ce_needs_separate_specular) && !using_separate_specular) {
```
Comment (Calinou) [inline servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:1912]: This check makes me curious: are *all* compositor effects that need separate specular broken when using a transparent background? If so, we should add a dedicated warning here when such an effect is used.

File: doc/classes/Viewport.xml [hunk 2]
```diff
@@ -442,6 +442,7 @@
 		</member>
 		<member name="transparent_bg" type="bool" setter="set_transparent_background" getter="has_transparent_background" default="false">
 			If [code]true[/code], the viewport should render its background as transparent.
+			[b]Note:[/b] Due to technical limitations, certain rendering features are disabled when a viewport has a transparent background. This currently applies to screen-space reflections, subsurface scattering and depth of field.
```
Comment (AThousandShips) [inline doc/classes/Viewport.xml]:
```suggestion
			[b]Note:[/b] Due to technical limitations, certain rendering features are disabled when a viewport has a transparent background. This currently applies to screen-space reflections, subsurface scattering, and depth of field.
```

**Review by clayjohn — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Comment by Repiteo** [comment]
Cherry-picked to 4.5
