### PR TITLE
BasisU: Use KTX2 format and add import options to configure encoder

### LINKED ISSUE #12165: Add project settings to configure Basis Universal compression
### Describe the project you are working on

Games that require smaller disk size.

### Describe the problem or limitation you are having in your project

Related issue: https://github.com/godotengine/godot/issues/105012.

Currently Godot Basis Universal compressor uses uastc format and disables zstd and rdo by default

https://github.com/godotengine/godot/blob/a210fe6dbd27cc01bffacb0ce2816e0cf303af5e/modules/basis_universal/image_compress_basisu.cpp#L81-L115

```cpp
        basisu::basis_compressor_params params;

	params.m_uastc = true;
	params.m_quality_level = basisu::BASISU_QUALITY_MIN;
	params.m_pack_uastc_flags &= ~basisu::cPackUASTCLevelMask;
	params.m_pack_uastc_flags |= basisu::cPackUASTCLevelFastest;

	params.m_rdo_uastc = 0.0f;
	params.m_rdo_uastc_quality_scalar = 0.0f;
	params.m_rdo_uastc_dict_size = 1024;

	params.m_mip_fast = true;
	params.m_multithreading = true;
	params.m_check_for_alpha = false;
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow to configure Basis Universal compression.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add project settings to configure Basis Universal packer, such as zstd level, rdo quality scalar, uastc quality level (for compression speed).

If this is implemented, I would suggest https://github.com/godotengine/godot/pull/104571 doesn't compress BasisU textures.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it can't.

### Is there a reason why this should be core and not an add-on in the asset library?

It's core

### LINKED ISSUE #105012: Basis Universal Imported texture disk size is the same as vram compressed and doesn't discard unused alpha channel
### Tested versions

4.4, 4.5

### System information

Godot v4.5.dev.mono  - EndeavourOS  SMP PREEMPT_DYNAMIC Sun, 23 Mar 2025 17:17:30 +0000 on Wayland - X11 display driver, Multi-window, 1 monitor - Vulkan (Mobile) - integrated AMD Radeon Graphics (RADV RENOIR) - AMD Ryzen 7 4800U with Radeon Graphics (16 threads)

### Issue description

The [docs](https://docs.godotengine.org/en/latest/tutorials/assets_pipeline/importing_images.html) say basis universal provides very small disk size, but actually its size is the same as vram compressed:  

Image

( the `test.png` is rgb8, `atest.png` is rgba8 )

Also, basis universal doesn't discard the unused alpha channel, which makes its size even 2x larger.

This also happens in PortableCompressedTexture.

I also try using basisu command line tool to compress, the ktx2 images I get is much smaller [test_images.zip](https://github.com/user-attachments/files/19601445/test_images.zip):
```bash
basisu -uastc test.png
basisu -uastc atest.png
```

Image

### Steps to reproduce

Import textures using basis universal compression.

### Minimal reproduction project (MRP)

[basis-import-test.zip](https://github.com/user-attachments/files/19601172/basis-import-test.zip)

### PR DESCRIPTION
**Pull request by beicause**
Implements and closes https://github.com/godotengine/godot-proposals/issues/12165
Should fix #105012.

Different from proposal: the project settings have been changed to import options to better adjust individual texture compression.

This PR switchs the basis format to ktx2 format and adds import options that allow to enable zstd supercompression and [ Rate-Distortion Optimizated (RDO)](https://en.wikipedia.org/wiki/Rate%E2%80%93distortion_optimization) to significantly reduce disk size of basisu textures.

Also adds the same settings for PortableCompressedTexture2D.

### CODE REVIEW

**Review by fire — APPROVED** [review]
Needs testing, but agree with the feature proposal.

File: modules/basis_universal/image_compress_basisu.cpp [hunk 1]
```diff
@@ -398,37 +413,34 @@ Ref<Image> basis_universal_unpacker_ptr(const uint8_t *p_data, int p_size) {
 	src_ptr += 4;
 	src_size -= 4;
 
-	basist::basisu_transcoder transcoder;
-	ERR_FAIL_COND_V(!transcoder.validate_header(src_ptr, src_size), image);
-
-	transcoder.start_transcoding(src_ptr, src_size);
+	basist::ktx2_transcoder transcoder;
+	ERR_FAIL_COND_V(!transcoder.init(src_ptr, src_size), image);
```
Comment (BlueCube3310) [inline modules/basis_universal/image_compress_basisu.cpp:417]: This breaks compatibility with older .basisu files. A flag should be added to the `decompress_format` field to inform the decoder that the .ktx version is used instead. If the flag is missing, the transcoder should use the older codec

File: doc/classes/ProjectSettings.xml [hunk 2]
```diff
@@ -3196,6 +3196,27 @@
...
+			If less than or equal to [code]0[/code], the quality will be automatically controlled. Otherwise, it controls the quality level, ranges from 1 to 255.
+		</member>
+		<member name="rendering/textures/basis_universal/rdo_dict_size" type="int" setter="" getter="" default="1024">
+			Specify the dict size for RDO, ranges from 64 to 65536.
+		</member>
+		<member name="rendering/textures/basis_universal/rdo_enabled" type="bool" setter="" getter="" default="false">
+			If [code]true[/code], enables Rate-Distortion Optimization (RDO) to reduce disk size.
+		</member>
+		<member name="rendering/textures/basis_universal/rdo_quality_scalar" type="float" setter="" getter="" default="1.0">
+			Specify the quality scalar for RDO, ranges from 0.001 to 50.0.
```
Comment (BlueCube3310) [inline doc/classes/ProjectSettings.xml:3209]: It should be made more clear which way this scalar affects the quality, it looks like as its value increases the texture quality becomes lower.

**Comment by beicause** [comment]
1024x1024 png(alpha unused): 
</img>

|method|disk size|encoding time|
|-|-|-|
|origin png|25.0 KiB (25,552)|-|
|q=1, fastest (default project settings)|1.0 MiB (1,048,828)|19 ms|
|q=1, fastest, zstd |9.9 KiB (10,179)|20 ms|
|q=1, fastest, zstd, rdo|9.8 KiB (10,074)|36 ms|
|q=0, medium, zstd, rdo, dict_size=4096 (default basisu params)|11.7 KiB (11,937)|95 ms|

4096x4096 jpg(alpha unused)
</img>
|method|disk size|encoding time|
|-|-|-|
|origin jpg|9.2 MiB (9,637,440)|-|
|q=1, fastest (default project settings)|16.0 MiB (16,777,468)|780 ms|
|q=1, fastest, zstd |15.4 MiB (16,117,890)|900 ms|
|q=1, fastest, zstd, rdo|15.0 MiB (15,707,026)|10000 ms|
|q=1, fastest, zstd, rdo, rdo_quality_scalar=2.0|13.9 MiB (14,600,149)|10000 ms|
|q=1, fastest, zstd, rdo, rdo_quality_scalar=3.0|12.8 MiB (13,411,973)|9400 ms|
|q=1, fastest, zstd, rdo, rdo_quality_scalar=5.0|11.0 MiB (11,523,290)|7500 ms|
|q=1, fastest, zstd, rdo, rdo_quality_scalar=10.0|9.1 MiB (9,491,140)|5200 ms|
|q=1, fastest, zstd, rdo, rdo_quality_scalar=50.0(lowest quality) |8.5 MiB (8,874,016)|3900 ms|
|q=0, fastest, zstd, rdo, rdo_quality_scalar=3.0|12.8 MiB (13,411,973)|9100 ms|
|q=0, fastest, zstd, rdo, rdo_quality_scalar=3.0, dict_size=4096|12.0 MiB (12,539,692)|27500 ms|
|q=0, medium, zstd, rdo, dict_size=4096 (default basisu params)|15.3 MiB (16,027,703)|53000 ms|

basisu v1.50.0 command line
```
time basisu  -uastc aerial_rocks_02_diff_4k.jpg
________________________________________________________
Executed in   12.93 secs    fish           external
   usr time  186.04 secs    0.00 micros  186.04 secs 
   sys time    0.61 secs  970.00 micros    0.61 secs

aerial_rocks_02_diff_4k.ktx2 15.7 MiB(16,499,621)
```

File: doc/classes/ProjectSettings.xml [hunk 3]
```diff
@@ -3196,6 +3196,27 @@
 		<member name="rendering/shading/overrides/force_vertex_shading" type="bool" setter="" getter="" default="false">
 			If [code]true[/code], forces vertex shading for all rendering. This can increase performance a lot, but also reduces quality immensely. Can be used to optimize performance on low-end mobile devices.
 		</member>
+		<member name="rendering/textures/basis_universal/quality_level" type="int" setter="" getter="" default="1">
+			If less than or equal to [code]0[/code], the quality will be automatically controlled. Otherwise, it controls the quality level, ranges from 1 to 255.
+		</member>
+		<member name="rendering/textures/basis_universal/rdo_dict_size" type="int" setter="" getter="" default="1024">
+			Specify the dict size for RDO, ranges from 64 to 65536.
```
Comment (BlueCube3310) [inline doc/classes/ProjectSettings.xml:3203]: This description should mention how this setting affects the compression speed/memory usage

File: doc/classes/ProjectSettings.xml (hunk 2 above)
Comment (fire) [reply doc/classes/ProjectSettings.xml:3209]: We could invert the value for usability

**Comment by beicause** [comment]
I'm considering move these settings to texture import options that allow setting different compression params for different texture. Some extreme settings are not suitable for all textures.

File: modules/basis_universal/image_compress_basisu.cpp (hunk 1 above)
Comment (beicause) [reply modules/basis_universal/image_compress_basisu.cpp:417]: Do we need to be compatible with the old imported files? Users just need to reimport the textures using the new editor.

Comment (BlueCube3310) [reply modules/basis_universal/image_compress_basisu.cpp:417]: That is true, but I think updating a project to newer versions should be as seamless as possible for users. Most other parts of the import pipeline are kept backwards-compatible as well.

**Comment by michaelharmonart** [comment]
I think having per texture import settings makes sense. That's the first place I'd think to go to adjust quality for any other texture format in godot

**Comment by fire** [comment]
I think we should get together and review the design of the options.

**Comment by beicause** [comment]
basisu v1.60 #103968 seems to be a great improvement and something is changed.

The m_quality_level is renamed to m_etc1s_quality_level which explicitly indicates it doesn't affect uastc. So this param should be removed.

Need retesting in v1.60.

**Comment by beicause** [comment]
In basisu v1.60 I also get ~4x imporvement (5500 ms -> 1400 ms) for https://polyhaven.com/a/cambridge 4096x2048, no mipmaps. But for the images in https://github.com/godotengine/godot/pull/105080#issuecomment-2781320112, It doesn't instead it's slightly slower. The compressed size is exactly the same in 1.50 and 1.60. Compression speed may vary depending on the texture.

**Comment by michaelharmonart** [comment]
ran into some mystical (probably linktime) problems with basisU on the web recently 
https://github.com/godotengine/godot/issues/104497

Any chance you've tested the new basisU version on a release build/export template for the web

Guess I'm just hoping it'll magically fix it 😂 (probably not, but hey it's worth a shot)

**Comment by beicause** [comment]
I placed the basisu parameters in a struct to improve readability.

And I'd like to enable zstd by default to actually make basisu disk size smaller as described in [docs](https://docs.godotengine.org/en/latest/tutorials/assets_pipeline/importing_images.html#compress-mode)

File: doc/classes/PortableCompressedTexture2D.xml [hunk 4]
```diff
@@ -43,6 +43,19 @@
...
+			<return type="void" />
+			<param index="0" name="uastc_pack_level" type="int" />
+			<param index="1" name="rdo_enabled" type="bool" />
+			<param index="2" name="rdo_quality_loss" type="float" />
+			<param index="3" name="rdo_dict_size" type="int" />
+			<param index="4" name="zstd_supercompression" type="bool" />
+			<param index="5" name="zstd_supercompression_level" type="int" />
+			<description>
+				Set compressor params for Basis Universal compression. See also the settings in [ResourceImporterTexture].
+				Note: This must be set before [method create_from_image] to take effect.
```
Comment (AThousandShips) [inline doc/classes/PortableCompressedTexture2D.xml:56]:
```suggestion
				[b]Note:[/b] This must be set before [method create_from_image] to take effect.
```

File: doc/classes/PortableCompressedTexture2D.xml [hunk 5]
```diff
@@ -55,6 +68,7 @@
 		<member name="keep_compressed_buffer" type="bool" setter="set_keep_compressed_buffer" getter="is_keeping_compressed_buffer" default="false">
 			When running on the editor, this class will keep the source compressed data in memory. Otherwise, the source compressed data is lost after loading and the resource can't be re saved.
 			This flag allows to keep the compressed data in memory if you intend it to persist after loading.
+			Note: This must be set before [method create_from_image] to take effect.
```
Comment (AThousandShips) [inline doc/classes/PortableCompressedTexture2D.xml:71]:
```suggestion
			[b]Note:[/b] This must be set before [method create_from_image] to take effect.
```

**Review by AThousandShips — APPROVED** [review]

File: doc/classes/ResourceImporterLayeredTexture.xml [hunk 6]
```diff
@@ -10,6 +10,24 @@
...
 	</tutorials>
 	<members>
+		<member name="basis_universal/rdo_dict_size" type="int" setter="" getter="" default="1024">
+			Specify the RDO dict size, ranges from 64 to 65536. Higher values increase memory consumption and reduce encoding speed, but give more compression.
+		</member>
+		<member name="basis_universal/rdo_enabled" type="bool" setter="" getter="" default="false">
+			If [code]true[/code], enables Rate-Distortion Optimization (RDO) to reduce disk size.
+		</member>
+		<member name="basis_universal/rdo_quality_loss" type="float" setter="" getter="" default="1.0">
+			Specify the RDO quality loss, ranges from 0.001 to 50.0. Higher value result in smaller file size but lower quality. Good range to try is from 0.25 to 10.0.
```
Comment (Mickeon) [inline doc/classes/ResourceImporterLayeredTexture.xml:20]:
```suggestion
			The RDO quality loss, as a value ranging from [code]0.001[/code] to [code]50.0[/code]. Higher values result in smaller file sizes but lower quality. It is recommended to choose values from [code]0.25[/code] to [code]10.0[/code].
```

Also applies to the equivalent in **ResourceImporterTexture**.

File: doc/classes/ResourceImporterLayeredTexture.xml [hunk 7]
```diff
@@ -10,6 +10,24 @@
...
+		</member>
+		<member name="basis_universal/uastc_pack_level" type="int" setter="" getter="" default="0">
+			Sets the UASTC compressor's level, ranges from 0 to 4. Slower encoding speed improves quality.
```
Comment (Mickeon) [inline doc/classes/ResourceImporterLayeredTexture.xml:23]: "Slower encoding speed improves quality"? What does this mean?
```suggestion
			Sets the UASTC compressor's level, ranging from [code]0[/code] to [code]4[/code]. Higher values result in better quality but slower encoding speed.
```
Also, are you sure the quality gets better, and it's not the compression that is improved?

Also applies to the equivalent in **ResourceImporterTexture**.

File: doc/classes/ResourceImporterLayeredTexture.xml [hunk 8]
```diff
@@ -10,6 +10,24 @@
...
+		</member>
+		<member name="basis_universal/zstd_supercompression" type="bool" setter="" getter="" default="true">
+			If [code]true[/code], enables Zstandard supercompression to reduce disk size.
+		</member>
+		<member name="basis_universal/zstd_supercompression_level" type="int" setter="" getter="" default="6">
+			Specify the compression level for Zstandard supercompression.
```
Comment (Mickeon) [inline doc/classes/ResourceImporterLayeredTexture.xml:29]: This is missing a bunch of detail that would be similar to `basis_universal/uastc_pack_level`

Also applies to the equivalent in **ResourceImporterTexture**.

File: doc/classes/ResourceImporterLayeredTexture.xml (hunk 7 above)
Comment (beicause) [reply doc/classes/ResourceImporterLayeredTexture.xml]: This mainly affects quality and encoding speed. In fact, it slightly increases the disk size.
See also https://github.com/BinomialLLC/basis_universal/blob/04f30f081ae484a58dc281bcbea27edc0a5d5449/basisu_tool.cpp#L156-L157.

File: doc/classes/ResourceImporterLayeredTexture.xml [hunk 9]
```diff
@@ -10,6 +10,24 @@
 		<link title="Importing images">$DOCS_URL/tutorials/assets_pipeline/importing_images.html</link>
 	</tutorials>
 	<members>
+		<member name="basis_universal/rdo_dict_size" type="int" setter="" getter="" default="1024">
+			Specify the RDO dict size, ranges from 64 to 65536. Higher values increase memory consumption and reduce encoding speed, but give more compression.
```
[the remark this answers is not in the document]
Comment (beicause) [reply doc/classes/ResourceImporterLayeredTexture.xml]: This option has significant impact on the encoding speed.
4x larger dict size almost makes the encoding time 2-4x longer.

File: doc/classes/ResourceImporterLayeredTexture.xml (hunk 7 above)
Comment (beicause) [reply doc/classes/ResourceImporterLayeredTexture.xml]: Renamed as `uastc_level`, which looks less misleading.

File: doc/classes/ResourceImporterLayeredTexture.xml (hunk 8 above)
Comment (beicause) [reply doc/classes/ResourceImporterLayeredTexture.xml:29]: It is the same as the zstd compression level in other places, simply controlling the zstd compression.

**Comment by BlueCube3310** [comment]
The Basisu settings currently appear at all times in the import dock, they should only show up when the compression mode is set to "BasisUniversal":
basisusettings

File: doc/classes/ResourceImporterLayeredTexture.xml [hunk 10]
```diff
@@ -10,6 +10,25 @@
 		<link title="Importing images">$DOCS_URL/tutorials/assets_pipeline/importing_images.html</link>
 	</tutorials>
 	<members>
+		<member name="basis_universal/rdo_dict_size" type="int" setter="" getter="" default="1024">
+			The dictionary size for RDO, ranging from [code]64[/code] to [code]65536[/code]. Higher values reduce the file size further, but significantly reduce encoding speed.
```
Comment (Mickeon) [inline doc/classes/ResourceImporterLayeredTexture.xml:14]: Continuing from https://github.com/godotengine/godot/pull/105080#discussion_r2064610472

The "_but_" here doesn't make sense. A smaller file size and **shorter** encoding speed are both good things.
Judging by what you said in https://github.com/godotengine/godot/pull/105080#discussion_r2065455944 , this may be an error:
> This option has significant impact on the encoding speed.
4x larger dict size almost makes the encoding time 2-4x longer.
```suggestion
			The dictionary size for RDO, ranging from [code]64[/code] to [code]65536[/code]. Higher values reduce the file size further, but significantly increase encoding speed.
```

There may be a bit of confusion, so just so we're clear:
- "Increase encoding speed": Makes encoding **slower**. meaning encoding takes **more** time to compute.
- "Decrease encoding speed": Makes encoding **faster**, meaning encoding takes **less** time to compute.

**Review by Mickeon — COMMENTED** [review]
There may be some confusion regarding how encoding speed is documented.

File: doc/classes/ResourceImporterLayeredTexture.xml (hunk 10 above)
Comment (beicause) [reply doc/classes/ResourceImporterLayeredTexture.xml:14]: >The "but" here doesn't make sense. A smaller file size and shorter encoding speed are both good things.

I mean a larger dict size will make encoding slower, so it's a bad thing. Is there anything wrong with "but" ?

Comment (Mickeon) [reply doc/classes/ResourceImporterLayeredTexture.xml:14]: Yes, correct, **but** "reduce encoding speed" (as is in this PR) means it makes it faster.

Comment (beicause) [reply doc/classes/ResourceImporterLayeredTexture.xml:14]: Isn't it that “reduce encoding time" means it's faster? I thought "reduce encoding speed" should mean it's slower.

Comment (Mickeon) [reply doc/classes/ResourceImporterLayeredTexture.xml:14]: Okay, hold on. In that case it may be my bad. Let's ask the audience.

Comment (Calinou) [reply doc/classes/ResourceImporterLayeredTexture.xml:14]: I would say "makes encoding times longer" to be as explicit as possible.

**Comment by BlueCube3310** [comment]
Tested on Windows 10 desktop and web, it works as expected:
| Desktop | Web |
|-----------|------|
| desktop | web |

Each texture, including the lightmap and shadowmask, is compressed as BasisU. The exported .pck is 9mb with supercompression, and 17mb without. Better results can likely be achieved by tweaking the settings

**Comment by Calinou** [comment]
In terms of UX, this adds a lot of import options when Basis Universal is chosen as a compression mode. It makes the already lengthy texture import options even longer.

I'm thinking these should be project settings instead (like https://github.com/godotengine/godot/pull/104571 does). Are there situations where you want specific textures only to import faster, but still use VRAM compression (instead of lossless or uncompressed while you're iterating)?

*Maybe* the UASTC level could be configurable per-texture, but that's probably the extent where I'd allow per-texture configuration.

**Comment by beicause** [comment]
I might prefer to only remain the "uastc level" and "rdo quality loss" ( and automatically disable rdo when the rdo quality loss is approximately 0), as the other options have a relatively small impact and the default values are fine.

**Comment by BlueCube3310** [comment]
> > Maybe the UASTC level could be configurable per-texture, but that's probably the extent where I'd allow per-texture configuration.
> 
> UASTC level mainly controls the quality and has little impact on the size (Higher quality even slightly increases the file size).
> 
> I might prefer to only remain the "uastc level" and "rdo quality loss" in import options( and automatically disable rdo when the rdo quality loss is approximately 0), as the other options have a relatively small impact and the default values are fine.

I agree with this, the level of aggressiveness with which RDO affects different textures highly varies depending on their type. For example, normal maps are highly sensitive to RDO, while artifacts on diffuse or ORM are much less noticeable. RDO also has the biggest influence on the resulting file size, so it makes sense for it to be exposed per-texture

**Comment by BlueCube3310** [comment]
Could the `Basis Universal` settings be moved next to the `Compress` category? I think it would be more intuitive, since these options are related:

basisuproposal

File: doc/classes/ProjectSettings.xml [hunk 11]
```diff
@@ -3257,6 +3257,16 @@
 		<member name="rendering/shading/overrides/force_vertex_shading" type="bool" setter="" getter="" default="false">
 			If [code]true[/code], forces vertex shading for all rendering. This can increase performance a lot, but also reduces quality immensely. Can be used to optimize performance on low-end mobile devices.
 		</member>
+		<member name="rendering/textures/basis_universal/rdo_dict_size" type="int" setter="" getter="" default="1024">
+			The dictionary size for Rate-Distortion Optimization (RDO) when importing textures as basis universal and when RDO is enabled, ranging from [code]64[/code] to [code]65536[/code]. Higher values reduce the file sizes further, but significantly make encoding times longer.
```
Comment (BlueCube3310) [inline doc/classes/ProjectSettings.xml:3261]: This sounds more natural (I think)

```suggestion
			The dictionary size for Rate-Distortion Optimization (RDO) when importing textures as basis universal and when RDO is enabled, ranging from [code]64[/code] to [code]65536[/code]. Higher values reduce the file sizes further, but make encoding times significantly longer.
```

File: core/io/image.cpp [hunk 12]
```diff
@@ -104,7 +104,7 @@ void (*Image::_image_decompress_astc)(Image *) = nullptr;
 Vector<uint8_t> (*Image::webp_lossy_packer)(const Ref<Image> &, float) = nullptr;
 Vector<uint8_t> (*Image::webp_lossless_packer)(const Ref<Image> &) = nullptr;
 Vector<uint8_t> (*Image::png_packer)(const Ref<Image> &) = nullptr;
-Vector<uint8_t> (*Image::basis_universal_packer)(const Ref<Image> &, Image::UsedChannels) = nullptr;
+Vector<uint8_t> (*Image::basis_universal_packer)(const Ref<Image> &p_image, Image::UsedChannels p_channels, const BasisUniversalPackerParams &p_basisu_params) = nullptr;
```
Comment (BlueCube3310) [inline core/io/image.cpp:107]: Since the rest of the function prototypes here don't use parameter names, I'd prefer to leave them as they are.

```suggestion
Vector<uint8_t> (*Image::basis_universal_packer)(const Ref<Image> &, Image::UsedChannels, const BasisUniversalPackerParams &) = nullptr;
```

File: core/io/image.h [hunk 13]
```diff
@@ -231,7 +236,7 @@ class Image : public Resource {
 	static Vector<uint8_t> (*webp_lossy_packer)(const Ref<Image> &p_image, float p_quality);
 	static Vector<uint8_t> (*webp_lossless_packer)(const Ref<Image> &p_image);
 	static Vector<uint8_t> (*png_packer)(const Ref<Image> &p_image);
-	static Vector<uint8_t> (*basis_universal_packer)(const Ref<Image> &p_image, UsedChannels p_channels);
+	static Vector<uint8_t> (*basis_universal_packer)(const Ref<Image> &p_image, Image::UsedChannels p_channels, const BasisUniversalPackerParams &p_basisu_params);
```
Comment (BlueCube3310) [inline core/io/image.h:239]:
```suggestion
	static Vector<uint8_t> (*basis_universal_packer)(const Ref<Image> &p_image, UsedChannels p_channels, const BasisUniversalPackerParams &p_basisu_params);
```

File: editor/import/resource_importer_layered_texture.cpp [hunk 14]
```diff
@@ -375,6 +384,13 @@ Error ResourceImporterLayeredTexture::import(ResourceUID::ID p_source_id, const
 			slices.push_back(slice);
 		}
 	}
+
+	const Image::BasisUniversalPackerParams basisu_params = {
+		p_options["compress/uastc_level"],
+		p_options["compress/rdo_quality_loss"],
+
+	};
```
Comment (BlueCube3310) [inline editor/import/resource_importer_layered_texture.cpp:392]:
```suggestion
		p_options["compress/uastc_level"],
		p_options["compress/rdo_quality_loss"],
	};
```

File: editor/import/resource_importer_texture.cpp [hunk 15]
```diff
@@ -508,6 +516,12 @@ Error ResourceImporterTexture::import(ResourceUID::ID p_source_id, const String
 	const bool hdr_clamp_exposure = p_options["process/hdr_clamp_exposure"];
 	int size_limit = p_options["process/size_limit"];
 
+	const Image::BasisUniversalPackerParams basisu_params = {
+		p_options["compress/uastc_level"],
+		p_options["compress/rdo_quality_loss"],
+
+	};
```
Comment (BlueCube3310) [inline editor/import/resource_importer_texture.cpp:523]:
```suggestion
	const Image::BasisUniversalPackerParams basisu_params = {
		p_options["compress/uastc_level"],
		p_options["compress/rdo_quality_loss"],
	};
```

File: editor/import/resource_importer_texture.cpp [hunk 16]
```diff
@@ -699,8 +713,7 @@ Error ResourceImporterTexture::import(ResourceUID::ID p_source_id, const String
 					image_compress_format = "s3tc";
 				}
 
-				_save_ctex(image, p_save_path + "." + image_compress_format + ".ctex", compress_mode, lossy, image_compress_mode, mipmaps, stream, detect_3d,
-						detect_roughness, detect_normal, force_normal, srgb_friendly_pack, false, mipmap_limit, normal_image, roughness_channel);
+				_save_ctex(image, p_save_path + "." + image_compress_format + ".ctex", compress_mode, lossy, basisu_params, image_compress_mode, mipmaps, stream, detect_3d, detect_roughness, detect_normal, force_normal, srgb_friendly_pack, false, mipmap_limit, normal_image, roughness_channel);
```
Comment (BlueCube3310) [inline editor/import/resource_importer_texture.cpp:716]: Makes it slightly easier to read

```suggestion
				_save_ctex(image, p_save_path + "." + image_compress_format + ".ctex", compress_mode, lossy, basisu_params, image_compress_mode, mipmaps, 
				stream, detect_3d, detect_roughness, detect_normal, force_normal, srgb_friendly_pack, false, mipmap_limit, normal_image, roughness_channel);
```

**Review by BlueCube3310 — COMMENTED** [review]
Tested on Android, it works as expected. Textures are properly compressed and transcoded to ETC2/ASTC formats

**Review by BlueCube3310 — APPROVED** [review]
Looks great!

File: doc/classes/ProjectSettings.xml [hunk 17]
```diff
@@ -3257,6 +3257,16 @@
...
 		</member>
+		<member name="rendering/textures/basis_universal/rdo_dict_size" type="int" setter="" getter="" default="1024">
+			The dictionary size for Rate-Distortion Optimization (RDO) when importing textures as basis universal and when RDO is enabled, ranging from [code]64[/code] to [code]65536[/code]. Higher values reduce the file sizes further, but make encoding times significantly longer.
+		</member>
+		<member name="rendering/textures/basis_universal/zstd_supercompression" type="bool" setter="" getter="" default="true">
+			If [code]true[/code], enables Zstandard supercompression to reduce file size when importing textures as basis universal.
+			[b]Note:[/b] Basis Universal textures need to be compressed to gain the benefit of smaller file sizes, otherwise they are as large as VRAM-compressed textures.
+		</member>
+		<member name="rendering/textures/basis_universal/zstd_supercompression_level" type="int" setter="" getter="" default="6">
+			Specify the compression level for basis universal zstd supercompression, ranging from [code]1[/code] to [code]22[/code].
```
Comment (akien-mga) [inline doc/classes/ProjectSettings.xml:3268]:
```suggestion
			Specify the compression level for Basis Universal Zstandard supercompression, ranging from [code]1[/code] to [code]22[/code].
```

File: modules/basis_universal/register_types.cpp [hunk 18]
```diff
@@ -30,6 +30,7 @@
 
 #include "register_types.h"
 
+#include "core/config/project_settings.h"
 #include "image_compress_basisu.h"
```
Comment (akien-mga) [inline modules/basis_universal/register_types.cpp:34]: In modules we keep the local module includes separate from the "absolute" common Godot headers.
```suggestion
#include "image_compress_basisu.h"

#include "core/config/project_settings.h"
```

**Comment by Repiteo** [comment]
Thanks!
