### PR TITLE
Fix listing files inside directory in pack file

### LINKED ISSUE #15801: can't find or open a directory on a standalone build
**Godot version:**
Godot RC1

**OS/device including version:**
Windows 10 x64

**Issue description:**
locating / opening a directory works in the editor but once you create a standalone build the engine seems to not know where the directory is. finding and loading a specific file in said directory works but 
if you can find a file why not the directory the file is located in?

**Steps to reproduce:**
using something like directory_exists( path-to_directory) returns false on a standalone build, while it will work in the editor.

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by RandomShaper**
When adding a directory path to the inventory of the pack, an empty file name was being added to the file list. That made `Directory.get_next()` signal end-of-list too early so that files in a subdirectory were missed.

Fixes #15801.
Helps with #16798.

### CODE REVIEW

File: core/io/file_access_pack.cpp [hunk 1]
```diff
@@ -88,7 +88,11 @@ void PackedData::add_path(const String &pkg_path, const String &path, uint64_t o
 				}
 			}
 		}
-		cd->files.insert(path.get_file());
+		String filename = path.get_file();
+		// Don't add as a file if the path points to a directoryy
```
Comment (neikeq) [inline core/io/file_access_pack.cpp]: typoo in directoryy

Comment (RandomShaper) [reply core/io/file_access_pack.cpp]: Oops. Well, it's already merged. I guess it's not as serious as to revert it. Some day someone will touch this file again and have the chance of fixing it.

Comment (akien-mga) [reply core/io/file_access_pack.cpp]: > I guess it's not as serious as to revert it.

Heh, I had seen it but chose to ignore it, didn't want to wait for a commit amend :)
`codespell` will fix it eventually.

**Comment by hpvb** [comment]
Cherry picked into 3.0.3
