### PR TITLE
Fix same project opening mutliple times from project manager

### LINKED ISSUE #58723: Project can be opened multiple times from Project Manager
### Godot version

3f69ea4

### System information

W10

### Issue description

When you double click a project on project list, it opens the project. But if you keep clicking it until project manager closes, it will spawn multiple instances of the editor.

If the project is starting, further clicks should have no effect.

### Steps to reproduce

1. Open Project Manager
2. Click a project on the list
3. Click it
4. Click again
5. Click
6. Click
7. Keep clicking

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by techiepriyansh**
Fixes #58723

### CODE REVIEW

File: editor/project_manager.cpp [hunk 1]
```diff
@@ -1818,8 +1820,9 @@ void ProjectList::_panel_input(const Ref<InputEvent> &p_ev, Node *p_hb) {
 
 		emit_signal(SNAME(SIGNAL_SELECTION_CHANGED));
 
-		if (!mb->is_ctrl_pressed() && mb->is_double_click()) {
+		if (!mb->is_ctrl_pressed() && mb->is_double_click() && !_project_opening_initiated) {
```
Comment (Calinou) [inline editor/project_manager.cpp:1823]: Since it's not immediately obvious as to why this is done, there should be a comment:

```suggestion
		// Do not allow opening a project more than once using a single project manager instance.
		// Opening the same project in several editor instances at once can lead to various issues.
		if (!mb->is_ctrl_pressed() && mb->is_double_click() && !_project_opening_initiated) {
```

Comment (techiepriyansh) [reply editor/project_manager.cpp:1825]: Thanks for the suggestion! I've added the comment now.

**Comment by KoBeWi** [comment]
This makes Project Manager unusable if opening the project fails. `_open_selected_projects_ask()` has a few `return` statements.

**Comment by techiepriyansh** [comment]
The only way I could think of to resolve this would be to add a bunch of `_project_opening_initiated = false` statements before some of the `return` statements in `open_selected_projects_ask()` and `open_selected_projects()`. Should I go with this, or is there any better approach?

**Comment by KoBeWi** [comment]
> Should I go with this, or is there any better approach?

You could set `_project_opening_initiated` when the project is really going to start. But if it won't work, the approach you mentioned is ok too.

**Comment by techiepriyansh** [comment]
> You could set _project_opening_initiated when the project is really going to start.

Managed to do it this way

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by KoBeWi** [comment]
I'm seeing this issue in 3.5 beta2. Not sure if regression, but this could be worth cherry-picking.

**Comment by techiepriyansh** [comment]
Made the cherry-picking PR: #59576.
