### PR TITLE
Split `RenderingDevice` into API-agnostic and `RenderingDeviceDriver` parts

### LINKED ISSUE #86106: [D3D12] Segfault when importing GDQuest Third Person Controller demo
### Tested versions

- New in 4.3.dev (41365c6c8ba357a490ed924a128958240f3ccf04) which is the first version with D3D 12 support.

### System information

Windows 10 - D3D12 (Forward+) - dedicated Radeon RX Vega (Advanced Micro Devices, Inc.) - AMD Ryzen 7 2700 Eight-Core Processor (16 Threads)

### Issue description

While testing #70315 yesterday, I ran into a segfault when trying to open the [GDQuest Third Person Controller demo](https://github.com/gdquest-demos/godot-4-3d-third-person-controller) with D3D12 in the editor. It seems to crash during import of some scenes.

My build was made without debug symbols so the stacktrace isn't useful. I'm not sure if I'll have time to debug further before going on holiday, so anyone interested can try to reproduce and post a stacktrace with debug symbols.

```
$ ./bin/godot.windows.editor.x86_64.console.exe
Godot Engine v4.3.dev.custom_build.f60b64765 - https://godotengine.org
OpenGL API 3.3.0 Core Profile Context 23.11.1.231017 - Compatibility - Using Dev
ice: ATI Technologies Inc. - Radeon RX Vega

Editing project: D:/Dev/Godot/Projects/godot-4-3d-third-person-controller
Godot Engine v4.3.dev.custom_build.f60b64765 - https://godotengine.org
D3D12 feature level 12_0 - Forward+ - Using D3D12 Adapter #0: Radeon RX Vega

WARNING: Blend file import is enabled in the project settings, but no Blender pa
th is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (.\modules/gltf/register_types.cpp:63)
ERROR: Condition "!preset.is_valid()" is true. Continuing.
   at: EditorExport::load_config (.\editor/export/editor_export.cpp:225)
ERROR: Couldn't open MTL file 'res://Environment/grass/grass_1_geo.mtl', it may
not exist or not be readable.
   at: (.\editor/import/resource_importer_obj.cpp:48)
WARNING: Ignoring face with non-finite normal in LOD generation.
     at: ImporterMesh::generate_lods (.\scene/resources/importer_mesh.cpp:518)
ERROR: Command list Reset failed with error 0x80070057.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:9023)
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:3042)
ERROR: Condition "data.size() == 0" is true. Returning: Ref<Image>()
   at: RendererRD::TextureStorage::texture_2d_get (.\servers/rendering/renderer_
rd/storage_rd/texture_storage.cpp:1272)
ERROR: CreateResource failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:2242)
ERROR: Condition "texture.rd_texture.is_null()" is true.
   at: RendererRD::TextureStorage::texture_2d_initialize (.\servers/rendering/re
nderer_rd/storage_rd/texture_storage.cpp:841)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_size_override (.\servers/renderin
g/renderer_rd/storage_rd/texture_storage.cpp:1407)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_path (.\servers/rendering/rendere
r_rd/storage_rd/texture_storage.cpp:1416)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_detect_3d_callback (.\servers/ren
dering/renderer_rd/storage_rd/texture_storage.cpp:1437)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_detect_roughness_callback (.\serv
ers/rendering/renderer_rd/storage_rd/texture_storage.cpp:1453)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_detect_normal_callback (.\servers
/rendering/renderer_rd/storage_rd/texture_storage.cpp:1445)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_path (.\servers/rendering/rendere
r_rd/storage_rd/texture_storage.cpp:1416)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_2d_get (.\servers/rendering/renderer_
rd/storage_rd/texture_storage.cpp:1264)
ERROR: CreateResource failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:2242)
ERROR: Condition "texture.rd_texture.is_null()" is true.
   at: RendererRD::TextureStorage::texture_2d_initialize (.\servers/rendering/re
nderer_rd/storage_rd/texture_storage.cpp:841)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_size_override (.\servers/renderin
g/renderer_rd/storage_rd/texture_storage.cpp:1407)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_path (.\servers/rendering/rendere
r_rd/storage_rd/texture_storage.cpp:1416)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_detect_3d_callback (.\servers/ren
dering/renderer_rd/storage_rd/texture_storage.cpp:1437)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_detect_roughness_callback (.\serv
ers/rendering/renderer_rd/storage_rd/texture_storage.cpp:1453)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_detect_normal_callback (.\servers
/rendering/renderer_rd/storage_rd/texture_storage.cpp:1445)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_path (.\servers/rendering/rendere
r_rd/storage_rd/texture_storage.cpp:1416)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_2d_get (.\servers/rendering/renderer_
rd/storage_rd/texture_storage.cpp:1264)
ERROR: CreateResource failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:2242)
ERROR: Condition "texture.rd_texture.is_null()" is true.
   at: RendererRD::TextureStorage::texture_2d_initialize (.\servers/rendering/re
nderer_rd/storage_rd/texture_storage.cpp:841)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_size_override (.\servers/renderin
g/renderer_rd/storage_rd/texture_storage.cpp:1407)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_path (.\servers/rendering/rendere
r_rd/storage_rd/texture_storage.cpp:1416)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_detect_3d_callback (.\servers/ren
dering/renderer_rd/storage_rd/texture_storage.cpp:1437)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_detect_roughness_callback (.\serv
ers/rendering/renderer_rd/storage_rd/texture_storage.cpp:1453)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_detect_normal_callback (.\servers
/rendering/renderer_rd/storage_rd/texture_storage.cpp:1445)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_path (.\servers/rendering/rendere
r_rd/storage_rd/texture_storage.cpp:1416)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_2d_get (.\servers/rendering/renderer_
rd/storage_rd/texture_storage.cpp:1264)
ERROR: CreateResource failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:2242)
ERROR: Condition "texture.rd_texture.is_null()" is true.
   at: RendererRD::TextureStorage::texture_2d_initialize (.\servers/rendering/re
nderer_rd/storage_rd/texture_storage.cpp:841)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_size_override (.\servers/renderin
g/renderer_rd/storage_rd/texture_storage.cpp:1407)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_path (.\servers/rendering/rendere
r_rd/storage_rd/texture_storage.cpp:1416)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_detect_3d_callback (.\servers/ren
dering/renderer_rd/storage_rd/texture_storage.cpp:1437)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_detect_roughness_callback (.\serv
ers/rendering/renderer_rd/storage_rd/texture_storage.cpp:1453)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_detect_normal_callback (.\servers
/rendering/renderer_rd/storage_rd/texture_storage.cpp:1445)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_set_path (.\servers/rendering/rendere
r_rd/storage_rd/texture_storage.cpp:1416)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "tex" is null.
   at: RendererRD::TextureStorage::texture_2d_get (.\servers/rendering/renderer_
rd/storage_rd/texture_storage.cpp:1264)
ERROR: Attempting to use an uninitialized RID
   at: (.\core/templates/rid_owner.h:199)
ERROR: Parameter "t" is null.
   at: RendererRD::TextureStorage::texture_free (.\servers/rendering/renderer_rd
/storage_rd/texture_storage.cpp:767)
ERROR: Can't create buffer of size: 432, error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1694)
ERROR: Condition "err != OK" is true. Returning: RID()
   at: RenderingDeviceD3D12::vertex_buffer_create (drivers\d3d12\rendering_devic
e_d3d12.cpp:4039)
ERROR: Can't create buffer of size: 144, error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1694)
ERROR: Condition "err != OK" is true. Returning: RID()
   at: RenderingDeviceD3D12::vertex_buffer_create (drivers\d3d12\rendering_devic
e_d3d12.cpp:4039)
ERROR: Can't create buffer of size: 192, error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1694)
ERROR: Condition "err != OK" is true. Returning: RID()
   at: RenderingDeviceD3D12::index_buffer_create (drivers\d3d12\rendering_device
_d3d12.cpp:4213)
ERROR: Condition "!index_buffer_owner.owns(p_index_buffer)" is true. Returning:
RID()
   at: RenderingDeviceD3D12::index_array_create (drivers\d3d12\rendering_device_
d3d12.cpp:4230)
ERROR: Can't create buffer of size: 204, error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1694)
ERROR: Condition "err != OK" is true. Returning: RID()
   at: RenderingDeviceD3D12::vertex_buffer_create (drivers\d3d12\rendering_devic
e_d3d12.cpp:4039)
ERROR: Can't create buffer of size: 68, error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1694)
ERROR: Condition "err != OK" is true. Returning: RID()
   at: RenderingDeviceD3D12::vertex_buffer_create (drivers\d3d12\rendering_devic
e_d3d12.cpp:4039)
ERROR: Can't create buffer of size: 144, error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1694)
ERROR: Condition "err != OK" is true. Returning: RID()
   at: RenderingDeviceD3D12::index_buffer_create (drivers\d3d12\rendering_device
_d3d12.cpp:4213)
ERROR: Condition "!index_buffer_owner.owns(p_index_buffer)" is true. Returning:
RID()
   at: RenderingDeviceD3D12::index_array_create (drivers\d3d12\rendering_device_
d3d12.cpp:4230)
ERROR: Can't create buffer of size: 72, error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1694)
ERROR: Condition "err != OK" is true. Returning: RID()
   at: RenderingDeviceD3D12::index_buffer_create (drivers\d3d12\rendering_device
_d3d12.cpp:4213)
ERROR: Condition "!index_buffer_owner.owns(p_index_buffer)" is true. Returning:
RID()
   at: RenderingDeviceD3D12::index_array_create (drivers\d3d12\rendering_device_
d3d12.cpp:4230)
ERROR: Can't create buffer of size: 36, error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1694)
ERROR: Condition "err != OK" is true. Returning: RID()
   at: RenderingDeviceD3D12::index_buffer_create (drivers\d3d12\rendering_device
_d3d12.cpp:4213)
ERROR: Condition "!index_buffer_owner.owns(p_index_buffer)" is true. Returning:
RID()
   at: RenderingDeviceD3D12::index_array_create (drivers\d3d12\rendering_device_
d3d12.cpp:4230)
ERROR: Can't create buffer of size: 288, error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1694)
ERROR: Condition "err != OK" is true. Returning: RID()
   at: RenderingDeviceD3D12::vertex_buffer_create (drivers\d3d12\rendering_devic
e_d3d12.cpp:4039)
ERROR: Can't create buffer of size: 192, error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1694)
ERROR: Condition "err != OK" is true. Returning: RID()
   at: RenderingDeviceD3D12::index_buffer_create (drivers\d3d12\rendering_device
_d3d12.cpp:4213)
ERROR: Condition "!index_buffer_owner.owns(p_index_buffer)" is true. Returning:
RID()
   at: RenderingDeviceD3D12::index_array_create (drivers\d3d12\rendering_device_
d3d12.cpp:4230)
ERROR: Can't create buffer of size: 136, error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1694)
ERROR: Condition "err != OK" is true. Returning: RID()
   at: RenderingDeviceD3D12::vertex_buffer_create (drivers\d3d12\rendering_devic
e_d3d12.cpp:4039)
ERROR: Can't create buffer of size: 144, error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1694)
ERROR: Condition "err != OK" is true. Returning: RID()
   at: RenderingDeviceD3D12::index_buffer_create (drivers\d3d12\rendering_device
_d3d12.cpp:4213)
ERROR: Condition "!index_buffer_owner.owns(p_index_buffer)" is true. Returning:
RID()
   at: RenderingDeviceD3D12::index_array_create (drivers\d3d12\rendering_device_
d3d12.cpp:4230)
ERROR: Can't create buffer of size: 72, error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1694)
ERROR: Condition "err != OK" is true. Returning: RID()
   at: RenderingDeviceD3D12::index_buffer_create (drivers\d3d12\rendering_device
_d3d12.cpp:4213)
ERROR: Condition "!index_buffer_owner.owns(p_index_buffer)" is true. Returning:
RID()
   at: RenderingDeviceD3D12::index_array_create (drivers\d3d12\rendering_device_
d3d12.cpp:4230)
ERROR: Can't create buffer of size: 36, error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1694)
ERROR: Condition "err != OK" is true. Returning: RID()
   at: RenderingDeviceD3D12::index_buffer_create (drivers\d3d12\rendering_device
_d3d12.cpp:4213)
ERROR: Condition "!index_buffer_owner.owns(p_index_buffer)" is true. Returning:
RID()
   at: RenderingDeviceD3D12::index_array_create (drivers\d3d12\rendering_device_
d3d12.cpp:4230)
ERROR: Condition "res" is true. Returning: ERR_UNAVAILABLE
   at: D3D12Context::_update_swap_chain (drivers\d3d12\d3d12_context.cpp:742)
ERROR: CreateRootSignature failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:5236)
ERROR: Parameter "p_version->variants" is null.
   at: ShaderRD::_allocate_placeholders (.\servers/rendering/renderer_rd/shader_
rd.cpp:483)
ERROR: Parameter "p_version->variants" is null.
   at: ShaderRD::_allocate_placeholders (.\servers/rendering/renderer_rd/shader_
rd.cpp:483)
ERROR: Parameter "p_version->variants" is null.
   at: ShaderRD::_allocate_placeholders (.\servers/rendering/renderer_rd/shader_
rd.cpp:483)
ERROR: Condition "!shader_singleton->shader.version_is_valid(version)" is true.
   at: RendererSceneRenderImplementation::SceneShaderForwardClustered::ShaderDat
a::set_code (servers\rendering\renderer_rd\forward_clustered\scene_shader_forwar
d_clustered.cpp:181)
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1903)
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1903)
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1903)
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1903)
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1903)
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1903)
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1903)
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1903)
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1903)
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1903)
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1903)
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1903)
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1903)
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1903)
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1903)
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1903)
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1903)
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1903)
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1903)
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1903)
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_d3d12.cpp:1903)

================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.3.dev.custom_build (f60b64765c52d043a1fc2405af5b
375d22864914)
Dumping the backtrace. Please include this when reporting the bug to the project
 developer.
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] <couldn't map PC to fn name>
[4] <couldn't map PC to fn name>
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] <couldn't map PC to fn name>
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
[13] <couldn't map PC to fn name>
[14] <couldn't map PC to fn name>
[15] <couldn't map PC to fn name>
[16] <couldn't map PC to fn name>
[17] <couldn't map PC to fn name>
[18] <couldn't map PC to fn name>
[19] <couldn't map PC to fn name>
[20] <couldn't map PC to fn name>
[21] <couldn't map PC to fn name>
[22] <couldn't map PC to fn name>
[23] <couldn't map PC to fn name>
[24] <couldn't map PC to fn name>
[25] <couldn't map PC to fn name>
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

- Clone https://github.com/gdquest-demos/godot-4-3d-third-person-controller
- Edit it once with Vulkan to change the RD rendering driver for Windows to `d3d12` (or change it by modifying `project.godot` directly)
- Close, and delete `.godot` folder to start fresh
- Edit it with a 4.3.dev build with D3D12 support -> crash

### Minimal reproduction project (MRP)

https://github.com/gdquest-demos/godot-4-3d-third-person-controller

### PR DESCRIPTION
**Pull request by RandomShaper**
A huge chunk of `RenderingDeviceVulkan` is API-agnostic bookkeeping, validation, etc. Such code is also shared with others, like `RenderingDeviceD3D12`. This PR keeps a single, non-abstract `RenderingDevice` with all those API-agnostic elements and moves all the API-specific parts to a thin wrapper around the driver, which is `RenderingDeviceDriver` for Vulkan. This makes much easier to write additional rendering drivers, by allowing one to focus on the API-specific stuff. In some cases that will require modifying the interface between `RD` and `RDD`, which is not exposed to the user.

Other relevant points:
- A common context interface has been extracted from `VulkanContext` (`APIContextRD`) with the bare minimum set of services `RenderingDevice` and direct usage needs. (The specific `RenderingDeviceDriver`s have access to the specific context implementation, which open doors for them to a much richer, but non-standard, API.) **UPDATE:** Now Direct3D 12 has been merged, it gets similar love in this PR.
- There are important notes on design choice in the code. Future maintainers, please follow or discuss, but don't break consistency.
- Every struct involved now have default initializers, both in `RenderingDevice` and `RenderingDeviceDriver`.
- Some of the wiring between context and `RD` has been enhanced so now you can instantiate a `RenderingDevice` even when Godot is running in compatibility mode (this will allow to have a `RD`-based lightmapper available in a GL compatibility project). This piece of code shows how to ensure you have a usable local `RenderingDevice` in any circumstances:
   ```C++
   RD *orig_rd_singleton = RD::get_singleton();

   ApiContextRD *vc = nullptr;
   if (GLOBAL_GET("rendering/renderer/rendering_method") == "gl_compatibility") {
   #ifdef VULKAN_ENABLED
   	if (GLOBAL_GET("rendering/rendering_device/driver") == "vulkan") {
   		vc = memnew(VulkanContext);
	}
   #endif
   	CRASH_COND_MSG(!vc, "No RD driver available.");
   	vc->initialize();
   } else {
   	vc = RD::get_singleton()->get_context();
   }

   RenderingDevice *rd = memnew(RenderingDevice);
   if (GLOBAL_GET("rendering/renderer/rendering_method") == "gl_compatibility") {
   	DEV_ASSERT(RD::get_singleton() == rd);
   }
   rd->initialize(vc, true);
   // Do stuff with RD here.
   memdelete(rd);

   if (GLOBAL_GET("rendering/renderer/rendering_method") == "gl_compatibility") {
    	memdelete(vc);
   }
   DEV_ASSERT(RD::get_singleton() == orig_rd_singleton);
   ```
- Deprecations: `RD::texture_get_native_handle()` (superfluous) and `DRIVER_RESOURCE_VULKAN_*` (replaced by API-agnostic).

~This includes a couple of merged (commits will go away once rebased) and unmerged (#82797) PRs.~

TODO:
- [X] Finish debugging and fix a few known issues.
- [X] Rebase on top of the lastest `master`.
- [X] Fix ligthmapper (local device?).
- [X] D3D12: Adapt to this new infrastucture. **2023-12-11:** The PR now includes #70315, which is then adapted to the new model.
- [X] Debug
- [X] Remove the interim change-tracking-assistance commit.
- [X] Ensure #86106 is fixed.

_Production edit: closes godotengine/godot-roadmap#31_

### CODE REVIEW

File: servers/rendering/rendering_device.h [hunk 1]
```diff
@@ -50,56 +58,16 @@ class RDPipelineColorBlendState;
 class RDFramebufferPass;
 class RDPipelineSpecializationConstant;
 
-class RenderingDevice : public Object {
+class RenderingDevice : public Object, public RenderingDeviceCommons {
```
Comment (reduz) [inline servers/rendering/rendering_device.h:61]: This is probably not going to work (or not warranted to work) with Godot binding system because depending on the implementation of multiple inheritance, the compiler will do offset adjustments to the pointer when casting, which breaks Godot type system.

This is why I originally suggested doing this different.

Comment (reduz) [reply servers/rendering/rendering_device.h:61]: Alternatively you could make RenderingDeviceCommons inherit from object and simply not registering RenderingDeviceDriver to the binding system (no GDCLASS) that should work fine.

**Review by reduz — CHANGES_REQUESTED** [review]

File: servers/rendering/renderer_rd/api_context_rd.h [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+	virtual int get_swapchain_image_count() const = 0;
+
+	virtual int window_get_width(DisplayServer::WindowID p_window = 0) = 0;
+	virtual int window_get_height(DisplayServer::WindowID p_window = 0) = 0;
+	virtual bool window_is_valid_swapchain(DisplayServer::WindowID p_window = 0) = 0;
+	virtual RDD::RenderPassID window_get_render_pass(DisplayServer::WindowID p_window = 0) = 0;
+	virtual RDD::FramebufferID window_get_framebuffer(DisplayServer::WindowID p_window = 0) = 0;
+
+	virtual RID local_device_create() = 0;
+	virtual void local_device_push_command_buffers(RID p_local_device, const RDD::CommandBufferID *p_buffers, int p_count) = 0;
```
Comment (reduz) [inline servers/rendering/renderer_rd/api_context_rd.h:51]: This will probably need to be changed for the acyclic graph, exposing queues and synchronization primitives.

**Comment by reduz** [comment]
Looks fantastic!

File: servers/rendering/renderer_rd/api_context_rd.h (hunk 2 above)
Comment (RandomShaper) [reply servers/rendering/renderer_rd/api_context_rd.h:51]: For now, I've chosen to alter the design of the context class as little as possible to keep the scope of the work under control for this first big iteration, but I won't deny future maintainers will need to make this more flexible (probably exposing from the driver).

File: servers/rendering/rendering_device_driver.h [hunk 3]
```diff
@@ -0,0 +1,619 @@
...
+		AttachmentLoadOp load_op = ATTACHMENT_LOAD_OP_LOAD;
+		AttachmentStoreOp store_op = ATTACHMENT_STORE_OP_STORE;
+		AttachmentLoadOp stencil_load_op = ATTACHMENT_LOAD_OP_LOAD;
+		AttachmentStoreOp stencil_store_op = ATTACHMENT_STORE_OP_STORE;
+		TextureLayout initial_layout = TEXTURE_LAYOUT_UNDEFINED;
+		TextureLayout final_layout = TEXTURE_LAYOUT_UNDEFINED;
+	};
+
+	struct AttachmentReference {
+		static const uint32_t UNUSED = 0xffffffff;
```
Comment (DarioSamo) [inline servers/rendering/rendering_device_driver.h:451]: This constant seems like it'd be better off defined at the global level, as the code below uses this same constant but without a name.

File: servers/rendering/rendering_device_driver.h [hunk 4]
```diff
@@ -0,0 +1,619 @@
...
+		RenderPassClearValue value;
+	};
+
+	struct AttachmentClearRect {
+		Rect2i rect;
+		uint32_t base_layer = 0xffffffff;
+		uint32_t layer_count = 0xffffffff;
+	};
+
+	virtual void command_begin_render_pass(CommandBufferID p_cmd_buffer, RenderPassID p_render_pass, FramebufferID p_framebuffer, CommandBufferType p_cmd_buffer_type, const Rect2i &p_rect, VectorView<RenderPassClearValue> p_clear_values) = 0;
```
Comment (DarioSamo) [inline servers/rendering/rendering_device_driver.h:500]: Minor nitpick, what's the benefit of CommandBufferType being specified here? Shouldn't we be able to derive it from the command buffer itself? Is it a validation measure?

File: servers/rendering/rendering_device_driver.h [hunk 5]
```diff
@@ -0,0 +1,619 @@
...
+
+	// Commands.
+	virtual void command_timestamp_query_pool_reset(CommandBufferID p_cmd_buffer, QueryPoolID p_pool_id, uint32_t p_query_count) = 0;
+	virtual void command_timestamp_write(CommandBufferID p_cmd_buffer, QueryPoolID p_pool_id, uint32_t p_index) = 0;
+
+	/****************/
+	/**** SCREEN ****/
+	/****************/
+
+	virtual DataFormat screen_get_format() = 0;
```
Comment (DarioSamo) [inline servers/rendering/rendering_device_driver.h:582]: This is a weird concept, as there's nothing exposed about how swap chains work or for what device they're currently associated to. You don't exactly tie a 'driver/device' to a single screen either. Probably one of those quirks we need to work on when Vulkan Context is re-evaluated.

**Comment by DarioSamo** [comment]
I'll be leaving feedback in general here and on a per-line basis if necessary. Some of my comments are just criticizing a few design carry-overs from the current design and aren't necessarily related to this PR being approved or not, it just feels like the right time to bring these points up.

### Type Safety

I already brought this up over DMs, but there's currently no type safety system for the IDs returned by RDD. Using the uint64_t's directly means we can mix and match arguments around and the compile won't indicate the error. We can solve this in a few ways.

**A)** Every type returned gets a struct that wraps around the uint64_t. A very minor change that guarantees the types can't be mixed together.
```
struct FramebufferID {
  uint64_t handle;
};
```

**B)** Every type returned is a pointer to an interface that the backend has to inherit. This requires more work but since these handles are already pointers (they're not references you can indefinitely hold) in disguise, there's not much of a downside to it. The major advantage is that debuggers can access these types natively and display their contents.
```
struct Framebuffer {
  // Empty interface.
};

virtual Framebuffer *framebuffer_create() = 0;
virtual void framebuffer_free(Framebuffer *p_framebuffer) = 0;
```
```
struct FramebufferVK : Framebuffer {
  VkFramebuffer fb = VK_NULL_HANDLE;
}
```
Another benefit to consider is const-correctness can be implemented into the pointer types and will therefore be directly indicated by the API whether the object's internals should be modifiable or not.

### Vertex Formats

There seems to be currently a forced correlation between bindings and attributes, meaning that attributes that share the same buffer can't share the same binding (e.g. if 10 elements are bound to the same buffer, they each get their own binding instead of using the same one). I'm not familiar if this has potential performance implications, but it's worth investigating if this is correct.

This is not new to this PR, as it was pretty much directly copied as is from the current Vulkan RD.

### Command Queues

Command queues are not directly exposed but managed by the backend, meaning RenderingDevice has no control whatsoever on where commands are executed, on what type of queue and when exactly. This could prove to be very useful in the feature as a lot of the logic around managing command queues should be common to most backends and it takes off some responsibility for the backend maintainer. I think we could address this in this PR and move most of the logic that Vulkan Context currently handles to RD instead.

I'll do a separate comment for concerns about D3D12 compatibility in the future.

File: servers/rendering/rendering_device.h (hunk 1 above)
Comment (RandomShaper) [reply servers/rendering/rendering_device.h:61]: I'll do just that in the next push.

File: servers/rendering/rendering_device_driver.h [hunk 6]
```diff
@@ -0,0 +1,619 @@
...
+		BUFFER_USAGE_INDIRECT_BIT = (1 << 8),
+	};
+
+	virtual BufferID buffer_create(uint64_t p_size, BitField<BufferUsageBits> p_usage, MemoryAllocationType p_allocation_type) = 0;
+	// Only for a buffer with BUFFER_USAGE_TEXEL_BIT.
+	virtual bool buffer_set_texel_format(BufferID p_buffer, DataFormat p_format) = 0;
+	virtual void buffer_free(BufferID p_buffer) = 0;
+	virtual uint64_t buffer_get_allocation_size(BufferID p_buffer) = 0;
+	virtual uint8_t *buffer_map(BufferID p_buffer) = 0;
+	virtual void buffer_unmap(BufferID p_buffer) = 0;
```
[the remark this answers is not in the document]
Comment (reduz) [reply servers/rendering/rendering_device_driver.h:148]: Probably better to keep it simple, I don't think its needed.

File: servers/rendering/rendering_device_driver.h [hunk 7]
```diff
@@ -0,0 +1,619 @@
...
+	virtual FramebufferID framebuffer_create(RenderPassID p_render_pass, VectorView<TextureID> p_attachments, uint32_t p_width, uint32_t p_height) = 0;
+	virtual void framebuffer_free(FramebufferID p_framebuffer) = 0;
+
+	/****************/
+	/**** SHADER ****/
+	/****************/
+
+	virtual String shader_get_binary_cache_key() = 0;
+	virtual Vector<uint8_t> shader_compile_binary_from_spirv(VectorView<ShaderStageSPIRVData> p_spirv, const ShaderReflection &p_shader_refl, const String &p_shader_name) = 0;
+	virtual ShaderID shader_create_from_bytecode(const Vector<uint8_t> &p_shader_binary, ShaderDescription &r_shader_desc, String &r_name) = 0;
```
[the remark this answers is not in the document]
Comment (reduz) [reply servers/rendering/rendering_device_driver.h:346]: Binary is implementation dependent. If you use Vulkan its likely still SPIRV, but if you use D3D12 or Metal, its the native format.

File: servers/rendering/rendering_device_driver.h [hunk 8]
```diff
@@ -0,0 +1,619 @@
...
+
+	virtual FramebufferID framebuffer_create(RenderPassID p_render_pass, VectorView<TextureID> p_attachments, uint32_t p_width, uint32_t p_height) = 0;
+	virtual void framebuffer_free(FramebufferID p_framebuffer) = 0;
+
+	/****************/
+	/**** SHADER ****/
+	/****************/
+
+	virtual String shader_get_binary_cache_key() = 0;
+	virtual Vector<uint8_t> shader_compile_binary_from_spirv(VectorView<ShaderStageSPIRVData> p_spirv, const ShaderReflection &p_shader_refl, const String &p_shader_name) = 0;
```
[the remark this answers is not in the document]
Comment (reduz) [reply servers/rendering/rendering_device_driver.h:345]: So far this is the responsibility of the backend, because it returns the format that is best preferred for caching in the driver for binary.

That said, when exporting we may want to ship caches precompiled, so these compilation things may need to be able from somewhere else, but at the moment it does not matter and I would leave as is. That's Pedro's problem when he does this export optimization.

File: servers/rendering/rendering_device_driver.h [hunk 9]
```diff
@@ -0,0 +1,619 @@
...
+	/**** RENDERING ****/
+	/*******************/
+
+	// ----- SUBPASS -----
+
+	enum AttachmentLoadOp {
+		ATTACHMENT_LOAD_OP_LOAD = 0,
+		ATTACHMENT_LOAD_OP_CLEAR = 1,
+		ATTACHMENT_LOAD_OP_DONT_CARE = 2,
+		ATTACHMENT_LOAD_OP_NONE = 1000400000,
```
[the remark this answers is not in the document]
Comment (reduz) [reply servers/rendering/rendering_device_driver.h:430]: Yeah possibly not needed.

File: servers/rendering/rendering_device_driver.h [hunk 10]
```diff
@@ -0,0 +1,619 @@
...
+	};
+
+	enum AttachmentStoreOp {
+		ATTACHMENT_STORE_OP_STORE = 0,
+		ATTACHMENT_STORE_OP_DONT_CARE = 1,
+		ATTACHMENT_STORE_OP_NONE = 1000301000,
```
[the remark this answers is not in the document]
Comment (reduz) [reply servers/rendering/rendering_device_driver.h:436]: agreed I think its not needed, is it used?

File: servers/rendering/rendering_device_driver.h (hunk 3 above)
Comment (reduz) [reply servers/rendering/rendering_device_driver.h:451]: IMO this should go away as we remove subpasses anyway.

File: servers/rendering/rendering_device_driver.h (hunk 4 above)
Comment (reduz) [reply servers/rendering/rendering_device_driver.h:500]: Yeah thats a good point. That said I think we may want to simplify this.

File: servers/rendering/rendering_device_driver.h (hunk 6 above)
[the remark this answers is not in the document]
Comment (RandomShaper) [reply servers/rendering/rendering_device_driver.h:148]: As with other features in the driver, I've generally chosen to expose what is currently actually used instead of opening dorrs to the whole functionality. This is something that future maintainers (maybe yourself) will have to change in case there's an actual use case for partial mapping.

File: servers/rendering/rendering_device_driver.h (hunk 8 above)
[the remark this answers is not in the document]
Comment (RandomShaper) [reply servers/rendering/rendering_device_driver.h:345]: For the time being, yes, everything orbits around SPIR-V. That said, the part that is API-agnostic, which is the reflection into Godot `RenderingDevice` structures is performed by `RenderingDevice`. From that info, the driver has to put it into it's own format. The D3D12 backend does the translation to DXIL as part of that process. Honestly, other parts of the process of writing the Godot shader binary, like compressing the bytecode of the stages, etc. is very similar or identical between Vulkan and D3D12, and can probably be refactored into common and distinct parts... in a future iteration.

File: servers/rendering/rendering_device_driver.h (hunk 3 above)
Comment (RandomShaper) [reply servers/rendering/rendering_device_driver.h:451]: The one below is for subpass, and is just a garbage, but fixed default value to make it apparent when it's not properly filled. This one is a proper value that can be specified as an (unused) attachment index.

File: servers/rendering/rendering_device_driver.h [hunk 11]
```diff
@@ -0,0 +1,619 @@
...
+		LocalVector<AttachmentReference> input_references;
+		LocalVector<AttachmentReference> color_references;
+		AttachmentReference depth_stencil_reference;
+		LocalVector<AttachmentReference> resolve_references;
+		LocalVector<uint32_t> preserve_attachments;
+		AttachmentReference vrs_reference;
+	};
+
+	struct SubpassDependency {
+		uint32_t src_subpass = 0xffffffff;
```
[the remark this answers is not in the document]
Comment (RandomShaper) [reply servers/rendering/rendering_device_driver.h:467]: See above. This is just a fixed, but garbage default.

File: servers/rendering/rendering_device_driver.h (hunk 5 above)
Comment (RandomShaper) [reply servers/rendering/rendering_device_driver.h:582]: Yeah, the boundary between context and device is kind of blurry. The design warrants a good redesign pass.

File: servers/rendering/rendering_device_driver.h (hunk 10 above)
[the remark this answers is not in the document]
Comment (RandomShaper) [reply servers/rendering/rendering_device_driver.h:436]: It's not. I'll remove it.

File: servers/rendering/rendering_device_driver.h (hunk 9 above)
[the remark this answers is not in the document]
Comment (RandomShaper) [reply servers/rendering/rendering_device_driver.h:430]: I'm removing them (also the store counterpart).

**Comment by DarioSamo** [comment]
These are not something that necessarily need to be solved by this PR but are probably worth considering before doing the D3D12 version of RDD. Some are really just points to consider when doing the D3D12 refactor.

### Combined Image Samplers

As far as I know these are not supported by D3D12 and the backend would need to work around it in some ugly ways to support them. Are we relying on this feature a lot? What approach did the D3D12 PR take to solving this?

### Compute dispatch base

I'm not aware D3D12 has anything about this. This is a new addition to the API by this PR. We might want to consider it more carefully. It's also a Vulkan 1.1 feature at minimum, so we need to query device support for it. I think we should just remove it and let the user handle it by adding the offset in a UBO/Push constant.

### Barriers

D3D12 requires resource barriers if not using enhanced barriers. I think we should take the chance to make our barrier-API only take resources instead. I don't think we ever rely on memory barriers. As far as I'm aware the current D3D12 PR needs to work around this and I think it's hard to find use cases for full memory barriers with the upcoming acyclic render graph/barrier solver design.

### Semantics vs Locations

What approach does the current D3D12 PR take for matching vertex location inputs to the semantics? Is that something that we'd need to address on this API or is it solved through some other means as part of the backend responsibility? If there's a possibility this API will take shaders in its native format, it sounds like we might need to allow for a type of configuration that allows input semantics.

### Unordered Access State

What is the suggested solution for mapping this API to the unordered access state in D3D12? Using the image layout for general and the bit for shader writes?

### Texel Buffers

These don't translate to a flag during creation in D3D12, so we'll just need to track that bit to enable using the format on the SRV/UAV when it's assigned.

File: servers/rendering/rendering_device_driver.h [hunk 12]
```diff
@@ -0,0 +1,619 @@
...
+	// ----- BINDING -----
+
+	virtual void command_bind_push_constants(CommandBufferID p_cmd_buffer, ShaderID p_shader, uint32_t p_offset, VectorView<uint32_t> p_data) = 0;
+
+	// ----- CACHE -----
+
+	virtual bool pipeline_cache_create(const Vector<uint8_t> &p_data) = 0;
+	virtual void pipeline_cache_free() = 0;
+	virtual size_t pipeline_cache_query_size() = 0;
+	virtual Vector<Vector<uint8_t>> pipeline_cache_serialize() = 0;
```
[the remark this answers is not in the document]
Comment (RandomShaper) [reply servers/rendering/rendering_device_driver.h:418]: I'm not very concerned about the allocations, since, after all, that's being called when about to hit the disk. Also, one of the chunks has actually been already allocated by the driver.

Regarding the obscurity of the return type, I can't think of a good one. It's just a number of vectors the caller is expected to write back-to-back in the cache file.

**Comment by RandomShaper** [comment]
You may want to check the D3D12 PR (#70315) to see how I mapped the `RenderingDevice` features to it.

Regarding barriers, the D3D12 driver using resource-level barriers would just ignore the detailed ones (that's exactly what the PR above is doing). If enhanced barriers are eventually implemented, well, it just have to obey them.

I'm addressing the type safey of ids in the next push.

Regarding other things, this is just the first iteration and will for sure need changes to fit other APIs or future `RD` features better.

File: servers/rendering/rendering_device_driver.h (hunk 12 above)
[the remark this answers is not in the document]
Comment (DarioSamo) [reply servers/rendering/rendering_device_driver.h:418]: Why is it a Vector of Vectors but the input is a Vector though? Am I supposed to concatenate them and then use them back again as the input?

**Comment by RandomShaper** [comment]
Regarding type safety, I'm taking the first approach you discuss because most `RDD` ids aren't actually pointers to its view of resources, but just the Vulkan handles.

File: servers/rendering/rendering_device_driver.h (hunk 12 above)
[the remark this answers is not in the document]
Comment (RandomShaper) [reply servers/rendering/rendering_device_driver.h:418]: That _was_ the idea. And I'm saying _was_ because on closer inspection I've realized I can get rid of that ugliness. Next push will come with a pain `Vector<uint8_t>` as the return type.

File: servers/rendering/rendering_device_commons.cpp
Comment (stuartcarnie) [inline servers/rendering/rendering_device_commons.cpp:1]: Excellent – moving these APIs to a common place so they don't have to be duplicated a 3rd time (Vulkan, D3D12 and Metal) is 💯

File: servers/rendering/rendering_device_driver.h (hunk 6 above)
[the remark this answers is not in the document]
Comment (stuartcarnie) [reply servers/rendering/rendering_device_driver.h:148]: For reference, Metal doesn't have to map / unmap buffers. `MTLBuffer` just has a pointer to the buffer, and you must respect standard memory coherency rules.

File: servers/rendering/rendering_device_driver.h (hunk 4 above)
Comment (RandomShaper) [reply servers/rendering/rendering_device_driver.h:504]: Well, since `RD` knows if it's about a primary or secondary command buffer, that argument avoids the need for `RDD` to track it and be able to map `RD::CommandBufferID` to `VkCommandBuffer` directly. The parameter is leveraged this way:
```
	VkSubpassContents vk_subpass_contents = p_cmd_buffer_type == COMMAND_BUFFER_TYPE_PRIMARY ? VK_SUBPASS_CONTENTS_INLINE : VK_SUBPASS_CONTENTS_SECONDARY_COMMAND_BUFFERS;
	vkCmdBeginRenderPass((VkCommandBuffer)p_cmd_buffer.id, &render_pass_begin, vk_subpass_contents);
```

I'm not sure how orthogonal are command buffer level and subpass content level as concepts, but the fact is that currently `RD` uses them 1:1, so I just took advantage.

File: servers/rendering/rendering_device.cpp [hunk 13]
```diff
@@ -91,771 +442,6324 @@ RID RenderingDevice::shader_create_from_spirv(const Vector<ShaderStageSPIRVData>
...
+
+String RenderingDevice::shader_get_binary_cache_key() const {
+	return driver->shader_get_binary_cache_key();
+}
+
+Vector<uint8_t> RenderingDevice::shader_compile_binary_from_spirv(const Vector<ShaderStageSPIRVData> &p_spirv, const String &p_shader_name) {
+	ShaderReflection reflection;
+	if (_reflect_spirv(p_spirv, reflection) != OK) {
+		return Vector<uint8_t>();
+	}
```
Comment (stuartcarnie) [inline servers/rendering/rendering_device.cpp:3222]: I need to use SPIRV-Cross for Metal, in order to generate MSL from the SPIR-V. I realise the `_reflect_spirv` does some validation, but otherwise, I don't really need it, so it is wasted CPU.

Does it make sense to leave it to the driver to decide if it wants to use `_reflect_spirv`?

**Comment by RandomShaper** [comment]
Re-pushed. Lightmapper is fixed (or so I think).

File: servers/rendering/rendering_device.cpp (hunk 13 above)
Comment (RandomShaper) [reply servers/rendering/rendering_device.cpp:3222]: Very good point. In the next push, I'm making `_reflect_spirv()` an optional service that drivers can choose to use or not.

Comment (stuartcarnie) [reply servers/rendering/rendering_device.cpp]: Disregard, as I see I'll use this as a sanity chec

**Comment by RandomShaper** [comment]
@sakrel, thank you for your feedback. I acknowledge that the new single `RenderingDevice` class in this PR is indeed tailored to the current supported, and about to be supported, Vulkan and D3D12. Therefore, it's indeed unsuitable for APIs following different models.

The best option I can think of to make WebGPU fit again is just making `RenderingDevice` more flexible, in collaboration with the driver. As such, `RenderingDeviceDriver` would have a new function to query about the model of the underlying API-platform. `RenderingDevice` would get extra logic to handle the different possibilities. `RenderingDeviceDriver` would, in turn, have to provide new functions (I think) for the pieces of functionality that need different mechanics (e.g., callback system for async), that would only be implemented for `RenderingDeviceDriverWebGPU`, and any other potentially needing similar characteristics in the future.

As I see it , the interface of `RenderingDeviceDriver` will be subject to change for a long time (potentially forever), to let it adapt to any needs that arise on the side of `RenderingDevice`, to support all its present and future features, as well as every graphics API.

File: core/templates/rb_map.h [hunk 14]
```diff
@@ -116,6 +116,11 @@ class RBMap {
 		explicit operator bool() const {
 			return E != nullptr;
 		}
+
+		Iterator &operator=(const Iterator &b) {
+			E = b.E;
```
[the remark this answers is not in the document]
Comment (RandomShaper) [reply core/templates/rb_map.h:121]: In this kind of cases, I'd rather keep the PR consistent with the _de facto_ style in the surroundings, and maybe then make another one fixing the whole file. That's why I've followed a noncompliant style here.

[the remark this answers is not in the document]
Comment (RandomShaper) [reply core/templates/rb_map.h:121]: Fair enough. I'm amending the relevant commit with `p_it` in every case, as a bonus. Now I'm wondering about the usage of `p_other` vs. `p_type_in_snake_case` in special member functions across the whole codebase. Not super important (and not something for now), but the greater the consistency, the merrier. 😃

File: drivers/vulkan/rendering_device_driver_vulkan.cpp [hunk 15]
```diff
@@ -0,0 +1,3247 @@
...
+	}
+
+	// Bookkeep.
+
+	TextureInfo ti;
+	ti.vk_image = vk_image;
+
+	textures.insert(vk_image_view, ti);
+
+	return TextureID(vk_image);
```
Comment (BastiaanOlij) [inline drivers/vulkan/rendering_device_driver_vulkan.cpp:669]: This needs to be `return TextureID(vk_image_view);` just like the other create functions.

**Comment by BastiaanOlij** [comment]
After applying the fix I mentioned in my comment I tested this with https://github.com/BastiaanOlij/godot_openxr_demo and it now works for OpenXR.

Tested using the mobile renderer with:
- Valve Index running in PCVR mode
- Quest Pro running natively
- Quest 3 running natively (surprising, works without the bypass implemented in #84244, did you do something to cause presentation to be skipped when there is nothing to present?)

Performance seems on-par with Godot 4.2 stable, not surprising as the mobile renderer likely has less to gain from these improvements.

**Comment by atirut-w** [comment]
> Performance seems on-par with Godot 4.2 stable

Would this make a difference when multiple render passes is implemented? I feel like this would have a more impact once it comes to thatl

**Comment by BastiaanOlij** [comment]
@RandomShaper sadly I found a more serious issue. Things go really bad when I enable MSAA.

On desktop it's rendering fine, but inside the Quest I'm getting all sorts of issues with polygons flickering. It very much looks like that it is either resolving the buffer before its finished rendering, or it may be an issue with a missing barrier before the results are handed off to the XR Compositor (seeing this happens outside of the control of the rendering device, it has likely no idea a barrier is needed).

Interestingly enough recording, while the issues remain visible in headset, are not present in the recording, which suggest Meta might introduce a barrier here.

I suspect that I didn't have trouble on PCVR simply because we finish rendering WAY before the XR compositor decides to present the image, I'm at 0.5ms render time so the GPU isn't even breaking a sweat.

File: drivers/vulkan/rendering_device_driver_vulkan.cpp (hunk 15 above)
Comment (RandomShaper) [reply drivers/vulkan/rendering_device_driver_vulkan.cpp:669]: Done! Will come in the next push.

**Comment by DarioSamo** [comment]
> > Performance seems on-par with Godot 4.2 stable
> 
> Would this make a difference when multiple render passes is eventually implemented? I feel like this would have a more impact once it comes to that.

RDD isn't expected to have performance improvements on its own as far as I know since the barrier management is the same as what it was before.

**Comment by YuriSizov** [comment]
Just an update from the production team. We're ready to merge this whenever it's ready, it's next in the line of big rendering changes. We would be okay merging it for dev1, which we plan to have early next week. But if you'd rather have it merged afterward dev1, that's also okay. The next public build will only be made in January, so that won't yield any broad user testing yet, but at least your burden with juggling branches will be easier.

With that said, this still needs a rebase from @RandomShaper to finalize the commits and remove the D3D12 prerequisites.
And this still needs some approvals and positive reviews to formally proclaim it as ready. So cc @clayjohn and @BastiaanOlij. And I'm ready when you all are. 🙃

**Comment by DarioSamo** [comment]
I can attest I've been doing some very extensive testing of this branch as well as people who've tested the Acyclic Graph have been using this. I'll be doing a rebase when the final version of this PR is submitted to double-check everything still works as intended.

**Comment by RandomShaper** [comment]
@YuriSizov, thanks for the heads-up. The problem is that,  now that D3D12 is merged, this PR is not complete until I'm done bug fixing the RDD incarnation of it. So, this can only be put in dev1 if I can do that in time. (Likely and desirable.)

**Comment by YuriSizov** [comment]
@RandomShaper No pressure from us in that regard 🙂

**Comment by BastiaanOlij** [comment]
@YuriSizov @RandomShaper my testing so far with this, it all looks pretty good.

My only issue I ran into was on Quest where we seem to have a sync or fence issue introduced. The Quest starts consuming the image before we finish rendering it. @DarioSamo and I were looking into that and I've still got some tests to complete.

However I think that shouldn't be a showstopper for this to go ahead esp as we're recommending everyone on Quest to use compatibility already. It's something we can fix up later.

File: servers/rendering/rendering_device_driver.h [hunk 16]
```diff
@@ -0,0 +1,663 @@
...
+// Another utility, to make it easy to compare members of different enums, which is not fine with some compilers.
+#define ENUM_MEMBERS_EQUAL(m_a, m_b) ((int64_t)m_a == (int64_t)m_b)
+
+class RenderingDeviceDriver : public RenderingDeviceCommons {
+public:
+	struct ID {
+		uint64_t id = 0;
+		_ALWAYS_INLINE_ ID() = default;
+		_ALWAYS_INLINE_ ID(uint64_t p_id) :
+				id(p_id) {}
```
Comment (bruvzg) [inline servers/rendering/rendering_device_driver.h:103]: I guess this should be changed to `size_t` to work with 32-bit builds (static assert below).

File: drivers/vulkan/rendering_device_driver_vulkan.cpp [hunk 17]
```diff
@@ -0,0 +1,3347 @@
...
+			return context->get_vrs_capabilities().texel_size.y;
+		default:
+			ERR_FAIL_V(0);
+	}
+}
+
+uint64_t RenderingDeviceDriverVulkan::api_trait_get(ApiTrait p_trait) {
+	switch (p_trait) {
+		case API_TRAIT_TEXTURE_TRANSFER_ALIGNMENT:
+			return (uint64_t)MAX(16, limits.optimalBufferCopyOffsetAlignment);
```
Comment (bruvzg) [inline drivers/vulkan/rendering_device_driver_vulkan.cpp:3277]:
```suggestion
			return (uint64_t)MAX(16ULL, limits.optimalBufferCopyOffsetAlignment);
```

File: servers/rendering/rendering_device_driver.h (hunk 16 above)
Comment (RandomShaper) [reply servers/rendering/rendering_device_driver.h:103]: Good point. Poor 32-bit builds, always forgotten.

**Review by reduz — APPROVED** [review]
Looks fine on my end, incredible work Pedro!

File: core/config/project_settings.cpp [hunk 18]
```diff
@@ -1399,12 +1399,22 @@ ProjectSettings::ProjectSettings() {
 	GLOBAL_DEF("rendering/rendering_device/staging_buffer/texture_upload_region_size_px", 64);
 	GLOBAL_DEF("rendering/rendering_device/pipeline_cache/save_chunk_size_mb", 3.0);
 	GLOBAL_DEF("rendering/rendering_device/vulkan/max_descriptors_per_pool", 64);
+
+#ifdef D3D12_ENABLED
```
[the remark this answers is not in the document]
Comment (RandomShaper) [reply core/config/project_settings.cpp]: Yeah, sounds like the most reasonable thing to do.

**Comment by clayjohn** [comment]
Before jumping into code review. Just a few notes on the testing this branch has had (that I am aware of and apart from the testing that is mentioned above):
1. Used in https://github.com/godotengine/godot/pull/84976 
2. Used by stuart carnie in developing the Metal backend
3. Used by The Forge as their base for Vulkan optimizations
4. Tested by me in multiple scenes of varying complexity 
    a. Test scene from https://www.youtube.com/watch?v=9kcjFJJxO6I&t=1484s (tons of assets, textures, materials, GI, heavy shaders)
    b. TPS demo with different permutations of GI, fog, etc.
    c. Simplfied TPS demo using mobile renderer, but with heavy use of animations, particles, and decals
    
At this point any problems that have been identified have been fixed and are included in the current state of things. In testing the current iteration I did not identify any issues (no graphical bugs, no crashes, no new errors, no new validation layer errors)

**Review by clayjohn — APPROVED** [review]
The code looks good to me. I can't spot anything that I would want changed before merging. There is some discussion above about XR issues that may have been exposed by this PR. Bastiaan says he is okay fixing those after merging and I agree. It is very likely that those issues will be fixed by https://github.com/godotengine/godot/pull/84976 anyway which we will be merging shortly. 

I think it is time to move ahead with this PR and merge it!

**Review by bruvzg — APPROVED** [review]
Tested on macOS and iOS (rebased on top of master, since https://github.com/godotengine/godot/pull/86219 is required). Seems to work fine.

DX12 version on Windows also seems to work.

**Comment by dsnopek** [comment]
Because I saw @BastiaanOlij's comments about this not working on the Quest, I decided to try it myself, and, unfortunately, and this PR seems to completely break the Compatibility renderer. :-/ When I switch to the Vulkan Mobile renderer, it seems to work fine. So, kind of the reverse of what of what Bastiaan saw?

This is the error I'm getting with the Compatibility renderer (via `adb logcat`):

```
12-19 13:59:25.549  4418  4459 E godot   : USER ERROR: Parameter "native_window" is null.
12-19 13:59:25.549  4418  4459 E godot   :    at: DisplayServerAndroid (platform/android/display_server_android.cpp:572)
12-19 13:59:25.549  4418  4459 E godot   : USER ERROR: Unable to create DisplayServer, all display drivers failed.
12-19 13:59:25.549  4418  4459 E godot   :    at: setup2 (main/main.cpp:2466)
12-19 13:59:25.549  4418  4459 E godot   : USER ERROR: Condition "!_start_success" is true. Returning: false
12-19 13:59:25.549  4418  4459 E godot   :    at: start (main/main.cpp:2928)
```

And that last message is spammed over and over.

I suspect there's something slightly off in the Android changes?

**Comment by bruvzg** [comment]
> I suspect there's something slightly off in the Android changes?

```
ANativeWindow *OS_Android::get_native_window() const {
#if defined(VULKAN_ENABLED)
	return native_window;
#else
	return nullptr;
#endif
}
```

So these lines should be inside Vulkan check.
```
		ANativeWindow *native_window = OS_Android::get_singleton()->get_native_window();
		ERR_FAIL_NULL(native_window);
```

File: platform/android/display_server_android.cpp [hunk 19]
```diff
@@ -518,20 +517,31 @@ void DisplayServerAndroid::register_android_driver() {
...
+
+		union {
+#ifdef VULKAN_ENABLED
+			VulkanContextAndroid::WindowPlatformData vulkan;
+#endif
+		} wpd;
+#ifdef VULKAN_ENABLED
+		if (rendering_driver == "vulkan") {
+			wpd.vulkan.window = native_window;
+		}
```
Comment (bruvzg) [inline platform/android/display_server_android.cpp:538]:
```suggestion
		if (rendering_driver == "vulkan") {
			ANativeWindow *native_window = OS_Android::get_singleton()->get_native_window();
			ERR_FAIL_NULL(native_window);
			wpd.vulkan.window = native_window;
		}
```

File: platform/android/display_server_android.cpp [hunk 20]
```diff
@@ -518,20 +517,31 @@ void DisplayServerAndroid::register_android_driver() {
 }
 
 void DisplayServerAndroid::reset_window() {
-#if defined(VULKAN_ENABLED)
-	if (rendering_driver == "vulkan") {
+#if defined(RD_ENABLED)
+	if (context_rd) {
 		ANativeWindow *native_window = OS_Android::get_singleton()->get_native_window();
 		ERR_FAIL_NULL(native_window);
```
Comment (bruvzg) [inline platform/android/display_server_android.cpp:523]:
```suggestion
```

File: platform/android/display_server_android.cpp [hunk 21]
```diff
@@ -554,30 +564,47 @@ DisplayServerAndroid::DisplayServerAndroid(const String &p_rendering_driver, Dis
...
 
-#if defined(VULKAN_ENABLED)
-	context_vulkan = nullptr;
-	rendering_device_vulkan = nullptr;
+#if defined(RD_ENABLED)
+	context_rd = nullptr;
+	rendering_device = nullptr;
+
+	ANativeWindow *native_window = OS_Android::get_singleton()->get_native_window();
+	ERR_FAIL_NULL(native_window);
```
Comment (bruvzg) [inline platform/android/display_server_android.cpp:572]:
```suggestion
```

File: platform/android/display_server_android.cpp [hunk 22]
```diff
@@ -554,30 +564,47 @@ DisplayServerAndroid::DisplayServerAndroid(const String &p_rendering_driver, Dis
...
-			ERR_FAIL_MSG("Failed to create Vulkan window.");
+
+		union {
+#ifdef VULKAN_ENABLED
+			VulkanContextAndroid::WindowPlatformData vulkan;
+#endif
+		} wpd;
+#ifdef VULKAN_ENABLED
+		if (rendering_driver == "vulkan") {
+			wpd.vulkan.window = native_window;
```
Comment (bruvzg) [inline platform/android/display_server_android.cpp:596]:
```suggestion
			ANativeWindow *native_window = OS_Android::get_singleton()->get_native_window();
			ERR_FAIL_NULL(native_window);
			wpd.vulkan.window = native_window;
```

File: platform/android/display_server_android.cpp [hunk 23]
```diff
@@ -554,30 +564,47 @@ DisplayServerAndroid::DisplayServerAndroid(const String &p_rendering_driver, Dis
...
+	context_rd = nullptr;
+	rendering_device = nullptr;
+
+	ANativeWindow *native_window = OS_Android::get_singleton()->get_native_window();
+	ERR_FAIL_NULL(native_window);
 
+#if defined(VULKAN_ENABLED)
 	if (rendering_driver == "vulkan") {
-		ANativeWindow *native_window = OS_Android::get_singleton()->get_native_window();
-		ERR_FAIL_NULL(native_window);
```
Comment (dsnopek) [inline platform/android/display_server_android.cpp:563]: This change seems to be the source of my problems when using the Compatibility renderer. Previously, the `ERR_FAIL_NULL(native_window);` would only happen when using Vulkan, but this PR causes it to happen always.

Applying this diff fixes it for me:

```
diff --git a/platform/android/display_server_android.cpp b/platform/android/display_server_android.cpp
index a133cd3ee2..640441a4b3 100644
--- a/platform/android/display_server_android.cpp
+++ b/platform/android/display_server_android.cpp
@@ -568,9 +568,6 @@ DisplayServerAndroid::DisplayServerAndroid(const String &p_rendering_driver, Dis
        context_rd = nullptr;
        rendering_device = nullptr;
 
-       ANativeWindow *native_window = OS_Android::get_singleton()->get_native_window();
-       ERR_FAIL_NULL(native_window);
-
 #if defined(VULKAN_ENABLED)
        if (rendering_driver == "vulkan") {
                context_rd = memnew(VulkanContextAndroid);
@@ -578,6 +575,9 @@ DisplayServerAndroid::DisplayServerAndroid(const String &p_rendering_driver, Dis
 #endif
 
        if (context_rd) {
+               ANativeWindow *native_window = OS_Android::get_singleton()->get_native_window();
+               ERR_FAIL_NULL(native_window);
+
                if (context_rd->initialize() != OK) {
                        memdelete(context_rd);
                        context_rd = nullptr;
```

**Review by dsnopek — CHANGES_REQUESTED** [review]

File: platform/android/display_server_android.cpp (hunk 23 above)
Comment (RandomShaper) [reply platform/android/display_server_android.cpp:563]: Makes sense! The fix will come in the imminent next push.

**Comment by DarioSamo** [comment]
I found a particular project that doesn't work with this branch in D3D12 mode, I'll see if I can get an MRP once I narrow down what the project does that is incompatible, but it seems it's straight up unable to create the graphics PSOs on this project.

**Comment by RandomShaper** [comment]
Pushed removing many cases of runtime allocation (powered by `PagedAllocator`), plus a change to `PagedAllocator` to improve its compatibility (e.g., usable with `HashMap`), plus the fix discussed above.

> > I suspect there's something slightly off in the Android changes?
> 
> ```
> ANativeWindow *OS_Android::get_native_window() const {
> #if defined(VULKAN_ENABLED)
> 	return native_window;
> #else
> 	return nullptr;
> #endif
> }
> ```
> 
> So these lines should be inside Vulkan check.
> 
> ```
> 		ANativeWindow *native_window = OS_Android::get_singleton()->get_native_window();
> 		ERR_FAIL_NULL(native_window);
> ```

I already fixed it locally, but hadn't pushed yet.

**Comment by RandomShaper** [comment]
I've pushed with the requested fixes, plus a small change to use `PagedAllocator` for the multiple RDD-bookkept resources, instead of using plain `memnew()`.

Regarding the SDFGI issue reported by @DarioSamo, it's a known issue the pre-RDD Direct3D 12 renderer already had. (See _Deprecate Texture Aliasing_ in #70315.) It will be addressed separately.

**Comment by RandomShaper** [comment]
News on the SDFGI thing: there was a silly bug initializing textures requiring format sharing. On Windows 11 you don't even need the Agility SDK for the feature to work without the hack, so I've pushed a fix to let it work. (The hacky version still works for me on W10 with no Agility SDK, on Nvidia. A proper fix for other GPUs will be provided in the future.)

**Comment by RandomShaper** [comment]
If CI succeeds (it failed because of a C++ technicality in the just added `VersatileResource` helper for allocation avoidance).

**Review by dsnopek — APPROVED** [review]
Thanks! I'm not qualified to review the RD changes (aka the main point of this PR) but I just retested the latest with the Compatibility renderer on Quest 3, and it's working now. :-)

**Comment by YuriSizov** [comment]
Okay, so Android/Quest issues have been addressed, and if the CI passes we're ready to go. Correct? 🙂

**Comment by DarioSamo** [comment]
> Okay, so Android/Quest issues have been addressed, and if the CI passes we're ready to go. Correct? 🙂

I just reported an issue with the latest change so just a bit more.

**Comment by DarioSamo** [comment]
> Not the D3D12 one from above which is also present in master?

There's just an implementation error in the recent change that will cause the list to get filled incorrectly with the size of the array is > 1. Should be fixed easily.

**Comment by RandomShaper** [comment]
It seems to be a GPU driver or OS version specific issue. Works as expected on some setups, fails on another. Maybe a driver bug. We are fine with merging as it is now. The code seems to be OK.

**Comment by RandomShaper** [comment]
This is never ending, is it? 😅 Pushed with a fix for the memory leaks.

**Comment by RandomShaper** [comment]
I think I'm going to force-push again...

Just kidding. 😈

**Comment by YuriSizov** [comment]
Thanks! As often is the case with such achievements, this monumental effort is not the end, but a beginning for even more exciting new things to be added into the engine in near and far future. But tonight you can rest with a proud smile. Cheers to everyone who contributed and tested this PR!

**Comment by Cyangmou** [comment]
Really happy to see this, just wanted to say thanks for the effort and can't wait for future improvements this will enable!

**Comment by aaronfranke** [comment]
This does not compile on macOS, it fails on the linking stage:

```
[100%] Linking Program bin/godot.macos.editor.arm64 ...
Undefined symbols for architecture arm64:
  "_vkCmdDrawIndexedIndirectCount", referenced from:
      RenderingDeviceDriverVulkan::command_render_draw_indexed_indirect_count(RenderingDeviceDriver::CommandBufferID, RenderingDeviceDriver::BufferID, unsigned long long, RenderingDeviceDriver::BufferID, unsigned long long, unsigned int, unsigned int) in libdrivers.macos.editor.arm64.a(rendering_device_driver_vulkan.macos.editor.arm64.o)
  "_vkCmdDrawIndirectCount", referenced from:
      RenderingDeviceDriverVulkan::command_render_draw_indirect_count(RenderingDeviceDriver::CommandBufferID, RenderingDeviceDriver::BufferID, unsigned long long, RenderingDeviceDriver::BufferID, unsigned long long, unsigned int, unsigned int) in libdrivers.macos.editor.arm64.a(rendering_device_driver_vulkan.macos.editor.arm64.o)
ld: symbol(s) not found for architecture arm64
```

**Comment by clayjohn** [comment]
> This does not compile on macOS, it fails on the linking stage (I tested both arm64 and x86_64):
> 
> ```
> [100%] Linking Program bin/godot.macos.editor.arm64 ...
> Undefined symbols for architecture arm64:
>   "_vkCmdDrawIndexedIndirectCount", referenced from:
>       RenderingDeviceDriverVulkan::command_render_draw_indexed_indirect_count(RenderingDeviceDriver::CommandBufferID, RenderingDeviceDriver::BufferID, unsigned long long, RenderingDeviceDriver::BufferID, unsigned long long, unsigned int, unsigned int) in libdrivers.macos.editor.arm64.a(rendering_device_driver_vulkan.macos.editor.arm64.o)
>   "_vkCmdDrawIndirectCount", referenced from:
>       RenderingDeviceDriverVulkan::command_render_draw_indirect_count(RenderingDeviceDriver::CommandBufferID, RenderingDeviceDriver::BufferID, unsigned long long, RenderingDeviceDriver::BufferID, unsigned long long, unsigned int, unsigned int) in libdrivers.macos.editor.arm64.a(rendering_device_driver_vulkan.macos.editor.arm64.o)
> ld: symbol(s) not found for architecture arm64
> ```

It compiles in the CI. Are you using any different parameters that would have an appreciable difference?

Molten VK appears to have support for both those functions, so it is odd that it's not linking

**Comment by aaronfranke** [comment]
@clayjohn Fixed, the problem was that I was using an old version of MoltenVK. If anyone else is experiencing this issue, try updating the Vulkan SDK.

File: platform/linuxbsd/x11/display_server_x11.cpp [hunk 24]
```diff
@@ -5606,10 +5606,21 @@ DisplayServerX11::WindowID DisplayServerX11::_create_window(WindowMode p_mode, V
...
+#endif
+			} wpd;
+#ifdef VULKAN_ENABLED
+			if (rendering_driver == "vulkan") {
+				wpd.vulkan.window = wd.x11_window;
+				wpd.vulkan.display = x11_display;
+			}
+#endif
+			Error err = context_rd->window_create(id, p_vsync_mode, win_rect.size.width, win_rect.size.height, &wpd);
+			ERR_FAIL_COND_V_MSG(err != OK, INVALID_WINDOW_ID, vformat("Can't create a %s window", context_rd->get_api_name()));
```
[the remark this answers is not in the document]
Comment (AThousandShips) [reply platform/linuxbsd/x11/display_server_x11.cpp:5623]: Related:
* https://github.com/godotengine/godot/issues/86436

[the remark this answers is not in the document]
Comment (akien-mga) [reply platform/linuxbsd/x11/display_server_x11.cpp:5623]: Thanks, copied my logs there.
