### PR TITLE
Fix theme updating of the inspector sections

### LINKED ISSUE #70356: Changing the editor's theme does not affect the scrollable property headers in the inspector immediately
### Godot version

2a04b18d37de6c6e621db5a9dfd1cd0da5ccb015

### System information

Windows 11

### Issue description

Just a minor editor bug, which is nicely to be fixed.

bug

### Steps to reproduce

^^

### Minimal reproduction project

Too easy to reproduce

### PR DESCRIPTION
**Pull request by Chaosus**
Fix https://github.com/godotengine/godot/issues/70356

I think it's more precise version than https://github.com/godotengine/godot/pull/70381 (not the whole inspector tree is updating, only sections to be redrawn) and have a chance to be merged.

Also fixes few incorrect places in code.
PS: `EditorInspectorSection` seems to be an internal class, so it's safe to merge without breaking change for the users.

### CODE REVIEW

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -1657,7 +1661,7 @@ void EditorInspectorSection::property_can_revert_changed(const String &p_path, b
 }
 
 void EditorInspectorSection::_bind_methods() {
-	ClassDB::bind_method(D_METHOD("setup", "section", "label", "object", "bg_color", "foldable"), &EditorInspectorSection::setup);
+	ClassDB::bind_method(D_METHOD("setup", "section", "label", "object", "bg_color", "foldable", "indent_depth", "level"), &EditorInspectorSection::setup, DEFVAL(0), DEFVAL(1));
```
Comment (KoBeWi) [inline editor/editor_inspector.cpp:1664]: I wonder why this is exposed 🤔

File: editor/editor_inspector.cpp [hunk 2]
```diff
@@ -1353,6 +1353,9 @@ void EditorInspectorSection::_notification(int p_what) {
 	switch (p_what) {
 		case NOTIFICATION_THEME_CHANGED: {
 			update_minimum_size();
+			bg_color = get_theme_color(SNAME("prop_subsection"), EditorStringName(Editor));
+			bg_color.a /= level;
```
Comment (KoBeWi) [inline editor/editor_inspector.cpp:1357]: Setting it here makes the `p_color` argument in `setup()` unnecessary. You should remove that argument.

File: editor/editor_inspector.cpp [hunk 3]
```diff
@@ -1353,6 +1353,9 @@ void EditorInspectorSection::_notification(int p_what) {
...
+			queue_redraw();
```
Comment (KoBeWi) [inline editor/editor_inspector.cpp:1358]:
```suggestion
```
This is done automatically.

File: editor/editor_inspector.cpp (hunk 2 above)
Comment (Chaosus) [reply editor/editor_inspector.cpp:1357]: Removal of this from setup will lead to incorrect color until the theme changed:

For example this:
изображение

Instead of this:
изображение

Comment (KoBeWi) [reply editor/editor_inspector.cpp:1357]: Seems like the section is added as child before setup, which is what causes this problem.
It would be nice to sort it out eventually, but for a bugfix it's safer to leave it as is.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
