### PR TITLE
Restructure and refine the noise module

### LINKED ISSUE #36675: Vulkan: Mipmaps aren't generated automatically for a NoiseTexture applied to a StandardMaterial3D
**Godot version:** Git https://github.com/godotengine/godot/commit/e4bc16b7b6a7a9354e6037cb571de934a8ec1430

**OS/device including version:** Fedora 31, NVIDIA 440.44, GeForce GTX 1080

**Issue description:** Mipmaps aren't being generated when applying a NoiseTexture in a 3D environment, which makes the texture grainy at a distance. This doesn't happen with ImageTexture. Interestingly, enabling anisotropic filtering on the texture *slightly* improves the appearance, but not by much.

**Steps to reproduce:** Create a MeshInstance and a StandardMaterial3D. Assign a NoiseTexture with OpenSimplexNoise to the material's Albedo property. Compare the result with an ImageTexture.

image

**Minimal reproduction project:** [test_mipmap.zip](https://github.com/godotengine/godot/files/4270376/test_mipmap.zip)

### PR DESCRIPTION
**Pull request by Geometror**
This PR is a follow-up to #56718 aiming to improve/refine the noise module and incorporate some of the feedback paired with a couple of bugfixes:

- Make interface methods and FastNoiseLite functions const
- Add mipmap generation toggleable with property (significantly improves quality, see demo picture below)
-  Move property color_ramp to NoiseTexture, so it can be used with other noise generators (in general, it makes more sense like that because it has nothing to do with the noise generator)
-  Move property in_3d_space to NoiseTexture (makes more sense there imo, since it was only used for creating 2d images; it is now a parameter of the get_image/get_seamless_image functions)
    -   Fix transparency blending for seamless textures
-  Change the default cellular distance function from CELL_VALUE to DISTANCE (as it is more common)
-  Initialize all primitive variables in the header and restructure the constructor of the FastNoiseLite resource so that emit_changed() and notify_property_list_changed() won't be called in it
- Some minor code style improvements, fix typo in fractal_ping_pong_strength and restructure *_bind_methods() to be more consistent with the rest of the codebase
-  Fix color_ramp removal not updating texture
-  Move the get_image implementation to noise.cpp as it just uses the interface methods and nothing specific to FastNoiseLite. Noise generators can still overwrite it, but the standard implementation should be sufficient in most cases.
- Add a general Noise resource preview plugin (quite essential when using the Noise resource directly without NoiseTexture for e.g. procedural world generation, etc.)
	- Toggleable "in 3d space" preview option (saved individually per resource)
	- Uses a NoiseTexture internally, so the noise generation happens on a thread allowing for smooth editing and direct feedback
- Fix domain warp noise always using seed 0
- Fix noise offset step size set to 1, effectively only allowing integers for each component when set via the inspector

Demo with materials which only use noise textures:
dem1

Demo of the noise preview:
noise_preview

There are still some features left I would like to add, but those are better addressed in another PR.

*Bugsquad edit: This closes https://github.com/godotengine/godot/issues/36675.*

### CODE REVIEW

**Comment by fire-forge** [comment]
Looks great! I'll take some time to review the code changes when I have a chance.

A suggestion: use a regular Button with text for the `3D` button instead of a custom icon. That would make it translatable, whereas an icon cannot be translated.

The demo with noise materials is really impressive. I never would have thought something like that could be made only with noise textures. FastNoiseLite seems to be a much more powerful tool than I realized.

File: modules/noise/noise_texture.cpp [hunk 1]
```diff
@@ -143,18 +155,42 @@ Ref<Image> NoiseTexture::_generate_texture() {
...
+	int height = p_image->get_height();
+
+	Ref<Image> new_image;
+	new_image.instantiate();
+	new_image->create(width, height, false, Image::FORMAT_RGBA8);
+
+	for (int row = 0; row < height; row++) {
+		for (int col = 0; col < width; col++) {
+			Color pixel_color = p_image->get_pixel(col, row);
+			Color ramp_color = color_ramp->get_color_at_offset(pixel_color.get_luminance());
```
Comment (fire-forge) [inline modules/noise/noise_texture.cpp:186]:
```suggestion
			Color ramp_color = color_ramp->get_color_at_offset(pixel_color.r);
```

Does it need to use luminance here, or can it use the raw noise value? Before this PR it used the raw noise value, whereas `get_luminance()` does some kind of color space conversion.

If you do change this then the code from the next comment will need to be updated, because it includes this line with `get_luminance()`.

File: modules/noise/noise_texture.cpp [hunk 2]
```diff
@@ -143,18 +155,42 @@ Ref<Image> NoiseTexture::_generate_texture() {
...
+			new_image->set_pixel(col, row, ramp_color);
+		}
+	}
```
Comment (fire-forge) [inline modules/noise/noise_texture.cpp:189]:
```suggestion
	Vector<uint8_t> data;
	data.resize(width * height * 4);

	uint8_t *wd8 = data.ptrw();

	for (int row = 0, x = 0; row < height; row++) {
		for (int col = 0; col < width; col++, x++) {
			Color pixel_color = p_image->get_pixel(col, row);
			Color ramp_color = color_ramp->get_color_at_offset(pixel_color.get_luminance());
			wd8[x * 4 + 0] = uint8_t(CLAMP(ramp_color.r * 255, 0, 255));
			wd8[x * 4 + 1] = uint8_t(CLAMP(ramp_color.g * 255, 0, 255));
			wd8[x * 4 + 2] = uint8_t(CLAMP(ramp_color.b * 255, 0, 255));
			wd8[x * 4 + 3] = uint8_t(CLAMP(ramp_color.a * 255, 0, 255));
		}
	}

	new_image->create(width, height, false, Image::FORMAT_RGBA8, data);
```

This is derived from the `FastNoiseLite::get_image()` function that was removed. It should be more performant than using `Image.set_pixel()` directly. I haven't tested this code, but it should work (or at least be close to working).

File: modules/noise/noise_texture.cpp [hunk 3]
```diff
@@ -227,6 +263,26 @@ bool NoiseTexture::get_invert() const {
 	return invert;
 }
 
+void NoiseTexture::set_in_3d_space(bool p_enable) {
+	in_3d_space = p_enable;
```
Comment (fire-forge) [inline modules/noise/noise_texture.cpp:267]:
```suggestion
	if (p_enable == in_3d_space) {
		return;
	}
	in_3d_space = p_enable;
```
Same check as in most of the other setters to prevent regenerating the texture when the value is unchanged.

File: modules/noise/noise_texture.h [hunk 4]
```diff
@@ -51,15 +51,18 @@ class NoiseTexture : public Texture2D {
 	mutable RID texture;
 	uint32_t flags = 0;
 
-	Ref<Noise> noise;
-	bool invert = false;
 	Vector2i size = Vector2i(512, 512);
```
Comment (fire-forge) [inline modules/noise/noise_texture.h:54]:
```suggestion
	Size2i size = Size2i(512, 512);
```

File: modules/noise/doc_classes/NoiseTexture.xml [hunk 5]
```diff
@@ -24,9 +24,20 @@
...
+		<member name="generate_mipmaps" type="bool" setter="set_generate_mipmaps" getter="is_generating_mipmaps" default="true">
+			Determines whether mipmaps are generated for this texture.
+			Enabling this results in less texture aliasing, but the noise texture generation may take longer.
+			Requires (anisotropic) mipmap filtering to be enabled for a material to have an effect.
+		</member>
 		<member name="height" type="int" setter="set_height" getter="get_height" default="512">
 			Height of the generated texture.
 		</member>
+		<member name="in_3d_space" type="bool" setter="set_in_3d_space" getter="is_in_3d_space" default="false">
+			Determines whether the noise image is calculated in 3d space. May result in reduced contrast.
```
Comment (fire-forge) [inline modules/noise/doc_classes/NoiseTexture.xml:39]:
```suggestion
			Determines whether the noise image is calculated in 3D space. May result in reduced contrast.
```

**Comment by Calinou** [comment]
> The demo with noise materials is really impressive. I never would have thought something like that could be made only with noise textures. FastNoiseLite seems to be a much more powerful tool than I realized.

This could be a good demo to submit to the [godot-demo-projects' `4.0-dev` branch](https://github.com/godotengine/godot-demo-projects) under the name "Procedural Textures" or something like that :slightly_smiling_face:

**Comment by Zireael07** [comment]
Yep, I know how to do sand/water but not the other two!

File: modules/noise/noise_texture.cpp (hunk 1 above)
Comment (Geometror) [reply modules/noise/noise_texture.cpp:186]: I think get_luminance calculates the perceived brightness of a pixel, so for a grayscale image where r=g=b the computed value is the same as the r component. However, if a noise library generates an image in color all channels are included with get_luminance().

File: modules/noise/noise_texture.cpp (hunk 2 above)
Comment (Geometror) [reply modules/noise/noise_texture.cpp:189]: You're right, the code you suggested would be slightly faster, but the problem is the lack of flexibility. (a Noise resource could generate a float texture). NoiseTexture should be able to handle all image formats because it has no information about which format `get_image` or `get_seamless_image` returns.

**Comment by Geometror** [comment]
@fire-forge I changed the button to a text-based one as you suggested. It does take up some more space, but imo it’s better this way (toggle state more clear/translatable/easier to click on). I originally planned to design a non-text icon like the ones you can find in the material preview but after using this placeholder texture I couldn't come up with any icon which wouldn't be confusing.
grafik

@Calinou After this gets merged, I'd be happy to submit a small demo.

**Comment by fire-forge** [comment]
@Geometror If you want to use an icon-based button, you could reuse the 3D icon from the top bar tabs. It'd also be a good idea to add a tooltip explaining what the button does since it might not be obvious from just an icon.

image

**Review by clayjohn — COMMENTED** [review]
Looks good to me, is there anything else this PR needs before being ready to merge?

File: modules/noise/fastnoise_lite.cpp [hunk 6]
```diff
@@ -418,108 +332,103 @@ void FastNoiseLite::_bind_methods() {
...
 
 	ClassDB::bind_method(D_METHOD("_changed"), &FastNoiseLite::_changed);
 
+	ADD_PROPERTY(PropertyInfo(Variant::INT, "noise_type", PROPERTY_HINT_ENUM, "Simplex,Simplex Smooth,Cellular,Perlin,Value Cubic,Value"), "set_noise_type", "get_noise_type");
+	ADD_PROPERTY(PropertyInfo(Variant::INT, "seed"), "set_seed", "get_seed");
+	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "frequency", PROPERTY_HINT_RANGE, ".001,1"), "set_frequency", "get_frequency");
+	ADD_PROPERTY(PropertyInfo(Variant::VECTOR3, "offset", PROPERTY_HINT_RANGE, "-999999999,999999999,0.01"), "set_offset", "get_offset");
+
+	ADD_GROUP("Fractal", "fractal_");
+	ADD_PROPERTY(PropertyInfo(Variant::INT, "fractal_type", PROPERTY_HINT_ENUM, "None,FBM,Ridged,PingPong"), "set_fractal_type", "get_fractal_type");
```
Comment (fire-forge) [inline modules/noise/fastnoise_lite.cpp:410]:
```suggestion
	ADD_PROPERTY(PropertyInfo(Variant::INT, "fractal_type", PROPERTY_HINT_ENUM, "None,FBM,Ridged,Ping-Pong"), "set_fractal_type", "get_fractal_type");
```

File: modules/noise/fastnoise_lite.cpp [hunk 7]
```diff
@@ -418,108 +332,103 @@ void FastNoiseLite::_bind_methods() {
...
+	ADD_PROPERTY(PropertyInfo(Variant::INT, "fractal_octaves", PROPERTY_HINT_RANGE, "1,10,1"), "set_fractal_octaves", "get_fractal_octaves");
+	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "fractal_lacunarity"), "set_fractal_lacunarity", "get_fractal_lacunarity");
+	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "fractal_gain"), "set_fractal_gain", "get_fractal_gain");
+	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "fractal_weighted_strength", PROPERTY_HINT_RANGE, "0,1,0.01"), "set_fractal_weighted_strength", "get_fractal_weighted_strength");
+	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "fractal_ping_pong_strength"), "set_fractal_ping_pong_strength", "get_fractal_ping_pong_strength");
+
+	ADD_GROUP("Cellular", "cellular_");
+	ADD_PROPERTY(PropertyInfo(Variant::INT, "cellular_distance_function", PROPERTY_HINT_ENUM, "Euclidean,EuclideanSquared,Manhattan,Hybrid"), "set_cellular_distance_function", "get_cellular_distance_function");
```
Comment (fire-forge) [inline modules/noise/fastnoise_lite.cpp:418]:
```suggestion
	ADD_PROPERTY(PropertyInfo(Variant::INT, "cellular_distance_function", PROPERTY_HINT_ENUM, "Euclidean,Euclidean Squared,Manhattan,Hybrid"), "set_cellular_distance_function", "get_cellular_distance_function");
```

File: modules/noise/fastnoise_lite.cpp [hunk 8]
```diff
@@ -418,108 +332,103 @@ void FastNoiseLite::_bind_methods() {
...
+	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "cellular_jitter"), "set_cellular_jitter", "get_cellular_jitter");
+	ADD_PROPERTY(PropertyInfo(Variant::INT, "cellular_return_type", PROPERTY_HINT_ENUM, "CellValue,Distance,Distance2,Distance2Add,Distance2Sub,Distance2Mul,Distance2Div"), "set_cellular_return_type", "get_cellular_return_type");
```
Comment (fire-forge) [inline modules/noise/fastnoise_lite.cpp:420]:
```suggestion
	ADD_PROPERTY(PropertyInfo(Variant::INT, "cellular_return_type", PROPERTY_HINT_ENUM, "Cell Value,Distance,Distance2,Distance2Add,Distance2Sub,Distance2Mul,Distance2Div"), "set_cellular_return_type", "get_cellular_return_type");
```

File: modules/noise/fastnoise_lite.cpp [hunk 9]
```diff
@@ -418,108 +332,103 @@ void FastNoiseLite::_bind_methods() {
...
+
+	ADD_GROUP("Domain Warp", "domain_warp_");
+	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "domain_warp_enabled"), "set_domain_warp_enabled", "is_domain_warp_enabled");
+	ADD_PROPERTY(PropertyInfo(Variant::INT, "domain_warp_type", PROPERTY_HINT_ENUM, "Simplex,SimplexReduced,BasicGrid"), "set_domain_warp_type", "get_domain_warp_type");
```
Comment (fire-forge) [inline modules/noise/fastnoise_lite.cpp:424]:
```suggestion
	ADD_PROPERTY(PropertyInfo(Variant::INT, "domain_warp_type", PROPERTY_HINT_ENUM, "Simplex,Simplex Reduced,Basic Grid"), "set_domain_warp_type", "get_domain_warp_type");
```

**Review by fire-forge — CHANGES_REQUESTED** [review]
Just needs a rebase since https://github.com/godotengine/godot/pull/60315 was merged. These comments cover all the changes.

**Comment by Geometror** [comment]
Rebased. Should be ready to merge :)

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Calinou** [comment]
> @Calinou After this gets merged, I'd be happy to submit a small demo.

@Geometror Do you still have the demo files in question?

**Comment by Geometror** [comment]
@Calinou Unfortunately I couldn't find them, but I can rebuild some of the materials and create a small demo scene.

**Comment by Zireael07** [comment]
@Geometror Please do!

**Comment by Geometror** [comment]
grafik
Close up:
grafik
Project files:
[noise-demo.zip](https://github.com/godotengine/godot/files/9946998/noise-demo.zip)
