### PR TITLE
Make label sizing algorithm more robust

### LINKED ISSUE #73296: [4.0 RC2] Label with autowrap and blank text does not show new text after the first frame
### Godot version

4.0 rc2

### System information

openSUSE Tumbleweed, compatibility renderer

### Issue description

A regression from RC1, most likely due to #73234. If we have a Label node with no text and with an autowrap mode set to something other than `Off`, and then we try to change the text into something else, the new text does not appear. Changing the text again does work, as long as the text is not the same as the previous text.

It does seem to work properly if the change happens immediately in the first frame of the game, but it does not work if the text changes in any other frame. Resizing the game window also seems to make the text visible. This did not occur in RC1.

### Steps to reproduce

Create a new Label node with no text and set its autowrap mode to something other than off. Then, change the text of that label after the first frame, either with a timer, an `await get_tree().process_frame` signal, an AnimationPlayer, or anything at all. Run the project, and the label will still appear empty.

Alternatively, simply download the MRP linked below, and run it. The text "This doesn't appear" will not appear, and after one second, the text "This appears" will appear. The expected behavior would be for both texts to appear.
Peek 2023-02-14 18-20

### Minimal reproduction project

[BlankLabelBug.zip](https://github.com/godotengine/godot/files/10734583/BlankLabelBug.zip)

### LINKED ISSUE #73385: Resizing Ninepatchrect horizontaly does not draw child label text.
### Godot version

v4.0.rc2.official [d2699dc7a]

### System information

Windows 10

### Issue description

Resizing a ninepatchrect horizontally causes child label text to not show.  
Vertical resizing is fine.  
If you resize it enough that label has to re-do the text wrap then text shows up.
Toggle the visibility and text will show up.
Resize the 9patch Vertically and text will show up.  

I would think a comparison between the Vertical and Horizontal handling in the code would show the issue. 

https://user-images.githubusercontent.com/3193592/219109730-d19edde5-6049-4460-9cab-f15ec2a3ea4a.mp4

### Steps to reproduce

In attached project, resize the 9pathc node and observe the label text behavior. Also, see attached video 

### Minimal reproduction project

[ninepatch_bug.zip](https://github.com/godotengine/godot/files/10745926/ninepatch_bug.zip)

### PR DESCRIPTION
**Pull request by RandomShaper**
Fixes #73296.
Fixes https://github.com/godotengine/godot/issues/73385.

This `Label` thing has been about to take me out of the few vestiges of sanity I still possess.

I've reworked the algorithm once more, in a way that it does everything needed to get the expected results while at the same time still looking sensible (not just a hardwire of contrived checks and bookkeeping to alleviate regressions.)

I've once more tested this to ensure the bugs in this unfortunate chain of issues are still dead like true poetry; namely:
- Catastrophic layout dance that freezes the editor upon an error in the Godot internal shaders.
- From https://github.com/godotengine/godot/pull/72387#issuecomment-1415344761:
  - Extremely tall script create dialog.
  - Project manager as it could look in a dream; that is, mostly normal, but with a lot of text missing.
- #73230.
- #72339.
- #73385.
- #73296, obviously.

I've also done some smoke testing by browsing different parts of the editor (help, some dialogs, etc.) to rule out potential new regressions. I have the impression that some user will be able to find one, though, but my gut feeling about the correctness of the code is now better than last time.

**UPDATE:** Added some related fixed bugs to the list.

### CODE REVIEW

File: scene/gui/label.cpp [hunk 1]
```diff
@@ -367,10 +373,9 @@ void Label::_notification(int p_what) {
 			}
 
 			if (dirty || font_dirty || lines_dirty) {
-				_shape();
-				if (lines_dirty) {
+				if (!_shape()) {
```
Comment (RandomShaper) [inline scene/gui/label.cpp:376]: This change was the main one to get #73296 fixed, but that wouldn't be enough since it by itself would "unbalance" other parts of the algorithm, causing already fixed bugs to come back. That's why this PR had to go over the whole thing once again.

**Comment by akien-mga** [comment]
To help with reviewing the changes in a holistic manner, I made a custom branch with the 3 preview PRs reverted, and then the 4 PRs reapplied but squashed into one: https://github.com/akien-mga/godot/tree/label-lo

This should make it easier to review the whole set of changes as one chunk and make sure that all loose ends are tied.

Unlike our usual procedure, I suggest making further changes to this PR as separate commits so that the review can be based on https://github.com/akien-mga/godot/tree/label-lo + new commits in this PR (and we'll get it squashed before merge once approved).

**Review by bruvzg — APPROVED** [review]
Seems fine.

For 4.1 we probably should rework container filling / sizing to avoid this kind of stuff. Probably pre-calculate min (shape with width `1`) and max (shape with mandatory breaks only) sizes independent for width/height (and a non-destructive function to get control height for specific width).

**Comment by RandomShaper** [comment]
In the light of the retrospective diff, I've added one commit, which does the following:
- Cosmetic changes; most notably avoid extra `lines_visible`/`visible_lines` changes.
- Keep default min size calculation as the original did: `Size2(1, get_line_height())`, which makes more sense.

**Comment by akien-mga** [comment]
I went ahead and amended your fixup to my unified commit to make it smaller:
https://github.com/akien-mga/godot/commit/3881059d0062747a1aa6a8130904eb6cae8b476e?w=1

**Comment by akien-mga** [comment]
Compiled locally and started testing, here's the first problem I notice:

image

**Comment by bruvzg** [comment]
> Compiled locally and started testing, here's the first problem I notice:

Seems like a result of this change?

> Keep default min size calculation as the original did: Size2(1, get_line_height()), which makes more sense.

The version I was looking at before was not doing this, but now I'm able to reproduce it on macOS as well.

**Comment by RandomShaper** [comment]
Yes. I think I was too reckless in not testing everything again after that change, given how slippery this slope is. That said, I think the idea of that change should stay, but will need some other change to avoid the new issues. I'll add another commit with that very soon.

**Comment by akien-mga** [comment]
I'm compiling now to test. I think you can squash the commits already, I'm fairly confident this should be good to merge after I've confirmed it works as expected in the editor.

**Review by akien-mga — APPROVED** [review]
Seems to work fine from a quick test of the editor interface, including dialogs and tooltips.

**Comment by akien-mga** [comment]
Thanks!
