### PR TITLE
[3.x] Fix several `OS_X11` memory leaks

### LINKED ISSUE #60467: `OS.get_latin_keyboard_variant` causes memory leak
### Godot version

3.5 beta 4

### System information

Ubuntu 22.04, Intel HD 3000

### Issue description

```
	var temp_variable1 = ClassDB.instance("_OS")
	temp_variable1.get_latin_keyboard_variant()
	temp_variable1.free()
```
```
Direct leak of 144 byte(s) in 2 object(s) allocated from:
    #0 0x7fe77c8f3a66 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:153
    #1 0x7fe77c706336 in XkbAllocKeyboard (/lib/x86_64-linux-gnu/libX11.so.6+0xa2336)
    #2 0x13737dd0 in _OS::get_latin_keyboard_variant() const core/bind/core_bind.cpp:544
    #3 0x241a93d in MethodBind0RC<String>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:581
    #4 0x12ab065a in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:918
    #5 0x12aae1a3 in Object::callv(StringName const&, Array const&) core/object.cpp:827
    #6 0x12b17f86 in MethodBind2R<Variant, StringName const&, Array const&>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:1681
    #7 0x12ab065a in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:918
    #8 0x12d53970 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1185
    #9 0x1f0b241 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1048
    #10 0x1d399f3 in GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) modules/gdscript/gdscript.cpp:1196
    #11 0x12ab01c7 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:899
    #12 0x12d53970 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1185
    #13 0x1f0b2c2 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1050
    #14 0x1d39f09 in GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1211
    #15 0xcf19d65 in Node::_notification(int) scene/main/node.cpp:56
    #16 0x1bdfc0f in Node::_notificationv(int, bool) scene/main/node.h:45
    #17 0x12ab0af6 in Object::notification(int, bool) core/object.cpp:927
    #18 0xd0596df in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:1057
    #19 0xd048a62 in SceneTree::idle(float) scene/main/scene_tree.cpp:596
    #20 0x1a18d22 in Main::iteration() main/main.cpp:2271
    #21 0x18e7b7b in OS_X11::run() platform/x11/os_x11.cpp:3842
    #22 0x184b109 in main platform/x11/godot_x11.cpp:55
    #23 0x7fe77bca2d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

```

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### LINKED ISSUE #60468: `OS.get_screen_size` causes memory leak
### Godot version

3.5 beta 4

### System information

Ubuntu 22.04, Intel HD 3000

### Issue description

```
	var temp_variable1 = ClassDB.instance("_OS")
	temp_variable1.get_screen_size(12)
	temp_variable1.get_screen_size(8)
	temp_variable1.free()
```
```
Direct leak of 24 byte(s) in 2 object(s) allocated from:
    #0 0x7fc6ad58c868 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7fc6ad46fa7d in XineramaQueryScreens (/lib/x86_64-linux-gnu/libXinerama.so.1+0x1a7d)
    #2 0x1373132d in _OS::get_screen_size(int) const core/bind/core_bind.cpp:299
    #3 0xefd8e03 in MethodBind1RC<Vector2, int>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:1305
    #4 0x12ab065a in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:918
    #5 0x12aae1a3 in Object::callv(StringName const&, Array const&) core/object.cpp:827
    #6 0x12b17f86 in MethodBind2R<Variant, StringName const&, Array const&>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:1681
    #7 0x12ab065a in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:918
    #8 0x12d53970 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1185
    #9 0x1f0b241 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1048
    #10 0x1d399f3 in GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) modules/gdscript/gdscript.cpp:1196
    #11 0x12ab01c7 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:899
    #12 0x12d53970 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1185
    #13 0x1f0b2c2 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1050
    #14 0x1d39f09 in GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1211
    #15 0xcf19d65 in Node::_notification(int) scene/main/node.cpp:56
    #16 0x1bdfc0f in Node::_notificationv(int, bool) scene/main/node.h:45
    #17 0x12ab0af6 in Object::notification(int, bool) core/object.cpp:927
    #18 0xd0596df in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:1057
    #19 0xd048a62 in SceneTree::idle(float) scene/main/scene_tree.cpp:596
    #20 0x1a18d22 in Main::iteration() main/main.cpp:2271
    #21 0x18e7b7b in OS_X11::run() platform/x11/os_x11.cpp:3842
    #22 0x184b109 in main platform/x11/godot_x11.cpp:55
    #23 0x7fc6ac93bd8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

```

Looks like pointer is not freed in case of error
https://github.com/godotengine/godot/blob/3ba980379dfb72f5d238640835d8e77c76cf3c99/platform/x11/os_x11.cpp#L1273-L1279

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### LINKED ISSUE #60469: `OS.get_screen_position` causes memory leak
### Godot version

3.5 beta 4

### System information

Ubuntu 22.04, Intel HD 3000

### Issue description

```
	var temp_variable1 = ClassDB.instance("_OS")
	temp_variable1.get_screen_position(-45)
	temp_variable1.get_screen_position(87)
	temp_variable1.free()
```

```
Direct leak of 24 byte(s) in 2 object(s) allocated from:
    #0 0x7f3de2106868 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f3de1fe9a7d in XineramaQueryScreens (/lib/x86_64-linux-gnu/libXinerama.so.1+0x1a7d)
    #2 0x13731149 in _OS::get_screen_position(int) const core/bind/core_bind.cpp:295
    #3 0xefd8e03 in MethodBind1RC<Vector2, int>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:1305
    #4 0x12ab065a in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:918
    #5 0x12aae1a3 in Object::callv(StringName const&, Array const&) core/object.cpp:827
    #6 0x12b17f86 in MethodBind2R<Variant, StringName const&, Array const&>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:1681
    #7 0x12ab065a in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:918
    #8 0x12d53970 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1185
    #9 0x1f0b241 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1048
    #10 0x1d399f3 in GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) modules/gdscript/gdscript.cpp:1196
    #11 0x12ab01c7 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:899
    #12 0x12d53970 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1185
    #13 0x1f0b2c2 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1050
    #14 0x1d39f09 in GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1211
    #15 0xcf19d65 in Node::_notification(int) scene/main/node.cpp:56
    #16 0x1bdfc0f in Node::_notificationv(int, bool) scene/main/node.h:45
    #17 0x12ab0af6 in Object::notification(int, bool) core/object.cpp:927
    #18 0xd0596df in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:1057
    #19 0xd048a62 in SceneTree::idle(float) scene/main/scene_tree.cpp:596
    #20 0x1a18d22 in Main::iteration() main/main.cpp:2271
    #21 0x18e7b7b in OS_X11::run() platform/x11/os_x11.cpp:3842
    #22 0x184b109 in main platform/x11/godot_x11.cpp:55
    #23 0x7f3de14b5d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

```

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by timothyqiu**
Fixes #60467
Fixes #60468
Fixes #60469

### CODE REVIEW

File: platform/x11/os_x11.cpp [hunk 1]
```diff
@@ -1273,7 +1276,10 @@ Size2 OS_X11::get_screen_size(int p_screen) const {
 	XineramaScreenInfo *xsi = XineramaQueryScreens(x11_display, &count);
 
 	// Check if screen is valid
-	ERR_FAIL_INDEX_V(p_screen, count, Size2i(0, 0));
+	if (p_screen < 0 || p_screen >= count) {
+		XFree(xsi);
+		ERR_FAIL_V_MSG(Point2i(0, 0), vformat("Index %d is out of bounds (count = %d)", p_screen, count));
```
Comment (akien-mga) [inline platform/x11/os_x11.cpp:1281]: Should be `Size2i` (same as `Point2i` but for consistency with the previous code). It's weird that these return int variants while the signature uses float ones though.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
