### PR TITLE
gltf: Add GLTFHandleBinary::HANDLE_BINARY_EMBED_AS_UNCOMPRESSED

### LINKED ISSUE #72191: GLTF Importer doesn't use the Project's Import settings when extracting its embedded textures.
### Godot version

v4.0.beta.custom_build [705273140]

### System information

windows 10

### Issue description

When importing a gltf file with embedded textures, godot will extract these textures, however it won't use the Project's Import settings, resulting in the textures looking compressed and messed up.
Also it creates a image file in the project- I don't remember it doing this before(it would just keep it embedded I think).

### Steps to reproduce

open project, check the included gltf file. See how it doesn't adhere to the project's import settings for texture2d. Instead it is all compressed and messed up.

### Minimal reproduction project

[gltf import bug.zip](https://github.com/godotengine/godot/files/10521850/gltf.import.bug.zip)

### LINKED ISSUE #72195: Opening GLTF Importer causes embedded textures to become unintentionally extracted
### Godot version

v4.0.beta.custom_build [705273140]

### System information

windows 10

### Issue description

When double-clicking a gltf file in the project, the Importer panel will open, but it will also extract the embedded textures.
This never happened in the previous version I was using (I'm not sure which beta I was using last- maybe 13 or 14).

### Steps to reproduce

open the project, and double-click the gltf file to open the importer, see that it creates an image file when it should stay embedded.

### Minimal reproduction project

[gltf import bug.zip](https://github.com/godotengine/godot/files/10522127/gltf.import.bug.zip)

### LINKED ISSUE #72200: GLTF Fatal error: Attempted to read or write protected memory. (C#)
### Godot version

4.0b16

### System information

Windows 11

### Issue description

Godot game (not the editor) crashes by loading a specific ".glb" model via `Godot.GltfDocument.AppendFromFile` (in C#, not tested in GDScript). The model is exported via Blender, and runs on Godot 4.0 Beta 15 without any problems.

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication t.
   at Godot.NativeInterop.NativeFuncs.godotsharp_method_bind_ptrcall(IntPtr, IntPtr, Void**, Void*)
   at Godot.NativeCalls.godot_icall_4_467(IntPtr, IntPtr, System.String, IntPtr, UInt32, System.String)
   at Godot.GltfDocument.AppendFromFile(System.String, Godot.GltfState, UInt32, System.String)
   at dummy_scene._Ready()
   at Godot.Node.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name ByRef, Godot.NativeInterop.NativeVariantPt)
   at Godot.Node3D.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name ByRef, Godot.NativeInterop.NativeVariant)
   at dummy_scene.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name ByRef, Godot.NativeInterop.NativeVariantP)
   at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr, Godot.NativeInterop.godot_string_name*, Godot.NativeInterop.godot_v)
```

image

### Steps to reproduce

Run the dummy scene with affected GLTF code. (See MRP.)

### Minimal reproduction project

C# proj [Godot 4 b16 GLTF Crash.zip](https://github.com/godotengine/godot/files/10522482/Godot.4.b16.GLTF.Crash.zip)

GDScript proj [Godot.4.b16.GLTF.Crash.gdscript.zip](https://github.com/godotengine/godot/files/10543553/Godot.4.b16.GLTF.Crash.gdscript.zip)

### LINKED ISSUE #72467: The GLTF importer crashes the engine when loading models at runtime
### Godot version

4.0.dev.935a6ef46b7c6af4239b6adce41b8198f051b57a

### System information

macOS 13.1

### Issue description

The GLTF importer crashes the engine when importing models from a file at runtime.

I have not traced the issue fully yet, but it was introduced sometime in the last 5 days, between d1e5903c67956707948b1de370b807e3aad395b7 and 935a6ef46b7c6af4239b6adce41b8198f051b57a

```
  ================================================================
  handle_crash: Program crashed with signal 11
  Engine version: Godot Engine v4.0.beta.mirror (024c2181d5173f5b4ebf202dd3252b488ec34bc4)
  Dumping the backtrace. Please include this when reporting the bug to the project developer.
  [1] 1   libsystem_platform.dylib            0x00000001854632a4 _sigtramp + 56
  [2] GLTFDocument::_parse_images(Ref<GLTFState>, String const&) (in godot.macos.editor.arm64) + 9080
  [3] GLTFDocument::_parse_gltf_state(Ref<GLTFState>, String const&) (in godot.macos.editor.arm64) + 684
  [4] GLTFDocument::_parse(Ref<GLTFState>, String, Ref<FileAccess>) (in godot.macos.editor.arm64) + 1976
  [5] GLTFDocument::append_from_file(String, Ref<GLTFState>, unsigned int, String) (in godot.macos.editor.arm64) + 780
```

Full stack trace:

<details>

```
  ================================================================
  handle_crash: Program crashed with signal 11
  Engine version: Godot Engine v4.0.beta.mirror (024c2181d5173f5b4ebf202dd3252b488ec34bc4)
  Dumping the backtrace. Please include this when reporting the bug to the project developer.
  [1] 1   libsystem_platform.dylib            0x00000001854632a4 _sigtramp + 56
  [2] GLTFDocument::_parse_images(Ref<GLTFState>, String const&) (in godot.macos.editor.arm64) + 9080
  [3] GLTFDocument::_parse_gltf_state(Ref<GLTFState>, String const&) (in godot.macos.editor.arm64) + 684
  [4] GLTFDocument::_parse(Ref<GLTFState>, String, Ref<FileAccess>) (in godot.macos.editor.arm64) + 1976
  [5] GLTFDocument::append_from_file(String, Ref<GLTFState>, unsigned int, String) (in godot.macos.editor.arm64) + 780
  [6] GLTFDocument::_parse_gltf_extensions(Ref<GLTFState>)
  [7] GLTFDocument::_parse_gltf_extensions(Ref<GLTFState>)
  [8] GLTFDocument::_parse_gltf_extensions(Ref<GLTFState>)
  [9] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (in godot.macos.editor.arm64) + 73812
  [10] Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) (in godot.macos.editor.arm64) + 228
  [11] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (in godot.macos.editor.arm64) + 63144
  [12] GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) (in godot.macos.editor.arm64) + 348
  [13] Object::callp(StringName const&, Variant const**, int, Callable::CallError&) (in godot.macos.editor.arm64) + 188
  [14] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (in godot.macos.editor.arm64) + 176
  [15] CallableCustomBind::call(Variant const**, int, Variant&, Callable::CallError&) const (in godot.macos.editor.arm64) + 452
  [16] core_bind::Thread::_start_func(void*) (in godot.macos.editor.arm64) + 552
  [17] Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) (in godot.macos.editor.arm64) + 176
  [18] Thread::~Thread()
  [19] 19  libsystem_pthread.dylib             0x000000018543506c _pthread_start + 148
```

</details>

### Steps to reproduce

Occurs when importing GLTF models at runtime. The same models import correctly when placed in the `res://` folder and imported by the editor. I will try to isolate this to a single model (or maybe it occurs on all? dunno yet).

### Minimal reproduction project

It occurs on my company's project, I will try to reproduce it in a smaller project, but wanted to open this issue ASAP in case someone already has an idea of what would be causing this.

### PR DESCRIPTION
**Pull request by lyuma**
This option allows for a safe fallback for embedded gltf textures in cases where VRAM compression is not needed.
Add an is_editor_hint guard around GLTFHandleBinary::HANDLE_BINARY_EXTRACT_TEXTURES, to use EMBED_AS_UNCOMPRESSED by default at runtime.
This provides an option for pixel art to be stored losslessly.
Additionally, respect project importer defaults for texture import settings.
Threw in another check to avoid overwriting and reimporting textures which were already extracted & identical to what is on disk.

editor import settings showing new embed as uncompressed option

Fixes #72200
Fixes #72195
Fixes #72467
Fixes #72191

### CODE REVIEW

File: modules/gltf/gltf_state.h [hunk 1]
```diff
@@ -108,6 +108,7 @@ class GLTFState : public Resource {
 		HANDLE_BINARY_DISCARD_TEXTURES = 0,
 		HANDLE_BINARY_EXTRACT_TEXTURES,
 		HANDLE_BINARY_EMBED_AS_BASISU,
+		HANDLE_BINARY_EMBED_AS_UNCOMPRESSED,
```
Comment (akien-mga) [inline modules/gltf/gltf_state.h:111]: Probably needs a comment that if the enum value changes, the 3 hardcore in core needs to be changed too.

Comment (lyuma) [reply modules/gltf/gltf_state.h]: I'll add a comment. It's still a bit icky

File: modules/gltf/editor/editor_scene_importer_gltf.cpp [hunk 2]
```diff
@@ -87,7 +87,7 @@ Node *EditorSceneFormatImporterGLTF::import_scene(const String &p_path, uint32_t
 
 void EditorSceneFormatImporterGLTF::get_import_options(const String &p_path,
 		List<ResourceImporter::ImportOption> *r_options) {
-	r_options->push_back(ResourceImporterScene::ImportOption(PropertyInfo(Variant::INT, "meshes/handle_gltf_embedded_images", PROPERTY_HINT_ENUM, "Discard All Textures,Extract Textures,Embed As Basis Universal", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_UPDATE_ALL_IF_MODIFIED), GLTFState::HANDLE_BINARY_EXTRACT_TEXTURES));
+	r_options->push_back(ResourceImporterScene::ImportOption(PropertyInfo(Variant::INT, "meshes/handle_gltf_embedded_images", PROPERTY_HINT_ENUM, "Discard All Textures,Extract Textures,Embed As Basis Universal,Embed as Uncompressed", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_UPDATE_ALL_IF_MODIFIED), GLTFState::HANDLE_BINARY_EXTRACT_TEXTURES));
```
Comment (reduz) [inline modules/gltf/editor/editor_scene_importer_gltf.cpp:90]: Please add a GLTF section for this, such as:
`gltf/embedded_image_handling` instead of taking over the mesh section.

**Review by reduz — CHANGES_REQUESTED** [review]

File: modules/gltf/editor/editor_scene_importer_gltf.cpp (hunk 2 above)
Comment (lyuma) [reply modules/gltf/editor/editor_scene_importer_gltf.cpp]: I changed it to use this name

**Comment by lyuma** [comment]
Updated the PR to also respect project import defaults. It will reimport them with Detect 3D after the gltf completes, which should be okay since it will run multithreaded, and avoids some hardcoded constants.

The original code set "compress/mode" to 2 but wrote remap instead of params, so it didn't actually work. Now that I'm reading the project defaults, there isn't a clean way to override the compression mode without disregarding the user's project settings, so I removed that part.

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
