### PR TITLE
Stop NodeRef highlighting if you start with a number

### LINKED ISSUE #70843: Syntax highlighting highlights `$` syntax on node names starting with a number, despite not being valid identifiers
### Godot version

Godot Engine v4.0.beta10.official.d0398f62f

### System information

Windows 10

### Issue description

Even though the syntax highlighting is correct, the following errors are raised, unless quotes are used.

`Expected node path as string or identifier after "$".`
`Invalid numeric notation.`
`Expected statement, found "Literal" instead.`

### Steps to reproduce

1. Add a node named "2D" to the scene
2. In a script, use `$2D`
3. The errors above are shown, even though the highlighting works fine

### Minimal reproduction project

[node-starts-with-number.zip](https://github.com/godotengine/godot/files/10332763/node-starts-with-number.zip)

### PR DESCRIPTION
**Pull request by MewPurPur**
Fixes #70843

image

Also modernizes the comments style in the highlighter file. (the fix itself is only one line diff)

### CODE REVIEW

File: modules/gdscript/editor/gdscript_highlighter.cpp [hunk 1]
```diff
@@ -465,7 +465,8 @@ Dictionary GDScriptSyntaxHighlighter::_get_line_syntax_highlighting_impl(int p_l
 
 		if (!in_node_ref && in_region == -1 && (str[j] == '$' || (str[j] == '%' && !is_binary_op))) {
 			in_node_ref = true;
-		} else if (in_region != -1 || (is_a_symbol && str[j] != '/' && str[j] != '%')) {
+		} else if (in_region != -1 || (is_a_symbol && str[j] != '/' && str[j] != '%') || (is_a_digit && j > 0 && (str[j - 1] == '$' || str[j - 1] == '/' || str[j - 1] == '%'))) {
```
Comment (akien-mga) [inline modules/gdscript/editor/gdscript_highlighter.cpp:468]: I'm not familiar with that code, but isn't it possible to rely on the same method that guarantees a valid identifier for nodes to do the completion, instead of reimplementing it?
We have `String::is_valid_identifier()` which I think handles this, though not 100% it's consistent with what is done here, or what `Node::validate_child_name()` does.

Comment (MewPurPur) [reply modules/gdscript/editor/gdscript_highlighter.cpp:468]: Valid node names are not valid identifiers, however, only valid identifiers are allowed in node refs (I think it's to make parsing easier - since many of the allowed symbols have special meanings in GDScript.)

Either way, it'd be more inconvenient to do that, since this part of the highlighter works character by character to figure out if it should flip bools.

Comment (akien-mga) [reply modules/gdscript/editor/gdscript_highlighter.cpp:468]: Makes sense. You might be interested in checking if `core/string/char_utils.h` has useful functions to reuse in this parser, but this PR can be merged as is in the meantime.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
