### PR TITLE
Use the new API for virtual keyboard height detection on Android, bugfix for old API

### LINKED ISSUE #41388: The android's virtual keyboard & the navigation bar height isn't calculated correctly.
___

***Bugsquad edit:** This bug has been confirmed several times already. No need to confirm it further.*

___

**Godot version:**

3.2 branch tip 9bf5a0b791faf8e960bdb07009b5fe8003206e4f

**Issue description:**

The height of the virtual keyboard `OS.get_virtual_keyboard_height()` 
isn't calculated correctly if it is above the Android navigation bar.

This happens in the smartphone in portrait format, on the tablet in portrait and landscape format.

Fortunately it is possible to craft some workaround for the issue. You get the negative
height of the **navigation bar** when you close the keyboard (see the first screenshot).

There have been attempts by @pouleyKetchoupp to fix this. The related PR was reverted due
to bad side effects. https://github.com/godotengine/godot/pull/40672

**Steps to reproduce:**

<details><summary>Screenshots</summary><p>

vkb_height_test

grafik

</p></details>

**Minimal reproduction project:**

[vkb_height_test.zip](https://github.com/godotengine/godot/files/5100303/vkb_height_test.zip)
[apk-app.zip](https://github.com/godotengine/godot/files/5100304/app.zip)

### PR DESCRIPTION
**Pull request by necrashter**
Uses the new [`WindowInsetsAnimation.Callback`](https://developer.android.com/reference/android/view/WindowInsetsAnimation.Callback?hl=en) to get the virtual keyboard height on Android 11 or above. We can now get the interpolated height values as the animation plays, which allows us to synchronize UI with the keyboard animation. The implementation is based on [this guide on Android Blog](https://developer.android.com/develop/ui/views/layout/sw-keyboard).

Uses the old approach when API level 30 is not available. However, I updated the old code to fix #41388. It works by subtracting the visible height from view height. Also it doesn't create a new `Rect` on each callback anymore, decreasing the load on JVM GC.

I tested both APIs on Galaxy Note 10 Lite running Android 13 (features a navbar) in portrait orientation. (Sensor orientation seems to be broken when switching to landscape, will look into it later.)

A basic test project:
[keyboard_test.zip](https://github.com/godotengine/godot/files/10889787/keyboard_test.zip)

Minor changes are required to apply this PR for the 3.x branch. 3.x version: #74399. I will update it if we make changes here.

Pinging @m4gr3d since he assigned himself to #41388.

### CODE REVIEW

File: platform/android/java/lib/src/org/godotengine/godot/Godot.java [hunk 1]
```diff
@@ -291,14 +295,64 @@ private boolean onVideoInit() {
...
+					WindowInsetsAnimation imeAnimation = null;
+					for (WindowInsetsAnimation animation : list) {
+						if ((animation.getTypeMask() & WindowInsets.Type.ime()) != 0) {
+							imeAnimation = animation;
+							break;
+						}
+					}
+					// Update keyboard height based on IME animation.
+					if (imeAnimation != null) {
+						float f = imeAnimation.getInterpolatedFraction();
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/Godot.java:329]: Can you use a full variable name here (e.g: `interpolatedFraction`).

**Review by m4gr3d — APPROVED** [review]
Looks good!

Left a minor comment, should be good to merge after addressing it.

**Comment by akien-mga** [comment]
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by necrashter** [comment]
Sorry about creating a fixup commit, I'm not used to this workflow yet. The fixup commit is squashed into the first commit now. Will do the same on 3.x version.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.2.
