### PR TITLE
[Windows] Improve frame pacing by busy waiting as needed

### LINKED ISSUE #99728: `Engine.max_fps` has bad frame pacing due to inaccurate OS sleep functions
### Tested versions

- Reproducible in: 4.3.stable, 4.4.dev5

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 32.0.15.6603) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

`Engine.max_fps` has bad frame pacing due to inaccurate OS sleep functions. This means the built-in FPS limiter isn't as stable as external solutions such as RTSS or Special K can be. This in turn leads to a bad player experience.

This is most noticeable on Windows where its sleep functions are known to be inaccurate compared to other operating systems. Nonetheless, even on other OSes, frametime graphs aren't quite a flat line even when the CPU and GPU are far from being fully utilized.

Possible avenues for improving this include:

- Perform hybrid busywaiting and sleeping, so we get more precise sleep durations but without increasing CPU utilization too much.
- On Windows 10 1803 and later, use `CREATE_WAITABLE_TIMER_HIGH_RESOLUTION ` as mentioned in https://blog.bearcats.nl/perfect-sleep-function/.

With good frame pacing, the graph should look like this:

Screenshot 2024-11-16 154908

But in `master`, it looks like this instead:

Screenshot 2024-11-16 154705

See https://github.com/godotengine/godot/pull/99178 and https://github.com/godotengine/godot/pull/99656.

### Steps to reproduce

Run the MRP and look at the frametime graph with various `Engine.max_fps` values.

### Minimal reproduction project (MRP)

[test-frame-pacing.zip](https://github.com/user-attachments/files/17786922/test-frame-pacing.zip)

### PR DESCRIPTION
**Pull request by Faless**
Apply a solution similar to the one in https://github.com/godotengine/godot/pull/99178 to the frame delay function only.

Fixes #99728 (implemented for windows only as describe in https://github.com/godotengine/godot/issues/99728#issuecomment-2504866896 since other platform doesn't seem affected).

### CODE REVIEW

File: platform/windows/os_windows.cpp [hunk 1]
```diff
@@ -2223,6 +2231,46 @@ String OS_Windows::get_system_ca_certificates() {
...
+		if (current_ticks < (target_ticks - delay_resolution)) {
+			delay_usec((target_ticks - delay_resolution) - current_ticks);
+		}
+		// Busy wait for the remainder of time.
+		while (get_ticks_usec() < target_ticks) {
+			YieldProcessor();
+		}
+
+		current_ticks = get_ticks_usec();
+		target_ticks = MIN(MAX(target_ticks, current_ticks - dynamic_delay), current_ticks + dynamic_delay);
```
Comment (clayjohn) [inline platform/windows/os_windows.cpp:2270]: Since we are busy waiting we can just avoid this logic entirely. `target_ticks` will always get set to itself here. 

A nice bonus is there is no point in tracking `current_ticks` or `target_ticks` across frames anymore

Comment (Faless) [reply platform/windows/os_windows.cpp]: > A nice bonus is there is no point in tracking `current_ticks` or `target_ticks` across frames anymore

Don't we still want to keep track of the `target_ticks` across frames so that any time spent actually producing the frame is not added to the next frame delay?

Comment (clayjohn) [reply platform/windows/os_windows.cpp]: Hmmm, yes thats right. Good point.

**Review by clayjohn — APPROVED** [review]
The changes look good to me. This seems to cover the most needed changes from https://github.com/godotengine/godot/pull/99178 and https://github.com/godotengine/godot/pull/99656 (leaving out the changes intended for Unix).

I tested locally and confirmed that this is working correctly.

**Comment by akien-mga** [comment]
Thanks!
