### PR TITLE
Need to use GL_RGB8 and GL_RGBA8 as the internal format for GLES2

### LINKED ISSUE #33705: GLES2 GL_RGB buffer breaks OpenVR
**Godot version:**
Commit # 35444576ff684aebb0133d46495be85d3d434900 but seems to have changed in Godot 3.2 some time ago

**OS/device including version:**
Tested on Windows, but any OpenVR capable OS will exhibit this

**Issue description:**
In Godot 3.2 the code here was changed:
https://github.com/godotengine/godot/blob/master/drivers/gles2/rasterizer_storage_gles2.cpp#L4587
We now create a GL_RGB buffer if we're not using a transparent background. In Godot 3.1 we always created an GL_RGBA buffer regardless. 

When sending the render output to OpenVR, GL_RGB is not a supported format, likely because the 24bit color buffer is more inefficient then a 32bit color buffer (data alignment wise)

I'm wondering if there is a good reason to use GL_RGB here other than slightly less memory usage (if the hardware doesn't decide to use a 32bit based buffer anyway)?

I'd hate to introduce a new switch to force GL_RGBA...

While I think its unrelated it is also interesting to note that the texture object returned for the viewport always assumes GL_RGBA:
https://github.com/godotengine/godot/blob/master/drivers/gles2/rasterizer_storage_gles2.cpp#L4679

**Steps to reproduce:**
Run the OpenVR demo project in GLES2 mode (https://github.com/godotvr/godot_openvr)

**Minimal reproduction project:**
https://github.com/godotvr/godot_openvr

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Found out that using GL_RGB doesn't always properly get resolved and gave problems when the render buffer was used in for instance OpenGL. Also the texture definition didn't apply the correct formatting, not sure of the impact of that.

Anyway, using GL_RGB8 (and also using GL_RGBA8 instead of GL_RGBA) for the internal format seems to be the correct thing to do.

Fixes #33705
And https://github.com/GodotVR/godot_openvr/issues/70

### CODE REVIEW

File: drivers/gles2/rasterizer_storage_gles2.cpp [hunk 1]
```diff
@@ -4583,13 +4583,16 @@ void RasterizerStorageGLES2::_render_target_allocate(RenderTarget *rt) {
...
+	Image::Format image_format;
 
 	if (rt->flags[RasterizerStorage::RENDER_TARGET_TRANSPARENT]) {
-		color_internal_format = GL_RGBA;
+		color_internal_format = GL_RGBA8;
 		color_format = GL_RGBA;
+		image_format = Image::FORMAT_RGBA8;
 	} else {
-		color_internal_format = GL_RGB;
+		color_internal_format = GL_RGBA;
```
Comment (clayjohn) [inline drivers/gles2/rasterizer_storage_gles2.cpp]: Should this be GL_RGB8?

**Comment by clayjohn** [comment]
After looking a little bit I realized that ES 2.0 base spec doesn't guaranteed that sized internal formats are available. 

For now maybe we need to do GL_RGB8 on desktop and GL_RGB on mobile (and maybe web)

File: drivers/gles2/rasterizer_storage_gles2.cpp [hunk 2]
```diff
@@ -4676,10 +4679,10 @@ void RasterizerStorageGLES2::_render_target_allocate(RenderTarget *rt) {
 			return;
 		}
 
-		texture->format = Image::FORMAT_RGBA8;
-		texture->gl_format_cache = GL_RGBA;
+		texture->format = image_format;
+		texture->gl_format_cache = color_format;
 		texture->gl_type_cache = GL_UNSIGNED_BYTE;
-		texture->gl_internal_format_cache = GL_RGBA;
+		texture->gl_internal_format_cache = color_internal_format;
```
Comment (akien-mga) [inline drivers/gles2/rasterizer_storage_gles2.cpp]: Maybe that part is what's actually making things work? i.e. you wouldn't have to specify `8`, but you do need to use the proper `GL_RGB` or `GL_RGBA` matching what's defined above?

Comment (BastiaanOlij) [reply drivers/gles2/rasterizer_storage_gles2.cpp]: no, tried it just by changing the GL_RGB8 setting, that was what made the difference. The rest I changed just to clean stuff up

**Comment by BastiaanOlij** [comment]
> 
> 
> After looking a little bit I realized that ES 2.0 base spec doesn't guaranteed that sized internal formats are available.
> 
> For now maybe we need to do GL_RGB8 on desktop and GL_RGB on mobile (and maybe web)

Looks like it, CI failed on that. I'll change it accordingly

File: drivers/gles2/rasterizer_storage_gles2.cpp (hunk 1 above)
Comment (BastiaanOlij) [reply drivers/gles2/rasterizer_storage_gles2.cpp]: yup, that is what you get when you make the last changes early in the morning while rushing to work :)

File: drivers/gles2/rasterizer_storage_gles2.cpp [hunk 3]
```diff
@@ -4583,13 +4583,24 @@ void RasterizerStorageGLES2::_render_target_allocate(RenderTarget *rt) {
 	GLuint color_internal_format;
 	GLuint color_format;
 	GLuint color_type = GL_UNSIGNED_BYTE;
+	Image::Format image_format;
 
 	if (rt->flags[RasterizerStorage::RENDER_TARGET_TRANSPARENT]) {
+#if defined(ANDROID_ENABLED) || defined(IPHONE_ENABLED)
```
Comment (akien-mga) [inline drivers/gles2/rasterizer_storage_gles2.cpp]: What about WebGL? Shouldn't this be `#ifndef GLES_OVER_GL`?

Comment (akien-mga) [reply drivers/gles2/rasterizer_storage_gles2.cpp]: Yeah looks like WebGL 1.0 also doesn't support `GL_RGBA8`:
https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texImage2D

Comment (BastiaanOlij) [reply drivers/gles2/rasterizer_storage_gles2.cpp]: sure, but I like #ifdef better so I'll swap em around :)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
