### PR TITLE
Android: Fix parsing `keep_screen_on` setting

### LINKED ISSUE #67034: "Keep Screen On" not working as expected on Android
### Godot version

4.0 Beta 2

### System information

Ubuntu 16.04

### Issue description

**Keep Screen On** option in **Project Settings > Display > Window** has no effect on exported Android builds. The issue was present from the first **Alpha** release of Godot 4.0 that I tested (**4.0 Alpha 6**)

### Steps to reproduce

1. Create a mobile project, got to **Project Settings > Display > Window**. Check **Keep Screen On** option. 
2. Export and run the project on Android device. 
3. The screen turns off after default screen timeout of Android.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by akien-mga**
Boolean stringification changed in Godot 4.0.

- Fixes #67034.
Tested on Xiaomi Pocophone F1.

Co-authored-by: @Calinou

### CODE REVIEW

File: platform/android/java/lib/src/org/godotengine/godot/Godot.java [hunk 1]
```diff
@@ -299,7 +299,7 @@ private boolean onVideoInit() {
 			for (GodotPlugin plugin : pluginRegistry.getAllPlugins()) {
 				plugin.onRegisterPluginWithGodotNative();
 			}
-			setKeepScreenOn("True".equals(GodotLib.getGlobal("display/window/energy_saving/keep_screen_on")));
+			setKeepScreenOn("true".equals(GodotLib.getGlobal("display/window/energy_saving/keep_screen_on")));
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/Godot.java:302]: Let's use [`Boolean.valueOf`](https://developer.android.com/reference/java/lang/Boolean#valueOf(java.lang.String)) instead. It performs a case-insensitive comparison which would avoid issues like that.
