### PR TITLE
Android: Fix joypad trigger value range

### LINKED ISSUE #79263: Controller Triggers stay pressed on Android
### Godot version

4.1.stable

### System information

Android 12, OneUI 4.1, Galaxy S10e | Godot 4.1.stable

### Description
On Android, Controller Triggers once pressed, stay pressed until the game is restarted 

### Video:
On Windows - everything works as intended.
https://github.com/godotengine/godot/assets/78328941/ee7976ab-b35a-4f91-888b-f3774c42e1b0

On Android - Once a Trigger is pressed, it stays pressed (Inverted triggers is a separate issue).
https://github.com/godotengine/godot/assets/78328941/981b514a-1c17-4490-9313-f72d89dec4d4

### The Setup
Input Map
Screenshot 2023-07-09 190118

Scene
Screenshot 2023-07-09 190138
Screenshot 2023-07-09 190131

Code
Screenshot 2023-07-09 190148

### Steps to reproduce

1. Set up triggers in Input Map
2. Make them do anything...
3. Export to Android
4. Press the Trigger, and thing only happens once, even if pressed multiple times.

### Minimal reproduction project

[controller trigger test.zip](https://github.com/godotengine/godot/files/11996634/controller.trigger.test.zip)

### PR DESCRIPTION
**Pull request by johnnyw**
`Input::joy_axis` converts trigger values to be between 0.0f to 1.0f by default. This is not needed for Android, as values are already within that range, as per Android documentation: https://developer.android.com/reference/android/view/MotionEvent#AXIS_RTRIGGER

This patch prevents this conversion on Android, which caused L2 and R2 triggers to get stuck pressed. https://github.com/godotengine/godot/issues/79263

This patch is compatible with 3.x.

*Bugsquad edit:*
- Fixes #79263

### CODE REVIEW

File: platform/android/android_input_handler.cpp [hunk 1]
```diff
@@ -39,7 +39,7 @@ void AndroidInputHandler::process_joy_event(AndroidInputHandler::JoypadEvent p_e
 			Input::get_singleton()->joy_button(p_event.device, (JoyButton)p_event.index, p_event.pressed);
 			break;
 		case JOY_EVENT_AXIS:
-			Input::get_singleton()->joy_axis(p_event.device, (JoyAxis)p_event.index, p_event.value);
+			Input::get_singleton()->joy_axis(p_event.device, (JoyAxis)p_event.index, p_event.value, false);
```
Comment (akien-mga) [inline platform/android/android_input_handler.cpp:42]: Warrants adding a comment to clarify that Android axis events are already normalized.

Is that true for all axes?

Comment (johnnyw) [reply platform/android/android_input_handler.cpp]: After reading your comment, I did a bit of extra digging. It turns out, they're also already normalized on iOS. So I dug further and found that there are some Android trigger mappings that use the positive axis, and some that use the full range. I've updated the patch to take the controller mapping range into account before applying the correction. I don't have the hardware to test but I think my previous revision would have fixed some Android controllers (such as mine) and broken some others. Taking the specific device mapping into account sounds like a more robust solution.

File: core/input/input.cpp [hunk 2]
```diff
@@ -1267,6 +1268,7 @@ Input::JoyEvent Input::_get_mapped_axis_event(const JoyDeviceMapping &mapping, J
 					case TYPE_AXIS:
 						event.index = (int)binding.output.axis.axis;
 						event.value = value;
+						r_range = binding.output.axis.range;
```
Comment (akien-mga) [inline core/input/input.cpp:1271]: Isn't the switch below on `axis.range` meant to handle this exact issue already? I'm not deeply familiar with that code but I wonder why this normalisation is handled in two different locations.

Comment (johnnyw) [reply core/input/input.cpp:1271]: I'm also not super familiar with what's going on here, but my impression is that the private method is converting to match the `gamecontrollerdb.txt` entry, and `joy_axis` is normalizing consistently for 0.0 to 1.0. On Android and iOS we should be able to bypass this entirely for the triggers. I wasn't sure about the private method conversion so I didn't want to mess with it, so I figured using the binding as the source of truth for the trigger-specific normalization was a reliable way to get it working.

Maybe the private method can branch on if it's an L/R trigger inside the switch and do the proper conversion for those specific axes only once? Because it seems like the switch in `joy_axis` is correcting an error introduced by the switch in `_get_mapped_axis_event` not being specific enough.

Comment (Eoin-ONeill-Yokai) [reply core/input/input.cpp:1271]: I've tested this and it works well and makes some sense, but I'm not sure I entirely get what you mean by this comment. Are you trying to say that you're avoiding updating `gamecontrollerdb.txt` and that it isn't configured to the right axis range? Or are you trying to say that the range is correct in `gamecontrollerdb.txt` and that this PR is making sure that Godot converts from those values appropriately (which it wasn't before?)

**Review by Eoin-ONeill-Yokai — APPROVED** [review]
I've tested this and it seems to work without regression on my end while resolving the reported issue.

I'll approve it, but I don't think it should be merged until we can be sure that these changes are absolutely necessary to `core`.  [See the conversion in question here](https://github.com/godotengine/godot/pull/81322/files#r1317741084) which asks whether this is a `gamecontrollerdb.txt` accuracy issue or a failure for us to interpret it correctly.

Once that comment chain is resolved, it should be clear to merge. The code looks clean otherwise.

File: core/input/input.cpp (hunk 2 above)
Comment (johnnyw) [reply core/input/input.cpp:1271]: I believe that the `gamecontrollerdb.txt` entry is correct (I recall cross-checking across some other repos), but Godot wasn't correctly converting them specifically in the case of the triggers.

Comment (Eoin-ONeill-Yokai) [reply core/input/input.cpp:1271]: In which case then it all looks correct to me. I see that @RandomShaper has already marked it for 4.3 milestone but let's focus on getting this into 4.3/master ASAP (after 4.2 release) as it can be understandably annoying if certain controllers don't work correctly on Android. We could then introduce it as a hotfix if it checks out.

Comment (RandomShaper) [reply core/input/input.cpp:1271]: Well, we decided to lie on the (maybe too) safe side. If you have tested it and think the changes are good, let's reschedule for 4.2.

Comment (akien-mga) [reply core/input/input.cpp:1271]: This seems ok for 4.2 if we merge it now so we get at least a couple betas/RCs of testing.

**Review by akien-mga — APPROVED** [review]
Making Eoin's approval "count".

**Comment by akien-mga** [comment]
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.4.
