### PR TITLE
Android: Implement sparse bundle PCK support.

### LINKED ISSUE #6675: Could you provide the PCK encryption for building Android using non-APK extensions?
### Describe the project you are working on

I am developing a 2D game that includes a lot of scripts.

### Describe the problem or limitation you are having in your project

The game I created is about 2GB. I want to encrypt it and generate an APK file. However, when I need to encrypt the PCK file, I have to select the APK extension, which requires a secret key from the Google Play Console. But I don't want to use this key to encrypt my game, maybe for other reasons. When 4.0 removed the GD script encryption function that was present in 3.x, I wondered if it was possible to achieve encryption in 4.x without requiring the APK extension, because leaving the PCK file unencrypted would be very insecure for the game.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Can you provide an APK build that does not depend on APK expansion using GDScript encryption or other encryption methods?

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I am not very familiar with how encryption works, but I would like to have more considerations for the security of the game.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It is not possible.

### Is there a reason why this should be core and not an add-on in the asset library?

Using encryption can improve the security of the APK in Godot 4.x. If the game is not encrypted, it can be easily cracked, so I believe that using only this encryption method is insufficient for security considerations.

### LINKED ISSUE #102998: Loading patch PCK on Android with big project is slow
### Tested versions

Reproducible in: 4.4.beta [93d270693079ea7802c9e1334a2e0ecd8529eeed]

### System information

N/A

### Issue description

When loading patch PCKs on Android currently, it seems to take a long time to load the first patch when you have many files in the project, which upon investigation seems to stem from the changes made in #90425.

When profiling the MRP (consisting of 5000 barebones scene files) through Android Studio it would seem that it spends about 10-30 seconds in `PackedSourceDirectory::try_open_pack`, which is what gets run ([here](https://github.com/godotengine/godot/blob/e948f52ea93cfff23b4a24b83d310724be2fb208/core/config/project_settings.cpp#L493)) when you first load a non-main pack.

More specifically, it seems to spend a lot of time dealing with `android::ZipAssetsProvider` when doing things like `DirAccessJAndroid::dir_exists` as part of `DirAccess::open` and `DirAccessJAndroid::current_is_dir` as part of `DirAccess::get_contents`.

Here's what the flame graph of the MRP's startup looks like:

Image

Here's a bottom-up view:

Image

Here's a zoomed in view of a few `DirAccess::get_contents` calls:

Image

Here's a zoomed in view of a few `DirAccess::open` calls:

Image

### Steps to reproduce

I've included a patch PCK in the project, under `patches/patch.pck`. All it does is change the label in `main.tscn` to say "Patched" instead of "Not patched".

I've also included the script (`generate.py`) used to generate the scene files under `generated_scenes`.

1. Open the MRP
2. Deploy it on an Android device
3. Note the time it takes before you're shown `main.tscn`

### Minimal reproduction project (MRP)

[android-patch-performance.zip](https://github.com/user-attachments/files/18847761/android-patch-performance.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Allow to save pack content as individual file with a PCK metadata as a separate file.

- Should fix https://github.com/godotengine/godot/issues/102998
- Allow using encryption on Android without platform code changes (tested with APK and AAB exports).

Partially superseded https://github.com/godotengine/godot/pull/76161

Fixes https://github.com/godotengine/godot-proposals/issues/6675

### CODE REVIEW

File: core/extension/gdextension_special_compat_hashes.cpp [hunk 1]
```diff
@@ -308,7 +308,7 @@ void GDExtensionSpecialCompatHashes::initialize() {
 #endif
 	});
 	mappings.insert("EditorExportPlatform", {
-		{ "export_project_files", 425454869, 1063735070 },
+		{ "export_project_files", 425454869, 4221279123 },
```
[the remark this answers is not in the document]
Comment (bruvzg) [reply core/extension/gdextension_special_compat_hashes.cpp]: It's not. Removed.

**Comment by bruvzg** [comment]
Tested with #102998 MRP, load time with sparse PCK enabled (option in the export settings) decreased from `8570` to `10` msec.

Not sure if there are any benefits on non-Android, but I have enabled the option on all platforms, since implementation is not platform depended.

For the reference, all it is doing is saving PCK header and directory as `{name}.sparsepck` file and all other files as `{name}_{sha256-hash-of-original-name}` files in the same directory. Therefore, it avoids slow directory enumeration on Android, since file metadata and list is read `{name}.sparsepck` (which is fully loaded to memory on load).

**Comment by mihe** [comment]
It does seem to fix the MRP in #102998, which is great.

I am a bit worried about the ergonomics of this though. It seems like an easy thing to miss that you need to enable this setting if you find yourself suffering from long load times for additional PCKs on Android, which I'm assuming any sizeable project using things like patch PCKs will do eventually.

Seeing as how Android builds are (as far as I can tell) already bundling the individual files in the APK, as opposed to a single PCK file, what exactly is it that this allows you to do differently that couldn't have been done with the "non-sparse" format? Is it about having every file essentially be its own small PCK so they can be encrypted individually, or something along those lines?

Would there be any downsides to using this new format on Android? If not, maybe just having this new format be the default is preferable?

**Comment by bruvzg** [comment]
> what exactly is it that this allows you to do differently that couldn't have been done with the "non-sparse" format? Is it about having every file essentially be its own small PCK so they can be encrypted individually, or something along those lines?

If I understand correctly, seeking the one big PCK file from the APK can also be slow (not sure how relevant it is for the current Android versions). Otherwise, bundling a single non-sparse PCK into an APK should also work.

**Comment by bruvzg** [comment]
> Would there be any downsides to using this new format on Android?

I do not see any.

**Comment by mihe** [comment]
> seeking the one big PCK file from the APK can also be slow

Maybe I'm missing some obvious export setting, but when opening an exported APK, without this new setting enabled, I'm seeing all the assets laid out plainly in the `assets` folder (or rather their `*.remap` files along with a `.godot` folder).

**Comment by bruvzg** [comment]
> Maybe I'm missing some obvious export setting, but when opening an exported APK, without this new setting enabled, I'm seeing all the assets laid out plainly in the assets folder (or rather their *.remap files along with a .godot folder).

Indeed, and it is like this and not a single PCK because it was causing performance issues before.

The only difference with the new option from a current APK layout, it's not enumerating file (and getting file info) from APK, but from a PCK header.

**Comment by bruvzg** [comment]
So the storage options are:
- Full PCK cons was slow to seek / read when it is in the APK (no supported).
- Files stored in APK as is, file reads are OK, but enumeration/metadata is slow (default).
- Files stored in APK as is, but file list and metadata is stored as PCK header (this PR, a middle ground that should avoid both issues).

**Comment by mihe** [comment]
Gotcha.

I realize the encryption stuff got intertwined with this, so maybe the format proposed here is simply what has to be done if we want all of that, but would this PR be made any simpler if it had only the PCK header part (i.e. `*.sparsepck`) that instead somehow referenced the files as laid out in the current APK format?

**Comment by bruvzg** [comment]
> I realize the encryption stuff got intertwined with this

Encryption is basically a free byproduct of the format, and entirely relies on existing PCK encryption code. I have moved some related export code to exposed functions, but without it, it won't be much simpler.

**Comment by bruvzg** [comment]
> that instead somehow referenced the files as laid out in the current APK format?

It would work, the only difference is file names, I have changed it to use hash format only to avoid any potential conflicts, since multiple sparse PCKs can technically exist and be loaded at the same time.

**Comment by bruvzg** [comment]
> If not, maybe just having this new format be the default is preferable?

Changed it to be enabled by default for Android.

**Comment by mihe** [comment]
Thinking about this some more, would it simplify this PR at all (assuming that's important to begin with) if this was changed to be the only way of doing it on Android, and only on Android, and not have this be a configurable option for all platforms with a whole new file extension and whatnot? Basically just have it be an implementation detail for Android specifically I guess.

(Also, there seem to be some new conflicts here.)

**Comment by bruvzg** [comment]
> would it simplify this PR at all (assuming that's important to begin with) if this was changed to be the only way of doing it on Android, and only on Android, and not have this be a configurable option for all platforms with a whole new file extension and whatnot?

Most of the code is not platform specific, and most of the platform specific changes are for Android, on other platforms it's only one extra option, and few checks in the exporter to apply it (can be easily removed, but won't change much).

> Also, there seem to be some new conflicts here.

Rebased.

**Comment by bruvzg** [comment]
But, it is pretty much useless on desktop, so I guess it would make sense to not support it. So I have removed the option for desktops and iOS. If there's any use for it, it can be re-added later.

**Review by akien-mga — APPROVED** [review]
Code / architecture changes look great to me. 
This is now more self-contained with the sparse PCK path being an implementation detail of the Android export pipeline.

I'd still like @m4gr3d or others in @godotengine/android team to review/test and confirm that this approach is suitable for Android exports. CC @godotengine/xr too as it would affect Quest and Pico.

**Review by mihe — APPROVED** [review]
If it helps, I can confirm that this resolves the issue seen in the MRP of #102998, taking the loading of the patch down from about 12 seconds to a couple of milliseconds.

I can't spot any obvious mistakes or issues in the code, but the encryption part of it is pretty foreign to me.

File: editor/export/editor_export_platform.cpp [hunk 2]
```diff
@@ -1897,6 +1913,105 @@ Dictionary EditorExportPlatform::_save_zip_patch(const Ref<EditorExportPreset> &
...
+	if (p_enc) {
+		pack_flags |= PACK_DIR_ENCRYPTED;
+	}
+	if (p_sparse) {
+		pack_flags |= PACK_SPARSE_BUNDLE;
+	}
+	p_fd->store_32(pack_flags); // Flags.
+
+	r_file_base_ofs = p_fd->get_position();
+	p_fd->store_64(0); // Diles base offset.
```
Comment (m4gr3d) [inline editor/export/editor_export_platform.cpp]:
```suggestion
	p_fd->store_64(0); // Files base offset.
```

File: core/config/project_settings.cpp [hunk 3]
```diff
@@ -701,6 +701,11 @@ Error ProjectSettings::_setup(const String &p_path, const String &p_main_pack, b
 		}
 	}
 
+#ifdef ANDROID_ENABLED
+	// Attempt to load sparse PCK assets.
+	_load_resource_pack("res://assets.sparsepck", false, 0, true);
+#endif
+
```
Comment (m4gr3d) [inline core/config/project_settings.cpp:710]: Can you update the comment at the top of this function and reference this additional logic for Android

File: core/io/file_access_pack.cpp [hunk 4]
```diff
@@ -467,13 +469,19 @@ void FileAccessPack::close() {
...
-FileAccessPack::FileAccessPack(const String &p_path, const PackedData::PackedFile &p_file) :
-		pf(p_file),
-		f(FileAccess::open(pf.pack, FileAccess::READ)) {
-	ERR_FAIL_COND_MSG(f.is_null(), vformat("Can't open pack-referenced file '%s'.", String(pf.pack)));
+FileAccessPack::FileAccessPack(const String &p_path, const PackedData::PackedFile &p_file) {
+	pf = p_file;
+	if (pf.bundle) {
+		String simplified_path = p_path.simplify_path().trim_prefix("res://");
+		f = FileAccess::open(pf.pack.get_basename() + "_" + simplified_path.sha256_text(), FileAccess::READ);
+		off = 0;
```
Comment (m4gr3d) [inline core/io/file_access_pack.cpp]: Shouldn't this seek to the offset as done in the block below?

Comment (bruvzg) [reply core/io/file_access_pack.cpp]: For a sparse pack, offset is always zero. And newly opened `FileAccess` (previous line) will have cursor at zero.

File: core/config/project_settings.cpp (hunk 3 above)
Comment (bruvzg) [reply core/config/project_settings.cpp:710]: Done.

File: core/io/file_access_pack.cpp (hunk 4 above)
Comment (m4gr3d) [reply core/io/file_access_pack.cpp]: Can you add a comment to mention that.

File: platform/android/export/gradle_export_util.cpp [hunk 5]
```diff
@@ -172,15 +172,48 @@ Error store_string_at_path(const String &p_path, const String &p_data) {
...
+	{
+		unsigned char hash[16];
+		CryptoCore::md5(p_data.ptr(), p_data.size(), hash);
+		sd.md5.resize(16);
+		for (int i = 0; i < 16; i++) {
+			sd.md5.write[i] = hash[i];
+		}
+	}
+
+	export_data->pd.file_ofs.push_back(sd);
```
Comment (m4gr3d) [inline platform/android/export/gradle_export_util.cpp]: This looks similar to the updated logic in `save_apk_file`. Can you move the common logic into an helper method.

**Review by m4gr3d — CHANGES_REQUESTED** [review]
The flattening of the directory structure and project files rename break projects like https://github.com/GodotVR/godot-openxr-android-surface-javaclasswrapper-example

File: platform/android/export/export_plugin.cpp [hunk 6]
```diff
@@ -3988,7 +4066,69 @@ Error EditorExportPlatformAndroid::export_project_helper(const Ref<EditorExportP
...
+			if (!EditorExportPlatform::_encrypt_and_store_directory(ftmp, ed.pd, key, p_preset->get_seed(), 0)) {
+				add_message(EXPORT_MESSAGE_ERROR, TTR("Save PCK"), TTR("Can't create encrypted file."));
+				return ERR_CANT_CREATE;
+			}
+
+			Vector<uint8_t> enc_data;
+			enc_data.resize(ftmp->get_length());
+			ftmp->seek(0);
+			ftmp->get_buffer(enc_data.ptrw(), enc_data.size());
+			ftmp.unref();
```
Comment (m4gr3d) [inline platform/android/export/export_plugin.cpp]: This logic is duplicated from line 3555 to line 3611 as well, and can be wrapped up in an helper method instead.

**Review by m4gr3d — APPROVED** [review]
The code looks good and the feature works as expected from my testing, so this PR looks good to go!

Thanks for this great update!

File: platform/android/export/export_plugin.cpp (hunk 6 above)
Comment (akien-mga) [reply platform/android/export/export_plugin.cpp]: I applied @m4gr3d's cleanup from https://github.com/bruvzg/godot/pull/7 directly to this PR.

**Comment by akien-mga** [comment]
Thanks!
