### PR TITLE
[ItemList] Fix item text positions in RTL mode.

### LINKED ISSUE #77043: Changes' names don't appear in History dock when using a language other than English
### Godot version

4.1 dev2, 4.0.3

### System information

Windows 10, ryzen 5900x, radeon 6950xt (driver: 23.2.2)

### Issue description

Hello there,

I'm working on Godot editor to translate it to Arabic, but I noticed 3 or 4 bugs in History block in the editor:

- Godot history doesnt show full name for changes record.
- Sometime Godot history records a change but with "blank name".
- In 4.1 dev2: When I "**hover**" over a change name in History it (the word itself or the name of record) moves forward quickly until it disappears.
- in 4.0.3 rc1: When I "**click**" on a change in History it moves one step forward. so, one step for each click.
- Sometime when I click on a record in History, Godot crashs. I think this crash is related to these bugs.

Note: those bugs just happen in Arabic version of Godot, English version works fine.
I will attach a captured video to clarify.
Also, Im sorry to report more than a bug in one issue but they seem related.
 

https://github.com/godotengine/godot/assets/121864036/1530ef49-df4f-46db-918f-e65d8d7978f9

### Steps to reproduce

- open Godot editor (Arabic version).
- do any change on your project.
- go to History block to go back to some previous changes.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/77043

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: scene/gui/item_list.cpp [hunk 1]
```diff
@@ -1260,12 +1260,13 @@ void ItemList::_notification(int p_what) {
 						text_ofs += base_ofs;
 						text_ofs += items[i].rect_cache.position;
 
+						float text_w = width - text_ofs.x;
+						items.write[i].text_buf->set_width(text_w);
+
 						if (rtl) {
-							text_ofs.x = size.width - text_ofs.x - max_len;
+							text_ofs.x = size.width - text_ofs.x - text_w;
```
Comment (YuriSizov) [inline scene/gui/item_list.cpp:1267]: Isn't this just `size.width - width`, as `text_ofs.x` cancels itself out?

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.4.
