### PR TITLE
`MovieWriter` extension support

### LINKED ISSUE #96055: Unable to use subclassed instances of MovieWriter
### Tested versions

Reproducible in 4.3 stable

### System information

MacOs aarch64, Godot v4.3 stable

### Issue description

I was subclassing `MovieWriter` when I realized that calls to `MovieWriter::add_writer` were not adding the writer to the list of available writers when done at scene initialization. This is problematic because, to my understanding, you cannot create new MovieWriter instances prior to this step in a gdextension. 

### Steps to reproduce

- subclass MovieWriter in a gdextension that adverstises mp4 support (MRP attached)
- set the movie writer file to test.mp4 in the project settings
- try to attach it at scene load time, to my understanding, the earliest that this can be done.
- the error :  `setup2: Can't find movie writer for file type, aborting: test.mp4` should be emitted in the debugger.

### Minimal reproduction project (MRP)

The following rust plugin demonstrates the lifecycle issue https://github.com/mobile-bungalow/WriterExample.

see that[ adding the writer](https://github.com/mobile-bungalow/WriterExample/blob/9762d581020fb4f1981786d3891e27897002f465/src/lib.rs#L21) must occur prior to [loading the writer](https://github.com/godotengine/godot/blob/e3550cb20f5d6a61befaafb7d9cbdb57b24870e4/main/main.cpp#L2962).

### PR DESCRIPTION
**Pull request by mobile-bungalow**
Fixes #96055 , MPR is fixed by this PR.

In `setup2` the setup sequence for the `MovieWriter` runs before any user provided subclasses of `MovieWriter` can be inserted into the lookup table. We can't instance `MovieWriter` prior to this point because, to my knowledge, it must be instanced during scene loading. Moving the writer directly after scene gdextension initialization fixes this, but I'm unsure if it's a clean solution or if the writer is selected directly after the render server is initialized for any specific reason.

### CODE REVIEW

File: main/main.cpp [hunk 1]
```diff
@@ -3203,6 +3195,16 @@ Error Main::setup2(bool p_show_boot_logo) {
 		GDExtensionManager::get_singleton()->initialize_extensions(GDExtension::INITIALIZATION_LEVEL_SCENE);
 
 		OS::get_singleton()->benchmark_end_measure("Scene", "Modules and Extensions");
+
+		/// We need to initialize the movie writer here in case
+		/// One of the user provided gdextensions subclasses MovieWriter
```
Comment (RedMser) [inline main/main.cpp:3200]:
```suggestion
		// We need to initialize the movie writer here in case
		// one of the user provided gdextensions subclasses MovieWriter.
```

[Comment style](https://docs.godotengine.org/en/stable/contributing/development/code_style_guidelines.html#comment-style-guide)

**Comment by fire** [comment]
> Moving the writer directly after scene gdextension initialization fixes this, but I'm unsure if it's a clean solution or if the writer is selected directly after the render server is initialized for any specific reason.

Can you explain this problem more?

**Comment by RedMser** [comment]
It's likely the same as in https://github.com/godotengine/godot/pull/91374 [^1]... Wrong order of things being initialized causes the registration to fail. The change likely fixes this, but it's in main.cpp so it's scary to touch and hard to ensure it doesn't break anything.

[^1]: unrelated but @ bug squad, the linked PR is tagged "enhancement (4.x)" despite doing basically the same as this PR which is marked as "bug (4.4)" , just in another area of the code :')

**Comment by mobile-bungalow** [comment]
> Can you explain this problem more?

Sure. As it stands to use a movie writer you need to instantiate it, then call `MovieWriter::add_writer`, this inserts it into a static table. The problem is that this static table is searched for the writer before the writer can be initialized. The lowest initialization level where you can construct a `MovieWriter` is `INITIALIZATION_LEVEL_SCENE`.

I recognize that touching main is modifying a very hot, and essential code path. I would appreciate any help or alternative directions someone could take this. Other solutions I can think up don't preserve `MovieWriter` functionality as it was designed, i.e. adding API to allow the user to swap to another `MovieWriter` at recording time.

**Review by fire — APPROVED** [review]
The reasoning in the previous posts explains why the move of initialization.

Edited:

That said, we probably want to test earlier so any unintended breakage is in first part of the 4.4 cycle and not in a beta.

File: main/main.cpp [hunk 2]
```diff
@@ -3484,6 +3476,16 @@ Error Main::setup2(bool p_show_boot_logo) {
 		GDExtensionManager::get_singleton()->initialize_extensions(GDExtension::INITIALIZATION_LEVEL_SCENE);
 
 		OS::get_singleton()->benchmark_end_measure("Scene", "Modules and Extensions");
+
+		// We need to initialize the movie writer here in case
+		// one of the user provided gdextensions subclasses MovieWriter.
```
Comment (Calinou) [inline main/main.cpp:3481]:
```suggestion
		// We need to initialize the movie writer here in case
		// one of the user-provided GDExtensions subclasses MovieWriter.
```

**Review by Calinou — COMMENTED** [review]
Code looks good to me. The rationale behind this makes sense; I don't see any other way to do it.

After applying the above suggestion, please [squash commits](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase) into a single commit.

**Comment by mobile-bungalow** [comment]
All squashed, ready for CI to run.

**Review by Calinou — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
