### PR TITLE
Fix crash when reparenting `SoftBody3D` with pinned points

### LINKED ISSUE #71785: Reparenting `SoftBody3D` crashes Godot if the `SoftBody3D` has pinned points
### Godot version

Since before v4.0.alpha1.official 31a7ddbf8 (first encountered in 4.0.beta14.official 28a24639c)

### System information

Windows 10, Forward+, NVIDIA GeForce GTX 1660/PCIe/SSE2

### Issue description

Reparenting a `SoftBody3D` node may crash the editor, especially if the `SoftBody3D` has at least one pinned point attached to a `Node3D` higher up in the tree.

### Steps to reproduce

1. Unzip, import, and edit the attached project.
2. Open `main.tscn` for editing.
3. Reparent the `SoftBody3D` from the `Node3D` named "main" to the `Node3D` named "body_parent".
4. The editor crashes whilst reparenting.

### Minimal reproduction project

[Crash reparenting SoftBody3D.zip](https://github.com/godotengine/godot/files/10471423/Crash.reparenting.SoftBody3D.zip)

### PR DESCRIPTION
**Pull request by PrecisionRender**
Fixes #71785.

Moves call to `pin_point()` to a deferred function, thus preventing it from calling methods on a referenced node before it gets moved, which resulted in a null pointer.

Thanks to @YuriSizov and @rburing for the help!

### CODE REVIEW

File: scene/3d/soft_body_3d.cpp [hunk 1]
```diff
@@ -683,6 +682,11 @@ void SoftBody3D::pin_point(int p_point_index, bool pin, const NodePath &p_spatia
 	}
 }
 
+void SoftBody3D::_pin_point_deferred(int p_point_index, bool pin, const NodePath p_spatial_attachment_path) {
+	pin_point(p_point_index, true, p_spatial_attachment_path);
```
Comment (James103) [inline scene/3d/soft_body_3d.cpp:686]: Either the argument `pin` in the function signature is not needed or the value `true` in the call to `pin_point` in the function can be replaced with the argument `pin`. As it is, the `pin` argument is unused.

Comment (PrecisionRender) [reply scene/3d/soft_body_3d.cpp:686]: Oversight on my part, thanks.

Comment (James103) [reply scene/3d/soft_body_3d.cpp]: This appears to have been fixed in favor of passing the `pin` argument into `pin_point` from the deferred call function.
I'll have to test if this PR fixes the issue on the next beta/RC release after it is merged.

File: scene/3d/soft_body_3d.cpp [hunk 2]
```diff
@@ -754,8 +758,11 @@ void SoftBody3D::_add_pinned_point(int p_point_index, const NodePath &p_spatial_
 		pinned_point->spatial_attachment_path = p_spatial_attachment_path;
 
 		if (!p_spatial_attachment_path.is_empty() && has_node(p_spatial_attachment_path)) {
-			pinned_point->spatial_attachment = Object::cast_to<Node3D>(get_node(p_spatial_attachment_path));
-			pinned_point->offset = (pinned_point->spatial_attachment->get_global_transform().affine_inverse() * get_global_transform()).xform(PhysicsServer3D::get_singleton()->soft_body_get_point_global_position(physics_rid, pinned_point->point_index));
+			Node3D *attachment_node = Object::cast_to<Node3D>(get_node(p_spatial_attachment_path));
+			if (attachment_node != nullptr) {
```
Comment (rburing) [inline scene/3d/soft_body_3d.cpp:762]: The `if` statement should be replaced by an `ERR_FAIL_NULL(attachment_node)`, or by an `ERR_FAIL_NULL_MSG` if you feel inspired.

**Review by rburing — DISMISSED** [review]
After my initial comment on the issue I was hoping there would be a better way to do this. Deferring is not really ideal because setting the offset of the attachment point depends on the attachment position. On the other hand, it's probably not going to move a lot. So let's go with this solution for now (after the suggested change to use the error macro).

File: scene/3d/soft_body_3d.cpp (hunk 2 above)
Comment (PrecisionRender) [reply scene/3d/soft_body_3d.cpp]: Added.

**Review by YuriSizov — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
