### PR TITLE
[3.x] Skip rendering of `Light2D` with zero size texture

### LINKED ISSUE #41756: Light 2D causes ERROR: affine_invert: Condition ' det == 0 ' is true to spam the console.
**Godot version:**
Godot 3.2.3 RC5 Non-Mono Build
Godot 3.2.3 RC5 Mono Build

**OS/device including version:**
Windows 10 64-bit
Open GL ES 3 Renderer
Geforce GTX 1050 Ti
Intel UHD Graphics 630

**Issue description:**
An error with Transform 2D occurs and is visible in the Output Console as soon as the Project is opened - the project does not need to be run to see this error.
When the project is run the 2D graphics performance is choppy, it's not smooth like it was in RC4.
The fan also kicks into high volume with CPU utilization up to 58% and GPU utilization at 83% and Geforce GTX at 22% utilization.
Performance degrades.
Untitled
Error
High CPU/GPU utilization (with Godot's processes on):
CPU Utilization
Normal CPU/GPU Utilization (with Godot's processes killed):
Normal utilization
When loading the project using the Mono Build:
image

**Steps to reproduce:**
1) Open the included reproduction project and check the output console.
2) Then run the game and use arrow keys to see the 2D performance is affected.
3) Use CTRL+ALT+DEL, go to the Task Manager's Performance Tab and check your PCs CPU/GPU utilization.

Note: The video also shows another bug with RC4/RC5 where you cannot open GDScript using an external editor such as VS Code.

Videos:
Steps to reproduce:
https://youtu.be/c6y4EXST08M

High fan speed:
https://youtu.be/LTNcfi1Iw9k

**Minimal reproduction project:**
[2DPhysics.zip](https://github.com/godotengine/godot/files/5172275/2DPhysics.zip)

### PR DESCRIPTION
**Pull request by JestemStefan**
Fix  #41756 

Using light with not yet set texture cause spam of `det==0` error to the console both in editor and in the game. (See issue #41756).
Error is coming from no yet set texture which seems to have size of (0,0) by default.
See explanation here: https://github.com/godotengine/godot/issues/41756#issuecomment-695756032

I tried to find best solution to this and this is the simplest one. I check if `Light2D` texture have 0 size and if it does then skip rendering this light.

Attached MRP provided by original author of the issue. Issue exist in 3.3.2 and this PR fixed it.
[41756_issue_MRP.zip](https://github.com/godotengine/godot/files/6801806/41756_issue_MRP.zip)
I didn't noticed any regressions.

This issue doesn't exist in [master]

### CODE REVIEW

File: servers/visual/visual_server_viewport.cpp [hunk 1]
```diff
@@ -131,6 +131,10 @@ void VisualServerViewport::_draw_viewport(Viewport *p_viewport, ARVRInterface::E
 				if (cl->enabled && cl->texture.is_valid()) {
 					//not super efficient..
 					Size2 tsize = VSG::storage->texture_size_with_proxy(cl->texture);
+					// HACK Avoid using lights with texture of 0 size
```
Comment (akien-mga) [inline servers/visual/visual_server_viewport.cpp:134]: I don't think it's a hack, that's a correct way to fix it IMO.

**Comment by akien-mga** [comment]
Please squash the commits together, we don't want to merge fixup commits if we can have the base commit "correct" from the start :)

File: servers/visual/visual_server_viewport.cpp (hunk 1 above)
Comment (JestemStefan) [reply servers/visual/visual_server_viewport.cpp]: That's great. I updated the comment.

I thought it was kind of a hack, because it seems more like bypassing the issue (That texture with 0 size is even processed further) then actually fixing it

**Review by akien-mga — APPROVED** [review]

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
