### PR TITLE
Change ShapeCast3D and RayCast3D debug to use RenderingServer directly

### LINKED ISSUE #82586: ShapeCast creating MeshInstances when "Visible Collision Shapes" is checked
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.3623) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

Reporting as a bug since it's a similar issue to https://github.com/godotengine/godot/issues/48085 which was resolved by https://github.com/godotengine/godot/pull/48175#pullrequestreview-645745811

image

ShapeCasts (and other collision related nodes) creating MeshInstances risks them getting picked up through calls to "get_children", which can interfere with game logic. In my case, it's only causing visual issues as I am moving all children to a specific location similar but not exactly like a SpringArm, which now happens to include the debug mesh. This caused some confusion as I was wondering why my shapecast was not where it should be and negated the usefulness of the visible debug shapes.

As I understood it from the previously mentioned resolution all debug shapes should preferably be handled directly by the rendering server going forward, so I figured I'd raise this as a possible minor oversight.

Alternative solution would be to mark debug nodes somehow to make them distinguishable through code, such as using the meta field, but that feels like it introduces unnecessary logic on the part of the game that would likely end up in production.

### Steps to reproduce

Create a scene with a shapecast with any shape. Run the game and look through the Remote tree, a generated MeshInstance will be there.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by smix8**
Closes https://github.com/godotengine/godot/issues/82586

Changes `ShapeCast3D` and `RayCast3D` debug to use RenderingServer directly.

Both nodes still used the old way of adding debug visuals by adding a child MeshInstance3D node.

### CODE REVIEW

**Comment by fire** [comment]
I like this but wasn't able to give it a good review.

**Review by fire — APPROVED** [review]
The code is changed to use the new style RenderServer apis to avoid developer confusion. Looks good to me.

File: scene/3d/physics/shape_cast_3d.cpp [hunk 1]
```diff
@@ -532,13 +541,13 @@ const Color &ShapeCast3D::get_debug_shape_custom_color() const {
...
-
-	MeshInstance3D *mi = memnew(MeshInstance3D);
-	mi->set_mesh(mesh);
+	if (!debug_instance.is_valid()) {
+		debug_instance = RenderingServer::get_singleton()->instance_create();
+	}
 
-	add_child(mi);
-	debug_shape = mi;
+	if (!debug_mesh.is_valid()) {
```
Comment (AThousandShips) [inline scene/3d/physics/shape_cast_3d.cpp:548]:
```suggestion
	if (debug_mesh.is_null()) {
```

File: scene/3d/physics/shape_cast_3d.cpp [hunk 2]
```diff
@@ -588,13 +597,11 @@ void ShapeCast3D::_update_debug_shape() {
 		return;
 	}
 
-	MeshInstance3D *mi = static_cast<MeshInstance3D *>(debug_shape);
-	Ref<ArrayMesh> mesh = mi->get_mesh();
-	if (!mesh.is_valid()) {
+	if (!debug_instance.is_valid() || !debug_mesh.is_valid()) {
```
Comment (AThousandShips) [inline scene/3d/physics/shape_cast_3d.cpp:600]:
```suggestion
	if (!debug_instance.is_valid() || debug_mesh.is_null()) {
```

File: scene/3d/physics/ray_cast_3d.cpp [hunk 3]
```diff
@@ -494,19 +503,17 @@ void RayCast3D::_update_debug_shape() {
...
 
-	if (!debug_shape) {
+	if (!debug_instance.is_valid()) {
 		_create_debug_shape();
 	}
 
-	MeshInstance3D *mi = static_cast<MeshInstance3D *>(debug_shape);
-	Ref<ArrayMesh> mesh = mi->get_mesh();
-	if (!mesh.is_valid()) {
+	if (!debug_instance.is_valid() || !debug_mesh.is_valid()) {
```
Comment (AThousandShips) [inline scene/3d/physics/ray_cast_3d.cpp:510]:
```suggestion
	if (!debug_instance.is_valid() || debug_mesh.is_null()) {
```

File: scene/3d/physics/ray_cast_3d.cpp [hunk 4]
```diff
@@ -448,13 +457,13 @@ const Color &RayCast3D::get_debug_shape_custom_color() const {
...
-
-	MeshInstance3D *mi = memnew(MeshInstance3D);
-	mi->set_mesh(mesh);
+	if (!debug_instance.is_valid()) {
+		debug_instance = RenderingServer::get_singleton()->instance_create();
+	}
 
-	add_child(mi);
-	debug_shape = mi;
+	if (!debug_mesh.is_valid()) {
```
Comment (AThousandShips) [inline scene/3d/physics/ray_cast_3d.cpp:464]:
```suggestion
	if (debug_mesh.is_null()) {
```

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
