### PR TITLE
Fix method hashes with default arguments

### LINKED ISSUE #81386: MethodBind::get_hash() fails to hash default arguments
### Godot version

v4.2.dev.custom_build [8449592d9]

### System information

Godot v4.2.dev (8449592d9) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Ti (NVIDIA; 31.0.15.3713) - 13th Gen Intel(R) Core(TM) i5-13600K (20 Threads)

### Issue description

The GDExtension method hash is supposed to include the values of its default arguments. This works for methods where every argument has a default, but fails when there are some arguments without a default.

This is because `MethodBind::get_hash()` starts counting at 0:
https://github.com/godotengine/godot/blob/8449592d92eaeef990f5502b419d491ee3eeb7a6/core/object/method_bind.cpp#L49-L53

But `get_default_argument` expects the absolute index of the argument in the function signature:
https://github.com/godotengine/godot/blob/8449592d92eaeef990f5502b419d491ee3eeb7a6/core/object/method_bind.h#L82-L90

So instead of hashing the actual default value, we end up hashing a nil Variant.

Fixing this would be a major compatibility break because the method hashes will change, so it probably requires some discussion.

### Steps to reproduce

In the godot-cpp test project, add call to one of the affected methods. For example: `add_child(memnew(Node));`

Set a debugger breakpoint inside `MethodBind::get_default_argument` with a condition of `idx < 0`.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by dsnopek**
Fixes https://github.com/godotengine/godot/issues/81386

Here's the start of a fix for the incorrect method hashing from issue #81386, including a mapping system so we don't have to break compatibility.

~~This is a draft because I haven't added any of the mappings yet (still working on a script to do it), but I wanted to start trying this on CI right away.~~

~~UPDATE: The list of mappings are in now, but they're missing a couple. Just need to get the CI passing to take this out of draft.~~

### CODE REVIEW

File: core/object/method_bind.cpp [hunk 1]
```diff
@@ -47,9 +47,11 @@ uint32_t MethodBind::get_hash() const {
 	}
 
 	hash = hash_murmur3_one_32(get_default_argument_count(), hash);
-	for (int i = 0; i < get_default_argument_count(); i++) {
-		Variant v = get_default_argument(i);
-		hash = hash_murmur3_one_32(v.hash(), hash);
+	for (int i = 0; i < get_argument_count(); i++) {
```
Comment (pkdawson) [inline core/object/method_bind.cpp:50]: There are two methods which have DEFVALs but no actual arguments. Those are `DirAccess::list_dir_begin` and `DisplayServer::is_touchscreen_available`.

If we want to avoid changing those hashes, I would suggest simply:
```cpp
for (const Variant &v : get_default_arguments()) {
	hash = hash_murmur3_one_32(v.hash(), hash);
}
```

Comment (dsnopek) [reply core/object/method_bind.cpp:50]: Hm. We probably shouldn't be including default arguments that aren't paired with actual arguments in the hash in the first place. And since we're already doing a mapping here, this actually seems like a good time to break those hashes. :-)

Locally, I tested removing the invalid default arguments, and the hashes (with the new calculation in this PR) remained stable, which I think is what we want. So, we can delete those `DEFVAL()`s at anytime, and if anyone adds any default arguments without arguments in the future, they won't be counted.

**Comment by dsnopek** [comment]
This is ready for review! Tests haven't finished running yet, but everything seems good locally, so I'm expecting them to pass.

It now includes the full hash mapping, mostly generated via a script that compared the `extension_api.json` before and after changing the hash calculation. There were, unexpectedly, a few that I had to do by hand: where there was a pre-existing compatibility method, and the hash of the compatibility method would change too.

File: core/extension/compat_hashes_81386.h [hunk 2]
```diff
@@ -0,0 +1,57 @@
+/**************************************************************************/
+/*  compat_hashes_81386.h                                                 */
```
Comment (RedworkDE) [inline core/extension/compat_hashes_81386.h:2]: I would remove the PR number in the file/class name and put it into the name of the initialize method instead, as that is the only part that should need to be duplicated if this ever becomes relevant again.

(Assuming that there will be more cases where the hash has to change for some reason)

**Review by RedworkDE — COMMENTED** [review]
Generally looks good to me, but I didn't test the code.

File: core/extension/compat_hashes_81386.h (hunk 2 above)
Comment (dsnopek) [reply core/extension/compat_hashes_81386.h:2]: I was imagining that we'd make a new class if we had to do something like this again. But you're suggesting we could just re-use this same class but have individual initialize methods for each issue where we broke the hashing algorithm?

I'm a little reluctant to do this, given that we don't know what another hash breaking issue would look like. If there was another hash break, and it meant all or some the `current_hash`es listed here were now wrong, we'd have have to either (1) update all or some of the `current_hash`es for the new values (which would be a pain without scripting this process again) or (2) have the mapping for the new hash breakage run _after_ the mapping here (so, we could leave all the code added here exactly the same, but then do another mapping on the mapped value). Depending on how many hashes we're talking about, option nr 1 or 2 may appear more attractive at the time.

So, I'd prefer to leave this as it is for now, and consider changing it if/when we have to break the hashes again. But if everyone feels strongly, I'd be fine switching this around (since we could equally change it back to the way it is now if it made sense when the next issue came up :-)).

Comment (dsnopek) [reply core/extension/compat_hashes_81386.h:2]: Alright, I'll rename it in my next push :-)

Comment (dsnopek) [reply core/extension/compat_hashes_81386.h]: Renamed!

File: core/extension/extension_api_dump.cpp [hunk 3]
```diff
@@ -884,11 +885,18 @@ Dictionary GDExtensionAPIDump::generate_extension_api() {
...
 							}
+						}
+
+#ifndef DISABLE_DEPRECATED
+						GDExtensionCompatHashes::get_legacy_hashes(class_name, method_name, compatibility);
+#endif
+
+						if (compatibility.size() > 0) {
 							d2["hash_compatibility"] = compatibility;
 						}
```
Comment (Bromeon) [inline core/extension/extension_api_dump.cpp:901]: General question: with `DISABLE_DEPRECATED`, do we still write this key?
Might very well be "yes", just wanted to double-check 🙂

**Review by Bromeon — COMMENTED** [review]
Thanks for addressing this! 👍

File: core/extension/extension_api_dump.cpp (hunk 3 above)
Comment (dsnopek) [reply core/extension/extension_api_dump.cpp:901]: Hm, well, if all compatibility methods are also wrapped with `#ifdef DISABLE_DEPRECATED` then we won't have anything else to put into "hash_compatibility". But I think this is fine? The _idea_ of compatibility hashes still exists with `DISABLE_DEPRECATED`, we just aren't registering any.

**Review by BastiaanOlij — APPROVED** [review]
Reviewed during GDExtension meeting, this looks like a good way to solve the backwards compatibility issue, much better then introducing 800 compatibility calls :)

File: core/extension/gdextension_compat_hashes.cpp [hunk 4]
```diff
@@ -0,0 +1,1384 @@
...
+	{
+		Vector<Mapping> m;
+		m.resize(5);
+		m.write[0] = { "add_point", 3370185124, 4074201818 };
+		m.write[1] = { "set_point_disabled", 4023243586, 972357352 };
+		m.write[2] = { "connect_points", 3785370599, 3710494224 };
+		m.write[3] = { "disconnect_points", 3785370599, 3710494224 };
+		m.write[4] = { "are_points_connected", 4063588998, 2288175859 };
+		mappings["AStar2D"] = m;
+	}
```
[the remark this answers is not in the document]
Comment (dsnopek) [reply core/extension/gdextension_compat_hashes.cpp]: Ah, makes sense, thanks! My latest push switches to `LocalVector` and initialization lists

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
