### PR TITLE
Initialize `pa_buffer_attr.maxlength` to -1

### LINKED ISSUE #102013: Audio Mic Record Demo fails to record when debug/settings/stdout/verbose_stdout=true on Linux
### Tested versions

This problem appears in v4.4.beta1 (not in v4.4.dev7).  

### System information

Godot v4.4.beta (77dcf97d8) - NixOS #1-NixOS SMP PREEMPT_DYNAMIC Thu Sep 12 09:13:13 UTC 2024 on X11 - X11 display driver, Multi-window, 1 monitor - OpenGL 3 (Compatibility) - Mesa Intel(R) Graphics (ADL GT2) - 12th Gen Intel(R) Core(TM) i5-1240P (16 threads)

### Issue description

The suspect PR which changed some behavior of the Microphone stream was noted by me here: https://github.com/godotengine/godot/pull/101097#issuecomment-2613042635

What changed was that if you called `play()` on an already playing `AudioStreamPlayer` with an `AudioStreamMicrophone` on Linux (okay on Windows) the microphone stopped working and gave out the error:
 
> ERROR: PulseAudio: pa_stream_disconnect error: Bad state

This is probably due to the bug that allows multiple calls to the singular `AudioDriver::input_start()` (Item 1 of https://github.com/godotengine/godot/pull/100508 )

The above is just context.  

__This__ bug is about the microphone no longer working when you enable debug/settings/stdout/verbose_stdout in Linux.  I have no idea how this could be.

### Steps to reproduce

Run the demo project. https://github.com/godotengine/godot-demo-projects/tree/master/audio/mic_record

Click *Record*, say something, click *Stop*, then click *Play* to hear it back.

Now under Project Settings -> Debug -> Settings, enable `Verbose stdout`, and repeat.

Aside from now playing no sound, my output is:

```
CameraServer: Registered camera Laptop Camera: Laptop Camera with ID 1 and position 0 at index 0
Loading resource: res://default_bus_layout.tres
CORE API HASH: 3420400551
EDITOR API HASH: 33618999
Loaded system CA certificates
Loading resource: res://MicRecord.tscn
Loading resource: res://MicRecord.gd
Loading resource: res://Intro.ogg
Loading resource: res://.godot/imported/Intro.ogg-dfe75727d0e47692e220adf97ddb7ad9.oggvorbisstr
PulseAudio: Detecting channels for device: alsa_input.pci-0000_00_1f.3.analog-stereo
PulseAudio: detected 2 input channels
PulseAudio: detected 2 input channels
PulseAudio: input buffer frames: 1024 calculated latency: 23ms

Playing recording: <AudioStreamWAV#-9223372001740061239>
Format: 16-bit uncompressed
Mix rate: 44100 Hz
Stereo: Yes
Size: 159744 bytes
```

The suspicious duplication of the "detected 2 input channels" message is merely the statement appearing twice in the function.
    https://github.com/godotengine/godot/blob/master/drivers/pulseaudio/audio_driver_pulseaudio.cpp#L716

### Minimal reproduction project (MRP)

see above

### PR DESCRIPTION
**Pull request by goatchurchprime**
Fixes https://github.com/godotengine/godot/issues/102013 (and other long term unreliabilities of the pulseaudio microphone on Linux) by initializing and uninitialized buffer definition attribute to -1 as recommended here: https://maemo.org/api_refs/5.0/5.0-final/pulseaudio/structpa__buffer__attr.html

The other three attributes (tlength, prebuf, minreq) are not used by the recording feature `pa_stream_connect_record()` and probably don't have to be initialized.

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
Not an expert on the audio system so hesitant to do more than having a quick look. Reading the documentation, leaving this property uninitialized seems like a bad idea. Seeing they themselves recommend setting this to -1 so the buffer is allocated with the maximum supported size seems sound.

File: drivers/pulseaudio/audio_driver_pulseaudio.cpp [hunk 1]
```diff
@@ -726,6 +726,7 @@ Error AudioDriverPulseAudio::init_input_device() {
 	int input_buffer_size = input_buffer_frames * spec.channels;
 
 	pa_buffer_attr attr;
```
Comment (akien-mga) [inline drivers/pulseaudio/audio_driver_pulseaudio.cpp:728]: I'd suggest also zeroing the struct so at least we have sane defaults if we end up relying on some of the other struct fields.
```suggestion
	pa_buffer_attr attr = {};
```

**Review by akien-mga — APPROVED** [review]
Great find! Thanks for looking into this.

**Comment by Repiteo** [comment]
Thanks!

**Comment by lawnjelly** [comment]
Cherry-picked for 3.7.

**Comment by lawnjelly** [comment]
Cherry-picked for 3.6.1.
