### PR TITLE
Fix script previews

### LINKED ISSUE #16699: Script previews are complete black(regression from #15193)
**Godot version:**
https://github.com/godotengine/godot/commit/79f48cde3d9c47e64cca6090c3db0bff1c9e557f

**OS/device including version:**
Linux mint 18.3

**Issue description:**
image

### PR DESCRIPTION
**Pull request by Chaosus**
This should fix #16699
"text_editor/theme/" properties not even existed...

### CODE REVIEW

File: editor/plugins/editor_preview_plugins.cpp [hunk 1]
```diff
@@ -467,15 +467,6 @@ Ref<Texture> EditorScriptPreviewPlugin::generate(const RES &p_from) {
 	Color text_color = EditorSettings::get_singleton()->get("text_editor/highlighting/text_color");
 	Color symbol_color = EditorSettings::get_singleton()->get("text_editor/highlighting/symbol_color");
 
-	if (EditorSettings::get_singleton()->get("text_editor/theme/color_theme") == "Adaptive") {
-		Ref<Theme> tm = EditorNode::get_singleton()->get_theme_base()->get_theme();
-
-		bg_color = tm->get_color("text_editor/theme/background_color", "Editor");
```
Comment (akien-mga) [inline editor/plugins/editor_preview_plugins.cpp]: They should likely be fixed and not removed (`"text_editor/highlighting/background_color"`): https://github.com/godotengine/godot/blob/9f479f096cb50fa8d1215e68c262f110116114ef/editor/editor_themes.cpp#L1069

Comment (akien-mga) [reply editor/plugins/editor_preview_plugins.cpp]: CC @djrm @volzhs

Comment (Chaosus) [reply editor/plugins/editor_preview_plugins.cpp]: There is no Adaptive theme colors are existed, only the setting colors, which already setted on previous lines. The PR from poke1024 corrupt the script preview cache now for all peoples, it should be fixed ASAP..

Comment (Chaosus) [reply editor/plugins/editor_preview_plugins.cpp]: However I could change it to "text_editor/highlighting/" instead "text_editor/theme"

Comment (akien-mga) [reply editor/plugins/editor_preview_plugins.cpp]: > The PR from poke1024 corrupt the script preview cache now for all peoples, it should be fixed ASAP..

It's the master branch, there's no hurry.. If previews are broken for a couple of days and fixed automatically later on, there's no harm done.

**Comment by Chaosus** [comment]
Ok, @akien-mga, I changed it to correct view and it is working(sorry if I do so many mistakes)

**Comment by akien-mga** [comment]
No problem, you do great contributions :)
