### PR TITLE
Fix engine crashing when using Down Arrow selection on Tree with no selection

### LINKED ISSUE #92958: Engine crashes clicking the down-arrow after clicking in the File System blank area (no file selected)
### Tested versions

Reproducible in 4.3beta1 in an empty project.

### System information

Linux Mint 21.3

### Issue description

The engine will crash if you click inside the blank area inside the file system (without a file selected) and then click the down arrow once.

https://github.com/godotengine/godot/assets/122749374/398e1e99-6931-40d7-b1bc-d7f77841a8d0

Here is a verbose log for anyone interested -

ERROR: FATAL: Index p_index = -1 is out of bounds (((Vector<T> *)(this))->_cowdata.size() = 1).
   at: operator[] (./core/templates/vector.h:52)

================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.3.beta.custom_build (5833f597865c773fae3ee09fc4e31d4a243f812d)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7682ab842520] (??:0)
[2] VectorWriteProxy<TreeItem::Cell>::operator[](long) (/home/booch/Documents/GodotCompiled/godot/./core/templates/vector.h:52 (discriminator 7))
[3] Tree::select_single_item(TreeItem*, TreeItem*, int, TreeItem*, bool*, bool) (/home/booch/Documents/GodotCompiled/godot/scene/gui/tree.cpp:2674)
[4] Tree::_go_down() (/home/booch/Documents/GodotCompiled/godot/scene/gui/tree.cpp:3394)
[5] Tree::gui_input(Ref<InputEvent> const&) (/home/booch/Documents/GodotCompiled/godot/scene/gui/tree.cpp:3503)
[6] Control::_call_gui_input(Ref<InputEvent> const&) (/home/booch/Documents/GodotCompiled/godot/scene/gui/control.cpp:1828)
[7] Viewport::_gui_input_event(Ref<InputEvent>) (/home/booch/Documents/GodotCompiled/godot/scene/main/viewport.cpp:2201)
[8] Viewport::push_input(Ref<InputEvent> const&, bool) (/home/booch/Documents/GodotCompiled/godot/scene/main/viewport.cpp:3249)
[9] Window::_window_input(Ref<InputEvent> const&) (/home/booch/Documents/GodotCompiled/godot/scene/main/window.cpp:1683)
[10] void call_with_variant_args_helper<Window, Ref<InputEvent> const&, 0ul>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (/home/booch/Documents/GodotCompiled/godot/./core/variant/binder_common.h:304 (discriminator 4))
[11] void call_with_variant_args<Window, Ref<InputEvent> const&>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, int, Callable::CallError&) (/home/booch/Documents/GodotCompiled/godot/./core/variant/binder_common.h:419)
[12] CallableCustomMethodPointer<Window, Ref<InputEvent> const&>::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/booch/Documents/GodotCompiled/godot/./core/object/callable_method_pointer.h:104)
[13] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (/home/booch/Documents/GodotCompiled/godot/core/variant/callable.cpp:57)
[14] Variant Callable::call<Ref<InputEvent> >(Ref<InputEvent>) const (/home/booch/Documents/GodotCompiled/godot/./core/variant/variant.h:876)
[15] DisplayServerX11::_dispatch_input_event(Ref<InputEvent> const&) (/home/booch/Documents/GodotCompiled/godot/platform/linuxbsd/x11/display_server_x11.cpp:4034)
[16] DisplayServerX11::_dispatch_input_events(Ref<InputEvent> const&) (/home/booch/Documents/GodotCompiled/godot/platform/linuxbsd/x11/display_server_x11.cpp:4011)
[17] Input::_parse_input_event_impl(Ref<InputEvent> const&, bool) (/home/booch/Documents/GodotCompiled/godot/core/input/input.cpp:774)
[18] Input::flush_buffered_events() (/home/booch/Documents/GodotCompiled/godot/core/input/input.cpp:1053)
[19] DisplayServerX11::process_events() (/home/booch/Documents/GodotCompiled/godot/platform/linuxbsd/x11/display_server_x11.cpp:5151)
[20] OS_LinuxBSD::run() (/home/booch/Documents/GodotCompiled/godot/platform/linuxbsd/os_linuxbsd.cpp:960)
[21] /home/booch/Documents/GodotCompiled/godot/bin/godot.linuxbsd.editor.dev.x86_64(main+0x190) [0x5af516b07439] (/home/booch/Documents/GodotCompiled/godot/platform/linuxbsd/godot_linuxbsd.cpp:85)
[22] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7682ab829d90] (??:0)
[23] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7682ab829e40] (??:0)
[24] /home/booch/Documents/GodotCompiled/godot/bin/godot.linuxbsd.editor.dev.x86_64(_start+0x25) [0x5af516b071e5] (??:?)
-- END OF BACKTRACE --

### Steps to reproduce

Load minimal project.
Click inside the File System blank space (no file selected).
Click the down arrow.

### Minimal reproduction project (MRP)

[newnew.zip](https://github.com/user-attachments/files/15756549/newnew.zip)

### PR DESCRIPTION
**Pull request by TheSofox**
Fixes  #92958

Now when Down (or Up) key is used to change selection on a `Tree` with `SELECT_MULTI` enabled, the code will check whether anything is selected before trying to change the selection. Previously it would not perform this check and a crash would be possible if nothing was selected.

This has a different approach from [#92959](https://github.com/godotengine/godot/pull/92959), though aiming to solve the same bug.

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -3359,8 +3359,10 @@ void Tree::_go_up() {
 			return;
 		}
 
-		select_single_item(prev, get_root(), selected_col);
-		queue_redraw();
+		if (selected_item) {
```
Comment (Hilderin) [inline scene/gui/tree.cpp:3362]: Adding this condition makes the behavior different for multi-select and single-select mode. In single select mode, going up select the last node.
I think the real problem is that selected_col is -1 if nothing is selected. 
image

I suggest moving `int col = selected_col < 0 ? 0 : selected_col;` before the `if (select_mode == SELECT_MULTI) {` and using `col` as the third parameter of `select_single_item`.

File: scene/gui/tree.cpp [hunk 2]
```diff
@@ -3391,8 +3393,10 @@ void Tree::_go_down() {
 			return;
 		}
 
-		select_single_item(next, get_root(), selected_col);
-		queue_redraw();
+		if (selected_item) {
```
Comment (Hilderin) [inline scene/gui/tree.cpp:3396]: Same here, in single select mode, going down select the next node after the root if nothing is selected.
I suggest moving `int col = selected_col < 0 ? 0 : selected_col;` before the `if (select_mode == SELECT_MULTI) {` and using `col` as the third parameter of `select_single_item`.

File: scene/gui/tree.cpp (hunk 1 above)
Comment (TheSofox) [reply scene/gui/tree.cpp:3362]: This is the approach taken by https://github.com/godotengine/godot/pull/92959 . I'm kinda confused why you want to make my PR exactly like theirs rather focus on their PR and see how it can be improved given it already has the approach you want.

File: scene/gui/tree.cpp (hunk 2 above)
Comment (TheSofox) [reply scene/gui/tree.cpp:3396]: Same as above. (ie. PR https://github.com/godotengine/godot/pull/92959 already takes this approach).

**Comment by KoBeWi** [comment]
When nothing is selected, you can't use arrows or any other button to select something. Which means that you can't select any item when you are Tabbing into the tree, making it less friendly for keyboard controls.

#92959 seems like a better approach, but it still has the problem I mentioned in my comment. Code of both PRs looks fine though.

**Comment by TheSofox** [comment]
Amended commit to be more like https://github.com/godotengine/godot/pull/92959 Seemed to fix the issues @Hilderin raised.
Since the issue was raised on the other PR, I tried to reproduce the "selecting folded nodes" glitch but it seemed to work okay. If anyone reproduces it, let me know with repo steps.

**Comment by KoBeWi** [comment]
> If anyone reproduces it, let me know with repo steps.

1. Have some folded node at the bottom of the scene.
2. Deselect all nodes.
3. Save the scene.
4. Reload the scene.
5. Click empty space in scene tree.
6. Press Up.

**Comment by TheSofox** [comment]
Thanks for the repo steps! The problem was `get_last_item()` didn't take into consideration whether the last item was hidden by a collapsed parent or not. Apparently this function is only used by `_go_up()`, so I modified it to only choose the last visible item.

File: scene/gui/tree.cpp [hunk 3]
```diff
@@ -3354,15 +3354,16 @@ void Tree::_go_up() {
 		prev = selected_item->get_prev_visible();
 	}
 
+	int col = selected_col < 0 ? 0 : selected_col;
```
Comment (KoBeWi) [inline scene/gui/tree.cpp:3357]:
```suggestion
	int col = MAX(selected_col, 0);
```

File: scene/gui/tree.cpp [hunk 4]
```diff
@@ -3386,16 +3387,15 @@ void Tree::_go_down() {
 		next = selected_item->get_next_visible();
 	}
 
+	int col = selected_col < 0 ? 0 : selected_col;
```
Comment (KoBeWi) [inline scene/gui/tree.cpp:3390]:
```suggestion
	int col = MAX(selected_col, 0);
```

**Review by KoBeWi — APPROVED** [review]

File: scene/gui/tree.cpp (hunk 3 above)
Comment (TheSofox) [reply scene/gui/tree.cpp]: Change implemented.

File: scene/gui/tree.cpp (hunk 4 above)
Comment (TheSofox) [reply scene/gui/tree.cpp]: Change implemented.

**Comment by akien-mga** [comment]
Thanks!
