### PR TITLE
Check for GL ES version of BPTC extension when using the OpenGL renderer

### LINKED ISSUE #95561: HIGH quality VRAM Compressed textures breaks Opengl 3 with ANGLE on Windows
### Tested versions

Tested on: Godot **4.3** _Release_ and Godot **4.2.2** _Release_

The project was not teste on godot 4.1 because the angle compatibility on windows was introduced on version 4.2

### System information

Godot v4.3.stable - Windows 11 - GLES3 (Compatibility) - NVIDIA GeForce RTX 2050 (NVIDIA; 32.0.15.6070) - 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz (12 Threads)

### Issue description

If your project uses any compressed texture where the high quality setting is enabled, if you use **OpenGl** with **ANGLE** on **Windows**, the texture will not load and the game will crash.

This issue seems to persist with both textures formats (S3TC BPTC and ETC2 ASTC)

This was tested on both recent computers (with rtx 2050), and also second generation intel cpus (2010-2011)

### Steps to reproduce

Create a new project, use the compatibility option, then import an image and select the "compressed texture" option and select the high quality option.

After that, run the project using Angle on Windows.

(I recommend exporting the project first so the editor doesn't crash)

### Minimal reproduction project (MRP)

**THE PROJECTS ARE SET TO USE THE NORMAL OPENGL MODE**

To see the bug on action, set to angle mode manually _(Reminder that this bug was tested on windows)_

[Godot 4.2.2 Opengl3 ANGLE PROJECT.zip](https://github.com/user-attachments/files/16626069/Godot.4.2.2.Opengl3.ANGLE.PROJECT.zip)
[Godot 4.3 Opengl Angle - Project.zip](https://github.com/user-attachments/files/16626070/Godot.4.3.Opengl.Angle.-.Project.zip)

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/95561

ANGLE only reports support for `GL_EXT_texture_compression_bptc`, not `GL_ARB_texture_compression_bptc` or `EXT_texture_compression_bptc` (the WebGL version of the extension) therefore, we need to check all three so that ANGLE devices will properly use BPTC textures

`GL_ARB_texture_compression_bptc `is the version for desktop devices while`GL_EXT_texture_compression_bptc` is for GL ES devices. However in practice, some desktop devices report support for`GL_EXT_texture_compression_bptc`. Ironically more desktop devices support `GL_EXT_texture_compression_bptc` than mobile devices.

### CODE REVIEW

**Review by BlueCube3310 — APPROVED** [review]
Tested locally, it fixes the issue. BPTC textures now display properly under ANGLE

File: drivers/gles3/storage/config.cpp [hunk 1]
```diff
@@ -77,7 +77,7 @@ Config::Config() {
 	}
 #endif
 
-	bptc_supported = extensions.has("GL_ARB_texture_compression_bptc") || extensions.has("EXT_texture_compression_bptc");
+	bptc_supported = extensions.has("GL_ARB_texture_compression_bptc") || extensions.has("GL_EXT_texture_compression_bptc") || extensions.has("EXT_texture_compression_bptc");
```
Comment (dsnopek) [inline drivers/gles3/storage/config.cpp:80]: I think Emscripten reports all the extensions with the `GL_` prepended (as well as the version without), so if `"EXT_texture_compression_bptc"` is for WebGL, I don't think it's necessary, it should be covered by the `GL_` version too. I haven't tested this, though, this is just from memory of working on other WebGL issues in the past

Comment (dsnopek) [reply drivers/gles3/storage/config.cpp:80]: Or, actually, we do that - not Emscripten. If you look about 20 lines above this code, you'll see that we're adding all the extensions to the list twice, once without the `GL_` and once with.

So, for sure, we don't need both here:

```suggestion
	bptc_supported = extensions.has("GL_ARB_texture_compression_bptc") || extensions.has("GL_EXT_texture_compression_bptc");
```

Comment (clayjohn) [reply drivers/gles3/storage/config.cpp]: Alright, I removed the checks without the "GL_" prefix. But this makes me realize that Godot is probably adding "GL_" in front of the "W

**Comment by Repiteo** [comment]
Thanks!

File: drivers/gles3/storage/config.cpp (hunk 1 above)
Comment (clayjohn) [reply drivers/gles3/storage/config.cpp]: Yep, just noticed that too while checking haha. I should have checked back here first
