### PR TITLE
Tooltip flickering and targeting fixes.

### LINKED ISSUE #41261: Tooltips target the wrong item and keep blinking in scene tree and script list
**Godot version:**
Master d3b5c0948c943b3fbcb4b5322262c59c92abfa83

**OS/device including version:**
Windows 10

**Issue description:**
On Windows, tooltips in the scene tree or script list show information about the wrong item and keep blinking.
Example in the scene tree:

**Steps to reproduce:**
Case 1. In any scene, hover on a node in the scene tree panel.
Case 2. In the script editor, hover on a script in the list.

**Minimal reproduction project:**
Can be easily reproduced in any project.

### PR DESCRIPTION
**Pull request by EricEzaM**
Tooltip flickering was caused by...
* For Buttons with shortcuts, every call of `Viewport::_gui_get)tooltip()` in `Viewport` would return a different value, because the `BaseButton::get_tooltip()` method would always return a string with `\n` on the end, while `Label::get_text()` would have this `\n` removed, since `Viewport::_gui_show_tooltip` calls `String::string_edges()` which removes them. This mean't there was an inequality between the current tooltip and what it should be, which is what caused it to flicker. 

The equality test is shown on line 2061 below.
https://github.com/godotengine/godot/blob/c4865921ec8f2a4f5d3440b2b2abe5dbe289a4b9/scene/main/viewport.cpp#L2054-L2063

* For the Tree, the calculation of which item was hovered was incorrect because it seems that the wrong `Point` was being passed in. I don't know why the last tooltip position was being passed in rather than the last mouse position. Anyway, changing it to `gui.last_mouse_pos` solved the issue for me.

~Finally, I also made it so that tooltips disappear on hover, which is the current behaviour in Godot 3.2, but was missing in the current master.~

CC @pouleyKetchoupp 

Closes #41261

### CODE REVIEW

**Comment by pouleyKetchoupp** [comment]
I've tested on Linux and I can confirm tooltips target the right items now. I've also spotted two remaining issues with tooltips:

**1. Tooltip disappears immediately in case it's close enough to a corner for the mouse to start inside**

I think it could be alleviated by making the tooltip disappear only when the mouse is moving inside.

tooltip-disappears

**2. Tooltip shows on top of the application bar**

It's probably outside of this PR's scope, but it's similar to the issue that happened with popup menus not using the usable screen area properly.

In Godot 3 the popup was cut by the bottom bar (it's probably how it is on Windows too) but it would be better for usability to move the tooltip inside of the usable screen area instead.

tooltip-bottom-bar

**Comment by EricEzaM** [comment]
@pouleyKetchoupp 

1. This looks to be a really annoying issue to solve. In Godot 3 it was simple because the popup were just controls, so their dissapearing logic was handled 'implicitly' by the below section of code. When tooltip was hovered, `over`  would be the tooltip, so it would cancel. Now that popups are windows... not as nice. I'll have to have a think about how to do it - maybe it will end up just being a case of, as you say, only disappearing when moving the mouse inside. 

https://github.com/godotengine/godot/blob/9fc4f17281a25a74a916c29dd629c7aca5498aab/scene/main/viewport.cpp#L2019-L2031


2. Looks like `Popup` might need some of the same treatment `PopupMenu` got regarding it's placement?

**Comment by EricEzaM** [comment]
@pouleyKetchoupp I removed the hiding on mouse enter from this PR... The solution is not trivial as it effects things like the editor documentation in tooltips in the inspector, which has links that can be clicked on to take you to documentation. We want to be able to hover those and click them, but we probably don't want that behaviour on "normal" tooltips.

File: scene/gui/base_button.cpp [hunk 1]
```diff
@@ -345,7 +345,7 @@ String BaseButton::get_tooltip(const Point2 &p_pos) const {
 	String tooltip = Control::get_tooltip(p_pos);
 	if (shortcut_in_tooltip && shortcut.is_valid() && shortcut->is_valid()) {
 		String text = shortcut->get_name() + " (" + shortcut->get_as_text() + ")";
-		if (shortcut->get_name().nocasecmp_to(tooltip) != 0) {
+		if (shortcut->get_name().nocasecmp_to(tooltip) != 0 && tooltip != String()) {
```
Comment (akien-mga) [inline scene/gui/base_button.cpp:348]: I'd check for `!tooltip.empty()` first, there's no reason to do a `nocasecmp_to` with an empty string.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
