### PR TITLE
Keep collapsed state for actions when modifying Input Map

### LINKED ISSUE #109212: Moving an action in the Input Map causes all input actions to expand their drop downs
### Tested versions

-Reproducible in v4.4.1.stable.official [49a5bc7b6]

### System information

Godot v4.4.1.stable - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 32.0.15.7680) - AMD Ryzen 7 3700X 8-Core Processor (16 threads)

### Issue description

Dragging an input action to a different spot in the Input Map causes all dropdowns to expand. I would expect them not to expand since there's no benefit to it and it makes me lose my spot of what I was working on.

https://github.com/user-attachments/assets/7cb53692-9d0a-4dec-ad32-fd6e8b98f3d0

### Steps to reproduce

Create several input actions with inputs
hide them by clicking the arrow
move one of them

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by aaronp64**
Changing the Input Map in Project Settings (adding/removing/renaming actions, reordering, or changing action events) causes the action list `Tree` to be cleared/repopulated.  Updated `ActionMapEditor::update_action_list` to store which actions were collapsed before clearing, so they can remain collapsed after modifications.

Fixes #109212

### CODE REVIEW

File: editor/settings/action_map_editor.cpp [hunk 1]
```diff
@@ -423,8 +423,19 @@ void ActionMapEditor::update_action_list(const Vector<ActionInfo> &p_action_info
 		actions_cache = p_action_infos;
 	}
 
+	HashSet<String> collapsed_actions;
+	TreeItem *root = action_tree->get_root();
+	if (root) {
+		for (int i = 0; i < root->get_child_count(); i++) {
+			TreeItem *child = root->get_child(i);
```
Comment (KoBeWi) [inline editor/settings/action_map_editor.cpp]:
```suggestion
		for (TreeItem *child = root->get_first_child(); child; child = child->get_next()) {
```

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
