### PR TITLE
Fix AnimationPlayer jumping to the beggining after ending on editor.

### LINKED ISSUE #26083: Animation jumps to zero time/pos after the animation is finished
**Godot version:**
3.1 Beta 5 (previous versions dont have this bug)

**OS/device including version:**
Windows 7

**Issue description:**
The Animation jumps to zero time/pos after the animation is finished.

**Steps to reproduce:**
play an Animation by an AnimationPlayer.

(in own code this bug makes problems on my project - own code behaviour not working anymore like expected and it makes it hard to work around this problem. And i think the finished event is not throwing anymore)

Maybe its this update that leads to the problem?:
https://github.com/godotengine/godot/commit/5ec4f14a245b66b3e268f3c6cbb68a85336c7ca6

**Minimal reproduction project:**
https://i.imgur.com/8lBEWdv.gif

### PR DESCRIPTION
**Pull request by luizcarlos1405**
As pointed by @TypeOverride https://github.com/godotengine/godot/pull/25886#commitcomment-32365629 and @mrcdk https://github.com/godotengine/godot/pull/25886#issuecomment-465159646 my PR #25886 introduced a bug where the AnimationPlayer would jump to the beginning of the animation, even on the editor.

This PR fixes this and maintain the intended behaviour from #25776. Now the animation resets its position to 0 only after resuming or starting a new animation, i.e., calling `play()`.

*Bugsquad edit:* Fixes #26083.

### CODE REVIEW

**Comment by luizcarlos1405** [comment]
I don't know why it didn't pass the check, trying to figure it out.

File: scene/animation/animation_player.cpp [hunk 1]
```diff
@@ -1196,9 +1195,14 @@ void AnimationPlayer::play(const StringName &p_name, float p_custom_blend, float
...
 	if (c.assigned != name) { // reset
 		c.current.pos = p_from_end ? c.current.from->animation->get_length() : 0;
-	} else if (p_from_end && c.current.pos == 0) {
-		// Animation reset BUT played backwards, set position to the end
-		c.current.pos = c.current.from->animation->get_length();
+	} else {
+		if (p_from_end && c.current.pos == 0) {
+			// Animation reset BUT played backwards, set position to the end
+			c.current.pos = c.current.from->animation->get_length();
+		} else if (c.current.pos == c.current.from->animation->get_length()) {
```
Comment (akien-mga) [inline scene/animation/animation_player.cpp]: Should it also check `!p_from_end`? Otherwise I guess it could still fail if you play the animation once normally (so position is at the end), and then you try to play it backwards.

Comment (luizcarlos1405) [reply scene/animation/animation_player.cpp]: Yes, don't know how I didn't see it. Now checking.

**Comment by luizcarlos1405** [comment]
I really hope this doesn't get us to another bug.

**Comment by akien-mga** [comment]
Thanks!
