### PR TITLE
Don't print error on empty actions

### LINKED ISSUE #65729: Committing a undo redo action without method causes an "INVALID_HISTORY" error
### Godot version

v4.0.alpha.custom_build [79b21e96ad7a154e6c64a88150c98bd4dea52e91]

### System information

Windows 10

### Issue description

Since #59564, when you create an undo redo action, then commit it without adding any method, it throws this error:
`editor\editor_undo_redo_manager.cpp:221 - Condition "pending_action.history_id == INVALID_HISTORY" is true.`

This happens in some cases, like here, when `drag_modified_tiles` is empty: https://github.com/godotengine/godot/blob/16228ba3e27b57df48256fcdf34670a25b3d52b0/editor/plugins/tiles/tile_set_atlas_source_editor.cpp#L1315-L1320

This didn't happen before the merge of #59564.

### Steps to reproduce

```
undo_redo->create_action(TTR("My Action"));
undo_redo->commit_action(false);
```
(or open a TileSet and try to create a tile where there's already one, this triggers the bug)

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #65729
The history ID is assigned on first do/undo method, so invalid ID means there was no action. I changed the error to no-op.
Committing empty action is not possible, because there is no UndoRedo object involved.

### CODE REVIEW

File: editor/editor_undo_redo_manager.cpp [hunk 1]
```diff
@@ -124,7 +124,7 @@ void EditorUndoRedoManager::create_action(const String &p_name, UndoRedo::MergeM
 	create_action_for_history(p_name, INVALID_HISTORY, p_mode);
 
 	if (p_custom_context) {
-		// This assigns context to pending action.
+		// This assigns history to pending action.
```
Comment (KoBeWi) [inline editor/editor_undo_redo_manager.cpp:127]: I think this is leftover from before I renamed "context" to "history".

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
