### PR TITLE
Fix Spinbox display does not round properly when using decimal custom arrow steps

### LINKED ISSUE #97561: Spinbox display does not round properly when using decimal custom arrow steps
### Tested versions

- Reproducible in: v4.2.2 stable, v4.3 stable

### System information

Godot v4.3.stable - macOS 15.0.0 - GLES3 (Compatibility) - AMD Radeon Pro 5300M OpenGL Engine - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 Threads)

### Issue description

Using a 0 step value and a decimal custom arrow step on a spinbox causes the displayed value in the spinbox to round incorrectly at some numbers, despite the internal value being rounded. I'm fairly sure this was working previously on both 4.2.2 and 4.3, so its possible its due to me upgrading to the newest macOS. Also reproduced with arrow steps like 0.2, 0.9, and 1.1, and in brand-new project. 

https://github.com/user-attachments/assets/1f842b7b-b639-4ae3-b640-2ec09e82124a

### Steps to reproduce

Create a new spinbox node, set its step value to 0 and its custom arrow step to a decimal value besides 0.5. Interacting with the arrows results in the issue

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by shahriarlabib000**
Fixes #97561

### CODE REVIEW

**Comment by shahriarlabib000** [comment]
Seems to be working for OP's testcases not really sure if this is the intended behavior for
`custom_arrow_step`

**Comment by shahriarlabib000** [comment]
Maybe we could give some optional parameter to the `_set_value_no_signal` instead of overriding it from the `Range` class ?

File: scene/gui/spin_box.cpp [hunk 1]
```diff
@@ -41,7 +41,13 @@ Size2 SpinBox::get_minimum_size() const {
 }
 
 void SpinBox::_update_text(bool p_keep_line_edit) {
-	String value = String::num(get_value(), Math::range_step_decimals(get_step()));
+	double step = 0.0;
+	if (get_step() != 0.0 && ((get_custom_arrow_step() == 0.0) ^ (get_step() < get_custom_arrow_step()))) {
```
Comment (AThousandShips) [inline scene/gui/spin_box.cpp:45]:
```suggestion
	if (get_step() != 0.0 && ((get_custom_arrow_step() == 0.0) != (get_step() < get_custom_arrow_step()))) {
```
Clearer and more correct than bitwise operation on bools IMO

Comment (shahriarlabib000) [reply scene/gui/spin_box.cpp]: Fixed!

**Comment by KoBeWi** [comment]
Each `set_step()` will emit `changed` signal, so doing it to temporarily adjust step is out of question.

The expected behavior is that `custom_arrow_step` only affects the value when clicking the arrows and displays it properly rounded. Other actions like manually typing the value, using mouse wheel or dragging the arrows, should use the regular step.

**Comment by shahriarlabib000** [comment]
So can we move `shared` of `Range` to `protected` and add a private `_set_step_no_signal` to the spin_box ?

**Comment by KoBeWi** [comment]
I mean rounded to the arrow step, so e.g. if arrow step is 0.1, you should never see e.g. 6.999999999 like in the issue.

> So can we move shared of Range to protected access modifier and add a private _set_step_no_signal to the spin_box ?

It would be nice to solve it without modifying `step`. If it's not possible, you can wrap `set_step()` in `set_block_signals()`.

**Comment by shahriarlabib000** [comment]
So something like this
 ```c++
set_block_signals(true);
set_step();
set_blovk_signals(false);
```

**Comment by KoBeWi** [comment]
Yes.

**Comment by shahriarlabib000** [comment]
It's might be intentional but let me ask this. Should dragging the arrow always clamp to to max_value and min_value ? Regardless if allow_greater or less is toggled?

**Comment by shahriarlabib000** [comment]
> using snapped seems to be working shahriarlabib000@3b2c592
Should I update to that branch?

**Comment by shahriarlabib000** [comment]
is there implementation of exp_edit enabled  in master?

**Comment by shahriarlabib000** [comment]
I think the issue for this pr hasn't been labelled yet

**Comment by shahriarlabib000** [comment]
> Seems like arrow step applies even if typing the value manually. This is wrong.

What were the values for `step` and `custom_arrow_step` ?

**Comment by KoBeWi** [comment]
Step 0, arrow step 0.1.

**Comment by shahriarlabib000** [comment]
I think it's fixed now?

File: scene/gui/spin_box.cpp [hunk 2]
```diff
@@ -41,7 +41,11 @@ Size2 SpinBox::get_minimum_size() const {
 }
 
 void SpinBox::_update_text(bool p_keep_line_edit) {
-	String value = String::num(get_value(), Math::range_step_decimals(get_step()));
+	double step = get_step();
+	if (use_custom_arrow_step && custom_arrow_step != 0.0) {
+		step = get_custom_arrow_step();
```
Comment (KoBeWi) [inline scene/gui/spin_box.cpp:46]:
```suggestion
		step = custom_arrow_step;
```

File: scene/gui/spin_box.cpp [hunk 3]
```diff
@@ -114,8 +121,15 @@ void SpinBox::_line_edit_input(const Ref<InputEvent> &p_event) {
 void SpinBox::_range_click_timeout() {
 	if (!drag.enabled && Input::get_singleton()->is_mouse_button_pressed(MouseButton::LEFT)) {
 		bool up = get_local_mouse_position().y < (get_size().height / 2);
-		double step = get_custom_arrow_step() != 0.0 ? get_custom_arrow_step() : get_step();
-		set_value(get_value() + (up ? step : -step));
+		bool original_do_round = is_using_rounded_values();
+		double step = get_step();
+		double temp_step = get_custom_arrow_step() != 0.0 ? get_custom_arrow_step() : get_step();
+		_rounded_values = false;
```
Comment (KoBeWi) [inline scene/gui/spin_box.cpp:127]: Why this? `rounded` should always make the value rounded.

Comment (shahriarlabib000) [reply scene/gui/spin_box.cpp:127]: Oh sorry, now that you mention it, I think it should be removed too. It's been awhile but I think the reasoning was the value was not updating if the arrow_step was too low. But I guess that logic is flawed. I'll remove it

**Comment by shahriarlabib000** [comment]
> I don't like how it partially duplicates set_value(), but if it works better then ok.

Maybe we could give set value () an optional step parameter

File: scene/gui/spin_box.cpp (hunk 3 above)
Comment (shahriarlabib000) [reply scene/gui/spin_box.cpp]: Oh ok, so if i set the step to 0.8 the value cannot get past 2.

**Comment by shahriarlabib000** [comment]
What about the `exp_edit` ?

**Comment by KoBeWi** [comment]
`exp_edit` is irrelevant for SpinBox.

**Comment by shahriarlabib000** [comment]
Is it possible to hide it from the inspector somehow?

**Comment by KoBeWi** [comment]
Yes, by using `_validate_property()`.

**Comment by shahriarlabib000** [comment]
Okay maybe for another pr if I can figure out how to use it

**Review by KoBeWi — APPROVED** [review]
Works fine now.
You could maybe add some comments for the new code, on why is it like that.

File: scene/gui/spin_box.cpp (hunk 3 above)
Comment (KoBeWi) [reply scene/gui/spin_box.cpp]: It's a pre-existing bug, so it can be fixed later.
Not sure what's the expected behavior here, maybe `rounded` could force the arrow step to be at least 1.
Then again, when both steps are 0, the arrows don't work either.

File: scene/gui/spin_box.cpp [hunk 4]
```diff
@@ -114,8 +121,13 @@ void SpinBox::_line_edit_input(const Ref<InputEvent> &p_event) {
 void SpinBox::_range_click_timeout() {
 	if (!drag.enabled && Input::get_singleton()->is_mouse_button_pressed(MouseButton::LEFT)) {
 		bool up = get_local_mouse_position().y < (get_size().height / 2);
-		double step = get_custom_arrow_step() != 0.0 ? get_custom_arrow_step() : get_step();
-		set_value(get_value() + (up ? step : -step));
+		double step = get_step();
+		//arrow button is being pressed, so we also need to set the step to the same value as custom_arrow_step if its not 0
```
Comment (KoBeWi) [inline scene/gui/spin_box.cpp:125]:
```suggestion
		// Arrow button is being pressed, so we also need to set the step to the same value as custom_arrow_step if its not 0.
```
Same in the other comment.

**Comment by shahriarlabib000** [comment]
@KoBeWi 
So if the step is 0, and the value is being typed, it seems that the displayed value's precision is affected.
What if we do something like this?
https://github.com/shahriarlabib000/godot/compare/spinBox...shahriarlabib000:godot:spinThyBox
```c++
void SpinBox::_update_text(bool p_keep_line_edit) {
	//String value = String::num(get_value(), Math::range_step_decimals(get_step()));
	double value_for_calculating_precision = get_value();
	int decimal = 0;
	while((int)value_for_calculating_precision != value_for_calculating_precision) {
		value_for_calculating_precision *= 10;
		++decimal;
		if(decimal >= 10) {
			break;
		}
	}

	String value = String::num(get_value(), decimal);
```

**Comment by KoBeWi** [comment]
I think that's a separate issue.

**Comment by Repiteo** [comment]
Thanks!
