### PR TITLE
Fix reload scripts error after saving in external editor.

### LINKED ISSUE #66644: Editor stuck in "The following files are newer on disk" After saving in external editor.
### Godot version

4.0.beta-2 (Mono)

### System information

Arch Linux x64 - Official Mono Build

### Issue description

Sometimes when saving code in my external editor, (vscode) I get a dialog saying the code file changed, and in this version (beta 2) it just reopens the dialog infinitely until I chose to resave the file. This did not happen in beta 1, I was able to just click reload.
Now when I try to click reload I get this in the debug console and the dialog just reopens.
`core/object/object.cpp:1057 - Error calling from signal 'confirmed' to callable: 'ScriptEditor::ScriptEditor::reload_scripts': Method expected 1 arguments, but called with 0.`

### Steps to reproduce

Edit code file in external editor and save, click back into godot to run.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by zaevi**
Fixes #66644.
`&ScriptEditor::reload_scripts` requires an argument after #66405.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
CC @Rindb

File: editor/plugins/script_editor_plugin.cpp [hunk 1]
```diff
@@ -3892,7 +3892,7 @@ ScriptEditor::ScriptEditor() {
 		vbc->add_child(disk_changed_list);
 		disk_changed_list->set_v_size_flags(SIZE_EXPAND_FILL);
 
-		disk_changed->connect("confirmed", callable_mp(this, &ScriptEditor::reload_scripts));
+		disk_changed->connect("confirmed", callable_mp(this, &ScriptEditor::reload_scripts).bind(true));
```
Comment (Rindbee) [inline editor/plugins/script_editor_plugin.cpp:3895]: Changes to the `gdscript_text_document.cpp` file in #66405 have been reverted in #66867, so #66405 is actually broken. I intend to synchronize the changes via a signal (#66880). Subsequent PRs will break some compatibility and have not been merged.


```suggestion
		disk_changed->connect("confirmed", callable_mp(this, &ScriptEditor::reload_scripts).bind(false));
```

This should be changed to `false` if we don't plan to restore the rest of #66405.

**Comment by akien-mga** [comment]
Thanks!
