### PR TITLE
Fix invalid 2D global position when read outside tree

### LINKED ISSUE #75676: Accessing global_position before a scene instance is added to the scene tree can cause its position to reset to zero
### Godot version

4.0.2

### System information

Windows 10

### Issue description

If a script accesses the `global_position` of an object instantiated from a packed scene before it's added to the scene tree, and then once added to the scene if its global position is modified by anything (including the physics engine) before its `position` is modified, it ends up at the origin, regardless of where it's placed in the editor. And for objects instantiated via script, regardless of what its `position` was set to before adding it with add_child()

The bug does not occur if the object is not a scene instance. Its position is preserved.

### Steps to reproduce

instantiate a scene
access its global_position
add it to the scene tree
modify its global position

### Minimal reproduction project

[min.zip](https://github.com/godotengine/godot/files/11156256/min.zip)

### LINKED ISSUE #76327: Area2D has stange position of colliders
### Godot version

4.0.2

### System information

Fedora Linux 38

### Issue description

In the script I use instantiate/add_child to create an object with Area2D that should detect collisions, but it doesn't.
But when I put tscn with this object on scene, it interacts normally.

After some testing and investigation, I found that the colliders are not where they are displayed, they are outside the top of the window and I can interact with them if the second area2d has a negative Y coordinate. Or i can resize window and these invisible area2d (or collision shapes?) will be lit lower than the top side of the window.

p.s. sorry for my English))

### Steps to reproduce

Screenshot

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/11300664/test.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
MRP for the bug:
[repro.tscn.txt](https://github.com/godotengine/godot/files/11115915/repro.tscn.txt)

When you get `global_position` of a CanvasItem outside tree, it will assign its position to global position (roughly speaking). When the node enters tree, its global transform is not invalidated, so `global_position` will still return its position. This also leads to some abnormalities, like sprite not displaying at its real position (as observed in the MRP).

*Bugsquad edit: Fixes #75676. Fixes #76327.*

### CODE REVIEW

**Comment by kleonc** [comment]
The global transform can still be not invalidated when changing top level for a CanvasItem outside the tree (it would need to be invalidated for the whole branch):
https://github.com/godotengine/godot/blob/44d539465acca7592e0c88748e231fe5f151da37/scene/main/canvas_item.cpp#L392-L408

**Comment by kleonc** [comment]
> @kleonc Does it lead to any issue? I tried bugging it, but it prints a correct global position.

Here's an example:
```gdscript
func foo() -> void:
	var a := Node2D.new()
	a.position = Vector2(1, 1)

	var b := Node2D.new()
	b.position = Vector2(2, 2)

	a.add_child(b)

#	b.global_position
	b.top_level = true
	print(b.global_position)
```
With the `b.global_position` line commented out it correctly outputs `(2, 2)`.
With the `b.global_position` line uncommented it incorrectly outputs `(3, 3)`.

**Comment by KoBeWi** [comment]
Ok fixed.

File: scene/main/canvas_item.cpp [hunk 1]
```diff
@@ -403,6 +408,8 @@ void CanvasItem::set_as_top_level(bool p_top_level) {
 
 	if (!is_inside_tree()) {
 		top_level = p_top_level;
+		propagate_call(SNAME("_invalidate_global_transform"));
+		global_invalid = true;
```
Comment (kleonc) [inline scene/main/canvas_item.cpp:412]:
```suggestion
```
`propagate_call` will call `_invalidate_global_transform` for `this` node too so no need to set `global_invalid = true` separately.

https://github.com/godotengine/godot/blob/06f5b09ca493d1de5dd4bec97bdb6b9ad4fb1d29/scene/main/node.cpp#L1959-L1975

Comment (KoBeWi) [reply scene/main/canvas_item.cpp:412]: Right, I forgot to remove this line .-.

**Review by kleonc — APPROVED** [review]
LGTM.
(haven't actually tested it after the changes though :upside_down_face:)

**Review by lawnjelly — APPROVED** [review]
Also looks fine to me.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.3.
