### PR TITLE
Fix shader uniform storage conversions and crash

### LINKED ISSUE #63064: Shader uniform vec4 array shows as PackedFloat32Array, breaking future uniforms with the same name.
### Godot version

v4.0.alpha.custom_build [ae5668f81]

### System information

Arch on 5.18.11-arch1-1

### Issue description

See reproduction steps, as it goes through more thoroughly

### Steps to reproduce

1) Make a shader with some working uniforms

    ```glsl
    shader_type canvas_item;

    uniform vec3 my_array1[4];
    uniform vec3 my_array2[4];

    ```
    shader parameters

2) Change one of them to a vec4 array:

    ```glsl
    uniform vec4 my_array1[4];
    ```
    Array type changes to PackedFloat32Array which kinda makes sense, but the values are still Vec3
    image

3) Rename it to `my_array` without the number and it changes to this:

    Since it's a new variable name, it's pretty much the expected behavior.

    image

4) Change it back to a vec3 array:

    Same variable name so the bug happens. The type changes to PackedVector3Array but the values are still floats.

    image

### Minimal reproduction project

(Right after step 1) [test15.zip](https://github.com/godotengine/godot/files/9125430/test15.zip)

### LINKED ISSUE #64051: Uniform arrays of `mat4` type are set incorrectly when an Array of Transform3D is supplied
### Godot version

3b39f00761145

### System information

Linux

### Issue description

While you can set a `uniform mat4 x;` using a `Transform3D`, you can't set a `uniform mat4 x[N];` using an Array of `Transform3D`s (the values visible to the shader will be corrupted / incorrect). Instead, currently you have to convert the Array of `Transform3D`s to a flattened `PackedFloat32Array` and use that as the parameter of `set_shader_param`.

I think the reason might be that the conversion in this line doesn't work as expected:
https://github.com/godotengine/godot/blob/25915cdd0e8e2baffc4d52692a1c54ad182e2aea/servers/rendering/renderer_rd/storage_rd/material_storage.cpp#L652

Somewhat related: #63064

### Steps to reproduce

Given this uniform:
```gdshader
uniform mat4 x[1];
```
This doesn't work (results in bad values in shader):
```gdscript
my_shader_material.set_shader_param("x", [global_transform])
```
This works:
```gdscript
my_shader_material.set_shader_param("x", global_transform_as_16_floats_in_packed_array)
```

### Minimal reproduction project

_No response_

### LINKED ISSUE #64832: "get_shader_uniform()" returns null, rather than default values, if uniforms have not been set or reverted
### Godot version

4.0.alpha14

### System information

Windows 10, Core i7 5820k, GeForce 980TI

### Issue description

Requesting uniform values with "get_shader_uniform()" will return null values if the uniforms have not been set or reverted rather than default values. This appears to be an issue for Godot internally as well as when you create a new shader material the inspector will also get the null values for the uniforms rather than the defaults from the shader.

image
EDIT: updated screenshot as I had misdrawn my line

### Steps to reproduce

Assign a shader material and a custom shader to a mesh and observe how the default values from the shader are not showing up in the inspector.

OR

Open the attached project and open the test scene and look at the assigned material. You can also click the "Get Uniforms" checkbox I set up to see it returning null when you run "get_shader_uniform()" on the uniforms.

### Minimal reproduction project

[shader_uniform_issue.zip](https://github.com/godotengine/godot/files/9416259/shader_uniform_issue.zip)

### LINKED ISSUE #66619: Shader hint source_color does not transmit the correct default value to the Inspector
### Godot version

4.0 Beta 2

### System information

Win 10, Nvidea 765M

### Issue description

image

This is not just a visual issue, the Inspector value is indeed `vec4(0.0, 0.0, 0.0, 1.0)` aka the color Black as can be seen when mouse over.

Possibly related: https://github.com/godotengine/godot/pull/61554

### Steps to reproduce

1. Add a Sprite,
2. add a shader
3. add this line: `uniform vec4 solid_color: source_color = vec4(1.0,0.0,0.0,1.0);`

### Minimal reproduction project
This is faster tested without having to download and extract a MRP

_Bugsquad edit: removed unrelated rant_

### LINKED ISSUE #74255: Global Shader Parameter Undefined Behavior in Editor
### Godot version

4.0.stable.mono

### System information

Windows 10, NVIDIA RTX 2060 (Driver 30.0.14.7284), Vulkan 1.2.175 Forward+ (Editor)

### Issue description

When changing certain Global Shader Parameters (in this case, a mat4) in the Project Settings, the value sent to the editor 3D view appears to be undefined, resulting in garbage values sent to the shaders.

As an example here, I'm using a mat4 to describe global light directions for a lighting shader
Note that the shader receives a different value even when the editor is being set to the same values
https://user-images.githubusercontent.com/44537737/222551889-b7c7ca63-ef65-484c-818f-c6ce47a7d3c0.mp4

Setting the global parameter from a script does pass the correct value to the shaders
image

I have also determined the shaders in the editor also do not get correct values from the `project.godot` when loading the project.

### Steps to reproduce

- Create a Global Shader Parameter of mat4 type (Project > Project Settings... > Shader Globals)
- Create a shader that visualizes the value of the mat4 (`global uniform mat4 global_mat`)
- Attempt to modify the global in the same Project Settings menu, the shader will receive garbage values

### Minimal reproduction project

[GlobalShaderParameters.zip](https://github.com/godotengine/godot/files/10875801/GlobalShaderParameters.zip)

### LINKED ISSUE #74680: Shader array uniforms dont always update in editor correctly
### Godot version

4.0 stable

### System information

Forward+ renderer, rx470

### Issue description

Creating a uniform array in shader and then changing its value in inspector will lock the variable type for some reason

### Steps to reproduce

1. Create a shader with something like uniform vec3[10] whatever;
2. Add something to the array
3. Change the array to something else, maybe vec4
4. Uniform will still show as vec3 in editor

seems to happen with all datatypes though, ive currently got it stuck on int array somehow even though it is clearly a vec4
reloading shader/scene/engine or even changing the variable name doesnt fix it, annoying

### Minimal reproduction project

trivial recreation

### LINKED ISSUE #75033: Global shader uniform vec4 does not accept Vector4 when setting
### Godot version

4.0 (.NET)

### System information

Windows 11

### Issue description

I have a global uniform vec4 in my shader. I was trying to set this value from code, using:

`RenderingServer.GlobalShaderParameterSet("vector4test", new Vector4(1f, 0.0f, 0.0f, 1.0f))`

This did not work, it seems the uniform was still at some default or invalid value. This is confirmed by running this afterwards:

`RenderingServer.GlobalShaderParameterGet("vector4test").As<Vector4>()`

Which also returns a zero'ed Vector4, not the vector I passed in.

After some time of head-scratching, I tried passing the value as a Plane instead of a Vector4. Then, it worked.

The [documentation](https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/shading_language.html) says that Vector4 type can be used to set vec4 shader types in GDscript (no mention of C# but I assume it should be the same). However this implementation seems to be broken.

### Steps to reproduce

Run attached project. Observe that nothing is visible. Change the line in the MeshInstance3D.cs script and observe that the plane with the shader suddenly appears when running it again.

### Minimal reproduction project

[Vector4Test.zip](https://github.com/godotengine/godot/files/11003334/Vector4Test.zip)

### LINKED ISSUE #75191: Shader uniform parameter vec4 without source_color hint does not follow explicit default value, and source_color default differs between vec3 and vec4
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Linux Ubuntu 22.04 with Unity desktop

### Issue description

In a shader using uniform parameters of type vec3 and vec4, the way defaults work is inconsistent.

* vec3 param => OK, default is (0, 0, 0) and explicit default is honored
* vec3 param : source_color => OK, default is black and explicit default is honored
* vec4 param => not OK, default is (0, 0, 0, 0) but explicit default is ignored and keeps using (0, 0, 0, 0)
* vec4 param : source_color => OK, default is white and explicit default is honored

So there are two issues:
* vec4 param without source_color hint ignores explicit default
* vec3 and vec4 react differently when source_color is used but there is no explicit default, to pick a default

Here is a sum-up screenshot of the default values for each case:

EDIT: I realized some vec3 labels are incorrect: since there is no alpha, Clear should be Black and Alpha Gray should just be Gray. This also means that it's normal that the source_color preview looks different on vec4 for those two.

image

### Steps to reproduce

1. Open the sample project attached, open the demo scene
2. Click on Sprite2D
3. In the inspector, unfold Material info and check the shader values (there should be no Revert button visible, so they are the default values). You should see the same inconsistent values as in the screenshot above
4. When an explicit default value is set, you can also modify the value and click on the Revert button to make sure that we refreshed to the last default values

### Minimal reproduction project

[v4.0 - Shader vec3 vec4 default inconsistencies.zip](https://github.com/godotengine/godot/files/11031311/v4.0.-.Shader.vec3.vec4.default.inconsistencies.zip)

### LINKED ISSUE #76135: Unable to pass color arrays through shader parameters
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

GNU/Linux, GLES3 & Vulkan, Intel UHD 770

### Issue description

When passing arrays of color objects to the shader, the shader program cannot get the values, even when converted to vector arrays.

And source_color hint does not convert colors correctly when passed through an array.

```
var colors := [
	Color.hex(0x0088ffff),
	Color.hex(0xff000088),
	Color.hex(0x00ff0000),
	Color.hex(0x0000ffff),
]
func _ready() -> void:
	var shader: ShaderMaterial = mesh.material
	shader.set_shader_parameter("vec4_no_hint", colors)
	shader.set_shader_parameter("vec4_hint", colors)
	shader.set_shader_parameter("vec3_no_hint", colors)
	shader.set_shader_parameter("vec3_hint", colors)
	var cvt_colors = colors.map(func (c): return Vector4(c.r, c.g, c.b, c.a))
	shader.set_shader_parameter("cvt_vec4_no_hint", cvt_colors)
	shader.set_shader_parameter("cvt_vec4_hint", cvt_colors)
	shader.set_shader_parameter("cvt_vec3_no_hint", cvt_colors)
	shader.set_shader_parameter("cvt_vec3_hint", cvt_colors)
```

Result With GLES3:
图片

Result With Vulkan:
图片

### Steps to reproduce

Open the sample project attached, open the test scene, switch to the 3D tab, you will see it.

### Minimal reproduction project

[test-color-uniform-array.tar.gz](https://github.com/godotengine/godot/files/11242561/test-color-uniform-array.tar.gz)

### LINKED ISSUE #76157: Unable to get color data from an array of source_color type in shader.
### Godot version

v4.1.dev.custom_build.a7276f1ce

### System information

Win10, AMD 2600, GeForce GTX 1060, Vulkan API 1.3.205

### Issue description

I can't get correct color data from an array of source_color type.
The color data is saved as **Color** in the file:
`shader_parameter/palette = [Color (1, 0, 0, 1), Color (0, 1, 0, 1), Color (0, 0, 1, 1)]`
Shouldn't it be saved as PackedColorArray?

### Steps to reproduce

1.Declare an array of source_color type.
2.Set colors.

### Minimal reproduction project

[shadertest.zip](https://github.com/godotengine/godot/files/11246504/shadertest.zip)

### PR DESCRIPTION
**Pull request by bitsawer**
* Fixes https://github.com/godotengine/godot/issues/64051
* Fixes https://github.com/godotengine/godot/issues/74255
* Fixes https://github.com/godotengine/godot/issues/75033
* Fixes https://github.com/godotengine/godot/issues/76135
* Fixes https://github.com/godotengine/godot/issues/76157
* Fixes https://github.com/godotengine/godot/issues/75191
* Fixes https://github.com/godotengine/godot/issues/66619
* Fixes https://github.com/godotengine/godot/issues/63064
* Fixes https://github.com/godotengine/godot/issues/74680
* Fixes https://github.com/godotengine/godot/issues/64832
* Fixes https://github.com/godotengine/godot/issues/77970

Also fixes an unreported (?) crash that can happen when passing too little data in for certain types using `set_shader_parameter()`. It was caused by incorrect bounds checking which would read and write garbage memory or rarely crash if the read memory was not mapped in the process.

This PR also allows more types to be used with GDScript arrays when calling `set_shader_parameter()`. It relies on the normal Variant behavior to figure out the conversion. Previously, the only thing that worked worked for setting many shader type arrays was creating a raw PackedXXArray.

Array auto-conversion already works for many classes (Vector2, Vector3 etc.) that have their own PackedXXXArray. For example there is PackedVector3Array. But some classes like Vector4, Transform2D, Transform3D, Basis, Projection etc. don't have these and thus did not receive the Variant array auto-conversion goodies. This PR adds some of that conversion behavior without adding new PackedXXXArray's for each class.

I created a new file for the conversion functions that is shared between Vulkan and OpenGL renderer. There are other files in there that are shared like that, but let me know if I should put the functions somewhere else.

I'm not 100% sure if this PR breaks compatibility if user has previously saved some global shader values in the project settings. After a some quick testing I think not, but someone more familiar with that area might need to confirm.

**edit 2:**

I also updated some more uniform/global conversions, some of them haven't worked at all in a long time, but I guess nobody either used them or bothered to make a bug report. Also, here's a simple test project that can be used to test this functionality:

~~[UniformTest.zip](https://github.com/godotengine/godot/files/11221490/UniformTest.zip) (OLD test project)~~

~~[UniformTester.zip](https://github.com/godotengine/godot/files/11285405/UniformTester.zip)~~

[UniformTester3.zip](https://github.com/godotengine/godot/files/11592136/UniformTester3.zip) (NEWEST test project)

This test project was generated in master branch (d6dde819be6e02de133fe1b9f97c8fa6ce8668bb) and contains all incorrect global uniform and shader uniform types and data saved to main.tscn and project.godot. Opening and running the project will show a black box in the master, as the data is not converted properly. After applying this PR, the box should be green in editor (this test saved resource data conversion) and dark blue when run pressing F5 (this test runtime `Shader.set_shader_parameter()` conversion). The cube also moves once per second to test some x, y and z values. The cube also rotates when demo is run (not in editor mode).

NOTE: When using Compatiblity renderer, remove or comment out line `#define GLOBALS_CHECK` in uniforms.gdshader, seems like all global uniforms are not yet supported there (or they are buggy).

### CODE REVIEW

File: editor/shader_globals_editor.cpp [hunk 1]
```diff
@@ -198,7 +198,7 @@ class ShaderGlobalsEditorInterface : public Object {
 					pinfo.type = Variant::COLOR;
 				} break;
 				case RS::GLOBAL_VAR_TYPE_MAT2: {
-					pinfo.type = Variant::PACKED_INT32_ARRAY;
+					pinfo.type = Variant::PACKED_FLOAT32_ARRAY;
```
[the remark this answers is not in the document]
Comment (bitsawer) [reply editor/shader_globals_editor.cpp:201]: Fixed IVEC4 and UVEC4 too and pushed changes. I also re-checked the other types and switches, but I didn't spot any more obviously wrong types.

**Review by clayjohn — DISMISSED** [review]
I'm happy with the changes. 

it would be nice to have @Chaosus take a look and confirm that the array stuff is correct

**Comment by LaneSun** [comment]
Thanks for the work, it helps a lot.

**Review by Chaosus — DISMISSED** [review]
Seems fine for me, and the code looks much cleaner now.

**Comment by bitsawer** [comment]
Fixed a few more types in `shader_language.cpp` and also added a compatibility Color conversion to `convert_array_std140()` for Color types which fixes https://github.com/godotengine/godot/issues/76157. Note that only the Vulkan renderer needs the srgb-to-linear conversion part. However, the real fix is probably to investigate why the PackedColorArray is serialized as a variant Array containing Color-variants instead of PackedColorArray (see https://github.com/godotengine/godot/issues/76157#issuecomment-1510822139). Still, adding that Color handling is also generally useful and also adds some backwards compatibility.

It's pretty clear by now that this PR breaks compatibility to some extent, but I think its worth it. Previously too many things were just broken in some way and there is no easy way to add backwards conversion compatibility everywhere. However, most issues should be pretty easy to fix as long as we tell users to where to look during out next release.

If we want to be super careful about maintaining compatibility, the only reliable way is to pretty much to add more conversions to Variant. For example, currently Quaternion or Plane does not automatically convert to Vector4 etc.

**Comment by YuriSizov** [comment]
@clayjohn @Chaosus Can you take a look again?

> However, most issues should be pretty easy to fix as long as we tell users to where to look during the next release.

Can you provide a list of what the incompatible changes are and how do you propose to address them in user projects?

**Comment by YuriSizov** [comment]
> Then again #75701 was a breaking change and that was done just to improve performace.

Ultimately, it wasn't, the old notification value was kept in the engine specifically to avoid breaking compat. The behavior changed though, that is true.

**Comment by clayjohn** [comment]
I think most of the changes that could be considered breaking are also places where the current behaviour is totally broken. Like changing the type on the global shader vec4 makes sense because currently it is totally broken and leaks garbage

**Comment by bitsawer** [comment]
Rebased and updated the PR. It should now be 100% compatible with old projects. I also updated the example project and its description in the first post, it tests uniform combination values and types that are affected by this PR (including saved global and Shader resource uniform data). Also tested bug report MRP projects, this PR seems to fix them all.

As a result of allowing much better type conversion with good backwards compatibility, I had to clean up the code a bit more. The templated conversion code is more complex than the current one, but it's either that or adding a few thousand lines of copy-paste Variant cross-type conversions. Changes also make it trivial to add support for new Variant or uniform types in the future and they should automatically receive full conversion support.

Previously, there were also several indexing errors in those uniform conversion loops as mentioned before (BVECX heap over-reads, wrong loop step counter in UVEC4 resulting in reading heap garbage etc.). I also made a few minor empty line additions and removals to make the two `material_storage.cpp`-files look more similar and consistent, easier to compare side-by-side.

Also noticed and fixed a subtle (unreported?) bug between Vulkan and OpengGL storage, for example passing Vector2/3/4(i), Quaternion or Plane would sometimes lead to different or bad values in vec4 uniforms. The `material_storage.cpp` files had gotten out-of-sync and the order of type checks in vec4 branch was different, which caused several incorrect type conversion combinations in OpenGL compatibility renderer.

Also fixes https://github.com/godotengine/godot/issues/75191 (added to first post). The vec4 values remain the same in resource file, but now in the editor there is a revert button which will fix the vec4 values to correct defaults (as the editor notices that old incorrect default value is not currently correct).

Also fixes https://github.com/godotengine/godot/issues/66619 (added to first post).

While I tested this a lot, there might still be some subtle bugs around. Still, this PR should improve the current situation significantly.

**Comment by bitsawer** [comment]
Also fixes https://github.com/godotengine/godot/issues/63064 and https://github.com/godotengine/godot/issues/74680 (added to first post). I made (and reverted) a separate PR for those (https://github.com/godotengine/godot/pull/76438), but as some uniforms have a wrong type currently that fix should be incorporated into this PR for better backwards compatibility so that all type updates happen at the same commit.

I'll need to test and fix a few small type compatibility issues so that all this stuff works together. Converted to draft until then.

**Comment by bitsawer** [comment]
Finally had some time to go through all issues, MRP projects and demos to verify everything works together. I added a few compatibility tweaks and rebased this PR, it should be fully backwards compatible and I didn't notice any regressions during my testing. Still, there are a lot of changes so something might have slipped past me, but any issues should be easily fixable once someone reports them.

Ready for a review. Also updated the test project in the first post.

File: drivers/gles3/storage/material_storage.cpp [hunk 2]
```diff
@@ -39,32 +39,24 @@
...
-						gui[j] = (r[i] != 0) ? 1 : 0;
-					} else {
-						gui[j] = 0;
-					}
-					gui[j + 1] = 0; // ignored
-					gui[j + 2] = 0; // ignored
-					gui[j + 3] = 0; // ignored
+				PackedInt32Array ba = value;
+				for (int i = 0; i < ba.size(); i++) {
+					ba.set(i, ba[i] ? 1 : 0);
```
Comment (clayjohn) [inline drivers/gles3/storage/material_storage.cpp:57]: Is this necessary? The code seems highly suspicious. It looks like it is copying over the entire ``value`` array, then iterating over it to clean the values, then passing the whole array to a new function to copy each value one-by-one into another array. Could we not convert, clean, and copy all at once as we do now?

Its nice that this templated approach cuts the amount of code in half, but I have a feeling it is forcing us to do way more copies and way more operations to do the same amount of work.

Comment (bitsawer) [reply drivers/gles3/storage/material_storage.cpp:57]: Note that old code does convert+copy+iterate passes too, they are just harder to see. In the old way, these lines:

```cpp
const PackedInt32Array &ba = value;
```

create a new temporary: a PackedInt32Array from a value variant object using Variant conversion. It just binds it as a const reference, but a temporary is still made and allocated. So a full conversion and array allocation is done here, anyway, it's just harder to see. The following manual for-loop is replaced by `write_array_std140(`), but they do the same thing. The amount of work done should be roughly the same between the old and new code. And when passed the same values, the new code does not really do any more conversions than the old one, there is a fast path in `convert_array_std140()` for many packed arrays. The only extra copying comes when passing more complex object arrays which have to allocate some temporary extra space, but these didn't work at all in the old code. I suspect because doing these conversions for arbitrary arrays and objects properly is actually pretty hard, as evident. I though about special casing all types and use internal variant accessors in variant_internal.h to handle these conversions without temporary copies, but it turned out that kind of code is even harder to write, read and understand.

The only exception here is indeed the boolean uniform handling (bool, bvec2, bvec3, bvec4), which has to do extra work for the "force to 1 or 0"-loop. However, the only extra cost is the loop (which is typically much less than 100 elements), because the temporary COW packed array is already made and its CowData reference count is 1, which means it doesn't have to copy anything when written into because it is already a non-shared copy which had to be made anyway (both in old and new versions).

In practice, it shouldn't have much effect on performance, but uniform boolean conversions are probably is a bit slower than the original version for the same arguments. Of course, I doubt many people actually use uniform boolean in the first place. However, to match the original performance and not make copy of the COW vector, I could write:

```cpp
const PackedInt32Array &ba = convert_array_std140<Vector2i, int32_t>(value);
write_array_std140<Vector2i>(ba, gui, p_array_size, 4);
for (int = 0; i < p_array_size * 4) {
    gui[i] = gui[i] ? 1 : 0;
}
```

It still makes one extra loop over the data, but as uniform arrays are not usually very large in practice it shouldn't matter too much. Alternatively, we could add an optional lambda function converter to inline the conversion into the copy loop, which the compiler can optimize nicely:

```cpp
const PackedInt32Array &ba = convert_array_std140<Vector2i, int32_t>(value);
write_array_std140<Vector2i>(ba, gui, p_array_size, 4, [](int32_t value) { return value ? 1: 0 });
```

With this version, the performance should be pretty much identical. Or we could leave the new code as-is, it's pretty simple to understand this way with a pretty minimal performance penalty.

Comment (clayjohn) [reply drivers/gles3/storage/material_storage.cpp:57]: Thank you for the detailed response. I didn't realize that ``const PackedInt32Array &ba = value;`` was copying the entire array.

Indeed the boolean arrays are the worst offenders in terms of copying necessarily, but they are also the cheapest to copy and likely won't be that large. 

I'm happy with the current state of things in that case. I would avoid making it any more complicated. Already this PR adds significant complexity by adding layers of templated functions. I understand that was done in order to make handling all the edge cases manageable, but adding more complexity will make this impossible to debug six months from now.

**Review by clayjohn — APPROVED** [review]
Seeing as my only concern turned out to be my misunderstanding, I am happy to go ahead with this PR. I trust that @bitsawer has properly handled things and this is a significant improvement over the status quo. 

I would go ahead and merge this so we can get wide testing before releasing 4.1

**Comment by akien-mga** [comment]
Thanks a ton!
