### PR TITLE
GDScript: Fix cached parser error when using typed Dictionaries

### LINKED ISSUE #96881: [4.4 dev2] Compile Error: Identifier not found (parser bug) when accessing typed dictionary value's members and functions
### Tested versions

- Reproducible in 4.4 dev2

### System information

Godot v4.4.dev2 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 (NVIDIA; 32.0.15.6094) - AMD Ryzen 7 5700X 8-Core Processor (16 Threads)

### Issue description

image
Relevant log:
```
  res://globals/resources/quests/test.gd:8 - Parse Error: Parser bug (please report): Could not find external parser for class "Step". (Trying to resolve class member)
```

When iterating over a typed dictionary using the `for key in typed_dict: ...` syntax, accessing the dictionary value's:

- signals
- members including enums, and
- functions

Causes the above error to be produced. In most cases, the error can be worked around by assigning the typed dictionary's value to an intermediate variable. Sometimes explicit typing is required - see the examples below to see what works and what doesn't.

### Steps to reproduce

```gdscript
class_name Step extends Resource

signal test_step(param: String)

@export var step_id: String

func nop() -> void:
	pass
	
func get_id() -> String:
	return step_id

enum StepState {
	ACTIVE
}

```

```gdscript
class_name Parent extends Resource

@export 
var steps: Dictionary[String, Step]
```

```gdscript
# Test class for https://github.com/godotengine/godot/issues/96881
# Uncommenting any of these functions yield a GDScript compile error
extends Node

func _on_connect() -> void:
	pass

#func _connect_signal(parent: Parent) -> void:
	#for step_id: String in parent.steps:
		#parent.steps[step_id].test_step.connect(_on_connect)
		## But this works! (with or without type)
		#var x = parent.steps[step_id]
		#x.test_step.connect(_on_connect)
		


#func access_member(parent: Parent) -> void:
	#for step_id: String in parent.steps:
		#parent.steps[step_id].step_id
		## This doesn't work either
		#var x: String = parent.steps[step_id].step_id
		## Neither does this
		#var x: String = parent.steps[step_id].step_id as String
		## But this works! (with or without type)
		#var x = parent.steps[step_id]
		#x.step_id
		
#func call_func(parent: Parent) -> void:
	#for step_id: String in parent.steps:
		#parent.steps[step_id].nop()
		## This doesn't work either
		#var id = parent.steps[step_id].get_id()
		## This doesn't work...
		#var x = parent.steps[step_id]
		#x.get_id()
		## But this works!
		#var x: Step = parent.steps[step_id]
		#x.get_id()


#func access_enum(parent: Parent) -> void:
	#for step_id: String in parent.steps:
		#parent.steps[step_id].StepState
		## This doesn't work either
		#var state = parent.steps[step_id].StepState
		## But this works!
		#var state: Step.StepState = parent.steps[step_id].StepState

```

### Minimal reproduction project (MRP)

See above.

### PR DESCRIPTION
**Pull request by rune-scape**
fixes https://github.com/godotengine/godot/issues/96881

a small mistake from https://github.com/godotengine/godot/pull/94871 where i only checked the first of the container types

also added a message to `ensure_cached_external_parser_for_class` explaining its function

### CODE REVIEW

**Comment by tracefree** [comment]
Can confirm this fixes the issue for me!

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -3816,6 +3816,12 @@ GDScriptParser::DataType GDScriptAnalyzer::make_global_class_meta_type(const Str
 }
 
 Ref<GDScriptParserRef> GDScriptAnalyzer::ensure_cached_external_parser_for_class(const GDScriptParser::ClassNode *p_class, const GDScriptParser::ClassNode *p_from_class, const char *p_context, const GDScriptParser::Node *p_source) {
+	// Delicate piece of code that intentionally doesn't use the GDScript cache or `get_depended_parser_for`.
+	// Search dependencies for the parser that owns p_class and make a cache entry for it.
```
Comment (dalexeev) [inline modules/gdscript/gdscript_analyzer.cpp:3820]:
```suggestion
	// Search dependencies for the parser that owns `p_class` and make a cache entry for it.
```

**Review by dalexeev — APPROVED** [review]
Looks good to me. I haven't tested this, but it seems reasonable. Also @rune-scape is the original author of the code and @tracefree confirmed that this fixes the issue.

**Comment by clayjohn** [comment]
Thank you!
