### PR TITLE
Fix rename animation in SpriteFramesEditor

### LINKED ISSUE #73883: SpriteFrames window renaming animation to empty still causes error and spurious naming conflict if already "new_animation"
### Godot version

v4.0.rc4.official [e0de3573f]

### System information

Linux Ubuntu 20.04 with Unity desktop

### Issue description

Following PR https://github.com/godotengine/godot/pull/70788 solving issue https://github.com/godotengine/godot/issues/70769, there are still a few bugs remaining.

1. Editing any animation name to empty string will auto-fix it with "new_animation[suffix]" as expected, but still show the Output error just before: 

> Animation '' doesn't exist.
Rename Animation

2. Renaming an animation already named "new_animation[suffix]" will consider the old name to be reserved, causing a conflict with itself and increment the suffix without needing to. For instance, "new_animation" -> empty string will become "new_animation_1". If "new_animation_1" already exists, it will become "new_animation_2", etc.

Basically, it should behave as if the user actually input "new_animation" instead of empty string. Looking at https://github.com/godotengine/godot/pull/70788/commits/62976659b8aa9a582550b5a19d0ea1b3af494912 I'd say that the empty -> "new_animation" fallback should be done earlier, before `if (new_name == String(edited_anim))` to fix 2. and before `if (!frames->has_animation(edited_anim))` to fix 1. But I'm not sure of possible side effects, so this needs to be tested.

### Steps to reproduce

1. In any project: create new Sprite Frames resource
2. In SpriteFrames window: you'll see "default" animation. Try to rename it to empty string -> becomes "new_animation" as it should.
3. Check the Output console: observe error "Animation '' doesn't exist."
4. Rename the animation to empty string again. This time, it becomes "new_animation_1".
5. Try various combinations of existing suffixes by adding new animations multiple times, and observe how number resolution by increment occurs as usual, but unnecessarily skipping the very animation that is renamed.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Rindbee**
When the name suffix grows, the old name is used if it is obtained first.

Fix the case where the following error message would appear when renaming an animation.

```
ERROR: Animation '' doesn't exist.
   at: get_frame_count (scene/resources/sprite_frames.cpp:71)
```

Fix #73883.

### CODE REVIEW

File: editor/plugins/sprite_frames_editor_plugin.cpp [hunk 1]
```diff
@@ -949,13 +949,16 @@ void SpriteFramesEditor::_animation_name_edited() {
 	String name = new_name;
 	int counter = 0;
 	while (frames->has_animation(name)) {
+		if (name == String(edited_anim)) {
+			edited->set_text(0, name); // The name didn't change, just updated the column text to name.
+			return;
+		}
```
Comment (TokageItLab) [inline editor/plugins/sprite_frames_editor_plugin.cpp:955]: Must be coded out of the while.

**Review by TokageItLab — CHANGES_REQUESTED** [review]

File: editor/plugins/sprite_frames_editor_plugin.cpp [hunk 2]
```diff
@@ -949,13 +949,16 @@ void SpriteFramesEditor::_animation_name_edited() {
...
 		counter++;
 		name = new_name + "_" + itos(counter);
 	}
 
 	EditorUndoRedoManager *undo_redo = EditorUndoRedoManager::get_singleton();
 	undo_redo->create_action(TTR("Rename Animation"), UndoRedo::MERGE_DISABLE, EditorNode::get_singleton()->get_edited_scene());
-	_rename_node_animation(undo_redo, false, edited_anim, "", "");
```
Comment (TokageItLab) [inline editor/plugins/sprite_frames_editor_plugin.cpp:958]: To be honest, I don't really remember what this initialization was implemented for. The `_rename_node_animation()` is a method to change the animation name kept in other properties of AnimatedSprite, but without it, it is possible to have some inconsistencies in some properties, so it should be tested carefully.

File: editor/plugins/sprite_frames_editor_plugin.cpp (hunk 1 above)
Comment (Rindbee) [reply editor/plugins/sprite_frames_editor_plugin.cpp:955]: This is for the case:
"animation_4" => "animation"
And "animation", "animation_1" ... "animation_3" already exists

https://github.com/godotengine/godot/assets/30386067/74c7c5f3-ef3e-4f0a-a772-b39e36a7b562

File: editor/plugins/sprite_frames_editor_plugin.cpp (hunk 2 above)
Comment (Rindbee) [reply editor/plugins/sprite_frames_editor_plugin.cpp:958]: The previous code will rename `name` to a non-empty value. Even though it would have side effects, I feel like it could be done in the call on line 961.

https://github.com/godotengine/godot/blob/57919beb05687cf2ee80ed0d3ccac6445c7edea9/editor/plugins/sprite_frames_editor_plugin.cpp#L958-L962

File: editor/plugins/sprite_frames_editor_plugin.cpp (hunk 1 above)
Comment (TokageItLab) [reply editor/plugins/sprite_frames_editor_plugin.cpp:955]: Indeed. Then this would need to be placed "after" the while loop considering the following cases:

1. There is anim, anim1, anim3, anim4
2. Rename anim4 -> anim
3. After while loop it should be anim2, means renamed

At this time, checks during the while loop are redundant.

Comment (Rindbee) [reply editor/plugins/sprite_frames_editor_plugin.cpp:955]: For another case:
1. There is anim, anim_1, anim_2, anim_4
2. Rename anim_2 -> anim 
3. Without this check, it might be renamed to anim_3
4. The result: anim, anim_1, anim_3, anim_4


https://github.com/godotengine/godot/assets/30386067/5ce988db-9547-4a93-92c5-823af5b620d5

When renaming, the old name already exists, so it will be skipped.

Comment (TokageItLab) [reply editor/plugins/sprite_frames_editor_plugin.cpp:955]: Oh, you are right. However, this suffix method is also used for state_machine, so the same fix is needed there as well.

**Review by TokageItLab — APPROVED** [review]
I don't know what affect deleting the `_rename_node_animation(undo_redo, false, edited_anim, "", "");` would have. Perhaps it was there to prevent some error when trying to use a space in the name, but rather it seems to be triggering an error and should be removed. If this removing causes other errors, that should be resolved in another way.

Well, I tested this and it seems to work fine, so I believe this can be merged.

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.4.
