### PR TITLE
GDScript: Fix constant conversions

### LINKED ISSUE #70861: randi() % a const pow(2, 32) that is cast to an int crashes Godot with no console output or errors
### Godot version

4.0 beta 10

### System information

Windows 11

### Issue description

This is weird, but I was trying to make the personality value for a pokemon and it crashed with no console output or errors.

It doesn't crash if:
* randi() is not present
* % is not present
* MAX_PERSONALITY_VALUE is a variable not a constant
* I put `randi() % int(pow(2, 32))` instead

### Steps to reproduce

this code
```
extends Node2D

const MAX_PERSONALITY_VALUE: int = pow(2, 32) # Not inclusive

func _ready() -> void:
	print(randi() % MAX_PERSONALITY_VALUE)
```

### Minimal reproduction project

none

### LINKED ISSUE #71255: Crash and weird behavior when using const packed arrays
### Godot version

4.0b11, 0abd60b9530d574fc8fc466e6a3f0c5b9814f697

### System information

Windows 10, RTX 2060, Vulkan

### Issue description

Trying to iterate over a const PackedStringArray in an _init() function causes silent crash. PackedInt32 + PackedInt64Arrays don't have the correct values.

Not fixed by #71228

### Steps to reproduce

Try to run this code (note: same issues exist using _ready() as well):
``` swift
extends Node

const array: Array = ["hello", 1234, 1.234]
const packed32: PackedInt64Array = [5034, 4343, 10101]
const packed64: PackedInt64Array = [5034, 4343, 10101]
const packed_string: PackedStringArray = ["hello", "goodbye", "testing"]

func _init():
	print_debug("about to iterate over array")
	for thing in array:
		print(thing)
	print_debug("about to iterate over packed32")
	for thing in packed32:
		print(thing)
	print_debug("about to iterate over packed64")
	for thing in packed64:
		print(thing)
	print_debug("about to iterate over packed_string")
	for thing in packed_string:
		print(thing)
```
which gives this output:
```
Godot Engine v4.0.beta.custom_build.0abd60b95 - https://godotengine.org
Vulkan API 1.3.224 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2060 with Max-Q Design

about to iterate over array
   At: res://main.gd:9:_init()
hello
1234
1.234
about to iterate over packed32
   At: res://main.gd:12:_init()
249108103170
10101
0
about to iterate over packed64
   At: res://main.gd:15:_init()
249108103170
10101
0
about to iterate over packed_string
   At: res://main.gd:18:_init()

================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.0.beta.custom_build (0abd60b9530d574fc8fc466e6a3f0c5b9814f697)
```

### Minimal reproduction project

[static-packed.zip](https://github.com/godotengine/godot/files/10397193/static-packed.zip)

### LINKED ISSUE #71483: Atomic storage crash on script execution
### Godot version

4.0.dev (9711abe78773426644b640d6052273203931555e) and (a6ddee9c00f76792632f43938a2c881cd9308e16)

### System information

Windows 11, Nvidia 1070

### Issue description

Happens 100% of the time on windows. I'll report soon if it also happens in linux.

image

### Steps to reproduce

Execute my project, when a script without reported errors is used. 

### Minimal reproduction project

I'll try to make one, but it can take a long time, since the project is big and bisection takes long.

### LINKED ISSUE #71635: const PackedArrays iteration issue
### Godot version

4 beta 13 & 12

### System information

Windows 10

### Issue description

can't properly iterate over const packed arrays, you can see the output will be a default initialized value and the last element of the array in beta13 and in 12 it will be similar with but with the other elements represented as what seem to be uninitialized memory (random numbers)

### Steps to reproduce

Start a new Project
Add any node and a script to it
add something like this to see it:

```
const array : PackedVector2Array = [Vector2(0,0),Vector2(1,1),Vector2(2,2),Vector2(3,3)]

func _ready() -> void:
	for i in array:
		print(i)
```

### Minimal reproduction project

"N/A" would be faster for you to check in your own projects

### LINKED ISSUE #72209: Callable: Not nullable, inconsistent behaviour
### Godot version

v4.0.beta16.official [518b9e580]

### System information

Windows 11

### Issue description

The new Callable has a few issues/inconsistencies around nullability:

1. Callables can be assigned `null`, but it fails at runtime.
  > `Trying to assign value of type 'Nil' to a variable of type 'Callable'`
  Static analysis does not currently find this issue.
2. Callables have a method `is_null()`, but right now, they cannot be `null`.
  a. What is the purpose of this method, if Callables cannot be `null`?
  b. As an alternative, there is also `is_valid()`
3. Function declarations with an optional `Callable` parameter need to define them by instantiating a `Callable()` with it's default constructor

# How should it work?
Either:
* Callables could/should be `null`able
or
* Static analysis should not allow assignment of `null` to a `Callable`
  And should potentially hint at using an instance with the default constructor.

## Failing Scenario
1. Create a function which accepts an optional parameter of type `Callable`, by setting it's default to `null`
  ```gdscript
func call_me_not_working_optional_param(callback: Callable = null):
	var test: Callable	
	test = null	
	if callback != null && callback.is_valid():
		callback.call()
		print("called")
	else:
		print("not called")
  ```
2. Call `call_me_not_working_optional_param()`
3. Start the build in debug
4. When The code is executed, an error is thrown:
  > `Trying to assign value of type 'Nil' to a variable of type 'Callable'`

### Minimal reproduction project

[godot4-callable-null.zip](https://github.com/godotengine/godot/files/10523453/godot4-callable-null.zip)

### PR DESCRIPTION
**Pull request by vonagam**
A constant value can be converted to a specified type during analysis, not at runtime every time.

```gdscript
var x: StringName = 'a' # initializer

x = 'b' # assignment

func print_name(y: StringName): print(y)
print_name('c') # call argument

func make_name() -> StringName: return 'd' # return

var z := 'c' as StringName # cast
```

Out of those places only variable initializer was handled at compile time before. 

Initializer for constants was not converted at all which was leading to many crash reports.

While at it, allowed a cast to be considered as constant expression under certain circumstances (which will be expanded with array PR from which code for this PR partially comes from).

Fixed minor things with casts and arguments validations.

Fixes #70861.
Fixes #71255.
Fixes #71483.
Fixes #71635.
Fixes #72209.

Related to #70872 (supersedes).
Related to #70873 (supersedes).

### CODE REVIEW

**Comment by dalexeev** [comment]
This PR does not fully supersede #70873, as there are more changes to `resolve_assignable()`, not just the part that can be replaced by `update_const_expression_builtin_type()` call.

**Comment by vonagam** [comment]
Hm. So I assume that the thing that wasn't included here was a fix for incorrect check of asymmetric compatibility - String can be converted to Color, but other way around will never work. Yeah, wrong argument was passed to `is_type_compatible` (`true` instead of `false`) in reverse check (that should cover only objects). Updated the PR and fixed the same thing in assignments.

Was there anything else that is missing?

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -2063,6 +2069,59 @@ void GDScriptAnalyzer::reduce_array(GDScriptParser::ArrayNode *p_array) {
 	p_array->set_datatype(arr_type);
 }
 
+void GDScriptAnalyzer::update_const_expression_builtin_type(GDScriptParser::ExpressionNode *p_expression, const GDScriptParser::DataType &p_type, const char *p_usage, bool p_is_cast) {
+	if (p_expression->get_datatype() == p_type) {
+		return;
+	}
+	if (p_type.kind != GDScriptParser::DataType::BUILTIN && p_type.kind != GDScriptParser::DataType::ENUM) {
+		return;
+	}
```
Comment (dalexeev) [inline modules/gdscript/gdscript_analyzer.cpp:2078]: I'm not sure if a silent return here is correct. It seems to me that either `ERR_FAIL_COND` is needed here, or the method should return `bool`.

Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp:2078]: This is not an error case, if an expected type is not built-in or enum (so a variant or an object) then there is nothing to do - no conversion will take place. There are checks afterwards in all corresponding places that deal with checking that types do match. 

Usage of the method assumes that you call it before storing the resulting type of an expression, like `update_array_literal_element_type` and `reduce_expression`, no need to return booleans.

**Comment by dalexeev** [comment]
> Is there anything else that is missing?

1. Some tests are missing.
2. I think in my PR the code has been reorganized to be more readable: first the status is determined (`SAFE`, `UNSAFE`, `ERROR`) and then actions are performed depending on this. This can help avoid mistakes in the future.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 2]
```diff
@@ -2063,6 +2069,59 @@ void GDScriptAnalyzer::reduce_array(GDScriptParser::ArrayNode *p_array) {
...
+
+	GDScriptParser::DataType value_type = type_from_variant(p_expression->reduced_value, p_expression);
+	if (expression_type.is_variant() && !is_type_compatible(p_type, value_type, true)) {
+		push_error(vformat(R"(Cannot %s a value of type "%s" as "%s".)", p_usage, value_type.to_string(), p_type.to_string()), p_expression);
+		return;
+	}
+
+	if (p_type.kind == GDScriptParser::DataType::ENUM && value_type.builtin_type == Variant::INT && enum_get_value_name(p_type, p_expression->reduced_value) == StringName()) {
+		if (expression_type.kind == GDScriptParser::DataType::ENUM) {
+			push_error(vformat(R"(Cannot %s "%s.%s" as Enum "%s": no corresponding enum member has the same value (%d).)", p_usage, expression_type.enum_type, enum_get_value_name(expression_type, p_expression->reduced_value), p_type.to_string(), (int64_t)p_expression->reduced_value), p_expression);
```
Comment (dalexeev) [inline modules/gdscript/gdscript_analyzer.cpp:2094]: I think this should be a warning, not an error (so as not to create false expectations for the user), since in other cases it is not guaranteed that the value of a variable of type `MyEnum` will be from `MyEnum.values()`.

Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp:2094]: This case happens in casts when a value of one enum casted to represent another.
This is preexisting logic.
Don't understand why would you want it to be a warning instead of an error.
```gdscript
enum A { X = 0 }
enum B { Y = 1 }
var b := A.X as B
```

Comment (dalexeev) [reply modules/gdscript/gdscript_analyzer.cpp:2094]: There is no guarantee that a variable of type `MyEnum` cannot contain an arbitrary `int`. It is wrong that in some cases this is an error, and in others a warning.

```gdscript
enum MyEnum {
    VALUE_A,
}

func _run() -> void:
    var x: int = 42
    var a: MyEnum = x # Warning, not an error.
    print(a) # 42
```

Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp:2094]: In your case it will not apply `var x` is not a constant.

Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp:2094]: `42` is a constant in that case. And there is no value 42 in `MyEnum`. How is it not an error?

Comment (dalexeev) [reply modules/gdscript/gdscript_analyzer.cpp:2094]: I wrote above. Enums are mostly an alias for `int`. An error **in this case** may give the user the impression that they cannot assign the wrong number **at all**. But this is not true in general.

Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp:2094]: Enum is a quasi-opaque type: an enum value is an int, but an int is not an enum. That's why there is a warning (when we don't know if there is a mismatch) and an error (when we do know that). Enum is not just an alias for int, it has its own type. 

Why type it `MyEnum` and not `int` if you want to assign random values to it?

Comment (dalexeev) [reply modules/gdscript/gdscript_analyzer.cpp:2094]: If the variable `a` **can be** equal to `42` (and this is true), then we should not forbid it in some particular cases, while in other cases there will be no error. We need to warn the user that they are doing something wrong (when we can detect it).

Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp:2094]: I mean `a` should not be ever equal to `42` in your example. I guess, there are missing checks in runtime to give an error when `42` is assigned to a variable of type `MyEnum`. I think it is just because enum information is stripped in runtime, maybe it was changed and it is possible to give an error now.

I recommend asking about what enum type represent in developer chat.

Comment (dalexeev) [reply modules/gdscript/gdscript_analyzer.cpp:2094]: See also [the comment](https://github.com/godotengine/godot/issues/71763#issuecomment-1399234932).

Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp:2094]: Ok, I asked in developer chat to clarify what does enum type represent.

But if you think that any int can be assigned to an enum type, then why do you think that there should be a warning then?

Comment (dalexeev) [reply modules/gdscript/gdscript_analyzer.cpp:2094]: Because it can give users false assumptions about what an enum is in GDScript. Errors should be only for those things that are not allowed in principle. If something is possible but wrong, then it should be a warning, not an error.

Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp:2094]: I mean if it is wrong then you make it an error to make it impossible. Why allow wrong code?

Comment (dalexeev) [reply modules/gdscript/gdscript_analyzer.cpp:2095]: I think we don't understand each other. I wrote above several times why I think so.

This is wrong code in the "shouldn't do this" sense, but not in the "can't do this" sense.

Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp]: Done. It is a warning now, not an error.

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Needs rebase.

**Comment by akien-mga** [comment]
Needs another rebase to pass CI, I fixed the GDScript test error.

**Comment by akien-mga** [comment]
Thanks!
