### PR TITLE
Fix crash on invalid values in EditorPropertyArray/Dict

### LINKED ISSUE #78630: Export variable of array type will ignore its own type and use the value's type when pasting value
### Godot version

v4.0.stable.official [92bee43ad], v4.1.beta.custom_build [19e7490c9]

### System information

 Linux Mint 21.1 (Vera) - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (nvidia; 515.105.01) - Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 Threads)

### Issue description

https://github.com/godotengine/godot/assets/30386067/679412c0-cce2-4874-af40-644449fe30e5

Export variable of array type will ignore its own type and use the value's type when pasting a value of a different type.

```
ERROR: Invalid method 'size' for type 'int'.
   at: _variant_call_error (core/variant/variant.cpp:3625)
ERROR: Invalid method 'resize' for type 'int'.
   at: _variant_call_error (core/variant/variant.cpp:3625)
```

### Steps to reproduce

1. Export an array;
2. Copy a value from another property of a different type;
3. Paste into that exported variable;
4. An error message will be output, but it still looks like an Array in the Inspector.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by ajreckof**
Fixes https://github.com/godotengine/godot/issues/78630#issuecomment-2039805841

### CODE REVIEW

File: editor/editor_properties_array_dict.cpp [hunk 1]
```diff
@@ -328,6 +328,7 @@ void EditorPropertyArray::update_property() {
 			memdelete(container);
 			button_add_item = nullptr;
 			container = nullptr;
+			slots.clear();
```
Comment (ajreckof) [inline editor/editor_properties_array_dict.cpp:331]: this part missing was the one creating the crash

File: editor/editor_properties_array_dict.cpp [hunk 2]
```diff
@@ -586,7 +587,7 @@ void EditorPropertyArray::_edit_pressed() {
 	Variant array = get_edited_property_value();
 	if (!array.is_array() && edit->is_pressed()) {
 		initialize_array(array);
-		get_edited_object()->set(get_edited_property(), array);
+		emit_changed(get_edited_property(), array);
```
Comment (ajreckof) [inline editor/editor_properties_array_dict.cpp:590]: this would have caused problem on nested arrays

File: editor/editor_properties_array_dict.cpp [hunk 3]
```diff
@@ -867,14 +868,15 @@ void EditorPropertyDictionary::setup(PropertyHint p_hint) {
 void EditorPropertyDictionary::update_property() {
 	Variant updated_val = get_edited_property_value();
 
-	if (updated_val.get_type() == Variant::NIL) {
+	if (updated_val.get_type() != Variant::DICTIONARY) {
```
Comment (ajreckof) [inline editor/editor_properties_array_dict.cpp:871]: this is to not only check for `null` but for anything that wouldn't be treated well (only dictionary is expected) just as `EditorPropertyArray` checks with `is_array`.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
