### PR TITLE
Fix i18n of 3D view name

### LINKED ISSUE #50742: Difficulties when translating 3D view name
### Godot version

3.3.2, 3.4.beta1, 3.x(883bb2f4f6), 4.0(5de991d57c)

### System information

macOS 11.4

### Issue description

Name is shown on the top left corner of each 3D viewport, like "Top Orthognal". But i18n and l10n are done separately on each word and then joined with a space.

This is OK in English, but in languages like Chinese, the space is not needed. There is no way to get rid of the space because it's hardcoded.

Wording & order may also be different depending on the context in other languages. "Top Orthognal" may not always be "Top" + "Orthognal". For example, Top - 顶部,  Orthognal - 正交, but Top Orthognal should be 正交顶视图 in Chinese, which swaps the order and changes the words when used together.

Currently, "thanks" to the space, "顶部 正交" makes sense if you think it's displaying two separate fields. But it's not ideal since Top Orthognal is always 正交顶视图 in other 3D softwares (e.g. Blender).

### Steps to reproduce

Open the 3D editor in Chinese.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by timothyqiu**
Make the full view name translatable as a whole instead of combining from sub-strings.

Fixes #50742.

### CODE REVIEW

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -809,18 +809,66 @@ void Node3DEditorViewport::_select_region() {
...
+		} break;
 	}
 
-	if (name != "") {
-		view_menu->set_text(name + " " + view_mode);
-	} else {
-		view_menu->set_text(view_mode);
+	if (auto_orthogonal) {
+		// TRANSLATORS: This will be appended to the view name when Auto Orthogonal is enabled.
+		name += TTR(" [auto]");
```
Comment (akien-mga) [inline editor/plugins/node_3d_editor_plugin.cpp:868]: How does this work for RTL languages? Should it be prepended instead? CC @bruvzg

Comment (timothyqiu) [reply editor/plugins/node_3d_editor_plugin.cpp:868]: IINM, RTL texts are stored in the order in which they are read, so this would be fine if they are localized.

Comment (bruvzg) [reply editor/plugins/node_3d_editor_plugin.cpp:868]: It is OK, text is stored in the logical order.

**Review by YeldhamDev — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
