### PR TITLE
Fix issues with `InputMap::load_from_project_settings()` when called in tool script

### LINKED ISSUE #103539: ERROR: The InputMap action "spatial_editor/viewport_pan_modifier_1" doesn't exist
### Tested versions

4.4 Stable.

### System information

ERROR: The InputMap action "spatial_editor/viewport_pan_modifier_1" doesn't exist.    at: (core/input/input.cpp:373)

### Issue description

As of upgrading to 4.4, every time I move my mouse inside of my 3d scene, I am hit with the following error message:

The below is the extent of the error message from godot -e -v.

ERROR: The InputMap action "spatial_editor/viewport_pan_modifier_1" doesn't exist.
   at: (core/input/input.cpp:373)

### Steps to reproduce

I'm sorry, but I actually don't know how to reproduce this. The error occurs every time I move my mouse inside of "globe_scene.tscn" in the editor in this project: https://github.com/BluntBSE/subrogue-1

### Minimal reproduction project (MRP)

https://github.com/BluntBSE/subrogue-1

### PR DESCRIPTION
**Pull request by ryevdokimov**
Fixes: https://github.com/godotengine/godot/issues/103539

Supersedes: https://github.com/godotengine/godot/pull/104975, https://github.com/godotengine/godot/pull/101251, and https://github.com/godotengine/godot/pull/101250

Related: https://github.com/godotengine/godot-proposals/issues/11424#issuecomment-2571719418

Currently when `InputMap::load_from_project_settings()` is called it breaks things in the 3D editor viewport because shortcuts relevant to its functionality but are added separately are cleared. The solution is to reload those shortcuts every time this method is called.

### CODE REVIEW

File: editor/scene/3d/node_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -6146,24 +6167,8 @@ Node3DEditorViewport::Node3DEditorViewport(Node3DEditor *p_spatial_editor, int p
...
-	register_shortcut_action("spatial_editor/freelook_left", TTRC("Freelook Left"), Key::A, true);
-	register_shortcut_action("spatial_editor/freelook_right", TTRC("Freelook Right"), Key::D, true);
-	register_shortcut_action("spatial_editor/freelook_forward", TTRC("Freelook Forward"), Key::W, true);
-	register_shortcut_action("spatial_editor/freelook_backwards", TTRC("Freelook Backwards"), Key::S, true);
-	register_shortcut_action("spatial_editor/freelook_up", TTRC("Freelook Up"), Key::E, true);
-	register_shortcut_action("spatial_editor/freelook_down", TTRC("Freelook Down"), Key::Q, true);
-	register_shortcut_action("spatial_editor/freelook_speed_modifier", TTRC("Freelook Speed Modifier"), Key::SHIFT);
-	register_shortcut_action("spatial_editor/freelook_slow_modifier", TTRC("Freelook Slow Modifier"), Key::ALT);
+	_load_viewport_inputs();
+	InputMap::get_singleton()->connect("project_settings_loaded", callable_mp(this, &Node3DEditorViewport::_load_viewport_inputs));
```
Comment (Nintorch) [inline editor/scene/3d/node_3d_editor_plugin.cpp:6359]: Personally I'm not sure if we should have this new signal, it should be possible to call `_load_viewport_inputs()` from `InputMap::load_from_project_settings()`, I think

Comment (ryevdokimov) [reply editor/scene/3d/node_3d_editor_plugin.cpp:6359]: That would require exposing the 3D editor to the core which would be architecturally wrong.

Comment (Nintorch) [reply editor/scene/3d/node_3d_editor_plugin.cpp:6359]: Oops, sorry, I didn't notice this wasn't `input_map.cpp`, my bad! 😅

**Review by Nintorch — APPROVED** [review]
Tested locally, can confirm it does fix the issue for me, code looks good to me!

**Comment by Repiteo** [comment]
Thanks!
