### PR TITLE
[Web] Add IME input support

### LINKED ISSUE #45904: Cannot type dead keys (accented characters) or use Input Method Editor on a LineEdit exported to HTML
**Godot version:**
 Godot v3.2.3

**OS/device including version:**
MacOS exporting to HTML

**Issue description:**
Cannot type dead keys (needed to enter accented characters) inside a LineEdit which has been exported to HTML.

**Steps to reproduce:**
1) Open this project:
https://origamer.itch.io/ortografiator
2) Try to enter any accented character in the input field (a LineEdit).  When you press the dead key (for example ^ or ' or ` or ") nothing will happen, and when you press the vowel key it will appear as a standard vowel, without the accent.

**Minimal reproduction project:**
Any project with a LineEdit.

### PR DESCRIPTION
**Pull request by bruvzg**
Implements IME event handling for Web platform.

- Fixes https://github.com/godotengine/godot/issues/45904

*Bugsquad edit:*
- Addresses Web part of #85597

https://github.com/godotengine/godot/assets/7645683/02ab92c5-b8ad-4571-a282-a7fe9c96a646

### CODE REVIEW

**Review by Faless — COMMENTED** [review]
This looks really nice :partying_face: 

I wonder if this can replace the experimental virtual keyboard support...

I remember I tested the composition events when doing that work, and the browser support was all over the place (missing events, repeated ones, etc) depending on both platform and vendor.

Which OS/browsers did you test?

**Comment by jtodaone** [comment]
I have tested current build of your fork, and these are my findings:

1. Currently does not work on Safari and Chromium-based browsers (I have tested it on Arc) It is essentially the same behavior with 4.2.stable, but here's a bit of a detailed explanation video.

https://github.com/godotengine/godot/assets/7546436/4cd51370-fd60-4320-a2b0-d3bdfab59b5e

2. On Firefox, it is better than stable (which does not use IME at all so it just comes out as English alphabet), but it has some weird behavior.

https://github.com/godotengine/godot/assets/7546436/ea7be2a1-3ff3-4c1d-9947-f9c737c34d62

- Vietnamese and French characters are duplicated.
- When inputting Korean characters, cursor does not advance as it should - it sometimes does advance, but it seems to be random.

**Comment by bruvzg** [comment]
> Which OS/browsers did you test?

Retested it, and it seems to be working only in Firefox. Until Chromium have IME API implemented, we probably won't be able to do anything with it.

> We should probably keep the reference to this instead of assigning it an ID and using selector to retrieve it (which must be page-unique, so ime is also likely to collide with user custom HTML).

Done.

> Vietnamese and French characters are duplicated.
> When inputting Korean characters, cursor does not advance as it should - it sometimes does advance, but it seems to be random.

Both should be fixed in the last commit (by applying the same logic as #85458 use).

**Comment by jtodaone** [comment]
> Retested it, and it seems to be working only in Firefox. Until Chromium have IME API implemented, we probably won't be able to do anything with it.

Out of curiosity, what APIs are missing from Chromium and Safari? compositionstart/update/end are all available in both engines and it seems like they are the only DOM events used by your PR? I am not familiar enough with Godot's source to dig into C++ code changes you've made (I tried 😭) so I might have missed a lot of things.

**Comment by jtodaone** [comment]
I think I am onto something, but I am not sure.

Apparently, Safari just doesn't render any DOM element inside <canvas> so it was acting as if nothing was different.

https://github.com/godotengine/godot/assets/7546436/58a7e1a8-0afd-4c34-8d83-4b8e7bd75c73

After I just moved the element out of the canvas, it started to behave a bit better. It still is acting weird, but it might be because I am using the older build with the issues I talked above. Same behavior on Arc (Chromium) too.

It does not recognize backspace when I did that, so that's new.

**Comment by bruvzg** [comment]
> I think I am onto something, but I am not sure.
>
>Apparently, Safari just doesn't render any DOM element inside <canvas> so it was acting as if nothing was different.

Interesting find, with the `key_up` / `key_down` event handlers added to the `ime` div it seems to be almost fully working in Chromium (the only issue I see is missing caret, which probably rely on canvas being focused).

**Comment by jtodaone** [comment]
> Interesting find, with the `key_up` / `key_down` event handlers added to the `ime` div it seems to be almost fully working in Chromium (the only issue I see is missing caret, which probably rely on canvas being focused).

How are you so fast? 😂 I was figuring out keyup keydown part

It seems to work perfect so far, except I think it will be better if display mode is fixed instead of absolute. Absolute makes viewport overflow.

```js
const ime = document.createElement("div");
      ime.className = "ime";
      ime.style.background = "none";
      ime.style.opacity = 0.0;
      ime.style.position = "fixed";
```

I'd submit PR if it were not just a single word change 😂 but I think it is more of a hassle to merge PR than just replacing a word.

**Review by Faless — COMMENTED** [review]
This is looking great :rocket: .
We are missing some cleanup for the added node, this patch adds that.

```diff
diff --git a/platform/web/js/libs/library_godot_input.js b/platform/web/js/libs/library_godot_input.js
index ec73f3bdb3..7c070f029d 100644
--- a/platform/web/js/libs/library_godot_input.js
+++ b/platform/web/js/libs/library_godot_input.js
@@ -34,6 +34,7 @@
 
 const GodotIME = {
        $GodotIME__deps: ['$GodotRuntime', '$GodotEventListeners'],
+       $GodotIME__postset: 'GodotOS.atexit(function(resolve, reject) { GodotIME.clear(); resolve(); });',
        $GodotIME: {
                ime: null,
                active: false,
@@ -121,6 +122,13 @@ const GodotIME = {
                        GodotConfig.canvas.parentElement.appendChild(ime);
                        GodotIME.ime = ime;
                },
+
+               clear: function () {
+                       if (GodotIME.ime) {
+                               GodotIME.ime.remove();
+                               GodotIME.ime = null;
+                       }
+               },
        },
 };
 mergeInto(LibraryManager.library, GodotIME);
```

I've also tested this on Android (would be great if someone could test on iOS).

Chrome raise the virtual keyboard, but input doesn't work. This seems to be a problem with chrome on android not emitting composition events with some(?) virtual keyboards.

With Firefox on Android on the other end, some composition events are emitted, and input is received thought it seems to produce unreliable results when auto-completing and auto-correcting.

I don't want virtual keyboards to block this PR since that's not officially supported anyway.
I think this PR still needs some work to at least not break the optional experimental vk support we introduced some time ago which uses a similar approach.
I think we might want to disable IME completely when that option is enabled.
I'll see if I can come up with another patch.

**Review by Faless — APPROVED** [review]
Amazing work :rocket:  !
Thank you very much :trophy: !

File: platform/web/display_server_web.cpp [hunk 1]
```diff
@@ -809,6 +818,100 @@ void DisplayServerWeb::_gamepad_callback(int p_index, int p_connected, const Str
...
+	godot_js_set_ime_position(p_pos.x, p_pos.y);
+}
+
+Point2i DisplayServerWeb::DisplayServerWeb::ime_get_selection() const {
+	return ime_selection;
+}
+
+String DisplayServerWeb::DisplayServerWeb::ime_get_text() const {
+	return ime_text;
+}
```
Comment (YuriSizov) [inline platform/web/display_server_web.cpp:913]: Is double `DisplayServerWeb::DisplayServerWeb::` here intentional?

Comment (Faless) [reply platform/web/display_server_web.cpp:913]: Ah, that seems indeed to be a mistake I didn't spot it during my review.

Comment (bruvzg) [reply platform/web/display_server_web.cpp]: Fixed.

**Comment by YuriSizov** [comment]
Thanks!

**Comment by zerosum-0** [comment]
Hi
Can you check this bugs. 
I made one LineEdit and one Text box . 
And When I change the focus while typing. 

The last letter dissapears in mac.
The last letter is move to another control in web (I used chrome)

[KoreanIMEBugReproduction 2.zip](https://github.com/godotengine/godot/files/13982651/KoreanIMEBugReproduction.2.zip)

https://github.com/godotengine/godot/assets/81721778/55ee8b41-1c1c-434f-87b6-e1a1af58e886


https://github.com/godotengine/godot/assets/81721778/0d061df9-ccde-4254-be79-05b356a0a2b5

**Comment by Zireael07** [comment]
@zerosum-0 please make a separate issue report

**Comment by JunShiozawa** [comment]
I am Japanese.
Prease add milestone Godot 3.x
Godot 4.x's web export don't run on iOS and Mac Safari.

**Comment by MASoftware-es** [comment]
Good morning.
I am currently using the official stable version v4.2.1, and this bug still occurs. When I use a "TextEdit" or an "InputLine" in the application, I can introduce accents if I compile natively in desktop application mode, both for Windows, Linux, Mac, but however, when I generate an HTML project, it only works from Windows, since neither from OSX nor from Linux can I get those fields to accept accents.
It seems that the case was closed, but it continues to happen.
Can you reconsider continuing the investigation and look for an alternative?
Thank you so much.

**Comment by akien-mga** [comment]
@MASoftware-es That issue was fixed in 4.3, you should test 4.3-dev5 or later.

**Comment by MASoftware-es** [comment]
Thanks so much!!El 16 abr 2024 10:27, Rémi Verschelde ***@***.***> escribió:
@MASoftware-es That issue was fixed in 4.3, you should test 4.3-dev5 or later.

**Comment by JunShiozawa** [comment]
@akien-mga 
Why do not you add this Godot 3.x?
I need this on Godot 3.x

**Comment by akien-mga** [comment]
> @akien-mga Why do not you add this Godot 3.x? I need this on Godot 3.x

It could be backported to 3.x if a contributor is interested. The 3.x branch is supported on a best-effort basis, and we already have our hands full with working on improvements for 4.3 (like this PR for example), and bug fixes for 4.2. So I can't make any promises because this is a resourcing question, not a technical issue.

**Comment by JunShiozawa** [comment]
@bruvzg

I am Japanese.

Could you please implement [Web] Add IME input support in Godot 3.x ?

Web export of Godot 4.x cannot be used for Safari for iPhone.

This is a political issue for Japanese people.

**Comment by JunShiozawa** [comment]
Chrome for Android Japanese input OK.
Firefox for Andriod Japanese input OK.
Safari for iPhpne Japanese input OK.
Firefox for Linux Japanese input OK.
Firefox for Windows Japanese input OK.
