### PR TITLE
fix persistent favorites after rename

### LINKED ISSUE #58498: Favorites in EditorFileDialog do not automatically remove folders that were renamed or removed
### Godot version

3.4.2.stable

### System information

windows 10, Intel(R) Core(TM) i7-4860HQ CPU @ 2.40GHz   2.39 GHz, 16.0 GB ram

### Issue description

I renamed the '_mats' folder to 'mats'.
The name in the favorites bar did not update ; now there is no obvious way to delete the old favorite folder. 

bug_favorites_3 4

### Steps to reproduce

 - 

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by DanielKriz**
This pull request addresses the #58498 issue. Although the code is very similar, or rather identical, I think it would unnecessary interconnect two sort of separated modules, if was put in some kind of function.

*Bugsquad edit:*
- Fixes #58498

### CODE REVIEW

File: editor/editor_file_dialog.cpp [hunk 1]
```diff
@@ -1294,6 +1294,18 @@ void EditorFileDialog::_update_favorites() {
 	favorite->set_pressed(false);
 
 	Vector<String> favorited = EditorSettings::get_singleton()->get_favorites();
+
+	bool fav_changed = false;
+	for (String &fav_file : favorited) {
+		if (!dir_access->dir_exists(fav_file)) {
+			favorited.erase(fav_file);
```
Comment (timothyqiu) [inline editor/editor_file_dialog.cpp:1301]: Is it safe to use `erase()` inside the loop? Or will it skip the next item in the array in case if `erase()` moves the following items forward?

Comment (DanielKriz) [reply editor/editor_file_dialog.cpp:1301]: Now that you are talking about it, it seems like it could make problems. (if the godot Vector doesn't work differently). I am going to iterate over `size()` of the vector and increase iterator, if `erase()` occured. Good catch, thank you.

Comment (EricEzaM) [reply editor/editor_file_dialog.cpp:1301]: You can just to a reverse for loop. For loop that starts at the array length and decrements the index variable.

**Comment by DanielKriz** [comment]
I updated the code to `erase()` from the vector from the end.

**Comment by aaronfranke** [comment]
@DanielKriz In the future, you should make a new branch before opening a PR. But this PR's Git history looks good now.

**Comment by DanielKriz** [comment]
I did some real chaos here with my poor github skills, I am sorry to anyone that has been affected

File: editor/editor_file_dialog.cpp [hunk 2]
```diff
@@ -1294,6 +1294,18 @@ void EditorFileDialog::_update_favorites() {
 	favorite->set_pressed(false);
 
 	Vector<String> favorited = EditorSettings::get_singleton()->get_favorites();
+
+	bool fav_changed = false;
+	for (int i = favorited.size() - 1; i >= 0; i--) {
+		if (!dir_access->dir_exists(favorited[i])) {
+			favorited.erase(favorited[i]);
```
Comment (timothyqiu) [inline editor/editor_file_dialog.cpp:1301]:
```suggestion
			favorited.remove_at(i);
```

This avoids element searching. Same in `FileSystemDock`.

**Review by timothyqiu — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.
