### PR TITLE
Fix shortcut input for `EditorSceneTabs`

### LINKED ISSUE #83500: Can't switch scene tabs using shortcut anymore
### Godot version

v4.2.beta.custom_build [fd33c7b32]

### System information

linux

### Issue description

The scene tab switching shortcuts, <kbd>Ctrl+Tab</kbd> and <kbd>Ctrl+Shift+Tab</kbd>, don't work anymore.
I couldn't find a setup-specific way that could cause it.

### Steps to reproduce

- Open 2 scenes
- press <kbd>Ctrl+Tab</kbd> 

### Minimal reproduction project

any

### PR DESCRIPTION
**Pull request by AThousandShips**
Seems like an oversight from when the tab was split off into its own component (in #80490)

* Fixes: #83500

### CODE REVIEW

File: editor/gui/editor_scene_tabs.cpp [hunk 1]
```diff
@@ -341,6 +341,8 @@ void EditorSceneTabs::_bind_methods() {
 EditorSceneTabs::EditorSceneTabs() {
 	singleton = this;
 
+	set_process_shortcut_input(true);
```
Comment (AThousandShips) [inline editor/gui/editor_scene_tabs.cpp:344]: Unsure where to place this, i.e. if the order matters, can move if it does matter

**Review by YuriSizov — APPROVED** [review]
Ah, good catch. Surprised it took so long for anyone to notice.

**Comment by AThousandShips** [comment]
Thank you!
