### PR TITLE
Fix ENet max clients highest value.

### LINKED ISSUE #34636: NetworkedMultiplayerENet.create_server() does not work with max_clients=4096
**Godot version:** 
3.1

**OS/device including version:** 
Ubuntu 18.04

**Issue description:**
The docs say that 4096 is the highest acceptable number for max_clients.
(https://docs.godotengine.org/en/3.1/classes/class_networkedmultiplayerenet.html#class-networkedmultiplayerenet-method-create-server)
Actually it is 4095. With 4096, networking just silently stops working, no connections are accepted and no error message is logged.

Also interesting: This number is NOT concurrent connected clients, but total connection attempts. If I start a server with max_clients=4 and then connect and disconnect 4 times with the same client, the server will not accept any more connections.

**Steps to reproduce:**
	host = NetworkedMultiplayerENet.new()
	host.create_server(self.LISTEN_PORT, 4096) 

Then try to connect.

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by Faless**
Was 4096, while actually it's 4095. Fixed now in both docs and `create_server` check.

Fixes #34636

### CODE REVIEW

File: modules/enet/networked_multiplayer_enet.cpp [hunk 1]
```diff
@@ -74,8 +74,8 @@ int NetworkedMultiplayerENet::get_last_packet_channel() const {
 Error NetworkedMultiplayerENet::create_server(int p_port, int p_max_clients, int p_in_bandwidth, int p_out_bandwidth) {
 
 	ERR_FAIL_COND_V(active, ERR_ALREADY_IN_USE);
-	ERR_FAIL_COND_V(p_port < 0 || p_port > 65535, ERR_INVALID_PARAMETER);
-	ERR_FAIL_COND_V(p_max_clients < 0, ERR_INVALID_PARAMETER);
+	ERR_FAIL_COND_V(p_port < 1 || p_port > 65535, ERR_INVALID_PARAMETER);
```
Comment (akien-mga) [inline modules/enet/networked_multiplayer_enet.cpp]: The docs still say "The port needs to be an available, unused port between 0 and 65535", which conflicts with this check.

**Review by akien-mga — APPROVED** [review]

File: modules/enet/networked_multiplayer_enet.cpp (hunk 1 above)
Comment (Faless) [reply modules/enet/networked_multiplayer_enet.cpp]: Right, thanks for spotting it.
Actually, I changed it back to allow port `0`.
That is a valid entry but with special meaning, i.e. asks the OS to assign a random available port.
For now, in godot, you can't really know what port you were bound to (no `getsockname` support for now), so I feel that needs to be added instead of disallowing port 0.

**Comment by akien-mga** [comment]
Thanks!
