### PR TITLE
ImageLoaderSVG: Improve error reporting

### LINKED ISSUE #68822: Loading a large amount of images crashes Godot
### Godot version

4.0 Beta 5

### System information

M1 MacBook Pro Arm 32gb

### Godot currently can't load large volumes of images all at once.  

I have a game on Godot 3.5 and use the plug in dialogic for my dialog.  They are developing a conversation feature that will port my game over to the 4.0 branch.  But after trying it, it crashes my editor as I have roughly 100 images.  

Even when I copy them over without converter, it crashes Godot.  
I found that it can only take between roughly 20-50 images at a time.  

Not ideal to not be able to upload a reasonable amount of images at a time.  

### Steps to reproduce

after starting up game engine, grab 20 - 100 images, and copy and paste into game folder in window res://.

Game Engine Crashes...

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by akien-mga**
Helps with #68822, which will now report:

```
WARNING: ImageLoaderSVG: Canvas dimensions of 1045714×1032197 (with scale 1.00) and exceed the max supported dimensions of 16384×16384. The canvas will be cropped.
     at: create_image_from_string (modules/svg/image_loader_svg.cpp:94)
ERROR: ImageLoaderSVG: Couldn't draw ThorVG pictures on canvas.
   at: create_image_from_string (modules/svg/image_loader_svg.cpp:122)
ERROR: Error loading image: res://testingSVG_fromInkscape_0.svg
   at: load_image (core/io/image_loader.cpp:101)
ERROR: Error importing 'res://testingSVG_fromInkscape_0.svg'.
   at: _reimport_file (editor/editor_file_system.cpp:1909)
ERROR: Condition "!importer.is_valid()" is true. Continuing.
   at: reimport_files (editor/editor_file_system.cpp:2123)
```

It still doesn't mention that the canvas actually doesn't contain drawable elements, but I don't know how to check that with the thorvg API to provide more details. At least it mentions that the drawing step failed.

It also warns about the image getting cropped, which should be an indicator for users that they'll not get the intended result.

There's still a failed reimport loop but that's tracked in #62271, so I think we can consider that this closes #68822.

### CODE REVIEW

File: modules/svg/image_loader_svg.cpp [hunk 1]
```diff
@@ -81,13 +81,23 @@ void ImageLoaderSVG::create_image_from_string(Ref<Image> p_image, String p_strin
...
 
-	uint32_t width = MIN(round(fw * p_scale), 16 * 1024);
-	uint32_t height = MIN(round(fh * p_scale), 16 * 1024);
+	uint32_t width = round(fw * p_scale);
+	uint32_t height = round(fh * p_scale);
+
+	const uint32_t max_dimension = 16384;
+	if (width > max_dimension || height > max_dimension) {
+		WARN_PRINT(vformat(
+				String::utf8("ImageLoaderSVG: Canvas dimensions of %d×%d (with scale %.2f) and exceed the max supported dimensions of %d×%d. The canvas will be cropped."),
```
Comment (bruvzg) [inline modules/svg/image_loader_svg.cpp:95]: Is it cropped or scaled down (probably scaled)?

Comment (akien-mga) [reply modules/svg/image_loader_svg.cpp]: Done.

**Review by fire — APPROVED** [review]
The major structure of the code looks good. I wasn’t able to go into deep review.
