### PR TITLE
Fix Tree focus item LineEdit is offset

### LINKED ISSUE #110521: If the part of the Tree's focus item is out of the visible area, the LineEdit will be offset.
### Tested versions

Reproducible: v4.5, v4.4

### System information

Windows11

### Issue description

When you start to edit the tree's item, if the part of the Tree's focus item is out of the visible area, the LineEdit will be offset.
Reproduce in the editor:
Image
Reproduce in the game:
Image

### Steps to reproduce

Follow gifs.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by BrotherShort**
Fix #110521.
Based on @KoBeWi 's work in #109938.

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -5739,14 +5744,28 @@ void Tree::ensure_cursor_is_visible() {
...
 		} else if (x_offset < h_scroll->get_value()) {
+			delta_h = x_offset - h_scroll->get_value();
 			h_scroll->set_value(x_offset);
 		}
 	}
 
+	// Move focus_rect.
+	if (select_mode == SELECT_ROW) {
+		Rect2 r = selected_item->cells[selected_col].focus_rect;
+		r = Rect2(r.position + Vector2(-delta_h, -delta_v), r.size);
```
Comment (KoBeWi) [inline scene/gui/tree.cpp]: You could just do

```suggestion
		r.position -= Vector2(delta_h, delta_v));
```

**Review by KoBeWi — APPROVED** [review]

File: scene/gui/tree.cpp (hunk 1 above)
Comment (BrotherShort) [reply scene/gui/tree.cpp]: Done.
