### PR TITLE
Reorganize main and sub-window initial position properties.

### LINKED ISSUE #71591: Project setting 'Initial Screen' has too many monitor options
### Godot version

v4.0.beta12.mono.official [3c9bf4bc2]

### System information

Windows 10, Forward+ (Vulkan), NVIDIA GeForce RTX 3070 (526.98)

### Issue description

The `Initial Screen` select dropdown provides 64 options for monitors when it should only provide options for what is available.  In my case, I'm only using two monitors so there should only be two monitors to choose from (excluding the Primary Monitor option of course).  Screenshot below.

image

### Steps to reproduce

The issue appears to occur whether I'm using two monitors or one monitor.

---
1. Open `Project Settings`
2. Go to `Display` > `Window` > `Size`
3. Select the `Initial Screen` dropdown.
4. You will see the `Primary Monitor` option and 64 other monitor options as seen in the screenshot.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/71591

### CODE REVIEW

File: core/config/project_settings.cpp [hunk 1]
```diff
@@ -1276,12 +1276,12 @@ ProjectSettings::ProjectSettings() {
...
-	for (int i = 0; i < 64; i++) {
-		screen_hints += ",Monitor " + itos(i + 1) + ":" + itos(i);
-	}
-	custom_prop_info["display/window/size/initial_screen"] = PropertyInfo(Variant::INT, "display/window/size/initial_screen", PROPERTY_HINT_ENUM, screen_hints);
+	GLOBAL_DEF_BASIC("display/window/size/initial_position_type", 1);
+	GLOBAL_DEF_BASIC("display/window/size/initial_position", Vector2i());
+	GLOBAL_DEF_BASIC("display/window/size/initial_screen", 0);
+	custom_prop_info["display/window/size/initial_position_type"] = PropertyInfo(Variant::INT, "display/window/size/initial_position_type", PROPERTY_HINT_ENUM, "Absolute,Primary Screen Center,Other Screen Center");
+	custom_prop_info["display/window/size/initial_position"] = PropertyInfo(Variant::VECTOR2I, "display/window/size/initial_position");
+	custom_prop_info["display/window/size/initial_screen"] = PropertyInfo(Variant::INT, "display/window/size/initial_screen", PROPERTY_HINT_RANGE, "0,64,1,or_greater");
```
Comment (akien-mga) [inline core/config/project_settings.cpp:1284]: `GLOBAL_DEF*` now supports `PropertyInfo` directly insteaad of just the property name, so you could unify these.

(Same goes for other uses of `custom_prop_info` in this file, but that's outside the scope of this PR.)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
