### PR TITLE
removed hardcoded color and added theme update for animation editor

### LINKED ISSUE #10828: Some visual issues with new theme changes
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
godot master

**Issue description:**

some unwanted effects were introduced along with the new white theme

before
screenshot from 2017-08-31 12-26-46
screenshot from 2017-08-31 12-26-57

after
screenshot from 2017-08-31 12-32-51
screenshot from 2017-08-31 12-35-00

1.  of all most of the elements are bigger now, this is unwanted, it actually even though this does not look that bad, it reduces the number of element in lists (at least should be configurable).

2. buttons are brighter

3. Inputs do not have borders even though my settings are set to have 1px border.

@toger5 this is the problem with including sneaky changes, next time it would be better to include such changes on different PRs

im not sure if there are other changes like that, but please @toger5 try to not include sneaky changes, i spend quite some work making sure that metric are correct and colors are not very odd, and including this changes would make me repeat my changes (which is not fun).

**Steps to reproduce:**

**Link to minimal example project:**

### PR DESCRIPTION
**Pull request by toger5**
tested. fixes #10828

### CODE REVIEW

**Comment by toger5** [comment]
@akien-mga can get merged now

File: editor/animation_editor.cpp [hunk 1]
```diff
@@ -1092,12 +1092,16 @@ void AnimationKeyEditor::_track_editor_draw() {
...
+	Color sepcolor = color;
+	sepcolor.a = 0.2;
+	Color timecolor = color;
+	timecolor.a = 0.2;
+	Color hover_color = color;
+	hover_color.a = 0.05;
+	Color select_color = color;
+	select_color.a = 0.1;
 	Color invalid_path_color = get_color("error_color", "Editor");
-	Color track_select_color = get_color("highlight_color", "Editor");
```
Comment (djrm) [inline editor/animation_editor.cpp]: i dont think this should be changed

Comment (toger5) [reply editor/animation_editor.cpp]: you mean we should continue using the highlight color?
if so we really need to change the highlight color used in the grey theme!
But you could be right... it makes sense since those tracks than are selected... so they should be highlighted or accented ;)

File: editor/animation_editor.cpp [hunk 2]
```diff
@@ -2995,6 +3000,56 @@ void AnimationKeyEditor::_notification(int p_what) {
 			_update_menu();
 
 		} break;
+
+		case EditorSettings::NOTIFICATION_EDITOR_SETTINGS_CHANGED: {
+
+			zoomicon->set_texture(get_icon("Zoom", "EditorIcons"));
```
Comment (djrm) [inline editor/animation_editor.cpp]: is this code, all repeated somewhere else, wouldnt it be better to create a function.

Comment (toger5) [reply editor/animation_editor.cpp]: Yea I was discussion that another day. if we might should introduce functions for the icon and style box changes. since they usually are needed in enter_tree and settings_chagned.

**maybe it is possible to listen to theme_changed**. since that is also a control event and should be called on tree enter and when the settings changes the tree!

Comment (toger5) [reply editor/animation_editor.cpp]: I'm just doing that right now, that I move all the icon updates in theme changed. this just makes sooo much more sense than editor settings changed. editor settings sometimes change the theme and if they do the theme updates that is just soo much better!

I might do that for all the editor classes soon. since that also saves performance for normal settings changes. and makes sure the theme always updates. also than it is not needed to have it in settings changed + enter tree... as mentioned before so we also can get rid of a lot or redundant code...

Comment (djrm) [reply editor/animation_editor.cpp]: @toger5 yeah, that sounds really good, however i would suggest you to wait until most breaking PRs get merged, so you have less conflicts
