### PR TITLE
Fix undo behavior on `EditorSettingsDialog::_update_builtin_action`.

### LINKED ISSUE #100068: Editor Settings Shortcuts: Undoing changes to built-in actions creates empty action
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 980 Ti (NVIDIA; 32.0.15.6603) - 13th Gen Intel(R) Core(TM) i7-13700K (24 Threads)

### Issue description

Two issues happen when undoing/redoing changes to the built-in actions in the Shortcuts list:
 
1. Undo/redo have a 1 second delay
2. Undoing back to the default shortcut results in an empty shortcut rather than the default.

https://github.com/user-attachments/assets/b24c9694-a1d1-4979-9b5e-63cc22127cc2

### Steps to reproduce

- Change one of the built-in editor shortcuts
- Undo with Ctrl-Z

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by allenwp**
Fixes #100068.

### CODE REVIEW

File: editor/editor_settings_dialog.cpp [hunk 1]
```diff
@@ -314,18 +314,22 @@ void EditorSettingsDialog::_event_config_confirmed() {
 
 void EditorSettingsDialog::_update_builtin_action(const String &p_name, const Array &p_events) {
 	Array old_input_array = EditorSettings::get_singleton()->get_builtin_action_overrides(p_name);
+	if (old_input_array.size() == 0) {
```
Comment (KoBeWi) [inline editor/editor_settings_dialog.cpp:317]:
```suggestion
	if (old_input_array.is_empty()) {
```

Comment (allenwp) [reply editor/editor_settings_dialog.cpp:317]: Good catch, thanks!

File: editor/editor_settings_dialog.cpp [hunk 2]
```diff
@@ -314,18 +314,22 @@ void EditorSettingsDialog::_event_config_confirmed() {
 
 void EditorSettingsDialog::_update_builtin_action(const String &p_name, const Array &p_events) {
 	Array old_input_array = EditorSettings::get_singleton()->get_builtin_action_overrides(p_name);
+	if (old_input_array.is_empty()) {
+		List<Ref<InputEvent>> defaults = InputMap::get_singleton()->get_builtins_with_feature_overrides_applied()[current_edited_identifier];
```
Comment (KoBeWi) [inline editor/editor_settings_dialog.cpp:318]: It would be nice to have a cheaper way to find the defaults, instead of building a HashMap and fetching one element.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
