### PR TITLE
Make zoom limits and step adjustable in `GraphEdit`

### LINKED ISSUE #38249: GraphEdit nodes max zoom, min zoom and zoom factor can't be changed
**Godot version:**
Godot 3.2.1

**OS/device including version:**
Ubuntu 18.04.3 LTS

**Issue description:**
The GraphEdit node is limited to 3 zoom-ins or zoom-outs with a fixed zoom factor. After further inspection it seems like this was hardcoded around [here](https://github.com/godotengine/godot/blob/dcebe668162d6927dff49049a194dc25353f72da/scene/gui/graph_edit.cpp#L43). I think setting the min and max values as well as the scaling factor are supposed to be customizable.

**Steps to reproduce:**
- In any GraphEdit node try to zoom for multiple times, it will be limited.
or
- In the editor, try to assign a large or small zoom value to a GraphEdit node, it will be limited

**Minimal reproduction project:**
Create a scene with a GraphEdit node.

### PR DESCRIPTION
**Pull request by YuriSizov**
Closes #38249. 

This also adds an optional label to the toolbar of the GraphEdit to display current zoom level (in percent).

*Note: Earlier version of this PR featured a linear zoom option that was removed*

https://user-images.githubusercontent.com/11782833/122230790-a01a7d80-cec2-11eb-9d06-9ca77258cde0.mp4

New settings are neatly grouped. I've also gone ahead and grouped connection lines related settings.

godot windows tools 64_2021-06-16_16-13-10

### CODE REVIEW

**Comment by LightningAA** [comment]
Not sure the linear zoom property is necessary, I'm not sure anyone's ever asked for this and if someone really does need this isn't it possible for them to implement it themselves?

**Comment by pycbouh** [comment]
> Not sure the linear zoom property is necessary, I'm not sure anyone's ever asked for this and if someone really does need this isn't it possible for them to implement it themselves?

I'm fine with cutting it out of this PR. As for implementing it on the user side, I don't think it would be trivial, no.

File: scene/gui/graph_edit.cpp [hunk 1]
```diff
@@ -984,12 +979,12 @@ void GraphEdit::_gui_input(const Ref<InputEvent> &p_ev) {
 
 		if (b->get_button_index() == BUTTON_WHEEL_UP && b->is_pressed()) {
 			//too difficult to get right
-			//set_zoom(zoom*ZOOM_SCALE);
+			//set_zoom(zoom*zoom_step);
```
Comment (akien-mga) [inline scene/gui/graph_edit.cpp:982]: It would be better to remove this as it's dead code.

File: scene/gui/graph_edit.cpp [hunk 2]
```diff
@@ -1305,11 +1413,24 @@ GraphEdit::GraphEdit() {
 	v_scroll->connect("value_changed", callable_mp(this, &GraphEdit::_scroll_moved));
 
 	zoom = 1;
+	linear_zoom = false;
+	zoom_step = 1.2;
```
Comment (akien-mga) [inline scene/gui/graph_edit.cpp:1417]: These can go in the header now (and `zoom`).

File: scene/gui/graph_edit.cpp (hunk 1 above)
Comment (pycbouh) [reply scene/gui/graph_edit.cpp]: Obsolete, as this code is no longer dead in master.

File: scene/gui/graph_edit.cpp (hunk 2 above)
Comment (pycbouh) [reply scene/gui/graph_edit.cpp]: Indeed, moved. Though I am now curious if we can move default min and max calculations to the header as well:

```cpp
	zoom_min = (1 / Math::pow(zoom_step, 8));
	zoom_max = (1 * Math::pow(zoom_step, 4));
```

I've left it in the constructor for the time being.

**Comment by pycbouh** [comment]
PR amended. The linear zoom option was removed as not that desired. Code was rebased against the most recent master, some code style changes were applied as well as some other adjustments to code to better fit the overall state of our codebase (now that I know it better).

**Review by AaronRecord — APPROVED** [review]
Haven't tested it, but the code looks good to me.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
