### PR TITLE
Export: Modify Windows template without rcedit

### LINKED ISSUE #1097: Provide an easier way to change the executable icon for projects exported to Windows
**Describe the project you are working on:**
Currently nothing, just tests.

**Describe the problem or limitation you are having in your project:**
It is not possible to change the properties of the executable (for example the description of the file, the icon, etc.) at the time of export

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
By including rcedit in godot it will be possible to export the games without having to download it separately

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I don't know

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It is not possible

**Is there a reason why this should be core and not an add-on in the asset library?:**
because this way you can change the properties of the executable without having to download it separately to get everything ready. Then I believe that if the rcedit code were included in godot there would no longer be any need for wine on macOS / linux.

### LINKED ISSUE #73497: Compressed godot.ico breaks Godot Icon tool
### Godot version

4.0 rc 2

### System information

All operating systems

### Issue description

@bruvzg This commit brakes compability with **Godot Icon** tool.
https://github.com/godotengine/godot/commit/42c2c02acfac6af5d382310e36a473bf36d18944

As agreed before in this commit:
https://github.com/godotengine/godot/commit/d469cfb2abb4074fe38097e43e015ebd69929f28

having a little bigger uncompressed Windows icon is ok when it enables users to replace it without **rcedit** usage.
**Godot Icon** tool is especially helpful on Linux systems.

Also **Godot Icon** is mentioned in official docs (at least for 3.x) so it would be nice to leave the uncompressed icon.

### Steps to reproduce

No steps needed to reproduce.

### Minimal reproduction project

As archive is required I'm attaching empty one.
[empty.zip](https://github.com/godotengine/godot/files/10766564/empty.zip)

### PR DESCRIPTION
**Pull request by pkowal1982**
Using rcedit is little problematic so I've created a POC which shows how it can be dropped.
PR contains only crucial code, if it's decided to go this way I'll fix loose ends.
For now code drops old resources section and replaces it with brand new created from scratch.
Questions which I can think of:
1. How to test this solution properly?
2. Do we need to copy anything from original resources?
3. Is there a minimum set of information which user should provide?
4. All the editor code regarding rcedit should be probably removed in another dedicated PR?

- *Production edit: This closes #73497
and closes godotengine/godot-proposals#1097.*

### CODE REVIEW

**Comment by Calinou** [comment]
> All the editor code regarding rcedit should be probably removed in another dedicated PR?

I think the rcedit code should be removed in the same PR, as we don't want to support both approaches at the same time.

**Comment by akien-mga** [comment]
> > All the editor code regarding rcedit should be probably removed in another dedicated PR?
> 
> I think the rcedit code should be removed in the same PR, as we don't want to support both approaches at the same time. While we try to preserve compatibility across 4.x, this mainly applies to the API, not the export system.
> 
> (Also, it should be possible to create compatibility handlers to automatically update old entries' names in the Windows export presets to the new names.)

I think it's fine to first assess whether this approach is good, before doing the extra work to remove the old. If it's not clear whether this PR wouldn't be merged (it hasn't been reviewed yet), there's no point doing removing the code it's meant to replace.

**Comment by sammypanda** [comment]
rcedit go away for integrated solution soon? :pleading_face::pray:

**Comment by fire** [comment]
I am interested in getting this to work since I export from Linux for Windows.

**Comment by Maran23** [comment]
I also think this is a good idea since it has multiple advantages:
- No `rcedit` needed on Windows
- Project can be exported on Linux or MacOS without using Wine (for this particular feature)

Note: This PR needs a rebase. I would be happy to test this as I always used `rcedit` in the past.

**Comment by pkowal1982** [comment]
Ok, rebased it so you can test it.

Also fixed a bug introduced [here](https://github.com/godotengine/godot/commit/9a33c97c2a1e46f79426fa091c271d273a458bb8) which prevented exporting console template.
Looks like it never worked, probably not too popular feature.

**Comment by YuriSizov** [comment]
> Also fixed a bug introduced [here](https://github.com/godotengine/godot/commit/9a33c97c2a1e46f79426fa091c271d273a458bb8) which prevented exporting console template.
> Looks like it never worked, probably not too popular feature.

This is incorrect. The official export templates (and the editor executable) are named with the underscore:

image

The name with a period is what is produced by our buildsystem by default, but the actual distribution is renamed. So this code was correct and should not be modified.

**Comment by pkowal1982** [comment]
Ok, the ones built on github contained in artifact windows-template.zip are named:
**godot.windows.template_release.x86_64.console.exe**

Would be nice to change the github workflow probably to be consistent.

**Comment by YuriSizov** [comment]
@pkowal1982 That's not related to the CI. As I mentioned, that's how the name is generated by the buildsystem. It uses a number of suffixes to differentiate between build options, but those get removed for the official distribution. It may be worth discussing the naming scheme of the official distribution, but in the meantime we should not break the system in favor of CI artifacts which are not supposed to be used in development anyway.

**Comment by pkowal1982** [comment]
Ok, reverted **_console** -> **.console** change. Though I think it would be nice
to change the CI workflow in another PR to produce _console named templates.
Now editor built from master does not work smoothly with templates built from the same branch.

**Review by Maran23 — COMMENTED** [review]
Right now, I can not really test this as I always get `Wrong number of icon images.`.
With the old implementation, I just got a bunch of warnings (that I do not provide icons for all formats) but the modify process worked (and the icon worked in the explorer, not when I opened the properties though).

**Comment by Maran23** [comment]
Tested now with an icon containing all 6 required image formats.
Looks good. I can confirm that the icon and all the metadata is set correctly. Nice!
Results below (Note: My Windows is set to German)

| Godot 4.2.1| Godot 4.3.dev (this PR) |
| - | - |
| image | image |

I would still recommend that if the icon does not contain all 6 image formats, we just print a warning as before, and continue with the modification.

File: platform/windows/export/template_modifier.cpp [hunk 1]
```diff
@@ -0,0 +1,584 @@
...
+	return bytes;
+}
+
+void TemplateModifier::GroupIcon::load(Ref<FileAccess> p_icon_file) {
+	if (p_icon_file->get_32() != 0x10000) { // Wrong reserved bytes
+		print_error("Wrong icon file type.");
+		return;
+	}
+	if (p_icon_file->get_16() != IMAGE_COUNT) {
+		print_error("Wrong number of icon images.");
```
Comment (Maran23) [inline platform/windows/export/template_modifier.cpp:246]: Is it possible like with rcedit to also do that operation with just one icon image? Would be nice for backward compatibility.

**Comment by fire** [comment]
@KoBeWi What are you thoughts about modifying the template without rcedit?

**Comment by KoBeWi** [comment]
This reimplements what rcedit does and makes it built-in, no? If it works the same as before then why not I guess.

**Comment by Maran23** [comment]
And it works on other platforms as well. Currently you need to use Wine on Linux to run rcedit to modify the .exe. Which is annoying for cross platform creation of the games.

**Review by fire — COMMENTED** [review]
* design proposal review: I think it's a great idea
* technical review: unreviewed
* style review: @AThousandShips Can you take a look?
* test plan: untested

File: platform/windows/export/template_modifier.h [hunk 2]
```diff
@@ -0,0 +1,242 @@
...
+	};
+
+	struct Structure : ByteStream {
+		uint16_t length = 0;
+		uint16_t value_length = 0;
+		uint16_t type = 0;
+		String key;
+
+		Vector<uint8_t> save() const;
+		Vector<uint8_t> &add_length(Vector<uint8_t> &bytes) const;
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.h:118]:
```suggestion
		Vector<uint8_t> &add_length(Vector<uint8_t> &r_bytes) const;
```

File: platform/windows/export/template_modifier.h [hunk 3]
```diff
@@ -0,0 +1,242 @@
...
+	};
+
+	struct StringStructure : Structure {
+		String value;
+
+		Vector<uint8_t> save() const;
+		StringStructure();
+		StringStructure(String p_key, String p_value);
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.h:126]:
```suggestion
		StringStructure(const String &p_key, const String &p_value);
```

File: platform/windows/export/template_modifier.cpp [hunk 4]
```diff
@@ -0,0 +1,584 @@
...
+	return p_value + (p_value % p_size ? p_size - (p_value % p_size) : 0);
+}
+
+Vector<uint8_t> TemplateModifier::_create_resources(uint32_t p_virtual_address, const GroupIcon &p_group_icon, const VersionInfo &p_version_info) const {
+	Vector<uint8_t> resources;
+	resources.resize(sizeof(RESOURCE_DIRECTORY_TABLES));
+	memcpy(resources.ptrw(), RESOURCE_DIRECTORY_TABLES, sizeof(RESOURCE_DIRECTORY_TABLES));
+
+	Vector<Vector<uint8_t>> data_entries;
+	for (Vector<uint8_t> image : p_group_icon.images) {
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp:350]:
```suggestion
	for (const Vector<uint8_t> &image : p_group_icon.images) {
```

File: platform/windows/export/template_modifier.cpp [hunk 5]
```diff
@@ -0,0 +1,584 @@
...
+		resources.append_array(data_entry);
+		while (resources.size() % 4) {
+			resources.append(0);
+		}
+	}
+
+	return resources;
+}
+
+TemplateModifier::VersionInfo TemplateModifier::_create_version_info(const HashMap<String, String> &strings) const {
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp:379]:
```suggestion
TemplateModifier::VersionInfo TemplateModifier::_create_version_info(const HashMap<String, String> &p_strings) const {
```

File: platform/windows/export/template_modifier.cpp [hunk 6]
```diff
@@ -0,0 +1,584 @@
...
+	StringTable string_table;
+	for (KeyValue<String, String> E : strings) {
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp:381]:
```suggestion
	for (const KeyValue<String, String> &E : p_strings) {
```

File: platform/windows/export/template_modifier.cpp [hunk 7]
```diff
@@ -0,0 +1,584 @@
...
+		group_icon.fill_with_godot_blue();
+		return group_icon;
+	}
+
+	group_icon.load(icon_file);
+
+	return group_icon;
+}
+
+Error TemplateModifier::_truncate(const String &path, uint32_t size) const {
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp:428]:
```suggestion
Error TemplateModifier::_truncate(const String &p_path, uint32_t p_size) const {
```

File: platform/windows/export/template_modifier.cpp [hunk 8]
```diff
@@ -0,0 +1,584 @@
...
+		strings["LegalCopyright"] = copyright;
+	}
+	if (!trademarks.is_empty()) {
+		strings["LegalTrademarks"] = trademarks;
+	}
+
+	return strings;
+}
+
+Error TemplateModifier::_modify_template(const Ref<EditorExportPreset> &p_preset, const String &template_path, bool p_console_icon) const {
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp:484]:
```suggestion
Error TemplateModifier::_modify_template(const Ref<EditorExportPreset> &p_preset, const String &p_template_path, bool p_console_icon) const {
```

File: platform/windows/export/template_modifier.cpp [hunk 9]
```diff
@@ -0,0 +1,584 @@
...
+
+	if (template_file->get_position() < template_size) {
+		template_file->close();
+		_truncate(template_path, relocations_section_entry.pointer_to_raw_data + relocations_section_entry.size_of_raw_data);
+	}
+
+	return OK;
+}
+
+Vector<TemplateModifier::SectionEntry> TemplateModifier::_get_section_entries(const String &executable_path) const {
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp:553]:
```suggestion
Vector<TemplateModifier::SectionEntry> TemplateModifier::_get_section_entries(const String &p_executable_path) const {
```

File: platform/windows/export/template_modifier.cpp [hunk 10]
```diff
@@ -0,0 +1,584 @@
...
+	for (int i = 0; i < num_sections; ++i) {
+		SectionEntry section_entry;
+		section_entry.load(executable);
+		section_entries.append(section_entry);
+	}
+
+	return section_entries;
+}
+
+Error TemplateModifier::modify(const Ref<EditorExportPreset> &p_preset, const String &template_path, bool p_console_icon) {
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp:581]:
```suggestion
Error TemplateModifier::modify(const Ref<EditorExportPreset> &p_preset, const String &p_template_path, bool p_console_icon) {
```

File: platform/windows/export/template_modifier.cpp [hunk 11]
```diff
@@ -0,0 +1,584 @@
...
+	image_size = p_file->get_32(); // Image data size in bytes.
+	image_offset = p_file->get_32(); // Image data offset.
+}
+
+Vector<uint8_t> TemplateModifier::GroupIcon::save() const {
+	Vector<uint8_t> bytes;
+	ByteStream::save(reserved, bytes);
+	ByteStream::save(type, bytes);
+	ByteStream::save(image_count, bytes);
+	for (IconEntry icon_entry : icon_entries) {
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp:234]:
```suggestion
	for (const IconEntry &icon_entry : icon_entries) {
```

File: platform/windows/export/template_modifier.cpp [hunk 12]
```diff
@@ -0,0 +1,584 @@
...
+		bytes.append_array(icon_entry.save());
+	}
+	return bytes;
+}
+
+void TemplateModifier::GroupIcon::load(Ref<FileAccess> p_icon_file) {
+	if (p_icon_file->get_32() != 0x10000) { // Wrong reserved bytes
+		print_error("Wrong icon file type.");
+		return;
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp:243]:
```suggestion
		ERR_FAIL_MSG("Wrong icon file type.");
```

File: platform/windows/export/template_modifier.cpp [hunk 13]
```diff
@@ -0,0 +1,584 @@
...
+	}
+	if (p_icon_file->get_16() != IMAGE_COUNT) {
+		print_error("Wrong number of icon images.");
+		return;
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp:247]:
```suggestion
		ERR_FAIL_MSG("Wrong number of icon images.");
```

File: platform/windows/export/template_modifier.cpp [hunk 14]
```diff
@@ -0,0 +1,584 @@
...
+	group_icon.load(icon_file);
+
+	return group_icon;
+}
+
+Error TemplateModifier::_truncate(const String &path, uint32_t size) const {
+	Error error;
+
+	Ref<FileAccess> file = FileAccess::open(path, FileAccess::READ, &error);
+	ERR_FAIL_COND_V(error, ERR_CANT_OPEN);
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp:432]:
```suggestion
	ERR_FAIL_COND_V(error != OK, ERR_CANT_OPEN);
```
Be consistent about error check here (you use `!= OK` below)

File: platform/windows/export/template_modifier.cpp [hunk 15]
```diff
@@ -0,0 +1,584 @@
...
+
+	String truncated_path = path + ".truncated";
+	Ref<FileAccess> truncated = FileAccess::open(truncated_path, FileAccess::WRITE, &error);
+	ERR_FAIL_COND_V(error, ERR_CANT_CREATE);
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp:436]:
```suggestion
	ERR_FAIL_COND_V(error != OK, ERR_CANT_CREATE);
```

File: platform/windows/export/template_modifier.cpp [hunk 16]
```diff
@@ -0,0 +1,584 @@
...
+TemplateModifier::StringStructure::StringStructure(String p_key, String p_value) {
+	type = 1;
+	value_length = p_value.length() + 1;
+	key = p_key;
+	value = p_value;
+}
+
+Vector<uint8_t> TemplateModifier::StringTable::save() const {
+	Vector<uint8_t> bytes = Structure::save();
+	for (StringStructure string : strings) {
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp:136]:
```suggestion
	for (const StringStructure &string : strings) {
```

**Comment by KoBeWi** [comment]
Tested on Windows. Using svg icon prints "Wrong icon file type.", using ico generated with GIMP iconify extension, which I'm always using, results in "Wrong number of icon images.". The executables end up without any icon. Both cases worked perfectly before the change.

**Comment by ztc0611** [comment]
@pkowal1982 are you still working on this? I'm also interested in this functionality. Not sure if there's anything I can do to help but I'd like to try. 🙂

**Comment by pkowal1982** [comment]
@ztc0611 Yeah, now as 4.4 is released I'll give it some love.

**Comment by fire** [comment]
What tasks are remaining on this?

**Comment by pkowal1982** [comment]
I would say it's complete. If it passes code review it needs only thorough testing.

File: platform/windows/export/template_modifier.h [hunk 17]
```diff
@@ -0,0 +1,224 @@
...
+/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
+/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
+/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
+/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
+/**************************************************************************/
+
+#pragma once
+
+#include "core/io/file_access.h"
+#include "editor/export/editor_export_platform_pc.h"
```
Comment (KoBeWi) [inline platform/windows/export/template_modifier.h:34]: These can be moved to cpp file, with necessary classes forward-declared.
Not sure about simple types though (Vector, String), you could maybe include `variant.h` for that.

File: platform/windows/export/template_modifier.h [hunk 18]
```diff
@@ -0,0 +1,224 @@
...
+		static const uint32_t SIZE = 16;
+
+		uint8_t width;
+		uint8_t height;
+		uint8_t colors = 0;
+		uint8_t reserved = 0;
+		uint16_t planes = 0;
+		uint16_t bits_per_pixel = 32;
+		uint32_t image_size;
+		uint32_t image_offset;
```
Comment (KoBeWi) [inline platform/windows/export/template_modifier.h:164]: You need to initialize all elements (ints).
Same in other structs.

**Review by KoBeWi — APPROVED** [review]
The icons now get modified correctly. I also tested metadata and they get properly written too.

File: platform/windows/export/template_modifier.cpp [hunk 19]
```diff
@@ -0,0 +1,674 @@
...
+	uint32_t pe_header_offset = _get_pe_header_offset(p_template_path);
+
+	Error error;
+	Ref<FileAccess> template_file = FileAccess::open(p_template_path, FileAccess::READ_WRITE, &error);
+	ERR_FAIL_COND_V(error != OK, ERR_CANT_OPEN);
+
+	Vector<uint8_t> relocations;
+	relocations.resize(relocations_section_entry.size_of_raw_data);
+	template_file->seek(relocations_section_entry.pointer_to_raw_data);
+	template_file->store_buffer(relocations);
```
Comment (bruvzg) [inline platform/windows/export/template_modifier.cpp:609]: What's this supposed to do? I assume it's intended to read the existing `.reloc` section to write it back later, but it's using `pointer_to_raw_data` after it was modified, and writing garbage (since non-zeroed resize is used) to the file instead of reading.

**Review by bruvzg — CHANGES_REQUESTED** [review]
This is not working with x86-32 and arm64 release templates with embedded PCK enabled, rcedit do.

**Comment by pkowal1982** [comment]
Ok, fixed this .reloc copying. I can't test the arm64 build but on my Windows 7 the arm64 embedded export does not show icon. Doesn't matter if it's modified or not.
Tried to export arm64 project with 4.4.1 and it behaves the same, embedded versions do not show proper icon on my pc.

**Comment by bruvzg** [comment]
With the latest changes it seems to be completely broken and not working with any architecture exports, all fail with `Magic number has wrong value` errors.

**Comment by pkowal1982** [comment]
@bruzvg Somehow calling FileAccess::open(p_template_path, FileAccess::READ_WRITE) twice on Windows was returning an error. For Linux it was working.
Resolved the issue and I think it's ready for another try.

File: platform/windows/export/template_modifier.h [hunk 20]
```diff
@@ -0,0 +1,226 @@
...
+
+		uint32_t rva;
+		uint32_t size;
+
+		Vector<uint8_t> save() const;
+	};
+
+	uint32_t _snap(uint32_t p_value, uint32_t p_size) const;
+	uint32_t _get_pe_header_offset(Ref<FileAccess> executable) const;
+	Vector<SectionEntry> _get_section_entries(Ref<FileAccess> executable) const;
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.h]:
```suggestion
	uint32_t _get_pe_header_offset(Ref<FileAccess> p_executable) const;
	Vector<SectionEntry> _get_section_entries(Ref<FileAccess> p_executable) const;
```

File: platform/windows/export/template_modifier.cpp [hunk 21]
```diff
@@ -0,0 +1,671 @@
...
+	return p_value + (p_value % p_size ? p_size - (p_value % p_size) : 0);
+}
+
+Vector<uint8_t> TemplateModifier::_create_resources(uint32_t p_virtual_address, const GroupIcon &p_group_icon, const VersionInfo &p_version_info) const {
+	// 0x04, 0x00 as string length ICON in UTF16 and padding to 32 bits
+	const uint8_t ICON_DIRECTORY_STRING[] = { 0x04, 0x00, 0x49, 0x00, 0x43, 0x00, 0x4f, 0x00, 0x4e, 0x00, 0x00, 0x00 };
+	const uint16_t RT_ENTRY_COUNT = 3;
+	const uint32_t icon_count = p_group_icon.images.size();
+
+	ResourceDirectoryTable root_directory_table = ResourceDirectoryTable();
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp]:
```suggestion
	ResourceDirectoryTable root_directory_table;
```
Unnecessary default

File: platform/windows/export/template_modifier.cpp [hunk 22]
```diff
@@ -0,0 +1,671 @@
...
+	root_directory_table.id_entry_count = RT_ENTRY_COUNT;
+
+	Vector<uint8_t> resources = root_directory_table.save();
+
+	ResourceDirectoryEntry rt_icon_entry = ResourceDirectoryEntry();
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp]:
```suggestion
	ResourceDirectoryEntry rt_icon_entry;
```

File: platform/windows/export/template_modifier.cpp [hunk 23]
```diff
@@ -0,0 +1,671 @@
...
+	rt_icon_entry.id = ResourceDirectoryEntry::ICON;
+	rt_icon_entry.data_offset = ResourceDirectoryTable::SIZE + RT_ENTRY_COUNT * ResourceDirectoryEntry::SIZE;
+	rt_icon_entry.subdirectory = true;
+	resources.append_array(rt_icon_entry.save());
+
+	ResourceDirectoryEntry rt_group_icon_entry = ResourceDirectoryEntry();
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp]:
```suggestion
	ResourceDirectoryEntry rt_group_icon_entry;
```

File: platform/windows/export/template_modifier.cpp [hunk 24]
```diff
@@ -0,0 +1,671 @@
...
+	rt_group_icon_entry.id = ResourceDirectoryEntry::GROUP_ICON;
+	rt_group_icon_entry.data_offset = (2 + icon_count) * ResourceDirectoryTable::SIZE + (RT_ENTRY_COUNT + 2 * icon_count) * ResourceDirectoryEntry::SIZE;
+	rt_group_icon_entry.subdirectory = true;
+	resources.append_array(rt_group_icon_entry.save());
+
+	ResourceDirectoryEntry rt_version_entry = ResourceDirectoryEntry();
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp]:
```suggestion
	ResourceDirectoryEntry rt_version_entry;
```

File: platform/windows/export/template_modifier.cpp [hunk 25]
```diff
@@ -0,0 +1,671 @@
...
+	rt_version_entry.id = ResourceDirectoryEntry::VERSION;
+	rt_version_entry.data_offset = (4 + icon_count) * ResourceDirectoryTable::SIZE + (RT_ENTRY_COUNT + 2 * icon_count + 2) * ResourceDirectoryEntry::SIZE;
+	rt_version_entry.subdirectory = true;
+	resources.append_array(rt_version_entry.save());
+
+	ResourceDirectoryTable icon_table = ResourceDirectoryTable();
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp]:
```suggestion
	ResourceDirectoryTable icon_table;
```

File: platform/windows/export/template_modifier.cpp [hunk 26]
```diff
@@ -0,0 +1,671 @@
...
+	icon_table.id_entry_count = icon_count;
+	resources.append_array(icon_table.save());
+
+	for (uint32_t i = 0; i < icon_count; i++) {
+		ResourceDirectoryEntry icon_entry = ResourceDirectoryEntry();
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp]:
```suggestion
		ResourceDirectoryEntry icon_entry;
```

File: platform/windows/export/template_modifier.cpp [hunk 27]
```diff
@@ -0,0 +1,671 @@
...
+		icon_entry.id = i + 1;
+		icon_entry.data_offset = (2 + i) * ResourceDirectoryTable::SIZE + (RT_ENTRY_COUNT + icon_count + i) * ResourceDirectoryEntry::SIZE;
+		icon_entry.subdirectory = true;
+		resources.append_array(icon_entry.save());
+	}
+
+	for (uint32_t i = 0; i < icon_count; i++) {
+		ResourceDirectoryTable language_icon_table = ResourceDirectoryTable();
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp]:
```suggestion
		ResourceDirectoryTable language_icon_table;
```

File: platform/windows/export/template_modifier.cpp [hunk 28]
```diff
@@ -0,0 +1,671 @@
...
+		language_icon_table.id_entry_count = 1;
+		resources.append_array(language_icon_table.save());
+
+		ResourceDirectoryEntry language_icon_entry = ResourceDirectoryEntry();
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp]:
```suggestion
		ResourceDirectoryEntry language_icon_entry;
```

File: platform/windows/export/template_modifier.cpp [hunk 29]
```diff
@@ -0,0 +1,671 @@
...
+		language_icon_entry.id = ResourceDirectoryEntry::ENGLISH;
+		language_icon_entry.data_offset = (6 + icon_count) * ResourceDirectoryTable::SIZE + (RT_ENTRY_COUNT + icon_count * 2 + 4) * ResourceDirectoryEntry::SIZE + sizeof(ICON_DIRECTORY_STRING) + i * ResourceDataEntry::SIZE;
+		resources.append_array(language_icon_entry.save());
+	}
+
+	ResourceDirectoryTable group_icon_name_table = ResourceDirectoryTable();
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp]:
```suggestion
	ResourceDirectoryTable group_icon_name_table;
```

File: platform/windows/export/template_modifier.cpp [hunk 30]
```diff
@@ -0,0 +1,671 @@
...
+	group_icon_name_table.name_entry_count = 1;
+	resources.append_array(group_icon_name_table.save());
+
+	ResourceDirectoryEntry group_icon_name_entry = ResourceDirectoryEntry();
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp]:
```suggestion
	ResourceDirectoryEntry group_icon_name_entry;
```

File: platform/windows/export/template_modifier.cpp [hunk 31]
```diff
@@ -0,0 +1,671 @@
...
+	group_icon_name_entry.id = (6 + icon_count) * ResourceDirectoryTable::SIZE + (RT_ENTRY_COUNT + icon_count * 2 + 4) * ResourceDirectoryEntry::SIZE;
+	group_icon_name_entry.data_offset = (3 + icon_count) * ResourceDirectoryTable::SIZE + (RT_ENTRY_COUNT + 2 * icon_count + 1) * ResourceDirectoryEntry::SIZE;
+	group_icon_name_entry.name = true;
+	group_icon_name_entry.subdirectory = true;
+	resources.append_array(group_icon_name_entry.save());
+
+	ResourceDirectoryTable group_icon_language_table = ResourceDirectoryTable();
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp]:
```suggestion
	ResourceDirectoryTable group_icon_language_table;
```

File: platform/windows/export/template_modifier.cpp [hunk 32]
```diff
@@ -0,0 +1,671 @@
...
+	group_icon_language_table.id_entry_count = 1;
+	resources.append_array(group_icon_language_table.save());
+
+	ResourceDirectoryEntry group_icon_language_entry = ResourceDirectoryEntry();
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp]:
```suggestion
	ResourceDirectoryEntry group_icon_language_entry;
```

File: platform/windows/export/template_modifier.cpp [hunk 33]
```diff
@@ -0,0 +1,671 @@
...
+	group_icon_language_entry.id = ResourceDirectoryEntry::ENGLISH;
+	group_icon_language_entry.data_offset = (6 + icon_count) * ResourceDirectoryTable::SIZE + (RT_ENTRY_COUNT + 2 * icon_count + 4) * ResourceDirectoryEntry::SIZE + sizeof(ICON_DIRECTORY_STRING) + icon_count * ResourceDataEntry::SIZE;
+	resources.append_array(group_icon_language_entry.save());
+
+	ResourceDirectoryTable version_table = ResourceDirectoryTable();
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp]:
```suggestion
	ResourceDirectoryTable version_table;
```

File: platform/windows/export/template_modifier.cpp [hunk 34]
```diff
@@ -0,0 +1,671 @@
...
+	version_table.id_entry_count = 1;
+	resources.append_array(version_table.save());
+
+	ResourceDirectoryEntry version_entry = ResourceDirectoryEntry();
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp]:
```suggestion
	ResourceDirectoryEntry version_entry;
```

File: platform/windows/export/template_modifier.cpp [hunk 35]
```diff
@@ -0,0 +1,671 @@
...
+	version_entry.id = 1;
+	version_entry.data_offset = (5 + icon_count) * ResourceDirectoryTable::SIZE + (RT_ENTRY_COUNT + 2 * icon_count + 3) * ResourceDirectoryEntry::SIZE;
+	version_entry.subdirectory = true;
+	resources.append_array(version_entry.save());
+
+	ResourceDirectoryTable version_language_table = ResourceDirectoryTable();
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp]:
```suggestion
	ResourceDirectoryTable version_language_table;
```

File: platform/windows/export/template_modifier.cpp [hunk 36]
```diff
@@ -0,0 +1,671 @@
...
+	version_language_table.id_entry_count = 1;
+	resources.append_array(version_language_table.save());
+
+	ResourceDirectoryEntry version_language_entry = ResourceDirectoryEntry();
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp]:
```suggestion
	ResourceDirectoryEntry version_language_entry;
```

File: platform/windows/export/template_modifier.cpp [hunk 37]
```diff
@@ -0,0 +1,671 @@
...
+
+	VersionInfo version_info;
+	version_info.value = fixed_file_info;
+	version_info.string_file_info = string_file_info;
+
+	return version_info;
+}
+
+TemplateModifier::GroupIcon TemplateModifier::_create_group_icon(const String &p_icon_path) const {
+	GroupIcon group_icon = GroupIcon();
```
Comment (AThousandShips) [inline platform/windows/export/template_modifier.cpp]:
```suggestion
	GroupIcon group_icon;
```

**Review by bruvzg — APPROVED** [review]
Now it seems to be working with all architectures, icons and metadata are set correctly.

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Tested on Linux and it seems to work great, both for setting the icon and other metadata. Checked the resulting binary with `exiftool` for metadata (version, product name, etc.) and confirmed that the icon is correct in Dolphin.

I think we can remove the rcedit code too. Is there any way it would still be used currently?

**Comment by bruvzg** [comment]
> I think we can remove the rcedit code too. Is there any way it would still be used currently?

Is there any left, it seems to be removed.

**Comment by bruvzg** [comment]
> I think we can remove the rcedit code too. Is there any way it would still be used currently?

Found few lines related to the editor setting which can be removed, the rest is already gone.

https://github.com/godotengine/godot/blob/1b37dacc1842779fb0d03a5b09026f59c13744fc/platform/windows/export/export_plugin.cpp#L826-L829

https://github.com/godotengine/godot/blob/1b37dacc1842779fb0d03a5b09026f59c13744fc/platform/windows/export/export.cpp#L44-L45

**Comment by akien-mga** [comment]
Yeah it's just a few, I found those:
```
platform/windows/export/export_plugin.cpp
524:    String tmp_icon_path = EditorPaths::get_singleton()->get_temp_dir().path_join("_rcedit.ico");
735:    String rcedit_path = EDITOR_GET("export/windows/rcedit");
736:    if (p_preset->get("application/modify_resources") && rcedit_path.is_empty()) {
737:            err += TTR("The rcedit tool must be configured in the Editor Settings (Export > Windows > rcedit) to change the icon or app information data.") + "\n";

platform/windows/export/export.cpp
44:     EDITOR_DEF_BASIC("export/windows/rcedit", "");
45:     EditorSettings::get_singleton()->add_property_hint(PropertyInfo(Variant::STRING, "export/windows/rcedit", PROPERTY_HINT_GLOBAL_FILE, "*.exe"));
52:     // On non-Windows we need WINE to run rcedit

editor/editor_property_name_processor.cpp
261:    capitalize_string_remaps["rcedit"] = "rcedit";
```
(The `_rcedit.ico` one is actually used by the new system, but maybe we can rename it to not refer to rcedit.)

And I guess we can remove the `wine` editor setting too, unless we use it for anything else:
```
$ rg '"export/windows/wine"'
platform/windows/export/export.cpp
53:     EDITOR_DEF_BASIC("export/windows/wine", "");
54:     EditorSettings::get_singleton()->add_property_hint(PropertyInfo(Variant::STRING, "export/windows/wine", PROPERTY_HINT_GLOBAL_FILE));
```

**Comment by bruvzg** [comment]
Yes, `wine` is not used by anything else, so can be removed, it's only a setting and a `capitalize_string_remaps`.

https://github.com/godotengine/godot/blob/1b37dacc1842779fb0d03a5b09026f59c13744fc/platform/windows/export/export.cpp#L53-L54

**Comment by pkowal1982** [comment]
I've removed the aforementioned rcedit related code in additional commit so it's easier for track.
When ready and approved it'll be squashed.

File: editor/editor_property_name_processor.cpp [hunk 38]
```diff
@@ -258,7 +258,6 @@ EditorPropertyNameProcessor::EditorPropertyNameProcessor() {
 	capitalize_string_remaps["ppc64"] = "ppc64";
 	capitalize_string_remaps["pvrtc"] = "PVRTC";
 	capitalize_string_remaps["pvs"] = "PVS";
-	capitalize_string_remaps["rcedit"] = "rcedit";
```
Comment (akien-mga) [inline editor/editor_property_name_processor.cpp:261]: There's also `wine` here which can be removed.

**Review by akien-mga — APPROVED** [review]
Looks good to me. You can squash the commits and it's ready to merge.

**Comment by akien-mga** [comment]
Thanks! Amazing work :tada:

**Comment by glkdrlgkrlzflnjkgh** [comment]
Now i need to get my rcedit install to a therapist- it doesnt have a purpose and is now depressed.
Which is mildy unfortunate.
(note: this is a joke.)
