### PR TITLE
Fix passing values to the instance uniforms in the shader

### LINKED ISSUE #63566: GDSHADER: Instanced uniform variable with shader hint color_source returns no value.
### Godot version

v4.0.dev.custom_build

### System information

Windows 10, Vulkan, GTX 780Ti

### Issue description

Instanced vector 3 with color_source hint returns no value while just a normal vector 3 with no color_source hint does. 
Instanced color_source should return the value picked from mesh instance.

### Steps to reproduce

Create a new shader with a instance uniform of vector 3 with color_source hint, add that variable to ALBEDO in fragment shader, apply material to mesh surface 0, adjust color on mesh instance to see no result.

### Minimal reproduction project

[shader_instance_bug.zip](https://github.com/godotengine/godot/files/9206057/shader_instance_bug.zip)

### PR DESCRIPTION
**Pull request by Chaosus**
Fix #63566

### CODE REVIEW

File: drivers/gles3/storage/material_storage.cpp [hunk 1]
```diff
@@ -2320,11 +2320,14 @@ void MaterialStorage::global_shader_uniforms_instance_update(RID p_instance, int
 		ShaderLanguage::TYPE_VEC3, // vec3
 		ShaderLanguage::TYPE_IVEC3, //vec3i
 		ShaderLanguage::TYPE_MAX, //xform2d not supported here
+		ShaderLanguage::TYPE_VEC4, //vec4
+		ShaderLanguage::TYPE_MAX, //ivec4 not supported here
```
Comment (akien-mga) [inline drivers/gles3/storage/material_storage.cpp:2324]: I guess `TYPE_IVEC4` could be added using `Vector4i` now that it's available?

**Review by akien-mga — APPROVED** [review]

File: drivers/gles3/storage/material_storage.cpp (hunk 1 above)
Comment (Chaosus) [reply drivers/gles3/storage/material_storage.cpp]: Ah, yes, its supported. Fixed.
