### PR TITLE
Check `playback_queue` existance after emit `animation_finished` signal

### LINKED ISSUE #116674: Calling `AnimationPlayer.stop()` on `animation_finished` with queued animation crashes the process
### Tested versions

- Reproducible in: 4.6.1.stable, 4.7.dev [a3e84cc2af14aa4cffbefd8e13492e59567a64e3]
- Not reproducible in: 4.5.1.stable

### System information

Godot v4.7.dev (a3e84cc2a) - Fedora Linux 43 (Forty Three) on Wayland - X11 display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 9070 XT (RADV GFX1201) - AMD Ryzen 9 9950X3D 16-Core Processor (32 threads) - 60.39 GiB memory

### Issue description

The following script:

```gdscript
extends AnimationPlayer

func _ready() -> void:
    play("my_first_animation")
    queue("my_second_animation")
    await animation_finished
    stop()
```

Will cause the process to crash here:

https://github.com/godotengine/godot/blob/a3e84cc2af14aa4cffbefd8e13492e59567a64e3/scene/animation/animation_player.cpp#L344

... with the following call stack:

```
AnimationPlayer::_blend_post_process() (scene/animation/animation_player.cpp:344)
AnimationMixer::_process_animation(double, bool) (scene/animation/animation_mixer.cpp:999)
AnimationMixer::_notification(int) (scene/animation/animation_mixer.cpp:2349)
AnimationMixer::_notification_forwardv(int) (scene/animation/animation_mixer.h:43)
AnimationPlayer::_notification_forwardv(int) (scene/animation/animation_player.h:37)
Object::_notification_forward(int) (core/object/object.cpp:1012)
Object::notification(int, bool) (core/object/object.h:929)
SceneTree::_process_group(SceneTree::ProcessGroup*, bool) (scene/main/scene_tree.cpp:1201)
SceneTree::_process(bool) (scene/main/scene_tree.cpp:1281)
SceneTree::process(double) (scene/main/scene_tree.cpp:708)
Main::iteration() (main/main.cpp:4944)
OS_LinuxBSD::run() (platform/linuxbsd/os_linuxbsd.cpp:995)
main (platform/linuxbsd/godot_linuxbsd.cpp:121)
```

... because the access of `playback_queue.front()->get()` doesn't take into account that the emission of `animation_finished` just above it can clear `playback_queue`:

https://github.com/godotengine/godot/blob/a3e84cc2af14aa4cffbefd8e13492e59567a64e3/scene/animation/animation_player.cpp#L340-L342

This emission of `animation_finished` was added in #112571, so would seem to be cause for this regression.

### Steps to reproduce

1. Open the MRP
2. Run the main scene
3. Note the crash after the first animation plays

### Minimal reproduction project (MRP)

[animation-player-crash.zip](https://github.com/user-attachments/files/25495151/animation-player-crash.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
- Fixes #116674

If the `playback_queue` becomes empty within a `finished` signal (e.g., `stop()` is called there), it should abort because the queue should not be accessed.

### CODE REVIEW

**Comment by mihe** [comment]
If you do this instead you won't need to duplicate the cleanup code:

```diff
void AnimationPlayer::_blend_post_process() {
	if (end_reached) {
		// If the method track changes current animation, the animation is not finished.
		if (tmp_from == animation_set[playback.current.animation_name].animation->get_instance_id()) {
			if (playback_queue.size()) {
				if (!finished_anim.is_empty()) {
					emit_signal(SceneStringName(animation_finished), finished_anim);
				}
+				if (playback_queue.size()) {
					String old = playback.assigned;
					play(playback_queue.front()->get());
					String new_name = playback.assigned;
					playback_queue.pop_front();
					if (end_notify) {
						emit_signal(SceneStringName(animation_changed), old, new_name);
					}
+				}
			} else {
				_clear_caches();
				playing = false;
				_set_process(false);
				if (end_notify) {
					if (!finished_anim.is_empty()) {
						emit_signal(SceneStringName(animation_finished), finished_anim);
					}
					emit_signal(SNAME("current_animation_changed"), "");
					if (movie_quit_on_finish && OS::get_singleton()->has_feature("movie")) {
						print_line(vformat("Movie Maker mode is enabled. Quitting on animation finish as requested by: %s", get_path()));
						get_tree()->quit();
					}
				}
			}
		}
		end_reached = false;
		end_notify = false;
	}
	tmp_from = ObjectID();
}
```

**Review by mihe — APPROVED** [review]
I don't agree with duplicating the cleanup code for the sake of avoiding a function call (that also happens to be `_FORCE_INLINE_`) but it's not worth arguing over.

Again, I can confirm that this fixes the crash, and the change looks straight-forward enough that I feel comfortable approving it, despite not being familiar with this code.

File: scene/animation/animation_player.cpp [hunk 1]
```diff
@@ -339,6 +339,13 @@ void AnimationPlayer::_blend_post_process() {
 			if (playback_queue.size()) {
 				if (!finished_anim.is_empty()) {
 					emit_signal(SceneStringName(animation_finished), finished_anim);
+					// Abort if playback_queue is cleared by animation_finished signal.
+					if (!playback_queue.size()) {
```
Comment (AThousandShips) [inline scene/animation/animation_player.cpp]:
```suggestion
					if (playback_queue.is_empty()) {
```
