### PR TITLE
Fix RendererRD crash on start on Intel Macs.

### LINKED ISSUE #105422: Crash under MacOS when creating or importing a project
### Tested versions

Reproducible in e5ccaa79e2a2d5551369bd6cc1f8ed654a791275

Unable to test in earlier versions.

### System information

Unable to access the menu bar from the project manager.

### Issue description

In order to test the new AccessKit integration, I have compiled e5ccaa79e2a2d5551369bd6cc1f8ed654a791275 with AccessKit-c 0.15.1 under MacOS 12.7.6 on an late 2014 Intel Mac Mini. I am running VoiceOver.

I don't have any export templates, nothing has been changed as far as the configuration is concerned, this is a vanilla setup using an auto-generated app bundle

When I try to import a new project (Godot Steam Audio Demo in this case), or create a new one, Godot crashes.

I am unfortunately unable to test earlier versions as the UI is not usable with VoiceOver.

Verbose log from the command line when Godot is ran using the generated new project file:

```
WorkerThreadPool: 4 threads, 3 max low-priority.
Godot Engine v4.5.dev.custom_build.e5ccaa79e (2025-04-15 00:39:54 UTC) - https://godotengine.org
TextServer: Added interface "Dummy"
TextServer: Added interface "ICU / HarfBuzz / Graphite (Built-in)"
[mvk-info] MoltenVK version 1.2.11, supporting Vulkan version 1.2.296.
	The following 107 Vulkan extensions are supported:
...
[mvk-info] GPU device:
	model: Intel Iris Graphics
	type: Integrated
	vendorID: 0x8086
	deviceID: 0x0a2e
	pipelineCacheUUID: 81541F64-0C07-0200-0000-000100000000
	GPU memory available: 1536 MB
	GPU memory used: 0 MB
	Metal Shading Language 2.4
	supports the following GPU Features:
		GPU Family Mac 2
		Read-Write Texture Tier 1
[mvk-info] Created VkInstance for Vulkan version 1.2.0, as requested by app, with the following 4 Vulkan extensions enabled:
	VK_KHR_get_physical_device_properties2 v2
	VK_KHR_surface v25
	VK_EXT_debug_utils v2
	VK_EXT_metal_surface v1
Devices:
  #0: Intel Intel Iris Graphics - Supported, Integrated
Optional extension VK_KHR_fragment_shading_rate not found
Optional extension VK_EXT_fragment_density_map not found
Optional extension VK_EXT_astc_decode_mode not found
Optional extension VK_KHR_buffer_device_address not found
Optional extension VK_EXT_texture_compression_astc_hdr not found
Optional extension VK_KHR_external_memory_fd not found
Optional extension VK_EXT_device_fault not found
- Vulkan Variable Rate Shading not supported
- Vulkan Fragment Density Map not supported
- Vulkan multiview supported:
  max view count: 32
  max instances: 134217727
- Vulkan subgroup:
  size: 32
  min size: 32
  max size: 32
  stages: STAGE_TESSELLATION_CONTROL, STAGE_FRAGMENT, STAGE_COMPUTE
  supported ops: FEATURE_BASIC, FEATURE_VOTE, FEATURE_ARITHMETIC, FEATURE_BALLOT, FEATURE_SHUFFLE, FEATURE_SHUFFLE_RELATIVE, FEATURE_QUAD
  quad operations in all stages
[mvk-info] Vulkan semaphores using MTLEvent.
[mvk-info] Descriptor sets binding resources using Metal argument buffers.
[mvk-info] Created VkDevice to run on GPU Intel Iris Graphics with the following 11 Vulkan extensions enabled:
	VK_KHR_16bit_storage v1
	VK_KHR_create_renderpass2 v1
	VK_KHR_image_format_list v1
	VK_KHR_maintenance2 v1
	VK_KHR_multiview v1
	VK_KHR_shader_float16_int8 v1
	VK_KHR_storage_buffer_storage_class v1
	VK_KHR_swapchain v70
	VK_EXT_debug_marker v4
	VK_EXT_pipeline_creation_cache_control v3
	VK_EXT_subgroup_size_control v2
Vulkan 1.2.296 - Forward+ - Using Device #0: Intel - Intel Iris Graphics
Startup PSO cache (0.0 MiB)
Using "default" pen tablet driver...
Creating VMA small objects pool for memory type index 0
Shader 'CanvasSdfShaderRD' (group 0) SHA256: 9c84637492fc161d7c38a4937218fcc9e09ab46e0290bfb40b24df2c7f1501f7
Shader 'SkeletonShaderRD' (group 0) SHA256: 13257e1bb079a860fbbc2216a2a2cbc590ba51b59f9917629d417ad23cdce93e
Shader 'SortShaderRD' (group 0) SHA256: 0d8c95aac91774c216743bf9fc3b9c8863f513871cfe95f384d30b98340d58f1
Shader 'ParticlesShaderRD' (group 0) SHA256: 73fe1cb29d7bcc095c7820bfd793535a0f9a8aeb4325b2e85d988e2bbeedd802
Shader 'ParticlesCopyShaderRD' (group 0) SHA256: bd65aefd9406b74b0f1419b936c140e4bbcf2a957b6a2008ee629ccfb855d7b3
Shader 'CanvasShaderRD' (group 0) SHA256: 59be06ee88d498018e50b70c83a628d98325b1b05829cdd781672c1e624a8413
Shader 'CanvasOcclusionShaderRD' (group 0) SHA256: 8e1113d95043583feedfb34e249bd7dfbbfca683d2519f084e9f992c8b2da2b6

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.5.dev.custom_build (e5ccaa79e2a2d5551369bd6cc1f8ed654a791275)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] 1   libsystem_platform.dylib            0x00007ff8066bbdfd _sigtramp + 29
[2] 2   ???                                 0x00007fc77ba30d30 0x0 + 140494749502768
[3] RendererRD::SkyRD::SkyRD()
[4] RendererSceneRenderRD::RendererSceneRenderRD()
[5] RendererSceneRenderImplementation::RenderForwardClustered::RenderForwardClustered()
[6] RendererCompositorRD::RendererCompositorRD()
[7] RendererCompositorRD::_create_current()
[8] RenderingServerDefault::_init()
[9] Main::setup2(bool)
[10] Main::setup(char const*, int, char**, bool)
[11] OS_MacOS::start_main()
[12] Ref<DirAccess> DirAccess::_create_builtin<DirAccessMacOS>()
[13] 13  CoreFoundation                      0x00007ff80676268c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
[14] 14  CoreFoundation                      0x00007ff8067ffaa2 ___CFXRegistrationPost_block_invoke + 49
[15] 15  CoreFoundation                      0x00007ff8067ffa20 _CFXRegistrationPost + 496
[16] 16  CoreFoundation                      0x00007ff8067342f8 _CFXNotificationPost + 735
[17] 17  Foundation                          0x00007ff80757358e -[NSNotificationCenter postNotificationName:object:userInfo:] + 82
[18] 18  AppKit                              0x00007ff8091b2357 -[NSApplication _postDidFinishNotification] + 306
[19] 19  AppKit                              0x00007ff8091b20a7 -[NSApplication _sendFinishLaunchingNotification] + 208
[20] 20  AppKit                              0x00007ff8091afc78 -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 541
[21] 21  AppKit                              0x00007ff8091af8cf -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 665
[22] 22  Foundation                          0x00007ff80759e4b4 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 308
[23] 23  Foundation                          0x00007ff80759e326 _NSAppleEventManagerGenericHandler + 80
[24] 24  AE                                  0x00007ff80ce28484 _AppleEventsCheckInAppWithBlock + 14323
[25] 25  AE                                  0x00007ff80ce27cee _AppleEventsCheckInAppWithBlock + 12381
[26] 26  AE                                  0x00007ff80ce21343 aeProcessAppleEvent + 419
[27] 27  HIToolbox                           0x00007ff80f42ece2 AEProcessAppleEvent + 54
[28] 28  AppKit                              0x00007ff8091a9efe _DPSNextEvent + 2036
[29] 29  AppKit                              0x00007ff8091a8166 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
[30] 30  AppKit                              0x00007ff80919a818 -[NSApplication run] + 586
[31] 31  Godot                               0x000000010dcc30c1 main + 241
[32] 32  dyld                                0x0000000122bec52e start + 462
-- END OF BACKTRACE --
```

### Steps to reproduce

Create or import a project. Godot crashes while the project is loading.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Regression from https://github.com/godotengine/godot/pull/103306, check was done before `RSG::utilities` init (required for `get_video_adapter_name`).

Fixes https://github.com/godotengine/godot/issues/105422

Note: marked as "cherrypick 4.4" since #103306 is.

### CODE REVIEW

File: servers/rendering/renderer_rd/environment/sky.cpp [hunk 1]
```diff
@@ -1286,6 +1280,16 @@ void SkyRD::update_radiance_buffers(Ref<RenderSceneBuffersRD> p_render_buffers,
 		sky_mode = RS::SKY_MODE_QUALITY;
 	}
 
+#if defined(MACOS_ENABLED) && defined(__x86_64__)
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/environment/sky.cpp:1283]: Is this check needed every frame for every sky? It should just be done once right?

Comment (bruvzg) [reply servers/rendering/renderer_rd/environment/sky.cpp]: Moved it to a separate function, now it should be called only one.

**Review by clayjohn — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
