### PR TITLE
Made slide and reflect active verbs acting on itself in Vector2 and V…

### LINKED ISSUE #8201: Vector math reflect() function is wrong?
I'm not math specialist but I think Vector reflect() math is wrong'ish.

When I'v checked the Godot source, code looked like this:

Vector2 Vector2::reflect(const Vector2 &p_vec) const {
	return p_vec - *this * this->dot(p_vec) * 2.0;
}

It produced results that don't look like correct vector reflection.

Shouldn't formula be:
-(vec - vec.dot(normal) * 2 * normal)

### PR DESCRIPTION
**Pull request by ghost**
…ector3.

This is in alignment with other functions in vector classes.
Also added checks for normalization, fixed the sign of reflect (which now corresponds to reflection along a plane mathematically), added bounce method and updated docs.

Fixes #8201.

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Hm, I don't see bindings in variant_call.cpp being added in this PR for VectorN::bounce.. And also, would be nice if `is_normalized` is exposed too.

**Comment by tagcup** [comment]
I'll add GDScript bindings eventually. There're many such functions that should be added before 3.0.

**Comment by reduz** [comment]
Seems good to me, but make sure any checks you add are disabled on release

**Comment by tagcup** [comment]
> Seems good to me, but make sure any checks you add are disabled on release

This kind of thing happens in other places in core/math actually (axis-angle rotations also expect normalized vectors), so I need your input to standardize this.

So in this case, if it's not normalized, it's a bug in the game, and will lead to diverging results.

But if we're thinking like "if the code passes such checks during debug, we can assume that the user has properly normalized everything, and remove them from release for the sake of performance". I'm just worried that this assumption may be too strong: user code may have passed these checks by luck.

So what do you think? If you want to take the fast and risky path, I can submit a follow up PR to disable this check and other similar checks for release.

**Comment by bojidar-bg** [comment]
@tagcup Ahem. Your `bounce` docs won't persist a `-doctool` run, since they aren't registered. That's the main reason I asked you to bind it.

**Comment by tagcup** [comment]
Ah, I see. Added. Thanks for letting know!

**Comment by Hinsbart** [comment]
Doesn't follow the style guidelines, check the Travis logs.

We also have [git hooks](https://github.com/godotengine/godot/tree/master/misc/hooks) that run this check locally when trying to commit, you might find them handy.
(I do, even though it complains about every commit I try to make :p)

**Comment by tagcup** [comment]
I know, I fixed that already.

**Comment by tagcup** [comment]
Oh no, that again. I'll fix it too.

File: core/math/vector3.h [hunk 1]
```diff
@@ -400,14 +401,23 @@ void Vector3::zero() {
...
 }
 
-Vector3 Vector3::reflect(const Vector3 &p_vec) const {
+Vector3 Vector3::bounce(const Vector3 &p_n) const {
+	return -reflect(p_n);
+}
 
-	return p_vec - *this * this->dot(p_vec) * 2.0;
+Vector3 Vector3::reflect(const Vector3 &p_n) const {
+#ifdef
```
Comment (akien-mga) [inline core/math/vector3.h]:
```
core/math/vector3.h:417:7: error: no macro name given in #ifdef directive
```
:)

Comment (tagcup) [inline core/math/vector3.h]: Yeah, been a little busy during the weekend, sorry! Will push the update in a moment

**Comment by tagcup** [comment]
@reduz Checks are enabled for debug only.

Haven't changed other similar stuff in core/math, which can be done in a separate PR, I'm waiting for your input on that.

**Comment by n-pigeon** [comment]
@tagcup Awesome! Thx for this fix. Quick question, you plan to bind is_normalized() later? Looks like very useful :)

**Comment by tagcup** [comment]
Sure thing, among others

File: core/math/vector3.h [hunk 2]
```diff
@@ -400,14 +401,23 @@ void Vector3::zero() {
 	x = y = z = 0;
 }
 
-Vector3 Vector3::slide(const Vector3 &p_vec) const {
-
-	return p_vec - *this * this->dot(p_vec);
+// slide returns the component of the vector along the given plane, specified by its normal vector.
+Vector3 Vector3::slide(const Vector3 &p_n) const {
+#ifdef DEBUG_ENABLED
```
Comment (nunodonato) [inline core/math/vector3.h]: after this change my character barely moves in the ground because of the slide function.
I get a lot of errors coming from this
error

**Comment by reduz** [comment]
Please remove the normalization tests, it's perfectly possible to obtain vectors that are not perfectly normalized but "good enough" (ie, after being transformed by an orthonormal matrix, rotated, etc.), yet trigger the error.

**Comment by reduz** [comment]
To make it clear, it's feasible to get a not perfectly normalized vector (due to numerical error) into a function that expects a normalized vector, in a context where it still perfectly serves it's purpose.. this happens a lot in Godot, so I guess we should not be checking for normalized vectors anywhere.

**Comment by tagcup** [comment]
@reduz If that was the problem here, the solution to that would be to make the error margin larger, rather than removing those checks altogether, because those checks can catch actual bugs (as in the case here): he's using `n.slide(motion)`, where he should be using `motion.slide(n)`.

@nunodonato Can you check the documentation of Vector2.slide again?

**Comment by nunodonato** [comment]
@tagcup You are right, using `motion.slide(n)` seems to work fine. I copied the code from the Kinematic3D Demo, so I guess that needs to be fixed too.

**Comment by tagcup** [comment]
@reduz To be clear, we're already using `CMP_EPSILON` (defined to be 1e-5) for those checks BTW, which is already quite large to accommodate the kind of errors you mentioned.

Errors larger than `CMP_EPSILON` are bad signs indicating a serious problem anyway (such as accumulation of errors).

@nunodonato So I think we can say your experience has been in favor of those checks :) Demos will be updated, there are various breaking math changes since 2.0.
