### PR TITLE
Checking path variable if empty before opening external editor to fix…

### LINKED ISSUE #71466: When external editor is set to true with no exec path freeze of Godot 4 beta 12
### Godot version

4.0 beta 12 mono

### System information

MacOS 13.1, Apple M1 Pro

### Issue description

When `text_editor/external/use_external_editor` is set to true but `text_editor/external/exec_path` is not set and I create a new script and attach it to a node Godot freezes and i need to force quit the application.
Also after a restart when double clicking on the script the application freezes but I can quit normally

### Steps to reproduce

- Set Use External Editor to true in Editor Settings and leave Exec Path empty
- Create a new project with Moblie Renderer and Git Versioning in Godot
- Create a 3D Scene
- Create a gd script in the FileSystem inspector or directly attach the script to a node

### Minimal reproduction project

[New Game Project.zip](https://github.com/godotengine/godot/files/10420510/New.Game.Project.zip)

### PR DESCRIPTION
**Pull request by chris-prenissl**
Fix #71466

Added check for exec_path to prevent editor freeze when try to edit a script while no exec_path is set

### CODE REVIEW

File: editor/plugins/script_editor_plugin.cpp [hunk 1]
```diff
@@ -2255,11 +2255,17 @@ bool ScriptEditor::edit(const Ref<Resource> &p_resource, int p_line, int p_col,
 		if (!has_file_flag) {
 			args.push_back(script_path);
 		}
+        
+        if (path.is_empty()) {
+            ERR_PRINT("use_external_editor flag is set, but no path to external text editor is set")
+            return false;
+        } else {
```
Comment (akien-mga) [inline editor/plugins/script_editor_plugin.cpp:2262]: You can use instead (also fixed formatting):
```suggestion
        ERR_FAIL_COND_V_MSG(path.is_empty(), false, "The `use_external_editor` setting is enabled, but the path to the external text editor is not configured in `text_editor/external/exec_path`.");
```

The indentation also needs to be fixed (you used spaces when we use tabs everywhere).

Comment (akien-mga) [reply editor/plugins/script_editor_plugin.cpp:2262]: That being said, I think erroring it and aborting is not the right solution here. Just below there is `WARN_PRINT("Couldn't open external text editor, using internal");` (which could get an extra period at the end btw).

I think this is sufficient, albeit it could be turned into an `ERR_PRINT`, maybe with slightly improved text. So you should just skip creating the process if there's no path.

```
if (!path.is_empty()) {
	Error err = OS::get_singleton()->create_process(path, args);
	if (err == OK) {
		return false;
	}
}

ERR_PRINT("Couldn't open external text editor, falling back to the internal editor. Review your `text_editor/external/` editor settings.");
```

**Comment by akien-mga** [comment]
For the record, your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

**Comment by snakept** [comment]
Thanks for the review @akien-mga. I'm still new to the github workflow with forking, branching and issues. Hope git user.email and name is now correct.

I took your suggestion. hope the code is now helpful

**Comment by akien-mga** [comment]
Sorry I pressed "close" by mistake.

This looks correct now as a way to error out early if the path is not defined, which is a possible solution that could be fine.

But I think there could be value in doing it the way I later suggested here:
https://github.com/godotengine/godot/pull/71528#discussion_r1072007515

i.e. we still fall back to the internal editor if the external editor is misconfigured.

**Comment by snakept** [comment]
Ok, you are right. I overread the comment. I will work on the suggested solution later when i have time and fix clang errors.

**Comment by snakept** [comment]
I hope this is how it should be now

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by snakept** [comment]
Feels good😊 And thank you for helping:)
