### PR TITLE
Fix expression base path on transitions

### LINKED ISSUE #62530: Advance expression for AnimationTree doesn't seem to work
### Godot version

v4.0.alpha.calinou [caa9ec8ac]

### System information

Windows 10, Vulkan

### Issue description

I'm using a simple state machine within the AnimationTree
image

Along with Advance Expressions like (this one is for idle_1 to walking):
image
 
However, it simply doesn't trigger the transition

### Steps to reproduce

1. Create a CharacterBody3D
2. Drop a model with animations (a gltf with a character for example) inside the CharacterBody3D
3. Add an AnimationTree node, assign it to the AnimationPlayer from your model, enable it and assign the Advance expression base node to be the CharacterBody3D
4. Create a new Tree Root in your AnimationTree. I used a simple State Machine.
5. Setup your tree using Advance Expressions. I just created an idle and a walking state, with a transition idle->walking using the expression "velocity.length()>1.0"
6. Check the results in-game

### Minimal reproduction project

[TestExpressions.zip](https://github.com/godotengine/godot/files/9012606/TestExpressions.zip)

### PR DESCRIPTION
**Pull request by GuilhermeGSousa**
Completely fixes #62530

Currently setting `Expression Base Node` on a transition (as shown below) prevents it from ever being triggered. The only way of using expressions is to not set this field, and set it only on its `AnimationTree`
image

This PR fixes this issue and allows for the `Expression Base Node` field on transitions to override the one set on the `AnimationTree`.

### CODE REVIEW

**Comment by joaopedrosgs** [comment]
I tested and it seems to be working correctly. Nice =)

**Comment by fire** [comment]
@lyuma Expressed some commentary on this feature, but I want to fix the feature as is.

File: scene/animation/animation_node_state_machine.h [hunk 1]
```diff
@@ -33,6 +33,7 @@
 
 #include "core/math/expression.h"
 #include "scene/animation/animation_tree.h"
+#include "scene/main/window.h"
```
Comment (fire) [inline scene/animation/animation_node_state_machine.h:36]: Is this include required?

File: scene/animation/animation_node_state_machine.cpp [hunk 2]
```diff
@@ -656,13 +656,15 @@ bool AnimationNodeStateMachinePlayback::_check_advance_condition(const Ref<Anima
 		ERR_FAIL_COND_V(tree_base == nullptr, false);
 
 		NodePath advance_expression_base_node_path;
-		if (!transition->advance_expression_base_node.is_empty()) {
-			advance_expression_base_node_path = transition->advance_expression_base_node;
+		Node *expression_base;
```
Comment (fire) [inline scene/animation/animation_node_state_machine.cpp:659]: Can you nullptr initialize?

**Review by fire — APPROVED** [review]
The general shape of the bugfix approved. Found some code style comments.

# Test plan
1. Downloaded the windows editor from github actions.
2. Download the test case https://github.com/godotengine/godot/files/9012606/TestExpressions.zip
3. Play


https://user-images.githubusercontent.com/32321/192111629-00cf7f9b-c176-4afb-b487-683c968904b9.mp4

File: scene/animation/animation_node_state_machine.h (hunk 1 above)
Comment (GuilhermeGSousa) [reply scene/animation/animation_node_state_machine.h:36]: Its needed because `get_root()` returns a Window, but I could move it to the `.cpp` file instead

**Comment by GuilhermeGSousa** [comment]
I'll add your changes tomorrow so we can close this

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
