### PR TITLE
Fix for GDScriptHighlighter dictionaries as function arguments

### LINKED ISSUE #81362: Incorrect GDScript highlighting of variables passed as values in dictionary function arguments.
### Godot version

4.2.dev4

### System information

Godot v4.2.dev4 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

image

I noticed the bug in a real use case here. Note that `w` and `h` are highlighted like they are types.

### Steps to reproduce

```gdscript
var a = 3
f({"a": a})
```

Paste this into a script

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by adeneve**
Fixes [#81362](https://github.com/godotengine/godot/issues/81362)

Dictionaries passed as function arguments were having their values highlighted green due to being misinterpreted as function argument hints.

Pics below and after code change.
beforePic
afterPic

### CODE REVIEW

File: modules/gdscript/editor/gdscript_highlighter.cpp [hunk 1]
```diff
@@ -68,6 +68,8 @@ Dictionary GDScriptSyntaxHighlighter::_get_line_syntax_highlighting_impl(int p_l
 	bool in_signal_declaration = false;
 	bool expect_type = false;
 
+	int in_dict = 0;
```
Comment (MewPurPur) [inline modules/gdscript/editor/gdscript_highlighter.cpp:71]: `in_function_arg_dicts` to make it clear.

File: modules/gdscript/editor/gdscript_highlighter.cpp [hunk 2]
```diff
@@ -495,7 +505,7 @@ Dictionary GDScriptSyntaxHighlighter::_get_line_syntax_highlighting_impl(int p_l
 					k++;
 				}
 
-				if (str[k] == ':') {
+				if (str[k] == ':' && !in_dict) {
```
Comment (MewPurPur) [inline modules/gdscript/editor/gdscript_highlighter.cpp:508]:
```suggestion
				if (str[k] == ':' && in_function_arg_dicts > 0) {
```

File: modules/gdscript/editor/gdscript_highlighter.cpp [hunk 3]
```diff
@@ -480,6 +482,14 @@ Dictionary GDScriptSyntaxHighlighter::_get_line_syntax_highlighting_impl(int p_l
...
 			}
 
+			if (in_function_args && str[j] == '{') {
+				in_dict += 1;
+			}
+
+			if (in_function_args && str[j] == '}') {
+				in_dict -= 1;
+			}
+
```
Comment (MewPurPur) [inline modules/gdscript/editor/gdscript_highlighter.cpp:492]:
```suggestion
			if (in_function_args) {
				if (str[j] == '{') {
					in_function_arg_dicts += 1;
				} else if (str[j] == '}') {
					in_function_arg_dicts -= 1;
				}
			}
```

**Review by MewPurPur — APPROVED** [review]
Looks good, mostly style nitpicks.

**Comment by MewPurPur** [comment]
While at it, you can also fix the comments near your changed lines to use "Sentence case."

File: modules/gdscript/editor/gdscript_highlighter.cpp (hunk 2 above)
Comment (adeneve) [reply modules/gdscript/editor/gdscript_highlighter.cpp:508]: Hi @MewPurPur ,

I think that condition on line 508 has to be inverted
e.g. i think any of the below would work
```
in_function_arg_dicts == 0 
in_function_arg_dicts <= 0
!in_function_arg_dicts
```

**Comment by adeneve** [comment]
Commit has been amended  👍. Ready for another review.

File: modules/gdscript/editor/gdscript_highlighter.cpp [hunk 4]
```diff
@@ -480,6 +482,14 @@ Dictionary GDScriptSyntaxHighlighter::_get_line_syntax_highlighting_impl(int p_l
 				in_function_args = false;
 			}
 
+			if (in_function_args) {
+				if (str[j] == '{'){
+					in_function_arg_dicts += 1;
+				} else if (str[j] == '}') {
```
Comment (MewPurPur) [inline modules/gdscript/editor/gdscript_highlighter.cpp:488]: Now that I think of it... Add `in_function_arg_dicts > 0` to this condition.

File: modules/gdscript/editor/gdscript_highlighter.cpp [hunk 5]
```diff
@@ -495,8 +505,8 @@ Dictionary GDScriptSyntaxHighlighter::_get_line_syntax_highlighting_impl(int p_l
 					k++;
 				}
 
-				if (str[k] == ':') {
-					// has type hint
+				if (str[k] == ':' && in_function_arg_dicts == 0) {
+					// Has type hint
```
Comment (MewPurPur) [inline modules/gdscript/editor/gdscript_highlighter.cpp:509]: Add punctuation.

Comment (adeneve) [reply modules/gdscript/editor/gdscript_highlighter.cpp:509]: just a period at the end like - 'Has type hint.' is that right? or do you want a dash in there too. 'Has type - hint.' ?

Comment (Scoppio) [reply modules/gdscript/editor/gdscript_highlighter.cpp:509]: yes, to be like the other comments in this file, all has punctuation at the end.

**Review by MewPurPur — APPROVED** [review]

**Review by dalexeev — APPROVED** [review]
Looks good to me. I've tested and it works with braces in string literals. Perhaps in some cases like multiline code this does not work, but this is not something that we could fix within a small PR.

Also I noticed a bug with parentheses:



`bool in_function_args = false;` should be replaced with `int in_function_args = 0;` like in this PR.

**Comment by akien-mga** [comment]
> `bool in_function_args = false;` should be replaced with `int in_function_args = 0;` like in this PR.

@adeneve Would you be able to update this PR with this additional fix? If so, please do it by amending the commit, so it stays a single commit for both related fixes.

**Comment by adeneve** [comment]
Ready for another review. Commit has been amended to address the parentheses bug.
 
> 
> 
> `bool in_function_args = false;` should be replaced with `int in_function_args = 0;` like in this PR.

**Review by MewPurPur — APPROVED** [review]
Code review LGTM

File: modules/gdscript/editor/gdscript_highlighter.cpp [hunk 6]
```diff
@@ -472,12 +474,24 @@ Dictionary GDScriptSyntaxHighlighter::_get_line_syntax_highlighting_impl(int p_l
...
+				in_function_args -= 1;
+			}
+
+			if (in_function_args > 0) {
+				if (str[j] == '{') {
+					in_function_arg_dicts += 1;
+				} else if (str[j] == '}' && in_function_arg_dicts > 0) {
+					in_function_arg_dicts -= 1;
+				}
 			}
```
Comment (dalexeev) [inline modules/gdscript/editor/gdscript_highlighter.cpp:495]: I haven't tested it, but perhaps this code is a little better?

```c++
			if (in_function_name) {
				if (str[j] == '(' && in_function_args == 0) {
					in_function_args = 1;
				}
			} else if (in_function_args > 0) {
				if (str[j] == '(') {
					in_function_args += 1;
				} else if (str[j] == ')') {
					in_function_args -= 1;
				} else if (str[j] == '{') {
					in_function_arg_dicts += 1;
				} else if (str[j] == '}' && in_function_arg_dicts > 0) {
					in_function_arg_dicts -= 1;
				}
			}
```

Comment (adeneve) [reply modules/gdscript/editor/gdscript_highlighter.cpp:495]: Yes, this looks more concise. I will take another look today!

Comment (adeneve) [reply modules/gdscript/editor/gdscript_highlighter.cpp]: Commit has been amended with the suggested code improvement. 👍

File: modules/gdscript/editor/gdscript_highlighter.cpp [hunk 7]
```diff
@@ -488,15 +504,15 @@ Dictionary GDScriptSyntaxHighlighter::_get_line_syntax_highlighting_impl(int p_l
 				expect_type = true;
 			}
 
-			if (in_variable_declaration || in_function_args) {
+			if (in_variable_declaration || in_function_args > 0) {
 				int k = j;
 				// Skip space
```
Comment (dalexeev) [inline modules/gdscript/editor/gdscript_highlighter.cpp:509]:
```suggestion
				// Skip space.
```

**Review by dalexeev — APPROVED** [review]

File: modules/gdscript/editor/gdscript_highlighter.cpp [hunk 8]
```diff
@@ -473,11 +475,25 @@ Dictionary GDScriptSyntaxHighlighter::_get_line_syntax_highlighting_impl(int p_l
...
+						in_function_args -= 1;
+						break;
+					case '{':
+						in_function_arg_dicts += 1;
+						break;
+					case '}':
+						in_function_arg_dicts -= 1;
+						break;
+				}
 			}
```
Comment (dalexeev) [inline modules/gdscript/editor/gdscript_highlighter.cpp:497]: Sorry, I realized that there is a bug in the code I suggested.



Here is the correct option:

```c++
			if (in_function_args > 0) {
				switch (str[j]) {
					case '(':
						in_function_args += 1;
						break;
					case ')':
						in_function_args -= 1;
						break;
					case '{':
						in_function_arg_dicts += 1;
						break;
					case '}':
						in_function_arg_dicts -= 1;
						break;
				}
			} else if (in_function_name && str[j] == '(') {
				in_function_args = 1;
				in_function_arg_dicts = 0;
			}
```

Comment (adeneve) [reply modules/gdscript/editor/gdscript_highlighter.cpp:497]: No worries! I’ll get that updated in a few hours.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
