### PR TITLE
Fixes Visual Script node operator mismatch

### LINKED ISSUE #49943: Incorrect operator property for visual script nodes.
### Godot version

4.0 Dev (92f75046378a63b46946e8acbd7c224f027ebfa5)

### System information

Windows 10, OpenGL ES 3.0 Renderer: AMD Radeon(TM) Vega 10 Graphics

### Issue description

Name of the operator property in the inspector does not match with the type of Visual Script node. This is happening for bitwise and logical operator nodes. 

The issue is not observed in 3.3.x stable builds. I believe this is side effect of new implementation of variant operators added in https://github.com/godotengine/godot/pull/43323.

Please check the screenshot animation below for exact issue. 
VisualScriptOperatorMismatch

I have made required changes to fix this issue, will submit the PR as well for review.

### Steps to reproduce

1. Add visual script to any node
2. Inside visual script editor add a node "Bitwise Shift Left".
3. Observe that operator property in inspector shows "concatenate"
4. Add another node "Logical AND", observe the operator property in the inspector shows "Bit Negate"

### Minimal reproduction project

I will submit if can't be re-produced with steps given.

### PR DESCRIPTION
**Pull request by MisoMosiSpy**
Root Cause: 

The op_names string array contains extra entry for **"Concatenate", //OP_STRING_CONCAT,** every operator after this entry if off by one.

Implemented Fix:

Replaced this array with function which returns the name string as per Variant::Operator instead of index. This will always keep them in sync.

Unit tested and verified with clang-format.

Since this is my first PR,  along with review please suggest if there is better way to fix this.

<i>Bugsquad edit</i>: Fix #49943

### CODE REVIEW

File: modules/visual_script/visual_script_nodes.cpp [hunk 1]
```diff
@@ -1080,10 +1112,13 @@ class VisualScriptNodeInstanceOperator : public VisualScriptNodeInstance {
 			if (p_outputs[0]->get_type() == Variant::STRING) {
 				r_error_str = *p_outputs[0];
 			} else {
+				// TODO: Do we need the long names here? we should use Variant::get_operator_name()
+				//       instead of VisualScriptOperator::get_operator_name(). That will also make
+				//       it consistent with gdscript error messages.
```
Comment (akien-mga) [inline modules/visual_script/visual_script_nodes.cpp:1117]: I don't have a strong opinion, but yes if you think it's best to use the `Variant` names in the error that should be fine.

Comment (MisoMosiSpy) [reply modules/visual_script/visual_script_nodes.cpp:1117]: Thanks. Yeah, I think Variant is better fit here, I will update the PR with this change today.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by MisoMosiSpy** [comment]
> Thanks! And congrats for your first merged Godot contribution 🎉

Thanks you very much, hoping to keep contributing :)
