### PR TITLE
Fix file rename crash after toggling split mode.

### LINKED ISSUE #84215: Crash after attempting selected file after toggling split modes.
### Godot version

5dc10b5aa506c4287c6ff87367efe031bc1a7d82

### System information

Windows 11

### Issue description

The engine will crash if you attempt to select an item in the thumbnail grid, then toggle between the filesystem split mode, then attempt to rename the file you had highlighted. This is due to renaming via the thumbnail grid depending upon on the 'current' ItemList variable, which gets unset when the panel is refreshed.

### Steps to reproduce

Create a project.
Create a file
Highlight the file
Switch between the split modes until you can see the thumbnail view again.
Press F2 or right click on the file you had selected and select rename.
The engine will now crash

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by SaracenOne**
This PR fixes a crash which occurs if you highlight a file in the thumbnail browser, then toggle between the split modes, and attempt to rename it again while it still shows up as highlighted. It fixes this by attempting to implicitly set the 'current' id of the selected file in the _update_file_list function.

Closes https://github.com/godotengine/godot/issues/84215

### CODE REVIEW

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -1159,6 +1163,11 @@ void FileSystemDock::_update_file_list(bool p_keep_selection) {
 		}
 		files->set_item_tooltip(item_index, tooltip);
 	}
+
+	// If we only have any selected items retained, we need to update the current idx.
+	if (valid_selection.size() >= 1) {
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:1168]:
```suggestion
	if (!valid_selection.is_empty()) {
```

**Review by KoBeWi — APPROVED** [review]

**Comment by SaracenOne** [comment]
@YuriSizov Fixed! Should be good to go now.

**Comment by YuriSizov** [comment]
Thanks!
