### PR TITLE
Fix crash when using non-`PackedScene` resource for POT generation

### LINKED ISSUE #76649: Generating a `.pot` file from a `.tscn` file opened in the script editor crashes Godot
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

`Linux 5.10.0-16-amd64 #1 SMP Debian 5.10.127-2 (2022-07-23) x86_64 GNU/Linux`

### Issue description

Using the `Generate POT` localization feature on a `.tscn` file which is opened in the script editor crashes Godot when clicking on the `save` button after choosing a file name for the `.pot` file.

The crash is reproducible for existing projects and new ones.

Here is the backtrace when using the debug build found at <https://github.com/Calinou/godot-debug-builds/releases/tag/v4.0>

```text
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.stable.custom_build (92bee43adba8d2401ef40e2480e53087bcb1eaf1)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x38d60) [0x7fac5eff8d60] (??:0)
[2] godot.linuxbsd.editor.x86_64(+0x3bc8bc4) [0x55c12db5ebc4] (/opt/godot/./core/object/ref_counted.h:61)
[3] godot.linuxbsd.editor.x86_64(+0x2675351) [0x55c12c60b351] (/opt/godot/./core/object/ref_counted.h:220)
[4] godot.linuxbsd.editor.x86_64(+0x2c3b50a) [0x55c12cbd150a] (/opt/godot/./core/object/ref_counted.h:220)
[5] godot.linuxbsd.editor.x86_64(+0x2c37101) [0x55c12cbcd101] (/opt/godot/./core/templates/cowdata.h:412)
[6] godot.linuxbsd.editor.x86_64(+0x4fa9ef1) [0x55c12ef3fef1] (/opt/godot/core/variant/callable.cpp:50)
[7] godot.linuxbsd.editor.x86_64(+0x5292fb8) [0x55c12f228fb8] (/opt/godot/core/object/object.cpp:1049)
[8] godot.linuxbsd.editor.x86_64(+0x1dec64a) [0x55c12bd8264a] (/opt/godot/./core/variant/variant.h:301)
[9] godot.linuxbsd.editor.x86_64(+0x1dfd0f2) [0x55c12bd930f2] (/opt/godot/./core/object/callable_method_pointer.h:105)
[10] godot.linuxbsd.editor.x86_64(+0x4fa9ef1) [0x55c12ef3fef1] (/opt/godot/core/variant/callable.cpp:50)
[11] godot.linuxbsd.editor.x86_64(+0x5292fb8) [0x55c12f228fb8] (/opt/godot/core/object/object.cpp:1049)
[12] godot.linuxbsd.editor.x86_64(+0x313d18e) [0x55c12d0d318e] (/opt/godot/./core/variant/variant.h:301)
[13] godot.linuxbsd.editor.x86_64(+0x31418b2) [0x55c12d0d78b2] (/opt/godot/./core/object/callable_method_pointer.h:105)
[14] godot.linuxbsd.editor.x86_64(+0x4fa9ef1) [0x55c12ef3fef1] (/opt/godot/core/variant/callable.cpp:50)
[15] godot.linuxbsd.editor.x86_64(+0x5292fb8) [0x55c12f228fb8] (/opt/godot/core/object/object.cpp:1049)
[16] godot.linuxbsd.editor.x86_64(+0x307c36f) [0x55c12d01236f] (/opt/godot/./core/variant/variant.h:301)
[17] godot.linuxbsd.editor.x86_64(+0x307d9a8) [0x55c12d0139a8] (/opt/godot/scene/gui/base_button.cpp:172)
[18] godot.linuxbsd.editor.x86_64(+0x307dcb6) [0x55c12d013cb6] (/opt/godot/./core/object/ref_counted.h:220)
[19] godot.linuxbsd.editor.x86_64(+0x3113f36) [0x55c12d0a9f36] (/opt/godot/scene/gui/control.cpp:1746)
[20] godot.linuxbsd.editor.x86_64(+0x3018981) [0x55c12cfae981] (/opt/godot/scene/main/viewport.cpp:1392)
[21] godot.linuxbsd.editor.x86_64(+0x301ae2c) [0x55c12cfb0e2c] (/opt/godot/scene/main/viewport.cpp:1659 (discriminator 1))
[22] godot.linuxbsd.editor.x86_64(+0x3020860) [0x55c12cfb6860] (/opt/godot/./core/object/ref_counted.h:220)
[23] godot.linuxbsd.editor.x86_64(+0x30565a1) [0x55c12cfec5a1] (/opt/godot/scene/main/window.cpp:1369)
[24] godot.linuxbsd.editor.x86_64(+0x3069e91) [0x55c12cfffe91] (/opt/godot/./core/object/ref_counted.h:220)
[25] godot.linuxbsd.editor.x86_64(+0x4fa9ef1) [0x55c12ef3fef1] (/opt/godot/core/variant/callable.cpp:50)
[26] godot.linuxbsd.editor.x86_64(+0xb715ba) [0x55c12ab075ba] (/opt/godot/platform/linuxbsd/x11/display_server_x11.cpp:3568)
[27] godot.linuxbsd.editor.x86_64(+0x4f2f630) [0x55c12eec5630] (/opt/godot/./core/object/ref_counted.h:220)
[28] godot.linuxbsd.editor.x86_64(+0x4f326ee) [0x55c12eec86ee] (/opt/godot/./core/templates/list.h:351)
[29] godot.linuxbsd.editor.x86_64(+0xb736c0) [0x55c12ab096c0] (/opt/godot/./core/templates/local_vector.h:326)
[30] godot.linuxbsd.editor.x86_64(+0xb4c750) [0x55c12aae2750] (/opt/godot/platform/linuxbsd/os_linuxbsd.cpp:878)
[31] godot.linuxbsd.editor.x86_64(+0xb3cdb1) [0x55c12aad2db1] (/opt/godot/platform/linuxbsd/godot_linuxbsd.cpp:75)
[32] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7fac5efe3d0a] (??:0)
[33] godot.linuxbsd.editor.x86_64(+0xb49d2e) [0x55c12aadfd2e] (??:?)
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

1. Create a new blank project
2. Add a single node to the default scene to be able to save it
3. Save the scene on disk
4. Open the `.tscn` file in the script editor
5. Go to `Project` -> `Project Settings` -> `Localization` tab -> `POT Generation` tab
6. Click on the `Add...` button
7. Select the `.tscn` file
8. Click on the `Open` button
9. Click on the `Generate POT` button
10. Give a name for the `.pot` file
11. Click on the `Save` button
12. Notice the crash

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by timothyqiu**
Fixes a crash reported in https://github.com/godotengine/godot/issues/73565#issuecomment-1435763920, closes #76649

`.res` is a valid extension for `PackedScene`, but not all `.res` files are `PackedScene`s. There should be a null check.

---

To reproduce the crash:

1. Save any resource as `.res` and add it to the file list of POT Generation tab.
    - Or use this test project: [pot.zip](https://github.com/user-attachments/files/17157189/pot.zip)
2. Click the Generate POT button and choose a file name. The editor will crash when you click Save.

### CODE REVIEW

File: editor/plugins/packed_scene_translation_parser_plugin.cpp [hunk 1]
```diff
@@ -49,7 +48,9 @@ Error PackedSceneEditorTranslationParserPlugin::parse_file(const String &p_path,
 		ERR_PRINT("Failed to load " + p_path);
 		return err;
 	}
-	Ref<SceneState> state = Ref<PackedScene>(loaded_res)->get_state();
+	Ref<PackedScene> packed_scene = loaded_res;
+	ERR_FAIL_COND_V_MSG(packed_scene.is_null(), ERR_FILE_UNRECOGNIZED, p_path.quote() + " is not a valid PackedScene resource.");
```
Comment (akien-mga) [inline editor/plugins/packed_scene_translation_parser_plugin.cpp:52]:
```suggestion
	ERR_FAIL_COND_V_MSG(packed_scene.is_null(), ERR_FILE_UNRECOGNIZED, vformat("'%s' is not a valid PackedScene resource.", p_path));
```

**Review by akien-mga — APPROVED** [review]
