### PR TITLE
Linux/BSD: Fix support for NetBSD

### LINKED ISSUE #42145: Compilation fails on NetBSD (conflict with system-defined RANDOM_MAX)
**Godot version:**
3.2.2 and 3.2.3

**OS/device including version:**
NetBSD 9 AMD64

**Issue description:**
When I issue the compilation command scons platform=x11 or if I want to compile with llvm: scons platform=x11 use_llvm=yes, they both fail very early.

**Steps to reproduce:**
NetBSD has the proper versions for dependencies and I believe that I have all dependencies satisfied from the package collection for NetBSD, but trying to compile it fails. If I use gcc I get a mix of several very vague errors like one mentioning an expected ';' in one file. If I used llvm I get an expected unqualified-id error. It doesn't matter if use the git, the stable releases for 3.2.2 or 3.2.3, or the port from openbsd. They all fail.

Edit: 
I will admit I was using virtualbox to render NetBSD, but it's been perfect performance so I really don't want to disregard this as a VM issue rather than possible godot issue. 

edit 2: Here are the logs in text form:
```
gcc-
scons: Reading SConscript files ...
Enabling ALSA
Enabling PulseAudio
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...

[Initial build] [94mCompiling [95m==> [93mplatform/x11/godot_x11.cpp[0m
In file included from platform/x11/godot_x11.cpp:33:0:
./core/math/random_pcg.h:70:24: error: expected unqualified-id before numeric constant
  static const uint64_t RANDOM_MAX = 0xFFFFFFFF;
                        ^
./core/math/math_funcs.h:50:24: error: expected unqualified-id before numeric constant
  static const uint64_t RANDOM_MAX = 0xFFFFFFFF;
                        ^
./core/math/math_funcs.h: In static member function 'static double Math::randd()':
./core/math/math_funcs.h:283:80: error: expected unqualified-id before numeric constant
  static _ALWAYS_INLINE_ double randd() { return (double)rand() / (double)Math::RANDOM_MAX; }
                                                                                ^
./core/math/math_funcs.h:283:80: error: expected ';' before numeric constant
In file included from ./core/math/vector2.h:34:0,
                 from ./core/math/rect2.h:34,
                 from ./core/math/transform_2d.h:34,
                 from ./core/os/input_event.h:34,
                 from ./core/os/main_loop.h:34,
                 from ./core/engine.h:35,
                 from ./core/os/os.h:34,
                 from platform/x11/context_gl_x11.h:38,
                 from platform/x11/os_x11.h:34,
                 from platform/x11/godot_x11.cpp:37:
./core/math/math_funcs.h:283:90: warning: statement has no effect [-Wunused-value]
  static _ALWAYS_INLINE_ double randd() { return (double)rand() / (double)Math::RANDOM_MAX; }
                                                                                          ^
In file included from platform/x11/godot_x11.cpp:33:0:
./core/math/math_funcs.h: In static member function 'static float Math::randf()':
./core/math/math_funcs.h:284:77: error: expected unqualified-id before numeric constant
  static _ALWAYS_INLINE_ float randf() { return (float)rand() / (float)Math::RANDOM_MAX; }
                                                                             ^
./core/math/math_funcs.h:284:77: error: expected ';' before numeric constant
In file included from ./core/math/vector2.h:34:0,
                 from ./core/math/rect2.h:34,
                 from ./core/math/transform_2d.h:34,
                 from ./core/os/input_event.h:34,
                 from ./core/os/main_loop.h:34,
                 from ./core/engine.h:35,
                 from ./core/os/os.h:34,
                 from platform/x11/context_gl_x11.h:38,
                 from platform/x11/os_x11.h:34,
                 from platform/x11/godot_x11.cpp:37:
./core/math/math_funcs.h:284:87: warning: statement has no effect [-Wunused-value]
  static _ALWAYS_INLINE_ float randf() { return (float)rand() / (float)Math::RANDOM_MAX; }
                                                                                       ^
scons: *** [platform/x11/godot_x11.x11.tools.64.o] Error 1
scons: building terminated because of errors.

LLVM-
scons: Reading SConscript files ...
Enabling ALSA
Enabling PulseAudio
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...

[Initial build] [94mCompiling [95m==> [93mplatform/x11/godot_x11.cpp[0m
In file included from platform/x11/godot_x11.cpp:37:
In file included from platform/x11/os_x11.h:34:
In file included from platform/x11/context_gl_x11.h:38:
In file included from ./core/os/os.h:34:
In file included from ./core/engine.h:35:
In file included from ./core/os/main_loop.h:34:
In file included from ./core/os/input_event.h:34:
In file included from ./core/math/transform_2d.h:34:
In file included from ./core/math/rect2.h:34:
In file included from ./core/math/vector2.h:34:
In file included from ./core/math/math_funcs.h:35:
[1m./core/math/random_pcg.h:70:24: [0m[0;1;31merror: [0m[1mexpected member name or ';' after
      declaration specifiers[0m
        static const uint64_t RANDOM_MAX = 0xFFFFFFFF;
[0;1;32m        ~~~~~~~~~~~~~~~~~~~~~ ^
[0m[1m/usr/include/stdlib.h:188:20: [0m[0;1;30mnote: [0mexpanded from macro 'RANDOM_MAX'[0m
#define RANDOM_MAX      0x7fffffff      /* (((long)1 << 31) - 1) */
[0;1;32m                        ^
[0mIn file included from platform/x11/godot_x11.cpp:37:
In file included from platform/x11/os_x11.h:34:
In file included from platform/x11/context_gl_x11.h:38:
In file included from ./core/os/os.h:34:
In file included from ./core/engine.h:35:
In file included from ./core/os/main_loop.h:34:
In file included from ./core/os/input_event.h:34:
In file included from ./core/math/transform_2d.h:34:
In file included from ./core/math/rect2.h:34:
In file included from ./core/math/vector2.h:34:
[1m./core/math/math_funcs.h:50:24: [0m[0;1;31merror: [0m[1mexpected member name or ';' after
      declaration specifiers[0m
        static const uint64_t RANDOM_MAX = 0xFFFFFFFF;
[0;1;32m        ~~~~~~~~~~~~~~~~~~~~~ ^
[0m[1m/usr/include/stdlib.h:188:20: [0m[0;1;30mnote: [0mexpanded from macro 'RANDOM_MAX'[0m
#define RANDOM_MAX      0x7fffffff      /* (((long)1 << 31) - 1) */
[0;1;32m                        ^
[0mIn file included from platform/x11/godot_x11.cpp:37:
In file included from platform/x11/os_x11.h:34:
In file included from platform/x11/context_gl_x11.h:38:
In file included from ./core/os/os.h:34:
In file included from ./core/engine.h:35:
In file included from ./core/os/main_loop.h:34:
In file included from ./core/os/input_event.h:34:
In file included from ./core/math/transform_2d.h:34:
In file included from ./core/math/rect2.h:34:
In file included from ./core/math/vector2.h:34:
[1m./core/math/math_funcs.h:283:80: [0m[0;1;31merror: [0m[1mexpected unqualified-id[0m
  ...double randd() { return (double)rand() / (double)Math::RANDOM_MAX; }
[0;1;32m                                                            ^
[0m[1m/usr/include/stdlib.h:188:20: [0m[0;1;30mnote: [0mexpanded from macro 'RANDOM_MAX'[0m
#define RANDOM_MAX      0x7fffffff      /* (((long)1 << 31) - 1) */
[0;1;32m                        ^
[0mIn file included from platform/x11/godot_x11.cpp:37:
In file included from platform/x11/os_x11.h:34:
In file included from platform/x11/context_gl_x11.h:38:
In file included from ./core/os/os.h:34:
In file included from ./core/engine.h:35:
In file included from ./core/os/main_loop.h:34:
In file included from ./core/os/input_event.h:34:
In file included from ./core/math/transform_2d.h:34:
In file included from ./core/math/rect2.h:34:
In file included from ./core/math/vector2.h:34:
[1m./core/math/math_funcs.h:284:77: [0m[0;1;31merror: [0m[1mexpected unqualified-id[0m
  ...float randf() { return (float)rand() / (float)Math::RANDOM_MAX; }
[0;1;32m                                                         ^
[0m[1m/usr/include/stdlib.h:188:20: [0m[0;1;30mnote: [0mexpanded from macro 'RANDOM_MAX'[0m
#define RANDOM_MAX      0x7fffffff      /* (((long)1 << 31) - 1) */
[0;1;32m                        ^
[0m4 errors generated.
scons: *** [platform/x11/godot_x11.x11.tools.64.llvm.o] Error 1
scons: building terminated because of errors.
```
It's not perfect, but it's better than the screenshot form I previously had.

### PR DESCRIPTION
**Pull request by akien-mga**
Add __NetBSD__ to `platform_config.h` so that it can find `alloca`
and use the proper `pthread_setname_np` format.

Rename RANDOM_MAX to avoid conflict with NetBSD stdlib.

Fixes #42145.

@notepade Can you check if this works for you, and if there are other issues?

---

NetBSD: Implement OS_Unix::get_executable_path()

Same implementation as OpenBSD seems to work fine.

---

X11: Try to load libXrandr.so.3 if libXrandr.so.2 isn't found

All Linux distros, and FreeBSD and OpenBSD seem to have libXrandr.so.2,
but for some reason recent NetBSD versions seem to have libXrandr.so.3 now.

### CODE REVIEW

File: core/math/math_funcs.h [hunk 1]
```diff
@@ -46,7 +46,8 @@ class Math {
 public:
 	Math() {} // useless to instance
 
-	static const uint64_t RANDOM_MAX = 0xFFFFFFFF;
+	// Not using 'RANDOM_MAX' to avoid conflict with system headers on some OSes (at least NetBSD).
+	static const uint64_t RANDOM_UINT32_MAX = 0xFFFFFFFF;
```
Comment (aaronfranke) [inline core/math/math_funcs.h:50]: > `UINT32`

> `uint64_t`

Hmm...

Comment (akien-mga) [reply core/math/math_funcs.h:50]: It's the max value of a 32-bit unsigned integer, stored in `uint64_t`. Is there a problem?

Comment (aaronfranke) [reply core/math/math_funcs.h:50]: Is there a particular reason this shouldn't be either `uint32_t` or `0xFFFFFFFFFFFFFFFF`?

Anyway, the name seems a bit strange and some may mistake it for Hungarian notation. Maybe `RANDOM_32BIT_MAX` would be clearer?

Comment (akien-mga) [reply core/math/math_funcs.h:50]: > Is there a particular reason this shouldn't be either `uint32_t` or `0xFFFFFFFFFFFFFFFF`?

No idea.

> Anyway, the name seems a bit strange and some may mistake it for Hungarian notation. Maybe `RANDOM_32BIT_MAX` would be clearer?

Sounds fine.

**Comment by akien-mga** [comment]
There are more fixes needed for NetBSD support, marking as WIP for now.

**Comment by akien-mga** [comment]
Cherry-picked version for `3.2` (which I'm using for testing for now): https://github.com/akien-mga/godot/tree/3.2-netbsd

**Comment by akien-mga** [comment]
The first commit solves the compilation errors (#42145).

The other two commits solve runtime errors about missing libXrandr.so.2 (for some reason NetBSD has libXrandr.so.3) and unimplemented `OS::get_executable_path()` (the OpenBSD code seems to work fine for NetBSD too).

So here's Dodge the Creeps running on NetBSD 9.0 in VirtualBox with the llvmpipe software rasterizer.
(Don't mind the cropped window, I couldn't get VBox additions to work so I'm stuck with 800x600.)

Screenshot_20200918_120316

**Comment by akien-mga** [comment]
For the reference, I'm pushing this to `master`, but the current `master` branch can't be built on NetBSD with those changes yet, as the vendored vulkan-loader library doesn't support it.

There's a WIP NetBSD package for vulkan-loader which could likely be used instead of the vendored lib once it's ready for production: https://pkgsrc.se/wip/vulkan-loader

But that's not a priority for me at this point, we can revisit this later when there's out-of-the-box Vulkan support in NetBSD. (I haven't checked if there are any GPU drivers with Vulkan support for NetBSD currently.)

The `3.2` version of this PR does make Godot 3.2.3+ functional on NetBSD: https://github.com/akien-mga/godot/tree/3.2-netbsd

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Comment by notepade** [comment]
> For the reference, I'm pushing this to `master`, but the current `master` branch can't be built on NetBSD with those changes yet, as the vendored vulkan-loader library doesn't support it.
> 
> There's a WIP NetBSD package for vulkan-loader which could likely be used instead of the vendored lib once it's ready for production: https://pkgsrc.se/wip/vulkan-loader
> 
> But that's not a priority for me at this point, we can revisit this later when there's out-of-the-box Vulkan support in NetBSD. (I haven't checked if there are any GPU drivers with Vulkan support for NetBSD currently.)
> 
> The `3.2` version of this PR does make Godot 3.2.3+ functional on NetBSD: https://github.com/akien-mga/godot/tree/3.2-netbsd

I'm a bit confused what you mean by all this. You're saying that it won't be compilable on NetBSD even if you pushed that pull request?

**Comment by akien-mga** [comment]
The latest `3.2` branch can be compiled on NetBSD now. The `master` branch can up to a certain point where it fails due to the lack of Vulkan support, which is beyond the scope of this PR.

**Comment by niacat** [comment]
Can libXrandr be loaded unversioned? The library will have a different version number on NetBSD depending on the way X11 is installed, libXrandr.so.3 if the base system's X11 sets are installed, libXrandr.so.2 if installed as modular X11 through the packaging system.

**Comment by akien-mga** [comment]
> Can libXrandr be loaded unversioned? 

No, because unversioned library symlinks (`libXrandr.so`) are part of devel packages on Linux, and not installed for most regular users.

One thing that could be looked into though is using Xrandr directly without dlopen'ing it, as we seem to link it anyway for other code. This dlopen maybe dates back to before we had a build dependency on Xrandr.

**Comment by niacat** [comment]
Ah, OK. On every BSD there is no concept of separation of dev packages, so it should be fine to attempt to load the version provided by upstream Xorg (libXrandr.so.2), then fall back to unversioned.

The history of this is apparently that we were previously including XFree86 as part of the OS, then as part of the switchover to X.org a decade ago every library got its version bumped. So, I think it's very unlikely the version number will change in the future and am not too worried.
