### PR TITLE
Fix embedding failing intermittently

### LINKED ISSUE #101068: Race Condition in `EmbeddedProcess::_try_embed_process`
### Tested versions

4.4-dev7

### System information

Godot v4.4.dev (f2d97462a) - Windows 11 (build 26100) - Multi-window, 2 monitors - Direct3D 12 (Forward+) - dedicated NVIDIA GeForce RTX 4080 (NVIDIA; 32.0.15.6614) - Intel(R) Core(TM) i9-14900K (32 threads)

### Issue description

There seems to be a race condition somewhere when embedding the game. When running things normally the Game tab shows nothing around 80% of the time. Resizing and none of the buttons in the game tab change anything. If I put a break point on https://github.com/godotengine/godot/blob/bdf625bd54958c737fa6b7213b07581cc91059ad/editor/plugins/embedded_process.cpp#L189 and wait a bit the window gets correctly shown all the time. One other thing I noticed was that if I put godot on my second monitor and launched the game it would show the game on my primary monitor where it should be drawn when it would have been embedded in the editor when the embedding "fails".

I wasn't able to narrow this down further yet but the error branches are never entered even if the Game tab does not display anything. 

### Steps to reproduce

- enable "Embed Game on Next Play"
- hit play

### Minimal reproduction project (MRP)

-

### PR DESCRIPTION
**Pull request by Hilderin**
- Fixes #101068

There was a problem in the logic to find the correct window handle for the embedded process.

Also fixed the conditions to hide the embedded window if it's too small. Since the minimum size of the embedded window is 100x100, the conditions `< 100` were never true.

Tested by @0x0ACB, see comments in the issue.

### CODE REVIEW

File: platform/windows/display_server_windows.cpp [hunk 1]
```diff
@@ -2876,10 +2876,11 @@ static BOOL CALLBACK _enum_proc_find_window_from_process_id_callback(HWND hWnd,
...
-			const DWORD style = GetWindowLongPtr(hWnd, GWL_STYLE);
-			if ((style & WS_VISIBLE) != WS_VISIBLE) {
-				return TRUE;
-			}
+			return TRUE;
+		}
+		const DWORD style = GetWindowLongPtr(hWnd, GWL_STYLE);
+		if ((style & WS_VISIBLE) != WS_VISIBLE) {
+			return TRUE;
 		}
```
Comment (bruvzg) [inline platform/windows/display_server_windows.cpp:2884]: Is this condition necessary? When using floating window, it causes incorrectly sized embedded window showing up during startup. If it's removed, everything seems to be working smoothly.

Screenshot 2025-01-06 113647

Comment (Hilderin) [reply platform/windows/display_server_windows.cpp]: Nice catch. No it's really not usefull on the contrary. I removed it. Thanks.

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
