### PR TITLE
Fix Android LineEdit editing bugs

### LINKED ISSUE #27065: LineEdit copies chunks of text erratically on Android
**Godot version:**
3.1 stable

**OS/device including version:**
Asus Zenfone Max Plus (Android 7)
Xiaomi Pocophophone F1 (Android 9)

**Issue description:**
If you move the caret to the middle of the text, when you type the keyboard copies a section of the text.

If you type

`aaaaabbbbcccc|`

, move the caret inbetween the `a` and `b`

`aaaaa|bbbbcccc`

and type `d`, you get

`aaaaabbbbccccd|bbbbcccc`

instead of the expected

`aaaaad|bbbbcccc`

I suspect this has to do with synchronizing the virtual keyboard's buffer.

**Steps to reproduce:**
- Create a LineEdit
- Export to Android
- Type some text as explained above

**Minimal reproduction project:**
(This MRP is literally just a LineEdit in an otherwise empty scene.)
[MRP.zip](https://github.com/godotengine/godot/files/2968261/MRP.zip)

### LINKED ISSUE #38158: LineEdit behaves erratically when a zone of text is replaced and backspace is used
**Godot version:**
3.2 c7ad8f539b52dfe7a76a7051505a9891f98e46d6

**OS/device including version:**
Android 9, Huawei

**Issue description:**
When a zone of text is selected and replaced in LineEdit, delete operations afterwards will behave in a buggy way, randomly replacing and adding characters.

Related to #27065 , but as far as I know it's not caused by the same bug.

**Steps to reproduce:**
1. Create an empty project, add Node2D and LineEdit.
2. Export to Android.
3. Type a line in LineEdit on Android, for example "A very good game"
4. Select a zone of text, for example the last 3 characters "ame"
5. Replace the selected text with any character or backspace.
6. Continue using backspace after that. It will delete and add random characters in the same time.

### PR DESCRIPTION
**Pull request by SkyLucilfer**
Supersedes #38104

Fixes #27065 
Fixes #38158 

- The first bug is solved by sending cursor_pos in LineEdit to the Android Java side, so that we consider only text until that cursor position. #38104 contains more explanation.

- The second bug is solved by sending selection.begin and selection.end to the Android Java side, so that text selection in LineEdit is taken into account.

There are still some problems with updates in [GodotEditText.java](https://github.com/godotengine/godot/blob/master/platform/android/java/lib/src/org/godotengine/godot/input/GodotEditText.java) and [GodotTextInputWrapper.java](https://github.com/godotengine/godot/blob/master/platform/android/java/lib/src/org/godotengine/godot/input/GodotTextInputWrapper.java) that I found during testing in some cases. Sometimes `edit.setText("");` doesn't set the text, sometimes the pCharSequence in beforeTextChanged() gets out of synced, and I believe InputFilter sometimes doesn't get set too. 
However during my tests this only happens when we have reached max length in LineEdit and we keep typing randomly, or when we spam clicking too fast on the LineEdit. I tried a few things but I couldn't solve this.

### CODE REVIEW

File: platform/android/java/lib/src/org/godotengine/godot/GodotIO.java [hunk 1]
```diff
@@ -489,9 +489,9 @@ public int getScreenDPI() {
 		return (int)(metrics.density * 160f);
 	}
 
-	public void showKeyboard(String p_existing_text, int p_max_input_length) {
+	public void showKeyboard(String p_existing_text, int p_max_input_length, int cursor_start, int cursor_end) {
```
Comment (akien-mga) [inline platform/android/java/lib/src/org/godotengine/godot/GodotIO.java:492]: Parameters should start with `p_` (like the other two)

**Comment by akien-mga** [comment]
CC @m4gr3d @pouleyKetchoupp

**Comment by pouleyKetchoupp** [comment]
Nice work! It looks like a good improvement on the existing system.

I was able to consistently reproduce a bug which could be the one you mentioned, and I'm not sure if it should be considered as a separate issue or if there's a problem with this new code in `GodotEditText::showKeyboard`, so I think it would be worth checking with prints or something.

Here are my repro steps:
- Make a LineEdit with max length 5
- Type "Abcde"
- Touch in the middle to move the cursor between 'c' and 'd'
- Touch at the end to move the cursor back to the end
- Type "ff", it shouldn't allow adding more letters but the result is "Abcff"

**Comment by SkyLucilfer** [comment]
@pouleyKetchoupp Thank you very much for taking the time to test the code !!

The problem that you reproduced was due to the same bug that I mentioned - `edit.setText("")` doesn't reset EditText back to "abced".

After some more testing, I finally found out that it was due to [setMaxInputLength()](https://github.com/godotengine/godot/blob/d29514accef09ba0402cdbb87ec5f5e773a48bbc/platform/android/java/lib/src/org/godotengine/godot/input/GodotEditText.java#L108) not being placed at the right location. 
When we move cursor back to the end, the InputFilter in the EditText is still the InputFilter we used from last time. Hence it prevents us from setting the new text properly, and causing all the other problems afterwards.

Setting `setMaxInputLength()` at the right place will normally solve all of the problems I mentioned in the PR description. 

I still notice some problems with InputFilter. I will push another PR soon.

File: platform/android/java/lib/src/org/godotengine/godot/input/GodotEditText.java [hunk 2]
```diff
@@ -122,14 +127,10 @@ private void handleMessage(final Message msg) {
 		}
 	}
```
Comment (SkyLucilfer) [inline platform/android/java/lib/src/org/godotengine/godot/input/GodotEditText.java:129]: I removed the conditional here because this time, if mMaxInputLength == 0, we really want the user to not be able to insert anymore character. 
mMaxInputLength == 0 happens when we reach max length in LineEdit, and we move the cursor to the frontmost position of the text.

File: platform/android/java/lib/src/org/godotengine/godot/input/GodotEditText.java [hunk 3]
```diff
@@ -122,14 +127,10 @@ private void handleMessage(final Message msg) {
...
 
-	private void setMaxInputLength(EditText p_edit_text, int p_max_input_length) {
-		if (p_max_input_length > 0) {
```
Comment (SkyLucilfer) [inline platform/android/java/lib/src/org/godotengine/godot/input/GodotEditText.java:126]: I removed the conditional here because this time, if mMaxInputLength == 0, we really want the user to not be able to insert anymore character.
mMaxInputLength == 0 happens when we reach max length in LineEdit, and we move the cursor to the frontmost position of the text.

**Comment by SkyLucilfer** [comment]
**TDLR : The LineEdit should be working fine now.**

===

There's still one last minor problem with the virtual keyboard. 

In the following scenarios, after reaching max length on LineEdit, we will still be able to continue typing on the virtual keyboard (but the LineEdit is not affected) : 
- after a space. For example, "Ab |cde"
- at the start of the line. "|Ab cde"
- inserting words with virtual keyboard suggestions at the furthest end of the text

As far as I know, [TextWatcher](https://github.com/godotengine/godot/blob/ad28d41a21e72c899aa3f6176d3504d0ea415c64/platform/android/java/lib/src/org/godotengine/godot/input/GodotTextInputWrapper.java#L42) is not triggered when we type on the vk in these scenarios. I couldn't find out why. And I think because of this, the InputFilter doesn't filter the text on the vk in these cases.

Other than that, the LineEdit should be working well now.

**Comment by pouleyKetchoupp** [comment]
Good job! This looks fine to me.

For the remaining issue with spaces and suggestions, it seems it's a general problem with the way the length filter works. We might be better off implementing it ourselves in the text watcher, as suggested here:
https://stackoverflow.com/questions/48869190/android-edittext-length-filter-not-working-as-it-should

Would you mind opening a new issue with your repro cases? I think this PR is already a great improvement but we'll have to solve these other problems eventually.

File: platform/android/java/lib/src/org/godotengine/godot/input/GodotEditText.java [hunk 4]
```diff
@@ -101,11 +102,17 @@ private void handleMessage(final Message msg) {
...
 				if (edit.requestFocus()) {
 					edit.removeTextChangedListener(edit.mInputWrapper);
+					setMaxInputLength(edit);
 					edit.setText("");
 					edit.append(text);
+					if (msg.arg2 != -1) {
+						edit.setSelection(msg.arg1, msg.arg2);
+						edit.mInputWrapper.setSelection(true);
+					} else
+						edit.mInputWrapper.setSelection(false);
```
Comment (akien-mga) [inline platform/android/java/lib/src/org/godotengine/godot/input/GodotEditText.java:112]:
```suggestion
					} else {
						edit.mInputWrapper.setSelection(false);
					}
```

File: scene/gui/line_edit.cpp [hunk 5]
```diff
@@ -127,8 +127,12 @@ void LineEdit::_gui_input(Ref<InputEvent> p_event) {
 			selection.creating = false;
 			selection.doubleclick = false;
 
-			if (DisplayServer::get_singleton()->has_feature(DisplayServer::FEATURE_VIRTUAL_KEYBOARD))
-				DisplayServer::get_singleton()->virtual_keyboard_show(text, get_global_rect(), max_length);
+			if (DisplayServer::get_singleton()->has_feature(DisplayServer::FEATURE_VIRTUAL_KEYBOARD)) {
+				if (selection.enabled)
+					DisplayServer::get_singleton()->virtual_keyboard_show(text, get_global_rect(), max_length, selection.begin, selection.end);
+				else
+					DisplayServer::get_singleton()->virtual_keyboard_show(text, get_global_rect(), max_length, cursor_pos);
```
Comment (akien-mga) [inline scene/gui/line_edit.cpp:134]:
```suggestion
				if (selection.enabled) {
					DisplayServer::get_singleton()->virtual_keyboard_show(text, get_global_rect(), max_length, selection.begin, selection.end);
				} else {
					DisplayServer::get_singleton()->virtual_keyboard_show(text, get_global_rect(), max_length, cursor_pos);
				}
```

File: scene/gui/line_edit.cpp [hunk 6]
```diff
@@ -933,8 +937,12 @@ void LineEdit::_notification(int p_what) {
 				DisplayServer::get_singleton()->window_set_ime_position(get_global_position() + cursor_pos, get_viewport()->get_window_id());
 			}
 
-			if (DisplayServer::get_singleton()->has_feature(DisplayServer::FEATURE_VIRTUAL_KEYBOARD))
-				DisplayServer::get_singleton()->virtual_keyboard_show(text, get_global_rect(), max_length);
+			if (DisplayServer::get_singleton()->has_feature(DisplayServer::FEATURE_VIRTUAL_KEYBOARD)) {
+				if (selection.enabled)
+					DisplayServer::get_singleton()->virtual_keyboard_show(text, get_global_rect(), max_length, selection.begin, selection.end);
+				else
+					DisplayServer::get_singleton()->virtual_keyboard_show(text, get_global_rect(), max_length, cursor_pos);
```
Comment (akien-mga) [inline scene/gui/line_edit.cpp:944]:
```suggestion
				if (selection.enabled) {
					DisplayServer::get_singleton()->virtual_keyboard_show(text, get_global_rect(), max_length, selection.begin, selection.end);
				} else {
					DisplayServer::get_singleton()->virtual_keyboard_show(text, get_global_rect(), max_length, cursor_pos);
				}
```

File: platform/android/java/lib/src/org/godotengine/godot/input/GodotEditText.java [hunk 7]
```diff
@@ -161,13 +164,25 @@ public boolean onKeyDown(final int keyCode, final KeyEvent keyEvent) {
 	// ===========================================================
 	// Methods
 	// ===========================================================
-	public void showKeyboard(String p_existing_text, int p_max_input_length) {
-		mOriginText = p_existing_text;
+	public void showKeyboard(String p_existing_text, int p_max_input_length, int p_cursor_start, int p_cursor_end) {
+
```
Comment (akien-mga) [inline platform/android/java/lib/src/org/godotengine/godot/input/GodotEditText.java:168]: Remove the empty line at the start of the block (`clang-format` should now do it automatically).

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

It's in #38832 as 2197ef05662913d81df5846516930c3c47739001, I did my best to resolve conflicts but I didn't test the Android build/export, so I'd welcome some testing to ensure that it's working as intended.

**Comment by SkyLucilfer** [comment]
@akien-mga I will test it sometime around tommorow or Friday.

**Comment by ondesic** [comment]
It should be noted that this same problem occurs with the TextEdit and needs to be fixed as well.

**Comment by ondesic** [comment]
Can this fix for the LineEdit be applied to the TextEdit please?  In 3.2.4 beta 4 this same bug still exists.

**Comment by pouleyKetchoupp** [comment]
> 
> 
> Can this fix for the LineEdit be applied to the TextEdit please? In 3.2.4 beta 4 this same bug still exists.

The same fix was done for TextEdit in #43560, it will be part of the next beta.

**Comment by ondesic** [comment]
I can confirm that this bug still exists in the TextEdit node in 3.3 RC7.

**Comment by akien-mga** [comment]
Please open a dedicated bug report then, this PR is merged, cherry-picked, and related to another node.
