### PR TITLE
Fix docks grabbing too much focus

### LINKED ISSUE #114232: Renaming TileMapLayer node requires three clicks
### Tested versions

v4.6.beta2.official [551ce8d47]
4.6 beta 1

### System information

win10

### Issue description

Renaming a TileMapLayer node requires three clicks, whereas normally only two are needed.

This does not happen with other nodes such as Sprite2D.
This also seems to happen in 4.5.1, but with less frequency.

### Steps to reproduce

Steps to reproduce:

Add a TileMapLayer node and a Sprite2D node.

Try renaming both nodes by double-clicking on their names.

You will notice that two clicks are not enough to rename the TileMapLayer node, while it works correctly with the Sprite2D node.

### Minimal reproduction project (MRP)

...

### PR DESCRIPTION
**Pull request by lodetrick**
Fixes #114232
Dock counterpart to #114241 for #113898
Related https://chat.godotengine.org/channel/editor?msg=7moZ6boxcxmAqha7s

This PR fixes the docks stealing focus when nodes like `TileMapLayer` and `AnimationPlayer` are selected. Note that this is a regression from 4.5 because previously the bottom docks didn't take focus when made visible.

I considered modifying the `focus_dock` method, but this was the only use case of that method that didn't make sense to me, so instead this PR introduces a fix for the `open_dock` method. The reason why `focus_dock` was chosen for `EditorDock::make_visible` was because `open_dock` wouldn't do anything with already open docks (while `focus_dock` would actively make the dock visible). This PR fixes that issue with `open_dock` by selecting the correct tab but not taking focus.

### CODE REVIEW

File: editor/docks/editor_dock_manager.cpp [hunk 1]
```diff
@@ -844,6 +844,19 @@ void EditorDockManager::open_dock(EditorDock *p_dock, bool p_set_current) {
 	ERR_FAIL_COND_MSG(!all_docks.has(p_dock), vformat("Cannot open unknown dock '%s'.", p_dock->get_display_title()));
 
 	if (p_dock->is_open) {
+		// Set tab to current if not open.
```
Comment (KoBeWi) [inline editor/docks/editor_dock_manager.cpp]: Misleading comment, the dock _is_ open.

**Review by KoBeWi — APPROVED** [review]
This makes the usefulness of having both `open()` and `make_visible()` questionable. Not sure if there is a use-case for _focusing_ a dock tab?
It works as a fix though.

**Comment by lodetrick** [comment]
It might be worth to combine the two while we have the chance in beta, make it `EditorDock::open(bool make_visible = true)` Just because of the similarity and how behind the scenes they are now calling the same function.

As far as I can tell there is only a single reference to `EditorDock::open` in source (which is in the BottomPanel for compatibility)

As to the use-case of focusing a dock tab, there currently is several cases when for example the game is run and focus is sent to the debugger or output docks, which makes sense as now the user wants to interact with those areas. Essentially focus currently is grabbed when the user presses a button to open the dock (rather than it happen contextually)
