### PR TITLE
Fix Steam input "crc" errors, and some other Coverity reports of uninitialized scalar variable

### LINKED ISSUE #88630: [Steam] [Linux] XBox Series X controller shows CRC errors
### Tested versions

- Reproducible in v4.2.1.stable.official [b09f793f5]
- Official website version does not show the error (same commit id), it only appears in Steam.

### System information

Godot v4.2.1.stable - Fedora Linux 39 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XTX (RADV NAVI31) () - AMD Ryzen 9 7950X 16-Core Processor (32 Threads)

### Issue description

When launching game from editor, I get the following errors:
```log
E 0:00:00:0016   parse_mapping: Unrecognized input string "dc18" in mapping:
050000005e040000130b000015050000,Xbox Series X Controller,a:b0,b:b1,x:b3,y:b4,back:b10,guide:b12,start:b11,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,misc1:b15,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a5,righttrigger:a4,crc:dc18,platform:Linux,
  <C++ Error>    Condition "true" is true. Continuing.
  <C++ Source>   core/input/input.cpp:1493 @ parse_mapping()
```
```log
E 0:00:00:0016   parse_mapping: Unrecognized input string "f003" in mapping:
050000005e0400008e02000030110000,Xbox 360 Controller,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b8,start:b7,leftstick:b9,rightstick:b10,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,misc1:b15,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,crc:f003,platform:Linux,
  <C++ Error>    Condition "true" is true. Continuing.
  <C++ Source>   core/input/input.cpp:1493 @ parse_mapping()
```
```log
E 0:00:00:0016   parse_mapping: Unrecognized input string "9d50" in mapping:
030000005e040000120b00000f050000,Xbox Series X Controller,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b8,start:b7,leftstick:b9,rightstick:b10,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,misc1:b11,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,crc:9d50,platform:Linux,
  <C++ Error>    Condition "true" is true. Continuing.
  <C++ Source>   core/input/input.cpp:1493 @ parse_mapping()
```

Notice these are not blocking errors, the game runs all the same in steam and non steam versions.

Also, I thought it might've been the `xpad` or `hid_microsoft` kernel modules, but doing `modprobe -r` on bothh doesn't seem to fix the issue.

### Steps to reproduce

1. Connect a XBox Series X controller
2. Launch a scene in Steam Godot

### Minimal reproduction project (MRP)

It happens with a clean new project and a series X controller. It happens even when it's disconnected, too.

### LINKED ISSUE #92578: Parse_mapping error on Steam version only
### Tested versions

Reproducible in 4.2.2 Steam version only

### System information

Godot v4.2.2.stable - Ubuntu 22.04.3 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 Ti (nvidia; 535.171.04) - Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 Threads)

### Issue description

The Steam version of Godot's gives the following error when pressing the play button to play the game:

image

E 0:00:00:0034   parse_mapping: Unrecognized input string "d95e" in mapping:
03000000010000000100000001000000,input-remapper gamepad,a:b0,b:b1,x:b3,y:b4,back:b10,guide:b12,start:b11,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,crc:d95e,platform:Linux,
  <C++ Error>    Condition "true" is true. Continuing.
  <C++ Source>   core/input/input.cpp:1494 @ parse_mapping()

The 4.2.2 version in the website does not give the error. My guess is that this is something to do with the Steam controller inputs that Steam automatically injects in games. The error persists even if on Steam you choose "Disable Steam Input" under controller.

### Steps to reproduce

- Open up Godot's Steam version
- Create a Node2D scene
- Press the play button, set the created Node2D scene as main scene
- Error will be shown in the debugger

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by akien-mga**
Going through a few reports on https://scan.coverity.com/projects/godotengine-godot?tab=overview

Lots of low hanging fruits there to improve the code quality and find potential bugs.

The input mapping change fixes these issues:
- Fixes #88630
- Fixes #92578

### CODE REVIEW

File: drivers/gles3/storage/light_storage.h [hunk 1]
```diff
@@ -141,7 +141,7 @@ struct ReflectionAtlas {
 	int size = 0;
 
 	int mipmap_count = 1; // number of mips, including original
-	int mipmap_size[8];
+	int mipmap_size[8] = {};
```
Comment (akien-mga) [inline drivers/gles3/storage/light_storage.h:144]: Fixes this:
image

CC @clayjohn @BastiaanOlij 

There's a bunch more issues with uninitialized stuff in rendering code, would be good for the rendering team to make a pass on the reports and decide whether to init all the structs properly, or what other approach to take. We've had a number of bugs on some platforms/GPUs due to uninitialized struct members.

File: drivers/gles3/rasterizer_gles3.cpp [hunk 2]
```diff
@@ -152,6 +149,8 @@ static void GLAPIENTRY _gl_debug_print(GLenum source, GLenum type, GLuint id, GL
 		strcpy(debSource, "Application");
 	} else if (source == _EXT_DEBUG_SOURCE_OTHER_ARB) {
 		strcpy(debSource, "Other");
+	} else {
+		ERR_FAIL_MSG(vformat("GL ERROR: Invalid or unhandled source '%d' in debug callback.", source));
```
Comment (akien-mga) [inline drivers/gles3/rasterizer_gles3.cpp:153]: These fix these errors:
image

CC @lawnjelly

File: drivers/gles3/rasterizer_gles3.cpp [hunk 3]
```diff
@@ -162,10 +161,8 @@ static void GLAPIENTRY _gl_debug_print(GLenum source, GLenum type, GLuint id, GL
 		strcpy(debType, "Undefined behavior");
 	} else if (type == _EXT_DEBUG_TYPE_PORTABILITY_ARB) {
 		strcpy(debType, "Portability");
-	} else if (type == _EXT_DEBUG_TYPE_PERFORMANCE_ARB) {
-		strcpy(debType, "Performance");
-	} else if (type == _EXT_DEBUG_TYPE_OTHER_ARB) {
-		strcpy(debType, "Other");
```
Comment (akien-mga) [inline drivers/gles3/rasterizer_gles3.cpp:168]: Removed as the early return makes it dead code.

File: modules/gdscript/language_server/godot_lsp.h [hunk 4]
```diff
@@ -236,7 +236,7 @@ struct ReferenceContext {
 	/**
 	 * Include the declaration of the current symbol.
 	 */
-	bool includeDeclaration;
+	bool includeDeclaration = false;
```
Comment (akien-mga) [inline modules/gdscript/language_server/godot_lsp.h:239]: Fixes this:
image

But this is actually never set anywhere, so the code where it was being used is bogus.

It was added in #80973, CC @ryanabx.

File: scene/resources/2d/tile_set.h [hunk 5]
```diff
@@ -265,8 +265,8 @@ class TileSet : public Resource {
 	class TerrainsPattern {
 		bool valid = false;
 		int terrain = -1;
-		int bits[TileSet::CELL_NEIGHBOR_MAX];
-		bool is_valid_bit[TileSet::CELL_NEIGHBOR_MAX];
+		int bits[TileSet::CELL_NEIGHBOR_MAX] = {};
+		bool is_valid_bit[TileSet::CELL_NEIGHBOR_MAX] = {};
```
Comment (akien-mga) [inline scene/resources/2d/tile_set.h:269]: Fixes this:
image

CC @groud

File: core/input/input.cpp [hunk 6]
```diff
@@ -1495,6 +1495,7 @@ void Input::parse_mapping(const String &p_mapping) {
 		JoyAxis output_axis = _get_output_axis(output);
 		if (output_button == JoyButton::INVALID && output_axis == JoyAxis::INVALID) {
 			print_verbose(vformat("Unrecognized output string \"%s\" in mapping:\n%s", output, p_mapping));
+			continue;
```
Comment (akien-mga) [inline core/input/input.cpp:1498]: This fixes what I reported here: https://github.com/godotengine/godot/pull/73224#discussion_r1587356111

image

CC @rsubtil

File: drivers/gles3/rasterizer_canvas_gles3.h [hunk 7]
```diff
@@ -108,8 +108,8 @@ class RasterizerCanvasGLES3 : public RendererCanvasRender {
 		RID texture;
 		struct {
 			bool enabled = false;
-			float z_far;
-			float y_offset;
+			float z_far = 0.0;
+			float y_offset = 0.0;
```
Comment (akien-mga) [inline drivers/gles3/rasterizer_canvas_gles3.h:112]: image

CC @clayjohn @BastiaanOlij

File: thirdparty/enet/enet/godot.h [hunk 8]
```diff
@@ -72,9 +72,9 @@ typedef void ENetSocketSet;
 
 typedef struct _ENetAddress
 {
-   uint8_t host[16];
-   uint16_t port;
-   uint8_t wildcard;
+   uint8_t host[16] = {};
+   uint16_t port = 0;
+   uint8_t wildcard = 0;
```
Comment (akien-mga) [inline thirdparty/enet/enet/godot.h:77]: image

CC @Faless

File: editor/debugger/debug_adapter/debug_adapter_types.h [hunk 9]
```diff
@@ -190,8 +190,8 @@ struct Message {
 struct Scope {
 	String name;
 	String presentationHint;
-	int variablesReference;
-	bool expensive;
+	int variablesReference = 0;
+	bool expensive = false;
```
Comment (akien-mga) [inline editor/debugger/debug_adapter/debug_adapter_types.h:194]: Fixes this type of errors:
image

CC @rsubtil

File: thirdparty/enet/enet/godot.h (hunk 8 above)
Comment (akien-mga) [reply thirdparty/enet/enet/godot.h]: This is C code so my fix was invalid, would need a different approach. Removed from this PR for now.

File: drivers/gles3/rasterizer_gles3.cpp (hunk 2 above)
Comment (lawnjelly) [reply drivers/gles3/rasterizer_gles3.cpp:153]: Although I'm in the blame this is because I'm registered as initial author for 4.x, but this was copy pasted from 3.x GLES2, which is karrofel it looks like.

But fix looks fine to me. :+1:

File: core/input/input.cpp (hunk 6 above)
Comment (rsubtil) [reply core/input/input.cpp:1498]: Yes, it makes sense, I didn't notice that detail when changing the error message to a warning :+1:

File: editor/debugger/debug_adapter/debug_adapter_types.h (hunk 9 above)
Comment (rsubtil) [reply editor/debugger/debug_adapter/debug_adapter_types.h:194]: Good catch, `expensive` ended up never being set in the code, so this was actually causing undefined behavior.

I can confirm it should be `false` as AFAIK Godot still doesn't support partial/pagination behavior to requesting variables from stack dumps, so there's no point in hinting such behavior to DAP when Godot will already have all that information.

File: editor/debugger/debug_adapter/debug_adapter_types.h [hunk 10]
```diff
@@ -169,10 +169,10 @@ struct Capabilities {
 };
 
 struct Message {
-	int id;
+	int id = 0;
 	String format;
-	bool sendTelemetry = false; // Just in case :)
-	bool showUser;
+	bool sendTelemetry = false;
```
Comment (rsubtil) [inline editor/debugger/debug_adapter/debug_adapter_types.h:174]: There goes my little easter egg :sweat_smile:

File: drivers/gles3/rasterizer_canvas_gles3.h (hunk 7 above)
Comment (akien-mga) [reply drivers/gles3/rasterizer_canvas_gles3.h]: I removed these changes from the PR for now.

File: editor/debugger/debug_adapter/debug_adapter_types.h (hunk 10 above)
Comment (akien-mga) [reply editor/debugger/debug_adapter/debug_adapter_types.h]: Brought it back ;)

File: core/input/input.cpp (hunk 6 above)
Comment (akien-mga) [reply core/input/input.cpp:1507]: I believe this should also fix these issues:
- #88630
- #92578
