### PR TITLE
Fix `AudioListener3D` not tracking velocity for doppler

### LINKED ISSUE #107799: Doppler effect calculation only takes `AudioStreamPlayer3D` velocity into account, not `AudioListener3D`
### Tested versions

Found in 4.5
Happens in 4.4

### System information

Windows 10

### Issue description

When calculating doppler effect pitch, only the velocity of the `AudioStreamPlayer3D` is taken into account, even though both players and listeners should have their velocities used for the calculation. Because of this, if doppler is desired on stationary objects while the listener zooms by, such as in a racing/flight game, no doppler effect will be heard. In addition, if a doppler-enabled `AudioStreamPlayer3D` is moving with the current `AudioListener3D` at the same velocity, the pitch will be affected even though there should be no change. The one exception to this last case is when the emitter and listener move perpendicularly to how they are arranged, in which case no doppler effect is heard.

Here is a video of the minimal reproduction project in action:

https://github.com/user-attachments/assets/9b14cf77-a765-42e9-b37c-021071d6cfd8

### Steps to reproduce

1. Download and play the reproduction project (4.4)
2. Click "Static Listener, Moving Player". Observe how the doppler effect works correct here.
3. Click "Moving Listener, Static Player". Observe how the doppler effect now does nothing.
4. Click "Both Moving (on axis)". Observe how the doppler effect is occuring even though it should not be.
5. Click "Both Moving (perpendicular)". Observe how there is now no noticeable doppler effect.

### Minimal reproduction project (MRP)

[doppler_mrp.zip](https://github.com/user-attachments/files/20846377/doppler_mrp.zip)

### PR DESCRIPTION
**Pull request by RoyBerardo**
This closes https://github.com/godotengine/godot/issues/107799

It seems that `AudioListener3D` did not have any code for using its own velocity for doppler calculation, so I essentially just copied over the `Camera3D` doppler code. Didn't need to change much at all, the code for the camera doppler calculation does everything it needs to do and nothing more.

Now, doppler works as expected when the listener moves.

This will have a noticeable but also likely preferable change in sound for projects which use doppler and a moving listener.

### CODE REVIEW

File: scene/3d/audio_listener_3d.h [hunk 1]
```diff
@@ -31,10 +31,32 @@
...
+#include "scene/3d/velocity_tracker_3d.h"
 
 class AudioListener3D : public Node3D {
 	GDCLASS(AudioListener3D, Node3D);
 
+public:
+	enum DopplerTracking {
+		DOPPLER_TRACKING_DISABLED,
+		DOPPLER_TRACKING_IDLE_STEP,
+		DOPPLER_TRACKING_PHYSICS_STEP
```
Comment (AThousandShips) [inline scene/3d/audio_listener_3d.h]:
```suggestion
		DOPPLER_TRACKING_PHYSICS_STEP,
```

**Comment by RoyBerardo** [comment]
Had a realization of something, tested to confirm that it does happen. If doppler tracking is disabled on the listener but enabled on a stream player, doppler will still be heard. I'm on the fence on if this is a bug or not, since the doppler setting enables _tracking_, not doppler itself. If this IS a bug, should I tackle that in this PR as well? To add, the camera currently exhibits this behavior, so fixing this bug would fix it for both listeners and cameras.

**Comment by RoyBerardo** [comment]
> Had a realization of something, tested to confirm that it does happen. If doppler tracking is disabled on the listener but enabled on a stream player, doppler will still be heard. I'm on the fence on if this is a bug or not, since the doppler setting enables tracking, not doppler itself. If this IS a bug, should I tackle that in this PR as well? To add, the camera currently exhibits this behavior, so fixing this bug would fix it for both listeners and cameras.

I've decided to convert this PR to a draft for now, since I feel this is an important topic to address. It's a very easy fix that can be done in this PR, but I wonder what the best approach would be.

IMO, doppler should only be heard on a sound if both the emitter and listener have doppler enabled. That being said, this would require projects that use doppler and the camera as a listener to enable doppler on the camera, if they haven't already.

**Comment by RoyBerardo** [comment]
Re-opening.

From me in the past:
> If doppler tracking is disabled on the listener but enabled on a stream player, doppler will still be heard.

IMO this is fine. If it was the other way around, that would be a problem. Plus, this is how it's been for a while now anyways. I've updated the PR to add this info to the documentation. I'm not the greatest at writing docs, so I'd appreciate it if someone who is gave my updates a look :)

**Review by Calinou — COMMENTED** [review]
Tested locally on Linux with the MRP from https://github.com/godotengine/godot/issues/107799, I can't spot any difference before and after this PR:

### `master`

https://github.com/user-attachments/assets/8288922e-883f-44a0-a3b2-e41e30d21ecc

### This PR

https://github.com/user-attachments/assets/42298326-fffe-4cd2-8be4-6ed0757660bf

**Comment by RoyBerardo** [comment]
@Calinou 

Ah, this one is on me for not making an updated MRP for this PR :)

The MRP in the issue doesn't have saved settings for `doppler_tracking` on the listeners, since that property is introduced in this PR. Without setting `doppler_tracking`, listeners behave the same as master since the listener won't track its own velocity.

I've attached an updated MRP to this comment, with `doppler_tracking` set on the listeners. 
[MRP_Fix_Test.zip](https://github.com/user-attachments/files/21374313/MRP_Fix_Test.zip)

Video of the updated MRP:

https://github.com/user-attachments/assets/68f4a949-072e-4116-9722-f7638d79e15a

**Review by Calinou — APPROVED** [review]
Works great with the updated MRP :slightly_smiling_face: 

Code and documentation look good to me.

File: scene/3d/audio_listener_3d.h (hunk 1 above)
Comment (RoyBerardo) [reply scene/3d/audio_listener_3d.h]: Force pushed these changes, seems to be failing checks though, not sure why.

**Comment by Repiteo** [comment]
Thanks!
