### PR TITLE
 Use regularization flag for LODs of deformable objects to improve appearance post deformation

### LINKED ISSUE #71141: Imported 3D Armature Missing Last Bone In Chain
### Godot version

v4.0.alpha10.official [4bbe7f0b9]

### System information

Windows 10

### Issue description

I've noticed that gltf files imported from Blender are missing all leaf bones in the scene view and in the skin weights, yet the bones are still selectable in the Skeleton3D inspector window.

This is how the animation appears in Blender: 
Honeycam 2023-01-10 01-13-32

This is how the imported animation appears in the scene: 

https://user-images.githubusercontent.com/38251868/211477994-7a739b6a-cf10-4fbb-9225-422dbef1fbf3.mp4

### Steps to reproduce

Open the zipped scene, right click on `test.gltf` and select `New Inherited Scene`, play the `test_anim` animation in the `AnimationPlayer` and view the bones in the `Skeleton3D` inspector.

### Minimal reproduction project

[Uploading ArmatureImportIssue.zip…]()

### LINKED ISSUE #84479: Potential skinning issue with glb files
### Godot version

4.1.3

### System information

Windows 11 - Godot 4.1.3 - Forward+

### Issue description

I was experimenting with using Blender's bendy bones for animation by copying the transform of the segments to standard bones, but the exported animation shows up weirdly in Godot.  Here's what the animation at a certain frame should look like
image
And here's the result from Godot:
image

The same issue doesn't happen when I export to FBX and use FBX2GLTF and with other GLTF viewers (I tried [this](https://gltf-viewer.donmccurdy.com/) and [this](https://playcanvas.com/viewer)), so this is most likely an edge-case in gltf-s godot doesn't handle properly.

### Steps to reproduce

1. Open the attached project
2. Make sure "test" has "Editable children" enabled
3. Select "AnimationPlayer" and set "Current Animation" to "ArmatureAction"

### Minimal reproduction project

[SkinningIssue.zip](https://github.com/godotengine/godot/files/13259731/SkinningIssue.zip)

### PR DESCRIPTION
**Pull request by zeux**
Closes https://github.com/godotengine/godot/issues/84479
Closes https://github.com/godotengine/godot/issues/71141

When generating LODs for meshes that use skinning or blend shapes, we now use the new regularization option (available as of meshoptimizer 0.25). This results in the simplifier taking the distance along the original surface into account when computing simplification error, which biases the results to have a more uniform tessellation, accounting for deformation that is unknown at import time. This fixes two instances of severe LOD degradation (above) after a re-import; it also helps more regular character meshes in certain cases, for example here's a before-after on a mesh with a cape that was simplified too much previously (LOD selection exaggerated via project settings, ~same number of triangles before/after):

before | after
----------|--------
image | image
image | image

### CODE REVIEW

**Review by fire — COMMENTED** [review]
Great work! Will want to try out the test cases to visually see the improvements. I like the neat trick you did.

Edited:

taking the distance along the original surface into account

**Review by clayjohn — APPROVED** [review]

**Comment by fire** [comment]
Significant improvement was seen at lod_bias 0.04

https://github.com/user-attachments/assets/c80c064a-35c3-4c33-98d6-1ef2321c5dbd

https://github.com/user-attachments/assets/5feb3b96-15d6-4fbb-809a-95b2d48fd3d9

[SkinningIssue-GODOT-pr-109992.zip](https://github.com/user-attachments/files/21997400/SkinningIssue-GODOT-pr-109992.zip)

File: scene/resources/3d/importer_mesh.cpp [hunk 1]
```diff
@@ -482,7 +484,15 @@ void ImporterMesh::generate_lods(float p_normal_merge_angle, Array p_bone_transf
...
 			new_indices.resize(index_count);
 
-			const int simplify_options = SurfaceTool::SIMPLIFY_LOCK_BORDER;
+			int simplify_options = 0;
+
+			// Lock geometric boundary in case the mesh is composed of multiple material subsets
+			simplify_options |= SurfaceTool::SIMPLIFY_LOCK_BORDER;
+
+			if (deformable) {
+				// Improves appearance of deformable objects after deformation by using more regular tessellation
```
Comment (Calinou) [inline scene/resources/3d/importer_mesh.cpp]:
```suggestion
				// Improves appearance of deformable objects after deformation by using more regular tessellation.
```

File: scene/resources/3d/importer_mesh.cpp [hunk 2]
```diff
@@ -482,7 +484,15 @@ void ImporterMesh::generate_lods(float p_normal_merge_angle, Array p_bone_transf
 			PackedInt32Array new_indices;
 			new_indices.resize(index_count);
 
-			const int simplify_options = SurfaceTool::SIMPLIFY_LOCK_BORDER;
+			int simplify_options = 0;
+
+			// Lock geometric boundary in case the mesh is composed of multiple material subsets
```
Comment (Calinou) [inline scene/resources/3d/importer_mesh.cpp]:
```suggestion
			// Lock geometric boundary in case the mesh is composed of multiple material subsets.
```

**Review by fire — APPROVED** [review]

**Review by Calinou — APPROVED** [review]
Code looks good to me. Remember to squash the last two commits so this can be merged :slightly_smiling_face:

**Comment by zeux** [comment]
Yup, squashed the last two commits here and rebased the dependent PR chain.

**Review by BlueCube3310 — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Comment by fire** [comment]
Would it be possible to cherry pick for 4.5?
