### PR TITLE
Fix debanding for Mobile rendering method with HDR 2D.

### LINKED ISSUE #108757: HDR 2D debanding is broken with Mobile rendering method
### Tested versions

- Reproducible in 2be2cbb720e4b2c2fa11e677c73d4371c4ab47b9 onwards
- Not reproducible in Godot 4.4.1

### System information

Any

### Issue description

When I wrote https://github.com/godotengine/godot/pull/107782, I forgot that HDR 2D still uses a 10-bit viewport buffer on the Mobile Rendering method, so this means that viewport-based debanding must still be active with HDR 2D enabled, but it should be 10-bit aligned dithering rather than 8-bit aligned dithering.

End result is that non-material based effects like Glow effects no longer have functioning debanding:

| 4.4.1 | masater
| --- | ---
| Image | Image

### Steps to reproduce

- Create a project with Mobile rendering method
- Enable HDR 2D
- Set up a scene that uses environment effects like Glow
- Enable debanding
- Note that it doesn't work on the environment effects

### Minimal reproduction project (MRP)

[mobile-debanding.zip](https://github.com/user-attachments/files/21322782/mobile-debanding.zip)

### PR DESCRIPTION
**Pull request by allenwp**
Fixes #108757

In addition to fixing the bug, this PR aligns the dither to the appropriate data format (8 bit or 10 bit) to reduce both banding/ringing and noise.

I've also removed a duplicate `convert_to_srgb` conditional statement from `renderer_compositor_rd.cpp` because this conditional is also performed in `blit.glsl`. I  think it's better to have the conditional check only occur in a single place, since it makes things confusion when editing the code and seeing no change in behaviour.

There are a few places where I've made assumptions about the `DataFormat` of the Framebuffer: I've noted these assumptions as comments so that if any issues arise in the future it will be easier to track down where the bad assumption is being made.

If my code is correct, debanding will be applied any time floating point values need to be quantized to integer values. For example, if a 10-bit integer buffer is loaded into shader-land as floats and then modified (for example, by applying a glow, tonemapping, or transfer function), then it needs to be benanded before being written back to a 10-bit buffer. Additionally, any time color data is transformed from 10-bit to 8-bit, debanding will need to be applied again.

The only time when debanding is not needed is when an image is read from an integer data format and written to an integer data format of the same bit depth without any floating point transformations on the image. In this case, if debanding was applied it should have no effect on the image because the debanding function is designed to apply noise/grain 50% above and below the colour value in the destination data format -- if the color is already perfectly aligned to the buffer's data format like in this case, then the 50% above and below will simply round back to the same color data as the original image.

...Unfortunately, it seems that rounding doesn't work exactly this way with my drivers. I suspect that rounding behaviour is simply not standardized and guaranteed. With my drivers, I need to modify the dither function as follows to get no rounding error and therefore no additional noise when applying the dither function to an already-quantized image:

```
vec3 dither = vec3(dot(vec2(171.0, 231.0), frag_coord));
dither.rgb = fract(dither.rgb / vec3(103.0, 71.0, 97.0));
dither = (dither.rgb - 0.5);
dither = max(dither, -0.43);
return dither / 255.0;
```

or:

```
vec3 dither = vec3(dot(vec2(171.0, 231.0), frag_coord));
dither.rgb = fract(dither.rgb / vec3(103.0, 71.0, 97.0));
return (dither.rgb - 0.5) * 0.86 / 255.0;
```

But with different drivers, a different "dither strength" modifier might be needed to produce stable rounding behaviour.

All that to say, it's good to disable the debanding in these scenarios to ensure we don't get any extra noise when debanding should be producing no difference to the image.

| 4.4.1 | `master` | This PR
| --- | --- | ---
|  | master | pr-fix

Mobile Without | Mobile With Debanding
-- | --
 | 
 | 

Forward+ Without Debanding | Forward+ With Debanding
-- | --
image | image
image | image

In addition to fixing the bug, this PR aligns the dither to the appropriate data format (8 bit or 10 bit) to reduce both banding/ringing and noise.

### CODE REVIEW

**Comment by allenwp** [comment]
I think I've sat on this for enough time to catch the issues that I only catch after giving myself the time. Marking as ready for review now.

File: servers/rendering/renderer_rd/renderer_scene_render_rd.cpp [hunk 1]
```diff
@@ -683,24 +684,43 @@ void RendererSceneRenderRD::_render_buffers_post_process_and_tonemap(const Rende
...
 			}
 		}
 
+		if (rb->get_use_debanding()) {
+			if (dest_fb_format >= RD::DATA_FORMAT_R8_UNORM && dest_fb_format <= RD::DATA_FORMAT_A8B8G8R8_SRGB_PACK32) {
+				tonemap.debanding_mode = RendererRD::ToneMapper::TonemapSettings::DebandingMode::DEBANDING_MODE_8_BIT;
+			} else if (dest_fb_format >= RD::DATA_FORMAT_A2R10G10B10_UNORM_PACK32 && dest_fb_format <= RD::DATA_FORMAT_A2B10G10R10_SINT_PACK32) {
+				tonemap.debanding_mode = RendererRD::ToneMapper::TonemapSettings::DebandingMode::DEBANDING_MODE_10_BIT;
+			} else {
+				// In this case, debanding will be handled later when quantizing to an integer data format. (During blit, for example)
```
Comment (Calinou) [inline servers/rendering/renderer_rd/renderer_scene_render_rd.cpp]:
```suggestion
				// In this case, debanding will be handled later when quantizing to an integer data format. (During blit, for example.)
```

File: servers/rendering/renderer_rd/renderer_scene_render_rd.cpp [hunk 2]
```diff
@@ -837,12 +859,26 @@ void RendererSceneRenderRD::_post_process_subpass(RID p_source_texture, RID p_fr
...
 	}
 
-	tonemap.use_debanding = rb->get_use_debanding();
 	tonemap.texture_size = Vector2i(target_size.x, target_size.y);
 
 	tonemap.luminance_multiplier = _render_buffers_get_luminance_multiplier();
 	tonemap.view_count = rb->get_view_count();
 
+	if (rb->get_use_debanding()) {
+		// Assume that the DataFormat of p_framebuffer is the same as render_target_get_color_format
```
Comment (Calinou) [inline servers/rendering/renderer_rd/renderer_scene_render_rd.cpp]:
```suggestion
		// Assume that the DataFormat of p_framebuffer is the same as render_target_get_color_format.
```

File: servers/rendering/renderer_rd/renderer_scene_render_rd.cpp [hunk 3]
```diff
@@ -837,12 +859,26 @@ void RendererSceneRenderRD::_post_process_subpass(RID p_source_texture, RID p_fr
...
+		RD::DataFormat dest_fb_format = texture_storage->render_target_get_color_format(using_hdr, tonemap.convert_to_srgb);
+		if (dest_fb_format >= RD::DATA_FORMAT_R8_UNORM && dest_fb_format <= RD::DATA_FORMAT_A8B8G8R8_SRGB_PACK32) {
+			tonemap.debanding_mode = RendererRD::ToneMapper::TonemapSettings::DebandingMode::DEBANDING_MODE_8_BIT;
+		} else if (dest_fb_format >= RD::DATA_FORMAT_A2R10G10B10_UNORM_PACK32 && dest_fb_format <= RD::DATA_FORMAT_A2B10G10R10_SINT_PACK32) {
+			tonemap.debanding_mode = RendererRD::ToneMapper::TonemapSettings::DebandingMode::DEBANDING_MODE_10_BIT;
+		} else {
+			// In this case, debanding will be handled later when quantizing to an integer data format. (During blit, for example)
```
Comment (Calinou) [inline servers/rendering/renderer_rd/renderer_scene_render_rd.cpp]:
```suggestion
			// In this case, debanding will be handled later when quantizing to an integer data format. (During blit, for example.)
```

File: servers/rendering/renderer_rd/renderer_scene_render_rd.cpp [hunk 4]
```diff
@@ -683,24 +684,43 @@ void RendererSceneRenderRD::_render_buffers_post_process_and_tonemap(const Rende
...
 			// Target size in this case is lying as we never get our real target size communicated.
 			// Bit nasty but...
 
 			if (dest_is_msaa_2d) {
+				// Assume that the DataFormat of render_target_get_rd_texture_msaa is the same as render_target_get_color_format
+				dest_fb_format = texture_storage->render_target_get_color_format(using_hdr, tonemap.convert_to_srgb);
 				dest_fb = FramebufferCacheRD::get_singleton()->get_cache(texture_storage->render_target_get_rd_texture_msaa(render_target));
 				texture_storage->render_target_set_msaa_needs_resolve(render_target, true); // Make sure this gets resolved.
 			} else {
+				// Assume that the DataFormat of render_target_get_rd_framebuffer is the same as render_target_get_color_format
```
Comment (Calinou) [inline servers/rendering/renderer_rd/renderer_scene_render_rd.cpp]:
```suggestion
				// Assume that the DataFormat of render_target_get_rd_framebuffer is the same as render_target_get_color_format.
```

File: servers/rendering/renderer_rd/renderer_scene_render_rd.cpp [hunk 5]
```diff
@@ -683,24 +684,43 @@ void RendererSceneRenderRD::_render_buffers_post_process_and_tonemap(const Rende
...
+			dest_fb_format = _render_buffers_get_color_format();
+			RID dest_texture = rb->create_texture(SNAME("Tonemapper"), SNAME("destination"), dest_fb_format, RD::TEXTURE_USAGE_SAMPLING_BIT | RD::TEXTURE_USAGE_STORAGE_BIT | RD::TEXTURE_USAGE_COLOR_ATTACHMENT_BIT, RD::TEXTURE_SAMPLES_1, Size2i(), 0, 1, true, true);
 			dest_fb = FramebufferCacheRD::get_singleton()->get_cache(dest_texture);
 		} else {
 			// If we do a bilinear upscale we just render into our render target and our shader will upscale automatically.
 			// Target size in this case is lying as we never get our real target size communicated.
 			// Bit nasty but...
 
 			if (dest_is_msaa_2d) {
+				// Assume that the DataFormat of render_target_get_rd_texture_msaa is the same as render_target_get_color_format
```
Comment (Calinou) [inline servers/rendering/renderer_rd/renderer_scene_render_rd.cpp]:
```suggestion
				// Assume that the DataFormat of render_target_get_rd_texture_msaa is the same as render_target_get_color_format.
```

**Review by Calinou — COMMENTED** [review]
Code looks good to me.

**Testing project:** [test_pr_108761.zip](https://github.com/user-attachments/files/21415052/test_pr_108761.zip)

I'm not sure if it's working on my end though, I still see significant banding in 2D in Mobile when glow is enabled (with HDR 2D also enabled):

Debanding OFF | Debanding ON
-|-
image | image

Contrast increased for visibility (using GIMP's **Colors > Auto > White Balance** filter):

Debanding OFF | Debanding ON
-|-
image | image

**Comment by allenwp** [comment]
> **Testing project:** [test_pr_108761.zip](https://github.com/user-attachments/files/21415052/test_pr_108761.zip)

Hmm. That's strange, this link points me to a "Not found" page.

The purpose of this PR is to fix a regression introduced in #107782, so I'm curious what this looks like when rendered with Godot 4.4.1...

Edit: Also, does this reproduce with a running instance of the scene or only in the Editor? Does restarting the editor resolve the issue?

**Comment by Calinou** [comment]
> Hmm. That's strange, this link points me to a "Not found" page.

Try this: https://0x0.st/8n7_.zip

> Edit: Also, does this reproduce with a running instance of the scene or only in the Editor? Does restarting the editor resolve the issue?

Restarting the editor didn't seem to resolve the issue, but I didn't try to reproduce this in the running project.

**Comment by allenwp** [comment]
Thanks! The link actually started working moments before you posted :)

I'm having a hard time reproducing this on my end. Here's what I see, but I need to restart the editor to see the changes in the editor:

This PR Debanding OFF (Editor) | This PR Debanding ON (Editor)
-- | --
image | image

That said, this test project fails to apply debanding in 4.4.1 in the editor, even after an editor restart.

4.4.1 Debanding OFF (Editor) | 4.4.1 Debanding ON (Editor)
-- | --
image | image

But the behaviour in a running instance of a game is the same and correct for both this PR and 4.4.1:

This PR Debanding OFF (Game) | This PR Debanding ON (Game)
-- | --
image | image

4.4.1 Debanding OFF (Game) | 4.4.1 Debanding ON (Game)
-- | --
image | image

So on my side, everything is working correctly and as expected in this PR's build artifact and I can't reproduce the issue you've described... 🤔 (Well, except for needing to restart the editor... but I remember this being an existing issue in 4.4.1.)

**Comment by Calinou** [comment]
> So on my side, everything is working correctly and as expected in this PR's build artifact and I can't reproduce the issue you've described... 🤔 (Well, except for needing to restart the editor... but I remember this being an existing issue in 4.4.1.)

I see, I wasn't aware of this editor issue. Is there an issue open to track it? I can't see any right now.

**Review by Calinou — APPROVED** [review]
Approving the PR, since the issue I reported above isn't related to this PR and is an existing editor bug.

**Comment by allenwp** [comment]
> I see, I wasn't aware of this editor issue. Is there an issue open to track it? I can't see any right now.

I'll open a bug report. It seems to be an issue that is specific to debanding of 2D scenes with a Canvas background mode Environment and the Mobile rendering method. 4.4.1 doesn't ever show debanding in the editor with this specific configuration... I must have changed something since 4.4.1 that makes it work after a restart of the editor.

**Comment by allenwp** [comment]
Bug report created: #108948

**Comment by Repiteo** [comment]
Could you update the commit message to remove the `Fixes godotengine#108757` line? Otherwise it'll cause a bunch of unnecessary pings

**Comment by allenwp** [comment]
> Could you update the commit message to remove the `Fixes godotengine#108757` line? Otherwise it'll cause a bunch of unnecessary pings

Done! And thanks for letting me know the reason -- I'll try to remember to keep the "Fixes ..." line out of the commit message and only in the github PR.

**Comment by Repiteo** [comment]
Thanks!
