### PR TITLE
Hide EditorSpinSlider slider for VectorNI

### LINKED ISSUE #102487: Slider visible for VectorNI
### Tested versions

Not in 4.4.beta2

v4.4.beta.custom_build [c394eaa45]

### System information

Fedora Linux 40 (KDE Plasma) on Wayland - X11 display driver, Multi-window

### Issue description

https://github.com/user-attachments/assets/68ce5ff5-f856-4b83-983a-b966357ce5f3

Image

### Steps to reproduce

Add a window and look at position or size

### Minimal reproduction project (MRP)

[sliders.zip](https://github.com/user-attachments/files/18692137/sliders.zip)

### PR DESCRIPTION
**Pull request by Giganzo**
Fixes: https://github.com/godotengine/godot/issues/102487

After:
Screenshot_20250205_230731

### CODE REVIEW

File: editor/editor_properties.cpp [hunk 1]
```diff
@@ -3663,7 +3663,7 @@ EditorProperty *EditorInspectorDefaultPlugin::get_editor_for_property(Object *p_
 		case Variant::VECTOR2I: {
 			EditorPropertyVector2i *editor = memnew(EditorPropertyVector2i(p_wide));
 			EditorPropertyRangeHint hint = _parse_range_hint(p_hint, p_hint_text, 1, true);
-			editor->setup(hint.min, hint.max, 1, false, p_hint == PROPERTY_HINT_LINK, hint.suffix);
+			editor->setup(hint.min, hint.max, 1, false, p_hint == PROPERTY_HINT_LINK, hint.suffix, hint.radians_as_degrees, true);
```
Comment (AThousandShips) [inline editor/editor_properties.cpp:3666]: Don't think using radians as degrees here makes sense, I think it should be:
```suggestion
			editor->setup(hint.min, hint.max, 1, false, p_hint == PROPERTY_HINT_LINK, hint.suffix, false, true);
```
For all

**Review by Calinou — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
