### PR TITLE
Fix Android TTS on-demand init.

### LINKED ISSUE #109156: DisplayServer.tts_get_voices() crashes on Android
### Tested versions

v4.5.beta4.mono.official [2d113cc22]

### System information

Android

### Issue description

Using DisplayServer.tts_get_voices() results in an instant crash for me on Android, have tested both on Android 9 and 14.
When using Mono, I get this error in adb logcat:
`ERROR: BUG: Unreferenced static string to 0: Physics2DConstraintSolveIslands`
I don't get the same error when only using GDScript, but it still crashes.

### Steps to reproduce

Simply call DisplayServer.tts_get_voices() and run on Android.

### Minimal reproduction project (MRP)

[tts-get-voices.zip](https://github.com/user-attachments/files/21527419/tts-get-voices.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/109156

- Adds `onInit` listener and a bunch of null checks for `voices`.
- Runs TTS init in a thread (and wait for state change if it is initialized on demand).

### CODE REVIEW

File: platform/android/tts_android.cpp [hunk 1]
```diff
@@ -99,6 +149,7 @@ void TTS_Android::_java_utterance_callback(int p_event, int p_id, int p_pos) {
 	if (unlikely(!initialized)) {
 		initialize_tts();
 	}
+	ERR_FAIL_COND(!initialized);
 	ERR_FAIL_NULL(tts);
```
Comment (AThousandShips) [inline platform/android/tts_android.cpp]: For convenience and ensuring things are done consistently it might be worth separating these two lines into a helper macro, like `CHECK_TTS_VALID`, so we don't forget to add either, though it might reduce readability by removing it from scope, alternatively it could be converted into:
```suggestion
	ERR_FAIL_COND_MSG(!initialized || tts == nullptr, "Text to Speech not initialized.");
```
Or some other appropriate error message

Comment (bruvzg) [reply platform/android/tts_android.cpp]: Macro won't be convenient since some of these check have different return values, changed it to single `COND_[V]_MSG`.

**Review by m4gr3d — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
