### PR TITLE
Fix ScriptEditor inline color wrong line number

### LINKED ISSUE #108331: ColorPicker puts values into wrong places in code
### Tested versions

- NOT reproducible in 4.4.1 Stable
- reproducible in 4.5 beta2

### System information

Godot v4.4.1.stable - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 32.0.15.6614) - AMD Ryzen 9 3900X 12-Core Processor (24 threads)

### Issue description

https://github.com/user-attachments/assets/327e73e8-8723-44e4-9c8a-90058abdf449

If you use the new color picker preview icon to pick a color, it places values into wrong places

### Steps to reproduce

1. Have an Array of Colors (you can use this code used in the MRP)

`const sky_colors = [
	[Color(0.263, 0.518, 0.878), Color(0.502, 0.651, 1.0)],
	[Color(0.004, 0.451, 0.831), Color(0.545, 0.804, 0.937)],
	[Color(0.086, 0.63, 0.998, 1.0), Color(0.996, 0.847, 0.776, 1.0)],
	[Color(0.0, 0.567, 0.978, 1.0), Color(0.808, 0.882, 0.945)],
]`

2. Click on the color preview square thing and change the color

### Minimal reproduction project (MRP)

[bugreport_MRP.zip](https://github.com/user-attachments/files/21087381/bugreport_MRP.zip)

### PR DESCRIPTION
**Pull request by kitbdev**
- Fixes https://github.com/godotengine/godot/issues/108331

Removes the line from the inline object, it doesn't need to be stored there and it didn't get updated.

To test: add or remove a line somewhere above an inline color object and try to use it.

### CODE REVIEW

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -2386,12 +2386,13 @@ void TextEdit::gui_input(const Ref<InputEvent> &p_gui_input) {
 					float wrap_indent = wrap_i > first_indent_line ? MIN(text.get_indent_offset(pos.y, is_layout_rtl()), wrap_at_column * 0.6) : 0.0;
 
 					Ref<TextParagraph> ldata = text.get_line_data(line);
-					for (Variant k : ldata->get_line_objects(wrap_i)) {
-						if (!is_inline_info_valid(k)) {
+					for (const Variant inline_key : ldata->get_line_objects(wrap_i)) {
```
Comment (adamscott) [inline scene/gui/text_edit.cpp]: This should fix the build error.

```suggestion
					for (const Variant &inline_key : ldata->get_line_objects(wrap_i)) {
```

**Review by bruvzg — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
