### PR TITLE
Fix lambda cross-thread dynamics (take 2)

### LINKED ISSUE #85151: GDScript engine destruction causes deadlock when destroying lambdas
### Godot version

v4.2.rc.custom_build [dfd61cdac]

### System information

Debian, Vulkan (Forward+)

### Issue description

<details><summary>Stack Trace</summary>

```
#0  futex_wait (private=0, expected=2, futex_word=0x55556474d280) at ../sysdeps/nptl/futex-internal.h:146
#1  __GI___lll_lock_wait (futex=futex@entry=0x55556474d280, private=0) at ./nptl/lowlevellock.c:49
#2  0x00007ffff7d61682 in lll_mutex_lock_optimized (mutex=0x55556474d280) at ./nptl/pthread_mutex_lock.c:48
#3  ___pthread_mutex_lock (mutex=0x55556474d280) at ./nptl/pthread_mutex_lock.c:93
#4  0x0000555557f673cd in __gthread_mutex_lock (__mutex=0x55556474d280) at /usr/include/x86_64-linux-gnu/c++/13/bits/gthr-default.h:749
#5  0x0000555557f6741d in __gthread_recursive_mutex_lock (__mutex=0x55556474d280) at /usr/include/x86_64-linux-gnu/c++/13/bits/gthr-default.h:811
#6  0x0000555557f67452 in std::recursive_mutex::lock (this=0x55556474d280) at /usr/include/c++/13/mutex:120
#7  0x0000555557f67d4f in std::unique_lock<std::recursive_mutex>::lock (this=0x7fffffffcc70) at /usr/include/c++/13/bits/unique_lock.h:141
#8  0x0000555557f67c7b in std::unique_lock<std::recursive_mutex>::unique_lock (this=0x7fffffffcc70, __m=...)
    at /usr/include/c++/13/bits/unique_lock.h:71
#9  0x00005555582a1d67 in MutexLock<MutexImpl<std::recursive_mutex> >::MutexLock (p_mutex=..., this=<optimized out>) at ./core/os/mutex.h:122
#10 GDScript::_remove_func_ptr_to_update (p_func_ptr_element=0x555564749d30) at modules/gdscript/gdscript.cpp:1424
#11 0x000055555848002c in GDScriptLambdaCallable::~GDScriptLambdaCallable (this=0x5555646bd690, __in_chrg=<optimized out>)
    at modules/gdscript/gdscript_lambda_callable.cpp:155
#12 0x000055555bf85196 in memdelete<CallableCustom> (p_class=0x5555646bd690) at ./core/os/memory.h:109
#13 0x000055555bf83e7a in Callable::~Callable (this=0x5555647355d8, __in_chrg=<optimized out>) at core/variant/callable.cpp:382
#14 0x000055555bf8b8a7 in Variant::_clear_internal (this=0x5555647355d0) at core/variant/variant.cpp:1373
#15 0x0000555557f58605 in Variant::clear (this=0x5555647355d0) at core/variant/variant.h:302
#16 0x0000555557f58672 in Variant::~Variant (this=0x5555647355d0, __in_chrg=<optimized out>) at core/variant/variant.h:788
#17 0x0000555557f9d0da in CowData<Variant>::_unref (this=0x555564749a18, p_data=0x5555647355a0) at ./core/templates/cowdata.h:216
#18 0x0000555557f985b0 in CowData<Variant>::~CowData (this=0x555564749a18, __in_chrg=<optimized out>) at ./core/templates/cowdata.h:415
#19 0x0000555557f92f28 in Vector<Variant>::~Vector (this=0x555564749a10, __in_chrg=<optimized out>) at ./core/templates/vector.h:290
#20 0x00005555582a6070 in GDScriptInstance::~GDScriptInstance (this=0x5555647499c0, __in_chrg=<optimized out>) at modules/gdscript/gdscript.cpp:2096
#21 0x000055555c2d7d5a in memdelete<ScriptInstance> (p_class=0x5555647499c0) at ./core/os/memory.h:109
#22 0x000055555c2d5493 in Object::~Object (this=0x555564749830, __in_chrg=<optimized out>) at core/object/object.cpp:1979
#23 0x000055555800d898 in RefCounted::~RefCounted (this=0x555564749830, __in_chrg=<optimized out>) at ./core/object/ref_counted.h:53
#24 0x000055555805c0a1 in memdelete<RefCounted> (p_class=0x555564749830) at ./core/os/memory.h:109
#25 0x000055555bf8b85a in Variant::_clear_internal (this=0x555564749530) at core/variant/variant.cpp:1360
#26 0x0000555557f58605 in Variant::clear (this=0x555564749530) at ./core/variant/variant.h:302
#27 0x0000555557f58672 in Variant::~Variant (this=0x555564749530, __in_chrg=<optimized out>) at ./core/variant/variant.h:788
#28 0x0000555557f9d0da in CowData<Variant>::_unref (this=0x55556474edb0, p_data=0x555564749530) at ./core/templates/cowdata.h:216
#29 0x0000555557f985b0 in CowData<Variant>::~CowData (this=0x55556474edb0, __in_chrg=<optimized out>) at ./core/templates/cowdata.h:415
#30 0x0000555557f92f28 in Vector<Variant>::~Vector (this=0x55556474eda8, __in_chrg=<optimized out>) at ./core/templates/vector.h:290
#31 0x000055555bf7f1c6 in ArrayPrivate::~ArrayPrivate (this=0x55556474eda0, __in_chrg=<optimized out>) at core/variant/array.cpp:44
#32 0x000055555bf7f1f5 in memdelete<ArrayPrivate> (p_class=0x55556474eda0) at ./core/os/memory.h:109
#33 0x000055555bf794cf in Array::_unref (this=0x5555645eca48) at core/variant/array.cpp:79
#34 0x000055555bf7d9d0 in Array::~Array (this=0x5555645eca48, __in_chrg=<optimized out>) at core/variant/array.cpp:823
#35 0x000055555bf8b8e6 in Variant::_clear_internal (this=0x5555645eca40) at core/variant/variant.cpp:1382
#36 0x0000555557f58605 in Variant::clear (this=0x5555645eca40) at ./core/variant/variant.h:302
#37 0x0000555557f58672 in Variant::~Variant (this=0x5555645eca40, __in_chrg=<optimized out>) at ./core/variant/variant.h:788
#38 0x0000555557f9d0da in CowData<Variant>::_unref (this=0x5555643a65d8, p_data=0x5555645ec8c0) at ./core/templates/cowdata.h:216
#39 0x0000555557f988a2 in CowData<Variant>::resize<false> (this=0x5555643a65d8, p_size=0) at ./core/templates/cowdata.h:275
#40 0x0000555557f931ea in Vector<Variant>::resize (this=0x5555643a65d0, p_size=0) at ./core/templates/vector.h:94
#41 0x00005555582b475d in Vector<Variant>::clear (this=0x5555643a65d0) at ./core/templates/vector.h:87
#42 0x00005555582a277a in GDScript::clear (this=0x5555643a6330, p_clear_data=0x0) at modules/gdscript/gdscript.cpp:1545
#43 0x00005555582a6c9d in GDScriptLanguage::finish (this=0x5555607fc2e0) at modules/gdscript/gdscript.cpp:2221
#44 0x000055555c2e7f82 in ScriptServer::finish_languages () at core/object/script_language.cpp:259
#45 0x0000555557fef64b in Main::cleanup (p_force=false) at main/main.cpp:3783
#46 0x0000555557f57961 in main (argc=1, argv=0x7fffffffdee8) at platform/linuxbsd/godot_linuxbsd.cpp:76
```

</details>

Not sure what causes this, but it seems having a vector/array of Callables/lambdas or of something that contains lambdas is causing a deadlock.

The deadlock only happens AFTER calling `get_tree().quit()` (or Alt+F4) and AFTER the tree has been removed. I am using static variables in classes to hold lists of callables, but even manually removing those references before quitting doesn't change the outcome.

It is impossible to pin it from the godot debugger as it blocks the keyboard interrupt signal, thus, a GDB backtrace. This causes the project to hang on the last frame and become unresponsive to anything save a kill.

I don't know how to provide more information on this, sorry.

### Steps to reproduce

No clue!

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by RandomShaper**
This PR has two commits:
1. Reverts recent attempts to fix a chain of issues, which was making the whole thing extremely complex.
2. Implements an alternative to #84659 (the first reverted one), much simpler, now I've been lucid enough to realize how to do it properly. I'm muuuch more satisfied with this approach. (Reviewers are advised to check the diff of just this one, to be back to the starting point.)

Supersedes #85223.
Fixes #85151.

Tested the following recent related bugs are still gone after this PR (plus no address sanitizer issues detected);
- #84046
- #84190
- #85112

### CODE REVIEW

File: modules/gdscript/gdscript.cpp [hunk 1]
```diff
@@ -2141,8 +2103,27 @@ void GDScriptLanguage::remove_named_global_constant(const StringName &p_name) {
 	named_globals.erase(p_name);
 }
 
+void GDScriptLanguage::thread_enter() {
+	GDScript::func_ptrs_to_update_thread_local = memnew(GDScript::UpdatableFuncPtr);
+	GDScript::func_ptrs_to_update_thread_local->mutex.lock();
+	GDScript::func_ptrs_to_update_thread_local->mutex.unlock();
```
Comment (adamscott) [inline modules/gdscript/gdscript.cpp:2109]: Is this a leftover or this is intentional? Maybe adding a comment here explaining the point of locking and unlocking the mutex without doing anything.

File: modules/gdscript/gdscript.cpp [hunk 2]
```diff
@@ -1391,34 +1391,54 @@ String GDScript::debug_get_script_name(const Ref<Script> &p_script) {
...
 	UpdatableFuncPtrElement result = {};
 
 	{
-		MutexLock lock(func_ptrs_to_update_thread_local.mutex);
-		result.element = func_ptrs_to_update_thread_local.ptrs.push_back(p_func_ptr_ptr);
-		result.mutex = &func_ptrs_to_update_thread_local.mutex;
+		MutexLock lock(func_ptrs_to_update_thread_local->mutex);
+		result.element = func_ptrs_to_update_thread_local->ptrs.push_back(p_func_ptr_ptr);
+		result.func_ptr = func_ptrs_to_update_thread_local;
+		//func_ptrs_to_update_thread_local->rc++;
```
Comment (akien-mga) [inline modules/gdscript/gdscript.cpp:1404]: Kept as reference, or from a previous attempt but it's not needed here?

File: modules/gdscript/gdscript.cpp [hunk 3]
```diff
@@ -1391,34 +1391,54 @@ String GDScript::debug_get_script_name(const Ref<Script> &p_script) {
...
 
-void GDScript::_remove_func_ptr_to_update(const UpdatableFuncPtrElement p_func_ptr_element) {
+void GDScript::_remove_func_ptr_to_update(const UpdatableFuncPtrElement &p_func_ptr_element) {
 	ERR_FAIL_NULL(p_func_ptr_element.element);
-	ERR_FAIL_NULL(p_func_ptr_element.mutex);
-	MutexLock lock(*p_func_ptr_element.mutex);
+	ERR_FAIL_NULL(p_func_ptr_element.func_ptr);
+	MutexLock lock(p_func_ptr_element.func_ptr->mutex);
 	p_func_ptr_element.element->erase();
+	//p_func_ptr_element.func_ptr->rc--;
```
Comment (akien-mga) [inline modules/gdscript/gdscript.cpp:1425]: Same question.

File: modules/gdscript/gdscript.cpp (hunk 1 above)
Comment (RandomShaper) [reply modules/gdscript/gdscript.cpp]: I added that deliberately to try to account for a possibility, but it doesn't make sense, so I've removed it.

I wanted to make sure that, by the unlock, the recently allocated object's bytes are effectively published to other threads that already exist and may need to lock this mutex. However, that wouldn't cover the mutex itself. Therefore, if that situation happens to be possible, we would be in a bad situation regardless any desperate attempt like mine. One situation where that may happen is the following:
- Thread 1 is created.
- Thread 2 is created.
- On thread 2, `GDScript::_add_func_ptr_to_update()`. The script takes awareness of thread 1's mutex (adds thread 1's `UpdatableFuncPtr` to its `func_ptrs_to_update`).
- On thread 1, `GDScript::clear()` is called on the same script. It will lock thread 2's mutex. Thread 1 may not have had a chance yet to see thread 2's `UpdatableFuncPtr`, which includes the mutex (so it may even cause a crash).

I'm trying to reason if that can ever happen. All in all, that's separate from this PR.

File: modules/gdscript/gdscript.cpp (hunk 2 above)
Comment (RandomShaper) [reply modules/gdscript/gdscript.cpp:1404]: The latter.

Long answer is at first I was involving each lambda added-removed in the RC, but it really didn't play any role. Moreover, it wouldn't allow us to check the RC of the main thread data block to be `1` at the end (it's a `DEV_ASSERT` around). Such RC would contain an arbitrary value instead.

File: core/templates/list.h [hunk 4]
```diff
@@ -762,4 +764,35 @@ class List {
...
+template <class T, class A>
+void List<T, A>::Element::transfer_to_back(List<T, A> *p_dst_list) {
+	// Detach from current.
+
+	if (data->first == this) {
+		data->first = data->first->next_ptr;
+	}
+	if (data->last == this) {
+		data->last = data->last->prev_ptr;
+	}
```
Comment (YuriSizov) [inline core/templates/list.h:776]: Shouldn't we also update where `next_ptr`'s `prev_ptr` points and where `prev_ptr`'s `next_ptr` points?

File: modules/gdscript/gdscript.cpp [hunk 5]
```diff
@@ -1391,36 +1391,54 @@ String GDScript::debug_get_script_name(const Ref<Script> &p_script) {
...
+
+	DEV_ASSERT(!Thread::is_main_thread());
+
+	MutexLock lock(func_ptrs_to_update_main_thread.mutex);
+	MutexLock lock2(func_ptrs_to_update_thread_local->mutex);
+
+	while (!func_ptrs_to_update_thread_local->ptrs.is_empty()) {
+		List<GDScriptFunction **>::Element *E = func_ptrs_to_update_thread_local->ptrs.front();
+		E->transfer_to_back(&func_ptrs_to_update_main_thread.ptrs);
+		func_ptrs_to_update_thread_local->transferred = true;
```
Comment (YuriSizov) [inline modules/gdscript/gdscript.cpp:1438]: I assume we don't need to set it to false at any point because it's a one way transfer from a sub thread to the main thread?

File: modules/gdscript/gdscript.h [hunk 6]
```diff
@@ -121,18 +121,25 @@ class GDScript : public Script {
 	struct UpdatableFuncPtr {
 		List<GDScriptFunction **> ptrs;
 		Mutex mutex;
-		bool initialized = false;
+		bool initialized : 1;
+		bool transferred : 1;
```
Comment (YuriSizov) [inline modules/gdscript/gdscript.h:125]: Do we not need to initialize values here? Or does this syntax do it for us somehow?

**Review by YuriSizov — APPROVED** [review]
I left a couple of questions, but overall it feels good and this does look simpler. I can almost understand what's going on 🙃 

I tested https://github.com/godotengine/godot/issues/85151 and https://github.com/godotengine/godot/issues/85112, which I was able to reproduce before, and can confirm this PR fixes/refixes them.

File: modules/gdscript/gdscript.h (hunk 6 above)
Comment (adamscott) [reply modules/gdscript/gdscript.h:125]: We should initialize, I think, the values here.

Comment (AThousandShips) [reply modules/gdscript/gdscript.h:125]: They are in the constructor just below, don't know if bitfields can be directly initialized

Comment (RandomShaper) [reply modules/gdscript/gdscript.h:125]: I tried, but that requires C++20.

File: modules/gdscript/gdscript.cpp (hunk 5 above)
Comment (RandomShaper) [reply modules/gdscript/gdscript.cpp:1438]: Exactly!

File: core/templates/list.h (hunk 4 above)
Comment (RandomShaper) [reply core/templates/list.h:776]: Very true. It's after all the same as `erase()` has to do. Fixed.

**Review by akien-mga — APPROVED** [review]
Tested successfully on a few projects using lambdas.

**Comment by akien-mga** [comment]
Thanks!
