### PR TITLE
Make text-related nodes translation domain aware

### LINKED ISSUE #97893: when the chosen language is a right-to-left language(Persian in my case) the placement of elements inside the 2D scene editor is different from when the project is run
### Tested versions

Reproducible in: v4.3.stable.official [77dcf97d8] and v4.2.stable.official [46dc27791]. pretty sure in earlier versions as well

### System information

windows 10, i5 9400F, GT 1030 driver version: 31.0.15.3623

### Issue description

when the editor is in a RTL language(Persian in this instance) while the UI flips as it should(the scene tree moving to right and so on) the elements inside the scene editor also flip horizontally meaning when you put a node on the left side of the screen you're actually putting it on the right side, which you can see when you run the project you're working on.
Screenshot (168)
Screenshot (170)
additionally the problem also includes control nodes; when using any type of placement option offered by control nodes whether in the inspector or top of the scene editor(anchor presets, container sizing, etc...) they will work oppositely. 
take into account that I've only tested 2D and while not completely sure i believe the problem also affects 3D to some degree.
keep in mind that this is a seriously huge problem, rendering the engine borderline unusable in RTL languages.

Unrelated note: if you're translating the engine to Persian or are interested in doing so please contact me in discord: kushyar.n

### Steps to reproduce

change the language to Persian and place the Godot logo on the left side of editor, then run the project.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by timothyqiu**
Follow-up to #96921
Closes #97893
Supersedes #97918

In this PR:

- Makes `is_layout_rtl()` translation domain aware.
    - The translation domain's locale of current node is used instead of global `TranslationServer.get_tool_locale()`.
    - When using inherited layout direction, the search stops at the last parent sharing the same translation domain.
- Makes various text-drawing controls translation domain aware.
- When translation preview is disabled, text won't be translated, but things like layout direction and font language are determined by the fallback locale project setting.

An internal `Object::_get_locale()` helper method is added to simplify getting the actual locale / language to use.

https://github.com/user-attachments/assets/1e707dca-5406-478d-b9b7-51b54040c0f2

Test project used in the video (font not included): [rtl-preview.zip](https://github.com/user-attachments/files/22252190/rtl-preview.zip)

There're lots of controls containing the word "Diameter" in the test project. They are to show how the language affects glyph rendering. Both Chinese and Japanese uses the word 直径 for diameter, but the two characters should be rendered differently: <span lang="zh-Hans">直径</span> vs <span lang="ja">直径</span>.

### CODE REVIEW

File: scene/3d/label_3d.cpp [hunk 1]
```diff
@@ -482,8 +480,9 @@ void Label3D::_shape() {
 		TS->shaped_text_clear(text_rid);
 		TS->shaped_text_set_direction(text_rid, text_direction);
 
-		String txt = (uppercase) ? TS->string_to_upper(xl_text, language) : xl_text;
-		TS->shaped_text_add_string(text_rid, txt, font->get_rids(), font_size, font->get_opentype_features(), language);
+		const String &lang = language.is_empty() ? TranslationServer::get_singleton()->get_or_add_domain(get_translation_domain())->get_locale() : language;
+		String txt = (uppercase) ? TS->string_to_upper(xl_text, lang) : xl_text;
```
Comment (AThousandShips) [inline scene/3d/label_3d.cpp]:
```suggestion
		String txt = uppercase ? TS->string_to_upper(xl_text, lang) : xl_text;
```
While we're here let's improve the readability

File: scene/gui/text_edit.cpp [hunk 2]
```diff
@@ -3740,8 +3743,9 @@ void TextEdit::set_text_direction(Control::TextDirection p_text_direction) {
 		} else {
 			dir = (TextServer::Direction)text_direction;
 		}
-		text.set_direction_and_language(dir, (!language.is_empty()) ? language : TranslationServer::get_singleton()->get_tool_locale());
-		text.invalidate_font();
+		const String &lang = language.is_empty() ? TranslationServer::get_singleton()->get_or_add_domain(get_translation_domain())->get_locale() : language;
+		text.set_direction_and_language(dir, lang);
+		text.invalidate_all();
```
Comment (bruvzg) [inline scene/gui/text_edit.cpp:3750]: Probably worth adding argument to this function to avoid unnecessary full invalidation on theme/direction change.

Comment (bruvzg) [reply scene/gui/text_edit.cpp:3750]:
```c++
		case NOTIFICATION_LAYOUT_DIRECTION_CHANGED:
		case NOTIFICATION_THEME_CHANGED: {
			if (is_inside_tree()) {
				_update_caches();
				_update_wrap_at_column(true);
			}
		} break;
		case NOTIFICATION_TRANSLATION_CHANGED: {
			if (is_inside_tree()) {
				_update_caches(true);
				_update_wrap_at_column(true);
			}
		} break;
....
		void TextEdit::_update_caches(bool p_invalidate_all = false) {
....
			if (p_invalidate_all) {
				text.invalidate_all();
			} else {
				text.invalidate_font();
			}
....
		}
```

**Review by bruvzg — APPROVED** [review]

File: scene/gui/code_edit.cpp [hunk 3]
```diff
@@ -188,13 +189,14 @@ void CodeEdit::_notification(int p_what) {
 					code_completion_line_ofs = CLAMP((code_completion_force_item_center < 0 ? code_completion_current_selected : code_completion_force_item_center) - lines / 2, 0, code_completion_options_count - lines);
 					RenderingServer::get_singleton()->canvas_item_add_rect(ci, Rect2(Point2(code_completion_rect.position.x, code_completion_rect.position.y + (code_completion_current_selected - code_completion_line_ofs) * row_height), Size2(code_completion_rect.size.width, row_height)), theme_cache.code_completion_selected_color);
 
+					const String &lang = TranslationServer::get_singleton()->get_or_add_domain(get_translation_domain())->get_locale();
```
Comment (KoBeWi) [inline scene/gui/code_edit.cpp:192]: `TranslationServer::get_singleton()->get_or_add_domain(get_translation_domain())->get_locale()` could be some helper method in Control, it's verbose and repeated everywhere.

File: scene/gui/text_edit.cpp [hunk 4]
```diff
@@ -863,13 +863,18 @@ void TextEdit::_notification(int p_what) {
 		} break;
 
 		case NOTIFICATION_LAYOUT_DIRECTION_CHANGED:
-		case NOTIFICATION_TRANSLATION_CHANGED:
 		case NOTIFICATION_THEME_CHANGED: {
 			if (is_inside_tree()) {
 				_update_caches();
```
Comment (KoBeWi) [inline scene/gui/text_edit.cpp:868]: Technically you could do
```suggestion
				_update_caches(p_what = NOTIFICATION_TRANSLATION_CHANGED);
```

**Comment by timothyqiu** [comment]
Instead of adding `TranslationDomain::get_locale()`, this PR now adds an internal helper method `Object::_get_locale()` to further simplify getting the actual locale.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
