### PR TITLE
OpenXR: Couple of small fixes on the action map

### LINKED ISSUE #90696: openxr_action_map.tres file gets corrupted after restarting the editor with xr/openxr/enabled = false in project settings.
### Tested versions

v4.2.1.stable.official [b09f793f5]
v4.3.dev.custom_build [0043b4edf]

### System information

Windows 11

### Issue description

I'm running into an issue with trying to keep a project both Non-VR and VR at the same time (Ideally would run VR only when calling it to run VR from command line, and most of the time I'd be working on the project and exporting the project with xr/openxr/enabled = false

My problem is that whenever I restart the project with xr/openxr/enabled = false it corrupts the openxr_action_map.tres file somehow.

This is what a corrupted openxr_action_map.tres file looks like:
image
image

And these are the errors that show up in the output log:
image

If I try to run a build that was generated with the broken openxr_action_map.tres file this is what I get on the console:
image

Tagging @BastiaanOlij as requested by them.

### Steps to reproduce

For reproducing the problem exporting isn't necessary at all, here are the steps that reproduce the problem consistently for me:

0 - Make sure you have the OpenXR Vendors plugin installed in the project, the problem can only be reproduced with the openxr vendors plugin installed.
1 - Have a project with a working openxr_action_map (xr/openxr/enabled = true)
2 - Turn off xr/openxr/enabled (xr/openxr/enabled = false)
3 - Restart as requested by the project settings window.
4 - After restarting turn on xr/openxr/enabled (xr/openxr/enabled = true)
5 - Restart as requested by the project settings window.
6 - See errors in output log, go to your openxr_action_map and see it's messed up.
Errors in output log after the last restart following those steps:

image

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by BastiaanOlij**
This PR makes 3 changes:

1. CTRL-S and running your project now saves outstanding changes to the action map
2. Opening the action map resource file no longer looses content if OpenXR is not enabled (important for projects that switch between XR and non-XR modes)
3. Added a bit of documentation on haptic pulses (not really related but ran into it)

Fixes https://github.com/godotengine/godot/issues/90696

### CODE REVIEW

**Review by Mickeon — APPROVED** [review]
> Added a bit of documentation on haptic pulses (not really related but ran into it)

If it's not related it should've been a separate PR but sure.

**Comment by akien-mga** [comment]
> Fixes:
> 
> * #90696

FYI this format doesn't work as closing keyword. "fixes" needs to be adjacent to the issue number it's fixing. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

File: modules/openxr/editor/openxr_action_map_editor.cpp [hunk 1]
```diff
@@ -259,8 +259,14 @@ void OpenXRActionMapEditor::_load_action_map(const String p_path, bool p_create_
 			if (err != OK) {
 				// show warning but continue
 				EditorNode::get_singleton()->show_warning(vformat(TTR("Error saving file %s: %s"), edited_path, error_names[err]));
+			} else {
+				// Reload so it's cached
```
Comment (AThousandShips) [inline modules/openxr/editor/openxr_action_map_editor.cpp:263]:
```suggestion
				// Reload so it's cached.
```

File: modules/openxr/editor/openxr_action_map_editor.cpp [hunk 2]
```diff
@@ -259,8 +259,14 @@ void OpenXRActionMapEditor::_load_action_map(const String p_path, bool p_create_
...
+				action_map = ResourceLoader::load(p_path, "", ResourceFormatLoader::CACHE_MODE_REUSE, &err);
+				if (err != OK) {
+					// show warning but continue
```
Comment (AThousandShips) [inline modules/openxr/editor/openxr_action_map_editor.cpp:266]:
```suggestion
					// Show warning but continue.
```

**Review by akien-mga — APPROVED** [review]

**Comment by DanielSnd** [comment]
This PR has fixed https://github.com/godotengine/godot/issues/90696 for me. I can no longer reproduce the problem using the steps I described on the issue after compiling the engine with this PR.

**Comment by akien-mga** [comment]
Thanks!
