### PR TITLE
Handle changing ItemLists from signals

### LINKED ISSUE #100663: [4.4dev7] Crash occurs shortly after clearing ItemList which contains item metadata
### Tested versions

- v4.4.dev4.mono and before this issue did not occur
- Occurs in v4.4.dev7.mono.official [46c8f8c5c] 

### System information

Godot v4.4.dev7.mono - Pop!_OS 22.04 LTS on X11 - X11 display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XT (RADV NAVI31) - AMD Ryzen 7 5800X3D 8-Core Processor (16 threads)

### Issue description

A fatal error occurs shortly after I clear a ItemList that contains metadata (the data being a custom class that inherits Node), though not immediately on the clear. I've attempted reproducing in a test project with no luck. If I move this clear to a different point in the script it no longer occurs. 

```
Godot Engine v4.4.dev7.mono.official.46c8f8c5c - https://godotengine.org
Vulkan 1.3.274 - Forward+ - Using Device #0: AMD - AMD Radeon RX 7900 XT (RADV NAVI31)
ERROR: Condition "status < 0" is true. Returning: ERR_CANT_OPEN
   at: init_output_device (drivers/alsa/audio_driver_alsa.cpp:90)
WARNING: All audio drivers failed, falling back to the dummy driver.
   at: initialize (servers/audio_server.cpp:247)

WARNING: Godot 3.x SpatialMaterial remapped parameter not found: flags_world_triplanar
   at: _set (scene/resources/material.cpp:3650)
WARNING: Camera2D overridden to physics process mode due to use of physics interpolation.
   at: _update_process_callback (scene/2d/camera_2d.cpp:92)
WARNING: Nodes with non-equal opposite anchors will have their size overridden after _ready(). 
If you want to set size, change the anchors or consider using set_deferred().
   at: _set_size (scene/gui/control.cpp:1443)
WARNING: Nodes with non-equal opposite anchors will have their size overridden after _ready(). 
If you want to set size, change the anchors or consider using set_deferred().
   at: _set_size (scene/gui/control.cpp:1443)
ERROR: FATAL: Index p_index = 0 is out of bounds (size() = 0).
   at: get (./core/templates/cowdata.h:214)

================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.4.dev7.mono.official (46c8f8c5c5874c7c56ea5b1384259de9402d3449)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.11/libcoreclr.so(+0x5dd281) [0x7abd3a9dd281] (??:0)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7abd75a42520] (??:0)
[3] /home/michaelgooch/GameDev/Godot/Godot_Current/Godot_v4.4-dev7_mono_linux.x86_64() [0x2a63c5d] (??:0)
[4] /home/michaelgooch/GameDev/Godot/Godot_Current/Godot_v4.4-dev7_mono_linux.x86_64() [0x28b72ff] (??:0)
[5] /home/michaelgooch/GameDev/Godot/Godot_Current/Godot_v4.4-dev7_mono_linux.x86_64() [0x2910e15] (??:0)
[6] /home/michaelgooch/GameDev/Godot/Godot_Current/Godot_v4.4-dev7_mono_linux.x86_64() [0x2911fb6] (??:0)
[7] /home/michaelgooch/GameDev/Godot/Godot_Current/Godot_v4.4-dev7_mono_linux.x86_64() [0x293debc] (??:0)
[8] /home/michaelgooch/GameDev/Godot/Godot_Current/Godot_v4.4-dev7_mono_linux.x86_64() [0x4dc3cab] (??:0)
[9] /home/michaelgooch/GameDev/Godot/Godot_Current/Godot_v4.4-dev7_mono_linux.x86_64() [0x4ccdbd] (??:0)
[10] /home/michaelgooch/GameDev/Godot/Godot_Current/Godot_v4.4-dev7_mono_linux.x86_64() [0x436da93] (??:0)
[11] /home/michaelgooch/GameDev/Godot/Godot_Current/Godot_v4.4-dev7_mono_linux.x86_64() [0x436f94f] (??:0)
[12] /home/michaelgooch/GameDev/Godot/Godot_Current/Godot_v4.4-dev7_mono_linux.x86_64() [0x4d48f8] (??:0)
[13] /home/michaelgooch/GameDev/Godot/Godot_Current/Godot_v4.4-dev7_mono_linux.x86_64() [0x41d383] (??:0)
[14] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7abd75a29d90] (??:0)
[15] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7abd75a29e40] (??:0)
[16] /home/michaelgooch/GameDev/Godot/Godot_Current/Godot_v4.4-dev7_mono_linux.x86_64() [0x446e6a] (??:0)
-- END OF BACKTRACE --
================================================================
``` 
```gdscript
func add_or_remove_selected_card_holder(target : CardHolder) -> void:
	selected_card_holders.append(target)
	card_holder_target_selected.emit(target)
	targeting_action.set_card_holder_target(selected_card_holders)
	_finish_targeting() #Crashes shortly after here. Script is not really doing anything after this. Nothing touches the item list after this


func _finish_targeting() -> void:
	card_holder_list.clear() #If this is commented out/moved, it no longer crashes. 
	finished_targeting.emit(true)
``` 

### Steps to reproduce

I get the crash 100% in my project in this exact set-up, but can't find a way to reproduce it outside this specific context unfortunately. 

### Minimal reproduction project (MRP)

Haven't been able to make a MRP yet.

### PR DESCRIPTION
**Pull request by hpvb**
When an ItemList changes in response to a UI event on that ItemList we could now potentially have an out of date index into the ItemList cached.

After the signal gets emited we now re-check the index and the state of the list of items.

This fixes #100663

### CODE REVIEW

**Comment by hpvb** [comment]
Copied from the issue:

in `void ItemList::gui_input(const Ref<InputEvent> &p_event)`

we detect what item is clicked by

`int closest = get_item_at_position(mb->get_position(), true);`

But then on line `emit_signal(SNAME("multi_selected"), i, true);`

We emit a signal, and in the project with the error the signal handler for this clears items

So we then

`if (items[i].selectable && select_mode == SELECT_TOGGLE) {`

Which is where the crash happens, at this point the closest value is still set to 1, or 2, but items has been cleared.

**Comment by akien-mga** [comment]
What PR caused the regression? It's easier to assess the fix in context of what made it necessary.

**Comment by hpvb** [comment]
> What PR caused the regression? It's easier to assess the fix in context of what made it necessary.

I will find the pr, and link it again tomorrow, but basically what it did was add this extra if block after the signal. Prior to the pr there was no extra check, so we were not crashing, but sending a bogus index in the signal.

**Comment by hpvb** [comment]
The regression was caused by https://github.com/godotengine/godot/pull/99355 notice how there is a second conditional after the signal fired that was previously not there.

Also notice that without that secondary if block, the data in the second signal was garbage.

**Comment by akien-mga** [comment]
CC @havi05 @KoBeWi

**Comment by havi05** [comment]
I tried to reproduce the error, but wasn't able to do so. (Does this only appear on the mono version?) Clearing all Items when the `multi_selected` signal fired didn't cause any errors on my side. (using 4.4dev7)

I also don't understand how the first if-condition in [line 749](https://github.com/godotengine/godot/pull/100714/files?diff=unified&w=0#diff-8cbdaea96117950192d3baac12f8cff87b2c4598e04e5df1aae4758f5de3b09bR749) can modifiy the list of Items, because it checks if `select_mode != SELECT_TOGGLE` is true and the second (new) one ([line 770](https://github.com/godotengine/godot/pull/100714/files?diff=unified&w=0#diff-8cbdaea96117950192d3baac12f8cff87b2c4598e04e5df1aae4758f5de3b09bR770)) checks the opposite.

_Since I'm on vacation it is difficult for me to debug this, but I will try my best to help you._

**Comment by hpvb** [comment]
@havi05 Sure I can do that too, I think generally we prefer early exits in Godot, that's why it is like this. But I can make it an if/then branch also. 

@KoBeWi @akien-mga any preferences?

File: scene/gui/item_list.cpp [hunk 1]
```diff
@@ -756,6 +756,17 @@ void ItemList::gui_input(const Ref<InputEvent> &p_event) {
 					}
 				}
 
+				// Because the above signal handler might have modified the list of Items, we need to
+				// check if we are empty now, in which case we should not emit a signal with a now
+				// faulty index.
+				if (items.is_empty()) {
+					return;
+				}
```
Comment (KoBeWi) [inline scene/gui/item_list.cpp:764]: This check could be moved to `get_item_at_position()` and return -1.
Then you could return if `i` is -1.

**Comment by KoBeWi** [comment]
tbh the crash can be fixed by just inverting the condition:

`if select_mode == SELECT_TOGGLE && items[i].selectable`

The code currently checks for the opposite thing independently, i.e.
`(items[i].selectable && (!items[i].selected || allow_reselect) && select_mode != SELECT_TOGGLE)
`items[i].selectable && select_mode == SELECT_TOGGLE`
these 2 lines are mutually exclusive, because the mode is either SELECT_TOGGLE or not, so this begs to add an else somewhere.

Or just use the code from havi, it looks cleaner.

Also I'd avoid calling `get_item_at_position()` just in case the user messed the list; it's unnecessary calculation. If the index can be invalidated, just do `ERR_FAIL_INDEX(i, items.size())` with a message that modifying list in signal callback is not supported and you should use a deferred call.

**Comment by hpvb** [comment]
If we don't want to support people changing the selection mode etc from inside the handler then this can be don differently, sure. I will make a revision.

**Comment by hpvb** [comment]
I kind of forgot about this, I'll do a revision soon. Sorry!

**Comment by hpvb** [comment]
@KoBeWi pretty sure this is fixed properly now.

**Review by havi05 — APPROVED** [review]
LGTM.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
