### PR TITLE
Make svg files respect `interface/theme/icon_saturation` setting when imported for editor use

### LINKED ISSUE #96129: Editor Icon Saturation not applied to Custom Editor Icons
### Tested versions

-Reproducible in Godot 4.3

### System information

Windows 11, Godot 4.3-stable

### Issue description

The editor theme icon saturation (`"interface/theme/icon_saturation"`) is only applied to built-in icons, not custom icons set using `@icon("res://...")`.
You can see it on the `ButtonContainer` icons here, notice they're not as saturated as the other Container icons.
image
I based these icons off of the built-in ones and they have the exact same color values.
My Editor saturation is set to 1.8 (because it's pretty ✨) and the difference is pretty apparent.

### Steps to reproduce

Open the MRP, set your Editor Icon Saturation to 2.
The icons should look like this:
image
CustomAnimationPlayer uses the same icon as AnimationPlayer, taken from the godot repo.
It's not saturated correctly, as it's a custom icon.

### Minimal reproduction project (MRP)

[icon-saturation-mrp.zip](https://github.com/user-attachments/files/16752513/icon-saturation-mrp.zip)

### PR DESCRIPTION
**Pull request by hayahane**
Fixes #96129. This pr partially solves the awkward situation of `icon_saturation`.

As already described in #64938, users are asked to restart the editor or manually reimport. I think we should find a better way to deal with this. Maybe a note to ask for a restart or a fully dynamic behaviour.

### CODE REVIEW

File: editor/import/resource_importer_texture.cpp [hunk 1]
```diff
@@ -810,6 +810,10 @@ Error ResourceImporterTexture::import(ResourceUID::ID p_source_id, const String
 		if (err != OK) {
 			WARN_PRINT(vformat("Failed to import an image resource for editor use from '%s'.", p_source_file));
 		} else {
+			// Adjust editor image saturation based on the editor theme.
```
Comment (Mickeon) [inline editor/import/resource_importer_texture.cpp]: Code speaks for itself in my opinion.
```suggestion
```

**Review by fire — APPROVED** [review]
Like the feature enhancement, did not test.

**Comment by hayahane** [comment]
Found a silly mistake, now fixed.
Auto reimport doesn't work right now, will fix it in a follow up pr.

**Comment by Repiteo** [comment]
Thanks!
