### PR TITLE
Fix TileMap Dock button placement and errors

### LINKED ISSUE #114984: TileMapLayer's tool options are far away
### Tested versions

4.6 rc1
This likely comes from the editor's reorganization, CC @lodetrick 

### System information

W10

### Issue description

When you select bucket tool in TileMap, the Contiguous option used to be close to the button:

Image

Now it's on the far right of the toolbar:

Image

It makes it easy to miss.

Same with scattering:

Image

### Steps to reproduce

1. Add TileMapLayer
2. In TileMap dock, select bucket tool

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by lodetrick**
This PR fixes a bug that while on a TileMap in vertical orientation, there was an extra wide control that is visible, increasing the size of the side bar unnecessarily. This PR moves that control to the top where all the other wide controls are.

It also improves the horizontal experience by having the wide controls be in the same place as before #113128 occurred.

Finally it fixes a span of errors when opening and closing the dock repeatedly in vertical orientation.

| Before | After |
| - | - |
|  |  |

*Bugsquad edit:* Fixes #114984

### CODE REVIEW

File: editor/scene/2d/tiles/tile_map_layer_editor.cpp [hunk 1]
```diff
@@ -4413,29 +4420,26 @@ void TileMapLayerEditor::set_show_layer_selector(bool p_show_layer_selector) {
...
 	tile_map_toolbar->set_h_size_flags(is_vertical ? SIZE_SHRINK_BEGIN : SIZE_EXPAND_FILL);
 	tile_map_toolbar->set_v_size_flags(is_vertical ? SIZE_EXPAND_FILL : SIZE_SHRINK_BEGIN);
 
-	main_box_container->move_child(padding_control, is_vertical ? 0 : 3);
+	main_box_container->move_child(padding_control, is_vertical ? 0 : 2);
 
 	if (is_vertical) {
-		tile_map_wide_toolbar->add_child(tabs_bar);
+		tabs_bar->reparent(tile_map_wide_toolbar);
+		layers_selection_button->reparent(tile_map_wide_toolbar);
```
Comment (KoBeWi) [inline editor/scene/2d/tiles/tile_map_layer_editor.cpp]: Why is only the button being reparented, not the whole hbox?

Comment (lodetrick) [reply editor/scene/2d/tiles/tile_map_layer_editor.cpp]: Because each button should be on a different position in the toolbar, if I reparented the box then they would all be together at the end

Comment (KoBeWi) [reply editor/scene/2d/tiles/tile_map_layer_editor.cpp]: ?
Wouldn't they end up next to OptionButton at the top?

Comment (lodetrick) [reply editor/scene/2d/tiles/tile_map_layer_editor.cpp]: Sorry, let me clarify. The tilemap_wide_toolbar is that top row you see in vertical mode. It exists so that the wider controls can live there so side toolbar doesn't become too wide. When in vertical mode this is fine. When swapping to horizontal layout the buttons need to be returned to their original positions on the toolbar.

The line you're looking at is to reparent the option button to the top of the dock in vertical mode. A later line reparents it back to the toolbar when in horizontal layout

Comment (KoBeWi) [reply editor/scene/2d/tiles/tile_map_layer_editor.cpp]: image

I guess there needs to be a different layout for TileMapLayer .-.
image

Comment (lodetrick) [reply editor/scene/2d/tiles/tile_map_layer_editor.cpp]: I see now, that is an improvement. I can just add a check for if its specifically a TileMap

File: editor/scene/2d/tiles/tile_map_layer_editor.cpp [hunk 2]
```diff
@@ -4421,12 +4430,22 @@ void TileMapLayerEditor::set_show_layer_selector(bool p_show_layer_selector) {
 	_update_layers_selector();
 }
 
+void TileMapLayerEditor::_update_layer_selector_layout(bool p_is_vertical) {
+	if (p_is_vertical && show_layers_selector) {
```
Comment (KoBeWi) [inline editor/scene/2d/tiles/tile_map_layer_editor.cpp:4434]: Why `show_layers_selector` is part of this condition? Looks like this method should not be called at all if the selector is invisible.

Comment (lodetrick) [reply editor/scene/2d/tiles/tile_map_layer_editor.cpp:4434]: Because the entire hbox is moved by this (so that the up and down arrows are also on the top with the selector), and so when the selector is hidden, these should go back to their position on the left toolbar rather than remain at the top (ie it prevents below from happening):

**Review by KoBeWi — APPROVED** [review]
