### PR TITLE
Keep editor SceneTree buttons attached to the cell in Right-To-Left

### LINKED ISSUE #102191: Tree buttons don't behave the same in Right to Left
### Tested versions

Godot v4.4.beta1

### System information

Fedora Linux 40 (KDE Plasma) on Wayland - X11 display driver, Multi-window

### Issue description

If tree i set to Right to Left layout direction the buttons in a column doesn't behave the same as in Left to Right direction when scrolling horizontally.

Scene tree in editor in LtR:

https://github.com/user-attachments/assets/f6c079ad-a05b-4ad0-baeb-ef7c52e05ad6

Buttons doesn't move (just a little bit, https://github.com/godotengine/godot/issues/100645) when tree is scrolled. 

Using RtL:

https://github.com/user-attachments/assets/eae1bcb4-db75-4500-850c-81e74967ebe5

See how the buttons doesn't stay visible.

### Steps to reproduce

Change editor to a language with RtL language.
Open a scene with nodes in the scene tree
Change the horizontal scroll position

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by BrotherShort**
Update tree.cpp.
Fix #102191.

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -2177,7 +2177,7 @@ int Tree::draw_item(const Point2i &p_pos, const Point2 &p_draw_ofs, const Size2
 				}
 			}
 
-			if (!rtl && p_item->cells[i].buttons.size()) {
+			if (p_item->cells[i].buttons.size()) {
```
Comment (KoBeWi) [inline scene/gui/tree.cpp:2180]:
```suggestion
			if (!p_item->cells[i].buttons.is_empty()) {
```
Could as well fix the style if you are changing this line.

**Review by KoBeWi — APPROVED** [review]

**Review by KoBeWi — APPROVED** [review]
