### PR TITLE
Fix wrong rotation matrix for orbit z velocity

### LINKED ISSUE #84033: GPU Particles 3D orbit velocity using the Z axis is bugged
### Godot version

v4.2.beta3

### System information

Godot v4.2.beta3 - Windows 10.0.19045 - Vulkan (Forward+, Mobile) - GLES3 (Compatibility) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.4584) - Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 Threads)

### Issue description

The Z axis for orbit velocity seems to have inverted something in the calculations as the particles speed into infinity ~~and beyond~~.

3D Orbit on the Z axis

### Steps to reproduce

The reproduction project has the "main_3d" scene that shows the issue, even in the editor. There is no 2d scene as it uses the X axis for rotation.

### Minimal reproduction project

[GPUParticle3D Orbit Z.zip](https://github.com/godotengine/godot/files/13184185/GPUParticle3D.Orbit.Z.zip)

### LINKED ISSUE #84035: GPU Particles orbit velocities are different between 2D, 3D and documentation on 4.2
### Godot version

v4.2.beta3

### System information

Godot v4.2.beta3 - Windows 10.0.19045 - Vulkan (Forward+, Mobile) - GLES3 (Compatibility) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.4584) - Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 Threads)

### Issue description

Each orbit behaves differently from one another and from the documentation hints.
- **Documentation:** orbits per second
- **Orbit 2D on 4.1.2:** Is the same as in the documentation
- **Orbit 2D on 4.2:** orbits per frame
- **Orbit 3D on 4.2 (new):** degrees per lifetime

They should all behave and display the same thing.

My personal suggestion is for orbit to use **degrees per second**. This is the same as other animated velocities, like Angular, Directional and Radial, that all use degrees/distance per second.

Alternatively, orbit could go back to use **full orbits per second** as to keep compatibility with the previous behavior. But I would suggest keeping Angular and Orbit in sync, as they use the same concept for speed.

I'd also suggest updating the Directional and Radial hints, as they don't tell the speed they use, and I had to estimate. (but I can open a new issue for that, since it's unrelated)

Orbit Speed 3D

### Steps to reproduce

The reproduction project has "main_2d" and "main_3d" scenes that show the difference between them, even in the editor.

### Minimal reproduction project

[GPUParticles Orbit Speed.zip](https://github.com/godotengine/godot/files/13184386/GPUParticles.Orbit.Speed.zip)

### PR DESCRIPTION
**Pull request by QbieShay**
Closes https://github.com/godotengine/godot/issues/84033
Closes https://github.com/godotengine/godot/issues/84035

### CODE REVIEW

**Comment by YuriSizov** [comment]
I'm not an expert, but comparing to this image from Wikipedia, X and Y are also incorrect:



Is this true?

**Comment by QbieShay** [comment]
Maybe this difference is about clockwise and counterclockwise?

File: scene/resources/particle_process_material.cpp [hunk 1]
```diff
@@ -720,7 +720,7 @@ void ParticleProcessMaterial::_update_shader() {
 			code += "	local_pos.z = 0.;\n";
 			code += "	mat3 z_rotation_mat = mat3(\n";
 			code += "		vec3(cos(orbit_velocities.z),-sin(orbit_velocities.z),0.0),\n";
-			code += "		vec3(-sin(orbit_velocities.z),cos(orbit_velocities.z), 0.0),\n";
+			code += "		vec3(sin(orbit_velocities.z),cos(orbit_velocities.z), 0.0),\n";
```
Comment (aaronfranke) [inline scene/resources/particle_process_material.cpp:723]: As far as I can tell, this code is working with columns. Therefore this should be the other way:

```
			code += "		vec3(cos(orbit_velocities.z), sin(orbit_velocities.z), 0.0),\n";
			code += "		vec3(-sin(orbit_velocities.z), cos(orbit_velocities.z), 0.0),\n";
```

(or, if this was rows, then the other two cases need to be swapped)

**Comment by QbieShay** [comment]
I just tested on top of this PR and it seems to all work fine, so i'm not sure if matrices should change ..?

**Comment by aaronfranke** [comment]
@QbieShay What I am certain of is:

* The old code is wrong.
* The change in this PR is also wrong (because it's not consistent with the other cases).

> Or is this because of the coordinate system that we use?

@YuriSizov Fortunately, all coordinate systems agree on rotation: X to Y around Z (not Y to X), Y to Z around X (not X to Z), and Z to X around Y (not X to Z). This is a matter of correctness. The only tricky part is to remember if we are working with rows or columns. Usually code works with columns since it's more geometrically intuitive. I referenced [this wiki page](https://en.wikibooks.org/wiki/GLSL_Programming/Vector_and_Matrix_Operations) which indicates mat3 uses columns (see `// first column (not row!)` and `mat3 n = mat3(column0, column1, column2); // sets columns of matrix n`).

File: scene/resources/particle_process_material.cpp (hunk 1 above)
Comment (kleonc) [reply scene/resources/particle_process_material.cpp:723]: I also checked this and got into the same conclusion, it should be changed as suggested in the above comment.

`z_rotation_mat` as currently in this PR would rotate according to the left-hand-rule, contrary to `x_rotation_mat`/`y_rotation_mat` which both rotate according to the right-hand-rule (which is correct as Godot uses right handed 3D coordinate system).
[Left and Right handed Coordinate Systems with rotations](https://coordinatesystemforgames.blogspot.com/)

**Comment by QbieShay** [comment]
Thanks y'all. I think it's fixed now.

File: scene/resources/particle_process_material.cpp [hunk 2]
```diff
@@ -719,7 +719,7 @@ void ParticleProcessMaterial::_update_shader() {
 			code += "	local_pos -= velocity_pivot;\n";
 			code += "	local_pos.z = 0.;\n";
 			code += "	mat3 z_rotation_mat = mat3(\n";
-			code += "		vec3(cos(orbit_velocities.z),-sin(orbit_velocities.z),0.0),\n";
+			code += "		vec3(cos(orbit_velocities.z),sin(orbit_velocities.z),0.0),\n";
```
Comment (aaronfranke) [inline scene/resources/particle_process_material.cpp:722]: Yes, this is correct, I approve. But I won't click the approve button on the PR, because other changes were added and I am not qualified to approve those.

File: scene/resources/particle_process_material.cpp (hunk 1 above)
Comment (aaronfranke) [reply scene/resources/particle_process_material.cpp]: @kleonc Actually the rotation matrices are the same in both left-hand and right-hand. If you mirror the axes (which switches the handedness), and you also switch hands, the rotation direction is the same.

hands

File: scene/resources/particle_process_material.cpp (hunk 2 above)
Comment (YuriSizov) [reply scene/resources/particle_process_material.cpp:722]: You can approve and say in the comment which part of the PR you're approving, same as you would do if you're only doing a code review without functional testing, or vice versa.

We read those ;)

File: scene/resources/particle_process_material.cpp (hunk 1 above)
Comment (kleonc) [reply scene/resources/particle_process_material.cpp]: > @kleonc Actually the rotation matrices are the same in both left-hand and right-hand. If you mirror the axes (which switches the handedness), and you also switch hands, the rotation direction is the same.

@aaronfranke I think you've misunderstood what I wrote. Yes, right-hand-rule-rotation in right handed coordinate system and left-hand-rule-rotation in left handed coordinate system both have the same rotation matrix. But left-hand-rule-rotation in right handed coordinate system does not, it has a mirrored matrix, just like the `z_rotation_mat` previously in this PR (it would rotate in the opposite direction than it should).

**Review by aaronfranke — APPROVED** [review]
See my comment above.

**Review by clayjohn — COMMENTED** [review]
This looks mostly good to me. Testing it out it seems great. I just caught one additional bug. When using disble_z, we are reading from the ``r`` channel of the orbit_velocity_curve which means if you switch a particle system to disable z (that was orbiting in the z direction then you lose the orbit unless you use the x-channel of the texture, or you switch to a single channel texture.

I recognize there is some tension here in maintaining backwards compatibility as previously users could only use a regular CurveTexture and not a CurveXYZ texture. Further, CurveTexture allows you to only pass a red channel if you want. So we need to adjust the logic to maintain backwards compatibility and make it compatible with CurveXYZTextures

I would change the lines from:
```
if (tex_parameters[PARAM_ORBIT_VELOCITY].is_valid()) {
	code += "   orbit_amount *= texture(orbit_velocity_curve, vec2(lifetime)).r;\n";
}
```
To:
```
if (tex_parameters[PARAM_ORBIT_VELOCITY].is_valid()) {
	CurveTexture *texture = Object::cast_to<CurveTexture>(tex_parameters[PARAM_ORBIT_VELOCITY].ptr());
	if (texture) {
		code += "   orbit_amount *= texture(orbit_velocity_curve, vec2(lifetime)).r;\n";
	} else {
		code += "   orbit_amount *= texture(orbit_velocity_curve, vec2(lifetime)).b;\n";
	}
}
```
This maintains backwards compatibility and allows users to continue using a CurveXYZTexture

**Comment by QbieShay** [comment]
Thanks Clay! Updated and tested.

**Comment by clayjohn** [comment]
Oof, I just realized that checking the type of the texture won't update the MaterialKey as the MaterialKey only checks for the existence of the texture. So we need to add a new flag :(

```

**Comment by QbieShay** [comment]
Updated!

**Review by clayjohn — APPROVED** [review]
Looks great! Tested locally and it works as far as I can tell.

**Comment by akien-mga** [comment]
Thanks!
