### PR TITLE
Fixed inspector not going back to single-node when deselecting an item.

### LINKED ISSUE #22479: The new inspector does not go back to single-node when deselecting an item
**Godot version:**
cb5a62903f9798da8b12f625cbd5a493f14e41d3

**OS/device including version:**
Any

**Issue description:**
The new inspector does not go back to single-node when deselecting an item.
output

### PR DESCRIPTION
**Pull request by Piet-G**
Fixed inspector not going back to single-node when deselecting an item.

Fixes #22479

### CODE REVIEW

File: editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -1587,6 +1587,12 @@ void SceneTreeDock::_selection_changed() {
 	if (selection_size > 1) {
 		//automatically turn on multi-edit
 		_tool_selected(TOOL_MULTI_EDIT);
+	} else {
```
Comment (akien-mga) [inline editor/scene_tree_dock.cpp]: Could maybe save one indentation level with `else if`, no?

Comment (DualMatrix) [reply editor/scene_tree_dock.cpp]: Correct, fixed that.

**Comment by akien-mga** [comment]
Thanks!
