### PR TITLE
DAP: Cast request's `seq` value to int

### LINKED ISSUE #108288: DAP: `request_seq` in responses is a float (regression)
### Tested versions

Reproducible in 4.4, 4.5 beta 2
NOT reproducible in 4.3

### System information

Godot v4.4.stable - Debian GNU/Linux 12 (bookworm) 12 on Wayland - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated AMD Radeon R7 360 Series (RADV BONAIRE) - Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz (4 threads)

### Issue description

I wanted to add DAP support to Zed code editor but encountered an issue. When Zed connects to Godot over TCP, it sends `initialize` command, Godot responds with a success, but Zed fail to parse it and prints `error: deserializing server message`, then disconnects. Upon inspection, it appears that the `request_seq` field in response is a float, but the DAP spec says it should be an integer.

Here are the RPC messages that Zed provides:

```
// Send
{
  "type": "request",
  "seq": 1,
  "command": "initialize",
  "arguments": {
    "clientID": "zed",
    "clientName": "Zed",
    "adapterID": "godot",
    "locale": "en-US",
    "linesStartAt1": true,
    "columnsStartAt1": true,
    "pathFormat": "path",
    "supportsVariableType": true,
    "supportsVariablePaging": false,
    "supportsRunInTerminalRequest": true,
    "supportsMemoryReferences": true,
    "supportsProgressReporting": false,
    "supportsInvalidatedEvent": false,
    "supportsMemoryEvent": false,
    "supportsArgsCanBeInterpretedByShell": false,
    "supportsStartDebuggingRequest": true,
    "supportsANSIStyling": true
  }
}
{
  "type": "request",
  "seq": 2,
  "command": "threads",
  "arguments": {}
}
// Receive
{
  "body": {
    "supportSuspendDebuggee": true,
    "supportTerminateDebuggee": true,
    "supportedChecksumAlgorithms": [
      "MD5",
      "SHA256"
    ],
    "supportsBreakpointLocationsRequest": true,
    "supportsConfigurationDoneRequest": true,
    "supportsEvaluateForHovers": true,
    "supportsRestartRequest": true,
    "supportsSetVariable": true,
    "supportsTerminateRequest": true,
    "supportsValueFormattingOptions": true
  },
  "command": "initialize",
  "request_seq": 1.0,
  "seq": 1,
  "success": true,
  "type": "response"
}
// Send
{
  "type": "request",
  "seq": 3,
  "command": "disconnect",
  "arguments": {
    "restart": false,
    "terminateDebuggee": true,
    "suspendDebuggee": false
  }
}
```

`"request_seq": 1.0` is the issue. In Godot 4.3, this field has a value of `1`, but in Godot 4.4 and later it's `1.0`.

There are only two places where `request_seq` is set (that I could find). Here:

https://github.com/godotengine/godot/blob/3954b2459d2dd7ae75c6a39531869a28ad8a3d5e/editor/debugger/debug_adapter/debug_adapter_parser.cpp#L73

And here:

https://github.com/godotengine/godot/blob/3954b2459d2dd7ae75c6a39531869a28ad8a3d5e/editor/debugger/debug_adapter/debug_adapter_parser.cpp#L83

And the only place where `p_params["seq"]` is set is here:

https://github.com/godotengine/godot/blob/3954b2459d2dd7ae75c6a39531869a28ad8a3d5e/editor/debugger/debug_adapter/debug_adapter_protocol.cpp#L117

And `seq` variable is an int, so I have no idea what the issue is.

UPD: here are zed's logs when using Godot 4.3:

<details>
  <summary>Spoiler</summary>

```
// Send
{
  "type": "request",
  "seq": 1,
  "command": "initialize",
  "arguments": {
    "clientID": "zed",
    "clientName": "Zed",
    "adapterID": "godot",
    "locale": "en-US",
    "linesStartAt1": true,
    "columnsStartAt1": true,
    "pathFormat": "path",
    "supportsVariableType": true,
    "supportsVariablePaging": false,
    "supportsRunInTerminalRequest": true,
    "supportsMemoryReferences": true,
    "supportsProgressReporting": false,
    "supportsInvalidatedEvent": false,
    "supportsMemoryEvent": false,
    "supportsArgsCanBeInterpretedByShell": false,
    "supportsStartDebuggingRequest": true,
    "supportsANSIStyling": true
  }
}
{
  "type": "request",
  "seq": 2,
  "command": "threads",
  "arguments": {}
}
// Receive
{
  "body": {
    "supportSuspendDebuggee": true,
    "supportTerminateDebuggee": true,
    "supportedChecksumAlgorithms": [
      "MD5",
      "SHA256"
    ],
    "supportsBreakpointLocationsRequest": true,
    "supportsConfigurationDoneRequest": true,
    "supportsEvaluateForHovers": true,
    "supportsRestartRequest": true,
    "supportsSetVariable": true,
    "supportsTerminateRequest": true,
    "supportsValueFormattingOptions": true
  },
  "command": "initialize",
  "request_seq": 1,
  "seq": 1,
  "success": true,
  "type": "response"
}
{
  "event": "initialized",
  "seq": 2,
  "type": "event"
}
```

</details>

### Steps to reproduce

I don't have concrete steps to reproduce this issue as it will require installing Rust, building the [zed-gdscript](https://github.com/GDQuest/zed-gdscript) extension locally, installing it, etc. But if people who are familiar with Godot's DAP implementation know what might be the issue here, then maybe these steps won't be necessary. But if not, then I will update this section, but it will be lengthy.

### Minimal reproduction project (MRP)

This is reproducible in new projects.

### PR DESCRIPTION
**Pull request by fstxz**
Closes #108288

### CODE REVIEW

File: editor/debugger/debug_adapter/debug_adapter_protocol.cpp [hunk 1]
```diff
@@ -851,6 +851,11 @@ bool DebugAdapterProtocol::process_message(const String &p_text) {
 	Dictionary params = json.get_data();
 	bool completed = true;
 
+	// workaround for non-compliant DAP/JSON implementations, see #108288
```
Comment (aaronfranke) [inline editor/debugger/debug_adapter/debug_adapter_protocol.cpp]: I'm not sure we need to explicitly say it's a workaround. I'd make the comment something more like:

```
// While JSON does not distinguish floats and ints, "seq" is an integer by specification. See #108288
```

**Review by aaronfranke — APPROVED** [review]

File: editor/debugger/debug_adapter/debug_adapter_protocol.cpp [hunk 2]
```diff
@@ -851,6 +851,11 @@ bool DebugAdapterProtocol::process_message(const String &p_text) {
 	Dictionary params = json.get_data();
 	bool completed = true;
 
+	// While JSON does not distinguish floats and ints, "seq" is an integer by specification. See #108288
```
Comment (AThousandShips) [inline editor/debugger/debug_adapter/debug_adapter_protocol.cpp]:
```suggestion
	// While JSON does not distinguish floats and ints, "seq" is an integer by specification. See https://github.com/godotengine/godot/issues/108288
```

**Comment by Repiteo** [comment]
Thanks!
