### PR TITLE
Fix a performance regression when duplicating a node

### LINKED ISSUE #91230: `Node.duplicate()` runs about twice as slow since node property duplication fix
### Tested versions

- Reproducible in: 4.3.dev5
- Not reproducible in: 4.2.1.stable

### System information

Godot v4.3.dev (b091162a9) - Fedora Linux 39 (KDE Plasma) - X11 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4090 (nvidia; 545.29.06) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

`Node.duplicate()` runs about twice as slow since node property duplication fix, even on a plain Node with no properties or metadata set.

### Before the fix

```
Iteration 0: 48.979 MB
Iteration 1: 48.984 MB
Iteration 2: 48.994 MB
Iteration 3: 49.014 MB
Iteration 4: 49.054 MB
Iteration 5: 49.132 MB
Iteration 6: 49.290 MB
Iteration 7: 49.606 MB
Iteration 8: 50.266 MB
Iteration 9: 51.588 MB
Iteration 10: 54.099 MB
Iteration 11: 59.252 MB
Iteration 12: 69.558 MB
Iteration 13: 90.169 MB
Iteration 14: 131.391 MB
Iteration 15: 213.836 MB
Done running in 3571 milliseconds.
```

### After the fix

```
Iteration 0: 40.596 MB
Iteration 1: 40.601 MB
Iteration 2: 40.611 MB
Iteration 3: 40.631 MB
Iteration 4: 40.671 MB
Iteration 5: 40.749 MB
Iteration 6: 40.907 MB
Iteration 7: 41.221 MB
Iteration 8: 41.881 MB
Iteration 9: 43.203 MB
Iteration 10: 45.714 MB
Iteration 11: 50.867 MB
Iteration 12: 61.173 MB
Iteration 13: 81.784 MB
Iteration 14: 123.006 MB
Iteration 15: 205.451 MB
Done running in 5207 milliseconds.
```

I bisected the regression to 9851c1bdd893a6194fdbf1820d2fa07449d4f9fb (https://github.com/godotengine/godot/pull/87387).

cc @warriormaster12

### Steps to reproduce

- Use `Node.duplicate()` thousands of times in a project or more in a quick succession. The performance difference is noticeable in both debug and release builds.

### Minimal reproduction project (MRP)

[test_alloc_duplicate.zip](https://github.com/godotengine/godot/files/15135522/test_alloc_duplicate.zip)

### LINKED ISSUE #91461: Crash when duplicating instantiated scene that removes child node in `_enter_tree`
### Tested versions

Does **not** happen in 4.3-dev5
Happens in 4.3-dev6

### System information

Godot v4.3.dev6 - Ubuntu 23.10 23.10 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 () - Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 Threads)

### Issue description

My game crashes with the following error message:
```
Godot Engine v4.3.dev6.official.64520fe67 - https://godotengine.org
Vulkan 1.3.242 - Forward+ - Using Device #1: NVIDIA - NVIDIA GeForce GTX 1650

ERROR: Index p_index = 7 is out of bounds ((int)data.children_cache.size() = 7).
   at: get_child (scene/main/node.cpp:1684)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.3.dev6.official (64520fe6741d8ec3c55e0c9618d3fadcda949f63)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42990) [0x7b67bfc42990] (??:0)
[2] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x429b1a1] (??:0)
[3] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x4871256] (??:0)
[4] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x487132b] (??:0)
[5] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x238816e] (??:0)
[6] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x2334236] (??:0)
[7] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x7e4821] (??:0)
[8] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x6c2be1] (??:0)
[9] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x69abd2] (??:0)
[10] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x4247c9f] (??:0)
[11] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x7d6ec9] (??:0)
[12] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x6c2be1] (??:0)
[13] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x423542f] (??:0)
[14] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x408195f] (??:0)
[15] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x7e2ee4] (??:0)
[16] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x6c2be1] (??:0)
[17] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x423542f] (??:0)
[18] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x408195f] (??:0)
[19] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x7e2ee4] (??:0)
[20] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x6c2be1] (??:0)
[21] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x2318742] (??:0)
[22] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x43c685] (??:0)
[23] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x4216a88] (??:0)
[24] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x2329174] (??:0)
[25] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x23650d3] (??:0)
[26] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x2370790] (??:0)
[27] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x526ab3] (??:0)
[28] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x420042] (??:0)
[29] /lib/x86_64-linux-gnu/libc.so.6(+0x28150) [0x7b67bfc28150] (??:0)
[30] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x89) [0x7b67bfc28209] (??:0)
[31] /home/user/Godot_v4.3-dev6_linux.x86_64() [0x43aaba] (??:0)
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

Run the MRP

### Minimal reproduction project (MRP)

[s11d-gdproj.zip](https://github.com/godotengine/godot/files/15191320/s11d-gdproj.zip)

### PR DESCRIPTION
**Pull request by warriormaster12**
@Calinou reported a performance regression when duplicating empty node so I fixed it by moving all property duplication away from ```duplicate```to ```_duplicate_properties``` function so that we wouldn't loop through them twice. 

Fixes: https://github.com/godotengine/godot/issues/91230

Duplicating empty node now takes on my Macbook 1336 milliseconds compared to before (2246 milliseconds).
```
Iteration 0: 60.805 MB
Iteration 1: 60.811 MB
Iteration 2: 60.819 MB
Iteration 3: 60.839 MB
Iteration 4: 60.879 MB
Iteration 5: 60.958 MB
Iteration 6: 61.115 MB
Iteration 7: 61.430 MB
Iteration 8: 62.090 MB
Iteration 9: 63.412 MB
Iteration 10: 65.923 MB
Iteration 11: 71.076 MB
Iteration 12: 81.382 MB
Iteration 13: 101.994 MB
Iteration 14: 143.217 MB
Iteration 15: 225.661 MB
Done running in 1336 milliseconds.
```

~~Edit: Should also fix https://github.com/godotengine/godot/issues/91461~~

### CODE REVIEW

**Comment by akien-mga** [comment]
For the record, your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

See which "email" you have configured currently: https://github.com/godotengine/godot/pull/91329.patch

**Comment by warriormaster12** [comment]
Ah yes, I pushed from my work laptop since it was the only thing that I had with. I’ll change it.

**Comment by warriormaster12** [comment]
@KoBeWi I guess, this pr should be merged first:
https://github.com/godotengine/godot/pull/91677

File: scene/main/node.cpp [hunk 1]
```diff
@@ -2897,34 +2859,58 @@ void Node::remap_nested_resources(Ref<Resource> p_resource, const HashMap<Ref<Re
...
+		Variant scr = p_original->get(script_property_name, &is_valid);
+		if (is_valid) {
+			p_copy->set(script_property_name, scr);
+		}
+	}
 	for (const PropertyInfo &E : props) {
 		if (!(E.usage & PROPERTY_USAGE_STORAGE)) {
 			continue;
 		}
 		String name = E.name;
```
Comment (KoBeWi) [inline scene/main/node.cpp:2880]: The `name` is used for StringName arguments, so it's better to convert it.
```suggestion
		const StringName name = E.name;
```

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by MangiameliFabio** [comment]
We encountered a bug in this code. When copying typed arrays the content is not copied and we only receive an empty array. We fixed this by moving `p_copy->set(name, value)` out of the if statement.

The fix looks like this:

```C++
if (value.get_type() == Variant::OBJECT) {
        Node *property_node = Object::cast_to<Node>(value);
	Variant out_value = value;
	if (property_node && (p_root == property_node || p_root->is_ancestor_of(property_node))) {
		out_value = p_copy->get_node_or_null(p_original->get_path_to(property_node));
	}
} else if (value.get_type() == Variant::ARRAY) {
	Array arr = value;
	if (arr.get_typed_builtin() == Variant::OBJECT) {
		for (int i = 0; i < arr.size(); i++) {
			Node *property_node = Object::cast_to<Node>(arr[i]);
			if (property_node && (p_root == property_node || p_root->is_ancestor_of(property_node))) {
			arr[i] = p_copy->get_node_or_null(p_original->get_path_to(property_node));
			}
		}
	        value = arr;
	}
}
p_copy->set(name, `value);`
```

**Comment by warriormaster12** [comment]
@MangiameliFabio what is the content type? If the variable type is Node have you checked that Nodepath is correct?

**Comment by MangiameliFabio** [comment]
We are using a typed array of string. When you follow the if case in your code you can see that `p_copy->set(name, value);` is not called because `arr.get_typed_builtin() == Variant::OBJECT` will be false.

https://github.com/godotengine/godot/blob/e96ad5af98547df71b50c4c4695ac348638113e0/scene/main/node.cpp#L2895-L2909

**Comment by warriormaster12** [comment]
Aight I see. Does your solution work with variables with node type? If not then you should modify your solution to work with both (add ```p_copy->set``` back into if and else if statements).

**Comment by MangiameliFabio** [comment]
Yes, node type is also working. `p_copy->set(name, value)` needs to be executed every time like it was before this PR. We are using the code from my first comment in our game Halls of Torment and didn't experience any further problems with duplication. (We are duplicating a lot :P) 

See this commit, `p_copy->set(name, value)` is out of the if bracket
https://github.com/ChasingCarrots/godot/commit/92939f2e97c56f534df5a2cb5add9383c3be1a77

**Comment by warriormaster12** [comment]
@MangiameliFabio huh, I guess there's no longer a purpose for if & else if statements. Just make a new pr I guess :)

**Comment by MangiameliFabio** [comment]
I discussed this a bit further and am unsure what the correct fix is. Executing `p_copy->set(name, value)` outside the if statemnt could possible set the value in to many occasions. So I won't open a pr as I simply don't know enough about the whole system.

**Comment by warriormaster12** [comment]
The behavior used to be your way where there weren't any if-statements and it would just set a value. My guess is that it might have something todo with this pr: https://github.com/godotengine/godot/pull/92095 for making if/else if unnecessary.

I'd say that it is worth it to open up a pr if:

a) it fixes issues with non node type typed arrays

b)  no other issues are present with other data types, resources and nodes.

**Comment by warriormaster12** [comment]
@KoBeWi could you take a look at this? I don't currently have that much time to look at this myself.
