### PR TITLE
Fix gltf import generate_scene() option

### LINKED ISSUE #73325: Crash previewing .blend file for import.
### Godot version

v4.0.rc.custom_build [b5549a871]

### System information

Windows 10, Forward+

### Issue description

Double clicking on a blend file (attached below) crashes the editor.

Call stack:
```
 	godot.windows.editor.x86_64.exe!HashMap<StringName,Variant,HashMapHasherDefault,HashMapComparatorDefault<StringName>,DefaultTypedAllocator<HashMapElement<StringName,Variant>>>::operator[](const StringName & p_key) Line 504	C++
>	godot.windows.editor.x86_64.exe!EditorSceneFormatImporterBlend::import_scene(const String & p_path, unsigned int p_flags, const HashMap<StringName,Variant,HashMapHasherDefault,HashMapComparatorDefault<StringName>,DefaultTypedAllocator<HashMapElement<StringName,Variant>>> & p_options, List<String,DefaultAllocator> * r_missing_deps, Error * r_err) Line 217	C++
 	godot.windows.editor.x86_64.exe!ResourceImporterScene::pre_import(const String & p_source_file, const HashMap<StringName,Variant,HashMapHasherDefault,HashMapComparatorDefault<StringName>,DefaultTypedAllocator<HashMapElement<StringName,Variant>>> & p_options) Line 2299	C++
 	godot.windows.editor.x86_64.exe!SceneImportSettings::open_settings(const String & p_path, bool p_for_animation) Line 593	C++
 	godot.windows.editor.x86_64.exe!FileSystemDock::_select_file(const String & p_path, bool p_select_in_favorites) Line 1011	C++
 	godot.windows.editor.x86_64.exe!FileSystemDock::_tree_activate_file() Line 1071	C++
 	godot.windows.editor.x86_64.exe!Callable::callp(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 51	C++
 	godot.windows.editor.x86_64.exe!Object::emit_signalp(const StringName & p_name, const Variant * * p_args, int p_argcount) Line 1047	C++
 	godot.windows.editor.x86_64.exe!Object::emit_signal<>(const StringName & p_name) Line 869	C++
 	godot.windows.editor.x86_64.exe!Tree::gui_input(const Ref<InputEvent> & p_event) Line 3691	C++
 	godot.windows.editor.x86_64.exe!Control::_call_gui_input(const Ref<InputEvent> & p_event) Line 1747	C++
 	godot.windows.editor.x86_64.exe!Viewport::_gui_call_input(Control * p_control, const Ref<InputEvent> & p_input) Line 1373	C++
 	godot.windows.editor.x86_64.exe!Viewport::_gui_input_event(Ref<InputEvent> p_event) Line 1599	C++
 	godot.windows.editor.x86_64.exe!Viewport::push_input(const Ref<InputEvent> & p_event, bool p_local_coords) Line 2816	C++
 	godot.windows.editor.x86_64.exe!Window::_window_input(const Ref<InputEvent> & p_ev) Line 1366	C++
 	[Inline Frame] godot.windows.editor.x86_64.exe!call_with_variant_args_helper(Window *) Line 293	C++
 	[Inline Frame] godot.windows.editor.x86_64.exe!call_with_variant_args(Window * p_instance, void(Window::*)(const Ref<InputEvent> &) p_method, const Variant * *) Line 407	C++
 	godot.windows.editor.x86_64.exe!CallableCustomMethodPointer<Window,Ref<InputEvent> const &>::call(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 104	C++
 	godot.windows.editor.x86_64.exe!Callable::callp(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 51	C++
 	godot.windows.editor.x86_64.exe!DisplayServerWindows::_dispatch_input_event(const Ref<InputEvent> & p_event) Line 2314	C++
 	godot.windows.editor.x86_64.exe!Input::_parse_input_event_impl(const Ref<InputEvent> & p_event, bool p_is_emulated) Line 690	C++
 	godot.windows.editor.x86_64.exe!Input::flush_buffered_events() Line 941	C++
 	godot.windows.editor.x86_64.exe!DisplayServerWindows::process_events() Line 2008	C++
 	godot.windows.editor.x86_64.exe!OS_Windows::run() Line 1296	C++
 	godot.windows.editor.x86_64.exe!widechar_main(int argc, wchar_t * * argv) Line 181	C++
 	godot.windows.editor.x86_64.exe!_main() Line 205	C++
 	godot.windows.editor.x86_64.exe!main(int argc, char * * argv) Line 217	C++
 	[Inline Frame] godot.windows.editor.x86_64.exe!invoke_main() Line 102	C++
 	godot.windows.editor.x86_64.exe!__scrt_common_main_seh() Line 288	C++
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown
```

Crashes on this CRASH_COND::
```
	const TValue &operator[](const TKey &p_key) const {
		uint32_t pos = 0;
		bool exists = _lookup_pos(p_key, pos);
		CRASH_COND(!exists);
		return elements[pos]->data.value;
	}
```

Looks like maybe we're trying to look up animation options that don't exist?
```
return gltf->generate_scene(state, (float)p_options["animation/fps"], (bool)p_options["animation/trimming"], (bool)p_options["animation/remove_immutable_tracks"]);
```

animation/remove_immutable_tracks is not in my .import file, so maybe that's causing the issue.

### Steps to reproduce

I couldn't get this to reproduce with a fresh project, as it keeps reimporting the .blend file.  I think you have to open the project with an older version of Godot 4, let it import, then use the newer version.

Reimporting the .blend file on the project I was having issues with fixed the crash.  Pretty sure it was just that property missing from the .import file.

### Minimal reproduction project

[test_blend_import_crash.zip](https://github.com/godotengine/godot/files/10738450/test_blend_import_crash.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
Fixes #73325.

Added checks for fbx and blend.

@jitspoe Please test if this is OK, as your MRP could not be opened in the first place.

### CODE REVIEW

File: modules/gltf/editor/editor_scene_importer_blend.cpp [hunk 1]
```diff
@@ -214,7 +214,19 @@ Node *EditorSceneFormatImporterBlend::import_scene(const String &p_path, uint32_
...
+	if (!opt.has("animation/trimming")) {
+		opt.insert("animation/trimming", false);
+	}
+	if (!opt.has("animation/remove_immutable_tracks")) {
+		opt.insert("animation/remove_immutable_tracks", true);
+	}
+	return gltf->generate_scene(state, (float)opt["animation/fps"], (bool)opt["animation/trimming"], (bool)opt["animation/remove_immutable_tracks"]);
+#else
 	return gltf->generate_scene(state, (float)p_options["animation/fps"], (bool)p_options["animation/trimming"], (bool)p_options["animation/remove_immutable_tracks"]);
+#endif
```
Comment (akien-mga) [inline modules/gltf/editor/editor_scene_importer_blend.cpp:229]: Seems fine overall, but isn't it a bit wasteful memory wise to copy the hashmap each time, when what we need is just two booleans?

It could be:
```suggestion
	bool trimming = p_options.has("animation/trimming") ? (bool)p_options["animation/trimming"] : false;
	bool remove_immutable = p_options.has("animation/remove_immutable_tracks") ? (bool)p_options["animation/remove_immutable_tracks"] : true;
	return gltf->generate_scene(state, (float)p_options["animation/fps"], trimming, remove_immutable);
```

Comment (TokageItLab) [reply modules/gltf/editor/editor_scene_importer_blend.cpp:229]: Good point...

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
