### PR TITLE
Fix global classes can't be used in the Evaluator

### LINKED ISSUE #99004: Evaluator has no access to autoload singletons
### Tested versions

4.4 dev4

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When you try to access autoload singleton via evaluator, you will get error `Invalid named index 'AutoloadName' for base type Object`
The workaround is to access it by path `get_node(/root/AutoloadName` (if you are inside Node script)

### Steps to reproduce

1. Add autoload singleton
2. Run a script with breakpoint
3. Type the autoloat's name in the Debugger's Evaulator

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #103963: Debugger's evaluator returns null when using enums from different script
### Tested versions

Reproducible in v4.4.stable.official [4c311cbee]

### System information

Godot v4.4.stable - macOS Sequoia (15.0.1) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon Pro 5300M - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 threads)

### Issue description

Debugger evaulator returns null when trying to evaluate enums from another script. The code and the if statements works as expected when running the program, but in this example the evaluator cannot be used to determine path taken in execution in "OtherNode" script.

Example code with two nodes & scripts:

```gdscript
class_name EnumNode
extends Node2D

enum Numbs {
	ONE,
	TWO
}

func _init() -> void:
	var evaluator_success : Numbs = Numbs.ONE
	if evaluator_success == Numbs.ONE :
		print("all good, evaluator works fine here")
		# place breakpoint on line with if statement
		# try evaulating EnumNode.Numbs.ONE or evaluator_success == EnumNode.Numbs.ONE and you'll get correct results
```

```gdscript
class_name OtherNode
extends Node2D

func _init() -> void:
	var fails = EnumNode.Numbs.ONE
	if fails == EnumNode.Numbs.ONE :
		print("this is printed, but debugger evaluator fails to check if statement")
		# place breakpoint on line with if statement
		# try evaulating EnumNode.Numbs.ONE or fails == EnumNode.Numbs.ONE and you'll get null
```

### Steps to reproduce

Set debugger breakpoint and evaluate expressions with enums. See the different behaviour depending on if the enum is in the same script or not.

### Minimal reproduction project (MRP)

[enum_evaluate_debugger_bug_repro.zip](https://github.com/user-attachments/files/19180111/enum_evaluate_debugger_bug_repro.zip)

### PR DESCRIPTION
**Pull request by ydeltastar**
- Fixes https://github.com/godotengine/godot/issues/103963
- Fixes https://github.com/godotengine/godot/issues/99004

Makes built-in, user-defined, and autoload classes available for static access in the Evaluator.

### CODE REVIEW

File: core/debugger/remote_debugger.cpp [hunk 1]
```diff
@@ -541,23 +541,43 @@ void RemoteDebugger::debug(bool p_can_continue, bool p_is_error_breakpoint) {
...
+					input_names.append(E);
+					input_vals.append(Engine::get_singleton()->get_singleton_object(E));
+				}
+
+				List<StringName> globals;
+				ScriptServer::get_global_class_list(&globals);
+				for (const StringName &S : globals) {
+					String scr_path = ScriptServer::get_global_class_path(S);
+					Ref<Script> scr = ResourceLoader::load(scr_path, "Script");
+					ERR_CONTINUE_MSG(scr.is_null(), vformat("Could not load the global class %s from resource path: %s", S, scr_path));
```
Comment (AThousandShips) [inline core/debugger/remote_debugger.cpp]:
```suggestion
					ERR_CONTINUE_MSG(scr.is_null(), vformat(R"(Could not load the global class %s from resource path: "%s".)", S, scr_path));
```

**Comment by artturipi** [comment]
Hmm, why no review? 🤔
This makes the evaluator that much more useful in tracking down unexpected code behaviour. How can I vote on the issue?

**Comment by AThousandShips** [comment]
People have been busy with other bugs, and there are few members of the debugger team and at least one is not very active right now AFAIK

**Review by Calinou — APPROVED** [review]
Tested locally with autoloads and a static variable in `class_name`, it works as expected. Code looks good to me.

**Testing project:** [test_evaluator_global.zip](https://github.com/user-attachments/files/20657317/test_evaluator_global.zip)

Try to evaluate `Example.variable` and `ClassName.variable` in the testing project. Previously, both would have returned `null`:

image

File: core/debugger/remote_debugger.cpp (hunk 1 above)
Comment (Calinou) [reply core/debugger/remote_debugger.cpp]: We tend to use double quotes in new messages (many existing messages use single quotes, but we should modify them eventually).

**Comment by Repiteo** [comment]
Thanks!
