### PR TITLE
Fix selection in 3D Game view

### LINKED ISSUE #98997: Selection in Game view stops working correctly when using in-game camera override feature
### Tested versions

v4.4.dev4.official [36e6207bb]

### System information

Godot v4.4.dev4 - Windows 10.0.19045 - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 980 Ti (NVIDIA; 32.0.15.6603) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 threads)

### Issue description

Selection in new Game view (#97257) sometimes stops working correctly when using "Override the in-game camera" feature:

https://github.com/user-attachments/assets/69dc2c95-fbb2-4b41-9c43-88e40fa2042d

I had this happen with 2D selection as well, but I did something to fix it. Maybe switching back and forth between 2D and 3D selection fixed it?

### Steps to reproduce

I have not been able to reproduce this yet. I will update this issue if I'm able to find a way to reproduce it.

### Minimal reproduction project (MRP)

I was using https://github.com/allenwp/calinou-godot-demo-projects/tree/add-color-correction-demo at the time of discovering this issue, but I suspect this project has nothing to do with the issue.

### PR DESCRIPTION
**Pull request by Hilderin**
- Fixes #98997

This PR should fix the issue for the selection in 3D. I was no able to reproduce the issue in 2D.

The problem was the calculation of the distance between the raycast collision point and the camera position. Since the camera position and the raycast hit point are in global space, we don't need to apply any other transformation to calculate the distance between them.

In addition, the selection did not work on CSG if collision is not enabled. I added support for CSGShape without collision.

Exemple:

https://github.com/user-attachments/assets/aafe6c5a-ad36-494d-aaed-3a8dc313f617

There's a little MRP project to test:
[test-godot-select-game-workspace.zip](https://github.com/user-attachments/files/18367196/test-godot-select-game-workspace.zip)

### CODE REVIEW

**Comment by Hilderin** [comment]
CC @YeldhamDev

**Review by YeldhamDev — APPROVED** [review]
LGTM.

File: scene/debugger/scene_debugger.cpp [hunk 1]
```diff
@@ -39,6 +39,7 @@
 #include "scene/2d/physics/collision_polygon_2d.h"
 #include "scene/2d/physics/collision_shape_2d.h"
 #ifndef _3D_DISABLED
+#include "modules/csg/csg_shape.h"
```
Comment (akien-mga) [inline scene/debugger/scene_debugger.cpp:42]: This breaks encapsulation of the CSG module, which should be (as far as possible) self-contained.

But looking at how many 3D nodes are included explicitly here, it seems to be an architectural issue that would prevent users from adding new 3D nodes via modules or extension that could be interacted with in the scene debugger, without forking the engine to modify this here file. That's a problem :/

Comment (YeldhamDev) [reply scene/debugger/scene_debugger.cpp:42]: A solution for this would be having `generate_triangle_mesh()` be implemented in `GeometryInstance3D`, and have it be overridable.

Comment (clayjohn) [reply scene/debugger/scene_debugger.cpp:42]: Could we consider just using the object's AABB? Then we don't need to generate the collision mesh

Comment (Hilderin) [reply scene/debugger/scene_debugger.cpp:42]: I think it's an excellent idea. It should works event for particle system. I'll try.

Comment (Hilderin) [reply scene/debugger/scene_debugger.cpp:42]: Ok, it works, but the behavior is a bit different then the selection in the editor. See on this screenshot, in the editor, it select the ground but with AABB, it select the mesh.
image

I think the previous selection using the collision mesh was more precise and what the user expects.

Comment (Hilderin) [reply scene/debugger/scene_debugger.cpp]: I added `generate_triangle_mesh()` in `GeometryInstance3D` and implemented overrides in `CSGShape`, `Label3D`, `MeshInstance3D` and `SpriteBase3D`.

**Review by akien-mga — APPROVED** [review]
That looks much cleaner architecture wise!

File: scene/debugger/scene_debugger.cpp [hunk 2]
```diff
@@ -1920,43 +1918,27 @@ void RuntimeNodeSelect::_find_3d_items_at_pos(const Point2 &p_pos, Vector<Select
 	}
 
 	// Then go for the meshes.
+	print_line(vformat("camera position: %s", pos));
```
[the remark this answers is not in the document]
Comment (Hilderin) [reply scene/debugger/scene_debugger.cpp]: Oups!! :)
It's removed.

File: scene/3d/label_3d.h [hunk 3]
```diff
@@ -253,7 +253,7 @@ class Label3D : public GeometryInstance3D {
 	StandardMaterial3D::TextureFilter get_texture_filter() const;
 
 	virtual AABB get_aabb() const override;
-	Ref<TriangleMesh> generate_triangle_mesh() const;
+	Ref<TriangleMesh> generate_triangle_mesh() const override;
```
Comment (AThousandShips) [inline scene/3d/label_3d.h:256]:
```suggestion
	virtual Ref<TriangleMesh> generate_triangle_mesh() const override;
```
This *should* have triggered a build error, unsure why it didn't

File: modules/csg/csg_shape.h [hunk 4]
```diff
@@ -169,6 +169,8 @@ class CSGShape3D : public GeometryInstance3D {
 	Ref<ArrayMesh> bake_static_mesh();
 	Ref<ConcavePolygonShape3D> bake_collision_shape();
 
+	Ref<TriangleMesh> generate_triangle_mesh() const override;
```
Comment (AThousandShips) [inline modules/csg/csg_shape.h:172]:
```suggestion
	virtual Ref<TriangleMesh> generate_triangle_mesh() const override;
```

File: scene/3d/mesh_instance_3d.h [hunk 5]
```diff
@@ -104,6 +104,8 @@ class MeshInstance3D : public GeometryInstance3D {
 	Ref<ArrayMesh> bake_mesh_from_current_blend_shape_mix(Ref<ArrayMesh> p_existing = Ref<ArrayMesh>());
 	Ref<ArrayMesh> bake_mesh_from_current_skeleton_pose(Ref<ArrayMesh> p_existing = Ref<ArrayMesh>());
 
+	Ref<TriangleMesh> generate_triangle_mesh() const override;
```
Comment (AThousandShips) [inline scene/3d/mesh_instance_3d.h:107]:
```suggestion
	virtual Ref<TriangleMesh> generate_triangle_mesh() const override;
```

File: scene/3d/sprite_3d.h [hunk 6]
```diff
@@ -172,7 +172,7 @@ class SpriteBase3D : public GeometryInstance3D {
 
 	virtual AABB get_aabb() const override;
 
-	Ref<TriangleMesh> generate_triangle_mesh() const;
+	Ref<TriangleMesh> generate_triangle_mesh() const override;
```
Comment (AThousandShips) [inline scene/3d/sprite_3d.h:175]:
```suggestion
	virtual Ref<TriangleMesh> generate_triangle_mesh() const override;
```

**Review by AThousandShips — APPROVED** [review]

File: scene/3d/label_3d.h (hunk 3 above)
Comment (Hilderin) [reply scene/3d/label_3d.h]: Good eye as usual :)
Done!

File: scene/3d/sprite_3d.h (hunk 6 above)
Comment (Hilderin) [reply scene/3d/sprite_3d.h]: Done!

**Comment by akien-mga** [comment]
Thanks!
