### PR TITLE
Remove Compatibility RenderTarget backbuffer size limit

### LINKED ISSUE #114899: Compatibility renderer: CanvasGroup turns black when it is the child of a SubViewport that is less than 41px in width or height
### Tested versions

Reproducible in v4.5.1.stable

### System information

Godot v4.5.1.stable - Windows 10 - OpenGL 3 (Compatibility) - NVIDIA GeForce GTX 1070

### Issue description

When using the Compatibility renderer, when either the width or height of a SubViewport is less than 41px, a CanvasGroup placed within it will turn completely black. See also #74622 

### Steps to reproduce

Make sure you are using Compatibility. Add a SubViewportContainer to the scene, to visualize the effect. Add a SubViewport that is 40px or less in width or height as a child of the SubViewportContainer. Add a CanvasGroup as a child of the SubViewport, and put something in the CanvasGroup as well (A Sprite2D or a ColorRect for example). Notice how the CanvasGroup turns black.

### Minimal reproduction project (MRP)

[px40_mrp_4.5.1.stable.zip](https://github.com/user-attachments/files/24572266/px40_mrp_4.5.1.stable.zip)

Screenshot

### PR DESCRIPTION
**Pull request by LucaTuerk**
Fixes #114899

**The Issue:**
The Compatibility Renders Texture Storage imposes a size limit of 41x41 when creating the back buffer for a RenderTarget. According to https://github.com/godotengine/godot/issues/114899#issuecomment-3750058511 this is intended to ensure no mipmaps are generated for these small buffers, however the base level is also not generated.

**The Fix:**
The limit is removed, as the function already correctly accounts for the case where only the base level is generated. Additionally an error is instead thrown at the top of the method is the RenderTargets size is invalid. This case should not happen.

**For the MRP linked in the issue this is the result:**
image

Is is possible to reduce the SubViewports size up to 2x2 with correct rendering. I assume this is the limit imposed by the size property but did not investigate further.

### CODE REVIEW

File: drivers/gles3/storage/texture_storage.cpp [hunk 1]
```diff
@@ -2489,57 +2489,57 @@ void TextureStorage::_update_render_target_velocity(RenderTarget *rt) {
...
-		GLenum status = glCheckFramebufferStatus(GL_FRAMEBUFFER);
-		if (status != GL_FRAMEBUFFER_COMPLETE) {
-			WARN_PRINT_ONCE("Cannot allocate mipmaps for canvas screen blur. Status: " + get_framebuffer_error(status));
-			glBindFramebuffer(GL_FRAMEBUFFER, system_fbo);
-			return;
-		}
-		GLES3::Utilities::get_singleton()->texture_allocated_data(rt->backbuffer, texture_size_bytes, "Render target backbuffer color texture");
+	GLenum status = glCheckFramebufferStatus(GL_FRAMEBUFFER);
+	if (status != GL_FRAMEBUFFER_COMPLETE) {
+		WARN_PRINT_ONCE("Cannot allocate RenderTarget backbuffer. Status: " + get_framebuffer_error(status));
```
Comment (LucaTuerk) [inline drivers/gles3/storage/texture_storage.cpp:2524]: I changed this error message as the function is not exclusively called by canvas screen blur and could be misleading.

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected (including with viewport sizes as low as 2×2, the lowest allowed size in the inspector). Code looks good to me.

Image

**Comment by Repiteo** [comment]
Thanks!
