### PR TITLE
Fix `Range`-derived nodes not redrawing after `set_value_no_signal`

### LINKED ISSUE #70821: SpinBox doesn't visually update when calling `set_value_no_signal`
### Godot version

v4.0.beta10.official.d0398f62f

### System information

Windows 10, gl_compatibility

### Issue description

If you use `set_value_no_signal` on a SpinBox, it doesn't redraw until clicked.

### Steps to reproduce

1. Add SpinBox to scene.
2. `set_value_no_signal(50)` # Value displayed doesn't change
3. Click it. Displayed value changed to 50.

### Minimal reproduction project

[spinbox redraw bug.zip](https://github.com/godotengine/godot/files/10329572/spinbox.redraw.bug.zip)

### PR DESCRIPTION
**Pull request by pattlebass**
Edit:
Everything seems to be correct now, including "shared" ranges.

`SpinBox` used to call `_value_changed(0)` to set the underlying Label's text. I moved that code in a new function `_update_text()`.

The project I used for testing:
[Range-test.zip](https://github.com/godotengine/godot/files/10338634/Range-test.zip)

Fixes #70821.

### CODE REVIEW

**Comment by YuriSizov** [comment]
That doesn't seem correct. This only adds a call to a virtual method, but to update the control you need to call queue_redraw.

**Comment by KoBeWi** [comment]
Note that simply adding `_queue_redraw()` would make it called twice when changing the value normally (because `set_value_no_signal()` is called internally by `set_value()`). It's not really a problem, but *maybe* there is a way to avoid it.

**Review by KoBeWi — DISMISSED** [review]
I tested and this actually works correctly. Sorry for the confusion.

**Comment by YuriSizov** [comment]
But why does it work correctly? This still doesn't seem right.

**Comment by KoBeWi** [comment]
The method is overriden in SpinBox and updates the underlying LineEdit.

The issue was about SpinBox and it gets fixed correctly, but yeah, other Range controls seem to be still broken.

**Comment by YuriSizov** [comment]
Then it is indeed very much incidental. Since this touches on Range itself, it should be implemented in a way that works for all range controls. And maybe we should double check if SpinBox isn't doing something excessive instead.

**Comment by pattlebass** [comment]
> The method is overriden in SpinBox and updates the underlying LineEdit.
>
> The issue was about SpinBox and it gets fixed correctly, but yeah, other Range controls seem to be still broken.

Broken in what way?

> Then it is indeed very much incidental. Since this touches on Range itself, it should be implemented in a way that works for all range controls. And maybe we should double check if SpinBox isn't doing something excessive instead.

I think the root problem was with Range's `_value_changed()`. It wouldn't get called even though the value changed (through `set_value_no_signal()`).

SpinBox uses the `_value_changed` virtual method to set the underlying Label's text. I don't see any problem with that. It seems that no other Range-derived nodes override this method, so nothing else is affected. See project below.

[range bug.zip](https://github.com/godotengine/godot/files/10333676/range.bug.zip)


However I've just noticed that this PR makes `set_value()` call `_value_changed()` twice so I should fix that.

```
set_value() -> set_value_no_signal() -> _value_changed()
            |
            -> emit_value_changed() -> _value_changed_notify() -> _value_changed()
```

**Comment by KoBeWi** [comment]
> Broken in what way?

They have the same issue as SpinBox. Try `set_value_no_signal()` on e.g. ProgressBar.

File: scene/gui/range.cpp [hunk 1]
```diff
@@ -107,6 +107,22 @@ void Range::set_value_no_signal(double p_val) {
...
+
+	if (shared->val != prev_val) {
+		// Redraw owners.
+		for (Range *E : shared->owners) {
+			Range *r = E;
+			if (!r->is_inside_tree()) {
+				continue;
+			}
+			r->queue_redraw();
+		}
```
Comment (YuriSizov) [inline scene/gui/range.cpp:122]: This can probably be made into a method of `Range::Shared`, for consistency.

**Review by YuriSizov — APPROVED** [review]
Other than that, this seems more reasonable than the original approach. LGTM.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.4.

**Comment by AThousandShips** [comment]
This was added in 4.1, so it's in 4.2 as well, please open a new bug report if something doesn't work correctly

**Comment by ditiem-games** [comment]
Apologies, it is working. My code screwed up with the min/max_value.

**Comment by slapin** [comment]
Can this be cherry-picked for 3.6? Thanks!
