### PR TITLE
Forbid passing multiview sampler to the custom function in shaders

### LINKED ISSUE #72290: Vulkan shader error when passing screen texture to function
### Godot version

v4.0.beta16.official.518b9e580

### System information

Windows 11, Vulkan, AMD Radeon 680M

### Issue description

If I pass a uniform sampler2D with hint_screen_texture to the function, I get a Vulkan shader error.
This issue does not occur before beta15.
It seems to me that perhaps #71455 has an impact.

### Steps to reproduce

Specify the following shader to MeshInstance3D and Run.

```glsl
shader_type spatial;

uniform sampler2D screen_tex : hint_screen_texture;

vec3 sample_rgb(sampler2D tex, vec2 uv) {
	return texture(tex, uv).rgb;
}

void fragment() {
	ALBEDO = sample_rgb(screen_tex, SCREEN_UV);
}
```

### Minimal reproduction project

[ShaderError.zip](https://github.com/godotengine/godot/files/10528974/ShaderError.zip)

### PR DESCRIPTION
**Pull request by Chaosus**
My attempt to fix https://github.com/godotengine/godot/issues/72290, if @BastiaanOlij has another idea of how to fix it that would be cool, and I will close this PR.

### CODE REVIEW

**Comment by clayjohn** [comment]
My feeling is that this might be necessary until we figure out a better solution. It would be really nice to automatically detect XR and non-XR usage, but I have a feeling that it will be too complex for now

**Comment by BastiaanOlij** [comment]
This does feel like a very ugly hack around the problem. One thing we could do is to check `actions.check_multiview_samplers` and only apply this restriction if that is true, and improve the code where we set `actions.check_multiview_samplers` to true to only do this if multiview shaders are actually used (right now a project setting).

Also could we change the check that if we detect a function being called using a parameter we've deemed needing multiview support, that we tell the user to create a sampler2Darray version of the function being called, if it doesn't exist?

**Comment by BastiaanOlij** [comment]
> My feeling is that this might be necessary until we figure out a better solution. It would be really nice to automatically detect XR and non-XR usage, but I have a feeling that it will be too complex for now

Keep in mind that in XR we're always dealing with a mixed environment. Plus someone adding a function like the OP did, that function might be used for both normal textures and for textures that require multiview access in the same shader.

**Comment by Chaosus** [comment]
It's not a hack - I would call it a plug until we found a way to handle it properly.

File: servers/rendering/shader_language.cpp [hunk 1]
```diff
@@ -3479,6 +3479,9 @@ bool ShaderLanguage::_validate_function_call(BlockNode *p_block, const FunctionI
 				}
 			}
 
+			if (r_is_custom_function) {
```
Comment (clayjohn) [inline servers/rendering/shader_language.cpp:3482]: Won't this always be false?

Comment (Chaosus) [reply servers/rendering/shader_language.cpp:3482]: It's working when the pointer is not a null.

**Comment by BastiaanOlij** [comment]
Just to repeat this here as it should be part of this fix, as i mentioned in the issue, we can make this smarter so that our restriction only applies if multiview is enabled. This requires a few small changes:

1) We need to merge the fix Clay did months ago but which was closed because we wanted a better implementation that never eventuated and probably won't until much much later: #63829

2) We need to change the code in 'GLES3::MaterialStorage', `SceneShaderForwardClustered` and `SceneShaderForwardMobile` from `actions.check_multiview_samplers = true;` to `actions.check_multiview_samplers = RendererCompositorRD::singleton->is_xr_enabled();`

3) We need to check `actions.check_multiview_samplers` in this fix and only apply this fix if it is true

With these changes our restriction will only be needed, and only apply, if we're compiling multiview shaders.

File: servers/rendering/shader_language.cpp (hunk 1 above)
Comment (clayjohn) [reply servers/rendering/shader_language.cpp:3482]: Ah, that makes sense

**Comment by YuriSizov** [comment]
@clayjohn @BastiaanOlij You seem to have agreed in the issue that this is a good short-term solution (on top of Clay's own old PR, which has since been merged). What changes, if any, are expected from @Chaosus now? Or should we bump it?

**Comment by clayjohn** [comment]
@Chaosus I agree with Bastiaan's proposed improvements to this PR. Together they will make this limitation only impact users who are working on XR. 

For reference, these are the two changes needed:

1. 
> We need to change the code in GLES3::MaterialStorage, SceneShaderForwardClustered and SceneShaderForwardMobile from actions.check_multiview_samplers = true; to actions.check_multiview_samplers = RendererCompositorRD::singleton->is_xr_enabled();

2. 
> We need to check actions.check_multiview_samplers in this fix and only apply this fix if it is true

**Comment by BastiaanOlij** [comment]
Sounds like clay covered it. If we can make those small changes, this should be ready to go.

**Comment by Chaosus** [comment]
@BastiaanOlij, @clayjohn OK, I think I've done it, please recheck.

File: servers/rendering/renderer_compositor.h [hunk 2]
```diff
@@ -107,6 +108,7 @@ class RendererCompositor {
 	static bool is_low_end() { return low_end; };
 	virtual bool is_xr_enabled() const;
 
+	static RendererCompositor *get_default_singleton() { return singleton; }
```
Comment (BastiaanOlij) [inline servers/rendering/renderer_compositor.h:111]: This can just be called `get_singleton`. As it's static it's clear from calling `RendererCompositor::get_singleton` what you're getting, even if get_singleton is also implemented on subclasses.

File: servers/rendering/renderer_rd/renderer_compositor_rd.h [hunk 3]
```diff
@@ -145,7 +145,7 @@ class RendererCompositorRD : public RendererCompositor {
 		low_end = false;
 	}
 
-	static RendererCompositorRD *singleton;
+	static RendererCompositorRD *get_singleton() { return static_cast<RendererCompositorRD *>(singleton); }
```
Comment (BastiaanOlij) [inline servers/rendering/renderer_rd/renderer_compositor_rd.h:148]: This is nitpicking, but I personally prefer having subclasses have their own singleton member. 

In this case if I have instanced an OpenGL compositor, I can still call `RendererCompositorRD::get_singleton` but now I get the pointer to the OpenGL compositor cast to the Render device compositor.

By having each subclass maintain their own properly typed singleton, we don't need to do casts and we get a nullptr returned if we've instanced a different compositor subclass and somehow run through code meant for render device. It's a few extra bytes but it saves us hard to track crashes.

Comment (BastiaanOlij) [reply servers/rendering/renderer_rd/renderer_compositor_rd.h:148]: Btw, just to be clear, absolutely agree with the move to using `get_singleton`, just that `static RendererCompositorRD *singleton;` should now be a private property that is set in `RendererCompositorRD::RendererCompositorRD` instead of re-using the singleton set in the parent class.

**Comment by BastiaanOlij** [comment]
Shader changes look good. Just a little nitpick on the singleton change, though this is my personal opinion on the subject, I don't know what the official stance on this is but I've always added separate singleton members to subclasses to ensure we're accessing a pointer that will remain null when a different subclass is instantiated.

**Comment by Chaosus** [comment]
@BastiaanOlij OK, check again.

File: servers/rendering/shader_language.cpp [hunk 4]
```diff
@@ -5391,6 +5401,22 @@ ShaderLanguage::Node *ShaderLanguage::_parse_expression(BlockNode *p_block, cons
 											//being sampler, this either comes from a uniform
 											ShaderNode::Uniform *u = &shader->uniforms[varname];
 											ERR_CONTINUE(u->type != call_function->arguments[i].type); //this should have been validated previously
+
+											bool is_xr_enabled;
+#ifdef GLES3_ENABLED
+											is_xr_enabled = RasterizerGLES3::get_singleton()->is_xr_enabled();
+#else
+											is_xr_enabled = RendererCompositorRD::get_singleton()->is_xr_enabled();
+#endif // GLES3_ENABLED
```
Comment (akien-mga) [inline servers/rendering/shader_language.cpp:5410]: This seems wrong.

This is a compile time check, so this means that by defaults (builds include both GLES3 and Vulkan), it will only check that XR is enabled in the GLES3 renderer. Likewise for the includes. It seems weird to have GLES3 includes in `servers/` code, currently there is none and things are well decoupled.

File: servers/rendering/renderer_compositor.h (hunk 2 above)
Comment (Chaosus) [reply servers/rendering/renderer_compositor.h]: It's not possible to define it as `get_singleton` if you want to define a new singleton in the derived class.

File: servers/rendering/shader_language.cpp (hunk 4 above)
Comment (Chaosus) [reply servers/rendering/shader_language.cpp]: I removed this code, and make a single singleton for the compositor base class.

File: servers/rendering/renderer_compositor.h (hunk 2 above)
Comment (BastiaanOlij) [reply servers/rendering/renderer_compositor.h]: Hmm, I do this in `RenderForwardClustered` and `RenderForwardMobile` which both inherit from `RendererSceneRenderRD` and all 3 have their own singleton member and `get_singleton` method. It's fairly important here because the likelihood of code being written that is shared between both render implementations yet calls the wrong `get_singleton` is relatively high.

File: servers/rendering/renderer_rd/environment/sky.cpp [hunk 5]
```diff
@@ -276,7 +276,7 @@ void SkyRD::ReflectionData::update_reflection_data(int p_size, int p_mipmaps, bo
 	int mipmaps = p_mipmaps;
 	uint32_t w = p_size, h = p_size;
 
-	EffectsRD *effects = RendererCompositorRD::singleton->get_effects();
+	EffectsRD *effects = static_cast<RendererCompositorRD *>(RendererCompositorRD::get_singleton())->get_effects();
```
Comment (BastiaanOlij) [inline servers/rendering/renderer_rd/environment/sky.cpp:279]: I'll clean this bit up in 4.1, there are only 2 or 3 effects left that need their own little class and `get_effects` is toast.

**Review by BastiaanOlij — APPROVED** [review]
Seeing `get_singleton` is now on the base class we could replace `RendererCompositorRD::get_singleton()` and `RendererCompositorGLES3::get_singleton()` with `RendererCompositor::get_singleton()`. But I feel I'm really taking nitpicking to the next level now :)

File: servers/rendering/renderer_rd/environment/sky.cpp (hunk 5 above)
Comment (BastiaanOlij) [reply servers/rendering/renderer_rd/environment/sky.cpp:279]: (I might sneak that in this week if I can, it's just cleanup so shouldn't break anything)

File: servers/rendering/renderer_compositor.h (hunk 2 above)
Comment (Chaosus) [reply servers/rendering/renderer_compositor.h]: Ah, I thought it's not possible for static methods in C++...

Comment (Chaosus) [reply servers/rendering/renderer_compositor.h]: *Fixed* like you said

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Tested this PR locally, got a segfault on exit on quitting a simple test project (empty 2D scene):
```
ERROR: 2 RID allocations of type 'N10RendererRD14TextureStorage7TextureE' were leaked at exit.
ERROR: 1 RID allocations of type 'N18RendererCanvasCull4ItemE' were leaked at exit.

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.rc.custom_build (0e988d558670f4e43df259fa1d41088d2f805368)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib64/libc.so.6(+0x36940) [0x7f134be38940] (??:0)
[2] RendererCanvasRender::Polygon::~Polygon() (/home/akien/Projects/godot/godot.git/./servers/rendering/renderer_canvas_render.h:154)
[3] RendererCanvasRender::Item::CommandPolygon::~CommandPolygon() (/home/akien/Projects/godot/godot.git/./servers/rendering/renderer_canvas_render.h:228)
[4] void memdelete<RendererCanvasRender::Item::Command>(RendererCanvasRender::Item::Command*) (/home/akien/Projects/godot/godot.git/./core/os/memory.h:112)
[5] RendererCanvasRender::Item::clear() (/home/akien/Projects/godot/godot.git/./servers/rendering/renderer_canvas_render.h:416)
[6] RendererCanvasRender::Item::~Item() (/home/akien/Projects/godot/godot.git/./servers/rendering/renderer_canvas_render.h:469)
[7] RendererCanvasCull::Item::~Item() (/home/akien/Projects/godot/godot.git/servers/rendering/renderer_canvas_cull.h:40)
[8] RID_Alloc<RendererCanvasCull::Item, true>::~RID_Alloc() (/home/akien/Projects/godot/godot.git/./core/templates/rid_owner.h:347)
[9] RID_Owner<RendererCanvasCull::Item, true>::~RID_Owner() (/home/akien/Projects/godot/godot.git/./core/templates/rid_owner.h:427)
[10] RendererCanvasCull::~RendererCanvasCull() (/home/akien/Projects/godot/godot.git/servers/rendering/renderer_canvas_cull.cpp:2248)
[11] void memdelete<RendererCanvasCull>(RendererCanvasCull*) (/home/akien/Projects/godot/godot.git/./core/os/memory.h:112)
[12] RenderingServerDefault::~RenderingServerDefault() (/home/akien/Projects/godot/godot.git/servers/rendering/rendering_server_default.cpp:434)
[13] void memdelete<RenderingServer>(RenderingServer*) (/home/akien/Projects/godot/godot.git/./core/os/memory.h:112)
[14] finalize_display() (/home/akien/Projects/godot/godot.git/main/main.cpp:282)
[15] Main::cleanup(bool) (/home/akien/Projects/godot/godot.git/main/main.cpp:3362)
[16] godot-git(main+0x164) [0x528e88a] (/home/akien/Projects/godot/godot.git/platform/linuxbsd/godot_linuxbsd.cpp:77)
[17] /lib64/libc.so.6(+0x23677) [0x7f134be25677] (??:0)
[18] /lib64/libc.so.6(__libc_start_main+0x85) [0x7f134be25735] (??:0)
[19] godot-git(_start+0x21) [0x528e661] (??:?)
-- END OF BACKTRACE --
================================================================
Aborted (core dumped)
```

**Comment by BastiaanOlij** [comment]
Weird, I thought this PR would only have impact on the 3D renderer, not on the 2D renderer, but I could be wrong

**Comment by akien-mga** [comment]
I'll try to do more testing, it might have been an unrelated bug present in `master` too.

**Comment by akien-mga** [comment]
Yeah my segfault was unrelated to this PR, sorry for the false alarm. It happens in the `master` branch too and is related to a simple plugin I got from an unrelated MRP.

So this should be good to go. But I already started the build for 4.0 RC 3, so please don't merge for now, we'll see in the production team how to time this.

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
