### PR TITLE
Fix vsync on macOS getting disabled when using `afterMinimumDuration`

### LINKED ISSUE #99657: Disabling vsync on macOS has no effect
### Tested versions

v4.4.dev.custom_build [0c45ace15]

Doesn't happen in 4.4-dev4

### System information

Godot v4.4.dev (0c45ace15) - macOS 15.1.0 - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M1 Max (Apple7) - Apple M1 Max (10 threads)

### Issue description

Setting `display/window/vsync/vsync_mode` to Disabled doesn't have any effect, `Engine.get_frames_per_second()` and the debugger monitor report the maximum display refresh rate. This happens with both Metal and Vulkan

Image

### Steps to reproduce

Run an empty project and look at Debugger->Monitors FPS

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by mrsaturnsan**
Calling afterMinimumDuration with 0.0 will implicitly enable vsync so need to work around that.

Fixes https://github.com/godotengine/godot/issues/99657#issuecomment-2501743024

### CODE REVIEW

**Comment by passivestar** [comment]
This works with max fps 0, however if I set it to anything else it forces vsync. For example if I set max fps to 200 I get 120 fps when I run the game

**Comment by passivestar** [comment]
This fixes the issue when vsync is disabled, but introduces a regression to fps stability when vsync is enabled

This PR (VSync ON):


Master (VSync ON):

File: drivers/metal/rendering_context_driver_metal.mm [hunk 1]
```diff
@@ -172,7 +172,11 @@ void present(MDCommandBuffer *p_cmd_buffer) override final {
 		count--;
 		front = (front + 1) % frame_buffers.size();
 
-		[p_cmd_buffer->get_command_buffer() presentDrawable:drawable afterMinimumDuration:present_minimum_duration];
+		if (vsync_mode == DisplayServer::VSYNC_ENABLED) {
+			[p_cmd_buffer->get_command_buffer() presentDrawable:drawable afterMinimumDuration:present_minimum_duration];
```
Comment (Calinou) [inline drivers/metal/rendering_context_driver_metal.mm:176]: Note that `VSYNC_ADAPTIVE` and `VSYNC_MAILBOX` are treated as `VSYNC_ENABLED` on macOS, so I suggest checking for `vsync_mode != DisplayServer::VSYNC_DISABLED` instead.

Comment (passivestar) [reply drivers/metal/rendering_context_driver_metal.mm]: I don't think this is related but I can check

Comment (passivestar) [reply drivers/metal/rendering_context_driver_metal.mm]: Well I just triple-checked and this is confusing, but it does regress to unstable FPS as soon as this line is put into the conditional statement:

```
[p_cmd_buffer->get_command_buffer() presentDrawable:drawable afterMinimumDuration:present_minimum_duration];
```

I tried taking it out of it myself and recompiling and I get stable 120 as soon as I do that. I also did a check to make sure that the correct branch is running when it's in it, so it's not a problem with `vsync_mode` either

If there is some obscure metal-related cache that I may need to clear or something like that let me know because I don't know why this is happening

Comment (passivestar) [reply drivers/metal/rendering_context_driver_metal.mm]: Yeah I'm on 15.1 as well

https://github.com/user-attachments/assets/376306ae-b7bf-4758-9d9d-e9689a49c854

Comment (passivestar) [reply drivers/metal/rendering_context_driver_metal.mm]: I went to check the call stack but I can't reproduce the issue anymore no matter what I do. Apparently it was something external that caused different vsync values. In any case it appears to be unrelated to this PR, I'll open another issue if I face it again

**Review by passivestar — APPROVED** [review]
Solves the issue

**Comment by coppolaemilio** [comment]
@stuartcarnie can you take a look at this one?

**Review by stuartcarnie — APPROVED** [review]
I can confirm that this resolves the issue when using --disable-vsync

File: drivers/metal/rendering_context_driver_metal.mm [hunk 2]
```diff
@@ -172,7 +172,11 @@ void present(MDCommandBuffer *p_cmd_buffer) override final {
 		count--;
 		front = (front + 1) % frame_buffers.size();
 
-		[p_cmd_buffer->get_command_buffer() presentDrawable:drawable afterMinimumDuration:present_minimum_duration];
+		if (vsync_mode != DisplayServer::VSYNC_DISABLED) {
```
Comment (clayjohn) [inline drivers/metal/rendering_context_driver_metal.mm:175]: Shouldn't this branch still run if `present_minimum_duration` is greater than 0?

This seems to make it so we don't benefit from https://github.com/godotengine/godot/pull/99041 when vsync is disabled. But you are very likely to be using `max_fps` when vsync is disabled.

Comment (stuartcarnie) [reply drivers/metal/rendering_context_driver_metal.mm:175]: I see, so you are saying when vsync is disabled, but `max_fps` is set, we still expect the renderer to limit the FPS?

Comment (clayjohn) [reply drivers/metal/rendering_context_driver_metal.mm:175]: That's right. We actually handle that in `OS::add_frame_delay` on the CPU side. But using `afterMinimumDuration` allows us to smooth it out and time things with the screen refresh

Comment (clayjohn) [reply drivers/metal/rendering_context_driver_metal.mm:175]: I might have just answered my own question. This probably provides no benefit when not using Vsync if the whole purpose is allowing us to synchronize better with vsync.

Comment (clayjohn) [reply drivers/metal/rendering_context_driver_metal.mm:175]: > Enabling that branch will implicitly enable vsync since macOS will limit frame rate to something the display can support.
> 
> Alternatively, you could query the refresh rate of the display and enable that branch only if the max FPS can be evenly divided by the refresh rate.

Thanks for your response. That makes sense. I agree we should just leave it off when not using vsync.

**Comment by Repiteo** [comment]
Thanks!
