### PR TITLE
Avoid manipulating `PackedScene` cache when generating scene preview thumbnails

### LINKED ISSUE #107494: Scripts detached from child-scenes in the editor when the scene is loaded.
### Tested versions

- Reproducible since #102313/[ea76c48bd09f54e710145cfb6197fe49fed2feca]

### System information

Godot v4.5.dev.mono (2a46634a6) - Ubuntu 24.04.2 LTS 24.04 on Wayland - X11 display driver, Multi-window, 3 monitors - Vulkan (Forward+) - integrated AMD Radeon Graphics (RADV RENOIR) - AMD Ryzen 7 5800H with Radeon Graphics (16 threads) - 13.49 GiB memory

### Issue description

In my main project (C#), certain child-scenes are loaded without their attached script in the editor. Sometimes they are loaded with the script, but it disappears when reloaded. These scenes also have no script when they are newly added to a scene. The script is only attached when the child scene is open in the editor. This only happens in the editor and with some scenes. Unfortunately, I'm not able to reproduce it in an MRP.

However, while trying to reproduce it, I found that something similar happens when a change is made to the scene, it is **not** saved, and then the scene is reloaded via Scene -> Reload Saved Scene -> Save & Reload. In this case, all child scene scripts are detached.

I pinpointed the problem to #102313/[ea76c48bd09f54e710145cfb6197fe49fed2feca]. Maybe there is some kind of problem (race?) when the scenes are saved/loaded for the thumbnails.

### Steps to reproduce

Open any scene containing child scenes with script. Change something. **Don't** save. Reload the scene via `Scene` -> `Reload Saved Scene` ->  `Save & Reload`. All child scenes have 'lost' their script.
The mrp contains two a main scene with two child scene. Edit something in the main scene (e.g. re-order the child-scenes) and reload.

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/20738205/mrp.zip)

### PR DESCRIPTION
**Pull request by daniel080400**
Attempt to fix issue #107494

Should likely be a cache issue with ```ResourceLoader```. Need further testing and MRP.

Edit:
Issue confirmed is related to cache mode, see comments below.

* *Bugsquad edit, fixes: #107494*

### CODE REVIEW

File: editor/plugins/editor_preview_plugins.cpp [hunk 1]
```diff
@@ -334,6 +334,7 @@ Ref<Texture2D> EditorPackedScenePreviewPlugin::generate_from_path(const String &
 		return Ref<Texture2D>();
 	}
 
+	pack = pack->duplicate_deep(); // Just to make sure we don't touch the cache
```
Comment (KoBeWi) [inline editor/plugins/editor_preview_plugins.cpp]: This will make generating previews much slower, especially when a scene has large resources. Using ignore deep should be enough.

Comment (daniel080400) [reply editor/plugins/editor_preview_plugins.cpp]: Thanks, I can confirm the issue is fixed just by changing the cache mode to ```CACHE_MODE_IGNORE_DEEP```, removing that line.

**Comment by daniel080400** [comment]
I confirmed the issue is fixed by changing the cache mode from ```CACHE_MODE_IGNORE``` to ```CACHE_MODE_IGNORE_DEEP```, using the steps to reproduce mentioned in #107494 with an **blank project created after 4.4.1**. (Previously I tested with complex projects that are created prior to 4.4.1 and it's somehow not reproducible)

>Open any scene containing child scenes with script. Change something. Don't save. Reload the scene via Scene -> Reload Saved Scene -> Save & Reload. All child scenes have 'lost' their script.

With the same project, the issue persists when changing it back to ```CACHE_MODE_IGNORE```, and fixed when changing it to ```CACHE_MODE_IGNORE_DEEP```.

Marking this as ready for review, this change should have no side effects, we should merge it right away. May someone provide more testing results to let us confidently mark the issue as resolved.

**Comment by pmoosi** [comment]
Can confirm that it fixes the issue for me.

**Review by KoBeWi — APPROVED** [review]
Fixes the issue for me too.

**Comment by poglad-ds** [comment]
After migrating from 51b0379e5 (11.06 build date) that have this problem, this looks like fixes it as long as i see.

**Comment by akien-mga** [comment]
Thanks!
