### PR TITLE
Fix a inherited transform bug with Camera2D preview drawing

### LINKED ISSUE #5339: Camera2D preview doesn't show correctly when parent moves
**Operating system or device - Godot version:**
regarding [1566da2](https://github.com/godotengine/godot/pull/4373)

**Issue description** (what happened, and what was expected):
The preview shows incorrect behavior if the parent node is moved

**Steps to reproduce:**
- add node to scene
- add another node "A" (Node2D would work)
- add a Camera2D  as child in "A"
- move "A"

**Link to minimal example project** (optional but very welcome):
https://www.dropbox.com/s/9ivvyy9k06mrul5/cambug.zip?dl=0

### PR DESCRIPTION
**Pull request by bojidar-bg**
Closes #5339 

It is a bit funny I missed that one, when I specifically needed global coordinates...

### CODE REVIEW

File: scene/2d/camera_2d.cpp [hunk 1]
```diff
@@ -281,11 +281,10 @@ void Camera2D::_notification(int p_what) {
 				inv_camera_transform.xform(Vector2(0, screen_size.height))
 			};
 
-			Matrix32 inv_transform = get_transform().affine_inverse(); // undo global space
-			draw_set_transform(inv_transform.get_origin(), inv_transform.get_rotation(), inv_transform.get_scale());
```
Comment (bojidar-bg) [inline scene/2d/camera_2d.cpp]: When the parent was scaled unequally, `draw_set_transform` failed me, so I had to switch :smile:
