### PR TITLE
Fixed pivot tool not setting position of Controls correctly

### LINKED ISSUE #17890: Pivot tool doesn't compensate Control node position correctly
**Godot version:**

3.0.2.stable.official

**Issue description:**
Using the pivot tool pivot_tool to change the pivot offset of a rotated Control node causes it to move northwest through the screen (I'm using a TextureButton as an example):

control_rotated

At 0°, this issue doesn't occur:

control_0_degrees

At 360°, the pivot tool now also changes the node's size:

control_360_degrees

The same doesn't happen when changing the offset of a Sprite node, as its position is compensated correctly:

sprite_rotated

**Steps to reproduce:**
1. Add a node that inherits the Control class;
2. Change its rotation to any degree other than 0;
3. Select the pivot tool in the toolbar and change the node's pivot offset.

**Edit:**

I thought that the issue was related to **Control::_edit_set_pivot**, but it seems to affect the Control node in-game too. Here's a demo project where you can click to change the pivot offset of a TextureButton and the offset of a Sprite, based on the local mouse position. The Sprite stays fixed in its place while the TextureButton moves up and left:

control_pivot

[control_pivot.zip](https://github.com/godotengine/godot/files/1865888/control_pivot.zip)

### PR DESCRIPTION
**Pull request by Piet-G**
Fixed pivot tool not setting position of Controls correctly

I did what @groud suggested in #17890

This fixes that issue. *Bugsquad edit:* Fixes #17890.

### CODE REVIEW

File: scene/gui/control.cpp [hunk 1]
```diff
@@ -1336,8 +1338,8 @@ void Control::_size_changed() {
 
 	// We use a little workaround to avoid flickering when moving the pivot with _edit_set_pivot()
 	if (is_inside_tree() && Math::abs(Math::sin(data.rotation * 4.0f)) < 0.00001f && get_viewport()->is_snap_controls_to_pixels_enabled()) {
```
Comment (groud) [inline scene/gui/control.cpp]: You should move the test to surround you changes in _update_canvas_item_transform.
And remove its content completely from there, and it does not serve any purpose now.

**Review by groud — CHANGES_REQUESTED** [review]

**Comment by groud** [comment]
The fix should be good with the requested changes. Not sure it does not create unexpected bugs though.

**Comment by DualMatrix** [comment]
Fixed what you suggested and added some code I forgot previously which is required for it to actually work.

File: scene/gui/control.cpp [hunk 2]
```diff
@@ -449,6 +449,12 @@ void Control::_update_canvas_item_transform() {
 	Transform2D xform = _get_internal_transform();
 	xform[2] += get_position();
 
+	// We use a little workaround to avoid flickering when moving the pivot with _edit_set_pivot()
+	if (is_inside_tree() && Math::abs(Math::sin(data.rotation * 4.0f)) < 0.00001f && get_viewport()->is_snap_controls_to_pixels_enabled()) {
+		xform[2] = xform[2].round();
+		xform.set_rotation_and_scale(xform.get_rotation(), xform.get_scale().round());
```
Comment (groud) [inline scene/gui/control.cpp]: Please don't do that, the scale should not be rounded. 
Keep in mind the snap to pixel makes only sense with non-rotated and non-scaled nodes, so in other situations it should not alter the display.

**Review by groud — CHANGES_REQUESTED** [review]

File: scene/gui/control.cpp (hunk 2 above)
Comment (DualMatrix) [reply scene/gui/control.cpp]: Yeah knew that, just wasn't paying enough attention, maybe letting r_margins[2] and r_margins[3] remain floored?

**Comment by groud** [comment]
> @groud What's the status now?

Well, the PR does not completely fix the problem as the control node size won't be pixel-aligned.
But until we figure out a better solution I think it's good to merge.

**Comment by akien-mga** [comment]
>  But until we figure out a better solution I think it's good to merge.

OK, merging then.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
For the reference, this is being reverted by #32959 as it's no longer necessary and caused other issues.
