### PR TITLE
Ensure that C# script names (and therefore class names) are valid identifiers

### LINKED ISSUE #74307: C# script naming is too relaxed and it can generate invalid class names
### Godot version

v4.0.stable.mono.official [92bee43ad]

### System information

Windows 10

### Issue description

C# script names are too relaxed because class names generated are not valid when used non alphanumeric chars.

### Steps to reproduce

Try creating a C# script named `tuk-a.cs`. Godot editor will consider it valid and create class named `tuk-a_w`. Which is an invalid C# name because it contains - char. One can also use , char and perhaps others invalid.

### Minimal reproduction project

[ScriptNamesProblem.zip](https://github.com/godotengine/godot/files/10883318/ScriptNamesProblem.zip)

Sample project with a C# script named Invalid,Name-Text.cs

### PR DESCRIPTION
**Pull request by aleksrutins**
This fixes #74307.
Previously, C# script names (and therefore class names) were not limited to valid C# identifiers, which could cause problems. This PR limits C# script names to valid identifiers.

### CODE REVIEW

**Comment by raulsntos** [comment]
Thanks for contributing!

I think we should be able to use `String::is_valid_identifier` for the check.

Also, make sure to squash the commits. See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by RedworkDE** [comment]
Actually `TS->is_valid_identifier` should probably be used instead, since C# allows Unicode in identifiers.
(The C# and Unicode definition of an identifier are slightly different, in that C# allows `Category Other, subcategory format` characters and Unicode allows some chars backwards compatibility with previous versions of the standard, which C# doesn't do, but the definitions are probably close enough that the differences don't really matter).

**Comment by aleksrutins** [comment]
Does C# also support `$` as a valid identifier character, or am I confusing it with JavaScript?

**Comment by RedworkDE** [comment]
No, `$` is not allowed in an identifier.

File: modules/mono/csharp_script.cpp [hunk 1]
```diff
@@ -374,6 +375,12 @@ String CSharpLanguage::validate_path(const String &p_path) const {
 	if (keywords.find(class_name)) {
 		return RTR("Class name can't be a reserved keyword");
 	}
+
```
Comment (RedworkDE) [inline modules/mono/csharp_script.cpp:378]: There is some whitespace on this line that should be removed.

**Comment by raulsntos** [comment]
> Actually `TS->is_valid_identifier` should probably be used instead, since C# allows Unicode in identifiers.

That makes sense to me. I'm not sure that the text server is always available, but I think it's fine. TextEdit seems to use it without wrapping it in if checks so I guess we can assume it's always available.

File: modules/mono/csharp_script.cpp [hunk 2]
```diff
@@ -374,6 +375,11 @@ String CSharpLanguage::validate_path(const String &p_path) const {
 	if (keywords.find(class_name)) {
 		return RTR("Class name can't be a reserved keyword");
 	}
+	Ref<TextServer> ts = TextServerManager::get_singleton()->get_primary_interface();
+	if(!ts->is_valid_identifier(class_name)) {
```
Comment (raulsntos) [inline modules/mono/csharp_script.cpp:379]: We can use the macro instead.

```suggestion
	if (!TS->is_valid_identifier(class_name)) {
```

**Review by raulsntos — CHANGES_REQUESTED** [review]

**Comment by raulsntos** [comment]
You may want to configure your IDE to use clang-format to follow our code style. See https://docs.godotengine.org/en/stable/contributing/development/code_style_guidelines.html#using-clang-format-locally.

**Review by raulsntos — APPROVED** [review]
LGTM

**Review by neikeq — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by aleksrutins** [comment]
Thanks! I hope to contribute more in the future.

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.1.
