### PR TITLE
Hide Scattering label and controls within TileMap editor window when "Place Random Tile" option is disabled

### LINKED ISSUE #69697: Cannot modify Scattering value when Place Random Tile is deselected
### Godot version

4.0.beta7.official [0bb1e89fb]

### System information

Windows 11 Home, Version 21H2, OS build 22000.1219

### Issue description

Within the TileMap window you cannot change the Scattering value if "Place Random Tile" is not selected, but you can still select the field and highlight it, hinting that it can be changed.

Is this expected behavior?

Scattering

### Steps to reproduce

Create TileMap Node
Assign a TileSet
Ensure "TileMap" is selected at the bottom within the TileMap editor window
Attempt to change Scattering value by clicking arrows or selecting field and entering a number. **[DOES NOT WORK]**

Enable "Place Random Tile" to the left of Scattering
Attempt to change Scattering value.  **[WORKS]**

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by henrlin24**
This change addresses issue #69697, which was an editor enhancement request. As stated in the title, the change hides the Scattering spinbox input within the TileMap window when "Place Random Tile" is disabled, where the current version grays out the Scattering spinbox. 
I created a new container object named ```scatter_controls_container```, with ```scatter_label``` and ```scatter_spinbox``` as child elements.  ```scatter_controls_container``` is set as a child element of the existing ```tools_setting``` container. When hiding the Scattering elements, I used ```hide()``` and ```show()``` on the ```scatter_controls_container```.
**Before:**
- Place Random Tile enabled:
RandomToggled
- Place Random Tile disabled: 
RandomNotToggled

**After:**
- Place Random Tile enabled:
Changed_toggle
- Place Random Tile disabled:
Changed_no_toggle

*Bugsquad edit:*
- Fixes #69697

### CODE REVIEW

File: editor/plugins/tiles/tile_map_editor.cpp [hunk 1]
```diff
@@ -55,7 +55,10 @@ void TileMapEditorTilesPlugin::tile_set_changed() {
 }
 
 void TileMapEditorTilesPlugin::_on_random_tile_checkbox_toggled(bool p_pressed) {
-	scatter_spinbox->set_editable(p_pressed);
+	if (p_pressed)
+		scatter_controls_container->show();
+	else
+		scatter_controls_container->hide();
```
Comment (akien-mga) [inline editor/plugins/tiles/tile_map_editor.cpp:61]: Our code style requires the use of braces even around single line statements.
You could also do `scatter_controls_container->set_visible(p_pressed);` probably.

Please fix the style issue with `git commit --amend` so that the change stays as a single commit (see https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request).

Comment (henrlin24) [reply editor/plugins/tiles/tile_map_editor.cpp:61]: Okay, I'll try that.

Comment (henrlin24) [reply editor/plugins/tiles/tile_map_editor.cpp]: Okay, I should have successfully amended the commit. Tested the changes and they seem to work the same.

**Comment by akien-mga** [comment]
Please remove "Updated after running clang-format." from the commit message - this is not relevant to the commit history. The commit should describe how it impacts the engine behavior, not what you did to make it pretty ;)

**Comment by henrlin24** [comment]
Re-did commit message.

**Comment by henrlin24** [comment]
Sorry for the late follow-up, but I did end up removing the unnecessary info. Let me know if there is anything else I can do. Thanks!

**Review by KoBeWi — APPROVED** [review]
