### PR TITLE
OpenGL: Implement 3D Texture support

### LINKED ISSUE #71029: OpenGL: TextureArrays and Texture3D samplers not implemented yet
### Godot version

Godot Engine v4.0.beta10

### System information

archlinux; vulkan on dedicated `NVIDIA GeForce RTX 3060 Laptop GPU`; opengl3 on integrated `AMD Radeon Graphics (renoir, LLVM 14.0.6, DRM 3.49, 6.1.1-arch1-1)`

### Issue description

With the opengl3 backend a shader will read a Samper2dArray uniform as being completely black.

opengl3:
texturearray_opengl3

vulkan:
texturearray_vulkan

used shader:
```
shader_type spatial;

uniform sampler2DArray textures : source_color, filter_linear_mipmap;

void fragment() {
	ALBEDO = texture(textures, vec3(UV, 1.0)).xyz;
}
```

### Steps to reproduce

Create a scene with a meshinstance3d with the shader above as a material.
Give that shader a Texture2DArray as parameter.
With the vulkan renderer this will run fine, but with opengl3 the texture is read as being completely black.

### Minimal reproduction project

[sampler2darray.zip](https://github.com/godotengine/godot/files/10366728/sampler2darray.zip)

### PR DESCRIPTION
**Pull request by alula**
*Bugsquad edit:*
- Fixes https://github.com/godotengine/godot/issues/71029

### CODE REVIEW

**Comment by akien-mga** [comment]
Should fix #71029 I suppose?

**Comment by alula** [comment]
This is for 4.x compatibility renderer, so 3.x milestone sounds like a mistake...

**Comment by clayjohn** [comment]
I am getting the following error just opening up the project manager with this PR:
```
ERROR: Image has included mipmaps
   at: texture_3d_initialize (drivers/gles3/storage/texture_storage.cpp:816)
ERROR: Image has included mipmaps
   at: texture_3d_initialize (drivers/gles3/storage/texture_storage.cpp:816)
```
I traced it back to our default texture generation which reuses images that already have mipmaps to create the default images. The following diff resolves the errors:
```
diff --git a/drivers/gles3/storage/texture_storage.cpp b/drivers/gles3/storage/texture_storage.cpp
index 268043f99f..ef16a52b3a 100644
--- a/drivers/gles3/storage/texture_storage.cpp
+++ b/drivers/gles3/storage/texture_storage.cpp
@@ -77,19 +77,24 @@ TextureStorage::TextureStorage() {
 			default_gl_textures[DEFAULT_GL_TEXTURE_2D_ARRAY_WHITE] = texture_allocate();
 			texture_2d_layered_initialize(default_gl_textures[DEFAULT_GL_TEXTURE_2D_ARRAY_WHITE], images, RS::TEXTURE_LAYERED_2D_ARRAY);
 
-			for (int i = 0; i < 3; i++) {
+			for (int i = 0; i < 5; i++) {
 				images.push_back(image);
 			}
 
-			default_gl_textures[DEFAULT_GL_TEXTURE_3D_WHITE] = texture_allocate();
-			texture_3d_initialize(default_gl_textures[DEFAULT_GL_TEXTURE_3D_WHITE], image->get_format(), 4, 4, 4, false, images);
+			default_gl_textures[DEFAULT_GL_TEXTURE_CUBEMAP_WHITE] = texture_allocate();
+			texture_2d_layered_initialize(default_gl_textures[DEFAULT_GL_TEXTURE_CUBEMAP_WHITE], images, RS::TEXTURE_LAYERED_CUBEMAP);
+		}
+
+		{
+			Ref<Image> image = Image::create_empty(4, 4, false, Image::FORMAT_RGBA8);
+			image->fill(Color(1, 1, 1, 1));
 
-			for (int i = 0; i < 2; i++) {
+			Vector<Ref<Image>> images;
+			for (int i = 0; i < 4; i++) {
 				images.push_back(image);
 			}
-
-			default_gl_textures[DEFAULT_GL_TEXTURE_CUBEMAP_WHITE] = texture_allocate();
-			texture_2d_layered_initialize(default_gl_textures[DEFAULT_GL_TEXTURE_CUBEMAP_WHITE], images, RS::TEXTURE_LAYERED_CUBEMAP);
+			default_gl_textures[DEFAULT_GL_TEXTURE_3D_WHITE] = texture_allocate();
+			texture_3d_initialize(default_gl_textures[DEFAULT_GL_TEXTURE_3D_WHITE], image->get_format(), 4, 4, 4, false, images);
 		}
 
 		{ // black
@@ -101,19 +106,23 @@ TextureStorage::TextureStorage() {
 			texture_2d_initialize(default_gl_textures[DEFAULT_GL_TEXTURE_BLACK], image);
 
 			Vector<Ref<Image>> images;
-
-			for (int i = 0; i < 4; i++) {
+			for (int i = 0; i < 6; i++) {
 				images.push_back(image);
 			}
+			default_gl_textures[DEFAULT_GL_TEXTURE_CUBEMAP_BLACK] = texture_allocate();
+			texture_2d_layered_initialize(default_gl_textures[DEFAULT_GL_TEXTURE_CUBEMAP_BLACK], images, RS::TEXTURE_LAYERED_CUBEMAP);
+		}
 
-			default_gl_textures[DEFAULT_GL_TEXTURE_3D_BLACK] = texture_allocate();
-			texture_3d_initialize(default_gl_textures[DEFAULT_GL_TEXTURE_3D_BLACK], image->get_format(), 4, 4, 4, false, images);
+		{
+			Ref<Image> image = Image::create_empty(4, 4, false, Image::FORMAT_RGBA8);
+			image->fill(Color(0, 0, 0, 1));
 
-			for (int i = 0; i < 2; i++) {
+			Vector<Ref<Image>> images;
+			for (int i = 0; i < 4; i++) {
 				images.push_back(image);
 			}
-			default_gl_textures[DEFAULT_GL_TEXTURE_CUBEMAP_BLACK] = texture_allocate();
-			texture_2d_layered_initialize(default_gl_textures[DEFAULT_GL_TEXTURE_CUBEMAP_BLACK], images, RS::TEXTURE_LAYERED_CUBEMAP);
+			default_gl_textures[DEFAULT_GL_TEXTURE_3D_BLACK] = texture_allocate();
+			texture_3d_initialize(default_gl_textures[DEFAULT_GL_TEXTURE_3D_BLACK], image->get_format(), 4, 4, 4, false, images);
 		}
 
 		{ // transparent black
@@ -813,6 +822,7 @@ void TextureStorage::texture_3d_initialize(RID p_texture, Image::Format p_format
```

**Comment by alula** [comment]
done

File: drivers/gles3/storage/texture_storage.cpp [hunk 1]
```diff
@@ -808,8 +817,57 @@ void TextureStorage::texture_2d_layered_initialize(RID p_texture, const Vector<R
...
+				valid_format = p_data[i]->get_format();
+				valid_mipmaps = p_data[i]->has_mipmaps();
+			} else {
+				ERR_FAIL_COND(p_data[i]->get_width() != valid_width);
+				ERR_FAIL_COND(p_data[i]->get_height() != valid_height);
+				ERR_FAIL_COND(p_data[i]->get_format() != valid_format);
+				ERR_FAIL_COND(p_data[i]->has_mipmaps() != valid_mipmaps);
+			}
+		}
+	}
```
Comment (clayjohn) [inline drivers/gles3/storage/texture_storage.cpp:850]: This should logic should mirror the logic from ``RD::texture_3d_initialize()`` instead of the logic from ``GLES3::texture_layered_initialize()`` as 3D textures work differently. 

Notably, 3D textures store mipmaps as slices in p_data, so this code will fail with any 3D texture that uses mipmaps. By way of illustration ``p_data`` is organized as follows (S stands for slice, M stands for mipmap):
```
// A 4x4x4 3D texture without mipmaps would look like:
p_data = {S1M1, S2M1, S3M1, S4M1}

// A 4x4x4 3D texture with mipmaps would look like:
p_data = {S1M1, S2M1, S3M1, S4M1, S1M2, S2M2, S3M2, S4M2, S1M3, S2M3, S3M3, S4M3}
```

https://github.com/godotengine/godot/blob/eca6f0eb545166708c56633152974f40f51de2be/servers/rendering/renderer_rd/storage_rd/texture_storage.cpp#L979-L1022

**Review by clayjohn — COMMENTED** [review]
This looks mostly good. I left a comment on the validation code as it will need some changes. 

Another thing to consider is implementing ``texture_3d_get()`` without it, NoiseTexture3Ds crash on creation. Please let me know if you would like some help with implementing ``texture_3d_get()`` as it is a little more complex

File: drivers/gles3/storage/texture_storage.cpp (hunk 1 above)
Comment (alula) [reply drivers/gles3/storage/texture_storage.cpp:850]: I see, I'll have to slightly refactor it...

**Comment by alula** [comment]
NoiseTexture3Ds seem to work fine now and implementing `texture_2d_layer_get()` and `texture_3d_get()` is straightforward on OpenGL due to `glGetTexImage()` availability but a bit tricky on GLES.

From a quick look it seems like it would need a variant of the "copy.glsl" shader with sampler3D, what would be your preferred way to implement that?

**Comment by clayjohn** [comment]
I would do something similar to how it was done in 3.x https://github.com/godotengine/godot/blob/4461f38c0b778ae321f57bbe79179923ec2377d9/drivers/gles3/rasterizer_storage_gles3.cpp#L1039

File: drivers/gles3/storage/texture_storage.cpp [hunk 2]
```diff
@@ -808,8 +817,44 @@ void TextureStorage::texture_2d_layered_initialize(RID p_texture, const Vector<R
...
 
-void TextureStorage::texture_3d_initialize(RID p_texture, Image::Format, int p_width, int p_height, int p_depth, bool p_mipmaps, const Vector<Ref<Image>> &p_data) {
-	texture_owner.initialize_rid(p_texture, Texture());
+void TextureStorage::texture_3d_initialize(RID p_texture, Image::Format p_format, int p_width, int p_height, int p_depth, bool p_mipmaps, const Vector<Ref<Image>> &p_data) {
+	ERR_FAIL_COND(p_data.size() == 0);
+
+	Image::Image3DValidateError verr = Image::validate_3d_image(p_format, p_width, p_height, p_depth, p_mipmaps, p_data);
+	if (verr != Image::VALIDATE_3D_OK) {
+		ERR_FAIL_MSG(Image::get_3d_image_validation_error_text(verr));
+	}
```
Comment (AThousandShips) [inline drivers/gles3/storage/texture_storage.cpp:826]:
```suggestion
	ERR_FAIL_COND_MSG(verr != Image::VALIDATE_3D_OK, Image::get_3d_image_validation_error_text(verr));
```

**Comment by alula** [comment]
That should be everything I guess?

**Review by alula — COMMENTED** [review]
I've applied the code review changes in separate commit, but it's not showing up here for me for some reason?

**Comment by alula** [comment]
GitHub moment

File: drivers/gles3/storage/texture_storage.cpp [hunk 3]
```diff
@@ -1055,6 +1111,153 @@ Ref<Image> TextureStorage::texture_2d_get(RID p_texture) const {
...
+	glDepthFunc(GL_LEQUAL);
+	glColorMask(1, 1, 1, 1);
+	glActiveTexture(GL_TEXTURE0);
+	glBindTexture(GL_TEXTURE_2D_ARRAY, texture->tex_id);
+
+	glViewport(0, 0, texture->alloc_width, texture->alloc_height);
+	glClearColor(0.0, 0.0, 0.0, 0.0);
+	glClear(GL_COLOR_BUFFER_BIT);
+
+	CopyEffects::get_singleton()->copy_to_rect_3d(Rect2i(0, 0, 1.0, 1.0), p_layer, Texture::TYPE_LAYERED);
```
Comment (AThousandShips) [inline drivers/gles3/storage/texture_storage.cpp:1153]:
```suggestion
	CopyEffects::get_singleton()->copy_to_rect_3d(Rect2i(0, 0, 1, 1), p_layer, Texture::TYPE_LAYERED);
```

File: drivers/gles3/storage/texture_storage.cpp [hunk 4]
```diff
@@ -1055,6 +1111,153 @@ Ref<Image> TextureStorage::texture_2d_get(RID p_texture) const {
...
+		glViewport(0, 0, width, height);
+		glClearColor(0.0, 0.0, 0.0, 0.0);
+		glClear(GL_COLOR_BUFFER_BIT);
+
+		for (int layer = 0; layer < depth; layer++) {
+			data.resize(data_size * 2); //add some memory at the end, just in case for buggy drivers
+			uint8_t *w = data.ptrw();
+
+			float layer_f = layer / float(depth);
+			CopyEffects::get_singleton()->copy_to_rect_3d(Rect2i(0, 0, 1.0, 1.0), layer_f, Texture::TYPE_3D, mipmap_level);
```
Comment (AThousandShips) [inline drivers/gles3/storage/texture_storage.cpp:1199]:
```suggestion
			CopyEffects::get_singleton()->copy_to_rect_3d(Rect2i(0, 0, 1, 1), layer_f, Texture::TYPE_3D, mipmap_level);
```

File: drivers/gles3/storage/texture_storage.cpp [hunk 5]
```diff
@@ -101,24 +106,28 @@ TextureStorage::TextureStorage() {
...
-			default_gl_textures[DEFAULT_GL_TEXTURE_CUBEMAP_BLACK] = texture_allocate();
-			texture_2d_layered_initialize(default_gl_textures[DEFAULT_GL_TEXTURE_CUBEMAP_BLACK], images, RS::TEXTURE_LAYERED_CUBEMAP);
+			default_gl_textures[DEFAULT_GL_TEXTURE_3D_BLACK] = texture_allocate();
+			texture_3d_initialize(default_gl_textures[DEFAULT_GL_TEXTURE_3D_BLACK], image->get_format(), 4, 4, 4, false, images);
 		}
 
 		{ // transparent black
 			Ref<Image> image = Image::create_empty(4, 4, true, Image::FORMAT_RGBA8);
-			image->fill(Color(0, 0, 0, 0));
+			image->fill(Color());
```
Comment (AThousandShips) [inline drivers/gles3/storage/texture_storage.cpp:130]:
```suggestion
			image->fill(Color(0, 0, 0, 0));
```
You seem to have changed the wrong line

File: drivers/gles3/storage/texture_storage.cpp [hunk 6]
```diff
@@ -101,19 +106,23 @@ TextureStorage::TextureStorage() {
...
 			}
+			default_gl_textures[DEFAULT_GL_TEXTURE_CUBEMAP_BLACK] = texture_allocate();
+			texture_2d_layered_initialize(default_gl_textures[DEFAULT_GL_TEXTURE_CUBEMAP_BLACK], images, RS::TEXTURE_LAYERED_CUBEMAP);
+		}
 
-			default_gl_textures[DEFAULT_GL_TEXTURE_3D_BLACK] = texture_allocate();
-			texture_3d_initialize(default_gl_textures[DEFAULT_GL_TEXTURE_3D_BLACK], image->get_format(), 4, 4, 4, false, images);
+		{
+			Ref<Image> image = Image::create_empty(4, 4, false, Image::FORMAT_RGBA8);
+			image->fill(Color(0, 0, 0, 1));
```
[the remark this answers is not in the document]
Comment (AThousandShips) [reply drivers/gles3/storage/texture_storage.cpp:118]: Mixed up with the one below

**Comment by alula** [comment]
rebased

**Comment by alula** [comment]
Fixed an issue I found while testing my project on Web target, any updates on this PR by the way?

File: drivers/gles3/storage/texture_storage.cpp [hunk 7]
```diff
@@ -1063,6 +1119,153 @@ Ref<Image> TextureStorage::texture_2d_get(RID p_texture) const {
...
+
+		width = MAX(1, width >> 1);
+		height = MAX(1, height >> 1);
+		depth = MAX(1, depth >> 1);
+	}
+
+	return ret;
+}
+
+Vector<Ref<Image>> TextureStorage::texture_3d_get(RID p_texture) const {
```
Comment (clayjohn) [inline drivers/gles3/storage/texture_storage.cpp:1231]: I would prefer to keep the implementation closer to the RD renderer and cache the texture. That way we can avoid expensive GPU readback as much as possible

https://github.com/clayjohn/godot/blob/1b80f21abff039dbf3e319698d118712c3e4f77f/servers/rendering/renderer_rd/storage_rd/texture_storage.cpp#L1332

The RD renderer caches the slice info for the texture and the raw data so that the images can be reconstructed when needed. This approach makes sense for Texture3D since it is never used as a framebuffer. So caching the data is fine (it just needs to e updated when calling ``texture_3d_update()``)

**Comment by QbieShay** [comment]
Hey :wave: 

This has been postponed to 4.3 at the time of 4.2, are you still available to update this PR @alula ?

Please let us know so we can organise and align on the implementation ^^

**Comment by alula** [comment]
Oh yes, I'm still around, I'll update it soon!

**Comment by clayjohn** [comment]
Hi! This has become a blocker for other work that needs to get finished on the compatibility backend. So I'm going to make the necessary changes and push directly to this PR

**Comment by alula** [comment]
@clayjohn alright, I've been busy with irl stuff and went on trip and totally forgot about finishing this PR oops...

File: drivers/gles3/storage/texture_storage.cpp (hunk 7 above)
Comment (alula) [reply drivers/gles3/storage/texture_storage.cpp:1231]: Since OpenGL doesn't have direct buffer access I think that my approach with caching `Ref<Image>` objects that are being uploaded to the GPU should work well?

**Comment by clayjohn** [comment]
> @clayjohn alright, I've been busy with irl stuff and went on trip after my last comment and totally forgot about finishing this PR, oops... 😅

No worries!

**Comment by alula** [comment]
rebased

File: drivers/gles3/storage/texture_storage.cpp (hunk 7 above)
Comment (clayjohn) [reply drivers/gles3/storage/texture_storage.cpp:1231]: I agree. I think caching makes sense here.

**Review by clayjohn — APPROVED** [review]
Hey, thanks for rebasing and updating based on my last comment. 

Right after commenting earlier I realized we could get by a little longer without 3D textures. So thank you for taking the initiative back and finishing this PR. 

It looks great to me overall. The final step before merging it is to "squash" all the commits into one commit. We describe how to that here: https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase

We like to have only one commit per PR in order to keep our git history clean and easy to navigate. Please let me know if you run into any trouble or want me to finish it off for you. I feel bad saying I would take over and then leaving it to you to finish again.

**Review by AThousandShips — APPROVED** [review]

**Comment by alula** [comment]
done

> Hey, thanks for rebasing and updating based on my last comment.
> 
> Right after commenting earlier I realized we could get by a little longer without 3D textures. So thank you for taking the initiative back and finishing this PR.
> 
> It looks great to me overall. The final step before merging it is to "squash" all the commits into one commit. We describe how to that here: https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase
> 
> We like to have only one commit per PR in order to keep our git history clean and easy to navigate. Please let me know if you run into any trouble or want me to finish it off for you. I feel bad saying I would take over and then leaving it to you to finish again.

**Comment by akien-mga** [comment]
Thanks!
