### PR TITLE
Fixed errors in AnimationPlayerEditor when switching current_animation in the inspector

### LINKED ISSUE #34021: Errors in AnimationPlayer editor when changing the current animation in the inspector
**Godot version:**
Master 1b40a95b6f34d4024c732ef68b3ba96e4bd6e6f1

**OS/device including version:**
Windows 10

**Issue description:**
When switching `current_animation` directly in the inspector while in the animation player editor, an error occurs in some cases:
```
ERROR: get_current_animation_position: Condition ' !playback.current.from ' is true. returned: 0
   At: scene/animation/animation_player.cpp:1365
```

**Steps to reproduce:**
Setup:
- Create an `AnimationPlayer` node with at least one playable animation

Repro case 1:
- Set `current_animation` to any animation to play
- Set `current_animation` to "[stop]"
- Observe error

Repro case 2:
- Set `current_animation` to any animation to play
- Stop the animation from playing in the track editor
- Start the animation again in the track editor
- Observe error

**Minimal reproduction project:**
[animation-stop.zip](https://github.com/godotengine/godot/files/3907310/animation-stop.zip)

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
This change handle cases where the current animation has been changed in the inspector property itself, and the player can't retrieve the last played animation and its position.

Case 1: start and stop an animation in the inspector
Case 2: start an animation in the inspector, then stop and start again in the track editor

Fixes #34021

### CODE REVIEW

File: editor/plugins/animation_player_editor_plugin.cpp [hunk 1]
```diff
@@ -85,8 +85,11 @@ void AnimationPlayerEditor::_notification(int p_what) {
 				track_editor->set_anim_pos(player->get_current_animation_position());
 				EditorNode::get_singleton()->get_inspector()->refresh();
 
+			} else if (!player->is_valid()) {
+				// Reset timeline when the player has been stopped externally
+				frame->set_value(0);
 			} else if (last_active) {
-				// Need the last frame after it stopped.
+				// Need the last frame after it stopped
```
Comment (akien-mga) [inline editor/plugins/animation_player_editor_plugin.cpp]: It's actually the current consensus that we do end comments with a dot.

Comment (pouleyKetchoupp) [reply editor/plugins/animation_player_editor_plugin.cpp]: Sorry for that, just reverted it.

**Comment by akien-mga** [comment]
Thanks!

File: editor/plugins/animation_player_editor_plugin.cpp (hunk 1 above)
Comment (YeldhamDev) [reply editor/plugins/animation_player_editor_plugin.cpp]: On that topic, could you add a dot to the end of the comment you added?

Comment (pouleyKetchoupp) [reply editor/plugins/animation_player_editor_plugin.cpp]: Yep. Good point.

Comment (YeldhamDev) [reply editor/plugins/animation_player_editor_plugin.cpp]: Also, I literally didn't pay attention that this was already merged, sorry... :P
