### PR TITLE
GDScript: Fix implicit conversions for function returns

### LINKED ISSUE #65286: Can't return an `int` in `float`-returning functions
### Godot version

4.0 alpha 15

### System information

linux

### Issue description

```gdscript
func f() -> float:
    return 0
```
image

It may make sense to error out on implicit `float` -> `int` conversion but in this example `int`s should be casted automatically and without warning, or at least I don't see why they would not.

### Steps to reproduce

see above

### Minimal reproduction project

_No response_

### LINKED ISSUE #71971: GDScript 2.0: Returned Array value isn't converted to Packed*Array
### Godot version

4.0beta14

### System information

Windows 10

### Issue description

Returned Array value isn't converted to Packed*Array

### Steps to reproduce

```
var string_array: PackedStringArray = ["test"] # valid
var int_array: PackedInt32Array = [3] # valid

func get_packed_string_array() -> PackedStringArray:
	return ["test"] #error


func get_packed_int_array() -> PackedInt32Array:
	return [3] #error
```

Line 8:Cannot return value of type "Array" because the function return type is "PackedStringArray".
Line 12:Cannot return value of type "Array" because the function return type is "PackedInt32Array".

### Minimal reproduction project

[return_bug.zip](https://github.com/godotengine/godot/files/10490367/return_bug.zip)

### PR DESCRIPTION
**Pull request by vonagam**
VM supports conversions of returned values in functions to a specified return type but a check for compatibility in `resolve_return` was not allowing implicit conversions. Fixed it.

```gdscript
func returns_float() -> float:
  return 1
  
func returns_packed_array() -> PackedStringArray:
  return ['a'] 
```

Did not know that such conversions were not allowed already. #71844 makes conversions for constant return values (like in `returns_float` here) to happen only once and during compilation.

Also made handling of untyped/variants - marking of unsafe lines and weak source downgrades - consistent with initializers and assignments. Theoretically it is possible to unify all cases where "value type meets specified type" - initializers/assignments/returns/casts/arguments.

Fixes #65286.
Fixes #71971.

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -1905,17 +1905,14 @@ void GDScriptAnalyzer::resolve_return(GDScriptParser::ReturnNode *p_return) {
...
+	bool has_expected_type = parser->current_function != nullptr;
+	if (has_expected_type) {
 		expected_type = parser->current_function->get_datatype();
-		has_expected_type = true;
 	}
 
 	if (p_return->return_value != nullptr) {
 		reduce_expression(p_return->return_value);
 		if (p_return->return_value->type == GDScriptParser::Node::ARRAY) {
-			// Check if assigned value is an array literal, so we can make it a typed array too if appropriate.
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:1918]: Any reason to remove this comment?

File: modules/gdscript/gdscript_analyzer.cpp [hunk 2]
```diff
@@ -1925,29 +1922,41 @@ void GDScriptAnalyzer::resolve_return(GDScriptParser::ReturnNode *p_return) {
 		}
 		result = p_return->return_value->get_datatype();
 	} else {
-		// Return type is null by default.
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:1928]: Any reason to remove this comment as well?

File: modules/gdscript/gdscript_analyzer.cpp [hunk 3]
```diff
@@ -1925,29 +1922,41 @@ void GDScriptAnalyzer::resolve_return(GDScriptParser::ReturnNode *p_return) {
...
 		result.is_constant = true;
 	}
 
 	if (has_expected_type) {
-		expected_type.is_meta_type = false;
-		if (expected_type.is_hard_type()) {
-			if (!is_type_compatible(expected_type, result)) {
-				// Try other way. Okay but not safe.
+		if (expected_type.is_variant()) {
+			// variant expectation
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:1933]: This is style nitpick but ideally comments should be in sentence case and end with a period.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 4]
```diff
@@ -1925,29 +1922,41 @@ void GDScriptAnalyzer::resolve_return(GDScriptParser::ReturnNode *p_return) {
...
+			if (!expected_type.is_hard_type()) {
+				// untyped expectation
+				mark_node_unsafe(p_return);
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:1936]: This enters in our discussion "what's a green line". If a function does not declare any return type, it should be Variant by default, so returning anything is safe.

**Review by vnen — CHANGES_REQUESTED** [review]
Other than the small issues it's fine.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 2 above)
Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp:1928]: Next lines obviously set things to be null, so the comment does not add anything. Does it?

File: modules/gdscript/gdscript_analyzer.cpp (hunk 1 above)
Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp:1918]: Comment does not add anything of value in my opinion, in array PR it is pretty obvious what the thing does:
```cpp
if (p_return->return_value->type == GDScriptParser::Node::ARRAY && has_expected_type && expected_type.has_container_element_type()) {
  update_array_literal_element_type(static_cast<GDScriptParser::ArrayNode *>(p_return->return_value), expected_type.get_container_element_type());
}
```
If it is not clear than maybe the name of the function should be changed.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 3 above)
Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp:1933]: Yeah, personally I do not like comments, I put them here to explicitly show what is current condition because there are a lot of `if-else`. And those comments made to match same in `reduce_assignment` with the idea that the logic can be moved in a separate function later.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 4 above)
Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp:1936]: Yes. To recap my opinion: the return is typed as Variant, yes, but weak one and it does not represent what user really wants. Unlike hard Variant which is a specified type with explicit intention, weak one is just a fallback in absence of a type but most likely does not reflect user's expectation. So since we don't know what type user has in mind it should be marked as unsafe. To make it safe they need to specify the type.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 1 above)
Comment (Zireael07) [reply modules/gdscript/gdscript_analyzer.cpp:1918]: I'd keep the comment

Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp]: I put the comment back. 

`update_array_literal_element_type` has only one function - to update an array literal type to a specified type, that's it. Commented code is a single `if` block with a single line with that method, there's no mystery as to when, why and what it does.

But ok.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 2 above)
Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp]: Put the comment back. Do not agree that there is any value in it, but ok.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 4 above)
Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp]: Done. Removed that logic.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 3 above)
Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp]: Done. Removed comments.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 2 above)
Comment (vnen) [reply modules/gdscript/gdscript_analyzer.cpp]: Even if that's the case, removing (non-incorrect) comments in code you're not changing just generates noise and isn't helpful.

**Review by vnen — APPROVED** [review]

File: modules/gdscript/gdscript_analyzer.cpp (hunk 2 above)
Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp]: I consider myself updating whole `resolve_return` in this PR. The function is small, code before and after was changed.

Even if all people were in agreement that the comment is meh, it still would be awkward for me to open a separate PR specifically about removing a comment, useless change by itself.

**Comment by akien-mga** [comment]
Needs rebase.

**Comment by akien-mga** [comment]
Needs another rebase to pass CI, I fixed the GDScript test error.

**Comment by akien-mga** [comment]
Thanks!
