### PR TITLE
[Windows, 4.0] Detect new Windows Terminal and disable unsupported set_console_visible code.

### LINKED ISSUE #55971: Game Output/Log goes to new terminal window on start and closes on game end
### Godot version

3.4.1-rc3 Windows Mono 

### System information

Win10 64bit, Radeon Vega 64, GLES3

### Issue description

Just upgraded from 3.4.1-rc2 to 3.4.1-rc3. Now each time the developed application  is started a new terminal window is open, output from the application  goes there and when the application  is closed the new terminal window gets closed immediately taking any output with it.
This is reproducible with the Control Gallery demo app and switching back to 3.4.1-rc2 restores the old behaviour of having the Godot log terminal also showing the application output. 

Not sure if that is the intended behaviour or a new regression, but the new log unfortunately takes the any final crash exception stack output with it, in case of crashes, which are not mirrored in the editors internal log window. 

### Steps to reproduce

Start Godor 3.4.1-rc3 with Control Gallery App. Start App and close it. Retry with 3.4.1-rc2. 

### Minimal reproduction project

Control Gallery

### PR DESCRIPTION
**Pull request by bruvzg**
- Improves #55924, new terminal will be opened only when using new Windows Terminal.
- Disables unsupported `set_console_visible` / `Toggle System Console` when using new Windows Terminal.

Tested on Windows 11 21H1(22000.348) with:
- Windows Console Host (Old terminal)
- ConEmu 210912
- Windows Terminal 1.11.2921.0

*Bugsquad edit:* Closes #55971.

### CODE REVIEW

**Review by mhilbrunner — APPROVED** [review]

File: platform/windows/os_windows.cpp [hunk 1]
```diff
@@ -467,6 +467,16 @@ Error OS_Windows::execute(const String &p_path, const List<String> &p_arguments,
 	return OK;
 };
 
+bool OS_Windows::_is_win11_terminal() const {
+	HANDLE hStdOut = GetStdHandle(STD_OUTPUT_HANDLE);
+	DWORD dwMode = 0;
+	if (GetConsoleMode(hStdOut, &dwMode)) {
+		return ((dwMode & ENABLE_VIRTUAL_TERMINAL_PROCESSING) == ENABLE_VIRTUAL_TERMINAL_PROCESSING);
```
Comment (mhilbrunner) [inline platform/windows/os_windows.cpp:474]: So if I understand it right, this is mostly a heuristic: ENABLE_VIRTUAL_TERMINAL_PROCESSING was added for the Windows Terminal in the Windows 10 Anniversary update, and isn't enabled by default in the legacy console, but _is_ enabled by default in Windows Terminal.

Thus we can check if it is enabled and assume we're likely running in a Windows Terminal. In theory, we could also use in another console that has this turned on manually.

This looks acceptable to me, but maybe we could have a comment explaining/documenting this? Maybe we also want to link to the original Github issue for future readers. (https://github.com/godotengine/godot/issues/54076)

Comment (akien-mga) [reply platform/windows/os_windows.cpp:474]: Adding a short comment sounds good yeah. The issue can be referenced as `GH-54076` in text, that's how I do it usually (it's easy enough to get to the URL from there, without having to hardcode all kinds of github.com all over the place).

Comment (akien-mga) [reply platform/windows/os_windows.cpp:474]: That being said, we might prefer to wait for the approach taken in https://github.com/godotengine/godot/pull/55987 and thus only merge this workaround for `3.4`?

Comment (akien-mga) [reply platform/windows/os_windows.cpp:474]: I'll merge as is for now as I want to cherry-pick #55967 for 3.4.1, and it's good to keep things consistent. Comments can be added later, or won't be needed if we go with the approach in #55987 and thus undo this workaround.

**Comment by akien-mga** [comment]
Thanks!
