### PR TITLE
Fix `Control` nodes emitting unnecessary `resized` signals

### LINKED ISSUE #48935: Tweening a `rect_position` changes `rect_size`
**Godot version:**

3.3 / 3.3.1

**OS/device including version:**

Windows 10

**Issue description:**

Tweening a `rect_position` changes `rect_size`.
Either that, or it's causing `rect_size` to no longer be rounded properly.

After the tween, my output is:
```
rect_size: (16.000031, 22.000006)
rect_min_size: (16, 22)
```
The `rect_size` value changes slightly every time I run the game.
Before the tween, they were the same. 

**Steps to reproduce:**
1. Run the example project.
2. Press `Enter` and wait for the `breakpoint`. (For me, the `breakpoint` is reached every time)

**Minimal reproduction project:**

[Tween Resize Bug.zip](https://github.com/godotengine/godot/files/6524364/Tween.Resize.Bug.zip)

### LINKED ISSUE #93832: GraphNode raises excessive `resized` events
### Tested versions

4.3.beta2

### System information

Windows 11

### Issue description

When using the `GraphEdit` scroll bars to change the scroll position within the graph canvas, all `GraphNode` instances on the canvas emit a `resized` event.  As the `GraphNode` is not being resized and only the scroll offset is being adjusted, it makes no sense why a `GraphNode` raises a `resized` event.

This only seems to apply to `GraphNode` instances within the viewport of the GraphEdit canvas.  Once the node has left the view of the canvas, it stops emitting the signal. 

In Godot 4.3, there is the new `resized_end` event; however, for code that needs to be compatible with Godot 4.2, this signal isn't possible for Godot 4.2 and the only viable option is `resized`.

### Steps to reproduce

1. Create a GraphEdit 
2. Add a GraphNode to the canvas
3. Connect a signal callback to the `resized` signal of the GraphNode
4. Move the scroll bars in the GraphEdit, the `resized` events are fired for the node instances.

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #93834: GraphNode `resize_request` signal emitted with incorrect min sizes
### Tested versions

4.2.1.stable & 4.2.2.stable, and 4.3.beta2

### System information

Windows 11

### Issue description

When connecting to the `GraphNode` signal `resize_request`, the signal is emitted even when the size of the `GraphNode` can no longer shrink due to content, including to the point where it can emit `(-x,-y)` if the user continues to draw to the top-left and beyond of the node's rect area.

### Steps to reproduce

1. Add a GraphEdit canvas.
2. Add a GraphNode to the `GraphEdit`, enabling resizability on the GraphNode
3. Connect a signal to the `resize_request` event to track the supplied size.
4. Drag the bottom right corner of the GraphNode toward the top-left, continuing to move the cursor even after the node stops shrinking, noticing that the signal continues to emit events, including negative X/Y values.

https://github.com/godotengine/godot/assets/3255568/fd33b3b0-291a-4ccc-83e3-fbf32d0cc016

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Geometror**
Fix `Control` nodes emitting unnecessary `resized` signals due to floating point precision issues.

Fixes #93832
Might fix #48935 (for 4.3).

### CODE REVIEW

**Comment by Naros** [comment]
Hi @Geometror, tested but it behaves strangely in the `GraphEdit`:
image

I don't see resize events, but the curves don't redraw.

**Comment by Geometror** [comment]
@Naros Should work now, I just missed a code path while restructuring the method.

**Review by Naros — APPROVED** [review]
Works as expected, I don't notice any unnecessary resize events and the GraphEdit works when panning, moving nodes, scrolling the canvas both with/without snapping.  👍 Will this be backported to 4.2 as well?

File: scene/gui/control.cpp [hunk 1]
```diff
@@ -1732,31 +1732,26 @@ void Control::_size_changed() {
...
-	bool size_changed = new_size_cache != data.size_cache;
+	bool pos_changed = !new_pos_cache.is_equal_approx(data.pos_cache);
+	bool size_changed = !new_size_cache.is_equal_approx(data.size_cache);
 
-	data.pos_cache = new_pos_cache;
-	data.size_cache = new_size_cache;
+	if (pos_changed) {
+		data.pos_cache = new_pos_cache;
+		_notify_transform();
+		item_rect_changed(false);
```
Comment (akien-mga) [inline scene/gui/control.cpp:1741]: What's the impact of calling these twice in the case where `pos_changed && size_changed && is_inside_tree()`? That seems to be the only logic change after the refactoring.

Comment (Geometror) [reply scene/gui/control.cpp]: That would emit the signal two times, which shouldn't be. I did some changes so that the code is as similar as possible to how it was before.

**Review by akien-mga — APPROVED** [review]

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
