### PR TITLE
Fix `ProgressDialog` errors during first scan.

### LINKED ISSUE #100900: At startup `ERROR: editor/progress_dialog.cpp:169 - Do not use progress dialog (task) while flushing the message queue or using call_deferred()!`
### Tested versions

- Happens in v4.4.dev7.mono.official [46c8f8c5c]

### System information

Godot v4.4.dev7.mono - Windows 10 (build 19045) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 32.0.15.6094) - Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 threads)

### Issue description

I get this error sometimes at startup. My project is mostly GDScript code with two C# scripts.

This _might_ be related to https://github.com/godotengine/godot/issues/96550, at least the error message is the same.

```
Godot Engine v4.4.dev7.mono.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started on port 6006 ---
--- GDScript language server started on port 6005 ---
  ERROR: editor/progress_dialog.cpp:169 - Do not use progress dialog (task) while flushing the message queue or using call_deferred()!
  ERROR: editor/progress_dialog.cpp:203 - Condition "!tasks.has(p_task)" is true. Returning: canceled
  ERROR: editor/progress_dialog.cpp:203 - Condition "!tasks.has(p_task)" is true. Returning: canceled
  ERROR: editor/progress_dialog.cpp:203 - Condition "!tasks.has(p_task)" is true. Returning: canceled
  ERROR: editor/progress_dialog.cpp:203 - Condition "!tasks.has(p_task)" is true. Returning: canceled
  ERROR: editor/progress_dialog.cpp:203 - Condition "!tasks.has(p_task)" is true. Returning: canceled
  ERROR: editor/progress_dialog.cpp:203 - Condition "!tasks.has(p_task)" is true. Returning: canceled
  ERROR: editor/progress_dialog.cpp:226 - Condition "!tasks.has(p_task)" is true.
[LSP] Connection Taken
```

### Steps to reproduce

Unfortunately I have no idea. I _feel_ that I have mostly seen this error when starting Godot first time after booting the computer. I did managed to get the error once by repeatedly starting Godot while Microsoft Defender was scanning the drive thus making everything slow. But even then I got the error only once with maybe 15 tries.

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #108446: Editor error messages on startup
### Tested versions

- Reproducible in 4.5 dev 2 - 4.5 beta 3
- Not reproducible in 4.5 dev 1

### System information

Godot v4.5.dev2.mono - CachyOS Linux #1 SMP PREEMPT_DYNAMIC Sun, 06 Jul 2025 09:33:29 +0000 on Wayland - Wayland display driver, Multi-window, 2 monitors - OpenGL 3 (Compatibility) - AMD Radeon RX 6600 (radeonsi, navi23, LLVM 20.1.7, DRM 3.63, 6.15.5-2-cachyos) - AMD Ryzen 7 5700G with Radeon Graphics (16 threads)

### Issue description

ERROR: editor/progress_dialog.cpp:183 - Do not use progress dialog (task) while flushing the message queue or using call_deferred()!
ERROR: (6) editor/progress_dialog.cpp:217 - Condition "!tasks.has(p_task)" is true. Returning: canceled
ERROR: editor/progress_dialog.cpp:240 - Condition "!tasks.has(p_task)" is true.

### Steps to reproduce

NA

### Minimal reproduction project (MRP)

NA

### PR DESCRIPTION
**Pull request by WhalesState**
* Fixes: https://github.com/godotengine/godot/issues/108446
* Fixes: https://github.com/godotengine/godot/issues/100900

Note: On Windows, minimizing the window while loading the project no longer throw errors, other issues can't be reproduced since users have reported that it happens randomly and I think they have minimized the window during loading without noticing it was the main reason.

### CODE REVIEW

File: editor/gui/progress_dialog.cpp [hunk 1]
```diff
@@ -168,14 +168,14 @@ void ProgressDialog::_popup() {
 
 	Window *current_window = SceneTree::get_singleton()->get_root()->get_last_exclusive_window();
 	ERR_FAIL_NULL(current_window);
-	reparent(current_window);
+	callable_mp((Control *)this, &Control::reparent).call_deferred(current_window, true);
```
Comment (WhalesState) [inline editor/gui/progress_dialog.cpp]: Can't use reparent during first scan.

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -851,7 +851,7 @@ void EditorNode::_notification(int p_what) {
 
 			command_palette->register_shortcuts_as_command();
 
-			callable_mp(this, &EditorNode::_begin_first_scan).call_deferred();
+			EditorNode::_begin_first_scan();
```
Comment (WhalesState) [inline editor/editor_node.cpp]: First scan should be called as soon as possible after entering tree, delaying it causes issues when flushing the MessageQueue.

Comment (WhalesState) [reply editor/editor_node.cpp]: Note: This line was added here https://github.com/godotengine/godot/pull/64610, <s>so i will test with editor startup benchmark to make sure it doesn't cause any further issues.</s> 

Edit:
Benchmarks still work without any issues.

File: editor/gui/progress_dialog.cpp (hunk 1 above)
Comment (WhalesState) [reply editor/gui/progress_dialog.cpp]: I was wondering whether it's worth deferring all the `reparent` and `show` calls just to fix an issue that only affects the first scan. These calls work fine with all other tasks.

**Comment by KoBeWi** [comment]
> I think they have minimized the window during loading without noticing it was the main reason.

I don't think it's safe to assume that for both issues, but indeed, this is what triggers the error. Specifically, editor checks for `can_draw()` here (false when minimized):
https://github.com/godotengine/godot/blob/e0603aeda3ce0e15c5843f5202172a56f3ff5534/editor/editor_node.cpp#L5621-L5623
And then here for `cmdline_mode`:
https://github.com/godotengine/godot/blob/e0603aeda3ce0e15c5843f5202172a56f3ff5534/editor/editor_node.cpp#L5357-L5359
This inconsistency is what's causing the errors, but not sure if this is the only way to trigger them.

File: editor/gui/progress_dialog.cpp [hunk 3]
```diff
@@ -168,14 +168,14 @@ void ProgressDialog::_popup() {
...
 
 	// Ensures that events are properly released before the dialog blocks input.
 	bool window_is_input_disabled = current_window->is_input_disabled();
 	current_window->set_disable_input(!window_is_input_disabled);
 	current_window->set_disable_input(window_is_input_disabled);
 
-	show();
+	callable_mp((CanvasItem *)this, &CanvasItem::show).call_deferred();
```
Comment (KoBeWi) [inline editor/gui/progress_dialog.cpp]: Why this needs to be deferred?

Comment (WhalesState) [reply editor/gui/progress_dialog.cpp]: To avoid showing the dialog before `reparent`, is it ok to make it visible first then changing its parent ? I just have tried to avoid any further issues that may happen because of this.

previously the reparent happened before showing the dialog and i tried to keep it the same as before.

**Comment by WhalesState** [comment]
> > I think they have minimized the window during loading without noticing it was the main reason.
> 
> I don't think it's safe to assume that for both issues, but indeed, this is what triggers the error. Specifically, editor checks for `can_draw()` here (false when minimized):

I have found that the main issue was because first scan is deferred then `MessageQueue::flush` is called from `SceneTree::physics_process` at the same frame where the dialog is trying to show the first scan task progress, so i wonder if it's also what makes `can_draw` return false because it's solved with the current changes and I was unable to reproduce the same issue again.

File: editor/gui/progress_dialog.cpp (hunk 3 above)
Comment (KoBeWi) [reply editor/gui/progress_dialog.cpp]: Showing it earlier shouldn't cause problems, but deferring makes sense.
It would be nice if the 2 deferred calls were done together, either just moved to be one after another, or as part of a separate method (like `_reparent_and_show()` which would then be deferred instead).

File: editor/gui/progress_dialog.cpp (hunk 1 above)
Comment (KoBeWi) [reply editor/gui/progress_dialog.cpp]: If the issue is that `current_window` is setting up children at the time, you can use `is_ready()` to check if you can reparent immediately.

**Review by KoBeWi — APPROVED** [review]
Some code comments, but otherwise works correctly.

**Comment by WhalesState** [comment]
> Some code comments, but otherwise works correctly.

Applied the changes from the comments and rebased, Thank you.

**Comment by Repiteo** [comment]
Thanks!

**Comment by mihe** [comment]
This PR seems to have broken headless imports: #108990.

I'd guess headless exports as well, but I haven't checked.

**Comment by WhalesState** [comment]
> This PR seems to have broken headless imports: #108990.
> 
> I'd guess headless exports as well, but I haven't checked.

<s>* Can this be solved by reverting https://github.com/godotengine/godot/pull/103403 ? </s>

Edit: will try to track the issue.
