### PR TITLE
[C#] Improve Documentation for Typed `Godot.Collections` Wrappers

### LINKED ISSUE #102753: [C#] Need to update the documentation for the typed `Godot.Collections.Dictionary` wrapper
### Tested versions

v4.4.beta3.mono.official [06acfccf8]

### System information

Godot v4.4.beta3.mono - Windows 10 (build 19044) - Multi-window, 4 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti (NVIDIA; 32.0.15.6603) - AMD Ryzen 9 5900X 12-Core Processor (24 threads)

### Issue description

As we now have #78656 (typed dictionaries support), we should update the old comments to reflect this behavior change (that the editor will now recognize the C# type annotation for the dictionary).

### Steps to reproduce

Check [the C# source code](https://github.com/godotengine/godot/blob/ad9abe841d9bb47a397c5e1a314ced1c5abc1ccd/modules/mono/glue/GodotSharp/GodotSharp/Core/Dictionary.cs#L479).
Image

### Minimal reproduction project (MRP)

Not Applicable

### PR DESCRIPTION
**Pull request by Delsin-Yu**
Closes #102753 

This pull request includes updates to the documentation comments for the `Godot.Collections.Array<[MustBeVariant] T>` and `Godot.Collections.Dictionary<[MustBeVariant] TKey, [MustBeVariant] TValue>` wrapper types to improve clarity and accuracy.

Documentation improvements:

* [`modules/mono/glue/GodotSharp/GodotSharp/Core/Array.cs`](diffhunk://#diff-7b222db775bbaf1eb3d1102d64652196b35cef13053ca8b5a92cba18a1fd2bd2L1038-R1038): Updated the summary comment to specify that the array contains elements of type `<typeparamref name="T"/>`.
* [`modules/mono/glue/GodotSharp/GodotSharp/Core/Dictionary.cs`](diffhunk://#diff-6ad5c52c284ba0bb55706e339e12e6a0f0ece132a0bd9cb4f67203937077223cL479-R479): Updated the summary comment to specify that the dictionary contains elements of types `<typeparamref name="TKey"/>` and `<typeparamref name="TValue"/>`.

### CODE REVIEW

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Dictionary.cs [hunk 1]
```diff
@@ -476,7 +476,7 @@ internal interface IGenericGodotDictionary
     }
 
     /// <summary>
-    /// Typed wrapper around Godot's Dictionary class, a dictionary of Variant
+    /// Typed wrapper around Godot's Dictionary class, a dictionary of <typeparamref name="TKey"/> and <typeparamref name="TValue"/>
```
Comment (Delsin-Yu) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Dictionary.cs:479]: I don't think the line break style is correct here. However, we are skipping the line break check for C# source files, so neither `pre-commit` nor `CI` is triggering. What would be a better approach here?

**Review by raulsntos — COMMENTED** [review]
I don't think this change is correct. The C# types are just converting the `Variant` elements to `T` every time an element is added/removed/accessed from the collection, the underlying type stored is still `Variant`.

To be clear about what the documentation was saying:

> Typed wrapper around Godot's Array class, an array of Variant typed elements allocated in the engine in C+++.

This is describing the native C++ `Array` type that the C# type is a wrapper of. Even when the array is typed, the underlying storage is still `Variant` (`TypedArray<int32_t>` stores the `int32_t` elements as `Variant`).

This is different from packed arrays that actually store the element they are specifically designed to hold. For example, a `PackedByteArray` stores the elements as `byte`. As a result `PackedByteArray` can take less memory than `PackedInt32Array`, but `TypedArray<uint8_t>` and `TypedArray<int32_t>` will both take the same memory.

Common C# collection types such as `List<T>` or `T[]` work more like packed arrays in this sense, so I can see where the confusion may be coming from, but this is also why I think it's important to mention explicitly in the documentation that the elements are stored as `Variant` and not `T`. And all of this also applies to dictionaries.

Perhaps there's a better way to describe how these types work, but it should still be clear that the underlying type stored is `Variant` even if conceptually it feels like they store `T` elements.

**Comment by Delsin-Yu** [comment]
I have updated the documentation to clarify that the elements are only "annotated" rather than "typed"; I also added remark blocks to indicate that regardless of the type used, the elements maintain the same memory footprint.

**Review by paulloz — APPROVED** [review]
Looks good to me 👍

**Comment by Repiteo** [comment]
Thanks!
