### PR TITLE
Mono: Implement stack info for errors and exceptions

### LINKED ISSUE #14589: Godot editor debugger doesn't give full stacktrace info for Mono exceptions
*Bugsquad edit:* See #14822 for a clear description of the issue and how to fix it.

----

**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10
Godot 3.0 beta 1

**Issue description:**

When a exception occurs in a C# script, the debugger doesn't display very helpful information, such as the name of the script that caused the error, and the line where it happened.

**Steps to reproduce:**
Add a C# script to any node and try to produce a NullReferenceException in any Godot callbacks.
E.g., 
in _Ready(), 
string nullStr = null;
int i = nullStr.Length;

When you run the code, the debugger will tell you that a NullReferenceException has been raised, but it won't tell you where it happened.

**Link to minimal example project:**

### PR DESCRIPTION
**Pull request by neikeq**
Closes #14589

ss1

ss2

### CODE REVIEW

File: core/script_debugger_remote.cpp [hunk 1]
```diff
@@ -899,6 +863,41 @@ void ScriptDebuggerRemote::send_message(const String &p_message, const Array &p_
 	mutex->unlock();
 }
 
+void ScriptDebuggerRemote::send_error(const String &p_func, const String &p_file, int p_line, const String &p_err, const String &p_descr, ErrorHandlerType p_type, const Vector<ScriptLanguage::StackInfo> &p_stack_info) {
```
Comment (neikeq) [inline core/script_debugger_remote.cpp]: @reduz As I mentioned on IRC, I needed to add this function in order to display the exception stack info.

**Comment by akien-mga** [comment]
Your branch is *old*, dude ;) https://github.com/neikeq/godot/commits/the-stack-frame-madness

**Comment by neikeq** [comment]
That is discrimination against old branches.

File: core/script_language.h [hunk 2]
```diff
@@ -254,7 +254,8 @@ class ScriptLanguage {
 	virtual String debug_parse_stack_level_expression(int p_level, const String &p_expression, int p_max_subitems = -1, int p_max_depth = -1) = 0;
 
 	struct StackInfo {
-		Ref<Script> script;
+		String file;
+		String func;
 		int line;
```
Comment (neikeq) [inline core/script_language.h]: Forgot to mention I changed the StackInfo struct. It includes the file path and the function string (not necessarily the name, it can be formatted to include the signature). I also removed the script from it because it was not needing and it meant you couldn't include files outside the project.

File: editor/script_editor_debugger.cpp [hunk 3]
```diff
@@ -1616,30 +1616,33 @@ void ScriptEditorDebugger::_error_selected(int p_idx) {
...
-		int line = st[i + 1];
+		String func = st[i + 1];
+		int line = st[i + 2];
 		Array md;
 		md.push_back(st[i]);
 		md.push_back(st[i + 1]);
+		md.push_back(st[i + 2]);
 
-		String str = script.get_file() + ":" + itos(line);
+		String str = func + " in " + script.get_file() + ":line " + itos(line);
```
Comment (neikeq) [inline editor/script_editor_debugger.cpp]: Also a slightly different formatting for the stack frame.
