### PR TITLE
Fix: break, continue outside of a loop, match statement handled when parsing

### LINKED ISSUE #30401: Adding `break` outside of a loop is not highlighted by the GDScript editor
Godot 3.1.1

The following code causes a compile error but it's not highlighted in the script editor before running it:
```gdscript
extends Node

func _ready():
	break
```

```
SCRIPT ERROR: GDScript::reload: Compile Error: 'break'' not within loop
```

### PR DESCRIPTION
**Pull request by ThakeeNathees**
break outside a loop now handled when parsing and could be highlighted on the script editor.
Fix: #30401

EDIT   : continue also added
EDIT2 : match statement added
EDIT3: commits were squashed

(`m_value` in the error log was fixed in my previous PR #36704 )
break-bugJPG

### CODE REVIEW

**Comment by Calinou** [comment]
`continue` should also be allowed in a `match` statement as it can be used for fallthrough. Not sure about `break` though.

**Comment by ThakeeNathees** [comment]
continue inside a match statement also valid now, but not break,  to make the break also valid -> just un comment the `can_break = true` line
```
BlockNode *compiled_branches = alloc_node<BlockNode>();
compiled_branches->parent_block = p_block;
compiled_branches->parent_class = p_block->parent_class;
// compiled_branches->can_break = true; // Not sure
compiled_branches->can_continue = true;
```
@Calinou

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -3273,6 +3307,8 @@ void GDScriptParser::_parse_block(BlockNode *p_block, bool p_static) {
 				BlockNode *compiled_branches = alloc_node<BlockNode>();
 				compiled_branches->parent_block = p_block;
 				compiled_branches->parent_class = p_block->parent_class;
+				// compiled_branches->can_break = true; // Not sure
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp:3310]: You can remove this line, `break` is not used for `match`.

**Comment by ThakeeNathees** [comment]
done removing the line.
@vnen

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Needs a rebase.

**Comment by ThakeeNathees** [comment]
rebase applied
@akien-mga

**Comment by ThakeeNathees** [comment]
rebased with the new style format
@akien-mga

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.
