### PR TITLE
Fix Adreno 3xx compatibility for devices with newer driver versions

### LINKED ISSUE #92662: godot 4.3 beta 1 mobile is rendering inversely to the screen.
### Tested versions

4.3 beta 1

### System information

Android 10, opengl es 3.0, qualcomm snapdragon 425, Adreno  (TM) 308, 32 bits, armeabi-v7

### Issue description

When I open Godot 4.3 beta 1 the rendering window is inverted in relation to my screen. and this bug also occurs when creating games.

### Steps to reproduce

1 example: the window renders inversely to my screen.
1 exmplo

2 example: when I click on the "Remover Ausente" option, the "Criar" option is selected instead.
2 exemplo
2 exemplo 2 0

### Minimal reproduction project (MRP)

I can't say specifically why this bug occurs.

### PR DESCRIPTION
**Pull request by Alex2782**
Fixes #92662

`Adreno 3xx` devices with newer driver version are not affected.

### CODE REVIEW

File: drivers/gles3/storage/config.cpp [hunk 1]
```diff
@@ -169,8 +169,31 @@ Config::Config() {
...
+		int start_pos = gl_version.find("V@");
+		if (start_pos > 0) {
+			start_pos += 2;
+			int end_pos = gl_version.find(" ", start_pos);
+			String driver_version = gl_version.substr(start_pos, end_pos - start_pos);
+			if (driver_version.is_valid_float() && driver_version.to_float() >= 331.0) {
+				adreno_3xx_compatibility = false;
+			}
+		}
+	}
```
Comment (Calinou) [inline drivers/gles3/storage/config.cpp:196]: Personally, I'd have done `gl_version.get_slice("V@", 1).get_slice(".", 0)` to get the number in a single line. It'll still have a leading zero though.

Comment (Alex2782) [reply drivers/gles3/storage/config.cpp:196]: looks good

```cpp
String driver_version = gl_version.get_slice("V@", 1).get_slice(" ", 0);
```
**INPUT:** `OpenGL ES 3.0 V@0502.0 (GIT@09fef447e8`...
print_line **OUTPUT:** `driver_version:  0502.0 to_float:  502`

File: drivers/gles3/storage/config.cpp [hunk 2]
```diff
@@ -169,8 +169,26 @@ Config::Config() {
...
+		// OpenGL ES 3.0 V@127.0 AU@ (GIT@I96aee987eb)
+		// OpenGL ES 3.0 V@140.0 AU@ (GIT@Ifd751822f5)
+		// OpenGL ES 3.0 V@251.0 AU@08.00.00.312.030 (GIT@Ie4790512f3)
+		// OpenGL ES 3.0 V@269.0 AU@ (GIT@I109c45a694)
+		// OpenGL ES 3.0 V@331.0 (GIT@35e467f, Ice9844a736) (Date:04/15/19)
+		// OpenGL ES 3.0 V@415.0 (GIT@d39f783, I79de86aa2c, 1591296226) (Date:06/04/20)
+		// OpenGL ES 3.0 V@0502.0 (GIT@09fef447e8, I1fe547a144, 1661493934) (Date:08/25/22)
+		String driver_version = gl_version.get_slice("V@", 1).get_slice(" ", 0);
+		if (driver_version.is_valid_float() && driver_version.to_float() >= 331.0) {
+			adreno_3xx_compatibility = false;
```
Comment (clayjohn) [inline drivers/gles3/storage/config.cpp:189]: We check `adreno_3xx_compatibility` to disable GPUParticles https://github.com/godotengine/godot/blob/a7aa8356b9288fb6de1cef2980465703c63102ea/drivers/gles3/storage/particles_storage.cpp#L125

This PR will re-enable GPUParticles on certain driver versions. Can you check that GPUParticles don't cause a crash on devices with the newer driver version?

Comment (Alex2782) [reply drivers/gles3/storage/config.cpp:189]: Unfortunately I can't test it:
https://github.com/godotengine/godot/issues/92662#issuecomment-2161199477

Comment (clayjohn) [reply drivers/gles3/storage/config.cpp:189]: Actually, looking at https://github.com/godotengine/godot/pull/88816 which introduces the check, it seems that the same GPU was tested as the one reported in https://github.com/godotengine/godot/issues/92662.

That means we need to split the `adreno_3xx_compatibility` into 2 parts. I would rename it into two bools:
1. `disable_particles_workaround`: This should use the old logic and should be `true` for all 3XX devices. 
2. `flip_xy_workaround`: This should use the new logic from this PR

Comment (Alex2782) [reply drivers/gles3/storage/config.cpp:189]: I would also like to wait for the answer, 2 to 3 days. Whether `Adreno 3xx` and `V@415.0` driver also has problems with GPUParticles.


---------------------------------------

**confirmed:**
```
		// OpenGL ES 3.0 V@127.0 AU@ (GIT@I96aee987eb)
		// OpenGL ES 3.0 V@140.0 AU@ (GIT@Ifd751822f5)
		// OpenGL ES 3.0 V@269.0 AU@ (GIT@I109c45a694)
```

???	->	`// OpenGL ES 3.0 V@331.0 (GIT@35e467f, Ice9844a736) (Date:04/15/19)`

**no crash and no flip_xy bug:** https://github.com/godotengine/godot/issues/92662#issuecomment-2144031734
`// OpenGL ES 3.0 V@415.0 (GIT@d39f783, I79de86aa2c, 1591296226) (Date:06/04/20)`

Comment (clayjohn) [reply drivers/gles3/storage/config.cpp:189]: Sounds good. I have reached out to a contact at Qualcomm to see if they know exactly what driver version this was fixed in

**Comment by Alex2782** [comment]
I could not reproduce a crash when `GPUParticles2D` is active. Invisible, or only visible for a few milliseconds.
Should we remove `disable_particles_workaround` again?


<details><summary>Tests on Firebase Test Lab</summary>

---------------------------------------

Moto Z, Android API 24, **Adreno (TM) 530**, 3.2 V@145.0

https://github.com/godotengine/godot/assets/41921395/f42015a9-66ba-46e5-a801-cc0df4b9394d

-------------------------------

moto e5 play, Android API 27, **Adreno (TM) 308**, 3.0 V@269.0

https://github.com/godotengine/godot/assets/41921395/8a1d024a-a864-4eeb-afb3-4295569d84d0

</details>

----------------


_Note: on Adreno 5xx with Vulkan Mobile the GPUParticles does not work either, invisible. (`#[compute]` maybe)_

https://docs.godotengine.org/en/stable/tutorials/shaders/compute_shaders.html
> _Note that compute shader support is generally poor on mobile devices (due to driver bugs), even if they are technically supported._

**Comment by clayjohn** [comment]
> I could not reproduce a crash when GPUParticles2D is active. Invisible, or only visible for a few milliseconds.
Should we remove disable_particles_workaround again?

Looking back at #88816 I am reminded that joined72 was able to fix the crash, but the particles still do not show up. In the end, we decided to disable them because they were invisible anyway and they reduced performance a lot https://github.com/godotengine/godot/pull/88816#issuecomment-2010233214. Accordingly, I would keep the disable_particles_workaround for now

**Review by clayjohn — APPROVED** [review]
Looks good to me. We still don't know exactly what driver version the flip_xy bug was fixed in, but the code looks great. We can adjust the exact driver version in the check once we have confirmation from Qualcomm

**Comment by akien-mga** [comment]
Thanks!
