### PR TITLE
Fix `RichTextLabel` bbcode rainbow play reversed and paused

### LINKED ISSUE #85031: RichTextLabel BBCode Rainbow animation can't be played backwards or paused
### Godot version

v4.2.rc1.official [ad72de508]

### System information

Windows 11, GeForce GTX 1660 Ti, Forward+ render

### Issue description

The BBCode rainbow animation can't be played backwards correctly. Not all rainbow colors are shown, if the frequency setting `freq` is negative. (It seems that just magenta and red are moving) If the setting is 0 the animation should pause, but the whole text is just red. (Not shown in the video, but in the MRP). [Here](https://docs.godotengine.org/en/stable/tutorials/ui/bbcode_in_richtextlabel.html#rainbow) is a link to the documantation with all the settings for the rainbow animation.

https://github.com/godotengine/godot/assets/71942164/41bdfb1b-1266-4ca2-9a8b-d0f9a578c40a

### Steps to reproduce

1. Add RichTextLabel
2. Enable BBCode
3.  Enter this to the text field:
```
[rainbow freq=0.3 sat=1 val=1]This is an example text.[/rainbow]
[rainbow freq=-0.3 sat=1 val=1]This is an example text.[/rainbow]
[rainbow freq=0 sat=1 val=1]This is an example text.[/rainbow]
```

### Minimal reproduction project

[rainbow_issue.zip](https://github.com/godotengine/godot/files/13397631/rainbow_issue.zip)

### PR DESCRIPTION
**Pull request by havi05**
Adds the abillity to pause and reverse the bbcode `rainbow` animation as written in the documentation ([bbcode_in_richtextlabel](https://docs.godotengine.org/en/latest/tutorials/ui/bbcode_in_richtextlabel.html#rainbow))

Adds a new bbcode option:
 `speed` - a negative value will play the animation reversed, a positive value will play the animation forwards, and a value of `0` will pause the animation

I have added the argument `speed` so that it is possible to change the speed independently of the frequency.
Fixes https://github.com/godotengine/godot/issues/85031

### CODE REVIEW

**Review by bruvzg — APPROVED** [review]
Working as expected, code looks good.

File: scene/gui/rich_text_label.h [hunk 1]
```diff
@@ -716,7 +717,7 @@ class RichTextLabel : public Control {
 	void push_shake(int p_strength, float p_rate, bool p_connected);
 	void push_wave(float p_frequency, float p_amplitude, bool p_connected);
 	void push_tornado(float p_frequency, float p_radius, bool p_connected);
-	void push_rainbow(float p_saturation, float p_value, float p_frequency);
+	void push_rainbow(float p_saturation, float p_value, float p_frequency, float p_speed);
```
Comment (bruvzg) [inline scene/gui/rich_text_label.h:720]: Note: method isn't exposed, so no need for compatibility bind.

**Comment by akien-mga** [comment]
Thanks!
