### PR TITLE
Fix immediate mesh modifications that don't call set_mesh

### LINKED ISSUE #94151: Bounding rect does not automatically update when using an ImmediateMesh with MeshInstance2D
### Tested versions

- Reproducible in: 4.3.dev [ec02d406ca], 4.2.2.stable, 4.0.4.stable.
- Not applicable in 3.x because `ImmediateMesh` doesn't exist yet, and `ImmediateGeometry` is a `Spatial` node.

### System information

Godot v4.2.2.stable - macOS 14.5.0 - GLES3 (Compatibility) - Apple M2 Max - Apple M2 Max (12 Threads)

#### Problem

When using `ImmediateMesh` with `MeshInstance2D`, the node's bounding rect is not automatically updated when the mesh's surfaces are cleared and re-generated in a different shape. Since `CanvasItem` nodes are culled when their bounding rect is entirely outside of the viewport, this can cause the mesh to "disappear" in cases where it should actually be visible.

The animation below demonstrates the problem. The white rectangle is a `MeshInstance2D` whose `position` is animated to move around the viewport. It has an `ImmediateMesh` that is re-generated each frame with its vertices in a different location with respect to its own origin. The blue rectangle is identical except that its mesh is never updated after the first frame, so it shows the initial pose of the white rectangle's mesh for reference.

Notice how whenever the blue rectangle is fully outside the viewport (meaning the cached bounding rect for the white rectangle is outside the viewport), the white rectangle is culled from the view:
immediatemesh_bug_demo

Obviously this is a contrived example, but the real-world situation where I ran into this problem was creating a Snake-style game where the snake's body is a procedurally-generated mesh. In order to allow the player's snake to leave one side of the screen and enter from the opposite side, I need to render snake meshes that are partly outside the viewport. In most cases this means the snake mesh's initial bounding rect fully leaves the viewport before the mesh does, causing the mesh to suddenly disappear.

#### Workaround

Invoking `queue_redraw()` on the `MeshInstance2D` node whenever its mesh changes shape avoids the problem because that causes the node's bounding rect to be marked as dirty. But this is awkward since there are no drawing commands, and perhaps also inefficient due to causing additional work that otherwise would not need to be done.

#### Expected behavior

The expected behavior is that the node's bounding rect would be marked as dirty whenever the ImmediateMesh changes shape, i.e. whenever a surface is added or the surfaces are cleared.

Alternatively, if the `queue_redraw()` workaround is the intended way get the bounding rect to be updated, then that should be mentioned in the documentation.

#### Other notes

* I suspect the same issue exists if using an `ArrayMesh` with `MeshInstance2D`, but I haven't tried it yet.
* Based on a very brief test, this issue does not seem to occur when using `ImmediateMesh` with `MeshInstance3D`. But I cannot be sure that my test was valid.

### Steps to reproduce

1. Create a `MeshInstance2D` and set its mesh to an `ImmediateMesh`.
2. Create a mesh surface in the `ImmediateMesh` and allow it to be rendered for at least one frame.
3. Re-generate the mesh in a new shape/orientation that extends outside the initial mesh's bounding rect.
4. Change the position of the `MeshInstance2D` node such that it's initial bounding rect is outside of the viewport, but part of the mesh should still be visible inside the viewport. Observe that the mesh disappears as soon as it's initial bounding rect is fully outside the viewport.

The attached MRP demonstrates these steps.

### Minimal reproduction project (MRP)

[immediatemesh_bug_mrp.zip](https://github.com/user-attachments/files/16149963/immediatemesh_bug_mrp.zip)

### PR DESCRIPTION
**Pull request by tdaven**
Mesh_instance_2d has no way to know when the mesh had been modified unless you called set_mesh.  This meant that you could modify the underlying mesh without it knowing which could result in incorrect result.

Modified mesh_instance_2d to be more similar to mesh_instance_3d which connects to the changed signal of the mesh and reacts occordingly.

Resolves [94151](https://github.com/godotengine/godot/issues/94151)

### CODE REVIEW

File: scene/2d/mesh_instance_2d.cpp [hunk 1]
```diff
@@ -53,9 +53,27 @@ void MeshInstance2D::_bind_methods() {
 	ADD_PROPERTY(PropertyInfo(Variant::OBJECT, "texture", PROPERTY_HINT_RESOURCE_TYPE, "Texture2D"), "set_texture", "get_texture");
 }
 
+void MeshInstance2D::_mesh_changed() {
+	queue_redraw();
```
Comment (KoBeWi) [inline scene/2d/mesh_instance_2d.cpp:57]: If this method just calls `queue_redraw()`, then it's not really needed.

Comment (tdaven) [reply scene/2d/mesh_instance_2d.cpp:57]: Its possible there is something else that could be called but without it you still have the bug.   Manually calling this was the work around reported on the original issue.  It has always been called by set_mesh as well, it just now get called automatically if the mesh gets modified.  Likely some state gets updated during the process.  set_texture does similar.

Comment (KoBeWi) [reply scene/2d/mesh_instance_2d.cpp:57]: I mean you can remove `_mesh_changed` and call/connect to `queue_redraw()` directly.

Comment (tdaven) [reply scene/2d/mesh_instance_2d.cpp:57]: I'll investigate this some more though.  Bounding boxes looked sane when I added some debug draw.

Comment (tdaven) [reply scene/2d/mesh_instance_2d.cpp]: I removed _mesh_changed.

File: scene/resources/immediate_mesh.cpp [hunk 2]
```diff
@@ -312,6 +312,8 @@ void ImmediateMesh::surface_end() {
 	uses_uv2s = false;
 
 	surface_active = false;
+
+	emit_changed();
```
Comment (clayjohn) [inline scene/resources/immediate_mesh.cpp:316]: Was MeshInstance3D working previously? Or does this fix updating the AABB for MeshInstance3D as well?

Comment (tdaven) [reply scene/resources/immediate_mesh.cpp:316]: I'll have to try that.  I had only tried the mrp in the issue which used 2d meshes.

**Comment by tdaven** [comment]
I've investigated this much deeper and in the cases when it disappears, its getting skipped in `_attach_canvas_item_for_draw` because `p_clip_rect.intersects(p_global_rect, true)` returns no intersection.  The values for `p_clip_rect` look fine but `p_global_rect` has a position that looks suspect.  Still working on why it is wrong though.

File: scene/resources/immediate_mesh.cpp (hunk 2 above)
Comment (tdaven) [reply scene/resources/immediate_mesh.cpp:316]: To answer this question, no, I do not believe this happens with MeshInstance3d. That is because when  clear is called on the immediate mesh, that calls into the mesh storage which causes `mesh->dependency.changed_notify(Dependency::DEPENDENCY_CHANGED_MESH);` to get called. That flags the instance as dirty and on the next draw it updates its AABB so it stays up to date.

It doesn't seem the same Dependency tracking is used at all by the canvas items though.  The issue occurs because without the queue_redraw, the Rect2 that is used as bounds, doesn't get updated unless there is a draw command for the mesh (see https://github.com/godotengine/godot/blob/master/servers/rendering/renderer_canvas_render.cpp#L87).

It might be possible to add a DependencyTracker and use the same system for notifications for the canvas items as scene but where nothing else uses it I wonder if that is the right approach.  Array mesh also emits changed when you add a surface which allows anything higher to get nofiications via that means as well.  Which, like this change currently does, allows it to queue the redraw so the aabb for the canvas item gets updated(see https://github.com/godotengine/godot/blob/master/scene/resources/mesh.cpp#L1800)

Comment (clayjohn) [reply scene/resources/immediate_mesh.cpp:316]: Thanks for taking a deeper look! I agree that your approach is the correct one for 2D. It's best to maintain the same approach as ArrayMesh

**Comment by clayjohn** [comment]
> I've investigated this much deeper and in the cases when it disappears, its getting skipped in `_attach_canvas_item_for_draw` because `p_clip_rect.intersects(p_global_rect, true)` returns no intersection. The values for `p_clip_rect` look fine but `p_global_rect` has a position that looks suspect. Still working on why it is wrong though.

I suspect the bounding rect isn't updated if we don't queue a redraw

**Comment by tdaven** [comment]
> > I've investigated this much deeper and in the cases when it disappears, its getting skipped in `_attach_canvas_item_for_draw` because `p_clip_rect.intersects(p_global_rect, true)` returns no intersection. The values for `p_clip_rect` look fine but `p_global_rect` has a position that looks suspect. Still working on why it is wrong though.
> 
> I suspect the bounding rect isn't updated if we don't queue a redraw

Yup.  That is what happens.

**Review by clayjohn — APPROVED** [review]
Looks good to me!

**Comment by Repiteo** [comment]
Thanks!
