### PR TITLE
Fix Toggle Last Opened Bottom Panel not working after restoring FileSystem Dock to the side

### LINKED ISSUE #94050: Toggle Last Opened Bottom Panel not working after restoring FileSystem Dock to the side
### Tested versions

4.3 master

### System information

Godot v4.3.beta.mono (42e5b3ac2) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3742) - 11th Gen Intel(R) Core(TM) i5-11600KF @ 3.90GHz (12 Threads)

### Issue description

When the FileSystem dock is at the bottom and you move it back to the side, pressing `Ctrl + J` won't toggle the Output panel (which then becomes the first bottom panel on the list). Nothing will happen when pressing `Ctrl + J`.

cc @Calinou 

I already have a fix for that, I'll create a PR soon.

### Steps to reproduce

- Move the FileSystem dock at the bottom.
- Move the FileSystem dock back to the side.
- Press the 'Toggle Last Opened Bottom Panel' shortcut (`Ctrl + J`).
- The Bottom panel disappear and `Ctrl + J` is not working anymore.

### Minimal reproduction project (MRP)

Any project.

### PR DESCRIPTION
**Pull request by Hilderin**
- Fixes #94050

Modifications:
- When the moved panel is visible, the first panel is now opened.
- When the bottom panel is closed when the panel is moved (ex: via plugin `EditorPlugin::remove_control_from_bottom_panel`), the bottom panel is kept closed and `last_opened_control` is updated for the first panel.

### CODE REVIEW

File: editor/gui/editor_bottom_panel.cpp [hunk 1]
```diff
@@ -200,6 +201,16 @@ void EditorBottomPanel::remove_item(Control *p_item) {
 			break;
 		}
 	}
+
+	if (was_visible) {
+		// Open the first panel to ensure that if the removed dock was visible, the bottom
+		// panel will not collapse.
+		_switch_to_item(true, 0);
```
Comment (KoBeWi) [inline editor/gui/editor_bottom_panel.cpp:208]: I wonder if it's better to close the panel instead 🤔
I don't see why would you want to open Output in this case.

**Review by KoBeWi — APPROVED** [review]

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected.

File: editor/gui/editor_bottom_panel.cpp (hunk 1 above)
Comment (Calinou) [reply editor/gui/editor_bottom_panel.cpp:208]: I'm 50/50 on this one personally. I'd say we should keep this PR's behavior as-is and change it if there's significant pushback.

Comment (Hilderin) [reply editor/gui/editor_bottom_panel.cpp:208]: I tend to agree with @Calinou, this behavior prevent the closing of the bottom panel when it's already opened. But it's really a personal taste at this point.
