### PR TITLE
Fix OmniLight/SpotLight shadow opacity calculation

### LINKED ISSUE #50343: Vulkan: Disabling shadows for an OmniLight or SpotLight will not apply until the scene is reloaded
### Godot version

4.0.dev (52e3f986a)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 465.31)

### Issue description

Disabling shadows for an OmniLight or SpotLight will not apply until the scene is reloaded. Until you reload the scene, an outdated version of the shadowmap will be used.

This bug has been around since April 2020 at least.

### Steps to reproduce

- Add a PlaneMesh and a BoxMesh using two MeshInstance nodes so you can see shadows.
- Add an OmniLight3D node.
- Enable shadows on the OmniLight3D node. Move the light around.
- Disable shadows on the OmniLight3D node. Move the light around.
- Save the scene then use **Scene > Reload Saved Scene**.
- Do the above steps with SpotLight3D as well.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Geometror**
When turning off the `shadow` property of `OmniLight`/`SpotLight`, the shadow was still rendered while the shadow atlas was no longer updated. This PR fixes the shadow opacity calculation so that it behaves the same as for directional lights. There is still some room for improvement, e.g. clear/free the shadow buffer(if possible) but that would require a significantly more complex approach.
Peek 2022-08-08 18-33

*Bugsquad edit: This closes https://github.com/godotengine/godot/issues/50343.*

### CODE REVIEW

**Comment by jcostello** [comment]
Does it fix it for lightmap baking?

**Comment by Calinou** [comment]
> Does it fix it for lightmap baking?

I didn't implement `shadow_opacity` in the lightmapper. I'm not sure how difficult this would be.

File: servers/rendering/renderer_rd/renderer_scene_render_rd.cpp [hunk 1]
```diff
@@ -3136,7 +3138,9 @@ void RendererSceneRenderRD::_setup_lights(const PagedArray<RID> &p_lights, const
 		if (needs_shadow && in_shadow_range) {
 			// fill in the shadow information
 
-			light_data.shadow_opacity = light_storage->light_get_param(base, RS::LIGHT_PARAM_SHADOW_OPACITY) * shadow_opacity_fade;
+			light_data.shadow_opacity = (p_using_shadows && light_storage->light_has_shadow(base))
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/renderer_scene_render_rd.cpp:3141]: I would add this check to line 3128 above (where ``needs_shadow`` is set) that way this whole block can be skipped when shadows are disabled and shadow opacity will still get set to 0 at line 3203 below

Comment (Geometror) [reply servers/rendering/renderer_rd/renderer_scene_render_rd.cpp]: Done.

**Review by clayjohn — APPROVED** [review]

**Review by Calinou — APPROVED** [review]
Thanks!
