### PR TITLE
GDScript: Preload should make native type

### LINKED ISSUE #61159: Incorrect GDScript warning emitted at assigning a null result from a function
### Godot version

838cb598e3ef5572018d3d549c15bb27b0a5864d

### System information

Windows 11

### Issue description

The following code will generate an incorrect warning at project run:
```
extends Node

func get_param():
	return null

func _ready():
	var test = get_param()
	print(test)
```
image

The returning a `null` from a function is absolutely correct, and the result may be assigned to a variable just like a common type.

<i>Does not happen on 3.x, so this is a regression</i> 

### Steps to reproduce

Create a function which return null and try to assign the result of it to a variable

### Minimal reproduction project

[AssignmentWarningBug.zip](https://github.com/godotengine/godot/files/8718288/AssignmentWarningBug.zip)

### LINKED ISSUE #69233: GDScript 2.0: Typed Arrays raise @implicit_new error with preloaded classes
### Godot version

v4.0.beta6.official [7f8ecffa5]

### System information

Windows

### Issue description

Not a duplicate of #58203

When using a preloaded class as type hint for a typed Array godot gives the following error:
```
@implicit_new: Script class can only be set together with base class name
```

### Steps to reproduce

- add a script `a.gd` without content to your project
- add a script `b.gd` with the following content
```swift
extends Node

const A := preload("res://a.gd")

var list: Array[A] = []
```
- attach `b.gd` to your main scene
- run the project

### Minimal reproduction project

[typed_array_bug.zip](https://github.com/godotengine/godot/files/10097091/typed_array_bug.zip)

### PR DESCRIPTION
**Pull request by rune-scape**
`reduce_preload()` was calling `type_from_variant()` which made datatype with `kind` set to `BUILTIN`, not `NATIVE`
`type_from_variant()` now returns a variant type when passed a null value, fixes #61159

### CODE REVIEW

**Review by adamscott — APPROVED** [review]
Seems fine to me. You're a machine, Rune!

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -3701,11 +3701,16 @@ void GDScriptAnalyzer::const_fold_dictionary(GDScriptParser::DictionaryNode *p_d
 GDScriptParser::DataType GDScriptAnalyzer::type_from_variant(const Variant &p_value, const GDScriptParser::Node *p_source) {
 	GDScriptParser::DataType result;
 	result.is_constant = true;
-	result.kind = GDScriptParser::DataType::BUILTIN;
 	result.builtin_type = p_value.get_type();
 	result.type_source = GDScriptParser::DataType::ANNOTATED_EXPLICIT; // Constant has explicit type.
 
-	if (p_value.get_type() == Variant::OBJECT) {
+	if (p_value.get_type() == Variant::NIL) {
+		// A null value is a variant, not void.
```
Comment (akien-mga) [inline modules/gdscript/gdscript_analyzer.cpp:3708]: Is this always true? I don't know what `p_value` represents here exactly but in PropertyInfo, there's `PROPERTY_USAGE_NIL_IS_VARIANT` for the case where `Variant::NIL` should be handled as `Variant()`. Otherwise it's indeed `void`.

Comment (akien-mga) [reply modules/gdscript/gdscript_analyzer.cpp:3708]: Notably, what happens with this PR and this MRP?
```
extends Node

func get_param():
	return

func _ready():
	var test = get_param()
	print(test)
```

**Comment by akien-mga** [comment]
The CI build failure is unrelated, it's a temporary inconsistency between godot and godot-cpp, which should be fixed when #67751 is merged.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 1 above)
Comment (rune-scape) [reply modules/gdscript/gdscript_analyzer.cpp:3708]: this function is for when the analyzer is given a variant and needs to make a corresponding datatype, 
as far as i know, void is only used in specific places and is never inferred from a value
in all the places this function is used, i wouldn't expect void to be returned
and the func in that code snippet would be void, because there's no null literal to pass to `type_from_variant`
https://github.com/godotengine/godot/blob/daf168f4c821980a6a06fde67057f6a14d9e20c6/modules/gdscript/gdscript_analyzer.cpp#L1781-L1785

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
