### PR TITLE
Fix Project Manager hard crashes due to invalid access to Editor Nodes

### LINKED ISSUE #59869: godot 4 crash while creating a directory for a new project
### Godot version

v4.0.alpha.custom_build (c630c2001dbe2e25e0d372bd22ce85cdc2822eb0)

### System information

Manjaro Linux, Vulkan, AMD RADV NAVI14

### Issue description

Reproducibility: 100%

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.alpha.custom_build (c630c2001dbe2e25e0d372bd22ce85cdc2822eb0)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x42560) [0x7f7be15d7560] (??:0)
[2] EditorFileSystem::get_filesystem_path(String const&) (??:0)
[3] EditorFileDialog::_make_dir_confirm() (??:0)
[4] void call_with_variant_args_helper<EditorFileDialog>(EditorFileDialog*, void (EditorFileDialog::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (??:0)
[5] void call_with_variant_args<EditorFileDialog>(EditorFileDialog*, void (EditorFileDialog::*)(), Variant const**, int, Callable::CallError&) (??:0)
[6] CallableCustomMethodPointer<EditorFileDialog>::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[7] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[8] Object::emit_signalp(StringName const&, Variant const**, int) (??:0)
[9] Error Object::emit_signal<>(StringName const&) (??:0)
[10] AcceptDialog::_ok_pressed() (??:0)
[11] AcceptDialog::_text_submitted(String const&) (??:0)
[12] void call_with_variant_args_helper<AcceptDialog, String const&, 0ul>(AcceptDialog*, void (AcceptDialog::*)(String const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (??:0)
[13] void call_with_variant_args<AcceptDialog, String const&>(AcceptDialog*, void (AcceptDialog::*)(String const&), Variant const**, int, Callable::CallError&) (??:0)
[14] CallableCustomMethodPointer<AcceptDialog, String const&>::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[15] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[16] Object::emit_signalp(StringName const&, Variant const**, int) (??:0)
[17] Error Object::emit_signal<String>(StringName const&, String) (??:0)
[18] LineEdit::gui_input(Ref<InputEvent> const&) (??:0)
[19] Control::_call_gui_input(Ref<InputEvent> const&) (??:0)
[20] Viewport::_gui_input_event(Ref<InputEvent>) (??:0)
[21] Viewport::push_input(Ref<InputEvent> const&, bool) (??:0)
[22] Window::_window_input(Ref<InputEvent> const&) (??:0)
[23] void call_with_variant_args_helper<Window, Ref<InputEvent> const&, 0ul>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (??:0)
[24] void call_with_variant_args<Window, Ref<InputEvent> const&>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, int, Callable::CallError&) (??:0)
[25] CallableCustomMethodPointer<Window, Ref<InputEvent> const&>::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[26] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[27] DisplayServerX11::_dispatch_input_event(Ref<InputEvent> const&) (??:0)
[28] DisplayServerX11::_dispatch_input_events(Ref<InputEvent> const&) (??:0)
[29] Input::_parse_input_event_impl(Ref<InputEvent> const&, bool) (??:0)
[30] Input::parse_input_event(Ref<InputEvent> const&) (??:0)
[31] DisplayServerX11::_handle_key_event(int, XKeyEvent*, LocalVector<_XEvent, unsigned int, false>&, unsigned int&, bool) (??:0)
[32] DisplayServerX11::process_events() (??:0)
[33] OS_LinuxBSD::run() (??:0)
[34] ./godot.linuxbsd.tools.64(main+0x174) [0x55824612b10d] (??:0)
[35] /usr/lib/libc.so.6(+0x2d310) [0x7f7be15c2310] (??:0)
[36] /usr/lib/libc.so.6(__libc_start_main+0x81) [0x7f7be15c23c1] (??:0)
[37] ./godot.linuxbsd.tools.64(_start+0x25) [0x55824612aec5] (??:0)
-- END OF BACKTRACE --
```

### Steps to reproduce

- new project
- browse
- create new folder
- type a name and click OK
- crash 

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by marstaik**
Resolves: https://github.com/godotengine/godot/issues/59869

Fixes incorrect usages in project manager referencing editor nodes from this PR: https://github.com/godotengine/godot/pull/59495

Unfortunately, while EditorFileSystem is a singleton, it is also a node that is supposed to be attached to the editor node tree. Its responsibility is more of a file system watch for the editor (should probably be renamed to avoid ambiguity).

Also did some minor cleanup for unnecessary string copies.

### CODE REVIEW

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -1427,18 +1427,18 @@ void FileSystemDock::_make_dir_confirm() {
...
-		EditorNode::get_singleton()->show_warning(TTR("Could not create folder. File with that name already exists."));
-		return;
-	}
-
 	print_verbose("Making folder " + dir_name + " in " + directory);
 	DirAccessRef da = DirAccess::create(DirAccess::ACCESS_RESOURCES);
 	Error err = da->change_dir(directory);
-	if (err == OK) {
-		err = da->make_dir(dir_name);
+	ERR_FAIL_COND_MSG(!err, "Cannot open directory '" + directory + "'.");
```
Comment (akien-mga) [inline editor/filesystem_dock.cpp:1433]: The condition seems backwars, `OK` is 0 so this will fail when it succeeds.
It should fail on `err`, or more explicit, `err != OK`.

Comment (marstaik) [reply editor/filesystem_dock.cpp]: Yep yep, my bad

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Could you squash the commits?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
