### PR TITLE
Prevent to seek doubly on AnimationPlayerEditor

### LINKED ISSUE #95391: AnimationPlayer flickering when scrubbing backwards on Discrete tracks
### Tested versions

- Reproducible in: 4.3.rc3
- Not reproducible in: 4.2.x

### System information

Godot v4.3.rc3 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (Advanced Micro Devices, Inc.; 31.0.21023.2010) - AMD Ryzen 7 5700X 8-Core Processor (16 Threads)

### Issue description

As of Godot 4.3, scrubbing backwards on AnimationTracks set to Discrete causes the animated values to rapidly flicker back and forth between the nearest two keyframes, as opposed to using the left keyframe's value.

This does not happen when playing the Animation either forwards or backwards, and seems to be an editor-only bug.

flickering

### Steps to reproduce

- Create a project
- Add an AnimationPlayer Node and create a new Animation
- Add another Node, add any of its properties to the Animation
- Set the track's Update Mode to Discrete if it isn't already
- Add some keyframes, then scrub back and forth to see the flickering

### Minimal reproduction project (MRP)

[AnimationFlickerMRP.zip](https://github.com/user-attachments/files/16574091/AnimationFlickerMRP.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
- Fixes #95391

Perhaps the fix for updating the drawing (maybe https://github.com/godotengine/godot/pull/93980) caused a double seek.

As I commented in https://github.com/godotengine/godot/pull/94420, Discrete gets the value of the previous key during reverse playback. The second time of the double seek is always updated with a positive 0 value, so the key to be acquired changes immediately after the reverse playback, which is the cause of #95391.

Ideally, we would remove the method call for the second seek, but for now I fix this by preventing the seek to the same time on the editor.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: editor/plugins/animation_player_editor_plugin.cpp [hunk 1]
```diff
@@ -1295,7 +1295,7 @@ void AnimationPlayerEditor::_seek_value_changed(float p_value, bool p_timeline_o
 	}
 	pos = CLAMP(pos, 0, (double)anim->get_length() - CMP_EPSILON2); // Hack: Avoid fposmod with LOOP_LINEAR.
 
-	if (!p_timeline_only && anim.is_valid()) {
+	if (!p_timeline_only && anim.is_valid() && (player->is_valid() ? !Math::is_equal_approx(pos, player->get_current_animation_position()) : true)) {
```
Comment (KoBeWi) [inline editor/plugins/animation_player_editor_plugin.cpp:1298]: Can be simplified to
```suggestion
	if (!p_timeline_only && anim.is_valid() && (!player->is_valid() || !Math::is_equal_approx(pos, player->get_current_animation_position()))) {
```

**Comment by akien-mga** [comment]
Thanks!
