### PR TITLE
Fix underculling of occlusion culling

### LINKED ISSUE #106184: Occlusion culling doesn't cull objects from all viewing angles
### Tested versions

- Reproducible in: 4.5.dev3
- Not reproducible in: 4.4.1.stable

### System information

Godot v4.5.dev3 - Arch Linux #1 ZEN SMP PREEMPT_DYNAMIC Tue, 29 Apr 2025 09:23:22 +0000 on X11 - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - integrated Intel(R) Iris(R) Xe Graphics (RPL-P) - 13th Gen Intel(R) Core(TM) i9-13900H (20 threads)

### Issue description

Godot's occlusion culling seems to only cull objects when looking at them from certain angles. The commit that resulted in this change is 18eb1c1072eba9032efb35a3b6e1039511700548

This is a video to demonstrate it in 4.5.dev3. The camera is inside of an OccluderInstance3D with a box shape.

https://github.com/user-attachments/assets/ba5645f4-8c53-47b5-9faf-be2d25f184ad

In 4.4.1, it happens to a much lesser extent:

https://github.com/user-attachments/assets/4fe857df-30cc-4d24-92f4-98b5b42ccb17

### Steps to reproduce

1. Add some MeshInstance3Ds to a scene
2. Create a new OccluderInstance3D with a BoxOccluder3D as the shape
3. Put the camera inside the OccluderInstance3D and look around

### Minimal reproduction project (MRP)

[occlusion_culling_test.zip](https://github.com/user-attachments/files/20109939/occlusion_culling_test.zip)

### PR DESCRIPTION
**Pull request by Rudolph-B**
Fixes #106184 

This commit effectively undoes #103798, reverting to the previous behavior. To ensure that distant objects are culled correctly, I force the distance calculation to use double precision.

The video below compares this PR to v4.4.1 and v4.5.beta2 in a [test scene](https://github.com/user-attachments/files/21090324/occlusion-base.zip). In this scene, the camera is placed within a transparent occluder, so ideally, everything should be occluded at all times.

https://github.com/user-attachments/assets/eb77cb6f-4dcc-4224-8cd4-3749c1750527

### CODE REVIEW

**Comment by Rudolph-B** [comment]
@Flarkk I made some changes, since we last spoke. Can you double check it still works for you?

File: servers/rendering/renderer_scene_occlusion_cull.h [hunk 1]
```diff
@@ -82,9 +84,13 @@ class RendererSceneOcclusionCull {
 				Vector3 corner = Vector3(p_bounds[0] * c.x + p_bounds[3] * nc.x, p_bounds[1] * c.y + p_bounds[4] * nc.y, p_bounds[2] * c.z + p_bounds[5] * nc.z);
 				Vector3 view = p_cam_inv_transform.xform(corner);
 
+				// When using an orthogonal camera the closets point of an AABB to the camera is guaranteed to be a corner.
```
Comment (Calinou) [inline servers/rendering/renderer_scene_occlusion_cull.h]:
```suggestion
				// When using an orthogonal camera, the closest point of an AABB to the camera is guaranteed to be a corner.
```

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected. Code looks good to me.

I didn't notice any visual issues when flying around in the occlusion culling and mesh LOD demo. Performance-wise, I can't spot a difference on the same demo.

**Testing project:** [occlusion_culling_test_standalone.zip](https://github.com/user-attachments/files/21111059/occlusion_culling_test_standalone.zip)
(same as https://github.com/godotengine/godot/issues/106184, but can be tested from an export template)

Videos recorded with `--write-movie /path/to/file.avi --quit-after 300`:

[master.webm](https://github.com/user-attachments/assets/1ce74d55-4c1d-49cf-b472-3b7a9c746bd6)

[pr.webm](https://github.com/user-attachments/assets/c8f4f9ac-e7d8-4bfe-b2a1-011ff48e4d53)

File: servers/rendering/renderer_scene_occlusion_cull.h (hunk 1 above)
Comment (Rudolph-B) [reply servers/rendering/renderer_scene_occlusion_cull.h]: Applied

**Comment by Repiteo** [comment]
Thanks!
