### PR TITLE
Use an icon in the top Animation Key menu

### LINKED ISSUE #35420: Animation buttons in the canvas item editor are taking up too much space
**Godot version:** Godot 3.2 master (d4ac0ca15397932960403d595f2e08f926411471)

**OS/device including version:** Manjaro Linux 18.1.5

**Issue description:**
Godot 3.2 now have a new "Auto insert keys" feature but these animation buttons are taking up too much space. When I select a Sprite node, the docks on the right are "compacted".

I have a partial solution for this (#35421) but I think the best solution would be moving these buttons to the Animation dock. Example:

image

**Steps to reproduce:**
Try the editor in a "medium" resolution (mine is 720p).
Add a Sprite (no texture required) and an AnimationPlayer node.
Select the Sprite and try to toggle the Animation dock.

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by williamd1k0**
Partially fixes- #35420.

Before:
image

After:
image

I think the "EditKey" icon fits better than the "Animation" text as this menu has keyframe stuff.

### CODE REVIEW

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -5667,7 +5668,6 @@ CanvasItemEditor::CanvasItemEditor(EditorNode *p_editor) {
 	animation_hb->add_child(key_auto_insert_button);
 
 	animation_menu = memnew(MenuButton);
-	animation_menu->set_text(TTR("Animation"));
```
Comment (akien-mga) [inline editor/plugins/canvas_item_editor_plugin.cpp]: Can you give it a tooltip instead? (ideally more detailed than the name was, since it's not obvious what an Animation menu would contain).

**Comment by akien-mga** [comment]
That looks better indeed and saves on horizontal space. The main issue is that it's not immediately obvious that this one is a drop-down menu button, while the others are toggle buttons. But that's a design problem that we already have with various other buttons, so it shouldn't be blocking for this PR.

File: editor/plugins/canvas_item_editor_plugin.cpp (hunk 1 above)
Comment (williamd1k0) [reply editor/plugins/canvas_item_editor_plugin.cpp]: Done!

Comment (akien-mga) [reply editor/plugins/canvas_item_editor_plugin.cpp]: I know @YeldhamDev will want to add a missing dot at the end of the tooltip's sentence, so we might as well do it now :P

Comment (YeldhamDev) [reply editor/plugins/canvas_item_editor_plugin.cpp]: @akien-mga You know me so well! :wink:

**Comment by Calinou** [comment]
Maybe replace the pencil icon with three vertical dots (like …, but vertical)?

File: editor/plugins/canvas_item_editor_plugin.cpp (hunk 1 above)
Comment (williamd1k0) [reply editor/plugins/canvas_item_editor_plugin.cpp]: I actually copied the style of "Skeleton Options" and "Snapping Options" but forgot to capitalize words :P 

Which one do you prefer?
1. "Animation Key and Pose Options"
2. "Animation key and pose options."

Comment (YeldhamDev) [reply editor/plugins/canvas_item_editor_plugin.cpp]: Considering that it's phrased like a title, I think the first option is better.

**Comment by williamd1k0** [comment]
> The main issue is that it's not immediately obvious that this one is a drop-down menu button, while the others are toggle buttons.
> Maybe replace the pencil icon with three vertical dots (like …, but vertical)?

I think `︙` looks better for settings in general (like the "Snapping Options" button), but in this case it can be better indeed, since ellipsis means "more" after all.

**Comment by williamd1k0** [comment]
> > The main issue is that it's not immediately obvious that this one is a drop-down menu button, while the others are toggle buttons.
> 
> > Maybe replace the pencil icon with three vertical dots (like …, but vertical)?
> 
> I think `︙` looks better for settings in general (like the "Snapping Options" button), but in this case it can be better indeed, since ellipsis means "more" after all.

image

File: editor/plugins/canvas_item_editor_plugin.cpp (hunk 1 above)
Comment (williamd1k0) [reply editor/plugins/canvas_item_editor_plugin.cpp]: Changed to `"Animation Key and Pose Options"`.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
