### PR TITLE
iOS: Fix multiple issues with PVRTC import, disable ETC1

### LINKED ISSUE #28596: Export checking for android/gles2/etc
**Godot version:**

Godot 3.1.2-devel (e802da4e8)

**OS/device including version:**

MacOSX 10.13.6

**Issue description:**

I setup this project settings:
```
rendering/vram_compression/import_etc = true
rendering/vram_compression/import_pvrtc = true
rendering/quality/driver/driver_name = GLES3
rendering/quality/driver/fallback_to_gles2 = true
rendering/quality/driver/driver_name.iOS = GLES3
rendering/quality/driver/driver_name.Android = GLES2
```
Other compression formats disabled. When I try to export android apk it shows me an error:
`- Target platform requires 'ETC2' texture compression for GLES3. Enable 'Import Etc 2' in Project Settings.`

I want to use GLES3 in editor and in internal simulator. I want to export for iOS with GLES3 support. I want to export to Android with GLES2 support. My project settings are correct for that.
It doesn't allow me even export for iOS! It shows the same error message and 'Export Project' button is disabled.
I think that godot should also check *.iOS and *.Android project settings. 

**Steps to reproduce:**

**Minimal reproduction project:**

### LINKED ISSUE #28621: Ability to select Video RAM compression formats for every image
**Godot version:**

Godot 3.1.2-devel

**OS/device including version:**

MacOSX 10.13.6

**Issue description:**

I make export to iOS and to Android from one project. For iOS I use GLES3 and pvrtc compression for many textures. For Android  I use GLES2 and etc1 compression but only for textures without alpha channel (because etc1 has no support of alpha channel).
So I have to switch compression mode for many textures every time I export to one platform or to another. It takes a lot of time to generate new pvrtc textures every iOS export.

The ideal solution will be to make separate alpha channel compression for etc1 (or other alphaless formats), but I think that it may be very difficult to implement.
Another way - to detect if image has the alpha channel and use some flag in project settings to skip etc1 conversion.
Another way N2 - to be able to select which video ram compressions will be applicable for this texture.

**Steps to reproduce:**

**Minimal reproduction project:**

### LINKED ISSUE #28683: Why PVRTC textures not exported to iOS build? (GLES2)
**Godot version:**

Godot 3.1.2-devel (bc577dc0c)

**OS/device including version:**

MacOSX 10.13.6
iOS 12.1.2

**Issue description:**

I setup project for GLES2. I added one vram compressed texture. I enabled pvrtc format in project settings. When I start project on iOS simulator I have this:
```
*********** main.m
running app main
Path: /Users/vasya/Library/Developer/CoreSimulator/Devices/09FF4D0D-095B-4F33-A179-24404FD05088/data/Containers/Bundle/Application/2A84127D-C6ED-438E-848C-C95385954509/test-particles-ios.app
godot_iphone /Users/vasya/Library/Developer/CoreSimulator/Devices/09FF4D0D-095B-4F33-A179-24404FD05088/data/Containers/Bundle/Application/2A84127D-C6ED-438E-848C-C95385954509/test-particles-ios.app/test-particles-ios
cwd /Users/vasya/Library/Developer/CoreSimulator/Devices/09FF4D0D-095B-4F33-A179-24404FD05088/data/Containers/Bundle/Application/2A84127D-C6ED-438E-848C-C95385954509/test-particles-ios.app
os created
setting data dir to /Users/vasya/Library/Developer/CoreSimulator/Devices/09FF4D0D-095B-4F33-A179-24404FD05088/data/Containers/Data/Application/454B8ABE-A404-4F82-89B0-6F14BE142C85/Documents from /Users/vasya/Library/Developer/CoreSimulator/Devices/09FF4D0D-095B-4F33-A179-24404FD05088/data/Containers/Data/Application/454B8ABE-A404-4F82-89B0-6F14BE142C85/Documents
setup 0
after init super 0x7fae23d03020
2019-05-04 19:53:07.790 test-particles-ios[52284:59232871] Setting up an OpenGL ES 2 context. Based on Project Settings "rendering/quality/driver/driver_name"
******** screen size 750, 1334
after init gles 0x7fae23d03020
******** adding observer for sound routing changes
******** adding observer for keyboard show/hide
cadisaplylink: 1start animation!
******** screen size 750, 1334
******** screen size 750, 1334
OpenGL ES 2.0 Renderer: Apple Software Renderer
2019-05-04 19:53:08.316532+0300 test-particles-ios[52284:59232871] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /Users/vasya/Library/Developer/CoreSimulator/Devices/09FF4D0D-095B-4F33-A179-24404FD05088/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2019-05-04 19:53:08.334097+0300 test-particles-ios[52284:59232871] [MC] Reading from private effective user settings.
2019-05-04 19:53:08.400950+0300 test-particles-ios[52284:59233665] [aqme] 254: AQDefaultDevice (1): skipping input stream 0 0 0x0
**ERROR**: Failed loading resource: res://scene/menu-background.png
   At: core/io/resource_loader.cpp:285:_load() - Method/Function Failed, returning: RES()
**ERROR**: res://scene/Control.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://scene/menu-background.png
   At: scene/resources/resource_format_text.cpp:440:poll() - res://scene/Control.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://scene/menu-background.png
**ERROR**: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:208:load() - Condition ' err != OK ' is true. returned: RES()
**ERROR**: Failed loading resource: res://scene/Control.tscn
   At: core/io/resource_loader.cpp:285:_load() - Method/Function Failed, returning: RES()
**ERROR**: Failed loading scene: res://scene/Control.tscn
   At: main/main.cpp:1739:start() - Condition ' !scene ' is true. returned: false
```
As far as I know GLES2 on iPhones supports Pvrtc compressed textures.

**Steps to reproduce:**

**Minimal reproduction project:**

[test-particles.zip](https://github.com/godotengine/godot/files/3144601/test-particles.zip)

### PR DESCRIPTION
**Pull request by DrMoriarty**
and some other VRAM compression formats.

For iOS we enable pvrtc feature by default for both GLES2/GLES3
Etc1 for iOS doesn't have any sense, so it disabled.
Fixed checks in export editor.
Fixed pvrtc ability detection in GLES2 driver.
Fixed pvrtc encoding procedure.
Compressed stream texture now saves right image dimensions for every compression format.
Also it allows to compressor resize image on it's side to make it more optimized.
So ETC1 format becames smaller then before. Pvrtc format always saves square texture.

*Bugsquad edit: closes #28683, closes #28621, closes #28596 and maybe others*
For #38040 and #35851, the fix has been moved to #42118.

### CODE REVIEW

**Comment by DrMoriarty** [comment]
I'm not sure that it will work for master, so make PR for 3.2 branch.

File: drivers/gles2/rasterizer_storage_gles2.cpp [hunk 1]
```diff
@@ -5871,7 +5871,7 @@ void RasterizerStorageGLES2::initialize() {
 	config.float_texture_supported = config.extensions.has("GL_ARB_texture_float") || config.extensions.has("GL_OES_texture_float");
 	config.s3tc_supported = config.extensions.has("GL_EXT_texture_compression_s3tc") || config.extensions.has("WEBGL_compressed_texture_s3tc");
 	config.etc1_supported = config.extensions.has("GL_OES_compressed_ETC1_RGB8_texture") || config.extensions.has("WEBGL_compressed_texture_etc1");
-	config.pvrtc_supported = config.extensions.has("IMG_texture_compression_pvrtc") || config.extensions.has("WEBGL_compressed_texture_pvrtc");
+	config.pvrtc_supported = config.extensions.has("GL_IMG_texture_compression_pvrtc") || config.extensions.has("IMG_texture_compression_pvrtc") || config.extensions.has("WEBGL_compressed_texture_pvrtc");
```
Comment (akien-mga) [inline drivers/gles2/rasterizer_storage_gles2.cpp:5874]: I think the one without `GL_` prefix might have been a bug, so it could likely be removed. All OpenGL extensions start with `GL_` IINM.

That's also what is used in the GLES3 backend:
```
config.pvrtc_supported = config.extensions.has("GL_IMG_texture_compression_pvrtc");
```
(BTW the `WEBGL_*` check should maybe also be added for GLES3?)

**Comment by Filippopotamus** [comment]
Loading textures on iOS using GLES2 is still an issue. Is there a plan to merge this fix?

**Comment by HEAVYPOLY** [comment]
+1 this is a big one for my project.

**Comment by akien-mga** [comment]
I need contributors familiar with iOS to help review it, CC @bruvzg @naithar.

The fixes should also be ported to the `master` branch.

**Comment by Filippopotamus** [comment]
@akien-mga I have cherry picked it to our 3.2.2 fork and it does seem to fix the GLES2 loading resource issue in iOS

File: editor/import/resource_importer_texture.cpp [hunk 2]
```diff
@@ -227,21 +227,8 @@ void ResourceImporterTexture::_save_stex(const Ref<Image> &p_image, const String
...
-		f->store_16(p_image->get_width());
-		f->store_16(next_power_of_2(p_image->get_height()));
-		f->store_16(p_image->get_height());
-	} else {
-		f->store_16(p_image->get_width());
-		f->store_16(0);
-		f->store_16(p_image->get_height());
-		f->store_16(0);
-	}
-	f->store_32(p_texture_flags);
```
Comment (akien-mga) [inline editor/import/resource_importer_texture.cpp:244]: These are the only changes I'm not confident with as they impact all formats, so I want @reduz to review this more closely.

The rest of the changes seem good though (with some obvious bugfixes like in `drivers/gles2` or `platform/iphone/export/export.cpp`), so I'd suggest splitting the texture importer change to a dedicated PR and remove it here, so that the rest can be merged first.

**Comment by akien-mga** [comment]
Rebased to remove the unrelated CHANGELOG conflict, and made the commit log a bit more explicit.

Could you check if the issues referenced as fixed by this PR are still all fixed, or if some of them are fixed by #42118 instead (or only fixed once both are merged)?

File: editor/editor_export.cpp [hunk 3]
```diff
@@ -1298,6 +1298,31 @@ String EditorExportPlatform::test_etc2() const {
 	return String();
 }
 
+String EditorExportPlatform::test_etc2_or_pvrtc() const {
+
+	String driver = ProjectSettings::get_singleton()->get("rendering/quality/driver/driver_name");
+	bool driver_fallback = ProjectSettings::get_singleton()->get("rendering/quality/driver/fallback_to_gles2");
+	bool etc_supported = ProjectSettings::get_singleton()->get("rendering/vram_compression/import_etc");
```
Comment (akien-mga) [inline editor/editor_export.cpp:1305]: I guess `etc_supported` is not relevant for iOS (and now disabled by `platform/iphone/export/export.cpp` changes), so maybe it can be removed from the checks / error messages?

**Comment by DrMoriarty** [comment]
@akien-mga 
issues https://github.com/godotengine/godot/issues/38040 and https://github.com/godotengine/godot/issues/35851 related to PR #42118 
Other related to this PR

File: editor/editor_export.cpp (hunk 3 above)
Comment (DrMoriarty) [reply editor/editor_export.cpp:1305]: Yes, I think so

Comment (akien-mga) [reply editor/editor_export.cpp]: I pushed an amend that removes the `etc_supported` check.

**Review by akien-mga — APPROVED** [review]
Looks great to me. I can't really assess the `modules/pvr/texture_loader_pvr.cpp` changes but I trust that you tested them and that they make things work as they should. The rest is :+1:

**Comment by akien-mga** [comment]
I forward-ported the relevant changes for the `master` branch with #42262 (untested, and some of it might not make sense for Vulkan, hence the TODOs).

**Comment by reduz** [comment]
As most users dont go iOS out of the box, I think disabling PVRTC by default is likely the best idea, and only enable it if you are planning to export to iOS.

**Comment by DrMoriarty** [comment]
@reduz this PR don't change default enabled compressed textures formats. So PVRTC will be disabled until user enabled it.

**Comment by akien-mga** [comment]
Yes @reduz seems to have misinterpreted the code, this doesn't change the fact that PVRTC is off by default (but it should be toggled on if you want to target iOS with GLES2, just like ETC1 needs to be toggled on manually if you want to target Android with GLES2).

**Comment by akien-mga** [comment]
Thanks!
