### PR TITLE
Fix scene node selection problem when no auto expand

### LINKED ISSUE #94467: Add child node problem with selection.
### Tested versions

v4.3.beta3.official [82cedc83c]
Works fine in 3.6 rc1

### System information

w10 64

### Issue description

Watch the video where the error occurs:

Initially I add a node "skeleton2D" as a child of "Node2D", this is done correctly.
Then, without left clicking on the "Sketelon2D" node (I don't left click because apparently it is already selected) I add a child node (with right click) "Bone2D" to the "Skeleton2D" node. Here the problem occurs, apparently the node "Skeleton2D" was automatically marked after being added as a child of "Node2D", well, this marking seems to have only been done visibly, that is, the node was not really selected since the new child node was not added as a child of "Skeleton2D".

All with mouse. no shortcuts.

https://github.com/user-attachments/assets/5b31618a-2250-4030-be5f-f02b778d676f

### Steps to reproduce

see the video

### Minimal reproduction project (MRP)

...

### PR DESCRIPTION
**Pull request by Hilderin**
- Fixes #94467

When the option `Docks > Scene Tree > Auto Expand to Selected` was disabled, the `selected` node was not updated in the method `SceneTreeEditor::set_selected`. Additionally, even if the node was not collapsed, `tree->ensure_cursor_is_visible` was never called, preventing the user from seeing the node after its creation if the tree was long enough. The same problem was present when navigating with the back/forward buttons of the Inspector.

Problem reproduction:

https://github.com/user-attachments/assets/69bf5a63-2f90-428a-8265-492b9d2a2c00

https://github.com/user-attachments/assets/af6b5bbd-9856-48d2-b3ab-187c7fa34e5b

### CODE REVIEW

File: editor/gui/scene_tree_editor.cpp [hunk 1]
```diff
@@ -1009,8 +1010,24 @@ void SceneTreeEditor::set_selected(Node *p_node, bool p_emit_selected) {
 			}
 			item->select(0);
 			item->set_as_cursor(0);
-			selected = p_node;
 			tree->ensure_cursor_is_visible();
+		} else {
+			// Ensure the node is selected and visible for the user is the node
```
Comment (KoBeWi) [inline editor/gui/scene_tree_editor.cpp:1015]:
```suggestion
			// Ensure the node is selected and visible for the user if the node
```

**Review by KoBeWi — APPROVED** [review]

File: editor/gui/scene_tree_editor.cpp (hunk 1 above)
Comment (Hilderin) [reply editor/gui/scene_tree_editor.cpp]: Done!

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.
