### PR TITLE
Validate Resource type when pasting property

### LINKED ISSUE #112347: Possible to copy-paste a `Resource` into an exported property field of different `Resource` type
### Tested versions

Reproducible in: `4.5.1.stable`, `4.4.1.stable`
Not reproducible in: `4.3.stable`

### System information

Godot v4.5.1.stable - Windows 11 (build 26100) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 32.0.15.7652) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 threads) - 15.92 GiB memory

### Issue description

It is possible to copy-paste a `Resource` into an exported property field of a different `Resource` type. For example, you can copy-paste a `Material` into a `Mesh` field, or a `GDScript` into a `Texture` field, etc.

Details:
- The issue seems to only occur on exported properties of scripts, not on properties of built-in nodes.
- The issue persists across scene and project reloads.
- The issue does not persist into runtime (the pasted values become null).
- The issue does not occur if the exported property is defined in a tool script (likely due to it running the same validation as runtime).

### Steps to reproduce

- Open `test.tscn` in the attached project
- On the root node, copy/paste any of the properties into any of the other properties

Image

### Minimal reproduction project (MRP)

[bug-report-2.zip](https://github.com/user-attachments/files/23308707/bug-report-2.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #112347

When you paste a property value, the inspector will just emit that property has changed with the new value, without doing _any_ validation. It works with built-in properties, because when you try to e.g. assign Object to float or Texture2D to Image, the engine will cast it to the new value and assign whatever remains after casting (so e.g. you can paste Resource as bool and it will assign true).

It's a bit different for script properties. If the script isn't `@tool`, they are assigned to PlaceholderScriptInstance, which has no information about the properties. Whatever you set just goes in. After the value is pasted, the EditorProperty will update itself based on the value. In most cases the value will correct itself, e.g. you can't assign Node to EditorPropertyInt, because it just can't accept/display that value.

Then there is EditorPropertyResource. After #84446 the validation of the value assigned to the object does not happen, so as long as it's any Resource, the property will accept it. This, coupled with what I explained above, is the source of the bug. I opted to fix it at pasting operation.

### CODE REVIEW

File: editor/inspector/editor_resource_picker.cpp [hunk 1]
```diff
@@ -1062,9 +1060,20 @@ void EditorResourcePicker::set_edited_resource(Ref<Resource> p_resource) {
...
+}
+
+void EditorResourcePicker::set_edited_resource(Ref<Resource> p_resource) {
+	if (!is_resource_allowed(p_resource)) {
+		StringName custom_class;
+		if (p_resource->get_script()) {
+			custom_class = EditorNode::get_singleton()->get_object_custom_type_name(p_resource->get_script());
 		}
+		const String class_str = (custom_class.is_empty() ? p_resource->get_class() : vformat("%s (%s)", custom_class, p_resource->get_class()));
+		ERR_FAIL_MSG(vformat("Failed to set a resource of the type '%s' because this EditorResourcePicker only accepts '%s' and its derivatives.", class_str, base_type));
```
Comment (akien-mga) [inline editor/inspector/editor_resource_picker.cpp:1189]: Should this be `ERR_FAIL_EDMSG` to show in the toaster?

Comment (KoBeWi) [reply editor/inspector/editor_resource_picker.cpp:1189]: tbh I'm not sure when this error can appear normally. The paste operation does not trigger it, and I don't think you can assign wrong resource any other way using the inspector.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Needs rebase.

**Comment by Repiteo** [comment]
Thanks!
