### PR TITLE
Fix problems with scripts and metadata in remote objects

### LINKED ISSUE #107428: Metadata values are not reflected in the remote inspector and cannot be edited (since at least 4.5dev1)
### Tested versions

- Reproducible in: 4.5.dev1, 4.5.dev4 4.5.dev5
- Not reproducible in: 4.4.1.stable (Although there is still odd behavior, metadata values display twice)

### System information

Mac OS 15.3.1

### Issue description

Metadata values on nodes aren't reflected in the remote scene tree, they just show their default values. They also can't be set, but flicker like they're trying to be. New metadata values can be added, and will show separately and can be removed, but still can't be edited.

### Steps to reproduce

Add a metadata value to a node and set it to anything other than it's default value. Easiest with a bool, add it and set it to true, then see that it's false in the remote inspector, but still true if evaluated in-game. Noticed it with an array, haven't done excessive testing to see if it affects every value type.

Image

### Minimal reproduction project (MRP)

[remote_metadata.zip](https://github.com/user-attachments/files/20698610/remote_metadata.zip)

### PR DESCRIPTION
**Pull request by YeldhamDev**
Fixes #107428.

### CODE REVIEW

File: editor/debugger/editor_debugger_inspector.cpp [hunk 1]
```diff
@@ -275,33 +279,18 @@ EditorDebuggerRemoteObjects *EditorDebuggerInspector::set_objects(const Array &p
...
-				KV.value.values[remote_objects->remote_object_ids[0]] = var;
-
-				if (pinfo.hint_string == "Script") {
-					if (remote_objects->get_script() != var) {
-						remote_objects->set_script(Ref<RefCounted>());
-						Ref<Script> scr(var);
-						if (scr.is_valid()) {
-							ScriptInstance *scr_instance = scr->placeholder_instance_create(remote_objects);
-							if (scr_instance) {
-								remote_objects->set_script_and_instance(var, scr_instance);
```
Comment (KoBeWi) [inline editor/debugger/editor_debugger_inspector.cpp:299]: Isn't this needed somewhere? I assume something already handles it, but where?

Comment (YeldhamDev) [reply editor/debugger/editor_debugger_inspector.cpp:299]: From my tests everything was fine without it, which makes me wonder if this wasn't just a leftover that isn't needed anymore. 

Also, my PR changes how scripts are stored in the object. Before, it set the `script` property of the `EditorDebuggerRemoteObjects` itself, now it sets a fake `Script` property.

**Comment by KoBeWi** [comment]
For some reason the remote Script property can't be modified. However it at least shows the script, unlike on master, so it's still some improvement.
The Add Metadata button seems gone for for remote nodes.

**Review by KoBeWi — APPROVED** [review]
There are still some problems, but it's better than before. I did not compare with before the regression though.

**Comment by YeldhamDev** [comment]
> For some reason the remote Script property can't be modified. However it at least shows the script, unlike on master, so it's still some improvement.

The removed code isn't related to that, as I can reproduce that on 4.4.1 as well.

> The Add Metadata button seems gone for for remote nodes.

It never really worked to begin with, it just added metadata to the `EditorDebuggerRemoteObjects` itself.

**Comment by akien-mga** [comment]
Thanks!
