### PR TITLE
Fixed physics server area cleaning

### LINKED ISSUE #17132: Multiple Areas collision giving errors while using bullet
**Godot version:**

Godot 3.0 and 3.0.1

**OS/device including version:**

Windows 8.1 x64

**Issue description:**

Using several areas together gives unexpected bug only in bullet

**Steps to reproduce:**
Make destructive (queue_free) collision of several areas (in the reproduction project, 8 (4 colliding with 4) and above areas cause the bug. Godot physics doesn't give errors.
Here is the log:

```
0:00:01:0469 - Condition ' !area_in && !E ' is true.
----------
Tipo:Error
Descripción: 
Tiempo: 0:00:01:0469
C Error: Condition ' !area_in && !E ' is true.
C Fuente: scene\3d\area.cpp:357
C Función: Area::_area_inout
```
**Minimal reproduction project:**

The test project will throw several areas against them, but only half of the areas should survive, bullet gives great accuracy in this case, since godot physics sometimes doesn't detect the collisions, but gives the errors.

[Test_Bullet_queue.zip](https://github.com/godotengine/godot/files/1769905/Test_Bullet_queue.zip)

### PR DESCRIPTION
**Pull request by AndreaCatania**
Fixes #17132
Can be cherry picked

### CODE REVIEW

File: modules/bullet/area_bullet.cpp [hunk 1]
```diff
@@ -1,4 +1,4 @@
-/*************************************************************************/
+﻿/*************************************************************************/
```
Comment (akien-mga) [inline modules/bullet/area_bullet.cpp]: Looks like your IDE added a byte order mark (BOM) to this file?

**Comment by AndreaCatania** [comment]
Aki, I've removed BOM

**Comment by hpvb** [comment]
Cherry picked into 3.0.3
