### PR TITLE
GDScript: Fix access non-static members in static context

### LINKED ISSUE #91403: Non-static methods can't be referenced as Callables from static methods
### Tested versions

4.3 dev6 broken
4.3 dev5 works

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

```GDScript
extends Node

func _ready() -> void:
	static_method()

static func static_method():
	print(not_static)

func not_static():
	pass
```
Running this script in dev5 prints `Node::not_static`. Running in dev6 results in `Invalid access to property or key 'not_static' on a base object of type 'Nil'.`. The callable is not accessible even if you name the script and do `ClassName.not_static`.

### Steps to reproduce

1. Run the code above in 4.3 dev5
2. Run the code above in 4.3 dev6

### Minimal reproduction project (MRP)

See above.

### PR DESCRIPTION
**Pull request by dalexeev**
* Fixes #91403.

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -4029,25 +4032,37 @@ void GDScriptAnalyzer::reduce_identifier(GDScriptParser::IdentifierNode *p_ident
...
+				push_error(vformat(R"*(Cannot access %s "%s" from a static variable initializer.)*", source_type, p_identifier->name), p_identifier);
 			}
 		}
 
 		if (current_lambda != nullptr) {
-			// If the identifier is a member variable (including the native class properties) or a signal, we consider the lambda to be using `self`, so we keep a reference to the current instance.
-			if (source_is_variable || source_is_signal) {
+			// If the identifier is a member variable (including the native class properties), member function, or a signal,
+			// we consider the lambda to be using `self`, so we keep a reference to the current instance.
+			if (source_is_instance_variable || source_is_instance_function || source_is_signal) {
```
Comment (dalexeev) [inline modules/gdscript/gdscript_analyzer.cpp:4065]: This is an "unrelated" change, but I guess it makes sense? At least the tests did not detect regressions, but this is not always a reliable criterion.

File: modules/gdscript/tests/scripts/analyzer/features/static_non_static_access.gd [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+	non_static_func()
+	print(non_static_func)
+	non_static_var = 1
+	print(non_static_var)
+	my_signal.emit()
+	print(my_signal)
+
+func test():
+	test_static_var_lambda = null
+	test_non_static_var_lambda = null
```
Comment (dalexeev) [inline modules/gdscript/tests/scripts/analyzer/features/static_non_static_access.gd:75]: This fixes memory leaks in CI. I'm not sure if this is a bug, but it's probably unrelated to the changes since I've noticed this problem before.

Comment (vnen) [reply modules/gdscript/tests/scripts/analyzer/features/static_non_static_access.gd:75]: It's a reference cycle. Lambda contains a reference to `self` which in turn contains a reference to the lambda. Not sure if there's a good way to solve it.

**Review by vnen — APPROVED** [review]
LGTM

**Comment by akien-mga** [comment]
Thanks!
