### PR TITLE
Fix printing error about unsupported modifier on `TransformUniform`

### LINKED ISSUE #51562: VisualShader: TransformUniform qualifier can be set to "Instance" which is not supported
### Godot version

4.0-dev (20210811)

### System information

Windows 10, Vulkan, RTX2080

### Issue description

Using the test build  [Godot_v4.0-dev.20210811_win64](https://downloads.tuxfamily.org/godotengine/testing/4.0/4.0-dev.20210811/)

It is currently possible to set the qualifier of TransformUniform nodes in the VisualShader editor to "Instance" which throws an error.

**"Uniforms with 'instance' qualifiers can't be of matrix type."**

### Steps to reproduce

1. Create a new visual shader
2. Add a TransformUniform node and set its qualifier to "instance"
3. Connect via TransformVectorMult node to Albedo

See minimal reproduction project

### Minimal reproduction project

grafik

### PR DESCRIPTION
**Pull request by Chaosus**
Fix error printing on uniform + add a `Transform` to unsupported types for the instancing:
image

Fix #51562

### CODE REVIEW

File: scene/resources/visual_shader.cpp [hunk 1]
```diff
@@ -3081,10 +3081,11 @@ String VisualShaderNodeUniform::get_warning(Shader::Mode p_mode, VisualShader::T
 	List<String> keyword_list;
 	ShaderLanguage::get_keyword_list(&keyword_list);
 	if (keyword_list.find(uniform_name)) {
-		return TTR("Uniform name cannot be equal to a shader keyword. Choose another name.");
+		return TTR("Uniform name cannot be named as a shader keyword.\nChoose another name.");
```
Comment (akien-mga) [inline scene/resources/visual_shader.cpp:3084]:
```suggestion
		return TTR("Shader keywords cannot be used as uniform names.\nChoose another name.");
```

**Review by akien-mga — APPROVED** [review]

File: scene/resources/visual_shader.cpp [hunk 2]
```diff
@@ -3081,10 +3081,22 @@ String VisualShaderNodeUniform::get_warning(Shader::Mode p_mode, VisualShader::T
...
+			case QUAL_NONE:
+				break;
+			case QUAL_GLOBAL:
+				qualifier_str = "global";
+				break;
+			case QUAL_INSTANCE:
+				qualifier_str = "instance";
+				break;
+		}
+		return vformat(TTR("This uniform type does not support '%s' qualifier."), qualifier_str);
```
Comment (akien-mga) [inline scene/resources/visual_shader.cpp:3098]:
```suggestion
		return vformat(TTR("This uniform type does not support the '%s' qualifier."), qualifier_str);
```

File: scene/resources/visual_shader.cpp [hunk 3]
```diff
@@ -3081,10 +3081,22 @@ String VisualShaderNodeUniform::get_warning(Shader::Mode p_mode, VisualShader::T
...
 	if (keyword_list.find(uniform_name)) {
-		return TTR("Uniform name cannot be equal to a shader keyword. Choose another name.");
+		return TTR("Uniform name cannot be named as a shader keyword.\nChoose another name.");
 	}
 	if (!is_qualifier_supported(qualifier)) {
-		return "This uniform type does not support that qualifier.";
+		String qualifier_str;
+		switch (qualifier) {
+			case QUAL_NONE:
+				break;
```
Comment (akien-mga) [inline scene/resources/visual_shader.cpp:3090]: This will produce `This uniform type does not support '' qualifier.` I suppose? Or this condition would never be hit?

File: scene/resources/visual_shader.cpp [hunk 4]
```diff
@@ -3081,10 +3081,84 @@ String VisualShaderNodeUniform::get_warning(Shader::Mode p_mode, VisualShader::T
...
+			case RS::GLOBAL_VAR_TYPE_SAMPLERCUBE: {
+				if (!Object::cast_to<VisualShaderNodeCubemapUniform>(this)) {
+					incompatible_type = true;
+				}
+			} break;
+			default:
+				break;
+		}
+		if (incompatible_type) {
+			return vformat(TTR("Global uniform '%s' has incorrect type for this kind of the node.\nChange it in the Project Settings."), uniform_name);
```
[the remark this answers is not in the document]
Comment (Chaosus) [reply scene/resources/visual_shader.cpp]: Thanks, fixed
