### PR TITLE
Changed shell_open behaviour

### LINKED ISSUE #43048: Godot keeps xdg-open zombie processes
**Godot version:**
3.2.3.stable.official
4.0 - I haven't tested

**OS/device including version:**
KDE Plasma Version: 5.20.0
KDE Frameworks Version: 5.75.0
Qt Version: 5.15.1
Kernel Version: 5.8.15-1-default

**Issue description:**

Closing Godot removes the zombie processes.
_I don't know, maybe the bug is not in Godot, but in KDE, because I noticed the `kde-open5` process opening briefly._

**Steps to reproduce:**
Project > Open Project Data Folder

**Minimal reproduction project:**
—

### PR DESCRIPTION
**Pull request by rsubtil**
Changed behaviour of `shell_open` to "block" when called, so Godot doesn't spawn multiple "zombie" processes, and changed commands, since `gnome-open` is deprecated for almost [10 years](https://askubuntu.com/questions/101965/what-is-the-replacement-for-gnome-open-in-gnome) and in some cases `kde-open` is actually called `kde-open5`.

Fixes #43048

### CODE REVIEW

File: platform/linuxbsd/os_linuxbsd.cpp [hunk 1]
```diff
@@ -125,15 +125,26 @@ Error OS_LinuxBSD::shell_open(String p_uri) {
...
 	args.push_back(p_uri);
-	ok = execute("xdg-open", args, false);
+	// Agnostic
+	ok = execute("xdg-open", args, true);
 	if (ok == OK) {
 		return OK;
 	}
-	ok = execute("gnome-open", args, false);
+	// GNOME
+	ok = execute("gio open", args, true);
```
Comment (akien-mga) [inline platform/linuxbsd/os_linuxbsd.cpp:134]: Does this work? Or should `open` be added to `args`?

Comment (Ev1lbl0w) [reply platform/linuxbsd/os_linuxbsd.cpp:134]: Good catch, it doesn't work this way indeed. I've added the `open` part to the args.

I didn't catch this because there is another issue actually; if `execute` fails *(such as, if `xdg-open` doesn't exist)*, it still returns `OK`, so the code doesn't attempt any other option. I'll fix that too.

Comment (Ev1lbl0w) [reply platform/linuxbsd/os_linuxbsd.cpp:134]: Well, I've found a rabbit hole; on `os_unix.cpp`, the exitcode was also returning 0, because of a "quirk" of `WEXITSTATUS`.

The fix is a one-liner, but it is unrelated to this PR; should I open up another one for it?

Comment (akien-mga) [reply platform/linuxbsd/os_linuxbsd.cpp:134]: Yeah a separate PR would be best.

**Comment by Ev1lbl0w** [comment]
I've opened #43056 for the inherent issue, so this PR won't "work" well until that one is merged. I didn't make this one dependent on that because technically it's an issue already present before my changes.

File: platform/linuxbsd/os_linuxbsd.cpp [hunk 2]
```diff
@@ -123,17 +123,32 @@ String OS_LinuxBSD::get_name() const {
 
 Error OS_LinuxBSD::shell_open(String p_uri) {
 	Error ok;
+	int errCode;
```
Comment (akien-mga) [inline platform/linuxbsd/os_linuxbsd.cpp:126]:
```suggestion
	int err_code;
```

File: platform/linuxbsd/os_linuxbsd.cpp [hunk 3]
```diff
@@ -123,17 +123,32 @@ String OS_LinuxBSD::get_name() const {
...
 	List<String> args;
 	args.push_back(p_uri);
-	ok = execute("xdg-open", args, false);
-	if (ok == OK) {
+
+	// Agnostic
+	ok = execute("xdg-open", args, true, nullptr, nullptr, &errCode);
+	if (ok == OK && !errCode) {
```
Comment (akien-mga) [inline platform/linuxbsd/os_linuxbsd.cpp:132]: I'm not sure about this, if there's a failed error code returns by the process, most likely the path we're trying to open cannot be opened, and going through attempt all `-open` methods under the sun is probably not a great idea (it will likely spam a lot of duplicate errors about e.g. path not found).

Comment (Ev1lbl0w) [reply platform/linuxbsd/os_linuxbsd.cpp:132]: Apparently `xdg-open`, `gvfs-open` and `gio open` return exit code 2 if the specified file/path doesn't exist *(and while `kde-open` doesn't have a exit code for that AFAIK, it opens a window with the error)*, so I'll add that into account.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
