### PR TITLE
Fix missing native file dialog title translation.

### LINKED ISSUE #99207: Native FileDialog does not translate its title
### Tested versions

- Reproduced in v4.4.dev.custom_build [c6c464cf9ae56e8b68620af65125dd980d0e8122]

### System information

Godot v4.4.dev (becbc04e9) - Windows 10.0.19044 - Multi-window, 3 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 2080 (NVIDIA; 32.0.15.5585) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 threads)

### Issue description

FileDialog with `Use Native Dialog` enabled and `Mode Overrides Title` disabled does not auto translate its title:

image

Seems to be an oversight since Window seems to auto-translate even if native (looking at the source code, I see `tr_title` used in `window_set_title`)

### Steps to reproduce

- Set up translation in project
- Create FileDialog with `Use Native Dialog` enabled and `Mode Overrides Title` disabled
- Set its title to a translation key
- Notice how the translation key is used as-is, without calling `atr`

### Minimal reproduction project (MRP)

I don't have time to create a MRP right now, sorry! I'm mobile for over a week.

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/99207

### CODE REVIEW

File: scene/gui/file_dialog.cpp [hunk 1]
```diff
@@ -67,10 +67,11 @@ void FileDialog::_native_popup() {
 	} else if (access == ACCESS_USERDATA) {
 		root = OS::get_singleton()->get_user_data_dir();
 	}
+	String tr_title = atr(get_title());
```
Comment (akien-mga) [inline scene/gui/file_dialog.cpp:70]: Apparently this shadows `tr_title` from Window.

Two things then:
- This could likely use `tr_title` directly?
- But to do it properly it would likely make sense to make `tr_title` private and add a getter like `get_translated_title`.

Comment (akien-mga) [reply scene/gui/file_dialog.cpp]: If we do decide to add a getter, then this can be simplified too:
```
main/viewport.cpp
333:            TextLine title_text = TextLine(p_window->atr(p_window->get_title()), title_font, font_size);
```

Comment (bruvzg) [reply scene/gui/file_dialog.cpp]: Added `get_translated_title`.

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
