### PR TITLE
Fix removal of `rect_min_size` not triggering resize

### LINKED ISSUE #21803: CTRL + Z doesn't undo size change in Label node
**Steps to reproduce:**

1. Create label node
2. Type any text
3. Press Enter to create new line -> Label height changes
4. Type more text
5. Press CTRL + Z until text disappears
6. You now have empty label, which has size of 2 lines, despite you tried to undo it to initial size

After some testing, seems like it happens also when label extends horizontally. When you then try to resize the label by dragging rectangle hooks (or whatever they are called), it magically retracts to original size as you click it.

### LINKED ISSUE #40454: Container magically shrinks to minimal size on scene reload
**Godot version:**

3.2.2

**Issue description:**

LIf9NwHBri

**Steps to reproduce:**
1. Create a scene with a container (PanelContainer is the easiest to observe)
2. Add a label (probably works with TextureRect etc. too)
3. Add some lines to the label, so the container expands
4. Undo your text (container should still be big)
5. **Save**
6. Reload scene
7. The container is magically back to small size, even though it was big when saving
(shrink also happens without reloading when you *touch* either handle of the container)

The container should shrink immediately to the small size.

This is similar to #21803 and #19252

### LINKED ISSUE #46672: Control's sized by anchors do not resize if their rect_minimum_size shrinks (They only expand)
**Godot version:**
3.2.3

**OS/device including version:**
Win 10

**Issue description:**
When a `Control` (C) is nested inside another parent control (P), and is using anchors for it's size and position (e.g. Full Rect) it does not correctly adjust it's size if its size (C) exceeded the bounds of the wrapper (P) and is then shrunk again in size.

When a control (C) exceeds the bounds of an anchor layout it will correctly have a `rect_size` larger than the parent to accommodate it's size - either due to a min size or having children that are wider than the parent. The size of the parent (P) remains unchanged. 

If this process is then reverted (e.g. `rect_min_size` is set back to 0), the control (C) will still persist with it's inflated size. If the size of the parent (P) is adjusted, then the child (C) will be correctly reset back to a size matching the parent. 

You will likely hit this issue using anchor layouts and controls that change size (such as a label with dynamic text). As a side effect, this also creates a bit of an oddity in that the order your resize nodes matters (i.e. setting a min size C -> P can result in a different size of C than the ordering P -> C).

**Steps to reproduce:**
1. Add a parent control (P) with some fixed size, and nest a child control (C) within the parent.
2. Set the layout of child (C) to be Full Rect so that it fully fills the parent (P).
3. Adjust the `rect_min_size` of C so that it is now larger than the parent (You will need to then yield for a resize or frame if doing this in script)
4. Reset the `rect_min_size` back to 0 (again yield). The child C will still have an inflated size despite having Full Rect anchors.
5. Change the size of the parent (P) by 1 pixel (again yield). The child C will once again have the correct size.

**Minimal reproduction project:**
[Testing-AnchorContract.zip](https://github.com/godotengine/godot/files/6085801/Testing-AnchorContract.zip)

### PR DESCRIPTION
**Pull request by HaSa1002**
When you had a `minimum size` and remove it, the control wasn't be resized. Instead it jumped to the automatically calculated size on the next change of the actual size. With this change the control will recalculate it's size, when the minimum size is removed (`Vector(0,0)`)

fixes #46672
*Bugsquad edit:* Fixes #21803 Fixes #40454

### CODE REVIEW

File: scene/gui/control.cpp [hunk 1]
```diff
@@ -286,7 +286,7 @@ void Control::_update_minimum_size() {
 
 	Size2 minsize = get_combined_minimum_size();
 	if (minsize.x > data.size_cache.x ||
-			minsize.y > data.size_cache.y) {
+			minsize.y > data.size_cache.y || (minsize.x == 0 && minsize.y == 0)) {
```
Comment (akien-mga) [inline scene/gui/control.cpp:289]:
```suggestion
			minsize.y > data.size_cache.y ||
			(minsize.x == 0 && minsize.y == 0)) {
```

**Comment by HaSa1002** [comment]
fixed

**Comment by KoBeWi** [comment]
I wonder if there is any reason behind the original behavior. IMO it would make sense to refresh on any change. Check this for example:
ujGrVNlLFr
I shrunk the rect to size greater than (0, 0), but it doesn't update. When I reload the scene, the size refreshes correctly. It's the same buggy behavior.

**Comment by HaSa1002** [comment]
Now, it updates on any min size change.

**Review by KoBeWi — APPROVED** [review]
Looks ok. I also added 2 more issues to the OP that this fixes (might be more of them).

**Comment by groud** [comment]
I don't understand the issue. From what i read in the original issue, this is the expected behavior. I don't think a control should shrink automatically because its minimum size reduced.

A minimum size is constraining the lower bound of a control's size, not the size itself. So unless the minimum size ends up greater than the current size, the current size should not change when it's minimum size is modified. Otherwise that means that the minimum_size property completely drives the size one, which, IMO, is not a desirable behavior.

**Comment by KoBeWi** [comment]
@groud See the two issues I linked. The current behavior is the same, except the size will refresh on scene reload or just randomly when editing. It's bugged.

**Comment by HaSa1002** [comment]
I didn't change the behaviour of the resize. All I do is to calculate the minimum size immediately. The actual change in behaviour is the time when this happens.
KoBeWi was faster ^^

**Comment by groud** [comment]
> I didn't change the behaviour of the resize. All I do is to calculate the minimum size immediately. The actual change in behaviour is the time when this happens.
KoBeWi was faster ^^

Oh ok, if that does not cause the Control to shrink when updating the minsize, I guess that's alright then. 

(Note, I deleted a comment, forget about it it was not a good idea)

**Review by groud — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by PoisonousGame** [comment]
Fixed? I don't think so. I need the following code to recalculate the container rect_size when the container element decreases.
var panel_container = $".".find_node("panel_container")
panel_container.visible = false
panel_container.call_deferred("set_visible", true)

I am using the standard version 3.4.4
