### PR TITLE
Fix crash when hiding subwindow during popup of new subwindow

### LINKED ISSUE #80767: SIGILL when hiding with focus_exited signal while popping up a child window
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Debian GNU/Linux 12 (bookworm) 12 - Vulkan (Forward+) - integrated Intel(R) HD Graphics 5500 (BDW GT2) () - Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 Threads)

### Issue description

Attempting to open a child window from a window while having the `focus_exited` signal connected to the `hide` method, crashes Godot with signal 4 (SIGILL)
I have a backtrace, though it may not really be useful, since I didn't want to make my own build of godot with debug symbols. I hope however that the MRE makes up for the lack of a proper backtrace on my side.
```
================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.1.1.stable.official (bd6af8e0ea69167dd0627f3bd54f9105bda0f8b5)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3bf90) [0x7f586db17f90] (??:0)
[2] /home/monix/.local/share/hourglass/versions/4.1.1/godot() [0x2d5f7b6] (??:0)
[3] /home/monix/.local/share/hourglass/versions/4.1.1/godot() [0x2d5fa78] (??:0)
[4] /home/monix/.local/share/hourglass/versions/4.1.1/godot() [0x2dfcdf7] (??:0)
[5] /home/monix/.local/share/hourglass/versions/4.1.1/godot() [0x2dfd587] (??:0)
[6] /home/monix/.local/share/hourglass/versions/4.1.1/godot() [0x2dfe1b9] (??:0)
[7] /home/monix/.local/share/hourglass/versions/4.1.1/godot() [0x2d98f17] (??:0)
[8] /home/monix/.local/share/hourglass/versions/4.1.1/godot() [0x47d7128] (??:0)
[9] /home/monix/.local/share/hourglass/versions/4.1.1/godot() [0x461cac4] (??:0)
[10] /home/monix/.local/share/hourglass/versions/4.1.1/godot() [0x483b9d1] (??:0)
[11] /home/monix/.local/share/hourglass/versions/4.1.1/godot() [0x2ded3de] (??:0)
[12] /home/monix/.local/share/hourglass/versions/4.1.1/godot() [0x2dede9d] (??:0)
[13] /home/monix/.local/share/hourglass/versions/4.1.1/godot() [0x2d365f0] (??:0)
[14] /home/monix/.local/share/hourglass/versions/4.1.1/godot() [0x2d7c325] (??:0)
[15] /home/monix/.local/share/hourglass/versions/4.1.1/godot() [0x2d7f9ec] (??:0)
[16] /home/monix/.local/share/hourglass/versions/4.1.1/godot() [0x2d802e4] (??:0)
[17] /home/monix/.local/share/hourglass/versions/4.1.1/godot() [0x2da6ca5] (??:0)
[18] /home/monix/.local/share/hourglass/versions/4.1.1/godot() [0xeb6b10] (??:0)
[19] /home/monix/.local/share/hourglass/versions/4.1.1/godot() [0x45be723] (??:0)
[20] /home/monix/.local/share/hourglass/versions/4.1.1/godot() [0x45bf97e] (??:0)
[21] /home/monix/.local/share/hourglass/versions/4.1.1/godot() [0xeb71bf] (??:0)
[22] /home/monix/.local/share/hourglass/versions/4.1.1/godot() [0xe46433] (??:0)
[23] /lib/x86_64-linux-gnu/libc.so.6(+0x2718a) [0x7f586db0318a] (??:0)
[24] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85) [0x7f586db03245] (??:0)
[25] /home/monix/.local/share/hourglass/versions/4.1.1/godot() [0xe777ae] (??:0)
-- END OF BACKTRACE --
================================================================
```
What I expect to happen instead:
Either the engine failing with a proper error, or hiding the window, or keeping both windows visible.

### Steps to reproduce

Download, and run the MRE
Press the Browse button in the window that appears
Crash occurs

### Minimal reproduction project

[sigill-mre.zip](https://github.com/godotengine/godot/files/12383126/sigill-mre.zip)

### PR DESCRIPTION
**Pull request by HolonProduction**
Fixes: #80767

The new subwindow is refered to by its index at some points. This index has to be updated directly before usage because signals that are connected to some part of the process may change the subwindow list.

### CODE REVIEW

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -363,9 +363,6 @@ void Viewport::_sub_window_grab_focus(Window *p_window) {
 		return;
 	}
 
-	int index = _sub_window_find(p_window);
-	ERR_FAIL_COND(index == -1);
-
```
Comment (Sauermann) [inline scene/main/viewport.cpp:368]: I would not remove this guard, which checks, that the argument `p_window` references to a non-existent window. The other newly introduced checks verify that nothing problematic happens during the event-callbacks.

**Review by Sauermann — APPROVED** [review]
Changes are looking good to me and I can confirm that they are fixing the crash.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.
