### PR TITLE
Fix crash when reimporting with Skeleton3D selected.

### LINKED ISSUE #74059: Godot 4 crashes when updating a GLTF file's skeleton
### Godot version

v4.0.rc6.official [0cd148313]

### System information

Windows 10, Vulkan, RTX3080

### Issue description

The Skeleton3D node of a skinned GLTF/GLB/FBX model causes Godot to crash if it's visible in the inspector as the user re-imports the model file with armature changes.

### Steps to reproduce

- Open the included reproduction file.
- Open the model_inherited.tscn scene.
- Select the Skeleton3D node so that its bone hierarchy shows up in the inspector.
- Open the included model.blend file in Blender and alter the bone structure of its armature by entering Edit Mode and moving, adding, removing, or renaming one of its bones. Either of these actions will do the job.
- Export the armature as GLB, overwriting the existing model.glb in the Godot project.
- Go back to Godot and watch it crash.

### Minimal reproduction project

[ArmatureCrashBug.zip](https://github.com/godotengine/godot/files/10841158/ArmatureCrashBug.zip)

### PR DESCRIPTION
**Pull request by SaracenOne**
Closes https://github.com/godotengine/godot/issues/74059

### CODE REVIEW

File: editor/plugins/skeleton_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -871,7 +871,9 @@ void Skeleton3DEditor::_notification(int p_what) {
 				skeleton->disconnect("pose_updated", callable_mp(this, &Skeleton3DEditor::_update_properties));
 				skeleton->set_transform_gizmo_visible(true);
 #endif
-				handles_mesh_instance->get_parent()->remove_child(handles_mesh_instance);
+				if (handles_mesh_instance->is_inside_tree()) {
+					handles_mesh_instance->get_parent()->remove_child(handles_mesh_instance);
+				}
```
Comment (fire) [inline editor/plugins/skeleton_3d_editor_plugin.cpp:876]:
```suggestion
				if (handles_mesh_instance->is_inside_tree() && handles_mesh_instance->get_parent()) {
					handles_mesh_instance->get_parent()->remove_child(handles_mesh_instance);
				}
```

**Review by fire — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
