### PR TITLE
Fix RigidBody3D.get_inverse_inertia_tensor() crash

### LINKED ISSUE #46282: Executing `RigidBody3D.get_inverse_inertia_tensor()` crashes Godot
**Godot version:**
4.0.dev.custom_build. 3bb628d8f

**OS**
Ubuntu 20.04 - Ubuntu 3.36 X11

**Issue description:**
Executing
```
var q_RigidBody3D : RigidBody3D = RigidBody3D.new()

func _ready() -> void:
	add_child(q_RigidBody3D)

func _process(_delta : float) -> void:
	if randi() % 10 == 0:
		q_RigidBody3D.queue_free()
		q_RigidBody3D = RigidBody3D.new()
		add_child(q_RigidBody3D)

	if randi() % 2 == 0:
		q_RigidBody3D.get_inverse_inertia_tensor()
```
shows this address sanitizer log
```
Executing RigidBody3D.get_inverse_inertia_tensor
core/variant/method_ptrcall.h:127:1: runtime error: store to misaligned address 0x7ffd89510401 for type 'struct Basis', which requires 4 byte alignment
0x7ffd89510401: note: pointer points here
 60 00 00  20 04 51 89 fd 7f 00 00  67 4b e8 01 00 00 00 00  f0 04 51 89 fd 7f 00 00  80 33 0c 00 70
              ^ 
=================================================================
==253104==ERROR: AddressSanitizer: dynamic-stack-buffer-overflow on address 0x7ffd89510401 at pc 0x00000df24aa5 bp 0x7ffd89510190 sp 0x7ffd89510180
WRITE of size 36 at 0x7ffd89510401 thread T0
    #0 0xdf24aa4 in PtrToArg<Basis>::encode(Basis const&, void*) core/variant/method_ptrcall.h:127
    #1 0xdf95993 in void call_with_ptr_args_ret_helper<__UnexistingClass, Basis>(__UnexistingClass*, Basis (__UnexistingClass::*)(), void const**, void*, IndexSequence<>) core/variant/binder_common.h:227
    #2 0xdf87557 in void call_with_ptr_args_ret<__UnexistingClass, Basis>(__UnexistingClass*, Basis (__UnexistingClass::*)(), void const**, void*) core/variant/binder_common.h:445
    #3 0xdf76425 in MethodBindTR<Basis>::ptrcall(Object*, void const**, void*) core/object/method_bind.h:460
    #4 0x5b2e7a9 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1590
    #5 0x562a0c3 in GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1544
    #6 0x13a0fa23 in ScriptInstance::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) core/object/script_language.cpp:322
    #7 0xc64557d in Node::_notification(int) scene/main/node.cpp:58
    #8 0x336c589 in Node::_notificationv(int, bool) scene/main/node.h:45
    #9 0x336ee58 in CanvasItem::_notificationv(int, bool) scene/main/canvas_item.h:164
    #10 0xe3425ba in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:37
    #11 0x139a46e2 in Object::notification(int, bool) core/object/object.cpp:793
    #12 0xc74ab21 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:812
    #13 0xc73dc2d in SceneTree::process(float) scene/main/scene_tree.cpp:441
    #14 0x1fc51e2 in Main::iteration() main/main.cpp:2471
    #15 0x1e6c83e in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:261
    #16 0x1e5f040 in main platform/linuxbsd/godot_linuxbsd.cpp:58
    #17 0x7f38f58f30b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #18 0x1e5eb7d in _start (/usr/bin/godot4s+0x1e5eb7d)

Address 0x7ffd89510401 is located in stack of thread T0 at offset 209 in frame
    #0 0xdf8748c in void call_with_ptr_args_ret<__UnexistingClass, Basis>(__UnexistingClass*, Basis (__UnexistingClass::*)(), void const**, void*) core/variant/binder_common.h:444

  This frame has 1 object(s):
    [32, 33) '<unknown>' <== Memory access at offset 209 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: dynamic-stack-buffer-overflow core/variant/method_ptrcall.h:127 in PtrToArg<Basis>::encode(Basis const&, void*)

```

### PR DESCRIPTION
**Pull request by JohnM666**
Fix #46282

Also I assume method get_inverse_inertia_tensor should be const

### CODE REVIEW

**Review by pouleyKetchoupp — APPROVED** [review]
Looks good and works fine!

**Review by akien-mga — APPROVED** [review]

File: core/variant/variant_internal.h [hunk 1]
```diff
@@ -46,6 +46,9 @@ class VariantInternal {
 			case Variant::AABB:
 				init_aabb(v);
 				break;
+			case Variant::BASIS:
+				init_basis(v);
+				break;
```
Comment (akien-mga) [inline core/variant/variant_internal.h:51]: Nitpick, but since you need to amend the commit to sync the class reference:

Could you reorder the first `case`s here to match the order of `Variant::Type`, which is also the order of declaration of the `init_` methods? It should be:
```
STRING
TRANSFORM2D
AABB
BASIS
TRANSFORM
STRING_NAME
etc. the rest is correct
```

And while at it I reviewed the list to make sure we don't miss any. Could you add this comment where the `init_` methods are declared?
```diff
diff --git a/core/variant/variant_internal.h b/core/variant/variant_internal.h
index 7d33d85cd6..c8ad1554fe 100644
--- a/core/variant/variant_internal.h
+++ b/core/variant/variant_internal.h
@@ -192,11 +192,14 @@ public:
                v->type = GetTypeInfo<T>::VARIANT_TYPE;
        }
 
+       // Should be in the same order as Variant::Type for consistency.
+       // Those primitive and vector types don't need an `init_` method:
+       // Nil, bool, float, Vector2/i, Rect2/i, Vector3/i, Plane, Quat, Color, RID.
+       // Object is a special case, handled via `object_assign_null`.
        _FORCE_INLINE_ static void init_string(Variant *v) {
                memnew_placement(v->_data._mem, String);
                v->type = Variant::STRING;
        }
-
        _FORCE_INLINE_ static void init_transform2d(Variant *v) {
                v->_data._transform2d = memnew(Transform2D);
                v->type = Variant::TRANSFORM2D;
```

Comment (akien-mga) [reply core/variant/variant_internal.h:51]: CC @vnen to review my added comment as I'm not a Variant expert :)

**Review by akien-mga — APPROVED** [review]

File: core/variant/variant_internal.h (hunk 1 above)
Comment (akien-mga) [reply core/variant/variant_internal.h:57]: Confirmed that the added comment is correct :)
```
<vnen> yeah, those types don’t allocate extra memory so they don’t need initialization, only setting the type is enough
```

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
