### PR TITLE
Fix issue regarding rotating Canvas Items in editor

### LINKED ISSUE #34861: Rotation tool in 2D Editor inverts its direction.
**Godot version:**
cab97f4b504a6

**OS/device including version:**
Win10 64-bit

**Issue description:**
When setting negative scaling in a node, it will influence how the rotation dragging works in its children.

Making the tool rotate in an inverted direction.  I understand it's from the transform inheritance, but for artists It's very unintuitive, especially since the parent node isn't affected by this change.  

The tool should apply a global rotation.

image

ezgif com-video-to-gif

**Steps to reproduce:**

Create a hierarchy of 2D nodes, flip the scaling of the parent, and try using the editor rotation to rotate it's children. 

**Minimal reproduction project:**
[Rotation Issue.zip](https://github.com/godotengine/godot/files/4026262/Rotation.Issue.zip)

### PR DESCRIPTION
**Pull request by Phischermen**
Fixes #34861
Canvas items will now rotate correctly no matter what their global scale happens to be.

### CODE REVIEW

**Comment by avencherus** [comment]
Nice.  Thanks for looking into this so quickly.

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -1492,7 +1492,9 @@ bool CanvasItemEditor::_gui_input_rotate(const Ref<InputEvent> &p_event) {
 			for (List<CanvasItem *>::Element *E = drag_selection.front(); E; E = E->next()) {
 				CanvasItem *canvas_item = E->get();
 				drag_to = transform.affine_inverse().xform(m->get_position());
-				canvas_item->_edit_set_rotation(snap_angle(canvas_item->_edit_get_rotation() + (drag_from - drag_rotation_center).angle_to(drag_to - drag_rotation_center), canvas_item->_edit_get_rotation()));
+				//Rotate opposite way if either global scale is inverted but local scale is not or global scale is not inverted but local scale is
+				bool opposite = (canvas_item->get_global_transform().get_scale().sign() != Vector2(1, 1)) == (canvas_item->get_transform().get_scale().sign() == Vector2(1, 1));
```
Comment (groud) [inline editor/plugins/canvas_item_editor_plugin.cpp]: I am not sure this condition is good. I haven't tested yet but it might not cover all use cases, especially when you have both vertical an horizontal scale flipped.

Comment (Phischermen) [reply editor/plugins/canvas_item_editor_plugin.cpp]: I tested a lot of possible combinations, but probably not all of them. I'll set up a test scene that's got sets of three sprites (a child, a parent, and a grand parent) that cover all possible combinations of scale.

**Comment by Phischermen** [comment]
Here is a test scene:
[RotationIssue.zip](https://github.com/godotengine/godot/files/4033051/RotationIssue.zip)
You can mess with variables in the root node to try different combinations of scale. There are 64 different possible combinations. I've tried about 1-20 so far and thankfully my fix appears to be working.

File: editor/plugins/canvas_item_editor_plugin.cpp (hunk 1 above)
Comment (akien-mga) [reply editor/plugins/canvas_item_editor_plugin.cpp]: If `opposite` is meant to be true only when there's an uneven number of negative coordinates in the two vectors, you can use dot product to assess it:
```
	print(Vector2(-1, 1).dot(Vector2(1, 1)))
	print(Vector2(-1, -1).dot(Vector2(1, 1)))
	print(Vector2(1, -1).dot(Vector2(1, 1)))
	print(Vector2(1, -1).dot(Vector2(1, -1)))
	print(Vector2(1, -1).dot(Vector2(-1, -1)))
	print(Vector2(1, -1).dot(Vector2(-1, 1)))
```
prints:
```
0
-2
0
2
0
-2
```
I'm a bit rusty on my math but I'm sure there must be a geometric explanation for why this would be the "proper" way to compare the signedness of two unit vectors.

Comment (akien-mga) [reply editor/plugins/canvas_item_editor_plugin.cpp]: > I'm a bit rusty on my math but I'm sure there must be a geometric explanation for why this would be the "proper" way to compare the signedness of two unit vectors.

Well basically it just means that the two unit vectors are orthogonal in the Cartesian space. If they were colinear, the signs would either be the same or opposite for both coordinates.

Comment (groud) [reply editor/plugins/canvas_item_editor_plugin.cpp]: Yeah, I was more expecting something with a dot product too. I assume the condition might work because the signed scale can never be `Vector2(-1,-1)`, but that's kind of weird.

Comment (Phischermen) [reply editor/plugins/canvas_item_editor_plugin.cpp]: I was unaware you could use dot product for these kind of situations; very clever! I updated my implementation to use dot product because I think it makes the code a bit cleaner. Everything still works as far as I am aware.

**Comment by akien-mga** [comment]
Looks good, thanks! Could you squash the two commits together? See [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase).

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
