### PR TITLE
Fix setting root inspector's `follow_focus` to `true` when `update_tree()` method ends

### LINKED ISSUE #104749: Inspector scrolls away when editing properties with a nested property unfolded
### Tested versions

4.4.1stable mono

### System information

Windows 10 x64, Nvidia

### Issue description

The Inspector scrolls away when editing a property. 
Strangely this only occurs when a nested property is also inside the inspector( for example a 'sky' Background inside a worldenvironment Node)
See video:

https://github.com/user-attachments/assets/842d2436-4219-4096-80c0-f095894eba52

May be linked to https://github.com/godotengine/godot/pull/96542 ?

### Steps to reproduce

Create a world enviromnent node inside a scene.

2) Click a few properties inside worldenvironment to expand them ... e.g. Glow, Fog
3) Note no scrolling away when clicked
4) Now, go to 'Background' property & create a 'Sky' ->New Sky -> Panoramic Sky
5) Go back to 'Glow' or "Fog' and see how it scrolls away now

### Minimal reproduction project (MRP)

None

### PR DESCRIPTION
**Pull request by Rindbee**
This may produce unexpected behavior in **recursive** calls.

Fix #104749.

### CODE REVIEW

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -3097,14 +3108,8 @@ void EditorInspector::update_tree() {
 		}
 	}
 
-	// Only hide plugins if we are not editing any object.
 	// This should be handled outside of the update_tree call anyway (see EditorInspector::edit), but might as well keep it safe.
```
Comment (KoBeWi) [inline editor/editor_inspector.cpp:3111]: Not sure what this comment refers to exactly, but it probably shouldn't be in 2 places.

**Review by KoBeWi — APPROVED** [review]

File: editor/editor_inspector.cpp (hunk 1 above)
Comment (Rindbee) [reply editor/editor_inspector.cpp:3111]: This is a comment on `_clear()`.

https://github.com/godotengine/godot/blob/c374ce211c00279ac4a69aaaa12b5ff12d7cf6da/editor/editor_inspector.cpp#L4219

File: editor/editor_inspector.cpp [hunk 2]
```diff
@@ -3097,14 +3104,9 @@ void EditorInspector::update_tree() {
...
-	// This should be handled outside of the update_tree call anyway (see EditorInspector::edit), but might as well keep it safe.
-	_clear(!object);
-
-	if (!object) {
-		get_root_inspector()->set_follow_focus(true);
-		return;
-	}
+	// The call here is for the edited object that has not changed, but the tree needs to be updated (for example, the object's property list has been modified).
+	// Since the edited object has not changed, there is no need to hide the plugin at this time.
+	_clear(false);
```
Comment (Rindbee) [inline editor/editor_inspector.cpp:3109]: Since the tree is now updated by rebuilding it, `_clear()` is necessary. Plugins are hidden when changing the edited object via `EditorInspector::edit()`.
