### PR TITLE
Fix loading GDExtension dependencies on Android

### LINKED ISSUE #87785: Godot editor on android doesn't copy over dependencies whent they're located on sdcard.
### Tested versions

- Tested in: 4.2.1

Most likely occurs in all versions due to dependencies not being touched by the code that loads a library.

### System information

Godot v4.2.1stable - Android - Vulcan (Mobile) - integrated Adreno (TM) 619 - (8 Threads)

### Issue description

When opening a project with gdextension in the android editor, that is located on an sdcard, the gdextension file is copied over into a cache, however other dependencies are not copied over, causing the library to not load.

### Steps to reproduce

Have a single project with one GDExtenension library, and another library that is its dependency next to it, and a Gdextension file that has both library and dependency describet inside of it.

With this project placed onto an android phone, opening it will cause the error.

### Minimal reproduction project (MRP)

Here's a minimal project, (I've used the library which I'm currently using and is causing the issue, but it's in total over 10 MB): [https://github.com/lemonJumps/gdextension-bug](https://github.com/lemonJumps/gdextension-bug)

### PR DESCRIPTION
**Pull request by m4gr3d**
Update the Android `gdextension` loading logic so that it copies any specified library dependencies alongside the gdextension shared library.

Fixes https://github.com/godotengine/godot/issues/87785

### CODE REVIEW

File: core/extension/gdextension.cpp [hunk 1]
```diff
@@ -686,7 +721,18 @@ GDExtensionInterfaceFunctionPtr GDExtension::get_interface_function(const String
 }
 
 Error GDExtension::open_library(const String &p_path, const String &p_entry_symbol) {
+	Vector<SharedObject> dependencies;
+	return open_library_with_dependencies(p_path, p_entry_symbol, dependencies);
+}
+
+Error GDExtension::open_library_with_dependencies(const String &p_path, const String &p_entry_symbol, const Vector<SharedObject> &p_dependencies) {
```
Comment (dsnopek) [inline core/extension/gdextension.cpp:728]: I assume this new method was added to avoid changing the signature of `GDExtension::open_library()` because it's exposed?

This actually reminds me that we decided at a recent GDExtension meeting to un-expose this method - I'll make a PR for that soon. :-)

File: platform/android/java/lib/build.gradle [hunk 2]
```diff
@@ -168,7 +169,7 @@ android {
             def taskName = getSconsTaskName(flavorName, buildType, selectedAbi)
             tasks.create(name: taskName, type: Exec) {
                 executable sconsExecutableFile.absolutePath
-                args "--directory=${pathToRootDir}", "platform=android", "store_release=${storeRelease}", "production=${productionBuild}", "dev_mode=${devBuild}", "dev_build=${devBuild}", "tests=${runTests}", "target=${sconsTarget}", "arch=${selectedAbi}", "-j" + Runtime.runtime.availableProcessors()
+                args "--directory=${pathToRootDir}", "debug_symbols=${debugSymbols}", "platform=android", "store_release=${storeRelease}", "production=${productionBuild}", "dev_mode=${devBuild}", "dev_build=${devBuild}", "tests=${runTests}", "target=${sconsTarget}", "arch=${selectedAbi}", "-j" + Runtime.runtime.availableProcessors()
```
Comment (dsnopek) [inline platform/android/java/lib/build.gradle:172]: Possibly an unrelated change that snuck in?

**Review by dsnopek — COMMENTED** [review]
Heh, just yesterday, I was just explaining to someone that the dependencies aren't used at all when loading a GDExtension, only in exporting. I guess that won't be true anymore, at least for Android. :-)

At a high-level, this looks good to me! I haven't done any testing.

File: core/extension/gdextension.cpp (hunk 1 above)
Comment (dsnopek) [reply core/extension/gdextension.cpp:728]: Here's the PR https://github.com/godotengine/godot/pull/88418 to unbind that method

Once it's no longer exposed, I think it would be fine to add the new arguments directly on `GDExtension::open_library()`

File: platform/android/java/lib/build.gradle (hunk 2 above)
Comment (m4gr3d) [reply platform/android/java/lib/build.gradle]: Fixed!

File: core/extension/gdextension.cpp (hunk 1 above)
Comment (m4gr3d) [reply core/extension/gdextension.cpp]: Updated!

**Comment by m4gr3d** [comment]
> Discussed at the GDExtension meeting, and the `OS::open_dynamic_library()` method is really starting to acquire a lot of arguments.
> 
> (This unrelated GDExtension PR also adds a new argument: #87117)
> 
> Perhaps we should consider having a more generic `OS::open_dynamic_library()` with the minimum of argument, and then another `OS::open_gdextension_library()` that takes lots of GDExtension-specific arguments, and the OS can do what is necessary for GDExtension? It should be OK to rework this since this method isn't exposed.

What about adding a gdextension specific argument which contains all the gdextension supplemental parameters and is `nullptr` by default for regular calls.
My concern with another method is possible confusion about what to use when since at its core a gdextension is a dynamic library.

**Comment by dsnopek** [comment]
I was imagining that the `open_dynamic_library()` would just do the low-level loading bits, and that `open_gdextension_library()` would probably call `open_dynamic_library()` (although, since both would be defined by the `OS` sub-class, they really could do it in whatever way made the most sense for the platform). It would only be GDExtension that would call `open_gdextension_library()` - any other code would call `open_dynamic_library()`.

> What about adding a gdextension specific argument which contains all the gdextension supplemental parameters and is `nullptr` by default for regular calls.

But, yes, that could work too! Are you imagining like a `struct` that has all the GDExtension info?

**Comment by m4gr3d** [comment]
> But, yes, that could work too! Are you imagining like a struct that has all the GDExtension info?

Yeah somethink like a `GDExtensionData` similar to the pattern we have in other places like [CustomExportData](https://github.com/godotengine/godot/blob/87d40ba743ff3a3a484db051c11b16559604efa9/platform/android/export/gradle_export_util.h#L64)

**Comment by dsnopek** [comment]
While it isn't required to solve this now (because this is a purely internal API and we can change it at any time), I'd personally prefer if we made a `struct` (as discussed above) or some other strategy to reduce the number of arguments to `OS::open_dynamic_library()`. I don't think this is the last GDExtension-related piece of data that we're going to want to pass to this method.

**Comment by m4gr3d** [comment]
> While it isn't required to solve this now (because this is a purely internal API and we can change it at any time), I'd personally prefer if we made a `struct` (as discussed above) or some other strategy to reduce the number of arguments to `OS::open_dynamic_library()`. I don't think this is the last GDExtension-related piece of data that we're going to want to pass to this method.

@dsnopek I've added the change into a second commit since the changes are orthogonal to each other, and to make it easier to review.

Let me know if you want me to collapse the commits together.

**Review by dsnopek — APPROVED** [review]
Thanks! I haven't tested it, but the code looks good to me :-)

**Comment by m4gr3d** [comment]
> Thanks! I haven't tested it, but the code looks good to me :-)

I validated the fix in https://github.com/godotengine/godot/issues/87785#issuecomment-2066760827

**Comment by akien-mga** [comment]
Thanks!
