### PR TITLE
Respect "compress_binary_resources" editor setting on scene import

### LINKED ISSUE #71538: glTF file import creates files that are too large
### Godot version

4.0 noticed since beta 4

### System information

Windows 10 and Arch Linux

### Issue description

When importing a glb or gltf file, the `.scn` file created in `.godot/imported` is much *much* larger than creating a new inherited scene, clearing inheritance (so the scene contains all the mesh information), and saving *that* as a `.scn` manually.

I've noticed this in my own projects, where manually creating a `.scn` file by clearing inheritance results in a file that is 60 KB, whereas the `.scn` file created by godot in the `.godot/imported` folder is 3.1 MB, **50 times larger**. In this same project, adding together the file sizes of all the `.scn` files created by importing either a `.glb` or `.gltf` file shows that there are 700 MB of `.scn` files. The *entire* size of my assets folder including textures and audio is only 192 MB. By manually turning every glb or gltf file into a `.scn` by clearing inheritance, and then excluding `*.glb` and `*.gltf` resources in my export profile, I can bring my pck down from 767 MB to 73 MB, a 10 times reduction in size.

### Steps to reproduce

1. Open blender, and export a default cube as a gltf or glb into a Godot project.

2. Open Godot, importing the model. Navigate to `.godot/imported` and notice the size of the created `.scn` file.
image

3. Right click on the gltf file in Godot, choose "New inherited scene". Save this scene as a `.scn` file. Then, right click on the root node and select "Clear inheritance", and save again. Notice the size of this `.scn` file.
image
In this example, the file *I* created is 2.6 times smaller.

4. Go to the scene menu, and choose "Save Scene As", saving it as a `.tscn` file. Notice the size of the file.
image
The `.tscn` file is smaller than the `.scn` file created by Godot, even though it is text based and not binary and thus should be larger.

5. Navigate to the `.godot/imported` directory and *copy* the created `.scn` file into your Godot project. Open the `.scn` file in the editor, and as in step 4, save it as a `.tscn` file as well. Note the file size.
image
Notice that now, it is the same size as the `.tscn` file *I* created in step 4.

6. Diff these two `.tscn` files together.
image
Notice that the only difference between the file created manually by making a new scene and clearing inheritance, and the file created automatically by Godot on import, is the uid assigned to the scene. Therefore, there has been zero loss of content or functionality to explain why the `.scn` created manually is 2.6 times smaller.

7. Reopen the `.scn` file created automatically by Godot during import, and "Save Scene As" again, but this time, continue to save it as a `.scn` file, just with a new name. Note the file size.
image
Even though no modifications were made to the file, and it was simply resaved into the same file format, it is still 2.6 times smaller than the file created automatically by Godot.

### Minimal reproduction project

[gltf.zip](https://github.com/godotengine/godot/files/10431349/gltf.zip)

### PR DESCRIPTION
**Pull request by gelvinp**
`ResourceImporterScene::import()` did not check the `filesystem/on_save/compress_binary_resources` editor setting to set `FLAG_COMPRESS` when saving after import, while `EditorNode::save_resource_in_path()` did, causing imported scenes (e.g. from gLTF files) to be larger than scenes created by manually saving in the editor.

Closes #71538

### CODE REVIEW

**Comment by Calinou** [comment]
Note for users and testers: you **must** remove the `.godot/` folder in the project while the editor is closed for changes from this PR to be effective. Godot will not automatically reimport resources when you toggle the **Compress Binary Resources** editor setting.

**Review by Calinou — APPROVED** [review]
Tested locally (rebased against `master` a83eb16fba5bb3da086b41cbd79e6f95b09eb8ee), it works. The imported SCN file from the MRP now weighs 1.8 KB instead of 4.8 KB.

File: editor/import/resource_importer_scene.cpp [hunk 1]
```diff
@@ -2528,6 +2529,11 @@ Error ResourceImporterScene::import(const String &p_source_file, const String &p
 
 	progress.step(TTR("Saving..."), 104);
 
+	int flg = 0;
+	if (EDITOR_GET("filesystem/on_save/compress_binary_resources")) {
+		flg |= ResourceSaver::FLAG_COMPRESS;
+	}
```
Comment (Calinou) [inline editor/import/resource_importer_scene.cpp:2535]: Is `flags` already taken? I think we have space to use a fully spelled out variable name :slightly_smiling_face:

Comment (gelvinp) [reply editor/import/resource_importer_scene.cpp:2535]: oop, sure thing. Let me give that a cursory compile and I'll push it up right now.

**Comment by akien-mga** [comment]
Thanks!
