### PR TITLE
Check if action name exists before adding it or renaming an action to it

### LINKED ISSUE #54698: Renaming actions in the Input Map editor causes other actions to be overwritten
### Godot version

Godot_v4.0-dev.20211027

### System information

Windows 11

### Issue description

The rename feature in Input Map editor is overwriting names of other items (cloning 1 name to another), returning an error, but not correcting the second name that got messed up.

### Steps to reproduce

Enter rename mode on one item from the Input Map editor, click on another item to finalize the rename, which will then replace the name of the second item with the name of the first item. It then throws an error complaining about the duplicate name, while not returning it to its previous name.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by madmiraal**
Currently, the check whether or not an action name already exists is only done when trying to change the project setting. This prevents any corrective action being taken. As identified by @SpiceyWolf in #54698, this will leave a renamed Action with the invalid duplicate name in the Input Map editor.

This PR performs the check before trying to change the project setting and, in the case of a rename, sets the name back to the old name.

Fixes: #54698

### CODE REVIEW

File: editor/project_settings_editor.cpp [hunk 1]
```diff
@@ -275,10 +275,8 @@ void ProjectSettingsEditor::_editor_restart_close() {
 void ProjectSettingsEditor::_action_added(const String &p_name) {
 	String name = "input/" + p_name;
 
-	if (ProjectSettings::get_singleton()->has_setting(name)) {
-		action_map->show_message(vformat(TTR("An action with the name '%s' already exists."), name));
-		return;
-	}
+	ERR_FAIL_COND_MSG(ProjectSettings::get_singleton()->has_setting(name),
+			"An action with the name already exists.");
```
Comment (akien-mga) [inline editor/project_settings_editor.cpp:279]:
```suggestion
			"An action with this name already exists.");
```
Assuming that the name is visible in the UI so redundant in the message.

Same for the other message.

**Review by akien-mga — APPROVED** [review]

File: editor/project_settings_editor.cpp (hunk 1 above)
Comment (madmiraal) [reply editor/project_settings_editor.cpp]: Done.

**Comment by akien-mga** [comment]
Thanks!
