### PR TITLE
fixed billboarding for non uniform scale

### LINKED ISSUE #64505: Particle billboarding shader uses the x scale for both x and y
### Godot version

v4.0.alpha.custom_build [2e24b7653]

### System information

Linux Fedora, Radeon RX 590

### Issue description

This code
```
mat4 mat_world = mat4(normalize(INV_VIEW_MATRIX[0]) * length(MODEL_MATRIX[0]), normalize(INV_VIEW_MATRIX[1]) * length(MODEL_MATRIX[0]),normalize(INV_VIEW_MATRIX[2]) * length(MODEL_MATRIX[2]), MODEL_MATRIX[3]);
```
Should be changed to:
```

	mat4 mat_world = mat4(normalize(INV_VIEW_MATRIX[0]) * length(MODEL_MATRIX[0]), normalize(INV_VIEW_MATRIX[1]) * length(MODEL_MATRIX[1]),normalize(INV_VIEW_MATRIX[2]) * length(MODEL_MATRIX[2]), MODEL_MATRIX[3]);
```

Note the second length uses MODEL_MATRIX[1] instead of 0.

### Steps to reproduce

Use a XYZ scale curve on a particle system

### Minimal reproduction project

_No response_

### LINKED ISSUE #64722: Non uniform scale in particles causes billboard to shear when there's an angle
### Godot version

v4.0.alpha.custom_build [2e24b7653]

### System information

Linux Fedora, Radeon RX 590

### Issue description

The quad in the video has two scale curves:
image
So on the Y axis, it's supposed to grow, but on the X axis, it will grow and then shrink.
In the second part of the video, you can see is working correctly on a straight quad, but when the quad gains an angle (first part of the video) the billboard shears the quad.
I believe that this is just a wrong order of transformations applied (scale after rotation) but it's all in a single matrix, so I'm not sure how to fix it.

https://user-images.githubusercontent.com/7917475/185897444-773dcc78-6d64-4c47-b268-8362516665e1.mp4

### Steps to reproduce

This is actually a bit complex due to https://github.com/godotengine/godot/issues/64505, please download MRP.

### Minimal reproduction project

**THIS IS A SINGLE TSCN FILE!! NOT A PROJECT**

[BillboardShear.zip](https://github.com/godotengine/godot/files/9393407/BillboardShear.zip)

### PR DESCRIPTION
**Pull request by QbieShay**
Closes #64722. Closes #64505.

Fixed billboarding for nonuniform scale:
1. using x and y and z length for scaling
2. fixing incorrect order of matrices which caused shearing

### CODE REVIEW

**Comment by Chaosus** [comment]
I don't understand the math behind it, so it's better to be asked @clayjohn or @reduz. Note that If you change it, then `Material` should be changed accordingly: https://github.com/godotengine/godot/blob/03b92ae9ba4ea6b1f610d2bad068ae87b595fbd3/scene/resources/material.cpp#L937 https://github.com/godotengine/godot/blob/03b92ae9ba4ea6b1f610d2bad068ae87b595fbd3/scene/resources/material.cpp#L939

**Comment by QbieShay** [comment]
Oh, thank you @Chaosus ! I missed that

**Comment by QbieShay** [comment]
I don't think I added it at all, but I made a little mess with git today. I'll fix it by tomorrow's pr review

**Comment by QbieShay** [comment]
The code is actually incorrect :/

File: scene/resources/material.cpp [hunk 1]
```diff
@@ -934,9 +934,9 @@ void BaseMaterial3D::_update_shader() {
 		} break;
 		case BILLBOARD_PARTICLES: {
 			//make billboard
-			code += "	mat4 mat_world = mat4(normalize(INV_VIEW_MATRIX[0]) * length(MODEL_MATRIX[0]), normalize(INV_VIEW_MATRIX[1]) * length(MODEL_MATRIX[0]),normalize(INV_VIEW_MATRIX[2]) * length(MODEL_MATRIX[2]), MODEL_MATRIX[3]);\n";
+			code += "	mat4 mat_world = mat4(normalize(INV_VIEW_MATRIX[0]) * length(MODEL_MATRIX[0]), normalize(INV_VIEW_MATRIX[1]) * length(MODEL_MATRIX[1]),normalize(INV_VIEW_MATRIX[2]) * length(MODEL_MATRIX[2]), MODEL_MATRIX[3]);\n";
```
Comment (clayjohn) [inline scene/resources/material.cpp:937]: I think you can just insert the "keep scale" code in between these two lines. I tested it out quickly and it seems to work if you revert these changes and then just add the following between the two lines:
```
if (flags[FLAG_BILLBOARD_KEEP_SCALE]) {
	code += "	mat_world = mat_world * mat4(vec4(length(MODEL_MATRIX[0].xyz), 0.0, 0.0, 0.0),vec4(0.0, length(MODEL_MATRIX[1].xyz), 0.0, 0.0), vec4(0.0, 0.0, length(MODEL_MATRIX[2].xyz), 0.0), vec4(0.0, 0.0, 0.0, 1.0));\n";
}
```

Comment (QbieShay) [reply scene/resources/material.cpp:937]: Thanks Clay! Will update the PR before tomorrow

**Comment by QbieShay** [comment]
Well, it was a very long day.

Tested the change on this project: 
[particlebillboardtest.zip](https://github.com/godotengine/godot/files/10725995/particlebillboardtest.zip)

**Review by clayjohn — APPROVED** [review]
Looks good to me! Tested locally and it works well.

**Comment by QbieShay** [comment]
I noticed that the keep scale is doing funny stuff with y billboard, may be worth fixing later? I didn't change the behaviour because i wanted to get this fix in for 4.0, but i was unsure about the scale for y billboards.

**Comment by clayjohn** [comment]
> I noticed that the keep scale is doing funny stuff with y billboard, may be worth fixing later? I didn't change the behaviour because i wanted to get this fix in for 4.0, but i was unsure about the scale for y billboards.

I think both billboard_Y and billboard_enabled ignore the custom scale/rotation from the particles which in the MRP makes them appear to ignore scale. But ya, issues with billboard_y are definitely suited for a new Issue/PR

**Comment by YuriSizov** [comment]
Thanks!
