### PR TITLE
Validate image formats, check if resize_to_po2 failed

### LINKED ISSUE #46480: Executing `Image.compress` crashes Godot
**Godot version:**
3.2.4.rc.custom_build. 8385a0d8a

**OS**
Ubuntu 20.04 - Ubuntu 3.36 X11

**Issue description:**
Executing
```
var q_Image : Image = Image.new()

func _process(_delta : float) -> void:
	q_Image = Image.new()
	q_Image.create(15, 15, false, 3)
	q_Image.compress(5,5,5)
```

crashes with this info
```
ERROR: resize_to_po2: Cannot resize in compressed or custom image formats.
   At: core/image.cpp:872.
core/pool_vector.h:308:75: runtime error: reference binding to null pointer of type 'const unsigned char'
modules/pvr/image_compress_pvrtc.cpp:69:4: runtime error: null pointer passed as argument 2, which is declared to never be null
godots: thirdparty/pvrtccompressor/PvrTcEncoder.cpp:388: static void Javelin::PvrTcEncoder::EncodeRgba4Bpp(void*, const Javelin::RgbaBitmap&): Assertion `bitmap.GetBitmapWidth() == bitmap.GetBitmapHeight()' failed.
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by pfertyk**
This should fix #46480. The main problem was that we resize an image in `modules/pvr/image_compress_pvrtc.cpp` and assume that it always works. However, the resizing can fail for some formats. I've figured we can fix this in 2 ways:
* change the signature of the `resize_to_po2` method to return `Error` instead of `void` and check that error in `modules/pvr/image_compress_pvrtc.cpp` to stop the method if the resizing failed
* repeat the initial check to see if the conditions that caused the resizing have been fixed and if not, stop the method

Changing the signature seemed like a big step, so I went with the second approach :) Let me know if it's acceptable.

I've also added some checks to make sure that methods like `compress` are called with proper formats. To do this, I've introduced new values to some enums. Let me know if this is ok or if I need to update some docs as well (the values are not really meant to be used, they just represent the max value, but maybe we want them in the documentation anyway).

### CODE REVIEW

File: core/io/image.cpp [hunk 1]
```diff
@@ -2403,6 +2406,8 @@ Error Image::compress_from_channels(CompressMode p_mode, UsedChannels p_channels
 			ERR_FAIL_COND_V(!_image_compress_bptc_func, ERR_UNAVAILABLE);
 			_image_compress_bptc_func(this, p_lossy_quality, p_channels);
 		} break;
+		case COMPRESS_MAX: {
```
Comment (qarmin) [inline core/io/image.cpp:2409]: Shouldn't this case return an error?

Comment (pfertyk) [reply core/io/image.cpp:2409]: Good point, I'll change this :)

Comment (pfertyk) [reply core/io/image.cpp:2409]: Done ;)

**Comment by pfertyk** [comment]
Fixed conflicts ;)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.
