### PR TITLE
[macOS] Remove 10.6+ runtime version checks, add 10.12+ runtime version checks

### LINKED ISSUE #13654: Godot 3.0 crashes when opening project on Mac OSX 10.9.5
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Mac OSX 10.9.5, Godot 3.0 beta1

**Issue description:**
Godot 3.0.beta.build1 crashes after creating new project or opening existing project.

I first trashed my Godot 3.0.alpha.build2 version and the one project I had created using it. I downloaded Godot 3.0.beta.build1 and dragged it to my applications folder. I started the app and got the create project dialog entered a directory and a folder and clicked create. Then the app crashed before I get to the editor. When I reopen the Godot, the new project is listed but when a double click it Godot crashes again.

I have posted the beginning of the error log below for reference. I also noticed that the size of the beta1 app is only 72 MB while the alpha2 app is 140.7 MB.

**Steps to reproduce:**
Start a new project causes a crash
Open a project causes a crash

**top section of error log**
Process:         Godot [1014]
Path:            /Users/USER/Downloads/Godot.app/Contents/MacOS/Godot
Identifier:      org.godotengine.godot
Version:         3.0-dev (3.0-dev)
Code Type:       X86-64 (Native)
Parent Process:  ??? [1]
Responsible:     Godot [1014]
User ID:         501

Date/Time:       2017-12-01 15:57:57.170 -0800
OS Version:      Mac OS X 10.9.5 (13F1507)
Report Version:  11
Anonymous UUID:  2801C782-005A-B2E4-6A7D-62CD0C8C02DF

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Dyld Error Message:
  Symbol not found: __os_log_internal
  Referenced from: /Users/USER/Downloads/Godot.app/Contents/MacOS/Godot
  Expected in: /usr/lib/libSystem.B.dylib

### PR DESCRIPTION
**Pull request by bruvzg**
Tested on 10.9.5 with binary built on 10.13.2.

Fixes #13654

### CODE REVIEW

File: platform/osx/os_osx.mm [hunk 1]
```diff
@@ -1807,10 +1806,14 @@ static int get_screen_index(NSScreen *screen) {
 		CGFloat menuBarHeight = [[[NSApplication sharedApplication] mainMenu] menuBarHeight];
 		if (menuBarHeight != 0.f) {
 			size.y += menuBarHeight;
-#if MAC_OS_X_VERSION_MAX_ALLOWED <= 101104
 		} else {
-			size.y += [[NSStatusBar systemStatusBar] thickness];
+#if MAC_OS_X_VERSION_MAX_ALLOWED >= 101200
```
Comment (akien-mga) [inline platform/osx/os_osx.mm]: Wouldn't a direct test without `#if` be equivalent and simpler?
```
if (floor(NSAppKitVersionNumber) < NSAppKitVersionNumber10_12) {
    size.y += [[NSStatusBar systemStatusBar] thickness];
}
```

Comment (bruvzg) [reply platform/osx/os_osx.mm]: `#if MAC_OS_X_VERSION_MAX_ALLOWED` is for compiling on pre 10.12 since NSAppKitVersionNumber10_12 is not defined.

Comment (akien-mga) [reply platform/osx/os_osx.mm]: Isn't it overkill to do both compile and runtime checks? For example currently if you build for 10.9 on 10.12, you will get a logger (albeit without the 10.12-specific part of it), but if you build for 10.9 on 10.9 you won't have it.

I think runtime checks might be enough, with custom defines of `NSAppKitVersionNumber10_{10,11,12}` when undefined, no?

Comment (akien-mga) [reply platform/osx/os_osx.mm]: Though I guess in the case of the logger without the compiler defines it might fail build if older SDKs don't know the methods.

Comment (bruvzg) [reply platform/osx/os_osx.mm]: Yep, without compile time checks it won't build without 10.12 SDK (min. Xcode 8.0 on macOS 10.11.5).
