### PR TITLE
Make custom types more subtle and more useful

### LINKED ISSUE #26980: Wrong type is shown in tooltip of custom not in scene tree
**Godot version:**
Godot 3.1 RC3

**OS/device including version:**
MacOSX 10.14.3

**Issue description:**
In editor in scene tree if user adds registered class node, tooltip will show base class as type.

**Steps to reproduce:**

1. Create script.
2. Register it as class.
3. Add node of this class to scene.
4. Loot at the tooltip. 

**Minimal project**

```
extends Node

class_name MyCustomNode

func _ready():
    pass
```

### PR DESCRIPTION
**Pull request by bojidar-bg**
Implements https://github.com/godotengine/godot/issues/6067#issuecomment-469575425 (@aaronfranke's idea).
Fixes #26980.

Also, makes custom type icons show in the AnimationPlayer editor.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: editor/scene_tree_editor.cpp [hunk 1]
```diff
@@ -295,6 +304,9 @@ bool SceneTreeEditor::_add_nodes(Node *p_node, TreeItem *p_parent) {
 		Ref<Script> script = p_node->get_script();
 		if (!script.is_null()) {
 			item->add_button(0, get_icon("Script", "EditorIcons"), BUTTON_SCRIPT, false, TTR("Open Script:") + " " + script->get_path());
+			if (EditorNode::get_singleton()->get_object_custom_type_base(p_node) == script) {
+				item->set_button_color(0, item->get_button_count(0) - 1, Color(1, 1, 1, 0.5));
```
Comment (aaronfranke) [inline editor/scene_tree_editor.cpp]: I would personally make it more transparent than 50%, since it's useful to know if you look closely but it's not something you usually need to see at a quick glance or when looking through your hierarchy.

**Review by aaronfranke — APPROVED** [review]
Very nice! I can confirm this works with existing projects and has the expected behavior, with no noticeable problems. 

Note that it only works with types added via `add_custom_type` and not `class_name`, which I actually think is ideal because it prevents user-made classes from showing up with faded scripts. It makes sense to only fade scripts for types added via plugins and `add_custom_type`.

File: editor/scene_tree_editor.cpp (hunk 1 above)
Comment (bojidar-bg) [reply editor/scene_tree_editor.cpp]: I initially made it disabled (and unclickable), but then decided to only use the disabled style (which is 50% transparent) with a working button.

**Comment by akien-mga** [comment]
Thanks!

**Comment by toiletsnakes** [comment]
THERE WAS MUCH REJOICING!
👏 🎈
