### PR TITLE
Fix drag and drop `@export` variable assignment when script has errors

### LINKED ISSUE #110735: Drag and drop `@export` variable into scripts with errors does not assign value
### Tested versions

master

### System information

N/A

### Issue description

Drag and drop `@export` variables recently got added: https://github.com/godotengine/godot/pull/106341
If you drag and drop `@export` variable into a script with errors, it will not assign the value once the script does not have the errors anymore.

### Steps to reproduce

1. Have a script with errors
2. Try drag and dropping an `@export` variable with `Alt`
3. After fixing the error, the variable is not assigned with dragged node/resource.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by fkeyzuwu**
Closes #110735

Might be a bit slow with a combination of long file system paths(string comparision), lots of errors and adding a lot of export variables at once, but that's a *very* extreme case. Although if anyone has an idea on how to do this better in terms of time complexity, feel free to suggest changes. But overall should work fine.

### CODE REVIEW

**Comment by fkeyzuwu** [comment]
Tested a bit more, seems to work well. Should be merged into 4.6 since it fixes a bug for a feature that was just merged. https://github.com/godotengine/godot/pull/106341

File: editor/script/script_text_editor.cpp [hunk 1]
```diff
@@ -2574,30 +2574,45 @@ void ScriptTextEditor::_assign_dragged_export_variables() {
...
+
+		for (const ScriptLanguage::ScriptError &error : errors) {
+			if (error.path == scr_path) {
+				script_has_errors = true;
+				break;
+			}
+		}
+
+		if (!script_has_errors) {
+			bool success = si->set(dragged_export.variable_name, dragged_export.value);
```
Comment (kitbdev) [inline editor/script/script_text_editor.cpp]: This PR exposes a minor issue.

It is possible to assign a Resource or Node to the wrong type.
When dragging in two different Resources/Nodes with the same name it causes a script error. If the error is fixed by removing the first one, then the first one gets assigned to the var with the type of the second one.

It doesn't seem to cause any problems. It gets saved to the tscn file, but when running it is just null and there isn't even any errors printed somehow.

Ex. 
Drag "containers.gd" and "containers.tscn" to a script.
It will generate 
```gdscript
@export var containers: GDScript
@export var containers: PackedScene
```
and error. Remove the first line, and then the containers.gd will be assigned even though the type doesn't match.

image

It seems like it shouldn't be possible `GDScriptInstance::set` since it checks the type, I'm not sure what's going on.

It should be possible to check the types manually, probably with `ScriptInstance::get_property_type`.

~Or if we ensure the generated names are unique, that might also fix it.~ It can also happen when changing the type in some cases.

**Comment by fkeyzuwu** [comment]
just rebased, will work on this soon

File: editor/script/script_text_editor.cpp (hunk 1 above)
Comment (fkeyzuwu) [reply editor/script/script_text_editor.cpp]: `ScriptInstance::get_property_type` just returns the Variant::Type, which will most likely just be `Variant::OBJECT`, so we probably need something else.

Regarding creating unique generated names for dragged variables, I have thought of doing that in a separate PR. However for `@export` variables specifically, that kind of creates an annoying workflow, since it would probably create something like `container_1`, which you would then want to rename, and that would reset the export variables value.

**Comment by fkeyzuwu** [comment]
I have managed to fix the initial "bug" with saving the class name of the variable in the `DraggedExport` struct and checking it against the property type hint.

While this does work, like you said it seems to be a separate problem. If you also change the type of the `@export` variable, it does not reset the value and keeps it assigned. Fixing this would have to be done in a separate PR since it doesn't have to do with drag-n-drop export variables, its just how export variables work in general.

There is an issue and PR about it: https://github.com/godotengine/godot/issues/104323, https://github.com/godotengine/godot/pull/104338
The change was introduced here: https://github.com/godotengine/godot/pull/84446

Anyways, updated to fix the original bug that this exposes with the name collision. Changing the type _while_ the name collision error is happening does work correctly so I think it's fine. Don't like how it adds yet another for loop where if its a giant class it will run through a lot of properties, but I don't see a work around. It does only run once when the script doesn't have errors anymore though, so I think its fine.

**Review by kitbdev — APPROVED** [review]
Looks good.

**Comment by Repiteo** [comment]
Thanks!
