### PR TITLE
Linux/BSD: Modify only keypad keys

### LINKED ISSUE #102259: Numpad is not properly detected on Wayland
### Tested versions

Not reproducible in 4.3.stable
Reproducible in v4.4.beta.custom_build [1586c5674]

I will try to bisect the issue later, but I think this is at least 2 weeks old now.

### System information

Godot v4.4.beta (1586c5674) - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Thu, 05 Dec 2024 16:26:44 +0000 on Wayland - Wayland display driver, Single-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XT (RADV NAVI31) - AMD Ryzen 9 7900X 12-Core Processor (24 threads)

### Issue description

In the Wayland version of the editor, there is a regression whereby typing using the numpad does not work properly anymore. It appears that everything will work the first time Godot is launched in the Wayland session, then after some time (probably simply alt-tabbing out and back in), numpad behaves as if it was off (typing numbers becomes impossible and the cursor is moved instead). This behavior is exclusive to Godot, the numpad works properly everywhere else in the session.
In Godot 4.3, there is no such issue, it appeared sometime around 4.4 beta 1 or maybe a bit earlier, I will try to bisect the exact commit.

### Steps to reproduce

On a Wayland session, and with the Wayland version of the editor (Run/Platforms/Prefer Wayland on - no issue on X11 version), alt-tab out and back in the editor. Numpad should not be detected properly anymore, even after completely closing the editor (and even the terminal that launched it) and opening it again.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by deralmas**
Should greatly alleviate #102137.
Fixes #102259.

The `keycode` field of `InputEventKey` is supposed to be "unshifted"; That is, what the key would output if no modifier keys were pressed. This should match what's written on the key label, but `Key` enumerates also all keypad keys, which require a modifier. We thus require some extra checks for them.

Note that this can still allow "stuck keys", but that's an even deeper problem.

---

This should bring both the X11 and Wayland backend to "parity" with Windows. Now only keypad keys should be able to get stuck; Better than having every other "non-US" modifier at least.

Feedback appreciated on the X11 impl.

Also note that I purposely made the "is keypad" method specific to only the related (modified) `Key` enumerations. If that's excessive, we could replace it with a simple check between `XKB_KEY_KP_Space` and `XKB_KEY_KP_9` (same for the XK equivalent on X11), as all keypad scancodes are consecutive. That would require no other changes as I built the code to allow for "no matches" to the mapping table, just in case.

CC @bruvzg

### CODE REVIEW

**Comment by tdaven** [comment]
I can confirm this fixes the number pad issue mention on https://github.com/godotengine/godot/pull/101848.

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected. The issue with script editor hover tooltips no longer appearing until you alt-tab out and back in is also fixed with this PR.

Disabling numlock in the script editor works as intended for navigational purposes, but this was also the case in `master` before this PR.

Code looks good to me.

```
Operating System: Fedora Linux 41
KDE Plasma Version: 6.2.5
KDE Frameworks Version: 6.10.0
Qt Version: 6.8.1
Kernel Version: 6.12.9-200.fc41.x86_64 (64-bit)
Graphics Platform: X11
```

### Before

Numlock OFF | Numlock ON
-|-
image | image

### After

*Notice that Unicode is now "Kp 0" instead of "0" for **Numlock ON**.*

Numlock OFF | Numlock ON
-|-
image | image

File: platform/linuxbsd/x11/display_server_x11.cpp [hunk 1]
```diff
@@ -3562,8 +3562,7 @@ void DisplayServerX11::_handle_key_event(WindowID p_window, XKeyEvent *p_event,
 	// XLookupString returns keysyms usable as nice keycodes.
 	char str[256] = {};
 	XKeyEvent xkeyevent_no_mod = *xkeyevent;
-	xkeyevent_no_mod.state &= ~ShiftMask;
-	xkeyevent_no_mod.state &= ~ControlMask;
+	xkeyevent_no_mod.state = 0;
```
Comment (bruvzg) [inline platform/linuxbsd/x11/display_server_x11.cpp:3565]: This change completely breaks some layouts. Try DVORAK, it will return QWERTY key codes and Russian labels (picking it from a previous layout I guess, since DVORAK has bit 13 set in the state, which is group id).

For the reference: keyboard layouts config used to test:

Screenshot From 2025-02-02 13-21-30

> A State Field from an XKB State
> 
> Many events report the keyboard state in a single state field. Using XKB, a state field combines modifiers, group and the pointer button state into a single sixteen bit value as follows:
> 
>    Bits 0 through 7 (the least significant eight bits) of the effective state comprise a mask of type KEYMASK which reports the state modifiers.
>
>    Bits 8 through 12 comprise a mask of type BUTMASK which reports pointer button state.
>
>    Bits 13 and 14 are interpreted as a two-bit unsigned numeric value and report the state keyboard group.
>
>    Bit 15 (the most significant bit) is reserved and must be zero.

I guess we only want to unset modifier bits, not all of it, like:

```suggestion
	xkeyevent_no_mod.state &= 0xFF00;
```

**Review by bruvzg — CHANGES_REQUESTED** [review]
Seems to fix Numpad issue, but breaks some layouts on X11.

File: platform/linuxbsd/x11/display_server_x11.cpp (hunk 1 above)
Comment (bruvzg) [reply platform/linuxbsd/x11/display_server_x11.cpp:3565]: > You confirm that this change fixes other layouts, right?

With `xkeyevent_no_mod.state &= 0xFF00;` it seems to work fine in all cases I ahve tested.

**Review by bruvzg — APPROVED** [review]

File: platform/linuxbsd/x11/display_server_x11.cpp (hunk 1 above)
Comment (Marenz) [reply platform/linuxbsd/x11/display_server_x11.cpp]: Unfortunately it breaks the NEO layout layer4 "mod4" or "m4" here: 
image

See https://www.neo-layout.org.

I noticed it no longer working with the new 4.4 release and `git bisect`ed it down to commit 140a63be25cbcf0abdc363be3a3e52ea2bf05e9c of this PR...
