### PR TITLE
Notify instance binding data api of refcount increment/decrement

### LINKED ISSUE #16877: Memory leak with the gui_input() signal in C# / Mono
**Godot version: 3.0 stable, Mono 5.4.1.7**

**OS/device including version: win 8.1**

**Issue description:**
C# only
The Godot.Object passed as argument of the signal gui_event(ev) is not disposed of when the method finishes and is not garbage collected unless explicitly disposed of with ev.Dispose().
Consequence: wiggling your cursor above a control with a C# script that listens to the event without disposing of the object will leak Godot Objects at a rate of 60/second.

The workaround is to call ev.Dispose() at the end of the gui_input method. It is bad practice to dispose of an object outside of its creation scope because there can still be references to this object, but it is no longer valid! I forgot to test what happens if several scripts listen to the same gui_input(ev). If the same object is reused in the different scripts then I will get a runtime exception ObjectDisposedException.

Possible solutions:
1) Emergency patch: Add this in the C# warnings in the docs:
http://docs.godotengine.org/en/latest/getting_started/scripting/c_sharp/c_sharp_basics.html#current-gotchas-and-known-issues
"Godot Objects passed as arguments of signals must be manually disposed of to avoid memory leaks. A method onGuiInput(Godot.Object ev) connected to the signal gui_input(object) must call ev.Dispose() before onGuiInput returns or ends."
Unfortunately I cannot use github right now, so I cannot do a pull request.

2) Best solution: automagically dispose of the object(s) when all the gui_input(ev) are finished.

3) If an automatic generation of the methods connected to signals is done before the solution 2) is implemented, add an ev.Dispose in the methods' bodies to help not to forget it.

**Steps to reproduce:**
Create any control, add a C# script to it, connect a method to the signal gui_input(object).
Run the scene and wiggle your cursor above the control while looking at the number of godot objects in the debugger's monitor tab.

**Minimal reproduction project:**
[InputEventObjectLeak.zip](https://github.com/godotengine/godot/files/1743286/InputEventObjectLeak.zip)

### PR DESCRIPTION
**Pull request by neikeq**
Refcount increment/decrement notifications are crucial to avoid circular references between managed (garbage collected) and native instances. This notification was already implemented for languages, but not for instance binding data.

This would fix #16877

I made some tweaks for performance reasons like adding the instance binding count field to avoid looping when there are no instance bindings, and not notifying at all when the refcount is higher than 2 on increment or 1 on decrement (The notification is needless for higher values. Actually, only equal to 2 on increment and 1 on decrement should be necessary, but not sure if anyone may find 1 and 0 respectively to be useful).

### CODE REVIEW

**Comment by neikeq** [comment]
Almost forgot to mention this. I didn't add the new ScriptLanguage methods to native script and plugin script. I'm not familiar with them.

**Comment by neikeq** [comment]
@reduz :)?

File: core/object.cpp [hunk 1]
```diff
@@ -1825,7 +1825,11 @@ void *Object::get_script_instance_binding(int p_script_language_index) {
 	//as it should not really affect performance much (won't be called too often), as in far most caes the condition below will be false afterwards
 
 	if (!_script_instance_bindings[p_script_language_index]) {
-		_script_instance_bindings[p_script_language_index] = ScriptServer::get_language(p_script_language_index)->alloc_instance_binding_data(this);
+		void *script_data = ScriptServer::get_language(p_script_language_index)->alloc_instance_binding_data(this);
+		if (script_data) {
+			instance_binding_count++;
```
Comment (reduz) [inline core/object.cpp]: I would use an atomic counter here for thread safety (check safe_refcount.h)

File: core/object.h [hunk 2]
```diff
@@ -484,10 +484,12 @@ class Object {
 	void _set_indexed_bind(const NodePath &p_name, const Variant &p_value);
 	Variant _get_indexed_bind(const NodePath &p_name) const;
 
-	void *_script_instance_bindings[MAX_SCRIPT_INSTANCE_BINDINGS];
-
 	void property_list_changed_notify();
 
+	friend class Reference;
+	uint8_t instance_binding_count;
```
Comment (reduz) [inline core/object.h]: I think a bool may actually be better that you set to true, since it's never really decremented.  No need to use thread safety either if so.

**Review by reduz — CHANGES_REQUESTED** [review]

File: core/object.h (hunk 2 above)
Comment (neikeq) [reply core/object.h]: I don't see how a bool would remove the need for thread safety. BTW, is there a reason not to use a Vector for `_script_instance_bindings` instead of a raw array?

Comment (reduz) [reply core/object.h]: ah nevermind, i misunderstood, yes, a bool won't do. just use an atomic operation for incrementing and it should be fine.

**Comment by mhilbrunner** [comment]
Whats the status of this?

**Comment by mhilbrunner** [comment]
@neikeq Can this be merged or does it still need changes? Or do we close this? :)

**Comment by neikeq** [comment]
There are pending changes, but I had something to discuss about it with reduz before which I will do next days.

**Comment by neikeq** [comment]
@hpvb Thanks!

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we only plan to cherry-pick critical bug fixes to the 3.0 branch, unless there is very strong support in favor of a specific non-critical issue. Removing cherrypick label for 3.0.
