### PR TITLE
C#: Hide hostfxr not found error

### LINKED ISSUE #70510: Editor can't find .NET when installed from the official Ubuntu feeds
### Godot version

4.0.beta10.mono.official.d0398f62f

### System information

Ubuntu 22.10 with dotnet 6 

### Issue description

If you are using Ubuntu 22.10, maybe other version, and you install .Net 6.0 from the official Ubuntu feeds, Godot 4 can't find the .Net package's install location and therefore can't find `/usr/share/dotnet/host/fxr`.

This is because the Ubuntu feeds put the dotnet directory at `usr/lib/dotnet` and if you install the package directly from the Microsoft official feeds the package is at `usr/share/dotnet`

When launching Godot 4, the error message is: `"The host fxr folder does not exist: /usr/share/dotnet/host/fxr"`

### Steps to reproduce

1. Start from a clean machine - you must not have any version of dotnet installed from any distribution/official  feed or Microsoft feed.
2. Download Godot 4.
3. Install to `/opt/godot` - this mean the Godot executable is at `/opt/godot4/Godot_v4.0-beta10_mono_linux.x86_64`
5. **Run** `sudo apt install dotnet-sdk-6.0`
6. **Run** `/opt/godot4/Godot_v4.0-beta10_mono_linux.x86_64`

Error message
```bash
ERROR: The host fxr folder does not exist: /usr/share/dotnet/host/fxr
   at: try_get_path_from_dotnet_root (modules/mono/editor/hostfxr_resolver.cpp:323)
```

### Minimal reproduction project

This is during the program launch, I'm happy to attach logs if that will help. I don't think a repro project helps here.

### PR DESCRIPTION
**Pull request by raulsntos**
Godot tries to find hostfxr in two locations, the method that tries to retrieve the location printed an error when it was not found. So when the first location fails it was printing an error, even if the second location succeeded, and users were left confused thinking there was something wrong with their installation.

Now the error will only be printed when stdout verbose is enabled. Users will still get an error later if hostfxr is not found in any of the two locations.

- Closes https://github.com/godotengine/godot/issues/70510.

I originally wanted to wait for _Editor unification_ but we've been receiving multiple error reports about this, so I think we should address it sooner.

### CODE REVIEW

File: modules/mono/editor/hostfxr_resolver.cpp [hunk 1]
```diff
@@ -320,7 +320,12 @@ bool get_dotnet_root_from_env(String &r_dotnet_root) {
 
 bool godotsharp::hostfxr_resolver::try_get_path_from_dotnet_root(const String &p_dotnet_root, String &r_fxr_path) {
 	String fxr_dir = path::join(p_dotnet_root, "host", "fxr");
-	ERR_FAIL_COND_V_MSG(!DirAccess::exists(fxr_dir), false, "The host fxr folder does not exist: " + fxr_dir);
+	if (!DirAccess::exists(fxr_dir)) {
+		if (OS::get_singleton()->is_stdout_verbose()) {
+			ERR_PRINT("The host fxr folder does not exist: " + fxr_dir);
```
Comment (AThousandShips) [inline modules/mono/editor/hostfxr_resolver.cpp:325]:
```suggestion
			ERR_PRINT("The host fxr folder does not exist: " + fxr_dir + ".");
```
Let's get in a style fix here while we're at it

**Review by AThousandShips — APPROVED** [review]
LGTM!

**Review by YuriSizov — APPROVED** [review]
Makes sense.

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.
