### PR TITLE
Clamp return value of SceneTreeTimer::get_time_left to 0.0

### LINKED ISSUE #73607: SceneTreeTimer time_left property goes into negative values
### Godot version

4.0.rc1

### System information

Linux Mint 21.1

### Issue description

When `SceneTreeTimer` is created using get_tree().create_timer(), it doesn't stop at `time_left = 0.0`, but goes into negative values. Normal `Timer` stops at exactly `0.0`, so I expected `SceneTreeTimer` to be the same.

### Steps to reproduce

1. Create an empty scene with one node.
2. Attach this script:
```gdscript
extends Node


var timer: SceneTreeTimer


func _ready() -> void:
	timer = get_tree().create_timer(1.0)


func _process(delta: float) -> void:
	assert(
		timer.time_left >= .0,
		"time_left: %f" % [timer.time_left] # time_left is negative
	)
```
3. Run.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by chutchinson**
This changes alters ```SceneTreeTimer::get_time_left``` to clamp to zero when negative, to match the behavior of ```Timer::get_time_left```. Timer sets time_left to negative in certain circumstances (i.e. stopping the timer), but ```get_time_left``` always returns positive values (or zero). This fix assumes that the **SceneTreeTimer** and **Timer** APIs are intended to be orthogonal.

Fixes #73607

### CODE REVIEW

File: scene/main/scene_tree.cpp [hunk 1]
```diff
@@ -530,6 +530,7 @@ void SceneTree::process_timers(double p_delta, bool p_physics_frame) {
 		} else {
 			time_left -= p_delta;
 		}
+
```
Comment (KoBeWi) [inline scene/main/scene_tree.cpp:533]: This change is unrelated and arguable. The `}` already acts as a separator, so empty line adds unnecessary space.

**Review by KoBeWi — APPROVED** [review]
Makes sense, but I think you should remove the empty line.

File: scene/main/scene_tree.cpp (hunk 1 above)
Comment (YuriSizov) [reply scene/main/scene_tree.cpp]: Applied this suggestion and force-pushed.

**Comment by YuriSizov** [comment]
Thanks!
