### PR TITLE
Change `VisualShaderNodeVec4Constant` type to vec4

### LINKED ISSUE #94509: [VisualShader] Default vec4 options are very hard to write to
### Tested versions

4.3-beta3

### System information

Windows10

### Issue description

It's really hard to edit default value for vec4

image

### Steps to reproduce

/

### Minimal reproduction project (MRP)

/

### PR DESCRIPTION
**Pull request by Chaosus**
I know it maybe too late to do this small compatibility breakage change but IDK, maybe this can be accepted for 4.3.

Before:
изображение

Afer:
изображение

Yes, after this change, users needs to recreate the vector4 values in their constants. I did not find a way to prevent this.

Also 
- Fix https://github.com/godotengine/godot/issues/94509

### CODE REVIEW

**Comment by akien-mga** [comment]
> Yes, after this change, users needs to recreate the vector4 values in their constants. I did not find a way to prevent this.

I think that if we want to do this change, we do need a way to convert the data, otherwise users will lose data and their shaders will break.

File: editor/plugins/visual_shader_editor_plugin.cpp [hunk 1]
```diff
@@ -311,8 +311,8 @@ void VisualShaderGraphPlugin::set_input_port_default_value(VisualShader::Type p_
 			Vector3 v = p_value;
 			button->set_text(String::num(v.x, 3) + "," + String::num(v.y, 3) + "," + String::num(v.z, 3));
 		} break;
-		case Variant::QUATERNION: {
```
[the remark this answers is not in the document]
Comment (Chaosus) [reply editor/plugins/visual_shader_editor_plugin.cpp:314]: Custom shader nodes does use only specific input/output types defined in `PortType`, so I think it's no longer relevant.

**Comment by Mickeon** [comment]
This would have to be documented in https://github.com/godotengine/godot-docs/pull/9250 if done by 4.3

File: scene/resources/visual_shader_nodes.cpp [hunk 2]
```diff
@@ -581,17 +583,53 @@ Quaternion VisualShaderNodeVec4Constant::get_constant() const {
...
+	}
+	constant = p_constant;
+	emit_changed();
+}
+
+Vector4 VisualShaderNodeVec4Constant::get_constant() const {
+	return constant;
+}
+
+#endif // DISABLE_DEPRECATED
```
Comment (akien-mga) [inline scene/resources/visual_shader_nodes.cpp:608]: We can't do this, the engine shouldn't have a different main behavior based on whether `DISABLE_DEPRECATED` is set.

`DISABLE_DEPRECATED` should just remove conversion code, not change how the engine works for the non-deprecated case.

Comment (Chaosus) [reply scene/resources/visual_shader_nodes.cpp:608]: ah, really...

**Comment by Chaosus** [comment]
`_set` method seems broken on master, so I cannot force it to change a type of property on fly. So closed for now.

**Comment by Chaosus** [comment]
Ok, so as discussed in core channel - its better to just introduce another Vector4 property and use it to configure the node and the internal `Quternion`. I've made it internal so it will not save its information to resource file.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
