### PR TITLE
Remove set_drag_forwarding_compat()

### LINKED ISSUE #71412: Error: Node3DEditorViewport::_get_drag_data_fw: Method not found.
### Godot version

Godot 4 Beta12

### System information

Windows 11/64, RTX 3070, Vulkan

### Issue description

Clicking and dragging in the viewport produces errors:

`ERROR: Error calling forwarded method from 'get_drag_data': 'Node3DEditorViewport::_get_drag_data_fw': Method not found.
   at: (scene/gui/control.cpp:1851)`

### Steps to reproduce

* Open an empty 3d scene
* Draw a selection box in the viewport

### Minimal reproduction project

n/a

### PR DESCRIPTION
**Pull request by KoBeWi**
Originally added in #71127
Technically it could use further cleanup, by removing `bind()` calls where not necessary.

Also fixes commented out perfectly working export profile drag and drop.
godot windows editor dev x86_64_E3UR6s1NBA

EDIT:
Fixes #71412

### CODE REVIEW

File: editor/action_map_editor.cpp [hunk 1]
```diff
@@ -578,7 +574,7 @@ ActionMapEditor::ActionMapEditor() {
 	action_tree->connect("button_clicked", callable_mp(this, &ActionMapEditor::_tree_button_pressed));
 	main_vbox->add_child(action_tree);
 
-	action_tree->set_drag_forwarding_compat(this);
+	action_tree->set_drag_forwarding(callable_mp(this, &ActionMapEditor::get_drag_data_fw).bind(action_tree), callable_mp(this, &ActionMapEditor::can_drop_data_fw).bind(action_tree), callable_mp(this, &ActionMapEditor::drop_data_fw).bind(action_tree));
```
Comment (akien-mga) [inline editor/action_map_editor.cpp:577]: If the syntax is always like this, maybe we could have a macro that sets up all three at once?
`SETUP_DRAG_FW(action_tree, ActionMapEditor);`

Comment (KoBeWi) [reply editor/action_map_editor.cpp:577]: Not all forwardings use all methods, so we'd need at least 2 (or 3?) macros. Also macro will make it more difficult to remove unnecessary `bind()`s.

But I can do that.

Comment (akien-mga) [reply editor/action_map_editor.cpp:577]: Yeah if it's not always the same with three methods and a bind of the base object it's maybe not worth macroing.

It's just a pretty verbose syntax compared to the previous one.

Maybe stylistically putting each callable_mp on a new line would help with readability at least.

Comment (KoBeWi) [reply editor/action_map_editor.cpp]: Ok, I changed it to macro. I needed 4 of them, but it's cleaner and less error-prone.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
