### PR TITLE
Fix critical regression

### LINKED ISSUE #18058: Segfault on latest master (Regression)
**Godot version:**

2f4f8de

**Issue description:**

```
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Haswell 
ERROR: operator[]: FATAL: Condition ' !_data._root ' is true.    
   At: core/map.h:597.
handle_crash: Program crashed with signal 4
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x348e0) [0x7f330507a8e0] (??:0)
[2] Map<String, Vector<EditorData::CustomType>, Comparator<String>, DefaultAllocator>::operator[](String const&) const (/home/noshyaar/git/godot/0/core/map.h:597 (discriminator 1))
[3] CustomPropertyEditor::edit(Object*, String const&, Variant::Type, Variant const&, int, String) (/home/noshyaar/git/godot/0/editor/property_editor.cpp:885)
[4] PropertyEditor::_custom_editor_request(bool) (/home/noshyaar/git/godot/0/editor/property_editor.cpp:3916 (discriminator 1))
[5] MethodBind1<bool>::call(Object*, Variant const**, int, Variant::CallError&) (/home/noshyaar/git/godot/0/core/method_bind.gen.inc:729 (discriminator 12))
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/noshyaar/git/godot/0/core/object.cpp:914 (discriminator 1))
[7] Object::emit_signal(StringName const&, Variant const**, int) (/home/noshyaar/git/godot/0/core/object.cpp:1195 (discriminator 1))
[8] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/noshyaar/git/godot/0/core/object.cpp:1241)
[9] Tree::propagate_mouse_event(Point2i const&, int, int, bool, TreeItem*, int, Ref<InputEventWithModifiers> const&) (/home/noshyaar/git/godot/0/scene/gui/tree.cpp:1911 (discriminator 4))
[10] Tree::propagate_mouse_event(Point2i const&, int, int, bool, TreeItem*, int, Ref<InputEventWithModifiers> const&) (/home/noshyaar/git/godot/0/scene/gui/tree.cpp:1951)
[11] Tree::propagate_mouse_event(Point2i const&, int, int, bool, TreeItem*, int, Ref<InputEventWithModifiers> const&) (/home/noshyaar/git/godot/0/scene/gui/tree.cpp:1951)
[12] Tree::_gui_input(Ref<InputEvent>) (/home/noshyaar/git/godot/0/scene/gui/tree.cpp:2603 (discriminator 5))
[13] MethodBind1<Ref<InputEvent> >::call(Object*, Variant const**, int, Variant::CallError&) (/home/noshyaar/git/godot/0/core/method_bind.gen.inc:729 (discriminator 12))
[14] Object::call_multilevel(StringName const&, Variant const**, int) (/home/noshyaar/git/godot/0/core/object.cpp:748 (discriminator 1))
[15] Object::call_multilevel(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/noshyaar/git/godot/0/core/object.cpp:855)
[16] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (/home/noshyaar/git/godot/0/scene/main/viewport.cpp:1370 (discriminator 2))
[17] Viewport::_gui_input_event(Ref<InputEvent>) (/home/noshyaar/git/godot/0/scene/main/viewport.cpp:1653 (discriminator 3))
[18] Viewport::input(Ref<InputEvent> const&) (/home/noshyaar/git/godot/0/scene/main/viewport.cpp:2353 (discriminator 2))
[19] Viewport::_vp_input(Ref<InputEvent> const&) (/home/noshyaar/git/godot/0/scene/main/viewport.cpp:1214)
[20] MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/noshyaar/git/godot/0/core/method_bind.gen.inc:729 (discriminator 12))
[21] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/noshyaar/git/godot/0/core/object.cpp:914 (discriminator 1))
[22] Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/noshyaar/git/godot/0/core/object.cpp:839)
[23] SceneTree::call_group_flags(unsigned int, StringName const&, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/noshyaar/git/godot/0/scene/main/scene_tree.cpp:250)
[24] SceneTree::input_event(Ref<InputEvent> const&) (/home/noshyaar/git/godot/0/scene/main/scene_tree.cpp:406 (discriminator 6))
[25] InputDefault::parse_input_event(Ref<InputEvent> const&) (/home/noshyaar/git/godot/0/main/input_default.cpp:324)
[26] OS_X11::process_xevents() (/home/noshyaar/git/godot/0/platform/x11/os_x11.cpp:1857 (discriminator 3))
[27] OS_X11::run() (/home/noshyaar/git/godot/0/platform/x11/os_x11.cpp:2503)
[28] /home/noshyaar/git/godot/0/bin/godot.x11.tools.64(main+0xd5) [0xef261f] (/home/noshyaar/git/godot/0/platform/x11/godot_x11.cpp:56)
[29] /usr/lib/libc.so.6(__libc_start_main+0xea) [0x7f3305066f4a] (??:0)
[30] /home/noshyaar/git/godot/0/bin/godot.x11.tools.64(_start+0x2a) [0xef248a] (??:?)
-- END OF BACKTRACE --
```

**Steps to reproduce:**
Click any inspector entry that takes Resource.

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by Chaosus**
Closes #18058

### CODE REVIEW

File: editor/property_editor.cpp [hunk 1]
```diff
@@ -882,7 +882,13 @@ bool CustomPropertyEditor::edit(Object *p_owner, const String &p_name, Variant::
 			} else if (hint_text != "") {
 				int idx = 0;
 
-				const Vector<EditorData::CustomType> custom_resources = EditorNode::get_editor_data().get_custom_types()["Resource"];
+				Vector<EditorData::CustomType> custom_resources;
+
+				if (EditorNode::get_editor_data().get_custom_types().has("Resource"))
+				{
```
Comment (Noshyaar) [inline editor/property_editor.cpp]: Brace should be on the same line as `if`

Comment (Chaosus) [reply editor/property_editor.cpp]: @Noshyaar I fixed it, check now, its safe to merge

**Comment by vnen** [comment]
Late here, but I prefer you make descriptive commit messages. Referring to a issue is convenient only in the GitHub interface but not when you are reading `git log`.
