### PR TITLE
[Compatibility] Add stub for VisualShaderNodeComment

### LINKED ISSUE #90303: GDExtension: several methods in `OpenXRHand`, `SkeletonIK3D`, `VisualShaderNodeComment` unavailable
### Tested versions

- Reproducible in `4.3.dev.custom_build.655e93d58`

### System information

Both Windows 10 and WSL 2 (Ubuntu 20.04)

### Issue description

The following 8 methods are listed in `extension_api.json` as of recent `master`, however their function pointers can't be retrieved:
```py
OpenXRHand::set_hand_skeleton (hash 1348162250)
OpenXRHand::get_hand_skeleton (hash 4075236667)
SkeletonIK3D::set_interpolation (hash 373806689)
SkeletonIK3D::get_interpolation (hash 1740695150)
VisualShaderNodeComment::set_title (hash 83702148)
VisualShaderNodeComment::get_title (hash 201670096)
VisualShaderNodeComment::set_description (hash 83702148)
VisualShaderNodeComment::get_description (hash 201670096)
```

Are these classes marked experimental?

Even if that's the case, their availability in GDExtension should generally match the advertised values in `extension_api.json`.

For a similar issue in the past, see e.g. https://github.com/godotengine/godot/issues/86206.

### Steps to reproduce

Try to fetch any of the above class methods through GDExtension, you will get a null pointer.

### Minimal reproduction project (MRP)

N/A -- but recently failed [CI run](https://github.com/godot-rust/gdext/actions/runs/8580795134/job/23517208760#step:3:415).

### PR DESCRIPTION
**Pull request by Geometror**
Fixes part of #90303.

### CODE REVIEW

File: scene/resources/visual_shader.h [hunk 1]
```diff
@@ -767,6 +767,27 @@ class VisualShaderNodeFrame : public VisualShaderNodeResizableBase {
...
+// Deprecated, for compatibility only.
+class VisualShaderNodeComment : public VisualShaderNodeFrame {
+	GDCLASS(VisualShaderNodeComment, VisualShaderNodeFrame);
+
+	String description;
+
+protected:
+#ifndef DISABLE_DEPRECATED
+	static void _bind_compatibility_methods();
+	void set_description_compat_88014(const String &p_description);
```
Comment (AThousandShips) [inline scene/resources/visual_shader.h:779]:
```suggestion
	void _set_description_bind_compat_88014(const String &p_description);
```
For both

File: scene/resources/visual_shader.h [hunk 2]
```diff
@@ -767,6 +767,27 @@ class VisualShaderNodeFrame : public VisualShaderNodeResizableBase {
...
+	String get_description_compat_88014() const;
+#endif
+
+public:
+	virtual String get_caption() const override { return "Comment(Deprecated)"; };
```
Comment (AThousandShips) [inline scene/resources/visual_shader.h:784]:
```suggestion
	virtual String get_caption() const override { return "Comment(Deprecated)"; }
```

File: scene/resources/visual_shader.h [hunk 3]
```diff
@@ -767,6 +767,27 @@ class VisualShaderNodeFrame : public VisualShaderNodeResizableBase {
...
+
+	virtual Category get_category() const override { return CATEGORY_NONE; }
+
+	VisualShaderNodeComment(){};
```
Comment (AThousandShips) [inline scene/resources/visual_shader.h:788]:
```suggestion
	VisualShaderNodeComment() {}
```

File: scene/resources/visual_shader.cpp [hunk 4]
```diff
@@ -30,6 +30,8 @@
 
 #include "visual_shader.h"
```
Comment (AThousandShips) [inline scene/resources/visual_shader.cpp:32]:
```suggestion
```

**Review by AThousandShips — APPROVED** [review]
Looks good otherwise!

File: scene/resources/visual_shader.h (hunk 1 above)
Comment (Geometror) [reply scene/resources/visual_shader.h:777]: Oh sorry, I think you just mean the underscore.

Comment (AThousandShips) [reply scene/resources/visual_shader.h]: (it's also the style that'll be more concretely official if the docs get updated as currently proposed)

Comment (AThousandShips) [reply scene/resources/visual_shader.h]: Please do add the `bind` as well, it's preferred

File: scene/resources/visual_shader.cpp (hunk 4 above)
Comment (AThousandShips) [reply scene/resources/visual_shader.cpp:32]: And no space here

File: scene/resources/visual_shader.h (hunk 1 above)
Comment (Geometror) [reply scene/resources/visual_shader.h]: Alright, good to know, done :)

**Review by AThousandShips — APPROVED** [review]
Thank you for bearing with me

File: scene/resources/visual_shader.h [hunk 5]
```diff
@@ -767,6 +767,25 @@ class VisualShaderNodeFrame : public VisualShaderNodeResizableBase {
...
+	String _get_description_bind_compat_88014() const;
+#endif
+
+public:
+	virtual String get_caption() const override { return "Comment(Deprecated)"; }
+
+	virtual Category get_category() const override { return CATEGORY_NONE; }
+
+	VisualShaderNodeComment() {}
+};
```
Comment (akien-mga) [inline scene/resources/visual_shader.h:787]:
```suggestion
#ifndef DISABLE_DEPRECATED
// Deprecated, for compatibility only.
class VisualShaderNodeComment : public VisualShaderNodeFrame {
	GDCLASS(VisualShaderNodeComment, VisualShaderNodeFrame);

protected:
#ifndef DISABLE_DEPRECATED
	static void _bind_compatibility_methods();
	void _set_description_bind_compat_88014(const String &p_description);
	String _get_description_bind_compat_88014() const;
#endif

public:
	virtual String get_caption() const override { return "Comment(Deprecated)"; }

	virtual Category get_category() const override { return CATEGORY_NONE; }

	VisualShaderNodeComment() {}
};
#endif
```

File: scene/register_scene_types.cpp [hunk 6]
```diff
@@ -657,6 +657,7 @@ void register_scene_types() {
 	GDREGISTER_ABSTRACT_CLASS(VisualShaderNodeConstant);
 	GDREGISTER_ABSTRACT_CLASS(VisualShaderNodeVectorBase);
 	GDREGISTER_CLASS(VisualShaderNodeFrame);
+	GDREGISTER_CLASS(VisualShaderNodeComment); // Deprecated, just for compatibility.
```
Comment (akien-mga) [inline scene/register_scene_types.cpp:660]:
```suggestion
#ifndef DISABLE_DEPRECATED
	GDREGISTER_CLASS(VisualShaderNodeComment); // Deprecated, just for compatibility.
#endif
```

File: scene/resources/visual_shader.compat.inc [hunk 7]
```diff
@@ -0,0 +1,45 @@
...
+/**************************************************************************/
+
+#ifndef DISABLE_DEPRECATED
+
+void VisualShaderNodeComment::_set_description_bind_compat_88014(const String &p_description) {
+}
+
+String VisualShaderNodeComment::_get_description_bind_compat_88014() const {
+	return "";
+}
```
Comment (akien-mga) [inline scene/resources/visual_shader.compat.inc:38]: Instead of empty compatibility stubs, WDYT about actually re-exposing the `description` property, and make it save its value in `Object.set_meta`?

This would allow users to salvage that information instead of losing it when moving to 4.3.

**Comment by akien-mga** [comment]
This line should be removed from the `4.2.stable.expected` file:
```
Validate extension JSON: API was removed: classes/VisualShaderNodeComment
```

File: scene/resources/visual_shader.compat.inc (hunk 7 above)
Comment (Geometror) [reply scene/resources/visual_shader.compat.inc]: Good idea, done.

Comment (Geometror) [reply scene/resources/visual_shader.compat.inc]: Not sure whether it's correct to put ADD_PROPERTY in _bind_compatibility_methods() though.

File: scene/resources/visual_shader.compat.inc [hunk 8]
```diff
@@ -0,0 +1,48 @@
...
+String VisualShaderNodeComment::_get_description_bind_compat_88014() const {
+	return get_meta("description", "");
+}
+
+void VisualShaderNodeComment::_bind_compatibility_methods() {
+	ClassDB::bind_compatibility_method(D_METHOD("set_description", "description"), &VisualShaderNodeComment::_set_description_bind_compat_88014);
+	ClassDB::bind_compatibility_method(D_METHOD("get_description"), &VisualShaderNodeComment::_get_description_bind_compat_88014);
+
+	ADD_PROPERTY(PropertyInfo(Variant::STRING, "description"), "set_description", "get_description");
+}
```
Comment (akien-mga) [inline scene/resources/visual_shader.compat.inc:46]: Actually now that I think further about it:
- I think this can be "normal" method bindings in `_bind_methods` instead of compat bindings. The class itself is already deprecated/for compat so the methods themselves don't need to be too.
- If so, we can also re-add the `description` property fully, and document that it doesn't do anything in this new setup, but is used to preserve data authored in earlier Godot versions.

File: doc/classes/VisualShaderNodeComment.xml [hunk 9]
```diff
@@ -0,0 +1,10 @@
+<?xml version="1.0" encoding="UTF-8" ?>
+<class name="VisualShaderNodeComment" inherits="VisualShaderNodeFrame" deprecated="This class has no function anymore and only exists for compatibility." xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
+	<brief_description>
+		Only exists for compatibility. Behaves exactly like [VisualShaderNodeFrame].
+	</brief_description>
+	<description>
+	</description>
```
Comment (akien-mga) [inline doc/classes/VisualShaderNodeComment.xml:7]: We should figure out something to write here too just to keep the completion ratio high in https://godotengine.github.io/doc-status/ :)

File: scene/resources/visual_shader.compat.inc (hunk 8 above)
Comment (akien-mga) [reply scene/resources/visual_shader.compat.inc:46]: To be clear, this means also moving them to `visual_shader.cpp` (enclosed in `#ifndef DISABLE_DEPRECATED`) and the `.compat.inc` file can be removed.

Comment (Geometror) [reply scene/resources/visual_shader.compat.inc]: Alright, done :)

**Review by akien-mga — APPROVED** [review]
Perfect!

BTW, hello Geometror from the future :wave: 
```
Date: Wed, 17 Apr 2024 19:00:41 +0200
```

**Review by AThousandShips — APPROVED** [review]

File: scene/resources/visual_shader.cpp [hunk 10]
```diff
@@ -4323,6 +4323,23 @@ void VisualShaderNodeFrame::_bind_methods() {
 VisualShaderNodeFrame::VisualShaderNodeFrame() {
 }
 
+////////////// Comment (Deprecated)
+
+void VisualShaderNodeComment::_bind_methods() {
```
Comment (AThousandShips) [inline scene/resources/visual_shader.cpp:4328]:
```suggestion
#ifndef DISABLE_DEPRECATED
void VisualShaderNodeComment::_bind_methods() {
```
And after

Comment (Geometror) [reply scene/resources/visual_shader.cpp:4329]: Hhm, I thought I did this, looks like I'm a bit puzzled today :)

**Comment by akien-mga** [comment]
Seems like these still get raised despite the API being present in the parent class:
```
Validate extension JSON: API was removed: classes/VisualShaderNodeComment/methods/get_title
Validate extension JSON: API was removed: classes/VisualShaderNodeComment/methods/set_title
Validate extension JSON: API was removed: classes/VisualShaderNodeComment/properties/title
```

Not sure how we handled this in the past, I think it _might_ be fine to just ignore those in the `4.2.stable.expected` file?

**Comment by dsnopek** [comment]
> Not sure how we handled this in the past, I think it _might_ be fine to just ignore those in the `4.2-stable.expected` file?

Yes, to double confirm: if a method moves up to a base class, it's fine to ignore the message in the `.expected` file

**Comment by akien-mga** [comment]
Thanks!
