### PR TITLE
[4.0] Fix alpha scissor support

### LINKED ISSUE #58924: Alpha Scissor does not cast shadows with depth_draw_opaque, even though manually discarding does
### Godot version

3.4.3.stable

### System information

Windows 10, GLES3, GTX 980Ti

### Issue description

As far as I understand, using alpha scissor should just discard transparent pixels, which means it should be able to cast shadows using "depth_draw_opaque", but it doesn't.

image

Alpha Scissor:
```
shader_type spatial;
render_mode depth_draw_opaque, cull_disabled;
uniform vec4 albedo : hint_color;
uniform sampler2D texture_albedo : hint_albedo;
uniform float alpha_scissor_threshold;

void fragment() {
	vec4 albedo_tex = texture(texture_albedo, UV);
	ALBEDO = albedo.rgb * albedo_tex.rgb;
	ALPHA = albedo.a * albedo_tex.a;
	ALPHA_SCISSOR=alpha_scissor_threshold;
}
```

Manual Discard:
```
shader_type spatial;
render_mode depth_draw_opaque, cull_disabled;
uniform vec4 albedo : hint_color;
uniform sampler2D texture_albedo : hint_albedo;
uniform float alpha_scissor_threshold;

void fragment() {
	vec4 albedo_tex = texture(texture_albedo, UV);
	ALBEDO = albedo.rgb * albedo_tex.rgb;
	if (albedo.a * albedo_tex.a < alpha_scissor_threshold)
		discard;
}
```

It seems that as soon as "ALPHA" gets set in a shader, even if it's just set to "1.0" shadow casting is disabled in "depth_draw_opaque" mode.

EDIT: I'm guessing the shader compiler looks for the ALPHA keywords and puts everything that has it in the transparent render queue? But if both ALPHA and ALPHA SCISSOR is present and depth_draw_opaque is set, I don't think it should send it to the transparent render queue.

### Steps to reproduce

Try out the shaders listed above or open the attached project.

### Minimal reproduction project

[Alpha Scissor Tests.zip](https://github.com/godotengine/godot/files/8214388/Alpha.Scissor.Tests.zip)

### PR DESCRIPTION
**Pull request by Ansraer**
Fixes #58924 in master.

Apparently, the alpha scissor check was lost in the transition from gles3 to vulkan. In addition materials with alpha scissors were still using the default shadow material, which obviously resulted in wrong shadows.

### CODE REVIEW

**Review by clayjohn — COMMENTED** [review]
Does the mobile renderer need the same changes?

**Comment by Ansraer** [comment]
Right, there are two vulkan renderers in master... I keep forgetting the mobile one every single time.
Probably yes, give me 3 minutes.

File: servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp [hunk 1]
```diff
@@ -293,7 +295,7 @@ void SceneShaderForwardMobile::ShaderData::set_code(const String &p_code) {
 
 					if (k == SHADER_VERSION_COLOR_PASS || k == SHADER_VERSION_COLOR_PASS_MULTIVIEW || k == SHADER_VERSION_LIGHTMAP_COLOR_PASS || k == SHADER_VERSION_LIGHTMAP_COLOR_PASS_MULTIVIEW) {
 						blend_state = blend_state_blend;
-						if (depth_draw == DEPTH_DRAW_OPAQUE) {
+						if (depth_draw == DEPTH_DRAW_OPAQUE && uses_alpha_clip == false) {
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp:298]: Looks like we may need this in the clustered code too. Otherwise in the clustered renderer alpha scissor materials will have depth drawing forced disabled.

Comment (Ansraer) [reply servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp:298]: Comparing the code right now. Based on my current understanding my clustered fix should not work. Since it does I am obviously still missing something, and I really don't want to change something I don't understand.

Comment (Ansraer) [reply servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp:298]: Here is the relevant piece of code in the clustered renderer:

https://github.com/godotengine/godot/blob/5c7971d8560cacc7efa06fc35eb90080dcaea9a8/servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp#L307-L318

**Review by clayjohn — APPROVED** [review]
Looks good to me!

Thanks for your patience.

**Comment by akien-mga** [comment]
Thanks!
