### PR TITLE
Fix voxelizer normals

### LINKED ISSUE #102407: VoxelGI baking incorrectly when objects are rotated
### Tested versions

- Reproducible in: 4.1, 4.3, 4.4 beta1, 4.4 beta2 
- These are the only versions I tried

### System information

Windows 11 - RTX 4080 - Vulkan, MacOS - M4 - Vulkan

### Issue description

When baking a VoxelGI node, its results are completely off when an object within its bounds has any form of rotation. For example, consider a wall piece that is symetrical on both sides. The result of the voxel GI bake will be completely different if the wall has a 0 degree y-rotation or a 180 degree y-rotation. Objects that have a 90 degree or -90 degree rotation are even more problematic, since they cannot be rotated in any way to get a correct result:

Screenshots:
For all screenshots I set the Display mode in editor to VoxelGI Lighting.

Screenshot 1 - incorrect bake:  
Image
Notice the left wall is rotated 180 degrees along the y-axis.

Screenshot 2 - correct bake:
Image
Notice the left wall now has no rotation at all.

Screenshot 2 - incorrect bake:
Image
I now duplicated the back wall and rotated it 90 and -90 degrees for the left and right walls.

### Steps to reproduce

- Setup a scene with some modular pieces
- Add a light to the scene
- Add a VoxelGI node to the scene
- hit bake
- Now rotate 1 of you walls 180 degrees around the y-axis
- bake again and notice the different result

### Minimal reproduction project (MRP)

[VoxelGIBakingMRP.zip](https://github.com/user-attachments/files/18657147/VoxelGIBakingMRP.zip)

### PR DESCRIPTION
**Pull request by orange-anvil-games**
Fixes #102407 

This PR fixes VoxelGI baking for rotated meshes
| Before | After |
|-|-|
| Screenshot 2025-02-15 at 16 01 52 | Screenshot 2025-02-15 at 16 03 05 |

### CODE REVIEW

**Comment by akien-mga** [comment]
For the record, your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

(Indeed, if you check https://github.com/godotengine/godot/pull/102893.patch, your email is invalid and using the local host name as domain.)

**Comment by orange-anvil-games** [comment]
Thanks @akien-mga, I amended the commit with the correct author. Should be fine now.

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected.

**Comment by MrModez** [comment]
Is this going to be merged for 4.4?

**Comment by akien-mga** [comment]
> Is this going to be merged for 4.4?

No, we're in release freeze for 4.4, which means that we only merge fixes to critical regressions. This can be merged for 4.5 and possibly backported to 4.4.1.

File: scene/3d/voxelizer.cpp [hunk 1]
```diff
@@ -463,7 +463,7 @@ Voxelizer::BakeResult Voxelizer::plot_mesh(const Transform3D &p_xform, Ref<Mesh>
 
 				if (nr) {
 					for (int k = 0; k < 3; k++) {
-						normal[k] = nr[ir[j * 3 + k]];
+						normal[k] = p_xform.basis.inverse().transposed().xform(nr[ir[j * 3 + k]]).normalized();
```
Comment (clayjohn) [inline scene/3d/voxelizer.cpp:466]: This makes sense, but the xform should be precomputed outside of the loops (e.g. at the top of the function) so it isn't calculating the inverse-transpose of the basis for every vertex of every surface

**Review by clayjohn — CHANGES_REQUESTED** [review]

File: scene/3d/voxelizer.cpp (hunk 1 above)
Comment (orange-anvil-games) [reply scene/3d/voxelizer.cpp]: Great suggestion. Updated the PR to only compute the normal xform once per mesh

**Review by clayjohn — APPROVED** [review]

**Comment by clayjohn** [comment]
Looks great! The final step before merging is to squash all the commits together so that the whole PR only contains 1 big commit with all your changes. We like to merge one commit at a time to keep the git history clean and navigable. 

If you don't know how to do that, we have a helpful tutorial in the official documentation https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 4.4.1.

**Comment by MrModez** [comment]
4.4.1-rc1 didn't fix the issue for me, still getting broken voxelgi lighting
image
