### PR TITLE
Setting project metadata doesn't fail when project_metadata.cfg doesn't exist

### LINKED ISSUE #31444: New errors checks on ConfigFile::load() generate unnecessary error prints when file doesn't exist yet
**Godot version:**
3.2 master (86371b7), regression from #31077 (@qarmin)

**OS/device including version:**
Any

**Issue description:**
PR #31077 added missing return value checks for `ConfigFile::load()`, but missed the fact that this API can be used successfully even if `err != OK`, as it will return `ERR_CANT_OPEN` if the file can't be opened, which also occurs if the file doesn't exist.

Code that uses `ConfigFile` typically attempts to load files even if not present, so that they can be either edited or created and then re-saved. So in this case no error should be raised.

Current code raises errors all the time when you e.g. save a scene, as the project metadata for the scene doesn't exist yet. And the metadata is not created at all due to this early exit.

The `ConfigFile` API could maybe be changed to use a more specific error when the file can't be loaded because it doesn't exist, so that it can be treated as a harmless error (e.g. `ERR_FILE_NOT_FOUND`).

**Steps to reproduce:**
- Create a new project
- Create new scene, save it
- Check terminal

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
Implemented specific errors for file not found in windows/unix, used for loading project metadata file when setting a value. If the file doesn't exist it will create one instead of failing.

Fixes #31444

### CODE REVIEW

**Comment by akien-mga** [comment]
Changes look good. Check the PR referenced in #31444, there are a few other places where this code was changed and should be changed back / improved as you did it.

**Comment by pouleyKetchoupp** [comment]
I've made additional changes from PR #31077 but I didn't find any other case where it shouldn't fail on a missing file.

Here are all the uses of ConfigFile::Load I've found:
EditorSettings::set_project_metadata: creates project_metadata.cfg if it doesn't exist
EditorSettings::create: still fails (it checks if the file exists right before)
PluginConfigDialog::config: still fails (there's a proper error message earlier for missing plugin.cfg)
EditorPlugin::get_config: removed (not used)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

File: drivers/windows/file_access_windows.cpp [hunk 1]
```diff
@@ -114,11 +114,18 @@ Error FileAccessWindows::_open(const String &p_path, int p_mode_flags) {
...
 	}
 
-	_wfopen_s(&f, path.c_str(), mode_string);
+	errno_t errcode = _wfopen_s(&f, path.c_str(), mode_string);
 
 	if (f == NULL) {
-		last_error = ERR_FILE_CANT_OPEN;
-		return ERR_FILE_CANT_OPEN;
+		switch (errcode) {
+			case ENOENT: {
```
Comment (akien-mga) [inline drivers/windows/file_access_windows.cpp]: Looks like MinGW needs `#include <errno.h>` for this, I'll make a PR.

Comment (akien-mga) [reply drivers/windows/file_access_windows.cpp]: PR is #31528.
