### PR TITLE
Fix unable to disconnect signal in Editor once created

### LINKED ISSUE #69348: Cannot disconnect signal with context menu once created
### Godot version

4.0.dev (55dae301)

### System information

Linux (Ubuntu 22.04), Vulkan, Radeon RX Vega 64 (eGPU)

### Issue description

When creating signals successfully, the signal can be shown yellow. If the signal is yellow, it's impossible to disconnect it from the context menu.

Capture d’écran du 2022-11-29 12-04-54

It's still possible to disconnect the signal using the Disconnect button at the bottom.

### Steps to reproduce

1. Create a scene
2. Attatch a script to the scene
3. Click on the root node of that scene
4. Attach a signal

Sometimes, the signal is yellow. If it's yellow, it's not possible to disconnect it using the context menu.

### Minimal reproduction project

Unfortunately, this happens only when creating a new signal. But if needed, here's a kind of MRP:
[cannot_disconnect_signal.zip](https://github.com/godotengine/godot/files/10115408/cannot_disconnect_signal.zip)

From testing, when loading a project, the yellow signals will become white and will work as usual.

### PR DESCRIPTION
**Pull request by Mickeon**
Fixes https://github.com/godotengine/godot/issues/69348.

https://github.com/godotengine/godot/pull/66665's implementation was a bit too stupid and didn't account all cases. Most importantly, signals that had yet to be saved.

To solve this in the least chaotic, slow and intrusive way, I basically gave up. This PR adds a **CONNECT_INHERITED** flag to connections, only available in editor builds. This flag denotes that the signal has been inherited from a previous Scene in the instancing hierarchy. Signals deemed to be inherited cannot be edited or deleted in the editor.

### CODE REVIEW

File: editor/connections_dialog.cpp [hunk 1]
```diff
@@ -788,23 +788,31 @@ bool ConnectionsDock::_is_item_signal(TreeItem &p_item) {
...
-
-	Ref<SceneState> state = scn->get_state();
-	ERR_FAIL_NULL_V(state, false);
-
 	Node *source = Object::cast_to<Node>(p_connection.signal.get_object());
 	Node *target = Object::cast_to<Node>(p_connection.callable.get_object());
 
-	const NodePath source_path = scene_root->get_path_to(source);
-	const NodePath target_path = scene_root->get_path_to(target);
 	const StringName signal_name = p_connection.signal.get_name();
```
Comment (KoBeWi) [inline editor/connections_dialog.cpp:794]:
```suggestion
	const StringName &signal_name = p_connection.signal.get_name();
```
StringNames should use references to avoid copying. Same with NodePaths.

File: editor/connections_dialog.cpp [hunk 2]
```diff
@@ -788,23 +788,31 @@ bool ConnectionsDock::_is_item_signal(TreeItem &p_item) {
...
+	const NodePath source_path = source->get_scene_file_path().is_empty() ? source->get_owner()->get_path_to(source) : NodePath(".");
+	const NodePath target_path = target->get_scene_file_path().is_empty() ? target->get_owner()->get_path_to(target) : NodePath(".");
+
+	Ref<PackedScene> scn = ResourceLoader::load(file_path);
+	ERR_FAIL_NULL_V(scn, false);
+
+	Ref<SceneState> state = scn->get_state();
+	ERR_FAIL_NULL_V(state, false);
+
+	bool exists_in_packed_scene_directly = state->has_connection(source_path, signal_name, target_path, method_name, true);
```
[the remark this answers is not in the document]
Comment (Mickeon) [reply editor/connections_dialog.cpp:808]: I believe it'd make the code more readable without resorting to comments. This feels still pretty hack-ish to do

[the remark this answers is not in the document]
Comment (Mickeon) [reply editor/connections_dialog.cpp:808]: It's more like, it'll likely be compiled out of the equation in your typical C++ compiler because it's just a never changing boolean. I can still remove it if it's way too beyond the general coding style.

**Review by KoBeWi — APPROVED** [review]

File: core/object/object.h [hunk 3]
```diff
@@ -556,6 +556,9 @@ class Object {
 		CONNECT_PERSIST = 2, // hint for scene to save this connection
 		CONNECT_ONE_SHOT = 4,
 		CONNECT_REFERENCE_COUNTED = 8,
+#ifdef TOOLS_ENABLED
```
Comment (reduz) [inline core/object/object.h:559]: Guess no need for tools enabled since nothing really significant is added.

Comment (Mickeon) [reply core/object/object.h:559]: Just wanted to make sure it didn't exist in release builds, although a good compiler would probably get rid of it, I'm sure...

File: scene/resources/packed_scene.cpp [hunk 4]
```diff
@@ -450,7 +450,11 @@ Node *SceneState::instantiate(GenEditState p_edit_state) const {
 			callable = callable.bindp(argptrs, binds.size());
 		}
 
+#ifdef TOOLS_ENABLED
+		cfrom->connect(snames[c.signal], callable, CONNECT_PERSIST | c.flags | (p_edit_state == GEN_EDIT_STATE_MAIN ? 0 : CONNECT_INHERITED));
```
Comment (akien-mga) [inline scene/resources/packed_scene.cpp:454]: Couldn't this possibly be useful at runtime too?

File: scene/resources/packed_scene.cpp [hunk 5]
```diff
@@ -450,7 +450,11 @@ Node *SceneState::instantiate(GenEditState p_edit_state) const {
 			callable = callable.bindp(argptrs, binds.size());
 		}
 
+#ifdef TOOLS_ENABLED
```
Comment (reduz) [inline scene/resources/packed_scene.cpp:453]: Would remove this ifdef too, probably not worth it

Comment (Mickeon) [reply scene/resources/packed_scene.cpp:453]: I don't know... CONNECT_PERSIST can technically also be used in release builds when building PackedScenes at run-time

**Review by akien-mga — APPROVED** [review]
There might be a case for actually exposing the new enum value to be consistent, since users may want to use it in editor plugins?

Otherwise seems good to me.

**Comment by akien-mga** [comment]
Thanks!

**Comment by KoBeWi** [comment]
Seems like discarding instancing (using the Make Local option) doesn't remove the flag and the connections cannot be disconnected at all.
