### PR TITLE
Fix export preset not duplicating selected files

### LINKED ISSUE #114150: Duplicating export preset doesn't duplicate `Resources to exclude`
### Tested versions

4.5.1

### System information

Godot v4.5.1.stable - macOS Tahoe (26.1.0) - Multi-window, 2 monitors - Metal (Mobile) - integrated Apple M3 Max (Apple9) - Apple M3 Max (14 threads) - 36.00 GiB memory

### Issue description

Duplicating an export preset doesn't also duplicate the resource exclusion list with it:

https://github.com/user-attachments/assets/7bfa667b-c2ea-45a2-8445-1ca830abe341

### Steps to reproduce

1. Make an export preset and add a few files to the resource exclusion list
2. Duplicate the export preset and notice that the resource exclusion list of the duplicate is empty.

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by DallasHuff**
Previously, export presets did not duplicate selected files for excluding / including specific files in the export. This commit fixes it by duplicating the selected files.

Closes https://github.com/godotengine/godot/issues/114150

https://github.com/user-attachments/assets/c2eeed9e-acb5-4bac-aa53-ee6d70ea3129

### CODE REVIEW

File: editor/export/editor_export_preset.h [hunk 1]
```diff
@@ -123,6 +123,8 @@ class EditorExportPreset : public RefCounted {
 	void update_value_overrides();
 
 	Vector<String> get_files_to_export() const;
+	HashSet<String> get_selected_files() const;
+	void set_selected_files(const HashSet<String> p_files);
```
Comment (AThousandShips) [inline editor/export/editor_export_preset.h]:
```suggestion
	void set_selected_files(const HashSet<String> &p_files);
```

**Review by KoBeWi — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]
Looks good!
