### PR TITLE
Fix Cursor Color in the Label/RichTextLabel

### LINKED ISSUE #26246: The cursor in the Label/RichTextLabel text editors is hard to see and doesn't blink
Godot 3.1 beta6

The default settings for `TextEdit` cursors in the editor is hard to see and doesn't blink, which makes it harder to use.

Both in the inspector:
image

And the popup:
image

Note: that's also generally the case for `TextEdit` nodes which are added by custom editor plugins.

### PR DESCRIPTION
**Pull request by mariambukenya**
I was able to change the cursor color of the text edit from cursor_color (which displayed a caret with a dull color that was hard to see) to mono_color (which displayed a white caret in the dark theme of godot and black caret in the light theme of godot), making it easier to be seen.

*Bugsquad edit: This closes #26246.*

### CODE REVIEW

File: editor/editor_themes.cpp [hunk 1]
```diff
@@ -829,7 +829,7 @@ Ref<Theme> create_editor_theme(const Ref<Theme> p_theme) {
 	theme->set_constant("side_margin", "TabContainer", 0);
 	theme->set_icon("tab", "TextEdit", theme->get_icon("GuiTab", "EditorIcons"));
 	theme->set_color("font_color", "TextEdit", font_color);
-	theme->set_color("caret_color", "TextEdit", highlight_color);
+	theme->set_color("caret_color", "TextEdit", mono_color);
```
Comment (Calinou) [inline editor/editor_themes.cpp]: It'd make more sense to use `font_color` for consistency, as it's the color used by the cursor in LineEdit:

```suggestion
	theme->set_color("caret_color", "TextEdit", font_color);
```

**Review by Calinou — CHANGES_REQUESTED** [review]

**Review by Calinou — APPROVED** [review]

**Comment by akien-mga** [comment]
Could you squash commits together?

**Comment by akien-mga** [comment]
Pushed an edit to squash commits and improve commit log.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by hpvb** [comment]
Cherry-picked for 3.1.1.
