### PR TITLE
Recurse into resources to check for changed node paths

### LINKED ISSUE #74155: Nested Resource doesn't update NodePath when node renamed or moved
### Godot version

4.0 STABLE :tada:

### System information

win 11

### Issue description

When I have a SkeletonModificationStack2D with a modification in the modification stack such as SkeletonModification2DFABRIK and I assign a NodePath such as "Target Node" and then I change the node's name or its position (changing the NodePath) the SkeletonModification2DFABRIK "Target Node" property is not updated.

### Steps to reproduce

Make SMS2D
Make SM2DF
Assign Target Node
Change Target Node NodePath

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by tom95**
Fixes #74155 by recursing into resources when checking for changed `NodePath`s. Also verified to work with custom resources.

The added code follows the same pattern as [the code that handles `Node` subclasses](https://github.com/godotengine/godot/blob/0511f9d9a7d56c742d87fafdcea8785d40ad14b3/editor/scene_tree_dock.cpp#L1716). For `Node` subclasses, however, the existing code does some extra work we don't need for resources, such as recursing into the Node's children and scanning for related AnimationPlayers.

### CODE REVIEW

File: editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -1682,6 +1682,30 @@ bool SceneTreeDock::_check_node_path_recursive(Node *p_root_node, Variant &r_var
 			}
 		} break;
 
+		case Variant::OBJECT: {
+			Resource *resource = Object::cast_to<Resource>(r_variant);
+			if (resource) {
```
Comment (KoBeWi) [inline editor/scene_tree_dock.cpp:1687]: You could use early break instead:
```suggestion
			if (!resource) {
				break;
			}
```

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by tom95** [comment]
Thanks for the note @akien-mga, I had forgotten. All done now :)

**Comment by akien-mga** [comment]
Thanks!
