### PR TITLE
Update libwebsockets to 3.1, fix IPv6 issues

### LINKED ISSUE #26517: WebSocketClient failed to connect to any server other than localhost on Windows
**Godot version:**
Godot 3.1 beta 10 official build
Godot 3.1 beta 9 official build
Godot 3.1 beta 8 official build
Godot 3.1 beta 7 official build

**OS/device including version:**
Windows 10 Pro 64 Bit

**Issue description:**
I ran the websocket demo found on https://github.com/LudiDorici/godot-websocket/tree/master/websocket_chat_demo. The websocket server and client provided by the demo ran just fine. But if I replace the hostname in the url from `localhost` to `127.0.0.1`; or connect to my local server; or `ws://echo.websocket.org/` the demo would no longer work.

I have tested the same project on old versions of beta build and found out that this issue only occurs on godot 3.1 beta 7 and onwards. I think this might be related to the #26189 because I noticed that ipv6 is enabled after beta 7.

**Steps to reproduce:**
1. Download and run the websocket demo from https://github.com/LudiDorici/godot-websocket/tree/master/websocket_chat_demo
2. Type the url `ws://echo.websocket.org/` onto the textbox on the top right hand corner
3. Uncheck `Multiplayer API`
3. Press connect
4. The client would not connect and just hangs

### PR DESCRIPTION
**Pull request by Faless**
Huge diff, basically just a library update with some extras:

- Add fix to libwebsocket to disable V6ONLY on IPv6 sockets (was causing issues on Windows, fixes #26517 )
- Disable WebSocket IPv6 support on OpenBSD (dual stacking doesn't work there, forcing IPv4 only).
  NOTE: hopefully, in `3.2` I'll be able to migrate to `wslay` and use our `NetSocket` interface supporting both IPv4 and IPv6 on OpenBSD too (still without dual-stacking ofc).

### CODE REVIEW

File: modules/websocket/lws_client.cpp [hunk 1]
```diff
@@ -34,7 +34,10 @@
 #include "core/io/ip.h"
 #include "core/io/stream_peer_ssl.h"
 #include "core/project_settings.h"
-#include "tls/mbedtls/wrapper/include/openssl/ssl.h"
+#if defined(LWS_OPENSSL_SUPPORT)
+// Not openssl, just the mbedtls wrapper
+#include "openssl/ssl.h"
```
Comment (akien-mga) [inline modules/websocket/lws_client.cpp]: Isn't that a bit risky given that many users will have `/usr/include/openssl/ssl.h` in their system which could take precedence here?

**Comment by akien-mga** [comment]
After this change, do we still support distros building against their system-packaged libwebsockets?

File: modules/websocket/lws_client.cpp (hunk 1 above)
Comment (Faless) [reply modules/websocket/lws_client.cpp]: Yes, it is, which is why I hate this library, it's simply ill-conceived in so many aspects.
The issue has been there for a while, I worked it around using `Prepend` instead of `Append` in 659c62ee338975eddf1f7e65f68190af65199324 / #17115

**Comment by Faless** [comment]
> After this change, do we still support distros building against their system-packaged libwebsockets?

We should, but I haven't actually tested it. Linux distros usually have V6ONLY OFF by default, and, when that isn't the case, I assume whoever packages the lib will notice that it's impossible to connect to anything IPv4 because it doesn't call the right `setsockopt`.
I mean, the library can be compiled with IPv6 OR IPv4, not both so there isn't much we can do there :-1: .
I'll try to compile with distro `libwebsockets` and see, but again, YMMV based on distro/network settings/package maintainer.

**Comment by akien-mga** [comment]
Thanks!
