### PR TITLE
Fix preview CSG interfering with itself during drag and drop

### LINKED ISSUE #112848: CSG interferes with drop raycast by detecting itself
### Tested versions

Godot v4.6.dev4

### System information

Windows 11 (build 26200) - Multi-window, 1 monitor - Vulkan (Forward+) - integrated Intel(R) Iris(R) Xe Graphics (Intel Corporation; 32.0.101.7076) - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 threads) - 15.80 GiB memory

### Issue description

I’m using several prefabricated CSG wall and floor scenes for level blockout. When collision is enabled on these CSG nodes, it becomes almost impossible to place them precisely in the editor using drag-and-drop

https://github.com/user-attachments/assets/b91f4623-cffb-4170-841e-e18833428f41

After some debugging, I found that the drag placement raycast hits the CSG node being dragged, causing the preview to snap to its own surface instead of the environment.

The relevant line is here:
https://github.com/godotengine/godot/blob/ef34c3d534a16b140aef0643ed2fa36f8e9d1612/editor/scene/3d/node_3d_editor_plugin.cpp#L4873

`StaticBody3D` is ignored by `intersect_ray`, but CSG nodes are not, so they block the ray

### Steps to reproduce

- Create a new scene
- Add a `CSGBox3D` and enable collisions
- Save the scene
- Drag and drop this scene into another scene in the editor
- Attempt to position it using the mouse - the object snaps to its own collision instead of the target surface

### Minimal reproduction project (MRP)

[csg-drag-and-drop-bug.zip](https://github.com/user-attachments/files/23568513/csg-drag-and-drop-bug.zip)

### PR DESCRIPTION
**Pull request by ryevdokimov**
Fixes: https://github.com/godotengine/godot/issues/112848

https://github.com/user-attachments/assets/632a3626-568a-4736-8860-a8c86274e73e

### CODE REVIEW

File: editor/scene/3d/node_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -4852,7 +4852,9 @@ Vector3 Node3DEditorViewport::_get_instance_position(const Point2 &p_pos, Node3D
 
 	HashSet<RID> rids;
 
-	if (!preview_node->is_inside_tree() && !ruler->is_inside_tree()) {
+	if (preview_node && preview_node->get_child_count() > 0) {
+		_insert_rid_recursive(preview_node, rids);
+	} else if (!preview_node->is_inside_tree() && !ruler->is_inside_tree()) {
```
Comment (kleonc) [inline editor/scene/3d/node_3d_editor_plugin.cpp:4857]: In this block there's an unused array, please remove it:
https://github.com/godotengine/godot/blob/ef34c3d534a16b140aef0643ed2fa36f8e9d1612/editor/scene/3d/node_3d_editor_plugin.cpp#L4860

**Review by kleonc — APPROVED** [review]
Fixes the issue.

**Review by fire — APPROVED** [review]

**Comment by Oblepikha** [comment]
Fix works great. Tested on complex CSG with unions and subtractions - no issues found

**Comment by Repiteo** [comment]
Thanks!
