### PR TITLE
Request immediate refresh of cursor in 2D editor while using shortcuts

### LINKED ISSUE #37333: Cursor shape doesn't change immediately when changing tool via shortcut
**Godot version:**
3.2.1

**Steps to reproduce:**
1. Go to 2D editor
2. Move cursor over viewport
3. Press W or any other shortcut to change tool
4. Cursor stays the same until you move it

### PR DESCRIPTION
**Pull request by dreamsComeTrue**
The only place across whole editor, where cursor is updated is in viewport.cpp (line 2288), but it happens only when MouseMotion event is fired.

Issue describes problem, when someone presses the shortcut key to switch between tools - in that case no MouseMotion is performed. 
That's why I've used direct call to DisplayServer to update that cursor immediately. 

cursor-change

Fixes: #37333

### CODE REVIEW

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -4380,7 +4384,13 @@ void CanvasItemEditor::_button_tool_select(int p_index) {
 	}
 
 	tool = (Tool)p_index;
+
 	viewport->update();
+	_update_cursor();
+
+	// Request immediate refresh of cursor when using hot-keys to switch between tools
+	DisplayServer::CursorShape ds_cursor_shape = (DisplayServer::CursorShape)viewport->get_default_cursor_shape();
```
Comment (groud) [inline editor/plugins/canvas_item_editor_plugin.cpp:4392]: Shouldn't this be done inside the update_cursor function ?

**Comment by Calinou** [comment]
Could this fix #30582? I'm not sure if that issue still applies in the current `master` branch though.

File: editor/plugins/canvas_item_editor_plugin.cpp (hunk 1 above)
Comment (dreamsComeTrue) [reply editor/plugins/canvas_item_editor_plugin.cpp:4392]: I didn't want to alter the way how ```_gui_input_viewport``` works - so ```_update_cursor``` it's only simple extraction of cursor selection, and immediate request for refresh is only called in ```_button_tool_select``` then.

Comment (groud) [reply editor/plugins/canvas_item_editor_plugin.cpp:4392]: OK, I guess it makes sense.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
@dreamsComeTrue Would you want to make a backport PR for `3.2`? The cherry-pick isn't trivial due to the DisplayServer and Viewport changes in `master`.
