### PR TITLE
[Unix] Replace symlink target, not the link itself when using backup save mode.

### LINKED ISSUE #109364: Godot replaces symlink with actual file on Fedora
### Tested versions

Reproducible in: v4.5.beta.custom_build [c2202d36c10661873fb729bcf9c4c00b99e10c7a], v4.4.1.stable.official [49a5bc7b6]

### System information

Fedora Linux 42 (KDE Plasma 6.4.3 / Wayland)

### Issue description

Godot replaces symlinks with actual files when saving, removing any connection to the original file.

### Steps to reproduce

* Create a resource
* Move it to another directory
* Create a symlink in the original location
* Save resource in Godot

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/109364

### CODE REVIEW

File: drivers/unix/file_access_unix.cpp [hunk 1]
```diff
@@ -117,7 +117,29 @@ Error FileAccessUnix::open_internal(const String &p_path, int p_mode_flags) {
...
+		String link;
+		bool is_link = false;
+		{
+			CharString cs = path.utf8();
+			struct stat lst = {};
+			if ((lstat(cs.get_data(), &lst) == 0)) {
+				is_link = S_ISLNK(lst.st_mode);
+			}
+			if (is_link) {
+				char buf[256];
```
Comment (rburing) [inline drivers/unix/file_access_unix.cpp]: Why 256? Compare https://man7.org/linux/man-pages/man2/readlink.2.html#EXAMPLES

Comment (bruvzg) [reply drivers/unix/file_access_unix.cpp]: Same as all other uses of `readlink`, but I guess `PATH_MAX` make more sense.

**Review by rburing — APPROVED** [review]

File: drivers/unix/file_access_unix.cpp [hunk 2]
```diff
@@ -117,7 +117,29 @@ Error FileAccessUnix::open_internal(const String &p_path, int p_mode_flags) {
...
 
 	if (is_backup_save_enabled() && (p_mode_flags == WRITE)) {
-		save_path = path;
+		// Set save path to the symlink target, not the link itself.
+		String link;
+		bool is_link = false;
+		{
+			CharString cs = path.utf8();
+			struct stat lst = {};
+			if ((lstat(cs.get_data(), &lst) == 0)) {
```
Comment (AThousandShips) [inline drivers/unix/file_access_unix.cpp]:
```suggestion
			if (lstat(cs.get_data(), &lst) == 0) {
```

**Review by AThousandShips — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
