### PR TITLE
Prevent `LineEdit` focus loss when text is submitted or rejected and allow selecting without editing with arrow keys.

### LINKED ISSUE #87673: LineEdit and SpinBox focus issue
### Tested versions

4.2.1

### System information

win 10

### Issue description

1 - when it's focused with keyboard, it immediately switch to edit mode instead of just selecting the line edit, so the only way to select the next focusable `CanvasItem` is by pressing Tab.
2 - if the `LineEdit` is focused and escape button is pressed, the focus is lost! and it's impossible to focus any `CanvasItem` again with the keyboard until we focus one of them with mouse click . [ Editor and Game ]

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by WhalesState**
Fixes: https://github.com/godotengine/godot/issues/87673

- Prevent focus loss when text is rejected by pressing `Escape`.
- [Editor] Prevent focus loss when a text property is submitted by pressing `Enter`.
- Allow exiting edit mode by pressing `Escape` to select other focusable `Control` nodes.
- Allow entering focus mode only without editing by entering focus with arrow keys, pressing `Enter` will toggle between select/edit modes and pressing `Escape` while editing will return back to select mode.

### CODE REVIEW

**Comment by WhalesState** [comment]
maybe we will need to add `grab_focus_edit()` to focus the `LineEdit` in edit mode directly.

**Comment by AThousandShips** [comment]
You keep wiping your branch and closing the PR, I'd suggest making your changes and check the branch locally before pushing and causing such noise in the history 🙂

File: editor/animation_track_editor.cpp [hunk 1]
```diff
@@ -2942,8 +2942,7 @@ void AnimationTrackEdit::gui_input(const Ref<InputEvent> &p_event) {
 		path_popup->set_position(get_screen_position() + path_rect.position - theme_ofs);
 		path_popup->set_size(path_rect.size);
 		path_popup->popup();
-		path->grab_focus();
-		path->set_caret_column(path->get_text().length());
+		path->grab_focus_edit();
```
Comment (WhalesState) [inline editor/animation_track_editor.cpp:2945]: I forgot to add this line, and I don't want to make more noise! 😄
`path->set_caret_column(path->get_text().length());`

File: editor/gui/editor_file_dialog.cpp [hunk 2]
```diff
@@ -64,8 +64,9 @@ void EditorFileDialog::popup_file_dialog() {
 void EditorFileDialog::_focus_file_text() {
 	int lp = file->get_text().rfind(".");
 	if (lp != -1) {
+		file->grab_focus_edit();
 		file->select(0, lp);
-		file->grab_focus();
+		file->set_caret_column(lp);
```
Comment (WhalesState) [inline editor/gui/editor_file_dialog.cpp:69]: need to keep the caret at the start of the `LineEdit` too, because pressing left button to move the caret will move it to the start of the selection and will remove the selection.

File: scene/gui/file_dialog.cpp [hunk 3]
```diff
@@ -52,10 +52,11 @@ void FileDialog::popup_file_dialog() {
 void FileDialog::_focus_file_text() {
 	int lp = file->get_text().rfind(".");
 	if (lp != -1) {
-		file->select(0, lp);
 		if (file->is_inside_tree() && !get_tree()->is_node_being_edited(file)) {
-			file->grab_focus();
+			file->grab_focus_edit();
 		}
+		file->select(0, lp);
+		file->set_caret_column(lp);
```
Comment (WhalesState) [inline scene/gui/file_dialog.cpp:59]: need to remove this line too.

File: editor/project_manager.cpp [hunk 4]
```diff
@@ -843,7 +843,7 @@ void ProjectManager::shortcut_input(const Ref<InputEvent> &p_ev) {
 			} break;
 			case Key::F: {
 				if (k->is_command_or_control_pressed()) {
-					search_box->grab_focus();
+					this->search_box->grab_focus_edit();
```
Comment (KoBeWi) [inline editor/project_manager.cpp:846]: What's the `this` for?

File: doc/classes/LineEdit.xml [hunk 5]
```diff
@@ -126,6 +126,14 @@
 				Returns the selection end column.
 			</description>
 		</method>
+		<method name="grab_focus_edit">
+			<return type="void" />
+			<param index="0" name="select_all" type="bool" default="false" />
+			<description>
+				Focus the [LineEdit] in edit mode.
+				If [param select_all] is [code]true[/code], it will select all [member text] and move the caret to it's length.
```
Comment (KoBeWi) [inline doc/classes/LineEdit.xml:134]:
```suggestion
				If [param select_all] is [code]true[/code], it will select all [member text] and move the caret to its length.
```

File: doc/classes/LineEdit.xml [hunk 6]
```diff
@@ -180,6 +194,13 @@
 				Selects the whole [String].
 			</description>
 		</method>
+		<method name="set_focus_edit">
+			<return type="void" />
+			<param index="0" name="focus_edit" type="bool" />
+			<description>
+				Toggles focus edit mode, if [member editable] is [code]false[/code] it will just focus the [LineEdit].
```
Comment (KoBeWi) [inline doc/classes/LineEdit.xml:201]: This description sounds misleading. It should more clearly say that it affects behavior of `grab_focus()`.

File: editor/find_in_files.cpp [hunk 7]
```diff
@@ -465,8 +465,7 @@ void FindInFilesDialog::_notification(int p_what) {
 		case NOTIFICATION_VISIBILITY_CHANGED: {
 			if (is_visible()) {
 				// Doesn't work more than once if not deferred...
-				callable_mp((Control *)_search_text_line_edit, &Control::grab_focus).call_deferred();
-				_search_text_line_edit->select_all();
+				callable_mp(_search_text_line_edit, &LineEdit::grab_focus_edit).bind(true).call_deferred();
```
Comment (KoBeWi) [inline editor/find_in_files.cpp:468]:
```suggestion
				callable_mp(_search_text_line_edit, &LineEdit::grab_focus_edit).call_deferred(true);
```

File: editor/gui/editor_spin_slider.cpp [hunk 8]
```diff
@@ -640,8 +640,7 @@ void EditorSpinSlider::_focus_entered() {
 	value_input->set_focus_next(find_next_valid_focus()->get_path());
 	value_input->set_focus_previous(find_prev_valid_focus()->get_path());
 	callable_mp((CanvasItem *)value_input_popup, &CanvasItem::show).call_deferred();
-	callable_mp((Control *)value_input, &Control::grab_focus).call_deferred();
-	callable_mp(value_input, &LineEdit ::select_all).call_deferred();
+	callable_mp(value_input, &LineEdit::grab_focus_edit).bind(true).call_deferred();
```
Comment (KoBeWi) [inline editor/gui/editor_spin_slider.cpp:643]:
```suggestion
	callable_mp(value_input, &LineEdit::grab_focus_edit).call_deferred(true);
```

File: editor/create_dialog.cpp [hunk 9]
```diff
@@ -474,8 +474,7 @@ void CreateDialog::_notification(int p_what) {
 
 		case NOTIFICATION_VISIBILITY_CHANGED: {
 			if (is_visible()) {
-				callable_mp((Control *)search_box, &Control::grab_focus).call_deferred(); // Still not visible.
-				search_box->select_all();
+				callable_mp(search_box, &LineEdit::grab_focus_edit).bind(true).call_deferred(); // Still not visible.
```
Comment (KoBeWi) [inline editor/create_dialog.cpp:477]:
```suggestion
				callable_mp(search_box, &LineEdit::grab_focus_edit).call_deferred(true); // Still not visible.
```

File: editor/plugins/visual_shader_editor_plugin.cpp [hunk 10]
```diff
@@ -4251,8 +4251,7 @@ void VisualShaderEditor::_show_members_dialog(bool at_mouse_pos, VisualShaderNod
 	Vector2 difference = (dialog_rect.get_end() - window_rect.get_end()).max(Vector2());
 	members_dialog->set_position(members_dialog->get_position() - difference);
 
-	callable_mp((Control *)node_filter, &Control::grab_focus).call_deferred(); // Still not visible.
-	node_filter->select_all();
+	callable_mp(node_filter, &LineEdit::grab_focus_edit).bind(true).call_deferred(); // Still not visible.
```
Comment (KoBeWi) [inline editor/plugins/visual_shader_editor_plugin.cpp:4254]:
```suggestion
	callable_mp(node_filter, &LineEdit::grab_focus_edit).call_deferred(true); // Still not visible.
```

File: scene/gui/line_edit.cpp [hunk 11]
```diff
@@ -45,6 +45,84 @@
...
+	if (focus_edit == p_focus_edit) {
+		return;
+	}
+
+	if (p_focus_edit && !editable) {
+		return;
+	}
+
+	focus_edit = p_focus_edit;
+	emit_signal(SNAME("focus_edit_toggled"), focus_edit);
```
Comment (KoBeWi) [inline scene/gui/line_edit.cpp:78]: This signal is emitted when calling the method, which is something we usually try to avoid. I think it can be handled by connecting to `focus_entered` and checking whether the node is being edited.
Though if it simplifies things, maybe it's justified in this case.

File: scene/gui/line_edit.cpp [hunk 12]
```diff
@@ -45,6 +45,84 @@
...
 
+void LineEdit::grab_focus_edit(bool p_select_all) {
+	if (!is_inside_tree()) {
+		return;
+	}
+	set_focus_edit(true);
+
+	if (p_select_all) {
+		select_all();
+		set_caret_column(text.length());
```
Comment (KoBeWi) [inline scene/gui/line_edit.cpp:56]: Doesn't `select_all()` already set the caret?

File: scene/gui/line_edit.cpp [hunk 13]
```diff
@@ -244,6 +327,23 @@ void LineEdit::gui_input(const Ref<InputEvent> &p_event) {
 
 	Ref<InputEventMouseButton> b = p_event;
 
+	if (!focus_edit) {
+		Ref<InputEventKey> k = p_event;
```
Comment (KoBeWi) [inline scene/gui/line_edit.cpp:331]: This should be after the `return` block.

**Comment by KoBeWi** [comment]
The SpinBox changes brought back #78079.

File: editor/project_manager.cpp (hunk 4 above)
Comment (WhalesState) [reply editor/project_manager.cpp:846]: Maybe it was added by mistake, because i have copied the changes while working on 4.2.1 stable branch.

File: doc/classes/LineEdit.xml (hunk 6 above)
Comment (WhalesState) [reply doc/classes/LineEdit.xml:201]: `grab_focus_edit()` is an alias for 
```cpp
LineEdit::grab_focus();
LineEdit::set_focus_edit(true);
LineEdit::select_all(); // optionally.
```
This is similar to the old behavior of `grab_focus()`, and yes `set_focus_edit(true)` is the same as `grab_focus_edit(false)` so maybe we can only expose grab_focus_edit() because it's more easier to notice when we type `grab_focus`. and maybe we can add release_focus_edit() to set `focus_edit` to false.

File: scene/gui/line_edit.cpp (hunk 12 above)
Comment (WhalesState) [reply scene/gui/line_edit.cpp:56]: i think it sets the caret to the start of the selection by default, since pressing the right arrow will move the caret to the end of the selection and remove the selection, and I got used to the old behavior so it may be confusing to change it.

File: doc/classes/LineEdit.xml (hunk 6 above)
Comment (KoBeWi) [reply doc/classes/LineEdit.xml:201]: Yeah that sounds like what I suggested below, but with different names.

**Comment by KoBeWi** [comment]
```
C:\godot_source\core/object/message_queue.cpp:223 - Error calling deferred method: 'LineEdit::LineEdit::edit': Method expected 1 arguments, but called with 0.
```
Since `edit()` takes an argument now, every `call_deferred()` needs to be fixed, because `callable_mp()` does not support default arguments.

File: scene/gui/spin_box.h [hunk 14]
```diff
@@ -65,8 +65,7 @@ class SpinBox : public Range {
 		double diff_y = 0.0;
 	} drag;
 
-	void _line_edit_focus_enter();
-	void _line_edit_focus_exit();
+	void _line_edit_editing_toggled(bool toggled_on);
```
Comment (KoBeWi) [inline scene/gui/spin_box.h:68]:
```suggestion
	void _line_edit_editing_toggled(bool p_toggled_on);
```

**Comment by WhalesState** [comment]
> Which made me realize that this breaks compatibility. I ignored it before, because you can just press Enter and still edit the LineEdit, but I think users who used `grab_edit()` to edit their controls will now be confused and might not realize that they need to press Enter. Not sure if it's worth handing, it would require a property to make the new behavior optional. Though defaulting to the old behavior would make the new one less discoverable, so idk.

We can optionally return back the old behavior, but the main issue was the focus loss when pressing `escape`, also we can allow force editing when focused but this is also useless since the new changes will force editing when focused with `tab` or `shift + tab` by default but not the arrow keys. The best solution is to note the new changes in docs, using `edit()` will also grab focus if it's unfocused or not editable, all they need to do is to change `grab_focus()` with `edit()` so we can also not this in the `grab_focus()` and `release_focus()` discriptions.

**Comment by WhalesState** [comment]
may we can enter edit mode directly for the first time when it's not focused with keyboard, and we exit back to focus mode when the escape key is pressed to avoid focus loss and be able to select another GUI with keyboard.

**Comment by KoBeWi** [comment]
Makes sense I think. You can still use Tab to change focus in edit mode.

**Comment by KoBeWi** [comment]
@WhalesState Looks like you erased your changes by mistake (I assume).

**Comment by WhalesState** [comment]
There was an issue while undoing the commit, it was reverting the branch publishing instead of the last commit.

Now with this changes, LineEdit will enter focus mode only when it's focused with arrow keys, using `grab_focus()` this will only prevent focus loss, and will alow users to exist edit mode by pressing `Enter` or `Escape` to submit or reject the text.

**Comment by WhalesState** [comment]
@KoBeWi, Please let me know if any changes are required.


https://github.com/user-attachments/assets/79e8ae51-db91-476b-ac52-7c8ebb29f612

File: doc/classes/LineEdit.xml [hunk 15]
```diff
@@ -301,6 +307,12 @@
 		</member>
 	</members>
 	<signals>
+		<signal name="editing_toggled">
+			<param index="0" name="toggled_on" type="bool" />
+			<description>
+				Emitted when the [LineEdit] switches between focus and edit modes.
```
Comment (WhalesState) [inline doc/classes/LineEdit.xml:313]: This isn't clear, since edit mode insures focus, maybe `select and edit modes` or `focus and focus-edit modes` is better.

Comment (KoBeWi) [reply doc/classes/LineEdit.xml:313]: `Emitted when the [LineEdit] switches in or out of edit mode.`?
I'd also explain edit mode in the class' description.

File: scene/gui/line_edit.cpp [hunk 16]
```diff
@@ -45,6 +45,70 @@
...
+	}
+
+	if (!editable || editing) {
+		return;
+	}
+
+	editing = true;
+	_validate_caret_can_draw();
+
+	if (get_viewport()->get_window_id() != DisplayServer::INVALID_WINDOW_ID && DisplayServer::get_singleton()->has_feature(DisplayServer::FEATURE_IME)) {
```
Comment (KoBeWi) [inline scene/gui/line_edit.cpp:64]: Not sure if this is an equivalent of the old code with window ID.

File: scene/gui/line_edit.cpp [hunk 17]
```diff
@@ -45,6 +45,70 @@
...
+
+	if (DisplayServer::get_singleton()->has_feature(DisplayServer::FEATURE_VIRTUAL_KEYBOARD) && virtual_keyboard_enabled) {
+		DisplayServer::get_singleton()->virtual_keyboard_hide();
+	}
+
+	if (deselect_on_focus_loss_enabled) {
+		// deselect calls queue_redraw().
+		deselect();
+	} else {
+		queue_redraw();
```
Comment (KoBeWi) [inline scene/gui/line_edit.cpp:102]: `set_caret_column()` also calls `queue_redraw()`.

File: scene/gui/line_edit.cpp [hunk 18]
```diff
@@ -265,26 +334,37 @@ void LineEdit::gui_input(const Ref<InputEvent> &p_event) {
 
 	Ref<InputEventMouseButton> b = p_event;
 
-	if (b.is_valid()) {
-		if (ime_text.length() != 0) {
-			// Ignore mouse clicks in IME input mode.
-			return;
```
Comment (KoBeWi) [inline scene/gui/line_edit.cpp:271]: What happened to this part?

File: scene/gui/line_edit.cpp [hunk 19]
```diff
@@ -1132,43 +1235,19 @@ void LineEdit::_notification(int p_what) {
...
 
-			DisplayServer::WindowID wid = get_window() ? get_window()->get_window_id() : DisplayServer::INVALID_WINDOW_ID;
-			if (wid != DisplayServer::INVALID_WINDOW_ID && DisplayServer::get_singleton()->has_feature(DisplayServer::FEATURE_IME)) {
-				DisplayServer::get_singleton()->window_set_ime_active(true, wid);
-				Point2 pos = Point2(get_caret_pixel_pos().x, (get_size().y + theme_cache.font->get_height(theme_cache.font_size)) / 2) + get_global_position();
-				if (get_window()->get_embedder()) {
-					pos += get_viewport()->get_popup_base_transform().get_origin();
-				}
-				DisplayServer::get_singleton()->window_set_ime_position(pos, wid);
+			if (!(Input::get_singleton()->is_action_pressed("ui_up") || Input::get_singleton()->is_action_pressed("ui_down") || Input::get_singleton()->is_action_pressed("ui_left") || Input::get_singleton()->is_action_pressed("ui_right"))) {
```
Comment (KoBeWi) [inline scene/gui/line_edit.cpp:1238]: You could add a comment to explain purpose of this condition.

File: scene/gui/line_edit.cpp [hunk 20]
```diff
@@ -1661,7 +1740,7 @@ void LineEdit::clear() {
 	_text_changed();
 
 	// This should reset virtual keyboard state if needed.
-	if (has_focus()) {
+	if (has_focus() && editing) {
```
Comment (KoBeWi) [inline scene/gui/line_edit.cpp:1743]: Same: can `editing` be true without focus?

**Review by KoBeWi — APPROVED** [review]
Tested basic functionality and it works great.
I noticed some IME change that I'm not sure about; they need to be assessed.

> This also can be applied to TextEdit, but to only exit editing mode by pressing escape and to not enter editing mode when it's focused with arrows.

Yeah this would be useful for TextEdit too.

File: scene/gui/line_edit.cpp (hunk 16 above)
Comment (WhalesState) [reply scene/gui/line_edit.cpp:64]: `_edit` and `_unedit` was missing the new changes related to some bug fixes, they should follow the old focus entered/exited code. Thank you.

File: scene/gui/line_edit.cpp (hunk 18 above)
Comment (WhalesState) [reply scene/gui/line_edit.cpp:271]: Combined both checks `if (b.is_valid() && ime_text.is_empty())` in one statement and returned back the comment.

**Comment by WhalesState** [comment]
> Tested basic functionality and it works great. I noticed some IME change that I'm not sure about; they need to be assessed.

We have to make sure that the old code is still the same.

Changes in this PR:
- `NOTIFICATION_FOCUS_ENTER` old code was moved to `_edit()`. 
- `NOTIFICATION_FOCUS_EXIT` old code was moved to `_unedit()`.
- `String.length() == 0` and `String.length() != 0` was changed to `String.is_empty()` and `!String.is_empty()` for readability.
- Removed redundant `queue_redraw()` calls.

File: scene/gui/spin_box.cpp [hunk 21]
```diff
@@ -602,8 +594,7 @@ SpinBox::SpinBox() {
 	line_edit->set_horizontal_alignment(HORIZONTAL_ALIGNMENT_LEFT);
 
 	line_edit->connect("text_submitted", callable_mp(this, &SpinBox::_text_submitted), CONNECT_DEFERRED);
-	line_edit->connect(SceneStringName(focus_entered), callable_mp(this, &SpinBox::_line_edit_focus_enter), CONNECT_DEFERRED);
-	line_edit->connect(SceneStringName(focus_exited), callable_mp(this, &SpinBox::_line_edit_focus_exit), CONNECT_DEFERRED);
+	line_edit->connect("editing_toggled", callable_mp(this, &SpinBox::_line_edit_editing_toggled), CONNECT_DEFERRED);
```
Comment (WhalesState) [inline scene/gui/spin_box.cpp:597]: Is it better use `SNAME("editing_toggled")` and `SNAME("text_submitted")` because those `StringName`s are already defined in `LineEdit`.

File: doc/classes/LineEdit.xml [hunk 22]
```diff
@@ -4,7 +4,15 @@
 		An input field for single-line text.
 	</brief_description>
 	<description>
-		[LineEdit] provides an input field for editing a single line of text. It features many built-in shortcuts that are always available ([kbd]Ctrl[/kbd] here maps to [kbd]Cmd[/kbd] on macOS):
+		[LineEdit] provides an input field for editing a single line of text.
+		[b]New behavior:[/b]
+		- When the [LineEdit] control is focused using keyboard arrow keys, it will only gain focus and not enter edit mode.
+		- To enter edit mode, click on the control with the mouse or press the "ui_text_submit" action (default: Enter or Kp Enter keys).
```
Comment (AThousandShips) [inline doc/classes/LineEdit.xml:10]:
```suggestion
		- To enter edit mode, click on the control with the mouse or press the "ui_text_submit" action (default: [kbd]Enter[/kbd] or [kbd]Kp Enter[/kbd]).
```

File: doc/classes/LineEdit.xml [hunk 23]
```diff
@@ -4,7 +4,15 @@
...
+		- To exit edit mode, press "ui_text_submit" or "ui_cancel" (default: Escape key) actions.
+		- Check [method is_editing] and [signal editing_toggled] for more information.
+		[b]Important:[/b]
+		- Focusing the [LineEdit] with "ui_focus_next" (default: Tab key) or "ui_focus_prev" (default: Shift+Tab key) or [method Control.grab_focus] still enters edit mode (for compatibility).
```
Comment (AThousandShips) [inline doc/classes/LineEdit.xml:14]:
```suggestion
		- Focusing the [LineEdit] with "ui_focus_next" (default: [kbd]Tab[/kbd]) or "ui_focus_prev" (default: [kbd]Shift + Tab[/kbd]) or [method Control.grab_focus] still enters edit mode (for compatibility).
```

**Review by AThousandShips — APPROVED** [review]

File: doc/classes/LineEdit.xml [hunk 24]
```diff
@@ -4,7 +4,15 @@
 		An input field for single-line text.
 	</brief_description>
 	<description>
-		[LineEdit] provides an input field for editing a single line of text. It features many built-in shortcuts that are always available ([kbd]Ctrl[/kbd] here maps to [kbd]Cmd[/kbd] on macOS):
+		[LineEdit] provides an input field for editing a single line of text.
+		[b]New behavior:[/b]
```
[the remark this answers is not in the document]
Comment (WhalesState) [reply doc/classes/LineEdit.xml:8]: Which line? I Just wanted to move the new changes after the short description and before the shortcuts list.

[the remark this answers is not in the document]
Comment (WhalesState) [reply doc/classes/LineEdit.xml:8]: Got it, `[b]New behavior:[/b]` line was removed, i thought it's about the ordering.

**Comment by akien-mga** [comment]
Thanks!
