### PR TITLE
Fix OGG Vorbis playback with more than one channel

### LINKED ISSUE #56371: Godot only plays one channel in .ogg file
### Godot version

4.0.dev (91b97dac0)

### System information

Windows 10, Vulkan, Realtek Audio

### Issue description

OGG files will play as mono sound files, only playing the left channel from the file. 
**This issue doesn't occur in 3.4.2,**

https://user-images.githubusercontent.com/76781125/147818823-ed512cf1-33e1-4b6c-935a-697e3acf0570.mp4

.

### Steps to reproduce

Import any stereo OGG file and play it. Only the left channel will work.

### Minimal reproduction project

[OGG issue reproduction project.zip](https://github.com/godotengine/godot/files/7795946/OGG.issue.reproduction.project.zip)

### PR DESCRIPTION
**Pull request by Cnidarias**
When an OGG Vorbis file has more than one channel we accidentily were
assigning only the left channel to both the L and R channels of the
AudioFrame output buffer

Fixes #56371

### CODE REVIEW

File: modules/vorbis/audio_stream_ogg_vorbis.cpp [hunk 1]
```diff
@@ -110,7 +110,7 @@ int AudioStreamPlaybackOGGVorbis::_mix_frames_vorbis(AudioFrame *p_buffer, int p
 	if (info.channels > 1) {
 		for (int frame = 0; frame < frames; frame++) {
 			p_buffer[frame].l = pcm[0][frame];
-			p_buffer[frame].r = pcm[0][frame];
+			p_buffer[frame].r = pcm[1][frame];
```
Comment (ellenhp) [inline modules/vorbis/audio_stream_ogg_vorbis.cpp:113]: From what I see in the libvorbis documentation, this might cause an out-of-bounds read for mono files.

https://xiph.org/vorbis/doc/libvorbis/vorbis_synthesis_pcmout.html

Perhaps we could check the number of channels in the vorbis_info? If it's a mono we should keep the current behavior I think. https://xiph.org/vorbis/doc/libvorbis/vorbis_info.html

Comment (Cnidarias) [reply modules/vorbis/audio_stream_ogg_vorbis.cpp:113]: That is exactly what is happening. The info in the if statement is the `vorbis_info` with the already parsed number of channels. The following else condition  is keeping the current behaviour of using the `0th` element for both L and R when we have `<= 1 ` channels

Comment (ellenhp) [reply modules/vorbis/audio_stream_ogg_vorbis.cpp:113]: Oh gosh you're right, that's what I get for reviewing code before I was fully awake.

**Review by ellenhp — APPROVED** [review]

**Comment by ellenhp** [comment]
@akien-mga I feel like this should be low-risk enough to merge but I don't want to mess things up given that I've been entrusted with write access. Are there any additional things that need to happen before I hit the big green button?

**Comment by akien-mga** [comment]
@ellenhp for the `master` branch during this stage of development, you're very welcome to merge this kind of fix yourself. It's only for 3.x branches or when `master` will reach beta/RC stage that some more coordination might be needed with regard to release management.

**Comment by ellenhp** [comment]
@Cnidarias Thank you for identifying the root cause of this issue and coming up with the fix! Much appreciated :)

**Comment by Cnidarias** [comment]
@akien-mga i don't think we need to cherry pick this into 3.x 
According to the original issue poster the issue was not present on the 3.x versions but I can verify this later if you'd like

**Comment by ellenhp** [comment]
Yeah, 3.x is still on stb_vorbis so cherry picking shouldn't be necessary.
