### PR TITLE
Replace malloc's with Godot's memalloc macro

### LINKED ISSUE #46807: Unchecked malloc return NULL vulnerability
**Issue description:**
Found two Unchecked malloc return NULL vulnerabilities in Godot repository.

The two vulnerabilities are in these files:
https://github.com/godotengine/godot/blob/b9aa2d0dfb5ec6e93e1dc3604fba92606c1a2398/modules/xatlas_unwrap/register_types.cpp#L163-L175
https://github.com/godotengine/godot/blob/5525cd85c60455b0bb9716bbef0ad2ad8111d752/modules/mono/mono_gd/support/android_support.cpp#L637-L641

Both vulnerabilities can potential occur when malloc cannot successfully allocate memory, it would instead return a null pointer which has unexpected behaviors when operated on. See this for more detail about this type of vulnerability https://cwe.mitre.org/data/definitions/690.html

### PR DESCRIPTION
**Pull request by rsubtil**
Replaces some "raw" calls to `malloc` and handle error scenarios.

Fixes #46807

### CODE REVIEW

File: platform/windows/windows_terminal_logger.cpp [hunk 1]
```diff
@@ -54,6 +54,7 @@ void WindowsTerminalLogger::logv(const char *p_format, va_list p_list, bool p_er
 		return;
 
 	wchar_t *wbuf = (wchar_t *)malloc((len + 1) * sizeof(wchar_t));
```
Comment (akien-mga) [inline platform/windows/windows_terminal_logger.cpp:56]: You forgot to change this one.

Comment (Ev1lbl0w) [reply platform/windows/windows_terminal_logger.cpp:56]: When I change this to Godot's macro, the unit tests for Windows fail. Maybe it has to do with padding being enforced on debug builds?
image

**Comment by akien-mga** [comment]
Should you use `memfree()` to free memory allocated with `memalloc()`?

File: modules/mono/mono_gd/support/android_support.cpp [hunk 2]
```diff
@@ -636,7 +635,8 @@ GD_PINVOKE_EXPORT int32_t _monodroid_get_dns_servers(void **r_dns_servers_array)
 
 	if (dns_servers_count > 0) {
 		size_t ret_size = sizeof(char *) * (size_t)dns_servers_count;
-		*r_dns_servers_array = malloc(ret_size); // freed by the BCL
+		*r_dns_servers_array = memalloc(ret_size); // freed by the BCL
+		ERR_FAIL_NULL_MSG(r_dns_servers_array, "Out of memory.");
```
Comment (neikeq) [inline modules/mono/mono_gd/support/android_support.cpp:639]: Like the comment says, this is freed by the Mono BCL which doesn't use Godot's `memfree` (`Memory::free_static`). Isn't that going to cause trouble?
Honestly, I would prefer this wasn't touched. Mono's allocations don't use Godot's allocation macros any way.

Comment (akien-mga) [reply modules/mono/mono_gd/support/android_support.cpp:639]: See #46807 - if `malloc` fails (e.g. OOM), this can lead to a null pointer dereference.

But yes in this file we can likely add `ERR_FAIL_NULL_MSG` on the result of `malloc()` without changing it to Godot's static alloc.

File: platform/windows/windows_terminal_logger.cpp (hunk 1 above)
Comment (akien-mga) [reply platform/windows/windows_terminal_logger.cpp:56]: You can see if it works when using `memfree()` to free the memory too.

**Comment by Ev1lbl0w** [comment]
Quick summary of the changes I've made:
- `modules/bullet/space_bullet.cpp`: reverted to `malloc` as the pointer is used elsewhere, in a way I honestly don't understand how :sweat_smile:
- `modules/upnp/upnp.cpp`: reverted to `malloc`, the pointer is freed using a custom method
- `modules/xatlas_unwrap/register_types.cpp`: changed `free`'s on `scene/resources/mesh.cpp`

Other than these, I've changed the corresponding free's to Godot's macro. I was also wrongly testing some allocations _(testing `r_vertices` when I should be testing `*r_vertices`, for example)_, so I've fixed those as well.

_(I am depending on the CI to know if this compiles to the many platforms this affects, so I might need to do quite some force-pushes)_

File: scene/resources/mesh.cpp [hunk 3]
```diff
@@ -1565,9 +1565,9 @@ Error ArrayMesh::lightmap_unwrap_cached(int *&r_cache_data, unsigned int &r_cach
 
 	if (!r_used_cache) {
 		//free stuff
-		::free(gen_vertices);
-		::free(gen_indices);
-		::free(gen_uvs);
+		::memfree(gen_vertices);
+		::memfree(gen_indices);
+		::memfree(gen_uvs);
```
Comment (akien-mga) [inline scene/resources/mesh.cpp:1570]: The `::` can be removed, they were used to disambiguate `free()`, but there's no ambiguity with `memfree()`.

Comment (Ev1lbl0w) [reply scene/resources/mesh.cpp]: Fixed

**Review by reduz — APPROVED** [review]

File: modules/xatlas_unwrap/register_types.cpp [hunk 4]
```diff
@@ -160,9 +160,12 @@ bool xatlas_mesh_lightmap_unwrap_callback(float p_texel_size, const float *p_ver
...
 
-	*r_vertices = (int *)malloc(sizeof(int) * output.vertexCount);
-	*r_uvs = (float *)malloc(sizeof(float) * output.vertexCount * 2);
-	*r_indices = (int *)malloc(sizeof(int) * output.indexCount);
+	*r_vertices = (int *)memalloc(sizeof(int) * output.vertexCount);
+	ERR_FAIL_NULL_V_MSG(*r_vertices, false, "Out of memory.");
+	*r_uvs = (float *)memalloc(sizeof(float) * output.vertexCount * 2);
+	ERR_FAIL_NULL_V_MSG(*r_uvs, false, "Out of memory.");
+	*r_indices = (int *)memalloc(sizeof(int) * output.indexCount);
+	ERR_FAIL_NULL_V_MSG(*r_indices, false, "Out of memory.");
```
Comment (akien-mga) [inline modules/xatlas_unwrap/register_types.cpp:168]: These are members of `xatlas::Mesh` which is in thirdparty code and doesn't use `memfree()`, so I'm not sure they should be changed to `memalloc()`.

File: modules/mono/mono_gd/support/android_support.cpp [hunk 5]
```diff
@@ -414,9 +414,8 @@ GD_PINVOKE_EXPORT int32_t monodroid_get_system_property(const char *p_name, char
 
 	if (r_value) {
 		if (len >= 0) {
-			*r_value = (char *)malloc(len + 1);
-			if (!*r_value)
-				return -1;
+			*r_value = (char *)memalloc(len + 1);
```
Comment (akien-mga) [inline modules/mono/mono_gd/support/android_support.cpp:417]: This is freed at line 629 and should be changed to `memfree()` - or kept as `malloc()` here if @neikeq thinks it's better.

Comment (Ev1lbl0w) [reply modules/mono/mono_gd/support/android_support.cpp:417]: Nice catch :slightly_smiling_face:.  I couldn't find any call to this method, maybe VSCode is skipping files that are ignored due to #if guards, I'll have to see if I can fix this.

I agree to use `malloc` here again; honestly, I'm scared of the scope this PR has, so maybe we should just stick with `malloc` where there are worries it might break something. The objective is to prevent null de-references from happening anyways.

Comment (neikeq) [reply modules/mono/mono_gd/support/android_support.cpp:417]: I prefer to keep it as it was as I'm not 100% sure it's always freed with the `monodroid_free` we implement above. I prefer not to risk.

Comment (Ev1lbl0w) [reply modules/mono/mono_gd/support/android_support.cpp]: Fixed

File: modules/xatlas_unwrap/register_types.cpp (hunk 4 above)
Comment (Ev1lbl0w) [reply modules/xatlas_unwrap/register_types.cpp]: Reverted to `malloc`, and reverted to normal `free`'s in `scene/resources/mesh.cpp`

Comment (akien-mga) [reply modules/xatlas_unwrap/register_types.cpp]: I think there was confusing here, `xatlas::Mesh` is not related to `scene/resources/mesh.cpp`. `xatlas` is a thirdparty library in `thirdparty/xatlas/`, and it has its own `Mesh` struct.

**Review by akien-mga — APPROVED** [review]
Looks great! The current subset of changes seems safe to me :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
