### PR TITLE
[HTML5] Port inline JS code to libraries, AudioWorklet support.

### LINKED ISSUE #40891: Audio stuttering on HTML5 export
**Godot version:**
Godot 3.2.2 Stable & 3.2.3 rc1 & 3.2.3 rc2

**OS/device including version:**
GLES2 / Chrome Browser

Tested on: 
LG k11+ - Android (Outdated Mobile)
LG K10 - Android (Outdated Mobile)
AMD C-50 Processor 1.00 GHZ - 2 GB RAM - Windows 7 (Outdated Computer)

**Issue description:**
We have start receiving feedback from customers, regarding stuttering audios, it does happens more often in outdated computers, and even more often in outdated mobile devices.
But our build versions in another engines seams to be working properly on the same devices, and only the Godot builds are stuttering.
We thought Godot 3.2.3 rc1 would come with a solution for this stuttering with the update in output latency for web, but it didn't do the trick for us.

Perhaps it is correlated with the drop in FPS, since we stick to use GLES2, we are still using GLES2 because of its compatibility with older mobile devices.
Is it possible the stuttering is happening because of WebGL 1.0? If so, is it a limitation of the technology version?

**Steps to reproduce:**
N/A

**Minimal reproduction project:**
[AudioTest.zip](https://github.com/godotengine/godot/files/5003542/AudioTest.zip)

### PR DESCRIPTION
**Pull request by Faless**
In this PR:

- Usual fixes to the `RasterizerDummy`
- Fix gdnative build when WebRTC module is disabled.
- Update syntax for lto. (we could do better, and specify `lto=thin` `lto=full` etc, but keep it short for now).
- A **huge refactor** of the JavaScript code porting it to libraries:
  The API is implemented in JavaScript, and generates C functions that can be called from Godot.
  This allows much cleaner code replacing all `EM_ASM` calls in our C++ code with plain C function calls.
  This also gets rid of few hacks and comes with few optimizations (e.g. custom cursor shapes should be much faster now).
- **AudioWorklet** API implementation.
  Rewrote AudioDriverJavaScript to support multiple processor nodes.
  The old (and deprecated) `ScriptProcessorNode` when threads are not available, and the new `AudioWorklet` API when threads are enabled.
  The new implementation uses two ring buffers and a shared state to communicated with the `AudioWorklet` thread.
  The `audio.worklet.js` JavaScript file is always added to the export template, but only really used (and downloaded) in the thread build.

Fixes #40891 (on thread builds, which is the only build that can be fixed).
Potentially others, which I will review.

There is a 3.x version here: https://github.com/Faless/godot/tree/js/3.x_audio_worklet

### CODE REVIEW

File: modules/webrtc/webrtc_data_channel_js.cpp [hunk 1]
```diff
@@ -34,90 +34,66 @@
...
 	in_buffer.write(p_data, p_size);
-	queue_count++;
+	peer->queue_count++;
 }
 
 void WebRTCDataChannelJS::close() {
 	in_buffer.resize(0);
 	queue_count = 0;
 	_was_string = false;
-	/* clang-format off */
```
Comment (akien-mga) [inline modules/webrtc/webrtc_data_channel_js.cpp:84]: Yay, begone `/* clang-format off */` hacks around all `EM_ASM` calls :D

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
