### PR TITLE
Redraw `TreeItem` on more changes

### LINKED ISSUE #87404: SetCustomFont() and SetCustomFontSize() don’t redraw TreeItem
### Tested versions

- Reproducible in Godot (mono) v4.2.1

### System information

Arch Linux

### Issue description

Setting font properties via SetCustomFont() and SetCustomFontSize() of a TreeItem don’t actually redraw the TreeItem, making it impossible to change the TreeItem’s font and fontsize on the fly. The visual representation of an item only seems to update when changing its text or rebuilding the tree.

A somewhat gentle workaround for now is to reset the item text while adding whitespace (just resetting the same text is ignored).

### Steps to reproduce

Add this script to a Tree node:

```C#
public partial class tree : Tree
{
	public override void _Ready()
	{
		CreateItem();
		TreeItem treeItem = CreateItem();
		treeItem.SetText(0, "Clicking me should change my font size");

		ItemSelected += _OnItemSelected;
	}

	public void _OnItemSelected()
	{
		TreeItem treeItem = GetSelected();
		treeItem.SetCustomFontSize(0, 20);
		//treeItem.SetText(0, "I'm now 20px"); <-- Uncommenting this line needed to update item
	}
}```

The item is only updated once the last line is uncommented.

### Minimal reproduction project (MRP)

[TreeItemTest.zip](https://github.com/godotengine/godot/files/13997621/TreeItemTest.zip)

### PR DESCRIPTION
**Pull request by AThousandShips**
* Custom font changes
* Custom draw changes
* Custom as button

Looking into detecting changes to the font itself to do updates but unsure if desired so will hold off on that for the time being (in that case I would look into doing it for all the relevant resource types, like for `set_icon`, `add_button`, `set_button`, etc.)

* Fixes: https://github.com/godotengine/godot/issues/87404

### CODE REVIEW

**Comment by AThousandShips** [comment]
While looking at the additional changes I realized that it's impossible to clear the custom draw for a `TreeItem`, making a PR to add that

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -1370,6 +1384,8 @@ void TreeItem::set_custom_as_button(int p_column, bool p_button) {
```
Comment (KoBeWi) [inline scene/gui/tree.cpp:1384]: Missing check for value being different.

Comment (AThousandShips) [reply scene/gui/tree.cpp:1384]: Will add 🙂

**Review by KoBeWi — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.4.
