### PR TITLE
Show in File Manager Clarification

### LINKED ISSUE #20897: Inconsistent behavior of `Show in File Manager` on file and on directory
**Godot version:**

non-official [hash: 52e6f1f25c86891381ca3ce9e03422db586ecd16](https://github.com/godotengine/godot/tree/52e6f1f25c86891381ca3ce9e03422db586ecd16)

**OS/device including version:**

macOS 10.13

**Issue description:**

inconsistent behavior of `Show in File Manager` on file and on directory. Not sure it is a bug or a feature.

**Steps to reproduce:**
##### open “Show in File Manager” on a directory
screen shot 2018-08-10 at 16 03 59

##### it opens the select directory
screen shot 2018-08-10 at 16 04 12

##### open "Show in File Manager" on a file
screen shot 2018-08-10 at 16 04 37

##### it opens the directory contains that file
screen shot 2018-08-10 at 16 04 55

In Godot 3.0, click on "Show in File Manager" both on file or directory will open the directory contains it

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by ivodopiviz**
Changed the context menu 'Show in File Manager' action description to better reflect actual behavior. Fixes #20897 

PS. I'm not sure if I need to do something to add a new translatable string or if it's picked up automatically by the translation system.

### CODE REVIEW

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -1757,7 +1757,10 @@ void FileSystemDock::_files_list_rmb_select(int p_item, const Vector2 &p_pos) {
 	file_options->add_item(TTR("New Folder..."), FILE_NEW_FOLDER);
 	file_options->add_item(TTR("New Script..."), FILE_NEW_SCRIPT);
 	file_options->add_item(TTR("New Resource..."), FILE_NEW_RESOURCE);
-	file_options->add_item(TTR("Show In File Manager"), FILE_SHOW_IN_EXPLORER);
+
```
Comment (akien-mga) [inline editor/filesystem_dock.cpp]: There's trailing whitespace here.

File: editor/editor_file_dialog.cpp [hunk 2]
```diff
@@ -558,7 +558,9 @@ void EditorFileDialog::_item_list_item_rmb_selected(int p_item, const Vector2 &p
 	}
 	if (single_item_selected) {
 		item_menu->add_separator();
-		item_menu->add_icon_item(get_icon("Filesystem", "EditorIcons"), TTR("Show In File Manager"), ITEM_MENU_SHOW_IN_EXPLORER);
+		Dictionary item_meta = item_list->get_item_metadata(p_item);
+		String item_text = (item_meta["dir"]) ? TTR("Open In File Manager") : TTR("Show In File Manager");
```
Comment (akien-mga) [inline editor/editor_file_dialog.cpp]: Style-wise, I wouldn't put parentheses around `item_meta["dir"]` (only if it was an expression with an evaluation like `(item_meta["dir"] != other_thing)`). Same for the other ternary operator in `filesystem_dock.cpp`.

File: editor/filesystem_dock.cpp [hunk 3]
```diff
@@ -1983,11 +1986,9 @@ FileSystemDock::FileSystemDock(EditorNode *p_editor) {
 
 */
 	file_options = memnew(PopupMenu);
-	file_options->set_hide_on_window_lose_focus(true);
```
Comment (akien-mga) [inline editor/filesystem_dock.cpp]: What's the rationale for changing this?

**Comment by akien-mga** [comment]
Apart from my nitpicks, the proposed changes seem fine.

File: editor/editor_file_dialog.cpp (hunk 2 above)
Comment (ivodopiviz) [reply editor/editor_file_dialog.cpp]: Will change, but there are other cases not written by me following that style, even on the same file. It seems to be mixed but I'd leave normalizing that for a different patch.

File: editor/filesystem_dock.cpp (hunk 3 above)
Comment (ivodopiviz) [reply editor/filesystem_dock.cpp]: I don't remember removing this, will rollback to master.

**Comment by ivodopiviz** [comment]
I think I cleaned up everything.

**Comment by akien-mga** [comment]
Thanks, looks good!
