### PR TITLE
MultiplayerAPI: Fix disconnect errors when passing invalid peer

### LINKED ISSUE #34634: MultiplayerAPI::set_network_peer try to disconnect not existent signals
**Godot version:**
Godot 3.2 beta 4
**OS/device including version:**
Ubuntu 19.10
**Issue description:**
Errors
```
ERROR: _disconnect: Nonexistent signal: peer_connected.
   At: core/object.cpp:1520.
ERROR: _disconnect: Nonexistent signal: peer_disconnected.
   At: core/object.cpp:1520.
ERROR: _disconnect: Nonexistent signal: connection_succeeded.
   At: core/object.cpp:1520.
ERROR: _disconnect: Nonexistent signal: connection_failed.
   At: core/object.cpp:1520.
ERROR: _disconnect: Nonexistent signal: server_disconnected.
   At: core/object.cpp:1520.

```
**Steps to reproduce:**
1. Run minimal project
2. Look at the output
**Minimal reproduction project:**
[AAA.zip](https://github.com/godotengine/godot/files/4005559/AAA.zip)

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #34634.

As mentioned in the issue, when I tried this fix on the "minimal" reproduction project, my system froze. Not sure what to make of it as I don't see why this code change would trigger a freeze when the previous code didn't. Might just have been bad luck.

### CODE REVIEW

**Comment by akien-mga** [comment]
> As mentioned in the issue, when I tried this fix on the "minimal" reproduction project, my system froze. Not sure what to make of it as I don't see why this code change would trigger a freeze when the previous code didn't. Might just have been bad luck.

Tested again a couple times without freeze, so I think it was likely not directly related to this fix.

File: core/io/multiplayer_api.cpp [hunk 1]
```diff
@@ -139,6 +139,9 @@ void MultiplayerAPI::set_network_peer(const Ref<NetworkedMultiplayerPeer> &p_pee
 
 	if (p_peer == network_peer) return; // Nothing to do
 
+	ERR_FAIL_COND_MSG(p_peer.is_valid() && p_peer->get_connection_status() == NetworkedMultiplayerPeer::CONNECTION_DISCONNECTED,
```
Comment (akien-mga) [inline core/io/multiplayer_api.cpp]: IINM one intended use for this method could be to reset the network peer to null with `set_network_peer(NULL)`.
I think it's still going to work as `p_peer.is_valid()` here will fail, so it won't error out, and `network_peer = p_peer;` will still run as expected.
