### PR TITLE
Fix custom Text Editor theme changes on reload

### LINKED ISSUE #103914: Modifying colors of the text editor theme highlightings causes non-modified colors to change without user input upon project reload.
### Tested versions

Reproducible in 4.4

### System information

Image

### Issue description

When changing colors of the text editor theme highlightings, non-modified colors will change without user input upon project reload.

Example:

Changing Comment Color to green. Everything looks fine.

Image

After project reload

Image

### Steps to reproduce

Open Project
View and verify that the editor themes/script editor themes are default colors
Change a single color of the Script Editor Theme Highlighting Colors
View script. It should look correct
Save project
Reload
View script. Script editor theme colors have changed

### Minimal reproduction project (MRP)

[testing.zip](https://github.com/user-attachments/files/19166370/testing.zip)

### PR DESCRIPTION
**Pull request by kitbdev**
- Fixes https://github.com/godotengine/godot/issues/103914

When the EditorSettings loads defaults, I replaced the call to `_load_godot2_text_editor_theme` with `EDITOR_SETTING*`, this is so the text editor theme settings always saves to the editor settings file, just like the editor theme settings does. This is important when loading and the preset is Custom.
The `_load_godot2_text_editor_theme` should probably be moved to the editor theme manager in the future, for now I left it as is since the text editor theme loading still uses it.

I wanted to have the EditorSettingsDialog immediately update so the revert icons show, but I ran into an issue with the ColorPickerButton completely freezing the dialog if it was open while reloading. As before, they only reload when reopening the category or the dialog. It shouldn't cause any issues that they aren't immediately updated, since it is just for the revert buttons.

The initial values for the Custom preset are now the current Default theme. So if you were on Godot 2 and change to Custom, all of the values can be reverted, and the same from Default if the editor's base color changes, since Default changes based on it.

### CODE REVIEW

File: editor/themes/editor_theme_manager.cpp [hunk 1]
```diff
@@ -2633,109 +2633,109 @@ void EditorThemeManager::_populate_editor_styles(const Ref<EditorTheme> &p_theme
...
+		colors["text_editor/theme/highlighting/warning_color"] = warning_color;
+		colors["text_editor/theme/highlighting/bookmark_color"] = bookmark_color;
+		colors["text_editor/theme/highlighting/breakpoint_color"] = breakpoint_color;
+		colors["text_editor/theme/highlighting/executing_line_color"] = executing_line_color;
+		colors["text_editor/theme/highlighting/code_folding_color"] = code_folding_color;
+		colors["text_editor/theme/highlighting/folded_code_region_color"] = folded_code_region_color;
+		colors["text_editor/theme/highlighting/search_result_color"] = search_result_color;
+		colors["text_editor/theme/highlighting/search_result_border_color"] = search_result_border_color;
+
+		for (KeyValue<StringName, Color> setting : colors) {
```
Comment (AThousandShips) [inline editor/themes/editor_theme_manager.cpp]:
```suggestion
		for (const KeyValue<StringName, Color> &setting : colors) {
```

File: editor/editor_settings.cpp [hunk 2]
```diff
@@ -695,7 +695,45 @@ void EditorSettings::_load_defaults(Ref<ConfigFile> p_extra_config) {
...
+	EDITOR_SETTING_BASIC(Variant::COLOR, PROPERTY_HINT_NONE, "text_editor/theme/highlighting/warning_color", Color(1.0, 0.8, 0.4, 0.1), "")
+	EDITOR_SETTING(Variant::COLOR, PROPERTY_HINT_NONE, "text_editor/theme/highlighting/bookmark_color", Color(0.08, 0.49, 0.98), "")
+	EDITOR_SETTING(Variant::COLOR, PROPERTY_HINT_NONE, "text_editor/theme/highlighting/breakpoint_color", Color(0.9, 0.29, 0.3), "")
+	EDITOR_SETTING(Variant::COLOR, PROPERTY_HINT_NONE, "text_editor/theme/highlighting/executing_line_color", Color(0.98, 0.89, 0.27), "")
+	EDITOR_SETTING(Variant::COLOR, PROPERTY_HINT_NONE, "text_editor/theme/highlighting/code_folding_color", Color(0.8, 0.8, 0.8, 0.8), "")
+	EDITOR_SETTING(Variant::COLOR, PROPERTY_HINT_NONE, "text_editor/theme/highlighting/folded_code_region_color", Color(0.68, 0.46, 0.77, 0.2), "")
+	EDITOR_SETTING(Variant::COLOR, PROPERTY_HINT_NONE, "text_editor/theme/highlighting/search_result_color", Color(0.05, 0.25, 0.05, 1), "")
+	EDITOR_SETTING(Variant::COLOR, PROPERTY_HINT_NONE, "text_editor/theme/highlighting/search_result_border_color", Color(0.41, 0.61, 0.91, 0.38), "")
```
Comment (KoBeWi) [inline editor/editor_settings.cpp:736]: These settings were basic before.
Probably fine to change it, just wanted to note.

**Comment by KoBeWi** [comment]
Why do `_load_defaults()` and `_load_godot2_text_editor_theme()` initialize the same values?

File: editor/editor_settings.cpp (hunk 2 above)
Comment (kitbdev) [reply editor/editor_settings.cpp:736]: These ones weren't basic before, they should be the same. In `_load_godot2_text_editor_theme` they don't have `true`.

**Comment by kitbdev** [comment]
I plan to move `_load_godot2_text_editor_theme` to EditorThemeManager or at least change it to use `set_initial_value` instead. `_load_godot2_text_editor_theme` is used when changing the theme, but the first initializing needs to use `EDITOR_SETTING`.
The color for the base theme does similar, there is a value set here in EditorSettings, and again in EditorThemeManager.

File: editor/editor_settings.cpp (hunk 2 above)
Comment (KoBeWi) [reply editor/editor_settings.cpp:736]: Nevermind, I misunderstood the code.

**Review by KoBeWi — APPROVED** [review]
You can introduce some struct Godot2Theme or something, which would have constants to use for default values. Defining them twice is not very maintainable.

Although if you plan to clean it up then it's probably fine for now. This fixes the bug at least.

**Comment by Repiteo** [comment]
Thanks!
