### PR TITLE
Fix several oddities in Project Converter

### LINKED ISSUE #65482: Poor English in `--validate-conversion-3to4` error message
### Godot version

v4.0.alpha.custom_build [019253512]

### System information

Arch Linux (IDK how to give a version for this)

### Issue description

When you run the editor with the `--validate-conversion-3to4` command-line option, can either specify a path to a Godot 3 project or have it look for a `project.godot` file in your current working directory. If you don’t specify a valid path and your current working directory does not contain a `project.godot` file, then you’ll get an error. That error is poorly worded:

<samp>ERROR: Current directory doesn't contains any Godot 3 project</samp>

### Steps to reproduce

1. Create an empty folder.
2. `cd` to that empty folder
3. Run `godot4 --validate-conversion-3to4`

### Minimal reproduction project

N/A (happens before the Project Manager loads)

### PR DESCRIPTION
**Pull request by Mickeon**
Fix #65482

This is not a complete list. Nor are all of the changes exhaustive.
- Measure final execution time in seconds instead of milliseconds.
- Use `vformat()` instead of unreadable string concatenation whenever necessary.
- Replaces every `&` used with booleans with `&&` because Visual Studio was really complaining about it.
- Adds punctuation to some comments, in accordance to codebase guidelines.
- Fixes some typos around the file (such as "_parenthesis_" being called "_parenthess_"), as well as attempting to change some sentences to be more English-correct.
- Reworded some comments and error messages outright.

### CODE REVIEW

File: editor/project_converter_3_to_4.cpp [hunk 1]
```diff
@@ -2860,9 +2859,9 @@ String ProjectConverter3To4::get_starting_space(const String &line) const {
 	return empty_space;
 }
 
-// Return object which execute specific function
-// e.g. in `var roman = kieliszek.funkcja()` to this function is passed everything before function which we want to check
-// so it is `var roman = kieliszek.` and this function return `kieliszek.`
+// Return object executing the function in the line.
```
Comment (Jayman2000) [inline editor/project_converter_3_to_4.cpp:2862]: I would change this to “Returns the object that’s executing the function in the line.” Here’s why:

1. The comment above the declaration for `ProjectConverter3To4::get_starting_space` says “Returns”, not “Return”.
2. If the nouns “function” and “line” are going to use an article, then the noun “object” should too.
3. It’s often OK to leave out the word “that”. I don’t think that it’s ever correct to leave out the word “that’s”.

File: editor/project_converter_3_to_4.cpp [hunk 2]
```diff
@@ -2860,9 +2859,9 @@ String ProjectConverter3To4::get_starting_space(const String &line) const {
...
+// e.g. in `var roman = kieliszek.funkcja()` to this function is passed everything before function which we want to check,
+// so it is `var roman = kieliszek.` and this function returns `kieliszek.`
```
Comment (Jayman2000) [inline editor/project_converter_3_to_4.cpp:2864]: I would replace those names with English ones. Additionally, I would simplify the explanation and replace the grave accents with double quotes:

```cpp
// e.g. If you passed "var foo = bar.baz()" to this function, it would return "bar".
```

File: editor/project_converter_3_to_4.cpp [hunk 3]
```diff
@@ -2880,10 +2879,10 @@ String ProjectConverter3To4::get_object_of_execution(const String &line) const {
 			if (start == 0) {
 				break;
 			} else if (is_nodepath_sep) {
-				// Freeze variable_start, try to fetch more chars since this might be node path literal
+				// Freeze variable_start, try to fetch more chars since this might be node path literal.
```
Comment (Jayman2000) [inline editor/project_converter_3_to_4.cpp:2882]: I would change this to “…this might be **a N**ode path literal” since “Node path literal” is a countable noun and `Node` is the name of a class.

File: editor/project_converter_3_to_4.cpp [hunk 4]
```diff
@@ -3031,9 +3030,9 @@ Vector<String> ProjectConverter3To4::check_for_rename_gdscript_functions(Vector<
 	return found_renames;
 }
 
-// TODO, this function should run only on all .gd files and also on lines in tscn files which
+// TODO, this function should run only on all ".gd" files and also on lines in ".tscn" files which
```
Comment (Jayman2000) [inline editor/project_converter_3_to_4.cpp:3033]: I would end this sentence with “and also on lines in ".tscn" files which are parts of built-in Scripts.”

File: editor/project_converter_3_to_4.cpp [hunk 5]
```diff
@@ -3031,9 +3030,9 @@ Vector<String> ProjectConverter3To4::check_for_rename_gdscript_functions(Vector<
...
 void ProjectConverter3To4::process_gdscript_line(String &line, const RegExContainer &reg_container, bool builtin) {
-	// In this and other functions, reg.sub are used only after checking line with str.contains function which is sometimes few times faster with bigger line lengths
+	// In this and other functions, reg.sub() are used only after checking line with str.contains() function which is sometimes few times faster with bigger line lengths
```
Comment (Jayman2000) [inline editor/project_converter_3_to_4.cpp:3035]: I would split this into multiple different sentences to make it easier to understand. Also, there’s subject-verb disagreement. I would change it to:

```cpp
	// In this and other functions, reg.sub() is used only after checking lines with str.contains().
	// When you have longer lines, doing so is sometimes significantly faster.
```

**Review by Jayman2000 — CHANGES_REQUESTED** [review]

**Comment by akien-mga** [comment]
> Begins most errors with "ERROR: " for consistency.

Errors printed by error macros already print a red and bold `ERROR:` prefix so it's redundant to include it again in the message. It will print as `ERROR: ERROR: Failed...`.

**Comment by Mickeon** [comment]
That's funny, so the "ERROR: " were the actual inconsistency.

File: editor/project_converter_3_to_4.cpp (hunk 2 above)
Comment (Mickeon) [reply editor/project_converter_3_to_4.cpp:2864]: Keeping the original language of the author for this one. as a comment it's not that big of a deal and is kind of charming.

**Comment by Mickeon** [comment]
Updated the PR just in time before I went mad.

**Review by akien-mga — APPROVED** [review]
