### PR TITLE
Fix editor crash when stopping game with F8.

### LINKED ISSUE #37121: Editor crash when exiting game using F8
**Godot version:**
989a223

**OS/device including version:**
Windows 10 x64

**Issue description:**
```
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] ScriptEditorDebugger::_notification (x:\inne\godot\source\godot\editor\debugger\script_editor_debugger.cpp:813)
[1] ScriptEditorDebugger::_notification (x:\inne\godot\source\godot\editor\debugger\script_editor_debugger.cpp:813)
[2] ScriptEditorDebugger::_notificationv (x:\inne\godot\source\godot\editor\debugger\script_editor_debugger.h:59)
[3] Object::notification (x:\inne\godot\source\godot\core\object.cpp:915)
[4] SceneTree::_notify_group_pause (x:\inne\godot\source\godot\scene\main\scene_tree.cpp:990)
[5] SceneTree::idle (x:\inne\godot\source\godot\scene\main\scene_tree.cpp:527)
[6] Main::iteration (x:\inne\godot\source\godot\main\main.cpp:2026)
[7] OS_Windows::run (x:\inne\godot\source\godot\platform\windows\os_windows.cpp:3176)
[8] widechar_main (x:\inne\godot\source\godot\platform\windows\godot_windows.cpp:162)
[9] _main (x:\inne\godot\source\godot\platform\windows\godot_windows.cpp:184)
[10] main (x:\inne\godot\source\godot\platform\windows\godot_windows.cpp:196)
[11] __scrt_common_main_seh (f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283)
[12] BaseThreadInitThunk
-- END OF BACKTRACE --
```
Closing the game window normally doesn't produce crash.

### PR DESCRIPTION
**Pull request by ThakeeNathees**
Fix: #37121

before the the while loop ends, the peer was unreferenced, which throws a nullptr access error

### CODE REVIEW

File: editor/debugger/script_editor_debugger.cpp [hunk 1]
```diff
@@ -810,7 +810,9 @@ void ScriptEditorDebugger::_notification(int p_what) {
 
 			const uint64_t until = OS::get_singleton()->get_ticks_msec() + 20;
 
-			while (peer->has_message()) {
+			while (true) {
+				ERR_FAIL_COND_MSG(peer.is_null(), "The debugger peer reference was NULL. (It probably have died).");
```
Comment (Faless) [inline editor/debugger/script_editor_debugger.cpp]: Why not simply:
```diff
diff --git a/editor/debugger/script_editor_debugger.cpp b/editor/debugger/script_editor_debugger.cpp
index 122d38dea3..e2dcd682a9 100644
--- a/editor/debugger/script_editor_debugger.cpp
+++ b/editor/debugger/script_editor_debugger.cpp
@@ -812,7 +812,7 @@ void ScriptEditorDebugger::_notification(int p_what) {
 
                        const uint64_t until = OS::get_singleton()->get_ticks_msec() + 20;
 
-                       while (peer->has_message()) {
+                       while (peer.is_valid() && peer->has_message()) {
 
                                Array arr = peer->get_message();
                                if (arr.size() != 2 || arr[0].get_type() != Variant::STRING || arr[1].get_type() != Variant::ARRAY) {
```

Comment (ThakeeNathees) [reply editor/debugger/script_editor_debugger.cpp]: to print the error message, does it really need or I just go with that?
@Faless

Comment (Faless) [reply editor/debugger/script_editor_debugger.cpp]: Yeah, I don't think we need the error message there

Comment (ThakeeNathees) [reply editor/debugger/script_editor_debugger.cpp]: Done. and thanks for the review
@Faless

**Review by Faless — APPROVED** [review]

**Comment by Faless** [comment]
Thanks!
