### PR TITLE
Fix color picker showing incorrect number of digits when changing display scale

### LINKED ISSUE #68466: only two digits displayed in color picker when changing editor display scale
### Godot version

4.0 beta 4

### System information

windows 10, nvidia geforce 1650, vulkan 1.2.0

### Issue description

Only 2 digits are shown in any color picker when changing editor display scale.

color_panel_wrong_number_of_digits

### Steps to reproduce

Change godot editor display scale to 1.04 for example. Open any color picker, 255 will only show 25.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by LucasLaukka**
fixes #68466 

When setting the offset, the difference between the side and the width of the text should be rounded up to make sure that the text always fits.

### CODE REVIEW

**Comment by MewPurPur** [comment]
The fix looks good to me, but maybe someone else should chime in too.

The commits should be squashed into one. Here's a link to our tutorial on this: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase

**Comment by LucasLaukka** [comment]
Thanks, I have also squashed the commits now.

File: scene/gui/line_edit.cpp [hunk 1]
```diff
@@ -822,7 +822,7 @@ void LineEdit::_notification(int p_what) {
 				case HORIZONTAL_ALIGNMENT_FILL:
 				case HORIZONTAL_ALIGNMENT_LEFT: {
 					if (rtl) {
-						x_ofs = MAX(style->get_margin(SIDE_LEFT), int(size.width - style->get_margin(SIDE_RIGHT) - (text_width)));
+						x_ofs = MAX(style->get_margin(SIDE_LEFT), int(size.width - ceil(style->get_margin(SIDE_RIGHT) + (text_width))));
```
Comment (akien-mga) [inline scene/gui/line_edit.cpp:825]: This should use our own `Math::ceil()` method for consistency (from `core/math/math_funcs.h`, might already be implicitly included).

**Comment by akien-mga** [comment]
@LucasLaukka FYI, the email used to sign your commit (you can see it in the header here: https://patch-diff.githubusercontent.com/raw/godotengine/godot/pull/69680.patch ) doesn't seem to be linked to your GitHub account. It's not a problem per se but if you want this commit to "count" towards contributions made by your GitHub account, you can add this email as secondary email in your GitHub profile (or amend the commit with a different email linked to your GH account).

**Comment by LucasLaukka** [comment]
Great, thanks for the help! I have updated to the 'Math::ceil()' now as well.

**Review by coppolaemilio — APPROVED** [review]

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
