### PR TITLE
Delta smoothing - fix overflow for long frames

### LINKED ISSUE #51482: 3.4-beta3: timing goes crazy after an iOS app suspend/resume cycle > 1 hour
### Godot version

3.4-beta3

### System information

iOS, iPad Pro 1st gen (9.7 inch)

### Issue description

Resuming after 1 hour a suspended (exited) app on iOS does not resume the game normally. The timing is totally messed up and the game goes like crazy, including physics, particles, shaders using `TIME`. Everything runs at lightning (machine) speed.

I ran the same test on an Android phone (Samsung Galaxy A40 - mid low-range), on an iPad Pro 1st gen (old, slower) and on an iPhone 12 mini (recent, fast).

Interestingly only the iPad Pro 1st gen exhibits this behavior, the Android and the iPhone are OK. The iPhone and iPad run the same iOS version 14.7.1.

This is a regression since the same test on 3.3.2 works well on the iPad on resume after 1 hour.

This is probably related to the shader TIME rollover logic set by default to 3600 seconds. If resuming only after 15 minutes for example there is no problem. Tested also with the delta smoothnig setting on and off - same problem in both cases on the said iPad.

### Steps to reproduce

Start the game. Suspend it by exiting the app (via the button or slider). Wait 1 hour. Resume the app.

### Minimal reproduction project

Any project with moving visuals. Particles or shaders using `TIME` are particularly visible.

### PR DESCRIPTION
**Pull request by lawnjelly**
Extremely long frames caused by suspending and resuming the machine could result in an overflow in the delta smoothing because it uses 32 bit math on delta values measured in nanoseconds.

This PR puts a cap of a second as the maximum frame delta that will be processed by the smoothing, otherwise it returns the frame delta 64 bit value unaltered.

I've also converted all internal math to use 64 bit explicitly (except counters). This is probably overkill but it might help avoid any future bugs, and it's not a bottleneck area so there's no real downside.

Fixes #51482 (untested, but looks like the source of the bug)

## Notes
* There are a number of ways of fixing this, we could for instance just cap the maximum delta, however that could make programs that depend on 'real time' go out of sync with long frames.
* Not processing long frames in the delta smoothing is equivalent to turning it off for one frame. As it is based on deltas, it should recover perfectly on the next frame, as if the long frame had never happened.
* We could alternatively use 64 bit math throughout the smoothing, but this is not necessary, smoothing is going to turn off anyway with such long frame times.
* Rather confusingly the bug occurs even when smoothing is off. This is because the `smooth` function is called _before_ it checks for the off condition, and the conversion to int32_t occurs in the function call.

### CODE REVIEW

File: main/main_timer_sync.cpp [hunk 1]
```diff
@@ -230,40 +230,50 @@ bool MainTimerSync::DeltaSmoother::fps_allows_smoothing(int p_delta) {
...
 }
 
-int MainTimerSync::DeltaSmoother::smooth_delta(int p_delta) {
+uint64_t MainTimerSync::DeltaSmoother::smooth_delta(uint64_t p_delta64) {
+	// Very important, ignore long deltas and pass them back unmodified.
+	// This is to deal with resuming after suspend for long periods.
+	// Delta is measured in ns, and will overflow with 32 bit integer after approx 36 mins.
+	if (p_delta64 > 1000000) {
+		return p_delta64;
+	}
```
Comment (akien-mga) [inline main/main_timer_sync.cpp:239]: In theory it could overflow and be unlucky enough to land in the `[0; 1000000[` range, no?

Comment (akien-mga) [reply main/main_timer_sync.cpp:239]: Discussed on chat, should be fine. It's the 32-bit int which is at risk of overflowing, not `p_delta64`.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
