### PR TITLE
Fix crash when dividing by 0 in Vector2/3i

### LINKED ISSUE #41125: Crash when trying to evaluate expression -  Vector2i(2,2) / Vector2i(1,0)
**Godot version:**
4.0.dev.custom_build. 69c81309cc786cc5702fb8d558636fb31f207971

**Issue description:**
When I type `Vector2i(2,2) / Vector2i(1,0)` in script then editor crash with this backtrace
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f72494ef210] (??:0)
[2] Vector2i::operator/(Vector2i const&) const (/mnt/Miecz/mojgodot/core/math/vector2.cpp:224)
[3] Variant::evaluate(Variant::Operator const&, Variant const&, Variant const&, Variant&, bool&) (/mnt/Miecz/mojgodot/core/variant_op.cpp:1117 (discriminator 1))
[4] GDScriptAnalyzer::reduce_binary_op(GDScriptParser::BinaryOpNode*) (/mnt/Miecz/mojgodot/modules/gdscript/gdscript_analyzer.cpp:1547)
[5] GDScriptAnalyzer::reduce_expression(GDScriptParser::ExpressionNode*) (/mnt/Miecz/mojgodot/modules/gdscript/gdscript_analyzer.cpp:1273)
[6] GDScriptAnalyzer::resolve_node(GDScriptParser::Node*) (/mnt/Miecz/mojgodot/modules/gdscript/gdscript_analyzer.cpp:749)
[7] GDScriptAnalyzer::resolve_suite(GDScriptParser::SuiteNode*) (/mnt/Miecz/mojgodot/modules/gdscript/gdscript_analyzer.cpp:856 (discriminator 2))
[8] GDScriptAnalyzer::resolve_function_body(GDScriptParser::FunctionNode*) (/mnt/Miecz/mojgodot/modules/gdscript/gdscript_analyzer.cpp:811)
[9] GDScriptAnalyzer::resolve_class_body(GDScriptParser::ClassNode*) (/mnt/Miecz/mojgodot/modules/gdscript/gdscript_analyzer.cpp:647)
[10] GDScriptAnalyzer::resolve_program() (/mnt/Miecz/mojgodot/modules/gdscript/gdscript_analyzer.cpp:3124)
[11] GDScriptAnalyzer::analyze() (/mnt/Miecz/mojgodot/modules/gdscript/gdscript_analyzer.cpp:3139)
[12] GDScriptLanguage::complete_code(String const&, String const&, Object*, List<ScriptCodeCompletionOption, DefaultAllocator>*, bool&, String&) (/mnt/Miecz/mojgodot/modules/gdscript/gdscript_editor.cpp:2364)
[13] ScriptTextEditor::_code_complete_script(String const&, List<ScriptCodeCompletionOption, DefaultAllocator>*, bool&) (/mnt/Miecz/mojgodot/editor/plugins/script_text_editor.cpp:705 (discriminator 2))
[14] ScriptTextEditor::_code_complete_scripts(void*, String const&, List<ScriptCodeCompletionOption, DefaultAllocator>*, bool&) (/mnt/Miecz/mojgodot/editor/plugins/script_text_editor.cpp:694)
[15] CodeTextEditor::_complete_request() (/mnt/Miecz/mojgodot/editor/code_editor.cpp:835)
[16] void call_with_variant_args_helper<CodeTextEditor>(CodeTextEditor*, void (CodeTextEditor::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (/mnt/Miecz/mojgodot/./core/callable_method_pointer.h:136 (discriminator 4))
[17] void call_with_variant_args<CodeTextEditor>(CodeTextEditor*, void (CodeTextEditor::*)(), Variant const**, int, Callable::CallError&) (/mnt/Miecz/mojgodot/./core/callable_method_pointer.h:158)
[18] CallableCustomMethodPointer<CodeTextEditor>::call(Variant const**, int, Variant&, Callable::CallError&) const (/mnt/Miecz/mojgodot/./core/callable_method_pointer.h:185)
[19] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (/mnt/Miecz/mojgodot/core/callable.cpp:54)
[20] Object::emit_signal(StringName const&, Variant const**, int) (/mnt/Miecz/mojgodot/core/object.cpp:1077)
[21] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/mnt/Miecz/mojgodot/core/object.cpp:1132)
[22] TextEdit::query_code_comple() (/mnt/Miecz/mojgodot/scene/gui/text_edit.cpp:6383 (discriminator 2))
[23] CodeTextEditor::_code_complete_timer_timeout() (/mnt/Miecz/mojgodot/editor/code_editor.cpp:824)
[24] void call_with_variant_args_helper<CodeTextEditor>(CodeTextEditor*, void (CodeTextEditor::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (/mnt/Miecz/mojgodot/./core/callable_method_pointer.h:136 (discriminator 4))
[25] void call_with_variant_args<CodeTextEditor>(CodeTextEditor*, void (CodeTextEditor::*)(), Variant const**, int, Callable::CallError&) (/mnt/Miecz/mojgodot/./core/callable_method_pointer.h:158)
[26] CallableCustomMethodPointer<CodeTextEditor>::call(Variant const**, int, Variant&, Callable::CallError&) const (/mnt/Miecz/mojgodot/./core/callable_method_pointer.h:185)
[27] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (/mnt/Miecz/mojgodot/core/callable.cpp:54)
[28] Object::emit_signal(StringName const&, Variant const**, int) (/mnt/Miecz/mojgodot/core/object.cpp:1077)
[29] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/mnt/Miecz/mojgodot/core/object.cpp:1132)
[30] Timer::_notification(int) (/mnt/Miecz/mojgodot/scene/main/timer.cpp:61 (discriminator 2))
[31] Timer::_notificationv(int, bool) (/mnt/Miecz/mojgodot/scene/main/timer.h:37 (discriminator 14))
[32] Object::notification(int, bool) (/mnt/Miecz/mojgodot/core/object.cpp:808)
[33] SceneTree::_notify_group_pause(StringName const&, int) (/mnt/Miecz/mojgodot/scene/main/scene_tree.cpp:818)
[34] SceneTree::idle(float) (/mnt/Miecz/mojgodot/scene/main/scene_tree.cpp:446 (discriminator 2))
[35] Main::iteration() (/mnt/Miecz/mojgodot/main/main.cpp:2333)
[36] OS_LinuxBSD::run() (/mnt/Miecz/mojgodot/platform/linuxbsd/os_linuxbsd.cpp:238)
[37] godot4(main+0x166) [0x19fca3c] (/mnt/Miecz/mojgodot/platform/linuxbsd/godot_linuxbsd.cpp:60)
[38] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f72494d00b3] (??:0)
[39] godot4(_start+0x2e) [0x19fc81e] (??:?)

```
This doesn't happens in Godot 3.2 due unavailability of Vector2i and Vector3i

### PR DESCRIPTION
**Pull request by qarmin**
Fixes #41125 

This PR just add specialized class to handle Vector3i and Vector2i because `b == 0` doesn't work with this types and need to be changed to `b.x == 0 || b.y == 0` or `b.x == 0 || b.y == 0 || b.z == 0`

I also added check inside `unlikely`, because this shouldn't happens to often

### CODE REVIEW

File: core/variant/variant_op.cpp [hunk 1]
```diff
@@ -233,6 +285,58 @@ class OperatorEvaluatorModNZ {
...
 
+template <>
+class OperatorEvaluatorModNZ<Vector2i, Vector2i, Vector2i> {
+public:
+	static void evaluate(const Variant &p_left, const Variant &p_right, Variant *r_ret, bool &r_valid) {
+		const Vector2i &a = *VariantGetInternalPtr<Vector2i>::get_ptr(&p_left);
+		const Vector2i &b = *VariantGetInternalPtr<Vector2i>::get_ptr(&p_right);
+		if (unlikely(b.x == 0 || b.y == 0)) {
+			r_valid = false;
+			*r_ret = "Module by zero error";
```
Comment (aaronfranke) [inline core/variant/variant_op.cpp:296]: Not sure "Module" is the best word here, perhaps "Modulus".

However, the `%` operator in C++ is not actually a modulus operator, it is a remainder operator. The difference is with negative numbers, `-1 % 3` is `-1` in C++, but would be `2` with modulus. So maybe instead this should be "Remainder" here, and `OperatorEvaluatorModNZ` could be `OperatorEvaluatorRemNZ`.

**Comment by bruvzg** [comment]
Note: #26131 crash is relevant for the `Vector2/3i` too. `Vector2i(-2147483648, 0) % Vector2i(-1, -1)` (vectors are 32-bit).

**Review by reduz — APPROVED** [review]

**Review by aaronfranke — APPROVED** [review]
Still don't think the name "module" is optimal, but that's a minor issue and we could later rename it consistently in a follow-up PR.

**Comment by mhilbrunner** [comment]
Thanks! Also sorry this took a bit to get reviewed and merged :)
