### PR TITLE
Don't instantiate `ColorPicker` in `EditorPropertyColor` constructor

### LINKED ISSUE #101569: Inspector loads slowly when there's many Color properties
### Tested versions

Reproducible in 4.4.dev7, and probably many versions earlier.

### System information

Windows 11

### Issue description

Inspectors (or project/editor settings) that contain many Color properties will load slowly. Additionally, they can be slow to switch away from.

### Steps to reproduce

For example, check out:
```
Editor Settings > Text Editor > Theme     (the worst example)
Editor Settings > Editors > 3D Gizmos
Editor Settings > Editors > Visual Editors
Project Settings > Debug > Shapes
```

### Minimal reproduction project (MRP)

Also, I made an MPR that has a Node with an exported `Array[Color]`, and some extra Color properties. Try repeatedly switching between the `Colorful` and `Colorless` nodes (make sure the Array is expanded).

[color_picker.zip](https://github.com/user-attachments/files/18418402/color_picker.zip)

### PR DESCRIPTION
**Pull request by larspet**
- Fixes #101569

The `EditorPropertyColor` constructor was using `ColorPickerButton::get_popup()` and `ColorPickerButton::get_picker()`, which was instantiating the ColorPicker without it being opened first. This led to 40+ pickers being instantiated in some cases.

This PR avoids calling those getters by using the `ColorPickerButton::picker_created` signal to setup the picker at a later stage.

On a debug build I get these results (quickly measured by eye & timer):
- Opening `Editor Settings > Text Editor > Theme`:
  - Master: 2 sec
  - This PR: instant
- Opening the MRP inspector:
  - Master: 1.5 sec
  - This PR: 0.2 sec (must be other Node properties making it not instant)
 
Switching away to another setting or inspector is faster now too, since there's no need to delete all the pickers.

### CODE REVIEW

**Comment by KoBeWi** [comment]
You can use `picker_created` signal.

**Comment by larspet** [comment]
> You can use `picker_created` signal.

I was considering that, but that signal is only emitted once right? I need the signal to be emitted every time it's opened. Unless I use `picker_created` to connect to `about_to_popup` (and also disconnect from `picker_created`). But that feels a little convoluted.

**Comment by KoBeWi** [comment]
You only need `picker_created` for the setup, the remaining code can be in `about_to_popup` like now.

File: editor/editor_properties.cpp [hunk 1]
```diff
@@ -2654,9 +2660,7 @@ EditorPropertyColor::EditorPropertyColor() {
 	add_child(picker);
 	picker->set_flat(true);
 	picker->connect("color_changed", callable_mp(this, &EditorPropertyColor::_color_changed));
-	picker->connect("popup_closed", callable_mp(this, &EditorPropertyColor::_popup_closed), CONNECT_DEFERRED);
-	picker->get_popup()->connect("about_to_popup", callable_mp(EditorNode::get_singleton(), &EditorNode::setup_color_picker).bind(picker->get_picker()));
-	picker->get_popup()->connect("about_to_popup", callable_mp(this, &EditorPropertyColor::_picker_opening));
+	picker->connect("picker_created", callable_mp(this, &EditorPropertyColor::_picker_created), CONNECT_ONE_SHOT);
```
Comment (KoBeWi) [inline editor/editor_properties.cpp:2663]: ONE_SHOT is not needed, because the signal is emitted only once anyway.

**Review by KoBeWi — APPROVED** [review]
Seems like `picker_created` was already used before, but was replaced in #62581.

For editor properties we could call `setup_color_picker()` only once. Also the setup method can be changed to take button instead, so popups are not created early (there is a few of them in the editor).

That's for later though, this fix is fine for now.

**Comment by Repiteo** [comment]
Thanks!

File: editor/editor_properties.cpp (hunk 1 above)
Comment (Repiteo) [reply editor/editor_properties.cpp:2663]: We can lump this in alongside the later fix you mentioned
