### PR TITLE
C#: Implement `IEquatable<>` and equality operators in `NodePath`

### LINKED ISSUE #72137: C# NodePath equality fails
### Godot version

v4.0.beta14.mono.official [28a24639c]

### System information

Windows 10

### Issue description

The C# implementation of NodePath == operator seems to only check identity.
Comparing two equal NodePath instances returns false.
GDScript allows comparison and I expected the same behavior in C#.

### Steps to reproduce

Create two NodePath instances with the same value and compare them.
See minimal reproduction project.

### Minimal reproduction project

[godot_dotnet_nodepath_eq.zip](https://github.com/godotengine/godot/files/10512940/godot_dotnet_nodepath_eq.zip)

### PR DESCRIPTION
**Pull request by RedworkDE**
- Implement `IEquatable<>` interface.
- Implement `==` and `!=` operators.
- Override `Equals` and `GetHashCode`.

Fixes #72137

### CODE REVIEW

File: modules/mono/glue/GodotSharp/GodotSharp/Core/NodePath.cs [hunk 1]
```diff
@@ -288,5 +288,37 @@ public bool IsAbsolute()
...
+
+        public override bool Equals(object obj)
+        {
+            return ReferenceEquals(this, obj) || (obj is NodePath other && Equals(other));
+        }
+
+        public override int GetHashCode()
+        {
+            var self = (godot_node_path)NativeValue;
+            return NativeFuncs.godotsharp_node_path_hash(self);
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/NodePath.cs:321]: `StringName` implementation is just `NativeValue.GetHashCode()`. Why do we need to do C++ interop here?

File: modules/mono/glue/GodotSharp/GodotSharp/Core/NodePath.cs [hunk 2]
```diff
@@ -288,5 +288,37 @@ public bool IsAbsolute()
...
+        }
+
+        public bool Equals(NodePath other)
+        {
+            if (other is null)
+                return false;
+            var self = (godot_node_path)NativeValue;
+            var otherNative = (godot_node_path)other.NativeValue;
+            return NativeFuncs.godotsharp_node_path_equals(self, otherNative).ToBool();
+        }
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/NodePath.cs:311]: This implementation also seems more costly than what we do in `StringName`. Can't we just compare `NativeValue.DangerousSelfRef`?

File: modules/mono/glue/GodotSharp/GodotSharp/Core/NodePath.cs (hunk 1 above)
Comment (RedworkDE) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/NodePath.cs:321]: Because the equals implementation isn't effectively just NativeValue.Equals and otherwise equal values could return different hash codes.

**Review by neikeq — APPROVED** [review]

File: modules/mono/glue/GodotSharp/GodotSharp/Core/NodePath.cs (hunk 2 above)
Comment (RedworkDE) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/NodePath.cs:311]: Because in `StringName` the whole point of StringNames is that all equal values are the same pointer and NativeValue, is that pointer, but for `NodePath` no such grantee exists, so we need to compare the pointer targets, which is native data, so we either need to implement the layout of that type or call into native code.

**Comment by akien-mga** [comment]
Thanks!
