### PR TITLE
Fix disabled slider highlighting

### LINKED ISSUE #78748: Disabled Sliders shouldn't be highlightable
### Godot version

v4.1.rc.custom_build [1b3bf4852]

### System information

Godot v4.1.rc (1b3bf4852) - Arch Linux #1 ZEN SMP PREEMPT_DYNAMIC Sat, 10 Jun 2023 00:35:19 +0000 - Vulkan (Compatibility) - AMD Radeon R9 380 Series (tonga, LLVM 15.0.7, DRM 3.52, 6.3.7-zen1-1-zen) () - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

Sliders that are set to *not* editable will still be highlighted on hover, even if you cannot interact with them.

This seems counterintuitive (I'd expect to be able to interact with something that lights up on hover), and inconsistent (disabled buttons do not get highlighted on hover).

Screencap of hover behaviour:

https://github.com/godotengine/godot/assets/1187609/af9466ad-37d5-4d13-ace5-b6268166e2b6

In Godot 3, uneditable sliders behaved as you would expect and did not get highlighted on hover, same as buttons.

### Steps to reproduce

Add HSlider or VSlider, hover over with mouse.

### Minimal reproduction project

None.

### PR DESCRIPTION
**Pull request by NiskashY**
Fix #78748

Added missing check for the grabber_area.

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally, it works.

https://github.com/godotengine/godot/assets/180032/23a62f24-3ad9-4bf2-8555-36d583f055e7

**Testing project:** [test_pr_78776.zip](https://github.com/godotengine/godot/files/11891010/test_pr_78776.zip)

**Comment by KoBeWi** [comment]
Maybe it would be better to change `highlighted` instead?
```C++
bool highlighted = editable && (mouse_inside || has_focus());
```

**Comment by NiskashY** [comment]
> Maybe it would be better to change `highlighted` instead?
> 
> ```c++
> bool highlighted = editable && (mouse_inside || has_focus());
> ```
> 
> Right now it's used only once, but technically it has wrong value if the Slider should never be highlighted when uneditable.

Seems good to me.
I propose to separate focus status `(mouse_inside || has_focus())' from highlighted

**Comment by NiskashY** [comment]
> Maybe it would be better to change `highlighted` instead?
> 
> ```c++
> bool highlighted = editable && (mouse_inside || has_focus());
> ```
> 
> Right now it's used only once, but technically it has wrong value if the Slider should never be highlighted when uneditable.

Seems good to me.
I propose to separate focused status ('mouse_inside || has_focus())' from highlighted status

so we get: 
> ```c++
> bool focused = mouse_inside || has_focus();
> bool highlighted = editable && focused;
> // same code here
> if (highlighted) {
>     graber_area = ...

Would that be okey? 
> ```

**Comment by KoBeWi** [comment]
`mouse_inside` means the Slider is hovered, not focused, so it wouldn't be accurate.

**Comment by YuriSizov** [comment]
@NiskashY Will you be willing to make the requested changes?

**Comment by NiskashY** [comment]
@YuriSizov Make changes KoBeWi suggested?
```c++
bool highlighted = editable && (mouse_inside || has_focus());
```

**Comment by YuriSizov** [comment]
> Make changes KoBeWi suggested?

Yep!

File: scene/gui/slider.cpp [hunk 1]
```diff
@@ -255,8 +255,8 @@ void Slider::_notification(int p_what) {
 
 			Ref<StyleBox> style = theme_cache.slider_style;
 			Ref<Texture2D> tick = theme_cache.tick_icon;
-
-			bool highlighted = mouse_inside || has_focus();
+            
+            bool highlighted = editable && (mouse_inside || has_focus());
```
Comment (YuriSizov) [inline scene/gui/slider.cpp:259]:
```suggestion

			bool highlighted = editable && (mouse_inside || has_focus());
```

The indentation must be done with tabs.

**Comment by YuriSizov** [comment]
Also, please make sure to squash your commits into one. Make sure that the final commit has a short but descriptive message (the title of this PR is a good option). See [this documentation](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase), if you need help with squashing.

**Review by KoBeWi — APPROVED** [review]

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.1.

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.4.
