### PR TITLE
Fix file logging log rotation

### LINKED ISSUE #97066: File logging log rotation is broken.
### Tested versions

v4.3.stable.arch_linux
v4.2.2.stable.official [15073afe3]

### System information

Godot v4.3.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (nvidia; 560.35.03) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

When file `debug/file_logging/enable_file_logging` is enabled and `debug/file_logging/max_log_files` is > 1, files should be logged to the set directory (default `"user://logs/godot.log"`) starting with `godot.log` (most recent run) and keeping previous runs as `godot{datetimestamp}.log`. Previously this would correctly maintain the most recent logs but since ~4.3 it has stopped working. Now once the first `debug/file_logging/max_log_files` have been generated, only the newest (`godot.log`) gets correctly replaced and the oldest n-1 files are kept forever.

### Steps to reproduce

Enable file logging add some print statements and run the game 6 times.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by pafuent**
Fixes #97066

`RBSet` were used on `RotatedFileLogger` because it guarantees that iterating it is done via `operator<`. This is important because `RotatedFileLogger` depends on this behavior to delete the oldest log file.
On #61194 `HashSet` was added and all `RBSet` uses were replaced by `HashSet`.
When that happened, the iteration in order is guaranteed to be the insertion order, wich made that `RotatedFileLogger` delete the newest log file. As a bonus, I added unit test for `RotatedFileLogger` and `CompositeLogger`.

### CODE REVIEW

**Comment by pafuent** [comment]
Friendly remainder

File: tests/core/io/test_logger.h [hunk 1]
```diff
@@ -0,0 +1,174 @@
...
+#define TEST_LOGGER_H
+
+#include "core/io/dir_access.h"
+#include "core/io/logger.h"
+#include "tests/test_macros.h"
+
+// #include "drivers/unix/file_access_unix_pipe.h"
+// Ref<FileAccessUnixPipe> _stdout;
+// _stdout.instantiate();
+// main_pipe->open_existing(pipe_out[0], pipe_in[1], p_blocking);
```
Comment (Calinou) [inline tests/core/io/test_logger.h:41]: Is this commented out code needed for anything? If not, it should probably be removed or there should be an explanation as for why it's here.

File: tests/core/io/test_logger.h [hunk 2]
```diff
@@ -0,0 +1,174 @@
...
+
+namespace TestLogger {
+
+const int sleep_duration = 1200000;
```
Comment (Calinou) [inline tests/core/io/test_logger.h:45]:
```suggestion
constexpr int sleep_duration = 1200000;
```

Also, can we use a shorter sleep duration? This is 1.2 seconds, which can impact test runtimes significantly since we test 6 rotations in total (8 seconds).

File: tests/core/io/test_logger.h (hunk 1 above)
Comment (pafuent) [reply tests/core/io/test_logger.h:41]: 🤦🏼‍♂️ I forgot to remove this when I submitted the PR

File: tests/core/io/test_logger.h (hunk 2 above)
Comment (pafuent) [reply tests/core/io/test_logger.h:45]: I know 1.2 seconds is a lot, but the timestamp format that is added to the log files when are rotated is `vformat("%sT%02d:%02d:%02d", timestamp, dt.hour, dt.minute, dt.second);` which is up to seconds. So in order to get a new file name more than a second must pass between file rotations.

**Review by Calinou — APPROVED** [review]
Code looks good to me.

File: core/io/logger.cpp [hunk 3]
```diff
@@ -129,7 +130,7 @@ void RotatedFileLogger::clear_old_backups() {
 
 	da->list_dir_begin();
 	String f = da->get_next();
-	HashSet<String> backups;
+	RBSet<String> backups;
```
Comment (akien-mga) [inline core/io/logger.cpp:133]: I'd suggest adding a short comment to clarify what RBSet specifically is needed here, so this doesn't get refactored back by mistake.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
