### PR TITLE
Fix various small issues with PopupMenu

### LINKED ISSUE #44894: Multiple visual glitches with 'PopupMenu'
**Godot version:**
950dedb

**Issue description:**
Here's a comparison of `PopupMenu` between the 3.2 and master versions:
popups

- [x] Items with no text nor icon get completely flattened, even if those that are checkable. Fixed by #46081.
- [x] The highlight indicator has its sides cutoff. Fixed by #44905.
- [x] The popup's width does not fit its button if bigger. Fixed by #44906.

### PR DESCRIPTION
**Pull request by YeldhamDev**
- Textless items aren't completely squished anymore.
- Check icon's height are now taken into account.
  - And so separators as well!

**Before / After:**
Screenshot_20210216_004438

I actually stumbled into a bug with `StyleBoxLine` while doing this, but the fix can also be applied to 3.2.*, so it will be done in another PR.

Fixes #44894.

### CODE REVIEW

File: scene/gui/popup_menu.cpp [hunk 1]
```diff
@@ -531,19 +553,20 @@ void PopupMenu::_draw_items() {
...
-					labeled_separator_left->draw(ci, Rect2(item_ofs + Point2(0, Math::floor((h - sep_h) / 2.0)), Size2(MAX(0, text_left - item_ofs.x), sep_h)));
+					labeled_separator_left->draw(ci, Rect2(item_ofs + Point2(0, sep_ofs), Size2(MAX(0, text_left - item_ofs.x), sep_h)));
 				}
 				if (text_right < display_width) {
-					labeled_separator_right->draw(ci, Rect2(Point2(text_right, item_ofs.y + Math::floor((h - sep_h) / 2.0)), Size2(MAX(0, display_width - text_right), sep_h)));
+					labeled_separator_right->draw(ci, Rect2(Point2(text_right, item_ofs.y + sep_ofs), Size2(MAX(0, display_width - text_right), sep_h)));
 				}
 			} else {
-				separator->draw(ci, Rect2(item_ofs, Size2(display_width, sep_h)));
+				separator->draw(ci, Rect2(item_ofs + Point2(0, sep_ofs), Size2(display_width, sep_h)));
```
Comment (EricEzaM) [inline scene/gui/popup_menu.cpp:569]: This addition should be removed to be in line with the changes from #45704. Adding this back in makes the separator margin uneven on the top and bottom sides.

uneven separator

**Review by EricEzaM — CHANGES_REQUESTED** [review]
Just one thing below to bring it to visual parity with a recent PR.

Otherwise looks good, the item height method was definitely needed!

File: scene/gui/popup_menu.cpp (hunk 1 above)
Comment (YeldhamDev) [reply scene/gui/popup_menu.cpp:569]: That is actually a bug with `StyleBoxLine` itself, that has been solved here: #46082

Comment (EricEzaM) [reply scene/gui/popup_menu.cpp:569]: Oh, ok then. It is a minor issue anyway. If it crops up again it can be addressed then.

**Review by EricEzaM — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
