### PR TITLE
Make `EditorProperty` and its child `EditorProperty` behave like sibling nodes when handling mouse events

### LINKED ISSUE #103578: Material Inspector Panel Scrolls Down Erratically
### Tested versions

Godot 4.3 .Net
Godot 4.4 .Net

### System information

Win10 22H2 x64
RTX 3070, Driver 572.60

### Issue description
Clicking any setting in the Material Inspector Panel, then clicking anything else in the Material Inspector Panel causes the panel to scroll down by a large amount. This becomes more annoying if the Inspector Panel is made smaller.

Issue occurs in Normal Mode, in Self Contained Mode, and even after setting layout to default.
https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html#self-contained-mode

Issue does NOT occur if the Inspector Panel is Floating.

### Steps to reproduce

1) Add any node that supports a material, then add a material to the node. For example, add CSGBox with a StandardMaterial3D.
2) Click on the StandardMaterial to view its properties in the Inspector Panel.
3) Open up any section in the Material Inspector Panel. For example, I will open up Transparency.
4) Click on any dropdown within Transparency. For example, Cull Mode's dropdown. Close the dropdown by selecting a dropdown option, or clicking outside the dropdown.
5) Click again anywhere in the Material Inspector Panel that is NOT a setting. For example, click on the actual word "Cull Mode". This will trigger the bug -> The inspector scrolls down by a large amount.
6) This may not seem like a big deal, but let's say you want to change Cull Mode's dropdown, and then the Albedo settings.
You click the Cull Mode dropdown and choose your setting. You then scroll down to click on Albedo section to expand it. Clicking on Albedo section will cause the inspector to scroll down by a large amount, forcing the user to scroll back up to Albedo.

Perform the above with a floating Inspector Panel, and the bug will not occur.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Rindbee**
Let `EditorProperty::gui_input()` no longer handle mouse events that occur in the child EditorProperty rect (`bottom_child_rect`).

This is another way to solve issues like #88848 , but avoids #100695 .

Bugsquad edit:
Fix #103578

### CODE REVIEW

**Comment by KoBeWi** [comment]
What case wasn't solved?
The original fix was meant as workaround, this is a proper fix, but it's more risky.

**Comment by AThousandShips** [comment]
Also we are in the RC phase and we merge only critical fixes currently

**Comment by JekSun97** [comment]
> What case wasn't solved?

I can still see the inspector shifting abruptly when expanding some properties, such as when editing a material.

https://github.com/user-attachments/assets/21b75833-ec03-45c7-ba98-075be7466e57

**Comment by KoBeWi** [comment]
Tested this PR and while folding now works properly, toggling some properties can still cause jumps:

https://github.com/user-attachments/assets/ef6ad1f7-e7c3-4905-b841-f040fe673f6e

It's caused by inspector refresh though, and the scroll ends up in the same position, so it's fine.

File: editor/editor_properties.cpp [hunk 1]
```diff
@@ -3302,12 +3302,11 @@ void EditorPropertyResource::update_property() {
 				sub_inspector->set_read_only(is_read_only());
 				sub_inspector->set_use_folding(is_using_folding());
 
-				sub_inspector->set_draw_focus_border(false);
```
Comment (KoBeWi) [inline editor/editor_properties.cpp:3305]: This leads to double borders.
image

File: editor/editor_inspector.cpp [hunk 2]
```diff
@@ -918,6 +918,9 @@ void EditorProperty::gui_input(const Ref<InputEvent> &p_event) {
 
 	if (me.is_valid()) {
 		Vector2 mpos = me->get_position();
+		if (bottom_child_rect.has_point(mpos)) {
+			return; // Makes child EditorProperties behave like sibling nodes.
```
Comment (KoBeWi) [inline editor/editor_inspector.cpp:922]: How does that work exactly?

Comment (Rindbee) [reply editor/editor_inspector.cpp:922]: Just when handling mouse events.  

In this case, when clicking on the `Label` of a child `EditorProperty`, we don't want the parent `EditorProperty`'s menu to pop up (RMB), but we want the **root** inspector to have focus (LMB).

File: editor/editor_properties.cpp (hunk 1 above)
Comment (Rindbee) [reply editor/editor_properties.cpp:3305]: Forget that it will also draw when the child control has focus. Has been modified.

**Review by KoBeWi — APPROVED** [review]
Seems to work correctly.

This also reverts #101768 and #102775

**Comment by Repiteo** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.4.1.
