### PR TITLE
Disable video driver option in editor

### LINKED ISSUE #36190: Godot crashes on launch after switching to GLES2 in editor
**Godot version:**
5c3944e7da9ca72077cb5348fadc86347904838c

**OS/device including version:**
Microsoft Windows 10 Pro 10.0.18363 Build 18363

**Issue description:**
Crash occurs when switch from Vulkan to GLES2 in editor.

The option to create a GLES2 project was disabled in #36167, but the Vulkan/GLES2 switcher is still present in editor.

**Steps to reproduce:**
1. Open new Vulkan project.
2. After editor opens, use drop down in top right corner of editor window to switch to GLES2.
3. Restart editor.

Crash

```
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] ???
[1] Rasterizer::create (E:\code\godot\servers\visual\rasterizer.cpp:68)
[2] VisualServerRaster::VisualServerRaster (E:\code\godot\servers\visual\visual_server_raster.cpp:252)
[3] OS_Windows::initialize (E:\code\godot\platform\windows\os_windows.cpp:1485)
[4] Main::setup2 (E:\code\godot\main\main.cpp:1222)
[5] Main::setup (E:\code\godot\main\main.cpp:1164)
[6] widechar_main (E:\code\godot\platform\windows\godot_windows.cpp:150)
[7] _main (E:\code\godot\platform\windows\godot_windows.cpp:184)
[8] main (E:\code\godot\platform\windows\godot_windows.cpp:196)
[9] __scrt_common_main_seh (d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[10] BaseThreadInitThunk
-- END OF BACKTRACE --
```

**Minimal reproduction project:**
Empty project.

### PR DESCRIPTION
**Pull request by drichardson**
Disable video driver option in editor since switching to GLES2 would currently cause a crash on restart.

Fixes #36190.

### CODE REVIEW

**Comment by drichardson** [comment]
This is just a temporary fix to prevent users from creating a project that cannot be opened. It should be reverted when GLES2 support is stable.

**Comment by clayjohn** [comment]
I think it would be best to comment on both lines "TODO re-enable when GLES2 is ported"

This will make it easier to find when we need to re-enable

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -6360,7 +6360,7 @@ EditorNode::EditorNode() {
 	stop_button->set_icon(gui_base->get_icon("Stop", "EditorIcons"));
 	stop_button->connect("pressed", this, "_menu_option", make_binds(RUN_STOP));
 	stop_button->set_tooltip(TTR("Stop the scene."));
-	stop_button->set_disabled(true);
+	stop_button->set_disabled(true); // Disable due to issue 36190 until switching to GLES2 works again.
```
Comment (YeldhamDev) [inline editor/editor_node.cpp]: This comment is in the wrong place.

**Review by clayjohn — APPROVED** [review]

**Comment by drichardson** [comment]
Sorry, I'm a hot mess today. I accidentally put the comment on the wrong line (stop button) and then accidentally removed the existing stop button disable in on of my rebases.

Latest version should be good.

Changed comment to TODO and put it on it's own line now.

**Comment by drichardson** [comment]
First commit woes. I didn't read the code formatting guidelines. Tab/space problem. Fixing now.

**Comment by akien-mga** [comment]
Thanks!
