### PR TITLE
Fix AudioStreamPlayer `get_playback_position()` for web build

### LINKED ISSUE #95128: AudioStreamPlayer not returning position on get_playback_position() on HTML5
### Tested versions

-reproducible in v4.3.beta3.official [82cedc83c]
-not reproducible in v4.2.2.stable.official [15073afe3]

### System information

Windows 11 Godot v4.3.beta3.official [82cedc83c]

### Issue description

HTML5 export returns same value no matter what position song is at while using AudioStreamMP3, changed the AudioStreamPlayer type to the new synchronized and now i am getting correct results on exported project.  

Side note, it seems that it always returning 0.00290249427781 regardless of which song is played.

### Steps to reproduce

Create new project and add AudioStreamPlayer and Label to scene
Attach mp3 to AudioStreamPlayer and set autoplay to true
Create script that updates label.text with AudioStreamPlayer.get_playback_positon() in _process
Export to web build and test

### Minimal reproduction project (MRP)

This is a fairly easy project to create..

### PR DESCRIPTION
**Pull request by yahkr**
fixes https://github.com/godotengine/godot/issues/95128

get_playback_position was missing a js hookup with audio samples updates

### CODE REVIEW

**Comment by adamscott** [comment]
This fix is interesting. But it takes for granted that the browser will play the sample without hitch. Technically, I think that we should rather implement something like mentioned here: https://github.com/WebAudio/web-audio-api/issues/2397#issuecomment-1193254844

With that solution, we get a more precise position of the playhead, not just an approximation.

**Comment by yahkr** [comment]
> This fix is interesting. But it takes for granted that the browser will play the sample without a hitch. Technically, I think that we should rather implement something like mentioned here: [WebAudio/web-audio-api#2397 (comment)](https://github.com/WebAudio/web-audio-api/issues/2397#issuecomment-1193254844)
> 
> With that solution, we get a more precise position of the playhead, not just an approximation.

Definitely looks like a tricky implementation with how godot-processor, wondering if this approximation is a good fix for the moment

**Comment by yahkr** [comment]
Looking more into this, and maybe im just missing something.  But when audio is or isn't playing I'm noticing that this chunk of code is always running.  Is this expected? Maybe i'm looking in the wrong place entirely for how to tackle this according to that possible solution... 

**audio.worklet.js**
```js
const process_output = GodotProcessor.array_has_data(outputs);
		if (process_output) {
			const output = outputs[0];
			const chunk = output[0].length * output.length;
			if (this.output_buffer.length !== chunk) {
				this.output_buffer = new Float32Array(chunk);
			}
			if (this.output.data_left() >= chunk) {
				this.output.read(this.output_buffer);
				this.position += outputs[0].length;
				this.port.postMessage({ 'cmd': 'position', 'data': this.position });
				this.port.postMessage({ cmd: 'debug', type: 'output', data: output });
				GodotProcessor.write_output(output, this.output_buffer);
				if (!this.threads) {
					this.port.postMessage({ 'cmd': 'read', 'data': chunk });
				}
			} else {
				// this.port.postMessage('Output buffer has not enough frames! Skipping output frame.'); // Uncomment this line to debug output buffer.
			}
		}
```

These are the only newly added lines.   
```js

				this.position += outputs[0].length;
				this.port.postMessage({ 'cmd': 'position', 'data': this.position });
				this.port.postMessage({ cmd: 'debug', type: 'output', data: output });
```

**Comment by yahkr** [comment]
@adamscott Gave it a shot... basically constructing a new AudioWorklet for each SampleNode to keep track of its playback by parsing the incoming buffer length.

```js
process(inputs, _outputs, _parameters) {
		if (inputs.length > 0) {
			const input = inputs[0];
			if (input.length > 0) {
				const channel = input[0];
				this.position += input[0].length;
				this.port.postMessage({'cmd': 'position', 'data': this.position});
				return true;
			}
		}
		return true;
	}
```
image

File: platform/web/js/libs/library_godot_audio.js [hunk 1]
```diff
@@ -1625,6 +1663,22 @@ const _GodotAudio = {
 		return Number(GodotAudio.sampleNodes.has(playbackObjectId));
 	},
 
+	godot_audio_get_sample_playback_position__proxy: 'sync',
+	godot_audio_get_sample_playback_position__sig: 'vii',
```
Comment (adamscott) [inline platform/web/js/libs/library_godot_audio.js:1667]:
```suggestion
	godot_audio_get_sample_playback_position__sig: 'vi',
```
There is only one parameter to your function here.

File: platform/web/js/libs/library_godot_audio.js [hunk 2]
```diff
@@ -588,6 +601,24 @@ class SampleNode {
...
+			'godot-position-reporting-processor'
+		);
+		worklet.port.onmessage = (event) => {
+			if (event.data['cmd'] === 'position') {
+				this._playback_position = (parseInt(event.data.data, 10) / this.getSample().sampleRate) + this.offset;
+			}
+		};
+		this._source.connect(worklet);
+		return worklet;
+	}
```
Comment (adamscott) [inline platform/web/js/libs/library_godot_audio.js:620]:
```suggestion
	createPositionWorklet() {
		const worklet = new AudioWorkletNode(
			GodotAudio.ctx,
			'godot-position-reporting-processor'
		);
		worklet.port.onmessage = (event) => {
			switch (event.data['type']) {
				case 'position':
					this._playbackPosition = (parseInt(event.data.data, 10) / this.getSample().sampleRate) + this.offset;
					break;
			}
		};
		return worklet;
	}
```

File: platform/web/js/libs/library_godot_audio.js [hunk 3]
```diff
@@ -453,6 +455,9 @@ class SampleNode {
 		const bus = GodotAudio.Bus.getBus(params.busIndex);
 		const sampleNodeBus = this.getSampleNodeBus(bus);
 		sampleNodeBus.setVolume(options.volume);
+
+		/** @type {AudioWorkletProcessor | null} */
+		this._position_worklet = this.getWorklet();
```
Comment (adamscott) [inline platform/web/js/libs/library_godot_audio.js:460]:
```suggestion
		this._positionWorklet = this.createPositionWorklet();
		this._source.connect(this._position_worklet);
```

File: platform/web/js/libs/library_godot_audio.js [hunk 4]
```diff
@@ -424,6 +424,8 @@ class SampleNode {
 		/** @type {number} */
 		this.offset = options.offset ?? 0;
 		/** @type {number} */
+		this._playback_position = options.offset;
```
Comment (adamscott) [inline platform/web/js/libs/library_godot_audio.js:427]:
```suggestion
		this._playbackPosition = options.offset;
```

File: platform/web/js/libs/library_godot_audio.js [hunk 5]
```diff
@@ -463,6 +468,14 @@ class SampleNode {
 		return this._playbackRate;
 	}
 
+	/**
+	 * Gets the playback position.
+	 * @returns {number}
+	 */
+	getPlaybackPosition() {
+		return this._playback_position;
```
Comment (adamscott) [inline platform/web/js/libs/library_godot_audio.js:476]:
```suggestion
		return this._playbackPosition;
```

File: platform/web/js/libs/library_godot_audio.js [hunk 6]
```diff
@@ -618,6 +655,7 @@ class SampleNode {
 	 */
 	_resetSourceStartTime() {
 		this._sourceStartTime = GodotAudio.ctx.currentTime;
+		this._position_worklet.port.postMessage({ 'cmd': 'reset' });
```
Comment (adamscott) [inline platform/web/js/libs/library_godot_audio.js:658]:
```suggestion
		this._positionWorklet.port.postMessage({ 'type': 'reset' });
```

File: platform/web/js/libs/library_godot_audio.js [hunk 7]
```diff
@@ -609,6 +640,12 @@ class SampleNode {
 		}
 		this._sampleNodeBuses.clear();
 
+		if (this._position_worklet) {
+			this._position_worklet.disconnect();
+			this._position_worklet.port.onmessage = null;
+			this._position_worklet = null;
+		}
```
Comment (adamscott) [inline platform/web/js/libs/library_godot_audio.js:647]:
```suggestion
		if (this._positionWorklet) {
			this._positionWorklet.disconnect();
			this._positionWorklet.port.onmessage = null;
			this._positionWorklet = null;
		}
```

**Review by adamscott — COMMENTED** [review]
Great work! Didn't test it yet, I'm doing this right now.
If it works well, I'll try to push the fix for 4.3.

There's only a few renames and nitpicks, but globally, it's a great implementation. Thanks!

**Comment by yahkr** [comment]
> You don't have to make me a co-author! ;) Please, keep the authorship.

Will do final cleanup and force push.  Appreciate your help!

**Comment by adamscott** [comment]
I'm having some issues when running with the Remote Debugger, I'm checking this out.

Capture d’écran, le 2024-08-08 à 10 27 26

**Comment by yahkr** [comment]
> I'm having some issues when running with the Remote Debugger, I'm checking this out.

Any errors in the console? Haven't seen this one yet. Currently running with remote debug and all appears working for me at least.

**Comment by adamscott** [comment]
So I figured it out. It's a race condition I get on Safari on my MacBook Pro.

So it's currently by pure luck that it works on your machine, because on mine, we try to create the `AudioWorklet` before it is properly registered.

**Comment by yahkr** [comment]
> So I figured it out. It's a race condition I get on Safari on my MacBook Pro.
> 
> So it's currently by pure luck that it works on your machine, because on mine, we try to create the `AudioWorklet` before it is properly registered.

ah thats unfortunate, yeah i was worried about that with the async addModule aspect. hmm...   a previous attempt I had was like this:

```js
		const bus = GodotAudio.Bus.getBus(params.busIndex);
		const sampleNodeBus = this.getSampleNodeBus(bus);
		sampleNodeBus.setVolume(options.volume);

		this._start = options.start;
		this.getWorklet(() => {
			this._finalize();
		});
	}
	
	_finalize(){
		this._source.connect(this._position_worklet);
		if(this._start){
			this.start();
			isStarted = true;
		}
	}
```
```js
getWorklet(callback) {
		const path = GodotConfig.locate_file('godot.audio.worklet.js');
		GodotAudio.ctx.audioWorklet
			.addModule(path)
			.then(() => {
				this._position_worklet = new AudioWorkletNode(
					GodotAudio.ctx,
					'position-reporting-processor'
				);
				if (typeof callback === 'function') {
					callback();
				}
				this._position_worklet.port.onmessage = (event) => {
					if (event.data['cmd'] === 'position') {
						this._playback_position = (parseInt(event.data.data) / this.getSample().sampleRate) + this.offset;
					}
				}
			})
			.catch((error) => {
				console.error('Error loading worklet module:', error);
			});
	}
```

Obviously needs cleaned up, but should prevent the starting of a node until this worklet is initialized?  Or atleast check if its been added yet if there is a way.

**Comment by yahkr** [comment]
@adamscott when you have a moment, feel free to give my most recent push a shot.

File: platform/web/js/libs/audio.worklet.js [hunk 8]
```diff
@@ -211,3 +211,34 @@ class GodotProcessor extends AudioWorkletProcessor {
...
+			const type = event.data['type'];
+			this.parse_message(type);
+		};
+	}
+
+	parse_message(p_type) {
+		if (p_type === 'reset') {
+			this.position = 0;
+		}
+	}
```
Comment (adamscott) [inline platform/web/js/libs/audio.worklet.js:229]: A switch case here could work better.

File: platform/web/js/libs/library_godot_audio.js [hunk 9]
```diff
@@ -453,6 +460,18 @@ class SampleNode {
...
+			/** @type {AudioWorkletProcessor | null} */
+			this._positionWorklet = await this.createPositionWorklet(true);
+			if (this._positionWorklet && !this.isCanceled) {
+				this._source.connect(this._positionWorklet);
+				if (options.start) {
+					this.start();
+					this.isStarted = true;
+				}
+			}
+		})();
```
Comment (adamscott) [inline platform/web/js/libs/library_godot_audio.js:474]: Either wrap the code with a try/catch, or better, add a `.catch()` to the async call.

File: platform/web/js/libs/library_godot_audio.js [hunk 10]
```diff
@@ -453,6 +460,18 @@ class SampleNode {
 		const bus = GodotAudio.Bus.getBus(params.busIndex);
 		const sampleNodeBus = this.getSampleNodeBus(bus);
 		sampleNodeBus.setVolume(options.volume);
+
```
Comment (adamscott) [inline platform/web/js/libs/library_godot_audio.js:463]: I would add this:

```javascript
			/** @type {AudioWorkletProcessor | null} */
			this._positionWorklet = null;
```

And then remove the typing in the async function.

File: platform/web/js/libs/library_godot_audio.js [hunk 11]
```diff
@@ -453,6 +460,18 @@ class SampleNode {
...
+		(async () => {
+			/** @type {AudioWorkletProcessor | null} */
+			this._positionWorklet = await this.createPositionWorklet(true);
```
Comment (adamscott) [inline platform/web/js/libs/library_godot_audio.js:466]: I would add a `this.isCanceled` check inside the async function before doing anything. Async functions executed later after the main loop.

File: platform/web/js/libs/library_godot_audio.js [hunk 12]
```diff
@@ -588,18 +615,55 @@ class SampleNode {
...
+				case 'position':
+					this._playbackPosition = (parseInt(event.data.data, 10) / this.getSample().sampleRate) + this.offset;
+					break;
+				default:
+				// do nothing
+				}
+			};
+		} catch (e) {
+			if (retry) {
+				const path = GodotConfig.locate_file('godot.audio.worklet.js');
```
Comment (adamscott) [inline platform/web/js/libs/library_godot_audio.js:641]: We need to make another file, as the current worklet is made for threaded audio. I suggest `godot.audio.position.worklet.js`.

File: platform/web/js/libs/library_godot_audio.js [hunk 13]
```diff
@@ -588,18 +615,55 @@ class SampleNode {
 		return this._sampleNodeBuses.get(bus);
 	}
 
+	/**
+	 * Sets up and assigns AudioWorkletProcessor used to track playback position.
+	 * @param {boolean} Whether or not attempt to add the worklet module if it hasn't been.
+	 * @returns {AudioWorkletProcessor}
+	 */
+	async createPositionWorklet(retry) {
```
Comment (adamscott) [inline platform/web/js/libs/library_godot_audio.js:623]: Instead of having a function that does a retry, I would put the try catch in the anonymous async function.

File: platform/web/js/libs/library_godot_audio.js [hunk 14]
```diff
@@ -588,18 +615,55 @@ class SampleNode {
 		return this._sampleNodeBuses.get(bus);
 	}
 
+	/**
+	 * Sets up and assigns AudioWorkletProcessor used to track playback position.
+	 * @param {boolean} Whether or not attempt to add the worklet module if it hasn't been.
```
Comment (adamscott) [inline platform/web/js/libs/library_godot_audio.js:620]:
```suggestion
	 * @param {boolean} retry Whether or not attempt to add the worklet module if it hasn't been.
```

File: platform/web/js/libs/library_godot_audio.js [hunk 15]
```diff
@@ -1252,15 +1323,14 @@ const _GodotAudio = {
...
 			GodotAudio.SampleNode.stopSampleNode(playbackObjectId);
-			const sampleNode = GodotAudio.SampleNode.create(
+			GodotAudio.SampleNode.create(
 				{
 					busIndex,
 					id: playbackObjectId,
 					streamObjectId,
 				},
 				startOptions
 			);
```
Comment (adamscott) [inline platform/web/js/libs/library_godot_audio.js:1333]: Why the change here?

File: platform/web/js/libs/library_godot_audio.js [hunk 16]
```diff
@@ -1625,6 +1696,22 @@ const _GodotAudio = {
 		return Number(GodotAudio.sampleNodes.has(playbackObjectId));
 	},
 
+	godot_audio_get_sample_playback_position__proxy: 'sync',
+	godot_audio_get_sample_playback_position__sig: 'if',
```
Comment (adamscott) [inline platform/web/js/libs/library_godot_audio.js:1700]:
```suggestion
	godot_audio_get_sample_playback_position__sig: 'ii',
```

**Review by adamscott — COMMENTED** [review]
Good idea, but I have a few changes to make to your code.

File: platform/web/js/libs/library_godot_audio.js (hunk 15 above)
Comment (yahkr) [reply platform/web/js/libs/library_godot_audio.js:1333]: before it was creating a const sampleNode, and then calling .start() . I didnt want it to start the node before the position worklet had been connected.  Just to ensure it wasnt getting out of sync

File: platform/web/js/libs/library_godot_audio.js [hunk 17]
```diff
@@ -588,18 +615,55 @@ class SampleNode {
...
+				GodotAudio.ctx,
+				'godot-position-reporting-processor'
+			);
+			worklet.port.onmessage = (event) => {
+				switch (event.data['type']) {
+				case 'position':
+					this._playbackPosition = (parseInt(event.data.data, 10) / this.getSample().sampleRate) + this.offset;
+					break;
+				default:
+				// do nothing
```
Comment (adamscott) [inline platform/web/js/libs/library_godot_audio.js:636]:
```suggestion
				// Do nothing.
```

File: platform/web/js/libs/library_godot_audio.js (hunk 16 above)
Comment (adamscott) [reply platform/web/js/libs/library_godot_audio.js:1700]: I edited my suggested change: you actually return a double.

**Comment by yahkr** [comment]
I really need to fix my local linter for js.  Sorry for the push spam.  Hopefully these latest changes are more inline with what you were thinking?

**Comment by yahkr** [comment]
Hmm, running into some other issues on creation. will dig in

File: platform/web/js/libs/library_godot_audio.js [hunk 18]
```diff
@@ -453,6 +462,36 @@ class SampleNode {
...
+	 * Finalizes Node setup and connects PositionWorklet node
+	 */
+	finalize(options) {
+		if (this._positionWorklet) {
+			this._source.connect(this._positionWorklet);
+			if (options.start) {
+				this.start();
+				this.isStarted = true;
+			}
+		}
```
[the remark this answers is not in the document]
Comment (yahkr) [reply platform/web/js/libs/library_godot_audio.js:494]: Fair, was just trying to avoid duplicating the code like this, but i guess it not much:

```js
try {
			this._positionWorklet = this.createPositionWorklet();
			this._source.connect(this._positionWorklet);
			if (options.start) {
				this.start();
			}			
		} catch (e) {
			const path = GodotConfig.locate_file('godot.audio.position.worklet.js');
			GodotAudio.ctx.audioWorklet
				.addModule(path)
				.then(() => {
					if (!this.isCanceled) {
						this._positionWorklet = this.createPositionWorklet();
						this._source.connect(this._positionWorklet);
						if (options.start) {
							this.start();
						}
					}
				}).catch((e2) => {
					GodotRuntime.error('Failed to create Position Worklet.', e2);
				});
		}
```

**Comment by adamscott** [comment]
You need to add a condition to platform/web/js/engine/config.js:300 to locate the new file.

**Comment by yahkr** [comment]
> You need to add a condition to platform/web/js/engine/config.js:300 to locate the new file.

ah yup, was missing a few other emscripten helper lines. Looks to be in order now

**Comment by adamscott** [comment]
I'm getting this error.

Capture d’écran, le 2024-08-08 à 13 32 34

I think we shoudn't mess with the `start()` function.

**Comment by adamscott** [comment]
I managed to fix the issues I had with your code. It seemed that `reset` was successfully called, but as the source was already processed by the PositionWorklet, `process()` was never called again, thus never updating the position.

Here's the diff from your last commit:

```diff
diff --git a/platform/web/js/libs/audio.position.worklet.js b/platform/web/js/libs/audio.position.worklet.js
index eb887fdaa7..bf3ac4ae2d 100644
--- a/platform/web/js/libs/audio.position.worklet.js
+++ b/platform/web/js/libs/audio.position.worklet.js
@@ -32,20 +32,6 @@ class GodotPositionReportingProcessor extends AudioWorkletProcessor {
 	constructor() {
 		super();
 		this.position = 0;
-		this.port.onmessage = (event) => {
-			const type = event.data['type'];
-			this.parse_message(type);
-		};
-	}
-
-	parse_message(p_type) {
-		switch (p_type) {
-		case 'reset':
-			this.position = 0;
-			break;
-		default:
-			// Do nothing.
-		}
 	}
 
 	process(inputs, _outputs, _parameters) {
diff --git a/platform/web/js/libs/library_godot_audio.js b/platform/web/js/libs/library_godot_audio.js
index 566805e31a..a5be6a8424 100644
--- a/platform/web/js/libs/library_godot_audio.js
+++ b/platform/web/js/libs/library_godot_audio.js
@@ -463,28 +463,7 @@ class SampleNode {
 		const sampleNodeBus = this.getSampleNodeBus(bus);
 		sampleNodeBus.setVolume(options.volume);
 
-		try {
-			this._positionWorklet = this.createPositionWorklet();
-			this._source.connect(this._positionWorklet);
-			if (options.start) {
-				this.start();
-			}
-		} catch (e) {
-			const path = GodotConfig.locate_file('godot.audio.position.worklet.js');
-			GodotAudio.ctx.audioWorklet
-				.addModule(path)
-				.then(() => {
-					if (!this.isCanceled) {
-						this._positionWorklet = this.createPositionWorklet();
-						this._source.connect(this._positionWorklet);
-						if (options.start) {
-							this.start();
-						}
-					}
-				}).catch((e2) => {
-					GodotRuntime.error('Failed to create Position Worklet.', e2);
-				});
-		}
+		this.connectPositionWorklet();
 	}
 
 	/**
@@ -650,6 +629,25 @@ class SampleNode {
 		return worklet;
 	}
 
+	connectPositionWorklet() {
+		try {
+			this._positionWorklet = this.createPositionWorklet();
+			this._source.connect(this._positionWorklet);
+		} catch (e) {
+			const path = GodotConfig.locate_file('godot.audio.position.worklet.js');
+			GodotAudio.ctx.audioWorklet
+				.addModule(path)
+				.then(() => {
+					if (!this.isCanceled) {
+						this._positionWorklet = this.createPositionWorklet();
+						this._source.connect(this._positionWorklet);
+					}
+				}).catch((e2) => {
+					GodotRuntime.error('Failed to create Position Worklet.', e2);
+				});
+		}
+	}
+
 	/**
 	 * Clears the `SampleNode`.
 	 * @returns {void}
@@ -720,6 +718,8 @@ class SampleNode {
 			? this.pauseTime
 			: 0;
 		this._source.start(this.startTime, this.offset + pauseTime);
+
+		this.connectPositionWorklet();
 	}
 
 	/**

```

**Comment by yahkr** [comment]
> I managed to fix the issues I had with your code. It seemed that `reset` was successfully called, but as the source was already processed by the PositionWorklet, `process()` was never called again, thus never updating the position.
> 
> Here's the diff from your last commit that makes work my MRP:
> Here's my MRP: [samples.zip](https://github.com/user-attachments/files/16551604/samples.zip)

any other changes? using your mrp most of the time the audio doesnt play and the connectPositionWorklet() is called twice.  On one refresh i was able to hear the voice line. ( and forgot how loud my audio was at lol)  I see the issue is with autoplay, i've been manuall starting mine. Will see why the timing is so different.

**Comment by yahkr** [comment]
oh im dumb, i forgot why i moved to manual, audio cant autoplay on web until you click into the page. so thats why  i didnt hear yours half the time. but we would still need the this.start() in the setup as it used to be called upon SampleNode creation when you call .play()

Give this latest push a try, autoplay / manual appear working.

File: platform/web/js/libs/audio.position.worklet.js [hunk 19]
```diff
@@ -0,0 +1,64 @@
...
+
+	parse_message(p_type) {
+		switch (p_type) {
+		case 'reset':
+			this.position = 0;
+			break;
+		default:
+			// Do nothing.
+		}
+	}
```
Comment (adamscott) [inline platform/web/js/libs/audio.position.worklet.js:49]: You can remove all the code related to reset.

File: platform/web/js/libs/library_godot_audio.js [hunk 20]
```diff
@@ -512,8 +531,11 @@ class SampleNode {
 	 * @returns {void}
 	 */
 	start() {
-		this._resetSourceStartTime();
-		this._source.start(this.startTime, this.offset);
+		if (!this.isStarted) {
+			this._resetSourceStartTime();
+			this._source.start(this.startTime, this.offset);
+			this.isStarted = true;
+		}
```
Comment (adamscott) [inline platform/web/js/libs/library_godot_audio.js:538]: Always use early return if possible.

```suggestion
		if (this.isStarted) {
			return;
		}
		this._resetSourceStartTime();
		this._source.start(this.startTime, this.offset);
		this.isStarted = true;
```

File: platform/web/js/libs/library_godot_audio.js [hunk 21]
```diff
@@ -588,18 +610,71 @@ class SampleNode {
...
+						this._source.connect(this._positionWorklet);
+						if (start) {
+							this.start();
+						}
+					}
+				}).catch((e2) => {
+					GodotRuntime.error('Failed to create Position Worklet.', e2);
+				});
+		}
+	}
```
Comment (adamscott) [inline platform/web/js/libs/library_godot_audio.js:640]: Here, I added a check to make sure that the error is related to the "InvalidStateError" that is signalled when PositionWorklet doesn't exist.

I also renamed `e` to `error` for both errors.

```suggestion
	connectPositionWorklet(start) {
		try {
			this._positionWorklet = this.createPositionWorklet();
			this._source.connect(this._positionWorklet);
			if (start) {
				this.start();
			}
		} catch (error) {
			if (error?.name !== 'InvalidStateError') {
				throw error;
			}
			const path = GodotConfig.locate_file('godot.audio.position.worklet.js');
			GodotAudio.ctx.audioWorklet
				.addModule(path)
				.then(() => {
					if (!this.isCanceled) {
						this._positionWorklet = this.createPositionWorklet();
						this._source.connect(this._positionWorklet);
						if (start) {
							this.start();
						}
					}
				}).catch((error) => {
					GodotRuntime.error('Failed to create PositionWorklet.', error);
				});
		}
	}
```

**Review by adamscott — CHANGES_REQUESTED** [review]
Last changes that I can see.

**Comment by yahkr** [comment]
> Last changes that I can see.

The errors do need separate names. But thank you for the reviews!

**Review by adamscott — APPROVED** [review]
Works for me! Thank you, @yahkr, for your time and effort. Very appreciated.

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.
