### PR TITLE
Fix calculation bug with `TextEdit::get_line_height()`

### LINKED ISSUE #69209: Crash when loading old theme from earlier Godot versions
### Godot version

4.0 Beta 3 and 4.0 beta 6

### System information

Linux Mint 20.3 Cinnamon - Intel© Core™ i7-8700K CPU @ 3.70GHz × 6 - NVIDIA Corporation TU106 [GeForce RTX 2070]

### Issue description

If I try to change the theme at runtime using 
`this.mainContainer.Theme = ServiceManager.Current.ThemeService.CurrentTheme;`

It simply crashes to desktop with the following trace:

```
================================================================
handle_crash: Program crashed with signal 8
Engine version: Godot Engine v4.0.beta6.mono.official (7f8ecffa56834dce3ccbd736738b613d51133dea)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[1] /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.11/libcoreclr.so(+0x4dce2e) [0x7f898b5a3e2e] (??:0)
[2] /lib/x86_64-linux-gnu/libpthread.so.0(+0x14420) [0x7f89c9b41420] (??:0)
[3] /media/me/Storage/Godot/Godot_v4.0-beta6_mono_linux_x86_64/Godot_v4.0-beta6_mono_linux.x86_64() [0x2ce6875] (??:0)
[4] /media/me/Storage/Godot/Godot_v4.0-beta6_mono_linux_x86_64/Godot_v4.0-beta6_mono_linux.x86_64() [0x2cc00ad] (??:0)
[5] /media/me/Storage/Godot/Godot_v4.0-beta6_mono_linux_x86_64/Godot_v4.0-beta6_mono_linux.x86_64() [0x432ae04] (??:0)
[6] /media/me/Storage/Godot/Godot_v4.0-beta6_mono_linux_x86_64/Godot_v4.0-beta6_mono_linux.x86_64() [0x2b2fdef] (??:0)
[7] /media/me/Storage/Godot/Godot_v4.0-beta6_mono_linux_x86_64/Godot_v4.0-beta6_mono_linux.x86_64() [0x2b31af8] (??:0)
[8] /media/me/Storage/Godot/Godot_v4.0-beta6_mono_linux_x86_64/Godot_v4.0-beta6_mono_linux.x86_64() [0x2ac4091] (??:0)
[9] /media/me/Storage/Godot/Godot_v4.0-beta6_mono_linux_x86_64/Godot_v4.0-beta6_mono_linux.x86_64() [0x432ae04] (??:0)
[10] /media/me/Storage/Godot/Godot_v4.0-beta6_mono_linux_x86_64/Godot_v4.0-beta6_mono_linux.x86_64() [0x2b1967c] (??:0)
[11] /media/me/Storage/Godot/Godot_v4.0-beta6_mono_linux_x86_64/Godot_v4.0-beta6_mono_linux.x86_64() [0x4910385] (??:0)
[12] /media/me/Storage/Godot/Godot_v4.0-beta6_mono_linux_x86_64/Godot_v4.0-beta6_mono_linux.x86_64() [0x43c3307] (??:0)
[13] /media/me/Storage/Godot/Godot_v4.0-beta6_mono_linux_x86_64/Godot_v4.0-beta6_mono_linux.x86_64() [0x2a27b95] (??:0)
[14] /media/me/Storage/Godot/Godot_v4.0-beta6_mono_linux_x86_64/Godot_v4.0-beta6_mono_linux.x86_64() [0xe66d55] (??:0)
[15] /media/me/Storage/Godot/Godot_v4.0-beta6_mono_linux_x86_64/Godot_v4.0-beta6_mono_linux.x86_64() [0xda7193] (??:0)
[16] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f89c980a083] (??:0)
[17] /media/me/Storage/Godot/Godot_v4.0-beta6_mono_linux_x86_64/Godot_v4.0-beta6_mono_linux.x86_64() [0xdc8bfe] (??:0)
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

Load **this branch** of my project https://gitlab.com/gametheatre/poriferareader/Porifera/-/tree/ThemeSwitch
In the top bar, the rightmost element should be an options button
Select anything other than default in that menu
Observe crash

### Minimal reproduction project

https://gitlab.com/gametheatre/poriferareader/Porifera/-/tree/ThemeSwitch
Please note this is not minimal, I tried making a minimal reproduction and it did not crash. There is something about the more complex UI of my project which I have not identified.

### PR DESCRIPTION
**Pull request by Rindbee**
When `get_line_height()` is not greater than `0`, there is no visible text.

In these cases, the user is required to increase `line_spacing` and/or `font_size` to obtain a reasonably positive `line_height`.

There are many cases where the return value of `get_line_height()` is used for calculation, and in some cases the final result is allowed to be negative. So limit the return result of `get_line_height()` to **not less** than `0`. Print an error if `get_line_height()` is `0` and used as the denominator.

Fix #69209.

### CODE REVIEW

**Review by adamscott — APPROVED** [review]
Fixes a possible nasty division by 0.

**Review by adamscott — APPROVED** [review]
Thanks for updating the documentation. The code is much better now too.

**Review by Paulb23 — CHANGES_REQUESTED** [review]
Should make the minimum return `1`, then we wouldn't need to worry about a divide by `0`, or is there a use case for `0` line height?

We should also print a warning if it is below the minimum.

**Comment by Rindbee** [comment]
> Should make the minimum return `1`, then we wouldn't need to worry about a divide by `0`, or is there a use case for `0` line height?

Set `line_spacing` small enough to hide all text. Might not be necessary for the use cases of `TextEdit`. So not less than `1` is fine.

**Comment by Paulb23** [comment]
Missing the warning print, either with `ERR_FAIL_COND_MSG` or a check in `_update_cache / _update_theme_item_cache` so it doesn't go unnoticed.

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -3005,6 +3005,9 @@ void TextEdit::_update_theme_item_cache() {
 	theme_cache.outline_color = get_theme_color(SNAME("font_outline_color"));
 
 	theme_cache.line_spacing = get_theme_constant(SNAME("line_spacing"));
+	if (text.get_line_height() + theme_cache.line_spacing < 1) {
+		WARN_PRINT("Line height is too small, please increase font_size and/or line_spacing");
+	}
```
Comment (Rindbee) [inline scene/gui/text_edit.cpp:3010]: Now prints a warning in `_update_theme_item_cache()`.

**Review by Paulb23 — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.4.
