### PR TITLE
Fix conversion of hex color strings in project converter

### LINKED ISSUE #73633: Conversion to 4.0 doesn't change hex string to RGBA in Color constructor
### Godot version

4.0.dev.dfdda9629

### System information

Windows 10

### Issue description

The way Godot parses hex Color strings is different in 4.0 (ARGB vs RGBA).

| HEX string | Godot 3 | Godot 4 |
| ----- | ----- | ----- |
| 00FFFFFF | Color(1,1,1,0) | Color(0,1,1,1) |
| 0FFF | Color(1,1,1,0) | Color(0,1,1,1) |

I think the project converter can look for the Color constructor and modify the string.
Something along the lines of `/Color\("#?([a-fA-F0-9]{8}|[a-fA-F0-9]{4})"\)/gm`.

Also, exported colors seem to reset their value because of an "@" in the `tscn` file. (`@exported_color` instead of `exported_color`)

### Steps to reproduce

1. Open MRP in Godot 3 and look at output.
2. Upgrade the project using the conversion tool.
3. Open it in Godot 4 and notice how the colors are now totally different.

### Minimal reproduction project

[color_conversion.zip](https://github.com/godotengine/godot/files/10786230/color_conversion.zip)

### PR DESCRIPTION
**Pull request by ericliu206**
fixes https://github.com/godotengine/godot/issues/73633

### CODE REVIEW

**Comment by ericliu206** [comment]
This appears to fix the issue, however, I am not sure if this is the best way to organize the code. Any suggestions will be appreciated. :)

**Comment by Maran23** [comment]
Can you also add tests? (`test_conversion_gdscript_builtin`).
Also you need to rebase the branch. :)

File: editor/project_converter_3_to_4.cpp [hunk 1]
```diff
@@ -965,6 +972,7 @@ bool ProjectConverter3To4::test_conversion(RegExContainer &reg_container) {
 	valid = valid && test_conversion_gdscript_builtin("button.pressed=1", "button.button_pressed=1", &ProjectConverter3To4::rename_gdscript_functions, "custom rename", reg_container, false);
 	valid = valid && test_conversion_gdscript_builtin("button.pressed SF", "button.pressed SF", &ProjectConverter3To4::rename_gdscript_functions, "custom rename", reg_container, false);
 
+	valid = valid && test_conversion_gdscript_builtin("Color(\"#ff478cbf\")", "Color(\"#478cbfff\")", &ProjectConverter3To4::convert_hexadecimal_colors, "custom rename", reg_container, false);
```
Comment (YuriSizov) [inline editor/project_converter_3_to_4.cpp:975]:
```suggestion
	valid = valid && test_conversion_with_regex("Color(\"#ff478cbf\")", "Color(\"#478cbfff\")", &ProjectConverter3To4::convert_hexadecimal_colors, "color literals", reg_container);
```

File: editor/project_converter_3_to_4.cpp [hunk 2]
```diff
@@ -2729,6 +2737,22 @@ Vector<String> ProjectConverter3To4::check_for_rename_common(const char *array[]
 	return found_renames;
 }
 
+// Convert hexadecimal colors from ARGB to RGBA
+void ProjectConverter3To4::convert_hexadecimal_colors(Vector<SourceLine> &source_lines, const RegExContainer &reg_container, bool builtin) {
```
Comment (YuriSizov) [inline editor/project_converter_3_to_4.cpp:2741]:
```suggestion
void ProjectConverter3To4::convert_hexadecimal_colors(Vector<SourceLine> &source_lines, const RegExContainer &reg_container) {
```

It doesn't do anything?

File: editor/project_converter_3_to_4.h [hunk 3]
```diff
@@ -102,6 +102,8 @@ class ProjectConverter3To4 {
 	void rename_common(const char *array[][2], LocalVector<RegEx *> &cached_regexes, Vector<SourceLine> &source_lines);
 	Vector<String> check_for_rename_common(const char *array[][2], LocalVector<RegEx *> &cached_regexes, Vector<String> &lines);
 
+	void convert_hexadecimal_colors(Vector<SourceLine> &source_lines, const RegExContainer &reg_container, bool builtin);
```
Comment (YuriSizov) [inline editor/project_converter_3_to_4.h:105]:
```suggestion
	void convert_hexadecimal_colors(Vector<SourceLine> &source_lines, const RegExContainer &reg_container);
```

File: editor/project_converter_3_to_4.cpp (hunk 2 above)
Comment (YuriSizov) [reply editor/project_converter_3_to_4.cpp:2741]: Method should also go next to `ProjectConverter3To4::rename_colors` in both the header and the cpp file.

File: editor/project_converter_3_to_4.cpp [hunk 4]
```diff
@@ -137,6 +137,8 @@ class ProjectConverter3To4::RegExContainer {
 	LocalVector<RegEx *> color_regexes;
 	LocalVector<String> color_renamed;
 
+	RegEx color_hexadecimal_constructor = RegEx("Color\\(\"#?(?=\\b[a-fA-F0-9]{4}\\b|\\b[a-fA-F0-9]{8}\\b)([a-fA-F0-9]{1,2})([a-fA-F0-9]{1,2})([a-fA-F0-9]{1,2})([a-fA-F0-9]{1,2})");
```
Comment (YuriSizov) [inline editor/project_converter_3_to_4.cpp:140]: Lookaheads are pretty expensive, and I don't think there is a good enough reason to ignore invalid strings here: since they are invalid we can't really make them worse.

So I would suggest something simpler:

```suggestion
	RegEx color_hexadecimal_constructor = RegEx("Color\\("#?([a-fA-F0-9]{1,2})([a-fA-F0-9]{3,7})\\b");
```

Here's what it matches:
image

**Comment by YuriSizov** [comment]
Sorry for the wait. So I checked this again and realized my suggestion was rather poor, as it would incorrectly convert your normal 6-character long hex colors.

image

<details><summary>Test set</summary>

```
Color("#dede")
Color("dede")
Color("#7e4e")
Color("8e0d")
Color("#bcbcbc")
Color("fefefe")
Color("#11dd33aa")
Color("11dd33aa")
Color("#9d9g9e")
Color("abch")
Color("#deded")
Color("0909909")
Color("123456789")
```
</details>

So I went ahead and updated your PR on your behalf, adding more tests to catch these cases and splitting the operation into two passes: one explicitly for 4 characters and another explicitly for 8 characters.

**Review by YuriSizov — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.3.
