### PR TITLE
Fix the behavior of the resource property of the sub-scene root node on instantiation

### LINKED ISSUE #76693: Local to Scene SubResource Ids change after saving
### Godot version

4.0.2 & 4.0.3 RC1

### System information

Windows 10, Vulkan API 1.3.224, NVIDIA RTX A2000 Laptop GPU

### Issue description

When saving a scene containing another recently saved instatiated scene with one or more resources being local to scene, Godot changes the affected Resource ID. This only happens if the Node containing the resource being local to scene is the root.
This Occurance is espacially problematic when working in a team with any source control solution.

### Steps to reproduce

- Create a new scene containing a MeshInstance3D node and make it the scene root.
- Assign a mesh and set the property resource_local_to_scene to true
- Create a second scene and instantiate the scene containing the MeshInstance3D node
- Without needing to change either scenes, save the MeshInstance3D scene (or any other instantiated child scene) first, then the scene where the MeshInstance3D scene is initiated

### Minimal reproduction project

[IdChange.zip](https://github.com/godotengine/godot/files/11380909/IdChange.zip)
In this example saving either child scene before the main scene will cause the error, but only the IDs of the Node labeled "ChanginIDs" will change.

### LINKED ISSUE #77997: Instances of scenes with a Material flagged Local to Scene see their material instances become independent and change ID every time you reopen the scene containing them
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Linux Ubuntu 22.04 with Unity desktop

### Issue description

Local to Scene is convenient for Materials because when changing properties / shader parameters by code, we often want to affect a single entity, not all of them.

However, when the material is placed on a scene to be instantiated (aka "prefab", "blueprint" or "archetype" in other engines; we'll call it "model scene" below), and flagged Local to Scene, each instance has the two following behaviors:

1. Independent: They create their own embedded material instance. While it seems to follow Local to Scene's design, this means such instances will stop being updated with new changes on the original material on the model scene. In addition, the Local to Scene tooltip says that it should affect *run-time*, not edit time. Although there is a point in making some changes in edit time (namely ungreying the fields to allow user to change some instance fields in the inspector to override defaults), this seems to go too far by breaking the original resource relationship.
2. ID change: Every time the scene containing the instances is closed and reopen, the material ID will change in both the SubResource declaration and reference, polluting VCS diff.

Saving the material as an asset (Resource) instead of being embed in the model scene doesn't fix the issue.

For now, my workaround is to manually duplicate the resource to make it a unique instance at runtime, on game start (or node instantiation), as I do in other engines:

`sprite.material = sprite.material.duplicate()`

This doesn't allow overriding property instances in the inspector at edit time, but at east it avoids sharing material shader parameter updates with all instances (whether due to scene instantiation or material resource asset reuse), while avoiding the repeated ID change.

### Steps to reproduce

The best is to download the MRP and read the Git history which explains each step and shows the diff. It also has additional steps to demonstrate cases where the bug does _not_ occur. Below, I'll sum-up the core steps:

**ID change**

1. Create a scene with a sprite with a CanvasItemMaterial flagged Local to Scene
2. Create another scene where you instantiate the model scene
3. Save the new scene and commit in Git.
4. Close and reopen the scene and observe the diff

Observed diff:

image

CanvasItemMaterial ID changes in both sub-resource declaration, and reference usage.

Since the ID change can be repeated indefinitely, you can also open the MRP and repeat step 4 as many times as you want. Note that the MRP has 2 scene model instances so you will see 2 IDs changing each time.

**Independence**

5. Change some property on the model scene material such as `particles_animation = true`
6. Save model scene, open scene with instance and save: particles_animation is not updated on the instance

**Bonus: Material as Resource**

Save material as a resource asset and try again: the bug still occurs.

### Minimal reproduction project

[v4.0.2 - Material of instance of scene with Local to Scene material keeps changing ID.zip](https://github.com/godotengine/godot/files/11686919/v4.0.2.-.Material.of.instance.of.scene.with.Local.to.Scene.material.keeps.changing.ID.zip)

### PR DESCRIPTION
**Pull request by Rindbee**
See https://github.com/godotengine/godot/pull/64999#issuecomment-1229569123, this PR complements it.

The sub-scene root node will be set successively in the sub-scene and the main scene.

In the following tables, the R prefix indicates a resource that does **not** have `resource_local_to_scene` enabled. The RL prefix indicates a resource with `resource_local_to_scene` enabled.

A gray background means that the record will be empty; others will still create a new record in the main scene.

In the case marked in yellow above, it is actually impossible to determine whether a new RL1 or an old RL0 is used.

The PR is simply to determine intent from the record, the above yellow cases are considered RL0. Mainly the cases when `resource_local_to_scene` is enabled in main scene.

After setting the properties of the sub-scene root node, call `setup_local_to_scene()` on the nested resource with `resource_local_to_scene` enabled so that the nested resource is setup correctly.

When updating resources according to the records of the main scene, use the `scene_unique_id` in the main scene to prevent the ID of the resource from changing continuously when saving the scene.

Fix #77997, fix #76693.

### CODE REVIEW

File: core/io/resource.cpp [hunk 1]
```diff
@@ -151,15 +151,20 @@ bool Resource::editor_can_reload_from_file() {
 void Resource::reset_state() {
 }
 Error Resource::copy_from(const Ref<Resource> &p_resource) {
-	ERR_FAIL_COND_V(p_resource.is_null(), ERR_INVALID_PARAMETER);
-	if (get_class() != p_resource->get_class()) {
+	HashMap<Ref<Resource>, Ref<Resource>> tmp;
+	return reset_data_from(p_resource, tmp, false);
+}
+
+Error Resource::reset_data_from(const Ref<Resource> &p_from, HashMap<Ref<Resource>, Ref<Resource>> &remap_cache, const bool p_keep_local_to_scene_resource) {
```
Comment (RandomShaper) [inline core/io/resource.cpp:158]: Let me suggest that instead of adding a new function `copy_from()` has new arguments added with defaults. The declaration in the header would be this:
```
Error copy_from(const Ref<Resource> &p_from, HashMap<Ref<Resource>, Ref<Resource>> &p_remap_cache = {}, bool p_keep_local_to_scene_resource = false);
```

File: core/io/resource.cpp [hunk 2]
```diff
@@ -169,10 +174,34 @@ Error Resource::copy_from(const Ref<Resource> &p_resource) {
 			continue; //do not change path
 		}
 
-		set(E.name, p_resource->get(E.name));
+		Variant value = p_from->get(E.name);
+
+		if (p_keep_local_to_scene_resource) {
+			Ref<Resource> sub_res_of_from = value;
```
Comment (RandomShaper) [inline core/io/resource.cpp:180]: Please add a nice comment here explaining the purpose of all this logic. Let's try to at least keep new additions to this packed scene tangle documented.

File: scene/resources/packed_scene.cpp [hunk 3]
```diff
@@ -287,11 +288,20 @@ Node *SceneState::instantiate(GenEditState p_edit_state) const {
...
-										Ref<Resource> node_res = node->get(snames[nprops[j].name]);
-										if (node_res.is_valid()) {
-											node_res->copy_from(res);
-											node_res->configure_for_local_scene(node, resources_local_to_scene);
-											value = node_res;
+										HashMap<Ref<Resource>, Ref<Resource>>::Iterator E = resources_local_to_sub_scene.find(res);
+										if (E) {
+											value = E->value;
+										} else {
+											Ref<Resource> node_res = node->get(snames[nprops[j].name]);
```
Comment (RandomShaper) [inline scene/resources/packed_scene.cpp:295]: You may want to add a bit of commenting here as well, for future maintainers to make sense of the code more easily, now details are still fresh in your mind.

**Review by RandomShaper — CHANGES_REQUESTED** [review]
I can't really test all the new changes. They look overall good.

**Comment by RandomShaper** [comment]
I was wondering if we could remove part of the recently added logic to scene instantiation (including the present PT) and do the fix instead at scene packing time; i.e., store nodes that wouldn't normally be stored for being pure instances in case they have properties pointing to local-to-scene resources, and store only those properties. @Rindbee, thoughts?

Aside again, I've tagged this PR for cherry-picking into 3.5 and 3.x, like the previous ones regarding this. However, given the changes are starting to get a bit complex and error prone, I'm wondering if they shouldn't be cherry-picked into 3.5 for the time being, to avoid regressions. @akien-mga, thoughts?

**Comment by akien-mga** [comment]
Yes any change to PackedScene will cause regressions in my experience :) This should not be cherry-picked for 3.5.

**Comment by Rindbee** [comment]
I think it's worth a shot, some things are easier to handle when packing.

**Comment by RandomShaper** [comment]
I'll untag from 3.5 all the PRs in the changeset.

**Comment by RandomShaper** [comment]
All the related (merged and not yet merged) PRs are now only tagged for being cherry-picked into 3.x.
That said, @Rindbee, bear in mind that some changes may not be trivially cherry-pickable. Such cases would require dedicated PRs for 3.x.

**Comment by RandomShaper** [comment]
> I think it's worth a shot, some things are easier to handle when packing.

So, do you still want to have this one merged or you'd rather try the other way first?

**Comment by Rindbee** [comment]
I'm now more familiar with scene instancing than scene packaging, so learning scene packaging may take more time. 

There is no need to merge it now, and it may be revised later.

**Comment by RandomShaper** [comment]
Will you split this PR into two? The part affecting instantiation and the part affecting node copy? The latter is ready to be merged right away. The former could be kept in standby until you decide.

**Comment by Rindbee** [comment]
The previous `copy_from` is directly replaced with the attribute value in the source resource, which is similar to the previous situation of the sub-scene root.

When local-to-scene is enabled, it is desirable to keep the previous resource instance, because direct replacement will break the sharing relationship.

These situations may currently exist:
1. node->res1(local)
2. node->res2(local)->res1(local)
3. node->res3->res1(local)

Now hopefully 1 and 2 are properly resolved. As for 3, it's a bit difficult.

**Comment by Rindbee** [comment]
OK, what can be done has been done.

> 3. node->res3->res1(local)

I think it's better to treat it as an error when instantiating, res3 that can be shared globally should not have local-to-scene sub-resources.

A possible solution is to propagate the local-to-scene of res1 to res3, i.e. res3 is also local-to-scene. It may be more appropriate to deal with it when packing.

**Comment by RandomShaper** [comment]
Well, if this already fixes some cases I think the best thing at this point is to have it merged. That will make it easier to track this waterfall of changes about instantiation and local-to-scene resources. If you at some point find a good way to do some of the fixes at packing time, I gues there's no harm in a new PR that partially reverts the current approach and adds the new way.

**Review by RandomShaper — APPROVED** [review]

**Comment by YuriSizov** [comment]
@RandomShaper Could you give it another look, given that it's been almost a year? Both in terms of PR itself and whether we should include it into 4.1 at this point, or rather into early 4.2.

**Comment by RandomShaper** [comment]
Changes still look good, but I would need to spend many hours checking them in detail for a refresher. I've re-targeted this for 4.2, where we'll be able to focus on specific issues that may appear.

**Comment by YuriSizov** [comment]
This needs a rebase. And probably it's still better to re-review it.

**Review by KoBeWi — APPROVED** [review]

File: core/io/resource.h [hunk 4]
```diff
@@ -83,11 +83,12 @@ class Resource : public RefCounted {
 public:
 	static Node *(*_get_local_scene_func)(); //used by editor
 	static void (*_update_configuration_warning)(); //used by editor
+	static Ref<Resource> get_remap_resource(const Ref<Resource> &p_resource, HashMap<Ref<Resource>, Ref<Resource>> p_remap_cache, const Ref<Resource> p_fallback, Node *p_for_scene);
```
Comment (AThousandShips) [inline core/io/resource.h:86]: Any reason `p_fallback` is not passed by reference yet is const?

File: core/io/resource.h [hunk 5]
```diff
@@ -83,11 +83,12 @@ class Resource : public RefCounted {
...
 
 	void update_configuration_warning();
 	virtual bool editor_can_reload_from_file();
 	virtual void reset_state(); //for resources that use variable amount of properties, either via _validate_property or _get_property_list, this function needs to be implemented to correctly clear state
-	virtual Error copy_from(const Ref<Resource> &p_resource);
+	virtual Error copy_from(const Ref<Resource> &p_resource, HashMap<Ref<Resource>, Ref<Resource>> p_remap_cache = {}, const bool p_keep_local_to_scene_resource_instance = false);
```
Comment (AThousandShips) [inline core/io/resource.h:91]: Any reason the boolean is const?

File: core/io/resource.h (hunk 4 above)
Comment (Rindbee) [reply core/io/resource.h]: It was omitted before, but it has been corrected.

File: core/io/resource.h [hunk 6]
```diff
@@ -83,11 +83,12 @@ class Resource : public RefCounted {
 public:
 	static Node *(*_get_local_scene_func)(); //used by editor
 	static void (*_update_configuration_warning)(); //used by editor
+	static Ref<Resource> get_remap_resource(const Ref<Resource> &p_resource, HashMap<Ref<Resource>, Ref<Resource>> &remap_cache, const Ref<Resource> &p_fallback, Node *p_for_scene);
 
 	void update_configuration_warning();
 	virtual bool editor_can_reload_from_file();
 	virtual void reset_state(); //for resources that use variable amount of properties, either via _validate_property or _get_property_list, this function needs to be implemented to correctly clear state
-	virtual Error copy_from(const Ref<Resource> &p_resource);
+	virtual Error copy_from(const Ref<Resource> &p_resource, HashMap<Ref<Resource>, Ref<Resource>> &remap_cache, bool p_keep_local_to_scene_resource_instance = false);
```
Comment (reduz) [inline core/io/resource.h:91]: If this logic is only used in PackedScene, it should be in PackedScene IMO.

**Review by reduz — CHANGES_REQUESTED** [review]

File: core/io/resource.h (hunk 6 above)
Comment (Rindbee) [reply core/io/resource.h]: It is for `Resource` with `local_to_scene` enabled, used in `Resource::get_remap_resource()`.

File: scene/resources/packed_scene.cpp [hunk 7]
```diff
@@ -74,6 +74,55 @@ static Array _sanitize_node_pinned_properties(Node *p_node) {
...
+		p_fallback->reset_state(); // May want to reset state.
+
+		List<PropertyInfo> pi;
+		p_resource->get_property_list(&pi);
+		for (const PropertyInfo &E : pi) {
+			if (!(E.usage & PROPERTY_USAGE_STORAGE)) {
+				continue;
+			}
+			if (E.name == "resource_path") {
+				continue; //do not change path
```
Comment (AThousandShips) [inline scene/resources/packed_scene.cpp:98]:
```suggestion
				continue; // Do not change path.
```

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
