### PR TITLE
Removed updates that caused unnecessary window updates

### LINKED ISSUE #52360: Moving the mouse cursor on the script editor causes constant redrawing (unlike in `3.x`)
### Godot version

4.0.dev (bb0122c93)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.57.02)

### Issue description

Moving the mouse cursor on the script editor causes constant redrawing (unlike in `3.x`). This results in increased CPU/GPU usage when using the script editor, which impacts power consumption and battery life negatively.

Look at the mouse cursor moving and the update spinner in the top-right corner:

https://user-images.githubusercontent.com/180032/131927412-138d6126-15f4-4745-a2a7-e1b8dfd65880.mp4

This does not occur in 3.4 beta4 (on the script editor itself at least – unnecessary redrawing still occurs when hovering the 2D editor tabs and PopupMenu items):

https://user-images.githubusercontent.com/180032/131927586-7093ee80-1b29-4123-b6b9-579ca7e62099.mp4

### Steps to reproduce

- Enable **Show Update Spinner** in the Editor Settings.
- Create a script.
- Move the mouse slowly. Notice how the spinner in the top-right corner will spin continuously when doing so, even if you don't click. In `3.x`, the spinner will only move slowly (twice a second) because of the caret blinking.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by e8newallm**
Fix #52360

The unnecessary updates were happening in both the tab and the text edit part of the script window.

In regards to the text edit part, it seemed to happen while updating a string. I changed it to only update if the string was changed.

The tab update seemed to not affect anything I could see, and removing it doesn't seem to have made a difference.

I am unsure about these changes, specifically the tab change, so I'd appreciate extra scrutiny to be sure that I haven't caused a problem elsewhere.

### CODE REVIEW

File: scene/gui/tabs.cpp [hunk 1]
```diff
@@ -120,7 +120,6 @@ void Tabs::gui_input(const Ref<InputEvent> &p_event) {
 		}
 
 		_update_hover();
-		update();
```
Comment (Paulb23) [inline scene/gui/tabs.cpp:123]: `_update_hover` doesn't call `update()` would guess that this is still needed.

File: scene/gui/text_edit.cpp [hunk 2]
```diff
@@ -4958,8 +4958,10 @@ void TextEdit::_set_line_as_hidden(int p_line, bool p_hidden) {
 
 // Symbol lookup.
 void TextEdit::_set_symbol_lookup_word(const String &p_symbol) {
-	lookup_symbol_word = p_symbol;
```
Comment (Paulb23) [inline scene/gui/text_edit.cpp:4961]: This looks good, though would prefer it to be handed on the `CodeEdit` side in `set_symbol_lookup_word_as_valid` if possible.

File: scene/gui/tabs.cpp (hunk 1 above)
Comment (e8newallm) [reply scene/gui/tabs.cpp:123]: When I tried it, I couldn't see any difference between the update() being there and not being there, but I don't know enough about the software to be sure I checked every aspect of the tabbing. I shall add it back in just to be safe.

File: scene/gui/text_edit.cpp (hunk 2 above)
Comment (e8newallm) [reply scene/gui/text_edit.cpp:4961]: Yeah, I can move it.

**Comment by e8newallm** [comment]
I have corrected the code as suggested.

Looking at the tabs though, I'm wondering if that update() couldn't be better placed. Could it not be moved inside of the `if (buttons_visible) {` of Tabs::gui_input() and inside of Tabs::_update_hover()? It's only a minor issue really, as the cursor isn't going to move around a lot on top of a tabs element, but for completion's sake, I'm wondering if the updating could be toned back more.

**Review by Paulb23 — APPROVED** [review]
LGTM.

Yeah probably best to handle tab `update` separately as it's a bit more involved.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
