### PR TITLE
Prevent crash in ImmediateMesh.create_outline

### LINKED ISSUE #73201: Executing `ImmediateMesh.create_outline` crashes Godot
### Godot version

4.0.beta.custom_build. 27b226046

### System information

Ubuntu 22.10 - AMD RX 470, Gnome shell 43 X11

### Issue description

When executing
```
extends Node
func _process(delta):

	var temp_variable687 = ImmediateMesh.new()
	temp_variable687.surface_begin(3, null)
	temp_variable687.surface_add_vertex_2d(Vector2(63.8818855285645, -28.761100769043))
	temp_variable687.surface_end()
	temp_variable687.create_outline(82.1518063545227)
```
Godot crashes:
```
=================================================================
==17657==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x603000ff0adc at pc 0x555ba04413dc bp 0x7ffd3b584b30 sp 0x7ffd3b584b20
READ of size 12 at 0x603000ff0adc thread T0
    #0 0x555ba04413db in Mesh::create_outline(float) const scene/resources/mesh.cpp:543
    #1 0x555ba051e86c in void call_with_variant_args_retc_helper<__UnexistingClass, Ref<Mesh>, float, 0ul>(__UnexistingClass*, Ref<Mesh> (__UnexistingClass::*)(float) const, Variant const**, Variant&, Callable::CallError&, IndexSequence<0ul>) core/variant/binder_common.h:762
    #2 0x555ba05156d3 in void call_with_variant_args_retc_dv<__UnexistingClass, Ref<Mesh>, float>(__UnexistingClass*, Ref<Mesh> (__UnexistingClass::*)(float) const, Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:557
    #3 0x555ba050ec07 in MethodBindTRC<Ref<Mesh>, float>::call(Object*, Variant const**, int, Callable::CallError&) const core/object/method_bind.h:548
    #4 0x555ba7a39158 in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:733
    #5 0x555ba6e2268a in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1161
    #6 0x555b8ead593f in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1613
    #7 0x555b8e3e3e28 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1826
    #8 0x555b9c3b2472 in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:238
    #9 0x555b9c316202 in Node::_notification(int) scene/main/node.cpp:57
    #10 0x555b8cf35f7b in Node::_notificationv(int, bool) scene/main/node.h:46
    #11 0x555ba7a3a6ac in Object::notification(int, bool) core/object/object.cpp:790
    #12 0x555b9c47cb0b in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:874
    #13 0x555b9c46eebd in SceneTree::process(double) scene/main/scene_tree.cpp:466
    #14 0x555b8c5f4703 in Main::iteration() main/main.cpp:3159
    #15 0x555b8c34c5f9 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:880
    #16 0x555b8c327ec7 in main platform/linuxbsd/godot_linuxbsd.cpp:73
    #17 0x7fb8742a7d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
    #18 0x7fb8742a7e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f)
    #19 0x555b8c327874 in _start (/home/runner/work/Qarminer/Qarminer/godot.linuxbsd.editor.dev.x86_64.san+0x3aaed874)

0x603000ff0ae0 is located 0 bytes to the right of 32-byte region [0x603000ff0ac0,0x603000ff0ae0)
allocated by thread T0 here:
    #0 0x7fb874c76867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x555ba6119a07 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x555b8cf555f2 in Error CowData<Vector3>::resize<false>(int) core/templates/cowdata.h:288
    #3 0x555b8cf5102f in Vector<Vector3>::resize(int) core/templates/vector.h:91
    #4 0x555ba6e159b7 in Vector<Vector3> _convert_array<Vector<Vector3>, Vector<Vector2> >(Vector<Vector2> const&) core/variant/variant.cpp:2192
    #5 0x555ba6dfd812 in Vector<Vector3> _convert_array_from_variant<Vector<Vector3> >(Variant const&) core/variant/variant.cpp:2226
    #6 0x555ba6dbfaa3 in Variant::operator Vector<Vector3>() const core/variant/variant.cpp:2300
    #7 0x555ba0440699 in Mesh::create_outline(float) const scene/resources/mesh.cpp:519
    #8 0x555ba051e86c in void call_with_variant_args_retc_helper<__UnexistingClass, Ref<Mesh>, float, 0ul>(__UnexistingClass*, Ref<Mesh> (__UnexistingClass::*)(float) const, Variant const**, Variant&, Callable::CallError&, IndexSequence<0ul>) core/variant/binder_common.h:762
    #9 0x555ba05156d3 in void call_with_variant_args_retc_dv<__UnexistingClass, Ref<Mesh>, float>(__UnexistingClass*, Ref<Mesh> (__UnexistingClass::*)(float) const, Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:557
    #10 0x555ba050ec07 in MethodBindTRC<Ref<Mesh>, float>::call(Object*, Variant const**, int, Callable::CallError&) const core/object/method_bind.h:548
    #11 0x555ba7a39158 in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:733
    #12 0x555ba6e2268a in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1161
    #13 0x555b8ead593f in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1613
    #14 0x555b8e3e3e28 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1826
    #15 0x555b9c3b2472 in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:238
    #16 0x555b9c316202 in Node::_notification(int) scene/main/node.cpp:57
    #17 0x555b8cf35f7b in Node::_notificationv(int, bool) scene/main/node.h:46
    #18 0x555ba7a3a6ac in Object::notification(int, bool) core/object/object.cpp:790
    #19 0x555b9c47cb0b in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:874
    #20 0x555b9c46eebd in SceneTree::process(double) scene/main/scene_tree.cpp:466
    #21 0x555b8c5f4703 in Main::iteration() main/main.cpp:3159
    #22 0x555b8c34c5f9 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:880
    #23 0x555b8c327ec7 in main platform/linuxbsd/godot_linuxbsd.cpp:73
    #24 0x7fb8742a7d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

SUMMARY: AddressSanitizer: heap-buffer-overflow scene/resources/mesh.cpp:543 in Mesh::create_outline(float) const
```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

Memory leaks or asan backtraces are visibe when using Godot build with sanitizers support - https://github.com/qarmin/GodotBuilds/actions (linux -> linux-editor-sanitizers)

### Steps to reproduce

Above

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by chutchinson**
Prevents a crash in ```ImmediateMesh.create_outline``` by ensuring that when no indices are specified, the number of vertices is divisible by 3 without residue. We must check if the vertices vector is divisible by 3 because the outline method constructs normal vectors from a triangle (in other words, there are 3 accesses per iteration)

Fixes #73201

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]

File: scene/resources/mesh.cpp [hunk 1]
```diff
@@ -526,6 +526,9 @@ Ref<Mesh> Mesh::create_outline(float p_margin) const {
 			vc = indices.size();
 			ir = indices.ptrw();
 			has_indices = true;
+		} else {
+			// ensure there are enough vertices to construct at least one triangle
```
Comment (Chaosus) [inline scene/resources/mesh.cpp:530]:
```suggestion
			// Ensure there are enough vertices to construct at least one triangle.
```

**Review by Chaosus — CHANGES_REQUESTED** [review]

**Review by Chaosus — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
