### PR TITLE
Fix cyclic references in GDScript 2.0

### LINKED ISSUE #21461: Some usages of `class_name` can produce cyclic errors unexpectedly
___

***Bugsquad edit:** This issue has been confirmed several times already. No need to confirm it further.*

___

Windows 10 64-bit - Godot 3.1 alpha

## Edit - Refined issue to focus on cyclic errors.

Certain uses of `class_name` can produce cyclic errors in situations where there are no cyclic references, and in fact sometimes no other references outside of the single one given.

I've noticed this most frequently in tool script when using `is` to make a class comparison, but it seems to happen at times in normal script situations.

Recreating it in a sample project has eluded me.

godot master_2018-08-27_00-47-02

### LINKED ISSUE #32165: Cyclic Errors After Autoload of Imported Asset
**Godot version:** 3.1 (confirmed)

**OS/device including version:** Windows 10 & Linux

**Issue description:**

I recently had an Asset approved on the Asset Lib. I was disappointed that trying my new Asset using the Import system produced errors. There is probably another request I want to open regarding having a TEST site for Assets, but for now I want to report this.

After importing my Asset (Godot-Stuff Logging 3.1) and setting up and Autoload global, I receive a number of errors as seen below.

The Workaround is to close your project and reopen it.

```
 Resource: 'res://gs_logger/logger.gd' is already being loaded. Cyclic reference?
 res://gs_logger/layouts/pattern_layout.gd:13 - Parse Error: Identifier 'Logger' is not declared in the current scope.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://gs_logger/appender.gd:53 - Parse Error: Class 'PatternLayout' could not be fully loaded (script error or cyclic dependency).
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://gs_logger/logger.gd:268 - Parse Error: Class 'Appender' could not be fully loaded (script error or cyclic dependency).
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 Script does not inherit a Node: res://gs_logger/logger.gd
 editor/editor_autoload_settings.cpp:448 - Condition ' !info->node ' is true. Continuing..:
Add AutoLoad
```

**Steps to reproduce:**

- create a new project
- use the assetlib and download and import Godot-Stuff 3.1 Logger
- create a new Autoload for the script gs_logger/logger.gd and call it "Logger"
- you will receive the errors above
- create a new scene and attach a gdscript to it
- try to access the Logger global object you will receive the following errors

```
 Resource: 'res://gs_logger/logger.gd' is already being loaded. Cyclic reference?
 res://gs_logger/layouts/pattern_layout.gd:13 - Parse Error: Identifier 'Logger' is not declared in the current scope.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://gs_logger/appender.gd:53 - Parse Error: Class 'PatternLayout' could not be fully loaded (script error or cyclic dependency).
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
 res://gs_logger/logger.gd:268 - Parse Error: Class 'Appender' could not be fully loaded (script error or cyclic dependency).
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERRO
```
- close the project and re-open it
- the errors disappear

**Minimal reproduction project:**

### LINKED ISSUE #41027: Cyclic reference error in GDScript 2.0
**Godot version:**
Godot Eninge v4.0.dev.custom_build.ec678c5e9

**OS/device including version:**
Windows 10

**Issue description:**
Cyclic reference error:
image

**Steps to reproduce:**
1) Create class1 and class2
2) Initialize class1 in class2 and class2 in class1
3) Add class1 to scene

**Minimal reproduction project:**
[godot_cyclic_reference.zip](https://github.com/godotengine/godot/files/5023741/godot_cyclic_reference.zip)

### LINKED ISSUE #58181: GDScript 2.0: Cannot preload cyclic const script references
### Godot version

b3507ab0cdf25e470b1e4d977ed0bea32a305c1b

### System information

Windows 10, Vulkan, Intel® Core™ i7-8700K, Nvidia GTX 1080 (471.11)

### Issue description

Scripts can preload other scripts with the 'preload' keyword, however, they will fail with the error ```Constant value uses script from "%s" which is loaded but not compiled``` if trying to preload a script which itself has preload keywords for the script which is loading, meaning it cannot resolve this cyclic dependency.

There are TODO messages in the ```GDScriptAnalyzer::reduce_preload``` which seem to hint at a strategy to support cyclic preloads, but it is unclear how this should be accomplished in the current GDScript framework. Requesting information from @vnen on the best way to potentially resolve this.

### Steps to reproduce

Simply create two scripts which use the ```preload``` function to preload each other.

### Minimal reproduction project

[cyclic_preload.zip](https://github.com/godotengine/godot/files/8079475/cyclic_preload.zip)

### LINKED ISSUE #58551: Can't preload a scene in AutoLoad script when the scene's script references the AutoLoad
### Godot version

4.0.alpha3

### System information

Windows 10

### Issue description

This appears to be a regression in 4.0, as this works in 3.4.3. Running the scene causes a ParserError crash, when I expect it to run fine.

### Steps to reproduce

If you have a simple AutoLoad script like so:
image

Which preloads this simple scene with just one script:
image

And that script references the AutoLoad script:
image

Then running the scene causes a crash:
`Parser Error: Could not preload resource file "res://Scene.tscn"`

### Minimal reproduction project

Working project in 3.4.3:
[AutoloadBugGodot3.4.3.zip](https://github.com/godotengine/godot/files/8146324/AutoloadBugGodot3.4.3.zip)

Identical project but in 4.0.alpha3:
[AutoloadBugGodot4.zip](https://github.com/godotengine/godot/files/8146325/AutoloadBugGodot4.zip)

### LINKED ISSUE #58871: Cyclic Autoload Singleton Plugin Bug.
### Godot version

v3.4.3.stable.official [242c05d12]

### System information

Windows 10

### Issue description

Cannot enable plugin because autoload is not declared. Autoload is not declared because plugin is disable.

Reloading project does not help.
You have to remove all the singleton reference to temporary fix the bug.

### Steps to reproduce

1. Make a plugin.
2. Create a singleton script and add to plugin.
3. Create any script that reference to that singleton and add to plugin.
4. Disable the plugin and reload project.
5. Try to enable the plugin and now you can't until you remove that reference.

### Minimal reproduction project

[Cyclic Autoload Singleton Plugin Bug.zip](https://github.com/godotengine/godot/files/8199572/Cyclic.Autoload.Singleton.Plugin.Bug.zip)

### LINKED ISSUE #61043: New cyclic reference error with autoload and preloaded script
### Godot version

6d5d9dd

### System information

Windows 10 x64

### Issue description

I have a `class_name` script `Game` that preloads another script that uses an autoload that uses a variable of the type `Game`. There is obvious cyclic reference here, but it runs fine in 3.5. In 4.0 the script is parsed properly in the editor, but at runtime it stops on `Parser Error: Could not preload resource file` at the `preload` line.

### Steps to reproduce

The steps are confusing, just check the project.

### Minimal reproduction project

[AutoloadBug.zip](https://github.com/godotengine/godot/files/8694166/AutoloadBug.zip)
You can run it both in 3.5 and 4.0 and compare results.

### LINKED ISSUE #65263: GDScript reload generates error when created dynamically (no backing script)
### Godot version

 v4.0.alpha15.official.432b25d36

### System information

OSX 10.15.7

### Issue description

When you create a GDScript object, set the source, and then call `reload` it generates the following error:
```
ERROR: Attempt to open script '' resulted in error 'File not found'.
   at: load_source_code (modules/gdscript/gdscript.cpp:1064)
```

### Steps to reproduce

This script creates a simple GDScript from a string of source code, creates an instance and calls a method on it.
```
extends SceneTree

func _init():
	var script_source = '' + \
	"func hello_world():\n" + \
	"\tprint('--- hello world ---')"

	print(script_source)

	var DynScript = GDScript.new()
	DynScript.source_code = script_source
	print('pre-reload')
	DynScript.reload()
	print('post-reload')

	var inst = DynScript.new()
	inst.hello_world()

	quit()

```
The output shows the error occurs on the `reload` call.

```
Godot Engine v4.0.alpha15.official.432b25d36 - https://godotengine.org
Vulkan API 1.1.216 - Using Vulkan Device #0: AMD - AMD Radeon Pro 450
 
Registered camera FaceTime HD Camera (Built-in) with id 1 position 0 at index 0
func hello_world():
        print('--- hello world ---')
pre-reload
ERROR: Attempt to open script '' resulted in error 'File not found'.
   at: load_source_code (modules/gdscript/gdscript.cpp:1064)
post-reload
--- hello world ---
```

### Minimal reproduction project

See steps to reproduce

### LINKED ISSUE #68211: Can't preload a scene in autoload if that scene uses the autoload
### Godot version

4.0 beta4

### System information

Windows 10 x64

### Issue description

When you have an Autoload and do `preload("scene.tscn")`, it will fail *at runtime* if that scene refers to Autoload in a script. This wasn't happening in beta3.

### Steps to reproduce

Just run MRP

### Minimal reproduction project

[PreloadBug.zip](https://github.com/godotengine/godot/files/9929400/PreloadBug.zip)

### PR DESCRIPTION
**Pull request by adamscott**
# TL;DR
This PR makes possible to use cyclic references in GDScript 2.0, i.e. preload class (or use by class name) `A` in `B` and `B` in `A`, preload cyclic scenes, use typing in addons.

# Summary
This PR tweaks the engine to accept and support cyclic references.

# What it tries to solve
The current GDScript engine blocks cyclic references as this would normally lead to memory leaks. Why? Because cyclic references artificially increase the refcount of gdscripts.

## Standard case
Let's say `Main` loads `A` that loads `B`.

Here, `Main` reference count is 1 (referenced by the engine), `A` is 1 (referenced by `Main`) and `B` is 1 (referenced by `A`).

When the engine unloads, `Main` reference count will be decremented by 1 and will be deleted, because its reference count will hit 0. `A` and `B` will also be deleted because `A` lost his reference from `Main` and `B` will lose its reference from `A` later.

## Current cyclic reference issue
Currently, the engine makes it so that using cyclic references is impossible. Why, you say?

Let's bring back our example, but with a cyclic reference. Let's say `Main` loads `A` that loads `B` that loads back `A`.

Here, `Main` reference count is 1 (referenced by the engine), `A` is 2 (referenced by `Main` and `B`) and `B` is 1 (referenced by `A`).

Do you see the issue? When `Main` will be deleted, there will be no way to delete `A` and `B`. `A` will lose its reference to `Main` and will decrement, but it will not be deleted as `A` reference count is now 1. `B` is not deleted because it didn't lose its reference to `A`.

So, the answer is: the engine makes cyclic references impossible due to memory leaks concerns. That explains errors thrown by the parser or the analyzer like `Constant value uses script from "res://b.gd" which is loaded but not compiled`.

# Proposed solution
## Cyclic dependency detection
There is no way to use the reference count as a mean to know if a cyclic `Ref<RefCounted>` needs to be disposed of. If `A` and `B` refers to themselves a number of times, the reference count will skyrocket and it would not be easy to track down the exact number of times the count has been incremented.

If, someday or someone, comes up with a reliable way to detect these, it would be the ideal solution.

Meanwhile, to fix this issue, I propose to use the existing `SelfList<GDScript> script_list` found in the `GDScript` class. This list holds each `GDScript` instance.

Take this table as basis for my following example:

| Script list | Script constants |
|-|-|
| `Main` | `A`, `B`, `X` |
| `A` | |
| `B` | `C` |
| `C` | `D`, `E` |
| `D` | |
| `E` | `F` |
| `F` | `E` |
| `X` | `Y` |
| `Y` | `F`, `Z` |
| `Z` | |

On the left column, each script contained in `script_list` and on the right one, each script referenced, contained in its constants (script constants, function constants, ...).

In the example, if `B` is disposed, `C` and `D` will be too, but not `E` and `F`. How to make sure they are disposed correctly? And how to make sure to not dispose any script that can be legitimately used by another one?

When we dispose of `B`, we can check the dependencies of its dependencies. After all, there's a good chance that those will be disposed of with `B`. So, `B` will check its `get_must_clear_dependencies()`.

### "Must clear" dependencies
`GDScript::get_must_clear_dependencies()` is called in `GDScript::clear()` to know which dependencies must be forcibly cleared.

The process may seem complicated, but it's quite simple. Let's say `Main` runs `get_must_clear_dependencies()`.

1. Get a dependencies set. These dependencies includes all the dependencies of the script dependencies;
2. Get the inverted dependencies of each dependency of set 1;
3. For each dependency of set 1, if one their inverted dependencies (step 2) is outside of the dependencies of step 1, add the dependency (and it's dependencies) to a "can't clear" set;
4. Filter out each dependency that appears in the "can't clear" set of step 3;
5. Return the set of step 4.

With this, we know for a fact that each dependency in the "must_clear" set can be deleted without impacting the rest of the scripts, even if their reference count is high. That means that it's high only because of cyclic references.

By clearing each of those scripts (`GDScript::clear()` clears all the constants holding scripts), their reference count will necessarily drop to zero, so they will be disposed without any need of hacks.

#### Example

cyclic-dependency-detection-Page-2 drawio

##### Must clear dependencies of `Main`
Must clear dependencies of `Main` is quite simple. It's every `GDScript` because every script comes from `Main`.

The direct dependencies of `Main` are `A`, `B` and `X`, but as it includes all the dependencies of the dependencies, it includes every class in the diagram.

| Class | Inverted dependencies |
|-|-|
| `A` | `Main` |
| `B` | `Main` |
| `C` | `B` |
| `D` | `C` |
| `E` | `C`, `F` |
| `F` | `E`, `Y` |
| `X` | `Main` |
| `Y` | `X` |
| `Z` | `Y` |

As every class is a dependency of `Main`, "can't clear" set is empty.

As "can't clear" is empty, the dependencies stay the same.

It returns every classes.

##### Must clear dependencies of `B`
This is where `must_clear_dependencies` shine, because it doesn't clear everything this time. Based on the algorithm, only `C` and `D` can be cleared without any consequences, as `E` and `F` are used by `Y`.

| Class | Dependencies |
|-|-|
| `B` | `C`, `D`, `E`, `F` |

The direct dependency of `B` is `C`, but as it includes all the dependencies of the dependencies, it includes `D`, `E` and `F`.

| Class | Inverted dependencies |
|-|-|
| `C` | `B` |
| `D` | `C` |
| `E` | `C`, `F` |
| `F` | `E`, `Y` |

`Y` is outside of `B` (itself), `C`, `D`, `E` and `F`. So, we add `F`, `E` and `Y` to the "can't clear" set.

We remove `F` and `E` from the dependencies.

It returns `C` and `D`.

## Backup
If, for some reason, a script was able to slip out of the process, it still has a reference to `script_list`. Then, we can call `clear()` in the loop found in `GDScriptLanguage::~GDScriptLanguage()` for script instances still left. This adds the ability to force the clear of internal variables of a script, which can trigger the reference count decrement of other scripts.

# Known issues
- ✔️ ~~Code completion isn't working for cyclic references~~ 
  - Bug present in 4.0beta2 for in-game scripts. The method list does not update at all until a refresh. Code completion for this PR does not show issues other than current ones;
- ✔️ ~~The code works, but the cleaning isn't optimal. I found a reliable way to calculate cyclic references (see `GDScript::get_cyclic_references_count()`), but my efforts to clear dynamically the script failed. It seems the `unreference()` function is somewhat unreliable.~~ 
  - Implemented with success, clearing GDScript with `GDScript::clear()` and `GDScript::get_must_clear_dependencies()`;
- ❌ For some reason, GDScript instances can still hold `Shape2D` references, even if `PhysicsServer2D` singleton was destructed, which leads to memory leaks.
- ❌ Same thing for `Shape3D`

# Code example
So, this code works with this PR, which returns this error on `master`: `Constant value uses script from "res://b.gd" which is loaded but not compiled.`:
```gdscript
# main.gd
const A = preload("res://a.gd")

func _ready() -> void:
	A.test()  # The console will print: "A.HELLO_WORLD: hello, world!"
```
```gdscript
# a.gd
extends Node

const B = preload("res://b.gd")

const HELLO_WORLD: = "hello, world!"

static func test() -> void:
	B.test()

	# Test cyclic `is` keyword
	var b_instance: = B.new()
	if b_instance is B:
		prints("b_instance is B")  # The console will print: "b_instance is B"
	b_instance.queue_free()
```
```gdscript
# b.gd
extends Node

const A = preload("res://a.gd")

static func test() -> void:
	prints("A.HELLO_WORLD:", A.HELLO_WORLD)

	# Test cyclic `is` keyword
	var a_instance: = A.new()
	if a_instance is A:
		prints("a_instance is A")  # The console will print: "a_instance is A"
	a_instance.queue_free()
```

# Minimal reproduction project:
[cyclic3.zip](https://github.com/godotengine/godot/files/9543713/cyclic3.zip)

# Fixes
Fixes #21461 - Some usages of `class_name` can produce cyclic errors unexpectedly
Fixes #32165 - Cyclic Errors After Autoload of Imported Asset
Fixes #41027 - Cyclic reference error in GDScript 2.0
Fixes #58551 - Can't preload a scene in AutoLoad script when the scene's script references the AutoLoad
Fixes #58181 - GDScript 2.0: Cannot preload cyclic const script references
Fixes #58871 - Cyclic Autoload Singleton Plugin Bug
Fixes #61043 - New cyclic reference error with autoload and preloaded script
Fixes #65263 - GDScript reload generates error when created dynamically (no backing script)
Fixes #68211 - Can't preload a scene in autoload if that scene uses the autoload

# Does not fix (yet)
#61386 - [4.x regression] AutoLoad scenes (not scripts) do not support implicit types

# Notes
This PR follows up #65752.

### CODE REVIEW

**Comment by dalexeev** [comment]
Please note: cyclic references (`RefCounted`-related issue), cyclic dependencies (a bug in GDScript) and cyclic definitions/calls (a user error, not a GDScript bug) are different things.

**Comment by adamscott** [comment]
> Please note: cyclic references (`RefCounted`-related issue), cyclic dependencies (a bug in GDScript) and cyclic definitions/calls (a user error, not a GDScript bug) are different things.

I renamed the PR title.

File: modules/gdscript/tests/gdscript_test_runner.cpp [hunk 1]
```diff
@@ -251,7 +251,10 @@ bool GDScriptTestRunner::make_tests_for_dir(const String &p_dir) {
 				return false;
 			}
 		} else {
-			if (next.get_extension().to_lower() == "gd") {
+			if (next.ends_with(".notest.gd")) {
```
Comment (adamscott) [inline modules/gdscript/tests/gdscript_test_runner.cpp:254]: I added the `.notest.gd` exception here, as it was defined elsewhere, but not used. Practical for `.gd` files that are loaded by tests, but not tests themselves.

**Comment by adamscott** [comment]
Renamed the PR to "Fix cyclic references in GDScript 2.0", as this fixes a bug (missing cyclic references support). It is not a "new feature" per se.

**Comment by adamscott** [comment]
I fixed #67714 in this PR because I used code that I added in this one, but I could separate the fix into another PR, if needed.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 2]
```diff
@@ -3102,14 +3103,37 @@ void GDScriptAnalyzer::reduce_identifier(GDScriptParser::IdentifierNode *p_ident
...
-			if (autoload.path.to_lower().ends_with(GDScriptLanguage::get_singleton()->get_extension())) {
+			if (ResourceLoader::get_resource_type(autoload.path) == "GDScript") {
 				Ref<GDScriptParserRef> singl_parser = get_parser_for(autoload.path);
 				if (singl_parser.is_valid()) {
 					Error err = singl_parser->raise_status(GDScriptParserRef::INTERFACE_SOLVED);
 					if (err == OK) {
 						result = type_from_metatype(singl_parser->get_parser()->head->get_datatype());
 					}
 				}
+			} else if (ResourceLoader::get_resource_type(autoload.path) == "PackedScene") {
```
Comment (adamscott) [inline modules/gdscript/gdscript_analyzer.cpp:3114]: Here's the fix for #67714.

**Comment by bitbrain** [comment]
Tested this thoroughly with my game and no problems whatsoever. The only issue still persisting is this:

> The object-derived class of argument 3 (RefCounted (ForgingAttributes)) is not a subclass of the expected argument class.

Which I think is out of scope for this PR and not mentioned by any of the issues above but is rather described here https://github.com/godotengine/godot/issues/64915 and probably should be addressed in a separate PR.

**Comment by adamscott** [comment]
I added the fix of #67850 inside this PR as the build tests seems to fail in the former. Probably because of cyclic dependencies, which are handled in this one.

File: modules/gdscript/gdscript_compiler.cpp [hunk 3]
```diff
@@ -165,7 +165,14 @@ GDScriptDataType GDScriptCompiler::_gdtype_from_datatype(const GDScriptParser::D
 						}
 					}
 					if (result.script_type_ref.is_null()) {
-						result.script_type_ref = GDScriptCache::get_shallow_script(p_datatype.script_path, main_script->path);
+						Ref<GDScript> scr;
+						if (!class_type->fqcn.is_empty()) {
+							scr = GDScript::get_script_by_fully_qualified_name(class_type->fqcn);
```
Comment (adamscott) [inline modules/gdscript/gdscript_compiler.cpp:170]: This is the fix for #64915

File: modules/gdscript/gdscript_analyzer.cpp [hunk 4]
```diff
@@ -3102,14 +3103,37 @@ void GDScriptAnalyzer::reduce_identifier(GDScriptParser::IdentifierNode *p_ident
...
+				Ref<PackedScene> scene = GDScriptCache::get_scene(autoload.path);
+				if (scene->get_state().is_valid()) {
+					const int ROOT_NODE = 0;
+					Ref<SceneState> state = scene->get_state();
+					for (int i = 0; i < state->get_node_property_count(ROOT_NODE); i++) {
```
Comment (RandomShaper) [inline modules/gdscript/gdscript_analyzer.cpp:3119]: Why only check the root node's `script` property? How does this approach handle, for instance, scripts referenced by subnodes, potentially from custom properties?

File: modules/gdscript/gdscript_analyzer.cpp [hunk 5]
```diff
@@ -3235,9 +3259,26 @@ void GDScriptAnalyzer::reduce_preload(GDScriptParser::PreloadNode *p_preload) {
...
+
+			// Must load GDScript and PackedScenes separately to permit cyclic references
+			// as ResourceLoader::load() detect and reject those.
+			if (ResourceLoader::get_resource_type(p_preload->resolved_path) == "GDScript") {
+				Ref<GDScript> res = GDScriptCache::get_shallow_script(p_preload->resolved_path, parser->script_path);
+				p_preload->resource = res;
+				if (p_preload->resource.is_null()) {
+					push_error(vformat(R"(Could not preload resource script "%s".)", p_preload->resolved_path), p_preload->path);
+				}
+			} else if (ResourceLoader::get_resource_type(p_preload->resolved_path) == "PackedScene") {
```
Comment (RandomShaper) [inline modules/gdscript/gdscript_analyzer.cpp:3271]: What would happen with other types of resources (maybe custom ones) that may have a reference to a script?

File: modules/gdscript/gdscript.cpp [hunk 6]
```diff
@@ -1183,6 +1253,83 @@ String GDScript::_get_gdscript_reference_class_name(const GDScript *p_gdscript)
...
+		return nullptr;
+
+	Object *obj = p_variant;
+	if (obj == nullptr)
+		return nullptr;
+
+	return Object::cast_to<GDScript>(obj);
+}
+
+void GDScript::_get_dependencies(RBSet<GDScript *> &p_dependencies, const GDScript *p_except) {
```
Comment (RandomShaper) [inline modules/gdscript/gdscript.cpp:1268]: How would this function, and the overall approach, interact with a mixture of, say, GDScrip and C# classes?

File: modules/gdscript/gdscript.cpp [hunk 7]
```diff
@@ -1256,33 +1403,45 @@ void GDScript::_init_rpc_methods_properties() {
...
-	{
-		MutexLock lock(GDScriptLanguage::get_singleton()->mutex);
-
-		while (SelfList<GDScriptFunctionState> *E = pending_func_states.first()) {
-			// Order matters since clearing the stack may already cause
-			// the GDSCriptFunctionState to be destroyed and thus removed from the list.
-			pending_func_states.remove(E);
-			E->self()->_clear_stack();
+void GDScript::clear() {
+	if (clearing)
```
Comment (RandomShaper) [inline modules/gdscript/gdscript.cpp:1407]: Style issue: braceless `if`.

**Review by RandomShaper — COMMENTED** [review]
In general, I'm a bit concerned with this approach. While the overall idea and algorithm for detecting cycles is ingenious, I feel that its materialization is maybe too Spartan, if you know what I mean. I also have to admit that I can't deeply assess all the changes. However, this is the best option we have now and seems to fix a bunch of issues.

That said, I'd like to have my attempt at fixing the cyclic references issue. However, that doesn't mean this can't be given a go and, if I am (or somebody else is) able to come up with something better, we'd replace this by the new one. The problem with that is that the reversion may be tricky if say, a few weeks or months pass and the code keeps changing, so we may end up with somewhat dirty code.

Sounds like a project management decision? CC @akien-mga

**Comment by RandomShaper** [comment]
Oh, and, regardless what happens in the end, let me congratulate you for this PR. I know this is a lot of work and thinking, and you've managed to make a reasonable fix to one complicated problem.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 4 above)
Comment (adamscott) [reply modules/gdscript/gdscript_analyzer.cpp:3119]: Because we're in `reduce_identifier`. Let's say that I have `MyAutoload.tscn` loaded as an autoload `MyAutoload`. That part checks if there's an autoload scene named `MyAutoload`. If so, it returns the main script.

But I need to test, as you said, subnodes and other instances.

Otherwise, maybe I could add support for generic scripts (with added checks for GDScript afterward).

File: modules/gdscript/gdscript_analyzer.cpp (hunk 5 above)
Comment (adamscott) [reply modules/gdscript/gdscript_analyzer.cpp:3271]: We're in `reduce_preload()`, so it parses the `preload()` value. If a GDScript is loaded otherwise, through other resources, the standard loader should work.

File: modules/gdscript/gdscript.cpp (hunk 6 above)
Comment (adamscott) [reply modules/gdscript/gdscript.cpp:1268]: Good question. Like, if `A.gd` refers to `B.cs` and `B.cs` refers to `C.gd`? Mmm.

File: modules/gdscript/gdscript.cpp (hunk 7 above)
Comment (adamscott) [reply modules/gdscript/gdscript.cpp:1407]: Fixed all braceless `if` from the PR.

**Comment by adamscott** [comment]
> In general, I'm a bit concerned with this approach. While the overall idea and algorithm for detecting cycles is ingenious, I feel that its materialization is maybe too Spartan, if you know what I mean.

While I agree with the statement, I must point out that the "Spartan" materialization of my approach is only a small part of my PR. I don't see how we could untangle cyclic GDScripts without forcing clearing, even if we could detect perfectly which references are cyclic and inflating the reference count (and how many times).

The cyclic detection part of my PR counts for ~150 lines. The rest is clearing GDScripts, permitting cyclic references, removing cyclic references checks, and fixes miscellaneous issues.

I'm not downplaying the difficulties that could occur trying to refactor that part of code, but I'm confident that my code will fixes numerous issues and will bring more benefits than difficulties.

Thanks again for the review, @RandomShaper.

**Comment by bitbrain** [comment]
My 2 cents on this: considering **how many** issues this PR is addressing, this non-ideal solution might be preferable over no solution at all (assuming this PR does not introduce new issues).

File: modules/gdscript/gdscript.cpp (hunk 6 above)
Comment (adamscott) [reply modules/gdscript/gdscript.cpp:1271]: I don't think it would affect this. C# cannot "preload" GDScript, so no C# constants can hold GDScripts. Neither is it possible to preload C# scripts, as it results to this:

```
SCRIPT ERROR: Parse Error: Preload file "res://HelloWorld.cs" has no resource loaders (unrecognized file extension).
          at: GDScript::reload (res://GameMenu.gd:5)
```

In the development of this PR, I mostly found out that it's constants that cause problems with cyclic dependencies, not dynamic loading of scripts.

So, I don't think it's a problem.

**Comment by adamscott** [comment]
I added two examples of my cyclic dependencies clearing workflow, for review and archive purposes.

**Comment by Lippanon** [comment]
Trying to port a big project from 3.x to 4.x, when running in editor I kept running into cyclic reference errors, so I tried this PR: it solved all the cyclic reference errors and I was able to run the project but the console gets flooded by this error at the start, it doesn't stop execution and it runs fine after the start:
error

I can't seem to debug where it's coming from exactly, the editor doesn't tell me what line is problematic, I think from an autoload but I can't pin it down. I understand this isn't much to go by and I can't provide a MRP but I thought I'd mention it anyway.

**Comment by adamscott** [comment]
@Lippanon I found out the likely source of your problem! I just pushed a new commit, it should be fixed by now.

**Comment by cridenour** [comment]
I have a medium sized project I've been working on since alpha6.

```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Godot Scene                    148           2445              0          17272
GDScript                       116           1959            639           5203
Godot Resource                  64            194              0           3895
SQL                              4             65             36            467
XML                              1              0              0            137
SVG                              5              0              0             42
YAML                             1             10             18             31
Python                           1              3              0             24
INI                              1              0              0              4
-------------------------------------------------------------------------------
SUM:                           341           4676            693          27075
-------------------------------------------------------------------------------
```

I just tested this (cherry picked on top of beta-3 to keep my gdextension addons working) and it worked without error or any issue I could find. Performance seemed the same as well.

Would be a welcome addition so I can get to 100% typed.

File: modules/gdscript/gdscript.cpp [hunk 8]
```diff
@@ -872,11 +872,8 @@ Error GDScript::reload(bool p_keep_state) {
 		if (source_path.is_empty()) {
 			source_path = get_path();
 		}
-		if (!source_path.is_empty()) {
-			MutexLock lock(GDScriptCache::singleton->lock);
```
Comment (RandomShaper) [inline modules/gdscript/gdscript.cpp:876]: Not sure about the removal of this lock. `shallow_gdscript_cache` seems to be accessed within a lock always.

**Review by RandomShaper — COMMENTED** [review]
At this point I'm more inclined towards the give this a deserved go option. Just added a new comment.

File: modules/gdscript/gdscript.cpp (hunk 8 above)
Comment (adamscott) [reply modules/gdscript/gdscript.cpp:876]: Oh! This is a leftover of a previous refactor. Thanks, I'll reinstate the lock.

**Review by RandomShaper — APPROVED** [review]

**Comment by akien-mga** [comment]
Great work! While this seems ready, I'll delay merging this by a few days to first put out beta 4 with the changes which have been tested while I was on holiday. I'll merge bigger changes like this afterwards for beta 5 (due sometime next week).

File: scene/resources/packed_scene.cpp [hunk 9]
```diff
@@ -43,6 +43,11 @@
 #include "scene/main/missing_node.h"
 #include "scene/property_utils.h"
 
+#include "modules/modules_enabled.gen.h" // For GDScript
```
Comment (reduz) [inline scene/resources/packed_scene.cpp:46]: This should not happen, we should find a different way to do this without having an include to modules from scene.

**Review by reduz — DISMISSED** [review]

**Comment by reduz** [comment]
I would like a bit more detail explaining why the changes are needed into PackedScene, since technically this should only be relevant for GDScript.

**Comment by reduz** [comment]
Just to clarify, the original code in GDScript is meant to avoid cyclic references for GDScript files. Cyclic references in scenes are not workaroundable, the scene is broken if you save this.

**Comment by adamscott** [comment]
> Cyclic references in scenes are not workaroundable, the scene is broken if you save this.

My PR permits cyclic references with `preload()` and global classes. It does not permit cyclic resources other than that, and it does not intend to fix that.

Though, I realize that there's maybe an underlining issue that I did not address. That my changes in `PackedScene` were about treating a symptom, not treating the problem itself. Currently, even if `GDScriptCache` is holding a `Ref<PackedScene>`, the latter reference count can drop to 0 (and be disposed of).

I'll investigate and return with some answers.

File: modules/gdscript/gdscript_cache.cpp [hunk 10]
```diff
@@ -245,13 +339,71 @@ Error GDScriptCache::finish_compiling(const String &p_owner) {
...
+
+void GDScriptCache::clear_unreferenced_scenes() {
+	if (singleton == nullptr) {
+		return;
+	}
+
+	MutexLock lock(singleton->mutex);
+
+	for (KeyValue<String, HashSet<String>> &E : singleton->packed_scene_dependencies) {
+		if (E.value.size() > 0 || !ResourceLoader::is_imported(E.key)) {
```
Comment (adamscott) [inline modules/gdscript/gdscript_cache.cpp:374]: Removed any modifications to `PackedScene` files. Added `GDScriptCache::clear_unreferenced_scenes()` that clears cached packed scenes if they are imported.

The import check is done to prevent a "cyclic load" error from `ResourceLoader`.

The way "cyclic scene references" work is pretty simple. When GDScript asks for a scene with `preload()`, a empty scene is cached first, then is reloaded with the right path. So, if another `preload()` is called within the loading of the first scene, as the empty (and loading) scene is cached, it's possible to return its reference. See [modules/gdscript/gdscript_cache.cpp:357](https://github.com/godotengine/godot/pull/67714/files#diff-a5502b90c5ce669d474f92292a3f2d6ef72ac9e1f1687534e3abce6b2640e703)

Unfortunately, I don't know how I could call `GDScriptCache::clear_unreferenced_scenes()` after the initial load.

**Comment by bitbrain** [comment]
I discovered an issue with this PR when using [Dialogic](https://github.com/coppolaemilio/dialogic).

Steps to reproduce:

1. create empty project in Godot 4
2. [download latest version](https://github.com/coppolaemilio/dialogic/archive/refs/heads/main.zip) and place dialogic into `addons` folder

When starting the project, this PR produces the following error:
```
SCRIPT ERROR: Compile Error: Identifier not found: dialogic
          at: GDScript::reload (res://addons/dialogic/Events/End Branch/event.gd:8)
```
Looking into this, the problem seems to be related to not being able to access a parent node's variable for some reason.

This issue does not happen on the latest `master` branch of Godot.

**Comment by adamscott** [comment]
> SCRIPT ERROR: Compile Error: Identifier not found: dialogic
>           at: GDScript::reload (res://addons/dialogic/Events/End Branch/event.gd:8)

This is weird. If you move the `dialogic` variable declaration to be on top of the parent class file, the error disappears. There's something wrong going on with the parsing of the parent file.

**Comment by rune-scape** [comment]
I was having a problem, and realized it was introduced in this pr (or this pr revealed it).
[godot-editor-removed-path.zip](https://github.com/godotengine/godot/files/9936200/godot-editor-removed-path.zip)
open "T1.gd" edit it (add a new line) and save, then open "T2.gd". T1 becomes "[unsaved]" in the file list.

**Comment by adamscott** [comment]
@bitbrain and @rune-scape, both of your issues should be resolved by now.

**Comment by rune-scape** [comment]
@adamscott yep, fixed gj 👍

File: modules/gdscript/gdscript.cpp [hunk 11]
```diff
@@ -2387,6 +2581,44 @@ Ref<GDScript> GDScriptLanguage::get_orphan_subclass(const String &p_qualified_na
 	return Ref<GDScript>(Object::cast_to<GDScript>(obj));
 }
 
+Ref<GDScript> GDScriptLanguage::get_script_by_fully_qualified_name(const String &p_name) {
```
Comment (rune-scape) [inline modules/gdscript/gdscript.cpp:2584]: @adamscott this technically fixes #65935, but it doesnt fix the underlying issue in gdtype_from_datatype and _update_exports, and I think its outside the scope of this pr. ive been bathing in subclass code for over a month now and i have a few PRs in the works to bring subclasses closer to the stability of a script file and id like to have the honor of fixing my own issue

Comment (adamscott) [reply modules/gdscript/gdscript.cpp:2584]: You meant #65953!

Comment (adamscott) [reply modules/gdscript/gdscript.cpp:2584]: I modified the description of my PR to add a note about the fix of #65953. I think your PR should be merged before or after mine (in order to use your fix.)

Capture d’écran du 2022-11-10 08-43-19

File: modules/gdscript/gdscript_compiler.cpp [hunk 12]
```diff
@@ -2275,6 +2299,30 @@ Error GDScriptCompiler::_parse_class_level(GDScript *p_script, const GDScriptPar
...
+				Error err = OK;
+				GDScriptCache::get_full_script(base->get_path(), err, main_script->path);
+				if (err != OK) {
+					return err;
+				}
+
+				// Test if the extends refers to a global class.
+				// Converts the extends array to a fully qualified name.
+				String base_path = "";
+				for (int i = 0; i < p_class->extends.size(); i++) {
```
Comment (rune-scape) [inline modules/gdscript/gdscript_compiler.cpp:2312]: this doesn't take into account extends_path

File: modules/gdscript/gdscript_compiler.cpp [hunk 13]
```diff
@@ -2275,6 +2299,30 @@ Error GDScriptCompiler::_parse_class_level(GDScript *p_script, const GDScriptPar
...
+					if (i > 0) {
+						base_path += "::";
+					}
+					base_path += p_class->extends.get(i);
+				}
+				Ref<GDScript> external_base = GDScriptLanguage::get_singleton()->get_script_by_fully_qualified_name(base_path);
+				if (external_base != base && p_class->extends.size() > 1) {
+					for (int i = 1; i < p_class->extends.size(); i++) {
+						StringName extend = p_class->extends.get(i);
+						base = base->constants[extend];
```
Comment (rune-scape) [inline modules/gdscript/gdscript_compiler.cpp:2322]: shouldn't this have been handled in `get_script_by_fully_qualified_name`?

**Comment by adamscott** [comment]
@rune-scape Could you join the developers chat? @akien-mga just mentionned your PR. 
https://chat.godotengine.org/channel/scripting

File: modules/gdscript/gdscript.cpp [hunk 14]
```diff
@@ -629,6 +629,10 @@ void GDScript::_update_doc() {
 		}
 	}
 
+	for (KeyValue<StringName, Ref<GDScript>> &E : subclasses) {
+		E.value->_update_doc();
```
Comment (adamscott) [inline modules/gdscript/gdscript.cpp:633]: @rune-scape I restored the `_update_doc()` call here [(and removed it in `gdscript_compiler.cpp`)](https://github.com/godotengine/godot/pull/67714/files#diff-43fc69f36899762bf59f1cd731dfc0be1ff0d2b648271e443944e4116c1c28a6L2578) because it crashed otherwise on @KoBeWi's large project.

Capture d’écran du 2022-11-15 04-12-49

Comment (rune-scape) [reply modules/gdscript/gdscript.cpp:633]: this looks exactly like my regression bug fixed by #68717! this may fix it because the subclass types aren't compiled yet, so theres no invalid data yet. can you see if https://github.com/godotengine/godot/commit/95a85c9058e9c2a7eab3f5a272ffbe741a6750d1 fixes this?

Comment (adamscott) [reply modules/gdscript/gdscript.cpp]: 95a85c9 seems to fix the issue! Thanks.

**Comment by bitbrain** [comment]
@adamscott out of curiosity: will this also fix https://github.com/godotengine/godot/issues/24146?

**Comment by adamscott** [comment]
> @adamscott out of curiosity: will this also fix #24146?

I just tested out the 4.0 MRP and unfortunately no. This PR does not change how PackedScenes and resources work internally.

File: modules/gdscript/gdscript.cpp [hunk 15]
```diff
@@ -1253,33 +1404,58 @@ void GDScript::_init_rpc_methods_properties() {
...
+		E->skip_dependencies = false;
+		GDScriptCache::remove_script(E->get_path());
 	}
 
+	RBSet<StringName> member_function_names;
 	for (const KeyValue<StringName, GDScriptFunction *> &E : member_functions) {
-		memdelete(E.value);
+		member_function_names.insert(E.key);
+	}
+	for (const StringName &name : member_function_names) {
```
Comment (akien-mga) [inline modules/gdscript/gdscript.cpp:1438]: Warning here (I don't know if the new GitHub Action that highlights it in the diff view also sends a notification).

Comment (adamscott) [reply modules/gdscript/gdscript.cpp]: Fixed by renaming the variable.

**Comment by akien-mga** [comment]
Thanks a ton for your work! Really impressive and thorough!

**Comment by tinmanjuggernaut** [comment]
I just tried beta 6. This isn't quite working. 

```
GameInit.gd # Autoloaded as 'class_name Game'
     var player: Player   # CRC errors before. In beta 6 unlocatable, non-CRC error. Works if no type.
```

Player and Enemy both inherit Unit. Many classes including Enemy reference `Game.*`, especially `Game.player`.

In previous versions we had CRC errors in Enemy when Player was typed as shown above, and we referenced `Game.player`. I received an editor notification highlighting the exact line in GameInit.gd.

Now in Beta 6, I get the following error in the console upon loading the editor or the game, and there's no reference at all to the GDScript location. The editor does load scenes, but the game does not.

```
ERROR: Condition "!base->is_valid()" is true. Returning: ERR_BUG
   at: _populate_class_members (modules/gdscript/gdscript_compiler.cpp:2287)
```

In the editor I'm presented with no info:

image

The Errors(2) shows the same error listed on the console, but clicking the lines don't take me to any gdscript. So if I didn't already know exactly where the CRC error is, I'd never find it. 

Someone else has the same issue, likely caused by a CRC error they don't know about. #69213. If I can make an MRP, I'll make an issue or contribute to this one.

**Comment by adamscott** [comment]
@tinmanjuggernaut Please create an issue and a MRP if possible. The `.cpp` path helps, but by itself, I cannot find the root of the issue. The issue you're experiencing can be related to this PR, but it's not necessarily the case.

@rune-scape Does it ring a bell to you?

**Comment by tinmanjuggernaut** [comment]
#69259 fixed my errors above using cyclic references. Thanks @adamscott .
