### PR TITLE
Fix issue where `set_global_position(global_position)` in `Control` resulted in a different result than `global_position`

### LINKED ISSUE #87354: Control.set_global_position(global_position) doesn't work after rotated around custom pivot
### Tested versions

Godot v4.2.stable

### System information

Godot v4.2.stable - macOS 13.6.1 - GLES3 (Compatibility) - ANGLE (AMD, ANGLE Metal Renderer: AMD Radeon Pro 560X, 版本13.6.1（版号22G313）) - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 Threads)

### Issue description

When a Control's pivot offset is set to somewhere other than (0, 0) and rotated, set_global_position(global_position) will move the Control far away. 

### Steps to reproduce

```GDScript
extends ColorRect

func _ready():
    pivot_offset = size
    rotation_degrees = 90
    for i in 36:
        set_global_position(global_position)
        await get_tree().process_frame
        print('%s %s %s'%[position, global_position, size])

```

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Rindbee**
Previously, the case where the pivot point was not at the origin was ignored.

Fix #87354.

### CODE REVIEW

File: scene/gui/control.cpp [hunk 1]
```diff
@@ -1425,7 +1425,18 @@ void Control::set_global_position(const Point2 &p_point, bool p_keep_offsets) {
 		inv = data.parent_canvas_item->get_global_transform().affine_inverse();
 	}
 
-	set_position(inv.xform(p_point), p_keep_offsets);
+	Point2 new_position;
+	if (data.pivot_offset.is_zero_approx() || (data.scale.is_equal_approx(Vector2(1.0f, 1.0f)) && Math::is_zero_approx(Math::fmod((double)data.rotation, Math_TAU)))) {
```
[the remark this answers is not in the document]
Comment (Rindbee) [reply scene/gui/control.cpp:1429]: Thanks for your suggestion.

File: scene/gui/control.cpp [hunk 2]
```diff
@@ -1419,13 +1419,29 @@ void Control::_set_global_position(const Point2 &p_point) {
...
 	}
 
-	set_position(inv.xform(p_point), p_keep_offsets);
+	Point2 new_position;
+	if (data.pivot_offset.is_zero_approx() || (data.scale.is_equal_approx(Vector2(1.0, 1.0)) && Math::is_zero_approx(Math::fmod(data.rotation, (real_t)Math_TAU)))) {
+		// The pivot point is at the origin or simply translated.
+		new_position = inv.xform(p_point);
+	} else {
+		inv = Transform2D(0.0, -get_position()) * inv; // Translation transformation in parent space.
+		inv = _get_internal_transform().affine_inverse() * inv; // Internal transformation relative to pivot point.
```
Comment (kleonc) [inline scene/gui/control.cpp:1439]: This is equivalent to `inv = get_transform().affine_inverse() * inv;` as:
```
   _get_internal_transform().affine_inverse() * Transform2D(0.0f, -get_position())
== _get_internal_transform().affine_inverse() * Transform2D(0.0f, get_position()).affine_inverse()
== (Transform2D(0.0f, get_position()) * _get_internal_transform()).affine_inverse()
== get_transform().affine_inverse()
```
(see #84840)

Further, given `inv` is initially the inverse of the parent global transform:
```
   get_transform().affine_inverse() * parent_global_transform.affine_inverse()
== (parent_global_transform * get_transform()).affine_inverse()
== get_global_transform().affine_inverse()
```

So the whole calculation could be simplified like:
```diff
diff --git a/scene/gui/control.cpp b/scene/gui/control.cpp
index 349102fafb..c352dd4a14 100644
--- a/scene/gui/control.cpp
+++ b/scene/gui/control.cpp
@@ -1419,13 +1419,8 @@ void Control::_set_global_position(const Point2 &p_point) {
 
 void Control::set_global_position(const Point2 &p_point, bool p_keep_offsets) {
 	ERR_MAIN_THREAD_GUARD;
-	Transform2D inv;
-
-	if (data.parent_canvas_item) {
-		inv = data.parent_canvas_item->get_global_transform().affine_inverse();
-	}
-
-	set_position(inv.xform(p_point), p_keep_offsets);
+	Point2 new_position = get_global_transform().affine_inverse().xform(p_point) + get_position();
+	set_position(new_position, p_keep_offsets);
 }
 
 Point2 Control::get_global_position() const {
```

Not sure if it needs a separate case for no pivot offset / (no rotation + unit scale).

File: scene/gui/control.cpp [hunk 3]
```diff
@@ -1419,13 +1419,29 @@ void Control::_set_global_position(const Point2 &p_point) {
...
+
 	Transform2D inv;
 
 	if (data.parent_canvas_item) {
 		inv = data.parent_canvas_item->get_global_transform().affine_inverse();
 	}
 
-	set_position(inv.xform(p_point), p_keep_offsets);
+	Point2 new_position;
+	if (data.pivot_offset.is_zero_approx() || (data.scale.is_equal_approx(Vector2(1.0, 1.0)) && Math::is_zero_approx(Math::fmod(data.rotation, (real_t)Math_TAU)))) {
```
Comment (kleonc) [inline scene/gui/control.cpp:1434]: BTW such check for the rotation would fail in case it's almost `TAU` etc. like `359.999999` degrees (it could be close to no rotation but not near-zero after `fmod`ding it).

Alternative could be e.g. `wrap`ping it into `[-PI, PI]` instead (and then checking only for near-zero). Or just adding here an additional check for near-`TAU`. Not sure if/what is preferred.

File: scene/gui/control.cpp (hunk 2 above)
Comment (Rindbee) [reply scene/gui/control.cpp:1439]: > Not sure if it needs a separate case for no pivot offset / (no rotation + unit scale).

If using its own `get_global_transform()`, no distinction is needed. The `global_transform` might already be cached.

File: scene/gui/control.cpp [hunk 4]
```diff
@@ -1419,13 +1419,15 @@ void Control::_set_global_position(const Point2 &p_point) {
 
 void Control::set_global_position(const Point2 &p_point, bool p_keep_offsets) {
 	ERR_MAIN_THREAD_GUARD;
-	Transform2D inv;
 
-	if (data.parent_canvas_item) {
-		inv = data.parent_canvas_item->get_global_transform().affine_inverse();
+	Transform2D global_transform = get_global_transform();
```
Comment (YuriSizov) [inline scene/gui/control.cpp:1423]: You need to rename it to avoid shadowing. Use `xform` for example.

**Review by kleonc — APPROVED** [review]
AFAICT it works fine now (I've done some testing).

**Comment by kleonc** [comment]
Shouldn't be cherry-picked, it introduced a regression: #89497.
