### PR TITLE
Fixed error spam in create node dialog with custom types.

### LINKED ISSUE #20789: Error spam while searching in the "New Node" dialog while having scripts with "class_name"
**Godot version:**
 e0456f7

**Issue description:**
peek 2018-08-07 15-00

### PR DESCRIPTION
**Pull request by Piet-G**
This should fix #20789 and #20365

### CODE REVIEW

File: editor/create_dialog.cpp [hunk 1]
```diff
@@ -330,7 +330,7 @@ void CreateDialog::_update_search() {
 					break;
 				}
 
-				type = ClassDB::get_parent_class(type);
+				type = (cpp_type ? ClassDB::get_parent_class(type) : "");
```
Comment (akien-mga) [inline editor/create_dialog.cpp]: I'm not convinced this is the correct fix, it defeats the purpose of the while loop so if `""` is what is expected for a non-C++ class, some refactoring would be in order.

Comment (DualMatrix) [reply editor/create_dialog.cpp]: Previously it did indeed return "" for non C++ classes

Comment (willnationsdev) [reply editor/create_dialog.cpp]: @DualMatrix @akien-mga The proper fix for this is to handle the script-supported "get_parent_class" variant present in EditorData, just like is done in the while loop statement (apologies, I must've missed this during my testing). Rather than hardcoding an empty-string response, it should be `ed.script_class_get_base(type)` since this method will check if the script class has an inherited script and whether that inherited script also is a script class to be added to the tree.

Comment (willnationsdev) [reply editor/create_dialog.cpp]: The ScriptServer method will only ever return the base C++ type (since that's all that's needed to create the object). For ClassDB-simulated methods, you have to use the EditorData instance.

**Comment by DualMatrix** [comment]
With @willnationsdev 's advice I properly fixed it using the `ed.script_class_get_base()` function

**Comment by willnationsdev** [comment]
@DualMatrix Thanks for catching this!

**Comment by willnationsdev** [comment]
Well, I thought that would be the fix, but when I tested it just now, I'm still getting error spams, just different ones. I'll try to tinker a bit with this to see if I can help you out.

**Comment by DualMatrix** [comment]
@willnationsdev  Interesting, I haven't encountered that error before in my tests, maybe it has to do with loading the icon of the custom type? I haven't tested that yet

**Comment by willnationsdev** [comment]
@DualMatrix Seems like this is happening because the just-recently-merged script class icons are triggering an error when attempting to load a non-existent icon on a script class that doesn't define one. I'll just go ahead and do a fix for that as well in my own branch (they are two perpendicular Issues).

**Comment by willnationsdev** [comment]
As such, I think this can be merged safely @akien-mga . I'll submit a follow-up for the other problem.

**Comment by akien-mga** [comment]
Thanks!
