### PR TITLE
[MP] Fix broken RPCs after dictionary keys type change

### LINKED ISSUE #96889: RPC is broken in 4.4 dev2
### Tested versions

Only in 4.4 dev2
In 4.4 dev 1 or 4.3 it doesn't happen

### System information

Windows 10, Godot 4.4-dev2

### Issue description

This is happening in dev2 (dev1 is fine):
Screenshot (10)
There are 2 issues:
1. RPC node checksum is failing (don't know why)
2. All RPCs are being called with 0 or sometimes 1 argument

This is what happens in 4.4 dev1 and 4.3:
Screenshot (11)
As you can see, no errors and the project runs fine

ps: I don't know if this may have something to do with it but the editor's autocompletion for `@rpc` is broken

### Steps to reproduce

Use a project with networking features in 4.4 dev2
1. Run 2 instances of the game
2. In one, host the game (there should be no errors yet)
3. Join the game in the second one and there's where all errors should appear

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by Faless**
As part of RPCs processing, they need to be sorted reliably across all peers, so that unique IDs can be assigned to greatly optimize the network layer.

The RPC configuration nodes are stored in dictionaries which, until recently (#70096), always casted StringName keys to String.

Since method names (keys) in the RPC configuration were StringName, a side effect of the above change is that sorting the dictionary keys no longer sort them alphabetically by default (StringName are compared using their pointers).

This commit changes the RPC processing logic to use sort_custom to provide a function that can handle the StringName comparison.

Fixes #96889
Regression from #70096

### CODE REVIEW

File: modules/multiplayer/scene_rpc_interface.cpp [hunk 1]
```diff
@@ -73,14 +73,24 @@ int get_packet_len(uint32_t p_node_target, int p_packet_len) {
 	}
 }
 
+bool SceneRPCInterface::_sort_rpc_names(const Variant &p_l, const Variant &p_r) {
```
Comment (akien-mga) [inline modules/multiplayer/scene_rpc_interface.cpp:76]: You could probably use `StringName::AlphCompare` for this instead of implementing something similar ad hoc?
https://github.com/godotengine/godot/blob/83d54ab2ad476ae265b323c2b88f4623b922f4c6/core/string/string_name.h#L167

Comment (Faless) [reply modules/multiplayer/scene_rpc_interface.cpp:76]: Yeah, I looked into that, the problem is that AlphCompare expects `const StringName &` because it's meant for internal (templated) data structures (`List`/`HashMap`/etc) which implements `sort_custom` as a template function while `Array.sort_custom` expects a callable because it's a bound data type (and the callable takes `const Variant &` arguments).

So I don't think there's a way to reuse it directly. Maybe, we could use it inside `_sort_rpc_names`  when we detect StringName and get (maybe?) a performance optimization? (I don't think the compiler is smart enough to optimize away the string creation otherwise)

Comment (akien-mga) [reply modules/multiplayer/scene_rpc_interface.cpp:76]: Makes sense. BTW I wondered why we're using Variant for the rpc config and the names instead of explicitly Dictionary/String(Name)?

**Review by akien-mga — APPROVED** [review]

File: modules/multiplayer/scene_rpc_interface.cpp (hunk 1 above)
Comment (Faless) [reply modules/multiplayer/scene_rpc_interface.cpp:76]: That's a good question, IIRC originally that was to allow migrating from a dictionary to a refcounted/struct and handle compatibility internally without changing the function signature (that was before we had compatibility methods and so on).

I think at this point we could switch to dictionary (but then, the config of each method would still be composed of "variants" since that's what dictionary values are).

We could even switch to something like `HashMap<StringName,InternalStruct>` but that involves doing copies every time we cross the boundaries (e.g. gdextension ScriptExtension._get_rpc_config), and I'd rather do that in the multiplayer module itself where they can be properly cached.

**Comment by akien-mga** [comment]
Thanks!
