### PR TITLE
Draw a checkerboard behind translucent colors in CodeEdit autocompletion previews

### LINKED ISSUE #89355: Colors in autocomplete don't display transparency.
### Tested versions

4.3.dev4

### System information

Godot v4.3.dev4 - Pop!_OS 22.04 LTS - X11 - GLES3 (Compatibility) - Mesa Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

image

No checkerboard background, like I'd expect, which makes this misleading.

### Steps to reproduce

`const lmofa = Color("ffffff44")`

Then make another variable and see the autocomplete.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Calinou**
This makes translucent colors easier to interpret as such and is consistent with how they're displayed in ColorPicker.

- This closes #89355.

## Preview

Code Complete Translucent Color 1

Code Complete Translucent Color 2

### CODE REVIEW

File: scene/gui/code_edit.cpp [hunk 1]
```diff
@@ -211,7 +211,13 @@ void CodeEdit::_notification(int p_what) {
 							tl->set_horizontal_alignment(HORIZONTAL_ALIGNMENT_RIGHT);
 						} else {
 							if (code_completion_options[l].default_value.get_type() == Variant::COLOR) {
-								draw_rect(Rect2(Point2(code_completion_rect.position.x + code_completion_rect.size.width - icon_area_size.x, icon_area.position.y), icon_area_size), (Color)code_completion_options[l].default_value);
+								const Color color = (Color)code_completion_options[l].default_value;
```
Comment (KoBeWi) [inline scene/gui/code_edit.cpp:214]:
```suggestion
								const Color color = code_completion_options[l].default_value;
```
Not needed.

File: scene/gui/code_edit.cpp [hunk 2]
```diff
@@ -211,7 +211,13 @@ void CodeEdit::_notification(int p_what) {
...
+								const Rect2 rect = Rect2(Point2(code_completion_rect.position.x + code_completion_rect.size.width - icon_area_size.x, icon_area.position.y), icon_area_size);
+								if (color.a < 1.0) {
+									draw_texture_rect(theme_cache.completion_color_bg, rect, true);
+								}
+
+								draw_rect(rect, (Color)code_completion_options[l].default_value);
```
Comment (KoBeWi) [inline scene/gui/code_edit.cpp:220]:
```suggestion
								draw_rect(rect, color);
```

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
