### PR TITLE
Particles: Fix directed points not working, and fix friction formula

### LINKED ISSUE #83811: In 4.2 GPUParticles3D using Directed Points emission shape doesn't affect particle initial direction
### Godot version

v4.2.beta2.mono.official [f8818f85e]

### System information

Godot v4.2.beta2.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.1640) - AMD Ryzen 7 4800H with Radeon Graphics (16 Threads)

### Issue description

When using GPUParticles3D the Directed Points emission shape doesn't seem to work, it just does the same thing that Points does. Using "Create Emission Points from Node" you can create an emission points texture and emission normal texture. The emission points texture works; the particles are emitted from the surface of the mesh. The emission normal texture doesn't seem to work though. The particles are just emitted in the direction set under velocity/direction. You can just clear the emission normal texture and nothing if affected.

### Steps to reproduce

New 3D scene.

Create MeshInstance3D and give it a mesh.

Create particles and give it a Draw pass. Give it a ParticleProcessMaterial and give the particles an initial velocity. Use "Create Emission Points from Node" and choose Surface Points + Normal (Directed) to create a Emission Points Texture and Emission Normal Texture.

Maybe I'm doing something wrong here, but I have been unable to find any combination of settings that causes the particles initial direction to be anything but the one set under Spawn>Velocity>Direction

### Minimal reproduction project

[particle emission normal test.zip](https://github.com/godotengine/godot/files/13065353/particle.emission.normal.test.zip)

### PR DESCRIPTION
**Pull request by QbieShay**
Fixes https://github.com/godotengine/godot/issues/83811

Fixes friction formula. It was supposed to be like this when i made it, but i just lost track of it so it stayed with a wrong formula. Video comparison:
Left current, Right updated.
https://github.com/godotengine/godot/assets/7917475/1b485e35-66dd-4801-b713-00d6b9aa5bba

Credit to @RPicster for the formula

### CODE REVIEW

File: scene/resources/particle_process_material.cpp [hunk 1]
```diff
@@ -850,6 +850,27 @@ void ParticleProcessMaterial::_update_shader() {
 	code += "		}\n";
 	code += "	if (RESTART_VELOCITY) {\n";
 	code += "		VELOCITY = get_random_direction_from_spread(alt_seed, spread) * dynamic_params.initial_velocity_multiplier;\n";
+	if (emission_shape == EMISSION_SHAPE_DIRECTED_POINTS) {
+		code += "	int point = min(emission_texture_point_count - 1, int(rand_from_seed(alt_seed) * float(emission_texture_point_count)));\n";
```
Comment (akien-mga) [inline scene/resources/particle_process_material.cpp:854]: Reading the code, I think the generated indentation would be wrong, the previous line has two tabs indent, and this one has only one tab.

It seems to be an issue that also exists in some other branches, at least in the section above with the `if (

Comment (QbieShay) [reply scene/resources/particle_process_material.cpp:854]: I already have an issue assigned for indentation problems, it's all over the place currently :<

Comment (AThousandShips) [reply scene/resources/particle_process_material.cpp:854]: In this case the new code should probably be correctly indented from the start at least

Comment (QbieShay) [reply scene/resources/particle_process_material.cpp:854]: I'm not sure if the outer indentation is correct

Comment (AThousandShips) [reply scene/resources/particle_process_material.cpp:854]: You're in a block with the `if` statement, so it should be one more than the current level, and you're inside a method, so that's two levels total

Comment (AThousandShips) [reply scene/resources/particle_process_material.cpp:854]: You have:
```
void start() {
...
	if (RESTART_VELOCITY) {
		...
	int point = min(emission_texture_point_count - 1, int(rand_from_seed(alt_seed) * float(emission_texture_point_count)));
```
Currently

Comment (QbieShay) [reply scene/resources/particle_process_material.cpp]: Should be fixed now

**Review by AThousandShips — APPROVED** [review]
Style looks good, can't comment on the functionality

**Review by clayjohn — APPROVED** [review]
Looks good. 

For a future PR we need to go back and clean up ``emission_tex_size`` and just store the size. Each call to ``textureSize()`` has the same cost as a texture read, which adds a lot to the cost of particles. But since this is an existing issue in the code, let's do that in a follow up PR

**Comment by akien-mga** [comment]
Thanks!
