### PR TITLE
Fix words not being selected by endpoints

### LINKED ISSUE #89551: Single word characters cannot be selected with double click in Editor
### Tested versions

v4.3.dev3.official [36e943b6b]

### System information

Linux Kubuntu 23.04 KDE Plasma Version: 5.27.4 KDE Frameworks Version: 5.104.0 Qt Version: 5.15.8

### Issue description

**Double clicking** does not select  on _single word characters_ such as alpha or numeric, in the Editor, unless the character is at the end and the cursor is placed after it. (I know, who uses single character variable names), but just thought I would report it since other editors I tested behave as expected.

```gdscript
        # a not selectable but 2 is if cursor at end of line.
	var a = 2

        # b and a not selectable
	var b= a*2

        # c not selectable
	var c =2

        # d not selectable
	d = 7

        # cc is selectable
	var cc= 2
```

### Steps to reproduce

see above

### Minimal reproduction project (MRP)

see above

### PR DESCRIPTION
**Pull request by smntic**
Previously, words were unable to be selected by placing the cursor at the left-most character or the character directly after the word. This issue is addressed by adjusting the conditions to check if the caret is positioned in these places.

While fixing this issue, I found that my edits to the conditions affected the behaviour of drag-selecting multiple words. Specifically, it made it impossible to select the whitespace between words in word selection mode, which was a feature before. This is fixed by modifying the conditions based on if multiple words are being selected.

Another problem related to how selecting the word by the leftmost character moved the caret to the left side of the word, while selecting it by any other character moved it to the right side. This is fixed by preventing the word selection from expanding to the left side.

In addition, multiple unit tests were added/changed. One test relied on the previous behaviour and was therefore changed. Additional tests were added to test the selection from left and right endpoints, as well as the deselection by moving the caret back to the original selection position.

Fixes #89551

### CODE REVIEW

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -7259,7 +7259,7 @@ void TextEdit::_update_selection_mode_word() {
 	int end = beg;
 	PackedInt32Array words = TS->shaped_text_get_word_breaks(text.get_line_data(line)->get_rid());
 	for (int i = 0; i < words.size(); i = i + 2) {
-		if ((words[i] < caret_pos && words[i + 1] > caret_pos) || (i == words.size() - 2 && caret_pos == words[i + 1])) {
+		if ((words[i] < caret_pos && words[i + 1] >= caret_pos) || (i == words.size() - 2 && caret_pos == words[i + 1])) {
```
Comment (kitbdev) [inline scene/gui/text_edit.cpp:7262]: This works when the right side of the word is double clicked, but not the left side.

Comment (MrPersonDev) [reply scene/gui/text_edit.cpp:7262]: I will adjust the condition to fix this.

**Comment by MrPersonDev** [comment]
While fixing the problem with words not being selected from the left side, I fixed two other issues with my solution.

My edits to the conditions affected the behaviour of drag-selecting multiple words. Specifically, it made it impossible to select the whitespace between words, which was a feature before. This is fixed by commit [f986196](https://github.com/godotengine/godot/pull/89556/commits/f98619649f95133fee87db2ecea5197aa021adec) (and style fix: [8f2c2f4](https://github.com/godotengine/godot/pull/89556/commits/8f2c2f40a534a62f289848317114ea4e368aac33)), which changes the conditions based on if multiple words are being selected.

Another problem related to how selecting the word by the leftmost character moved the caret to the left side, while selecting it by any other character moved it to the right. This is fixed by [7dbdf77](https://github.com/godotengine/godot/pull/89556/commits/7dbdf77e829869da570f6e090582e03c951fcc58), which prevents the caret from moving to the left side of the word until the word selection has moved.

File: scene/gui/text_edit.cpp [hunk 2]
```diff
@@ -7275,7 +7275,8 @@ void TextEdit::_update_selection_mode_word() {
 		carets.write[caret_idx].selection.selected_word_origin = beg;
 		set_caret_line(line, false, true, 0, caret_idx);
 		set_caret_column(end, true, caret_idx);
-	} else {
+		moved_word_selection = false;
+	} else if (!(col == carets[caret_idx].selection.selected_word_origin && line == get_selection_line(caret_idx) && !moved_word_selection)) {
```
Comment (AThousandShips) [inline scene/gui/text_edit.cpp:7279]:
```suggestion
	} else if (col != carets[caret_idx].selection.selected_word_origin || line != get_selection_line(caret_idx) || moved_word_selection) {
```

**Comment by kitbdev** [comment]
This works as expected, but I'm not sure if it would work after https://github.com/godotengine/godot/pull/86978 fixes the ability to word select empty lines or shift double click to word select from caret, since that may change the logic.

**Comment by MrPersonDev** [comment]
#86978 does change the logic a little bit.

I would say the `p_initial` parameter should be used instead of the `has_selection` function for clarity purposes. Additionally, the condition that I added to fix the caret moving to the left after selecting can be moved into the else block.
\
The only thing I would change from the logic added in #86978 is to change the condition for `is_new_selection_dir_right` to not be true when the caret is at the leftmost character. Using `column >` instead of `column >=` resolves the issue where the editor selects the range from the beginning to the beginning instead of the word.
```
void TextEdit::_update_selection_mode_word(bool p_initial) {
	...
	for (int i = 0; i < words.size(); i = i + 2) {
		// (1) use p_initial instead of has_selection()
		if ((p_initial && words[i] <= caret_pos && words[i + 1] >= caret_pos) || (!p_initial && words[i] < caret_pos && words[i + 1] > caret_pos) || (i == words.size() - 2 && caret_pos == words[i + 1])) {
			beg = words[i];
			end = words[i + 1];
			break;
		}
	}

	if (p_initial && !has_selection(caret_index)) {
		// Set the selection origin if there is no existing selection.
		...
		
		moved_word_selection = false;
	} else {
		// Expand the word selection to the mouse.
		...
		// (3) 'column >' instead of 'column >='
		bool is_new_selection_dir_right = line > origin_line || (line == origin_line && column > carets[caret_index].selection.word_begin_column);
		...

		// (2) move the "moved word selection" condition here instead
		if (column != carets[caret_index].selection.word_begin_column || line != origin_line || moved_word_selection) {
			select(origin_line, origin_col, line, caret_col, caret_index);
			moved_word_selection = true;
		}
	}
	...
}
```
These changes seem to work well when I add them to your fork.

**Review by kitbdev — COMMENTED** [review]
Tested and it does work after my PR, I can apply changes like that when I rebase (assuming this one gets merged first).
Also I think we can simplify things a bit.

File: scene/gui/text_edit.cpp [hunk 3]
```diff
@@ -7275,7 +7275,8 @@ void TextEdit::_update_selection_mode_word() {
 		carets.write[caret_idx].selection.selected_word_origin = beg;
 		set_caret_line(line, false, true, 0, caret_idx);
 		set_caret_column(end, true, caret_idx);
-	} else {
+		moved_word_selection = false;
+	} else if (col != carets[caret_idx].selection.selected_word_origin || line != get_selection_line(caret_idx) || moved_word_selection) {
 		if ((col <= carets[caret_idx].selection.selected_word_origin && line == get_selection_line(caret_idx)) || line < get_selection_line(caret_idx)) {
```
[the remark this answers is not in the document]
Comment (MrPersonDev) [reply scene/gui/text_edit.cpp:7280]: Sorry, I should have been more clear about why I added the variable.
It was to recreate previous functionality in the editor and in many other text editors where the caret can be moved to the left of a highlighted word, but only after moving the caret elsewhere first:
prior behaviour
If we remove `moved_word_selection` and handle that case separately as suggested, we lose that functionality:
removed behaviour
But with the logic I proposed, we maintain that functionality and the caret doesn't jump around when double-clicking the left side:
proposed behaviour

[the remark this answers is not in the document]
Comment (kitbdev) [reply scene/gui/text_edit.cpp:7280]: Is it desirable to want the caret on the left side of the word? It doesn't change behavior and when the caret is at any other part of the word, it will jump to the right anyway.
Also it feels inconsistent that double clicking on the left side puts the caret on the right end, but moving the cursor to the left end puts it on the left end.

godot te select word start inconsistent

I was basing my logic on VSCode, where the caret is always on the right side of the word. In a different text editor I tried, it is based on the original click position, not just the left end of the word.
And in my opinion, I think the logic is cleaner if we don't have a class variable.

I guess if we do want the caret on the left we could handle it separately and put it on the left.

[the remark this answers is not in the document]
Comment (MrPersonDev) [reply scene/gui/text_edit.cpp:7280]: I just wanted to keep the functionality as it was before. However, since this doesn't add anything new and complicates the code, I'll switch it for the suggested change.

**Comment by smnast** [comment]
Rebased to resolve conflicts with #86978.

Also altered one test that used the previous behavior when double-clicking the endpoint of a word, and added two tests to capture the behavior of selecting a word by its endpoints.
I tried to avoid altering the tests as much as possible, but please let me know if there's a better way.

File: tests/scene/test_text_edit.h [hunk 4]
```diff
@@ -1869,30 +1869,43 @@ TEST_CASE("[SceneTree][TextEdit] text entry") {
...
 			SEND_GUI_MOUSE_MOTION_EVENT(text_edit->get_rect_at_line_column(0, 10).get_center(), MouseButtonMask::LEFT, Key::NONE);
 			CHECK(text_edit->get_selection_mode() == TextEdit::SELECTION_MODE_WORD);
 			CHECK(text_edit->has_selection());
 			CHECK(text_edit->get_selected_text() == "some");
 			CHECK(text_edit->get_caret_line() == 0);
-			CHECK(text_edit->get_caret_column() == 8);
+			CHECK(text_edit->get_caret_column() == 12);
 			CHECK(text_edit->get_selection_origin_line() == 0);
-			CHECK(text_edit->get_selection_origin_column() == 12);
+			CHECK(text_edit->get_selection_origin_column() == 8);
```
Comment (kitbdev) [inline tests/scene/test_text_edit.h:1908]: This was part of the ` Can start word select mode when not on a word.` test, and it was used to show that moving the mouse before the initial column reverses without keeping any text still selected from the first move (since it was sticky like that before).
This should be moved down to that test.
Also maybe there should be another one before this that moves the mouse over the initial selection point to show that text can still be deselected.

File: scene/gui/text_edit.cpp [hunk 5]
```diff
@@ -7818,7 +7818,10 @@ void TextEdit::_update_selection_mode_word(bool p_initial) {
 		int origin_col = is_new_selection_dir_right ? carets[caret_index].selection.word_begin_column : carets[caret_index].selection.word_end_column;
 		int caret_col = is_new_selection_dir_right ? end : beg;
 
-		select(origin_line, origin_col, line, caret_col, caret_index);
+		// Expand the word selection only if the caret is not at the start of the selection.
+		if (column != carets[caret_index].selection.word_begin_column || line != origin_line) {
+			select(origin_line, origin_col, line, caret_col, caret_index);
+		}
```
Comment (kitbdev) [inline scene/gui/text_edit.cpp:7824]:
```suggestion
		if (column != carets[caret_index].selection.word_begin_column || line != origin_line || carets[caret_index].selection.word_begin_column == carets[caret_index].selection.word_end_column) {
			select(origin_line, origin_col, line, caret_col, caret_index);
		}
```

This prevents text from deselecting even if there was no selection to start with. I think adding this condition will fix it.

Comment (smnast) [reply scene/gui/text_edit.cpp]: Thanks! I added the tests (hopefully) as you described. This condition allows it to pass the new test.

**Review by kitbdev — APPROVED** [review]
Looks good to me.
You can hit Resolve on all of my previous review comments, since I can't. (Only those with write access can.)

**Review by kitbdev — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
