### PR TITLE
[3.x] Fix non-latin layout scancodes on Linux, adds access to physical scancodes.

### LINKED ISSUE #46750: Godot don't work with non-English layout of keyboard on Linux
**Godot version: 3.2.3 stable release**

**OS/device including version: Linux Mint 18.3**

**Issue description: I have 2 layout on my laptop (English and Russian for me) and when i change it to non-English layout happends:
1) Hotkey is not working
2) When i run the project and trying to catch action by _if Input.is_action_pressed("ui_right")_ it doesn't work
3) When i try see scancode of character, i see 0 for all keys, if it not a special key (like "shift", "control", "tab" and etc.)**

**Steps to reproduce: For reproduce this bug you can try to catch any action or InputEventKey and see it (of course, you need to do it on linux)**

**Minimal reproduction project:*[game.zip](https://github.com/godotengine/godot/files/6096826/game.zip)*

### LINKED ISSUE #46751: InputEventKey.scancode does not return the correct value on non-QWERTY layouts
**Godot version:** 3.2.3.stable.mono.official

**OS/device including version:**
Windows 10

**Issue description:**
I use the Dvorak keyboard layout, which has a different key placement from QWERTY.

For example, in JavaScript, there are different values in a keyboard event that correspond to the *physical* key pressed (the "scancode" in its original sense), and to the *character* corresponding to the key pressed.

However, on Godot, `InputEventKey.scancode` does not return the scancode on Dvorak, but the scancode of the key that corresponds to the character on QWERTY.

Here is the result of pressing the Q key on QWERTY:
image

And here is the result of pressing the same key on Dvorak:
image
It should say this instead:
```
scancode: 0d0081 = 0x0051 (Q)
unicode: 0d0039 = 0x0027 (')
get_scancode_with_modifiers():
 81 (0x00000051)
```

For reference, here's the result of pressing the same key on ЙЦУКЕН, the standard keyboard layout for Russian:
image
(As a side note, this reportedly (#46750) does not work on Linux.)

**Steps to reproduce:**

1. Listen for any `InputEventKey`.
2. Inspect its properties.

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/6096913/Test.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Backport of #18020, without breaking changes.

Existing Functions properties are not renamed, new property is `physical_scancode`.

For the reference, list of changes to existing API (in both cases physical scancode is used only if remapped scancode is `0`):
- `InputEventKey::action_match` uses physical scancode, if remapped scancode is `0` (Physical key are added to `InputMap` with `scancodes == 0`, remapped keys with `physical_scancode == 0`).
- On Linux/X11, physical scancode is used in place remapped, if scancode is `0` (not remapped correctly by `XLookupString`).

Modified test project from 46751: [Test.zip](https://github.com/godotengine/godot/files/6097439/Test.zip)
<details>
  <summary>Screenshots:</summary>
Dvorak:
Screenshot 2021-03-07 at 16 45 10
Russian (phonetic) layout:
Screenshot 2021-03-07 at 16 45 32
Results are the same on macOS, Linux (Ubuntu 20.10) and Windows.
</details>

Fixes #46751 and fixes #46750

### CODE REVIEW

File: platform/javascript/os_javascript.cpp [hunk 1]
```diff
@@ -253,6 +253,7 @@ static Ref<InputEventKey> setup_key_event(const EmscriptenKeyboardEvent *emscrip
 	ev->set_echo(emscripten_event->repeat);
 	dom2godot_mod(emscripten_event, ev);
 	ev->set_scancode(dom_code2godot_scancode(emscripten_event->code, emscripten_event->key));
+	ev->set_physical_scancode(dom_code2godot_scancode(emscripten_event->code, emscripten_event->key));
```
Comment (Faless) [inline platform/javascript/os_javascript.cpp:256]: There is actually "proper" (quoted because we are still talking about the web :( ) implementation for this. Let me do the backport on top of these changes so you could simply add it on top.

Comment (Faless) [reply platform/javascript/os_javascript.cpp:256]: See https://github.com/Faless/godot/commit/516eacef08ea13686126920a1a27ca484c704da6

Comment (bruvzg) [reply platform/javascript/os_javascript.cpp:256]: Thanks. I have pulled JS commit to the PR branch.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by jitspoe** [comment]
Does this mean we'll be able to bind the default keys based on key positions instead of the letters of the keys?  Would be great for non-qwerty keyboard users!

**Comment by Calinou** [comment]
> Does this mean we'll be able to bind the default keys based on key positions instead of the letters of the keys? Would be great for non-qwerty keyboard users!

Yes 🙂

**Comment by jitspoe** [comment]
Awesome!  I saw there's a physical_key that gets written to the project file, but it seems to always be 0.  Maybe it's only supported in Linux at the moment?

**Comment by akien-mga** [comment]
@jitspoe Should work on all platforms, but `key` and `physical_key` are mutually exclusive. You should click "Physical Key" to add one to the input map (and `key` will be 0).
Screenshot_20210919_112749

**Comment by jitspoe** [comment]
Is there a way to get the display string from a physical_key?  Can't seem to find anything, so I made a proposal here: https://github.com/godotengine/godot-proposals/issues/3571

**Comment by agameraaron** [comment]
I really appreciate this!! Was really hoping I wouldn't have to wait until 4.0 for this and thankfully that is now the case.
