### PR TITLE
Fix several shader preprocessor include issues

### LINKED ISSUE #5399: Add shader include relative path support
### Describe the project you are working on

3D game.

### Describe the problem or limitation you are having in your project

Often I like put my project to deferent directories and move, so for most shader files for include, it's absolute path was changed but relative path not. 
eg:
Tree look:
image
And `comm.gdshaderinc` was incluced by `node_3d.shader`:
image
image

If I change my `shaders` folder to `xd/shaders`, I must change the `node_3d.gdshader` file because the `comm.gdshaderinc` file's absolute path was changed.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

For shader `include` preprocessor, support absolute and relative path.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

/

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I must change many files, if my project was big, i'm afraid to do that.

### Is there a reason why this should be core and not an add-on in the asset library?

/

### LINKED ISSUE #64792: Shader include auto complete does not include folder directory
### Godot version

4.0 alpha 14

### System information

Windows 10, Vulkan

### Issue description

The autocomplete for shader include does not include the folder directory path.

### Steps to reproduce

Following the example in https://github.com/godotengine/godot/pull/62513

* Open the attached example project
* Open res://folder/shader.gdshader
* Remove the include file path (e.g. "shader.gdshaderinc")
* Type open " to trigger autocomplete

Expected outcome:

* The autocomplete provides a file path of "folder/shader.gdshaderinc"

Actual outcome:

* The autocomplete provides a file path of "shader.gdshaderinc"

### LINKED ISSUE #66075: Shaders using a shader include are not reloaded after editing the include
### Godot version

Godot 4.0 master 90879530

### System information

Windows 10, 64bit

### Issue description

When I edit a shader include and save it I expect all shaders depending on it to be reloaded. It does not happen in practice and there seem to be no manual way to reload shaders, other then editing them one by one manually.

### Steps to reproduce

- Open the attached project.
- Open Scene, it has a sphere using the `Shader` shader
- Open `Include.gdshaderinc` for editing
- Change the color, the sphere on the scene will not change color

**Workaround**
- Open all dependent shaders as well in the editor
- Changing the include files will not reload the shaders

This either need to be fixed or documented as known behavior.

### Minimal reproduction project

[ShaderIncludeNoReload.zip](https://github.com/godotengine/godot/files/9595328/ShaderIncludeNoReload.zip)

### LINKED ISSUE #67811: Relative paths for shader include in 4.0 beta3 are not working
### Godot version

4.0 beta 3

### System information

Arch Linux, Vulkan, NVidia gtx 1650ti

### Issue description

Relative paths for shader includes are not working. It only works for top level dir. (first dir after "res://" ) e.g. "res://top_dir". Then `#include top_dir/..` works. But let's say we have another dir inside top_level. e.g. `res://top_dir/second_dir/`. Then any includes with relative paths wont work, like: `#include second_dir/..`

### Steps to reproduce

Use shader include inside multi level directories.

### Minimal reproduction project

Open shader.gdshader for quick example.
[ShaderInc.zip](https://github.com/godotengine/godot/files/9847006/ShaderInc.zip)

### LINKED ISSUE #72108: Functions from shader includes can't have arguments when included with relative path
### Godot version

v4.0.beta15.official [4fa6edc88]

### System information

Windows 10 (10.0.19045 Build 19045) | Forward+ | Vulkan API 1.3.206 | AMD Radeon RX 6800 XT

### Issue description

If there is a function with arguments within a `.gdshaderinc` file, then this function can not be used in other shaders that include this via a relative include. The error in the other shaders is "Too many arguments for "example()" call. Expected at most 0 but received 1". Using an absolute path for the include resolves the error.

**Note:** The relative include *does* work in the special case of both files being in the project root.

### Steps to reproduce

1. Put a shader and a shader-include file into a subdirectory
2. Write a function with arguments in the shader-include file
3. Include that file in the shader
4. Try to use the function

### Minimal reproduction project

[shader-include-bug.zip](https://github.com/godotengine/godot/files/10508745/shader-include-bug.zip)

### PR DESCRIPTION
**Pull request by bitsawer**
Fix several issues related to shader preprocessor include path handling.

* Close https://github.com/godotengine/godot-proposals/issues/5399. This PR started as a bugfix, so it was a nice surprise to accidentally implement a proposal too.

* Close https://github.com/godotengine/godot/issues/66075, hopefully forever. The issue in the first post was already fixed in my previous PR (https://github.com/godotengine/godot/pull/71878), but the issue was kept open because it might still have relevance. Hopefully this PR will finally slay the other problems discussed in that thread. I was able to reproduce similar shader loading error behavior as @TokisanGames described and this PR fixed it for me, but if they have some complex Godot gigaproject there might be more corner cases lurking somewhere. Fingers crossed.

* Fix https://github.com/godotengine/godot/issues/64792. Because relative paths should now work correctly, that issue will no longer be a problem as the autocomplete relative path suggestion is a now a good one.

* Fix https://github.com/godotengine/godot/issues/72108. The title and first post of that issue are a bit misleading, read the second post in the thread for clarification. Relative paths should now work correctly. The mostly unrelated "Too many arguments for xyz()" issue seems to be tracked here: https://github.com/godotengine/godot/issues/72120.

* Fix https://github.com/godotengine/godot/issues/67811.

This mostly applies to externally saved Shaders and ShaderIncludes resources that have a file path. Shaders stored inside a scene or created programmatically will naturally have to use absolute include paths.

By a relative path I mean paths that are in the same level or below in the directory hierarchy (like "subdir/another/common.gdshaderinc"). Relative paths that would require normalization (like "../../common.gdshaderinc") will not work. Absolute paths like "res://data/common.gdshaderinc" have always worked. Previously, relative paths only worked if the files using #include were in the project root folder.

The problem was that the full resource path to the processed shader or include wasn't always available or even used, which naturally caused relative includes to fail. This was especially common when loading a project, moving files or reimporting stuff as the resource path was sometimes updated too late.

### CODE REVIEW

File: editor/plugins/text_shader_editor.cpp [hunk 1]
```diff
@@ -383,11 +383,12 @@ void ShaderTextEditor::_code_complete_script(const String &p_code, List<ScriptLa
 	List<ScriptLanguage::CodeCompletionOption> pp_defines;
 	ShaderPreprocessor preprocessor;
 	String code;
-	complete_from_path = (shader.is_valid() ? shader->get_path() : shader_inc->get_path()).get_base_dir();
+	String resource_path = (shader.is_valid() ? shader->get_path() : shader_inc->get_path());
```
Comment (akien-mga) [inline editor/plugins/text_shader_editor.cpp:386]: The parentheses are now redundant, but it's probably not worth amending the commit just for it. Let's wait to see if reviewers have other things they want updated.

**Review by clayjohn — COMMENTED** [review]
Seems fine to me. Would be good to have @Chaosus weigh in as well. 

Also great work @bitsawer you are on fire!

**Review by Chaosus — APPROVED** [review]

**Comment by Chaosus** [comment]
Thanks!
