### PR TITLE
regression: var declaration type info parser bug fix

### LINKED ISSUE #38698: 3.2 GDScript Type Errors
**Godot version:**
8cb67bb359d47be115c439346668f73974490de6

**OS/device including version:**
Win10 64-bit

**Issue description:**
A recent regression has appeared, and I have now been getting errors about GDScript type assignments.  I've isolated it to preloading scripts and using them as a type hint for variables.  Haven't done much to explore all the conditions, but here are the errors, the stack, and a minimal project for it.

ss

```
GDScriptCompiler::_gdtype_from_datatype(const GDScriptParser::DataType & p_datatype) Line 166	C++
GDScriptCompiler::_parse_expression(GDScriptCompiler::CodeGen & codegen, const GDScriptParser::Node * p_expression, int p_stack_level, bool p_root, bool p_initializer, int p_index_addr) Line 1147	C++
GDScriptCompiler::_parse_block(GDScriptCompiler::CodeGen & codegen, const GDScriptParser::BlockNode * p_block, int p_stack_level, int p_break_addr, int p_continue_addr) Line 1561	C++
GDScriptCompiler::_parse_function(GDScript * p_script, const GDScriptParser::ClassNode * p_class, const GDScriptParser::FunctionNode * p_func, bool p_for_ready) Line 1620	C++
GDScriptCompiler::_parse_class_blocks(GDScript * p_script, const GDScriptParser::ClassNode * p_class, bool p_keep_state) Line 2035	C++
GDScriptCompiler::compile(const GDScriptParser * p_parser, GDScript * p_script, bool p_keep_state) Line 2171	C++
GDScript::load_byte_code(const String & p_path) Line 805	C++
ResourceFormatLoaderGDScript::load(const String & p_path, const String & p_original_path, Error * r_error) Line 2280	C++
ResourceLoader::_load(const String & p_path, const String & p_original_path, const String & p_type_hint, bool p_no_cache, Error * r_error) Line 270	C++
ResourceLoader::load(const String & p_path, const String & p_type_hint, bool p_no_cache, Error * r_error) Line 401	C++
GDScriptParser::_parse_expression(GDScriptParser::Node * p_parent, bool p_static, bool p_allow_assign, bool p_parsing_constant) Line 510	C++
GDScriptParser::_parse_and_reduce_expression(GDScriptParser::Node * p_parent, bool p_static, bool p_reduce_const, bool p_allow_assign) Line 2026	C++
GDScriptParser::_parse_class(GDScriptParser::ClassNode * p_class) Line 5116	C++
GDScriptParser::_parse(const String & p_base_path) Line 8571	C++
GDScriptParser::parse_bytecode(const Vector<unsigned char> & p_bytecode, const String & p_base_path, const String & p_self_path) Line 8663	C++
GDScript::load_byte_code(const String & p_path) Line 798	C++
ResourceFormatLoaderGDScript::load(const String & p_path, const String & p_original_path, Error * r_error) Line 2280	C++
ResourceLoader::_load(const String & p_path, const String & p_original_path, const String & p_type_hint, bool p_no_cache, Error * r_error) Line 270	C++
ResourceLoader::load(const String & p_path, const String & p_type_hint, bool p_no_cache, Error * r_error) Line 401	C++
GDScriptParser::_parse_expression(GDScriptParser::Node * p_parent, bool p_static, bool p_allow_assign, bool p_parsing_constant) Line 510	C++
GDScriptParser::_parse_and_reduce_expression(GDScriptParser::Node * p_parent, bool p_static, bool p_reduce_const, bool p_allow_assign) Line 2026	C++
GDScriptParser::_parse_class(GDScriptParser::ClassNode * p_class) Line 5116	C++
GDScriptParser::_parse(const String & p_base_path) Line 8571	C++
GDScriptParser::parse_bytecode(const Vector<unsigned char> & p_bytecode, const String & p_base_path, const String & p_self_path) Line 8663	C++
GDScript::load_byte_code(const String & p_path) Line 798	C++
ResourceFormatLoaderGDScript::load(const String & p_path, const String & p_original_path, Error * r_error) Line 2280	C++
ResourceLoader::_load(const String & p_path, const String & p_original_path, const String & p_type_hint, bool p_no_cache, Error * r_error) Line 270	C++
ResourceLoader::load(const String & p_path, const String & p_type_hint, bool p_no_cache, Error * r_error) Line 401	C++
ResourceInteractiveLoaderText::poll() Line 433	C++
ResourceFormatLoader::load(const String & p_path, const String & p_original_path, Error * r_error) Line 197	C++
ResourceLoader::_load(const String & p_path, const String & p_original_path, const String & p_type_hint, bool p_no_cache, Error * r_error) Line 270	C++
ResourceLoader::load(const String & p_path, const String & p_type_hint, bool p_no_cache, Error * r_error) Line 401	C++
Main::start() Line 1705	C++
widechar_main(int argc, wchar_t * * argv) Line 160	C++
_main() Line 184	C++
main(int _argc, char * * _argv) Line 196	C++

```
**Steps to reproduce:**
Running the minimal project is enough to produce the errors in the console.

**Minimal reproduction project:**
[GDScript Type Errors.zip](https://github.com/godotengine/godot/files/4617482/GDScript.Type.Errors.zip)

### PR DESCRIPTION
**Pull request by ThakeeNathees**
Fix: #38698

### CODE REVIEW

**Comment by avencherus** [comment]
I can't attest to the code correctness in this area, but the errors have stopped appearing when using this commit.

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -7956,6 +7956,7 @@ void GDScriptParser::_check_class_level_types(ClassNode *p_class) {
 
 		_mark_line_as_safe(v.line);
 		v.data_type = _resolve_type(v.data_type, v.line);
+		v.initial_assignment->arguments[0]->set_datatype(v.data_type);
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp:7959]: Is `initial_assignment` always available? If a variable is not set this would be `nullptr` and crash, or am I missing something?

Comment (ThakeeNathees) [reply modules/gdscript/gdscript_parser.cpp:7959]: every var declaration has initial_assignment of `OperatorNode::OP_INIT_ASSIGN` with the first argument as the identifier(always available unless parser error) and the second may or may not be `nullptr`. 
And the identifier's type was unresolved when when it created, but it has a type [fixed in my early pr](https://github.com/godotengine/godot/pull/37598/files#diff-8b4334df54a8abf5b41fe22cf292f9edR4945).
now i'm re assigning the datatype of the identifier after resolving the type.
@vnen @avencherus

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.
