### PR TITLE
Close expanded tile editor when inspector updates

### LINKED ISSUE #84321: Editor: expanded polygon view in the Tile Set Polygon Editor doesn't sync with subsequently selected tile
### Godot version

4.2 beta 4

### System information

Windows 11

### Issue description

In the editor, when using the expanded polygon view in the Tile Set Polygon Editor, the view doesn't sync with subsequently selected tiles. I have to close the expanded editor and reopen it to see the polygon of the just selected tile.

### Steps to reproduce

- Make sure you have a project that has a tile map with a physics layer and a tile set
- Open the tile set
- Select or create a Tiles item
- Activate Select tiles mode
- Select a tile
- Expand Physics
- Expand the physics layer
- Press the Expand editor button above the polygon panel
- Draw a polygon
- Select another tile
- Observe that the polygon didn't update and still displays the one of the previously selected tile

### Minimal reproduction project

N/A

### LINKED ISSUE #86720: Tileset collisions: The expanded polygon drawing tool can get stuck in a state where modifications are ignored.
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 Ti (NVIDIA; 31.0.15.3699) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 Threads)

### Issue description

When trying to draw collision polygons on 2D tiles, there has been two situations that put the **expanded editor** in a state where no further modifications are "registered": modifications will still show normally in the editor itself, but when saving and closing the editor, your last changes will be lost.

The two scenarios:
- Draw a polygon of any shape.
- Use the `clear` option.

Any further node addition / move / deletion will be ignored.

### Steps to reproduce

1. Create a tileset atlas with a texture.
2. Add a physics layer.
3. In the tileset editor at the bottom, got to `Physics > Physics Layer 0`, select a tile, and select the `Expand editor` option:
   s1
4. Trigger one of the two cases:
   - Draw any shape. Once the shape is "closed", no more modifications will take effect. Illustrated below: I drew a triangle, and then modified it to be a square.
     s3
   - Use the `clear` option. No more modifications will take effect. Illustrated below: I cleared an existing polygon and drew a new one.
     s2

Saving has no effect.

### Minimal reproduction project (MRP)

[mrp_tilset_poly_editor_bug.zip](https://github.com/godotengine/godot/files/13812986/mrp_tilset_poly_editor_bug.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
TileSet editor has an internal inspector that really likes getting refreshed. One instance is when you select another tile, another is when a polygon is added or removed:
https://github.com/godotengine/godot/blob/3978628c6cc1227250fc6ed45c8d854d24c30c30/scene/resources/2d/tile_set.cpp#L6271
This causes all property editors to get destroyed and re-created.

There is one special editor though - the expanded editor. When you expand polygon editor (see #79512), it's moved to a different parent that isn't inside the inspector. So when inspector is cleared, the expanded editor survives it and holds outdated information.

I don't have a good solution for that yet. Perfectly, when inspector is refreshed, the previous editor should be automatically expanded again. However the "previous" editor no longer exists and there can be multiple polygon editors, so it has to be somehow remembered per-property, idk.

For now I just force-close the editor when it's going to become invalid.

https://github.com/user-attachments/assets/1389469d-56f1-4171-8195-5ddf8d1dd0a3

It's a safe fix that could be applied for now.

Closes #84321
Closes #86720
Opens #95XXX (the new behavior is disrupting, so an issue should be opened if this is merged)

### CODE REVIEW

File: editor/plugins/tiles/tile_data_editors.cpp [hunk 1]
```diff
@@ -859,6 +859,11 @@ void GenericTilePolygonEditor::_notification(int p_what) {
 				button_expand->set_pressed_no_signal(false);
 			}
 		} break;
+
+		case NOTIFICATION_READY: {
+			get_parent()->connect("tree_exited", callable_mp(TileSetEditor::get_singleton(), &TileSetEditor::remove_expanded_editor));
```
Comment (groud) [inline editor/plugins/tiles/tile_data_editors.cpp:864]: Does it really need to be connected to the parent? Wouldn't it work to simply put it in a `NOTIFICATION_EXIT_TREE`, as I assume GenericTilePolygonEditor exits the tree too when its parent does ?

Comment (AThousandShips) [inline editor/plugins/tiles/tile_data_editors.cpp:864]:
```suggestion
			get_parent()->connect(SceneStringName(tree_exited), callable_mp(TileSetEditor::get_singleton(), &TileSetEditor::remove_expanded_editor));
```

Comment (KoBeWi) [reply editor/plugins/tiles/tile_data_editors.cpp:864]: Expanded editor has different parent and does not exit.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
> Opens #95XXX (the new behavior is disrupting, so an issue should be opened if this is merged)

Reminder to open that issue - or should we hold off merging this until investigated further?
