### PR TITLE
Reset TileMapEditor painting state on application refocus

### LINKED ISSUE #24970: Tilemap editor draws lines
**Godot version:** 3.1 beta 1 

**OS/device including version:** Windows 10 x64

**Issue description:**

When putting a tile in the tilemap editor, the editor draws a line of tiles.

https://ibb.co/p4ZY6S4

**Steps to reproduce:**

Open a window of a different program on the side of Godot Editor. With the Tilemap Editor opened and a tile selected, click that window, then click your canvas to put the tile. 
**Minimal reproduction project:**

### LINKED ISSUE #42398: Tilemap Editor-breaking bug when drawing with the tilemap [UndoRedo]
A similar issue has been opened since the earlier version of Godot, such as these, #39802
Please, this is my first time opening an issue. I apologize for any error in my issue writing.

**Godot Version:**
_Godot v3.2.3 stable-win64_

**Issue description:**
```
 core/undo_redo.cpp:373 - Condition "action_level > 0" is true. Returned: ""
 core/undo_redo.cpp:346 - Condition "action_level > 0" is true. Returned: false

```
This happens during tilemap drawing, in my case, simultaneously holding both mouse buttons and when trying to draw a rectangle with the draw seems to elicit this bug. I cannot undo or redo anymore during this state or even change scenes, which leads me to restart Godot every time this happens.

Of course, it is fixed after restarting Godot but a fix to this bug is needed for easier use of the engine.

**Steps to reproduce:**
Create a tilemap with sprites, draw sprites with Shift + Control + Left Mouse Button + Right Mouse Button held down. There may be some other keys pressed during that time.

**Minimal reproduction project:**
_None. Since the bug disappears when you exit Godot, it is illogical to include a reproduction project as it cannot be reproduced in this state unless you directly do it within your project._

### PR DESCRIPTION
**Pull request by NEO97online**
Currently, when focusing another window, then returning to the TileMap editor, a line is drawn from approximately the last in-editor mouse position to the clicked position. This is not desirable and reflected in #24970, #34003, #10949.

A related issue is #39802; Switching window focus (i.e. with Alt+Tab) while painting leaves the editor in a broken state, preventing the user from undoing any further actions in the TileMap editor until restarting Godot. This bug is caused by the undo action_level being incremented on mousedown, but since mouseup occurs after focus is lost, the action_level is never reset.

This PR fixes both bugs by handling application unfocus and resetting state accordingly. It adds a simple flag to the TileMapEditor which prevents extra lines from being drawn when the application is refocused.

Fixes #24970 and resolves the TileMap portion of #39802 (GridMap not fixed in this PR)

### CODE REVIEW

File: editor/plugins/tile_map_editor_plugin.h [hunk 1]
```diff
@@ -119,6 +119,7 @@ class TileMapEditor : public VBoxContainer {
 	Rect2i rectangle;
 
 	Point2i over_tile;
+	bool refocus_over_tile;
```
Comment (KoBeWi) [inline editor/plugins/tile_map_editor_plugin.h:122]:
```suggestion
	bool refocus_over_tile = false;
```

**Review by KoBeWi — APPROVED** [review]
The PR looks fine (aside from the suggestion above). I somehow still managed to reproduce #39802, but the reproduction steps are more complicated and apparently random (I don't even know what caused it this time). The fix is reliable, so it should be fine as is.

I noticed that when you unfocus when e.g. drawing line, the origin point will change on refocus. I wonder if the line/rectangle/fill should be committed like the paint tool. But the way it's done currently it would lead to much duplicated code, so maybe it's not worth changing it.

**Comment by auderer** [comment]
> I noticed that when you unfocus when e.g. drawing line, the origin point will change on refocus. I wonder if the line/rectangle/fill should be committed like the paint tool. But the way it's done currently it would lead to much duplicated code, so maybe it's not worth changing it.

Agreed, I came to the same conclusion while working on this. I thought it would be best to submit this minimal fix for the primary bug, then I can try proposing a larger rewrite that would commit the other tools on unfocus.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
