### PR TITLE
Limit icon size in `EditorDebuggerTree`.

### LINKED ISSUE #92309: GDExtension icons are big in 'Remote' scene tree
### Tested versions

v4.2.stable.official [46dc27791]

### System information

Godot v4.2.stable - macOS 14.5.0 - Vulkan (Forward+) - integrated Apple M2 - Apple M2 (8 Threads)

### Issue description

I added icons to GDExtension nodes. Although the [documentation](https://docs.godotengine.org/en/stable/contributing/development/editor/creating_icons.html#creating-icons) clearly says to use 16x16 icons, I **disobeyed** and just downloaded a random Swift logo image from the internet. It is 92x92 pixels, but displayed in the editor just fine! It only displays as too big in the _Remote scene tree_ view. See sceenshots.

| Editor scene tree | Local scene tree | Remote scene tree |
| --- | --- | --- |
| scene-tree | local-scene-tree | remote-scene-tree |

**I wouldn't be surprised if the icon was too big everywhere.** Docs make it clear that it should be 16x16. But like this 2 of the 3 scene tree views work fine and one looks broken. I think the image should be scaled down everywhere.

I'm confident that this isn't a Swift or MacOS issue, but this is how I encountered the bug.

### Steps to reproduce

- I cloned the [Swift port of Kenney's Godot platformer starter kit](https://github.com/lorenalexm/Starter-Kit-3D-Platformer-Swift), built it and added the dynamic libraries into the `bin` folder. I'm guessing you could do any GDExtension project, but this is the one I used.
- Downloaded icon of Swift from the internet (92x92 pixels!)
- There is already a `Platformer3D.gdextension` in the `bin` folder
- Added the gdextension icons to all the nodes ([docs](https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_cpp_example.html#custom-editor-icon)) with this code:

```ini
[icons]
Player = "res://swift-logo.png"
AudioPlayer = "res://swift-logo.png"
Player = "res://swift-logo.png" 
Coin = "res://swift-logo.png"
Cloud = "res://swift-logo.png"
FallingPlatform = "res://swift-logo.png"
GameUI = "res://swift-logo.png"
CameraView = "res://swift-logo.png"
```

- Run the project, switch to **Remote** scene tree view

### Minimal reproduction project (MRP)

I stripped down the Kenney project port from everything that isn't needed. This zip contains just a single Swift node and a simple Godot scene that contains that node.

[mrp-gdext-icons.zip](https://github.com/godotengine/godot/files/15430960/mrp-gdext-icons.zip)

### PR DESCRIPTION
**Pull request by Daylily-Zeleen**
Limit custom classes icon size in `EditorDebuggerTree`.

Before:
"Remote" Tab:
QQ图片20240506223825
But the scene tree editor can display it correctly.
QQ图片20240506232416

After:
QQ图片20240506232541

* *Bugsquad edit, fixes: https://github.com/godotengine/godot/issues/92309*

### CODE REVIEW

File: editor/debugger/editor_debugger_tree.cpp [hunk 1]
```diff
@@ -62,6 +63,15 @@ void EditorDebuggerTree::_notification(int p_what) {
 			connect("item_collapsed", callable_mp(this, &EditorDebuggerTree::_scene_tree_folded));
 			connect("item_mouse_selected", callable_mp(this, &EditorDebuggerTree::_scene_tree_rmb_selected));
 		} break;
+
+		case NOTIFICATION_THEME_CHANGED: {
+			const StringName icon_max_width = "icon_max_width";
+			const int class_icon_size = get_theme_constant(SNAME("class_icon_size"), EditorStringName(Editor));
```
Comment (timothyqiu) [inline editor/debugger/editor_debugger_tree.cpp:69]: Both `icon_max_width` and `class_icon_size` should either use `SNAME` or not.

**Comment by Daylily-Zeleen** [comment]
Any progress?

File: editor/debugger/editor_debugger_tree.cpp [hunk 2]
```diff
@@ -62,6 +63,15 @@ void EditorDebuggerTree::_notification(int p_what) {
 			connect("item_collapsed", callable_mp(this, &EditorDebuggerTree::_scene_tree_folded));
 			connect("item_mouse_selected", callable_mp(this, &EditorDebuggerTree::_scene_tree_rmb_selected));
 		} break;
+
+		case NOTIFICATION_THEME_CHANGED: {
+			const StringName icon_max_width = "icon_max_width";
+			const int class_icon_size = get_theme_constant("class_icon_size", EditorStringName(Editor));
+			if (has_theme_constant_override(icon_max_width) && get_theme_constant(icon_max_width) == class_icon_size) {
```
Comment (Maran23) [inline editor/debugger/editor_debugger_tree.cpp:70]: I'm not sure if this is needed? At least we never did that on other locations where we clamp the icon size of global classes.

File: editor/debugger/editor_debugger_tree.cpp [hunk 3]
```diff
@@ -62,6 +63,15 @@ void EditorDebuggerTree::_notification(int p_what) {
 			connect("item_collapsed", callable_mp(this, &EditorDebuggerTree::_scene_tree_folded));
 			connect("item_mouse_selected", callable_mp(this, &EditorDebuggerTree::_scene_tree_rmb_selected));
 		} break;
+
+		case NOTIFICATION_THEME_CHANGED: {
+			const StringName icon_max_width = "icon_max_width";
+			const int class_icon_size = get_theme_constant("class_icon_size", EditorStringName(Editor));
```
[the remark this answers is not in the document]
Comment (Daylily-Zeleen) [reply editor/debugger/editor_debugger_tree.cpp:69]: Theme changed is not a frequent work. It is nor worth to use `SNAME` here.

File: editor/debugger/editor_debugger_tree.cpp (hunk 2 above)
Comment (Daylily-Zeleen) [reply editor/debugger/editor_debugger_tree.cpp:70]: You can refer this:
https://github.com/godotengine/godot/blob/bd2300d77a6008167043f23fd91bcc562cde0a19/editor/gui/scene_tree_editor.cpp#L931-L932

The different between this pr and `SceneTreeEditor` is that this pr only set them constant override if changed.
Otherwise, it will fall into infinite loop ( already tested).

**Comment by Daylily-Zeleen** [comment]
You can just build [godot-cpp](https://github.com/godotengine/godot-cpp)'s test and add few lines to `example.gdextension`:
```
[icons]
Example = "res://icon.png"

```
Then add `return` to `func _ready()` in "main.gd" to avoid auto quit.

Run the "main.tscn" and check the remote scene tree:

QQ截图20240524232110

**Review by KoBeWi — APPROVED** [review]
