### PR TITLE
Fix "Go to parent folder" in `EditorFileDialog`

### LINKED ISSUE #80750: `FileDialog` considers `/path/to/dir/`'s parent directory to be `path/to/dir`
### Godot version

4.1.1

### System information

linux

### Issue description

- When favoriting a path in a `FileDialog`, clicking on it travels to `path/to/dir/`.
- When going up a level from there, it doesn't go to `path/to` but to `path/to/dir` (without the `/`).

[simplescreenrecorder-2023-08-18_09.38.37.webm](https://github.com/godotengine/godot/assets/71937306/00c20ad3-292f-4961-84ed-dbc64906df52)

The problem is either (or both) that:
 - loaded path has a trailing `/`
 - parent dir of `stuff/` is considered to be `stuff`

### Steps to reproduce

favorite a directory and use the feature to navigate to it

### Minimal reproduction project

any (i.e. the project manager's "new project" dialog has one)

### PR DESCRIPTION
**Pull request by Alex2782**
Fixes: #80750

I am not sure if '/' character may be removed in the function `get_base_dir()` as well. (190 results in 80 files)

### CODE REVIEW

File: editor/gui/editor_file_dialog.cpp [hunk 1]
```diff
@@ -1528,7 +1528,13 @@ void EditorFileDialog::_recent_selected(int p_idx) {
 }
 
 void EditorFileDialog::_go_up() {
-	dir_access->change_dir(get_current_dir().get_base_dir());
+	String cur_dir = get_current_dir();
+
+	if (cur_dir.ends_with("/")) {
+		cur_dir = cur_dir.substr(0, cur_dir.length() - 1);
```
Comment (AThousandShips) [inline editor/gui/editor_file_dialog.cpp:1534]:
```suggestion
		cur_dir = cur_dir.left(-1);
```
Has the same effect

Comment (Alex2782) [reply editor/gui/editor_file_dialog.cpp]: thank you for the advice, now `left(-1)`

File: editor/gui/editor_file_dialog.cpp [hunk 2]
```diff
@@ -1528,7 +1528,13 @@ void EditorFileDialog::_recent_selected(int p_idx) {
 }
 
 void EditorFileDialog::_go_up() {
-	dir_access->change_dir(get_current_dir().get_base_dir());
+	String cur_dir = get_current_dir();
+
+	if (cur_dir.ends_with("/")) {
+		cur_dir = cur_dir.left(-1);
+	}
```
Comment (KoBeWi) [inline editor/gui/editor_file_dialog.cpp:1535]:
```suggestion
	String cur_dir = get_current_dir().trim_suffix("/");
```
This should behave the same.

Although I think both solutions would break `res://` (which can also be favorited). Probably needs extra check.

**Comment by KoBeWi** [comment]
> I am not sure if '/' character may be removed in the function get_base_dir() as well. (190 results in 80 files)

I remember we have workaround code for the `/` issue in various places. Might be indeed worth it to modify `get_base_dir()` itself (but then we should do a cleanup pass to remove the workarounds).

File: editor/gui/editor_file_dialog.cpp (hunk 2 above)
Comment (Alex2782) [reply editor/gui/editor_file_dialog.cpp:1535]: should i run `Commit changes` via github? never done it before 😄 

image

Comment (KoBeWi) [reply editor/gui/editor_file_dialog.cpp:1535]: It's better to apply the changes yourself. Also, as I mentioned, it needs some modification anyway.

Comment (YuriSizov) [reply editor/gui/editor_file_dialog.cpp:1535]: You can do that, but following that you would still have to pull these changes locally and then do a squash/fixup so that you end up with one single commit. So it may be quicker for you to do these changes locally instead of applying the suggestion :)

**Comment by Alex2782** [comment]
no problems

https://github.com/godotengine/godot/assets/41921395/bb9f72cc-1c90-467c-9ba9-e05c3b775bf6

File: editor/gui/editor_file_dialog.cpp [hunk 3]
```diff
@@ -1528,7 +1528,9 @@ void EditorFileDialog::_recent_selected(int p_idx) {
 }
 
 void EditorFileDialog::_go_up() {
-	dir_access->change_dir(get_current_dir().get_base_dir());
+	String cur_dir = get_current_dir().trim_suffix("/");
+
+	dir_access->change_dir(cur_dir.get_base_dir());
```
Comment (KoBeWi) [inline editor/gui/editor_file_dialog.cpp:1533]:
```suggestion
	String cur_dir = get_current_dir().trim_suffix("/");
	dir_access->change_dir(cur_dir.get_base_dir());

```
Cleaner IMO.

**Review by KoBeWi — APPROVED** [review]
I can't reproduce the issue myself, but the fix looks fine.

**Comment by Alex2782** [comment]
maybe in one line? `Cleaner`?

```c++
void EditorFileDialog::_go_up() {
	dir_access->change_dir(get_current_dir().trim_suffix("/").get_base_dir());
	update_file_list();
	update_dir();
	_push_history();
}
```

or better?
```c++
void EditorFileDialog::_go_up() {
	String up_dir = get_current_dir().trim_suffix("/").get_base_dir();
	dir_access->change_dir(up_dir);
	
	update_file_list();
	update_dir();
	_push_history();
}
```

**Review by akien-mga — APPROVED** [review]
Looks good.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.3.
