### PR TITLE
Fix noticeable freeze after saving a scene

### LINKED ISSUE #93104: Noticeable freeze after saving a scene
### Tested versions

Regression from #77932

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

I noticed that there is a noticeable editor freeze when saving a scene. I did some profiling and it turns out that when you save a scene, it causes EditorFileSystem update, which causes the FileSystem dock to... reload the whole tree.

While previously it wouldn't be that noticeble, it is after #77932.

Here's a comparison in a dev build.
With #77932

https://github.com/godotengine/godot/assets/2223172/8e73ea9b-6d3e-4bda-b750-6a79299d0f42

Without #77932

https://github.com/godotengine/godot/assets/2223172/9c39a444-2740-48a6-adcf-b0418254bb17

It's 3 times shorter. Maybe we wouldn't have freeze at all if the FileSystem dock did not decide to update for no reason.

### Steps to reproduce

1. Open a project with many resources (e.g. 2000)
2. Save a scene

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Hilderin**
Fixes #93104 and maybe #92515

After testing with a project having a lot of Resources I was able to reproduce the problem.

MRP: 
[test-godot-resource-icon.zip](https://github.com/user-attachments/files/15831495/test-godot-resource-icon.zip)

The problem came from the modifications in `_get_entry_script_icon` for the management of the resource icons, more specifically the calls to `ResourceLoader::get_resource_type` and `EditorFileSystem::get_singleton()->find_file`:
image
image

I reused the cache that was there but instead of resetting the cache at each `_update_tree`, I created a `clear_icon_cache` method and called it only when an icon script or a resource changes. I probably missed some places where the icons could change!?!

It's really not perfect but I guess the performance should be the same as before #77932. 

My tests with 3000 resources:
Before: 4-4.5 seconds
After: 1.5-2 seconds

The time remaining on a save occurs in the Tree, I'm really not sure I should touch that:
image

### CODE REVIEW

**Review by Calinou — COMMENTED** [review]
Tested locally, it works as expected.

However, I can't reproduce https://github.com/godotengine/godot/issues/93104 on an optimized editor build (`optimize=speed lto=full`). Saving is quite fast both before and after this PR, although it's slightly faster with this PR. This is also the case with a debug build (saving takes ~800 ms in `master`, ~700 ms with this PR).

In both cases, the FileSystem dock gets scrolled up when saving the scene. I'd prefer if the existing scroll bar position was kept instead, but that should be looked into in its own PR.

<details open>

<summary>PC specifications</summary>

- **CPU:** Intel Core i9-13900K
- **GPU:** NVIDIA GeForce RTX 4090
- **RAM:** 64 GB (2×32 GB DDR5-5800 C30)
- **SSD:** Solidigm P44 Pro 2 TB
- **OS:** Linux (Fedora 39)
</details>

**Comment by Hilderin** [comment]
Thanks for testing this PR.
I tested on my system and effectively with an optimized build with `optimize=speed lto=full` the master version is pretty fast even if my PC is less performant then yours, it's around 1.5sec after the save and before the editor unfreeze. With the PR, it's less then a second.

For the scrollbar, I don't have the same issue about the scroll bar position.

My PC specifications:
CPU: Intel Core i5-11600KF 3.9Ghz
GPU: NVIDIA GeForce RTX 3060
OS: Windows 11

Master version:

https://github.com/godotengine/godot/assets/81109165/fc4425b3-3615-4bf2-a43a-7d8a329502c8

This PR version:

https://github.com/godotengine/godot/assets/81109165/a447f265-7b94-4b3b-97fd-13f8656c2d91

File: editor/editor_file_system.cpp [hunk 1]
```diff
@@ -1816,13 +1822,19 @@ void EditorFileSystem::update_files(const Vector<String> &p_script_paths) {
...
+			}
 			updated = true;
 		}
 	}
 
 	if (updated) {
 		_update_pending_script_classes();
 		_update_pending_scene_groups();
+		if (clear_icon_cache) {
+			FileSystemDock::get_singleton()->clear_icon_cache();
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:1836]: Instead of calling it here, could it be a callback for `filesystem_changed` instead?

File: editor/editor_file_system.cpp [hunk 2]
```diff
@@ -1816,13 +1822,19 @@ void EditorFileSystem::update_files(const Vector<String> &p_script_paths) {
 			if (fs->files[cpos]->type == SNAME("PackedScene")) {
 				_queue_update_scene_groups(file);
 			}
+			if (fs->files[cpos]->type == SNAME("Resource") || old_script_class_icon_path != fs->files[cpos]->script_class_icon_path) {
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:1825]: The first check returns true only for plain Resources. Is this intended?

File: editor/editor_file_system.cpp [hunk 3]
```diff
@@ -1789,6 +1794,7 @@ void EditorFileSystem::update_files(const Vector<String> &p_script_paths) {
 				_save_late_updated_files(); //files need to be updated in the re-scan
 			}
 
+			String old_script_class_icon_path = fs->files[cpos]->script_class_icon_path;
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:1797]:
```suggestion
			const String old_script_class_icon_path = fs->files[cpos]->script_class_icon_path;
```

File: editor/editor_file_system.cpp (hunk 1 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp:1836]: I'm trying to clear the icon cache in FileSystemDock only if resource are changed. If I clear the cache on every `filesystem_changed` it will be the same as before where the cache was cleared at each tree update because `filesystem_changed` is signaled everytime something is saved. I could created a new signal just for icon_changed if it's better?

Comment (KoBeWi) [reply editor/editor_file_system.cpp:1836]: tbh it would be cleaner if EditorFileSystem was responsible only for file system. So yeah, it's better to have a new signal.

File: editor/editor_file_system.cpp (hunk 2 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp:1825]: Yes it's intended, the purpose here is to manage the modification of the script on a Resource here:

image

The type is "Resource":
image

File: editor/editor_file_system.cpp (hunk 3 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp]: Done!

File: editor/editor_file_system.cpp (hunk 2 above)
Comment (KoBeWi) [reply editor/editor_file_system.cpp:1825]: Yeah but *technically* you can make a custom sub-class of another Resource type, e.g. Texture2D. But maybe it's not worth worrying about 🤔

Comment (Hilderin) [reply editor/editor_file_system.cpp:1825]: You are right!! Maybe I should use `ClassDB::is_parent_class` ??

Comment (KoBeWi) [reply editor/editor_file_system.cpp:1825]: I wonder. Technically any file is a Resource sub-class, so maybe it's better to leave it like that for now.

File: editor/editor_file_system.cpp (hunk 1 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp:1836]: You are right, even a PackedScene is a Resource. I will leave it like that.

File: editor/editor_file_system.cpp (hunk 2 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp:1825]: You are right, even a PackedScene is a Resource. I will leave it like that.

File: editor/editor_file_system.cpp (hunk 1 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp]: I took your alternative solution and moved the icon_path directly into the EditorFileSystem.

File: editor/editor_file_system.cpp [hunk 4]
```diff
@@ -44,6 +44,7 @@
 #include "editor/editor_paths.h"
 #include "editor/editor_resource_preview.h"
 #include "editor/editor_settings.h"
+#include "editor/filesystem_dock.h"
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:47]:
```suggestion
```
Unused.

File: editor/editor_file_system.cpp [hunk 5]
```diff
@@ -740,6 +745,8 @@ void EditorFileSystem::scan() {
 		scanning = false;
 		_update_pending_script_classes();
 		_update_pending_scene_groups();
+		// Update all icons so they are loaded for the FileSystemDock
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:748]:
```suggestion
		// Update all icons so they are loaded for the FileSystemDock.
```
Same below.

File: editor/editor_file_system.cpp [hunk 6]
```diff
@@ -1578,6 +1587,47 @@ String EditorFileSystem::_get_global_script_class(const String &p_type, const St
...
+		}
+	} else {
+		icon_path = file_info->script_class_icon_path;
+	}
+
+	file_info->icon_path = icon_path;
+}
+
+void EditorFileSystem::_update_files_icon_path(EditorFileSystemDirectory *edp) {
+	if (edp == nullptr) {
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:1619]:
```suggestion
	if (!edp) {
```

**Review by KoBeWi — APPROVED** [review]

File: editor/editor_file_system.cpp (hunk 6 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp]: Done!

File: editor/editor_file_system.cpp (hunk 5 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp]: Done!

**Comment by Hilderin** [comment]
One difference I found with my latest modifications are icons for the script that have a `@icon`. Before these scripts did not have an icon, now they do because of the line `icon_path = file_info->script_class_icon_path;` in `EditorFileSystem::_update_file_icon_path`.

Before:
image

After:
image

Should I removed this line?

**Comment by KoBeWi** [comment]
*Technically* it's consistent with the inspector showing icon in Script field, but personally I find it annoying. I think scripts should show script icon (for their language), not their `@icon`, which should be reserved for instances of these scripts.

**Comment by Hilderin** [comment]
I tend to agree with you. I'll revert it to what it was before.

**Comment by Hilderin** [comment]
Done!

File: editor/editor_file_system.cpp [hunk 7]
```diff
@@ -1578,6 +1586,45 @@ String EditorFileSystem::_get_global_script_class(const String &p_type, const St
 	return String();
 }
 
+void EditorFileSystem::_update_file_icon_path(EditorFileSystemDirectory::FileInfo *file_info) {
+	String icon_path;
+	if (file_info->script_class_icon_path.is_empty()) {
+		if (!file_info->deps.is_empty()) {
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:1592]: You can reduce nesting now.
```suggestion
	if (file_info->script_class_icon_path.is_empty() && !file_info->deps.is_empty()) {
```

Comment (Hilderin) [reply editor/editor_file_system.cpp]: Done :)

**Comment by akien-mga** [comment]
Thanks!
