### PR TITLE
OSX: Add signing of directory structure when exporting for OSX

### LINKED ISSUE #52184: Problem adding folder structure containing dylibs to OSX exported app using `EditorExportPlugin`.
### Godot version

3.3.3-stable (from source, with kotlin support)

### System information

OSX arm64

### Issue description

I don't know if it is a bug, but did not see any category that fits better. It is not really a bug IMO, but more a corner case.
I'm currently working on OSX exports for [godot-kotlin](https://github.com/utopia-rise/godot-kotlin-jvm).  
We currently have troubles making OSX export because we have to embed the JRE the user wants (Note that embedding the jre in the template we will provide is not an option as the user should be able to select its JVM version).

In case of graalvm native image we have a simple dylib at the end, so this will be easy to add it to app, sign it and use it, by using `EditorExportPlugin::add_shared_object` method.

The troubles start when we want to use a classic JVM (like OpenJDK).  
We have to load the jvm using `libjvm.dylib`, which is located in : `jre-folder/lib/{client|server|hotspot}/libjvm.dylib`.  
The thing is JVM needs also to load some other libraries, but to do so JVM will look at `libjvm.dylib` path to get where are those libraries, look [here](https://github.com/openjdk/jdk/blob/bd27bb9cbedebd09f589679947ff32261f9ef352/src/hotspot/os/bsd/os_bsd.cpp#L432).

So to sum up, in export plugin I need:
- To be able to add, right into the osx app, a folder containing all JRE and keep its structure.
- Have all dylibs added code signed.

For now it seems I just have two ways to add files to the export:
- Using `EditorExportPlugin::add_file`, but I wonder to what it can be useful while exporting an OSX app as it adds files next to generated `dmg` file (and not in app).
- Using `EditorExportPlugin::add_shared_object`, which ensure signing as far as I understand, but does not keep jre folder structure and so does not enable to load JVM properly.

Did I missed something about how to add files to OSX app from export plugin ?

### Steps to reproduce

Pretty hard to provide as I'm working on fixing the OSX export on our side. 

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by piiertho**
This enable to sign all dylib and framework in a directory added as shared objects.  
This is useful when you need a dependency that contains several dylib, taking care of directory structure (as an example an unsigned JVM build.  

This checks if shared object is a directory.  
If it is, it will call new method `EditorExportPlatformOSX::_code_sign_directory` to explore folder, find all dylib and framework in it and sign them.  
If it is not a directory, this will call `EditorExportPlatformOSX::_code_sign` as before.  

Changes can be easily added to `3.4`.

This resolves #52184

### CODE REVIEW

File: platform/osx/export/export_plugin.cpp [hunk 1]
```diff
@@ -435,6 +435,52 @@ Error EditorExportPlatformOSX::_code_sign(const Ref<EditorExportPreset> &p_prese
...
+    String current_file{dir_access->get_next()};
+    while (!current_file.is_empty()) {
+        String current_file_path{p_path.plus_file(current_file)};
+
+        if (current_file == ".." || current_file == ".") {
+            current_file = dir_access->get_next();
+            continue;
+        }
+
+        if (extensions_to_sign.find(current_file.get_extension()) > -1) {
```
Comment (bruvzg) [inline platform/osx/export/export_plugin.cpp:465]: Just checking for `!current_file..get_extension().is_empty()` should be enough, nothing except dylibs and frameworks is allowed to be in the `Frameworks` anyway.

File: platform/osx/export/export_plugin.cpp [hunk 2]
```diff
@@ -865,22 +911,28 @@ Error EditorExportPlatformOSX::export_project(const Ref<EditorExportPreset> &p_p
...
-				}
-				if (err == OK && sign_enabled) {
-					err = _code_sign(p_preset, tmp_app_path_name + "/Contents/Frameworks/" + src_path.get_file(), ent_path);
+					print_verbose("export dylib: " + src_path + " -> " + path_in_app);
+					err = da->copy(src_path, path_in_app);
 				}
+                if (err == OK && sign_enabled) {
+                    if (da->dir_exists(src_path) && src_path.get_extension().is_empty()) {
+                        // If it is a directory, find and sign all dynamic libraries.
+                        _code_sign_directory(p_preset, path_in_app, ent_path);
```
Comment (bruvzg) [inline platform/osx/export/export_plugin.cpp:931]:
```suggestion
                        err = _code_sign_directory(p_preset, path_in_app, ent_path);
```

**Review by bruvzg — COMMENTED** [review]
The change is fine, but I'm not sure if it will work with JVM. If there are non-executable files in the JVM, it should go into the `Resources` folder instead  of `Frameworks`, like we do with the Mono runtime.

**Comment by piiertho** [comment]
Will do some more testing with JVM to check how it behave without non executables files.  
Then I'll update this PR.

**Comment by bruvzg** [comment]
> Will do some more testing with JVM to check how it behave without non executables files.

Probably the best option is to add an extra argument to the `EditorExportPlugin::add_shared_object` function (or a new dedicated function) to indicate there are non-executable files. If it's set, copy it to the `Resources` instead.

**Comment by piiertho** [comment]
BTW, just for knowledge.  
Is it an apple requirements to have only executable code in Framework dir of the app ?  
Because with all jvm files included it works on my side.

**Comment by bruvzg** [comment]
> Is it an apple requirements to have only executable code in Framework dir of the app ?

It's Apple requirement for notarization. It's not preventing the app from working.

**Comment by piiertho** [comment]
> > Is it an apple requirements to have only executable code in Framework dir of the app ?
> 
> It's Apple requirement for notarization. It's not preventing the app from working.

I think JVM will cause troubles for notarization :/  
There is a file named `module` in lib folder of JVM. If I remove it, JVM cannot initialize properly.  
I tried to place it in resource folder with same layout, but it seems JVM needs it right next to dynamic libraries.

**Comment by bruvzg** [comment]
It's OK to put all other dynamic libraries to the `Resources` as well.

**Comment by bruvzg** [comment]
The only restricted folders are `Frameworks` and `MacOS`, everything else can have any files.

I have seen Java based notarized apps with the structure like this (Java stuff it the root of the bundle):
Screenshot 2021-12-19 at 21 33 04
Putting everything `Resources` seems like a cleaner way, but if it's not working for some reason, it might be an option as well.

**Comment by piiertho** [comment]
Hey ! It should work in `Resources` folder, After all we just dlopen jvm dynamic lib.  
I just want to be sure what's the best folder for embedded `jre.  
It seems Oracle is putting it in `PlugIns` directory. Do you think it is a better option ?

**Comment by bruvzg** [comment]
> PlugIns directory. Do you think it is a better option ?

If other Java app use `PlugIns`, it's probably better to do the same.

**Comment by piiertho** [comment]
> > PlugIns directory. Do you think it is a better option ?
> 
> If other Java app use `PlugIns`, it's probably better to do the same.

Thx ! Will add a method to add to `PlugIns` directory.

**Review by bruvzg — APPROVED** [review]
Everything else seems to be OK.

**Comment by piiertho** [comment]
@bruvzg everything should be fixed

**Review by bruvzg — APPROVED** [review]

**Comment by piiertho** [comment]
@bruvzg need another review as I just spotted I forgot clearing osx plugins when export ends.

**Comment by pycbouh** [comment]
Please squash your commits into one with a single descriptive commit message (title of the PR is okay).

**Comment by piiertho** [comment]
> Please squash your commits into one with a single descriptive commit message (title of the PR is okay).

Done :)

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
