### PR TITLE
Fix kinematic angular velocity calculations

### LINKED ISSUE #47029: [Godot Physics] PhysicsServer reports angular velocity with the wrong sign
**Godot version:**
3.2.3.stable

**OS/device including version:**
N/A

**Issue description:**

If you request the angular velocity estimate of a kinematic body from the physics server with
```
PhysicsServer.body_get_direct_state(self.get_rid()).angular_velocity
```
the Godot physics value has the incorrect sign.  If you rotate with an angular velocity of `(0, 1, 0)`, then the angular velocity estimate is reported as `(0, -1, 0)`.

**Steps to reproduce:**

* Rotate a kinematic body with a fixed angular velocity: `self.rotate(Vector3(0, 1, 0), 1 * delta)`
* See that the reported `angular_velocity` value has the wrong sign: `(0, -1, 0)`

**Minimal reproduction project:**
[angular-velocity-bug.zip](https://github.com/godotengine/godot/files/6142095/angular-velocity-bug.zip)

### PR DESCRIPTION
**Pull request by e344fde6bf**
The angular velocity estimate for kinematic bodies was calculated
incorrectly.  Also, fixes its use in kinematic collision
calculations.

This fixes #47029.

### CODE REVIEW

File: servers/physics_3d/body_3d_sw.cpp [hunk 1]
```diff
@@ -501,20 +501,17 @@ void Body3DSW::integrate_forces(real_t p_step) {
...
 		real_t angle;
 
 		rot.get_axis_angle(axis, angle);
-		axis.normalize();
-		angular_velocity = axis.normalized() * (angle / p_step);
-
-		motion = new_transform.origin - get_transform().origin;
-		do_motion = true;
-
+		angular_velocity = axis * (angle / p_step);
```
Comment (pouleyKetchoupp) [inline servers/physics_3d/body_3d_sw.cpp:514]: Better keep the `axis.normalize();` line to be safe here.

File: servers/physics_3d/space_3d_sw.cpp [hunk 2]
```diff
@@ -332,7 +332,7 @@ bool PhysicsDirectSpaceState3DSW::cast_motion(const RID &p_shape, const Transfor
 			best_first = false;
 			if (col_obj->get_type() == CollisionObject3DSW::TYPE_BODY) {
 				const Body3DSW *body = static_cast<const Body3DSW *>(col_obj);
-				r_info->linear_velocity = body->get_linear_velocity() + (body->get_angular_velocity()).cross(body->get_transform().origin - closest_B);
+				r_info->linear_velocity = body->get_linear_velocity() + (body->get_angular_velocity()).cross(closest_B - body->get_transform().origin);
```
Comment (pouleyKetchoupp) [inline servers/physics_3d/space_3d_sw.cpp:335]: In order to also take the center of mass into account, the correct calculation should be actually:
```
Vector3 rel_vec = closest_B - body->get_transform().origin - body->get_center_of_mass();
r_info->linear_velocity = body->get_linear_velocity() + body->get_angular_velocity().cross(rel_vec);
```
Same for the other cases.

**Review by pouleyKetchoupp — CHANGES_REQUESTED** [review]
Thanks for fixing this!

These changes will also make collider velocity accurate when colliding with rigid bodies in kinematic body motion, since the angular part was inverted before.

File: servers/physics_3d/body_3d_sw.cpp (hunk 1 above)
Comment (pouleyKetchoupp) [reply servers/physics_3d/body_3d_sw.cpp:514]: I'm a bit suspicious about that part of `get_axis_angle()`:
https://github.com/godotengine/godot/blob/ec3f220098f4bf5a10809e6682a9a24ff93d85cb/core/math/basis.cpp#L891-L932
I have no idea if it's exact math and gives normalized axes in all cases, so I would rather be 100% safe and keep the extra `normalize()` since it's not performance critical code.

**Review by pouleyKetchoupp — APPROVED** [review]
Looks good!

**Comment by pouleyKetchoupp** [comment]
It will require a separate PR for 3.3 made against 3.x branch to be cherry-picked, because the file name has changed on master.

**Comment by akien-mga** [comment]
Thanks!
