### PR TITLE
Fix 3D editor Perspective/Ortho shortcut inconsistency

### LINKED ISSUE #71576: Perspective menu Perspective/Orthogonal hotkey display inconsistency
### Godot version

3.5.1, 4.0 beta 12

### System information

Arch Linux x86_64

### Issue description

Under the Perspective menu, the Perspective and Orthogonal buttons have the hotkey in parentheses beside the name, rather than tinted and off to the side like other similar buttons.

Additionally, changing the hotkey does not change the hotkey displayed in the label until the editor is restarted.

image

### Steps to reproduce

1. Open any project or create a new one.
2. Click on the 3D button to access the 3D view.
3. Click the Perspective drop-down.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by EricEzaM**
Fixes #71576

**Before**
original

**After**
image

### CODE REVIEW

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -2208,11 +2208,6 @@ void Node3DEditorViewport::_sinput(const Ref<InputEvent> &p_event) {
 		if (ED_IS_SHORTCUT("spatial_editor/focus_selection", p_event)) {
 			_menu_option(VIEW_CENTER_TO_SELECTION);
 		}
-		// Orthgonal mode doesn't work in freelook.
-		if (!freelook_active && ED_IS_SHORTCUT("spatial_editor/switch_perspective_orthogonal", p_event)) {
-			_menu_option(orthogonal ? VIEW_PERSPECTIVE : VIEW_ORTHOGONAL);
-			_update_name();
-		}
```
Comment (EricEzaM) [inline editor/plugins/node_3d_editor_plugin.cpp:2215]: This is not needed any more due to the blanket `if (freelook_active) accept_event();` at the end of this method.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
