### PR TITLE
Make trackball rotation optional as toggle option of Node3DEditorTool

### LINKED ISSUE #114749: Skeleton3D node Edit Mode is almost unusable
### Tested versions

Reproducible in: v4.6.beta3.official [76dda5c6c]

Did not try any other versions

### System information

Godot v4.6.beta3 - Windows 11 (build 26200) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated AMD Radeon RX 5700 XT (Advanced Micro Devices, Inc.; 32.0.21037.1004) - 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz (12 threads) - 15.86 GiB memory

### Issue description

Skeleton3D node edit mode has a lot of issues and flaws

You cannot select a bone in transform mode, only in select mode, that adds frustrating necessity to change modes
Bone button's hitbox is too small, it's even smaller than its icon
There is no undo/redo after you transform bone

Also, I think it should unselect Skeleton3D node if you clicked past AABB boundaries

Also, maybe there should be Insert Key that is only adding tracks for changed transform bones, or just that adds tracks for selected bone

### Steps to reproduce

Select Skeleton3D node
Turn on edit mode
Try selecting any bone in transform mode (It does not work)
Try selecting any bone in select mode, notice how hard it is to select a bone
Go back to transform mode
Transform bone in anyway
Try undoing that transform (It does not work)

### Minimal reproduction project (MRP)

[skeleton-3d-edit-mode.zip](https://github.com/user-attachments/files/24498942/skeleton-3d-edit-mode.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
- Supersedes/Closes https://github.com/godotengine/godot/pull/115789
- Follow up https://github.com/godotengine/godot/pull/109976
- Fixes: https://github.com/godotengine/godot/issues/114749

https://github.com/user-attachments/assets/27af6fbb-9621-4457-b25b-25b554a67ba2

### CODE REVIEW

**Review by ryevdokimov — CHANGES_REQUESTED** [review]
It's missing the `Node3DEditor::get_state()` check to persist the option across editor sessions.

**Review by ryevdokimov — APPROVED** [review]
I think it solves the regression elegantly enough, and code looks good.

File: editor/scene/3d/node_3d_editor_plugin.h [hunk 1]
```diff
@@ -817,6 +819,8 @@ class Node3DEditor : public VBoxContainer {
 	EditorSpinSlider *snap_rotate = nullptr;
 	EditorSpinSlider *snap_scale = nullptr;
 
+	bool trackball_enabled;
```
Comment (KoBeWi) [inline editor/scene/3d/node_3d_editor_plugin.h]:
```suggestion
	bool trackball_enabled = false;
```
Instead of initializing it in the constructor.

File: editor/scene/3d/node_3d_editor_plugin.cpp [hunk 2]
```diff
@@ -10023,6 +10037,15 @@ Node3DEditor::Node3DEditor() {
 	tool_option_button[TOOL_OPT_USE_SNAP]->set_shortcut_context(this);
 	tool_option_button[TOOL_OPT_USE_SNAP]->set_accessibility_name(TTRC("Use Snap"));
 
+	tool_option_button[TOOL_OPT_USE_TRACKBALL] = memnew(Button);
+	main_menu_hbox->add_child(tool_option_button[TOOL_OPT_USE_TRACKBALL]);
```
Comment (KoBeWi) [inline editor/scene/3d/node_3d_editor_plugin.cpp:10034]: The button should be added to tree _after_ doing setup.
(same applies to the existing code, so just noting it)

File: editor/scene/3d/node_3d_editor_plugin.cpp [hunk 3]
```diff
@@ -7216,6 +7217,11 @@ void Node3DEditor::set_state(const Dictionary &p_state) {
 		tool_option_button[TOOL_OPT_USE_SNAP]->set_pressed(d["snap_enabled"]);
 	}
 
+	if (d.has("trackball_enabled")) {
+		trackball_enabled = d["trackball_enabled"];
+		tool_option_button[TOOL_OPT_USE_TRACKBALL]->set_pressed(d["trackball_enabled"]);
```
Comment (KoBeWi) [inline editor/scene/3d/node_3d_editor_plugin.cpp:7222]: This should use `set_pressed_no_signal()`, but again, the existing code has the same problem, so just noting.

**Review by KoBeWi — APPROVED** [review]

File: editor/scene/3d/node_3d_editor_plugin.h (hunk 1 above)
Comment (TokageItLab) [reply editor/scene/3d/node_3d_editor_plugin.h]: The same applies to snap_enabled, so I think we should probably do an overall refactoring there in the future as separate PR, same with the other review comments below.
