### PR TITLE
Editor: Do not embolden the Main Font if it's variable

### LINKED ISSUE #110426: `InterVariable` font looks a bit blurry in the Editor
### Tested versions

- Reproducable in Godot 4.5rc2
- Reproducable in Godot 4.5-beta1
- Not reproducable in Godot 4.4.1

### System information

Godot v4.5.rc2 - Windows 11 (build 26100) - Multi-window, 4 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 6900 XT (Advanced Micro Devices, Inc.; 32.0.21013.1000) - AMD Ryzen 9 5900X 12-Core Processor (24 threads) - 31.92 GiB memory

### Issue description

I use the `InterVariable` font in the Editor:

Image

Since the Godot 4.5-beta1 version, the font looks a bit blurry compared to Godot 4.4.1:

Image

I don't know if this might be expected, but I thought I report this in case it might be a font rendering regression.

### Steps to reproduce

- Set the `InterVariable` font. 
  - Can be downloaded from the Inter Repo: https://github.com/rsms/inter/releases/tag/v4.1
- Edit a `Node2D` in the Godot Editor
- The font looks different compared to Godot 4.4.1, and a bit blurry

### Minimal reproduction project (MRP)

Too simple to reproduce, and font must be changed in the editor settings (so not project related)

### PR DESCRIPTION
**Pull request by DeeJayLSP**
Fixes #110426

During #106217's writing I was unaware that if the editor's Main Font Bold was unset, it would take the Main Font and embolden it.

In that situation, the weight would be set to bold and the embolden process would happen at the same time, resulting in a very heavy and blurry font.

This changes so emboldening won't happen if the font is variable, as by default, the bold font will be set to have a bold weight.

- Inter Variable set on both Main Font and Main Font Bold:
image

---
- Inter Variable set on Main Font, Main Font Bold unset, before fix:
image

---
- Inter Variable set on Main Font, Main Font Bold unset, after fix:
image

### CODE REVIEW

**Review by Maran23 — APPROVED** [review]
Can confirm that this fixes the issue!

Fix makes sense.
I wondered what the magic number `2003265652` stood for. It turns out that it refers to the `weight`. I wonder if we should create a constant with a good name for it. Let's see what the folks at Godot have to say about it. :)

File: editor/themes/editor_fonts.cpp [hunk 1]
```diff
@@ -286,7 +286,9 @@ void editor_register_fonts(const Ref<Theme> &p_theme) {
 			custom_font->set_fallbacks(fallback_custom);
 		}
 		bold_fc->set_base_font(custom_font);
-		bold_fc->set_variation_embolden(embolden_strength);
+		if (!custom_font->get_supported_variation_list().has(2003265652)) {
```
Comment (AThousandShips) [inline editor/themes/editor_fonts.cpp]: Would be good to have this magic number named for clarity

Comment (DeeJayLSP) [reply editor/themes/editor_fonts.cpp]: My first priority was making the fix work, but now I notice the number can just be replaced with `TS->name_to_tag("wght")`

**Review by Maran23 — APPROVED** [review]
Can confirm that this still works.

In the code, I saw also calls looking like this `name_to_tag("weight")`. Is there a difference between `"wght"`?

**Comment by DeeJayLSP** [comment]
> In the code, I saw also calls looking like this `name_to_tag("weight")`. Is there a difference between `"wght"`?

~~From what I've seen in the code, `name_to_tag()` is supposed to work with [four character OpenType tags](https://simoncozens.github.io/feature-tags/), discarding the rest.~~

~~Whether those are wrong or not, that's unrelated to this PR and probably a case for another PR or issue.~~

**Edit: I have been corrected in the comment below.**

**Comment by bruvzg** [comment]
`name_to_tag` works with 4 letter string codes and a set of default names (see https://github.com/godotengine/godot/blob/master/modules%2Ftext_server_adv%2Ftext_server_adv.cpp#L536). The returned tag is `uint32_t` (contains the same 4 ASCII letter code in memory).

**Review by Calinou — APPROVED** [review]
Code looks good to me.

**Comment by Repiteo** [comment]
Thanks!

**Comment by Repiteo** [comment]
Cherry-picked to 4.5
