### PR TITLE
[iOS] Fix getting Unicode executable path, fix error spam on start.

### LINKED ISSUE #68723: Unicode project names  not compatible with iOS export
### Godot version

3.5.1

### System information

iOS 16.1, mac, xcode 

### Issue description

If you create a new hello world project, with the name `λογικός` and export it as an iOS Xcode project, and attempt to run the newly created project inside Xcode, the application will crash on startup, and report that it cannot find the .pck file.

### Steps to reproduce

Create a new hello world project, with the name λογικός and export it as an iOS Xcode project, and attempt to run the newly created project inside Xcode, the application will crash on startup, and report that it cannot find the .pck file.

### Minimal reproduction project

a blank project is fine to reproduce this problem

### PR DESCRIPTION
**Pull request by bruvzg**
- Fixes https://github.com/godotengine/godot/issues/68723
- Fixes `!configured` and `!classes.has(ti.inherits)` error spam due to `Ref<DirAccess>` created before core type initialization.

### CODE REVIEW

**Comment by akien-mga** [comment]
> Fixes `!configured` and `!classes.has(ti.inherits)` error spam due to `Ref<DirAccess>` created before core type initialization.

Does this fix #65772, or just some error spam but not the underlying issue?

**Comment by bruvzg** [comment]
> Does this fix https://github.com/godotengine/godot/issues/65772, or just some error spam but not the underlying issue?

Probably not, it seems to be some side effect of attaching Xcode debugger, probably caused by the large number of warnings in the shaders.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

File: platform/ios/os_ios.mm [hunk 1]
```diff
@@ -273,13 +271,16 @@ void register_dynamic_symbol(char *name, void *address) {
...
 
-void OS_IOS::set_user_data_dir(String p_dir) {
-	Ref<DirAccess> da = DirAccess::open(p_dir);
-	user_data_dir = da->get_current_dir();
-	printf("setting data dir to %s from %s\n", user_data_dir.utf8().get_data(), p_dir.utf8().get_data());
-}
-
 String OS_IOS::get_user_data_dir() const {
+	static bool user_data_dir_set = false;
+	if (user_data_dir_set) {
```
Comment (ualac) [inline platform/ios/os_ios.mm:276]: should this not be  `if( !user_data_dir_set )` ?  
as it is nothing can set this flag to true and you won't get the run-once behavior that appears to be intended.

Comment (bruvzg) [reply platform/ios/os_ios.mm:276]: Oh, indeed. At least on M1 mac, it seems to do absolutely nothing and the resulting path is the same as the source, so I guess I have removed `!` when renaming the variable, and did not notice it. I'm not sure what's this code supposed to do anyway, so might worth removing it or use `NSSearchPathForDirectoriesInDomains` directly, like we do on macOS.

**Comment by akien-mga** [comment]
Doesn't seem cherry-pickable easily for `3.x`, the init code is somewhat different.
Could you make a dedicated PR so we can still fix #68723 in 3.6? Maybe together with #69334.
