### PR TITLE
Fix `set_window_size` crash when using NaN

### LINKED ISSUE #60466: `OS.set_window_size` crashes Godot
### Godot version

3.5 beta 4

### System information

Ubuntu 22.04, Intel HD 3000

### Issue description

```
	var temp_variable1304 = ClassDB.instance("_OS")
	temp_variable1304.set_window_size(Vector2(-NAN, 33.651245))
```
crashes with message
```
platform/x11/os_x11.cpp:1555:46: runtime error: -nan is outside the range of representable values of type 'unsigned int'
platform/x11/os_x11.cpp:1558:33: runtime error: -nan is outside the range of representable values of type 'int'
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  12 (X_ConfigureWindow)
  Value in failed request:  0x0
  Serial number of failed request:  283
  Current serial number in output stream:  284

```

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by pfertyk**
Fixes #60466.

I'm submitting this to 3.x instead of `master` because the structure of classes and methods changed significantly and I wasn't able to recreate this issue.

### CODE REVIEW

File: platform/x11/os_x11.cpp [hunk 1]
```diff
@@ -1529,6 +1529,15 @@ void OS_X11::set_window_size(const Size2 p_size) {
 	int old_h = xwa.height;
 
 	Size2 size = p_size;
+
+	if (Math::is_nan(size.x)) {
+		WARN_PRINT("Incorrect width (NaN), using 0 instead.");
```
Comment (fire-forge) [inline platform/x11/os_x11.cpp:1534]:
```suggestion
		WARN_PRINT("Invalid width (NaN), using 0 instead.");
```

I think invalid sounds better than incorrect in this context.

File: platform/x11/os_x11.cpp [hunk 2]
```diff
@@ -1529,6 +1529,15 @@ void OS_X11::set_window_size(const Size2 p_size) {
...
+		size.x = 0;
+	}
+	if (Math::is_nan(size.y)) {
+		WARN_PRINT("Incorrect height (NaN), using 0 instead.");
```
Comment (fire-forge) [inline platform/x11/os_x11.cpp:1538]:
```suggestion
		WARN_PRINT("Invalid height (NaN), using 0 instead.");
```

**Comment by pfertyk** [comment]
Changed to `Invalid` @fire-forge  :)

File: platform/x11/os_x11.cpp [hunk 3]
```diff
@@ -1529,6 +1529,15 @@ void OS_X11::set_window_size(const Size2 p_size) {
...
 	Size2 size = p_size;
+
+	if (Math::is_nan(size.x)) {
+		WARN_PRINT("Invalid width (NaN), using 0 instead.");
+		size.x = 0;
+	}
+	if (Math::is_nan(size.y)) {
+		WARN_PRINT("Invalid height (NaN), using 0 instead.");
+		size.y = 0;
+	}
```
Comment (akien-mga) [inline platform/x11/os_x11.cpp:1540]: Since it's then set to 1 right after, it would be best to set it to 1 right away instead of mentioning 0.

Comment (pfertyk) [reply platform/x11/os_x11.cpp]: Good point :) I've replaced it with `ERR_FAIL_COND`, let me know if you would like to add a message as well :)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.5.
