### PR TITLE
GDScript: Don't get invalid dictionary key during completion

### LINKED ISSUE #102926: ERROR: Attempted to getptr a variable of type 'Nil' into a TypedDictionary.Key of type <T>.
### Tested versions

- Reproducible in v4.4.beta3.official [06acfccf8]
- Reproducible in v4.4.beta2.official [a013481b0]
- Reproducible in v4.4.dev7.official [46c8f8c5c]
- Reproducible in v4.4.dev5.official [9e6098432]
- Reproducible in v4.4.dev3.official [f4af8201b] <---- **Appeared there**
- Not reproducible in v4.4.dev2.official [97ef3c837] 
- Not occurring in v4.3.stable.official [77dcf97d8] since Typed Dictionaries (https://github.com/godotengine/godot/pull/78656) were introduced in 4.4.dev2

### System information

Godot v4.4.beta3 - Windows 11 (build 26100) - Multi-window, 2 monitors - OpenGL 3 (Compatibility) - AMD Radeon RX 6600 (Advanced Micro Devices, Inc.; 32.0.11037.4004) - AMD Ryzen 7 2700X Eight-Core Processor (16 threads)

### Issue description

While investigating for https://github.com/godotengine/godot/issues/100458, I got this error while typing code:

`ERROR: Attempted to getptr a variable of type 'Nil' into a TypedDictionary.Key of type 'String'.`

It happens when accessing a **constant** dictionary with a **defined type** for its **key** within a **for loop** iterating a **declared typed array for its key.**
- Does not happen with non constant dictionary
- Does not happen with non typed Dictionaries (or just typed as `Dictionary`)
- Does not happen if the type for the key is Variant
- Does not happen if the array iterating is non typed  (or just as `Array`)

Ex: 
```gdscript
const dict: Dictionary[String, int] = {
		"a": 12
	}

var n: Array[String] = ["a", "b", "c"]

for s in n:
	dict[s]. # <--- type anything here and you get the error
```

It's thrown by https://github.com/godotengine/godot/blob/f42e612da286b14b3a50eff7935615b3bc132c37/core/variant/container_type_validate.h#L103

I tested `float`, `int` and `String` for the key / array and all of them threw the error.

### Steps to reproduce

- Declare a constant typed dictionary
- Declare a typed array (same as key)
- Iterate through the array and access the dictionary with the iterator
- Try to access any property / method from this value
- Get the error

### Minimal reproduction project (MRP)

[GetPtrError.zip](https://github.com/user-attachments/files/18815944/GetPtrError.zip)

### PR DESCRIPTION
**Pull request by vnen**
We try to get the value out of a dictionary in order to establish its type for completion purposes. However, if the dictionary or the key is not a constant, we cannot safely get the actual value, so we skip this and just try to infer from static typing.

> [!NOTE]
> ~~This also adds a change in core: it removes type validation from `Dictionary.has()` (and `has_all()`) because it simplifies checking if a given key is valid without having to check its type externally.~~
> This now exposes the `ContainerTypeValidate` object from the dictionary and add a function to it to test a value without generating errors. This way the completion code can check it before trying to get the key.

Fix #102926
Supersedes #104757

### CODE REVIEW

File: core/variant/dictionary.cpp [hunk 1]
```diff
@@ -217,14 +217,12 @@ bool Dictionary::is_empty() const {
 
 bool Dictionary::has(const Variant &p_key) const {
 	Variant key = p_key;
-	ERR_FAIL_COND_V(!_p->typed_key.validate(key, "use 'has'"), false);
```
Comment (Ivorforce) [inline core/variant/dictionary.cpp]: This _sort of_ makes sense to me, but it's kind of inconsistent with the rest of the API.
I'd rather add a function like `const ContainerTypeValidate &get_key_validator()`, and allow querying it if the given key is compatible. Something like that, anyway.

In any case, this change should be run by the core meeting, I think.

**Comment by Ivorforce** [comment]
Following the core meeting, here's my suggestion:

1. Expose validators through `Dictionary` API:
```c++
const ContainerTypeValidate &get_key_validator();
const ContainerTypeValidate &get_value_validator();
```

2. Add a bool-based validation method to `ContainerTypeValidate`, mostly copying `validate`, ala
```c++
bool can_validate_variant(const Variant &p_variant) const
```

3. Use the new functions from autocomplete to avoid error messages

**Comment by vnen** [comment]
Updated to use the proposed `ContainerTypeValidate` API

**Comment by Ivorforce** [comment]
> Updated to use the proposed ContainerTypeValidate API

I see no changes, did you forget to push?

**Comment by vnen** [comment]
> > Updated to use the proposed ContainerTypeValidate API
> 
> I see no changes, did you forget to push?

I did forget to push :laughing:

**Review by Ivorforce — APPROVED** [review]
This works for me. 
Having to convert a variant just to test may be inefficient, but it's not used in performance sensitive code, so it's fine.

Thanks for working with the feedback!

**Comment by Ivorforce** [comment]
@vnen Looks like tests have been failing with the latest build

**Review by Repiteo — APPROVED** [review]
Looks good!

**Comment by Repiteo** [comment]
Thanks!
