### PR TITLE
Fix "scale" property collision in CPUParticles

### LINKED ISSUE #20126: CPU Particles converter issues
**Godot version:**
Godot master build (d488c35ef)

**OS/device including version:**
Windows 10

**Issue description:**
I found the following problems when converting Particles into CPU particles:
1. Converter dont save old node name and set name of converted node to `CPUParticles`
2. Converter dont migrate node translation and rotation and set to zero
3. `Life time` and `gravity`  of converted CPUParticles affect in different way than in original particles 

**Minimal reproduction project:**
[godot-particle-test.zip](https://github.com/godotengine/godot/files/2191050/godot-particle-test.zip)

### PR DESCRIPTION
**Pull request by JFonS**
CPUParticles had a property called "scale" (copied fron ParticlesMaterial) that collided with Spatial's scale. 

I also changed the way transform scale affects initial velocity so it's consistent with (GPU)Particles.

Closes  #20126

### CODE REVIEW

**Comment by akien-mga** [comment]
There's the same conflict for CPUParticles2D and Node2D, no?

Wouldn't it be possible to make CPUParticles* a material, so that we could use either CPUParticlesMaterial or GPUParticlesMaterial in the Particles* node directly?

**Comment by JFonS** [comment]
I updated the commit o fix the conflict in CPUParticles2D.

I think it would be very quite difficult to do what you propose, implementation-wise.

File: scene/2d/cpu_particles_2d.cpp [hunk 1]
```diff
@@ -1305,9 +1305,9 @@ void CPUParticles2D::_bind_methods() {
 	ADD_PROPERTYI(PropertyInfo(Variant::REAL, "angle_random", PROPERTY_HINT_RANGE, "0,1,0.01"), "set_param_randomness", "get_param_randomness", PARAM_ANGLE);
 	ADD_PROPERTYI(PropertyInfo(Variant::OBJECT, "angle_curve", PROPERTY_HINT_RESOURCE_TYPE, "Curve"), "set_param_curve", "get_param_curve", PARAM_ANGLE);
 	ADD_GROUP("Scale", "");
```
Comment (akien-mga) [inline scene/2d/cpu_particles_2d.cpp]: Maybe the second argument should be `particle_` here?

File: scene/2d/cpu_particles_2d.cpp [hunk 2]
```diff
@@ -1305,9 +1305,9 @@ void CPUParticles2D::_bind_methods() {
...
-	ADD_PROPERTYI(PropertyInfo(Variant::REAL, "scale", PROPERTY_HINT_RANGE, "0,1000,0.01,or_greater"), "set_param", "get_param", PARAM_SCALE);
-	ADD_PROPERTYI(PropertyInfo(Variant::REAL, "scale_random", PROPERTY_HINT_RANGE, "0,1,0.01"), "set_param_randomness", "get_param_randomness", PARAM_SCALE);
-	ADD_PROPERTYI(PropertyInfo(Variant::OBJECT, "scale_curve", PROPERTY_HINT_RESOURCE_TYPE, "Curve"), "set_param_curve", "get_param_curve", PARAM_SCALE);
+	ADD_PROPERTYI(PropertyInfo(Variant::REAL, "particle_scale", PROPERTY_HINT_RANGE, "0,1000,0.01,or_greater"), "set_param", "get_param", PARAM_SCALE);
```
Comment (reduz) [inline scene/2d/cpu_particles_2d.cpp]: I would rename this one to scale_amount I think, would make a tiny bit more sense for whoever looks at it

**Comment by JFonS** [comment]
Updated commit.

**Comment by akien-mga** [comment]
Thanks!
