### PR TITLE
Fix hole in heightmap navigation mesh baking

### LINKED ISSUE #76195: Baking a NavigationMesh for HeightMapShape creates incorrect NavMesh
### Godot version

4.0.2.stable

### System information

Windows 10, Vulkan, Nvidia RTX 3060 Ti

### Issue description

When baking a NavMesh from code for a StaticBody3D that has a HeightMapShape as its Shape, the resulting navmesh is offset and skewed strangely.

Here's a simple example where a radial gradient image is used to generate cone shaped collision for a HeightMapShape. As you can see the navmesh is offset and distorted compared to the collision.

radial

navmesh

### Steps to reproduce

Please see the Minimal Repro project attached below.
When you run it, you can move the debug camera with WASD and rotate it by holding down the right mouse button.

The project is structured like this:

navmesh_proj

Note: The **Parsed Geometry Type** of the **NavigationMesh** is set to **Static Colliders**

The script on the root node generates collision from an image and then bakes the navmesh. 

### Minimal reproduction project

[NavmeshBug.zip](https://github.com/godotengine/godot/files/11258220/NavmeshBug.zip)

### LINKED ISSUE #80509: NavigationRegion3D generates inexplicable hole at (0,0,0) against HeightMapShape3D with values at -1.5 to -1.75...
### Godot version

4.1.1 Stable

### System information

Windows 11, RTX 3070TI, Vulcan

### Issue description

NavigationRegion3D generates inexplicable hole at (0,0,0) against HeightMapShape3D with values at -1.5 to -1.75

Not sure how this hasn't been noticed before, but the NavigationMeshRegion3D bakes a single square unit size hole at (0,0,0) against HeightMapShape3D if it is using values between -1.5 and -1.75... I have attached a MRP that is very easy to use and demonstrate the error happening.

### Steps to reproduce

Create a HeightMapShape3D, set values between -1.5 and -1.75, bake NavigationRegion3D mesh on it. Observe hole in mesh at (0,0,0). 

In MRP with the "main" node selected, you can adjust the "height_map_value" export variable to move a dynamically generated heightmapshape3d up and down, the script will automatically rebake the navmesh when the value is changed. When values are between -1.5 and -1.75 a hole will appear at (0,0,0)

[MRP_NavMeshHole.zip](https://github.com/godotengine/godot/files/12319007/MRP_NavMeshHole.zip)
image

### Minimal reproduction project

In MRP with the "main" node selected, you can adjust the "height_map_value" export variable to move a dynamically generated heightmapshape3d up and down, the script will automatically rebake the navmesh when the value is changed. When values are between -1.5 and -1.75 a hole will appear at (0,0,0)

### PR DESCRIPTION
**Pull request by smix8**
Fixes hole in heightmap navigation mesh baking.

Fixes https://github.com/godotengine/godot/issues/80509.

Apparently the pr https://github.com/godotengine/godot/pull/76212 that was made to fix https://github.com/godotengine/godot/issues/76195 was wrong. I now tried with both MRPs with this pr and it fixes both for me. No "inexplicable holes" show up and the heightmap-from-texture also bakes its half-sphere correctly but more testers are welcome to finally close this heightmap bug-juggle-chapter.

### CODE REVIEW

File: modules/navigation/nav_mesh_generator_3d.cpp [hunk 1]
```diff
@@ -388,29 +388,18 @@ void NavMeshGenerator3D::generator_parse_staticbody3d_node(const Ref<NavigationM
...
+							int vertex_index = 0;
+
+							for (int d = 0; d < heightmap_depth - 1; d++) {
+								for (int w = 0; w < heightmap_width - 1; w++) {
+									vertex_array_ptrw[vertex_index] = Vector3(start.x + w, map_data[(heightmap_width * d) + w], start.y + d);
+									vertex_array_ptrw[vertex_index + 1] = Vector3(start.x + w + 1, map_data[(heightmap_width * d) + w + 1], start.y + d);
+									vertex_array_ptrw[vertex_index + 2] = Vector3(start.x + w, map_data[(heightmap_width * d) + heightmap_width + w], start.y + d + 1);
+									vertex_array_ptrw[vertex_index + 3] = Vector3(start.x + w + 1, map_data[(heightmap_width * d) + w + 1], start.y + d);
+									vertex_array_ptrw[vertex_index + 4] = Vector3(start.x + w + 1, map_data[(heightmap_width * d) + heightmap_width + w + 1], start.y + d + 1);
+									vertex_array_ptrw[vertex_index + 5] = Vector3(start.x + w, map_data[(heightmap_width * d) + heightmap_width + w], start.y + d + 1);
```
Comment (AThousandShips) [inline modules/navigation/nav_mesh_generator_3d.cpp:401]:
```suggestion
									vertex_array_ptrw[vertex_index] = start + Vector3(w, map_data[(heightmap_width * d) + w], d);
									vertex_array_ptrw[vertex_index + 1] = start + Vector3(w + 1, map_data[(heightmap_width * d) + w +1], d);
									vertex_array_ptrw[vertex_index + 2] = start + Vector3(w, map_data[(heightmap_width * d) + heightmap_width + w], d + 1);
									vertex_array_ptrw[vertex_index + 3] = start + Vector3(w + 1, map_data[(heightmap_width * d) + w +1], d);
									vertex_array_ptrw[vertex_index + 4] = start + Vector3(w + 1, map_data[(heightmap_width * d) + heightmap_width + w +1], d + 1);
									vertex_array_ptrw[vertex_index + 5] = start + Vector3(w, map_data[(heightmap_width * d) + heightmap_width + w], d + 1);
```
And make `start` a `Vector3`, for readability, same below.

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` 8c25a98fdf68dc388eddaefa188f3386236cdfe4), it works as expected.

Before | After *(this PR)*
-|-
Screenshot_20231022_232218 webp | Screenshot_20231022_232154 webp

**Comment by akien-mga** [comment]
Thanks!
