### PR TITLE
Fix RtAudio driver buffer_size incorrect calculation

### LINKED ISSUE #10644: RtAudio warning while game is running, and audio has sound pops
**Operating system or device, Godot version:**
Windows 10 64bit - Godot 2.1.4 RC

**Issue description:**
The warning "RtAudio output underflow!" shows up in the error log a few times per second while the game is running. And audio (specifically tested using the Platformer demo with the music) has a popping sound almost in sync with the warnings.

This was not present in 2.1.4 2017-08-17, the audio sounds completely normal in that build and there was no warnings.

**Steps to reproduce:**
Open any project or create a new project and run it.

### PR DESCRIPTION
**Pull request by marcelofg55**
Should fix #10644 and #7288.
Previous to this PR the audio buffer size was resulting too small on the RtAudio driver, and this triggered the underflow warnings.

### CODE REVIEW

**Comment by akien-mga** [comment]
For the reference, this code has been added @lonesurvivor in da6b6c2dd7.

File: drivers/rtaudio/audio_driver_rtaudio.cpp [hunk 1]
```diff
@@ -117,65 +117,37 @@ Error AudioDriverRtAudio::init() {
 	mix_rate = GLOBAL_DEF("audio/mix_rate", 44100);
 
 	int latency = GLOBAL_DEF("audio/output_latency", 25);
-	// calculate desired buffer_size, taking the desired numberOfBuffers into account (latency depends on numberOfBuffers*buffer_size)
-	unsigned int buffer_size = closest_power_of_2(latency * mix_rate / 1000 / target_number_of_buffers);
```
Comment (akien-mga) [inline drivers/rtaudio/audio_driver_rtaudio.cpp]: You can likely remove the assignment of `target_number_of_buffers` a few lines above.

Comment (marcelofg55) [reply drivers/rtaudio/audio_driver_rtaudio.cpp]: Yeah, I've just removed it.
