### PR TITLE
[Rendering] Add hints to some uniform `PropertyInfo`s

### LINKED ISSUE #89436: shader uniform uint allows negative numbers in inspector panel
### Tested versions

Tested in 4.2 canvas_item shader

### System information

Godot v4.2.1.stable - macOS 14.3.0 - GLES3 (Compatibility) - Apple M2 Max - Apple M2 Max (12 Threads)

### Issue description

`uniform uint unsigned_int = 1;`

unsigned_int cannot set to negative 'inside the shader' which is perfect. But the uniform allows to be to set to a negative integer 'inside the inspector panel', that's a bug. It can be set by typing and by using the decrement arrow.

### Steps to reproduce

1. create a Node2D scene
2. Add a `canvas_item` shader to the root node
3. add a uint uniform

```
shader_type canvas_item;
uniform uint unsigned_int = 1;
```

4. go to shader parameter
5a. type a negative number
5b. use arrows to decrease the number below 0

Screenshot 2024-03-13 at 10 37 21

### Minimal reproduction project (MRP)

1. create a Node2D scene
2. Add a `canvas_item` shader to the root node
3. add a uint uniform

```
shader_type canvas_item;
uniform uint unsigned_int = 1;
```

4. go to shader parameter
5a. type a negative number
5b. use arrows to decrease the number below 0

Screenshot 2024-03-13 at 10 37 21

### PR DESCRIPTION
**Pull request by AThousandShips**
* Enforce range on `int/uint`
* Use flags for `bvec2/3/4` arrays

Left some `TODO` notes for possible future improvements, unsure what can be one with them but good to add if we end up improving other contexts

Full change can't be cherry picked as it depends on arrays having hints, but can cherry pick specifically the `int/uint` case if desired

---

* Fixes: https://github.com/godotengine/godot/issues/89436

### CODE REVIEW

File: servers/rendering/shader_language.cpp [hunk 1]
```diff
@@ -4076,13 +4076,16 @@ PropertyInfo ShaderLanguage::uniform_to_property_info(const ShaderNode::Uniform
 		case ShaderLanguage::TYPE_BOOL:
 			if (p_uniform.array_size > 0) {
 				pi.type = Variant::PACKED_INT32_ARRAY;
+				// TODO: Handle boolean representation.
```
Comment (AThousandShips) [inline servers/rendering/shader_language.cpp:4079]: Tried doing this with a `boolean` type hint but it didn't work correctly, could use a `flags` hint but unsure if it's as useful, or if it will be translated correctly, will test later

File: servers/rendering/shader_language.cpp [hunk 2]
```diff
@@ -4076,13 +4076,17 @@ PropertyInfo ShaderLanguage::uniform_to_property_info(const ShaderNode::Uniform
 		case ShaderLanguage::TYPE_BOOL:
 			if (p_uniform.array_size > 0) {
 				pi.type = Variant::PACKED_INT32_ARRAY;
+				pi.hint = PROPERTY_HINT_TYPE_STRING;
+				pi.hint_string = itos(Variant::INT) + "/" + itos(PROPERTY_HINT_FLAGS) + ":" + RTR("On");
```
Comment (AThousandShips) [inline servers/rendering/shader_language.cpp:4080]: Slightly hacky I'd say, but translation works fine with this, so for now it's sufficient, tried with `hint_string = itos(Variant::BOOL)` but it didn't work, unsure if that's because I'm not using it correctly or because it's bugged somehow, but solved it this way for now

File: servers/rendering/shader_language.cpp [hunk 3]
```diff
@@ -4111,18 +4119,24 @@ PropertyInfo ShaderLanguage::uniform_to_property_info(const ShaderNode::Uniform
 		case ShaderLanguage::TYPE_INT: {
 			if (p_uniform.array_size > 0) {
 				pi.type = Variant::PACKED_INT32_ARRAY;
+				// TODO: Handle range and encoding for for unsigned values.
```
Comment (AThousandShips) [inline servers/rendering/shader_language.cpp:4122]: There should probably be some hint for the editor to treat `PACKED_INT32_ARRAY` as unsigned for the purposes of editing, as a future improvement

**Comment by AThousandShips** [comment]
I'll be experimenting with some improvements to property handling perhaps this weekend, would start with experimenting with remapping unsinged integers to be edited correctly, that should be relatively straight forward to do, adding it as a hint string

Might also look at adding special constants to the range to help with things, like `(U)INT8/16/32/64_MIN/MAX` to the range handling

File: servers/rendering/shader_language.cpp (hunk 2 above)
Comment (clayjohn) [reply servers/rendering/shader_language.cpp:4080]: Could you explain the logic here a bit? Using type string doesn't seem obvious to me as I am a bit unfamiliar with this area of the editor.

Comment (AThousandShips) [reply servers/rendering/shader_language.cpp:4080]: This makes it a check, a single "on" checkbox as flags, will upload a screenshot when I'm back at the computer

Comment (AThousandShips) [reply servers/rendering/shader_language.cpp:4080]: image

Like so, for boolean vectors and arrays of booleans

Comment (clayjohn) [reply servers/rendering/shader_language.cpp:4080]: Thank you. I already understand _what_ it does, what I don't understand is why setting the hint to a string and then using that specific string ("2/6:On") results in a checkbox

Comment (raulsntos) [reply servers/rendering/shader_language.cpp:4080]: If it helps, the format is `{element_type}/{element_hint}:{element_hint_string}`. This means that for each element in the array, we can specify a `hint` and `hint_string`.

In this case, to export a property as a checkbox you need to use `PROPERTY_HINT_FLAGS` as the `hint`, and then you can specify the label in the `hint_string`.

There's more examples in the [`PROPERTY_HINT_TYPE_STRING`](https://docs.godotengine.org/en/stable/classes/class_@globalscope.html#class-globalscope-constant-property-hint-type-string) documentation.

Comment (clayjohn) [reply servers/rendering/shader_language.cpp:4080]: Thank you! That makes sense

**Review by clayjohn — APPROVED** [review]
Seems like a nice improvement!

**Comment by akien-mga** [comment]
Should be squashable before merge.

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank *you*!
