### PR TITLE
Fix ItemList click detection gaps

### LINKED ISSUE #88095: ItemList has a non-clickable deadzone between items in the editor
### Tested versions

- Reproducible in: 3.5.3.stable, 4.2.1.stable, 4.3.dev 284397d6c

### System information

Godot v4.3.dev (284397d6c) - Fedora Linux 39 (KDE Plasma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 545.29.06) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

As I reported in https://github.com/godotengine/godot-proposals/issues/8264#issuecomment-1786566547, ItemLists in the editor have a non-clickable deadzone between items:

https://github.com/godotengine/godot-proposals/assets/180032/466f9cf9-1f4b-4874-838e-1aaac69a55ff

This is made more evident by ItemList hover feedback being implemented in 4.2 and later, but the issue also exists in 3.x.

This is likely caused by the editor theme having inconsistent spacing/margin attributes for ItemList items.

### Steps to reproduce

- Create 3 scripts, go to the Script tab, open them all and hover the mouse slowly between them. Notice how the hover highlight disappears when the mouse is between two scripts, but it shouldn't – clicking on the ItemList should *always* select an item.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by davthedev**
Fixes #88095

### CODE REVIEW

File: scene/gui/item_list.cpp [hunk 1]
```diff
@@ -1495,6 +1495,13 @@ int ItemList::get_item_at_position(const Point2 &p_pos, bool p_exact) const {
 
 	for (int i = 0; i < items.size(); i++) {
 		Rect2 rc = items[i].rect_cache;
+
+		// Grow the detection rectangle to match the grown selection indicator
```
Comment (akien-mga) [inline scene/gui/item_list.cpp:1499]:
```suggestion
		// Grow the detection rectangle to match the grown selection indicator.
```

**Review by Calinou — APPROVED** [review]
Tested locally at all editor scale presets, it works as expected.

https://github.com/godotengine/godot/assets/180032/32eda233-edc1-48eb-9795-b37d03617e4c

**Comment by akien-mga** [comment]
Thanks!
