### PR TITLE
Spatial::look_at() now preserves its scale values

### LINKED ISSUE #10003: Spatial.look_at affects more than just rotation
**Operating system or device - Godot version:**
Windows 10
Godot 3.0 alpha-1

**Issue description:**
look_at reverts the scale on the affected scale, expected behavior should only be changing the rotation of the model instead of the whole transformation.

**Steps to reproduce:**
Create a spatial with a scale vector other than `(1,1,1)` and perform a look_at on the spatial towards any point.

### LINKED ISSUE #19000: look_at resets scale
Call reset on a spatial with a scale that isn't (1,1,1) and see what happens.

### PR DESCRIPTION
**Pull request by rodolforg**
It always normalized basis after look_at() computation.
Now it applies previous scale back, in order to avoid
distortions when global scale was different of (1,1,1).

fix #10003 and fix #19000

### CODE REVIEW

File: scene/3d/spatial.cpp [hunk 1]
```diff
@@ -676,7 +676,7 @@ void Spatial::set_identity() {
 void Spatial::look_at(const Vector3 &p_target, const Vector3 &p_up) {
 
 	Transform lookat;
-	lookat.origin = get_global_transform().origin;
+	lookat = get_global_transform();
```
Comment (akien-mga) [inline scene/3d/spatial.cpp]: You can move that up to the previous line as `Transform lookat = get_global_transform();`.

Comment (rodolforg) [reply scene/3d/spatial.cpp]: Done.

**Comment by akien-mga** [comment]
Please squash those commits together.

**Comment by reduz** [comment]
This should be done in Node, but not in Transform, since Transform one is a reference implementation of the function and it creates a new one, without keeping anything.

**Comment by KoBeWi** [comment]
It would also fix #17924.

**Comment by rodolforg** [comment]
I originally coded on Node, but I thought it would be better to be on
Transform.
As I was wrong, I'll fix it later today

Em qui, 25 de abr de 2019 às 20:34, Tomek <notifications@github.com>
escreveu:

**Comment by akien-mga** [comment]
Thanks!

**Comment by dc740** [comment]
Thank you! I was affected by this too in my custom billboards. I hope this gets pushed to production ASAP.

**Comment by malbach** [comment]
Hi,
I might be wrong but shouldn't [look_at_from_position](https://github.com/godotengine/godot/blob/712b789dc83f1d6e9279aa7c9368e6dc3ee7a21e/scene/3d/spatial.cpp#L696) be corrected also ?
I know it's not the same use case, but to me **look_at_from_position** can fire the same bug, no ?. 
And in addition, it doesn't have the error checks that **look_at** has.

**Comment by Zylann** [comment]
I found `look_at_from_position` does reset scale in 3.1, would be nice to be fixed if it still does in master.

**Comment by dc740** [comment]
You should definitely create a new issue, so it doesn't get lost, and it's easier to find for someone with the same problem

**Comment by rodolforg** [comment]
@malbach fixed and merged ;)
