### PR TITLE
Avoid crashes when engine leaks canvas items and friends

### LINKED ISSUE #85495: Godot crashes on shutdown after interacting with a GraphEdit editor plugin.
### Godot version

4.2.dev

### System information

Godot v4.2.rc (custom build) - Fedora Linux 39 - Wayland - Vulkan (Mobile) - integrated AMD Radeon Vega 11 Graphics (RADV RAVEN) - AMD Ryzen 5 2400G

### Issue description

Godot crashes on shutdown after interacting with a GraphEdit editor plugin.
```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.rc.custom_build (1ff13eb3889c7e7d8e004a13ef9e7076b02135ce)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib64/libc.so.6(+0x3e9a0) [0x7ff0883e09a0] (??:0)
[2] RendererCanvasRender::Polygon::~Polygon() (/home/user/Godot/./servers/rendering/renderer_canvas_render.h:154)
[3] RendererCanvasRender::Item::CommandPolygon::~CommandPolygon() (/home/user/Godot/./servers/rendering/renderer_canvas_render.h:228)
[4] void memdelete<RendererCanvasRender::Item::Command>(RendererCanvasRender::Item::Command*) (/home/user/Godot/./core/os/memory.h:112)
[5] RendererCanvasRender::Item::clear() (/home/user/Godot/./servers/rendering/renderer_canvas_render.h:419)
[6] RendererCanvasRender::Item::~Item() (/home/user/Godot/./servers/rendering/renderer_canvas_render.h:473)
[7] RendererCanvasCull::Item::~Item() (/home/user/Godot/servers/rendering/renderer_canvas_cull.h:40)
[8] RID_Alloc<RendererCanvasCull::Item, true>::~RID_Alloc() (/home/user/Godot/./core/templates/rid_owner.h:349)
[9] RID_Owner<RendererCanvasCull::Item, true>::~RID_Owner() (/home/user/Godot/./core/templates/rid_owner.h:427)
[10] RendererCanvasCull::~RendererCanvasCull() (/home/user/Godot/servers/rendering/renderer_canvas_cull.cpp:2177)
[11] void memdelete<RendererCanvasCull>(RendererCanvasCull*) (/home/user/Godot/./core/os/memory.h:112)
[12] RenderingServerDefault::~RenderingServerDefault() (/home/user/Godot/servers/rendering/rendering_server_default.cpp:428)
[13] void memdelete<RenderingServer>(RenderingServer*) (/home/user/Godot/./core/os/memory.h:112)
[14] finalize_display() (/home/user/Godot/main/main.cpp:324)
[15] Main::cleanup(bool) (/home/user/Godot/main/main.cpp:3842)
[16] ./godot.linuxbsd.editor.dev.x86_64.llvm(main+0x1b3) [0x4c7e5a3] (/home/user/Godot/platform/linuxbsd/godot_linuxbsd.cpp:78)
[17] /lib64/libc.so.6(+0x2814a) [0x7ff0883ca14a] (??:0)
[18] /lib64/libc.so.6(__libc_start_main+0x8b) [0x7ff0883ca20b] (??:0)
[19] ./godot.linuxbsd.editor.dev.x86_64.llvm(_start+0x25) [0x4c7e325] (??:?)
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

1. Open the MRP in the Godot editor
2. Open the "Behavior Tree" bottom tab
3. Close Godot editor

### Minimal reproduction project

[Minimal reproduction project](https://github.com/godotengine/godot/files/13495874/Crasher.zip)

### PR DESCRIPTION
**Pull request by YuriSizov**
Closes https://github.com/godotengine/godot/issues/85495. Code is gently stolen from the Vulkan renderer, which does a similar thing.

Now you'll see this with the MRP on exit:

```
servers\rendering\renderer_canvas_cull.cpp:2172 - 28 RIDs of type "CanvasItem" were leaked.
WARNING: 28 RIDs of type "CanvasItem" were leaked.
     at: RendererCanvasCull::_free_rids (servers\rendering\renderer_canvas_cull.cpp:2172)
```
Plus a lot of other leaks.

----

What happens, basically, is that when there is a leak we are left with some data in the `RendererCanvasCull` class. When we try to delete it, it attempts to delete all its memory, including `RendererCanvasRender::Item`s it has in store. These contain commands which contain polygons. When you delete polygons, we need to access the `RendererCanvasRender` singleton. But this singleton is already null at this point (it is removed when the rendering server is finalized, whereas `RendererCanvasCull` is only removed when the rendering server is deleted).

So we need to do these things earlier and with more grace, and report to the user that they have a leak.

### CODE REVIEW

**Comment by YuriSizov** [comment]
I also noticed some outdated code that was out of place in relevant files, so I did a little cleanup. Seems like it dates back to https://github.com/godotengine/godot/commit/2787ad65be12a8ac84b7cc8536749686e9fe80dc#diff-2eaa5fdddb0bc4674976c8bbaeb5aab4c69d5a3c74fb1ead3a00f9e9c06a4f26, but after some additional changes the singleton definition should be moved to the class' own file.

Thanks @clayjohn for looking into it 🙃

**Review by akien-mga — APPROVED** [review]
Looks good to me overall.
Waiting for rendering team review to merge.

File: servers/rendering/renderer_canvas_cull.cpp [hunk 1]
```diff
@@ -2165,6 +2165,30 @@ bool RendererCanvasCull::free(RID p_rid) {
...
+	List<RID> owned;
+	p_owner.get_owned_list(&owned);
+	if (owned.size()) {
+		if (owned.size() == 1) {
+			WARN_PRINT(vformat("1 RID of type \"%s\" was leaked.", p_type));
+		} else {
+			WARN_PRINT(vformat("%d RIDs of type \"%s\" were leaked.", owned.size(), p_type));
+		}
+		for (const RID &E : owned) {
+			free(E);
```
Comment (BastiaanOlij) [inline servers/rendering/renderer_canvas_cull.cpp:2179]: We don't do this consistantly on the 3D side but if you search you'll see a few places I added it, but seeing that it can be very difficult to find the cause of the leak simply by a count, I check if a description was recorded for the RID (this is a debug/tools build only feature), than we print the description of the resource being leaked.

This also means off course that we need to get more consistent in recording descriptions when the resource is allocated. Something we can improve on over time.

**Review by BastiaanOlij — APPROVED** [review]
This looks good to me, it makes perfect sense to add this check. It's helped us lots of times on the 3D side.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.
