### PR TITLE
Unify y-flip behavior for sky in RD backends

### LINKED ISSUE #99193: Sky is not rendering for right eye in VR (4.4.dev4)
### Tested versions

Not reproducible in v4.3.stable.mono.official [77dcf97d8], v4.4.dev1.mono.official [28a72fa43], v4.4.dev3.mono.official [f4af8201b]
Producible in v4.4.dev4.mono.official [36e6207bb]
I was not able to get VR to work at all on v4.4.dev2.mono.official [97ef3c837], it would hang on the Godot splash. 

### System information

Windows 11 - Godot 4.4 dev4 mono - Vulkan (Forward+) - AMD Ryzen 7 3800x - NVIDIA RTX 3070 Ti with driver 566.03

### Issue description

The sky is not visible for the right eye in VR. (4.4.dev4)
Screenshot
The sky should be visible for both eyes. (4.4.dev3)
Screenshot

### Steps to reproduce

1. Create and open a new project
2. Enable OpenXR and XR shaders
3. Create a new scene with a WorldEnvironment with Background set to Sky and set a new material for the sky. I used a PhysicalSkyMaterial.
4. Create an XROrigin node, and a XRCamera as a child
5. Attach a script to the scene root that enables XR for the viewport
```gdscript
extends Node3D
func _ready() -> void:
	get_viewport().use_xr = true
```
6. Run the project

### Minimal reproduction project (MRP)

[skyrepro.zip](https://github.com/user-attachments/files/17738256/skyrepro.zip)

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/99193

Most of this PR is just cleanup. The original bug was a copy-paste error that we missed because the list of arguments to `setup_sky` was so long. Almost all the arguments come straight from RenderDataRD, so we just pass a reference to that struct instead. 

The important change here is that we use the `depth_correction` `y_flip` instead of manually doing a y flip in the shader. This way the sky will use the same logic as the scene and we don't have to maintain a bunch of hacks for alternative codepaths (like we had previously for ReflectionProbes)

CC @BastiaanOlij

### CODE REVIEW

File: servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp [hunk 1]
```diff
@@ -1957,22 +1957,7 @@ void RenderForwardClustered::_render_scene(RenderDataRD *p_render_data, const Co
...
-			} else {
-				Projection projection = p_render_data->scene_data->cam_projection;
-				if (p_render_data->scene_data->cam_frustum) {
-					// Sky is drawn upside down, the frustum offset doesn't know the image is upside down so needs a flip.
-					projection[2].y = -projection[2].y;
-				}
-
-				sky.setup_sky(p_render_data->environment, rb, *p_render_data->lights, p_render_data->camera_attributes, p_render_data->scene_data->view_count, &projection, p_render_data->scene_data->view_eye_offset, p_render_data->scene_data->cam_transform, projection, screen_size, p_render_data->scene_data->taa_jitter, this);
-			}
+			sky.setup_sky(p_render_data, screen_size, p_render_data->scene_data->taa_jitter);
```
Comment (BastiaanOlij) [inline servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:1960]: Seeing you're passing `p_render_data` here, does it make sense to pass `p_render_data->scene_data->taa_jitter` here as it will be accessible from its source?

Comment (clayjohn) [reply servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:1960]: Yep!

**Review by BastiaanOlij — APPROVED** [review]
Confirmed this both with stereo test project and a live XR project. Everything renders correctly in stereo again.

**Comment by akien-mga** [comment]
Thanks!
