### PR TITLE
Ensure default node groups' call queue are processed

### LINKED ISSUE #77548: Setting bone rotation in _process gets overridden by running animation in 4.1-dev3
### Godot version

4.1 dev3

### System information

Windows 11, Forward+, Intel 13700k, 4070ti

### Issue description

In 4.0.x and in 4.1 dev2, if you overwrite the rotation of a bone in `_process` it has preferred over the currently running animation. In 4.1 dev3, the running animation takes precedence and overwrites any changes in `_process`. This happens both with a simple animation and with an animation tree, and happens in-editor and in-game.

### Steps to reproduce

1. Open the attached project.
2. Click on `AnimationPlayer` and pick an animation, e.g. `Armature|Standing`. Set it to looping if it's not already. (@RandomShaper's note: and play it).
3. Click on the `PointOfInterest` and move it along the X axis.
4. If you're on:
    - 4.0.x or 4.1-dev2: Notice the head rotating
    - 4.1-dev3: Notice that nothing happens

### Minimal reproduction project

[BoneRotationIssue-4.0.3.zip](https://github.com/godotengine/godot/files/11582187/BoneRotationIssue-4.0.3.zip)
[BoneRotationIssue-4.1-dev.zip](https://github.com/godotengine/godot/files/11582188/BoneRotationIssue-4.1-dev.zip)

Should include all licensing stuff for the model, but let me just add [the link](https://opengameart.org/content/human-model-ready-for-animation) for good measure.

### LINKED ISSUE #78470: Skeleton causes error and project stops working when played when a camera3D is in the scene.
### Godot version

4.1 b2

### System information

Windows 10, Nvidia GTX 1660Ti, Vulkan

### Issue description

As you can see in the image:

skeleton_error_41b2

In the editor I have an imported model, no errors. The model has a skeleton. Moving bones moves the mesh accordingly no errors and nothing seems to be wrong as far as I can tell.

When I play the project without the camera I get no errors.
When I play the project with a Camera3D the project throws 12 errors (see the image above) and the whole project freezes without dispalying anything as you can see in the image it's just a gray window.

This model and import works just fine in 4.0.3, this is also not the only model I have issues with so it's not just this model.

I can't provide a test scene or models because these models are purchased but I hope the fact it works in 4.0.3 and the error could help?

I'll try anything you ask me to do to help to resolve this - hopefully before 4.1 get released.

NOTE: Same error and the following line as in the screenshot appear in the windows Console, no other errors.
NOTE2: This project was initiated from 4.1beta as brand new, nothing else is in as you can see.
NOTE3: I'll need to double check but I had some models working before so it might not be with every model but I'll check later on today.

### Steps to reproduce

Hard to tell, if you have a model with a skeleton give it a try, add the model t othe scene, camera3d and then see if it happens?

### Minimal reproduction project

~~For now check this one from another report: https://github.com/godotengine/godot/issues/77780~~

[TestMeshWithSkinGD.zip](https://github.com/godotengine/godot/files/11851108/TestMeshWithSkinGD.zip)

EDIT:
Related line where the editor takes me to: https://github.com/godotengine/godot/blob/a2575cba48121a9e31c3a550ebd29398a7facf3f/servers/rendering/renderer_rd/storage_rd/mesh_storage.h#L693

**Production team edit:** Added the non-mono MRP (reduced to fit Github's size limit) to the issue.

### PR DESCRIPTION
**Pull request by RandomShaper**
Fixes #78470.
May fix #77548.
Supersedes #78623,

### CODE REVIEW

File: scene/main/scene_tree.cpp [hunk 1]
```diff
@@ -1052,13 +1052,13 @@ void SceneTree::_process(bool p_physics) {
 		if (p_physics) {
 			if (!pg->physics_nodes.is_empty()) {
 				process_valid = true;
-			} else if (pg->owner != nullptr && pg->owner->data.process_thread_messages.has_flag(Node::FLAG_PROCESS_THREAD_MESSAGES_PHYSICS) && pg->call_queue.has_messages()) {
+			} else if (pg == &default_process_group || (pg->owner != nullptr && pg->owner->data.process_thread_messages.has_flag(Node::FLAG_PROCESS_THREAD_MESSAGES_PHYSICS)) && pg->call_queue.has_messages()) {
```
Comment (akien-mga) [inline scene/main/scene_tree.cpp:1055]: This generates a warning, `a || b && c` is too ambiguous.
