### PR TITLE
Fix: Profiler and Visual Profiler start/stop state inconsistency

### LINKED ISSUE #65209: Godot profiler cant start
### Godot version

v4.0.alpha15.official

### System information

Windows10,Vulkan

### Issue description

I can't start Godot profiler

### Steps to reproduce

I started the Godot profiler before I started the game, but after I started the game, the Godot profiler didn't output any results. I had to turn it off and then turn it on to output
image
Then, when the game is running, I pause the scene first, and then stop the scene. At this time, I can't start the Godot profiler again
image
image

### Minimal reproduction project

_No response_

### LINKED ISSUE #70143: Profiler and Visual Profiler start/stop state inconsistency
### Godot version

4.0.beta8

### System information

macOS 13.0.1

### Issue description

This may be borderline usability improvement, but I think it can be considered a bug report. Basically the bug here is that the Visual profiler, unlike the Profiler is not automatically stopped when running the game if it's been left running from the previous run. So, the Visual profiler appears to be running but it is probably not, or at least not connected to the current running game instance.

Beside the simple reported bug here that the Profiler and Visual Profiler behave differently (and theProfiler slightly better) a more robust usability improvement to fix this issue as well could be to stop both profilers when the game is quit, and possibly not allow starting them when the project isn't running to more clearly communicate that they only work while the game is running (see #65209).

### Steps to reproduce

- Run a project (any project)
- Start the Visual Profiler in the Debug tab
- Stop the game
- Observer the profiler looks like it's still running
- Run the game again
- Observer the profiler looks like it's still running

### Minimal reproduction project

Any project as it's an issue in the editor profiler interface

### PR DESCRIPTION
**Pull request by stmSi**
Fix: #70143 
Fix: #65209 

This is my Fix according to my understanding of the issues

- **Star**t buttons are disabled (grey out) if not running the program (default).
- **Start/Stop** buttons are enabled when run the program.
- **Start/Stop** buttons are disabled (grey out) when pause the program.
- Pressing **Start** buttons will change to **Stop** and vice visa
-  Stopping the program will reset **Stop** button to **Start** and disable the button.

also changes to the Clear button in "Visual Profiler" to be the same behavior with Profiler's Clear button.

### CODE REVIEW

File: editor/debugger/script_editor_debugger.cpp [hunk 1]
```diff
@@ -957,7 +958,9 @@ void ScriptEditorDebugger::stop() {
 	res_path_cache.clear();
 	profiler_signature.clear();
 
-	profiler->set_enabled(true, false);
+	profiler->set_enabled(false, false);
+	visual_profiler->set_enabled(false);
+
```
Comment (clayjohn) [inline editor/debugger/script_editor_debugger.cpp:963]:
```suggestion
```

You'll have to delete this line to pass CI

**Comment by KoBeWi** [comment]
I think the Start button should still be enabled and when you start in the editor, the profiling should autostart when the project is started. That's how it worked in 3.x at least.

File: editor/debugger/editor_visual_profiler.cpp [hunk 2]
```diff
@@ -647,10 +650,26 @@ void EditorVisualProfiler::_bind_methods() {
 	ADD_SIGNAL(MethodInfo("enable_profiling", PropertyInfo(Variant::BOOL, "enable")));
 }
 
+void EditorVisualProfiler::_set_button_text() {
```
Comment (KoBeWi) [inline editor/debugger/editor_visual_profiler.cpp:653]: It should be called `_update_button_text()`, because it's not a setter.

**Comment by stmSi** [comment]
> I think the Start button should still be enabled and when you start in the editor, the profiling should autostart when the project is started. That's how it worked in 3.x at least.

@KoBeWi 
In 3.5.2 rc1, profiler doesn't autostart. That's why i disabled Start button at first. I still don't familiar with debugger to implement autostart yet. May be enable by default after we implement autostart?

File: editor/debugger/editor_visual_profiler.cpp (hunk 2 above)
Comment (stmSi) [reply editor/debugger/editor_visual_profiler.cpp]: changed for both "Profiler" and "Visaul Profiler". thanks for suggestion.

File: editor/debugger/editor_profiler.cpp [hunk 3]
```diff
@@ -510,13 +510,18 @@ void EditorProfiler::_bind_methods() {
...
-	activate->set_pressed(false);
 	activate->set_disabled(!p_enable);
 	if (p_clear) {
 		clear();
 	}
 }
 
+void EditorProfiler::set_pressed(bool p_pressed) {
+	activate->set_pressed(p_pressed);
+
```
Comment (KoBeWi) [inline editor/debugger/editor_profiler.cpp:521]: This blank line could be removed.

**Review by KoBeWi — APPROVED** [review]
> May be enable by default after we implement autostart?

Makes sense.

File: editor/debugger/editor_profiler.cpp (hunk 3 above)
Comment (stmSi) [reply editor/debugger/editor_profiler.cpp]: done. for both Profiler and Visual Profiler.

**Comment by akien-mga** [comment]
Thanks!
