### PR TITLE
Display and allow setting name/index of BlendSpace points

### LINKED ISSUE #4417: Show index of the points in AnimationBlendSpace
### Describe the project you are working on

working on advanced movement system with multiple animation layers.

### Describe the problem or limitation you are having in your project

I can't know the index of point in BlendSpace so I can edit its animation through code to choose another animation.

this is the code to edit its animation : 
`$AnimationTree.tree_root.get_node("name_of_BlendSpaceNode").get_blend_point_node(index).animation = "new_anim"`

here is a related issue : 
#4381 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

show the index of the point in the properties panel like (Animation,Play Mode)
BlendSpaceIndex

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

yes, but it isn't good workaround, though for advanced animations I think it will be used often, though here is the workaround script :

```
var blendspace = $AnimationTree.root.get_node("your_blendspace")
for b in blendspace.get_blend_point_count():
   print("index %s, animation %s" % [b, blendspace.get_blend_point_node(b).animation])
```

### Is there a reason why this should be core and not an add-on in the asset library?

simple feature to add, no need for extra plugin for this, and I think it will help anyone who wants to edit BlendSpace's points properties

### LINKED ISSUE #12487: Allow naming of BlendSpace points
### Describe the project you are working on

A stealth action game with complex blended animations.

### Describe the problem or limitation you are having in your project

When any node is placed as a point within a `BlendSpace` through the interface, the point is assigned a numerical index as its name, from 0, ascending from its creation time.

Image

So, if I create a `BlendSpace2D` and create four nested `BlendTree`s within, and want to manipulate them in code, I have to keep track of their indexes 0, 1, 2 and 3. However, if I delete number 1, then 3 becomes 2, 2 becomes 1, and all lines in my code referencing these paths need to be edited to accommodate this. As you can imagine, this gets very unwieldy when there are a large number of points being edited.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Therefore, I propose some changes, which could aid consistency across `AnimationTree`:
1. Adding Class properties on the Inspector for all `AnimationNode` resources, not just `AnimationNodeAnimation`.
2. In this, expose a "Name" property that can be manually defined by the user, the same property as the node names in `BlendTree` or state names in `StateMachine`.
3. In `BlendSpace`, instead of the index system, default names be assigned in normal `BlendTree` and `StateMachine` convention: First added `BlendSpace1D` has the name "BlendSpace1D", the second has "BlendSpace1D 2", then "BlendSpace1D 3", and so on. This "name" is now what is used as the path for points nested within a `BlendSpace`.
5. Allow editing of blend position from the sidebar as well, so that precise entry is now possible for a `BlendSpace` point, as well as being able to see it's name without needing to enter its editor with "Open Editor" first.
6. Finally, a small QOL feature: when clicking away to deselect a node/point in `BlendTree`, `StateMachine` or `BlendSpace` editors, revert the selection to the parent. So, if I have a `BlendSpace2D` within which is an `AnimationNodeAnimation` point, clicking on the point will give me its inspector, but clicking away into blank space will revert the currently selected node to be the `BlendSpace2D` that we are currently inside.

From what I can tell, this index system that `BlendSpace` currently offers no way to properly change points' index via the interface, and also is inconsistent to the intuitive experience offered by `BlendTree` and `StateMachine`, that use `name: StringName` in their methods instead of the arbitrarily assigned and constantly changing `point: int`.

I have been unable to find someone online using it as part of their game code aside from #4417, and I couldn't personally think of a use case for the index system that is not possible with a name. I am wrong in this, please let me know.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Image

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It will be used often.

### Is there a reason why this should be core and not an add-on in the asset library?

It is a core part of the engine interface and affects usability.

### LINKED ISSUE #66336: AnimationTree blend result value is not determined.
### Godot version

4.0 b1

### System information

Win10 Vulkan gtx1060

### Issue description

A 2d sprite uses an animationTree, the same blend 2d space nodes, the same blend point coordinates, but the result is different.

adminTree_bug

ps: Connecting and not connecting nodes does not affect the results.

### Steps to reproduce

See minimal sample

### Minimal reproduction project

[AnimationTree_Bug.zip](https://github.com/godotengine/godot/files/9638181/AnimationTree_Bug.zip)

### PR DESCRIPTION
**Pull request by vaner-org**
Closes [#12487](https://github.com/godotengine/godot-proposals/issues/12487), closes [#4417](https://github.com/godotengine/godot-proposals/issues/4417), closes [#66336](https://github.com/godotengine/godot/issues/66336).

~For ease of review and feedback, this PR's commits are currently separate.~ I'd like to walk through everything this commit adds, so that any additions deemed extraneous can be removed before the squash.

## Allow naming points

Points can now be named, and their name will now hold their reference in code.

Allow naming points

~This is not a breaking change, all index references remain valid until they are replaced with a name.~ On first launch, indices are transcribed into the string names, that can then be changed by the user.

## Visible index/name

In both BlendSpace editors, the index/name is now visible above the point.

Visible indexes

If this text is too close to the left/right/top edge, it automatically moves itself to fit in the visible view.

https://github.com/user-attachments/assets/c2ec8b5b-9c4c-42f3-8c9e-6a4fa84258be

The point can also be dragged using its text.

## Unique names upon creation

As mentioned in [#12487](https://github.com/godotengine/godot-proposals/issues/12487), points are now given unique names in  the same convention as BlendTree and StateMachine.

Unique names given upon creation

## Inline editing for names

When a point's text is clicked and released without initiating a drag, its name can be edited inline. ~If this name is removed, the point reverts to using its index reference.  A purely numeric name results in the forced prefixing of '#'.~ If an empty name is committed, the point reverts to a name based on its node type or animation.

https://github.com/user-attachments/assets/3de76906-13ff-4590-93f9-09d5ccac2fbf

## Editing index via toolbar or scrolling directly over points

It is possible to edit the index of a point by incrementing/decrementing/specifying a new index via the toolbar, or scrolling over the points. This makes the BlendSpace editor enter a temporary state where indexes are displayed above points, rather than names. ~It is possible edit the name here too, and once again, a purely numeric name results in the forced prefixing of '#'.~

Editing index and name via toolbar

## Consolidating point editing tools to the right side

The toolbar was moved to the right to consolidate all the "point editing" features to one side, to better separate the tools editing the blend space as a whole versus a blend point within it.

Consolidating point editing tools to the right side

~However, since the name box can likely be removed entirely thanks to the inline editing, maybe this change not needed. That being said, I do feel it helps AnimationTree usability as a whole, and can relegate it to another PR.~

***

The issue this PR closes was one of the first major pain points I had with animation in Godot. However, the scope of this is beyond anything I've attempted before, so feedback is very much appreciated. I will integrate recommendations as soon as I can.

What in my opinion needs the most rigorous testing is undo/redo, it took me a while to get it free of bugs.

### CODE REVIEW

File: scene/animation/animation_blend_space_1d.cpp [hunk 1]
```diff
@@ -191,6 +203,56 @@ Ref<AnimationRootNode> AnimationNodeBlendSpace1D::get_blend_point_node(int p_poi
...
 
+void AnimationNodeBlendSpace1D::set_blend_point_name(int p_point, const String &p_name) {
+	ERR_FAIL_INDEX(p_point, blend_points_used);
+
+	String final_name = p_name;
+
+	// Avoid names that are purely numeric.
+	if (!p_name.is_empty() && p_name.is_valid_int()) {
+		final_name = "#" + p_name;
+	}
```
Comment (TokageItLab) [inline scene/animation/animation_blend_space_1d.cpp]: I believe names should be allowed even in cases where they are just simple numbers.

Especially problematic is that attempting to rename a point once triggers the name to change from a numeric-only string to something else, breaking compatibility with old project codes.

The concern here would be that users cannot know or control the index of the point array, so there is a possibility that the array index and the number might not match.

Therefore, as mentioned above, if we provide a way for users to control the array index, then as long as the names are unique, we should be able to accept even just numbers. Additionally, I believe we can avoid confusion by distinguishing the index display with colored (like yellow) text.

**Review by TokageItLab — CHANGES_REQUESTED** [review]
I agree that the current point names are just transcribed array indices and are not meaningful.

~However, in my opinion, regardless of whether these points have meaningful names, we need to implement a way to control the array indices.~

~The reason is that triangle creation priority follows the order in which points are stored in the array. Therefore, this PR should not resolve #66336.~

~I'm still positive about this PR, but adding some kind of GUI that allows users to see the array indices storing points and reorder them (means users should be able to see both the point name and the index of the array) would provide a stronger reason to merge it.~

Ah sorry, I realized I can change the index using the spinner. Please disregard the comment above.

Therefore, it should be fine as long as concern about naming restriction is resolved.

From a usability perspective, changing the index via the spinner is not so intuitive. Then I feel it would be helpful to have a function to move the selected point to either the most top or most bottom (this should allow creating a preferred triangle by applying it any three points in cases where symmetrical quadrilateral occur like https://github.com/godotengine/godot/issues/66336).

File: scene/animation/animation_blend_space_2d.cpp [hunk 2]
```diff
@@ -126,6 +126,56 @@ Ref<AnimationRootNode> AnimationNodeBlendSpace2D::get_blend_point_node(int p_poi
...
+	}
+}
+
+String AnimationNodeBlendSpace2D::get_blend_point_name(int p_point) const {
+	ERR_FAIL_INDEX_V(p_point, blend_points_used, String());
+	if (blend_points[p_point].name.is_empty()) {
+		return itos(p_point);
+	}
+	return blend_points[p_point].name;
+}
```
Comment (TokageItLab) [inline scene/animation/animation_blend_space_2d.cpp]: As mentioned above, I believe names with only simple number should be permitted. Furthermore, empty names should not be allowed, so this exception handling should be removed. Or just check `ERR_FAIL_COND_V(blend_points[p_point].name.is_empty(), String());`.

**Review by TokageItLab — CHANGES_REQUESTED** [review]

File: editor/animation/animation_blend_space_2d_editor.cpp [hunk 3]
```diff
@@ -353,10 +413,14 @@ void AnimationNodeBlendSpace2DEditor::_add_menu_type(int p_index) {
 		return;
 	}
 
+	// Trim 'AnimationNode' from class name.
+	String unique_name = _generate_unique_blend_point_name(blend_space, node->get_class().substr(13));
```
Comment (TokageItLab) [inline editor/animation/animation_blend_space_2d_editor.cpp]:
```suggestion
	String unique_name = _generate_unique_blend_point_name(blend_space, node->get_class().replace_first("AnimationNode", "");
```
To be clear and for consistency with StateMachineEditor.

**Review by TokageItLab — CHANGES_REQUESTED** [review]

**Comment by vaner-org** [comment]
> From a usability perspective, changing the index via the spinner is not so intuitive. Then I feel it would be helpful to have a function to move the selected point to either the most top or most bottom (this should allow creating a preferred triangle by applying it any three points in cases where symmetrical quadrilateral occur like #66336).

It's possible to type into the index field a number higher than the number of points to clamp it to the top, or a negative number to clamp it to 0. Is this not satisfactory?

**Comment by TokageItLab** [comment]
@vaner-org That might be sufficient to some extent. However, since there's no way for users to know this within the editor, it should probably be documented somewhere, like in a tooltip or at least in the documentation. Ideally, right-clicking might bring up options including renaming, but if that's too much work, just the documentation for now should suffice (and I think we can send the right-click option as follow up PR later).

File: scene/animation/animation_blend_space_1d.cpp (hunk 1 above)
Comment (vaner-org) [reply scene/animation/animation_blend_space_1d.cpp]: I'm not sure I follow.

The intention here is for the name field be opt-in, and also locked in once created. The array index and the name being separate properties, with the name always taking precedence and never changing outside of user intervention is the new paradigm under this PR, and also what allows this to have backwards compatibility and not be a breaking change.

> Especially problematic is that attempting to rename a point once triggers the name to change from a numeric-only string to something else, breaking compatibility with old project codes.

Again, I'm not sure I follow. Clearing the name always reverts to index used as reference, and inline editing a point with only an index gives it a blank name, to start.

I think it would help me understand if you could tell me what you would prefer instead. If there is an index-based point that has its reference in code as `"parameters/BlendSpace1D/1/blend_position"`, what would you like a new point with the (string) name "1" to become, once I press enter? At the moment, it becomes "#1".

It can be "2", or "3", or whichever the next named index is.
Or it can be "1 2", like other names do.

It can't also be "1" though, because there's no way to distinguish between the two when referring to them via code.

File: scene/animation/animation_blend_space_2d.cpp (hunk 2 above)
Comment (vaner-org) [reply scene/animation/animation_blend_space_2d.cpp]: Empty names are what allows the fallback to index to work. If empty names are no longer allowed, how will this PR not break older projects?

File: scene/animation/animation_blend_space_1d.cpp (hunk 1 above)
Comment (TokageItLab) [reply scene/animation/animation_blend_space_1d.cpp]: I means that when `AnimationNodeBlendSpace1D::set_blend_point_name(2, "1")` occurs, the name should be set to `1` instead of `#1` unless there is already a Node named `1` in the same Space.

If an empty name is used, simply reject the empty name instead of reverting to the index.

> It can't also be "1" though, because there's no way to distinguish between the two when referring to them via code.

I don't understand the meaning of this. What's seen in the code implies paths, but they are always valid only by name. Also, the function for getting points always looks only at the array index, while names are used to search for array indices, so their roles are distinct. There is no confusion between them, so there should be no restrictions on the names given to nodes.

Therefore, the number set in the name property is completely unrelated to the array index, so it doesn't need a `#` prefix. If an arbitrary name `777` is assigned to a point originally having path `parameters/BlendSpace1D/1/blend_position`, path `parameters/BlendSpace1D/1/blend_position` becomes invalid thereafter, and only `parameters/777/Jump/blend_position` remains valid.

Comment (vaner-org) [reply scene/animation/animation_blend_space_1d.cpp]: Okay, but if index 1 has the name "1" and then the point with the index 0 (and no name yet) swaps indexes with "1", what would the new reference of the 0 node be, since the reference "1" is already taken?

> ...unless there is already a Node named `1` in the same Space.

What happens then?

Comment (TokageItLab) [reply scene/animation/animation_blend_space_1d.cpp]: It should either be a unique name or trigger an alert and be rejected. If based on NodeTreeDock behavior, the sequence number would increment to `2`. If based on AnimationPlayerEditor's animation addition, an alert would appear and the operation would be rejected.

File: scene/animation/animation_blend_space_2d.cpp (hunk 2 above)
Comment (TokageItLab) [reply scene/animation/animation_blend_space_2d.cpp]: This means older project script may be manipulating BlendSpace using path `parameters/blendspace2d/1/blend2/amount`. The problem arises when they change the name from `parameters/blendspace2d/1` to `parameters/blendspace2d/any` and then cannot revert it back to `parameters/blendspace2d/1` since now this PR make it `parameters/blendspace2d/#1`.

> If empty names are no longer allowed, how will this PR not break older projects?

BlendTree blending relies on subpaths, and without a name, the path cannot be created. This is why empty names are not permitted. There is no relationship between not allowing empty name and compatibility.

So in current BlendSpace2D, the index and name were _tentatively_ the same (in other words, it's just that numbers are used in the name), but since the index is not the name, it should not be returned by the get_name function as a fallback.

Comment (vaner-org) [reply scene/animation/animation_blend_space_2d.cpp]: > The problem arises when they change the name from `parameters/blendspace2d/1` to `parameters/blendspace2d/any` and then cannot revert it back to `parameters/blendspace2d/1` since now this PR make it `parameters/blendspace2d/#1`.

I think you're misunderstanding something here. This isn't something this PR does, they can just clear the name to go back to the index reference, either through the toolbar, through inline edit, or through code. The empty name property is what allows the path reference to fallback into index.

If names can no longer be empty, _then_ the problem you describe arises. Not now. It also prevents anyone that relied on the index system in the past, with it self managing through `add_blend_point` and `remove_blend_point` to continue to use their blendspaces the same way.

Comment (TokageItLab) [reply scene/animation/animation_blend_space_2d.cpp]: I don't understand why you absolutely must fall back to the empty name in the index. The index and the name are completely separate things, residing in different domains. So it should be sufficient to simply disallow empty names and permit names simple number.

Current BlendSpace `add_blend_point()` and `remove_blend_point()` are also looking at an array index which is an `int` value, not retrieving a stringified number from the name.

Comment (vaner-org) [reply scene/animation/animation_blend_space_2d.cpp]: If empty names are disallowed, does that mean once a point has a name, it must keep a name and use that name forever, and no longer be accessible via its index?
So projects edited after this PR, once they give a name to a blendspace point, can no longer clear or reset it to a prior state, with what used to be an automatically managed index for a reference that is subject to `add_blend_point` and `remove_blend_point`? How is this not a breaking change?

Comment (TokageItLab) [reply scene/animation/animation_blend_space_2d.cpp]: Are you implying cases where points are dynamically removed at runtime, causing the path to change? I don't think such cases occur frequently. However, if you're assuming that the path might change when the number of points changes and the same path indicates a different point entity depends on that changing path, the old index should match the array index. Therefore, the path name implemented by this PR should be retrievable with `get_blend_point_name()`.

Comment (vaner-org) [reply scene/animation/animation_blend_space_2d.cpp]: Do we have any way of knowing that? The old system was clandestine but we can't discount that changing things in the way you recommend would be a breaking change for those cases, for someone that relied on indexes for whatever reason. If a point was inserted at in index in the middle of the array, all the following points would shift forward. Forcing names onto users will break something for someone, and lead to more unexpected behavior than now.

This PR in it's current state _does_ allow name and index to continue residing in different domains, and the lines of code highlighted here just elegantly allow for a fallback to index when the name isn't present, in cases where both are interchangeable.

For when the name is explicitly needed (null, not index when no name), `get_blend_point_stored_name` is what is called. Should I change the names of the functions instead, to make their roles clearer?

Also, while I would be happy to make a change here because no one disliked the prior index-only system as much as I did, I think backgrounding indexes as a concept is a bad idea, because of #66336. Users should be aware that indexes play a special role in BlendSpaces, even if that means keeping the (flawed) current paradigm intact. This PR simply heavily nudges users in the direction of having named blend points, and they really have to go out of their way to continue using indexes for reference.

Comment (TokageItLab) [reply scene/animation/animation_blend_space_2d.cpp]: Let's imagine there are points like the following:

```
A: parameters/blendspace2d/0
B: parameters/blendspace2d/1
C: parameters/blendspace2d/2
```

If A is deleted, the old system would look like this:

```
B: parameters/blendspace2d/0
C: parameters/blendspace2d/1
```

Indeed, if A is deleted on the new system might behave as follows when assigning a permanent name:

```
B: parameters/blendspace2d/1
C: parameters/blendspace2d/2
```

The migration path for this behavior change should be the `get_blend_point_name()` function.

```
B: parameters/blendspace2d/ + get_blend_point_name(0)　
C: parameters/blendspace2d/ + get_blend_point_name(1)　
```

These arguments should match the indices of the old system.

I assume there are no other locations in the core that permit empty name, and I believe there is no need for migration paths that duplicate roles.

These cases relying on this dynamic path should be quite niche. Furthermore, since a migration path is provided, I believe such minor compatibility breaks are acceptable (although we'll ultimately discuss it with the animation team).

Eventually, what you really need here is to add migration code to the setter so that when an old project is opened for the first time after this PR, and the name is empty, the index is used as the default name. Probably you can refer to the setter for AnimationPlayer. Then, remove the fallback, don't allow empty name and allow simple numeric names, I believe everything should be fine.

Comment (vaner-org) [reply scene/animation/animation_blend_space_2d.cpp]: Okay, I understand. Let me know when there is a consensus and I'll make changes accordingly.

Comment (TokageItLab) [reply scene/animation/animation_blend_space_2d.cpp]: I've posted to [ContributorsChat](https://chat.godotengine.org/channel/animation) to open the discussion, so you can join if you're interested.

**Comment by lyuma** [comment]
(from rocketchat) I'm not happy about changing from returning a cached StringName name; to calling String get_blend_point_name(int p_point) const; which then must perform itos(i) followed by String -> StringName conversion, at every _process

If the names could be cached, I might feel better about it. Or maybe, for compatibility, we should always store the number as the name, and if the name is numeric, then it always uses an index and ignores the name.

**Comment by TokageItLab** [comment]
@lyuma That case `parameters/blendspace2d/ + get_blend_point_name(0)` exists solely for compatibility with niche scenarios where paths depend on dynamically changing points. If you want to cache the path name in cases where it depends on this dynamic path, you would likely need to handle caching on the user side before and after `add_point()` or `remove_point()`. Alternatively, adding a signal like `points_reordered` could be another approach to consider.

However, as I mentioned above, I believe use cases that rely on paths being dynamically changed are niche. So in most normal cases where you're just accessing path `parameters/blendspace2d/0` (`0` is "name", not "index") shouldn't affect performance. The current BlendSpace dynamically transcribes index into name using itos, so my suggestion in https://github.com/godotengine/godot/pull/110369#discussion_r2335739050 for this PR simply always prevents name from being changed automatically. Furthermore, I argue that inconsistent path behavior depend on whether it is number or not should be avoided, as it can cause confusion.

**Comment by vaner-org** [comment]
Pending further opinions, I do request that this PR not close #66336, because if the important part that indexes play in animation blending isn't exposed and made apparent to the user, a lot of unpredictable things can occur. I know it caused me a great deal of confusion before I understood it.

While blendpoint indexes remain a necessary evil that hold serious influence over animation blending, I don't think they should be swept under the rug.

File: editor/animation/animation_blend_space_2d_editor.h [hunk 4]
```diff
@@ -109,16 +111,30 @@ class AnimationNodeBlendSpace2DEditor : public AnimationTreeNodeEditorPlugin {
 	Vector2 drag_from;
 	Vector2 drag_ofs;
 
+	Vector<Rect2> text_rects;
+	int editing_point = -1;
+	LineEdit *inline_editor = nullptr;
+	float inline_editor_point_x;
```
Comment (AThousandShips) [inline editor/animation/animation_blend_space_2d_editor.h]: Needs a default

File: editor/animation/animation_blend_space_1d_editor.h [hunk 5]
```diff
@@ -104,14 +106,28 @@ class AnimationNodeBlendSpace1DEditor : public AnimationTreeNodeEditorPlugin {
 	Vector2 drag_from;
 	Vector2 drag_ofs;
 
+	Vector<Rect2> text_rects;
+	int editing_point = -1;
+	LineEdit *inline_editor = nullptr;
+	float inline_editor_point_x;
```
Comment (AThousandShips) [inline editor/animation/animation_blend_space_1d_editor.h]: Needs a default

File: editor/animation/animation_blend_space_2d_editor.cpp [hunk 6]
```diff
@@ -882,6 +1055,104 @@ void AnimationNodeBlendSpace2DEditor::_bind_methods() {
...
+
+	inline_editor = memnew(LineEdit);
+	blend_space_draw->add_child(inline_editor);
+
+	inline_editor->add_theme_color_override("font_color", get_theme_color(SNAME("accent_color"), EditorStringName(Editor)));
+	inline_editor->add_theme_color_override("font_selected_color", Color::named("white"));
+	inline_editor->add_theme_color_override("selection_color", get_theme_color(SNAME("accent_color"), EditorStringName(Editor)));
+	StyleBoxEmpty *empty_style = memnew(StyleBoxEmpty);
+	empty_style->set_content_margin_all(0);
+	inline_editor->add_theme_style_override("normal", empty_style);
```
Comment (AThousandShips) [inline editor/animation/animation_blend_space_2d_editor.cpp]:
```suggestion
	inline_editor->add_theme_style_override(CoreStringName(normal), empty_style);
```

File: editor/animation/animation_blend_space_2d_editor.cpp [hunk 7]
```diff
@@ -882,6 +1055,104 @@ void AnimationNodeBlendSpace2DEditor::_bind_methods() {
...
+		inline_editor->set_size(Vector2(editor_width, text_rect.size.y));
+
+		Size2 s = blend_space_draw->get_size();
+
+		float editor_x = inline_editor_point_x - editor_width / 2.0;
+		editor_x = CLAMP(editor_x, 0.0f, s.width - editor_width);
+		inline_editor->set_position(Vector2(editor_x, text_rect.position.y));
+	}
+
+	inline_editor->connect("text_changed", callable_mp(this, &AnimationNodeBlendSpace2DEditor::_inline_editor_text_changed));
```
Comment (AThousandShips) [inline editor/animation/animation_blend_space_2d_editor.cpp]:
```suggestion
	inline_editor->connect(SceneStringName(text_changed), callable_mp(this, &AnimationNodeBlendSpace2DEditor::_inline_editor_text_changed));
```

File: editor/animation/animation_blend_space_1d_editor.cpp [hunk 8]
```diff
@@ -652,13 +816,111 @@ void AnimationNodeBlendSpace1DEditor::edit(const Ref<AnimationNode> &p_node) {
...
+
+	inline_editor = memnew(LineEdit);
+	blend_space_draw->add_child(inline_editor);
+
+	inline_editor->add_theme_color_override("font_color", get_theme_color(SNAME("accent_color"), EditorStringName(Editor)));
+	inline_editor->add_theme_color_override("font_selected_color", Color::named("white"));
+	inline_editor->add_theme_color_override("selection_color", get_theme_color(SNAME("accent_color"), EditorStringName(Editor)));
+	StyleBoxEmpty *empty_style = memnew(StyleBoxEmpty);
+	empty_style->set_content_margin_all(0);
+	inline_editor->add_theme_style_override("normal", empty_style);
```
Comment (AThousandShips) [inline editor/animation/animation_blend_space_1d_editor.cpp]:
```suggestion
	inline_editor->add_theme_style_override(CoreStringName(normal), empty_style);
```

File: doc/classes/AnimationNodeBlendSpace1D.xml [hunk 9]
```diff
@@ -21,12 +21,26 @@
 				Adds a new point that represents a [param node] on the virtual axis at a given position set by [param pos]. You can insert it at a specific index using the [param at_index] argument. If you use the default value for [param at_index], the point is inserted at the end of the blend points array.
 			</description>
 		</method>
+		<method name="find_blend_point_by_name" qualifiers="const">
+			<return type="int" />
+			<param index="0" name="name" type="String" />
+			<description>
+				Returns the index of the blend point with the given [param name]. Returns -1 if no blend point with that name is found.
```
Comment (AThousandShips) [inline doc/classes/AnimationNodeBlendSpace1D.xml]:
```suggestion
				Returns the index of the blend point with the given [param name]. Returns [code]-1[/code] if no blend point with that name is found.
```

File: doc/classes/AnimationNodeBlendSpace2D.xml [hunk 10]
```diff
@@ -32,12 +32,26 @@
 				Creates a new triangle using three points [param x], [param y], and [param z]. Triangles can overlap. You can insert the triangle at a specific index using the [param at_index] argument. If you use the default value for [param at_index], the point is inserted at the end of the blend points array.
 			</description>
 		</method>
+		<method name="find_blend_point_by_name" qualifiers="const">
+			<return type="int" />
+			<param index="0" name="name" type="String" />
+			<description>
+				Returns the index of the blend point with the given [param name]. Returns -1 if no blend point with that name is found.
```
Comment (AThousandShips) [inline doc/classes/AnimationNodeBlendSpace2D.xml]:
```suggestion
				Returns the index of the blend point with the given [param name]. Returns [code]-1[/code] if no blend point with that name is found.
```

File: doc/classes/AnimationNodeBlendSpace1D.xml [hunk 11]
```diff
@@ -41,13 +55,36 @@
...
+			<description>
+				Swaps the blend points at indices [param from_index] and [param to_index], exchanging their positions and properties.
+			</description>
+		</method>
+		<method name="set_blend_point_name">
+			<return type="void" />
+			<param index="0" name="point" type="int" />
+			<param index="1" name="name" type="String" />
+			<description>
+				Sets the name of the blend point at index [param point]. If the name conflicts with existing points, a unique name will be generated automatically.
```
Comment (AThousandShips) [inline doc/classes/AnimationNodeBlendSpace1D.xml]:
```suggestion
				Sets the name of the blend point at index [param point]. If the name conflicts with an existing point, a unique name will be generated automatically.
```
I'd say, as there's only one possible since the names are unique

File: doc/classes/AnimationNodeBlendSpace2D.xml [hunk 12]
```diff
@@ -80,6 +101,22 @@
...
+			<description>
+				Swaps the blend points at indices [param from_index] and [param to_index], exchanging their positions and properties.
+			</description>
+		</method>
+		<method name="set_blend_point_name">
+			<return type="void" />
+			<param index="0" name="point" type="int" />
+			<param index="1" name="name" type="String" />
+			<description>
+				Sets the name of the blend point at index [param point]. If the name conflicts with existing points, a unique name will be generated automatically.
```
Comment (AThousandShips) [inline doc/classes/AnimationNodeBlendSpace2D.xml]:
```suggestion
				Sets the name of the blend point at index [param point]. If the name conflicts with an existing point, a unique name will be generated automatically.
```

File: editor/animation/animation_blend_space_2d_editor.h [hunk 13]
```diff
@@ -108,16 +111,28 @@ class AnimationNodeBlendSpace2DEditor : public AnimationTreeNodeEditorPlugin {
...
+	String _generate_unique_blend_point_name(Ref<AnimationNodeBlendSpace2D> p_blend_space, const String &p_base_name);
 
 	void _tool_switch(int p_tool);
 	void _update_edited_point_pos();
+	void _update_edited_point_name();
 	void _update_tool_erase();
 	void _erase_selected();
 	void _edit_point_pos(double);
+	void _edit_point_name(const String &p_name);
+	void _edit_point_index(double);
```
Comment (AThousandShips) [inline editor/animation/animation_blend_space_2d_editor.h]:
```suggestion
	void _edit_point_index(double p_index);
```

File: editor/animation/animation_blend_space_2d_editor.cpp [hunk 14]
```diff
@@ -859,6 +1046,78 @@ void AnimationNodeBlendSpace2DEditor::_bind_methods() {
...
+		return;
+	}
+
+	editing_point = p_point;
+	selected_point = p_point;
+
+	inline_editor = memnew(LineEdit);
+	blend_space_draw->add_child(inline_editor);
+
+	inline_editor->add_theme_color_override("font_color", get_theme_color(SNAME("accent_color"), EditorStringName(Editor)));
```
Comment (AThousandShips) [inline editor/animation/animation_blend_space_2d_editor.cpp]:
```suggestion
	inline_editor->add_theme_color_override(SceneStringName(font_color), get_theme_color(SNAME("accent_color"), EditorStringName(Editor)));
```

File: editor/animation/animation_blend_space_1d_editor.h [hunk 15]
```diff
@@ -103,14 +106,26 @@ class AnimationNodeBlendSpace1DEditor : public AnimationTreeNodeEditorPlugin {
...
+	String _generate_unique_blend_point_name(Ref<AnimationNodeBlendSpace1D> p_blend_space, const String &p_base_name);
 
 	void _tool_switch(int p_tool);
 	void _update_edited_point_pos();
+	void _update_edited_point_name();
 	void _update_tool_erase();
 	void _erase_selected();
 	void _edit_point_pos(double);
+	void _edit_point_name(const String &p_name);
+	void _edit_point_index(double);
```
Comment (AThousandShips) [inline editor/animation/animation_blend_space_1d_editor.h]:
```suggestion
	void _edit_point_index(double p_index);
```

File: editor/animation/animation_blend_space_1d_editor.cpp [hunk 16]
```diff
@@ -635,13 +811,85 @@ void AnimationNodeBlendSpace1DEditor::edit(const Ref<AnimationNode> &p_node) {
...
+		return;
+	}
+
+	editing_point = p_point;
+	selected_point = p_point;
+
+	inline_editor = memnew(LineEdit);
+	blend_space_draw->add_child(inline_editor);
+
+	inline_editor->add_theme_color_override("font_color", get_theme_color(SNAME("accent_color"), EditorStringName(Editor)));
```
Comment (AThousandShips) [inline editor/animation/animation_blend_space_1d_editor.cpp]:
```suggestion
	inline_editor->add_theme_color_override(SceneStringName(font_color), get_theme_color(SNAME("accent_color"), EditorStringName(Editor)));
```

File: editor/animation/animation_blend_space_1d_editor.cpp [hunk 17]
```diff
@@ -652,13 +816,111 @@ void AnimationNodeBlendSpace1DEditor::edit(const Ref<AnimationNode> &p_node) {
...
+		Size2 s = blend_space_draw->get_size();
+
+		float editor_x = inline_editor_point_x - editor_width / 2.0;
+		editor_x = CLAMP(editor_x, 0.0f, s.width - editor_width);
+		inline_editor->set_position(Vector2(editor_x, text_rect.position.y));
+	}
+
+	inline_editor->connect("text_changed", callable_mp(this, &AnimationNodeBlendSpace1DEditor::_inline_editor_text_changed));
+	inline_editor->connect("text_submitted", callable_mp(this, &AnimationNodeBlendSpace1DEditor::_finish_inline_edit_with_text));
+	inline_editor->connect("focus_exited", callable_mp(this, &AnimationNodeBlendSpace1DEditor::_finish_inline_edit));
```
Comment (AThousandShips) [inline editor/animation/animation_blend_space_1d_editor.cpp]:
```suggestion
	inline_editor->connect(SceneStringName(text_changed), callable_mp(this, &AnimationNodeBlendSpace1DEditor::_inline_editor_text_changed));
	inline_editor->connect(SceneStringName(text_submitted), callable_mp(this, &AnimationNodeBlendSpace1DEditor::_finish_inline_edit_with_text));
	inline_editor->connect(SceneStringName(focus_exited), callable_mp(this, &AnimationNodeBlendSpace1DEditor::_finish_inline_edit));
```

File: editor/animation/animation_blend_space_2d_editor.cpp [hunk 18]
```diff
@@ -882,6 +1055,104 @@ void AnimationNodeBlendSpace2DEditor::_bind_methods() {
...
+		Size2 s = blend_space_draw->get_size();
+
+		float editor_x = inline_editor_point_x - editor_width / 2.0;
+		editor_x = CLAMP(editor_x, 0.0f, s.width - editor_width);
+		inline_editor->set_position(Vector2(editor_x, text_rect.position.y));
+	}
+
+	inline_editor->connect("text_changed", callable_mp(this, &AnimationNodeBlendSpace2DEditor::_inline_editor_text_changed));
+	inline_editor->connect("text_submitted", callable_mp(this, &AnimationNodeBlendSpace2DEditor::_finish_inline_edit_with_text));
+	inline_editor->connect("focus_exited", callable_mp(this, &AnimationNodeBlendSpace2DEditor::_finish_inline_edit));
```
Comment (AThousandShips) [inline editor/animation/animation_blend_space_2d_editor.cpp]:
```suggestion
	inline_editor->connect(SceneStringName(text_changed), callable_mp(this, &AnimationNodeBlendSpace2DEditor::_inline_editor_text_changed));
	inline_editor->connect(SceneStringName(text_submitted), callable_mp(this, &AnimationNodeBlendSpace2DEditor::_finish_inline_edit_with_text));
	inline_editor->connect(SceneStringName(focus_exited), callable_mp(this, &AnimationNodeBlendSpace2DEditor::_finish_inline_edit));
```

**Comment by vaner-org** [comment]
In working to address the concerns of the animation team:

- I have removed the restriction on purely numeric names.
- I now convert index names to String names on first launch post this PR using `get_child_nodes`, to retain compatibility with current code paths, that users can then change into descriptors or clear to get the default creation naming scheme (of "BlendSpace1D", "StateMachine 2" etc.). If there's a better mechanism for upgrading, I'd appreciate some guidance.

As for my own concerns about this PR:
- I have removed the name editing box from the toolbar, after improvements to the inline editor's placement. This not only makes this PR more coherent with StateMachine and AnimationTree, but also helps the toolbar be less cluttered.
- To better address [#66336](https://github.com/godotengine/godot/issues/66336), when the index edit box in the toolbar has focus, all of the labels above the points show their indices rather than their names.
- Additionally, rolling the mousewheel over a blend point increments/decrements the index, while similarly revealing the indices of all points, a timed state that reverts back to names after 1.5 seconds. With this, [opening](https://github.com/godotengine/godot/pull/109839), moving, renaming and reordering the index of a blend point can all be done on the point itself rather than via the toolbar.

File: scene/animation/animation_blend_space_2d.cpp [hunk 19]
```diff
@@ -55,8 +55,11 @@ Variant AnimationNodeBlendSpace2D::get_parameter_default_value(const StringName
 
 void AnimationNodeBlendSpace2D::get_child_nodes(List<ChildNode> *r_child_nodes) {
 	for (int i = 0; i < blend_points_used; i++) {
+		if (blend_points[i].name.is_empty()) {
+			blend_points[i].name = itos(i);
+		}
```
Comment (TokageItLab) [inline scene/animation/animation_blend_space_2d.cpp]:
```suggestion
```
As I mentioned above, cases where the name is empty should not be allowed. So thin fallback is not needed. Same is applied to BlendSpace1D.

File: scene/animation/animation_blend_space_2d.cpp [hunk 20]
```diff
@@ -83,6 +86,7 @@ void AnimationNodeBlendSpace2D::add_blend_point(const Ref<AnimationRootNode> &p_
 	}
 	blend_points[p_at_index].node = p_node;
 	blend_points[p_at_index].position = p_position;
+	blend_points[p_at_index].name = String();
```
Comment (TokageItLab) [inline scene/animation/animation_blend_space_2d.cpp]:
```suggestion
	blend_points[p_at_index].name = String();
	StringName n = _get_default_name_from_class(p_node);
	blend_points[p_at_index].name = _get_safe_name(n); // If the space has same name, modify name to "StateMachine_2" to avoid conflict.
```
Instead of an empty name, a default name will be defined, similar to other resources.

Or add argument to set the name and implement function to get default name in AnimationNodeBlendSpace2DEditor.
```cpp
void AnimationNodeBlendSpace2D::add_blend_point(const Ref<AnimationRootNode> &p_node, const Vector2 &p_position, int p_at_index, StringName &p_name) {
	ERR_FAIL_COND(blend_points_used >= MAX_BLEND_POINTS);
	ERR_FAIL_COND(p_node.is_null());
	ERR_FAIL_COND(p_name.is_empty() || has_point(p_name)); // You need to ensure safe name by AnimationNodeBlendSpace2DEditor side.
	ERR_FAIL_COND(p_at_index < -1 || p_at_index > blend_points_used);
```
```cpp
void AnimationNodeBlendSpace2DEditor::_add_animation_type(int p_index) {
	Ref<AnimationNodeAnimation> anim;
	anim.instantiate();

	anim->set_animation(animations_to_add[p_index]);

	updating = true;
	EditorUndoRedoManager *undo_redo = EditorUndoRedoManager::get_singleton();
	undo_redo->create_action(TTR("Add Animation Point"));
	undo_redo->add_do_method(blend_space.ptr(), "add_blend_point", anim, add_point_pos, _get_safe_name(blend_space, _get_default_name_by_class(anim)));
	undo_redo->add_undo_method(blend_space.ptr(), "remove_blend_point", blend_space->get_blend_point_count());
```
The latter is probably preferred due to the clear separation of roles between the Editor and GameObject, also it's more consistent with other classes.

However, since the latter approach breaks compatibility, the getting safe name feature should be added to compatible methods with creating the file `animation_blend_space_2d(1d).compat.inc`.

For example:

**animation_blend_space_2d.compat.inc**
```cpp
void AnimationNodeBlendSpace2D::add_blend_point_compat_xxxxxx(const Ref<AnimationRootNode> &p_node, const Vector2 &p_position, int p_at_index) {
	StringName n = p_node.get_class_name(); // Or, is itos(p_at_index) better to keep old behavior?
	while (has_point(n)) {
		// inclement
	}
	add_blend_point(p_node, p_position, p_at_index, n);
}
```

File: scene/animation/animation_blend_space_2d.cpp [hunk 21]
```diff
@@ -127,6 +131,51 @@ Ref<AnimationRootNode> AnimationNodeBlendSpace2D::get_blend_point_node(int p_poi
 	return blend_points[p_point].node;
 }
 
+void AnimationNodeBlendSpace2D::set_blend_point_name(int p_point, const String &p_name) {
+	ERR_FAIL_INDEX(p_point, blend_points_used);
+	ERR_FAIL_COND(p_name.contains_char('.') || p_name.contains_char('/'));
```
Comment (TokageItLab) [inline scene/animation/animation_blend_space_2d.cpp]:
```suggestion
	ERR_FAIL_COND(p_name.is_empty() || p_name.contains_char('.') || p_name.contains_char('/') || has_point(p_name));
```

File: scene/animation/animation_blend_space_2d.cpp [hunk 22]
```diff
@@ -127,6 +131,51 @@ Ref<AnimationRootNode> AnimationNodeBlendSpace2D::get_blend_point_node(int p_poi
...
+
+	if (final_name.is_empty()) {
+		Ref<AnimationNode> node = blend_points[p_point].node;
+		if (node.is_valid()) {
+			base_name = node->get_class().replace_first("AnimationNode", "");
+		} else {
+			base_name = "Point";
+		}
+		final_name = base_name;
+	}
```
Comment (TokageItLab) [inline scene/animation/animation_blend_space_2d.cpp]:
```suggestion
```
Empty name should be just prevented above line.

File: scene/animation/animation_blend_space_2d.cpp [hunk 23]
```diff
@@ -127,6 +131,51 @@ Ref<AnimationRootNode> AnimationNodeBlendSpace2D::get_blend_point_node(int p_poi
...
+	while (find_blend_point_by_name(final_name) != -1 && find_blend_point_by_name(final_name) != p_point) {
+		base++;
+		final_name = base_name + " " + itos(base);
+	}
+
+	String old_name = blend_points[p_point].name;
+	blend_points[p_point].name = final_name;
+	if (old_name != final_name) {
+		emit_signal(SNAME("animation_node_renamed"), get_instance_id(), old_name, final_name);
+	}
```
Comment (TokageItLab) [inline scene/animation/animation_blend_space_2d.cpp]: This process to avoid duplicate names should be refactored into a function and called by `add_point` and `set_blend_point_name` as mentioned above https://github.com/godotengine/godot/pull/110369#discussion_r2874215156 (and they should be implemented in AnimationNodeBlendSpace2DEditor if we choose later approach of https://github.com/godotengine/godot/pull/110369#discussion_r2874215156).

**Review by TokageItLab — CHANGES_REQUESTED** [review]
As I mentioned above, there is no need to allow empty names and fall back. The point of the BlendSpece in old projects should be that they have simple numerical names.

File: scene/animation/animation_blend_space_2d.cpp (hunk 19 above)
Comment (vaner-org) [reply scene/animation/animation_blend_space_2d.cpp]: I understand, what is the optimal place to convert the index to name during the first deserialization after launching a project with this commit? Is `_add_blend_point` suitable?

```
void AnimationNodeBlendSpace2D::_add_blend_point(int p_index, const Ref<AnimationRootNode> &p_node) {
	if (p_index == blend_points_used) {
		String pre_existing_name = blend_points[p_index].name;
		if (pre_existing_name.is_empty()) {
			pre_existing_name = itos(p_index);
		}
		add_blend_point(p_node, Vector2(), pre_existing_name);
	} else {
		set_blend_point_node(p_index, p_node);
	}
}
```

Comment (TokageItLab) [reply scene/animation/animation_blend_space_2d.cpp]: Deserialization is performed in setters, so migration from older projects needs to be handled there with `#ifndef DISABLE_DEPRECATED` block. You can refer to compatibility code implemented in AnimationMixer or other some classes' `_set()` method as the reference.

Comment (vaner-org) [reply scene/animation/animation_blend_space_2d.cpp]: I've refactored `_validate_property()` and `_add_blend_point()` into `set()`, `get()` and `get_property_list()` for both BlendSpace classes. Please check the last commit. Is this what was to be done?

Comment (TokageItLab) [reply scene/animation/animation_blend_space_2d.cpp]: The direction should be correct as long as looking code.

- When an old project is opened, the parameter path remains the same as before

image

- When a new point is added, a default name based on the class name is assigned
- Assigning a new empty name is not permitted

If above points have been implemented, there should be no problem. I will test it when I have time.

By the way, if we modify the arguments of an existing bound method, we need to add a compatibility method to the compat file to pass CI. Please refer to other classes' `.compat.inc` file.

Comment (vaner-org) [reply scene/animation/animation_blend_space_2d.cpp]: Yes, all three are functioning correctly. Is there an external need for `_get_triangles()` and `_set_triangles()`? Otherwise I can pull those into the new functions and remove `_validate_property()` too.

I'll do the `compat.inc` next.

Comment (TokageItLab) [reply scene/animation/animation_blend_space_2d.cpp]: You need to add `void _add_blend_point_bind_compat_110369(const Ref<AnimationRootNode> &p_node, float p_position, int p_at_index);` for both 1D and 2D, and implement make default name implementation like https://github.com/godotengine/godot/pull/110369#discussion_r2874215156. If you want to maintain the old behavior, implementing names using `itos()` might be okay. The compat method exists for compatibility, so doing it there should be fine.

**Comment by vaner-org** [comment]
A few questions: 
- Failing checks against the extension API. The name must be added as a non-optional member, so has to be before index in `add_blend_point()`. How should I proceed?
- Is there an external need for `_get_triangles()` and `_set_triangles()` in BlendSpace2D? Otherwise I can pull those into the `set`, `get()` and `get_property_list()` and remove `_validate_property()` too.
- Where should I document the new functionality of rolling the mousewheel to change index, and double clicking the text to change the name?

File: scene/animation/animation_blend_space_1d.h [hunk 24]
```diff
@@ -72,28 +74,37 @@ class AnimationNodeBlendSpace1D : public AnimationRootNode {
...
 
-	void _validate_property(PropertyInfo &p_property) const;
 	static void _bind_methods();
 
 	virtual void _tree_changed() override;
 	virtual void _animation_node_renamed(const ObjectID &p_oid, const String &p_old_name, const String &p_new_name) override;
 	virtual void _animation_node_removed(const ObjectID &p_oid, const StringName &p_node) override;
 
+#ifndef DISABLE_DEPRECATED
+	void _add_blend_point_bind_compat_110369(const Ref<AnimationRootNode> &p_node, float p_position, int p_at_index);
```
Comment (TokageItLab) [inline scene/animation/animation_blend_space_1d.h]:
```suggestion
	void _add_blend_point_bind_compat_110369(const Ref<AnimationRootNode> &p_node, float p_position, int p_at_index = -1);
```

File: scene/animation/animation_blend_space_2d.h [hunk 25]
```diff
@@ -92,20 +95,30 @@ class AnimationNodeBlendSpace2D : public AnimationRootNode {
 	virtual void _animation_node_renamed(const ObjectID &p_oid, const String &p_old_name, const String &p_new_name) override;
 	virtual void _animation_node_removed(const ObjectID &p_oid, const StringName &p_node) override;
 
+#ifndef DISABLE_DEPRECATED
+	void _add_blend_point_bind_compat_110369(const Ref<AnimationRootNode> &p_node, const Vector2 &p_position, int p_at_index);
```
Comment (TokageItLab) [inline scene/animation/animation_blend_space_2d.h]:
```suggestion
	void _add_blend_point_bind_compat_110369(const Ref<AnimationRootNode> &p_node, const Vector2 &p_position, int p_at_index = -1);
```

**Review by TokageItLab — COMMENTED** [review]
The old code contained two methods: `add_blend_point` and `_add_blend_point`. `add_blend_point` has been modified this time, and a compatibility method has been registered. `_add_blend_point` is being removed because it is an internal method for array serialization and is not publicly exposed due to the leading underscore. Therefore, it should not actually affect compatibility. So you need to add an exclusion for this error under `godot/misc/extension_api_validation/4.6-stable/`.

> Is there an external need for _get_triangles() and _set_triangles() in BlendSpace2D?

If it's not needed immediately, it can be done in a later PR.

> Where should I document the new functionality of rolling the mousewheel to change index, and double clicking the text to change the name?

I think it's better to write it in a tooltip rather than the documentation. FYI, the editor documentation should be sent to https://github.com/godotengine/godot-docs.

File: scene/animation/animation_blend_space_2d.cpp [hunk 26]
```diff
@@ -59,16 +59,30 @@ Variant AnimationNodeBlendSpace2D::get_parameter_default_value(const StringName
...
+#ifndef DISABLE_DEPRECATED
+	StringName safe_name = p_name;
+	if (safe_name == StringName()) {
+		int n = p_at_index == -1 ? blend_points_used : p_at_index;
+		while (find_blend_point_by_name(itos(n)) != -1) {
+			n++;
+		}
+		safe_name = StringName(itos(n));
+		WARN_PRINT_ED("AnimationNodeBlendSpace2D::add_blend_point: No name provided, using index \"" + itos(n) + "\" as reference. In the future, empty names will be deprecated, so explicitly passing a name is recommended.");
+	}
```
Comment (TokageItLab) [inline scene/animation/animation_blend_space_2d.cpp:77]:
```suggestion
#ifndef DISABLE_DEPRECATED
	_add_blend_point_bind_compat_110369(p_node, p_position, p_at_index);
	WARN_PRINT_ED("AnimationNodeBlendSpace2D::add_blend_point: No name provided, using safe index as reference. In the future, empty names will be deprecated, so explicitly passing a name is recommended.");
	return;		
```
I think you can reuse compat method although warning can't shown the safe name result.

File: doc/classes/AnimationNodeBlendSpace1D.xml [hunk 27]
```diff
@@ -16,9 +16,17 @@
 			<return type="void" />
 			<param index="0" name="node" type="AnimationRootNode" />
 			<param index="1" name="pos" type="float" />
-			<param index="2" name="at_index" type="int" default="-1" />
+			<param index="2" name="name" type="StringName" />
+			<param index="3" name="at_index" type="int" default="-1" />
 			<description>
-				Adds a new point that represents a [param node] on the virtual axis at a given position set by [param pos]. You can insert it at a specific index using the [param at_index] argument. If you use the default value for [param at_index], the point is inserted at the end of the blend points array.
+				Adds a new point with [param name] that represents a [param node] on the virtual axis at a given position set by [param pos]. You can insert it at a specific index using the [param at_index] argument. If you use the default value for [param at_index], the point is inserted at the end of the blend points array.
```
Comment (TokageItLab) [inline doc/classes/AnimationNodeBlendSpace1D.xml:22]: It would be advisable to include in the documentation that empty name will be deprecated in the future with `[b]Note:[/b]`.

File: scene/animation/animation_blend_space_1d.cpp [hunk 28]
```diff
@@ -129,18 +121,23 @@ void AnimationNodeBlendSpace1D::_bind_methods() {
...
+void AnimationNodeBlendSpace1D::add_blend_point(const Ref<AnimationRootNode> &p_node, float p_position, int p_at_index, const StringName &p_name) {
 	ERR_FAIL_COND(blend_points_used >= MAX_BLEND_POINTS);
 	ERR_FAIL_COND(p_node.is_null());
-
 	ERR_FAIL_COND(p_at_index < -1 || p_at_index > blend_points_used);
-
+#ifndef DISABLE_DEPRECATED
+	_add_blend_point_bind_compat_110369(p_node, p_position, p_at_index);
+	WARN_PRINT_ED("AnimationNodeBlendSpace1D::add_blend_point: No name provided, using safe index as reference. In the future, empty names will be deprecated, so explicitly passing a name is recommended.");
+	return;
```
Comment (TokageItLab) [inline scene/animation/animation_blend_space_1d.cpp]:
```suggestion
#ifndef DISABLE_DEPRECATED
	if (p_name == StringName()) {
		_add_blend_point_bind_compat_110369(p_node, p_position, p_at_index);
		WARN_PRINT_ED("AnimationNodeBlendSpace1D::add_blend_point: No name provided, using safe index as reference. In the future, empty names will be deprecated, so explicitly passing a name is recommended.");
		return;
	}
```

Comment (vaner-org) [reply scene/animation/animation_blend_space_1d.cpp]: Whoops, sorry.

Comment (TokageItLab) [reply scene/animation/animation_blend_space_1d.cpp]: NP, my suggestion was not entirely accurate. While it could also be written as follows, when using FAIL_COND, it's better to have an if statement within the block.
```cpp
if (p_name == StringName()) {
#ifndef DISABLE_DEPRECATED
  WARN_PRINT();
#else
  ERR_PRINT();
#endif
  return;
}
```

Comment (vaner-org) [reply scene/animation/animation_blend_space_1d.cpp]: Should I do it this way instead?

Comment (TokageItLab) [reply scene/animation/animation_blend_space_1d.cpp]: I think it's fine as is.

**Comment by TokageItLab** [comment]
I think now this PR code is fine, I will test and re-review in Animation meeting this weekend. Can you squash commits into one?

**Review by TokageItLab — APPROVED** [review]
I've confirmed that it's working as expected.

Image

I'll add the `brakes compat` label just in case, as it involves a minor breaking change; As long as `disable_deprecated` is `false`, it will issue a warning but won't break the project.

I'll confirm the final agreement later in the animation meeting.

File: editor/animation/animation_blend_space_2d_editor.cpp [hunk 29]
```diff
@@ -811,6 +927,71 @@ void AnimationNodeBlendSpace2DEditor::_edit_point_pos(double) {
...
+	undo_redo->add_do_method(blend_space.ptr(), "set_blend_point_name", selected_point, safe_name);
+	undo_redo->add_undo_method(blend_space.ptr(), "set_blend_point_name", selected_point, old_name);
+	undo_redo->add_do_method(this, "_update_space");
+	undo_redo->add_undo_method(this, "_update_space");
+	undo_redo->add_do_method(this, "_update_edited_point_name");
+	undo_redo->add_undo_method(this, "_update_edited_point_name");
+	undo_redo->commit_action();
+	updating = false;
+
+	blend_space_draw->queue_redraw();
```
Comment (TokageItLab) [inline editor/animation/animation_blend_space_2d_editor.cpp:967]: `queue_redraw()` seems don't recalc triangles immediately, so I think it needs to have call recalc triangle func and connect it with changed index signal with BlendSpace resource.

https://github.com/user-attachments/assets/2ded0bb1-0333-4f3a-96bd-eba5302fa466

**Review by lyuma — COMMENTED** [review]
We discussed this at the animation meeting, but it was difficult to find consensus.

BlendPoint name is StringName, not String. The APIs to `set_blend_point_name` and `get_blend_point_name` and `find_blend_point_by_name` should take StringName.

Tokage notes: The compatibility impact is when the number of points is changed dynamically at runtime, so people who need this can use `get_blend_point_name`

@fire commented during the meeting that this is not something we need, and changing it from an integer to string and having an editable title might be a bad idea.

I and fire agree it may be helpful to have the index number visible at least.

File: editor/animation/animation_blend_space_2d_editor.cpp (hunk 29 above)
Comment (vaner-org) [reply editor/animation/animation_blend_space_2d_editor.cpp:967]: In `reorder_blend_point`, added `_queue_auto_triangles()` and `emit_signal(SNAME("triangles_updated"))`, seems to fix it. Is that enough?

File: scene/animation/animation_blend_space_2d.cpp (hunk 19 above)
Comment (vaner-org) [reply scene/animation/animation_blend_space_2d.cpp]: What purpose do these serve? Is it safe to strip the for loop?
```
AnimationNodeBlendSpace2D::AnimationNodeBlendSpace2D() {
	for (int i = 0; i < MAX_BLEND_POINTS; i++) {
		blend_points[i].name = String();
	}
}

AnimationNodeBlendSpace2D::~AnimationNodeBlendSpace2D() {
}
```

File: scene/animation/animation_blend_space_1d.cpp [hunk 30]
```diff
@@ -426,9 +520,6 @@ String AnimationNodeBlendSpace1D::get_caption() const {
 }
 
 AnimationNodeBlendSpace1D::AnimationNodeBlendSpace1D() {
-	for (int i = 0; i < MAX_BLEND_POINTS; i++) {
-		blend_points[i].name = itos(i);
```
Comment (vaner-org) [inline scene/animation/animation_blend_space_1d.cpp:430]: @TokageItLab is this responsible for #117490?

Comment (TokageItLab) [reply scene/animation/animation_blend_space_1d.cpp:430]: That is indeed the cause. I’ve already sent a PR https://github.com/godotengine/godot/pull/117508, but in theory, that does the same thing as restoring this line, but it can be done outside the constructor as in #117508 since it reduce instancing cost.
