### PR TITLE
Prevent save confirmation dialog from trying to parent to itself

### LINKED ISSUE #102418: Attempt to close Godot with two or more scenes with changes open can lock the engine
### Tested versions

- Reproducible in latest master (eee39f004)
- Not reproducible in 4.4 beta 2

### System information

Godot v4.4.beta (eee39f004) - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 580 2048SP (Advanced Micro Devices, Inc.; 31.0.21921.1000) - AMD Ryzen 5 3600 6-Core Processor (12 threads)

### Issue description

When you have two or more scenes open with unsaved changes and attempt to close the editor, selecting `Don't save` lock the engine from be closed or restarted. 

After select `Don't save` these three errors will appear:

```
ERROR: Can't add child '@ConfirmationDialog@8238' to itself.
   at: (C:\Users\Matheus\Downloads\Godot Source\scene/main/node.cpp:1652)
ERROR: Condition "!windows.has(p_window)" is true. Returning: -1
   at: DisplayServerWindows::window_get_current_screen (platform\windows\display_server_windows.cpp:1959)
ERROR: Condition "!is_inside_tree()" is true.
   at: Viewport::_push_unhandled_input_internal (C:\Users\Matheus\Downloads\Godot Source\scene/main/viewport.cpp:3338)
```

<br>

And any new attempt to close/restart the editor or close a scene will throw this error:

```
ERROR: Condition "!is_inside_tree()" is true.
   at: Window::popup_centered (C:\Users\Matheus\Downloads\Godot Source\scene/main/window.cpp:1794)
```

https://github.com/user-attachments/assets/7c028dd3-1eef-4439-94e5-a8e0f11d695c

<br>

Bisecting points to #102070 as the culprit

Image

CC @ryevdokimov

### Steps to reproduce

1. Open two scenes at the same time
2. Do any modification in both scenes but don't save
3. Try to close/restart the editor
4. In the confirmation window, choice `Don't save`

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by ryevdokimov**
Fixes: https://github.com/godotengine/godot/issues/102418

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -5734,7 +5734,9 @@ void EditorNode::_cancel_close_scene_tab() {
 }
 
 void EditorNode::_prepare_save_confirmation_popup() {
-	save_confirmation->reparent(get_last_exclusive_window());
+	if (save_confirmation->get_window() != get_last_exclusive_window()) {
```
Comment (Ivorforce) [inline editor/editor_node.cpp:5737]: I'd argue that a window should never reparent to itself. Wouldnt the sanity check make more sense in `reparent`'s implementation?

Comment (ryevdokimov) [reply editor/editor_node.cpp:5737]: Nodes in general shouldn't be able to parent to themselves, but they already do have a check via an `ERR_FAIL_COND_MSG`, that is how the bug was easily caught in the attached issue. This code is to prevent the error from occurring.

**Review by akien-mga — APPROVED** [review]

File: editor/editor_node.cpp (hunk 1 above)
Comment (ryevdokimov) [reply editor/editor_node.cpp:5737]: Though since you mention it, I do think that there is value to explicitly throwing an error on reparent so it's more obvious the origin of the error. I can make a separate PR.

**Comment by Repiteo** [comment]
Thanks!
