### PR TITLE
Don't open editor window when using --export or --doctool

### LINKED ISSUE #43752: Command line exporting needlessly opens the editor window
**Godot version:**
v3.2.3.stable.official

**OS/device including version:**
macOS Catalina

**Issue description:**
When exporting via the command line (running with the `--export` option), Godot opens the editor window for some reason, and then closes it a few seconds later after the export is done.  I want to be able to automate exporting (which _is_ is the purpose of command line functionality, right?), and having a random window pop up and cover whatever else I'm doing is a problem.  On Windows, I think this could be worked around with the `--no-window` option, but as [mentioned in the docs](https://docs.godotengine.org/en/stable/getting_started/editor/command_line_tutorial.html), this doesn't work on other platforms.

**Steps to reproduce:**
Export any project from the command line.

**Minimal reproduction project:**
I wanted to include a minimal reproduction project, but even the editor binary and macOS export template individually are over the 10MB limit, and without them it's just a blank project with an export preset.

### PR DESCRIPTION
**Pull request by name-here**
Fixes #43752

Adds `--no-window` when using `--export`, so the editor window doesn't suddenly pop up and then vanish when exporting from the command line.  ~~Should probably do this for `--doctool` too (and maybe others?), but I couldn't figure out how to make it work consistently.~~  I think it should work for `--doctool` and `--gdnative-generate-json-api` now, too.

This is against `3.2` instead of master because, as mentioned in the discussion on #43752, `--no-window` hasn't been implemented in `master` yet.

### CODE REVIEW

File: main/main.cpp [hunk 1]
```diff
@@ -715,6 +715,7 @@ Error Main::setup(const char *execpath, int argc, char *argv[], bool p_second_ph
 
 			editor = true;
 			main_args.push_back(I->get());
+			args.push_back("--no-window");
```
Comment (akien-mga) [inline main/main.cpp:718]: It would be better to enable no window mode (it's one line of code) instead of modifying arguments.

**Comment by name-here** [comment]
I figured out how to do the same with `--doctool` (not showing the window), but I can't get `--doctool` to work at all, even in the official `3.2` branch.

**Comment by Calinou** [comment]
Would it be worth adding automatic no-window mode for `--gdnative-generate-json-api` as well? It could help work around https://github.com/godotengine/godot/issues/43953.

**Comment by name-here** [comment]
> Would it be worth adding automatic no-window mode for `--gdnative-generate-json-api` as well? It could help work around #43953 for those working with GDNative.

Done.  Any other command line options that should have it?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Could you do the relevant changes for the `master` branch too?

**Comment by akien-mga** [comment]
This broke `doctool` for some reason. Fixed with 0c7a9bd.

**Comment by name-here** [comment]
> Could you do the relevant changes for the `master` branch too?

I just tested, and `--no-window` still doesn't seem work in `master`.  Should I make the PR anyways, so when `--no-window` is implemented, the editor will already have these improvements?  Or should I wait until `--no-window` is made functional?

**Comment by Calinou** [comment]
> I just tested, and `--no-window` still doesn't seem work in `master`.

See https://github.com/godotengine/godot-proposals/issues/991. I'm not sure if this will be implemented as a `--no-window` switch or an entirely different switch such as `--display-server`.

**Comment by name-here** [comment]
When that's implemented, I'll make a PR for `master` that uses whatever flag it adds instead of `--no-window`.  For now, I'm not sure how helpful it would be to make a PR with options that don't exist yet, especially since it would only add ~10 lines.

**Comment by akien-mga** [comment]
This also broke the `--export` mode (#44403), so I'll revert this for now (#44428).
