### PR TITLE
Remove `NOTIFICATION_ENTER_TREE` when paired with `NOTIFICATION_THEME_CHANGED`

### LINKED ISSUE #50743: `NOTIFICATION_THEME_CHANGED` is getting called when it shouldn't
### Godot version

883bb2f4f657fa38da07efc1f04f35b5c8923120

### System information

Windows 10

### Issue description
<details>
<summary>
See https://chat.godotengine.org/channel/devel?msg=J4SjAHxFmwZ7NHYqQ
</summary>

image
</details>

When opening a project in 3.x, `NOTIFICATION_THEME_CHANGED` consistently gets called 8 times (or at least on the `FileSystemDock` and `ProjectExportDialog` which were what I tested. In master it's only 3 times).

When running the project manager in 3.x, `NOTIFICATION_THEME_CHANGED` is only called 3 times in `EditorAbout` (although it doesn't get called at all in master because (maybe by mistake?) `NOTIFICATION_THEME_CHANGED` [was removed from `EditorAbout` in master](https://github.com/godotengine/godot/commit/4758057f205a7d2e0d2db2c034705b7afcdf310f#diff-35a6b6fb0e84d2469de9ad1bd4b47405b9e1eb58a74b2529ae404c1f922c649dR53)).

 `NOTIFICATION_THEME_CHANGED` is also called when/right before an object is destroyed it seems (or at least when closing the editor.

In master `NOTIFICATION_THEME_CHANGED` is only called three times.
### Steps to reproduce

Insert a breakpoint in `NOTIFICATION_THEME_CHANGED`

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by AaronRecord**
Fixes https://github.com/godotengine/godot/issues/50743

Since https://github.com/godotengine/godot/pull/62845 this is unnecessary as `NOTIFICATION_THEME_CHANGED` is always called when a control/window node enters the tree.

regex: `(case (NOTIFICATION_ENTER_TREE|NOTIFICATION_THEME_CHANGED):\n*\t*){2,}`

Including https://github.com/godotengine/godot/pull/62845 this speeds up editor start time opening an empty project [by about 7%](https://github.com/godotengine/godot/pull/62846#issuecomment-1204710636)

### CODE REVIEW

**Comment by AaronRecord** [comment]
Okay, it turns out that `NOTIFICATION_THEME_CHANGED` isn't unconditionally called in `NOTIFICATION_ENTER_TREE`, although https://github.com/godotengine/godot/pull/62845 would fix that.

**Comment by AaronRecord** [comment]
[Hyperfine ](https://github.com/sharkdp/hyperfine) comparison of opening an empty project in the editor with this commit vs ad9a8e70f499267251daaa4cb51f3c2545d4ad4e using CI builds:
```
Summary  'C:\Users\aaron\Downloads\theme-changes\godot.windows.opt.tools.64.exe --editor --path C:\Users\aaron\Projects\Godot\EmptyProject4.0 --quit' ran
    1.03 ± 0.04 times faster than 'C:\Users\aaron\Downloads\master\godot.windows.opt.tools.64.exe --editor --path C:\Users\aaron\Projects\Godot\EmptyProject4.0 --quit'
```

**Comment by YuriSizov** [comment]
Can you please rebase this now that https://github.com/godotengine/godot/pull/63318 is merged?

**Comment by AaronRecord** [comment]
Marking as draft until https://github.com/godotengine/godot/pull/62845 is merged so I don't have to keep rebasing it

File: editor/editor_autoload_settings.cpp [hunk 1]
```diff
@@ -58,7 +58,6 @@ void EditorAutoloadSettings::_notification(int p_what) {
 					get_tree()->get_root()->call_deferred(SNAME("add_child"), info.node);
 				}
 			}
-			browse_button->set_icon(get_theme_icon(SNAME("Folder"), SNAME("EditorIcons")));
```
Comment (AaronRecord) [inline editor/editor_autoload_settings.cpp:61]: it's already set in `NOTIFICATION_THEME_CHANGED` (look below)

**Comment by AaronRecord** [comment]
Rebased, it seems new changes from https://github.com/godotengine/godot/pull/62845 have caused the one test case that was failing before to fail again, my guess is that it has something to do with `NOTIFICATION_THEME_CHANGED` being deferred. I'll try looking into the failing test case again and see if I can solve it properly.

File: tests/scene/test_code_edit.h [hunk 2]
```diff
@@ -2943,6 +2943,11 @@ TEST_CASE("[SceneTree][CodeEdit] completion") {
 			code_edit->set_code_completion_enabled(true);
 			CHECK(code_edit->get_code_completion_selected_index() == -1);
 
+			// `NOTIFICATION_THEME_CHANGED` is called deferred from `NOTIFICATION_ENTER_TREE`,
+			// but it won't have been called yet here, and `update_code_completion_options` requires access
+			// to the theme's font size, so we need to force an update here.
+			code_edit->notification(Control::NOTIFICATION_THEME_CHANGED);
```
Comment (AaronRecord) [inline tests/scene/test_code_edit.h:2949]: So https://github.com/godotengine/godot/blob/29ba1fc1be653858a936593fc373d23a1ab548da/scene/gui/code_edit.cpp#L2748 seems to depend on having `font` initialized, but currently with https://github.com/godotengine/godot/pull/62845 theme items aren't initialized *immediately* when entering the tree, instead the call is deferred because `add_child_notify` is called after `NOTIFICATION_ENTER_TREE`, but `NOTIFICATION_THEME_CHANGED` shouldn't be called until after `add_child_notify` because `add_child_notify` assigns what Control/Window the added child should inherit theme items from.

@Paulb23 You're the expert on `CodeEdit`, if you had a second to give your thoughts on this it'd be greatly appreciated 🙂

**Comment by AaronRecord** [comment]
Did an updated benchmark with the new changes from https://github.com/godotengine/godot/pull/62845, now editor startup time on an empty project is now about 7% faster:
```py
C:\Users\aaron>hyperfine -iw2 "C:\Users\aaron\Downloads\theme-changes\godot.windows.opt.tools.64.exe --editor --path C:\Users\aaron\Projects\Godot\EmptyProject4.0 --quit" "C:\Users\aaron\Downloads\master\godot.windows.opt.tools.64.exe --editor --path C:\Users\aaron\Projects\Godot\EmptyProject4.0 --quit"
Benchmark 1: C:\Users\aaron\Downloads\theme-changes\godot.windows.opt.tools.64.exe --editor --path C:\Users\aaron\Projects\Godot\EmptyProject4.0 --quit
  Time (mean ± σ):      3.875 s ±  0.012 s    [User: 0.004 s, System: 0.003 s]
  Range (min … max):    3.857 s …  3.898 s    10 runs

  Warning: Ignoring non-zero exit code.

Benchmark 2: C:\Users\aaron\Downloads\master\godot.windows.opt.tools.64.exe --editor --path C:\Users\aaron\Projects\Godot\EmptyProject4.0 --quit
  Time (mean ± σ):      4.149 s ±  0.095 s    [User: 0.001 s, System: 0.006 s]
  Range (min … max):    3.878 s …  4.188 s    10 runs

  Warning: Ignoring non-zero exit code.
  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.

Summary
  'C:\Users\aaron\Downloads\theme-changes\godot.windows.opt.tools.64.exe --editor --path C:\Users\aaron\Projects\Godot\EmptyProject4.0 --quit' ran
    1.07 ± 0.02 times faster than 'C:\Users\aaron\Downloads\master\godot.windows.opt.tools.64.exe --editor --path C:\Users\aaron\Projects\Godot\EmptyProject4.0 --quit'
```

File: tests/scene/test_code_edit.h (hunk 2 above)
Comment (Paulb23) [reply tests/scene/test_code_edit.h:2949]: If this is only happening in the unit tests, something like this is kind of expected as it's not really processing anything normally. Instead the message queue has to be forced with `MessageQueue::get_singleton()->flush();` calls. Most of these calls however are hidden in the test macros, so in this case manually calling the notifications is okay, or some kind of macro to hide it would also work.

**Comment by AaronRecord** [comment]
image

**Comment by akien-mga** [comment]
```
editor/plugins/script_editor_plugin.cpp: In member function 'void ScriptEditorQuickOpen::_notification(int)':
editor/plugins/script_editor_plugin.cpp:354:40: error: this statement may fall through [-Werror=implicit-fallthrough=]
  354 |    search_box->set_clear_button_enabled(true);
      |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
editor/plugins/script_editor_plugin.cpp:357:3: note: here
  357 |   case NOTIFICATION_THEME_CHANGED: {
      |   ^~~~
```

File: editor/animation_bezier_editor.cpp [hunk 3]
```diff
@@ -216,8 +216,7 @@ void AnimationBezierTrackEdit::_notification(int p_what) {
 
 		case NOTIFICATION_ENTER_TREE: {
 			panner->setup((ViewPanner::ControlScheme)EDITOR_GET("editors/panning/animation_editors_panning_scheme").operator int(), ED_GET_SHORTCUT("canvas_item_editor/pan_view"), bool(EditorSettings::get_singleton()->get("editors/panning/simple_panning")));
-			[[fallthrough]];
-		}
+		} break;
```
Comment (akien-mga) [inline editor/animation_bezier_editor.cpp:219]: Nitpick, there should be a separation line between `case`s (unless it's a fallthrough) for readability, as they're often quite big.

File: editor/connections_dialog.cpp [hunk 4]
```diff
@@ -230,9 +230,7 @@ void ConnectDialog::_notification(int p_what) {
 	switch (p_what) {
 		case NOTIFICATION_ENTER_TREE: {
 			bind_editor->edit(cdbinds);
-
-			[[fallthrough]];
-		}
+		} break;
```
Comment (akien-mga) [inline editor/connections_dialog.cpp:233]: Here too.

File: editor/debugger/script_editor_debugger.cpp [hunk 5]
```diff
@@ -787,8 +787,7 @@ void ScriptEditorDebugger::_notification(int p_what) {
 			error_tree->connect("item_selected", callable_mp(this, &ScriptEditorDebugger::_error_selected));
 			error_tree->connect("item_activated", callable_mp(this, &ScriptEditorDebugger::_error_activated));
 			breakpoints_tree->connect("item_activated", callable_mp(this, &ScriptEditorDebugger::_breakpoint_tree_clicked));
-			[[fallthrough]];
-		}
+		} break;
```
Comment (akien-mga) [inline editor/debugger/script_editor_debugger.cpp:790]: Here too.

File: editor/editor_help.cpp [hunk 6]
```diff
@@ -1994,10 +1970,29 @@ void EditorHelp::_notification(int p_what) {
 		} break;
 
 		case NOTIFICATION_THEME_CHANGED: {
-			if (is_inside_tree()) {
-				_class_desc_resized(true);
-			}
```
Comment (akien-mga) [inline editor/editor_help.cpp:1999]: This was added to prevent crashes as EditorHelp could receive this notification while not in tree - did you check that this is no longer the case?

See #32985 and referenced issues/PRs for details.

File: editor/plugins/font_config_plugin.cpp [hunk 7]
```diff
@@ -380,13 +379,7 @@ EditorPropertyFontMetaOverride::EditorPropertyFontMetaOverride(bool p_script) {
...
 /*************************************************************************/
 
-void EditorPropertyOTVariation::_notification(int p_what) {
-	switch (p_what) {
-		case NOTIFICATION_ENTER_TREE:
-		case NOTIFICATION_THEME_CHANGED: {
-		} break;
-	}
-}
+void EditorPropertyOTVariation::_notification(int p_what) {}
```
Comment (akien-mga) [inline editor/plugins/font_config_plugin.cpp:382]: Should be removed.

File: editor/plugins/polygon_2d_editor_plugin.cpp [hunk 8]
```diff
@@ -91,8 +91,7 @@ void Polygon2DEditor::_notification(int p_what) {
 
 			uv_vscroll->set_anchors_and_offsets_preset(PRESET_RIGHT_WIDE);
 			uv_hscroll->set_anchors_and_offsets_preset(PRESET_BOTTOM_WIDE);
-			[[fallthrough]];
-		}
+		} break;
```
Comment (akien-mga) [inline editor/plugins/polygon_2d_editor_plugin.cpp:94]: Here too.

File: editor/plugins/script_editor_plugin.cpp [hunk 9]
```diff
@@ -352,9 +352,9 @@ void ScriptEditorQuickOpen::_notification(int p_what) {
 			connect("confirmed", callable_mp(this, &ScriptEditorQuickOpen::_confirmed));
 
 			search_box->set_clear_button_enabled(true);
-			[[fallthrough]];
-		}
-		case NOTIFICATION_VISIBILITY_CHANGED: {
```
Comment (akien-mga) [inline editor/plugins/script_editor_plugin.cpp:357]: Worth noting that this was handling `VISIBILITY_CHANGED`. Does it change the behavior?

File: editor/plugins/script_editor_plugin.cpp [hunk 10]
```diff
@@ -1613,8 +1613,7 @@ void ScriptEditor::_notification(int p_what) {
 			EditorSettings::get_singleton()->connect("settings_changed", callable_mp(this, &ScriptEditor::_editor_settings_changed));
 			EditorFileSystem::get_singleton()->connect("filesystem_changed", callable_mp(this, &ScriptEditor::_filesystem_changed));
 			_editor_settings_changed();
-			[[fallthrough]];
-		}
+		} break;
```
Comment (akien-mga) [inline editor/plugins/script_editor_plugin.cpp:1616]: Here too.

File: editor/plugins/script_text_editor.cpp [hunk 11]
```diff
@@ -1392,16 +1392,14 @@ void ScriptTextEditor::_change_syntax_highlighter(int p_idx) {
...
+		case NOTIFICATION_THEME_CHANGED: {
 			if (!editor_enabled) {
 				break;
 			}
 			if (is_visible_in_tree()) {
 				_update_warnings();
 				_update_errors();
 			}
-			[[fallthrough]];
-		case NOTIFICATION_ENTER_TREE: {
```
Comment (akien-mga) [inline editor/plugins/script_text_editor.cpp:1404]: Worth noting that it's not exactly equivalent (now it will reset the gutter width on all theme changes), but it's probably fine anyway.

File: editor/plugins/theme_editor_plugin.cpp [hunk 12]
```diff
@@ -1865,8 +1864,7 @@ void ThemeItemEditorDialog::_notification(int p_what) {
 	switch (p_what) {
 		case NOTIFICATION_ENTER_TREE: {
 			connect("about_to_popup", callable_mp(this, &ThemeItemEditorDialog::_dialog_about_to_show));
-			[[fallthrough]];
-		}
+		} break;
```
Comment (akien-mga) [inline editor/plugins/theme_editor_plugin.cpp:1867]: Here too.

File: editor/plugins/theme_editor_plugin.cpp [hunk 13]
```diff
@@ -2194,8 +2192,7 @@ void ThemeTypeDialog::_notification(int p_what) {
 	switch (p_what) {
 		case NOTIFICATION_ENTER_TREE: {
 			connect("about_to_popup", callable_mp(this, &ThemeTypeDialog::_dialog_about_to_show));
-			[[fallthrough]];
-		}
+		} break;
```
Comment (akien-mga) [inline editor/plugins/theme_editor_plugin.cpp:2195]: Here too.

File: editor/plugins/theme_editor_preview.cpp [hunk 14]
```diff
@@ -193,8 +193,7 @@ void ThemeEditorPreview::_notification(int p_what) {
 			}
 
 			connect("visibility_changed", callable_mp(this, &ThemeEditorPreview::_preview_visibility_changed));
-			[[fallthrough]];
-		}
+		} break;
```
Comment (akien-mga) [inline editor/plugins/theme_editor_preview.cpp:196]: Here too.

File: editor/plugins/visual_shader_editor_plugin.cpp [hunk 15]
```diff
@@ -3704,9 +3703,10 @@ void VisualShaderEditor::_notification(int p_what) {
 
 			graph->get_panner()->setup((ViewPanner::ControlScheme)EDITOR_GET("editors/panning/sub_editors_panning_scheme").operator int(), ED_GET_SHORTCUT("canvas_item_editor/pan_view"), bool(EditorSettings::get_singleton()->get("editors/panning/simple_panning")));
 			graph->set_warped_panning(bool(EditorSettings::get_singleton()->get("editors/panning/warped_mouse_panning")));
-			[[fallthrough]];
-		}
+		} break;
```
Comment (akien-mga) [inline editor/plugins/visual_shader_editor_plugin.cpp:3706]: Here too.

File: editor/script_create_dialog.cpp [hunk 16]
```diff
@@ -120,9 +120,7 @@ void ScriptCreateDialog::_notification(int p_what) {
 			} else {
 				language_menu->select(default_language);
 			}
-
-			[[fallthrough]];
-		}
+		} break;
```
Comment (akien-mga) [inline editor/script_create_dialog.cpp:123]: Here too.

File: scene/gui/color_picker.cpp [hunk 17]
```diff
@@ -63,8 +63,7 @@ void ColorPicker::_notification(int p_what) {
 				}
 			}
 #endif
-			[[fallthrough]];
-		}
+		} break;
```
Comment (akien-mga) [inline scene/gui/color_picker.cpp:66]: Here too.

File: scene/gui/gradient_edit.cpp [hunk 18]
```diff
@@ -292,8 +292,7 @@ void GradientEdit::_notification(int p_what) {
 			if (!picker->is_connected("color_changed", callable_mp(this, &GradientEdit::_color_changed))) {
 				picker->connect("color_changed", callable_mp(this, &GradientEdit::_color_changed));
 			}
-			[[fallthrough]];
-		}
+		} break;
```
Comment (akien-mga) [inline scene/gui/gradient_edit.cpp:295]: Here too.

**Review by akien-mga — APPROVED** [review]

File: editor/editor_help.cpp (hunk 6 above)
Comment (AaronRecord) [reply editor/editor_help.cpp:1999]: It's the same thing as https://github.com/godotengine/godot/blob/e06cd2742f8af57b23fa11dec62ba9c4eb544291/editor/plugins/texture_editor_plugin.cpp#L41-L49

`NOTIFICATION_THEME_CHANGED` should now never be called when the node is outside of the tree, so this check is redundant.

File: editor/plugins/script_editor_plugin.cpp (hunk 9 above)
Comment (AaronRecord) [reply editor/plugins/script_editor_plugin.cpp:357]: I'll check, but I don't see anything special about this case, it seems like it should just be using `NOTIFICATION_THEME_CHANGED`

File: editor/plugins/script_text_editor.cpp (hunk 11 above)
Comment (AaronRecord) [reply editor/plugins/script_text_editor.cpp:1404]: Fixed

File: editor/animation_bezier_editor.cpp (hunk 3 above)
Comment (AaronRecord) [reply editor/animation_bezier_editor.cpp:219]: It'd be neat if this could be added to clang-format

**Comment by AaronRecord** [comment]
Changes made, thanks for the thorough review :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Reverted for now in #65025, see the PR description for details.
