### PR TITLE
Don't attempt to create or use an R8_UINT texture as storage if VRS is not supported

### LINKED ISSUE #67430: texture_create: Format 'R8_Uint' does not support usage as storage image.
### Godot version

Godot Engine v4.0.beta3.official.01ae26d31

### System information

VIVO Z3, Android 9, Snapdragon 710AIE, Vulkan API 1.1.0 - Using Vulkan Device #0: Qualcomm - Adreno (TM) 616

### Issue description

Just re-tested https://github.com/godotengine/godot/issues/67146 on beta3 this time reveal a new issue, still black screen
image

### Steps to reproduce

please use the reproduction project

### Minimal reproduction project
[demo.zip](https://github.com/godotengine/godot/files/9791365/demo.zip)

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/67430

I can't reproduce the original issue so I changed the rendering device code to always return VRS not supported and to always fail when trying to allocate an R8_UINT texture. Would be good to have testing from @BastiaanOlij and some of the users who were able to reproduce the original error

### CODE REVIEW

**Review by BastiaanOlij — APPROVED** [review]
This is such a pain, specialization constants make this so much neater, to just be thwarted by just the inclusion of the 8bit int type...

More than happy that this is changed back to using plain old defines.

My only remark is that in other shaders we do add all variant but we then disable the unsupported variants preventing them from being compiled, this so there are no changes in the enumeration of the variants. In this case we only have two variants, the last one being the VRS one, so it doesn't matter much but maybe to future proof it we should follow that pattern.

**Comment by clayjohn** [comment]
> This is such a pain, specialization constants make this so much neater, to just be thwarted by just the inclusion of the 8bit int type...
> 
> More than happy that this is changed back to using plain old defines.
> 
> My only remark is that in other shaders we do add all variant but we then disable the unsupported variants preventing them from being compiled, this so there are no changes in the enumeration of the variants. In this case we only have two variants, the last one being the VRS one, so it doesn't matter much but maybe to future proof it we should follow that pattern.

We actually don't create VRS variants with this code. Instead I use a global define. As we never need both VRS and non-VRS variants we only compile one. Now that I think about it, this means the VRS code will be run if VRS is supported even if not enabled. I will bring back the specialization constant so we can enable/disable without creating more variants

**Comment by clayjohn** [comment]
Should be ready to merge now

File: servers/rendering/renderer_rd/storage_rd/texture_storage.cpp [hunk 1]
```diff
@@ -420,10 +420,11 @@ TextureStorage::TextureStorage() {
 		tformat.width = 4;
 		tformat.height = 4;
 		tformat.usage_bits = RD::TEXTURE_USAGE_COLOR_ATTACHMENT_BIT | RD::TEXTURE_USAGE_SAMPLING_BIT | RD::TEXTURE_USAGE_STORAGE_BIT | RD::TEXTURE_USAGE_CAN_UPDATE_BIT;
-		if (RD::get_singleton()->has_feature(RD::SUPPORTS_ATTACHMENT_VRS)) {
-			tformat.usage_bits |= RD::TEXTURE_USAGE_VRS_ATTACHMENT_BIT;
-		}
 		tformat.texture_type = RD::TEXTURE_TYPE_2D;
+		if (!RD::get_singleton()->has_feature(RD::SUPPORTS_ATTACHMENT_VRS)) {
+			tformat.usage_bits = RD::TEXTURE_USAGE_COLOR_ATTACHMENT_BIT | RD::TEXTURE_USAGE_SAMPLING_BIT | RD::TEXTURE_USAGE_STORAGE_BIT | RD::TEXTURE_USAGE_CAN_UPDATE_BIT;
```
Comment (akien-mga) [inline servers/rendering/renderer_rd/storage_rd/texture_storage.cpp:425]: This duplicates the assignment two lines above, seems redundant.
There's no more VRS attachment bit set?

Comment (clayjohn) [reply servers/rendering/renderer_rd/storage_rd/texture_storage.cpp:425]: Should be good now

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by norrath-hero-cn** [comment]
Just checked this PR builds, issue still exists, please take a took on https://github.com/godotengine/godot/issues/67430, I uploaded full logcat logs there
