### PR TITLE
Fix crash when extending taken-over named class

### LINKED ISSUE #83542: `take_over_path` and extending the same named class twice
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3699) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

```gdscript
func _init() -> void:
	var extend_0 = load("res://extends/extend0.gd")
	extend_0.new()
	extend_0.take_over_path("res://base.gd")
	var extend_1 = load("res://extends/extend1.gd")
	extend_1.new()
	extend_1.take_over_path("res://base.gd")
```

Running this code causes a game crash with no error message in the editor output.

The following error is printed if the editor is run with the console:

```
ERROR: FATAL: Condition "!exists" is true.
   at: operator[] (./core/templates/hash_map.h:504)
```

This pattern was used to build an ["inheritance chain"](https://blog.cy.md/2022/05/27/modding-for-godot/) for [modding](https://github.com/GodotModding/godot-mod-loader) in Godot 3.5.

In Godot 4.1, after loading the first script and taking over the path of the named class, it crashes the game as soon as the second script that extends the same-named class is loaded, in the above example:

```gdscript
var extend_1 = load("res://extends/extend1.gd")
```

This all works as expected if the `class_name Base` is removed from *res://base.gd*.

### Steps to reproduce

1. Create a script with a `class_name`:
```gdscript
class_name Base
extends Node

func _ready() -> void:
    print("base")

func do_stuff() -> void:
    print("do_stuff")
```

2. Create 2 scripts that extend the named class:

```gdscript
# extend0.gd
extends "res://base.gd"

func _ready() -> void:
    super._ready()
    print("extend0 - _ready()")

func do_stuff() -> void:
    super.do_stuff()
    print("extend0 - do_stuff()")
```

```gdscript
# extend1.gd
extends "res://base.gd"

func _ready() -> void:
    super._ready()
    print("extend1 - _ready()")
```

3. Create an autoload with the following code:

```gdscript
func _init() -> void:
    var extend_0 = load("res://extends/extend0.gd")
    extend_0.new()
    extend_0.take_over_path("res://base.gd")
    var extend_1 = load("res://extends/extend1.gd")
    extend_1.new()
    extend_1.take_over_path("res://base.gd")
```

**Minimal reproduction project description**

*res://base.gd*
- The named class (`class_name Base`) that is extended and taken over by `res://extends/extend0.gd` and `res://extends/extend1.gd`.
- The `class_name Base` can be commented out to toggle between working and not working.

*res://extends/extend0.gd and res://extends/extend1.gd*
- These scripts can be viewed as two mods that want to modify the same vanilla game script.

*res://singletons/extender.gd*
- An autoload that handles the extending of the script. Each "script extension" is loaded, and `take_over_path` is used to take over the base script.

*res://VanillaThing.gd*
- Represents a vanilla game script that calls the modified `do_stuff` method on the `Base` class.
- If everything works as intended, calling `do_stuff` from here should print:

```
do_stuff
extend0 - do_stuff()
```

### Minimal reproduction project

[Script Extending.zip](https://github.com/godotengine/godot/files/12999139/Script.Extending.zip)

### PR DESCRIPTION
**Pull request by KANAjetzt**
Added error handling in `_prepare_compilation()` to address cases where the `base_type` cannot be found, preventing a crash. 
Added an additional if statement to `find_class()` to check the script path.

I expect this to not be the ideal solution, as I stated in my issue comment.
But this PR might be a better place to discuss code changes, and I'm looking forward to any feedback.

Nonetheless, I ran all the GDScript tests and tried this fix in the MRP and two bigger projects with success and no obvious side effects.

Cheers.

---
> [!NOTE]
> This now only contains the crash prevention. Future debugging is needed. #83542 will stay open.

### CODE REVIEW

**Comment by adamscott** [comment]
If we merge this PR, I'm wondering if we should update the GDScriptCache when a path is taken over by a new script.

**Review by adamscott — APPROVED** [review]
Seems fine!

Thank you again for your first PR!

File: modules/gdscript/gdscript_compiler.cpp [hunk 1]
```diff
@@ -2647,7 +2647,10 @@ Error GDScriptCompiler::_prepare_compilation(GDScript *p_script, const GDScriptP
 
 	GDScriptDataType base_type = _gdtype_from_datatype(p_class->base_type, p_script, false);
 
+	ERR_FAIL_COND_V_MSG(base_type.native_type == StringName(), ERR_BUG, vformat(R"(Failed to get base class for "%s")", p_script->path));
```
Comment (akien-mga) [inline modules/gdscript/gdscript_compiler.cpp:2650]: Should this be an engine-level error (`ERR_BUG`), or a user-level error (`_set_error` + returning the most relevant error code)?

File: modules/gdscript/gdscript.cpp [hunk 2]
```diff
@@ -1102,6 +1102,9 @@ GDScript *GDScript::find_class(const String &p_qualified_name) {
 		// Script path could have a class path separator("::") in it.
 		class_names = p_qualified_name.trim_prefix(get_root_script()->path).split("::");
 		result = get_root_script();
+	} else if (path.begins_with(get_root_script()->path)) {
+		class_names = path.trim_prefix(get_root_script()->path).split("::");
+		result = get_root_script();
```
Comment (dalexeev) [inline modules/gdscript/gdscript.cpp:1107]: I'm not sure, but the condition looks as always true to me. `p_qualified_name` is not used at all in the branch, this is weird.

File: modules/gdscript/gdscript_compiler.cpp (hunk 1 above)
Comment (dalexeev) [reply modules/gdscript/gdscript_compiler.cpp:2650]: I think it's fine, this should not happen as a result of user error, it's an analyzer/compiler bug.

File: modules/gdscript/gdscript.cpp (hunk 2 above)
Comment (KANAjetzt) [reply modules/gdscript/gdscript.cpp:1107]: Thanks for looking at this! I tried to explain what I found while debugging [here](https://github.com/godotengine/godot/issues/83542#issuecomment-1782628013).

If you can provide more details, I can dive back in.

"_The condition looks as always true_" - Which condition?
_"`p_qualified_name` is not used_" - What exactly do you mean by "not used" and what is weird about it?

Comment (dalexeev) [reply modules/gdscript/gdscript.cpp:1107]: > Which condition?

`path.begins_with(get_root_script()->path)`. `path` is the script path, for inner classes it may additionally contain suffixes. `get_root_script()` returns the topmost script that owns the inner class scripts.

> What exactly do you mean by "not used" and what is weird about it?

This method checks `p_qualified_name`, every other branch has `p_qualified_name`, but not this one, that's weird. I haven't tested this, but it might break the `_owner != nullptr` branch.

Comment (KANAjetzt) [reply modules/gdscript/gdscript.cpp:1148]: >  I haven't tested this, but it might break the _owner != nullptr branch.

How can I test for this? 
Adding some inner classes to my MRP?
I run `--test --test-suite="*GDScript*"` and everything seems to be fine.
image

Comment (dalexeev) [reply modules/gdscript/gdscript.cpp:1148]: Successful tests do not guarantee the absence of regressions, since the tests do not cover all possible scenarios. I added this PR for discussion at the GDScript team meeting or maybe @vnen will review it offline.

Comment (vnen) [reply modules/gdscript/gdscript.cpp:1148]: It is odd to me as well. This is a function to find a class identified by `p_qualified_name`, so the branch not checking the argument cannot reliably find the requested class. As @dalexeev said, this will always be true (the path of an inner class will always start with the path of its root script), so the other conditions will never be checked.

Given that, I don't think this is a proper solution.

**Review by vnen — DISMISSED** [review]
See comment

**Comment by pirey0** [comment]
@vnen i've been talking with Kana and further analyzed the root cause for this issue (see https://github.com/godotengine/godot/issues/83542#issuecomment-2094835838)
 This problem will not be fixed by changes to find_class(.
Maybe we should close this PR, and address the actual problem in a new PR?

**Review by dalexeev — APPROVED** [review]

**Comment by akien-mga** [comment]
This seems good as crash prevention, but the bug still exsits. Do we have an open bug report with a MRP keeping track of it?

**Comment by pirey0** [comment]
> This seems good as crash prevention, but the bug still exsits. Do we have an open bug report with a MRP keeping track of it?

https://github.com/godotengine/godot/issues/83542

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
