### PR TITLE
Fix animation player crash when setting current animation to stop

### LINKED ISSUE #98076: Track of Current Animation Crush
### Tested versions

4.3.stable

### System information

Godot v4.3.stable (77dcf97d8) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 32.0.15.6109) - AMD Ryzen 7 6800H with Radeon Graphics (16 Threads)

### Issue description

If you create a property track in animation player, which tracks current animation. It will crush engine, and if you save it, it will crush engine in every start or at least when you try to open this Animation Player.

https://github.com/user-attachments/assets/2ac6c9ee-9811-40ac-b7c0-d9525b944527

### Steps to reproduce

Create Animation Player (AP)
Create Animation in AP
Add new Property Track on Current Animation of Ap.
Save file

Crush

If you try to open AP it will crush 

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/17335329/test.zip)

### LINKED ISSUE #115105: Clicking AnimationPlayer causes a Crash
### Tested versions

v4.5.stable.official [876b29033]
v4.5.1.stable.official [f62fdbde1]

### System information

Windows 10  - Ryzen 1600 - RX 6600

### Issue description

https://github.com/user-attachments/assets/95577fb5-3fa2-4ec1-b4d5-d04e8986cf53

Video is self explanatory. Clicking AnimationPlayer causes a crash. I was working on it and it happened. For some reason, the AnimationPlayer has become corrupted
Now I cant delete it since I cannot select it. Lucky In this case I can delete a parent that is a scene and redo it but it could have been a bigger problem.
However, the problem is what if it happens again.
As for what elements i used: Position, Animation, Flip for the Sprite and current_animation for AnimationPlayer.

### Steps to reproduce

Click on AnimationPlayer

### Minimal reproduction project (MRP)

[Minimal needed for a crash.zip](https://github.com/user-attachments/files/24697876/Minimal.needed.for.a.crash.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
- Fixes https://github.com/godotengine/godot/issues/115105
- Fixes https://github.com/godotengine/godot/issues/98076
- Supersedes https://github.com/godotengine/godot/pull/115126
- Supersedes https://github.com/godotengine/godot/pull/98704

The fundamental issue is that calling `seek()` inside `stop()` to reset the state causes `set_current_animation()` to be called recursively.

The following changes will prevent the crash:

1. Make `stop()` a deferred call
2. Limit the case setting `current_animation` and triggering the `stop()` only when `is_playing()` is `true`

Also, since stopping via `current_animation` clears the `AnimationPlayer`'s `current_animation`, implement a fallback in `AnimationPlayerEditor` for when `current_animation` is empty.

And remove unused flag and comment.

### CODE REVIEW

File: scene/animation/animation_player.cpp [hunk 1]
```diff
@@ -595,7 +595,12 @@ bool AnimationPlayer::is_playing() const {
 
 void AnimationPlayer::set_current_animation(const StringName &p_animation) {
 	if (p_animation == SNAME("[stop]") || p_animation.is_empty()) {
-		stop();
+		// It should be call deferred and handled only when is_playing() == true to prevent infinite loops caused by seeking within stop().
+		// Especially when the key current_animation = "[stop]" is placed at the beginning of an animation,
+		// this line is called when the animation changes, so is_playing() == true must be checked.
+		if (is_playing()) {
+			callable_mp(this, &AnimationPlayer::stop).bind(false).call_deferred();
```
Comment (AThousandShips) [inline scene/animation/animation_player.cpp]:
```suggestion
			callable_mp(this, &AnimationPlayer::stop).call_deferred(false);
```

Comment (AThousandShips) [inline scene/animation/animation_player.cpp]:
```suggestion
			callable_mp(this, &AnimationPlayer::stop).call_deferred(false);
```

**Review by lyuma — APPROVED** [review]
I think the code looks good
