### PR TITLE
#24303: remember sorting order in the project manager

### LINKED ISSUE #24303: Sorting in the Project Manager is not saved. Always defaults to Name.
**Godot version:**
Godot 3.1 alpha 3

**OS/device including version:**
Windows 10 64bit

**Issue description:**
The new "sort" option in the Project Manager always defaults to the "Name" option when opened. It should remember the last selected sort option and always open with that.

**Steps to reproduce:**
Open Project Manager, change sort option to "Last Modified", close Project Manager and open it again, It will be back to sorting by "Name".

### PR DESCRIPTION
**Pull request by mineevgleb**
Closes #24303

### CODE REVIEW

File: editor/project_manager.cpp [hunk 1]
```diff
@@ -1165,10 +1165,13 @@ void ProjectManager::_load_recent_projects() {
 
 	bool set_ordered_latest_modification;
 	ProjectListFilter::FilterOption filter_order_option = project_order_filter->get_filter_option();
-	if (filter_order_option == ProjectListFilter::FILTER_NAME)
+	if (filter_order_option == ProjectListFilter::FILTER_NAME) {
 		set_ordered_latest_modification = false;
-	else
+		EditorSettings::get_singleton()->set("default_projects_order", "Name");
```
Comment (akien-mga) [inline editor/project_manager.cpp]: To do this cleanly (as it will be exposed in the Editor Settings), I would put it in a `project_manager` category, like `project_manager/sorting_order` (no need to mention `default`, it's not just a default as you can't override it - if you change it, the default is changed too :)).

And I would save the enum value instead of a string. You can do it with:
```
EditorSettings::get_singleton()->add_property_hint(PropertyInfo(Variant::INT, "project_manager/sorting_order", PROPERTY_HINT_ENUM, "Name,Last Modified"));
```

File: editor/project_manager.cpp [hunk 2]
```diff
@@ -1838,16 +1840,22 @@ ProjectManager::ProjectManager() {
...
+	project_order_filter->_setup_filters(sort_filter_titles);
 	project_order_filter->set_filter_size(150);
 	sort_filters->add_child(project_order_filter);
 	project_order_filter->connect("filter_changed", this, "_load_recent_projects");
 	project_order_filter->set_custom_minimum_size(Size2(180, 10) * EDSCALE);
 
+	Variant projects_sorting_order = EditorSettings::get_singleton()->get("project_manager/sorting_order");
+
+	if (projects_sorting_order.get_type() != Variant::NIL) {
+		project_order_filter->set_filter_option((ProjectListFilter::FilterOption)((int)projects_sorting_order));
```
Comment (bojidar-bg) [inline editor/project_manager.cpp]: You might be able to do this without the (int) cast if you add `VARIANT_ENUM_CAST`.

Comment (mineevgleb) [reply editor/project_manager.cpp]: Well, given that this cast is only needed in this one place, leaving it like this might be simplier. And I'll need to make the enum public to use VARIANT_ENUM_CAST, I guess. (not sure why it's private now, but still :)).

Comment (akien-mga) [reply editor/project_manager.cpp]: I'd do `int project_sorting_order = (int)EditorSettings::get_singleton()->get("project_manager/sorting_order");` to avoid this `Variant::NIL` stuff.

**Comment by akien-mga** [comment]
Could you squash the commits together?

**Comment by mineevgleb** [comment]
Looks like I fucked up the commit history somehow, and now it shows my commit and two commits before, how do I fix it?)

**Comment by akien-mga** [comment]
Thanks!
