### PR TITLE
Fix crash when freeing GradientTexture and NoiseTexture

### LINKED ISSUE #49563: Executing NoiseTexture functions crashes Godot
### Godot version

4.0.dev.custom_build. e82a1113a

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

When executing
```
var q = NoiseTexture.new()
q.set_width(-4)
q.set_noise(OpenSimplexNoise.new())
q._update_texture()
```

Godot crashes with backtrace
```
ERROR: Condition "p_size < 0" is true. Returning: ERR_INVALID_PARAMETER
   at: resize (./core/templates/cowdata.h:260)
ERROR: Image width must be greater than 0.
   at: create (core/io/image.cpp:1994)
ERROR: Condition "p_image->is_empty()" is true.
   at: texture_2d_initialize (servers/rendering/renderer_rd/renderer_storage_rd.cpp:549)
ERROR: Attempting to use an uninitialized RID
   at: getornull (./core/templates/rid_owner.h:197)
servers/rendering/renderer_rd/renderer_storage_rd.cpp:8555:3: runtime error: member access within null pointer of type 'struct Texture'
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] godot4s() [0x2050562] (/mnt/Miecz/godot/platform/linuxbsd/crash_handler_linuxbsd.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x41040) [0x7fef1b242040] (??:0)
[3] RendererStorageRD::free(RID) (/mnt/Miecz/godot/servers/rendering/renderer_rd/renderer_storage_rd.cpp:8555)
[4] RenderingServerDefault::_free(RID) (/mnt/Miecz/godot/servers/rendering/rendering_server_default.cpp:68)
[5] RenderingServerDefault::free(RID) (/mnt/Miecz/godot/servers/rendering/rendering_server_default.h:904)
[6] NoiseTexture::~NoiseTexture() (/mnt/Miecz/godot/modules/opensimplex/noise_texture.cpp:45)
[7] void memdelete<Reference>(Reference*) (/mnt/Miecz/godot/./core/os/memory.h:118)
[8] Variant::_clear_internal() (/mnt/Miecz/godot/core/variant/variant.cpp:1311)
[9] Variant::clear() (/mnt/Miecz/godot/./core/variant/variant.h:259)
[10] Variant::~Variant() (/mnt/Miecz/godot/./core/variant/variant.h:670)
[11] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/mnt/Miecz/godot/modules/gdscript/gdscript_vm.cpp:3317 (discriminator 2))
[12] GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) (/mnt/Miecz/godot/modules/gdscript/gdscript.cpp:1487)
[13] ScriptInstance::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/mnt/Miecz/godot/core/object/script_language.cpp:311)
[14] Node::_notification(int) (/mnt/Miecz/godot/scene/main/node.cpp:58)
[15] Node::_notificationv(int, bool) (/mnt/Miecz/godot/./scene/main/node.h:45 (discriminator 14))
[16] CanvasItem::_notificationv(int, bool) (/mnt/Miecz/godot/./scene/main/canvas_item.h:164 (discriminator 3))
[17] Node2D::_notificationv(int, bool) (/mnt/Miecz/godot/./scene/2d/node_2d.h:37 (discriminator 3))
[18] Object::notification(int, bool) (/mnt/Miecz/godot/core/object/object.cpp:827)
[19] SceneTree::_notify_group_pause(StringName const&, int) (/mnt/Miecz/godot/scene/main/scene_tree.cpp:809)
[20] SceneTree::process(float) (/mnt/Miecz/godot/scene/main/scene_tree.cpp:443 (discriminator 2))
[21] Main::iteration() (/mnt/Miecz/godot/main/main.cpp:2495)
[22] OS_LinuxBSD::run() (/mnt/Miecz/godot/platform/linuxbsd/os_linuxbsd.cpp:278)
[23] godot4s(main+0x3fc) [0x204e042] (/mnt/Miecz/godot/platform/linuxbsd/godot_linuxbsd.cpp:60)
[24] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xd5) [0x7fef1b229565] (??:0)
[25] godot4s(_start+0x2e) [0x204db8e] (??:?)
-- END OF BACKTRACE --
Aborted (core dumped)
```

This example was found by fuzzer, so I don't recommend trying understand in what situation such code could be used in real project, because such situation probably doesn't exists.

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### LINKED ISSUE #49569: Freeing GradientTexture crashes Godot
### Godot version

4.0.dev.custom_build. e82a1113a

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

When executing
```
func _process(_delta):
	var q = GradientTexture.new()
	q.set_width(-3)
	q.set_gradient(Gradient.new())
```

Godot crashes with backtrace
```
ERROR: Condition "p_size < 0" is true. Returning: ERR_INVALID_PARAMETER
   at: resize (./core/templates/cowdata.h:260)
ERROR: Image width must be greater than 0.
   at: create (core/io/image.cpp:1994)
ERROR: Condition "p_image->is_empty()" is true.
   at: texture_2d_initialize (servers/rendering/renderer_rd/renderer_storage_rd.cpp:549)
ERROR: Attempting to use an uninitialized RID
   at: getornull (./core/templates/rid_owner.h:197)
servers/rendering/renderer_rd/renderer_storage_rd.cpp:8555:3: runtime error: member access within null pointer of type 'struct Texture'
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] godot4s() [0x2050562] (/mnt/Miecz/godot/platform/linuxbsd/crash_handler_linuxbsd.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x41040) [0x7f97781f3040] (??:0)
[3] RendererStorageRD::free(RID) (/mnt/Miecz/godot/servers/rendering/renderer_rd/renderer_storage_rd.cpp:8555)
[4] RenderingServerDefault::_free(RID) (/mnt/Miecz/godot/servers/rendering/rendering_server_default.cpp:68)
[5] RenderingServerDefault::free(RID) (/mnt/Miecz/godot/servers/rendering/rendering_server_default.h:904)
[6] GradientTexture::~GradientTexture() (/mnt/Miecz/godot/scene/resources/texture.cpp:1515)
[7] void memdelete<Reference>(Reference*) (/mnt/Miecz/godot/./core/os/memory.h:118)
[8] Variant::_clear_internal() (/mnt/Miecz/godot/core/variant/variant.cpp:1311)
[9] Variant::clear() (/mnt/Miecz/godot/./core/variant/variant.h:259)
[10] Variant::~Variant() (/mnt/Miecz/godot/./core/variant/variant.h:670)
[11] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/mnt/Miecz/godot/modules/gdscript/gdscript_vm.cpp:3317 (discriminator 2))
[12] GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) (/mnt/Miecz/godot/modules/gdscript/gdscript.cpp:1487)
[13] ScriptInstance::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/mnt/Miecz/godot/core/object/script_language.cpp:311)
[14] Node::_notification(int) (/mnt/Miecz/godot/scene/main/node.cpp:58)
[15] Node::_notificationv(int, bool) (/mnt/Miecz/godot/./scene/main/node.h:45 (discriminator 14))
[16] CanvasItem::_notificationv(int, bool) (/mnt/Miecz/godot/./scene/main/canvas_item.h:164 (discriminator 3))
[17] Node2D::_notificationv(int, bool) (/mnt/Miecz/godot/./scene/2d/node_2d.h:37 (discriminator 3))
[18] Object::notification(int, bool) (/mnt/Miecz/godot/core/object/object.cpp:827)
[19] SceneTree::_notify_group_pause(StringName const&, int) (/mnt/Miecz/godot/scene/main/scene_tree.cpp:809)
[20] SceneTree::process(float) (/mnt/Miecz/godot/scene/main/scene_tree.cpp:443 (discriminator 2))
[21] Main::iteration() (/mnt/Miecz/godot/main/main.cpp:2495)
[22] OS_LinuxBSD::run() (/mnt/Miecz/godot/platform/linuxbsd/os_linuxbsd.cpp:278)
[23] godot4s(main+0x3fc) [0x204e042] (/mnt/Miecz/godot/platform/linuxbsd/godot_linuxbsd.cpp:60)
[24] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xd5) [0x7f97781da565] (??:0)
[25] godot4s(_start+0x2e) [0x204db8e] (??:?)
```

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by timothyqiu**
* The crash was directly caused by `RID_Alloc` calling destructor for uninitialized elements.
    * The backtrace of original issues show godot crashed at a different place for a different reason, that was covered by #49520.
* No range validation are performed when setting texture size, thus the uninitialized element, resulting in leaked RID allocations at exit.

Fixes #49569.
Fixes #49563.

### CODE REVIEW

File: core/templates/rid_owner.h [hunk 1]
```diff
@@ -351,6 +351,9 @@ class RID_Alloc : public RID_AllocBase {
 
 			for (size_t i = 0; i < max_alloc; i++) {
 				uint64_t validator = validator_chunks[i / elements_in_chunk][i % elements_in_chunk];
+				if (validator & 0x80000000) {
+					continue; //uninitialized
+				}
```
Comment (akien-mga) [inline core/templates/rid_owner.h:356]: About this change, @reduz said:
```
technically this situation should never happen so, while the fix is correct, I wonder what is causing it 
```

Comment (timothyqiu) [reply core/templates/rid_owner.h:356]: `RID_Alloc::allocate_rid()` and `RID_Alloc::initialize_rid()` are two APIs, so this situation will happen if only the former is called.

In this case, the `initialize_rid()` inside `RendererStorageRD::texture_2d_initialize()` will be skipped if `ERR_FAIL_COND` is triggered. No error handling can be done in `texture_2d_create()` (the `FUNCRIDTEX1` macro).

https://github.com/godotengine/godot/blob/7a85e95a4b699960c540bb583cec526ab1b034d8/servers/rendering/renderer_rd/renderer_storage_rd.cpp#L543-L551

https://github.com/godotengine/godot/blob/7a85e95a4b699960c540bb583cec526ab1b034d8/servers/rendering/rendering_server_default.h#L156-L165

The parameter range validations in this PR are added to prevent this error condition from happening.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
