### PR TITLE
Handling NodePaths in in-place Editor for Resources

### LINKED ISSUE #16035: Editing ViewportTexture's ViewportPath in-place using the node browser icon creates a non-working path
If ViewportTexture’s ViewportPath is edited in-place using the little node browser icon next to it, then it ends up with some weirdly long path like “/root/EditorNode/@@5/@@6/@@14/@@16/@@20/@@24/@@25/@@26/@@42/@@43/@@50/@@51/@@6456/@@6322/@@6323/@@6324/@@6325/@@6326/@@6327/Root_Control/MyViewport”, which works in the editor but not when running app.

To reproduce, create a new scene, at a Node2D as the root, add a Viewport and a Sprite at the top level. For the Sprite's texture, use the drop-down arrow to create a "New ViewportTexture", then select the Viewport you created earlier for this texture. Everything works fine at this point. But then click on the assigned Texture for the Sprite to open up the created ViewportTexture in the node/attribute editor and assign the "Viewport Path" there using the browser icon next to it (assign it to the same Viewport or to another). This produces a long path similar to the one I copied above, which works fine in the Godot Editor, but not in a running app.

**Godot version:**
V3.0, custom build (currently based on Commit #44cce2b of Jan 24, 2018, but the issue has been there for awhile).

### PR DESCRIPTION
**Pull request by DavidSichma**
Closes #16035

The NodePath builtin editor now handles NodePaths in Resources relative to the edited scene root.
This makes it possible to assign a NodePath that does not only work in the editor.

The viewport property of ViewportTexture can now be reassigned.

### CODE REVIEW

File: editor/editor_properties.cpp [hunk 1]
```diff
@@ -1802,8 +1802,13 @@ void EditorPropertyNodePath::_node_selected(const NodePath &p_path) {
 
 	NodePath path = p_path;
 	Node *base_node = Object::cast_to<Node>(get_edited_object());
-	if (base_node == NULL && get_edited_object()->has_method("get_root_path")) {
-		base_node = get_edited_object()->call("get_root_path");
+	if (base_node == NULL){
+		if (Object::cast_to<Resource>(get_edited_object())){
```
Comment (LikeLakers2) [inline editor/editor_properties.cpp]: You should have a space before the opening brackets: https://travis-ci.org/godotengine/godot/jobs/446867553#L534

Comment (DavidSichma) [reply editor/editor_properties.cpp]: fixed.

**Comment by akien-mga** [comment]
Thanks!
