### PR TITLE
Fix initialization of visual server in all platforms

### LINKED ISSUE #17086: Using resource_queue.gd script not working on Android
**Godot version:**
Godot 3.0.2

**OS/device including version:**
Android 5.0 Lolipop / Xiaomi Redmi A4 (GPU: Adreno 308)
Android 7.0 Nougat / Xiaomi Mi6
Android 8.0 Oreo / LG Nexus 5X (GPU: Adreno Adreno 418)

**Issue description:**
When loading a scene in background, the textures are shown in black.

**Steps to reproduce:**
Export project to android, open apk. Should see black space (which should be a texture) over colored background. Button on the right, is to switch between two different scenes.  

**Minimal reproduction project:**
[BackgroundResourceLoading.zip](https://github.com/godotengine/godot/files/1889055/BackgroundResourceLoading.zip)

### LINKED ISSUE #21609: Background thread loading demo not working on Android and iOS
**Godot version:**

master: v3.1 2b9902d

**OS/device including version:**

Windows 10
Android 7.1.1 in Motorola Moto Z
iOS 11.4.1 in iPhone 6

**Issue description:**

Running the background loading demo works fine on Windows, but shows black boxes on Android.

**Steps to reproduce:**
1. Open the background thread loading demo
2. Test on Windows: works fine
3. Test on Android: shows black squares instead of the images
Android screenshot

**Minimal reproduction project:**
Background thread loading demo

### PR DESCRIPTION
**Pull request by vnen**
Avoid leaking an extra instance when using threads. Also fix threaded loading issues on Android and iOS.

Fix #21609.
Likely fix #17086 too.

### CODE REVIEW

File: platform/iphone/os_iphone.cpp [hunk 1]
```diff
@@ -107,13 +107,12 @@ Error OSIPhone::initialize(const VideoMode &p_desired, int p_video_driver, int p
 	RasterizerGLES3::register_config();
 	RasterizerGLES3::make_current();
 
-	visual_server = memnew(VisualServerRaster());
-	/*
-		FIXME: Reimplement threaded rendering? Or remove?
+	// FIXME: Reimplement threaded rendering? Or remove?
```
Comment (akien-mga) [inline platform/iphone/os_iphone.cpp]: That comment is no longer relevant since this commit does reimplement it. Same in Haiku and UWP code.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we only plan to cherry-pick critical bug fixes to the 3.0 branch, unless there is very strong support in favor of a specific non-critical issue. Removing cherrypick label for 3.0.
