### PR TITLE
Use BitField<> in core type masks

### LINKED ISSUE #64005: Use `VARIANT_BITFIELD_CAST()` consistently for all flag enums
### Godot version

3.5

### System information

PopOS

### Issue description

When I get the list of script variables of a node by calling the get_property_list() method, the properties related to export variables comes with the value 8199 in "usage" instead of 8192 used for the flag PROPERTY_USAGE_SCRIPT_VARIABLE. I cannot find this new flag in the Docs and neither in the GlobalScope.xml.

### Steps to reproduce

Create a script with some export variables, use the get_property_list() in the _ready() method and analyze the "usage" key of the script variables (that come at the end of the list).

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by reduz**
* All core types masks are now correctly marked as bitfields.
* The enum hacks in MouseButtonMask (that results in weird values outside the enum elements) and many other similar types are gone. This ensures that binders to other languages non C++ can actually implement type safe bitmasks.
* Most bitmask operations replaced by functions in BitField<>, which are safe and less error prone.
* Key enum is still a problem because its an enum and a mask at the same time. While it kind of works in C++, this most likely can't be implemented safely in other languages and will have to be changed at some point. Mostly left as-is. I think we should consider a different solution to include keymasks and keep Key as an actual enum.
* Documentation and API dump updated to reflect bitfields in core types.

Fixes #64005.

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Looks good from a cursory view. Areas related to input handling likely benefit from real world testing still, to check for regressions.

File: core/variant/binder_common.h [hunk 1]
```diff
@@ -146,22 +146,53 @@ VARIANT_ENUM_CAST(Side);
...
+	return (Key)((int)a | (int)b.operator int64_t());
+}
+
+static inline Key operator&(Key a, BitField<KeyModifierMask> b) {
+	return (Key)((int)a & (int)b.operator int64_t());
+}
+
+static inline Key operator+(BitField<KeyModifierMask> a, Key b) {
+	return (Key)((int)a.operator int64_t() + (int)b);
+}
```
Comment (kleonc) [inline core/variant/binder_common.h:190]: Not sure why anyone would want to add a value to a bitfield like that.

Likely a typo and it was meant to be `operator&`? :thinking:
(there's no `operator&(BitField<KeyModifierMask> a, Key b)` added)

File: doc/classes/@GlobalScope.xml [hunk 2]
```diff
@@ -2376,20 +2376,18 @@
...
 			Middle mouse button mask.
 		</constant>
-		<constant name="MOUSE_BUTTON_MASK_XBUTTON1" value="128" enum="MouseButton">
-			Extra mouse button 1 mask.
+		<constant name="MOUSE_BUTTON_MASK_MB_XBUTTON1" value="128" enum="MouseButtonMask" is_bitfield="true">
 		</constant>
-		<constant name="MOUSE_BUTTON_MASK_XBUTTON2" value="256" enum="MouseButton">
-			Extra mouse button 2 mask.
+		<constant name="MOUSE_BUTTON_MASK_MB_XBUTTON2" value="256" enum="MouseButtonMask" is_bitfield="true">
 		</constant>
```
Comment (kleonc) [inline doc/classes/@GlobalScope.xml:2391]: Why were these descriptions removed?

File: core/variant/binder_common.h (hunk 1 above)
Comment (reduz) [reply core/variant/binder_common.h:190]: Its needed for compatibiltiy in some places of the code. At some point we just need to do away with all this and create a KeyWithModifier structure or something like that, since the Key enum is still illegal in a lot of languages.

File: doc/classes/@GlobalScope.xml (hunk 2 above)
Comment (reduz) [reply doc/classes/@GlobalScope.xml:2391]: Ah, this was by mistake because I had to rename them. I will add back.

File: editor/animation_track_editor.cpp [hunk 3]
```diff
@@ -5309,7 +5309,7 @@ void AnimationTrackEditor::_scroll_input(const Ref<InputEvent> &p_event) {
 	Ref<InputEventMouseMotion> mm = p_event;
 
 	if (mm.is_valid() && box_selecting) {
-		if ((mm->get_button_mask() & MouseButton::MASK_LEFT) == MouseButton::NONE) {
+		if (mm->get_button_mask().has_flag(MouseButtonMask::LEFT)) {
```
[the remark this answers is not in the document]
Comment (reduz) [reply editor/animation_track_editor.cpp:5312]: No, likely intended, I was sure I made this mistake somewhere but I could not find it, thanks for pointing it out!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by m4gr3d** [comment]
@reduz @akien-mga This PR breaks clicks on Android.

**Comment by akien-mga** [comment]
See #71101.
