### PR TITLE
Use the CanvasItemEditor info overlay to display TileMap coordinates

### LINKED ISSUE #28135: Tilemap Editor Changes Editor Scale on Small Screens Constantly
**Godot version:**
3.1 official stable

**OS/device including version:**
Windows 10 / Didn't test on any other platforms

**Issue description:**

When painting tiles in the TileMap node, if the window is small enough that not all the panels fit the screen, Godot editor scales all the panels constantly to fit the status label (the label that shows the coordinates and the tile name under the mouse cursor, check the gif below)

tilemap_scale_bug
Screenshot_5

**Steps to reproduce:**
* Create a TileMap, paint at least 2 tiles with different names
* Resize the window so it's small enough to not fit all the panels
* Hover your cursor over your tiles

### PR DESCRIPTION
**Pull request by Calinou**
This also removes the editor setting that toggles coordinate display, as it no longer solves an existing bug.

This closes #28135.

## Preview

Editor with new position for the tilemap coordinates

### CODE REVIEW

File: editor/plugins/tile_map_editor_plugin.cpp [hunk 1]
```diff
@@ -2055,7 +2047,12 @@ TileMapEditor::TileMapEditor(EditorNode *p_editor) {
 
 	// Tile position.
 	tile_info = memnew(Label);
-	toolbar_right->add_child(tile_info);
+	tile_info->set_modulate(Color(1, 1, 1, 0.8));
+	tile_info->set_mouse_filter(MOUSE_FILTER_IGNORE);
```
Comment (Calinou) [inline editor/plugins/tile_map_editor_plugin.cpp]: Not a critical issue, but I noticed that despite this flag, I still can't place tiles behind the label. This also occurs with the [`warning_child_of_container`](https://github.com/Calinou/godot/blob/13f98f80b62f736f36de8b75722901d8dd8311a7/editor/plugins/canvas_item_editor_plugin.cpp#L5354-L5359) info label.

Comment (homer666) [reply editor/plugins/tile_map_editor_plugin.cpp]: Dumb question, but have you tried `MOUSE_FILTER_PASS`?

Comment (Calinou) [reply editor/plugins/tile_map_editor_plugin.cpp]: @homer666 I have, but it still blocks mouse input behind the label.

**Comment by akien-mga** [comment]
Thanks!

File: editor/plugins/tile_map_editor_plugin.cpp (hunk 1 above)
Comment (YeldhamDev) [reply editor/plugins/tile_map_editor_plugin.cpp]: When using `add_control_to_info_overlay()`, it adds it to a `VBoxContainer`, could that be blocking the mouse?
https://github.com/godotengine/godot/blob/d422eff03604ff5ea10692e71c92f0d79a6d9355/editor/plugins/canvas_item_editor_plugin.cpp#L5185-L5191

Comment (Calinou) [reply editor/plugins/tile_map_editor_plugin.cpp]: @YeldhamDev Don't Containers have their mouse mode set to Pass (or Ignore) by default? I remember seeing this when I used Zylann's editor debuggeer plugin.
