### PR TITLE
GDScript arithmetic assignment type check bug fix

### LINKED ISSUE #40686: Arithmetic-assignment operators incorrectly set the type of the variable
**Godot version:** `master` after the GDScript "2.0" rewrite

**OS/device including version:** Ubuntu 20.04

**Issue description:**

```gdscript
	var test := Vector3()
	test *= 3 # Parse Error: Cannot assign a value of type "int" to a target of type "Vector3".
```

The above works in Godot 3.x, but is broken in the current master branch. However, the below works in the master branch:

```gdscript
	var test := Vector3()
	test = test * 3
```

**Steps to reproduce:** Copy the above code, and use the current master branch.

**Minimal reproduction project:** I'm going to not bother with one, this is a very simple bug.

### PR DESCRIPTION
**Pull request by ThakeeNathees**
Fix: #40686

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -1359,7 +1359,47 @@ void GDScriptAnalyzer::reduce_assignment(GDScriptParser::AssignmentNode *p_assig
...
+		case GDScriptParser::AssignmentNode::OP_BIT_OR:
+			vop = Variant::Operator::OP_BIT_OR;
+			break;
+		case GDScriptParser::AssignmentNode::OP_BIT_XOR:
+			vop = Variant::Operator::OP_BIT_XOR;
+			break;
+	}
+
+	bool compatible = false;
+	get_operation_type(vop, p_assignment->assignee->get_datatype(), p_assignment->assigned_value->get_datatype(), compatible);
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:1400]: `get_operation_type` won't check the assignment compatibility, only the operation. So if this is false the error should be that the operands have invalid type for the operation. Then we need to store the return value of `get_operation_type to test the assignment compatibility. Otherwise something like this would be valid:

```gdscript
var i := 3
i *= Vector2(1, 1)
```

**Review by vnen — CHANGES_REQUESTED** [review]

File: modules/gdscript/gdscript_analyzer.cpp (hunk 1 above)
Comment (ThakeeNathees) [reply modules/gdscript/gdscript_analyzer.cpp]: @vnen fixed!

Comment (ThakeeNathees) [reply modules/gdscript/gdscript_analyzer.cpp]: Fixed with 2 different errors cases

```gdscript
int_val *= Vector2()
# Cannot assign a value of type "Vector2" to a target of type "int"
```

```gdscript
int_val *= String()
# Invalid operands "int" and "String" for assignment operator.
```

File: modules/gdscript/gdscript_analyzer.cpp [hunk 2]
```diff
@@ -1359,12 +1359,56 @@ void GDScriptAnalyzer::reduce_assignment(GDScriptParser::AssignmentNode *p_assig
...
+		case GDScriptParser::AssignmentNode::OP_BIT_OR:
+			vop = Variant::Operator::OP_BIT_OR;
+			break;
+		case GDScriptParser::AssignmentNode::OP_BIT_XOR:
+			vop = Variant::Operator::OP_BIT_XOR;
+			break;
+	}
+
+	bool compatible = false;
+	GDScriptParser::DataType op_type = get_operation_type(vop, p_assignment->assignee->get_datatype(), p_assignment->assigned_value->get_datatype(), compatible);
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:1400]: Actually, I don't think it's a good idea to call this when there's no operator (just `x = y`). In this case you are testing with `OP_EQUAL` but that is the equality test operator so it always returns a boolean. I think `op_type` should be the assigned value by default and only if only if there's an operation it should call `get_operation_type()`.

**Review by vnen — CHANGES_REQUESTED** [review]

File: modules/gdscript/gdscript_analyzer.cpp (hunk 2 above)
Comment (ThakeeNathees) [reply modules/gdscript/gdscript_analyzer.cpp]: done!

**Review by vnen — APPROVED** [review]

**Comment by vnen** [comment]
Thanks!
