### PR TITLE
Skip `script` property in remote object property list

### LINKED ISSUE #51077: The Script property appears doubled in the Remote inspector
### Godot version

v3.4.beta2.official

### System information

Windows 10

### Issue description

The script property doubles in the inspector when running the app and selecting 'remote'. Is present on all nodes, in every project, in a new project, after clearing the cache at User/AppData/Roaming/Godot/Projects.

script_doubling_3_4_LI

### Steps to reproduce

Create a new, simple, runnable project. Run it and go to the 'Remote tab'. Select any node. In the inspector, the 'script' property is doubled. Occurs both in 3.3.2 and 3.4.beta2.official.

### Minimal reproduction project

[Test_3_4.zip](https://github.com/godotengine/godot/files/6909171/Test_3_4.zip)

### PR DESCRIPTION
**Pull request by raulsntos**
Closes #51077

Since the `Object::get_property_list` method always adds the `script` property, skipping it in the virtual implementation to avoid duplicating the property.

This is option 1 described in https://github.com/godotengine/godot/issues/51077#issuecomment-984028025.

### CODE REVIEW

File: editor/debugger/editor_debugger_inspector.cpp [hunk 1]
```diff
@@ -55,9 +55,14 @@ bool EditorDebuggerRemoteObject::_get(const StringName &p_name, Variant &r_ret)
 }
 
 void EditorDebuggerRemoteObject::_get_property_list(List<PropertyInfo> *p_list) const {
-	p_list->clear(); //sorry, no want category
-	for (const PropertyInfo &E : prop_list) {
-		p_list->push_back(E);
+	p_list->clear(); // Sorry, no want category.
```
Comment (akien-mga) [inline editor/debugger/editor_debugger_inspector.cpp:58]: Not sure what this comment means, beside the bad grammar :)

Comment (raulsntos) [reply editor/debugger/editor_debugger_inspector.cpp:58]: It seems to be clearing the list to get rid of any PropertyInfo with `PROPERTY_USAGE_GROUP` so the properties that get added to the list are not grouped in a category.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
