### PR TITLE
Fix GridMap free navigation RID error spam

### LINKED ISSUE #74429: gridmap spamming thousands of errors
### Godot version

4 stable

### System information

Windows 10

### Issue description

getting this error hundreds of times if I just paint anywhere for 1 second with Gridmap
`modules/navigation/godot_navigation_server.cpp:760 - Condition ""Attempted to free a NavigationServer RID that did not exist (or was already freed)."" is true.`

image

### Steps to reproduce

It happened (I think) after I cleared a baked navigation mesh, but not sure.

### Minimal reproduction project

n/a

### PR DESCRIPTION
**Pull request by smix8**
Fixes GridMap free navigation RID error spam.

Fixes https://github.com/godotengine/godot/issues/74429

### CODE REVIEW

**Review by DarkKilauea — APPROVED** [review]

File: modules/gridmap/grid_map.cpp [hunk 1]
```diff
@@ -557,8 +557,11 @@ bool GridMap::_octant_update(const OctantKey &p_key) {
...
 	//erase navigation
-	for (const KeyValue<IndexKey, Octant::NavigationCell> &E : g.navigation_cell_ids) {
-		NavigationServer3D::get_singleton()->free(E.value.region);
+	for (KeyValue<IndexKey, Octant::NavigationCell> &E : g.navigation_cell_ids) {
+		if (E.value.region.is_valid()) {
+			NavigationServer3D::get_singleton()->free(E.value.region);
+			E.value.region = RID();
+		}
 		if (E.value.navigation_mesh_debug_instance.is_valid()) {
 			RS::get_singleton()->free(E.value.navigation_mesh_debug_instance);
```
Comment (YuriSizov) [inline modules/gridmap/grid_map.cpp:566]: Should we reset the RID here as well? It seems that's what we do in `_octant_exit_world`.

Comment (smix8) [reply modules/gridmap/grid_map.cpp:566]: Yes properly should as `_octant_update()` seems to be a function prone to be called again while the RID is still not freed.

**Review by YuriSizov — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!
