### PR TITLE
Fix TextEdit Shift+Click selection start position

### LINKED ISSUE #114738: `Shift + Click` to select words is broken
### Tested versions

- Reproducible in v4.6.beta3.official [76dda5c6c]
- Reproducible in v4.6.beta2.official [551ce8d47]
- Reproducible in v4.6.beta1.official [d743736f8]
- Reproducible in v4.6.dev6.official [dec5a373d]
- Reproducible in v4.6.dev5.official [f5918a9d3]
- Reproducible in v4.6.dev4.official [bd2ca13c6]
- Not reproducible in v4.6.dev3.official [9d84f3d13]
- Not reproducible in v4.5.1.stable.official [f62fdbde1]

### System information

v4.6.beta3.official [76dda5c6c]

### Issue description

Regression in v4.6.dev4.official [bd2ca13c6].

Word selection does not start from the blinking cursor position after a jump.

https://github.com/user-attachments/assets/3d436df3-40e0-44dd-b826-cfa41d819723

### Steps to reproduce

1. ctrl+click to find a symbol or a function 
2. shift+click to select some words

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by kitbdev**
- Fixes https://github.com/godotengine/godot/issues/114738

There were 2 issues here.
On symbol lookup click in CodeEdit, the mouse released event never makes it to TextEdit, so the logic that changes the selection mode in https://github.com/godotengine/godot/pull/111535 never gets hit.
Moving the caret with the arrow keys or directly with the function never updated the word column, which is now needed.

The symbol lookup now falls through to TextEdit.
The word beg/end columns are now set when the selection origin is updated, which includes `select()`, so it should always be updated by the time they are used in `_update_selection_mode_pointer`. This also covers ones from `_pre_shift_selection` that I removed.

Added a few tests, and made the tests in this test case always send a mouse release event to be more accurate to expected behavior.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Review by bruvzg — APPROVED** [review]

File: scene/gui/code_edit.cpp [hunk 1]
```diff
@@ -459,7 +459,6 @@ void CodeEdit::gui_input(const Ref<InputEvent> &p_gui_input) {
 					if (line != -1) {
 						emit_signal(SNAME("symbol_lookup"), symbol_lookup_word, line, col);
 					}
-					return;
```
Comment (bruvzg) [inline scene/gui/code_edit.cpp:462]: Might be worth adding a comment here, to avoid accidentally reverting this in the future.
