### PR TITLE
Use correct screen-space to ndc equation in Compatibility refraction

### LINKED ISSUE #106213: Refraction is broken in Compatibility renderer
### Tested versions

I use 4.4.1 stable.

### System information

Arch Linux

### Issue description

There is no refraction.

one thing I think might be an issue is that the screen texture doesnt have mipmaps, but thats not all...

### Steps to reproduce

Have a scene with one mesh with standard material, enable refraction and set albedo alpha to 0.3.

### Minimal reproduction project (MRP)

currently I dont have one but should be easy to reproduce.

### PR DESCRIPTION
**Pull request by Kaleb-Reid**
Converting from screen-space coordinates to ndcs use a different equation in OpenGL as compared to Vulkan. This incorrect equation breaks refraction in Compatibility.

Closes https://github.com/godotengine/godot/issues/106213

### CODE REVIEW

**Review by Calinou — COMMENTED** [review]
Using `RS::get_singleton()->is_low_end()` will change the created code depending on the current rendering driver, which means that if you convert a BaseMaterial3D to a ShaderMaterial while using Compatibility, it will break on Forward+/Mobile and vice versa. This is an issue if you switch rendering methods during development, or even if an automatic fallback is applied on the user's device.

We should use the shader preprocessor instead, but it's currently broken when used in BaseMaterial3D (as I mentioned in https://github.com/godotengine/godot/issues/87486#issuecomment-2663688834).

**Comment by Kaleb-Reid** [comment]
@Calinou Ah yes forgot about that. Unfortunately I don't think the shader preprocessor is ran for materials as they call ```RS::shader_create_from_code``` directly, which does not run the preprocessor as apposed to calling ```Shader::set_code``` which does and then calls ```RS::shader_create_from_code``` internally.

The way I am thinking of working around this would be:
 - Move code responsible for generating the shader to it's own function that can be called when converting to shader material / sending to RenderingServer.
 - Calling preprocessor manually in material.cpp before sending to RenderingServer.

Unsure if this is the best solution though.

**Comment by Kaleb-Reid** [comment]
~~Alright so I've added a method to BaseMaterial3D which generates the shader code including the preprocessor directives so that when you press "Convert to ShaderMaterial" in the editor, instead of dumping the already processed shader code from RenderingServer, it generates new shader code with the directives still in it. The method is just code which used to be inside ```BaseMaterial3D::_update_shader```, but with the updated fix for refraction. The shader code is also now preprocessed inside  ```BaseMaterial3D::_update_shader```.~~

~~I didn't add this to any of the other material types, but I can if it makes sense. If I need to then I could just make another pr which adds this method to all of the materials and remove it from this one.~~

EDIT: Went with clayjohn's solution of using ```OUTPUT_IS_SRGB``` instead to determine if Compatibility is being used.

File: scene/resources/material.cpp [hunk 1]
```diff
@@ -1813,7 +1850,11 @@ void fragment() {)";
 	float ref_amount = 1.0 - albedo.a * albedo_tex.a;
 
 	float refraction_depth_tex = textureLod(depth_texture, ref_ofs, 0.0).r;
+#if CURRENT_RENDERER == RENDERER_COMPATIBILITY
```
Comment (clayjohn) [inline scene/resources/material.cpp]: Instead of use the GDShader preprocessor. You can just use `OUTPUT_IS_SRGB` which is always `true` for the compatibility renderer and false otherwise. I.e.

```
if (OUTPUT_IS_SRGB) {
	vec4 refraction_view_pos = INV_PROJECTION_MATRIX * vec4(vec3(SCREEN_UV, refraction_depth_tex) * 2.0 - 1.0, 1.0);
} else {
	vec4 refraction_view_pos = INV_PROJECTION_MATRIX * vec4(SCREEN_UV * 2.0 - 1.0, refraction_depth_tex, 1.0);
}
```
This lets you avoid any issues with the preprocessor and converting to shader material. You can also check the value of `CLIP_SPACE_FAR` to do the same thing effectively.

**Review by clayjohn — CHANGES_REQUESTED** [review]

File: scene/resources/material.cpp (hunk 1 above)
Comment (Kaleb-Reid) [reply scene/resources/material.cpp]: Well that makes it a lot simpler, thanks. I saw on another issue or pr mentioning the preprocessor that this constant exists and you can currently use it to tell if you are using Compatibility but I wasn't sure if we are allowed to assume that this won't change.

**Review by clayjohn — APPROVED** [review]
Nice work!

**Comment by Repiteo** [comment]
Thanks!
