### PR TITLE
Fix `ColorPicker` virtual keyboard popup on mobile

### LINKED ISSUE #88235: Color Picker on Mobile causes keyboard to popup by default
### Tested versions

v4.3.dev2.official [352434668], likely has existed for longer.

### System information

Pixel 6a Android

### Issue description

When clicking on the color picker button it by default brings up the onscreen keyboard. Likely because the 'Hex' field is active by default.

Why is this a bug? See below:
Screenshot_20240212-173731

Setting hex_visible to false does not work around the issue.

### Steps to reproduce

Add a ColorPickerButton node.
Click it.

### Minimal reproduction project (MRP)

Am not near computer, but can MRP if required later.

### PR DESCRIPTION
**Pull request by syntaxerror247**
This PR fixes auto popup of virtual keyboard when colorPickerButton is pressed on mobile devices.
Fixes #88235

### CODE REVIEW

File: scene/gui/color_picker.cpp [hunk 1]
```diff
@@ -2089,7 +2089,9 @@ void ColorPickerButton::pressed() {
 	float v_offset = show_above ? -minsize.y : get_size().y;
 	popup->set_position(get_screen_position() + Vector2(h_offset, v_offset));
 	popup->popup();
-	picker->set_focus_on_line_edit();
+	if DisplayServer::get_singleton()->has_hardware_keyboard() {
```
Comment (WhalesState) [inline scene/gui/color_picker.cpp:2092]: if (DisplayServer::get_singleton()->has_hardware_keyboard()) {

Comment (syntaxerror247) [reply scene/gui/color_picker.cpp:2092]: Yeah I know, I am not able to push my changes due to some internet issues 😅

Comment (WhalesState) [reply scene/gui/color_picker.cpp:2092]: I have used this.
```cpp
void ColorPicker::set_focus_on_line_edit() {
	bool has_hardware_keyboard = true;
#if defined(ANDROID_ENABLED) || defined(IOS_ENABLED)
	has_hardware_keyboard = DisplayServer::get_singleton()->has_hardware_keyboard();
#endif // ANDROID_ENABLED || IOS_ENABLED
	if (has_hardware_keyboard) {
		callable_mp((Control *)c_text, &Control::grab_focus).call_deferred();
	} else {
		// A hack to avoid showing the virtual keyboard when the ColorPicker window popups and
		// no hardware keyboard is detected on Android and IOS.
		// This will only focus the LineEdit without editing, the virtual keyboard will only be visible when
		// we touch the LineEdit to enter edit mode.
		callable_mp(c_text, &LineEdit::set_editable).call_deferred(false);
		callable_mp((Control *)c_text, &Control::grab_focus).call_deferred();
		callable_mp(c_text, &LineEdit::set_editable).call_deferred(true);
	}
}
```

The only difference is that i have preserved the focus. I don't know which one is accurate but it's better to remove this fix from my pull request since it's not related.

Comment (syntaxerror247) [reply scene/gui/color_picker.cpp]: After battling rebase and internet issues, i have finally pushed my changes.

**Comment by WhalesState** [comment]
It looks good but I don't know if we should return from `TextEdit` and `LineEdit` `show_virtual_keyboard` instead, to avoid showing the virtual keyboard when a physical keyboard is detected, at least we can do it for android and ios only but what if the users still wants to use the virtual keyboard ? There's no option to show virtual keyboard over physical one.

**Comment by WhalesState** [comment]
> @WhalesState Isn't this the current behaviour, virtual keyboard does not appear if physical keyboard is connected.

There was no way to check for physical keyboards before, it was recently merged so it always show the virtual keyboard on android and ios by default.

**Comment by WhalesState** [comment]
That's why i have applied a hack for this, since focusing any `LineEdit` or `TextEdit` will still show the virtual keyboard even if a hardware keyboard is connected, but I don't know if there are any opened issues or discussions about this.

**Comment by syntaxerror247** [comment]
> There was no way to check for physical keyboards before, it was recently merged so it always show the virtual keyboard on android and ios by default.

No, virtual keyboard doesn't appear if physical kb is connected even before that PR . This was used internally just wasn't exposed.

**Comment by WhalesState** [comment]
There's an option on android `Physical keyboard` settings `Show on-screen keyboard` while a physical keyboard is being used, which is true by default.

**Comment by syntaxerror247** [comment]
> There's an option on android `Physical keyboard` settings `Show on-screen keyboard` while a physical keyboard is being used, which is true by default.

I just checked in two different devices and it was turned off in Motorola and turned on in Xiaomi, both are default.

**Review by WhalesState — APPROVED** [review]

**Comment by KoBeWi** [comment]
The linked issue was closed by another PR. Is this still relevant?

**Comment by syntaxerror247** [comment]
> The linked issue was closed by another PR. Is this still relevant?

Yes, this fix is simpler and IMO better.
I think the only difference is that, fix in that PR hides virtual keyboard but still keep html_color box focused, But I think completely removing the focus would be better.

It would be great if you could have a look yourself 🙂

**Review by KoBeWi — APPROVED** [review]
This basically reverts the ColorPicker part of #97094 idk why that code was merged if the author of that PR has approved this one 🤷‍♂️

The code looks ok, but I didn't test it on mobile.

**Comment by WhalesState** [comment]
I've approved this PR since it was submitted after my own fix and my PR was approved but not merged yet. However, I do have some questions about the approach taken here.

I'm not sure why this fix was submitted as a separate PR instead of being discussed in my original PR, where the issue was already being tracked and addressed.

Regarding the fix itself, I agree that it's simpler. However, I do have some concerns about its accuracy. Specifically, every popup should focus on at least one control.

Also to avoid potential regressions on other platforms when `has_hardware_keyboard()` is supported, I made sure to apply the changes only to Android and iOS.

I'm not familiar enough with the underlying mechanics to provide a definitive opinion on which fix is better. I'd be happy to let more experienced team members weigh in and provide guidance on the best approach.

**Comment by syntaxerror247** [comment]
> I'm not sure why this fix was submitted as a separate PR instead of being discussed in my original PR, where the issue was already being tracked and addressed.

That PR was already addressing multiple issues, so I thought it would be better to open a new one. ( I accept that was an error an my part)

> Regarding the fix itself, I agree that it's simpler. However, I do have some concerns about its accuracy. Specifically, every popup should focus on at least one control.

This fix won't even create a popup or try to open virtual keyboard, if hardware keyboard is not connected. It will only focus the lineEdit if hardware keyboard is connected or specifically clicked on it.

> Also to avoid potential regressions on other platforms when has_hardware_keyboard() is supported, I made sure to apply the changes only to Android and iOS.

This fix won't affect any other platform because [has_hardware_keyboard()](https://docs.godotengine.org/en/latest/classes/class_displayserver.html#class-displayserver-method-has-hardware-keyboard) will always return true on any other platform. And if this func gets supported on other platforms then it should work there too.

I hope all the question are answered :)

**Review by m4gr3d — APPROVED** [review]
The code and the reasoning looks good to me!

**Comment by Repiteo** [comment]
Thanks!
