### PR TITLE
[Accessibility] Process non-focusable windows (popups, menus) as part of the parent window tree.

### LINKED ISSUE #106669: Accesskit crash in single window mode
### Tested versions

- Reproducible in 4.5 dev3 and dev4
- Not reproducible 4.5 dev2 and earlier

### System information

Godot v4.5.dev4 - Ubuntu 22.04.5 LTS 22.04 on X11 - X11 display driver, Single-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (nvidia; 535.247.01) - AMD Ryzen 3 3200G with Radeon Vega Graphics (4 threads)

### Issue description

Accesskit panics every time a menu opens, for example the items in the main menu or the extra scenes options button. It does not happen for context menus or choosing a rendering method. Opening windows works, I was able to use the command palette to open editor settings.

The crash only happens in single window mode.

The following console output is generated. I have set `RUST_BACKTRACE` to full, but it does not offer much information.

```
Godot Engine v4.5.dev4.mono.official.209a446e3 - https://godotengine.org
Vulkan 1.3.242 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce GTX 1050 Ti


thread '<unnamed>' panicked at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/accesskit_consumer-0.27.0/src/iterators.rs:406:45:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:          0x4ec60e2 - <unknown>
   1:          0x4eac9a3 - <unknown>
   2:          0x4ec5982 - <unknown>
   3:          0x4ec5df3 - <unknown>
   4:          0x4ec578d - <unknown>
   5:          0x4ef3e95 - <unknown>
   6:          0x4ef3e29 - <unknown>
   7:          0x4ef42cc - <unknown>
   8:           0x42683f - <unknown>
   9:           0x42688b - <unknown>
  10:           0x426b48 - <unknown>
  11:          0x4e154f8 - <unknown>
  12:          0x4e19094 - <unknown>
  13:          0x4e16158 - <unknown>
  14:          0x4e10ade - <unknown>
  15:          0x1576ee2 - <unknown>
  16:          0x28345f6 - <unknown>
  17:           0x5342d9 - <unknown>
  18:           0x42d0f9 - <unknown>
  19:     0x7f7c03d59d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  20:     0x7f7c03d59e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  21:           0x463cfa - <unknown>
  22:                0x0 - <unknown>
```

### Steps to reproduce

  1. Create an empty project
  2. Enable single window mode in editor settings
  3. Click on the scene button in the main menu 

No other editor settings can be the cause of this crash, as I have deleted all my editor settings files and reproduced the issue this way.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/106433
Fixes https://github.com/godotengine/godot/issues/106669

### CODE REVIEW

File: scene/main/window.cpp [hunk 1]
```diff
@@ -1371,10 +1374,10 @@ Viewport *Window::get_embedder() const {
 }
 
 RID Window::get_accessibility_element() const {
-	if (is_part_of_edited_scene()) {
+	if (is_part_of_edited_scene() || !visible) {
```
Comment (AThousandShips) [inline scene/main/window.cpp]:
```suggestion
	if (!visible || is_part_of_edited_scene()) {
```
Unless there's some specific reason to do `is_part_of_edited_scene` first

**Comment by clayjohn** [comment]
CC @lawnjelly Do you mind testing this out since you were able to reproduce the crash?

**Comment by lawnjelly** [comment]
Sorry I must have missed this last week, I've had a go but it's proving very difficult to test so far.

I can confirm that the crash happens on the official build of 4.5 dev 5 (when accesskit is not set to disabled in the editor settings). _However_, although I previously noticed the crash didn't happen in dev builds, on testing further, it doesn't happen for me on locally built release builds _either_.

I first checked this with current master, then rebuilt with the commit for 4.5 dev 5, and sure enough no crash with the local build. So there appears something special about the official build that is triggering the crash (maybe it isn't building in the accesskit stuff in my local builds for some reason?).

I also can't test the mono builds from the linux artifacts currently as I don't have all the .NET stuff installed (I tend to test the windows builds under WINE for this reason, which wouldn't be super helpful in this case, and can confirm the WINE build runs fine).

**Comment by bruvzg** [comment]
> So there appears something special about the official build that is triggering the crash (maybe it isn't building in the accesskit stuff in my local builds for some reason?).

You need prebuilt static libraries from https://github.com/godotengine/godot-accesskit-c-static/releases and `accesskit_sdk_path={PATH_EXTRACTED_ARCHIVE}` SCons flag to build with AccessKit enabled.

**Comment by lawnjelly** [comment]
> You need prebuilt static libraries from https://github.com/godotengine/godot-accesskit-c-static/releases and accesskit_sdk_path={PATH_EXTRACTED_ARCHIVE} SCons flag to build with AccessKit enabled.

Great! Have compiled this in and now crashing with master with the DEV build too, so I should be able to test the PR. Will report back.

**Comment by bruvzg** [comment]
While you are testing it, please also check if it's crashing with this branch - https://github.com/bruvzg/godot/tree/atspi_check (not related to the issues directly, but might improve screen reader detection, and crashing code should not run without screen reader active at all).

**Comment by lawnjelly** [comment]
Good news, as far as I can see this PR *does* fix the crash I was getting on opening the menus.

UPDATE: The `atscpi_check` branch does _not_ fix the crash. Have to go out now, can do more testing later if required.

File: scene/main/node.cpp [hunk 2]
```diff
@@ -2055,6 +2055,14 @@ Window *Node::get_window() const {
 	return nullptr;
 }
 
+Window *Node::get_non_popup_window() const {
+	Window *w = get_window();
+	while (w && (w->get_flag(Window::FLAG_POPUP) || w->get_flag(Window::FLAG_NO_FOCUS))) {
```
Comment (KoBeWi) [inline scene/main/node.cpp]: Seeing the flag checks repeated multiple times, there could be a helper method `is_popup()` to check that.

**Review by KoBeWi — APPROVED** [review]
I can't reproduce the issue on Windows, but I tested that this doesn't break anything at least.
Code looks fine.

**Comment by tomsterBG** [comment]
Can confirm 4.5 beta5 was broken and this fixes it for my issue https://github.com/godotengine/godot/issues/106433

**Comment by Repiteo** [comment]
Thanks!
