### PR TITLE
Fix default_cursor_shape for TextEdit

### LINKED ISSUE #20296: TextEdit not showing typed text and error on scrolling/typing
**Godot version:**
Tried with:
v3.1.dev.custom_build.b2d7641
v3.1.dev.custom_build.43dc050
v3.1.dev.custom_build.911febb

Every time that I will use Godot I make a build

**OS/device including version:**
Windows 10 Pro
GeForce GTX 1080/PCIe/SSE2

**Issue description:**
Can't use the TextEdit properly.
It was supposed to show the text that I type or the text on _Text_ property

**Steps to reproduce:**
Create a blank project, place a root node (I tried with _Node_ or _Control_), create a TextEdit child node and run the project.
With the TextEdit on focus, scroll down and then "scroll more" to get the first debug errors
Typing after that scroll does trigger the error too.

Error:
> 0:00:04:0295 - Index line=3 out of size (text.size()=3)
> Type:Error Description: Time: 0:00:04:0295 C Error: Index line=3 out of size (text.size()=3) C Source: 
> scene\gui\text_edit.cpp:3731 C Function: TextEdit::times_line_wraps

**Minimal reproduction project:**
[TextEditTest.zip](https://github.com/godotengine/godot/files/2212381/TextEditTest.zip)

[Video of the problem](https://www.youtube.com/watch?v=44m4fBDgN_0)

### PR DESCRIPTION
**Pull request by guilhermefelipecgs**
~Also fix #20296. If users change anchor bottom to zero (END) this error will come back again. Maybe we still need this pr #21219 as a fallback (I didn't test it to know if is really a fallback, just guessing) or another solution should be created.~

### CODE REVIEW

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -4174,7 +4174,7 @@ Control::CursorShape TextEdit::get_cursor_shape(const Point2 &p_pos) const {
 		}
 	}
 
-	return CURSOR_IBEAM;
+	return Control::get_default_cursor_shape();
```
Comment (akien-mga) [inline scene/gui/text_edit.cpp]: Is the `Control::` scope useful here? We inherit it so it's directly available.

**Comment by akien-mga** [comment]
I merged #21219 as @reduz says it's still necessary to remove the caching of `get_size` in TextEdit. Is the `set_anchor(MARGIN_BOTTOM, ANCHOR_END);` still relevant after that?

**Comment by guilhermefelipecgs** [comment]
Let me check here.

File: scene/gui/text_edit.cpp (hunk 1 above)
Comment (guilhermefelipecgs) [reply scene/gui/text_edit.cpp]: You're right, I was thinking that get_default_cursor_shape was overwrited in this class but it wasn't.

**Comment by guilhermefelipecgs** [comment]
> I merged #21219 as @reduz says it's still necessary to remove the caching of `get_size` in TextEdit. Is the `set_anchor(MARGIN_BOTTOM, ANCHOR_END);` still relevant after that?

This is not relevant anymore.

**Comment by akien-mga** [comment]
Thanks!
