### PR TITLE
Fixes some AnimationPlayer bugs

### LINKED ISSUE #17423: Stop method of AnimationPlayer clears the animation
Related to Godot 3.0.

Look at the documentation of `stop` method of `AnimationPlayer`.
 
It looks that it was the intention that when the [`reset`](http://docs.godotengine.org/en/3.0/classes/class_animationplayer.html#stop) parameter is set to false, then the method would act as a pause.

> Stop the currently playing animation. If reset is true, the anim position is reset to 0.

Setting `reset` to `false` does preserve the position of the animation but the issue here is that it clears the animation itself. 

```
	print("* Initial values")
	print("animation: ", $PlayerAnimation.current_animation)
	print("position: ", $PlayerAnimation.current_animation_position)

	$PlayerAnimation.play("walk_up")
	$PlayerAnimation.seek(3.14)
	
	print("* After play+seek")
	print("animation: ", $PlayerAnimation.current_animation)
	print("position: ", $PlayerAnimation.current_animation_position)
	
	$PlayerAnimation.stop(false)

	print("* After stop")
	print("animation: ", $PlayerAnimation.current_animation)
	print("position: ", $PlayerAnimation.current_animation_position)
	
	$PlayerAnimation.play("walk_up")
	
	print("* After another play")
	print("animation: ", $PlayerAnimation.current_animation)
	print("position: ", $PlayerAnimation.current_animation_position)
```

Output:

```
* Initial values
0
* After play+seek
3.14
walk_up
* After stop
3.14
* After another play
animation: walk_up
position: 0
```

I don't think, there is any other no built-in way to pause an animation, but there is an easy workaround:

```
var last_anim_pos = 0.0
var last_anim = null

func pause_animation():
	last_anim_pos = $PlayerAnimation.current_animation_position
	last_anim = $PlayerAnimation.current_animation
	$PlayerAnimation.stop()

func continue_animation():
	$PlayerAnimation.play(last_anim)
	$PlayerAnimation.seek(last_anim_pos)
```

### LINKED ISSUE #25745: animation_finished giving empty String as argument after calling play() method
**Godot version:**
v3.1 Beta 3

**OS/device including version:**
Linux

**Issue description:**
This code:
image

Results in this output:
image

Actually, the `stop()` method doesn't interfere. When I tried this:

image

The same happened. The problem seems to be with the `play()` method when called again without arguments. If you call it with the animation name it works fine for the signal.

Also, calling `play()` will reset the animation position to 0 regardless of the argument of `stop()` so this issue might be related to  #17423. Example:

image

Prints 0.5 and 0 respectively.

**Minimal reproduction project:**
[animation_player_bugs.zip](https://github.com/godotengine/godot/files/2848177/animation_player_bugs.zip)

### PR DESCRIPTION
**Pull request by luizcarlos1405**
Fixes #25745 
Fixes #17423

Line _1210_ from animation_player.cpp is:
https://github.com/godotengine/godot/blob/eda4be193fd736d362184bc937efc99c1faa18c3/scene/animation/animation_player.cpp#L1210

Which means that when called without arguments the method would replace the variable `playback.assigned` with an empty String. This makes the signal `animation_finished` give this empty String as an argument.

I've changed it to
https://github.com/godotengine/godot/blob/592d514380eabfc9d36c68b44f263513e823c35b/scene/animation/animation_player.cpp#L1210

The variable `name` in this method has the correct animation name as defined at the beginning of it. This fixes  #25745.

The line _1208_:
https://github.com/godotengine/godot/blob/eda4be193fd736d362184bc937efc99c1faa18c3/scene/animation/animation_player.cpp#L1208

Doesn't have any condition to run, so it resets the position of the animation to 0 every time p_from_end is false. Also, calling `stop(true)` doesn't reset the animation. This PR makes the animation position be 0 when calling `stop(true)` 
https://github.com/godotengine/godot/blob/592d514380eabfc9d36c68b44f263513e823c35b/scene/animation/animation_player.cpp#L1281-L1294

and replaces line _1208_ with
https://github.com/godotengine/godot/blob/592d514380eabfc9d36c68b44f263513e823c35b/scene/animation/animation_player.cpp#L1208

The animation position is reset, or not, at the `stop()` method, so the `play()` method just keeps the decision made there (unless it is told to run the animation backwards), fixing #17423.

### CODE REVIEW

File: scene/animation/animation_player.cpp [hunk 1]
```diff
@@ -1205,9 +1205,9 @@ void AnimationPlayer::play(const StringName &p_name, float p_custom_blend, float
 	_stop_playing_caches();
 
 	c.current.from = &animation_set[name];
-	c.current.pos = p_from_end ? c.current.from->animation->get_length() : 0;
+	c.current.pos = p_from_end ? c.current.from->animation->get_length() : c.current.pos;
```
Comment (akien-mga) [inline scene/animation/animation_player.cpp]: I think it would be more clearer to do:
```
if (p_from_end) {
	c.current.pos = c.current.from->animation->get_length();
}
```
if the `else` branch is meant not to do any change.

Comment (luizcarlos1405) [reply scene/animation/animation_player.cpp]: Agreed, will do it in a sec

Comment (luizcarlos1405) [reply scene/animation/animation_player.cpp]: Changed:

https://github.com/luizcarlos1405/godot/blob/9a2121cf9ce5ba899f5a6537bf5efe84aa91540b/scene/animation/animation_player.cpp#L1207-L1209

File: scene/animation/animation_player.cpp [hunk 2]
```diff
@@ -1203,11 +1203,14 @@ void AnimationPlayer::play(const StringName &p_name, float p_custom_blend, float
 	}
 
 	_stop_playing_caches();
-
+	
+	if (p_from_end) {
+		c.current.pos = c.current.from->animation->get_length();
```
Comment (akien-mga) [inline scene/animation/animation_player.cpp]: That's wrong, it has to stay where it was, here you're accessing `c.current.from` before it has been modified.

Comment (akien-mga) [reply scene/animation/animation_player.cpp]: Please squash commits together when fixing it :)

File: scene/animation/animation_player.cpp [hunk 3]
```diff
@@ -1203,11 +1203,15 @@ void AnimationPlayer::play(const StringName &p_name, float p_custom_blend, float
 	}
 
 	_stop_playing_caches();
-
+
```
Comment (akien-mga) [inline scene/animation/animation_player.cpp]: There's now a trailing tab here that should be removed.

File: scene/animation/animation_player.cpp (hunk 2 above)
Comment (luizcarlos1405) [reply scene/animation/animation_player.cpp]: I think now it is right. First-time _pull requesting_.

File: scene/animation/animation_player.cpp (hunk 3 above)
Comment (luizcarlos1405) [reply scene/animation/animation_player.cpp]: Removed.

File: scene/animation/animation_player.cpp [hunk 4]
```diff
@@ -1205,9 +1205,13 @@ void AnimationPlayer::play(const StringName &p_name, float p_custom_blend, float
 	_stop_playing_caches();
 
 	c.current.from = &animation_set[name];
-	c.current.pos = p_from_end ? c.current.from->animation->get_length() : 0;
+
+	if (p_from_end) {
+		c.current.pos = c.current.from->animation->get_length();
```
Comment (akien-mga) [inline scene/animation/animation_player.cpp]: Thanks, the style is good now :)

Now regarding the logic, I wonder if this is correct though. If you use `play()` to play a different animation than the current one, won't that imply that it will stay at the position where the previous animation was? If so that would likely not be the expected outcome, it should start the new animation at 0.

Comment (luizcarlos1405) [reply scene/animation/animation_player.cpp]: I see. What about doing this:

Line 1153
```suggestion
        if (String(name) == "")
	        name = playback.assigned;
	else
                playback.current.pos = 0;
```

This way the logic for passing or not the name stays on top of the method and is easily spotted.

File: scene/animation/animation_player.cpp [hunk 5]
```diff
@@ -1152,6 +1152,8 @@ void AnimationPlayer::play(const StringName &p_name, float p_custom_blend, float
 
 	if (String(name) == "")
 		name = playback.assigned;
+	else
+		playback.current.pos = 0;
```
Comment (akien-mga) [inline scene/animation/animation_player.cpp]: This is problematic, as it would reset the animation if you call `play()` with the name of the currently assigned animation. IMO it should only force reset if `name != playback.assigned`.

I also think this shouldn't be changed here, but below on the `c` variable, as done until now. (See other comment.)

File: scene/animation/animation_player.cpp [hunk 6]
```diff
@@ -1205,9 +1207,13 @@ void AnimationPlayer::play(const StringName &p_name, float p_custom_blend, float
 	_stop_playing_caches();
 
 	c.current.from = &animation_set[name];
-	c.current.pos = p_from_end ? c.current.from->animation->get_length() : 0;
+
+	if (p_from_end) {
```
Comment (akien-mga) [inline scene/animation/animation_player.cpp]: I'd do this instead:
```cpp
if (c.assigned != name) { // reset
	c.current.pos = p_from_end ? c.current.from->animation->get_length() : 0;
}
```
This was it even allows resuming an animation which was playing backwards and was stop without reset.

Comment (luizcarlos1405) [reply scene/animation/animation_player.cpp]: Agreed, just did it.

File: scene/animation/animation_player.cpp [hunk 7]
```diff
@@ -1205,9 +1205,13 @@ void AnimationPlayer::play(const StringName &p_name, float p_custom_blend, float
 	_stop_playing_caches();
 
 	c.current.from = &animation_set[name];
-	c.current.pos = p_from_end ? c.current.from->animation->get_length() : 0;
+
+	if (c.assigned != name) { // reset
```
Comment (akien-mga) [inline scene/animation/animation_player.cpp]: Thought some more about this, and there would still be one problematic case with this change I proposed. It makes it quite hard to reset a backward-playing animation, since `stop(true)` will reset it to 0, and `play_backwards()` or `play_backwards("same_animation")` would now resume from the `c.current.pos`, which is 0, so the animation would end right away.

Not sure if there's any good way to handle this properly.

Comment (akien-mga) [reply scene/animation/animation_player.cpp]: One option could be to add a `bool p_reset = false` parameter (both to `play` and `play_backwards`), and use it here:
```
if (c.assigned != name || p_reset) { // reset
	c.current.pos = p_from_end ? c.current.from->animation->get_length() : 0;
}
```

The other option is to consider that `p_from_end` always means "reset to end", so it could be:
```
if (p_from_end) {
	c.current.pos = c.current.from->animation->get_length();
} else if (c.assigned != name) { // reset
	c.current.pos = 0;
}
```
That would make it harder to resume a backwards-playing animation though, you'd have to do `play("animation_name", custom_blend, -1, false)`.

Comment (luizcarlos1405) [reply scene/animation/animation_player.cpp]: What about this:

``` C++
if (c.assigned != name) { // reset
	c.current.pos = p_from_end ? c.current.from->animation->get_length() : 0;
} else if (c.current.pos == 0 && p_from_end) { // Animation reseted BUT played backwars, set position to the end
	c.current.pos = c.current.from->animation->get_length()
}
```

When calling `play_backwars()` after calling `stop(true)` the animation will be at position 0 inevitably, so we just start from the end, just like we do when calling `play_backwars("different_animation")`.

Comment (akien-mga) [reply scene/animation/animation_player.cpp]: Yeah I was thinking about something like that too, that's a good idea.

Comment (akien-mga) [reply scene/animation/animation_player.cpp]: Style wise, I'd just do the check the other way around though (so `else if (p_from_end && c.current.pos == 0)`.
And typo fixes for the suggested comment:
"// Animation reset BUT played backwards, set position to the end"

Comment (akien-mga) [reply scene/animation/animation_player.cpp]: It would be great if you could ensure that the documentation (in `doc/classes/AnimationPlayer.xml`) properly describes how things work after this fix.

Comment (luizcarlos1405) [reply scene/animation/animation_player.cpp]: Cool, I can do this. I'm trying my best with English, will make these adjustments and then check the docs. It should be another PR or is it fine to put it here?

Comment (akien-mga) [reply scene/animation/animation_player.cpp]: It would be best if it's in the same commit, so that the logic change and corresponding documentation change are together.

Comment (luizcarlos1405) [reply scene/animation/animation_player.cpp]: On it.

Comment (luizcarlos1405) [reply scene/animation/animation_player.cpp]: I hope the documentation update is clear enough.

File: doc/classes/AnimationPlayer.xml [hunk 8]
```diff
@@ -217,7 +219,8 @@
 			<argument index="0" name="reset" type="bool" default="true">
 			</argument>
 			<description>
-				Stop the currently playing animation. If [code]reset[/code] is [code]true[/code], the anim position is reset to [code]0[/code].
+				Stop the currently playing animation. If [code]reset[/code] is [code]true[/code], the animation position is reset to [code]0[/code].
+				if [code]reset[/code] is [code]false[/code], then calling [code]play()[/code] without arguments or [code]play("same_as_before")[/code] will resume the animation. Works the same for [code]play_backwards()[/code] method.
```
Comment (akien-mga) [inline doc/classes/AnimationPlayer.xml]: Should start with a capital letter, "If".

File: doc/classes/AnimationPlayer.xml [hunk 9]
```diff
@@ -217,7 +219,8 @@
 			<argument index="0" name="reset" type="bool" default="true">
 			</argument>
 			<description>
-				Stop the currently playing animation. If [code]reset[/code] is [code]true[/code], the anim position is reset to [code]0[/code].
+				Stop the currently playing animation. If [code]reset[/code] is [code]true[/code], the animation position is reset to [code]0[/code].
```
Comment (akien-mga) [inline doc/classes/AnimationPlayer.xml]: Since it needs an amend for the typo below, maybe you can add this to this sentence?
"If [code]reset[/code] is [code]true[/code], the animation position is reset to [code]0[/code] **and the playback speed is reset to 1.0**."
(without emphasing in the docs, it's just so that you see the edit)

**Review by akien-mga — APPROVED** [review]
Looks great! One last typo to fix but otherwise it's perfect IMO, thanks for bearing with the long review process :)

File: doc/classes/AnimationPlayer.xml (hunk 8 above)
Comment (luizcarlos1405) [reply doc/classes/AnimationPlayer.xml]: Done.

File: doc/classes/AnimationPlayer.xml (hunk 9 above)
Comment (luizcarlos1405) [reply doc/classes/AnimationPlayer.xml]: Done.

**Comment by luizcarlos1405** [comment]
Awesome. I learned a few things from this.

File: doc/classes/AnimationPlayer.xml [hunk 10]
```diff
@@ -217,7 +219,8 @@
 			<argument index="0" name="reset" type="bool" default="true">
 			</argument>
 			<description>
-				Stop the currently playing animation. If [code]reset[/code] is [code]true[/code], the anim position is reset to [code]0[/code].
+				Stop the currently playing animation. If [code]reset[/code] is [code]true[/code], the animation position is reset to [code]0[/code] and the playback speed is reset to 1.0.".
```
Comment (akien-mga) [inline doc/classes/AnimationPlayer.xml]: There's a trailing `".` here (sorry :D).

Comment (akien-mga) [reply doc/classes/AnimationPlayer.xml]: And might be good to use `[code]1.0[/code]` for consistency with `[code]0[/code]`.

File: doc/classes/AnimationPlayer.xml [hunk 11]
```diff
@@ -217,7 +219,8 @@
...
+				If [code]reset[/code] is [code]false[/code], then calling [code]play()[/code] without arguments or [code]play("same_as_before")[/code] will resume the animation. Works the same for [code]play_backwards()[/code] method.
```
Comment (akien-mga) [inline doc/classes/AnimationPlayer.xml]: "for **the** play_backwards() method"

Comment (luizcarlos1405) [reply doc/classes/AnimationPlayer.xml]: Done.

File: doc/classes/AnimationPlayer.xml (hunk 10 above)
Comment (luizcarlos1405) [reply doc/classes/AnimationPlayer.xml]: Done.

**Comment by akien-mga** [comment]
Thanks!
@Calinou The behaviour change of `play()` should likely be documented in the changelog too, as it "breaks compat" (even though it fixes a bug, some people might have relied on `play()` always resetting the animation).
