### PR TITLE
LSP: Sanitizes protocol URI `file:///c%3A` in file path

### LINKED ISSUE #63205: GDScript 2.0: Invalid `file:///` path is used for script reloading
### Godot version

#63195

### System information

Windows 10, Vulkan, GTX 780Ti

### Issue description

When externally editing GDscripts, manual reload prompt appears pressing reload does nothing, same with soft reloading.
When auto reloading, it errors being unable to open file, the file path though is wrong file is `file:/` or `file:///`
when it should be `file://`

image

### Steps to reproduce

Edit GDscript externally and try different methods of reloading.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by A-Lamia**
Fix string formatting issues in get_file_path that caused sync_script_content() to always error. https://github.com/godotengine/godot/issues/63205

*Bugsquad edit:*
- Fixes #63205.

### CODE REVIEW

**Comment by fire** [comment]
Approved the ccid.

**Comment by akien-mga** [comment]
CC @Razoric480

**Comment by Razoric480** [comment]
Looks accurate to me, given the nature of the original bug.

File: modules/gdscript/language_server/gdscript_workspace.cpp [hunk 1]
```diff
@@ -499,7 +499,9 @@ Error GDScriptWorkspace::parse_local_script(const String &p_path) {
 
 String GDScriptWorkspace::get_file_path(const String &p_uri) const {
 	String path = p_uri;
-	path = path.replace(root_uri + "/", "res://");
+	path = (path.matchn("*///*")) ? path.replace("///", "//") : path;
+	path = (path.matchn("*%3A*")) ? path.replace("%3A", ":") : path;
```
Comment (akien-mga) [inline modules/gdscript/language_server/gdscript_workspace.cpp:503]: Is the actually match check useful? You should be able to just run `replace()` directly and if there's nothing to replace, it won't do anything.

Comment (A-Lamia) [reply modules/gdscript/language_server/gdscript_workspace.cpp:503]: Aaah could be depending on what operation is faster though I'm guessing replace does some sort of match as well to check if there is anything to replace, i can remove that now and recommit.

Comment (A-Lamia) [reply modules/gdscript/language_server/gdscript_workspace.cpp]: done removed match checks.

**Comment by akien-mga** [comment]
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

Do you know if that change is also needed for `3.x`?

**Comment by A-Lamia** [comment]
Thanks!, I'm not 100% but it was working at some point in 4.0 so i think something changed in the LSP server that might have not been changed in 3.X
