### PR TITLE
Fallback to RGBA4444 for textures with alpha set to ETC compression

### LINKED ISSUE #33178: Artifacts when rendering HTML5 export on Samsung Galaxy Tab A (2019)
**Godot version:**
7d710a745e3eecbde482349fff78f0a4e14f6371

**OS/device including version:**
Device with issue: Samsung Galaxy Tab A (2019)
Browser on device: Chrome 77.0.3865.116

**Issue description:**
Our game doesn't render correctly.

Example:
Screenshot_20191030-122954_Chrome

Correct rendering on Desktop Chrome:
Screenshot at 2019-10-30 12-33-46

**Steps to reproduce:**
More info will follow on what render features this game specifically uses.

**Minimal reproduction project:**
Will follow if needed.

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/33178

**The Primary Bugfix**
When creating the etc texture previously it would just ignore the alpha channel. Now, if an alpha channel is detected, it converts to ``RGBA4444`` and exits early. This cuts the size of the texture in half, maintains the alpha channel, but reduces precision dramatically. If users want full precision they should select "uncompressed". Reduz and I discussed this over IRC, this solution was selected as it respects the users choice of compression format while maintaining the alpha channel. Additionally, this change minimally impacts the codebase and so should be suitable to merge for 3.2.

**The Uncovered Bug**
In making this fix, I also noticed that ``Image::FORMAT_RGBA4444`` and  ``Image::FORMAT_RGBA5551`` were broken. The image below should be a solid gradient from white to clear however, it was appearing as a gradient from white to blue. 
Screenshot (33)

**Fixing the Uncovered Bug**
This is because ``FORMAT_RGBA4444`` and ``FORMAT_RGBA5551`` were encoded backwards. The code appears to be from when Godot was open sourced and it appears it has been unused. The behaviour in master is to encode ``RGBA4444`` as ``AAAABBBBGGGGRRRR``, when instead it should be ``RRRRGGGGBBBBAAAA`` as we are instructing OpenGL to treat them as an RGBA color. A similar fix to ``RGBA5551`` was necessary, now both image formats can be used. 

**Note To Maintainers**
While the original bug fix has been discussed with reduz, the changes to image.cpp have not. As a result, his review is necessary before merging this PR.

This code is graciously donated by Gamblify.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: modules/etc/image_etc.cpp [hunk 1]
```diff
@@ -139,6 +139,13 @@ static void _compress_etc(Image *p_img, float p_lossy_quality, bool force_etc1_f
 		return;
 	}
 
+	if (img_format >= Image::FORMAT_RGBA8 && force_etc1_format) {
```
Comment (reduz) [inline modules/etc/image_etc.cpp]: i think you should check for alpha detected instead, check the detect_channels structure

**Review by reduz — CHANGES_REQUESTED** [review]

**Comment by akien-mga** [comment]
@reduz seems OK with the `Image` changes.

I'll merge as is as I want to include this in 3.2 beta 5 today, but please make a follow up PR addressing @reduz's above comment (IIUC the current code should already work properly, but what @reduz requests would be more correct).

**Comment by akien-mga** [comment]
Thanks!

File: modules/etc/image_etc.cpp (hunk 1 above)
Comment (clayjohn) [reply modules/etc/image_etc.cpp]: I initially used `` if (detected_channels == Image::DETECTED_RGBA && force_etc1_format)`` however, the branch was never run for some reason so I switched to using what I have here. I'll take a deeper look if it is truly better to use ``DETECTED_RGBA``.

Comment (clayjohn) [reply modules/etc/image_etc.cpp]: Fixed in https://github.com/godotengine/godot/pull/34790
