### PR TITLE
Fix rendering centered odd-size texture in `AnimatedSprite2D`/`AnimatedSprite3D`

### LINKED ISSUE #53050: Incorrect rendering of centered odd-size texture (frame) in `AnimatedSprite`/`AnimatedSprite3D`
### Godot version

3.4.beta5

### System information

N/A

### Issue description

Title.
In `AnimatedSprite(2D)` the rect is calculated properly but the texture is rendered incorrectly:
(it's 1x1 texture)
Godot_v3 4-beta5_win64_mnDGAHGS57

In `AnimatedSprite3D` the rect is consistent with the rendering but it's not centered properly:
(it's 1x1 texture)
Godot_v3 4-beta5_win64_vH75O194FM

### Steps to reproduce

Add an odd-size texture as a frame to `AnimatedSprite`/`AnimatedSprite3D` and make it centered.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by kleonc**
Fixes #53050.

Edit: also fixes selecting issue in `Sprite3D` - previously I could select a 1x1 centered sprite only by clicking at its positive quarter:
ThjiCby19g
Now I can select by clicking anywhere on the sprite.

### CODE REVIEW

File: scene/2d/animated_sprite_2d.cpp [hunk 1]
```diff
@@ -228,11 +228,10 @@ void AnimatedSprite2D::_notification(int p_what) {
 
 			RID ci = get_canvas_item();
 
-			Size2i s;
-			s = texture->get_size();
+			Size2i s = texture->get_size();
```
Comment (AnilBK) [inline scene/2d/animated_sprite_2d.cpp:231]: Texture's get_size() returns Size2().
So, wouldn't it be better to change Size2i to Size2 instead,so that you don't need to cast it to Size2() below?

Comment (kleonc) [reply scene/2d/animated_sprite_2d.cpp:231]: > Texture's get_size() returns Size2().

Yeah, I know. However, AFAIK currently every `Texture`-derived type returns just `Size2(get_width(), get_height())` so it consists of ints (`get_size()` is virtual so it could potentially be overridden though). In many places in the code base there's something like `Size2i s = some_texture.get_size();` so I'd say `get_size()` is kinda expected to really return `Size2i`. Thus I just kinda wanted to be consistent with the code base and make the intention clear by casting to `Size2` explicitly.
I can of course change it if what you've suggested is preferred.

Comment (AnilBK) [reply scene/2d/animated_sprite_2d.cpp:231]: You are correct too.
Additionally, in the same Animated Sprite2d Class, there is the similar code,using Size2.

https://github.com/godotengine/godot/blob/9013771b53cdbc6451f2645f3618ad59d90a2fb1/scene/2d/animated_sprite_2d.cpp#L93-L104

Someone,from core should confirm it though,what's the more correct thing to do. :)

Comment (kleonc) [reply scene/2d/animated_sprite_2d.cpp]: I've made these changes.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
