### PR TITLE
Fix BBCode tables overlap with bottom text (Fix #47012)

### LINKED ISSUE #47012: BBCode Tables overlap with bottom text
**Godot version:**

3.2.4-rc4

**OS/device including version:**

Windows 10

**Issue description:**

RichTextLabel using BBCode tag "[table]" doesn't push the text after the table down far enough so it overlaps with table.
image
Sorry if this is a duplicate issue, I tried to find if this had been submitted before.

**Steps to reproduce:**
Paste this into a RichTextLabel:
```
Top text
[table=3]
[cell]Cell[/cell]
[cell]Cell[/cell]
[cell]Cell[/cell]
[cell]Cell[/cell]
[cell]Cell[/cell]
[cell]Cell[/cell]
[cell]Cell[/cell]
[/table]
Bottom Text
```

**Minimal reproduction project:**

[test.zip](https://github.com/godotengine/godot/files/6137769/test.zip)

### PR DESCRIPTION
**Pull request by jmb462**
Fix #47012

### Issue : 

In RichTextLabel, text after a [table] element overlaps with table last row if the last row doesn't use all columns.

**Before :** 

before

### Fix proposal : 

The height of the row was only added if `column == col_count - 1` => if all the columns was used.
I've added an other condition : `(column == col_count - 1 || E->next() == nullptr)` =>  if all the columns was used OR if it's the last element of the table (even if it's not on the last column).

**After :**

after

### CODE REVIEW

File: scene/gui/rich_text_label.cpp [hunk 1]
```diff
@@ -588,7 +588,7 @@ void RichTextLabel::_shape_line(ItemFrame *p_frame, int p_line, const Ref<Font>
 					offset.x += table->columns[column].width + hseparation + frame->padding.size.x;
 
 					row_height = MAX(yofs, row_height);
-					if (column == col_count - 1) {
+					if (column == col_count - 1 || E->next() == nullptr) {
```
Comment (akien-mga) [inline scene/gui/rich_text_label.cpp:591]: Maybe we can add a comment to make the meaning of the code more obvious?
E.g.
`// Wrap the row on last column or the last cell.`

Comment (jmb462) [reply scene/gui/rich_text_label.cpp:592]: Note sure of the meaning of "wrap" here.

I've added `// Add row height after last column of the row or last cell of the table.`

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
This will need a dedicated PR for the `3.x` branch as the code changed a lot in `master`, and can't be cherry-picked.

**Comment by akien-mga** [comment]
Thanks, I'll do it then :)

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.
