### PR TITLE
Re-add close button for nodes in `AnimationNodeBlendTree` editor

### LINKED ISSUE #82501: No obvious way to delete `AnimationNodeBlendTree` node in `AnimationTree` editor
### Godot version

4.2-mono-rc5

### System information

MacOS 12.3

### Issue description

When adding a new node to an `AnimationNodeBlendTree` in the `AnimationTree` editor, I can't find a way to remove it again other than undo.

- `Ctrl+Delete` removes the `AnimationTree` node.
- Right click on the node opens the `Add Node` menu.
- `Delete`/`Backspace` does nothing.
- Macbook Pro keyboard doesn't have a `Del` key.
- `Fn+Delete` (Mac `Del` emulation) does nothing.

image

### Steps to reproduce

1. Add an `AnimationTree` node with an `AnimationNodeBlendTree`
2. Open the `AnimationTree` editor
3. Add a node
4. Try to remove it

### Minimal reproduction project

Should be easily reproducible without an MRP

### PR DESCRIPTION
**Pull request by timothyqiu**
Closes #82501

The close/delete button was removed [intentionally](https://github.com/godotengine/godot/pull/79311#issuecomment-1701027224) from these editors. Users are supposed to use context menu delete option or the `DEL` key. However, there was no "Delete" option in `AnimationNodeBlendTree` editor's context menu. The only way to delete a node was using `DEL` key, but it's hard to discover.

My initial thought was to add the missing "Delete" option. But the right click menu in this editor was actually not a standalone context menu. Right clicking triggers the "Add Node" menu option. So this PR readds the button instead.

Peek 2023-10-17 23-26

I have to adjust the editor theme so that the button's position looks right. Otherwise it looks too far away from the right edge. This is the only place in the editor that uses `get_titlebar_hbox()`, so I think the modification won't affect others.

### CODE REVIEW

File: editor/plugins/animation_blend_tree_editor_plugin.cpp [hunk 1]
```diff
@@ -170,7 +170,13 @@ void AnimationNodeBlendTreeEditor::update_graph() {
 			name->connect("text_changed", callable_mp(this, &AnimationNodeBlendTreeEditor::_node_rename_lineedit_changed), CONNECT_DEFERRED);
 			base = 1;
 			agnode->set_closable(true);
-			node->connect("delete_request", callable_mp(this, &AnimationNodeBlendTreeEditor::_delete_node_request).bind(E), CONNECT_DEFERRED);
+
+			Button *delete_button = memnew(Button);
```
Comment (SaracenOne) [inline editor/plugins/animation_blend_tree_editor_plugin.cpp:174]: This change is good, but I think it would make sense to check for `if (!read_only) {` only see the delete button only appears when the editor is not operating in read-only mode?

**Review by SaracenOne — CHANGES_REQUESTED** [review]

**Review by SaracenOne — APPROVED** [review]
LGTM 👍

**Comment by akien-mga** [comment]
Thanks!
