### PR TITLE
Fix child relationship lines not being drawn when selecting cells other than first

### LINKED ISSUE #110023: Children relationship line is not drawn when selecting cell other than first
### Tested versions

- Reproducible in master

### System information

Godot v4.5.beta (b267c2fc6) - Windows 11 (build 26100) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 (NVIDIA; 32.0.15.6094) - 13th Gen Intel(R) Core(TM) i5-13500 (20 threads) - 31.78 GiB memory

### Issue description

The children relationship line is only drawn as such if the cell selected on the parent is the first, when it should be drawn if any cell is selected on the parent. Below, the normal relationship lines are drawn in red, the parent relationship lines are drawn in green, and the children relationship lines are drawn in blue.

| First Cell Selected | Second Cell Selected |
|--------|--------|
| Image |Image|

### Steps to reproduce

1. Create a `Tree` with more than 1 column
2. Set `draw_relationship_lines` to >0
3. Set `relationship_line_color` and `children_hl_line_color` to different values
4. Select any cell except for the first in an item with children

### Minimal reproduction project (MRP)

[tree-rl.zip](https://github.com/user-attachments/files/22008205/tree-rl.zip)

### PR DESCRIPTION
**Pull request by dagarsar**
Fix #110023

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -1285,6 +1285,15 @@ bool TreeItem::is_selected(int p_column) {
 	return cells[p_column].selectable && cells[p_column].selected;
 }
 
+bool TreeItem::is_any_column_selected() {
+	for (Cell &cell : cells) {
```
Comment (bruvzg) [inline scene/gui/tree.cpp]:
```suggestion
	for (const Cell &cell : cells) {
```

File: scene/gui/tree.cpp [hunk 2]
```diff
@@ -1285,6 +1285,15 @@ bool TreeItem::is_selected(int p_column) {
 	return cells[p_column].selectable && cells[p_column].selected;
 }
 
+bool TreeItem::is_any_column_selected() {
```
Comment (bruvzg) [inline scene/gui/tree.cpp]:
```suggestion
bool TreeItem::is_any_column_selected() const {
```

File: scene/gui/tree.h [hunk 3]
```diff
@@ -362,6 +362,7 @@ class TreeItem : public Object {
 	bool is_selectable(int p_column) const;
 
 	bool is_selected(int p_column);
+	bool is_any_column_selected();
```
Comment (bruvzg) [inline scene/gui/tree.h]:
```suggestion
	bool is_any_column_selected() const;
```

**Review by bruvzg — APPROVED** [review]
Issue is reproducible and fixed, code looks fine.

**Comment by dagarsar** [comment]
This code in `_is_branch_selected` could benefit from the newly created `is_any_column_selected` method. Should I do a different PR as a follow-up or can it be included in this one?

https://github.com/godotengine/godot/blob/4ebf67c12dcdffcb69242569c118a371a654b6ae/scene/gui/tree.cpp#L2873-L2877

There are also other places where `is_selected(0)` is used and they look like they are hacks to check if the item is selected by checking only the first cell ([here](https://github.com/godotengine/godot/blob/4ebf67c12dcdffcb69242569c118a371a654b6ae/editor/docks/filesystem_dock.cpp#L2068) and [here](https://github.com/godotengine/godot/blob/4ebf67c12dcdffcb69242569c118a371a654b6ae/editor/scene/scene_tree_editor.cpp#L1060)). Maybe all three of these cases together would make for a follow-up PR?

Edit: after taking a closer look, both cases where `is_selected(0)` is used are on `Tree`s with only one column, so they are fine, unless we think this could change in the future.

**Comment by bruvzg** [comment]
> Should I do a different PR as a follow-up or can it be included in this one?

It's the same code, so should be fine add it to the same PR.

**Comment by Repiteo** [comment]
Needs rebase

**Comment by dagarsar** [comment]
> Needs rebase

Done!

**Comment by Repiteo** [comment]
Thanks!
