### PR TITLE
Fix refraction offset by manually unpacking normal mappings

### LINKED ISSUE #44571: Normal mapping offsets refraction rather than just distorting them
**Godot version:**
3.2.3.Stable

**OS/device including version:**
NA

**Issue description:**
Normal mapping offsets refraction rather than just distorting them. This appears to be because the normals are not unpacked before being used for the distortion.
e019cp75Dz

**Current**
```
NORMALMAP = texture(texture_normal,base_uv).rgb;
NORMALMAP_DEPTH = normal_scale;
vec3 ref_normal = normalize( mix(NORMAL,TANGENT * NORMALMAP.x + BINORMAL * NORMALMAP.y + NORMAL * NORMALMAP.z, NORMALMAP_DEPTH) );
```

**Suggested**
```
NORMALMAP = texture(texture_normal,base_uv).rgb;
NORMALMAP_DEPTH = normal_scale;
vec3 normal_unpacked = NORMALMAP * 2.0 - 1.0;
vec3 ref_normal = normalize( mix(NORMAL,TANGENT * normal_unpacked.x + BINORMAL * normal_unpacked.y + NORMAL * normal_unpacked.z, NORMALMAP_DEPTH) );
```

**Steps to reproduce:**
Open attached project to see the issue.

**Minimal reproduction project:**

[refraction_bug.zip](https://github.com/godotengine/godot/files/5724504/refraction_bug.zip)

### PR DESCRIPTION
**Pull request by brennengreen**
Implemented the suggested changes from @clayjohn in issue #44571. Changes were implemented to manually unpack the normal maps to enable refraction rather than just an offset when a normal mapping is provided.

Fixes: #44571

### CODE REVIEW

File: scene/resources/material.cpp [hunk 1]
```diff
@@ -1032,6 +1032,8 @@ void BaseMaterial3D::_update_shader() {
 
 	if (features[FEATURE_REFRACTION]) {
 		if (features[FEATURE_NORMAL_MAPPING]) {
+			code += "\tNORMAL_MAP.xy = NORMAL_MAP.xy * 2.0 - 1.0;\n";
```
Comment (clayjohn) [inline scene/resources/material.cpp:1035]: You should be using a local variable such as ``normal_unpacked`` like what Arnklit suggested in the issue. If you override the ``NORMAL_MAP`` variable then the unpack will happen twice for actually calculating the normals of the object.

Comment (brennengreen) [reply scene/resources/material.cpp:1035]: Got it! Yea that actually makes sense... copy the normal mapping, unpack it, and feed it to the shader for when it needs to consider refraction. Leave the original normal mapping unedited for the remainder of the shader.

Something like 
```
normal_unpacked = NORMAL_MAP;
normal_unpacked = ...;
...
code += "\tvec3 ref_normal = normalize( mix(NORMAL,TANGENT * normal_unpacked.x + BINORMAL * normal_unpacked.y + NORMAL * normal_unpacked.z,NORMAL_MAP_DEPTH) );\n";
```

Then? If so I'll get that fixed and ammended to the commit/pr as soon as I get back home! Thanks!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats on your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.1.
