### PR TITLE
Fixed error spam in remote debugger

### LINKED ISSUE #20365: "core\class_db.cpp:324 - Condition ' !ti ' is true. returned: StringName()" is spammed to console.
**Godot version:**

525384d8cc45a0976e0afb862c8a54244bbd72e7,
v3.1-alpha1
06667b2fcfcf130a9b9e8974c1c7ac0c9ae1de0a - 12-09-2018

**OS/device including version:**

Windows 7 Pro SP1

**Issue description:**

Message "core\class_db.cpp:325 - Condition ' !ti ' is true. returned: StringName()
" gets spammed to output console when game is running and node gets selected in Scene/Remote tab.

Some nodes like Node / Node2D will produce this message if any script is attached to them but will not without a script.

**Steps to reproduce:**
Create new project, add a 'Node' to scene, add default script to it, run the game and select 'Node' node in Scene/Remote. Message starts appearing in console.

If 'Node' is already selected, select 'root' and 'Node' again.

**Minimal reproduction project:**

https://github.com/hilfazer/Projects/tree/EngineIssues/Godot/ConditionNotTiIsTrue

### PR DESCRIPTION
**Pull request by Piet-G**
Fixed error spam in remote debugger.

This finally fixes #20365 for real this time.

Big thanks to @willnationsdev for tracking down where it all went wrong.

### CODE REVIEW

**Comment by akien-mga** [comment]
This `RES:` prefix was added by @Geequlim in ccf76798d5, to be used in https://github.com/godotengine/godot/blob/5436abefe4f40eb84f96c36ae372df39ec4295d7/editor/script_editor_debugger.cpp#L496-L499

**Comment by willnationsdev** [comment]
@DualMatrix You can probably just add a delimeter in the hint string to store both values and then split it up on the other side.

**Comment by DualMatrix** [comment]
Fixed it while preserving the resource path.

File: editor/script_editor_debugger.cpp [hunk 1]
```diff
@@ -492,17 +492,19 @@ void ScriptEditorDebugger::_parse_message(const String &p_msg, const Array &p_da
...
-				String path = hint_string.substr(4, hint_string.length());
-				var = ResourceLoader::load(path);
-			}
-
 			if (is_new_object) {
 				//don't update.. it's the same, instead refresh
 				debugObj->prop_list.push_back(pinfo);
 			}
 
+			if (Variant::get_type_name(var.get_type()) == "String") {
```
Comment (akien-mga) [inline editor/script_editor_debugger.cpp]: It would be cleaner to check `var.get_type() == Variant::STRING` IMO instead of checking the human readable name.

**Comment by akien-mga** [comment]
I'm not convinced by the fix overall, not because it's bad, but because it doesn't improve the existing hacky code that caused the issue in the first place.

I'm not familiar with this code but I think it might be possible to find a cleaner way to identify resources that have to be loaded as a path, without abusing either the property hint or the Variant value itself.

File: editor/script_editor_debugger.cpp (hunk 1 above)
Comment (DualMatrix) [reply editor/script_editor_debugger.cpp]: Yeah thats better, fixed!

**Comment by DualMatrix** [comment]
Yeah it isn't the cleanest code, but it's at least less hacky/broken than previously where the path was stored where the type of the resource was supposed to be, storing it in var at least kinda makes sense imo.
But if someone wants to rewrite this to make it cleaner please go ahead, I don't really feel confident enough to do that.

**Comment by akien-mga** [comment]
As you say, that's good enough for now. The debugger protocol might need a cleanup, but as long as it works... :)
