### PR TITLE
Project Manager: Fix hacky code for project rename

### LINKED ISSUE #25661: A lot of warnings "Property not found:" when trying to rename project
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Godot version:**
3.1 8698876

**OS/device including version:**
Ubuntu 18.04 

**Issue description:**
When I Try to rename project, then this error appears:
```
WARNING: _get: Property not found: rendering/quality/shadows/filter_mode
   At: core/project_settings.cpp:193.
WARNING: _get: Property not found: rendering/quality/subsurface_scattering/follow_surface
   At: core/project_settings.cpp:193.
WARNING: _get: Property not found: rendering/quality/subsurface_scattering/weight_samples
   At: core/project_settings.cpp:193.
WARNING: _get: Property not found: rendering/quality/subsurface_scattering/quality
   At: core/project_settings.cpp:193.
WARNING: _get: Property not found: rendering/quality/subsurface_scattering/scale
   At: core/project_settings.cpp:193.
WARNING: _get: Property not found: rendering/quality/voxel_cone_tracing/high_quality
   At: core/project_settings.cpp:193.
WARNING: _get: Property not found: rendering/limits/time/time_rollover_secs
```

### PR DESCRIPTION
**Pull request by akien-mga**
Instantiating a new ProjectSettings is *not* the way to go. ConfigFile works just fine to read/change a single value.

Fixes memory leaks as the instantiated ProjectSettings was never freed.

- Fixes #25661.
- Supersedes #67579.

### CODE REVIEW

File: core/config/project_settings.cpp [hunk 1]
```diff
@@ -1200,6 +1200,7 @@ ProjectSettings::ProjectSettings() {
 	// Initialization of engine variables should be done in the setup() method,
 	// so that the values can be overridden from project.godot or project.binary.
 
+	ERR_FAIL_COND_MSG(singleton != nullptr, "Instantiating a new ProjectSettings singleton is not supported.");
```
Comment (akien-mga) [inline core/config/project_settings.cpp:1203]: For the record, `memnew(ProjectSettings)` now would show this error and then crash, because failing here is not handled gracefully. I could change it to just a condition `ERR_PRINT` if preferred, though crashing here may not be bad as it's a developer mistake.

File: editor/project_manager.cpp [hunk 2]
```diff
@@ -436,18 +436,18 @@ class ProjectDialog : public ConfirmationDialog {
...
+				get_ok_button()->set_disabled(true);
 			} else {
-				ProjectSettings::CustomMap edited_settings;
-				edited_settings["application/config/name"] = project_name->get_text().strip_edges();
-
-				if (current->save_custom(dir2.path_join("project.godot"), edited_settings, Vector<String>(), true) != OK) {
-					set_message(TTR("Couldn't edit project.godot in project path."), MESSAGE_ERROR);
-				}
+				cfg.set_value("application", "config/name", project_name->get_text().strip_edges());
+				cfg.save(project_godot);
```
Comment (YuriSizov) [inline editor/project_manager.cpp:450]: Should we check for a save error?

Comment (akien-mga) [reply editor/project_manager.cpp:450]: Those don't happen™ :P

But yeah why not.

File: core/config/project_settings.cpp (hunk 1 above)
Comment (Faless) [inline core/config/project_settings.cpp:1203]: Maybe `ERR_CRASH_COND`?

Comment (Faless) [reply core/config/project_settings.cpp:1203]: Maybe `ERR_CRASH_COND`?

**Review by mhilbrunner — APPROVED** [review]
PR council approves

File: core/config/project_settings.cpp (hunk 1 above)
Comment (akien-mga) [reply core/config/project_settings.cpp]: Done.

**Comment by akien-mga** [comment]
So I checked after someone mentioned it in the PR meeting, and indeed there's a potential risk of losing information by going through the ConfigFile API. Here's the diff after rename for a test project with a few global script classes:

```diff
--- project.godot.bkp   2022-11-29 15:43:40.739102066 +0100
+++ project.godot       2022-11-29 15:43:47.488103630 +0100
@@ -1,13 +1,4 @@
-; Engine configuration file.
-; It's best edited using the editor UI and not directly,
-; since the parameters that go here are not all obvious.
-;
-; Format:
-;   [section] ; section goes between []
-;   param=value ; assign values to parameters
-
 config_version=5
-
 _global_script_classes=[{
 "base": "Node",
 "class": &"MyClass",
@@ -26,7 +17,7 @@
 
 [application]
 
-config/name="New Game Project test"
+config/name="New Game Project"
 run/main_scene="res://node_2d.tscn"
 config/features=PackedStringArray("4.0")
 config/icon="res://icon.svg"
```

So it removes comments, and the separation line between `config_version` and `_global_script_classes`.
Those are possibly the only elements in `project.godot` which differ from a proper ConfigFile. Might be worth changing that...

**Comment by YuriSizov** [comment]
> Might be worth changing that...

I'd go with "Allow ConfigFile to preserve formatting (spacing, comments)", but that'd take some effort. I guess if someone complains, asking them to open the project once is okay.

**Review by YuriSizov — APPROVED** [review]
Tested it with a realistic project and it didn't break anything else. I think it's okay as an immediate solution, though it'd be nice to preserve formatting with ConfigFile. Task for another day.

**Comment by YuriSizov** [comment]
Let's see if this causes problems with the next beta. Thanks for the quick turnaround!

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by timothyqiu** [comment]
Cherry-picked for 3.5.2
