### PR TITLE
[3.2] New CPU lightmapper

### LINKED ISSUE #15055: RayTrace is much darker than ConeTrace with BakedLightmap
**Godot version:**
37aab45

**OS/device including version:**
Debian GNU/Linux

**Issue description:**
Using the same setting, by just changing the Mode between ConeTrace and RayTrace, the light energy is vastly different.

With ConeTrace
6tlxiq

With RayTrace
9bpl7u

**Steps to reproduce:**
Import a GLTF scene with Gen Lightmaps on. Add a DirectionalLight and add an WorldEnvironment with no light. Add a BakedLightmap and bake with ConeTrace. Then switch to RayTrace and rebake.

**Minimal reproduction project:**

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

### LINKED ISSUE #16398: Make the lightmap render result affected by the WorldEnvironment.
I suggest the environment map should affect the result of the Lightmapper.

**Godot version:**
ea99b90

**OS/device including version:**
Doesn't matter.

**Issue description:**
The WorldEnvironment doesn't affect the render result of the BakedLightmap.
envaffect

### LINKED ISSUE #16820: Lightmap (raytrace) not working?
**Godot version:**
Godot 3

Hello,

I've created a simple room in blender and exported it with the better collada exporter.
Now, I'm trying to create a lightmap. With ConeTrace mode, everything looks ok but in RayTrace mode it looks very strange...

ConeTrace:
conetrace

RayTrace:
raytrace

You can have a look at the project.

Is it a bug or have I done something wrong?
[house_viewer.zip](https://github.com/godotengine/godot/files/1736846/house_viewer.zip)

### LINKED ISSUE #20321: Baked Lighting
**Godot version:**
3.0.5 64 bits

**OS/device including version:**
* Intel Core i5-6200U 
* Intel HD Graphics 520
* 12 GB RAM
* Windows 10 

**Issue description:**
I've been testing Baked Lighting recently and found quite a lot of odd stuff. 

>When 
* Using the unwrap mesh Uv2 for lightmap baking option and then baking the scene
* Unwrapping Uv2 from Blender and then baking
* Unwrapping Uv2 from Blender and then re-importing with Gen-light enabled
* Trying to bake an instanced scene

Something like shown in the screenshot happens: 

imagen
Not nice, not expected at all.

But if I only enable gen-lighting on re-import this happens: 

imagen

Nice and expected

imagen

Other problem is that I can't actually bake big scenes (with a lot of polygons in some objects) using objects without Uv2 and with Gen-light enabled, as I always get this message: 

(...)
DECOMPRESSING!!!!
ERROR: Vector<struct VoxelLightBaker::Cell>::resize: Condition ' !_ptrnew ' is true. returned: ERR_OUT_OF_MEMORY
   At: c:\projects\godot-builds\godot\core\vector.h:296
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] <couldn't map PC to fn name>
[4] <couldn't map PC to fn name>
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] <couldn't map PC to fn name>
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
[13] <couldn't map PC to fn name>
[14] <couldn't map PC to fn name>
[15] <couldn't map PC to fn name>
[16] <couldn't map PC to fn name>
[17] <couldn't map PC to fn name>
[18] <couldn't map PC to fn name>
[19] <couldn't map PC to fn name>
[20] <couldn't map PC to fn name>
[21] <couldn't map PC to fn name>
[22] <couldn't map PC to fn name>
[23] <couldn't map PC to fn name>
[24] <couldn't map PC to fn name>
[25] <couldn't map PC to fn name>
[26] <couldn't map PC to fn name>
[27] <couldn't map PC to fn name>
[28] <couldn't map PC to fn name>
[29] <couldn't map PC to fn name>
[30] <couldn't map PC to fn name>
[31] <couldn't map PC to fn name>
[32] <couldn't map PC to fn name>
[33] <couldn't map PC to fn name>
[34] <couldn't map PC to fn name>
[35] <couldn't map PC to fn name>
[36] <couldn't map PC to fn name>
[37] CallWindowProcW
[38] CallWindowProcW
[39] glDebugEntry
[40] CallWindowProcW
[41] DispatchMessageW
[42] <couldn't map PC to fn name>
[43] <couldn't map PC to fn name>
[44] <couldn't map PC to fn name>
[45] <couldn't map PC to fn name>
[46] <couldn't map PC to fn name>
[47] BaseThreadInitThunk
-- END OF BACKTRACE --

I only could bake the scene using the capture and bake Cell sizes to 64, with low quality cone-tracing

A suggestion is that we could load our previously baked lightmaps into godot, as I actually tried trying to hack my way into make it work (replacing files), but it didn't work. 

**Steps to reproduce:**

When 
* Using the unwrap mesh Uv2 for lightmap baking option and then baking the scene
* Unwrapping Uv2 from Blender and then baking
* Unwrapping Uv2 from Blender, re-importing with Gen-light enabled and then baking
* Trying to bake an instanced scene

**Minimal reproduction project:**

This one is the file that I tried to bake and failed numerous times. 
https://github.com/ProjectJoyeuse/PathsOfJjaro/blob/master/Scenes/YucatanDive.dae

### LINKED ISSUE #21587: Dynamic lighting missing/broken on some meshes
**Godot version:**

3.0.6.stable.custom_build (compiled from "https://github.com/godotengine/godot/archive/3.0.6-stable.tar.gz")

**OS/device including version:**

OpenGL ES 3.0 Renderer: Radeon RX 560 Series (POLARIS11, DRM 3.26.0, 4.18.5-arch1-1-ARCH, LLVM 6.0.1)
(confirmed on other machines)

**Issue description:**

Lighting does not work for certain meshes.
Adding a UV2 map allows baked lightmaps but not dynamic.

Disabling the normal map OR enabling Triplanar UV2 both seem to fix the problem.

dynamic_light_mesh_problem

I also noticed the widgets won't draw over the affected objects
widget_lost

**Steps to reproduce:**
Run attached scene. Meshes are baked into the scene, exported from Maya dae

**Minimal reproduction project:**

[couchbug.zip](https://github.com/godotengine/godot/files/2334266/couchbug.zip)

### LINKED ISSUE #30789: Godot crashes during lightmap generation
**Godot version:**

Godot 3.1.1

**OS/device including version:**

Windows 10

**Issue description:**

When I changed light baking to Gen Lightmaps and pressed Reimport, the lightmap generation process was started, but after some time progress freezed and then Godot crashed.

**Steps to reproduce:**
1) Add floor_2.escn and/or female.escn and/or chest_2.dae to the project, select it in the file manager
2) Switch to the Import tab
3) Select Light Baking == Gen Lightmaps
4) Hit reimport

**Models used:**
[floor_2.zip](https://github.com/godotengine/godot/files/3425722/floor_2.zip)
[female.zip](https://github.com/godotengine/godot/files/3425727/female.zip)
[chest_2.zip](https://github.com/godotengine/godot/files/3425815/chest_2.zip)

P.S.: There was an error in console just before crash:
image

### LINKED ISSUE #30929: BakedLightmap shadows looks highly pixelated when using ConeTrace and simply incorrect when using RayTrace
**Godot version:**
Godot 3.1.1

**OS/device including version:**
Windows 10

**Issue description:**
I've had troubles when trying to implement baked light for our game.
Shadows looks highly pixelated when using ConeTrace and simply incorrect when using RayTrace.

**Steps to reproduce:**
1) Get the demo project from here: https://github.com/Antokolos/palladium3d-demo/archive/v0.0.1.zip
2) Open BakedLightmap node in res://floor_demo_full.tscn
3) Click Bake Lightmaps and wait for completion (Caution, this will require some time to be finished)
4) Run the game, press Esc, set the Optimal quality in the settings, now the Godot's OmniLights will be hidden and you'll see only baked light
5) Take a look at the shadows, they are looking very pixelated.

image

image

6) Press Esc, set the High quality in the settings, now you can see Godot's OmniLights with shadows enabled. This is what I'm trying to achieve when using baked light

image

7) Press ALT+F4, exit the game.
8) Open BakedLightmap node in res://floor_demo_full.tscn, set bake mode to RayTrace
9) Click Bake Lightmaps and wait for completion (Caution, this will require some time to be finished)
10) Run the game, set the Optimal graphics quality
10) Take a look at the shadows, they are incorrect

image

image

**Minimal reproduction project:**
https://github.com/Antokolos/palladium3d-demo/archive/v0.0.1.zip

### LINKED ISSUE #32746: Generated UV2s are not saved
**Godot version:**
Latest 3.2 Alpha aad4d86

**OS/device including version:**
Linux Mint 18.2

**Issue description:**
When you use the menu option Mesh->Unwrap UV2 for Lightmap/AO this successfully generates second set of UVs which can be viewed with Mesh->View UV2 and can be used for lightmapping.

The problem is that this is not registered as a change to the scene (the * does not appear on the scene tab) and it is not autosaved, as Godot thinks there have been no changes. Then next time you load the project, the lightmapping is gone, because the UV2 coords are not saved.

It took me a while to figure out what was going wrong here. When I was using a mesh stored in a tscn file, I could force it to save by explicitly choosing Scene->Save Scene from the menu. With an obj file I can't seem to get it to save UV2 at all.

**Steps to reproduce:**
Add a MeshInstance mesh that has no second set of UVs. Choose 'Unwrap UV2', verify they are there with 'View UV2'. Press Ctrl-S to save, then quit godot, and reopen the project. The UV2s are gone.

**Minimal reproduction project:**
[UV2Bug.zip](https://github.com/godotengine/godot/files/3717130/UV2Bug.zip)

### LINKED ISSUE #38685: BakedLightmap crash on large scenes
**Godot version:**
Master 66b0b0c

**OS/device including version:**
Windows 10 NVidia GTX 1050 2gb

**Issue description:**
When baking lightmaps in Calinou's sponza scene I get a GPU crash
```
The instruction at 0x00007FF8A3745D6B referenced memory at 0x0000000000000068. The memory could not be read.
```
Along with the following backtrace:
```
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] vkGetInstanceProcAddr
[1] vkCmdCopyImageToBuffer (C:\Users\Clay\dev\godot\thirdparty\vulkan\loader\trampoline.c:1785)
[2] RenderingDeviceVulkan::texture_get_data (C:\Users\Clay\dev\godot\drivers\vulkan\rendering_device_vulkan.cpp:2511)
[3] RasterizerSceneRD::bake_render_uv2 (C:\Users\Clay\dev\godot\servers\rendering\rasterizer_rd\rasterizer_scene_rd.cpp:4237)
[4] RenderingServerScene::bake_render_uv2 (C:\Users\Clay\dev\godot\servers\rendering\rendering_server_scene.cpp:3018)
[5] RenderingServerRaster::bake_render_uv2 (C:\Users\Clay\dev\godot\servers\rendering\rendering_server_raster.h:637)
[6] RenderingServerWrapMT::bake_render_uv2 (C:\Users\Clay\dev\godot\servers\rendering\rendering_server_wrap_mt.h:543)
[7] BakedLightmap::bake (C:\Users\Clay\dev\godot\scene\3d\baked_lightmap.cpp:699)
[8] BakedLightmapEditorPlugin::_bake_select_file (C:\Users\Clay\dev\godot\editor\plugins\baked_lightmap_editor_plugin.cpp:40)
[9] call_with_variant_args_helper<BakedLightmapEditorPlugin,String const &,0> (C:\Users\Clay\dev\godot\core\callable_method_pointer.h:136)
[10] call_with_variant_args<BakedLightmapEditorPlugin,String const &> (C:\Users\Clay\dev\godot\core\callable_method_pointer.h:162)
[11] CallableCustomMethodPointer<BakedLightmapEditorPlugin,String const &>::call (C:\Users\Clay\dev\godot\core\callable_method_pointer.h:178)
[12] Callable::call (C:\Users\Clay\dev\godot\core\callable.cpp:50)
[13] Object::emit_signal (C:\Users\Clay\dev\godot\core\object.cpp:1201)
[14] Object::emit_signal (C:\Users\Clay\dev\godot\core\object.cpp:1258)
[15] EditorFileDialog::_action_pressed (C:\Users\Clay\dev\godot\editor\editor_file_dialog.cpp:463)
[16] call_with_variant_args_helper<EditorFileDialog> (C:\Users\Clay\dev\godot\core\callable_method_pointer.h:140)
[17] call_with_variant_args<EditorFileDialog> (C:\Users\Clay\dev\godot\core\callable_method_pointer.h:162)
[18] CallableCustomMethodPointer<EditorFileDialog>::call (C:\Users\Clay\dev\godot\core\callable_method_pointer.h:178)
[19] Callable::call (C:\Users\Clay\dev\godot\core\callable.cpp:50)
[20] Object::emit_signal (C:\Users\Clay\dev\godot\core\object.cpp:1201)
[21] Object::emit_signal (C:\Users\Clay\dev\godot\core\object.cpp:1258)
[22] AcceptDialog::_ok_pressed (C:\Users\Clay\dev\godot\scene\gui\dialogs.cpp:110)
[23] call_with_variant_args_helper<AcceptDialog> (C:\Users\Clay\dev\godot\core\callable_method_pointer.h:140)
[24] call_with_variant_args<AcceptDialog> (C:\Users\Clay\dev\godot\core\callable_method_pointer.h:162)
[25] CallableCustomMethodPointer<AcceptDialog>::call (C:\Users\Clay\dev\godot\core\callable_method_pointer.h:178)
[26] Callable::call (C:\Users\Clay\dev\godot\core\callable.cpp:50)
[27] Object::emit_signal (C:\Users\Clay\dev\godot\core\object.cpp:1201)
[28] Object::emit_signal (C:\Users\Clay\dev\godot\core\object.cpp:1258)
[29] BaseButton::_pressed (C:\Users\Clay\dev\godot\scene\gui\base_button.cpp:135)
[30] BaseButton::on_action_event (C:\Users\Clay\dev\godot\scene\gui\base_button.cpp:174)
[31] BaseButton::_gui_input (C:\Users\Clay\dev\godot\scene\gui\base_button.cpp:64)
[32] MethodBind1<BaseButton,Ref<InputEvent> >::call (C:\Users\Clay\dev\godot\core\method_bind.gen.inc:867)
[33] Object::call_multilevel (C:\Users\Clay\dev\godot\core\object.cpp:747)
[34] Object::call_multilevel (C:\Users\Clay\dev\godot\core\object.cpp:848)
[35] Viewport::_gui_call_input (C:\Users\Clay\dev\godot\scene\main\viewport.cpp:1675)
[36] Viewport::_gui_input_event (C:\Users\Clay\dev\godot\scene\main\viewport.cpp:1997)
[37] Viewport::input (C:\Users\Clay\dev\godot\scene\main\viewport.cpp:3035)
[38] Window::_window_input (C:\Users\Clay\dev\godot\scene\main\window.cpp:904)
[39] call_with_variant_args_helper<Window,Ref<InputEvent> const &,0> (C:\Users\Clay\dev\godot\core\callable_method_pointer.h:136)
[40] call_with_variant_args<Window,Ref<InputEvent> const &> (C:\Users\Clay\dev\godot\core\callable_method_pointer.h:162)
[41] CallableCustomMethodPointer<Window,Ref<InputEvent> const &>::call (C:\Users\Clay\dev\godot\core\callable_method_pointer.h:178)
[42] Callable::call (C:\Users\Clay\dev\godot\core\callable.cpp:50)
[43] DisplayServerWindows::_dispatch_input_event (C:\Users\Clay\dev\godot\platform\windows\display_server_windows.cpp:1779)
[44] DisplayServerWindows::_dispatch_input_events (C:\Users\Clay\dev\godot\platform\windows\display_server_windows.cpp:1762)
[45] Input::_parse_input_event_impl (C:\Users\Clay\dev\godot\core\input\input.cpp:561)
[46] Input::parse_input_event (C:\Users\Clay\dev\godot\core\input\input.cpp:379)
[47] Input::flush_accumulated_events (C:\Users\Clay\dev\godot\core\input\input.cpp:793)
[48] DisplayServerWindows::process_events (C:\Users\Clay\dev\godot\platform\windows\display_server_windows.cpp:1520)
[49] OS_Windows::run (C:\Users\Clay\dev\godot\platform\windows\os_windows.cpp:661)
[50] widechar_main (C:\Users\Clay\dev\godot\platform\windows\godot_windows.cpp:162)
[51] _main (C:\Users\Clay\dev\godot\platform\windows\godot_windows.cpp:184)
[52] main (C:\Users\Clay\dev\godot\platform\windows\godot_windows.cpp:196)
[53] __scrt_common_main_seh (d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[54] BaseThreadInitThunk
-- END OF BACKTRACE --
```

**Steps to reproduce:**
1. Download https://github.com/Calinou/godot-sponza-4
2. Unwrap UVs for lightmap
3. Add a BakedLightmap to the scene
4. Press "Bake"

**Minimal reproduction project:**
I can't reproduce on a small scene, but I can reproduce in https://github.com/Calinou/godot-sponza-4

### LINKED ISSUE #39532: "Assertion !isZero(l, epsilon) failed" in xatlas.cpp during lightmap generation
**Godot version:**
Godot Engine v3.2.2.rc.custom_build.6efab27a4

**OS/device including version:**
OS: Arch linux
GPU driver: nvidia 440.82-21

OpenGL ES 3.0 Renderer: GeForce GTX 970/PCIe/SSE2

**Issue description:**
When opening "Third Person Shooter Demo" godot editor crashes on assert `thirdparty/xatlas/xatlas.cpp:814: xatlas::internal::Vector3 xatlas::internal::normalize(const xatlas::internal::Vector3&, float): Assertion '!isZero(l, epsilon)' failed.` during lightmap generation.

Logs from console:
```
Editing project: /home/aelspire/Dokumenty/Godot/tps-demo (::home::aelspire::Dokumenty::Godot::tps-demo)
Godot Engine v3.2.2.rc.custom_build.6efab27a4 - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 970/PCIe/SSE2

ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
ERROR: _create_material: Condition "!collada.state.material_map.has(p_target)" is true. Returned: ERR_INVALID_PARAMETER
   At: editor/import/editor_import_collada.cpp:361.
Adding mesh..
Generate..
Final texture size: 100.000000,100.000000 - max 99.500000,99.500000
Done
Adding mesh..

***************************
8< snip snip
***************************

Done
Adding mesh..
Generate..
Final texture size: 52.000000,48.000000 - max 51.500000,47.500000
Done
Adding mesh..
Generate..
godot.x11.tools.64: thirdparty/xatlas/xatlas.cpp:814: xatlas::internal::Vector3 xatlas::internal::normalize(const xatlas::internal::Vector3&, float): Assertion `!isZero(l, epsilon)' failed.
```

### LINKED ISSUE #45086: New CPU Lightmapper crashes with GridMap when baking
**Godot version:**

Godot Engine v3.2.4.beta5+lightmapper.official

**OS/device including version:**

Windows 10 (Build: 19042.685, Arch: x64)
AMD Ryzen 7 3800XT
NVidia GeForce RTX 2080 (running GLES3)

**Issue description:**

I was testing the new CPU lightmapper proposed in #44628 with a simple GridMap.  Whenever I try to bake the lightmap for the scene, I get a crash.  Sample scene is attached.

Log:
```
Godot Engine v3.2.4.beta5+lightmapper.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce RTX 2080/PCIe/SSE2
OpenGL ES Batching: ON

ERROR: get: FATAL: Index p_index = 0 is out of bounds (size() = 0).
   At: ./core/cowdata.h:152
```

I tested the same scene with the official build of v3.2.4.beta5 and the lightmapper worked fine there.

**Steps to reproduce:**

1. Create a scene and add a Gridmap.
2. Create a MeshLibrary containing a cube as the only item.
3. Paint a scene with the cube "tiles",
4. Add some lights.
5. Add a BakedLightmap node and cover the GridMap in its extents.
6. Click the "Bake" button.

**Minimal reproduction project:**

[TestGridmapLightmap.zip](https://github.com/godotengine/godot/files/5793653/TestGridmapLightmap.zip)

### LINKED ISSUE #45091: New CPU Lightmapper doesn't work on MacOS with IntelGPU
**Godot version:**

Godot Engine v3.2.4.beta5 lightmapper bulid

**OS/device including version:**

屏幕快照 2021-01-11 13 58 21

**Issue description:**

after baking, I can't see anything but a piece of gray model

also I got error message when use GLES2
屏幕快照 2021-01-11 13 41 23

got error message when use GLES3
屏幕快照 2021-01-11 13 53 59
屏幕快照 2021-01-11 14 31 39

before baking
屏幕快照 2021-01-11 13 54 36

after baking
屏幕快照 2021-01-11 13 54 23

**Steps to reproduce:**
find some model to test
imported the model to engine
unwarp lightmap for each mesh
enabled "Use In Baked Light"
add a directional light and turn on shadow
add BakedLightmap node to the scene tree
click bake button and wait for finsihing

**Minimal reproduction project:**

https://drive.google.com/file/d/1GwlClcFxspsK7swA2SqnSnsIZWlupanF/view?usp=sharing

### LINKED ISSUE #45097: New CPU lightmapper stuck at preparing data structures [MinGW GCC]
**Godot version:**
3.2.4.beta5+lightmapper from https://github.com/godotengine/godot/pull/44628#issuecomment-757508966

**OS/device including version:**
Windows 10, GeForce GTX 660/PCIe/SSE2, i7-3820 @3.6GHz

**Issue description:**
I tried the new lightmapper on a simple model using the lowest bake settings on my old PC and it hangs at: "Preparing data structures". It was not responding and after half an hour i had to kill the process. The UV2 coordinates were generated by Godot using "Generate Lightmaps" in the import settings. cc @JFonS

Capture

These are my bake settings:
settings

**Steps to reproduce:**
Open the project, select the BakedLightmap Node and bake it.

**Minimal reproduction project:**
[LightmapperTester.zip](https://github.com/godotengine/godot/files/5794821/LightmapperTester.zip)

### PR DESCRIPTION
**Pull request by JFonS**
Completely re-write the lightmap generation code:
- Follow the general lightmapper code structure from 4.0.
- Use proper path tracing to compute the global illumination.
- Use atlassing to merge all lightmaps into a single texture (done by @RandomShaper)
- Use OpenImageDenoiser to improve the generated lightmaps.

There is some minor compatibility breakage in some properties and methods
in BakedLightmap, but lightmaps generated in previous engine versions
should work fine out of the box.

The scene importer has been changed to generate `.unwrap_cache` files
next to the imported scene files. These files *SHOULD* be added to any
version control system as they guarantee there won't be differences when
re-importing the scene from other OSes or engine versions.

Documentation is missing, I'll work on it after the holidays :)

This work started as a Google Summer of Code project; Was later funded by IMVU for a good amount of progress;
Was then finished and polished by me on my free time.

TPS demo with direct light only:
lm-off

TPS demo with baked indirect lighting.
lm-on

Special thanks to Pedro (@RandomShaper) for helping out with atlassing and other issues!

Supersedes #40035.
This closes #15055, closes #16820, closes #16398, closes #20321, closes #21587, closes #30789, closes #30929, closes #32746, closes #38685, closes #39532.

Edit:
I updated the PR with fixes for all the issues reported so far:
* Fix Embree runtime when using MinGW (patch by @RandomShaper), closes #45097.
* Fix baking of lightmaps on GridMaps, closes #45086.
* Fix some GLSL errors, should fix #45091 but I don't have a proper way to test it on a mac.
* Fix overflow in the number of shader variants (GLES2), it made gizmos go black. Reported via twitter, no issue open AFAIK.

### CODE REVIEW

**Comment by NHodgesVFX** [comment]
The light mapper works really well with the exception of dynamic objects, I couldn't seem to get them to work properly.

Here is a image from blender's cycles engine
Cycles

Here is one in godot with this lightmapper, lights are set to indirect only.
Godot

here is with lights set to all
Godot_AllBaked

here is with no lights, the scene is lit with environment light only
Godot_EnviormentOnly

with no indirect light.
Godot_NoGI

with GIProbe
Godot_GIProbe

**Comment by NHodgesVFX** [comment]
Here is the scene 
[LightMapperTest.zip](https://github.com/godotengine/godot/files/5737215/LightMapperTest.zip)

**Comment by dedm0zaj** [comment]
In editor:

изображение

In game:

изображение

Project 
[test_lightmap_capture_energy_new.zip](https://github.com/godotengine/godot/files/5737845/test_lightmap_capture_energy_new.zip)

**Comment by dedm0zaj** [comment]
Test with my change (Energy parameter of DataLight affects dynamic objects)
https://github.com/godotengine/godot/pull/44458

https://user-images.githubusercontent.com/75580200/103059987-5028c100-45d9-11eb-8516-fa4d2e196495.mp4

**Comment by JFonS** [comment]
@NHodgesVFX Do you have a reproduction project for the dynamic objects issue? I'm testing and everything seems to work fine for me.

**Comment by JFonS** [comment]
@dedm0zaj That's a separate issue, I will follow up on your PR soon.

**Comment by NHodgesVFX** [comment]
> @NHodgesVFX Do you have a reproduction project for the dynamic objects issue? I'm testing and everything seems to work fine for me.

i was trying to get it to work with the cornel's box scene above. This is what it looks like. Im wondering if its a scale issue. I just set the two small sphere to be dynamic. Here is the scene as it is in the photo
[CornelBox_Dynamic.zip](https://github.com/godotengine/godot/files/5739883/CornelBox_Dynamic.zip)

godot dynamic

**Comment by NHodgesVFX** [comment]
Update it does seem to be a scale issue, is it possible to get the cell size slider to go smaller? I scaled up the scene 5x  and that made it work. Something I noticed is it might be nice to exaggerate the GI, although I would worry about that later.

**Comment by JFonS** [comment]
@NHodgesVFX I set a lower bound to the cell size because the amount of stored data can grow pretty quickly, but it can be lowered.

As per the exaggeration, @dedm0zaj is working on a change so that the "Energy" property of BakedLightmapData also affects dynamics objects, so that should do fine.

**Comment by NHodgesVFX** [comment]
> @NHodgesVFX I set a lower bound to the cell size because the amount of stored data can grow pretty quickly, but it can be lowered.
> 
> As per the exaggeration, @dedm0zaj is working on a change so that the "Energy" property of BakedLightmapData also affects dynamics objects, so that should do fine.

I unbounded the values or at least i think i did, about to try it now.

**Comment by NHodgesVFX** [comment]
Ok im at a loss, it doesn't work, the scene I listed above for whatever reason doesn't work. It does seem like the unbounded capture size worked fine though judging by bake time and size. Probably best if you give it a check when you have the chance. Although its Christmas now, so take a break :) Happy Holidays

**Comment by JFonS** [comment]
@NHodgesVFX I will get back to this after the break then, happy holidays to you too!

**Comment by esblinuxcss** [comment]
> Completely re-write the lightmap generation code:
> 
> * Follow the general lightmapper code structure from 4.0.
> * Use proper path tracing to compute the global illumination.
> * Use atlassing to merge all lightmaps into a single texture (done by @RandomShaper)
> * Use OpenImageDenoiser to improve the generated lightmaps.
> 
> There is some minor compatibility breakage in some properties and methods
> in BakedLightmap, but lightmaps generated in previous engine versions
> should work fine out of the box.
> 
> The scene importer has been changed to generate `.unwrap_cache` files
> next to the imported scene files. These files _SHOULD_ be added to any
> version control system as they guarantee there won't be differences when
> re-importing the scene from other OSes or engine versions.
> 
> Documentation is missing, I'll work on it after the holidays :)
> 
> This work started as a Google Summer of Code project; Was later funded by IMVU for a good amount of progress;
> Was then finished and polished by me on my free time.
> 
> TPS demo with direct light only:
> lm-off
> 
> TPS demo with baked indirect lighting.
> lm-on
> 
> Special thanks to Pedro (@RandomShaper) for helping out with atlassing and other issues!
> 
> Supersedes #40035.
> This closes #15055, closes #16820, closes #16398, closes #20321, closes #21587, closes #30789, closes #30929, closes #32746, closes #38685, closes #39532.

I try to bake a small screne created with Qodot Plugin it take very longer time(3 and a half hours) to bake the scre with 4 Lights15 bounces in high quality my pc is not a power house is laptop with 1.66 Ghz Dual Core AMD CPU with 8Gb of RAM the current Ligthmapper takes 7-12minutes to bake the scne (using come trace and the ligths are set in Bake All) i will try to make another test with a more small scene created in blender with one ligth. when i do that i will show the results

**Comment by NHodgesVFX** [comment]
@esblinuxcss this is expected, the cone tracing mode of the previous light mapper was a fast but inaccurate mode based off of GiProbe. The new lightmapper uses a much better version of the raytrace mode of the previous lightmapper. In addition you are using 15 bounces the previous lightmapper only used 1, more bounces more time. 

Make sure you are building with target=release_debug or you are downloading an artifact from here which is compiled using release_debug.

**Comment by Calinou** [comment]
We could consider adding an easy way to bake with a "preview" quality before committing to a "final" bake. This way, you could keep your current settings in your BakedLightmap node, yet you'd have the ability to perform a quick bake with low quality settings.

**Comment by Avogine** [comment]
I've got a questions regarding draw calls. When using baked light, it seems like every object with baked light is adding 1 extra draw call. How are you supposed to optimize a forest with hundreds of trees, for example, where you would normally use multimeshes?

File: core/math/geometry.cpp [hunk 1]
```diff
@@ -33,6 +33,8 @@
 #include "core/print_string.h"
 #include "thirdparty/misc/clipper.hpp"
 #include "thirdparty/misc/triangulator.h"
+#define STB_RECT_PACK_IMPLEMENTATION
+#include "thirdparty/stb_rect_pack/stb_rect_pack.h"
```
Comment (akien-mga) [inline core/math/geometry.cpp:37]: Nitpick as it's preexisting code, but please add a separation line between Godot headers (`"core/print_string.h"`) and thirdparty/system headers.

**Comment by reduz** [comment]
@Avogine you just don't use lightmaps for such kind of scenes. For outdoors, you will have to wait for Godot 4 SDFGI, or just not use them.

**Comment by Avogine** [comment]
Ok thanks, good to know

File: thirdparty/stb_rect_pack/stb_rect_pack.h [hunk 2]
```diff
@@ -0,0 +1,629 @@
+// stb_rect_pack.h - v1.00 - public domain - rectangle packing
```
Comment (akien-mga) [inline thirdparty/stb_rect_pack/stb_rect_pack.h:1]: This can go in `thirdparty/misc/` like other `stb` headers, and like done in `master`.

Also make sure to document it in `thirdparty/README.md` (under "Misc / Modules", you can copy from `stb_vorbis.c` and adjust).

File: modules/denoise/denoise_wrapper.cpp [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,  */
+/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE     */
+/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                */
+/*************************************************************************/
+
+#include "denoise_wrapper.h"
+#include "core/os/copymem.h"
+#include "core/os/memory.h"
+#include "thirdparty/oidn/include/OpenImageDenoise/oidn.h"
+#include <stdio.h>
```
Comment (akien-mga) [inline modules/denoise/denoise_wrapper.cpp:35]:
```suggestion
#include "denoise_wrapper.h"

#include "core/os/copymem.h"
#include "core/os/memory.h"

#include "thirdparty/oidn/include/OpenImageDenoise/oidn.h"

#include <stdio.h>
```

See https://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html#header-includes

Note that normally you shouldn't include thirdparty headers with a fully qualified path like this, it would be better to add them to the include path and use `#include <OpenImageDenoise/oidn.h>`. But given that it's done the same way in `master`, no need to change it there. One day I'll get to allow unbundling this dependency on Linux distros and that will be part of it).

File: modules/denoise/denoise_wrapper.cpp [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+bool oidn_denoise(void *deviceptr, float *p_floats, int p_width, int p_height) {
+	OIDNDeviceImpl *device = (OIDNDeviceImpl *)deviceptr;
+	OIDNFilter filter = oidnNewFilter(device, "RTLightmap");
+	void *input_buffer = memalloc(p_width * p_height * 3 * sizeof(float));
+	copymem(input_buffer, p_floats, p_width * p_height * 3 * sizeof(float));
+	oidnSetSharedFilterImage(filter, "color", input_buffer, OIDN_FORMAT_FLOAT3, p_width, p_height, 0, 0, 0);
+	oidnSetSharedFilterImage(filter, "output", (void *)p_floats, OIDN_FORMAT_FLOAT3, p_width, p_height, 0, 0, 0);
+	oidnSetFilter1b(filter, "hdr", true);
+	//oidnSetFilter1f(filter, "hdrScale", 1.0f);
+	//oidnSetFilter1i(filter, "verbose", 4);
```
Comment (akien-mga) [inline modules/denoise/denoise_wrapper.cpp:52]: Is this relevant to keep?

File: modules/denoise/lightmap_denoiser.cpp [hunk 5]
```diff
@@ -0,0 +1,65 @@
...
+/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF    */
+/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.*/
+/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY  */
+/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,  */
+/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE     */
+/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                */
+/*************************************************************************/
+
+#include "lightmap_denoiser.h"
+#include "denoise_wrapper.h"
```
Comment (akien-mga) [inline modules/denoise/lightmap_denoiser.cpp:32]:
```suggestion
#include "lightmap_denoiser.h"

#include "denoise_wrapper.h"
```

File: modules/denoise/register_types.cpp [hunk 6]
```diff
@@ -0,0 +1,40 @@
...
+/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.*/
+/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY  */
+/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,  */
+/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE     */
+/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                */
+/*************************************************************************/
+
+#include "register_types.h"
+#include "core/engine.h"
+#include "lightmap_denoiser.h"
```
Comment (akien-mga) [inline modules/denoise/register_types.cpp:33]:
```suggestion
#include "register_types.h"

#include "core/engine.h"
#include "lightmap_denoiser.h"
```

File: modules/lightmapper_cpu/lightmapper_cpu.cpp [hunk 7]
```diff
@@ -0,0 +1,1646 @@
...
+/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF    */
+/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.*/
+/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY  */
+/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,  */
+/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE     */
+/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                */
+/*************************************************************************/
+
+#include "lightmapper_cpu.h"
+#include "core/math/geometry.h"
```
Comment (akien-mga) [inline modules/lightmapper_cpu/lightmapper_cpu.cpp:32]:
```suggestion
#include "lightmapper_cpu.h"

#include "core/math/geometry.h"
```

File: modules/lightmapper_cpu/lightmapper_cpu.cpp [hunk 8]
```diff
@@ -0,0 +1,1646 @@
...
+#include "core/os/os.h"
+#include "core/os/threaded_array_processor.h"
+#include "core/project_settings.h"
+#include "modules/raycast/lightmap_raycaster.h"
```
Comment (akien-mga) [inline modules/lightmapper_cpu/lightmapper_cpu.cpp:36]: That's tricky, do you properly handle the mutual dependency between each module? What happens if one builds with `module_raycast_enabled=no`?

File: modules/lightmapper_cpu/lightmapper_cpu.h [hunk 9]
```diff
@@ -0,0 +1,182 @@
...
+/*************************************************************************/
+
+#ifndef LIGHTMAPPER_CPU_H
+#define LIGHTMAPPER_CPU_H
+
+#include "core/local_vector.h"
+#include "scene/3d/lightmapper.h"
+#include "scene/resources/mesh.h"
+#include "scene/resources/surface_tool.h"
+#include <atomic>
```
Comment (akien-mga) [inline modules/lightmapper_cpu/lightmapper_cpu.h:38]:
```suggestion
#include "scene/resources/surface_tool.h"

#include <atomic>
```

File: modules/lightmapper_cpu/lightmapper_cpu.cpp (hunk 8 above)
Comment (akien-mga) [reply modules/lightmapper_cpu/lightmapper_cpu.cpp:36]: I see it's checked in `config.py` so it should be fine.

File: modules/lightmapper_cpu/register_types.cpp [hunk 10]
```diff
@@ -0,0 +1,55 @@
...
+/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                */
+/*************************************************************************/
+
+#include "register_types.h"
+
+#include "core/project_settings.h"
+#include "lightmapper_cpu.h"
+#include "scene/3d/lightmapper.h"
+
+#ifndef _3D_DISABLED
```
Comment (akien-mga) [inline modules/lightmapper_cpu/register_types.cpp:37]: It might be cleaner to check `not env["disable_3d"]` in `config.py:can_build()`, so you don't need to have guards here (here the `lightmapper_cpu.{cpp,h}` would still be built with 3D disabled, just not registered).

File: modules/raycast/godot_update_embree.py [hunk 11]
```diff
@@ -0,0 +1,259 @@
...
+    "kernels/bvh/bvh_intersector1.cpp",
+    "kernels/bvh/bvh_intersector1_bvh4.cpp",
+]
+
+os.chdir("../../thirdparty")
+
+if os.path.exists("embree"):
+    shutil.rmtree("embree")
+
+subprocess.run(["git", "clone", "https://github.com/embree/embree.git", "embree-tmp"])
```
Comment (akien-mga) [inline modules/raycast/godot_update_embree.py:80]: That's bad, we can't have our buildsystem depend on stuff which has to be downloaded from the Internet. It's a requirement for Linux distros that things can build without networking, and that builds should be reproducible - and that's a requirement that I believe is good for us to uphold as a project even for ourselves, we don't want thirdparty dependencies pulling the carpet under our feet.

Here we're depending on a git clone to build (without checking that git or network are available) and tracking the `master` branch, so it will change the result depending on when you clone.

Was it done this way because it's too big to bundle?

Comment (akien-mga) [reply modules/raycast/godot_update_embree.py:80]: Reading further, it seems to be done only to extract version information and generate a config header?
If so that's really overkill, we should have a static config header instead that is ready to use and match the source code we're vendoring. The script you wrote can still be put somewhere in `thirdparty/embree` to re-generate the config header manually whenever one of us is updating the lib, but it's not something that every single user should have to rebuild each time.

Comment (akien-mga) [reply modules/raycast/godot_update_embree.py:80]: Welp, and it *is* actually already a helper script not called by the buildsystem but used to update the thirdparty code... My bad, I read too fast and I thought I was reviewing the `SCsub` :)

I'd have put it in `thirdparty/embree` myself so that it's clear that it's used to update the thirdparty code, but it's not a big deal.

File: modules/raycast/lightmap_raycaster.cpp [hunk 12]
```diff
@@ -0,0 +1,196 @@
...
+/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.*/
+/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY  */
+/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,  */
+/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE     */
+/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                */
+/*************************************************************************/
+
+#include "lightmap_raycaster.h"
+#include "math/vec2.h"
+#include "math/vec3.h"
```
Comment (akien-mga) [inline modules/raycast/lightmap_raycaster.cpp:33]:
```suggestion
#include "lightmap_raycaster.h"

// From Embree.
#include <math/vec2.h>
#include <math/vec3.h>
```

`<>` makes it clear it's a system header and not a local include path. I added a comment as those are pretty generic names and it's hard to know if we're getting them from Godot's `core/math/` or another lib.

File: modules/raycast/lightmap_raycaster.h [hunk 13]
```diff
@@ -0,0 +1,72 @@
...
+/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY  */
+/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,  */
+/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE     */
+/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                */
+/*************************************************************************/
+
+#include "core/object.h"
+#include "scene/3d/lightmapper.h"
+#include "scene/resources/mesh.h"
+#include "thirdparty/embree/include/embree3/rtcore.h"
```
Comment (akien-mga) [inline modules/raycast/lightmap_raycaster.h:34]:
```suggestion
#include "scene/resources/mesh.h"

#include <embree3/rtcore.h>
```

Assuming the include path is properly set (it should be if the includes in the `.cpp` file work).

File: modules/raycast/register_types.cpp [hunk 14]
```diff
@@ -0,0 +1,39 @@
...
+/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF    */
+/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.*/
+/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY  */
+/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,  */
+/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE     */
+/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                */
+/*************************************************************************/
+
+#include "register_types.h"
+#include "lightmap_raycaster.h"
```
Comment (akien-mga) [inline modules/raycast/register_types.cpp:32]:
```suggestion
#include "register_types.h"

#include "lightmap_raycaster.h"
```

File: scene/3d/baked_lightmap.cpp [hunk 15]
```diff
@@ -727,51 +1190,125 @@ Ref<BakedLightmapData> BakedLightmap::get_light_data() const {
...
 
-void BakedLightmap::set_bake_mode(BakeMode p_mode) {
-	bake_mode = p_mode;
-}
-
-BakedLightmap::BakeMode BakedLightmap::get_bake_mode() const {
-	return bake_mode;
-}
-
+#ifndef DISABLE_DEPRECATED
```
Comment (akien-mga) [inline scene/3d/baked_lightmap.cpp:1236]: Since we're breaking compat already on the rest of the API, is this worth keeping as deprecated?

File: scene/3d/lightmapper.h [hunk 16]
```diff
@@ -0,0 +1,196 @@
...
+/*************************************************************************/
+
+#ifndef LIGHTMAPPER_H
+#define LIGHTMAPPER_H
+
+#include "scene/resources/mesh.h"
+
+#if !defined(__aligned)
+
+#if (defined(WIN32) || defined(_WIN32) || defined(__WIN32__) || defined(__NT__)) && !defined(__CYGWIN__)
```
Comment (akien-mga) [inline scene/3d/lightmapper.h:38]: Is that a very convoluted way to approximate `#ifdef _MSC_VER`? ;)

File: scene/3d/lightmapper.h [hunk 17]
```diff
@@ -0,0 +1,196 @@
...
+};
+
+class LightmapRaycaster : public Reference {
+	GDCLASS(LightmapRaycaster, Reference)
+protected:
+	static LightmapRaycaster *(*create_function)();
+
+public:
+	// compatible with embree3 rays
+	struct __aligned(16) Ray {
```
Comment (akien-mga) [inline scene/3d/lightmapper.h:63]: Architecture wise, why is `LightmapRaycaster` part of `scene` when it seems designed only for use with Embree which is in `modules/raycast`? Should it all be in `modules/lightmapper` that would build all relevant dependencies and only make the `Lightmapper` node available when that module is built?

In other words, is there a use case for the modularity offered by having a generic structure in core, that is then enabled only by specific modules for each component?

To clarify, while most modules build a single thirdparty library, that's not a requirement. Modules are for content that can be enabled/disabled as needed, and if several libraries are necessary for either part to make sense as a whole, they can all be together.

File: scene/resources/mesh.cpp [hunk 18]
```diff
@@ -30,11 +30,14 @@
 
 #include "mesh.h"
 
+#include "core/local_vector.h"
 #include "core/pair.h"
 #include "scene/resources/concave_polygon_shape.h"
 #include "scene/resources/convex_polygon_shape.h"
 #include "surface_tool.h"
 
+#include "core/crypto/crypto_core.h"
```
Comment (akien-mga) [inline scene/resources/mesh.cpp:39]:
```suggestion
#include "core/crypto/crypto_core.h"
#include "core/local_vector.h"
#include "core/pair.h"
#include "scene/resources/concave_polygon_shape.h"
#include "scene/resources/convex_polygon_shape.h"
#include "surface_tool.h"
```

File: thirdparty/README.md [hunk 19]
```diff
@@ -35,6 +35,21 @@ Files extracted from upstream source:
...
+## embree
+
+- Upstream: https://github.com/embree/embree
+- Version: 3.12.1 (69bd4c272f1ed608494f233ecfff3feec516880b, 2020)
+- License: Apache 2.0
+
+Files extracted from upstream:
+
+- All cpp files listed in `modules/raytrace/godot_update_embree.py`
+- All header files in the directories listed in `modules/raytrace/godot_update_embree.py`
```
Comment (akien-mga) [inline thirdparty/README.md:47]: I'd document usage of that script to update Embree.

File: thirdparty/README.md [hunk 20]
```diff
@@ -35,6 +35,21 @@ Files extracted from upstream source:
...
+
+Some minor changes have been made in order to fix build errors.
+They are marked with `// -- GODOT start --` and `// -- GODOT end --`
+comments.
```
Comment (akien-mga) [inline thirdparty/README.md:51]: Could you make a patch file with those changes so they're easy to re-apply on update?

File: thirdparty/README.md [hunk 21]
```diff
@@ -329,6 +344,10 @@ Collection of single-file libraries used in Godot components.
   * Upstream: https://github.com/ivanfratric/polypartition (`src/polypartition.cpp`)
   * Version: TBD, class was renamed
   * License: MIT
+- `stb_rect_pack.h`
```
Comment (akien-mga) [inline thirdparty/README.md:347]: Should be ordered alphabetically.

File: thirdparty/README.md [hunk 22]
```diff
@@ -488,7 +538,7 @@ File extracted from upstream release tarball:
 ## xatlas
 
 - Upstream: https://github.com/jpcy/xatlas
-- Version: git (5571fc7ef0d06832947c0a935ccdcf083f7a9264, 2020)
+- Version: git (470576d3516f7e6d8b4554e7c941194a935969fd, 2020)
```
Comment (akien-mga) [inline thirdparty/README.md:541]: Rebase error I think, we updated with df047e56fea8a211ef1e5f7150ead5d6251bc25d.

**Review by akien-mga — COMMENTED** [review]
Looks good to me overall. I left some style nitpicks and questions.

Could you add documentation for the changed APIs? (Sync with `godot --doctool .`)
You might want to rebase too as I just merged a lot of cherry-picks (shouldn't impact this specifically, but you never know).

Any idea on the impact all this has on binary size for the editor and export templates?

**Comment by lawnjelly** [comment]
Sorry I wasn't able to spend a lot of time looking, I've mainly just looked at the functionality of this version. I've only looked at the lightmap generation and not the use in a game situation. Overall it seems quite polished, and the user interface is nice and it tends to produce usable results. :+1: :smile: 

Just to point out a few nitpicks:
* Lights don't seem to have volume, so you don't get soft shadows (at least in the first pass). This is one of the major advantages of baked light so it would be nice to get this in the next version. You can get soft light by using emission or sky however.

You can also see aliasing which occurs with thin geometry, this can be also dealt with by volumetric lights. Look at the shadows cast by the railings:
lightmap_aliasing

* Skies - In general I think this is problematic in godot, not just in lightmap but in the PBR. The problem is getting a blue hue from blue skies. This is a standard sky (boosted a bit because it is seems overly hard to get it light enough to appear on the lightmap):

lightmap_sunandsky

This is understandable because most of the samples are hitting blue sky in the procedural sky.

This is turning down the blue energy to zero and turning up the sun itself (which is white):
lightmap_sunonly
Color is better, but because of the stochastic samples, a lot are hitting zero energy sky.

This also happens with PBR shading. I suspect the problem is two fold:
1) The balance between the energy of the direct sunlight and the diffuse from the blue sky is incorrect (probably that the sun contains way more energy than it appears)
2) Our eyes auto compensate for this white balance in shade from direct sunlight. This happens in real life but not in a photo.
See:
https://wtamu.edu/~cbaird/sq/2014/02/10/why-doesnt-the-outside-world-appear-blue-even-though-so-much-light-comes-from-the-blue-sky/

## Codewise
As the denoiser and embree are quite large libraries, I'd just like to confirm:

* They are not compiled in to non-tools builds
* They are easily compile-outable with an scons switch

This second point is so that devs who are working normally often end up having something cause a rebuild all, and it would be nice to be able to remove this functionality to decrease build time.

Overall though great work! :grinning: :+1:

**Comment by akien-mga** [comment]
I'm testing a build on the official buildsystem to compare it with a build of `3.2` without this PR, but Embree build fails with MinGW for Windows:
```
thirdparty/embree/common/sys/library.cpp: In function 'void* embree::getSymbol(embree::lib_t, const string&)':
thirdparty/embree/common/sys/library.cpp:30:26: error: invalid conversion from 'FARPROC' {aka 'long long int (*)()'} to 'void*' [-fpermissive]
   30 |     return GetProcAddress(HMODULE(lib),sym.c_str());
      |            ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                          |
      |                          FARPROC {aka long long int (*)()}
```
```
scons: *** [thirdparty/embree/common/sys/library.windows.opt.tools.64.o] Error 1
In file included from thirdparty/embree/common/sys/../math/vec2.h:6,
                 from thirdparty/embree/common/sys/string.h:7,
                 from thirdparty/embree/common/sys/string.cpp:4:
thirdparty/embree/common/sys/../math/math.h:19:22: error: redefinition of 'bool std::isinf(float)'
   19 |   __forceinline bool isinf ( const float x ) { return _finite(x) == 0; }
      |                      ^~~~~
In file included from /usr/x86_64-w64-mingw32/sys-root/mingw/include/c++/math.h:36,
                 from thirdparty/embree/common/sys/../math/constants.h:11,
                 from thirdparty/embree/common/sys/../math/math.h:8,
                 from thirdparty/embree/common/sys/../math/vec2.h:6,
                 from thirdparty/embree/common/sys/string.h:7,
                 from thirdparty/embree/common/sys/string.cpp:4:
/usr/x86_64-w64-mingw32/sys-root/mingw/include/c++/cmath:584:3: note: 'constexpr bool std::isinf(float)' previously defined here
  584 |   isinf(float __x)
      |   ^~~~~
In file included from thirdparty/embree/common/sys/../math/vec2.h:6,
                 from thirdparty/embree/common/sys/string.h:7,
                 from thirdparty/embree/common/sys/string.cpp:4:
thirdparty/embree/common/sys/../math/math.h:20:22: error: redefinition of 'bool std::isnan(float)'
   20 |   __forceinline bool isnan ( const float x ) { return _isnan(x) != 0; }
      |                      ^~~~~
In file included from /usr/x86_64-w64-mingw32/sys-root/mingw/include/c++/math.h:36,
                 from thirdparty/embree/common/sys/../math/constants.h:11,
                 from thirdparty/embree/common/sys/../math/math.h:8,
                 from thirdparty/embree/common/sys/../math/vec2.h:6,
                 from thirdparty/embree/common/sys/string.h:7,
                 from thirdparty/embree/common/sys/string.cpp:4:
/usr/x86_64-w64-mingw32/sys-root/mingw/include/c++/cmath:611:3: note: 'constexpr bool std::isnan(float)' previously defined here
  611 |   isnan(float __x)
      |   ^~~~~
In file included from thirdparty/embree/common/sys/../math/vec2.h:6,
                 from thirdparty/embree/common/sys/string.h:7,
                 from thirdparty/embree/common/sys/string.cpp:4:
thirdparty/embree/common/sys/../math/math.h:21:22: error: redefinition of 'bool std::isfinite(float)'
   21 |   __forceinline bool isfinite (const float x) { return _finite(x) != 0; }
      |                      ^~~~~~~~
In file included from /usr/x86_64-w64-mingw32/sys-root/mingw/include/c++/math.h:36,
                 from thirdparty/embree/common/sys/../math/constants.h:11,
                 from thirdparty/embree/common/sys/../math/math.h:8,
                 from thirdparty/embree/common/sys/../math/vec2.h:6,
                 from thirdparty/embree/common/sys/string.h:7,
                 from thirdparty/embree/common/sys/string.cpp:4:
/usr/x86_64-w64-mingw32/sys-root/mingw/include/c++/cmath:562:3: note: 'constexpr bool std::isfinite(float)' previously defined here
  562 |   isfinite(float __x)
      |   ^~~~~~~~
```

Detailed log: [mingw-embree.log](https://github.com/godotengine/godot/files/5753931/mingw-embree.log)

**Comment by akien-mga** [comment]
I'm also getting a build failure for Embree on Linux 32-bit (on Ubuntu 14.04 with GCC 9):
```
In file included from thirdparty/embree/common/lexers/../sys/../math/../simd/sse.h:33,
                 from thirdparty/embree/common/lexers/../sys/../math/vec2fa.h:8,
                 from thirdparty/embree/common/lexers/../sys/../math/vec2.h:206,
                 from thirdparty/embree/common/lexers/../sys/string.h:7,
                 from thirdparty/embree/common/lexers/stream.h:9,
                 from thirdparty/embree/common/lexers/stringstream.h:6,
                 from thirdparty/embree/common/lexers/stringstream.cpp:4:
thirdparty/embree/common/lexers/../sys/../math/../simd/vint4_sse2.h: In function 'size_t embree::toSizeT(const vint4&)':
thirdparty/embree/common/lexers/../sys/../math/../simd/vint4_sse2.h:450:12: error: '_mm_cvtsi128_si64' was not declared in this scope; did you mean '_mm_cvtsi128_si32'?
  450 |     return _mm_cvtsi128_si64(v);
      |            ^~~~~~~~~~~~~~~~~
      |            _mm_cvtsi128_si32
```

We should also make sure that SSE2 support is not assumed as it's not a given on ix86. Our buildsystem has SSE2 support and compiles binary for it, but for example on my Linux distro the i586 is without SSE2 so the generated binaries have greater compability (it's arguable whether using Embree without SSE2 on a Pentium III is really worth the pain, but well ;)).

**Comment by akien-mga** [comment]
> We should also make sure that SSE2 support is not assumed as it's not a given on ix86. Our buildsystem has SSE2 support and compiles binary for it, but for example on my Linux distro the i586 is without SSE2 so the generated binaries have greater compability (it's arguable whether using Embree without SSE2 on a Pentium III is really worth the pain, but well ;)).

Note that OIDN is only built on 64-bit desktop platforms - maybe the same treatment should be given to Embree? Or is there a use for embree raycasting without denoising?

File: modules/raycast/config.py [hunk 23]
```diff
@@ -0,0 +1,6 @@
+def can_build(env, platform):
+    return env["tools"] and platform not in ["android", "ios"]
```
Comment (akien-mga) [inline modules/raycast/config.py:2]: If we decide not to build it on 32-bit for https://github.com/godotengine/godot/pull/44628#issuecomment-752416916, maybe this test should be further improved to match the oidn one. I'm not sure it makes sense to build embree for JavaScript tools?

**Comment by akien-mga** [comment]
OIDN fails building on macOS ARM64:
```
/root/osxcross/target/bin/arm64-apple-darwin20-c++ -o thirdparty/oidn/core/api.osx.opt.tools.arm64.o -c -std=gnu++14 -w -O2 -arch arm64 -mmacosx-version-min=10.15 -w -Werror=return-type -w -DDEBUG_ENABLED -D__MACPORTS__ -DOSX_ENABLED -DUNIX_ENABLED -DGLES_ENABLED -DAPPLE_STYLE_KEYS -DCOREAUDIO_ENABLED -DCOREMIDI_ENABLED -DGL_SILENCE_DEPRECATION -DPTRCALL_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DMODULE_BMP_ENABLED -DMODULE_BULLET_ENABLED -DMODULE_CAMERA_ENABLED -DMODULE_CSG_ENABLED -DMODULE_CVTT_ENABLED -DMODULE_DDS_ENABLED -DMODULE_DENOISE_ENABLED -DMKLDNN_THR=MKLDNN_THR_SEQ -DOIDN_STATIC_LIB -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DDISABLE_VERBOSE -DMKLDNN_ENABLE_CONCURRENT_EXEC -DNDEBUG -Ithirdparty/oidn -Ithirdparty/oidn/include -Ithirdparty/oidn/mkl-dnn/include -Ithirdparty/oidn/mkl-dnn/src -Ithirdparty/oidn/mkl-dnn/src/common -Ithirdparty/oidn/mkl-dnn/src/cpu/xbyak -Ithirdparty/oidn/mkl-dnn/src/cpu -Ithirdparty/libpng -Ithirdparty/glad -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/osx -I. thirdparty/oidn/core/api.cpp
/root/osxcross/target/bin/arm64-apple-darwin20-c++ -o thirdparty/oidn/core/device.osx.opt.tools.arm64.o -c -std=gnu++14 -w -O2 -arch arm64 -mmacosx-version-min=10.15 -w -Werror=return-type -w -DDEBUG_ENABLED -D__MACPORTS__ -DOSX_ENABLED -DUNIX_ENABLED -DGLES_ENABLED -DAPPLE_STYLE_KEYS -DCOREAUDIO_ENABLED -DCOREMIDI_ENABLED -DGL_SILENCE_DEPRECATION -DPTRCALL_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DMODULE_BMP_ENABLED -DMODULE_BULLET_ENABLED -DMODULE_CAMERA_ENABLED -DMODULE_CSG_ENABLED -DMODULE_CVTT_ENABLED -DMODULE_DDS_ENABLED -DMODULE_DENOISE_ENABLED -DMKLDNN_THR=MKLDNN_THR_SEQ -DOIDN_STATIC_LIB -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DDISABLE_VERBOSE -DMKLDNN_ENABLE_CONCURRENT_EXEC -DNDEBUG -Ithirdparty/oidn -Ithirdparty/oidn/include -Ithirdparty/oidn/mkl-dnn/include -Ithirdparty/oidn/mkl-dnn/src -Ithirdparty/oidn/mkl-dnn/src/common -Ithirdparty/oidn/mkl-dnn/src/cpu/xbyak -Ithirdparty/oidn/mkl-dnn/src/cpu -Ithirdparty/libpng -Ithirdparty/glad -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/osx -I. thirdparty/oidn/core/device.cpp
/root/osxcross/target/bin/arm64-apple-darwin20-c++ -o thirdparty/oidn/core/filter.osx.opt.tools.arm64.o -c -std=gnu++14 -w -O2 -arch arm64 -mmacosx-version-min=10.15 -w -Werror=return-type -w -DDEBUG_ENABLED -D__MACPORTS__ -DOSX_ENABLED -DUNIX_ENABLED -DGLES_ENABLED -DAPPLE_STYLE_KEYS -DCOREAUDIO_ENABLED -DCOREMIDI_ENABLED -DGL_SILENCE_DEPRECATION -DPTRCALL_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DMODULE_BMP_ENABLED -DMODULE_BULLET_ENABLED -DMODULE_CAMERA_ENABLED -DMODULE_CSG_ENABLED -DMODULE_CVTT_ENABLED -DMODULE_DDS_ENABLED -DMODULE_DENOISE_ENABLED -DMKLDNN_THR=MKLDNN_THR_SEQ -DOIDN_STATIC_LIB -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DDISABLE_VERBOSE -DMKLDNN_ENABLE_CONCURRENT_EXEC -DNDEBUG -Ithirdparty/oidn -Ithirdparty/oidn/include -Ithirdparty/oidn/mkl-dnn/include -Ithirdparty/oidn/mkl-dnn/src -Ithirdparty/oidn/mkl-dnn/src/common -Ithirdparty/oidn/mkl-dnn/src/cpu/xbyak -Ithirdparty/oidn/mkl-dnn/src/cpu -Ithirdparty/libpng -Ithirdparty/glad -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/osx -I. thirdparty/oidn/core/filter.cpp
/root/osxcross/target/bin/arm64-apple-darwin20-c++ -o thirdparty/oidn/core/network.osx.opt.tools.arm64.o -c -std=gnu++14 -w -O2 -arch arm64 -mmacosx-version-min=10.15 -w -Werror=return-type -w -DDEBUG_ENABLED -D__MACPORTS__ -DOSX_ENABLED -DUNIX_ENABLED -DGLES_ENABLED -DAPPLE_STYLE_KEYS -DCOREAUDIO_ENABLED -DCOREMIDI_ENABLED -DGL_SILENCE_DEPRECATION -DPTRCALL_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DMODULE_BMP_ENABLED -DMODULE_BULLET_ENABLED -DMODULE_CAMERA_ENABLED -DMODULE_CSG_ENABLED -DMODULE_CVTT_ENABLED -DMODULE_DDS_ENABLED -DMODULE_DENOISE_ENABLED -DMKLDNN_THR=MKLDNN_THR_SEQ -DOIDN_STATIC_LIB -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DDISABLE_VERBOSE -DMKLDNN_ENABLE_CONCURRENT_EXEC -DNDEBUG -Ithirdparty/oidn -Ithirdparty/oidn/include -Ithirdparty/oidn/mkl-dnn/include -Ithirdparty/oidn/mkl-dnn/src -Ithirdparty/oidn/mkl-dnn/src/common -Ithirdparty/oidn/mkl-dnn/src/cpu/xbyak -Ithirdparty/oidn/mkl-dnn/src/cpu -Ithirdparty/libpng -Ithirdparty/glad -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/osx -I. thirdparty/oidn/core/network.cpp
/root/osxcross/target/bin/arm64-apple-darwin20-c++ -o thirdparty/oidn/core/autoencoder.osx.opt.tools.arm64.o -c -std=gnu++14 -w -O2 -arch arm64 -mmacosx-version-min=10.15 -w -Werror=return-type -w -DDEBUG_ENABLED -D__MACPORTS__ -DOSX_ENABLED -DUNIX_ENABLED -DGLES_ENABLED -DAPPLE_STYLE_KEYS -DCOREAUDIO_ENABLED -DCOREMIDI_ENABLED -DGL_SILENCE_DEPRECATION -DPTRCALL_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DMODULE_BMP_ENABLED -DMODULE_BULLET_ENABLED -DMODULE_CAMERA_ENABLED -DMODULE_CSG_ENABLED -DMODULE_CVTT_ENABLED -DMODULE_DDS_ENABLED -DMODULE_DENOISE_ENABLED -DMKLDNN_THR=MKLDNN_THR_SEQ -DOIDN_STATIC_LIB -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DDISABLE_VERBOSE -DMKLDNN_ENABLE_CONCURRENT_EXEC -DNDEBUG -Ithirdparty/oidn -Ithirdparty/oidn/include -Ithirdparty/oidn/mkl-dnn/include -Ithirdparty/oidn/mkl-dnn/src -Ithirdparty/oidn/mkl-dnn/src/common -Ithirdparty/oidn/mkl-dnn/src/cpu/xbyak -Ithirdparty/oidn/mkl-dnn/src/cpu -Ithirdparty/libpng -Ithirdparty/glad -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/osx -I. thirdparty/oidn/core/autoencoder.cpp
/root/osxcross/target/bin/arm64-apple-darwin20-c++ -o thirdparty/oidn/core/transfer_function.osx.opt.tools.arm64.o -c -std=gnu++14 -w -O2 -arch arm64 -mmacosx-version-min=10.15 -w -Werror=return-type -w -DDEBUG_ENABLED -D__MACPORTS__ -DOSX_ENABLED -DUNIX_ENABLED -DGLES_ENABLED -DAPPLE_STYLE_KEYS -DCOREAUDIO_ENABLED -DCOREMIDI_ENABLED -DGL_SILENCE_DEPRECATION -DPTRCALL_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DMODULE_BMP_ENABLED -DMODULE_BULLET_ENABLED -DMODULE_CAMERA_ENABLED -DMODULE_CSG_ENABLED -DMODULE_CVTT_ENABLED -DMODULE_DDS_ENABLED -DMODULE_DENOISE_ENABLED -DMKLDNN_THR=MKLDNN_THR_SEQ -DOIDN_STATIC_LIB -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DDISABLE_VERBOSE -DMKLDNN_ENABLE_CONCURRENT_EXEC -DNDEBUG -Ithirdparty/oidn -Ithirdparty/oidn/include -Ithirdparty/oidn/mkl-dnn/include -Ithirdparty/oidn/mkl-dnn/src -Ithirdparty/oidn/mkl-dnn/src/common -Ithirdparty/oidn/mkl-dnn/src/cpu/xbyak -Ithirdparty/oidn/mkl-dnn/src/cpu -Ithirdparty/libpng -Ithirdparty/glad -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/osx -I. thirdparty/oidn/core/transfer_function.cpp
In file included from thirdparty/oidn/core/api.cpp:48:
In file included from thirdparty/oidn/core/device.h:19:
In file included from thirdparty/oidn/core/common.h:19:
In file included from thirdparty/oidn/common/platform.h:27:
In file included from /usr/bin/../lib64/clang/10.0.1/include/xmmintrin.h:13:
[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:33:5: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?[0m
    __builtin_ia32_emms();
[0;1;32m    ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:33:5: [0m[0;1;30mnote: [0m'__builtin_isless' declared here[0m
[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:33:25: [0m[0;1;31merror: [0m[1mtoo few arguments to function call, expected 2, have 0[0m
    __builtin_ia32_emms();
[0;1;32m                        ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:50:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_vec_init_v2si'[0m
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:67:12: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_vec_ext_v2si'[0m
    return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
[0;1;32m           ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:129:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_packsswb'[0m
    return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0mIn file included from thirdparty/oidn/core/device.cpp:17:
In file included from thirdparty/oidn/core/device.h:19:
In file included from thirdparty/oidn/core/common.h:19:
In file included from thirdparty/oidn/common/platform.h:27:
In file included from /usr/bin/../lib64/clang/10.0.1/include/xmmintrin.h:13:
[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:33:5: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?[0m
    __builtin_ia32_emms();
[0;1;32m    ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:33:5: [0m[0;1;30mnote: [0m'__builtin_isless' declared here[0m
[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:33:25: [0m[0;1;31merror: [0m[1mtoo few arguments to function call, expected 2, have 0[0m
    __builtin_ia32_emms();
[0;1;32m                        ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:159:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_packssdw'[0m
    return (__m64)__builtin_ia32_packssdw((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:50:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_vec_init_v2si'[0m
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:189:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_packuswb'[0m
    return (__m64)__builtin_ia32_packuswb((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^[1m
[0m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:67:12: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_vec_ext_v2si'[0m
    return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
[0;1;32m           ^
[0mIn file included from thirdparty/oidn/core/filter.cpp:17:
In file included from thirdparty/oidn/core/filter.h:19:
In file included from thirdparty/oidn/core/common.h:19:
In file included from thirdparty/oidn/common/platform.h:27:
In file included from /usr/bin/../lib64/clang/10.0.1/include/xmmintrin.h:13:
[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:33:5: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?[0m
    __builtin_ia32_emms();
[0;1;32m    ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:33:5: [0m[0;1;30mnote: [0m'__builtin_isless' declared here[0m
[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:33:25: [0m[0;1;31merror: [0m[1mtoo few arguments to function call, expected 2, have 0[0m
    __builtin_ia32_emms();
[0;1;32m                        ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:129:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_packsswb'[0m
    return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:50:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_vec_init_v2si'[0m
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:216:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpckhbw'[0m
    return (__m64)__builtin_ia32_punpckhbw((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:159:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_packssdw'[0m
    return (__m64)__builtin_ia32_packssdw((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:67:12: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_vec_ext_v2si'[0m
    return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
[0;1;32m           ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:239:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpckhwd'[0m
    return (__m64)__builtin_ia32_punpckhwd((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:189:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_packuswb'[0m
    return (__m64)__builtin_ia32_packuswb((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:129:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_packsswb'[0m
    return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:260:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpckhdq'[0m
    return (__m64)__builtin_ia32_punpckhdq((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:216:[1m19/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:: 159[0m:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_packssdw'[0;1;31m[0merror
: [0m[1muse of undeclared identifier '__builtin_ia32_punpckhbw'[0m
    return (__m64)__builtin_ia32_packssdw((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m    return (__m64)__builtin_ia32_punpckhbw((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:287:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpcklbw'[0m
    return (__m64)__builtin_ia32_punpcklbw((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:189:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_packuswb'[0m
    return (__m64)__builtin_ia32_packuswb((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:239:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpckhwd'[0m
    return (__m64)__builtin_ia32_punpckhwd((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:310:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpcklwd'[0m
    return (__m64)__builtin_ia32_punpcklwd((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0mIn file included from thirdparty/oidn/core/network.cpp:17:
In file included from thirdparty/oidn/core/upsample.h:19:
In file included from thirdparty/oidn/core/node.h:19:
In file included from thirdparty/oidn/core/common.h:19:
In file included from thirdparty/oidn/common/platform.h:27:
In file included from /usr/bin/../lib64/clang/10.0.1/include/xmmintrin.h:13:
[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:33:5: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?[0m
    __builtin_ia32_emms();
[0;1;32m    ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:33:5: [0m[0;1;30m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:216:19: [0m[0;1;31merror: [0m[1mnote: [0muse of undeclared identifier '__builtin_ia32_punpckhbw''__builtin_isless' declared here[0m
[0m
    return (__m64)__builtin_ia32_punpckhbw((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:33:25: [0m[0;1;31merror: [0m[1mtoo few arguments to function call, expected 2, have 0[0m
    __builtin_ia32_emms();
[0;1;32m                        ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:260:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpckhdq'[0m
    return (__m64)__builtin_ia32_punpckhdq((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:50:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_vec_init_v2si'[0m
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:331:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpckldq'[0m
    return (__m64)__builtin_ia32_punpckldq((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:239:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpckhwd'[0m
    return (__m64)__builtin_ia32_punpckhwd((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:287:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpcklbw'[0m
    return (__m64)__builtin_ia32_punpcklbw((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;31merror: [0m[1m[1muse of undeclared identifier '__builtin_ia32_paddb'; did you mean '__builtin_arm_addg'?/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h[0m:
67:12: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_vec_ext_v2si'[0m
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
    return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);[0;1;32m
                  ^[0;1;32m
           ^[0m
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;30mnote: [0m'__builtin_arm_addg' declared here[0m
[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;31merror: [0m[1mfirst argument of MTE builtin function must be a pointer ('__v8qi' (vector of 8 'char' values) invalid)[0m
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^                    ~~~~~~~~~~~~
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:260:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpckhdq'[0m
    return (__m64)__builtin_ia32_punpckhdq((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:310:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpcklwd'[0m
    return (__m64)__builtin_ia32_punpcklwd((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:129:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_packsswb'[0m
    return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:373:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_paddw'; did you mean '__builtin_arm_addg'?[0m
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;30mnote: [0m'__builtin_arm_addg' declared here[0m
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:373:19: [0m[0;1;31merror: [0m[1mfirst argument of MTE builtin function must be a pointer ('__v4hi' (vector of 4 'short' values) invalid)[0m
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^                    ~~~~~~~~~~~~
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:287:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpcklbw'[0m
    return (__m64)__builtin_ia32_punpcklbw((__v8qi)__m1, (__v8qi)__m2);In file included from 
[0;1;32m                  ^
[0mthirdparty/oidn/core/autoencoder.cpp:17:
In file included from thirdparty/oidn/core/autoencoder.h:19:
In file included from thirdparty/oidn/core/filter.h:19:
In file included from thirdparty/oidn/core/common.h:19:
In file included from thirdparty/oidn/common/platform.h:27:
In file included from /usr/bin/../lib64/clang/10.0.1/include/xmmintrin.h:13:
[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:33:5: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?[0m
    __builtin_ia32_emms();
[0;1;32m    ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:33:5: [0m[0;1;30mnote: [0m'__builtin_isless' declared here[0m
[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:33:25: [0m[0;1;31merror: [0m[1mtoo few arguments to function call, expected 2, have 0[0m
    __builtin_ia32_emms();
[0;1;32m                        ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:331:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpckldq'[0m
    return (__m64)__builtin_ia32_punpckldq((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:159:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_packssdw'[0m
    return (__m64)__builtin_ia32_packssdw((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:394:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_paddd'; did you mean '__builtin_arm_addg'?[0m
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;30mnote: [0m'__builtin_arm_addg' declared here[0m
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:394:19: [0m[0;1;31merror: [0m[1mfirst argument of MTE builtin function must be a pointer ('__v2si' (vector of 2 'int' values) invalid)[0m
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^                    ~~~~~~~~~~~~
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:310:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpcklwd'[0m
    return (__m64)__builtin_ia32_punpcklwd((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:50:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_vec_init_v2si'[0m
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_paddb'; did you mean '__builtin_arm_addg'?[0m
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;30mnote: [0m'__builtin_arm_addg' declared here[0m
[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;31merror: [0m[1mfirst argument of MTE builtin function must be a pointer ('__v8qi' (vector of 8 'char' values) invalid)[0m
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^                    ~~~~~~~~~~~~
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:189:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_packuswb'[0m
    return (__m64)__builtin_ia32_packuswb((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[0;1;31mfatal error: [0mtoo many errors emitted, stopping now [-ferror-limit=][0m
[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:331:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpckldq'[0m
    return (__m64)__builtin_ia32_punpckldq((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:67:12: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_vec_ext_v2si'[0m
    return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
[0;1;32m           ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:373:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_paddw'; did you mean '__builtin_arm_addg'?[0m
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[1m[0m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:[1m216:19: /usr/bin/../lib64/clang/10.0.1/include/mmintrin.h[0m:[0;1;31m352error:: [0m[1muse of undeclared identifier '__builtin_ia32_punpckhbw'19: [0m[0;1;30mnote: [0m'__builtin_arm_addg' declared here[0m
[0m
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m    return (__m64)__builtin_ia32_punpckhbw((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:373:19: [0m[0;1;31merror: [0m[1mfirst argument of MTE builtin function must be a pointer ('__v4hi' (vector of 4 'short' values) invalid)[0m
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^                    ~~~~~~~~~~~~
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_paddb'; did you mean '__builtin_arm_addg'?[0m
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;30mnote: [0m'__builtin_arm_addg' declared here[0m
[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19:In file included from  thirdparty/oidn/core/transfer_function.cpp[0m:[0;1;31m17error:
: In file included from [0mthirdparty/oidn/core/transfer_function.h[1mfirst argument of MTE builtin function must be a pointer ('__v8qi' (vector of 8 'char' values) invalid):[0m
19:
In file included from thirdparty/oidn/core/image.h:    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);19
:
In file included from thirdparty/oidn/core/common.h:[0;1;32m                  ^                    ~~~~~~~~~~~~
[0m19:
In file included from thirdparty/oidn/common/platform.h:27:
In file included from /usr/bin/../lib64/clang/10.0.1/include/xmmintrin.h:13:
[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:33:5: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?[0m
    __builtin_ia32_emms();
[0;1;32m    ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:33:5: [0m[0;1;30mnote: [0m'__builtin_isless' declared here[0m
[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:33:25: [0m[0;1;31merror: [0m[1mtoo few arguments to function call, expected 2, have 0[0m
    __builtin_ia32_emms();
[0;1;32m                        ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:239:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpckhwd'[0m
    return (__m64)__builtin_ia32_punpckhwd((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:394:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_paddd'; did you mean '__builtin_arm_addg'?[0m
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;30mnote: [0m'__builtin_arm_addg' declared here[0m
[1m    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:129:19: [0m[0;1;31merror[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:394:19: [0m[0;1;31merror: : [0m[1muse of undeclared identifier '__builtin_ia32_packsswb'[0m
[0m    return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);[1mfirst argument of MTE builtin function must be a pointer ('__v2si' (vector of 2 'int' values) invalid)
[0;1;32m                  ^
[0m[0m
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^                    ~~~~~~~~~~~~
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:373:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_paddw'; did you mean '__builtin_arm_addg'?[0m
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;30mnote: [0m'__builtin_arm_addg' declared here[0m
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:373:19: [0m[0;1;31merror: [0m[1mfirst argument of MTE builtin function must be a pointer ('__v4hi' (vector of 4 'short' values) invalid)[0m
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^                    ~~~~~~~~~~~~
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:260:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpckhdq'[0m
    return (__m64)__builtin_ia32_punpckhdq((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:50:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_vec_init_v2si'[0m
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
[0;1;32m                  ^
[0m[0;1;31mfatal error: [0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:too many errors emitted, stopping now [-ferror-limit=][0m
159:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_packssdw'[0m
    return (__m64)__builtin_ia32_packssdw((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:394:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_paddd'; did you mean '__builtin_arm_addg'?[0m
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;30mnote: [0m'__builtin_arm_addg' declared here[0m
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:394:19: [0m[0;1;31merror: [0m[1mfirst argument of MTE builtin function must be a pointer ('__v2si' (vector of 2 'int' values) invalid)[0m
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^                    ~~~~~~~~~~~~
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:287:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpcklbw'[0m
    return (__m64)__builtin_ia32_punpcklbw((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:189:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_packuswb'[0m
    return (__m64)__builtin_ia32_packuswb((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:67:12: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_vec_ext_v2si'[0m
    return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
[0;1;32m           ^
[0m[0;1;31mfatal error: [0mtoo many errors emitted, stopping now [-ferror-limit=][0m
[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:310:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpcklwd'[0m
    return (__m64)__builtin_ia32_punpcklwd((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:216:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpckhbw'[0m
    return (__m64)__builtin_ia32_punpckhbw((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:129:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_packsswb'[0m
    return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:331:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpckldq'[0m
    return (__m64)__builtin_ia32_punpckldq((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:239:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpckhwd'[0m
    return (__m64)__builtin_ia32_punpckhwd((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:159:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_packssdw'[0m
    return (__m64)__builtin_ia32_packssdw((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_paddb'; did you mean '__builtin_arm_addg'?[0m
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;30mnote: [0m'__builtin_arm_addg' declared here[0m
[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;31merror: [0m[1mfirst argument of MTE builtin function must be a pointer ('__v8qi' (vector of 8 'char' values) invalid)[0m
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^                    ~~~~~~~~~~~~
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:373:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_paddw'; did you mean '__builtin_arm_addg'?[1m[0m
/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:260    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);:
19[0;1;32m:                  ^ 
[0m[1m[0m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h[0;1;31m:352:19:error : [0m[0;1;30m[0mnote[1m: use of undeclared identifier '__builtin_ia32_punpckhdq'[0m[0m'__builtin_arm_addg' declared here[0m

    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m    return (__m64)__builtin_ia32_punpckhdq((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^[1m
/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h[0m:373:19: [0m[0;1;31merror: [0m[1mfirst argument of MTE builtin function must be a pointer ('__v4hi' (vector of 4 'short' values) invalid)[0m
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^                    ~~~~~~~~~~~~
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:189:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_packuswb'[0m
    return (__m64)__builtin_ia32_packuswb((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:394:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_paddd'; did you mean '__builtin_arm_addg'?[0m
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;30mnote: [0m'__builtin_arm_addg' declared here[0m
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:394:19: [0m[0;1;31merror: [0m[1mfirst argument of MTE builtin function must be a pointer ('__v2si' (vector of 2 'int' values) invalid)[0m
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^                    ~~~~~~~~~~~~
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:287:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpcklbw'[0m
    return (__m64)__builtin_ia32_punpcklbw((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:216:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpckhbw'[0m
    return (__m64)__builtin_ia32_punpckhbw((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[0;1;31mfatal error: [0mtoo many errors emitted, stopping now [-ferror-limit=][0m
[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:310:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpcklwd'[0m
    return (__m64)__builtin_ia32_punpcklwd((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:239:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpckhwd'[0m
    return (__m64)__builtin_ia32_punpckhwd((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:331:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpckldq'[0m
    return (__m64)__builtin_ia32_punpckldq((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:260:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpckhdq'[0m
    return (__m64)__builtin_ia32_punpckhdq((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_paddb'; did you mean '__builtin_arm_addg'?[0m
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;30mnote: [0m'__builtin_arm_addg' declared here[0m
[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;31merror: [0m[1mfirst argument of MTE builtin function must be a pointer ('__v8qi' (vector of 8 'char' values) invalid)[0m
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^                    ~~~~~~~~~~~~
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:287:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpcklbw'[0m
    return (__m64)__builtin_ia32_punpcklbw((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:373:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_paddw'; did you mean '__builtin_arm_addg'?[0m
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;30mnote: [0m'__builtin_arm_addg' declared here[0m
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:373:19: [0m[0;1;31merror: [0m[1mfirst argument of MTE builtin function must be a pointer ('__v4hi' (vector of 4 'short' values) invalid)[0m
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^                    ~~~~~~~~~~~~
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:310:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpcklwd'[0m
    return (__m64)__builtin_ia32_punpcklwd((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:394:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_paddd'; did you mean '__builtin_arm_addg'?[0m
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;30mnote: [0m'__builtin_arm_addg' declared here[0m
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:394:19: [0m[0;1;31merror: [0m[1mfirst argument of MTE builtin function must be a pointer ('__v2si' (vector of 2 'int' values) invalid)[0m
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^                    ~~~~~~~~~~~~
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:331:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_punpckldq'[0m
    return (__m64)__builtin_ia32_punpckldq((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m[0;1;31mfatal error: [0mtoo many errors emitted, stopping now [-ferror-limit=][0m
[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_paddb'; did you mean '__builtin_arm_addg'?[0m
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;30mnote: [0m'__builtin_arm_addg' declared here[0m
[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;31merror: [0m[1mfirst argument of MTE builtin function must be a pointer ('__v8qi' (vector of 8 'char' values) invalid)[0m
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^                    ~~~~~~~~~~~~
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:373:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_paddw'; did you mean '__builtin_arm_addg'?[0m
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;30mnote: [0m'__builtin_arm_addg' declared here[0m
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:373:19: [0m[0;1;31merror: [0m[1mfirst argument of MTE builtin function must be a pointer ('__v4hi' (vector of 4 'short' values) invalid)[0m
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
[0;1;32m                  ^                    ~~~~~~~~~~~~
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:394:19: [0m[0;1;31merror: [0m[1muse of undeclared identifier '__builtin_ia32_paddd'; did you mean '__builtin_arm_addg'?[0m
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:352:19: [0m[0;1;30mnote: [0m'__builtin_arm_addg' declared here[0m
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
[0;1;32m                  ^
[0m[1m/usr/bin/../lib64/clang/10.0.1/include/mmintrin.h:394:19: [0m[0;1;31merror: [0m[1mfirst argument of MTE builtin function must be a pointer ('__v2si' (vector of 2 'int' values) invalid)[0m
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
[0;1;32m                  ^                    ~~~~~~~~~~~~
[0m[0;1;31mfatal error: [0mtoo many errors emitted, stopping now [-ferror-limit=][0m
```

**Comment by akien-mga** [comment]
As expected, JavaScript tools build (i.e. the Web editor) fails too:
```
Compiling ==> thirdparty/embree/common/sys/sysinfo.cpp
Compiling ==> thirdparty/embree/common/sys/alloc.cpp
em++: error: Passing any of -msse, -msse2, -msse3, -mssse3, -msse4.1, -msse4.2, -mavx, -mfpu=neon flags also requires passing -msimd128!
Compiling ==> thirdparty/embree/common/sys/filename.cpp
scons: *** [thirdparty/embree/common/sys/sysinfo.javascript.tools.threads.bc] Error 1
em++: error: Passing any of -msse, -msse2, -msse3, -mssse3, -msse4.1, -msse4.2, -mavx, -mfpu=neon flags also requires passing -msimd128!
scons: *** [thirdparty/embree/common/sys/filename.javascript.tools.threads.bc] Error 1
em++: error: Passing any of -msse, -msse2, -msse3, -mssse3, -msse4.1, -msse4.2, -mavx, -mfpu=neon flags also requires passing -msimd128!
scons: *** [thirdparty/embree/common/sys/alloc.javascript.tools.threads.bc] Error 1
scons: building terminated because of errors.
```

But as I commented above, I'd suggest excluding the `javascript` platform, I don't see much use case for baking lightmaps in a browser.

**Comment by Calinou** [comment]
> You can also see aliasing which occurs with thin geometry, this can be also dealt with by volumetric lights. Look at the shadows cast by the railings:

JFons is working on adding a bicubic sampling option in both GLES2 and GLES3, so this shouldn't be an issue as long as it's enabled.

**Comment by JFonS** [comment]
Well, that's a lot of feedback :) I'll try to go over everything starting from the top.

File: modules/lightmapper_cpu/register_types.cpp (hunk 10 above)
Comment (JFonS) [reply modules/lightmapper_cpu/register_types.cpp:37]: I copied this code straight from `master`, so it's probably better if we merge this as-is, fix it in master and cherry-pick it back.

File: scene/3d/baked_lightmap.cpp (hunk 15 above)
Comment (JFonS) [reply scene/3d/baked_lightmap.cpp:1236]: I think it makes sense to keep it, in case someone opens a project in 3.2.4 and then goes back to 3.2.3 or older. I tested this already and thing don't break too much, you get a broken dependency warning because the resource format can't be loaded, but re-baking lightmaps fixes everything.

It's a very small amount of code anyways, so I'd say we keep it.

File: scene/3d/lightmapper.h (hunk 17 above)
Comment (JFonS) [reply scene/3d/lightmapper.h:63]: I followed the same structure as LightmapDenoiser. Other than providing the possiblility of adding different raycast engines, this organization makes it easy to compile the editor when this module is disabled. AFAIK there is no real way to tell if a module is disabled outside the `modules` build environment, So there needs to be some common type in `scene` that may or may not be implemented by a module.

File: scene/3d/lightmapper.h (hunk 16 above)
Comment (JFonS) [reply scene/3d/lightmapper.h:38]: Not sure... I don't even remember where this code came from :) 

Once the rest of build issues are fixed, we can try to replace this with `#ifdef _MSC_VER` and see if everything still builds fine.

File: thirdparty/README.md (hunk 20 above)
Comment (JFonS) [reply thirdparty/README.md:51]: I thought I already did that, I'll give it a go.

**Comment by akien-mga** [comment]
Here's some size comparisons for a regular build from latest `3.2`, and this PR rebased on `3.2`.

- `3.2` branch:

```
.
├── [         23]  android
│   └── [        113]  templates
│       ├── [   49428456]  android_debug.apk
│       ├── [   40110146]  android_release.apk
│       ├── [   82106864]  android_source.zip
│       └── [   39059980]  godot-lib.release.aar
├── [         23]  ios
│   └── [        264]  templates
│       ├── [     216584]  libgodot_arkit_module.iphone.opt.debug.fat
│       ├── [     190280]  libgodot_arkit_module.iphone.opt.fat
│       ├── [     132536]  libgodot_camera_module.iphone.opt.debug.fat
│       ├── [     131336]  libgodot_camera_module.iphone.opt.fat
│       ├── [  136210968]  libgodot.iphone.opt.debug.fat
│       └── [  117375600]  libgodot.iphone.opt.fat
├── [         28]  linux
│   ├── [         36]  x64
│   │   ├── [         60]  templates
│   │   │   ├── [   41107244]  godot.x11.opt.64
│   │   │   └── [   45652743]  godot.x11.opt.debug.64
│   │   └── [         36]  tools
│   │       └── [   76173862]  godot.x11.opt.tools.64
│   └── [         36]  x86
│       ├── [         60]  templates
│       │   ├── [   39128047]  godot.x11.opt.32
│       │   └── [   43381449]  godot.x11.opt.debug.32
│       └── [         36]  tools
│           └── [   73226442]  godot.x11.opt.tools.32
├── [         36]  macosx
│   ├── [        196]  templates
│   │   ├── [   39369792]  godot.osx.opt.arm64
│   │   ├── [   41492288]  godot.osx.opt.debug.arm64
│   │   ├── [   84827968]  godot.osx.opt.debug.universal
│   │   ├── [   43320320]  godot.osx.opt.debug.x86_64
│   │   ├── [   79281216]  godot.osx.opt.universal
│   │   └── [   39891208]  godot.osx.opt.x86_64
│   └── [        110]  tools
│       ├── [   72495536]  godot.osx.opt.tools.arm64
│       ├── [  147009968]  godot.osx.opt.tools.universal
│       └── [   74507960]  godot.osx.opt.tools.x86_64
├── [         17]  server
│   └── [         36]  x64
│       ├── [         37]  templates
│       │   └── [   37544621]  godot_server.x11.opt.64
│       └── [         43]  tools
│           └── [   72539822]  godot_server.x11.opt.tools.64
└── [         28]  windows
    ├── [         36]  x64
    │   ├── [         76]  templates
    │   │   ├── [   56505699]  godot.windows.opt.64.exe
    │   │   └── [   60464046]  godot.windows.opt.debug.64.exe
    │   └── [         44]  tools
    │       └── [   91054428]  godot.windows.opt.tools.64.exe
    └── [         36]  x86
        ├── [         76]  templates
        │   ├── [   52606586]  godot.windows.opt.32.exe
        │   └── [   58225433]  godot.windows.opt.debug.32.exe
        └── [         44]  tools
            └── [   89310584]  godot.windows.opt.tools.32.exe
 
25 directories, 33 files
```

- Rebased PR (some builds missing, see above):

```
.
├── [         23]  android
│   └── [        113]  templates
│       ├── [   49472813]  android_debug.apk
│       ├── [   40135978]  android_release.apk
│       ├── [   82166268]  android_source.zip
│       └── [   39085813]  godot-lib.release.aar
├── [         23]  ios
│   └── [        264]  templates
│       ├── [     216584]  libgodot_arkit_module.iphone.opt.debug.fat
│       ├── [     190280]  libgodot_arkit_module.iphone.opt.fat
│       ├── [     132536]  libgodot_camera_module.iphone.opt.debug.fat
│       ├── [     131336]  libgodot_camera_module.iphone.opt.fat
│       ├── [  136406680]  libgodot.iphone.opt.debug.fat
│       └── [  117532496]  libgodot.iphone.opt.fat
├── [         28]  linux
│   ├── [         36]  x64
│   │   ├── [         60]  templates
│   │   │   ├── [   41084265]  godot.x11.opt.64
│   │   │   └── [   45653163]  godot.x11.opt.debug.64
│   │   └── [         36]  tools
│   │       └── [   84708475]  godot.x11.opt.tools.64
│   └── [          6]  x86
├── [          6]  macosx
├── [         17]  server
│   └── [         36]  x64
│       ├── [         37]  templates
│       │   └── [   37526857]  godot_server.x11.opt.64
│       └── [         43]  tools
│           └── [   81001905]  godot_server.x11.opt.tools.64
└── [          6]  windows
 
15 directories, 15 files
```

So macOS and Windows are missing as they broke mid-build, but for Linux we can see:

- Linux 64-bit tools build: 76173862 -> 84708475 (72.6 MB -> 80.8 MB, so it adds 8.2 MB / 11%).
- Linux 64-bit templates release build: 41107244 -> 41084265, so no change (actually got a bit smaller, likely more code removed than added when the modules are not compiled).

So it's a big increase for the editor binary, but it shouldn't impact game releases and it's still reasonable I guess.

**Comment by JFonS** [comment]
I updated the PR addressing most of the issues raised by @akien-mga, I think I'm only missing the Embree patch files.

I will look into the build issues next, I may have troubles reproducing some of the issues, though, especially the mac builds.

**Comment by JFonS** [comment]
@lawnjelly Adding light volume is not hard, in fact we already have some code by @RandomShaper adding support for it. But I wasn't sure how to properly define the size of each light. In 4.0 we already have a size property in `Light3D` which works on regular shadows. I could use the same property here, but it may be confusing because in 3.2 it would only work for lightmaps.

Regarding skies, the current approach is not great. I use a low level mip instead of a proper irradiance map because there's no easy way to get irradiance maps in 3.2., so that doesn't help either. But I'm not entirely sure how to improve the situation other than that.

Finally, both OIDN and Embree are compiled from modules, so you can just use `module_raycast_enabled`,  `module_denoise_enabled` and even `module_lightmapper_cpu_enabled` to pick and choose what you want to build :)

**Comment by NHodgesVFX** [comment]
> @lawnjelly Adding light volume is not hard, in fact we already have some code by @RandomShaper adding support for it. But I wasn't sure how to properly define the size of each light. In 4.0 we already have a size property in `Light3D` which works on regular shadows. I could use the same property here, but it may be confusing because in 3.2 it would only work for lightmaps.
> 
> Regarding skies, the current approach is not great. I use a low level mip instead of a proper irradiance map because there's no easy way to get irradiance maps in 3.2., so that doesn't help either. But I'm not entirely sure how to improve the situation other than that.
> 
> Finally, both OIDN and Embree are compiled from modules, so you can just use `module_raycast_enabled`, `module_denoise_enabled` and even `module_lightmapper_cpu_enabled` to pick and choose what you want to build :)
> 
> Edit: and all these modules are disabled on non-tools builds 👍

I think adding a light size paramter is fine just mention that is only works with the lightmapper in the tooltip and/or use a name like lightmap_light_size. that should alleviate any confusion.

**Comment by RandomShaper** [comment]
The code I added for light size, to get soft shadows (by the way, thanks, @JFonS, for the theory you taught me about that), works in a way that you configure size per type of light in the light bake node itself. Not sure if that's a good general-purpose option for Godot, but maybe it's a good compromise given what has been said about adding that per light.

**Comment by clayjohn** [comment]
> Regarding skies, the current approach is not great. I use a low level mip instead of a proper irradiance map because there's no easy way to get irradiance maps in 3.2., so that doesn't help either. But I'm not entirely sure how to improve the situation other than that.

GLES3 has a proper irradiance map that you can use! It helps a lot.

**Comment by JFonS** [comment]
> > Regarding skies, the current approach is not great. I use a low level mip instead of a proper irradiance map because there's no easy way to get irradiance maps in 3.2., so that doesn't help either. But I'm not entirely sure how to improve the situation other than that.
> 
> GLES3 has a proper irradiance map that you can use! It helps a lot.

Oh, that's interesting. I will check it out :)

**Comment by qarmin** [comment]
I have crash when trying to search help:

Zrzut ekranu z 2021-01-02 12-17-56

```
editor/editor_help_search.cpp:461:35: runtime error: member access within null pointer of type 'struct ClassDoc'
editor/editor_help_search.cpp:461:35: runtime error: reference binding to null pointer of type 'const struct String'
core/typedefs.h:292:82: runtime error: member call on null pointer of type 'const struct String'
core/ustring.cpp:456:18: runtime error: member call on null pointer of type 'const struct String'
core/ustring.cpp:431:11: runtime error: member call on null pointer of type 'const struct String'
core/ustring.h:315:51: runtime error: member call on null pointer of type 'const struct String'
core/ustring.h:196:15: runtime error: member call on null pointer of type 'const struct String'
core/ustring.h:153:56: runtime error: member access within null pointer of type 'const struct String'
core/ustring.h:153:56: runtime error: member call on null pointer of type 'const struct CowData'
core/ustring.h:153:43: runtime error: member access within null pointer of type 'const struct String'
core/cowdata.h:126:41: runtime error: member call on null pointer of type 'const struct CowData'
core/cowdata.h:71:8: runtime error: member access within null pointer of type 'const struct CowData'
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] bin/godot.x11.tools.64s() [0x16adeea] (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/platform/x11/crash_handler_x11.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f9dc8f37210] (??:0)
[3] CowData<wchar_t>::_get_size() const (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/./core/cowdata.h:71)
[4] CowData<wchar_t>::size() const (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/./core/cowdata.h:126)
[5] String::size() const (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/./core/ustring.h:153)
[6] String::length() const (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/./core/ustring.h:196)
[7] String::empty() const (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/./core/ustring.h:315)
[8] String::operator<(wchar_t const*) const (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/core/ustring.cpp:431)
[9] String::operator<(String const&) const (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/core/ustring.cpp:457)
[10] Map<String, TreeItem*, Comparator<String>, DefaultAllocator>::_find(String const&) const (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/./core/typedefs.h:292)
[11] Map<String, TreeItem*, Comparator<String>, DefaultAllocator>::find(String const&) const (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/./core/map.h:524)
[12] Map<String, TreeItem*, Comparator<String>, DefaultAllocator>::has(String const&) const (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/./core/map.h:557)
[13] EditorHelpSearch::Runner::_create_class_hierarchy(EditorHelpSearch::Runner::ClassMatch const&) (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/editor/editor_help_search.cpp:461)
[14] EditorHelpSearch::Runner::_create_class_hierarchy(EditorHelpSearch::Runner::ClassMatch const&) (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/editor/editor_help_search.cpp:471)
[15] EditorHelpSearch::Runner::_phase_class_items() (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/editor/editor_help_search.cpp:394)
[16] EditorHelpSearch::Runner::_slice() (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/editor/editor_help_search.cpp:296)
[17] EditorHelpSearch::Runner::work(unsigned long) (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/editor/editor_help_search.cpp:590)
[18] EditorHelpSearch::_notification(int) (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/editor/editor_help_search.cpp:127)
[19] EditorHelpSearch::_notificationv(int, bool) (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/editor/editor_help_search.h:42 (discriminator 14))
[20] Object::notification(int, bool) (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/core/object.cpp:931)
[21] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/scene/main/scene_tree.cpp:985)
[22] SceneTree::idle(float) (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/scene/main/scene_tree.cpp:525 (discriminator 3))
[23] Main::iteration() (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/main/main.cpp:2115)
[24] OS_X11::run() (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/platform/x11/os_x11.cpp:3608)
[25] bin/godot.x11.tools.64s(main+0x331) [0x16a4dd7] (/home/rafal/Pobrane/godot-new_cpu_lightmapper_3.2/platform/x11/godot_x11.cpp:57)
[26] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f9dc8f180b3] (??:0)
[27] bin/godot.x11.tools.64s(_start+0x2e) [0x16a49ee] (??:?)
-- END OF BACKTRACE --
Przerwane (zrzut pamięci)
```

**Comment by JFonS** [comment]
The crash reported by @qarmin seems to come from the fact that `Lightmapper` is not being picked by the doctool,while `LightmapperCPU` is. 

@akien-mga I'm not sure what's the policy on these editor-only and internal classes, should I just remove the `register_class` call from the `lightmapper_cpu` module?

I included it because I copied the module from master's `lightmapper_rd`, but removing it fixes the issue while keeping the functionality. Also, I wasn't planning on documenting the class anyways because its usage is only internal.

**Comment by JFonS** [comment]
@akien-mga Regarding the OIDN build issues, I looked around and found https://github.com/DLTcollab/sse2neon which promises to transparently translate from Intel's SIMD extensions to Neon. 

I can give it a go and get it to compile on my machine, but I don't know how to test the ARM64 mac builds.

**Comment by ForestKatsch** [comment]
> I can give it a go and get it to compile on my machine, but I don't know how to test the ARM64 mac builds.

I have an ARM mac and am happy to test this for you (and work to reproduce/fix any issues.)

**Comment by akien-mga** [comment]
I made a build of 3.2.4 beta 5 (a18df71789a36b318c40d691efdb4da1e574bbfd) + this PR as of f7aa38e, using the official buildsystem:

https://downloads.tuxfamily.org/godotengine/testing/3.2.4-beta5%2blightmapper/

This can be used to test this PR on different platforms in optimized builds (both editor and once exported with the generated lightmaps) to see how it goes. If there's no obvious showstopper this would then be merged soon for inclusion in 3.2.4 beta 6.

If you run into regressions which might not seem directly related to this feature, you can double check using the 3.2.4 beta 5 builds (without this PR): https://downloads.tuxfamily.org/godotengine/3.2.4/beta5/

**Comment by danilw** [comment]
feature-request:
is it possible to add an **option to generate a *grey*(single channel) texture** to save VRAM and size of the project, as a checkbox on the BakedLightmap node. Can be useful for gray/white surfaces where no other color.

**Comment by Calinou** [comment]
> is it possible to add an option to generate a grey(single channel) texture to save VRAM and size of the project, as a checkbox on the BakedLightmap node. Can be useful for gray/white surfaces where no other color.

Sounds like a good idea to me, I could see it work nicely when you only want to bake indirect lighting. Obviously, using a grayscale lightmap to bake direct light will mean you'll no longer be able to have colored baked lights, but this isn't a problem in some cases.

**Comment by jcostello** [comment]
When bake mode `all`  in lights, shadows shouldn't be in  the baked result?
image

**Comment by Calinou** [comment]
@jcostello Can you upload the project you're using here? It's difficult to understand what's going on the screenshot.

**Comment by jcostello** [comment]
I tried to create a simpler scene to reproduce the issue and I couldn't. Provably I have something wrong in the first scene anyway. In another hand, I was playing with the bounces counter and I notice that with more bounces light propagates a lot more. In my mind I though that bounces will be dim after each bounce but there is a lot of diference between 6 and 10 bounces. My scene walls almost have a plain color from the bouncing light.

image

[LightMap Test.zip](https://github.com/godotengine/godot/files/5814445/LightMap.Test.zip)

**Comment by JFonS** [comment]
I updated the PR with fixes for all the issues reported so far:
* Fix Embree runtime when using MinGW (patch by @RandomShaper), closes #45097.
* Fix baking of lightmaps on GridMaps, closes #45086.
* Fix some GLSL errors, should fix #45091 but I don't have a proper way to test it on a mac.
* Fix overflow in the number of shader variants (GLES2), it made gizmos go black. Reported via twitter, no issue open AFAIK.

**Comment by clayjohn** [comment]
Changes to shader compiler look good! I havent reviewed anything else, but I trust the above reviews are sufficient in that regard.

**Review by akien-mga — APPROVED** [review]
Let's get this merged :)

**Comment by akien-mga** [comment]
Thanks for the amazing work!

**Comment by Jummit** [comment]
@JFonS You forgot to add documentation for the new settings. Most of them are pretty obvious, but I bet there are some things that are good to know, but only you are aware of.

**Comment by Calinou** [comment]
@Jummit Doesn't https://github.com/godotengine/godot/commit/d909592fc508b32c4c3a74d2e5e310ed200c1822 cover the documentation?

**Comment by Jummit** [comment]
> @Jummit Doesn't #44628 cover the documentation?

Weird, it looks like it, but they don't appear in the documentation in my build. Probably a mistake on my end.
