### PR TITLE
Prevent crash when dropping Resource that can't load

### LINKED ISSUE #90600: Holding Ctrl while dragging a CSV file into a script crashes Godot 4.2.1
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3070 Ti Laptop GPU (NVIDIA; 31.0.15.5212) - 12th Gen Intel(R) Core(TM) i9-12900H (20 Threads)

### Issue description

I am not versed on how csv's are imported. First time testing it, and I see it imported it as a translation file. I need to read up on those. I was just using it as essentially a comma separated value to parse into an array later. So not sure if preload is needed for any of that, but by habit did that, and noticed the crash.

### Steps to reproduce

Make a new scene
Add script to scene
While holding Ctrl drag test.csv file from file list to script
Godot then crashes

### Minimal reproduction project (MRP)

[MRP CSV crash.zip](https://github.com/godotengine/godot/files/14964494/MRP.CSV.crash.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #90600

### CODE REVIEW

File: editor/plugins/script_text_editor.cpp [hunk 1]
```diff
@@ -1838,6 +1838,11 @@ void ScriptTextEditor::drop_data_fw(const Point2 &p_point, const Variant &p_data
 
 			if (drop_modifier_pressed && ResourceLoader::exists(path)) {
 				Ref<Resource> resource = ResourceLoader::load(path);
+				if (resource.is_null()) {
+					// Resource exists, but failed to load. We need only path and name, so we can use a dummy Resource instead.
+					resource.instantiate();
+					resource->set_path_cache(path);
```
Comment (akien-mga) [inline editor/plugins/script_text_editor.cpp:1844]: Would it make sense to always use this approach and save a costly `load`? Or it's not enough for some types of resources?

Comment (KoBeWi) [reply editor/plugins/script_text_editor.cpp:1844]: `_get_dropped_resource_line()` also uses resource name, which currently can't be obtained without loading the Resource.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
