### PR TITLE
`TileSet` Fix crash in `AtlasMergingDialog`

### LINKED ISSUE #75354: Atlas Merge Tool crashes when selecting entries to merge
### Godot version

v4.0.1.stable.official [cacf49999]

### System information

Windows 11

### Issue description

When trying to select multiple entries inside the Atlas Merge Tool, the engine crashes.
grafik

Thanks for the help!

### Steps to reproduce

1. Import multiple sprites (at least 2)
2. Create a Tilemap and its Tileset
3. Drag sprites into Tileset window
4. Create the Tiles for every sprite
grafik
5. Open Atlas Merging tool
6. Try to select the sprites you want to merge

### Minimal reproduction project

[Atlas Merging Bug.zip](https://github.com/godotengine/godot/files/11071428/Atlas.Merging.Bug.zip)

### PR DESCRIPTION
**Pull request by kleonc**
When generating the `merged` TileSetAtlasSource the newly calculated `new_texture_region_size` was being set after creating tiles within such source. Hence during tiles creation its `texture_region_size` was the default `(16, 16)` instead of the `new_texture_region_size`. When any dimension of `new_texture_region_size` was smaller than 16 then the tile would fail to be created as it would be determined to not fit within the new texture. Hence later obtaining such tile's data would fail (as it was not created) and thus `nullptr` would be dereferenced when trying to copy the properties (which caused the crash).

This PR makes the `new_texture_region_size` be set before copying the tiles so the checks should not fail like before.

Fixes #75354.

### CODE REVIEW

File: editor/plugins/tiles/atlas_merging_dialog.cpp [hunk 1]
```diff
@@ -104,10 +106,12 @@ void AtlasMergingDialog::_generate_merged(Vector<Ref<TileSetAtlasSource>> p_atla
 				// Create tiles and alternatives, then copy their properties.
 				for (int alternative_index = 0; alternative_index < atlas_source->get_alternative_tiles_count(tile_mapping.key); alternative_index++) {
 					int alternative_id = atlas_source->get_alternative_tile_id(tile_mapping.key, alternative_index);
-					if (alternative_id == 0) {
+					if (alternative_index == 0) {
 						merged->create_tile(tile_mapping.value, atlas_source->get_tile_size_in_atlas(tile_mapping.key));
```
Comment (kleonc) [inline editor/plugins/tiles/atlas_merging_dialog.cpp:110]: @groud Not sure about this change, but the new tile should be created at the first iteration of that loop so when `alternative_index == 0`. Is it guaranteed that `alternative_id` will be `0` at the first iteration or something like that?

Comment (KoBeWi) [reply editor/plugins/tiles/atlas_merging_dialog.cpp:110]: I did a quick test and alternative tile id at index `0` is always 0. The function works even if there are no alternative tiles, so I assume it's the original, non-alternative tile.

That said, seems like `alternative_id` and `alternative_index` will work the same here.

File: editor/plugins/tiles/atlas_merging_dialog.cpp [hunk 2]
```diff
@@ -95,7 +95,9 @@ void AtlasMergingDialog::_generate_merged(Vector<Ref<TileSetAtlasSource>> p_atla
 			}
 		}
 
+		merged->set_name(p_atlas_sources[0]->get_name());
 		merged->set_texture(ImageTexture::create_from_image(output_image));
+		merged->set_texture_region_size(new_texture_region_size);
```
Comment (KoBeWi) [inline editor/plugins/tiles/atlas_merging_dialog.cpp:100]: I looked at the code and this line seems enough to fix the crash. The problem was that the region size was 0 and no tiles were created.

File: editor/plugins/tiles/atlas_merging_dialog.cpp [hunk 3]
```diff
@@ -104,10 +106,12 @@ void AtlasMergingDialog::_generate_merged(Vector<Ref<TileSetAtlasSource>> p_atla
 				// Create tiles and alternatives, then copy their properties.
 				for (int alternative_index = 0; alternative_index < atlas_source->get_alternative_tiles_count(tile_mapping.key); alternative_index++) {
 					int alternative_id = atlas_source->get_alternative_tile_id(tile_mapping.key, alternative_index);
-					if (alternative_id == 0) {
+					if (alternative_index == 0) {
 						merged->create_tile(tile_mapping.value, atlas_source->get_tile_size_in_atlas(tile_mapping.key));
+						ERR_FAIL_COND(!merged->has_tile(tile_mapping.value));
```
Comment (KoBeWi) [inline editor/plugins/tiles/atlas_merging_dialog.cpp:111]: I checked if this condition helps with anything and I still get a crash without the `set_texture_region_size()` fix.

File: editor/plugins/tiles/atlas_merging_dialog.cpp (hunk 1 above)
Comment (kleonc) [reply editor/plugins/tiles/atlas_merging_dialog.cpp:110]: Checked the source of few TileSet methods and it indeed seems it's guaranteed `alternative_id == 0` always exist (for an existing tile) and it's always at index 0 within the alternative ids cache for the tile. So yeah, the previous check should be fine (both should be equivalent), gonna revert this change.

**Review by KoBeWi — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.2.
