### PR TITLE
Fix "p_from_line > p_to_line" errors in text edit

### LINKED ISSUE #58906: Script editor dumps "Condition "p_from_line > p_to_line" is true." errors when moving mouse across top threshold
### Godot version

4.0.alpha3

### System information

Windows 10 (but has happened on linux as well)

### Issue description

Super weird. The text editor dumps that error in the console when moving the mouse over the upper threshold to the text editor - but only when the text is arranged in certain ways and scrolled to the right position. See the following.

Scrolled to one position:
bug1

And then another:
bug2

(I am using a custom theme here but it is still occuring in a completely spotless copy with no changed settings)

From some quick debug outputs in my own build (have not run a full debug build yet though) it looks like at this point `p_from_line` is 1 larger than `p_to_line`

I am unsure if this occurs in other text editor instances.

### Steps to reproduce

Imitate the gifs in the description, pretty much.

### Minimal reproduction project

Not super necessary because of how simple it is, but hey why not:

[bug_test.zip](https://github.com/godotengine/godot/files/8208649/bug_test.zip)

### PR DESCRIPTION
**Pull request by novaplusplus**
The function in question (TextEdit::get_visible_line_count_in_range) expects "to" to be larger than "from" but a number of places that call it don't really do any check. In the issue page I made (#58906), @Paulb23 recommended that the function be modified to be tolerant of different input orderings, so that's what I've done here.

(updated with some style fixes so the checks don't fail and stuff!)
(I also thought I might have to update the docs, but this change doesn't really contradict anything so)

*Bugsquad edit:*
- Fixes https://github.com/godotengine/godot/issues/58906

### CODE REVIEW

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -4469,15 +4469,25 @@ int TextEdit::get_visible_line_count() const {
...
+	int smaller;
+	int larger;
+
+	if (p_from_line > p_to_line) {
+		smaller = p_to_line;
+		larger = p_from_line;
+	} else {
+		smaller = p_from_line;
+		larger = p_to_line;
+	}
```
Comment (bruvzg) [inline scene/gui/text_edit.cpp:4482]:
```suggestion
	if (p_from_line > p_to_line) {
		SWAP(p_from_line, p_to_line);
	}
```

Comment (novaplusplus) [reply scene/gui/text_edit.cpp:4482]: Huh. Never knew about that macro. Will do.

**Review by Paulb23 — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
