### PR TITLE
GDScript: Fix setting native type with script inheritance

### LINKED ISSUE #70591: Godot v4 (beta 10) crashes when loading project with classes with inheritance
### Godot version

v4.0.beta10.official [d0398f62f]

### System information

macOS Ventura 13.1 (22C65)

### Issue description

I closed Godot and when I opened my project again, it just shows an empty project and seconds later it crashes.

I recorded the error it outputs and took a screenshot of it. What you see is the last frame before crashing:

Screenshot 2022-12-26 at 3 44 38 PM

Unfortunately this only happens on my project, which I cannot share, so I apologize for that.

I tried removing `@tool` on two scripts that use this, but this doesn't seem to be the cause. The only thing I believe it's worth noting is that I use `class_name` for a lot of objects, which always seems to behave unexpectedly on Godot.

**Workaround:** I can get Godot to load by:
1. Editing one of my GDScripts on an external editor and commenting out any random `func` that another func calls.
2. This causes the parser to throw an error since the function doesn't exist, allowing the project to load normally.
3. I can then proceed to uncomment the function and run my project just fine without any errors.

If you think I can provide any more specifics, please let me know.

### Steps to reproduce

No clear steps to reproduce.

### Minimal reproduction project

(Edit) https://github.com/godotengine/godot/files/10449995/Godot.Crash.Project.zip

### PR DESCRIPTION
**Pull request by vnen**
Sometimes the inheritance tree is compiled out of order and the base don't have yet a native type set. This is now changed to not rely on the base script but use the native type set in the datatype, which is already resolved by the analyzer.

Fix #70591

### CODE REVIEW

File: modules/gdscript/gdscript_compiler.cpp [hunk 1]
```diff
@@ -2265,13 +2265,15 @@ Error GDScriptCompiler::_populate_class_members(GDScript *p_script, const GDScri
 
 	GDScriptDataType base_type = _gdtype_from_datatype(p_class->base_type, p_script);
 
+	int native_idx = GDScriptLanguage::get_singleton()->get_global_map()[base_type.native_type];
+	p_script->native = GDScriptLanguage::get_singleton()->get_global_array()[native_idx];
```
Comment (akien-mga) [inline modules/gdscript/gdscript_compiler.cpp:2269]: Just to be sure, there's no risk of out of bound reads here?

It's the same code as there was for `NATIVE` but since it will now run for more base types, I think it might be worth double checking.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

File: modules/gdscript/gdscript_compiler.cpp (hunk 1 above)
Comment (vnen) [reply modules/gdscript/gdscript_compiler.cpp:2269]: Should not happen but I guess it doesn't hurt to add an extra check.
