### PR TITLE
Set uniform default values in inspector

### LINKED ISSUE #17887: Default shader values not displayed correctly in the Inspector
**Godot version:**
image

**OS/device including version:**
Windows 10 64

**Issue description:**
image
Default shader values not displayed correctly in the Inspector. They are set correctly though.

**Steps to reproduce:**
Create shader with specified default values, create a material with it, assign to mesh, check inspector.

### PR DESCRIPTION
**Pull request by JFonS**
With this PR shader param properties return the default uniform value if the uniform has one and the parameter hasnt been set. This means the dafault value will correctly appear in the insperctor, fixes #17887.

I also added a revert functionality so that shader parameters can be set to their default value by clicking a button.

unif

Modifying the uniform adds a "revert" button that sets the default value:
unif2

### CODE REVIEW

**Comment by akien-mga** [comment]
Awesome work! Does this also fix `VisualServer::material_get_param` as described in #20291?

**Comment by JFonS** [comment]
@akien-mga I wasn't aware of this issue, but I will update this PR to adress it.

**Comment by JFonS** [comment]
`VisualServer::material_get_param_default` is definetely needed to tell wether a param has a default value or not. But `VisualServer::material_get_param` could be modified to return the default value if it has no value assigned.

**Comment by akien-mga** [comment]
A quick rebase will be needed since I messed with the `core` include style.

**Comment by reduz** [comment]
Is doing this really needed? I would think that just ensuring VisualServer::material_get_param returns the default value if nothing is set would be enough..

File: drivers/gles3/rasterizer_storage_gles3.cpp [hunk 1]
```diff
@@ -29,8 +29,8 @@
 /*************************************************************************/
 
 #include "rasterizer_storage_gles3.h"
-
 #include "core/engine.h"
+#include "core/matrix3.h"
```
Comment (akien-mga) [inline drivers/gles3/rasterizer_storage_gles3.cpp]: Sorry it's `core/math/matrix3.h`, there used to be `core/math` in the include path too :D

**Comment by JFonS** [comment]
Yeah, I noticed :p I had to leave so I couldn't fix it right away. Will do later.

File: drivers/gles3/rasterizer_storage_gles3.cpp (hunk 1 above)
Comment (JFonS) [reply drivers/gles3/rasterizer_storage_gles3.cpp]: Yeah I noticed :p I had to leave so I couldn't fix it right away. Will do later.

File: drivers/gles2/rasterizer_storage_gles2.cpp [hunk 2]
```diff
@@ -1419,6 +1419,99 @@ Variant RasterizerStorageGLES2::material_get_param(RID p_material, const StringN
...
 
+	return material_get_param_default(p_material, p_param);
+}
+
+Variant RasterizerStorageGLES2::material_get_param_default(RID p_material, const StringName &p_param) const {
+	const Material *material = material_owner.get(p_material);
+	ERR_FAIL_COND_V(!material, Variant());
+
+	if (material->shader) {
+		if (material->shader->uniforms.has(p_param)) {
```
Comment (reduz) [inline drivers/gles2/rasterizer_storage_gles2.cpp]: I was thinking that to avoid repeating this code in GLES2 and GLES3, there could be a function to convert a GLSL value into a Variant in ShaderLanguage?

**Review by reduz — CHANGES_REQUESTED** [review]
