### PR TITLE
Fixes gravity calculation for kinematic bodies in Bullet

### LINKED ISSUE #15554: 3D KinematicBody not affected by area gravity in Bullet Physics
**Godot version:**
[aebdc4c2126789b915b0fb753f0594fec0f0226d](https://github.com/godotengine/godot/commit/aebdc4c2126789b915b0fb753f0594fec0f0226d)

**OS/device including version:**
Windows 10 64bit

**Issue description:**
In the Godot physics engine I'm able to get the KinematicBody's direct state and get it's total gravity it's being affected by so I can make kinematic bodies respond to areas with gravity points and gravity in general
```gdscript
var state = PhysicsServer.body_get_direct_state(get_rid())
var gravity = state.get_total_gravity()
```
I thought I was able to do this before in the Bullet Physics engine but tested today and the gravity is just always `Vector3( 0.0, 0.0, 0.0)`

**Steps to reproduce:**
- Create a KinematicBody with this script attached
```gdscript
extends KinematicBody

func _physics_process(delta):
	var state = PhysicsServer.body_get_direct_state(get_rid())
	print(state.get_total_gravity())
```
- In project's settings set Physics > 3D > Physics Engine = Bullet
- run the scene. It should print `(0, 0, 0)`

If you switch the 3D physics to GodotPhysics it should print `(0, -9.8, 0)`

**Minimal reproduction project:**
[Kinematic3dGravityTest.zip](https://github.com/godotengine/godot/files/1618583/Kinematic3dGravityTest.zip)

### PR DESCRIPTION
**Pull request by Dar13**
Resolves #15554, ensures that gravity calculations are done for kinematic rigid bodies and is reflected via `get_total_gravity()`

### CODE REVIEW

File: modules/bullet/rigid_body_bullet.cpp [hunk 1]
```diff
@@ -832,7 +832,8 @@ void RigidBodyBullet::on_exit_area(AreaBullet *p_area) {
 
 void RigidBodyBullet::reload_space_override_modificator() {
 
-	if (!is_active())
+	// Make sure that kinematic bodies have their total gravity calculated, even though they aren't active
```
Comment (AndreaCatania) [inline modules/bullet/rigid_body_bullet.cpp]: Can you please remove this: _"even though they aren't active"_ since the kinematic is not part of simulation and can't be active / unactive

**Review by AndreaCatania — CHANGES_REQUESTED** [review]

File: modules/bullet/rigid_body_bullet.cpp (hunk 1 above)
Comment (Dar13) [reply modules/bullet/rigid_body_bullet.cpp]: Done (via 5fb8a6a)

**Comment by AndreaCatania** [comment]
This can be merged

**Comment by akien-mga** [comment]
Thanks!

@AndreaCatania Do you think this can be cherry-picked for 3.0.x or does it break compat?
