### PR TITLE
Fixes to the GLTF export with baking and null checks.

### LINKED ISSUE #72699: Exporting gltf animation broke
### Godot version

0810ecaafdbee3ea747219e6ab3a8de5d2216a09

### System information

Windows 11, Nvidia 3000, firefox

### Issue description

Exporting the gltf file is corrupt in blender.

### Steps to reproduce

1. Open project.
2. Export as glb
3. Open in blender
4. Blender display many warnings

image

### Minimal reproduction project

https://cdn.discordapp.com/attachments/598003845657788438/1071249610896580691/Test_Game_Project.zip

### PR DESCRIPTION
**Pull request by fire**
Fixes: https://github.com/godotengine/godot/issues/72699

### CODE REVIEW

File: modules/gltf/gltf_document.cpp [hunk 1]
```diff
@@ -6488,55 +6622,77 @@ GLTFAnimation::Track GLTFDocument::_convert_animation_track(Ref<GLTFState> p_sta
...
+				}
+			} else {
+				for (int32_t key_i = 0; key_i < key_count; key_i++) {
+					Vector3 scale_track = p_animation->track_get_key_value(p_track_i, key_i);
+					p_track.scale_track.values.write[key_i] = scale_track;
+				}
 			}
 		}
 	} else if (track_type == Animation::TYPE_BEZIER) {
+		const int32_t keys = p_animation->track_get_key_time(p_track_i, key_count - 1) * BAKE_FPS;
```
Comment (lyuma) [inline modules/gltf/gltf_document.cpp:6656]: this will bake the bezier with the length of the first encountered track (in the case that :x, :y and :z tracks have different lengths.

bezier is hard enough to work with in Godot that I don't know how worthwhile it is to fix this, but just pointing it out. Users could also be encouraged to use the same number of keys for each of :x, :y and :z

File: modules/gltf/gltf_document.cpp [hunk 2]
```diff
@@ -6565,11 +6746,20 @@ void GLTFDocument::_convert_animation(Ref<GLTFState> p_state, AnimationPlayer *p
 		if (!animation->track_is_enabled(track_i)) {
 			continue;
 		}
-		String orig_track_path = animation->track_get_path(track_i);
-		if (String(orig_track_path).contains(":position")) {
-			const Vector<String> node_suffix = String(orig_track_path).split(":position");
+		String final_track_path = animation->track_get_path(track_i);
+		Node *animation_base_node = p_animation_player->get_parent();
+
+		if (final_track_path.begins_with("%")) {
```
Comment (lyuma) [inline modules/gltf/gltf_document.cpp:6752]: Made this comment in discord too, but this special case should not be necessary. `get_node_or_null` should handle this already.

File: modules/gltf/gltf_document.cpp [hunk 3]
```diff
@@ -6425,61 +6431,189 @@ GLTFAnimation::Track GLTFDocument::_convert_animation_track(Ref<GLTFState> p_sta
 	Vector<real_t> times;
 	times.resize(key_count);
 	String path = p_animation->track_get_path(p_track_i);
+	if (path.begins_with("%")) {
+		const Vector<String> node_suffix = String(path).split(":");
+		String path_split = node_suffix[0];
+		Node *node = p_animation_player->get_owner()->get_node_or_null(path_split);
+		path = String(p_animation_player->get_parent()->get_path_to(node)) + ":" + node_suffix[1];
+	}
```
Comment (lyuma) [inline modules/gltf/gltf_document.cpp:6439]: same here. This special case should not be needed, and hence the extra "p_animation_player" argument should also not be necessary.

File: modules/gltf/gltf_document.cpp [hunk 4]
```diff
@@ -4872,12 +4872,18 @@ Error GLTFDocument::_serialize_animations(Ref<GLTFState> p_state) {
...
 	for (int32_t player_i = 0; player_i < p_state->animation_players.size(); player_i++) {
-		List<StringName> animation_names;
 		AnimationPlayer *animation_player = p_state->animation_players[player_i];
-		animation_player->get_animation_list(&animation_names);
-		if (animation_names.size()) {
-			for (int animation_name_i = 0; animation_name_i < animation_names.size(); animation_name_i++) {
-				_convert_animation(p_state, animation_player, animation_names[animation_name_i]);
+		List<StringName> animation_library_names;
+		animation_player->get_animation_library_list(&animation_library_names);
+		for (StringName library_name : animation_library_names) {
```
Comment (lyuma) [inline modules/gltf/gltf_document.cpp:4878]: Why was the original code incorrect? `get_animation_list` still exists and should return the full list of animations?

File: modules/gltf/gltf_document.cpp (hunk 1 above)
Comment (fire) [reply modules/gltf/gltf_document.cpp:6656]: I believe the current code doesn't change the algorithm of baking. Need a design clarification at some point.

File: modules/gltf/gltf_document.cpp (hunk 3 above)
Comment (fire) [reply modules/gltf/gltf_document.cpp:6439]: Modified to be done this way.

```
	String path = p_animation->track_get_path(p_track_i);
	const Vector<String> node_suffix = String(path).split(":");
	String path_split = node_suffix[0];
	Node *node = p_animation_player->get_owner()->get_node_or_null(path_split);
	// Rewites the path to remove unique names.
	path = String(p_animation_player->get_parent()->get_path_to(node)) + ":" + node_suffix[1];
```

Comment (fire) [reply modules/gltf/gltf_document.cpp]: Removing rewrite path.

File: modules/gltf/gltf_document.cpp [hunk 5]
```diff
@@ -6431,7 +6429,7 @@ void GLTFDocument::_process_mesh_instances(Ref<GLTFState> p_state, Node *p_scene
 	}
 }
 
-GLTFAnimation::Track GLTFDocument::_convert_animation_track(Ref<GLTFState> p_state, GLTFAnimation::Track p_track, Ref<Animation> p_animation, int32_t p_track_i, GLTFNodeIndex p_node_i) {
+GLTFAnimation::Track GLTFDocument::_convert_animation_track(Ref<GLTFState> p_state, GLTFAnimation::Track p_track, Ref<Animation> p_animation, int32_t p_track_i, GLTFNodeIndex p_node_i, AnimationPlayer *p_animation_player) {
 	Animation::InterpolationType interpolation = p_animation->track_get_interpolation_type(p_track_i);
```
Comment (lyuma) [inline modules/gltf/gltf_document.cpp:6433]: Unused argument `p_animation_player`

**Review by lyuma — APPROVED** [review]
Changes look reasonable.

The bezier cases are unreachable. they check for `"/scale"` and `"/scale:x"` but Godot uses `":scale:x"` with a colon. Probably the case that nobody has ever tested exporting bezier position/rotation/scale tracks.

File: modules/gltf/gltf_document.cpp (hunk 4 above)
Comment (lyuma) [reply modules/gltf/gltf_document.cpp]: animation_set contains animations from all libraries with /. I see you already updated the PR to reflect that `get_animation_list` works

**Comment by akien-mga** [comment]
Thanks!
