### PR TITLE
Node.add_child Check for cyclic dependency

### LINKED ISSUE #48997: Node.add_child() doesn't check for a cyclic dependency
**Godot version:**
3.3.1.stable

**Issue description:**
`Node.add_child()` doesn't check for a cyclic dependency so it's possible to group nodes in a graph not being a tree.

**Steps to reproduce:**
This results in an infinite loop:
```
var a := Node.new()
var b := Node.new()
a.add_child(b)
b.add_child(a)
a.print_tree()
```

### PR DESCRIPTION
**Pull request by kleonc**
Fixes #48997.

Is using `vformat()` or something similar preferred over just adding strings?

### CODE REVIEW

**Comment by akien-mga** [comment]
That seems like a correct logical change but I'm concerned about what impact it may have on performance. This might be worth benchmarking on some pathological cases (adding lots of nodes) to see what impact it has.

**Comment by kleonc** [comment]
> That seems like a correct logical change but I'm concerned about what impact it may have on performance. This might be worth benchmarking on some pathological cases (adding lots of nodes) to see what impact it has.

Yeah, it went through my mind. Number of additional checks depends on the number of nodes up in the tree from the node `add_child` was called on. So I don't think it should be a big overhead. But I've done a little benchmark (was curious myself):
<details>
  <summary>This is a script timing addition of X nodes for each level in the tree down to Y nodes deep (really levels 2..(Y+2) because of self, root).</summary>
  
```
extends Node


const LEVELS = 3000
const ADDITIONS_PER_LEVEL = 1000


func _ready():

	var timings = []
	timings.resize(LEVELS)

	var parent = self
	for i in range(LEVELS):
		parent.add_child(Node.new())
		parent = parent.get_child(0)

	var nodes = []
	nodes.resize(ADDITIONS_PER_LEVEL)
	for i in range(ADDITIONS_PER_LEVEL):
		nodes[i] = Node.new()

	var start_time
	var end_time
	parent = self

	for level in LEVELS:

		start_time = OS.get_ticks_usec()
		for i in range(ADDITIONS_PER_LEVEL):
			parent.add_child(nodes[i])
		end_time = OS.get_ticks_usec()

		timings[level] = (end_time - start_time) / 1000.0

		for i in range(NODES_PER_LEVEL):
			parent.remove_child(nodes[i])

		parent = parent.get_child(0)

	for i in ADDITIONS_PER_LEVEL:
		nodes[i].free()

        # do something with timings
```
</details>

And example results on my potato pc:

soffice bin_1Lqwop0rjh

soffice bin_LwqCmww7Ny

But yeah, I think that adding 1000 nodes at once 300 nodes deep in the tree is kinda abstract... :wink:

---

> Yeah that's usually preferred.

So I've replaced those with `vformat()` in this file. Haven't squashed yet just in case it's not desired.

**Comment by amoriqbal** [comment]
Checking for cycles can be of O(N) in worst case and O(log N) in best and average case (N = number of nodes). For large nested trees, this can be an overhead indeed. 
**Proposal 1:**
We keep a *checkbox* in *Project Settings* named **Check for cycles in node hierarchy**. 
**Proposal 2:**
We can add an optional parameter `no_cycles : bool = false` to the `add_child()` function. 
Eg: `add_child(p_child)` and `add_child(p_child, false)` will not check for cycles. But `add_child(p_child, true)` will report cycles.

**Comment by Phischermen** [comment]
I'm a fan of proposal #2. A project setting seems overkill, but a function parameter seems just right.

**Comment by akien-mga** [comment]
Both proposals seem overkill to me, I'd just make the check debug only (`#ifdef DEBUG_ENABLED`) so that it doesn't affect performance on release builds.

**Comment by amoriqbal** [comment]
> Both proposals seem overkill to me, I'd just make the check debug only (`#ifdef DEBUG_ENABLED`) so that it doesn't affect performance on release builds.

Indeed... this seems best because we don't want error messages in the release build.

**Comment by kleonc** [comment]
Yeah, I think user shouldn't know/care about this at all, no reason to bloat the API. It should indeed be fine to check it in the debug builds only. But it needs to be noted in the error message.

I've rebased, feel free to review the error message / suggest changes.

File: scene/main/node.cpp [hunk 1]
```diff
@@ -1240,8 +1240,11 @@ void Node::_add_child_nocheck(Node *p_child, const StringName &p_name) {
 
 void Node::add_child(Node *p_child, bool p_legible_unique_name) {
 	ERR_FAIL_NULL(p_child);
-	ERR_FAIL_COND_MSG(p_child == this, "Can't add child '" + p_child->get_name() + "' to itself."); // adding to itself!
-	ERR_FAIL_COND_MSG(p_child->data.parent, "Can't add child '" + p_child->get_name() + "' to '" + get_name() + "', already has a parent '" + p_child->data.parent->get_name() + "'."); //Fail if node has a parent
+	ERR_FAIL_COND_MSG(p_child == this, vformat("Can't add child '%s' to itself.", p_child->get_name())); // adding to itself!
+	ERR_FAIL_COND_MSG(p_child->data.parent, vformat("Can't add child '%s' to '%s', already has a parent '%s'.", p_child->get_name(), get_name(), p_child->data.parent->get_name())); //Fail if node has a parent
+#ifdef DEBUG_ENABLED
+	ERR_FAIL_COND_MSG(p_child->is_a_parent_of(this), vformat("Can't add child '%s' to '%s', would result in cyclic dependency since '%s' is a direct or indirect parent of '%s'. This is a debug only error, fix it or be ready to face undefined behavior in a release build.", p_child->get_name(), get_name(), p_child->get_name(), get_name()));
```
Comment (akien-mga) [inline scene/main/node.cpp:1246]:
```suggestion
	ERR_FAIL_COND_MSG(p_child->is_a_parent_of(this), vformat("Can't add child '%s' to '%s' as it would result in a cyclic dependency since '%s' is already a parent of '%s'.", p_child->get_name(), get_name(), p_child->get_name(), get_name()));
```

The warning was funny but a bit too informal compared to other warnings - but usually we don't bother specifying when errors are debug only, as a vast number of errors are. This error in a debug build is already logic breaking, so will be fixed prior to releasing (or the game won't behave as intended anyway).

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
I prefer not to cherry-pick for `3.3` at this stage.
