### PR TITLE
GPU/CPU particle parameter list consistency changes

### LINKED ISSUE #94687: GPUParticles2D and GPUParticles3D have inconsistent property order in inspector
### Tested versions

- v4.2.2.stable.mono.official [15073afe3]
- v4.3.beta2.mono.official [b75f0485b]

### System information

Godot v4.3.beta2.mono - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4080 (NVIDIA; 32.0.15.5599) - AMD Ryzen 9 7950X3D 16-Core Processor (32 Threads)

### Issue description

GPUParticles3D and GPUParticles2D have inconsistent order of their properties in the inspector. This makes it confusing to work with particles in 2D and 3D because in 3D you have to scroll up to change time settings when you were working on the process material while in 2D you have to scroll down.

image

It would be nicer if both particle systems had the same order of properties, e.g. GPUParticles2D could look like this:

image

### Steps to reproduce

Add a GPUParticles2D and a GPUParticles3D to a scene and compare the inspectors.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by LeonStansfield**
This draft PR introduces changes to the listing of parameters for the GPU and CPU particles 2D to be more consistent with their 3D counterparts as a minor quality of life improvement, as requested in #94687

The inconsistencies I noticed that have been addressed are:

On gpu_particles_2d:
 -  interp_to_end are at different locations in the list between gpu_particles_3d and gpu_particles_2d
 -  lifetime has exponential flag in its range slider on the gpu_particles_3d, which isn't the case in gpu_particles_2d.
 -  preprocess has exponential flag in its range slider on the 3d version, which isn't the case in the 2d version
 -  Draw order is set to index by default in gpu_particles_3d but lifetime in gpu_particles_2d

And on cpu_particles_2d:
 -  lifetime has exponential flag in its range slider on the cpu_particles_3d, which isn't the case in cpu_particles_2d.
 
The changes should address these inconsistencies.

* *Bugsquad edit, closes: #94687*

### CODE REVIEW

File: scene/2d/gpu_particles_2d.cpp [hunk 1]
```diff
@@ -874,7 +874,7 @@ GPUParticles2D::GPUParticles2D() {
 	set_randomness_ratio(0);
 	set_visibility_rect(Rect2(Vector2(-100, -100), Vector2(200, 200)));
 	set_use_local_coordinates(false);
-	set_draw_order(DRAW_ORDER_LIFETIME);
+	set_draw_order(DRAW_ORDER_INDEX);
```
Comment (AThousandShips) [inline scene/2d/gpu_particles_2d.cpp:877]: This breaks compatibility

Comment (LeonStansfield) [reply scene/2d/gpu_particles_2d.cpp]: Okay, reverted that change.

Comment (Calinou) [reply scene/2d/gpu_particles_2d.cpp]: This could be done in a way that only affects newly created nodes in the editor, so that it doesn't break compatibility. We don't have a standard way to achieve this yet though.

Comment (LeonStansfield) [reply scene/2d/gpu_particles_2d.cpp]: I appreciate that suggestion and it could be something I could come back to at some point. At the moment I am trying to help with small basic tasks to get familiar with the code base so that is probably a bit out of the scope for me for now.

**Comment by LeonStansfield** [comment]
Hi everyone, is there any way to progress this PR getting reviewed and merged?

**Review by akien-mga — APPROVED** [review]
Looks good to me overall.

My only concern is with moving `process_material` at the end of an already long list of settings. I guess that's how it is in 3D but I always found it's hard to find even though it's such an important (the most important probably) property for GPU particles.

CC @QbieShay @paddy-exe

**Comment by akien-mga** [comment]
BTW while we wait for a second review, could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by QbieShay** [comment]
I see in the original PR comment you list a change of default for draw order, but I cannot see it in the PR.

I don't think we should change it.

**Comment by AThousandShips** [comment]
> I see in the original PR comment you list a change of default for draw order, but I cannot see it in the PR.

Resolved above in a review comment

**Review by paddy-exe — APPROVED** [review]
LGTM. There could be people complaining that the order will be confusing but I guess it makes sense to make them consistent.
Regarding loosing the overview: Wasn't there a proposal/discussion to have a default `ParticleProcessMaterial` when adding a GPU/CPU Particles Node to the SceneTree?

**Comment by akien-mga** [comment]
Thanks!
