### PR TITLE
Add non-public `{Line,Text}Edit::_set_text()` to fix `text_submitted` signal emission on Web

### LINKED ISSUE #76215: experimental_virtual_keyboard
### Godot version

3.5.1-stable, 4.0.2-stable

### System information

Safari iOS, firefox Android, Chrome Android

### Issue description

When the experimental virtual keyboard is used the keyboard will cover the canvas. Is there a way to react to this and show the text box that is now covered by the keyboard above the virtual keyboard?

I don't know if https://developer.chrome.com/docs/web-platform/virtual-keyboard/#showing-and-hiding-the-virtual-keyboard is being used but it should allow the bounds of the virtual keyboard to be shared with the app.

### Steps to reproduce

create an app with a LineEdit at the bottom and run it on a mobile browser. Enable the virtual keyboard option in the export settings.

When you tap on the line edit to edit text you will not be able to see the line edit anymore because the keyboard covers it.

### Minimal reproduction project

[html5-virtual-keyboard.zip](https://github.com/godotengine/godot/files/11264657/html5-virtual-keyboard.zip)

For html you need a web server. I've added a simple one written in nodejs, so you'd need nodejs (16+?) installed, then you can run `node staticserver.js 0.0.0.0` and it will create a certificate and serve at https://<your ip>:8080

### LINKED ISSUE #103771: 'text submitted' and 'text_changed' signals of 'LineEdit' unable handle in web.
### Tested versions

    Reproducible in: v4.4-stable, 3.3.5-stable, ...(Since lineEdit was added, I think)
    Not reproducible in: No

### System information

Godot v4.4.stable (4c311cbee) - Ubuntu 22.04.5 LTS 22.04 on X11 - X11 display driver, Multi-window, 1 monitor - OpenGL 3 (Compatibility) - llvmpipe (LLVM 15.0.7, 256 bits) - AMD Ryzen 5 3600 6-Core Processor (12 threads)

### Issue description

Signals 'text_submitted' and 'text_changed' of 'LineEdit' not work if run project in web. I add alert similar like for "focus_exit" to show that some-any works.

https://github.com/user-attachments/assets/f7072eec-28eb-4aa6-b7ef-44fe7fd44749

### Steps to reproduce

1. Common 'LineEdit' connected to 'text_submitted' and 'text_chang3d' that call 'alert('')' on emit
2. Export to web
3. Configure app to open from any phone
4. Open the app from a phone, tap on 'LineEdit', type any, press 'enter' on keyboard
5. See nothing alive from the signals mentioned above without 'focus_exit'

### Minimal reproduction project (MRP)

[test_kb.zip](https://github.com/user-attachments/files/19130039/test_kb.zip)

### LINKED ISSUE #106539: [Web] LineEdit's `text_changed` signal is never triggered when using a virtual keyboard
### Tested versions

- Reproducible in master and latest official builds too.

### System information

- Chrome, Firefox and Safari (Tested on a pixel 6a, iPhone 15 pro, and iPad Air)

### Issue description

The way web export handles text changes from a virtual keyboard is by creating a hidden HTML input and sending the text to LineEdit by calling `set_text()`. However `set_text()` does not trigger text_changed signal (by design). This is problematic because if you have some logic which triggers on text change, it won't work for web export with VK.

### Steps to reproduce

- Create an input
- Connect to `text_changed` signal
- Type some text with the virtual keyboard

### Minimal reproduction project (MRP)

[line_edit_text_changed_2025-05-18_00-51-21.zip](https://github.com/user-attachments/files/20266847/line_edit_text_changed_2025-05-18_00-51-21.zip)

### PR DESCRIPTION
**Pull request by adamscott**
Supersedes #106540
Fixes https://github.com/godotengine/godot/issues/106539
Fixes https://github.com/godotengine/godot/issues/103771
Partially fixes https://github.com/godotengine/godot/issues/76215

> [!NOTE]
> This solution is not perfect. For the Web platform, as we rely on a hack to edit text, the text cursor position in the executed callbacks will be wrong. But this solution is the best we can have until we refactor the way we edit text externally (i.e. to make it work with changes not made by keyboards, such as phones autocorrect.)

This PR also fixes the Web platform issue where pressing `Enter` wouldn't trigger the `text_submitted` signal. It is solved by the Web stack by sending the correct `InputEvent` when editing `LineEdit`s.

I added @pippenpaddleopsicopolis as co-author to recognize his efforts towards fixing this issue.

### CODE REVIEW

File: scene/gui/line_edit.cpp [hunk 1]
```diff
@@ -39,6 +39,7 @@
 #include "core/string/translation_server.h"
 #include "scene/gui/label.h"
 #include "scene/main/window.h"
+#include "scene/scene_string_names.h"
```
Comment (AThousandShips) [inline scene/gui/line_edit.cpp]:
```suggestion
```
Already included

Comment (adamscott) [reply scene/gui/line_edit.cpp]: Already removed!

File: platform/web/js/libs/library_godot_display.js [hunk 2]
```diff
@@ -61,6 +61,17 @@ const GodotDisplayVK = {
 					input_cb(c_str, elem.selectionEnd);
 					GodotRuntime.free(c_str);
 				}, false);
+				if (what === 'input') {
+					// Handling the "Enter" key.
+					const onKey = (pEvent, pEventName) => {
+						if (pEvent.key != 'Enter') {
+							return;
+						}
```
Comment (Calinou) [inline platform/web/js/libs/library_godot_display.js]:
```suggestion
						if (pEvent.key !== 'Enter') {
							return;
						}
```

**Review by Calinou — COMMENTED** [review]
Tested locally on Firefox 145 and Chromium 142 on Linux, it works as expected. I've also tested it on Android 16 with Firefox 145 and Chrome 139 and it works correctly, both with experimental virtual keyboard disabled and enabled.

PS: I can still use the virtual keyboard in Firefox on Android with the option disabled. In fact, it seems to work better this way, as the caret remains visible after I move it using touch controls or after I enter some text. In Chrome, when experimental virtual keyboard is enabled, the caret disappears after I move it (when releasing the finger) or when I enter any text. Text input still works, but it will sometimes start at the beginning unexpectedly instead of the end of the LineEdit.

File: scene/gui/line_edit.cpp [hunk 3]
```diff
@@ -2111,8 +2111,20 @@ void LineEdit::delete_text(int p_from_column, int p_to_column) {
...
+
+	String previous_state = get_text();
 	insert_text_at_caret(p_text);
-	_create_undo_state();
+	String current_state = get_text();
+
+	if (current_state != previous_state) {
+		_create_undo_state();
+
+		bool meta_text_changed = has_meta(SNAME("__set_text_emit_text_changed")) && (bool)get_meta(SNAME("__set_text_emit_text_changed"));
```
Comment (KoBeWi) [inline scene/gui/line_edit.cpp]:
```suggestion
		bool meta_text_changed = get_meta(SNAME("__set_text_emit_text_changed"), false);
```

File: scene/main/viewport.cpp [hunk 4]
```diff
@@ -2828,16 +2828,26 @@ void Viewport::_post_gui_grab_click_focus() {
...
 	}
 
-	if (gui.key_focus) {
-		gui.key_focus->call("set_text", p_text);
+	if (!gui.key_focus || !gui.key_focus->has_method(SNAME("set_text"))) {
+		return;
 	}
+
+	if (p_emit_text_changed) {
+		gui.key_focus->set_meta(SNAME("__set_text_emit_text_changed"), true);
```
Comment (KoBeWi) [inline scene/main/viewport.cpp]: This meta is referenced enough times that it should be either SceneStringName or a constant somewhere.

File: scene/gui/line_edit.cpp [hunk 5]
```diff
@@ -2111,8 +2111,20 @@ void LineEdit::delete_text(int p_from_column, int p_to_column) {
 
 void LineEdit::set_text(String p_text) {
 	clear_internal();
+
+	String previous_state = get_text();
 	insert_text_at_caret(p_text);
-	_create_undo_state();
+	String current_state = get_text();
+
+	if (current_state != previous_state) {
```
Comment (KoBeWi) [inline scene/gui/line_edit.cpp]:
```suggestion
	if (text != previous_state) {
```

File: scene/main/window.h [hunk 6]
```diff
@@ -244,7 +244,7 @@ class Window : public Viewport {
 	friend class Viewport; //friend back, can call the methods below
 
 	void _window_input(const Ref<InputEvent> &p_ev);
-	void _window_input_text(const String &p_text);
+	void _window_input_text(const String &p_text, bool p_emit_text_changed = false);
```
Comment (KoBeWi) [inline scene/main/window.h]: Note that `callable_mp()` does not support default arguments, so if something calls the callback without the new argument, it won't work anymore.

**Review by KoBeWi — APPROVED** [review]
The GUI/Viewport code seems fine. I didn't test the issue though.

File: scene/gui/line_edit.cpp [hunk 7]
```diff
@@ -2123,8 +2135,20 @@ void LineEdit::set_text_with_selection(const String &p_text) {
...
+		_create_undo_state();
+
+		bool meta_text_changed = has_meta(SNAME("__set_text_emit_text_changed")) && (bool)get_meta(SNAME("__set_text_emit_text_changed"));
+		if (meta_text_changed) {
+			_text_changed();
+			remove_meta(SNAME("__set_text_emit_text_changed"));
+		}
+	}
```
Comment (KoBeWi) [inline scene/gui/line_edit.cpp]: On another look, I don't think this part is necessary for anything. `set_text_with_selection()` is only called from SpinBox to get rid of prefix/suffix.

File: platform/android/display_server_android.cpp [hunk 8]
```diff
@@ -437,26 +437,27 @@ void DisplayServerAndroid::window_set_drop_files_callback(const Callable &p_call
...
 
 void DisplayServerAndroid::send_input_event(const Ref<InputEvent> &p_event) const {
-	_window_callback(input_event_callback, p_event);
+	_window_callback(input_event_callback, false, p_event);
 }
 
 void DisplayServerAndroid::send_input_text(const String &p_text) const {
-	_window_callback(input_text_callback, p_text);
+	_window_callback(input_text_callback, false, p_text, false);
 }
```
Comment (adamscott) [inline platform/android/display_server_android.cpp:461]: `DisplayServerAndroid::_window_callback()` always assumed that callbacks would have only one argument, which is not the case anymore with `input_text_callback` with this PR. Hence the new template.

File: scene/gui/line_edit.cpp [hunk 9]
```diff
@@ -2109,10 +2109,26 @@ void LineEdit::delete_text(int p_from_column, int p_to_column) {
...
 void LineEdit::set_text(String p_text) {
 	clear_internal();
+
+	String previous_text = get_text();
 	insert_text_at_caret(p_text);
-	_create_undo_state();
+
+	if (get_text() != previous_text) {
+		_create_undo_state();
+	}
```
Comment (adamscott) [inline scene/gui/line_edit.cpp:2123]: I left a "fix" here. Technically, we should always create an undo state only if the action was needed, isn't it?

File: scene/gui/line_edit.cpp [hunk 10]
```diff
@@ -2123,8 +2139,13 @@ void LineEdit::set_text_with_selection(const String &p_text) {
...
 
 	clear_internal();
+
+	String previous_text = get_text();
 	insert_text_at_caret(p_text);
-	_create_undo_state();
+
+	if (get_text() != previous_text) {
+		_create_undo_state();
+	}
```
Comment (adamscott) [inline scene/gui/line_edit.cpp:2144]: Same here. (see https://github.com/godotengine/godot/pull/113461/files#r2586028009)

File: scene/gui/text_edit.cpp [hunk 11]
```diff
@@ -3999,6 +4006,9 @@ void TextEdit::set_text(const String &p_text) {
 		_remove_text(0, 0, MAX(0, get_line_count() - 1), MAX(get_line(MAX(get_line_count() - 1, 0)).size() - 1, 0));
 		insert_text_at_caret(p_text);
 		end_complex_operation();
+	} else {
+		_clear();
+		insert_text_at_caret(p_text);
```
Comment (adamscott) [inline scene/gui/text_edit.cpp]: It makes the code more readable.

File: scene/main/viewport.cpp (hunk 4 above)
Comment (adamscott) [reply scene/main/viewport.cpp]: I removed the meta finally.

File: scene/main/window.h (hunk 6 above)
Comment (adamscott) [reply scene/main/window.h]: Thanks for the heads up. I changed the Android display server accordingly.

File: scene/main/viewport.cpp [hunk 12]
```diff
@@ -2828,16 +2828,26 @@ void Viewport::_post_gui_grab_click_focus() {
...
 	if (gui.subwindow_focused) {
 		gui.subwindow_focused->push_text_input(p_text);
 		return;
 	}
 
-	if (gui.key_focus) {
-		gui.key_focus->call("set_text", p_text);
+	StringName set_text_method = p_emit_text_changed_signal
+			? SNAME("_set_text_and_emit_text_changed_signal")
+			: SNAME("set_text");
```
Comment (KoBeWi) [inline scene/main/viewport.cpp]: Since you are adding a new method anyway, you could make it handle both emitting and not emitting the signal (it can be a parameter). And the method could be renamed to something that isn't an implementation detail, like `_push_text_input()`.

Comment (adamscott) [reply scene/main/viewport.cpp]: You mean something like `{Line,Text}Edit::_push_text_input(const String &p_text, bool p_emit_signal)`?

Comment (KoBeWi) [reply scene/main/viewport.cpp]: Yes. This way you have only one method that should be called in this case and its use-case is more clear.

Comment (adamscott) [reply scene/main/viewport.cpp]: I followed @YeldhamDev's suggestion: I created instead a private public API `_set_text()` function that is essentially the implementation of the public `set_text()`.

See:
- https://github.com/adamscott/godot/blob/c826847419084db56c5a6fd600cbda841e4a89d2/scene/gui/line_edit.cpp#L2112-L2128
- https://github.com/adamscott/godot/blob/c826847419084db56c5a6fd600cbda841e4a89d2/scene/gui/text_edit.cpp#L3987-L4025

**Review by YeldhamDev — APPROVED** [review]

File: pyproject.toml [hunk 13]
```diff
@@ -68,6 +68,11 @@ skip = [
 	"platform/android/java/lib/src/main/java/com/*",
 	"platform/web/package-lock.json",
 ]
+ignore-regex = [
+	# Regexes:
+	#  "\\b(_?[a-z][A-Z][_a-zA-Z0-9]+?)\\b": Prevent { pEvent ==> prevent }.
+    "\\b(_?[a-z][A-Z][_a-zA-Z0-9]+?)\\b"
```
Comment (akien-mga) [inline pyproject.toml]:
```suggestion
	# Prevent { pEvent ==> prevent }.
    "\\b(_?[a-z][A-Z][_a-zA-Z0-9]+?)\\b"
```
If it's just that one though, you could also put `pevent` in the `ignore-words-list`.

What's the performance impact of adding this `ignore-regex` if you run `pre-commit run codespell --all` on the codebase?

File: scene/gui/text_edit.cpp [hunk 14]
```diff
@@ -3997,8 +4009,11 @@ void TextEdit::set_text(const String &p_text) {
 		begin_complex_operation();
 		deselect();
 		_remove_text(0, 0, MAX(0, get_line_count() - 1), MAX(get_line(MAX(get_line_count() - 1, 0)).size() - 1, 0));
-		insert_text_at_caret(p_text);
+		_l_insert_text(p_text);
 		end_complex_operation();
+	} else {
+		_clear();
+		_l_insert_text(p_text);
 	}
```
Comment (akien-mga) [inline scene/gui/text_edit.cpp]: Instead of adding a lambda (which decouples the logic implementation from where it's used and adds an extra header dependency), you could just do:

```suggestion
	} else {
		_clear();
	}
	
	// insert text
	
	if (undo_enabled) {
		end_complex_operation();
	}
```

File: scene/gui/text_edit.cpp [hunk 15]
```diff
@@ -7091,6 +7110,11 @@ Color TextEdit::get_font_color() const {
 }
 
 void TextEdit::_bind_methods() {
+	// Private API.
+	ClassDB::bind_method(D_METHOD("_set_text", "text", "emit_signal"), &TextEdit::_set_text, DEFVAL(false));
+
+	// Public API.
+
```
Comment (akien-mga) [inline scene/gui/text_edit.cpp:7113]: I'm not fond of binding methods publicly as a private API.

It seems here it's only used in Viewport. Instead of doing:
```cpp
StringName set_text_method = SNAME("_set_text");
	if (!gui.key_focus || !gui.key_focus->has_method(set_text_method)) {
		return;
	}
	gui.key_focus->call(set_text_method, p_text, p_emit_signal);
```
You can simply cast the object to `LineEdit` and `TextEdit` successively to a public `set_text_no_signal`.

```cpp
LineEdit *line_edit = Object::cast_to<LineEdit>(gui.key_focus);
if (line_edit) {
    line_edit->set_text_no_signal(p_text);
}
TextEdit *text_edit = Object::cast_to<TextEdit>(gui.key_focus);
if (text_edit) {
    text_edit->set_text_no_signal(p_text);
}
```

Unless I'm missing something obviously.

File: pyproject.toml (hunk 13 above)
Comment (adamscott) [reply pyproject.toml]: I will test the performance impact, but as I intend to make JavaScript use letter prefixes like the main code base, it is bound to happen again. But yeah, I could put `pEvent` for now in the list and deal with more use-cases later.

File: scene/gui/text_edit.cpp (hunk 15 above)
Comment (adamscott) [reply scene/gui/text_edit.cpp:7113]: It would work! (with making it's something like `set_text_with_text_changed_signal` instead of no signal if emit signal is true). The whole point of the PR is to fix the issue of the Web platform not being able to send individual key text inputs to the engine directly, that making the `text_changed` signal never fire.
But it would change the design of the Window call from duck typing to literally only call `{Line,Text}Edit` instances. If we're ok with this, I'll make the change. Good idea, as I'm not too fond of creating public/private APIs.

Comment (akien-mga) [reply scene/gui/text_edit.cpp:7113]: Ah I missed that it was already using `call()` before your changes.

Then yeah I'm not sure if this was done because it's simpler than casting, or to support potential other nodes implementing this method.

I suspect it's the former but this should be checked. It might also be to reduce dependencies so Windows doesn't need to include LineEdit/TextEdit (in case it doesn't yet).

Regarding the private API, another option would be to make it actually public, with a name like `set_text_no_signal`. I believe we added a couple methods like this in Control classes in recent releases.

Not sure which option I'd favor tbh.

Comment (adamscott) [reply scene/gui/text_edit.cpp:7113]: > Regarding the private API, another option would be to make it actually public, with a name like `set_text_no_signal`. I believe we added a couple methods like this in Control classes in recent releases.

Take note that the signal is already NOT emitted when calling `set_text()` by design. So the new function would be awkwardly `set_text_with_text_changed_signal()` (or just `set_text_and_signal()`). See the note at the end of the property [`LineEdit.text` in the docs](https://docs.godotengine.org/en/stable/classes/class_lineedit.html#class-lineedit-property-text).

Comment (bruvzg) [reply scene/gui/text_edit.cpp:7113]: I would not expose it as public. Since the whole text input API should be probably refactored to unify virtual keyboard with IME (currently using `NOTIFICATION_OS_IME_UPDATE` notification and display server methods).

File: scene/gui/text_edit.cpp [hunk 16]
```diff
@@ -43,6 +43,8 @@
 #include "scene/main/window.h"
 #include "scene/theme/theme_db.h"
 
+#include <functional>
```
Comment (bruvzg) [inline scene/gui/text_edit.cpp]: What's this for?

**Review by bruvzg — APPROVED** [review]

File: scene/gui/text_edit.cpp (hunk 15 above)
Comment (adamscott) [reply scene/gui/text_edit.cpp:7113]: @bruvzg So, you suggest we test against `Object::cast_to<{Text,Line}Edit>` and call directly the method instead of relying on `ClassDB`, like @akien-mga initially suggested ?

Comment (bruvzg) [reply scene/gui/text_edit.cpp:7113]: No, current implementation is fine. Since it's `_*` method and not showing in the docs, I would not consider it public.

File: scene/gui/text_edit.cpp (hunk 16 above)
Comment (adamscott) [reply scene/gui/text_edit.cpp]: I'll remove it. It was for a lambda used previously.

**Comment by akien-mga** [comment]
Thanks!
