### PR TITLE
Fix editor crash when re-importing GLTF while animation is playing

### LINKED ISSUE #82962: Editor crashes when re-importing GLTF scene while animation is playing.
### Godot version

Godot_v4.2-dev6_linux

### System information

Godot_v4.2-dev6_linux

### Issue description

When re-importing a GLTF scene while an AnimationPlayer is playing an animations on nodes inside the imported scene the editor crashes.

Backtrace:
```handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.dev6.official (57a6813bb8bc2417ddef1058d422a91f0c9f753c)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7fbe6b442520] (??:0)
[2] /home/user/Programs/Godot/Godot_v4.2-dev6_linux.x86_64() [0x471814] (??:0)
[3] /home/user/Programs/Godot/Godot_v4.2-dev6_linux.x86_64() [0x262f908] (??:0)
[4] /home/user/Programs/Godot/Godot_v4.2-dev6_linux.x86_64() [0x263f0e4] (??:0)
[5] /home/user/Programs/Godot/Godot_v4.2-dev6_linux.x86_64() [0x2865dee] (??:0)
[6] /home/user/Programs/Godot/Godot_v4.2-dev6_linux.x86_64() [0x28838fc] (??:0)
[7] /home/user/Programs/Godot/Godot_v4.2-dev6_linux.x86_64() [0x3b896b0] (??:0)
[8] /home/user/Programs/Godot/Godot_v4.2-dev6_linux.x86_64() [0x20e6533] (??:0)
[9] /home/user/Programs/Godot/Godot_v4.2-dev6_linux.x86_64() [0x20feb3f] (??:0)
[10] /home/user/Programs/Godot/Godot_v4.2-dev6_linux.x86_64() [0x20ff6b1] (??:0)
[11] /home/user/Programs/Godot/Godot_v4.2-dev6_linux.x86_64() [0x515caa] (??:0)
[12] /home/user/Programs/Godot/Godot_v4.2-dev6_linux.x86_64() [0x45761b] (??:0)
[13] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fbe6b429d90] (??:0)
[14] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7fbe6b429e40] (??:0)
[15] /home/user/Programs/Godot/Godot_v4.2-dev6_linux.x86_64() [0x4696ae] (??:0)
-- END OF BACKTRACE --
```

### Steps to reproduce

1. Download the attached minimum reproduction project, extract and open in the Godot Editor.
2. Open the "Monke.glb" file from the file picker and click re-import. The editor should **_not_** crash now.
3. Click the AnimationPlayer node and play the animation present inside it.
4. Repeat step 2. Editor _**should**_ now crash. If not repeat step 3 and 2 (on some very rare occasions I had it work correctly).

### Minimal reproduction project

[Import Crash.zip](https://github.com/godotengine/godot/files/12837831/Import.Crash.zip)

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes #82962

~~This might not be a good solution as it stops the animation everytime `edit` is called. 
Do we have a way to distinguish between normal `edit` and `edit` caused by resource re-import? I would appreciate any feedback or alternative suggestions.~~

### CODE REVIEW

**Review by TokageItLab — CHANGES_REQUESTED** [review]
I think this is not good way because it will affect even the cases that have nothing related to the reimport.

I suggest that get the singleton of PlayerEditor in importer or somewhere and call the function which stop the player only when a reimport occurs. However, I wonder if `stop()` is really necessary; just regenerating the cache with `clear_caches()` may be sufficient. Well, it should not be done in `edit()` anyway.

**Comment by jsjtxietian** [comment]
> I suggest that get the singleton of PlayerEditor in importer or somewhere and call the function which stop the player only when a reimport occurs. However, I wonder if `stop()` is really necessary; just regenerating the cache with `clear_caches()` may be sufficient. Well, it should not be done in `edit()` anyway.

Thanks! I did not realize there is a singleton of PlayerEditor！

**Comment by jsjtxietian** [comment]
> However, I wonder if `stop()` is really necessary; just regenerating the cache with `clear_caches()` may be sufficient.

IMHO it's fine to stop it, as let the animation playing while reimporting is a very rare case and it's not unintuitive to see the animation stopped when re-imported.

**Review by TokageItLab — CHANGES_REQUESTED** [review]

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -1001,6 +1001,11 @@ void EditorNode::_resources_reimported(const Vector<String> &p_resources) {
 		}
 	}
 
+	if (scenes.size() > 0) {
+		// Editor may crash when related animation is playing while re-importing GLTF scene, stop it in advance.
+		AnimationPlayerEditor::get_singleton()->get_player()->stop(true);
+	}
+
```
[the remark this answers is not in the document]
Comment (jsjtxietian) [reply editor/editor_node.cpp:1008]: I added the scene size check because I only want to stop the animation when a gltf is reloaded. But I might be wrong. Thanks for helping with the null check!

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -1001,6 +1001,14 @@ void EditorNode::_resources_reimported(const Vector<String> &p_resources) {
 		}
 	}
 
+	if (scenes.size() > 0) {
```
Comment (fire) [inline editor/editor_node.cpp:1004]: Typically an index check is between >= 0 and < size(), but we check the negated version of that. Size will always be 0 > INT_MAX. So we don't have to check the < 0 case.

Comment (jsjtxietian) [reply editor/editor_node.cpp:1004]: So based on your comment, I guess the code here is fine ?

Comment (TokageItLab) [reply editor/editor_node.cpp:1004]: I think you can simply omit it.

File: editor/editor_node.cpp [hunk 3]
```diff
@@ -1001,6 +1001,12 @@ void EditorNode::_resources_reimported(const Vector<String> &p_resources) {
 		}
 	}
 
+	// Editor may crash when related animation is playing while re-importing GLTF scene, stop it in advance.
+	AnimationPlayer *ap = AnimationPlayerEditor::get_singleton()->get_player();
+	if (ap != nullptr) {
```
Comment (TokageItLab) [inline editor/editor_node.cpp:1006]:
```suggestion
	if (ap) {
```
他のほとんどのコードはこれで nullptr をチェックします。

**Review by TokageItLab — COMMENTED** [review]
Considering multithreading, it may be fine to stop before re-importing as just you have written.

Ideally, it would be better to resume playback if the animation has not changed after re-import, but given that this is editor-only, it is probably not worth it.

File: editor/editor_node.cpp (hunk 3 above)
Comment (TokageItLab) [reply editor/editor_node.cpp:1006]: > Is there anything different between 0 and 1? If there is no problem to call that stop() on both, then this check would not be necessary anyway.

I did comment above though. I missed your comment, does this mean that the animation does not stop when the image is re-imported, etc.? If so, I think `if (scenes.size() > 0)` check is available and required.

Comment (jsjtxietian) [reply editor/editor_node.cpp:1006]: > does this mean that the animation does not stop when the image is re-imported, etc.?

Yes.

**Review by TokageItLab — APPROVED** [review]
