### PR TITLE
Safer encode/decode variant.

### LINKED ISSUE #27395: RPC passes Objects by default
**Godot version:**
3.1

**OS/device including version:**
Debian 9

**Issue description:**
High level multiplayer API allows passing Objects with scripts to peers. This opens up a remote code execution exploit.

**Steps to reproduce:**
Initialize NetworkedMultiplayerENet on a client and server, connect them, and set them as the network peer interfaces for their respective scene trees. Pass scripted object over RPC.

**Minimal reproduction project:**
[Exploit.zip](https://github.com/godotengine/godot/files/3001649/Exploit.zip)

### PR DESCRIPTION
**Pull request by Faless**
This PR supersedes the other three. Closes #27399 Closes #27398 Closes #27442 .
Rationale.
Encoding decoding object variant is dangerous, and should never be the default.
The first 3 commits (e61a074, fbe7730, and 58a1f4a) do not change the exposed API but actively disable object variant encoding/decoding for all the methods that do not already expose an option to let the user decide (potentially breaking for users that relied on the dangerous functionality of object encoding).
It also swap the default parameters for `encode_variant` and `decode_variant` (not exposed directly) to make future internal code that uses them less likely to be bogus by mistake.

The other 2 commits (c06dd51, d9be3bf) add the `full_objects`/`allow_objects` parameters to respectively encoding and decoding functions:

- Network peers get_var/put_var
- File get_var/store_var
- GDScript/Mono/VisualScript/Expression bytes2var/var2bytes base64_to_variant/variant_to_base64
- Add MultiplayerAPI.allow_object_decoding member which deprecates PacketPeer.allow_object_decoding.

It also add docs for thos functions, but breaks ABI compatibaility (API compatibility for GDNative).

The question on what to do when cherry picking is left to release maintainers (@hpvb @akien-mga)... Should we only cherry-pick the first 3 (actively disabling a dangerous behaviour some users may rely on), or cherry pick all 5 commits, breaking ABI, still changing API behaviour for those dangerous cases, but giving users a chance to still decode objects by adding a parameter to their function call?

Please bear with me, helping out double-checking that changes are correct.

**EDIT**: Note that there is also a compat braking change where `Expression` now requires two parameters for bytes2var and var2bytes. I haven't found a way to have defaults there. Is it supported at all?

Fixes #27395

### CODE REVIEW

File: modules/mono/glue/gd_glue.cpp [hunk 1]
```diff
@@ -41,11 +41,11 @@
 
 #include "../mono_gd/gd_mono_utils.h"
 
-MonoObject *godot_icall_GD_bytes2var(MonoArray *p_bytes) {
```
Comment (neikeq) [inline modules/mono/glue/gd_glue.cpp]: Should be `MonoBoolean` instead of `bool`.

File: modules/mono/glue/gd_glue.cpp [hunk 2]
```diff
@@ -187,19 +187,19 @@ void godot_icall_GD_pushwarning(MonoString *p_str) {
 	WARN_PRINTS(GDMonoMarshal::mono_string_to_godot(p_str));
 }
 
-MonoArray *godot_icall_GD_var2bytes(MonoObject *p_var) {
```
Comment (neikeq) [inline modules/mono/glue/gd_glue.cpp]: ditto

File: modules/mono/glue/gd_glue.h [hunk 3]
```diff
@@ -35,7 +35,7 @@
 
 #include "../mono_gd/gd_mono_marshal.h"
 
-MonoObject *godot_icall_GD_bytes2var(MonoArray *p_bytes);
```
Comment (neikeq) [inline modules/mono/glue/gd_glue.h]: ditto

File: modules/mono/glue/gd_glue.h [hunk 4]
```diff
@@ -71,7 +71,7 @@ MonoObject *godot_icall_GD_str2var(MonoString *p_str);
 
 bool godot_icall_GD_type_exists(MonoString *p_type);
 
-MonoArray *godot_icall_GD_var2bytes(MonoObject *p_var);
```
Comment (neikeq) [inline modules/mono/glue/gd_glue.h]: ditto

**Review by neikeq — DISMISSED** [review]

**Comment by Faless** [comment]
@neikeq thanks! Fixed. BTW, **good job** on the mono module, it's getting really awesome :+1: :1st_place_medal:

**Comment by Xrayez** [comment]
This seems to work fine, but I wasn't dealing with variant encoding/decoding in the first place in my project, so at least no regressions hopefully. Integrate-tested file system encoding/decoding only.

File: doc/classes/PacketPeer.xml [hunk 5]
```diff
@@ -60,6 +60,7 @@
 	</methods>
 	<members>
 		<member name="allow_object_decoding" type="bool" setter="set_allow_object_decoding" getter="is_object_decoding_allowed">
+				If [code]true[/code] the PacketPeer will allow encoding and decoding of object via [method get_var] and [method put_var]. WARNING: Deserialized object can contain code which gets executed. Do not use this option if the serialized object comes from untrusted sources to avoid potential security threats (remote code execution).
```
Comment (akien-mga) [inline doc/classes/PacketPeer.xml]: One tab too much for indentation.

Comment (akien-mga) [reply doc/classes/PacketPeer.xml]: Maybe use `[b]WARNING:[/b]` to highlight it (and a line break before to make a new paragraph).

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
393e62b caused #27651, which #28052 aims to fix. The rest of the changes should likely also be reviewed to see if there are other cases where we do want to decode objects.

**Comment by Faless** [comment]
I was actually surprised to see that the Project Settings InputMap was working.
But yeah, I didn't export it, so of course it was working, it was using `var2str` and not `var2bytes` -.- :crying_cat_face:

**Comment by hpvb** [comment]
Cherry-picked for 3.1.1.

Entirely, breaking GDNative ABI

**Comment by akien-mga** [comment]
Which commits can we cherry-pick for the 3.0 branch, to avoid breaking compat?

**Comment by Faless** [comment]
@akien-mga the most conservative choice is to only cherry pick the second commit (but add a negation `!` to values passed to `encode_variant`, since the previous commit flipped the meaning of `encode_variant` last parameter).

That fixes the MultiplayerAPI security issue, do not break other compat (beside for people relying on object decoding who would need to set the appropriate option to true in the ENetPeer).

That will not fix other potential security issues derived from using `var2bytes` `bytes2var` etc directly.

I can make a PR on 3.0 referencing this if you like.

**Comment by akien-mga** [comment]
> I can make a PR on 3.0 referencing this if you like.

That would be great :)

**Comment by akien-mga** [comment]
Removing `cherrypick:3.0` label as the 3.0 version was merged in #30306.
