### PR TITLE
Ignore rename shortcut when Remote tab is active

### LINKED ISSUE #106306: It is possible to make changes in the tree while the game is running
### Tested versions

v4.5.dev3.official [28089c4]

### System information

Godot v4.5.dev3

### Issue description

If you press F2 in the tree during an active game session, you can rename something not within the game itself, but externally. Obviously, this key should be disabled in game mode. This leads to an error:
`ERROR: editor/gui/scene_tree_editor.cpp:1627 - Parameter "which" is null.`

### Steps to reproduce

https://youtu.be/87uxn0rJnvs

### Minimal reproduction project (MRP)

--

### PR DESCRIPTION
**Pull request by sakubou**
Fixes #106306 

In shortcut_input(), an early exit is now taken if edit_remote->is_pressed(), skipping all local-node shortcuts (e.g. rename, delete, cut).

### CODE REVIEW

**Comment by KoBeWi** [comment]
IMO blocking every shortcut is too much. Right now you can e.g. select nodes in 2D editor and delete them, and it will be synced with the running project. Selecting a node will deselect any selected remote node, and show the selected node in the inspector, so I think this behavior is fine.
Also some shortcuts are still actove, like Add Node (Ctrl+A).

The main problem here is that renaming a node with visible remote tree is broken. The popup appears at wrong position and the rename takes no effect.
Either the rename should be blocked (only), or the local tree should automatically appear on rename.

**Comment by sakubou** [comment]
Okay understood! I’ve adjusted it to solely block the rename shortcut.

File: editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -184,6 +184,9 @@ void SceneTreeDock::shortcut_input(const Ref<InputEvent> &p_event) {
 		if (focus_owner && (Object::cast_to<BaseButton>(focus_owner) || Object::cast_to<Range>(focus_owner))) {
 			return;
 		}
+		if (edit_remote->is_pressed()) {
```
Comment (KoBeWi) [inline editor/scene_tree_dock.cpp:187]: Could probably use a comment.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
