### PR TITLE
Fix LineEdit Unicode code-point/control character insertion failing to emit `text_changed`

### LINKED ISSUE #110809: `text_changed` not emitted for code point input and Insert Control Character options
### Tested versions

4.5.stable

### System information

Godot v4.5.stable unknown - Arch Linux # 1 SMP PREEMPT_DYNAMIC Fri, 19 Sep 2025 15:58:36 +0000 on X11 - X11 display driver, Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3060 Ti (nvidia; 580.82.09) - 13th Gen Intel(R) Core(TM) i5-13400F (16 threads) - 15.37 GiB memory

### Issue description

`LineEdit` supports Unicode code point input (`Ctrl+Shift+U` + Code Point) since 4.4. But it does not trigger `text_changed` signal.

After further test, adding a character via the Insert Control Character options in the context menu does not trigger `text_changed` too.

### Steps to reproduce

Use any `LineEdit` and check the `text_changed` signal. You can also use text boxes in the editor that reacts to empty text, e.g., the Project name input in Create Project dialog, the name input in Create Folder dialog.

- Unicode code point input
    - `Ctrl+Shift+U`, an underlined `u` appears
    - `2020` and hit enter, an `†` character is inserted
- Insert Control Character
   -  Right click in the `LineEdit` and choose any option in the Insert Control Character sub menu.

You can see that `text_changed` is not emitted. (Some editor input validation output still says that it's empty.)

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by SantiagoDaza3**
### Summary
`LineEdit` did not emit `text_changed` when text was inserted via Unicode code-point input and the “Insert Control Character” menu. This would break UI logic that depends on `text_changed`.

### Reproduction
Minimal scene with a single `LineEdit` element and the following attached script:

```Python
extends LineEdit
func _ready():
    text_changed.connect(func(new_text):
        print("text_changed:", new_text))
```

Pressing ctrl + shift + u and typing `2020` then pressing enter inserts the dagger character (†) but does not trigger `text_changed` i.e. no print statement is written to the console.

Right click + Insert Control Character (pick any) also inserts but does **not** trigger `text_changed`.

https://github.com/user-attachments/assets/7b3ac2a4-2b5b-4b6c-adad-1ac9fc9d4ea1

### Fix
After performing the two aforementioned insertions, defer `_text_changed()` and set the `text_changed_dirty` guard (exact same process used in `paste_text()` ). Regular typing and paste behavior remains unaffected. `set_text()` is unchanged and still does **not** emit, as per the documentation. This is a small, localized fix in `scene/gui/line_edit.cpp`

https://github.com/user-attachments/assets/6d11362b-e9e6-4047-97b9-8e55f7624c5b

### Testing
Verified fix on a Windows dev build, code-point submission and control character insertion now print once to the console and update any bound UI elements. Regular typing, paste, and deletions have been verified to still emit exactly once.

Formatting: clang-format 17

Fixes #110809

Note: There is an overlapping PR #110988 that instead moves the `text_changed` emission logic to the core function `insert_text_at_caret()` while removing `text.length() != prev_len` checks to determine whether to emit `text_changed` or not. Let me know if this more general change to a core function is preferred, as the changes in my PR attempt to fix two specific bugs without altering core functions while aligning with the existing architecture. A previous PR #84382 also attempted to alter `insert_text_at_caret()` directly which resulted in duplicate signals.

### CODE REVIEW

File: scene/gui/line_edit.cpp [hunk 1]
```diff
@@ -818,6 +818,7 @@ void LineEdit::gui_input(const Ref<InputEvent> &p_event) {
 	if ((!k->is_pressed() && alt_start && k->get_keycode() == Key::ALT) || (alt_start_no_hold && (k->is_action("ui_text_submit", true) || k->is_action("ui_accept", true)))) {
 		alt_start = false;
 		alt_start_no_hold = false;
+		int prev_len = false;
```
Comment (AThousandShips) [inline scene/gui/line_edit.cpp]:
```suggestion
		int prev_len = text.length();
```
Copy paste error I assume

File: scene/gui/line_edit.cpp [hunk 2]
```diff
@@ -849,6 +850,13 @@ void LineEdit::gui_input(const Ref<InputEvent> &p_event) {
 			ime_selection = Vector2i();
 			_shape();
 		}
+		// Mirror paste behavior: defer text_changed once per frame while emitting text_changed signal.
```
Comment (AThousandShips) [inline scene/gui/line_edit.cpp]:
```suggestion
		// Mirror paste behavior: defer _text_changed once per frame while emitting text_changed signal.
```
The method has an underscore

File: scene/gui/line_edit.cpp [hunk 3]
```diff
@@ -2638,87 +2648,111 @@ void LineEdit::menu_option(int p_option) {
...
 				insert_text_at_caret(String::chr(0x00AD));
+				inserted_control_char = true;
 			}
 		} break;
 		case MENU_EMOJI_AND_SYMBOL: {
 			show_emoji_and_symbol_picker();
 		} break;
 	}
+
+	// Mirror paste/drag behavior, emit _text_changed signal if a control character was inserted.
```
Comment (AThousandShips) [inline scene/gui/line_edit.cpp]:
```suggestion
	// Mirror paste/drag behavior, emit text_changed signal if a control character was inserted.
```
The signal doesn't have that prefix, or just match the other comment

File: scene/gui/line_edit.cpp (hunk 1 above)
Comment (SantiagoDaza3) [reply scene/gui/line_edit.cpp]: Good catch, thank you. Seems like I got mixed up with the two assignments immediately preceding the line in question. Fixed!

File: scene/gui/line_edit.cpp [hunk 4]
```diff
@@ -818,6 +818,7 @@ void LineEdit::gui_input(const Ref<InputEvent> &p_event) {
 	if ((!k->is_pressed() && alt_start && k->get_keycode() == Key::ALT) || (alt_start_no_hold && (k->is_action("ui_text_submit", true) || k->is_action("ui_accept", true)))) {
 		alt_start = false;
 		alt_start_no_hold = false;
+		int prev_len = text.length();
 		if ((alt_code > 0x31 && alt_code < 0xd800) || (alt_code > 0xdfff)) {
```
Comment (bruvzg) [inline scene/gui/line_edit.cpp:823]: New code can be in this `if`, since it's the only branch with `insert_text_at_caret`.

```c++
if ((alt_code > 0x31 && alt_code < 0xd800) || (alt_code > 0xdfff)) {
	int prev_len = text.length();

	ime_text = String();
	ime_selection = Vector2i();
	...
	alt_mode = ALT_INPUT_NONE;
	// Mirror paste behavior: defer text_changed once per frame while emitting text_changed signal.
	if (!text_changed_dirty) {
		if (is_inside_tree() && text.length() != prev_len) {
			callable_mp(this, &LineEdit::_text_changed).call_deferred();
		}
		text_changed_dirty = true;
	}
} else {
	ime_text = String();
	ime_selection = Vector2i();
	_shape();
}
```

**Review by bruvzg — APPROVED** [review]
It's only affecting user input, so should be safe.

File: scene/gui/line_edit.cpp (hunk 4 above)
Comment (SantiagoDaza3) [reply scene/gui/line_edit.cpp:823]: Good point, I went ahead and moved the new code within the `if` that calls `insert_text_at_caret`.

**Comment by SantiagoDaza3** [comment]
Thanks for the code reviews, I've applied all the suggested changes and CI is showing up green. Let me know if any more modifications are needed.

**Comment by Repiteo** [comment]
Could you squash your commits? See our [pull request guidelines](https://contributing.godotengine.org/en/latest/organization/pull_requests/creating_pull_requests.html#the-interactive-rebase) for more information

**Comment by SantiagoDaza3** [comment]
> Could you squash your commits? See our [pull request guidelines](https://contributing.godotengine.org/en/latest/organization/pull_requests/creating_pull_requests.html#the-interactive-rebase) for more information

Done! The extra code review commits have been squashed.

**Comment by Repiteo** [comment]
Perfect! Now there's just one last thing: you'll need to remove the trailing `Fixes Issue #110809` message from the commit, as it otherwise produces unwanted pings whenever that commit is mentioned

**Comment by SantiagoDaza3** [comment]
> Perfect! Now there's just one last thing: you'll need to remove the trailing `Fixes Issue #110809` message from the commit, as it otherwise produces unwanted pings whenever that commit is mentioned

All done!

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
