### PR TITLE
Fix collision reposition with `CSGShape3D`

### LINKED ISSUE #102274: Reposition Using Collisions bug Godot v4.4
### Tested versions

Godot v4.4.beta2 the new feature reposition using collisions doesn't like if you move a csgbox inside a csgcombiner with collision enabled

### System information

Godot v4.4.beta2 - Windows 11 (build 22631) - Multi-window, 3 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce GTX 1070 (NVIDIA; 32.0.15.6614) - AMD Ryzen 5 3600 6-Core Processor (12 threads)

### Issue description

https://github.com/user-attachments/assets/d77c120b-9ff9-47da-b675-f4c235304706

### Steps to reproduce

Watch video above

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by ryevdokimov**
Fixes: https://github.com/godotengine/godot/issues/102274

https://github.com/user-attachments/assets/fdcc691d-8533-4430-b6f7-8dafdb75610d

### CODE REVIEW

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -81,6 +81,7 @@
 #include "editor/plugins/gizmos/voxel_gi_gizmo_plugin.h"
 #include "editor/plugins/node_3d_editor_gizmos.h"
 #include "editor/scene_tree_dock.h"
+#include "modules/csg/csg_shape.h"
```
Comment (akien-mga) [inline editor/plugins/node_3d_editor_plugin.cpp:84]: This breaks encapsulation - general editor code shouldn't include module specific code normally. Ideally the CSG module should be self-contained and responsible for exposing what's needed for the generic logic to handle it.

Comment (fire) [reply editor/plugins/node_3d_editor_plugin.cpp:84]: Needs to be resolve for approval

Comment (KoBeWi) [reply editor/plugins/node_3d_editor_plugin.cpp:84]: I can think of 2 solutions:
- more general: add `_edit_get_collision_rid()` method. Can be dynamic
- to only remove the include: use `is_class()` and call `get_root_collision_instance()` via `call()`.

Comment (ryevdokimov) [reply editor/plugins/node_3d_editor_plugin.cpp]: Opted for the 2nd solution, since it seems straighter forward, and this pattern doesn't seem particularly unique from looking around in the engine.

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 2]
```diff
@@ -4385,6 +4385,10 @@ void _insert_rid_recursive(Node *node, HashSet<RID> &rids) {
 		rids.insert(co->get_rid());
 	}
 
+	if (node->is_class("CSGShape3D")) {
+		rids.insert(node->call("get_root_collision_instance"));
+	}
+
```
Comment (fire) [inline editor/plugins/node_3d_editor_plugin.cpp:4391]: This is still breaking encapsulation. I remember we may have added call back functions, but I don't remember.

Comment (KoBeWi) [reply editor/plugins/node_3d_editor_plugin.cpp:4391]: No such function is used here, so probably it does not exist, or is for something else.

Comment (ryevdokimov) [reply editor/plugins/node_3d_editor_plugin.cpp:4391]: CSG collision shapes from what I can tell are unique in how they're generated by having the parent hold the identity of the collision resource. Somehow which behavior is being used needs to be identified and the RIDs retrieved that way. Currently not seeing any obvious way to do that, but I'll keep thinking about it.

Comment (Hilderin) [reply editor/plugins/node_3d_editor_plugin.cpp:4391]: I'm no expert in the matter but I faced a similar problem in #101368. Maybe one idea could be to add some kind of `get_collision_rid` method in `VisualInstance3D` that returns an empty RID and overload it in `CsgShape`?

Comment (ryevdokimov) [reply editor/plugins/node_3d_editor_plugin.cpp:4391]: >Maybe one idea could be to add some kind of get_collision_rid method in VisualInstance3D

Adding a method for getting collision related data in an object meant only for visual things seems strange to me, and I'm not sure much better than breaking encapsulation in this scenario. I'm opened to second opinions though.

**Review by Calinou — COMMENTED** [review]
Tested locally, it works as expected.

**Testing project:** [test_pr_102286.zip](https://github.com/user-attachments/files/18741061/test_pr_102286.zip)

Note that it won't work if the CSGBox you're moving is a child of the CSGCombiner3D with the collision on it. It will just pass through instead:

https://github.com/user-attachments/assets/41a9cfbe-4601-414d-ac92-d7b87e30df0c

This may be difficult to resolve though, given the collision shape is regenerating itself in real-time when you're moving the object (and you don't want the object to collide with itself as you're repositioning it).

PS: I noticed that we can pan, zoom and orbit while using physics-based repositioning, but not when using the translate/rotate/style Blender-style manipulation shortcuts. It would be good to look into unlocking those options if they don't conflict with anything else (in a separate PR).

File: modules/csg/csg_shape.cpp [hunk 3]
```diff
@@ -982,6 +992,8 @@ void CSGShape3D::_bind_methods() {
 	ClassDB::bind_method(D_METHOD("set_collision_mask_value", "layer_number", "value"), &CSGShape3D::set_collision_mask_value);
 	ClassDB::bind_method(D_METHOD("get_collision_mask_value", "layer_number"), &CSGShape3D::get_collision_mask_value);
 
+	ClassDB::bind_method(D_METHOD("get_root_collision_instance"), &CSGShape3D::get_root_collision_instance);
```
Comment (Calinou) [inline modules/csg/csg_shape.cpp:995]: Is there a need to expose this method? If not, I'd avoid exposing it so we don't have to preserve compatibility for it.

Comment (akien-mga) [reply modules/csg/csg_shape.cpp:995]: This is needed to `call()` it in `Node3DEditorPlugin`, as that goes through the binding system.

But it should probably be prefixed with `_` so it doesn't appear in the public API/docs.

File: editor/plugins/node_3d_editor_plugin.cpp (hunk 2 above)
Comment (akien-mga) [reply editor/plugins/node_3d_editor_plugin.cpp:4391]: It would likely go in `GeometryInstance3D` I think, and not `VisualInstance3D`? (The former inherits the latter.)

Collision data in geometry is slightly more related I suppose.

But yeah I don't see an easy/clean solution.

File: modules/csg/csg_shape.cpp (hunk 3 above)
Comment (ryevdokimov) [reply modules/csg/csg_shape.cpp]: Done.

File: editor/plugins/node_3d_editor_plugin.cpp (hunk 2 above)
Comment (ryevdokimov) [reply editor/plugins/node_3d_editor_plugin.cpp]: I agree that would be marginally better, but still is it worth muddying up the classes to handle niche cases like this? I just don't want a precedent to be set that might end up making things confusing down the future. I feel like the real solution to this is something more fundamental that I can't pin down quite yet.

**Review by akien-mga — APPROVED** [review]

**Review by Calinou — APPROVED** [review]

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 4]
```diff
@@ -4385,6 +4385,10 @@ void _insert_rid_recursive(Node *node, HashSet<RID> &rids) {
 		rids.insert(co->get_rid());
 	}
 
+	if (node->is_class("CSGShape3D")) {
```
Comment (KoBeWi) [inline editor/plugins/node_3d_editor_plugin.cpp:4388]:
```suggestion
	} else if (node->is_class("CSGShape3D")) {
```
These conditions are mutually exclusive, so no reason to check both.

**Review by KoBeWi — APPROVED** [review]
Didn't test, but the code looks ok.

File: editor/plugins/node_3d_editor_plugin.cpp (hunk 4 above)
Comment (ryevdokimov) [reply editor/plugins/node_3d_editor_plugin.cpp]: Done

File: editor/plugins/node_3d_editor_plugin.cpp (hunk 2 above)
Comment (ryevdokimov) [reply editor/plugins/node_3d_editor_plugin.cpp]: I added a comment in the code to point on this is a hack. I do plan on developing this snapping idea further, see: https://github.com/godotengine/godot/pull/100415 for example, so maybe something will hit me in the head during the process.

**Comment by Repiteo** [comment]
Thanks!
