### PR TITLE
Validate custom directory when project is started

### LINKED ISSUE #103367: Validate `Custom User Dir Name`, disallow absolute `user://` and `res://` paths
### Tested versions

4.4.beta4 but was already present in the previous versions 

### System information

Apple Macbook M3 Pro - MacOS Sequoia 15.3.1

### Issue description

When using Forward+ renderer on macosx error log is filled with
```cpp
E 0:00:00:099   _save_to_cache: Condition "f.is_null()" is true.
  <C++ Source>  servers/rendering/renderer_rd/shader_rd.cpp:512 @ _save_to_cache()
```

**EDIT:** with this settings (`user://`)
Image

Image

The errors disappear with renderer "Compatibility"

I tried deleting the shader_cache directory inside project and in global library user data, they do fill again both

I checked all shaders of my project, no error or warning in shader editor

I don't know how to debut the path that is accessed in the editor code:  

Image

### Steps to reproduce

I don't know if this is linked to my project or a common issue on the development platform

### Minimal reproduction project (MRP)

I can't provide a minimal project

### PR DESCRIPTION
**Pull request by runbozhuang**
Fixes #103367

### CODE REVIEW

**Comment by runzh-crypto** [comment]
Pushed again, for fixing clang-format issue

**Comment by KoBeWi** [comment]
That validation doesn't seem valid. A folder may exist for multiple reasons, the most common one being that you just changed the path, which case you won't be able to run the project until restart. or opening the folder from Project menu.

Also the original issue had problems specifically with overrides, which this PR does not check. If you set `application/config/custom_user_dir_name.web`, you will have potentially broken Web export, but the safeguard won't tell you that.

**Comment by runzh-crypto** [comment]
> That validation doesn't seem valid. A folder may exist for multiple reasons, the most common one being that you just changed the path, which case you won't be able to run the project until restart. or opening the folder from Project menu.
> 
> Also the original issue had problems specifically with overrides, which this PR does not check. If you set `application/config/custom_user_dir_name.web`, you will have potentially broken Web export, but the safeguard won't tell you that.

Thank you for reviewing the code, now I am confused about this issue. 
As I understand 
1) the main issue is because the custom dir will somehow  affect the shader_cache_dir, which cause shader_cache_dir to be empty, and then the error happens
2) if 1) is correct, then I suppose I just validating the custom dir name should be enough, note that the custom dir won't affect cache folder name as well 
3) regarding this case "application/config/custom_user_dir_name.web", I am not sure what can I do for it
I tried to search .web but I cannot find related code, do you know what test case I should use ?

**Comment by runzh-crypto** [comment]
Pushed another verison with rebase
Basically use same logic as Editor_Paths.cpp, validate the dir from custom dir
A known issue is, custom dir name will use safe dir name, 
e.g. converting ":" to "-"
1) user:// -> user-//
2) user: -> user-

**Comment by KoBeWi** [comment]
> regarding this case "application/config/custom_user_dir_name.web", I am not sure what can I do for it
I tried to search .web but I cannot find related code, do you know what test case I should use ?

https://github.com/godotengine/godot/issues/103367#issuecomment-2740562487

**Comment by Alex2782** [comment]
**Some hints:** on MacOs _(maybe also on Linux and Android)_

- The function `fopen` returns error 2 (`ENOENT -> ERR_FILE_NOT_FOUND`) if the path contains "//" `(mode_string = "wb")`, -> write mode
- If the shader cache is already present, it seems to work with "//" in the path. `mode_string = "rb"` -> read mode

image


https://github.com/godotengine/godot/blob/12384d93db851f210d785194d6bb72073bdeace4/drivers/unix/file_access_unix.cpp#L140-L154

**Comment by runzh-crypto** [comment]
> > regarding this case "application/config/custom_user_dir_name.web", I am not sure what can I do for it
> > I tried to search .web but I cannot find related code, do you know what test case I should use ?
> 
> [#103367 (comment)](https://github.com/godotengine/godot/issues/103367#issuecomment-2740562487)

Thank you for the information and feedback

I spend some time for checking this, but I am not super sure I am doing it in the right way.
1) I tried to add a "application/config/custom_user_dir_name.web", and then fill in "user://" or "test//test"
And then I do a web export, it seems working fine, exporting is not terminated 

2) I tried to use .windows for testing, it seems working correctly. 
e.g. If I set user_dir_name.windows as "test//test2", and then as user_dir_name as "test".
The user_dir_name.windows will take priority still, and then find out the invalid folder.
image
`
String data_dir = OS::get_singleton()->get_user_data_dir();
`
`
String custom_dir = OS::get_singleton()->get_safe_dir_name(GLOBAL_GET("application/config/custom_user_dir_name.windows"), true);
`

I also have some quetiones about these settings. 
1) it means the setting will only be triggered when I am using specific platform ? 
(I am using Windows, when I set a .macos user_dir_name.macos, it doesn't seem to get the value).
2) any way I can simulating to test other platform case ? e.g.  trigger the engine to get .macos value

**Comment by runzh-crypto** [comment]
> **Some hints:** on MacOs _(maybe also on Linux and Android)_
> 
> * The function `fopen` returns error 2 (`ENOENT -> ERR_FILE_NOT_FOUND`) if the path contains "//" `(mode_string = "wb")`, write mode
> * If the shader cache is already present, it seems to work with "//" in the path. `mode_string = "rb"`, read mode
> 
> image
> 
> https://github.com/godotengine/godot/blob/12384d93db851f210d785194d6bb72073bdeace4/drivers/unix/file_access_unix.cpp#L140-L154

Thank you for the hints. 
1)Do you use current branch for testing OR you test it in master branch ? 
Because it seems not working at all in Windows. 

2)In this case, should we handle it OR we should fix "//" issue in a separate ticket ?

**Comment by KoBeWi** [comment]
> any way I can simulating to test other platform case ? e.g. trigger the engine to get .macos value

You can use Debug -> Customize Run Instances and set feature tags.

**Comment by Alex2782** [comment]
> 1) Do you use current branch for testing OR you test it in master branch ? Because it seems not working at all in Windows.
> 2) In this case, should we handle it OR we should fix "//" issue in a separate ticket ?

1) I tried `master` branch a few days ago
2) I'm not sure, I'll try to check tomorrow on Windows and Android what exactly is happening there.

**Comment by Alex2782** [comment]
I tested on Windows, with `\\` and `//`. (Vulkan + OpenGLES)
_The function `get_safe_dir_name` converts all `\` characters to `/`_

`ERR_PRINT("Can't create shader cache folder, no shader caching will happen: " + shader_cache_dir);
`

I think the safest change for all OS would be to simply replace `//` with `/`, in the function `OS::get_user_data_dir()`. `GLOBAL_GET` also considers `overrides`


```cpp
String OS::get_user_data_dir() const {
	String appname = get_safe_dir_name(GLOBAL_GET("application/config/name"));
	if (!appname.is_empty()) {
		bool use_custom_dir = GLOBAL_GET("application/config/use_custom_user_dir");
		if (use_custom_dir) {
			String custom_dir = get_safe_dir_name(GLOBAL_GET("application/config/custom_user_dir_name"), true);
			if (custom_dir.is_empty()) {
				custom_dir = appname;
			} else {
				custom_dir = custom_dir.replace("//", "/"); // <--- NEW
			}
```
-------------------



In the function `get_safe_dir_name` replace might also be possible, but I'm not sure what effect it would have on other functions.


```cpp
// Helper function to ensure that a dir name/path will be valid on the OS
String OS::get_safe_dir_name(const String &p_dir_name, bool p_allow_paths) const {
	String safe_dir_name = p_dir_name;
	Vector<String> invalid_chars = String(": * ? \" < > |").split(" ");
	if (p_allow_paths) {
		// Dir separators are allowed, but disallow ".." to avoid going up the filesystem
		invalid_chars.push_back("..");
		safe_dir_name = safe_dir_name.replace("\\", "/").replace("//", "/").strip_edges();
	} else {


```

**Comment by runzh-crypto** [comment]
@Alex2782 Thanks for the testing and information

I tried both, and it works well 
personally I prefer to use the second way, since it is more robust to convert mutiple / OR \ to a single one
Which is what method name represent to, get_safe_dir_name.

**Comment by Alex2782** [comment]
> Perhaps we should have another checking for "user://" and "res://", because Custom User Dir Name essentially is an additional path from user://, what do you think ?

I tried it on MacOS, and we can probably remove the `validate_custom_directory` function. To test your validation function, I hardcoded an absolute path without write permissions.

<details><summary>cpp</summary>

```cpp
bool EditorNode::validate_custom_directory() {
	print_line("EditorNode::validate_custom_directory()");
	bool use_custom_dir = GLOBAL_GET("application/config/use_custom_user_dir");

	if (use_custom_dir) {
		String data_dir = OS::get_singleton()->get_user_data_dir();
		data_dir = "/test/test";
		print_line("data_dir: ", data_dir);
```
</details>

<details><summary>screenshot</summary>

Bildschirmfoto 2025-03-28 um 20 22 36
</details>

------------------

Test on MacOS with special characters and smileys was successful.

image

```
test/1_ßüäö+'#´`"%$&/()=°^€.:,;?§$😅☹ᕕ( ᐛ )ᕗ1
```

I think on Android or Windows, the validation function will also always create valid paths in the user directory.
If not, we can extend the `OS::get_safe_dir_name` function again and replace invalid characters.

Bildschirmfoto 2025-03-28 um 20 43 24

**Comment by runzh-crypto** [comment]
> I tried it on MacOS, and we can probably remove the `validate_custom_directory` function. To test your validation function, I hardcoded an absolute path without write permissions.

So you mean we only keep the changes in os.cpp ? 
If we remove the '`validate_custom_directory' function, the invalid path will still tigger the error.
e.g. using "test///test", it will be convert to "test//test" which is still invalid and causing the issue

**Comment by Alex2782** [comment]
> If we remove the '`validate_custom_directory' function, the invalid path will still tigger the error.
> e.g. using "test///test", it will be convert to "test//test" which is still invalid and causing the issue

Ok, I haven't tried the `validate_custom_directory` function on Windows yet, but if the message appears there, then it has the right to exist.

Otherwise, we can replace the characters in a loop until no more (`//` and `\\`) are found. However, I'm still not sure whether the `get_safe_dir_name` function can be extended. That's up to others to decide.

**Comment by runzh-crypto** [comment]
Hi @KoBeWi 
Sorry for bothering you, would you mind to take a look at the changes, and see if there is any improvement I can do ? 

Thanks a lot !

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -8188,6 +8212,11 @@ EditorNode::EditorNode() {
 	select_current_scene_button = pick_main_scene->add_button(TTR("Select Current"), true, "select_current");
 	pick_main_scene->connect("custom_action", callable_mp(this, &EditorNode::_pick_main_scene_custom_action));
 
+	open_project_settings = memnew(ConfirmationDialog);
+	gui_base->add_child(open_project_settings);
+	open_project_settings->set_ok_button_text(TTR("Open Project Settings"));
```
Comment (KoBeWi) [inline editor/editor_node.cpp:8217]:
```suggestion
	open_project_settings->set_ok_button_text(TTRC("Open Project Settings"));
```

**Review by KoBeWi — APPROVED** [review]
Looks good now.

File: editor/editor_node.cpp (hunk 1 above)
Comment (runzh-crypto) [reply editor/editor_node.cpp]: Updated now

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉

**Comment by runzh-crypto** [comment]
> Thanks! Congratulations on your first merged contribution! 🎉

Thanks everone for giving feedback and reviewing this PR !

**Comment by KoBeWi** [comment]
I just discovered that this only handles the case when starting the project normally (F5).
When running current scene (F6), the path is not validated. Interestingly, the project will crash on startup when folder is invalid (not caused by this PR). Can be easily tested by putting a Windows reserved name as data directory, e.g. CON.

**Comment by runzh-crypto** [comment]
> I just discovered that this only handles the case when starting the project normally (F5). When running current scene (F6), the path is not validated. Interestingly, the project will crash on startup when folder is invalid (not caused by this PR). Can be easily tested by putting a Windows reserved name as data directory, e.g. CON.

@KoBeWi  Is there a known issue about it, if not I can create a new issue about this crash. 
In this case, perhaps we can include the F6 case for preventing the crash, what do you think ?

**Comment by KoBeWi** [comment]
Looks like the same issue as #103367. I couldn't reproduce it with the original example, but with the reserved name on Windows it results in a crash.

The fix you did should be probably moved deeper (in EditorRunBar I think?), so that it handles any form of running. Aside from project and current scene, you can run a custom scene or run from a plugin.

**Comment by runzh-crypto** [comment]
> The fix you did should be probably moved deeper (in EditorRunBar I think?), so that it handles any form of running. Aside from project and current scene, you can run a custom scene or run from a plugin.
Yeah, I agree with it !
Sure, I guess I can create another branch for this change ? (since the original branch is already merged into master)
basically move the change to where it trigger project start (not just a specfic start of project)

**Comment by runzh-crypto** [comment]
> > The fix you did should be probably moved deeper (in EditorRunBar I think?), so that it handles any form of running. Aside from project and current scene, you can run a custom scene or run from a plugin.
Yeah, I agree with it !
 I guess I can create another branch for this change ? (since the original branch is already merged into master)
basically move the change to where it trigger project start (not just a specfic start of project)

**Comment by runzh-crypto** [comment]
> The fix you did should be probably moved deeper (in EditorRunBar I think?), so that it handles any form of running. Aside from project and current scene, you can run a custom scene or run from a plugin.

Yeah, I agree with it !
 I guess I can create another branch for this change ? (since the original branch is already merged into master)
basically move the change to where it trigger project start (not just a specfic start of project)

**Comment by KoBeWi** [comment]
Yes, you need to open a new pull request. The implementation will be likely similar, you only need to move the code.
