### PR TITLE
Re-add `Skeleton3D::animate_physical_bones` property

### LINKED ISSUE #90880: Re-add `Skeleton3D::animate_physical_bones` property and `Skeleton3D::bone_pose_updated` signal
### Tested versions

- Reproducible in v4.3.dev.mono.custom_build [2efbc6bfb]

### System information

Pop OS 21.04

### Issue description

As I was looking into the compat break in 4.3 for the migration guide (https://github.com/godotengine/godot-docs/pull/9250) I found these changes in `Skeleton3D` that look like they could be avoided.

The property `animate_physical_bones`:
- It was removed in https://github.com/godotengine/godot/pull/87888.
- The methods `set_animate_physical_bones` and `get_animate_physical_bones` are still available, so they could be used to re-expose the property.

The signal `bone_pose_updated`:
- It was replaced by `skeleton_updated` in https://github.com/godotengine/godot/pull/90575.
- We could re-add the old signal and emit it when `pose_updated` is emitted which seems to be the suggested alternative, so existing user code still works.

### Steps to reproduce

Try to use any of the mentioned members in GDScript or C#.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by TokageItLab**
- Closes https://github.com/godotengine/godot/issues/90880

~The `bone_pose_updated` signal is very dangerous as described in https://github.com/godotengine/godot/pull/90575, so it is reimplemented as an alias of `skeleton_updated`.~ We cannot re-add a compatible signal that is not hazardous and has no performance problems, so bone_pose_changed signal should be eliminated.

- Follow-up https://github.com/godotengine/godot/pull/93504

The internal PhysicalBoneSimulator3D is set after enter_tree, so that `animate_physical_bones` is updated once there.

However, the old configuration where PhysicalBone is directly a child of Skeleton3D without already having PhysicalBoneSimulator3D is deprecated, so it is placed under the group "Deprecated", to avoid confusion if the user follows the recommended new settings and has PhysicalBoneSimulator3D explicitly.

image

### CODE REVIEW

File: scene/3d/skeleton_3d.cpp [hunk 1]
```diff
@@ -1097,6 +1101,14 @@ void Skeleton3D::_bind_methods() {
...
 	ClassDB::bind_method(D_METHOD("physical_bones_add_collision_exception", "exception"), &Skeleton3D::physical_bones_add_collision_exception);
 	ClassDB::bind_method(D_METHOD("physical_bones_remove_collision_exception", "exception"), &Skeleton3D::physical_bones_remove_collision_exception);
+
+	ADD_GROUP("Deprecated", "");
+	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "animate_physical_bones"), "set_animate_physical_bones", "get_animate_physical_bones");
+
+	// Note:
+	// In the old Skeleton3D, it really was fired every time the pose was changed, which means it could be fired dozens of times in one frame.
+	// It was very dangerous in terms of performance and potentially breaking the processing order, so for now it should just be an alias of "skeleton_updated".
+	ADD_SIGNAL(MethodInfo("bone_pose_updated"));
```
Comment (raulsntos) [inline scene/3d/skeleton_3d.cpp:1111]: Sorry, my bad. It looks like the signal was called `bone_pose_changed`. It also had an int parameter `bone_idx`.

```suggestion
	ADD_SIGNAL(MethodInfo("bone_pose_changed", PropertyInfo(Variant::INT, "bone_idx")));
```

File: scene/3d/skeleton_3d.cpp [hunk 2]
```diff
@@ -1097,6 +1101,14 @@ void Skeleton3D::_bind_methods() {
 	ClassDB::bind_method(D_METHOD("physical_bones_start_simulation", "bones"), &Skeleton3D::physical_bones_start_simulation_on, DEFVAL(Array()));
 	ClassDB::bind_method(D_METHOD("physical_bones_add_collision_exception", "exception"), &Skeleton3D::physical_bones_add_collision_exception);
 	ClassDB::bind_method(D_METHOD("physical_bones_remove_collision_exception", "exception"), &Skeleton3D::physical_bones_remove_collision_exception);
+
+	ADD_GROUP("Deprecated", "");
+	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "animate_physical_bones"), "set_animate_physical_bones", "get_animate_physical_bones");
```
Comment (raulsntos) [inline scene/3d/skeleton_3d.cpp:1106]: Would it be better to hide this property from the inspector? I only need it to be exposed to scripting to prevent breaking binary compatibility.

```suggestion
	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "animate_physical_bones", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_NO_EDITOR), "set_animate_physical_bones", "get_animate_physical_bones");
```

File: scene/3d/skeleton_3d.cpp (hunk 1 above)
Comment (TokageItLab) [reply scene/3d/skeleton_3d.cpp:1111]: Since there is no compatibility for it, it may need to return an invalid value such as `-1`.

File: scene/3d/skeleton_3d.cpp (hunk 2 above)
Comment (TokageItLab) [reply scene/3d/skeleton_3d.cpp:1106]: For compatibility with past projects, I think it is fine to have this show in the editor. Since some initialization process changes were included in this PR to make this public, so I believe it works without any problem.

File: scene/3d/skeleton_3d.cpp (hunk 1 above)
Comment (raulsntos) [reply scene/3d/skeleton_3d.cpp]: :thinking: I see, not sure how disruptive that is compared to removing the signal. If this is going to break users anyway then maybe it's not worth adding it back. I feel like I'm not familiar enough with this area to make this decision.

Comment (TokageItLab) [reply scene/3d/skeleton_3d.cpp]: While it is possible to actually make changes to a particular bone only once per frame, it would result in a quite a bit of performance loss as quaternion comparisons would need to be made for all bones; More specifically, the pose of the previous frame should be recorded and compared with the skeleton_updated signal. However, this should be done on the user side, since firing the signal for a particular bone will cause comparisons of other bones that do not need to be detected,

I have written lightly about the reasons for returning `-1` in the documentation, but I think this signal should be removed IMO.

**Comment by TokageItLab** [comment]
https://github.com/godotengine/godot/pull/94291#discussion_r1677021851

As the discussion, we cannot re-add a compatible signal that is not hazardous and has no performance problems, so `bone_pose_changed` signal should be eliminated.

**Review by raulsntos — APPROVED** [review]
The reasoning for not re-adding `bone_pose_changed` makes sense to me, hopefully it won't be too disruptive. I'll make a note to document the change in https://github.com/godotengine/godot-docs/pull/9250.

**Comment by akien-mga** [comment]
Thanks!
