### PR TITLE
Editor: Fix documentation for built-in scripts

### LINKED ISSUE #94338: @export script variables do not display tooltips when they are in built in script of node.
### Tested versions

v4.3.beta2.official [b75f0485b]

### System information

Linux Kubuntu 23.04 KDE Plasma Version: 5.27.4 KDE Frameworks Version: 5.104.0 Qt Version: 5.15.8

### Issue description

@export variable tooltips will not display if the script they are in is internal to a node.
image

### Steps to reproduce

Create a new 2D scene e.g. Control
Create a built-in/internal script for Control.

Add the following code and save:

```gdscript
extends Control

## Here should be a tooltip
@export var maximum_speed:int=100
```

After save click in the inspetor variable and hover over `maximum_speed`. Notice no tooltip shows up.

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by dalexeev**
Fixes the following bugs:

* Fixes #94338.

### 1. Standard tooltip is displayed instead of doc tooltip

I couldn't reproduce this, but it is apparently caused by the check:

https://github.com/godotengine/godot/blob/b947c53ddc08d4314b2ce70ca1bc2adb37b83c37/editor/connections_dialog.cpp#L875-L879

https://github.com/godotengine/godot/blob/b947c53ddc08d4314b2ce70ca1bc2adb37b83c37/editor/connections_dialog.cpp#L1520

### 2. Doc tooltip is empty for built-in classes and their members

This is because the Script Editor handles editing/saving external and built-in scripts inconsistently. As a result, `Script.reload()` was never called for built-in scripts (this method causes documentation to be regenerated in GDScript).

I'm not familiar with the Script Editor, so I tried to make minimal changes. I'm not sure about this part, please review and test carefully.

#### 2.1. Documentation missing for built-in scripts

This is the real reason why tooltips didn't work. This fix may be inconvenient for some people, but we cannot make tooltips work without registering the built-in scripts documentation globally. Instead, we might add filters in the future (see godotengine/godot-proposals#4285).

After the fix:

### 3. EditorHelp does not handle `::` in class names correctly

Added parsing instead of `get_slice(":", index)`.

### CODE REVIEW

**Comment by KoBeWi** [comment]
Does this allow for built-in script documentation? I listed it as a limitation #55287, so resolving it would be nice.

**Comment by KoBeWi** [comment]
I tested that it works, but the documentation is lost upon editor restart. If the page is opened on launch, it's empty:
image
You need to save the script/scene while the script is open in the script editor to regenerate the doc.

Though it's fine like that if we don't have doc cache for scripts. It's unreasonable to generate docs for every built-in script in the project. But it would be nice if at least it didn't require saving after opening a scene.

**Comment by dalexeev** [comment]
> I tested that it works, but the documentation is lost upon editor restart.

See:
* #72406
* #86577

**Comment by dalexeev** [comment]
> I tested that it works, but the documentation is lost upon editor restart.

Looks like #95821 didn't fix this automatically for built-in scripts. @anvilfolk Could you please help me fix this?

**Comment by anvilfolk** [comment]
I don't know a ton about built-in scripts, since I've never used them! It sounds like we need to add their docs to the script doc cache - does that sound right?

**Comment by dalexeev** [comment]
Yes, that's right. As far as I understand, built-in scripts are not tracked in the doc cache now.

**Comment by anvilfolk** [comment]
The script doc cache system iterates through all the docs available in memory, then writes them into a cache file on editor close. That cache is read on editor start. So I see a few scenarios.
1. Built-in script docs are not generated when script cache is force-regenerated. The force-regenerating process iterates through _script files_, but I assume builtin scripts are directly in something like scene files, which we don't iterate over/force-reload to generate docs.
2. Either built-in docs are stored elsewhere and not iterated on when saving the cache, or
3. When saving the script doc cache, we filter out non-script docs, but this could be excluding built-in docs, or
4. When loading the script doc cache, we filter out built-in docs if their paths are not found (I think this is happening but can't remember)

Problems 2-4 should be easy to fix, if they're issues at all. I think the toughest to solve is 1, since it could require iterating through every single file that may have built-in scripts, and loading them? We're already worried about the performance of force-reloading every script file, let alone every scene file! Unless there's some place where we track which files have built-in scripts?

**Comment by dalexeev** [comment]
Looks like it works now, but I'm worried about performance.

File: editor/editor_file_system.cpp [hunk 1]
```diff
@@ -2195,6 +2195,29 @@ void EditorFileSystem::_update_script_documentation() {
 			continue;
 		}
 
+		if (path.ends_with(".tscn")) {
```
Comment (anvilfolk) [inline editor/editor_file_system.cpp:2198]: A few thoughts.
1. Aren't there other types of files that can have built-in scripts, like maybe resources (.tres) or binary scenes (.scn)?
2. It looks like the .tscn files are added to `update_script_paths_documentation` when edited from the script editor. Is that it?

If you close the editor, and copy a .tscn with a built-in script file into the project, do the docs show up in Search Help with this PR? I I suspect they don't, because of point 2.

If that's the case, we might want to consider making a conscious decision to avoid documentation for built-in scripts entirely because of performance concerns. If the script doc cache is missing, we need to generate it on editor start. Right now we force-compile every .gd script. If .tscn or even .tres files may have built-in scripts, we'd need to force-load them as well, which is almost equivalent to loading up the entire project in one go.

I think our choice is between:
a. Accept an inconsistent cache, where only built-in scripts that were manually saved at some point are kept in the cache.
b. Ignore built-in scripts for script doc cache purposes, unfortunately making built-in scripts second class citizens.

Comment (KoBeWi) [reply editor/editor_file_system.cpp:2198]: > Aren't there other types of files that can have built-in scripts, like maybe resources (.tres) or binary scenes (.scn)?

Yes.

a. It's fine. Built-in scripts are saved with the scene, which can happen even without opening the script, so the documentation will be re-generated often enough.
b. That's fine too, however I'd make the tooltip say explicitly that built-in scripts don't support documentation.

I'd go with a. if it doesn't worsen the performance (does saving the scene regenerate the docs for every script every time?). b. is not terrible; built-in scripts already have many known limitations, because making them work on par with regular scripts is just not feasible.

File: editor/editor_file_system.cpp [hunk 2]
```diff
@@ -1385,7 +1385,7 @@ void EditorFileSystem::_process_file_system(const ScannedDirectory *p_scan_dir,
 void EditorFileSystem::_process_removed_files(const HashSet<String> &p_processed_files) {
 	for (const KeyValue<String, EditorFileSystem::FileCache> &kv : file_cache) {
 		if (!p_processed_files.has(kv.key)) {
-			if (ClassDB::is_parent_class(kv.value.type, SNAME("Script"))) {
+			if (ClassDB::is_parent_class(kv.value.type, SNAME("Script")) || ClassDB::is_parent_class(kv.value.type, SNAME("PackedScene"))) {
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:1388]: The comment below should be updated I think.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
