### PR TITLE
Change the resource path before `update_files()`

### LINKED ISSUE #117211: FileSystem, reorder script, error another resource is loaded from path
### Tested versions

Reproduced in:
v4.7.dev2.official [778cf54da]
v4.6.1.stable.official [14d19694e]

### System information

Godot v4.7.dev2 - Windows 11 (build 26100) - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - GeForce GTX 550 Ti - Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz (4 threads) - 11.95 GiB memory

### Issue description

In the FileSystem panel, dragging a script to or or from a folder, shows the error message:

> ERROR: Another resource is loaded from path 'res://a/new_script.gd' (possible cyclic resource inclusion).

Reordering the script shows the error message every time.

The same error message is reported here:
Another resource is loaded from path (possible cyclic resource inclusion). #116551

But that issue describes having to create and remove an exported resource multiple times to cause the error.
> Check console output logs -- sometimes the error is difficult to reproduce.
After anywhere from 5 to 20 tries you should see the error.

### Steps to reproduce

- open the project: [error-when-reordering-script.zip](https://github.com/user-attachments/files/25822800/error-when-reordering-script.zip)
- in the filesystem panel
drag `new_script.gd` to the folder: `a`
- a dialog opens:
> Please Confirm...
Move 1 selected item to "res://a"?
- click: ok
- open the output panel

Issue:
The output panel shows:
>   ERROR: Another resource is loaded from path 'res://a/new_script.gd' (possible cyclic resource inclusion).

The same error appears when dragging the script from the folder `a` to `res://`
>  ERROR: Another resource is loaded from path 'res://new_script.gd' (possible cyclic resource inclusion).

Expected:
No error message when reordering a script.

### Minimal reproduction project (MRP)

[error-when-reordering-script.zip](https://github.com/user-attachments/files/25822800/error-when-reordering-script.zip)

It's just a new project with:
- a folder, named: a
- an empty script: new_script.gd

### PR DESCRIPTION
**Pull request by Rindbee**
Fix #117211.

### CODE REVIEW

**Review by dujanhung — APPROVED** [review]

File: editor/docks/filesystem_dock.cpp [hunk 1]
```diff
@@ -1620,18 +1620,6 @@ void FileSystemDock::_try_duplicate_item(const FileOrFolder &p_item, const Strin
 }
 
 void FileSystemDock::_update_resource_paths_after_move(const HashMap<String, String> &p_renames, const HashMap<String, ResourceUID::ID> &p_uids) const {
-	for (const KeyValue<String, String> &pair : p_renames) {
-		// Update UID path.
-		const String &old_path = pair.key;
-		const String &new_path = pair.value;
-
-		const HashMap<String, ResourceUID::ID>::ConstIterator I = p_uids.find(old_path);
```
Comment (KoBeWi) [inline editor/docks/filesystem_dock.cpp:1628]: `p_uids` is now unused.

The code works correctly though, so this just needs to be removed.

**Review by KoBeWi — APPROVED** [review]
