### PR TITLE
Fix transform calculations for drag-moving CanvasItems in editor

### LINKED ISSUE #82643: Sprite2D Position Drag Error When Parent Sprite2D is Rotated and Child Sprite2D scale is unlinked and Changed
### Godot version

4.1.1.stable

### System information

Windows 11

### Issue description

When using the select mode tool to change a child Sprite2D's position in the editor window, the sprite will move unexpectedly. The rotation of the parent sprite, when set to some number other than 0, and the child sprite, unlinked in scale, and set to a ratio other than 1:1 causes will cause this. The more drastic the ratio, such as 1:5 or 1:20, the more intense sprite moves in the unintended direction. 

The Child sprite should remain under the mouse cursor and move to the desired location regardless of parent node rotation or child node scale imbalance.

### Steps to reproduce

1. Open 2D scene editor
2. Create a Sprite2D Node
3. Add a texture for visualization
4. Add a child Sprite2D node to the 1st Sprite2D, and again add a texture
5. Rotate the parent node an arbitrary non-zero angle, 45 degrees works well
6. Unlink the child node's scale and change the node to a non 1:1 ratio. The more intense the ratio, the more noticeable
7. Using the editor window, drag the child Sprite using the select tool or the transform tool
8. Observe that the sprite no longer follows the mouse to its desired drag location.

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/12778348/Bug.zip)

### PR DESCRIPTION
**Pull request by kleonc**
Fixes #82643.

Lately these calculations were tweaked in #81735 but we must have tested only some simple cases. In https://github.com/godotengine/godot/pull/81735#discussion_r1327973174 I deduced the `drag_from`/`drag_to` are in the parent coordinate space, but I've deduced it only based on the new code in that PR (which seemed to work). This was a wrong a conclusion. Now I've properly taken a look at a bigger chunk of code and `drag_from`/`drag_to` seem to be in the Viewport's global canvas coordinate space (viewport space transformed by inverse of its `global_canvas_transform`). Updated the calculations accordingly, now things seem to work just fine.
(To be clear things were broken for "non-standard" transforms even before #81735.)

| Before | After |
|--------|--------|
|foegTIB6X3|o1aB4FdPB8|

### CODE REVIEW

**Comment by KoBeWi** [comment]
Found a case that's still broken:
godot windows editor dev x86_64_th8ckHVfi8
Both ancestor nodes are rotated and scaled non-uniformly (with different ratios).

**Comment by kleonc** [comment]
> Found a case that's still broken:

Ah, right, I've made the movement be locked to local X/Y axes, but:
- gizmo X axis matches local X axis (so X dragging should work fine as is),
- gizmo Y axis is not equivalent to the local Y axis, as it's forced to be perpendicular/orthogonal to the gizmo X axis.

Just skewing a single item is enough to see this discrepancy in action.

So what's desired here?:thinking: Keeping the gizmo axes perpendicular as is and just changing the Y drag to match the gizmo direction?

**Comment by KoBeWi** [comment]
> Keeping the gizmo axes perpendicular as is and just changing the Y drag to match the gizmo direction?

Yes, gizmos should always display in the same way. If they were transformed it would appear bugged.

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -2062,23 +2062,26 @@ bool CanvasItemEditor::_gui_input_move(const Ref<InputEvent> &p_event) {
...
 				previous_pos = _get_encompassing_rect_from_list(drag_selection).position;
 			}
 
 			Point2 drag_delta = drag_to - drag_from;
 			if (drag_selection.size() == 1 && (drag_type == DRAG_MOVE_X || drag_type == DRAG_MOVE_Y)) {
 				const CanvasItem *selected = drag_selection.front()->get();
-				drag_delta = selected->get_transform().affine_inverse().basis_xform(drag_delta);
+				Transform2D parent_xform = selected->get_global_transform_with_canvas() * selected->get_transform().affine_inverse();
+				Transform2D unscaled_transform = (transform * parent_xform * selected->_edit_get_transform()).orthonormalized();
+				Transform2D simple_xform = viewport->get_transform() * unscaled_transform;
```
Comment (kleonc) [inline editor/plugins/canvas_item_editor_plugin.cpp:2076]: Changed it so this transform is calculated just like in many different places in this file. The last part (`viewport->get_transform() *`) don't make much sense to me, something seems off. The `viewport` here is a `Control` and according to the docs in `_gui_input` the events should be relative to such control, so applying its own transform on top makes no sense. Maybe the docs lie, maybe here things are incorrect. For now leaving it calculated as in other places as it seems like a potential pandora box (changing it here, would require changes in 20 different places and so on). For potential another PR.

**Review by KoBeWi — APPROVED** [review]
Works correctly now.

**Comment by akien-mga** [comment]
Thanks!
