### PR TITLE
Fix incorrect check on importing project

### LINKED ISSUE #77831: "This directory already contains a Godot project" when inputting a valid path without trailing /
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 10

### Issue description

Inputting a project path without a trailing / results in a warning:

> This directory already contains a Godot project

image

It's not obvious that you need to add a trailing slash to fix.

Godot detected there's a project in this folder, so could it add the trailing slash for me? or accept paths without it?

### Steps to reproduce

1. Open Godot
2. Click Import
3. Type path to existing project. When you've typed the path (but without the trailing `/`), you'll see the error.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by AThousandShips**
Note: #77760 makes this impossible to test on some platforms, see there, reverting the cause helps verify this fix

(This problem also occurs on 3.x, have not tested if this can be cherry-picked)

* Fixes: #77831

### CODE REVIEW

**Review by RedworkDE — APPROVED** [review]
Tho it's more `improve` than `fix`, if the folder name ends with `.zip` it still breaks in the same way, and also selecting a project to import by typing into the text field instead of using the browse dialog seems pretty broken in general

**Comment by AThousandShips** [comment]
The check in this case is when the folder contains a project already (the path is invalid, or the directory contains a `project.godot` file), which breaks for this as that's valid if you're opening a folder, but if you're importing a zip the target folder shouldn't already have a project, unless I'm not understanding the import process here?

**Comment by AThousandShips** [comment]
That's true

**Comment by AThousandShips** [comment]
Got some ideas digging into some of the code, will test them later today probably, marking as draft until then

**Comment by AThousandShips** [comment]
Some improvements, it's still pretty inefficient and spaghetti, and if you point to a `project.godot` file it doesn't work still, but now it manages folders ending in `.zip`, and makes the install path appear and vanish when you change the import path

This needs a major cleaning but at least now it should work correctly, will clean up some of the code though

File: editor/project_manager.cpp [hunk 1]
```diff
@@ -281,6 +284,19 @@ void ProjectDialog::_path_text_changed(const String &p_path) {
 	}
 }
 
+void ProjectDialog::_path_text_changed(const String &p_path) {
+	Ref<DirAccess> d = DirAccess::create(DirAccess::ACCESS_FILESYSTEM);
+	String p = p_path;
+	if (mode == MODE_IMPORT && ((p.ends_with(".zip") && d->file_exists(p)) || (p.strip_edges().ends_with(".zip") && d->file_exists(p.strip_edges())))) {
```
Comment (idbrii) [inline editor/project_manager.cpp:290]: I'd suggest making a helper to simplify this code:

```
static bool is_zip_file(Ref<DirAccess>& d, String& path)
{
	return path.ends_with(".zip") && d->file_exists(path);
}
```

Then this check becomes more readable:
```
	if (mode == MODE_IMPORT
		&& (is_zip_file(d, p) || (is_zip_file(d, p.strip_edges()))))
	{
```

And the above `is_zip` init becomes simpler too.

File: editor/project_manager.cpp [hunk 2]
```diff
@@ -201,19 +204,19 @@ String ProjectDialog::_test_path() {
...
-				_set_message(TTR("Please choose a \"project.godot\" or \".zip\" file."), MESSAGE_ERROR);
+				_set_message(TTR("Please choose a project folder or a \".zip\" file."), MESSAGE_ERROR);
 				install_path_container->hide();
 				get_ok_button()->set_disabled(true);
 				return "";
 			}
 
-		} else if (valid_path.ends_with("zip")) {
+		} else if (is_zip) {
 			_set_message(TTR("This directory already contains a Godot project."), MESSAGE_ERROR, INSTALL_PATH);
```
Comment (idbrii) [inline editor/project_manager.cpp:220]: Suggest changing message to: "A zipped Godot project already exists at this location."

I read where is_zip is initialized as: not a directory, ends with ".zip", is a file. So the input path isn't a folder containing a zip, it's a path of an existing zip.

**Review by idbrii — APPROVED** [review]
Thanks for fixing this!

File: editor/project_manager.cpp (hunk 2 above)
Comment (AThousandShips) [reply editor/project_manager.cpp:220]: That isn't the case though, the case is that the path to install to already contains a project

File: editor/project_manager.cpp (hunk 1 above)
Comment (AThousandShips) [reply editor/project_manager.cpp:290]: Thank you for your suggestion

Comment (idbrii) [reply editor/project_manager.cpp:290]: You're right that it's not quite equivalent to the init code, but that code is wrong. Writing it like this would correctly handle leading spaces in the path:

```
	} else if (is_zip_file(d, project_path->get_text())) {
		valid_path = project_path->get_text();
		is_zip = true;
	} else if (is_zip_file(d, project_path->get_text().strip_edges())) {
		valid_path = project_path->get_text().strip_edges();
		is_zip = true;
	}
```

In the existing code, the case `else if (project_path->get_text().ends_with(".zip"))` will incorrectly entered for `  c:/therewerespaces.zip` which might be valid but has incorrect leading spaces. That would prevent it from entering the next case `else if (project_path->get_text().strip_edges().ends_with(".zip"))` which handles stripping non ASCII characters.

File: editor/project_manager.cpp [hunk 3]
```diff
@@ -107,21 +107,25 @@ void ProjectDialog::_set_message(const String &p_msg, MessageType p_type, InputT
...
-			valid_path = project_path->get_text();
-		}
-	} else if (project_path->get_text().strip_edges().ends_with(".zip")) {
-		if (d->file_exists(project_path->get_text().strip_edges())) {
-			valid_path = project_path->get_text().strip_edges();
-		}
+	bool is_zip = false;
+	if (d->change_dir(base_path) == OK) {
+		valid_path = base_path;
+	} else if (is_zip_file(d, base_path)) {
```
Comment (AThousandShips) [inline editor/project_manager.cpp:121]: Reordering here in the weird case where there's a file matching but not a directory, unsure if this will ever happen, but it can't hurt

File: editor/project_manager.cpp [hunk 4]
```diff
@@ -109,21 +109,25 @@ void ProjectDialog::_set_message(const String &p_msg, MessageType p_type, InputT
 	}
 }
 
+static bool is_zip_file(Ref<DirAccess> p_d, const String &p_path) {
+	return p_path.ends_with(".zip") && p_d->file_exists(p_path);
+}
+
 String ProjectDialog::_test_path() {
 	Ref<DirAccess> d = DirAccess::create(DirAccess::ACCESS_FILESYSTEM);
+	const String base_path = project_path->get_text();
```
Comment (akien-mga) [inline editor/project_manager.cpp:118]: Any reason we shouldn't `strip_edges()` here and not have to deal with doing the logic twice with and without stripping below?

Comment (AThousandShips) [reply editor/project_manager.cpp:118]: That's a good point, I think I just didn't think of it, will take a look

Comment (akien-mga) [reply editor/project_manager.cpp:112]: Right, on Linux I can have trailing and leading space:
```
$ file "  LICENSE.txt  " 
  LICENSE.txt  : ASCII text
```

**Review by akien-mga — APPROVED** [review]

**Comment by AThousandShips** [comment]
Thank you!
