### PR TITLE
Fix selection highlight not updating when selecting a hidden canvasitems

### LINKED ISSUE #111686: Incorrect selection highlight when selecting hidden CanvasItem
### Tested versions

- Reproducable: v4.6.dev.custom_build [1e9d0ff92], v4.0.stable.official [92bee43ad]

### System information

Godot v4.6.dev (1e9d0ff92) - Windows 11 (build 26100) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 32.0.15.5599) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 threads) - 15.76 GiB memory

### Issue description

Found while investigating #105564, but smaller MRP provided.

If currently selecting a canvas item in the tree dock then clicking on a canvas item with visibility toggled off that is listed below the current selection in the tree dock, then the selection highlight for the first selection remains when no selection should be shown. 

In the screen shot below, the selection is shown for the node "Visible 1" but only "Hidden" is selected.
Image

Bug does not occur if the positions in the tree dock are swapped. As in, first selecting a visible canvas item then selecting a non-visible canvas item listed above the first.
Bug also resolves itself if the cursor is moved into the scene viewport probably because that triggers a fresh redraw.

### Steps to reproduce

In the MRP:

1. Open the "hidden_selection" scene
2. Go into 2D mode
3. Click the node "Visible 1" in the scene tree dock
4. Click the node "Hidden" in the scene tree dock
5. Notice how the selection is still around "Visible 1" in the scene view

### Minimal reproduction project (MRP)

[select_mrp.zip](https://github.com/user-attachments/files/22933185/select_mrp.zip)

### PR DESCRIPTION
**Pull request by kevinlam508**
Fixes #111686

Adds a check to redraw to clear drawings for a previous visible selection if the current selection is not visible.

From what I could tell, all the calls to redraw the viewport that I could find do not trigger on `CanvasItem`s with visibility off. This normally makes sense since nothing is drawn when visibility is off, but this issue is that it's not clearing a previous drawing.

Order in tree mattered in the issue because it affects the order of add/remove.
If the new selection is below, remove of the old selection is done first, so selection thinks it's a single selection the whole time.
If the new selection is above, add of the new selection is done first, so the selection momentarily is treated like a multi-select until the remove, which triggered redraws associated with multi-select.

### CODE REVIEW

**Comment by kevinlam508** [comment]
I'm not sure why the unit tests step hung for that one check. Unit tests were fine for the other runs and I didn't change anything that affects unit tests.

**Comment by KoBeWi** [comment]
Does it have to be checked every frame? Can't it only happen on selection change?

**Comment by kevinlam508** [comment]
Good point. Moved the checks to `_selection_changed()`. Didn't use `_get_edited_canvas_items()` so it can early out with visible selections.

File: editor/scene/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -4497,6 +4497,32 @@ void CanvasItemEditor::_selection_changed() {
 		temp_pivot = Vector2(Math::INF, Math::INF);
 		viewport->queue_redraw();
 	}
+
+	// Check to redraw to clear anything drawn from visible selections if no selections are visible.
+	bool has_visible = false;
+	for (const KeyValue<Node *, Object *> &E : editor_selection->get_selection()) {
+		CanvasItem *ci = Object::cast_to<CanvasItem>(E.key);
```
Comment (KoBeWi) [inline editor/scene/canvas_item_editor_plugin.cpp]:
```suggestion
	for (const KeyValue<ObjectID, Object *> &E : editor_selection->get_selection()) {
		CanvasItem *ci = ObjectDB::get_instance<CanvasItem>(E.key);
```

**Review by KoBeWi — APPROVED** [review]
Needs rebase.

File: editor/scene/canvas_item_editor_plugin.cpp (hunk 1 above)
Comment (kevinlam508) [reply editor/scene/canvas_item_editor_plugin.cpp]: Rebased and updated that snippet
