### PR TITLE
Fix cursor stucking in resize shape

### LINKED ISSUE #55786: Cursor is sometimes stuck in resize shape
### Godot version

04cc06b

### System information

W10

### Issue description

lH7rWFfJbA
Happens randomly with any dialog. It's especially jarring when you close a dialog and your cursor changes for whatever reason.

### Steps to reproduce

1. Open any non-maximized window/dialog
2. Move cursor to the border so it changes to "resize" shape
3. When you move cursor inside the dialog, it sometimes gets stuck in this shape

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Chaosus**
Fix #55786

### CODE REVIEW

File: platform/windows/display_server_windows.cpp [hunk 1]
```diff
@@ -3126,14 +3128,6 @@ DisplayServer::WindowID DisplayServerWindows::_create_window(WindowMode p_mode,
 #endif
 
 		RegisterTouchWindow(wd.hWnd, 0);
-
-		TRACKMOUSEEVENT tme;
-		tme.cbSize = sizeof(TRACKMOUSEEVENT);
-		tme.dwFlags = TME_LEAVE;
-		tme.hwndTrack = wd.hWnd;
-		tme.dwHoverTime = HOVER_DEFAULT;
-		TrackMouseEvent(&tme);
```
Comment (akien-mga) [inline platform/windows/display_server_windows.cpp:3135]: Just to be sure, this removal (without replacing by `track_mouse_leave_event`) was intentional?

Comment (Chaosus) [reply platform/windows/display_server_windows.cpp:3135]: I think it's useless to call it twice since it is called at the WndProc/WM_ACTIVATE event now

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
