### PR TITLE
Fixed broken root motion calculation in internal process of `AnimationBlendTree` such as `NodeOneShot`

### LINKED ISSUE #4418: Allow to choose whether or not to calculate root motion when seeking
### Describe the project you are working on

3D Character Game

### Describe the problem or limitation you are having in your project

Root motion predicts the previous animation position based on delta and calculates the root transform. Currently it is always calculated correctly, even during seek. This has side effects.

For example, if the root bone has a different transform at the beginning and at the end in animation, NodeOneShot will set the animation back to 0 with seeking when it fires (you may not notice unless the FadeIn value is 0), meaning that there will be a rapid rollback animation at the time of the firing. This also gets in the way of looping by seek.

https://user-images.githubusercontent.com/61938263/163900856-4bf7ee8b-00f8-4dfa-9541-9d6f754e20d7.mov

You can see that the grid is moving rapidly when the timing of OneShot fired.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It has already caused serious bugs/limitations with NodeOneShot and others. This fix would allow users to control animation without having to provide a special case for root motion, such as when synchronizing animation at an arbitrary speed from a script using Seek. It will also help it when implementing https://github.com/godotengine/godot/pull/57959.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

After fixed:

https://user-images.githubusercontent.com/61938263/163900904-34f6e897-8159-406d-8e33-3d72c6ca034b.mov

We need to add an implementation that allows passing parameters such as `bool::seek_root` or `enum SEEK_MODE` as arguments to the blend process.

Or it could be implemented in such a way that only rollbacks are avoided. It is simple, but perhaps the root motion is not calculated correctly when an animation that is playing in a playback-forward is seeked in a playback-backward.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, animation process is core.

### Is there a reason why this should be core and not an add-on in the asset library?

Most people who use root motion need this.

### LINKED ISSUE #40294: Root motion produces inaccurate transform
**Godot version:**

3.2.2.stable.custom_build.0fe60f842

**OS/device including version:**

Linux 5.7.7-arch1-1

**Issue description:**

I have an animation that rotates my root bone by 90 degrees.
When animated directly by the `AnimationPlayer` it rotates the object exactly 90degrees.
When I add it to an `AnimationTree` and play the animation once via a `OneShot` or `Transition` node, the total rotation is slightly less than 90 degrees.
You can see this easily if you add a `RootMotionView`.

**Steps to reproduce:**

1. Open example project
2. Play the "Spin" animation from the `AnimationPlayer`
3. Observe the cube rotate exactly 90 degrees
4. Activate the `OneShot` in the `AnimationTree`
5. Observe the cube rotate less than 90 degrees

Note that the root motion view no longer lines up with the grid after one rotation:

**Minimal reproduction project:**

[example.zip](https://github.com/godotengine/godot/files/4907331/example.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
Fixed #40294.

The root motion is calculated by subtracting delta from the current time, but if the current time is start or end an error occurred because the clamped current time was passed. This is regression by #53819 (sorry it's my mistake). In addition, make NodeOneShot not fade by default, because it would be confusing to have NodeOneShot fade by default, which would change the value of the root motion.

----

Fixed https://github.com/godotengine/godot-proposals/issues/4418.

In the case of an implicit seek performed by an internal process such as NodeOneShot, the root motion should not be calculated. Conversely, if the user explicitly seeks with NodeSeek, the root motion should be calculated.

If NodeSeek or NodePhase(#57959) supports loops, the `p_seek_root` may need to be an int (enum) instead of a bool, but for now, this PR fixes the unusable broken calculation of the root motion for NodeOneShot.

Before:

https://user-images.githubusercontent.com/61938263/166854064-73ab85d4-7f4e-4a62-a2b5-d5729c2db7d9.mov

After:

https://user-images.githubusercontent.com/61938263/166853450-30eea5c4-b067-433e-b988-8032b9919b38.mov

----

In addition, this includes small fix of the enum notation in Animation.
`Animation::LoopMode::LOOP_LINEAR` -> `Animation::LOOP_LINEAR`

### CODE REVIEW

**Comment by TokageItLab** [comment]
I found some errors and fixed them additionally.

**Comment by TokageItLab** [comment]
I leave a few comments to make the review easier.

File: scene/animation/animation_blend_tree.cpp [hunk 1]
```diff
@@ -116,22 +116,24 @@ double AnimationNodeAnimation::process(double p_time, bool p_seek) {
...
-			if (anim_size) {
+		if (anim->get_loop_mode() == Animation::LOOP_LINEAR) {
+			if (!Math::is_zero_approx(anim_size)) {
 				time = Math::fposmod(time, anim_size);
 			}
 		} else if (time < 0) {
+			step += time;
 			time = 0;
 		} else if (time > anim_size) {
+			step += anim_size - time;
```
Comment (TokageItLab) [inline scene/animation/animation_blend_tree.cpp:127]: Adjusted by the overflow value.

File: scene/animation/animation_tree.cpp [hunk 2]
```diff
@@ -1057,7 +1058,7 @@ void AnimationTree::_process_graph(double p_delta) {
 									}
 									a->position_track_interpolate(i, 0, &loc[1]);
 									t->loc += (loc[1] - loc[0]) * blend;
-									prev_time = 0;
+									prev_time = (double)a->get_length();
```
Comment (TokageItLab) [inline scene/animation/animation_tree.cpp:1061]: Fixed the simple bug...

File: scene/animation/animation_tree.cpp [hunk 3]
```diff
@@ -995,7 +996,7 @@ void AnimationTree::_process_graph(double p_delta) {
 					case Animation::TYPE_POSITION_3D: {
 #ifndef _3D_DISABLED
 						TrackCacheTransform *t = static_cast<TrackCacheTransform *>(track);
-						if (track->root_motion) {
+						if (track->root_motion && calc_root) {
```
Comment (TokageItLab) [inline scene/animation/animation_tree.cpp:999]: AnimationTree performs a seek to change the playback time, but should be able to choose whether to calculate the root motion or not.

File: scene/animation/animation_tree.cpp [hunk 4]
```diff
@@ -967,6 +967,7 @@ void AnimationTree::_process_graph(double p_delta) {
 			int pingponged = as.pingponged;
 #ifndef _3D_DISABLED
 			bool backward = signbit(delta);
+			bool calc_root = !seeked || as.seek_root;
```
Comment (TokageItLab) [inline scene/animation/animation_tree.cpp:970]: AnimationTree performs a seek to change the playback time, but should be able to choose whether to calculate the root motion or not.

**Comment by TokageItLab** [comment]
I left a few comments to make the review easier. The other parts of these sections are argument rewrites and style corrections.

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Valeryn4** [comment]
#58061 - not fixed
the problem is not fixed. The necessary global transformation of the root-bone.

problem actual in 4.0, last version!
rotation no sync!
see video: https://youtu.be/Z78KnTzFswg

im use:
````
var tr2: Transform3D = _animation_tree.get_root_motion_transform() 
_core.transform.basis *= tr2.basis.orthonormalized()
```

i rotate the model using root_motion_transform.
But I can't get the absolute transformation of the main bone, which causes the animation to shift over time.

**Comment by TokageItLab** [comment]
@Valeryn4 I comennted in https://github.com/godotengine/godot/pull/29458#issuecomment-1146840887.
