### PR TITLE
Fix for webgl reflection probes

### LINKED ISSUE #38571: Web Build : Reflection probes not working correctly
**Godot version:**
3.2.1

**OS/device including version:**
Web Build + GLES2
**Issue description:**
Reflection probes not working correctly in web builds, see the image.

**Steps to reproduce:**

**Minimal reproduction project:**
https://www.dropbox.com/s/ndg1i75yknqfhus/minifix.zip?dl=0

image

### PR DESCRIPTION
**Pull request by WeaselShoppe**
Render buffer storage was being configured with wrong format on WebGL leading to reflection probes failing.

Fix #38571

### CODE REVIEW

**Comment by Calinou** [comment]
It might be worth checking whether this should also be fixed in GLES3.

**Comment by WeaselShoppe** [comment]
> Thanks for opening a pull request!
> 
> If you have spare time, it might be worth checking whether this should also be fixed in GLES3 (WebGL 2.0).

No problem. I will check/test reflection probes in GLES3.0/WebGL 2.0 as well. For right now I am trying to figure out what I did to make clang-format angry...

File: drivers/gles2/rasterizer_storage_gles2.cpp [hunk 1]
```diff
@@ -6133,7 +6140,9 @@ void RasterizerStorageGLES2::initialize() {
 			glBindTexture(GL_TEXTURE_2D, 0);
 			glDeleteTextures(1, &depth);
 		}
+#ifndef JAVASCRIPT_ENABLED
```
Comment (akien-mga) [inline drivers/gles2/rasterizer_storage_gles2.cpp:6143]: That's not the closing bracket corresponding to `if (status != GL_FRAMEBUFFER_COMPLETE) {`.

Comment (WeaselShoppe) [reply drivers/gles2/rasterizer_storage_gles2.cpp:6142]: Whoops. That's embarrassing. Fixed now.

Comment (WeaselShoppe) [reply drivers/gles2/rasterizer_storage_gles2.cpp:6142]: Discovered another problem with this PR but think I fixed it (glTexImage2D doesn't accept GL_DEPTH_COMPONENT(X) enums on webgl 1.0). Don't want to waste anyone's time while I verify though. Should I convert to draft while I test?

Comment (WeaselShoppe) [reply drivers/gles2/rasterizer_storage_gles2.cpp]: Amended PR with what I think are final fixes. Tested on

-Windows Desktop
-Chrome Windows
-Chrome Android
-Safari IOS

No errors in dev console on Chrome Windows.

File: drivers/gles2/rasterizer_storage_gles2.cpp [hunk 2]
```diff
@@ -6069,6 +6069,13 @@ void RasterizerStorageGLES2::initialize() {
 	config.rgtc_supported = config.extensions.has("GL_EXT_texture_compression_rgtc") || config.extensions.has("GL_ARB_texture_compression_rgtc") || config.extensions.has("EXT_texture_compression_rgtc");
 	config.bptc_supported = config.extensions.has("GL_ARB_texture_compression_bptc") || config.extensions.has("EXT_texture_compression_bptc");
 
+// Skip depth texture check for webgl 1.0
+#ifdef JAVASCRIPT_ENABLED
+	config.depth_internalformat = GL_DEPTH_COMPONENT16;
```
Comment (clayjohn) [inline drivers/gles2/rasterizer_storage_gles2.cpp:6074]: Please look at how these variables are defined earlier in ``initialize()``.

You are overwriting variables that have valid inputs. For example, ``support_depth_texture`` is always set to false, even though it works when the browser has the ``WEBGL_depth_texture`` extension. 

Further ``depth_type`` gets set correctly in the branch that you have compiled out. 

Im guessing that the correct fix will be less intrusive. Have you tried just adding a condition for JAVASCRIPT_ENABLED at line 6109-6114

Comment (WeaselShoppe) [reply drivers/gles2/rasterizer_storage_gles2.cpp:6074]: So something like this?

```
#if defined(GLES_OVER_GL) || defined(JAVASCRIPT_ENABLED)
			config.depth_internalformat = GL_DEPTH_COMPONENT16;
#else
			// OES_depth_texture extension only specifies GL_DEPTH_COMPONENT.
			config.depth_internalformat = GL_DEPTH_COMPONENT;
#endif
```

If so, that branch never gets executed on my system. Inserting some debug prints shows that...

```
		if (status != GL_FRAMEBUFFER_COMPLETE) {
```
Evaluates to non-zero/true. (status is 0x8CD5/GL_FRAMEBUFFER_COMPLETE)

image
image

Comment (WeaselShoppe) [reply drivers/gles2/rasterizer_storage_gles2.cpp:6074]: So starting from scratch with this I came with something that might be better...

https://github.com/WeaselShoppe/godot/commit/5ea36e836d0df0dd72b891a6d678e3809a6818ee

The issues that I understand:

-config->depth_internalformat should probably be set to GL_DEPTH_COMPONENT16 at the beginning of RasterizerStorageGLES2::initialize if JAVASCRIPT_ENABLED

-config->depth_internalformat is passed to glTexImage2D in several places in the GLES2 rendering code. If this is equal to GL_DEPTH_COMPONENT16 that will cause errors in WebGL since GL_DEPTH_COMPONENT16 is not a valid parameter to pass.

The branch I pushed just now should solve both problems. no rendering errors and no warnings in console. Seems minimally intrusive too. Not sure if this is right approach though?

image

Comment (clayjohn) [reply drivers/gles2/rasterizer_storage_gles2.cpp:6074]: Why not just replace line 5970 with
```
#ifdef JAVASCRIPT_ENABLED
    config.depth_internalformat = GL_DEPTH_COMPONENT16;
#else
    config.depth_internalformat = GL_DEPTH_COMPONENT;
#endif
```

Comment (WeaselShoppe) [reply drivers/gles2/rasterizer_storage_gles2.cpp:6074]: If we do that, it will cause failures elsewhere in the code where config.depth_internalformat is passed to glTexImage2D (GL_DEPTH_COMPONENT16 is not a valid format for this on WebGL1.0)

I have a simple fix here that should be less intrusive. Does this look like it might be more appropriate?
https://github.com/WeaselShoppe/godot/commit/5ea36e836d0df0dd72b891a6d678e3809a6818ee

Comment (clayjohn) [reply drivers/gles2/rasterizer_storage_gles2.cpp:6074]: Yes, I looked at your branch when you posted it before. You are replacing the config variable with a global macro in two different files. The problem with a hardcoded approach like this is that it is hard to maintain. When coming up with a solution it helps to write your solution as if the next person who works on this code will be learning it for the first time. In that case it is much more preferable for them to be able to look through ``initialize`` and understand how the config variables are determined. Rather than having the config determined for some platforms in ``initialize`` and in a global macro for others.

**Comment by clayjohn** [comment]
Looking into the code a little deeper, it appears that the issue is actually with a few calls to ``glRenderbufferStorage`` that are accidentally using ``config.depth_internalformat`` instead of ``config.depth_buffer_internalformat``.

**Comment by WeaselShoppe** [comment]
> Looking into the code a little deeper, it appears that the issue is actually with a few calls to `glRenderbufferStorage` that are accidentally using `config.depth_internalformat` instead of `config.depth_buffer_internalformat`.
> 
> textures should use `depth_internalformat` while storage buffers should use `depth_buffer_internalformat`

ah. this makes a lot of sense. is depth_buffer_internalformat correctly set to GL_DEPTH_COMPONENT16 when running in WebGL 1.0 context?

**Comment by clayjohn** [comment]
@WeaselShoppe Yep :)

https://github.com/godotengine/godot/blob/7595228794f180c5e9a8cac5859abca719ed7aac/drivers/gles2/rasterizer_storage_gles2.cpp#L5987-L5994

**Comment by WeaselShoppe** [comment]
> @WeaselShoppe Yep :)
> 
> https://github.com/godotengine/godot/blob/7595228794f180c5e9a8cac5859abca719ed7aac/drivers/gles2/rasterizer_storage_gles2.cpp#L5987-L5994

Awesome. Should I just revise this PR by reverting back to 3.2 HEAD, and fixing the calls to glRenderbufferStorage? (after testing on my devices of course).

**Comment by clayjohn** [comment]
> Awesome. Should I just revise this PR by reverting back to 3.2 HEAD, and fixing the calls to glRenderbufferStorage? (after testing on my devices of course)

Yes please :)

**Comment by clayjohn** [comment]
Looks good. You are going to need to squash your commits now so that it is just a single commit. How to do so is explained here https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html

**Review by clayjohn — APPROVED** [review]
Looks great now! Thank you and good job!

**Comment by WeaselShoppe** [comment]
> Looks great now! Thank you and good job!

No problem. Thanks for all the help/guidance!

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
