### PR TITLE
[Windows] Read Wacom config to check if Windows Ink is disabled and auto switch to WinTab.

### LINKED ISSUE #102155: Most editor buttons cannot be used with a graphic tablet if `winink` driver is selected (new default in Godot) but Windows drivers have "Use Windows Ink" unchecked
### Tested versions

- broken in 4.4beta 1
- broken in 4.4dev3
- works in 4.3 stable

### System information

Godot v4.4.beta1 - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 (NVIDIA; 32.0.15.6094) - AMD Ryzen 5 3600 6-Core Processor (12 threads) + Wacom Tablet

### Issue description

Most buttons can no longer be pressed using my tablet pen. This also affects buttons in exported products. I only know of this because a user informed us that this broke in the newest material maker 1.4 alphas. Then I noticed the same is true in the godot editor, but was working fine in previous versions.

This affects most editor buttons, though there are some exceptions which I assume have some kind of different input code (e.g the menus and the little three dots on tab bars work as well). But any traditional buttons, toggles (e.g. in the inspector), the MainScreen buttons at the top, etc. all cannot be clicked anymore.

### Steps to reproduce

Open the editor, connect a graphic tablet, try clicking a button.

### Minimal reproduction project (MRP)

Godot Editor

### LINKED ISSUE #102740: Pen tablet: Pressure reporting breaks when "Use Windows Ink" is unselected in Wacom driver, unless driver in project settings is changed to "wintab"
### Tested versions

Reproducible in 4.4-beta3, 4.3-stable

### System information

Windows

### Issue description

Turning off the "Use Windows Ink" option in the Wacom driver breaks pressure support in Godot with default settings. Godot always defaults to "winink" driver in the project settings, but this silently breaks when this option is unset.

I should note that this configuration is not that niche, since it is easily reachable in the Wacom driver GUI and is recommended by at least 1 popular youtube video.

This hasn't caused an issue for me in either Krita or Blender.

### Steps to reproduce

1. Using a wacom driver, turn off "Use Windows Ink" in driver settings.
2. Print `InputEventMouseMotion.pressure` and note values are either 0 or 1.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/102155
Fixes https://github.com/godotengine/godot/issues/102740

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: platform/windows/display_server_windows.cpp [hunk 1]
```diff
@@ -6669,6 +6684,26 @@ DisplayServerWindows::DisplayServerWindows(const String &p_rendering_driver, Win
...
+		XMLParser parser;
+		if (parser.open(wacom_cfg) == OK) {
+			while (parser.read() == OK) {
+				if (parser.get_node_type() != XMLParser::NODE_ELEMENT) {
+					continue;
+				}
+				if (parser.get_node_name() == "WinUseInk") {
+					parser.read();
+					if (parser.get_node_type() == XMLParser::NODE_TEXT) {
+						winink_disabled = (parser.get_node_data().to_lower().strip_edges() != "true");
```
Comment (AThousandShips) [inline platform/windows/display_server_windows.cpp:6698]:
```suggestion
		Ref<XMLParser> parser;
		parser.instantiate();
		if (parser->open(wacom_cfg) == OK) {
			while (parser->read() == OK) {
				if (parser->get_node_type() != XMLParser::NODE_ELEMENT) {
					continue;
				}
				if (parser->get_node_name() == "WinUseInk") {
					parser->read();
					if (parser->get_node_type() == XMLParser::NODE_TEXT) {
						winink_disabled = (parser->get_node_data().to_lower().strip_edges() != "true");
```

**Review by AThousandShips — APPROVED** [review]

File: platform/windows/display_server_windows.cpp (hunk 1 above)
Comment (bruvzg) [reply platform/windows/display_server_windows.cpp:6698]: It's a local variable, what's the point of having it refcounted?

Comment (AThousandShips) [reply platform/windows/display_server_windows.cpp:6698]: To ensure all memory management is correct, it's a `RefCounted` type

Comment (bruvzg) [reply platform/windows/display_server_windows.cpp:6698]: It will be freed the same way as soon as it's out of scope (at the end of `if file exist` block), `RefCounted` only relevant when either multiple references exist or it's accessed via Variant calls.

Comment (AThousandShips) [reply platform/windows/display_server_windows.cpp:6698]: Are we assuming that `postinitialize_handler` is completely unnecessary?

Comment (bruvzg) [reply platform/windows/display_server_windows.cpp:6698]: In this case, no, it's not doing anything relevant (or instance specific), but I guess it is a valid concern in case it will do something in the future.

**Comment by Jordyfel** [comment]
Tested, this fixes the issue for me

**Review by Calinou — APPROVED** [review]
Code looks good to me.

**Comment by Repiteo** [comment]
Thanks!
