### PR TITLE
C# Truncate instead of round in Vector2/3/4 to Vector2I/3I/4I conversion

### LINKED ISSUE #75470: C# Vector2I inconsistent rounding behavior
### Godot version

v4.0.1.stable.mono.official

### System information

Windows 10

### Issue description

In C# Vector2I conversion produces inconsistent rounding behavior. `GD.PrintS((Vector2I)(new Vector2(0.5f, 0.51f)), (int)(0.5f), (int)(0.51f));` will print `(0, 1) 0 0` (note that y component is rounded to 1). On the other hand, such conversion in GDScript produces consistent result, both `print(Vector2i(0.5, 0.51))` and `print(Vector2i(Vector2(0.5, 0.51)))` will output `(0, 0)`.
It looks like Vector2I conversion in C# uses Round() instead of Truncate() (taking into account negative values).

### Steps to reproduce

Run following codes in C#:
`GD.PrintS((Vector2I)(new Vector2(0.5f, 0.51f)), (int)(0.5f), (int)(0.51f));` 
and GDScript:
`print(Vector2i(0.5, 0.51))` and `print(Vector2i(Vector2(0.5, 0.51)))`
then compare results.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by kleonc**
Makes C# Vector2/3/4 to Vector2I/3I/4I conversions behave consistently with the core, i.e. now they are performed by truncating to ins instead of rounding to ints like before. Also improved the relevant docs.

Fixes #75470.

### CODE REVIEW

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Vector2I.cs [hunk 1]
```diff
@@ -504,15 +504,15 @@ public Vector2I(int x, int y)
         }
 
         /// <summary>
-        /// Converts a <see cref="Vector2"/> to a <see cref="Vector2I"/>.
+        /// Converts a <see cref="Vector2"/> to a <see cref="Vector2I"/> by truncating
+        /// components' fractional parts (rounding towards zero). For a different
+        /// behavior consider passing the result of <see cref="Vector2.Ceil"/>,
+        /// <see cref="Vector2.Floor"/> or <see cref="Vector2.Round"/> to this constructor instead.
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Vector2I.cs:510]: This isn't a constructor, it's a conversion operator. I guess this is just a copy-paste mistake, the other types have the same issue.

**Review by raulsntos — CHANGES_REQUESTED** [review]
LGTM, just a nit pick about the C# documentation.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Vector2I.cs (hunk 1 above)
Comment (kleonc) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Vector2I.cs]: > I guess this is just a copy-paste mistake

Yeah, I've missed that part. Corrected!

**Review by raulsntos — APPROVED** [review]

**Review by neikeq — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.3.
