### PR TITLE
bug with Tween.is_active, fixes #39760

### LINKED ISSUE #39760: Tween.is_active() always true after tween.stop() and then tween.start()
**Godot version:3.2**

**OS/device including version: Several OS (Win10 / MacOS)**

**Issue description:**
Tween never gets finished when tween.start() is called after tween.stop() without calling tween.resume()

**Steps to reproduce:**
Start() a tween.
is_active() become true (normal)
Stop() the tween before it finished.
is_active() become false (normal)
Start() the tween again. 
is_active() become true (normal)

but in this case when the tween is over, it never switch is_active() to false.
Completed events are not fired. 

**Minimal reproduction project:**
[tween_bug.zip](https://github.com/godotengine/godot/files/4815036/tween_bug.zip)

### PR DESCRIPTION
**Pull request by ChristopheLY**
Fixes #39760

### CODE REVIEW

File: scene/animation/tween.cpp [hunk 1]
```diff
@@ -713,6 +713,7 @@ void Tween::_tween_process(float p_delta) {
 
 		// Is the data not active or already finished? No need to go any further
 		if (!data.active || data.finish) {
+			all_finished = true;
```
Comment (akien-mga) [inline scene/animation/tween.cpp:716]: The fix would be to fix the logic for `all_finished` on line 716, not hack it here, possibly losing information about a previous `data` which was active and not finished (so this would introduce a bug IMO).

Comment (ChristopheLY) [reply scene/animation/tween.cpp:716]: Is it better to make this ?
`all_finished = !data.active || data.finish;`

Comment (akien-mga) [reply scene/animation/tween.cpp:716]: No, that would erase the value from previous iterations.
It should be (on line 712):
```
all_finished = all_finished && (data.finish || !data.active)
```

Comment (ChristopheLY) [reply scene/animation/tween.cpp:716]: but `all_finished` is false at this moment and it's because it false that `set_active(false)` and `emit_signal("tween_all_completed")` was not sent (line 816)

Comment (akien-mga) [reply scene/animation/tween.cpp:716]: In your test project, sure. But if could be true if the previous iteration was true.
Its purpose is to check that *all* iterations are finished (or, as you're trying to change, inactive). If *any* iteration is active and not finished, it should end up false when the loop terminates.

File: scene/animation/tween.cpp [hunk 2]
```diff
@@ -713,6 +713,7 @@ void Tween::_tween_process(float p_delta) {
 
 		// Is the data not active or already finished? No need to go any further
 		if (!data.active || data.finish) {
+			all_finished = all_finished && (!data.active || data.finish);
```
Comment (bsil78) [inline scene/animation/tween.cpp:716]: this line is useless : second part **&&...** is **true** by inclosing test ; then '**all_finished**' is not changed by this line of code ; better suppress it if logic is good (do not know)

**Review by bsil78 — CHANGES_REQUESTED** [review]

File: scene/animation/tween.cpp (hunk 2 above)
Comment (bsil78) [reply scene/animation/tween.cpp:716]: `all_finished = true;` is simpler and forces state as well

Comment (ChristopheLY) [reply scene/animation/tween.cpp:716]: https://github.com/godotengine/godot/pull/39801#discussion_r445088518

File: scene/animation/tween.cpp [hunk 3]
```diff
@@ -709,10 +709,11 @@ void Tween::_tween_process(float p_delta) {
 		InterpolateData &data = E->get();
 
 		// Track if we hit one that isn't finished yet
-		all_finished = all_finished && data.finish;
+		all_finished = all_finished && (!data.active || data.finish);
 
 		// Is the data not active or already finished? No need to go any further
 		if (!data.active || data.finish) {
+			all_finished = true;
```
Comment (akien-mga) [inline scene/animation/tween.cpp:716]: It still doesn't seem correct to me. Read the comments and the code again and this about how this algorithm is meant to work:
- `all_finished` is assumed true initially.
- For each tween, we check if it's either inactive (`!data.active`) or finished (`data.finish`) to confirm if `all_finished` is still true (if the tween is active or not finished, then `all_finished` **must become `false`**.
- If the current tween is finished, we skip to the next.

Your current code will make it so that as regardless of previous values of `all_finished`, the variable with be set to `true` any time the iterated tween is finished (so missed the point of the `all_` in the variable name).

Unroll the code on paper if it helps. For the sake of simplicity, let's assumed "finished" means `!data.active || data.finish`, so either `!active` or `finish` is true.
Here's what your current PR does:

| Step | Tween state | `all_finished` |
| ----- | ----- | ----- |
| Before loop | -- | `true` |
| Tween 0 | Finished | `true` |
| Tween 1 | Not finished | `false` |
| Tween 2 | Finished | `true` |
| After loop | --- | `true` |

The Tween will be deactivated and emit `tween_all_completed` even though Tween 1 is not finished.

**Review by akien-mga — CHANGES_REQUESTED** [review]

File: scene/animation/tween.cpp (hunk 1 above)
Comment (akien-mga) [reply scene/animation/tween.cpp:716]: After the last amend we're back to the initial state, which is wrong. See https://github.com/godotengine/godot/pull/39801#discussion_r457329250

File: scene/animation/tween.cpp [hunk 4]
```diff
@@ -709,10 +709,10 @@ void Tween::_tween_process(float p_delta) {
 		InterpolateData &data = E->get();
 
 		// Track if we hit one that isn't finished yet
-		all_finished = all_finished && data.finish;
+		all_finished = all_finished && (!data.active || data.finish);
 
 		// Is the data not active or already finished? No need to go any further
-		if (!data.active || data.finish) {
+		if (all_finished) {
```
Comment (akien-mga) [inline scene/animation/tween.cpp:715]: That's better, but still incorrect. This will now mean that if any previous Tween was unfinished, `all_finished` will become and stay `false` (which is good), but subsequent Tweens which are actually finished won't use the early `continue`, leading to unnecessary computation.

Here's the right fix:
```diff
diff --git a/scene/animation/tween.cpp b/scene/animation/tween.cpp
index 854db5fee2..d45fc7dd07 100644
--- a/scene/animation/tween.cpp
+++ b/scene/animation/tween.cpp
@@ -709,7 +709,7 @@ void Tween::_tween_process(float p_delta) {
                InterpolateData &data = E->get();
 
                // Track if we hit one that isn't finished yet
-               all_finished = all_finished && data.finish;
+               all_finished = all_finished && (!data.active || data.finish);
 
                // Is the data not active or already finished? No need to go any further
                if (!data.active || data.finish) {
```

**Review by akien-mga — CHANGES_REQUESTED** [review]

**Comment by akien-mga** [comment]
Here's another option which might be better and fixes a possible extra bug in that `else if (!repeat)` branch, but I haven't tested so I can't say if it works as I think it should:
```diff
diff --git a/scene/animation/tween.cpp b/scene/animation/tween.cpp
index 854db5fee2..53dacbadbc 100644
--- a/scene/animation/tween.cpp
+++ b/scene/animation/tween.cpp
@@ -701,21 +701,21 @@ void Tween::_tween_process(float p_delta) {
 	}
 
 	// Are all of the tweens complete?
-	bool all_finished = true;
+	int any_unfinished = 0;
 
 	// For each tween we wish to interpolate...
 	for (List<InterpolateData>::Element *E = interpolates.front(); E; E = E->next()) {
 		// Get the data from it
 		InterpolateData &data = E->get();
 
-		// Track if we hit one that isn't finished yet
-		all_finished = all_finished && data.finish;
-
 		// Is the data not active or already finished? No need to go any further
 		if (!data.active || data.finish) {
 			continue;
 		}
 
+		// Track if we hit one that isn't finished yet
+		any_unfinished++;
+
 		// Get the target object for this interpolation
 		Object *object = ObjectDB::get_instance(data.id);
 		if (object == nullptr) {
@@ -802,17 +802,15 @@ void Tween::_tween_process(float p_delta) {
 			// If we are not repeating the tween, remove it
 			if (!repeat) {
 				call_deferred("_remove_by_uid", data.uid);
+				any_unfinished--;
 			}
-		} else if (!repeat) {
-			// Check whether all tweens are finished
-			all_finished = all_finished && data.finish;
 		}
 	}
 	// One less update left to go
 	pending_update--;
 
 	// If all tweens are completed, we no longer need to be active
-	if (all_finished) {
+	if (any_unfinished > 0) {
 		set_active(false);
 		emit_signal("tween_all_completed");
 	}

```

**Comment by ChristopheLY** [comment]
Should I apply the other option ?
It's work, like the last one

**Comment by akien-mga** [comment]
I guess it might be safe enough, and easier to understand, yeah.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.

**Comment by akien-mga** [comment]
I reverted the 3.2.3 cherry-pick due to the regression #40679.

Once the regression is solved in the `master` branch, we can look into cherry-pick this with the regression fix again.

**Comment by akien-mga** [comment]
Cherry-picked/backported with regression fixed via #47142.
