### PR TITLE
Adjust the material key bit size for `ParticlesMaterial`

### LINKED ISSUE #51428: [Editor Bug] Particles Emission Shape switch bug
### Godot version

3.4 beta2, 3.4 beta3

### System information

MacOS 10.14.6 intel GPU GLES3

### Issue description

when switching Emission Shape from Sphere to Ring / Ring to Sphere or Point to Directed Points / Directed Points to Point , Editor won't update the particles shape

https://user-images.githubusercontent.com/64188282/128686527-6ddcac58-14c7-471e-9831-f422af956bd0.mov

### Steps to reproduce

create a Particles Node and setup it
change Emission Shape default Point to Directed Points, then change back to Point
or change Emission Shape to Sphere, then change to Ring and change back to Sphere

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by YuriSizov**
Fixes https://github.com/godotengine/godot/issues/51428.

I have very surface level understanding of this, but from what I can see — when we assign 

```cpp
mk.emission_shape = emission_shape;
```

a few lines below the change, we hit the size limit of the struct member size. The value for the ring emitter is 5, which is `101` in binary, but it gets truncated to only 2 bits, turning it into `01`.  `01` (or 1 in dec) is the same value as the sphere emitter, hence why changing between the two doesn't trigger the shader update that you see in the reported issue.

In fact, I think the issue existed before, as the directed points emitter also exceeds the size of the field. But, I guess, directed points are similar to the point emitter which they collide with (4 -> `100` -> `00`), so it went undetected. But it's worth checking if we have similar reported problems, this may also close them.

3 bits should be enough for a couple more emitter types for the time being.

### CODE REVIEW

File: scene/resources/particles_material.h [hunk 1]
```diff
@@ -92,7 +92,7 @@ class ParticlesMaterial : public Material {
 			uint32_t texture_mask : 16;
 			uint32_t texture_color : 1;
 			uint32_t particle_flags : 4;
-			uint32_t emission_shape : 2;
+			uint32_t emission_shape : 3;
```
Comment (akien-mga) [inline scene/resources/particles_material.h:95]: I'd make it 4 to be safe and make the sum 32 instead of 31.

Comment (akien-mga) [reply scene/resources/particles_material.h:95]: Which is the size of `key` in the union too, so it should keep it all on 32-bit IINM.

Comment (akien-mga) [reply scene/resources/particles_material.h:95]: Alternatively, we can use 3 here and add a 1 bit padding field to make it 32. I assume that was the intent of this union, but maybe some fields were removed, make the size 30 bits.

Comment (pycbouh) [reply scene/resources/particles_material.h]: I've made it to 4 in both `master` and `3.x` versions. Since it's all for padding, I guess it wouldn't matter until there are more fields in that struct and we need to reconsider the bits. In `3.x` it doesn't result in a pretty round number like 32 though 🙁

Comment (akien-mga) [reply scene/resources/particles_material.h]: Yeah I've asked reduz and clayjohn for feedback on RC, maybe 3 was indeed better and we should only use what we need to leave room for more fields (though in `master` we've almost exhausted all bits).

Comment (akien-mga) [reply scene/resources/particles_material.h]: @jfons says:

> as long as they are kept under or equal 32 bits it should be fine

Let's go back to `3` since that's what needed, so we keep one bit free. And add a comment before the struct to make it explicit that the sum of fields should be kept <= 32.

Might also be worth adding a comment before the emission shape enum definition to make contributors aware of that restriction if they had several new shapes.

Comment (pycbouh) [reply scene/resources/particles_material.h:100]: Done, added comments to other participating enums too.

**Review by akien-mga — APPROVED** [review]
Looks great, thanks!
