### PR TITLE
Fix for `RuntimeNodeSelect` `selection_list` showing up as an orphaned node when editor is open during runtime

### LINKED ISSUE #98999: Having a Control node gives 7 orphans in 4.4-dev4
### Tested versions

- Reproducible in `4.4-dev4`
- **Not** reproducible in `4.4-dev3`

### System information

Godot v4.4.dev4 - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Tue Oct  8 03:11:08 UTC 2024 on X11 - X11 display driver, Single-window, 3 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Laptop GPU - AMD Ryzen 9 5900HX with Radeon Graphics (16 threads)

### Issue description

I updated to `4.4-dev4` and noticed that I have *7 orphan nodes*. I reopened the same project in `4.4-dev3` and there were no orphans there. This is the output of `print_orphan_nodes()`:
```
32631686465 - Stray Node:  (Type: PopupMenu)
32782681410 - Stray Node: /@ScrollContainer@2/_v_scroll (Type: VScrollBar)
32715572554 - Stray Node: /@ScrollContainer@2 (Type: ScrollContainer)
32749126992 - Stray Node: /@ScrollContainer@2/_h_scroll (Type: HScrollBar)
32816235887 - Stray Node: /@ScrollContainer@2/@Control@3 (Type: Control)
32849790321 - Stray Node: /@Timer@4 (Type: Timer)
32866567538 - Stray Node: /@Timer@5 (Type: Timer)
```
There is nothing in my project called `PopupMenu`. :man_shrugging: 
But after some trial & error, it appears that having a single `Control` node gives these new orphans.

### Steps to reproduce

Create a new project, add a Control node, save, run.
While it's running check the orphan nodes counter.

### Minimal reproduction project (MRP)

Open the project:
[control_orphans.zip](https://github.com/user-attachments/files/17688863/control_orphans.zip)
And when you run it, check the orphans.

### PR DESCRIPTION
**Pull request by yahkr**
- fixes https://github.com/godotengine/godot/issues/98999

The issue appears because the `selection_list` https://github.com/godotengine/godot/commit/194ddfd0c469bf1d554caf62f45a9736333d2c44 exists and is not a part of the tree, this solution destroys and recreates the selection list popup as needed instead of keeping it around.

[MRP from 98999](https://github.com/user-attachments/files/17688863/control_orphans.zip)

### CODE REVIEW

File: scene/debugger/scene_debugger.h [hunk 1]
```diff
@@ -295,6 +295,9 @@ class RuntimeNodeSelect : public Object {
 	void _clear_selection();
 	void _set_selection_visible(bool p_visible);
 
+	void _open_selection_list(Vector<SelectResult> items, Point2 pos);
```
Comment (akien-mga) [inline scene/debugger/scene_debugger.h:298]: We use `const T &` for these types where possible.

```suggestion
	void _open_selection_list(Vector<SelectResult> items, const Point2 &pos);
```

Comment (AThousandShips) [reply scene/debugger/scene_debugger.h:298]: Also for the `Vector`, and prefix arguments with `p_`
```suggestion
	void _open_selection_list(const Vector<SelectResult> &p_items, const Point2 &p_pos);
```

**Review by AThousandShips — APPROVED** [review]
LGTM

**Comment by akien-mga** [comment]
How do you evaluate the cost of re-creating this list every time it's needed?

File: scene/debugger/scene_debugger.cpp [hunk 2]
```diff
@@ -1530,21 +1523,9 @@ void RuntimeNodeSelect::_click_point() {
...
-			root->add_child(selection_list);
+		if (!selection_list) {
+			_open_selection_list(items, pos);
 		}
-
-		selection_list->clear();
-		for (const SelectResult &I : items) {
-			selection_list->add_item(I.item->get_name());
-			selection_list->set_item_metadata(-1, I.item);
-		}
```
Comment (yahkr) [inline scene/debugger/scene_debugger.cpp:1541]: @akien-mga 
> How do you evaluate the cost of re-creating this list every time it's needed?

The cost of this PR's change differs only in that it re-creates the `PopupMenu` itself. The process of populating the list remains unchanged from the current implementation.

**Comment by Repiteo** [comment]
Thanks!
