### PR TITLE
Round AtlasTexture size

### LINKED ISSUE #101341: Round up region and margin size of `AtlasTexture` to nearest integer
### Tested versions

4.4dev7

### System information

Not relevant

### Issue description

`margin` and `region` size of `AtlasTexture` could be set as float value, but they always should be integer values.
`margin` and `region` position of `AtlasTexture` don't have such restriction, so Rect2I can not be used.
See comments https://github.com/godotengine/godot/pull/94365#issuecomment-2573955678 and https://github.com/godotengine/godot/pull/94365#issuecomment-2580034730

### Steps to reproduce

- Create `AtlasTexture`.
- Set region size to `(0.2, 0.2)` for example.
- Get errors (size is rounded to `(0, 0)`):
``` 
  ERROR: The Image width specified (0 pixels) must be greater than 0 pixels.
  ERROR: core/io/image.cpp:2865 - Condition "dsize == 0" is true.
```

### Minimal reproduction project (MRP)

[atlas_texturesize.zip](https://github.com/user-attachments/files/18361808/atlas_texturesize.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #101341

The image size uses integer vector, so the region needed some special handling. There are various solutions, I went with adding a second Rect2 with rounded size. Keeping the original float value makes the property editing more intuitive (because Rect2 size is edited as float vector) and works better with region editor.

### CODE REVIEW

**Comment by arkology** [comment]
https://github.com/godotengine/godot/issues/101341 :)

File: scene/resources/atlas_texture.cpp [hunk 1]
```diff
@@ -227,8 +228,8 @@ bool AtlasTexture::is_pixel_opaque(int p_x, int p_y) const {
 		return true;
 	}
 
-	int x = p_x + region.position.x - margin.position.x;
-	int y = p_y + region.position.y - margin.position.y;
```
Comment (arkology) [inline scene/resources/atlas_texture.cpp:231]: Not necessary as positions are the same.

File: scene/resources/atlas_texture.cpp [hunk 2]
```diff
@@ -227,8 +228,8 @@ bool AtlasTexture::is_pixel_opaque(int p_x, int p_y) const {
...
+	int x = p_x + rounded_region.position.x - margin.position.x;
+	int y = p_y + rounded_region.position.y - margin.position.y;
```
Comment (arkology) [inline scene/resources/atlas_texture.cpp:232]: Not necessary as positions are the same.
Same above.

Comment (KoBeWi) [reply scene/resources/atlas_texture.cpp:232]: Yeah I used it for consistency.

**Comment by arkology** [comment]
Interesting, is it possible to do the same without adding new property?

**Comment by KoBeWi** [comment]
Yes, but it involves rounding the size every time you want to use it.

**Comment by arkology** [comment]
> It doesn't print any errors and has no conditional behavior. 

Margin size could also be negative which may lead to 0x0 texture. As said above, the image size uses integer vector, and it takes region.size + margin.size.
I agree that this does not trigger any errors, but effective (real) margin size is also rounded on Image creation.

File: scene/resources/atlas_texture.cpp [hunk 3]
```diff
@@ -94,6 +94,7 @@ void AtlasTexture::set_region(const Rect2 &p_region) {
 		return;
 	}
 	region = p_region;
+	rounded_region = Rect2(p_region.position, p_region.size.round());
```
Comment (arkology) [inline scene/resources/atlas_texture.cpp:97]: Looks like this one should be `floor()` instead on `round()` (recently I tried to take into account margins while remapping uv in `draw_polygon` and failed, but at least `floor()` usage was correct).

Comment (KoBeWi) [reply scene/resources/atlas_texture.cpp]: I changed it to `floor()`. Now it seems consistent with margins, which are rounded implicitly.

Comment (arkology) [reply scene/resources/atlas_texture.cpp]: Thanks!
(But I'm not actually sure that margins rounded implicitly)

Comment (arkology) [reply scene/resources/atlas_texture.cpp]: Sorry, I mean not sure they are rounded implicitly when calling `get_region_rect()` which is the problem.

Comment (arkology) [reply scene/resources/atlas_texture.cpp]: I tested again and this implicit margin casting is not actually _margin_ casting. It is casting of region + margin (set region.w=1.5 and margin.w=1.49 and then slowly increase margin.w above 1.5).

Comment (KoBeWi) [reply scene/resources/atlas_texture.cpp]: So does anything need to be changed?

Comment (arkology) [reply scene/resources/atlas_texture.cpp]: `margins` can be freely left unchanged.
Thanks!

**Comment by WhalesState** [comment]
I just wonder if `set_region(Rect2(Point2(0.5, 0.5), Size2(8, 8)))` or `set_margin(Rect2(Point2(), Size2(0.5, 0.5)))` can still reproduce the issue since it's only solving it for the region rect size.

**Review by Repiteo — APPROVED** [review]
Simple enough!

**Comment by Repiteo** [comment]
Thanks!
