### PR TITLE
[3.2] Various light culling fixes

### LINKED ISSUE #19438: Cull mask in DirectionalLight appears to have no effect
**Godot version:**
3.x trunk

**OS/device including version:**
ubuntu 18.04, nvidia

**Issue description:**
I have two meshes, one in VisualInstance layer 1 and the other in layer 2. I'd like the DirectionalLight to only affect one mesh but toggling the Cull Mask layers in the inspector has no effect on the scene at all (even toggling off all cull mask layers the scene is still illuminated). 

Switching the DirectionalLight to invisible hides the light source from the scene.

### LINKED ISSUE #46332: Real-time lights on lightmapped surfaces with bake mode "All" are only disabled in GLES2, not GLES3
*Continued from https://github.com/godotengine/godot/pull/41629.*

**Godot version:** `3.2` Git 4f891b706

**OS/device including version:** Fedora 33, GeForce GTX 1080 (NVIDIA 460.39)

**Issue description:**

Real-time lights on lightmapped surfaces with bake mode "All" are only disabled in GLES2, not GLES3. This happens regardless of which renderer was used at the time of lightmap baking. Texture atlases are only used when baking in GLES3, but this bug is also visible when using lightmaps baked without texture arrays in GLES3.

We should fix this so that the behavior in GLES3 is identical to GLES2.

**Steps to reproduce:**

Edit the minimal reproduction project and switch it to GLES3 using the dropdown in the top-right corner.

### DirectionalLight visible

image

### DirectionalLight hidden

image

### DirectionalLight visible

image

### DirectionalLight hidden

image

**Minimal reproduction project:** [test_lightmap_shadow.zip](https://github.com/godotengine/godot/files/6025308/test_lightmap_shadow.zip)

### PR DESCRIPTION
**Pull request by JFonS**
**GLES3**

This commit makes it possible to disable 3D directional lights by using the light's cull mask. It also automatically disables directionals when the object has baked lighting and the light is set to "bake all".

While these changes work fine, they have some downsides due to the current structure of the GLES3 renderer:
- Object sorting is done only once for all directional lights, so there is no way to sort the enabled/disabled objects for each light. 
This results in more GL state changes and can have some performance hit (only happens if directional lights affect some objects and not others).

- Environment lighting is always done in the first pass, regardless of the corresponding directional light being enabled or not.
This means in some cases there will be a first pass with env light only (disabled light) and a second pass with an enabled light only, instead of merging the two passes in a single one.

**GLES2**

Added a check for the light cull mask, since it was previously ignored.

Fixes #46332. Fixes #19438.

### CODE REVIEW

**Comment by clayjohn** [comment]
> Object sorting is done only once for all directional lights, so there is no way to sort the enabled/disabled objects for each light.
This results in more GL state changes and can have some performance hit (only happens if directional lights affect some objects and not others).

When you say "more GL state changes" you mean "unnecessary GL state changes right"? You aren't increasing the number of GL state changes by using the light mask, you just aren't necessarily decreasing state changes resulting in unnecessary changes, right?

**Comment by JFonS** [comment]
The concept of necessary and unnecessary is a bit fuzzy...

Before these changes all directional lights affected all objects, so there were no state changes triggered by using a cull mask.

If we merge this PR, certain lights can be culled for certain objects, so even in the same directional pass, the state can change.

At the time of writing the commit message I thought this would result in a bunch of GL state changes, since there is no way to correctly sort the objects for all lights at once. But after your comment I realized we just need to sort the objects respect to the first light in the list, since the rest of passes (the additive ones) just skip culled lights.


So I will take a look at adding this sorting and the state changes should be minimized.

We still don't solve the issue with the first pass always being in charge of the environment lighting, but in this case performance will stay the same as before, It's just a missed optimization opportunity.

**Comment by clayjohn** [comment]
I think I misunderstood you before. You are talking about the ``USE_LIGHT_DIRECTIONAL`` state changing between draw calls. Indeed, it would lead to wastefully changing state when the cull_mask is used for the first directional light in the scene.  Once you add in the sorting for that, this should be good to go!


> We still don't solve the issue with the first pass always being in charge of the environment lighting, but in this case performance will stay the same as before, It's just a missed optimization opportunity.

I agree. I don't think this can be easily solved with the current architecture in 3.2. I wouldn't worry about it

**Comment by akien-mga** [comment]
The regression test project + sanitizer found a heap-use-after-free, see logs in https://github.com/godotengine/godot/pull/46694/checks?check_run_id=2047848252

Here's what the CI runs if you want to try it locally:
https://github.com/godotengine/godot/blob/3d5f964a4993d6bd172f70a738bb95a77039072f/.github/workflows/linux_builds.yml#L189-L210

**Comment by JFonS** [comment]
@akien-mga I noticed... I will take a look on monday.

**Review by clayjohn — APPROVED** [review]
Approved subject to Akien's comment about the heap use after free.

File: drivers/gles3/rasterizer_scene_gles3.cpp [hunk 1]
```diff
@@ -2382,8 +2384,12 @@ void RasterizerSceneGLES3::_add_geometry_with_material(RasterizerStorageGLES3::G
 		e->geometry->index = current_geometry_index++;
 	}
 
-	if (!p_depth_pass && directional_light && (directional_light->light_ptr->cull_mask & e->instance->layer_mask) == 0) {
-		e->sort_key |= SORT_KEY_NO_DIRECTIONAL_FLAG;
+	// We sort only by the first directional light. The rest of directional lights will be drawn in additive passes that are skipped if disabled.
+	if (first_directional_light.is_valid()) {
+		RasterizerStorageGLES3::Light *directional = light_instance_owner.getptr(first_directional_light)->light_ptr;
```
Comment (akien-mga) [inline drivers/gles3/rasterizer_scene_gles3.cpp:2389]: I guess the heap-use-after-free is here, the saved instance must be pointing at a now freed Light.

I'm not familiar with this code but isn't it possible to use `directional_lights[0]` (after checking the size I guess) instead of saving the first light RID in `first_directional_light`?

Comment (JFonS) [reply drivers/gles3/rasterizer_scene_gles3.cpp:2389]: That's what I was doing before, and saving the RID was an attempt to fix the issue :)

Comment (JFonS) [reply drivers/gles3/rasterizer_scene_gles3.cpp:2389]: Not sure what's going on... I though the RID and RID_Owner system would take care of invalidating freed objects, but it doesn't seem to work.

Comment (JFonS) [reply drivers/gles3/rasterizer_scene_gles3.cpp:2389]: I pushed a last attempt at fixing this, but I don't think it will succeed. 

The only other way I can think for fixing this is checking here: https://github.com/godotengine/godot/blob/118567ca2853bf120f7195a9fb9684038cb97f5f/drivers/gles3/rasterizer_scene_gles3.cpp#L4948-L4953
If `p_rid == first_directional_light` and invalidating the stored `RID` in such case, but it's quite hacky...

Comment (JFonS) [reply drivers/gles3/rasterizer_scene_gles3.cpp:2389]: Seems like it worked. I will confirm with reduz whether RIDs are meant to be used like this, because I only found one occurrence of a similar check in the same file.

**Comment by JFonS** [comment]
@akien-mga The use-after-free issue is fixed, so this should be good to merge :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by Calinou** [comment]
@tavurth Please open a new issue with a minimal reproduction project attached. Make sure to test 3.4.2 *and* 3.4.3rc1 on the same project.
