### PR TITLE
Fix `Input.vibrate_handheld` on Android.

### LINKED ISSUE #103496: Input.vibrate_handheld Android crash
### Tested versions

4.4-rc3

### System information

Android

### Issue description

Whenever is Input.vibrate_handheld() called on Android platform the game crash.
No specific message in log is shown.
Doesn`t matter if Vibrate permission is set or not.
Android project was generated by Android template.

I guess it worked in 4.3 but have no time to test it right now.

### Steps to reproduce

Just create Android build and call  Input.vibrate_handheld()

### Minimal reproduction project (MRP)

(Sorry I have no time currently to create one.)

### PR DESCRIPTION
**Pull request by Alex2782**
Fixes #103496

Catched the crash via `try / catch`.

```kotlin
			try {
                                 ....
                                 vibratorService.vibrate( .... )
                                 ....
			} catch (e: SecurityException) {
				Log.w(TAG, e)
			}

```

<details><summary>logcat</summary>

```java
06-11 02:50:51.881 26791 26927 W Godot   : java.lang.SecurityException: vibrate: Neither user 10717 nor current process has android.permission.VIBRATE.
06-11 02:50:51.881 26791 26927 W Godot   :      at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
06-11 02:50:51.881 26791 26927 W Godot   :      at android.os.Parcel.createException(Parcel.java:3007)
06-11 02:50:51.881 26791 26927 W Godot   :      at android.os.Parcel.readException(Parcel.java:2990)
06-11 02:50:51.881 26791 26927 W Godot   :      at android.os.Parcel.readException(Parcel.java:2932)
06-11 02:50:51.881 26791 26927 W Godot   :      at android.os.IVibratorManagerService$Stub$Proxy.vibrate(IVibratorManagerService.java:438)
06-11 02:50:51.881 26791 26927 W Godot   :      at android.os.SystemVibratorManager.vibrate(SystemVibratorManager.java:140)
06-11 02:50:51.881 26791 26927 W Godot   :      at android.os.SystemVibrator.vibrate(SystemVibrator.java:218)
06-11 02:50:51.881 26791 26927 W Godot   :      at android.os.Vibrator.vibrate(Vibrator.java:513)
06-11 02:50:51.881 26791 26927 W Godot   :      at android.os.Vibrator.vibrate(Vibrator.java:464)
06-11 02:50:51.881 26791 26927 W Godot   :      at org.godotengine.godot.Godot.vibrate(Godot.kt:1017)
06-11 02:50:51.881 26791 26927 W Godot   :      at org.godotengine.godot.GodotLib.step(Native Method)
06-11 02:50:51.881 26791 26927 W Godot   :      at org.godotengine.godot.gl.GodotRenderer.onDrawFrame(GodotRenderer.java:61)
06-11 02:50:51.881 26791 26927 W Godot   :      at org.godotengine.godot.gl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1592)
06-11 02:50:51.881 26791 26927 W Godot   :      at org.godotengine.godot.gl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1294)
06-11 02:50:51.881 26791 26927 W Godot   : Caused by: android.os.RemoteException: Remote stack trace:
06-11 02:50:51.881 26791 26927 W Godot   :      at android.app.ContextImpl.enforce(ContextImpl.java:2359)
06-11 02:50:51.881 26791 26927 W Godot   :      at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2387)
06-11 02:50:51.881 26791 26927 W Godot   :      at com.android.server.vibrator.VibratorManagerService.vibrateInternal(VibratorManagerService.java:447)
06-11 02:50:51.881 26791 26927 W Godot   :      at com.android.server.vibrator.VibratorManagerService.vibrate(VibratorManagerService.java:435)
06-11 02:50:51.881 26791 26927 W Godot   :      at android.os.IVibratorManagerService$Stub.onTransact(IVibratorManagerService.java:252)
06-11 02:50:51.881 26791 26927 W Godot   : 
06-11 02:50:51.881 26791 26927 V Godot   : OnGodotMainLoopStarted
```
</details>

### CODE REVIEW

**Review by m4gr3d — APPROVED** [review]

**Comment by Alex2782** [comment]
@m4gr3d  

`VIBRATE` is "normal" and not "dangerous permission" is this code correct?

```kotlin
	@SuppressLint("MissingPermission")
	@Keep
	private fun vibrate(durationMs: Int, amplitude: Int) {
		if (durationMs > 0 && requestPermission("VIBRATE")) {

```

<details><summary>Details</summary>

https://developer.android.com/reference/android/Manifest.permission#VIBRATE

> Allows access to the vibrator.
> Protection level: normal


https://github.com/godotengine/godot/blob/1bbfe637c62d48dd455562bf2bc24d92e6ba9ade/platform/android/java/lib/src/org/godotengine/godot/utils/PermissionsUtil.java#L140-L182


</details>

**Comment by m4gr3d** [comment]
@Alex2782 The check could probably be removed, but it's fine either way. The logic in https://github.com/godotengine/godot/blob/1bbfe637c62d48dd455562bf2bc24d92e6ba9ade/platform/android/java/lib/src/org/godotengine/godot/utils/PermissionsUtil.java#L119 validates the permission is `DANGEROUS` before requesting it, so it's a `NORMAL` permission, then the request is a no-op.

**Review by syntaxerror247 — APPROVED** [review]

**Comment by akien-mga** [comment]
Shouldn't we output a more user-friendly error than just forwarding an exception if the issue is just that the permission wasn't set?

And shouldn't there be a way to request a "normal" permission so that this code can work instead of failing with an exception?

**Comment by syntaxerror247** [comment]
> Shouldn't we output a more user-friendly error than just forwarding an exception if the issue is just that the permission wasn't set?

I think, exception clearly indicates the error: `Neither user 10717 nor current process has android.permission.VIBRATE.` but yeah a message can be added like "Needs to enable VIBRATE permission in export preset to use vibration" or something similar.

> And shouldn't there be a way to request a "normal" permission so that this code can work instead of failing with an exception?

Normal permissions cannot be requested at runtime. They need to be declared in the manifest (by selecting in export preset) and are granted by default.

**Comment by Alex2782** [comment]
> a more user-friendly error

now: `SecurityException: VIBRATE permission not granted. Make sure it is declared in the manifest and enabled in the export preset.`

<details><summary>logcat</summary>

-------------

`adb logcat -s Godot`

``` java
06-11 16:40:25.546  3811  3864 V Godot   : OnGodotSetupCompleted
06-11 16:40:25.557  3811  3864 W Godot   : SecurityException: VIBRATE permission not granted. Make sure it is declared in the manifest and enabled in the export preset.
06-11 16:40:25.557  3811  3864 V Godot   : OnGodotMainLoopStarted
```
</details>

File: platform/android/java/lib/src/org/godotengine/godot/Godot.kt [hunk 1]
```diff
@@ -1011,25 +1011,29 @@ class Godot(private val context: Context) {
...
+					}
+				} else {
+					// deprecated in API 26
+					vibratorService.vibrate(durationMs.toLong())
 				}
-			} else {
-				// deprecated in API 26
-				vibratorService.vibrate(durationMs.toLong())
+			} catch (e: SecurityException) {
+				Log.w(TAG, "SecurityException: VIBRATE permission not granted. Make sure it is declared in the manifest and enabled in the export preset.")
```
Comment (syntaxerror247) [inline platform/android/java/lib/src/org/godotengine/godot/Godot.kt]:
```suggestion
				Log.w(TAG, "SecurityException: VIBRATE permission not found. Make sure it is enabled in the export preset.")
```

Enabling in the export preset adds the permission to manifest during export.

Comment (Alex2782) [reply platform/android/java/lib/src/org/godotengine/godot/Godot.kt]: I've changed the text. And what about the `Godot Android library`? 
Do users have to edit the manifest file themselves?

https://docs.godotengine.org/en/stable/tutorials/platform/android/android_library.html

Comment (m4gr3d) [reply platform/android/java/lib/src/org/godotengine/godot/Godot.kt]: > I've changed the text. And what about the `Godot Android library`? Do users have to edit the manifest file themselves?
> 
> https://docs.godotengine.org/en/stable/tutorials/platform/android/android_library.html

Good point, I think we should keep the language about checking that it's declared in the manifest.

Comment (Alex2782) [reply platform/android/java/lib/src/org/godotengine/godot/Godot.kt]: In the documentation, I also found `Godot Android plugins`. 
Should I then output the error message more generally in 2 lines?


```kotlin
Log.w(TAG, "SecurityException: VIBRATE permission not found. Make sure it is enabled in the export preset.")
Log.w(TAG, "If using a custom Android library (e.g. Godot plugin), declare it in the AndroidManifest.xml.")
```

Comment (syntaxerror247) [reply platform/android/java/lib/src/org/godotengine/godot/Godot.kt]: How about this then?
```
Log.w(TAG, "SecurityException: VIBRATE permission not found. Make sure it is declared in the manifest or enabled in the export preset.")
```

Comment (syntaxerror247) [reply platform/android/java/lib/src/org/godotengine/godot/Godot.kt]: > In the documentation, I also found `Godot Android plugins`. Should I then output the error message more generally in 2 lines?
> 
> ```kotlin
> Log.w(TAG, "SecurityException: VIBRATE permission not found. Make sure it is enabled in the export preset.")
> Log.w(TAG, "If using a custom Android library (e.g. Godot plugin), declare it in the AndroidManifest.xml.")
> ```

This also seems good.

Comment (Alex2782) [reply platform/android/java/lib/src/org/godotengine/godot/Godot.kt]: ok now: 
`SecurityException: VIBRATE permission not found. Make sure it is declared in the manifest or enabled in the export preset.`

**Review by syntaxerror247 — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
