### PR TITLE
Make unsaved scene dialog more accurate

### LINKED ISSUE #116224: The last saved time is not really correct
### Tested versions

4.6

### System information

W10

### Issue description

When you try to close an unsaved scene, you will get a message telling you when it was last saved:

Image

It's now always true.
The time it shows is the minimum of file modification time and editor startup time. If you open a new scene and modify it, the message will say that the scene was last saved whatever long you happen to have the editor open right now. Also nitpick, but even if it's the first scene you opened, saying it was last saved when you opened it is technically not correct either.

I think the scenes should:
- track the time they were opened instead of counting from when the editor was opened
- if the scene was not saved yet, the message should convey that better
  - but not sure how, something like "This scene was opened 5 minutes ago and not saved yet" seems weird

### Steps to reproduce

1. Open editor
2. Wait 1 minute
3. Open any scene, modify it and try to close the tab
4. Read the confirmation dialog

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Klology**
Fixes #116224

Updated the last saved dialog to now show the time since the scene was opened if it hasn't been saved since. Previously it would just show the time since the editor itself was opened.

4.6 when the scene was actually saved several minutes ago:
image

This pr when the scene was last saved before it was opened:
image

This pr when the scene was last saved after it was opened (same as 4.6):
image

### CODE REVIEW

File: scene/main/node.h
Comment (KoBeWi) [inline scene/main/node.h:1]: The opened time shouldn't be stored in Node 💀

You can use this struct in EditorData:
https://github.com/godotengine/godot/blob/bf95b62586e31b8a3503f5903d7764d7c52bf2ab/editor/editor_data.h#L113

Comment (Klology) [reply scene/main/node.h:1]: Thanks for reviewing my first PR and the info on how to improve it.

I did consider the EditedScene struct but when trying to integrate it into the already existing code with how the _get_unsaved_scene_dialog_text was being called Node seemed like the better call. 

I would love to hear your and @DexterFstone's insights. While they may be obvious to you, the emojis don't explain much to a newcomer like me 💀 

I've pushed the changes to move the time to EditedScene. Since this was the only piece of feedback I got from you, does that mean you agree with my approach to fixing the issue you had with the save dialog?

Comment (DexterFstone) [reply scene/main/node.h:1]: Sorry for the emoji; the emoji wasn't for your implementation

File: editor/editor_data.h [hunk 1]
```diff
@@ -122,6 +122,7 @@ class EditorData {
 		NodePath live_edit_root;
 		int history_id = 0;
 		uint64_t last_checked_version = 0;
+		uint64_t time_opened = Time::get_singleton()->get_unix_time_from_system();
```
Comment (KoBeWi) [inline editor/editor_data.h]: This should be assigned where EditedScene is created, not here.

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -6624,7 +6635,8 @@ void EditorNode::_scene_tab_closed(int p_tab) {
 		if (scene_filename.is_empty()) {
 			unsaved_message = TTR("This scene was never saved.");
 		} else {
-			unsaved_message = _get_unsaved_scene_dialog_text(scene_filename, started_timestamp);
+			uint32_t time_opened = editor_data.get_edited_scenes()[p_tab].time_opened;
```
Comment (KoBeWi) [inline editor/editor_node.cpp]: You should add a `get_scene_time_opened()` to EditorData, instead of fetching the whole array (it makes a copy).

Same above.

File: editor/editor_node.cpp [hunk 3]
```diff
@@ -3535,7 +3546,7 @@ void EditorNode::_menu_option_confirm(int p_option, bool p_confirmed) {
 			if (unsaved_cache) {
 				if (!p_confirmed) {
 					confirmation->set_ok_button_text(TTRC("Save & Reload"));
-					const String unsaved_message = _get_unsaved_scene_dialog_text(scene_filename, started_timestamp);
```
Comment (KoBeWi) [inline editor/editor_node.cpp:3538]: The `started_timestamp` is now unused. Should be removed.

File: editor/editor_data.h (hunk 1 above)
Comment (Klology) [reply editor/editor_data.h]: Moved to here:
https://github.com/Klology/godot/blob/4a823dcd23d67c3c32f1d797956f10a05bb3dd95/editor/editor_data.cpp#L621

File: editor/editor_node.cpp (hunk 2 above)
Comment (Klology) [reply editor/editor_node.cpp]: Good to know, thanks. Added the function and replaced the get_edited_scene calls with it.

File: editor/editor_node.cpp (hunk 3 above)
Comment (Klology) [reply editor/editor_node.cpp:3538]: Removed

File: editor/editor_node.cpp [hunk 4]
```diff
@@ -3269,13 +3267,15 @@ void EditorNode::_android_explore_build_templates() {
...
 }
 
-static String _get_unsaved_scene_dialog_text(String p_scene_filename, uint64_t p_started_timestamp) {
+static String _get_unsaved_scene_dialog_text(String p_scene_filename, uint64_t p_opened_timestamp) {
+	const uint64_t scene_modified_time = FileAccess::get_modified_time(p_scene_filename);
 	String unsaved_message;
 
-	// Consider editor startup to be a point of saving, so that when you
+	// Consider scene opening to be a point of saving, so that when you
 	// close and reopen the editor, you don't get an excessively long
```
Comment (KoBeWi) [inline editor/editor_node.cpp:3275]:
```suggestion
	// close and reopen the scene, you don't get an excessively long
```

**Review by KoBeWi — APPROVED** [review]
