### PR TITLE
Android: Refactor Custom Build options in export preset

### LINKED ISSUE #62465: "Changing the "Target SDK" is not valid" error even though I never tried to
### Godot version

3.5. RC5

### System information

Win, Nvidea 765M

### Issue description

I'm testing the latest Godot 3.5.RC build, trying the one click deploy but can't export and get this error:

image

I have not touched the "Target SDK":

image

If I enable "Use Custom Build" like the error message seems to want me to, I get another error which also makes no sense to me (I have the 3.5.RC5 templates installed, even restarted Godot 3.5RC5 after just to make sure):

image

Not sure if this is related to https://github.com/godotengine/godot/pull/61691 or https://github.com/godotengine/godot/pull/51815 since the times I have tested Godot 3.5 so far, I never tried to export.

### Steps to reproduce

Trying to export working 3.4.4 project to Android.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by akien-mga**
Instead of reusing the custom_template/ prefix which is actually only
used for the prebuilt APK workflow, we add a new custom_build/ prefix.

This is a slight compat breakage (users will have to redo their config)
but enables us to group the Min SDK and Target SDK options where they make
sense, and avoid reusing the previously hardcoded Target SDK 30 from
Godot 3.4.

Those two options are now strings instead of integers so that we can keep
them empty by default, and show their default value using a placeholder.
So some validation has been added to make sure they are proper ints.
The upper bound on Target SDK was also removed as it's a common use case
to use it to try to target newer released SDKs. But we warn the user that
this wasn't validated by us.

The export info dialog is now exclusive so that when it doesn't auto-close,
i.e. when it errors, you don't close it by mistake by clicking outside.

- Fixes #62465.
- Forward port of `3.x` version: #62602

### CODE REVIEW

File: platform/android/export/export_plugin.cpp [hunk 1]
```diff
@@ -2201,43 +2203,68 @@ bool EditorExportPlatformAndroid::can_export(const Ref<EditorExportPreset> &p_pr
...
+			err += TTR("\"Target SDK\" can only be overridden when \"Use Custom Build\" is enabled.");
+			err += "\n";
+		}
+		if (!target_sdk_str.is_valid_int()) {
+			valid = false;
+			err += vformat(TTR("\"Target SDK\" should be a valid integer, but got \"%s\" which is invalid."), target_sdk_str);
+			err += "\n";
+		} else {
+			target_sdk_int = target_sdk_str.to_int();
+		}
```
Comment (m4gr3d) [inline platform/android/export/export_plugin.cpp:2262]: I agree with not capping the target sdk (surprisingly, gradle doesn't complain when you use insanely high values of the target sdk), but we should include a warning to let users know that the engine hasn't been tested with the specified target sdk value and may be instable.

This will let advanced users test new versions of the target sdk and report issues if they encounter any (speeding up our upgrade process), while regular users will be nudged back toward the safer (tested) versions.

**Review by m4gr3d — CHANGES_REQUESTED** [review]

File: platform/android/export/export_plugin.cpp (hunk 1 above)
Comment (m4gr3d) [reply platform/android/export/export_plugin.cpp:2262]: > as it's typically used to
support newer SDKs faster than we do with official builds

Note that customizing the target sdk build is also done when targeting other stores that don't have the play store requirements (e.g: Oculus store, Amazon Android store).

Comment (akien-mga) [reply platform/android/export/export_plugin.cpp:2262]: I agree, but we don't really have a good way to show such warnings to the users without being obnoxious if they actually know what they're doing.

This validation code can only add blocking errors, and while we could do a `WARN_PRINT`, it's easy to miss and will always be printed whenever they open the export dialog. Similarly, showing an info dialog in the editor would also happen every time.

We'd have to implement a custom dialog with a "Don't show this again." checkbox which saves to editor metadata for future occurrences (and somehow has logic to get reset if the conditions for the warnings change). That's significant work and IMO outside the scope of this PR.

Comment (m4gr3d) [reply platform/android/export/export_plugin.cpp:2262]: @akien-mga we already support printing warnings by updating the `err` string but setting `valid` to true.
See https://github.com/godotengine/godot/blob/master/editor/project_export.cpp#L277-L287

Comment (akien-mga) [reply platform/android/export/export_plugin.cpp]: Thanks, adding a warning as we discussed.

**Review by m4gr3d — APPROVED** [review]
Looks great!

**Comment by akien-mga** [comment]
For the record, I only found this screenshot that requires an update in the docs: https://github.com/godotengine/godot-docs/pull/5905
