### PR TITLE
removed 2nd particle collision velocity calculation

### LINKED ISSUE #65707: GPUParticles collisions shader code seems broken. Creates jittery bounces when bounce > 0.0
### Godot version

4.0.alpha15

### System information

Arch Linux, Vulkan

### Issue description

GPUParicles bounce is very jittery and doesn't respond well to `collision_bounce` being increased.

When checking the gdshader that was generated from the particle process resource, i noticed 2 different places where velocity was being calculated after a collision.

removing the 2nd one appeared to fix the issue, but made `collision_friction` affect the height of the bounce, which it probably shouldn't do.

### Steps to reproduce

Create a GPUParticle3d node, rigid body, and height field

ensure that the rigid body is inside of the height field, but the particle emitter is not.

set the particle's collision mode to "rigid" and bounce to 1.0

observe the jittery behavior when the particles land on the rigid body

### Minimal reproduction project

[minimal.tar.gz](https://github.com/godotengine/godot/files/9549165/minimal.tar.gz)

### PR DESCRIPTION
**Pull request by benbot**
The velocity change of a particle that has collided with something is being applied twice in the GPUParticleProcess shader, causing some weirdness.

This removes the newer, 2nd velocity calculation. keeping the original one in its place.

Should resolve  #65707

### CODE REVIEW

File: scene/resources/particle_process_material.cpp [hunk 1]
```diff
@@ -830,6 +830,13 @@ void ParticleProcessMaterial::_update_shader() {
 		code += "	TRANSFORM[3].z = 0.0;\n";
 	}
 
+	// scale by scale
+	code += "	float base_scale = mix(scale_min, scale_max, scale_rand);\n";
+	code += "	base_scale = sign(base_scale) * max(abs(base_scale), 0.001);\n";
+	code += "	TRANSFORM[0].xyz *= base_scale * sign(tex_scale.r) * max(abs(tex_scale.r), 0.001);\n";
+	code += "	TRANSFORM[1].xyz *= base_scale * sign(tex_scale.g) * max(abs(tex_scale.g), 0.001);\n";
+	code += "	TRANSFORM[2].xyz *= base_scale * sign(tex_scale.b) * max(abs(tex_scale.b), 0.001);\n";
+
```
Comment (clayjohn) [inline scene/resources/particle_process_material.cpp:839]: It looks like this was originally above the ``if (COLLIDED)`` branch but was moved to be below in https://github.com/godotengine/godot/pull/55387. 

What is the reasoning for bringing it back up? In either case it looks like it shouldn't interact with the ``if (COLLIDED)`` branch

Comment (benbot) [reply scene/resources/particle_process_material.cpp:839]: The diff came out a little weird.
What I did was remove the 2nd conditional and move the 1st down to where the 2nd was so that the `else if(collision_mode == COLLISION_HIDE_ON_CONTACT)` block would still behave the same.

**Review by clayjohn — APPROVED** [review]
Well, looks good to me. On closer inspection, it shouldn't matter whether that block is moved above the collision check or not. 

Let's move forward with merging this.
