### PR TITLE
Display a warning if device CPU architecture is not active in the export preset.

### LINKED ISSUE #86284: Android Remote Debug: Godot Editor remains stuck if one-click deploy device architecture doesn't match the device
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - macOS 14.2.0 - Vulkan (Mobile) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

Godot does not yet check whether the architecture fits. Progress bar remains stuck at 66%, it is not possible to press "Cancel". The application "does not respond" and must be terminated via the task manager.

Bildschirmfoto 2023-12-18 um 02 23 22

### Steps to reproduce

In the export dialog, select the Android CPU architecture that the device does **not** support.

Bildschirmfoto 2023-12-18 um 01 23 06
Bildschirmfoto 2023-12-18 um 01 23 35

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Alex2782**
Fixes #86284

Editor crash / freeze _(with arm32 devices)_ are prevented by selecting the correct device CPU architecture. It should also be more user-friendly. https://github.com/godotengine/godot/issues/86284#issuecomment-1941920808

### CODE REVIEW

File: platform/android/export/export_plugin.cpp [hunk 1]
```diff
@@ -2002,6 +2003,13 @@ Error EditorExportPlatformAndroid::run(const Ref<EditorExportPreset> &p_preset,
 		return ERR_UNCONFIGURED;
 	}
 
+	// Force device CPU architecture
+	String preset_arch = "architectures/" + devices[p_device].cpu_abi;
+	bool is_device_abi_enabled = p_preset->get(preset_arch);
+	if (!is_device_abi_enabled) {
+		p_preset->set(preset_arch, true);
+	}
```
Comment (m4gr3d) [inline platform/android/export/export_plugin.cpp:2011]: We should provide a warning to the user, maybe throw an error dialog with the option to continue regardless. I don't like the idea of forcing a behavior without user consent and / or knowledge.

**Review by m4gr3d — CHANGES_REQUESTED** [review]

**Review by m4gr3d — APPROVED** [review]
This updated approach looks good to me!

I wonder if it's worth adding an additional `Fix and run` button to the confirm dialog to automatically add the missing architecture as your previous approach was doing, though that may make the UX looks busy.

cc @Calinou Any thoughts on the UX used in this PR?

**Comment by Calinou** [comment]
> I wonder if it's worth adding an additional Fix and run button to the confirm dialog to automatically add the missing architecture as your previous approach was doing, though that may make the UX looks busy.

This should be done if we want to provide a "Run Remote Debug anyway" button, as the button is unlikely to work otherwise. This is even more the case with Android 14 and later which is no longer able to run 32-bit ARM apps on 64-bit ARM devices.

**Comment by akien-mga** [comment]
Thanks!

**Comment by Alex2782** [comment]
`Fix and run` button maybe later (new PR).
