### PR TITLE
Fix for OccluderPolygon2D memory leak

### LINKED ISSUE #53722: Setting polygon in `OccluderPolygon2D`, causes memory leak
### Godot version

4.0.dev.custom_build. 2a28df82d

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

```
func _process(delta) -> void:
	var temp_variable168 = OccluderPolygon2D.new()
	temp_variable168.set_polygon(PackedVector2Array([Vector2(-1.96203291416168, 43.732250213623), Vector2(-3.87614369392395, -31.1479396820068), Vector2(0.90432775020599, 0.42683869600296), Vector2(-0.67551755905151, -0.73734384775162), Vector2(0.64782792329788, -0.76178675889969), Vector2(-19.8318519592285, -23.6984405517578), Vector2(18.73681640625, 32.8182144165039), Vector2(-41.7148208618164, -23.8256015777588), Vector2(0.73689669370651, -0.67600530385971), Vector2(0.74997538328171, -0.66146582365036), Vector2(-9.57956314086914, -7.77863883972168), Vector2(0.97349464893341, 0.22870987653732), Vector2(12.0813131332397, -25.7706909179688), Vector2(-14.5937471389771, 14.8585910797119), Vector2(0.96760237216949, -0.25247895717621)]))
```
causes this memory leak
```
WARNING: 40 RIDs of type "IndexArray" were leaked.
     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:8962)
WARNING: 40 RIDs of type "IndexBuffer" were leaked.
     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:8962)
WARNING: 40 RIDs of type "VertexArray" were leaked.
     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:8962)
WARNING: 40 RIDs of type "VertexBuffer" were leaked.
     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:8962)
```

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by jmattspartacus**
Fix for https://github.com/godotengine/godot/issues/53722

RendererCanvasRenderRD::occluder_polygon_set_shape was not freeing index/vertex arrays/buffers because sdf_point_count and line_point_count for OccluderPolygon2D were not being set after initialization. 

To fix this, I set line_point_count, and then also added a check to see if the number of lines/points is zero and allow it to free in that case.

I do not know the intent of sdf_point_count, so I have not set that value.

_Production edit: Closes https://github.com/godotengine/godot/issues/53722_

### CODE REVIEW

File: servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp [hunk 1]
```diff
@@ -1844,7 +1844,6 @@ void RendererCanvasRenderRD::occluder_polygon_set_shape(RID p_occluder, const Ve
 	ERR_FAIL_COND(!oc);
 
 	Vector<Vector2> lines;
-
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:1847]: You should avoid changing whitespace in lines that don't relate to your PR as they create a lot of noise in the git history.

File: servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp [hunk 2]
```diff
@@ -1941,6 +1941,7 @@ void RendererCanvasRenderRD::occluder_polygon_set_shape(RID p_occluder, const Ve
 			oc->index_buffer = RD::get_singleton()->index_buffer_create(3 * lc, RD::INDEX_BUFFER_FORMAT_UINT16, indices);
 			oc->index_array = RD::get_singleton()->index_array_create(oc->index_buffer, 0, 3 * lc);
 
+
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:1944]: Same as above, this line should be deleted

File: servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp [hunk 3]
```diff
@@ -1971,12 +1972,13 @@ void RendererCanvasRenderRD::occluder_polygon_set_shape(RID p_occluder, const Ve
...
 	}
 
-	if (oc->sdf_index_count != sdf_indices.size() && oc->sdf_point_count != p_points.size() && oc->sdf_vertex_array.is_valid()) {
+	if (((oc->sdf_index_count != sdf_indices.size() && oc->sdf_point_count != p_points.size()) || p_points.size() == 0) && oc->sdf_vertex_array.is_valid()) {
 		RD::get_singleton()->free(oc->sdf_vertex_array);
 		RD::get_singleton()->free(oc->sdf_vertex_buffer);
 		RD::get_singleton()->free(oc->sdf_index_array);
 		RD::get_singleton()->free(oc->sdf_index_buffer);
 
+
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:1981]: This line should be deleted

**Review by clayjohn — COMMENTED** [review]
Just a few nitpicky comments about whitespace to keep the PR clean. The implementation seems fine

File: servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp (hunk 1 above)
Comment (jmattspartacus) [reply servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:1847]: I think this was an accident in removing some code for debug output. Just to keep this out of history, I should just squash the commits, right?

**Comment by clayjohn** [comment]
Looks great! The final step before merging is to squash all the commits together so that the whole PR only contains 1 big commit with all your changes. We like to merge one commit at a time to keep the git history clean and navigable. 

If you don't know how to do that, we have a helpful tutorial in the official documentation https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase

**Comment by jmattspartacus** [comment]
Should be ready at any point, let me know if/when there is anything else I need to do.

**Review by clayjohn — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks, and congrats on your first merged Godot pull request!
