### PR TITLE
Fix local 3D translation editing

### LINKED ISSUE #81604: Incorrect Node3D transform when moving and rotating with the gizmo in local space if parent node's coordinates are not in (0,0,0)
### Godot version

v4.2.dev4.official [549fcce5f]

### System information

Windows 10 - Godot v4.2.dev4.official - Vulkan (Forward+) editor

### Issue description

Version **4.2-dev4** introduced incorrect behavior when transforming nodes in local space (Node "jumps" to unwanted position). In the previous version everything works correctly.

https://github.com/godotengine/godot/assets/97123013/d098cfc9-6a34-4674-b042-2ef74f4a46b8

### Steps to reproduce

1. Create any **Node3D**
3. Add any child **Node3D**
4. Move parent node away from **(0,0,0)** or/and rotate it
5. Enable **"use local space"**
6. Try to move child node with gizmo and see undesired behavior when transforming

### Minimal reproduction project

[translate_localspace_editor_bug.zip](https://github.com/godotengine/godot/files/12593837/translate_localspace_editor_bug.zip)

### PR DESCRIPTION
**Pull request by AThousandShips**
Transformation was applied incorrectly, transformation is now smoother and doesn't jump incorrectly

* Fixes: #81604

### CODE REVIEW

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -1459,14 +1459,15 @@ Transform3D Node3DEditorViewport::_compute_transform(TransformMode p_mode, const
 				p_motion.snap(Vector3(p_extra, p_extra, p_extra));
 			}
 
+			Transform3D t;
 			if (p_local) {
-				p_motion = p_original.basis.xform(p_motion);
+				t = p_original_local;
+				t.origin += p_original_local.basis.xform(p_motion);
```
Comment (AThousandShips) [inline editor/plugins/node_3d_editor_plugin.cpp:1465]: This matches the other cases and makes the movement smooth, using `p_original` makes the movement jerky with scale, which doesn't make sense to me, for example if it is scaled the motion is scaled up in the original implementation

**Comment by capnm** [comment]
I have tested my projects, the local 3D transformations in the editor seem to work now properly :+1:

**Comment by TokageItLab** [comment]
I will test it today.

**Comment by capnm** [comment]
(At 5f1e56f + #81609)  I'm not sure where this is coming from. In some cases the translated models temporarily leave their wireframes in the editor, perhaps someone can observe this also during testing):

image

Close an open the scene in editor:

image

**Comment by AThousandShips** [comment]
Cannot replicate this bug, also it doesn't happen without this PR for you?

**Comment by AThousandShips** [comment]
Unrelated to this PR, happens without it, please open a bug report for it on the latest version

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 2]
```diff
@@ -1459,14 +1459,15 @@ Transform3D Node3DEditorViewport::_compute_transform(TransformMode p_mode, const
...
+			} else {
+				t = p_original;
+				t.origin += p_motion;
 			}
 
-			// Apply translation
-			Transform3D t = p_original;
-			t.origin += p_motion;
-
 			return t;
```
Comment (kleonc) [inline editor/plugins/node_3d_editor_plugin.cpp:1471]: BTW there are dedicated methods for such operations, it could be simplified to e.g.:
```cpp
if (p_local) {
	return p_original_local.translated_local(p_motion);
} else {
	return p_original.translated(p_motion);
}

Comment (AThousandShips) [reply editor/plugins/node_3d_editor_plugin.cpp:1471]: Thank you! Will test that

**Review by kleonc — APPROVED** [review]
Seems to be working fine. :upside_down_face:

**Comment by kleonc** [comment]
Removed `cherrypick:4.1`, it's 4.2.dev4 specific regression.

**Comment by AThousandShips** [comment]
Have you tested that this doesn't happen in 4.1? The code is the same

**Comment by kleonc** [comment]
> Have you tested that this doesn't happen in 4.1? The code is the same

Tested v4.1.1.stable.official [bd6af8e0e], and 4.2.dev1/2/3/4 versions. The issue only happened in 4.2.dev4.

**Comment by AThousandShips** [comment]
You're right, some other change there interact with it

Will take a look at making a pass over it to see how it interacts with itself and see if the discrepencies can be identified, but the current behavior is so glaring I feel it's best to get it fixed

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 3]
```diff
@@ -1460,14 +1460,10 @@ Transform3D Node3DEditorViewport::_compute_transform(TransformMode p_mode, const
 			}
 
 			if (p_local) {
-				p_motion = p_original.basis.xform(p_motion);
+				return p_original_local.translated_local(p_motion);
+			} else {
+				return p_original.translated(p_motion);
 			}
```
Comment (TokageItLab) [inline editor/plugins/node_3d_editor_plugin.cpp:1466]:
```suggestion
				return p_original_local.translated_local(p_motion);
			}

			return p_original.translated(p_motion);
```

Comment (TokageItLab) [reply editor/plugins/node_3d_editor_plugin.cpp:1466]: For the safety of switch-case.

**Review by TokageItLab — APPROVED** [review]
I saw what it broke, but the problem is that translate is not converting correctly, which should be fixed in this PR. I tested this and it works fine.

https://github.com/godotengine/godot/issues/81604#issuecomment-1722174157

As for rotate the last argument does not match, but that is not a problem considering it is `&& true` since rotate does not have a plane transform so it will always be true.

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!
