### PR TITLE
Fix saving editor folder colors

### LINKED ISSUE #81342: Folder color is not retained after editor restart
### Godot version

4.2.dev.4

### System information

Windows 11

### Issue description

With the new feature in 4.2, user can color folder in different colors. You can change the color in the editor, and it reflects it in the file system dock.
When you restart the editor with the same project or reload the project the color changes to the folders are lost.

### Steps to reproduce

- Create a project
- Add a folder in the file system.
- Change the color of the folder by right clicking and setting the folder color.
- Now reload the project using menu `Project > Reload Current Project `or simply close the editor and reopen the project again.
- The color changes will be lost

### Minimal reproduction project

N.A

### PR DESCRIPTION
**Pull request by AThousandShips**
Also clears the setting if no folder is configured

If the addition of folder colors are added to the release blog post I think adding a note about it not currently working would be good

* Fixes: #81342

### CODE REVIEW

**Comment by KoBeWi** [comment]
I think you should check if the setting exists. Setting it is only needed when it doesn't.

**Comment by AThousandShips** [comment]
Am just about to push that change, was testing it out

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -2794,6 +2794,12 @@ void FileSystemDock::_folder_color_index_pressed(int p_index, PopupMenu *p_menu)
 		}
 	}
 
+	if (!ProjectSettings::get_singleton()->has_setting("file_customization/folder_colors")) {
+		ProjectSettings::get_singleton()->set_setting("file_customization/folder_colors", assigned_folder_colors);
+	} else if (assigned_folder_colors.is_empty()) {
+		ProjectSettings::get_singleton()->set_setting("file_customization/folder_colors", Variant());
```
Comment (AThousandShips) [inline editor/filesystem_dock.cpp:2800]: Can remove if wanted, but thought it'd be good to avoid taking up space in the settings if nothing is configured

**Review by KoBeWi — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!
