### PR TITLE
Fix incorrect bottom panel theming

### LINKED ISSUE #112611: Bottom panel theming is broken
### Tested versions

I suppose this is caused by https://github.com/godotengine/godot/pull/106164
cc @lodetrick 

### System information

Godot v4.6.dev (cb8e592b5) - Windows 10 (build 19045) - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3070 (NVIDIA; 32.0.15.8108) - AMD Ryzen 5 5600X 6-Core Processor (12 threads) - 31.94 GiB memory

### Issue description

https://github.com/user-attachments/assets/ff98e88f-7038-4260-ac9c-ed66839e285b

### Steps to reproduce

See above

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by lodetrick**
Closes #112611

Previously, if the editor theme was changed, the bottom panel's background would not be updated. This is because when the bottom panel retrieved the necessary stylebox it retrieved the overridden previous theme rather than the new theme. Removing the override is a simple method to force the retrieved stylebox to be correct.

I'm not too sure why it retrieved the override in the first place because overrides are specific to nodes but this method worked well.

### CODE REVIEW

**Comment by ryevdokimov** [comment]
Not sure how this should be addressed, but possibly related issue and a comment I made there: https://github.com/godotengine/godot/issues/112549#issuecomment-3508427026

https://github.com/godotengine/godot/blob/6fd949a6dcbda94140200633394f2b4b99de8f6f/editor/editor_node.cpp#L680

>Convention says this should be a private method, and shouldn't the bottom panel handle theme changes itself via the notification system? 

https://github.com/godotengine/godot/blob/6fd949a6dcbda94140200633394f2b4b99de8f6f/editor/gui/editor_bottom_panel.cpp#L89

>Having that method called on repaint (tab changed) as well seems strange. Hard to tell what is going on with a quick glance.

**Comment by KoBeWi** [comment]
Alternate fix is getting the theme stylebox either directly from theme (`EditorNode::get_editor_theme()->get_stylebox()`) or from another control (`EditorNode::get_gui_base()->get_theme_stylebox()`).

> I'm not too sure why it retrieved the override in the first place because overrides are specific to nodes

The override came from BottomPanel theme variation.

> possibly related issue and a comment I made there

It's not.

File: editor/gui/editor_bottom_panel.cpp [hunk 1]
```diff
@@ -56,6 +56,7 @@ void EditorBottomPanel::_on_tab_changed(int p_idx) {
 }
 
 void EditorBottomPanel::_theme_changed() {
+	remove_theme_style_override("tabbar_background");
 	Ref<StyleBox> bottom_tabbar_style = get_theme_stylebox("tabbar_background", "BottomPanel")->duplicate();
```
Comment (KoBeWi) [inline editor/gui/editor_bottom_panel.cpp]: Due to bottom panel having BottomPanel variation, this can be removed
```suggestion
	Ref<StyleBox> bottom_tabbar_style = get_theme_stylebox("tabbar_background")->duplicate();
```
(unless you use the alternate solution I mentioned)

**Review by KoBeWi — APPROVED** [review]

**Comment by lodetrick** [comment]
I ended up using the alternate solution you mentioned, it solved the issue nicely.

**Comment by Repiteo** [comment]
Thanks!
