### PR TITLE
Properly calculate binormal when creating SurfaceTool from arrays

### LINKED ISSUE #86131: Mirrored UVs break normal mapping
### Tested versions

Reproducible in 4.2.1

### System information

Windows 11, Vulkan, Forward+

### Issue description

Having mirrored UVs break normal mapping. I would expect Godot to correctly take mirrored UVs into account like other 3d software does. Not only does it not do that. it creates some very strange normal artifacts in the middle of polygons that I can't explain.

Here is a cube that has been mirrored and had an open gl normal map with a "bump" sphere shape applied to it in Blender:

Model:
image

With mirror modifier:
image

Normals work as expected:
https://github.com/godotengine/godot/assets/4955051/9b4a85bc-8656-4f7d-b9ec-d590dc0e1822

Here the box is imported as gltf into Godot:
https://github.com/godotengine/godot/assets/4955051/384aafbb-9760-4a66-968d-9b3bc014ca6c

As you can see the normals are not acting correctly when mirrored and there is for some reaons a strange artifact running down the middle of a polygon where no edge exist.
image
image

### Steps to reproduce

Open the MRP and observe the issue.

### Minimal reproduction project (MRP)

[mirror_uv_normalmap_issue.zip](https://github.com/godotengine/godot/files/13665636/mirror_uv_normalmap_issue.zip)

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/86131

I suspect that this will also fix some other subtle bugs.

This bug has existed in the SurfaceTool code for many many years. But it wasn't caught as there were very few situations where this code made a major impact. However, we started using `create_vertex_array_from_triangle_arrays()` in the default GLTF import path a few years ago. The result was that we ended up forcing the binormal sign of all GLTF meshes to 1.0. This is fine for most meshes, but the binormal sign is necessary when mirroring normal maps, so losing it totally broke those meshes. 

_edit: I have also pushed a related fix that ensures that the binormal sign is properly encoded when sending it to the shader. This fixes a related bug when using the compressed mesh format_

_Before:_
Screenshot from 2024-02-23 10-17-23
_After_
Screenshot from 2024-02-23 10-16-48

### CODE REVIEW

**Comment by fire** [comment]
Does U mirroring look correct to you?

**Review by fire — APPROVED** [review]
Overall the tests show that the geometry, normal and mirrored v looks correct. I think mirrored U is broken, but this is already an improvement even if incomplete.

File: scene/resources/surface_tool.cpp [hunk 1]
```diff
@@ -882,7 +882,7 @@ void SurfaceTool::create_vertex_array_from_triangle_arrays(const Array &p_arrays
 		if (lformat & RS::ARRAY_FORMAT_TANGENT) {
 			Plane p(tarr[i * 4 + 0], tarr[i * 4 + 1], tarr[i * 4 + 2], tarr[i * 4 + 3]);
```
Comment (fire) [inline scene/resources/surface_tool.cpp:883]: This is a Vector4. It is not a geometric plane.

**Comment by clayjohn** [comment]
> Overall the tests show that the geometry, normal and mirrored v looks correct. I think mirrored U is broken, but this is already an improvement even if incomplete.

Move the camera over to the right and mirrored U will look the same as the others

File: scene/resources/surface_tool.cpp (hunk 1 above)
Comment (clayjohn) [reply scene/resources/surface_tool.cpp]: I removed the Plane entirely

**Review by fire — APPROVED** [review]

File: servers/rendering_server.cpp [hunk 2]
```diff
@@ -340,7 +340,7 @@ void _get_axis_angle(const Vector3 &p_normal, const Vector4 &p_tangent, float &r
 	if (d < 0.0) {
 		r_angle = CLAMP((1.0 - r_angle / Math_PI) * 0.5, 0.0, 0.49999);
 	} else {
-		r_angle = (r_angle / Math_PI) * 0.5 + 0.5;
+		r_angle = CLAMP((r_angle / Math_PI) * 0.5 + 0.5, 0.500008, 1.0);
```
Comment (Calinou) [inline servers/rendering_server.cpp:343]: Out of curiosity, where does that `0.500008` come from? It might be worth adding a comment.

Comment (clayjohn) [reply servers/rendering_server.cpp:343]: Its the smallest number representable by a 16 bit UNORM value in the range 0.5 - 1.0.

Its the flipside of `0.49999` above.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Comment by jitspoe** [comment]
Seems to fix some of my problem cases.  Thanks a bunch!
