### PR TITLE
Check parameter validity in `Object::set_script`

### LINKED ISSUE #46120: Crash, when using set_script and emit_signal on AnimatedSprite
**Godot version:**
Godot 3.2.4 rc 2

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
When executing 
```
extends Node2D

var q_AnimatedSprite : AnimatedSprite = AnimatedSprite.new()

func _ready() -> void:
	add_child(q_AnimatedSprite)

func _process(_delta : float) -> void:

	if randi() % 2 == 0:
		print("Executing AnimatedSprite::set_script")

		var p_object_0 = Reference.new()
		q_AnimatedSprite.set_script(p_object_0)

	if randi() % 2 == 0:
		print("Executing AnimatedSprite::emit_signal")

		q_AnimatedSprite.emit_signal("")

```
Godot crashes and shows this backtrace
```
core/object.cpp:1490:46: runtime error: member call on null pointer of type 'struct Script'
core/object.cpp:1490:46: runtime error: member access within null pointer of type 'struct Script'
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f1b6f4b5210] (??:0)
[2] Object::emit_signal(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot3.2/core/object.cpp:1192 (discriminator 12))
[3] Object::_emit_signal(Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot3.2/core/object.cpp:1179)
[4] MethodBindVarArg<Object>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot3.2/./core/method_bind.h:345 (discriminator 4))
[5] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot3.2/core/object.cpp:919 (discriminator 1))
[6] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot3.2/core/variant_call.cpp:1129 (discriminator 1))
[7] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot3.2/modules/gdscript/gdscript_function.cpp:1089)
[8] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot3.2/modules/gdscript/gdscript.cpp:1254)
[9] Node::_notification(int) (/home/rafal/Pulpit/godot3.2/scene/main/node.cpp:58)
[10] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot3.2/./scene/main/node.h:46 (discriminator 14))
[11] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot3.2/./scene/2d/canvas_item.h:166 (discriminator 3))
[12] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot3.2/./scene/2d/node_2d.h:38 (discriminator 3))
[13] Object::notification(int, bool) (/home/rafal/Pulpit/godot3.2/core/object.cpp:931)
[14] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot3.2/scene/main/scene_tree.cpp:988)
[15] SceneTree::idle(float) (/home/rafal/Pulpit/godot3.2/scene/main/scene_tree.cpp:528 (discriminator 3))
[16] Main::iteration() (/home/rafal/Pulpit/godot3.2/main/main.cpp:2113)
[17] OS_X11::run() (/home/rafal/Pulpit/godot3.2/platform/x11/os_x11.cpp:3634)
[18] /usr/bin/godot(main+0x125) [0x16e0bfb] (/home/rafal/Pulpit/godot3.2/platform/x11/godot_x11.cpp:57)
[19] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f1b6f4960b3] (??:0)
[20] /usr/bin/godot(_start+0x2e) [0x16e0a1e] (??:?)
```

### PR DESCRIPTION
**Pull request by angad-k**
fixes #46120

### CODE REVIEW

File: core/object/object.cpp [hunk 1]
```diff
@@ -823,14 +823,16 @@ void Object::set_script(const Variant &p_script) {
 		return;
 	}
 
+	Ref<Script> s = script;
+	ERR_FAIL_COND(s.is_null());
```
Comment (akien-mga) [inline core/object/object.cpp:827]: I don't think that's the correct fix, assigning an empty/null `Script` to `script` is valid, that's how you would remove a script. You'll probably get errors if you try to unassign a script from a node in the inspector now.

Search for `script` in this file, there's lots of occurrences where the validity of the script is checked before using it, so that's a supported use case. The crash must be somewhere more specific and that's where it should be fixed.

Comment (angad-k) [reply core/object/object.cpp:827]: Ok cool I'll look into it and get back to you

Comment (angad-k) [reply core/object/object.cpp]: Hey!  I have made the changes. The code was failing because if a reference was passed that wasn't pointing to a script, it wasn't getting detected. So, now I have set the error condition such that only invalid references as arguments will trigger an error and not a null argument

**Review by theraot — APPROVED** [review]

**Comment by theraot** [comment]
*I tested and reviewed this without a keyboard so I didn't leave a message.*

I vow that the bug still happens, and this change fixes it. I did test both setting something that is not a script, which result in an error, and setting null, which does not.

**Review by RandomShaper — APPROVED** [review]

File: core/object/object.cpp [hunk 2]
```diff
@@ -823,14 +823,16 @@ void Object::set_script(const Variant &p_script) {
 		return;
 	}
 
+	Ref<Script> s = p_script;
+	ERR_FAIL_COND(s.is_null() && !p_script.is_null());
```
Comment (akien-mga) [inline core/object/object.cpp:827]:
```suggestion
	ERR_FAIL_COND_MSG(s.is_null() && !p_script.is_null(), "Invalid parameter, it should be a reference to a valid script (or null).");
```

**Comment by akien-mga** [comment]
Rebased and improved the error message as suggested above.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.1.

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.
