### PR TITLE
Hide redundant categories from project settings

### LINKED ISSUE #24453: Autoloads can be overridden in General tab of Project Settings causing duplicate nodes in the scene tree.
**Godot version:**
Godot 3.1 alpha 3

**OS/device including version:**
All

**Issue description:**
Setting an override for an autoload from the general tab of the project settings or in project.godot overrides the script used by the autoload (you are not supposed to be able to override autoloads) but also results in multiple nodes with the same script (the override script) being added to the scene tree at runtime.
This is a follow up from #24054, see there for more details.

**Steps to reproduce:**

1. Add an autoload
2. Go to General/Autoload (if the Autoload section isn't there then close and reopen the project settings)
3. Override the autoload (debug works best to demonstrate)
screenshot from 2018-12-11 18-34-14
4. Run the game and look at the remote scene tree
screenshot from 2018-12-11 18-13-09
5. Check the scripts on the nodes. The override works.

### LINKED ISSUE #39639: Autoload names are incorrect in Project Settings under Filesystem
**Godot version:**
3.2.1.stable.official
**OS/device including version:**
Windows 10 Home 1909
**Issue description:**
I have an autoloaded scene and an autoloaded script. At Project --> Project Settings --> Filesystem --> Autoload the names I've given the autoload singeltons are different.
Screenshot (70)
Screenshot (69)
**Steps to reproduce:**

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by KoBeWi**
Salvage of #39670 with some extras. Aside from Autoloads, it hides Editor Plugins and Shader Globals:
image
(they have their own tabs too)

Fixes #39639
Fixes #24453

### CODE REVIEW

**Review by fire-forge — APPROVED** [review]

File: editor/editor_sectioned_inspector.cpp [hunk 1]
```diff
@@ -250,6 +250,11 @@ void SectionedInspector::update_category_list() {
 			continue;
 		}
 
+		// Filter-out unnecessary ProjectSettings sections.
```
Comment (Calinou) [inline editor/editor_sectioned_inspector.cpp:253]:
```suggestion
		// Filter-out unnecessary ProjectSettings sections.
		// These are already covered by the AutoLoad, Plugins and Shader Globals tabs of the project settings dialog.
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by KoBeWi** [comment]
This could've been done better actually. Inspector will automatically hide properties that don't have PROPERTY_USAGE_EDITOR, so a better solution would be removing this flag from these properties.
