### PR TITLE
Wayland: Workaround tooltip issues 

### LINKED ISSUE #107438: Wayland editor documentation popups appear on screen's edge and generate errors
### Tested versions

- Reproducible in v4.5.dev.custom_build [3b963ab8b]
- Has been happening for some time before that commit too (about a week? I haven't tried bisecting)

### System information

Godot v4.5.dev (d9cd011e2) - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Wed, 14 May 2025 14:56:34 +0000 on Wayland - Wayland display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XT (RADV NAVI31) - AMD Ryzen 9 7900X 12-Core Processor (24 threads) - 30.49 GiB memory

### Issue description

Every time a class or function is hovered and its documentation popup appears, the popup is placed against the screen's right edge, and the following error is displayed in the output panel:
```
ERROR: platform/linuxbsd/wayland/display_server_wayland.cpp:1052 - Condition "p_window_id != MAIN_WINDOW_ID" is true. Returning: INVALID_SCREEN
```
This error points [to this function](https://github.com/godotengine/godot/blob/master/platform/linuxbsd/wayland/display_server_wayland.cpp#L1051-L1055).
In the following screenshot, I am hovering the `rotated` method:

Image

### Steps to reproduce

Open any script, hover a documented class or function (custom or built-in).

Note that disabling multi-window support (or enabling single window mode) causes the popup to appear at the correct location, but still generates the error.

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #108443: Wayland error spam when hovering over anything with a tooltip
### Tested versions

- Reproducible in 4.5 beta 1-3
- Not reproducible in 4.5 dev 1-5

### System information

Godot v4.5.beta3.mono - CachyOS Linux #1 SMP PREEMPT_DYNAMIC Sun, 06 Jul 2025 09:33:29 +0000 on Wayland - Wayland display driver, Multi-window, 2 monitors - OpenGL 3 (Compatibility) - AMD Radeon RX 6600 (radeonsi, navi23, LLVM 20.1.7, DRM 3.63, 6.15.5-2-cachyos) - AMD Ryzen 7 5700G with Radeon Graphics (16 threads) - 31.22 GiB memory

### Issue description

This error message occurs in the editor when hovering over anything that has a tooltip e.g. buttons, files in the FileSystem dock.

ERROR: platform/linuxbsd/wayland/display_server_wayland.cpp:1052 - Condition "p_window_id != MAIN_WINDOW_ID" is true. Returning: INVALID_SCREEN

### Steps to reproduce

NA

### Minimal reproduction project (MRP)

NA

### PR DESCRIPTION
**Pull request by deralmas**
Fixes #107438.
Fixes #108443.

Best seen with "hide whitespace".

Two commits because one is literally a one-liner :P

Mostly "correctness" improvements (both checks should've been there in the first place), although an even more correct fix I'm working on is to properly handle `INVALID_SCREEN` throughout the whole codebase as discussed in #107438.

### CODE REVIEW

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -1678,26 +1678,28 @@ void Viewport::_gui_show_tooltip_at(const Point2i &p_pos) {
 	r.size = r.size.ceil();
 	r.size = r.size.min(panel->get_max_size());
 
-	if (r.size.x + r.position.x > vr.size.x + vr.position.x) {
-		// Place it in the opposite direction. If it fails, just hug the border.
-		r.position.x = gui.tooltip_pos.x - r.size.x - tooltip_offset.x;
+	if (!DisplayServer::get_singleton()->has_feature(DisplayServer::FEATURE_SELF_FITTING_WINDOWS)) {
```
Comment (bruvzg) [inline scene/main/viewport.cpp]:
```suggestion
	if (!DisplayServer::get_singleton()->has_feature(DisplayServer::FEATURE_SELF_FITTING_WINDOWS) || gui.tooltip_popup->is_embedded()) {
```

File: editor/doc/editor_help.cpp [hunk 2]
```diff
@@ -4655,26 +4655,28 @@ void EditorHelpBitTooltip::popup_under_cursor() {
 		vr = window->get_usable_parent_rect();
 	}
 
-	if (r.size.x + r.position.x > vr.size.x + vr.position.x) {
-		// Place it in the opposite direction. If it fails, just hug the border.
-		r.position.x = mouse_pos.x - r.size.x - tooltip_offset.x;
+	if (!DisplayServer::get_singleton()->has_feature(DisplayServer::FEATURE_SELF_FITTING_WINDOWS)) {
```
Comment (bruvzg) [inline editor/doc/editor_help.cpp]:
```suggestion
	if (!DisplayServer::get_singleton()->has_feature(DisplayServer::FEATURE_SELF_FITTING_WINDOWS) || is_embedded()) {
```

**Review by bruvzg — COMMENTED** [review]
`DisplayServer::FEATURE_SELF_FITTING_WINDOWS` should not affect embedded windows, otherwise seems fine.

File: scene/main/viewport.cpp (hunk 1 above)
Comment (deralmas) [reply scene/main/viewport.cpp]: Great catch! I already did this mistake once, oof.

Comment (deralmas) [reply scene/main/viewport.cpp]: Done!

File: editor/doc/editor_help.cpp (hunk 2 above)
Comment (deralmas) [reply editor/doc/editor_help.cpp]: Done!

**Review by bruvzg — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
