### PR TITLE
Fix tooltips behaving incorrectly on `Tree` nodes

### LINKED ISSUE #80398: Minor Issue - Tooltips are not Reactivating Correctly Upon Hover Over new Items in the Tree Control (Node and Filesystem Panes)
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Compatibility) - NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.14.7311) - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 Threads)

### Issue description

In the _Inspector_ tab the tooltip continuously tracks the mouse position and resets once it is no longer over the rect for the control that a tooltip is currently being shown for, and awaits a new hover event to be shown again for a new control.  This also behaves similarly in the _History_ tab.

However, in the _Node_ tab, the tooltip is not reset once the mouse leaves the rect of the underlying tree item and will continue to show the old/incorrect content even though the user has moved to something else.  You have to move the mouse outside of the _Node_ tab's tree control's rect and then back in again in order to get a new, refreshed tooltip.

This might be an issue with the tree control being used if it is not generating hover events correctly (or however it works internally) because the tree control used on the _Filesystem_ tab has similar behavior.

The tooltip should respond to new hover events as they are generated from the tree control (or respond to the mouse being moved over the rect of a new item) and refresh with new content without having to leave the client area of the entire tree control.  

This should be possible because the tree control used on the _Scene_ pane _kinda-sorta-almost_ works as expected: if you move to another item, the tooltop does not immediately update, but seems to wait for a new hover event and then is updated.  Not perfect, but definitely better than how the _Node_ pane's tree behaves.

N.b. - although this issue talks about multiple panes, and the recreation scenario also uses multiple panes to demonstrate the differing behaviors, I believe the problem is with the underlying tree control itself, which I believe qualifies as the **one bug** discussed in this issue: **Tooltips do not work correctly in the tree control**.

### Steps to reproduce

In Godot, select any Node in the _Scene_ pane and go to the _Node_ tab.  Hover over an item in the _Node_ pane's tree control and them move the mouse to another item and hover.  The tooltip will not update to reflect the new item being hovered over.

Now activate the _Inspector_ pane and try again.  On this pane, the tooltip updates as you move to different items on that pane.

Try those steps again with the tree on the _Filesystem_ pane and again with the tree on the _Scene_ pane and notice the different behaviors.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by YeldhamDev**
Tooltips within `Tree` nodes behave awkwardly on Godot 4. Normal ones don't disappear when switching to another item, and custom ones don't even update at all. This PR fixes both cases.

### CODE REVIEW

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -1467,12 +1469,13 @@ void Viewport::_gui_show_tooltip() {
...
 			gui.tooltip_control,
 			gui.tooltip_control->get_global_transform().xform_inv(gui.last_mouse_pos),
 			&tooltip_owner);
-	tooltip_text = tooltip_text.strip_edges();
-	if (tooltip_text.is_empty()) {
+	gui.tooltip_text = gui.tooltip_text.strip_edges();
+
+	if (gui.tooltip_text.is_empty()) {
 		return; // Nothing to show.
 	}
```
Comment (YuriSizov) [inline scene/main/viewport.cpp:1481]: I noticed something unrelated but worth fixing. Below this line we're memdeleting the tooltip popup, but we never `nullptr` the reference to `gui.tooltip_popup`. And that's despite the method having a path with an early return immediately after. So we can end up with garbage in `gui.tooltip_popup`.

If you could add `gui.tooltip_popup = nullptr` after the deletion here, it would be great!

**Review by YuriSizov — APPROVED** [review]
A think this makes sense. There is definitely a visible usability improvement, the only question is whether this may lead to some regressions and excessive updates for some tooltip. But I couldn't notice anything from a quick test with the editor.

**Old**

https://github.com/godotengine/godot/assets/11782833/24a14935-3301-4552-bac9-3fd037622dbc

**New**

https://github.com/godotengine/godot/assets/11782833/88fbdd3d-b9b9-42a2-a458-4481850dd3b6

File: scene/main/viewport.cpp (hunk 1 above)
Comment (YeldhamDev) [reply scene/main/viewport.cpp:1484]: Done.

**Comment by YeldhamDev** [comment]
@YuriSizov Well, the way it works is still the same, string comparison. The only difference is that now it's a little more sophisticated.

**Comment by YuriSizov** [comment]
I'm not so worried about string comparison performance. What I meant is that this changes when we request an update for the tooltip itself. If this somehow could lead to more updates to it when previously and than needed, this would be a performance problem. But we'll see.

**Comment by YeldhamDev** [comment]
From my tests, it only triggers updates when the tooltip string itself changes, which is what we want to do.

**Comment by YuriSizov** [comment]
Thanks!
