### PR TITLE
In Create New Scene dialog derive the default root node name based on `editor/naming/node_name_casing`

### LINKED ISSUE #79751: When creating a new scene the default root node name doesn't respect the `editor/naming/node_name_casing` project setting
### Godot version

4.1.stable

### System information

Windows 11

### Issue description

The Create New Scene dialog always defaults the scene root node name to the filename. If you're following the recommended (and default) naming conventions for filenames (snake_case) and node names (PascalCase), this default name always needs to be changed. It would be lovely if the default root node name respected the `editor/naming/node_name_casing` project setting.

Also, I have already implemented this in my fork and would be happy to contribute it. This was my "dip my toes" into Godot engine development idea since it was simple and has bothered me for a while. I consider this more of an oversight bug than a feature proposal which is why I'm opening the issue here instead of on the proposals repo.

### Steps to reproduce

1. Create and open new project
2. (only if you've changed this) In project settings set `editor/naming/node_name_casing` to PascalCase
3. In Filesystem view, right click | Create new | Scene
4. Enter a filename like "test_scene" and click Ok

Notice the root node of the new scene will also be named "test_scene" instead of "TestScene"

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by sfreed141**
Fixes #79751 

This PR updates the Create New Scene dialog to respect the `editor/naming/node_name_casing` project setting for the root node name (when it's left empty). I also updated the placeholder text to be more accurate, as well as add a tooltip to the line edit control with more information (so users can discover the project setting if they aren't aware of it yet)

### CODE REVIEW

**Comment by sfreed141** [comment]
(force push was to fix style issue)

**Comment by dalexeev** [comment]
The static method `Node::adjust_name_casing()` with the functionality already exists.

https://github.com/godotengine/godot/blob/6588a4a29af1621086feac0117d5d4d37af957fd/scene/main/node.cpp#L1199-L1209

Also note that the `to_pascal_case()` method does not respect specific abbreviations (e.g. `Node2D` is converted to `Node2d`). See #67219 for details.

**Comment by sfreed141** [comment]
Thanks for the info @dalexeev, I'll update the PR to use `Node::adjust_name_casing`!

 > Also note that the to_pascal_case() method does not respect specific abbreviations (e.g. Node2D is converted to Node2d)
I was wondering about these edge cases too, but since it's quite simple to change the name after the fact (or in the Create New Scene dialog) I'm not concerned about it. This PR should still improve the majority of cases (since the current workflow essentially requires you to rename everything manually, assuming a difference in naming convention between  filenames and node names).

One way to address that could be to show the converted name as placeholder text in realtime (as the scene name is modified). This way a user would be able to see if the name is converted as expected and, if needed, manually enter a name. Thoughts?

**Comment by dalexeev** [comment]
* See #67219.

https://github.com/godotengine/godot/blob/6588a4a29af1621086feac0117d5d4d37af957fd/editor/scene_tree_dock.cpp#L2277-L2281

The built-in classes are already named in PascalCase with the correct capitalization, so it's probably justified to do nothing for the PascalCase option.

CC @KoBeWi

**Comment by sfreed141** [comment]
@dalexeev I'm confused what you mean here. This PR is unrelated to the capitalization of built-in classes. Perhaps a screenshot will make this more clear:
image
image
This PR is automatically adjusting the Root Name to respect the `node_name_casing` option (the prior behavior was copying the Scene Name).

Also I'm pushing an update to use `adjust_name_casing` and show the derived name in the placeholder text.

**Comment by dalexeev** [comment]
@sfreed141 Sorry, I confused this with another issue, since I don't use the dialog, but just press the plus button to add an empty scene tab. Then I think that it makes sense to capitalize as is, with `to_pascal_case()`. Showing a preview of the generated name is a good idea, thank you!

Please squash your commits into one with a suitable message, according to [the docs](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase).

File: editor/scene_create_dialog.cpp [hunk 1]
```diff
@@ -30,6 +30,7 @@
 
 #include "scene_create_dialog.h"
 
+#include "core/config/project_settings.h"
```
Comment (dalexeev) [inline editor/scene_create_dialog.cpp:33]: This `#include` is no longer needed as you are now using `Node::adjust_name_casing()` instead of `GLOBAL_GET()`.

File: editor/scene_create_dialog.cpp [hunk 2]
```diff
@@ -131,6 +132,18 @@ void SceneCreateDialog::update_dialog() {
 	root_name = root_name_edit->get_text().strip_edges();
 	if (root_name.is_empty()) {
 		root_name = scene_name.get_file().get_basename();
+
+		if (root_name.is_empty())
+		{
```
Comment (dalexeev) [inline editor/scene_create_dialog.cpp:137]: Please bring the code in line with [style guidelines](https://docs.godotengine.org/en/stable/contributing/development/code_style_guidelines.html). You can use `clang-format` to auto-format.

File: editor/scene_create_dialog.cpp [hunk 3]
```diff
@@ -131,6 +132,18 @@ void SceneCreateDialog::update_dialog() {
...
+			// If the user clears the scene name make sure we reset the placeholder text
```
Comment (AThousandShips) [inline editor/scene_create_dialog.cpp:138]:
```suggestion
			// If the user clears the scene name make sure we reset the placeholder text.
```
And same below

**Comment by sfreed141** [comment]
Thanks for the feedback @dalexeev and @AThousandShips, the changes have been made and pushed.

File: editor/scene_create_dialog.cpp [hunk 4]
```diff
@@ -285,7 +294,8 @@ SceneCreateDialog::SceneCreateDialog() {
 
 		root_name_edit = memnew(LineEdit);
 		gc->add_child(root_name_edit);
-		root_name_edit->set_placeholder(TTR("Leave empty to use scene name"));
+		root_name_edit->set_placeholder(TTR("Leave empty to derive from scene name"));
+		root_name_edit->set_tooltip_text(TTR("When empty, the root node name is derived from the scene name based on the \"editor/naming/node_name_casing\" project setting"));
```
Comment (dalexeev) [inline editor/scene_create_dialog.cpp:298]:
```suggestion
		root_name_edit->set_tooltip_text(TTR("When empty, the root node name is derived from the scene name based on the \"editor/naming/node_name_casing\" project setting."));
```

**Review by dalexeev — DISMISSED** [review]
Looks good to me and works great!

**Comment by KoBeWi** [comment]
Displaying final root name is something I had on my TODO list, so it's nice to see it being implemented.

I wonder if the name could be validated though. E.g. if you name your scene like this:
image
You will get this:
image
We already lack a warning if you put invalid root name that's going to be renamed, so it's something that could be fixed later though.

File: editor/scene_create_dialog.cpp [hunk 5]
```diff
@@ -131,6 +131,15 @@ void SceneCreateDialog::update_dialog() {
 	root_name = root_name_edit->get_text().strip_edges();
 	if (root_name.is_empty()) {
 		root_name = scene_name.get_file().get_basename();
+
+		if (root_name.is_empty()) {
+			// If the user clears the scene name make sure we reset the placeholder text.
```
Comment (KoBeWi) [inline editor/scene_create_dialog.cpp:136]: If you remove the other `set_placeholder()` line, this comment should be reworded or removed.

**Comment by sfreed141** [comment]
@KoBeWi @dalexeev thanks for the suggestions, I'll incorporate those into this PR. A question though: if the derived name contains invalid values is there a precedent for how to display that? Right now I'm thinking of having the placeholder text start with a "⚠️" and have the tooltip say that invalid node name characters have been replaced with an "_". Thoughts?

**Comment by KoBeWi** [comment]
You could add a yellow warning message in the validation panel.

**Comment by sfreed141** [comment]
(forgot a period)

File: editor/scene_create_dialog.cpp [hunk 6]
```diff
@@ -131,6 +131,22 @@ void SceneCreateDialog::update_dialog() {
...
+			bool has_invalid_characters = root_name != adjusted_root_name;
+			if (has_invalid_characters) {
+				update_error(node_error_label, MSG_WARNING, TTR("Invalid root node name characters replaced with \"_\"."));
+			}
+
+			root_name_edit->set_placeholder(root_name);
+		}
 	}
 
 	if (root_name.is_empty() || root_name.validate_node_name().size() != root_name.size()) {
```
Comment (dalexeev) [inline editor/scene_create_dialog.cpp:152]:
```suggestion
	if (root_name.is_empty() || root_name.validate_node_name() != root_name) {
```

Prior to #75760 `validate_node_name()` removed invalid characters rather than replacing them with underscores. So now this check is not working correctly.

File: editor/scene_create_dialog.cpp [hunk 7]
```diff
@@ -131,6 +131,22 @@ void SceneCreateDialog::update_dialog() {
 	root_name = root_name_edit->get_text().strip_edges();
 	if (root_name.is_empty()) {
 		root_name = scene_name.get_file().get_basename();
+
+		// Set the placeholder text.
```
Comment (dalexeev) [inline editor/scene_create_dialog.cpp:135]: This block not only sets the placeholder, but it also generates the root name and sets the warning, so the comment is a bit confusing in my opinion.

File: editor/scene_create_dialog.cpp (hunk 6 above)
Comment (sfreed141) [reply editor/scene_create_dialog.cpp:152]: Good catch! I think I'll add a `has_invalid_node_name_characters()` method to the `String` class, since I don't like how current approach relies on implementation details of `validate_node_name()`.

Comment (dalexeev) [reply editor/scene_create_dialog.cpp:152]: Perhaps we need `is_valid_node_name()` method, in addition to `validate_node_name()`. This would be consistent with `is_valid_identifier()` and `validate_identifier()` pair (the second is not exposed to scripting, see #67701). But I think that this is more of a material for a separate PR. As part of this PR, the `name.validate_node_name() != name` check looks OK to me.

File: editor/scene_create_dialog.cpp [hunk 8]
```diff
@@ -131,9 +131,24 @@ void SceneCreateDialog::update_dialog() {
 	root_name = root_name_edit->get_text().strip_edges();
 	if (root_name.is_empty()) {
 		root_name = scene_name.get_file().get_basename();
```
Comment (dalexeev) [inline editor/scene_create_dialog.cpp:133]: I hope this is the last one. Sorry for the many rounds of the review.

```suggestion
		root_name = scene_name_edit->get_text().strip_edges();
```

**Review by dalexeev — APPROVED** [review]
Looks good to me. Thanks for your patience!

File: editor/scene_create_dialog.cpp (hunk 8 above)
Comment (dalexeev) [reply editor/scene_create_dialog.cpp]: Note that subfolders are not supported by this field. But it is not related to this PR.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
