### PR TITLE
Fix `ScrollBar` grabber mouse input ignores scroll content margins.

### LINKED ISSUE #98004: ScrollBar StyleBoxTexture Grabber only half usable?
### Tested versions

Reproducible in:
  - v4.3.stable.official [77dcf97d8]
  - v4.2.stable.official [46dc27791]
  - v4.1

### System information

Godot v4.3.stable - Ubuntu 24.04.1 LTS 24.04 - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (RADV NAVI23) - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads)

### Issue description

When using StyleBoxTexture for scroll bar only half the grabber is usable. The other half just click thru the grabber onto bar.
Screenshot from 2024-10-09 00-21-20

Thanks.

### Steps to reproduce

- make a scroll bar use StyleBoxTexture from theme.
- grab.

### Minimal reproduction project (MRP)

https://github.com/rakkarage/test-scrollbar-grabber

### PR DESCRIPTION
**Pull request by WhalesState**
* Fixes: https://github.com/godotengine/godot/issues/98004

Fixes this, the grab area now will respect the left and top content margins.

image

Also ignoring the focus style content margins and using only the scroll style's one, to prevent the grabber from changing it's position when focused.

Before:

https://github.com/user-attachments/assets/86948e48-1478-4dec-92c1-c0a165cce8fc

After:

https://github.com/user-attachments/assets/13eb758a-1c92-4741-adc1-cbe4cf87b4a7

### CODE REVIEW

**Review by bruvzg — COMMENTED** [review]
Grab area seems to be still a bit off (red area works, the rest is still click-through):

Screenshot 2024-10-10 at 09 18 01

**Comment by WhalesState** [comment]
> Grab area seems to be still a bit off (red area works, the rest is still click-through):

The MRP project that he have added includes expand margin for both left and right, if you check it again, you will see that it's actually centered but the first and last 8 pixels can't be clicked. please test with this MRP after removing the expand margins 
[test-scrollbar-grabber-main.zip](https://github.com/user-attachments/files/17328664/test-scrollbar-grabber-main.zip) .

**Comment by Mickeon** [comment]
Why was this closed? Either way, this looks entirely salvageable.

**Comment by Zireael07** [comment]
@Mickeon Guy closed all his PRs over fears of Github censorship, or that's what I got from his a bit rambly reply on another PR

**Comment by KoBeWi** [comment]
I don't see any difference with and without this PR. The original MRP is still broken, the new MRP works properly without the fix. It would be nice to see some project that works incorrectly on master, but is fixed by this PR.

File: scene/gui/scroll_bar.cpp [hunk 1]
```diff
@@ -248,8 +248,6 @@ void ScrollBar::_notification(int p_what) {
 				incr = theme_cache.increment_icon;
 			}
 
-			Ref<StyleBox> bg = has_focus() ? theme_cache.scroll_focus_style : theme_cache.scroll_style;
```
Comment (KoBeWi) [inline scene/gui/scroll_bar.cpp:251]: Why this change?

File: scene/gui/scroll_bar.cpp [hunk 2]
```diff
@@ -93,7 +93,7 @@ void ScrollBar::gui_input(const Ref<InputEvent> &p_event) {
 				return;
 			}
 
-			ofs -= decr_size;
+			ofs -= decr_size + (orientation == VERTICAL ? theme_cache.scroll_style->get_margin(SIDE_TOP) : theme_cache.scroll_style->get_margin(SIDE_LEFT));
```
Comment (KoBeWi) [inline scene/gui/scroll_bar.cpp:96]:
```suggestion
			ofs -= decr_size;
			if (orientation == VERTICAL) {
				ofs -= theme_cache.scroll_style->get_margin(SIDE_TOP);
			} else {
				ofs -= theme_cache.scroll_style->get_margin(SIDE_LEFT);
			}
```
More readable.

**Comment by WhalesState** [comment]
> I confirmed that this fixes a bug, but not the linked issues.
> 
> Though there are some changes that I'm not sure about. Removing `bg` makes the margins of focus StyleBox ignored.

You can define the margins inside an empty stylebox, just test again in the current godot's dev branch with a focus margin that has some content margins and you will see the grabber runs into a new position after you grab it.

**Comment by WhalesState** [comment]
> I don't see any difference with and without this PR. The original MRP is still broken, the new MRP works properly without the fix. It would be nice to see some project that works incorrectly on master, but is fixed by this PR.

image

This issue was mentioned in the linked issue, also i have helped him to fix the original issue. so we can close the issue after merging it.

**Review by KoBeWi — APPROVED** [review]
Makes sense.

File: scene/gui/scroll_bar.cpp (hunk 2 above)
Comment (Repiteo) [reply scene/gui/scroll_bar.cpp:96]: Alternatively
```suggestion
			ofs -= decr_size + theme_cache.scroll_style->get_margin(orientation == VERTICAL ? SIDE_TOP : SIDE_LEFT);
```

File: scene/gui/scroll_bar.cpp [hunk 3]
```diff
@@ -151,7 +151,7 @@ void ScrollBar::gui_input(const Ref<InputEvent> &p_event) {
 			Ref<Texture2D> decr = theme_cache.decrement_icon;
 
 			double decr_size = orientation == VERTICAL ? decr->get_height() : decr->get_width();
-			ofs -= decr_size;
+			ofs -= decr_size + (orientation == VERTICAL ? theme_cache.scroll_style->get_margin(SIDE_TOP) : theme_cache.scroll_style->get_margin(SIDE_LEFT));
```
Comment (KoBeWi) [inline scene/gui/scroll_bar.cpp:154]: Same here.

**Comment by Repiteo** [comment]
Thanks!
