### PR TITLE
Fix non uniform scaling normals in 3D objects

### LINKED ISSUE #49862: Vulkan: StandardMaterial3D doesn't have an `ensure_correct_normals` property like 3.x's SpatialMaterial did
### Godot version

4.0.dev (6d98f84ab)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 465.31)

### Issue description

While investigating https://github.com/godotengine/godot/issues/49861, I noticed that StandardMaterial3D doesn't have a way to force the computation of normal scaling in real-time. This is useful when using non-uniformly scaled meshes, especially when their scale changes non-uniformly at run-time.

While this property has a performance cost, you don't always have an alternative since regenerating a mesh's normals is very costly to do at run-time on a complex mesh.

I think we should look into reimplementing it, or at least providing an add-on ShaderMaterial for it.

### Steps to reproduce

- Create a StandardMaterial3D resource in the inspector and notice that there's no equivalent to `3.x` SpatialMaterial's **Ensure Correct Normals**.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by reduz**
* Flag was there, but not implemented.
* Fixed issue with base flags not being initialized.

*Bugsquad edit:* Fixes #49862.

### CODE REVIEW

File: servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.h [hunk 1]
```diff
@@ -184,6 +184,7 @@ class RenderForwardClustered : public RendererSceneRenderRD {
 	};
 
 	enum {
+		INSTANCE_DATA_FLAGS_NON_UNIFORM_SCALE = 1 << 5,
```
Comment (reduz) [inline servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.h:187]: Just in case you wonder about this change, I will use the upper 8 bits for something else soon.

**Review by JFonS — APPROVED** [review]

**Comment by Calinou** [comment]
Does this fix https://github.com/godotengine/godot/issues/49862?

**Comment by reduz** [comment]
@Calinou yes, this fixes it.

**Comment by akien-mga** [comment]
Thanks!
