### PR TITLE
Fix #24137 Different number of leading zeros on MINGW printf("%lg")

### LINKED ISSUE #24137: Different number of leading zeros in scientific notation exponent recorded in TSCN file in Windows versus Linux
**Godot version:**
v3.0.6.stable.official.8314054 for Windows
Same-ish v3.0.6 build for Linux

**Issue description:**
Opening and resaving a scene file with values containing scientific notation have equivalent numeric values written slightly different (two digits places instead of three).

**Linux:**
transform = Transform( 1, -1.12852e-06, 9.19296e-14, 9.19296e-14, 1.62921e-07, 1, -1.12852e-06, -1, 1.62921e-07, 0, 45, 0 )

**Windows:**
transform = Transform( 1, -1.12852e-006, 9.19296e-014, 9.19296e-014, 1.62921e-007, 1, -1.12852e-006, -1, 1.62921e-007, 0, 45, 0 )

It's expected that these values written as strings should be equivalent with string comparisons, as not to trigger unnecessary file changes in a version control system.

**Steps to reproduce:**
 - Launch Godot Editor and a project in Linux.
 - Add nodes to scene, adjusting their translation and rotation until their corresponding transform in that scene's TSCN file contains components written with scientific notation. Should probably see "e-00n" with two zeros or total of three digit places.
 - Save scene. Close Godot Editor.
 - Open Godot Editor in Windows.
 - Open previous project.
 - Move a component that has a transform with components written with scientific notation.
 - Undo that movement.
 - Save scene.
 - Observe that the components written with scientific notation have two digit places instead of three.

### PR DESCRIPTION
**Pull request by jamie-pate**
Use _set_output_format() on MINGW platform to force _snprintf_s() to
conform to the C99 standard and match the other platforms.

*Bugsquad edit:* Fixes #24137.

### CODE REVIEW

**Comment by jamie-pate** [comment]
https://travis-ci.org/godotengine/godot/jobs/607924096?utm_medium=notification&utm_source=github_status <- i feel like this travis failure isn't due to this patch?

File: core/ustring.cpp [hunk 1]
```diff
@@ -1337,7 +1337,17 @@ String String::num_scientific(double p_num) {
 	char buf[256];
 
 #if defined(__GNUC__) || defined(_MSC_VER)
+
+#if defined(_TWO_DIGIT_EXPONENT)
```
Comment (akien-mga) [inline core/ustring.cpp]: Is it guaranteed that `_TWO_DIGIT_EXPONENT` is only defined by MinGW and MSVC < 2015?

Comment (jamie-pate) [reply core/ustring.cpp]: Googling gives a good probability, but no guarantees. I guess to be more correct we could check for the correct msvc version || mingw?

Comment (akien-mga) [reply core/ustring.cpp]: Yeah, though that should likely be something like:
```
#if defined(__MINGW32__) || (defined(_MSC_VER) && _MSC_VER < 1900)
```
Might also be worth checking if recent MinGW versions fix that / if they have plans to change it eventually, since it seems they set the default to `_THREE_DIGIT_EXPONENT` for compatibility with the Windows API, which seems not longer to be relevant if MSVC changed that. (But MinGW often has a few years lag, understandably.)

Comment (jamie-pate) [reply core/ustring.cpp]: From the conversations I've seen, it looks like they only will maintain compatibility with the msvcrt that ships with Windows, the runtime that ships with vc++ 2015 etc is an add-on redistributable package and the goal of 'run without dependencies' on window would conflict. 

I also wondered if there is a good place to set this behavior on program initialization instead of this specific location? That might clean up this section at least.

**Comment by akien-mga** [comment]
Thanks!

**Comment by bruvzg** [comment]
This PR breaks MinGW/clang/LLD build using Windows 10 UCRT, we should additionally have `!defined(_UCRT)` check.
