### PR TITLE
Fix Script Editor saves C# files as embedded scripts.

### LINKED ISSUE #88160: Godot User Error running C# project on Android
### Tested versions

- Reproducible in Godot 4.3 on `v4.3.dev.mono.custom_build [4e990cd7e]`.
- Could open but not build Godot project on `v4.2.1.stable.mono.official [b09f793f5]` (I think it is a separate error since I was able to build on a later version like Godot 4.3).

### System information

Ubuntu 22.04 - v4.3.dev.mono.custom_build [4e990cd7e] - Mobile - Rendering failure

### Issue description

Godot v4.3.dev.mono (4e990cd7e) - Ubuntu 22.04.3 LTS 22.04 - X11 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 970 (nvidia; 535.154.05) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

I am exporting a C# project on Godot 4.3 mono to Android and the APK builds correctly, but the app stalls with black screen on the device after running `adb install MyApp.apk`. Testing it from the editor on Ubuntu it works fine.

```
02-09 13:32:16.512 23342 23394 E godot   : USER ERROR: Failed loading scene: res://shade_scene.tscn.
02-09 13:32:16.512 23342 23394 E godot   :    at: start (main/main.cpp:3736)
02-09 13:32:16.512 23342 23394 E godot   : USER ERROR: Condition "default_certs != nullptr" is true.
02-09 13:32:16.512 23342 23394 E godot   :    at: load_default_certificates (modules/mbedtls/crypto_mbedtls.cpp:342)
02-09 13:32:16.519 23342 23394 E godot   : USER ERROR: Cannot get class 'CSharpScript'.
02-09 13:32:16.519 23342 23394 E godot   :    at: instantiate (core/object/class_db.cpp:359)
02-09 13:32:16.519 23342 23394 E godot   : USER ERROR: res://shade_scene.tscn:Resource of unrecognized type in file: CSharpScript.
02-09 13:32:16.519 23342 23394 E godot   :    at: load (core/io/resource_format_binary.cpp:762)
02-09 13:32:16.519 23342 23394 E godot   : USER ERROR: Failed loading resource: res://.godot/exported/133200997/export-6a459847f1b0e7a5df30194dc41776f7-shade_scene.scn. Make sure resources have been imported by opening the project in the editor at least once.
02-09 13:32:16.519 23342 23394 E godot   :    at: _load (core/io/resource_loader.cpp:276)
```

### Steps to reproduce

1. Download repo and switch to `4e990cd7e` commit.
2. Build editor `scons p=linuxbsd target=editor module_mono_enabled=yes`.
3. Build `scons platform=android target=template_debug arch=arm64` export template.
4. Move `android_debug.apk` to `$HOME/.local/share/godot/export_templates/4.3.dev.mono/ and add `version.txt` too.
5. Follow steps on [Exporting for Android](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html#exporting-for-android).
6. Install using ADB `adb install MyApp.apk`

### Minimal reproduction project (MRP)

[shadeslider_MRP.zip](https://github.com/godotengine/godot/files/14226294/shadeslider_MRP.zip)

### LINKED ISSUE #88543: C#: Reloading unregistered CSharpScript makes it embedded in scene.
### Tested versions

v4.3.0.dev.mono.custom_build [a92921ae4]

Not reproducible on 4.2.1.

### System information

Godot v4.3.0.dev.mono (a92921ae4) - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 2050 () - 12th Gen Intel(R) Core(TM) i5-12500H (16 Threads)

### Issue description

If a C# script is not registered (or not build) and is reloaded after external modification, it loses its `resource_path` and can be embedded in scene.

Related to https://github.com/godotengine/godot/issues/88160#issuecomment-1940465237

Edit: I didn't change anything about external settings like `dotnet/editor/external_editor`. It's all by default.

### Steps to reproduce

1. New project, new scene.
2. Attach new C# script and save. Don't build now and keep the build-in script editor open.
3. Modify the script on external editor.
4. Turn to editor and the Reload dialog will be shown. Click `Reload`.
5. The script become `[unsaved]` and if you save now, it will turn like `res://Main.tscn::CSharpScript_tlpw1`

(If build in step 2, you won't have this issue)

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by nongvantinh**
fixes: https://github.com/godotengine/godot/issues/88543
fixes: https://github.com/godotengine/godot/issues/88160

Because of the limitations of compiled programming languages like C#, when a newly created *.cs file hasn't been compiled, we don't have any information about its `Path` or `Type` in the `assembly`. This means we end up creating an invalid instance of this file whenever there's a request. Consequently, multiple instances of the script can exist. When a new instance takes over the path, it clears the `path_cache` of the previous instance, leading to undefined behavior.

### CODE REVIEW

**Comment by KoBeWi** [comment]
If other instances of the script exist, taking over path will make them unlinked from the original resource. It might cause attached scripts to stop updating (relevant for tool scripts).

**Comment by KoBeWi** [comment]
So I just realized

> During the ResourceLoader::load process, the C# side creates a different instance and clears the path_cache of the old one, causing it to lose its path.

This points to a bug in C# loader, because CACHE_MODE_IGNORE is not supposed to do that.

**Comment by KoBeWi** [comment]
Tested this PR and I'm getting
```
C:\godot_source\modules/gdscript/gdscript.cpp:702 - Condition "!p_keep_state && has_instances" is true. Returning: ERR_ALREADY_IN_USE
```
when modifying a GDScript file externally. Specifically it's a tool script attached in the current scene. After the error prints once, the script no longer updates.

**Comment by nongvantinh** [comment]
Thanks for pointing this out, the new PR should correctly and safely fix the bug and any future bugs related to multiple instances of C# script.

File: modules/mono/csharp_script.cpp [hunk 1]
```diff
@@ -2851,7 +2851,11 @@ Ref<Resource> ResourceFormatLoaderCSharpScript::load(const String &p_path, const
 	ERR_FAIL_COND_V_MSG(!scr->get_path().is_empty() && scr->get_path() != p_original_path, Ref<Resource>(),
 			"The C# script path is different from the path it was registered in the C# dictionary.");
 
-	scr->set_path(p_original_path, true);
+	Ref<Resource> existing = ResourceCache::get_ref(p_path);
+	if (!existing.is_valid()) {
```
Comment (KoBeWi) [inline modules/mono/csharp_script.cpp:2855]:
```suggestion
	if (existing.is_null()) {
```

**Comment by KoBeWi** [comment]
While this works, it's not exactly how it should be implemented.
The code you added should take effect only when `p_cache_mode` is `CACHE_MODE_IGNORE`. Otherwise the new script should normally take over path.

**Comment by nongvantinh** [comment]
Thanks. I was completely ignored the `p_cache_mode` parameter since it wasn't being used before. Now, I have modified it according to [the latest document specifications](https://docs.godotengine.org/en/latest/classes/class_resourceloader.html#:~:text=via%20load_threaded_get.-,enum%20CacheMode%3A,-CacheMode%20CACHE_MODE_IGNORE%20%3D). Please help me test it thoroughly.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
