### PR TITLE
[Export] Add readable descriptions and validation warnings to the export options.

### LINKED ISSUE #6360: Add minimum required OS version setting to macOS and iOS exports
### Describe the project you are working on

A multi-platform game I'll try to get published via the Apple App Store and other platforms

### Describe the problem or limitation you are having in your project

On macOS and iOS (and possible other plattforms) apps have a minimum required OS version specified in them. This provides a nice message on unsupported OS versions if you try to run the app (instead of it just crashing) and is also used in the App Store to inform you your device can't run the app before you download it.

As far as I can tell via testing using the Mobile Vulkan renderer in Godot 4 you need macOS 10.15 or later and iOS 16 or later to be sure that the device can run the game (as [discussed here](https://github.com/godotengine/godot/issues/70013)). However, when exporting Godot seems to set no macOS minimum required version (which defaults to macOS 10.12) and sets iOS 12 as the minimum required iOS version. In both cases this means the game will be distributed to and be possible to launch on devices where it will just show a black screen. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

One solution would of course be to correctly set these limits based on what the engine requires for your project, but this can be hard to know and get right. So I propose at least adding a field in the export dialogue where you can specify the macOS and iOS version that should be specified as the minimum required version for the export. Then you as the developer at least have control over this and can set it consistently for your exports.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add fields to the export settings for macOS and iOS.

When building add these fields to the appropriate info.plist fields of the bundle for macOS:
```
<key>LSMinimumSystemVersion</key>
<string>10.15</string>
<key>LSMinimumSystemVersionByArchitecture</key>
<dict>
  <key>x86_64</key>
  <string>10.15</string>
</dict>
```
For iOS the value needs to be set in the xcode build target as the IPHONEOS_DEPLOYMENT_TARGET key in the buildSettings dictionary. For example

```
D0BCFE7318AEBDA3004A7AAE /* Release */ = {
        isa = XCBuildConfiguration;
	buildSettings = {
		...
		IPHONEOS_DEPLOYMENT_TARGET = 16.0;
		...
	};
	name = Release;
};
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You can work around it on macOS by exporting the game unsigned, editing the info.plist manually and then manually signing and notarizing it via terminal. 
On iOS you can edit the information in XCode before building it there.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a hassle to need to do these extra steps on each export, and it would be better if it was correctly set when you export it from Godot. 

It would probably also be a good idea to then bump up the default values for these since I think the current minimum required macOS and iOS values will likely be wrong in for all exports unless they're using the compatibility renderer.

### LINKED ISSUE #73876: macOS (and iOS?) exports missing required provisioning profiles required for Apple App Store distribution
### Godot version

4.0rc4

### System information

macOS 13.2

### Issue description

I've been experimenting with trying to get a Godot project onto the Apple App Store (or at least into the Test Flight testing part) and I've run into an issue: Basically, when codesigning code with certain entitlements (like the now required App Sandbox) this also seems to require a provisioning profile to be embedded. However, it seems that Godot does not do this currently, and there is no option in the export dialogue to pick a provisioning profile to use.

In the case of iOS exports I think this problem could be the same, but there Godot generates an XCode project where you can fix the code signing issues and let XCode handle the signing and uploading, so there you can work around it. For macOS there is no way to generate an XCode project where you can fix the signing and upload it to the app store, so you need to create a pkg installer package and use the Transporter app to upload to app. And while I've managed to create a signed .pkg that Transporter accepts and uploads (using [this information](https://developer.apple.com/forums/thread/674916)) I get these two cryptic errors back from Apple by e-mail (APP_NAME replaced):

```
We identified one or more issues with a recent delivery for your app, "APP_NAME" 0.9.1 (0.9.1). Please correct the following issues, then upload again.

ITMS-90238: Invalid Signature - The main app bundle APP_NAME at path APP_NAME.app has following signing error(s): valid on disk /Volumes/workspace/app_data/SWValidationService/mz_6836161176781981326dir/mz_4826098586216996361dir/com.lostminds.APP_NAME.pkg/Payload/APP_NAME.app: satisfies its Designated Requirement test-requirement: code failed to satisfy specified code requirement(s) . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.

ITMS-90889: 'Cannot be used with TestFlight because the bundle at “APP_NAME.app” is missing a provisioning profile. Main bundles are expected to have provisioning profiles in order to be eligible for TestFlight.'
```

The first of these seems to indicate that there is something wrong with the code signing or signature and I don't really know what since the signature seems valid and there's no issue running the game. But it could be something that is not signed correctly during export. 

The second one is however more straight forward and indicates that the provisioning profile is missing as stated in the title. It seems there is a way to embed these (as [describe here under "Embed Distribution Provisioning Profiles"](https://developer.apple.com/forums/thread/701514)) but it seems like this has to be done by adding it to the bundle before signing, so it can't be fixed after the export as I understand it. 

### Steps to reproduce

- Export a signed (and notarized) macOS app
- Create a signed installer app store package for this ([here's how](https://developer.apple.com/forums/thread/674916))
- Upload the package to the App Store using the Transporter app
- Observer signing and provisioning profile errors coming back from Apple

### Minimal reproduction project

This is I think more of an export process omission/issue and not specific to a certain project.

### LINKED ISSUE #74154: Missing info.plist keys prevent submitting macOS build for App Store review
### Godot version

4.0rc6

### System information

macOS 13.2

### Issue description

While trying to get a Godot macOS export onto the macOS Apple App Store (as described here: https://github.com/godotengine/godot/issues/73876 which led to improvements for this process here in this PR: https://github.com/godotengine/godot/pull/74027) I've now managed to get a build to be properly signed and packaged to be accepted for upload by the Transporter app and listed in App Store Connect as ready for review. However, when you try to submit it for review (for Test Flight external testing) a new error is shown:

`This build is using a beta version of Xcode and can’t be submitted. Make sure you’re using the latest version of Xcode or the latest seed release found on the releases tab in News and Updates`

In other words, you can't submit the app for review since the system thinks it's been built with a beta version of XCode, preventing distribution via the App Store. It seems this is due to some missing keys in the info.plist of the exported app bundle Godot produces as guessed by @bruvzg  https://github.com/godotengine/godot/issues/73876#issuecomment-1448040562.

Adding the following keys copied from another macOS app I've built with XCode to the game info.plist before signing and packaging seems to resolve the issue:

```
<key>DTCompiler</key>
<string>com.apple.compilers.llvm.clang.1_0</string>
<key>DTPlatformBuild</key>
<string>14C18</string>
<key>DTPlatformName</key>
<string>macosx</string>
<key>DTPlatformVersion</key>
<string>13.1</string>
<key>DTSDKBuild</key>
<string>22C55</string>
<key>DTSDKName</key>
<string>macosx13.1</string>
<key>DTXcode</key>
<string>1420</string>
<key>DTXcodeBuild</key>
<string>14C18</string>
```

So at least some of these need to be added in exports for them to be eligible for mac app store distribution. It is however unlikely all of these keys are required for the build to be accepted. It's also unclear what content will be acceptable for these keys. I'll open this issue now to keep track of it and see if anyone else knows more about this. And I'll update with further comments if I figure out more about what keys are actually needed.

### Steps to reproduce

- Export, sign, package and upload a macOS build to the App Store using the steps described here: https://github.com/godotengine/godot/issues/73876
- In the App Store connect Test Flight interface, add external testers to the build and click the button to submit for review.
- Observer error about beta version of Xcode blocking submit.

### Minimal reproduction project

This is a general macOS export issue

### PR DESCRIPTION
**Pull request by bruvzg**
#### Adds an ability to dynamically validate and display warning for the export options.
Screenshot 2023-03-15 at 09 38 02

#### Adds more export option visibility checks (auto-hide irrelevant options).

https://user-images.githubusercontent.com/7645683/225239188-21593b69-8ee9-429d-8a78-21d7ee832c4b.mov

#### Adds export option to set macOS min. version (macOS).

Fixes https://github.com/godotengine/godot-proposals/issues/6360
Fixes https://github.com/godotengine/godot/issues/73876
Fixes https://github.com/godotengine/godot/issues/74154

Supersede https://github.com/godotengine/godot/pull/74027
Supersede https://github.com/godotengine/godot/pull/49525
Supersede #73219

### CODE REVIEW

**Comment by Calinou** [comment]
Does this use the class reference XML (which would allow for localization)?

**Comment by bruvzg** [comment]
> Does this use the class reference XML

Not in a class reference, since it's not a real class, all properties are dynamically generated (and depends on platform in some cases), and I'm not sure making it a full class and register in ClassDB is a good idea. But all strings should be localizable as part of editor translation.

**Comment by bruvzg** [comment]
> This is what I attempted in https://github.com/godotengine/godot/pull/49525.

Actually, this approach is probably better, changed it to use class ref. XMLs in a similar manner.

**Comment by bruvzg** [comment]
The list of Android permissions seems to be a mess. I have copy-pasted descriptions and added some links, but a lot of them are marked as deprecated or completely missing from the current Android documentation, so it's gonna need some extra work to clean up.

Also, I have not added any descriptions for OpenXR options and most of the Web export options, since I'm not sure what exactly these are doing.

**Comment by lostminds** [comment]
This feels like a great step in the right direction, good job! If this supersedes #74027 and has a wider scope, would it be possible to add the minOS version field for iOS export as well, to cover the entire https://github.com/godotengine/godot-proposals/issues/6360 ?

File: platform/android/export/export_plugin.cpp [hunk 1]
```diff
@@ -1698,6 +1698,91 @@ void EditorExportPlatformAndroid::get_preset_features(const Ref<EditorExportPres
 	}
 }
 
+String EditorExportPlatformAndroid::get_export_option_warning(const EditorExportPreset *p_preset, const StringName &p_name) const {
```
Comment (m4gr3d) [inline platform/android/export/export_plugin.cpp:1701]: The checks here replicate the ones in `has_valid_project_configuration(...)`. Can the latter method be deprecated then?

Comment (m4gr3d) [reply platform/android/export/export_plugin.cpp:1701]: I see from your example screenshots they serve different purposes. It may be easier then to move the warnings check logic into a helper method that both methods use.

Comment (bruvzg) [reply platform/android/export/export_plugin.cpp:1701]: Yes, probably it can be merged. I guess I'll add an extra `validation_required` option (to indicate what's warning and what's error) to the `ExportOption`, and check all the options using `get_export_option_warning` instead of duplicating the checks in the `has_valid_project_configuration`.

Comment (bruvzg) [reply platform/android/export/export_plugin.cpp:1706]: Updated to use `get_export_option_warning` for both.

**Review by m4gr3d — COMMENTED** [review]
The Android section looks good!

File: doc/classes/EditorExportPlatformWindows.xml [hunk 2]
```diff
@@ -0,0 +1,135 @@
...
+			Path to the custom export template. If left empty, default template is used.
+		</member>
+		<member name="debug/export_console_script" type="int" setter="" getter="">
+			If [code]true[/code], a console wrapper executable is exported alongside the main executable, which allows running the project with enabled console output.
+		</member>
+		<member name="ssh_remote_deploy/cleanup_script" type="String" setter="" getter="">
+			Script code to execute on the remote host when app is finished.
+			   The following variables can be used in the script:
+
+			- [code]{temp_dir}[/code] - Path of temporary folder on the remote, used to upload app and scripts to.
```
Comment (akien-mga) [inline doc/classes/EditorExportPlatformWindows.xml:93]: There shouldn't be empty lines in the XML, each line is one paragraph.
```suggestion
			The following variables can be used in the script:
			- [code]{temp_dir}[/code] - Path of temporary folder on the remote, used to upload app and scripts to.
```

File: doc/classes/EditorExportPlatformAndroid.xml [hunk 3]
```diff
@@ -0,0 +1,581 @@
...
+			Path to the custom export template. If left empty, default template is used.
+		</member>
+		<member name="custom_template/release" type="String" setter="" getter="">
+			Path to the custom export template. If left empty, default template is used.
+		</member>
+		<member name="gradle_build/export_format" type="int" setter="" getter="">
+			Export format for Gradle build.
+		</member>
+		<member name="gradle_build/min_sdk" type="String" setter="" getter="">
+			Min. Android SDK version for Gradle build.
```
Comment (akien-mga) [inline doc/classes/EditorExportPlatformAndroid.xml:48]:
```suggestion
			Minimal Android SDK version for Gradle build.
```

File: doc/classes/EditorExportPlatformLinuxBSD.xml [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+			Path to the custom export template. If left empty, default template is used.
+		</member>
+		<member name="debug/export_console_script" type="int" setter="" getter="">
+			If [code]true[/code], a console wrapper script is exported alongside the main executable, which allows running the project with enabled console output.
+		</member>
+		<member name="ssh_remote_deploy/cleanup_script" type="String" setter="" getter="">
+			Script code to execute on the remote host when app is finished.
+			   The following variables can be used in the script:
+
+			- [code]{temp_dir}[/code] - Path of temporary folder on the remote, used to upload app and scripts to.
```
Comment (akien-mga) [inline doc/classes/EditorExportPlatformLinuxBSD.xml:33]:
```suggestion
			The following variables can be used in the script:
			- [code]{temp_dir}[/code] - Path of temporary folder on the remote, used to upload app and scripts to.
```

File: doc/classes/EditorExportPlatformLinuxBSD.xml [hunk 5]
```diff
@@ -0,0 +1,75 @@
...
+			Remote host SSH user name and address, in [code]user@address[/code] format.
+		</member>
+		<member name="ssh_remote_deploy/port" type="String" setter="" getter="">
+			Remote host SSH port number.
+		</member>
+		<member name="ssh_remote_deploy/run_script" type="String" setter="" getter="">
+			Script code to execute on the remote host when running the app.
+			The following variables can be used in the script:
+
+			- [code]{temp_dir}[/code] - Path of temporary folder on the remote, used to upload app and scripts to.
```
Comment (akien-mga) [inline doc/classes/EditorExportPlatformLinuxBSD.xml:57]:
```suggestion
			The following variables can be used in the script:
			- [code]{temp_dir}[/code] - Path of temporary folder on the remote, used to upload app and scripts to.
```

File: doc/classes/EditorExportPlatformMacOS.xml [hunk 6]
```diff
@@ -0,0 +1,293 @@
...
+			A message displayed when requesting access to the user's removable drives (in English).
+		</member>
+		<member name="privacy/removable_volumes_usage_description_localized" type="Dictionary" setter="" getter="">
+			A message displayed when requesting access to the user's removable drives (localized).
+		</member>
+		<member name="ssh_remote_deploy/cleanup_script" type="String" setter="" getter="">
+			Script code to execute on the remote host when app is finished.
+			   The following variables can be used in the script:
+
+			- [code]{temp_dir}[/code] - Path of temporary folder on the remote, used to upload app and scripts to.
```
Comment (akien-mga) [inline doc/classes/EditorExportPlatformMacOS.xml:245]:
```suggestion
			The following variables can be used in the script:
			- [code]{temp_dir}[/code] - Path of temporary folder on the remote, used to upload app and scripts to.
```

File: doc/classes/EditorExportPlatformMacOS.xml [hunk 7]
```diff
@@ -0,0 +1,293 @@
...
+			Remote host SSH user name and address, in [code]user@address[/code] format.
+		</member>
+		<member name="ssh_remote_deploy/port" type="String" setter="" getter="">
+			Remote host SSH port number.
+		</member>
+		<member name="ssh_remote_deploy/run_script" type="String" setter="" getter="">
+			Script code to execute on the remote host when running the app.
+			The following variables can be used in the script:
+
+			- [code]{temp_dir}[/code] - Path of temporary folder on the remote, used to upload app and scripts to.
```
Comment (akien-mga) [inline doc/classes/EditorExportPlatformMacOS.xml:269]:
```suggestion
			The following variables can be used in the script:
			- [code]{temp_dir}[/code] - Path of temporary folder on the remote, used to upload app and scripts to.
```

File: doc/classes/EditorExportPlatformWindows.xml [hunk 8]
```diff
@@ -0,0 +1,135 @@
...
+			Remote host SSH user name and address, in [code]user@address[/code] format.
+		</member>
+		<member name="ssh_remote_deploy/port" type="String" setter="" getter="">
+			Remote host SSH port number.
+		</member>
+		<member name="ssh_remote_deploy/run_script" type="String" setter="" getter="">
+			Script code to execute on the remote host when running the app.
+			The following variables can be used in the script:
+
+			- [code]{temp_dir}[/code] - Path of temporary folder on the remote, used to upload app and scripts to.
```
Comment (akien-mga) [inline doc/classes/EditorExportPlatformWindows.xml:117]:
```suggestion
			The following variables can be used in the script:
			- [code]{temp_dir}[/code] - Path of temporary folder on the remote, used to upload app and scripts to.
```

**Review by akien-mga — APPROVED** [review]
That's really amazing work. It's so cool to have all this documented.

Haven't reviewed the docs in depth beyond quick style comments, but the code looks great, and the docs seem quite thorough too.

It's outside the scope of this PR, but now that platform-specific classes are being registered, we might need to find a way to let them host their XML files in their platform folder, like we do for modules. It's not necessarily needed for platforms in core, but it would be needed for non-upstream platforms (e.g. console ports) so they can provide their docs easily.

**Review by Calinou — APPROVED** [review]
Looks great!

Note for others: I'll be documenting all properties I can in a future PR after this is merged.

File: doc/classes/EditorExportPlatformWindows.xml (hunk 8 above)
Comment (bruvzg) [reply doc/classes/EditorExportPlatformWindows.xml:117]: Fixed.

**Comment by bruvzg** [comment]
> It's outside the scope of this PR, but now that platform-specific classes are being registered, we might need to find a way to let them host their XML files in their platform folder, like we do for modules. It's not necessarily needed for platforms in core, but it would be needed for non-upstream platforms (e.g. console ports) so they can provide their docs easily.

[Done - https://github.com/godotengine/godot/pull/76251](https://github.com/godotengine/godot/pull/76251)
