### PR TITLE
Automatically add all AutoLoad resources when exporting the project

### LINKED ISSUE #32377: Export with dependencies is missing autoload files
**Godot version:** 3.1.1

**OS/device including version:** OS X 10.14.6 (18G95)

**Issue description:** When I select export selected scenes and dependencies, it misses the files declared as autoloaded which renders the game unplayable.

Even other scenes that are directly inside a scene are missing: Player.tscn

**Steps to reproduce:** Have in autoloader and export selected scenes and dependencies

**Project:** https://github.com/firegate666/godot-platformer

```
ERROR: initialize: Directional shadow framebuffer status invalid
   At: drivers/gles2/rasterizer_scene_gles2.cpp:3369.
ERROR: load_interactive: Condition ' err != OK ' is true. returned: Ref<ResourceInteractiveLoader>()
   At: scene/resources/resource_format_text.cpp:1226.
ERROR: _load: Failed loading resource: res://default_env.tres
   At: core/io/resource_loader.cpp:285.
ERROR: SceneTree: Default Environment as specified in Project Settings (Rendering -> Environment -> Default Environment) could not be loaded.
   At: scene/main/scene_tree.cpp:2048.
ERROR: load_source_code: Condition ' err ' is true. returned: err
   At: modules/gdscript/gdscript.cpp:813.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: modules/gdscript/gdscript.cpp:2172.
ERROR: _load: Failed loading resource: res://SignalBus.gd
   At: core/io/resource_loader.cpp:285.
ERROR: start: Can't autoload: res://SignalBus.gd
   At: main/main.cpp:1549.
ERROR: load_source_code: Condition ' err ' is true. returned: err
   At: modules/gdscript/gdscript.cpp:813.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: modules/gdscript/gdscript.cpp:2172.
ERROR: _load: Failed loading resource: res://Player.gd
   At: core/io/resource_loader.cpp:285.
ERROR: poll: res://Player.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Player.gd
   At: scene/resources/resource_format_text.cpp:440.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Failed loading resource: res://Player.tscn
   At: core/io/resource_loader.cpp:285.
ERROR: poll: res://Level1.tscn:4 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Player.tscn
   At: scene/resources/resource_format_text.cpp:440.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Failed loading resource: res://Level1.tscn
   At: core/io/resource_loader.cpp:285.

```

### PR DESCRIPTION
**Pull request by fmazan**
Fixes #32377

Adds all AutoLoad resources and their dependencies on export.

Could this change be cherrypicked back to 3.2?

### CODE REVIEW

File: editor/editor_export.cpp [hunk 1]
```diff
@@ -757,6 +757,25 @@ Error EditorExportPlatform::export_project_files(const Ref<EditorExportPreset> &
...
 		}
+
+		// add autoload resources and their dependencies
+		List<PropertyInfo> props;
+		ProjectSettings::get_singleton()->get_property_list(&props);
+
+		for (List<PropertyInfo>::Element *E = props.front(); E; E = E->next()) {
+			const PropertyInfo &pi = E->get();
+
+			if (!pi.name.begins_with("autoload/"))
```
Comment (KoBeWi) [inline editor/editor_export.cpp:768]: Conditions need to be wrapped in braces even if they have one line. (as per Godot's coding guideline)

File: editor/editor_export.cpp [hunk 2]
```diff
@@ -757,6 +757,25 @@ Error EditorExportPlatform::export_project_files(const Ref<EditorExportPreset> &
 
 			_export_find_dependencies(files[i], paths);
 		}
+
+		// add autoload resources and their dependencies
```
Comment (KoBeWi) [inline editor/editor_export.cpp:761]:
```suggestion
		// Add autoload resources and their dependencies.
```

File: editor/editor_export.cpp [hunk 3]
```diff
@@ -757,6 +757,25 @@ Error EditorExportPlatform::export_project_files(const Ref<EditorExportPreset> &
...
+		for (List<PropertyInfo>::Element *E = props.front(); E; E = E->next()) {
+			const PropertyInfo &pi = E->get();
+
+			if (!pi.name.begins_with("autoload/"))
+				continue;
+
+			String autoload_path = ProjectSettings::get_singleton()->get(pi.name);
+
+			if (autoload_path.begins_with("*")) {
+				autoload_path = autoload_path.substr(1, autoload_path.length());
```
Comment (KoBeWi) [inline editor/editor_export.cpp:774]: The second argument of `substr` is unnecessary here.

**Review by KoBeWi — COMMENTED** [review]
Code looks ok and works. If you do the requested changes I can approve the PR.

**Comment by fmazan** [comment]
Thanks for your code review, all proposed changes are applied.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
I assume this doesn't handle that part of the bug report? https://github.com/godotengine/godot/issues/32377#issuecomment-679194798

**Comment by KoBeWi** [comment]
It doesn't.

**Comment by fmazan** [comment]
I believe [this](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_parser.h#L1322) is why class_name references are not marked as dependencies and hence are not exported automatically. I could look into it, but honestly I have never seen or touched gdscript code before, so it could take me some time to do properly.

All in all, this PR fixes the original issue, but not the class_name sub-issue.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
