### PR TITLE
Fix insert key crash with no animation

### LINKED ISSUE #76369: Godot Crashing when switching to the animation tab and clicking on key symbol
### Godot version

4.0.2

### System information

Windows 10,Radeon RX 550/550 Series,23.3.2,Vulkan

### Issue description

After Switching to the animations tabs and pressing the key symbol because I wanted to know what it does, Godot crashes

### Steps to reproduce

Go into a project 
Switch to the Animations Tab, make sure no animation is active 
And then press on the key symbol

here is a video demonstrating the bug

https://user-images.githubusercontent.com/59411880/233839816-5489899e-828f-4ac9-9de3-7914f727f754.mp4

### Minimal reproduction project

The File
[package.zip](https://github.com/godotengine/godot/files/11303712/package.zip)

### PR DESCRIPTION
**Pull request by spanzeri**
Add a sanity check and an error message if a user tries to insert a key when no animation are selected.
Fix https://github.com/godotengine/godot/issues/76369

### CODE REVIEW

**Comment by akien-mga** [comment]
That makes sense to fix the crash, but the real problem happens before this IMO. The animation toolbar that attempts to insert those keys shouldn't be shown when no AnimationPlayer is being edited.

Currently, the :key: keying icons only show when you have selected an AnimationPlayer for example. This toolbar should likely be hidden and shown in the same conditions.

And then the null check can be kept for good measure, but the user shouldn't be able to reach a situation that triggers this error in the first place.

**Comment by spanzeri** [comment]
@akien-mga good points. I have updated the PR to only show the options when it would be valid to key a node

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -526,13 +526,18 @@ Object *CanvasItemEditor::_get_editor_data(Object *p_what) {
 }
 
 void CanvasItemEditor::_keying_changed() {
-	if (AnimationPlayerEditor::get_singleton()->get_track_editor()->is_visible_in_tree()) {
+	AnimationTrackEditor *te = AnimationPlayerEditor::get_singleton()->get_track_editor();
+	if (te && te->is_visible_in_tree() && !te->get_current_animation().is_null()) {
```
Comment (YuriSizov) [inline editor/plugins/canvas_item_editor_plugin.cpp:530]:
```suggestion
	if (te && te->is_visible_in_tree() && te->get_current_animation().is_valid()) {
```

**Review by YuriSizov — APPROVED** [review]
Aside from pretty nitpicky suggestions this seems fine.

**Comment by spanzeri** [comment]
Thank you @YuriSizov . I have cleaned up the PR as you suggested: removed the extra function and replaced is_null with is_valid.

**Comment by YuriSizov** [comment]
Let's get this merged. If Tokage has some concerns, we can address them in a follow-up. This is a pretty safe sanity check change.

**Comment by YuriSizov** [comment]
Thanks!

**Comment by TokageItLab** [comment]
Skeleton editor has a similar implementation, but does not crash due to the following error:
```
editor\animation_track_editor.cpp:3746 - Condition "!root" is true. Returning: false
```

As @akien-mga said, this should not prevent insertion on the CanvasEditor side, it should prevent insertion on the TrackEditor side.

If the crash occurs on the CanvasEditor side, it is possible that CanvasEditor is referencing null or not using the TrackEditor API correctly.

Well, Skeleton3DEditor also lacks the ability to show and hide the keying buttons when the Animation list is updated, so we may need to work on a follow-up PR later to make all of those behaviors consistent.
