### PR TITLE
Cleanup QuickOpenDialog history and fix UID errors

### LINKED ISSUE #104961: ERROR: Unrecognized UID: "uid://vfkt4pl67hw3" when opening Quick Open dialog
### Tested versions

- Reproducible in v4.5.dev1.mono.official [97241ffea]

### System information

Godot v4.5.dev1.mono - Windows 10 (build 19045) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 32.0.15.6094) - Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 threads)

### Issue description

When I opened Quick Open... dialog I got these error messages:

Image

My first though was that my project is somehow corrupted. When I searched for these unrecognized UIDs are, I found them from `quick_open_dialog_cache.cfg`. 

Image

So the cache contains files I have already deleted. I think this is a quite normal thing to happen with caches. 

In my opinion no error message should be displayed here. This error message only makes the user to suspect that something is broken. Even displaying the source of the error (quick open dialog cache) would be useless because users do not care about this kind of internal editor things.

### Steps to reproduce

1. Add new gdscript file to a project
2. Open the added gdscript file using Quick Open (`Shift-Alt-O` in Windows)
3. Quit Godot
4. Delete the added gdscript file manually
5. Start Godot and load the project
6. Open Quick Open dialog
==> `Unrecognized UID`

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by KoBeWi**
The EditorQuickOpenDialog does a check for missing resource paths, but if the path is UID, the check will print an error. This PR prevents that.
I also added a code that will cleanup invalid paths and re-save history when necessary. While normally it does not matter, because history is re-saved when you open something, the dialog wouldn't modify history of a type you didn't open recently. If you had some outdated paths for rarely used types, they'd be loaded and skipped every time for no reason.

* *Bugsquad edit, fixes: https://github.com/godotengine/godot/issues/104961*

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: editor/gui/editor_quick_open_dialog.cpp [hunk 1]
```diff
@@ -363,13 +376,29 @@ void QuickOpenResultContainer::init(const Vector<StringName> &p_base_types) {
...
+						history_file->set_value("selected_history", type, cleaned_paths);
+					}
+					history_modified = true;
 			}
 		}
 	}
+		if (history_modified) {
+			history_file->save(_get_cache_file_path());
+		}
+	}
```
Comment (akien-mga) [inline editor/gui/editor_quick_open_dialog.cpp:400]: You seem to have indentation issues.

**Comment by Repiteo** [comment]
Thanks!
