### PR TITLE
fixed issue where shortcut doesn't work if alt is pressed before shift

### LINKED ISSUE #39351: Shortcuts don't work if Alt is pressed before Shift
**Godot version:**
3.2.1.stable.official

**OS/device including version:**
Microsoft Windows [Version 10.0.17134.706]

**Issue description:**
A shortcut that uses both the <kbd>Shift</kbd> and <kbd>Alt</kbd> modifiers does not trigger its associated action if <kbd>Alt</kbd> is pressed before <kbd>Shift</kbd>.

**Steps to reproduce:**
Using the default shortcut mapping for _Quick open_, press <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>O</kbd>, in that order.

**Minimal reproduction project:**
N/A

### PR DESCRIPTION
**Pull request by hcmlax**
Fixes #39351 

Order shouldn't matter for shortcuts involving alt+shift anymore.

### CODE REVIEW

File: platform/windows/display_server_windows.cpp [hunk 1]
```diff
@@ -2536,7 +2536,7 @@ LRESULT DisplayServerWindows::WndProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARA
 		case WM_KEYUP:
 		case WM_KEYDOWN: {
 			if (wParam == VK_SHIFT)
-				shift_mem = uMsg == WM_KEYDOWN;
+				shift_mem = (uMsg == WM_KEYDOWN || uMsg == WM_SYSKEYDOWN);
```
Comment (akien-mga) [inline platform/windows/display_server_windows.cpp:2539]: Should the same be done for `VK_CONTROL` below?

**Comment by akien-mga** [comment]
For context:
- https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-syskeydown
- https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-keydown

File: platform/windows/display_server_windows.cpp (hunk 1 above)
Comment (hcmlax) [reply platform/windows/display_server_windows.cpp:2539]: I think you're probably right.  I was only fixing the bug that was mentioned in the issue, but I assume that shortcuts involving control/alt might result in the same bug.  I will make that change and update the pull request.

**Comment by akien-mga** [comment]
Could you squash the two commits into one?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.
