### PR TITLE
Fix #8617 WindowDialog with custom panel background crashes godot

### LINKED ISSUE #8617: WindowDialog with custom panel background crashes godot
godot 3.0 30th april build Kubuntu 17.04 x64

STR: 1. Have a theme that sets WindowDialog/styles/panel to anything other than null
2. Open anything that uses WindowDialog (Export menu for example)

### PR DESCRIPTION
**Pull request by Zylann**
Never downcast without a check :p
Fixes #8617

### CODE REVIEW

File: scene/gui/dialogs.cpp [hunk 1]
```diff
@@ -54,20 +54,24 @@ void WindowDialog::_fix_size() {
...
-	if (resizable) {
-		size.x = MIN(size.x, viewport_size.x - left - right);
-		size.y = MIN(size.y, viewport_size.y - top - bottom);
-		set_size(size);
+	// Check validity, because the theme could contain a different type of StyleBox
+	if (panel.is_valid()) {
+		float top = panel->get_expand_margin_size(MARGIN_TOP);
+		float left = panel->get_expand_margin_size(MARGIN_LEFT);
+		float bottom = panel->get_expand_margin_size(MARGIN_BOTTOM);
+		float right = panel->get_expand_margin_size(MARGIN_RIGHT);
```
Comment (volzhs) [inline scene/gui/dialogs.cpp]: I face this issue while making editor theme.
I think only `panel->get_expand_margin_size(MARGIN_*);` is problem.
other part could be fine.
I made changes check if panel is `StyleBoxTexture` and taking expand margin values.
and rest of codes run fine.

Comment (Zylann) [inline scene/gui/dialogs.cpp]: Aren't the values 0 otherwise? Then the repositionning isn't needed, right?
