### PR TITLE
[Windows] Use CRLF in the terminal prints.

### LINKED ISSUE #91603: External Editor Console Output format is wrong with many whitespaces (Godot 4.3 dev 6) C#
### Tested versions

- Tested in 4.2.1 (Working fine)
- Tested in 4.3 dev 6 (Not working)

### System information

Godot v4.3. dev6.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Ti (NVIDIA; 31.0.15.5222) - 13th Gen Intel(R) Core(TM) i9-13900KF (32 Threads)

### Issue description

When calling GD.Print("blabla") in C# in Jetbrains Rider 2024.1 and using the Godot 4.3 dev 6 version the format of the ouput is totally messed up and has many whitespaces.

Project in Godot 4.3 dev 6 (wrong formatting of output)
image

The same project in Godot 4.2.1 (formatting the output correct)
image

### Steps to reproduce

1. Create a script in Godot and write a GD.Print statement in the _Process function.
2. Open the external editor
3. Click on "Build & Debug" in the external editor
4. See the output in the console

### Minimal reproduction project (MRP)

[OutputTest.zip](https://github.com/godotengine/godot/files/15214490/OutputTest.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Replaces `\n` with `\r\n` in the Windows terminal prints.

Might fix https://github.com/godotengine/godot/issues/91603 (I was not able to reproduce it, but this is the only possible reason I can think of).

### CODE REVIEW

File: platform/windows/windows_terminal_logger.cpp [hunk 1]
```diff
@@ -42,20 +42,30 @@ void WindowsTerminalLogger::logv(const char *p_format, va_list p_list, bool p_er
...
+	va_list list_copy;
+	va_copy(list_copy, p_list);
+	int len = vsnprintf(buf, static_buffer_size, p_format, p_list);
+	if (len >= static_buffer_size) {
+		buf = (char *)memalloc(len + 1);
+		len = vsnprintf(buf, len + 1, p_format, list_copy);
+	}
+	va_end(list_copy);
+
+	String str_buf = String::utf8(buf, len).replace("\r\n", "\n").replace("\n", "\r\n");
```
Comment (kus04e4ek) [inline platform/windows/windows_terminal_logger.cpp:57]:
```suggestion
	String str_buf = String::utf8(buf, len).replace("\n", "\r\n");
```

Comment (bruvzg) [reply platform/windows/windows_terminal_logger.cpp:57]: String can already have `\r\n`s and without removing it first it will result in `\r\r\n`.

Comment (kus04e4ek) [reply platform/windows/windows_terminal_logger.cpp:57]: > String can already have `\r\n`s and without removing it first it will result in `\r\r\n`.

Makes sense👍

**Comment by MatthiasBae** [comment]
I would like to test it but Godot won't build the managed libraries after creating the Mono Glue.

Having this issue https://github.com/godotengine/godot/issues/80739

It does not find the GeneratedIncludes.props file

**Comment by van800** [comment]
I confirm the issue was solved.
image

**Comment by viksl** [comment]
I can also confirm both prints and errors are fine with this.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
