### PR TITLE
Properly load multiple action sets in XR

### LINKED ISSUE #80420: Multiple OpenXR Action Sets in Godot does not work
### Godot version

4.2 dev 2

### System information

Windows 10 Godot Engine v4.2.dev2.mono.official.da81ca62a - https://godotengine.org OpenGL API 3.3.0 NVIDIA 536.67 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce GTX 980 Ti

### Issue description

If you have multiple openxr action sets it will fail to load all of the action sets after the first one loaded

### Steps to reproduce

Have multiple openxr action sets

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Faolan-Rad**
This pull request addresses an issue where Godot was unable to correctly load multiple action sets. Previously, only the first action set was loaded, and any subsequent attempts would result in an error, indicating that the action sets were already loaded.

This fix ensures that multiple action sets can be loaded without errors

* *Bugsquad edit, fixes: #80420*

### CODE REVIEW

File: modules/openxr/openxr_api.h [hunk 1]
```diff
@@ -380,7 +380,7 @@ class OpenXRAPI {
 
 	RID action_set_create(const String p_name, const String p_localized_name, const int p_priority);
 	String action_set_get_name(RID p_action_set);
-	bool action_set_attach(RID p_action_set);
+	bool attach_action_sets(Vector<RID> p_action_sets);
```
Comment (AThousandShips) [inline modules/openxr/openxr_api.h:383]:
```suggestion
	bool attach_action_sets(const Vector<RID> &p_action_sets);
```
Unless you intend the vector to be modified

File: modules/openxr/openxr_interface.cpp [hunk 2]
```diff
@@ -555,9 +555,11 @@ bool OpenXRInterface::initialize() {
 	xr_server->add_tracker(head);
 
 	// attach action sets
+	Vector<RID> loaded_action_sets = {};
```
Comment (AThousandShips) [inline modules/openxr/openxr_interface.cpp:558]:
```suggestion
	Vector<RID> loaded_action_sets;
```
Unneeded

**Comment by Faolan-Rad** [comment]
[issues](https://github.com/godotengine/godot/issues/80420)

File: modules/openxr/openxr_api.cpp [hunk 3]
```diff
@@ -2274,33 +2274,41 @@ String OpenXRAPI::action_set_get_name(RID p_action_set) {
 	return action_set->name;
 }
 
-bool OpenXRAPI::action_set_attach(RID p_action_set) {
-	ActionSet *action_set = action_set_owner.get_or_null(p_action_set);
-	ERR_FAIL_NULL_V(action_set, false);
+bool OpenXRAPI::attach_action_sets(const Vector<RID> p_action_sets) {
```
Comment (AThousandShips) [inline modules/openxr/openxr_api.cpp:2277]:
```suggestion
bool OpenXRAPI::attach_action_sets(const Vector<RID> &p_action_sets) {
```

File: modules/openxr/openxr_api.h [hunk 4]
```diff
@@ -380,7 +380,7 @@ class OpenXRAPI {
 
 	RID action_set_create(const String p_name, const String p_localized_name, const int p_priority);
 	String action_set_get_name(RID p_action_set);
-	bool action_set_attach(RID p_action_set);
+	bool attach_action_sets(const Vector<RID> p_action_sets);
```
Comment (AThousandShips) [inline modules/openxr/openxr_api.h:383]:
```suggestion
	bool attach_action_sets(const Vector<RID> &p_action_sets);
```

File: modules/openxr/openxr_api.cpp (hunk 3 above)
Comment (AThousandShips) [reply modules/openxr/openxr_api.cpp:2277]: These still need to be fixed

**Comment by YuriSizov** [comment]
Please amend the commit message to be closer to the project's preferred style. The current title of the PR is a good option. We don't prefix commits/PR titles with `Fix:` or anything like that, and there is no need to capitalize every word.

**Comment by BastiaanOlij** [comment]
I'm going to double check this with OpenXR because it should be possible to attach action sets one at a time, it shouldn't clear previously attached action sets...

**Comment by BastiaanOlij** [comment]
No, I'm definately wrong, I don't know if this was a restriction added after I build this or if it is something else but:

> The runtime must return XR_ERROR_ACTIONSETS_ALREADY_ATTACHED if [xrAttachSessionActionSets (https://registry.khronos.org/OpenXR/specs/1.0/man/html/xrAttachSessionActionSets.html) is called more than once for a given session.

in https://registry.khronos.org/OpenXR/specs/1.0/man/html/xrAttachSessionActionSets.html

**Review by BastiaanOlij — APPROVED** [review]

File: modules/openxr/openxr_api.cpp [hunk 5]
```diff
@@ -2274,33 +2274,41 @@ String OpenXRAPI::action_set_get_name(RID p_action_set) {
...
-	ActionSet *action_set = action_set_owner.get_or_null(p_action_set);
-	ERR_FAIL_NULL_V(action_set, false);
+bool OpenXRAPI::attach_action_sets(const Vector<RID> &p_action_sets) {
+	ERR_FAIL_COND_V(session == XR_NULL_HANDLE, false);
 
-	if (action_set->is_attached) {
-		// already attached
-		return true;
-	}
+	XrActionSet *action_handles = new XrActionSet[p_action_sets.size()];
```
Comment (BastiaanOlij) [inline modules/openxr/openxr_api.cpp:2280]: I'm probably missing it but are you freeing `action_handles` anywhere?

Comment (BastiaanOlij) [reply modules/openxr/openxr_api.cpp:2280]: Alternatively you can use:
```
Vector<XRActionSet> action_handles;
action_handles.resize(p_action_sets.size())
```
which will be freed automatically.

But now I'm nitpicking :)

Comment (akien-mga) [reply modules/openxr/openxr_api.cpp:2280]: Well using Godot templates that do memory management in a safe way is definitely not a nitpick, it's our policy :)
There's rarely any reason to use `new`.

**Review by m4gr3d — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
