### PR TITLE
Mono/macOS: Move GodotSharp data to Resources to allow codesigning

### LINKED ISSUE #43732: Codesigning silently fails on Mac Mono exports
**Godot version:**
3.2.3 Mono

**OS/device including version:**
macOS 10.15.7

**Issue description:**
Exporting a Mac app with the Mono build of Godot and a valid codesigning identity, the codesigning step fails with the following error: 

```
codesign (/Users/shane/Library/Caches/Godot/MonoTest.app/Contents/MacOS/MonoTest): /Users/shane/Library/Caches/Godot/MonoTest.app/Contents/MacOS/MonoTest: code object is not signed at all
In subcomponent: /Users/shane/Library/Caches/Godot/MonoTest.app/Contents/MacOS/data_MonoTest/Mono/etc/mono/config
```

The [Apple documentation on codesigning](https://developer.apple.com/library/archive/technotes/tn2206/_index.html) has a section on "nested code" that seems like the problem we're running into. Since a good chunk of the Mono distribution gets packaged up into the app, the `codesign` process doesn't happily operate. When I tried manually running codesign with the `--deep` flag, it raised a problem with the version directories, which that same Apple page says is problematic because they get interpreted as bundles. 

I don't know if there's an easy fix for this, other than re-arranging the layout of where the Mac build expects to find the mono distribution. In the meanwhile, though, the export should probably not fail silently as it currently does. (Took me a while to figure out what was wrong with this Godot project but not others.)

I'm looking at different solutions -- apparently Unity runs into similar issues with their exports, but people have had success individually signing each executable. That didn't work on my first effort, but still investigating. Wanted to log the issue though if anyone else runs into it.

**Steps to reproduce:**
1. Load the attached project on a Mac. 
2. Change the export configuration to have a valid codesigning identity. (One that works with a non-Mono Godot project, for instance.)
3. Run the export. 
4. Note the message that appears in the output (reproduced above). Running `codesign -vvvv ./MonoTest.app` on the resulting app confirms that it was not codesigned. 

**Minimal reproduction project:**
[MonoTest.zip](https://github.com/godotengine/godot/files/5576490/MonoTest.zip)

### PR DESCRIPTION
**Pull request by sjml**
This fixes #43732 -- that exported Mono projects could not be codesigned on the Mac due to their directory layout. This change creates a directory layout that is capable of being signed, and combined with [a change to the release build scripts](https://github.com/sjml/godot-build-scripts/commit/4c400fc07136ddbf6257cd32ef72335450d68834) will also create a version of the editor and export templates that work similarly. 

A few caveats:
1. ~~In the original issue, @bruvzg indicated that `etc` should go into `Frameworks` but this causes the codesign to fail due to the [policies about nested code](https://developer.apple.com/library/archive/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG201). I've put it into `Resources` instead, where the codesign cares less about the directory structure.~~ Per discussion below, the `lib` directory has been split up between `Resources` and `Frameworks`. 
2. The export no longer has a folder called `data_{GAMENAME}`, since the Mono distribution is more split up through the `.app`. I assume it was originally called that to have parity with the Linux and Windows exports, but since Mac applications are all bundled together and those details are invisible to the user, I didn't think that needed to be preserved. If it's significant for some other reason, please let me know. 
3. ~~[I'm slightly concerned that none of the loading code had to change to accommodate the different directories](https://github.com/godotengine/godot/issues/43732#issuecomment-731715196). I can't tell if Mono is just very good at finding its files, or if it's somehow picking up my system installation at runtime, or what. It works, but it's not 100% clear how, and I'm not a fan of that.~~ The loading code has now been changed, so it's clear there isn't magic going on.
4. Both the produced editor and export templates still produce `.app` packages that are unusable until they have `libMoltenVK.dylib` added to the `Frameworks` directory. I was following the existing build practices there, as it seems like the maintainers haven't yet settled on the best means of including it (#36213). I've poked on that issue thread to re-raise the question, and if it's something that can be decided soon-ish, this PR could easily be amended to accommodate whatever method makes sense. 

Long-term:
* This appears to be an issue with upstream mono as well (mono/mono#20304). It's unclear what the proper solution should be, but some seem to have a degree of success packing things together with [mkbundle](https://linux.die.net/man/1/mkbundle). Might be worth investigating? 
* [Unity ran into similar issues with their embedded Mono](https://issuetracker.unity3d.com/issues/cannot-distribute-macos-builds-codesign-errors-on-monobleedingedge-framework), and fixed them, but I haven't been able to find any documentation of what the change was. I briefly tried to seek out some games made before and after, but that's a hard search. If anyone has any insight or info there, it might be useful.

### CODE REVIEW

**Comment by sjml** [comment]
(Some issues with the export templates; still working here.)

**Comment by bruvzg** [comment]
> cp -rp out/macosx/tools-mono/GodotSharp/Mono Godot_mono.app/Contents/Resources/GodotSharp/Mono

There are few `dylib`s in the `GodotSharp/Mono/lib`, even if signing will work with `--deep`, it's not the correct way to put them to the `Resources`.

Only `etc` should be in `Resources`, and `--deep` should not be necessary:

Original code seems to be correct (ant it's for editor release):
```
cp -rp out/macosx/tools-mono/GodotSharp/Mono/lib Godot_mono.app/Contents/Frameworks/GodotSharp/Mono
cp -rp out/macosx/tools-mono/GodotSharp/Mono/etc Godot_mono.app/Contents/Resources/GodotSharp/Mono
```

Template part is here: https://github.com/godotengine/godot-build-scripts/blob/master/build-release.sh#L351

And should be changed to do the same as editor (and export code change should be ok).

```diff
-cp -rp out/macosx/templates-mono/data.mono.osx.universal.* osx_template.app/Contents/MacOS/
+cp -rp out/macosx/templates-mono/data.mono.osx.universal.release/Mono/lib osx_template.app/Contents/Frameworks/data.mono.osx.universal.release/Mono
+cp -rp out/macosx/templates-mono/data.mono.osx.universal.release/Mono/etc osx_template.app/Contents/Resources/data.mono.osx.universal.release/Mono
+cp -rp out/macosx/templates-mono/data.mono.osx.universal.release_debug/Mono/lib osx_template.app/Contents/Frameworks/data.mono.osx.universal.release_debug/Mono
+cp -rp out/macosx/templates-mono/data.mono.osx.universal.release_debug/Mono/etc osx_template.app/Contents/Resources/data.mono.osx.universal.release_debug/Mono
```

**Comment by bruvzg** [comment]
> Was just seeing problems if you enable "Hardened Runtime" without an accompanying entitlements file letting Mono work. 

There's an option to add entitlements file, but we probably do need to add default one for the Mono exports.

**Comment by sjml** [comment]
> There are few `dylib`s in the `GodotSharp/Mono/lib`, even if signing will work with `--deep`, it's not the correct way to put them to the `Resources`.
> 
> Only `etc` should be in `Resources`, and `--deep` should not be necessary:

I know that's the preferred way, but codesign won't accept it. The current editor is **also** not able to be codesigned -- we get this error: 

```
Godot_mono.app: bundle format unrecognized, invalid, or unsuitable
In subcomponent: /Applications/Godot_mono.app/Contents/Frameworks/GodotSharp/Mono/lib/mono/4.5
```

The problem is that the library files are nested in directories that include periods, which makes codesign try to treat them like a bundle... and then it doesn't recognize the type of bundle, so it craps out. 

So we either need to rename those directories (and probably patch Mono to deal with a new naming structure) or we need to put them someplace else in the `.app` layout. The only other option I see is looking into something like mkbundle, unless I'm missing something.

**Comment by sjml** [comment]
> There's an option to add entitlements file, but we probably do need to add default one for the Mono exports.

Where should that file live? Or should it be generated/inserted during the export if the user hasn't defined one? 

Easiest solution would be to just have the export fail with a very specific error message, but I'm not sure how we feel about that.

**Comment by bruvzg** [comment]
> The problem is that the library files are nested in directories that include periods, which makes codesign try to treat them like a bundle... and then it doesn't recognize the type of bundle, so it craps out.

In the export there's only three `dylib`s right in the `lib`, without any nested folders. I missed there's other stuff in the editor. But it's `dll`s, in there not macOS libraries, only `dylib`s should stay in Frameworks.

Something like:

```
cp -rp out/macosx/tools-mono/GodotSharp/Api Godot_mono.app/Contents/Resources/GodotSharp
cp -rp out/macosx/tools-mono/GodotSharp/Tools Godot_mono.app/Contents/Resources/GodotSharp
cp -rp out/macosx/tools-mono/GodotSharp/Mono/lib/*.dylib Godot_mono.app/Contents/Frameworks/GodotSharp/Mono
cp -rp out/macosx/tools-mono/GodotSharp/Mono/lib/mono Godot_mono.app/Contents/Resources/GodotSharp/Mono/lib
cp -rp out/macosx/tools-mono/GodotSharp/Mono/etc Godot_mono.app/Contents/Resources/GodotSharp/Mono
```

**Comment by sjml** [comment]
> > The problem is that the library files are nested in directories that include periods, which makes codesign try to treat them like a bundle... and then it doesn't recognize the type of bundle, so it craps out.
> 
> In the export there's only three `dylib`s right in the `lib`, without any nested folders. I missed there's other stuff in the editor. But it's `dll`s, in there not macOS libraries, only `dylib`s should stay in Frameworks.
> 
> Something like:
> 
> ```
> cp -rp out/macosx/tools-mono/GodotSharp/Api Godot_mono.app/Contents/Resources/GodotSharp
> cp -rp out/macosx/tools-mono/GodotSharp/Tools Godot_mono.app/Contents/Resources/GodotSharp
> cp -rp out/macosx/tools-mono/GodotSharp/Mono/lib/*.dylib Godot_mono.app/Contents/Frameworks/GodotSharp/Mono
> cp -rp out/macosx/tools-mono/GodotSharp/Mono/lib/mono Godot_mono.app/Contents/Resources/GodotSharp/Mono/lib
> cp -rp out/macosx/tools-mono/GodotSharp/Mono/etc Godot_mono.app/Contents/Resources/GodotSharp/Mono
> ```

Ah, ok. I see what you're saying. Yes, that makes sense. We can leave the `.dylib`s in there and move the `.dll`s to Resources, then? Let me cook a little bit and make sure that will work the way we need it to. Thanks for checking.

**Comment by bruvzg** [comment]
> We can leave the .dylibs in there and move the .dlls to Resources, then?

Exactly, `dylib`s in Frameworks, everything else in Resources.

**Comment by sjml** [comment]
I have a codesignable build of the editor working with the desired layout, and changes to the library loading code, which allays my fears from caveat number 3 in the initial PR description. 

There's a small issue, though, in that Mono really expects `lib` to be a single directory, not two. Right now I have the code set up to consider `Resources/GodotSharp/Mono/lib` to be the "true" library directory, where the runtime finds all of its goodies. *However*, it wants to load the `.dylib`s during initialization, and it pulls their locations from `Resources/GodotSharp/Mono/etc/mono/config`, where they are defined as living in `$mono_libdir/`. I got my build working by hand-patching this file to `$mono_libdir/../../../../Frameworks/GodotSharp/Mono/lib`. 

On top of being aesthetically displeasing (I'm going to experiment and see if things *really* need to be that nested), it has a bit of a code smell to it. But it **does** work.

@bruvzg, how do you feel about this? Is it something that should be addressed by the mono-build scripts, or is doing some (relatively easy) processing on the `config` file ok? 

(Holding off on updating the export templates until we feel solid about the editor build, but they're a relatively easy setup once it's good.)

**Comment by sjml** [comment]
Starting on the export stuff, and I think I've got it working. One thing I'm not able to test is `data_game_assemblies_dir`. It used to get set to `../Frameworks/GodotSharp/Assemblies` but since they would be `.dll` files I thought they'd be better put in `Resources`. 

How does this get used, though? So far as I can tell all the assemblies referenced in the project get put into the `.pck` during export. Is this for people who might need to add their own assemblies for manual loading later? 

If someone has an example project that uses extra assemblies like this, I'm happy to check that it still works.

**Comment by sjml** [comment]
I've rebased this to master -- any additional thoughts on how best to handle the modifications to the config file?

**Comment by neikeq** [comment]
>2. The export no longer has a folder called `data_{GAMENAME}`, since the Mono distribution is more split up through the `.app`. I assume it was originally called that to have parity with the Linux and Windows exports, but since Mac applications are all bundled together and those details are invisible to the user, I didn't think that needed to be preserved. If it's significant for some other reason, please let me know.

This was make like this to make it easy to debug Godot during development. Having to create an app bundle complicates things.

**Comment by neikeq** [comment]
From what I understand now we have the data folder for macOS split between `data.*.frameworks.*` and `data.*.resources.*`. Yet this split is something that is done by [godot-build-scripts](https://github.com/godotengine/godot-build-scripts) rather than the mono module build in this repo which still creates the unified data directory: https://github.com/godotengine/godot/blob/d834789f475d431b10dcaef8804cd75dcd8b47dd/modules/mono/build_scripts/mono_configure.py#L403-L430

IMO we should make the mono module build take care of it. This makes it less problematic for [godot-build-scripts](https://github.com/godotengine/godot-build-scripts). Keeping this logic in the SCons build is also good as not everyone else uses our release build scripts.

**Comment by sjml** [comment]
> This was make like this to make it easy to debug Godot during development. Having to create an app bundle complicates things.

I was finding that I couldn't get the `master` to run without an app bundle, as it was the only way to make it consistently find `libMoltenVK.dylib`. That said, I didn't spend too much time trying to fix it once I resigned myself to building the app bundle. I definitely don't want to make ongoing dev more complicated at the expense of shipping builds being signable. 

I agree it would be nice to keep the Mono files all together, but to get a signable directory layout that is set up the way @bruvzg (and Apple guidelines) prefer, it looks like it will have to be split. Would you want to see this behind a flag set by SCons so that it only happens during the shipping builds?

**Comment by bruvzg** [comment]
> I was finding that I couldn't get the master to run at all without an app bundle, as it was the only way to make it consistently find libMoltenVK.dylib.

It's possible to run a standalone executable by setting `VK_ICD_FILENAMES` environment variable (e.g. running it using `VK_ICD_FILENAMES=./MoltenVK_icd.json ./godot` command), with the absolute path to the `dylib` in the `.json`, or by placing the same `.json` in the  `vulkan/icd.d/` subfolder in the executable folder (in case of bundle it's in `Resources/vulkan/icd.d/` and have relative path to `dylib`).

**Comment by sjml** [comment]
> It's possible to run a standalone executable by setting `VK_ICD_FILENAMES` environment variable (e.g. running it using `VK_ICD_FILENAMES=./MoltenVK_icd.json ./godot` command), with the absolute path to the `dylib` in the `.json`, or by placing the same `.json` in the `vulkan/icd.d/` subfolder in the executable folder (in case of bundle it's in `Resources/vulkan/icd.d/` and have relative path to `dylib`).

Yeah, for some reason I couldn't it to load the `.json` file from the path in the environment variable. Didn't try placing it in a subdirectory next to the executable, though. Like I said, I didn't push on it too hard since it seemed like things were kind of in flux and I had something working.

**Comment by neikeq** [comment]
>I was finding that I couldn't get the `master` to run at all without an app bundle, as it was the only way to make it consistently find `libMoltenVK.dylib`. ...

Ah, I see. I haven't touched macOS with master after the Vulkan merge, only with 3.2. If latest master no longer supports running without creating an app bundle then I guess this change is fine.

>I agree it would be nice to keep the Mono files all together, but to get a signable directory layout that is set up the way @bruvzg (and Apple guidelines) prefer, it looks like it will have to be split. Would you want to see this behind a flag set by SCons so that it only happens during the shipping builds? 

I don't want to keep these files all together in a single data directory, I'm fine with the change. I want it to be SCons who outputs these files already split into the two directories (`data.*.frameworks.*` and `data.*.resources.*`).

**Comment by sjml** [comment]
> I don't want to keep these files all together in a single data directory, I'm fine with the change. I want it to be SCons who outputs these files already split into the two directories (`data.*.frameworks.*` and `data.*.resources.*`).

Ah, gotcha. OK, this will mean my learning some SCons, then, so it might be a little while before I can tackle the change. (Unless someone who knows what they are doing might be able to have a go at it?)

**Comment by neikeq** [comment]
I can do the SCons part. I just need to know what needs to go in each of the two directories as it's not 100% clean to me from the changes.

**Comment by bruvzg** [comment]
> I can do the SCons part. I just need to know what needs to go in each of the two directories as it's not 100% clean to me from the changes.

`Frameworks` subfolder should have only native macOS libraries (`*.dylib`s), `MacOS` subfolder should have only native macOS executable, everything else (`dll`s, config files, etc.) should be in `Resources`.

**Comment by neikeq** [comment]
I've made the changes I mentioned. Feel free to use it or tweak it as needed: https://github.com/neikeq/godot/commit/ff6ccb09f4df31bdd79dd953a2a0f72ada9edda4

The changes are as follows for export templates (from what I understood from this PR, we get rid of the `/Mono/` part and copy `lib` and `etc` directly into the data dir root):

| Before | After |
| -------- | ------- |
| `data.mono.{platform}.{bits}.{target}/Mono/lib/*.dylibs` | `data.mono.{platform}.{bits}.frameworks.{target}/lib/*.dylibs` |
| `data.mono.{platform}.{bits}.{target}/Mono/etc/*`          | `data.mono.{platform}.{bits}.resources.{target}/etc/*`             |

And for the editor:

| Before | After |
| -------- | ------- |
| `GodotSharp/Api/*`                         | `GodotSharp.resources/Api/*`                          |
| `GodotSharp/Mono/etc/*`                | `GodotSharp.resources/Mono/etc/*`                |
| `GodotSharp/Mono/lib/mono/4.5/*` | `GodotSharp.resources/Mono/lib/mono/4.5/*` |
| `GodotSharp/Mono/lib/*.dylibs`       | `GodotSharp.frameworks/Mono/lib/*.dylibs`    |
| `GodotSharp/Tools/*`                      | `GodotSharp.resources/Tools/*`                       |

**Comment by akien-mga** [comment]
The changes suggested by @neikeq would still need to be added to this PR, are you available to work further on it @sjml?
We're actually in the process of figuring out signing and notarization for official releases so this will be quite useful for the upcoming 3.2.4 release.

**Comment by sjml** [comment]
> The changes suggested by @neikeq would still need to be added to this PR, are you available to work further on it @sjml?
> We're actually in the process of figuring out signing and notarization for official releases so this will be quite useful for the upcoming 3.2.4 release.

Hello! Sorry I went MIA -- my Godot project was backburnered for a bit and I had some real-life things crop up as well. I have some bandwidth in the next week or so to jump in on this, though, so will review the changes ASAP. What's the current timetable on 3.2.4?

**Comment by akien-mga** [comment]
> What's the current timetable on 3.2.4?

Hard to say as it depends on which bugs are found and are critical enough to delay the release. But the best case would be within the next two weeks.

**Comment by sjml** [comment]
> Hard to say as it depends on which bugs are found and are critical enough to delay the release. But the best case would be within the next two weeks.

Great, good to know. I'll get my branch synced to the master in the next few days and then can hopefully apply the changes by the end of the week/end. Thanks for poking me!

**Comment by sjml** [comment]
Quick update: I'm living in a region with very flaky internet and have had trouble pulling the Godot repo, and since Git doesn't do well with resuming broken transfers, it's been a pain. Currently have a workflow that involves SSHing to a more stable connection, tarballing the repo there and then using other transfer methods that can resume when they stall... but you can imagine that it impedes the process a bit. 😉 

Still working here, but I can't promise it in time for 3.2.4. Sorry about that. Will update when I can. 😢

**Comment by akien-mga** [comment]
I went ahead and rebased this PR + amended @neikeq's changes from https://github.com/godotengine/godot/pull/43768#issuecomment-747515430 directly into the commit (I could have kept them as separate commits but it seems they're both necessary parts of the same change so it's best in a single commit IMO).

I haven't actually tested the changes yet, but I'll do a `3.2` backport and see if it enables me to sign the macOS editor for `3.2.4-rc`.

**Comment by akien-mga** [comment]
@neikeq With your changes applied I get the following structure after compiling an editor build:
```
.
./GodotSharp
./GodotSharp/Tools
./GodotSharp/Tools/GodotTools.IdeMessaging.dll
./GodotSharp/Tools/Microsoft.Build.dll
./GodotSharp/Tools/Microsoft.Build.Framework.dll
./GodotSharp/Tools/Newtonsoft.Json.dll
./GodotSharp/Tools/Semver.dll
./GodotSharp/Tools/Microsoft.VisualStudio.Setup.Configuration.Interop.dll
./GodotSharp/Tools/System.Buffers.dll
./GodotSharp/Tools/System.Collections.Immutable.dll
./GodotSharp/Tools/System.Memory.dll
./GodotSharp/Tools/System.Numerics.Vectors.dll
./GodotSharp/Tools/System.Runtime.CompilerServices.Unsafe.dll
./GodotSharp/Tools/System.Threading.Tasks.Dataflow.dll
./GodotSharp/Tools/GodotTools.BuildLogger.dll
./GodotSharp/Tools/GodotTools.ProjectEditor.dll
./GodotSharp/Tools/GodotTools.Core.dll
./GodotSharp/Tools/GodotTools.Core.pdb
./GodotSharp/Tools/GodotTools.BuildLogger.pdb
./GodotSharp/Tools/GodotTools.ProjectEditor.pdb
./GodotSharp/Tools/MSBuild.exe
./GodotSharp/Tools/GodotTools.dll
./GodotSharp/Tools/GodotTools.pdb
./GodotSharp/Api
./GodotSharp/Api/Release
./GodotSharp/Api/Release/GodotSharp.dll
./GodotSharp/Api/Release/GodotSharp.pdb
./GodotSharp/Api/Release/GodotSharp.xml
./GodotSharp/Api/Release/GodotSharpEditor.dll
./GodotSharp/Api/Release/GodotSharpEditor.pdb
./GodotSharp/Api/Release/GodotSharpEditor.xml
./GodotSharp/Api/Debug
./GodotSharp/Api/Debug/GodotSharp.dll
./GodotSharp/Api/Debug/GodotSharp.pdb
./GodotSharp/Api/Debug/GodotSharp.xml
./GodotSharp/Api/Debug/GodotSharpEditor.dll
./GodotSharp/Api/Debug/GodotSharpEditor.pdb
./GodotSharp/Api/Debug/GodotSharpEditor.xml
./GodotSharp.frameworks
./GodotSharp.frameworks/Mono
./GodotSharp.frameworks/Mono/lib
./GodotSharp.frameworks/Mono/lib/libmono-btls-shared.dylib
./GodotSharp.frameworks/Mono/lib/libmono-native-compat.dylib
./GodotSharp.frameworks/Mono/lib/libMonoPosixHelper.dylib
./GodotSharp.resources
./GodotSharp.resources/Mono
./GodotSharp.resources/Mono/etc
./GodotSharp.resources/Mono/etc/mono
./GodotSharp.resources/Mono/etc/mono/2.0
./GodotSharp.resources/Mono/etc/mono/2.0/DefaultWsdlHelpGenerator.aspx
./GodotSharp.resources/Mono/etc/mono/2.0/machine.config
./GodotSharp.resources/Mono/etc/mono/2.0/settings.map
./GodotSharp.resources/Mono/etc/mono/2.0/web.config
./GodotSharp.resources/Mono/etc/mono/2.0/Browsers
./GodotSharp.resources/Mono/etc/mono/2.0/Browsers/Compat.browser
./GodotSharp.resources/Mono/etc/mono/4.5
./GodotSharp.resources/Mono/etc/mono/4.5/DefaultWsdlHelpGenerator.aspx
./GodotSharp.resources/Mono/etc/mono/4.5/machine.config
./GodotSharp.resources/Mono/etc/mono/4.5/settings.map
./GodotSharp.resources/Mono/etc/mono/4.5/web.config
./GodotSharp.resources/Mono/etc/mono/4.5/Browsers
./GodotSharp.resources/Mono/etc/mono/4.5/Browsers/Compat.browser
./GodotSharp.resources/Mono/etc/mono/4.0
./GodotSharp.resources/Mono/etc/mono/4.0/DefaultWsdlHelpGenerator.aspx
./GodotSharp.resources/Mono/etc/mono/4.0/machine.config
./GodotSharp.resources/Mono/etc/mono/4.0/settings.map
./GodotSharp.resources/Mono/etc/mono/4.0/web.config
./GodotSharp.resources/Mono/etc/mono/4.0/Browsers
./GodotSharp.resources/Mono/etc/mono/4.0/Browsers/Compat.browser
./GodotSharp.resources/Mono/etc/mono/mconfig
./GodotSharp.resources/Mono/etc/mono/mconfig/config.xml
./GodotSharp.resources/Mono/etc/mono/browscap.ini
./GodotSharp.resources/Mono/etc/mono/config
./GodotSharp.resources/Mono/lib
./GodotSharp.resources/Mono/lib/mono
./GodotSharp.resources/Mono/lib/mono/4.5
./GodotSharp.resources/Mono/lib/mono/4.5/Accessibility.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Commons.Xml.Relaxng.dll
./GodotSharp.resources/Mono/lib/mono/4.5/CustomMarshalers.dll
./GodotSharp.resources/Mono/lib/mono/4.5/I18N.CJK.dll
./GodotSharp.resources/Mono/lib/mono/4.5/I18N.MidEast.dll
./GodotSharp.resources/Mono/lib/mono/4.5/I18N.Other.dll
./GodotSharp.resources/Mono/lib/mono/4.5/I18N.Rare.dll
./GodotSharp.resources/Mono/lib/mono/4.5/I18N.West.dll
./GodotSharp.resources/Mono/lib/mono/4.5/I18N.dll
./GodotSharp.resources/Mono/lib/mono/4.5/IBM.Data.DB2.dll
./GodotSharp.resources/Mono/lib/mono/4.5/ICSharpCode.SharpZipLib.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Microsoft.Build.Engine.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Microsoft.Build.Framework.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Microsoft.Build.Tasks.v4.0.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Microsoft.Build.Utilities.v4.0.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Microsoft.Build.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Microsoft.CSharp.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Microsoft.CodeAnalysis.CSharp.Scripting.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Microsoft.CodeAnalysis.CSharp.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Microsoft.CodeAnalysis.Scripting.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Microsoft.CodeAnalysis.VisualBasic.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Microsoft.CodeAnalysis.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Microsoft.VisualC.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Microsoft.Web.Infrastructure.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Mono.Btls.Interface.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Mono.CSharp.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Mono.Cairo.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Mono.CodeContracts.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Mono.CompilerServices.SymbolWriter.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Mono.Data.Sqlite.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Mono.Data.Tds.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Mono.Debugger.Soft.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Mono.Http.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Mono.Management.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Mono.Messaging.RabbitMQ.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Mono.Messaging.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Mono.Parallel.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Mono.Posix.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Mono.Profiler.Log.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Mono.Security.Win32.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Mono.Security.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Mono.Simd.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Mono.Tasklets.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Mono.WebBrowser.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Mono.XBuild.Tasks.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Novell.Directory.Ldap.dll
./GodotSharp.resources/Mono/lib/mono/4.5/PEAPI.dll
./GodotSharp.resources/Mono/lib/mono/4.5/RabbitMQ.Client.dll
./GodotSharp.resources/Mono/lib/mono/4.5/SMDiagnostics.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Collections.Immutable.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.ComponentModel.Composition.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.ComponentModel.DataAnnotations.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Configuration.Install.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Configuration.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Core.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Data.DataSetExtensions.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Data.Entity.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Data.Linq.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Data.OracleClient.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Data.Services.Client.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Data.Services.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Data.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Deployment.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Design.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.DirectoryServices.Protocols.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.DirectoryServices.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Drawing.Design.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Drawing.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Dynamic.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.EnterpriseServices.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.IO.Compression.FileSystem.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.IO.Compression.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.IdentityModel.Selectors.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.IdentityModel.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Json.Microsoft.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Json.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Management.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Memory.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Messaging.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Net.Http.Formatting.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Net.Http.WebRequest.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Net.Http.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Net.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Numerics.Vectors.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Numerics.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Reactive.Core.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Reactive.Debugger.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Reactive.Experimental.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Reactive.Interfaces.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Reactive.Linq.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Security.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Reactive.Observable.Aliases.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Reactive.PlatformServices.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Reactive.Providers.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Reactive.Runtime.Remoting.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Reactive.Windows.Forms.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Reactive.Windows.Threading.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Reflection.Context.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Reflection.Metadata.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Runtime.Caching.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Web.Http.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Runtime.CompilerServices.Unsafe.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Runtime.DurableInstancing.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Runtime.Remoting.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Runtime.Serialization.Formatters.Soap.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Runtime.Serialization.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.ServiceModel.Activation.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.ServiceModel.Discovery.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.ServiceModel.Internals.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.ServiceModel.Routing.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.ServiceModel.Web.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.ServiceModel.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.ServiceProcess.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Threading.Tasks.Dataflow.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Threading.Tasks.Extensions.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Transactions.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Web.Abstractions.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Web.ApplicationServices.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Web.DynamicData.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Web.Extensions.Design.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Web.Extensions.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Web.Http.SelfHost.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Web.Http.WebHost.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Web.Mobile.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Web.Mvc.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Web.Razor.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Web.RegularExpressions.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Web.Routing.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Web.Services.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Web.WebPages.Deployment.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Web.WebPages.Razor.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Web.WebPages.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Web.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Windows.Forms.DataVisualization.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Windows.Forms.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Windows.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Workflow.Activities.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Workflow.ComponentModel.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Workflow.Runtime.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Xaml.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Xml.Linq.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Xml.Serialization.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.Xml.dll
./GodotSharp.resources/Mono/lib/mono/4.5/System.dll
./GodotSharp.resources/Mono/lib/mono/4.5/WebMatrix.Data.dll
./GodotSharp.resources/Mono/lib/mono/4.5/WindowsBase.dll
./GodotSharp.resources/Mono/lib/mono/4.5/cscompmgd.dll
./GodotSharp.resources/Mono/lib/mono/4.5/mscorlib.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.IO.Compression.ZipFile.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.IO.FileSystem.AccessControl.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.IO.FileSystem.DriveInfo.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.IO.FileSystem.Primitives.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.IO.FileSystem.Watcher.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.IO.FileSystem.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.IO.IsolatedStorage.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.IO.MemoryMappedFiles.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.IO.Pipes.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.IO.UnmanagedMemoryStream.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.IO.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Linq.Expressions.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Linq.Parallel.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Linq.Queryable.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Linq.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Net.AuthenticationManager.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Net.Cache.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Net.Http.Rtc.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Net.HttpListener.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Net.Mail.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Net.NameResolution.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Net.NetworkInformation.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Net.Ping.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Net.Primitives.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Net.Requests.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Net.Security.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Net.ServicePoint.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Net.Sockets.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Net.Utilities.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Net.WebHeaderCollection.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Net.WebSockets.Client.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Net.WebSockets.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.ObjectModel.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Reflection.Emit.ILGeneration.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Reflection.Emit.Lightweight.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Reflection.Emit.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Reflection.Extensions.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Reflection.Primitives.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Reflection.TypeExtensions.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Reflection.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Resources.Reader.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Resources.ReaderWriter.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Resources.ResourceManager.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Resources.Writer.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Runtime.CompilerServices.VisualC.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Runtime.Extensions.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Runtime.Handles.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Runtime.InteropServices.RuntimeInformation.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Runtime.InteropServices.WindowsRuntime.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Runtime.InteropServices.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Runtime.Numerics.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Runtime.Serialization.Formatters.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Runtime.Serialization.Json.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Runtime.Serialization.Primitives.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Runtime.Serialization.Xml.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Runtime.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Security.AccessControl.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Security.Claims.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Security.Cryptography.Algorithms.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Security.Cryptography.Csp.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Security.Cryptography.DeriveBytes.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Security.Cryptography.Encoding.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Security.Cryptography.Encryption.Aes.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Security.Cryptography.Encryption.ECDiffieHellman.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/Microsoft.Win32.Primitives.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/Microsoft.Win32.Registry.AccessControl.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/Microsoft.Win32.Registry.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.AppContext.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Collections.Concurrent.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Collections.NonGeneric.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Collections.Specialized.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Collections.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.ComponentModel.Annotations.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.ComponentModel.EventBasedAsync.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.ComponentModel.Primitives.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.ComponentModel.TypeConverter.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.ComponentModel.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Console.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Data.Common.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Data.SqlClient.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Diagnostics.Contracts.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Diagnostics.Debug.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Diagnostics.FileVersionInfo.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Diagnostics.Process.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Diagnostics.StackTrace.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Diagnostics.TextWriterTraceListener.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Diagnostics.Tools.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Diagnostics.TraceEvent.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Diagnostics.TraceSource.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Diagnostics.Tracing.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Drawing.Primitives.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Dynamic.Runtime.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Globalization.Calendars.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Globalization.Extensions.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Globalization.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Security.Cryptography.Encryption.ECDsa.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Security.Cryptography.Encryption.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Security.Cryptography.Hashing.Algorithms.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Security.Cryptography.Hashing.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Security.Cryptography.Primitives.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Security.Cryptography.ProtectedData.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Security.Cryptography.RSA.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Security.Cryptography.RandomNumberGenerator.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Security.Cryptography.X509Certificates.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Security.Principal.Windows.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Security.Principal.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Security.SecureString.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.ServiceModel.Duplex.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.ServiceModel.Http.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.ServiceModel.NetTcp.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.ServiceModel.Primitives.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.ServiceModel.Security.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.ServiceProcess.ServiceController.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Text.Encoding.CodePages.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Text.Encoding.Extensions.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Text.Encoding.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Text.RegularExpressions.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Threading.AccessControl.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Threading.Overlapped.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Threading.Tasks.Parallel.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Threading.Tasks.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Threading.Thread.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Threading.ThreadPool.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Threading.Timer.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Threading.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.ValueTuple.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Xml.ReaderWriter.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Xml.XDocument.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Xml.XPath.XDocument.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Xml.XPath.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Xml.XmlDocument.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Xml.XmlSerializer.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/System.Xml.Xsl.Primitives.dll
./GodotSharp.resources/Mono/lib/mono/4.5/Facades/netstandard.dll
./GodotSharp.resources/Tools
./godot.osx.opt.tools.x86_64.mono
```

I suspect that the files under `GodotSharp` are meant to be in `GodotSharp.resources` too?

**Comment by akien-mga** [comment]
I fixed the issue with `Api` which had been missed in the patch, and I'll debug what's happening for `Tools` (the code seems correct).

**Comment by akien-mga** [comment]
Reverting my change for `Api` as it breaks the solution build. For the reference, the change was:
```
diff --git a/modules/mono/build_scripts/api_solution_build.py b/modules/mono/build_scripts/api_solution_build.py
index 9abac22df6..b2417ddc8e 100644
--- a/modules/mono/build_scripts/api_solution_build.py
+++ b/modules/mono/build_scripts/api_solution_build.py
@@ -62,7 +62,11 @@ def build(env_mono):
 
     for build_config in ["Debug", "Release"]:
         output_dir = Dir("#bin").abspath
-        editor_api_dir = os.path.join(output_dir, "GodotSharp", "Api", build_config)
+        editor_api_dir = (
+            os.path.join(output_dir, "GodotSharp", "Api", build_config)
+            if env_mono["platform"] != "osx"
+            else os.path.join(output_dir, "GodotSharp.resources", "Api", build_config)
+        )
 
         targets = [os.path.join(editor_api_dir, filename) for filename in target_filenames]
 
```

File: modules/mono/godotsharp_dirs.cpp [hunk 1]
```diff
@@ -216,13 +216,11 @@ class _GodotSharpDirs {
 #endif
 
 #ifdef OSX_ENABLED
-		if (!DirAccess::exists(data_mono_root_dir)) {
-			data_mono_etc_dir = exe_dir.plus_file("../Resources/GodotSharp/Mono/etc");
-			data_mono_lib_dir = exe_dir.plus_file("../Frameworks/GodotSharp/Mono/lib");
-		}
+		data_mono_etc_dir = exe_dir.plus_file("../Resources/GodotSharp/Mono/etc");
+		data_mono_lib_dir = exe_dir.plus_file("../Frameworks/GodotSharp/Mono/lib");
```
Comment (akien-mga) [inline modules/mono/godotsharp_dirs.cpp:220]: I changed those two and `data_game_assemblies_dir` back as the `GodotSharp/` part had been removed, while it's still being used by the updated build scripts from @neikeq.

File: modules/mono/godotsharp_dirs.cpp [hunk 2]
```diff
@@ -179,16 +179,16 @@ class _GodotSharpDirs {
...
 
 		if (!DirAccess::exists(data_editor_prebuilt_api_dir)) {
-			data_editor_prebuilt_api_dir = exe_dir.plus_file("../Frameworks/GodotSharp/Api");
+			data_editor_prebuilt_api_dir = exe_dir.plus_file("../Resources/GodotSharp/Api");
 		}
 
 		if (!DirAccess::exists(data_mono_root_dir)) {
 			data_mono_etc_dir = exe_dir.plus_file("../Resources/GodotSharp/Mono/etc");
-			data_mono_lib_dir = exe_dir.plus_file("../Frameworks/GodotSharp/Mono/lib");
+			data_mono_lib_dir = exe_dir.plus_file("../Resources/GodotSharp/Mono/lib");
```
Comment (akien-mga) [inline modules/mono/godotsharp_dirs.cpp:191]: Do we need a new dir string to keep track of the fact that OSX has some lib stuff in `../Resources/GodotSharp/Mono/lib` and other in `../Frameworks/GodotSharp/Mono/lib`? Not also that the `!TOOLS_ENABLED` codepath uses `Frameworks` while this one uses `Resources`.

**Comment by akien-mga** [comment]
See https://github.com/godotengine/godot-build-scripts/pull/24, the **editor** .app which I can generate with this PR can now be signed and notarized but it's broken, it can't find the Mono libs. Help needed :)

File: modules/mono/godotsharp_dirs.cpp (hunk 2 above)
Comment (neikeq) [reply modules/mono/godotsharp_dirs.cpp:191]: This is likely the reason it cannot find the Mono native libs. We append this directory to PATH for Mono to search for the libs there: https://github.com/godotengine/godot/blob/43264c63724ef040606936c65a1c24edb9d1f862/modules/mono/mono_gd/gd_mono.cpp#L240-L248

**Comment by neikeq** [comment]
In the end we decided to put everything in `Contents/Resources/GodotSharp/`. I updated the commit accordingly.
This goes together with https://github.com/godotengine/godot-build-scripts/pull/24 which needs to be updated to work with this last change.
I removed `--deep` since that is not needed with #46618.

File: modules/mono/godotsharp_dirs.cpp (hunk 2 above)
Comment (akien-mga) [reply modules/mono/godotsharp_dirs.cpp:191]: Resolved since we put all in `Resources`.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks everyone for the joint work on this issue!

I'll update container build scripts soon and make some binaries to confirm that all works as expected.

File: platform/osx/export/export.cpp [hunk 3]
```diff
@@ -114,7 +114,7 @@ class EditorExportPlatformOSX : public EditorExportPlatform {
 	virtual void get_platform_features(List<String> *r_features) override {
 		r_features->push_back("pc");
 		r_features->push_back("s3tc");
-		r_features->push_back("OSX");
+		r_features->push_back("macOS");
```
Comment (bruvzg) [inline platform/osx/export/export.cpp:117]: This line should be skipped on cherry-picking to 3.2.

Comment (akien-mga) [reply platform/osx/export/export.cpp:117]: Thanks for the reminder!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
