### PR TITLE
Fix libjpeg-turbo not working on 32-bit builds

### LINKED ISSUE #106172: Web: Failing to open some types of jpg files that opened fine in 4.4.1.
### Tested versions

Found in master branch 4 days ago: [[d4dabd15aa85a6c7bb1a62eb412bc8fbe901ac5c](https://github.com/godotengine/godot/commit/d4dabd15aa85a6c7bb1a62eb412bc8fbe901ac5c)]

### System information

Godot v4.4.1.stable - Nobara Linux 40 (KDE Plasma) on Wayland - X11 display driver, Multi-window, 2 monitors - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4070 SUPER (nvidia; 565.77) - Intel(R) Core(TM) i7-14700KF (28 threads)

### Issue description

My web export can no longer read any of my jpg files from user:// (example below).  They worked fine in 4.4.1.  

I see in the web console: "ERROR: Failed to load image. Error 15. at: load_from_file (core/io/image.cpp:2551) and none of the jpgs load. ERROR 15 appears to be ERR_FILE_UNRECOGNIZED according to core/error/error_list.h. This error is printed when calling Image.load_from_file() with the jpg filename.  

My other files in user:// load just fine.  Even pngs are fine.  

This might be due to the change in jpg libraries: [Use libjpeg-turbo for improved jpg compatibility and speed #104347](https://github.com/godotengine/godot/pull/104347)
 
I created the export using `scons platform=web target=template_release`

More details of my efforts here: https://forum.godotengine.org/t/compiled-web-export-template-doesnt-support-jpgs-but-pngs-work/109841

Image

### Steps to reproduce

1. Image.load_from_file() with the attached file 
2. Build for web (might happen for other builds - haven't tested)

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by DanielKinsman**
Sorry for missing this when I did the cmake -> scons translation for libjpeg-turbo.

*Bugsquad edit:*
- Fixes #106172.

### CODE REVIEW

File: modules/jpg/SCsub [hunk 1]
```diff
@@ -84,6 +84,11 @@ def source_paths(files):
 
 env_jpg.Prepend(CPPEXTPATH=[thirdparty_dir + "/src"])
 
+if env["arch"].endswith("32"):
```
Comment (DanielKinsman) [inline modules/jpg/SCsub:87]: Is there a better way of determining this?

Comment (akien-mga) [reply modules/jpg/SCsub:87]: Hm yeah that's not great.

I think it would be better to keep this in `jconfigint.h` somehow and ask the pre-processor for what's the size of `size_t`.
But from a quick look I couldn't find a reliable, portable way to do this, aside from checking arch-specific macros directly.

I did find `__SIZEOF_SIZE_T__` which seems to be a non-standard GCC/Clang builtin and which works in my tests on Linux, but that's not defined for MSVC.

So we'd have to do something like that:
```cpp
#if defined(__SIZEOF_SIZE_T__)
  #define SIZEOF_SIZE_T __SIZEOF_SIZE_T__
#elif defined(_WIN64)
  #define SIZEOF_SIZE_T 8
#elif defined(_WIN32)
  #define SIZEOF_SIZE_T 4
#else
  #error "Cannot determine size of size_t"
#endif
```

Not sure if it's worth it, but that would be possibly more future proof for potential other LLVM-based platforms with alternative architectures.

Otherwise, hardcoding it here from SCons is also fine, but maybe we should specify the 32-bit architectures explicitly, in case we later add an arch that doesn't end in `32` or `64`.

So that would be
```python
if env["arch"] in ["x86_32", "arm32", "ppc32", "wasm32"]
```

Comment (fire) [reply modules/jpg/SCsub:87]: I think that the godot engine build system knows if an arch is ~64 bit so we probably want a godot engine define exposing that? It's still crufty to parse the arch string.

Comment (akien-mga) [reply modules/jpg/SCsub:87]: I think `if env["arch"] in ["x86_32", "arm32", "ppc32", "wasm32"]` is the simplest.

Comment (DanielKinsman) [reply modules/jpg/SCsub]: I decided to go with the preprocessor approach because otherwise it might be a trap for people adding new architectures who have no idea that that have to change a line here.

File: thirdparty/libjpeg-turbo/src/jconfigint.h [hunk 2]
```diff
@@ -33,10 +33,18 @@
 #define PACKAGE_NAME  "libjpeg-turbo"
 
 /* Version number of package */
-#define VERSION  "3.1.1"
+#define VERSION  "3.1.0"
```
Comment (DanielKinsman) [inline thirdparty/libjpeg-turbo/src/jconfigint.h:36]: Looks like I missed this in the original libjpeg-turbo PR after going back to the stable version.

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
