### PR TITLE
Don't stop export if rcedit path is invalid

### LINKED ISSUE #28456: Invalid path to rcedit will break windows exports and give a misleading popup message
**Godot version:**
3.1 Stable

**OS/device including version:**
Windows 10

**Issue description:**
If you move/remove rcedit and fail to update your editor settings to reflect the path change and attempt to export your project you will get the following message:

> Failed to export the project for platform 'Windows Desktop'.
> Export templates seem to be missing or invalid

Godot-Stable_2019-04-26_07-53-14

**Steps to reproduce:**
1. Create an empty project & hit the build button to generate the solution
2. Add a scene with any node, attach a blank script to it. Can just create a generated script from the editor
3. Add rcedit 64 to your project settings, delete the exe from where ever it's located (for testing)
4. Attempt to export a Windows Desktop project and you'll see the incorrect alert message.

**Minimal reproduction project:**
[EXPORTER.zip](https://github.com/godotengine/godot/files/3123080/EXPORTER.zip)

**Other information**
It does give you the correct error in the output editor and console window, but if you're on a different tab like "Mono" build tab you won't notice this error at all.

```
** Debug Process Stopped **
 platform/windows/export/export.cpp:58 - Could not find rcedit executable at Z:/Downloads/rcedit-x64.exe, aborting.
 editor/project_export.cpp:981 - Failed to export the project for platform 'Windows Desktop'.
```

### PR DESCRIPTION
**Pull request by KoBeWi**
Supposed to resolve #28456

### CODE REVIEW

File: platform/windows/export/export.cpp [hunk 1]
```diff
@@ -69,17 +69,17 @@ Error EditorExportPlatformWindows::export_project(const Ref<EditorExportPreset>
 	}
 
 	if (!FileAccess::exists(rcedit_path)) {
-		ERR_PRINTS("Could not find rcedit executable at " + rcedit_path + ", aborting.");
-		return ERR_FILE_NOT_FOUND;
+		ERR_PRINTS("Could not find rcedit executable at " + rcedit_path + ", no icon will be included.");
```
Comment (bruvzg) [inline platform/windows/export/export.cpp]: > no icon will be included

It's not exclusively for icons, everything in `application/` depends on `rcedit`, app/company name, version, copyright info.

File: platform/windows/export/export.cpp [hunk 2]
```diff
@@ -69,17 +69,17 @@ Error EditorExportPlatformWindows::export_project(const Ref<EditorExportPreset>
...
+		return OK;
```
Comment (akien-mga) [inline platform/windows/export/export.cpp]: This will make it skip the `codesign` part at the end which is independent from the use of rcedit.

Comment (akien-mga) [reply platform/windows/export/export.cpp]: Though that's already the case currently due to the `rcedit_path == String()` early return, so that's not adding a bug.

Maybe move the whole rcedit stuff to a dedicated private function? This way you can still make it return `OK` while continuing the `export_project` logic to do code signing.

File: platform/windows/export/export.cpp (hunk 1 above)
Comment (KoBeWi) [reply platform/windows/export/export.cpp]: So how to call it correctly? Application info? App metadata?

Comment (bruvzg) [reply platform/windows/export/export.cpp]: >So how to call it correctly? Application info? App metadata?

Microsoft calls it [Version Information](https://docs.microsoft.com/en-us/windows/win32/menurc/versioninfo-resource), I'm not sure what's better.

File: platform/windows/export/export.cpp (hunk 2 above)
Comment (KoBeWi) [reply platform/windows/export/export.cpp]: Done.

**Comment by akien-mga** [comment]
Thanks!
