### PR TITLE
Move "Create Debug Tangents" on MeshInstance3D into an editor plugin

### LINKED ISSUE #50158: "Create Debug Tangents" action on MeshInstance3D is missing undo/redo
### Godot version

4.0.dev (52e3f986a)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 465.31)

### Issue description

The Create Debug Tangents action on MeshInstance3D is missing undo/redo functionality.

### Steps to reproduce

- Create a MeshInstance3D node then add any primitive mesh resource to it.
- Select the MeshInstance3D node, go to the Inspector, click the "toolbox" button then choose **Create Debug Tangents**:

image

- Try to undo the action using <kbd>Ctrl + Z</kbd>.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by MaeIsBad**
This closes https://github.com/godotengine/godot/issues/50158

### CODE REVIEW

**Comment by MaeIsBad** [comment]
Oops I should've ran the format myself, my bad it's kinda late here, added a git-hook so it won't happen again 😅

**Comment by MaeIsBad** [comment]
Third attempt! Now compiles with tools=off

File: scene/3d/mesh_instance_3d.cpp [hunk 1]
```diff
@@ -34,6 +34,11 @@
 #include "core/core_string_names.h"
 #include "physics_body_3d.h"
 
+#include "core/object/undo_redo.h"
+#ifdef TOOLS_ENABLED
+#include "editor/plugins/node_3d_editor_plugin.h"
+#endif
```
Comment (KoBeWi) [inline scene/3d/mesh_instance_3d.cpp:40]: Including editor files in `scene/` code is not allowed (#29730). You should come up with a way that doesn't involve this.

Although looking at the code, it might be tricky to handle as the editor isn't involved in the method aside from calling it.

**Comment by MaeIsBad** [comment]
This moves "Create Debug Tangents" from the manage object properties menu in the inspector(godot 3 screenshot)
image
to the mesh menu above the viewport
image

File: scene/3d/mesh_instance_3d.cpp [hunk 2]
```diff
@@ -383,13 +383,13 @@ void MeshInstance3D::_mesh_changed() {
 	update_gizmos();
 }
 
-void MeshInstance3D::create_debug_tangents() {
+MeshInstance3D *MeshInstance3D::create_debug_tangents_node() {
```
Comment (MaeIsBad) [inline scene/3d/mesh_instance_3d.cpp:386]: I would suggest making create_debug_tangents return the mesh instance it creates and adds as a child, but I think that would require me to open a GIP

File: scene/3d/mesh_instance_3d.cpp [hunk 3]
```diff
@@ -450,15 +450,23 @@ void MeshInstance3D::create_debug_tangents() {
...
+	MeshInstance3D *mi = create_debug_tangents_node();
+	if (!mi) {
+		return;
+	}
+
+	add_child(mi, true);
+	if (is_inside_tree() && this == get_tree()->get_edited_scene_root()) {
+		mi->set_owner(this);
+	} else {
+		mi->set_owner(get_owner());
```
Comment (KoBeWi) [inline scene/3d/mesh_instance_3d.cpp:469]: The old method can be removed I think.

**Review by KoBeWi — APPROVED** [review]

**Comment by KoBeWi** [comment]
Needs squash and rebase btw.

File: scene/3d/mesh_instance_3d.cpp [hunk 4]
```diff
@@ -457,15 +457,23 @@ void MeshInstance3D::create_debug_tangents() {
...
+}
+
+void MeshInstance3D::create_debug_tangents() {
+	MeshInstance3D *mi = create_debug_tangents_node();
+	if (!mi) {
+		return;
+	}
+
+	add_child(mi, true);
+	if (is_inside_tree() && this == get_tree()->get_edited_scene_root()) {
```
Comment (KoBeWi) [inline scene/3d/mesh_instance_3d.cpp:473]: This was previously wrapped in `#ifdef TOOLS_ENABLED`, but I think it's fine to leave it, because `get_edited_scene_root()` just returns null in non-editor builds.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by MaeIsBad** [comment]
Thanks for your patience with me ^^ @KoBeWi
