### PR TITLE
Skip error messages for buttons that don't exist

### LINKED ISSUE #77638: "parse_mapping: Invalid device entry" on Steam version
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

- OS: Windows 10
- Godot Version: v4.0.3.stable.official [5222a99f5]
- Rendering Driver: GLES3 
- Rendering Method: Compatiblity
- Graphics Card: Intel UHD Graphics 630 (HP)
- Graphics Card Driver: version 24.20.100.6025
- CPU: Intel Core i3-8100 

### Issue description

image
Whenever I run any project, even empty ones, I get these 4 errors about input mapping. They are as follows:

`E 0:00:00:0053   parse_mapping: Invalid device mapping entry "x:" in mapping:
03000000790000004318000000000000,dev:gc:GameCube,platform:Windows,a:b1,b:b2,y:b3,x:,start:b9,guide:,back:,leftstick:,rightstick:b0,leftshoulder:b4,rightshoulder:b7,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,rightx:a5,righty:a2,lefttrigger:a3,righttrigger:a4,
  <C++ Error>    Condition "output.length() < 1 || input.length() < 2" is true. Continuing.
  <C++ Source>   core/input/input.cpp:1357 @ parse_mapping()`
`E 0:00:00:0053   parse_mapping: Invalid device mapping entry "guide:" in mapping:
03000000790000004318000000000000,dev:gc:GameCube,platform:Windows,a:b1,b:b2,y:b3,x:,start:b9,guide:,back:,leftstick:,rightstick:b0,leftshoulder:b4,rightshoulder:b7,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,rightx:a5,righty:a2,lefttrigger:a3,righttrigger:a4,
  <C++ Error>    Condition "output.length() < 1 || input.length() < 2" is true. Continuing.
  <C++ Source>   core/input/input.cpp:1357 @ parse_mapping()`
`E 0:00:00:0053   parse_mapping: Invalid device mapping entry "back:" in mapping:
03000000790000004318000000000000,dev:gc:GameCube,platform:Windows,a:b1,b:b2,y:b3,x:,start:b9,guide:,back:,leftstick:,rightstick:b0,leftshoulder:b4,rightshoulder:b7,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,rightx:a5,righty:a2,lefttrigger:a3,righttrigger:a4,
  <C++ Error>    Condition "output.length() < 1 || input.length() < 2" is true. Continuing.
  <C++ Source>   core/input/input.cpp:1357 @ parse_mapping()`
`E 0:00:00:0053   parse_mapping: Invalid device mapping entry "leftstick:" in mapping:
03000000790000004318000000000000,dev:gc:GameCube,platform:Windows,a:b1,b:b2,y:b3,x:,start:b9,guide:,back:,leftstick:,rightstick:b0,leftshoulder:b4,rightshoulder:b7,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,rightx:a5,righty:a2,lefttrigger:a3,righttrigger:a4,
  <C++ Error>    Condition "output.length() < 1 || input.length() < 2" is true. Continuing.
  <C++ Source>   core/input/input.cpp:1357 @ parse_mapping()`

This only happens when I use the Steam version. Using the version downloaded from godotengine.org does not yield this error. I have tried rebooting and reinstalling Godot, neither of which have worked.

### Steps to reproduce

1. Install Godot from Steam
2. Create a new project
3. Run the project

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by DevanOBoyle**
Changed error to continue rather than display a false error message for button mappings the user doesn't care about due to Steam inputting them automatically.

- Fixes #77638

### CODE REVIEW

File: core/input/input.cpp [hunk 1]
```diff
@@ -1356,8 +1356,9 @@ void Input::parse_mapping(String p_mapping) {
 
 		String output = entry[idx].get_slice(":", 0).replace(" ", "");
 		String input = entry[idx].get_slice(":", 1).replace(" ", "");
-		ERR_CONTINUE_MSG(output.length() < 1 || input.length() < 2,
-				vformat("Invalid device mapping entry \"%s\" in mapping:\n%s", entry[idx], p_mapping));
+		if (output.length() < 1 || input.length < 2) {
+      continue;
```
Comment (AThousandShips) [inline core/input/input.cpp:1360]: You need to follow the proper indentation, easiest to use `clang-format`, or set up your IDE with the correct indentation, [see here](https://docs.godotengine.org/en/latest/contributing/development/code_style_guidelines.html)

**Comment by brno32** [comment]
I believe you'll want to squash your commits into just one commit

https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase

**Review by akien-mga — APPROVED** [review]

File: core/input/input.cpp [hunk 2]
```diff
@@ -1356,8 +1356,9 @@ void Input::parse_mapping(String p_mapping) {
 
 		String output = entry[idx].get_slice(":", 0).replace(" ", "");
 		String input = entry[idx].get_slice(":", 1).replace(" ", "");
-		ERR_CONTINUE_MSG(output.length() < 1 || input.length() < 2,
-				vformat("Invalid device mapping entry \"%s\" in mapping:\n%s", entry[idx], p_mapping));
+		if (output.length() < 1 || input.length < 2) {
```
Comment (akien-mga) [inline core/input/input.cpp:1359]: This doesn't compile (missing parentheses for function call).

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.4.
