### PR TITLE
Fix crash on doc dragging in script list panel

### LINKED ISSUE #50897: Dragging doc items in script list panel leads to editor crash
### Godot version

64dc58bfba55c4e5dcdce18bf848abf43332afd0

### System information

Windows 10

### Issue description

editor_crash

Callstack:
```
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] EditorResourcePicker::_is_drop_valid (C:\Git\godot\editor\editor_resource_picker.cpp:508)
[1] EditorResourcePicker::_is_drop_valid (C:\Git\godot\editor\editor_resource_picker.cpp:508)
[2] EditorResourcePicker::_notification (C:\Git\godot\editor\editor_resource_picker.cpp:670)
[3] EditorResourcePicker::_notificationv (C:\Git\godot\editor\editor_resource_picker.h:41)
[4] Object::notification (C:\Git\godot\core\object\object.cpp:843)
[5] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[6] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[7] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[8] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[9] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[10] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[11] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[12] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[13] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[14] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[15] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[16] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[17] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[18] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[19] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[20] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[21] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[22] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[23] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[24] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[25] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[26] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[27] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[28] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[29] Viewport::_propagate_viewport_notification (C:\Git\godot\scene\main\viewport.cpp:1187)
[30] Viewport::_gui_input_event (C:\Git\godot\scene\main\viewport.cpp:2064)
[31] Viewport::input (C:\Git\godot\scene\main\viewport.cpp:3095)
[32] Window::_window_input (C:\Git\godot\scene\main\window.cpp:918)
[33] call_with_variant_args<VisualScriptPropertySelector,Ref<InputEvent> const &> (C:\Git\godot\core\variant\binder_common.h:332)
[34] Callable::call (C:\Git\godot\core\variant\callable.cpp:51)
[35] DisplayServerWindows::_dispatch_input_event (C:\Git\godot\platform\windows\display_server_windows.cpp:1803)
[36] Input::_parse_input_event_impl (C:\Git\godot\core\input\input.cpp:642)
[37] Input::flush_accumulated_events (C:\Git\godot\core\input\input.cpp:858)
[38] DisplayServerWindows::process_events (C:\Git\godot\platform\windows\display_server_windows.cpp:1530)
[39] OS_Windows::run (C:\Git\godot\platform\windows\os_windows.cpp:626)
[40] widechar_main (C:\Git\godot\platform\windows\godot_windows.cpp:163)
[41] _main (C:\Git\godot\platform\windows\godot_windows.cpp:187)
[42] main (C:\Git\godot\platform\windows\godot_windows.cpp:199)
[43] __scrt_common_main_seh (d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[44] BaseThreadInitThunk
-- END OF BACKTRACE --
```

### Steps to reproduce

Open a few documentation pages and try to drag them around that list.

### Minimal reproduction project

Too trivial to reproduce.

### PR DESCRIPTION
**Pull request by Chaosus**
Fix #50897

### CODE REVIEW

File: editor/editor_resource_picker.cpp [hunk 1]
```diff
@@ -505,7 +505,16 @@ bool EditorResourcePicker::_is_drop_valid(const Dictionary &p_drag_data) const {
 	Ref<Resource> res;
 	if (drag_data.has("type") && String(drag_data["type"]) == "script_list_element") {
 		ScriptEditorBase *se = Object::cast_to<ScriptEditorBase>(drag_data["script_list_element"]);
-		res = se->get_edited_resource();
+		if (se) {
+			res = se->get_edited_resource();
+		} else {
+			EditorHelp *eh = Object::cast_to<EditorHelp>(drag_data["script_list_element"]);
```
Comment (pycbouh) [inline editor/editor_resource_picker.cpp:511]: I don't think we need this `else` block. We can't really accept anything from the `EditorHelp` as a valid drop item in the resource picker. It will just crash again `drop_data_fw` where we cast it to `ScriptEditorBase` again.

**Review by YuriSizov — CHANGES_REQUESTED** [review]

**Comment by pycbouh** [comment]
This should also be cherry-picked or backported for 3.x. `3.4-beta2 also crashes.

File: editor/editor_resource_picker.cpp (hunk 1 above)
Comment (Chaosus) [reply editor/editor_resource_picker.cpp]: Ah right, it's true that it should return false in that case, and it's will be fine to fix this issue.

Comment (Chaosus) [reply editor/editor_resource_picker.cpp]: Done

**Comment by Chaosus** [comment]
@pycbouh Strange, I don't observe this crash on `3.4beta-2`.

**Comment by pycbouh** [comment]
@Chaosus Maybe you're not setting it up properly? For it to crash you need to have a scene open and a node selected so that there is something in the Inspector (this is where the resource picker appears). If you don't have a scene and just go straight to the script editor, dragging help items works.

**Comment by akien-mga** [comment]
Needs rebase for CI.

**Comment by Chaosus** [comment]
@pycbouh Ah, indeed it crashing (just not so obviously as in 4.0)

**Review by YuriSizov — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
Not relevant for 3.3.
