### PR TITLE
Fix scrolling to bottom panel selected button.

### LINKED ISSUE #109496: Regression causes error by calling ScrollContainer::ensure_control_visible() with nullptr
### Tested versions

- 4.4.1-stable
- v4.4.2.rc.custom_build [e531f3eb7]
- 4.5b5

### System information

Godot v4.4.2.rc (e531f3eb7) - Windows 11 (build 26100) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Laptop GPU (NVIDIA; 32.0.15.7680) - 12th Gen Intel(R) Core(TM) i9-12900H (20 threads)

### Issue description

PR https://github.com/godotengine/godot/pull/97878 caused a set of errors, when using a ScrollContainer, possibly as part of an editor plugin. It is reproducible in Terrain3D.  

```
ERROR: Parameter "p_node" is null.
   at: is_ancestor_of (scene/main/node.cpp:2037)
ERROR: Must be an ancestor of the control.
   at: (scene/gui/scroll_container.cpp:293)
ERROR: Error calling deferred method: 'ScrollContainer::ScrollContainer::ensure_control_visible': Cannot convert argument 1 from Object to Object.
   at: _call_function (core/object/message_queue.cpp:222)
```

[This is the offending line](https://github.com/mounirtohami/godot/blob/2f87b7aae0d7a5481159fc02eb6bdb83ac3ad1fa/editor/gui/editor_bottom_panel.cpp#L137) that was added. Commenting the line prevents the error. The passed variables in the deferred call are not null at this moment.
```
callable_mp(button_scroll, &ScrollContainer::ensure_control_visible).call_deferred(items[p_idx].button);
```

The problem may be in [this function](https://github.com/godotengine/godot/blob/master/scene/gui/scroll_container.cpp#L326). When the error occurs, this function receives a null for p_control. Because this node is not an ancestor of null, it prints an error. 
```
void ScrollContainer::ensure_control_visible(Control *p_control) {
	ERR_FAIL_COND_MSG(!is_ancestor_of(p_control), "Must be an ancestor of the control.");
```

I thought maybe we just need a null check and silent exit of the above function but that leaves this error remaining. Also note that it has `ScrollContainer::` twice:
```
ERROR: Error calling deferred method: 'ScrollContainer::ScrollContainer::ensure_control_visible': Cannot convert argument 1 from Object to Object.
   at: CallQueue::_call_function (core\object\message_queue.cpp:222)
```

Looking at all of the Godot source, ensure_control_visible is only called in 3 places. I made this diff to 4.4.2 for some debugging lines:
<details>
  <summary>Debug code</summary>  

```
diff --git a/editor/editor_properties_array_dict.cpp b/editor/editor_properties_array_dict.cpp
index 066c0d7d9e..d5ff552c7b 100644
--- a/editor/editor_properties_array_dict.cpp
+++ b/editor/editor_properties_array_dict.cpp
@@ -851,6 +851,7 @@ void EditorPropertyArray::_reorder_button_gui_input(const Ref<InputEvent> &p_eve
                                _page_changed(page_index + direction);
                        }
                        // Ensure the moving element is visible.
+                       OS::get_singleton()->print("ensure_control_visible editor_properties_array_dict.cpp\n");
                        InspectorDock::get_inspector_singleton()->ensure_control_visible(reorder_slot.container);
                }
        }
diff --git a/editor/gui/editor_bottom_panel.cpp b/editor/gui/editor_bottom_panel.cpp
index e984f196fb..5a43cd7997 100644
--- a/editor/gui/editor_bottom_panel.cpp
+++ b/editor/gui/editor_bottom_panel.cpp
@@ -41,6 +41,8 @@
 #include "scene/gui/button.h"
 #include "scene/gui/scroll_container.h"
 #include "scene/gui/split_container.h"
+#include "core/string/print_string.h"
+#include "core/os/time.h"

 void EditorBottomPanel::_notification(int p_what) {
        switch (p_what) {
@@ -134,6 +136,14 @@ void EditorBottomPanel::_switch_to_item(bool p_visible, int p_idx, bool p_ignore
                if (expand_button->is_pressed()) {
                        EditorNode::get_top_split()->hide();
                }
+               print_line(Time::get_singleton()->get_ticks_usec(), " editor_bottom_panel, idx: ", String::num_int64(p_idx));
+               for (int i = 0; i < items.size(); i++) {
+                       print_line(i, ": ", items[i].name, ", ", items[i].control, ", ", items[i].button);
+                       if (i == 16) {
+
+                       }
+               }
+               print_line(Time::get_singleton()->get_ticks_usec(), "Setting up ensure_control_visible.call_deferred(items[", p_idx, "].button: ", items[p_idx].button, ")");
                callable_mp(button_scroll, &ScrollContainer::ensure_control_visible).call_deferred(items[p_idx].button);
        } else {
                add_theme_style_override(SceneStringName(panel), get_theme_stylebox(SNAME("BottomPanel"), EditorStringName(EditorStyles)));
diff --git a/scene/gui/scroll_container.cpp b/scene/gui/scroll_container.cpp
index fdb134c5d0..f84d69081f 100644
--- a/scene/gui/scroll_container.cpp
+++ b/scene/gui/scroll_container.cpp
@@ -279,6 +279,7 @@ void ScrollContainer::_update_scrollbar_position() {

 void ScrollContainer::_gui_focus_changed(Control *p_control) {
        if (follow_focus && is_ancestor_of(p_control)) {
+               OS::get_singleton()->print("ensure_control_visible ScrollContainer::_gui_focus_changed\n");
                ensure_control_visible(p_control);
        }
        if (draw_focus_border) {
@@ -290,6 +291,9 @@ void ScrollContainer::_gui_focus_changed(Control *p_control) {
 }

 void ScrollContainer::ensure_control_visible(Control *p_control) {
+       if (p_control == nullptr) {
+               OS::get_singleton()->print("ensure_control_visible p_control is null\n");
+       }
        ERR_FAIL_COND_MSG(!is_ancestor_of(p_control), "Must be an ancestor of the control.");

        // Just eliminate the rotation of this ScrollContainer.

```
</details>

What I found is that when I do the test operation in Terrain3D that only updates the visibility of children under the ScrollContainer, it calls `EditorBottomPanel::_switch_to_item()` 4 times at least, twice with idx 0, twice with idx 16. 
This dumps `Vector<BottomPanelItem> items;` as `idx: items[i].name, .control, .button` and none of the entries are null leading into the deferred call. 

When the call is received by `ScrollContainer::ensure_control_visible(Control *p_control)`, p_control is null, which causes the error message since it's not an ancestor. 

<details>
  <summary>Logs</summary>  

```
11869286  editor_bottom_panel, idx:  0
0 :  Output ,  @EditorLog@7952:<EditorLog#652969279506> ,  @Button@7953:<Button#653892026440>
1 :  Debugger ,  @EditorDebuggerNode@9842:<EditorDebuggerNode#709105847228> ,  @Button@9843:<Button#749438276586>
2 :  Audio ,  @EditorAudioBuses@13406:<EditorAudioBuses#1034181199160> ,  @Button@13407:<Button#1042871797507>
3 :  Search Results ,  @FindInFilesPanel@13173:<FindInFilesPanel#1030037226581> ,  @Button@13174:<Button#1031446512806>
4 :  Animation ,  @AnimationPlayerEditor@11125:<AnimationPlayerEditor#757474563411> ,  @Button@11126:<Button#844749645045>
5 :  AnimationTree ,  @AnimationTreeEditor@15326:<AnimationTreeEditor#1077432864347> ,  @Button@15327:<Button#1166184341031>
6 :  ResourcePreloader ,  @ResourcePreloaderEditor@16949:<ResourcePreloaderEditor#1255103590073> ,  @Button@16950:<Button#1264163287208>
7 :  Shader Editor ,  @WindowWrapper@16986:<WindowWrapper#1264230396076> ,  @Button@16987:<Button#1266780533032>
8 :  ShaderFile ,  @ShaderFileEditor@17226:<ShaderFileEditor#1277400511331> ,  @Button@17227:<Button#1278054822793>
9 :  SpriteFrames ,  @SpriteFramesEditor@17915:<SpriteFramesEditor#1278541362075> ,  @Button@17916:<Button#1335768448360>
10 :  Theme ,  @ThemeEditor@19025:<ThemeEditor#1358585462997> ,  @Button@19026:<Button#1406299867755>
11 :  Polygon ,  @VBoxContainer@19941:<VBoxContainer#1451397026353> ,  @Button@19942:<Button#1472368547193>
12 :  TileSet ,  @TileSetEditor@20553:<TileSetEditor#1486562072515> ,  @Button@20554:<Button#1509043543171>
13 :  TileMap ,  @TileMapLayerEditor@20711:<TileMapLayerEditor#1509110652039> ,  @Button@20712:<Button#1519160204918>
14 :  Replication ,  @ReplicationEditor@21148:<ReplicationEditor#1537229267428> ,  @Button@21149:<Button#1543218733879>
15 :  GridMap ,  @GridMapEditor@21372:<GridMapEditor#1894567192737> ,  @Button@21373:<Button#1905187170914>
11873868 Setting up ensure_control_visible.call_deferred(items[ 0 ].button:  @Button@7953:<Button#653892026440> )
11876798  editor_bottom_panel, idx:  16
0 :  Output ,  @EditorLog@7952:<EditorLog#652969279506> ,  @Button@7953:<Button#653892026440>
1 :  Debugger ,  @EditorDebuggerNode@9842:<EditorDebuggerNode#709105847228> ,  @Button@9843:<Button#749438276586>
2 :  Audio ,  @EditorAudioBuses@13406:<EditorAudioBuses#1034181199160> ,  @Button@13407:<Button#1042871797507>
3 :  Search Results ,  @FindInFilesPanel@13173:<FindInFilesPanel#1030037226581> ,  @Button@13174:<Button#1031446512806>
4 :  Animation ,  @AnimationPlayerEditor@11125:<AnimationPlayerEditor#757474563411> ,  @Button@11126:<Button#844749645045>
5 :  AnimationTree ,  @AnimationTreeEditor@15326:<AnimationTreeEditor#1077432864347> ,  @Button@15327:<Button#1166184341031>
6 :  ResourcePreloader ,  @ResourcePreloaderEditor@16949:<ResourcePreloaderEditor#1255103590073> ,  @Button@16950:<Button#1264163287208>
7 :  Shader Editor ,  @WindowWrapper@16986:<WindowWrapper#1264230396076> ,  @Button@16987:<Button#1266780533032>
8 :  ShaderFile ,  @ShaderFileEditor@17226:<ShaderFileEditor#1277400511331> ,  @Button@17227:<Button#1278054822793>
9 :  SpriteFrames ,  @SpriteFramesEditor@17915:<SpriteFramesEditor#1278541362075> ,  @Button@17916:<Button#1335768448360>
10 :  Theme ,  @ThemeEditor@19025:<ThemeEditor#1358585462997> ,  @Button@19026:<Button#1406299867755>
11 :  Polygon ,  @VBoxContainer@19941:<VBoxContainer#1451397026353> ,  @Button@19942:<Button#1472368547193>
12 :  TileSet ,  @TileSetEditor@20553:<TileSetEditor#1486562072515> ,  @Button@20554:<Button#1509043543171>
13 :  TileMap ,  @TileMapLayerEditor@20711:<TileMapLayerEditor#1509110652039> ,  @Button@20712:<Button#1519160204918>
14 :  Replication ,  @ReplicationEditor@21148:<ReplicationEditor#1537229267428> ,  @Button@21149:<Button#1543218733879>
15 :  GridMap ,  @GridMapEditor@21372:<GridMapEditor#1894567192737> ,  @Button@21373:<Button#1905187170914>
16 :  Terrain3D ,  Terrain3D:<PanelContainer#2253431850753> ,  @Button@23957:<Button#2721549731655>
11879477 Setting up ensure_control_visible.call_deferred(items[ 16 ].button:  @Button@23957:<Button#2721549731655> )
11894944  editor_bottom_panel, idx:  0
0 :  Output ,  @EditorLog@7952:<EditorLog#652969279506> ,  @Button@7953:<Button#653892026440>
1 :  Debugger ,  @EditorDebuggerNode@9842:<EditorDebuggerNode#709105847228> ,  @Button@9843:<Button#749438276586>
2 :  Audio ,  @EditorAudioBuses@13406:<EditorAudioBuses#1034181199160> ,  @Button@13407:<Button#1042871797507>
3 :  Search Results ,  @FindInFilesPanel@13173:<FindInFilesPanel#1030037226581> ,  @Button@13174:<Button#1031446512806>
4 :  Animation ,  @AnimationPlayerEditor@11125:<AnimationPlayerEditor#757474563411> ,  @Button@11126:<Button#844749645045>
5 :  AnimationTree ,  @AnimationTreeEditor@15326:<AnimationTreeEditor#1077432864347> ,  @Button@15327:<Button#1166184341031>
6 :  ResourcePreloader ,  @ResourcePreloaderEditor@16949:<ResourcePreloaderEditor#1255103590073> ,  @Button@16950:<Button#1264163287208>
7 :  Shader Editor ,  @WindowWrapper@16986:<WindowWrapper#1264230396076> ,  @Button@16987:<Button#1266780533032>
8 :  ShaderFile ,  @ShaderFileEditor@17226:<ShaderFileEditor#1277400511331> ,  @Button@17227:<Button#1278054822793>
9 :  SpriteFrames ,  @SpriteFramesEditor@17915:<SpriteFramesEditor#1278541362075> ,  @Button@17916:<Button#1335768448360>
10 :  Theme ,  @ThemeEditor@19025:<ThemeEditor#1358585462997> ,  @Button@19026:<Button#1406299867755>
11 :  Polygon ,  @VBoxContainer@19941:<VBoxContainer#1451397026353> ,  @Button@19942:<Button#1472368547193>
12 :  TileSet ,  @TileSetEditor@20553:<TileSetEditor#1486562072515> ,  @Button@20554:<Button#1509043543171>
13 :  TileMap ,  @TileMapLayerEditor@20711:<TileMapLayerEditor#1509110652039> ,  @Button@20712:<Button#1519160204918>
14 :  Replication ,  @ReplicationEditor@21148:<ReplicationEditor#1537229267428> ,  @Button@21149:<Button#1543218733879>
15 :  GridMap ,  @GridMapEditor@21372:<GridMapEditor#1894567192737> ,  @Button@21373:<Button#1905187170914>
11897593 Setting up ensure_control_visible.call_deferred(items[ 0 ].button:  @Button@7953:<Button#653892026440> )
11900413  editor_bottom_panel, idx:  16
0 :  Output ,  @EditorLog@7952:<EditorLog#652969279506> ,  @Button@7953:<Button#653892026440>
1 :  Debugger ,  @EditorDebuggerNode@9842:<EditorDebuggerNode#709105847228> ,  @Button@9843:<Button#749438276586>
2 :  Audio ,  @EditorAudioBuses@13406:<EditorAudioBuses#1034181199160> ,  @Button@13407:<Button#1042871797507>
3 :  Search Results ,  @FindInFilesPanel@13173:<FindInFilesPanel#1030037226581> ,  @Button@13174:<Button#1031446512806>
4 :  Animation ,  @AnimationPlayerEditor@11125:<AnimationPlayerEditor#757474563411> ,  @Button@11126:<Button#844749645045>
5 :  AnimationTree ,  @AnimationTreeEditor@15326:<AnimationTreeEditor#1077432864347> ,  @Button@15327:<Button#1166184341031>
6 :  ResourcePreloader ,  @ResourcePreloaderEditor@16949:<ResourcePreloaderEditor#1255103590073> ,  @Button@16950:<Button#1264163287208>
7 :  Shader Editor ,  @WindowWrapper@16986:<WindowWrapper#1264230396076> ,  @Button@16987:<Button#1266780533032>
8 :  ShaderFile ,  @ShaderFileEditor@17226:<ShaderFileEditor#1277400511331> ,  @Button@17227:<Button#1278054822793>
9 :  SpriteFrames ,  @SpriteFramesEditor@17915:<SpriteFramesEditor#1278541362075> ,  @Button@17916:<Button#1335768448360>
10 :  Theme ,  @ThemeEditor@19025:<ThemeEditor#1358585462997> ,  @Button@19026:<Button#1406299867755>
11 :  Polygon ,  @VBoxContainer@19941:<VBoxContainer#1451397026353> ,  @Button@19942:<Button#1472368547193>
12 :  TileSet ,  @TileSetEditor@20553:<TileSetEditor#1486562072515> ,  @Button@20554:<Button#1509043543171>
13 :  TileMap ,  @TileMapLayerEditor@20711:<TileMapLayerEditor#1509110652039> ,  @Button@20712:<Button#1519160204918>
14 :  Replication ,  @ReplicationEditor@21148:<ReplicationEditor#1537229267428> ,  @Button@21149:<Button#1543218733879>
15 :  GridMap ,  @GridMapEditor@21372:<GridMapEditor#1894567192737> ,  @Button@21373:<Button#1905187170914>
16 :  Terrain3D ,  Terrain3D:<PanelContainer#2253431850753> ,  @Button@23958:<Button#2725593040711>
11902017 Setting up ensure_control_visible.call_deferred(items[ 16 ].button:  @Button@23958:<Button#2725593040711> )
ensure_control_visible p_control is null
ERROR: Parameter "p_node" is null.
   at: Node::is_ancestor_of (scene\main\node.cpp:2037)
ERROR: Must be an ancestor of the control.
   at: (scene\gui\scroll_container.cpp:305)
ERROR: Error calling deferred method: 'ScrollContainer::ScrollContainer::ensure_control_visible': Cannot convert argument 1 from Object to Object.
   at: CallQueue::_call_function (core\object\message_queue.cpp:222)

```
</details>

[The code that triggers the call](https://github.com/TokisanGames/Terrain3D/blob/main/project/addons/terrain_3d/src/asset_dock.gd#L266-L290) is called when pressing a button on our asset dock, which hides one child of the ScrollContainer and makes another visible (mesh_list and texture_list). Both children are Containers with a bunch of texture buttons in it. I understand ScrollContainer is really only supposed to have one child, however if I change the structure so there's a single Control child, it makes no difference to this error.

### Steps to reproduce

The problem is intermittent so can be flakey, but in build after build after build I've been able to produce it, with new projects, builds by me, builds by github, and countless commits up and down my tree.

* Create a new project
* Change to the asset lib and download Terrain3D and install.
* Enable Terrain3D in the project settings.
* Open Demo.tscn
* Click Terrain3D
* The error occurs when you alternate clicking on Meshes or Textures in the Terrain3D Asset Dock. You may also need to click off Terrain3D in the scene tree, and back on, or change to a new scene and back, then click the buttons.

If you can't get it to trigger with the release build, try our latest artifact. Remove addons/terrain_3d and add it from this file: https://github.com/TokisanGames/Terrain3D/actions/runs/16824689292/artifacts/3717626215

### Minimal reproduction project (MRP)

See above.

cc @WhalesState

### PR DESCRIPTION
**Pull request by WhalesState**
* Fixes: https://github.com/godotengine/godot/issues/109496

* Regression from: https://github.com/godotengine/godot/pull/97878

### CODE REVIEW

File: editor/gui/editor_bottom_panel.cpp [hunk 1]
```diff
@@ -100,6 +100,15 @@ void EditorBottomPanel::_update_disabled_buttons() {
 	right_button->set_disabled(h_scroll->get_value() + h_scroll->get_page() == h_scroll->get_max());
 }
 
+void EditorBottomPanel::_ensure_control_visible(Control *p_control) {
+	if (!p_control || !p_control->is_visible()) {
```
Comment (WhalesState) [inline editor/gui/editor_bottom_panel.cpp]: If there are no cases of a button being hidden in the bottom panel then we can remove this check `!p_control->is_visible()`.

**Comment by KoBeWi** [comment]
Still managed to reproduce:
```
ERROR: C:\godot_source\core/object/message_queue.cpp:222 - Error calling deferred method: 'EditorBottomPanel::EditorBottomPanel::_ensure_control_visible': Cannot convert argument 1 from Object to Object.
```

**Comment by WhalesState** [comment]
> Still managed to reproduce:
> 
> ```
> ERROR: C:\godot_source\core/object/message_queue.cpp:222 - Error calling deferred method: 'EditorBottomPanel::EditorBottomPanel::_ensure_control_visible': Cannot convert argument 1 from Object to Object.
> ```

Failed to reproduce all the error on Linux with this PR and the official `Godot-4.5 beta 5`, will try to confirm if it only happens on Windows.

**Comment by WhalesState** [comment]
I was able to reproduce the issue on windows, happens only after loading the project the first time. but i have failed to reproduce it the second time. I am removing the issue from this PR as it doesn't fix the issue, I have left a comment with the call stack in the issue.

**Comment by WhalesState** [comment]
We can replace the bug label with enhancement as it doesn't fix the bug.

**Comment by WhalesState** [comment]
> Still managed to reproduce:
> 
> ```
> ERROR: C:\godot_source\core/object/message_queue.cpp:222 - Error calling deferred method: 'EditorBottomPanel::EditorBottomPanel::_ensure_control_visible': Cannot convert argument 1 from Object to Object.
> ```

This was an issue in his code calling `EditorInterface.edit_node()` twice in the same frame, and it only throws this error on Windows, we can investigate with a double call on any node or resource that triggers the editor bottom panel to see why it only happens on Windows.

**Comment by KoBeWi** [comment]
The code looks fine, but I wonder about usefulness of this change 🤔
It can potentially prevent errors, but not sure when it's relevant if it doesn't fix the previously linked issue.

**Comment by WhalesState** [comment]
> The code looks fine, but I wonder about usefulness of this change 🤔 It can potentially prevent errors, but not sure when it's relevant if it doesn't fix the previously linked issue.

The PR and this issue: https://github.com/godotengine/godot/issues/109496 should be closed, Those changes are part of https://github.com/godotengine/godot/pull/109396 and the issue itself was fixed here https://github.com/TokisanGames/Terrain3D/pull/779

**Comment by KoBeWi** [comment]
I wonder if we can at least make the error more clear? The problem was fixed only after the discussion, but it's not documented anywhere outside the issue.

**Comment by WhalesState** [comment]
> I wonder if we can at least make the error more clear? The problem was fixed only after the discussion, but it's not documented anywhere outside the issue.

I have no issue with calling `EditorInterface.edit_node()` many times or showing/hiding the plugin button many times in the same frame on Linux, but I have found an issue, calling `edit_node()` in the same frame where `EditorPlugin._handles()` calls `EditorPlugin._edit()` results in thousands of errors.

image

And waiting one frame before calling `edit_node()` makes `_edit()` called one extra time with `<Object#null>`, please check if this can trigger the same issue on Windows.

Double click any SVG file to trigger `_edit()` ie. `icon.svg`.

```gdscript
@tool
extends EditorPlugin

var panel: PanelContainer


func _enable_plugin() -> void:
	panel = PanelContainer.new()
	add_control_to_bottom_panel(panel, "Bottom Panel Test")


func _disable_plugin() -> void:
	remove_control_from_bottom_panel(panel)
	panel.free()
	panel = null


func _edit(object: Object) -> void:
	print(object)
	await get_tree().process_frame
	EditorInterface.edit_node(get_tree().edited_scene_root)


func _handles(object: Object) -> bool:
	var res: Resource = object as Resource
	if not res:
		return false
	return res.resource_path.ends_with("svg")
```

Each `_edit()` call prints.

```
<CompressedTexture2D#-9223366879286766564>
<Object#null>
```

**Comment by KoBeWi** [comment]
I did check it and I indeed get double print. Without `await` the editor will crash from what looks like stack overflow.

Although this behavior is expected. `edit_node()` does call `_handles()` in the plugin, and then `edit(null)`, because another plugin is going to edit the object.

**Comment by WhalesState** [comment]
> Although this behavior is expected. `edit_node()` does call `_handles()` in the plugin, and then `edit(null)`, because another plugin is going to edit the object.

Sounds like a bug or unexpected behavior, we can discuss it later since the docs here says that `_edit()` will be called later with `null` Object to allow cleaning the plugin, which makes `edit_node()` tells the same plugin that just handled the `Object` and returned `true` to clean, it's confusing.

**Comment by KoBeWi** [comment]
Well, only one object can be edited by any plugin at the time (it's actually one per "context", but in this case the SVG file and scene root share the context). Hence if you try to edit another object, the current plugin, which does not handle it, has to cleanup.

**Comment by WhalesState** [comment]
Yes but we have an exception here when `_handles(Object)` returns `true` it already calls `_edit(Object)` and `_edit(null)` at same frame which is indeed a bug. We should exclude the Plugins that can handle the `Object` from the cleanup.

Edit: This also can be fixed if the clean up happens before the handling which should be the expected behavior.

**Comment by KoBeWi** [comment]
`edit_node()` requests editor to edit the node. The editor goes through all relevant plugins, calls `_handles()` passing the object and if a plugin returns `true` for the object, the editor will call `_edit()`.

What happens in your code:
- You click SVG file
- Editor gets edit request from FileSystem dock
- Your plugin receives `_handles()` call and returns true
- Your plugin receives `_edit()` call
- In the `_edit()` callback, you request to edit _another_ object
- The editor gets request and goes over plugins
- Your plugin gets a `_handles()` call with the new object that you just requested and returns `false`
- _Another_ plugin returns true for `_handles()`
- Your plugin receives `_edit(null)`, because it no longer edits (doesn't matter if it was editing a different object)
- Another plugin receives `_edit(the new object)` call

**Comment by WhalesState** [comment]
Ok this explains the main [issue](https://github.com/godotengine/godot/issues/109496) now, and can be fixed with a check if the Object is not deleted before calling `Node::_is_ancestor_of(*Control)` with an invalid pointer.

**Comment by WhalesState** [comment]
Fixed the bug and we can close the issue now. Thanks for helping figuring it out.

File: editor/gui/editor_bottom_panel.cpp [hunk 2]
```diff
@@ -100,6 +100,15 @@ void EditorBottomPanel::_update_disabled_buttons() {
 	right_button->set_disabled(h_scroll->get_value() + h_scroll->get_page() == h_scroll->get_max());
 }
 
+void EditorBottomPanel::_ensure_control_visible(ObjectID p_id) {
+	Control *c = Object::cast_to<Control>(ObjectDB::get_instance(p_id));
```
Comment (KoBeWi) [inline editor/gui/editor_bottom_panel.cpp]:
```suggestion
	Control *c = ObjectDB::get_instance<Control>(p_id));
```

**Review by KoBeWi — APPROVED** [review]

File: editor/gui/editor_bottom_panel.cpp (hunk 2 above)
Comment (WhalesState) [reply editor/gui/editor_bottom_panel.cpp]: Fixed it and rebased. Thanks again.

**Comment by Repiteo** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.5.2.
