### PR TITLE
Make `dict2inst` to work with arbitrary `_init` parameters

### LINKED ISSUE #30572: dict2inst does not work on classes with _init parameters
**Godot version:**
Godot Engine v3.1.1.stable.official

**Issue description:**
`dict2inst` does not work on classes with `_init` parameters.  A simple fix is to manually initialize the object after it has been created with `.new()`

**Steps to reproduce:**
Create a scene with an external(not built in script). Then run the scene with this in the script:
```gdscript
extends Node2D

class A:
	var value 
	func _init(val):
		self.value = val
		
class B:
	var value
	func init(val):
		self.value = val

func serializeA():
	var inst = A.new(1)
	var instDict = inst2dict(inst)
	var inst2 = dict2inst(instDict)
	print("A was serialized and deserialize succesfully")

func serializeB():
	var inst = B.new()
	B.init(1)
	var instDict = inst2dict(inst)
	var inst2 = dict2inst(instDict)
	print("B was serialized and deserialize succesfully")

func _ready():
	serializeA() # this will crash the program
	serializeB() # this runs fine
```
```

### PR DESCRIPTION
**Pull request by Xrayez**
Fixes #30572.

This is achieved by skipping initializer call while creating an instance of a GDScript. This is implemented by passing -1 as an argument count to `_new` and interpreting any value below 0 to mean that the initializer should not be called during instantiation, because internal members of an instance are going to be overridden afterwards (from a dictionary).

I'm not sure if the initializer should actually be called, but it doesn't make sense to me because this is mostly done for deserialization, so I think this should do it. In fact, I don't see a way to call the initializer without knowing what are the actual arguments for parameters, unless you somehow store the initial arguments beforehand when an instance is created normally with `script.new(vararg)` for them to be stored directly inside dictionary created with `inst2dict`.

I'd be more adventurous in making more thorough changes but I'd like to hear what you think of this, or whether you see a better fix. Namely, creation and construction would need to be refactored and treated separately.

### CODE REVIEW

File: modules/gdscript/gdscript.cpp [hunk 1]
```diff
@@ -111,22 +111,22 @@ GDScriptInstance *GDScript::_create_instance(const Variant **p_args, int p_argco
...
 #endif
-		instances.erase(p_owner);
+			instances.erase(p_owner);
 #ifndef NO_THREADS
-		GDScriptLanguage::singleton->lock->unlock();
+			GDScriptLanguage::singleton->lock->unlock();
 #endif
-
-		ERR_FAIL_COND_V(r_error.error != Variant::CallError::CALL_OK, NULL); //error constructing
+			ERR_FAIL_V_MSG(NULL, "Error constructing a GDScriptInstance.");
```
Comment (ThakeeNathees) [inline modules/gdscript/gdscript.cpp:127]: why this always has to fail?

File: modules/gdscript/gdscript.cpp [hunk 2]
```diff
@@ -111,22 +111,22 @@ GDScriptInstance *GDScript::_create_instance(const Variant **p_args, int p_argco
 	GDScriptLanguage::singleton->lock->unlock();
 #endif
```
Comment (ThakeeNathees) [inline modules/gdscript/gdscript.cpp:113]: IMO this can simplified with
`if (p_argcount < 0) return instance;`

File: modules/gdscript/gdscript_functions.cpp [hunk 3]
```diff
@@ -1217,8 +1217,8 @@ void GDScriptFunctions::call(Function p_func, const Variant **p_args, int p_arg_
 					return;
 				}
 			}
-
-			r_ret = gdscr->_new(NULL, 0, r_error);
+			const int skip_initializer = -1;
+			r_ret = gdscr->_new(NULL, skip_initializer, r_error);
```
Comment (ThakeeNathees) [inline modules/gdscript/gdscript_functions.cpp:1221]:
```c++
static const SKIP_INITIALIZER  = -1; // I prefer an enum or macro more
// or
r_ret = gdscr->_new(NULL, -1/*skip initializer*/, r_error);
```

**Comment by ThakeeNathees** [comment]
IMO instead of `arg count = -1`,  what if `GDScript::_create_instance()` 1st call `create` and then call `initialize` and later we only call `create` for deserializing?

File: modules/gdscript/gdscript.cpp (hunk 1 above)
Comment (Xrayez) [reply modules/gdscript/gdscript.cpp:127]: Because the error is handled in the above `if` statement, and having to check the same condition within `ERR_FAIL_COND` is redundant (it always fails here regardless).

File: modules/gdscript/gdscript.cpp (hunk 2 above)
Comment (Xrayez) [reply modules/gdscript/gdscript.cpp:113]: I guess the reason why I haven't done this is simply because of the below clean up procedures, in some cases short-cutting with `return` statement is error-prone.

File: modules/gdscript/gdscript_functions.cpp (hunk 3 above)
Comment (Xrayez) [reply modules/gdscript/gdscript_functions.cpp:1221]: I like the inline comment too but I'm not sure about the specific style requirements...

**Comment by Xrayez** [comment]
@ThakeeNathees yep, but I'm not that enthusiastic when it comes to rewriting core stuff, we need feedback from @vnen.

File: modules/gdscript/gdscript.cpp (hunk 2 above)
Comment (Xrayez) [reply modules/gdscript/gdscript.cpp]: Indeed this makes less diff changes. 🙂

**Comment by Xrayez** [comment]
Rebased, works alright, thanks for suggestions @ThakeeNathees.

**Review by vnen — APPROVED** [review]
Makes sense to me. Sorry for not looking into this sooner.

**Comment by akien-mga** [comment]
Thanks!
