### PR TITLE
Handle UID path in packs.

### LINKED ISSUE #116936: `FileAccess` fails to access `uid://` paths in exported builds even when their corresponding `res://` path works
### Tested versions

Reproducible in v4.6.stable.official.89cea1439 and v4.6.1.stable.official.14d19694e

### System information

macOS with Apple M3 CPU

### Issue description

`FileAccess` cannot access files using their `uid://` paths in exported builds, even when it can access their corresponding `res://` paths (got via `ResourceUID.uid_to_path` for example).
This only happens in exported builds.

### Steps to reproduce

1. Clone the MRP
2. Export the project
3. Run the exported project
4. Check for the message `FileAccess.file_exists(uid_path) -> false` indicating that `FileAccess` cannot access the file from its `uid://` path, while `FileAccess.file_exists(res_path) -> true` indicates that it can access the same file via its `res://` path

### Minimal reproduction project (MRP)

https://github.com/gilzoide/godot-fileaccess-uid-bug

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/116936

### CODE REVIEW

File: core/io/file_access_pack.h [hunk 1]
```diff
@@ -119,6 +120,15 @@ class PackedData {
 	void _free_packed_dirs(PackedDir *p_dir);
 	void _get_file_paths(PackedDir *p_dir, const String &p_parent_dir, HashSet<String> &r_paths) const;
 
+	_FORCE_INLINE_ PathMD5 _get_path(const String &p_path) {
```
Comment (KoBeWi) [inline core/io/file_access_pack.h]: Could use a more descriptive name, like `_get_resolved_path()` or `_get_simplified_path()`.

**Review by KoBeWi — APPROVED** [review]
Didn't test, but the code looks fine.

**Review by Repiteo — APPROVED** [review]
