### PR TITLE
[3.x] Address slow copy performance when using the `FileAccessFilesystemJAndroid` implementation

### LINKED ISSUE #62969: Extreme Android slowdown when copying files with scoped storage
### Godot version

3.5 rc6

### System information

Windows 11

### Issue description

If I copy a file over to the "user://" directory, it takes 65 milliseconds.
However, If I allow permission to **Manage_External_Storage**, **Read_External_Storage** and **Write_External_Stoage** I can copy a file to a new directory int the Documents folder...yet, doing so takes over 5000 milliseconds!

Though this slowdown may also occur with other instances of trying to use a file in storage, this extreme slowdown for sure occurs with file copying.  

### Steps to reproduce

Take turns commenting out line 21 and 22.  One uses the "user://" directory, the other uses the phone's regular storage.
Make sure each time you install it, you allow and accept the two permissions, **then close and run again** to see effects.

### Minimal reproduction project

I usually use C#, but made it in GDScript to speed up the testing.
[Storage.zip](https://github.com/godotengine/godot/files/9097956/Storage.zip)

### PR DESCRIPTION
**Pull request by m4gr3d**
Read/write ops for this implementation are done through the java layer via jni, and so for good performance, it's key to avoid numerous repeated small read/write ops due the jni overhead.

The alternative is to allocate a (conversatively-sized) large buffer to reduce the number of read/write ops over the jni boundary.

Fixes #62969

3.x version of https://github.com/godotengine/godot/pull/63242

### CODE REVIEW

File: core/os/dir_access.cpp [hunk 1]
```diff
@@ -302,7 +304,9 @@ Error DirAccess::copy(String p_from, String p_to, int p_chmod_flags) {
 	int size = fsrc->get_position();
 	fsrc->seek(0);
 	err = OK;
-	while (size--) {
+	size_t buffer_size = std::min(size * sizeof(uint8_t), COPY_BUFFER_LIMIT);
+	uint8_t *buffer = (uint8_t *) memalloc(buffer_size);
```
Comment (akien-mga) [inline core/os/dir_access.cpp:308]: Style issue.

**Review by lawnjelly — APPROVED** [review]
Might be a little more "Godotey" to use a `LocalVector` local variable for this rather than alloc the buffer directly, but that's more a style / maintenance nitpick, using a buffer directly isn't any worse.

An alternative could be to persist the vector to prevent multiple allocations, but probably won't make a massive difference as file access is expected to be slow anyway, and the approach in the PR avoids tying up any memory.

Also might be a tad better practice to just have the `COPY_BUFFER_LIMIT` a local const unless it was used in multiple places, to avoid polluting global namespace.

These are all nitpicks though, up to you if you wanted to change imo.

P.S. Haven't tried running it, only looking at the function.

EDIT: Noticed one possible bug though. `get_buffer()` can return -1 in error condition (maybe this doesn't happen in practice) but might be good to check for this, `get_buffer()` could change in future. This can probably only currently happen if the malloc fails but could be worth checking that too and ERR_FAILing?

**Comment by akien-mga** [comment]
The!
