### PR TITLE
Check for null pointer in get_column_width(0)

### LINKED ISSUE #46005: Executing `Tree.new().get_column_width(0)` crashes Godot
**Godot version:**
Godot 3.2.4 rc 2

**Issue description:**
Executing
```
Tree.new().get_column_width(0)
```

crashes with backtrace
```
scene/gui/tree.cpp:3372:54: runtime error: member call on null pointer of type 'struct StyleBox'
scene/gui/tree.cpp:3372:54: runtime error: member access within null pointer of type 'struct StyleBox'
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] godots() [0x16f757a] (/mnt/Miecz/godot3.2/platform/x11/crash_handler_x11.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f280d54b210] (??:0)
[3] Tree::get_column_width(int) const (/mnt/Miecz/godot3.2/scene/gui/tree.cpp:3372 (discriminator 1))
[4] MethodBind1RC<int, int>::call(Object*, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/./core/method_bind.gen.inc:1333 (discriminator 8))
[5] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/core/object.cpp:919 (discriminator 1))
[6] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/mnt/Miecz/godot3.2/core/variant_call.cpp:1129 (discriminator 1))
[7] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript_function.cpp:1089)
[8] GDScriptInstance::_ml_call_reversed(GDScript*, StringName const&, Variant const**, int) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript.cpp:1269)
[9] GDScriptInstance::call_multilevel_reversed(StringName const&, Variant const**, int) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript.cpp:1278)
[10] Node::_notification(int) (/mnt/Miecz/godot3.2/scene/main/node.cpp:152)
[11] Node::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/main/node.h:46 (discriminator 14))
[12] CanvasItem::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/2d/canvas_item.h:166 (discriminator 3))
[13] Node2D::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/2d/node_2d.h:38 (discriminator 3))
[14] Object::notification(int, bool) (/mnt/Miecz/godot3.2/core/object.cpp:931)
[15] Node::_propagate_ready() (/mnt/Miecz/godot3.2/scene/main/node.cpp:197)
[16] Node::_propagate_ready() (/mnt/Miecz/godot3.2/scene/main/node.cpp:186 (discriminator 2))
[17] Node::_set_tree(SceneTree*) (/mnt/Miecz/godot3.2/scene/main/node.cpp:2560)
[18] SceneTree::init() (/mnt/Miecz/godot3.2/scene/main/scene_tree.cpp:464)
[19] OS_X11::run() (/mnt/Miecz/godot3.2/platform/x11/os_x11.cpp:3628)
[20] godots(main+0x331) [0x16ee467] (/mnt/Miecz/godot3.2/platform/x11/godot_x11.cpp:57)
[21] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f280d52c0b3] (??:0)
[22] godots(_start+0x2e) [0x16ee07e] (??:?)
-- END OF BACKTRACE --
```

### PR DESCRIPTION
**Pull request by jcsho**
Creating a new Tree without children crashes Godot on `get_column_width(0)` due to null pointer of StyleBox.

Fix #46005

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -3506,9 +3506,12 @@ int Tree::get_column_width(int p_column) const {
 		return columns[p_column].min_width;
 	}
 
+	int expand_area = get_size().width;
+
 	Ref<StyleBox> bg = cache.bg;
 
-	int expand_area = get_size().width - (bg->get_margin(SIDE_LEFT) + bg->get_margin(SIDE_RIGHT));
+	if (bg.is_valid())
+		expand_area -= (bg->get_margin(SIDE_LEFT) + bg->get_margin(SIDE_RIGHT));
```
Comment (bruvzg) [inline scene/gui/tree.cpp:3514]:
```suggestion
	if (bg.is_valid()) {
		expand_area -= (bg->get_margin(SIDE_LEFT) + bg->get_margin(SIDE_RIGHT));
	}
```

**Review by bruvzg — APPROVED** [review]

File: scene/gui/tree.cpp (hunk 1 above)
Comment (jcsho) [reply scene/gui/tree.cpp]: Thanks! The 3.x branch didn't have braces for any if-statements so I just followed that

File: scene/gui/tree.cpp [hunk 2]
```diff
@@ -3506,9 +3506,13 @@ int Tree::get_column_width(int p_column) const {
 		return columns[p_column].min_width;
 	}
 
+	int expand_area = get_size().width;
+
 	Ref<StyleBox> bg = cache.bg;
 
-	int expand_area = get_size().width - (bg->get_margin(SIDE_LEFT) + bg->get_margin(SIDE_RIGHT));
+	if (bg.is_valid()) {
+		expand_area -= (bg->get_margin(SIDE_LEFT) + bg->get_margin(SIDE_RIGHT));
```
Comment (akien-mga) [inline scene/gui/tree.cpp:3514]: You could remove the parentheses which are no longer needed now as the whole right-hand side is being subtracted to `expand_area` with `-=`.

**Comment by akien-mga** [comment]
Could you squash the commits into one? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

File: scene/gui/tree.cpp (hunk 2 above)
Comment (jcsho) [reply scene/gui/tree.cpp]: Fixed!

**Comment by jcsho** [comment]
Got it, commits squashed. Thanks for the help!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.
