### PR TITLE
Fix distraction-free mode changing split offsets

### LINKED ISSUE #113783: Exiting distraction free mode resets dock slot width
### Tested versions

- Reproducible in: v4.6.dev6.official [dec5a373d], v4.6.dev.custom_build [757bba192]
- Not reproducible in: v4.5.1.stable, v4.6.dev3.official [9d84f3d13], v4.6.dev5.official [f5918a9d3]

### System information

Godot v4.6.dev (757bba192) - Arch Linux #1 SMP PREEMPT_DYNAMIC Mon, 24 Nov 2025 15:21:09 +0000 on X11 - X11 display driver, Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3060 Ti (nvidia; 580.105.08) - 13th Gen Intel(R) Core(TM) i5-13400F (16 threads) - 15.37 GiB memory

### Issue description

Exiting distraction free mode resets the width of the right dock slot.

The old (expected) behavior is to restore the width before entering distraction free mode.

Image

### Steps to reproduce

1. Make the right dock slot much wider.
2. Click the Distraction Free Mode button to enter distraction free mode.
3. Click the Distraction Free Mode button to exit distraction free mode.
4. See that the right dock slot width been reset.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by kitbdev**
- Fixes https://github.com/godotengine/godot/issues/113783

The `can_use_desired_sizes` is to make sure adding children doesn't affect the split offset when setting up the SplitContainer, so it should be fine to keep it as true.

The order that children are added and removed is important when trying to keep their sizes the same.

### CODE REVIEW

File: scene/gui/split_container.cpp [hunk 1]
```diff
@@ -993,7 +993,7 @@ void SplitContainer::_remove_valid_child(Control *p_control) {
 	}
 	// Only use desired sizes to change the split offset after the first time a child is removed.
 	// This allows adding children to not affect the split offsets when creating.
-	can_use_desired_sizes = valid_children.size() > 1u;
+	can_use_desired_sizes = true;
```
Comment (KoBeWi) [inline scene/gui/split_container.cpp:996]: What is this change?
Makes the variable always true (after removing first child) and the comment outdated.

Comment (kitbdev) [reply scene/gui/split_container.cpp:996]: When adding children to the SplitContainer for the first time, it needs to not affect the spit offsets so it starts as false. But afterwards, adding children should affect the split offsets so they keep the same size if removed and re-added. Removing a valid child is the sign I use to know when to change behaviors here, the only reason that this used to be `valid_children.size() > 1u` is because I was thinking it may be useful to go back to the setup behavior (IIRC). But it was partially causing issue https://github.com/godotengine/godot/issues/113783 as changing distraction free mode needs to use desired sizes logic even when all but one children are hidden.
The comment is still accurate.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
