### PR TITLE
Fix skeleton 3d editor's toolbar ui deleted from wrong container

### LINKED ISSUE #82094: Accumulation of VSeparator in toolbox when selecting a node
### Godot version

4.2.dev5

### System information

Windows 10

### Issue description

In an open scene of a glb file, when selecting different nodes, seperators endlessly accumulate in the top field, then the editor slows down a lot.

err

### Steps to reproduce

Open the main scene and perform the above actions

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/12697345/test.zip)

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes #82094

The bug comes from node mismatch: In `create_editors`, editors like `animation_hb` are added to `topmenu_bar` but in the destructor they are removed from `Node3DEditor::get_singleton()` which is the parent of `topmenu_bar`.

### CODE REVIEW

File: editor/plugins/skeleton_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -1096,24 +1096,27 @@ Skeleton3DEditor::~Skeleton3DEditor() {
...
-		ne->remove_control_from_menu_panel(skeleton_options);
+		topmenu_bar->remove_child(skeleton_options);
 		memdelete(skeleton_options);
 	}
 
 	if (edit_mode_button) {
-		ne->remove_control_from_menu_panel(edit_mode_button);
+		topmenu_bar->remove_child(edit_mode_button);
 		memdelete(edit_mode_button);
 	}
```
Comment (timothyqiu) [inline editor/plugins/skeleton_3d_editor_plugin.cpp:1116]: Children will automatically be deleted when the parent is deleted.

These separate `remove_child()` and `memdelete()` calls won't be necessary anymore :)

**Review by timothyqiu — APPROVED** [review]

**Comment by JekSun97** [comment]
Thank you for quick bug fix :)

File: editor/plugins/skeleton_3d_editor_plugin.h [hunk 2]
```diff
@@ -113,6 +113,7 @@ class Skeleton3DEditor : public VBoxContainer {
 	};
 
 	EditorInspectorPluginSkeleton *editor_plugin = nullptr;
+	HBoxContainer *topmenu_bar = nullptr;
```
Comment (YuriSizov) [inline editor/plugins/skeleton_3d_editor_plugin.h:116]: Can move this below in place of `separator` which is unused, actually.

**Review by YuriSizov — APPROVED** [review]
Aside from a bit of cleanup, should be good. My bad, missed this in https://github.com/godotengine/godot/pull/81557. Doesn't look like any other toolbar behaves like that.

**Comment by akien-mga** [comment]
Thanks!
