### PR TITLE
[MP] Improve SceneReplicationConfig editor UX + optimizations

### LINKED ISSUE #77896: Improve MultiplayerSynchronizer editor UX to prevent setting both Sync and Watch
### Godot version

4.1.dev4

### System information

Windows 10 Godot 4.1.dev4

### Issue description

The watched property in the Multiplayer Synchronizer node is supposed to pass the variable through the network only when it changes, but as I use the network profiler, it is evidently not working as intended

### Steps to reproduce

Open 2 debug instances on the project I will give, use the network profiler and you will see the variable does not change, although it goes up to 780b/s on the network

### Minimal reproduction project

[minimalproject.zip](https://github.com/godotengine/godot/files/11659414/minimalproject.zip)

### PR DESCRIPTION
**Pull request by Faless**
Make "Sync" and "Watch" mutually exclusive by adding an enum (Never/Always/On Change).

Deprecate old methods.

Prevent invalid NodePath from being added to the config.

Optimize the replication config loading by composing the lists on demand.

Fixes #77896

never_always_change

### CODE REVIEW

File: modules/multiplayer/scene_replication_config.h [hunk 1]
```diff
@@ -86,11 +95,16 @@ class SceneReplicationConfig : public Resource {
 	bool property_get_watch(const NodePath &p_path);
 	void property_set_watch(const NodePath &p_path, bool p_enabled);
 
-	const List<NodePath> &get_spawn_properties() { return spawn_props; }
-	const List<NodePath> &get_sync_properties() { return sync_props; }
-	const List<NodePath> &get_watch_properties() { return watch_props; }
+	ReplicationMode property_get_replication_mode(const NodePath p_path);
```
Comment (AThousandShips) [inline modules/multiplayer/scene_replication_config.h:98]:
```suggestion
	ReplicationMode property_get_replication_mode(const NodePath &p_path);
```

File: modules/multiplayer/scene_replication_config.h [hunk 2]
```diff
@@ -86,11 +95,16 @@ class SceneReplicationConfig : public Resource {
...
+	void property_set_replication_mode(const NodePath p_path, ReplicationMode p_mode);
```
Comment (AThousandShips) [inline modules/multiplayer/scene_replication_config.h:99]:
```suggestion
	void property_set_replication_mode(const NodePath &p_path, ReplicationMode p_mode);
```

File: modules/multiplayer/doc_classes/SceneReplicationConfig.xml [hunk 3]
```diff
@@ -37,49 +37,64 @@
...
-		<method name="property_set_spawn">
+		<method name="property_set_replication_mode">
+			<return type="void" />
+			<param index="0" name="path" type="NodePath" />
+			<param index="1" name="mode" type="int" enum="SceneReplicationConfig.ReplicationMode" />
+			<description>
+				Sets the synchronization mode for the property identified by the given [param path]. See [enum ReplicationMode].
+			</description>
+		</method>
+		<method name="property_set_spawn" is_deprecated="true">
```
Comment (Summersay415) [inline modules/multiplayer/doc_classes/SceneReplicationConfig.xml:76]: Why set spawn is deprecated, but get spawn is not?

Comment (Faless) [reply modules/multiplayer/doc_classes/SceneReplicationConfig.xml]: Ah, nice spot, that was a mistake indeed, should have been added to `property_get/set_watch` and `property_get/set_sync` only.

Fixed.

File: modules/multiplayer/doc_classes/SceneReplicationConfig.xml [hunk 4]
```diff
@@ -66,20 +81,20 @@
...
 			</description>
 		</method>
-		<method name="property_set_sync">
+		<method name="property_set_sync" is_deprecated="true">
 			<return type="void" />
 			<param index="0" name="path" type="NodePath" />
 			<param index="1" name="enabled" type="bool" />
 			<description>
-				Sets whether the property identified by the given [param path] is configured to be synchronized on process.
+				Sets whether the property identified by the given [param path] is configured to be synchronized on process. See [constant REPLICATION_MODE_ALWAYS].
```
Comment (YuriSizov) [inline modules/multiplayer/doc_classes/SceneReplicationConfig.xml:89]: For clarity we usually add a deprecated note in the description. E.g.

```suggestion
				Sets whether the property identified by the given [param path] is configured to be synchronized on process.
				[i]Deprecated.[/i] Use [method property_set_replication_mode] with [constant REPLICATION_MODE_ALWAYS] instead.
```

Similar notes can be added to the getters too.

File: modules/multiplayer/editor/replication_editor.cpp [hunk 5]
```diff
@@ -281,11 +281,8 @@ ReplicationEditor::ReplicationEditor() {
 	tree->set_column_custom_minimum_width(1, 100);
 	tree->set_column_title(2, TTR("Sync"));
```
Comment (YuriSizov) [inline modules/multiplayer/editor/replication_editor.cpp:282]: Since it's "Replication mode" in code, should this perhaps be renamed to "Replicate"?

File: modules/multiplayer/editor/replication_editor.cpp [hunk 6]
```diff
@@ -399,6 +396,11 @@ void ReplicationEditor::_add_pressed() {
 		np_text = "." + np_text;
 	}
 	NodePath path = NodePath(np_text);
+	if (path.is_empty()) {
+		error_dialog->set_text(vformat(TTR("Invalid property path: '%s'"), np_text));
+		error_dialog->popup_centered();
+		return;
+	}
```
Comment (YuriSizov) [inline modules/multiplayer/editor/replication_editor.cpp:403]: This is unrelated to this specific PR, but should we use `EditorNode::get_singleton()->show_warning` instead of a custom dialog?

Comment (Faless) [reply modules/multiplayer/editor/replication_editor.cpp:403]: Well, we are using that error dialog in a bunch of other places, including the recently merged https://github.com/godotengine/godot/pull/65558 .
Should I make a pass to replace all of them in this PR or do it in a separate one?

**Review by YuriSizov — APPROVED** [review]
This change is desired because there was a lot of confusion around the flags. The code looks good too, aside from a couple of nits that I've left.

File: modules/multiplayer/scene_replication_config.cpp [hunk 7]
```diff
@@ -47,38 +47,25 @@ bool SceneReplicationConfig::_set(const StringName &p_name, const Variant &p_val
...
 		ERR_FAIL_INDEX_V(idx, properties.size(), false);
 		ReplicationProperty &prop = properties[idx];
+		if (what == "replication_mode") {
+			ERR_FAIL_COND_V(p_value.get_type() != Variant::INT, false);
+			ReplicationMode mode = (ReplicationMode)p_value.operator int();
+			ERR_FAIL_COND_V(mode < REPLICATION_MODE_NEVER || mode > REPLICATION_MODE_ON_CHANGE, false);
+			property_set_replication_mode(prop.name, mode);
+			return true;
+		}
+		// Deprecated
```
[the remark this answers is not in the document]
Comment (Faless) [reply modules/multiplayer/scene_replication_config.cpp]: Correct, fixed!

File: modules/multiplayer/editor/replication_editor.cpp (hunk 6 above)
Comment (YuriSizov) [reply modules/multiplayer/editor/replication_editor.cpp:403]: It's definitely for a separate PR, would be great if you did a pass!

File: modules/multiplayer/editor/replication_editor.cpp (hunk 5 above)
Comment (Faless) [reply modules/multiplayer/editor/replication_editor.cpp]: I like that, fixed!

File: modules/multiplayer/editor/replication_editor.cpp (hunk 6 above)
Comment (Faless) [reply modules/multiplayer/editor/replication_editor.cpp]: Well, I ended up attaching it to this PR, sorry about that :sweat_smile: ... it was smaller than expected and really straight forward: https://github.com/faless/godot/commit/fb67517edc92d73ddee3a1ef0d5c064be123a0ad .
(it also highlighted a small issue in the current PR where it was trying to `set_checked` instead of `set_range` with more than 64 on change vars)

**Comment by akien-mga** [comment]
Thanks!
