### PR TITLE
GDScript: Restore support for `Token::UNDERSCORE` in identifiers

### LINKED ISSUE #94310: Single underscore node name is ignored when using the $ get_node() shorthand
### Tested versions

4.3.beta1, 4.3.beta3

### System information

Linux Mint 21.3 (Virginia)

### Issue description

When working with $ shorthand node paths in gdscript, a single underscore node name gets ignored.  
Example:
```
SceneRoot
\- _
   \- Node
\- Sibling
   \- _
      \- Node
```
Here, `$_/Node` gets recognised as `/Node`, `$Sibling/_/Node` gets recognised as `Sibling/Node`.

### Steps to reproduce

- Create a scene
- Add a child, name it `_`
- Add a grandchild
- In gdscript, try accessing the grandchild with the $ get_node() shorthand, such as `$_/<Grandchildname>`

### Minimal reproduction project (MRP)

[bugreport_underscore_nodename_absolute_path.zip](https://github.com/user-attachments/files/16202146/bugreport_underscore_nodename_absolute_path.zip)

### PR DESCRIPTION
**Pull request by HolonProduction**
Fixes #94310

`get_identifier` used the token source before. With the introduction of the binary tokenizer this is handled differently, so we need to manually set the identifier on `Token::UNDERSCORE`.

### CODE REVIEW

**Comment by ClayTaeto** [comment]
I would like this feature in

File: modules/gdscript/gdscript_tokenizer.cpp [hunk 1]
```diff
@@ -359,6 +359,11 @@ GDScriptTokenizer::Token GDScriptTokenizerText::make_token(Token::Type p_type) {
 	token.rightmost_column = rightmost_column;
 	token.source = String(_start, _current - _start);
 
+	if (p_type == Token::UNDERSCORE) {
+		// UNDERSCORE could be part of an identifier.
+		token.literal = "_";
+	}
```
Comment (dalexeev) [inline modules/gdscript/gdscript_tokenizer.cpp:365]: You could do it here instead:

https://github.com/godotengine/godot/blob/97b8ad1af0f2b4a216f6f1263bef4fbc69e56c7b/modules/gdscript/gdscript_tokenizer.cpp#L575-L578

This would be a bit more optimized as it would remove branching from the general case.

**Review by dalexeev — APPROVED** [review]

File: modules/gdscript/gdscript_tokenizer.cpp (hunk 1 above)
Comment (HolonProduction) [reply modules/gdscript/gdscript_tokenizer.cpp]: Changed it. The original idea was to prevent similar issues if someone ever was to construct an underscore token in another place, but since there is a testcase we should be fine.

**Comment by akien-mga** [comment]
Thanks!
