### PR TITLE
Fix drag_selection crash on scene close

### LINKED ISSUE #62964: Crash when closing scene
### Godot version

42537da

### System information

Windows 10 x64

### Issue description

Regression from #62539
```
[0] CanvasItemEditor::_draw_transform_message (C:\godot_source\editor\plugins\canvas_item_editor_plugin.cpp:3652)
[1] CanvasItemEditor::_draw_viewport (C:\godot_source\editor\plugins\canvas_item_editor_plugin.cpp:3819)
[2] call_with_variant_args_helper<CanvasItemEditor> (C:\godot_source\core\variant\binder_common.h:264)
[3] call_with_variant_args<CanvasItemEditor> (C:\godot_source\core\variant\binder_common.h:374)
[4] CallableCustomMethodPointer<CanvasItemEditor>::call (C:\godot_source\core\object\callable_method_pointer.h:105)
[5] Callable::call (C:\godot_source\core\variant\callable.cpp:51)
[6] Object::emit_signalp (C:\godot_source\core\object\object.cpp:1014)
[7] Object::emit_signal<> (C:\godot_source\core\object\object.h:825)
[8] CanvasItem::_update_callback (C:\godot_source\scene\main\canvas_item.cpp:144)
[9] call_with_variant_args_helper<CanvasItem> (C:\godot_source\core\variant\binder_common.h:264)
[10] call_with_variant_args_dv<CanvasItem> (C:\godot_source\core\variant\binder_common.h:407)
[11] MethodBindT<CanvasItem>::call (C:\godot_source\core\object\method_bind.h:322)
[12] Object::callp (C:\godot_source\core\object\object.cpp:684)
[13] Callable::call (C:\godot_source\core\variant\callable.cpp:62)
[14] MessageQueue::_call_function (C:\godot_source\core\object\message_queue.cpp:230)
[15] MessageQueue::flush (C:\godot_source\core\object\message_queue.cpp:277)
[16] SceneTree::physics_process (C:\godot_source\scene\main\scene_tree.cpp:421)
[17] Main::iteration (C:\godot_source\main\main.cpp:2824)
[18] OS_Windows::run (C:\godot_source\platform\windows\os_windows.cpp:777)
[19] widechar_main (C:\godot_source\platform\windows\godot_windows.cpp:179)
[20] _main (C:\godot_source\platform\windows\godot_windows.cpp:201)
[21] main (C:\godot_source\platform\windows\godot_windows.cpp:215)
[22] WinMain (C:\godot_source\platform\windows\godot_windows.cpp:229)
[23] __scrt_common_main_seh (D:\a01\_work\26\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[24] BaseThreadInitThunk
-- END OF BACKTRACE --
```
Seems to crash on this line:
https://github.com/godotengine/godot/blob/42537daeb1819b72a700acfe7ab6486b1a5d45d8/editor/plugins/canvas_item_editor_plugin.cpp#L3652
`drag_selection.front()->get()` likely returns a freed object. The weird thing is that there is a safety check against that:
https://github.com/godotengine/godot/blob/42537daeb1819b72a700acfe7ab6486b1a5d45d8/editor/plugins/canvas_item_editor_plugin.cpp#L3648-L3649
So seems like selection list isn't cleared when it should and might hold references to freed objects?

### Steps to reproduce

Exact steps uncertain, but this seems to work reliably:
1. Open any scene with 2D node
2. Select Move Tool (W)
3. Move the 2D node
4. Close the scene tab and discard changes
5. Crash

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #62964

It's a bit worrying that `drag_selection` nodes can get invalidated, but I couldn't find an easy solution for that.

### CODE REVIEW

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -3645,7 +3645,7 @@ void CanvasItemEditor::_draw_hover() {
 }
 
 void CanvasItemEditor::_draw_transform_message() {
-	if (drag_selection.is_empty() || !drag_selection.front()->get()) {
+	if (drag_type == DRAG_NONE || drag_selection.is_empty() || !drag_selection.front()->get()) {
```
Comment (Rindbee) [inline editor/plugins/canvas_item_editor_plugin.cpp:3648]: When the scene tab is switched, `drag_selection` contains nodes that are not in the tree. 
```suggestion
	if (drag_selection.is_empty() || !drag_selection.front()->get() || !drag_selection.front()->get()->is_inside_tree() ) {
```

Comment (KoBeWi) [reply editor/plugins/canvas_item_editor_plugin.cpp:3648]: But `drag_type` is still `DRAG_NONE`, so contents of `drag_selection`.

I agree that clearing the selection would be better solution, but it's not obvious when it should be done.

**Review by akien-mga — APPROVED** [review]
Seems ok as a stopgap, though should likely be investigated further.
