### PR TITLE
Fix light culling mask behavior in Mobile and Compat renderers

### LINKED ISSUE #82263: Mobile/Compatibility: SpotLight and OmniLight cull masks don't cull moving meshes
### Godot version

v4.1.1.stable.official[bd6af8e0e]

### System information

Windows 10 - Godot 4.1.1 Stable - Mobile

### Issue description

Both Omni lights and spotlights will light up a mesh that has been transformed, despite there being no overlapping layers. This does not appear to be a problem with the Forward+ Renderer nor with directional lights on the mobile renderer.

In this example I have two lights, one is set to affect all layers, the light is periodically toggled on and off,
another light is on all of the time, but it's cull mask is only set to affect layer 2, which neither of the Mesh Instances are on.
The expected behaviour is that when the first light is toggled, the cubes will no longer be visible,

Expected Behaviour

as works on the Forward+ renderer. However when using the mobile renderer, Meshes will reappear again if they are moved (via script) and will not disappear even if their movement is stopped.

Mobile Behaviour

I first noticed this behaviour when I was attempting to do an effect where all but one object would fade to black because it was the only mesh on a specific layer (which the spotlight cull was also set to) however other objects still appeared despite not being on that layer because they had been or were being moved.

### Steps to reproduce

Start a project with the mobile renderer

Create a 3D scene with a mesh that can be moved.
image
image
image

Create a spot light or omni light near the mesh so that it is noticeably lit.
image

Set the Cull Mask of the light to only affect layers that do not overlap with the cube's VisualInstance3D layers
image

The cube will correctly not be lit by the spotlight upon first playing, but once the cube has been moved, it will suddenly be lit up.
GIF 2023-09-24 1-28-41 PM

### Minimal reproduction project

[Light Cull Mask Mini Project.zip](https://github.com/godotengine/godot/files/12709615/Light.Cull.Mask.Mini.Project.zip)

*Production edit (keywords for easier searching): OpenGL*

### LINKED ISSUE #94643: MeshInstance3D visual instance layer ignored by OmniLight3D in the Compatibility and Mobile renderers
### Tested versions

- Reproducible in 4.0.3, 4.1.2, and 4.2.2

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.4612) - 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz (16 Threads)

### Issue description

When a MeshInstance3D is moved, it starts showing light from any OmniLight3D, regardless of what visual instance layer the mesh is assigned to. This has been tested to occur when the MeshInstance3D is moved in editor, changes visibility in the editor, or is moved at runtime by an AnimationPlayer or by being a child of a RigidBody3D. In the Forward+ renderer, the visual instance layer continues to be respected by the OmniLight3D

### Steps to reproduce

- Create a MeshInstance3D and OmniLight3D
- Configure the MeshInstance3D and OmniLight3D so that the visual instance layers of the MeshInstance3D have no overlap with the cull mask or visual instance layers of the OmniLight3D
- Move the MeshInstance3D in the editor

### Minimal reproduction project (MRP)

[visual_instance_omnilight_compatibility.zip](https://github.com/user-attachments/files/16342924/visual_instance_omnilight_compatibility.zip)

### PR DESCRIPTION
**Pull request by franeaux**
Fixes #94643. Added logic which checks the light's culling mask settings before proceeding with lighting calculations to wherever not present (namely the Forward-Mobile and Compatibility renderers). Just a simple port of the one already used in the Forward-Plus renderer.

Pictures for comparison:

<details>
<summary>MRP:</summary>
Compatibility: <br/>
bug-compat
<br>Forward+: <br/>
bug-fplus
<br>Forward-Mobile: <br/>
bug-mobilee
</details>

<details>
<summary>Fixed:</summary>
Compatibility: <br/>
fix-compat
<br>Forward+: <br/>
fix-fplus
<br>Forward-Mobile: <br/>
fix-mobile

</details>

(Also fixes the bug in editor mode too)

- *Production edit: This closes https://github.com/godotengine/godot/issues/82263.*

### CODE REVIEW

**Review by Calinou — CHANGES_REQUESTED** [review]
Tested locally, it works as expected in Mobile and Compatibility.

However, the solution used in Mobile is probably not the correct one, as it'd leave performance on the table since lights would not be culled on the CPU before being sent to the GPU. See comments in https://github.com/godotengine/godot/pull/86105, as it's the same fix as applied there (except it's applied in two locations in that PR).

I suggest looking at moving the culling to the CPU side in Mobile, as is already done in Compatibility in your PR. If you can't find a way to do this, then I suggest removing the Mobile changes so the Compatibility changes can be merged first.

**Comment by clayjohn** [comment]
I think in both cases the check should be inside of `pair_light_instances()` so that it is done at culling time and also you aren't pairing with lights that are masked out anyway.

**Comment by m-pranav-r** [comment]
(I really should have consulted this page again before making the changes, I think I added the culling logic _just_ before the pairing call but I'll revise it if need be.)

Shifted culling back to CPU so that the light instances indices wont be sent to the buffer at all. Also covers both spot and omni lights.

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected in Compatibility and Mobile.

This should be good to merge after squashing the 2 commits together; see [PR workflow](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

File: drivers/gles3/rasterizer_scene_gles3.cpp [hunk 1]
```diff
@@ -1298,6 +1298,11 @@ void RasterizerSceneGLES3::_fill_render_list(RenderListType p_render_list, const
 					RID light = light_storage->light_instance_get_base_light(light_instance);
 					int32_t shadow_id = light_storage->light_instance_get_shadow_id(light_instance);
 
+					//Skip lights that do not contribute to the current instance
+					if (!(light_storage->light_get_cull_mask(light) & inst->layer_mask)) {
```
Comment (clayjohn) [inline drivers/gles3/rasterizer_scene_gles3.cpp:1302]: If the light is already culled in `_scene_cull()` then this check is unnecessary right?

Comment (m-pranav-r) [reply drivers/gles3/rasterizer_scene_gles3.cpp:1302]: Yes. I skipped the check and it works just fine. (sry for that!)

**Review by clayjohn — APPROVED** [review]
Looks great now! Thank you for investigating further.

**Comment by Repiteo** [comment]
Thanks!
