### PR TITLE
Ask before closing with unsaved resources

### LINKED ISSUE #45612: Quit does not ask to save resources and causes data loss.
**Godot version:**
4.0.dev c9413b513fd2fb95e9b71d886e01a04e379bb969

**OS/device including version:**
Windows 10.0.19041.746
Nvidia RTX 2080 Ti driver 452.06

**Issue description:**
When exiting the editor (such as Quit; or Quit to Project List; or the X button on the godot editor), no attempt is made to notify the user of unsaved resources, and in the case that no unsaved scenes are open, no attempt is made to give the user a chance to save their work.

Note that when the current *scene* is unsaved, the editor may pop up a confirmation dialog. However, this dialog has a few problems.
1. When no scenes have unsaved changes, the dialog does not even appear, and the editor is closed instantly.
2. It does not notify the user of the fact that there are unsaved resources in addition to the scene.
3. If the user clicks "Dont Save" in order not to save the scene, the resource changes are discarded.

image

Related to issues #45611 and #9069, but this problem is about the lack of confirmation at the moment when data is about to be lost.

One solution would be to notify the user of unsaved resources.
Another solution would be to automatically save them (given that other unrelated actions can sometimes automatically save all resources without notification or confirmation)

**Steps to reproduce:**
1. Create a new project or open existing
2. Double click default_env.tres
3. Expand Sky. Then, in the Sky fleld, click Sky to expand the sky object.
4. In the Sky Material box, create a new PanoramaSky
5. The 3d scene should turn light blue.
6. Quit to Project List and reopen.
7. The default_sky.tres was not saved. The scene is black again.

**Minimal reproduction project:**
Happens in a new project

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #45612

If none of the scenes have unsaved changed, but the global history is unsaved, a unique dialog appears:
image

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -2657,22 +2657,36 @@ void EditorNode::_menu_option_confirm(int p_option, bool p_confirmed) {
 		case FILE_CLOSE_ALL_AND_RELOAD_CURRENT_PROJECT: {
 			if (!p_confirmed) {
 				tab_closing_idx = _next_unsaved_scene(false);
-				_scene_tab_changed(tab_closing_idx);
+				if (tab_closing_idx == -1) {
+					tab_closing_idx = -2; // Only external resources are unsaved.
```
Comment (akien-mga) [inline editor/editor_node.cpp:2661]: Could maybe use a local bool instead of using a new magic number in an unrelated index?

Comment (KoBeWi) [reply editor/editor_node.cpp:2661]: It can't be a local bool, because the value is also used elsewhere. Re-using the variable was simpler to do and is less error-prone than adding a new variable and making sure it's used where necessary.

Comment (akien-mga) [reply editor/editor_node.cpp:2661]: But outside this scope, does it serve a purpose and is it properly handled that `tab_closing_idx` stays `-2`?

What I meant with a local bool would be this:
```
tab_closing_idx = _next_unsaved_scene(false);
bool ext_res_only = false;
if (tab_closing_idx == -1) {
	ext_res_only = true;
} else {
	_scene_tab_changed(tab_closing_idx);
}
```

Comment (KoBeWi) [reply editor/editor_node.cpp:2661]: Yes, here:
https://github.com/godotengine/godot/blob/8b79a19426c7f5eab04caa573866276c76c70871/editor/editor_node.cpp#L1958-L1960

Comment (akien-mga) [reply editor/editor_node.cpp:2661]: That's pretty smelly :(

But well, I guess this can be revisited in the future.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
