### PR TITLE
C#: Ensure .NET editor supports Visual Studio 2026

### LINKED ISSUE #112675: Godot on Windows always uses Visual Studio 2022 instead of Visual Studio 2026
### Tested versions

Reproduced in Godot v4.5.1.stable.mono

### System information

Godot v4.5.1.stable.mono - Windows 11 (build 26200) - Multi-window, 2 monitors - Vulkan (Mobile) - integrated Intel(R) Graphics (Intel Corporation; 32.0.101.6129) - Intel(R) Core(TM) Ultra 7 165U (14 threads) - 15.57 GiB memory

### Issue description

When both Visual Studio 2022 and Visual Studio 2026 are installed on Windows, Godot always launches Visual Studio 2022 regardless of configuration. Setting the editor under Editor → Editor Settings → Dotnet → Editor → Visual Studio forces Godot to use 2022.

Here's what I tried without any luck:
* Changing the Windows default program for .sln and .csproj files to VS 2026
* Setting the Custom Exec Path to point to the VS 2026 executable - this is ignored unless using "Custom" instead of "Visual Studio", and if "Custom" is elected, it opens a new instance of VS 2026 every time you click a C# script.

This makes it impossible to use VS 2026 smoothly with Godot, even though it is installed and set as the default solution editor in Windows.

### Steps to reproduce

Install both VS2022 and VS2026 and click a C# script in the Godot editor.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Repiteo**
- Fixes #112675
- Supersedes #110851
- Supersedes #112677

Considered writing up reviews for the above PRs, but this is functionally a release blocker and it's been straggling for a while now, so I'd prefer it dealt with expediently. This adds detection/launch support for Visual Studio 2026, and removes it for Visual Studio 2019.

### CODE REVIEW

File: modules/mono/editor/GodotTools/GodotTools.OpenVisualStudio/Program.cs [hunk 1]
```diff
@@ -46,19 +46,13 @@ private static int Main(string[] args)
...
                 {
-                    // Launch of VS 2022 failed, fallback to 2019
-                    dte = TryVisualStudioLaunch("VisualStudio.DTE.16.0");
-
-                    if (dte == null)
-                    {
-                        Console.Error.WriteLine("Visual Studio not found");
-                        return 1;
-                    }
+                    Console.Error.WriteLine("Supported Visual Studio not found");
```
Comment (akien-mga) [inline modules/mono/editor/GodotTools/GodotTools.OpenVisualStudio/Program.cs]:
```suggestion
                    Console.Error.WriteLine("Could not find a supported Visual Studio version (VS 2026 or VS 2022).");
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Cherry-picked for 4.5.2.
