### PR TITLE
FileSystem: Force update when we delete a folder from the editor and …

### LINKED ISSUE #46469: Multiple folder delete through editor filesystem dock crashes editor
**Godot version:**
v3.2.4-rc3

**OS/device including version:**
Win 10 64x

**Issue description:**
Deleting multiple project folders one by one (not at the same time) through editor filesystem dock gets editor stuck in an infinite loop with console spam.

First folder delete  through the editor filesystem dock works flawless.
Second folder delete (doesn't matter if already empty or folder is full of files) the editor seems to be stuck in an infinite loop.
After a few seconds editor prints a generic file access error to the console.
After another few seconds editor prints another generic file access error to the console.
After some time editor gives up and spams the console endless with "Cannot open file from path 'XYZ'" At: editor/editor_file_system.cpp:1801
The XYZ filepaths that get spamed are previous deleted filepaths and sometimes completely unrelated filepaths in the project.
The editor is unresponsive and requires a hardreset.

The Godot editor runs with with admin and full fileaccess rights so that shouldn't be the issue. Maybe this is a Windows only issue, I can't test on Linux.

**Steps to reproduce:**
Delete one project subfolder through the editor filesystem dock, now delete another.

**Minimal reproduction project:**
see steps

### PR DESCRIPTION
**Pull request by kuruk-mm**
…searching changes only if we change the directory successfully in the scan_fs_changes

Fix #46469 

I gave the explanation of this in the issue. I think this is the best idea to fix this bug without changing the performance.

And I don't found a better name to `force_update`... `reset_modified_time` maybe is better.

### CODE REVIEW

File: editor/editor_file_system.cpp [hunk 1]
```diff
@@ -852,94 +856,96 @@ void EditorFileSystem::_scan_fs_changes(EditorFileSystemDirectory *p_dir, const
...
-			String f = da->get_next();
-			if (f == "") {
-				break;
-			}
-
-			if (da->current_is_hidden()) {
-				continue;
-			}
+		Error ret = da->change_dir(cd);
+		if (ret == OK) {
```
Comment (kuruk-mm) [inline editor/editor_file_system.cpp:860]: I just added this `IF`, i don't know why git found all those changes.

Comment (YeldhamDev) [reply editor/editor_file_system.cpp:860]: Indentation change, makes a mess out of the diff.

**Review by KoBeWi — APPROVED** [review]

File: editor/editor_file_system.cpp (hunk 1 above)
Comment (akien-mga) [reply editor/editor_file_system.cpp:860]: It would look better if you changed `da` to a `DirAccessRef` (so it doesn't need to be `memdelete`d), and then you can do an early return instead of indenting the whole world:
```
Error err = da->change_dir(cd);
if (err) {
    return;
}

da->list_dir_begin();
// etc.
```

File: editor/editor_file_system.cpp [hunk 2]
```diff
@@ -68,6 +68,10 @@ int EditorFileSystemDirectory::find_dir_index(const String &p_dir) const {
 	return -1;
 }
 
+void EditorFileSystemDirectory::force_update() {
+	modified_time = 0;
```
Comment (akien-mga) [inline editor/editor_file_system.cpp:72]: Might need an explanatory comment, it's not obvious how changing the `modified_time` will force an update.

Comment (kuruk-mm) [reply editor/editor_file_system.cpp:72]: `// We set modified_time to 0 to force `EditorFileSystem::_scan_fs_changes` to search changes in the directory`

seems good?

Comment (akien-mga) [reply editor/editor_file_system.cpp:72]: Yeah :)

File: editor/editor_file_system.cpp (hunk 1 above)
Comment (kuruk-mm) [reply editor/editor_file_system.cpp:860]: If we do that, we stop the recursive search of changes on an error.

Here is the code in the bottom of that function
```
	for (int i = 0; i < p_dir->subdirs.size(); i++) {
		if (updated_dir && !p_dir->subdirs[i]->verified) {
			//this directory was removed, add action to remove it
			ItemAction ia;
			ia.action = ItemAction::ACTION_DIR_REMOVE;
			ia.dir = p_dir->subdirs[i];
			scan_actions.push_back(ia);
			continue;
		}
		_scan_fs_changes(p_dir->get_subdir(i), p_progress); // <-- we need to execute this
	}
```

Comment (akien-mga) [reply editor/editor_file_system.cpp:860]: Ah right, too bad then.

Comment (kuruk-mm) [reply editor/editor_file_system.cpp:860]: > Ah right, too bad then. Indentation it will be :)

Ok, I analized it a bit further. And I maybe you're right.

For the readers, this function detects changes in the FileSystem and notify Godot on new/delete/modifications. So it doesn't affect the files directly, is just we see on the editor.

And an error on that line is not normal at all. Something very bad happened.

So... If we use what I did every file that has an error, will be treated as `deleted` in Godot File System. So it will 'dissapear' from Godot. So I don't know if that is the desired behavior.

If we add a `return` like you said, it will not update our Godot File System at all and it will remain the same, and we can add a print_error.

If we want to change what I did, I would like to make some tests in the weekend to give more feedback.

Comment (akien-mga) [reply editor/editor_file_system.cpp:860]: If an error on this line is not expected you can just use `ERR_FAIL_COND_MSG` and it will return with an error message. It won't process the rest but at that point it might be in a too damaged state for the rest to be meaningful indeed.

**Comment by kuruk-mm** [comment]
Done, I tested and I triggered the error manually (must never happens in normal conditions). And the only side effect is not getting an update on the GUI for a second.

Please take a look :)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.
