### PR TITLE
[EditorHelpBit] Open online documentation if script editor is not available.

### LINKED ISSUE #113614: Crash clicking documentation links in EditorSettings tooltips from the Project Manager
### Tested versions

- Reproducible in: v4.6.dev.custom_build [3edd256a6], v4.6.dev5.official [f5918a9d3]
- Not reproducible in: 4.5.1.stable, v4.6.dev2.official [7864ac801], v4.6.dev3.official [9d84f3d13]

### System information

Godot v4.6.dev (3edd256a6) - Arch Linux #1 SMP PREEMPT_DYNAMIC Mon, 24 Nov 2025 15:21:09 +0000 on X11 - X11 display driver, Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3060 Ti (nvidia; 580.105.08) - 13th Gen Intel(R) Core(TM) i5-13400F (16 threads) - 15.37 GiB memory

### Issue description

From the Editor Settings dialog opened in the Project Manager, clicking any doc link in the tooltip results in a crash.

Image

<details><summary>Output</summary>

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.6.dev.custom_build (3edd256a6f8f72d8c656f02e319e280151187840)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x3e4d0) [0x7f1ff943e4d0] (??:0)
[2] EditorNode::get_editor_main_screen() (/home/timothy/repos/godot-master/editor/editor_node.h:745)
[3] EditorHelpBit::_go_to_help(String const&) (/home/timothy/repos/godot-master/editor/doc/editor_help.cpp:4222 (discriminator 2))
[4] EditorHelpBit::_meta_clicked(String const&) (/home/timothy/repos/godot-master/editor/doc/editor_help.cpp:4293 (discriminator 7))
[5] void call_with_variant_args_helper<EditorHelpBit, String const&, 0ul>(EditorHelpBit*, void (EditorHelpBit::*)(String const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (/home/timothy/repos/godot-master/core/variant/binder_common.h:224 (discriminator 6))
[6] void call_with_variant_args<EditorHelpBit, String const&>(EditorHelpBit*, void (EditorHelpBit::*)(String const&), Variant const**, int, Callable::CallError&) (/home/timothy/repos/godot-master/core/variant/binder_common.h:339)
[7] CallableCustomMethodPointer<EditorHelpBit, void, String const&>::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/timothy/repos/godot-master/core/object/callable_method_pointer.h:107)
[8] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (/home/timothy/repos/godot-master/core/variant/callable.cpp:57)
[9] Object::emit_signalp(StringName const&, Variant const**, int) (/home/timothy/repos/godot-master/core/object/object.cpp:1362)
[10] Node::emit_signalp(StringName const&, Variant const**, int) (/home/timothy/repos/godot-master/scene/main/node.cpp:4189)
[11] Error Object::emit_signal<Variant>(StringName const&, Variant) (/home/timothy/repos/godot-master/core/object/object.h:978)
[12] RichTextLabel::gui_input(Ref<InputEvent> const&) (/home/timothy/repos/godot-master/scene/gui/rich_text_label.cpp:2850 (discriminator 3))
[13] Control::_call_gui_input(Ref<InputEvent> const&) (/home/timothy/repos/godot-master/scene/gui/control.cpp:1891)
[14] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (/home/timothy/repos/godot-master/scene/main/viewport.cpp:1736)
[15] Viewport::_gui_input_event(Ref<InputEvent>) (/home/timothy/repos/godot-master/scene/main/viewport.cpp:2013 (discriminator 2))
[16] Viewport::push_input(RequiredParam<InputEvent>, bool) (/home/timothy/repos/godot-master/scene/main/viewport.cpp:3511 (discriminator 2))
[17] Window::_window_input(Ref<InputEvent> const&) (/home/timothy/repos/godot-master/scene/main/window.cpp:1850 (discriminator 1))
[18] void call_with_variant_args_helper<Window, Ref<InputEvent> const&, 0ul>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (/home/timothy/repos/godot-master/core/variant/binder_common.h:224 (discriminator 6))
[19] void call_with_variant_args<Window, Ref<InputEvent> const&>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, int, Callable::CallError&) (/home/timothy/repos/godot-master/core/variant/binder_common.h:339)
[20] CallableCustomMethodPointer<Window, void, Ref<InputEvent> const&>::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/timothy/repos/godot-master/core/object/callable_method_pointer.h:107)
[21] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (/home/timothy/repos/godot-master/core/variant/callable.cpp:57)
[22] Variant Callable::call<Ref<InputEvent> >(Ref<InputEvent>) const (/home/timothy/repos/godot-master/core/variant/variant.h:942)
[23] DisplayServerX11::_dispatch_input_event(Ref<InputEvent> const&) (/home/timothy/repos/godot-master/platform/linuxbsd/x11/display_server_x11.cpp:4473 (discriminator 2))
[24] DisplayServerX11::_dispatch_input_events(Ref<InputEvent> const&) (/home/timothy/repos/godot-master/platform/linuxbsd/x11/display_server_x11.cpp:4450)
[25] Input::_parse_input_event_impl(Ref<InputEvent> const&, bool) (/home/timothy/repos/godot-master/core/input/input.cpp:987)
[26] Input::flush_buffered_events() (/home/timothy/repos/godot-master/core/input/input.cpp:1292)
[27] DisplayServerX11::process_events() (/home/timothy/repos/godot-master/platform/linuxbsd/x11/display_server_x11.cpp:5612)
[28] OS_LinuxBSD::run() (/home/timothy/repos/godot-master/platform/linuxbsd/os_linuxbsd.cpp:990)
[29] bin/godot.linuxbsd.editor.dev.x86_64(main+0x23d) [0x55ca41a4f87d] (/home/timothy/repos/godot-master/platform/linuxbsd/godot_linuxbsd.cpp:121)
[30] /usr/lib/libc.so.6(+0x27635) [0x7f1ff9427635] (??:0)
[31] /usr/lib/libc.so.6(__libc_start_main+0x89) [0x7f1ff94276e9] (??:0)
[32] bin/godot.linuxbsd.editor.dev.x86_64(_start+0x25) [0x55ca41a30125] (??:?)
-- END OF C++ BACKTRACE --
================================================================
```
</details>

### Steps to reproduce

1. Open the Project Manager
2. Click Settings
3. Click Edit All Settings
4. Hover over any property that has a doc link in its tooltip, e.g., `Editor Language`
5. Click that link and see the engine crashes

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/113614

### CODE REVIEW

File: editor/doc/editor_help.cpp [hunk 1]
```diff
@@ -4218,9 +4218,63 @@ void EditorHelpBit::_update_labels() {
...
+				parts.push_back(p_what.substr(buffer_start, pos - buffer_start));
+				from = pos + 1;
+				buffer_start = from;
+			}
+		}
+	}
+
+	const String what = parts[0]; // `parts` is always non-empty.
+	const String clss = (parts.size() > 1) ? parts[1].to_lower() : String();
+	const String name = (parts.size() > 2) ? parts[2].to_lower().replace("/", "-").replace("_", "-") : String();
```
Comment (AThousandShips) [inline editor/doc/editor_help.cpp]:
```suggestion
	const String name = (parts.size() > 2) ? parts[2].to_lower().replace_chars("/_", '-') : String();
```

**Review by akien-mga — APPROVED** [review]

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
