### PR TITLE
Autocompletion: Don't call const functions

### LINKED ISSUE #57669: Segmentation fault when duplicating a Node's script from inside the node
### Godot version

3.4.2.stable

### System information

Windows 10, AMD Ryzen 7 5800X, NVIDIA RTX 3080

### Issue description

While writing a script, **not while the game is running**, when duplicating a Node's script from within the same script and then trying to access that duplicate script causes a segfault. Please note that the game was not run, simply typing something in the editor causes the crash.

## Use case
I am dynamically creating new scripts at runtime. Instead of using a dummy node with a script attached, I thought it would be nice to simply duplicate the current node's script instead.

## Stacktrace
```
$ ./Godot_v3.4.2-stable_win64.exe --editor --verbose --path ../dev/repl-gd/
Godot Engine v3.4.2.stable.official.45eaa2daf - https://godotengine.org
Using GLES3 video driver
OpenGL ES 3.0 Renderer: NVIDIA GeForce RTX 3080/PCIe/SSE2
OpenGL ES Batching: ON
        OPTIONS
        max_join_item_commands 16
        colored_vertex_format_threshold 0.25
        batch_buffer_size 16384
        light_scissor_area_threshold 1
        item_reordering_lookahead 4
        light_max_join_items 32
        single_rect_fallback False
        debug_flash False
        diagnose_frame False
WASAPI: wFormatTag = 65534
WASAPI: nChannels = 2
WASAPI: nSamplesPerSec = 48000
WASAPI: nAvgBytesPerSec = 384000
WASAPI: nBlockAlign = 8
WASAPI: wBitsPerSample = 32
WASAPI: cbSize = 22
WASAPI: detected 2 channels
WASAPI: audio buffer frames: 1962 calculated latency: 44ms

CORE API HASH: 2238588822097579888
EDITOR API HASH: 10291639213636549143
Construct gdnative interface

Destruct gdnative interface

Class 'BulletPhysicsDirectBodyState' is not exposed, skipping.
Class 'BulletPhysicsDirectSpaceState' is not exposed, skipping.
Class 'BulletPhysicsServer' is not exposed, skipping.
Class 'GDScriptNativeClass' is not exposed, skipping.
Class 'IP_Unix' is not exposed, skipping.
Class 'InputDefault' is not exposed, skipping.
Class 'Physics2DDirectBodyStateSW' is not exposed, skipping.
Class 'Physics2DDirectSpaceStateSW' is not exposed, skipping.
Class 'Physics2DServerSW' is not exposed, skipping.
Class 'ResourceImporterMP3' is not exposed, skipping.
Class 'ResourceImporterOGGVorbis' is not exposed, skipping.
Loading resource: C:/redacted ;)/editor_settings-3.tres
EditorSettings: Load OK!
Loaded builtin certs
EditorSettings: Save OK!
Loading resource: res://addons/repl-gd/standalone/dummy_plugin.gd
Loading resource: res://addons/repl-gd/fake_tree.gd
Loading resource: res://addons/repl-gd/plugin.gd
Loading resource: res://addons/repl-gd/repl.gd
Loading resource: res://addons/repl-gd/standalone/main_shim.tscn
Loading resource: res://addons/repl-gd/repl.tscn
Loading resource: res://addons/repl-gd/repl.tscn
Segmentation fault
```

### Steps to reproduce

Minimal reproduction code in a completely new project. There is no need to run the game.
```
extends Node

var dummy: GDScript

func _ready():
	dummy = get_script().duplicate()
	# start typing 'dummy.'
        # Typing the period character will cause a segfault
```

### Minimal reproduction project

[segfault-3.4.2.zip](https://github.com/godotengine/godot/files/8008512/segfault-3.4.2.zip)

### LINKED ISSUE #109193: Crash with Signal 11 (SIGSEGV) in Godot 4.4.1 (No Debug Info in Backtrace)
### Tested versions

v4.4.1.stable.official [49a5bc7b6]

### System information

Godot v4.4.1.stable - Windows 11 (build 26100) - Multi-window, 1 monitor - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4060 Laptop GPU (NVIDIA; 32.0.15.6100) - Intel(R) Core(TM) i9-14900HX (32 threads)

### Issue description

The project crashes with a Signal 11 (SIGSEGV – Segmentation Fault). The backtrace shows no debug info (no debug info in PE/COFF executable), making it difficult to pinpoint the exact cause.
This crash is sometimes triggered when the smart prompt is triggered。
`
================================================================
CrashHandlerException: Program crashed with signal 11
Engine version: Godot Engine v4.4.1.stable.official (49a5bc7b616bd04689a2c89e89bda41f50241464)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] error(-1): no debug info in PE/COFF executable
[2] error(-1): no debug info in PE/COFF executable
[3] error(-1): no debug info in PE/COFF executable
[4] error(-1): no debug info in PE/COFF executable
[5] error(-1): no debug info in PE/COFF executable
[6] error(-1): no debug info in PE/COFF executable
[7] error(-1): no debug info in PE/COFF executable
[8] error(-1): no debug info in PE/COFF executable
[9] error(-1): no debug info in PE/COFF executable
[10] error(-1): no debug info in PE/COFF executable
[11] error(-1): no debug info in PE/COFF executable
[12] error(-1): no debug info in PE/COFF executable
[13] error(-1): no debug info in PE/COFF executable
[14] error(-1): no debug info in PE/COFF executable
[15] error(-1): no debug info in PE/COFF executable
[16] error(-1): no debug info in PE/COFF executable
[17] error(-1): no debug info in PE/COFF executable
[18] error(-1): no debug info in PE/COFF executable
[19] error(-1): no debug info in PE/COFF executable
[20] error(-1): no debug info in PE/COFF executable
[21] error(-1): no debug info in PE/COFF executable
[22] error(-1): no debug info in PE/COFF executable
[23] error(-1): no debug info in PE/COFF executable
[24] error(-1): no debug info in PE/COFF executable
[25] error(-1): no debug info in PE/COFF executable
[26] error(-1): no debug info in PE/COFF executable
[27] error(-1): no debug info in PE/COFF executable
[28] error(-1): no debug info in PE/COFF executable
[29] error(-1): no debug info in PE/COFF executable
[30] error(-1): no debug info in PE/COFF executable
[31] error(-1): no debug info in PE/COFF executable
[32] error(-1): no debug info in PE/COFF executable
[33] error(-1): no debug info in PE/COFF executable
[34] error(-1): no debug info in PE/COFF executable
[35] error(-1): no debug info in PE/COFF executable
[36] error(-1): no debug info in PE/COFF executable
[37] error(-1): no debug info in PE/COFF executable
[38] error(-1): no debug info in PE/COFF executable
[39] error(-1): no debug info in PE/COFF executable
[40] error(-1): no debug info in PE/COFF executable
[41] error(-1): no debug info in PE/COFF executable
[42] error(-1): no debug info in PE/COFF executable
[43] error(-1): no debug info in PE/COFF executable
[44] error(-1): no debug info in PE/COFF executable
[45] error(-1): no debug info in PE/COFF executable
[46] error(-1): no debug info in PE/COFF executable
[47] error(-1): no debug info in PE/COFF executable
[48] error(-1): no debug info in PE/COFF executable
-- END OF BACKTRACE --
`

### Steps to reproduce

Open the project.  
Run a specific scene. 
Write code (press enter the result of the smart prompt)
Crash occurs. 

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by HolonProduction**
Fixes https://github.com/godotengine/godot/issues/109193
Fixes https://github.com/godotengine/godot/issues/57669

Supersedes https://github.com/godotengine/godot/pull/85361

Makes https://github.com/godotengine/godot/pull/109211 and https://github.com/godotengine/godot/pull/109218 not required anymore CC @clayjohn 

Autocompletion does not only rely on Godot analyzer types, but does some additional inference work beforehand. One of the approaches for this, was to actually call some functions and deduce a type from the returned value.

This however disregards that calling those functions might have side effects, e.g. in https://github.com/godotengine/godot/issues/109193 the called function would allocate memory. The `const` identifier is not a strict enough check to assume that there are no side effects.

This PR removes this behavior completely. This might break some cases that currently work, but the actual impact is limited:

Due to a bug in the original code, only `const` methods which can be called without providing arguments would actually be executed (notice how no values ever get added to `args` in the old code). So I read through all `const` methods which can take no args to evaluate the actual impact. The methods can be split into certain groups:

- Having an annotated builtin return type that is not a container type and not `Variant` -> the return value provides the same results as the type hint, no impact
- The method is declared on some ref counted class which there is no way to obtain a constant instance of -> e.g. `PhysicsTestMotionResult2D` -> would never be called due to no constant base object
- The method is a property getter -> no one actually uses property getters in GDScript, they are not even suggested by autocompletion. Using the property is a completely different code path anyway
- The method accesses some dynamic object state -> e.g. get_currently_focused_control -> using the static type hint is safer anyway since the state while editing might not match the runtime state
- Same for a lot of methods that return object types that can be polymorphic -> calling it would yield the correct polymorphic type but I'd argue that just leads to unsafe suggestions, users should use casting and type checking if the code relies on receiving a certain subtype

The main use case for this piece of code are methods which return a structured dictionary. For those autocompletion can actually suggest the keys. I added dummy results for the limited set of methods to which this applied.

I also added some special handling for `duplicate` methods since those can be quite handy IMO. Other than that most effected results are either too unsafe or so unlikely to actually hit, that we can add a special case if anyone actually notices the change.

> This PR also removes some code that is duplicated with the analyzer. GDScript utility functions and Builtin type constructors are always correctly resolved by the analyzer we don't need special code in the completion for it. I also removed the `get_node` special case. It was dead code due to the `args` bug mentioned above.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
I can't properly review the code, but I tested locally and confirmed this fixes the issue with leaking the local rendering device and it doesn't appear to change the code completion recommendations for any of the code I tested

I suspect a lot of the perceived instability of Godot when working with advanced rendering features comes from https://github.com/godotengine/godot/issues/109193, so I believe that this PR will be a huge step forward in the perceived stability of Godot for advanced users

**Review by Calinou — APPROVED** [review]
Code looks good to me.

I think the "static declaration" approach for autocompletion of dictionaries returned by Engine methods makes sense. It's likely the best we can do while keeping autocompletion's behavior as static as possible.

This PR will probably also help with performance a little when working in the code editor, at least on the power usage/battery life front.

File: modules/gdscript/gdscript_editor.cpp [hunk 1]
```diff
@@ -1764,6 +1764,113 @@ static bool _is_expression_named_identifier(const GDScriptParser::ExpressionNode
...
 }
 
+// Creates a map of exemplary results for some functions that return a structured dictionary.
+// Setting this example as value allows autocompletion to suggest the specific keys in some cases.
+static HashMap<String, Dictionary> make_structure_samples() {
+	HashMap<String, Dictionary> res;
+	const Array arr;
+
+	{
+		Dictionary d;
```
Comment (bruvzg) [inline modules/gdscript/gdscript_editor.cpp:1774]: Not important for a fix, but keeping this list up to date won't be convenient. This feels like something that should be part of `ClassDB` and defined in the `bind_methods` near the method definition:

Image

Comment (Mickeon) [reply modules/gdscript/gdscript_editor.cpp:1774]: I'd slap a big TODO here because these dictionaries should really be structs once implemented properly. If this list is to be inserted in **ClassDB** it should not be present in release builds as it serves no purpose.

File: modules/gdscript/gdscript_editor.cpp [hunk 2]
```diff
@@ -1884,156 +1991,68 @@ static bool _guess_expression_type(GDScriptParser::CompletionContext &p_context,
...
-								if (!found && all_is_const && baseptr) {
-									Vector<const Variant *> argptr;
-									for (int i = 0; i < args.size(); i++) {
-										argptr.push_back(&args[i]);
-									}
-
-									Callable::CallError ce;
-									Variant ret = mb->call(baseptr, (const Variant **)argptr.ptr(), argptr.size(), ce);
+					// Simulate generics for some typed array methods.
+					if (base.type.builtin_type == Variant::ARRAY && base.type.has_container_element_types() && (call->function_name == SNAME("back") || call->function_name == SNAME("front") || call->function_name == SNAME("get") || call->function_name == SNAME("max") || call->function_name == SNAME("min") || call->function_name == SNAME("pick_random") || call->function_name == SNAME("pop_at") || call->function_name == SNAME("pop_back") || call->function_name == SNAME("pop_front"))) {
```
Comment (Mickeon) [inline modules/gdscript/gdscript_editor.cpp:2037]: For readability each of these "name conditions" could be its own individual line, or at least split in two?

We could also easily(?) have the same logic for just a few methods for typed dictionaries, so worth keeping that in mind for another time.

Comment (HolonProduction) [reply modules/gdscript/gdscript_editor.cpp:2037]: Yeah originally I only wanted to maintain as much functionality as possible, but I used those Array methods to test some assumptions, and figured I could just leave them in. Doing the same for dict would definitely make sense. Also fixing the return type of `get_script` from `Variant` to `Script` here should be possible.

As for splitting the lines, I tried but for some reason my clang format always fixes it back to one line.

File: modules/gdscript/gdscript_editor.cpp (hunk 1 above)
Comment (HolonProduction) [reply modules/gdscript/gdscript_editor.cpp:1774]: Yeah this is a big hack for something that eventually should be solved by structs. I see no point in making a proper system in ClassDB out of this hack. For the few methods we have we can just add a comment at the point were they are bound similar to the "keep enums in sync" comments we have at some places.

I also see no point in making this exhaustive, we can add a handful of very common methods like `intersect_ray`. But beyond that we should just wait for a proper struct based solution.

File: modules/gdscript/gdscript_editor.cpp (hunk 2 above)
Comment (Repiteo) [reply modules/gdscript/gdscript_editor.cpp:2037]: clang-format can be particularly finicky when it comes to multilining conditionals for some reason. I really need to dig into why that is…

File: modules/gdscript/gdscript_editor.cpp (hunk 1 above)
Comment (Mickeon) [reply modules/gdscript/gdscript_editor.cpp:1774]: I for one would love to have it be exhaustive _enough_, and am up for the challenge of filling this list. Great autocompletion does wonders.

**Comment by Repiteo** [comment]
Thanks!

File: modules/gdscript/gdscript_editor.cpp (hunk 2 above)
Comment (Mickeon) [reply modules/gdscript/gdscript_editor.cpp:2037]: Oftentimes the additional lines of the `if` statement need to be indented twice (and I frankly hate it very much it looks terrible)

File: modules/gdscript/gdscript_editor.cpp (hunk 1 above)
Comment (HolonProduction) [reply modules/gdscript/gdscript_editor.cpp:1774]: Feel free to add new entries if you have some methods that come to mind. I just don't want to do an exhaustive search for methods of this kind myself.
