### PR TITLE
Remove font height restriction from Button

### LINKED ISSUE #35005: godot buttons can't be resized to 8×8
**Godot version:**
3.1.2

**OS/device including version:**
windows 10 64 bit

**Issue description:**
I can't shrink buttons below the size 8x16.848
image

**Steps to reproduce:**
- 1 make 24x24 pixel square for the button panel style
- 2 apply the style to all styles in the button except focus use empty style for that.
- 3 enable clip text and clip content
- 4 set the minimum size to 8x8
- 5 try to set the size to 8x8.

**Minimal reproduction project:**
[PocketQuest.zip](https://github.com/godotengine/godot/files/4049012/PocketQuest.zip)

please fix this every time I come back to godot ui I find this is still here.
content should always be resizeable unless the user themselves set a minimum size.

things that should also be looked at..
- anything that restricts the size of the control should be turned off by default
- allowing the user to resize the controls in containers

### PR DESCRIPTION
**Pull request by KoBeWi**
Possible fix #35005
The button height is determined by the text buffer, so additinally using font height is not necessary.
godot windows tools 64_PERzIDkiyp

### CODE REVIEW

**Comment by Calinou** [comment]
How does this behave when the button is within a Container with no custom minimum size set?

**Comment by KoBeWi** [comment]
It shrinks to the stylebox size (the same as show in the GIF). This change only affects buttons without text, so it doesn't break anything in majority of the cases.

**Review by Geometror — COMMENTED** [review]
Seems reasonable to me. However, we have to keep in mind that this has an effect on the editor UI (vertical shrinking), which might require some adjustments. For example, the OptionButton arrow isn't centered anymore in some cases and a few controls which had the same height before now have different heights. Both observable here:
Before: 
grafik
After:
grafik


GIF before/after of whole editor:

**Review by fire-forge — APPROVED** [review]
Not a bad idea. Could be useful for icon-only buttons where the font height is taller than the icon.

File: scene/gui/button.cpp [hunk 1]
```diff
@@ -60,12 +60,6 @@ Size2 Button::get_minimum_size() const {
 			}
 		}
 	}
-
-	Ref<Font> font = get_theme_font(SNAME("font"));
-	float font_height = font->get_height(get_theme_font_size(SNAME("font_size")));
-
-	minsize.height = MAX(font_height, minsize.height);
```
Comment (bruvzg) [inline scene/gui/button.cpp:67]: Maybe change it to use font height, only if `!xl_text.is_empty()`, instead of removing. When there is text, restricting min size to the text height seems reasonable.

Comment (KoBeWi) [reply scene/gui/button.cpp:67]: That's what `Size2 minsize = text_buf->get_size();` already does.

**Comment by KoBeWi** [comment]
@Geometror OptionButton will be handled by #59303, other buttons don't really have this problem.

**Review by Geometror — APPROVED** [review]
I only checked the most common areas, but altough some elements shrink in height (as seen in the GIF) they still look good. There is only one nitpick, the plus icon of the "Add new scene" button in the central tab bar moves up 1 px, making it look a bit off-centered :)
grafik

**Comment by Geometror** [comment]
Just noticed that some Color inspector properties are squished heavily:
Before->after:
grafik

**Comment by KoBeWi** [comment]
Maybe bruvzg's suggestion makes sense actually...

File: scene/gui/button.cpp (hunk 1 above)
Comment (Geometror) [reply scene/gui/button.cpp:67]: They give different results, `text_buf->get_size();` returns the size of that specific string (depends on the characters used) and `font->get_height(get_theme_font_size(SNAME("font_size")));` returns the general (maximum) height of the font.

Comment (bruvzg) [reply scene/gui/button.cpp:67]: It's not the same, text-buffer size is a real text size (depends on context and used fallback fonts), so text will fit, but two adjacent buttons can have a bit different height.

**Comment by YuriSizov** [comment]
> Just noticed that some Color inspector properties are squished heavily: Before->after: grafik

This is actually a good thing and the fix working as intended, IMO. ColorPickerButton shouldn't depend on the height of the font, and we should just adjust its theme properties to give it more initial height to match the UI.

**Comment by Geometror** [comment]
The shrinking is still present (at least in color theme overrides section) but I agree with what @YuriSizov said, this could be fixed by adjusting the ColorPickerButton style/minsize (in this or a subsequent PR).

**Comment by Geometror** [comment]
I think this can be merged. The tweaks needed for the editor UI can be done separately.

**Comment by akien-mga** [comment]
Thanks!
