### PR TITLE
Make build profile project detection also set build options

### LINKED ISSUE #103884: Build Profile "Detect from Project" Causes Error: Mainloop type doesn't exist: SceneTree
### Tested versions

- Reproducible in Godot 4.4.stable

### System information

Godot v4.4.stable - Windows 11 (build 22631) - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 4060 Laptop GPU (NVIDIA; 32.0.15.6636) - AMD Ryzen 7 7735HS with Radeon Graphics (16 threads)

### Issue description

Using "Detect from project" in the engine compilation configuration editor causes the build to crash on launch. I detected from project, saved the `.build` file, then compiled Windows release templates using it. Exporting the MRP with that build makes it crash on launch with this error: "Mainloop type doesn't exist: Scenetree"

Clipboard - March 9, 2025

**This issue doesn't happen when I reset to the default settings then tick off the same nodes/resources manually**. The auto-detected build file is also much bigger, so I suspect it's accidentally disabling something that Godot needs to run.

[build_files.zip](https://github.com/user-attachments/files/19154423/build_files.zip)

### Steps to reproduce

Open up MRP, go to Project>Tools>Engine Compilation Configuration Editor

Click on "Detect from project", then save as a new `.build` file

Try compiling a release template and use it to export the MRP. The build created will fail to launch with the error mentioned above.

### Minimal reproduction project (MRP)

[godot-size-test_2.zip](https://github.com/user-attachments/files/19154431/godot-size-test_2.zip)

### LINKED ISSUE #104586: Clicking "Load" in Engine Compilation Configuration Editor does nothing.
### Tested versions

- Issue found in versions: 4.4stable & 4.3stable
- This tool does not exist in 4.2stable & below.

### System information

Godot v4.4.stable - Windows 11 (build 26100) - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - Quadro RTX 5000 with Max-Q Design - Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 threads)

### Observed Issue:
Loading a `.build` file in the Engine Compilation Configuration Editor tool (found in `Project -> Tools`) simply does nothing & does not load the build file.
Every other option ("New", "Save", & "Save As") work as intended however it is only the load option I am having issues with.
If you edit the `.build` in a text editor you can see the settings are in fact saved in the file & should be valid.

### Expected Behavior:
Upon clicking "Load" it should load the configuration from the selected `.build` file.

### Steps to reproduce

- Open "Project" options at the top of the editor.
- Hover over "Tools" until more options show up.
- Select the "Engine Compilation Configuration Editor" option.
- Remove any of the profile's included classes.
- Click "Save As" to save the `.build` file.
- Click "New" again to reset the selected classes.
- Click "Load" to observe your build profile does not load.

### Minimal reproduction project (MRP)

No project as this is the base Godot editor with no extensions or plugins.

### PR DESCRIPTION
**Pull request by YeldhamDev**
Currently, the build profile editor only updates the used classes when attempting to detect from the project. This PR makes so that the other settings are also updated from the project information with the following.

- Checking project settings.
- Checking classes that require them.
- And last but definitely not least, import settings. This one required me to add an extra functionality called `get_build_dependencies()`, that works like `get_classes_used()` but is geared towards resource importers. And just like the latter, the former is also exposed to scripting.

However, that are a couple of build options that I couldn't find a way to detect, because as far as I'm aware, there are no settings that could imply if the project is using them or not:
- ~X11/Wayland~
- SIL Graphite Fonts

This PR also fixes some issues necessary to make the feature to work properly:
- Fix error when scanning resource files.
- Fix loading profile files doing nothing.
- Hardcode some classes that are necessary for the engine to function.

**Sponsored By:** 🐺 Lone Wolf Technology / 🍀 W4 Games.

### CODE REVIEW

**Comment by YeldhamDev** [comment]
@Riteo Yep, missed that setting. If it's set to `default`, both are now selected, otherwise, it will be the one you picked.

**Comment by YeldhamDev** [comment]
This PR is ready for review.

**Comment by Calinou** [comment]
I get this error when compiling a release export template with a profile generated from the 3D platformer demo:

```
main/main.cpp:188:8: error: unknown type name 'XRServer'
  188 | static XRServer *xr_server = nullptr;
      |        ^
1 error generated.
Compiling modules/gltf/extensions/gltf_document_extension.cpp ...
scons: *** [bin/obj/main/main.macos.template_release.arm64.o] Error 1
scons: building terminated because of errors.
INFO: Time elapsed: 00:00:07.16
```

This doesn't occur with a profile generated from `master`.

Profile files: [build_profiles.zip](https://github.com/user-attachments/files/19590759/build_profiles.zip)

SCons command:

```
scons -j16 progress=no target=template_release optimize=speed build_profile=path/to/profile.gdbuild
```

**Comment by YeldhamDev** [comment]
@Calinou Try again, please. Seem that it was just a missing `#ifndef`.

**Comment by akien-mga** [comment]
> I get this error on macOS when compiling a release export template with a profile generated from the [3D platformer demo](https://github.com/godotengine/godot-demo-projects/tree/master/3d/platformer):
> 
> ```
> main/main.cpp:188:8: error: unknown type name 'XRServer'
>   188 | static XRServer *xr_server = nullptr;
>       |        ^
> 1 error generated.
> Compiling modules/gltf/extensions/gltf_document_extension.cpp ...
> scons: *** [bin/obj/main/main.macos.template_release.arm64.o] Error 1
> scons: building terminated because of errors.
> INFO: Time elapsed: 00:00:07.16
> ```

This is being fixed in #104978.

**Comment by Calinou** [comment]
I'm getting a different build error after rebasing on top on `master` on Linux:

```
Compiling scene/resources/scu/scu_scene_resources_4.gen.cpp ...
In file included from editor/scu/scu_editor_2.gen.cpp:2:
./editor/editor_build_profile.cpp: In member function 'void EditorBuildProfileManager::_detect_from_project()':
./editor/editor_build_profile.cpp:917:62: error: cannot convert 'List<StringName>*' to 'LocalVector<StringName>&'
  917 |                 ClassDB::get_inheriters_from_class(hc_class, &inheriters);
      |                                                              ^~~~~~~~~~~
      |                                                              |
      |                                                              List<StringName>*
In file included from ./core/object/ref_counted.h:33,
                 from ./core/object/script_instance.h:33,
                 from ./core/object/gdvirtual.gen.inc:4,
                 from ./scene/gui/control.h:34,
                 from ./scene/gui/container.h:33,
                 from ./scene/gui/box_container.h:33,
                 from ./editor/editor_autoload_settings.h:33,
                 from ./editor/editor_autoload_settings.cpp:31,
                 from editor/scu/scu_editor_2.gen.cpp:1:
./core/object/class_db.h:314:99: note:   initializing argument 2 of 'static void ClassDB::get_inheriters_from_class(const StringName&, LocalVector<StringName>&)'
  314 |         static void get_inheriters_from_class(const StringName &p_class, LocalVector<StringName> &p_classes);
      |                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
scons: *** [bin/obj/editor/scu/scu_editor_2.gen.linuxbsd.editor.x86_64.o] Error 1
```

**Comment by YeldhamDev** [comment]
@Calinou Alright, the problem was that class extraction from binary resources was broken (like almost everything about this feature before this PR. :melting_face:). I have now fixed it, please try again.

**Comment by Calinou** [comment]
> That's not right, it manages to find `GridMap` on my end. Are you deleting the cache before re-detecting?

It works after removing `.godot/` :slightly_smiling_face:
The project works just fine with the custom build profile now.

These messages are still printed on startup though:

```
WARNING: Property not found: 'editor/movie_writer/mix_rate'.
     at: get_setting_with_override (core/config/project_settings.cpp:405)
WARNING: Property not found: 'editor/movie_writer/speaker_mode'.
     at: get_setting_with_override (core/config/project_settings.cpp:405)
WARNING: Property not found: 'editor/movie_writer/mjpeg_quality'.
     at: get_setting_with_override (core/config/project_settings.cpp:405)
```

**Review by Calinou — APPROVED** [review]
Works great now!

File: editor/editor_build_profile.cpp [hunk 1]
```diff
@@ -210,16 +474,38 @@ String EditorBuildProfile::get_build_option_description(BuildOption p_build_opti
...
+	return build_option_identifiers[p_build_option];
+}
+
 EditorBuildProfile::BuildOptionCategory EditorBuildProfile::get_build_option_category(BuildOption p_build_option) {
 	ERR_FAIL_INDEX_V(p_build_option, BUILD_OPTION_MAX, BUILD_OPTION_CATEGORY_GENERAL);
 	return build_option_category[p_build_option];
 }
 
+LocalVector<EditorBuildProfile::BuildOption> EditorBuildProfile::get_build_option_dependencies(BuildOption p_build_option) {
+	ERR_FAIL_INDEX_V(p_build_option, BUILD_OPTION_MAX, {});
```
Comment (AThousandShips) [inline editor/editor_build_profile.cpp:488]:
```suggestion
	ERR_FAIL_INDEX_V(p_build_option, BUILD_OPTION_MAX, LocalVector<EditorBuildProfile::BuildOption>());
```
Please be explicit about return types

File: editor/editor_build_profile.cpp [hunk 2]
```diff
@@ -210,16 +474,38 @@ String EditorBuildProfile::get_build_option_description(BuildOption p_build_opti
...
+	return build_option_dependencies.has(p_build_option) ? build_option_dependencies[p_build_option] : LocalVector<EditorBuildProfile::BuildOption>();
+}
+
+HashMap<String, LocalVector<Variant>> EditorBuildProfile::get_build_option_settings(BuildOption p_build_option) {
+	ERR_FAIL_INDEX_V(p_build_option, BUILD_OPTION_MAX, {});
```
Comment (AThousandShips) [inline editor/editor_build_profile.cpp:493]:
```suggestion
	ERR_FAIL_INDEX_V(p_build_option, BUILD_OPTION_MAX, HashMap<String, LocalVector<Variant>>());
```

File: editor/editor_build_profile.cpp [hunk 3]
```diff
@@ -210,16 +474,38 @@ String EditorBuildProfile::get_build_option_description(BuildOption p_build_opti
...
+	return build_option_settings.has(p_build_option) ? build_option_settings[p_build_option] : HashMap<String, LocalVector<Variant>>();
+}
+
+LocalVector<String> EditorBuildProfile::get_build_option_classes(BuildOption p_build_option) {
+	ERR_FAIL_INDEX_V(p_build_option, BUILD_OPTION_MAX, {});
```
Comment (AThousandShips) [inline editor/editor_build_profile.cpp:498]:
```suggestion
	ERR_FAIL_INDEX_V(p_build_option, BUILD_OPTION_MAX, LocalVector<String>());
```

**Review by AThousandShips — APPROVED** [review]

**Comment by YeldhamDev** [comment]
@Calinou The PR has been updated with the following:
- Improved the extraction of classes from binary scene files. This removes the need for `Skin` to be hardcoded.
- Added `ADD_CLASS_DEPENDENCY()`. This is used inside `_bind_methods()` so classes can mark if they depend on other classes being registered. This fixes the error with `TabBar`.
- Removed the logic to toggle advanced GUI in the build profile, [as stated by Akien](https://github.com/godotengine/godot/pull/103291#issuecomment-2788794427), that was made before this feature existed, and it's kinda redundant now.

@AThousandShips Changes made.

**Comment by Calinou** [comment]
Tested again, it works as expected. The Control Gallery demo now generates the profile correctly.

I get a warning when running the demo with a compiled export template that uses the profile:

```
WARNING: Property not found: 'gui/common/default_scroll_deadzone'.
     at: get_setting_with_override (core/config/project_settings.cpp:404)
```

While rebasing on `master`, to account for the conflict generated by https://github.com/godotengine/godot/commit/55dd5d59e1fd98b0a7904a01cf6c73214556310e, I chose to kept current changes only (i.e. what's in `master`). It performs the check slightly differently, since it checks each MovieWriter individually (which makes more sense to me). It seems to work fine.

**Comment by akien-mga** [comment]
I tested the PR on the 2D platformer demo: https://github.com/godotengine/godot-demo-projects/tree/master/2d/platformer

The auto-detection works relatively well, but the `Window` class is wrongly disabled, so the one script fails parsing:
```
SCRIPT ERROR: Parse Error: Native class Window used in script doesn't exist or isn't exposed. [tmp_js_export.js:477:18](http://localhost:8060/tmp_js_export.js)
   at: GDScript::reload (res://game.gd:16)
```

Since the root node is of type `Window`, I believe Window should never be disabled?

Surprisingly, with Window disabled, the 2D platformer demo does work fine though. Only the functionality from the Game script (fullscreen and pause toggles) is broken.

File: editor/editor_build_profile.cpp [hunk 4]
```diff
@@ -40,34 +41,58 @@
...
 };
 
 const bool EditorBuildProfile::build_option_disabled_by_default[BUILD_OPTION_MAX] = {
 	// This maps to SCons build options.
 	false, // 3D
-	false, // PHYSICS_2D
-	false, // PHYSICS_3D
-	false, // NAVIGATION
+	false, // NAVIGATION 2D
+	false, // NAVIGATION 3D
```
Comment (akien-mga) [inline editor/editor_build_profile.cpp:79]: This is meant to be the suffix after `BUILD_OPTION_` so it should use underscores (same for other occurrences).

```suggestion
	false, // NAVIGATION_2D
	false, // NAVIGATION_3D
```

File: editor/editor_build_profile.cpp [hunk 5]
```diff
@@ -40,34 +41,58 @@
...
+	false, // D3D12
+	false, // METAL
+	false, // OPENGL
+	false, // PHYSICS_2D
+	false, // PHYSICS_GODOT_2D
+	false, // PHYSICS_3D
+	false, // PHYSICS_GODOT_3D
+	false, // PHYSICS_JOLT
 	true, // TEXT_SERVER_FALLBACK
 	false, // TEXT_SERVER_COMPLEX
```
Comment (akien-mga) [inline editor/editor_build_profile.cpp:97]:
```suggestion
	false, // TEXT_SERVER_ADVANCED
```

File: editor/editor_build_profile.cpp [hunk 6]
```diff
@@ -79,38 +104,215 @@ const bool EditorBuildProfile::build_option_disabled_by_default[BUILD_OPTION_MAX
...
+	false, // METAL
+	false, // OPENGL
+	true, // PHYSICS_2D
+	false, // PHYSICS_GODOT_2D
+	true, // PHYSICS_3D
+	false, // PHYSICS_GODOT_3D
+	false, // PHYSICS_JOLT
 	false, // TEXT_SERVER_FALLBACK
-	false, // TEXT_SERVER_COMPLEX
+	false, // BUILD_OPTION_TEXT_SERVER_ADVANCED
```
Comment (akien-mga) [inline editor/editor_build_profile.cpp:126]: `BUILD_OPTION_` is implicit in these comments. (Same for other occurrences.)
```suggestion
	false, // TEXT_SERVER_ADVANCED
```

File: editor/editor_build_profile.cpp [hunk 7]
```diff
@@ -79,38 +104,215 @@ const bool EditorBuildProfile::build_option_disabled_by_default[BUILD_OPTION_MAX
...
+			"XRVRS",
+			"XRBodyTracker",
+			"XRControllerTracker",
+			"XRFaceTracker",
+			"XRHandTracker",
+			"XRInterfaceExtension",
+			"XRPose",
+			"XRPositionalTracker",
+			"XRServer",
+			"XRTracker",
```
Comment (akien-mga) [inline editor/editor_build_profile.cpp:272]: Should those be ordered alphabetically so it's easier to review?

File: editor/editor_build_profile.cpp [hunk 8]
```diff
@@ -79,38 +104,215 @@ const bool EditorBuildProfile::build_option_disabled_by_default[BUILD_OPTION_MAX
...
+			"PhysicsServer3DRenderingServerHandler",
+			"RayCast3D",
+			"SoftBody3D",
+			"SpringArm3D",
+			"SpringBoneCollision3D",
+			"SpringBoneSimulator3D",
+			"VehicleWheel3D",
+	} },
+	{ BUILD_OPTION_TEXT_SERVER_ADVANCED, {
+			"Control",
```
Comment (akien-mga) [inline editor/editor_build_profile.cpp:308]: Does this mean Control is removed if you disable TextServerAdvanced? That seems wrong.

File: editor/editor_build_profile.cpp [hunk 9]
```diff
@@ -79,38 +104,215 @@ const bool EditorBuildProfile::build_option_disabled_by_default[BUILD_OPTION_MAX
...
+			"XRFaceModifier3D",
+			"XRNode3D",
+			"XROrigin3D",
+			"XRInterface",
+			"XRVRS",
+			"XRBodyTracker",
+			"XRControllerTracker",
+			"XRFaceTracker",
+			"XRHandTracker",
+			"XRInterfaceExtension",
```
Comment (akien-mga) [inline editor/editor_build_profile.cpp:268]: Why do we need to list all these explicitly? Don't the SCons options amount to just disabling all these nodes?

File: editor/editor_build_profile.cpp [hunk 10]
```diff
@@ -79,38 +104,215 @@ const bool EditorBuildProfile::build_option_disabled_by_default[BUILD_OPTION_MAX
...
-	BUILD_OPTION_CATEGORY_GENERAL, // NAVIGATION
+	BUILD_OPTION_CATEGORY_GENERAL, // NAVIGATION 2D
+	BUILD_OPTION_CATEGORY_GENERAL, // NAVIGATION 3D
 	BUILD_OPTION_CATEGORY_GENERAL, // XR
-	BUILD_OPTION_CATEGORY_GENERAL, // RENDERING_DEVICE
-	BUILD_OPTION_CATEGORY_GENERAL, // OPENGL
-	BUILD_OPTION_CATEGORY_GENERAL, // VULKAN
+	BUILD_OPTION_CATEGORY_GENERAL, // OPENXR
+	BUILD_OPTION_CATEGORY_GENERAL, // WAYLAND
+	BUILD_OPTION_CATEGORY_GENERAL, // X11
```
Comment (akien-mga) [inline editor/editor_build_profile.cpp:169]: These could maybe go in a "Platform" category.

File: editor/editor_build_profile.cpp [hunk 11]
```diff
@@ -192,13 +416,24 @@ String EditorBuildProfile::get_build_option_description(BuildOption p_build_opti
...
 		TTRC("XR (AR and VR)."),
+		TTRC("OpenXR standard implementation (requires XR to be enabled)."),
+		TTRC("Wayland display (Linux only)."),
+		TTRC("X11 display (Linux only)."),
 		TTRC("RenderingDevice based rendering (if disabled, the OpenGL back-end is required)."),
-		TTRC("OpenGL back-end (if disabled, the RenderingDevice back-end is required)."),
+		TTRC("Forward+ renderer for advanced 3D graphics."),
+		TTRC("Mobile renderer for less advanced 3D graphics."),
 		TTRC("Vulkan back-end of RenderingDevice."),
+		TTRC("Direct3D 12 back-end of RenderingDevice."),
```
Comment (akien-mga) [inline editor/editor_build_profile.cpp:429]: This is the only file that uses "back-end" with a hyphen. I'd suggest streamlining it to "backend" which seems more common, since we're changing those strings.

File: editor/editor_build_profile.cpp [hunk 12]
```diff
@@ -79,38 +104,215 @@ const bool EditorBuildProfile::build_option_disabled_by_default[BUILD_OPTION_MAX
...
+	} },
+	{ BUILD_OPTION_PHYSICS_GODOT_3D, {
+			BUILD_OPTION_PHYSICS_3D,
+	} },
+	{ BUILD_OPTION_PHYSICS_JOLT, {
+			BUILD_OPTION_PHYSICS_3D,
+	} },
+	{ BUILD_OPTION_DYNAMIC_FONTS, {
+			BUILD_OPTION_TEXT_SERVER_ADVANCED,
+	} },
```
Comment (akien-mga) [inline editor/editor_build_profile.cpp:228]: Is this dependency correct? I think you can use TTF/OTF dynamic fonts with TextServerFallback.

CC @bruvzg

File: editor/editor_build_profile.cpp [hunk 13]
```diff
@@ -405,7 +737,11 @@ void EditorBuildProfileManager::_profile_action(int p_action) {
 			confirm_dialog->popup_centered();
 		} break;
 		case ACTION_DETECT: {
-			confirm_dialog->set_text(TTR("This will scan all files in the current project to detect used classes."));
+			String text = TTR("This will scan all files in the current project to detect used classes.\nNote that the first scan may take a while, specially in larger projects.");
+#ifdef MODULE_MONO_ENABLED
+			text += "\n\n" + TTR("Warning: Class detection for C# scripts is not currently available, and such files will be ignored.");
+#endif // MODULE_MONO_ENABLED
```
Comment (akien-mga) [inline editor/editor_build_profile.cpp:743]: FYI @godotengine/dotnet - would be good to implement as a follow-up.

File: scene/gui/color_picker.cpp [hunk 14]
```diff
@@ -1993,6 +1993,10 @@ void ColorPicker::_bind_methods() {
 	BIND_THEME_ITEM_EXT(Theme::DATA_TYPE_STYLEBOX, ColorPicker, mode_button_normal, "tab_unselected", "TabContainer");
 	BIND_THEME_ITEM_EXT(Theme::DATA_TYPE_STYLEBOX, ColorPicker, mode_button_pressed, "tab_selected", "TabContainer");
 	BIND_THEME_ITEM_EXT(Theme::DATA_TYPE_STYLEBOX, ColorPicker, mode_button_hover, "tab_selected", "TabContainer");
+
+	ADD_CLASS_DEPENDENCY("LineEdit");
+	ADD_CLASS_DEPENDENCY("MenuButton");
+	ADD_CLASS_DEPENDENCY("PopupMenu");
```
Comment (akien-mga) [inline scene/gui/color_picker.cpp:1999]: How do you determine which classes should be added as dependencies?

I see `color_picker.cpp` has an internal LineEdit but there's also e.g. SpinBox, HSlider, etc.

Is this a requirement only when signals are used?

**Review by akien-mga — COMMENTED** [review]
Did a code review pass, looks pretty good overall.

Let's finalize this and get it merged :D

File: editor/editor_build_profile.cpp (hunk 9 above)
Comment (YeldhamDev) [reply editor/editor_build_profile.cpp]: Because we need to know when any of those are being used to decide if certain features should be disabled or not. For example, even if all nodes related to 2D navigation are disabled, the 2D server for navigation is still compiled unless we tell it otherwise.

File: editor/editor_build_profile.cpp (hunk 10 above)
Comment (YeldhamDev) [reply editor/editor_build_profile.cpp:170]: I don't think two items are enough to warrant a new category.

File: editor/editor_build_profile.cpp (hunk 13 above)
Comment (YeldhamDev) [reply editor/editor_build_profile.cpp:744]: Oh believe me, I tried, and it's currently not possible in a way that makes it worth it. You can ask @raulsntos for more details.

File: scene/gui/color_picker.cpp (hunk 14 above)
Comment (YeldhamDev) [reply scene/gui/color_picker.cpp:1999]: > Is this a requirement only when signals are used?

Seems so, as connecting signals require the class to be registered.

File: editor/editor_build_profile.cpp (hunk 12 above)
Comment (Calinou) [reply editor/editor_build_profile.cpp:229]: Yes, TextServerFallback supports all font file formats that TextServerAdvanced does.

Comment (bruvzg) [reply editor/editor_build_profile.cpp:229]: The opposite is also true, `TextServerAdvanced` can support RTL/BiDi with bitmap fonts. So it might be something like `BUILD_OPTION_COMPLEX_TEXT_LAYOUTS`, but not dynamic fonts.

File: editor/editor_build_profile.cpp (hunk 6 above)
Comment (akien-mga) [reply editor/editor_build_profile.cpp:127]: You missed this one.

File: editor/editor_build_profile.cpp (hunk 10 above)
Comment (akien-mga) [reply editor/editor_build_profile.cpp:170]: For now maybe not, but in the future we might want to expose more options.

E.g. for Linux:
```
        BoolVariable("alsa", "Use ALSA", True),
        BoolVariable("pulseaudio", "Use PulseAudio", True),
        BoolVariable("dbus", "Use D-Bus to handle screensaver and portal desktop settings", True),
        BoolVariable("speechd", "Use Speech Dispatcher for Text-to-Speech support", True),
        BoolVariable("fontconfig", "Use fontconfig for system fonts support", True),
        BoolVariable("udev", "Use udev for gamepad connection callbacks", True),
        BoolVariable("x11", "Enable X11 display", True),
        BoolVariable("wayland", "Enable Wayland display", True),
        BoolVariable("libdecor", "Enable libdecor support", True),
        BoolVariable("touch", "Enable touch events", True),
```
Most of those likely don't have a significant impact on binary size though.

So I guess we can keep it as is for now and revisit later if we add more platform-specific options.

File: scene/gui/color_picker.cpp (hunk 14 above)
Comment (akien-mga) [reply scene/gui/color_picker.cpp:1999]: FYI @KoBeWi. I wonder if we could find a more elegant way to do this so we don't need to hardcode such list only for internal classes that have signal connections.

It's fine for now for this PR though.

File: servers/register_server_types.cpp [hunk 15]
```diff
@@ -364,12 +363,14 @@ void unregister_server_types() {
...
 	ServersDebugger::deinitialize();
 	memdelete(shader_types);
+
 	if (GD_IS_CLASS_ENABLED(MovieWriterMJPEG)) {
 		memdelete(writer_mjpeg);
 	}
 	if (GD_IS_CLASS_ENABLED(MovieWriterPNGWAV)) {
 		memdelete(writer_pngwav);
 	}
+
```
Comment (akien-mga) [inline servers/register_server_types.cpp:373]: There's only whitespace changes in this file in the end so this can be reverted.

That should also prevent conflicts with #106013 (which could use an approval btw :wink: ).

**Review by akien-mga — APPROVED** [review]
Looks great to me!
The configuration system isn't perfect yet but this is much better than what was before, and we can build upon it.

I have a couple minor outstanding comments but this should be good to merge soon.

File: scene/resources/resource_format_text.cpp [hunk 16]
```diff
@@ -1223,15 +1223,10 @@ Error ResourceLoaderText::get_classes_used(HashSet<StringName> *r_classes) {
 			return error;
 		}
 
-		if (!next_tag.fields.has("type")) {
-			error = ERR_FILE_CORRUPT;
-			error_text = "Missing 'type' in external resource tag";
-			_printerr();
-			return error;
+		if (next_tag.fields.has("type")) {
+			r_classes->insert(next_tag.fields["type"]);
```
[the remark this answers is not in the document]
Comment (YeldhamDev) [reply scene/resources/resource_format_text.cpp:1227]: Yes, instanced scenes.

File: core/io/resource_importer.cpp [hunk 17]
```diff
@@ -456,6 +457,18 @@ void ResourceFormatImporter::get_dependencies(const String &p_path, List<String>
...
 
+void ResourceFormatImporter::get_build_dependencies(const String &p_path, HashSet<String> *r_dependencies) {
+	if (!exists(p_path)) {
+		return;
+	}
+
+	List<Ref<ResourceImporter>> valid_importers;
+	get_importers_for_file(p_path, &valid_importers);
+	for (Ref<ResourceImporter> importer : valid_importers) {
+		return importer->get_build_dependencies(p_path, r_dependencies);
```
Comment (Repiteo) [inline core/io/resource_importer.cpp]: MSVC gives a warning for unreachable code here, but the fact this is returning at all seems like a relic of a previous iteration. I assume this is instead meant to be:
```suggestion
		importer->get_build_dependencies(p_path, r_dependencies);
```

Comment (YeldhamDev) [reply core/io/resource_importer.cpp]: Good catch, fixed.

**Comment by Repiteo** [comment]
Thanks!
