### PR TITLE
Fix some overflows and unitialized variables

### LINKED ISSUE #33240: GCC 9: error: '<anonymous>.ShaderGLES2::Version::frag_id' is used uninitialized in this function [-Werror=uninitialized]
**Godot version:**

ce352ce5b4f0e4718ba3ecd1b12d59854b617182

**OS/device including version:**

**Issue description:**

I see a compilation warning with GCC 9:
```
$ scons progress=yes verbose=yes -j1 platform=x11 tools=no   target=release_debug warnings=extra use_lto=0 werror=1
...
[ 65%] g++ -o drivers/gles2/shader_gles2.x11.opt.debug.64.o -c -std=c++11 -Wctor-dtor-privacy -Wnon-virtual-dtor -Wnoexcept -Wplacement-new=1 -g1 -O2 -pipe -fpie -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wshadow-local -Walloc-zero -Wduplicated-branches -Wduplicated-cond -Wstringop-overflow=4 -Wlogical-op -Wattribute-alias=2 -Werror -DDEBUG_ENABLED -DTOUCH_ENABLED -DALSA_ENABLED -DALSAMIDI_ENABLED -DPULSEAUDIO_ENABLED -D_REENTRANT -DJOYDEV_ENABLED -DX11_ENABLED -DUNIX_ENABLED -DOPENGL_ENABLED -DGLES_ENABLED -DPTRCALL_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DFREETYPE_ENABLED -DSVG_ENABLED -DHAVE_MNTENT -Ithirdparty/nanosvg -Ithirdparty/freetype/include -Ithirdparty/libpng -Ithirdparty/glad -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/x11 -I. drivers/gles2/shader_gles2.cpp

In file included from drivers/gles2/shader_gles2.cpp:31:
drivers/gles2/shader_gles2.h: In member function 'HashMap<TKey, TData, Hasher, Comparator, MIN_HASH_TABLE_POWER, RELATIONSHIP>::Element* HashMap<TKey, TData, Hasher, Comparator, MIN_HASH_TABLE_POWER, RELATIONSHIP>::create_element(const TKey&) [with TKey = ShaderGLES2::VersionKey; TData = ShaderGLES2::Version; Hasher = ShaderGLES2::VersionKeyHash; Comparator = HashMapComparatorDefault<ShaderGLES2::VersionKey>; unsigned char MIN_HASH_TABLE_POWER = 3; unsigned char RELATIONSHIP = 8]':
drivers/gles2/shader_gles2.h:110:9: error: '<anonymous>.ShaderGLES2::Version::frag_id' is used uninitialized in this function [-Werror=uninitialized]
  110 |  struct Version {
      |         ^~~~~~~
drivers/gles2/shader_gles2.h:110:9: error: '<anonymous>' is used uninitialized in this function [-Werror=uninitialized]
cc1plus: all warnings being treated as errors
scons: *** [drivers/gles2/shader_gles2.x11.opt.debug.64.o] Error 1
scons: building terminated because of errors.
```

**Steps to reproduce:**
The issue started with the mentioned revision. One can see it here:
https://travis-ci.org/godotengine/godot/jobs/606026116?utm_medium=notification&utm_source=github_status

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by qarmin**
Fixes #33240

Fixes also warnings showed by undefined behavior sanitizer like division by zero, unitialized variables and loss value conversions
```
scene/gui/range.cpp:188:10: runtime error: division by zero
editor/script_editor_debugger.cpp:1933:9: runtime error: load of value 3200171710, which is not a valid value for type 'ScriptEditorDebugger::CameraOverride'
scene/resources/texture.cpp:2588:15: runtime error: load of value 100, which is not a valid value for type 'CameraServer::FeedImage'
editor/editor_sectioned_inspector.cpp:311:7: runtime error: implicit conversion from type 'int' of value -1 (32-bit, signed) to type 'ObjectID' (aka 'unsigned long') changed the value to 18446744073709551615 (64-bit, unsigned)
core/ustring.cpp:1419:17: runtime error: implicit conversion from type 'char' of value -60 (8-bit, signed) to type 'uint8_t' (aka 'unsigned char') changed the value to 196 (8-bit, unsigned)
scene/2d/tile_map.cpp:1236:15: runtime error: implicit conversion from type 'uint16_t' (aka 'unsigned short') of value 65129 (16-bit, unsigned) to type 'int16_t' (aka 'short') changed the value to -407 (16-bit, signed)
core/variant.cpp:2690:11: runtime error: implicit conversion from type 'int64_t' (aka 'long') of value -1 (64-bit, signed) to type 'uint32_t' (aka 'unsigned int') changed the value to 4294967295 (32-bit, unsigned)
scene/resources/audio_stream_sample.cpp:98:15: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'uint32_t' (aka 'unsigned int')
scene/resources/audio_stream_sample.cpp:475:20: runtime error: division by zero
core/math/camera_matrix.cpp:187:24: runtime error: division by zero
core/math/camera_matrix.cpp:188:24: runtime error: division by zero
core/math/camera_matrix.cpp:190:32: runtime error: division by zero
core/math/camera_matrix.cpp:191:32: runtime error: division by zero
core/math/camera_matrix.cpp:192:31: runtime error: division by zero
core/math/camera_matrix.cpp:193:33: runtime error: division by zero
```
and this leak
```
Direct leak of 104 byte(s) in 1 object(s) allocated from:
    #0 0x7f7f9be78ae8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dae8)
    #1 0x9c332bd in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:85
    #2 0x9c331bc in operator new(unsigned long, char const*) core/os/memory.cpp:42
    #3 0x9eb5781 in PackedSourcePCK::get_file(String const&, PackedData::PackedFile*) core/io/file_access_pack.cpp:220
    #4 0x9b64ea9 in PackedData::try_open_path(String const&) core/io/file_access_pack.h:187
    #5 0x9b5768d in FileAccess::open(String const&, int, Error*) core/os/file_access.cpp:100
    #6 0x9764db3 in ProjectSettings::_load_settings_binary(String const&) core/project_settings.cpp:493
    #7 0x97691c1 in ProjectSettings::_load_settings_text_or_binary(String const&, String const&) core/project_settings.cpp:606
    #8 0x9760b60 in ProjectSettings::_setup(String const&, String const&, bool) core/project_settings.cpp:392
    #9 0x9764335 in ProjectSettings::setup(String const&, String const&, bool) core/project_settings.cpp:467
    #10 0x1098c89 in Main::setup(char const*, int, char**, bool) main/main.cpp:825
    #11 0xf3e2ee in main platform/x11/godot_x11.cpp:49
    #12 0x7f7f9a9541e2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x271e2)
```

### CODE REVIEW

File: core/image.cpp [hunk 1]
```diff
@@ -2521,6 +2521,10 @@ void Image::set_pixel(int p_x, int p_y, const Color &p_color) {
 	ERR_FAIL_INDEX(p_x, width);
 	ERR_FAIL_INDEX(p_y, height);
 
+	ERR_FAIL_COND(Math::is_nan(p_color.r * 255.0));
+	ERR_FAIL_COND(Math::is_nan(p_color.g * 255.0));
+	ERR_FAIL_COND(Math::is_nan(p_color.b * 255.0));
+	ERR_FAIL_COND(Math::is_nan(p_color.a * 255.0));
```
Comment (akien-mga) [inline core/image.cpp]: Is there any situation where `x * 255.0` will be NaN if `x` is not NaN itself? If not, we could spare ourselves the multiplication.

I'm also not sure why we need to do this here. There are tons of methods taking floats as input and making operations with them, we can't possibly add NaN checks everywhere, we'd get 5 FPS in the editor...

File: core/io/packet_peer.cpp [hunk 2]
```diff
@@ -281,7 +281,7 @@ void PacketPeerStream::set_input_buffer_max_size(int p_max_size) {
 
 	//warning may lose packets
 	ERR_FAIL_COND_MSG(ring_buffer.data_left(), "Buffer in use, resizing would cause loss of data.");
-	ring_buffer.resize(nearest_shift(p_max_size + 4));
+	ring_buffer.resize(nearest_shift((p_max_size < 0 ? 0 : p_max_size) + 4));
```
Comment (akien-mga) [inline core/io/packet_peer.cpp]: I don't think negative `p_max_size` is meant to be supported. So it should be an `ERR_FAIL_COND` IMO, not a hack at the end location where the warning is raised. @Faless

File: core/project_settings.cpp [hunk 3]
```diff
@@ -525,6 +525,8 @@ Error ProjectSettings::_load_settings_binary(const String &p_path) {
 		set(key, value);
 	}
 
+	f->close();
```
Comment (akien-mga) [inline core/project_settings.cpp]: Do we really need to `close` before `memdelete`? Because if so there are tons of locations where this is not done currently and we just `memdelete(f)`.

File: core/variant.cpp [hunk 4]
```diff
@@ -2687,7 +2689,7 @@ uint32_t Variant::hash() const {
 		} break;
 		case INT: {
 
-			return _data._int;
+			return _data._int >= 0 ? _data._int : UINT32_MAX + _data._int;
```
Comment (akien-mga) [inline core/variant.cpp]: I'm not sure this is a good idea.
While it was previously a bug, this custom handling now makes it a feature that several numbers have the same hash (and since `Variant::_data._int` is an `int64_t`, there should actually be a lot of them).

It's probably better to use `hash_one_uint64` instead, though it might break compatibility.

File: drivers/png/image_loader_png.cpp [hunk 5]
```diff
@@ -64,7 +65,7 @@ Ref<Image> ImageLoaderPNG::load_mem_png(const uint8_t *p_png, int p_size) {
 	Ref<Image> img;
 	img.instance();
 
-	Error err = PNGDriverCommon::png_to_image(p_png, p_size, img);
+	Error err = PNGDriverCommon::png_to_image(p_png, p_size == -1 ? (sizeof(size_t) == 4 ? INT32_MAX : INT64_MAX) : p_size, img);
```
Comment (akien-mga) [inline drivers/png/image_loader_png.cpp]: Again, overflowing the integer size is NOT a feature we use (at least not in such obvious case), we shouldn't make code that does it explicitly to silence a warning pointing us to an actual bug.

`p_size` should be unsigned, and `lossless_unpack_png` should be fixed so that it can't pass a negative size (which should already be the case BTW since it errors if `len < 4` and it passes `len - 4`, so I'm not sure what we're fixing here.

File: editor/editor_sectioned_inspector.cpp [hunk 6]
```diff
@@ -308,7 +311,7 @@ EditorInspector *SectionedInspector::get_inspector() {
 }
 
 SectionedInspector::SectionedInspector() :
-		obj(-1),
+		obj(UINT64_MAX),
```
Comment (akien-mga) [inline editor/editor_sectioned_inspector.cpp]: No... That's obviously not what the code expects.

Comment (akien-mga) [reply editor/editor_sectioned_inspector.cpp]: `core/object.cpp` seems to use 0 as the invalid valid for ObjectID, so this should be used here too (and in the other code assigning `-1` to `obj` when not editing an object.

File: scene/gui/range.cpp [hunk 7]
```diff
@@ -183,6 +183,8 @@ double Range::get_as_ratio() const {
 		return CLAMP((v - exp_min) / (exp_max - exp_min), 0, 1);
 
 	} else {
+		if (Math::is_zero_approx(get_max() - get_min()))
```
Comment (akien-mga) [inline scene/gui/range.cpp]: You can use `is_equal_approx(get_max(), get_min())` instead.

Comment (akien-mga) [reply scene/gui/range.cpp]: There's the same problem in the previous branch a priori. IMO it would be worth simply throwing an error if min == max.

File: core/image.cpp (hunk 1 above)
Comment (aaronfranke) [reply core/image.cpp]: There is none. The only values for `x` in the expression `x * 255.0` that produce `NaN` is `NaN` itself. https://en.wikipedia.org/wiki/NaN#Operations_generating_NaN

File: core/variant.cpp (hunk 4 above)
Comment (qarmin) [reply core/variant.cpp]: I totally forgot that _int in this situation is 64 bit instead 32 bit, so this is wrong.

File: core/image.cpp (hunk 1 above)
Comment (qarmin) [reply core/image.cpp]: I just added this, because I got this error:
```
core/image.cpp:2552:31: runtime error: -nan is outside the range of representable values of type 'unsigned char'
```
I will try to find cause of existing of Nan in this variables to prevent this checks.

File: drivers/gles2/rasterizer_canvas_gles2.cpp [hunk 8]
```diff
@@ -749,6 +749,10 @@ void RasterizerCanvasGLES2::_canvas_item_render_commands(Item *p_item, Item *cur
 					WARN_PRINT("NinePatch without texture not supported yet in GLES2 backend, skipping.");
 					continue;
 				}
+				if (tex->width == 0 || tex->height == 0) {
+					WARN_PRINT("Cannot set empty texture to NinePatch");
```
Comment (akien-mga) [inline drivers/gles2/rasterizer_canvas_gles2.cpp]: Sentence should end with a dot.

File: editor/editor_sectioned_inspector.cpp [hunk 9]
```diff
@@ -308,7 +308,7 @@ EditorInspector *SectionedInspector::get_inspector() {
 }
 
 SectionedInspector::SectionedInspector() :
-		obj(-1),
+		obj(0),
```
Comment (akien-mga) [inline editor/editor_sectioned_inspector.cpp]: As I mentioned in the previous comment, there's another line with `obj = -1` in this file.

File: scene/gui/range.cpp [hunk 10]
```diff
@@ -184,6 +184,8 @@ double Range::get_as_ratio() const {
 
 	} else {
 
+		ERR_FAIL_COND_V_MSG(Math::is_equal_approx(get_max(), get_min()), 0.0, "Cannot get ratio when minimum and maximum value are equal.");
```
Comment (akien-mga) [inline scene/gui/range.cpp]: As mentioned in my previous comment, the same problem happens in the previous branch if `get_min()` and `get_max()` are equal and non 0.

File: core/variant.cpp [hunk 11]
```diff
@@ -2687,7 +2687,7 @@ uint32_t Variant::hash() const {
 		} break;
 		case INT: {
 
-			return _data._int;
+			return hash_one_uint64(uint64_t(_data._int));
```
Comment (akien-mga) [inline core/variant.cpp]: I'd prefer this move to a dedicated PR, as I fear it's breaking compatibility. The other changes can be merged for 3.2, but this one I doubt.

File: drivers/png/image_loader_png.cpp (hunk 5 above)
Comment (akien-mga) [reply drivers/png/image_loader_png.cpp]: Just do something like:
```
ERR_FAIL_COND_V_MSG(p_size < 0, Ref<Image>, "Cannot convert PNG to Image resource with a negative size.");
```

File: core/variant.cpp (hunk 11 above)
Comment (aaronfranke) [reply core/variant.cpp]: See also: https://github.com/godotengine/godot/issues/33581

File: drivers/png/image_loader_png.cpp (hunk 5 above)
Comment (qarmin) [reply drivers/png/image_loader_png.cpp]: I can't put that line there, because Godot crash a little after start in OS_X11::set_icon function
Zrzut ekranu z 2019-11-18 20-15-18
Default value of -1 is set to p_len and is used in a lot of functions using Image with constructor
Zrzut ekranu z 2019-11-18 20-19-48
Zrzut ekranu z 2019-11-18 20-20-04
Zrzut ekranu z 2019-11-18 20-20-14

File: core/typedefs.h [hunk 12]
```diff
@@ -174,6 +174,9 @@ inline void __swap_tmpl(T &x, T &y) {
 
 static _FORCE_INLINE_ unsigned int next_power_of_2(unsigned int x) {
 
+	if (x == 0)
+		return 0;
```
Comment (aaronfranke) [inline core/typedefs.h]: Braces will be enforced in the near future, see #33027

File: scene/animation/tween.cpp [hunk 13]
```diff
@@ -63,6 +63,8 @@ void Tween::_add_pending_command(StringName p_key, const Variant &p_arg1, const
 		count = 2;
 	else if (p_arg1.get_type() != Variant::NIL)
 		count = 1;
+	else
+		count = 0;
```
Comment (aaronfranke) [inline scene/animation/tween.cpp]: Same as above.

File: core/typedefs.h (hunk 12 above)
Comment (akien-mga) [reply core/typedefs.h]: Yeah but this will be done by a script. No need to refactor existing code to match it yet (it's not bad to do it either, but it's not necessary).

File: core/math/camera_matrix.cpp [hunk 14]
```diff
@@ -183,6 +183,10 @@ void CameraMatrix::set_orthogonal(real_t p_size, real_t p_aspect, real_t p_znear
 
 void CameraMatrix::set_frustum(real_t p_left, real_t p_right, real_t p_bottom, real_t p_top, real_t p_near, real_t p_far) {
 
+	ERR_FAIL_COND(Math::is_equal_approx(p_right, p_left));
+	ERR_FAIL_COND(Math::is_equal_approx(p_top, p_bottom));
+	ERR_FAIL_COND(Math::is_equal_approx(p_far, p_near));
```
Comment (akien-mga) [inline core/math/camera_matrix.cpp]: I think we can be more clever here. The code reads like there are expectations on what number should be higher than the other, so we should check that.
```
ERR_FAIL_COND(p_right <= p_left);
ERR_FAIL_COND(p_top <= p_bottom);
ERR_FAIL_COND(p_far <= p_near);
```
CC @JFonS

File: drivers/gles3/rasterizer_canvas_gles3.cpp [hunk 15]
```diff
@@ -820,7 +820,7 @@ void RasterizerCanvasGLES3::_canvas_item_render_commands(Item *p_item, Item *cur
 
 				RasterizerStorageGLES3::Texture *texture = _bind_canvas_texture(mesh->texture, mesh->normal_map);
 
-				if (texture) {
+				if (texture && texture->width != 0 && texture->height != 0) {
```
Comment (akien-mga) [inline drivers/gles3/rasterizer_canvas_gles3.cpp]: There are lots of other occurrences of the same code in this file which also need to be handled.

I don't know if this would negatively impact performance, maybe we'd better ensure that textures can't have null widths/heights? CC @clayjohn

File: drivers/png/image_loader_png.cpp (hunk 5 above)
Comment (akien-mga) [reply drivers/png/image_loader_png.cpp]: This needs a dedicated bug report, but this manual overflow is definitely not OK.
`Image(const uint8_t *p_mem_png_jpg, int p_len = -1);` is bogus and should be removed, or changed so that a default length of `-1` means that the size is inferred from the byte array. Currently that's not done, so I don't even understand how `make_icon` works at all.

File: core/math/camera_matrix.cpp (hunk 14 above)
Comment (JFonS) [reply core/math/camera_matrix.cpp]: Yes, that makes more sense.

File: drivers/gles3/rasterizer_canvas_gles3.cpp (hunk 15 above)
Comment (akien-mga) [reply drivers/gles3/rasterizer_canvas_gles3.cpp]: This one is the last change I'm not 100% sure about, so I'd suggest to move it to a separate PR to be discussed further. Then this PR can be merged.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
