### PR TITLE
Fix potential infinite loop when calculating tile editor zoom level

### LINKED ISSUE #86496: Enabling "Physics Layers" for Tilemap with Tile Size of x:1 and y:1 always freezes the editor.
### Tested versions

- Reproducible in the versions: 
v4.2.1.stable.official [b09f793f5]
v4.3.dev1.official [9d1cbab1c]

### System information

Tested on following PC setups: Godot v4.3.dev1 - Windows 10.0.22631 - Vulkan (Forward+) - integrated Intel(R) Iris(R) Xe Graphics (Intel Corporation; 31.0.101.4255) - 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 Threads) and Godot v4.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.4633) - AMD Ryzen 7 7800X3D 8-Core Processor (16 Threads)

### Issue description

Adding "Physics Layers" for TileMap which has a tileset made of any image (tested on 8x8 sized .png texture and the default icon.svg) and Tile Size set to x: 1, y: 1 _always_ freezes the editor and gives no crash log. 

This works the other way around too so that I enable physics layers first before setting the Tile Set but this basically corrupts the project as it won't load anymore once the changes are made in.

I'm suspecting that some code within cannot handle the Tile Size of x:1, y:1, which I need, as this does not occur if they are for example the basic values 16 and 16.

This bug is reproducible within a minute in a completely new project like shown in the example video: 

https://github.com/godotengine/godot/assets/3968462/22ff8754-f011-45bb-8029-4e4df0a90612

### Steps to reproduce

1. Create a TileMap node
2. Add a Tile Set with any image
3. Set Tile Size to x:1 and y:1
4. Enable "Physics Layers"

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes https://github.com/godotengine/godot/issues/86496

### CODE REVIEW

File: editor/plugins/tiles/tile_data_editors.cpp [hunk 1]
```diff
@@ -33,6 +33,7 @@
 #include "tile_set_editor.h"
 
 #include "core/math/geometry_2d.h"
+#include "core/math/math_funcs.h"
```
Comment (AThousandShips) [inline editor/plugins/tiles/tile_data_editors.cpp:36]:
```suggestion
```
Already included in `geometry_2d`

**Comment by VetusScientia** [comment]
I made some modifications to the code as I noticed some potential issues, especially regarding zoom limits. Below, I describe the main ones:

#### Points of Divergence:

1. **Consideration of Zoom Limits:**
   - **Changes in this PR:** It does not explicitly consider the maximum and minimum zoom limits during the zoom adjustment loops.
   - **My changes:** Implement precise checks for the maximum and minimum zoom limits, avoiding infinite loops and ensuring that the zoom does not exceed these limits.

2. **Zoom Adjustment Logic:**
   - **Changes in this PR:** It uses loops to increase or decrease the zoom until reaching the desired tile size, without explicitly considering the zoom limits.
   - **My changes:** Considers whether the tile size multiplied by the maximum zoom is smaller than the desired size. It uses loops only when necessary, with checks for the zoom limits.

3. **Handling Extreme Conditions:**
   - **Changes in this PR:** It does not explicitly address scenarios where the original tile size multiplied by the maximum zoom is smaller than the desired size.
   - **My changes:** Specifically handles these extreme conditions, ensuring proper zoom adjustment even in situations where the initial tile size multiplied by the maximum zoom is smaller than the desired size.
   
#### My Code - I tested it locally and it worked without any apparent errors:
   
  ```cpp
  // Set the default zoom value.
int default_control_y_size = 200 * EDSCALE;

float target_tile_size = default_control_y_size / editor_zoom_widget->get_zoom();
Vector2 original_tile_size = tile_set->get_tile_size();
Vector2 current_tile_size = original_tile_size * editor_zoom_widget->get_zoom();

// Checks if the multiplication of the tile size by the maximum zoom is less than the default size
if (original_tile_size.y * editor_zoom_widget->get_max_zoom() < default_control_y_size) {
	// Adjusts the zoom to the maximum possible without exceeding the desired standard size
	float new_zoom = editor_zoom_widget->get_zoom() * (default_control_y_size / (original_tile_size.y * editor_zoom_widget->get_max_zoom()));
	if (new_zoom >= editor_zoom_widget->get_max_zoom()) {
		editor_zoom_widget->set_zoom(editor_zoom_widget->get_max_zoom());
	} else {
		editor_zoom_widget->set_zoom(new_zoom);
	}
} else {
	// Checks if the current tile size is smaller or larger than the desired size
	if (current_tile_size.y < target_tile_size) {
		while (current_tile_size.y < target_tile_size && editor_zoom_widget->get_zoom() < editor_zoom_widget->get_max_zoom()) {
			editor_zoom_widget->set_zoom(editor_zoom_widget->get_zoom() * 1.1);
			current_tile_size = original_tile_size * editor_zoom_widget->get_zoom();
		}
	} else if (current_tile_size.y > target_tile_size) {
		while (current_tile_size.y > target_tile_size && editor_zoom_widget->get_zoom() > editor_zoom_widget->get_min_zoom()) {
			editor_zoom_widget->set_zoom(editor_zoom_widget->get_zoom() * 0.9);
			current_tile_size = original_tile_size * editor_zoom_widget->get_zoom();
		}
	}
}

_zoom_changed();
  ```
 
I'm not sure if the issues I've highlighted are really important to emphasize, but I made that comment just in case and to check for problems.

*This is my first time commenting on an open-source project, so I hope I haven't done anything strange or wrong.* Have a great day!

File: editor/plugins/tiles/tile_data_editors.cpp (hunk 1 above)
Comment (jsjtxietian) [reply editor/plugins/tiles/tile_data_editors.cpp:36]: Thanks! Visual studio frequently acts up

**Comment by jsjtxietian** [comment]
@VetusScientia Thank you very much for your suggestion, invaluable.

I guess we can ask for some advice from @groud since he is the author of this code.

Also, feel free to take my pr and work based on it.

**Comment by groud** [comment]
Alright, sorry for the late review, and thanks for the contribution.

While @VetusScientia's one is, like, more "correct", it would add a lot of LoC for limited gains IMO. I think the approach by @jsjtxietian is the simplest one. I think the current state of the PR is acceptable.

**Review by groud — APPROVED** [review]
Needs the comment by @AThousandShips 's addressed, but aside from that, LGTM.

File: editor/plugins/tiles/tile_data_editors.cpp (hunk 1 above)
Comment (jsjtxietian) [reply editor/plugins/tiles/tile_data_editors.cpp]: Done

**Comment by VetusScientia** [comment]
> You did perfectly fine ! :)

Thank you very much, @ground! I'm still studying Godot's source code, meaning I'm still a noob :smile:

> While @VetusScientia's one is, like, more "correct", it would add a lot of LoC for limited gains IMO.

But the current state of the PR is indeed simpler and works well. I hope to be able to contribute better in the future! 

_Have a great day!_

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.
