### PR TITLE
[3.x] Fix `AtlasTexture` nesting

### LINKED ISSUE #42806: SpriteFrames not working with TextureAtlas!?
**Godot version:**
3.2.3

**OS/device including version:**
Ubuntu 20

**Issue description:**
I have a couple files like this that I am using to create a SpriteFrames for an AnimatedSprite.

Arrow

It works fine until I change import settings to combine some into a TextureAtlas? Then It changes and I cannot select the right tiles?

**Steps to reproduce:**

1. animation is fine
2. combine with other files into atlas
2. animation broke?

Peek-2020-10-12-15-58

I have seen some related issues like this: https://github.com/godotengine/godot/issues/9340 but none really the same I think.

**Minimal reproduction project:**
https://github.com/rakkarage/TestAtlasAtlas

Thanks.

### LINKED ISSUE #56767: scene files not updating region for sub-resources when the linked .tres file is updated, causing all animated sprites, etc to be wrong
### Godot version

3.4.2

### System information

PopOS

### Issue description

If you have a .tres file pointing at a region of a graphic file and an animation file using it, then update the tres file region, any references to it in scene files (e.g./i.e. AnimatedSprite) are not updated because they are themselves hard-coding the region in sub-texture section and not updating themselves when tres files are updated. The result is while the .tres file is ok, all uses of it inside a scene file now point at the wrong place.

A typical example is a sprite sheet/atlas that is rearranged (e.g. texture packer), causing everything to become invalid.

Here a snippet from a .tres file:

region = Rect2( **96, 32**, 32,32 )

Here is the .tscn file reference for the first region for an AnimatedSprite:

[ext_resource path="res://assets/image.tres" type="Texture" id=2]
[sub_resource type="AtlasTexture" id=12]
atlas = ExtResource( 2 )
region = Rect2( **96, 32**, 32,32 )

As you can see it is referencing 96,32 for the region in the .tres file which is correct and has also duplicated this to refer to each sprite in my .tres file.

So, update the spritesheet and tres file now becomes:
region = Rect2( **64,32**, 32,32 )

This is correct. Note the position has changed, opening the new .tres file shows the correct same image. However, the .tscn file still has this:

[sub_resource type="AtlasTexture" id=12]
atlas = ExtResource( 2 )
region = Rect2( **96, 32**, 44, 64 )

It has not updated, i.e. it is ignoring completely the .tres file change. I don't know whether .tscn file should be storing region as an offset for .tres files or whether Godot should know there's been a file change and update sub-regions, but either way, it's not working.

### Steps to reproduce

1. Open the project and open the .tres file and note the graphic
2. Open the scene Animated Sprite and note it is correct
3. Close Godot, rename/delete the image.png and image.tres, and rename image-new.png and image-new.tres to be image.png and image.tres, i.e. to simulate changing the file because it is an atlas that will change (manually or via texturepacker)
4. Repeat step 1 and 2 and note the tres file is correct, however the animated sprite is now wrong

### Minimal reproduction project

[tres_not_updated.zip](https://github.com/godotengine/godot/files/7869057/tres_not_updated.zip)
s

### PR DESCRIPTION
**Pull request by kleonc**
When drawing an `AtlasTexture` it was directly calling the `VisualServer` by itself instead of just forwarding the draw request to the source `atlas` texture (with the proper rect/region passed in). As a result an `AtlasTexture` being a source `atlas` of another `AtlasTexture` could have resulted in incorrect rendering. This should be fixed now (assuming other methods work as they're supposed to).

With this being fixed it means that pretty much nothing external should care if some `Texture` is actually an `AtlasTexture` as there should be no need to treat it as some special case where `AtlasTexture`'s `region` and/or `margin` needs to be manually taken into account or something like that. If there's such special casing somewhere then it's very likely there's something wrong conceptually in there (as `AtlasTexture` should probably be handling this stuff by itself).

So for example fix in #37939 was conceptually wrong, the same as my fix in #51030 on top of it. I've kind of reverted them as such special casing is not needed in there (it was never needed in there, the bug was elsewhere). Now it should work properly.
Fixes #42806.
Fixes #56767.
Just note that for the frames already saved with the incorrect data above issues still hold.

### CODE REVIEW

File: scene/resources/texture.cpp [hunk 1]
```diff
@@ -915,7 +915,11 @@ uint32_t AtlasTexture::get_flags() const {
 }
 
 void AtlasTexture::set_atlas(const Ref<Texture> &p_atlas) {
-	ERR_FAIL_COND(p_atlas == this);
+	Ref<AtlasTexture> at = p_atlas;
+	while (at.is_valid()) {
+		ERR_FAIL_COND_MSG(at == this, vformat("Can't set %s as atlas of %s as it would result in a cyclic dependency.", p_atlas, this));
```
Comment (akien-mga) [inline scene/resources/texture.cpp:920]: Interesting, is there an implicit conversion from `Ref<T>` to `String` for use in `vformat`? I used to call `->to_string()` manually.

File: scene/resources/texture.cpp [hunk 2]
```diff
@@ -915,7 +915,11 @@ uint32_t AtlasTexture::get_flags() const {
...
+		at = at->atlas;
+	}
 	if (atlas == p_atlas) {
```
Comment (akien-mga) [inline scene/resources/texture.cpp:923]: Nitpick but this could come first to avoid the while loop in this no-op case.

**Comment by akien-mga** [comment]
> I've also added a check to `AtlasTexture::set_atlas()` ensuring no cyclic dependency will be created between some `AtlasTexture`s.

I once went down that rabbit hole and there's still a lot of horrible ways to trigger cyclic dependencies by mixing and matching proxy texture formats, e.g.:
```
var a1 = AtlasTexture.new()
var p1 = ProxyTexture.new()
p1.base = a1
a1.atlas = p1
	
var sp = Sprite.new()
sp.texture = a1
add_child(sp)
```

Basically any `Texture` type that uses another `Texture` type internally can easily create such cyclic dependencies.
Also `MeshTexture`, and probably `AnimatedTexture`, etc.

File: scene/resources/texture.cpp (hunk 1 above)
Comment (kleonc) [reply scene/resources/texture.cpp:920]: Actually I haven't even thought of that, just wrote it like this and it worked. :smile: 

Just looked at it and `vformat` seems to take in `const Variant &` and there's a `operator Variant()` in `Ref<T>`. And `vformat` passes such `Variant` to `String::sprintf` which, in case of `%s`, (indirectly) calls `Variant::operator String()` which calls `Variant::stringify`. Something like that.

**Comment by kleonc** [comment]
> > I've also added a check to `AtlasTexture::set_atlas()` ensuring no cyclic dependency will be created between some `AtlasTexture`s.
> 
> I once went down that rabbit hole and there's still a lot of horrible ways to trigger cyclic dependencies by mixing and matching proxy texture formats, e.g.:
> 
> ```
> var a1 = AtlasTexture.new()
> var p1 = ProxyTexture.new()
> p1.base = a1
> a1.atlas = p1
> 	
> var sp = Sprite.new()
> sp.texture = a1
> add_child(sp)
> ```
> 
> Basically any `Texture` type that uses another `Texture` type internally can easily create such cyclic dependencies. Also `MeshTexture`, and probably `AnimatedTexture`, etc.

Maybe adding a method like `virtual bool Texture::is_referenced_by(const Ref<Texture> &other_texture)` overridden accordingly by `AtlasTexture`, `ProxyTexture` etc. and used in `AtlasTexture::set_atlas`, `ProxyTexture::set_base` etc. would solve that?

**Comment by kleonc** [comment]
I've actually removed that cyclic dependency check as that wasn't really a proper solution, it was just checking one specific case. And a proper solution (whatever it will be) can be made in another PR.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
