### PR TITLE
Assign temporary path to preloaded resources

### LINKED ISSUE #72854: Opening a currently preloaded scene will remove paths from sub-resources
### Godot version

4.0 a05670c

### System information

Windows 10 x64

### Issue description

Follow-up to #72257
The PR fixed only half of the issue. Sub-resource IDs are no longer lost, but paths still are. When a scene is preloaded in a currently opened script, opening that scene will result in all sub-resources having empty paths until you save it. While it's harmless in most cases, it's a major pain for built-in scripts, because they appear as `[unsaved]` in the script editor (which leads to further issues, like not being closed on scene close or not being able to open multiple scripts).

https://user-images.githubusercontent.com/2223172/217350742-d3b204d9-c30b-4b01-b8dd-d84f9e39e954.mp4

As identified in https://github.com/godotengine/godot/pull/72257#issuecomment-1412393593, the issue is caused by `preload()` using resource cache in a wrong way. This needs a GDScript fix (and #72257 can be then reverted).

### Steps to reproduce

1. Create a scene
2. Close it
3. Preload it in a script
4. Open again

### Minimal reproduction project

[PreloadBug.zip](https://github.com/godotengine/godot/files/10678899/PreloadBug.zip)

### LINKED ISSUE #80812: Crash when opening preloaded scene
### Godot version

4.2 5444afa

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

```
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.2.dev.custom_build (5444afae63f37cb4b890c781e5679a3b7ee5a392)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] List<ScriptLanguage::ScriptError,DefaultAllocator>::operator[] (C:\godot_source\core\templates\list.h:521)
[1] ScriptTextEditor::_validate_script (C:\godot_source\editor\plugins\script_text_editor.cpp:490)
[2] ScriptTextEditor::enable_editor (C:\godot_source\editor\plugins\script_text_editor.cpp:168)
[3] ScriptEditor::edit (C:\godot_source\editor\plugins\script_editor_plugin.cpp:2399)
[4] ScriptEditor::edit (C:\godot_source\editor\plugins\script_editor_plugin.h:513)
[5] ScriptEditor::set_scene_root_script (C:\godot_source\editor\plugins\script_editor_plugin.cpp:3543)
[6] EditorNode::_set_main_scene_state (C:\godot_source\editor\editor_node.cpp:3569)
[7] call_with_variant_args_helper<EditorNode,Dictionary,Node *,0,1> (C:\godot_source\core\variant\binder_common.h:308)
[8] call_with_variant_args_dv<EditorNode,Dictionary,Node *> (C:\godot_source\core\variant\binder_common.h:451)
[9] MethodBindT<EditorNode,Dictionary,Node *>::call (C:\godot_source\core\object\method_bind.h:333)
[10] Object::callp (C:\godot_source\core\object\object.cpp:741)
[11] Callable::callp (C:\godot_source\core\variant\callable.cpp:62)
[12] CallQueue::_call_function (C:\godot_source\core\object\message_queue.cpp:220)
[13] CallQueue::flush (C:\godot_source\core\object\message_queue.cpp:326)
[14] SceneTree::physics_process (C:\godot_source\scene\main\scene_tree.cpp:474)
[15] Main::iteration (C:\godot_source\main\main.cpp:3463)
[16] OS_Windows::run (C:\godot_source\platform\windows\os_windows.cpp:1479)
[17] widechar_main (C:\godot_source\platform\windows\godot_windows.cpp:182)
[18] _main (C:\godot_source\platform\windows\godot_windows.cpp:204)
[19] main (C:\godot_source\platform\windows\godot_windows.cpp:218)
[20] WinMain (C:\godot_source\platform\windows\godot_windows.cpp:232)
[21] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[22] <couldn't map PC to fn name>
-- END OF BACKTRACE --
```
Probably related to #72854

### Steps to reproduce

1. Open MRP
2. Open Preload.gd
3. Open Scene.tscn

### Minimal reproduction project

[Preload.zip](https://github.com/godotengine/godot/files/12387842/Preload.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #72854 in a safe and very hacky way.
The issue is waiting for a "proper" fix (see the discussion in #72257), but it kept annoying me in the meantime so I'm coming with another hack 🤷‍♂️

I added a method to Resource that sets the path completely bypassing the cache, so `Resource.get_path()` will return the "correct" path, while not causing unwanted side-effects. The method is called for built-in resources loaded with CACHE_MODE_IGNORE.

It was not enough, because GDScript keeps its own `path`, set with the regular `set_path()` method. I could make `set_temporary_path()` virtual, but instead I added a flag to track whether the path is valid and try returning `get_path()` if it's not.

Here's an extended MRP for the debugger bug that this fixes:
[PreloadBug.zip](https://github.com/godotengine/godot/files/12265238/PreloadBug.zip)
Preloaded built-in scripts still can't be clicked for some reason, but at least you can see their path.

EDIT:
Fixes #80812

### CODE REVIEW

File: core/io/resource.h [hunk 1]
```diff
@@ -103,6 +103,7 @@ class Resource : public RefCounted {
 
 	virtual void set_path(const String &p_path, bool p_take_over = false);
 	String get_path() const;
+	void set_temporary_path(const String &p_path);
```
Comment (reduz) [inline core/io/resource.h:106]: Have not looked in depth but since its hacky, maybe better to use a metadata, then clear it?

Comment (adamscott) [reply core/io/resource.h:106]: I would name it for what it does. 
```suggestion
	void set_path_cache(const String &p_path);
```

**Review by akien-mga — APPROVED** [review]
Seems relatively safe. Let's merge and test it in the next beta.

**Comment by akien-mga** [comment]
Thanks!

**Comment by nikitalita** [comment]
@KoBeWi  shouldn't it be here, too?
https://github.com/KoBeWi/godot/blob/a3627b6e37049ca55cc0d5227a4ff7bc1b19ae1e/scene/resources/resource_format_text.cpp#L713

And here:
https://github.com/KoBeWi/godot/blob/a3627b6e37049ca55cc0d5227a4ff7bc1b19ae1e/scene/resources/resource_format_text.cpp#L801

**Comment by KoBeWi** [comment]
Well, that code isn't known to cause problems, so it wasn't necessary. This solution is basically a hack, so it should be used only where relevant.

**Comment by nikitalita** [comment]
Given your current fix, I'm not really sure why those instances above wouldn't cause problems. Right now, you're assigning the patch_cache to both the internal resources and the main resource in resource_format_binary, but in resource_format_text, you're only assigning the path_cache to the internal resources. Unless you intended to only assign the path_cache to the internal resources in resource_format_binary?

**Comment by KoBeWi** [comment]
> Right now, you're assigning the path_cache to both the internal resources and the main resource in resource_format_binary

I'm not, the code I added for both is the same.
The bug affects only internal resources.
