### PR TITLE
Fix `GridMap` shortcuts being triggered during freelook (mouse captured)

### LINKED ISSUE #104122: GridMap shortcuts not disabled while Freelook with right-click
### Tested versions

4.4.stable, 4.4.1.rc1

### System information

Godot v4.4.1.rc1 - Windows 10 (build 19045) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 (NVIDIA; 32.0.15.6094) - Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 threads)

### Issue description

The shortcuts while using GridMap are not disabled when Freelook with right-click is used.
This results in changing tools (selection, erase, paint) and rotating the tiles (W, A, S, D) while in Freelook.

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

[gridmap-issue.zip](https://github.com/user-attachments/files/19249074/gridmap-issue.zip)

### PR DESCRIPTION
**Pull request by ryevdokimov**
Fixes: https://github.com/godotengine/godot/issues/104122

### CODE REVIEW

File: modules/gridmap/editor/grid_map_editor_plugin.cpp [hunk 1]
```diff
@@ -674,7 +674,7 @@ void GridMapEditor::_show_viewports_transform_gizmo(bool p_value) {
 }
 
 EditorPlugin::AfterGUIInput GridMapEditor::forward_spatial_input_event(Camera3D *p_camera, const Ref<InputEvent> &p_event) {
-	if (!node) {
+	if (!node || Input::get_singleton()->get_mouse_mode() == Input::MOUSE_MODE_CAPTURED) {
```
Comment (Calinou) [inline modules/gridmap/editor/grid_map_editor_plugin.cpp:677]:
```suggestion
	// If the mouse is currently captured, we are most likely in freelook mode.
	// In this case, disable shortcuts to avoid conflicts with freelook navigation.
	if (!node || Input::get_singleton()->get_mouse_mode() == Input::MOUSE_MODE_CAPTURED) {
```

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected.

Shortcuts still tend to be prone to misinputs as they'll be effective if you press a navigation key *then* enter freelook without releasing the key. Ideally, we should make all shortcuts that can potentially conflict with freelook effective on key release, rather than on key press (or, perhaps better, cancel the shortcut's action if freelook was entered before the key was released). This issue is not specific to GridMap shortcuts; it also happens with the <kbd>QWER</kbd> shortcuts to switch between selection modes.

Either way, this is still an usability improvement over what we have now.

**Comment by Repiteo** [comment]
Thanks!
