### PR TITLE
Properly clear material slots on mesh instance when material is freed

### LINKED ISSUE #67144: Debugger throwing errors when MeshInstance3D containing a duplicate material is removed with queue_free()
### Godot version

4.0.beta2

### System information

Windows 11, RTX 3070TI, GLES2

### Issue description

When attempting to create a duplicate material of a MeshInstance3D, the material.duplicate() method appears to work properly, however, it throws errors in the Debugger when 'queue_free()' is executed on a meshinstance with a duplicated material. This behavior does not occur if the material is not duplicated.

Error messages:

```
E 0:00:02:0561   material_casts_shadows: Condition "!material" is true. Returning: true
  <C++ Source>   servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2676 @ material_casts_shadows()
E 0:00:02:0561   material_is_animated: Condition "!material" is true. Returning: false
  <C++ Source>   servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2663 @ material_is_animated()
E 0:00:02:0561   material_get_instance_shader_parameters: Condition "!material" is true.
  <C++ Source>   servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2689 @ material_get_instance_shader_parameters()
E 0:00:02:0561   material_update_dependency: Condition "!material" is true.
  <C++ Source>   servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2701 @ material_update_dependency()

```

### Steps to reproduce

Instantiate a scene object that contains a mesh with a material assigned to it.
Get the meshinstance3d object of the instantiation.
Get the material of the meshinstance3d, and utilize the .duplicate() method to create a copy of the material
Reassign the duplicate material to the meshinstance3d override material
call queue_free() on the instance to remove it, which will result in errors thrown stating that parameters are missing from the duplicate material.

### Minimal reproduction project

[MaterialBugProject.zip](https://github.com/godotengine/godot/files/9742041/MaterialBugProject.zip)

There is a bool toggle on the main scene that will enable or disable material duplication on the spawned meshinstance3D objects. It should be enabled by default which will demonstrate the bug, disabling it shows that non duplicated materials do not behave the same way.

### PR DESCRIPTION
**Pull request by BastiaanOlij**
The dependency code for mesh instance was simply calling `_instance_queue_update` when a material was freed. This function however does not unset the slots in which the material was used. 

This PR changes this logic and will first clear any usage of the material being freed, be it override, overlay, surface override or particles.

Fixes #67144

### CODE REVIEW

File: servers/rendering/renderer_scene_cull.h [hunk 1]
```diff
@@ -39,6 +39,7 @@
 #include "core/templates/pass_func.h"
 #include "core/templates/rid_owner.h"
 #include "core/templates/self_list.h"
+#include "rendering_server_globals.h"
```
Comment (akien-mga) [inline servers/rendering/renderer_scene_cull.h:42]: Should use `servers/rendering/...` for consistency. In principle, we should only use relative paths for modules and platform code (should be self-contained).

**Review by clayjohn — APPROVED** [review]
Looks good to me!

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.4.
