### PR TITLE
Fix NodeOneShot doesn't respect fade-out when aborting and improvement

### LINKED ISSUE #53947: Oneshot AnimationTree node doesn't respect fade-out duration when unsetting active parameter
### Godot version

3.3.4.stable.mono.official

### System information

Windows 10

### Issue description

When setting a oneshot node to active and waiting for it to finish, the active parameter gets reset automatically and the animation will blend in and out according to the oneshot-node's settings.
But when unsetting the active parameter while its animation is still playing (to end it prematurely) the fade-out setting is not respected and the animation is reset instantly (snapping back to start).

Here, the first 2 triggers are untoggled manually (snapping) and the last one is left alone to fade back itself:
https://user-images.githubusercontent.com/8841352/137686625-a6f980a7-d3f9-4798-91ba-cd250f04184e.mp4

### Steps to reproduce

Create an animationTree with a oneshot node, toggle it active and immediately toggle it back inactive, see the animation snap back instead of fading back.

### Minimal reproduction project

_No response_

### LINKED ISSUE #73113: Resetting the animation during the fade-out produced a strange condition
### Godot version

4.0.rc (Also 3.x)

### System information

Any

### Issue description

Here is an example of a NodeTransition case.
	
During a 3-second crossfade from Animation A to Animation B, the parent's OneShot or Transition resets their state after 1 second has elapsed.
	
In this case, animation B is reset and played back, but the 2-second fade of animation A, which has not been reset, is still there.

https://user-images.githubusercontent.com/61938263/218275507-7ae7a414-6b88-4ddb-9975-afd3c5e9dd6d.mp4

So, it is necessary to detect the reset and remove the remaining fade.

### Steps to reproduce

Use Xfade transition and reset it during fading

### Minimal reproduction project

[fadetest.zip](https://github.com/godotengine/godot/files/10714466/fadetest.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
Fixes: #53947
Fixes: #73113

Apply same fix to NodeOneShot with #73120.

Also, add a request `ONE_SHOT_REQUEST_FADE_OUT` to NodeOneshot to Abort with respect to the fade-out time.

This changes the transition timing of the active state. This means that the transition to the next state will occur at the start of the fade in the same way as NodeTransition and NodeState.

However, for the Active state, it should be true if OneShot is still in effect. Also for compatibility.

Therefore, the display (retrieve-able) active state and the internal active state are separated as: `active` and `internal_active`.

In addition, the xfade curve can be set as in NodeTransition and StateMachine.

https://user-images.githubusercontent.com/61938263/222272844-87771e4a-a212-4f9b-8d77-ceb8a4d2e647.mp4

### CODE REVIEW

File: scene/animation/animation_blend_tree.cpp [hunk 1]
```diff
@@ -334,19 +414,32 @@ double AnimationNodeOneShot::process(double p_time, bool p_seek, bool p_is_exter
...
 		}
 	}
 
 	bool os_seek = p_seek;
-	if (p_seek) {
-		cur_time = p_time;
+
+	if (clear_remaining_fade) {
+		os_seek = false;
+		cur_fade_out_remaining = 0;
```
Comment (lyuma) [inline scene/animation/animation_blend_tree.cpp:425]: Should `clear_remaining_fade` also set `is_shooting = false`?

**Review by lyuma — APPROVED** [review]
In terms of the implementation and fade out curve, I see nothing wrong here.

I'm assuming the main bugfix here is due to calling `blend_input(1, ...` even while fading, rather than short circuiting with `return blend_input(0...)` which prevented 1 from being evaluated in the old version.

However, my personal preference is to avoid renames if possible. I cannot evaluate the necessity of renaming against the compatibility breakage in 4.1, so I will leave this to Godot devs who have more experience with backwards compatibility decisions.

**Comment by TokageItLab** [comment]
If we do not change the NodeOneShot API name now, we will have to set a constant like ONE_SHOT_REQUEST_FADEOUT instead of ONE_SHOT_REQUEST_FADE_OUT for consistency, and we will accumulate APIs with bad names in the future, so I think we should change it now.

**Comment by mhilbrunner** [comment]
Note that these renames not only break GDScript scripts, but also compatability with GDExtension and C#. Ideally, these renames should have happened before 4.0 final release; now we really need to consider how critical these are, and if in doubt strive to keep compatability.

**Comment by TokageItLab** [comment]
Certainly it should not be changed in a patch release like 4.0.x. However, I think it should be changed as needed in minor releases like 4.x, rather than continuing to accumulate badly named APIs until 5.0.

Also, it may not be good to just rename PR, but this PR breaks compatibility since it changes not only the method name but also the behavior of the original functionality in the first place. In such cases, I believe it is acceptable to rename to let them that changing the behavior (though the renaming should only be an extra).

**Comment by fire** [comment]
Is it possible to use a complete new set of names for the changed functionality? That would be compatible.

**Comment by TokageItLab** [comment]
I had already supported that migration as deprecated for properties' setter/getter, but I followed @fire's suggestion and added deprecated methods with the old method names bound to them. This should temporarily ensure script compatibility, but I also thought it might be better to add an `is_deprecated` flag to the bind macro.

File: modules/mono/utils/naming_utils.cpp [hunk 2]
```diff
@@ -60,8 +60,6 @@ const HashMap<String, String> pascal_case_part_overrides = _create_hashmap_from_
 		{ "AA", "AA" }, // Anti Aliasing
 		{ "AO", "AO" }, // Ambient Occlusion
 		{ "FILENAME", "FileName" },
-		{ "FADEIN", "FadeIn" },
-		{ "FADEOUT", "FadeOut" },
```
Comment (TokageItLab) [inline modules/mono/utils/naming_utils.cpp:64]: @mhilbrunner The CSharp test has an error, so I looked into it, and it seems that your point is partially incorrect.

It seems that the method `get_fade_in_time` has already been converted to the method `GetFadeInTime` by `naming_utils.cpp`. However, since the other part naming in CPP are consistent with `fade_in`, so this "fadein -> FadeIn" conversion seems to be currently only used for NodeOneShot and it looks entirely like a hack.

In summary:

- I added `set_fade_in_time` here, which is converted correctly to `SetFadeInTime` without `naming_utils.cpp` in CSharp.

- Also, I remain the deprecated method `set_fadein_time` for compatibility. However, `naming_utils.cpp` will convert it to `SetFadeInTime`, which will result in duplicated declarations and errors, so we need to remove it (and again, this is only used for NodeOneShot, so removing it here should not be a problem). One problem that occurs as a side effect of that is the addition of a new method `SetFadeinTime` to CSharp.

Comment (raulsntos) [reply modules/mono/utils/naming_utils.cpp:64]: Since this is just a rename and doesn't break compat, I think it's fine for the C# implementation to call the new `get_fade_in_time`.

As for the new deprecated `SetFadeinTime` method, it'd be nice to avoid generating it. We can probably skip it like we do with [some classes](https://github.com/godotengine/godot/blob/964a5353dbf5fc0dca4c4b7b9cfa5631dd5ab568/modules/mono/editor/bindings_generator.cpp#L117-L118) but this can probably be done in a separate PR as long as it gets merged before the new API ships. But I don't think it would be a big deal even if we end up shipping the new deprecated API.

**Comment by akien-mga** [comment]
I think this PR is going overkill on cosmetic compat breakage of the API where it's not needed. I understand that you might feel that `fade_in` is better than `fadein`, but it's not at all critical and as we made it clear multiple times, such compat breakage in 4.x releases is *not* expected.

I'm not fully closing the door to figuring out a proper way to let the API evolve in 4.x minor releases where it's very needed (fixing outright wrong names or bogus APIs), but this is not the case here.

So I'd appreciate if this PR was amended not to break compatibility, as I don't see why it's justified here.

**Comment by TokageItLab** [comment]
I would argue that the method conversion hack for CSharp there indicates that the original method name is incorrect and that this should be justified to remove such hacks,

**Comment by akien-mga** [comment]
Whatever hack was added in the C# bindings to make the API nicer for C# users is not a justification for breaking compat.

We released 4.0 with this API, it's not wrong, there's no reason to break compat or introduce a ton of duplicated deprecated methods because you don't like the look of "fadeout". Nobody asked for this change.

This PR claims to be fixing a logic bug - that's all it should do. But we can't merge that fix because it's being mixed with opinionated compat breakage when we made clear that this was not an option after the 4.0 release.

**Comment by TokageItLab** [comment]
For now, I will be separating only the PR for the renaming.

**Comment by TokageItLab** [comment]
@akien-mga Modified the old bound method names to leave them unchanged.

File: scene/animation/animation_blend_tree.cpp [hunk 3]
```diff
@@ -385,47 +449,60 @@ double AnimationNodeOneShot::_process(double p_time, bool p_seek, bool p_is_exte
...
 
 	ClassDB::bind_method(D_METHOD("set_mix_mode", "mode"), &AnimationNodeOneShot::set_mix_mode);
 	ClassDB::bind_method(D_METHOD("get_mix_mode"), &AnimationNodeOneShot::get_mix_mode);
 
 	ADD_PROPERTY(PropertyInfo(Variant::INT, "mix_mode", PROPERTY_HINT_ENUM, "Blend,Add"), "set_mix_mode", "get_mix_mode");
 
 	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "fadein_time", PROPERTY_HINT_RANGE, "0,60,0.01,or_greater,suffix:s"), "set_fadein_time", "get_fadein_time");
+	ADD_PROPERTY(PropertyInfo(Variant::OBJECT, "fade_in_curve", PROPERTY_HINT_RESOURCE_TYPE, "Curve"), "set_fade_in_curve", "get_fade_in_curve");
 	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "fadeout_time", PROPERTY_HINT_RANGE, "0,60,0.01,or_greater,suffix:s"), "set_fadeout_time", "get_fadeout_time");
+	ADD_PROPERTY(PropertyInfo(Variant::OBJECT, "fade_out_curve", PROPERTY_HINT_RESOURCE_TYPE, "Curve"), "set_fade_out_curve", "get_fade_out_curve");
```
Comment (akien-mga) [inline scene/animation/animation_blend_tree.cpp:505]: I think we should aim to keep the new API consistent with the existing one, so these should be `fadein_curve` and `fadeout_curve` (same for the methods).

The internal C++ method renames are fine though, it's just the bindings which need to preserve compatibility.

Comment (TokageItLab) [reply scene/animation/animation_blend_tree.cpp]: done

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
