### PR TITLE
Fix Variant::OBJECT token parsing

### LINKED ISSUE #8969: Custom action keys/buttons are not saved
**Operating system or device - Godot version:**
3.0 master Linux

**Steps to reproduce:**
- Create new action in project and attribute some keys/buttons to it
- Save and close project
- When reopening project all keys/buttons for action are gone

### PR DESCRIPTION
**Pull request by cart**
Fixes @reduz's new generic Variant:OBJECT parsing code, which also fixes reading/writing input maps from project.godot.  This should resolve #8969.

### CODE REVIEW

File: core/variant_parser.cpp [hunk 1]
```diff
@@ -744,7 +744,7 @@ Error VariantParser::parse_value(Token &token, Variant &value, Stream *p_stream,
 						return err;
 
 					if (token.type == TK_PARENTHESIS_CLOSE) {
-
+						value = REF(obj->cast_to<Reference>());
```
Comment (bojidar-bg) [inline core/variant_parser.cpp]: Can we be sure that the value would be a Reference-derived type each time?

Comment (mcanders) [inline core/variant_parser.cpp]: Probably not.  I convinced myself that all Objects could be cast to a reference but looking back thats definitely false as Reference inherits from Object and not the other way around.  

Sorry I'm still new 😄 

Would something like this work?

```cpp
Reference *r = obj->cast_to<Reference>();
if (r)
{
    value = REF(r);
}
else
{
    value = obj;
}
```

Comment (bojidar-bg) [inline core/variant_parser.cpp]: Or you could just look the type name up in ClassDB?

Comment (mcanders) [inline core/variant_parser.cpp]: We could do this instead:

```cpp
if (ClassDB::is_parent_class(obj->get_class_name(), "Reference")) {
    value = REF(obj->cast_to<Reference>());		
} else {
    value = obj;
}
```

I've seen both patterns used in this code base.  When checking if something is a Node, ive seen ClassDB used, but when checking if something is a Reference, ive seen cast_to used.  But shouldn't the "cast_to" approach be much faster?  "is_parent_class" needs to walk the class dependency tree and do a bunch of string comparisons.

Am I wrong or did you have a different idea?

**Comment by mcanders** [comment]
I just pushed the cast_to approach as I believe it is the best option.  But I'm happy change it if anyone has strong opinions.

File: core/variant_parser.cpp (hunk 1 above)
Comment (bojidar-bg) [inline core/variant_parser.cpp]: Ah, if it is already used like that, it should be fine.. 😃
