### PR TITLE
Replace squish with bcdec for BC decompression

### LINKED ISSUE #95721: VRAM compressed textures are not rendered in the web when the import mode is high quality.
### Tested versions

Reproducible in Godot 4.3 stable, windows 10, chrome browser. Also in Godot 4.2.

### System information

windows 10, Godot 4.3 stable, chrome browser, RX 580, compatibility mode, web export with default settings

### Issue description

My game is a web 2D game with lots of animation that benefit greatly from VRAM compressed import of images, as without it the VRAM consumption is close to 10GiB and the load times are high. The game is working perfectly when I run it normally in the editor, however in the browser the VRAM compressed textures are not rendered while all the rest are rendered normally.

### Steps to reproduce

Reimport the godot icon as vram compressed and try to render it on the web. It won't show. Reimport it as lossless or lossy and it will render normally.

### Minimal reproduction project (MRP)

[vram-compressed-textures-not-rendered-in-web.zip](https://github.com/user-attachments/files/16646889/vram-compressed-textures-not-rendered-in-web.zip)

### PR DESCRIPTION
**Pull request by BlueCube3310**
Fixes #95721

Replaces libsquish with the bcdec library for decompressing BC-compressed textures. This improves decompression speeds (about 2x faster) and allows runtime decompression of BC6 and BC7. 
Some more comparisons can be found here: https://aras-p.info/blog/2022/06/23/Comparing-BCn-texture-decoders/ 
(BC6 is probably faster here since in the blog's benchmarks it's also converted from half to float, in here it's directly to half).

Performance:
image: https://polyhaven.com/a/worn_brick_floor (no mipmaps)
Compressed with DirectXTex
bc1/bc2/bc3/bc6/bc7 - diffuse 4k
bc4 - displacement 4k
bc5 - normal (openGL) 4k

OS: Windows 10
CPU: AMD Ryzen 9 5900X 12-Core Processor (24 threads)
RAM: 64 GB DDR4
build: production

| format | squish | cvtt | bcdec |
|---------|-------|------|-------|
| bc1 | 52ms | n/a | 24ms |
| bc2 | 58ms | n/a | 31ms |
| bc3 | 61ms | n/a | 35ms |
| bc4 | 48ms | n/a | 12ms |
| bc5 | 60ms | n/a | 28ms |
| bc6 | n/a | 364ms | 122ms |
| bc7 | n/a | 174ms | 133ms |

TODO:
- [x] Add a testing project,
- [x] Compare performance

MRP: [bcdectest.zip](https://github.com/user-attachments/files/17130853/bcdectest.zip)

### CODE REVIEW

**Comment by fire** [comment]
As someone who touched the older areas of the compression I think this is a good idea, but we probably want to merge code changing the 3d compression types earlier or push it for Godot Engine 4.5.

**Comment by clayjohn** [comment]
> As someone who touched the older areas of the compression I think this is a good idea, but we probably want to merge code changing the 3d compression types earlier or push it for Godot Engine 4.5.

Keep in mind, this is only for _decompression_, so the impact will be much smaller than if we were to change the compression library

File: modules/bcdec/image_decompress_bcdec.cpp [hunk 1]
```diff
@@ -0,0 +1,180 @@
...
+
+	Vector<uint8_t> data;
+	int64_t target_size = Image::get_image_data_size(w, h, target_format, p_image->has_mipmaps());
+	int mm_count = p_image->get_mipmap_count();
+	data.resize(target_size);
+
+	const uint8_t *rb = p_image->get_data().ptr();
+	uint8_t *wb = data.ptrw();
+
+	// Decompress mipmaps.
```
Comment (fire) [inline modules/bcdec/image_decompress_bcdec.cpp:158]: @lyuma Can we check this? I've forgotten about how the mipmap texel squishing works.

**Comment by BlueCube3310** [comment]
I've fixed some bugs with bc6 and added benchmarks - bcdec is faster than both squish and CVTT in all formats. Surprisingly, bcdec's bc6 is 3x faster than CVTT

**Review by clayjohn — APPROVED** [review]
Looks great to me! The performance results are really the cherry on top of the cake!

**Review by fire — APPROVED** [review]
Did not deeply review the code, but the design proposal is good.

File: thirdparty/README.md [hunk 2]
```diff
@@ -650,6 +650,10 @@ comments and a patch is provided in the `patches` folder.
 
 Collection of single-file libraries used in Godot components.
 
+- `bcdec.h`
+  * Upstream: https://github.com/iOrange/bcdec
+  * Version: git (026acf98ea271045cb10713daa96ba98528badb7, 2022)
```
Comment (akien-mga) [inline thirdparty/README.md:655]: Just noticed this - there's been a handful of commits since (https://github.com/iOrange/bcdec/commits/main/), might be worth updating to the latest, even if there's no functional change. Just so that when I review thirdparty code I know we're up to date.

**Comment by akien-mga** [comment]
Thanks!
