### PR TITLE
Fix editor texture preview for certain specific dimensions

### LINKED ISSUE #35662: GradientTexture TRES periodically causes editor errors.
**Godot version:**
3.2 RC4

**OS/device including version:**
Win10 64-bit

**Issue description:**

When setting up a GradientTexture resource, the error throws some errors.  

Caught the one about image height.
https://github.com/godotengine/godot/blob/1c3aff42dea3f9d9c49e6395dd4a9c848e65cbf6/core/image.cpp#L891

The trace looks like:

```
>	godot.windows.tools.64.exe!Image::resize(int p_width, int p_height, Image::Interpolation p_interpolation) Line 889	C++
 	godot.windows.tools.64.exe!EditorTexturePreviewPlugin::generate(const Ref<Resource> & p_from, const Vector2 & p_size) Line 136	C++
 	godot.windows.tools.64.exe!EditorResourcePreviewGenerator::generate_from_path(const String & p_path, const Vector2 & p_size) Line 69	C++
 	godot.windows.tools.64.exe!EditorResourcePreview::_generate_preview(Ref<ImageTexture> & r_texture, Ref<ImageTexture> & r_small_texture, const EditorResourcePreview::QueueItem & p_item, const String & cache_base) Line 167	C++
 	godot.windows.tools.64.exe!EditorResourcePreview::_thread() Line 270	C++
 	godot.windows.tools.64.exe!EditorResourcePreview::_thread_func(void * ud) Line 108	C++
 	godot.windows.tools.64.exe!ThreadWindows::thread_callback(void * userdata) Line 55	C++

```

image

Hopefully nothing serious, but maybe it's something needing clean up?

**Steps to reproduce:**

1. Create a GradientTexture resource.  (Gives first error.)
2. Create the Gradient inside it.  (Gives the 0 size error.)

**Minimal reproduction project:**
Doesn't seem to always occur after it exists.  So the steps above are the most reliable method of reproduction.

### LINKED ISSUE #36940: Shader parameter taking a 256x1 pixel image raises an error.
**Godot version:**
3.2 stable

**OS/device including version:**
Linux 5.5.8

**Issue description:**
adding a `uniform sampler2D` shader parameter and assigning a png which is 256x1 pixels causes the error `ERROR: resize: Image height must be greater than 0. At: core/image.cpp:891.`.

**Steps to reproduce:**
1.  Create a new project
2.  Add a Sprite
3.  Add a shader
4. Add the following shader code:
```
shader_type canvas_item;
uniform sampler2D foo : hint_albedo;
```
5.  Assign a 256x1 pixel image to the "foo" shader parameter.
6.  Save, restart editor and select the sprite and the error message should be visible in the terminal.

Note: changing the image to a 256x2 pixel image doesn't cause the error anymore

### PR DESCRIPTION
**Pull request by mrushyendra**
Currently, an error may be issued when showing a preview of a resource if
the associated image is resized to sub-1 pixel dimensions. This fix ensures no such error
is issued. 

For example, when previewing a 256 x 1 PNG image:
Screenshot from 2020-06-18 16-50-53

After:
Screenshot from 2020-06-18 16-50-33

Figured that showing an image with 1-pixel width or height is better than not showing any 
preview at all, though there may be a small distortion. `p_size` must also already be size 1x1 or
bigger, else a different error would be issued in the `rendering_server`, so this should be safe.

Closes #36940

(The same issue may also occur with the `EditorImagePreviewPlugin`, `EditorBitmapPreviewPlugin` and `EditorMeshPreviewPlugin`, though none seem to have been raised so far)

Edit: Turns out it would also close #35662

### CODE REVIEW

File: editor/plugins/editor_preview_plugins.cpp [hunk 1]
```diff
@@ -127,7 +127,8 @@ Ref<Texture2D> EditorTexturePreviewPlugin::generate(const RES &p_from, const Siz
 	if (new_size.y > p_size.y) {
 		new_size = Vector2(new_size.x * p_size.y / new_size.y, p_size.y);
 	}
-	img->resize(new_size.x, new_size.y, Image::INTERPOLATE_CUBIC);
+	Vector2i new_size_i(MAX(1, static_cast<int>(new_size.x)), MAX(1, static_cast<int>(new_size.y)));
```
Comment (akien-mga) [inline editor/plugins/editor_preview_plugins.cpp:130]: We tend to prefer classic C-style casts, so just `(int)new_size.x` here.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.
