### PR TITLE
Fixes to the new inspector

### LINKED ISSUE #9890: The mouse gets locked when dragging a number field
Godot 3.0 alpha1 official
Windows 10 64 bits

I dragged the bloom intensity property, and my mouse got immediately stuck at the middle of the screen. It started to warp there showing a red icon, then it disappeared when I released the button. I tabbed out of Godot, then focused it again, and I could see my mouse warping at the center everytime I try to move it.
Then I was able to get back the mouse by clicking again.

Note 1: dragging didn't affect the property at all, it took the first "pixel" of movement (going from 1.0 to 1.1) but not more.

Note 2: it seems it doen't happen all the time.

Looks like another occurence of #7098.

### LINKED ISSUE #19008: Inspector Label Text Input reversed
Godot Master

Reproduce:
Cntl+D for duplicating the Node.
peek 2018-05-18 15-52

### LINKED ISSUE #19072: Mass/Weight doesn't update
Master revision 9a5950ace52c4ebb575d452d6451259d6f2323e3
Windows 7, 64 bit

3D Rigid Body has both a mass and a weight, and these update each other, but the new values aren't visible until you select a different object and then come back.

### PR DESCRIPTION
**Pull request by guilhermefelipecgs**
Fix #19008, Fix  #19072.
- Fix inspector dock not updating tree for main resource;
- Also fix "docks/property_editor/auto_refresh_interval" used by MultiNodeEdit, it wasn't working.

## Update:
Fix https://github.com/godotengine/godot/issues/9890#issuecomment-394844248.
Before:
out mp4
After:
out mp4
This happens when you try to slide to a value that the property doesn't allow (because of the minimum size of the children is "dynamic"), in this case the `margin_left` can't go above 15, but here it's set that can range from -4096 to 4096.
https://github.com/godotengine/godot/blob/66871322b99436990daec5a70c09620619430b8d/scene/gui/control.cpp#L2868
and the fix was just pass "anchor" on `_change_notify`.

### CODE REVIEW

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -1709,6 +1709,8 @@ void EditorInspector::_edit_set(const String &p_name, const Variant &p_value, bo
 		}
 	}
 
+	changing++;
```
Comment (guilhermefelipecgs) [inline editor/editor_inspector.cpp]: I moved this variable here to fix multiedit node and all other flows we can have inside this logic too.

**Comment by guilhermefelipecgs** [comment]
I removed:
- signal: `multiple_properties_changed`
- method: `add_property_editor_for_multiple_properties`, `_multiple_properties_changed`

because no one was using.

Maybe @reduz wants to review.

**Comment by vnen** [comment]
Is there anything missing for this? #19008 is an extremely annoying bug.

**Comment by guilhermefelipecgs** [comment]
> 19008 is an extremely annoying bug.

Yeah, this is annoying me too.

This pr is complete and waiting to merge, I just pointed out that I am removing an unused method that @reduz might be planning to use in the future, but I believe that since he didn't change the inspector again, he probably didn't intend to use it at all.

**Comment by vnen** [comment]
I'm not sure if he actually forgot an `emit_signal()` somewhere.

**Comment by reduz** [comment]
Please dont remove multiple properties changed, it will be used in the reworked anchor/margin editor

**Comment by guilhermefelipecgs** [comment]
Ok, changes made.
