### PR TITLE
Perform a clean Gradle build if android plugins changed

### LINKED ISSUE #38986: Can't disable custom android plugin
**Godot version:**
3.2.2 beta3

**OS/device including version:**
Windows 10

**Issue description:**
I sucessfully created an Android plugin using the new v1 system and deployed it on a phone. I then disabled it in the export settings, built again and got this gradle error:

The only way to fix this is to either:
- Enable the plugin again
- Clear/delete the `build` folder and rebuild

Note that i never enabled the GodotPayment plugin.

**Steps to reproduce:**
1. Enable custom Android template build
2. Add a barebones custom plugin to `plugins` folder
3. Enable it in export settings and build -> builds fine
4. Disable it in export settings and build -> build error

### PR DESCRIPTION
**Pull request by mbrlabs**
Fixes #38986

To check if a plugin has been part of the previous build i check if it appears in the manifest merger logs in `build/outputs/logs/`. If it has been enabled/disabled since the last build i do a clean Gradle build, which deletes the android/build/build directory.

Note, that i only tested this on the 3.2 branch, but since there is no difference between master and 3.2 i directly opened this PR against master.

### CODE REVIEW

**Comment by m4gr3d** [comment]
@mbrlabs This seems to do the job partially as the logic doesn't check for changes to the plugin dependencies (both local and remote ones) in the manifest merger logs.

I wonder though if it would be easier and simpler to compare the last updated timestamp instead.

We can add a `last_updated` field to the `PluginConfig` struct and at load time (the logic used by `get_plugins()`) fill it with the value of the last updated component of the plugin:
- Start with the `last update time` for the plugin configuration file.
- If any of the plugin binary or local dependencies has a more recent updated timestamp, use that instead.

Then at export time, check the `last update timestamp` of the `build` directory with the ones from the enabled plugins. As soon as one of the enabled plugins is newer, perform a `clean` build.

To check for added/removed plugins, we can store in memory the [list of plugins' names](https://github.com/godotengine/godot/blob/57d21ebeda8460036efac1f70cd9ecd0896de517/platform/android/export/export.cpp#L774) used in the last build, and compare with the current build.

**Comment by mbrlabs** [comment]
Right, i didn't consider the plugin's dependencies. Your solution sould be easy to implement. I'm going to have a shot at it tomorrow. 

Concerning the check for enabled/removed plugins: I thought about doing it in-memory at first as well, but then went for the logfile checks because it's not garanteed that the user made a build before enabling/disabling plugins in the editor...so it might not be in memory.

**Comment by m4gr3d** [comment]
> Concerning the check for enabled/removed plugins: I thought about doing it in-memory at first as well, but then went for the logfile checks because it's not garanteed that the user made a build before enabling/disabling plugins in the editor...so it might not be in memory.

In that scenario, we can just default to having a `clean` build similarly to the logic you have when unable to open the log files. 
In practice, this should only affect the first build after the editor has been opened. It seems like good practice to always have the first build be a `clean` build.

**Comment by mbrlabs** [comment]
@m4gr3d Done.
One thing tough: It's not possible to check the modification time of a folder (at least not in Windows) if no files have been added/removed directly, so instead of checking a particular file i used an in-memory `last_custom_build_time` field which is initially set to 0 and also makes sure that the first build is always a clean build.

**Comment by mbrlabs** [comment]
I don't know whats going on with the static analysis checks. The last time i updated this PR was because Clang wanted spaces between the comments and values and now i should remove them again?

File: platform/android/export/export.cpp [hunk 1]
```diff
@@ -1874,11 +1876,28 @@ class EditorExportPlatformAndroid : public EditorExportPlatform {
...
+				for (int i = 0; i < enabled_plugins.size(); i++) {
+					if (enabled_plugins.get(i).last_updated > last_custom_build_time) {
+						clean_build_required = true;
+						break;
+					}
+				}
+			}
+			last_custom_build_time = OS::get_singleton()->get_unix_time();
+			last_plugin_names = plugin_names;
+
```
Comment (m4gr3d) [inline platform/android/export/export.cpp:1896]: Nice implementation! Can you wrap the logic into an `inline` method. Since the surrounding method is frequently updated, this will ensure this logic is not inadvertently modified.

**Review by m4gr3d — COMMENTED** [review]
Looks good! I've added one minor cleanup comment and it should be good to go.

One thing to notice though is that if the user doesn't use plugins, then the first build won't be a `clean` build.
We could change that by checking if `last_custom_build_time == 0` and triggering the `clean` build flag, but that may be overkill.
I don't have a preference either way so I'm opened to suggestions.

File: platform/android/export/export.cpp (hunk 1 above)
Comment (mbrlabs) [reply platform/android/export/export.cpp:1896]: Thanks! Yes, will do.

**Comment by mbrlabs** [comment]
> One thing to notice though is that if the user doesn't use plugins, then the first build won't be a `clean` build.
> We could change that by checking if `last_custom_build_time == 0` and triggering the `clean` build flag, but that may be overkill.
> I don't have a preference either way so I'm opened to suggestions.

Checking for  `last_custom_build_time == 0` should be fine.

**Comment by mbrlabs** [comment]
Alright, i pushed the changes. CI checks should be fixed now as well i hope :)

File: platform/android/export/export.cpp [hunk 2]
```diff
@@ -1831,6 +1833,25 @@ class EditorExportPlatformAndroid : public EditorExportPlatform {
 		return list;
 	}
 
+	inline bool is_clean_build_required(Vector<PluginConfig> enabled_plugins) {
+		bool first_build = last_custom_build_time == 0;
```
Comment (m4gr3d) [inline platform/android/export/export.cpp:1837]: If `first_build` is `true`, you can skip the rest of the logic below similarly to what you do when `have_plugins_changed` is `true`.

**Review by m4gr3d — CHANGES_REQUESTED** [review]

File: platform/android/export/export.cpp (hunk 2 above)
Comment (mbrlabs) [reply platform/android/export/export.cpp]: Done.

**Review by m4gr3d — APPROVED** [review]
Looks great!

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.
