### PR TITLE
Automatically go up if current dir was deleted

### LINKED ISSUE #19022: Stuck in the removed directory in scene selection dialogbox
**Godot version:**
228b09b

**OS/device including version:**
Windows 7 64 bit

**Issue description:**
Stuck in the removed directory in scene selection dialogbox (open, instance, add autoload, etc)

**Steps to reproduce:**
1. In any project create a new directory 'test' in Godot's file manager
2. Select 'Scene->Open Scene...'; navigate to 'test' directory and click 'Cancel'
3. Remove 'test' directory
4. Select 'Scene->Open Scene...' => stuck in the removed directory ("Go to parent folder" doesn't work), but can exit by changing text in path bar

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #19022

### CODE REVIEW

File: editor/editor_file_dialog.cpp [hunk 1]
```diff
@@ -121,6 +121,11 @@ void EditorFileDialog::_notification(int p_what) {
 		if (!is_visible()) {
 			set_process_unhandled_input(false);
 		}
+	} else if (p_what == NOTIFICATION_WM_WINDOW_FOCUS_IN) {
+		// Check if the current directory was removed externally (much less likely to happen while editor window is focused).
+		while (!dir_access->dir_exists(get_current_dir())) {
+			_go_up();
+		}
```
Comment (timothyqiu) [inline editor/editor_file_dialog.cpp:128]: I wonder if this would become an infinite loop. e.g. You were somewhere in Windows `E:` drive, but later the drive is  removed?

Comment (KoBeWi) [reply editor/editor_file_dialog.cpp:128]: I though about that and didn't considered that a drive can indeed be removed. The problems is where to go when this happens?

Comment (akien-mga) [reply editor/editor_file_dialog.cpp:128]: I guess on Windows we can expect `C:\` to always be available? Or `%USERPROFILE%`?

Comment (timothyqiu) [reply editor/editor_file_dialog.cpp:128]: The drives available can be retrieved with `get_drive_count()` and `get_drive(n)`. Maybe just try them one by one.

Comment (KoBeWi) [reply editor/editor_file_dialog.cpp]: Added fallback to user directoy. I can't test if it works though, I don't have external drive and deleting project directory with project open is impossible on Windows.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.
