### PR TITLE
Fix LineEdit expanding to text length

### LINKED ISSUE #77474: LineEdit with expand_to_text_length don't fits content size perfectly
### Godot version

4.0.2.stable.official [7a0977ce2]

### System information

Windows 10

### Issue description

LineEdit node with enabled "expand_to_text_length" option and "minimum_character_width = 0" and cleared margins in style overrides still has some empty space inside
node
node settings
style overrides

### Steps to reproduce

1. Add LineEdit node
2. Set expand_to_text_length = true
3. Set minimum_character_width in theme overrides = 0
4. Set normal to StyleBoxEmpty

### Minimal reproduction project

[LineEdit can't be zero sized.zip](https://github.com/godotengine/godot/files/11566017/LineEdit.can.t.be.zero.sized.zip)

### PR DESCRIPTION
**Pull request by Igorrreha**
Fix #77474

### CODE REVIEW

**Comment by AThousandShips** [comment]
Can you add some screenshots to compare with the results in the issue report? Preferably with the caret at the end to see how well it fits

Also needs to be tested with various fonts as mentioned on the previous PR

File: scene/gui/line_edit.cpp [hunk 1]
```diff
@@ -1774,10 +1774,10 @@ Size2 LineEdit::get_minimum_size() const {
 	// Minimum size of text.
 	float em_space_size = font->get_char_size('M', font_size).x;
 	min_size.width = theme_cache.minimum_character_width * em_space_size;
-
+
```
Comment (akien-mga) [inline scene/gui/line_edit.cpp:1777]: You added a tab on this empty line, which conflicts with our style guide. See https://docs.godotengine.org/en/latest/contributing/development/code_style_guidelines.html#using-clang-format-locally

**Comment by Igorrreha** [comment]
https://github.com/godotengine/godot/pull/77507#issuecomment-1564055109

I need to build Godot Editor from my branch for test this fix, right?
Can you help me, please (this is my first contribution)

**Comment by AThousandShips** [comment]
See [here](https://docs.godotengine.org/en/latest/contributing/development/index.html)

**Comment by Igorrreha** [comment]
https://github.com/godotengine/godot/pull/77507#issuecomment-1564080709
@AThousandShips 

With focus stylebox:
https://github.com/godotengine/godot/assets/23380802/2f8b160d-df4c-42f7-93bc-1cc18f0a18a1

Without focus stylebox
https://github.com/godotengine/godot/assets/23380802/f2a7933e-11d9-4374-8919-b891cf29405b

**Comment by AThousandShips** [comment]
Feels very cramped to me like that tbh

**Comment by Igorrreha** [comment]
The same with default style: (no spaces)
with_default_style

**Comment by Igorrreha** [comment]
Do you see any visual issues here?

**Comment by AThousandShips** [comment]
That is less cramped imo

**Comment by Igorrreha** [comment]
Example with margine
another_example

File: scene/gui/line_edit.cpp [hunk 2]
```diff
@@ -1777,7 +1777,7 @@ Size2 LineEdit::get_minimum_size() const {
 
 	if (expand_to_text_length) {
 		// Add a space because some fonts are too exact, and because caret needs a bit more when at the end.
```
Comment (akien-mga) [inline scene/gui/line_edit.cpp:1779]: It's no longer a "space" technically, but the width of the caret, so this might need a slight rewording.
```suggestion
		// Ensure some space for the caret when placed at the end.
```

**Comment by akien-mga** [comment]
Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by Igorrreha** [comment]
@akien-mga did I do everything right?

**Comment by AThousandShips** [comment]
You need to squash all your commits into one, see the instructions

**Comment by Igorrreha** [comment]
@AThousandShips, @akien-mga, thanks for help) Commits are squashed now

**Comment by Igorrreha** [comment]
@akien-mga, can you finish review, please?

**Comment by akien-mga** [comment]
@Igorrreha it looks fine to me, but I'm waiting for @bruvzg's OK as he's the one working the most closely on text related nodes and servers.

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Congratulations! Good work and first contribution!

**Comment by Igorrreha** [comment]
Thanks guys ;)
