### PR TITLE
Fix memory management for ColorPalette in save file dialog

### LINKED ISSUE #113556: Crash when saving color palettes from ColorPicker
### Tested versions

Reproducible in: v4.6.dev.custom_build [63e14e13f]
Not reproducible in: 4.6.dev5

### System information

Godot v4.6.dev (63e14e13f) - Arch Linux #1 SMP PREEMPT_DYNAMIC Mon, 24 Nov 2025 15:21:09 +0000 on X11 - X11 display driver, Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3060 Ti (nvidia; 580.105.08) - 13th Gen Intel(R) Core(TM) i5-13400F (16 threads) - 15.37 GiB memory

### Issue description

You can save swatches in a color picker as a color palette in the editor.

However, saving it crashes the editor.

https://github.com/user-attachments/assets/d402b5cd-fbe8-4c98-a926-448b695b654f

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.6.dev.custom_build (63e14e13f972671a43abcf019962129e5cca7d01)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x3e4d0) [0x7fe5bb83e4d0] (??:0)
[2] vtable for __cxxabiv1::__si_class_type_info (??:0)
-- END OF C++ BACKTRACE --
================================================================
```

### Steps to reproduce

1. Find a color picker in the editor. For example, clicking Color properties in the inspector.
2. Make sure there is at least a swatch in it so the palette can be saved.
3. In the three-dots menu beside "Swatches", click Save.
4. The Save Palette dialog appears.
5. Try clicking Save.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by MattiaZir**
Using `Ref<T>`  instead of creating a raw pointer seems to have fixed #113556.

### CODE REVIEW

File: scene/gui/color_picker.cpp [hunk 1]
```diff
@@ -974,7 +974,7 @@ void ColorPicker::_palette_file_selected(const String &p_path) {
 #endif
 		} break;
 		case FileDialog::FileMode::FILE_MODE_SAVE_FILE: {
-			ColorPalette *palette = memnew(ColorPalette);
+			Ref<ColorPalette> palette = memnew(ColorPalette);
```
Comment (KoBeWi) [inline scene/gui/color_picker.cpp]:
```suggestion
			Ref<ColorPalette> palette;
			palette.instantiate();
```

Comment (MattiaZir) [reply scene/gui/color_picker.cpp]: Done!

**Review by KoBeWi — APPROVED** [review]

**Comment by KoBeWi** [comment]
The commits need to be squashed.

**Comment by MattiaZir** [comment]
Done, thank you again!

**Comment by akien-mga** [comment]
Thanks!
