### PR TITLE
Mention version compatibility when there are no results in the assetlib

### LINKED ISSUE #36469: AssetLib does not load in 4.0
**Clarification**: Is this because there is an issue in 4.0 or because there are no Assets made yet for 4.0?

**Godot version:**
Godot Engine v4.0.dev.custom_build.f2d8c4eb8

**OS/device including version:**
Linux Mint 19.3

**Issue description:**
AssetLib loads fine in 3.2
image

> No results for ""

in latest master

image

**Steps to reproduce:**
Open AssetLib or Templates in 4.0

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by Calinou**
This closes #36469.

### CODE REVIEW

File: editor/plugins/asset_library_editor_plugin.cpp [hunk 1]
```diff
@@ -1210,7 +1210,16 @@ void EditorAssetLibrary::_http_request_completed(int p_status, int p_code, const
 			library_vb->add_child(asset_bottom_page);
 
 			if (result.empty()) {
-				library_error->set_text(vformat(TTR("No results for \"%s\"."), filter->get_text()));
+				if (filter->get_text() != String()) {
+					library_error->set_text(
+							vformat(TTR("No results for \"%s\" compatible with Godot %s."), filter->get_text(), String(VERSION_BRANCH)));
```
Comment (akien-mga) [inline editor/plugins/asset_library_editor_plugin.cpp]: I'm not sure I would put the version number here, I fear it might be jarring to users. They might wonder if they should change something to get access to the compatible results.

It's good to have in the "no content at all" case though.

**Comment by akien-mga** [comment]
Thanks!
