### PR TITLE
Fix texture atlas import deadlock by keeping `group_file=` on failed `import_file()` attempts

### LINKED ISSUE #104796: Stuck when importing project
### Tested versions

4.4.1stable

### System information

Win10 

### Issue description

Stuck when importing project

### Steps to reproduce

Download the project: https://github.com/Jamsers/Bistro-Demo-Tweaked
open it in Godot.

### Minimal reproduction project (MRP)

https://github.com/Jamsers/Bistro-Demo-Tweaked

### PR DESCRIPTION
**Pull request by isaaccp**
The problem is that when a texture_atlas resource is loaded during startup (e.g. because it's referenced by an autoload) using _load_resource_on_startup(), we always call _reimport_file() even if the resource has a group_file= attribute.

This causes _reimport_file() to drop the group_file= and when reimport_files() is called later it causes the deadlock as detailed below and in the issue linked.

I was wondering whether we could try to instead update _load_resource_on_startup() so it's aware of group_file, but at that point the filesystem hasn't been scanned yet, so it doesn't seem possible to find all the files in the group.

Instead, this PR makes it so _reimport_file() doesn't drop the group_file= attribute when import fails during startup. This allows the file to be loaded as part of the group in reimport_files().

Without group_file= set, this actually causes a deadlock in the editor as the ResourceImporterTextureAtlas::import() call attempts to use the rendering server while the main thread is waiting on a semaphore for imports to finish.

This fixes #104796 (verified locally), which has more details about the issue.

### CODE REVIEW

**Comment by isaaccp** [comment]
Updated the PR against current head (as editor_file_system.cpp was moved to a new directory).

**Review by KoBeWi — APPROVED** [review]

File: editor/file_system/editor_file_system.cpp [hunk 1]
```diff
@@ -2918,7 +2923,9 @@ Error EditorFileSystem::_reimport_file(const String &p_file, const HashMap<Strin
 		}
 
 		f->store_line("uid=\"" + ResourceUID::get_singleton()->id_to_text(uid) + "\""); // Store in readable format.
-
+		if (!group_file.is_empty()) {
+			f->store_line("group_file=\"" + group_file + "\"");
+		}
```
Comment (AThousandShips) [inline editor/file_system/editor_file_system.cpp:2928]:
```suggestion
		}

```
Keep for readability

Comment (isaaccp) [reply editor/file_system/editor_file_system.cpp:2928]: Done.

**Comment by Repiteo** [comment]
Thanks!
