### PR TITLE
[3.5] Fix broken TileSet Navigation due to wrong NavigationPolygon format

### LINKED ISSUE #30883: Navigation2D Using Tileset With Corners
**Godot version:**
3.1.1

**OS/device including version:**
Win 10/AMD Radeon R9 200 Series

**Issue description:**
After having created a tileset, and placing navigation polygons that only partially take up those tiles, it seems that corners are causing `get_simple_path` to return no solution. I've verified that the tiles line up exactly in the tileset and editor, and also that the nav polygons do as well.
When enabling navigation debug drawing, I've noticed an odd artifact that I believe may be responsible for causing the undesired behavior, but am unsure as to what is causing this artifact.

Successful case
tilemap-pathfinding-bug-3

Artifact in-game
tilemap-pathfinding-bug-4

Configured tilemap
tilemap-pathfinding-bug-1

Failing case
tilemap-pathfinding-bug-2

**Steps to reproduce:**
- Configure tilemap with corners
- Draw navigation polys
- Attempt to use `get_simple_path` across corner tile

**Minimal reproduction project:**
[bug-repro.zip](https://github.com/godotengine/godot/files/3438754/bug-repro.zip)

### LINKED ISSUE #41349: Navigation2D on TileMap passes over non-navigation area
**Godot version:**
3.2.2 Stable

**OS/device including version:**
macOS

**Issue description:**
If you have a turn in the navigation area in a tile, the Navigation2D ignores it and tries to move straight through it instead of going around the turn.

**Steps to reproduce:**
Have a turn in the navigation area in a tile, run get_simple_path() on the Navigation2D and you will get a straight line instead of a turn.

**Minimal reproduction project:**
[Bug Showcase.zip](https://github.com/godotengine/godot/files/5089464/Bug.Showcase.zip)
This projects has a Line2D draw the path of Navigation2D from get_simple_path(). Notice that the navigation area in the tile has a bend.

### LINKED ISSUE #43079: Pathfinder and 2D isometric tilemaps dont find path between side cells
**Godot version:** 3.2.2.stable

**OS/device including version:** Manjaro / Nvidia Rtx 3090 / Core I9 / 64GB

**Issue description:**

I am configuring the Navigation2D node in my project, which is using a TileMap node configured for isometric visualization. When debugging, I realized that it only generates its way on the tile where it is already positioned, never to other places.

I've tried to increase the size of the navigation borders in the tilemaps editor, but it just doesn't work.
I tried to make the mesh match perfectly, and it didn't work.

**Steps to reproduce:**

Create a Navigation2D node and add a TileMap as a child.
Configure the tilemap through the TileMap editor.
Debug with a Line2D the path generated by Navigation2D

Peek 25-10-2020 14-25

image

image

```gdscript
extends Line2D

onready var nav : Navigation2D = get_parent() as Navigation2D
onready var player : Node2D = get_parent().get_node("Player") as Node2D
func _ready():
	InputBehavior.connect("clicked", self, "_input_clicked")

func _input_clicked(position : Vector2) -> void:
	points = nav.get_simple_path(nav.get_closest_point(player.get_global_transform().get_origin()), nav.get_closest_point(position))

```

```gdscript
extends Camera2D


func _input(event):
	if event is InputEventMouseButton and not event.pressed:
		InputBehavior.clicked(get_global_mouse_position())
```

### LINKED ISSUE #45045: Overlapping navigation tiles do not pathfind with Navigation2D
**Godot version:** 3.2.3

**OS/device including version:** Windows 10 Version 10.0.19042 Build 19042
Not really graphic related, I'll add if needed.

**Issue description:** 

When configuring a Navigation2D Node using a TileMap node, `get_simple_path` does not pathfind between tiles that have overlapping navigation polygons.

This is an issue especially with hexagonal or isometric tilemap.
A workaround is to have pixel-perfect navigation polygons, but this quite bothersome when lots of different tiles are involved.

**Steps to reproduce:**
Create a Navigation2D node and add a TileMap as a child.
Configure the tilemap through the TileMap editor, set the navigation polygon (or grid) to overlap between nearby tiles.
Debug with a Line2D the path generated by Navigation2D

**Minimal reproduction project:**

[MinimalBroken.zip](https://github.com/godotengine/godot/files/5791626/MinimalBroken.zip)

The project is setup with an hexagonal grid. Each tile has a rectangular navigation polygon that overlap between the top and bottom rows. The line2D shows the plotted path. You can see that it can pathfind easily in the row (because navigation polygons do not overlap) but not between rows.
You can see the polygon by ticking debug>"View Navigation".

**Sidenote:**
Related to #43079, which was closed by its owner without reasons.

### PR DESCRIPTION
**Pull request by smix8**
This is targeting 3.5 to fix very old and persistent 2D navigation bugs in 3.x TileSets.
The entire tileeditor has a full rework in Godot 4.0 that, as far as I am aware, has not copied this issue over to Godot 4.0.

Since this pr would change how NavigationPolygon resources are created and stored by TileSets this would be a breaking change to old navigation tilesets but imo necessary for at least 3.5 with the new NavigationServer introduced.

TileSets created and stored NavigationPolyons in a format that did not work for Navigation or if fixed displayed the NavigationPolygon wrong in the TileSetEditor. This problem was not so noticeable on simple square grids but as soon as users would try to create more complex shapes around corners the navigation polygon would break and navigation would create ugly paths.

tilsetpolygon

I was able to get the TileSet navigation with not simple square shapes working again for the NavigationServer in 3.5 and also make it display correct in the Editor. I might have missed something as 2D and especially the TileEditor is not my forte and I could not figure out some parts e.g. the undo_redo part at FIXME that I commented out so help is welcome.

tilesetnavbug

Still, not everything is solved for 2D tileset navigation with this. There seems to be a lot of issues in the outdated 2D NavigationServer 3.5 backport related to 2D edge merging that were fixed by groud in Godot 4.0 e.g. I could barely get same edges to merge but not different, shorter edges while the same NavigationPolygon work perfectly in Godot 4.0 but this should be a different topic.

Fixes #30883
Fixes #41349
Fixes #45045
Fixes #43079
and a ton of other duplicates and 2D navigation issues that I randomly sighted but forgot to bookmark while digging through old 2D navigation issues.

### CODE REVIEW

**Comment by smix8** [comment]
Note that without upgrading the 3.5 navigation backport with another backport of #47024 the navmesh edges will still not merge in many cases.

File: editor/plugins/tile_set_editor_plugin.cpp [hunk 1]
```diff
@@ -2808,11 +2812,14 @@ void TileSetEditor::draw_polygon_shapes() {
 							colors.push_back(c_bg);
 						}
 					} else {
-						PoolVector<Vector2> vertices = shape->get_vertices();
-						for (int j = 0; j < shape->get_polygon(0).size(); j++) {
-							polygon.push_back(vertices[shape->get_polygon(0)[j]] + anchor);
-							colors.push_back(c_bg);
+						for (int outline_inx = 0; outline_inx < shape->get_outline_count(); outline_inx++) {
```
Comment (akien-mga) [inline editor/plugins/tile_set_editor_plugin.cpp:2815]: We use `idx` throughout the codebase whenever an abbreviation for `index` is needed.

File: editor/plugins/tile_set_editor_plugin.cpp [hunk 2]
```diff
@@ -1665,16 +1665,20 @@ void TileSetEditor::_on_workspace_input(const Ref<InputEvent> &p_ie) {
...
-										undo_redo->add_undo_method(edited_navigation_shape.ptr(), "clear_polygons");
-										undo_redo->add_do_method(edited_navigation_shape.ptr(), "add_polygon", indices);
-										undo_redo->add_undo_method(edited_navigation_shape.ptr(), "add_polygon", edited_navigation_shape->get_polygon(0));
-										undo_redo->add_do_method(this, "_select_edited_shape_coord");
-										undo_redo->add_undo_method(this, "_select_edited_shape_coord");
-										undo_redo->commit_action();
+										edited_navigation_shape->clear_outlines();
+										edited_navigation_shape->add_outline(polygon);
+										edited_navigation_shape->make_polygons_from_outlines();
+										// FIXME Couldn't figure out the undo_redo quagmire
```
Comment (akien-mga) [inline editor/plugins/tile_set_editor_plugin.cpp:1671]: Maybe @KoBeWi can help?

Comment (KoBeWi) [reply editor/plugins/tile_set_editor_plugin.cpp:1671]: I don't know the exact methods, but probably something like
```C++
undo_redo->create_action(TTR("Edit Navigation Polygon"));
undo_redo->add_do_method(edited_navigation_shape.ptr(), "clear_outlines");
undo_redo->add_do_method(edited_navigation_shape.ptr(), "add_outline", polygon);
undo_redo->add_do_method(edited_navigation_shape.ptr(), "make_polygons_from_outlines");
undo_redo->add_undo_method(edited_navigation_shape.ptr(), "clear_outlines");
for (int i = 0; i < edited_navigation_shape->get_polygon_count(); i++) {
    undo_redo->add_undo_method(edited_navigation_shape.ptr(), "add_polygon", edited_navigation_shape->get_polygon(i));
}
undo_redo->commit_action();
```

Comment (smix8) [reply editor/plugins/tile_set_editor_plugin.cpp:1671]: Thanks, I tested this but it seems something is still missing. It does not go back to previous state on undo only visually deletes it.

Comment (akien-mga) [reply editor/plugins/tile_set_editor_plugin.cpp:1671]: This code looks similar to that one, maybe it can do something similar?
https://github.com/godotengine/godot/blob/1bac95b1669ed6faf17958e76a8946a88487548b/editor/plugins/tile_set_editor_plugin.cpp#L2994-L3010

Notably, it looks like the methods called on `edited_navigation_shape` don't need to be in the undo redo, it's `edited_navigation_shape` itself which is used in the `do` methods.

**Review by akien-mga — APPROVED** [review]
Let's merge as is to fix the bug and we can figure out the UndoRedo later.

**Comment by akien-mga** [comment]
Thanks!
