### PR TITLE
Fix lightmapper seam blending

### LINKED ISSUE #91614: LightmapGI: Stripes on curved surfaces
### Tested versions

v4.3.dev6.official [89850d553]

### System information

Godot v4.3.dev6 - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

I'm getting weird stripes when baking some geometry with LightmapGI and I can't get rid of them by tweaking any settings.

I first reported this in https://github.com/godotengine/godot/issues/90929 but I'm opening a separate issue for this as suggested by @lander-vr, because this seems to be a separate issue

image

image

### Steps to reproduce

MRP

### Minimal reproduction project (MRP)

[MRP_lightmap_stripes.zip](https://github.com/godotengine/godot/files/15292112/MRP_lightmap_stripes.zip)

### PR DESCRIPTION
**Pull request by passivestar**
Closes #91614

| Before  | After |
| ------------- | ------------- |
| before  | after |

### CODE REVIEW

File: modules/lightmapper_rd/lightmapper_rd.cpp [hunk 1]
```diff
@@ -428,6 +428,7 @@ void LightmapperRD::_create_acceleration_structures(RenderingDevice *rd, Size2i
 					SWAP(edge.a, edge.b);
 					SWAP(edge.na, edge.nb);
 					SWAP(uv2.a, uv2.b);
+					SWAP(uv2.indices.x, uv2.indices.y);
```
Comment (akien-mga) [inline modules/lightmapper_rd/lightmapper_rd.cpp:431]: A wise man once told me:

> [wouldn't be surprised if it's a one line fix tbh](https://twitter.com/passivestar_/status/1790018831018021348)

Comment (passivestar) [reply modules/lightmapper_rd/lightmapper_rd.cpp:431]: _Narrator:_ "It was."

**Comment by BlueCube3310** [comment]
Does this also fix #90929?

**Comment by passivestar** [comment]
> Does this also fix https://github.com/godotengine/godot/issues/90929?

This fixes a specific bug with vertex index mismatch that caused super sharp stripes when blending seams

I believe https://github.com/godotengine/godot/pull/91601 improved the situation with light leaks that are denoider-related

But there's still lots of room for improvement after our 2 fixes

**Review by Calinou — COMMENTED** [review]
Tested locally, this doesn't appear to do much against the seams in the Global Illumination demo project:

Before | After *(this PR)*
-|-
Screenshot_20240515_185503 | Screenshot_20240515_190512

**Testing project:** [global_illumination.zip](https://github.com/godotengine/godot/files/15324761/global_illumination.zip) (bake the *LightmapGIAll* node)

**Comment by BlueCube3310** [comment]
These ones seem to be caused by the lightmap UVs being too small and packed too tightly, making the texture bleed onto its neighbours.

**Comment by passivestar** [comment]
> this doesn't appear to do much against the seams in the Global Illumination demo project

yeah because those aren't caused by wrong vertex indeces. There's more than one issue with lightmaps

If I had to guess those are most likely due to wrong UV offset calculation during seam blending

**Review by clayjohn — APPROVED** [review]
Looks great for a Yolo merge before Beta. 

For context, that code block swaps all the other properties, so the change makes intuitive sense and the results speak for themselves

File: modules/lightmapper_rd/lightmapper_rd.cpp (hunk 1 above)
Comment (fire) [reply modules/lightmapper_rd/lightmapper_rd.cpp:431]: Narrator: "And just like that, the issue was resolved. A single line of code, the smallest of changes, had made all the difference."

**Review by fire — APPROVED** [review]

**Comment by permelin** [comment]
I was so happy that I found the bug, only to see now that you beat me to it. (Why doesn't Github notify me when there's a PR that would close an issue that I'm subscribed to?)

When the bug is fixed, the blending effect is so subtle that it's difficult to be sure whether it's working or just broken to the point where it does nothing. But there are actually some seams that look smoother with it.

The left is with seam blending disabled, the right is with the fix.

blendseams-before-after

While I was debugging, I noticed that the texels that are blended often don't perfectly line up with the actual seam. But that is a completely different issue.

**Comment by passivestar** [comment]
@permelin I hope you'll beat me to fixing the bug that @Calinou pointed out because I'm not looking forward to fixing that 😂

**Comment by akien-mga** [comment]
Thanks!
