### PR TITLE
Make use of export path when exporting PCK/ZIP

### LINKED ISSUE #39769: the Export path not works when Export PCK/Zip
**Godot version:**

3.2.1

**OS/device including version:**

macOS 10.15.5

**Issue description:**

When click Export PCK/ZIP, the default directory is the project root directory, not the Export Path.

And the Export with Debug Checkbox is always checked on.

**Steps to reproduce:**
Create a project
do export for any platform
close the project
reopen the same project
 click Export PCK/ZIP
 the default directory is not the export path and the Export with Debug  is always on.

Without restarting the project,these options are recorded on export.
 

**Minimal reproduction project:**

Screen Shot 2020-06-23 at 9 45 01 AM

Screen Shot 2020-06-23 at 4 33 25 PM

### PR DESCRIPTION
**Pull request by mrushyendra**
Ensures that the directory set in `Export Path` is used as the default for the editor file dialog pop up when `Export PCK/ZIP` is selected.

Closes #39769

### CODE REVIEW

File: editor/project_export.cpp [hunk 1]
```diff
@@ -830,6 +830,17 @@ void ProjectExportDialog::_refresh_parent_checks(TreeItem *p_item) {
...
+	ERR_FAIL_COND(current.is_null());
+
+	String p_path = current->get_export_path();
+	if (p_path != "") {
+		int pos = MAX(p_path.rfind("/"), p_path.rfind("\\"));
+		if (pos != -1) {
+			String dir = p_path.substr(0, pos);
+			export_pck_zip->set_current_dir(dir);
+		}
+	}
```
Comment (akien-mga) [inline editor/project_export.cpp:843]: Isn't `p_path.get_base_dir()` sufficient?

Comment (mrushyendra) [reply editor/project_export.cpp]: Yep, you're right. That would be simpler.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
