### PR TITLE
GDScript: Improve call analysis

### LINKED ISSUE #73213: Object.new() can't be used (but it works on any Object-derived class like Node or RefCounted)
### Godot version

v4.0.rc1.official.8843d9ad3

### System information

Windows 10, Forward+, NVIDIA GeForce GTX 860M

### Issue description

cannot use Object.new()

image

### Steps to reproduce

NA

### Minimal reproduction project

NA

### LINKED ISSUE #73283: Trying to invoke un-existing static methods does not yield a parser error
### Godot version

4.0.rc1

### System information

windows 10

### Issue description

Trying to invoke un-existing static methods does not yield a parser error. Only trying to access other static members (consts and enums) does.

image

### Steps to reproduce

In any project, put the code bellow on any script. It will yield a parser error only at ```var a = MyClass.qwer``` but not at ```MyClass.myUnexistingMethod()```

```gdscript
class MyClass: pass
func test():
	MyClass.myUnexistingMethod()
	var a = MyClass.qwer

```

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by dalexeev**
* Closes #73213.
* Closes #73283.
* Add missing `UNSAFE_CALL_ARGUMENT` warning.

### CODE REVIEW

File: modules/gdscript/gdscript_warning.cpp [hunk 1]
```diff
@@ -123,7 +123,7 @@ String GDScriptWarning::get_message() const {
 		} break;
 		case UNSAFE_CALL_ARGUMENT: {
 			CHECK_SYMBOLS(4);
-			return "The argument '" + symbols[0] + "' of the function '" + symbols[1] + "' requires a the subtype '" + symbols[2] + "' but the supertype '" + symbols[3] + "' was provided";
+			return "The argument " + symbols[0] + " of the function '" + symbols[1] + "' requires a the subtype '" + symbols[2] + "' but the supertype '" + symbols[3] + "' was provided.";
```
Comment (anvilfolk) [inline modules/gdscript/gdscript_warning.cpp:126]: Is it possible to change this to `vformat` which is supposed to be faster?

**Comment by adamscott** [comment]
Notes from the GDScript meeting:

- The missing warning is a problem;
- The error message should be changed. Something like: "the function expects an int, but the value is only inferred" instead of "int (variant)";
- The formatting of DataType to string should maybe not change, or at least, this should belong in another PR.

File: modules/gdscript/gdscript_warning.cpp (hunk 1 above)
Comment (dalexeev) [reply modules/gdscript/gdscript_warning.cpp:126]: Yes, I will clean up all the warnings in a separate PR (`vformat`, double quotes, trailing dot, order).

Comment (dalexeev) [reply modules/gdscript/gdscript_warning.cpp:126]: * Done: #76412.

**Comment by dalexeev** [comment]
I removed the `DataType::to_string()` changes from this PR. In the future, we may investigate this issue separately.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 2]
```diff
@@ -4781,18 +4781,32 @@ void GDScriptAnalyzer::validate_call_arg(const List<GDScriptParser::DataType> &p
...
 		} else if (par_type.is_hard_type() && !is_type_compatible(par_type, arg_type, true)) {
 			// Supertypes are acceptable for dynamic compliance, but it's unsafe.
+#ifdef DEBUG_ENABLED
 			mark_node_unsafe(p_call);
+			String visible_arg_type = arg_type.to_string();
+			if (!arg_type.is_hard_type()) {
+				visible_arg_type = "Variant";
+			}
+			parser->push_warning(p_call->arguments[i], GDScriptWarning::UNSAFE_CALL_ARGUMENT, itos(i + 1), p_call->function_name, par_type.to_string(), visible_arg_type);
+#endif
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:4801]: I think this should be in the `else` branch of the `if` just below. There shouldn't be an error and a warning reported for the same thing at the same time.

File: modules/gdscript/gdscript_warning.cpp [hunk 3]
```diff
@@ -123,7 +123,7 @@ String GDScriptWarning::get_message() const {
 		} break;
 		case UNSAFE_CALL_ARGUMENT: {
 			CHECK_SYMBOLS(4);
-			return "The argument '" + symbols[0] + "' of the function '" + symbols[1] + "' requires a the subtype '" + symbols[2] + "' but the supertype '" + symbols[3] + "' was provided";
+			return vformat(R"*(The argument %s of the function "%s()" requires a the subtype "%s" but the supertype "%s" was provided.)*", symbols[0], symbols[1], symbols[2], symbols[3]);
```
Comment (anvilfolk) [inline modules/gdscript/gdscript_warning.cpp:126]: There's a typo in `requires a the subtype` :)

File: modules/gdscript/tests/scripts/analyzer/warnings/unsafe_call_argument.gd [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+	int_func(untyped_string)
+	int_func(variant_int)
+	int_func(variant_string)
+	int_func(typed_int) # No warning.
+
+	float_func(untyped_int)
+	float_func(untyped_string)
+	float_func(variant_int)
+	float_func(variant_string)
+	float_func(typed_int) # No warning.
```
Comment (anvilfolk) [inline modules/gdscript/tests/scripts/analyzer/warnings/unsafe_call_argument.gd:37]: This works, and we would expect `int_func(typed_float)`, to generate an error from within the inner `if` that checks for "inverted" type compatibility, right? Not just a warning. Which is why that doesn't show up in this test suite?

**Review by anvilfolk — CHANGES_REQUESTED** [review]
A small typo noticed, and needs a rebase, but is there a reason this hasn't been merged? It feels like it's good to go otherwise :)

File: modules/gdscript/tests/scripts/analyzer/warnings/unsafe_call_argument.gd (hunk 4 above)
Comment (dalexeev) [reply modules/gdscript/tests/scripts/analyzer/warnings/unsafe_call_argument.gd:37]: No, I just didn't add this test. As far as I remember, `int` (left) is compatible with `float` (right), but causes `NARROWING_CONVERSION` warning. Therefore, I think that there is no need for this test. The supertype and subtype are tested against `int` and `Variant`, I added `float_func` just to test for no false positive warning on compatible arguments.

File: modules/gdscript/gdscript_warning.cpp (hunk 3 above)
Comment (dalexeev) [reply modules/gdscript/gdscript_warning.cpp:126]: Okay, I'll fix this. :)

File: modules/gdscript/tests/scripts/analyzer/warnings/unsafe_call_argument.gd (hunk 4 above)
Comment (anvilfolk) [reply modules/gdscript/tests/scripts/analyzer/warnings/unsafe_call_argument.gd:37]: Just tested it and you are absolutely right - it does the narrowing conversion error so doesn't need to be tested here! :)

File: modules/gdscript/gdscript_warning.cpp (hunk 3 above)
Comment (dalexeev) [reply modules/gdscript/gdscript_warning.cpp]: Done.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 5]
```diff
@@ -4838,18 +4838,33 @@ void GDScriptAnalyzer::validate_call_arg(const List<GDScriptParser::DataType> &p
 
 		if ((arg_type.is_variant() || !arg_type.is_hard_type()) && !(par_type.is_hard_type() && par_type.is_variant())) {
 			// Argument can be anything, so this is unsafe.
+#ifdef DEBUG_ENABLED
 			mark_node_unsafe(p_call->arguments[i]);
```
Comment (anvilfolk) [inline modules/gdscript/gdscript_analyzer.cpp:4842]: So all of the `push_warning()` that I saw in the analyzer were protected by `DEBUG_ENABLED`, but none of the `mark_node_unsafe()` calls were. I think it might make sense to pull this one outside the `#ifdef` block here?

File: modules/gdscript/gdscript_analyzer.cpp [hunk 6]
```diff
@@ -4838,18 +4838,33 @@ void GDScriptAnalyzer::validate_call_arg(const List<GDScriptParser::DataType> &p
...
-			// Supertypes are acceptable for dynamic compliance, but it's unsafe.
-			mark_node_unsafe(p_call);
 			if (!is_type_compatible(arg_type, par_type)) {
 				push_error(vformat(R"*(Invalid argument for "%s()" function: argument %d should be "%s" but is "%s".)*",
 								   p_call->function_name, i + 1, par_type.to_string(), arg_type.to_string()),
 						p_call->arguments[i]);
+#ifdef DEBUG_ENABLED
+			} else {
+				// Supertypes are acceptable for dynamic compliance, but it's unsafe.
+				mark_node_unsafe(p_call);
```
Comment (anvilfolk) [inline modules/gdscript/gdscript_analyzer.cpp:4857]: Same thing here!

**Review by anvilfolk — CHANGES_REQUESTED** [review]
I just noticed some discrepancies in whether `mark_node_unsafe` should be protected by `#ifdef DEBUG_ENABLED` compared to existing code. I didn't do a thorough review of the analyzer, but I believe there's an existing pattern that isn't being followed here that could have unintended consequences?

File: modules/gdscript/gdscript_analyzer.cpp (hunk 5 above)
Comment (dalexeev) [reply modules/gdscript/gdscript_analyzer.cpp:4842]: https://github.com/godotengine/godot/blob/f6bf51ca49ed0073a3c34054a7ab583faff2d3ec/modules/gdscript/gdscript_analyzer.cpp#L5117-L5127

**Review by anvilfolk — APPROVED** [review]
LGTM :)

**Comment by dalexeev** [comment]
I extended this PR. Please remove the `cherrypick:4.0` label.

**Comment by santouits** [comment]
Should you remove this code too?
https://github.com/godotengine/godot/blob/e188d619227990001667821dac8bc8940076d4a9/modules/gdscript/gdscript_analyzer.cpp#L634-L638

File: modules/gdscript/gdscript_analyzer.cpp [hunk 7]
```diff
@@ -247,7 +247,7 @@ Error GDScriptAnalyzer::check_native_member_name_conflict(const StringName &p_me
 		return ERR_PARSE_ERROR;
 	}
 
-	if (GDScriptParser::get_builtin_type(p_member_name) != Variant::VARIANT_MAX) {
+	if (GDScriptParser::get_builtin_type(p_member_name) < Variant::VARIANT_MAX) {
```
Comment (adamscott) [inline modules/gdscript/gdscript_analyzer.cpp:250]: Nice catch.

**Comment by adamscott** [comment]
Moved the milestone to 4.2, as we entered yesterday the release freeze for 4.1, where only urgent bugfixes are merged. Added the "cherrypick 4.1" tag as this would be interesting to patch 4.1.x with your PR.

**Comment by adamscott** [comment]
The GDScript team thinks that this PR should be merged for 4.2. We should take a look again at this before the feature freeze.

**Review by vnen — APPROVED** [review]
Overall looks good to me.

File: modules/gdscript/tests/scripts/runtime/features/stringify.gd [hunk 8]
```diff
@@ -24,7 +24,8 @@ func test():
 	print(StringName("hello"))
 	print(NodePath("hello/world"))
 	var node := Node.new()
-	print(RID(node))
+	@warning_ignore("unsafe_call_argument")
+	print(RID(node)) # TODO: Why is the constructor (or implicit cast) not documented?
```
Comment (YuriSizov) [inline modules/gdscript/tests/scripts/runtime/features/stringify.gd:28]: What do you mean with this comment? https://docs.godotengine.org/en/stable/classes/class_rid.html#class-rid

Comment (dalexeev) [reply modules/gdscript/tests/scripts/runtime/features/stringify.gd:28]: There is no `RID(Object)` constructor (or something like this).

**Comment by YuriSizov** [comment]
Thanks!

File: modules/gdscript/tests/scripts/runtime/features/stringify.gd (hunk 8 above)
Comment (YuriSizov) [reply modules/gdscript/tests/scripts/runtime/features/stringify.gd:28]: Ah right, we should document the explicit conversion.
