### PR TITLE
Metal: Disable MetalFX Temporal for `mobile` rendering method

### LINKED ISSUE #106665: MetalFX temporal + Dof + screenreading shader breaks
### Tested versions

Godot 4.5 dev5
Godot 4.4.1 stable

### System information

MacBook Pro M1 - Sequoia 15.4.1

### Issue description

in a specific combination of settings and assets, the temporal MetalFX upscaler breaks

### Steps to reproduce

in a 3d scene, do the following: 
- enable dof on the camera
- put a mesh in front of the camera that is screen-reading
- enable MetalFX (Temporal) upscaler in the project settings with a scale factor <1.0
all of these in combination create the bug. as soon as one of them is missing, everything works

it will look like this:
Image

### Minimal reproduction project (MRP)

https://github.com/thmasn/godot-bugreport-dof

### PR DESCRIPTION
**Pull request by stuartcarnie**
Closes #106665

It isn't supported, as `mobile` can't provide motion vectors. We can revisit once motion vector support is added via #100283.

### CODE REVIEW

**Comment by Calinou** [comment]
> We can revisit once motion vector support is added via https://github.com/godotengine/godot/pull/100283.

Motion vectors added by that PR work differently from the ones in Forward+. They are rendered in a separate pass at a much lower resolution. They're intended to provide the data required for XR reprojection (asynchronous spacewarp) to work, rather than effects like TAA and motion blur.

It might be possible to make them render at the same resolution as the viewport resolution, but since it's a separate pass, this may probably end up slower than in Forward+ (due to the cost of setting up the pass). In Forward+, motion vector computations are already quite expensive: https://github.com/godotengine/godot/issues/61905

File: servers/rendering/renderer_viewport.cpp [hunk 1]
```diff
@@ -971,8 +971,10 @@ void RendererViewport::viewport_set_use_xr(RID p_viewport, bool p_use_xr) {
...
 	Viewport *viewport = viewport_owner.get_or_null(p_viewport);
 	ERR_FAIL_NULL(viewport);
-	ERR_FAIL_COND_EDMSG(p_mode == RS::VIEWPORT_SCALING_3D_MODE_FSR && OS::get_singleton()->get_current_rendering_method() != "forward_plus", "FSR1 is only available when using the Forward+ renderer.");
-	ERR_FAIL_COND_EDMSG(p_mode == RS::VIEWPORT_SCALING_3D_MODE_FSR2 && OS::get_singleton()->get_current_rendering_method() != "forward_plus", "FSR2 is only available when using the Forward+ renderer.");
+	const String rendering_method = OS::get_singleton()->get_current_rendering_method();
+	ERR_FAIL_COND_EDMSG(p_mode == RS::VIEWPORT_SCALING_3D_MODE_FSR && rendering_method != "forward_plus", "FSR1 is only available when using the Forward+ renderer.");
+	ERR_FAIL_COND_EDMSG(p_mode == RS::VIEWPORT_SCALING_3D_MODE_FSR2 && rendering_method != "forward_plus", "FSR2 is only available when using the Forward+ renderer.");
+	ERR_FAIL_COND_EDMSG(p_mode == RS::VIEWPORT_SCALING_3D_MODE_METALFX_TEMPORAL && rendering_method != "forward_plus", "MetalFX Temporal is only available when using the Forward+ renderer.");
```
Comment (Calinou) [inline servers/rendering/renderer_viewport.cpp:977]: Is MetalFX Spatial implemented in the Mobile renderer? I'm curious about it, since we don't have working FSR1 in Mobile right now. (We could probably add it, but FSR1 is rather demanding on mobile devices when it's not in tweaked form like https://github.com/godotengine/godot-proposals/issues/3786 or https://github.com/godotengine/godot-proposals/issues/10411.)

Comment (stuartcarnie) [reply servers/rendering/renderer_viewport.cpp:977]: Apple's MetalFX are also optimised for their mobile devices, so they would still be usable there, but if the motion vectors are not viable for MetalFX Temporal upscaling, then we won't use it 👍🏻

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected.

I can confirm MetalFX **Spatial** _is_ available and fully functional on the Mobile rendering method, unlike FSR 1.0 which acts like Bilinear (or the previously selected 3D scaling mode, to be precise). So this PR is good as it is.

File: servers/rendering/renderer_viewport.cpp (hunk 1 above)
Comment (akien-mga) [inline servers/rendering/renderer_viewport.cpp:977]: This starts being worth doing:
```suggestion
	if (rendering_method != "forward_plus") {
		ERR_FAIL_COND_EDMSG(p_mode == RS::VIEWPORT_SCALING_3D_MODE_FSR, "FSR1 is only available when using the Forward+ renderer.");
		ERR_FAIL_COND_EDMSG(p_mode == RS::VIEWPORT_SCALING_3D_MODE_FSR2, "FSR2 is only available when using the Forward+ renderer.");
		ERR_FAIL_COND_EDMSG(p_mode == RS::VIEWPORT_SCALING_3D_MODE_METALFX_TEMPORAL, "MetalFX Temporal is only available when using the Forward+ renderer.");
	}
```

Comment (stuartcarnie) [reply servers/rendering/renderer_viewport.cpp]: Good call – changed!

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
