### PR TITLE
Fix `emission_shape_changed` signal error when using ShaderMaterial with GPUParticles3D

### LINKED ISSUE #101679: GPUParticles3D cannot set ShaderMaterial in process_material
### Tested versions

- Reproducible in Godot Engine v4.4.beta1.official.d33da79d3

### System information

Win11 - Godot Engine v4.4.beta1.official.d33da79d3 - Vulkan 1.3.287 - Forward+

### Issue description

All project setting `GPUParticles3D.process_material` to shader causes crash.

### Steps to reproduce

```gdscript
extends GPUParticles3D


func _ready() -> void:
	self.process_material = ShaderMaterial.new()
```

Or just set in property panel

Image

which identically output following error without further information:

```text
ERROR: In Object of type 'ShaderMaterial': Attempt to connect nonexistent signal 'emission_shape_changed' to callable 'GPUParticles3D::update_gizmos'.
   at: (core/object/object.cpp:1439)
```

For plugins that provides node based on `GPUParticles3D` - opening scene containing it will immediately crash editor (i.e. [GPUTrail3D](https://github.com/celyk/GPUTrail))

### Minimal reproduction project (MRP)

refer step to reproduce, will add mre just in case but probably creating node and setting shader param will be faster than unzipping

[44beta1_gpu_trail_crash.zip](https://github.com/user-attachments/files/18454287/44beta1_gpu_trail_crash.zip)

originally was MRE for other repo so don't mind the project name.

I assume line 152 is culprit so just cloned & building godot to see if this is something I can PR myself, 
Did signal not exist or changed? I think I didn't saw in changelog

### PR DESCRIPTION
**Pull request by paddy-exe**
Fixes https://github.com/godotengine/godot/pull/100113#discussion_r1917407023

* *Bugsquad edit, fixes: https://github.com/godotengine/godot/issues/101679*

### CODE REVIEW

File: scene/3d/gpu_particles_3d.cpp [hunk 1]
```diff
@@ -149,6 +149,7 @@ void GPUParticles3D::set_process_material(const Ref<Material> &p_material) {
 	RID material_rid;
 	if (process_material.is_valid()) {
 		material_rid = process_material->get_rid();
+	} else if (cast_to<ParticleProcessMaterial>(*process_material)) {
 		process_material->connect("emission_shape_changed", callable_mp((Node3D *)this, &GPUParticles3D::update_gizmos));
 	}
```
Comment (akien-mga) [inline scene/3d/gpu_particles_3d.cpp:154]: This won't work, since the `process_material.is_valid()` condition is true, so it will never evaluate the `else if`.
It should be:
```suggestion
	if (process_material.is_valid()) {
		material_rid = process_material->get_rid();
		if (Ref<ParticleProcessMaterial>(process_material).is_valid()) {
			process_material->connect("emission_shape_changed", callable_mp((Node3D *)this, &GPUParticles3D::update_gizmos));
		}
	}
```

**Comment by akien-mga** [comment]
There are some more issues with #100113 and its follow-up #101537:
- #101537 removed the signal disconnect, but not the previous two lines which you just added to be able to disconnect the signal. These should be removed too. But I wonder: when is the signal disconnected now? What happens if you set the same ParticleProcessMaterial twice in a GPUParticles3D? Won't it error that the signal is already connected? The way we handle this usually is that the `set_process_material` setter should first check if the current material needs the signal disconnected, before assigning the new material and connecting the signal.
- The signal is emitted only in `TOOLS_ENABLED`, but this isn't documented, and there's still code like here that connects it in non-TOOLS_ENABLED builds.
- Finally there's #101611 which is why I started looking into #100113, but the above nitpicks don't seem to be what's causing the crash. I haven't had time to investigate further yet.

**Comment by paddy-exe** [comment]
Alright, I think I have solved the problem with `ShaderMaterial` and the signal connect and disconnect. Also added a documentation note in the class reference. In the `CurveEdit` class at least when setting a new curve you disconnect the signals and then re-add them to the new assigned one (see [here](https://github.com/godotengine/godot/blob/d33da79d3f8fe84be2521d25b9ba8e440cf25a88/editor/plugins/curve_editor_plugin.cpp#L59)) so I took inspiration from that.

File: scene/3d/gpu_particles_3d.cpp [hunk 2]
```diff
@@ -145,11 +145,23 @@ void GPUParticles3D::set_use_local_coordinates(bool p_enable) {
 }
 
 void GPUParticles3D::set_process_material(const Ref<Material> &p_material) {
+#ifdef TOOLS_ENABLED
+	if (process_material.is_valid()) {
+		if (cast_to<ParticleProcessMaterial>(*process_material)) {
```
Comment (AThousandShips) [inline scene/3d/gpu_particles_3d.cpp:150]:
```suggestion
		if (Object::cast_to<ParticleProcessMaterial>(*process_material)) {
```
It's a static method

File: scene/3d/gpu_particles_3d.cpp [hunk 3]
```diff
@@ -145,11 +145,23 @@ void GPUParticles3D::set_use_local_coordinates(bool p_enable) {
...
+	}
+#endif
+
 	process_material = p_material;
 	RID material_rid;
 	if (process_material.is_valid()) {
 		material_rid = process_material->get_rid();
-		process_material->connect("emission_shape_changed", callable_mp((Node3D *)this, &GPUParticles3D::update_gizmos));
+#ifdef TOOLS_ENABLED
+		if (cast_to<ParticleProcessMaterial>(*process_material)) {
```
Comment (AThousandShips) [inline scene/3d/gpu_particles_3d.cpp:161]:
```suggestion
		if (Object::cast_to<ParticleProcessMaterial>(*process_material)) {
```

**Review by Norrox — APPROVED** [review]

**Review by AThousandShips — APPROVED** [review]
Makes sense

**Review by Repiteo — APPROVED** [review]
Will be good to get this field-tested early

**Comment by Repiteo** [comment]
Thanks!
