### PR TITLE
Expression before 'is' may be null

### LINKED ISSUE #28057: Editor crash when using "match" and "is" statments together
**Godot version:**
3.1

**OS/device including version:**
Linux Mint 19 Cinnamon x64
kernel 4.15.0-47-generic
AMD Ryzen 5 2600 Six-Core Processor × 6
NVIDIA Corporation GP106 [GeForce GTX 1060 3GB] **not graphic related**, though

**Issue description:**
I don't know how to use match and "var is type" like "a is float" properly yeat, and I was exploring to see if it was possible to use match to check a type of a variable.
when writing this block of code
```gdscript
var a = 0.2
match a:
    is float:
        print("float
```

it crashes into this

```bash
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f6c8debaf20] (??:0)
[2] /home/scar/Programs/godot() [0x8c356f] (<artificial>:?)
[3] /home/scar/Programs/godot() [0x8c376c] (<artificial>:?)
[4] /home/scar/Programs/godot() [0x8c7193] (<artificial>:?)
[5] /home/scar/Programs/godot() [0x8c7474] (<artificial>:?)
[6] /home/scar/Programs/godot() [0x8c97d9] (<artificial>:?)
[7] /home/scar/Programs/godot() [0x8d0939] (<artificial>:?)
[8] /home/scar/Programs/godot() [0x8d680f] (??:?)
[9] /home/scar/Programs/godot() [0x8d700d] (??:?)
[10] /home/scar/Programs/godot() [0x8d8401] (??:?)
[11] /home/scar/Programs/godot() [0x14285cf] (<artificial>:?)
[12] /home/scar/Programs/godot() [0x1579534] (<artificial>:?)
[13] /home/scar/Programs/godot() [0xa414e9] (??:?)
[14] /home/scar/Programs/godot() [0x2174733] (??:?)
[15] /home/scar/Programs/godot() [0x21e4e02] (??:?)
[16] /home/scar/Programs/godot() [0x21e5e40] (??:?)
[17] /home/scar/Programs/godot() [0x1826c10] (??:?)
[18] /home/scar/Programs/godot() [0xa414e9] (??:?)
[19] /home/scar/Programs/godot() [0x2174733] (??:?)
[20] /home/scar/Programs/godot() [0x21e4e02] (??:?)
[21] /home/scar/Programs/godot() [0x21e5e40] (??:?)
[22] /home/scar/Programs/godot() [0x1699a01] (??:?)
[23] /home/scar/Programs/godot() [0x2129a84] (??:?)
[24] /home/scar/Programs/godot() [0x1652dde] (<artificial>:?)
[25] /home/scar/Programs/godot() [0x16cb40a] (??:?)
[26] /home/scar/Programs/godot() [0xaf1220] (??:?)
[27] /home/scar/Programs/godot() [0x7b28ed] (??:?)
[28] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f6c8de9db97] (??:0)
[29] /home/scar/Programs/godot() [0x7bfc4e] (??:?)
-- END OF BACKTRACE --
```

**Steps to reproduce:**

**Minimal reproduction project:**
write the code discribed above in the `func _ready():` of a script

### LINKED ISSUE #31055: Script editor crash checking type for Object while typing
**Godot version:**
3.1-stable, 3.2-dev 4d08f72b7

**OS/device including version:**
Windows 10

**Issue description:**
Editor crash while checking whether a variable extends `Object`:
```gdscript
extends Node

func _ready():
	var node = Node.new()
	if node is Object: # remove `node`
		pass
```
```
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] GDScriptParser::_reduce_expression (engine\modules\gdscript\gdscript_parser.cpp:1602)
[1] GDScriptParser::_reduce_expression (engine\modules\gdscript\gdscript_parser.cpp:1602)
[2] GDScriptParser::_reduce_expression (engine\modules\gdscript\gdscript_parser.cpp:1681)
[3] GDScriptParser::_parse_and_reduce_expression (engine\modules\gdscript\gdscript_parser.cpp:1988)
[4] GDScriptParser::_parse_block (engine\modules\gdscript\gdscript_parser.cpp:2876)
[5] GDScriptParser::_parse_class (engine\modules\gdscript\gdscript_parser.cpp:3911)
[6] GDScriptParser::_parse (engine\modules\gdscript\gdscript_parser.cpp:8273)
[7] GDScriptParser::parse (engine\modules\gdscript\gdscript_parser.cpp:8379)
[8] GDScriptLanguage::validate (engine\modules\gdscript\gdscript_editor.cpp:123)
[9] ScriptTextEditor::_validate_script (engine\editor\plugins\script_text_editor.cpp:544)
[10] MethodBind0<ScriptTextEditor>::call (engine\core\method_bind.gen.inc:149)
[11] Object::call (engine\core\object.cpp:933)
[12] Object::emit_signal (engine\core\object.cpp:1233)
[13] Object::emit_signal (engine\core\object.cpp:1290)
[14] CodeTextEditor::_text_changed_idle_timeout (engine\editor\code_editor.cpp:1445)
[15] MethodBind0<CodeTextEditor>::call (engine\core\method_bind.gen.inc:149)
[16] Object::call (engine\core\object.cpp:933)
[17] Object::emit_signal (engine\core\object.cpp:1233)
[18] Object::emit_signal (engine\core\object.cpp:1290)
[19] Timer::_notification (engine\scene\main\timer.cpp:61)
[20] Timer::_notificationv (engine\scene\main\timer.h:38)
[21] Object::notification (engine\core\object.cpp:945)
[22] SceneTree::_notify_group_pause (engine\scene\main\scene_tree.cpp:975)
[23] SceneTree::idle (engine\scene\main\scene_tree.cpp:518)
[24] Main::iteration (engine\main\main.cpp:1935)
[25] OS_Windows::run (engine\platform\windows\os_windows.cpp:3038)
[26] widechar_main (engine\platform\windows\godot_windows.cpp:162)
[27] _main (engine\platform\windows\godot_windows.cpp:184)
[28] main (engine\platform\windows\godot_windows.cpp:196)
[29] __scrt_common_main_seh (f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[30] BaseThreadInitThunk
```

**Steps to reproduce:**
Try to remove `node` from the snippet:
script_cast_object

**Minimal reproduction project:**
[script-cast-object.zip](https://github.com/godotengine/godot/files/3463896/script-cast-object.zip)

### PR DESCRIPTION
**Pull request by creikey**
Fixes #31055 and fixes #28057.

### CODE REVIEW

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -898,6 +898,10 @@ GDScriptParser::Node *GDScriptParser::_parse_expression(Node *p_parent, bool p_s
 
 		} else if (tokenizer->get_token() == GDScriptTokenizer::TK_PR_IS && tokenizer->get_token(1) == GDScriptTokenizer::TK_BUILT_IN_TYPE) {
 			// 'is' operator with built-in type
+			if (!expr) {
+				_set_error("No identifier provided for is operator");
```
Comment (akien-mga) [inline modules/gdscript/gdscript_parser.cpp]: Maybe enclose "is" in single quotes? Otherwise might read as a broken sentence.
Probably worth adding a trailing dot too, though it doesn't seem used consistently in `_set_error` calls.

Comment (creikey) [reply modules/gdscript/gdscript_parser.cpp]: @akien-mga with my latest force push I've updated the PR, commit message, and error message to include 'is' in brackets and made the error message more like the other `_set_error` error messages.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.
