### PR TITLE
Renderer: Reduce scope of mutex locks to prevent common deadlocks

### LINKED ISSUE #102877: Scenes can't be fully loaded and Godot freezes
### Tested versions

- Reproducible in: v4.4.beta.gh [b607110ad] v4.4.beta3
- Not reproducible in: v4.4.beta1 v4.4.beta2

### System information

Godot v4.4.beta (b607110ad) - Windows 10 (build 19045) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 960 - AMD FX(tm)-6300 Six-Core Processor (6 threads)

### Issue description

In the TPS Demo project, when pressing play on the main menu, Godot finishes the loading bar but then stops responding.
Image

Note 1: In beta 1 and 2, it also freezes but eventually responds after a few seconds.

### Steps to reproduce

- Open TPS Demo.
- Press play.

### Minimal reproduction project (MRP)

https://github.com/godotengine/tps-demo

### PR DESCRIPTION
**Pull request by stuartcarnie**
Fixes #102877

Introduces fine-grained locking to `ShaderRD`, so that each version has its own lock, making `ShaderRD` version APIs thread safe. 

> [!NOTE]
>
> It is expected that one of the `initialize` APIs are called prior to querying version, which is a requirement. The `initialize` APIs mutate some of the state, after which point it is read-only.

Additional changes to `BaseMaterial3D` and `MaterialStorage` to extract the queued updates into a separate list (non-allocating) and then releases the lock. This is to ensure that any shader updates are not performed under the shared locks of `BaseMaterial3D` and `MaterialStorage`.

Now that accessing shader versions of `ShaderRD` is thread-safe, we remove a number of calls to the shared mutex in `SceneShaderForwardClustered` when querying shader versions, which was a source of many deadlocks.

`ShaderRD` no longer uses a separate named `WorkerThreadPool`.

> [!NOTE]
>
> We may want to introduce a platform-specific `Thread` implementation for Apple, so that we can increase the size of the stack for worker threads.

### CODE REVIEW

File: core/object/worker_thread_pool.cpp [hunk 1]
```diff
@@ -182,6 +182,7 @@ void WorkerThreadPool::_process_task(Task *p_task) {
 
 void WorkerThreadPool::_thread_function(void *p_user) {
 	ThreadData *thread_data = (ThreadData *)p_user;
+	Thread::set_name(vformat("WorkerThread %d", thread_data->index));
```
Comment (stuartcarnie) [inline core/object/worker_thread_pool.cpp:185]: Make it easy to find the worker threads

File: scene/resources/material.cpp [hunk 2]
```diff
@@ -684,29 +684,35 @@ void BaseMaterial3D::_update_shader() {
...
-			// Deallocate shader which is no longer in use.
-			RS::get_singleton()->free(shader_map[current_key].shader);
-			shader_map.erase(current_key);
+	{
+		MutexLock lock(shader_map_mutex);
+		if (ShaderData *v = shader_map.getptr(current_key); v) {
+			v->users--;
+			if (v->users == 0) {
+				// Deallocate shader which is no longer in use.
+				RS::get_singleton()->free(v->shader);
```
Comment (stuartcarnie) [inline scene/resources/material.cpp:693]: An improvement, as we no longer perform multiple lookups into `shader_map` too

File: scene/resources/material.cpp [hunk 3]
```diff
@@ -684,29 +684,35 @@ void BaseMaterial3D::_update_shader() {
...
 
-	current_key = mk;
+		current_key = mk;
 
-	if (shader_map.has(mk)) {
-		shader_rid = shader_map[mk].shader;
-		shader_map[mk].users++;
+		if (ShaderData *v = shader_map.getptr(mk); v) {
+			shader_rid = v->shader;
+			v->users++;
```
Comment (stuartcarnie) [inline scene/resources/material.cpp:702]: Same here – let's not perform multiple lookups into shader_map.

File: scene/resources/material.cpp [hunk 4]
```diff
@@ -1932,8 +1938,18 @@ void fragment() {)";
...
 	shader_data.shader = RS::get_singleton()->shader_create_from_code(code);
 	shader_data.users = 1;
-	shader_map[mk] = shader_data;
-	shader_rid = shader_data.shader;
+
+	MutexLock lock(shader_map_mutex);
+	if (ShaderData *v = shader_map.getptr(mk); v) {
+		// We raced and managed to sneak the same key in concurrently, so we'll destroy the one we just created,
+		// given we know it isn't used, and use the winner.
+		RS::get_singleton()->free(shader_data.shader);
```
Comment (stuartcarnie) [inline scene/resources/material.cpp:1946]: @clayjohn I had to remove this, as it caused a crash in the `List` destructor of this list, as it wasn't empty:

https://github.com/godotengine/godot/blob/324512e11c1b7663c3cf47bec6ddbe65c6b8db2b/servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.h#L291

File: scene/resources/material.cpp [hunk 5]
```diff
@@ -1959,11 +1975,18 @@ void BaseMaterial3D::_check_material_rid() {
...
+			copy.add(E);
+		}
+	}
 
-	while (dirty_materials.first()) {
-		dirty_materials.first()->self()->_update_shader();
-		dirty_materials.first()->remove_from_list();
+	while (SelfList<BaseMaterial3D> *E = copy.first()) {
+		E->self()->_update_shader();
+		copy.remove(E);
```
Comment (stuartcarnie) [inline scene/resources/material.cpp:1989]: This doesn't allocate anything, which is convenient! We just remove from the `dirty_materials` list into the local `copy`.

File: servers/rendering/renderer_rd/shader_rd.h [hunk 6]
```diff
@@ -79,8 +80,6 @@ class ShaderRD {
 		bool initialize_needed;
 	};
 
-	Mutex variant_set_mutex;
-
```
Comment (stuartcarnie) [inline servers/rendering/renderer_rd/shader_rd.h:83]: No longer needed, as we have a mutex per version.

File: servers/rendering/renderer_rd/shader_rd.h [hunk 7]
```diff
@@ -95,7 +94,9 @@ class ShaderRD {
 	void _compile_ensure_finished(Version *p_version);
 	void _allocate_placeholders(Version *p_version, int p_group);
 
-	RID_Owner<Version> version_owner;
+	RID_Owner<Version, true> version_owner;
```
Comment (stuartcarnie) [inline servers/rendering/renderer_rd/shader_rd.h:97]: Make this thread-safe now

File: servers/rendering/renderer_rd/storage_rd/material_storage.cpp [hunk 8]
```diff
@@ -2136,9 +2136,19 @@ void MaterialStorage::_material_queue_update(Material *material, bool p_uniform,
...
+		while (SelfList<Material> *E = material_update_list.first()) {
+			DEV_ASSERT(E == &E->self()->update_element);
+			material_update_list.remove(E);
+			copy.add(E);
+		}
+	}
+
+	while (SelfList<Material> *E = copy.first()) {
+		Material *material = E->self();
+		copy.remove(E);
```
Comment (stuartcarnie) [inline servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2151]: This change was necessary to limit the scope of the lock, as `update_parameters` could cause shader compilation.

**Review by stuartcarnie — COMMENTED** [review]
Left a few notes

File: scene/resources/material.cpp [hunk 9]
```diff
@@ -684,29 +684,35 @@ void BaseMaterial3D::_update_shader() {
...
-	MutexLock lock(shader_map_mutex);
-	if (shader_map.has(current_key)) {
-		shader_map[current_key].users--;
-		if (shader_map[current_key].users == 0) {
-			// Deallocate shader which is no longer in use.
-			RS::get_singleton()->free(shader_map[current_key].shader);
-			shader_map.erase(current_key);
+	{
+		MutexLock lock(shader_map_mutex);
+		if (ShaderData *v = shader_map.getptr(current_key); v) {
```
Comment (clayjohn) [inline scene/resources/material.cpp:689]:
```suggestion
		ShaderData *v = shader_map.getptr(current_key);
		if (v) {
```
We like the old fashioned style more

File: scene/resources/material.cpp [hunk 10]
```diff
@@ -684,29 +684,35 @@ void BaseMaterial3D::_update_shader() {
...
 		}
-	}
 
-	current_key = mk;
+		current_key = mk;
 
-	if (shader_map.has(mk)) {
-		shader_rid = shader_map[mk].shader;
-		shader_map[mk].users++;
+		if (ShaderData *v = shader_map.getptr(mk); v) {
```
Comment (clayjohn) [inline scene/resources/material.cpp:700]:
```suggestion
		*v = shader_map.getptr(mk);
		if ( v) {
```

File: scene/resources/material.cpp [hunk 11]
```diff
@@ -1932,8 +1938,18 @@ void fragment() {)";
 	ShaderData shader_data;
 	shader_data.shader = RS::get_singleton()->shader_create_from_code(code);
 	shader_data.users = 1;
-	shader_map[mk] = shader_data;
-	shader_rid = shader_data.shader;
+
+	MutexLock lock(shader_map_mutex);
+	if (ShaderData *v = shader_map.getptr(mk); v) {
```
Comment (clayjohn) [inline scene/resources/material.cpp:1943]:
```suggestion
	ShaderData *v = shader_map.getptr(mk);
	if (v) {
```

**Review by clayjohn — CHANGES_REQUESTED** [review]

File: scene/resources/material.cpp (hunk 2 above)
Comment (clayjohn) [reply scene/resources/material.cpp:693]: This is a great pattern that is worth using more widely. Calling `has()` is almost always a waste of cycles

File: scene/resources/material.cpp (hunk 4 above)
Comment (clayjohn) [reply scene/resources/material.cpp:1946]: Makes sense

File: scene/resources/material.cpp (hunk 9 above)
Comment (stuartcarnie) [reply scene/resources/material.cpp]: I didn't get any feedback, so I've switched to the preferred style.

**Comment by stuartcarnie** [comment]
@clayjohn I've switched to the preferred style

**Review by clayjohn — APPROVED** [review]
Thanks!

**Comment by Repiteo** [comment]
Thanks!
