### PR TITLE
Fixed Issue #68194 involving ColorPicker being allowed to align horizontally when it shouldn't

### LINKED ISSUE #68194: ColorPicker can be made horizontal and broken
### Godot version

4.0 08d56ac

### System information

Windows 10 x64

### Issue description

Unintended consequence of BoxContainer rework.

`vertical` should be hidden with `_validate_property()`, like in other subclasses of BoxContainer.

### Steps to reproduce

1. Add ColorPicker
2. Change `vertical` to `false`
3. Funny

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by jbcolli2**
Fixed the ColorPicker class to disallow the vertical checkbox option in the editor and be set to vertical by default.

This fix was implemented by making the `ColorPicker` class a subclass of `VBoxContainer` and initializing with the `VBoxContainer` constructor.

*Bugsquad edit:* Fixes #68194

### CODE REVIEW

**Comment by akien-mga** [comment]
Looks good, but the docs should be synced too with `doctool`: https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html
(Or apply the diff from https://github.com/godotengine/godot/actions/runs/3394381224/jobs/5642870378)

File: scene/gui/color_picker.cpp [hunk 1]
```diff
@@ -1530,7 +1530,7 @@ void ColorPicker::_bind_methods() {
 }
 
 ColorPicker::ColorPicker() :
-		BoxContainer(true) {
+		VBoxContainer() {
```
Comment (KoBeWi) [inline scene/gui/color_picker.cpp:1533]: Isn't this initialization unnecessary now?

Comment (jbcolli2) [reply scene/gui/color_picker.cpp:1533]: Yep, that's right.  I'll get rid of it in my next push.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by jbcolli2** [comment]
My pleasure.
