### PR TITLE
Fix action exact match (Also fixes ui_ focus keys)

### LINKED ISSUE #54602: Tab key doesn't move between editor fields in the inspector
### Godot version

4.0 dev (804406fcaf49789d4618d9c33f71d16996e95504)

### System information

Ubuntu 21.10

### Issue description

When using the editor, pressing the tab key while editing an inspector field does not appear to have any effect at all. In 3.x, tab moves between editable fields in order, as expected for a desktop app.

### Steps to reproduce

Open editor to any project (fresh or existing) -> select a node -> edit a field of the node (i.e. `transform.position`'s X/Y/Z coords) -> press tab key -> currently-selected field remains selected and editing.

### Minimal reproduction project

_No response_

### LINKED ISSUE #55622: "ui_right" and "ui_up" keys do not work for focusing neighbors
### Godot version

4.0.dev.calinou [4f298237b]

### System information

Windows 11, 1060 GT

### Issue description

As seen in the video below, both automatic and focus cannot be changed using the arrow keys (default ui controls)

https://user-images.githubusercontent.com/38346332/144704813-099bd01e-4cc0-41a8-9dba-f6fdbf1b5194.mp4

surprisingly, ui_focus_next and ui_focus_previous are fully functional. (TAB / SHIFT + TAB)

### Steps to reproduce

1. Create an empty project
3. Create buttons and put them in arbitrary locations, or in containers such as VBox/HBox/Grid
2. (optional) manually assign focus neighbors
3. run the project and click on one button
4. try to change the focused button using arrow keys (up and right do not work)

### Minimal reproduction project

[ui_focus_min.zip](https://github.com/godotengine/godot/files/7654188/ui_focus_min.zip)

### PR DESCRIPTION
**Pull request by nathanfranke**
Fixes https://github.com/godotengine/godot/issues/54602
Fixes https://github.com/godotengine/godot/issues/55622
Supersedes https://github.com/godotengine/godot/pull/54842

3.x version: https://github.com/godotengine/godot/pull/54174

Previously, `event.is_action_pressed("test", false, true)` always returned false, while `event.is_action_released("test", false, true)` returned true both for pressed and released. This is because the pressed pointer was not passed into `is_match`. This PR fixes it by using `action_match` instead.

MRP: [Test10.zip](https://github.com/godotengine/godot/files/7404122/Test10.zip)

### CODE REVIEW

File: core/input/input_event.h [hunk 1]
```diff
@@ -79,7 +79,7 @@ class InputEvent : public Resource {
 
 	virtual Ref<InputEvent> xformed_by(const Transform2D &p_xform, const Vector2 &p_local_ofs = Vector2()) const;
 
-	virtual bool action_match(const Ref<InputEvent> &p_event, bool *p_pressed, float *p_strength, float *p_raw_strength, float p_deadzone) const;
+	virtual bool action_match(const Ref<InputEvent> &p_event, const bool p_exact_match, const float p_deadzone, bool *const p_pressed, float *const p_strength, float *const p_raw_strength) const;
```
Comment (akien-mga) [inline core/input/input_event.h:82]: All the added const qualifiers are not useful here, and make the signature harder to read and inconsistent with the rest of the codebase.

File: core/input/input_map.h [hunk 2]
```diff
@@ -58,7 +58,7 @@ class InputMap : public Object {
 	OrderedHashMap<String, List<Ref<InputEvent>>> default_builtin_cache;
 	OrderedHashMap<String, List<Ref<InputEvent>>> default_builtin_with_overrides_cache;
 
-	List<Ref<InputEvent>>::Element *_find_event(Action &p_action, const Ref<InputEvent> &p_event, bool p_exact_match = false, bool *p_pressed = nullptr, float *p_strength = nullptr, float *p_raw_strength = nullptr) const;
+	List<Ref<InputEvent>>::Element *_find_event(Action &p_action, const Ref<InputEvent> &p_event, const bool p_exact_match = false, bool *const p_pressed = nullptr, float *const p_strength = nullptr, float *const p_raw_strength = nullptr) const;
```
Comment (akien-mga) [inline core/input/input_map.h:61]: Primitive types (`int`, `bool`, `float`, etc.) shouldn't be made `const` in the prototypes.

File: core/input/input_event.h [hunk 3]
```diff
@@ -437,7 +437,7 @@ class InputEventAction : public InputEvent {
 
 	virtual bool is_action(const StringName &p_action) const;
 
-	virtual bool action_match(const Ref<InputEvent> &p_event, bool *p_pressed, float *p_strength, float *p_raw_strength, float p_deadzone) const override;
+	virtual bool action_match(const Ref<InputEvent> &p_event, const bool p_exact_match, const float p_deadzone, bool *r_pressed, float *r_strength, float *r_raw_strength) const override;
```
Comment (akien-mga) [inline core/input/input_event.h:440]: There's still some unnecessary `const bool` and `const float` in prototypes.

**Comment by nathanfranke** [comment]
Thanks for reviewing, sorry for missing those extra consts so many times now! Should be ready now.

**Review by bruvzg — APPROVED** [review]
Haven't checked it in deep, but all changes seems reasonable, and it fixes keyboard navigation.

File: core/input/input_event.cpp [hunk 4]
```diff
@@ -887,36 +887,40 @@ bool InputEventJoypadMotion::is_pressed() const {
...
 	if (jm.is_null()) {
 		return false;
 	}
 
-	bool match = (axis == jm->axis); // Matches even if not in the same direction, but returns a "not pressed" event.
+	// Matches even if not in the same direction, but returns a "not pressed" event.
+	bool match = axis == jm->axis;
+	if (p_exact_match) {
+		match &= (axis_value < 0) == (jm->axis_value < 0);
+	}
```
Comment (akien-mga) [inline core/input/input_event.cpp:900]: I'm a bit concerned about the potential impact of this change on joypad motion events.

I guess let's merge and assess while testing whether this is working as expected.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
