### PR TITLE
Fix double tap & drag on Android

### LINKED ISSUE #76587: double_tap & drag on Android fails to detect drag
### Godot version

v4.0.1.stable.official [cacf49999]

### System information

Windows 11

### Issue description

Pretty easy to reproduce, in a blank project, add a script that logs all input events:

```gdscript
extends Node2D

func _input(event):
	print(event)
```

If you double tap & drag (as in, 2 "down" events, 1 "up" event) no drag events are emitted no matter how much you move your finger. 

If you tap another finger on the screen, it seems to "unblock" and now the drag events on the original finger register.

This doesn't happen when testing on a computer, just on my Android Pixel 6. 

### Steps to reproduce

See above

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by OmarShehata**
This fixes https://github.com/godotengine/godot/issues/76587. This is very easy to reproduce, just compile on Android device a project which prints all input events:

```gdscript
extends Node2D
func _input(event):
	print(event)
```

In `master`, if you double tap & drag, **no events are emitted** for the drag. In this PR, you correctly see the drag events. This makes Android consistent with iOS and Windows (I haven't tested other platforms behavior).

The fix involves listening for motion events in the `onDoubleTapEvent` listener, because the native Android `GestureDetector` differentiates between motion events after a double tap and regular motion events.

### CODE REVIEW

File: platform/android/java/lib/src/org/godotengine/godot/input/GodotGestureHandler.kt [hunk 1]
```diff
@@ -197,8 +197,13 @@ internal class GodotGestureHandler : SimpleOnGestureListener(), OnScaleGestureLi
 		if (event.actionMasked == MotionEvent.ACTION_UP) {
 			nextDownIsDoubleTap = false
 			GodotInputHandler.handleMotionEvent(event)
+			return true
 		}
-		return true
```
Comment (OmarShehata) [inline platform/android/java/lib/src/org/godotengine/godot/input/GodotGestureHandler.kt:201]: I am not sure why this was always returning true even for cases when it wasn't actually handling the event. I've changed it to only return true when it handles the event, consistent with the other event listeners here.

File: platform/android/java/lib/src/org/godotengine/godot/input/GodotGestureHandler.kt [hunk 2]
```diff
@@ -197,8 +197,13 @@ internal class GodotGestureHandler : SimpleOnGestureListener(), OnScaleGestureLi
 		if (event.actionMasked == MotionEvent.ACTION_UP) {
 			nextDownIsDoubleTap = false
 			GodotInputHandler.handleMotionEvent(event)
```
Comment (OmarShehata) [inline platform/android/java/lib/src/org/godotengine/godot/input/GodotGestureHandler.kt:199]: Also, is this correct, that a ACTION_UP should trigger a motion event?

Comment (m4gr3d) [reply platform/android/java/lib/src/org/godotengine/godot/input/GodotGestureHandler.kt:199]: That's correct, this correspond to the release of the double tap event.

File: platform/android/java/lib/src/org/godotengine/godot/input/GodotGestureHandler.kt (hunk 1 above)
Comment (m4gr3d) [reply platform/android/java/lib/src/org/godotengine/godot/input/GodotGestureHandler.kt:201]: This doesn't look correct, this callback should receive both down and up events and with this update the logic now returns false for down events, which would have the effect of cancelling the next up event.
Can you log the events passing through this method and check we are still receiving the expected flow.

**Review by m4gr3d — CHANGES_REQUESTED** [review]

**Comment by OmarShehata** [comment]
Thanks for the feedback @m4gr3d, I've force pushed an update (my understanding this is the preferred workflow to keep the commit history squashed). It now maintains the original behavior, but just handles the motion event.

I was able to confirm with additional logging the incorrect behavior you expected in my original attempt. We get an `ACTION_DOWN` event triggered here that we need to `return true` for but that should NOT trigger a `handleMotionEvent` (otherwise it triggers more events than expected).

**Comment by OmarShehata** [comment]
Also just noting down here, this could be implemented in the following way and I tested that it has the same behavior (my test was double tap, drag, & release, and comparing the events emitted on the GDScript side):

```kotlin
override fun onDoubleTapEvent(event: MotionEvent): Boolean {
	if (event.actionMasked == MotionEvent.ACTION_UP) {
		nextDownIsDoubleTap = false
		GodotInputHandler.handleMotionEvent(event)
		return true
	}
	if (event.actionMasked == MotionEvent.ACTION_MOVE) {
		GodotInputHandler.handleMotionEvent(event)
		return true
	}
	if (event.actionMasked == MotionEvent.ACTION_DOWN) {
		// No need to handle this, just need to return true
		// otherwise you get 2 extra events (pressed=true & pressed=false) when double tapping
		return true
	}
	return false
}
```

The version I pushed is more concise/closer to the original code.

File: platform/android/java/lib/src/org/godotengine/godot/input/GodotGestureHandler.kt [hunk 3]
```diff
@@ -197,7 +197,10 @@ internal class GodotGestureHandler : SimpleOnGestureListener(), OnScaleGestureLi
...
+		} else if (event.actionMasked == MotionEvent.ACTION_MOVE) {
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/input/GodotGestureHandler.kt:200]: Thanks for the update, this looks like it should handle the issue!

There's one more scenario to consider and incorporate in the logic; when panning and scaling is enabled (`panningAndScalingEnabled == true`), the `ScaleGestureDetector` logic treats `double_tap` followed by `swipe` as a `magnify` event:
- For the documentation, see https://developer.android.com/reference/android/view/ScaleGestureDetector#setQuickScaleEnabled(boolean)
- And the scale callback is https://github.com/godotengine/godot/blob/cf8ad12b56df4ae7bba4c73070dd035693a880e4/platform/android/java/lib/src/org/godotengine/godot/input/GodotGestureHandler.kt#L242.

This capability is still private (not exposed to GDScript) and only being used by the Android editor to support scaling in the spatial editor.
To complement your fix and not break that functionality, you'll need to check that `panningAndScalingEnabled == false` before forwarding the motion event.

**Review by m4gr3d — CHANGES_REQUESTED** [review]

**Comment by OmarShehata** [comment]
@m4gr3d just updated to prevent handling the event in the case of `panningAndScalingEnabled == false`. I've never used the Android version of the editor before, but I tested this by enabling panning & scaling as follows, and checking that when it is enabled, we go back to the old behavior (no drag events emitted after double tap)

```java
this.godotGestureHandler.setPanningAndScalingEnabled(true);
```

Let me know if this looks right!

**Review by m4gr3d — APPROVED** [review]
Looks great, thanks for the fix!

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by OmarShehata** [comment]
Thank you so much @akien-mga !! Thank you & all the contributors who spent the time & effort documenting everything so well that made me feel confident enough to give this a shot 🙏

**Comment by akien-mga** [comment]
Cherry-picked for 4.0.3.

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
This fix can't be cherry-picked for 3.5.x as is, the code is significantly different and I can't find easily where to do a similar change.
