### PR TITLE
Fix mutable bone axes process in TwoBoneIK3D

### LINKED ISSUE #113047: TwoBoneIK3D now emits infinite errors by `mutable_bone_axis` in latest 4.6.dev
### Tested versions

- Reproducible in v4.6.dev.gh [235a32ad1] (latest master)

- **Not reproducible** in v4.6.dev4.mono.official [bd2ca13c6]

### System information

Windows 10 - Godot 4.6.dev - Vulkan (Foward+) - NVIDIA GeForce 1070

### Issue description

TwoBoneIK3D now emits infinite math errors of **_"Vectors must not be zero"_** where before it didn't.

The TwoBoneIK3D works the same as expected, but those errors are now emitted infinitely in the console.

https://github.com/user-attachments/assets/ed5953f4-dadd-44f9-9885-5f9bbb4bfb3d

----
This change seems to have happend 5 days ago.
Using the build CI available,
One of the last versions I found where it still worked without errors is the v4.6.dev.gh-78598 [eb52be297]

After that, I get this errors.

### Steps to reproduce

- Import a model with a skeleton
- Add a TwoBoneIK3D 
- Add the bone settings

Result: Infinite errors
Expected: No errors

### Minimal reproduction project (MRP)

[MRP_TwoBoneIK.zip](https://github.com/user-attachments/files/23688374/MRP_TwoBoneIK.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
- Follow up https://github.com/godotengine/godot/pull/111815
- Fixes https://github.com/godotengine/godot/issues/113047

1. `init_current_joint_rotations()` was always required after joint updates but was missing in the mutable bone axes block, so it causes that setting zero vector for the chain vectors. Now it is included in `_update_bone_axis()` (meaning a partial revert).
2. The starting basis for `_get_bone_global_rest` was incorrect, fixed.

Before:
image

After:
image

### CODE REVIEW

File: scene/3d/two_bone_ik_3d.cpp [hunk 1]
```diff
@@ -656,7 +654,6 @@ void TwoBoneIK3D::_update_bone_axis(Skeleton3D *p_skeleton, int p_index) {
 	// Root bone.
 	orig = _get_bone_global_rest(p_skeleton, setting->root_bone.bone, setting->root_bone.bone).origin;
 	axis = global_rest_origin - orig;
-	global_rest_origin = orig;
```
Comment (TokageItLab) [inline scene/3d/two_bone_ik_3d.cpp:659]: Unused, I forgot to delete it when I copied and pasted from 643-645.

**Review by lyuma — APPROVED** [review]
It looks self consistent. Performing the origin offset in rest space is a bit unconventional, but I think it is equivalent to resetting the skeleton to rest and then re-applying any changes to the bone position.

**Comment by TokageItLab** [comment]
Addition: There was a safety issue after the bone length dynamically became 0, so fixed it.

**Comment by Repiteo** [comment]
Thanks!
