### PR TITLE
[GDScript 2.0] Don't double-reference Refs returned from function

### LINKED ISSUE #52699: Some Tweeners are leaking references
### Godot version

32f8f74

### System information

W10

### Issue description

Related to #51231

Tween and Tweeners had a circular reference, which prevented them from being freed properly (this was fixed by #51237)

However, Tween is still not being destroyed. Also if you use typed variable for tween, some Tweeners aren't destroyed too, which makes me think it's some GDScript bug. Here's test code:
```GDScript
extends Node2D
func _input(event):
	if event is InputEventKey and event.pressed:
		var tween = create_tween()
#		var tween: Tween = create_tween()
		tween.tween_property(self, "modulate", Color.RED, 1)
		tween.tween_interval(0.1)
		tween.tween_method(func(v): print(v), 0, 1, 0.1)
		tween.tween_callback(func(): print("finished"))
```
Run the scene, press any key and check the object Monitor. When animation starts, 5 objects are created and only 4 are destroyed when it ends; 1 object leaks (the Tween). When you switch to the commented line (so the tween is typed), 3 objects are leaked (Tween, IntervalTweener and CallbackTweener).

### Steps to reproduce

See above.

### Minimal reproduction project

You can compile engine with this patch for easier debugging:
[0001-Add-Tween-destructor-prints.txt](https://github.com/godotengine/godot/files/7170033/0001-Add-Tween-destructor-prints.txt)

### LINKED ISSUE #53093: RefCounted objects leaking when created in a C++ factory function called from GDScript
### Godot version

4.0.dev (ff2f1f54a9)

### System information

Windows 10

### Issue description

In C++, I have a factory function that creates new objects that inherit RefCounted and returns them.

```cpp
Ref<SomeRefCountedType> SomeClass::my_factory_function() {
	Ref<SomeRefCountedType> v = memnew(SomeRefCountedType);
	v->initialize(some_data);
	print_line("Created new SomeRefCountedType " + String::num_uint64((uint64_t)(v->get_instance_id())));
	return v;
}
```

In GDScript, I use these references for some stuff.
```gdscript
extends RefCounted

var _my_thing: SomeRefCountedType = null

func _make_my_thing(factory: SomeClass):
	_my_thing = factory.my_factory_function()
```

However, these objects never get destructed. (I verified with `print_line` statements in their destructors.)

---

To debug this issue, I added a check in `RefCounted::reference` and `unreference` to print out when they occur.
I added breakpoints here to get the call stacks.

```cpp
bool RefCounted::reference() {
	//...
	if (this->is_class("SomeRefCountedType")) {
		print_line("Reffing SomeRefCountedType " + String::num_uint64((uint64_t)(this->get_instance_id())) + " new count:" + String::num_int64(this->reference_get_count()));
	}

	return success;
}
```

Here is a table of when my object gets referenced, unreferenced, and where (shown by an abridged call stack).

| Transition | ref count | Abridged call stack |
| --- | --- | --- |
| [load scene] |  |  |
| ref | 2 | `<GDScript>, my_factory_function, Ref::ref_pointer, RefCounted::init_ref, RefCounted::reference` |
| unref | 1 | `<GDScript>, my_factory_function, Ref::ref_pointer, RefCounted::init_ref, RefCounted::unreference` |
| ref | 2 | `<GDScript>, my_factory_function, Ref::ref, RefCounted::reference` |
| unref | 1 | `<GDScript>, my_factory_function, Ref::~Ref, Ref::unref, RefCounted::unreference` |
| ref  | 2 | `<GDScript>, call_with_ptr_args_ret, ..., Ref::operator=, Ref::ref, RefCounted::reference` |
| unref | 1 | `<GDScript>, call_with_ptr_args_ret, ..., Ref::~Ref, Ref::unref, RefCounted::unreference` |
| ref | 2 | `GDScriptFunction::call, VariantInternal::object_assign, RefCounted::init_ref, RefCounted::reference` |
| (!!! no unref) |  |  |
| ref | 3 | `GDScriptFunction::call, Variant::operator=, Variant::reference, RefCounted::reference` |
| unref | 2 | `GDScriptFunction::call, Variant::~Variant, Variant::_clear_internal, RefCounted::unreference` |
| [unload scene] |  |  |
| unref | 1 | `~GDScriptInstance, ..., ~Variant, Variant::_clear_internal, RefCounted::unreference` |

To my untrained eye, it appears that Variants use `init_ref` where they shouldn't be.

### Steps to reproduce

See above

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by briansemrau**
GDScript 2.0 opcode `OPCODE_CALL_PTRCALL_OBJECT` will double-reference returned `Ref`s. This results in a memory leak.
This change fixes that issue while still keeping the fixes of #43992

Fixes #53093
Fixes #52699
(both issues are the same underlying bug)

@vnen Requesting review to make sure there are no regressions to #43941 or #43851

### CODE REVIEW

File: core/variant/variant_construct.cpp [hunk 1]
```diff
@@ -303,7 +303,7 @@ void VariantInternal::object_assign(Variant *v, const Object *o) {
 	if (o) {
 		if (o->is_ref_counted()) {
 			RefCounted *ref_counted = const_cast<RefCounted *>(static_cast<const RefCounted *>(o));
-			if (!ref_counted->init_ref()) {
+			if (ref_counted->reference_get_count() == 0) {
```
Comment (akien-mga) [inline core/variant/variant_construct.cpp:306]: For the record, this looks like it was copied/adapted from the `Variant` constructor:
https://github.com/godotengine/godot/blob/a56e8f8afc2b358ec6e58eed2725bfe85942e5e6/core/variant/variant.cpp#L2516-L2531

I'm not really familiar with this code, but won't this mean that when you assign a RefCounted object to a variant, it won't increment the refcount? So if it's dropped in whichever other object holds a reference to it, wouldn't this cause issues?

Comment (briansemrau) [reply core/variant/variant_construct.cpp:306]: Whoops. This needs to be its own function for this specific use case. I didn't notice it had other usage.

OPCODE_CALL_PTRCALL_OBJECT handles the return value of a native method returning an Object. When this object is a Ref<>, the native call automatically increments the refcount on return. So, object_assign redundantly increments the refcount in this case.

File: core/variant/variant_construct.cpp [hunk 2]
```diff
@@ -318,6 +318,25 @@ void VariantInternal::object_assign(Variant *v, const Object *o) {
 	}
 }
 
+void VariantInternal::object_assign_do_not_ref(Variant *v, const Object *o) {
```
Comment (briansemrau) [inline core/variant/variant_construct.cpp:321]: I'm not too happy with amount of code duplication, so if it's an issue, I'll take suggestions on how to reduce redundancy.

Comment (akien-mga) [reply core/variant/variant_construct.cpp:321]: An alternative could be to keep using `object_assign`, but decrement the reference in the GDScript VM after the fact. That's hacky though :P

Otherwise a boolean flag.

Comment (briansemrau) [reply core/variant/variant_construct.cpp:321]: Maybe `object_assign_do_not_ref` is the hack and decrementing in the gdscript VM is the more appropriate.

After all, calling the native function increments the refcount because it's expected that the caller will hold a local `Ref`, which will later be destructed and unref. This might be an issue of `MethodBind::ptrcall` not being safe with `Ref`.

**Comment by akien-mga** [comment]
The current version looks pretty clean, kudos. I'll let @vnen review/confirm that it's the best approach.

**Comment by akien-mga** [comment]
Poke @vnen.

**Comment by KoBeWi** [comment]
I checked #52699 and with my original code some instances are still leaked with the typed line. So it fixes only half of the issue.

**Review by vnen — APPROVED** [review]
It looks okay to me. I guess this a bit tricky to wrap the head around since there's a lot going on under the hood.

I wonder if we should restore the `set_object()` function that I removed in #43992, though having one just for updating the ID should be good enough.

Maybe a comment here about the reference counting would be handy so it isn't wrongly changed in the future.
