### PR TITLE
Fix inability to uncomment code in text shader editor

### LINKED ISSUE #83821: Can not uncomment code in text shader editor
### Godot version

Godot v4.2.beta (8c25a98fd)

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3619) - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

### Issue description

Can not uncomment code in text shader editor.
Uncomment this `//vertex_interpolated = VERTEX;` results in `// //vertex_interpolated = VERTEX;`

### Steps to reproduce

Open any text shader file, try comment and uncomment any code.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes #83821

The origin logic assumes delimiter is `#` and thus  `left(1)`, but in shader it's `\\`, so the logic for checking is_commented failed.

### CODE REVIEW

File: editor/code_editor.cpp [hunk 1]
```diff
@@ -1514,8 +1514,8 @@ void CodeTextEditor::toggle_inline_comment(const String &delimiter) {
 			// Empty lines should not be counted.
 			bool is_empty = text_editor->get_line(line).strip_edges().is_empty();
 			is_all_empty = is_all_empty && is_empty;
-			// `.left(1)` here because get_delimiter_start_key will return `##` instead of `#` when there is multiple comment delimiter in a line.
-			if (!is_empty && (delimiter_idx == -1 || text_editor->get_delimiter_start_key(delimiter_idx).left(1) != delimiter)) {
+			// `.left(delimiter.length())` here because get_delimiter_start_key will return `##` instead of `#` when there is multiple comment delimiter in a line.
+			if (!is_empty && (delimiter_idx == -1 || text_editor->get_delimiter_start_key(delimiter_idx).left(delimiter.length()) != delimiter)) {
```
Comment (dalexeev) [inline editor/code_editor.cpp:1518]:
```suggestion
			// `get_delimiter_start_key()` will return `##` instead of `#` when there is multiple comment delimiter in a line.
			if (!is_empty && (delimiter_idx == -1 || !text_editor->get_delimiter_start_key(delimiter_idx).begins_with(delimiter))) {
```

I haven't tested this, but it probably makes sense.

Comment (jsjtxietian) [reply editor/code_editor.cpp:1518]: Tested locally, it worked and makes sense.

**Review by SaracenOne — APPROVED** [review]
LGTM 👍 
Tested, it works, and implementation looks fine. I also compared it with a previous similar PR I reviewed for the script editor, and it doesn't seem like any regressions have been introduced by fixing this. (https://github.com/godotengine/godot/pull/83382).

**Comment by akien-mga** [comment]
Thanks!
