### PR TITLE
Fix toggling snap mode while transforming the Spatial object

### LINKED ISSUE #26855: Toggle snap shortcut does not working while moving node
**Godot version:**
3.1 RC1

**OS/device including version:**
Windows 10 x64

**Issue description:**
An improvement in use (to stay similar to many editors) would be toggling snap while moving a node.

**Steps to reproduce:**

1. Press W (move)
2. Start moving an object (do not release the mouse button)
3. Press Y (Snap) while moving
4. At this point, the snap should already have toggled and have begun to act in the new snap mode (on or off).
5. But currently, I have to release the mouse, only then the change of the snap is effected.

### PR DESCRIPTION
**Pull request by Janglee123**
Fixes #26855.
@Chaosus, as you said the problem is with `_edit.snap`. It was not toggling with `Y key`.

### CODE REVIEW

File: editor/plugins/spatial_editor_plugin.cpp [hunk 1]
```diff
@@ -1422,7 +1422,7 @@ void SpatialEditorViewport::_sinput(const Ref<InputEvent> &p_event) {
 
 						Vector3 motion_mask;
 						Plane plane;
-						bool plane_mv = false;
+						bool plane_mv = false;
```
Comment (Chaosus) [inline editor/plugins/spatial_editor_plugin.cpp]: Looks like a bad formating here

Comment (Chaosus) [reply editor/plugins/spatial_editor_plugin.cpp]: Use `git commit --amend` command to fix it (and then git push --force origin <branch (master in your case> - http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html , https://git-scm.com/book/en/v2/Git-Basics-Undoing-Things

Comment (Chaosus) [reply editor/plugins/spatial_editor_plugin.cpp]: Its generally recommended to create a separate branches for each PR you've created

Comment (Janglee123) [reply editor/plugins/spatial_editor_plugin.cpp]: From now on I will take care of these things.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.1.
