### PR TITLE
Fix inertia tensor update & Generic6DOFJoint & Simplify Basis::get_euler()

### LINKED ISSUE #11131: Generic6DOFJoint broken
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot since merge https://github.com/godotengine/godot/pull/7426

**Issue description:**

 I was trying to port a project from 2.1 to 3 and I realized that the generic 6DOF joint isn't working, everything gets unstable, so I started tracking down the regression.
In this branch (https://github.com/m4nu3lf/godot/tree/bugfix/physics) it was working, so by rebuilding tons of different commits I've been able to find where things broke, and it is... just after the merge of the branch (https://github.com/godotengine/godot/pull/7426)!
Diffing the physics server I couldn't see any major change before and after the merge so... long story short, the bug is in the Matrix3 and/or Transform classes. Not sure if the conventions have been changed without updating the physics engine, but if I revert just those 2 files to before the merge (fixing just a few compilation errors) everything works again

**Steps to reproduce:**
Create 2 rigid bodies and join them with a Generic6DOFJoint with angular constraints

### PR DESCRIPTION
**Pull request by m4nu3lf**
This PR has evolved a bit. Here is a recap:

- Fix  a bug in the Generic6DOFJoint, angles were wrong because Basis::get_euler() uses a different convention than the previous method and YXZ convention was used while the XYZ is required.
- Fix a bug in the BodySW::_update_inertia_tensor() method. The Basis::scale() method was multiplying from the right, but now it multiplies from the left.
- Simplify the Basis::get_euler() method. Not sure if the implementation was causing problems in the Generic6DOFJoint, but now it is equivalent to the one that was written in the Generic6DOFJoint (It was borrowed from Bullet I think).

Not sure if point 3 can cause problems in other parts of the engine, I think it was @tagcup to introduce that change so I need his opinion.
This definitely fixes https://github.com/godotengine/godot/issues/11131 and likely other bugs

### CODE REVIEW

File: core/math/matrix3.cpp [hunk 1]
```diff
@@ -369,32 +369,24 @@ Vector3 Basis::get_euler_xyz() const {
 
 	Vector3 euler;
 #ifdef MATH_CHECKS
-	ERR_FAIL_COND_V(is_rotation() == false, euler);
+	ERR_FAIL_COND_V(!is_rotation(), euler);
 #endif
-	euler.y = Math::asin(elements[0][2]);
-	if (euler.y < Math_PI * 0.5) {
-		if (euler.y > -Math_PI * 0.5) {
-			// is this a pure Y rotation?
```
Comment (m4nu3lf) [inline core/math/matrix3.cpp]: This two ifs assume that Math::asin(1) == Math_PI * 0.5 and Math::asin(-1) == Math_PI * 0.5 which I'm pretty sure it is not true in floating point arithmetcs

File: core/math/matrix3.cpp [hunk 2]
```diff
@@ -369,32 +369,24 @@ Vector3 Basis::get_euler_xyz() const {
...
-			if (elements[1][0] == 0.0 && elements[0][1] == 0.0 && elements[1][2] == 0 && elements[2][1] == 0 && elements[1][1] == 1) {
```
Comment (m4nu3lf) [inline core/math/matrix3.cpp]: This if is useless because the else branch evaluates to the same values (apart for some fp approximations), but the if could actually be more costly (if that is an optimization) than just computing the values.

File: core/math/matrix3.cpp [hunk 3]
```diff
@@ -369,32 +369,24 @@ Vector3 Basis::get_euler_xyz() const {
...
-			real_t r = Math::atan2(elements[1][0], elements[1][1]);
+            euler.x = -Math::atan2(elements[0][1], elements[1][1]);
+            euler.y = -Math_PI / 2.0;
 			euler.z = 0.0;
-			euler.x = euler.z - r;
 		}
 	} else {
-		real_t r = Math::atan2(elements[0][1], elements[1][1]);
-		euler.z = 0;
-		euler.x = r - euler.z;
```
Comment (m4nu3lf) [inline core/math/matrix3.cpp]: x - 0 = x from the properties of zero :P

File: servers/physics/joints/generic_6dof_joint_sw.cpp [hunk 4]
```diff
@@ -221,7 +221,7 @@ Generic6DOFJointSW::Generic6DOFJointSW(BodySW *rbA, BodySW *rbB, const Transform
 void Generic6DOFJointSW::calculateAngleInfo() {
 	Basis relative_frame = m_calculatedTransformA.basis.inverse() * m_calculatedTransformB.basis;
 
-	m_calculatedAxisAngleDiff = relative_frame.get_euler();
+	m_calculatedAxisAngleDiff = -relative_frame.get_euler();
```
Comment (m4nu3lf) [inline servers/physics/joints/generic_6dof_joint_sw.cpp]: Don't ask me way. It works this way, convention must have changed for the computed matrix

**Comment by akien-mga** [comment]
CC @tagcup

**Comment by akien-mga** [comment]
The indentation is bogus: https://travis-ci.org/godotengine/godot/jobs/275238001

**Comment by m4nu3lf** [comment]
@akien-mga My bad, I was not aware that the Godot source uses tabs (or I didn't remember)
Anyway this PR doesn't really solve any issue (I'm still investigating https://github.com/godotengine/godot/issues/11131) but I think it is still small improvement

File: servers/physics/body_sw.cpp [hunk 5]
```diff
@@ -45,8 +45,9 @@ void BodySW::_update_transform_dependant() {
 	// update inertia tensor
 	Basis tb = principal_inertia_axes;
 	Basis tbt = tb.transposed();
-	tb.scale(_inv_inertia);
```
Comment (m4nu3lf) [inline servers/physics/body_sw.cpp]: Conventions have changed for the scale method, this was making the physics engine unstable

File: servers/physics/joints/generic_6dof_joint_sw.cpp [hunk 6]
```diff
@@ -219,7 +219,7 @@ Generic6DOFJointSW::Generic6DOFJointSW(BodySW *rbA, BodySW *rbB, const Transform
 }
 
 void Generic6DOFJointSW::calculateAngleInfo() {
-	Basis relative_frame = m_calculatedTransformA.basis.inverse() * m_calculatedTransformB.basis;
```
Comment (m4nu3lf) [inline servers/physics/joints/generic_6dof_joint_sw.cpp]: Same here, conventions have changed

**Comment by akien-mga** [comment]
@tagcup Could you have a look at the math changes?

**Comment by tagcup** [comment]
Ah I apparently missed those bits when I switched to YXZ convention and changed the order of rotation and scale, thanks.

I wouldn't worry about the get_euler itself too much because fast math optimizer will optimize those anyway.

As for the "This if is useless" bits, they're a workaround for #1479 that @reduz asked.

I didn't carefully check other changes you made in get_euler but I compiled and run it and the rotations in the editor don't seem to be working correctly.

**Comment by tagcup** [comment]
Maybe you can defer the changes in get_euler to a separate PR and we can go ahead and merge the fixes to physics code which I didn't properly updated back then, since they're two separate things?

**Comment by m4nu3lf** [comment]
@tagcup I got it now. The angles are valid either way but that form is easier to read in the editor. As long as it doesn't impact the the physics engine (Maybe it is better?) I'm happy to revert that change, (or I could just put back the special case handling and keep the aesthetic improvements?).

I was not concerned about performance issues I wrongly assumed that was a (failed) attempt to an optimization

**Comment by akien-mga** [comment]
It would probably be good to add a comment explaining the UX workaround, to avoid misunderstandings next time someone reads that code :)

**Comment by tagcup** [comment]
@m4nu3lf I think it'd be better if you don't change the get_euler functions in this PR, because as I mentioned earlier, there is apparently a mistake somewhere in the changes you made there, and the rotations in the editor are broken as a result. I don't think there is anything wrong with get_euler functions in its current state either, but we can discuss this in a separate issue if you want. 

The other changes are actual bugfixes though, so it'd be nice to get them in.

**Comment by tagcup** [comment]
The matices in terms of Euler angles are already given in comments, here's a more readable (to me at least) output from Mathematica which the code need to match:

screenshot_20170922_141719

What you implemented appears to be ZXY rather than YXZ.

**Comment by Zireael07** [comment]
Please get the bugfixes in, the joint and inertia tensor fixes should hopefully fix an issue with vehicle body in 3.0. that I'm waiting on :)

**Comment by m4nu3lf** [comment]
@tagcup It is XYZ, it is the same expected from the G6DOF Joint. I didn't change the convention and checked the math over and over, actually I think there was a bug in the previous implementation, if you look carefully for the case sin(y) == 1 we are computing x as atan2(m[0][1], m[1][1]) but that is atan2(-cy*sz, ....) that can never give x

**Comment by tagcup** [comment]
Ah, you're right. I didn't check the XYZ code before, I agree with your change, and I should check other XYZ that I didn't go over before.

What's puzzling is, the UI uses YXZ code only, so I'm not sure what's wrong. I can give it a check during the weekend.

Meanwhile, can you restore the aesthetic workarounds?

**Comment by m4nu3lf** [comment]
@tagcup Sure, I'll restore it! Indeed the bug can only cause problems to code that is using the XYZ convention (that is the joint).
I think that eventually we should rewrite the G6DOF joint to use the YXZ convention as well, being the default in godot

**Comment by tagcup** [comment]
I just cleanly switched back to your branch and recompiled and oddly enough, I can't reproduce the problem in the UI? Sorry, that appears to be a mistake on my side.

I'm OK with all your changes if you restore the aesthetic hacks.

**Comment by tagcup** [comment]
About switching 6DOF to YXZ, I believe those parts will be completely replaced once Bullet is merged?

File: servers/physics/joints/generic_6dof_joint_sw.cpp (hunk 6 above)
Comment (tagcup) [reply servers/physics/joints/generic_6dof_joint_sw.cpp]: Basis is fixed to be R.S rather than S.R, but what does that have to do with this change?

Comment (tagcup) [reply servers/physics/joints/generic_6dof_joint_sw.cpp]: Also, below in this function, you may want to renormalize m_calculatedAxis below. I don't know how bad the drift due to errors is in general, but the current version of bullet [does it](https://github.com/bulletphysics/bullet3/blob/master/src/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.cpp#L353) apparently.

**Comment by m4nu3lf** [comment]
What are you saying that we are going to get rid of the Godot physics engine? I've got pull requests and I was preparing a few more for it...
Anyway If the tests pass it should be ready to be merged

**Comment by tagcup** [comment]
Oh, I see. Maybe, I'm not sure about the extent of it, you can check the current state of the change set in #10013

**Comment by tagcup** [comment]
On the other hand, these fixes will still be useful until it's merged

**Comment by Zireael07** [comment]
#10013 is a toggle, Godot physics OR Bullet physics, so the fixes will definitely be useful.

**Comment by Zireael07** [comment]
What's the status on merging this?

**Comment by Zireael07** [comment]
@akien-mga Can this get looked at before alpha 2?

**Comment by akien-mga** [comment]
@tagcup Do you agree with the `Basis::get_euler()` changes?

**Comment by tagcup** [comment]
Yes, it looks good to me

**Comment by Zireael07** [comment]
So if it looks good, can this get merged?

**Comment by akien-mga** [comment]
After alpha2.
