### PR TITLE
Fix implementation of move_to_trash() on Linux

### LINKED ISSUE #42840: OS move_to_trash() on Linux is not compliant with the Freedesktop specification
**Godot version:**
3.2.2 stable

**OS/device including version:**
Linux mint

**Issue description:**
In Godot modifying files externally is generally a bad idea as things may break inside Godot, so the approach is to use the IDE.

Unlike almost most IDEs, when you select DELETE on an item in the FileSystem dock they are removed permanently (yes, I know there is a message saying this), they are not removed to the current operating system Trash.

This is quite a dangerous thing and all other editors simply send the files to the Trash. I know this because I decided to tidy up some files before committing and accidentally deleted all the files I had created and worked on in the past few hours as I'd selected a couple by mistake.

**Steps to reproduce:**
1. create a file
2. Use Godot to delete it
3. No getting it back

### PR DESCRIPTION
**Pull request by dakennedyd**
Modifies move_to_trash() on Linux
Fixes #42840 OS move_to_trash() on Linux is not compliant with the Freedesktop specification

### CODE REVIEW

File: platform/linuxbsd/os_linuxbsd.cpp [hunk 1]
```diff
@@ -303,62 +303,138 @@ static String get_mountpoint(const String &p_path) {
 }
 
 Error OS_LinuxBSD::move_to_trash(const String &p_path) {
-	String trash_can = "";
+	Error ok;
```
Comment (aaronfranke) [inline platform/linuxbsd/os_linuxbsd.cpp:306]: We don't need to declare variables before they're needed. You can remove this and change what is currently line 311 to `Error ok = execute(` etc.

Also, maybe this variable should be named `err` or `result` or something instead of `ok`. I see that there is also `err` below, I think this code would be a good candidate for adding some scopes using `{}`.

Comment (dakennedyd) [reply platform/linuxbsd/os_linuxbsd.cpp:306]: No prob, I'll change it :)
Tried to emulate the style of the code already written,
i copied the style from OS_LinuxBSD::shell_open() on line 124.

File: platform/linuxbsd/os_linuxbsd.cpp [hunk 2]
```diff
@@ -303,65 +303,150 @@ static String get_mountpoint(const String &p_path) {
...
+		dest_path = trash_path + "/files/" + fn;
+	}
+	file_name = fn;
+
+	// Generates the .trashinfo file
+	OS::Date date = OS::get_singleton()->get_date(false);
+	OS::Time time = OS::get_singleton()->get_time(false);
+	String timestamp = vformat("%04d-%02d-%02dT%02d:%02d:", date.year, date.month, date.day, time.hour, time.min);
+	timestamp = vformat("%s%02d", timestamp, time.sec); // vformat only supports up to 6 arguments.
+	String trash_info = "[Trash Info]\nPath=" + p_path.http_escape() + "\nDeletionDate=" + timestamp + "\n";
```
Comment (pouleyKetchoupp) [inline platform/linuxbsd/os_linuxbsd.cpp:408]: Why is `http_escape` needed here?

File: platform/linuxbsd/os_linuxbsd.cpp [hunk 3]
```diff
@@ -303,65 +303,150 @@ static String get_mountpoint(const String &p_path) {
...
+		Error err;
+		FileAccess *file = FileAccess::open(trash_path + "/info/" + file_name + ".trashinfo", FileAccess::WRITE, &err);
+		if (err != OK) {
+			ERR_PRINT("move_to_trash: Can't create trashinfo file:" + trash_path + "/info/" + file_name + ".trashinfo");
+			return err;
+		}
+		file->store_string(trash_info);
+		file->close();
+
+		// Rename our resource before moving it to the trash can
```
Comment (pouleyKetchoupp) [inline platform/linuxbsd/os_linuxbsd.cpp:419]: Comment missing `.` at the end (coding style).

File: platform/linuxbsd/os_linuxbsd.cpp [hunk 4]
```diff
@@ -303,65 +303,150 @@ static String get_mountpoint(const String &p_path) {
...
+	String fn = file_name;
+
+	// Checks if a resource with the same name already exist in the trash can,
+	// if there is, add an identifying number to our resource's name.
+	while (stat(dest_path.utf8().get_data(), &buff) == 0) {
+		id_number++;
+
+		// Added a limit to check for identically named files already on the trash can
+		// if there are too many it could make the editor unresponsive.
+		if (id_number > 999) {
```
Comment (pouleyKetchoupp) [inline platform/linuxbsd/os_linuxbsd.cpp:394]: You can use `ERR_FAIL_COND_V_MSG` to make this shorter.

```suggestion
		ERR_FAIL_COND_V_MSG(id_number > 999, FAILED, "Too many identically named resources already in the trash can.");
```

File: platform/linuxbsd/os_linuxbsd.cpp [hunk 5]
```diff
@@ -303,65 +303,150 @@ static String get_mountpoint(const String &p_path) {
...
+		}
+		memdelete(dir_access);
+	}
 
-	// Issue an error if trash can is not created proprely.
-	if (err != OK) {
-		ERR_PRINT("move_to_trash: Could not create the trash can \"" + trash_can + "\"");
-		return err;
+	// The trash can is successfully created, now we check that we don't exceed our file name Length limit.
+	// If the file name it's too long trim it so we can add the identifyng number and ".trashinfo"
```
Comment (pouleyKetchoupp) [inline platform/linuxbsd/os_linuxbsd.cpp:375]: Missing `.` at the end (coding style) + spelling: `is too long`, `identifying`

File: platform/linuxbsd/os_linuxbsd.cpp [hunk 6]
```diff
@@ -303,65 +303,150 @@ static String get_mountpoint(const String &p_path) {
...
+	// Generates the .trashinfo file
+	OS::Date date = OS::get_singleton()->get_date(false);
+	OS::Time time = OS::get_singleton()->get_time(false);
+	String timestamp = vformat("%04d-%02d-%02dT%02d:%02d:", date.year, date.month, date.day, time.hour, time.min);
+	timestamp = vformat("%s%02d", timestamp, time.sec); // vformat only supports up to 6 arguments.
+	String trash_info = "[Trash Info]\nPath=" + p_path.http_escape() + "\nDeletionDate=" + timestamp + "\n";
+	{
+		Error err;
+		FileAccess *file = FileAccess::open(trash_path + "/info/" + file_name + ".trashinfo", FileAccess::WRITE, &err);
+		if (err != OK) {
```
Comment (pouleyKetchoupp) [inline platform/linuxbsd/os_linuxbsd.cpp:412]: Same thing with ERR_FAIL_COND_V_MSG here.

```suggestion
		ERR_FAIL_COND_V_MSG(err != OK, err, "Can't create trashinfo file:" + trash_path + "/info/" + file_name + ".trashinfo");
```

File: platform/linuxbsd/os_linuxbsd.cpp [hunk 7]
```diff
@@ -303,65 +303,150 @@ static String get_mountpoint(const String &p_path) {
...
+			ERR_PRINT("move_to_trash: Can't create trashinfo file:" + trash_path + "/info/" + file_name + ".trashinfo");
+			return err;
+		}
+		file->store_string(trash_info);
+		file->close();
+
+		// Rename our resource before moving it to the trash can
+		DirAccess *dir_access = DirAccess::create(DirAccess::ACCESS_FILESYSTEM);
+		Error err2 = dir_access->rename(p_path, p_path.get_base_dir() + "/" + file_name);
+		if (err2 != OK) {
```
Comment (pouleyKetchoupp) [inline platform/linuxbsd/os_linuxbsd.cpp:422]: Same thing with ERR_FAIL_COND_V_MSG here.

```suggestion
		err = dir_access->rename(p_path, p_path.get_base_dir() + "/" + file_name);
		ERR_FAIL_COND_V_MSG(err != OK, err, "Can't rename file \"" + p_path + "\"");
```

**Review by pouleyKetchoupp — CHANGES_REQUESTED** [review]
Nice work! See my comments for details, otherwise the code looks fine. I haven't tested though.

Are there known use cases for `gio trash` and `gvfs-trash` not supported? I wonder if we still need the manual fallback case at all.

File: platform/linuxbsd/os_linuxbsd.cpp (hunk 2 above)
Comment (dakennedyd) [reply platform/linuxbsd/os_linuxbsd.cpp:408]: According to the Free Desktop trash spec the value for the path key should have escaped characters as in URLs which i assume is what http_escape() does. Seems to work.
It would be nice if this low level functions had some comments explaining their purpose exactly.

File: platform/linuxbsd/os_linuxbsd.cpp (hunk 3 above)
Comment (dakennedyd) [reply platform/linuxbsd/os_linuxbsd.cpp:419]: Done.

File: platform/linuxbsd/os_linuxbsd.cpp (hunk 4 above)
Comment (dakennedyd) [reply platform/linuxbsd/os_linuxbsd.cpp:394]: Done.

File: platform/linuxbsd/os_linuxbsd.cpp [hunk 8]
```diff
@@ -303,65 +303,150 @@ static String get_mountpoint(const String &p_path) {
...
 		return FAILED;
 	}
 
 	// Create needed directories for decided trash can location.
-	DirAccess *dir_access = DirAccess::create(DirAccess::ACCESS_FILESYSTEM);
-	Error err = dir_access->make_dir_recursive(trash_can);
-	memdelete(dir_access);
+	{
+		DirAccess *dir_access = DirAccess::create(DirAccess::ACCESS_FILESYSTEM);
+		Error err = dir_access->make_dir_recursive(trash_path);
```
[the remark this answers is not in the document]
Comment (dakennedyd) [reply platform/linuxbsd/os_linuxbsd.cpp:362]: Okeydoke.

File: platform/linuxbsd/os_linuxbsd.cpp (hunk 6 above)
Comment (dakennedyd) [reply platform/linuxbsd/os_linuxbsd.cpp:412]: Done and done.

File: platform/linuxbsd/os_linuxbsd.cpp (hunk 5 above)
Comment (dakennedyd) [reply platform/linuxbsd/os_linuxbsd.cpp:375]: Done.

File: platform/linuxbsd/os_linuxbsd.cpp (hunk 7 above)
Comment (dakennedyd) [reply platform/linuxbsd/os_linuxbsd.cpp:422]: Done.

**Comment by dakennedyd** [comment]
The gio/gvfs-trash functions seem to be part of the GNOME/GTK stack. I don't know if this commands work at all
on non GNOME systems, plus is nice to have a fallback.

File: platform/linuxbsd/os_linuxbsd.cpp (hunk 2 above)
Comment (pouleyKetchoupp) [reply platform/linuxbsd/os_linuxbsd.cpp:404]: Makes sense. I agree on comments for internal methods. There's actually a documentation available for this one because it's exposed to scripts:
https://docs.godotengine.org/en/stable/classes/class_string.html?#class-string-method-http-escape

I'm leaving the reference spec here for the record:

> The value type for this key is “string”; it SHOULD store the file name as the sequence of bytes produced by the file system, with characters escaped as in URLs (as defined by RFC 2396, section 2).

*from https://specifications.freedesktop.org/trash-spec/trashspec-latest.html*

**Comment by pouleyKetchoupp** [comment]
I've made some tests on Ubuntu/Gnome and it works fine with the 3 methods.

The only difference is in the manual fallback, the `.trashinfo` files use `%2F` for `/` characters (due to how Godot's `http_escape` works) while gio and gvfs-trash use `/`. It doesn't seem to be a problem though, the file information is displayed correctly in the trash.

**Review by pouleyKetchoupp — APPROVED** [review]

**Comment by akien-mga** [comment]
>> Are there known use cases for `gio trash` and `gvfs-trash` not supported? I wonder if we still need the manual fallback case at all.
>
> The gio/gvfs-trash functions seem to be part of the GNOME/GTK stack. I don't know if this commands work at all
> on non GNOME systems, plus is nice to have a fallback.

I do have `gio` here on KDE Plasma, which is part of glib2.0, which is a common dependency for a lot of software regardless of the DE, so that's a fairly safe option.

That being said, KDE does have its own "io" client `kioclient5`:
```
  kioclient5 move 'src' 'dest'
            # Moves the URL 'src' to 'dest'.
            #   'src' may be a list of URLs.

            #   'dest' may be "trash:/" to move the files
            #   to the trash.

            #   the short version kioclient5 mv
            #   is also available.
```

Tested locally with:
```
kioclient5 move icon.png trash:/
```
And it seems to work fine.

I think KDE4 had `kioclient` (without 5), but I don't think we need to both with KDE4 support anymore.

**Comment by akien-mga** [comment]
Could you add support for `kioclient5` as suggested above? Then it should be good to merge.

I'd suggest this order:
- `gio` (glib)
- `kioclient5` (KDE)
- `gfvs-trash` (Debian/Ubuntu-specific, deprecated)

**Comment by dakennedyd** [comment]
I did the changes you requested.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.
