### PR TITLE
Fix debanding not being used in the 2D editor when enabled in Project Settings

### LINKED ISSUE #108948: Editor sometimes does not display debanding
### Tested versions

- Reproducible in Godot v4.4.1.stable

### System information

Godot v4.4.1.stable - Windows 11 (build 26100) - Multi-window, 2 monitors - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 5070 Ti (NVIDIA; 32.0.15.7700) - 13th Gen Intel(R) Core(TM) i7-13700K (24 threads)

### Issue description

When using the following, debanding is never shown in the editor with Godot 4.4.1:

- Mobile rendering method
- Environment with Canvas Background mode and Glow effect

Editor | Game
-- | --
Image | Image

I also tested with the build artifact from #107782 and found that the behaviour has changed slightly: With this PR's build artifact, the debanding can now be seen in the editor, but **only after the edtior has been restarted**.

### Steps to reproduce

This issue is easier to see with HDR 2D enabled, but it happens with both HDR 2D enabled and disabled.

1. Create a 2D scene
2. Create a world environment and set it's background mode to canvas
3. Create a 2D object and add a glow effect to the world environment
4. Enable debanding in the project settings
5. Note that debanding is not visible
6. Run the game and note that debanding is visible
7. Restart the editor and note that in 4.4.1 debanding is still not visible in the editor, but with #107782 debanding becomes visible in the editor after restarting.

### Minimal reproduction project (MRP)

[editor-debanding-needs-restart.zip](https://github.com/user-attachments/files/21417442/editor-debanding-needs-restart.zip)

### PR DESCRIPTION
**Pull request by Calinou**
Note that the debanding Viewport property still needs to be set on the 3D viewport to ensure it still works there.

- This closes https://github.com/godotengine/godot/issues/108948.

## Preview

image

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -510,6 +510,10 @@ void EditorNode::_update_from_settings() {
 	Viewport::MSAA msaa = Viewport::MSAA(int(GLOBAL_GET("rendering/anti_aliasing/quality/msaa_2d")));
 	scene_root->set_msaa_2d(msaa);
 
+	// 2D doesn't use a dedicated SubViewport like 3D does, so we apply it on the root viewport instead.
+	const bool use_debanding = GLOBAL_GET("rendering/anti_aliasing/quality/use_debanding");
+	scene_root->set_use_debanding(use_debanding);
```
Comment (KoBeWi) [inline editor/editor_node.cpp]:
```suggestion
	scene_root->set_use_debanding(GLOBAL_GET("rendering/anti_aliasing/quality/use_debanding"));
```
It's not much longer this way.

**Comment by allenwp** [comment]
Hmm. This PR seems to fix the Mobile rendering method, but there seems to be one remaining issue that can be reproduced with the MRP from the linked issue: The editor must be restarted to see a change in debanding with the **Forward+ rendering method when HDR 2D is enabled**.

(Sorry, in my initial bug report I thought the issue was only related to the Mobile rendering method, but then realized it affects Forward+ as well.)

Edit: this PR looks great though, so it's fine to merge this and fix the other but separately if the Forward+ part proves to be at all tricky.

**Comment by allenwp** [comment]
I seem to have confused myself: For some reason, I previously thought that it was when Forward+ is disabled that the debanding setting change isn't visible... But now when I test it I notice that it's when Forward+ is enabled that the problem occurs.

I must have made a mistake. I've updated my previous comment to be correct, as I see it now.

**Review by allenwp — APPROVED** [review]
This looks good and resolves the longstanding issue and is thus suitable for cherry-picking.

I've looked more into the issue with the editor needing a restart before seeing changes to the debanding project setting (specific to ~~Forward+ with~~ HDR 2D enabled) and found that this issue was also introduced by #107782. I'll look into seeing why this might be the case separate of this PR. I've also opened an issue to track this specific regression that my PR caused: #108975

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -510,6 +510,9 @@ void EditorNode::_update_from_settings() {
 	Viewport::MSAA msaa = Viewport::MSAA(int(GLOBAL_GET("rendering/anti_aliasing/quality/msaa_2d")));
 	scene_root->set_msaa_2d(msaa);
 
+	// 2D doesn't use a dedicated SubViewport like 3D does, so we apply it on the root viewport instead.
+	scene_root->set_use_debanding(GLOBAL_GET("rendering/anti_aliasing/quality/use_debanding"));
+
```
Comment (allenwp) [inline editor/editor_node.cpp]:
```suggestion
	bool use_debanding = GLOBAL_GET("rendering/anti_aliasing/quality/use_debanding");
	scene_root->set_use_debanding(use_debanding);
	get_viewport()->set_use_debanding(use_debanding);
```

By changing it to this, it fixes both #108975 and #108948 and should sill be safe for cherry-picking.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
