### PR TITLE
Prevent signal disconnection attempts on invalid references

### LINKED ISSUE #45072: Editor Crashed using GraphEdit with instanced GraphNode
**Godot version:**
Godot v3.2.4 beta 5

**OS/device including version:**
EndeavourOS Linux

**Issue description:**
Editor crashed when working with GraphEdit and instanced GraphNode. Saving a scene with GraphNode as a base node, and return to the scene where it was instanced, make the editor crashed.

```
// Representation of sceen tree that I tested

// Not crashed
Control
    GraphEdit // Not crashed even if not inside tree
    GraphNode
    GraphNode(Instanced)

// Crashed
Control
    GraphEdit
        GraphNode(Instanced)
    GraphNode

// Crashed
Control
    GraphEdit
        GraphNode
    GraphNode(Instanced)
```

<details>
<summary>Backtrace</summary>

handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug
[1] /usr/lib/libc.so.6(+0x3d6a0) [0x7faa7135a6a0] (??:0)
[2] /home/nafys/dev/godot/godot3() [0xda8e4e] (??:?)
[3] /home/nafys/dev/godot/godot3() [0x1b7704a] (<artificial>:?)
[4] /home/nafys/dev/godot/godot3() [0x1c822aa] (??:?)
[5] /home/nafys/dev/godot/godot3() [0x1c9e2d2] (??:?)
[6] /home/nafys/dev/godot/godot3() [0xdbc65b] (??:?)
[7] /home/nafys/dev/godot/godot3() [0x2cef619] (??:?)
[8] /home/nafys/dev/godot/godot3() [0x1c9e2da] (??:?)
[9] /home/nafys/dev/godot/godot3() [0xdbc65b] (??:?)
[10] /home/nafys/dev/godot/godot3() [0x2cef619] (??:?)
[11] /home/nafys/dev/godot/godot3() [0x25375ef] (??:?)
[12] /home/nafys/dev/godot/godot3() [0x2e58934] (??:?)
[13] /home/nafys/dev/godot/godot3() [0xde38f6] (??:?)
[14] /home/nafys/dev/godot/godot3() [0xd6a483] (<artificial>:?)
[15] /home/nafys/dev/godot/godot3() [0xd6d339] (??:?)
[16] /home/nafys/dev/godot/godot3() [0xd6d570] (??:?)
[17] /home/nafys/dev/godot/godot3() [0x24bc0b7] (??:?)
[18] /home/nafys/dev/godot/godot3() [0x2e58934] (??:?)
[19] /home/nafys/dev/godot/godot3() [0xde38f6] (??:?)
[20] /home/nafys/dev/godot/godot3() [0xdd36e4] (??:?)
[21] /home/nafys/dev/godot/godot3() [0xdd448c] (??:?)
[22] /home/nafys/dev/godot/godot3() [0x1aaca96] (??:?)
[23] /home/nafys/dev/godot/godot3() [0x1aad57d] (<artificial>:?)
[24] /home/nafys/dev/godot/godot3() [0x2c2582f] (??:?)
[25] /home/nafys/dev/godot/godot3() [0xdd4cbb] (??:?)
[26] /home/nafys/dev/godot/godot3() [0xdbc54d] (??:?)
[27] /home/nafys/dev/godot/godot3() [0x1c0c1c5] (<artificial>:?)
[28] /home/nafys/dev/godot/godot3() [0x1c29b44] (<artificial>:?)
[29] /home/nafys/dev/godot/godot3() [0x1c2b515] (??:?)
[30] /home/nafys/dev/godot/godot3() [0x1c2b666] (<artificial>:?)
[31] /home/nafys/dev/godot/godot3() [0x2c2582f] (??:?)
[32] /home/nafys/dev/godot/godot3() [0xde38f6] (??:?)
[33] /home/nafys/dev/godot/godot3() [0xdbc5d5] (??:?)
[34] /home/nafys/dev/godot/godot3() [0x1c4ed17] (??:?)
[35] /home/nafys/dev/godot/godot3() [0x1c62700] (??:?)
[36] /home/nafys/dev/godot/godot3() [0x2f04639] (??:?)
[37] /home/nafys/dev/godot/godot3() [0x2ea87ec] (<artificial>:?)
[38] /home/nafys/dev/godot/godot3() [0x2f0721f] (<artificial>:?)
[39] /home/nafys/dev/godot/godot3() [0x97b24c] (??:?)
[40] /usr/lib/libc.so.6(__libc_start_main+0xf2) [0x7faa71345152] (??:0)
[41] /home/nafys/dev/godot/godot3() [0x98997e] (??:?)
-- END OF BACKTRACE --

</details>

**Steps to reproduce:**
[bug.zip](https://github.com/godotengine/godot/files/5797680/bug.zip)

open the project
open the instanced scene in new tab
save it
return to main scene

### PR DESCRIPTION
**Pull request by YuriSizov**
Fixes #45072. At least addresses the error. I would appreciate if someone with a Linux system could validate that there is a crash in beta5 and it is gone with this commit. Alternatively, #45150 can be used for the same testing in 3.2. They should be identical in the end.

From my tests, the error is gone both from the editor and from a running project. I've also tested that for a case described in #41995 the `disconnect` method is still called.

### CODE REVIEW

File: scene/gui/graph_edit.cpp [hunk 1]
```diff
@@ -409,8 +409,14 @@ void GraphEdit::remove_child_notify(Node *p_child) {
 	if (gn) {
 		gn->disconnect("position_offset_changed", callable_mp(this, &GraphEdit::_graph_node_moved));
 		gn->disconnect("raise_request", callable_mp(this, &GraphEdit::_graph_node_raised));
-		gn->disconnect("item_rect_changed", callable_mp((CanvasItem *)connections_layer, &CanvasItem::update));
-		gn->disconnect("item_rect_changed", callable_mp((CanvasItem *)minimap, &GraphEditMinimap::update));
+
+		// In case of the whole GraphEdit being destroyed these references can already be freed.
+		if (connections_layer->is_inside_tree()) {
```
Comment (qarmin) [inline scene/gui/graph_edit.cpp:414]: This isn't right solution because address sanitizer still show usage of freed memory.
If `connections_layer` is already removed by e.g. `memdelete` we can't use it anymore, because at this place there may already be completely different data here.

**Review by qarmin — CHANGES_REQUESTED** [review]

File: scene/gui/graph_edit.cpp (hunk 1 above)
Comment (pycbouh) [reply scene/gui/graph_edit.cpp:414]: Yes, I've concidered something like this. In my tests it was still a reference to an object, just not a valid object. I initially wanted something more robust, so in `3.2` version I've tried using `ObjectDB::instance_validate`, but the result was mixed. The errors were gone, but the disconnects were still being performed, they just didn't err anymore. Almost like calling `ObjectDB::instance_validate` refreshed the references.

Plus, there is no equivalent to this in `master`. I've tried several other ways to evaluate if those variables still point somewhere reasonable, but had no luck. So I considered that I may be overthinking this and tried this, and it worked just as expected. But a better way may have escaped me due to my lack of experience with C++ and memory management, and the whole object system in Godot.

So what would be a right solution? I can for example cast to to the expected type and check that before checking for the inside the tree?
```cpp
CanvasItem *cl = Object::cast_to<CanvasItem>(connections_layer);
if (cl && cl->is_inside_tree()) {
  ...
```
And the same for the minimap. Would that be sufficient?

Comment (qarmin) [reply scene/gui/graph_edit.cpp:414]: Deleted variables should never be used except when given a value or nullptr.
That variable doesn't contains information in runtime if is valid or not(unlike e.g. in Java) so it is .

I tested that and this code doesn't show any errors and warnings but I'm not sure if logic is good:
```
	if (gn) {
		gn->disconnect("offset_changed", this, "_graph_node_moved");
		gn->disconnect("raise_request", this, "_graph_node_raised");
		if (is_inside_tree()) {
			gn->disconnect("item_rect_changed", connections_layer, "update");
			gn->disconnect("item_rect_changed", minimap, "update");
		}
	}
```

Comment (pycbouh) [reply scene/gui/graph_edit.cpp:414]: This seems to be the same approach as was patched a couple of lines earlier for 
```cpp
top_layer->call_deferred("raise");
```

So I guess it works. 

Something more robust would probably be using the fact that `remove_child_notify` for those nodes would be called before it is called for `GraphNode`. So we can probably check if we are removing `connections_layer` and `top_layer` (for `minimap`) and give those variables `nullptr`. Then it would be a straightforward check here. What do you think about that?

Comment (pycbouh) [reply scene/gui/graph_edit.cpp:414]: So, something like this:

```cpp

void GraphEdit::remove_child_notify(Node *p_child) {
	Control::remove_child_notify(p_child);

	if (p_child == top_layer) {
		top_layer = nullptr;
		minimap = nullptr;
	}
	else if (p_child == connections_layer) {
		connections_layer = nullptr;
	}

	if (top_layer != nullptr && is_inside_tree()) {
		top_layer->call_deferred("raise"); // Top layer always on top!
	}

	GraphNode *gn = Object::cast_to<GraphNode>(p_child);
	if (gn) {
		gn->disconnect("position_offset_changed", callable_mp(this, &GraphEdit::_graph_node_moved));
		gn->disconnect("raise_request", callable_mp(this, &GraphEdit::_graph_node_raised));

		// In case of the whole GraphEdit being destroyed these references can already be freed.
		if (connections_layer != nullptr && connections_layer->is_inside_tree()) {
			gn->disconnect("item_rect_changed", callable_mp((CanvasItem *)connections_layer, &CanvasItem::update));
		}
		if (minimap != nullptr && minimap->is_inside_tree()) {
			gn->disconnect("item_rect_changed", callable_mp((CanvasItem *)minimap, &GraphEditMinimap::update));
		}
	}
}
```

Don't see any issues with the editor or a running project with that so far.

Comment (qarmin) [reply scene/gui/graph_edit.cpp:414]: I tested code from previous comment, and now doesn't use invalid memory.

**Review by qarmin — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by kleonc** [comment]
Probably fixes #44073.
