### PR TITLE
[Windows] Try reading GPU IDs directly from registry.

### LINKED ISSUE #95772: Projects using the "compatibility" rendering engine take a few seconds to run now
### Tested versions

- Reproducible in: v4.3.stable.official [77dcf97d8]
- Not Reproducible in: v4.2.stable.official [46dc277], v4.2.2.stable.official [15073af]

### System information

Godot v4.3.stable - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4050 Laptop GPU (NVIDIA; 32.0.15.5599) - 13th Gen Intel(R) Core(TM) i7-13650HX (20 Threads)

### Issue description

When you click the "Run Project" button, or the "Run Current Scene" button, or the "Run Specific Scene" button, then the window for the project will take a few seconds to open. But that's only if the rendering engine is set to compatibility. This makes it slower to playtest, since before 4.3 the project would run almost instantly. And this happens no matter how big or small the project/scene is.

### Steps to reproduce

- Create a new project with "compatibility" as the rendering engine, or take an existing project and switch it to compatibility
- If needed, create an empty scene for the project (it doesn't have to be empty, the scene can be anything)
- Run the project

### Minimal reproduction project (MRP)

[new-game-project.zip](https://github.com/user-attachments/files/16651992/new-game-project.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Same as https://github.com/godotengine/godot/pull/109346, but for ANGLE list. Also adds check to skip device ID check and ANGLE fallback on Wine.

Fixes https://github.com/godotengine/godot/issues/95772

### CODE REVIEW

File: platform/windows/display_server_windows.cpp [hunk 1]
```diff
@@ -6704,6 +6777,14 @@ Vector2i _get_device_ids(const String &p_device_name) {
 	return ids;
 }
 
+Vector2i _get_device_ids(const String &p_device_name) {
+	Vector2i out = _get_device_ids_info_reg(p_device_name);
+	if (out == Vector2i()) {
+		out = _get_device_ids_info_wmi(p_device_name);
```
Comment (clayjohn) [inline platform/windows/display_server_windows.cpp]: Is it possible for the registry not to have the ids while WMI does? Or is this fallback just there to be absolutely safe?

Comment (bruvzg) [reply platform/windows/display_server_windows.cpp]: Wine can have it missing (but WMI will fail on Wine as well), on real Windows it seems to always have it, so fallback probably not needed.

Comment (bruvzg) [reply platform/windows/display_server_windows.cpp]: But in case of Wine, it would make sense to skip the whole ANGLE check entirely, since on Linux using GL likely will work better than GL over DX11 over Vulkan.

Comment (clayjohn) [reply platform/windows/display_server_windows.cpp]: That's a good point. Let's go with this approach then.

**Review by clayjohn — APPROVED** [review]
Looks great!

File: platform/windows/display_server_windows.cpp [hunk 2]
```diff
@@ -7072,7 +7156,7 @@ DisplayServerWindows::DisplayServerWindows(const String &p_rendering_driver, Win
 	}
 
 	bool gl_supported = true;
-	if (fallback && (rendering_driver == "opengl3")) {
+	if (fallback && (rendering_driver == "opengl3") && !is_wine) {
```
Comment (AThousandShips) [inline platform/windows/display_server_windows.cpp]:
```suggestion
	if (fallback && !is_wine && (rendering_driver == "opengl3")) {
```

**Comment by Repiteo** [comment]
Thanks!
