### PR TITLE
Use defaults to initialize sky data in case of no sky

### LINKED ISSUE #79509: Using Fog Sun Scatter property on Windows 10 (QEMU) freezes system
### Godot version

v4.1-stable (latest from website)

### System information

Windows 10 (QEMU) Godot_v4.1-stable_win64 Forward+ Vulkan

### Issue description

I am using Shadow Cloud for development which is done using QEMU virtualization, so it's may be a problem with hardware virtualization

I can't capture video due to OBS crash after unfreezing

After 3 minute frezze i got this errors in console.

### Steps to reproduce

1. Create WorldEnvironment
2. Enable fog
3. Set any value to Sun Scatter property

### Minimal reproduction project

Blank project with 3D scene and WorldEnvironment

### PR DESCRIPTION
**Pull request by ParsleighScumble**
Fixes #79509. Effectively makes parameter "sky" optional - we only check it where it's used and everywhere it's not needed is not behind a condition anymore. Classic fog now no longer results in TDR when clear color is used for sky.

### CODE REVIEW

File: servers/rendering/renderer_rd/environment/sky.cpp [hunk 1]
```diff
@@ -1065,101 +1067,103 @@ void SkyRD::setup_sky(RID p_env, Ref<RenderSceneBuffersRD> p_render_buffers, con
...
-			// This can't be done in RenderSceneRenderRD::_setup lights because that needs to be called
-			// after the depth prepass, but this runs before the depth prepass
-			for (int i = 0; i < (int)p_lights.size(); i++) {
-				if (!light_storage->owns_light_instance(p_lights[i])) {
-					continue;
+	sky_scene_state.ubo.directional_light_count = 0;
+	if (shader_data->uses_light) {
+		// Run through the list of lights in the scene and pick out the Directional Lights.
+		// This can't be done in RenderSceneRenderRD::_setup lights because that needs to be called
+		// after the depth prepass, but this runs before the depth prepass
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/environment/sky.cpp:1076]:
```suggestion
		// after the depth prepass, but this runs before the depth prepass.
```
All comments should start with upper case (for the whole sentence), and end with period, including if they are just moved, apply same to others

Comment (ParsleighScumble) [reply servers/rendering/renderer_rd/environment/sky.cpp:1076]: Will do

**Review by clayjohn — COMMENTED** [review]
Looks good to me! The same changes are needed in GLES3 as well before this is ready to merge:

https://github.com/godotengine/godot/blob/0c2144da908a8223e188d27ed1d31d8248056c78/drivers/gles3/rasterizer_scene_gles3.cpp#L590

**Comment by ParsleighScumble** [comment]
One thing - I saw affect_sky fog property doesn't do anything to the clear color in GLES3. Should I fix that before we merge this?

**Comment by clayjohn** [comment]
> One thing - I saw affect_sky fog property doesn't do anything to the clear color in GLES3. Should I fix that before we merge this?

If you want to, then sure! But IMO that would be best done in a follow-up PR.

**Comment by clayjohn** [comment]
The updated code looks great! The final step before merging is to squash all the commits together so that the whole PR only contains 1 big commit with all your changes. We like to merge one commit at a time to keep the git history clean and navigable. 

If you don't know how to do that, we have a helpful tutorial in the official documentation https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase

**Comment by ParsleighScumble** [comment]
Should be good to go.

**Review by clayjohn — APPROVED** [review]
Looks good to me. 

I've tested locally and I didn't identify any regressions. I wasn't able to reproduce the reported bug though, so I can't confirm that it is actually fixed. 

At any rate, I am happy to move forward with merging this

**Comment by YuriSizov** [comment]
Thanks! And congrats on your first merged Godot PR!

**Comment by ParsleighScumble** [comment]
Thanks, Yuri!
