### PR TITLE
Fix `RichTextLabel`'s tag stack being overridden on translation change

### LINKED ISSUE #88532: Tooltip show empty for most properties when hovering
### Tested versions

Godot v4.3.dev (ae51db75e)

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3619) - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

### Issue description

It looks like all properties's tooltip can not be shown correctly when hovering,  I'm using TextEdit as an example below:

https://github.com/godotengine/godot/assets/8315986/ad2709d2-ecc7-484b-a977-4223db7cf55a

### Steps to reproduce

* Add any node to scene
* Hover some properties to check the tooltip

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by YeldhamDev**
Turns out my "regression" was just me stumbling into a bug. When `RichTextLabel` reacted to a translation change, it would try to translate its `text` variable, but if the content was added with the `add/push_*()` methods, said variable would be empty, and the tag stack would be overridden with an empty string.

Fixes #88532.

### CODE REVIEW

File: scene/gui/rich_text_label.cpp [hunk 1]
```diff
@@ -5650,10 +5650,15 @@ void RichTextLabel::set_text(const String &p_bbcode) {
 }
 
 void RichTextLabel::_apply_translation() {
+	// If `text` is empty, it could mean that the tag stack is being used instead. Leave it be.
```
Comment (akien-mga) [inline scene/gui/rich_text_label.cpp:5653]: How do we handle updated translations when using the tag stack then?

**Review by akien-mga — APPROVED** [review]

File: scene/gui/rich_text_label.cpp (hunk 1 above)
Comment (KoBeWi) [reply scene/gui/rich_text_label.cpp:5653]: I checked and the tooltips are still being translated, so it's done at the time of pushing the text.
