### PR TITLE
Fix `ScrollContainer` focus border issue

### LINKED ISSUE #100176: ScrollContainer focus StyleBox is not clipped by parent
### Tested versions

v4.4.dev6.official [1f47e4c4e]

### System information

Fedora Linux 40 (KDE Plasma) on Wayland - X11 display driver, Multi-window

### Issue description

Image

PR https://github.com/godotengine/godot/pull/97521 added a focus style for ScrollContainer this has the same problem as following issues:

Tree:
https://github.com/godotengine/godot/issues/100063
https://github.com/godotengine/godot/issues/88749
https://github.com/godotengine/godot/issues/74670

ItemList:
https://github.com/godotengine/godot/issues/77919

### Steps to reproduce

A ScrollContainer inside another ScrollContainer
Add some content to both
Enable draw_focus_border for second ScrollContainer
Select something in the second ScrollContainer so it gets focus
Scroll the first ScrollContainer

### Minimal reproduction project (MRP)

[scrollfocus.zip](https://github.com/user-attachments/files/18052689/scrollfocus.zip)

### LINKED ISSUE #105191: Sub-inspector background tint no longer appears
### Tested versions

Regression from #104339

### System information

W10

### Issue description

Inspector no longer tints the background of sub-resources. They appear with default inspector background.

### Steps to reproduce

1. Unfold a sub-Resource in the inspector
2. (optional) Unfold another nested resource
3. (optional) Repeat point 2

The Resource properties have corrected selection color, but the sub-inspectors don't.

Image

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by pafuent**
Fixes #100176 Fixes #105191

Instead of using no clipping technique to draw the focus border because it causes problems if a `ScrollContainer` is nested in another `ScrollContainer`, now the focus border is drawn using an internal `PanelContainer`.

ScrollConainerInsideAScrollContainerFocusStyle

Here is how `EditorInspector` is still working even when the no clipping was removed.
InspectorBorder

### CODE REVIEW

File: scene/gui/scroll_container.cpp [hunk 1]
```diff
@@ -350,6 +369,10 @@ void ScrollContainer::_reposition_children() {
 		fit_child_in_rect(c, r);
 	}
 
+	if (draw_focus_border) {
+		focus_panel->add_theme_style_override("panel", theme_cache.focus_style);
```
Comment (KoBeWi) [inline scene/gui/scroll_container.cpp:373]: This should happen in NOTIFICATION_THEME_CHANGED.

Comment (pafuent) [reply scene/gui/scroll_container.cpp:373]: `_reposition_children()` is being called conditionally on `NOTIFICATION_THEME_CHANGED`
```cpp
		case NOTIFICATION_ENTER_TREE:
		case NOTIFICATION_THEME_CHANGED:
		case NOTIFICATION_LAYOUT_DIRECTION_CHANGED:
		case NOTIFICATION_TRANSLATION_CHANGED: {
			_updating_scrollbars = true;
			callable_mp(this, is_ready() ? &ScrollContainer::_reposition_children : &ScrollContainer::_update_scrollbar_position).call_deferred();
		} break;
```
But now that I'm thinking it, I guess what you are trying to say is that doing this every time `_reposition_children()` is called is overkill and I should move those two lines to `_notification` to run only when the theme is changed

**Comment by pafuent** [comment]
I added a call to `_reposition_children` on `set_draw_focus_border` to draw the focus border without requiring a reload

File: scene/gui/scroll_container.cpp (hunk 1 above)
Comment (KoBeWi) [reply scene/gui/scroll_container.cpp:373]: Yes.

**Comment by KoBeWi** [comment]
Now I noticed that the focus style increases margins. It's especially noticeable in the inspector, where this makes less available space.
ScrollContainer already has a margin from `panel` style. You could draw focus over the panel and use maximum of their margins as content margin, instead of adding them.

File: scene/gui/scroll_container.cpp [hunk 2]
```diff
@@ -399,6 +450,9 @@ void ScrollContainer::_notification(int p_what) {
 			if (p_what == NOTIFICATION_THEME_CHANGED) {
 				scroll_border = get_theme_constant(SNAME("scroll_border"), SNAME("Tree"));
 				scroll_speed = get_theme_constant(SNAME("scroll_speed"), SNAME("Tree"));
+				if (draw_focus_border) {
```
Comment (KoBeWi) [inline scene/gui/scroll_container.cpp:453]: This condition is not needed.

File: scene/gui/scroll_container.cpp [hunk 3]
```diff
@@ -313,8 +347,22 @@ void ScrollContainer::_reposition_children() {
 	Size2 size = get_size();
 	Point2 ofs;
 
+	Point2 panel_offset = theme_cache.panel_style->get_offset();
+	Size2 panel_size = theme_cache.panel_style->get_minimum_size();
 	size -= theme_cache.panel_style->get_minimum_size();
 	ofs += theme_cache.panel_style->get_offset();
```
Comment (KoBeWi) [inline scene/gui/scroll_container.cpp:353]:
```suggestion
	size -= panel_size;
	ofs += panel_offset;
```

File: scene/gui/scroll_container.cpp [hunk 4]
```diff
@@ -536,6 +583,9 @@ void ScrollContainer::_notification(int p_what) {
 void ScrollContainer::update_scrollbars() {
 	Size2 size = get_size();
 	size -= theme_cache.panel_style->get_minimum_size();
+	if (draw_focus_border) {
+		size -= theme_cache.focus_style->get_minimum_size();
+	}
```
Comment (KoBeWi) [inline scene/gui/scroll_container.cpp:588]: This adds the stylebox sizes instead of using maximum like in other methods.

**Review by KoBeWi — APPROVED** [review]
Supersedes #105214

**Comment by Repiteo** [comment]
Thanks!

**Comment by Maran23** [comment]
I guess the same fix can be applied to fix https://github.com/godotengine/godot/issues/88749 for `Tree`? From looking into the code, it really looks like the same issue!
