### PR TITLE
Properly implement Basis constructor using Vector3 of Euler angles

### LINKED ISSUE #13104: ERROR: add_register_func: Condition ' register_funcs.has(p_name) ' is true.
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux, current master (82ad05a20)

**Issue description:**
This new error is shown when starting the editor:
```
ERROR: add_register_func: Condition ' register_funcs.has(p_name) ' is true.
   At: modules/visual_script/visual_script.cpp:2643.
```

It wasn't there this morning, so it comes from a PR merged today. *Edit:* Though I don't see any PR changing visual_script in the last 3 days, so not sure.

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #13104.

Regarding binding such constructors: take note that `can_convert` must also be changed, it was already done for this constructor in #13080 but that was incomplete.

### CODE REVIEW

File: core/variant.cpp [hunk 1]
```diff
@@ -1632,7 +1633,9 @@ Variant::operator Basis() const {
 		return *_data._basis;
 	else if (type == QUAT)
 		return *reinterpret_cast<const Quat *>(_data._mem);
-	else if (type == TRANSFORM)
+	else if (type == VECTOR3) {
+		return Basis(*reinterpret_cast<const Vector3 *>(_data._mem));
+	} else if (type == TRANSFORM) // unexposed in Variant::can_convert?
```
Comment (akien-mga) [inline core/variant.cpp]: This was already there, but it's not listed as valid in `Variant::can_convert`. Should it be added?

File: core/variant.cpp [hunk 2]
```diff
@@ -513,6 +513,7 @@ bool Variant::can_convert_strict(Variant::Type p_type_from, Variant::Type p_type
 
 			static const Type valid[] = {
 				QUAT,
+				VECTOR3,
```
Comment (akien-mga) [inline core/variant.cpp]: I'm not sure if this change is needed. I understand that the type must be added to `Variant::can_convert`, but what about `Variant::can_convert_strict`? @reduz

**Comment by akien-mga** [comment]
CC @tagcup

**Comment by tagcup** [comment]
I have no idea how gdscript works actually...

**Comment by akien-mga** [comment]
Well it was just FYI, since you were the one looking for how to do this properly, and AIUI this seems to be the proper way.

**Comment by tagcup** [comment]
Thanks but I switched to C# and GDNative completely (and mine is a hobby project anyway), and I don't think I'll use GDScript again, so...

**Comment by akien-mga** [comment]
Well, sorry for mentioning you then.
