### PR TITLE
GDScript: Out of order member resolution

### LINKED ISSUE #44375: GDScript 2.0: "Parser bug (please report): Trying to check compatibility of unset value type" error
**Godot version:**
current master 4.0 a511a26ad

**OS/device including version:**
Windows 10

**Issue description:**
E 0:00:00:0827   is_type_compatible: Parser bug (please report): Trying to check compatibility of unset value type
  <C++ Error>    Condition "!p_source.is_set()" is true. Returning: true
  <C++ Source>   modules/gdscript/gdscript_analyzer.cpp:3157 @ is_type_compatible()

**Steps to reproduce:**
I don't know because debugger don't show me where it is in my code.
Empty project don't do that

**Minimal reproduction project:**
n/a

### LINKED ISSUE #67085: GDScript 2.0: Script with function assigned to `@onready` variable generates "tried to assign unset node without an identifier" errors
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Windows 11, GLES3, NVIDIA GeForce GTX 1650, i5-11300H

### Issue description

image

it prints these 2 errors constantly while im writing in that file:
`Parser bug (please report): Trying to check compatibility of unset value type`
and
`modules/gdscript/gdscript_analyzer.cpp:668 - Parser bug (please report): tried to assign unset node without an identifier.`

### Steps to reproduce

create a new scene and attach this script to the root node
```
extends Node

@export_file("*.txt") var path_to_words_file: String

@onready var hebrew_words: Dictionary = _create_dict()

func get_random_word() -> String:
	var array = hebrew_words[get_random_letter()]
	return array[randi_range(0, array.size() - 1)]

func get_random_letter() -> String:
	return hebrew_words.keys()[randi_range(0, hebrew_words.keys().size() - 1)]

func save_dictonary(path: String = path_to_words_file) -> void:
	var file = FileAccess.open(path, FileAccess.WRITE)
	var json_string = JSON.stringify(hebrew_words, '\t')
	file.store_string(json_string)
	

# Create a dictonary with each hebrew letter as keys
func _create_dict() -> Dictionary:
	var file = FileAccess.open(path_to_words_file, FileAccess.READ)
	var hebrew_dict: Dictionary = {}
	for letter in "אבגדהוזחטיכלמנסעפצקרשת":
		hebrew_dict[letter] = []
	while not file.eof_reached():
		var current_word: String = file.get_line()
		current_word = current_word.replacen(",", '')
		current_word = current_word.replacen("\"", '')
		if current_word:
			var current_letter: = current_word[0]
			if current_letter in hebrew_dict.keys():
				hebrew_dict[current_letter].append(current_word)
	return hebrew_dict

```

### Minimal reproduction project

_No response_

### LINKED ISSUE #68017: GDScript 2.0: When assigning a function to a variable before function results in a lot of errors when pressing "Ctrl".
### Godot version

4.0.beta3

### System information

Windows 10, Forward+, RX Vega 56

### Issue description

In any script when assigning a function to a variable before the function results in an error when pressing the key "Ctrl" in the script editor or when starting the project: "modules/gdscript/gdscript_analyzer.cpp:668 - Parser bug (please report): tried to assign unset node without an identifier.". Works in latest version of Godot 3. 

### Steps to reproduce

1.Create a project
2.Create a script for any node
3.Create a variable and a function below it, assign the function to a variable
4.press "Ctrl" in the editor or start the project

### Minimal reproduction project

[Editor_bug.zip](https://github.com/godotengine/godot/files/9893770/Editor_bug.zip)

### LINKED ISSUE #68069: GDScript cannot infer the type of a variable initialized with a typed method call
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

KDE neon 22.04

### Issue description

(_Sorry in advance if the following bug was reported before, or is already fixed. I couldn't find anything related._)

(_Edit: Added the MRP._)

It seems that the GDScript parser cannot infer the type of a _typed_ user method ahead of its definition.

```gdscript
extends Node

var some_var := some_func()

# NOTE: It doesn't matter if you qualify the method as `static` or not.
static func some_func() -> int:
	return 42
```

The code above will trigger a parser error notification on both the script editor and the debug console, as follows:

```
  modules/gdscript/gdscript_analyzer.cpp:668 - Parser bug (please report): tried to assign unset node without an identifier.
  res://bug_2.gd:3 - Parse Error: Cannot infer the type of "some_var" variable because the initial value doesn't have a set type.
  modules/gdscript/gdscript_analyzer.cpp:668 - Parser bug (please report): tried to assign unset node without an identifier.
  modules/gdscript/gdscript_analyzer.cpp:668 - Parser bug (please report): tried to assign unset node without an identifier.
```

editor_screenshot_2022-10-30T221805

For comparison: that same code works on Godot 3.5.

Either declaring the variable after the method or replacing the type inferred assignment (`:=`) works fine.

### Steps to reproduce

Creating a script with the following content on any project triggers the error:

```gdscript
extends Node

var some_var := some_func()

static func some_func() -> int:
	return 42

# func some_func() -> int:
#	return 42
```

### Minimal reproduction project

[68069.zip](https://github.com/godotengine/godot/files/9910850/68069.zip)

### LINKED ISSUE #69479: Setting @onready var variable value by calling a function inside the same class causes a parser bug.
### Godot version

v4.0.beta4.official [e6751549c].

### System information

Windows 11.

### Issue description

> What doesn't work…

I have a variable called `_state_list` with the `@onready` annotation whose value is set by calling the method `_fetch_state_list()`:
```gdscript
# This is a custom state machine class that extends node.
@export var state_machine: StateMachine

@onready var _state_list: Array[StringName] = _fetch_state_list()

func _fetch_state_list() -> Array[StringName]:
	_state_list.clear()
	
	for child in state_machine.get_children():
		if child is State:
			_state_list.append(child.name)
	
	return _state_list
```

The value assignment itself works with no issues, but the editor keeps displaying this pair of error messages in the output panel:
```
  modules/gdscript/gdscript_analyzer.cpp:668 - Parser bug (please report): tried to assign unset node without an identifier.
  Parser bug (please report): Trying to check compatibility of unset value type
```

This pair of error messages appear when I opened the project; each time I opened, or in any way interacted with, the `.gd` file that contains the code in the topmost code block; and when I run the project. They also appear five-six times for every keystroke I made editing the script, and simply writing a few lines could easily flood the output panel with hundreds of error messages.

This pair of error messages also appear in the debugger panel each time I run the project:

```
E 0:00:00:0677   resolve_class_interface: Parser bug (please report): tried to assign unset node without an identifier.
  <C++ Source>   modules/gdscript/gdscript_analyzer.cpp:668 @ resolve_class_interface()
E 0:00:00:0677   is_type_compatible: Parser bug (please report): Trying to check compatibility of unset value type
  <C++ Error>    Condition "!p_source.is_set()" is true. Returning: true
  <C++ Source>   modules/gdscript/gdscript_analyzer.cpp:4098 @ is_type_compatible()

```

> […] and how do you expect it to work instead?

I expect it not to output error messages, especially because the variable value assignment actually works. I have also tried using the latest official version (v4.0.beta7.official [0bb1e89fb]), but it still happens.

Is this a bug or am I just doing things wrong?

### Steps to reproduce

Attach a script onto any node that contains this code block:
```gdscript
@onready var test_variable: int = fetch_test_variable()


func fetch_test_variable() -> int:
	return 10
```

It happens every time there is a variable with the `@onready` annotation whose value is assigned by calling a method that is inside the same class. The variable and return type and value do not seem to matter, I just happened to use an `int` value.

It does not happen if the method comes from outside the class; I have tried assigning a value to the variable by calling a method from a singleton (autoload) and from a child node, and no error messages appeared. It also does not happen if I set `test_variable` on the `_ready()` function, which I thought was what `@onready` was supposed to emulate.

### Minimal reproduction project

I think it is pretty trivial to reproduce this error, but I uploaded a reproduction project anyway.

[Onready Error.zip](https://github.com/godotengine/godot/files/10139334/Onready.Error.zip)

### LINKED ISSUE #69763: GDScript 2.0: @onready var using static func results in Parser bug
### Godot version

v4.0.beta6.official [7f8ecffa5]

### System information

Windows 10, MacOS

### Issue description

I using a texture image converter as a static function called add ready var assignment.

```gdscript

extends Control


@onready var ICON_SPINNER = load("res://assets/spinner.tres")
@onready var ICON_TEST_DEFAULT :ImageTexture = load_resized_texture("res://assets/TestCase.svg")

@onready var _tree :Tree = $Tree


var _tree_root :TreeItem


static func load_resized_texture(path :String, width :int = 16, height :int = 16) -> ImageTexture:
	var texture :CompressedTexture2D = load(path)
	var image = texture.get_image()
	if width > 0 && height > 0:
		image.resize(width, height)
	return ImageTexture.create_from_image(image)

```
The editor console shows an error during loading the script.

```
  modules/gdscript/gdscript_analyzer.cpp:667 - Parser bug (please report): tried to assign unset node without an identifier.
  Parser bug (please report): Trying to check compatibility of unset value type
  modules/gdscript/gdscript_analyzer.cpp:667 - Parser bug (please report): tried to assign unset node without an identifier.
  Parser bug (please report): Trying to check compatibility of unset value type
  modules/gdscript/gdscript_analyzer.cpp:667 - Parser bug (please report): tried to assign unset node without an identifier.
  Parser bug (please report): Trying to check compatibility of unset value type
  modules/gdscript/gdscript_analyzer.cpp:667 - Parser bug (please report): tried to assign unset node without an identifier.
  Parser bug (please report): Trying to check compatibility of unset value type
  modules/gdscript/gdscript_analyzer.cpp:667 - Parser bug (please report): tried to assign unset node without an identifier.
  Parser bug (please report): Trying to check compatibility of unset value type
  modules/gdscript/gdscript_analyzer.cpp:667 - Parser bug (please report): tried to assign unset node without an identifier.
  Parser bug (please report): Trying to check compatibility of unset value type
````

And additional errors when run the scene
image

### Steps to reproduce

download the example project and run the scene

### Minimal reproduction project

[onready_bug.zip](https://github.com/godotengine/godot/files/10185945/onready_bug.zip)

### PR DESCRIPTION
**Pull request by rune-scape**
Implements out of order member resolution
-- this was allowed in some specific places, but this PR pulls it out into its own function to make the behavior consistent
-- and allow more complex ordering

class members are now resolved just before they are needed
-- This means class members will always have resolved types before used, else an error is pushed
same goes for members of external classes
-- This fixes alot of dependency errors.

also fixes a few minor bugs:
-- singleton datatypes now get properly resolved in extends
-- Object and Variant no longer allow array syntax (`Variant[int]` doesn't parse)
-- pushes an error if a native enum doesn't exist when resolving a type
those were all just missing a line or 2

fixes #68069
fixes #69479
fixes #67085
fixes #69763
fixes https://github.com/godotengine/godot/issues/68017
may fix #44375 (didn't read the all the comments, but it addresses the problem in the most recent ones)

### CODE REVIEW

**Comment by MewPurPur** [comment]
Does this address https://github.com/godotengine/godot/issues/61159?

File: modules/gdscript/gdscript_parser.h [hunk 1]
```diff
@@ -601,6 +620,33 @@ class GDScriptParser {
...
+						return m_class;
+					case CONSTANT:
+						return constant;
+					case FUNCTION:
+						return function;
+					case VARIABLE:
+						return variable;
+					case ENUM:
+						return m_enum;
+					case ENUM_VALUE: {
```
Comment (anvilfolk) [inline modules/gdscript/gdscript_parser.h:635]: Gonna be super picky, but why do these have `{}` if they're just returning? :)

**Comment by rune-scape** [comment]
@MewPurPur i can checkin a bit, but my instinct is no

File: modules/gdscript/gdscript_parser.h [hunk 2]
```diff
@@ -577,20 +606,10 @@ class GDScriptParser {
 					case ENUM:
 						return m_enum->get_datatype();
 					case ENUM_VALUE: {
-						// Always integer.
-						DataType out_type;
-						out_type.type_source = DataType::ANNOTATED_EXPLICIT;
-						out_type.kind = DataType::BUILTIN;
-						out_type.builtin_type = Variant::INT;
-						return out_type;
+						return enum_value.identifier->get_datatype();
```
Comment (anvilfolk) [inline modules/gdscript/gdscript_parser.h:609]: This change looks super sensible, and makes `ENUM_VALUE` and `SIGNAL` conform to all the other types.

I guess the concern is just that there might be a situation in which the identifiers haven't been fully resolved, at which point this would return garbage, right? Just a reminder to double-check that this will never be null.

File: modules/gdscript/gdscript_parser.h (hunk 1 above)
Comment (adamscott) [reply modules/gdscript/gdscript_parser.h:635]: Maybe just uniformize the switch case. Either adding `{}` to each `case`, or remove them altogether.

File: modules/gdscript/gdscript_parser.cpp [hunk 3]
```diff
@@ -642,6 +642,52 @@ void GDScriptParser::parse_program() {
...
+		result = head;
+	} else if (head->has_member(first)) {
+		class_names = p_qualified_name.split("::");
+		GDScriptParser::ClassNode::Member member = head->get_member(first);
+		if (member.type == GDScriptParser::ClassNode::Member::CLASS) {
+			result = member.m_class;
+		}
+	}
+
+	for (int i = 1; result != nullptr && i < class_names.size(); i++) {
```
Comment (anvilfolk) [inline modules/gdscript/gdscript_parser.cpp:666]: `// Starts at 1 because the 0 is `first` which was handled above.`

It really throws me when `for` loops don't start at 0 :) in this case, it also works even if `first == nullptr` because in that case, class_names has a single element, and therefore `1 < 1` fails and the loop doesn't run.

It all checks out! <3

File: modules/gdscript/gdscript_parser.cpp [hunk 4]
```diff
@@ -642,6 +642,52 @@ void GDScriptParser::parse_program() {
...
+	}
+
+	return result;
+}
+
+bool GDScriptParser::has_class(const GDScriptParser::ClassNode *p_class) const {
+	if (head->fqcn.is_empty() && p_class->fqcn.get_slice("::", 0).is_empty()) {
+		return p_class == head;
+	} else if (p_class->fqcn.begins_with(head->fqcn)) {
+		return find_class(p_class->fqcn.trim_prefix(head->fqcn)) == p_class;
```
Comment (anvilfolk) [inline modules/gdscript/gdscript_parser.cpp:685]: Does `head->fqcn` contain `::`? Wouldn't this potentially `find_class("::some_weird::class_path")`, which would make `first` in `find_class` an empty string?

File: modules/gdscript/gdscript_parser.h (hunk 1 above)
Comment (rune-scape) [reply modules/gdscript/gdscript_parser.h:635]: ah, thanks! just a formatting mistake from a copy-paste

File: modules/gdscript/gdscript_analyzer.cpp [hunk 5]
```diff
@@ -234,6 +264,9 @@ Error GDScriptAnalyzer::resolve_inheritance(GDScriptParser::ClassNode *p_class,
 	}
 
 	GDScriptParser::DataType result;
+	result.kind = GDScriptParser::DataType::RESOLVING;
+	p_class->base_type = result;
+	result.kind = GDScriptParser::DataType::UNRESOLVED;
```
Comment (anvilfolk) [inline modules/gdscript/gdscript_analyzer.cpp:269]: Wouldn't line 268 invoke the copy constructor?

```
DataType(const DataType &p_other) {
	*this = p_other;
}
```
Looks like this would simply make `p_class->base_type` point to the same object as `result`, so that `p_class->base_type.kind` will be `UNRESOLVED`?

**Comment by adamscott** [comment]
As is, this PR fixes #69479. I just tested it.

File: modules/gdscript/gdscript_parser.h (hunk 2 above)
Comment (rune-scape) [reply modules/gdscript/gdscript_parser.h:609]: well, `member.get_datatype()` should (in this pr) only be called after `resolve_class_member()` was called, otherwise it will return garbage or a resolving type (which is intentional), 
datatype resolution should always be done before this method is called
ill put that in the description :)
also enum values don't get added if parsing the id fails

File: modules/gdscript/gdscript_parser.cpp (hunk 3 above)
Comment (rune-scape) [reply modules/gdscript/gdscript_parser.cpp:666]: ya, it does look a bit confusing, ill add a comment. thanks!

File: modules/gdscript/gdscript_parser.cpp (hunk 4 above)
Comment (rune-scape) [reply modules/gdscript/gdscript_parser.cpp:685]: it's actually supposed to call `find_class` with that empty initial name (`"::some_weird::class_path"`) because that means start at the head
https://github.com/rune-scape/godot/blob/85025ff3b6dcd49dac22e2f3d5883a719f56d166/modules/gdscript/gdscript_parser.cpp#L650-L651

File: modules/gdscript/gdscript_analyzer.cpp [hunk 6]
```diff
@@ -314,11 +347,12 @@ Error GDScriptAnalyzer::resolve_inheritance(GDScriptParser::ClassNode *p_class,
 					return ERR_PARSE_ERROR;
 				}
 
-				Error err = info_parser->raise_status(GDScriptParserRef::INTERFACE_SOLVED);
+				Error err = info_parser->raise_status(GDScriptParserRef::INHERITANCE_SOLVED);
 				if (err != OK) {
 					push_error(vformat(R"(Could not resolve super class inheritance from "%s".)", name), p_class);
 					return err;
 				}
+				base = info_parser->get_parser()->head->get_datatype();
```
Comment (anvilfolk) [inline modules/gdscript/gdscript_analyzer.cpp:355]: Good eye catching this one! There have been a few issues with `autoloads` and this might be the source of at least a few of them?

Comment (rune-scape) [reply modules/gdscript/gdscript_analyzer.cpp:355]: haha, yea, probably! i figured it was small enough that no one would care if it got fixed here 😄

File: modules/gdscript/gdscript_analyzer.cpp [hunk 7]
```diff
@@ -403,30 +435,33 @@ Error GDScriptAnalyzer::resolve_inheritance(GDScriptParser::ClassNode *p_class,
...
+	}
+
+	if (!p_type->get_datatype().has_no_type()) {
+		return p_type->get_datatype();
+	}
+
+	GDScriptParser::DataType result;
+	result.kind = GDScriptParser::DataType::RESOLVING;
+	p_type->set_datatype(result);
 	result.type_source = result.ANNOTATED_EXPLICIT;
```
Comment (anvilfolk) [inline modules/gdscript/gdscript_analyzer.cpp:464]: Minor issue with original code (not even yours), but isn't line 464 more correctly stated as the following?
`result.type_source = GDScriptParser::DataType::ANNOTATED_EXPLICIT;` rather than `result.ANNOTATED_EXPLICIT;`?

File: modules/gdscript/gdscript_analyzer.cpp [hunk 8]
```diff
@@ -439,29 +474,21 @@ GDScriptParser::DataType GDScriptAnalyzer::resolve_datatype(GDScriptParser::Type
...
 	if (first == SNAME("Variant")) {
-		result.kind = GDScriptParser::DataType::VARIANT;
 		if (p_type->type_chain.size() > 1) {
-			push_error(R"("Variant" type don't contain nested types.)", p_type->type_chain[1]);
-			return GDScriptParser::DataType();
+			// TODO: Variant does actually have a nested Type though.
+			push_error(R"(Variant doesn't contain nested types.)", p_type->type_chain[1]);
+			return bad_type;
 		}
-		return result;
```
Comment (anvilfolk) [inline modules/gdscript/gdscript_analyzer.cpp:447]: Shouldn't this be returning something within `if (first == SNAME("Variant")) {...}`, if chain size is 1?

File: modules/gdscript/gdscript_analyzer.cpp (hunk 5 above)
Comment (rune-scape) [reply modules/gdscript/gdscript_analyzer.cpp:269]: yes, it copies the datatype over to `base_type` then switches the local variable `result`, but `base_type` is a copy, it isn't affected, i'll add a comment to this and others

File: modules/gdscript/gdscript_analyzer.cpp (hunk 7 above)
Comment (rune-scape) [reply modules/gdscript/gdscript_analyzer.cpp:464]: yep you're right, i'll change that

File: modules/gdscript/gdscript_analyzer.cpp (hunk 8 above)
Comment (rune-scape) [inline modules/gdscript/gdscript_analyzer.cpp:447]: i was very annoyed that Variant and Object were the only ones to return a good result early
removing this actually fixes an annoying bug that allows the type `Variant[int]` but chops off the `[int]` part in the analyzer. same with Object

Comment (anvilfolk) [reply modules/gdscript/gdscript_analyzer.cpp:447]: Yeah, deleted my comment after realizing that you can probably still fill out some stuff later, so you can do all these checks and do some partial fills :)

Comment (rune-scape) [reply modules/gdscript/gdscript_analyzer.cpp:447]: :)

File: modules/gdscript/gdscript_analyzer.cpp [hunk 9]
```diff
@@ -523,29 +555,30 @@ GDScriptParser::DataType GDScriptAnalyzer::resolve_datatype(GDScriptParser::Type
...
 					case GDScriptParser::ClassNode::Member::CLASS:
-						result = member.m_class->get_datatype();
+						result = member.get_datatype();
 						found = true;
 						break;
 					case GDScriptParser::ClassNode::Member::ENUM:
-						result = member.m_enum->get_datatype();
+						result = member.get_datatype();
 						found = true;
 						break;
```
Comment (anvilfolk) [inline modules/gdscript/gdscript_analyzer.cpp:568]: You can now let `CLASS` fallthrough to `ENUM` since the code is the same! Wonder if there's any other places where this could be done :)

**Comment by rune-scape** [comment]
@anvilfolk and @adamscott thank you for reviewing!

**Comment by rune-scape** [comment]
Technically this could be expanded to allow the analyzer to resolve individual members of other scripts, allowing member dependencies both ways between script interfaces, but i'm not sure anyone has a use for that 🙂

**Comment by anvilfolk** [comment]
> Technically this could be expanded to allow the analyzer to resolve individual members of other scripts, allowing member dependencies both ways between script interfaces, but i'm not sure anyone has a use for that 🙂

Wouldn't this actually be really neat now that cyclic dependencies are possible? Could probably come up with a small interesting case like:

```GDScript
# A.gd

var a := B.b_func()

static func a_func() -> int:
  return 42


# B.gd

static func b_func() -> int:
  return A.a_func()
```

Something like that?

**Comment by rune-scape** [comment]
@anvilfolk exactly! i do kinda wanna see how difficult it is, so i'll put it on my todo list 😄 
who knows, maybe its dead simple

**Comment by rune-scape** [comment]
i added braces inside `resolve_class_member()` to make the diff much more readable

File: modules/gdscript/gdscript_analyzer.cpp [hunk 10]
```diff
@@ -615,194 +646,246 @@ GDScriptParser::DataType GDScriptAnalyzer::resolve_datatype(GDScriptParser::Type
...
+	}
 
 	GDScriptParser::ClassNode *previous_class = parser->current_class;
 	parser->current_class = p_class;
 
-	for (int i = 0; i < p_class->members.size(); i++) {
-		GDScriptParser::ClassNode::Member member = p_class->members[i];
-
-		switch (member.type) {
+	{
```
Comment (rune-scape) [inline modules/gdscript/gdscript_analyzer.cpp:686]: this block is just here to make the diff is more readable

Comment (adamscott) [reply modules/gdscript/gdscript_analyzer.cpp:686]: Oh, I understand now what you meant. No need for a block, as in the settings of Github, you can hide whitespace and change the way Github shows the diff.

image

**Comment by rune-scape** [comment]
@MewPurPur no, this doesn't fix https://github.com/godotengine/godot/issues/61159, but i found the bug.
https://github.com/godotengine/godot/pull/69518 fixes that

File: modules/gdscript/gdscript_analyzer.cpp (hunk 10 above)
Comment (rune-scape) [reply modules/gdscript/gdscript_analyzer.cpp:686]: ooo ok

File: modules/gdscript/gdscript_analyzer.cpp [hunk 11]
```diff
@@ -615,431 +646,560 @@ GDScriptParser::DataType GDScriptAnalyzer::resolve_datatype(GDScriptParser::Type
...
-				}
-				// TODO: Make MethodInfo from signal.
-				GDScriptParser::DataType signal_type;
-				signal_type.type_source = GDScriptParser::DataType::ANNOTATED_EXPLICIT;
-				signal_type.kind = GDScriptParser::DataType::BUILTIN;
-				signal_type.builtin_type = Variant::SIGNAL;
+			// TODO: Make MethodInfo from signal.
+			datatype.type_source = GDScriptParser::DataType::ANNOTATED_EXPLICIT;
+			datatype.kind = GDScriptParser::DataType::BUILTIN;
+			datatype.builtin_type = Variant::SIGNAL;
```
Comment (anvilfolk) [inline modules/gdscript/gdscript_analyzer.cpp:857]: This is duplicated code from before the `for` loop I believe.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 12]
```diff
@@ -615,431 +646,560 @@ GDScriptParser::DataType GDScriptAnalyzer::resolve_datatype(GDScriptParser::Type
...
+			for (GDScriptParser::AnnotationNode *&E : p_member.signal->annotations) {
+				E->apply(parser, p_member.signal);
+			}
+		} break;
+		case GDScriptParser::ClassNode::Member::ENUM: {
+			check_class_member_name_conflict(p_class, p_member.m_enum->identifier->name, p_member.m_enum);
+
+			GDScriptParser::DataType datatype;
+			datatype.kind = GDScriptParser::DataType::RESOLVING;
+			p_member.m_enum->set_datatype(datatype);
```
Comment (anvilfolk) [inline modules/gdscript/gdscript_analyzer.cpp:871]: Like you had a `bad_type` elsewhere, could you also just have a single `resolving_type` at the top of this function that gets set everywhere? This avoids having to `datatype = DataType()` to reuse all the time?

Comment (rune-scape) [reply modules/gdscript/gdscript_analyzer.cpp:871]: good point, thats much cleaner

File: modules/gdscript/gdscript_analyzer.cpp (hunk 11 above)
Comment (rune-scape) [reply modules/gdscript/gdscript_analyzer.cpp:857]: yes it is, fixing

File: modules/gdscript/gdscript_analyzer.cpp (hunk 10 above)
Comment (rune-scape) [reply modules/gdscript/gdscript_analyzer.cpp]: this actually doesn't make it more readable for whatever reason

**Comment by adamscott** [comment]
I cannot NOT underline the great teamwork between you both, @rune-scape and @anvilfolk. <3

**Comment by adamscott** [comment]
> > Technically this could be expanded to allow the analyzer to resolve individual members of other scripts, allowing member dependencies both ways between script interfaces, but i'm not sure anyone has a use for that slightly_smiling_face
> 
> Wouldn't this actually be really neat now that cyclic dependencies are possible? Could probably come up with a small interesting case like:
> 
> ```gdscript
> # A.gd
> 
> var a := B.b_func()
> 
> static func a_func() -> int:
>   return 42
> 
> 
> # B.gd
> 
> static func b_func() -> int:
>   return A.a_func()
> ```
> 
> Something like that?

Here's what I added in the GDScript tests with #67714:

https://github.com/godotengine/godot/blob/5704055d30499cc63672d44001760a98abfbfc08/modules/gdscript/tests/scripts/analyzer/features/preload_cyclic_reference.gd#L1-L4

https://github.com/godotengine/godot/blob/6f1d4fd8871155efcb29d115a7168879948e1cf3/modules/gdscript/tests/scripts/analyzer/features/preload_cyclic_reference_a.notest.gd#L1-L12

https://github.com/godotengine/godot/blob/6f1d4fd8871155efcb29d115a7168879948e1cf3/modules/gdscript/tests/scripts/analyzer/features/preload_cyclic_reference_b.notest.gd#L1-L10

**Comment by rune-scape** [comment]
oh, thats right, the status is set to resolved Before it gets resolved, so that does already work, huh
looks like it was dead simple!

**Comment by anvilfolk** [comment]
On that note, I think it'd be really neat to add a unit test showcasing something that wasn't possible before but is now possible, so that out-of-order member resolution is never lost from this point forward :)

All in all, I think this is an excellent PR! Really appreciate @rune-scape and their patience in letting me pick at their code and generally being an annoying little .... :)

After being stuck in line-by-line code, I just want to double check that I understand the big picture:

Instead of resolving functions first, then class members, and having a specific order in which things are allowed to depend on one another, this PR basically does "on demand" resolution. If a function, variable, subclass, whatever, called `member` depends on something else, you immediately attempt to resolve it.

If, while resolving one of those dependencies you find that one of the things you are attempting to resolve is `RESOLVING`, i.e., in the process of being resolved as well, then you have cyclic types and are unable to resolve from then on and you throw an error.

However, if you managed to resolve this big long line of type dependency all the way to the end (probably at builtin/native types or GDScript classes with no further dependencies?), then everything along that line has been resolved. You're likely to eventually try to re-resolve some of those (e.g. the `for` loop for members in resolving class interfaces/body) but every resolve function has a check on whether something's already been resolved, and you can skip doing that work again. No harm no foul.



Ultimately, it passes every unit test and fixes a couple of issues. The code looks lovely, needing only a couple teeny tiny optional tweaks. With the addition of a unit test showcasing GDScript's new capabilities, I'd say merge merge merge :)

This was a lovely opportunity to learn more GDScript internals - thanks @rune-scape <3

**Comment by adamscott** [comment]
Congrats for your PR, @rune-scape!

I second the idea to create unit tests though! A great way to make sure we don't mess up your work in the future. 🙃

**Comment by rune-scape** [comment]
@anvilfolk Yes! Exactly!
i am working on unit tests, and also now that @adamscott pointed out that dependencies between members in scripts can already exist, im working on resolving individual members of other scripts, for better error messages

**Comment by rune-scape** [comment]
> letting me pick at their code and generally being an annoying little .... :)
thank you for picking at my code! it's better now :)

**Comment by adamscott** [comment]
@rune-scape Don't forget to rebase your branch, just to be sure to test your code with the latest merges.

**Comment by adamscott** [comment]
I ran @KoBeWi's huge project as a test for your PR. Here's an error that I got.

image

Seems that it doesn't like casting of nodes.

**Comment by anvilfolk** [comment]
I really do think that there ought to be a big project that peeps working on GDScript should test against. I don't know whether @KoBeWi's project is public, but I know @unfa works liblast, which is open-source, so maybe that's the way to go?

**Comment by adamscott** [comment]
> I ran @KoBeWi's huge project as a test for your PR. Here's an error that I got.
> 
> image
> 
> Seems that it doesn't like casting of nodes.

Here's the MRP:
[69471_oomr_infer.zip](https://github.com/godotengine/godot/files/10145705/69471_oomr_infer.zip)

**Comment by adamscott** [comment]
@anvilfolk Sure, we can use [Liblast](https://codeberg.org/Liblast/Liblast/) too to test!

**Comment by rune-scape** [comment]
@adamscott
thanks for that info, i'm about to push a fix for that

**Comment by unfa** [comment]
Wanna test? Be my guest!

Here's instructions for cloning the Liblast repo (some people have trouble because they forget about LFS):
https://codeberg.org/Liblast/Liblast#_how_to_edit_the_game

**Comment by adamscott** [comment]
@rune-scape It fixed KoBeWi's project! Runs flawlessly, from what I could tell. Thanks!

**Comment by rune-scape** [comment]
there's currently not too many crazy things this PR allows, mostly because there's still so many limitations on resolution order (mostly between scripts), but i'm looking at the changes needed to lift most of them and make dependencies between scripts do what you expect (or at least what i expect)

**Comment by anvilfolk** [comment]
@rune-scape got another test for you that's giving me trouble.

```GDScript
class_name OuterClass

class InnerClass:
	enum MyEnum { V0, V2, V1 }
	
func outer_inner_class(e : InnerClass.MyEnum) -> void:
	print(e)
```

Does this work in this PR?

**Comment by rune-scape** [comment]
@anvilfolk yes, that resolves fine in this branch

**Comment by akien-mga** [comment]
Needs rebase.

**Comment by rune-scape** [comment]
i added a single tiny test, but https://github.com/godotengine/godot/pull/69907 is needed to test dependencies between scripts, and a couple more type resolution bugs are also making my life hard 😢 
i also took the opportunity to improve my code :)

**Comment by anvilfolk** [comment]
Looks like the PR you mentioned is in! :) I take it merging should wait until the bugs are ironed out?

**Comment by rune-scape** [comment]
that was fast!, yes, i want to make some more complex tests now before this gets merged

**Comment by rune-scape** [comment]
ok, it took a while to figure out, but tests are added and they helped me find a few bugs! it's finally done

**Comment by anvilfolk** [comment]
Nice! Look forward to seeing this merged so I can fix conflicts with the enum PR! :)

**Review by akien-mga — APPROVED** [review]
Great work!

**Comment by akien-mga** [comment]
Thanks!

**Comment by lufog** [comment]
I think this PR broke something in Autoloads.

on ec4de82ab:
MRP works

on 6debf86d5:
I get `Parser Error: Cannot find member "audio_player" in base "".`

MRP: [var_from_autoload_test.zip](https://github.com/godotengine/godot/files/10240605/var_from_autoload_test.zip)

**Comment by adamscott** [comment]
@lufog Can you create an issue?

**Comment by lufog** [comment]
@adamscott, to be honest, I don't even know how to properly formulate it. But I'll try.

**Comment by rune-scape** [comment]
@lufog thank you for the project! i think i found the mistake

**Comment by adamscott** [comment]
> I don't even know how to properly formulate it.

You can formulate it like "Autoloads broken: cannot find members" and copy/paste what you wrote here in the issue.

It will be easier for @rune-scape to create a PR that links to your issue.

**Comment by lufog** [comment]
Done #70127

**Comment by dmaz** [comment]
since this pr I'm also having some errors some of which was just lazy code on my part.  My biggest issue that I'm having trouble isolating is from an autoload that loads a bunch of resources that creates instances from a named base class.  I get this 
`Parser Error: Could not resolve class ItemBase`

one of the other issues that was easily fixed was a reference from an autoload to another autoload
`play3D(null, Game.player.global_position, key, 1.0, parms)`
clearly this is lazy but it worked and being a "simple" scripting language I would figure we still want the compiler to be able be ok with stuff like this

**Comment by adamscott** [comment]
@dmaz Please create issues and link them to this PR. Commenting here doesn't really help fixing your issues.

**Comment by dmaz** [comment]
yeah for sure... just haven't been able to isolate class one into an example yet
