### PR TITLE
Fix `CollisionShape{2D,3D}.debug_color` inconsistencies

### LINKED ISSUE #100088: Default value of `CollisionShape3D`'s property `debug_color` should not be saved in .tscn file
### Tested versions

- Reproducible in 4.4.dev6

### System information

Godot v4.4.dev6 - Windows 10.0.22631 - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 32.0.15.6094) - 13th Gen Intel(R) Core(TM) i5-13600KF (20 threads)

### Issue description

The default value of `CollisionShape3D`'s property `debug_color` (introduced in 4.4.dev6) should not be saved in `.tscn` file.
Not friendly to Version Control.

Image

### Steps to reproduce

NA

### Minimal reproduction project (MRP)

NA

### PR DESCRIPTION
**Pull request by dalexeev**
* Fixes #100088.
* See also https://github.com/godotengine/godot/pull/39072#issuecomment-1231891794.

CC @BattyBovine

### CODE REVIEW

File: scene/2d/physics/collision_shape_2d.cpp [hunk 1]
```diff
@@ -232,7 +227,18 @@ real_t CollisionShape2D::get_one_way_collision_margin() const {
 	return one_way_collision_margin;
 }
 
+#ifdef DEBUG_ENABLED
+
+Color CollisionShape2D::_get_default_debug_color() const {
+	SceneTree *st = SceneTree::get_singleton();
+	return st ? st->get_debug_collisions_color() : Color(0.0, 0.0, 0.0, 0.0);
```
Comment (akien-mga) [inline scene/2d/physics/collision_shape_2d.cpp:234]: Wouldn't it be better to keep `Color()` (black) instead of transparent black as the fallback?

If using collision shapes without a scene tree, a black shape is probably better than a transparent one.

Comment (dalexeev) [reply scene/2d/physics/collision_shape_2d.cpp:234]: This is debatable. On the one hand, at least you'll see the shape. On the other hand, you might get a bunch of indistinguishable black rectangles, squares, spheres, etc. But in any case, this is a very hypothetical scenario, the vast majority of users use the standard `SceneTree`, and do not implement their own `MainLoop`s.

Comment (dalexeev) [reply scene/2d/physics/collision_shape_2d.cpp:234]: So would you prefer a transparent color?

Comment (akien-mga) [reply scene/2d/physics/collision_shape_2d.cpp:234]: Why can't we use a fallback value that's actually a good option, like the current default?
```
1837:   debug_collisions_color = GLOBAL_DEF("debug/shapes/collision/shape_color", Color(0.0, 0.6, 0.7, 0.42));
```

**Review by akien-mga — APPROVED** [review]
This is already better than the status quo, but maybe the fallback color could be something colored and semi-transparent like the previous default.

**Review by AThousandShips — APPROVED** [review]

File: scene/2d/physics/collision_shape_2d.cpp (hunk 1 above)
Comment (Zylann) [reply scene/2d/physics/collision_shape_2d.cpp:234]: I would be for a better default too, although having skimmed over some code related to it, I think it's been used as a special value to mean "null". Maybe that should be checked as well

File: scene/2d/physics/collision_shape_2d.cpp [hunk 2]
```diff
@@ -232,7 +227,18 @@ real_t CollisionShape2D::get_one_way_collision_margin() const {
 	return one_way_collision_margin;
 }
 
+#ifdef DEBUG_ENABLED
+
```
[the remark this answers is not in the document]
Comment (akien-mga) [reply scene/2d/physics/collision_shape_2d.cpp:231]: When spanning 50+ lines and multiple functions, I tend to prefer it with some spacing, as otherwise the start and end of the scope can be hard to spot at a glance.

Not a policy but I wouldn't go out of our ways to point out such things either in style reviews, unless it's inconsistent with surrounding code.

**Review by akien-mga — APPROVED** [review]
Let's merge as is for now and see if a different default is useful after dev7.

**Comment by akien-mga** [comment]
Thanks!

File: scene/2d/physics/collision_shape_2d.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (AThousandShips) [reply scene/2d/physics/collision_shape_2d.cpp:231]: That's fair, I find it easier to read myself when it's attached and it's AFAIK the majority of existing code but good points

[the remark this answers is not in the document]
Comment (dalexeev) [reply scene/2d/physics/collision_shape_2d.cpp:231]: * Probably these `#ifdef`s were not needed at all, see #100317. But I was too late to answer here.
