### PR TITLE
Fix Directory.dir_exist/get_current_dir for 'res://' on Android

### LINKED ISSUE #7014: Directory.dir_exists() always return True on Android
**Operating system or device - Godot version:**
Android Galaxy S4 Galaxy S6
Godot tools and export templates from 20dd5a6 compiled on Windows 7 x64

**Issue description** (what happened, and what was expected):
Calling Directory.dir_exists(some_path) on Android always return True even if there isn't any directory in that path
Related to [6837](https://github.com/godotengine/godot/issues/6837)

**Steps to reproduce:**
A project with assets:
- scenes
    - 0
        - 0.scn
        - 1.scn
        - 2.scn
        - 3.scn

And the following code
```
1. var dir = Directory.new()
2. var path = "res://scenes/non_valid/dir"
3. if dir.dir_exists(path):
4. 	print(path, " exist")
5. else:
6. 	print(path, " not exist")
```
After running this on Android device it will print "res://scenes/non_valid/dir exist" even if it isn't.

### PR DESCRIPTION
**Pull request by volzhs**
Fix #7014

a little more detail info.
```gdscript
var dir = Directory.new()
if dir.open("res://")==OK:
    print("current dir path = ", dir.get_current_dir())        # prints "/"
    var path = dir.get_current_dir().plus_file("sub_dir_name") # path is now "/sub_dir_name"
    var sub_dir = Directory.new()
        # it tries to search on filesystem not under "res://"
        if sub_dir.open(path)==OK:
            # so can't be reached here
            pass
```

### CODE REVIEW

File: platform/android/dir_access_jandroid.cpp [hunk 1]
```diff
@@ -154,7 +154,7 @@ Error DirAccessJAndroid::change_dir(String p_dir){
 
 String DirAccessJAndroid::get_current_dir(){
 
-	return "/"+current_dir;
+	return "res://"+current_dir;
```
Comment (volzhs) [inline platform/android/dir_access_jandroid.cpp]: https://github.com/godotengine/godot/blob/master/platform/android/os_android.cpp#L77-L115

If I understand this code right, `dir_access_jandroid.cpp` handles only "res://" on running on Android device.
The problem is that `res://path` is changed to `/path`.
So, it will use `DirAccess::ACCESS_FILESYSTEM` after `var path = dir.get_current_dir().plus_file("sub_dir_name")`

So, I don't think it makes other trouble.
And I tested it with exported apk, run on Android device.

Comment (volzhs) [inline platform/android/dir_access_jandroid.cpp]: I tested it more for clear.

```gdscript
func _ready():
	var dir = Directory.new()
	var result = dir.open("res://")
	print(dir.get_current_dir().plus_file("test"))

	var dir = Directory.new()
	var result = dir.open("user://")
	print(dir.get_current_dir().plus_file("test"))

	var dir = Directory.new()
	var result = dir.open("/")
	print(dir.get_current_dir().plus_file("test"))
```
This prints this on desktop and android both. :)
```
res://test
user://test
/test
```

**Comment by volzhs** [comment]
edit commit message to describe what really fixed.
