### PR TITLE
Fix indeterminate minimum size in ScrollContainer

### LINKED ISSUE #61927: Crash when opening/running simple scene without any scripts
### Godot version

4.0 alpha 9

### System information

Ubuntu 22.04 - Nvidia GTX 970, Gnome shell 42 X11

### Issue description

```
ERROR: Can't create buffer of size: 1680, error -2.
   at: _buffer_allocate (drivers/vulkan/rendering_device_vulkan.cpp:1347)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.alpha.custom_build (1baee2189c21ae36c852ddff10f769b1134509ca)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] godot4s() [0x243f6d8] (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/crash_handler_linuxbsd.cpp:56)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7fbb371cc520] (??:0)
[3] /lib/x86_64-linux-gnu/libnvidia-glcore.so.510.73.05(+0x11cf442) [0x7fbb17bcf442] (??:0)
[4] RenderingDeviceVulkan::_buffer_update(RenderingDeviceVulkan::Buffer*, unsigned long, unsigned char const*, unsigned long, bool, unsigned int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/drivers/vulkan/rendering_device_vulkan.cpp:1572 (discriminator 5))
[5] RenderingDeviceVulkan::index_buffer_create(unsigned int, RenderingDevice::IndexBufferFormat, Vector<unsigned char> const&, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/drivers/vulkan/rendering_device_vulkan.cpp:4279 (discriminator 1))
[6] RendererCanvasRenderRD::request_polygon(Vector<int> const&, Vector<Vector2> const&, Vector<Color> const&, Vector<Vector2> const&, Vector<int> const&, Vector<float> const&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:317 (discriminator 2))
[7] RendererCanvasRender::Polygon::create(Vector<int> const&, Vector<Vector2> const&, Vector<Color> const&, Vector<Vector2> const&, Vector<int> const&, Vector<float> const&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./servers/rendering/renderer_canvas_render.h:147)
[8] RendererCanvasCull::canvas_item_add_triangle_array(RID, Vector<int> const&, Vector<Vector2> const&, Vector<Color> const&, Vector<Vector2> const&, Vector<int> const&, Vector<float> const&, RID, int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/servers/rendering/renderer_canvas_cull.cpp:1297)
[9] RenderingServerDefault::canvas_item_add_triangle_array(RID, Vector<int> const&, Vector<Vector2> const&, Vector<Color> const&, Vector<Vector2> const&, Vector<int> const&, Vector<float> const&, RID, int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/servers/rendering/rendering_server_default.h:827 (discriminator 2))
[10] StyleBoxFlat::draw(RID, Rect2 const&) const (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/resources/style_box.cpp:837 (discriminator 4))
[11] ScrollBar::_notification(int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/gui/scroll_bar.cpp:245)
[12] ScrollBar::_notificationv(int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./scene/gui/scroll_bar.h:37 (discriminator 14))
[13] HScrollBar::_notificationv(int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./scene/gui/scroll_bar.h:116 (discriminator 3))
[14] Object::notification(int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/object.cpp:849)
[15] CanvasItem::_update_callback() (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/canvas_item.cpp:143)
[16] void call_with_variant_args_helper<__UnexistingClass>(__UnexistingClass*, void (__UnexistingClass::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:241 (discriminator 4))
[17] void call_with_variant_args_dv<__UnexistingClass>(__UnexistingClass*, void (__UnexistingClass::*)(), Variant const**, int, Callable::CallError&, Vector<Variant> const&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:354)
[18] MethodBindT<>::call(Object*, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/object/method_bind.h:334)
[19] Object::callp(StringName const&, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/object.cpp:838 (discriminator 1))
[20] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/variant/callable.cpp:62)
[21] MessageQueue::_call_function(Callable const&, Variant const*, int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/message_queue.cpp:230)
[22] MessageQueue::flush() (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/message_queue.cpp:277)
[23] SceneTree::physics_process(double) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/scene_tree.cpp:421 (discriminator 4))
[24] Main::iteration() (/home/runner/work/GodotBuilds/GodotBuilds/godot/main/main.cpp:2705)
[25] OS_LinuxBSD::run() (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/os_linuxbsd.cpp:441)
[26] godot4s(main+0x496) [0x243cd7c] (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/godot_linuxbsd.cpp:70)
[27] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fbb371b3d90] (??:0)
[28] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7fbb371b3e40] (??:0)
[29] godot4s(_start+0x2e) [0x243c82e] (??:?)
-- END OF BACKTRACE --
================================================================
```

Tscn content
```
[gd_scene format=3]

[node name="@@2" type="Node"]

[node name="20" type="VScrollBar" parent="."]

[node name="19" type="AnimationTree" parent="."]

[node name="16" type="ColorPickerButton" parent="19"]

[node name="15" type="TabContainer" parent="19/16"]

[node name="11" type="HSplitContainer" parent="19/16/15"]

[node name="10" type="OmniLight3D" parent="19/16/15/11"]

[node name="9" type="ReflectionProbe" parent="19/16/15/11/10"]

[node name="2" type="ScrollContainer" parent="19/16/15/11/10/9"]

[node name="0" type="VSeparator" parent="19/16/15/11/10/9/2"]
```

### Steps to reproduce

Just run tscn file or open it in editor - [ABCD1461692499.tscn.zip](https://github.com/godotengine/godot/files/8883465/ABCD1461692499.tscn.zip)
 

### Minimal reproduction project

_No response_

### LINKED ISSUE #62013: Crash when adding Button/ColorPickerButton child node to two nested ScrollContainers
### Godot version

v4.0.alpha9.official [fc18891db]

### System information

Linux Mint 20.3, Vulkan, NVIDIA GeForce GTX 1050 Ti

### Issue description

Although the usage is not recommended, it should not crash. Also the message printed when it crashes is weird.

```
Failed method: HScrollBar::_update_callback
Failed method: RichTextLabel::_update_callback
Failed method: Button::_update_callback

================================================================
Failed method: Button::_update_callback
```

### Steps to reproduce

It will crash when trying to get a tree with the following structure.
```
...
└─ScrollContainer
  └─ScrollContainer
    └─Button/ColorPickerButton
...
```

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Rindbee**
Fix #62013.
Fix #61927.

Both of the above problems are related to `scroll_mode` in `ScrollContainer` being `SCROLL_MODE_AUTO` (default value).
It's because the calculation of the minimum size of `ScrollContainer` will consider the visibility of the internal `ScrollBar`, and the visibility of the internal `ScrollBar` is related to the minimum size. So in some cases it might get stuck in an infinite loop. For example, a control with a minimum size of `(8, 8)`.

### CODE REVIEW

File: scene/gui/scroll_container.cpp [hunk 1]
```diff
@@ -37,10 +37,11 @@
 Size2 ScrollContainer::get_minimum_size() const {
 	Ref<StyleBox> sb = get_theme_stylebox(SNAME("bg"));
 	Size2 min_size;
+	Size2 size_max;
```
Comment (KoBeWi) [inline scene/gui/scroll_container.cpp:40]: This could be renamed to something like `content_min_size` for better clarity.

**Review by KoBeWi — APPROVED** [review]

**Review by KoBeWi — APPROVED** [review]

File: scene/gui/scroll_container.cpp (hunk 1 above)
Comment (Rindbee) [reply scene/gui/scroll_container.cpp]: Thanks for the suggestion.

**Comment by akien-mga** [comment]
Thanks!
