### PR TITLE
Enhance thread-safety of loaders and importers (a.k.a. fix editor deadlock)

### LINKED ISSUE #69919: Opening a project containing compute shaders, or adding them while open, can freeze Godot
### Godot version

Godot 4 beta8 (and some preceding betas I dont recall)

### System information

Windows 10 64 bits NVIDIA GeForce GTX 1060

### Issue description

The editor opens, a GLSL file starts importing, then immediately a popup shows up, either completely black or white, blocking the editor. The popup stays that way, meaning the whole editor is stuck and I have to kill it.
It happened to me 3 times at this point in various beta versions.
The shaders likely have errors in them, but that should not make Godot freeze like that.

EDIT: happened again as I was trying to workaround it. I removed shaders from the project, the project opened, then I moved the files back in the project, but Godot went stuck the same way while importing them.

I also tried commenting out the code in the `main` function, which this time did not show a popup, but Godot still froze anyways.

image

I eventually found out a workaround that SEEMS to work:
I commented out the contents of every shader, except `#[compute]` and `#version 450`, and added a placeholder `void main() {}` just so it doesnt complain. Finally Godot opened fine, then I removed the placeholder and uncommented the rest of the code, and only then, Godot properly opened the error popup without freezing.

### Steps to reproduce

Unfortunately I tried reproducing this a few times but it's not happening 100% of the time. But every time it happened, the following conditions were met:

- I was opening the project, it wasn't already open. Although I also had the same thing happen with an open project, if I add shader files to the project and focus back Godot.
- The project had GLSL compute shader(s) that had errors in them. Syntax, or other.
- Those GLSL shaders were either brand new since the last time the project opened, or were imported before but have been modified while the project was closed.
- This one might not matter, but my environment is such that Godot's internal shader cache gets recompiled often, since I'm often switching between versions (although I always opened my project with increasing beta versions).

### Minimal reproduction project

Last time it happened, I started my computer and opened this project for the first time in the day, and the faulty shaders were brand new files. The project itself had been opened in the past and already had valid imported shaders, but the new ones were added while the project was not open.

[shaders_copy.zip](https://github.com/godotengine/godot/files/10202822/shaders_copy.zip)

It might not reproduce for you though, as I mentionned it's not 100%.

### PR DESCRIPTION
**Pull request by RandomShaper**
Fixes #69919.

**UPDATE 2:** Most of what is said below is still true, but the approach taken for Godot 4.0 is more conservative:
- Importers that advertise themselves as thread-safe use deferred calls to the not thread-safe methods.
- Loaders, which can run on threads, likewise.
- A few dev-only guards are added to prevent the most common cases of devs unintendedly and inadvertedly adding thread unsafe code.
Post Godot 4.0 there will be a big effort to make thread safety more robust.

There's also a commit that simplifies the very related error reporting callbacks API. The only current use case doesn't need an user data parameter, so things can be simpler.

### ❗❗❗ This PR needs ~#71644~ (already merged) to work (or #75994 for 4.0). ❗❗❗
~**UPDATE:** And, thus, it nows includes it.~

---
The problem in that issue is a deadlock caused by how we are dealing with the windowing system. This at least applies to Windows. The problem is that if you create a window from an arbitrary thread, you are expected to have a message loop in it and also deal with some of the other multi-threading specifics. It's not as easy as just serializing the the calls via a thread safe implementation of the `DisplayServer`.

Furthermore, the way Godot deals with long blocking operations, such as resource importing, prevents even the main message loop to run. That can cause deadlocks in situations like this:
- Main thread is polling a worker thread pool to check if it's done.
- One of the worker threads deals with a Window (therefore holding the `DisplayServer` lock).
- Tthe OS needs to communicate something to a window owned by the main thread (and won't return from the call until such communication has ended).
- The main thread's message loop is not running at all during the blocking operation, as said above. Frozen!

One could consider that maybe the polling loop could call `DisplayServer::process_events()`, but that's not a solution either. The main thread would claim the lock for itself, but the arbitrary thread still owns it. Frozen again!
**UPDATE:** I've found that the progress dialog implementation does precisely that, but it's still not a full solution.

I believe the best fix for that is either:
a) Godot deals with the windowing systems via a command queue.
b) Godot imposes that windowing can happen only on the main thread.

Since it's a bit too late for such a change for Godot 4.0, what this PR does is fixing the issue indirectly. I mean, thread-safety in the editor, and hence stability, is improved (it was buggy before), but that comes with the side effect that the editor is no longer trying to deal with windows from multiple threads, which is a bit as if we had already enforced b). One conclusion is that regardless we enforce or not such a rule in the future, this change makes sense by itself.

P. S. In case we really wanted to do proper multi-threaded windowing on Windows, I'm leaving this note for the future: we may want to look into `AttachThreadInput()`.

P. P. S.: I'm not stating that the new practices and idioms about thread safety in Godot's code are necessarilly the ones I've used in this patch, but I think it's at least a good start that can be embraced more extensively in the future, or ditched in favor of a different one.

### CODE REVIEW

**Comment by RandomShaper** [comment]
@reduz, I've reworked this PR after what we discussed on RocketChat. Please re-review.

File: core/io/resource_format_binary.cpp [hunk 1]
```diff
@@ -693,7 +693,7 @@ Error ResourceLoaderBinary::load() {
 
 			if (external_resources[i].cache.is_null()) {
 				if (!ResourceLoader::get_abort_on_missing_resources()) {
-					ResourceLoader::notify_dependency_error(local_path, path, external_resources[i].type);
+					callable_mp_static(&ResourceLoader::notify_dependency_error).bind(local_path, path, external_resources[i].type).call_deferred();
```
Comment (reduz) [inline core/io/resource_format_binary.cpp:696]: I think I would implement the deferred call in the editor side on whathever handles this static function for notifying dependency errors, the loader in itself is kind of agnostic to threading.

Comment (RandomShaper) [reply core/io/resource_format_binary.cpp:696]: If neither `ResourceLoader` implementations nor the editor have to be aware of threading, the only option remaining is that the static function `ResourceLoader::&ResourceLoader::notify_dependency_error()` be the one that "bridges" between the multi-threaded loader world and the single-threaded editor world. In short, that function would be the one deferring the call to the registered notify function (which happens to be editor's).
Would that make sense?

Comment (RandomShaper) [reply core/io/resource_format_binary.cpp]: In case it does, I've already done the change, so please re-review.

**Comment by RandomShaper** [comment]
I've removed the commit from a PR dependency that is now divergent between 4.0 and 4.1 and therefore lives in different PRs (see updated PR description).

**Comment by akien-mga** [comment]
I'm surprised this compiled without https://github.com/godotengine/godot/pull/71644 in the PR, but it should probably be rebased now that it was merged so any test landing on the commits from this PR would still work as expected.

**Comment by RandomShaper** [comment]
> I'm surprised this compiled without #71644 in the PR, but it should probably be rebased now that it was merged so any test landing on the commits from this PR would still work as expected.

Rebased!

It compiles because the interfaces to make static deferred calls were already there, which is all this PR needs for a successful build. What the other PR does is make those calls _work_.

**Review by akien-mga — APPROVED** [review]
@reduz said he's OK with this PR.

I might suggest a rebase for good measure, as we've merged quite a few changes around this code?

**Comment by RandomShaper** [comment]
Rebased.

**Comment by akien-mga** [comment]
Thanks!
