### PR TITLE
Make the meta click area fit to its visible area

### LINKED ISSUE #53599: Links in editor help have bigger clickable area than they should
### Godot version

df37675

### System information

W10

### Issue description

k2zv1k2ntO
Notice how cursor changes to hand on blank space.

### Steps to reproduce

1. Open Vector2 in editor help
2. Inspect the tutorial links

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Rindbee**
Fix #53599.

Previously, items of type `ITEM_NEWLINE` were ignored, these items had information about their parent item, which might be useful in some cases.

| Before | After |
| :-------: | :-----: |
|  | |

### CODE REVIEW

File: scene/gui/rich_text_label.cpp [hunk 1]
```diff
@@ -1467,7 +1472,7 @@ float RichTextLabel::_find_click_in_line(ItemFrame *p_frame, int p_line, const V
 			rect.size.y += get_theme_constant(SNAME("table_v_separation"));
 		}
 
-		if (p_click.y >= rect.position.y && p_click.y <= rect.position.y + rect.size.y) {
+		if (p_click.y >= rect.position.y && p_click.y <= rect.position.y + rect.size.y && p_click.x >= rect.position.x) {
 			char_pos = TS->shaped_text_hit_test_position(rid, p_click.x - rect.position.x);
```
Comment (Rindbee) [inline scene/gui/rich_text_label.cpp:1476]: Probably not a good solution here, `GRAPHEME_IS_RTL` is not considered, but it would be more convenient to have one side equal to `-1` and the other equal to `glyph_count`.

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
