### PR TITLE
[macOS export] Implements ad-hoc signing on Linux/Windows.

### LINKED ISSUE #51007: 3.3.2 Linux Headless exports invalid Mac app
### Godot version

3.3.2.stable Linux Headless

### System information

macOS Big Sur 11.5 with M1 Chip

### Issue description

I am using godot-ci for my project, but it exports invalid mac app. Seems like a godot issue. Godot 3.2.3 doesn't have this issue, only versions higher than 3.3 has it.

`xattr -dr com.apple.quarantine /path/to/Application.app` solves the problem, but it requires a Mac.

Possibly related to #527.

### Steps to reproduce

1. Create an empty project.
2. Create a Mac export.
3. Export the app using CLI.
4. Run app in macOS.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by bruvzg**
This PR adds:
- custom implementation of `codesign` to ad-hoc sign macOS exports on Linux/Windows (and macOS without Xcode installed), to allow valid macOS export from any platform. Using real signatures is not supported (MbedTLS used by Godot for cryptography do not have PKCS#7/CMS support), but without notarization there are no benefits over ad-hoc anyway.
- entitlements config validation for GDNative exports.
- extra warnings for different singing conditions.
- some optional extra usage messages to export settings to match supported entitlements.
- improved export template handling to allow including frameworks in the template ZIP (won't work on Windows, due to lack of symlink support implementation).

Tested on macOS, Linux and Windows with classic, mono + GDNative libraries.

Note for testing: there are changes to export template `Info.plist`, some features (usage message) won't work if it's used with old template, but signing should work in any case.

Screenshot 2021-08-10 at 20 23 18

Fixes: #51007, #48076, #48803

### CODE REVIEW

File: editor/export/codesign.cpp [hunk 1]
```diff
@@ -0,0 +1,1052 @@
...
+		}
+	}
+
+	// Extract fat binary.
+	Vector<String> files_to_sign;
+	if (LipO::is_lipo(main_exe)) {
+		String tmp_path_name = EditorPaths::get_singleton()->get_cache_dir().plus_file("_lipo");
+		Error err = da->make_dir_recursive(tmp_path_name);
+		if (err != OK) {
+			r_error_msg = "Failed to create " + tmp_path_name + " subfolder.";
```
Comment (timothyqiu) [inline editor/export/codesign.cpp:828]: I think these error messages should be translatable.

File: editor/export/lipo.cpp [hunk 2]
```diff
@@ -0,0 +1,237 @@
+/*************************************************************************/
+/*  lipo.cpp                                                             */
+/*************************************************************************/
+/*                       This file is part of:                           */
+/*                           GODOT ENGINE                                */
+/*                      https://godotengine.org                          */
+/*************************************************************************/
+/* Copyright (c) 2007-2021 Juan Linietsky, Ariel Manzur.                 */
+/* Copyright (c) 2014-2021 Godot Engine contributors (cf. AUTHORS.md).   */
```
Comment (akien-mga) [inline editor/export/lipo.cpp:9]: Copyright header will need an update.

File: editor/export/codesign.h [hunk 3]
```diff
@@ -0,0 +1,356 @@
...
+/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,       */
+/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF    */
+/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.*/
+/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY  */
+/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,  */
+/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE     */
+/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                */
+/*************************************************************************/
+
+// macOS code signature creation utility.
```
Comment (akien-mga) [inline editor/export/codesign.h:31]: Might be worth adding a few more details to present the library and how it differs to the Apple implementation.

File: editor/export/codesign.cpp [hunk 4]
```diff
@@ -0,0 +1,1610 @@
...
+/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                */
+/*************************************************************************/
+
+#include "core/os/os.h"
+#include "editor/editor_settings.h"
+
+#include "codesign.h"
+#include "lipo.h"
+#include "macho.h"
+#include "plist.h"
```
[the remark this answers is not in the document]
Comment (bruvzg) [reply editor/export/codesign.cpp]: Real codesign is not part of SDK, it should not conflict with anything.

File: editor/export/codesign.cpp [hunk 5]
```diff
@@ -0,0 +1,1610 @@
...
+
+#include <ctime>
+
+/*************************************************************************/
+/* CodeSignCodeResources                                                 */
+/*************************************************************************/
+
+String CodeSignCodeResources::hash_sha1_base64(const String &p_path) {
+	FileAccessRef fa = FileAccess::open(p_path, FileAccess::READ);
+	ERR_FAIL_COND_V_MSG(!fa, String(), "CodeSign/CodeResources: " + TTR("Can't open file: ") + p_path);
```
[the remark this answers is not in the document]
Comment (bruvzg) [reply editor/export/codesign.cpp]: Removed all translations from the console errors, and changed it and editor errors to `vformat`.

File: editor/export/codesign.cpp [hunk 6]
```diff
@@ -0,0 +1,1610 @@
...
+CodeSignRequirements::CodeSignRequirements() {
+#define _W(a, b, c, d) \
+	blob.push_back(a); \
+	blob.push_back(b); \
+	blob.push_back(c); \
+	blob.push_back(d);
+	_W(0xFA, 0xDE, 0x0C, 0x01); // Requirement set magic.
+	_W(0x00, 0x00, 0x00, 0x0C); // Length of requirements set (12 bytes).
+	_W(0x00, 0x00, 0x00, 0x00); // Empty.
+#undef _W
```
[the remark this answers is not in the document]
Comment (bruvzg) [reply editor/export/codesign.cpp]: Changed all of these to `blob.append_array({ 0xFA, 0xDE, 0x0C, 0x01 });`.

File: editor/export/codesign.cpp [hunk 7]
```diff
@@ -0,0 +1,1610 @@
...
+
+Error CodeSign::codesign(bool p_use_hardened_runtime, bool p_force, const String &p_path, const String &p_ent_path, String &r_error_msg) {
+	DirAccess *da = DirAccess::create(DirAccess::ACCESS_FILESYSTEM);
+	if (!da) {
+		r_error_msg = TTR("Can't get filesystem access.");
+		ERR_FAIL_V_MSG(ERR_CANT_CREATE, "CodeSign: " + TTR("Can't get filesystem access."));
+	}
+
+	if (da->dir_exists(p_path)) {
+		String fmw_ver = "Current"; // Framewrok version (default).
```
[the remark this answers is not in the document]
Comment (bruvzg) [reply editor/export/codesign.cpp]: It's similar, but not exactly the same, some checks can be moved to a function, but a function with multiple return values probably will be less readable.

File: editor/export/codesign.h [hunk 8]
```diff
@@ -0,0 +1,356 @@
...
+#ifndef CODESIGN_H
+#define CODESIGN_H
+
+#include "core/crypto/crypto.h"
+#include "core/crypto/crypto_core.h"
+#include "core/io/dir_access.h"
+#include "core/io/file_access.h"
+#include "core/object/ref_counted.h"
+
+#include "modules/regex/regex.h"
```
[the remark this answers is not in the document]
Comment (bruvzg) [reply editor/export/codesign.h]: RegEx is required to process resource files, disabled all built-in codesign code if it's not available.

File: editor/export/codesign.h (hunk 3 above)
Comment (bruvzg) [reply editor/export/codesign.h]: Added a list of the current limitations.

File: platform/osx/export/export_plugin.h [hunk 9]
```diff
@@ -42,6 +42,7 @@
 #include "editor/editor_export.h"
 #include "editor/editor_node.h"
 #include "editor/editor_settings.h"
+#include "modules/modules_enabled.gen.h" // For regex.
```
Comment (akien-mga) [inline platform/osx/export/export_plugin.h:45]: This should go in the `.cpp` where it's used I think.

File: platform/osx/export/lipo.cpp [hunk 10]
```diff
@@ -0,0 +1,241 @@
...
+/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.*/
+/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY  */
+/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,  */
+/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE     */
+/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                */
+/*************************************************************************/
+
+#include "lipo.h"
+
+#ifdef MODULE_REGEX_ENABLED
```
Comment (akien-mga) [inline platform/osx/export/lipo.cpp:33]: It works as `modules_enabled.gen.h` is included in the matching header, but since missing it can lead to subtle bugs (see e.g. #54911), I prefer to be explicit and always re-include it in each file that uses a `MODULE_*_ENABLED` check.

File: platform/osx/export/codesign.cpp [hunk 11]
```diff
@@ -0,0 +1,1562 @@
...
+
+#include "core/os/os.h"
+#include "editor/editor_settings.h"
+
+#include "codesign.h"
+#include "lipo.h"
+#include "macho.h"
+#include "plist.h"
+
+#include <ctime>
```
Comment (akien-mga) [inline platform/osx/export/codesign.cpp:39]: Nitpick but for our codestyle, `codesign.h` (which matches `codesign.cpp`) should be the first include. Though I agree that grouping the "ad hoc library" headers together makes sense. Maybe something like this?

```suggestion
#include "codesign.h"

#include "lipo.h"
#include "macho.h"
#include "plist.h"

#include "core/os/os.h"
#include "editor/editor_settings.h"

#include <ctime>
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks a ton!
