### PR TITLE
Prevent editor crash when deleting children of GraphNode

### LINKED ISSUE #69082: Editor crashes when deleting children of GraphNode
### Godot version

4.0b6

### System information

Linux/Manjaro

### Issue description

Deleting the last child of a GraphNode crashes the editor, unless that GraphNode has been resized at least once by the user. The issue is easy to avoid, but the crash is still odd.

There is another crash in which deleting all the children of GraphNode at once will crash

### Steps to reproduce

First crash:
1. Create a new scene with a GraphNode, and do not resize it;
2. Add any Control that draws content, like a Button;
3. Delete the new child you just created;
4. Observe the crash

Second crash:
1. Create a new scene with a GraphNode;
2. Add multiple Controls as children;
3. Select all of them and delete them from the scene;
4. Observe the crash.

### Minimal reproduction project

[graphnode-crash-repro.zip](https://github.com/godotengine/godot/files/10079773/graphnode-crash-repro.zip)

This project has two scenes: `graph_node.tscn` showcases the first crash with a default size GraphNode and a single content-drawing Control. The `graph_node_multiple_children.tscn` scene has a GraphNode with multiple children that crash the editor when deleted.

### PR DESCRIPTION
**Pull request by John-Gdi**
Solve #69082 by adding avaliable child checking.

*Bugsquad edit:*
- Fixes #69082

### CODE REVIEW

File: scene/gui/graph_node.cpp [hunk 1]
```diff
@@ -392,7 +392,7 @@ void GraphNode::_notification(int p_what) {
 				}
 
 				// Draw slot stylebox.
-				if (s.draw_stylebox) {
+				if (s.draw_stylebox && get_child_count()) {
```
Comment (akien-mga) [inline scene/gui/graph_node.cpp:395]: This would only solve it for a case with no children, but there could still be a mismatch between the number of children and the value of `E.key` I suppose?
So it would at least need to check `E.key < get_child_count()`.

But this is a sign of a deeper issue IMO.

Comment (John-Gdi) [reply scene/gui/graph_node.cpp:395]: @akien-mga , thanks for your comment. During my test, the crash only occurs when deleting the last child of a GraphNode, as well as deleting all child nodes at once. Because delete the last node, the data in the redraw call may not update yet.

and i think the check `E.key < get_child_count()` is done at the begining of the for loop. since the `cache_y.size()` is equal to the child node count.
```
if (E.key < 0 || E.key >= cache_y.size()) {
    continue;
}
```

Comment (YuriSizov) [reply scene/gui/graph_node.cpp:395]: > and i think the check `E.key < get_child_count()` is done at the begining of the for loop. since the `cache_y.size()` is equal to the child node count.

Clearly they are not equal in that moment, otherwise your own check wouldn't achieve much. They aren't guaranteed to be equal anyway, because the cache is only created for visible and valid _Control_-based children, and also not the ones which are set to be top level.

I agree with Akien, that there does seem to be some underlying issue, but I think an ad-hoc fix could also be done for now. It should, however, be a different fix than yours. It should check the validity of child nodes before doing anything with them. In fact, it's just a good idea in general.

See the code where the lines around https://github.com/godotengine/godot/blob/5d986cb8cccc3c6bd980d27b4413e6109534ee38/scene/gui/graph_node.cpp#L252 for a reference.

Comment (John-Gdi) [reply scene/gui/graph_node.cpp:395]: Hi, @YuriSizov , thansk for your review, in my test, the crash occurs at the code 
[`Control *c = Object::cast_to<Control>(get_child(E.key));`](https://github.com/godotengine/godot/blob/166066d9f74e574b68d9f9d0ba05bf42b8de2131/scene/gui/graph_node.cpp#L396)
in the `get_child` function, so i can't do any further check, any suggestion will be appreciate.

Comment (YuriSizov) [reply scene/gui/graph_node.cpp:395]: That's curious. I'd need to check myself, because `get_child()` should not itself crash for non-existent children, and it already checks for the number of children internally.

**Review by YuriSizov — CHANGES_REQUESTED** [review]
Formally marking as "Request changes", see the discussion above.

File: scene/gui/graph_node.cpp (hunk 1 above)
Comment (John-Gdi) [reply scene/gui/graph_node.cpp]: @YuriSizov, thanks for your professional explanation, and i have updated the commit according to your advice, please take a view, thanks!

File: scene/gui/graph_node.cpp [hunk 2]
```diff
@@ -366,38 +366,40 @@ void GraphNode::_notification(int p_what) {
...
-				if (!slot_info.has(E.key)) {
-					continue;
-				}
-				const Slot &s = slot_info[E.key];
-				// Left port.
-				if (s.enable_left) {
-					Ref<Texture2D> p = port;
-					if (s.custom_slot_left.is_valid()) {
-						p = s.custom_slot_left;
+			if(get_child_count() > 0){
```
Comment (akien-mga) [inline scene/gui/graph_node.cpp:369]: Style issue. Please make sure to use the same style as surrounding code (or better, use clang-format locally to enforce it). See https://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html
```suggestion
			if (get_child_count() > 0) {
```

**Comment by YuriSizov** [comment]
When you will be updating your PR next, please amend the commit message as well. I've edited the title of your PR, you can use that.

File: scene/gui/graph_node.cpp (hunk 2 above)
Comment (John-Gdi) [reply scene/gui/graph_node.cpp]: @YuriSizov @akien-mga, I have update the PR and modified the style issue with clang-format. Thanks for your help again, i really learn a lot during the pr processing.

**Review by YuriSizov — APPROVED** [review]
LGTM

**Comment by YuriSizov** [comment]
Thanks!
