### PR TITLE
C#: Do not use DocCache when generating glue code

### LINKED ISSUE #76250: Building C# Assemblies fails because of missing generated files
```
❯ ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --push-nupkgs-local ~/dev/LocalNugetSource
Running MSBuild:  /usr/bin/dotnet msbuild /home/geo/dev/godot/modules/mono/glue/GodotSharp/GodotSharp.sln /restore /t:Build /p:Configuration=Debug /p:NoWarn=1591 /p:ClearNuGetLocalCache=true /p:PushNuGetToLocalSource=/home/geo/dev/LocalNugetSource
MSBuild version 17.4.1+fedecea9d for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
/home/geo/dev/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj(142,3): error MSB4019: The imported project "/home/geo/dev/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GeneratedIncludes.props" was not found. Confirm that the expression in the Import declaration "Generated/GeneratedIncludes.props" is correct, and that the file exists on disk.
/home/geo/dev/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/GodotSharpEditor.csproj(43,3): error MSB4019: The imported project "/home/geo/dev/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/Generated/GeneratedIncludes.props" was not found. Confirm that the expression in the Import declaration "Generated/GeneratedIncludes.props" is correct, and that the file exists on disk.
/home/geo/dev/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj(142,3): error MSB4019: The imported project "/home/geo/dev/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GeneratedIncludes.props" was not found. Confirm that the expression in the Import declaration "Generated/GeneratedIncludes.props" is correct, and that the file exists on disk.
  Godot.SourceGenerators.Internal -> /home/geo/dev/godot/modules/mono/glue/GodotSharp/Godot.SourceGenerators.Internal/bin/Debug/netstandard2.0/Godot.SourceGenerators.Internal.dll
```

I've been using the same script to build the dotnet version of godot for months:

```sh
#!/usr/bin/env bash

git tag -d last-build
git tag last-build

set -e

scons module_mono_enabled=yes
./bin/godot.linuxbsd.editor.x86_64.mono --headless --generate-mono-glue modules/mono/glue

#dotnet nuget add source ~/dev/LocalNugetSource --name LocalNugetSource
rm -rf ~/.local/share/godot/mono/GodotNuGetFallbackFolder
mkdir -p ~/.local/share/godot/mono/GodotNuGetFallbackFolder

./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin \
 --push-nupkgs-local ~/dev/LocalNugetSource

# Export templates
#scons target=template_debug module_mono_enabled=yes
#scons target=template_release module_mono_enabled=yes

```

It recently stared to fail so I tried to delete everything extra via `git clean -xfd` and now I'm unable to build the mono version.

_Originally posted by @geowarin in https://github.com/godotengine/godot/issues/75152#issuecomment-1513810811_

---

@geowarin Moving to a new issue, because it doesn't look like it has anything to do with that issue.

Please post your system configuration, in particular the output of `dotnet --info`. Additionally please post the full output of the `godot --generate-mono-glue` command.

### PR DESCRIPTION
**Pull request by RedworkDE**
- Fixes #76250
- See also https://github.com/godotengine/godot/pull/72855#issuecomment-1515491486

Just a workaround really, but I am not sure what the problem is and the in-editor documentation for these classes seems to work just fine.

### CODE REVIEW

File: editor/editor_help.cpp [hunk 1]
```diff
@@ -2256,7 +2256,7 @@ void EditorHelp::generate_doc() {
 		doc = memnew(DocTools);
 	}
 
-	if (first_attempt && FileAccess::exists(get_cache_full_path())) {
+	if (first_attempt && FileAccess::exists(get_cache_full_path()) && p_use_cache) {
```
Comment (akien-mga) [inline editor/editor_help.cpp:2259]: Nitpick, but you could check `p_use_cache` earlier so we don't need to access the filesystem if not needed.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
This commit seems to have caused a regression, the editor help no longer works (video by @KoBeWi on Windows, and I could confirm it on Linux too):

https://user-images.githubusercontent.com/4701338/233503506-75e459b4-7c20-41d0-aafa-468fac3e9b02.mp4
