### PR TITLE
Fixed incorrect type display of function arguments in GDScript editor tooltips

### LINKED ISSUE #63017: Incorrect type display of function arguments in GDScript editor tooltips
### Godot version

4.0.alpha12

### System information

Windows11, Nvidia RTX 2060, Vulkan

### Issue description

For function arguments without a defined type but with a default value set, the arguments type will be displayed as the type of the default value in the editor tooltip (should be Variant)
image

### Steps to reproduce

Just look at the tooltip when calling the fn function:
```GDScript
func _ready():
	fn()


func fn(x = [1, 2, 3], y:int = 1):
	return
```

### Minimal reproduction project

```GDScript
func _ready():
	fn()


func fn(x = [1, 2, 3], y:int = 1):
	return
```

### PR DESCRIPTION
**Pull request by Xwdit**
For function arguments without a defined type but with a default value set, the arguments type will be displayed as the type of the default value in the editor tooltip (should be Variant)  

Fix #63017

Before this PR:
image

After:
image

### CODE REVIEW

**Comment by Xwdit** [comment]
Also note that for the current Master branch, the default value of the function parameter will not be displayed in the tooltip, so the picture shows the effect after merging #62934 and #62994

File: modules/gdscript/gdscript_editor.cpp [hunk 1]
```diff
@@ -671,7 +671,12 @@ static String _make_arguments_hint(const GDScriptParser::FunctionNode *p_functio
 			arghint += String::chr(0xFFFF);
 		}
 		const GDScriptParser::ParameterNode *par = p_function->parameters[i];
-		arghint += par->identifier->name.operator String() + ": " + par->get_datatype().to_string();
+
+		if (par->datatype_specifier == nullptr) {
```
Comment (cdemirer) [inline modules/gdscript/gdscript_editor.cpp:675]: This looks like it doesn't consider inferred static types (`:=`).

Using `is_hard_type()` might be a better idea.

Comment (Xwdit) [reply modules/gdscript/gdscript_editor.cpp]: Thanks for your guidance, I have fixed it

**Comment by Xwdit** [comment]
> Needs rebase to fix CI due to a temporary godot-cpp issue.

Rebased to fix CI issue

**Review by akien-mga — APPROVED** [review]
