### PR TITLE
Fix vertical alignment of Inspector category titles

### LINKED ISSUE #110302: Inspector Category text is not vertically centered
### Tested versions

Reproducible in Godot 4.2 onwards

### System information

Godot v4.5.rc1.mono - Windows 11 (build 26100) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2080 (NVIDIA; 32.0.15.8108) - AMD Ryzen 7 5700X 8-Core Processor (16 threads) - 31.91 GiB memory

### Issue description

The text in the inspector category headings is not vertically centered - it sits slightly too high.

Image

### Steps to reproduce

- Open any Godot project.
- Create a Node.
- View its properties in the inspector.
- The category headings will have slightly offset text.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Unbansheee**
Fixes https://github.com/godotengine/godot/issues/110302

Before:
Godot_v4 5-beta7_mono_win64_pCvQXk6NKg

After:
godot windows editor x86_64_HFoWMlcpEI

### CODE REVIEW

File: editor/inspector/editor_inspector.cpp [hunk 1]
```diff
@@ -1678,7 +1678,8 @@ void EditorInspectorCategory::_notification(int p_what) {
 			if (is_layout_rtl()) {
 				ofs = get_size().width - ofs - w;
 			}
-			float text_pos_y = font->get_ascent(font_size) + (get_size().height - font->get_height(font_size)) / 2 + v_margin_offset;
+			float font_height = font->get_height(font_size);
+			float text_pos_y = (get_size().height - font_height) + (font_height / 2) + v_margin_offset;
```
Comment (rsubtil) [inline editor/inspector/editor_inspector.cpp]: Seems like this can be simplified to this, can you confirm please?
```suggestion
			float text_pos_y = get_size().height - (font_height / 2) + v_margin_offset;
```

Comment (Unbansheee) [reply editor/inspector/editor_inspector.cpp]: Good catch, can confirm the simplified version is valid

**Comment by Unbansheee** [comment]
Further investigation shows that this may be a platform specific issue. This doesn't seem to be a problem on other platforms, and while this PR fixes it on Windows, it causes a regression for other platforms. 
Will investigate further tomorrow

File: editor/inspector/editor_inspector.cpp [hunk 2]
```diff
@@ -1678,7 +1678,8 @@ void EditorInspectorCategory::_notification(int p_what) {
 			if (is_layout_rtl()) {
 				ofs = get_size().width - ofs - w;
 			}
-			float text_pos_y = font->get_ascent(font_size) + (get_size().height - font->get_height(font_size)) / 2 + v_margin_offset;
+			float font_height = font->get_height(font_size);
+			float text_pos_y = get_size().height - (font_height / 2) + v_margin_offset;
 			Point2 text_pos = Point2(ofs, text_pos_y).round();
 			draw_string(font, text_pos, label, HORIZONTAL_ALIGNMENT_LEFT, w, font_size, theme_cache.font_color);
```
Comment (bruvzg) [inline editor/inspector/editor_inspector.cpp]:
```c++
Ref<TextLine> tl;
tl.instantiate();
tl->add_string(label, font, font_size);
tl->set_width(w);
tl->set_horizontal_alignment(HORIZONTAL_ALIGNMENT_LEFT);
float text_pos_y = (get_size().height - tl->get_size().height) / 2 + v_margin_offset;
Point2 text_pos = Point2(ofs, text_pos_y).round();
tl->draw(get_canvas_item(), text_pos, theme_cache.font_color);
```
Using real text metrics should always work, regardless of fonts and system font fallbacks in use.

Comment (Unbansheee) [reply editor/inspector/editor_inspector.cpp]: I can confirm this works, at least on my end. Will need someone else to validate. I have integrated this into the PR

**Review by Calinou — APPROVED** [review]
Tested locally on Linux, it works as expected.

### Default settings at various editor scales

75% | 100% | 125%
-|-|-
image | image | image

150% | 175% | 200%
-|-|-
image | image | image

### Custom settings

Inter, no hinting | Adwaita Mono, full hinting | Comic Neue, no hinting, size 17 |
-|-|-
image |  image | image

File: editor/inspector/editor_inspector.cpp [hunk 3]
```diff
@@ -1678,9 +1678,15 @@ void EditorInspectorCategory::_notification(int p_what) {
...
 				ofs = get_size().width - ofs - w;
 			}
-			float text_pos_y = font->get_ascent(font_size) + (get_size().height - font->get_height(font_size)) / 2 + v_margin_offset;
+
+			Ref<TextLine> tl;
+			tl.instantiate();
+			tl->add_string(label, font, font_size);
+			tl->set_width(w);
+			tl->set_horizontal_alignment(HORIZONTAL_ALIGNMENT_LEFT);
+			float text_pos_y = (get_size().height - tl->get_size().height) / 2 + v_margin_offset;
```
Comment (Calinou) [inline editor/inspector/editor_inspector.cpp:1690]: Add a comment to explain why we go the TextLine approach:

```suggestion
			// Use TextLine so we have access to accurate font metrics. This way,
			// we can ensure the line is vertically centered regardless of the font used
			// or its size.
			Ref<TextLine> tl;
			tl.instantiate();
			tl->add_string(label, font, font_size);
			tl->set_width(w);
			tl->set_horizontal_alignment(HORIZONTAL_ALIGNMENT_LEFT);
			float text_pos_y = (get_size().height - tl->get_size().height) / 2 + v_margin_offset;
```

**Comment by Calinou** [comment]
Remember to [squash commits into a single commit](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase) so this can be merged.

**Comment by fstxz** [comment]
I tested this again, works as expected now.

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
