### PR TITLE
Unify editor icon palette, fix up some inconsistent icons, theme usage

### LINKED ISSUE #57129: [4.0] Certain icons are shrunken (SVG scale not taken into account)
### Godot version

4.0-dev (6a3ff8f), 4.0-alpha1

### System information

Manjaro Linux 21.2.2

### Issue description

I found a few icons that are shrunken down compared to other ones.
One is the ruler tool and the others are the NavigationAgent and NavigationObstacle nodes.

image
image

### Steps to reproduce

Look for the icons on the latest commit or alpha1.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by YuriSizov**
Closes https://github.com/godotengine/godot/issues/57129. Part of https://github.com/godotengine/godot/issues/56790.

So I've decided to faint two pokemons with one move. The issue https://github.com/godotengine/godot/issues/56790 put the spotlight on inconsistencies with how editor's SVG icons are created and saved. I've used this opportunity to fix not only scaling issues, but also a bunch of other problems. For example, the breakpoint icon was not only too big, but also malformed (it's supposed to have two discs!). Several icons weren't optimized. Some were hiding their colors in the `style` attribute instead of individual SVG attributes for fill or stroke color.

godot windows tools 64_2022-01-28_16-15-03

This was important to start addressing https://github.com/godotengine/godot/issues/57129. I've tried to reduce the number of used colors as much as possible, but there are still a lot of niche colors that we cannot work around. So the conversion table had to be extended as well. I've picked colors without looking too much into how well they work, because that would take an enormous amount of time. They should be sensible, but I'm open to correct the base colors and converted colors in this or future PRs.

godot windows tools 64_2022-01-28_19-29-28

I've also stored the colors that we don't want to convert, simply for completeness. As described in https://github.com/godotengine/godot/issues/57129, we should want to add some sort of CI test/build task to validate the structure of SVGs to avoid aforementioned problems. As such, the conversion table acts as a natural start for tracking our complete panel, so that colors can be validated against it in an organized manner. Refer to my comment https://github.com/godotengine/godot/issues/56790#issuecomment-1024363712 for a bit more details on the matter.

godot windows tools 64_2022-01-28_19-54-08

-----

While updating icons, I've also noticed a few occasions of icons not working well for the light theme. Part of that were aforementioned issues, but in case of the path and curve editors it was just bad code, so I've fixed it in a dedicated commit. I could've made it a separate PR, but without the rest of these changes, I don't think you can test it.

image

-----

PS. Commits are separate for obvious reasons, they tackle different things and it should be clearer this way. They are still valid independently, but build upon each other.

### CODE REVIEW

File: editor/editor_themes.cpp [hunk 1]
```diff
@@ -174,30 +188,51 @@ void editor_register_and_generate_icons(Ref<Theme> p_theme, bool p_dark_theme =
...
+		ADD_CONVERT_COLOR(dark_icon_color_dictionary, "#dbee15", "#b7d10a"); // Color track yellow
+		ADD_CONVERT_COLOR(dark_icon_color_dictionary, "#288027", "#218309"); // Color track green
+
 		ADD_CONVERT_COLOR(dark_icon_color_dictionary, "#ffca5f", "#fea900"); // Mesh resource (orange)
-		ADD_CONVERT_COLOR(dark_icon_color_dictionary, "#0787ff", "#68b6ff"); // Shape resource (blue)
+		ADD_CONVERT_COLOR(dark_icon_color_dictionary, "#2998ff", "#68b6ff"); // Shape resource (blue)
+		ADD_CONVERT_COLOR(dark_icon_color_dictionary, "#a2d2ff", "#4998e3"); // Shape resource (light blue)
 
-		ADD_CONVERT_COLOR(dark_icon_color_dictionary, "#ff5f5f", "#ff3333"); // Red audio gradient + remove (red)
+		ADD_CONVERT_COLOR(dark_icon_color_dictionary, "#ff5f5f", "#ff3333"); // Remove (red)
```
Comment (akien-mga) [inline editor/editor_themes.cpp:209]: This duplicates `// Red` that you added up.

File: editor/editor_themes.cpp [hunk 2]
```diff
@@ -246,7 +286,7 @@ void editor_register_and_generate_icons(Ref<Theme> p_theme, bool p_dark_theme =
 	const Color error_color = p_theme->get_color("error_color", "Editor");
 	const Color success_color = p_theme->get_color("success_color", "Editor");
 	const Color warning_color = p_theme->get_color("warning_color", "Editor");
-	dark_icon_color_dictionary[Color::html("#ff0000")] = error_color;
+	dark_icon_color_dictionary[Color::html("#ff5d5d")] = error_color;
```
Comment (akien-mga) [inline editor/editor_themes.cpp:290]: That's a third override for red as defined in lines 191 and 208, is that intended?

File: editor/plugins/abstract_polygon_2d_editor.cpp [hunk 3]
```diff
@@ -147,14 +147,16 @@ void AbstractPolygon2DEditor::_menu_option(int p_option) {
 
 void AbstractPolygon2DEditor::_notification(int p_what) {
 	switch (p_what) {
+		case NOTIFICATION_ENTER_TREE:
+		case NOTIFICATION_THEME_CHANGED: {
+			button_create->set_icon(get_theme_icon(SNAME("CurveCreate"), SNAME("EditorIcons")));
+			button_edit->set_icon(get_theme_icon(SNAME("CurveEdit"), SNAME("EditorIcons")));
+			button_delete->set_icon(get_theme_icon(SNAME("CurveDelete"), SNAME("EditorIcons")));
+			button_edit->set_pressed(true);
```
Comment (akien-mga) [inline editor/plugins/abstract_polygon_2d_editor.cpp:155]: Is that relevant on theme changes? Otherwise it could stay in `ready`.

File: editor/plugins/path_2d_editor_plugin.cpp [hunk 4]
```diff
@@ -531,42 +530,42 @@ Path2DEditor::Path2DEditor(EditorNode *p_editor) {
 	CanvasItemEditor::get_singleton()->add_control_to_menu_panel(base_hb);
 
 	sep = memnew(VSeparator);
+
```
Comment (akien-mga) [inline editor/plugins/path_2d_editor_plugin.cpp:533]: That separation line should be before `curve_edit = memnew(Button);` no? Instead of separating the instantiation of `sep` and its `add_child` call.

File: editor/plugins/path_3d_editor_plugin.cpp [hunk 5]
```diff
@@ -539,12 +539,29 @@ void Path3DEditorPlugin::_handle_option_pressed(int p_option) {
...
-		curve_del->connect("pressed", callable_mp(this, &Path3DEditorPlugin::_mode_changed), make_binds(2));
-		curve_close->connect("pressed", callable_mp(this, &Path3DEditorPlugin::_close_curve));
+	switch (p_what) {
+		case NOTIFICATION_ENTER_TREE: {
+			curve_create->connect("pressed", callable_mp(this, &Path3DEditorPlugin::_mode_changed), make_binds(0));
+			curve_edit->connect("pressed", callable_mp(this, &Path3DEditorPlugin::_mode_changed), make_binds(1));
+			curve_del->connect("pressed", callable_mp(this, &Path3DEditorPlugin::_mode_changed), make_binds(2));
+			curve_close->connect("pressed", callable_mp(this, &Path3DEditorPlugin::_close_curve));
+
+			_update_theme();
```
Comment (akien-mga) [inline editor/plugins/path_3d_editor_plugin.cpp:559]: Should you also handle `NOTIFICATION_THEME_CHANGED` with `_update_theme`?

Comment (akien-mga) [reply editor/plugins/path_3d_editor_plugin.cpp:559]: Ah nevermind, I see it's connected to `theme_changed` and that gives meaning to the above `TODO`, I guess this plugin doesn't get `NOTIFICATION_THEME_CHANGED`?

**Review by akien-mga — APPROVED** [review]

File: editor/editor_themes.cpp (hunk 2 above)
Comment (pycbouh) [reply editor/editor_themes.cpp:290]: I initially split the other two because they were used in different context. It was intentional, but given this override here is always applied, I guess there is simply no point.

File: editor/plugins/path_3d_editor_plugin.cpp (hunk 5 above)
Comment (pycbouh) [reply editor/plugins/path_3d_editor_plugin.cpp:559]: Indeed, `EditorPlugin` is not a control and doesn't have it, which is why I had to rely on the signal instead. Decided not to risk with a proper fix here amongst all the other changes.

**Comment by pycbouh** [comment]
I've moved around some of those error/warning/success, red/orange/green colors. Apparently, the old success color was not in use, same as the old error color (which was the only thing I fixed initially). So I've gone ahead and reduced the palette further, making sure those replacements actually get applied.

**Comment by akien-mga** [comment]
Thanks!
