### PR TITLE
Return at invalid skeleton in ChainIK3D before updating mutable info

### LINKED ISSUE #114059: Moving a IK Modifier Node away from parent Skeleton while active crashes the Editor
### Tested versions

Reproducible in v4.6.beta.custom_build [4b6c88ded]

### System information

Godot v4.6.beta (4b6c88ded) - EndeavourOS #1 SMP PREEMPT_DYNAMIC Tue, 29 Apr 2025 09:23:13 +0000 on X11 - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated AMD Radeon RX 6800 XT (RADV NAVI21) - AMD Ryzen 7 7700 8-Core Processor (16 threads) - 30.46 GiB memory

### Issue description

It appears that moving an IK node somewhere else in the scene tree outside of it's skeleton while it is configured causes an engine crash, i've reproduced it with all of the new IK nodes that came in with 4.6

https://github.com/user-attachments/assets/4121b0fc-e3c4-496c-b453-263498fe005e

 

### Steps to reproduce

1. Import Blender File
2. Mark Imported Scene Editable Children
3. Add IK Node as a child of the Skeleton
4. Config IK Settings with bones and target node
5. Move IK node to a new parent

### Minimal reproduction project (MRP)

[skelecrash.zip](https://github.com/user-attachments/files/24176921/skelecrash.zip)

### PR DESCRIPTION
**Pull request by CSLRDoesntGameDev**
pretty self explanatory i hope.. in my testing it fixes the segfault reported in https://github.com/godotengine/godot/issues/114059 when moving a ChainIK3D derived node from its parent skeleton in the editor's scene tree

edit:

been trying to find an alternative way of doing this and couldn't really find one that was a solid fix, it seems like for some reason the function that caused the segfault gets called a few times once its gone from the skeleton's hierarchy.

either way it's probably a good idea to return when the skeleton is invalid because right after the skeleton check it's getting referenced 

* *Bugsquad edit, fixes: https://github.com/godotengine/godot/issues/114059*

### CODE REVIEW

File: scene/3d/chain_ik_3d.cpp [hunk 1]
```diff
@@ -497,6 +497,7 @@ void ChainIK3D::_update_mutable_info() {
 		for (uint32_t i = 0; i < settings.size(); i++) {
 			chain_settings[i]->root_global_rest = Transform3D();
 		}
+		return;
```
Comment (fire) [inline scene/3d/chain_ik_3d.cpp:500]: @TokageItLab Thoughts on this? This code becomes an early return but did we forget to cleanup everything?

**Review by TokageItLab — APPROVED** [review]
Needs to rebase to follow our [PR workflow](https://docs.godotengine.org/en/4.4/contributing/workflow/pr_workflow.html) (this PR must contain only 1 commit).
