### PR TITLE
[Android] `JavaClassWrapper` bug fixes

### LINKED ISSUE #109671: JNI ERROR: local reference table overflow (max=512)
### Tested versions

- Reproducible in 4.5 beta 5
- Reproducible in 4.4.1 stable

### System information

Linux Fedora 42

### Issue description

Crash when calling `decorView.setBackgroundColor(Color.RED.to_argb32())`
```
A  art/runtime/indirect_reference_table.cc:116] JNI ERROR (app bug): local reference table overflow (max=512)
A  art/runtime/indirect_reference_table.cc:116] local reference table dump:
A  art/runtime/indirect_reference_table.cc:116]   Last 10 entries (of 512):
A  art/runtime/indirect_reference_table.cc:116]       511: 0x12f1e880 java.lang.reflect.Method
A  art/runtime/indirect_reference_table.cc:116]       510: 0x12f1e858 java.lang.reflect.Method
A  art/runtime/indirect_reference_table.cc:116]       509: 0x12f1e830 java.lang.reflect.Method
A  art/runtime/indirect_reference_table.cc:116]       508: 0x12f1e808 java.lang.reflect.Method
A  art/runtime/indirect_reference_table.cc:116]       507: 0x12f1e7e0 java.lang.reflect.Method
A  art/runtime/indirect_reference_table.cc:116]       506: 0x12f1e7b8 java.lang.reflect.Method
A  art/runtime/indirect_reference_table.cc:116]       505: 0x12f1e790 java.lang.reflect.Method
A  art/runtime/indirect_reference_table.cc:116]       504: 0x12f1e768 java.lang.reflect.Method
 A  art/runtime/indirect_reference_table.cc:116]       503: 0x12f1e740 java.lang.reflect.Method
A  art/runtime/indirect_reference_table.cc:116]       502: 0x12f1e718 java.lang.reflect.Method
A  art/runtime/indirect_reference_table.cc:116]   Summary:
A  art/runtime/indirect_reference_table.cc:116]         8 of java.lang.Class (7 unique instances)
A  art/runtime/indirect_reference_table.cc:116]         4 of java.lang.String (4 unique instances)
A  art/runtime/indirect_reference_table.cc:116]         5 of java.lang.reflect.Constructor (5 unique instances)
A  art/runtime/indirect_reference_table.cc:116]       492 of java.lang.reflect.Method (492 unique instances)
A  art/runtime/indirect_reference_table.cc:116]         1 of java.lang.String[] (4 elements)
A  art/runtime/indirect_reference_table.cc:116]         1 of java.lang.reflect.Constructor[] (5 elements)
A  art/runtime/indirect_reference_table.cc:116]         1 of java.lang.reflect.Method[] (780 elements)
A  art/runtime/indirect_reference_table.cc:116] 
A  art/runtime/runtime.cc:403] Runtime aborting...
```

### Steps to reproduce

Just call this method:

```
func _on_button_pressed() -> void:
	var android_runtime = Engine.get_singleton("AndroidRuntime")
	var activity = android_runtime.getActivity()
	var callable = func ():
		var decorView = activity.getWindow().getDecorView()
		decorView.setBackgroundColor(Color.RED.to_argb32())
	
	activity.runOnUiThread(android_runtime.createRunnableFromGodotCallable(callable))
```

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by m4gr3d**
- Adds implementation of `has_java_method(...)` for `JavaClassWrapper` and `JNISingleton`
  - Addresses https://github.com/godotengine/godot/issues/106436
- Catch exceptions thrown during 'wrapping' of the Java class
  - Fixes crash described in https://github.com/godotengine/godot/issues/109667
- Cleaning local references during 'wrapping' of the Java class to prevent local references overflow
  - Fixes https://github.com/godotengine/godot/issues/109671

### CODE REVIEW

File: core/object/object.h [hunk 1]
```diff
@@ -854,7 +854,7 @@ class Object {
 	bool property_can_revert(const StringName &p_name) const;
 	Variant property_get_revert(const StringName &p_name) const;
 
-	bool has_method(const StringName &p_method) const;
+	virtual bool has_method(const StringName &p_method) const;
```
Comment (dsnopek) [inline core/object/object.h]: If we're going to make `has_method()` something that child classes can override, we should also make that possible via GDExtension (so, `GDVIRTUAL1R(bool, _has_method, StringName)` and all that)

**Review by dsnopek — COMMENTED** [review]
I think making `Object::has_method()` virtual should be discussed with the core team

Personally, I have kind of mixed feelings about it. This will mean that there are methods that will return `true` for `has_method()` but that won't be included in `get_method_list()`, which isn't currently the case.

We already have `JavaClass::get_java_method_list()` to list methods from Java - perhaps we should just add a `JavaClass::has_java_method()` and not mess with `Object`?

**Comment by m4gr3d** [comment]
> I think making `Object::has_method()` virtual should be discussed with the core team
> 
> Personally, I have kind of mixed feelings about it. This will mean that there are methods that will return `true` for `has_method()` but that won't be included in `get_method_list()`, which isn't currently the case.
> 
> We already have `JavaClass::get_java_method_list()` to list methods from Java - perhaps we should just add a `JavaClass::has_java_method()` and not mess with `Object`?

I went with that approach for consistency; users expect to use `has_method()` to check for a method's existence, they would expect the same for `JavaClassWrapper` and `JNISingleton` (see the issue referenced in the description). 
I wasn't aware that `get_java_method_list()` was the counterpart for `get_method_list()`, but I would also be in favor of overriding the latter for consistency as well.

**Comment by dsnopek** [comment]
> I wasn't aware that `get_java_method_list()` was the counterpart for `get_method_list()`, but I would also be in favor of overriding the latter for consistency as well.

If we made both `has_method()` and `get_method_list()` virtual, that would allow making those consistent with each other, which would be good. I still feel a little unsure about this, though

File: core/object/object.h (hunk 1 above)
Comment (dsnopek) [reply core/object/object.h]: Actually, if we made this overrideable via GDExtension, we might want to do it through the GDExtension interface rather than normal virtual methods, because I don't think it makes sense for scripts to be able to override this method

**Comment by syntaxerror247** [comment]
I think, it's better to support `has_method()` and `get_method_list()` instead of having counterparts. But yeah, I agree that it should be discussed with core.

**Comment by m4gr3d** [comment]
> > I wasn't aware that `get_java_method_list()` was the counterpart for `get_method_list()`, but I would also be in favor of overriding the latter for consistency as well.
> 
> If we made both `has_method()` and `get_method_list()` virtual, that would allow making those consistent with each other, which would be good. I still feel a little unsure about this, though

@dsnopek An alternative to making both methods virtual would be to check for `JNISingleton` and `JavaClassWrapper` classes within `Object` implementations and explicitly call `has_java_method()` and `get_java_method_list()` from there.

**Comment by m4gr3d** [comment]
> @dsnopek An alternative to making both methods virtual would be to check for `JNISingleton` and `JavaClassWrapper` classes within `Object` implementations and explicitly call `has_java_method()` and `get_java_method_list()` from there.

That'd require an `include` from `object.cpp` onto `platform/android/api`.. are dependencies from `core` to `platform` allowed?

**Review by Ivorforce — COMMENTED** [review]
I'm not sure this is a great idea.

This would introduce a path for `Object` subclasses to define methods that are not registered in `ClassDB`, introducing 'dynamic typing' as a whole new concept to our ecosystem. Adding this would make it impossible (or at least much harder) to cache method pointers on a `Class` level, which is something I've shown in https://github.com/godotengine/godot/pull/106646 to accelerate property access by at least 60% (with potential for more).

Is there some other way this could be resolved? Perhaps this is just an indication for Java functions to register their existing methods in `ClassDB` (or in the scripts way)?

**Comment by dsnopek** [comment]
> This would introduce a path for `Object` subclasses to define methods that are not registered in `ClassDB`, introducing 'dynamic typing' as a whole new concept to our ecosystem.

It's already possible for classes to have "dynamic methods" that aren't registered in `ClassDB`, which is used in a couple places, including `JavaClassWrapper` (for Android) and `JavaScriptBridge` (for the web).

However, those methods aren't currently recognized by `has_method()` and `get_method_list()`

> > @dsnopek An alternative to making both methods virtual would be to check for `JNISingleton` and `JavaClassWrapper` classes within `Object` implementations and explicitly call `has_java_method()` and `get_java_method_list()` from there.
> 
> That'd require an `include` from `object.cpp` onto `platform/android/api`.. are dependencies from `core` to `platform` allowed?

I think I probably like this idea less than making `has_method()` and `get_method_list()` virtual. :-/ This feels kinda hacky and only addresses `JavaClassWrapper`, but none of the other places (ex `JavaScriptBridge`) that also have dynamic methods

If we need a short-term solution, I think that should probably be adding `JavaClass::has_java_method()`. Then we can continue discussing a core change for the longer-term?

**Comment by Ivorforce** [comment]
> > This would introduce a path for `Object` subclasses to define methods that are not registered in `ClassDB`, introducing 'dynamic typing' as a whole new concept to our ecosystem.
> 
> It's already possible for classes to have "dynamic methods" that aren't registered in `ClassDB`, which is used in a couple places, including `JavaClassWrapper` (for Android) and `JavaScriptBridge` (for the web).
> 
> However, those methods aren't currently recognized by `has_method()` and `get_method_list()`

That's unfortunate. Do you know the reason for this (i.e. why it's not going through the usual scripting interfaces)?

**Comment by dsnopek** [comment]
> That's unfortunate. Do you know the reason for this (i.e. why it's not going through the usual scripting interfaces)?

Well, I don't think this could work through the scripting interfaces, at least not nicely. I guess we could dynamically generate a script resource for each native class we wanted to wrap, or something like that?

Anyway, this is something that has existed since Godot was open sourced, so I don't personally know the original thinking behind it

**Comment by m4gr3d** [comment]
> If we need a short-term solution, I think that should probably be adding JavaClass::has_java_method(). Then we can continue discussing a core change for the longer-term?

Who should we loop from `core` that can weigh in? 

Once we go with `has_java_method(...)`, we are unlikely to revisit this discussion unless there's a forcing function, so I'd rather we align on the longer term approach and go with that.

**Comment by m4gr3d** [comment]
@dsnopek Could you validate the updated PR against your `JavaClassWrapper` set of tests?

**Comment by syntaxerror247** [comment]
Thanks! I tested it and confirmed that it fixes the local references overflow issue. It also resolves the crash during class wrapping caused by NoClassDefFoundError, and has_java_method() works as expected.

File: platform/android/java_class_wrapper.cpp [hunk 2]
```diff
@@ -873,10 +850,15 @@ JavaClass::~JavaClass() {
 /////////////////////
 
 Variant JavaObject::callp(const StringName &p_method, const Variant **p_args, int p_argcount, Callable::CallError &r_error) {
+	// Godot methods take precedence.
+	Variant ret = RefCounted::callp(p_method, p_args, p_argcount, r_error);
+	if (r_error.error == Callable::CallError::CALL_OK) {
+		return ret;
+	}
+
```
Comment (syntaxerror247) [inline platform/android/java_class_wrapper.cpp:858]: Why was this change made? Shouldn’t Java methods take precedence when dealing with JavaClass or JavaObject?

Comment (syntaxerror247) [reply platform/android/java_class_wrapper.cpp:858]: I suppose it’s not really a problem. It’s just something that feels a bit unexpected to me.

**Review by syntaxerror247 — APPROVED** [review]
I skimmed through the changes; looks good to me!

File: platform/android/java_class_wrapper.cpp (hunk 2 above)
Comment (m4gr3d) [reply platform/android/java_class_wrapper.cpp:858]: Since a `JavaObject` extends from `RefCounted`, it has also access to methods from `RefCounted` and `Object`.

Suppose a wrapped Java class defines a `reference()` method in its API; without the added logic, the Java version of `reference()` would shadow the `RefCounted` version of `reference()`. 

So the added logic ensures that whenever there's overlap, the Godot methods take precedence.

**Comment by dsnopek** [comment]
> @dsnopek Could you validate the updated PR against your `JavaClassWrapper` set of tests?

FYI, my test project is here:

https://github.com/dsnopek/javaclasswrapper-test

The project will run a bunch of automated tests and print any failures to the log, as well as a couple interactive tests with some buttons you can press. I've basically added tests for every `JavaClassWrapper` bug I've had to fix :-) - I guess I should add some based on these bugs too!

Unfortunately, this PR crashes with my test project:

```
JNI DETECTED ERROR IN APPLICATION: JNI ERROR (app bug): jobject is an invalid local reference: 0x74
2c97c289 (reference at index 34 with bad serial number 2 v. 3 (valid 1 - 3))
```

I haven't had a chance to do any debugging yet

**Comment by syntaxerror247** [comment]
> FYI, my test project is here:
> 
> https://github.com/dsnopek/javaclasswrapper-test

@dsnopek I think this repo is private. I can't access it.

**Comment by dsnopek** [comment]
> @dsnopek I think this repo is private. I can't access it.

Oops! Sorry, I didn't realize it was private. Should be public now!

**Comment by m4gr3d** [comment]
> > @dsnopek Could you validate the updated PR against your `JavaClassWrapper` set of tests?
> 
> FYI, my test project is here:
> 
> https://github.com/dsnopek/javaclasswrapper-test
> 
> The project will run a bunch of automated tests and print any failures to the log, as well as a couple interactive tests with some buttons you can press. I've basically added tests for every `JavaClassWrapper` bug I've had to fix :-) - I guess I should add some based on these bugs too!
> 
> Unfortunately, this PR crashes with my test project:
> 
> ```
> JNI DETECTED ERROR IN APPLICATION: JNI ERROR (app bug): jobject is an invalid local reference: 0x74
> 2c97c289 (reference at index 34 with bad serial number 2 v. 3 (valid 1 - 3))
> ```
> 
> I haven't had a chance to do any debugging yet

@dsnopek @syntaxerror247 I fixed the remaining bugs uncovered by the regression tests.
Can you take another look at the PR.

**Review by syntaxerror247 — APPROVED** [review]
Code looks good!
I re-verified and it passes all the tests.

**Comment by Repiteo** [comment]
Thanks!
