### PR TITLE
Handle spaces correctly for base / parent scripts in the "New Script" dialog

### LINKED ISSUE #27547: Add Script dialog doesn't support paths with spaces for base script
**Godot version:**
Godot stable 3.1, daily builds

**OS/device including version:**
Windows 10 x64

**Issue description:**
if there are spaces in the path name when you try to extend a script the menu will not allow you to find the file being extended.
Screenshot (1)

**Steps to reproduce:**
try to extend a script with the Inherit from path having spaces in the path name. Also why does the path have quotations around it?

**Minimal reproduction project:**
I think issue #27307 is linked to this.

### PR DESCRIPTION
**Pull request by DrNochi**
The validation algorithm used for the selected parent script ("Inherits") did not account for spaces. If the parent script had a space in its name/path, an error was reported by the dialog. This made it impossible to inherit from a script with a space in its name.

This change unifies the path validation algorithm for the parent script's path with the one that is used for the path of the new script. This ensures that spaces are handled correctly and helps with a consistent path validation across the dialog.

fixes #27547

### CODE REVIEW

File: editor/script_create_dialog.cpp [hunk 1]
```diff
@@ -82,26 +82,20 @@ bool ScriptCreateDialog::_validate(const String &p_string) {
 	if (p_string.length() == 0)
 		return false;
 
-	String path_chars = "\"res://";
-	bool is_val_path = ScriptServer::get_language(language_menu->get_selected())->can_inherit_from_file();
+	if (ScriptServer::get_language(language_menu->get_selected())->can_inherit_from_file() && p_string.begins_with("\"") && p_string.ends_with("\"")) {
```
Comment (akien-mga) [inline editor/script_create_dialog.cpp]: Using `p_string.is_quoted()` instead to also support paths enclosed in single quotes.

**Comment by akien-mga** [comment]
Could you squash the commits together? The branch should also be released on master to fix a merge conflict.

**Comment by DrNochi** [comment]
Should be ready to merge now :)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by DrNochi** [comment]
np, you're welomce! :)
