### PR TITLE
Fix crash with FindReplaceBar

### LINKED ISSUE #49785: Close all open text editors causes crash
### Godot version

d696bd1

### System information

popos 20.04

### Issue description

Editor crashes when I use the right menu close all scripts.

### Steps to reproduce

1. use the right menu close all scripts.
2. crash

### Minimal reproduction project

Any project will crash.

### Other

https://github.com/godotengine/godot/blob/d696bd17ed1b7019108c8a573712f00ac2d735a3/editor/code_editor.cpp#L593-L595

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes regression from #49265

The editor was crashing with this backtrace, randomly when closing/opening scripts:
```
[0] Object::get_instance_id (C:\godot_source\core\object\object.h:627)
[1] CallableCustomMethodPointer<Label,String const &>::CallableCustomMethodPointer<Label,String const &> (C:\godot_source\core\object\callable_method_pointer.h:103)    
[2] create_custom_callable_function_pointer<Label,String const &> (C:\godot_source\core\object\callable_method_pointer.h:117)
[3] CodeTextEditor::remove_find_replace_bar (C:\godot_source\editor\code_editor.cpp:971)
[4] FindReplaceBar::set_text_edit (C:\godot_source\editor\code_editor.cpp:593)
[5] CodeTextEditor::set_find_replace_bar (C:\godot_source\editor\code_editor.cpp:963)
[6] ScriptTextEditor::set_find_replace_bar (C:\godot_source\editor\plugins\script_text_editor.cpp:1363)
[7] ScriptEditor::ensure_select_current (C:\godot_source\editor\plugins\script_editor_plugin.cpp:1645)
[8] ScriptEditor::_tab_changed (C:\godot_source\editor\plugins\script_editor_plugin.cpp:1465)
[9] call_with_variant_args_helper<ScriptEditor,int,0> (C:\godot_source\core\variant\binder_common.h:214)
[10] call_with_variant_args<ScriptEditor,int> (C:\godot_source\core\variant\binder_common.h:324)
[11] CallableCustomMethodPointer<ScriptEditor,int>::call (C:\godot_source\core\object\callable_method_pointer.h:97)
[12] Callable::call (C:\godot_source\core\variant\callable.cpp:51)
[13] Object::emit_signal (C:\godot_source\core\object\object.cpp:1084)
[14] Object::emit_signal (C:\godot_source\core\object\object.cpp:1139)
[15] TabContainer::add_child_notify (C:\godot_source\scene\gui\tab_container.cpp:735)
[16] Node::_add_child_nocheck (C:\godot_source\scene\main\node.cpp:1036)
[17] Node::add_child (C:\godot_source\scene\main\node.cpp:1051)
[18] ScriptEditor::edit (C:\godot_source\editor\plugins\script_editor_plugin.cpp:2246)
[19] ScriptEditor::edit (C:\godot_source\editor\plugins\script_editor_plugin.h:465)
[20] ScriptEditorPlugin::edit (C:\godot_source\editor\plugins\script_editor_plugin.cpp:3626)
[21] EditorNode::_edit_current (C:\godot_source\editor\editor_node.cpp:2193)
[22] EditorNode::push_item (C:\godot_source\editor\editor_node.cpp:1997)
[23] InspectorDock::_resource_selected (C:\godot_source\editor\inspector_dock.cpp:289)
[24] InspectorDock::edit_resource (C:\godot_source\editor\inspector_dock.cpp:380)
[25] EditorNode::load_resource (C:\godot_source\editor\editor_node.cpp:1074)
[26] FileSystemDock::_select_file (C:\godot_source\editor\filesystem_dock.cpp:985)
[27] FileSystemDock::_tree_activate_file (C:\godot_source\editor\filesystem_dock.cpp:999)
[28] call_with_variant_args_helper<FileSystemDock> (C:\godot_source\core\variant\binder_common.h:214)
[29] call_with_variant_args<FileSystemDock> (C:\godot_source\core\variant\binder_common.h:324)
[30] CallableCustomMethodPointer<FileSystemDock>::call (C:\godot_source\core\object\callable_method_pointer.h:97)
[31] Callable::call (C:\godot_source\core\variant\callable.cpp:51)
[32] Object::emit_signal (C:\godot_source\core\object\object.cpp:1084)
[33] Object::emit_signal (C:\godot_source\core\object\object.cpp:1139)
[34] Tree::_gui_input (C:\godot_source\scene\gui\tree.cpp:3143)
[35] call_with_variant_args_helper<Tree,Ref<InputEvent>,0> (C:\godot_source\core\variant\binder_common.h:214)
[36] call_with_variant_args_dv<Tree,Ref<InputEvent> > (C:\godot_source\core\variant\binder_common.h:357)
[37] MethodBindT<Tree,Ref<InputEvent> >::call (C:\godot_source\core\object\method_bind.h:285)
[38] Viewport::_gui_call_input (C:\godot_source\scene\main\viewport.cpp:1667)
[39] Viewport::_gui_input_event (C:\godot_source\scene\main\viewport.cpp:1923)
[40] Viewport::input (C:\godot_source\scene\main\viewport.cpp:3076)
[41] Window::_window_input (C:\godot_source\scene\main\window.cpp:916)
[42] call_with_variant_args_helper<Window,Ref<InputEvent> const &,0> (C:\godot_source\core\variant\binder_common.h:209)
[43] call_with_variant_args<Window,Ref<InputEvent> const &> (C:\godot_source\core\variant\binder_common.h:324)
[44] CallableCustomMethodPointer<Window,Ref<InputEvent> const &>::call (C:\godot_source\core\object\callable_method_pointer.h:97)
[45] Callable::call (C:\godot_source\core\variant\callable.cpp:51)
[46] DisplayServerWindows::_dispatch_input_event (C:\godot_source\platform\windows\display_server_windows.cpp:1798)
[47] DisplayServerWindows::_dispatch_input_events (C:\godot_source\platform\windows\display_server_windows.cpp:1772)
[48] Input::_parse_input_event_impl (C:\godot_source\core\input\input.cpp:643)
[49] Input::parse_input_event (C:\godot_source\core\input\input.cpp:466)
[51] DisplayServerWindows::process_events (C:\godot_source\platform\windows\display_server_windows.cpp:1534)
[52] OS_Windows::run (C:\godot_source\platform\windows\os_windows.cpp:622)
[53] widechar_main (C:\godot_source\platform\windows\godot_windows.cpp:163)
[54] _main (C:\godot_source\platform\windows\godot_windows.cpp:185)
[55] main (C:\godot_source\platform\windows\godot_windows.cpp:199)
[56] __scrt_common_main_seh (D:\a01\_work\26\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[57] BaseThreadInitThunk
```

Fixes #49785

### CODE REVIEW

File: editor/code_editor.cpp [hunk 1]
```diff
@@ -1655,6 +1655,12 @@ void CodeTextEditor::_notification(int p_what) {
 			warning_button->set_icon(get_theme_icon("NodeWarning", "EditorIcons"));
 			add_theme_constant_override("separation", 4 * EDSCALE);
 		} break;
+		case NOTIFICATION_EXIT_TREE: {
+			if (find_replace_bar) {
+				remove_child(find_replace_bar);
+				find_replace_bar = nullptr;
+			}
+		} break;
```
Comment (akien-mga) [inline editor/code_editor.cpp:1663]: Couldn't it be deleted here once instead of having to do it both in ScriptEditorPlugin and ShaderEditorPlugin?

File: editor/plugins/script_editor_plugin.cpp [hunk 2]
```diff
@@ -3606,6 +3606,7 @@ ScriptEditor::ScriptEditor(EditorNode *p_editor) {
 
 ScriptEditor::~ScriptEditor() {
 	memdelete(completion_cache);
+	memdelete(find_replace_bar);
```
Comment (akien-mga) [inline editor/plugins/script_editor_plugin.cpp:3609]: This causes a heap-use-after-free: https://github.com/godotengine/godot/pull/49650/checks?check_run_id=2837442073

File: editor/code_editor.cpp (hunk 1 above)
Comment (KoBeWi) [reply editor/code_editor.cpp:1663]: The problem is that code editor might be freed when closing script (not 100% sure when this happens though, as the crash is rather random). This is what was causing the bar being freed and the crash. I'm removing the bar to avoid freeing it. Script editor still has a reference, for shader editor I had to do a little workaround.

Comment (akien-mga) [reply editor/code_editor.cpp:1663]: I wonder if we're not getting more troubles than gain by reusing the same `FindReplaceBar` in different editors. It would be cleaner if there was one instance in each plugin as child of the plugin, which gets freed with it.

**Comment by KoBeWi** [comment]
Uh, I just realized that this fix doesn't make sense. The FindReplaceBar never changes its parent. I have no idea why this worked .-.

**Comment by Calinou** [comment]
I can confirm this fixes https://github.com/godotengine/godot/issues/49785.

**Comment by KoBeWi** [comment]
Ok, I think I fixed all the crashes now. The biggest problem was that TabContainer doesn't emit `tab_changed` when last tab is closed. I added a new method that checks if there is active editor and updates FindReplaceBar, and added some calls in all the spots that might affect current tab.

Also seems like script editor and find replace bar might be freed in different orders, so I added some safeguards.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
