### PR TITLE
Fix `noise_direction` variable used before initialized in particle shader when using turbulence with collisions

### LINKED ISSUE #83858: When both Collision and Turbulence are enabled, GPUParticles2D and GPUParticles3D will freeze and spam error messages
### Godot version

4.2 Beta2

### System information

Win 10, Nvidea 765M

### Issue description

When both Collision and Turbulence is enabled, GPUParticles2D and GPUParticles3D will freeze and spam error messages.
Both Collision and Turbulence work fine when the other is _not_ enabled.

Error message:

> No compute pipeline was set before attempting to draw.
> drivers/vulkan/rendering_device_vulkan.cpp:7892 - Parameter "pipeline" is null.
> This compute pipeline requires (0) bytes of push constant data, supplied: (32)

### Steps to reproduce

1. Add GPUParticles2D or GPUParticles3D node
2. Add texture/draw mesh and ParticleProcessMaterial
3. Enable Collision by setting it to "Rigid" in the ParticleProcessMaterial
4. Enable Turbulence
5. Observe the freeze and error spam

### Minimal reproduction project

N/A 
easier to follow the steps.

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes #83858

And why do we not use R""(Raw String Literal) to replace continuous `string +=` in `particle_process_material` ? Much cleaner and potentially faster.

### CODE REVIEW

File: scene/resources/particle_process_material.cpp [hunk 1]
```diff
@@ -984,6 +980,10 @@ void ParticleProcessMaterial::_update_shader() {
 		}
 		code += "		\n";
 		code += "		vec3 noise_direction = get_noise_direction(TRANSFORM[3].xyz);\n";
+		// set the noise direction to up so the turbulence color is "neutral"
+		code += "		if (COLLIDED && length(VELOCITY) <= 3.0) {\n";
```
Comment (AThousandShips) [inline scene/resources/particle_process_material.cpp:984]: This will hurt performance, see:
* https://github.com/godotengine/godot/pull/83749

Comment (jsjtxietian) [reply scene/resources/particle_process_material.cpp:984]: Thanks! I will rebase first and check it.

Comment (akien-mga) [reply scene/resources/particle_process_material.cpp:984]: Also small style nitpick, please remember to capitalize the first letter and end with a period on comments.

File: scene/resources/particle_process_material.cpp [hunk 2]
```diff
@@ -987,6 +983,10 @@ void ParticleProcessMaterial::_update_shader() {
 		// The following snippet causes massive performance hit. We don't need it as long as collision is disabled.
 		// Refer to GH-83744 for more info.
 		if (collision_mode != COLLISION_DISABLED) {
+			// Set the noise direction to up so the turbulence color is "neutral".
+			code += "		if (COLLIDED && length(VELOCITY) <= 3.0) {\n";
+			code += "			noise_direction = vec3(1.0, 0.0, 0.0);\n";
+			code += "		}\n";
```
Comment (clayjohn) [inline scene/resources/particle_process_material.cpp:989]: Comparing this to the code in 4.1 I am noticing a few issues worth thinking about. 
1: In 4.1 this equivalent branch did nothing as ``noise_direction`` was never used again:
https://github.com/godotengine/godot/blob/399c9dc393f6f84c0b4e4d4117906c70c048ecf2/scene/resources/particle_process_material.cpp#L873 CC @RPicster Do you remember the original reason for this code?
2. ``noise_direction`` is only ever used if ``!COLLIDED`` is true which means that this code will never impact anything anyway.
3. (This is a pre-existing issue) When collisions are disabled, the old code still ran the calculation for final velocity: https://github.com/godotengine/godot/blob/399c9dc393f6f84c0b4e4d4117906c70c048ecf2/scene/resources/particle_process_material.cpp#L720-L734

These two issues make me suspect that the original code setting ``noise_direction = vec3(1.0, 0.0, 0.0)`` was actually out of date before it was needed and can actually be removed entirely instead of moved here. 

I suggest that while removing that code, you also change the logic to match that in 4.1 so the ``!COLLIDED`` check is only added when using RIGID BODY collisions.

Comment (jsjtxietian) [reply scene/resources/particle_process_material.cpp:989]: Yes you are right, `noise_direction = vec3(1.0, 0.0, 0.0);\n"; ` is indeed useless now.

File: scene/resources/particle_process_material.cpp [hunk 3]
```diff
@@ -986,12 +982,14 @@ void ParticleProcessMaterial::_update_shader() {
 		code += "		vec3 noise_direction = get_noise_direction(TRANSFORM[3].xyz);\n";
 		// The following snippet causes massive performance hit. We don't need it as long as collision is disabled.
 		// Refer to GH-83744 for more info.
```
Comment (akien-mga) [inline scene/resources/particle_process_material.cpp:984]: I don't know if the change in this PR is correct, but if it is this comment might warrant being further tweaked. It used to sound like the whole `if` block was expensive, but now it seems reduced to only checking for `COLLIDED` is expensive. That should be made explicit.

Comment (jsjtxietian) [reply scene/resources/particle_process_material.cpp:984]: Agreed. And there is a minor tweak I miss, I will update it soon.

File: scene/resources/particle_process_material.cpp [hunk 4]
```diff
@@ -984,14 +980,18 @@ void ParticleProcessMaterial::_update_shader() {
...
-		// Refer to GH-83744 for more info.
-		if (collision_mode != COLLISION_DISABLED) {
+
+		// Godot detects when the COLLIDED keyword is used. If it's used anywhere in the shader then Godot will generate the screen space SDF for collisions.
+		// We don't need it as long as collision is disabled. Refer to GH-83744 for more info.
+		if (collision_mode == COLLISION_RIGID) {
 			code += "		if (!COLLIDED) {\n";
-			code += "			\n";
+		}
+		if (collision_mode != COLLISION_DISABLED) {
```
Comment (clayjohn) [inline scene/resources/particle_process_material.cpp:989]: I don't think this should have been added. This code should _always_ run when collisions are disabled. 

If collisions are set to rigid mode, then this code should only run when ``!COLLIDED`` is true.

Comment (jsjtxietian) [reply scene/resources/particle_process_material.cpp:989]: Sorry for the misunderstanding, I was a bit lost.

**Review by clayjohn — APPROVED** [review]
Looks great! Thanks for making so many changes

**Comment by akien-mga** [comment]
Thanks!
