### PR TITLE
[Viewport] Add option to inherit parents texture filter/repeat, use it for popups.

### LINKED ISSUE #113872: PopupMenu doesn't inherit Texture Filter from project or parents
### Tested versions

Reproducible in: 4.5.1.stable (Steam)
Untested in any further version

### System information

Godot v4.5.1.stable (f62fdbde1) - Windows 11 (build 26200) - Multi-window, 3 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 32.0.15.8129) - 13th Gen Intel(R) Core(TM) i5-13600KF (20 threads) - 63.81 GiB memory

### Issue description

PopupMenu (as a child of OptionButton) doesn't inherit the Default Texture Filter from both its parent and the project itself.

If the project and the parent of the PopupMenu are set to Nearest Filtering, the PopupMenu will remain the new project default of Linear Filtering.

### Steps to reproduce

- Set rendering/textures/canvas_textures/default_texture_filter to Nearest.
- Create a new theme and set the PopupMenu.panel property to a StyleBoxTexture.
- Assign an AtlasTexture to that StyleBoxTexture.
- Use a pixel art UI texture inside the AtlasTexture, then configure its region and texture margins.
- Create a new scene with a Control node as the root.
- Add an OptionButton to the scene and add several items to it.
- Apply the theme you created to the OptionButton.
- Set the OptionButton's texture_filter to Nearest.
- Run the project and click the OptionButton.

Result:
The PopupMenu appears blurry, while any pixel art texture directly assigned to the OptionButton itself renders correctly with nearest filtering.

### Minimal reproduction project (MRP)

[bug_report2.zip](https://github.com/user-attachments/files/24090593/bug_report2.zip)

This doesn't seem to be project-dependent, but we'll see.

### PR DESCRIPTION
**Pull request by bruvzg**
https://github.com/user-attachments/assets/7205ff9f-eb61-49af-b816-76103aedb7eb

Fixes https://github.com/godotengine/godot/issues/113872
Supersede https://github.com/godotengine/godot/pull/113883

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: scene/main/canvas_item.cpp [hunk 1]
```diff
@@ -1720,10 +1724,15 @@ void CanvasItem::_update_texture_repeat_changed(bool p_propagate) {
 	_update_self_texture_repeat(texture_repeat_cache);
 
 	if (p_propagate) {
-		for (uint32_t n = 0; n < data.canvas_item_children.size(); n++) {
-			CanvasItem *ci = data.canvas_item_children[n];
-			if (!ci->top_level && ci->texture_repeat == TEXTURE_REPEAT_PARENT_NODE) {
-				ci->_update_texture_repeat_changed(true);
+		for (int n = 0; n < get_child_count(); n++) {
+			Node *c = get_child(n);
```
Comment (KoBeWi) [inline scene/main/canvas_item.cpp]: You can do

```suggestion
		for (Node *c : iterate_children()) {
```

File: scene/main/canvas_item.cpp [hunk 2]
```diff
@@ -1720,10 +1724,15 @@ void CanvasItem::_update_texture_repeat_changed(bool p_propagate) {
...
+			CanvasItem *child_ci = Object::cast_to<CanvasItem>(c);
+			if (child_ci && child_ci->texture_repeat == CanvasItem::TEXTURE_REPEAT_PARENT_NODE) {
+				child_ci->_update_texture_repeat_changed(true);
+			}
+			Viewport *child_vp = Object::cast_to<Viewport>(c);
```
Comment (KoBeWi) [inline scene/main/canvas_item.cpp:1737]: Nitpick, but if the above conversion succeeds, checking also for Viewport is redundant. You could put a `continue` somewhere.

File: scene/main/canvas_item.cpp (hunk 1 above)
Comment (Ivorforce) [reply scene/main/canvas_item.cpp]: Beware that `iterate_children` makes no thread checks, and may crash under mutation. But if children are guaranteed not to change it's the best solution. If mutation is possible, `get_children` should be iterated instead. `get_child` iteration is the slowest option, and not very safe either.

Comment (bruvzg) [reply scene/main/canvas_item.cpp]: Adding/removing children are limited to main thread. And this is called from setters with `ERR_MAIN_THREAD_GUARD`. So it should be safe.
