### PR TITLE
Fix gamepad triggers not working on web exports

### LINKED ISSUE #81758: Joypad analog triggers do not work on web export (Xbox One controller)
### Godot version

4.1.1

### System information

Windows 10 version 22H2, Google Chrome 116.0.5845.188

### Issue description

Similar to #45535, the L and R triggers don't register any input on **web exported builds only**. Meanwhile they work fine on https://hardwaretester.com/gamepad, and also in non-web builds.
Tested with the above configuration and a Xbox One model 1708 gamepad.

### Steps to reproduce

see below

### Minimal reproduction project

```gdscript
func _input(event):
	print(event.as_text())
```

Simply run and see that there is no output in the web console when pressing the triggers. You can also use the [gamepad demo](https://github.com/godotengine/godot-demo-projects/tree/master/misc/joypads), if you can find a version that works on 4.1

### PR DESCRIPTION
**Pull request by noidexe**
Fixes #81758

DisplayServerWeb::process_joypads handles buttons 6 and 7 of the HTML5 Standard Gamepad as a special case by doing: `input->joy_axis(idx, (JoyAxis)b, s_btns[b]);`

This doesn't work because there is no JoyAxis 6 or 7 in the enum

To fix this we use JoyAxis::TRIGGER_LEFT and TRIGGER_RIGHT for button 6 and 7

However since we are now lying to input->joy_axis we also need to lie in the mappings for the standard gamepad in godotcontrollersdb.txt, otherwise input->joy_axis will try to find a mapping to axis 4(LT) and axis 5(RT) that's not defined.

Therefore we set lefttrigger to +a4 and righttrigger to +a5 in the mapping, to match what we are actually sending.

A cleaner, and more involved fix to this would be modifying input->joy_button so that it can handle analog buttons and map them to axes preserving their value instead of converting to boolean

### CODE REVIEW

File: platform/web/display_server_web.cpp [hunk 1]
```diff
@@ -902,8 +902,10 @@ void DisplayServerWeb::process_joypads() {
 		for (int b = 0; b < s_btns_num; b++) {
 			// Buttons 6 and 7 in the standard mapping need to be
 			// axis to be handled as JoyAxis::TRIGGER by Godot.
-			if (s_standard && (b == 6 || b == 7)) {
-				input->joy_axis(idx, (JoyAxis)b, s_btns[b]);
+			if (s_standard && (b == 6)) {
+				input->joy_axis(idx, JoyAxis::TRIGGER_LEFT, s_btns[b]);
+			} else if (s_standard && (b == 7)) {
+				input->joy_axis(idx, JoyAxis::TRIGGER_RIGHT, s_btns[b]);
```
Comment (akien-mga) [inline platform/web/display_server_web.cpp:908]: Doesn't the change to `godotcontrollerdb.txt` make this unused?
It should not get `b6` and `b7` anymore.

Comment (noidexe) [reply platform/web/display_server_web.cpp:908]: It's the other way around. Lefttrigger:+a4 means that when we receive +a4 from the browser we map it to lefttrigger in godot.
But the browser will never send that, it sends b6. That's why we need to convert it.

The "proper" solution is not lying in de controllerdb, not converting any buttons to axes, and modifying input->joy_button so that it can properly handle analog buttons. 

I'll give it a try later.

Comment (noidexe) [reply platform/web/display_server_web.cpp:908]: Ok reading the code a bit more, the proper fix basically means implementing analog button support in Godot

The following need to be changed:

`Input::joy_button` Needs to take a float p_value instead of a bool p_pressed, plus implementation changes
`Input::Joypad` last_buttons[] needs to be array of floats instead of bools
`Input::JoyEvent Input::_get_mapped_button_event` needs to handle converting analog buttons to full and half axes
`Input::_button_event` needs to use set_pressure() instead of only set_pressed()
At least `InputEventJoypadButton` seems to actually support analog values through it's `pressure` property for some reason. 

I think it's too big a change for a quirk of the html gamepad api and it'll probably break something else, so I'd just keep this PR as is, which essentially does what the original code meant to do.

**Review by Faless — APPROVED** [review]
Thank you for looking into this!

I believe the fix is correct, and I've tested it successfully with Chrome on Linux.

Other mapping are not affected since the changes only apply to gamepads with a "standard" mapping (according to the W3C spec).

One thing to note, is that almost all my controllers had an incorrect "standard" mapping reported by Firefox on Linux. This seems to be a Firefox issues, since after [testing here](https://hardwaretester.com/gamepad) the mapping is indeed reported as "standard" while not being standard-complaint (bindings are all over the place).

We might want to report that to upstream Firefox but there are quite a few reports already: https://bugzilla.mozilla.org/buglist.cgi?quicksearch=gamepad .

**Comment by akien-mga** [comment]
Thanks!

**Comment by michaelgundlach** [comment]
If I am only going to ship my game to web, is there a workaround I can use in 4.3 to read trigger axes?

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.
