### PR TITLE
Reorganize Region Rect Editor

### LINKED ISSUE #28341: Confusing to get out of TextureRegion editor
**Godot version:**

3.1

**OS/device including version:**

Ubuntu 14

**Issue description:**

I was creating a theme. I added the panel container class, added a stylebox, added a texture to the style box, then I couldn't figure out how to get out of the TextureReigon editor back into the Style editor. I eventually figured out you had to minimize the panelcontainer in the inspector, and reload the theme to get the style editor back.

### LINKED ISSUE #29873: "Theme" > "Button" > "Styles" > "StyleBoxTexture" won't unfold edit pane
**Godot version:**
3.1 stable.official

**OS/device including version:**
Windows 10 Home 

**Issue description:**
I added a  Theme for a popup dialog in a game i was making which also included buttons. When trying to add Button Styles for the theme i choose to go for "StyleBoxTexture". I found out that this is bugged. When clicking on to edit the Texture the whole Theme tab folds.

**Steps to reproduce:**
Use a Node which can have a Theme (Popup in my case)
Theme > Button > Styles > choose one of the states below e.g. "Disabled" >
From the dropdown choose "New StyleBoxTexture"
Click on the "StyleBoxTexture" 

Expected: should open a dropdown like when clicking on "Theme" or "Font"

Actually behaviour: closes the whole "Theme" tab

### LINKED ISSUE #47514: Unable to edit theme StyleBoxTexture
**Godot version:**

3.2.3, 3.3rc7

**OS/device including version:**

Linux

**Issue description:**

Can't edit StyleBoxTexture after I add the theme to a control.

https://user-images.githubusercontent.com/16458555/113092948-6eb9dc00-9208-11eb-93d8-86e772c684b9.mp4

If I open the theme separately from a control (for example double clicking on the theme file in filesystem), this weird behavior doesn't happens.

**Steps to reproduce:**
1. Create a control (I created `HSlider`)
2. Add a theme on it
3. Add a `StyleBoxTexture` to an item (for example for HSlider it's `slider`, `grabber area`, `grabber area highlight`)
4. click on it to edit StyleBoxTexture parameters
you will see the behavior shown in the video (above)

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by reduz**
**Problem**:

* Region Rect was pretty much a mythical editor. Because it was annoying for it to pop up automatically, it was hidden by default.
* Because it was hidden by default, most users have no idea it even exists.
* But because it is a transient editor, it would steal focus of other editors and annoy users unexpectedly.
* This editor only edits a sole property of objects (*region_rect*) and there is a general disconnect to it, so users have it very difficult to make the mental link of what is being edited exactly.

In general, Region Rect editor is a very weird editor, because it only edits the single *region_rect* property of objects that read a texture from a region, no other editor works quite like it.

**Solution**:

Because of the strange nature of this editor, a dedicated solution was implemented:

* As its only useful to edit a very specific property in objects, the way to access it is now from that property via a button.
* Editor has been moved to a window.
* Regions that can be edited  now display a "Edit Region" button (below the region property). Pressing it brings up the Region Rect editor.

This required a slight change in EditorInspectorPlugin to allow custom editors to be below others.

### How it looks in action:

Regions now have a button you can press to edit them:
image
This opens the region editor in context, only when you need it:
image

### What it fixes:

Fixes #28341
Fixes #47514
Fixes #29873 

And probably many others.

### CODE REVIEW

**Comment by KoBeWi** [comment]
The editor should automatically center the texture whenever opened. Right now it opens in top-left corner for the first time.

The window is super big, you don't have live preview when editing the region (unless you have a second screen). It should be probably smaller.

Also it might be helpful to display some faint borders to denote texture's size.

**Comment by reduz** [comment]
@KoBeWi makes sense. I did not modify the editor itself though, just put it in a window. I think improvements to the editor could happen on a separate PR.

**Review by groud — APPROVED** [review]
Looks good overall. The `add_to_end` argument added to `add_property_editor` is welcome.

**Comment by Sslaxx** [comment]
Instead of the small button on the left, make the entire "Edit Region" thing a button?

**Comment by groud** [comment]
> Instead of the small button on the left, make the entire "Edit Region" thing a button? And perhaps rename it "Region Editor" to be consistent?

I think it is already the case. The icon is just ragged left. 
For the name I prefer "Edit region", as it clearer it's an action (opening the editor) IMO.

**Comment by KoBeWi** [comment]
> I did not modify the editor itself though, just put it in a window.

That's not good, because any shortcoming of that switch is now a usability regression. The editor moved from a small panel to a huge window, so you get this:
image
Your texture is now crammed in a corner and the first thing you see after opening the editor is huge empty space, which covers your whole editor, so you can't even preview the region changes on the scene. It's not that bad, because you can just adjust the window, but you also removed editor state for some reason, so it will be reset to obtrusive window every time you restart Godot.

File: editor/plugins/texture_region_editor_plugin.cpp [hunk 1]
```diff
@@ -1119,88 +1124,40 @@ TextureRegionEditor::TextureRegionEditor() {
...
-		region_editor->sb_sep_y->set_value(sep.y);
-		region_editor->snap_separation = sep;
-	}
-
-	if (state.has("snap_mode")) {
-		region_editor->_set_snap_mode(state["snap_mode"]);
-		region_editor->snap_mode_button->select(state["snap_mode"]);
+bool EditorInspectorPluginTextureRegion::parse_property(Object *p_object, const Variant::Type p_type, const String &p_path, const PropertyHint p_hint, const String &p_hint_text, const uint32_t p_usage, const bool p_wide) {
+	if ((p_type == Variant::RECT2 || p_type == Variant::RECT2I)) {
+		if (((Object::cast_to<Sprite2D>(p_object) || Object::cast_to<Sprite3D>(p_object) || Object::cast_to<NinePatchRect>(p_object) || Object::cast_to<StyleBoxTexture>(p_object)) && p_path == "region_rect") || (Object::cast_to<AtlasTexture>(p_object) && p_path == "region")) {
```
Comment (KoBeWi) [inline editor/plugins/texture_region_editor_plugin.cpp:1143]: Checking property of `StyleBoxTexture` is not necessary, as `region_rect` is the only Rect2 property in there.

**Comment by groud** [comment]
> That's not good, because any shortcoming of that switch is now a usability regression. The editor moved from a small panel to a huge window, so you get this:

This is a little bit exaggerated. On your screen the new window is maybe twice the height of what would be the bottom panel, so it does not go from small to huge, but from already too big to huge. So I would not call that a regression.

I think a simple fix would be to popup with a smaller size for now (like 50% of the editor window instead of the default value, or even automatically computed according to the texture size), but I agree the texture should be centered if possible too.

**Comment by KoBeWi** [comment]
> This is a little bit exaggerated. On your screen the new window is maybe twice the height of what would be the bottom panel, so it does not go from small to huge, but from already too big to huge. So I would not call that a regression.

Yeah but the window appears over the 2D editor and covers the whole viewport. Panel didn't have this problem.

> I think a simple fix would be to popup with a smaller size for now

That's what I suggested in my first comment, but then this got merged :v

**Comment by groud** [comment]
> That's what I suggested in my first comment, but then this got merged :v

Oh my bad, I though the commit pushed by reduz after your comment addressed your feedback. :/
I should have checked before approving.

**Comment by reduz** [comment]
@KoBeWi I can do some fixes later if you wish later (or you can PR them to use a smaller window ratio). But I needed to merge this to work on the shader editor.

**Comment by KoBeWi** [comment]
Is something like this better?
image
The problem is that a non-flat button doesn't have borders, but just slightly lighter background. Maybe we could add some theme override here?

**Comment by reduz** [comment]
@KoBeWi I suppose its better, but you should check other buttons, like Add Metadata and the ones for array management so we use something unified.
