### PR TITLE
Fix: String::format Variant to String conversion

### LINKED ISSUE #23129: str.format() function adds escape characters when interpolating a string containing the double quote character.
**Godot version:**

3.0.6, 3.1-alpha1, 4c1a5d9

**OS/device including version:**
linux, 1070 nvidia driver

**Issue description:**
When using the [String.format()](http://docs.godotengine.org/en/latest/classes/class_string.html#class-string-format) function, any double quote character `"` in an interpolated string becomes prefixed with `\`

**Steps to reproduce:**

`print('{0}: {1}'.format([1, 'something "with" quotes']))`
`something \"with\" quotes`
```
    print("{0}, {1}".format([1, 'Something "with" quotes']))
    print("{0}, {1}".format([2, "Something 'with' quotes"]))
    print("{0}, {1}".format([3, "Something \'with\' quotes"]))
    print("{0}, {1}".format([4, 'Something \"with\" quotes']))
    print("{0}, {1}".format([5, "Something \"with\" quotes"]))
    print("{0}, {1}".format([6, 'Something \'with\' quotes']))
```
```
1, Something \"with\" quotes
2, Something 'with' quotes
3, Something 'with' quotes
4, Something \"with\" quotes
5, Something \"with\" quotes
6, Something 'with' quotes
```

### PR DESCRIPTION
**Pull request by DavidSichma**
Previosly String::format used variant.get_construct_string() to convert the passed Variants to Strings. This however did not match the expected printing behavior of some datatypes: Strings for example turned out escaped.

This fix replaces the call to get_construct_string() with a simple conversion. This makes String::format consistent with "%s" % "sth" and formated Variants turn out like printed as expected.

Closes #23129

### CODE REVIEW

File: core/ustring.cpp [hunk 1]
```diff
@@ -2776,14 +2776,14 @@ String String::format(const Variant &values, String placeholder) const {
 					Variant v_key = value_arr[0];
 					String key;
 
-					key = v_key.get_construct_string();
+					key = v_key;
```
Comment (akien-mga) [inline core/ustring.cpp]: Do you know if there's a specific reason to do this in two statements instead of just `String key = v_key;`?

Comment (DavidSichma) [reply core/ustring.cpp]: I don't think there is one. I just left it the way it was.
Might combine the lines as well.

**Comment by akien-mga** [comment]
Thanks!
