### PR TITLE
Fix snapping when zoomed in `Polygon2D` UV editor

### LINKED ISSUE #94385: Incorrect grid snapping when zoomed in `Polygon2D` UV editor
### Tested versions

v4.3.beta3.official [82cedc83c]

### System information

w10 64

### Issue description

works fine in 3.6 rc1

Anchoring to the grid is done in a strange way.
The grid has a pixel configuration.
Points are not anchored to the corners of a pixel but to another point.
I expected the points to match the pixels or the grid.
This anchoring is strange, I thought it could be a bug.

https://youtu.be/HSkJrn7MDzA

On 3.6 rc1

https://github.com/user-attachments/assets/42259b13-124a-4c96-bda7-a9612684910e

### Steps to reproduce

see the video

### Minimal reproduction project (MRP)

...

### PR DESCRIPTION
**Pull request by kleonc**
After reading the code I concluded that `uv_draw_ofs` is not affected by the `uv_draw_zoom`, hence should be multpliplied by it as well when snapping.
Also simplified some code when reading.

Fixes #94385.

Before<br>(v4.3.rc2.official [3978628c6])|After<br>(this PR)
-|-
Xllk5eJ1fi|TxAtJxtFT2

### CODE REVIEW

File: editor/plugins/polygon_2d_editor_plugin.cpp [hunk 1]
```diff
@@ -851,7 +851,7 @@ void Polygon2DEditor::_uv_input(const Ref<InputEvent> &p_input) {
 		if (uv_drag) {
 			Vector2 uv_drag_to = mm->get_position();
 			uv_drag_to = snap_point(uv_drag_to); // FIXME: Only works correctly with 'UV_MODE_EDIT_POINT', it's imprecise with the rest.
```
Comment (KoBeWi) [inline editor/plugins/polygon_2d_editor_plugin.cpp:853]: Is the FIXME resolved now?

**Review by KoBeWi — APPROVED** [review]

File: editor/plugins/polygon_2d_editor_plugin.cpp (hunk 1 above)
Comment (akien-mga) [reply editor/plugins/polygon_2d_editor_plugin.cpp:853]: Ping @kleonc

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.
