### PR TITLE
Fix `AudioStreamWAV::save_to_wav` adding extra '.wav' to file if existing ext is not lower case

### LINKED ISSUE #98719: AudioStreamWAV::save_to_wav adding extra '.wav' to file if existing ext is not lower case
### Tested versions

Tested on current master @ dbad9c60fbc294057172a112e5d8a39d31c210d5
Affects all versions back to 1.0.

### System information

macOS 14.5.0, M2 Pro, Vulkan

### Issue description

AudioStreamWAV::save_to_wav adds an extra '.wav' to file if existing ext is not lower case. This is because it only does a string literal comparison to the lower-case '.wav' without normalizing the existing extension.

### Steps to reproduce

run save_to_wav() with an uppercase .WAV path (e.g. "sound.WAV")
Observe that adds an extra '.wav' to the output file (e.g. "sound.WAV.wav")

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by nikitalita**
Fixes #98719

Pretty simple: if the file_path passed in contains an upper-case extension (e.g. ".WAV"), it would add an extra ".wav" on top of that. A simple `.to_lower()` fixes this.

### CODE REVIEW

**Review by fire — APPROVED** [review]

**Review by mhilbrunner — APPROVED** [review]

File: scene/resources/audio_stream_wav.cpp [hunk 1]
```diff
@@ -624,7 +624,7 @@ Error AudioStreamWAV::save_to_wav(const String &p_path) {
 	}
 
 	String file_path = p_path;
-	if (!(file_path.substr(file_path.length() - 4, 4) == ".wav")) {
+	if (!(file_path.substr(file_path.length() - 4, 4).to_lower() == ".wav")) {
```
Comment (AThousandShips) [inline scene/resources/audio_stream_wav.cpp:627]:
```suggestion
	if (file_path.substr(file_path.length() - 4, 4).to_lower() != ".wav") {
```
Worth cleaning this up while we're here, more readable

**Review by AThousandShips — APPROVED** [review]

**Review by ShadowNotDefined — APPROVED** [review]

File: scene/resources/audio_stream_wav.cpp (hunk 1 above)
Comment (mhilbrunner) [reply scene/resources/audio_stream_wav.cpp]: Great catch, thats indeed more readable :)

**Review by adamscott — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
