### PR TITLE
Fix typed arrays not working with concatenation operator `+`

### LINKED ISSUE #72948: Typed arrays aren't working with +=
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Lubuntu

### Issue description

You can't use + or += to mutate typed arrays.

It seems to be not correctly getting the type information from the second operand.

The error you see is:
```Trying to assign an array of type "Array" to a variable of type "Array[int]".```

### Steps to reproduce

```
	var Alice: Array[int] = [1,2,3]
	var Bob: Array[int] = [4,5,6]
	Alice += Bob
```

### Minimal reproduction project

[plus_syntax_broken_demo_project.zip](https://github.com/godotengine/godot/files/10694514/plus_syntax_broken_demo_project.zip)

### PR DESCRIPTION
**Pull request by mashumafi**
This fixes https://github.com/godotengine/godot/issues/72948 allowing concatenation of typed arrays and maintaining the type information. Includes a test case as well.

*Bugsquad edit:*
- Fixes #72948
- Fixes #72590

### CODE REVIEW

**Comment by mashumafi** [comment]
This should also fix https://github.com/godotengine/godot/issues/72590

**Comment by dalexeev** [comment]
How does it work with this?

```gdscript
var a: Array[int] = [1, 2, 3]
var b: Array[String] = ["one", "two", "three"]
print(a + b)
```

I think the sum type should be the narrowest type, including type a and type b, and not just the type of the first array? Or maybe it should cause an error?

**Comment by mashumafi** [comment]
> How does it work with this?
> 
> ```gdscript
> var a: Array[int] = [1, 2, 3]
> var b: Array[String] = ["one", "two", "three"]
> print(a + b)
> ```
> 
> I think the sum type should be the narrowest type, including type a and type b, and not just the type of the first array? Or maybe it should cause an error?

This would likely result in an error currently. It wouldn't reach the concatenating portion of the code.
I think once `_add_arrays` is reached the types of both arrays were already determined to be identical. Perhaps adding some `CHECK` code to make that more clear but it does seem like the expectation. Open to ideas though. 

In the example the narrowest type would be `Varant`? It might be worth it to be able to write code like:
```gdscript
var node2ds : Array[Node2D] = [ ... ]
var node3ds : Array[Node3D] = [ ... ]
var nodes : Array[Node] = node2ds + node3ds
```

**Comment by mashumafi** [comment]
Thinking about it more, perhaps adding the additional feature pushes this into 4.x territory. I think just focusing on this bug fix for now and open a separate issue for the narrowest type for a potential 4.x release.

**Comment by mashumafi** [comment]
I took another look after understanding @dalexeev concern. Now the implementation is a bit more involved but covers more use-cases. Hopefully it's still in scope of 4.0. I feel pretty confident with because the tests pretty much cover all the functionality of mixing 2 types together. Feedback is appreciated!

**Comment by akien-mga** [comment]
CC @vonagam

**Comment by akien-mga** [comment]
> I feel pretty confident with because the tests pretty much cover all the functionality of mixing 2 types together

I don't see explicit tests for untyped arrays (though maybe some existing tests cover it)? That's my main concern with this change, fixing the obviously broken behavior for typed arrays makes sense but we shouldn't take any risk with untyped arrays at this late stage.

**Comment by vonagam** [comment]
This one is problematic one.

I can approve of `Array[T] + Array[T] = Array[T]` but any other mixing should result in untyped array:
```gdscript
var nodes: Array[Node] = node2ds + node3ds # will work
var objects: Array[Object] = node2ds + node3ds # will fail
```

Trying to guess typed array element type will complicate and slow down things.

So in my opinion, there should no new `mix` method, addition to `_add_arrays` can be simple:
```cpp
if (array_a.is_typed() && array_a.is_same_typed(array_b)) {
  sum.set_typed(array_a.get_typed_builtin(), array_a.get_typed_class_name(), array_a.get_typed_script());
}
```

And ideally in analyzer [there](https://github.com/godotengine/godot/blob/6f64349bfe42b795a6c50e9c2093d38e7a992e7a/modules/gdscript/gdscript_analyzer.cpp#L2602) should be added handling of case with `Array[T] + Array[T]` so that the result is typed as `Array[T]` and not as an untyped one.

**Comment by YuriSizov** [comment]
> This one is problematic one.

Okay, then let's give it a bit more time to develop and give you guys a bit more time to discuss it. We can cherry-pick the final solution into 4.0.x if it's safe enough.

**Comment by mashumafi** [comment]
Adjusted the PR. Removed the mixing behavior, keeping it simple and simply adding types if both arrays match. Enhanced the analyzer code as well to return the proper type, works similar to the `_add_arrays` function, and now the editor shows the lines as "safe".

image

**Comment by vonagam** [comment]
Superb. 

The other place worth updating is [`type_from_variant`](https://github.com/godotengine/godot/blob/9c960a8c2494eb826a557a7ffc96dd4547f9d31e/modules/gdscript/gdscript_analyzer.cpp#L4407) this will be used when two constant arrays combined together to get a datatype for typing. Right now it will be resolved to an untyped array.

One thing that you may stumble upon in tests - do not use empty constant typed arrays, there is an unresolved issue with how constants are stored.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -4740,6 +4740,12 @@ GDScriptParser::DataType GDScriptAnalyzer::get_operation_type(Variant::Operator
 			b_type = Variant::INT;
 		}
 	}
+	if (p_operation == Variant::OP_ADD && a_type == Variant::ARRAY && b_type == Variant::ARRAY) {
+		if (p_a.get_container_element_type() == p_a.get_container_element_type()) {
+			r_valid = true;
+			return p_a;
```
Comment (vonagam) [inline modules/gdscript/gdscript_analyzer.cpp:4746]: Small thing, `type_source` is an important part, let's say that `p_a` is a hard annotated type while `p_b` is a weak inferred one. Result should be a weak one.

So makes sense to move next lines of `bool hard_operation = p_a.is_hard_type() && p_b.is_hard_type();` and `GDScriptParser::DataType result;` before this if condition and have this inside condition:
```cpp
result = p_a;
result.type_source = hard_operation ? GDScriptParser::DataType::ANNOTATED_INFERRED : GDScriptParser::DataType::INFERRED;
```

**Comment by mashumafi** [comment]
Updated with `hard_operation` and now concatenating `const` arrays results in green-lines

image

File: modules/gdscript/gdscript_analyzer.cpp [hunk 2]
```diff
@@ -4306,7 +4306,12 @@ GDScriptParser::DataType GDScriptAnalyzer::type_from_variant(const Variant &p_va
 	result.builtin_type = p_value.get_type();
 	result.type_source = GDScriptParser::DataType::ANNOTATED_EXPLICIT; // Constant has explicit type.
 
-	if (p_value.get_type() == Variant::OBJECT) {
+	if (p_value.get_type() == Variant::ARRAY && p_source->type == GDScriptParser::Node::BINARY_OPERATOR) {
```
Comment (vonagam) [inline modules/gdscript/gdscript_analyzer.cpp:4309]: Ideally `p_source` should not matter, it is for debugging purposes (warnings and errors).

To get an element type combo of `type_from_metatype` and relevant `make_builtin_meta_type`/`make_native_meta_type`/`make_script_meta_type` can be used.

Comment (mashumafi) [reply modules/gdscript/gdscript_analyzer.cpp]: Thanks for the help, it looks much cleaner now!

Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp]: `type_from_metatype` calls on args for `set_container_element_type` are missing.

Comment (mashumafi) [reply modules/gdscript/gdscript_analyzer.cpp]: Oops, missed that, it's there now!

**Review by vonagam — APPROVED** [review]

**Comment by vonagam** [comment]
All good now.

**Comment by dalexeev** [comment]
Looks good, except that the test does not match the code style (extra parentheses and spaces).

**Comment by mashumafi** [comment]
> Looks good, except that the test does not match the code style (extra parentheses and spaces).

I took a look at some other tests and update mine to be closer in consistency :)

File: core/variant/variant_op.h [hunk 3]
```diff
@@ -824,6 +824,11 @@ class OperatorEvaluatorAddArray {
 	_FORCE_INLINE_ static void _add_arrays(Array &sum, const Array &array_a, const Array &array_b) {
 		int asize = array_a.size();
 		int bsize = array_b.size();
+
+		if (array_a.is_typed() && array_a.is_same_typed(array_b)) {
```
Comment (aw-square) [inline core/variant/variant_op.h:828]: Do we need to check `array_b.is_typed()`?
Apologies for the drive by comment... :^) Testing a github action PR review bot and was using your PR as an example.

Comment (mashumafi) [reply core/variant/variant_op.h:828]: Technically I don't even think `array_a.is_typed()` needs to be checked. `is_same_typed` might just be enough because if they are both untyped then `set_typed` pretty much acts like a no-op. I guess it can be a bit expensive to call `set_typed` just to set no type though so it helps optimize that use-case.

To answer your question, checking if `array_b.is_typed()` would be redundant. If `array_a.is_typed()` and `array_a.is_same_typed(array_b)` then it can be safe to assume `array_b.is_typed()`.

**Review by adamscott — APPROVED** [review]
As @vonagam and @dalexeev gave their thumbs up, I shall too.
Thanks @mashumafi! Sorry for the delay, by the way.

**Comment by adamscott** [comment]
@akien-mga @YuriSizov We should maybe wait for @vnen input as this affects core. But I think everything is alright.

**Review by vnen — APPROVED** [review]
Looks good to me.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 4]
```diff
@@ -4741,11 +4750,21 @@ GDScriptParser::DataType GDScriptAnalyzer::get_operation_type(Variant::Operator
 		}
 	}
 
-	Variant::ValidatedOperatorEvaluator op_eval = Variant::get_validated_operator_evaluator(p_operation, a_type, b_type);
+	GDScriptParser::DataType result;
 	bool hard_operation = p_a.is_hard_type() && p_b.is_hard_type();
+
+	if (p_operation == Variant::OP_ADD && a_type == Variant::ARRAY && b_type == Variant::ARRAY) {
+		if (p_a.get_container_element_type() == p_a.get_container_element_type()) {
```
[the remark this answers is not in the document]
Comment (YuriSizov) [reply modules/gdscript/gdscript_analyzer.cpp:4757]: Also it compares the value with itself...

[the remark this answers is not in the document]
Comment (YuriSizov) [reply modules/gdscript/gdscript_analyzer.cpp:4757]: See https://github.com/godotengine/godot/pull/78478
