### PR TITLE
Keep focus on floating window when showing ProgressDialog

### LINKED ISSUE #78672: Saving script from floating script window moves window focus back to the main editor window
### Godot version

master (3710f06929)

### System information

Godot v4.1.beta (3710f0692) - Arch Linux #1 ZEN SMP PREEMPT_DYNAMIC Sat, 10 Jun 2023 00:35:19 +0000 - Vulkan (Forward+) - dedicated AMD Radeon R9 380 Series (RADV TONGA) () - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

Using i3wm, tiling window manager.

If I'm in the floating script window and I hit Ctrl+S to save, the window focus gets switched to the main Godot window.

I'd expect it to stay on the script window instead.

Note: this happens only when the script is associated with a scene. A standalone script does not trigger the focus switch.

### Steps to reproduce

Float script window, use ctrl+s to save, see focus returned to main godot editor window.

Following screencap of this exact sequence. I switch focus to the script window, type "pass" and press ctrl+s. and you can see the blue square around the windows showing current focus move back to the main window.

https://github.com/godotengine/godot/assets/1187609/8638d269-3f82-4f75-b559-f6ed8d148d65

### Minimal reproduction project

You only need a scene with a script attached.

### PR DESCRIPTION
**Pull request by trollodel**
Fixes #78672 

This uses the first approach described in https://github.com/godotengine/godot/issues/78672#issuecomment-1646848253

I tested this only on Linux (KDE neon 5.27 22.04 - X11 - Vulkan (Forward+) - dedicated AMD Radeon Graphics (RADV NAVI23) - AMD Ryzen 5 5600 6-Core Processor (12 Threads)). 
Other OSes should be tested as well, just in case any of them doesn't like quick focus changes.

<hr>

I have done this patch  ~2 months ago, but I never get to publish it 🙈. 
Initially, I want to base this PR to #79261, but it's not merged.

### CODE REVIEW

File: editor/progress_dialog.cpp [hunk 1]
```diff
@@ -147,6 +147,12 @@ void ProgressDialog::_popup() {
 	main->set_offset(SIDE_BOTTOM, -style->get_margin(SIDE_BOTTOM));
 
 	if (!is_inside_tree()) {
+		for (Window *window : host_windows) {
+			if (window->has_focus()) {
+				popup_exclusive_centered(window, ms);
```
Comment (Maran23) [inline editor/progress_dialog.cpp:152]: shouldn't this return after `popup_exclusive_centered` was called?

Comment (trollodel) [reply editor/progress_dialog.cpp:152]: Correct, even if it seems to work without.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
> Initially, I want to base this PR to https://github.com/godotengine/godot/pull/79261, but it's not merged.

How different would this PR be with #79261? That PR was moved to 4.3 due to feature freeze, but if it helps simplify a bugfix, it could still be merged now.

**Comment by KoBeWi** [comment]
That PR would allow to get rid of the whole `host_windows` vector, so it would simplify the code a lot.

Though the current code is only limited to the wrapped windows, so we won't get popups or transient windows unexpectedly getting progress dialog. This is a safer approach, not sure if it matters.

**Comment by Sauermann** [comment]
> How different would this PR be with #79261? That PR was moved to 4.3 due to feature freeze, but if it helps simplify a bugfix, it could still be merged now.

I would recommend to not consider #79261 for 4.2, because it changes things, that would benefit from testing.

**Comment by KoBeWi** [comment]
btw the linked issue is already "fixed" so this PR can be postponed too probably.

**Review by YuriSizov — APPROVED** [review]
The code looks fine to me, although I think this should be a part of the popup behavior in the editor, not a part of `ProgressDialog` specifically. But we can look into it later.

**Review by akien-mga — APPROVED** [review]
I tested it on Linux X11 (KDE) a few days ago, worked fine for me.

**Comment by akien-mga** [comment]
Thanks!
