### PR TITLE
Fix cyclic reference base being loaded but not valid (which is ok)

### LINKED ISSUE #69213: Parser Error: When trying to run (F5) a project
### Godot version

4.0 Beta 6

### System information

Windows 11

### Issue description

When trying to run my project with F5 it halts with Parse Error:
The only information shown is in the console as follows. 

> E 0:00:02:0469   GDScriptCompiler::_populate_class_members: Condition "!base->is_valid()" is true. Returning: ERR_BUG
  <C++ Source>   modules\gdscript\gdscript_compiler.cpp:2287 @ GDScriptCompiler::_populate_class_members()

My project is fairly large and runs fine in Beta 5.

in case it helps heres the log when loading up the project:

> Godot Engine v4.0.beta6.official.7f8ecffa5 - https://godotengine.org
OpenGL Renderer: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2
Editing project: C:/SpaceSlog Game/SpaceSlog
Godot Engine v4.0.beta6.official.7f8ecffa5 - https://godotengine.org
Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080 Ti
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Condition "!base->is_valid()" is true. Returning: ERR_BUG
   at: _populate_class_members (modules/gdscript/gdscript_compiler.cpp:2287)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Condition "!base->is_valid()" is true. Returning: ERR_BUG
   at: _populate_class_members (modules/gdscript/gdscript_compiler.cpp:2287)
ERROR: Condition "!base->is_valid()" is true. Returning: ERR_BUG
   at: _populate_class_members (modules/gdscript/gdscript_compiler.cpp:2287)
ERROR: Condition "!base->is_valid()" is true. Returning: ERR_BUG
   at: _populate_class_members (modules/gdscript/gdscript_compiler.cpp:2287)
ERROR: Condition "!base->is_valid()" is true. Returning: ERR_BUG
   at: _populate_class_members (modules/gdscript/gdscript_compiler.cpp:2287)
ERROR: Condition "!base->is_valid()" is true. Returning: ERR_BUG
   at: _populate_class_members (modules/gdscript/gdscript_compiler.cpp:2287)
ERROR: Condition "!preset.is_valid()" is true. Continuing.
   at: load_config (editor/export/editor_export.cpp:206)
ERROR: Condition "!d.has("handle_modes")" is true. Returning: false
   at: _set (scene/resources/animation.cpp:319)

### Steps to reproduce

Unfortunately i cannot help much as my project is fairly large. I have tried to narrow the issue down but cannot.  Any help with this would be appreciated.

### Minimal reproduction project

Please see above.

### PR DESCRIPTION
**Pull request by adamscott**
In some cases, a script from `GDScriptCache::get_full_script()` can be not null, but invalid. In the context of cyclic references and while populating class members (`GDScriptCompiler::_populate_class_members()`), the test was too strict and was issuing an error even if the script itself is usable.

This was breaking seemingly valid code that was working in previous betas.

Making the tests more lax seems to be the right thing to do.

Fixes #69213

### CODE REVIEW

**Comment by adamscott** [comment]
@rune-scape I'm informally asking you to review my PR.

File: modules/gdscript/gdscript_compiler.cpp [hunk 1]
```diff
@@ -2277,14 +2277,13 @@ Error GDScriptCompiler::_populate_class_members(GDScript *p_script, const GDScri
 					_set_error(vformat(R"(Could not compile base class "%s" from "%s": %s)", base->fully_qualified_name, base->path, error_names[err]), nullptr);
 					return err;
 				}
-				if (base_root.is_valid()) {
+				if (!base_root.is_null()) {
```
Comment (kleonc) [inline modules/gdscript/gdscript_compiler.cpp:2280]: This changes nothing, before/after are equivalent.
https://github.com/godotengine/godot/blob/860884bde7d895887236306887d01381f747bcd7/core/object/ref_counted.h#L212-L213
And I think `is_valid()` is preferred in here, that's kinda why this method exists (to avoid having negated `is_null()` checks).

File: modules/gdscript/gdscript_compiler.cpp [hunk 2]
```diff
@@ -2277,14 +2277,13 @@ Error GDScriptCompiler::_populate_class_members(GDScript *p_script, const GDScri
...
 					base = Ref<GDScript>(base_root->find_class(base->fully_qualified_name));
 				}
 				if (base.is_null()) {
 					_set_error(vformat(R"(Could not find class "%s" in "%s".)", base->fully_qualified_name, base->path), nullptr);
 					return ERR_COMPILATION_FAILED;
 				}
-				ERR_FAIL_COND_V(!base->is_valid(), ERR_BUG);
```
Comment (rune-scape) [inline modules/gdscript/gdscript_compiler.cpp:2287]: this shouldn't be removed, if the base isn't valid here, theres something wrong elsewhere,
either `get_full_script()` should have given an error, or the inner class is not valid for some reason
the code i replaced didn't allow this

**Review by rune-scape — COMMENTED** [review]
seems to me like 2 of the changes wouldn't have any effect, im confused

File: modules/gdscript/gdscript_compiler.cpp (hunk 1 above)
Comment (adamscott) [reply modules/gdscript/gdscript_compiler.cpp:2280]: You're right for `Ref<T>` instances, except for `GDScript`.
> https://github.com/godotengine/godot/blob/860884bde7d895887236306887d01381f747bcd7/modules/gdscript/gdscript.h#L185

File: modules/gdscript/gdscript_compiler.cpp (hunk 2 above)
Comment (adamscott) [reply modules/gdscript/gdscript_compiler.cpp:2287]: In the case of the MRP of #69213, `base` is reloading. While reloading, the script `valid` value is set to false, as shown:

https://github.com/godotengine/godot/blob/860884bde7d895887236306887d01381f747bcd7/modules/gdscript/gdscript.cpp#L850-L860

So, as replied to @kleonc, in `gdscript.h`, `GDScript::is_valid()` returns a different value than being the inverse of `GDScript::is_null()`. An invalid script just means that it's reloading. We could change the behaviour, but checking if the script is valid, at this stage, just creates bug, it doesn't prevent ones.

https://github.com/godotengine/godot/blob/860884bde7d895887236306887d01381f747bcd7/modules/gdscript/gdscript.h#L185

Maybe we could add a check to `is_valid()` that it must be `GDScript::reloading == true` too. Otherwise, it's a bug.

File: modules/gdscript/gdscript_compiler.cpp (hunk 1 above)
Comment (rune-scape) [reply modules/gdscript/gdscript_compiler.cpp:2280]: but thats defned in `Script`, not `Ref` https://github.com/godotengine/godot/blob/860884bde7d895887236306887d01381f747bcd7/core/object/script_language.h#L144

Comment (adamscott) [reply modules/gdscript/gdscript_compiler.cpp:2280]: You're right. My bad.

File: modules/gdscript/gdscript_compiler.cpp (hunk 2 above)
Comment (adamscott) [reply modules/gdscript/gdscript_compiler.cpp:2287]: I put back the error with the added `&& !base->reloading` condition.

File: modules/gdscript/gdscript_compiler.cpp (hunk 1 above)
Comment (kleonc) [reply modules/gdscript/gdscript_compiler.cpp]: `base_root` is `Ref<GDScript>` so:
- `base_root.is_valid()` calls `Ref::is_valid`,
- `base_root->is_valid()` calls `GDScript::is_valid`.

Comment (adamscott) [reply modules/gdscript/gdscript_compiler.cpp]: > `base_root` is `Ref<GDScript>` so:
> 
>     * `base_root.is_valid()` calls `Ref::is_valid`,
> 
>     * `base_root->is_valid()` calls `GDScript::is_valid` (or its override as it's virtual).

I got mixed up. Thanks.

File: modules/gdscript/gdscript_compiler.cpp (hunk 2 above)
Comment (rune-scape) [reply modules/gdscript/gdscript_compiler.cpp:2287]: that sounds good to me 👍

File: modules/gdscript/gdscript_compiler.cpp (hunk 1 above)
Comment (rune-scape) [reply modules/gdscript/gdscript_compiler.cpp]: i don't blame you its **very** confusing

**Review by rune-scape — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

File: modules/gdscript/gdscript_compiler.cpp (hunk 1 above)
Comment (akien-mga) [reply modules/gdscript/gdscript_compiler.cpp]: Wow this is an API asking for bugs...

**Comment by akien-mga** [comment]
Thanks!

**Comment by produno** [comment]
I compiled from source to test this and i am receiving new errors. Please let me know if i should create a new issue for this, or if i should wait and test the release of Beta 6?

When i try to run my project it complains that it cannot find a property in my inherited class that resides in a base class and shows the error below.

> ERROR: Condition "!nc" is true. Returning: false
   at: GDScriptCompiler::_is_class_member_property (modules\gdscript\gdscript_compiler.cpp:63)


If i comment that out it will then crash when trying to run showing this:

>CrashHandlerException: Program crashed
Engine version: Godot Engine v4.0.beta.custom_build (166066d9f74e574b68d9f9d0ba05bf42b8de2131)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] embree::TaskScheduler::wait
[3] oidnUnmapBuffer
[4] oidnUnmapBuffer
[5] oidnUnmapBuffer
[6] oidnUnmapBuffer
[7] oidnUnmapBuffer
[8] oidnUnmapBuffer
[9] oidnUnmapBuffer
[10] oidnUnmapBuffer
[11] oidnUnmapBuffer
[12] oidnUnmapBuffer
[13] oidnUnmapBuffer
[14] oidnUnmapBuffer
[15] oidnUnmapBuffer
[16] oidnUnmapBuffer
[17] oidnUnmapBuffer
[18] oidnUnmapBuffer
[19] oidnUnmapBuffer
[20] oidnUnmapBuffer
[21] oidnUnmapBuffer
[22] oidnUnmapBuffer
[23] oidnUnmapBuffer
[24] oidnUnmapBuffer
[25] oidnUnmapBuffer
[26] oidnUnmapBuffer
[27] oidnUnmapBuffer
[28] oidnUnmapBuffer
[29] oidnUnmapBuffer
[30] oidnUnmapBuffer
[31] oidnUnmapBuffer
[32] oidnUnmapBuffer
[33] oidnUnmapBuffer
[34] oidnUnmapBuffer
[35] oidnUnmapBuffer
[36] oidnUnmapBuffer
[37] oidnUnmapBuffer
[38] oidnUnmapBuffer
[39] oidnUnmapBuffer
[40] oidnUnmapBuffer
[41] oidnUnmapBuffer
[42] oidnUnmapBuffer
[43] oidnUnmapBuffer
[44] oidnUnmapBuffer
[45] embree::TaskScheduler::wait
[46] embree::TaskScheduler::wait
[47] embree::TaskScheduler::wait
[48] <couldn't map PC to fn name>
[49] <couldn't map PC to fn name>
[50] <couldn't map PC to fn name>
[51] <couldn't map PC to fn name>
[52] embree::TaskScheduler::wait
[53] BaseThreadInitThunk
-- END OF BACKTRACE --

**Comment by adamscott** [comment]
@produno As mentioned by @akien-mga in #69295, it seems that there's some issues with libraries. Please follow this issue about your bug.

**Comment by akien-mga** [comment]
@adamscott The bug they're reporting is still valid and related to GDScript. #69295 just clarifies that the stacktrace is useless, it doesn't invalidate the fact that it's crashing :)

**Comment by produno** [comment]
Fyi, i am still getting this issue #https://github.com/godotengine/godot/pull/69259#issuecomment-1328933864

When starting the game it will show `Parser Error: Identifier not found: encloses_room` (This property is on a base class) and will show the below in the Debugger/Errors window.

>E 0:00:02:0383   _is_class_member_property: Condition "!nc" is true. Returning: false
  <C++ Source>   modules/gdscript/gdscript_compiler.cpp:63 @ _is_class_member_property()

Removing the property will cause the game to crash (not load). Beta 5 does not cause any errors and the project runs as expected.

**Comment by adamscott** [comment]
Oh, sorry, I completely forgot that issue. Fell out of the radar.
I'll take a look ASAP.

**Comment by produno** [comment]
> Oh, sorry, I completely forgot that issue. Fell out of the radar. I'll take a look ASAP.

No problem. Thanks!

**Comment by adamscott** [comment]
@produno Could you test with one of the build artifacts of #69587? Maybe my PR could help (or not!)

**Comment by produno** [comment]
> @produno Could you test with one of the build artifacts of #69587? Maybe my PR could help (or not!)

Unfortunately i have the same issue when compiling from your repository and the current master branch.
Heres the backtrace if it helps.

>CrashHandlerException: Program crashed
Engine version: Godot Engine v4.0.beta.custom_build (f3e6750a7e4702918e05f42b1376e30e652f2f90)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] <couldn't map PC to fn name>
[4] <couldn't map PC to fn name>
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] <couldn't map PC to fn name>
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
[13] <couldn't map PC to fn name>
[14] <couldn't map PC to fn name>
[15] <couldn't map PC to fn name>
[16] <couldn't map PC to fn name>
[17] <couldn't map PC to fn name>
[18] <couldn't map PC to fn name>
[19] <couldn't map PC to fn name>
[20] <couldn't map PC to fn name>
[21] <couldn't map PC to fn name>
[22] <couldn't map PC to fn name>
[23] <couldn't map PC to fn name>
[24] <couldn't map PC to fn name>
[25] <couldn't map PC to fn name>
[26] <couldn't map PC to fn name>
[27] <couldn't map PC to fn name>
[28] <couldn't map PC to fn name>
[29] <couldn't map PC to fn name>
[30] <couldn't map PC to fn name>
[31] <couldn't map PC to fn name>
[32] <couldn't map PC to fn name>
[33] <couldn't map PC to fn name>
[34] <couldn't map PC to fn name>
[35] <couldn't map PC to fn name>
[36] <couldn't map PC to fn name>
[37] <couldn't map PC to fn name>
[38] <couldn't map PC to fn name>
[39] <couldn't map PC to fn name>
[40] <couldn't map PC to fn name>
[41] <couldn't map PC to fn name>
[42] <couldn't map PC to fn name>
[43] <couldn't map PC to fn name>
[44] <couldn't map PC to fn name>
[45] <couldn't map PC to fn name>
[46] <couldn't map PC to fn name>
[47] <couldn't map PC to fn name>
[48] <couldn't map PC to fn name>
[49] <couldn't map PC to fn name>
[50] <couldn't map PC to fn name>
[51] <couldn't map PC to fn name>
[52] <couldn't map PC to fn name>
-- END OF BACKTRACE --

If there is any way i can actually try and help debug this i am all ears, i dont feel i am being much help atm. Although unfortunately i am back on 12 hour night shifts for the next few days so i will be pretty busy.

I have tried to reproduce the issue in a fresh project but have not managed to so far.

**Comment by produno** [comment]
@adamscott I should probably also note i had a circular dependency issue on the base class in Beta 5. I tried to re-add the type for this in Beta 6 and it still caused issues. When i removed the type, nothing changed as if it had been cached but did not clear, so it still assumed it was of that type, which was still causing issues.

I have no idea if that's related or another issue altogether but before that it didnt complain about the property in the other class, but about the class itself. Only after i changed the type of a property in the base class to cause a circular dependency bug it complained about the other property.

Hopefully i am making sense.

**Comment by adamscott** [comment]
@produno If you could create a minimal reproduction project, it would be ideal. I don't know how to reproduce, unfortunately.
If you don't know how, try to copy your project, and start erasing stuff until there's only the issue at hand.
