### PR TITLE
fix Android/HTML5 custom templates option does not work

### LINKED ISSUE #17661: Android/HTML5 custom templates option does not work
**Godot version:**
master (3.1-dev)
compiled export templates

**OS/device including version:**
Antergos OS (Linux)

**Issue description:**
https://godot.readthedocs.io/en/latest/development/compiling/compiling_for_android.html
The documentation shows that custom export templates should be either copied to ```/home/[username]/.godot/templates``` or linked via the Custom Package option in the godot exporter.
However I get the message that the export templates are missing: the export button is grayed out.
This only happens for Android and HTML5; the X11 and Windows export works fine.

### PR DESCRIPTION
**Pull request by Essojadojef**
Fixes #17661, allowing to export projects for android and html even if the default export templates are missing, as long as you provide custom ones.

### CODE REVIEW

File: platform/android/export/export.cpp [hunk 1]
```diff
@@ -1333,12 +1333,28 @@ class EditorExportAndroid : public EditorExportPlatform {
 
 	virtual bool can_export(const Ref<EditorExportPreset> &p_preset, String &r_error, bool &r_missing_templates) const {
 
+		String err;
 		r_missing_templates = find_export_template("android_debug.apk") == String() || find_export_template("android_release.apk") == String();
 
+		if (p_preset->get("custom_package/debug") != "") {
+			if (FileAccess::exists(p_preset->get("custom_package/debug"))) {
+				r_missing_templates = false;
```
Comment (akien-mga) [inline platform/android/export/export.cpp]: The problem with this approach is that if only one custom package is defined, then we consider that it's possible to export - but if it's say the debug package, and you want to export a release binary with no corresponding template, then it will error out.

That being said, the `EditorExportPlatformPC` uses a similar logic, so I guess it's OK to use the same for Android and JS. This whole system really needs a refactor though, but that's out of scope of this issue.

**Comment by akien-mga** [comment]
Thanks!
