### PR TITLE
Custom Skeleton3DEditorPlugin

### LINKED ISSUE #35652: Editor freeze when clicking Skeleton node of a glTF scene with 500+ bones
**Godot version:**
3.2 rc 4

**OS/device including version:**
macos 10.15.2
*Issue description:**
[New Game Project.zip](https://github.com/godotengine/godot/files/4121086/New.Game.Project.zip)

**Steps to reproduce:**
open BAQIR-RIG.glb  click armature_baq node,editor freeze

**Minimal reproduction project:**

*Bugsquad edit (keywords for easier searching): select, selecting, crash*

### PR DESCRIPTION
**Pull request by fire**
Co-authored-by: Marios Staikopoulos <marios@staik.net>

Screen Shot 2020-02-20 at 9 15 03 PM

Sponsored by IMVU.

Features:

Drag and drop skeleton parentage move with UNDO!

Rest and pose are exposed as transforms with degrees as units. [UPDATED]

Can key transforms into animation tracks.

Handles the other variables that represent a bone.

Ensure all used labels are translatable.

DOES NOT FREEZE THE EDITOR FOR 30 seconds swapping between the skeleton and any other node!!!

Use for testing:

https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Fox/glTF-Binary/Fox.glb

*Bugsquad edit:* Fixes #35652.

### CODE REVIEW

File: editor/plugins/skeleton_editor_plugin.cpp [hunk 1]
```diff
@@ -130,68 +439,263 @@ PhysicalBone *SkeletonEditor::create_physical_bone(int bone_id, int bone_child_i
...
+		const BoneId parent_idx = skeleton->get_bone_parent(selected_boneidx);
+		const int bone_count = skeleton->get_bone_count();
+		for (BoneId i = 0; i < bone_count; ++i) {
+			if (skeleton->get_bone_parent(i) == selected_boneidx) {
+				skeleton->set_bone_parent(i, parent_idx);
+			}
+		}
 	}
+
+	skeleton->set_bone_parent(selected_boneidx, target_boneidx);
```
Comment (fire) [inline editor/plugins/skeleton_editor_plugin.cpp]: Add undo and redo.

Comment (fire) [reply editor/plugins/skeleton_editor_plugin.cpp]: Drag and drop will change skeleton parentage.

Comment (fire) [reply editor/plugins/skeleton_editor_plugin.cpp]: Bone parentage is now reversible.

File: scene/3d/skeleton.cpp [hunk 2]
```diff
@@ -154,17 +154,17 @@ bool Skeleton::_get(const StringName &p_path, Variant &r_ret) const {
...
 	for (int i = 0; i < bones.size(); i++) {
 
 		String prep = "bones/" + itos(i) + "/";
-		p_list->push_back(PropertyInfo(Variant::STRING, prep + "name"));
-		p_list->push_back(PropertyInfo(Variant::INT, prep + "parent", PROPERTY_HINT_RANGE, "-1," + itos(bones.size() - 1) + ",1"));
-		p_list->push_back(PropertyInfo(Variant::TRANSFORM, prep + "rest"));
-		p_list->push_back(PropertyInfo(Variant::BOOL, prep + "enabled"));
-		p_list->push_back(PropertyInfo(Variant::TRANSFORM, prep + "pose", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_EDITOR));
-		p_list->push_back(PropertyInfo(Variant::ARRAY, prep + "bound_children"));
+		p_list->push_back(PropertyInfo(Variant::STRING, prep + "name", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_NOEDITOR));
```
Comment (fire) [inline scene/3d/skeleton.cpp]: This is a problem where setting the usage to be no editor stops the creation of the animation, when the goal is skip the inspector.

Comment (fire) [reply scene/3d/skeleton.cpp]: Probably fine.

**Comment by AndreaCatania** [comment]
Sample model: https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Fox/glTF-Binary/Fox.glb

File: editor/plugins/skeleton_editor_plugin.h [hunk 3]
```diff
@@ -35,11 +35,87 @@
...
+
+	GridContainer *translation_grid;
+	GridContainer *rotation_grid;
+	GridContainer *scale_grid;
+	GridContainer *transform_grid;
+
+	EditorSpinSlider *translation[3];
+	EditorSpinSlider *rotation[3];
+	EditorSpinSlider *scale[3];
+	EditorSpinSlider *transform[12];
```
Comment (AndreaCatania) [inline editor/plugins/skeleton_editor_plugin.h]: The name of these are miss leading; Who checked the code for the first time will find strange that it's possible to set the stepping or the colour to a variable called `translation`.

I propose to be more precise, so something like would be better:
```cpp
EditorSpinSlider *translation_slider[3];
EditorSpinSlider *rotation_slider[3];
EditorSpinSlider *scale_slider[3];
EditorSpinSlider *transform_slider[12];
```
or `spin` or `input`, or anything that tells that it's not just a `Vector3`

File: editor/plugins/skeleton_editor_plugin.cpp [hunk 4]
```diff
@@ -30,13 +30,326 @@
...
+				background_rects[0] = Rect2(key_button->get_position() + buffer, Size2(width, button_height));
+			} else {
+				background_rects[0] = Rect2(0, 0, 0, 0);
+			}
+
+			if (section->get_vbox()->is_visible()) {
+				background_rects[1] = Rect2(translation_grid->get_position() + buffer, Size2(width, vector_height));
+				background_rects[2] = Rect2(rotation_grid->get_position() + buffer, Size2(width, vector_height));
+				background_rects[3] = Rect2(scale_grid->get_position() + buffer, Size2(width, vector_height));
+				background_rects[4] = Rect2(transform_grid->get_position() + buffer, Size2(width, transform_height));
```
Comment (AndreaCatania) [inline editor/plugins/skeleton_editor_plugin.cpp]: A for loop would be better here

**Review by AndreaCatania — CHANGES_REQUESTED** [review]
@fire you did a really good job here, and this addition improves a lot the skeleton usability!

However, you can find some little tweaks that you can do to the code in order to improve it.

Another comment that I've is that there are too much hard written numbers that makes the code hard to read. See:
```cpp
for (int i = 0; i < 12; i++) {
```
What _12_ stands for? In these cases would be nice have something like:

```cpp
const int spin_slider_count = 12;
for (int i = 0; i < spin_slider_count; i++) {
```

File: editor/plugins/skeleton_editor_plugin.cpp [hunk 5]
```diff
@@ -30,13 +30,326 @@
...
+		translation[i]->set_label(desc[i]);
+		setup_spinner(translation[i], false);
+		translation[i]->set_step(0.1);
+		translation_grid->add_child(translation[i]);
+
+		rotation[i] = memnew(EditorSpinSlider());
+		rotation[i]->set_label(desc[i]);
+		rotation[i]->set_flat(true);
+		setup_spinner(rotation[i], false);
+		rotation[i]->set_step(0.1);
```
[the remark this answers is not in the document]
Comment (akien-mga) [reply editor/plugins/skeleton_editor_plugin.cpp]: FYI, if no step is defined, it will default to the `interface/inspector/default_float_step` editor setting, which is `0.001` by default. So indeed, not specifying the step is the right approach here if it's not meant to be particularly limited.

File: editor/plugins/skeleton_editor_plugin.cpp [hunk 6]
```diff
@@ -30,13 +30,326 @@
...
+	transform_grid->set_columns(3);
+	section->get_vbox()->add_child(transform_grid);
+
+	static const char *desc[12] = { "x", "y", "z", "x", "y", "z", "x", "y", "z", "x", "y", "z" };
+
+	for (int i = 0; i < 3; ++i) {
+		translation[i] = memnew(EditorSpinSlider());
+		translation[i]->set_label(desc[i]);
+		setup_spinner(translation[i], false);
+		translation[i]->set_step(0.1);
```
[the remark this answers is not in the document]
Comment (fire) [reply editor/plugins/skeleton_editor_plugin.cpp]: The goal is to allow left and right to 360 range and the other direction in a normal mouse distance.

File: editor/plugins/skeleton_editor_plugin.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (fire) [reply editor/plugins/skeleton_editor_plugin.cpp]: The 12 stands for the number of floats in a Transform. 3x3 (scale and rotation) + 1x3 (origin).

File: editor/plugins/skeleton_editor_plugin.cpp (hunk 4 above)
Comment (fire) [reply editor/plugins/skeleton_editor_plugin.cpp]: You cannot iterate here, because it does different things for the 5 controls.

Comment (fire) [reply editor/plugins/skeleton_editor_plugin.cpp]: I guess I can make it use a vector of vec2.

File: editor/plugins/skeleton_editor_plugin.cpp [hunk 7]
```diff
@@ -30,13 +30,326 @@
...
+		rotation[i]->set_label(desc[i]);
+		rotation[i]->set_flat(true);
+		setup_spinner(rotation[i], false);
+		rotation[i]->set_step(0.1);
+		rotation_grid->add_child(rotation[i]);
+
+		scale[i] = memnew(EditorSpinSlider());
+		scale[i]->set_label(desc[i]);
+		setup_spinner(scale[i], false);
+		scale[i]->set_step(0.1);
```
[the remark this answers is not in the document]
Comment (fire) [reply editor/plugins/skeleton_editor_plugin.cpp]: This is a general problem with sliders and forcing the step to be 0.1 is a hack. So I'll think about that problem in a different time.

File: editor/plugins/skeleton_editor_plugin.h (hunk 3 above)
Comment (fire) [reply editor/plugins/skeleton_editor_plugin.h]: Renamed.

File: editor/plugins/skeleton_editor_plugin.cpp [hunk 8]
```diff
@@ -30,13 +30,326 @@
...
+					if (rotation[i] != nullptr)
+						rotation[i]->set_custom_label_color(true, c);
+					if (scale[i] != nullptr)
+						scale[i]->set_custom_label_color(true, c);
+				}
+
+				if (transform[i] != nullptr) {
+					transform[i]->set_custom_label_color(true, c);
+				}
+			}
```
[the remark this answers is not in the document]
Comment (fire) [reply editor/plugins/skeleton_editor_plugin.cpp]: Split into separate loops.

File: editor/plugins/skeleton_editor_plugin.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (fire) [reply editor/plugins/skeleton_editor_plugin.cpp]: Removed the manual step.

File: editor/plugins/skeleton_editor_plugin.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (fire) [reply editor/plugins/skeleton_editor_plugin.cpp]: The translation range is (-inf, inf).
The rotation range is multiples of 0 to 360 that include the negatives.
The scale is mostly around -1 to 1. But it can be any number.

**Comment by fire** [comment]
Ready for second review. I didn't feel like figuring the math for iterating this and it's less clear with that math.

```c++
	transform_slider[0]->set_value(tform.get_basis()[Vector3::AXIS_X].x);
	transform_slider[1]->set_value(tform.get_basis()[Vector3::AXIS_X].y);
	transform_slider[2]->set_value(tform.get_basis()[Vector3::AXIS_X].z);
	transform_slider[3]->set_value(tform.get_basis()[Vector3::AXIS_Y].x);
	transform_slider[4]->set_value(tform.get_basis()[Vector3::AXIS_Y].y);
	transform_slider[5]->set_value(tform.get_basis()[Vector3::AXIS_Y].z);
	transform_slider[6]->set_value(tform.get_basis()[Vector3::AXIS_Z].x);
	transform_slider[7]->set_value(tform.get_basis()[Vector3::AXIS_Z].y);
	transform_slider[8]->set_value(tform.get_basis()[Vector3::AXIS_Z].z);
```

**Comment by fire** [comment]
Noticed that Bone Custom Rest is missing.

**Comment by fire** [comment]
Adding bone custom pose to the inspector.

editor_screenshot_2020-02-21T121021-0800

**Comment by AndreaCatania** [comment]
>  I didn't feel like figuring the math for iterating this and it's less clear with that math.

You can use this one:

```cpp
const int matrix_row_count = 3;
const int matrix_column_count = 3;

for(int c = 0; c < matrix_column_count; c++){
    for(int r = 0; r < matrix_row_count; r++){
        transform_slider[(c*matrix_row_count) + r]->set_value(tform.get_basis()[c][r]);
    }
}
```

**Review by AndreaCatania — APPROVED** [review]
The code looks better now, once fixed the above code it's good to be merged. However, I'm approving it now. Thanks :)

**Comment by fire** [comment]
Merged AndreaCatania's suggestion, but currently testing a bug with the matrix step being "1".

**Comment by AndreaCatania** [comment]
Godot is row major, I've corrected my code that was written for column major. I don't know if this is the cause, if not can you please explain the error? 

```
const int matrix_row_count = 3;
const int matrix_column_count = 3;

for(int r = 0; r < matrix_row_count; r++){
    for(int c = 0; c < matrix_column_count; c++){
        transform_slider[(r*matrix_column_count) + c]->set_value(tform.get_basis()[r][c]);
    }
}
```

**Comment by fire** [comment]
The problem was related the default stepping being of the properties being steps of 1 rather than 0.001 (default) or 0.1 (orientation).

Yes. The matrix order is wrong. I update the pr.

File: scene/3d/skeleton.h [hunk 9]
```diff
@@ -35,9 +35,12 @@
 #include "scene/3d/spatial.h"
 #include "scene/resources/skin.h"
 
-#ifndef _3D_DISABLED
+#ifndef BONE_ID_DEF
```
Comment (akien-mga) [inline scene/3d/skeleton.h]: What's the point of these guards? There are already header guards for the whole file so this code will only be included once.

File: scene/3d/skeleton.cpp [hunk 10]
```diff
@@ -929,6 +934,10 @@ void Skeleton::_bind_methods() {
 	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "animate_physical_bones"), "set_animate_physical_bones", "get_animate_physical_bones");
 #endif // _3D_DISABLED
 
+#ifdef TOOLS_ENABLED
+	ADD_SIGNAL(MethodInfo("pose_updated"));
+#endif // TOOLS_ENABLED
```
Comment (akien-mga) [inline scene/3d/skeleton.cpp]: That doesn't seem right. It's still unclear to me how to properly propagate info from scene to editor, but we don't use signals for that usually. Either change receptors or `change_notify`. @reduz would know more.

File: scene/3d/skeleton.h (hunk 9 above)
Comment (fire) [reply scene/3d/skeleton.h]: I think the intent is to expose the bone def globally. However, I can remove.

Comment (akien-mga) [reply scene/3d/skeleton.h]: But no existing code nor code added in this PR needs it, so it seems pointless?

**Comment by AndreaCatania** [comment]
What's the state of this?

**Comment by fire** [comment]
I updated it, but still had problems with change receptors, had to use a signal.

File: scene/3d/skeleton_3d.cpp [hunk 11]
```diff
@@ -639,8 +640,12 @@ int Skeleton3D::get_process_order(int p_idx) {
 	return process_order[p_idx];
 }
 
-void Skeleton3D::localize_rests() {
+const Vector<int> &Skeleton3D::get_process_order() {
```
Comment (fire) [inline scene/3d/skeleton_3d.cpp:643]: Any idea why `const Vector<int> &` breaks gdscript binding?

Must be `const Vector<int>`.

**Comment by fire** [comment]
Updated to master. Waiting on the build.

File: scene/3d/skeleton_3d.cpp [hunk 12]
```diff
@@ -346,11 +346,16 @@ void Skeleton3D::_notification(int p_what) {
...
 					ERR_CONTINUE(bone_index >= (uint32_t)len);
-					vs->skeleton_bone_set_transform(skeleton, i, bonesptr[bone_index].pose_global * skin->get_bind_pose(i));
+					rs->skeleton_bone_set_transform(skeleton, i, bonesptr[bone_index].pose_global * skin->get_bind_pose(i));
 				}
 			}
 
 			dirty = false;
+
+#ifdef TOOLS_ENABLED
+			emit_signal("pose_updated");
```
Comment (reduz) [inline scene/3d/skeleton_3d.cpp:356]: Emitting a signal here does not make me happy, but I understand why you need it.
Can you replace the C string by a StringName in scene_string_names.h ?

**Review by reduz — CHANGES_REQUESTED** [review]

File: scene/3d/skeleton_3d.cpp (hunk 12 above)
Comment (fire) [reply scene/3d/skeleton_3d.cpp:356]: Waking, but will make the changes to this when there's a free moment in the evenings.

Comment (fire) [reply scene/3d/skeleton_3d.cpp]: Missed one.

Comment (fire) [reply scene/3d/skeleton_3d.cpp]: Never mind, the create signal uses a string, but the emit signal uses a string name from scene_string_names.h. This is correct.

**Comment by JFonS** [comment]
The spinners used in the inspector only allow integer values, they should have float values.

I would also get rid of the custom grid of spinners and use the same inspector controls useed in Vector3 and Transform properties, but that could be done on a separate PR.

**Comment by fire** [comment]
@JFonS I changed the default to `spinner->set_step(0.001f);`.

Agreed, the matrix changes can be another pr.

**Review by JFonS — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks a lot!

@fire Would you be able to prepare a PR backporting this for the `3.2` branch? Given the amount of changes, I assume that a simple `git cherry-pick` might not be trivial nor guaranteed to work as expected. -- There's no hurry though, we might want to wait for some testing in `master` / further fixes before merging the same changes in `3.2`, so it could be for 3.2.3.

**Comment by slapin** [comment]
Would be nice to have for 3.2 as skeleton editing is currently very hard with 175 bones
as editor crashes with default settings freezing the computer beforehand. Increasing queue size fixes the crash but editing is still not a piece of cake.

**Comment by keymastar** [comment]
Is it possible to use this on 3.2, and if so, how? I am trying to make a 3d game and it seems impossible if I can't access my rigged models.

**Comment by Zireael07** [comment]
@slapin @keymastar 3.2 version is being worked on here: https://github.com/godotengine/godot/pull/39090 and not merged yet.

**Comment by keymastar** [comment]
> @slapin @keymastar 3.2 version is being worked on here: #39090 and not merged yet.

That's great to hear. Thanks for letting me know.

**Comment by slapin** [comment]
Thanks! Looking forward to it.

**Comment by akien-mga** [comment]
Removing `cherrypick:3.2` label as the cherrypicking is done via a separate PR: #39090.

**Comment by Sawrr** [comment]
I am not seeing the "Create physical skeleton" option anymore after this commit. The menu dropdown at the top seems to be missing. Was this intentional?

**Comment by fire** [comment]
Is not intentional.

**Comment by Sawrr** [comment]
@fire commenting out options->hide() seemed to fix it https://github.com/godotengine/godot/blob/master/editor/plugins/skeleton_3d_editor_plugin.cpp#L668

**Comment by fire** [comment]
@Sawrr Can you make a pull request, should be simple to test.

**Comment by Sawrr** [comment]
@fire Sure. This is my first PR so let me know if I need to add any additional detail https://github.com/godotengine/godot/pull/39543

**Comment by giabeni** [comment]
I think there is still open issues regarding to the Skeleton 3D Editor.

I am using [a model](https://free3d.com/3d-model/black-dragon-rigged-and-game-ready-92023.html) with no more than 150 bones and every time that I make a left/right click in the skeleton node, Godot crashes.

I have already tried using the DAE and the GLTF/GLB exports methods... but the result is the same.

I was hopeful that this new release would fix it but no success :( .

### Context and Environment:
**MacBook Pro**  macOS Catalina 10.15.1
**Processor** 2,3 GHz Dual-Core Intel Core i5
**Memory** 8GB 2133 MHz LPDDR3
**Graphics** Intel Iris Plus Graphics 640 1536 MB

Is it a memory issue of my computer or is it a real bug?

Btw, the animations and constraints using the bones works normally. It only crashes when selecting the skeleton node.

Thanks in advance

**Comment by Zireael07** [comment]
IIRC the 3.2 cherrypick hasn't happened yet, so it's on master only?
