### PR TITLE
Fix Bone2D gizmo scaling

### LINKED ISSUE #80643: The last Bone2D in the chain will scale incorrectly
### Godot version

v4.2.dev3.official [013e8e3af]

### System information

Ubuntu 23.04 x86_64

### Issue description

When scaling the last Bone2D from the chain, there is a specific case where the bone length will be more than expected.  

The main logic is to use the lower value from scale `MIN(get_global_scale().x, get_global_scale().y)`:  
https://github.com/godotengine/godot/blob/c495eb5102278a110c14bbffbf833ed436d1594d/scene/2d/skeleton_2d.cpp#L328  

But this can go wrong when the lower value is negative, attention for (-1, 3) and (1, -3):  
image  

**Note**: This can easily be fixed by getting the absolute value from scale.  
```cpp
rel = Vector2(cos(angle_to_use), sin(angle_to_use)) * (length * MIN(ABS(get_global_scale().x), ABS(get_global_scale().y)));
```  

**Note 2**: (1, -3) and (-1, 3) as only equal after saving the project because the project reload information from transforms and the (-1, 3) is convert to (1, -3).  

### Steps to reproduce

- Create a scene with Node2D as root
- Add a Skeleton2D
- Add a Bone2D
- Scale Bone2D by (1, -3)

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by TokageItLab**
Co-authored-by: Thiago Lages de Alencar <thiagola92@gmail.com> @thiagola92

- Supersedes / Closes https://github.com/godotengine/godot/pull/81048
- Fixes #80643

~To minimize the effect of the fix; Context: https://github.com/godotengine/godot/pull/81048#discussion_r1594462768~ Revised overall behavior.

### CODE REVIEW

File: scene/2d/skeleton_2d.cpp [hunk 1]
```diff
@@ -329,7 +329,7 @@ bool Bone2D::_editor_get_bone_shape(Vector<Vector2> *p_shape, Vector<Vector2> *p
 		rel = rel.rotated(-get_global_rotation()); // Undo Bone2D node's rotation so its drawn correctly regardless of the node's rotation
 	} else {
 		real_t angle_to_use = get_rotation() + bone_angle;
-		rel = Vector2(cos(angle_to_use), sin(angle_to_use)) * (length * MIN(get_global_scale().x, get_global_scale().y));
+		rel = Vector2(cos(angle_to_use), sin(angle_to_use)) * length * get_global_scale();
```
Comment (AThousandShips) [inline scene/2d/skeleton_2d.cpp:332]:
```suggestion
		rel = Vector2(Math::cos(angle_to_use), Math::sin(angle_to_use)) * length * get_global_scale();
```
While we're at it

**Comment by TokageItLab** [comment]
I think the problem was that the gizmo scaling was scaling after the rotation. So, perhaps the scaling of Node is done before the rotation? I think that is where the direction mismatch was occurring.

Also, the abs() was needed in #81048 because there was a reverse rotation there to cancel first rotation (it was done rotation->scaling->rotation.inv). So now I make to simplify the calculations for the deformation so that they match the Node scaling.

@thiagola92 Does this change make sense to you?

**Comment by thiagola92** [comment]
> I think the problem was that the gizmo scaling was scaling after the rotation. So, perhaps the scaling of Node is done before the rotation? I think that is where the direction mismatch was occurring.
> 
> Also, the abs() was needed in #81048 because there was a reverse rotation there to cancel first rotation (it was done rotation->scaling->rotation.inv). So now I make to simplify the calculations for the deformation so that they match the Node scaling.
> 
> @thiagola92 Does this change make sense to you?

I tested and it seems to be working :+1:  

I'm still confuse about how the rotation was affecting everything.  
In my head `get_rotation()` was useless in this lines because would cancel itself:  
```cpp
real_t angle_to_use = get_rotation() + bone_angle;
//
rel = rel.rotated(-get_rotation());
```

But if I'm understanding correctly, there were some scale operation during this step... I'm understanding correctly?

**Comment by thiagola92** [comment]
Note: This would fix Bone2D *length* when scaling  

To fix height too would probably need something like #81544 (which I used `abs()` probably without needing)

**Comment by TokageItLab** [comment]
> I'm still confuse about how the rotation was affecting everything.
> In my head get_rotation() was useless in this lines because would cancel itself:

In the old code, the vector after rotation (Bone Angle + rotation) was globally scaled.

This code globally scales the vector after rotation by Bone Angle only.

Evenually, Bone Angle is a Bone2D property, so it should be handled by Bone2D, but rotation is a Node2D property, so transformation/scaling for rotation should be handled by Node2D.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.
