### PR TITLE
Prevent dragging from SceneTree buttons

### LINKED ISSUE #10026: SceneTreeDock: dragging node by column != 0 reparents wrong node
**Operating system or device - Godot version:**
Antergos x86_64 - daad16b

**Issue description:**

Expected: Column other than the first undraggable, or reselect node when dragging other column
Happened: Node selected gets reparented instead of node dragged

**Steps to reproduce:**
1. Create some nodes with toggle visibility (eye) icon
2. Select one node
3. Drag another node TreeItem by its toggle visibility icon
4. Notice that the drag preview is of selected node
5. Node selected gets reparented instead of node dragged

### PR DESCRIPTION
**Pull request by timothyqiu**
This fixes #10026

* Disables the possibility to drag a node from its icon buttons
    * To determine whether it's dragging from the icon buttons, a `Tree:: get_button_id_at_position` public method is added
        * Why not `get_button_at_position`? While button ID is a standalone value, button index does not make much sense without item/column around. Get button ID makes the method simple.
        * Why not `is_button_at_position`? As a public method, this seems too limited to a single application.

### CODE REVIEW

**Comment by aaronfranke** [comment]
@timothyqiu Is this still desired? If so, it needs to be rebased on the latest master branch. While there are no conflicts, rebasing is important so that reviewers can easily test the PR.

**Comment by timothyqiu** [comment]
Rebased :)

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -3623,6 +3623,46 @@ TreeItem *Tree::get_item_at_position(const Point2 &p_pos) const {
 	return nullptr;
 }
 
+int Tree::get_button_id_at_position(const Point2 &p_pos) const {
+
```
Comment (akien-mga) [inline scene/gui/tree.cpp:3627]: We changed our style guide since this was first written, so now you should remove the empty lines at the start of code blocks (here and lines 3629 and 3645), and add braces around single line `if` or `for` blocks.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.
