### PR TITLE
Fix global scripts not being added because of bad `global_script_class_cache.cfg`

### LINKED ISSUE #102557: Upgrading project to 4.4 results in GDScript parser errors
### Tested versions

- Reproducible in: 4.4.beta3

### System information

Godot v4.3.stable - Windows 10.0.26100 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 32.0.15.6636) - AMD Ryzen 9 7940HS w/ Radeon 780M Graphics (16 Threads)

### Issue description

I can't quite explain this one, but I happened to run into this when reporting #102551.

In short, there's something strange going on with GDScript when upgrading this particular MRP from 4.3 to 4.4, where you'll be met with parser errors after upgrading, that then manifest themselves at runtime as well.

It seems that it has something to do with the stuff that's cached in the `.godot` folder, as deleting it resolves the errors, regardless if you delete it before or after upgrading. As such, I've included a more comprehensive set of reproduction steps to create the project from scratch, as opposed to providing an MRP.

I tried reducing down the script to something even more minimal, but for whatever reason this particular script seems to force the problem.

### Steps to reproduce

- Create a new project using 4.3-stable
- Add a 2D main scene, call it `main.tscn`
- Add a new GDScript script through the FileSystem dock, call it `my_resource.gd`
- Populate `my_resource.gd` with the following contents:

```gdscript
extends Resource
class_name MyResource
```

- Attach a new script to the root of `main.tscn`, call it `main.gd`
- Populate `main.gd` with the following contents:

```gdscript
extends Node2D

@export var my_resource: MyResource

func _ready() -> void:
	bytes_to_var_with_objects(var_to_bytes_with_objects(my_resource)) as MyResource
```

- Run the main scene
- Note that it runs without errors
- Close the project
- Open the project in Godot 4.4-beta3
- Go through the upgrade process
- Note errors in Output pane saying:

```
ERROR: res://main.gd:3 - Parse Error: Could not find type "MyResource" in the current scope.
ERROR: res://main.gd:3 - Parse Error: Cannot use simple "@export" annotation because the type of the initialized value can't be inferred.
ERROR: res://main.gd:6 - Parse Error: Could not find type "MyResource" in the current scope.
ERROR: modules/gdscript/gdscript.cpp:3022 - Failed to load script "res://main.gd" with error "Parse error".
```

- Reload the project
- Note the lack of errors
- Run the main scene
- Note debugger break with error saying `Parser Error: Could not find type "MyResource" in the current scope.`
- Close the project
- Delete the `.godot` folder
- Open the project again
- Run the main scene
- Note how it runs fine

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #102568: Bad `global_script_class_cache.cfg` in project version upgrade
### Tested versions

v4.4.beta3.official [06acfccf8] - broken
v4.4.beta2.official [a013481b0] - worked fine

### System information

Godot v4.4.beta3 - Windows 10 (build 19045) - Multi-window, 1 monitor - Vulkan (Mobile) - dedicated AMD Radeon RX 6600 (Advanced Micro Devices, Inc.; 32.0.11027.2001) - AMD Ryzen 5 3600 6-Core Processor (12 threads)

### Issue description

On upgrading my project to 4.4-beta3, I get the error "Parser Error: 'Util' not defined in the current scope" in one of my scripts. This did not occur in 4.4-beta2 or earlier.

The error occurs in my `ConfigManager` autoload, which is near the start of my load order. The class `Util`, is a script which simply has a `class_name Util`, and a number of `static func`s, for general use.

My only assumption is that some sort of complex load order issue is causing it to fail to find `Util` at the time of `ConfigManager`. Attempting to reproduce this for an MRP has so far eluded me, so it seems unlikely to be trivial. `Util` does have some functions which reference other classes, ex. at least one of them checks for `is BaseScene`, referencing my `BaseScene` class; which itself references other autoloads that are after the ConfigManager? But attempting a similar setup in a fresh project didn't reproduce, so I'm really not sure exactly what's causing this.

### Steps to reproduce

Unknown; but something definitely regressed here. Will edit with steps if I manage to reproduce cleanly.

### Minimal reproduction project (MRP)

Will edit with MRP if I manage to reproduce cleanly.

### PR DESCRIPTION
**Pull request by amarsero**
Fixes #102557, probably also fixes #102568

The Issue:
A [commit](https://github.com/godotengine/godot/commit/318af42020cd349c5c9c3e4c88aa87249ca224b0) made "is_tool" and "is_abstract" mandatory to add new global classes to `ScriptServer::global_classes`.  But `global_script_class_cache.cfg` from projects before 4.4 lack these properties, so these classes won't be added, causing errors when running the game.

Current Solution:
After the editor scans all the scripts for the first time, now forcibly updates `global_script_class_cache.cfg`, resolving the issue. 
However, running a 4.3 game with 4.4 without first opening it with the editor at least once still fails.

I've tried to fix this in `ScriptServer::init_languages`, where the global classes are first loaded, but couldn't figure it out.

### CODE REVIEW

**Comment by akien-mga** [comment]
Some quick thoughts, but @RandomShaper and @Hilderin should be able to assess this further:

- This seems to remove an optimization (only update when it's need). Would be good to assess whether this will lead to a lot more updates than necessary and possibly a performance impact, or possible side effects of writing an unchanged file to disk too frequently (Windows can be touchy there). If yes, the alternative could be to figure out how to better check whether an update is needed, instead of always updating.
- Another approach could be to make the new `is_tool` and `is_abstract` not mandatory, and treat those as `false` if they're missing. Or a third bool option ("unset") but that would require another variable or changing to an int internally, that's a bit hacky.

I'm not necessarily suggesting to implement any of the above, it's just food for thought. The proposed solution here might totally be the best one already.

**Comment by amarsero** [comment]
Thanks for the thoughts!

About removing the optimization, i believe the method is called only once at the start of the editor. Only on the `first_scan` of the `EditorFileSystem`. So there should be no big performance impact.

And i thought about making them not mandatory, but tool scripts were added on 4.3, so any tool script migrating to 4.4 might break if we default to false.

The problem is not so much the editor, since it refreshes all the scripts at startup, but the games don't work when `global_script_class_cache.cfg` is bad.

**Comment by Hilderin** [comment]
After looking at the issue a bit, I found 2 problems.

1. When `_first_scan_process_scripts` calls `_register_global_class_script`, the following lines are never called:
```cpp
ScriptServer::save_global_classes();
EditorNode::get_editor_data().script_class_save_icon_paths();
```
That causes the `global_script_class_cache.cfg` to not be saved on first scan. I tested by modifying the `_first_scan_process_scripts` to return true when a new global script is registered and added the call to these 2 lines when it results true.

2. The most problematic issue is that the `UIDUpgradeTool::get_singleton()->finish_upgrade` is done before the first scan is done and since the global cache is invalid, all the scripts processed in the update are invalid. I fixed that by executing the upgrade after the first scan.

Another minor modif: I added a break in `EditorFileSystem::_get_global_script_class` to prevent looping for nothing.

I created a branch with my modified test code to help you if you want: https://github.com/godotengine/godot/compare/master...Hilderin:godot:fix-global-class-names-not-save-with-upgrade-tool

**Comment by amarsero** [comment]
Thanks for the help Hilderin!

Now if a global class is found or removed on the first scan, `global_script_class_cache.cfg` is updated.
This is to ensure migrations from earlier versions have all the needed properties.

Also i noticed that every time that `EditorData::script_class_save_icon_paths` was called, `ScriptServer::save_global_classes` was called immediately before. And both methods changed and saved `global_script_class_cache.cfg`. To avoid writing the file twice I took the liberty of unifying both methods into `script_class_save_icon_paths` (but without modifying `save_global_classes`).

File: editor/editor_data.cpp [hunk 1]
```diff
@@ -1042,23 +1042,22 @@ void EditorData::script_class_set_name(const String &p_path, const StringName &p
 }
 
 void EditorData::script_class_save_icon_paths() {
```
Comment (akien-mga) [inline editor/editor_data.cpp:1044]: This is no longer only saving icon paths, so it should be renamed to better describe what it does.

File: editor/editor_file_system.cpp [hunk 2]
```diff
@@ -319,7 +319,12 @@ void EditorFileSystem::_first_scan_filesystem() {
 	_first_scan_process_scripts(first_scan_root_dir, gdextension_extensions, existing_class_names, extensions);
 
 	// Removing invalid global class to prevent having invalid paths in ScriptServer.
-	_remove_invalid_global_class_names(existing_class_names);
+	bool save_scripts = _remove_invalid_global_class_names(existing_class_names);
+
+	// If a global class is found or removed, we sync global_script_class_cache.cfg with the ScriptServer
+	if (!existing_class_names.is_empty() || save_scripts) {
```
Comment (Hilderin) [inline editor/editor_file_system.cpp:325]: At this point, I'm wondering if it's just simpler to always resave the global class cache file. With this modification, the cache is saved everytime when there is at least one global class. If `existing_class_names` is empty, saving the file will be ultra fast.

I still think the best approach should be to return a bool from `_first_scan_process_scripts` to prevent rewriting the cache when nothing was added. It's easy to do and on a large project it could save a couple of ms.

File: editor/editor_data.cpp (hunk 1 above)
Comment (Hilderin) [inline editor/editor_data.cpp:1044]: With this modification, le method `ScriptServer::save_global_classes` could be removed completely and we could only use this method. You already removed almost every call to `ScriptServer::save_global_classes`, the other(s) could be replaced by this method.

File: editor/editor_file_system.cpp (hunk 2 above)
Comment (amarsero) [reply editor/editor_file_system.cpp:325]: Also, the original problem is that migrating from 4.3 to 4.4, the properties "is_tool" and "is_abstract" are missing from `global_script_class_cache.cfg`. I could check if a class was added or removed or if any of the `existing_class_names` have those properties missing, but maybe that complexity is not worth it.

Although I have no problem trying.

File: editor/editor_node.cpp [hunk 3]
```diff
@@ -901,6 +895,20 @@ void EditorNode::_update_update_spinner() {
 	OS::get_singleton()->set_low_processor_usage_mode(!update_continuously);
 }
 
+void EditorNode::_execute_upgrades() {
+	if (run_surface_upgrade_tool) {
```
Comment (RandomShaper) [inline editor/editor_node.cpp:899]: I know this is unrelated, but I was curious about why these checks are excluding. I've found it's only possible that one of them is instructed to run. If only this has been modeled as an enum... But again, not in this PR's scope.

**Review by RandomShaper — APPROVED** [review]
Notwithstanding other comments needing to be addressed, this makes sense to me.

File: editor/editor_data.cpp (hunk 1 above)
Comment (KoBeWi) [reply editor/editor_data.cpp:1044]: Can we instead remove this method and use the ScriptServer one? It's much more efficient, because it doesn't query every class property.

File: editor/editor_node.cpp (hunk 3 above)
Comment (KoBeWi) [reply editor/editor_node.cpp:899]: I plan to eventually replace both tools with a universal one. They do pretty much the same thing.

**Comment by KoBeWi** [comment]
`script_class_save_icon_paths()` seems to be called as often as before. Now it updates all class properties, while previously it would *load* class cache, modify one property of each class and save it too, so not much changed on that regard. We could better optimize class cache saving, but this PR does not make it worse.

File: editor/editor_data.cpp (hunk 1 above)
Comment (amarsero) [reply editor/editor_data.cpp:1044]: The problem is that `EditorData::script_class_save_icon_paths` has access to the icon paths for all scripts, while `ScriptServer::save_global_classes` has all the other properties but only for global scripts.
A quick fix is to make `ScriptServer` a friend of `EditorData`, and keep only `ScriptServer::save_global_classes`. 
A more complete solution would be to use `ScriptServer::get_class_icon_path` as the source of truth for global script icons while using`EditorData::_script_class_icon_paths` for the others. But this would make the code more confusing.

File: editor/editor_file_system.cpp (hunk 2 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp:325]: I guess it could be done in another PR if needed, it works with the current state of the PR.

Comment (Hilderin) [reply editor/editor_file_system.cpp:325]: In fact, It's not bad that the cache is recreated each startup because it forces to update all the props of the global classes if the cache file.

File: editor/editor_data.cpp (hunk 1 above)
Comment (Hilderin) [reply editor/editor_data.cpp]: I suggest to do that in another PR, right now, this issue is a real problem for the release of 4.4 and it works just fine as is,

**Review by Hilderin — APPROVED** [review]
Tested locally, it works as expected, fixes the issue and even prevents some potential out of sync of the global cache file on some limit cases or in the future if other props are added. Good job!

**Comment by akien-mga** [comment]
Thanks!
