### PR TITLE
Fix region section not ignoring #region and #endregion when in a string

### LINKED ISSUE #89115: Region section is not correctly handled when "#endregion" is set in a string variable inside the region
### Tested versions

Godot 4.3 dev 4 (probably previous versions as well)

### System information

Manjaro Linux (DE: Cinnamon v6.0.4) 64 bits (but probably all systems)

### Issue description

When using the comment regions in a script, if a string inside a region contains "#endregion" alone on a single line, it triggers the region's end prematurely and then messes the region feature.

### Steps to reproduce

Copy the following code inside a script and try to fold the region TEST (comments are only there to explain the behavior):

```
#region TEST
# This region should be folded up to the EOF comment
func test() -> void:
	# Dummy content
	var testing : String = "" 
	# To trigger the region's end, the string must be the first thing on the line, with or without tabs in front
	# Single quoted or literal strings does the same effect
	testing += """
#endregion
"""
	# Some more content which will not be folded with the region!
	var new_var : int = 3
# The real end of the region, when folding TEST we should not see any of the test() method content
#endregion
# EOF comment
```
The result is a partially folded region (see screenshots below).

Unfolded region:
Capture d’écran du 2024-03-03 16-29-57

Actual folded region:
Capture d’écran du 2024-03-03 16-30-10

Expected result:
Capture d’écran du 2024-03-03 16-42-08

### Minimal reproduction project (MRP)

Not necessary.

### PR DESCRIPTION
**Pull request by RafaelRain18**
When using the script editor, if the keywords #region and #endregion where in a string and at the start of the line, the editor would not ignore them and count them as the actual keywords, which when folded, would only fold until the first #endregion in a string, for example.

By checking if these keywords were in a string, this commit now ensures the editor ignores strings and fold the section correctly.

Fixes #89115.

### CODE REVIEW

**Comment by Kiisu-Master** [comment]
Wouldn't it make more sense to add `is_in_string` check to the `is_line_code_region_*` functions?
Because right now it means that the `is_line_code_region_*` functions are still returning incorrect answer.

**Comment by RafaelRain18** [comment]
@Kiisu-Master Yeah, for some reason when I changed it before, it was still giving me the wrong results, so I thought there was something else that I wasn't seeing and I didn't want to break anything else, so I did it this way. But now when I tried it again it now works perfectly.
Should I now close this PR and open a similar one with the changes?

**Review by Paulb23 — COMMENTED** [review]
Thanks for the contribution!

Code and tests looks good to me.

Any chance you could rebase and squash your commits, we have some documentation here that should help: https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#updating-your-branch

File: tests/scene/test_code_edit.h [hunk 1]
```diff
@@ -3048,6 +3048,27 @@ TEST_CASE("[SceneTree][CodeEdit] region folding") {
...
+		code_edit->add_comment_delimiter("#", "");
+		code_edit->clear_string_delimiters();
+		code_edit->add_string_delimiter("\"", "\"");
+		code_edit->set_text("#region region_name1\nline2\n\"\n#region region_name2\n#endregion\n\"\n#endregion\nvisible");
+		CHECK(code_edit->is_line_code_region_start(0));
+		CHECK(code_edit->is_line_code_region_end(6));
+		CHECK(code_edit->can_fold_line(0));
+		for (int i = 1; i < 7; i++) {
+			if (i == 2)
+				continue;
```
Comment (AThousandShips) [inline tests/scene/test_code_edit.h:3063]:
```suggestion
			if (i == 2) {
				continue;
			}
```
Always use brackets

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
