### PR TITLE
Fixed unknown ASCII symbols rendered instead of tabs in bookmarks list

### LINKED ISSUE #34046: Bookmark list shows unknown symbol for tabs
**Godot version:**
3.2 beta2

**Issue description:**
image
image
Might happen when toggling comment, because it puts # at the beginning of the line.

### PR DESCRIPTION
**Pull request by andycodesstuff**
Escape characters were not rendered properly in the bookmarks list of the script editor if the bookmarked line was a comment, resulting in unknown ASCII symbols “�”

Fixes #34046

### CODE REVIEW

**Comment by andrycodestuffs** [comment]
I have just realized that I forgot to check if the string is empty before checking if the bookmarked line is a comment.
I'm going to fix this very quickly

File: editor/plugins/script_text_editor.cpp [hunk 1]
```diff
@@ -690,7 +690,14 @@ void ScriptTextEditor::_update_bookmark_list() {
 	bookmarks_menu->add_separator();
 
 	for (int i = 0; i < bookmark_list.size(); i++) {
+		// Strip edges to avoid rendering unknown ASCII symbol ('�')
 		String line = code_editor->get_text_edit()->get_line(bookmark_list[i]).strip_edges();
+
+		// Strip edges from comments' content
+		if (line.length() > 0 && line.get(0) == '#') {
+			line = "# " + line.substr(1).strip_edges();
```
Comment (akien-mga) [inline editor/plugins/script_text_editor.cpp]: Won't this crash if `line.length() == 1`?

Comment (akien-mga) [reply editor/plugins/script_text_editor.cpp]: But beyond that, I'm not sure why `strip_edges()` is used to solve this. `strip_edges()` removes whitespace characters at the start and end of the string (and here if it's working I guess invalid chars are mistakenly seen as "whitespace"), but won't handle any invalid characters within the string. So `# Some comment<TAB>More comment` will still have the same problem.

Comment (andrycodestuffs) [reply editor/plugins/script_text_editor.cpp]: I wholeheartedly agree.
In the beginning, I thought about understanding why are escape characters are rendered improperly in the first place but quickly got overwhelmed by the size of the codebase.
When I find something that solves the issue in the more general case, I will add commits to this pull request and let you know

Comment (KoBeWi) [reply editor/plugins/script_text_editor.cpp]: `replace("\t", "    ")`

Comment (andrycodestuffs) [reply editor/plugins/script_text_editor.cpp]: I tried to render other escape characters with the same result and I noticed that this behaviour applies to every character that comes before the space in ASCII (hex 0x20, decimal 32).
Is this intended behaviour? Or should we just replace them with whitespace?

**Comment by kimjiy9607** [comment]
Can I ask why is this still open after all the checks have been passed?

**Comment by akien-mga** [comment]
> Can I ask why is this still open after all the checks have been passed?

Because it's not merged yet. It's not the correct solution as discussed above in the comments, so it needs to be reworked before it can be merged.

The "checks" are just checking that the code compiles, it doesn't mean that it's approved.

**Comment by andrycodestuffs** [comment]
> Is this intended behaviour? Or should we just replace them with whitespace?

I asked this question to decide what type of solution I should be working on.
If it is normal that characters like tab, newline, etcetera are rendered with “�”, I will work on fixing my implementation.
Otherwise, I was thinking about fixing the root cause of the issue (in addition to my implementation, which has to be improved for sure)

**Comment by Calinou** [comment]
I think calling `strip_edges(false, true).replace("\t", "    ")` on the string could work well enough here.

**Comment by Feniks-Gaming** [comment]
@Calinou after those changes is this ready to be merged. It looks like it

File: editor/plugins/script_text_editor.cpp [hunk 2]
```diff
@@ -690,7 +690,20 @@ void ScriptTextEditor::_update_bookmark_list() {
...
 	for (int i = 0; i < bookmark_list.size(); i++) {
+		// Strip edges to avoid rendering unknown ASCII symbol ('�')
 		String line = code_editor->get_text_edit()->get_line(bookmark_list[i]).strip_edges();
+
+		if (line.length() > 1 && line.get(0) == '#') {
+			// Use configured tab size to create a tab replacement using only spaces
+			String tab_replacement = "";
+			for (int j = 0; j < code_editor->get_text_edit()->get_indent_size(); j++) {
+				tab_replacement += " ";
+			}
```
Comment (akien-mga) [inline editor/plugins/script_text_editor.cpp]: That's ok, but IMO for the bookmarks it would have been just as fine to simply replace `"\t"` by one or two spaces.

We don't really need to see all the indentation as wide as it is in the script editor, in fact we even strip it away from indented strings which aren't comments.

File: editor/plugins/script_text_editor.cpp [hunk 3]
```diff
@@ -690,7 +690,20 @@ void ScriptTextEditor::_update_bookmark_list() {
...
+
+			// Strip edges from comments' content
+			line = "# " + line.substr(1).strip_edges().replace("\t", tab_replacement);
```
Comment (akien-mga) [inline editor/plugins/script_text_editor.cpp]: I'd simplify as:
```
line = line.replace("\t", tab_replacement).strip_edges()
```
or simply
```
line = line.replace("\t", "  ").strip_edges()
```

**Comment by akien-mga** [comment]
Could you squash commits into one? See [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase).

**Comment by akien-mga** [comment]
I'll squash the commits and do some simplifications.

I also missed all this time that this was only adjusting the bookmarks menu, but the breakpoints menu has the same issue.

**Comment by akien-mga** [comment]
Now looks like this:
Screenshot_20200116_134731

**Comment by akien-mga** [comment]
Thanks!
