### PR TITLE
Fix physics/3d/run_on_separate_thread race condition in WorkerThreadPool (crash).

### LINKED ISSUE #63671: Godot 4.0 Alpha 13 Threaded Physics causes Crashing
### Godot version

4.0 Alpha 13

### System information

Windows 11, Vulkan, Nvidia GTX 1050 Ti, 512.15

### Issue description

Regression in Alpha 13 (not found in Alpha 12)

Running a Scene with Physics running on a Thread causes a crash within several minutes of running.

### Steps to reproduce

Set Physics to run on a Separate Thread
Run any Scene (F6)
Wait a couple of minutes for Crash to occur

### Minimal reproduction project

Only setting Physics to run on a Separate Thread (2d & 3d) is required to reproduce, nothing else matters

### LINKED ISSUE #63879: WorkerThreadPool::_add_group_task crash
### Godot version

3ea9a7daea58c825a78ce1b5ed5d2becc2f84966 + 50 branches

### System information

popos 22.04 Linux, Vulkan, NVIDIA 3000 series

### Issue description

image

Godot Engine crashes.

```
[Unknown/Just-In-Time compiled code] (Unknown Source:0)
memdelete<WorkerThreadPool::BaseTemplateUserdata>(WorkerThreadPool::BaseTemplateUserdata * p_class) (/home/elee/Documents/chibifire/groups-engine-workspace/godot/core/os/memory.h:108)
WorkerThreadPool::_add_group_task(WorkerThreadPool * this, const Callable & p_callable, void (*)(void *, uint32_t) p_func, void * p_userdata, WorkerThreadPool::BaseTemplateUserdata * p_template_userdata, int p_elements, int p_tasks, const String & p_description) (/home/elee/Documents/chibifire/groups-engine-workspace/godot/core/object/worker_thread_pool.cpp:303)
WorkerThreadPool::add_template_group_task<GodotStep3D, void (GodotStep3D::*)(unsigned int, void*), decltype(nullptr)>(GodotStep3D*, void (GodotStep3D::*)(unsigned int, void*), decltype(nullptr), int, int, bool, String const&)(WorkerThreadPool * this, GodotStep3D * p_instance, void (GodotStep3D::*)(GodotStep3D * const, unsigned int, void *) p_method, decltype(nullptr) p_userdata, int p_elements, int p_tasks, bool p_high_priority,  p_description) (/home/elee/Documents/chibifire/groups-engine-workspace/godot/core/object/worker_thread_pool.h:181)
GodotStep3D::step(GodotStep3D * this, GodotSpace3D * p_space, real_t p_delta) (/home/elee/Documents/chibifire/groups-engine-workspace/godot/servers/physics_3d/godot_step_3d.cpp:346)
GodotPhysicsServer3D::step(GodotPhysicsServer3D * this, real_t p_step) (/home/elee/Documents/chibifire/groups-engine-workspace/godot/servers/physics_3d/godot_physics_server_3d.cpp:1615)
PhysicsServer3DWrapMT::thread_step(PhysicsServer3DWrapMT * this, real_t p_delta) (/home/elee/Documents/chibifire/groups-engine-workspace/godot/servers/physics_server_3d_wrap_mt.cpp:40)
CommandQueueMT::_flush(CommandQueueMT * this) (/home/elee/Documents/chibifire/groups-engine-workspace/godot/core/templates/command_queue_mt.h:373)
CommandQueueMT::wait_and_flush(CommandQueueMT * this) (/home/elee/Documents/chibifire/groups-engine-workspace/godot/core/templates/command_queue_mt.h:414)
PhysicsServer3DWrapMT::thread_loop(PhysicsServer3DWrapMT * this) (/home/elee/Documents/chibifire/groups-engine-workspace/godot/servers/physics_server_3d_wrap_mt.cpp:59)
PhysicsServer3DWrapMT::_thread_callback(void * _instance) (/home/elee/Documents/chibifire/groups-engine-workspace/godot/servers/physics_server_3d_wrap_mt.cpp:47)
Thread::callback(Thread * p_self, const Thread::Settings & p_settings, Thread::Callback p_callback, void * p_userdata) (/home/elee/Documents/chibifire/groups-engine-workspace/godot/core/os/thread.cpp:75)
execute_native_thread_routine (Unknown Source:0)
libc.so.6!start_thread(void * arg) (pthread_create.c:442)
libc.so.6!clone3() (clone3.S:81)
```

### Steps to reproduce

For our project when we use the background loader and the download file is 200+ megabytes.

### Minimal reproduction project

I wasn't able to reduce our project maybe we can try the previous demo from https://github.com/godotengine/godot/issues/56776

### LINKED ISSUE #67333: Certain Control nodes cause a crash if `physics/3d/run_on_separate_thread` is enabled
### Godot version

v4.0.beta.custom_build [ea47e03b3]

### System information

Linux (Fedora 36)

### Issue description

If 3D physics is set to run on a separate thread, some Control nodes will cause a crash. It does not matter if there are any 3D nodes actually in the scene tree at all.
Clicking a ColorPickerButton seems to crash the most frequently. I also got a crash from clicking around on a ColorPicker (sans button), leaving an empty Tree open for a while, and clicking on a regular Button. All produced the same stacktrace:
```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta.custom_build (ea47e03b360d0aeee10c1f7ef798f5750c2b1aa8)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[1] /lib64/libc.so.6(+0x3ea70) [0x7f5da7241a70] (??:0)
[2] void memdelete<WorkerThreadPool::BaseTemplateUserdata>(WorkerThreadPool::BaseTemplateUserdata*) (/home/jtnicholl/godot/source/godot/./core/os/memory.h:109)
[3] WorkerThreadPool::_add_group_task(Callable const&, void (*)(void*, unsigned int), void*, WorkerThreadPool::BaseTemplateUserdata*, int, int, bool, String const&) (/home/jtnicholl/godot/source/godot/core/object/worker_thread_pool.cpp:303)
[4] long WorkerThreadPool::add_template_group_task<GodotStep3D, void (GodotStep3D::*)(unsigned int, void*), decltype(nullptr)>(GodotStep3D*, void (GodotStep3D::*)(unsigned int, void*), decltype(nullptr), int, int, bool, String const&) (/home/jtnicholl/godot/source/godot/./core/object/worker_thread_pool.h:181)
[5] GodotStep3D::step(GodotSpace3D*, float) (/home/jtnicholl/godot/source/godot/servers/physics_3d/godot_step_3d.cpp:346)
[6] GodotPhysicsServer3D::step(float) (/home/jtnicholl/godot/source/godot/servers/physics_3d/godot_physics_server_3d.cpp:1645 (discriminator 3))
[7] PhysicsServer3DWrapMT::thread_step(float) (/home/jtnicholl/godot/source/godot/servers/physics_server_3d_wrap_mt.cpp:41)
[8] CommandQueueMT::Command1<PhysicsServer3DWrapMT, void (PhysicsServer3DWrapMT::*)(float), float>::call() (/home/jtnicholl/godot/source/godot/./core/templates/command_queue_mt.h:322 (discriminator 4))
[9] CommandQueueMT::_flush() (/home/jtnicholl/godot/source/godot/./core/templates/command_queue_mt.h:374)
[10] CommandQueueMT::wait_and_flush() (/home/jtnicholl/godot/source/godot/./core/templates/command_queue_mt.h:414)
[11] PhysicsServer3DWrapMT::thread_loop() (/home/jtnicholl/godot/source/godot/servers/physics_server_3d_wrap_mt.cpp:57)
[12] PhysicsServer3DWrapMT::_thread_callback(void*) (/home/jtnicholl/godot/source/godot/servers/physics_server_3d_wrap_mt.cpp:48)
[13] Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) (/home/jtnicholl/godot/source/godot/core/os/thread.cpp:67)
[14] void std::__invoke_impl<void, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*>(std::__invoke_other, void (*&&)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*&&, Thread::Settings&&, void (*&&)(void*), void*&&) (/usr/include/c++/12/bits/invoke.h:61)
[15] std::__invoke_result<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*>::type std::__invoke<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*>(void (*&&)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*&&, Thread::Settings&&, void (*&&)(void*), void*&&) (/usr/include/c++/12/bits/invoke.h:97)
[16] void std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >::_M_invoke<0ul, 1ul, 2ul, 3ul, 4ul>(std::_Index_tuple<0ul, 1ul, 2ul, 3ul, 4ul>) (/usr/include/c++/12/bits/std_thread.h:252)
[17] std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >::operator()() (/usr/include/c++/12/bits/std_thread.h:259)
[18] std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> > >::_M_run() (/usr/include/c++/12/bits/std_thread.h:210)
[19] /home/jtnicholl/godot/source/godot/bin/godot.linuxbsd.editor.dev.x86_64() [0x72abf13] (thread.o:?)
[20] /lib64/libc.so.6(+0x8ce2d) [0x7f5da728fe2d] (??:0)
[21] /lib64/libc.so.6(+0x1121b0) [0x7f5da73151b0] (??:0)
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

1. Enable threaded 3D physics
2. Open a scene with certain Control nodes
3. Wait, or click around a bit
4. Crash

### Minimal reproduction project

[PhysicsCrash.zip](https://github.com/godotengine/godot/files/9769472/PhysicsCrash.zip)

### PR DESCRIPTION
**Pull request by haasanen**
Fixes #67333, fixes #63671, fixes #63879
May also fix this: #61250

This mutex request fixes a race condition in `WorkerThreadPool` as far as I can tell. The race condition causes an eventual segmentation fault (crash). The comment on the `groups.erase(p_group);` is only true when `physics/3d/run_on_separate_thread` option in the project settings is disabled.

For example, add the following line next to `groups.erase(p_group);`:

```cpp
OS::get_singleton()->print("Thread id: %u\n", Thread::get_caller_id()); // Debug line
groups.erase(p_group); // Threads do not access this, so safe to erase here.
```

If you have `physics/3d/run_on_separate_thread` **disabled**, it prints only a single thread id:
```bash
...
Thread id: 3401590889
Thread id: 3401590889
Thread id: 3401590889
Thread id: 3401590889
Thread id: 3401590889
Thread id: 3401590889
...
```

If you **enable** `physics/3d/run_on_separate_thread`, it prints two thread ids:
```bash
...
Thread id: 3840933713
Thread id: 3840933713
Thread id: 1959143244
Thread id: 3840933713
Thread id: 3840933713
Thread id: 1959143244
Thread id: 3840933713
Thread id: 3840933713
...
```

The same is true if you enable the 2D thread in `physics/2d/run_on_separate_thread`. If you have separate threads enabled for both 2D and 3D, there are still only two thread ids printed.

I understand that this might not be the ideal place to fix the race condition, as the comment on the line suggests that there should not be multiple threads accessing it. However, this does fix the UI crashing in 4.0 beta 3 (or since #63354).

To test this:
1. Create empty project and enable `physics/3d/run_on_separate_thread` in the settings.
2. Save an empty scene with Control node as root.
3. Run project.
4. To speed up crashing (could be a placebo): move your mouse on and off the window. This will create internal events. Within a minute or so, your program crashes without this PR fix.

Or you can run any existing project with the `physics/3d/run_on_separate_thread` enabled and it will crash within minutes without this PR fix.

I'd really appreciate if someone else also verified this as it _works on my machine™_ .

### CODE REVIEW

**Comment by rburing** [comment]
To me the name `run_on_separate_thread` suggests that only *one non-main* thread should be starting those worker thread pools. Using your debug code, can you check if one of the threads is the main thread? If so, we should probably prevent the main thread from starting the worker thread pools in the first place. (I'm no expert on threads, so take my comment with a grain of salt.)

**Comment by jtnicholl** [comment]
I've tested and can confirm this does fix #67333 for me.

File: core/object/worker_thread_pool.cpp [hunk 1]
```diff
@@ -402,7 +402,9 @@ void WorkerThreadPool::wait_for_group_task_completion(GroupID p_group) {
 		}
 	}
 
-	groups.erase(p_group); // Threads do not access this, so safe to erase here.
+	task_mutex.lock(); // This mutex is needed when Physics 2D and/or 3D is selected to run on a separate thread.
+	groups.erase(p_group);
+	task_mutex.unlock();
```
Comment (lyuma) [inline core/object/worker_thread_pool.cpp:407]: I think performance could be improved if that `groups.erase(p_group);` is moved within the matching `task_mutex.lock()` : this will remove possible overhead from doing two locks in a row.
```cpp
	if (group->low_priority_native_tasks.size() > 0) {
		...
		task_mutex.lock();
		group_allocator.free(group);
		groups.erase(p_group);
		task_mutex.unlock();
	} else {
		...
		if (finished_users == max_users) {
			// All tasks using this group are gone (finished before the group), so clear the group too.
			task_mutex.lock();
			group_allocator.free(group);
			groups.erase(p_group);
			task_mutex.unlock();
		} else {
			task_mutex.lock(); // This mutex is needed when Physics 2D and/or 3D is selected to run on a separate thread.
			groups.erase(p_group);
			task_mutex.unlock();
		}
	}
```

Actually... I wonder if the *intent* of the original code might have been that `groups.erase(p_group);` should only happen in the cases where `group_allocator.free(group)` was called, that is to say `if (group->low_priority_native_tasks.size() > 0)` in the original case, or `if (finished_users == max_users)`  in the else. If this is true, I might suggest the following code instead.
```cpp
	if (group->low_priority_native_tasks.size() > 0) {
		...
		task_mutex.lock();
		group_allocator.free(group);
		groups.erase(p_group);
		task_mutex.unlock();
	} else {
		...
		if (finished_users == max_users) {
			// All tasks using this group are gone (finished before the group), so clear the group too.
			task_mutex.lock();
			group_allocator.free(group);
			groups.erase(p_group);
			task_mutex.unlock();
		}
	}
```

**Review by lyuma — DISMISSED** [review]
Argument in favor of the change: every other access to the `groups` array was guarded by `task_mutex`, except this one. The PR locks `task_mutex` around the last and final access.

In the original change, @reduz left a comment `// Threads do not access this, so safe to erase here.` Why, then, was the other access to the `groups` HashMap in this function already guarded by the `task_mutex` lock. I think that inconsistency implies there was a mistake in this function, but I have some questions about the proposed fix. See my comment.

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
This should be fine, performance should not really be an issue in this context.

**Comment by akien-mga** [comment]
Thanks!
