### PR TITLE
Fix Reflection Mask not working on Mobile

### LINKED ISSUE #93173: Mobile Renderer: ReflectionProbe Reflection Masks have no effect
### Tested versions

- Reproducible in: Godot Engine v4.3.beta1.official, and v4.3.beta.custom_build [71699e08c] (Current master).

### System information

Fedora Linux 40.20240613.0 (Silverblue) - Wayland - Vulkan (Mobile) - dedicated AMD Radeon RX 5700 (RADV NAVI10) () - Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 Threads)

### Issue description

Reflection Masks can be used to exclude meshes from being affected by a ReflectionProbe. In the Forward+ and Compatibility backends this works correctly, but not so on the Mobile backend. Meshes are always affected by a ReflectionProbe in Forward Mobile, even when excluded by the Reflection Mask.

I've also tested ReflectionProbe Cull Masks to see if it had similar issues, but it works just fine in the Mobile renderer.

Forward Plus (Working correctly):
gd4MRP-MRPM-Screenshot_ForwardPlus

Forward Mobile (With issues):
gd4MRP-MRPM-Screenshot_Mobile

Compatibility (Working correctly):
gd4MRP-MRPM-Screenshot_Compatibility

### Steps to reproduce

1. Create two MeshInstance3Ds and set one of them to Layer 2.
2. Create a ReflectionProbe and in the Reflection Mask, exclude Layer 2.
3. Set the Ambient Color in the ReflectionProbe to Constant Color and use a bright color to help exaggerate the differences between the two Meshes.
4. Switch between the Forward+ and Mobile backends to see the difference.

### Minimal reproduction project (MRP)

[gd4MRP-MobileReflectionProbeMasks.zip](https://github.com/user-attachments/files/15842498/gd4MRP-MobileReflectionProbeMasks.zip)

### PR DESCRIPTION
**Pull request by SpockBauru**
Closes #93173 
Supersedes #93175 

Fix reflection masks on the mobile renderer according @clayjohn [commnet on the previews attempt](https://github.com/godotengine/godot/pull/93175#pullrequestreview-2138921050). Now it uses RendererSceneCull in order to cull the reflections before calling the shader.

MRP for the picure: 
[reflection_mask_test.zip](https://github.com/user-attachments/files/20214351/reflection_mask_test.zip)

Reflection_Mask

Note: the new [cull_mask overhaul](https://github.com/godotengine/godot/pull/102399/) is great! In 4.4 I did an ugly workaround, now it just works the right way.

### CODE REVIEW

File: servers/rendering/renderer_scene_cull.cpp [hunk 1]
```diff
@@ -212,6 +212,11 @@ void RendererSceneCull::_instance_pair(Instance *p_A, Instance *p_B) {
 		}
 
 	} else if (self->geometry_instance_pair_mask & (1 << RS::INSTANCE_REFLECTION_PROBE) && B->base_type == RS::INSTANCE_REFLECTION_PROBE && ((1 << A->base_type) & RS::INSTANCE_GEOMETRY_MASK)) {
+		if (!(A->layer_mask & RSG::light_storage->reflection_probe_get_reflection_mask(B->base))) {
```
Comment (clayjohn) [inline servers/rendering/renderer_scene_cull.cpp:215]: This code is also needed in `instance_unpair()`

File: servers/rendering/renderer_scene_cull.h [hunk 2]
```diff
@@ -506,7 +506,11 @@ class RendererSceneCull : public RenderingMethod {
 				case Dependency::DEPENDENCY_CHANGED_DECAL:
 				case Dependency::DEPENDENCY_CHANGED_LIGHT:
 				case Dependency::DEPENDENCY_CHANGED_REFLECTION_PROBE: {
-					singleton->_instance_queue_update(instance, true, true);
+					//requires repairing
+					if (instance->indexer_id.is_valid()) {
+						singleton->_unpair_instance(instance);
+						singleton->_instance_queue_update(instance, true, true);
+					}
```
Comment (clayjohn) [inline servers/rendering/renderer_scene_cull.h:513]: Instead of changing the behaviour for mesh, particles, multimesh, decals and lights. You can just move the `case Dependency::DEPENDENCY_CHANGED_REFLECTION_PROBE:` below so that it is with `DEPENDENCY_CHANGED_LIGHT_SOFT_SHADOW_AND_PROJECTOR` and `DEPENDENCY_CHANGED_CULL_MASK`

**Review by clayjohn — CHANGES_REQUESTED** [review]

File: servers/rendering/renderer_scene_cull.cpp (hunk 1 above)
Comment (SpockBauru) [reply servers/rendering/renderer_scene_cull.cpp:215]: Copied and flipped the logic to skip the unpair when the masks match, otherwise it will not unpair when the reflection mask changes:
Reflection_Mask

Comment (clayjohn) [reply servers/rendering/renderer_scene_cull.cpp:215]: I'm not sure I understand what you are saying. Take a look at the other pairing types, like decals, for an example of how this should work

Comment (SpockBauru) [reply servers/rendering/renderer_scene_cull.cpp:215]: Sorry, English is not my native language. Let me try to explain.

In `_instance_unpair` if I skip the unpairing when both masks does **not** match, like the code bellow, the reflection probe will not unpair with the geometry when needed, causing the bug in the picture above where disabling the Reflection Mask does not stop reflections in the geometry:
```
if (!(A->layer_mask & RSG::light_storage->reflection_probe_get_reflection_mask(B->base))) {
	// Early return if the object's layer mask doesn't match the reflection mask.
	return;
}
```

If I flip the logic and skip the unpairing when both masks **does** match, like the code bellow (current PR code), I suspect that the geometry and probe will not be unpaired even when the visibility is set to false, causing performance decrease since the probe will still be updating the invisible geometry:
```
if ((A->layer_mask & RSG::light_storage->reflection_probe_get_reflection_mask(B->base))) {
	// Early return if the object's layer mask matches the reflection mask.
	return;
}
```

If this is true, I believe that for reflection probes is better to not skip the unpairing in `_instance_unpair`.

Comment (clayjohn) [reply servers/rendering/renderer_scene_cull.cpp:215]: Why are ReflectionProbes different from all of the other pairable objects?

Comment (SpockBauru) [reply servers/rendering/renderer_scene_cull.cpp:215]: Because unlike the others ReflectionProbes have 2 masks: The `cull_mask` which is like other pairable objects and handles the reflections on itself, and the `reflection_mask` which handles the reflections on the other objects.

**Comment by SpockBauru** [comment]
While scratching my head on why ReflectionProbes must have inverted logic on` _instance_unpair` otherwise the Reflection Mask will not work, I made a picture to help understand the point of view of one Light instance and one Reflection Probe instance. 

pairing_pov


As you can see in the picture, the Reflection Probes have 3 types of masks instead of 2. The logic for the Cull Mask and Layer Mask is the same as the others, but the logic for the Reflection Mask is reversed! That’s why it does not work like the others!

I hope this picture idea also helps others to follow the logic of the pairing system.

**Comment by clayjohn** [comment]
You are forgetting that lights also have three types of mask:
1. Layer mask (light to camera)
2. Light mask (what meshes are affected by the light)
3. shadow mask (what objects cast shadows) (equivalent to reflection mask)

**Comment by SpockBauru** [comment]
You are absolutely right! I forgot about the shadow mask, it really works like the reflection mask.

It seems that the `shadow_caster_mask` is not handled by the pairing system, but by `_light_instance_update_shadow`.

Should we move the `reflection_mask` handling to another place? Personally, I prefer to handle in the pairing system, but I'm open for suggestions.

**Review by clayjohn — APPROVED** [review]
Looks good to me now!

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected.

Code looks good to me.

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
