### PR TITLE
Fix compilation warnings in macOS build, enable `warnings=extra werror=yes`

### LINKED ISSUE #24418: SemaphorePosix raises deprecation warnings on macOS / iOS
**Godot version:**
Master (4b6e7b5)

**OS/device including version:**
macOS, Xcode 9.4.1 (Travis CI)

**Issue description:**
The following warnings are raised by Xcode against SemaphorePosix:
```
drivers/unix/semaphore_posix.cpp:60:2: warning: 'sem_getvalue' is deprecated [-Wdeprecated-declarations,29]
        sem_getvalue(&sem, &val);
         ^
/Applications/Xcode-9.4.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/usr/include/sys/semaphore.h:54:56: note: 'sem_getvalue' has been explicitly marked deprecated here [2]
 int sem_getvalue(sem_t * __restrict, int * __restrict) __deprecated;
                                                        ^
/Applications/Xcode-9.4.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/usr/include/sys/cdefs.h:176:37: note: expanded from macro '__deprecated'
 #define __deprecated   __attribute__((deprecated))
                                        ^
drivers/unix/semaphore_posix.cpp:77:10: warning: 'sem_init' is deprecated [-Wdeprecated-declarations,29]
        int r = sem_init(&sem, 0, 0);
                 ^
/Applications/Xcode-9.4.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/usr/include/sys/semaphore.h:55:42: note: 'sem_init' has been explicitly marked deprecated here [2]
 int sem_init(sem_t *, int, unsigned int) __deprecated;
                                          ^
/Applications/Xcode-9.4.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/usr/include/sys/cdefs.h:176:37: note: expanded from macro '__deprecated'
 #define __deprecated   __attribute__((deprecated))
                                        ^
drivers/unix/semaphore_posix.cpp:84:2: warning: 'sem_destroy' is deprecated [-Wdeprecated-declarations,29]
        sem_destroy(&sem);
         ^
/Applications/Xcode-9.4.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/usr/include/sys/semaphore.h:53:26: note: 'sem_destroy' has been explicitly marked deprecated here [2]
 int sem_destroy(sem_t *) __deprecated;
                          ^
/Applications/Xcode-9.4.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/usr/include/sys/cdefs.h:176:37: note: expanded from macro '__deprecated'
 #define __deprecated   __attribute__((deprecated))
                                        ^
```

### LINKED ISSUE #24420: BitMap class definition conflicts with macOS Quickdraw.h's BitMap struct
**Godot version:**
Master (4b6e7b5)

**OS/device including version:**
macOS, Xcode 9.4.1 (Travis)

**Issue description:**
The following warning is raised when building with `scons p=osx dev=yes`:
```
./scene/resources/texture.h:91:1: warning: class 'BitMap' was previously declared as a struct [-Wmismatched-tags]
class BitMap;
^
/Applications/Xcode-9.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/QD.framework/Headers/Quickdraw.h:61:8: note: previous use is here
struct BitMap {
       ^
./scene/resources/texture.h:91:1: note: did you mean struct here?
class BitMap;
^~~~~
struct
```

Not sure how to fix it, are we forced to use a namespace to work it around?

### LINKED ISSUE #29799: [TRACKER] Compilation warnings raised on macOS builds
**Godot version:**
3.2 master (5cc1c7d)

**OS/device including version:**
macOS

**Issue description:**
This tracker should list all current warnings raised for macOS builds, specifying when relevant the build options (`tools`, `target`).

The initial set of warnings has been copied from @bruvzg's report on #29033.

If you're a contributor with edit access, please modify the OP directly to add more checkboxes for new/other warnings. If you don't have edit access, you can add them in a comment below.

#### `warnings=all`

With Xcode 10.2.1 (@bruvzg):

- [ ] `tools=yes target=debug` in `scene/resources/texture.h` (more details in #24420)

```
scene/resources/texture.h:91:1: warning: class 'BitMap' was previously declared as a struct [-Wmismatched-tags]
class BitMap;
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/QD.framework/Headers/Quickdraw.h:61:8: note:
      previous use is here
struct BitMap {
       ^
scene/resources/texture.h:91:1: note: did you mean struct here?
class BitMap;
^~~~~
struct
```

- [ ] `tools=yes target=debug` in `drivers/unix/semaphore_posix.cpp` (more details in #24418)

```
drivers/unix/semaphore_posix.cpp:60:2: warning: 'sem_getvalue' is deprecated [-Wdeprecated-declarations]
        sem_getvalue(&sem, &val);
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/semaphore.h:54:56: note: 'sem_getvalue' has been explicitly
      marked deprecated here
int sem_getvalue(sem_t * __restrict, int * __restrict) __deprecated;
                                                       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/cdefs.h:176:40: note: expanded from macro '__deprecated'
#define __deprecated    __attribute__((deprecated))
                                       ^
drivers/unix/semaphore_posix.cpp:77:10: warning: 'sem_init' is deprecated [-Wdeprecated-declarations]
        int r = sem_init(&sem, 0, 0);
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/semaphore.h:55:42: note: 'sem_init' has been explicitly
      marked deprecated here
int sem_init(sem_t *, int, unsigned int) __deprecated;
                                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/cdefs.h:176:40: note: expanded from macro '__deprecated'
#define __deprecated    __attribute__((deprecated))
                                       ^
drivers/unix/semaphore_posix.cpp:84:2: warning: 'sem_destroy' is deprecated [-Wdeprecated-declarations]
        sem_destroy(&sem);
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/semaphore.h:53:26: note: 'sem_destroy' has been explicitly
      marked deprecated here
int sem_destroy(sem_t *) __deprecated;
                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/cdefs.h:176:40: note: expanded from macro '__deprecated'
#define __deprecated    __attribute__((deprecated))
                                       ^
```

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes #29799
Fixes #24420
Fixes #24418
Fixes some of warnings in #29800

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: drivers/unix/os_unix.cpp [hunk 1]
```diff
@@ -126,7 +126,9 @@ void OS_Unix::initialize_core() {
 	RWLockDummy::make_default();
 #else
 	ThreadPosix::make_default();
+#if !defined(OSX_ENABLED)
```
Comment (akien-mga) [inline drivers/unix/os_unix.cpp]: Should we also remove it on `IPHONE_ENABLED` and fix #24418?

Comment (bruvzg) [reply drivers/unix/os_unix.cpp]: Probably, iOS have its own implementation as well: https://github.com/godotengine/godot/blob/master/platform/iphone/os_iphone.cpp#L99, but I have not tested it.

**Comment by bruvzg** [comment]
Huh, this thing seems to be still present on old Xcode (not getting this warning with Xcode 11.1), I'll check it a bit later.

```
./scene/resources/texture.h:88:1: error: class 'BitMap' was previously declared as a struct [-Werror,-Wmismatched-tags]
class BitMap;
^
/Applications/Xcode-9.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/QD.framework/Headers/Quickdraw.h:61:8: note: previous use is here
struct BitMap {
       ^
./scene/resources/texture.h:88:1: note: did you mean struct here?
class BitMap;
^~~~~
struct
```

**Comment by bruvzg** [comment]
`Bitmap` warning (leftovers of PowerPC era API deprecated 15 years ago) seems to be fixed, along with some iOS and MinGW/clang warnings.

* MinGW/clang compiles with `warnings=extra werror=yes` too (tested 32/64-bit release export templates, and 64-bit debug tools builds).
* iOS build still have tons of warnings (mostly deprecated APIs, I have no idea how to fix any of it), only semaphore and few signed/unsigned type mismatches are fixed.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
> iOS build still have tons of warnings (mostly deprecated APIs, I have no idea how to fix any of it), only semaphore and few signed/unsigned type mismatches are fixed.

For those we have many fixes in #22784, but it's stalled and not in a mergeable state :/

**Comment by akien-mga** [comment]
Thanks!

**Comment by follower** [comment]
### Additional context on why `BitMap` conflict occurred

> `Bitmap` warning (leftovers of PowerPC era API deprecated 15 years ago) seems to be fixed

For some additional context, when I was researching this issue for my suggested patch in https://github.com/godotengine/godot/issues/24420#issuecomment-497079269 I also uncovered *why* the different behavior between occurs in pre-10.14 builds.

### Backward-incompatible changes in system header includes

In macOS/Mac OS X 10.13 (and at least back to 10.9) the `CVDisplayLink.h` header includes `ApplicationServices/ApplicationServices.h`:

https://github.com/alexey-lysiuk/macos-sdk/blob/352a0070583ecdde139db5c36a6e0734b86438d3/MacOSX10.13.sdk/System/Library/Frameworks/CoreVideo.framework/Versions/A/Headers/CVDisplayLink.h#L22-L27

But in macOS 10.14 this include was changed to `CoreGraphics/CoreGraphics.h` directly:

https://github.com/alexey-lysiuk/macos-sdk/blob/352a0070583ecdde139db5c36a6e0734b86438d3/MacOSX10.14.sdk/System/Library/Frameworks/CoreVideo.framework/Versions/A/Headers/CVDisplayLink.h#L22-L27

The direct inclusion resulted in far fewer includes as `ApplicationServices.h` previously included [`QD.h`](https://github.com/alexey-lysiuk/macos-sdk/blob/352a0070583ecdde139db5c36a6e0734b86438d3/MacOSX10.13.sdk/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/Headers/QD.h#L37-L39) which includes [`Quickdraw.h`](https://github.com/alexey-lysiuk/macos-sdk/blob/352a0070583ecdde139db5c36a6e0734b86438d3/MacOSX10.13.sdk/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/Headers/Quickdraw.h#L59-L68) where the conflicting `BitMap` can be found.

### Potential for future issues

Apple changing what gets included by long-standing system headers between OS releases means it's plausible odd backward-incompatibilities such as this one may occur again in future. Which is why I thought it was worth documenting this additional context.

In addition, with Apple pushing non-backward compatible changes (such as Metal & 64-bit only support) & seemingly sub-optimal QA practices (such as those that apparently led to the VSync issue that caused the original DisplayLink-related workaround to be created) I think it could be wise to consider making such workarounds version-gated in future.

File: platform/osx/os_osx.h [hunk 2]
```diff
@@ -31,6 +31,8 @@
 #ifndef OS_OSX_H
 #define OS_OSX_H
 
+#define BitMap _QDBitMap // Suppress deprecated QuickDraw definition.
```
Comment (follower) [inline platform/osx/os_osx.h]: FWIW according to my understanding identifiers that begin with an underscore & a capital letter are reserved--their use is considered undefined behavior.

I think it would be more "correct" to just use `QDBitMap` here.

References:

 * "the identifiers that begin with an underscore followed by an uppercase letter are reserved; " in point 3 [here](https://en.cppreference.com/w/cpp/language/identifiers#In_declarations).
 * Point 3 [here](https://en.cppreference.com/w/c/language/identifier#Reserved_identifiers).
 * [GNU C library documentation](https://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html).
 * "[use _ and __ in C programs](https://stackoverflow.com/questions/25090635/use-and-in-c-programs#25090719)" post.
