### PR TITLE
Change how embedded windows are focused

### LINKED ISSUE #50949: Clicking on the titlebar of a embedded window with more than 2 open results in crash
### Godot version

b4778082d1d8afe74eb5900e114b015faab4a526

### System information

Ubuntu Mate

### Issue description

Clicking in the titlebar of a embedded window when there's 3 or more windows of any kind opened will result in a crash.

```
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x41040) [0x7fa4a3beb040] (??:0)
[2] /home/michael/Development/Projects/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x525b8e0] (/home/michael/Development/Projects/godot/scene/main/window.cpp:82)
[3] /home/michael/Development/Projects/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x522c21d] (/home/michael/Development/Projects/godot/scene/main/viewport.cpp:2981)
[4] /home/michael/Development/Projects/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x522cc59] (/home/michael/Development/Projects/godot/scene/main/viewport.cpp:3077)
[5] /home/michael/Development/Projects/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x525f180] (/home/michael/Development/Projects/godot/scene/main/window.cpp:917)
[6] /home/michael/Development/Projects/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x5274ce9] (/home/michael/Development/Projects/godot/./core/object/ref_counted.h:220)
[7] /home/michael/Development/Projects/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x30796b6] (/home/michael/Development/Projects/godot/platform/linuxbsd/display_server_x11.cpp:?)
[8] /home/michael/Development/Projects/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x69c377c] (/home/michael/Development/Projects/godot/./core/object/ref_counted.h:220)
[9] /home/michael/Development/Projects/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x307b796] (/home/michael/Development/Projects/godot/./core/object/ref_counted.h:220)
[10] /home/michael/Development/Projects/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x3066d32] (/home/michael/Development/Projects/godot/platform/linuxbsd/os_linuxbsd.cpp:340)
[11] /home/michael/Development/Projects/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x3062842] (/home/michael/Development/Projects/godot/platform/linuxbsd/godot_linuxbsd.cpp:60)
[12] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xd5) [0x7fa4a3bd2565] (??:0)
[13] /home/michael/Development/Projects/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x30626ce] (??:?)
-- END OF BACKTRACE --
```

Seems like the problem resides in this line:
https://github.com/godotengine/godot/blob/48857194b360dabdaac7cd4c9c6714546ca15aa1/scene/main/viewport.cpp#L2981

### Steps to reproduce

1. Open the project provided below and run it.
2. Right-click the `LineEdit`.
3. Click the titlebar of either window.

### Minimal reproduction project

[popup_crash.zip](https://github.com/godotengine/godot/files/6887425/popup_crash.zip)

### LINKED ISSUE #51445: Position of a dragged embedded window is the same of a previously focused one
### Godot version

511f9619736f47946f3d0613bc2642cf2b47beac

### System information

Ubuntu Mate

### Issue description

When selecting an embedded window, then dragging another one, the position will be in the area of that last focused window. This can be circumvented by clicking in the body of window first, then the titlebar. But if the titlebar is dragged first, the bug happens:

Peek 2021-08-09 14-57

### Steps to reproduce

- Drag around Window 1, see how it moves correctly.
- Then, go directly for the titlebar of Window 2, and drag it around. It will start at the last position you left in Window 1.

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/6956481/Test.zip)

### PR DESCRIPTION
**Pull request by TechnoPorg**
Fixes #50949 and fixes #51445
This PR adds a new struct, `SubWindowFocusSort`, to bring embedded windows to the foreground during rendering.
The previous system was causing two bugs, both to do with the fact that a `Vector` was being changed in `sub_windows_forward_input` without changing a reference to an element in it.
I also removed an unused variable, `Viewport::GUI::embedding_subwindows`.

It's worth noting that this system will currently break if multiple subwindows are focused within the same main loop iteration. I can't see that happening except in quite an unusual situation, but feedback would be appreciated on the matter. I could change it to use a vector, but that would make things slower.

### CODE REVIEW

File: scene/main/viewport.h [hunk 1]
```diff
@@ -584,6 +582,7 @@ class Viewport : public Node {
 	void set_embed_subwindows_hint(bool p_embed);
 	bool get_embed_subwindows_hint() const;
 	bool is_embedding_subwindows() const;
+	static RID *subwindow_needs_focus; // Waiting to be brought to the front by the the renderer
```
Comment (akien-mga) [inline scene/main/viewport.h:585]:
```suggestion
	static RID *subwindow_needs_focus; // Waiting to be brought to the front by the renderer.
```

Comment (akien-mga) [reply scene/main/viewport.h:585]: (Note: I added a dot, and removed a duplicate word.)

File: servers/rendering/renderer_canvas_cull.h [hunk 2]
```diff
@@ -34,6 +34,8 @@
 #include "core/templates/paged_allocator.h"
 #include "renderer_compositor.h"
 #include "renderer_viewport.h"
+#include "rendering_server_globals.h"
+#include "scene/main/viewport.h"
```
Comment (akien-mga) [inline servers/rendering/renderer_canvas_cull.h:38]: Servers shouldn't have dependencies on `scene`, see #53295. So this system might need to be registered in `DisplayServer` I guess?

Though it seems weird that window management ends up in `RendererCanvasCull`, but I'm not familiar with this area.

File: servers/rendering/renderer_canvas_cull.h [hunk 3]
```diff
@@ -163,6 +149,36 @@ class RendererCanvasCull {
...
+				return p_left->ysort_index < p_right->ysort_index;
+			}
+
+			return p_left->ysort_pos.y < p_right->ysort_pos.y;
+		}
+	};
+
+	// Shunts the newly focused embedded window to the foreground, while leaving other items in the same order
+	struct SubWindowFocusSort {
+		 bool operator()(const Item *p_left, const Item *p_right) const {
```
Comment (akien-mga) [inline servers/rendering/renderer_canvas_cull.h:173]: There's a space before `bool` here that should be removed.

File: scene/main/viewport.cpp [hunk 4]
```diff
@@ -370,7 +355,6 @@ void Viewport::_sub_window_remove(Window *p_window) {
 void Viewport::_notification(int p_what) {
 	switch (p_what) {
 		case NOTIFICATION_ENTER_TREE: {
-			gui.embedding_subwindows = gui.embed_subwindows_hint;
```
Comment (akien-mga) [inline scene/main/viewport.cpp:358]: Empty line at start of block should be removed.

**Comment by TechnoPorg** [comment]
I've fixed the formatting stuff, but I agree that it's weird to handle subwindows in `RendererCanvasCull`. A way to provide custom sorts for canvas item children would make it unnecessary and also remove the `scene` dependency I had mistakenly added to `RendererCanvasCull`. Any thoughts?

**Comment by TechnoPorg** [comment]
I've found a 1 character fix for this bug :P 
Again, sorry that everything is taking me so long. This is kind of just symptom fixing, but it's definitely the least complicated option, and I can't see this change introducing any regressions. I'd appreciate feedback on whether it's acceptable.

**Review by YeldhamDev — APPROVED** [review]
Fixes the reported issues.

**Comment by akien-mga** [comment]
Thanks!
