### PR TITLE
Fix completion of parameters in function call

### LINKED ISSUE #58561: GDScript 2.0 Methods' argument autocomplete for variables doesn't popup
### Godot version

v4.0.alpha.calinou [0393057e3]

### System information

Windows 11

### Issue description

Basically, it seems that we have popups which indicate what our parameters are for our method we are calling is like this:
image

but when you start typing, I expect it to also allow me to autocomplete with my existing variables and such, as it does normally like this:
image

But it won't if I'm typing it inside a method
image

### Steps to reproduce

Steps shown above. This can be done with any function requiring parameters.

### Minimal reproduction project

No need for a reproduction.

*Bugsquad edit (keywords for easier searching): autocompletion*

### PR DESCRIPTION
**Pull request by Chaosus**
Fix https://github.com/godotengine/godot/issues/58561

Demo:

gds_bugfix

### CODE REVIEW

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -2948,6 +2948,10 @@ GDScriptParser::ExpressionNode *GDScriptParser::parse_call(ExpressionNode *p_pre
 			push_error(R"(Expected expression as the function argument.)");
 		} else {
 			call->arguments.push_back(argument);
+
+			if (argument->type == Node::IDENTIFIER && current.cursor_place == GDScriptTokenizer::CURSOR_BEGINNING) {
+				completion_context.type = COMPLETION_IDENTIFIER;
+			}
```
Comment (akien-mga) [inline modules/gdscript/gdscript_parser.cpp:2954]: Just commenting what we discussed on chat:

I'm not really familiar with the GDScript parser and completion but this looks a bit like a hack here, as if it's not the right place to do this check. No other code in this function accesses `completion_context` directly as far as I can see.

This looks more like the main loop that calls various other functions to update the completion context so my feeling is that the fix should be done in one of those functions, but again I don't really know much about it, it's just a gut feeling.

It feels like this should maybe set `ct` (and prevent it from being overridden) instead of editing the created completion context?

Would be great if @vnen could confirm, but otherwise it might be fine to merge anyway and it can be refactored later.

Comment (Chaosus) [reply modules/gdscript/gdscript_parser.cpp:2954]: The problem is the argument type and cursor place should be checked, which happened after the creation of context in the `make_completion_context` function and `parse_expression`. Otherwise, the completion would be incorrect.

**Review by akien-mga — APPROVED** [review]
Let's go with this fix for now and if it turns out that it could be done a better way, this can be revisit later.
