### PR TITLE
Android: Fix excessive `getRotation` calls

### LINKED ISSUE #99733: Android ANR in Godot.getRotatedValues
### Tested versions

Reported to Google Play Console from Godot 4.3 

### System information

Android(9,10) - Godot 4.3.stable - compatibility

### Issue description

We've received a few ANR reports in Google Play Console with this callstack:
```
"main" tid=1 Native
  #00  pc 0x000000000001f0ac  /system/lib64/libc.so (syscall+28)
  #01  pc 0x00000000000d7224  /system/lib64/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+148)
  #02  pc 0x000000000051bd30  /system/lib64/libart.so (art::GoToRunnable(art::Thread*) (.llvm.<US_SOCIAL_SECURITY_NUMBER>)+480)
  #03  pc 0x000000000051bb0c  /system/lib64/libart.so (art::JniMethodEnd(unsigned int, art::Thread*)+28)
  at android.os.BinderProxy.transactNative (Native method)
  at android.os.BinderProxy.transact (Binder.java:1129)
  at android.os.ServiceManagerProxy.getService (ServiceManagerNative.java:125)
  at android.os.ServiceManager.rawGetService (ServiceManager.java:253)
  at android.os.ServiceManager.getService (ServiceManager.java:124)
  at android.hardware.display.DisplayManagerGlobal.translateAppSpaceDisplayIdBasedOnCurrentActivity (DisplayManagerGlobal.java:135)
  at android.hardware.display.DisplayManagerGlobal.getDisplayInfo (DisplayManagerGlobal.java:181)
  at android.view.Display.updateDisplayInfoLocked (Display.java:1071)
  at android.view.Display.getRotation (Display.java:750)
  at org.godotengine.godot.Godot.getRotatedValues (Godot.kt:866)
  at org.godotengine.godot.Godot.onSensorChanged (Godot.kt:896)
  at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent (SystemSensorManager.java:833)
  at android.os.MessageQueue.nativePollOnce (Native method)
  at android.os.MessageQueue.next (MessageQueue.java:326)
  at android.os.Looper.loop (Looper.java:160)
  at android.app.ActivityThread.main (ActivityThread.java:6975)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:865)
```

Apparently this line is the trigger of the ANR:
`when (windowManager.defaultDisplay.rotation) {`

Maybe it would be better to listen for screen rotation and save the value in a var, rather then calling windowManager.defaultDisplay.rotation everytime any sensor changes.

Also we don't use sensors anyways and would like to just turn off listening for them to save some cpu and battery. See proposal: https://github.com/godotengine/godot-proposals/discussions/7645#discussioncomment-11389311

### Steps to reproduce

I haven't been able to reproduce

### Minimal reproduction project (MRP)

I think this could happen in any Godot android project because godot is always listening for sensor changes on android.

### PR DESCRIPTION
**Pull request by syntaxerror247**
Fixes https://github.com/godotengine/godot/issues/99733

### CODE REVIEW

File: platform/android/java/lib/src/org/godotengine/godot/Godot.kt [hunk 1]
```diff
@@ -669,6 +669,7 @@ class Godot(private val context: Context) {
 			darkMode = newDarkMode
 			GodotLib.onNightModeChanged()
 		}
+		renderView?.inputHandler?.updateCachedRotation()
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/Godot.kt:672]: Let's create an `onConfigurationChanged` method in `GodotInputHandler` and call that, this way we can keep `updateCachedRotation()` private and not make it part of the public API.

**Review by m4gr3d — CHANGES_REQUESTED** [review]

**Review by m4gr3d — APPROVED** [review]
Looks good!
