### PR TITLE
Fix batch rename for unique name and empty name

### LINKED ISSUE #78290: Batch rename to empty string will behave strangely.
### Godot version

v4.1.beta.custom_build [01453ab7f]

### System information

macOS 13.3.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

When Batch renaming multiple nodes to empty nodes, this will error out instead of using the class name. Moreover item name will be set to empty instead of reverting them back. 

https://github.com/godotengine/godot/assets/66184050/ca8dcd75-a306-428e-87ff-7c39c231d101

### Steps to reproduce

1. create a scene with one root and multiple child nodes
2. batch rename them by replacing N by P
3. batch rename them using regular expression to set them all to empty string (using regular expression `.*`)
4. see errors and bugged out items
5. unselect nodes their name will reappear you can see nothing has been set

### Minimal reproduction project

with MRP you can start at step 3
[Test.zip](https://github.com/godotengine/godot/files/11763532/Test.zip)

### LINKED ISSUE #78291: Batch rename won't check for duplicate unique name
### Godot version

v4.1.beta.custom_build [c0d8d91b1]

### System information

macOS 13.3.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

When batch renaming nodes it won't check for already used unique name. This will lead to the unique name being revoked with those warning. 
Capture d’écran 2023-06-15 à 23 56 06
Expected behavior would be a popup similar to this one being fired when doing the same rename with basic rename and preventing node rename.
Capture d’écran 2023-06-15 à 23 56 21

### Steps to reproduce

1. create a scene with a root two child and one grand child
2. make unique name the scond child and the grand child
3. batch rename the two child to "Node"
4. see the warning and the unique name being revoked

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/11763614/Test.zip)
with MRP start at step 3

### PR DESCRIPTION
**Pull request by ajreckof**
Fixes #78290 
Fixes #78291

### CODE REVIEW

File: editor/gui/scene_tree_editor.h [hunk 1]
```diff
@@ -62,6 +62,7 @@ class SceneTreeEditor : public Control {
 	String filter_term_warning;
 
 	AcceptDialog *error = nullptr;
+	AcceptDialog *error2 = nullptr;
```
[the remark this answers is not in the document]
Comment (ajreckof) [reply editor/gui/scene_tree_editor.h:65]: Both can appear at the same time if the name is invalid it is replacing the invalids characters with `_`. This means if you try to rename a node that is Unique to `Node%` and you already have a unique name called `Node_` it will first tells you there was invalid characters and then tells you this unique name is already used. Right now this specific case make the unique name be revoked even with normal renames because I think it checked them in the wrong order.

I'm not sure about adding a return to the first error as this is not how it behaved previously.

[the remark this answers is not in the document]
Comment (KoBeWi) [reply editor/gui/scene_tree_editor.h:65]: read my edit

**Comment by ajreckof** [comment]
Implemented what kobewi suggested with both it now look like this.
Capture d’écran 2023-06-20 à 23 22 22

File: editor/gui/scene_tree_editor.cpp [hunk 2]
```diff
@@ -968,15 +968,34 @@ void SceneTreeEditor::_rename_node(Node *p_node, const String &p_name) {
 	String new_name = p_name.validate_node_name();
 
 	if (new_name != p_name) {
-		error->set_text(TTR("Invalid node name, the following characters are not allowed:") + "\n" + String::get_invalid_node_name_characters());
-		error->popup_centered();
+		String text = TTR("Invalid node name, the following characters are not allowed:") + "\n" + String::get_invalid_node_name_characters();
+		if (error->is_visible()) {
```
Comment (KoBeWi) [inline editor/gui/scene_tree_editor.cpp:972]: Not sure if this condition is necessary; it's not really something that can happen here.

**Review by KoBeWi — DISMISSED** [review]

File: editor/gui/scene_tree_editor.cpp (hunk 2 above)
Comment (ajreckof) [reply editor/gui/scene_tree_editor.cpp:972]: Unfortunately this can happen with batch rename if one node is erroring because of unique name already in use and another node because of invalid character later.

**Comment by KoBeWi** [comment]
The approach for appending errors needs to be reworked, as it's possible to stack errors from multiple nodes:
image

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` cb73a6e9f9046229a16b6b298c9086f03548e186), it works.

However, I can only confirm the first case (empty node name) is resolved, as I can't test the second issue. [I never see the **Batch Rename** option in the context menu when selecting several nodes](https://github.com/godotengine/godot/issues/78291#issuecomment-1603343062) if both are scene-unique, and this also applies in `master`.

Approving nonetheless, as this is an improvement over the existing situation.

**Comment by KoBeWi** [comment]
> I never see the Batch Rename option in the context menu when selecting several nodes

Batch Rename does not appear if you select a parent and child node together. Likely a bug.

**Comment by ajreckof** [comment]
> > I never see the Batch Rename option in the context menu when selecting several nodes
> 
> Batch Rename does not appear if you select a parent and child node together. Likely a bug.

See #76069

**Comment by YuriSizov** [comment]
Besides a review from @KoBeWi this also needs a rebase.

**Comment by ajreckof** [comment]
So I rebased this. The conflicting fix was about making sure it wouldn't raise an error when renaming a node to the same name when it is an unique name in owner. I moved this fix to the new places from this PR

**Comment by YuriSizov** [comment]
I think the added meta should be prefixed with "_" by convention. Otherwise, this seems to address @KoBeWi's concern, albeit in a rather awkward way. Can't we set the meta and then compose a line by checking for each possible key, instead of doing this nested `if` thing?

File: editor/gui/scene_tree_editor.cpp [hunk 3]
```diff
@@ -964,26 +964,55 @@ void SceneTreeEditor::_rename_node(Node *p_node, const String &p_name) {
...
 	}
 
 	if (new_name == p_node->get_name()) {
 		if (item->get_text(0).is_empty()) {
 			item->set_text(0, new_name);
 		}
+		return;
+	}
 
+	// we previously made sure name is not the same as current name so that it wonn't complain about already used unique name when not changing name
```
Comment (KoBeWi) [inline editor/gui/scene_tree_editor.cpp:999]:
```suggestion
	// We previously made sure name is not the same as current name so that it won't complain about already used unique name when not changing name.
```

File: editor/gui/scene_tree_editor.cpp (hunk 2 above)
Comment (KoBeWi) [reply editor/gui/scene_tree_editor.cpp:968]: > I'll try to show an actual case of it happening tomorrow.

Right...

**Comment by KoBeWi** [comment]
> I think the added meta should be prefixed with "_" by convention.

This convention is irrelevant for internal editor nodes.

**Review by KoBeWi — APPROVED** [review]

File: editor/gui/scene_tree_editor.cpp (hunk 3 above)
Comment (akien-mga) [reply editor/gui/scene_tree_editor.cpp:999]: Poke @ajreckof, would be good to fix this before merging.

**Comment by akien-mga** [comment]
Thanks!
