### PR TITLE
Fix crash when tooltip_request_func object is freed

### LINKED ISSUE #52876: Executing `TextEdit::get_tooltip` crashes Godot
### Godot version

4.0.dev.custom_build. b1063a7c0

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

When executing
```
func _process(delta):
	var temp_variable = TextEdit.new()
	temp_variable.set_tooltip_request_func(RDPipelineDepthStencilState.new(), StringName("."), CollisionShape2D.new())
	temp_variable.set_text(".")
	temp_variable.force_drag(null, HBoxContainer.new())
	temp_variable.set_syntax_highlighter(CodeHighlighter.new())
	temp_variable.get_tooltip(Vector2(36.1853256225586, 6.84734582901001))
```
address sanitizer shows this info
```
==51603==ERROR: AddressSanitizer: heap-use-after-free on address 0x61300002cf90 at pc 0x558c4b265a81 bp 0x7ffdb892de10 sp 0x7ffdb892de00
READ of size 8 at 0x61300002cf90 thread T0
    #0 0x558c4b265a80 in Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) core/object/object.cpp:773
    #1 0x558c43b6c745 in TextEdit::get_tooltip(Vector2 const&) const scene/gui/text_edit.cpp:2399
    #2 0x558c432041a7 in void call_with_variant_args_retc_helper<__UnexistingClass, String, Vector2 const&, 0ul>(__UnexistingClass*, String (__UnexistingClass::*)(Vector2 const&) const, Variant const**, Variant&, Callable::CallError&, IndexSequence<0ul>) core/variant/binder_common.h:699
    #3 0x558c431ef744 in void call_with_variant_args_retc_dv<__UnexistingClass, String, Vector2 const&>(__UnexistingClass*, String (__UnexistingClass::*)(Vector2 const&) const, Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:486
    #4 0x558c431e0855 in MethodBindTRC<String, Vector2 const&>::call(Object*, Variant const**, int, Callable::CallError&) core/object/method_bind.h:546
    #5 0x558c4b266f23 in Object::call(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:832
    #6 0x558c4a95ae6d in Variant::call(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1017
    #7 0x558c3ae5c60d in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1487
    #8 0x558c3a93dee9 in GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1501
    #9 0x558c42a9eb80 in Node::_gdvirtual__process_call(double) scene/main/node.h:232
    #10 0x558c42a16ce4 in Node::_notification(int) scene/main/node.cpp:58
    #11 0x558c34edc2e9 in Node::_notificationv(int, bool) scene/main/node.h:48
    #12 0x558c35d193a2 in CanvasItem::_notificationv(int, bool) scene/main/canvas_item.h:47
    #13 0x558c4275a6a4 in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:37
    #14 0x558c4b267332 in Object::notification(int, bool) core/object/object.cpp:841
    #15 0x558c42b47b69 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:851
    #16 0x558c42b3a202 in SceneTree::process(double) scene/main/scene_tree.cpp:453
    #17 0x558c3474e98d in Main::iteration() main/main.cpp:2561
    #18 0x558c345eaa3c in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:342
    #19 0x558c345d90d3 in main platform/linuxbsd/godot_linuxbsd.cpp:58
    #20 0x7f986aab9564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)
    #21 0x558c345d8c0d in _start (/usr/bin/godot4s+0x32036c0d)

0x61300002cf90 is located 16 bytes inside of 344-byte region [0x61300002cf80,0x61300002d0d8)
freed by thread T0 here:
    #0 0x7f986ba888f7 in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:127
    #1 0x558c49e067ba in Memory::free_static(void*, bool) core/os/memory.cpp:168
    #2 0x558c3502aa7b in void memdelete<RefCounted>(RefCounted*) core/os/memory.h:112
    #3 0x558c4a90ddac in Variant::operator=(Variant const&) core/variant/variant.cpp:2747
    #4 0x558c3ae5ef59 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1595
    #5 0x558c3a93dee9 in GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1501
    #6 0x558c42a9eb80 in Node::_gdvirtual__process_call(double) scene/main/node.h:232
    #7 0x558c42a16ce4 in Node::_notification(int) scene/main/node.cpp:58
    #8 0x558c34edc2e9 in Node::_notificationv(int, bool) scene/main/node.h:48
    #9 0x558c35d193a2 in CanvasItem::_notificationv(int, bool) scene/main/canvas_item.h:47
    #10 0x558c4275a6a4 in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:37
    #11 0x558c4b267332 in Object::notification(int, bool) core/object/object.cpp:841
    #12 0x558c42b47b69 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:851
    #13 0x558c42b3a202 in SceneTree::process(double) scene/main/scene_tree.cpp:453
    #14 0x558c3474e98d in Main::iteration() main/main.cpp:2561
    #15 0x558c345eaa3c in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:342
    #16 0x558c345d90d3 in main platform/linuxbsd/godot_linuxbsd.cpp:58
    #17 0x7f986aab9564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

previously allocated by thread T0 here:
    #0 0x7f986ba88c47 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x558c49e0577b in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x558c49e0568c in operator new(unsigned long, char const*) core/os/memory.cpp:40
    #3 0x558c472cb9c8 in Object* ClassDB::creator<RDPipelineDepthStencilState>() core/object/class_db.h:151
    #4 0x558c4b1f0b24 in ClassDB::instantiate(StringName const&) core/object/class_db.cpp:545
    #5 0x558c3a90a054 in GDScriptNativeClass::instantiate() modules/gdscript/gdscript.cpp:87
    #6 0x558c3a909a3c in GDScriptNativeClass::_new() modules/gdscript/gdscript.cpp:75
    #7 0x558c3a9fb989 in void call_with_variant_args_ret_helper<__UnexistingClass, Variant>(__UnexistingClass*, Variant (__UnexistingClass::*)(), Variant const**, Variant&, Callable::CallError&, IndexSequence<>) core/variant/binder_common.h:648
    #8 0x558c3a9fb3e5 in void call_with_variant_args_ret_dv<__UnexistingClass, Variant>(__UnexistingClass*, Variant (__UnexistingClass::*)(), Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:453
    #9 0x558c3a9faadd in MethodBindTR<Variant>::call(Object*, Variant const**, int, Callable::CallError&) core/object/method_bind.h:455
    #10 0x558c3ae5eefc in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1595
    #11 0x558c3a93dee9 in GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1501
    #12 0x558c42a9eb80 in Node::_gdvirtual__process_call(double) scene/main/node.h:232
    #13 0x558c42a16ce4 in Node::_notification(int) scene/main/node.cpp:58
    #14 0x558c34edc2e9 in Node::_notificationv(int, bool) scene/main/node.h:48
    #15 0x558c35d193a2 in CanvasItem::_notificationv(int, bool) scene/main/canvas_item.h:47
    #16 0x558c4275a6a4 in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:37
    #17 0x558c4b267332 in Object::notification(int, bool) core/object/object.cpp:841
    #18 0x558c42b47b69 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:851
    #19 0x558c42b3a202 in SceneTree::process(double) scene/main/scene_tree.cpp:453
    #20 0x558c3474e98d in Main::iteration() main/main.cpp:2561
    #21 0x558c345eaa3c in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:342
    #22 0x558c345d90d3 in main platform/linuxbsd/godot_linuxbsd.cpp:58
    #23 0x7f986aab9564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

SUMMARY: AddressSanitizer: heap-use-after-free core/object/object.cpp:773 in Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&)

```

This example was found by fuzzer, so I don't recommend trying understand in what situation such code could be used in real project, because such situation probably doesn't exists.

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by timothyqiu**
Fixes #52876.

* Uses `ObjectID` instead of `Object *` to keep track of freed objects.
* The original issue metioned that `CodeEdit` also has this crash, it's because `CodeEdit` inherits from `TextEdit`.

### CODE REVIEW

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -2421,7 +2422,7 @@ String TextEdit::get_tooltip(const Point2 &p_pos) const {
 }
 
 void TextEdit::set_tooltip_request_func(Object *p_obj, const StringName &p_function, const Variant &p_udata) {
-	tooltip_obj = p_obj;
+	tooltip_obj_id = p_obj->get_instance_id();
```
Comment (akien-mga) [inline scene/gui/text_edit.cpp:2425]: Should this check for `p_obj`'s validity first?

Comment (timothyqiu) [reply scene/gui/text_edit.cpp:2425]: Ah, yes 🤣

**Review by akien-mga — APPROVED** [review]
