### PR TITLE
Editor: Inspector and Signal docks improvements

### LINKED ISSUE #64432: GDScript 2.0: `@export_category` interferes with the property inspector tooltip
### Godot version

v4.0.alpha.custom_build [f2a616841]

### System information

Linux

### Issue description

Properties can be documented by giving them a description with `##` comments. That description is then showed as a tooltip in the inspector, like this.
example1

However, any properties following an `@export_category` annotation will only have a "no description" tooltip. 
example2

This bug actually predates `@export_category` and also occurs when using `PROPERTY_USAGE_CATEGORY` directly in `_get_property_list()`.

The problem is that `EditorInspector::update_tree()` assumes that any property with `PROPERTY_USAGE_CATEGORY` either has a `name` that is a class name or a `hint_string` that is a path to a script. And it uses that class/path to look up the description of subsequent properties.

One possible fix is to simply add the required hint string to `@export_category`. I've verified that this works.
```diff
--- a/modules/gdscript/gdscript_parser.cpp
+++ b/modules/gdscript/gdscript_parser.cpp
@@ -3826,6 +3826,7 @@ bool GDScriptParser::export_group_annotations(const AnnotationNode *p_annotation
        switch (t_usage) {
                case PROPERTY_USAGE_CATEGORY: {
                        annotation->export_info.usage = t_usage;
+                       annotation->export_info.hint_string = script_path;
                } break;
```

One downside to that is that the tooltip of the category itself will be the description of the script ("This is a description of the script" in the screenshots above).

I guess the alternative is to change `EditorInspector::update_tree()` which is a 670 line hairy monster.

### Steps to reproduce

See screenshots above.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by dalexeev**
* Continuation of #81092.
* Fixes #64432.

1\. Fixes a part of #78934 (no description for properties after `@export_category`).

There is now a way (`hint_string`) to distinguish type categories from custom categories. This is consistent with scripts, they already use `hint_string`.

https://github.com/godotengine/godot/blob/549fcce5f8f7beace3e5c90e9bbe4335d4fd1476/core/object/object.h#L492

https://github.com/godotengine/godot/blob/549fcce5f8f7beace3e5c90e9bbe4335d4fd1476/core/object/script_language.cpp#L124

```gdscript
extends Node
@export var a: int
@export_category("Node")
@export var b: int
```

Also we can make the background a bit less bright than normal categories.

2\. Added a tooltip when hovering a class item in the Signal dock, to be consistent with the Inspector.

3\. Added "Open Documentation" context menu for classes to Inspector and Signal docks.

4\. Fixed a bug with displaying incorrect tooltips for callback items.

Before:

After:

5\. Fixed a bug where descriptions could be truncated if they contain `::` (the `maxsplit` argument for `String.split()` is now specified)

### CODE REVIEW

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -2729,6 +2761,7 @@ void EditorInspector::update_tree() {
 	// Get the lists of editors for properties.
 	for (List<PropertyInfo>::Element *E_property = plist.front(); E_property; E_property = E_property->next()) {
 		PropertyInfo &p = E_property->get();
+		print_line(p.name);
```
Comment (YuriSizov) [inline editor/editor_inspector.cpp:2764]: 👀

File: editor/editor_inspector.cpp [hunk 2]
```diff
@@ -2801,6 +2834,14 @@ void EditorInspector::update_tree() {
 			main_vbox->add_child(category);
 			category_vbox = nullptr; //reset
 
+			// `hint_script` should contain a native class name or a script path.
+			// Otherwise the category was probably added via `@export_category` or `_get_property_list()`.
+			if (p.hint_string.is_empty()) {
+				category->label = p.name;
+				category->set_tooltip_text(p.name);
+				continue; // Do not add an icon, do not change the current class (`doc_name`).
```
Comment (YuriSizov) [inline editor/editor_inspector.cpp:2842]: This was a pretty useful hack, btw, as a way to add icons to categories you could define dummy classes with the same name. But I guess now you can just pass the hint string with `_get_property_list`?

File: editor/connections_dialog.cpp [hunk 3]
```diff
@@ -994,11 +998,11 @@ void ConnectionsDock::_tree_item_selected() {
 		connect_button->set_text(TTR("Connect..."));
 		connect_button->set_icon(get_theme_icon(SNAME("Instance"), SNAME("EditorIcons")));
 		connect_button->set_disabled(true);
-	} else if (_is_item_signal(*item)) {
+	} else if (_get_item_type(*item) == TREE_ITEM_TYPE_SIGNAL) {
 		connect_button->set_text(TTR("Connect..."));
 		connect_button->set_icon(get_theme_icon(SNAME("Instance"), SNAME("EditorIcons")));
 		connect_button->set_disabled(false);
-	} else {
+	} else if (_get_item_type(*item) == TREE_ITEM_TYPE_CONNECTION) {
```
Comment (YuriSizov) [inline editor/connections_dialog.cpp:1005]: Should there still be the default branch that disables the button? In case if the class item is selected, I guess.

**Review by YuriSizov — APPROVED** [review]
Just a debug print and a bit of cleaning, but code looks good otherwise.

The addition of the hint string seems safe to me, as far as core changes are.

File: editor/editor_inspector.cpp (hunk 2 above)
Comment (dalexeev) [reply editor/editor_inspector.cpp:2841]: Yes, you can still use the hack if you specify a `hint_string`. But property descriptions will be missing or incorrect.

<details>
<summary>Example</summary>

```gdscript
extends Node
@export var a: int
@export_category("Label")
@export var text: int ## Test desc.
```

Before:


After:


</details>

The inspector cannot distinguish between standard properties and added in `_get_property_list()`. But the solution fixes the `@export_category` issue since `hint_string` is empty in this case. We probably shouldn't have added the annotation at all, but people will continue to use it despite the note in the docs.

> Categories in the Inspector dock's list usually divide properties coming from different classes (Node, Node2D, Sprite, etc.). For better clarity, it's recommended to use `@export_group` and `@export_subgroup`, instead.

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Comment by akien-mga** [comment]
Thanks!
