### PR TITLE
Fix macOS .NET export.

### LINKED ISSUE #66702: MacOS: Unable to export - Failed to publish dotnet project
### Godot version

4.0beta-2

### System information

MacOS 12.6, x86_64

### Issue description

I am unable to export C# based projects in Godot4.0 beta.
I am exporting using the macOS export template and selecting the .app format.

Exporting a project that only makes use of GDScript works just fine with the same steps, however as soon as a C# script is added it fails with the error message (via popup) "Failed to publish .NET project".

Interestingly the game can be played just fine by pressing cmd + b, or cmd + r and playing in the editor.

Looking in the MSBuild output window shows this error:

```
Running:  /usr/local/share/dotnet/dotnet publish /Users/maxfletcher/GodotProjects/Example/Example.sln -c ExportDebug -r osx-x86 --self-contained true -v normal "-l:GodotTools.BuildLogger.GodotBuildLogger,/Applications/Godot_mono 4.0-beta2.app/Contents/MacOS/../Resources/GodotSharp/Tools/GodotTools.BuildLogger.dll;/Users/maxfletcher/Library/Application Support/Godot/mono/build_logs/3d83d5d84e96b16a9281e565e9ef1c27_ExportDebug" -p:GodotTargetPlatform=macos -o /var/folders/76/njcgdlq537s30g3f27l4ljt00000gn/T/godot-publish-dotnet/12071-ExportDebug-osx-x86
MSBuild version 17.3.1+2badb37d1 for .NET
Build started 01/10/2022 12:39:59.
     1>Project "/Users/maxfletcher/GodotProjects/Example/Example.sln" on node 1 (Restore target(s)).
     1>ValidateSolutionConfiguration:
         Building solution configuration "ExportDebug|Any CPU".
       _GetAllRestoreProjectPathItems:
         Determining projects to restore...
     1>Project "/Users/maxfletcher/GodotProjects/Example/Example.sln" (1) is building "/Users/maxfletcher/GodotProjects/Example/Example.csproj" (2:4) on node 1 (_GenerateRestoreGraphProjectEntry target(s)).
     2>/usr/local/share/dotnet/sdk/6.0.401/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1083: The specified RuntimeIdentifier 'osx-x86' is not recognized. [/Users/maxfletcher/GodotProjects/Example/Example.csproj]
     2>Done Building Project "/Users/maxfletcher/GodotProjects/Example/Example.csproj" (_GenerateRestoreGraphProjectEntry target(s)) -- FAILED.
     1>Done Building Project "/Users/maxfletcher/GodotProjects/Example/Example.sln" (Restore target(s)) -- FAILED.

Build FAILED.

       "/Users/maxfletcher/GodotProjects/Example/Example.sln" (Restore target) (1) ->
       "/Users/maxfletcher/GodotProjects/Example/Example.csproj" (_GenerateRestoreGraphProjectEntry target) (2:4) ->
       (ProcessFrameworkReferences target) -> 
         /usr/local/share/dotnet/sdk/6.0.401/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1083: The specified RuntimeIdentifier 'osx-x86' is not recognized. [/Users/maxfletcher/GodotProjects/Example/Example.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.69
```

Its Interesting it mentions the platform osx-x86 is not recognised, shouldnt this be osx-x64? As far as i can tell the list of supported runtime identifiers for dotnet project does not include osx-x86 and i cant see it mentioned in the [runtime.json ](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.NETCore.Platforms/src/runtime.json) file in the dotnet repo. Also apple themselves dropped support for 32 bit apps years ago as far as I am aware.

### Steps to reproduce

- Create a new project using the mono/dotnet version of Godot4.0
- Create an empty scene
- Add a c# script to the root node of the scene
- Create an export profile for macOS using the default settings
- Select a location for the exported project
- Click export project and select the .app export option
- Export the project

### Minimal reproduction project

[Example.zip](https://github.com/godotengine/godot/files/9690204/Example.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
- Fix incorrect file placement, search paths and architecture detection.
- Automatically detect executable files and set +x flag.
- Automatically apply "Disable Library Validation" entitlements when required.
- Remove old Mono export code.
- Fix folder tree creation for shared objects export.
- Add arch suffix to the exported .NET "data" folder name (for all platforms).
- Remove old Mono code from .NET "data" folder lookup.

Fixes https://github.com/godotengine/godot/issues/66702

### CODE REVIEW

File: modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs [hunk 1]
```diff
@@ -111,62 +113,80 @@ private void _ExportBeginImpl(string[] features, bool isDebug, string path, long
...
+                        "Publish succeeded but project assembly not found in the output directory");
+                }
+
+                // Add to the exported project sharead object list.
+
+                foreach (string file in Directory.GetFiles(publishOutputTempDir, "*", SearchOption.AllDirectories))
+                {
+                    if (platform == OS.Platforms.MacOS)
+                    {
+                        AddSharedObject(file, tags: null, Path.Combine("Contents", "Resources", DetermineDataDirNameForProject() + "_" + arch));
```
Comment (raulsntos) [inline modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs:183]: Nitpick but the call to `DetermineDataDirNameForProject` could be done outside the for loop, may also want to use string interpolation instead of concatenation to avoid some string allocations.

```csharp
$"{DetermineDataDirNameForProject()}_{arch}"
```

File: modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs [hunk 2]
```diff
@@ -198,6 +218,11 @@ public override void _ExportEnd()
             if (Directory.Exists(aotTempDir))
                 Directory.Delete(aotTempDir, recursive: true);
 
+            foreach (string folder in tempFolders)
+            {
+                Directory.Delete(folder, recursive: true);
+            }
```
Comment (raulsntos) [inline modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs:224]: Don't we also need to clear the `tempFolders` list after this?

File: modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs [hunk 3]
```diff
@@ -17,6 +17,8 @@ namespace GodotTools.Export
 {
     public partial class ExportPlugin : EditorExportPlugin
     {
+        private List<string> tempFolders = new List<string>();
```
Comment (raulsntos) [inline modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs:20]: Nit: our naming convention is prefix private class fields with an underscore (`_tempFolders`).

File: modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs [hunk 4]
```diff
@@ -111,62 +113,80 @@ private void _ExportBeginImpl(string[] features, bool isDebug, string path, long
...
+
+                if (!File.Exists(Path.Combine(publishOutputTempDir, $"{GodotSharpDirs.ProjectAssemblyName}.dll"))
+                    // NativeAOT shared library output
+                    && !File.Exists(Path.Combine(publishOutputTempDir, $"{GodotSharpDirs.ProjectAssemblyName}.{soExt}")))
+                {
+                    throw new NotSupportedException(
+                        "Publish succeeded but project assembly not found in the output directory");
+                }
+
+                // Add to the exported project sharead object list.
```
Comment (raulsntos) [inline modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs:177]: Typo.

```suggestion
                // Add to the exported project shared object list.
```

File: modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs [hunk 5]
```diff
@@ -111,62 +113,78 @@ private void _ExportBeginImpl(string[] features, bool isDebug, string path, long
...
+                    throw new NotSupportedException(
+                        "Publish succeeded but project assembly not found in the output directory");
+                }
+
+                // Add to the exported project shared object list.
+
+                foreach (string file in Directory.GetFiles(publishOutputTempDir, "*", SearchOption.AllDirectories))
+                {
+                    AddSharedObject(file, tags: null, projectDataDirName);
+                }
```
Comment (neikeq) [inline modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs:187]: How does this part work? Will it copy all files to `projectDataDirName`? Or only shared objects?

Comment (bruvzg) [reply modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs:187]: It will copy all files, ensure it's copied after extracting template, and sign native libs / executables.

**Review by neikeq — APPROVED** [review]
Looks good.

**Comment by akien-mga** [comment]
Thanks!
