### PR TITLE
Fix extension registration order.

### LINKED ISSUE #50031: Error `Condition "int32_t(p_level) != level" is true.` when running command `godot4 --version`
### Godot version

4.0.dev.custom_build. bb409efa1

### System information

Ubuntu 21.04

### Issue description

`godot4 --version`
```
4.0.dev.custom_build.bb409efa1
ERROR: Condition "int32_t(p_level) != level" is true.
   at: deinitialize_extensions (core/extension/native_extension_manager.cpp:101)
```

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by poiati**
Fixes https://github.com/godotengine/godot/issues/50031. This is the second patch, the [first one](https://github.com/godotengine/godot/pull/58196/files) broke GDExtensions and had to be reverted.

I have tested this with the demo extension we have under `godot-cpp`.

### CODE REVIEW

**Comment by Sauermann** [comment]
adf80b4 works fine for me: I can load GDExtensions.

File: main/main.cpp [hunk 1]
```diff
@@ -1115,7 +1115,6 @@ Error Main::setup(const char *execpath, int argc, char *argv[], bool p_second_ph
 		goto error;
 	}
 #endif
-
```
Comment (akien-mga) [inline main/main.cpp:1118]: This line and the one removed above are not related to this change and IMO useful for readability, so I'd prefer if they were not removed in this PR.

File: core/extension/native_extension.cpp [hunk 2]
```diff
@@ -297,7 +297,7 @@ NativeExtension::InitializationLevel NativeExtension::get_minimum_library_initia
 }
 void NativeExtension::initialize_library(InitializationLevel p_level) {
 	ERR_FAIL_COND(library == nullptr);
-	ERR_FAIL_COND(p_level <= int32_t(level_initialized));
+	ERR_FAIL_COND_MSG(p_level <= int32_t(level_initialized), "Level '" + itos(p_level) + "' must be higher than the current level: '" + itos(level_initialized) + "'");
```
Comment (akien-mga) [inline core/extension/native_extension.cpp:300]: You can use `vformat` to simplify:
```suggestion
	ERR_FAIL_COND_MSG(p_level <= int32_t(level_initialized),
			vformat("Level '%d' must be higher than the current level '%d'.", p_level, level_initialized));
```
(Didn't check if it would require explicit casting from enum to int but since `itos` worked without I think it should not be needed.)

**Comment by akien-mga** [comment]
Might be good to check how #58350 might affect this.

**Comment by kidrigger** [comment]
#58350 changes a small issue with index usage at https://github.com/godotengine/godot/blob/91a57b5b6a567ff10e30f4c0f1385c78e39ca284/core/extension/native_extension_manager.cpp#L49-L51 and https://github.com/godotengine/godot/blob/91a57b5b6a567ff10e30f4c0f1385c78e39ca284/core/extension/native_extension_manager.cpp#L73-L75

Shouldn't conflict.

File: core/extension/native_extension.cpp (hunk 2 above)
Comment (poiati) [reply core/extension/native_extension.cpp]: Far better. Thank you!

**Comment by poiati** [comment]
> #58350 changes a small issue with index usage at
> 
> https://github.com/godotengine/godot/blob/91a57b5b6a567ff10e30f4c0f1385c78e39ca284/core/extension/native_extension_manager.cpp#L49-L51
> 
> and
> https://github.com/godotengine/godot/blob/91a57b5b6a567ff10e30f4c0f1385c78e39ca284/core/extension/native_extension_manager.cpp#L73-L75
> 
> Shouldn't conflict.

I also tested the demo with both PR's merged and it works.

**Comment by akien-mga** [comment]
Tested with the godot-cpp test project (with headers updated to latest upstream `master`) and it seems to work fine (I did get a GDScript crash on first import but that's not related to the changes in this PR).

CC @mhilbrunner @groud would be good if you can test on your GDExtension project too.

**Comment by mhilbrunner** [comment]
I can confirm this fixes the issue and does not seem to impact any of our GDExtension projects negatively. Found no issues. :)

**Comment by kidrigger** [comment]
I can confirm the fix works on the VideoStream extension I'm working on.

**Review by bruvzg — APPROVED** [review]
Seems to be working fine with TextServer GDExtensions.

**Comment by akien-mga** [comment]
Thanks!
