### PR TITLE
C#: Implement `ExportPlugin::_get_name` and move `GLOBAL_DEF` to CSharpLanguage

### LINKED ISSUE #71608: Error when exporting .NET project
### Godot version

4.0.beta13

### System information

Mageia 9, Linux

### Issue description

When exporting a trivial .NET project with 4.0.beta13, I get the following error:

```
ERROR: Required virtual method EditorExportPlugin::_get_name must be overridden before calling.
   at: _gdvirtual__get_name_call (editor/export/editor_export_plugin.h:123)
```

It doesn't seem to prevent exporting, but should be fixed anyway.

On the first export attempt (not be reproducible in my MRP, needs to be redone from scratch), it also shows this warning:
```
WARNING: Property not found: dotnet/project/assembly_name
     at: get_setting_with_override (core/config/project_settings.cpp:364)
```
Which likely means that we're using `GLOBAL_GET` before we defined the property with `GLOBAL_DEF`.

### Steps to reproduce

- Create a simple project with a hello world C# script
- Export it from Linux to Linux or Windows (didn't test other combinations, would likely have the same issue)
- Check Output dock / console

### Minimal reproduction project

[TestMono.zip](https://github.com/godotengine/godot/files/10445350/TestMono.zip)

### PR DESCRIPTION
**Pull request by raulsntos**
- Fixes https://github.com/godotengine/godot/issues/71608.
- Also documents the .NET project settings.

### CODE REVIEW

File: modules/mono/csharp_script.cpp [hunk 1]
```diff
@@ -113,6 +113,9 @@ void CSharpLanguage::init() {
 	BindingsGenerator::handle_cmdline_args(cmdline_args);
 #endif
 
+	GLOBAL_DEF("dotnet/project/assembly_name", "");
+	GLOBAL_DEF("dotnet/project/solution_directory", "");
```
Comment (raulsntos) [inline modules/mono/csharp_script.cpp:117]: I moved it to the `CSharpLanguage` constructor but the `GDMono` constructor also seems like a good place to me. GDScript seems to register some properties in the `GDScriptLanguage` constructor which is what made me go with `CSharpLanguage`.

Comment (neikeq) [reply modules/mono/csharp_script.cpp:117]: This is the right place. The solution dir property could be surrounded with `TOOLS_ENABLED`.

File: modules/mono/editor/GodotTools/GodotTools/Internals/GodotSharpDirs.cs [hunk 2]
```diff
@@ -48,12 +48,6 @@ public static string DataEditorToolsDir
             }
         }
 
-        public static void RegisterProjectSettings()
-        {
-            GlobalDef("dotnet/project/assembly_name", "");
-            GlobalDef("dotnet/project/solution_directory", "");
-        }
```
Comment (neikeq) [inline modules/mono/editor/GodotTools/GodotTools/Internals/GodotSharpDirs.cs:55]: I still don't understand why this wasn't working. It should be called at the start of the editor.

**Review by neikeq — APPROVED** [review]

File: modules/mono/editor/GodotTools/GodotTools/Internals/GodotSharpDirs.cs (hunk 2 above)
Comment (raulsntos) [reply modules/mono/editor/GodotTools/GodotTools/Internals/GodotSharpDirs.cs:55]: `GDMono::_load_project_assembly` tries to get `dotnet/project/assembly_name`. AFAIK, in order to enable the plugin, which is implemented in C#, we need to load the assembly so that gets called first.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
