### PR TITLE
GDScript: Fix crash with `GDScriptNativeClass`

### LINKED ISSUE #82255: Godot Crashes Immediately Upon Opening Project
### Godot version

4.2-dev5

### System information

Windows 11 - Ryzen 7 5800x - RX7900XTX

### Issue description

I have a project that I created and have been working on in 4.0, then 4.1. No issues between the two versions. The project still works fine in both versions. However, in 4.2-dev5, the project will not even open, and crashes with the following error.

image

Screenshot 2023-09-24 130432
Screenshot 2023-09-24 130408

### Steps to reproduce

Not sure how I could upload reproduction steps without sharing my entire game, so I've linked the full project below.

### Minimal reproduction project

[See this. ](https://drive.google.com/file/d/1Uzjte8vv5ZZAx7UVB9m1zmGWzB5OmbeI/view?usp=drive_link)

### PR DESCRIPTION
**Pull request by dalexeev**
* Fixes #82255.

### CODE REVIEW

File: modules/gdscript/gdscript_compiler.cpp [hunk 1]
```diff
@@ -104,7 +104,8 @@ GDScriptDataType GDScriptCompiler::_gdtype_from_datatype(const GDScriptParser::D
 			if (p_handle_metatype && p_datatype.is_meta_type) {
 				result.kind = GDScriptDataType::NATIVE;
 				result.builtin_type = Variant::OBJECT;
-				result.native_type = GDScriptNativeClass::get_class_static();
+				//result.native_type = GDScriptNativeClass::get_class_static();
+				result.native_type = Object::get_class_static(); // GH-82255.
```
Comment (akien-mga) [inline modules/gdscript/gdscript_compiler.cpp:108]: There's no detailed explanation on #82255 of why this caused a crash and what's the effect of doing this change here. So might be worth discussing in this PR / maybe clarifying as a comment.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
