### PR TITLE
Fixed Tileset editor button having the wrong text and not being translatable

### LINKED ISSUE #14601: Tileset option button says "Theme" instead of "Tileset"
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 Beta - Windows

Just a minor thing I noticed.
When you're editing a TileSet resource manually, the button to add and remove tiles is named incorrectly.

[Here's an image of it](https://imgur.com/a/Xsmp9)

(Also, the button is a few pixels too low)

### PR DESCRIPTION
**Pull request by YeldhamDev**
Fixes #14601.

### CODE REVIEW

File: editor/plugins/tile_set_editor_plugin.cpp [hunk 1]
```diff
@@ -244,7 +244,7 @@ TileSetEditor::TileSetEditor(EditorNode *p_editor) {
 	MenuButton *options = memnew(MenuButton);
 	panel->add_child(options);
 	options->set_position(Point2(1, 1));
```
Comment (akien-mga) [inline editor/plugins/tile_set_editor_plugin.cpp]: What's the point of this? It makes it offset and unaligned.

Comment (MarianoGnu) [reply editor/plugins/tile_set_editor_plugin.cpp]: "Theme" button used to be at the bottom of the viewport, in an unreachable place, i dont know why, it was almost imposible to click, i moved it to the toolbar when was working on autotiles, this code is most probably from before o moved it, so just remove that line imo.
