### PR TITLE
Auto-expand current node type when changing node type

### LINKED ISSUE #26389: Changing node type should auto-expand to its current node type
**Godot version:** 3.1 beta 8

**OS/device including version:** Linux, but any/all

**Issue description:**

When I go to change a node's type, the chances are very high that I'm going to be changing it to a similar type. For example, changing a RigidBody to KinematicBody. I am very unlikely to change a RigidBody into a Control or an AnimationPlayer. Therefore, it would make sense to make the "Change Node Type" menu default to having the current type as expanded.

But currently, the "Change Node Type" menu only starts with Node and CanvasItem expanded, so I have to click open Spatial -> CollisionObject -> PhysicsBody to get where I want. This isn't ideal.

Bonus: Changing a type should expand itself, for example, changing a Spatial should auto-expand Spatial, and changing a RigidBody should expand itself to show VehicleBody, etc.

This is very low-priority. Suggested tags: usability, enhancement, topic:editor.

**Steps to reproduce:**

1. Create a node of type RigidBody.

2. Try to change it to KinematicBody.

3. Notice that you have to click through several expandables to get there.

### PR DESCRIPTION
**Pull request by matzebond**
This should fix #26389 :-)

I implemented 'Uncollapsing a `Tree` to show a `TreeItem` deep in the hierarchy' in `CreateDialog`.
I think this functionality should be in `Tree` but I'm not sure if i overlooked something.

### CODE REVIEW

**Comment by aaronfranke** [comment]
@matzebond Can you rebase this?

**Comment by matzebond** [comment]
@aaronfranke done and still working :)

File: editor/create_dialog.cpp [hunk 1]
```diff
@@ -258,6 +259,27 @@ bool CreateDialog::_is_class_disabled_by_feature_profile(const StringName &p_cla
...
+void CreateDialog::select_type(const String &p_type) {
+	TreeItem *to_select;
+	if (search_options_types.has(p_type)) {
+		to_select = search_options_types[p_type];
+	} else {
+		to_select = search_options->get_root();
+	}
+
+	// uncollapse from selected type to top level
+	// TODO: should this be in tree?
```
Comment (aaronfranke) [inline editor/create_dialog.cpp]: This TODO should be looked at by Godot devs before merging.

**Review by aaronfranke — APPROVED** [review]
I can confirm that this PR fixes the problem in https://github.com/godotengine/godot/issues/26389. It looks like a pretty nice implementation, better than https://github.com/godotengine/godot/pull/27202, since the new functionality is mostly in a method.

**Comment by akien-mga** [comment]
Thanks!
