### PR TITLE
[Web] Fix Web MouseWheel scrolling

### LINKED ISSUE #105925: [Web] Scrolling is very sensitive/jumpy when using mac Trackpad
### Tested versions

- Reproducible in master and latest official builds too.

### System information

Godot v4.5.dev3 - macOS Sequoia (15.3.2) - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - Apple M1 Max - Apple M1 Max (10 threads)

### Issue description

When I run my project on MacOS (15.3.2) scrolling (ScrollContainer) is smooth. But when I export the project to the Web, the scrolling becomes very jumpy and almost unusable. I'm using my integrated macbook Trackpad but same thing happen with the Magic Trackpad. This happens on Chrome, Safari and Firefox.

### Steps to reproduce

Scroll the container [here](https://belote.live)

### Minimal reproduction project (MRP)

https://belote.live you can test it here. 

[scrolling-issue.zip](https://github.com/user-attachments/files/19968354/scrolling-issue.zip)

### PR DESCRIPTION
**Pull request by adamscott**
Adds some defined factors for scrolling depending on the scroll mode. Seems to fix most of the issues.

Fixes #105925

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Code looks good to me. I didn't test this on my end, but this was confirmed to be working by @roughbits01 in https://github.com/godotengine/godot/issues/105925#issuecomment-2877161666.

File: platform/web/display_server_web.cpp [hunk 1]
```diff
@@ -665,21 +665,44 @@ int DisplayServerWeb::_mouse_wheel_callback(double p_delta_x, double p_delta_y)
 	ev->set_ctrl_pressed(input->is_key_pressed(Key::CTRL));
 	ev->set_meta_pressed(input->is_key_pressed(Key::META));
 
+	enum DeltaMode {
+		DELTA_MODE_PIXEL = 0,
+		DELTA_MODE_LINE = 1,
+		DELTA_MODE_PAGE = 2,
+	};
```
Comment (adamscott) [inline platform/web/display_server_web.cpp:672]: @Calinou I added an enum here instead of relying on raw integers in the switch/case.

Comment (Calinou) [reply platform/web/display_server_web.cpp:672]: Looks good!

**Comment by Repiteo** [comment]
Thanks!
