### PR TITLE
Fix AudioStreamPlayer3D stereo panning issue

### LINKED ISSUE #103989: AudioStreamPlayer3D spatial panning problem
### Tested versions

Reproducible in 4.4

### System information

Godot v4.4.stable (77dcf97d8) - NixOS #1-NixOS SMP PREEMPT_DYNAMIC Thu Sep 12 09:13:13 UTC 2024 on X11 - X11 display driver, Multi-window, 1 monitor - OpenGL 3 (Compatibility) - Mesa Intel(R) Graphics (ADL GT2) - 12th Gen Intel(R) Core(TM) i5-1240P (16 threads)

### Issue description

The purpose of this issue is to draw together the observations of a bug found here https://github.com/godotengine/godot/pull/103655#issuecomment-2708225574 and argue about what the solution is, of which this PR https://github.com/godotengine/godot/pull/103926 is but one possibility.

By orbiting an `AudioStreamPlayer3D` around an `AudioListener3D` in the horizontal plane and plotting the amplitude of the AudioEffectCaptured left and right channels on a polar graph (see the project below), one gets the following graphs:

|Panning Strength=1  | Panning Strength=0.3
|-------------------------|------------------------------|
|Image | Image |

This is definitely wrong.  Aside from being weird, this diagram contradicts the documentation under [panning strength](https://docs.godotengine.org/en/stable/classes/class_projectsettings.html#class-projectsettings-property-audio-general-3d-panning-strength):

>A value of 0.0 disables stereo panning entirely, leaving only volume attenuation in place. A value of 1.0 completely mutes one of the channels if the sound is located exactly to the left (or right) of the listener.
>The default value of 0.5 is tuned for headphones. When using speakers, you may find lower values to sound better as speakers have a lower stereo separation compared to headphones.

Clearly, reducing the panning strength is increasing the stereo separation, especially around the two misplaced nodes at 45 degrees to the backward facing vector.

Now, I have identified to source of the bug (use of an algorithm designed for 7.1 surround sound for stereo sound with the wrong speaker positions), but what is the correct answer? 

Let's check what happens on other platforms.

**Web Audio (W3C)**

This platform is fully documented because it is a standard.  It is reasonable to expect that the designers will want it to conform to conform to main stream conventions.

The specification for [PannerNode "equalpower" Panning](https://webaudio.github.io/web-audio-api/#Spatialization-equal-power-panning) is described thus:

>This is a simple and relatively inexpensive algorithm which provides basic, but reasonable results. It is used for the PannerNode when the panningModel attribute is set to "equalpower", in which case the elevation value is ignored. 

In this case the `azimuth` is to the angle of the listener facing forwards.  Anything outside of the -90 to 90 region is behind the listener and mirrored to the front: 

```C++
if (azimuth < -90)
    azimuth = -180 - azimuth;
else if (azimuth > 90)
    azimuth = 180 - azimuth;

if (azimuth <= 0)
    x = (azimuth + 90) / 90;
else
    x = azimuth / 90;

gainL = cos(x * Math.PI / 2);
gainR = sin(x * Math.PI / 2);
```

**Unity**

I have not found the explicit documentation for this, so instead I collected the data of the sound intensity in each ear as the camera rotates around in the horizontal plane and looks up and looks down.

| Horizontal Camera Vector  | Volume intensity polar plot
|--------------|-------------|
| Image | Image|

The orange and blue fuzzy lines are the measured data.  The red and green lines are the polar plots of `cos(t/2)` and `sin(t/2)`, the same as the implementation I found in the UE code.  It's a close match, although I have not been able to account for the discrepancy.

**Unreal Engine**

The public [Spatialization Overview documentation](https://dev.epicgames.com/documentation/en-us/unreal-engine/spatialization-overview-in-unreal-engine) for Unreal Engine describes panning as "the oldest and simplest way to simulate spatialization".  

The computation is diagrammed for four speakers, but when there are two speakers they are 180 degrees on opposite sides of the head.  The panning value for the left speaker is `X/180` where `X` is the horizontal angle between the vector to the sound source and the vector that is perpendicular to your left ear.  The panning value for the right speaker is then `1-X`, which is consistent.

To convert this value to "equal power panning" such that the sum of the squares of volume/gain in each ear is constant (because kinetic energy is the square of the velocity) they offer the choice of a "square-root panning law" or the "cosine panning law".

Their "cosine panning law" where `left_volume=cos(X)`, `right_volume=sin(X)` agrees with the documented Web.Audio behavior and the observed Unity behavior.  Confirmation that the elevation angle to the sound source is ignored is provided by the section titled "The Problem of Vector Flipping".

**Proposed implementation for Godot**

There are very good reasons not to depart from the default implementation given by these three established platforms in the stereo case.  This includes their choice to ignore the elevation value, which is not how I would do it.  

However, we can use some school mathematics to implement this calculation as follows without the use of trig functions:

```C++
// inputs
Vector3 to_source;
Vector3 listener_up;  // eg (0,1,0)
Vector3 listener_ear; // eg (1,0,0)

// calculation
Vector3 to_source_projected = to_source - listener_up*(listener_up.dot(to_source));
float cos_asimuth = listener_ear.dot(to_source_projected)/to_source_projected.length();
float cos_asimuth_by_two = sqrt(cos_asimuth + 1)/2); // using cos(t) = 2*cos(t/2)^2 - 1
return cos_asimuth_by_two;
```

**More advanced implementations**

All these platforms have the facility for a more advanced HRTF (Head-Related Transform Function) implementation, even the [webaudio platform](https://webaudio.github.io/web-audio-api/#Spatialization-hrtf-panning).  However UE and Unity do it with a plugin extension, and so should we since it is would otherwise involve some code bloat for a feature that is predominantly required for VR.

Unity seems to implement the `panning_strength` feature by blending this stereo calculation with the mono (same) value using a lerp, which is a good answer.

Let's just fix this by implementing it in the industry standard way so that everything else that builds upon it works.

### Steps to reproduce

See below

### Minimal reproduction project (MRP)

[amplitudepanning.zip](https://github.com/user-attachments/files/19189811/amplitudepanning.zip)

### PR DESCRIPTION
**Pull request by goatchurchprime**
Fixes: https://github.com/godotengine/godot/issues/103989
Incorporates: https://github.com/godotengine/godot/pull/103856
Supersedes: https://github.com/godotengine/godot/pull/103926

This is implemented as suggested in the issue by separating out the `SPEAKER_MODE_STEREO` as a special case and calling `_calc_output_vol_stereo()` instead of `_calc_output_vol()`.  

Obviously the handling of the stereo case in `_calc_output_vol()` is now redundant.  However, I don't think it is wise to touch I cannot test.  Either I've got to get access to a 7.1 speaker arrangement, or use https://github.com/godotengine/godot/pull/103655 or find some other viable method to fake the existence of high numbers of speakers on my development system.

Also the I believe documentation is the wrong way round regarding panning_strength on speakers vs headphones.  It's okay to set the panning strength to 1.0 with speakers since you can hear both speakers with both ears.  However it can be unpleasant for headphones to have one side entirely muted.

### CODE REVIEW

**Comment by AThousandShips** [comment]
Please give the PR a more descriptive title of what the issue is and/or how it is solved

**Comment by AThousandShips** [comment]
You also need to update your base branch, you are months behind and you have conflicts

**Comment by AThousandShips** [comment]
Still needs a rebase as it's got conflicts

**Comment by goatchurchprime** [comment]
Rebased and tested on linux and Windows and against [steam-audio](https://github.com/stechyo/godot-steam-audio).  

(Steam-audio is a very worthwhile addon to refer to since it effectively removes the pressure to implement super-advanced audio features whilst we address the many issues in the base system.)

I've pushed my interactive [amplitudepanning project](https://github.com/goatchurchprime/amplitudepanning/tree/main) that makes it easier to test and verify the changes.  You can run it with and without the PR to witness how the 3D spatial audio has evolved.  

The polar graph of the captured volume in each ear is animated during the measurement, which makes it a lot easier to comprehend.

image

File: scene/3d/audio_stream_player_3d.cpp [hunk 1]
```diff
@@ -144,6 +146,17 @@ void AudioStreamPlayer3D::_calc_output_vol(const Vector3 &source_dir, real_t tig
 	}
 }
 
+// set the volume to cosine of half the angle from the source to the left/right speaker direction ignoring elevation
+// panning_strength<1 moves the cosx value towards 0 till the ratio of the speakers equals it
```
Comment (unvermuthet) [inline scene/3d/audio_stream_player_3d.cpp:150]: You could link to the WebAudio Stereo Panning algorithm you referenced here, too.

And also adhere to the Godot comment style :)

**Review by unvermuthet — CHANGES_REQUESTED** [review]
I like the documentation changes you made. Seems even clearer to me now than in last week's audio meeting.

File: scene/3d/audio_stream_player_3d.cpp [hunk 2]
```diff
@@ -449,10 +462,18 @@ Vector<AudioFrame> AudioStreamPlayer3D::_update_panning() {
...
-		// Bake in a constant factor here to allow the project setting defaults for 2d and 3d to be normalized to 1.0.
-		float tightness = cached_global_panning_strength * 2.0f;
-		tightness *= panning_strength;
-		_calc_output_vol(local_pos.normalized(), tightness, output_volume_vector);
+
+		if (AudioServer::get_singleton()->get_speaker_mode() == AudioServer::SPEAKER_MODE_STEREO) {
+			output_volume_vector.write[0] = _calc_output_vol_stereo(local_pos, cached_global_panning_strength * panning_strength);
+			output_volume_vector.write[1] = AudioFrame(0, 0);
+			output_volume_vector.write[2] = AudioFrame(0, 0);
+			output_volume_vector.write[3] = AudioFrame(0, 0);
```
[the remark this answers is not in the document]
Comment (goatchurchprime) [reply scene/3d/audio_stream_player_3d.cpp:470]: They're not frames.  They are the volume levels for the other 6 of the 8 channels that are supported by the system.  Even though they should not be used, I followed the example in `_calc_reverb_vol()` of not leaving them uninitialized.

File: scene/3d/audio_stream_player_3d.cpp (hunk 1 above)
Comment (goatchurchprime) [reply scene/3d/audio_stream_player_3d.cpp:150]: What's the Godot comment style?  This isn't something picked up in the linter?

Comment (Mickeon) [reply scene/3d/audio_stream_player_3d.cpp:150]: [Begin with an uppercase character, end with an end mark (usually period)](https://docs.godotengine.org/en/stable/contributing/development/code_style_guidelines.html#comment-style-guide)

File: scene/3d/audio_stream_player_3d.cpp [hunk 3]
```diff
@@ -144,6 +146,18 @@ void AudioStreamPlayer3D::_calc_output_vol(const Vector3 &source_dir, real_t tig
 	}
 }
 
+// Set the volume to cosine of half horizontal the angle from the source to the left/right speaker direction ignoring elevation.
+// Then scale `cosx` so that greatest ratio of the speaker volumes is `1-panning_strength`.
+// See https://github.com/godotengine/godot/issues/103989 for evidence that this is the most standard implementation.
```
Comment (unvermuthet) [inline scene/3d/audio_stream_player_3d.cpp:151]: A reference would be enough. I don’t see a reason to “prove” this to future readers. It’s just the way the wording comes off, so not that important.

**Review by unvermuthet — APPROVED** [review]

**Review by adamscott — APPROVED** [review]
Reviewed during the audio team meeting. Looks great! Thank you so much!

**Comment by akien-mga** [comment]
Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by Repiteo** [comment]
Thanks!
