### PR TITLE
[Windows] Fix transient windows not working in the full-screen mode.

### LINKED ISSUE #57184: 4.0 alpha 1 problem with editor in full screen mode
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

w10 64 radeon vega 8

### Issue description
Video capture in full screen mode seems to have problems but I guess they are out of Godot's control, the screen will go completely black at times.

When you go full screen and hold your cursor for a description (on the button to play the scene) these things appear
You will need to pause the video at 0:00:07 (at 7 seconds) and look at the top edge of the window, then continue playback and note at 0:00:11 that the error message appeared.

https://user-images.githubusercontent.com/19652075/150949542-a3ce103a-03a8-47a5-87be-9e644ef5b11c.mp4

Captura2

### Steps to reproduce

Enter in full screen mode
Hover (and hold) the cursor over the play scene icon to get the description.

### Minimal reproduction project

...

### PR DESCRIPTION
**Pull request by bruvzg**
- [Windows] Add  WS_BORDER flag to windows in WINDOW_MODE_FULLSCREEN mode to allow multi-window interface in full-screen.
- [Windows] Add WINDOW_MODE_EXCLUSIVE_FULLSCREEN without WS_BORDER flag enabled (no multi-window support).

Seems like there's no way to consistently display other windows over the exclusive full-screen window. But it's possible to do it by adding a border to the full-screen window (see https://doc.qt.io/qt-5/windows-issues.html#fullscreen-opengl-based-windows for example).

Single pixel border is OK for the editor UI or other GUI apps, but probably is not desired for games and disables exclusive full-screen mode, which can affect performance, so I have added an extra function to enable/disable it.

Fixes #57184

### CODE REVIEW

File: servers/display_server.h [hunk 1]
```diff
@@ -241,6 +241,8 @@ class DisplayServer : public Object {
 	virtual int64_t window_get_native_handle(HandleType p_handle_type, WindowID p_window = MAIN_WINDOW_ID) const;
 
 	virtual WindowID get_window_at_screen_position(const Point2i &p_position) const = 0;
+	virtual void set_allow_child_windows_in_fullscreen(bool p_allow){};
```
Comment (akien-mga) [inline servers/display_server.h:244]:
```suggestion
	virtual void set_allow_child_windows_in_fullscreen(bool p_allow) {}
```

Comment (akien-mga) [reply servers/display_server.h:244]: I should probably report this as a bug upstream for clang-format though.

File: servers/display_server.cpp [hunk 2]
```diff
@@ -390,6 +390,9 @@ void DisplayServer::_bind_methods() {
 	ClassDB::bind_method(D_METHOD("get_window_list"), &DisplayServer::get_window_list);
 	ClassDB::bind_method(D_METHOD("get_window_at_screen_position", "position"), &DisplayServer::get_window_at_screen_position);
 
+	ClassDB::bind_method(D_METHOD("set_allow_child_windows_in_fullscreen", "allow"), &DisplayServer::set_allow_child_windows_in_fullscreen);
+	ClassDB::bind_method(D_METHOD("get_allow_child_windows_in_fullscreen"), &DisplayServer::get_allow_child_windows_in_fullscreen);
```
Comment (akien-mga) [inline servers/display_server.cpp:394]: This could be a property I guess.

Comment (bruvzg) [reply servers/display_server.cpp:394]: That's gonna be the only property in the `DisplayServer`, maybe it better to add another window mode instead, like `WINDOW_MODE_FULLSCREEN` and `WINDOW_MODE_EXCLUSIVE_FULLSCREEN`?

Comment (bruvzg) [reply servers/display_server.cpp]: Changed it to `WINDOW_MODE_FULLSCREEN` (new behavior, with single pixel border) and `WINDOW_MODE_EXCLUSIVE_FULLSCREEN` (old behavior, with black flash on mode change, and no child windows).

File: servers/display_server.h [hunk 3]
```diff
@@ -53,7 +53,8 @@ class DisplayServer : public Object {
 		WINDOW_MODE_WINDOWED,
 		WINDOW_MODE_MINIMIZED,
 		WINDOW_MODE_MAXIMIZED,
-		WINDOW_MODE_FULLSCREEN
+		WINDOW_MODE_FULLSCREEN,
+		WINDOW_MODE_EXCLUSIVE_FULLSCREEN
```
Comment (akien-mga) [inline servers/display_server.h:57]: You could add a trailing comma to prepare for potential future additions.

File: doc/classes/ProjectSettings.xml [hunk 4]
```diff
@@ -1413,7 +1413,6 @@
 			"DEFAULT" and "GodotPhysics2D" are the same, as there is currently no alternative 2D physics server implemented.
 		</member>
 		<member name="physics/2d/run_on_separate_thread" type="bool" setter="" getter="" default="false">
-			If [code]true[/code], the 2D physics server runs on a separate thread, making better use of multi-core CPUs. If [code]false[/code], the 2D physics server runs on the main thread. Running the physics server on a separate thread can increase performance, but restricts API access to only physics process.
```
Comment (akien-mga) [inline doc/classes/ProjectSettings.xml:1416]: These two were removed by mistake it seems.

File: doc/classes/DisplayServer.xml [hunk 5]
```diff
@@ -900,6 +900,11 @@
 			Fullscreen window mode. Note that this is not [i]exclusive[/i] fullscreen. On Windows and Linux, a borderless window is used to emulate fullscreen. On macOS, a new desktop is used to display the running project.
 			Regardless of the platform, enabling fullscreen will change the window size to match the monitor's size. Therefore, make sure your project supports [url=$DOCS_URL/tutorials/rendering/multiple_resolutions.html]multiple resolutions[/url] when enabling fullscreen mode.
 		</constant>
+		<constant name="WINDOW_MODE_EXCLUSIVE_FULLSCREEN" value="4" enum="WindowMode">
+			Exclusive fullscreen window mode. This mode is implemented on Windows only. On other platforms, it is equivalent to [constant WINDOW_MODE_FULLSCREEN].
+			Only one window can enter exclusive fullscreen mode, when window is in exclusive fullscreen mode, child window can not be displayed.
```
Comment (akien-mga) [inline doc/classes/DisplayServer.xml:905]:
```suggestion
			Only one window can enter exclusive fullscreen mode. When a window is in exclusive fullscreen mode, child windows can not be displayed.
```

File: doc/classes/Window.xml [hunk 6]
```diff
@@ -398,6 +398,11 @@
 			Fullscreen window mode. Note that this is not [i]exclusive[/i] fullscreen. On Windows and Linux, a borderless window is used to emulate fullscreen. On macOS, a new desktop is used to display the running project.
 			Regardless of the platform, enabling fullscreen will change the window size to match the monitor's size. Therefore, make sure your project supports [url=$DOCS_URL/tutorials/rendering/multiple_resolutions.html]multiple resolutions[/url] when enabling fullscreen mode.
 		</constant>
+		<constant name="MODE_EXCLUSIVE_FULLSCREEN" value="4" enum="Mode">
+			Exclusive fullscreen window mode. This mode is implemented on Windows only. On other platforms, it is equivalent to [constant MODE_FULLSCREEN].
+			Only one window can enter exclusive fullscreen mode, when window is in exclusive fullscreen mode, child window can not be displayed.
```
Comment (akien-mga) [inline doc/classes/Window.xml:403]:
```suggestion
			Only one window can enter exclusive fullscreen mode. When a window is in exclusive fullscreen mode, child windows can not be displayed.
```

File: doc/classes/DisplayServer.xml (hunk 5 above)
Comment (akien-mga) [reply doc/classes/DisplayServer.xml:905]: BTW, what happens if a user sets exclusive mode to one window, and then attempts to set it to another? Does the second `window_set_mode` call override the first, or is the second window's mode ignored?

**Review by akien-mga — APPROVED** [review]

File: doc/classes/DisplayServer.xml (hunk 5 above)
Comment (bruvzg) [reply doc/classes/DisplayServer.xml:905]: It's a bit imprecise description. It is possible to set exclusive mode for multiple windows (and useful to do it on multiple screens). Setting another one to exclusive mode is fine, it will bring it to the front and hide the first one.
I guess I'll change it to:
```
Only one window in exclusive fullscreen mode at a time can be simultaneously visible on a screen.
```

Comment (akien-mga) [reply doc/classes/DisplayServer.xml:905]: Sounds good, maybe:
```
Only one window in exclusive fullscreen mode can be visible on a given screen at a time. If multiple windows are in exclusive fullscreen mode for the same screen, the last one being set to this mode takes precedence.
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by mhilbrunner** [comment]
FYI, this may have caused https://github.com/godotengine/godot/issues/57831.

**Comment by Calinou** [comment]
Does this PR mean Godot supports exclusive fullscreen on Windows now? If so, is it used by default when fullscreen is enabled?
