### PR TITLE
memdelete the node in AnimationTreePlayer.remove_node

### LINKED ISSUE #51189: Memory leak when using `AnimationTreePlayer.add_node`
### Godot version

3.4.beta.custom_build. 7c1ee0488

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

When executing
```
func _process(delta):
	var temp_variable = AnimationTreePlayer.new()
	temp_variable.add_node(1, ".")
	temp_variable.remove_node(".")
	temp_variable.queue_free()
	get_tree().quit()
```

Godot leaks memory:
```
=================================================================
==47354==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7f3e0786ac47 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x12110223 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x12110134 in operator new(unsigned long, char const*) core/os/memory.cpp:40
    #3 0xea36295 in AnimationTreePlayer::add_node(AnimationTreePlayer::NodeType, StringName const&) scene/animation/animation_tree_player.cpp:932
    #4 0xeac0082 in MethodBind2<AnimationTreePlayer::NodeType, StringName const&>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:1523
    #5 0x11bb651d in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:918
    #6 0x11e3e88f in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1173
    #7 0x1e36ed7 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1034
    #8 0x1c679d2 in GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1166
    #9 0xc3db82b in Node::_notification(int) scene/main/node.cpp:56
    #10 0x1b132bb in Node::_notificationv(int, bool) scene/main/node.h:45
    #11 0x1b15730 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:162
    #12 0xdfcef9e in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:37
    #13 0x11bb69b7 in Object::notification(int, bool) core/object.cpp:927
    #14 0xc50ed31 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:973
    #15 0xc4ff2bf in SceneTree::idle(float) scene/main/scene_tree.cpp:528
    #16 0x1966be1 in Main::iteration() main/main.cpp:2140
    #17 0x1840a64 in OS_X11::run() platform/x11/os_x11.cpp:3638
    #18 0x17abd8b in main platform/x11/godot_x11.cpp:55
    #19 0x7f3e068ed564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)


```

This example was found by fuzzer, so I don't recommend trying understand in what situation such code could be used in real project, because such situation probably doesn't exists.

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by timothyqiu**
Fixes #51189

* The node is `memnew`ed inside `add_node` and kept in `node_map`
* Every pointer inside `node_map` will be `memdelete`d in the destructor of `AnimationTreePlayer`
* But calling `remove_node` only removes the pointer from `node_map` without deleting it.

### CODE REVIEW

File: scene/animation/animation_tree_player.cpp [hunk 1]
```diff
@@ -1314,6 +1314,7 @@ void AnimationTreePlayer::remove_node(const StringName &p_node) {
 		}
 	}
 
+	memdelete(node_map[p_node]);
```
Comment (akien-mga) [inline scene/animation/animation_tree_player.cpp:1317]: Is there a risk that the node could have been freed manually before this, which could lead to double-free?

Comment (timothyqiu) [reply scene/animation/animation_tree_player.cpp:1317]: The actual pointer is not exposed to the outside of `AnimationTreePlayer`, users refer to a node by a string id when calling the API.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
