### PR TITLE
Priorize Embedded PCKs on loading

### LINKED ISSUE #37568: Export project to windows reuses existing files from previous export
**Godot version:** v3.2.1

**OS/device including version:** Win 10

**Issue description:** Exporting to windows does not rebuild the game, but reuses previously exported game code

**Steps to reproduce:**
1. send "this is a test" to stdout using print
1. create an export present for HTML, set the export path to "dist/test.html"
1. create an export present for windows, set the flag "Embed Pck" [x] and set the export path to "dist/test.exe"
1. click on "export all" and export in debug mode
1. test the exported executable to see if "this is a test" is shown
1. now change the text to "this is another test"
1. export the game just for windows using the "export project" button
1. when saving the file, godot should tell you that the file does already exist
1. confirm to overwrite that file
1. test the exported executable and still see the old text
1. export all presents at once, test the binary - and see that the text has finally changed

**expected behaviour**
- When exporting a single present, it should rebuild the binary completly using the current game code

**Minimal reproduction project:**
[godot-exporttest.zip](https://github.com/godotengine/godot/files/4430371/godot-exporttest.zip)

screencast of how to reproduce the problem:
2020-04-04_011254_x_jZcf

My guess is, that the pck file from the HTML export is somehow reused instead of recreated when exporting to windows only. The problem does not occure if I export all presents, if I have different names in the export paths, or if I do not activate "Embed Pck".

### PR DESCRIPTION
**Pull request by HaSa1002**
Fixes #37568

### CODE REVIEW

File: core/project_settings.cpp [hunk 1]
```diff
@@ -368,21 +368,6 @@ Error ProjectSettings::_setup(const String &p_path, const String &p_main_pack, b
...
-		} else {
-			// If we couldn't find them next to the executable, we attempt
-			// the current working directory. Same story, two tests.
-			if (_load_resource_pack(exec_basename + ".pck") ||
-					_load_resource_pack(exec_filename + ".pck")) {
-				found = true;
-			}
-		}
-
 #ifdef OSX_ENABLED
```
Comment (bruvzg) [inline core/project_settings.cpp:371]: This check should be moved with the rest of code.

Comment (HaSa1002) [reply core/project_settings.cpp]: done.

File: core/project_settings.cpp [hunk 2]
```diff
@@ -368,34 +368,32 @@ Error ProjectSettings::_setup(const String &p_path, const String &p_main_pack, b
...
-		}
 #endif
 
-		// Attempt with PCK bundled into executable
-		if (!found) {
-			if (_load_resource_pack(exec_path)) {
+			// Try to load data pack at the location of the executable
+			// As mentioned above, we have two potential names to attempt
+
+			if (_load_resource_pack(exec_dir.plus_file(exec_basename + ".pck")) ||
```
Comment (bruvzg) [inline core/project_settings.cpp:387]: And this part probably should be wrapped in `if (!found)` or it will load pack from the exec_dir on top of embedded.

Comment (HaSa1002) [reply core/project_settings.cpp:387]: That is in the `!found` block. I moved the `OSX_ENABLED` block into the `!found` block and removed `! found` inside the `ifdef`

Comment (HaSa1002) [reply core/project_settings.cpp:387]: Oh my mistake. wait

Comment (bruvzg) [reply core/project_settings.cpp:387]: Each one should be it the separate (!found) block to run if the previous one failed.

Comment (HaSa1002) [reply core/project_settings.cpp:389]: done. I oversaw that, when I moved the `ifdef`

Comment (HaSa1002) [reply core/project_settings.cpp:389]: in theory we could get rid of the `if (... || ...) found = true`and set it directly, but I don't know if'd break style conventions there.

**Comment by HaSa1002** [comment]
Should I change the `if (... || ...) found = true` to `found = ...`? since I already touch it. We would get rid of three ifs and add one new `!found`.

**Comment by akien-mga** [comment]
> Should I change the `if (... || ...) found = true` to `found = ...`? since I already touch it. We would get rid of three ifs and add one new `!found`.

I guess that would make sense yeah.

**Comment by HaSa1002** [comment]
Done

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.
