### PR TITLE
Fix 8 bone weights in glTF2

### LINKED ISSUE #49399: 8 weights isn't working from gltf2 and causes a slow loop
**Godot version:**
On custom engine.

Master is currently at a194397.

**OS/device including version:**
Win10, vulkan, RTX 3000 series Nvidia

**Issue description:**
Godot Engine loses 8 weights in glTF2 document.

Loading the glb appears to be a infinite loop, but it's just very slow.

Incoming pr.

Will try to reproduce on master. Can recreate.

**Steps to reproduce:**
Import glb.

**Minimal reproduction project:**
[8 Weights Project.zip](https://github.com/godotengine/godot/files/6611473/8.Weights.Project.zip)

### PR DESCRIPTION
**Pull request by fire**
Don't spam in glTF2 import either.

Clear() in SurfaceTool does not keep 8 weights.

Fixes: https://github.com/godotengine/godot/issues/49399

### CODE REVIEW

File: scene/resources/surface_tool.cpp [hunk 1]
```diff
@@ -542,7 +542,10 @@ Array SurfaceTool::commit_to_arrays() {
 				for (uint32_t idx = 0; idx < vertex_array.size(); idx++) {
 					const Vertex &v = vertex_array[idx];
 
-					ERR_CONTINUE(v.bones.size() != count);
+					if (v.bones.size() > count) {
+						ERR_PRINT(vformat("Invalid bones size %s vs count %s", itos(v.bones.size()), itos(count)));
```
Comment (akien-mga) [inline scene/resources/surface_tool.cpp:546]: You can use `%d` as placeholder for integers, then you don't need `itos()`.

File: scene/resources/surface_tool.cpp [hunk 2]
```diff
@@ -542,7 +542,10 @@ Array SurfaceTool::commit_to_arrays() {
 				for (uint32_t idx = 0; idx < vertex_array.size(); idx++) {
 					const Vertex &v = vertex_array[idx];
 
-					ERR_CONTINUE(v.bones.size() != count);
+					if (v.bones.size() > count) {
```
Comment (akien-mga) [inline scene/resources/surface_tool.cpp:545]: If `v.bones.size() < count`, the indexing in the next `for` loop will segfault, no?

Comment (fire) [reply scene/resources/surface_tool.cpp:545]: What do you mean? 

count is either 4 or 8.

v.bones.size() is a number from 0 to +infinity.

uint32_t idx = 0; idx < vertex_array.size(); idx++

first iteration is:

1. idx = 0
2. Let's assume the bone size is 7
3. 	```for (int j = 0; j < count; j++) {
		w[idx * count + j] = v.bones[j];
	}```
4. idx = idx + 1` from `uint32_t idx = 0; idx < vertex_array.size(); idx++`

The second iteration is:

5. idx is 1
6. Let's assume the bone size is 6
7. ```for (int j = 0; j < count; j++) {
		w[idx * count + j] = v.bones[j];
	}```
8. idx = idex + 1 ` from `uint32_t idx = 0; idx < vertex_array.size(); idx++`

Comment (fire) [reply scene/resources/surface_tool.cpp:546]: Added an `array.fill(0)` line.

**Review by phocodes — APPROVED** [review]

File: scene/resources/surface_tool.cpp (hunk 2 above)
Comment (fire) [reply scene/resources/surface_tool.cpp:546]: I think this is correct. Please comment if there are concerns.

**Review by reduz — APPROVED** [review]
