### PR TITLE
Fix performance for godot's interface

### LINKED ISSUE #12391: Tilemap edition has slower framerate than usual
Godot 3.0 Windows 10 64 bits
nVidia 940M

I noticed a very slow framerate when editing tilemaps (just panning or moving the tile cursor is enough to notice).
Here is a video where  I try to show it (watch til the end):

https://www.youtube.com/watch?v=trGway9DoqU

You can clearly see that the 3D editor runs smoother, and the 2D editor also runs smoother if the tilemap isn't selected. Checking "update always" improves framerate a bit (cc #11030) but in this case it isn't the only factor.

Repro:
Create a tilemap with a simple tileset and select it to bring up the editor, notice slowdown even before drawing tiles. It looks like it happens when the tile cursor moves, but I'm not sure.

### LINKED ISSUE #19864: [Regression] TileMap response time with mouse it's very bad
**Godot version:**
3852c5f8a0b439a8c0c6e72433d6fe82e3e596de

**OS/device including version:**
Linux 4.17.3

**Issue description:**
It's very bad to work with tilemap because response time is horrible.
In 3.0.4 the response time is good enough.

In my project, the cpu goes to 100% of usage and it's very unusable.

**Steps to reproduce:**
Create a simple TileMap and see the delay on response with your mouse cursor.
Video: https://youtu.be/-kiq_HEtvdc

**Minimal reproduction project:**
Just create a simple TileMap, ~you don't even need to have a TileSet~ you need a TileSet, even if it's empty.

### PR DESCRIPTION
**Pull request by guilhermefelipecgs**
Make godot performance great again :)

Fix #19864, Fix #12391.

This fix isn't only for TileMap, it's for all control nodes. All interface now is very smooth when doing resizing.

This was a regression from changes that I made here #19334.

### CODE REVIEW

File: scene/gui/item_list.cpp [hunk 1]
```diff
@@ -942,6 +942,7 @@ void ItemList::_notification(int p_what) {
 				}
 			}
 
+			minimum_size_changed();
```
Comment (guilhermefelipecgs) [inline scene/gui/item_list.cpp]: FYI, I'm adding this because ItemList don't update minimum size when adding/modifying/etc and I don't want a regression in the about dialog.

**Comment by akien-mga** [comment]
> Fix #12391

Does it really fix this one? It was reported before 3.0 stable was released, so it can't be caused by #19334.

**Comment by guilhermefelipecgs** [comment]
Actually this has been fixed here 005b69cf6e276209464cc8c36ebc7376679925b6 by @reduz, "-Changed UI resizing code, gained huge amount of speed.", but this new improvements only exists on master and I unintentionally created a regression of his changes.

But to be sure, I've tested this problem on stable and master branch with my patch and I can clearly see a big difference. After this patch, I can't notice any delays. I can move the 2D viewport with the tilemap selected and the performance remains the same as moving the screen without selecting it.

**Comment by Zylann** [comment]
I noticed the slowdown back then on a laptop, so if you have a powerful computer you may indeed not have seen the difference, so it needs to be tested on weaker computers (refer to the video I posted in https://github.com/godotengine/godot/issues/12391 to see the amplitude of the difference).

**Comment by guilhermefelipecgs** [comment]
@Zylann I saw your video and I was able to reproduce the problem in all stable branchs, the lag is there! and after this pr fixed for me. You can try in an older machine and if you think this not fixed your issue, feel free to reopen it.

**Comment by guilhermefelipecgs** [comment]
I also did a simple "benchmark" test here, monitoring the cpu usage when working with TileMap and without it, and I can't see any noticeable difference, cpu usage is the same here (with this pull request).

**Comment by Zylann** [comment]
@guilhermefelipecgs are you referring to the newer lag or the one I had back in #12391 ? (it sounds like they are two different occurences of lag getting worse)

**Comment by guilhermefelipecgs** [comment]
I'm referring of what you reported in #12391. 

The "new lag" is kind of the same as you had in #12391, but much worse and technically the cause for both issues is different, but now both cases was fixed.
