### PR TITLE
Make editing properties more intuitive in VisualShader

### LINKED ISSUE #9183: Focus the input field in Visual Shader when the field is clicked on and make it disappear on Enter press.
### Describe the project you are working on

Not important.

### Describe the problem or limitation you are having in your project

When working in visual shaders when you want to type in a number you always need to click on the field you want to change (obviously ;-)) but then a new input field pop up appears and you need to click on that too and then change the value there and then press enter to confirm the value and then press outside the pop up input box to make it disappear.

Changing one or two values doesn't seem like much but when you keep iterating and/or having more values the unnecessary clicks around really do get obnoxious.

In the image you can see the field with number 1 of the Clamp node, then below is the popup field.
image

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

1. I suggest that when a user clicks on a field then when the popup appears the popup field should be focused and the content selected (so the user doesn't need to delete the content first before changing to a new value) for easy customizations.
2. I suggest that when the focus is inside the popup box the Enter key should confirm the value and make the box disappear.

These two options would make it easier and much more natural to edit values for fields on visual nodes. Currently it's cumbersome.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Well as described above, code wise I have no idea unfortunately.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

Visual Shaders are editor core.

### LINKED ISSUE #75598: Certain VisualShader nodes (constants) contain a selectable, blank bar above the editor part
### Godot version

4.1.dev (21d080ead4ff09a0796574c920a76e66e8b8a3e4)

### System information
\-

### Issue description

If you click on it once it stays selected until you reload the editor (or in some cases toggle the preview).

grafik

There seems to be a context menu registered for this, but the entries are disfunctional:

grafik
(I'd assume that clicking on "Copy Value" on a TransformConstant and then clicking on "Paste Value" on another TransformConstant or Transform property editor is its intended use case, but that does nothing - just like "Copy Property Path" (which does not even make sense to me here).

Edit:
This is probably because some VisualShader \*\*\*Constant nodes use the same property editors which are used in the inspector:

grafik
So the blank bar usually contains the property's name, but since this is no property here it remains empty. I think it should either be editable to give the constant a name or removed/replaced completely.

### Steps to reproduce

Create a VisualShader resource and add e.g. a TransformConstant or Vector2/3/4Constant.

### Minimal reproduction project

\-

### PR DESCRIPTION
**Pull request by Geometror**
This PR aims to make editing properties in VisualShader more intuitive.
Fixes #75598.
Fixes godotengine/godot-proposals#9183 (partly).

**Detailed changes:**
- Focus the first focusable control when opening the property editor popup
- Adjust the size of the property editor popup based on the type
- Remove the blank area of the property editor when no label text is set

# Before:
grafik

grafik

# After:

grafik

grafik

### CODE REVIEW

**Review by fire — APPROVED** [review]
I like the usability improvements but I haven't checked the code.

File: editor/plugins/visual_shader_editor_plugin.cpp [hunk 1]
```diff
@@ -2738,42 +2739,74 @@ void VisualShaderEditor::_port_edited(const StringName &p_property, const Varian
...
+	property_editor = EditorInspector::instantiate_property_editor(edited_property_holder.ptr(), value.get_type(), "edited_property", PROPERTY_HINT_NONE, "AAAAAA", PROPERTY_USAGE_NONE, true);
+	ERR_FAIL_COND_MSG(!property_editor, "Failed to create property editor for type: " + itos(value.get_type()));
+
+	// Determine the best size for the popup based on the property type.
+	// Since the property editors are also used in the inspector, we can't
+	Size2 popup_pref_size;
+	switch (value.get_type()) {
+		case Variant::VECTOR3:
+		case Variant::BASIS:
+			popup_pref_size = Size2(320, 0);
```
Comment (AThousandShips) [inline editor/plugins/visual_shader_editor_plugin.cpp:2776]:
```suggestion
			popup_pref_size.width = 320;
```

File: editor/plugins/visual_shader_editor_plugin.cpp [hunk 2]
```diff
@@ -2738,42 +2739,74 @@ void VisualShaderEditor::_port_edited(const StringName &p_property, const Varian
...
+			break;
+		case Variant::VECTOR4:
+		case Variant::QUATERNION:
+		case Variant::PLANE:
+		case Variant::TRANSFORM2D:
+		case Variant::TRANSFORM3D:
+		case Variant::PROJECTION:
+			popup_pref_size = Size2(480, 0);
```
Comment (AThousandShips) [inline editor/plugins/visual_shader_editor_plugin.cpp:2784]:
```suggestion
			popup_pref_size.width = 480;
```

**Review by AThousandShips — APPROVED** [review]

File: editor/plugins/visual_shader_editor_plugin.cpp [hunk 3]
```diff
@@ -2738,42 +2739,74 @@ void VisualShaderEditor::_port_edited(const StringName &p_property, const Varian
...
 
+void VisualShaderEditor::_port_default_popup_input(const Ref<InputEvent> &p_event) {
+	if (p_event.is_null()) {
+		return;
+	}
+
+	if (p_event->is_action_pressed("ui_accept")) {
+		property_editor_popup->hide();
+	}
+}
```
Comment (KoBeWi) [inline editor/plugins/visual_shader_editor_plugin.cpp:2750]: This method is unused.

File: editor/plugins/visual_shader_editor_plugin.cpp [hunk 4]
```diff
@@ -2738,42 +2739,74 @@ void VisualShaderEditor::_port_edited(const StringName &p_property, const Varian
...
 	}
 
 	// TODO: Define these properties with actual PropertyInfo and feed it to the property editor widget.
-	property_editor = EditorInspector::instantiate_property_editor(edited_property_holder.ptr(), value.get_type(), "edited_property", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_NONE);
-	if (property_editor) {
-		property_editor->set_object_and_property(edited_property_holder.ptr(), "edited_property");
-		property_editor->update_property();
-		property_editor->set_name_split_ratio(0);
-		property_editor_popup->add_child(property_editor);
+	property_editor = EditorInspector::instantiate_property_editor(edited_property_holder.ptr(), value.get_type(), "edited_property", PROPERTY_HINT_NONE, "AAAAAA", PROPERTY_USAGE_NONE, true);
```
Comment (KoBeWi) [inline editor/plugins/visual_shader_editor_plugin.cpp:2767]: What is "AAAAAA" for?

Comment (akien-mga) [reply editor/plugins/visual_shader_editor_plugin.cpp:2767]: Getting ready for next-next-next-gen AAA games.

Comment (Geometror) [reply editor/plugins/visual_shader_editor_plugin.cpp]: Oops :)

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
