### PR TITLE
Fix Editor 2D Ruler Text Top-Align

### LINKED ISSUE #104981: Ruler numbers too small at 90% editor scale
### Tested versions

- Reproducible in 4.4 stable

### System information

Godot v4.4.stable - Windows 11 (build 26100) - Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3070 (NVIDIA; 32.0.15.7260) - AMD Ryzen 7 5800X3D 8-Core Processor (16 threads)

### Issue description

I use Godot on a 1080p display so pixel density is a bit limited, so I have my editor scale set to a custom value of 0.9. This gives a comfortable amount of information density, but as a side effect it makes the ruler numbers too small to read comfortably:

Image

### Steps to reproduce

- Make sure the OS is at 100%/1x DPI scaling (just in case).
- Go to Editor -> Editor Settings -> Interface -> Editor
- Set "Display Scale" to "Custom" and "Custom Display Scale" to 0.9.
- Restart the editor.
- Switch to the 2D view.
- If rulers aren't enabled, show them using View -> Show Rulers.
- Observe uncomfortably small ruler numbers. The 6 practically looks like a 0!

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by lodetrick**
Fixes the Editor2D ruler text-top align by offsetting the text to be above any of the ruler marker lines. Tested with 0.6, 0.9, 1.5 editor scales. It appears that the `font->get_height` returns a larger value than what is actually drawn (because it includes the downward height of letters like g), so I changed it to `font->get_ascent` to find the distance from the top of the ruler that it needs to be.

### CODE REVIEW

**Comment by KeyboardDanni** [comment]
Not quite the fix I had in mind (my fix lets the user enlarge the ruler and the font grows with it), but I did notice that the numbers were overlapping the tick markers.

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -3076,7 +3076,7 @@ void CanvasItemEditor::_draw_rulers() {
 		if (i % (major_subdivision * minor_subdivision) == 0) {
 			viewport->draw_line(Point2(position.x, 0), Point2(position.x, RULER_WIDTH), graduation_color, Math::round(EDSCALE));
 			real_t val = (ruler_transform * major_subdivide * minor_subdivide).xform(Point2(i, 0)).x;
-			viewport->draw_string(font, Point2(position.x + 2, font->get_height(font_size)), TS->format_number(vformat(((int)val == val) ? "%d" : "%.1f", val)), HORIZONTAL_ALIGNMENT_LEFT, -1, font_size, font_color);
+			viewport->draw_string(font, Point2(position.x + 2, font->get_ascent(font_size)), TS->format_number(vformat(((int)val == val) ? "%d" : "%.1f", val)), HORIZONTAL_ALIGNMENT_LEFT, -1, font_size, font_color);
```
Comment (bruvzg) [inline editor/plugins/canvas_item_editor_plugin.cpp:3079]:
```suggestion
			viewport->draw_string(font, Point2(position.x + 2, font->get_ascent(font_size) + Math::round(EDSCALE)), TS->format_number(vformat(((int)val == val) ? "%d" : "%.1f", val)), HORIZONTAL_ALIGNMENT_LEFT, -1, font_size, font_color);
```

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 2]
```diff
@@ -3094,7 +3094,7 @@ void CanvasItemEditor::_draw_rulers() {
 			viewport->draw_line(Point2(0, position.y), Point2(RULER_WIDTH, position.y), graduation_color, Math::round(EDSCALE));
 			real_t val = (ruler_transform * major_subdivide * minor_subdivide).xform(Point2(0, i)).y;
 
-			Transform2D text_xform = Transform2D(-Math_PI / 2.0, Point2(font->get_height(font_size), position.y - 2));
+			Transform2D text_xform = Transform2D(-Math_PI / 2.0, Point2(font->get_ascent(font_size), position.y - 2));
```
Comment (bruvzg) [inline editor/plugins/canvas_item_editor_plugin.cpp:3097]:
```suggestion
			Transform2D text_xform = Transform2D(-Math_PI / 2.0, Point2(font->get_ascent(font_size) + Math::round(EDSCALE), position.y - 2));
```

**Review by bruvzg — COMMENTED** [review]
`ascent` is sufficient to fit the text, but now it collides with viewport focus rect, so might be worth adding a few extra pixels:

Master:
master

This PR:
this_pr

This PR with ` + Math::round(EDSCALE)`

plus_px

**Review by bruvzg — APPROVED** [review]
Please squash the commits, see [Pull request workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for details.

**Comment by Repiteo** [comment]
Thanks!
