### PR TITLE
Reintroduce the dragging method of Sprite2D's region_rect

### LINKED ISSUE #106081: Resizing Sprite with smart snapping now resizes the region rect
### Tested versions

Godot v4.5.dev (1cf573f44) - master, since https://github.com/godotengine/godot/pull/105147

### System information

Windows 11 (build 26100) - Single-window, 1 monitor - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 2070 (NVIDIA; 32.0.15.7602) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 threads)

### Issue description

Resizing a Sprite with Ctrl held now adjusts the region rect when control is held, instead of just being for smart snapping. They should be two separate actions.

https://github.com/user-attachments/assets/07536947-e57f-4b8c-9fff-2177c16515d0

The region rect editing was added by https://github.com/godotengine/godot/pull/105147, and it uses the control key.
However the control key is already in use for the smart snapping, so the region rect editing should be accessed in a different way.
All modifier keys are already in use, so it can't just be moved to another one.

To fix this, I think the Sprite Editor Plugin should have it as a separate tool mode, like how the Path2D Editor Plugin has its own tool modes.

### Steps to reproduce

- Add a sprite.
- Enable the region rect.
- Hold control and drag the rect side to resize; try use to smart snap.
- It will adjust the region rect and smart snap at the same time.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Lazy-Rabbit-2001**
Fixes and closes: https://github.com/godotengine/godot/issues/106081

Due to the fact that holding ctrl, shift, and alt have been used for other handlings in the editor, the original implementation of pr #105147 is not dedicate enough.

This time I turned it into a small plugin button at the right of the Sprite2D plugin. The icon of the new button is “KeepAspect” (not sure if there are any better icon for this). The button is togglable so only when it is pressed can you drag the selected sprite to resize its `region_rect`, otherwise you will resize its `scale`.

### CODE REVIEW

File: scene/2d/sprite_2d.h [hunk 1]
```diff
@@ -89,6 +91,8 @@ class Sprite2D : public Node2D {
 	bool is_pixel_opaque(const Point2 &p_point) const;
 	bool is_editor_region_rect_draggable() const;
 
+	void set_dragging_to_resize_rect(bool p_dragging_to_resize_rect);
```
Comment (groud) [inline scene/2d/sprite_2d.h:94]: This should be in the TOOLS_ENABLED part and likely prefixed with  `_edit`, as this only matters for the editor. Likely same for the `dragging_to_resize_rect` variable.

**Comment by groud** [comment]
I am a bit confused by this PR. It comments out many things, and adds a lot of code for something that should be more or less trivial. I don't think we need an additional `Sprite2DEditorResizeRect` class to handle that too. The button should simply change the newly added Sprite2D resize mode and that's all.
 
I feel it would be better to simply revert the PR that introduced the issue and start again on a clean copy.

File: editor/plugins/sprite_2d_editor_plugin.cpp [hunk 2]
```diff
@@ -665,18 +661,54 @@ Sprite2DEditor::Sprite2DEditor() {
...
+
+	button->set_flat(true);
+	button->set_toggle_mode(true);
+	//button->set_text(TTR("Resize Region Rect"));
+	button->set_tooltip_text(TTR("Drag to Resize Region Rect"));
+	button->connect(SceneStringName(toggled), callable_mp(this, &Sprite2DEditorResizeRect::_sync_state_to_sprite));
+}
+
 void Sprite2DEditorPlugin::_editor_theme_changed() {
-	dragging_mode_hint->add_theme_color_override(SceneStringName(font_color), Color(0.6f, 0.6f, 0.6f, 1));
```
Comment (groud) [inline editor/plugins/sprite_2d_editor_plugin.cpp:669]: Why is those two function completely commented out? They are useless now.

**Comment by groud** [comment]
> I would have wanted to add a new option in Sprite2DEditor but the fact was that it would break the alignment, i.e. the checkbox will push the three icons a bit righter, which looks not quite fine. So I selected making a new plugin button for it.

I think it is not a great idea. Could you please show a screenshot of the issue when adding another button?
If it's just about adding another button that is not the correct size, we could also create another icon, that's not a problem.

> But if you mean the pr that implements the stuff of dragging to resize the region_rect, that's ok when another pr of mine, https://github.com/godotengine/godot/pull/106530, gets merged.

I meant reverting this one. https://github.com/godotengine/godot/pull/105147

File: editor/plugins/sprite_2d_editor_plugin.cpp [hunk 3]
```diff
@@ -449,6 +445,29 @@ void Sprite2DEditor::_add_as_sibling_or_child(Node *p_own_node, Node *p_new_node
...
+	resize_region_rect->set_disabled(!node->is_region_enabled());
+	resize_region_rect->set_pressed(node->_editor_is_dragging_to_resiz_rect());
+}
+
+void Sprite2DEditor::_update_sprite_resize_mode_tooltip() {
+	if (node != nullptr && node->is_region_enabled()) {
+		return;
+	}
+
+	resize_region_rect->set_tooltip_text("\n" + TTR("Please set 'region_rect' to 'true'."));
```
Comment (KoBeWi) [inline editor/plugins/sprite_2d_editor_plugin.cpp:468]: This text is wrong. It's `region_enabled`, not `region_rect`.
Though I'd reword it to not mention any property (it can be confusing with the new section checkboxes).
```suggestion
	resize_region_rect->set_tooltip_text("\n" + TTR("Sprite's region needs to be enabled in the inspector."));
```

File: scene/2d/sprite_2d.cpp [hunk 4]
```diff
@@ -544,9 +553,8 @@ void Sprite2D::_bind_methods() {
...
 Sprite2D::Sprite2D() {
 #ifdef TOOLS_ENABLED
-	add_user_signal(MethodInfo("_editor_region_rect_enabled", PropertyInfo(Variant::BOOL, "enabled"))); // Sprite2DEditorPlugin listens to this.
+	add_user_signal(MethodInfo("_editor_region_rect_enabled"));
 #endif
 }
 
-Sprite2D::~Sprite2D() {
-}
+Sprite2D::~Sprite2D() {}
```
Comment (KoBeWi) [inline scene/2d/sprite_2d.cpp:560]: What's this change?
If anything, this should be removed.

File: scene/2d/sprite_2d.h [hunk 5]
```diff
@@ -40,6 +40,10 @@ class Sprite2D : public Node2D {
 	Color specular_color;
 	real_t shininess = 0.0;
 
+#ifdef TOOLS_ENABLED
+	bool dragging_to_resize_rect = false;
```
Comment (KoBeWi) [inline scene/2d/sprite_2d.h:44]: It would be simpler if you just made this property public 🤷‍♂️

File: editor/plugins/sprite_2d_editor_plugin.h [hunk 6]
```diff
@@ -48,14 +49,15 @@ class Sprite2DEditor : public Control {
 		MENU_OPTION_CONVERT_TO_MESH_2D,
 		MENU_OPTION_CONVERT_TO_POLYGON_2D,
 		MENU_OPTION_CREATE_COLLISION_POLY_2D,
-		MENU_OPTION_CREATE_LIGHT_OCCLUDER_2D
+		MENU_OPTION_CREATE_LIGHT_OCCLUDER_2D,
```
Comment (KoBeWi) [inline editor/plugins/sprite_2d_editor_plugin.h:52]: Unless you are adding something to the enum, this change is useless.

File: editor/plugins/sprite_2d_editor_plugin.cpp [hunk 7]
```diff
@@ -706,22 +743,18 @@ bool Sprite2DEditorPlugin::handles(Object *p_object) const {
 void Sprite2DEditorPlugin::make_visible(bool p_visible) {
 	if (p_visible) {
 		sprite_editor->options->show();
+		sprite_editor->resize_region_rect->show();
```
Comment (KoBeWi) [inline editor/plugins/sprite_2d_editor_plugin.cpp:746]: It's better to toggle all editor options together.
For that, you can make a single HBoxContainer for the buttons and toggle it instead.

File: editor/plugins/sprite_2d_editor_plugin.cpp [hunk 8]
```diff
@@ -597,6 +639,31 @@ Sprite2DEditor::Sprite2DEditor() {
...
+	Ref<InputEventKey> key = memnew(InputEventKey);
+	key->set_ctrl_pressed(true);
+	key->set_physical_keycode(Key::R);
+
+	Array events;
+	events.append(key);
+
+	Ref<Shortcut> shortcut = memnew(Shortcut);
+	shortcut->set_name(TTR("Dragging to Resize Region Rect"));
+	shortcut->set_events(events);
```
Comment (KoBeWi) [inline editor/plugins/sprite_2d_editor_plugin.cpp:661]: You should use `ED_SHORTCUT()`.

File: editor/plugins/sprite_2d_editor_plugin.cpp [hunk 9]
```diff
@@ -597,6 +639,31 @@ Sprite2DEditor::Sprite2DEditor() {
 
 	options->get_popup()->connect(SceneStringName(id_pressed), callable_mp(this, &Sprite2DEditor::_menu_option));
 
+	// Resize region rect definition
+	resize_region_rect = memnew(Button);
+
+	CanvasItemEditor::get_singleton()->add_control_to_menu_panel(resize_region_rect);
+
+	_update_sprite_resize_mode_tooltip();
```
Comment (KoBeWi) [inline editor/plugins/sprite_2d_editor_plugin.cpp:647]: It's pointless here, the editor is not even initialized properly.

**Comment by KoBeWi** [comment]
There are minor bugs and style problems, but overall looks fine.

**Comment by KoBeWi** [comment]
The button can end up disabled without explaining tooltip. I didn't test exact circumstances for that, but it will always happen when you add a Sprite2D after launching editor.

File: editor/plugins/sprite_2d_editor_plugin.cpp [hunk 10]
```diff
@@ -597,6 +642,26 @@ Sprite2DEditor::Sprite2DEditor() {
...
+	top_hb->add_child(resize_region_rect);
+
+	resize_region_rect->set_theme_type_variation("FlatMenuButton");
+	resize_region_rect->set_toggle_mode(true);
+
+	Ref<Shortcut> shortcut = ED_SHORTCUT("canvas_item_editor/resize_region_rect", "Dragging to Resize Region Rect", Key::R, true);
+	Ref<InputEventKey> key = shortcut->get_events()[0];
+
+	if (key.is_valid()) {
+		key->set_ctrl_pressed(true);
```
Comment (KoBeWi) [inline editor/plugins/sprite_2d_editor_plugin.cpp:657]: ??
You can do `KeyModifierMask::CMD_OR_CTRL | Key::R`, no need for some hacks.

File: editor/plugins/sprite_2d_editor_plugin.cpp [hunk 11]
```diff
@@ -597,6 +642,26 @@ Sprite2DEditor::Sprite2DEditor() {
...
 
+	// Resize region rect definition
+	resize_region_rect = memnew(Button);
+
+	top_hb->add_child(resize_region_rect);
+
+	resize_region_rect->set_theme_type_variation("FlatMenuButton");
+	resize_region_rect->set_toggle_mode(true);
+
+	Ref<Shortcut> shortcut = ED_SHORTCUT("canvas_item_editor/resize_region_rect", "Dragging to Resize Region Rect", Key::R, true);
```
Comment (KoBeWi) [inline editor/plugins/sprite_2d_editor_plugin.cpp:653]:
```suggestion
	Ref<Shortcut> shortcut = ED_SHORTCUT("canvas_item_editor/resize_region_rect", TTRC("Dragging to Resize Region Rect"), Key::R, true);
```

File: editor/plugins/sprite_2d_editor_plugin.cpp [hunk 12]
```diff
@@ -597,6 +642,26 @@ Sprite2DEditor::Sprite2DEditor() {
 
 	options->get_popup()->connect(SceneStringName(id_pressed), callable_mp(this, &Sprite2DEditor::_menu_option));
 
+	// Resize region rect definition
+	resize_region_rect = memnew(Button);
+
+	top_hb->add_child(resize_region_rect);
```
Comment (KoBeWi) [inline editor/plugins/sprite_2d_editor_plugin.cpp:648]: Add child _after_ doing setup. This avoids unnecessary notifications and callbacks when node is being setup while in tree.

File: editor/plugins/sprite_2d_editor_plugin.cpp [hunk 13]
```diff
@@ -449,6 +445,27 @@ void Sprite2DEditor::_add_as_sibling_or_child(Node *p_own_node, Node *p_new_node
...
+	if (node == nullptr) {
+		return;
+	}
+	resize_region_rect->set_disabled(!node->is_region_enabled());
+	resize_region_rect->set_pressed(node->_editor_is_dragging_to_resiz_rect());
+}
+
+void Sprite2DEditor::_update_sprite_resize_mode_tooltip() {
+	if (node != nullptr && !node->is_region_enabled()) {
+		resize_region_rect->set_tooltip_text("\n" + TTR("Sprite's region needs to be enabled in the inspector."));
```
Comment (KoBeWi) [inline editor/plugins/sprite_2d_editor_plugin.cpp:464]:
```suggestion
		resize_region_rect->set_tooltip_text(TTRC("Sprite's region needs to be enabled in the inspector."));
```
This seems to work correctly.

File: editor/plugins/sprite_2d_editor_plugin.cpp [hunk 14]
```diff
@@ -449,6 +445,26 @@ void Sprite2DEditor::_add_as_sibling_or_child(Node *p_own_node, Node *p_new_node
...
+
+void Sprite2DEditor::_update_sprite_resize_mode_button() {
+	if (node == nullptr) {
+		return;
+	}
+	resize_region_rect->set_disabled(!node->is_region_enabled());
+	resize_region_rect->set_pressed(node->_editor_is_dragging_to_resiz_rect());
+}
+
+void Sprite2DEditor::_update_sprite_resize_mode_tooltip() {
```
Comment (KoBeWi) [inline editor/plugins/sprite_2d_editor_plugin.cpp:462]: I don't know how, but the tooltip and disabled state can still get desynced.
image
Though as I mentioned, you can update them together. I don't see why there are 2 separate methods if they are called together and button's tooltip and disabled state basically depend on each other.

Comment (KoBeWi) [reply editor/plugins/sprite_2d_editor_plugin.cpp:463]: It's still a separate method XD
Remove `_update_sprite_resize_mode_tooltip()` completely, it's not needed. You can set the tooltip in `_update_sprite_resize_mode_button()`.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

File: scene/2d/sprite_2d.h [hunk 15]
```diff
@@ -86,6 +90,11 @@ class Sprite2D : public Node2D {
 	virtual bool _edit_use_rect() const override;
 #endif // DEBUG_ENABLED
 
+#ifdef TOOLS_ENABLED
+	void _editor_set_dragging_to_resize_rect(bool p_dragging_to_resize_rect);
+	bool _editor_is_dragging_to_resiz_rect() const;
```
Comment (arkology) [inline scene/2d/sprite_2d.h:95]: @Lazy-Rabbit-2001 BTW there is a typo
