### PR TITLE
Fix for issue #7766

### LINKED ISSUE #7766: OS.get_mouse_mode() returns garbage on OSX
Present in 2.1 and master on OSX:

QA thread: https://godotengine.org/qa/12250/input-get_mouse_mode-is-returning-32767-why

`mouse_mode` is not initialized in the constructor of `OS_OSX`. It should be `VISIBLE` I think.

https://github.com/godotengine/godot/blob/master/platform/osx/os_osx.mm#L1767

### PR DESCRIPTION
**Pull request by Brett-Mitchell**
When calling get_mouse_mode() on OS_OSX, garbage was returned.  This is because mouse_mode was not initialized in the constructor for OS_OSX.

Add initialization for OS_OSX.mouse_mode in OS_OSX::OS_OSX().  mouse_mode now defaults to OS::MOUSE_MODE_VISIBLE.

_Bugsquad edit:_ fixes #7766

### CODE REVIEW

**Review by bojidar-bg — APPROVED** [review]
(Not like I can test it, but it should work if it compiles)

**Review by 27thLiz — APPROVED** [review]

File: platform/osx/os_osx.mm [hunk 1]
```diff
@@ -1765,7 +1765,8 @@ static void keyboardLayoutChanged(CFNotificationCenterRef center, void *observer
 OS_OSX* OS_OSX::singleton=NULL;
 
 OS_OSX::OS_OSX() {
-
+	
+	mouse_mode=OS::MOUSE_MODE_VISIBLE
```
Comment (akien-mga) [inline platform/osx/os_osx.mm]: Well, approved by two experienced Godot devs and merged by a third one, but obviously I should have waited on Travis: it lacks a semicolon, that doesn't compile. :)

Will fix.

Comment (Hinsbart) [inline platform/osx/os_osx.mm]: lol, damn...

**Comment by Brett-Mitchell** [comment]
Hehe...  :P

First PR ever and I forget the semicolon.

**Comment by bojidar-bg** [comment]
@Brett-Mitchell Run scons locally, that's the best way to ensure no such issues happen :wink:
