### PR TITLE
Follow-Up Fix Directory Open

### LINKED ISSUE #40234: "Directory must be opened before use" errors while using some for the `Directory` methods
**Godot version:**
3.2.3.beta 6fd712c87433422eb5d7cbb03f1a69686e5ba454, likely due to #40151.

**OS/device including version:**
Windows 10

**Issue description:**
```
E 0:00:00.811   _Directory::change_dir: Directory must be opened before use.
  <C++ Error>   Condition "!is_open()" is true. Returned: ERR_UNCONFIGURED
  <C++ Source>  core\bind\core_bind.cpp:2424 @ _Directory::change_dir()
  <Stack Trace> test.gd:5 @ _ready()
```

Other methods are also affected: `dir_exists`, `make_dir`, `make_dir_recursive`, `file_exists`.

**Steps to reproduce:**

```gdscript
extends Node2D

func _ready():
	var dir = Directory.new()
	dir.change_dir("res://") # Fail here.
	dir.list_dir_begin()

	var file = dir.get_next()
	while not file.empty():
		print(file)
		file = dir.get_next()
```

This piece of snippet works fine in `3.2.2-stable`.

I stumbled upon this while running a project with the [plugin refresher](https://github.com/godot-extended-libraries/godot-plugin-refresher), the plugins are not listed in 3.2.3 now.

**Minimal reproduction project:**
[dir_access_chdir.zip](https://github.com/godotengine/godot/files/4896486/dir_access_chdir.zip)

### PR DESCRIPTION
**Pull request by nathanfranke**
Fixes #40234 
Related to #40151 

We should test this thoroughly before merging to make sure there aren't any other regressions.

CC @Xrayez @akien-mga 

```py
var fs = Directory.new()
print(fs.file_exists("res://icon.png")) # True
print(fs.dir_exists("res://")) # True

fs.open("test")
fs.list_dir_begin(true, true)
print(fs.get_next()) # test_file
```

### CODE REVIEW

**Comment by nathanfranke** [comment]
Updated documentation

File: core/bind/core_bind.cpp [hunk 1]
```diff
@@ -1673,8 +1673,14 @@ int _Directory::get_current_drive() {
 }
 
 Error _Directory::change_dir(String p_dir) {
-	ERR_FAIL_COND_V_MSG(!is_open(), ERR_UNCONFIGURED, "Directory must be opened before use.");
-	return d->change_dir(p_dir);
+	Error err = d->change_dir(p_dir);
+	
+	if(err != Error::OK) {
```
Comment (Xrayez) [inline core/bind/core_bind.cpp:1678]: Scoping is not necessary, consistent with other codebase.
Also clang-format asks to add a space there. 🙂

```suggestion
	if (err != OK) {
```

File: core/bind/core_bind.cpp [hunk 2]
```diff
@@ -1673,8 +1673,14 @@ int _Directory::get_current_drive() {
...
+		return err;
+	}
+	dir_open = true;
+	
+	return Error::OK;
```
Comment (Xrayez) [inline core/bind/core_bind.cpp:1683]: Same here.

```suggestion
	return OK;
```

**Comment by Xrayez** [comment]
I've tested this on 3.2 branch, I haven't caught any errors. If there are, they can be easily fixed on the project side rather than plugins etc, so should be fine I guess. I'm also able to run unit tests with GUT now.

**Comment by nathanfranke** [comment]
Thanks for the changes feedback. I always forget the space after `if` :)

**Review by Xrayez — APPROVED** [review]

File: core/bind/core_bind.cpp [hunk 3]
```diff
@@ -1673,8 +1673,14 @@ int _Directory::get_current_drive() {
 }
 
 Error _Directory::change_dir(String p_dir) {
-	ERR_FAIL_COND_V_MSG(!is_open(), ERR_UNCONFIGURED, "Directory must be opened before use.");
-	return d->change_dir(p_dir);
+	Error err = d->change_dir(p_dir);
+
```
Comment (akien-mga) [inline core/bind/core_bind.cpp:1677]: Trailing whitespace here and on line 1682.

I suggest setting up the pre-commit hooks locally to run clang-format when you commit: https://github.com/godotengine/godot/tree/master/misc/hooks

File: core/bind/core_bind.cpp [hunk 4]
```diff
@@ -1673,8 +1673,14 @@ int _Directory::get_current_drive() {
 }
 
 Error _Directory::change_dir(String p_dir) {
-	ERR_FAIL_COND_V_MSG(!is_open(), ERR_UNCONFIGURED, "Directory must be opened before use.");
```
Comment (akien-mga) [inline core/bind/core_bind.cpp:1676]: I think the methods which don't check `is_open()` should keep checking that `d` is valid as they used to. Otherwise if the code ever changes to make `d` invalid, this is a null pointer dereference waiting to happen.

**Comment by nathanfranke** [comment]
Fixed

I renamed the error so it wouldn't be confused with the `is_open` check

```c++
ERR_FAIL_COND_V_MSG(!d, ERR_UNCONFIGURED, "Directory is not configured properly.");
```

As of right now, I am not sure what "not configured properly" means since I don't think `d` can be `nullptr`

**Comment by akien-mga** [comment]
> As of right now, I am not sure what "not configured properly" means since I don't think `d` can be `nullptr`

Well, the main question is: Can you guarantee that `DirAccess::create(DirAccess::ACCESS_RESOURCES);` would never return `nullptr`? It's a virtual method which has to be implemented by each platform port/driver, so it differs on Windows and Unix, might also differ on some console ports or other thirdparty ports, etc. Also differs when in a PCK (`DirAccessPack`).

So this kind of check is definitely useful in the wrapper code that relies on so many platform-specific implementations.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
```
In file included from ./core/cowdata.h:34,
                 from ./core/ustring.h:35,
                 from ./core/color.h:35,
                 from ./core/image.h:34,
                 from core/bind/core_bind.h:34,
                 from core/bind/core_bind.cpp:31:
core/bind/core_bind.cpp: In member function 'bool _Directory::file_exists(String)':
core/bind/core_bind.cpp:1715:26: error: enum constant in boolean context [-Werror=int-in-bool-context]
 1715 |  ERR_FAIL_COND_V_MSG(!d, ERR_UNCONFIGURED, "Directory is not configured properly.");
      |                          ^~~~~~~~~~~~~~~~
./core/error_macros.h:386:10: note: in definition of macro 'ERR_FAIL_COND_V_MSG'
  386 |   return m_retval;                                                                                                                            \
      |          ^~~~~~~~
core/bind/core_bind.cpp: In member function 'bool _Directory::dir_exists(String)':
core/bind/core_bind.cpp:1724:26: error: enum constant in boolean context [-Werror=int-in-bool-context]
 1724 |  ERR_FAIL_COND_V_MSG(!d, ERR_UNCONFIGURED, "Directory is not configured properly.");
      |                          ^~~~~~~~~~~~~~~~
./core/error_macros.h:386:10: note: in definition of macro 'ERR_FAIL_COND_V_MSG'
  386 |   return m_retval;                                                                                                                            \
      |          ^~~~~~~~
```

**Comment by nathanfranke** [comment]
Apologies! `file_exists` and `dir_exists` return a `bool` and not an `Error`

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.
