### PR TITLE
Fix calling `TextureStorage::texture_3d_update()` could cause a crash

### LINKED ISSUE #77248: ImageTexture3D update crashes game.
### Godot version

4.0 master commit 9ad9820f5d2a4357ad16480f88a679fce8ecd492

### System information

Linux

### Issue description

When I create an ImageTexture3D and then try and update it, even with the same exact data I just created it with, it causes the entire game to crash, with no explanation, beyond *sometimes* saying 'With signal 11'.

### Steps to reproduce

Download and run the repro project with godot.

### Minimal reproduction project

https://gitlab.com/AngularAngel/TextureCrashMinimalRepro

### PR DESCRIPTION
**Pull request by Rindbee**
Fix #77248.

### CODE REVIEW

File: servers/rendering/renderer_rd/storage_rd/texture_storage.cpp [hunk 1]
```diff
@@ -1146,14 +1146,13 @@ void TextureStorage::texture_3d_update(RID p_texture, const Vector<Ref<Image>> &
...
-		images.resize(p_data.size());
 		for (int i = 0; i < p_data.size(); i++) {
 			Ref<Image> image = p_data[i];
 			if (image->get_format() != tex->validated_format) {
 				image = image->duplicate();
 				image->convert(tex->validated_format);
 			}
-			all_data_size += images[i]->get_data().size();
+			all_data_size += image->get_data().size();
 			images.push_back(image);
```
Comment (RedworkDE) [inline servers/rendering/renderer_rd/storage_rd/texture_storage.cpp:1156]:
```suggestion
			images[i] = image;
```
instead of removing the `resize` above avoids having to incrementally grow the vector.

**Review by RedworkDE — APPROVED** [review]
Not an rendering export, so I cannot say if there are any more issues with this functions.

I can still tell that the previous handling of `images` was nonsense and that the updated code is most likely what was originally intended.

**Review by RandomShaper — APPROVED** [review]
Makes a lot of sense!

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.4.
