### PR TITLE
[3.2] Fixed SkeletonIK not working with scaled skeletons

### LINKED ISSUE #25544: SkeletonIK does not work with scaled object
**Godot version:**
3.1 Beta 3

**OS/device including version:**
Kubuntu 18.04

**Issue description:**
When I scale my Scene that contains the rigged mesh, IK_Target and SkeletonIK nodes, the IK chain is not working properly anymore

**Steps to reproduce:**
- create working SkeletonIK model
- scale parent node down
- the tip of the IK scene will get scaled twice, once from the parent node and once from the Position3D that is scaled by the parent node
- the location data of the Position3D target doesn't seem affected by the scale. I have to move it where it would have been in the unscaled scene to get the proper orientation of the IK chain

edit: this also happens when only the armature is scaled and the Target is outside of the scaled armature. Position of the IK chain is still wrong, even though the tip of the chain remains unscaled this time.

**Minimal reproduction project:**
[SkeletonIK_scale_bug.zip](https://github.com/godotengine/godot/files/2821691/SkeletonIK_scale_bug.zip)

using the model from 3d in 2d demo
- when the scene is loaded, select SkeletonIK and Press play IK
- the foot will get scaled down to a very tiny size
- leg/foot won't point to the Position3D, you have to make very big movements to animate it

- reset scaling of root Spatial node from 0.1 to 1
- IK chain works as expected

### PR DESCRIPTION
**Pull request by TwistedTwigleg**
Closes #25544

The issue turns out to be that the target in the minimum replication project given, in the linked issue, is a child node of the scaled bone. This means it is also being scaled when the Skeleton is scaled. Scaling *only* the Skeleton/Armature node or increasing the scale of the IK target relative to the parent's scale also fixes the issue.
However, IK probably shouldn't be affecting the scale of bones, since IK is really only for rotation. To prevent this, the scale calculated in the IK chain is discarded before being applied to the Skeleton. This should fix any issues where the bone's are scaled when being operated on by IK.

This PR is targeted towards Godot 3.2, as the reworked IK in Godot 4.0/master does not exhibit this issue.

### CODE REVIEW

File: scene/animation/skeleton_ik.cpp [hunk 1]
```diff
@@ -274,7 +274,7 @@ void FabrikInverseKinematic::make_goal(Task *p_task, const Transform &p_inverse_
 	} else {
 
 		// End effector in local transform
-		const Transform end_effector_pose(p_task->skeleton->get_bone_global_pose(p_task->end_effectors.write[0].tip_bone));
+		const Transform end_effector_pose(p_task->skeleton->get_bone_global_pose(p_task->end_effectors[0].tip_bone));
```
Comment (TwistedTwigleg) [inline scene/animation/skeleton_ik.cpp:277]: This was just a general fix I applied while looking through the code. It does not change the functionality of the IK in any way.

File: scene/animation/skeleton_ik.cpp [hunk 2]
```diff
@@ -331,6 +331,12 @@ void FabrikInverseKinematic::solve(Task *p_task, real_t blending_delta, bool ove
 				new_bone_pose.basis = new_bone_pose.basis * p_task->chain.tips[0].end_effector->goal_transform.basis;
 		}
 
+		// IK should not affect scale, so undo any scaling
+		new_bone_pose.basis[0].normalize();
+		new_bone_pose.basis[1].normalize();
+		new_bone_pose.basis[2].normalize();
```
Comment (TwistedTwigleg) [inline scene/animation/skeleton_ik.cpp:337]: Is there a better way to remove only the scale from a Basis? Would the `orthonormalized` function work?

**Comment by barbaros83** [comment]
thnx !!

File: scene/animation/skeleton_ik.cpp (hunk 2 above)
Comment (fire) [reply scene/animation/skeleton_ik.cpp:337]: You might have to handle the non-uniform scaling removal. I don't know if that's possible..

Comment (TwistedTwigleg) [reply scene/animation/skeleton_ik.cpp:337]: I'm *hoping* it will not be an issue, as after normalizing I apply whatever scale is set in the global position, which should reapply any non-uniform scales. It could be an issue though, I had not thought to test this. For most cases though, it should (fingers crossed) be okay.

Comment (AndreaCatania) [reply scene/animation/skeleton_ik.cpp:337]: You can use this: https://github.com/godotengine/godot/blob/master/core/math/basis.cpp#L74

**Comment by AndreaCatania** [comment]
This problem should be solved by setting the local transform of each bone instead, so the un-trasformation would remove the scale naturally. However, this fix is good anyway after the change that I mentioned above.

Thanks :)

**Comment by TwistedTwigleg** [comment]
Fixed! Thanks @AndreaCatania! :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by barbaros83** [comment]
is this merged in the new 3.2.3 beta ? because im still having the same problem

**Comment by TwistedTwigleg** [comment]
I know its been merged, but I have no idea if it is in the beta or not. I'll try the project in this issue on the beta tomorrow and see if I can reproduce it there.

**Comment by TwistedTwigleg** [comment]
Okay, I checked and found that the project in the issue #25544 is indeed fixed in the beta build.

@barbaros83 - It may be the issue you are having is different from the issue in #25544. If possible, can you make a minimum replication project that has the issue you are experiencing and include that project in a new GitHub issue? Then I can use the project to see if I can figure out what is going on and potentially fix it.

**Comment by barbaros83** [comment]
https://github.com/godotengine/godot/issues/40466

**Comment by Yazir** [comment]
I'm on stable 3.2.3, the scaled skeleton issue persists

**Comment by TwistedTwigleg** [comment]
@Yazir - If you do not mind, can you describe some more details about the issue you are seeing? Is the bones being operated on by IK changing scale? Is the target position offset or otherwise not correct?

I've made another PR, #40774, that fixes some more issues around the SkeletonIK node and scaling. Its targeted for Godot 4.0, but the fixes to the Skeleton IK node should be able to be cherry picked to Godot 3.2 as well.

**Comment by Yazir** [comment]
Hierarchy I've had:

Spatial
- Spatial
- - Skeleton
- - - Mesh
- - - SkeletonIK
- - - TargetIK

When I scaled Spatial or Skeleton, I've had to move the TargetIK to where it would be in global space before rescaling.

I was doing this while streaming, so I've made clips explaining the problem
https://clips.twitch.tv/TemperedTawdryShieldSoBayed
https://clips.twitch.tv/KitschyObedientNostrilKeyboardCat

Maybe I am approaching it in an incorrect way?

**Comment by TwistedTwigleg** [comment]
It doesn't appear the issue is anything with your approach or anything, it seems to be a SkeletonIK bug.
Based on the clips, it looks like what is happening is that the SkeletonIK is not correctly taking the scale of the Skeleton into account when solving. Because it is not taking the scale into account, the target position is offset incorrectly. This looks like the same problem that was happening in #4046. 
I believe the fix in PR #40774 *should* fix the issue then.
