### PR TITLE
Fix bounding box glitch

### LINKED ISSUE #91860: Bounding box glitch after selecting different nodes
### Tested versions

v4.3.dev.custom_build [bdc031621] (glitch)

v4.3.dev5.official [89f70e98d] (no glitch)

### System information

Godot v4.3.dev (bdc031621) - Windows 10.0.22631 - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.24002.92) - AMD Ryzen 7 PRO 6850U with Radeon Graphics (16 Threads)

### Issue description

Note origin:

https://github.com/godotengine/godot/assets/105675984/d9baa41d-5bb0-4a0b-bfb0-658de433ee7c

https://github.com/godotengine/godot/assets/105675984/4b230b2c-8c43-491a-96b6-56a7417d741f

### Steps to reproduce

Focus on origin and perform a drag-and-drop to instantiate scene or select via the SceenTree

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by ajreckof**
Fixes #91860

### CODE REVIEW

File: editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -3103,8 +3103,32 @@ bool SceneTreeDock::_check_node_recursive(Variant &r_variant, Node *p_node, Node
 void SceneTreeDock::set_edited_scene(Node *p_scene) {
 	edited_scene = p_scene;
 }
-
+bool is_same_selection(const Vector<Node *> &p_first, const List<Node *> &p_second) {
```
Comment (AThousandShips) [inline editor/scene_tree_dock.cpp:3107]:
```suggestion
static bool _is_same_selection(const Vector<Node *> &p_first, const List<Node *> &p_second) {
```
Use static method to avoid pollution of namespace

**Comment by ajreckof** [comment]
Thanks forgot to remove them before commiting

File: editor/scene_tree_dock.cpp [hunk 2]
```diff
@@ -3104,7 +3104,23 @@ void SceneTreeDock::set_edited_scene(Node *p_scene) {
...
+	for (Node *node : p_second) {
+		if (!p_first.has(node)) {
+			return false;
+		}
+	}
+	return true;
+}
+
 void SceneTreeDock::set_selection(const Vector<Node *> &p_nodes) {
+	// If the nodes selected are the same independently of order then return true.
```
Comment (AThousandShips) [inline editor/scene_tree_dock.cpp:3120]:
```suggestion
	// If the nodes selected are the same independently of order then return early.
```
No value is returned, or was this meant for the method above?

Comment (ajreckof) [reply editor/scene_tree_dock.cpp:3120]: yep this was meant for the above but maybe this is more usefull here with your modification

**Review by KoBeWi — APPROVED** [review]
The issue suggests that 3D editor is doing something wrong with the selection.
This fix is safe though, so the cause can be investigated later.

**Comment by ajreckof** [comment]
This might also be a case that should never happen as I was in this case replacing a selection by the same selection. This is most likely something that does not happen often and might even be something that shouldn't happen at all.

**Comment by akien-mga** [comment]
Thanks!
