### PR TITLE
Move GDScript uninitialization to `GDScriptLanguage::finish()`

### LINKED ISSUE #68973: `Shape2D` and `Shape3D` RID allocations can leak since #67714
### Godot version

4.0.dev (11e1c83)

### System information

Linux (Ubuntu 22.04), Vulkan, Radeon RX Vega 64 (eGPU)

### Issue description

Since the merge of #67714, some RID allocations of `Shape2D` and `Shape3D` can leak when the `PhysicsServer` singleton is disposed before the GDScript holding them.

This was a known issue when the merge occured.

```
ERROR: 3450 RID allocations of type 'P12GodotShape2D' were leaked at exit.
```

### Steps to reproduce

Investigating now.

### Minimal reproduction project

Not yet.

### PR DESCRIPTION
**Pull request by adamscott**
`GDScriptLanguage::finish()` was empty. So I moved the uninitialization of GDScriptLanguage originally in `GDScriptLanguage::~GDScriptLanguage()` inside it, calling too a new `GDScriptCache::clear()` to clear the cache sooner than the destructor. And `finish_languages` is called before the servers uninit.

As cyclic references didn't exist, there wasn't any GDScript instance that could live after the removal of the root script, so it wasn't a problem until cyclic references (which could make it so that instances could live beyond the root script).

The problem existed when ~~cyclic~~ cached scripts would hold RID past the uninitialization of the servers.

Fixes #68973
Would be interesting to merge with #69077

### CODE REVIEW

**Comment by adamscott** [comment]
Credited @rburing as a co-author for it's valuable help.

File: modules/gdscript/gdscript.cpp [hunk 1]
```diff
@@ -2019,6 +2019,55 @@ Error GDScriptLanguage::execute_file(const String &p_path) {
...
 
 void GDScriptLanguage::finish() {
+	finalize();
+}
+
+void GDScriptLanguage::finalize() {
+	if (finalized) {
+		return;
+	}
+	finalizing = true;
```
Comment (akien-mga) [inline modules/gdscript/gdscript.cpp:2029]: I don't see this used anywhere.

File: modules/gdscript/gdscript.cpp [hunk 2]
```diff
@@ -2019,6 +2019,55 @@ Error GDScriptLanguage::execute_file(const String &p_path) {
...
+	while (s) {
+		// This ensures the current script is not released before we can check
+		// what's the next one in the list (we can't get the next upfront because we
+		// don't know if the reference breaking will cause it -or any other after
+		// it, for that matter- to be released so the next one is not the same as
+		// before).
+		Ref<GDScript> scr = s->self();
+		if (scr.is_valid()) {
+			for (KeyValue<StringName, GDScriptFunction *> &E :
+					scr->member_functions) {
```
Comment (akien-mga) [inline modules/gdscript/gdscript.cpp:2050]: The wrapping doesn't seem to really make the code more readable here, I would keep it on a single line (same below).

Comment (adamscott) [reply modules/gdscript/gdscript.cpp:2050]: I had problems with my gitrepo, and in the process, it reformatted everything (weirdly).
I'll fix this.

File: modules/gdscript/gdscript.cpp (hunk 1 above)
Comment (adamscott) [reply modules/gdscript/gdscript.cpp:2029]: Fixed!

**Comment by adamscott** [comment]
@unfa This PR should fix the crash that happens when closing Liblast.

File: modules/gdscript/gdscript.cpp [hunk 3]
```diff
@@ -2019,6 +2019,50 @@ Error GDScriptLanguage::execute_file(const String &p_path) {
...
 
 void GDScriptLanguage::finish() {
+	finalize();
+}
+
+void GDScriptLanguage::finalize() {
+	if (finalizing) {
+		return;
+	}
+	finalizing = true;
```
Comment (akien-mga) [inline modules/gdscript/gdscript.cpp:2029]: This would now work, but I'm a bit confused because now `finalize()` will be called both by `GDScriptLanguage::finish()` and `GDScriptLanguage::~GDScriptLanguage()`, but it will only do something for the first one that calls it.

Is that order non deterministic, or why do we need to call it in both?

Comment (adamscott) [reply modules/gdscript/gdscript.cpp:2029]: Mmm. Yeah, calling it once should work. I'll let the `finalizing` variable there, just to be sure that it's not called twice.

Comment (akien-mga) [reply modules/gdscript/gdscript.cpp:2029]: I guess there's no need for a new `finalize()` method now and it can go in `finish()` directly?

Comment (adamscott) [reply modules/gdscript/gdscript.cpp:2029]: Yes. I was inspired by `csharp_script.cpp`, which explains a lot, but yes, I'll transfer everything into `finish()`.

https://github.com/godotengine/godot/blob/bcc061edaeb8676b82dba0d857cfbf66638071b5/modules/mono/csharp_script.cpp#L128-L140

Comment (akien-mga) [reply modules/gdscript/gdscript.cpp]: Maybe @neikeq can give some input then, there might be a good reason to still call `finalize()` in both `finish()` and the destructor.

File: modules/gdscript/gdscript.cpp [hunk 4]
```diff
@@ -2019,6 +2019,41 @@ Error GDScriptLanguage::execute_file(const String &p_path) {
 }
 
 void GDScriptLanguage::finish() {
+	if (_call_stack) {
+		memdelete_arr(_call_stack);
```
Comment (kleonc) [inline modules/gdscript/gdscript.cpp:2023]: Just to be safe:
```suggestion
		memdelete_arr(_call_stack);
		_call_stack = nullptr;
```

File: scene/resources/shape_2d.cpp [hunk 5]
```diff
@@ -124,7 +124,5 @@ Shape2D::Shape2D(const RID &p_rid) {
 }
 
 Shape2D::~Shape2D() {
-	if (PhysicsServer2D::get_singleton() != nullptr) {
-		PhysicsServer2D::get_singleton()->free(shape);
-	}
+	PhysicsServer2D::get_singleton()->free(shape);
```
Comment (kleonc) [inline scene/resources/shape_2d.cpp:127]: Don't we still want a guard in here? An error might be preferred over a crash in case something will go wrong.
cc @akien-mga
```suggestion
	ERR_FAIL_NULL(PhysicsServer2D::get_singleton());
	PhysicsServer2D::get_singleton()->free(shape);
```

Comment (adamscott) [reply scene/resources/shape_2d.cpp:127]: The guard initially didn't exist at all, as most of the code base.

File: modules/gdscript/gdscript.cpp (hunk 3 above)
Comment (neikeq) [reply modules/gdscript/gdscript.cpp]: > Maybe @neikeq can give some input then, there might be a good reason to still call `finalize()` in both `finish()` and the destructor.

I don't really remember, to be honest, and I'm afraid changing it could cause an issue. I wish I had left an explanatory comment there...

The reason it's a different method (`finalize`) is because clang-tidy warns when calling virtual methods (`finish`) from the destructor.

File: modules/gdscript/gdscript.cpp (hunk 4 above)
Comment (adamscott) [reply modules/gdscript/gdscript.cpp:2023]: Thanks!

File: scene/resources/shape_2d.cpp (hunk 5 above)
Comment (adamscott) [reply scene/resources/shape_2d.cpp:128]: Thanks!

**Comment by adamscott** [comment]
@kleonc I added you as co-author of the PR.

**Comment by kleonc** [comment]
> @kleonc I added you as co-author of the PR.

Barely did anything but sure, fine for me. Gotta be able to blame someone for these changes. :smile:

File: modules/gdscript/gdscript.h [hunk 6]
```diff
@@ -341,6 +341,8 @@ class GDScriptLanguage : public ScriptLanguage {
 	HashMap<StringName, int> globals;
 	HashMap<StringName, Variant> named_globals;
 
+	bool finalizing = false;
```
Comment (akien-mga) [inline modules/gdscript/gdscript.h:344]: Unused variable (I thought our warnings would catch this...).

Comment (adamscott) [reply modules/gdscript/gdscript.h:344]: Removed it!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by adamscott** [comment]
@akien-mga Thanks for the review! 😊
