### PR TITLE
Defend against directories without trailing slashes

### LINKED ISSUE #103992: Folder Creation fails(Show in File System) : New Folder (Could not create folder: Can't create)
### Tested versions

Godot v4.4.stable - Windows 10 (build 19045) - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - NVIDIA GeForce GTX 1650 (NVIDIA; 32.0.15.7260) - AMD Ryzen 3 3100 4-Core Processor (8 threads)

### System information

Godot v4.4.stable - Windows 10 (build 19045) - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - NVIDIA GeForce GTX 1650 (NVIDIA; 32.0.15.7260) - AMD Ryzen 3 3100 4-Core Processor (8 threads)

### Issue description

Folder Creation fails when show in File System clicked and then right clicked > New Folder (Could not create folder: Can't create)

### Steps to reproduce

From Scene Tab > Click Show in File System 
Right Click in File System > New Folder 
(Could not create folder: Can't create)

### Minimal reproduction project (MRP)

Any simple project would work with a saved scene.

### PR DESCRIPTION
**Pull request by precup**
Fixes #103992

`FileSystemDock::create_directory` can get called with a `base_dir` that don't have a trailing slash in a couple ways.  It seemed like a footgun for it to require a trailing slash, so I fixed the issue by making it tolerant to either formatting. 

After that, I audited similar usages of trim combined with paths in the rest of the codebase since this seems like an easy mistake to make, and the editor_file_system change addresses the only one that seemed similarly easy to make a mistake with and is a cheap enough addition it seemed reasonable to add defensively.

This largely occurs because `String::get_base_dir` returns a result without a trailing slash. Since this is also a `base_dir`, it seems like it *should* accept things straight from `String::get_base_dir`.

### CODE REVIEW

File: editor/editor_file_system.cpp [hunk 1]
```diff
@@ -3437,7 +3437,7 @@ Error EditorFileSystem::make_dir_recursive(const String &p_path, const String &p
 	ERR_FAIL_NULL_V(parent, ERR_FILE_NOT_FOUND);
 	folders_to_sort.insert(parent->get_instance_id());
 
-	const PackedStringArray folders = p_path.trim_prefix(path).trim_suffix("/").split("/");
+	const PackedStringArray folders = p_path.trim_prefix(path).trim_suffix("/").split("/", false);
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:3440]: Doesn't this make trimming the suffix redundant?

File: editor/filesystem_dock.cpp [hunk 2]
```diff
@@ -2743,7 +2743,13 @@ void FileSystemDock::focus_on_filter() {
 }
 
 void FileSystemDock::create_directory(const String &p_path, const String &p_base_dir) {
-	Error err = EditorFileSystem::get_singleton()->make_dir_recursive(p_path.trim_prefix(p_base_dir), p_base_dir);
+	String trimmed_path = p_path.trim_prefix(p_base_dir);
+	if (!p_base_dir.is_empty()) {
+		// Trims off the joining '/' if the base didn't end with one. If the base did have it
+		// and there's two slashes, the empty directory is safe to trim off anyways.
+		trimmed_path = trimmed_path.trim_prefix("/");
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:2750]: You could change it to something like
```suggestion
	String trimmed_path = p_path;
	if (!p_base_dir.is_empty()) {
		// Trims off the joining '/' if the base didn't end with one. If the base did have it
		// and there's two slashes, the empty directory is safe to trim off anyways.
		trimmed_path = trimmed_path.trim_prefix(p_base_dir).trim_prefix("/");
```
This avoids potential empty trim (though not sure if it can even happen).

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
For the record, your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

**Comment by precup** [comment]
> For the record, your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

Ah, good catch, thanks. I hadn't added my work email to this GitHub account, fixed.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
