### PR TITLE
Fixing tilemap rotation for non top-left tiles.

### LINKED ISSUE #11876: Tilemap rotation and mirror broke the collision
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Master branch

**Issue description:**
Open isometric example project, run it with debug collision visible, go into the door which is mirrored, the collision is not in right place. This bug only on master branch (v3), I've tried with v2.x and everything is fine

image

### PR DESCRIPTION
**Pull request by Nibodhika**
Fixes #11876. It still seems wrong, but now it behaves the same as in 2.x.

### CODE REVIEW

File: scene/2d/tile_map.cpp [hunk 1]
```diff
@@ -459,10 +459,12 @@ void TileMap::_update_dirty_quadrants() {
 					Transform2D xform;
 					xform.set_origin(offset.floor());
 
-					Vector2 shape_ofs = tile_set->tile_get_shape_transform(c.id, 0).get_origin();
+					Vector2 shape_ofs = tile_set->tile_get_shape_offset(c.id);
 
 					_fix_cell_transform(xform, c, shape_ofs + center_ofs, s);
 
+					//xform *= shapes[i].shape_transform;
```
Comment (akien-mga) [inline scene/2d/tile_map.cpp]: Please remove commented out code. If there's a reason to keep it, there must be a comment explaining why.

File: scene/resources/tile_set.cpp [hunk 2]
```diff
@@ -313,6 +311,16 @@ Transform2D TileSet::tile_get_shape_transform(int p_id, int p_shape_id) const {
 	return Transform2D();
 }
 
+void TileSet::tile_set_shape_offset(int p_id, const Vector2 &p_offset) {
+	Transform2D transform = tile_get_shape_transform(p_id,0);
```
Comment (akien-mga) [inline scene/resources/tile_set.cpp]: Style issue here (and on line 321): https://travis-ci.org/godotengine/godot/jobs/301115760

**Comment by akien-mga** [comment]
Please squash the commits together when the style issue is fixed ([PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request)).

**Comment by Nibodhika** [comment]
I think I did something wrong on the rebase because there's now another commit appearing in the pr that is not mine, altough mine were squashed.

**Comment by akien-mga** [comment]
Try to rebase again on `upstream/master`.

**Comment by Nibodhika** [comment]
Done, thanks for the patience

**Review by akien-mga — DISMISSED** [review]

File: scene/2d/tile_map.cpp [hunk 3]
```diff
@@ -459,9 +459,9 @@ void TileMap::_update_dirty_quadrants() {
 					Transform2D xform;
 					xform.set_origin(offset.floor());
 
-					_fix_cell_transform(xform, c, center_ofs, s);
+					Vector2 shape_ofs = tile_set->tile_get_shape_offset(c.id);
```
Comment (bojidar-bg) [inline scene/2d/tile_map.cpp]: You should use `i` as well, since different tiles can have different shape offsets.

File: scene/resources/tile_set.cpp [hunk 4]
```diff
@@ -313,6 +311,16 @@ Transform2D TileSet::tile_get_shape_transform(int p_id, int p_shape_id) const {
 	return Transform2D();
 }
 
+void TileSet::tile_set_shape_offset(int p_id, const Vector2 &p_offset) {
```
Comment (bojidar-bg) [inline scene/resources/tile_set.cpp]: You should take `p_shape_id` as well, instead of hardcoding id = 0.

**Review by bojidar-bg — CHANGES_REQUESTED** [review]
Tested on a test project of mine, which had multiple shapes per tile, some of them were still off.

**Comment by Nibodhika** [comment]
Sorry about the .h, must have lost it on the rebase.

**Comment by Nibodhika** [comment]
I submitted the requested changes yesterday, I guess there was no notification because I amended the previous commit.
