### PR TITLE
Fix analyzer pushing `SHADOWED_VARIABLE` warning for members shadowed in subclass

### LINKED ISSUE #74395: SHADOWED_VARIABLE warning is unclear for derived classes
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Steam OS Holo, Steam Deck

### Issue description

The SHADOWED_VARIABLE warning is unclear when the shadowed variable belongs to a user-defined base class.

**Base.gd**
```gdscript
extends Node

var inherited

func foo(name : String):
	pass
``` 

**Derived.gd**
```gdscript
extends "res://Base.gd"

var shadowed

func bar(inherited):
	pass

func baz(shadowed):
	pass
```

The use of `name` in `Base` triggers a very clear SHADOWED_VARIABLE_BASE_CLASS warning:
```
W 0:00:00:0492   The local function parameter "name" is shadowing an already-declared property at the base class "Node".
  <GDScript Error>SHADOWED_VARIABLE_BASE_CLASS
  <GDScript Source>Base.gd:5
```

However, the use of `inherited` in `Derived` triggers a SHADOWED_VARIABLE warning that does not reference the base class:
```
W 0:00:00:0493   The local function parameter "inherited" is shadowing an already-declared variable at line 3.
  <GDScript Error>SHADOWED_VARIABLE
  <GDScript Source>Derived.gd:5
```

To demonstrate how confusing this could be, I've deliberately set things up here such that `shadowed` triggers a warning pointing to the same line number, despite shadowing a different variable defined in a different class:
```
W 0:00:00:0493   The local function parameter "shadowed" is shadowing an already-declared variable at line 3.
  <GDScript Error>SHADOWED_VARIABLE
  <GDScript Source>Derived.gd:8
```

### Steps to reproduce

Run the minimal reproduction project.

### Minimal reproduction project

[ShadowedVariables.zip](https://github.com/godotengine/godot/files/10889723/ShadowedVariables.zip)

### PR DESCRIPTION
**Pull request by girdenis-p**
This fixes #74395. It does this by comparing the class which contains the shadowed member with the class containing the variable, and pushing the `SHADOWED_VARIABLE` warning only if the classes are the same, otherwise the `SHADOWED_VARIABLE_BASE_CLASS` warning is pushed.

Additionally, `SHADOWED_VARIABLE_BASE_CLASS` can now take an extra symbol which helps to specify the line for non native base class.

Comments and docs have been updated to highlight that these warnings are related to shadowed members in the concerning class instead of just shadowed variables.

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -5839,12 +5839,23 @@ void GDScriptAnalyzer::is_shadowing(GDScriptParser::IdentifierNode *p_identifier
...
+
+					parser->push_warning(p_identifier, GDScriptWarning::SHADOWED_VARIABLE_BASE_CLASS, p_context, p_identifier->name, current_parent_class->get_member(name).get_type_name(), itos(current_parent_class->get_member(name).get_line()), current_class_name);
+					return;
+				}
+				parser->push_warning(p_identifier, GDScriptWarning::SHADOWED_VARIABLE, p_context, p_identifier->name, current_parent_class->get_member(name).get_type_name(), itos(current_parent_class->get_member(name).get_line()));
 				return;
 			}
-			base_class = base_class->base_type.class_type;
+			current_parent_class = current_parent_class->base_type.class_type;
 		}
```
Comment (dalexeev) [inline modules/gdscript/gdscript_analyzer.cpp:5859]: This is ok, but for better readability I would rewrite this fragment as follows:

<details>
<summary>Details</summary>

```c++
	const GDScriptParser::DataType current_class_type = parser->current_class->get_datatype();

	if (p_in_local_scope) {
		GDScriptParser::ClassNode *base_class = current_class_type.class_type;

		if (base_class != nullptr) {
			if (base_class->has_member(name)) {
				parser->push_warning(p_identifier, GDScriptWarning::SHADOWED_VARIABLE, p_context, p_identifier->name, base_class->get_member(name).get_type_name(), itos(base_class->get_member(name).get_line()));
				return;
			}
			base_class = base_class->base_type.class_type;
		}

		while (base_class != nullptr) {
			if (base_class->has_member(name)) {
				String base_class_name = base_class->get_global_name();
				if (base_class_name.is_empty()) {
					base_class_name = base_class->fqcn;
				}
				parser->push_warning(p_identifier, GDScriptWarning::SHADOWED_VARIABLE_BASE_CLASS, p_context, p_identifier->name, base_class->get_member(name).get_type_name(), itos(base_class->get_member(name).get_line()), base_class_name);
				return;
			}
			base_class = base_class->base_type.class_type;
		}
	}

	StringName native_base_class = current_class_type.native_type;
	while (native_base_class != StringName()) {
		ERR_FAIL_COND_MSG(!class_exists(native_base_class), "Non-existent native base class.");

		if (ClassDB::has_method(native_base_class, name, true)) {
			parser->push_warning(p_identifier, GDScriptWarning::SHADOWED_VARIABLE_BASE_CLASS, p_context, p_identifier->name, "method", native_base_class);
			return;
		} else if (ClassDB::has_signal(native_base_class, name, true)) {
			parser->push_warning(p_identifier, GDScriptWarning::SHADOWED_VARIABLE_BASE_CLASS, p_context, p_identifier->name, "signal", native_base_class);
			return;
		} else if (ClassDB::has_property(native_base_class, name, true)) {
			parser->push_warning(p_identifier, GDScriptWarning::SHADOWED_VARIABLE_BASE_CLASS, p_context, p_identifier->name, "property", native_base_class);
			return;
		} else if (ClassDB::has_integer_constant(native_base_class, name, true)) {
			parser->push_warning(p_identifier, GDScriptWarning::SHADOWED_VARIABLE_BASE_CLASS, p_context, p_identifier->name, "constant", native_base_class);
			return;
		} else if (ClassDB::has_enum(native_base_class, name, true)) {
			parser->push_warning(p_identifier, GDScriptWarning::SHADOWED_VARIABLE_BASE_CLASS, p_context, p_identifier->name, "enum", native_base_class);
			return;
		}
		native_base_class = ClassDB::get_parent_class(native_base_class);
	}
```

</details>

Note that you can move the following definitions (with renames) below, closer to where they are used:

```c++
	GDScriptParser::DataType base = parser->current_class->get_datatype();
	GDScriptParser::ClassNode *base_class = base.class_type;
```

File: modules/gdscript/gdscript_warning.cpp [hunk 2]
```diff
@@ -64,7 +64,10 @@ String GDScriptWarning::get_message() const {
 			return vformat(R"(The local %s "%s" is shadowing an already-declared %s at line %s.)", symbols[0], symbols[1], symbols[2], symbols[3]);
```
Comment (dalexeev) [inline modules/gdscript/gdscript_warning.cpp:64]: Perhaps this makes sense for clarification and consistency?

```suggestion
			return vformat(R"(The local %s "%s" is shadowing an already-declared %s at line %s in the current class.)", symbols[0], symbols[1], symbols[2], symbols[3]);
```

File: modules/gdscript/gdscript_warning.cpp [hunk 3]
```diff
@@ -64,7 +64,10 @@ String GDScriptWarning::get_message() const {
...
 		case SHADOWED_VARIABLE_BASE_CLASS:
 			CHECK_SYMBOLS(4);
-			return vformat(R"(The local %s "%s" is shadowing an already-declared %s at the base class "%s".)", symbols[0], symbols[1], symbols[2], symbols[3]);
+			if (symbols.size() < 5) {
+				return vformat(R"(The local %s "%s" is shadowing an already-declared %s at the base class "%s".)", symbols[0], symbols[1], symbols[2], symbols[3]);
```
Comment (dalexeev) [inline modules/gdscript/gdscript_warning.cpp:68]:
```suggestion
				return vformat(R"(The local %s "%s" is shadowing an already-declared %s in the base class "%s".)", symbols[0], symbols[1], symbols[2], symbols[3]);
```

Or should there be "at" below too?

File: modules/gdscript/gdscript_warning.h [hunk 4]
```diff
@@ -53,8 +53,8 @@ class GDScriptWarning {
 		UNUSED_PRIVATE_CLASS_VARIABLE, // Class variable is declared private ("_" prefix) but never used in the class.
 		UNUSED_PARAMETER, // Function parameter is never used.
 		UNUSED_SIGNAL, // Signal is defined but never explicitly used in the class.
-		SHADOWED_VARIABLE, // Variable name shadowed by other variable in same class.
-		SHADOWED_VARIABLE_BASE_CLASS, // Variable name shadowed by other variable in some base class.
+		SHADOWED_VARIABLE, // Member shadowed by other variable in same class.
+		SHADOWED_VARIABLE_BASE_CLASS, // Variable shadows other member in some base class.
```
Comment (dalexeev) [inline modules/gdscript/gdscript_warning.h:57]:
```suggestion
		SHADOWED_VARIABLE, // A local variable/constant or enum member shadows a current class member.
		SHADOWED_VARIABLE_BASE_CLASS, // A local variable/constant or enum member shadows a base class member.
```

File: modules/gdscript/tests/scripts/analyzer/warnings/local_variable_shadows_base_member.gd
Comment (dalexeev) [inline modules/gdscript/tests/scripts/analyzer/warnings/local_variable_shadows_base_member.gd:1]: Please extend the test to show the `SHADOWED_VARIABLE` warning, and also the `SHADOWED_VARIABLE_BASE_CLASS` for shadowing native members. Also note that there is `modules/gdscript/tests/scripts/analyzer/warnings/shadowning.gd`, perhaps we should update that instead of adding a new file.

File: doc/classes/ProjectSettings.xml [hunk 5]
```diff
@@ -561,10 +561,10 @@
 			When set to [code]warn[/code] or [code]error[/code], produces a warning or an error respectively when defining a local or member variable, signal, or enum that would have the same name as a built-in function or global class name, thus shadowing it.
 		</member>
 		<member name="debug/gdscript/warnings/shadowed_variable" type="int" setter="" getter="" default="1">
-			When set to [code]warn[/code] or [code]error[/code], produces a warning or an error respectively when defining a local or member variable that would shadow a member variable that the class defines.
+			When set to [code]warn[/code] or [code]error[/code], produces a warning or an error respectively when defining a local or class variable that would shadow a member that the class defines.
```
[the remark this answers is not in the document]
Comment (girdenis-p) [reply doc/classes/ProjectSettings.xml:564]: This warning doesn't seem to trigger if an enum member shadows instead what seemed to happen before this PR is that an error was pushed saying the member already exists in a parent class. If this is intentional, should I change the doc to the above but remove the enum member part?

File: doc/classes/ProjectSettings.xml [hunk 6]
```diff
@@ -561,10 +561,10 @@
...
 		</member>
 		<member name="debug/gdscript/warnings/shadowed_variable_base_class" type="int" setter="" getter="" default="1">
-			When set to [code]warn[/code] or [code]error[/code], produces a warning or an error respectively when defining a local or subclass member variable that would shadow a variable that is inherited from a parent class.
+			When set to [code]warn[/code] or [code]error[/code], produces a warning or an error respectively when defining a local or subclass variable that would shadow a member that is inherited from a parent class.
```
[the remark this answers is not in the document]
Comment (girdenis-p) [reply doc/classes/ProjectSettings.xml:567]: A similar behaviour happens as I described above for SHADOWED_VARIABLE but an error is pushed saying that the member is already used in the parent class. If this is intentional, should I change the doc to the above but remove the enum member part?

[the remark this answers is not in the document]
Comment (dalexeev) [reply doc/classes/ProjectSettings.xml:567]: Judging by the code, this is supposed to work:

https://github.com/godotengine/godot/blob/87318a2fb7fffeb72adca934e31915be077c3d1f/modules/gdscript/gdscript_analyzer.cpp#L1145-L1148

If for some reason it doesn't work, we should fix it. If you want to do it, you can fix it within this PR.

File: doc/classes/ProjectSettings.xml (hunk 5 above)
[the remark this answers is not in the document]
Comment (dalexeev) [reply doc/classes/ProjectSettings.xml:564]: Judging by the code, this is supposed to work:

https://github.com/godotengine/godot/blob/87318a2fb7fffeb72adca934e31915be077c3d1f/modules/gdscript/gdscript_analyzer.cpp#L1145-L1148

If for some reason it doesn't work, we should fix it. If you want to do it, you can fix it within this PR.

File: modules/gdscript/gdscript_warning.cpp (hunk 2 above)
Comment (girdenis-p) [reply modules/gdscript/gdscript_warning.cpp:64]: I will have to update current tests to reflect this update, is this okay to be done?

File: doc/classes/ProjectSettings.xml (hunk 5 above)
[the remark this answers is not in the document]
Comment (girdenis-p) [reply doc/classes/ProjectSettings.xml:564]: I believe it is impossible to reach line 1147 because the parser would parse elements of an unnamed enum as enum_values so I don't know in what case `member.m_enum->identifier->name == StringName()` could be true.

Can we clarify here? By enum members do we mean members that are enums or enum values? Because the comment and code seems to try to see if enum values are shadowing a member.

File: modules/gdscript/gdscript_warning.cpp (hunk 2 above)
Comment (dalexeev) [reply modules/gdscript/gdscript_warning.cpp:64]: Yes, otherwise the tests will fail.

File: doc/classes/ProjectSettings.xml (hunk 5 above)
[the remark this answers is not in the document]
Comment (dalexeev) [reply doc/classes/ProjectSettings.xml:564]: Unfortunately, we don't have a unified naming for enum elements. We call them "constants", "enum values", "enum members". Also note that there are unnamed enums, their elements fall through to the outer scope.

[the remark this answers is not in the document]
Comment (Mickeon) [reply doc/classes/ProjectSettings.xml:564]: "[EnumName] constants" is the most consistent in the class reference and is what should be used.

[the remark this answers is not in the document]
Comment (girdenis-p) [reply doc/classes/ProjectSettings.xml:564]: I am wondering whether if would be possible to reach line 1147 because to reach the condition. 
`member.type` would have to be `GDScriptParser::ClassNode::Member::ENUM`. However if the parser was parsing an unnamed enum then this case block would never be entered. Instead the case block for `GDScriptParser::ClassNode::Member::ENUM_VALUE` would be entered for elements of the unnamed enum. I have confirmed this through the editor by logging messages once inside the different cases.

I may be misunderstanding here and I would appreciate if you could show me a time when line 1147 is reached.

So I am wondering if it makes sense for the shadowing check to be moved to the case for `GDScriptParser::ClassNode::Member::ENUM_VALUE`. However, if it true that the check mentioned never happened before then I wonder if this warning is redundant due to the fact that we check for member name conflict in and this pushes an error:
```
case GDScriptParser::ClassNode::Member::ENUM_VALUE: {
	member.enum_value.identifier->set_datatype(resolving_datatype);

	if (member.enum_value.custom_value) {
		check_class_member_name_conflict(p_class, member.enum_value.identifier->name, member.enum_value.custom_value);
```

[the remark this answers is not in the document]
Comment (dalexeev) [reply doc/classes/ProjectSettings.xml:564]: Probably the warning for unnamed enum members is not needed at all. Sorry for the confusion.

[the remark this answers is not in the document]
Comment (girdenis-p) [reply doc/classes/ProjectSettings.xml:564]: Is there something we can fix for this issue regarding SHADOWED_GLOBAL_INDENTIFIER or should we open an issue specifically for that once we have some reproducible behaviour?

[the remark this answers is not in the document]
Comment (dalexeev) [reply doc/classes/ProjectSettings.xml:564]: You are right, `SHADOWED_VARIABLE` and `SHADOWED_VARIABLE_BASE_CLASS` will never be produced for enum members, so it shouldn't be in the documentation. As for `SHADOWED_GLOBAL_IDENTIFIER`, we could fix that in a separate PR, as you see fit.

[the remark this answers is not in the document]
Comment (girdenis-p) [reply doc/classes/ProjectSettings.xml]: I updated the docs to mentioned local variables and constants but not enums.

File: doc/classes/ProjectSettings.xml (hunk 6 above)
[the remark this answers is not in the document]
Comment (girdenis-p) [reply doc/classes/ProjectSettings.xml]: I updated the docs to mention local variables/constants but not enums

File: modules/gdscript/gdscript_analyzer.cpp (hunk 1 above)
Comment (girdenis-p) [reply modules/gdscript/gdscript_analyzer.cpp]: I have changed the implementation to match your rewrite.

File: modules/gdscript/gdscript_warning.cpp (hunk 3 above)
Comment (girdenis-p) [reply modules/gdscript/gdscript_warning.cpp]: Updated to "in"

File: modules/gdscript/tests/scripts/analyzer/warnings/local_variable_shadows_base_member.gd
Comment (girdenis-p) [reply modules/gdscript/tests/scripts/analyzer/warnings/local_variable_shadows_base_member.gd:1]: I have deleted the previously made tests and expanded the tests in `modules/gdscript/tests/scripts/analyzer/warnings/shadowning.gd`.

File: modules/gdscript/tests/scripts/analyzer/warnings/shadowing_base.notest.gd [hunk 7]
```diff
@@ -0,0 +1,7 @@
+class_name ShadowingBase
+
+const base_const_member = 1
```
Comment (dalexeev) [inline modules/gdscript/tests/scripts/analyzer/warnings/shadowing_base.notest.gd:3]: Looks unused.

File: modules/gdscript/gdscript_warning.cpp [hunk 8]
```diff
@@ -61,10 +61,13 @@ String GDScriptWarning::get_message() const {
...
 			CHECK_SYMBOLS(4);
-			return vformat(R"(The local %s "%s" is shadowing an already-declared %s at line %s.)", symbols[0], symbols[1], symbols[2], symbols[3]);
+			return vformat(R"(The local %s "%s" is shadowing an already-declared %s at line %s in the current class.)", symbols[0], symbols[1], symbols[2], symbols[3]);
 		case SHADOWED_VARIABLE_BASE_CLASS:
 			CHECK_SYMBOLS(4);
-			return vformat(R"(The local %s "%s" is shadowing an already-declared %s at the base class "%s".)", symbols[0], symbols[1], symbols[2], symbols[3]);
+			if (symbols.size() < 5) {
+				return vformat(R"(The local %s "%s" is shadowing an already-declared %s in the base class "%s".)", symbols[0], symbols[1], symbols[2], symbols[3]);
+			}
+			return vformat(R"(The local %s "%s" is shadowing an already-declared %s at line %s in the base class "%s".)", symbols[0], symbols[1], symbols[2], symbols[3], symbols[4]);
```
Comment (dalexeev) [inline modules/gdscript/gdscript_warning.cpp:70]:
```suggestion
			if (symbols.size() > 4) {
				return vformat(R"(The local %s "%s" is shadowing an already-declared %s at line %s in the base class "%s".)", symbols[0], symbols[1], symbols[2], symbols[3], symbols[4]);
			}
			return vformat(R"(The local %s "%s" is shadowing an already-declared %s in the base class "%s".)", symbols[0], symbols[1], symbols[2], symbols[3]);
```

Nitpick: first check the array size and then access the element, rather than implicitly exclude the possibility of going out of bounds.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 9]
```diff
@@ -5809,8 +5809,7 @@ void GDScriptAnalyzer::validate_call_arg(const List<GDScriptParser::DataType> &p
 #ifdef DEBUG_ENABLED
 void GDScriptAnalyzer::is_shadowing(GDScriptParser::IdentifierNode *p_identifier, const String &p_context, const bool p_in_local_scope) {
 	const StringName &name = p_identifier->name;
-	GDScriptParser::DataType base = parser->current_class->get_datatype();
-	GDScriptParser::ClassNode *base_class = base.class_type;
+	const GDScriptParser::DataType current_class_type = parser->current_class->get_datatype();
```
Comment (dalexeev) [inline modules/gdscript/gdscript_analyzer.cpp:5812]: Nitpick: this isn't used until line 5841. It's recommended to declare variables as close to the first use as possible, if it doesn't affect anything.

**Review by dalexeev — APPROVED** [review]
Looks good to me. It would be great to check the grammar in documentation and warning messages.

File: modules/gdscript/tests/scripts/analyzer/warnings/shadowing_base.notest.gd (hunk 7 above)
Comment (girdenis-p) [reply modules/gdscript/tests/scripts/analyzer/warnings/shadowing_base.notest.gd:3]: I added a test cast for in the `shadowning.gd`.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 9 above)
Comment (girdenis-p) [reply modules/gdscript/gdscript_analyzer.cpp]: I added it above:
```
if (p_in_local_scope) {
	GDScriptParser::ClassNode *base_class = current_class_type.class_type;
```
this way it is accessible for `base_class` and `native_base_class` (defined later).

**Review by AThousandShips — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first contribution! 🎉
