### PR TITLE
Fix 3D editor gizmos appearing in GI following default GI mode change

### LINKED ISSUE #62670: SDFGI: World axes visible in reflections and cascades
### Godot version

4.0 Alpha 11

### System information

Windows 10, GTX1080, i7 6700

### Issue description

World axes show in SDFGI reflections and in cascade view when enabled.
Disabling requires reopening the scene to take effect.
SDFGI_WorldAxisReflectionBug
SDFGI_WorldAxisReflectionBug02

### Steps to reproduce

- Open new project
- Add CSG sphere
- Give it a fully reflective metallic material
- Activate SDFGI
- World axes will be visible in reflections of the sphere and in cascade view.

### Minimal reproduction project

[Uploading SDFGI_AxisInReflectionsBug.zip…]()

### PR DESCRIPTION
**Pull request by Calinou**
This fixes a regression from https://github.com/godotengine/godot/pull/60935. Your gizmos are no longer *globally illuminated* now :slightly_smiling_face:

Here's what it looked like:

image

*Bugsquad edit:*
- Fixes #62670

### CODE REVIEW

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -3283,13 +3287,17 @@ void Node3DEditorViewport::_init_gizmo_instance(int p_idx) {
...
 
 		axis_gizmo_instance[i] = RS::get_singleton()->instance_create();
 		RS::get_singleton()->instance_set_base(axis_gizmo_instance[i], spatial_editor->get_axis_gizmo(i)->get_rid());
 		RS::get_singleton()->instance_set_scenario(axis_gizmo_instance[i], get_tree()->get_root()->get_world_3d()->get_scenario());
 		RS::get_singleton()->instance_set_visible(axis_gizmo_instance[i], true);
 		RS::get_singleton()->instance_geometry_set_cast_shadows_setting(axis_gizmo_instance[i], RS::SHADOW_CASTING_SETTING_OFF);
 		RS::get_singleton()->instance_set_layer_mask(axis_gizmo_instance[i], layer);
+		RS::get_singleton()->instance_geometry_set_flag(axis_gizmo_instance[i], RS::INSTANCE_FLAG_IGNORE_OCCLUSION_CULLING, true);
+		RS::get_singleton()->instance_geometry_set_flag(axis_gizmo_instance[i], RS::INSTANCE_FLAG_USE_BAKED_LIGHT, false);
+
```
Comment (akien-mga) [inline editor/plugins/node_3d_editor_plugin.cpp:3300]: Unnecessary empty line.

**Comment by akien-mga** [comment]
I feel like there's a lot of redundant code in there, maybe there could be a helper method to create a gizmo MeshInstance with all the default parameters set?

Like:
```cpp
RID Node3DEditorViewport::create_gizmo_instance(int p_idx, uint32_t p_layer) {
	RID rid = RS::get_singleton()->instance_create();
	RS::get_singleton()->instance_set_base(rid, spatial_editor->get_rotate_gizmo(p_idx)->get_rid());
	RS::get_singleton()->instance_set_scenario(rid, get_tree()->get_root()->get_world_3d()->get_scenario());
	RS::get_singleton()->instance_set_visible(rid, false);
	RS::get_singleton()->instance_geometry_set_cast_shadows_setting(rid, RS::SHADOW_CASTING_SETTING_OFF);
	RS::get_singleton()->instance_set_layer_mask(rid, p_layer);
	RS::get_singleton()->instance_geometry_set_flag(rid, RS::INSTANCE_FLAG_IGNORE_OCCLUSION_CULLING, true);
	RS::get_singleton()->instance_geometry_set_flag(rid, RS::INSTANCE_FLAG_USE_BAKED_LIGHT, false);
	return rid;
}

...

		move_plane_gizmo_instance[i] = create_gizmo_instance(i, layer);
		...
```

Needs checking that the code is indeed always the same.
```

**Comment by DarkKilauea** [comment]
Does this also fix gizmo plugins using `create_material` and `create_handle_material`, or were those not affected?

**Comment by Calinou** [comment]
> Does this also fix gizmo plugins using `create_material` and `create_handle_material`, or were those not affected?

I changed how gizmo instances are created in node_3d_editor_gizmos.cpp, so these should be fixed as well.

That said, from my testing, I only noticed the issue with editor origin lines, not individual node gizmos.

**Review by akien-mga — APPROVED** [review]
My refactorign suggestion could be done in a follow-up PR.

**Comment by akien-mga** [comment]
Thanks!
