### PR TITLE
Fix resource picker regression

### LINKED ISSUE #69356: Unable to use custom resources with the @tool hint.
### Godot version

4.0-dev(cdd99e9bec16db60efd894a06826f6fea139d00d)

### System information

Archlinux stable

### Issue description

Selecting a custom resource from the inspector fails with this error message:
```editor/editor_resource_picker.cpp:445 - Condition "!resp" is true. Breaking.```

### Steps to reproduce

- Create a script extending `Resource`, add a `class_name` and the `@tool` keyword.
- Create a script exporting the custom resource from previous step
- Instantiate it in a scene and try to assign a resource from the inspector.

### Minimal reproduction project

Minimal reproduction project: [debug_4.zip](https://github.com/godotengine/godot/files/10117319/debug_4.zip)

Open the test.tscn scene, select the node and try to assign it a resource from the inspector.

### PR DESCRIPTION
**Pull request by rune-scape**
ref-counted types weren't being referenced properly before calling `set_script()`

fixes https://github.com/godotengine/godot/issues/69356

### CODE REVIEW

File: editor/editor_data.cpp [hunk 1]
```diff
@@ -947,9 +947,9 @@ Variant EditorData::script_class_instance(const String &p_class) {
 	if (ScriptServer::is_global_class(p_class)) {
 		Ref<Script> script = script_class_load_script(p_class);
 		if (script.is_valid()) {
-			Object *obj = ClassDB::instantiate(script->get_instance_base_type());
+			Variant obj = ClassDB::instantiate(script->get_instance_base_type());
 			if (obj) {
-				obj->set_script(script);
+				obj.operator Object *()->set_script(script);
```
Comment (akien-mga) [inline editor/editor_data.cpp:952]: That looks pretty confusing, and warrants at least an explanatory comment.
Are you also sure that `if (obj)` will still work as intended now that it's checking a Variant instead of a pointer?

Comment (rune-scape) [reply editor/editor_data.cpp:952]: you're right, it is confusing, i'll add a comment
this was just reverted to what it was before (the Variant and cast part seemed weird and confusing and unecessary, so i changed it):
https://github.com/godotengine/godot/blob/c7ceb94e372216b1b033d7c2ac26d5b7545c4dac/editor/editor_data.cpp#L948-L952
and yes it will just do a null check:
https://github.com/godotengine/godot/blob/c7ceb94e372216b1b033d7c2ac26d5b7545c4dac/core/variant/variant.cpp#L933-L935

**Comment by akien-mga** [comment]
As discussed in #70311, this kind of issue warrants discussing the underlying problem of `RefCounted` vs `Object *`/`Variant`, but for the short term this PR is a good fix.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
