### PR TITLE
Revamp autoload creation

### LINKED ISSUE #10691: Autoload UI doesn't make it clear that its compatible with packedscenes.
### Describe the project you are working on

This is irrelevant to the proposal.

### Describe the problem or limitation you are having in your project

Someone in the discord mentioned that they wished it was possible to nest nodes in autoloads, but that it wasn't possible because you need to use a script. I informed them this was actually possible, and on a closer look I realize the UI makes no indication of this and only explicitly mentions scripts.

image

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Reword the path box to state both compatibilities.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

image

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is just a QOL UI change, and requires no work around.

### Is there a reason why this should be core and not an add-on in the asset library?

There is already so much information to learn about a game engine, and the UI should be careful not to imply incorrect information. The current UI does worse than no information by stating partial information, implying a restriction that does not exist.

 It could also make the UI more readable at a glance, separating information to the fields where it is relevant.

### LINKED ISSUE #17110: Project Settings : Autoload tab -- confusing layout, columns cut off, icon illegible
**Godot version:**
3.0.1

**OS/device including version:**
Windows 10 / Microsoft Surface Pro 4

**Issue description:**
3 usability issues in the Autoload dialog (see accompanying screenshot)

1) the input fields for node name and path are reversed from the order they appear in the table. Recommend keeping same order so user's mental model - established during input matches the table shown on-screen.

2) the 'Singleton' column is cut-off and the table columns don't appear to be adjustable.

3) the toggle icon for a node in the Singleton column is illegible - cannot tell whether on or off

**Steps to reproduce:**
1. open the settings dialog
2. click the autoload tab
3. add an autoload node

godot_301_settings_autoload_dialog

### PR DESCRIPTION
**Pull request by KoBeWi**
Closes #17110
Closes https://github.com/godotengine/godot-proposals/issues/10691
- Text fields are replaced with buttons:
  - Select Existing Script/Scene - select a scene or script that will be added as autoload. This is the previous browse option, except the autoload is added immediately
  - Create Script Autoload - creates a new script and adds as autoload. This already existed btw, the script dialog was opening when you tried to Add autoload without a path
  - Create Scene Autoload - same as above, but creates a scene. The UX is a bit awkward, because you need to go through 2 dialogs, but maybe it's fine

Autoload name is assigned automatically from file name (or root name in case of scene) and there is basic validation to create valid identifier, as otherwise you'll be met with an error dialog. Hopefully it won't be a big problem. If you don't like auto-generated name, you can rename the autoload by double-clicking it in Tree (although the default name is fine in most cases, hence the text inputs were mostly useless).

https://github.com/godotengine/godot/assets/2223172/b9876b15-8e4e-42f3-a6f4-41c3b667ef2b

I'm getting some errors about exclusive children™, though they already existed with the script dialog. Not sure how to fix.

### CODE REVIEW

**Comment by YeldhamDev** [comment]
Why are the buttons centered?

**Comment by KoBeWi** [comment]
> Why are the buttons centered?

There is an awkward empty space when they are aligned to one side.

**Comment by YeldhamDev** [comment]
> There is an awkward empty space when they are aligned to one side.

Still odd to have them like this, since everywhere else in the editor buttons tend to be aligned to one side when on the top.

**Comment by KoBeWi** [comment]
Less text and left align:
image

**Comment by tokengamedev** [comment]
Just want to check there was this scenario while selecting a script you can change the name of the node, which does not have to be the same name as the script (Ignore case)
I hope you can still edit the name of the Node.

Now couple of issues I found in 4.3:
1. Double clicking on the path of the Autoload or the directory icon in the list -> closes the window.
2. You should not be allowed to create two autoload variables with the same script file. Is there a use case to load the same script twice, then I may be wrong.

Also agree with @passivestar comments, I think `Create Script` and `Create Scene` will be fine as you are already under the autoload context

**Comment by KoBeWi** [comment]
> Double clicking on the path of the Autoload or the directory icon in the list -> closes the window.

That's intended. It opens the script in script editor.

> You should not be allowed to create two autoload variables with the same script file. Is there a use case to load the same script twice, then I may be wrong.

There is no obvious use-case, but it's not wrong either. No reason to prevent that I think.

> Also agree with passivestar comments, I think Create Script and Create Scene will be fine as you are already under the autoload context

image

**Comment by KoBeWi** [comment]
Rebased and fixed some errors. Autoload dialog will now use its own SceneCreateDialog and no longer open the scene when created.

**Comment by tokengamedev** [comment]
Thanks @KoBeWi for the update.

**Comment by Zshandi** [comment]
I would love to see this in the next release of Godot! Let me know if there's anything I could do to help make that a reality 🙂

I especially like the change to have it use its own dialog for both the scene and script, rather than re-using the filesystem dock one as it was previously doing! It still behaves weirdly in that you can click out of the pop-up and it goes behind the project settings, though I think that's a much larger problem than just this (which I'm guessing already has it's own Issue somewhere, unless it's already fixed on latest master?).

**Comment by KoBeWi** [comment]
Rebased.
I also deleted the Open button on the right, because you can double-click the path to do the same.
image

**Comment by Zshandi** [comment]
> Rebased. I also deleted the Open button on the right, because you can double-click the path to do the same.

Nice, hope it gets in soon then!

I'm personally partial to having more than one way to do things in UIs (more likely users will discover it), however in this case I feel it was also counter-intuitive that a folder icon opened the file itself (rather than just revealing it in the file system dock). Great work overall!

**Review by passivestar — APPROVED** [review]
Tested, works as expected and the UX is a clear improvement over the previous one

**Review by AdriaandeJongh — COMMENTED** [review]
Also tested this and found this little icon on hover (it doesn't do anything):
Screenshot 2026-03-05 at 09 42 11

And while we're at it: would be nice to give the headers a tooltip. Especially the Global Variable could use something along the lines of "If enabled, this autoload can be accessed by scripts through $Name where 'Name' is replaced with the name of the autoload".

File: editor/settings/editor_autoload_settings.cpp [hunk 1]
```diff
@@ -458,6 +399,56 @@ void EditorAutoloadSettings::init_autoloads() {
...
 
+void EditorAutoloadSettings::_autoload_file_selected(const String &p_path) {
+	_add_autoload(p_path.get_file().get_basename(), p_path);
+}
+
+void EditorAutoloadSettings::_scene_file_selected(const String &p_path) {
+	if (!scene_create_dialog) {
+		scene_create_dialog = memnew(SceneCreateDialog);
+		add_child(scene_create_dialog);
+		scene_create_dialog->connect("confirmed", callable_mp(this, &EditorAutoloadSettings::_scene_created));
```
Comment (AThousandShips) [inline editor/settings/editor_autoload_settings.cpp]:
```suggestion
		scene_create_dialog->connect(SceneStringName(confirmed), callable_mp(this, &EditorAutoloadSettings::_scene_created));
```

**Review by AdriaandeJongh — APPROVED** [review]
If the bug I mentioned above isn't in the scope of this PR, then the rest looks good to me.

**Review by akien-mga — APPROVED** [review]

**Comment by thottee** [comment]
Do I can use without mouse?
