### PR TITLE
Use monotonic clock for get_ticks_usec

### LINKED ISSUE #19393: Network time update causing Godot physics simulation to hang / speed up
**Godot version: 3.1 build from source**

**OS/device including version:**

Android 7.1.2 - Moto G 2nd gen GPU: Adreno 305

**Issue description:**

I've been having issues with _physics_process() running normally, then suddenly start running at more than twice the speed as if it's in fast forward. It looks very amusing and breaks lots of things. It keeps running like this until the process exits. I have similar problem using _process() where it just freezes and hangs instead. After some investigation with adb logcat, it appears that it all starts going wrong after this happens:

AlarmClock: AlarmInitReceiver android.intent.action.TIME_SET

This completely screws up the physics processing. These are sent if you have "Settings -> Date & time -> Use network-provided date and time" set. Switching this off, stops the problem from happening. On my home WiFi, this seems to be generated every few minutes, meaning, it breaks quite often. My home setup is just a typical setup. Nothing unusual. 

Not sure if there's anything that can be done here. It doesn't break other games made with (for example Unity). Maybe there physics processing needs some sort of sanity check between frames?

**Steps to reproduce:**

**Minimal reproduction project:**

### LINKED ISSUE #22041: Getting negative delta values for _process on Android
**Godot version:**
Godot 3.1 Alpha (commit bcba5a99cdb2debcd9a595a4e9e905809f65da10)

**OS/device including version:**
Xiaomi MI5 - Miui 9.6 (Android 8)

**Issue description:**
Toggling Android's "plane mode" on and off several times while some object is processing seems to cause Godot to give a delta value of -139812 for _process in some devices. Here's an illustration using the attached minimal project:

deltatest

Sometimes I only need toggling 1 or 2 times and sometimes I need many more. In some other Android devices I just get negative values close to 0, but they do not get stuck in that "negatively large" number.

Probably there're other ways to reproduce this but I haven't been able to find them. I've tried with other Android toggles or adding thousands of processing objects to slow down the frame rate but only the "plane mode" thing seems to trigger it for me.

**Steps to reproduce:**
1. Run the attached project on Android.
2. Toggle Android's "plane mode" mode on and off several times (rapidly or slowly, it doesn't matter).
3. Depending on the device (sometimes) you'll get:
   - Negative numbers close to 0 for delta parameter (in _process) just for a few frames, then it continues to work correctly (positive numbers again).
   - A delta value of -139812 all the time, so the game gets glitched.

**Minimal reproduction project:**
[DeltaTest.zip](https://github.com/godotengine/godot/files/2380257/DeltaTest.zip)

### PR DESCRIPTION
**Pull request by Faless**
Fix `get_ticks_usec`/`get_ticks_msec` on Unix systems.

Use `clock_get_time` on Unix. (`CLOCK_MONOTONIC_RAW` on Linux, `CLOCK_MONOTONIC` on other systems).
Use `mach_absolute_time` where `__APPLE__` is defined (should be OSX and iPhone).
Windows is unaffected, but should also be unaffected by the issue itself because it uses `QueryPerformanceCounter`.

It compiles for Mac, but I need someone to test it, because I don't have a Mac (cross compiles fine, but need to check if it actually works as expected... it should!),

Some references:
https://hg.libsdl.org/SDL/file/b504b29c3831/src/timer/unix/SDL_systimer.c
https://github.com/ThomasHabets/monotonic_clock

Closes #19393 
*Bugsquad edit:* Fixes #22041.

EDIT: How to test? Run your game, and let it print delta time in frames. Send your system clock back in time of few hours.
The `delta` time should be unaffected (instead of starting to be negative like it does without this patch)

### CODE REVIEW

**Comment by allkhor** [comment]
Also fixed #22041, after this commit i can't reproduce bug.

**Comment by samuelpedrajas** [comment]
Yep I can confirm after this commit I can't reproduce #22041.
First I tested it again on master commit 2893b5a6bee1f1185c52d4a46734b2741acbb52c and I was able to reproduce it. Then I pulled this PR and tested it again and the bug is gone. Thanks!

File: drivers/unix/os_unix.cpp [hunk 1]
```diff
@@ -246,10 +253,29 @@ void OS_Unix::delay_usec(uint32_t p_usec) const {
...
+			ERR_FAIL_V(1);
+		}
+		scale = (double)info.numer / (double)info.denom;
+	}
 
-	uint64_t longtime = (uint64_t)tv_now.tv_usec + (uint64_t)tv_now.tv_sec * 1000000L;
+	uint64_t longtime = mach_absolute_time() * scale;
+#else
+	struct timespec tv_now = { 0, 0 };
+	if (clock_gettime(GODOT_CLOCK, &tv_now) != 0 && ticks_start == 0) {
```
Comment (akien-mga) [inline drivers/unix/os_unix.cpp]: I wonder if it would be better to use directly:
```
ERR_EXPLAIN("CLOCK IS NOT WORKING!");
ERR_FAIL_COND_V(clock_gettime(GODOT_CLOCK, &tv_now) != 0 && ticks_start == 0, 1);
```
to benefit from the `unlikely()` in `ERR_FAIL_COND*`? (CC @hpvb)

It's arguably less pretty but since this is called in the game loop, might be worth the optimization.

Comment (akien-mga) [reply drivers/unix/os_unix.cpp]: That said allocating memory for a string in `ERR_EXPLAIN` might cost much than the lack of usage of `unlikely()`, so nevermind my comment :P

Comment (Faless) [reply drivers/unix/os_unix.cpp]: Yeah, actually, that was my main concern about it. But there might still be a better solution...

**Comment by akien-mga** [comment]
Thanks!

**Comment by marcelofg55** [comment]
My game is running weirdly after this PR on OS X, it runs like with a fast forward effect.

**Comment by Faless** [comment]
@marcelofg55 I think I might have screwed up the math

**Comment by Faless** [comment]
@marcelofg55 can you try:
https://github.com/Faless/godot/tree/fix_mac_time

**Comment by marcelofg55** [comment]
@Faless I've added #22424, both changes do pretty much the same :)
