### PR TITLE
Parser: Fix "trying to resolve type of null node" when missing condition.

### LINKED ISSUE #115239: Typing `while` anywhere in a script produces an error
### Tested versions

Reproducible in `4.5.1.stable`, `4.6.rc2`

### System information

Godot v4.6.rc2 - Windows 11 (build 26100) - Multi-window, 1 monitor - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 32.0.15.9159) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 threads) - 15.92 GiB memory

### Issue description

Upon typing the last letter in the `while` keyword anywhere in a script, you get an error that says `Trying to resolve type of a null node.`

https://github.com/user-attachments/assets/2a1a4b43-00ab-45e4-a399-817a013cdc38

### Steps to reproduce

See description.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by MattiaZir**
fixes #115239

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -2373,7 +2373,9 @@ void GDScriptAnalyzer::resolve_for(GDScriptParser::ForNode *p_for) {
 }
 
 void GDScriptAnalyzer::resolve_while(GDScriptParser::WhileNode *p_while) {
-	resolve_node(p_while->condition, false);
+	if (p_while->condition) {
+		resolve_node(p_while->condition, false);
+	}
```
Comment (dalexeev) [inline modules/gdscript/gdscript_analyzer.cpp]:
```suggestion
	reduce_expression(p_while->condition);
```

Also here:

https://github.com/godotengine/godot/blob/d5edd4a59287679ae390149c0c1c3397aeb5f502/modules/gdscript/gdscript_analyzer.cpp#L2259

Comment (MattiaZir) [reply modules/gdscript/gdscript_analyzer.cpp]: Thank you, i'll implement your suggestions ASAP.

**Review by dalexeev — APPROVED** [review]
Looks good to me. :+1:
