### PR TITLE
Fix incomplete shadowing of member properties by parameters

### LINKED ISSUE #67185: GDScript 2.0: parameter name issue
### Godot version

4.0 beta 2

### System information

Windows 11 x64 professional

### Issue description

I've experienced some issues with the scope of class variables and function parameters:

For example a class containing a var file_path and a function (static or non static) has a parameter file_path:

```gdscript
class_name Example
extends RefCounted

var file_name: String

static func loadFromFile(file_name: String = "") -> Example:
    if file_name == "":
        file_name = ... #some random file name generation
        var example := new()
        example.file_name = file_name
        # more code
```

While debugging my code I get errors because the variable / parameter scope is not correct:

### Steps to reproduce

Create code like described and debug it

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by vonagam**
Fixes #67185.

```gdscript
var a: int = 1

func shadow( a: Variant, b: Variant ) -> void:
  print( a ) # a
  print( self.a ) # 1
  a = b
  print( a ) # before: a, after: b
  print( self.a ) # before: b, after: 1

func _ready():
  shadow( 'a', 'b' )
```

Pretty simple change. Includes a small test. Can make the change smaller - without the method, but someone initially forgot to check not only locals but params too and the presence of that method should help (at least a little) to prevent that.

Just encountered the issue myself and was confused because shadowing was kinda working but also not, as it is shown here in the example it was working for reading but for an assignment it was missing the mark.

### CODE REVIEW

File: modules/gdscript/gdscript_compiler.cpp [hunk 1]
```diff
@@ -920,7 +924,7 @@ GDScriptCodeGenerator::Address GDScriptCompiler::_parse_expression(CodeGen &code
 								StringName var_name = identifier->name;
 								if (_is_class_member_property(codegen, var_name)) {
 									assign_class_member_property = var_name;
-								} else if (!codegen.locals.has(var_name) && codegen.script->member_indices.has(var_name)) {
+								} else if (!_is_local_or_parameter(codegen, var_name) && codegen.script->member_indices.has(var_name)) {
```
Comment (kleonc) [inline modules/gdscript/gdscript_compiler.cpp:927]: I see the other similar change (line 1134L/1138R) is in _"Regular assignment"_ case so I suppose that's the one which actually fixes the example you've showcased (CMIIW). What case does the change in here fix?

Comment (vonagam) [reply modules/gdscript/gdscript_compiler.cpp:927]: Hm... as it is visible that this is about an assignment a to subscript so `a.b = 3`, and this part in particular is about deciding the origin of the base - `a`. It makes the same mistake as bellow and sets bunch of stuff like `is_member_property` to true for actually shadowed by parameter hypothetical `a`, but for some reason it still works afterwards as expected, at least it is hard for me to create a clear test to show the difference. Will investigate more.

Comment (vonagam) [reply modules/gdscript/gdscript_compiler.cpp:927]: Added example with broken subscript assignment to the test.

Comment (kleonc) [reply modules/gdscript/gdscript_compiler.cpp:927]: Yeah, I was wondering whether a test for it could be added too. Thanks for doing so!

**Review by kleonc — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by AFE-GmdG** [comment]
Thank you for your work and fix!
