### PR TITLE
Fix accessing UID before first scan

### LINKED ISSUE #100915: [4.4.dev7] The `Default Environment` setting is reset after the "cold" project loading (`res://` | `uid://` issue)
### Tested versions

- reproducible in 4.4.dev7 (maybe 4.4.x)
- not reproducible: 4.3.stable

### System information

Godot v4.4.dev7 - Windows 11 (build 26100) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 32.0.15.6636) - 12th Gen Intel(R) Core(TM) i5-12400 (12 threads)

### Issue description

The default environment setting (`rendering/environment/defaults/default_environment`) is reset after the **"cold"** project loading (deleting the `.godot` folder and loading project for the first time). However, it stays on place if it was saved as `res://...` path, not as `uid://...` value. Seems like `uid` related bug.

### Steps to reproduce

Steps for 4.4.dev7: 
- create new project;
- create an `Environment` asset;
- set it as default in `Project Settings`;
- close the project;
- delete the `.godot` folder;
- open the project.

Not reproduced with 4.3 -> 4.4 migration because its value will still be saved as `res://`, not `uid://`.

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/18270863/test.zip)

### LINKED ISSUE #101677: minimal project doesn't import errorless (main_scene uid)
### Tested versions

reproducible in 4.4-dev7, 4.4-beta1

### System information

Godot v4.4.beta1 - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4070 (NVIDIA; 32.0.15.6636) - AMD Ryzen 9 3950X 16-Core Processor (32 threads)

### Issue description

MRP import has errors related to main_scene being referenced as uid.

4.4-dev7:
```
Godot Engine v4.4.dev7.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
  ERROR: core/io/resource_uid.cpp:155 - Condition "!unique_ids.has(p_id)" is true. Returning: String()
--- Debug adapter server started on port 6006 ---
--- GDScript language server started on port 6005 ---
  ERROR: core/io/resource_uid.cpp:155 - Condition "!unique_ids.has(p_id)" is true. Returning: String()
  ERROR: core/io/resource_uid.cpp:155 - Condition "!unique_ids.has(p_id)" is true. Returning: String()
  ERROR: core/io/resource_uid.cpp:155 - Condition "!unique_ids.has(p_id)" is true. Returning: String()
```

4.4-beta1 (4owdun8sxw04 is root_scene.tscn, which is set as main_scene):
```
Godot Engine v4.4.beta1.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
  ERROR: Unrecognized UID: "uid://4owdun8sxw04".
--- Debug adapter server started on port 6006 ---
--- GDScript language server started on port 6005 ---
  ERROR: Unrecognized UID: "uid://4owdun8sxw04".
  ERROR: Unrecognized UID: "uid://4owdun8sxw04".
  ERROR: Unrecognized UID: "uid://4owdun8sxw04".
```

### Steps to reproduce

import MRP

### Minimal reproduction project (MRP)

[44b1expdebug.zip](https://github.com/user-attachments/files/18454066/44b1expdebug.zip)

### PR DESCRIPTION
**Pull request by Hilderin**
- Fixes #101677
- Fixes #100915

This PR should fix most of the issues where Godot tries to access an UID before the first scan is done and when the UID cache is missing, incomplete or invalid.

The idea is to execute a scan for UIDs on startup if an UID is used before the first scan. This scan is done a maximum of one time and, if executed, replaces the "normal" first scanning which loads the file structure of the project into `first_scan_root_dir`.

One potential problem with large project is that the scanning could take a while and the user has no feedback.

Also, the plugins are, maybe, not loaded when the scan of UIDs is executed. That means that it's possible that some custom loader will be missing, resulting in an impossibility to read some UIDs.

Tested with the MRP from #101677 and #100915.

### CODE REVIEW

**Comment by mihe** [comment]
> One potential problem with large project is that the scanning could take a while and the user has no feedback.

For what it's worth, when testing this PR on a real-world project with thousands of resource files, I'm not seeing any noticeable regression in pure wall time when deleting `uid_cache.bin` and measuring from editor start to when all the various scan dialogs and progress bars are gone.

**Comment by Hilderin** [comment]
I did some tests this morning, and below are the added loading times for the editor when the UID cache is missing, and a UID is required before the first scan (e.g., `run/main_scene` project settings):  

- **3000 files** (without `.import` and `.uid`): **1.5 sec**  
- **60000 files** (without `.import` and `.uid`): **48 sec**  

One way to improve this could be to avoid scanning the entire project when looking up a single UID and instead stop as soon as it is found. However, the challenge and potential drawback of this approach is that if multiple UIDs are needed, multiple rescans may be required.

That's why I suggest scanning everything. Technically, this "scan for UIDs" should not happen often, except in CI/CD environments where the UID cache will always be missing.

**Comment by mihe** [comment]
> * **3000 files** (without `.import` and `.uid`): **1.5 sec**
> * **60000 files** (without `.import` and `.uid`): **48 sec**

Right, yeah, the "real-world project" in question was definitely closer to 3k than 60k. A second here or there wasn't really what I was looking out for. :)

File: core/io/resource_uid.h [hunk 1]
```diff
@@ -63,6 +65,8 @@ class ResourceUID : public Object {
 	static void _bind_methods();
 
 public:
+	static ResourceUIDScanForUIDOnStartup scan_for_uid_on_startup;
```
Comment (KoBeWi) [inline core/io/resource_uid.h:68]:
```suggestion
	inline static ResourceUIDScanForUIDOnStartup scan_for_uid_on_startup = nullptr;
```

Comment (Hilderin) [reply core/io/resource_uid.h]: Done!

Comment (KoBeWi) [reply core/io/resource_uid.h]: Same for the variables in `editor_file_system`.

**Comment by Hilderin** [comment]
Thanks for the review and testing.

Fixing the boot splash screen will be a bit trickier. The problem is that the logo is loaded before the resources format importers are loaded. If I move `ResourceUID::scan_for_uid_on_startup = EditorFileSystem::scan_for_uid;` just before `setup_boot_logo`, the `ResourceFormatImporter::get_singleton()->get_recognized_extensions` returns no extensions. That causes to not be able to get the UID for extensions like `.tscn`.

Since the issue is not supposed to happen that often, I did a little check before calling`ResourceUID::ensure_path` on the boot logo path to prevent printing errors.

The alternative could be to display the boot logo later in the start sequence or put the loading of the `ResourceFormatImporter` sooner, but I fear that could lead to serious side effects and this close to a release candidate, I think it's a bad idea for this small issue.

**Comment by KoBeWi** [comment]
Yeah, removing errors is enough.

File: main/main.cpp [hunk 2]
```diff
@@ -3496,9 +3507,16 @@ void Main::setup_boot_logo() {
...
-		const String boot_logo_path = ResourceUID::ensure_path(GLOBAL_DEF_BASIC(PropertyInfo(Variant::STRING, "application/boot_splash/image", PROPERTY_HINT_FILE, "*.png"), String())).strip_edges();
 		const bool boot_logo_scale = GLOBAL_DEF_BASIC("application/boot_splash/fullsize", true);
 		const bool boot_logo_filter = GLOBAL_DEF_BASIC("application/boot_splash/use_filter", true);
+		String boot_logo_path = GLOBAL_DEF_BASIC(PropertyInfo(Variant::STRING, "application/boot_splash/image", PROPERTY_HINT_FILE, "*.png"), String());
+
+		// If the UID cache is missing or invalid, it could be 'normal' for the UID to not exist in memory.
+		// It's too soon to scan the project files since the ResourceFormatImporter is not loaded yet,
+		// so to prevent printing errors, we will just skip the custom boot logo this time.
+		if (boot_logo_path.begins_with("uid://") && ResourceUID::get_singleton()->has_id(ResourceUID::get_singleton()->text_to_id(boot_logo_path))) {
+			boot_logo_path = ResourceUID::ensure_path(boot_logo_path).strip_edges();
```
Comment (KoBeWi) [inline main/main.cpp:3518]:
```suggestion
		if (boot_logo_path.begins_with("uid://")) {
			const ResourceUID::ID logo_id = ResourceUID::get_singleton()->text_to_id(boot_logo_path);
			if (ResourceUID::get_singleton()->has_id(id)) {
				boot_logo_path = ResourceUID::get_singleton()->get_id_path(boot_logo_path).strip_edges();
			}
```

**Comment by KoBeWi** [comment]
> I did a little check before callingResourceUID::ensure_path on the boot logo path to prevent printing errors.

Did you test whether it fixes the errors? 🙃
image

File: main/main.cpp (hunk 2 above)
Comment (Hilderin) [reply main/main.cpp:3518]: Done!

**Comment by Hilderin** [comment]
Really sorry about that, I went to fast! Tested correctly this time!

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
