### PR TITLE
Correct hash behavior for floating point numbers

### LINKED ISSUE #6947: Godot crashes when a certain gdscript file is in the project folder
Issue experienced on Windows 7 and Windows 10 - Godot version 2.1

Description: When Godot has a certain gdscript somewhere within "res://", it crashes when this file is either previewed in the file browser, opened, or saved within Godot. This problematic .gd file is attached to this issue. A way to prevent the crash is to mess with lines 30 and 31:

```
var x = 200 * cos(2 * PI / (0))
var y = 200 * sin(2 * PI / (0))
```

If either of these lines are deleted, Godot won't crash. If either of these lines are changed enough, Godot won't crash. It makes no sense to me why the editor seems to crash only in the case that these lines are present in a file.

Steps to reproduce:
1. Download the attached file
2. Change the file extension from .txt to .gd
3. Create a new Godot project
4. Put the downloaded .gd file in the Godot project's root directory
5. Open the project
6. Open the .gd file within Godot
7. Try to save the .gd file a number of times

Godot should crash at some point during this process.

[Game.txt](https://github.com/godotengine/godot/files/557495/Game.txt)

### LINKED ISSUE #7354: Vector2 division breaks the editor
**Operating system or device - Godot version:**
2.2.1

**Issue description** (what happened, and what was expected):
Typing out Vector2 division immediately crashes the editor, and opening the project afterwards causes the editor to immediately crash again until you remove the line using some other method.

**Steps to reproduce:**
I wrote this line in the _ready call of an otherwise empty script in an empty scene.

Vector2(5, 0)/Vector2(1, 0)

### PR DESCRIPTION
**Pull request by hpvb**
Correct hash behavior for floating point numbers

This fixes HashMap where a key or part of a key is a floating point
number. To fix this the following has been done:

* HashMap now takes an extra template argument Comparator. This class
gets used to compare keys. The default Comperator now works correctly
for common types and floating point numbets.

* Variant implements ::hash_compare() now. This function implements
nan-safe comparison for all types with components that contain floating
point numbers.

* Variant now has a VariantComparator which uses Variant::hash_compare()
safely compare floating point components of variant's types.

* The hash functions for floating point numbers will now normalize NaN 
values so that all floating point numbers that are NaN hash to the same
value.

C++ module writers that want to use HashMap internally in their modules
can now also safeguard against this crash by defining their on
Comperator class that safely compares their types.

GDScript users, or writers of modules that don't use HashMap internally
in their modules don't need to do anything.

This fixes #7354 and fixes #6947.

### CODE REVIEW

File: core/hash_map.h [hunk 1]
```diff
@@ -29,12 +29,64 @@
...
+#include <cmath>
+
 #include "hashfuncs.h"
 #include "error_macros.h"
 #include "ustring.h"
 #include "os/memory.h"
 #include "list.h"
 
+// Don't pollute global namespace with generic terms like 'compare' or 'enable_if'
+namespace _hashmap_priv {
```
Comment (bojidar-bg) [inline core/hash_map.h]: Are you trying to get yourself shot?

File: core/variant.cpp [hunk 2]
```diff
@@ -2921,6 +2917,186 @@ uint32_t Variant::hash() const {
 
 }
 
+#define hash_compare_one(p_lhs, p_rhs)\
```
Comment (bojidar-bg) [inline core/variant.cpp]: `one` -> `scalar` or something of that sort might be simpler

File: core/hash_map.h (hunk 1 above)
Comment (hpvb) [inline core/hash_map.h]: If it is preferred I can call it _hash_compare or something. I just figured this was easier to read especially since we really don't expect other callers for this. I was under the impression that @reduz didn't want namespaces to separate parts of the engine, but that he was fine with using it for this type of hiding. Maybe I misunderstood.

File: core/variant.cpp (hunk 2 above)
Comment (hpvb) [inline core/variant.cpp]: Agreed, I'll change this.

**Comment by hpvb** [comment]
I'm actually removing all the template magic. It appears to be poorly  in general  and I introduced a GCCism. It builds and runs fine on clang also but perhaps not msvc? Anyway I'm working on a new revision. It will just hardcode the behavior only for Variant.

**Comment by tagcup** [comment]
> Because of the template trickery @tagcup's concern about the burden on module writers to implement hash_equals() should also be addressed.

Will this work on types that use floats but don't implement a special comparison function (name doesn't matter, be it operator== or hash_compare) that behaves in the particular way to suit Variant's needs?

**Comment by hpvb** [comment]
Due to the way godot's hash system works it will always crash if you try to place an object in it for which x != x and you then try to retrieve it later. 

Custom types written in c++ will have to either implement hash_equals() or make sure their operator==() deals with it if they have this property.

**Comment by hpvb** [comment]
@tagcup You're right, there needs to be a little more done for this to be really OK. We need to know in an unambiguous way whether or not an object is the same. And while we can't do a bit-by-bit comparison for Variant I think we *can* get away with it for 'normal' C++ objects. 

Looks like we're going to end up with a solution that does all of the things

**Comment by tagcup** [comment]
> Due to the way godot's hash system works

Then the hashing is wrong. You can't expect to fix Variant's issues by fixing *everybody else* to "fix" their code and implement this particular hack.

Furthermore, this is pretty much specific to GDScript. You can write games in C++ or any other upcoming languages.

> Custom types written in c++ will have to either implement hash_equals() or make sure their operator==() deals with it if they have this property.

Not just custom types. This applies to everything that GDScript has access to, including dozens of other classes that ships with Godot and missing in your PR.

Also, to make this really work just in the core, you need to go through this list:

http://docs.godotengine.org/en/stable/classes/_classes.html

And good luck explaining all Godot users that a special comparison function that behaves in a particular way is required in their class is to work without crashing the editor.

**Comment by akien-mga** [comment]
> And good luck explaining all Godot users that a special comparison function that implements a non-standard floating point comparison is required in their class to work without crashing the editor.

If we just can continue this interesting discussion without being sarcastic or trying to prove by all means that the other is wrong, that would be nice. We're looking to work together towards a common solution, so let's keep it constructive (so far it's fine, but yesterday it wasn't, so I prefer to drop a small encouragement for going in a positive discussion ground beforehand ;)).

**Comment by tagcup** [comment]
@akien-mga That wasn't meant to be sarcastic actually. I was literally thinking: "let's say this gets merged, how do we explain this to others?"

I understand & totally agree with what you're saying though. Sorry if it sounded harsh.

**Comment by akien-mga** [comment]
> I understand & totally agree with what you're saying though. Sorry if it sounded harsh.

Yeah it didn't particularly sound harsh, but I know that such discussions can quickly become heated when all participants are passionate about the topic, so I preferred to make sure everybody makes an effort to try to think positively about proposed solutions (while still being able to say what is not a good solution of course). So it wasn't particularly for you, but for all of us (even if I quoted your might-be-interpreted-sarcastically last line hehe).

**Comment by hpvb** [comment]
@tagcup I had another look as I remember from our last discussion being quite sure there was nothing else needed. I looked at my notes again and to be extra sure spend another 15 minutes single-stepping through the relevant codepaths.

Have look look at variant_op.cpp:281 
```c++
if (p_b.type==OBJECT)
	_RETURN( (p_a._get_obj().obj == p_b._get_obj().obj) );
if (p_b.type==NIL)
	_RETURN( !p_a._get_obj().obj );
```
This is what happens when OP_EQ is called on a Variant of type object (which the current code continues to do, and is the code used by the hash comparison function also)

At this point p_a._get_obj().obj is of type Object*. GDScript (and hash tables) are only ever able to compare the pointer values of Objects. Different objects in GDscript are always different. An illustration:
```gdscript
func _ready():
    var x = Listener.new()
    var y = Listener.new()
    print (x == y)
```
will print 'False' to the terminal.

This PR does solve the issue.

I got a little sidetracked by @tagcup's comments on the previous PR as I thought they were worried about *users of HashMap in C++*. That cannot be helped. If you want to use HashMap from C++ with custom types you will still have to ensure that x ==x. But for GDScript and module writers it does not matter at all.

**Comment by hpvb** [comment]
Sorry, my previous explanation actually left out an important detail. One may reasonably ask 'but TMM, if objects are always unequal why don't THEY crash the engine?'. 

The answer to that is that the crash occurs only when an object hashes the same but is still not equal to the object. (object meaning 'a thing in the hashtable') for Variants of type Object this doesn't matter as the hash value is calculated as follows:

```c++
case OBJECT: {
	return hash_djb2_one_64(make_uint64_t(_get_obj().obj));
} break;
```
As in, here also only the pointer value is taken into account.

**Comment by tagcup** [comment]
Ah, OK. Thanks for the explanation.

The issue partially remains, because you it is still possible to introduce new classes to GDScript that are not objects. So then let me confirm this. Is it true that doing this involves adding custom hooks to Variant? Because that's different from [writing a module](http://docs.godotengine.org/en/stable/reference/custom_modules_in_c++.html), and you document it as some internal mechanism only required when injecting a new (non-object-based) type to GDScript.

**Comment by hpvb** [comment]
@tagcup this is correct. The only way to add a type to GDScript that would need this special treatment is by adding it as a type to Variant. This cannot be done without actually editing variant.h, variant.cpp, and variant_ops.cpp. I think that if someone does this they will encounter Variant::hash_equals() and try to find out why it's there :)

**Comment by hpvb** [comment]
For the maintainers. @reduz just suggested I add an equality check function as a parameter to the hashmap when instantiating. This makes everything a little cleaner, and alleviates some of the mistakes other C++ module writers may have. I'll implement this in this PR also, please don't merge yet until another comment saying it's ready.

If you prefer I can close this PR and reopen it once this is implement @akien-mga

**Comment by tagcup** [comment]
Again sorry for being illiterate about the internals of GDScript, but I realized I have one more follow-up question along the same lines.

Let's say I make a class in Godot (using the class keyword). Does it actually inherit from Reference or Object?

BTW, it'd be really nice if you can add some comments in the code about this workaround, maybe even link to the relevant github issue, because it's not obvious and can be perplexing (speaking from experience :)).

**Comment by akien-mga** [comment]
> If you prefer I can close this PR and reopen it once this is implement @akien-mga

It's fine by me if you want to simply rebase this PR :)

**Comment by tagcup** [comment]
Also please don't forget about other basis GDScript-accesible types: Basis, Transform, Transform2D, Plane, etc.

File: core/hash_map.h [hunk 3]
```diff
@@ -80,6 +80,20 @@ class HashMapHahserDefault {
  *
 */
 
+template<typename T>
+bool _nan_compare(const T& lhs, const T& rhs) {
```
Comment (bojidar-bg) [inline core/hash_map.h]: I think you should keep those in the .h with _FORCE_INLINE_ if possible

**Comment by bojidar-bg** [comment]
@tagcup I think no additional clarification is needed, to me this code is relatively simple (compare with other parts of the core....)

About the `class` question, you can use extends just fine there, exactly like in the main body of the script (or even inline, if you want, with `class A extends B:`)

**Comment by tagcup** [comment]
@bojidar-bg No, I think the workaround regarding IEEE-754 floats needs to be clarified, because 1) this is a very specific kind of hack that is bound to the internal quirks of how dictionary works in GDScript 2) and new types added in the future are expected to implement this hack too.

I mean I'm not talking about a detailed doc, just a a few lines saying that this non-standard floating point comparison is required for types containing floats to make hashing work, and a link to this issue for details for example.

**Comment by tagcup** [comment]
@bojidar-bg 

Yes, but what if it doesn't extend anything? Is there a hidden, default base class (maybe Reference)?
What I was essentially trying to ask is this: can we generate a class from GDScript that won't work correctly with the current hashing unless the user also provides a special comparison function.

**Comment by hpvb** [comment]
@tagcup there is no codepath where you can create a class from gdscript where you can cause the interpreter to call operator==() from HashMap's compare function. This fix really is comprehensive for this isue.

**Comment by hpvb** [comment]
@bojidar-bg @akien-mga  I think this is now done. If you're OK with the code in general feel free to merge it.

File: core/hash_map.h [hunk 4]
```diff
@@ -74,13 +87,14 @@ class HashMapHahserDefault {
  * @param TKey  Key, search is based on it, needs to be hasheable. It is unique in this container.
  * @param TData Data, data associated with the key
  * @param Hasher Hasher object, needs to provide a valid static hash function for TKey
+ * @param Comarator Comoratar object, needs to be able to safely compare two TKey values
```
Comment (akien-mga) [inline core/hash_map.h]: Comarator Comoratar... Always there :P

File: core/hash_map.h [hunk 5]
```diff
@@ -51,19 +48,35 @@ class HashMapHahserDefault {
...
 };
 
+template <typename T>
+struct HashMapComparatorDefault {
+	static bool compare(const T& lhs, const T& rhs) {
+		return lhs == rhs;
+	}
+
+	bool compare(const float& lhs, const float& rhs) {
+			return (lhs == rhs) || (std::isnan(lhs) && std::isnan(rhs));
```
Comment (akien-mga) [inline core/hash_map.h]: One excess level of indent, but clang-format would fix it anyway so no need to rebase just for that.

File: core/hashfuncs.h [hunk 6]
```diff
@@ -75,9 +76,26 @@ static inline uint32_t hash_djb2_one_float(float p_in,uint32_t p_prev=5381) {
 		uint32_t i;
 	} u;
 
-	// handle -0 case
```
Comment (akien-mga) [inline core/hashfuncs.h]: That comment was actually useful.

File: core/hashfuncs.h [hunk 7]
```diff
@@ -75,9 +76,26 @@ static inline uint32_t hash_djb2_one_float(float p_in,uint32_t p_prev=5381) {
...
+}
+
+// Overload for real_t size changes
+static inline uint32_t hash_djb2_one_float(double p_in,uint32_t p_prev=5381) {
+	union {
+		double d;
+		uint64_t i;
+	} u;
+
+	if (p_in==0.0f) u.d=0.0;
```
Comment (akien-mga) [inline core/hashfuncs.h]: Would be good to use the same style as in the previous method (so not single line ifs but with a proper indentation).

**Review by akien-mga — APPROVED** [review]
Looks good to me code wise, but let's wait for a review by @reduz, @tagcup and maybe @bojidar-bg before merging.

**Comment by hpvb** [comment]
ok @akien-mga I think I've addressed your concerns now

File: core/hashfuncs.h (hunk 6 above)
Comment (bojidar-bg) [inline core/hashfuncs.h]: The comment replacing it is good too though.

File: core/hashfuncs.h [hunk 8]
```diff
@@ -75,9 +76,31 @@ static inline uint32_t hash_djb2_one_float(float p_in,uint32_t p_prev=5381) {
...
 	} u;
 
-	// handle -0 case
-	if (p_in==0.0f) u.f=0.0f;
-	else u.f=p_in;
+	// Normalize +/- 0.0 and Nan values so they hash the same.
+	if (p_in==0.0f)
+		u.f=0.0;
+	else if (std::isnan(p_in))
+		u.f=std::numeric_limits<float>::quiet_NaN();
```
Comment (bojidar-bg) [inline core/hashfuncs.h]: Can we be sure that this would actually work on consoles and other weirdnesses? (also, I'm not sure we are using std:: anywhere else, so, would be cool if we can get it out somehow)

File: core/hashfuncs.h [hunk 9]
```diff
@@ -75,9 +76,31 @@ static inline uint32_t hash_djb2_one_float(float p_in,uint32_t p_prev=5381) {
...
+
+	// Normalize +/- 0.0 and Nan values so they hash the same.
+	if (p_in==0.0f)
+		u.d=0.0;
+	else if (std::isnan(p_in))
+		u.d=std::numeric_limits<double>::quiet_NaN();
+	else
+		u.d=p_in;
 
 	return ((p_prev<<5)+p_prev)+u.i;
```
Comment (bojidar-bg) [inline core/hashfuncs.h]: Just a note that you are discarding lots of bits here (32 to be exact)

**Review by bojidar-bg — APPROVED** [review]
Looks cool

File: core/hashfuncs.h (hunk 6 above)
Comment (akien-mga) [inline core/hashfuncs.h]: It wasn't there when I commented about it ;) It was then added in a rebase.

File: core/hashfuncs.h (hunk 8 above)
Comment (hpvb) [inline core/hashfuncs.h]: It's part of the c++98 STL. I'd be extremely surprised if anything that Godot can actually build for didn't have it.

File: core/hashfuncs.h (hunk 9 above)
Comment (hpvb) [inline core/hashfuncs.h]: You are correct, I'll move the 64 bit hasher into hashfucs.h and reuse it for this case.

File: core/hashfuncs.h (hunk 6 above)
Comment (hpvb) [inline core/hashfuncs.h]: Yeah I replaced the comment in response to this message. It looks like github didn't pick up that this line was now changed.

**Comment by hpvb** [comment]
@bojidar-bg I think I've addressed your suggestions also.

File: core/hashfuncs.h (hunk 8 above)
Comment (bojidar-bg) [inline core/hashfuncs.h]: Ok...

Comment (tagcup) [inline core/hashfuncs.h]: AFAIK, Godot doesn't use STL. Can you instead add wrap the libc function in math_funcs.h and use it? NAN in math.h is qNaN.

File: core/hashfuncs.h [hunk 10]
```diff
@@ -69,19 +69,52 @@ static inline uint32_t hash_djb2_one_32(uint32_t p_in,uint32_t p_prev=5381) {
...
 	} u;
 
-	// handle -0 case
-	if (p_in==0.0f) u.f=0.0f;
-	else u.f=p_in;
+	// Normalize +/- 0.0 and NaN values so they hash the same.
+	if (p_in==0.0f)
+		u.f=0.0;
+	else if (isnan(p_in))
+		u.f=NAN;
```
Comment (tagcup) [inline core/hashfuncs.h]: The convention so far has been to put these stuff (like isnan and NAN) under math_defs.h and math_funcs.h rather than using them from math.h. There is actually a PR for that #7787, can you check it?

File: core/hash_map.h [hunk 11]
```diff
@@ -74,13 +78,14 @@ class HashMapHahserDefault {
  * @param TKey  Key, search is based on it, needs to be hasheable. It is unique in this container.
  * @param TData Data, data associated with the key
  * @param Hasher Hasher object, needs to provide a valid static hash function for TKey
+ * @param Comparator comparator object, needs to be able to safely compare two TKey values
```
Comment (tagcup) [inline core/hash_map.h]: I don't think just saying "safely" is informative or helpful. It would be helpful for future contributors if you give a short explanation about what exactly is expected from a comparator (which is nan == nan behavior for floats only) and why this *workaround* (which violates IEEE-754 standard, in a *particular way* to fit the need of the particular way dictionary hash behaves) is needed.

Comment (hpvb) [inline core/hash_map.h]: It's not a workaround. Other hashmaps do this, or do a bitwise comparison of members to check for collisions. We can't do a bitwise comparison due to the way variant is implemented, thus we do a different equality check. The alternative would be to have a comparison function that internally inside of variant does a bitwise compare of the parts of variant for each type that makes sense. A separate comparator would still be needed and that comment would still be the same. 

For instance a class that has nested pointers to other class instances that it would want to compare the dereferenced value of would equally need to take care of this.

It is not possible for any hashmap to not treat nan special, or do a bitwise comparison (making sure that all different types of NaNs hash to different values also). Try inserting a NaN into a an std::map as a key for instance. (it will crash for the same reason as godot's hashmap does once you insert another item)

I can expand the comment to say that 'safely' means that x == x is guaranteed if you think that's more useful. I'm not going to add an 'intro into basic float precautions' into a comment about a hashmap.

File: core/hashfuncs.h (hunk 10 above)
Comment (hpvb) [inline core/hashfuncs.h]: I've move to using Math::is_nan() instead of isnan from math.h but the definition of NAN is only in that unmeged PR. I'm going to continue to rely on the NAN value from <math.h>. If it is merged I'll create another PR.

Comment (tagcup) [inline core/hashfuncs.h]: is_nan is available in math_funcs.h BTW.

**Comment by hpvb** [comment]
@tagcup I believe my last set of changes address your concerns.

File: core/hash_map.h (hunk 11 above)
Comment (tagcup) [inline core/hash_map.h]: Whatever you call, this is something non-standard and depends on the internal decisions used for hashmap. I can show one at least one very different implementation [in Go](https://golang.org/src/runtime/alg.go#L101). And see how they document the behavior that deviates from IEEE-754. Concise, to the point, and brief. See how they don't brush it off by just saying "safe".

I really don't understand your resistance for not documenting this. You could've written a single line about what is expected and why rather than writing paragraphs arguing about it.

**Comment by tagcup** [comment]
@hpvb Can you please, please, please just write a sentence that conveys actual information about what exactly (nan==nan for floats) is expected from a comparator? You're expecting a *particular* non-standard behavior, so please document what it is. "Safe" doesn't convey any useful information or help any future contributor in a meaningful way.

**Comment by tagcup** [comment]
If you mention floats and NaN != NaN issue which breaks x == x, future readers will be able to understand what's really going on.

File: core/hash_map.h (hunk 11 above)
Comment (hpvb) [inline core/hash_map.h]: The comment you're referring to is for func f32hash(p unsafe.Pointer, h uintptr) uintptr; in Go. This is equivalent to my comment  '// Normalize +/- 0.0 and NaN values so they hash the same.' in hashfuncs.h.

Since in Go there is no way to use a value as a key that does not have an '==' operator there is never an issue. But the comment equivalent you're asking for here exists in my PR.

Comment (tagcup) [inline core/hash_map.h]: For example, something like this:
"A Comparator is only required for data structures containing floats, for which comparison requires special treatment for NaN values to ensure that x == x is satisfied."

**Comment by hpvb** [comment]
I have added a reminder to a potential user that nan != nan in C++. I hope this addresses your concern.

**Comment by tagcup** [comment]
Thank you. That has nothing to do with C or C++ though, that's just how the hardware works.
Could you please also add Math_NAN in math_defs.h and use that, and not include math.h directly?

**Comment by hpvb** [comment]
I've removed the 'in C' comment. I've added the value from that PR as well. Someone needs to ensure that when #7787 gets merged we don't get two separate definitions.

File: core/hash_map.h (hunk 11 above)
Comment (tagcup) [inline core/hash_map.h]: > Since in Go there is no way to use a value as a key that does not have an '==' operator there is never an issue.

You chose to apply your behavior to floats uniformly by introducing a Comparator that behaves consistently, Go is clever about types and can figure out where floats on its own without additional runtime cost (it's already the) and just call the relevant internal function for that.

This whole thing is about how the hash function treats floats *internally* versus how the *hardware* comparison works. It's about the nature of the behavior, not which language feature you use to override the hardware comparison.

**Comment by tagcup** [comment]
Thank you! LGTM otherwise.

File: core/hash_map.h (hunk 11 above)
Comment (hpvb) [inline core/hash_map.h]: Go doesn't cleverly work around it, it doesn't IMPLEMENT the feature we're using. In go the variant equivalent could just not be used as a key in a hash at all.

You ignored my actual point though. The comment equivalent of the go comment was already there.

**Comment by tagcup** [comment]
About #7787, it affects only a single line of the PR, so regardless of the merge order, should be an easy fix.

File: core/hash_map.h (hunk 11 above)
Comment (tagcup) [inline core/hash_map.h]: And no, the comment I was referring is this

```
   101	// NOTE: Because NaN != NaN, a map can contain any
   102	// number of (mostly useless) entries keyed with NaNs.
   103	// To avoid long hash chains, we assign a random number
   104	// as the hash value for a NaN.
```

(which is also the link I gave points to)

Comment (hpvb) [inline core/hash_map.h]: Yes, exactly. Go randomizes the key, Godot normalizes nan values. It doesn't say anywhere 'oh, btw, if you use a (compound) key with a nan value we produce garbage and you won't be able to retrieve by key any longer. Which is the type of comment you apparently want.

I'm saying, I already had what you were asking for.

Comment (tagcup) [inline core/hash_map.h]: > Go doesn't cleverly work around it, it doesn't IMPLEMENT the feature we're using. In go the variant equivalent could just not be used as a key in a hash at all.

That "feature" you're talking about is a workaround, it is something you invented. There is no such standard. Go just uses has a different workaround treating NaN float keys. You *can* add items with NaN values multiple times; instead of hashing them to the same bin like you do, they chose to put items with NaN keys in random bins.

Comment (tagcup) [inline core/hash_map.h]: > It doesn't say anywhere 'oh, btw, if you use a (compound) key with a nan value we produce garbage and you won't be able to retrieve by key any longer. Which is the type of comment you apparently want.

They don't say anything like that because their work around just works whereas your works around requires people to implement something called Comparator in a particular way you came up with.

Comment (tagcup) [inline core/hash_map.h]: A new data structure with floats just works with Go. A new data structure with a float in GDScript on the other hand, if will just crash Godot unless they repeat the behavior you expect using a custom Comparator.

So it seems only natural to me that you need to document this pitfall.

Comment (tagcup) [inline core/hash_map.h]: And mind you, Go devs could have chosen to to put all NaNs into the same bin as well. It only requires them to make changes in the hashing function I linked to, and still won't require users to implement custom methods like Comparator does.

The nature of the workaround  is perpendicular whether you expect users to actively implement a certain function with certain behavior to make it work.

Comment (tagcup) [inline core/hash_map.h]: > It doesn't say anywhere 'oh, btw, if you use a (compound) key with a nan value we produce garbage and you won't be able to retrieve by key any longer. Which is the type of comment you apparently want.

No, I mean something that conveys the actual issue, and when it is needed. If you scroll up, you'll see I already gave you an example:

> A Comparator is only required for data structures containing floats, for which comparison requires special treatment for NaN values to ensure that x == x is satisfied.

**Comment by bojidar-bg** [comment]
@tagcup The trick is not easy vs not easy, the question is who :wink:

**Comment by tagcup** [comment]
@bojidar-bg Yes but what I'm trying to say is, since it's going to a trivial fix either way, does it really matter?

**Comment by reduz** [comment]
We can have specializations for types with floats, its not terrible

**Comment by tagcup** [comment]
> We can have specializations for types with floats, its not terrible

Since it turned out that this only impacts data types added directly into GDScript and not stuff derived from Object (including all user modules), yeah, totally.

I mean, to me, it's not ideal to have workaround which needs to be implemented for each GDScript data structure with floats separately over and over again in a particular manner consistently, but luckily, there're only a handful such cases and users aren't expected to that anyway, and nobody came up with a better workaround so far.

**Comment by hpvb** [comment]
@tagcup You keep calling this a workaround. There are only a handful of options:
* x[nan] == x[nan] : Implement a nan-safe comparison for Variant, every non-GDScript type that wants to use HashMap has to implement one too.
* x[nan] != x[nan]: Implement a nan-safe hasher for Variant, every non-GDScript type that wants to use HashMap has to implement one too.
* x[nan] != x[nan]: Hardcode a nan-safe hasher in HashMap. No non-GDScript type can use HashMap <-- This is Go's solution.

Of these different solutions I picked the one with the least surprising results for users of GDScript. A HashMap index is NOT a math operation, a hashmap index is a symbolic reference to another thing, adhering to float semantics for a symbol makes no sense to me.

You will also notice that every implementation requires the same level of knowledge from non-GDScript types.

**Comment by tagcup** [comment]
> You keep calling this a workaround.

Because that's what it is.

As I already explained, you are conflating two things. The nature of how NaN keys are handled, and how this is applied to floats.

Go has support for maps at language level. For this reason, they can implement and change this behavior [with a single function](https://golang.org/src/runtime/alg.go#L101). It doesn't matter which behavior it is, and frankly I don't care which you chose to implement, it's non-standard either way. If they wanted to hash all NaNs to a single bin, then they can also do that by changing a single function in the runtime, and it will just work without any active efforts: it won't require users to implement special functions with special behaviors (I'm referring to Comparator).

C++ doesn't readily give you a way to define *one function* which will be applied to all floats in all incoming data structures. Workaround, ugly-standard-breaking-floating-point-hack or whatever you wanna call it, regardless of the way you chose to break IEEE-754 for your hash function, my problem is this:

*You're not just implementing a single non-standard function (which I think is fine, everybody else is also doing that), you're asking that everyone has to reimplement that non-standard thing exactly over and over again whenever they add a new class to GDScript.*

I don't how how I can make this more clear.

**Comment by hpvb** [comment]
Go doesn't support nested data structures as hash keys, it has no way to override the equals operator. If they did they'd have to pick either the first or second option. There is no alternative. I don't understand why you have any objection at all to something that simply is unavoidable.

**Comment by tagcup** [comment]
> Go doesn't support nested data structures as hash keys, it has no way to override the equals operator. If they did they'd have to pick either the first or second option. There is no alternative. I don't understand why you have any objection at all to something that simply is unavoidable.

Despite the fact that this is tangent to the point I just made, I'll bite.

> Go doesn't support nested data structures as hash keys, it has no way to override the equals operator.

[It does support nested data structures as hash keys](https://play.golang.org/p/nOHVhyBET2).

And yes, there is not operator overlading, and yes, and users can't change the runtime's hashing behavior. And they don't want to allow that either. I'm sure they don't want to end up with awkward things like Comparator either.

> There is no alternative. I don't understand why you have any objection at all to something that simply is unavoidable.

So you're actually saying you have considered all the possible scenarios men and gods can conceive, and you're absolutely sure that it's impossible to come up with a hash map implementation for GDScript that doesn't require everyone, past and future, to implement your particular hack over and over again consistently. Even though no prominent language sorts to this kind repetitive workarounds. Wow. OK. So be it.

You know, this isn't productive. Let's stop this. @reduz is fine with your workaround or whatever keyword you wanna use to pitch it. I already said LGTM.

**Comment by reduz** [comment]
You guys seem to get along great, did't expect such a strong friendship
would develop :P
I am honestly not someone so knowledgeable on theoretical backgrounds, so
for the most part i'm mostly inclined towards solutions that just work.

It seems to happen that sometimes I go against preconceptions or standards
without realizing it, so It's vital that you guys can make a point for when
we are crossing the line in this regard. Yet, I will insist that usability
always takes the priority.

I think the hash map solution, adding a comparison operator works well
enough. C++ provides automatic template specialization in case one wants to
use it from C++ for types such as Vector2, Vector3, etc. For GDScript this
is a special case, as hashing and comparing happens in Variant.  The
proposed solution is good enough for me, and definitely better than what
was done before, can't really think of a better one.

**Comment by hpvb** [comment]
> It does support nested data structures as hash keys.

Sorry, I was imprecise. This only works as long as all types have a strong equality guarantee. What I meant by 'nested' (which was the wrong term to use). You can't have a type with say, a pointer in it to another type as a hash key. 

When you do that it is no longer possible reconstruct the key value. So you can be in a situation where:
```go
n1.a. = 1
n1.b.b = 2
n2.a = 1
n2.b.b = 2
map[n1] != man[n2] 
```
if any of the fields are pointers, or if any field is a map itself as maps are not comparable. The only way to compare those is using reflect.DeepEqual(), but there is no way to tell a Map to do this. So the issue is sidestepped by simple not supporting these types as hashkeys.

**Comment by tagcup** [comment]
Hashing works fine with everything in Go. If you have a reference (pointer, slice, map), it will just compare the pointers, which is the expected behavior per language standard from day 1. It may not work the way *you* expect, and yes, it is confusing for some people at first, but that's something else.

By this standards, you can as well say "hashing doesn't work with floats in Go because I expect them to has all NaNs into same bin, and it behaves differently".

It's just a design decision to avoid runtime burden.

**Comment by akien-mga** [comment]
Alright, we're running in circles here.

@tagcup If you can make a Godot module that exposes your concerns about this PR (i.e. implement a new type that should use the same kind of hashing and show that all hell breaks loose) that would be very helpful so that we can bring the technical discussion further. But now just discussion whether this solution here is better or worse than Go's, it's bringing us nowhere. @hpvb has tried several times to explain why Variant hashing is different from Go's, but if that's not enough, I think we really need a PoC that showcases what is the real issue that you are concerned with. Otherwise it's starting to sound like bikeshedding.

**Comment by tagcup** [comment]
@akien-mga If you missed it, I've already said that LGTM and

> there're only a handful such cases and users aren't expected to that anyway, and nobody came up with a better workaround so far.

Beyond that, I'm just replying to his nitpicking about whether his PR is a monument of perfection or a just a workaround with certain burdens to other people and off-topic (and wrong) comments about how maps work in Go, so it sounds it's unfair you're telling *me* this.

**Comment by akien-mga** [comment]
Well I feel there's nitpicking on both sides about a topic which might not really be worth so much discussion, i.e. "is it a workaround or not?". It's code that works, it doesn't implement a standard but the consensus we agreed upon, so I guess it can be seen as both a workaround *and* the right solution for Godot.

That said, I'm thankful for both you and @hpvb spending so much time to try to get to the bottom of this and ensure we have the best (as in "best fitting to our needs", not the best technical solution to this generic issue ;)) solution implemented in Godot :)

**Comment by hpvb** [comment]
Thanks @akien-mga and thanks for the review and discussion @tagcup. On to the next bug! :)

**Comment by tagcup** [comment]
At the end of the day, I'm also thankful to @akien-mga, @reduz and @bojidar-bg for keeping the discussion sane @hpvb for fixing 2 serious issues. And I do apologize for all the noise.

> On to the next bug! :)

For some reason, I'm feeling scared :P
