### PR TITLE
Fix hang when importing blender files in headless mode

### LINKED ISSUE #100122: CLI import hangs in docker environment with blend file
### Tested versions

- Reproducible in: v4.3-stable, 4.4-dev6

### System information

Linux 6.11.10-2-MANJARO, 64-bit, Docker version 27.3.1, build ce1223035a

### Issue description

When using a Docker image in a CI/CD setup to build a Godot game, the command:
```shell
godot --headless --import --verbose project.godot
```
unexpectedly hangs if a .blend file is present, regardless of whether it is utilized in the project. The import completes successfully if the .blend file is removed.

**What have I tried?**
- Installed Blender within the Docker image, but the issue persists.
- Defined a .gdignore file and moved all .blend files into it, yet the problem remains.

<details> <summary>View Detailed Docker Logs</summary>

```plaintext
#10 [6/6] RUN /opt/godot --import --headless --verbose /app/test/project.godot
#10 0.244 Godot Engine v4.3.stable.official.77dcf97d8 - https://godotengine.org
#10 0.245 TextServer: Added interface "Dummy"
#10 0.252 TextServer: Added interface "ICU / HarfBuzz / Graphite (Built-in)"
#10 0.257 JoypadLinux: udev enabled and loaded successfully.
#10 0.257 Using "default" pen tablet driver...
#10 0.258 
#10 0.262 TextServer: Primary interface set to: "ICU / HarfBuzz / Graphite (Built-in)".
#10 0.317 CORE API HASH: 966092234
#10 0.318 EDITOR API HASH: 444927587
#10 0.320 EditorTheme: Generating new theme for the config '66886095'.
#10 0.320 EditorTheme: Generating new icons.
#10 0.354 EditorTheme: Generating new fonts.
#10 0.358 EditorTheme: Generating new styles.
#10 0.991 Regenerating editor help cache
#10 0.991 Class 'AbstractPolygon2DEditor' is not exposed, skipping.
#10 0.991 Class 'AbstractPolygon2DEditorPlugin' is not exposed, skipping.
#10 0.992 Class 'ActionMapEditor' is not exposed, skipping.
#10 0.992 Class 'AnchorPresetPicker' is not exposed, skipping.
#10 0.995 Class 'AnimationBezierTrackEdit' is not exposed, skipping.
#10 0.995 Class 'AnimationLibraryEditor' is not exposed, skipping.
#10 0.996 Class 'AnimationNodeBlendSpace1DEditor' is not exposed, skipping.
#10 0.997 Class 'AnimationNodeBlendSpace2DEditor' is not exposed, skipping.
#10 0.997 Class 'AnimationNodeBlendTreeEditor' is not exposed, skipping.
#10 0.997 Class 'AnimationNodeStateMachineEditor' is not exposed, skipping.
#10 0.998 Class 'AnimationPlayerEditor' is not exposed, skipping.
#10 0.998 Class 'AnimationPlayerEditorPlugin' is not exposed, skipping.
#10 0.998 Class 'AnimationTimelineEdit' is not exposed, skipping.
#10 0.998 Class 'AnimationTrackEditDefaultPlugin' is not exposed, skipping.
#10 0.998 Class 'AnimationTrackEditPlugin' is not exposed, skipping.
#10 0.998 Class 'AnimationTrackEditor' is not exposed, skipping.
#10 0.998 Class 'AnimationTrackKeyEditEditorPlugin' is not exposed, skipping.
#10 0.999 Class 'AnimationTreeEditor' is not exposed, skipping.
#10 0.999 Class 'AnimationTreeEditorPlugin' is not exposed, skipping.
#10 0.999 Class 'AnimationTreeNodeEditorPlugin' is not exposed, skipping.
#10 1.002 Class 'AssetLibraryEditorPlugin' is not exposed, skipping.
#10 1.002 Class 'AtlasMergingDialog' is not exposed, skipping.
#10 1.002 Class 'AtlasTileProxyObject' is not exposed, skipping.
#10 1.003 Class 'AudioBusesEditorPlugin' is not exposed, skipping.
#10 1.006 Class 'AudioStreamEditorPlugin' is not exposed, skipping.
#10 1.006 Class 'AudioStreamImportSettingsDialog' is not exposed, skipping.
#10 1.006 Class 'AudioStreamInteractiveEditorPlugin' is not exposed, skipping.
#10 1.006 Class 'AudioStreamInteractiveTransitionEditor' is not exposed, skipping.
#10 1.007 Class 'AudioStreamPlayerInternal' is not exposed, skipping.
#10 1.007 Class 'AudioStreamPreviewGenerator' is not exposed, skipping.
#10 1.007 Class 'AudioStreamRandomizerEditorPlugin' is not exposed, skipping.
#10 1.007 Class 'BackgroundProgress' is not exposed, skipping.
#10 1.015 Class 'BitMapEditorPlugin' is not exposed, skipping.
#10 1.016 Class 'BoneMapEditorPlugin' is not exposed, skipping.
#10 1.019 Class 'CPUParticles2DEditorPlugin' is not exposed, skipping.
#10 1.021 Class 'CPUParticles3DEditor' is not exposed, skipping.
#10 1.021 Class 'CPUParticles3DEditorPlugin' is not exposed, skipping.
#10 1.034 Class 'CSGShape3DGizmoPlugin' is not exposed, skipping.
#10 1.037 Class 'Camera3DEditorPlugin' is not exposed, skipping.
#10 1.040 Class 'CanvasItemEditor' is not exposed, skipping.
#10 1.040 Class 'CanvasItemEditorPlugin' is not exposed, skipping.
#10 1.040 Class 'CanvasItemEditorViewport' is not exposed, skipping.
#10 1.040 Class 'CanvasItemMaterialConversionPlugin' is not exposed, skipping.
#10 1.041 Class 'Cast2DEditor' is not exposed, skipping.
#10 1.041 Class 'Cast2DEditorPlugin' is not exposed, skipping.
#10 1.048 Class 'CollisionPolygon2DEditor' is not exposed, skipping.
#10 1.048 Class 'CollisionPolygon2DEditorPlugin' is not exposed, skipping.
#10 1.048 Class 'CollisionShape2DEditor' is not exposed, skipping.
#10 1.048 Class 'CollisionShape2DEditorPlugin' is not exposed, skipping.
#10 1.053 Class 'ConnectDialog' is not exposed, skipping.
#10 1.053 Class 'ConnectDialogBinds' is not exposed, skipping.
#10 1.053 Class 'ConnectionsDock' is not exposed, skipping.
#10 1.054 Class 'ControlEditorPlugin' is not exposed, skipping.
#10 1.054 Class 'ControlEditorPopupButton' is not exposed, skipping.
#10 1.054 Class 'ControlEditorPresetPicker' is not exposed, skipping.
#10 1.054 Class 'ControlEditorToolbar' is not exposed, skipping.
#10 1.055 Class 'CreateDialog' is not exposed, skipping.
#10 1.055 Class 'CurveEditorPlugin' is not exposed, skipping.
#10 1.055 Class 'CurvePreviewGenerator' is not exposed, skipping.
#10 1.057 Class 'DebugAdapterParser' is not exposed, skipping.
#10 1.057 Class 'DebugAdapterServer' is not exposed, skipping.
#10 1.057 Class 'DebuggerEditorPlugin' is not exposed, skipping.
#10 1.058 Class 'DefaultThemeEditorPreview' is not exposed, skipping.
#10 1.058 Class 'DependencyEditor' is not exposed, skipping.
#10 1.058 Class 'DependencyEditorOwners' is not exposed, skipping.
#10 1.058 Class 'DependencyErrorDialog' is not exposed, skipping.
#10 1.058 Class 'DependencyRemoveDialog' is not exposed, skipping.
#10 1.062 Class 'DirectoryCreateDialog' is not exposed, skipping.
#10 1.062 Class 'DockContextPopup' is not exposed, skipping.
#10 1.062 Class 'DockSplitContainer' is not exposed, skipping.
#10 1.062 Class 'DynamicFontImportSettingsData' is not exposed, skipping.
#10 1.062 Class 'DynamicFontImportSettingsDialog' is not exposed, skipping.
#10 1.063 Class 'EditorAbout' is not exposed, skipping.
#10 1.063 Class 'EditorAssetLibrary' is not exposed, skipping.
#10 1.063 Class 'EditorAudioBuses' is not exposed, skipping.
#10 1.063 Class 'EditorAudioStreamPreviewPlugin' is not exposed, skipping.
#10 1.063 Class 'EditorAudioStreamTooltipPlugin' is not exposed, skipping.
#10 1.063 Class 'EditorAutoloadSettings' is not exposed, skipping.
#10 1.063 Class 'EditorBitmapPreviewPlugin' is not exposed, skipping.
#10 1.063 Class 'EditorBottomPanel' is not exposed, skipping.
#10 1.063 Class 'EditorBuildProfileManager' is not exposed, skipping.
#10 1.064 Class 'EditorDebuggerInspector' is not exposed, skipping.
#10 1.064 Class 'EditorDebuggerNode' is not exposed, skipping.
#10 1.064 Class 'EditorDebuggerRemoteObject' is not exposed, skipping.
#10 1.064 Class 'EditorDebuggerTree' is not exposed, skipping.
#10 1.064 Class 'EditorDirDialog' is not exposed, skipping.
#10 1.064 Class 'EditorDockManager' is not exposed, skipping.
#10 1.064 Class 'EditorExport' is not exposed, skipping.
#10 1.064 Class 'EditorExportGDScript' is not exposed, skipping.
#10 1.284 Class 'EditorFeatureProfileManager' is not exposed, skipping.
#10 1.290 Class 'EditorFileServer' is not exposed, skipping.
#10 1.291 Class 'EditorFileSystemImportFormatSupportQueryBlend' is not exposed, skipping.
#10 1.291 Class 'EditorFontPreviewPlugin' is not exposed, skipping.
#10 1.291 Class 'EditorGradientPreviewPlugin' is not exposed, skipping.
#10 1.291 Class 'EditorHelpBit' is not exposed, skipping.
#10 1.291 Class 'EditorHelpSearch' is not exposed, skipping.
#10 1.291 Class 'EditorImagePreviewPlugin' is not exposed, skipping.
#10 1.291 Class 'EditorImportBlendRunner' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorDefaultPlugin' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorParticleProcessMaterialPlugin' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPlugin3DTexture' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginAnimationTrackKeyEdit' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginAudioStream' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginAudioStreamInteractive' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginBitMap' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginBoneMap' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginControl' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginCurve' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginFontPreview' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginFontVariation' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginGradient' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginGradientTexture2D' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginInputEvent' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginLayeredTexture' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginMaterial' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginMesh' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginPackedScene' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginSkeleton' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginStyleBox' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginSubViewportPreview' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginSystemFont' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginTexture' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginTextureRegion' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorPluginTileData' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorRootMotionPlugin' is not exposed, skipping.
#10 1.291 Class 'EditorInspectorVisualShaderModePlugin' is not exposed, skipping.
#10 1.291 Class 'EditorJSONSyntaxHighlighter' is not exposed, skipping.
#10 1.291 Class 'EditorLayoutsDialog' is not exposed, skipping.
#10 1.291 Class 'EditorLocaleDialog' is not exposed, skipping.
#10 1.291 Class 'EditorLog' is not exposed, skipping.
#10 1.291 Class 'EditorMaterialPreviewPlugin' is not exposed, skipping.
#10 1.291 Class 'EditorMeshPreviewPlugin' is not exposed, skipping.
#10 1.291 Class 'EditorNativeShaderSourceVisualizer' is not exposed, skipping.
#10 1.291 Class 'EditorNode' is not exposed, skipping.
#10 1.292 Class 'EditorOBJImporter' is not exposed, skipping.
#10 1.292 Class 'EditorObjectSelector' is not exposed, skipping.
#10 1.292 Class 'EditorPackedScenePreviewPlugin' is not exposed, skipping.
#10 1.292 Class 'EditorPerformanceProfiler' is not exposed, skipping.
#10 1.292 Class 'EditorPluginCSG' is not exposed, skipping.
#10 1.292 Class 'EditorPluginSettings' is not exposed, skipping.
#10 1.292 Class 'EditorProfiler' is not exposed, skipping.
#10 1.292 Class 'EditorPropertyInteger' is not exposed, skipping.
#10 1.292 Class 'EditorPropertyNameProcessor' is not exposed, skipping.
#10 1.292 Class 'EditorPropertyPath' is not exposed, skipping.
#10 1.292 Class 'EditorPropertyVector2i' is not exposed, skipping.
#10 1.292 Class 'EditorPropertyVectorN' is not exposed, skipping.
#10 1.292 Class 'EditorQuickOpen' is not exposed, skipping.
#10 1.293 Class 'EditorRunBar' is not exposed, skipping.
#10 1.293 Class 'EditorRunNative' is not exposed, skipping.
#10 1.293 Class 'EditorSceneExporterGLTFSettings' is not exposed, skipping.
#10 1.293 Class 'EditorSceneFormatImporterCollada' is not exposed, skipping.
#10 1.293 Class 'EditorSceneFormatImporterESCN' is not exposed, skipping.
#10 1.293 Class 'EditorSceneTabs' is not exposed, skipping.
#10 1.293 Class 'EditorScriptPreviewPlugin' is not exposed, skipping.
#10 1.294 Class 'EditorSettingsDialog' is not exposed, skipping.
#10 1.297 Class 'EditorTexturePreviewPlugin' is not exposed, skipping.
#10 1.297 Class 'EditorTextureTooltipPlugin' is not exposed, skipping.
#10 1.297 Class 'EditorTheme' is not exposed, skipping.
#10 1.297 Class 'EditorTitleBar' is not exposed, skipping.
#10 1.297 Class 'EditorToaster' is not exposed, skipping.
#10 1.297 Class 'EditorValidationPanel' is not exposed, skipping.
#10 1.297 Class 'EditorVisualProfiler' is not exposed, skipping.
#10 1.297 Class 'EditorZoomWidget' is not exposed, skipping.
#10 1.298 Class 'EventListenerLineEdit' is not exposed, skipping.
#10 1.298 Class 'ExportTemplateManager' is not exposed, skipping.
#10 1.298 Class 'FBXImporterManager' is not exposed, skipping.
#10 1.303 Class 'FileSystemList' is not exposed, skipping.
#10 1.303 Class 'FindInFiles' is not exposed, skipping.
#10 1.303 Class 'FindInFilesDialog' is not exposed, skipping.
#10 1.303 Class 'FindInFilesPanel' is not exposed, skipping.
#10 1.303 Class 'FindReplaceBar' is not exposed, skipping.
#10 1.304 Class 'FogMaterialConversionPlugin' is not exposed, skipping.
#10 1.305 Class 'FontEditorPlugin' is not exposed, skipping.
#10 1.306 Class 'GDScriptEditorTranslationParserPlugin' is not exposed, skipping.
#10 1.306 Class 'GDScriptLanguageServer' is not exposed, skipping.
#10 1.306 Class 'GDScriptNativeClass' is not exposed, skipping.
#10 1.306 Class 'GDScriptSyntaxHighlighter' is not exposed, skipping.
#10 1.306 Class 'GLTFDocumentExtensionPhysics' is not exposed, skipping.
#10 1.306 Class 'GLTFDocumentExtensionTextureKTX' is not exposed, skipping.
#10 1.306 Class 'GLTFDocumentExtensionTextureWebP' is not exposed, skipping.
#10 1.307 Class 'GPUParticles2DEditorPlugin' is not exposed, skipping.
#10 1.308 Class 'GPUParticles3DEditor' is not exposed, skipping.
#10 1.308 Class 'GPUParticles3DEditorBase' is not exposed, skipping.
#10 1.308 Class 'GPUParticles3DEditorPlugin' is not exposed, skipping.
#10 1.319 Class 'GPUParticlesCollisionSDF3DEditorPlugin' is not exposed, skipping.
#10 1.324 Class 'Gizmo3DHelper' is not exposed, skipping.
#10 1.324 Class 'GodotNavigationServer2D' is not exposed, skipping.
#10 1.324 Class 'GodotPhysicsServer2D' is not exposed, skipping.
#10 1.324 Class 'GodotPhysicsServer3D' is not exposed, skipping.
#10 1.324 Class 'GradientEditorPlugin' is not exposed, skipping.
#10 1.324 Class 'GradientTexture2DEditorPlugin' is not exposed, skipping.
#10 1.325 Class 'GraphEditFilter' is not exposed, skipping.
#10 1.325 Class 'GraphEditMinimap' is not exposed, skipping.
#10 1.326 Class 'GridMapEditor' is not exposed, skipping.
#10 1.326 Class 'GridMapEditorPlugin' is not exposed, skipping.
#10 1.327 Class 'GroupSettingsEditor' is not exposed, skipping.
#10 1.327 Class 'GroupsEditor' is not exposed, skipping.
#10 1.336 Class 'HistoryDock' is not exposed, skipping.
#10 1.336 Class 'IPUnix' is not exposed, skipping.
#10 1.337 Class 'ImportDefaultsEditor' is not exposed, skipping.
#10 1.337 Class 'ImportDefaultsEditorSettings' is not exposed, skipping.
#10 1.337 Class 'ImportDock' is not exposed, skipping.
#10 1.337 Class 'ImportDockParameters' is not exposed, skipping.
#10 1.338 Class 'InputEventConfigurationDialog' is not exposed, skipping.
#10 1.338 Class 'InputEventEditorPlugin' is not exposed, skipping.
#10 1.344 Class 'InspectorDock' is not exposed, skipping.
#10 1.353 Class 'LightOccluder2DEditor' is not exposed, skipping.
#10 1.353 Class 'LightOccluder2DEditorPlugin' is not exposed, skipping.
#10 1.354 Class 'LightmapGIEditorPlugin' is not exposed, skipping.
#10 1.355 Class 'Line2DEditor' is not exposed, skipping.
#10 1.355 Class 'Line2DEditorPlugin' is not exposed, skipping.
#10 1.357 Class 'LocalizationEditor' is not exposed, skipping.
#10 1.358 Class 'MaterialEditorPlugin' is not exposed, skipping.
#10 1.359 Class 'MeshEditorPlugin' is not exposed, skipping.
#10 1.360 Class 'MeshInstance3DEditor' is not exposed, skipping.
#10 1.360 Class 'MeshInstance3DEditorPlugin' is not exposed, skipping.
#10 1.360 Class 'MeshLibraryEditor' is not exposed, skipping.
#10 1.360 Class 'MeshLibraryEditorPlugin' is not exposed, skipping.
#10 1.362 Class 'MovieWriterMJPEG' is not exposed, skipping.
#10 1.362 Class 'MovieWriterPNGWAV' is not exposed, skipping.
#10 1.362 Class 'MultiMeshEditor' is not exposed, skipping.
#10 1.362 Class 'MultiMeshEditorPlugin' is not exposed, skipping.
#10 1.363 Class 'MultiplayerEditorDebugger' is not exposed, skipping.
#10 1.363 Class 'MultiplayerEditorPlugin' is not exposed, skipping.
#10 1.364 Class 'NavigationLink2DEditor' is not exposed, skipping.
#10 1.364 Class 'NavigationLink2DEditorPlugin' is not exposed, skipping.
#10 1.365 Class 'NavigationMeshEditor' is not exposed, skipping.
#10 1.365 Class 'NavigationMeshEditorPlugin' is not exposed, skipping.
#10 1.365 Class 'NavigationObstacle2DEditor' is not exposed, skipping.
#10 1.365 Class 'NavigationObstacle2DEditorPlugin' is not exposed, skipping.
#10 1.365 Class 'NavigationObstacle3DEditor' is not exposed, skipping.
#10 1.365 Class 'NavigationObstacle3DEditorPlugin' is not exposed, skipping.
#10 1.365 Class 'NavigationPolygonEditor' is not exposed, skipping.
#10 1.365 Class 'NavigationPolygonEditorPlugin' is not exposed, skipping.
#10 1.367 Class 'Node3DEditor' is not exposed, skipping.
#10 1.367 Class 'Node3DEditorPlugin' is not exposed, skipping.
#10 1.367 Class 'Node3DEditorViewport' is not exposed, skipping.
#10 1.367 Class 'Node3DEditorViewportContainer' is not exposed, skipping.
#10 1.367 Class 'NodeDock' is not exposed, skipping.
#10 1.367 Class 'NoiseEditorInspectorPlugin' is not exposed, skipping.
#10 1.367 Class 'NoiseEditorPlugin' is not exposed, skipping.
#10 1.371 Class 'ORMMaterial3DConversionPlugin' is not exposed, skipping.
#10 1.372 Class 'OccluderInstance3DEditorPlugin' is not exposed, skipping.
#10 1.379 Class 'OrphanResourcesDialog' is not exposed, skipping.
#10 1.379 Class 'PackedSceneEditorPlugin' is not exposed, skipping.
#10 1.379 Class 'PackedSceneEditorTranslationParserPlugin' is not exposed, skipping.
#10 1.380 Class 'PanoramaSkyMaterialConversionPlugin' is not exposed, skipping.
#10 1.380 Class 'ParallaxBackgroundEditorPlugin' is not exposed, skipping.
#10 1.381 Class 'ParticleProcessMaterialConversionPlugin' is not exposed, skipping.
#10 1.381 Class 'Path2DEditor' is not exposed, skipping.
#10 1.381 Class 'Path2DEditorPlugin' is not exposed, skipping.
#10 1.381 Class 'Path3DEditorPlugin' is not exposed, skipping.
#10 1.381 Class 'Path3DGizmoPlugin' is not exposed, skipping.
#10 1.383 Class 'PhysicalBone3DEditorPlugin' is not exposed, skipping.
#10 1.384 Class 'PhysicalSkyMaterialConversionPlugin' is not exposed, skipping.
#10 1.397 Class 'PluginConfigDialog' is not exposed, skipping.
#10 1.399 Class 'Polygon2DEditor' is not exposed, skipping.
#10 1.399 Class 'Polygon2DEditorPlugin' is not exposed, skipping.
#10 1.399 Class 'Polygon3DEditor' is not exposed, skipping.
#10 1.399 Class 'Polygon3DEditorPlugin' is not exposed, skipping.
#10 1.400 Class 'PostImportPluginSkeletonRenamer' is not exposed, skipping.
#10 1.400 Class 'PostImportPluginSkeletonRestFixer' is not exposed, skipping.
#10 1.400 Class 'PostImportPluginSkeletonTrackOrganizer' is not exposed, skipping.
#10 1.401 Class 'ProceduralSkyMaterialConversionPlugin' is not exposed, skipping.
#10 1.404 Class 'ProgressDialog' is not exposed, skipping.
#10 1.404 Class 'ProjectExportDialog' is not exposed, skipping.
#10 1.404 Class 'ProjectExportTextureFormatError' is not exposed, skipping.
#10 1.404 Class 'ProjectSettingsEditor' is not exposed, skipping.
#10 1.404 Class 'PropertySelector' is not exposed, skipping.
#10 1.409 Class 'RenameDialog' is not exposed, skipping.
#10 1.412 Class 'ReparentDialog' is not exposed, skipping.
#10 1.412 Class 'ReplicationEditor' is not exposed, skipping.
#10 1.412 Class 'ResourceFormatImporterSaver' is not exposed, skipping.
#10 1.413 Class 'ResourcePreloaderEditor' is not exposed, skipping.
#10 1.413 Class 'ResourcePreloaderEditorPlugin' is not exposed, skipping.
#10 1.418 Class 'RunInstancesDialog' is not exposed, skipping.
#10 1.418 Class 'SceneCacheInterface' is not exposed, skipping.
#10 1.418 Class 'SceneCreateDialog' is not exposed, skipping.
#10 1.418 Class 'SceneExporterGLTFPlugin' is not exposed, skipping.
#10 1.418 Class 'SceneImportSettingsData' is not exposed, skipping.
#10 1.418 Class 'SceneImportSettingsDialog' is not exposed, skipping.
#10 1.418 Class 'SceneRPCInterface' is not exposed, skipping.
#10 1.418 Class 'SceneReplicationInterface' is not exposed, skipping.
#10 1.418 Class 'SceneTileProxyObject' is not exposed, skipping.
#10 1.418 Class 'SceneTreeDialog' is not exposed, skipping.
#10 1.418 Class 'SceneTreeDock' is not exposed, skipping.
#10 1.418 Class 'SceneTreeEditor' is not exposed, skipping.
#10 1.418 Class 'ScreenSelect' is not exposed, skipping.
#10 1.429 Class 'ScriptEditorDebugger' is not exposed, skipping.
#10 1.429 Class 'ScriptEditorPlugin' is not exposed, skipping.
#10 1.434 Class 'SectionedInspector' is not exposed, skipping.
#10 1.434 Class 'SectionedInspectorFilter' is not exposed, skipping.
#10 1.436 Class 'ShaderCreateDialog' is not exposed, skipping.
#10 1.436 Class 'ShaderEditorPlugin' is not exposed, skipping.
#10 1.436 Class 'ShaderFileEditor' is not exposed, skipping.
#10 1.436 Class 'ShaderFileEditorPlugin' is not exposed, skipping.
#10 1.436 Class 'ShaderGlobalsEditor' is not exposed, skipping.
#10 1.436 Class 'ShaderGlobalsEditorInterface' is not exposed, skipping.
#10 1.437 Class 'SizeFlagPresetPicker' is not exposed, skipping.
#10 1.437 Class 'Skeleton2DEditor' is not exposed, skipping.
#10 1.437 Class 'Skeleton2DEditorPlugin' is not exposed, skipping.
#10 1.437 Class 'Skeleton3DEditorPlugin' is not exposed, skipping.
#10 1.437 Class 'Skeleton3DGizmoPlugin' is not exposed, skipping.
#10 1.438 Class 'SkeletonIK3DEditorPlugin' is not exposed, skipping.
#10 1.445 Class 'SnapDialog' is not exposed, skipping.
#10 1.448 Class 'SplitContainerDragger' is not exposed, skipping.
#10 1.449 Class 'Sprite2DEditor' is not exposed, skipping.
#10 1.449 Class 'Sprite2DEditorPlugin' is not exposed, skipping.
#10 1.454 Class 'SpriteFramesEditor' is not exposed, skipping.
#10 1.454 Class 'SpriteFramesEditorPlugin' is not exposed, skipping.
#10 1.458 Class 'StandardMaterial3DConversionPlugin' is not exposed, skipping.
#10 1.461 Class 'StyleBoxEditorPlugin' is not exposed, skipping.
#10 1.464 Class 'SubViewportPreviewEditorPlugin' is not exposed, skipping.
#10 1.464 Class 'SurfaceUpgradeDialog' is not exposed, skipping.
#10 1.464 Class 'SurfaceUpgradeTool' is not exposed, skipping.
#10 1.468 Class 'Texture3DEditorPlugin' is not exposed, skipping.
#10 1.470 Class 'TextureEditorPlugin' is not exposed, skipping.
#10 1.470 Class 'TextureLayeredEditorPlugin' is not exposed, skipping.
#10 1.473 Class 'TextureRegionEditor' is not exposed, skipping.
#10 1.473 Class 'TextureRegionEditorPlugin' is not exposed, skipping.
#10 1.473 Class 'ThemeContext' is not exposed, skipping.
#10 1.473 Class 'ThemeEditor' is not exposed, skipping.
#10 1.473 Class 'ThemeEditorPlugin' is not exposed, skipping.
#10 1.473 Class 'ThemeEditorPreview' is not exposed, skipping.
#10 1.473 Class 'ThemeItemEditorDialog' is not exposed, skipping.
#10 1.473 Class 'ThemeItemImportTree' is not exposed, skipping.
#10 1.473 Class 'ThemeTypeDialog' is not exposed, skipping.
#10 1.473 Class 'ThemeTypeEditor' is not exposed, skipping.
#10 1.473 Class 'TileAtlasView' is not exposed, skipping.
#10 1.474 Class 'TileMapEditorPlugin' is not exposed, skipping.
#10 1.474 Class 'TileMapLayerEditor' is not exposed, skipping.
#10 1.474 Class 'TileMapLayerEditorTerrainsPlugin' is not exposed, skipping.
#10 1.474 Class 'TileMapLayerEditorTilesPlugin' is not exposed, skipping.
#10 1.474 Class 'TileProxiesManagerDialog' is not exposed, skipping.
#10 1.474 Class 'TileSetAtlasSourceEditor' is not exposed, skipping.
#10 1.474 Class 'TileSetAtlasSourceProxyObject' is not exposed, skipping.
#10 1.474 Class 'TileSetEditor' is not exposed, skipping.
#10 1.474 Class 'TileSetEditorPlugin' is not exposed, skipping.
#10 1.474 Class 'TileSetScenesCollectionProxyObject' is not exposed, skipping.
#10 1.475 Class 'TileSetScenesCollectionSourceEditor' is not exposed, skipping.
#10 1.475 Class 'TileSourceInspectorPlugin' is not exposed, skipping.
#10 1.475 Class 'TilesEditorUtils' is not exposed, skipping.
#10 1.477 Class 'UVEditDialog' is not exposed, skipping.
#10 1.484 Class 'VersionControlEditorPlugin' is not exposed, skipping.
#10 1.484 Class 'ViewPanner' is not exposed, skipping.
#10 1.486 Class 'ViewportNavigationControl' is not exposed, skipping.
#10 1.486 Class 'ViewportRotationControl' is not exposed, skipping.
#10 1.489 Class 'VisualShaderConversionPlugin' is not exposed, skipping.
#10 1.514 Class 'VoxelGIEditorPlugin' is not exposed, skipping.
#10 1.517 Class 'WindowWrapper' is not exposed, skipping.
#10 1.530 Loaded builtin CA certificates
#10 2.540 EditorSettings: Save OK!
^C#10 CANCELED
ERROR: failed to solve: Canceled: context canceled
```
</details> 

### Steps to reproduce

Prerequisites: Linux environment with docker installed.
 
1. Download the testproject: [docker-setup-blend-bug.zip](https://github.com/user-attachments/files/18043979/docker-setup-blend-bug.zip)
2. Copy the godot executable you want to test into the folder besides the run.sh
3. Rename the godot executable to `godot`
4. Run `run.sh`, expected outcome: stuck / endless loop
5. Remove blend file
6. Run `run.sh`, expected outcome: terminates 

### Minimal reproduction project (MRP)

[docker-setup-blend-bug.zip](https://github.com/user-attachments/files/18043979/docker-setup-blend-bug.zip)

### PR DESCRIPTION
**Pull request by DanielKinsman**
Godot currently tries to open a dialog box in headless mode then waits forever for it to complete. Instead just fail straight away when in headless mode.

Fixes #100122

### CODE REVIEW

File: modules/gltf/editor/editor_scene_importer_blend.cpp [hunk 1]
```diff
@@ -516,6 +516,8 @@ void EditorFileSystemImportFormatSupportQueryBlend::_update_icons() {
 }
 
 bool EditorFileSystemImportFormatSupportQueryBlend::query() {
+	ERR_FAIL_COND_V_MSG(DisplayServer::get_singleton()->get_name() == "headless", true, "Blender path is invalid or not set, check your Editor Settings.");
```
Comment (AThousandShips) [inline modules/gltf/editor/editor_scene_importer_blend.cpp]: This error message should be clearer

**Review by AThousandShips — DISMISSED** [review]

File: modules/gltf/editor/editor_scene_importer_blend.cpp (hunk 1 above)
Comment (DanielKinsman) [reply modules/gltf/editor/editor_scene_importer_blend.cpp]: updated it

File: modules/gltf/editor/editor_scene_importer_blend.cpp [hunk 2]
```diff
@@ -516,6 +516,8 @@ void EditorFileSystemImportFormatSupportQueryBlend::_update_icons() {
 }
 
 bool EditorFileSystemImportFormatSupportQueryBlend::query() {
+	ERR_FAIL_COND_V_MSG(DisplayServer::get_singleton()->get_name() == "headless", true, "Blender is required to import .blend files but it could not be found.");
```
Comment (AThousandShips) [inline modules/gltf/editor/editor_scene_importer_blend.cpp]: What I mean is that this is not an error that blender cannot be found, it's that you're in headless mode, the error should reflect this, something like:
```suggestion
	ERR_FAIL_COND_V_MSG(DisplayServer::get_singleton()->get_name() == "headless", true, "Blender path is invalid or not set, check your Editor Settings. Cannot configure blender path in headless mode.");
```

Comment (DanielKinsman) [reply modules/gltf/editor/editor_scene_importer_blend.cpp]: From the user's point of view they aren't trying to configure it so I think that makes it more confusing to say they "cannot" it. To them the error occurs because blender cannot be found, in a headless scenario this is likely because it isn't even installed, e.g. a CI build on a server.

Ultimately though any message with "blender" in it will be enough to point them in the right direction so let's run with it.

**Review by lyuma — APPROVED** [review]
Approving because the current behavior will infinite loop and is clearly broken. The reason this PR is needed is due to the dangerous nested main loop, which is highly unconventional and not done in any other place in the code:

```cpp
while (true) {
		DisplayServer::get_singleton()->process_events();
		Main::iteration();
		if (!configure_blender_dialog->is_visible() || confirmed) {
			break;
		}
	}
```

I agree that it is better to ERR_FAIL and display a warning message for headless. I do wonder if it might be better to avoid invoking `EditorFileSystemImportFormatSupportQueryBlend` in the first place. I do not get why we are creating this whole object only to guaranteed ERR_FAIL.

Should headless mode perform autodetection? I believe it currently will return true without having set a path, which is inconsistent with the non-headless behavior which disables blend import and returns false.

**Comment by DanielKinsman** [comment]
I did look at fixing it further up the call stack but it seemed to be in generic importer land and not in anything blender related, and I didn't want to accidentally cause explosions for other well behaved importers.

> Should headless mode perform autodetection? I believe it currently will return true without having set a path, which is inconsistent with the non-headless behavior which disables blend import and returns false.

I don't know what "autodetection" is in this context? Disabling blend import seems to require saving and overwriting the user's editor settings which I am hesitant to do in a headless run. So I am avoiding that but returning `true` the same way that the [gui version does](https://github.com/godotengine/godot/blob/master/modules/gltf/editor/editor_scene_importer_blend.cpp#L611) after it disables blend import. I must admit though, I don't know what the return value is supposed to signify, it doesn't appear to be documented. Testing it with both true and false, I get this behaviour:

`true`: fails to import then segfaults.
`false`: fails to import then the process exists with success (0 return code).

I guess we probably want the second one, and people can inspect the output to determine success or failure? A non-zero return code would sure be ideal, but I guess that is a whole separate issue...

**Comment by Repiteo** [comment]
Thanks!
