### PR TITLE
[Windows] Fix left/right Shift key regression

### LINKED ISSUE #101384: Keys do not release properly if left shift and right shift are held at the same time
### Tested versions

- Reproducible in 4.3.stable.official, 4.4.dev7.official

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 32.0.15.6603) - Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 Threads)

### Issue description

If you create input actions for left shift (Physical left) and right shift (Physical right) they work fine as long as you press one at a time, but if you press both shift keys at the same time they will not release properly.

If you release one key, both will still count as being still pressed and when you let go of the other key that key will properly release while the first key will still count as pressed and is now stuck in a perpetual "key pressed" state. This is the same regardless of if using `Input.is_key_pressed()` or the `_input(event)` function with `exact_match = true`

I was planning to use this feature for a pinball game and was very excited Godot finally supports physical left and right shift keys but due to this bug they are currently unusable. The problem still persists in the 4.4 dev snapshot.

### Steps to reproduce

Add new action for left shift (Physical left) and right shift (Physical right) in Input Map, press both shift keys at the same time and then release them.

### Minimal reproduction project (MRP)

[shiftstuck.zip](https://github.com/user-attachments/files/18375232/shiftstuck.zip)

### PR DESCRIPTION
**Pull request by SupSuper**
This fixes a regression introduced in #92415 and reported in #101384.

When multiple Shift keys are pressed, Windows only sends a KEYUP for the last key released, leaving the other stuck pressed. A workaround was introduced in #80231 to fake this missing KEYUP event.
However this workaround was broken in #92415. _get_mods() returns the modifier keys *before* the KEYUP, so there will always be a Shift key pressed before it's released.

This PR restores the original check and respective functionality. The MRP in #101384 can be used to reproduce and confirm the fix.

Thanks to @ghostsoft @andyprice @romlok for helping debug the issue.

* *Bugsquad edit, fixes: #101384*

### CODE REVIEW

**Comment by Zireael07** [comment]
Can you add a comment explaining WHY this function and not the other?

**Comment by bruvzg** [comment]
The difference between `mods/GetKeyboardState` and `GetAsyncKeyState` is how they interact with message queue. For a fake key injection in the raw input handler, it is likely correct to use `GetAsyncKeyState` since normal input messages are not processed at this moment. Will test it tomorrow.

**Review by bruvzg — APPROVED** [review]

**Comment by SupSuper** [comment]
@Zireael07 
> Can you add a comment explaining WHY this function and not the other?

The goal is to send a fake KEYUP event *when* a Shift key is released *after* a Shift key is pressed. (i.e. check if Shift keys are still pressed after the KEYUP).
`mods/GetKeyboardState` doesn't work for this because it returns the state *before* the KEYUP is resolved, so there will always be a Shift key pressed. You either end up sending no fake events or duplicate events.

The only solutions were:
* Extend `_get_mods` to also handle Left/Right modifier keys so we can check for both pressed.
* Rewrite everything to use RawInput.
* Use `GetAsyncKeyState` to check the real key state (the old solution).

Since the old solution still worked, I opted for the simplest fix.

**Comment by Zireael07** [comment]
@SupSuper I meant a comment in code, so that future contributors know why

**Review by Repiteo — APPROVED** [review]
There's already another use of `GetAsyncKeyState` in that script, so I don't think a comment is imperative. With that said, even though it's probably outside the scope of this PR, it'd be nice to have a similar wrapper for `GetAsyncKeyState` like we already do with `GetKeyState` in `mouse_get_button_state` & `GetKeyboardState` with `_get_mods` (maybe an optional `p_async` bool for the latter?).

I'll approve all the same, but give a bit of time before merging if you wanna get a rebase in with that comment.

**Comment by SupSuper** [comment]
@Zireael07 Done.

File: platform/windows/display_server_windows.cpp [hunk 1]
```diff
@@ -4684,7 +4684,9 @@ LRESULT DisplayServerWindows::WndProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARA
 					// If multiple Shifts are held down at the same time,
 					// Windows natively only sends a KEYUP for the last one to be released.
 					if (raw->data.keyboard.Flags & RI_KEY_BREAK) {
-						if (!mods.has_flag(WinKeyModifierMask::SHIFT)) {
+						// Make sure to check the latest key state since
+						// we're in the middle of the message queue.
```
Comment (Repiteo) [inline platform/windows/display_server_windows.cpp:4688]: This bit of trailing whitespace caused the style check to fail.
```suggestion
						// we're in the middle of the message queue.
```

Comment (SupSuper) [reply platform/windows/display_server_windows.cpp]: Fixed

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
