### PR TITLE
Enforce mult-of-4 requirements on etcpak input.

### LINKED ISSUE #49981: Corruption on VRAM-compressed texture mipmaps (S3TC compression)
### Godot version

eb318d3e04ac6d3bb01b0f2a8311d06ba55c3a2b

### System information

Windows 10, Vulkan, Nvidia GTX 1080 (471.11)

### Issue description

It appears that the mipmaps of textures imported as VRAM Compressed can appear with odd skewing distortion.

editor_screenshot_2021-06-29T050000

The cube in the centre is using a texture with VRAM compression, while the other cubes are using the other four options. This issue does not appear to affect all textures, but it seems consistently broken on the example texture provided.

### Steps to reproduce

Simply open the example project and observe the middle cube with VRAM Compressed version of the texture at an appropriate distance to see the mipmaps.

### Minimal reproduction project

[mipmaps.zip](https://github.com/godotengine/godot/files/6730593/mipmaps.zip)

### PR DESCRIPTION
**Pull request by lyuma**
Re: https://github.com/godotengine/godot/issues/49981

Adds back a variation old code from modules/etc/image_compress_etc.cpp to enforce ~~power-of-two (mipmapped) and~~ multiple of 4 ~~(non-mipmapped)~~ on compressed textures.

Here is the original code from before etcpak was added:
https://github.com/godotengine/godot/pull/47370/files#diff-d43a3b757699a828b4602b39b53ce14bc22f35556ed7ea2d3943608f90bf4d34

There was something else [added by reduz in February, 2019](https://github.com/godotengine/godot/commit/74d0ed2236b333d0a292e15b9c2a9380c2c122a1#diff-4949ecbffc5fadfd3ef6ff61bcc12d88c51ea8fd1bc17d586f624b9b56685fa6R422-R427) to enforce power-of-two, but it was only intended for GLES2 and doesn't seem to be in the right place in the code to solve this particular issue.

Intermediate mipmap levels need to be resized to Nx4 or 4xN accordingly, since etcpak is stricter about padding.

Not doing so causes the following artifact when sampling the 2x2 or 1x1 mipmap levels:
image
It looks normal when samplihg 4x4 or higher:
image
Here is what I think is happening before this PR.
```
		8x8 data...
		4x4 data...
		2x2 data...
		1x1 data...
		8888888888888888..8888844444444444444422221xxxxxxxxxxxxxxxxxx <-- current state.
last two mipmap levels sample out-of-bounds
possible idea: resize Nx2 and 2xN and lower to multiple of 4, using a temporary buffer
		8888888888888888..8888844444444444444422222222222222221111111111111111
```
I have now implemented the above.

*Bugsquad edit:*
- Fixes #49981

### CODE REVIEW

**Comment by lyuma** [comment]
All right, this PR is ready for review!

Update:
I have reread the relevant specifications and dropped the power-of-2 requirement. multiple of 4 is only required on the first LOD, of course.

Here is an image showing the 2nd mipmap LOD from an 20x20 texture, matching the example in the Direct3D spec.
image

Unfortunately I picked a poor choice of branch name, as "po2" is no longer a part of this PR. Shall I open a new one or will we live with it?

**Comment by akien-mga** [comment]
> Unfortunately I picked a poor choice of branch name, as "po2" is no longer a part of this PR. Shall I open a new one or will we live with it?

That's fine as is :)

File: core/io/image.cpp [hunk 1]
```diff
@@ -1434,12 +1434,11 @@ int Image::_get_dst_image_size(int p_width, int p_height, Format p_format, int &
 		}
 
 		// Set mipmap size.
-		// It might be necessary to put this after the minimum mipmap size check because of the possible occurrence of "1 >> 1".
 		if (r_mm_width) {
-			*r_mm_width = bw >> 1;
+			*r_mm_width = w;
```
Comment (clayjohn) [inline core/io/image.cpp:1438]: Does this change fix a different bug or is it related to the other fixes in this PR? The connection is not obvious to me (being only somewhat familiar with the texture import code)

Comment (lyuma) [reply core/io/image.cpp:1438]: I was having unexplained corruption with some texture dimensions and traced it to these returned width/height values (returned by `Image::get_image_mipmap_offset_and_dimensions`).

For example, on the 12x12 texture (block=4), I was seeing this. First loop iteration
```
{
  bw=12, bh=12
  s=144
  w = 6, h = 6
  *r_mm_width = (12>>1) = 6
  *r_mm_height = (12>>1) = 6
}
```
Second loop iteration
```
{
  bw=8, bh=8
  s=64
  w = 3, h = 3
  *r_mm_width = (8>>1) = 4 <-- wrong!
  *r_mm_height = (8>>1) = 4 <-- wrong!
}
```
Third loop iteration
```
{
  bw=4, bh=4
  s=16
  w = 1, h = 1
  *r_mm_width = (4>>1) = 2 <-- wrong!
  *r_mm_height = (4>>1) = 2 <-- wrong!
}
```

Note that the behavior of this function was altered slightly by 81ed9fa31bc63823235f64c88d441a8e530ab039
However, It was also wrong before. It's possible either that Godot always had this bug with 2x2 and 1x1 mipmaps reading out-of-bounds, or didn't cause an issue before because the old `etc` compression library ignored the out-of-bounds data.

I can't see any reason for the return values to use these "half-block" values. I would think if I want to know the dimensions of a mipmap level, I would want the actual dimensions, namely `w` and `h`. I can't find any callers of this code which would be adversely affected by this change.

In case you want to check my assertions, the only public functions using these `*r_mm_` return values are `Image::get_image_mipmap_size` and `Image::get_image_mipmap_offset_and_dimensions`.

I did some further digging into that logic, so a quick history breakdown. @reduz originally added this `*r_mm_width = bw;` statement in 0586e184490fd132f99acb1a67c788959cfdbade . This function was only used in one place, in what is now `servers/rendering/renderer_rd/renderer_storage_rd.cpp`. However, the function was only ever used with FORMAT_RGBA8 for the longest time, meaning block size is 1 and bw == w and bh == h. For this reason, I suspect reduz either never tested it with compressed formats, or had a different intended usecase in mind than what it has ultimately been used for.

Alright, I know I talk too much. I hope this answers your question about why this code change was necessary, why it was relevant to this PR, and why it evaded notice for so long. I'll also loop in @floppyhammer as they made the more recent commit here.

Comment (floppyhammer) [reply core/io/image.cpp:1438]: What I did in https://github.com/godotengine/godot/commit/81ed9fa31bc63823235f64c88d441a8e530ab039 is just to make mipmap 0 correspond to the first mipmap instead of the original texture. The block size matching logic was there before that PR. As I haven't got a Vulkan-capable computer on hand right now, I will try to take a closer look at this on Monday.

Comment (lyuma) [reply core/io/image.cpp:1438]: aha, and I think my version does the same thing, since I reference 'w' and 'h' after they are shifted by 1, compared with your code using bw shifted by 1. So I think in this sense, they both fulfill the requirement of having mipmap 0 correspond to the first mipmap.

My change should just be handling the non-multiple-of-four mipmaps a bit more carefully than how it was written before..

File: modules/etcpak/image_compress_etcpak.cpp [hunk 2]
```diff
@@ -132,8 +132,35 @@ void _compress_etcpak(EtcpakType p_compresstype, Image *r_img, float p_lossy_qua
...
+	For mipmaps, the top level map is required to be a multiple of 4 size in all dimensions.
+	The sizes for the lower level maps are computed as they are for all mipmapped surfaces,
+	and thus may not be a multiple of 4, for example a top level map of 20 results in a second level
+	map size of 10. For these cases, there is a differing 'physical' size and a 'virtual' size.
+	The virtual size is that computed for each mip level without adjustment, which is 10 for the example.
+	The physical size is the virtual size rounded up to the next multiple of 4, which is 12 for the example,
+	and this represents the actual memory size. The sampling hardware will apply texture address
+	processing based on the virtual size (using, for example, border color if specified for accesses
+	beyond 10), and thus for the example case will not access the 11th and 12th row of the resource.
+	So for mipmap chains when an axis becomes < 4 in size, only texels 'a','b','e','f' (see diagram below)
```
Comment (clayjohn) [inline modules/etcpak/image_compress_etcpak.cpp:151]:
```suggestion
	So for mipmap chains when an axis becomes < 4 in size, only texels 'a','b','e','f'
```

File: modules/etcpak/image_compress_etcpak.cpp [hunk 3]
```diff
@@ -132,8 +132,35 @@ void _compress_etcpak(EtcpakType p_compresstype, Image *r_img, float p_lossy_qua
...
+	are used for a 2x2 map, and texel 'a' is used for 1x1. Note that this is similar to, but distinct from,
+	the surface pitch, which can encompass additional padding beyond the physical surface size.
+	*/
+	int next_width = (width + 3) & ~3; // MAX(4, mipmaps ? next_power_of_2(width) : (width + 3) & ~3);
+	int next_height = (height + 3) & ~3; // MAX(4, mipmaps ? next_power_of_2(height) : (height + 3) & ~3);
```
Comment (clayjohn) [inline modules/etcpak/image_compress_etcpak.cpp:156]:
```suggestion
	int next_width = (width + 3) & ~3;
	int next_height = (height + 3) & ~3;
```

File: core/io/image.cpp (hunk 1 above)
Comment (clayjohn) [reply core/io/image.cpp:1438]: Thanks for the detailed explanation. That all makes sense to me!

I see that ``Image::get_image_mipmap_offset_and_dimensions`` is also used here https://github.com/godotengine/godot/blob/c99c5a1caeafab161daebdde21ccd83ecdc897d5/scene/resources/texture.cpp#L400 But this code appears to only be used when loading VRAM compressed textures, so it makes sense that the logic mirrors the logic when compressing the texture in the first place.

**Review by RandomShaper — APPROVED** [review]
The only things that I may not be sure about would have failed miserably if wrong, so looks good to me.

**Review by clayjohn — APPROVED** [review]

**Comment by lawnjelly** [comment]
Presumably the power of 2 requirement is for mipmaps that could be used tiled.

Afaik If it isn't to be used tiled, you can use padding.
If you are using wrapping but power of 4 this works for the first mipmap, but not necessarily for later mipmaps, e.g.
width 116 becomes width 29 on first mipmap, but width 7.25 on 2nd mipmap.

**Comment by akien-mga** [comment]
Thanks!
