### PR TITLE
Remove AnimationMixer bindings only bound in the editor

### LINKED ISSUE #82993: Calling AnimationPlayer.RootNode from C# errors in exported version
### Godot version

4.2-dev6

### System information

Windows 11

### Issue description

Using the `RootNode` getter on `AnimationPlayer` from C# causes the following error in both debug and release exports.

```sh
ERROR: System.TypeInitializationException: The type initializer for 'Godot.AnimationMixer' threw an exception.
 ---> Godot.GodotObject+NativeMethodBindNotFoundException: Unable to find the native method bind. (Method 'AnimationMix)
   at Godot.GodotObject.ClassDB_get_method_with_compatibility(StringName type, StringName method, UInt64 hash)
   at Godot.AnimationMixer..cctor()
   --- End of inner exception stack trace ---
   at Godot.AnimationMixer.GetRootNode()
   at Godot.AnimationMixer.get_RootNode()
   at TestCSharp._Ready() in C:\Users\Pooh\Code\games\test-4.2dev6-animplayer\TestCSharp.cs:line 11
   at Godot.Node.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret)
   at Godot.CanvasItem.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret)
   at Godot.Node2D.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret)
   at TestCSharp.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in C:8
   at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** arg)
   at: void Godot.NativeInterop.ExceptionUtils.LogException(System.Exception) (:0)
```

The code runs fine in the editor and the same issue does not happen with GDScript.

### Steps to reproduce

**From scratch:**

1. Create a C# script that references an `AnimationPlayer`.
2. Call `AnimationPlayer.RootNode`.
3. Create a debug or release export.
4. Run the export with console.
5. The scene will show a "GDScript" label, but not the "CSharp" label because the CSharp script errored.
6. Check the console output for the error message.

**With the MRP:**

1. Create an export.
2. Run the export with console.
3. Same steps as above.

### Minimal reproduction project

[dotnet-getrootnode-mrp.zip](https://github.com/godotengine/godot/files/12840388/dotnet-getrootnode-mrp.zip)

### PR DESCRIPTION
**Pull request by raulsntos**
Removes bindings inside `#ifdef TOOL_ENABLED` that would only be bound in the editor and break the C# bindings in exported games.

- Fixes https://github.com/godotengine/godot/issues/82993.

### CODE REVIEW

File: scene/animation/animation_mixer.cpp [hunk 1]
```diff
@@ -2095,14 +2113,7 @@ void AnimationMixer::_bind_methods() {
 	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "active"), "set_active", "is_active");
 	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "deterministic"), "set_deterministic", "is_deterministic");
 
-#ifdef TOOLS_ENABLED
-	ClassDB::bind_method(D_METHOD("_reset"), &AnimationMixer::reset);
-	ClassDB::bind_method(D_METHOD("_restore", "backup"), &AnimationMixer::restore);
```
Comment (raulsntos) [inline scene/animation/animation_mixer.cpp:2100]: These don't seem to need to be bound, so I just removed them.

File: scene/animation/animation_mixer.cpp [hunk 2]
```diff
@@ -2095,14 +2113,7 @@ void AnimationMixer::_bind_methods() {
...
-	ClassDB::bind_method(D_METHOD("set_reset_on_save_enabled", "enabled"), &AnimationMixer::set_reset_on_save_enabled);
-	ClassDB::bind_method(D_METHOD("is_reset_on_save_enabled"), &AnimationMixer::is_reset_on_save_enabled);
-	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "reset_on_save", PROPERTY_HINT_NONE, ""), "set_reset_on_save_enabled", "is_reset_on_save_enabled");
```
Comment (raulsntos) [inline scene/animation/animation_mixer.cpp:2103]: This seems like it was only bound to add a checkbox to the inspector, so I moved it to `_get_property_list`, `_get` and `_set`.

File: scene/animation/animation_mixer.cpp [hunk 3]
```diff
@@ -2095,14 +2113,7 @@ void AnimationMixer::_bind_methods() {
...
 	ADD_SIGNAL(MethodInfo("mixer_updated")); // For updating dummy player.
```
Comment (raulsntos) [inline scene/animation/animation_mixer.cpp:2116]: The signal is now bound in non-editor builds even though it's only emitted in editor builds. I'm not sure if that's OK, but the signal is used by `AnimationPlayerEditorPlugin` so I think it's still needed.

File: scene/animation/animation_mixer.cpp (hunk 2 above)
Comment (akien-mga) [reply scene/animation/animation_mixer.cpp:2103]: I think it should simply be exposed for both tools and non-tools builds. It can be documented that it's only functional in the editor.

Comment (raulsntos) [reply scene/animation/animation_mixer.cpp:2103]: Oh, actually we have to expose it because it was exposed before so it would break compat not to.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
The documentation seems to already properly flag the property and signal as editor-only.

**Comment by akien-mga** [comment]
Thanks!
