### PR TITLE
Fix node naming in scene tree dock

### LINKED ISSUE #54813: Copy paste naming bug
### Godot version

v4.0.dev.20211108.official [596865366]

### System information

Windows 10

### Issue description

When you copy and paste a node, it gets a weird name like: CollisionShape2D -> @CollisionShape2D@23668
I'm not quite sure if this is a bug or if it's intentional, however it was different in the previous build.

### Steps to reproduce

v4.0.dev.20211108.official [596865366]:
CLxDNlrIjW
v4.0.dev.20211027.official [157cba393]:
E2Eaq1o6MF

Edit: Okay it is definitely a bug:
Godot4_Pg3hRGsTfH

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by KoBeWi**
I originally wanted to avoid using "legible unique name" when not necessary, but seems like there are many unforeseen cases where it breaks. Well, it doesn't hurt to use it everywhere here.

Fixes #54813

### CODE REVIEW

File: editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -259,8 +259,8 @@ void SceneTreeDock::_replace_with_branch_scene(const String &p_file, Node *base)
 	int pos = base->get_index();
 	undo_redo->add_do_method(parent, "remove_child", base);
 	undo_redo->add_undo_method(parent, "remove_child", instantiated_scene);
-	undo_redo->add_do_method(parent, "add_child", instantiated_scene);
-	undo_redo->add_undo_method(parent, "add_child", base);
+	undo_redo->add_do_method(parent, "add_child", instantiated_scene, true;
```
Comment (akien-mga) [inline editor/scene_tree_dock.cpp:262]: You lost the parenthesis.

Comment (KoBeWi) [reply editor/scene_tree_dock.cpp]: 🙃

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
