### PR TITLE
GDScript assert message parsing bug fixed

### LINKED ISSUE #43540: Can't concatenate strings inside assert
**Godot version:**

dd54851

**Issue description:**

```
assert(true, "I" + "am" + "error")
```
This works fine in 3.2.x, but in 4.0 it shows
image

### PR DESCRIPTION
**Pull request by ThakeeNathees**
Fix: #43540

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -1215,7 +1215,12 @@ void GDScriptAnalyzer::resolve_constant(GDScriptParser::ConstantNode *p_constant
 void GDScriptAnalyzer::resolve_assert(GDScriptParser::AssertNode *p_assert) {
 	reduce_expression(p_assert->condition);
 	if (p_assert->message != nullptr) {
-		reduce_literal(p_assert->message);
+		reduce_expression(p_assert->message);
+		if (!p_assert->message->is_constant) {
+			push_error(R"(Expected constant string for assert error message.)", p_assert->message);
+		} else if (p_assert->message->reduced_value.get_type() != Variant::STRING) {
+			push_error(R"(Expected constant string for assert error message.)", p_assert->message);
```
Comment (aaronfranke) [inline modules/gdscript/gdscript_analyzer.cpp:1222]: Aren't these blocks identical?

```suggestion
		if (!p_assert->message->is_constant || p_assert->message->reduced_value.get_type() != Variant::STRING) {
			push_error(R"(Expected constant string for assert error message.)", p_assert->message);
```

Comment (ThakeeNathees) [reply modules/gdscript/gdscript_analyzer.cpp:1222]: yeah, I'll change it. It was different error messages for resolving enum values  1. should be constant, 2. should be an integer. here I combined the messages as "expected constant string"

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
