### PR TITLE
[RTL] Fix `outline_size=0` and `font`/`otf` tags with invalid arguments breaking tag stack and spamming errors.

### LINKED ISSUE #110440: [outline_size=0] BBCode parameter produces error
### Tested versions

Godot 4.4.1 Stable

### System information

MacOS 15.6.1 | M4 Pro MacBook Pro 24GB 

### Issue description

I kept getting an error when working on a scene with several RichTextLabels:

**ERROR: scene/gui/rich_text_label.cpp:4139 - Parameter "current->parent" is null.**

I did some debugging and found out the problem line was `[outline_size=0]`. When I changed it to `[outline_size=1]` the error goes away.

If this isn't a bug then maybe the documentation needs to be updated. Since in the Inspector I can set the Font Outline Size to 0, I'd assume the same would be true in BBCode. I should also add that `[outline_size=0]` does work, but it spawns the error as well.

For full documentation purposes, this is the error in the debugger when I run the scene with `[outline_size=0]`:

```
E 0:00:00:915   pop: Parameter "current->parent" is null.
  <C++ Source>  scene/gui/rich_text_label.cpp:4139 @ pop()
```

Seems mildly similar to [this issue](https://github.com/godotengine/godot/issues/84243).

### Steps to reproduce

1. Add a RichTextLabel to a Scene
2. Enable BBCode
3. Add the line: `[outline_size=0][/outline_size]`

### Minimal reproduction project (MRP)

[error-project.zip](https://github.com/user-attachments/files/22289030/error-project.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/110440

Before:
Screenshot 2025-09-12 at 08 52 13

After:
Screenshot 2025-09-12 at 08 53 02

### CODE REVIEW

File: scene/gui/rich_text_label.cpp [hunk 1]
```diff
@@ -6026,18 +6026,18 @@ void RichTextLabel::append_text(const String &p_bbcode) {
...
+			ItemFont *font_it = _find_font(current);
+			if (font_it) {
+				if (font_it->font.is_valid()) {
+					font = font_it->font;
+					def_font = font_it->def_font;
 				}
-				Dictionary features;
+			}
+			Dictionary features;
+			if (subtag.size() > 0) {
```
Comment (KoBeWi) [inline scene/gui/rich_text_label.cpp]:
```suggestion
			if (!subtag.is_empty()) {
```

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
