### PR TITLE
Rearrange TriangleMesh function to workaround MSVC compiler bug

### LINKED ISSUE #59964: Ray picking in 3D editor broken in release_debug MSVC builds
### Godot version

a49079947b7ffde28262cc4978cae9bbec24361b

### System information

Windows 10, Vulkan, Intel® Core™ i7-8700K, Nvidia GTX 1080 (471.11)

### Issue description

It would appear that click-selection for meshes is broken when compiling as release_debug (and presumably regular release) in the 3D editor. Placing any mesh instance in a scene then clicking on the mesh in the viewport should subsequently select the node, and while this works on debug builds, the nodes will not be selected on release_debug builds. Selection box selection still works in both builds though.

I have not indicated exactly how far back this is the case, but I believe from some preliminary investigation that at the very least has been completely broken for several months, but probably signifcantly longer.

### Steps to reproduce

Simply create a new project, create a scene with a MeshInstance node, then assign it any default mesh primitive or array mesh. Then attempt to click on the mesh in the 3D viewport. In debug builds, the node should be selected, but in release_debug, nothing will happen.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by SaracenOne**
Closes #59964

So, this bug is a bit weird. One the surface, there should be nothing wrong we the way the code is written other than it perhaps *looking* a little clunky, but it seems that raycast collision tests totally break when compiling with MSVC with release compiler optimisations (and maybe LLVM too; I'm still looking into this). Changing it to this appears to make it work, whereas previous you couldn't click-select nodes in the 3D viewport. I only noticed the issue with raycast tests, but I added the same change to all the functions for consistency and safety.

I kind of want to look into this more including comparing assembly output since this could be a good test case for a compiler bugs, and the implication of other bugs like this popping up feels concerning.

While this specific line appears to be the culprit for this bug, there are other potentially concerning aspects of these functions including what appears to the stack array leaking, and the fact that while I don't think it *should* be possible to overrun the stack given how the BVH is generated, it still gives warnings to the effect of potential stack overruns.

### CODE REVIEW

**Comment by GeorgeS2019** [comment]
@SaracenOne 
What you discover is VERY INTERSTING.


@lewiji  is able to build the dotnet6 branch and make it works (create csproj and dotnet publish) using Linux e.g. Ubuntu 20.04. 

However, we are still struggling with MSVC build (it works partially, we are not able to create csproj, add an instance of c# script etc.)

I really wonder how much your finding here would be relevant to future Godot4 mono MSVC build

File: core/math/triangle_mesh.cpp [hunk 1]
```diff
@@ -231,14 +231,12 @@ Vector3 TriangleMesh::get_area_normal(const AABB &p_aabb) const {
 			}
 			case VISIT_LEFT_BIT: {
 				stack[level] = (VISIT_RIGHT_BIT << VISITED_BIT_SHIFT) | node;
-				stack[level + 1] = b.left | TEST_AABB_BIT;
-				level++;
+				stack[++level] = b.left | TEST_AABB_BIT;
```
Comment (akien-mga) [inline core/math/triangle_mesh.cpp:234]: That's pretty confusing that a compiler would trip up on this... But if it works `¯\_(ツ)_/¯``

Another option if it works (might be more friendly in the Godot codebase as we usually avoid the ambiguity of `++i` and `i++` (personally I need to think a few seconds each time to be sure about what's going to happen):
```suggestion
				level++;
				stack[level] = b.left | TEST_AABB_BIT;
```
Though I'm not strongly opposed to the current form either, in the context of this code it's fairly explicit.

Comment (akien-mga) [reply core/math/triangle_mesh.cpp:234]: That doesn't appear to be related to this PR at all.

Comment (SaracenOne) [reply core/math/triangle_mesh.cpp:234]: This was mostly from a friend's suggestion and I actually did have it that way (which also fixed it), but honestly, I'm happy to do it whatever way you'd prefer. All I know is that the way it was being was causing bugs in MSVC

Comment (SaracenOne) [reply core/math/triangle_mesh.cpp:234]: Also, my bad about the other issue. That's clearly an oversight. I will correct it

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
