### PR TITLE
[GDNative] added "new" method and fixed headers

### LINKED ISSUE #8432: [GDNative] Cannot instance GDNativeScript using `new`
Godot 3.0 pre-alpha master
Windows 10 64 bits MSVC

I am making an `opensimplex` GDNative plugin that registers a `Noise` class inheriting Reference (not a node script, unlike the news shows). 
So I compiled my library as a `.dll` using the C++ kit, and put it in the project with GDNaive libraries as well.

Then I created these resources:
`opensimplex.tres`, which references my `.dll` (and other platforms in the future),
`noise.gdn`, which is a resource referencing the `Noise` class within my library.

However, the following didn't work:

```gdscript
const OsnNoise = preload("res://addons/zylann.opensimplex/noise.gdn")

func _ready():
	var noise = OsnNoise.new()
```
`Invalid call. Nonexistent function 'new' in base 'GDNativeScript'.`

@karroffel told me the `new` method might indeed be missing.

-----------------
**The following is wrong due to earlier confusion based on a wrong guess.**

However, I got confused when I went to create an instance of my class in GDScript. Apparently, as @karroffel told me, the `.gdn` already is an instance of the `Noise` class. So getting the instance looks like this:

```gdscript
var noise = load("noise.gdn")
```
But there are numerous things I find wrong with it:

1) It is inconsistent compared to how GDScript classes usually work. From my experience using GDScript, a `.gd` file behaves as a `Resource` containing a *class*, not an *instance*. So instancing it actually look like this:
```gdscript
const Klass = preload("klass.gd")
var obj = Klass.new()
```
And if the Klass inherit a `Node`, you should get a node instance with the script on it. Same for Resources I guess.

2) It makes class constants harder to access, because they are usually bound as "static" members of the class. However with this you are forced to get the constant from an instance of the class, instead of the class itself. Again, in GDScript, this is how it looks:
```gdscript
const Klass = preload("klass.gd")
print(Klass.SOME_CONSTANT)
# or
print(Mesh.PRIMITIVE_TRIANGLES)
```

3) Creating an instance from scratch is too complicated, or requires to create a `.gdn` file which would look like a singleton.
Without a file, this is the code required (pure guess, this code actually doesn't work for some reason, although the same process happens in the editor when creating a `.gdn` file. @karroffel tell me if I'm wrong on this one):
```gdscript
var noise = GDNativeScript.new()
noise.library = preload("opensimplex.tres")
noise.script_name = "Noise"
```

What I would expect is for the .gdn file to represent a class, not an instance, and to be able to create instances the following way:

```gdscript
const Noise = preload("noise.gdn")
var noise = Noise.new()
```~~

### PR DESCRIPTION
**Pull request by karroffel**
Fixes #8432

### CODE REVIEW

File: modules/gdnative/gdnative.cpp [hunk 1]
```diff
@@ -391,6 +391,55 @@ void GDNativeScript::get_script_signal_list(List<MethodInfo> *r_signals) const {
...
+	} else {
+		owner = memnew(Reference); //by default, no base means use reference
+	}
+
+	Reference *r = owner->cast_to<Reference>();
+	if (r) {
+		ref = REF(r);
+	}
+
+	// GDScript does it like this: _create_instance(p_args, p_argcount, owner, r != NULL, r_error);
```
Comment (bojidar-bg) [inline modules/gdnative/gdnative.cpp]: GDScript might not, but GDNative might...
