### PR TITLE
Batching - use FINAL_MODULATE_ALIAS in shaders

### LINKED ISSUE #46873: 3.2.4 RC4 modulate and tilemap inconsistencies
Godot 3.2.4 RC4. Also observed in RC3.

MacOs Big Sur 11.2.2 (20D80), Mid 2015 Retina Macbook 15'. AMD Radeon R9 M370X.
Both GLES3 and GLES2 display issues. Has also showed up on Android (GLES3).

**Issue description:**
Watch the [5 minute video for a demonstration](https://www.youtube.com/watch?v=zaSTcj_Lz7Y).

A 2D shader that consists of this:
```
COLOR = vec4(1.0);
COLOR *= MODULATE;
```

Displays odd behavior, especially on tilemaps:
* Two colors show up in the tilemap, depending on how filled-in it is.
* Sometimes the color might change based on the zoom level in editor.
* It seems that in GLES2 the darker one is the normal modulate, the light is no modulate. In GLES3 the dark is... double modulate? No idea. The light color is the regular modulate. I think.

The change seems to depend around the center of the object (though it does happens further out as well). Moved object retains the issue. Non-tilemap sprites do share at least a part of the issue.

GLES3:
image

GLES3: Colors are darker, as if modulate happened twice:
image

GLES2: Colors seem to be accurate, but the issue with only part of the tilemap being modulated persists:
image

**Steps to reproduce and a testing project**
Have a simple tilemap. Give it the shader material with the shader as above. Give it a *modulate* value. Draw around, watch it break, un-break, re-break.

I've made a [video where i reproduced the issue](https://www.youtube.com/watch?v=zaSTcj_Lz7Y). The project from that video: [tilemap_shader.zip](https://github.com/godotengine/godot/files/6117230/tilemap_shader.zip)

### PR DESCRIPTION
**Pull request by lawnjelly**
As part of the improvements to batch more cases, batching can store final_modulate as an attribute in the vertex format rather than sending as a uniform. This allows draw calls with different final_modulate to be batched together.

However custom shader code was reading from only the final_modulate uniform, and not the attribute when it was in use. This was leading to visual errors.

This is tricky to solve, because we cannot use the same name for the attribute in the vertex and fragment shaders, because one is an attribute and one a varying, whereas a uniform is accessible anywhere. To get around this, a macro is used which can translate to the most appropriate variable depending on whether uniform or attribute or varying is required.

Fixes #46873

## Notes
* This needs a good consultation with @clayjohn. There may be more than one way of fixing this, and it does seem a bit like a sledgehammer to crack a walnut, there may be a better way.
* In particular any use of `final_modulate` directly to create a shader from the c++ source code (i.e. not using MODULATE) will read from the wrong color. I couldn't immediately see any cases of this by searching but it is a possibility.
* Although this fixes the bug, I noticed that when you have an error in your shader, it ends up in some kind of half way situation where the color read is incorrect. I'm assuming that `USE_ATTRIB_MODULATE` does not get defined if the shader is broken. This is not a massive problem as a broken shader can't be expected to behave correctly but it would be nice to track this down.
* Unfortunately this does have the possibility of regressions. I'll try and test as much as possible. Alternatively I could see whether it would be possible to temporarily turn off this batching path for 3.2.4, although that might be just as risky.

### CODE REVIEW

File: drivers/gles2/shader_compiler_gles2.cpp [hunk 1]
```diff
@@ -911,7 +911,7 @@ ShaderCompilerGLES2::ShaderCompilerGLES2() {
 	actions[VS::SHADER_CANVAS_ITEM].renames["INSTANCE_CUSTOM"] = "instance_custom";
 
 	actions[VS::SHADER_CANVAS_ITEM].renames["COLOR"] = "color";
-	actions[VS::SHADER_CANVAS_ITEM].renames["MODULATE"] = "final_modulate";
+	actions[VS::SHADER_CANVAS_ITEM].renames["MODULATE"] = "FINAL_MODULATE_ALIAS";
```
Comment (clayjohn) [inline drivers/gles2/shader_compiler_gles2.cpp:914]: Small nitpick. For style consistency, this should still be lowercase.

**Review by clayjohn — CHANGES_REQUESTED** [review]
Overall looks good to me. I had to refresh myself on the batching logic, but it all makes sense. 

I'm not seeing why this is a high risk merge. I would go ahead and merge it for the next RC if we can. 

Just a minor style nitpick to fix up before merging

File: drivers/gles2/shader_compiler_gles2.cpp (hunk 1 above)
Comment (lawnjelly) [reply drivers/gles2/shader_compiler_gles2.cpp:914]: the `final_modulate_alias`? Yup I did wonder about that. Normally I tend to use upper case for macros but here lower case could be better.

File: drivers/gles2/shaders/canvas.glsl [hunk 2]
```diff
@@ -469,6 +480,18 @@ void main() {
 		normal_used = true;
 #endif
 
+		// If larger fvfs are used, final_modulate is passed as an attribute.
+		// we need to read from this in custom fragment shaders or applying in the post step,
+		// rather than using final_modulate directly.
+#if defined(FINAL_MODULATE_ALIAS)
+#undef FINAL_MODULATE_ALIAS
+#endif
+#ifdef USE_ATTRIB_MODULATE
```
Comment (lawnjelly) [inline drivers/gles2/shaders/canvas.glsl:489]: Forgot to mention, wasn't 100% sure we needed this, as although this is one file to godot, it gets split into 2 for vertex and fragment shader. I don't suppose it does any harm...

File: drivers/gles2/shader_compiler_gles2.cpp (hunk 1 above)
Comment (lawnjelly) [reply drivers/gles2/shader_compiler_gles2.cpp]: Fixed.

File: drivers/gles2/shaders/canvas.glsl (hunk 2 above)
Comment (clayjohn) [reply drivers/gles2/shaders/canvas.glsl:489]: My thinking exactly.

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
