### PR TITLE
Shortcuts rework - fixed issues with input propagation and triggering of unwanted shortcuts.

### LINKED ISSUE #17591: Ctrl+F in the script editor doesn't work if shader editor is open at the same time
Godot 3.0.2
Windows 10 64 bits

Repro:
1) Open script editor
2) Open shader editor at the same time to see both script and shader
3) Click in the script editor to focus it
4) Hit Ctrl+F: notice the search doesn't open in the script editor, in the shader editor instead.

Expected: the search should open in the currently focused text editor.

### LINKED ISSUE #31779: Pressing delete key while having animation selected in AnimatedSprite should delete animation not a node
**Godot version:**
3.1

**OS/device including version:**
Win 10

**Issue description:**

In AnimatedSprite when you add some animation and want to remove them you can select animation and press delete key this will then delete a AnimatedSprite node where as user is likely wanting to delete animation itself or a frame. 

I believe this is because node is still selected in a scene tree and editor thinks key presses are related to a node not anything else. Solution to this problem would be the moment user clicks on any resource to unselct node and treat last thing user clicked on as main focus. 

Expected behaviour from this would be I crate AnimatedSprite Create animation "idle" with 3 different frames. If I click on a individual frame and press delete I should delete this frame only. If I click on animation "idle" and click delete I should delete whole animation and if I click on AnimatedSprite and press delete I should delete node. 

**Steps to reproduce:**

Just add any animation to a AnimatedSprite and press delete.

**Minimal reproduction project:**

### LINKED ISSUE #35834: Delete key doesn't Delete Node when Visual Script Editor is open
**Godot version:**
3.2

**OS/device including version:**
Linux Mint 19.2 Cinnamon

**Issue description:**
The Delete key does not Delete the selected node when focusing a node in the Scene Tree when the Visual Script Editor is open. This is due to Delete being mapped to Delete Selected (visual node) in the context of Visual Script Editor, and this context being considered active despite focusing the Scene Tree. Note that when pressing Delete however, the last focused Visual node is not deleted either; nothing happens instead.

If you remove the mapping of Delete in Visual Script Editor context (or remap Delete Selected to another key), Delete will work correctly on the Scene Tree.

**Steps to reproduce:**
With default mappings:

1. Create a Visual Script and keep the Visual Script Editor open.
2. Select a node in the scene tree (outside the Root)
3. Press Delete

Result: nothing happens

Bonus: do the same, but after removing Delete Selected mapping in Visual Script Editor context.

Result: Godot prompts for node deletion as expected

### LINKED ISSUE #36205: While in script editor ctrl+D paste a line instead of the duplicating node
**Godot version:** 3.2
cant reproduce in 3.1.2

**OS/device including version:** Linux

**Issue description:** 
Peek 2020-02-14 10-37

**Steps to reproduce:** 
1. Create project, add node like Timer or Tween
2. Open Script editor 
3. select Timer node and Press Ctrl+D

### LINKED ISSUE #37054: Select All in the inspector text boxes might trigger Create New Node dialog
**Godot version:**
3.2.1

**Steps to reproduce:**
1. Create a new node (must be done via shortcut, i.e. Ctrl + A)
2. Enter some text to the Editor Description of that node
3. Press Ctrl + A to select all text
4. ->Create New Node appears again

If you try to do Ctrl + A again or didn't use the shortcut to add the node, the text will be correctly selected.

### LINKED ISSUE #37807: Input Map Ctrl+D assign issue
**Godot version:**
3.2.1

**OS/device including version:**
Windows 7 Professional 64-bit

**Issue description:**
Assigning Ctrl+D to an action doesn't work while the GDScript editor is open in the background, but assign works when editor is closed.
Noticed this while testing key combo assigns.

**Steps to reproduce:**
Press Ctrl+D when Input Map assign window is open and GDScript editor is open in the background.

**Minimal reproduction project:**

GodotBug

### LINKED ISSUE #38922: Duplicating node by Ctrl+D duplicates code
**Godot version:**
3.2.2 beta 2 8cf450c16b

**OS/device including version:**
Linux mint 19.3

**Issue description:**
Duplicating node by Ctrl+D duplicates code of current line, not duplicating node.

**Steps to reproduce:**
1. Duplicate node by Ctrl + D with 2D viewport
2. Duplicate node by Ctrl + D with script editor
duplicate_node

**Minimal reproduction project:**

### LINKED ISSUE #41248: Delete key deletes local node while in remote scene
**Godot version:** v3.2.2.stable.official

**OS/device including version:** Windows 10 Home 10.0.18363 Build 18363 

**Issue description:** Pressing the delete key when viewing a remote scene will attempt to delete any node selected in the local scene

**Steps to reproduce:** Open a scene and select a node in the local tab then run the game and switch to the remote tab in the godot editor, then press the delete key

### PR DESCRIPTION
**Pull request by EricEzaM**
The key file to look at is `base_button.cpp`. The rest is mainly just adding the usage of the new API, and changing of names. There are a couple of other commits with some input/shortcut related changes. You can view those commits on their own to see what was changed.

**What does this solve?**
This solves a number of shortcut related issues which have been around the engine for quite some time. Issue listed below.
Fixes #36205, fixes #38922, fixes #37807, fixes #37054, fixes #17591, fixes #35834, fixes #31779
(Supersedes) closes #37068 and closes #39039 

Most notably this allows greater control over what context shortcuts are allowed to be triggered.

**What changes are there and how does it solve the issue?**
`Control`'s have a new method - `set_shortcut_context(ObjectID p_ctx)`. This allows you to set the 'context' of where the shortcut is allowed to work. See the below image. The MenuButton's have the `ScriptTextEditor` as their context. This means that you have the option to ensure that their shortcuts will only trigger if the `ScriptTextEditor` or any of it's children have GUI focus in the viewport.

image

This context is used wherever you want to check for shortcuts. Most commonly, this will be inside `unhandled_key_input`. Here is an example for the ScriptTextEditor...

**script_text_editor.cpp (constructor)**
```
edit_menu = memnew(MenuButton);
edit_menu->set_text(TTR("Edit"));
edit_menu->set_shortcut_context(this);
```
**menu_button.cpp**
```
void MenuButton::_unhandled_key_input(Ref<InputEvent> p_event) {
	if (!is_focus_owner_in_shorcut_context()) {
		return;
	}

        < ... more logic ... >
}
```

If the focus of the viewport is not a child of the context, then no input is handled. Nice!

---

I am pretty sure I have caught every case of Buttons and MenuButtons being used as shortcuts and have added `set_shortcut_context` where it is needed, but it is possible I missed a few.

Through my work I also found a number of redundant pieces of code, which included some `_unhandled_key_input` calls which were never reached since their functionality was actually handled in a parent.

**In Action:**
#17591
shader_script_editor_working

#37054
script_scenetree_CtrlD_CtrlA_working

**Also Works in script...**
In this clip I spam the button shortcut I set up. As you can see, it only works when the shortcut context has the viewport focus. 
shortcuts_demo1

### CODE REVIEW

**Comment by EricEzaM** [comment]
Ok, after some initial discussion with @groud this might be too much of an overcomplication for what is needed. I'll do some updates and also post the IRC log here later.

**Comment by BeayemX** [comment]
Will this also solve #22843?

**Comment by EricEzaM** [comment]
@BeayemX No, pressing escape to close the bottom panel was removed completely. That functionality would need to be reinstated for it work.

**Comment by EricEzaM** [comment]
```
[12:03:04] <EricEzaM[m]> Groud: Akien reduz yesterdays input and shortcuts discussion now in PR form... #42109.
[12:03:05] <IssueBot_> #42109: Shortcuts rework - fixed issues with input propagation and triggering of unwanted shortcuts. | https://git.io/JUBP2
[12:17:06] <Groud> EricEzaM: I don't get it, why would you have to create a whole new method instead of using _unhandled_key_input ?
[12:19:10] <Groud> The only thing needed was to check if the focus was in the given context no ? So like context.is_a_parent_of(focussed_node)
[12:20:20] <Groud> I mean this logic could have been implemented in the few places where we handle shortcuts, which are not that many
[12:22:09] <Groud> The justification you use for creating a new function is for the function to receive less events, but using _unhandled_key_input is rarely done, and it already processes few arguments
[12:22:16] <Groud> So there is no performance gain here
[12:23:02] <Groud> Honestly, I would simply use _unhandled_key_input, which was kind of meant for keyboard shortcuts, and not create yet another function dedicated to shortcuts.
[12:23:56] <EricEzaM[m]> @groud currently viewport doesnt expose a public method for getting focused node
[12:26:03] <EricEzaM[m]> also i mentioned shortcuts might not just be keyboard. Having ability for extra mouse buttons to act in shortcuts would be a plus
[12:26:49] <Groud> hmm
[12:27:15] <Groud> I don't know... why not but it kind of annoys me to create another function only for that...
[12:27:45] <EricEzaM[m]> I understand, I kind of thought the same thing but I didn't know what else to do
[12:27:55] <EricEzaM[m]> What you say does make me think though...
[12:28:20] <Groud> The thing is that it kind of make _unhandled_key_input useless now
[12:28:51] <EricEzaM[m]> The other thing is that shortcuts are for gui only
[12:29:21] <Groud> hmm, I guess that would make sense
[12:29:50] <Groud> but I am not sure it is worth creating yet another function only to allow shortcuts for mouse buttons
[12:29:57] <EricEzaM[m]> What if `unhandled_key_input` becomes `unhandled_button_input` or something similar, and is not only restricted to `InputEventKey` but Key, MouseButton and JoyButton as I have in this PR.
[12:29:58] <Groud> It's kind of an unusual use case
[12:30:11] <Groud> ah
[12:31:06] <Groud> That might be a good idea, as we would still have few events compared to handling mouse moves/joy sticks
[12:31:22] <Groud> I like it, that would solve the problem quite well
[12:31:25] <EricEzaM[m]> then, on controls you can set `set_shortcut_context` as I have in this PR. Then you register to use `unhandled_button_input`, and when you do, you check  if `get_viewport()->get_gui_focus()` is a parent of the `shortcut_context`
[12:31:43] <EricEzaM[m]> and I would need to add a viewport method which exposes the gui focus
[12:31:51] <EricEzaM[m]> publicly
[12:32:17] <Groud> I don't think you need that in fact
[12:33:06] <Groud> simply call context->get_focus_owner() to get the focus
[12:34:00] <EricEzaM[m]> oh yeah it is exposed that way
[12:34:02] <EricEzaM[m]> nice
[12:39:05] <Groud> EricEzaM: maybe let's see what reduz think about this first though :)
```

File: editor/editor_help.cpp [hunk 1]
```diff
@@ -56,19 +56,6 @@ void EditorHelp::_init_colors() {
 	class_desc->add_theme_constant_override("line_separation", Math::round(5 * EDSCALE));
 }
 
-void EditorHelp::_unhandled_key_input(const Ref<InputEvent> &p_ev) {
```
Comment (EricEzaM) [inline editor/editor_help.cpp:59]: FYI this was removed because the search popup is actually handled through `ScriptEditor::_menu_option`, via the `Search` menu button in the script editor. This code would never be hit.

image

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 2]
```diff
@@ -471,29 +471,34 @@ float CanvasItemEditor::snap_angle(float p_target, float p_start) const {
...
+				grid_step_multiplier = MIN(grid_step_multiplier + 1, 12);
+				viewport->update();
+			} else if ((grid_snap_active || show_grid) && divide_grid_step_shortcut.is_valid() && divide_grid_step_shortcut->is_shortcut(p_ev)) {
+				// Divide the grid size
+				Point2 new_grid_step = grid_step * Math::pow(2.0, grid_step_multiplier - 1);
+				if (new_grid_step.x >= 1.0 && new_grid_step.y >= 1.0) {
+					grid_step_multiplier--;
+				}
+				viewport->update();
 			}
```
Comment (EricEzaM) [inline editor/plugins/canvas_item_editor_plugin.cpp:501]: This looks like a lot of changes but all I did was add the `is_valid()` check since the input might not always be `InputEventKey` now.

File: editor/animation_track_editor.cpp [hunk 3]
```diff
@@ -5701,6 +5702,7 @@ AnimationTrackEditor::AnimationTrackEditor() {
 	timeline->set_zoom(zoom);
 
 	edit = memnew(MenuButton);
+	edit->set_shortcut_context(get_instance_id());
```
Comment (reduz) [inline editor/animation_track_editor.cpp:5705]: I would make it still pass a Control*, to make API easier, but internally get the ID

File: editor/plugins/asset_library_editor_plugin.cpp [hunk 4]
```diff
@@ -1277,7 +1280,7 @@ void EditorAssetLibrary::disable_community_support() {
 }
 
 void EditorAssetLibrary::_bind_methods() {
-	ClassDB::bind_method("_unhandled_input", &EditorAssetLibrary::_unhandled_input);
+	ClassDB::bind_method("_unhandled_button_input", &EditorAssetLibrary::_unhandled_button_input);
```
Comment (reduz) [inline editor/plugins/asset_library_editor_plugin.cpp:1283]: I think it should remain as _unhandled_key_input, what I meant is that if we at any point need to add button support (like joypad, mouse, etc) we can add an _unhandled_button_input, but we need to wait to see if this is something needed or that makes sense for users at some point.

**Review by reduz — CHANGES_REQUESTED** [review]

File: editor/plugins/asset_library_editor_plugin.cpp (hunk 4 above)
Comment (groud) [reply editor/plugins/asset_library_editor_plugin.cpp:1283]: I personally believe it would be good to have shortcuts support mouse buttons, it's a good to have for not much trouble.
But still, I would avoid adding yet another function only this. IMHO it's better to have all those events inside an `_unhandled_key_or_button_input`, so that nodes implementing shortcuts would have only one function to override, not two.

Comment (EricEzaM) [reply editor/plugins/asset_library_editor_plugin.cpp:1283]: Via discussion in IRC it was agreed that handling Mouse Button events is more complicated than it looks at the surface.

For this reason, the API will remain as `_unhandled_key_input` and only support keys at this stage.

**Comment by EricEzaM** [comment]
@akien-mga Please let me know if you want me to squash some or all of the commits. I feel they are unrelated enough to warrant separate commits but it is up to you.

**Comment by akien-mga** [comment]
> Please let me know if you want me to squash some or all of the commits. I feel they are unrelated enough to warrant separate commits but it is up to you.

The current commit lineup looks good to me :+1:

**Review by groud — APPROVED** [review]

**Comment by EricEzaM** [comment]
@akien-mga Can I bump this one ;)

**Comment by akien-mga** [comment]
I'll try to get it reviewed by @reduz this week.
Given the age of the last commit, might be worth giving it a rebase to ensure that it still builds and works as expected.

**Comment by EricEzaM** [comment]
Rebased

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks a ton, it's great to get all these issues finally solved :)

**Comment by Feniks-Gaming** [comment]
Thank you it will solve a lot of headaches I had
