### PR TITLE
Fix GDScript external inner class constant assignment

### LINKED ISSUE #69917: GDScript 2.0: Cannot assign external inner class as a constant
### Godot version

4.0.dev (05097de)

### System information

Linux (Ubuntu 22.04), Vulkan, Radeon RX Vega 64 (eGPU)

### Issue description

It's a regression that was introduced very recently. Using `git bisect`, it seems that the regression comes from #69907.

We cannot assign inner classes as constants.

```gdscript
# test.gd
extends Node

const Lambda: = preload("res://lambda.gd")
const InnerClass: = Lambda.InnerClass  # the script error is thrown here

func _ready() -> void:
	var inst: InnerClass = InnerClass.new()
```

```
SCRIPT ERROR: Parse Error: Initializer for a constant must be a constant expression.
          at: GDScript::reload (res://test.gd:4)
```
Inner classes should be assignable to constants.

### Steps to reproduce

1. Open the MRP
2. Open `test.gd`
3. Note the error

### Minimal reproduction project

[innerclass_constant.zip](https://github.com/godotengine/godot/files/10202773/innerclass_constant.zip)

### PR DESCRIPTION
**Pull request by adamscott**
Sets the reduced value of a inner class as the parsed inner class GDScript instance.

This reenables the assignment of a inner class as a constant.

Fixes #69917 - GDScript 2.0: Cannot assign inner class as a constant

### CODE REVIEW

**Comment by adamscott** [comment]
Removed the draft status. @rune-scape and @anvilfolk, could you take a look?

**Comment by vonagam** [comment]
Note, `scr->find_class` here can return null in editor.

Example, copy paste this code or comment/uncomment it after that.
```gdscript
class A:
  class B:
    const X := A.B
```

Because there is some cache of the file `A` will be missing in subclasses hashmap of the script when `A.B` will be evaluated. So the reduced value is `nullptr`. (You can check it by editing the code and adding something like `if (src == nullptr) prtintf("Hah\n");`.)

But somehow it does not matter. Even if you use other constants and access them through `A.B` there is no warning. 

I know that because I want to make static functions available as constants with reduced value of Callable. But Callable complains that it's constructor called with null as an object when commenting/uncommenting code in the editor.

For this case it seems to be working without a problem, at least I cannot produce a situation where this null is revealed, but maybe in the future it will show itself in some edge case.

**Comment by adamscott** [comment]
I'm curious if #70000 will fix some of the issues you mention @vonagam.

**Comment by vonagam** [comment]
Does not seems like it. The problem is that editor has cached script (which you get when call `get_full_script`) and it does not have copy-pasted or uncommented subclasses in it as they are added in `make_scripts`.

**Comment by adamscott** [comment]
@vonogram But cached scripts are the same, they are just references, not copy of old versions.

And when you save, `GDScript::reload()` should be called I think, which runs `GDScriptParser` and `GDScriptAnalyzer` through the script.

**Comment by vonagam** [comment]
[`GDScriptCompiler::make_scripts`](https://github.com/godotengine/godot/blob/8d52eea52b4914a26409823047fc2ffd82c294f0/modules/gdscript/gdscript_compiler.cpp#L2664) populates a script `subclasses` with instances of scripts for those subclasses.

It is get called in [`GDScriptCache::get_shallow_script`](https://github.com/godotengine/godot/blob/8d52eea52b4914a26409823047fc2ffd82c294f0/modules/gdscript/gdscript_cache.cpp#L260) when the script is first requested.

And as you saying cached scripts are the same, they are references, so on reload a script which is already in cache will not have its subclasses repopulated with new ones.

**Comment by vonagam** [comment]
Ah, I see now. Yes, there is `GDScript::reload` which gets called and it [calls](https://github.com/godotengine/godot/blob/8d52eea52b4914a26409823047fc2ffd82c294f0/modules/gdscript/gdscript.cpp#L889) `GDScriptCompiler::compile`, which in turn [calls](https://github.com/godotengine/godot/blob/8d52eea52b4914a26409823047fc2ffd82c294f0/modules/gdscript/gdscript_compiler.cpp#L2714) `make_scripts` to update subclasses. The problem is that the call to compiler happens after [this call](https://github.com/godotengine/godot/blob/8d52eea52b4914a26409823047fc2ffd82c294f0/modules/gdscript/gdscript.cpp#L870) to analyzer. So on reload analyzer has stale subclasses.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -3615,8 +3615,17 @@ void GDScriptAnalyzer::reduce_subscript(GDScriptParser::SubscriptNode *p_subscri
 			if (attr_type.is_set()) {
 				valid = true;
 				result_type = attr_type;
-				p_subscript->is_constant = p_subscript->attribute->is_constant;
-				p_subscript->reduced_value = p_subscript->attribute->reduced_value;
+				if (base_type.is_constant && result_type.kind == GDScriptParser::DataType::CLASS) {
```
Comment (anvilfolk) [inline modules/gdscript/gdscript_analyzer.cpp:3618]: I wonder whether instead of doing this work here, it would be possible to simply call `reduce_identifier_from_base` and have this code as one of the special cases of that function. Would that make sense? Would it make it more reusable elsewhere?

Comment (adamscott) [reply modules/gdscript/gdscript_analyzer.cpp]: I successfully (for the first time, not that I had not tried) moved the code to `reduce_identifier_from_base()`!

Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp]: What about outer lookup?

Also instead of `p_base != nullptr && p_base->is_constant` you can say `base.is_constant`, no?

Comment (anvilfolk) [reply modules/gdscript/gdscript_analyzer.cpp]: > I successfully (for the first time, not that I had not tried) moved the code to `reduce_identifier_from_base()`!

It's easy to have opinions on someone else's code but I am glad it worked!

**Comment by vonagam** [comment]
I see now why the fact that `reduce_value` is nullptr is not visible much. It is for the same reason that this PR exist - meta types are now a little bit exempt from their usage of `reduce_value` like in `reduce_subscript` (which is most of the time). So `A.B.value` before would get `value` from reduced value of `B`, but now analyzer is used and `B` here mostly for the type in such case.

**Comment by adamscott** [comment]
@vonagam I tested your example with this branch, but I get errors, which is normal. So where's the issue?
Yes, the editor autocomplete seems off and suggests `A.B.X`, but at the end, this is not permitted.

```gdscript
extends Node

const External: = preload("res://external_test.gd")

func _ready() -> void:
	var test: = External.A.B.X
```

Here's the error.
```
SCRIPT ERROR: Parse Error: Cannot find member "X" in base "B".
          at: GDScript::reload (res://test2.gd:6)
```

**Comment by adamscott** [comment]
@vonagam Please use the issue https://github.com/godotengine/godot/issues/70206 to add stuff about local inner classes. This PR (I just renamed it) is for the assignment of external inner classes as constant.

**Comment by adamscott** [comment]
> And there is outer lookup. It seems wrong to expose outer class through inner class, so I guess the check should be reverse and datatype should only be set if `p_base` is null, currently datatype set in in all cases.
> 
> ```gdscript
> class A:
>   class B: pass
> class X: pass
> ```
> 
> To illustrate: I think, it is wrong to access `X` as `A.B.X` or as `b.X` (where `b is B`), it should be accessible only as `X` (without base) for things inside `A` and `B`.

@vonagam About this, please create a new issue.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
