### PR TITLE
Re-Allow absolute paths, make them behave correctly

### LINKED ISSUE #6801: local:// totally broken in load()
**Operating system or device - Godot version:**
linux x11 HEAD (12843167cacf3bacca32c29b7ea8b4426392bad0)

**Issue description** (what happened, and what was expected):
load fails on any local:// path
since some recent update load no longer works on absolute paths without prepending local:// however the big problem is that local:// doesn't seem to work either.  My server just lost its only way to access external enduser-supplied resources (which is not part of the project nor its hidden 'savegame' directory which is already broken due to #6047 if any symlinks occur along user://'s real directory path [I was also using absolute paths to work around #6047 via OS.get_data_dir()]).  Now all means of loading external files are gone!!!

**Steps to reproduce:**
screenshot

**Link to minimal example project** (optional but very welcome):
see _ready() in the screenshot (it's two lines and a sample dir sturcture to test with is shown)
duplicate with:

`sudo mkdir /test`
`sudo ln -s /test /symtest`
`sudo chown me:me /test`
`sudo chown -h me:me /symtest`
(where me is the user you run godot apps with)
`echo -e "extends Node\n\nfunc _ready():\n\tpass\n" >/test/test1.gd`
`cp /test/test1.gd /test/test2.gd`

in Godot:

```
func _ready():
    var a=load("local://test/test1.gd")
    var b=load("local://symtest/test2.gd")
```

### PR DESCRIPTION
**Pull request by Faless**
This PR reverts #6702 and closes #6801 .

It also provide a fix that will prevent an absolute path to be misinterpreted as a resource path (which keeps #3106 and #4280 closed since it should not be misleading anymore).
I tested this with absolute paths on Windows and Linux, all is working on my side.

Regarding the `local://` path, apparently is used inside XML representation for resources saved inside the scene file (eg. CollisionShape2D). So I left it untouched.

Example content of XML scene

```
        <resource type="CircleShape2D" path="local://2">
                <real name="custom_solver_bias"> 0 </real>
                <real name="radius"> 11.5 </real>

        </resource>
```

### CODE REVIEW

File: core/globals.cpp [hunk 1]
```diff
@@ -54,7 +54,7 @@ String Globals::localize_path(const String& p_path) const {
 	if (resource_path=="")
 		return p_path; //not initialied yet
 
-	if (p_path.begins_with("res://") || p_path.begins_with("user://"))
+	if (p_path.begins_with("res://") || p_path.begins_with("user://") || p_path.is_abs_path())
```
Comment (neikeq) [inline core/globals.cpp]: This line causes a regression for me. It makes the `localize_path` return the same absolute path I introduced.
