### PR TITLE
Silence false-positive warning for malformed placement new on GCC 11.1

### LINKED ISSUE #52119: Placement new warnings generated under GCC 11.1
### Godot version

master `6e87d62873`

### System information

Manjaro Linux (kernel 5.13), GCC 11.1

### Issue description

The following warning is generated almost all the time during the build:
```
./core/templates/cowdata.h: In instantiation of 'uint32_t CowData<T>::_copy_on_write() [with T = Face3; uint32_t = unsigned int]':
./core/templates/cowdata.h:276:16:   required from 'Error CowData<T>::resize(int) [with T = Face3]'
./core/templates/vector.h:88:51:   required from 'Error Vector<T>::resize(int) [with T = Face3]'
./core/variant/method_ptrcall.h:410:13:   required from here
./core/templates/cowdata.h:235:30: warning: placement new constructing an object of type 'SafeNumeric<unsigned int>' and size '4' in a region of type 'uint32_t*' {aka 'unsigned int*'} and size '0' [-Wplacement-new=]
  235 |                 new (mem_new - 2) SafeNumeric<uint32_t>(1); //refcount
      |                      ~~~~~~~~^~~
./core/templates/cowdata.h:233:27: note: at offset -8 from 'mem_new' declared here
  233 |                 uint32_t *mem_new = (uint32_t *)Memory::alloc_static(_get_alloc_size(current_size), true);
      |                           ^~~~~~~
```

Not entirely sure it matters, as it is just a warning, but I find this part here suspicious:
>in a region of type 'uint32_t*' {aka 'unsigned int*'} and size '0'

I have bisected this to commit 98ceb60eb4. Will attempt a fix, but I am not entirely sure what the intent of the code in that place is, so I might ask a few things if I am stuck.

### Steps to reproduce

Under latest Manjaro with GCC 11.1, run this in the project root:

`scons platform=linuxbsd target=release_debug use_lto=yes -j4`

### Minimal reproduction project

Not applicable here.

### PR DESCRIPTION
**Pull request by lightspot21**
This closes #52119. Right now I am moving the offset to its own variable in order to calm down GCC's warning. Better ideas always welcome.

### CODE REVIEW

File: core/templates/cowdata.h [hunk 1]
```diff
@@ -231,9 +231,11 @@ uint32_t CowData<T>::_copy_on_write() {
 		uint32_t current_size = *_get_size();
 
 		uint32_t *mem_new = (uint32_t *)Memory::alloc_static(_get_alloc_size(current_size), true);
+		uint32_t *refcount_offset = mem_new - 2;
+		uint32_t *size_offset = mem_new - 1;
```
Comment (nathanfranke) [inline core/templates/cowdata.h:235]: Should these be const references to allow some optimizations?

`uint32_t * const &refcount_offset = mem_new - 2;`

Comment (lightspot21) [reply core/templates/cowdata.h:235]: I see no reason why this can't be the case.

**Comment by lightspot21** [comment]
@godotengine/core ?

**Comment by lightspot21** [comment]
@nathanfranke please let me know if I changed this correctly

**Comment by nathanfranke** [comment]
> @nathanfranke please let me know if I changed this correctly

Yes, looks fine. Although maybe another core contributor can look at it, since I think there are some exceptions or issues that can arise from using references.

**Comment by RandomShaper** [comment]
Considering that the reason for those interim pointers will most likely be no apparent to a future reader of that code, I'd suggest adding a comment about their purpose. However, if we take into account the size of the base patch plus comments and also that the goal is to silence a really broken warning, I'd suggest going with this:

- Around the top of the file:
```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wplacement-new"
```
- Around the bottom of the file:
```
#pragma GCC diagnostic pop
```

Anyone expected to maintain this file will know how to understand it.

**Comment by lightspot21** [comment]
@RandomShaper done

**Review by RandomShaper — APPROVED** [review]

File: core/templates/cowdata.h [hunk 2]
```diff
@@ -49,6 +49,12 @@ class VMap;
 SAFE_NUMERIC_TYPE_PUN_GUARANTEES(uint32_t)
 #endif
 
+// silence a false warning in #52123
+#if defined(__GNUC__) && !defined(__clang__)
```
Comment (akien-mga) [inline core/templates/cowdata.h:53]: Trailing whitespace on this line.

File: core/templates/cowdata.h [hunk 3]
```diff
@@ -49,6 +49,12 @@ class VMap;
 SAFE_NUMERIC_TYPE_PUN_GUARANTEES(uint32_t)
 #endif
 
+// silence a false warning in #52123
```
Comment (akien-mga) [inline core/templates/cowdata.h:52]:
```suggestion
// Silence a false positive warning (see GH-52119).
```

File: core/templates/cowdata.h [hunk 4]
```diff
@@ -379,5 +385,7 @@ template <class T>
 CowData<T>::~CowData() {
 	_unref(_ptr);
 }
-
+#if defined(__GNUC__) && !defined(__clang__)
+#pragma GCC diagnostic pop
+#endif
```
Comment (akien-mga) [inline core/templates/cowdata.h:390]:
```suggestion

#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic pop
#endif

```
Let's keep some whitespace to avoid having unrelated stuff crammed together here.

**Comment by akien-mga** [comment]
Might be worth amending the commit title as we're no longer *fixing* the warning but *silencing* it as a false positive.

File: core/templates/cowdata.h (hunk 3 above)
Comment (lightspot21) [reply core/templates/cowdata.h]: Done!

File: core/templates/cowdata.h (hunk 2 above)
Comment (lightspot21) [reply core/templates/cowdata.h]: Whoops... Should be ok now.

**Comment by lightspot21** [comment]
> Might be worth amending the commit title as we're no longer _fixing_ the warning but _silencing_ it as a false positive.

@akien-mga done and done

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
