### PR TITLE
Fix color pickers closing in editor settings

### LINKED ISSUE #23626: Editor settings color picker and OptionButton close themselves prematurely when the editor theme is regenerated
**Godot version:**

a16d9c6ab68cadb3cff07ef8b7b8c00717e98922

**OS/device including version:**

Linux

**Issue description:**

image

The color picker dialogue under `Editor Settings -> Interface -> Theme` has a habit of closing itself while you're in the middle of trying to decide on a color; the moment the editor updates its color scheme, whether or not you're finished, the dialogue will close on its own, and may close itself again after a short delay when opened a second time.  This self-closing behavior seems to also happen when other editor color settings are modified, such as `Text Editor -> Highlighting`.

Picking a color, picking a hue, sometimes even just clicking in one of the RGBA number fields, can cause the dialogue to close.  Ideally it will stay open until the user clicks outside of the dialogue.

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #23626

### CODE REVIEW

File: editor/editor_settings_dialog.cpp [hunk 1]
```diff
@@ -134,8 +134,6 @@ void EditorSettingsDialog::_notification(int p_what) {
 
 		case EditorSettings::NOTIFICATION_EDITOR_SETTINGS_CHANGED: {
 			_update_icons();
-			// Update theme colors.
-			inspector->update_category_list();
```
Comment (KoBeWi) [inline editor/editor_settings_dialog.cpp:138]: The colors are updated anyways after removing this, so looks like it's ok to remove it. Could someone test?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by KoBeWi** [comment]
No, it depends on #53839
We'd need to backport both PRs.
