### PR TITLE
Fix icons for Embedded / Sub Windows

### LINKED ISSUE #57484: Embedded Windows on Windows 10/11 Don't Have an Icon
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows 11

### Issue description

Screenshot 2022-01-31 165615

### Steps to reproduce

Open any other window (other than the main editor window)

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by TechnicalSoup**
Modify the `create_sub_window` method in the DisplayServer class to set the icon for sub windows to the same icon as the main window. All sub windows will an icon set

Fixes #57484

### CODE REVIEW

**Comment by TechnicalSoup** [comment]
Ok - I'm not 100% sure of the best way to progress this one. Checks are failing on the Linux build where the docs are compared to the class, and if I'm reading the details correctly it's because the added method isn't implemented in the Linux platform DisplayServer code?
I did add in a brief description of the method to the class documentation file.

**Comment by Chaosus** [comment]
@TechnicalSoup You forgot to register the method in `DisplayServer::_bind_method` - like 
	"ClassDB::bind_method(D_METHOD("inherit_icon"), &DisplayServer::inherit_icon);" then it would correctly passing to documentation generation and end-user may use it via GDScript's code.

File: scene/main/window.cpp [hunk 1]
```diff
@@ -254,7 +254,10 @@ void Window::_make_window() {
 #endif
 	DisplayServer::get_singleton()->window_set_title(tr_title, window_id);
 	DisplayServer::get_singleton()->window_attach_instance_id(get_instance_id(), window_id);
-
+	// Inherit the window icon from the main window if the new sub_window is configured with a title bar
+	if (!get_flag(FLAG_BORDERLESS)) {
+		DisplayServer::get_singleton()->inherit_icon(window_id);
+	}
```
Comment (bruvzg) [inline scene/main/window.cpp:260]: I'm not sure exposing `inherit_icon` is useful, just doing it for the all new windows (probably in the `DispalyServerWindows`) should be enough, it's a reasonable default behavior.

And `set_native_icon`/`set_icon` probably should set icon for all windows (or have an optional argument to set individual window icon).

Comment (TechnicalSoup) [reply scene/main/window.cpp:260]: I was originally going to modify the set_icon and set_native_icon methods to take a window_id parameter, but thought that reading the icon handles form the existing parent window (main window) may be quicker/easier than re-parsing the icon input file (either the image or native files).

Happy to go back to that thinking if it's the preferred solution.

**Comment by TechnicalSoup** [comment]
> You've forgot to register the method in `DisplayServer::_bind_method`

Ah yes - of course. Thanks for pointing that one out @Chaosus.

File: scene/main/window.cpp (hunk 1 above)
Comment (TechnicalSoup) [reply scene/main/window.cpp:260]: > I'm not sure exposing `inherit_icon` is useful, just doing it for the all new windows (probably in the `DispalyServerWindows`) should be enough, it's a reasonable default behavior.

The `_create_sub_window` method could be modified to include the read-icon-from-main / write-icon-to-sub-window code in place of the new inherit_icon code. That certainly wraps it up a little neater and doesn't add another method to the public namespace.

File: platform/windows/display_server_windows.cpp [hunk 2]
```diff
@@ -546,6 +546,17 @@ DisplayServer::WindowID DisplayServerWindows::create_sub_window(WindowMode p_mod
 		wd.no_focus = true;
 	}
 
+	// Inherit icons from MAIN_WINDOW for all sub windows that are not borderless
+	if (!wd.borderless) {
```
Comment (bruvzg) [inline platform/windows/display_server_windows.cpp:550]: Are there any issues with setting the icon of a borderless window? If there are, `window_set_flag` should be also modified to set/unset icon when borderless mode is toggled. If not (which is probably the case) just remove this check.

Comment (bruvzg) [inline platform/windows/display_server_windows.cpp:550]: Are there any issues with setting the icon of a borderless window? If there are, `window_set_flag` should be also modified to set/unset icon when borderless mode is toggled. If not (which is probably the case) just remove this check.

Comment (bruvzg) [inline platform/windows/display_server_windows.cpp:550]: Are there any issues with setting the icon of a borderless window? If there are, `window_set_flag` should be also modified to set/unset icon when borderless mode is toggled. If not (which is probably the case) just remove this check.

Comment (TechnicalSoup) [reply platform/windows/display_server_windows.cpp:550]: No, during my initial tests I was just setting an icon for everything and didn't see any problems. I will remove that check.

**Review by bruvzg — APPROVED** [review]

File: platform/windows/display_server_windows.cpp [hunk 3]
```diff
@@ -546,6 +546,15 @@ DisplayServer::WindowID DisplayServerWindows::create_sub_window(WindowMode p_mod
...
 
+	// Inherit icons from MAIN_WINDOW for all sub windows
+	HICON mainwindow_icon = (HICON)SendMessage(windows[MAIN_WINDOW_ID].hWnd, WM_GETICON, ICON_SMALL, 0);
+	if (mainwindow_icon != 0) {
+		SendMessage(windows[window_id].hWnd, WM_SETICON, ICON_SMALL, (LPARAM)mainwindow_icon);
+	}
+	mainwindow_icon = (HICON)SendMessage(windows[MAIN_WINDOW_ID].hWnd, WM_GETICON, ICON_BIG, 0);
+	if (mainwindow_icon != 0) {
+		SendMessage(windows[window_id].hWnd, WM_SETICON, ICON_BIG, (LPARAM)mainwindow_icon);
+	}
```
Comment (akien-mga) [inline platform/windows/display_server_windows.cpp:557]: I assume `!= 0` is a `NULL` pointer check? If so it should use `nullptr`, or simply this:
```suggestion
	// Inherit icons from MAIN_WINDOW for all sub windows.
	HICON mainwindow_icon = (HICON)SendMessage(windows[MAIN_WINDOW_ID].hWnd, WM_GETICON, ICON_SMALL, 0);
	if (mainwindow_icon) {
		SendMessage(windows[window_id].hWnd, WM_SETICON, ICON_SMALL, (LPARAM)mainwindow_icon);
	}
	mainwindow_icon = (HICON)SendMessage(windows[MAIN_WINDOW_ID].hWnd, WM_GETICON, ICON_BIG, 0);
	if (mainwindow_icon) {
		SendMessage(windows[window_id].hWnd, WM_SETICON, ICON_BIG, (LPARAM)mainwindow_icon);
	}
```

**Comment by akien-mga** [comment]
Please squash the commits together once ready: https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase

File: platform/windows/display_server_windows.cpp (hunk 3 above)
Comment (TechnicalSoup) [reply platform/windows/display_server_windows.cpp:557]: Going off the Windows API docs, they indicate that is an icon is unable to be read then a zero value will be returned. Link to the Microsoft docs [here](https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-geticon)

Comment (bruvzg) [reply platform/windows/display_server_windows.cpp:557]: `HICON` (and other WinAPI handles) is typedef for `void *`, but in Windows documentation is not consistent and sometimes use `0`, sometimes `NULL`. `if (mainwindow_icon)` is probably a cleaner way to check it anyway.

**Review by akien-mga — APPROVED** [review]
