### PR TITLE
Editor: Fix some issues with `EditorHelpTooltip`

### LINKED ISSUE #82934: Dictionary key tooltips broken
### Godot version

v4.2.dev.custom_build [691634969]

### System information

Windows 11, Forward+ (applicable to all)

### Issue description

Hovering over a Dictionary's key will now produce an empty box and throw an error (both pictured below). The old method of setting a key tooltip in `editor_properties_array_dict.cpp` via `prop->set_tooltip_text(cs)` is no longer compatable with the new tooltip system

23-10-06 16-36-54 godot windows editor dev x86_64

23-10-06 16-35-39 godot windows editor dev x86_64

### Steps to reproduce

Hover over a dictionary key

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by dalexeev**
* Fixes #82934.

```gdscript
@export_category("class|test")
@export var d: Dictionary = {key = 123}
signal s2(a: Array[int])
```

1. Fix tooltips for dictionary keys.
2. Fix tooltips for categories starting with `class|`.
3. Add BBCode markup escaping for signal parameters.

### CODE REVIEW

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -906,7 +906,14 @@ void EditorProperty::_update_pin_flags() {
...
 
 Control *EditorProperty::make_custom_tooltip(const String &p_text) const {
-	EditorHelpTooltip *tooltip = memnew(EditorHelpTooltip(p_text));
+	EditorHelpBit *tooltip = nullptr;
+	if (has_doc_tooltip) {
+		tooltip = memnew(EditorHelpTooltip(p_text));
+	} else {
+		tooltip = memnew(EditorHelpBit());
+		tooltip->set_text(p_text);
+		tooltip->get_rich_text()->set_custom_minimum_size(Size2(360 * EDSCALE, 0));
```
Comment (YeldhamDev) [inline editor/editor_inspector.cpp:915]: What's the reason to not just return `nullptr`?

Comment (YeldhamDev) [reply editor/editor_inspector.cpp]: I think your new solution is over-engineered, but meh. :man_shrugging:

**Review by YeldhamDev — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
