### PR TITLE
Fix modifying base script exports not propagating to derived scripts

### LINKED ISSUE #82998: Adding/removing base class export does not properly update inspector for inherited scripts
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 27.20.21034.37) - AMD Ryzen 7 5700X 8-Core Processor (16 Threads)

### Issue description

When you have a script inheriting a script, adding or removing exports to/from the base script does not cause the inspector to update, leaving in stale values or not showing new values. Adding or removing exports from/to the inherited script works fine.

<details><summary>Before</summary>

image

</details>

<details><summary>After</summary>

image

</details> 

### Steps to reproduce

Base class

```gdscript
class_name BaseClass
extends Node3D


@export var base_a := 1
@export var base_b := 2
```

Inherited script (attach it to a node)

```gdscript
extends BaseClass


@export var not_inherited := 1234
```

You can trigger the issue by adding or removing exports from/to the base class.

### Minimal reproduction project

[Inheritence.zip](https://github.com/godotengine/godot/files/12840567/Inheritence.zip)

### PR DESCRIPTION
**Pull request by astillich**
Fixes issue #82998 by triggering an update in derived scripts if an export changes on of the base scripts in the hierarchy. Tested over three levels of inheritance with editing the default value and adding / removing exports.

_Bugsquad edit: fixes https://github.com/godotengine/godot/issues/82998_

### CODE REVIEW

**Review by vnen — APPROVED** [review]
LGTM

**Comment by akien-mga** [comment]
Could you update the commit message to match our preferred style? https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind

File: modules/gdscript/gdscript.h [hunk 1]
```diff
@@ -163,13 +163,14 @@ class GDScript : public Script {
 	HashSet<PlaceHolderScriptInstance *> placeholders;
 	//void _update_placeholder(PlaceHolderScriptInstance *p_placeholder);
 	virtual void _placeholder_erased(PlaceHolderScriptInstance *p_placeholder) override;
+	void update_exports_down(bool p_base_exports_changed);
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.h:166]:
```suggestion
	void _update_exports_down(bool p_base_exports_changed);
```
Let's keep the private method style consistent here

Comment (astillich) [reply modules/gdscript/gdscript.h]: Fixed in new commit.

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

I was about to thank you for your _first_ contribution, but then I looked at the history and found your previous one 9 years ago... that's a big one! #1002
