### PR TITLE
Fix settings not appearing for Animation Libraries in the Scene Import window

### LINKED ISSUE #73849: The Advanced Scene Import Dialog doesn't always switch back to a visible tab.
### Godot version

4.0 RC4

### System information

Arch Linux, KDE Plasma Version: 5.27.0, Linux 6.1.12-zen1-1-zen, X11 AMD Ryzen 5 2400G, NVIDIA GeForce GTX 1660

### Issue description

Sometimes, nothing appears on the left side panel of the Advanced Import window when editing AnimationLibrary's. 

### Steps to reproduce

1. Open a regular model.
2. pick a different tab other than the first.
3. Open an Animation Library 

[advancedimportbug.webm](https://user-images.githubusercontent.com/32441086/221053564-c57dc619-d83a-4aca-bcb3-988772a6a8c4.webm)

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by CheesecakeCG**
Fixes https://github.com/godotengine/godot/issues/73849

Before (Video)

After:
After (Video)

### CODE REVIEW

**Comment by Zireael07** [comment]
videos didn't embed correctly

File: editor/import/scene_import_settings.cpp [hunk 1]
```diff
@@ -594,6 +594,9 @@ void SceneImportSettings::open_settings(const String &p_path, bool p_for_animati
 	// Visibility
 	data_mode->set_tab_hidden(1, p_for_animation);
 	data_mode->set_tab_hidden(2, p_for_animation);
+	if (p_for_animation) {
+		data_mode->set_current_tab(0);
+	}
```
Comment (akien-mga) [inline editor/import/scene_import_settings.cpp:599]: I wonder if this should be conditional or should always be done.

WDYT @godotengine/import?

**Review by akien-mga — APPROVED** [review]
My comment can be discussed later, this should be good as is already to fix the bug that you can end up on a hidden tab.

**Comment by akien-mga** [comment]
Thanks!
