### PR TITLE
Fix `Ref<>.is_valid()` for ScriptInstanceExtension

### LINKED ISSUE #78116: ScriptInstanceExtension GDExtensionObjectPtr is no longer readable on Godot Side
### Godot version

v4.1.beta

### System information

Windows 10

### Issue description

```
        virtual Ref<Script> get_script() const override {
                if (native_info->get_script_func) {
                        GDExtensionObjectPtr script = native_info->get_script_func(instance);
                        return Ref<Script>(reinterpret_cast<Script *>(script));
                }
                return Ref<Script>();
```
Is not creating a functional reference.

GDExtensionObjectPtr is a part of gdextension_interface and is a void pointer to pas data pointers between GDExtesion and Godot Core.

In the images below you are able to see that the extension `reinterpret_cast `works fine.
And that the pointer is passed to core.
However at core `Ref<Script> script_test` stays a NULL value

image
image
image

I was hoping this would be solved by solving [cpp 1119](https://github.com/godotengine/godot-cpp/issues/1119)

### Steps to reproduce

Create a custom script instance and create it using `internal::gdextension_interface_script_instance_create` and a `GDExtensionScriptInstanceInfo` that only implements `get_property_list_func` and `get_script_func`.

### Minimal reproduction project

Difficult to create a minimal project.
Mostly looking for advice on what to test to find the actual source problem

### PR DESCRIPTION
**Pull request by Gallilus**
First, check the reference then check the value.

Fix #78116 
caused by #63712
https://github.com/godotengine/godot/pull/63712#discussion_r1233120685

### CODE REVIEW

**Comment by Gallilus** [comment]
I still need to do some functional tests do double-check.

**Comment by AThousandShips** [comment]
If you need time to work more you can convert it to a draft PR, but shouldn't be needed

**Comment by Gallilus** [comment]
It is an improvement! Not jet sure it is a catch-all.

File: core/object/script_language_extension.h [hunk 1]
```diff
@@ -651,7 +651,7 @@ class ScriptInstanceExtension : public ScriptInstance {
 
 #ifdef TOOLS_ENABLED
 			Ref<Script> script = get_script();
-			if (script->is_valid() && pcount > 0) {
+			if (script.is_valid() && script->is_valid() && pcount > 0) {
```
Comment (dsnopek) [inline core/object/script_language_extension.h:654]: Great catch!

The additional `script.is_valid()` definitely seems right to me. I'm not sure about leaving the `script->is_valid()` in there, though. I think this would mean that the class category wouldn't be added if the script has a syntax error (or is invalid for some other reason)? In this case, the script would already have returned more than zero properties, so it stands to reason that it should be able to get the class category too? So, maybe the `&& script->is_valid()` should be removed?

But I'm not very familiar with the details of how `Script` and `ScriptInstance` work.

Comment (akien-mga) [reply core/object/script_language_extension.h:654]: Yeah I'm not an expert either, but it seems to me like `script->get_class_category()` should return a valid result regardless of the valid of the `Script` itself.

The original code in #63712 which was refactored here only used `.is_valid()` checks.

Comment (Gallilus) [reply core/object/script_language_extension.h:654]: Using reference_2b I am able to get the following access error. 
So I will change the PR to `if (script.is_valid() && pcount > 0) {` it seems to work.
Will test it in the next few days during the cleanup of my code.

```
    MyClass my_object = memnew(MyClass);
    Ref<MyClass > reference_1 = *my_object;
    Ref<MyClass > reference_2a = reference_1;
    Ref<MyClass > reference_2b = reference_1.ptr();
    if (refrence_2b.is_valid()){
        // Is reference_2 a or b valid?
        // Will reference.is_valid() && refrence->is_valid() catch this problem?
    }
```

image

**Comment by Gallilus** [comment]
Using reference_2b I am able to get the following access error. 
So I will change the PR to `if (script.is_valid() && pcount > 0) {` it seems to work.
Will test it in the next few days during the cleanup of my code.

```
    MyClass my_object = memnew(MyClass);
    Ref<MyClass > reference_1 = *my_object;
    Ref<MyClass > reference_2a = reference_1;
    Ref<MyClass > reference_2b = reference_1.ptr();
    if (refrence_2b.is_valid()){
        // Is reference_2 a or b valid?
        // Will reference.is_valid() && refrence->is_valid() catch this problem?
    }
```

image

**Review by YuriSizov — APPROVED** [review]
The consensus seems to be that the change is correct, and it looks like that to me as well.

**Comment by YuriSizov** [comment]
Thanks!
