### PR TITLE
Restart game on GL context loss on Android

### LINKED ISSUE #22955: OpenGL context loss is not handled on Android
**Godot version:**
3.0, 3.1

**OS/device including version:**
Many different Android devices, both Mali and Adreno, different generations, different Android versions (from 5.1 to 8.1).

**Issue description:**
When you switch an active app using OpenGL, its OpenGL context may (partially?) be destroyed by the system in low-resource situations. As a result, some textures or other resources are invalidated and are no longer available. We have seen it on our testing devices and have dozens of reports from our players that the game starts looking like this:
eglcontextloss

Godot uses [setPreserveEGLContextOnPause(true)](https://developer.android.com/reference/android/opengl/GLSurfaceView#setPreserveEGLContextOnPause(boolean)) call, but it is not guaranteed to preserve the context - it is just a hint given to the system that we would like to preserve the context, if possible. However, the engine still needs to reload resources in the event of context loss, and Godot does not do this.

This video briefly explains the topic and how the context loss could be detected: https://www.youtube.com/watch?v=NHVtLC5QOpo

**Steps to reproduce:**
There is no 100% way to reproduce this, but this is the most likely way to see the issue:

1. Create a project with a bunch of large images and make a game that loads/displays all of them. The more (graphical) memory the game consumes, the likely this is to reproduce, as it increases the chance that the system will destroy some of the game's resources while it's in background.

2. Open the game on an Android device.

3. Switch to a different app or a number of apps that consume a lot of memory.

4. Switch back to the game.

### PR DESCRIPTION
**Pull request by RandomShaper**
Bonus:
Remove useless old code about reload hooks

Fixes #22955.

@godotengine/android, I believe that having the app instrumented on subsequent launches will not affect performance since no monitors nor any kind of watching is enabled, but I may be wrong.

### CODE REVIEW

File: platform/android/java_glue.cpp [hunk 1]
```diff
@@ -941,12 +942,15 @@ JNIEXPORT void JNICALL Java_org_godotengine_godot_GodotLib_resize(JNIEnv *env, j
...
-
-		os_android->reload_gfx();
+		if (step == 0) {
+			// During startup
+			os_android->set_context_is_16_bits(!p_32_bits);
+		} else {
+			// GL context recreated because it was lost; restart app to let it reload everything
+			os_android->main_loop_end();
+			env->CallVoidMethod(_godot_instance, _restart);
+            step = -1; // Ensure no further steps are attempted
```
Comment (akien-mga) [inline platform/android/java_glue.cpp]: Indentation issue here.

Comment (RandomShaper) [reply platform/android/java_glue.cpp]: Ooops. I'm fixing it in a few hours.

**Comment by akien-mga** [comment]
I pushed a rebase with the style issue fixed.

**Comment by RandomShaper** [comment]
I've had to push again, because I left `setPreserveEGLContextOnPause(false)`.
Good to force context losses, bad for production. 😝

**Comment by akien-mga** [comment]
Thanks!
