### PR TITLE
parser error for static func access non-static variables

### LINKED ISSUE #38408: Wrong use of a variable inside a static function results into class cyclic dependency
**Godot version:**
Godot Engine v3.2.1.stable.official (c) 2007-2020

**OS/device including version:**
Windows 10 (64x)
**Issue description:**
When i use "wrongly" a class member variable inside a static function the compiler ends in a class cyclic dependency.

```
extends Resource
class_name ClassA


var _name:String

func _ready():
	
	pass


static func bugInStaticFunc(name:String):
	# here i used wrongly the varibale '_name' from the classA itself instead the func argument 'name'
	prints("name", _name)
```
I expect error like "ERROR: Using a non static varibale '_x' inside a static function"

```
extends Resource
class_name ClassB


func _ready():
	var a:ClassA = ClassA.new()
```

> Godot Engine v3.2.1.stable.official (c) 2007-2020 Juan Linietsky, Ariel Manzur & Godot Contributors.
> 	 --- GDScript language server started ---
> 	 res://ClassB.gd:6 - Parse Error: The class "ClassA" couldn't be fully loaded (script error or cyclic dependency).
> 	 modules/gdscript/gdscript.cpp:576 - Method failed. Returning: ERR_PARSE_ERROR

**Steps to reproduce:**
See attached Project

**Minimal reproduction project:**
https://drive.google.com/file/d/1L5Lk764fBY7018-4PTDcRJr7WbWS_WoU/view?usp=sharing

### PR DESCRIPTION
**Pull request by ThakeeNathees**
Fix: #38408

**EDIT :**  the error message changed to `Can't access member variable ("_name") from a static function.`

non-static-var-access

### CODE REVIEW

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -7571,6 +7571,10 @@ GDScriptParser::DataType GDScriptParser::_reduce_identifier_type(const DataType
 	}
 
 	if (_get_member_type(base_type, p_identifier, member_type)) {
+		if (current_function && current_function->_static) {
+			_set_error("Can't access non-static variable (\"" + p_identifier.operator String() + "\") from a static function.", p_line);
```
Comment (Calinou) [inline modules/gdscript/gdscript_parser.cpp:7575]: The "non-static" may imply GDScript has static variables, which isn't the case. I'm not sure if the proposed wording is better, but it may be a tad less confusing:

```suggestion
			_set_error("Can't access member variable (\"" + p_identifier.operator String() + "\") from a static function.", p_line);
```

Comment (asheraryam) [reply modules/gdscript/gdscript_parser.cpp]: I agree with @Calinou , "non-static" implies that static variables exist somewhere.

File: modules/gdscript/gdscript_parser.cpp [hunk 2]
```diff
@@ -7571,6 +7571,10 @@ GDScriptParser::DataType GDScriptParser::_reduce_identifier_type(const DataType
 	}
 
 	if (_get_member_type(base_type, p_identifier, member_type)) {
+		if (current_function && current_function->_static) {
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp:7574]: The problem is that this function is also used to find indexed members, so this will be wrong if that's the case. You can check if `p_base_type` is a `nullptr` because them it'll certainly be looking for members of the current class.

**Review by vnen — CHANGES_REQUESTED** [review]

File: modules/gdscript/gdscript_parser.cpp (hunk 2 above)
Comment (ThakeeNathees) [reply modules/gdscript/gdscript_parser.cpp]: done! 👍 
@vnen

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Comment by avencherus** [comment]
After this static functions can longer use constants.  Was this never intended or is it a regression?
