### PR TITLE
Check default project and autoscan directories exist on project manager startup

### LINKED ISSUE #45302: Infinite recursion in project selector when directory fails to open
**Godot version:**
4.0.dev 8ba67b7

**OS/device including version:**
Windows [Version 10.0.19041.746]
NVidia 452.06 RTX 2080 Ti

**Issue description:**
Godot hangs when loading the project list, after deleting or moving the folder specified under `filesystem/directories/autoscan_project_path`

The main issue is that in project_manager.cpp, `void ProjectManager::_scan_dir(const String &path, List<String> *r_projects)` no error checking is performed after the `change_dir` call or the `list_dir_begin` call.

It seems that if change_dir fails, the DirAccess is left at the current working directory, which is my user home directory by default ("C:/Users/MYUSER").

Here is what I gathered by inspecting stack frames manually after the failure.
_scan_begin("C:/Projects/old_autoscan_directory")
_scan_dir("C:/Projects/old_autoscan_directory") -> change_dir fails and iterates through the original working directory, finding "AppData"
_scan_dir("C:/Users/MYUSER/AppData") -> "Local"
_scan_dir("C:/Users/MYUSER/AppData/Local") -> "ElevatedDiagnostics"
_scan_dir("C:/Users/MYUSER/AppData/Local/ElevatedDiagnostics") -> change_dir fails and iterates through the original working directory, finding "AppData"
_scan_dir("C:/Users/MYUSER/AppData") -> "Local"
_scan_dir("C:/Users/MYUSER/AppData/Local") -> "ElevatedDiagnostics"
...and so on

This actually uncovered two problems: one is if the autoscan project path does not exist; and the other is if any directory within the project path is not readable (due to permissions or otherwise), for example the above "ElevatedDiagnostics" directory:
permission dialog showing no permissions other than Administrators and SYSTEM

Here is the full stack trace:

```
ntdll.dll!NtOpenFile()
ntdll.dll!RtlpCreateNewDirectoryReference()
ntdll.dll!RtlSetCurrentDirectory_U()
KernelBase.dll!SetCurrentDirectoryW()
godot.windows.tools.64.exe!DirAccessWindows::change_dir(String p_dir) Line 132
	at S:\repo\godot4\drivers\windows\dir_access_windows.cpp(132)
godot.windows.tools.64.exe!DirAccessWindows::DirAccessWindows() Line 386
	at S:\repo\godot4\drivers\windows\dir_access_windows.cpp(386)
godot.windows.tools.64.exe!DirAccess::_create_builtin<DirAccessWindows>() Line 63
	at S:\repo\godot4\core\os\dir_access.h(63)
godot.windows.tools.64.exe!DirAccess::create(DirAccess::AccessType p_access) Line 246
	at S:\repo\godot4\core\os\dir_access.cpp(246)
godot.windows.tools.64.exe!ProjectManager::_scan_dir(const String & path, List<String,DefaultAllocator> * r_projects) Line 2169
	at S:\repo\godot4\editor\project_manager.cpp(2169)
godot.windows.tools.64.exe!ProjectManager::_scan_dir(const String & path, List<String,DefaultAllocator> * r_projects) Line 2175
	at S:\repo\godot4\editor\project_manager.cpp(2175)
......
godot.windows.tools.64.exe!ProjectManager::_scan_dir(const String & path, List<String,DefaultAllocator> * r_projects) Line 2175
	at S:\repo\godot4\editor\project_manager.cpp(2175)
godot.windows.tools.64.exe!ProjectManager::_scan_dir(const String & path, List<String,DefaultAllocator> * r_projects) Line 2175
	at S:\repo\godot4\editor\project_manager.cpp(2175)
godot.windows.tools.64.exe!ProjectManager::_scan_begin(const String & p_base) Line 2189
	at S:\repo\godot4\editor\project_manager.cpp(2189)
godot.windows.tools.64.exe!ProjectManager::ProjectManager() Line 2695
	at S:\repo\godot4\editor\project_manager.cpp(2695)
godot.windows.tools.64.exe!Main::start() Line 2368
	at S:\repo\godot4\main\main.cpp(2368)
godot.windows.tools.64.exe!widechar_main(int argc, wchar_t * * argv) Line 161
	at S:\repo\godot4\platform\windows\godot_windows.cpp(161)
godot.windows.tools.64.exe!_main() Line 185
	at S:\repo\godot4\platform\windows\godot_windows.cpp(185)
godot.windows.tools.64.exe!main(int argc, char * * argv) Line 199
	at S:\repo\godot4\platform\windows\godot_windows.cpp(199)
[Inline Frame] godot.windows.tools.64.exe!invoke_main() Line 78
	at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(78)
godot.windows.tools.64.exe!__scrt_common_main_seh() Line 288
	at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(288)
kernel32.dll!BaseThreadInitThunk()
ntdll.dll!RtlUserThreadStart()
```

**Steps to reproduce:**
1. Set a folder for your autoscan path.
2. Open Godot's project selector
2. Open a project in that folder.
3. Close godot editor
4. Move the folder you selected as autoscan.
5. Open Godot's project selector **with its working directory set as your user home directory**

**Minimal reproduction project:**
N/A

### PR DESCRIPTION
**Pull request by Kanabenki**
Closes #45302.

A check is also added to ensure `_scan_dir` has a valid directory.

### CODE REVIEW

File: editor/project_manager.cpp [hunk 1]
```diff
@@ -2158,8 +2158,9 @@ void ProjectManager::_run_project() {
 }
 
 void ProjectManager::_scan_dir(const String &path, List<String> *r_projects) {
-	DirAccess *da = DirAccess::create(DirAccess::ACCESS_FILESYSTEM);
-	da->change_dir(path);
+	DirAccessRef da = DirAccess::create(DirAccess::ACCESS_FILESYSTEM);
+	Error error = da->change_dir(path);
+	ERR_FAIL_COND_MSG(error != Error::OK, "Could not scan directory " + path);
```
Comment (akien-mga) [inline editor/project_manager.cpp:2163]: We usually use error code without specifying the enum:
```suggestion
	ERR_FAIL_COND_MSG(error != OK, "Could not scan directory at: " + path);
```

File: editor/project_manager.cpp [hunk 2]
```diff
@@ -2684,8 +2684,26 @@ ProjectManager::ProjectManager() {
...
-	if (EditorSettings::get_singleton()->get("filesystem/directories/autoscan_project_path")) {
-		_scan_begin(EditorSettings::get_singleton()->get("filesystem/directories/autoscan_project_path"));
+	DirAccessRef dir_access = DirAccess::create(DirAccess::AccessType::ACCESS_FILESYSTEM);
+
+	Variant default_project_path = EditorSettings::get_singleton()->get("filesystem/directories/default_project_path");
+	if (!dir_access->dir_exists(default_project_path)) {
+		Error error = dir_access->make_dir_recursive(default_project_path);
+		if (error != Error::OK) {
+			print_error("Could not create default project directory at path " + String(default_project_path));
+		}
```
Comment (akien-mga) [inline editor/project_manager.cpp:2694]:
```suggestion
		if (error != OK) {
			ERR_PRINT("Could not create default project directory at path: " + String(default_project_path));
		}
```

File: editor/project_manager.cpp [hunk 3]
```diff
@@ -2684,8 +2684,26 @@ ProjectManager::ProjectManager() {
...
+
+	Variant autoscan_path = EditorSettings::get_singleton()->get("filesystem/directories/autoscan_project_path");
+	if (autoscan_path) {
+		if (dir_access->dir_exists(autoscan_path)) {
+			_scan_begin(autoscan_path);
+		} else {
+			Error error = dir_access->make_dir_recursive(autoscan_path);
+			if (error != Error::OK) {
+				print_error("Could not create project autoscan directory at path " + String(autoscan_path));
+			}
```
Comment (akien-mga) [inline editor/project_manager.cpp:2705]:
```suggestion
			if (error != OK) {
				ERR_PRINT("Could not create project autoscan directory at path: " + String(autoscan_path));
			}
```

File: editor/project_manager.cpp [hunk 4]
```diff
@@ -2684,8 +2684,26 @@ ProjectManager::ProjectManager() {
 
 	_load_recent_projects();
 
-	if (EditorSettings::get_singleton()->get("filesystem/directories/autoscan_project_path")) {
-		_scan_begin(EditorSettings::get_singleton()->get("filesystem/directories/autoscan_project_path"));
+	DirAccessRef dir_access = DirAccess::create(DirAccess::AccessType::ACCESS_FILESYSTEM);
+
+	Variant default_project_path = EditorSettings::get_singleton()->get("filesystem/directories/default_project_path");
```
Comment (akien-mga) [inline editor/project_manager.cpp:2689]:
```suggestion
	String default_project_path = EditorSettings::get_singleton()->get("filesystem/directories/default_project_path");
```

And then you don't need to cast to `String` further down. Same for autoscan.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
