### PR TITLE
Fix Project Manager `ProjectDialog` install dialog OK button

### LINKED ISSUE #114701: [Web editor] Cannot install projects, "Install" button disabled
### Tested versions

- Reproducible in [4.6.beta3](https://editor.godotengine.org/releases/4.6.beta3/)
- Not reproducible in [4.6.beta2](https://editor.godotengine.org/releases/4.6.beta2/)

Regression starts from #114330 merge

### System information

Godot v4.6.beta (5d9722e83) - macOS Tahoe (26.3.0) - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M3 Max (Apple9) - Apple M3 Max (16 threads) - 48.00 GiB memory

### Issue description

The "Install" button from the Install popup of the Project Manager `ProjectDialog` is disabled for no reason.

Image

From debugging, I found out that `invalid_flags` has `ValidationFlags.INVALID_RENDERER_SELECT` set, which disables the button (even if the project value is valid).

### Steps to reproduce

1. Create a new project.
2. Zip the project.
3. Set "Preload project ZIP" to the created zip.
4. See the install button is disabled.

### Minimal reproduction project (MRP)

[web-editor-super-simple-project.zip](https://github.com/user-attachments/files/24482393/web-editor-super-simple-project.zip)

### PR DESCRIPTION
**Pull request by adamscott**
Fixes #114701

Essentially, the `invalid_flags` was set to `ValidationFlags::INVALID_RENDERER_SELECT` due to failing to initialize properly the flags in the class definition.

This PR fixes this and renames the enum name to something more concrete. It also adds the `ProjectDialog::_update_ok_button()` method in order to simplify code logic.

### CODE REVIEW

File: editor/project_manager/project_dialog.h [hunk 1]
```diff
@@ -64,9 +64,11 @@ class ProjectDialog : public ConfirmationDialog {
 		INSTALL_PATH,
 	};
 
-	enum ValidationFlags {
-		INVALID_PATH_INPUT = 1,
-		INVALID_RENDERER_SELECT = 2
+	enum InvalidStateFlag {
+		INVALID_STATE_FLAG_NONE = 0 << 0,
```
Comment (KoBeWi) [inline editor/project_manager/project_dialog.h]:
```suggestion
		INVALID_STATE_FLAG_NONE = 0,
```

File: editor/project_manager/project_dialog.h [hunk 2]
```diff
@@ -64,9 +64,11 @@ class ProjectDialog : public ConfirmationDialog {
...
+		INVALID_STATE_FLAG_INVALID_PATH_INPUT = 1 << 0,
+		INVALID_STATE_FLAG_INVALID_RENDERER_SELECT = 1 << 1,
+		INVALID_STATE_FLAG_ALL = (INVALID_STATE_FLAG_INVALID_RENDERER_SELECT << 1) - 1,
```
Comment (KoBeWi) [inline editor/project_manager/project_dialog.h]: The ALL flag is unused.

File: editor/project_manager/project_dialog.h [hunk 3]
```diff
@@ -64,9 +64,11 @@ class ProjectDialog : public ConfirmationDialog {
 		INSTALL_PATH,
 	};
 
-	enum ValidationFlags {
-		INVALID_PATH_INPUT = 1,
-		INVALID_RENDERER_SELECT = 2
+	enum InvalidStateFlag {
+		INVALID_STATE_FLAG_NONE = 0 << 0,
+		INVALID_STATE_FLAG_INVALID_PATH_INPUT = 1 << 0,
+		INVALID_STATE_FLAG_INVALID_RENDERER_SELECT = 1 << 1,
```
Comment (KoBeWi) [inline editor/project_manager/project_dialog.h]: It would be better if the names did not include INVALID twice 🙃

**Review by KoBeWi — APPROVED** [review]
The fix is fine, but the enum changes are questionable.

**Review by akien-mga — APPROVED** [review]
