### PR TITLE
Fix slow import when window is unfocused

### LINKED ISSUE #93877: Resource (re)importing speed is affected by editor framerate, leading to slow import speeds when the window is unfocused
### Tested versions

- Reproducible in: 4.3.beta 92c8e87cd

### System information

Godot v4.3.beta (92c8e87cd) - Fedora Linux 40 (KDE Plasma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 550.90.07) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

Resource (re)importing speed is affected by editor framerate, leading to slow import speeds when the window is unfocused. This is particularly the case when importing lots of small resources that import fast individually (as opposed to few large, complex resources). I noticed this while testing https://github.com/godotengine/godot/pull/93727.

This is a frequent problem in various games and apps, to the point where many games disable V-Sync and any built-in FPS limiters during loading screens to speed them up. We can likely do something similar here.

Project exporting may be affected by similar issues as well, but I haven't tested.

*Time includes editor startup + shutdown time. Tests done on a 120 Hz display.*

Mode | Time taken
-|-
Unfocused (10 FPS[^1]) | 12m05s
Default (120 FPS) | 1m09s
Update Continuously (120 FPS) | 1m09s
No V-Sync (145 FPS) | 1m08s
No V-Sync, Update Continuously[^2] | 23s

[^1]: Controlled by the **Unfocused Low Processor Mode Sleep Usec** editor setting. This limit is only effective if **Update Continuously** is unchecked.
[^2]: In this scenario, I average 400 FPS during the import process and 1,700 FPS at idle once importing is done (with no scene open in the editor).

Command used for testing

### Steps to reproduce

- Open the MRP and measure the time taken to import all resources (e.g. using the command line or with a stopwatch).
- Set V-Sync Mode to Disabled and enable Update Continuously in the Editor Settings.
- Exit the editor and remove `.godot/` in the project folder.
- Reopen the editor on the project and measure the time taken again.
  - Your mileage may vary if your OS/graphics driver forces V-Sync on all applications.

### Minimal reproduction project (MRP)

[test_base_mesh.zip](https://github.com/user-attachments/files/16075644/test_base_mesh.zip)

### PR DESCRIPTION
**Pull request by Hilderin**
Fixes #93877

Effectively, the importation speed was dependent on the `VSync` and `Update continuously` settings. That was because there is a lot of progress popup update while importing scenes. Disabling `VSync` and `Update continuously` settings while importing files accelerated the importation process on my computer and I got the same speed now when the editor is focused or not. On my computer, it accelerated the importation of the MRP project from 132 sec. to 88 sec. even when focused.

At the same time, I made a couple of little tweaks in the progress popups to prevent redrawing at each step progress passing `p_force_redraw` to false to `step` method.
There was also a bug in `ProgressDialog` when more then one step was present. If the second task was updated quickly or with `p_force_redraw` at true, the first step was never updated if the first task was using `p_force_redraw` at false. That was because `last_progress_tick` was global and always updated only for the second task. When `task_step` was called for the first task, `last_progress_tick` was always up to date causing it to return and not update the step.

### CODE REVIEW

File: editor/editor_file_system.cpp [hunk 1]
```diff
@@ -2734,11 +2739,14 @@ void EditorFileSystem::reimport_files(const Vector<String> &p_files) {
 			}
 		}
 	}
+	pr.step(TTR("Finalizing importation..."), p_files.size());
```
Comment (akien-mga) [inline editor/editor_file_system.cpp:2742]:
```suggestion
	pr.step(TTR("Finalizing Asset Import..."), p_files.size());
```

Comment (Hilderin) [reply editor/editor_file_system.cpp]: Done!

**Review by KoBeWi — APPROVED** [review]
I didn't really measure any noticeable difference (though I only tested with 10% of the import), but the code looks fine.

But I wonder why does it even depend on framerate. Is it because of `Main::iteration()` call? Maybe there is a way to call it async somehow.

**Comment by Hilderin** [comment]
Yes, I think it's because of `Main::iteration()`. When VSync is enabled, the DisplayServer waits before rendering the frame (I think) and with `low_processor_usage_mode`, `OS::add_frame_delay` adds `low_processor_usage_mode_sleep_usec` each frame.

File: editor/editor_file_system.cpp [hunk 2]
```diff
@@ -2611,6 +2611,11 @@ void EditorFileSystem::reimport_files(const Vector<String> &p_files) {
 
 	EditorProgress pr("reimport", TTR("(Re)Importing Assets"), p_files.size());
 
+	const bool old_low_processor_usage_mode = OS::get_singleton()->is_in_low_processor_usage_mode();
+	const DisplayServer::VSyncMode old_vsync_mode = DisplayServer::get_singleton()->window_get_vsync_mode(DisplayServer::MAIN_WINDOW_ID);
+	OS::get_singleton()->set_low_processor_usage_mode(false);
+	DisplayServer::get_singleton()->window_set_vsync_mode(DisplayServer::VSyncMode::VSYNC_DISABLED);
```
Comment (Calinou) [inline editor/editor_file_system.cpp:2617]: There should be a comment above to explain why this is done, as it's not obvious at first.

File: editor/editor_file_system.cpp [hunk 3]
```diff
@@ -2734,11 +2739,14 @@ void EditorFileSystem::reimport_files(const Vector<String> &p_files) {
...
 		}
 	}
+	pr.step(TTR("Finalizing Asset Import..."), p_files.size());
 
 	ResourceUID::get_singleton()->update_cache(); // After reimporting, update the cache.
 
 	_save_filesystem_cache();
 	_process_update_pending();
+	OS::get_singleton()->set_low_processor_usage_mode(old_low_processor_usage_mode);
+	DisplayServer::get_singleton()->window_set_vsync_mode(old_vsync_mode);
```
Comment (Calinou) [inline editor/editor_file_system.cpp:2749]: Same as above.

Comment (Hilderin) [reply editor/editor_file_system.cpp:2756]: Done!

File: editor/editor_file_system.cpp (hunk 2 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp:2622]: Done!

**Review by Calinou — COMMENTED** [review]
Tested locally, it mostly works as expected.

Reimporting all resources from the MRP linked in https://github.com/godotengine/godot/issues/93877 takes 51 seconds with this PR. I used an optimized editor build for testing, just like in my issue.

The progress dialog clearly redraws very quickly **(photosensitivity warning)**:

https://github.com/godotengine/godot/assets/180032/8e7ab7b2-59b5-4441-bc7d-13d10bbc0a5e

However, it's not quite as fast as with the "optimal" settings listed in https://github.com/godotengine/godot/issues/93877, where I get 12 seconds.

If I set V-Sync mode to Disabled in the Editor Settings with this PR, I get 22 seconds. Enabling Update Continuously has no effect on import times.

I wonder if this has to do with V-Sync only being applied on the main window and not the progress window, or vice-versa.

**Edit:** Even with current `master` and optimal settings, I can't get any lower than 22 seconds (matching this PR with V-Sync disabled in the editor settings). Something else may have caused import speeds to regress between https://github.com/godotengine/godot/commit/92c8e87cd987e8d55d176608c3038e9c4646cb2c and https://github.com/godotengine/godot/commit/b97110cd307e4d78e20bfafe5de6c082194b2cd6 – or in fact, between https://github.com/godotengine/godot/commit/92c8e87cd987e8d55d176608c3038e9c4646cb2c and 4d984b63697d840f2c823608d2c46740fb44651a, since I didn't rebase your PR when testing it.

**Comment by Hilderin** [comment]
Thanks for testing. I'm glad that you are able to get the same performance has the "optional settings".
For the difference in the time for the importation, I took a quick look at all the modifications between https://github.com/godotengine/godot/commit/92c8e87cd987e8d55d176608c3038e9c4646cb2c and https://github.com/godotengine/godot/commit/4d984b63697d840f2c823608d2c46740fb44651a
https://github.com/godotengine/godot/compare/92c8e87..4d984b6

The only think I see that could have affected the importation is that commit which was suppose to optimize the load/saving of scenes: https://github.com/godotengine/godot/commit/b83c64faacd317bd375b90b5f24cfd62cf72d96c (#93723)

I don't known, maybe it reloads all the meshes to load scene groups?!? I could look into it a bit later.

**Comment by Calinou** [comment]
> I don't known, maybe it reloads all the meshes to load scene groups?!? I could look into it a bit later.

After testing 4.3.beta2, 4.3.dev2 and 4.2.2, I can't reproduce my time of 12 seconds with any of their official builds. I'm not sure how I managed to get that time in the first place. If anything, the latest `master` branch is a bit faster than 4.2.2.

**Comment by Hilderin** [comment]
That's a good news!!! I'll not investigate further then. Thanks!

**Comment by akien-mga** [comment]
Needs rebase, then it should be good to merge.

**Comment by Hilderin** [comment]
Rebased done! I retested with the MRP project from the issue. Performance optimization was as expected.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
