### PR TITLE
Inspector `(N changes)` indicator propagates upwards

### LINKED ISSUE #78568: Parent categories doesn't show changes
### Godot version

4.1 beta3

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Normally categories show how many properties are changed (non-default), but it doesn't happen with nested categories:

https://github.com/godotengine/godot/assets/2223172/0ddfc0e8-3298-49ff-892c-25fd61178471

(tested only with Theme Overrides tho)

### Steps to reproduce

1. Add some control node
2. Override some theme property
3. See that Theme Overrides has no "changes" label

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by RedMser**
Fixes #78568

image

Sums up the number of "revertable properties" from all child sections recursively, and shows the same `(N changes)` marker as if it was change directly in the same section. Does not go across sub-resource boundaries for now.

### CODE REVIEW

**Comment by Mickeon** [comment]
I would hold off propagating this through subresources, at least, not at the moment.
Not sure how the PR currently handles the following scenario, but it would be a nuisance when the same Resource (with its default values changed) is reused in multiple parts.
Ideally it should only propagate when the subresource is used once, but that would feel "magical" and inconsistent on the outside.

**Comment by RedMser** [comment]
Added additional logic that skips propagating out of sub-inspectors.

**Comment by RedMser** [comment]
Ah, as it stands it just sums up the number of "revertable properties" from all child sections recursively, and shows the same `(N changes)` marker as if it was change directly in the same section. So yeah, doesn't seem like it closes the proposal.

**Review by Mickeon — APPROVED** [review]
Current PR's behavior is a fairly safe bet for now, should've been like this a long while ago.

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -2616,8 +2616,17 @@ void EditorInspector::_parse_added_editors(VBoxContainer *current_vbox, EditorIn
...
-				ep->connect("property_can_revert_changed", callable_mp(p_section, &EditorInspectorSection::property_can_revert_changed));
+			Node *section_search = p_section;
+			while (section_search) {
+				EditorInspectorSection *section = Object::cast_to<EditorInspectorSection>(section_search);
+				if (section) {
+					ep->connect("property_can_revert_changed", callable_mp(section, &EditorInspectorSection::property_can_revert_changed));
+				}
+				section_search = section_search->get_parent();
+				if (Object::cast_to<EditorInspector>(section_search)) {
+					// Skip sub-resource inspectors for now.
```
Comment (KoBeWi) [inline editor/editor_inspector.cpp:2627]:
```suggestion
					// Skip sub-resource inspectors.
```
If you want to keep the "for now" part, it should be reworded to include TODO or FIXME.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
