### PR TITLE
Fixes deprecated=no compilation option

### LINKED ISSUE #48852: CompatibilityShapeData was not properly scoped so `deprecated=no` does not compile.
**Godot version:**
c3f7465b7efe233eaa8945e41f4029840c1aa153

**OS/device including version:**
win10

**Issue description:**
https://github.com/godotengine/godot/blob/c3f7465b7efe233eaa8945e41f4029840c1aa153/scene/resources/tile_set.h#L68

CompatibilityShapeData was not properly scoped so `deprecated=no` does not compile.

https://github.com/godotengine/godot/blob/c3f7465b7efe233eaa8945e41f4029840c1aa153/scene/resources/tile_set.cpp#L748-L756 

When was compatibility deprecation added? Can we delete the old code?

**Steps to reproduce:**
```
scons platform=windows -j8 bits=64 dev=yes deprecated=no target=debug
```

**Minimal reproduction project:**
See above.

### PR DESCRIPTION
**Pull request by groud**
Should fix https://github.com/godotengine/godot/issues/48852.

### CODE REVIEW

File: scene/2d/tile_map.cpp [hunk 1]
```diff
@@ -777,6 +777,13 @@ void TileMap::_set_tile_data(const Vector<int> &p_data) {
 	int offset = (format >= FORMAT_2) ? 3 : 2;
 
 	clear();
+
+#ifdef DISABLE_DEPRECATED
+	if (format != FORMAT_3) {
+		ERR_FAIL(vformat("Cannot handle deprecated TileMap data format version %d. This Godot version was compiled with no support for deprecated data.", format));
+	}
```
Comment (akien-mga) [inline scene/2d/tile_map.cpp:784]:
```suggestion
	ERR_FAIL_COND_MSG(format != FORMAT_3, vformat("Cannot handle deprecated TileMap data format version %d. This Godot version was compiled with no support for deprecated data.", format));
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
