### PR TITLE
Reimplement scene change

### LINKED ISSUE #70910: Error spam (and/or crash) in release template / exported builds: `"slot >= slot_max" is true. Returning: nullptr`
### Godot version

4.0 beta 10

### System information

Windows 10 

### Issue description

In my rss reader on windows, when the user switches between feed lists - that is, when a VBoxContainer has all its children removed and a new set re-added, the application crashes with:

USER ERROR: Condition "slot >= slot_max" is true. Returning: nullptr
   at: get_instance (./core/object/object.h:974)

This only happens on the windows version and only when that version is built in release mode. In an earlier beta (7 or 10 I am not sure) it was happening occasionally on the linux build too, but that no longer appears to be an issue. I was not able to find any information or other bug reports about this error.

### Steps to reproduce

I have no simple minimal reproduction available, but it is fairly constant in my current project. You can find the source here:
https://gitlab.com/gametheatre/poriferareader/Porifera

1. Build a release windows version of the project
2. Run the exported executable
3. After running the project, subscribe to two or more RSS feeds.
4. If it still has not crashed, switch back and forth between these feeds.

Because this appears to be an issue with the build system it is likely that it will be a major hassle to debug. Let me know if there is any help I can offer.

### Minimal reproduction project

As mentioned above it is consistently reproducible with this (non minimal) project: https://gitlab.com/gametheatre/poriferareader/Porifera

As a temporary workaround, only creating debug builds for windows solves this.

### LINKED ISSUE #78788: VideoStreamPlayer causes random crashes on a Windows export without "Export with Debug"
### Godot version

4.1.beta3, 4.0.3.stable

### System information

Godot v4.1.beta3 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti (NVIDIA; 31.0.15.3598) - Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 Threads)

### Issue description

The game crashes on a Windows export without "Export with Debug" when I use VideoStreamPlayer node as a background in my scene.

I have created 2 simple scenes with VideoStreamPlayer and a button in each to switch between them. When I run the game in the editor, it works fine, when I export it with debug it works fine. As soon as I untick "Export with Debug" the game crashes randomly, sometimes after a few button clicks(changing scenes), sometimes on the first click... The console gives no errors whatsoever...

Tried to do it in both: Godot 4.0.3 and 4.1 beta3, the result is the same. 

I have also recreated this in Godot 3.5.2, the exported game without "Export with Debug" works fine, without crashes at all.

I have spent 4-5 hours yesterday searching internet and trying to fix it, but I couldn't. Tried different ffmpeg builds to convert the video, tried different video framerates, with audio and without audio... Looks like it's a Godot 4 issue.

### Steps to reproduce

1 - create a scene, add VideoStreamPlayer node, assign your video to it.
2 - create another scene with a VideoStreamPlayer node and assign your video to it.
3 - create buttons on each scene to switch between them.
4 - export your project for windows without "Export with Debug"
5 - play the game, after switching the scenes a couple of time, the game will crash.

### Minimal reproduction project

[Crash_Test_3.zip](https://github.com/godotengine/godot/files/11893147/Crash_Test_3.zip)

### PR DESCRIPTION
**Pull request by RandomShaper**
Maybe fixes #78788.
Maybe fixes #70910.

*Bugsquad edit:*
- See #85251 for post-merge discussion on this change and the rationale.

### CODE REVIEW

**Comment by YuriSizov** [comment]
The title says "Avoid too early removal of current scene", but you've moved it to an even earlier point, kinda 🤔 I don't think `queue_free`ing it would be sufficient. I think we also need to unparent the node first, so we stop processing.

**Comment by RandomShaper** [comment]
I've changed the PR to a new approach.

File: scene/main/scene_tree.cpp [hunk 1]
```diff
@@ -1417,7 +1410,22 @@ Error SceneTree::change_scene_to_packed(const Ref<PackedScene> &p_scene) {
 	Node *new_scene = p_scene->instantiate();
 	ERR_FAIL_NULL_V(new_scene, ERR_CANT_CREATE);
 
-	call_deferred(SNAME("_change_scene"), new_scene);
+	// If called again while a change is pending.
+	if (pending_new_scene) {
```
Comment (YuriSizov) [inline scene/main/scene_tree.cpp:1414]: Could probably check if it's the same scene being set and just return and do nothing.

Comment (YuriSizov) [reply scene/main/scene_tree.cpp:1414]: Or I guess we can't, since it's going to be a new instance? Well nevermind then.

Comment (RandomShaper) [reply scene/main/scene_tree.cpp:1414]: This function instantiates the scene `Node` itself. It will always be a different one. An option would be to remember the last `p_scene` argument and in `change_scene_to_file()` remember the `p_path` argument, but that's a bit cumbersome.

**Comment by RandomShaper** [comment]
This one would be good for 4.2 dev builds.

**Review by YuriSizov — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Given the changes in behavior, we shouldn't cherry-pick this.
