### PR TITLE
Fix `TabContainer` regressions related to switching tabs in certain cases

### LINKED ISSUE #91135: Setting current_tab of a tab container doesn't work when it's not visible or not ready
### Tested versions

- Reproducible in: 4.3.dev5
- Not reproducible in: 4.2.1

### System information

Godot v4.3.dev5 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 SUPER (NVIDIA; 31.0.15.3118) - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 Threads)

### Issue description

This issue is two-fold (I don't know if I should make separate issues as they seem related):
- Setting `current_tab` from script doesn't work when the tab container is not ready. (It works previously) For example, when setting the `current_tab` from an "uncle" node's `_ready()` that is higher up in the tree than the parent node.
- Setting `current_tab` from script doesn't work in a nested tab container where the target container was not visible, when performed from a button click. `select_next_available()` doesn't seem to work either.

I noticed this behavior because my project which was working in Godot 4.2.1 no longer works properly in Godot 4.3.dev5 in regards to tab containers.

Setting the current tab in the editor does always seem to work on the other hand.

### Current "workaround"
Instead of setting `current_tab`, setting the tab control's visibility directly seems to work reliably.

### Reproduction 1 (not ready)
- Create 2 sibling nodes, the ordering is important. Attach script to the 1st node, and add a tab container with 2 distinct tabs to the 2nd node. Set the current tab to 0 in the editor inspector.
- In the 1st node's script's `_ready()` function, set the tab container's `current_tab` to 1. It does *not* work, presumably because the tab container is not ready.
- In the scene's root node, attach a script and set the tab container's `current_tab` to 1 in its `_ready()` function. It *does work*, presumably because the children are ready, including the tab container.

### Reproduction 2 (not visible)
- Create a nested tab container structure with 1 parent tab container and 2 child tab containers as its tabs. Then add 2 distinct tabs each to the child tab containers. Set the current tab of all tab containers to 0 in the editor inspector.
- Add a button to the scene's root node. Attach a script in the scene's root node and connect the button's `pressed()` signal. In the `_on_button_pressed()` function, set the top tab container's `current_tab` to 1 then set the 2nd child tab container's `current_tab` to 1 in the next line.
- Run the project, click the button once. The top tab container `current_tab` will change successfully, however the 2nd child's `current_tab` will fail to change, presumably due to it being previously/currently invisible. Click the button again, now it works because the 2nd child is now visible.

### Minimal reproduction project (MRP)

This project contains both reproduction method in separate scenes. Open the scene and run them individually.
- `not_ready_reproduction.tscn` for the "not ready" issue reproduction
- `not_visible_reproduction.tscn` for the "not visible" issue reproduction

[godot4.3.dev5_tab_container_test.zip](https://github.com/godotengine/godot/files/15103844/godot4.3.dev5_tab_container_test.zip)

### PR DESCRIPTION
**Pull request by YeldhamDev**
Fixes #91135.

- Fix regression caused by #83893, where setting the current tab right after entering the tree would make the value be reset to 0.

- The other one is bit more complicated (caused by #87194). It happens because the tab visibility change is also triggered if it becomes visible in the tree (even if it was already set to `visible`), ~and I'm not sure how to fix this without some ugly hackiness.~ Alright, did the cleanest attempt I could, suggestions are welcomed.

Thanks to @jsjtxietian for pointing me in the right direction and saving me time.

### CODE REVIEW

File: scene/gui/tab_container.cpp [hunk 1]
```diff
@@ -611,6 +611,11 @@ void TabContainer::set_current_tab(int p_current) {
 		setup_current_tab = p_current;
 		return;
 	}
+	// Discard setup if the current tab was changed right after entering the tree.
+	if (setup_current_tab > -2) {
+		setup_current_tab = -2;
+	}
+
```
Comment (jsjtxietian) [inline scene/gui/tab_container.cpp:618]: I did some test : move `set_current_tab(setup_current_tab)` from `NOTIFICATION_POST_ENTER_TREE` to `NOTIFICATION_ENTER_TREE` also fix this bug, not sure why it has to be `NOTIFICATION_POST_ENTER_TREE`

**Comment by KoBeWi** [comment]
> partially fixes https://github.com/godotengine/godot/issues/91135

You should unlink the issue then. I tested and the visibility problem is not fixed.

**Comment by kitbdev** [comment]
We could make the tab visibility callback only apply in the editor when it is part of the edited scene, since that is where it is most intended for.

**Comment by YeldhamDev** [comment]
> You should unlink the issue then. I tested and the visibility problem is not fixed.

Wait, I just forgot to update the PR's description, because both issues are fixed on my end. What happens in the visibility test scene on your end?

**Comment by KoBeWi** [comment]
Nevermind, I didn't test properly.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
