### PR TITLE
Fix GPUParticles3D emitting `finished` signal on ready

### LINKED ISSUE #101733: As of 4.4 Beta 1, one-shot particle system behavior is altered
### Tested versions

I've loaded my project which was last working in 4.4 Dev 6 into 4.4 Beta 1, where the issue occurs.

### System information

Godot v4.4.beta1 - Windows 11 (build 22631) - Multi-window, 2 monitors - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4060 Laptop GPU (NVIDIA; 32.0.15.6081) - 13th Gen Intel(R) Core(TM) i7-13650HX (20 threads)

### Issue description

Particle systems with the "Oneshot" setting, which are spawned into the scene with "Emitting = false" and gdscript enables the emitting flag, no longer play the full sequence. Disabling oneshot allows the full sequence to play.

### Steps to reproduce

Open the attached test project and run it. You'll see the particle system only appears for a single frame before being freed. This is because the emitting property is being set to "false" elsewhere outside the script (the test project only has 1 script).

In previous versions, the one-shot animation would run to completion, then emitting would be set to false (presumably by code within the particle system itself).

### Minimal reproduction project (MRP)

[reproduce-oneshot-bug.zip](https://github.com/user-attachments/files/18462604/reproduce-oneshot-bug.zip)

### LINKED ISSUE #101975: Child Scene nodes disappearing from loaded/instantiated PackedScenes
### Tested versions

- not reproducible 4.3 stable
- reproducible 4.4 beta 1

### System information

MacOS 15.2 Godot4.4 Beta 1

### Issue description

Child scene nodes disappearing after loading of a packed scene.

[Example Repo](https://github.com/mrmikemon/scenetest4_4beta1.git)

### Steps to reproduce

[Example Repo](https://github.com/mrmikemon/scenetest4_4beta1.git)

Test code
1. Finds a place holder node in main scene
2. Removes the placehodler node 'LoadedLevel'
3. Loads a packed scene from resoure and instanciate
4. Rename the scene as 'LoadedLevel'

Image
Snapshot of tree just after load

Image

Snapshot once main scene displayed

Test result
Level loads correctly
All child node instanciate
All child scenes 'BaseStation' child scenes are removed from scene only leaving simple nodes

Verified using RemoteDebug view of node treee.

### Minimal reproduction project (MRP)

[Example Repo](https://github.com/mrmikemon/scenetest4_4beta1.git)

### PR DESCRIPTION
**Pull request by TCROC**
Fixes a bug introduced by PR: https://github.com/godotengine/godot/pull/92089
Fixes: https://github.com/godotengine/godot/pull/101596
Fixes: #101733
Fixes #101975

The bug being that all gpu_particle_3ds emit the ``finished`` signal on ``ready``.

Discussion in rocket chat can be found here: https://chat.godotengine.org/channel/vfx-tech-art/thread/WhhDnzLmTke5vYHF9

Details are as follows.

@QbieShay 's pr changes this method:

```cpp
void GPUParticles3D::set_one_shot(bool p_one_shot) {
	one_shot = p_one_shot;
	RS::get_singleton()->particles_set_one_shot(particles, one_shot);

	if (is_emitting()) {
		if (!one_shot) {
			RenderingServer::get_singleton()->particles_restart(particles);
		}
	}
}
```

To

```cpp
void GPUParticles3D::set_one_shot(bool p_one_shot) {
	one_shot = p_one_shot;
	RS::get_singleton()->particles_set_one_shot(particles, one_shot);

	if (is_emitting()) {
		if (!one_shot) {
			restart();
		}
	}
}
```

Specifically the part ``RenderingServer::get_singleton()->particles_restart(particles);`` being changed to ``restart();`` is what introduces this bug.  If we inspect the ``restart`` method, we see that some fields get set:

```cpp
void GPUParticles3D::restart(bool p_keep_seed) {
	if (!p_keep_seed && !use_fixed_seed) {
		set_seed(Math::rand());
	}
	RenderingServer::get_singleton()->particles_restart(particles);
	RenderingServer::get_singleton()->particles_set_emitting(particles, true);

	emitting = true;
	active = true;
	signal_canceled = false;
	time = 0;
	emission_time = lifetime * (1 - explosiveness_ratio);
	active_time = lifetime * (2 - explosiveness_ratio);
	set_process_internal(true);
}
```

These fields are then evaluated in ``void GPUParticles3D::_notification`` here:

```cpp
if (time > active_time) {
	if (active && !signal_canceled) {
		emit_signal(SceneStringName(finished));
	}
	active = false;
	if (!emitting) {
		set_process_internal(false);
	}
}
```

But you still may be wondering, who calls the ``set_one_shot`` method?  That gets called by the constructor as can be seen by my debugger:

image

In summary, the issue is:

constructor calls ``set_one_shot`` -> calls ``restart`` -> sets fields incorrectly indicating particle system started -> ``GPUParticles3D::_notification`` sees that the particle system isn't running but incorrectly thinks it was started so it incorrectly emits the ``finished`` signal.

By reverting ``void GPUParticles3D::set_one_shot`` it goes back to behaving how it was before.  To be thorough, I checked GPUParticles2D and can confirm this is how it is currently implemented over there so there is no bug with GPUParticle2D.

Thank you for the help debugging this @QbieShay! :heart:

### CODE REVIEW

**Review by QbieShay — APPROVED** [review]

**Review by clayjohn — COMMENTED** [review]
This is going to need to update the seed still otherwise the one shot particle will look the exact same every time which is a change in behaviour

**Comment by TCROC** [comment]
> This is going to need to update the seed still otherwise the one shot particle will look the exact same every time which is a change in behaviour

Makes sense.  I'll go update it to update the seed

**Comment by TCROC** [comment]
@clayjohn It has been done 😎

**Comment by QbieShay** [comment]
@clayjohn i'm not sure it's necessaary, this happens in the setter of oneshot and not on reset

**Comment by TCROC** [comment]
Whatever the Godot powers that be command of me, I shall do 😎

**Comment by TCROC** [comment]
I do agree with @QbieShay though. I personally don't care that much about it one way or the other. Yes doing this introduces (imo) an unnecessary call to randomize the seed since this is just a setter. But I don't call set_one_shot often (never actually in my case) to care one way or the other. So I didn't bother bringing it up as I'd rather the PR just go through. But if I am to offer some input, I do agree with @QbieShay that randomizing the seed should be left to the restart method rather than this setter. In most cases, doing it here will be redundant.

**Comment by TCROC** [comment]
So I guess with that said, @clayjohn do you like it as it is (your suggestion) or would you like me to go back to the way the pr was (@QbieShay and my suggestion).

**Comment by QbieShay** [comment]
Clay and I discussed in chat https://chat.godotengine.org/channel/rendering?msg=Mgd4xD8bH3TZKrQND

The outocme is that it should be reverted to what it was before, and the seed logic shoudl be added. The same thing should be done with GPUParticles2D. I hadn't seen it when i did the PR, but they should behave the same.

**Comment by TCROC** [comment]
> Clay and I discussed in chat https://chat.godotengine.org/channel/rendering?msg=Mgd4xD8bH3TZKrQND
> 
> The outocme is that it should be reverted to what it was before, and the seed logic shoudl be added. The same thing should be done with GPUParticles2D. I hadn't seen it when i did the PR, but they should behave the same.

I responded in that chat.  I'm looking at the old source code and I believe @clayjohn may be mistaken.  It does not look like this method ever set the seed when set_one_shot was called.  Pushing the PR through as it currently is would **actually** be changing the behavior compared to how it behaves in 4.3.

**Comment by TCROC** [comment]
@clayjohn is indeed correct!  Previously the seed would get randomized when ``set_one_shot`` was called but in a very indirect way.  I am very impressed that @clayjohn was able to keep that entire logic train in his head!

It went (in rough pseudocode) renderingserver::restart_particles -> particles request restart -> particles clear -> randomize

^ And that wasn't a direct callstack either.  That was booleans being set and then actions being taken in multiple different methods.  Wow I am impressed with @clayjohn knowning that about code he wrote _checks git blame_ 2 years ago! 👀👀👀

Impressive review clay!  Very impressive! 👏

**Comment by TCROC** [comment]
But in short, I have no concerns.  The PR should go through as it currently is :)

**Comment by clayjohn** [comment]
> I am very impressed that @clayjohn was able to keep that entire logic train in his head!

You give me way too much credit. I followed the chain of calls yesterday while reviewing this PR! I definitely didn't remember all the logic from before

**Comment by TCROC** [comment]
> > I am very impressed that @clayjohn was able to keep that entire logic train in his head!
> 
> You give me way too much credit. I followed the chain of calls yesterday while reviewing this PR! I definitely didn't remember all the logic from before

Lol the fact that you looked at a one line change and successfully followed the chain of logic from the previous PR is still impressive.  I would never have thought to look for such detailed side effects.

**Comment by TCROC** [comment]
I mean post this PR me knows to.  But pre this PR me did not 😅

**Comment by TCROC** [comment]
> Clay and I discussed in chat https://chat.godotengine.org/channel/rendering?msg=Mgd4xD8bH3TZKrQND
> 
> 
> 
> The outocme is that it should be reverted to what it was before, and the seed logic shoudl be added. The same thing should be done with GPUParticles2D. I hadn't seen it when i did the PR, but they should behave the same.

Also yes, I'll put in a PR fixing the 2d particles tomorrow.

**Review by clayjohn — APPROVED** [review]

File: scene/3d/gpu_particles_3d.cpp [hunk 1]
```diff
@@ -92,7 +92,11 @@ void GPUParticles3D::set_one_shot(bool p_one_shot) {
 
 	if (is_emitting()) {
 		if (!one_shot) {
-			restart();
+			if (!use_fixed_seed) {
+				set_seed(Math::rand());
```
Comment (clayjohn) [inline scene/3d/gpu_particles_3d.cpp:96]: I just realized, we may not want to use `set_seed` here as it will change the value that gets saved if `seed` is serialized. 

We probably just want to call the renderingserver function directly

Comment (TCROC) [reply scene/3d/gpu_particles_3d.cpp:96]: Hey @clayjohn i see you approved and left a review. Maybe it's just a bug on my end but it says you still approve. Do you want me to make these changes you suggested?

Comment (TCROC) [reply scene/3d/gpu_particles_3d.cpp:96]: Got back to my PC this morning.  I'll go update this as well :)

Comment (TCROC) [reply scene/3d/gpu_particles_3d.cpp:96]: Examining the code, I'm actually not sure about this change.  I see there is a public ``get_seed`` function.  So if I were to call ``RS::get_singleton()->particles_set_seed`` without also calling ``seed = p_seed;``, this would make ``gpu_particles_3d.cpp`` out of sync with the rendering server.  The ``get_seed`` function would no longer correctly reflect the value that has been set on the rendering server.  What are your thoughts on this?  @QbieShay Do you have some input as well?

**Comment by Repiteo** [comment]
Thanks!

File: scene/3d/gpu_particles_3d.cpp (hunk 1 above)
Comment (Repiteo) [reply scene/3d/gpu_particles_3d.cpp:96]: We'll send it as-is; it'll be easy to apply a fix if this does cause a desync.

**Comment by kleonc** [comment]
> Fixes: #101596

@clayjohn You've added this line but it links to this PR. :upside_down_face: So whatever it was supposed to link to might still be not closed.
