### PR TITLE
Fix goto line issues in code editor

### LINKED ISSUE #70438: Selecting methods in script editor methods list does not position them consistently when scrolling, if Word Wrap option is enabled.
### Godot version

v3.5.2.rc1.official [f5f0543ae]

### System information

w10 64

### Issue description

You can see it in the video.
I select a function and the editor places it at the bottom of the screen, other times it places it at the top, and other times it places it in the center.

https://youtu.be/4yqvRaNwZes

### Steps to reproduce
Thanks to user Tetane we know that the problem happens when:
The setting "text_editor/appearance/word_wrap" is set to true.
See the video.

### Minimal reproduction project

...

### PR DESCRIPTION
**Pull request by kitbdev**
- Fixes https://github.com/godotengine/godot/issues/70438
- Fixes not unselecting when going to error. For both the label and the line number in the expanded panel.
- Fixes not centering when going to the error from the error panel.
- Fixes Find in Files not selecting results. (only use of `goto_line_selection`)
- Fixes clicking on a warning in shader editor not deselecting or unfolding.
- Fixes caret column clamping instead of being set to column 0 when using go to function, going to symbol, clicking on breakpoint from debugger tab, etc (`goto_line`).

I did not change the goto line popup since I have another PR about that https://github.com/godotengine/godot/pull/91388.
Removed the `p_with_error` argument since it isn't used. There are some other uses of `goto_line` that could use the new column argument, but I'll leave that for another PR.

### CODE REVIEW

File: editor/plugins/script_editor_plugin.cpp [hunk 1]
```diff
@@ -1861,13 +1861,11 @@ void ScriptEditor::_members_overview_selected(int p_idx) {
...
 		return;
 	}
-	// Go to the member's line and reset the cursor column. We can't change scroll_position
-	// directly until we have gone to the line first, since code might be folded.
-	se->goto_line(members_overview->get_item_metadata(p_idx));
-	Dictionary state = se->get_edit_state();
-	state["column"] = 0;
-	state["scroll_position"] = members_overview->get_item_metadata(p_idx);
-	se->set_edit_state(state);
+	CodeTextEditor *cte = se->get_code_editor();
```
Comment (Paulb23) [inline editor/plugins/script_editor_plugin.cpp:1864]: Can't say I like the idea of the `ScriptEditorPlugin` interacting with the code editor directly, would prefer changing the API (combine them with a new arg?) or as above cast to the specific type.

**Review by Paulb23 — COMMENTED** [review]
Overall looks good, one small note inline.

**Comment by kitbdev** [comment]
Updated to use a cast as elsewhere in this file.

**Review by Paulb23 — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
