### PR TITLE
Fix AnimationPlayer `blend_times` sorting

### LINKED ISSUE #76491: Transition / blend times in AnimationPlayer are reordered upon saving
### Godot version

v4.0.1.stable.official [cacf49999]

### System information

Kubuntu 23.04

### Issue description

When setting up an `AnimationPlayer` with several animations, it is possible to hit the "Animation" button to the left of the animation name / dropdown box and click "Edit Transitions..." which will let you create a blend time between the animations. The blend times of these animations are then stored in the tscn file like so:

```
blend_times = [&"RESET", &"RESET", 0.8, &"RESET", &"anim1", 0.8, &"RESET", &"anim3", 0.8, &"RESET", &"anim2", 0.8, &"anim1", &"RESET", 0.8, &"anim1", &"anim1", 0.8, &"anim1", &"anim3", 0.8, &"anim1", &"anim2", 0.8, &"anim3", &"RESET", 0.8, &"anim3", &"anim1", 0.8, &"anim3", &"anim3", 0.8, &"anim3", &"anim2", 0.8, &"anim2", &"RESET", 0.8, &"anim2", &"anim1", 0.8, &"anim2", &"anim3", 0.8, &"anim2", &"anim2", 0.8]
```

If an unrelated change is then made to the scene (for example, adding another child node), after saving, the blend times are then regenerated. Although the blend times remain correct, the order in the file is changed, which results in version control noise every time the file is saved.

An example of this can be seen on line 85 of the following diff: https://github.com/RobTheFiveNine/godot-animation-blend-reorder-bug/commit/3ab62ba1976381fa2b20247a0cb04a9b55bd54a5#diff-d3989be7149720fdbe62886f9bcc0644e7012d3c8b3f239c3d618e0760c307d0R85

```diff
index 2cffb18..e2771b9 100644
--- a/node_3d.tscn
+++ b/node_3d.tscn
@@ -2,9 +2,8 @@
 
 [sub_resource type="BoxMesh" id="BoxMesh_6clns"]
 
-[sub_resource type="Animation" id="Animation_mi6jd"]
-resource_name = "anim1"
-length = 3.0
+[sub_resource type="Animation" id="Animation_d1xbe"]
+length = 0.001
 tracks/0/type = "value"
 tracks/0/imported = false
 tracks/0/enabled = true
@@ -12,14 +11,15 @@ tracks/0/path = NodePath("CSGMesh3D:rotation")
 tracks/0/interp = 1
 tracks/0/loop_wrap = true
 tracks/0/keys = {
-"times": PackedFloat32Array(0, 1.5, 3),
-"transitions": PackedFloat32Array(1, 1, 1),
+"times": PackedFloat32Array(0),
+"transitions": PackedFloat32Array(1),
 "update": 0,
-"values": [Vector3(0, 0, 0), Vector3(3.14159, 0, 0), Vector3(0, 0, 0)]
+"values": [Vector3(0, 0, 0)]
 }
 
-[sub_resource type="Animation" id="Animation_d1xbe"]
-length = 0.001
+[sub_resource type="Animation" id="Animation_mi6jd"]
+resource_name = "anim1"
+length = 3.0
 tracks/0/type = "value"
 tracks/0/imported = false
 tracks/0/enabled = true
@@ -27,10 +27,10 @@ tracks/0/path = NodePath("CSGMesh3D:rotation")
 tracks/0/interp = 1
 tracks/0/loop_wrap = true
 tracks/0/keys = {
-"times": PackedFloat32Array(0),
-"transitions": PackedFloat32Array(1),
+"times": PackedFloat32Array(0, 1.5, 3),
+"transitions": PackedFloat32Array(1, 1, 1),
 "update": 0,
-"values": [Vector3(0, 0, 0)]
+"values": [Vector3(0, 0, 0), Vector3(3.14159, 0, 0), Vector3(0, 0, 0)]
 }
 
 [sub_resource type="Animation" id="Animation_2woje"]
@@ -82,4 +82,7 @@ mesh = SubResource("BoxMesh_6clns")
 libraries = {
 "": SubResource("AnimationLibrary_0p174")
 }
-blend_times = [&"RESET", &"RESET", 0.8, &"RESET", &"anim1", 0.8, &"RESET", &"anim3", 0.8, &"RESET", &"anim2", 0.8, &"anim1", &"RESET", 0.8, &"anim1", &"anim1", 0.8, &"anim1", &"anim3", 0.8, &"anim1", &"anim2", 0.8, &"anim3", &"RESET", 0.8, &"anim3", &"anim1", 0.8, &"anim3", &"anim3", 0.8, &"anim3", &"anim2", 0.8, &"anim2", &"RESET", 0.8, &"anim2", &"anim1", 0.8, &"anim2", &"anim3", 0.8, &"anim2", &"anim2", 0.8]
+blend_times = [&"RESET", &"RESET", 0.8, &"RESET", &"anim3", 0.8, &"RESET", &"anim2", 0.8, &"RESET", &"anim1", 0.8, &"anim3", &"RESET", 0.8, &"anim3", &"anim3", 0.8, &"anim3", &"anim2", 0.8, &"anim3", &"anim1", 0.8, &"anim2", &"RESET", 0.8, &"anim2", &"anim3", 0.8, &"anim2", &"anim2", 0.8, &"anim2", &"anim1", 0.8, &"anim1", &"RESET", 0.8, &"anim1", &"anim3", 0.8, &"anim1", &"anim2", 0.8, &"anim1", &"anim1", 0.8]
+
+[node name="Node3D" type="Node3D" parent="."]
+transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 1.54048, 0, 0)
```

The only change made in this sample project was to add a `Node3D` child object to the root node, but the order of the blend times changes and makes the version control flag more changes.

The same issue can also be triggered by simply hitting CTRL+S on an unchanged scene, doing this can result in the `blend_times` property being changed, as can be seen in this commit: https://github.com/RobTheFiveNine/godot-animation-blend-reorder-bug/commit/806b2b45c6104c511cbc348098c33cf8db0051ac

```diff
index e2771b9..6e4fd74 100644
--- a/node_3d.tscn
+++ b/node_3d.tscn
@@ -82,7 +82,7 @@ mesh = SubResource("BoxMesh_6clns")
 libraries = {
 "": SubResource("AnimationLibrary_0p174")
 }
-blend_times = [&"RESET", &"RESET", 0.8, &"RESET", &"anim3", 0.8, &"RESET", &"anim2", 0.8, &"RESET", &"anim1", 0.8, &"anim3", &"RESET", 0.8, &"anim3", &"anim3", 0.8, &"anim3", &"anim2", 0.8, &"anim3", &"anim1", 0.8, &"anim2", &"RESET", 0.8, &"anim2", &"anim3", 0.8, &"anim2", &"anim2", 0.8, &"anim2", &"anim1", 0.8, &"anim1", &"RESET", 0.8, &"anim1", &"anim3", 0.8, &"anim1", &"anim2", 0.8, &"anim1", &"anim1", 0.8]
+blend_times = [&"RESET", &"RESET", 0.8, &"RESET", &"anim2", 0.8, &"RESET", &"anim1", 0.8, &"RESET", &"anim3", 0.8, &"anim2", &"RESET", 0.8, &"anim2", &"anim2", 0.8, &"anim2", &"anim1", 0.8, &"anim2", &"anim3", 0.8, &"anim1", &"RESET", 0.8, &"anim1", &"anim2", 0.8, &"anim1", &"anim1", 0.8, &"anim1", &"anim3", 0.8, &"anim3", &"RESET", 0.8, &"anim3", &"anim2", 0.8, &"anim3", &"anim1", 0.8, &"anim3", &"anim3", 0.8]
 
 [node name="Node3D" type="Node3D" parent="."]
 transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 1.54048, 0, 0)
```

### Steps to reproduce

1. Create a new project and add an `AnimationPlayer` which has several animations
2. Setup blend times on each animation
3. Commit the project to a version control repo
4. Press CTRL + S on the unchanged scene or add a new node to it and check the diff in the repository (sometimes it may take a few attempts as it seems to sporadically use a different order when saving the blend times)

### Minimal reproduction project

https://github.com/RobTheFiveNine/godot-animation-blend-reorder-bug

### PR DESCRIPTION
**Pull request by JacobMillner**
Fixes #76491 

The current operator< for `BlendKeys` compares to/from pointers resulting in nondeterministic behavior. You can see this represented in the `.tscn` file of anything with lots of `blend_times` resulting in file changes which leads to extra noise in your git commits.

This PR uses`StringName::AlphaCompare` when making to/from comparisons in order preform a lexicographic order sort rather than one determined by memory location.

### CODE REVIEW

File: scene/animation/animation_player.h [hunk 1]
```diff
@@ -94,10 +94,10 @@ class AnimationPlayer : public AnimationMixer {
 			return from == bk.from && to == bk.to;
 		}
 		bool operator<(const BlendKey &bk) const {
-			if (from == bk.from) {
-				return to < bk.to;
+			if (String(from) == String(bk.from)) {
```
Comment (AThousandShips) [inline scene/animation/animation_player.h:97]: Why this? There's no reason to compare them as strings, that's significantly slower

Comment (JacobMillner) [reply scene/animation/animation_player.h:97]: Good point and thanks for the review, I will change this back to `if (from == bk.from)`. Testing it locally seems to work fine and not result in sort variations.

Do you know if comparing two `StringName`s  that have the same string literal will always point to the same mem address?

Comment (AThousandShips) [reply scene/animation/animation_player.h]: You should just use `StringName::AlphCompare` here, like so:
```cpp
return StringName::AlphCompare()(from, bk.from) < 0;
```

File: scene/animation/animation_player.h [hunk 2]
```diff
@@ -95,9 +95,9 @@ class AnimationPlayer : public AnimationMixer {
 		}
 		bool operator<(const BlendKey &bk) const {
 			if (from == bk.from) {
-				return to < bk.to;
+				return String(to) < String(bk.to);
```
Comment (AThousandShips) [inline scene/animation/animation_player.h:98]:
```suggestion
				return StringName::AlphCompare()(to, bk.to) < 0;
```

File: scene/animation/animation_player.h [hunk 3]
```diff
@@ -95,9 +95,9 @@ class AnimationPlayer : public AnimationMixer {
...
 			} else {
-				return from < bk.from;
+				return String(from) < String(bk.from);
```
Comment (AThousandShips) [inline scene/animation/animation_player.h:100]:
```suggestion
				return StringName::AlphCompare()(from, bk.from) < 0;
```

File: scene/animation/animation_player.h [hunk 4]
```diff
@@ -95,9 +95,9 @@ class AnimationPlayer : public AnimationMixer {
 		}
 		bool operator<(const BlendKey &bk) const {
 			if (from == bk.from) {
-				return to < bk.to;
+				return StringName::AlphCompare()(to, bk.to) < 0;
```
Comment (AThousandShips) [inline scene/animation/animation_player.h:98]:
```suggestion
				return StringName::AlphCompare()(to, bk.to);
```
Forgot it was a `<` not a ordering return

**Comment by JacobMillner** [comment]
tested and working locally with `StringName::AlphaCompare` :+1:

**Review by TokageItLab — APPROVED** [review]

**Comment by TokageItLab** [comment]
Please squash the commits to follow PR workflow https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase

**Comment by akien-mga** [comment]
Thanks!

**Comment by JacobMillner** [comment]
Thanks everyone!
