### PR TITLE
Fix script properties reload from external editor

### LINKED ISSUE #91035: Custom resources with script parents only reload in Inspector when opened in internal script editor
### Tested versions

- Reproducible in v4.2.2.stable.mono

### System information

Godot v4.2.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.4633) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description

I am using Sublime Text 4 as my editor.
When editing a script used as a base for custom resources, if the setting `Use External Editor` is enabled then changes to the base script are only reflected in the inspector upon a complete project reload, or if script is open in the Script view.  If `Use External Editor` is disabled then changes are still only reflected if the script is open internally, although that's most likely working as intended.  I have also had problems with new scripts not appearing to use as a resource parent until I reload the project.  
I would expect that changes are detected and updated automatically, like they are for scripts attached to nodes that are edited by external programs.

This problem is exacerbated by the fact that there is no way to force-open a script in the internal editor if you're using an external editor (see godotengine/godot-proposals#3659).  The only solution currently is to temporarily disable external editors just to open the script interally.

### Steps to reproduce

To create the attached minimum project 
- From a fresh project, ensure `Use External Editor` is enabled
- Create a script by right-clicking the FileSystem panel
  - Make it inherit Resource
  - Name it `Stats.gd`
- Make its contents the following:
```gdscript
extends Resource

class_name Stats

@export var health: int = 10
```
- Create a resource from the FileSystem panel with our new Stats class as a base
  - Name it `EnemyStats.res`

Now we have the MRP.  Reload the project to start fresh.

- Open `EnemyStats.res` from the FileSystem panel
  - Note that it has an exported variable `health` that is accessible from the inspector panel
- Open `Stats.gd` in an external editor and add a new exported variable
- Open `EnemyStats.res` from the FileSystem panel
  - Note that `health` remains as the only exported variable
- Change the `Use External Editor` setting to false
  - Note that `EnemyStats.res` still has not updated in the inspector panel
- Open `Stats.gd` in the internal editor
- Open `EnemyStats.res` from the FileSystem panel
  - Note that the changes made finally reflect in the inspector panel
- Switch to a different view such as 3D
- Remove or add an external variable in an external program and save the file
  - Note that the inspector panel updated
- Return to the Script view and close the file there
- Remove or add an external variable in an external program and save the file
  - Note the the inspector panel no longer updates

If you follow the first part and create new scripts and resources (e.g. Item.gd and Torch.res), the resource's inspector panel will only update if that particular script is open in the internal editor.
I tried to be as thorough as possible but it feels picky.  I've had the script open internally with with `Use External Editor` enabled without the inspector updating at all, but I was unable to reproduce here.

### Minimal reproduction project (MRP)

[ExternalResource.zip](https://github.com/godotengine/godot/files/15069548/ExternalResource.zip)

### PR DESCRIPTION
**Pull request by Hilderin**
- Fixes #91035

This fixes the issue where the properties of a custom resource linked to a script are not updated when the script is modified outside the Godot Script Editor.

The problem was caused by the fact that `update_exports` on the script was never called in this situation. I added a call to `update_exports` in `EditorNode::_resources_changed` if the reloaded resource is a script.

While debugging, I also discovered that the global class name cache and the script documentation were not updated when the script was modified in an external editor and the script was never loaded in the editor. This was caused by the `if (ResourceCache::has(path))` condition in `EditorFileSystem::_update_scan_actions`. There's already a similar condition in `EditorNode::_resources_changed` to prevent loading resources that were never loaded.

Additionally, the global class name was never read from the script file when it was modified externally. In `EditorFileSystem::_update_scan_actions`, when processing `ACTION_FILE_RELOAD`, the `FileInfo` was updated, but with the value in memory. To fix this, I called `update_files` with all the reloaded files. This method is already used when scripts are updated in the Script Editor.

https://github.com/user-attachments/assets/180456ad-ff9b-42df-ac59-0b84cddb588e

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -964,6 +964,12 @@ void EditorNode::_resources_changed(const Vector<String> &p_resources) {
 	if (changed.size()) {
 		for (Ref<Resource> &res : changed) {
 			res->reload_from_file();
+
+			// Update exports to update the properties in the inspector.
+			Ref<Script> scr = Object::cast_to<Script>(res.ptr());
+			if (scr.is_valid()) {
+				scr->update_exports();
+			}
```
Comment (kitbdev) [inline editor/editor_node.cpp:972]: Maybe this should be in `Script::reload_from_file()`.

Comment (Hilderin) [reply editor/editor_node.cpp:972]: There's already a` reload_from_file` just above and it was not sufficient.

Comment (kitbdev) [reply editor/editor_node.cpp:972]: Sorry, I meant that `update_exports()` should be added into the Script's `reload_from_file` implementation instead of having it here, since every time we reload the script we also want to update the exports.
For instance `ScriptEditor::_close_discard_current_tab` also uses `reload_from_file` and it should call `update_exports` too.

**Comment by Hilderin** [comment]
While testing I encounter another problem. If I open the script in an external editor like VSCode that is connected to the LSP server and I modify the script in a third editor like notepad or from a git update, VSCode calls the LSP server with a `didChange` message. At this point `GDScriptTextDocument::sync_script_content` was called which called `EditorFileSystem::get_singleton()->update_file(path);` which updates the last modification date of the script but does not reloads the resource. Since the last modification date of the script is updated in `EditorFileSystem`, it is not reloaded from the scan changes in the `EditorFileSystem`.

In this situation, the resource was never reloaded in the editor. 

I removed the call to `EditorFileSystem::update_file` in which caused the desynchronization between the `EditorFileSystem` and the loaded resources.

**Comment by Hilderin** [comment]
Just found another bug while testing #95821 when updating a script from external editor not connected to LSP. The documentation of the script (ex: Documentation on a property with ##) is not updated in the editor. Just pushed a fix for that

**Comment by Hilderin** [comment]
Rebased and fixed another bug when reloading script from external editor without being connected via LSP where the documentation was not updated if it was opened in the Script Editor.

File: editor/editor_file_system.cpp [hunk 2]
```diff
@@ -43,6 +43,7 @@
 #include "editor/editor_resource_preview.h"
 #include "editor/editor_settings.h"
 #include "editor/project_settings_editor.h"
+#include "plugins/script_editor_plugin.h"
```
Comment (akien-mga) [inline editor/editor_file_system.cpp:46]: We prefer to use "absolute" include paths for consistency.
```suggestion
#include "editor/plugins/script_editor_plugin.h"
#include "editor/project_settings_editor.h"
```

Comment (Hilderin) [reply editor/editor_file_system.cpp]: Wow, I copy/paste from the only place in all Godot code base where the absolute path was not used for `script_editor_plugin.h`!!
I changed it in `C:\Projects\godot\editor\connections_dialog.cpp` also.

File: editor/editor_file_system.cpp [hunk 3]
```diff
@@ -841,7 +833,7 @@ bool EditorFileSystem::_update_scan_actions() {
 		}
 	}
 
-	if (reimports.size()) {
+	if (reimports.size() > 0) {
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:836]:
```suggestion
	if (!reimports.is_empty()) {
```

File: editor/editor_file_system.cpp [hunk 4]
```diff
@@ -1341,8 +1338,7 @@ void EditorFileSystem::_scan_fs_changes(EditorFileSystemDirectory *p_dir, ScanPr
 				ia.file = p_dir->files[i]->file;
 				scan_actions.push_back(ia);
 			}
-		} else if (ResourceCache::has(path)) { //test for potential reload
-
+		} else {
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:1341]: This causes reload attempt for non-loaded Resources (I think?). Why this change?

Comment (Hilderin) [reply editor/editor_file_system.cpp:1341]: The problem that this fix is if a script is modified in an external editor without LSP (or just a git pull) and that script was never loaded, it will never be processed and that causes the documentation to not update and the file last modification date was never updated the EditorFileSystem.

Comment (KoBeWi) [reply editor/editor_file_system.cpp:1341]: Non-loaded Resources shouldn't need reloading, only updating their last checked time 🤔

Comment (Hilderin) [reply editor/editor_file_system.cpp:1341]: One thing that is important to known is that the same check is done in `EditorNode::_resources_changed` to prevent resources that are not already loaded to reload. Also, I don't think it's possible to update du documentation without reloading the script. So, my comprehension is that for script, they will all be reloaded in `EditorFileSystem::_update_script_documentation` but for other resources, they should be reloaded only if they were already in the cache due to the condition in `EditorNode::_resources_changed`. The difference is that in the `resources_reload` signal we will also receive resources that were not already loaded.

I think, after thinking about it, I should put back the condition just to add the path in the `reloads` list. That way, only resources that have been already loaded will be present in the `resources_reload` signal and we still get the documentation updated. Sounds good?

Comment (KoBeWi) [reply editor/editor_file_system.cpp:1341]: Yep.

Comment (Hilderin) [reply editor/editor_file_system.cpp:1343]: Done!

File: editor/editor_file_system.cpp (hunk 3 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp]: Done!

File: editor/editor_file_system.cpp [hunk 5]
```diff
@@ -852,6 +846,11 @@ bool EditorFileSystem::_update_scan_actions() {
 		ResourceUID::get_singleton()->update_cache();
 	}
 
+	if (reloads.size() > 0) {
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:849]:
```suggestion
	if (!reloads.is_empty()) {
```

**Review by KoBeWi — APPROVED** [review]
I can't reproduce the bug, but this doesn't seem to break anything and the code looks ok.

File: editor/editor_file_system.cpp (hunk 5 above)
Comment (Hilderin) [reply editor/editor_file_system.cpp]: Done!

**Comment by akien-mga** [comment]
Thanks!

**Comment by ryevdokimov** [comment]
I'm having trouble narrowing down what specifically in my project is causing this error: https://github.com/godotengine/godot/blob/922ae7e7b5fb6c8733a7c03a3c797773f97d9162/modules/gdscript/gdscript.cpp#L747

But it has something to do with this PR since it only started occurring after this was merged and reverting it prevents it. I'm using a lot of tool scripts which may have something to do with it, and it only occurs when the project is first imported. I'll keep digging before I submit an issue because I don't know how to describe what the problem is yet, but maybe it's something more obvious to the people here.

**Comment by Zireael07** [comment]
@ryevdokimov Please open an issue, comments on closed PRs are rarely seen

**Comment by ryevdokimov** [comment]
Looks like someone already did: https://github.com/godotengine/godot/issues/97138
