### PR TITLE
Fix crash on project importing by dragging a folder.

### LINKED ISSUE #7226: Crash on drag-n-drop to new project dialog
**Operating system or device - Godot version:**
Windows 10 Core i5 - 2.1.1.stable.official (64-bit)

**Issue description** (what happened, and what was expected):
Crash on folder drag-n-drop to new project dialog

**Steps to reproduce:**
From project manager: click "New Project"
click "Browse"
Drag a folder from Explorer to anywhere in the "Open a Directory" dialog
Crash

Note: a crash will also occur if a folder is dragged into the "New Project" dialog without clicking "Browse"

My motivation was to make browsing to the new folder easier, since the previous project path is not remembered between program runs.  I already had the path open in explorer, so dragging seemed natural.  Copy and paste does work, but is more cumbersome.

### PR DESCRIPTION
**Pull request by 27thLiz**
Fixes #7226

### CODE REVIEW

File: tools/editor/project_manager.cpp [hunk 1]
```diff
@@ -1154,7 +1154,7 @@ void ProjectManager::_files_dropped(StringArray p_files, int p_screen) {
 				dir->list_dir_begin();
 				String file = dir->get_next();
 				while(confirm && file!=String()) {
-					if (!da->current_is_dir() && file.ends_with("engine.cfg")) {
```
Comment (Hinsbart) [inline tools/editor/project_manager.cpp]: `da` has been `memdelete`d a few lines above, so it crashed here.
