### PR TITLE
Fix signals disconnecting on changing target node type

### LINKED ISSUE #11673: Connected signals will be disconnected if the target node changes its type
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master https://github.com/godotengine/godot/commit/4f39ce32b9195405f934445b20059e86632b47f9

**Issue description:**

When changing the type of a node all connected signals to that node will be disconnected.

**Steps to reproduce:**
1. Create two nodes
2. Connect a signal from one to another
3. Change the type of the target node

### PR DESCRIPTION
**Pull request by kitbdev**
fixes #11673
I removed the ERR_CONTINUE that checked if the target has the signal method, it seemed unnecessary and was causing the problem.

### CODE REVIEW

**Comment by neikeq** [comment]
That was a fix for #6602. I'm not sure if I understand #11673, is the target a script method? I would expect `has_method` to detect it and keep the connection:

https://github.com/godotengine/godot/blob/19b1ff0fc5f7acce23176ad6c8752604357472f0/core/object.cpp#L699-L716

Maybe it is not working for non-tool scripts because of placeholders? If that's the case, then I think checking it in the script itself should work. Something like this:
``` C++
ERR_CONTINUE(!p_new_target->has_method(c.method) && !(get_script().is_valid() && get_script()->has_method(c.method)));
```

**Comment by ianb96** [comment]
I updated the code to use `!p_new_target->has_method(c.method) && (!p_new_target->get_script().is_null() && !Ref<Script>(p_new_target->get_script())->has_method(c.method))` to check if the node has the method.

**Review by neikeq — APPROVED** [review]

File: scene/main/node.cpp [hunk 1]
```diff
@@ -2422,7 +2422,9 @@ void Node::_replace_connections_target(Node *p_new_target) {
 
 		if (c.flags & CONNECT_PERSIST) {
 			c.source->disconnect(c.signal, this, c.method);
-			ERR_CONTINUE(!p_new_target->has_method(c.method));
+			bool invalid = !p_new_target->has_method(c.method) && (!p_new_target->get_script().is_null() && !Ref<Script>(p_new_target->get_script())->has_method(c.method));
```
Comment (vnen) [inline scene/main/node.cpp]: You should reverse the logic to test if it's `valid` instead, then do `ERR_CONTINUE(!valid)`. It'll make the condition easier to understand.

Make sure to amend the commit after the change. You can consult our [PR workflow guide](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request) for instructions.

**Review by vnen — CHANGES_REQUESTED** [review]

**Comment by ianb96** [comment]
I changed it to use `p_new_target->has_method(c.method) || p_new_target->get_script().is_null() || Ref<Script>(p_new_target->get_script())->has_method(c.method)` and !valid
