### PR TITLE
Fix menus and dropdowns requiring two clicks

### LINKED ISSUE #101214: Open an in-editor menu requires an extra click
### Tested versions

- Reproducible in 4.4dev [4cf02312f6674083c5a628b4701643e1157c85f0]
- Not reproducible in 4.4dev 7

### System information

Windows 11

### Issue description

I've detected that in-editor menu now requires an extra click:

Image

Seems like a recent regression.

### Steps to reproduce

^^

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by wlsnmrk**
Fixes #101214. Makes handling of all pressed status elements consistent on toggle buttons with `ACTION_MODE_BUTTON_PRESSED`.

https://github.com/user-attachments/assets/27b88e0f-9cc5-463d-9fab-98fcbd45f3b1

### CODE REVIEW

File: scene/gui/base_button.cpp [hunk 1]
```diff
@@ -165,6 +165,8 @@ void BaseButton::on_action_event(Ref<InputEvent> p_event) {
 				if (action_mode == ACTION_MODE_BUTTON_PRESS) {
 					status.press_attempt = false;
 					status.pressing_inside = false;
+					status.pressed_down_with_focus = false;
+					emit_signal(SNAME("button_up"));
```
Comment (Hilderin) [inline scene/gui/base_button.cpp:169]: This seems to fix the issue but I think the `button_up` signal should be emitted after the pressed event. Usually, it's expected to have down, pressed and up. In this order. Maybe a bool could be set here and checked at the end of the method to prevent the code duplication.

**Comment by Hilderin** [comment]
I'm wondering since it's easy to create side effects in this code if conditions like that should be use instead:
```
if (p_event->is_pressed() && (mouse_button.is_null() || status.hovering)) {
	status.press_attempt = true;
	status.pressing_inside = true;
	if (!status.pressed_down_with_focus) {
		status.pressed_down_with_focus = true;
		emit_signal(SNAME("button_down"));
	}
}
```
```
if (!p_event->is_pressed()) {
	status.press_attempt = false;
	status.pressing_inside = false;
	if (status.pressed_down_with_focus) {
		status.pressed_down_with_focus = false;
		emit_signal(SNAME("button_up"));
	}
}
```

**Comment by badsectoracula** [comment]
I tried and works, however i'll agree with Hilderin that `button_up` should be emitted after any press event. I modified the code a bit to use an `emit_button_up` boolean which is checked at the end of the function above `queue_draw` (using the existing code) and it seemed to work fine, so i'd recommend that.

File: scene/gui/base_button.cpp (hunk 1 above)
Comment (wlsnmrk) [reply scene/gui/base_button.cpp:169]: Thanks. This raises an interesting point, which is that the current (4.3) behavior is inconsistent. Normal buttons do indeed emit down->pressed->up, but dropdowns and menus have different behavior depending whether they're being opened or closed. On close, they also emit down->pressed->up. However, on open, they emit down->up->pressed. (See attached video, taken in 4.3. It only shows dropdowns, but menus behave the same.)

https://github.com/user-attachments/assets/e7918597-6069-4dd4-9791-f46cb90c5dc6

I suppose the question is whether the current behavior should be replicated exactly, or the open behavior changed to match the close behavior (and other buttons).

**Comment by wlsnmrk** [comment]
> I'm wondering, since it's easy to create side effects in this code, if conditions like that should be use instead.

Great suggestion, thanks. I've done exactly this. With respect to the above discussion about signal order, this is currently preserving the somewhat inconsistent 4.3 behavior. If a fix/change is desired there, I can take a look at it.

**Comment by Hilderin** [comment]
> I've removed the special-case button-up signal for toggle buttons with ACTION_MODE_BUTTON_PRESSED

Great!

> so with respect to the above discussion about signal order, this is currently preserving the somewhat inconsistent 4.3 behavior. If a fix/change is desired there, I can take a look at it.

I'm not sure it causes any issue right now. I suggest we wait for an actual bug report on this.

I'll test a bit more your last commit but it looks good.

**Review by Hilderin — APPROVED** [review]
Test on a local build, everything in the editor and in the test project works fine.
Great job, thank you!

**Comment by akien-mga** [comment]
Thanks!
