### PR TITLE
Print an error if trying to run a self-contained editor in a project folder

### LINKED ISSUE #66176: When using `--export` the game exported from Mac will not work
### Godot version

658bfb0395fa356f67745de0620628167671d5c6

### System information

MacOS, intel mac

### Issue description

Exporting game on MacOS with terminal results in non functional game (non headless)

```console
cp ../godot/bin/godot.macos.opt.tools.x86_64 ./
touch _sc_
mkdir -p editor_data/export_templates/4.0.alpha
cp ../godot/osx_template.zip ./editor_data/export_templates/4.0.alpha/macos.zip
./godot.macos.opt.tools.x86_64 --verbose --editor --quit 
./godot.macos.opt.tools.x86_64 --export macOS build/Client.app
```

log from client after launching:
```console
[1;31mERROR:[0;91m Cannot open file 'res://main.tscn'.
[0;90m   at: load (scene/resources/resource_format_text.cpp:1558)[0m
[1;31mERROR:[0;91m Failed loading resource: res://main.tscn. Make sure resources have been imported by opening the project in the editor at least once.
[0;90m   at: _load (core/io/resource_loader.cpp:222)[0m
[1;31mERROR:[0;91m Failed loading scene: res://main.tscn
[0;90m   at: start (main/main.cpp:2931)[0m
ERROR: 1 RID allocations of type 'P11GodotBody3D' were leaked at exit.
ERROR: 1 RID allocations of type 'P11GodotArea3D' were leaked at exit.
ERROR: 1 RID allocations of type 'P12GodotSpace3D' were leaked at exit.
ERROR: 1 RID allocations of type 'P11GodotArea2D' were leaked at exit.
ERROR: 1 RID allocations of type 'P12GodotSpace2D' were leaked at exit.
ERROR: 2 RID allocations of type '6NavMap' were leaked at exit.
ERROR: 2 RID allocations of type 'N21RendererSceneRenderRD11ShadowAtlasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N21RendererSceneRenderRD15ReflectionAtlasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N10RendererRD14TextureStorage12RenderTargetE' were leaked at exit.
ERROR: 2 RID allocations of type 'N10RendererRD14TextureStorage7TextureE' were leaked at exit.
ERROR: 1 RID allocations of type 'N18RendererCanvasCull6CanvasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N16RendererViewport8ViewportE' were leaked at exit.
ERROR: 1 RID allocations of type 'N17RendererSceneCull8ScenarioE' were leaked at exit.
[1;33mWARNING:[0;93m 3 RIDs of type "StorageBuffer" were leaked.
[0;90m     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:9416)[0m
[1;33mWARNING:[0;93m 1 RID of type "UniformBuffer" was leaked.
[0;90m     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:9414)[0m
[1;33mWARNING:[0;93m 1 RID of type "Framebuffer" was leaked.
[0;90m     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:9414)[0m
[1;33mWARNING:[0;93m 4 RIDs of type "Texture" were leaked.
[0;90m     at: finalize (drivers/vulkan/rendering_device_vulkan.cpp:9736)[0m
[1;33mWARNING:[0;93m ObjectDB instances leaked at exit (run with --verbose for details).
[0;90m     at: cleanup (core/object/object.cpp:1956)[0m
arguments
0: /Users/gordon/Projects/repro-export/build/Client.app/Contents/MacOS/Repro-export
Godot Engine v4.0.beta.custom_build.658bfb039 - https://godotengine.org
Vulkan API 1.1.216 - Using Vulkan Device #0: AMD - AMD Radeon Pro 5500M
 
```

### Steps to reproduce

1. Put minimal reproduction project in the folder adjacent to your godot folder
2. make a script file and paste contents from issue description
3. run the script after chmod +x'ing the script

### Minimal reproduction project

[repro-export.zip](https://github.com/godotengine/godot/files/9610671/repro-export.zip)

This issue is for The Mirror.

### PR DESCRIPTION
**Pull request by aaronfranke**
This scenario is invalid, but previously Godot did not prevent doing this, leading to silent failure. Fixes #66176.

Note 1: The error is actually printed twice, which is a bit weird, but it's fine.

Note 2: The editor files being inside of the export is not the only reason for doing this, but it's the easiest reason to explain. We encountered problems because there were some files *not* being exported. This is likely a bug unto itself, but I guess it's not a big deal to fix a bug that only happens in an invalid configuration anyway, so my suggestion is to consider that "WONTFIX" and instead just have this error message for the invalid situation.

EDIT: Fixed in https://github.com/godotengine/godot/pull/66364

### CODE REVIEW

**Review by bruvzg — COMMENTED** [review]
Maybe it should be done in the `main`, and prevent running `self-contained` executable from the project folder at all. Even if it is capable of opening / running the project, it would have unexpected consequences, like mixing editor config/cache file with the project imports and later adding them to the exported PCK.

**Review by bruvzg — APPROVED** [review]

File: main/main.cpp [hunk 1]
```diff
@@ -1933,6 +1933,13 @@ Error Main::setup2(Thread::ID p_main_tid_override) {
 	if (editor || project_manager || cmdline_tool) {
 		EditorPaths::create();
 	}
+	if (EditorPaths::get_singleton()->is_self_contained()) {
```
Comment (akien-mga) [inline main/main.cpp:1936]: This will crash when running a project. EditorPaths is created right above under conditions - you can only use it under those same conditions.

Comment (bruvzg) [reply main/main.cpp:1936]: `_sc_` seems to be only used by the editor, so I guess it's not relevant when running the project, so I guess it should be in the same `(editor || project_manager || cmdline_tool)` condition.

Comment (aaronfranke) [reply main/main.cpp:1936]: Sorry about that, this seems obvious in retrospect, it's what I get for trying to finish this feature past midnight.

**Review by akien-mga — APPROVED** [review]
