### PR TITLE
Complete Dummy mesh support in the dummy renderer.

### LINKED ISSUE #64720: ERROR: unimplemented base type encountered in renderer scene cull when running `--doctool`
### Godot version

4.0.alpha (8a1e5980116355024cd7a7ce0c15db7d4ecb200a)

### System information

Mageia 9 Linux, x86_64

### Issue description

When running `--doctool` (and possibly other run modes), the following error is printed to the terminal:

```
ERROR: unimplemented base type encountered in renderer scene cull
   at: instance_set_base (servers/rendering/renderer_scene_cull.cpp:619)
```

And when the process terminates:
```
ERROR: 21 RID allocations of type 'N13RendererDummy11MeshStorage9DummyMeshE' were leaked at exit.
```

This bug was introduced recently (didn't happen 2 weeks ago).

### Steps to reproduce

`godot --doctool`

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Rudimentary mesh support was added to the dummy renderer but this was incomplete resulting in objects being leaked.

This PR adds the bare minimum implementation and adds a dummy implementation of GeometryInstance so everything works.

Fixes #64720

### CODE REVIEW

File: servers/rendering/renderer_scene_cull.cpp [hunk 1]
```diff
@@ -637,20 +637,22 @@ void RendererSceneCull::instance_set_base(RID p_instance, RID p_base) {
...
-				geom->geometry_instance->set_layer_mask(instance->layer_mask);
-				geom->geometry_instance->set_lod_bias(instance->lod_bias);
-				geom->geometry_instance->set_transparency(instance->transparency);
-				geom->geometry_instance->set_use_baked_light(instance->baked_light);
-				geom->geometry_instance->set_use_dynamic_gi(instance->dynamic_gi);
-				geom->geometry_instance->set_use_lightmap(RID(), instance->lightmap_uv_scale, instance->lightmap_slice_index);
-				geom->geometry_instance->set_cast_double_sided_shadows(instance->cast_shadows == RS::SHADOW_CASTING_SETTING_DOUBLE_SIDED);
-				if (instance->lightmap_sh.size() == 9) {
-					geom->geometry_instance->set_lightmap_capture(instance->lightmap_sh.ptr());
+				if (geom->geometry_instance) {
```
Comment (BastiaanOlij) [inline servers/rendering/renderer_scene_cull.cpp:640]: Not entirely happy at having to check this pointer everywhere. This is because we do support meshes but we don't support geometry instances, but one triggers the other. 

One point of discussion before we merge this PR, should we implement a dummy geometry instance class so that we do instance these properly. Then we can get rid of all of these if statements or add a `ERR_FAIL_NULL(geom->geometry_instance)` which in this case makes more sense..

Comment (clayjohn) [inline servers/rendering/renderer_scene_cull.cpp:640]: Why is this change needed? As far as I can tell a geometry_instance is allocated for every InstanceGeometryData immediately after creation. Is there a possibility that geometry_instance gets freed while the InstanceGeometryData does not?

Comment (clayjohn) [reply servers/rendering/renderer_scene_cull.cpp:640]: Oops, I see you have already flagged this line

Comment (BastiaanOlij) [reply servers/rendering/renderer_scene_cull.cpp:640]: Because the dummy renderer doesn't instance it because it doesn't implement it, it returns a NULLPTR

I'm changing that right now..

Comment (BastiaanOlij) [reply servers/rendering/renderer_scene_cull.cpp]: Ok added proper geometry instance support as well.

**Review by clayjohn — APPROVED** [review]
Looks much better now with GeometryInstance added. Great work!

**Comment by akien-mga** [comment]
Thanks!
