### PR TITLE
Expose "Keep" import option when multiple files are selected

### LINKED ISSUE #52037: Can't set 'import as' flag for multiple .csv files to 'KeepFile (no import)'.
### Godot version

v3.3.3.stable.official [b973f997f]

### System information

Windows 10, GLES3

### Issue description

When selecting 1 csv file it appears as expected:

But when selecting more than 1 csv file the option keep file (no import) dissapears:

In theory it's possible to re-import each .csv file separated, however being in a big project, re-opening the project with a lot of .csv files isn't a option.

### Steps to reproduce

Place two .csv files in a project, select the two files in the editor, go to import tab, the option doesn't show up to reimport them as keep file;

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by David1Socha**
To resolve https://github.com/godotengine/godot/issues/52037 . Extracts the code adding "Keep" option to a private method, and adds a call of that method to the `ImportDock::set_edit_multiple_paths()` (in addition to the current call from `ImportDock::set_edit_path()`)

The fix suggested by @akien-mga worked, after making that change I was able to select several files and change them all to "Keep" import simultaneously. For what it's worth, the reverse operation still isn't possible in a batch form from within Godot (i.e. changing 10 files from "Keep" import to "Image" import or whatever), but that is hopefully a rarer use-case and looks like it'd require some deeper updating to change.

### CODE REVIEW

File: editor/import_dock.h [hunk 1]
```diff
@@ -66,6 +66,7 @@ class ImportDock : public VBoxContainer {
 	void _importer_selected(int i_idx);
 	void _update_options(const Ref<ConfigFile> &p_config = Ref<ConfigFile>());
 	void _update_preset_menu();
+	void _add_keep_import_option(const String &importer_name);
```
Comment (akien-mga) [inline editor/import_dock.h:69]: Our convention is to use `p_` prefix for parameters (or `r_` when they're mutated by the function).
```suggestion
	void _add_keep_import_option(const String &p_importer_name);
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
