### PR TITLE
Produce an error when a class has the same name as a Singleton

### LINKED ISSUE #28187: class_name overrides AutoLoad global name if using the same name
**Godot version:**
3.1 official

**OS/device including version:**
Windows 7 PC

**Issue description:**
Whenever i use globals and give them a class_name, i cannot access their non-static methods via script, because the script thinks i want to access a class instead of a global, although i have autoload on. But it can be "solved" in two ways:

- remove the class-name
- make the func in the global static (although he seems to still try to access the Object and not the global) But here i have the advantage of not being able to emit signals from the global. Maybe more, but this is the most impactful to me.

I guess this happens only, if the class_name and the script-name are identical.

As i know this now, for me personally this is not too big of an issue, but for newcomers this could put them in front of a problem, that could be deterring them from using godot any further, as its not a direclty "logical" error, if you dont know its cause.

**Steps to reproduce:**
- Add Script to autoload
- add Class_name that is identical to the Name in Autoload
- try executing a non-static method in the global

solve by:
- either make method static
- or delete class_name

**Minimal reproduction project:**
[Reproduction_Project.zip](https://github.com/godotengine/godot/files/3097255/Reproduction_Project.zip)

### PR DESCRIPTION
**Pull request by mitchcurtis**
If you somehow end up with a Singleton.gd that looks like this:

	extends Node

	class_name Singleton

	func foo():
	    pass

You will get an error when using it in another file:

	extends Node2D

	func _init():
	    # Parser Error: Non-static function "foo" can only be called from an instance.
	    Singleton.foo()

This error is confusing. This patch ensures that an error on the class_name line will be produced:

    Parse Error: The class "Singleton" conflicts with the AutoLoad singleton of the same name, and is therefore redundant. Remove the class_name declaration to fix this error.

Fixes #28187.

### CODE REVIEW

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -3533,6 +3533,11 @@ void GDScriptParser::_parse_class(ClassNode *p_class) {
 					return;
 				}
 
+				if (p_class->classname_used && ScriptServer::is_global_class(p_class->name)) {
```
Comment (bojidar-bg) [inline modules/gdscript/gdscript_parser.cpp]: This check already exists above (line 3526), no?

Comment (mitchcurtis) [reply modules/gdscript/gdscript_parser.cpp]: Isn't that checking for duplicate singletons? It doesn't do any checks for types declared with `class_name`.

Comment (bojidar-bg) [reply modules/gdscript/gdscript_parser.cpp]: Wouldn't this check error even on scripts using class_name without being singletons?

Comment (mitchcurtis) [reply modules/gdscript/gdscript_parser.cpp]: I will check that this afternoon, but wouldn't it only act on singletons due to the following line?
```
ScriptServer::is_global_class(p_class->name)
```

Comment (bojidar-bg) [reply modules/gdscript/gdscript_parser.cpp]: I'm pretty sure singletons/autoloads are not handled by `is_global_class`. More like, `is_global_class` should handle `class_name`-s

Comment (mitchcurtis) [reply modules/gdscript/gdscript_parser.cpp]: Oh... but what is `p_class->classname_used` used for then?

Comment (bojidar-bg) [reply modules/gdscript/gdscript_parser.cpp]: `p_class->classname_used` is set to true whenever `class_name` (the keyword) was used in the class.
To check if there is a singleton with that name, you would have to check `ProjectSettings`. Specifically, search for `"autoload/"` in the code.

**Comment by bojidar-bg** [comment]
Looks better now -- just make sure that it does not conflict with all autoloads, but only with singletons.

**Comment by mitchcurtis** [comment]
> Looks better now -- just make sure that it does not conflict with all autoloads, but only with singletons.

Er... can you give an example of how I would do that? I see that there is an "enable" check box, but what specific steps should I take to test that it doesn't conflict?

**Comment by bojidar-bg** [comment]
Just check if the script path in the setting starts with `*`.

**Comment by mitchcurtis** [comment]
Ping.

**Review by bojidar-bg — APPROVED** [review]
Error message might need some work, should work fine otherwise.

**Comment by akien-mga** [comment]
Thanks!
