### PR TITLE
[Web] Fix closure compiler typedef annotation

### LINKED ISSUE #91161: Web build fails on Emscripten 3.1.58
### Tested versions

- Reproducible in 4.3.dev (780e1a50408360cf0cf93c0b55b59e9d7b4ad0b1)
- Reproducible in 3.6.beta (after including #91151 so recent Emscripten can be used)

### System information

Fedora Linux 39 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7600M XT (RADV NAVI33) () - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)

### Issue description

Emscripten never fails to disappoint with breaking Godot every other release.

I tested the latest 3.1.58 and our Web editor build is broken (this is with closure compiler, but it fails the same without).

```
/usr/bin/node /home/akien/Godot/toolchains/emsdk/upstream/emscripten/node_modules/.bin/google-closure-compiler --compilation_level ADVANCED_OPTIMIZATIONS --externs /home/akien/Godot/godot/platform/web/js/engine/engine.externs.js --js /home/akien/Godot/godot/platform/web/js/engine/features.js --js /home/akien/Godot/godot/platform/web/js/engine/preloader.js --js /home/akien/Godot/godot/platform/web/js/engine/config.js --js /home/akien/Godot/godot/platform/web/js/engine/engine.js --js_output_file /home/akien/Godot/godot/bin/godot.web.editor.wasm32.engine.js
Install file: "misc/dist/html/logo.svg" as "bin/.web_zip/logo.svg"
Install file: "misc/dist/html/manifest.json" as "bin/.web_zip/manifest.json"
Install file: "misc/dist/html/offline.html" as "bin/.web_zip/offline.html"
Creating 'bin/godot.web.editor.wasm32.service.worker.js'
Install file: "bin/godot.web.editor.wasm32.service.worker.js" as "bin/.web_zip/service.worker.js"
Building compilation database compile_commands.json
progress_finish(["progress_finish"], [])
/home/akien/Godot/godot/platform/web/js/engine/features.js:75:4: WARNING - [JSC_TYPE_PARSE_ERROR] Bad type annotation. type annotation incompatible with other annotations. See https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler for more information.
  75|    * @typedef {{ threads: boolean }} SupportedFeatures
           ^

/home/akien/Godot/godot/platform/web/js/engine/features.js:76:12: WARNING - [JSC_UNRECOGNIZED_TYPE_ERROR] Bad type annotation. Unknown type SupportedFeatures
  76|    * @param {SupportedFeatures} supportedFeatures
                   ^

0 error(s), 2 warning(s), 73.6% typed
Linking Static Library core/libcore.web.editor.wasm32.a ...
Ranlib Library core/libcore.web.editor.wasm32.a ...
Linking Program bin/godot.web.editor.wasm32.js ...
em++: warning: -pthread + ALLOW_MEMORY_GROWTH may run non-wasm code slowly, see https://github.com/WebAssembly/design/issues/1271 [-Wpthreads-mem-growth]
cache:INFO: generating system asset: symbol_lists/4b07af37ace67ce59deb12f4d95eee632ec0a8c4.json... (this will be cached in "/home/akien/Godot/toolchains/emsdk/upstream/emscripten/cache/symbol_lists/4b07af37ace67ce59deb12f4d95eee632ec0a8c4.json" for subsequent builds)
cache:INFO:  - ok
wasm-ld: warning: function signature mismatch: unztell
>>> defined as (i32) -> i64 in core/libcore.web.editor.wasm32.a(file_access_zip.web.editor.wasm32.o)
>>> defined as (i32) -> i32 in core/libcore.web.editor.wasm32.a(unzip.web.editor.wasm32.o)
Creating 'bin/godot.web.editor.wasm32.wrapped.js'
Install file: "bin/godot.web.editor.wasm32.wasm" as "bin/.web_zip/godot.editor.wasm"
Install file: "bin/godot.web.editor.wasm32.worker.js" as "bin/.web_zip/godot.editor.worker.js"
scons: *** [bin/.web_zip/godot.editor.worker.js] bin/godot.web.editor.wasm32.worker.js: No such file or directory
scons: building terminated because of errors.
[Time elapsed: 00:06:08.446]
```

The missing `godot.web.editor.wasm32.worker.js` is actually generated in the root folder of the repo, instead of the `bin` folder.

It works fine with Emscripten 3.1.39, so it regressed somewhere in between.

### Steps to reproduce

- Install Emscripten 3.1.58
- Build with `scons p=web target=editor`

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by Faless**
The typedef annotation is expected to come bofre a var (or const) since it's most commonly used in externs. Use an inline definition instead.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
This doesn't seem compatible with the JS file structure we have in `3.x`, could you make a backport for that branch?

**Comment by Faless** [comment]
> This doesn't seem compatible with the JS file structure we have in `3.x`, could you make a backport for that branch?

I don't think the `3.x` branch should be affected by this specifically. The bogus annotation is not there, so it should compile. If it fails, it should have a different error.

I'm trying to make a build now.

**Comment by akien-mga** [comment]
Here's the build log on 3.x: https://github.com/godotengine/godot/pull/91151#issuecomment-2076994986

There's indeed another warning. It's a bit weird that _warnings_ cause the build to fail, without explicit mention that warnings are treated as errors.

**Comment by akien-mga** [comment]
I guess we can merge this as just a warning fix now.

File: platform/web/js/engine/features.js [hunk 1]
```diff
@@ -72,8 +72,7 @@ const Features = { // eslint-disable-line no-unused-vars
 	 *
 	 * @returns {Array<string>} A list of human-readable missing features.
 	 * @function Engine.getMissingFeatures
-	 * @typedef {{ threads: boolean }} SupportedFeatures
-	 * @param {SupportedFeatures} supportedFeatures
+	 * @param {{threads: (boolean|undefined)}} supportedFeatures
```
Comment (Faless) [inline platform/web/js/engine/features.js:75]: I wonder if we should rename the parameter to `requestedFeatures`...

Comment (akien-mga) [reply platform/web/js/engine/features.js:75]: @adamscott

**Comment by akien-mga** [comment]
Thanks!
