### PR TITLE
Fix freeze when data chunk size in WAV header is larger than the actual size

### LINKED ISSUE #94718: Adding large WAV file causes freeze, looping Reimport
### Tested versions

Reproducible in 4.2.2.stable.official [15073afe3], 4.3.beta3.official [82cedc83c]

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 (NVIDIA; 32.0.15.6070) - Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz (4 Threads)

### Issue description

When adding WAV files of a certain size (>~10MB,) the editor will freeze on the "(Re)Importing Assets" dialog for 1-2 minutes. The import will fail, indicated by a X next to the file in the filesystem window. Attempting to do anything in the editor will cause Godot to attempt to import the file again, freezing again and failing to import again. This also makes it painful to remove the offending file from within the editor- technically possible, but much faster to force quit and delete from outside the editor.

I initially thought it was purely a filesize problem, but 2 of the 5 larger WAV files successfully imported, and quickly, without any freezes or notable delays. Both of those files were ~12MB. Reformatting the offending files to MP3 causes them to import correctly.

"How do you expect it to work instead?"

1- For the files to just import, or fail to import quickly and with a dialog explaining why
2- If the cause is predictable (e.g filesize) for a warning dialog to precede the import process
3- Once failed, for the editor to not constantly try to reimport the file so that it can be removed from the project from within the editor

Apologies if I've done any of this obviously wrong. Hi, I'm new here! Thanks for your time

### Steps to reproduce

MRP is an empty project with just a WAV file that has failed to import. Opening the project should immediately make the editor attempt to import the file, causing the freeze.

Originally the MRP also included a larger WAV that successfully imported for comparison purposes, but that made the zip too big

### Minimal reproduction project (MRP)

[TestProject.zip](https://github.com/user-attachments/files/16370431/TestProject.zip)

### PR DESCRIPTION
**Pull request by EAinsley**
Fix  #94718 .

https://github.com/user-attachments/assets/029268be-6f3a-45a6-b255-7d8c65ce38c2

Warn the user if the size in header mismatch with the actual size. When the data chunk size in the header is larger than the actual size, treat the remaining data as data chunk and continue import. It will also provide a warning.

### CODE REVIEW

File: editor/import/resource_importer_wav.cpp [hunk 1]
```diff
@@ -112,7 +112,13 @@ Error ResourceImporterWAV::import(const String &p_source_file, const String &p_s
 	}
 
 	/* GET FILESIZE */
-	file->get_32(); // filesize
+	uint32_t file_size_header = file->get_32() + 8; // Offset 8 byte
```
Comment (adamscott) [inline editor/import/resource_importer_wav.cpp:115]: That isn't an offset, isn't it? You just added `8` to the value.

File: editor/import/resource_importer_wav.cpp [hunk 2]
```diff
@@ -112,7 +112,13 @@ Error ResourceImporterWAV::import(const String &p_source_file, const String &p_s
...
+	uint64_t file_size = file->get_length();
+	if (file_size > file_size_header) {
+		WARN_PRINT(vformat("File size %d is more than expected size %d. (%s)", file_size, itos(file_size_header), p_source_file));
+	} else if (file_size < file_size_header) {
+		WARN_PRINT(vformat("File size %d is less than expected size %d. (%s)", file_size, file_size_header, p_source_file));
+	}
```
Comment (adamscott) [inline editor/import/resource_importer_wav.cpp:121]:
```suggestion
	if (file_size != file_size_header) {
		WARN_PRINT(vformat("File size %s is %s than the expected size %d. (%s)", file_size, file_size_header, file_size > file_size_header ? "more" : "less",  p_source_file));
	}
```

File: editor/import/resource_importer_wav.cpp [hunk 3]
```diff
@@ -198,7 +204,12 @@ Error ResourceImporterWAV::import(const String &p_source_file, const String &p_s
 				break;
 			}
 
+			uint64_t remaining_bytes = file_size - file_pos;
 			frames = chunksize;
+			if (remaining_bytes < chunksize) {
+				WARN_PRINT(vformat("Data chunk is less than expected. Proceed with actual data size. (%s)", p_source_file));
```
Comment (adamscott) [inline editor/import/resource_importer_wav.cpp:210]:
```suggestion
				WARN_PRINT(vformat("Data chunk size is less than expected. Proceeding with actual data size. (%s)", p_source_file));
```

File: editor/import/resource_importer_wav.cpp (hunk 1 above)
Comment (EAinsley) [reply editor/import/resource_importer_wav.cpp:115]: It's the file size in header is 8 bytes less than the actual file size. It is a little confusing, I will change this.

File: editor/import/resource_importer_wav.cpp [hunk 4]
```diff
@@ -112,7 +112,15 @@ Error ResourceImporterWAV::import(const String &p_source_file, const String &p_s
 	}
 
 	/* GET FILESIZE */
-	file->get_32(); // filesize
+
+	// The file size in header is 8 bytes less than the actual size.
+	// See https://docs.fileformat.com/audio/wav/
+	const int FILE_SIZE_HEADER_OFFSET = 8;
+	uint32_t file_size_header = file->get_32() + FILE_SIZE_HEADER_OFFSET;
```
Comment (adamscott) [inline editor/import/resource_importer_wav.cpp:119]:
```suggestion
	const int FILE_SIZE_HEADER_OFFSET = 8;
	uint32_t file_size_header = file->get_32() - FILE_SIZE_HEADER_OFFSET;
```

Comment (EAinsley) [reply editor/import/resource_importer_wav.cpp:119]: The file size in the header is 8 bytes less than the actual file size. The fist `file->get_32()` reads the file size in the header, and we need to add 8 bytes so that it reflects the real file size. If change it to minus, it will have false warning.

**Review by adamscott — APPROVED** [review]
Seems fine to me!

**Review by AThousandShips — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
