### PR TITLE
Assign the correct bone rest transform to nodes with matrix in GLTF

### LINKED ISSUE #97022: Gltf nodes using "matrix" instead of TRS have incorrect bone rest
### Tested versions

- Reproducible in 4.3.stable

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

A bug in this if statement in gltf_document.cpp causes nodes with matrix not not assign the correct bone rest transform.

```cpp
		if (n.has("matrix")) {
			node->transform = _arr_to_xform(n["matrix"]);
		} else {
			if (n.has("translation")) {
				node->set_position(_arr_to_vec3(n["translation"]));
			}
			if (n.has("rotation")) {
				node->set_rotation(_arr_to_quaternion(n["rotation"]));
			}
			if (n.has("scale")) {
				node->set_scale(_arr_to_vec3(n["scale"]));
			}

			Transform3D godot_rest_transform;
			godot_rest_transform.basis.set_quaternion_scale(node->transform.basis.get_rotation_quaternion(), node->transform.basis.get_scale());
			godot_rest_transform.origin = node->transform.origin;
			node->set_additional_data("GODOT_rest_transform", godot_rest_transform);
		}
```

Also of note, skin_tool.cpp blindly uses the GODOT_rest_transform withouot checking if it exists.
```
			skeleton->add_bone(node->get_name());
			Transform3D rest_transform = node->get_additional_data("GODOT_rest_transform");
			skeleton->set_bone_rest(bone_index, rest_transform);
			skeleton->set_bone_pose_position(bone_index, node->transform.origin);
			skeleton->set_bone_pose_rotation(bone_index, node->transform.basis.get_rotation_quaternion());
			skeleton->set_bone_pose_scale(bone_index, node->transform.basis.get_scale());
```

This is where the identity transform is coming from.

Originally filed by @fire at V-Sekai/godot-vrm#105

### Steps to reproduce

1. Rename the attached .vrm to instead be .glb extension.
2. Import to Godot
3. Double-click the glb to open the advanced importer. all bones have 0,0,0 position in a ball.
4. Reimport the scene with the glb in it. the bones are reset to rest.
5. Click on bones in the Skeleton3D and expand bone rest. the matrix is identity.

### Minimal reproduction project (MRP)

https://github.com/user-attachments/files/16056290/viverse_avatar_model_101119.vrm.zip

### PR DESCRIPTION
**Pull request by fire**
Fixes: https://github.com/godotengine/godot/issues/97022

### CODE REVIEW

**Comment by fire** [comment]
Still need to test the failure projects, but a trip is soon so not sure if I can promise.

**Comment by fire** [comment]
Can confirm broken on `v4.3.stable.steam [77dcf97d8]` and fixed here.

editor_screenshot_2024-10-07T095048

editor_screenshot_2024-10-07T095147

File: modules/gltf/gltf_document.cpp [hunk 1]
```diff
@@ -613,12 +615,10 @@ Error GLTFDocument::_parse_nodes(Ref<GLTFState> p_state) {
 			if (n.has("scale")) {
 				node->set_scale(_arr_to_vec3(n["scale"]));
 			}
-
-			Transform3D godot_rest_transform;
 			godot_rest_transform.basis.set_quaternion_scale(node->transform.basis.get_rotation_quaternion(), node->transform.basis.get_scale());
 			godot_rest_transform.origin = node->transform.origin;
-			node->set_additional_data("GODOT_rest_transform", godot_rest_transform);
 		}
+		node->set_additional_data("GODOT_rest_transform", godot_rest_transform);
```
Comment (lyuma) [inline modules/gltf/gltf_document.cpp:621]: I would delete `godot_rest_transform` and then do:
```suggestion
		node->set_additional_data("GODOT_rest_transform", node->transform);
```

**Review by lyuma — APPROVED** [review]

File: modules/gltf/gltf_document.cpp (hunk 1 above)
Comment (fire) [reply modules/gltf/gltf_document.cpp:621]: Weird TRS is desynced from matrix.

Comment (fire) [reply modules/gltf/gltf_document.cpp]: Or at least asymmetrical.

Comment (fire) [reply modules/gltf/gltf_document.cpp]:
```
Vector3 GLTFNode::get_position() {
	return transform.origin;
}

void GLTFNode::set_position(Vector3 p_position) {
	transform.origin = p_position;
}

Quaternion GLTFNode::get_rotation() {
	return transform.basis.get_rotation_quaternion();
}

void GLTFNode::set_rotation(Quaternion p_rotation) {
	transform.basis.set_quaternion_scale(p_rotation, transform.basis.get_scale());
}

Vector3 GLTFNode::get_scale() {
	return transform.basis.get_scale();
}

void GLTFNode::set_scale(Vector3 p_scale) {
	transform.basis = transform.basis.orthonormalized() * Basis::from_scale(p_scale);
}
```

@aaronfranke modified the code a few years to avoid two ways of specifying the same transform. Looks good.

**Review by lyuma — APPROVED** [review]

**Review by aaronfranke — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
