### PR TITLE
Fix undefined behavior with atan in GPU Particles

### LINKED ISSUE #30906: Particles stop emitting if set a initial velocity [macOS]
**Godot version:**
Master (6c9ccf1)

**OS/device including version:**
macOS 10.14.5
RX 580

**Issue description:**

Particles stop emitting if set a initial velocity
(it works before)

**Steps to reproduce:**

- create a Particles node
- assign a Mesh and ParticleMaterial
- it start emitting
- set Velocity in Initial Velocity to any value
- it stop emitting

### LINKED ISSUE #35492: GPU particles don't work without disable z
3.2.rc2 and alpha3 or earlier on 3.1 stable it works 

Windows 10

Particles do not work without putting disable z on.
3.2.rc2
bug

3.1 stable
bug

Just add particle put some mesh on pass 1 and add process material.

### PR DESCRIPTION
**Pull request by zxcvdev**
Should fix #35492 , fix #30906 .

### CODE REVIEW

File: scene/resources/particles_material.cpp [hunk 1]
```diff
@@ -316,14 +316,17 @@ void ParticlesMaterial::_update_shader() {
 
 	if (flags[FLAG_DISABLE_Z]) {
 
-		code += "		float angle1_rad = atan(direction.y, direction.x) + rand_from_seed_m1_p1(alt_seed) * spread_rad;\n";
+		code += "		float angle1_rad = rand_from_seed_m1_p1(alt_seed) * spread_rad;\n";
+		code += "		angle1_rad += direction.x != 0.0 ? atan(direction.y, direction.x) : sign(direction.y) * (pi / 2.0);\n";
```
Comment (akien-mga) [inline scene/resources/particles_material.cpp]: This makes the previous statement unused.

Comment (akien-mga) [reply scene/resources/particles_material.cpp]: Nevermind, I misread.

**Comment by akien-mga** [comment]
The bug originates in #26613, CC @KoBeWi.
Might be worth reviewing the CPU Particles{,2D} code too for potential issues (`atan2` seems to handle `x == 0` fine, as long as `y != 0`).

File: scene/resources/particles_material.cpp (hunk 1 above)
Comment (zxcvdev) [reply scene/resources/particles_material.cpp]: Do you mean in the conditional, so `atan(direction.y, direction.x)`? If you set a direction x=0.5, y=1 (z is ignored because disable z flag) for example, it gets used.

Comment (akien-mga) [reply scene/resources/particles_material.cpp]: I missed that the line used `+=` operator, and though it was `=`, thus replacing the previous definition.

**Comment by clayjohn** [comment]
I wonder if something similar could be done to fix https://github.com/godotengine/godot/issues/30340 which also comes from #26613

**Comment by zxcvdev** [comment]
@clayjohn I pushed a fix for #30340 in this [branch](https://github.com/zxcvdev/godot/commit/7e56a37d2dbf7c00826a5fb150009c359dcf27e4) which builds upon the code in this PR.

Setting the direction of particles should behave as expected with that fix, including when the direction is Vec3(x != 0, y != 0, 0).

Not sure if it would be considered breaking/changing existing projects though, since the behavior of particles when the direction is Vec3(x != 0, y != 0, 0) gets changed (to the correct behavior). So let me know if I should create another PR or wait for this one to be reviewed.

**Comment by clayjohn** [comment]
@zxcvdev Looks like a step in the direction. But not sure that it solves the issue in #30340. Copying your code into a test scene, I can still reproduce the issue. 

The issue doesn't just occur when a given direction is 0. It occurs whenever Y is different from 0, regardless of the values of X or Z.

**Comment by zxcvdev** [comment]
@clayjohn You're right, my bad. It only solves the issue where the X direction was ignored when Y != 0 and Z = 0, not the incorrect spread thing of #30340 .

**Comment by clayjohn** [comment]
That's fine. :) It should be included in this PR. We can look into the solution for #30340 later.

**Comment by zxcvdev** [comment]
Amended to include additional minor fix as mentioned.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.1.
