### PR TITLE
Filesystem and Visual Script Members delete key fix

### LINKED ISSUE #14568: Inconsistent behavior of delete key
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7 64bits, Godot 3.0 beta1

**Issue description:**
- Clicking on a node and pressing "delete" shows the confirmation window for deleting that node
- Clicking on a key frame in the Animator timeline and pressing "delete" deletes said key frame
- *However*, clicking on a file in the filesystem panel and pressing "delete" shows the confirmation window for deleting the **node** that's currently selected on the scene panel rather than a confirmation window for the selected **file**. 

This behavior is inconsistent and unexpected being that Godot has an otherwise pretty standard UI/UX and can lead to the user accidentally deleting nodes while intending to delete files.

### PR DESCRIPTION
**Pull request by kitbdev**
Fixes #14568
Adds Keyboard shortcuts.
In the Filesystem allows Delete (Delete), Duplicate (Cmd+D), and Copy Node Path (Cmd+C) on files 
In the Visual Script Editor's Members area allows Delete (Delete) and Edit (Cmd+E) on variables, functions, and signals

### CODE REVIEW

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -1738,6 +1757,10 @@ FileSystemDock::FileSystemDock(EditorNode *p_editor) {
 	editor = p_editor;
 	path = "res://";
 
+	ED_SHORTCUT("filesystem_dock/copy_node_path", TTR("Copy Node Path"), KEY_MASK_CMD | KEY_C);
+	ED_SHORTCUT("filesystem_dock/duplicate", TTR("Duplicate"), KEY_MASK_CMD | KEY_D);
```
Comment (sudoio) [inline editor/filesystem_dock.cpp]: I believe you should use `TTR("Copy Path")` and `TTR("Duplicate..")` here, as seen in:
- https://github.com/godotengine/godot/blob/34c988cfa92f19c232b65990704816ba1c7d2622/editor/filesystem_dock.cpp#L1603
- https://github.com/godotengine/godot/blob/34c988cfa92f19c232b65990704816ba1c7d2622/editor/filesystem_dock.cpp#L1605

File: modules/visual_script/visual_script_editor.cpp [hunk 2]
```diff
@@ -3108,9 +3140,11 @@ void VisualScriptEditor::_member_rmb_selected(const Vector2 &p_pos) {
 
 		member_type = MEMBER_SIGNAL;
 		member_name = ti->get_text(0);
-		member_popup->add_icon_item(edit_icon, TTR("Edit Signal"), MEMBER_EDIT);
+		member_popup->add_icon_shortcut(edit_icon, ED_GET_SHORTCUT("visual_script_editor/edit_member"), MEMBER_EDIT);
+		member_popup->set_item_text(member_popup->get_item_count() - 1, "Edit Signal");
 		member_popup->add_separator();
-		member_popup->add_icon_item(del_icon, TTR("Remove Signal"), MEMBER_REMOVE);
+		member_popup->add_icon_shortcut(del_icon, ED_GET_SHORTCUT("visual_script_editor/delete_selected"), MEMBER_REMOVE);
+		member_popup->set_item_text(member_popup->get_item_count() - 1, "Remove Signal");
```
Comment (sudoio) [inline modules/visual_script/visual_script_editor.cpp]: Why you removed the localization `TTR()`?
Lines [`3121`](https://github.com/godotengine/godot/pull/15379/files/2f97af36cbde5379c6b739b4f2dc419fa38fc5bb#diff-bc4de62b8d91eb9cc820c6cce706d8b3R3121), [`3131`](https://github.com/godotengine/godot/pull/15379/files/2f97af36cbde5379c6b739b4f2dc419fa38fc5bb#diff-bc4de62b8d91eb9cc820c6cce706d8b3R3131), [`3134`](https://github.com/godotengine/godot/pull/15379/files/2f97af36cbde5379c6b739b4f2dc419fa38fc5bb#diff-bc4de62b8d91eb9cc820c6cce706d8b3R3134), [`3144`](https://github.com/godotengine/godot/pull/15379/files/2f97af36cbde5379c6b739b4f2dc419fa38fc5bb#diff-bc4de62b8d91eb9cc820c6cce706d8b3R3144), [`3147`](https://github.com/godotengine/godot/pull/15379/files/2f97af36cbde5379c6b739b4f2dc419fa38fc5bb#diff-bc4de62b8d91eb9cc820c6cce706d8b3R3147).

Comment (ianb96) [reply modules/visual_script/visual_script_editor.cpp]: My bad, those were supposed to be deleted since they don't actually work.
