### PR TITLE
C# scripts reload in editor fixed

### LINKED ISSUE #48590: C# Tool-/EditorScript can only be run successfully once from script editor (ctrl+shift+x).
**Godot version:**
```
Godot Engine v3.3.1.rc.mono.custom_build.476bc5191
commit 476bc5191bafcdea99e918100394479c06f0e5b4 (HEAD -> 3.3, origin/3.3)
Author: Tomasz Chabora <kobewi4e@gmail.com>
Date:   Fri Mar 26 14:10:41 2021 +0100
    Save project after opening
...
```
also tested on
```
Godot Engine v3.3.stable.mono.official - https://godotengine.org
```

**OS/device including version:**
```
Windows 10
Visual Studio 2017 - Found MSVC compiler: amd64
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Mono JIT compiler version 6.12.0 (Visual Studio built mono)
```

**Issue description**
I'm currently evaluating Godot+Mono for porting over a project that comes with a lot of C# code and I'm taking a closer look at procedural content creation in the editor through c#-based tool-scripts. Unfortunately I hit a wall when it comes to reliably running C# based tool-scripts. I can run them successfully once and then i need to restart the editor to make them work again. Comparing this to GDScript based tool-scripts, this seems clearly broken.

Here are the specifics based on a minimal repro-sample I include at the end of this post:

I have 2 tool editorscripts, one GDscript and one C# script.
I can run the GDScript from the script-editor (ctrl+shift+x) without problems multiple times and everything works as expected.
I can run the C# script from the script-editor (ctrl+shift+x) exactly once. Starting with the second run the editor prints:
```
ERROR: CSharpScript::reload: Condition "!p_keep_state && has_instances" is true. Returned: ERR_ALREADY_IN_USE
   At: modules\mono\csharp_script.cpp:3160
```

Upon further investigation & after reviewing the contents of the instances container [here](https://github.com/godotengine/godot/blob/3.3/modules/mono/csharp_script.cpp#L3157), I found that there is an EditorScript owner left over which prevents the script from reloading and throwing the above mentioned error. 

My suspicious is that this could be due to an edge-case or even a leak concerning c# editor-scripts that fell through the cracks so far. Possibly related to the script-editor itself. 

Before I start hacking away at this to see if this could be some low-hanging fruit, it still requires a lot of domain knowledge concerning the C# module that I don't have right now. So, I'd love to have your thoughts and input, maybe together we can easily zero down on this further.

**Steps to reproduce:**
1. Open the supplied project "Script Debug"
2. On the lower left in the resource-browser, double click `tool_test.gd` to open it in the script-editor
3. (ctrl+shift+x) to run the script at least 2 times and see the prints in the editor console:
```
Hello from tool_test.gd
Hello from tool_test.gd
```
4. On the lower left in the resource-browser, double click `tool_test.cs` to open it in the script-editor
5. Run a C# build: "MSBuild->Build Solution"
6. In the script-editor (ctrl+shift+x) to run the c# script at least 2 times and see the prints in the editor console:
```
Hello from tool_test.cs
ERROR: CSharpScript::reload: Condition "!p_keep_state && has_instances" is true. Returned: ERR_ALREADY_IN_USE
   At: modules\mono\csharp_script.cpp:3160
```

**Minimal reproduction project:**
[ScriptDebug.zip](https://github.com/godotengine/godot/files/6448002/ScriptDebug.zip)

### PR DESCRIPTION
**Pull request by Germanrc**
Co-authored-by: Michael Bickel <mib@developium.net>

This fixes the problem when trying to run the same script more than once in the editor (see #48590). 
Originally started by in @dazKind in #48627. Changes were required to the merge the PR but unfortunatly he did not have the time to make them and the problem was never fixed. So I made the changes that were asked in his PR.

*Bugsquad edit:* Fixes #48590.

### CODE REVIEW

File: modules/mono/csharp_script.cpp [hunk 1]
```diff
@@ -3117,13 +3119,10 @@ MethodInfo CSharpScript::get_method_info(const StringName &p_method) const {
...
 Error CSharpScript::reload(bool p_keep_state) {
-	bool has_instances;
-	{
-		MutexLock lock(CSharpLanguage::get_singleton()->script_instances_mutex);
-		has_instances = instances.size();
-	}
-
-	ERR_FAIL_COND_V(!p_keep_state && has_instances, ERR_ALREADY_IN_USE);
+	
+	if(!reload_invalidated) return OK;
```
Comment (Calinou) [inline modules/mono/csharp_script.cpp:3123]: To follow the new code style guidelines, don't use single-line `if` statements, add braces and remove the blank line at the beginning:

```suggestion
	if (!reload_invalidated) {
		return OK;
	}
```

File: modules/mono/csharp_script.cpp [hunk 2]
```diff
@@ -3117,13 +3119,10 @@ MethodInfo CSharpScript::get_method_info(const StringName &p_method) const {
...
+	
+	reload_invalidated = false; /* In the case of C#, reload doesn't really do any script reloading. That's done separately via domain reloading. */
```
Comment (Calinou) [inline modules/mono/csharp_script.cpp:3125]: We prefer `//` comments to `/* */` comments:

```suggestion
	// In the case of C#, reload doesn't really do any script reloading.
	// That's done separately via domain reloading.
	reload_invalidated = false;
```

**Review by Calinou — DISMISSED** [review]

**Comment by Germanrc** [comment]
Done! Code style should be fixed now.

**Review by neikeq — APPROVED** [review]

**Comment by akien-mga** [comment]
Looks good to me, but maybe you could amend the commit message to remove the mention to clang-format - passing style checks is the rule, not the exception, so is not worth mentioning in the commit message.

**Comment by Germanrc** [comment]
Any additional changes needed to merge this PR? It has been a few days since I commited the required changes. I am guessing this is several commits behind the official repo branch by now.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

This should likely be changed in `master` too?

**Comment by Germanrc** [comment]
Yes. I did not use master branch because C# is quite unstable right now, but it would be nice to have the fix in godot 4 too.

**Comment by neikeq** [comment]
Whoops, I didn't realize this was made against the 3.x branch. It's needed in master too, but no hurries. I'll add it to my list just in case to not forget.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.4.
