### PR TITLE
Fix Android export failing with custom keystores and no JDK setup in the OS environment

### LINKED ISSUE #94815: Android export failing with custom keystores and no JDK setup in the OS environment
### Tested versions

- Reproducible in:  v4.3.rc1.official [e343dbbcc](https://github.com/godotengine/godot/commit/e343dbbcc1030f04dc5833f1c19d267a17332ca9)
- Tested on: Windows 11 Pro, Version 23H2, Build 22631.3880

### System information

Windows 11 - Godot  v4.3.rc1.official

### Issue description

Export for Android fails on Windows if there is no path to a JDK set in the PATH environment variable and debug and/or release keystores have been set in the options dialg of the export window.
The error messages printed in the console looks like this:
```
Could not create child process: keytool -list -keystore ******** -storepass ******** -alias ********
Error: There was a problem validating the keystore username and password
```

The reason for this is that the static function **has_valid_keystore_credentials** in ```platform/android/export/export_plugin.cpp``` runs the hardcoded **"keytool"** command instead of using **get_keytool_path** to get the correct path that uses the ```export/android/java_sdk_path``` setting.

### Steps to reproduce

Tested on Windows

1. Ensure your PATH variable doesn't contain any JDK binary directoy
2. In Godot open ```Project > Export ...``` and select an Android export
3. Specify a Debug and/or Release keystore
4. Execute ```Export Project...```

### Minimal reproduction project (MRP)

Should be reproducable with any project

### PR DESCRIPTION
**Pull request by ChrisBase**
* Fixes: https://github.com/godotengine/godot/issues/94815

## Test environment
Godot Engine v4.3.rc1.official
Windows 11 Pro, Version 23H2, Build 22631.3880

## Issue
Export for Android fails on Windows if there is no path to a JDK set in the PATH environment variable and debug and/or release keystores have been set in the options dialg of the export window.  
This issue should also affect other operating systems but i have only tested in windows.
The error message printed in the console looks like this:

```
Could not create child process: keytool -list -keystore ******** -storepass ******** -alias ********
```

## Fix
The reason for this is that the static function **has_valid_keystore_credentials** in ```platform/android/export/export_plugin.cpp``` runs the hardcoded **"keytool"** command instead of using **get_keytool_path** to get the correct path that uses the ```export/android/java_sdk_path``` setting.  
The proposed fix replaces all occurrences of the hardcoded **"keytool"** with a string returned by **get_keytool_path**.

### CODE REVIEW

**Comment by AThousandShips** [comment]
Please open a dedicated bug report to track this properly

**Comment by ChrisBase** [comment]
Related issue: #94815

File: platform/android/export/export_plugin.cpp [hunk 1]
```diff
@@ -2340,6 +2340,7 @@ static bool has_valid_keystore_credentials(String &r_error_str, const String &p_
 }
 
 bool EditorExportPlatformAndroid::has_valid_username_and_password(const Ref<EditorExportPreset> &p_preset, String &r_error) {
+	String keytool = get_keytool_path();
```
Comment (m4gr3d) [inline platform/android/export/export_plugin.cpp:2343]: Can we use `get_keytool_path()` directly in `has_valid_keystore_credentials` instead of passing it as an argument?

Comment (ChrisBase) [reply platform/android/export/export_plugin.cpp:2343]: Not without changing the signature of **has_valid_keystore_credentials** which currently is static, so no access to the member function get_keytool_path() is given.

Comment (m4gr3d) [reply platform/android/export/export_plugin.cpp:2343]: `get_keytool_path()` is also `static` but the issue seems to be because `has_valid_keystore_credentials` is not declared in the header file. Adding that declaration should resolve the access issue.

Comment (ChrisBase) [reply platform/android/export/export_plugin.cpp:2343]: I missed ```get_keytool_path()``` beeing ```static```. There's not even a need for declaring ```has_valid_keystore_credentials```  in the header file. Calling ```EditorExportPlatformAndroid::get_keytool_path()``` (added class specifier) is sufficient.  
I will amend the pull request accordingly.

**Review by m4gr3d — APPROVED** [review]
Looks good, thanks for the fix!

**Comment by ChrisBase** [comment]
> Looks good, thanks for the fix!
It is a pleasure to support such a great project!

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
