### PR TITLE
Don't try to initialize empty NativeLibrary

### LINKED ISSUE #29162: Editor crashes when attempting to make a built-in nativescript unique
**Godot version:**
Godot_v3.1.1-stable_mono_win64

**OS/device including version:**
Microsoft Windows 10 Education

**Issue description:**
Creating a built-in native script and attempting to make unique causes the Godot editor to crash. (Not much reason for doing it at the time)

**Steps to reproduce:**
* Open or create a project
* Attach a GDNative script to a node, or the scene's node
  * Set `Built-in Script` on from within the prompt
* Select script property on node, choose `Make Unique`
  * This is where the crash occurs

**Minimal reproduction project:**
Here is an example project: [New Project.zip](https://github.com/godotengine/godot/files/3218854/New.Project.zip)
Open the scene, and in the child Node, attempt to make the native script unique.

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #29162

It happened because the NativeScript was trying to initialize a null library.

### CODE REVIEW

File: modules/gdnative/nativescript/nativescript.cpp [hunk 1]
```diff
@@ -119,20 +119,24 @@ String NativeScript::get_class_name() const {
 
 void NativeScript::set_library(Ref<GDNativeLibrary> p_library) {
 	if (!library.is_null()) {
-		WARN_PRINT("library on NativeScript already set. Do nothing.");
+		WARN_PRINT("Library in NativeScript already set. Do nothing.");
 		return;
 	}
 	library = p_library;
-	lib_path = library->get_current_library_path();
+	if (library.is_valid()) {
```
Comment (akien-mga) [inline modules/gdnative/nativescript/nativescript.cpp]: Shouldn't we do
```
if (p_library.is_null()) {
    return;
}
```
before assigning an empty library to `library` instead?

Comment (KoBeWi) [reply modules/gdnative/nativescript/nativescript.cpp]: That makes sense...

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
