### PR TITLE
GLTF: Read material texture "texCoord" property on import

### LINKED ISSUE #80858: GLTF mesh primitive texCoord property ignored
### Godot version

4.1.1-stable

### System information

Windows 10

### Issue description

According to the [GLTF 2.0 specification on materials](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_013_SimpleTexture.md#the-textured-material-definition), individual textures can specify a UV layer to use by providing a texCoord property. Godot currently does not read this property and always assumes UV layer 1 should be used. This results in incorrect rendering when importing GLTF models that have textures that use any UV channel besides 1.

The below image shows the SheenChair GLTF sample model after being imported into Godot 4.1.1-stable:
image

### Steps to reproduce

* Download the SheenChair GLTF sample model.
* Create a new Godot project using any renderer.
* Import the GLTF model into your project.
* Observe incorrect rendering.

### Minimal reproduction project

[GLTFTexCoordMinimalReproduction.zip](https://github.com/godotengine/godot/files/12398882/GLTFTexCoordMinimalReproduction.zip)

### LINKED ISSUE #93884: UV Map Node Ignored in GLTF/GLB Import
### Tested versions

- Reproducible in 4.2.2 stable

### System information

Windows 10 - Godot v4.2.2.stable - Vulkan (Forward +) - dedicated GPU

### Issue description

The UV Map node is ignored in materials in imported gltf/glb models. Godot instead defaults to the first UV Map for all materials.

image

From left to right (Godot, Blender, 3D Viewer):
image
The above image shows Blender and 3D Viewer rendering the materials using the correct UV map, while Godot is ignoring the assigned UV Map and using the default.

When the UV Map node is removed from the materials, Blender renders the model the same way as it shows up in Godot:
image
image

### Steps to reproduce

1. Create model with two materials.
2. Create a second UV Map and assign it to one of the materials.
3. Save scene as gltf/glb and import into Godot.

### Minimal reproduction project (MRP)

From left to right (Godot, Windows 3D Viewer):
image

The right image correctly shows the UVMap.001being used for the GreenMaterial.
image

[cube-2uv-materials.zip](https://github.com/user-attachments/files/16078054/cube-2uv-materials.zip)

### LINKED ISSUE #100172: UV Map corruption on GLB import
### Tested versions

Godot 4.3

### System information

Forward+, Windows 10, I3 4190

### Issue description

When importing GLB models into Godot, textures seem stretched or corrupted.

Model in Blender(imported GLB)
Image

Model in Godot Editor
Image

btw materials aren`t corrupted:
Image
Image
Image

### Steps to reproduce

Import model into the editor and see corruption of UV

[axe.zip](https://github.com/user-attachments/files/18052186/axe.zip)

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by aaronfranke**
Fixes #80858 and fixes #93884 and fixes #100172 to the extent which is possible in the glTF code.

Supersedes PR #80522, supersedes PR #106786.

Godot uses UV1 for the base color, normal, and metallic/roughness. It can also have occlusion and emission on either UV1 or UV2. The glTF spec [allows any texture to use any UV map](https://github.com/KhronosGroup/glTF/blob/main/specification/2.0/schema/textureInfo.schema.json), so not everything in glTF is possible in Godot.

In the current master, the glTF import code does not read this property, and expects that every texture is on UV1. We can do better than that. With this PR, the glTF import code will do its best to consider the UV preferences of material textures, allowing for many more configurations such as color+normal+metallic on a different texCoord, or occlusion/emission on a separate texCoord. When the code encounters a configuration not supported by Godot, it will print a warning.

Here is the test file from #93884. Left is current master, right is with this PR.

Screenshot 2024-09-09 at 2 31 49 AM

Here is the test file from #80858.

Screenshot 2024-10-09 at 9 08 48 PM

This PR also handles the case of exporting materials with emission and/or occlusion on UV2, while previously they always exported as if they were on UV1. The code for exporting is much more straightforward than importing, the only changes are in the `_serialize_materials` function.

While not all glTF files will have their UV maps perfectly imported into Godot, this should be enough to ensure that exporting from Godot and importing back into Godot will preserve any UV2 map usage.

Also, I renamed some local variables for readability (ex: `p` -> `mesh_prim_dict`, `sgm` -> `spec_gloss_ext_dict`).

I'm labeling this as an enhancement because support for UV2 in glTF is a new feature, but arguably it's a bug because this is a case of Godot not following the glTF specification.

### CODE REVIEW

**Comment by fire** [comment]
I am in favour of the proposal. Did not technical review yet.

**Review by fire — COMMENTED** [review]
@aaronfranke what's a prose version of the algorithm for picking the coordinates?

**Comment by aaronfranke** [comment]
@fire The prose version is that we want to read what's in the file, except that to fit within Godot's material system, we can only read at most two UVs, and the second UV can only be used for certain things. Therefore, we prefer reading the most important UV maps first to provide the best mapping, starting with the base color / albedo texture, and continuing on to less important UV maps.

**Comment by fire** [comment]
So like a greedy algorithm that has 2 slots and from the inputs we fit the `base color / albedo texture` to the first slot and then the others.

**Comment by lyuma** [comment]
I am not personally in favor of this proposal as is. In short, this creates a few hardcoded rules which impact the mesh depending on a series of conditions, and this logic will never be able to change without breaking compatibility.

Most importantly, I couldn't find the import option to control this. Having an option to control this behavior is an absolute necessity. For example, the change may alter the mesh channels of content already imported into Godot, perhaps using a custom ,tres material.

The thing I am worried about is that this unconditionally changes the order of the UV channels, based on materials which may even be replaced or swapped during the import process.

In my experience, it is common for the UV channels to have semantic meaning, for example TEXCOORD_1 is often used for lightmapping while TEXCOORD_0 is conventionally used for albedo. This flips it around, so that the material attached to a particular mesh determines the UV channels to more closely match with this semantic. While there is some sense in this, it means that the mesh data will be drastically affected by the presence of various settings on the materials.

For example, if the glTF is exported without materials, or perhaps if the user changes some of their material nodes in Blender before export, the order of mesh channels in Godot will be unexpectedly flipped, and the cause will be difficult to diagnose, for example depending on the presence of albedo or emission in blender nodes which may not even be used in Godot.

Still, I might be swayed to be okay with this as an import option.

**Comment by aaronfranke** [comment]
@lyuma Currently, meshes are plainly broken on import if they are using different UV maps from what you mention is the common convention. I'm not inclined to keep adding more and more import options to preserve broken behavior. I prefer to just have the correct behavior be the only option.

If users are expecting UV maps to be preserved as-is, that is already not the case. Godot doesn't support more than 2 UV maps, so any others are discarded. Furthermore, currently UV2 is always unused on import, and can only be used with custom materials, this PR fixes that.

In my opinion, the primary focus should be to ensure that the glTF's intended appearance is correct in Godot, not in keeping texCoord 0 mapped to Godot's UV1. I don't believe it is worth supporting import of a file where the user explicitly wants Godot to use the wrong UV map. To me it just seems like nonsense behavior that there would be an option that says "yes, import me with the wrong visuals" for the sake of always using the first UV map as the used one. It's better to just always use the UV map that the glTF file says is the correct UV map.

**Comment by huwpascoe** [comment]
I agree with what this PR is doing, the GLTF should be visually represented in engine as closely as possible, even if that means there are no guarantees of how data is mapped.

> The thing I am worried about is that this unconditionally changes the order of the UV channels, based on materials which may even be replaced or swapped during the import process.

Yes, sometimes you do want explicit control over how things are mapped: https://github.com/godotengine/godot/pull/97756.
Perhaps rather than a script extension, it could be fully realized as a property group to override default behavior?
image

**Comment by aaronfranke** [comment]
Updated to account for PR #94165, supporting animated UV maps on textures on both import and export to the best extent possible with Godot's material system. I tested UV map animation on the red chair and it works, and also tested the animation pointer test file again just in case and that also works.

**Comment by fire** [comment]
I would ideally want to see something like https://github.com/godotengine/godot/pull/96748#issuecomment-2446638473, do you think it's possible for us to do in this or another pr?

**Comment by aaronfranke** [comment]
@fire There is PR #97756 from @huwpascoe which implements the ability to import custom attributes.

**Comment by huwpascoe** [comment]
> Perhaps rather than a script extension, it could be fully realized as a property group to override default behavior?

I've determined that the UI approach is just too much of a mess for what is a technical feature. So I'll be moving forward with the original plan to add the method to DocumentExtension.

How do you want to coordinate this @aaronfranke? This PR is older so I'd probably say get this merged first and then I can add the _remap overrides where needed?

**Review by huwpascoe — APPROVED** [review]
Works as expected, both import and export.

image

The warning messages are a very nice addition and explains clearly why an import fails.

I couldn't find any problems with the source. 👍

**Comment by lyuma** [comment]
There was some opposition to this change in the rendering meeting, and I just wanted to comment further on this and also what I think is a better path forward.

First, one of the reasons we are encountering so much trouble handling texcoords is due to limitations on the standard material: basically, the standard material only permits certain texture maps on UV and UV2, and there are no other combinations... Therefore, this change is forced to remap texcoord channels to 0 and 1 so that they can be correctly assigned to the material.

I have some questions how common this issue really is, and it sounds more like making compatibility with marketplace assets than supporting a workflow for game art.

With that, I see two diverging usecases for the asset importer (And accordingly perhaps an import setting or some way to tell Godot which user you are):
1. For game art designed with import to Godot in mind, this content will already be designed to support StandardMaterial and will not want UVs remapped.
2. For marketplace assets or when full compatibility with glTF is desired, rather than conforming to Godot material conventions.

So given that description, for usecase 2, we have the goal of trying to render a glTF asset as accurately as possible, but we are not necessarily required to use StandardMaterial to do so. In this case, it might interesting to create material nodes with VisualShader that best mimics the visual representation in glTF, similar to how Blender works.

The downside of this is it means it will require more complexity to export the material, but it should be possible given that Blender is also able to export material graphs to glTF.

This PR is more like a baking approach where instead of creating a custom material graph, we are reordering UVs or baking textures to fit on the first two UV channels, which will work for some glTF materials but not in all cases. As I said before, I can be swayed if there is an import option, but this approach still feels a little bit messy: it will improve render compatibility with some glTF files but not 100%.

I think it might be worth considering a baking approach where when multiple texcoords are used, Godot can bake them to a single texcoord channel, which can make it look correct (although maybe a bit lower resolution), and this will also improve performance on mobile, which struggles when multiple UVs are in use at once.

And finally, the approach in godotengine/godot-proposals#10892 could be combined with a way for the user to manually select custom channels or UVs. Though there's still a problem that the StandardMaterial is too limited to use CUSTOM for textures.

**Comment by huwpascoe** [comment]
I have an idea that could allow this to be implemented as a script/plugin. I'll update my PR soon.

**Comment by tlobig** [comment]
as for the question whether this is an unusual request: no. I'm currently trying to establish an art pipeline from Blender to Godot for a VR game where I need lightmaps as SDFGI is very broken for VR :-/ - LightmapGI doesn't have the same quality as what I can do with a Blender addon and requires it's own painful workaround.

I'm a bit stuck as with Blender I get 2 UV maps and Godot doesn't load these properly as standard material:
grafik

I approximated what it might look like hand fiddling a visual shader for each of these three objects (disregard overall quality, important thing for me was the shadow of the small cube)
grafik

but this is not suitable for an art pipeline. I will see if I can change the Blender side of things to merge everything into the diffuse texture, but this also means I'm less versatile with only one UV map.

so I was quite pumped to see there is a PR fixing MY issue - lo and behold, it does fix it:
grafik

Therefore I would love to see this PR or a version of it to make it to 4.4

**Comment by lyuma** [comment]
@tlobig I'd like to understand more on how the exported file looks and how the blender nodes are set up, to understand better how this change helps.

Since you mention using Blender to create a baked lightmap, is it done through multiplying two diffuse textures? Or is the albedo being baked together with the lighting to a second diffuse texture?

My understanding is with this change, Godot will still only pick a single UV, but it might pick UV2 instead of UV1. Even if it looks better to you, I suspect there is still something it's getting wrong. (Or if not, it should be possible to replicate this on vanilla godot by swapping the order of the UV maps in Blender).

**Comment by tlobig** [comment]
@lyuma good instincts. I used the lightmap addon "The Lightmapper" (https://github.com/Naxela/The_Lightmapper), and it generates a second UV map automagically and then sets up a texture node using this uv map as input to mix (muliply) the diffuse color. The addon is supposed to be helping setting things up for game engines, so not just for Blender. Yet the standard material is too limited and we would need more involved import options to deal with the problem.

 Simply baking (everything to diffuse/albedo) in Blender works, though the result is not as nice as it could be.
That's the TL;DR

Here is a minimal scene, I added the baked result and what the lightmapper generates (combined light (direct+indirect) + AO)
[minimal_blender_scene.zip](https://github.com/user-attachments/files/18239964/minimal_blender_scene.zip)
grafik

red cube's color is lost in conversion, bottom cube has no material before the lightmapper does it's thing and the textured cube looses the texture after import to Godot (this PR) 

I might be missing a few of the finer points.

File: modules/gltf/gltf_document.h [hunk 1]
```diff
@@ -107,6 +107,7 @@ class GLTFDocument : public Resource {
 	static String _gen_unique_name_static(HashSet<String> &r_unique_names, const String &p_name);
 
 private:
+	static void _append_khr_texture_transform_ext_json_pointer(PackedStringArray &p_split_json_pointer, const String &p_texture_name, const bool p_is_offset);
```
Comment (AThousandShips) [inline modules/gltf/gltf_document.h:117]:
```suggestion
	static void _append_khr_texture_transform_ext_json_pointer(PackedStringArray &p_split_json_pointer, const String &p_texture_name, bool p_is_offset);
```

File: modules/gltf/gltf_document.cpp [hunk 2]
```diff
@@ -5323,6 +5427,17 @@ Ref<GLTFObjectModelProperty> GLTFDocument::import_object_model_property(Ref<GLTF
 	return ret;
 }
 
+void GLTFDocument::_append_khr_texture_transform_ext_json_pointer(PackedStringArray &p_split_json_pointer, const String &p_texture_name, const bool p_is_offset) {
```
Comment (AThousandShips) [inline modules/gltf/gltf_document.cpp:5344]:
```suggestion
void GLTFDocument::_append_khr_texture_transform_ext_json_pointer(PackedStringArray &p_split_json_pointer, const String &p_texture_name, bool p_is_offset) {
```

File: modules/gltf/gltf_document.cpp [hunk 3]
```diff
@@ -3049,109 +3072,153 @@ Error GLTFDocument::_parse_materials(Ref<GLTFState> p_state) {
...
 					if (orig_texture.is_valid()) {
 						spec_gloss->spec_gloss_img = orig_texture->get_image();
 					}
 				}
+				if (spec_gloss_texture.has("texCoord")) {
+					const int spec_gloss_tex_coord = spec_gloss_texture["texCoord"];
+					if (primary_texture_coord == -1) {
+						primary_texture_coord = spec_gloss_tex_coord;
+					} else if (spec_gloss_tex_coord != primary_texture_coord) {
+						WARN_PRINT("glTF: File uses different UV maps for specular/glossiness texture and diffuse texture. Godot does not support this. Using diffuse texture's UV map only and ignoring specular/glossiness texture's UV map.");
```
Comment (AThousandShips) [inline modules/gltf/gltf_document.cpp]:
```suggestion
						WARN_PRINT("glTF: File uses different UV maps for specular/glossiness and diffuse textures. Godot does not support this. Using diffuse texture's UV map only and ignoring specular/glossiness texture's UV map.");
```

File: modules/gltf/gltf_document.cpp [hunk 4]
```diff
@@ -3049,109 +3072,153 @@ Error GLTFDocument::_parse_materials(Ref<GLTFState> p_state) {
...
+					if (!metal_rough_dict.has("roughnessFactor")) {
 						material->set_roughness(1);
 					}
 				}
+				if (metal_rough_tex_dict.has("texCoord")) {
+					const int metal_rough_tex_coord = metal_rough_tex_dict["texCoord"];
+					if (primary_texture_coord == -1) {
+						primary_texture_coord = metal_rough_tex_coord;
+					} else if (metal_rough_tex_coord != primary_texture_coord) {
+						WARN_PRINT("glTF: File uses different UV maps for metallic/roughness texture and base color texture. Godot does not support this. Using base color texture's UV map only and ignoring metallic/roughness texture's UV map.");
```
Comment (AThousandShips) [inline modules/gltf/gltf_document.cpp]:
```suggestion
						WARN_PRINT("glTF: File uses different UV maps for metallic/roughness and base color textures. Godot does not support this. Using base color texture's UV map only and ignoring metallic/roughness texture's UV map.");
```

File: modules/gltf/gltf_document.cpp [hunk 5]
```diff
@@ -3164,12 +3231,25 @@ Error GLTFDocument::_parse_materials(Ref<GLTFState> p_state) {
...
+			if (emissive_tex_dict.has("texCoord")) {
+				int emissive_tex_coord = emissive_tex_dict["texCoord"];
+				if (unlikely(primary_texture_coord == -1)) {
+					primary_texture_coord = emissive_tex_coord;
+				} else if (emissive_tex_coord != primary_texture_coord) {
+					if (emissive_tex_coord == secondary_texture_coord || secondary_texture_coord == -1) {
+						secondary_texture_coord = emissive_tex_coord;
+						material->set_flag(BaseMaterial3D::FLAG_EMISSION_ON_UV2, true);
+					} else {
+						WARN_PRINT("glTF: File uses different UV maps for emission texture, occlusion texture, and primary texture (baseColor/normal/etc). Godot does not support this, it only supports up to two UV maps. Using occlusion texture's UV map only and ignoring emission texture's UV map.");
```
Comment (AThousandShips) [inline modules/gltf/gltf_document.cpp]:
```suggestion
						WARN_PRINT("glTF: File uses different UV maps for emission, occlusion, and primary textures (baseColor/normal/etc). Godot does not support this, it only supports up to two UV maps. Using occlusion texture's UV map only and ignoring emission texture's UV map.");
```

**Comment by fire** [comment]
As far as I know the disagreement from https://github.com/godotengine/godot/pull/96748?notification_referrer_id=NT_kwDNfkGxMTIzMTU4OTYxNzk6MzIzMjE#issuecomment-2561051652 is still active.

**Review by lyuma — COMMENTED** [review]
I know I've been negative about this PR, but on the plus side, improving compatibility with GLTF assets by default is good for the godot user experience, for most users who do not need custom shaders.

All of my objections are related to compatibility of materials between imports, and usage for custom shaders or other uses of mesh UVs. So the main limiter in my approving this change is the lack of a setting to turn this off.

Therefore, we proposed the following in the animation/asset metting:

Make the function to determine the `primary_texture_coord` a standalone function to isolate some of the complex logic and make the rest of the material remapping easier to read.

add an import enum setting shader_uv_mapping ("Preserve UV Mapping" / "StandardMaterial3D")
New meshes can use StandardMaterial3D. Existing files should be "Preserve UV Mapping" to avoid breaking compatibility.

(Eventually, our visual shader node idea could eventually be added as a third option (like "VisualShader") )

Users who wish to use custom shaders can now switch the setting back to Preserve UV Mapping.

I just have another comment: There's a usability issue that it will be difficult to change this setting *and* extract materials at the same time. Perhaps the Extract Materials dialog can also have this setting, but I would like to address this usability issue before merging this to make sure the workflow of assigning a custom material / shader is smooth.
One way to create such a workflow is to solve #107351 so we need to discuss this part further to see how that change interacts.

**Comment by aaronfranke** [comment]
As requested in today's @godotengine/asset-pipeline meeting, I made this feature optional:

Screenshot 2026-02-21 at 1 24 53 PM

The reason this is an enum instead of a boolean is to allow for future options to be added for more ways to handle this, such as @lyuma's idea of using a custom shader instead of StandardMaterial3D.

**Review by lyuma — APPROVED** [review]
Looks good.

It handles the common cases very cleanly and tracks the primary and secondary texcoord, finally using it in one place during parse_meshes.

We found a corner case during review if someone imports a model which uses non-default texcoords, and there is an animation that animates the texcoords, and the user has remapping enabled (default) and they then switch to Import as Animation Library, the generated animations will behave as if the user set Do Not Remap.

The amount of code to fix this edge case is too much given how rare it is, and the workaround would be to simply use Do Not Remap in the import settings or switch the animations to TEXCOORD_0.

The other corner case we discussed was if there is a normal map on texcoord 1, we could import it as a detail normal, but this will add complexity, so we should see if anyone reports this issue and has a MRP so we can test this with real data.

**Comment by Repiteo** [comment]
Thanks!
