### PR TITLE
VisualScriptEditor Fix in graph position calculation (do not skip zoom)

### LINKED ISSUE #49840: Adding new functions to visual script when zoomed out places them ' badly ' . .
### Godot version

Godot 3.3 . .

### System information

Windows 10

### Issue description

Had this problem many times before, when zoomed out, dragging a new function, or variable, it is placed wrong . . .

Now, visual script is looking mint, really cool . . These are some of last small bugs, only happens when zoomed out, it's a minor bug, but it does get annoying, esp. now Godot 4 appears to look better when zoomed out ( I have a custom font, but it's small, and still very readable, zoomed out ) . . It's like, are there any bugs left in visual script ?? Super - happy with the feature, atm, thx . . . :OO . . .

### Steps to reproduce

Uhhh, make a new visual script, make a variable, or new function . . Move it in, normal zoom, it just works, the more one zooms out, worse it gets . .

It's not really a bug, it's just bit annoying, and weird . . Anyway, Godot 4 Visual script is just amazing, nothing much left to complain about, except small bugs, like this, thx . . . .

### Minimal reproduction project

Uhh, just like above . . .

### PR DESCRIPTION
**Pull request by kleonc**
Calculations for converting in-editor position to in-graph position was made manually in many separate places, some of them didn't take zoom into account. Extracted that into seperate method.

Tested it briefly in `3.x`, seems to work. But more testing is welcomed before merging.

Fixes #49840 (and probably more zoom-related issues, e.g. before this PR it was possible to start dragging a node by clicking outside of it, with this PR it seems to no longer be the case).
Cherry-pickable `3.x`, `3.3`.

### CODE REVIEW

**Comment by DavidCambre** [comment]
Oh seeing this makes me happy.
I did a very similar thing in #49749 I have to admit this version is cleaner. Better readability etc.
I will let @fire merge this PR first then I will do a last rebase on my PR. That will provide the cleanest result.

Code seems good.
Tested The windows build its OK.
Only one request for @kleonc, do you have any id where the position is decided when you drag out from the sequence port?

image

It seems to set position on window zero or last position.

**Review by Gallilus — APPROVED** [review]

**Comment by kleonc** [comment]
> Only one request for @kleonc, do you have any id where the position is decided when you drag out from the sequence port?

After a little digging I think [here's the relevant part](https://github.com/godotengine/godot/blob/f00e3019984077a388ce7f117adb5483a8976016/modules/visual_script/visual_script_editor.cpp#L3121-L3163) (linked code includes this PR). As you can see it uses `port_action_pos` to determine the actual in-graph position. In the case you've mentioned `port_action_pos` [seems to be set here](https://github.com/godotengine/godot/blob/f00e3019984077a388ce7f117adb5483a8976016/modules/visual_script/visual_script_editor.cpp#L2954-L2978). And indeed [this condition](https://github.com/godotengine/godot/blob/f00e3019984077a388ce7f117adb5483a8976016/modules/visual_script/visual_script_editor.cpp#L2965) doesn't check for output sequence port count so `port_action_pos` might not being set properly. [In `3.x` it's being set unconditionally](https://github.com/godotengine/godot/blob/c045219869dfccb507cdc60eeb93953c8730d8de/modules/visual_script/visual_script_editor.cpp#L3372). Will try to fix this in a moment.

**Review by fire — APPROVED** [review]
Looks good. 

Thanks for reviewing @DavidCambre and @kleonc for working on it.

File: modules/visual_script/visual_script_editor.cpp [hunk 1]
```diff
@@ -3009,7 +2962,7 @@ void VisualScriptEditor::_graph_connect_to_empty(const String &p_from, int p_fro
 	if (!vsn.is_valid()) {
 		return;
 	}
-	if (vsn->get_output_value_port_count()) {
+	if (vsn->get_output_value_port_count() || vsn->get_output_sequence_port_count()) {
```
Comment (kleonc) [inline modules/visual_script/visual_script_editor.cpp:2965]: That's this additional change, please test if it fixes what @DavidCambre reported.

Comment (DavidCambre) [reply modules/visual_script/visual_script_editor.cpp:2965]: Tested. OK

**Review by Gallilus — APPROVED** [review]

**Comment by DavidCambre** [comment]
@fire I do not now ho to ask. Please merge? So I can work on the rebase for PR49749

**Comment by fire** [comment]
Thanks.

**Comment by akien-mga** [comment]
>  Cherry-pickable `3.x`, `3.3`.

This would need a dedicated PR for `3.x`, there are significant conflicts to handle.

**Comment by kleonc** [comment]
> 
> This would need a dedicated PR for `3.x`, there are significant conflicts to handle.

It's because of [this change](https://github.com/godotengine/godot/pull/49854#discussion_r657426335) since that changed condition is non-existant in `3.x` (as I've mentioned in [the comment above](https://github.com/godotengine/godot/pull/49854#issuecomment-867116048)). Not sure if that condition is neccessary at all but I'll add it in `3.x` too to sync that part with `master` (code involving `port_action_pos` (which is being changed conditionally in there) seems the same in both `master` and `3.x` so it shouldn't break anything).

**Comment by veryprofessionaldodo** [comment]
I think that this is still a problem. Currently building a plugin that uses a Visual Node system for dialogues, and I get this behaviour on `3.3.3.rc1` and `3.4.beta3`. Here's a [gif of it in action](https://gfycat.com/idealisticanyichthyostega).

Sorry to resurrect an old issue, I'll open a new one if it is more appropriate.

**Comment by kleonc** [comment]
@veryprofessionaldodo As [I've just mentioned in the Reddit thread where you're describing your issue](https://www.reddit.com/r/godot/comments/p523e2/graph_node_port_cant_be_selected_properly_and_its/h953xk5?utm_source=share&utm_medium=web2x&context=3): this PR is actually not related to your issue. So yes, please open a new issue. Also provided gif is a nice addition but it's much easier to investigate the issue having minimal reproduction project provided (please provide one when opening new issue).

**Comment by veryprofessionaldodo** [comment]
Hi there! It was actually my bad, and not related to this at all indeed. The problem was that I had a hidden AcceptDialog inside of the GraphEdit that was catching inputs, as it can be seen [here](https://gfycat.com/cluelessamazingdrake). Sorry for adding entropy, it's already fixed!
