### PR TITLE
Use 64-bit offset/loop points in `AudioStreamWAV`

### LINKED ISSUE #90957: Unsafe cast when loading WAV files
### Tested versions

4.2.1
4.3.dev5

### System information

Windows 10 x64

### Issue description

[There is](https://github.com/godotengine/godot/blob/master/editor/import/resource_importer_wav.cpp#L200)(link) unsafe cast from `uint32_t` to `int` 
```
frames = chunksize;
```

If you try to load WAV file with size more then INT_MAX (2147483647) you'll get `frames < 0`, and after [some lines of code](https://github.com/godotengine/godot/blob/master/editor/import/resource_importer_wav.cpp#L213)
user will get a not clear message 
> ERROR: Condition "p_size < 0" is true. Returning: ERR_INVALID_PARAMETER
   at: CowData<float>::resize (core/templates/cowdata.h:314)

Or, if workstation have small amout of RAM (8Gb)  - Godot also crash

As a partial solution you can add check like this after [this line](https://github.com/godotengine/godot/blob/master/editor/import/resource_importer_wav.cpp#L150) 
```
if (chunksize > INT_MAX) {
		ERR_FAIL_V_MSG(ERR_INVALID_DATA, "File too big.");
}
```
but it not well. May be better to constraint file size and with understandable message for Godot user.
WAV file can be 4Gb as `chunksize` is unsigned 32bit int [wiki ](https://en.wikipedia.org/wiki/WAV#:~:text=The%20WAV%20format%20is%20limited,record%20the%20file%20size%20header.), but in Godot data also stored in `Vector<float>`, and it require big amount of memory and mine 32Gb not enougth(I try to rebuild Godot changing `frames` type to `uint32_t` and got exception with `stosb` assembler instruction )

### Steps to reproduce

Try to import big WAV file, more then 2147483647 bytes

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by DeeJayLSP**
Closes #90957
Supersedes #91077 by allowing instead of denying.

`AudioStreamWAV` offset, loop begin and loop end have been changed to use `int64_t` instead of `int`. WAV files store the sample count using 32-bit, so it's virtually impossible for it to overflow. A cast from `uint32_t` to `int64_t` should be safe.

Additionally, every `Vector::resize()` call has been placed inside error macros.

This is very unlikely to happen as not everyone uses WAV files over 2GB, but doesn't hurt to fix anyway.

### CODE REVIEW

**Comment by DeeJayLSP** [comment]
cc @lyuma

**Review by lyuma — COMMENTED** [review]
So if I understand, the issue is that wav uses *unsigned* uint32, while Godot integers are signed when exposed in APIs (or when used in vectors). I think it makes sense....

A lot of my uncertainty comes down also to code style. For example, given that Vector.resize() returns an Error, is it better to store that in a variable, and then call `ERR_FAIL_COND_V(err, ...)` , or better to do it on one line as this code is written.

I would like @AThousandShips to take a look at this code and see if it's going in the right direction in terms of code quality + style. If she thinks it is good, and there's some way to verify that this fixes an issue (MRP / example case) then I think I'd be okay approving this change.

**Comment by AThousandShips** [comment]
So a few potential issues:
* Containers use signed sizes, so it's relevant to check for sizing issues, I'd say it might be better to use signed sizes unless impossible (realized it all uses 32 bit numbers for unsigned so that shouldn't be a problem)
* For putting functional code inside error macros that's something I've been wanting to discuss for our usage and style guides as I feel it'd be better to not put code that changes things inside macros in case we want to be able to remove the tests etc.

Will go over style, but from a glance I don't think there's anything significant beyond that

File: scene/resources/audio_stream_wav.cpp [hunk 1]
```diff
@@ -910,34 +911,34 @@ Ref<AudioStreamWAV> AudioStreamWAV::load_from_buffer(const Vector<uint8_t> &p_st
...
 	print_line("\tframes: " + itos(frames));
 	print_line("\tformat_channels: " + itos(format_channels));
 	print_line("\t16bits: " + itos(is16));
 	print_line("\trate: " + itos(rate));
-	print_line("\tloop: " + itos(loop));
+	print_line("\tloop: " + itos(loop_mode));
 	print_line("\tloop begin: " + itos(loop_begin));
 	print_line("\tloop end: " + itos(loop_end));
-	*/
+#endif
```
Comment (AThousandShips) [inline scene/resources/audio_stream_wav.cpp]: I think we can remove this debug code

File: scene/resources/audio_stream_wav.cpp [hunk 2]
```diff
@@ -785,23 +786,23 @@ Ref<AudioStreamWAV> AudioStreamWAV::load_from_buffer(const Vector<uint8_t> &p_st
 			print_line("bits: "+itos(format_bits));
 			*/
 
-			data.resize(frames * format_channels);
+			ERR_FAIL_COND_V(data.resize(frames * format_channels), Ref<AudioStreamWAV>());
```
Comment (AThousandShips) [inline scene/resources/audio_stream_wav.cpp]:
```suggestion
			ERR_FAIL_COND_V(data.resize(frames * format_channels) != OK, Ref<AudioStreamWAV>());
```
Prefer being explicit, for all

File: scene/resources/audio_stream_wav.cpp (hunk 1 above)
Comment (DeeJayLSP) [reply scene/resources/audio_stream_wav.cpp]: To reduce the scope of the PR to a fix, I opted to leave this untouched. Maybe a future codestyle-focused PR could remove it.

File: scene/resources/audio_stream_wav.cpp (hunk 2 above)
Comment (DeeJayLSP) [reply scene/resources/audio_stream_wav.cpp]: Done.

**Comment by DeeJayLSP** [comment]
> Containers use signed sizes

Makes sense. Although realistically, that limit can never be reached unless the user has over 17 ***billion*** GB of RAM and storage. Assuming you would have the max possible values for channels (2^16) and mix rate (2^32) it would be enough to fit 18 hours of audio, but of course, the probability of a stream like this being created by someone is literally null.

 The data length now uses a signed 64-bit integer.

**Comment by DeeJayLSP** [comment]
Modified a few more things that could have caused problems to playback (more `uint32_t` to `int64_t` conversions).

**Comment by adamscott** [comment]
cc. @Ivorforce If you could review this PR, it's highly technical about integer types, if you can help us.

**Comment by Ivorforce** [comment]
> Containers use signed sizes, so it's relevant to check for sizing issues, I'd say it might be better to use signed sizes unless impossible (realized it all uses 32 bit numbers for unsigned so that shouldn't be a problem)

Sorry for bringing this up again, but this is incorrect. Both `LocalVector` and `Vector` use unsigned sizes internally. Some interfaces accept signed sizes to avoid accidental conversion of user-supplied negative values to unsigned, which would result in confusing error messages. Some interfaces also return signed sizes, either for consistency or just as legacy behavior. But internally, our containers are using unsigned sizes.

I'm not sure what was changed from this suggestion, but unsigned is appropriate when dealing with non-negative data. I'd suggest changing at least `TightLocalVector` to use `uint64_t`. Most other data types that were previously unsigned should probably remain so.

Generally, the change looks sensible to me, but implicit C++ conversions make it difficult to be very sure that nothing unintentional is happening. Unfortunately (afaik) it's impossible to be sure about it without testing. I'll review the code again in more detail when the above suggestions are addressed.

**Comment by DeeJayLSP** [comment]
> I'd suggest changing at least `TightLocalVector` to use `uint64_t`

Addressed. Also took the opportunity to modify some missing changes.

Note that getting the length in `_mix_internal` needs to use a signed integer, as it triggers a warning due to a comparison with `offset`, which needs to be able to be negative (or else we would need a bigger refactor).

File: scene/resources/audio_stream_wav.cpp [hunk 3]
```diff
@@ -174,7 +174,7 @@ void AudioStreamPlaybackWAV::decode_samples(const Depth *p_src, AudioFrame *p_ds
 			}
 
 		} else if (is_qoa) {
-			uint32_t new_data_ofs = 8 + pos / QOA_FRAME_LEN * p_qoa->frame_len;
+			int64_t new_data_ofs = 8 + pos / QOA_FRAME_LEN * p_qoa->frame_len;
```
Comment (Ivorforce) [inline scene/resources/audio_stream_wav.cpp]: `data_ofs` is `uint32_t`. Why change to signed?

File: scene/resources/audio_stream_wav.cpp [hunk 4]
```diff
@@ -222,7 +222,7 @@ int AudioStreamPlaybackWAV::_mix_internal(AudioFrame *p_buffer, int p_frames) {
 		return 0;
 	}
 
-	uint32_t len = base->data_bytes;
+	int64_t len = base->data_bytes;
```
Comment (Ivorforce) [inline scene/resources/audio_stream_wav.cpp]: `data_bytes` is `uint64_t`. Why change to signed?

File: scene/resources/audio_stream_wav.h [hunk 5]
```diff
@@ -52,7 +52,7 @@ class AudioStreamPlaybackWAV : public AudioStreamPlaybackResampled {
 
 	struct QOA_State {
 		qoa_desc desc = {};
-		uint32_t data_ofs = 0;
+		int64_t data_ofs = 0;
```
Comment (Ivorforce) [inline scene/resources/audio_stream_wav.h]: Again, why change to signed?

**Review by Ivorforce — COMMENTED** [review]
Most changes look good to me.

File: scene/resources/audio_stream_wav.cpp (hunk 4 above)
Comment (DeeJayLSP) [reply scene/resources/audio_stream_wav.cpp]: > Note that getting the length in `_mix_internal` needs to use a signed integer, as it triggers a warning due to a comparison with `offset`, which needs to be able to be negative (or else we would need a bigger refactor).

For some reason, the warning is triggered if it's `uint64_t`, but not `uint32_t`. I'll do an experiment.

File: scene/resources/audio_stream_wav.h (hunk 5 above)
Comment (DeeJayLSP) [reply scene/resources/audio_stream_wav.h]: Because `data_ofs` is supposed to be the same type as the size type of the data vector. I just missed this change.

**Review by Ivorforce — APPROVED** [review]
Looks good to me.
I think this has _some_ potential to cause odd regressions, especially with intermediate values of math that was changed from signed to unsigned. I'm with you on the decision; some of these types should have been unsigned from the start, but it _is_ somewhat of a risk.
I'd hesitate to recommend merging this for 4.5 for this reason, i'd feel more comfortable merging it in early 4.6 and perhaps cherry-picking it after a month or so of tests. But I guess there's still some weeks to go until 4.5 release, so it could be fine.

**Comment by adamscott** [comment]
Following @Ivorforce suggestion, I moved the milestone to 4.6.

**Comment by DeeJayLSP** [comment]
If there is any regressions, those would only be noticeable if we tried to import a 2GB+ WAV file, as that's where the range of signed 32-bit int overflows.

If you do try importing a 2GB+ file right now, the import will be broken because it will try to assign `UINT32_MAX` to a signed `int`. This won't happen with this PR in.

Also, I don't think wrapping a 64-bit data range with a signed integer (there is only *one* iteration of that, as Ivorforce complained, that isn't a default from a WAV file) breaks anything, as the average storage/RAM doesn't cover that much range, and I doubt it will before hundreds of years.

There are some sign changes I could revert that wouldn't make a problem.

**Comment by Ivorforce** [comment]
> If there is any regressions, those would only be noticeable if we tried to import a 2GB+ WAV file, as that's where the range of signed 32-bit int overflows.

I'm specifically worried about breaking normal files by implicit conversions, not just 2GB+ files. Changing types like this can break math in unexpected ways. 

> There are some sign changes I could revert that wouldn't make a problem.

I think your PR is fine as is.
I'm not _against_ a 4.5 merge, I just wouldn't vouch for it since the release is getting quite close. Since loading >2Gb files is kind of niché, I think the fix can wait to reduce regression risks. We can still cherry-pick it once it's been under test for a bit in alpha.

**Review by aaronfranke — APPROVED** [review]

**Comment by Repiteo** [comment]
Needs rebase

**Comment by DeeJayLSP** [comment]
Rebase done.

**Comment by Repiteo** [comment]
Thanks!

**Comment by DeeJayLSP** [comment]
If we're taking into account only WAV files can be imported, #91077 could be considered superseded.

On the other hand, that PR changes the file pos type into a `uint64_t`. For WAVs, it shouldn't be a problem since the WAV specification states it can't go over 4 GiB anyway.
