### PR TITLE
Fixed animation player auto-queue duplication and undo/redo

### LINKED ISSUE #148: changing Next (auto-queue) doesn't mark scene as changed
if you open up a scene (for a character or somesuch) and select the AnimationPlayer node, then click on the =><= blending button, and enter a value for the Next (Auto Queue) field, the Scene does not get marked as changed.

If this is the only change you make before switching to another scene, then you will lose the change without being prompted about it, like you should be.

------

( I poked around in the source code and I got it to mark the scene as changed by inserting an undo step, however, it does not behave as desired.. the text box loses focus after every keystroke and a new undo step is saved for every keystroke, etc.  (And further to that, the undo didn't even work.) I'm currently too much of a newbie to properly fix this, but I did try... I think if I could change the text field to a dropdown menu which lists all the other animations in the AnimationPlayer, that would solve it. )

### LINKED ISSUE #974: duplicating an animation doesn't copy next auto-queue
If you duplicate an animation, the copy should copy everything, including the next auto-queue (in Blend dialog)

also, would be nice if the next auto-queue option was a dropdown menu instead of a text box, unless there's a reason we would want a text box?

### PR DESCRIPTION
**Pull request by Paulb23**
Fixed animation player auto-queue duplication and undo/redo history, by doing this setting the scene as changed.

Also turned it into a dropdown instead of a text box.

closes #148 
closes #974

### CODE REVIEW

File: tools/editor/plugins/animation_player_editor_plugin.cpp [hunk 1]
```diff
@@ -536,14 +536,19 @@ void AnimationPlayerEditor::_animation_name_edited() {
...
-void AnimationPlayerEditor::_blend_editor_next_changed(const String& p_string) {
+void AnimationPlayerEditor::_blend_editor_next_changed(const int p_idx) {
 
 	if (animation->get_item_count()==0)
 		return;
 
 	String current = animation->get_item_text(animation->get_selected());
-	player->animation_set_next(current,p_string);
 
+	undo_redo->create_action(TTR("Blend Next Changed"));
```
Comment (akien-mga) [inline tools/editor/plugins/animation_player_editor_plugin.cpp]: Kudos for having noticed the new translation mechanism for such things :D

**Comment by akien-mga** [comment]
Nice work, thanks!
