### PR TITLE
JavaClassWrapper: Improve handling of typed array arguments

### LINKED ISSUE #102712: When using JavaClassWrapper, calling a method with multiple overloaded parameters will cause an error.
### Tested versions

4.4 beta 3

### System information

Windows10 - Godot v4.4 beta3

### Issue description

When calling a method with more than two overloaded versions and a vararg parameter, the correct parameter type cannot be recognized, as demonstrated below:

### Steps to reproduce

```kotlin
class TestClass {
    companion object {
        @JvmStatic
        fun testMethod(int: Int,array: IntArray): String {
            return "IntArray"
        }

        @JvmStatic
        fun testMethod(int: Int,vararg args: String): String {
            return "StringArray"
        }
    }
}
```

When I call this class in Godot, it fails to recognize the parameter types correctly, causing the wrong method to be invoked every time.

```gdscript
func _ready() -> void:
	var javaClass = JavaClassWrapper.wrap("com.godot.game.TestClass")
	print('from kotlin:' + javaClass.testMethod(1,["asd"]))
```

Image
When I pass a parameter of type String, the first method is invoked instead of the second method with the vararg parameter.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by dsnopek**
Fixes https://github.com/godotengine/godot/issues/102712

There are 3 issues that come from that:

- [X] Method selection doesn't take typed arrays (including the `Packed*Array` types) into account when selected an overloaded method
- ~~[x] vararg methods aren't supported~~
- [x] Arrays of `JavaObject`s aren't supported (this one I noticed while working on this)

~~So far, this PR only fixes the first one, which is why this is currently marked as DRAFT.~~

**UPDATE:** All the issues are fixed now in my testing!

**UPDATE 2:** I ended up deciding to remove the explicit support for varargs - see [this comment](https://github.com/godotengine/godot/pull/102817#issuecomment-2659500068).

### CODE REVIEW

**Comment by dsnopek** [comment]
I've now got all the issues fixed in my testing!

However, this does change quite a large amount of code, and will need a thorough review.

**Review by syntaxerror247 — COMMENTED** [review]
The code looks good to me. I prefer the current approach (treating Java varargs methods as having a final array parameter), but I'd like to hear @m4gr3d's preference and leave the approval to him.

File: platform/android/java_class_wrapper.cpp [hunk 1]
```diff
@@ -410,7 +617,21 @@ bool JavaClass::_call_method(JavaObject *p_instance, const StringName &p_method,
 				to_free.push_back(jarr);
 			} break;
 			case ARG_ARRAY_BIT | ARG_TYPE_CLASS: {
-				argv[i].l = nullptr;
+				String cn = method->param_sigs[i].operator String();
+				if (cn.begins_with("[L") && cn.ends_with(";")) {
+					cn = cn.substr(2, cn.length() - 3);
+				}
+				jclass c = env->FindClass(cn.utf8().get_data());
```
Comment (m4gr3d) [inline platform/android/java_class_wrapper.cpp:624]: We should check that `c` is valid before proceeding.

**Review by m4gr3d — APPROVED** [review]
Looks great!

The changes are small and scoped enough they should be safe to include in 4.4. Leaving it up to @akien-mga to decide.

File: platform/android/java_class_wrapper.cpp (hunk 1 above)
Comment (dsnopek) [reply platform/android/java_class_wrapper.cpp:624]: We would have checked this earlier on line 224.

This process goes in two phase: a validation phase, where it reports errors about any of the provided arguments, and then a calling phase where (if there were no validation errors) it marshals the data into the Java types and actually calls the method. This would have gotten caught in the validation phase.

However, it's no problem to add `if (c) { ... }`, so I have done that in my latest push :-)

**Comment by dsnopek** [comment]
> The changes are small and scoped enough they should be safe to include in 4.4.

The ship _may_ have sailed on Godot 4.4, but it'd fine for this to end up in 4.4.1.

**Comment by dsnopek** [comment]
In my latest push, I added one of the same efficiency improvements as I did in PR https://github.com/godotengine/godot/pull/103375, where JNI fills some the arrays (the ones where the types match) rather than us going element by element. I have a test project that comprehensively tests all the conversion branches in this one, so I'm pretty confident about this update!

File: platform/android/java_class_wrapper.cpp [hunk 2]
```diff
@@ -307,90 +417,171 @@ bool JavaClass::_call_method(JavaObject *p_instance, const StringName &p_method,
...
+						jshort val = arr[j];
+						env->SetShortArrayRegion(a, j, 1, &val);
+					}
+				} else if (p_args[i]->get_type() == Variant::PACKED_INT32_ARRAY) {
+					PackedInt32Array arr = *p_args[i];
+					a = env->NewShortArray(arr.size());
+					for (int j = 0; j < arr.size(); j++) {
+						jshort val = arr[j];
+						env->SetShortArrayRegion(a, j, 1, &val);
+					}
```
Comment (m4gr3d) [inline platform/android/java_class_wrapper.cpp:477]: Does the copy logic not work for `short`?

Comment (dsnopek) [reply platform/android/java_class_wrapper.cpp:477]: Not with the way that I decided to convert from `PackedInt32Array`: it's set up to treat each item in the `PackedInt32Array` as representing a single `short`.

If we decided that each item in the `PackedInt32Array` represented 2 `short`s (with one of them shifted two bytes to the left) then we could copy directly. However, that didn't seem like the most friendly for developers - my guess is that they would assume it was the former.

Although, that was just a judgement call I made! If anyone thinks otherwise, let's discuss :-)

Comment (dsnopek) [reply platform/android/java_class_wrapper.cpp:477]: Actually, thinking about this a little more, I don't think we actually could treat each item in `PackedInt32Array` as representing two `short`s: how would you pass an array with an odd number of items? There'd be no way to indicate that the last element didn't exist.

I think the way I'm doing the conversion is really the only way to do it if we use `PackedInt32Array`. If we wanted to pack them tighter, we could use `PackedByteArray`, but that would be so tricky to use from GDScript.

I'm happy with the judgement call I made here: it optimizes for each of use by the developer, not performance or lower memory usage. I don't think APIs that take `short[]` are super common anyway, so odds are this conversion won't get used that much anyway

Comment (syntaxerror247) [reply platform/android/java_class_wrapper.cpp:477]: Yeah, I don't really remeber the last time I used short[].

**Review by syntaxerror247 — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.4.1.
