### PR TITLE
Fix TextEdit `read_only` drawing.

### LINKED ISSUE #97099: TextEdit/LineEdit inconsistency when non-editable
### Tested versions

- Reproducable in v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated AMD Radeon RX 6600 (Advanced Micro Devices, Inc.; 32.0.11029.1008) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

A TextEdit and LineEdit do not draw their StyleBoxes in the same way when `editable = false`. I would expect these to look visually more similar than they do.
image

### Steps to reproduce

1. Create a TextEdit and a LineEdit next to each other.
2. Uncheck `editable` for both
3. Notice that the TextEdit is notably more solid-looking than the LineEdit

### Minimal reproduction project (MRP)

[mrp_textedit.zip](https://github.com/user-attachments/files/17022732/mrp_textedit.zip)

### PR DESCRIPTION
**Pull request by WhalesState**
* Fixes: https://github.com/godotengine/godot/issues/97099

### CODE REVIEW

**Comment by WhalesState** [comment]
Unrelated to the changes, I have no clue why it keeps happening, the failed check will pass if we rerun it.

image

**Review by kitbdev — APPROVED** [review]
Looks good.

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -8807,7 +8781,8 @@ void TextEdit::_adjust_viewport_to_caret_horizontally(int p_caret, bool p_maximi
 		return;
 	}
 
-	int visible_width = get_size().width - theme_cache.style_normal->get_minimum_size().width - gutters_width - gutter_padding;
+	Ref<StyleBox> style = _get_current_stylebox();
+	int visible_width = get_size().width - Math::ceil(style->get_margin(SIDE_LEFT)) - Math::floor(style->get_margin(SIDE_RIGHT)) - gutters_width - gutter_padding;
```
Comment (WhalesState) [inline scene/gui/text_edit.cpp]: This change fixes the issue where the last character was cut off when the editor scale is a fractional number. Previously, we used `style->get_minimum_size().width`, but draw methods always round up the left and right style margins with `Math::ceil`, which caused a mismatch.

File: scene/gui/text_edit.cpp [hunk 2]
```diff
@@ -1157,9 +1152,9 @@ void TextEdit::_notification(int p_what) {
 				}
 
 				if (rtl) {
-					RenderingServer::get_singleton()->canvas_item_add_rect(ci, Rect2(size.width - (xmargin_end + 2) - minimap_width, viewport_offset_y, minimap_width, viewport_height), viewport_color);
+					RenderingServer::get_singleton()->canvas_item_add_rect(ci, Rect2(size.width - xmargin_end - minimap_width, viewport_offset_y, minimap_width, viewport_height), viewport_color);
```
Comment (WhalesState) [inline scene/gui/text_edit.cpp]: I initially removed the extra 2 pixels added to the end margin while debugging this issue, since I suspected they might be the cause. I’ll revert that change, as they weren’t actually responsible.

File: scene/gui/text_edit.cpp (hunk 1 above)
Comment (kitbdev) [reply scene/gui/text_edit.cpp]: It seems to fix the issue.
Why are some of them ceil ceil (for left, right) and some are ceil floor? Shouldn't they all be the same using ceil?

Comment (WhalesState) [reply scene/gui/text_edit.cpp]: I originally made this change to avoid ending up with one extra pixel compared to what `style.get_minimum_size()` returns, since each margin could be rounded up individually. But I agree this causes confusion, margins should be usable individually without additional operations, and `get_minimum_size()` should consistently equal (side_left + side_right).

I’ll make sure all margins multiplied by `EDSCALE` are rounded properly, since they’re floats and can otherwise lead to inconsistent results.

Edit: Also AFAIR i have changed both to use ceil and maybe i have tested with flooring right margin and it also was solving the issue and i forgot to revert it back to ceil, but to avoid the confusion I will solve it in `editor_theme_manager.cpp` instead.

Comment (WhalesState) [reply scene/gui/text_edit.cpp]: I remember we had a similar issue in the Button class with the last character, but that was solved. I’ll check later if the cause was also related to the button style using float margins. so rounding one margin but then returning a minimum size based on `StyleBox.get_minimum_size()`. These issues all seem to stem from the editor theme not ensuring margins are consistently rounded after being multiplied.

Edit: It was unrelated, we have fixed that issue by updating minimum size when the button is disabled.

**Comment by WhalesState** [comment]
https://github.com/user-attachments/assets/66b345e7-34ff-4720-aca0-93a5db3766a8

**Comment by kitbdev** [comment]
I think affecting all editor theme styleboxes is out of scope for this PR that was about the TextEdit readonly style. It was already approved too, I think these new changes would be better in a new PR to be reviewed separately.

**Comment by WhalesState** [comment]
Removed editor theme changes, also removed ceiling the margins which still fixes the text clipping issue but will report minimum size + 1 instead of -1 when left/right margin has values that can be rounded up.

**Comment by kitbdev** [comment]
>  also removed ceiling the margins which still fixes the text clipping issue but will report minimum size + 1 instead of -1 when editor scale is %50 or %150 which is fine for now.

This reverts #105870 so it reintroduces an issue and needs more consideration.
I think it should be a separate change so we can focus on allowing this PR to merge with just the read only change.

File: scene/gui/text_edit.cpp [hunk 3]
```diff
@@ -1941,6 +1922,7 @@ void TextEdit::_notification(int p_what) {
 			}
 
 			if (has_focus()) {
+				theme_cache.style_focus->draw(ci, Rect2(Point2(), get_size()));
```
Comment (kitbdev) [inline scene/gui/text_edit.cpp]: I realized that the focus drawing should be before the text drawing, since it might not just be an outline and then it would block the text. LineEdit also has it before the text.

**Review by kitbdev — CHANGES_REQUESTED** [review]

**Comment by WhalesState** [comment]
> This reverts #105870 so it reintroduces an issue and needs more consideration. I think it should be a separate change so we can focus on allowing this PR to merge with just the read only change.

* Moved the fix here https://github.com/godotengine/godot/pull/110791 since the last character clipping was a regression from https://github.com/godotengine/godot/pull/105870.

File: scene/gui/text_edit.cpp (hunk 3 above)
Comment (WhalesState) [reply scene/gui/text_edit.cpp]: Fixed.

Comment (kitbdev) [reply scene/gui/text_edit.cpp]: It should be before the minimap and guidelines too. Where it was on master is fine.

Comment (WhalesState) [reply scene/gui/text_edit.cpp]: Fixed again, sorry I just resolved it from a conflict since it was drawn twice.

**Comment by kitbdev** [comment]
> Moved the fix here https://github.com/godotengine/godot/pull/110791 since the last character clipping was a regression from https://github.com/godotengine/godot/pull/105870.

If the fix is moved to another PR, why is #105870 still being reverted here?
I tested and it reopens https://github.com/godotengine/godot/issues/105827

**Comment by WhalesState** [comment]
> If the fix is moved to another PR, why is #105870 still being reverted here? I tested and it reopens #105827

* I have explained the issue more in #110791 since fixing it for RTL  #110791 reproduced it in LTR using 150% editor scale #108520, reverting the fix now will conflict with this fix that's why i kept both fixes together first since they all are related to StyleBox and drawing methods.

**Comment by WhalesState** [comment]
> If the fix is moved to another PR, why is #105870 still being reverted here? I tested and it reopens #105827

Fixed by not reverting it in this PR, it should only close the linked issue now without causing any regressions.

**Review by kitbdev — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
