### PR TITLE
Fix Skeleton3D insert key tooltips

### LINKED ISSUE #8957: Skeleton3D Insert Key button is impossible to read
**Your Godot version:**
Godot 4.2.stable

**Issue description:**
At the top ribbon when you are animating a Skeleton3D, there is a button to insert all bone positions/rotations as keys to an existing track, but it just about gave me a stroke reading it. Moreover, I tried to fix it myself, but I apparently can't, but I noticed that this is literally the key for all translations, which means all translations should probably be checked to make sure that they're translated properly, because the original was hardly understandable. I'm not going to fix it myself because I'm not sure how the translation keys work and I don't want to cause any issues with translations.

**URL to the documentation page:**
https://github.com/godotengine/godot/blob/e5a3fd1e53ad4e6efc1fd17deded8f4ce0973d10/editor/plugins/skeleton_3d_editor_plugin.cpp#L790

https://github.com/search?q=repo%3Agodotengine%2Fgodot+already+exist+track.&type=code&p=1

I suggest something like "Insert key of existing bone poses into an existing track." and also you might wanna look into the "Insert Key (All Bones) part too because it's hard to understand what the difference is between that and the "Insert Key (Existing Tracks) button.

### PR DESCRIPTION
**Pull request by skyace65**
Original text looks like it was written by someone in the middle of a stroke. This PR fixes that. Closes https://github.com/godotengine/godot-docs/issues/8957

### CODE REVIEW

**Comment by hunterbk** [comment]
Does the button only key rotations, or also translations? If it's only rotations, that button was even more severely mislabeled than I originally thought

**Review by fire — APPROVED** [review]

File: editor/plugins/skeleton_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -787,15 +787,15 @@ void Skeleton3DEditor::create_editors() {
 	key_insert_button->set_theme_type_variation("FlatButton");
 	key_insert_button->set_focus_mode(FOCUS_NONE);
 	key_insert_button->connect("pressed", callable_mp(this, &Skeleton3DEditor::insert_keys).bind(false));
-	key_insert_button->set_tooltip_text(TTR("Insert key of bone poses already exist track."));
+	key_insert_button->set_tooltip_text(TTR("Insert key for bone rotations with an existing track."));
```
Comment (fire) [inline editor/plugins/skeleton_3d_editor_plugin.cpp:790]:
```suggestion
	key_insert_button->set_tooltip_text(TTR("Insert keyframes for the bone with an existing track."));
```

**Review by fire — DISMISSED** [review]
I suspect something is wrong.

I think this refers to keyframes of loc,rot, and scale. Where does it say rotation only?

File: editor/plugins/skeleton_3d_editor_plugin.cpp [hunk 2]
```diff
@@ -787,15 +787,15 @@ void Skeleton3DEditor::create_editors() {
...
 	key_insert_button->set_shortcut(ED_SHORTCUT("skeleton_3d_editor/insert_key_to_existing_tracks", TTR("Insert Key (Existing Tracks)"), Key::INSERT));
 	animation_hb->add_child(key_insert_button);
 
 	key_insert_all_button = memnew(Button);
 	key_insert_all_button->set_theme_type_variation("FlatButton");
 	key_insert_all_button->set_focus_mode(FOCUS_NONE);
 	key_insert_all_button->connect("pressed", callable_mp(this, &Skeleton3DEditor::insert_keys).bind(true));
-	key_insert_all_button->set_tooltip_text(TTR("Insert key of all bone poses."));
+	key_insert_all_button->set_tooltip_text(TTR("Insert key for all bone rotations."));
```
Comment (fire) [inline editor/plugins/skeleton_3d_editor_plugin.cpp:798]:
```suggestion
	key_insert_all_button->set_tooltip_text(TTR("Insert keyframes for all bone poses."));
```

**Comment by skyace65** [comment]
@fire both buttons only work for rotation, I tested that before making this PR. If they're intended to keyframe position and scale as well that's currently broken in 4.2.1. Here's a video of me using the buttons.
[Button Test.zip](https://github.com/godotengine/godot/files/14310776/Button.Test.zip)

**Comment by fire** [comment]
In your video the button for rotation was selected, did you try selecting the other buttons (next to it).

**Comment by skyace65** [comment]
You were right Fire, I completely forgot about those buttons. I've updated this PR but I'd like to re-word it further tomorrow. I want to try and keep the description consistent with what we use for the key button in the toolbar for 2D scenes.

**Comment by skyace65** [comment]
Updated description again, ready for review again.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Needs rebase.

**Comment by akien-mga** [comment]
Thanks!
