### PR TITLE
Fix saving unmodified scenes and resources

### LINKED ISSUE #6025: Godot edits and saves .tscn without consent!
I've pulled form git my game, opened it in Godot 2.1 editor, and then I saw in my shell that files have changed! **But I've not even saved anything!**

here's git diff:

``` diff
diff --git a/main.tscn b/main.tscn
index abc0021..31c1cd7 100644
--- a/main.tscn
+++ b/main.tscn
@@ -273,3 +273,5 @@ geometry/depth_scale = false
 geometry/visible_in_all_rooms = false
 geometry/use_baked_light = false
 geometry/baked_light_tex_id = 0
+
+
```

### PR DESCRIPTION
**Pull request by robfram**
Fix saving unmodified scenes and resources

When `_save_all_scenes` or `save_resource_in_path` was called, they
always saved all the scenes and the resource no matter if they were
modified or not. For example, when `saving before run` option was
checked, it always overwrote the current scene and the default
environment simply by opening and runing the project.

This PR adds checks for unsaved scenes (using the same `unsave` check
others method used) and modified resources (comparing last modified
time and last import time).

Fix #6025.

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -1089,14 +1093,21 @@ void EditorNode::_save_scene(String p_file, int idx) {
...
 		Node *scene = editor_data.get_edited_scene_root(i);
-		if (scene && scene->get_filename() != "") {
-			if (i != editor_data.get_edited_scene())
-				_save_scene(scene->get_filename(), i);
-			else
-				_save_scene_with_preview(scene->get_filename());
-		} // else: ignore new scenes
+
+		if (scene) {
+			bool unsaved = (i == current) ? saved_version != editor_data.get_undo_redo().get_version() : editor_data.get_scene_version(i) != 0;
```
Comment (Noshyaar) [inline editor/editor_node.cpp]: I think this logic is already implemented in `_next_unsaved_scene`.

Comment (robfram) [reply editor/editor_node.cpp]: I understand you want to use `_next_unsaved_scene` here to check if it must be saved or not instead repeating the `unsave` code. I will update the commit with that.

**Comment by puppetmaster-** [comment]
Is it possible to have this fix also for 2.1?

**Comment by akien-mga** [comment]
@hpvb Keep in mind to also cherry-pick #17747 as a fixup with this one (or neither - that's your call :)).

**Comment by hpvb** [comment]
It seems that the main scene is still saved on every run even if it was not modified. Is this still a bug left over?

**Comment by hpvb** [comment]
Never mind my last comment. Building between cherry picking and retesting helps a lot. 

Cherry picked into 3.0.3

**Comment by abdalrahmanhamami** [comment]
Hello  guys , how can stop  receiving  those emails

**Comment by vnen** [comment]
@abdalrahmanhamami you can unsubscribe in GitHub.

**Comment by akien-mga** [comment]
Reverted in #19836.
