### PR TITLE
TileMap: Set texture_filter and texture_repeat to generated CanvasItems...

### LINKED ISSUE #36328: Vulkan: changing filter mode doesn't work on TileMaps
**Godot version:**
Godot 4.0 dev

**OS/device including version:**
Windows 10

**Issue description:**
Filtering options are now on each CanvasItem node, but it seems changing them has no effect on TileMap nodes:
oxPKRj5
4VMdjfa

**Steps to reproduce:**
Create a TileMap, set its filter mode to Nearest and add one or more tiles.

### PR DESCRIPTION
**Pull request by kuruk-mm**
...  and update when it changes

Fix #36328 

I'm getting used to Godot code, so I copied how to do some things like:

Transform from VisualServer::CanvasItemTextureFilter to CanvasItem::TextureFilter
image
(similar transform from VisualServer::CanvasItemTextureRepeat to CanvasItem::TextureRepeat)

And i change set_texture_filter() and set_texture_repeat() to virtual, similar to set_material to inherit from TileMap for update.

### CODE REVIEW

**Comment by Calinou** [comment]
Please look at resolving merge conflicts so this can be considered for merging :slightly_smiling_face:

File: scene/2d/tile_map.cpp [hunk 1]
```diff
@@ -1782,6 +1785,16 @@ bool TileMap::get_clip_uv() const {
 	return clip_uv;
 }
 
+void TileMap::set_texture_filter(TextureFilter p_texture_filter) {
+	CanvasItem::set_texture_filter(p_texture_filter);
+	_recreate_quadrants();
```
Comment (clayjohn) [inline scene/2d/tile_map.cpp:1790]: Why are you recreating quadrants here? You can probably just updated the texture filter directly in the server. Same goes for below.

Comment (kuruk-mm) [reply scene/2d/tile_map.cpp:1790]: Can you give me an advice of how to do that?

Comment (clayjohn) [reply scene/2d/tile_map.cpp:1790]: Well, I'm just guessing, but it seems odd to have to re create the quadrants just to change a setting. 

Are you able to retrieve the RIDs for the quadrants? If so, you could just loop through them and set the filter mode with the same line you included above 
``vs->canvas_item_set_default_texture_filter(canvas_item, VS::CanvasItemTextureFilter(CanvasItem::get_texture_filter()))``

Comment (kuruk-mm) [reply scene/2d/tile_map.cpp:1790]: I tried with this, but is not working, I don't know exactly what i'm missing.

```
void TileMap::_update_textures() {
	for (Map<PosKey, Quadrant>::Element *F = quadrant_map.front(); F; F = F->next()) {
		Quadrant &q = F->get();
		for (List<RID>::Element *E = q.canvas_items.front(); E; E = E->next()) {
			RenderingServer::get_singleton()->canvas_item_set_default_texture_filter(E->get(), RS::CanvasItemTextureFilter(CanvasItem::get_texture_filter()));
			RenderingServer::get_singleton()->canvas_item_set_default_texture_repeat(E->get(), RS::CanvasItemTextureRepeat(CanvasItem::get_texture_repeat()));
		}
	}
}
```

Comment (clayjohn) [reply scene/2d/tile_map.cpp:1695]: Where are you calling that?

Comment (kuruk-mm) [reply scene/2d/tile_map.cpp:1695]: I resolve merge conflicts and force push with the `_recreate_quadrants();` if someone want to test it, I will continue searching tomorrow.

I don't know how to update this properly and I'm not having such time, if someone can help with this will be nice. I think you're correct clayjohn but I don't know exactly how to do it.

Comment (kuruk-mm) [reply scene/2d/tile_map.cpp:1695]: > Where are you calling that?

In set_texture_filter and set_texture_repeat

```void TileMap::set_texture_filter(TextureFilter p_texture_filter) {
	CanvasItem::set_texture_filter(p_texture_filter);
	_update_textures();
}```

Comment (clayjohn) [reply scene/2d/tile_map.cpp:1695]: Here is a slightly improved approach. This sets all quadrants as dirty and refreshes them instead of completely clearing all quadrants and rebuilding them from scratch. Although, this still seems like we are doing way too much work just to update the texture filter. 

```
void TileMap::set_texture_filter(TextureFilter p_texture_filter) {
	CanvasItem::set_texture_filter(p_texture_filter);
	for (Map<PosKey, Quadrant>::Element *F = quadrant_map.front(); F; F = F->next()) {
		Quadrant &q = F->get();
		for (List<RID>::Element *E = q.canvas_items.front(); E; E = E->next()) {
			RenderingServer::get_singleton()->canvas_item_set_default_texture_filter(E->get(), RS::CanvasItemTextureFilter(p_texture_filter));
			_make_quadrant_dirty(F);
		}
	}
}

void TileMap::set_texture_repeat(CanvasItem::TextureRepeat p_texture_repeat) {
	CanvasItem::set_texture_repeat(p_texture_repeat);
	for (Map<PosKey, Quadrant>::Element *F = quadrant_map.front(); F; F = F->next()) {
		Quadrant &q = F->get();
		for (List<RID>::Element *E = q.canvas_items.front(); E; E = E->next()) {
			RenderingServer::get_singleton()->canvas_item_set_default_texture_repeat(E->get(), RS::CanvasItemTextureRepeat(p_texture_repeat));
			_make_quadrant_dirty(F);
		}
	}
}
```

Comment (kuruk-mm) [reply scene/2d/tile_map.cpp]: That's working, maybe there is another way to update the texture filter, but I tried to figure out a way to do better without success.
I force-push with your code anyway.

**Review by reduz — APPROVED** [review]

File: scene/2d/tile_map.cpp (hunk 1 above)
Comment (kuruk-mm) [reply scene/2d/tile_map.cpp]: I asked reduz and he said is ok

**Comment by akien-mga** [comment]
Thanks!
