### PR TITLE
Display correct symbol in warning when unique name is used without @onready annotation

### LINKED ISSUE #102386: "The default value is using "$" which won't return nodes..." warning despite using Unique Name ("%")
### Tested versions

- Reproducible in v4.4.beta.custom_build [eee39f004]

### System information

Godot v4.4.beta (eee39f004) - macOS Sequoia (15.3.0) - Multi-window, 2 monitors - OpenGL 3 (Compatibility) - AMD Radeon Pro 5500 XT OpenGL Engine - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 threads)

### Issue description

The error message for attempting to access a unique-named node in a class body without the `@onready` annotation is slightly incorrect - it claims the user is using "$", when in reality the user is using "%".

Image

 

### Steps to reproduce

In a new GDScript file, on the class level, type the following:
```gdscript
var something = %Hello
```

You will get an error like
```
The default value is using "$" which won't return nodes in the scene tree before "_ready()" is called. Use the "@onready" annotation to solve this. (Warning treated as error.)gdscript(-1)
```

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Meorge**
Closes #102386.

This adds a few lines of code to the procedure generating the warning. It simply checks if the path being used in shorthand begins with "%", and if so uses that symbol instead of "$" for the warning.

https://github.com/user-attachments/assets/9cbd3e4a-0fa5-4d4b-8106-198c2e157cd9

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -1093,7 +1093,16 @@ void GDScriptAnalyzer::resolve_class_member(GDScriptParser::ClassNode *p_class,
 							}
 						}
 						if (is_get_node) {
-							parser->push_warning(member.variable, GDScriptWarning::GET_NODE_DEFAULT_WITHOUT_ONREADY, is_using_shorthand ? "$" : "get_node()");
+							GDScriptParser::GetNodeNode *get_node_node = static_cast<GDScriptParser::GetNodeNode *>(expr);
+							String offending_syntax = "get_node()";
+							if (is_using_shorthand) {
+								if (get_node_node->full_path.begins_with("%")) {
```
Comment (dalexeev) [inline modules/gdscript/gdscript_analyzer.cpp:1099]: There is `use_dollar` property:

https://github.com/godotengine/godot/blob/eee39f004b42a4948af90cdebedf65c34a4a4970/modules/gdscript/gdscript_parser.h#L877

Compare: `%Node` and `$"%Node"`. Also please add a test.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 2]
```diff
@@ -1093,7 +1093,16 @@ void GDScriptAnalyzer::resolve_class_member(GDScriptParser::ClassNode *p_class,
 							}
 						}
 						if (is_get_node) {
-							parser->push_warning(member.variable, GDScriptWarning::GET_NODE_DEFAULT_WITHOUT_ONREADY, is_using_shorthand ? "$" : "get_node()");
+							GDScriptParser::GetNodeNode *get_node_node = static_cast<GDScriptParser::GetNodeNode *>(expr);
```
Comment (dalexeev) [inline modules/gdscript/gdscript_analyzer.cpp:1096]: I'd move this into the `if (is_using_shorthand)` condition. Otherwise it's an incorrect cast if the type is not `GET_NODE`.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 3]
```diff
@@ -1093,7 +1093,16 @@ void GDScriptAnalyzer::resolve_class_member(GDScriptParser::ClassNode *p_class,
...
+							String offending_syntax = "get_node()";
+							if (is_using_shorthand) {
```
Comment (dalexeev) [inline modules/gdscript/gdscript_analyzer.cpp:1098]: There are 2 variables: `is_get_node` and `is_using_shorthand`. Are you sure that this is the correct one?

File: modules/gdscript/gdscript_analyzer.cpp (hunk 2 above)
Comment (Meorge) [reply modules/gdscript/gdscript_analyzer.cpp:1096]: Done, thanks!

File: modules/gdscript/gdscript_analyzer.cpp (hunk 3 above)
Comment (Meorge) [reply modules/gdscript/gdscript_analyzer.cpp:1098]: My understanding was that `is_using_shorthand` was used for when the `$` or `%` prefix was used, rather than a call to the `get_node` method:
```gdscript
# In all of these, is_get_node = true
var a = get_node("Node2D")  # is_using_shorthand = false
var b = $Node2D             # is_using_shorthand = true
var c = %Node2D             # is_using_shorthand = true
```
Since in all of these cases, `is_get_node` is `true`, we start out by checking it - then, we change the string to output to one of the shorthand versions if `is_using_shorthand` is `true` as well.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 1 above)
Comment (Meorge) [reply modules/gdscript/gdscript_analyzer.cpp:1099]: Thank you for the `use_dollar` suggestion. I'm using it in a newer version of the code that I'll push very shortly.

As for the test, I will try to get one added soon!

File: modules/gdscript/tests/scripts/analyzer/warnings/get_node_without_onready.gd [hunk 4]
```diff
@@ -8,6 +8,12 @@ var without_self = get_node(^"Node")
 var with_cast = get_node(^"Node") as Node
 var shorthand_with_cast = $Node as Node
 
+var shorthand_unique = %UniqueNode
+var with_self_unique = self.get_node(^"%UniqueNode")
+var without_self_unique = get_node(^"%UniqueNode")
+var with_cast_unique = get_node(^"%UniqueNode")
+var shorthand_with_cast_unique = %UniqueNode as Node
```
Comment (dalexeev) [inline modules/gdscript/tests/scripts/analyzer/warnings/get_node_without_onready.gd:15]: I'm not sure if we should duplicate all the cases, but we should add a test for `$"%UniqueNode"`.

File: modules/gdscript/tests/scripts/analyzer/warnings/get_node_without_onready.gd [hunk 5]
```diff
@@ -1,18 +1,30 @@
...
 var shorthand = $Node
 var with_self = self.get_node(^"Node")
 var without_self = get_node(^"Node")
 var with_cast = get_node(^"Node") as Node
 var shorthand_with_cast = $Node as Node
 
+var shorthand_unique = %UniqueNode
+var shorthand_in_dollar_unique = $"%UniqueNode"
+var without_self_unique = get_node(^"%UniqueNode")
+var shorthand_with_cast_unique = %UniqueNode as Node
```
Comment (dalexeev) [inline modules/gdscript/tests/scripts/analyzer/warnings/get_node_without_onready.gd:14]:
```suggestion
```

**Review by dalexeev — APPROVED** [review]

File: modules/gdscript/tests/scripts/analyzer/warnings/get_node_without_onready.gd (hunk 5 above)
Comment (dalexeev) [reply modules/gdscript/tests/scripts/analyzer/warnings/get_node_without_onready.gd:14]: In my opinion these cases are redundant, we use the same logic for regular and unique node shorthands.

Comment (akien-mga) [reply modules/gdscript/tests/scripts/analyzer/warnings/get_node_without_onready.gd:14]: IMO it can still make sense, as currently we use the same logic but if this changed in the future, the unit test would help ensure the behavior stays consistent. But I don't feel strongly about it, removing it is also fine.

Comment (akien-mga) [reply modules/gdscript/tests/scripts/analyzer/warnings/get_node_without_onready.gd:14]: I'd say it doesn't harm either way so let's not block this too long, and get it tested in the next beta.

**Comment by akien-mga** [comment]
Thanks!
