### PR TITLE
Fix missing shortcuts for play buttons in SpriteFrames Editor

### LINKED ISSUE #109414: Shortcut keys not functioning in the SpriteFrames Animation Player
### Tested versions

Reproducible in v4.5.beta5.official [c81fd6c51] and v4.4.1.stable.official [49a5bc7b6]

### System information

Godot v4.5.beta5 - Windows 11 (build 22631) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 Laptop GPU (NVIDIA; 32.0.15.7688) - 13th Gen Intel(R) Core(TM) i9-13900HX (32 threads) - 63.74 GiB memory

### Issue description

When the SpriteFrames panel for AnimatedSprite2D is in focus, the shortcut keys described in the icons don't function at all.

All of these commands only work for me if I click the buttons manually.

So hitting A, SHIFT + A, S, SHIFT + D, and D doesn't process any of those things. I have to manually click the buttons. Tried it on 4.4.1 and 4.5 and had the same problem.

I also checked the command palette and there are no shortcuts to bind in there.

Hitting CTRL + N, WILL make a new animation properly. 

Image

Image

### Steps to reproduce

1. Select the AnimatedSprite2D Node under the Player node in the Player scene.
2. click into the Animation player
3. Press any of the shortcut keys (A, SHIFT + A, S, SHIFT + D, and D)

### Minimal reproduction project (MRP)

[SpriteFrames Bug.zip](https://github.com/user-attachments/files/21674887/SpriteFrames.Bug.zip)

### PR DESCRIPTION
**Pull request by Giganzo**
Fixes: https://github.com/godotengine/godot/issues/109414

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected. Code looks good to me.

In a future PR, we should move these shortcuts to physical shortcuts so that their location is correct on non-QWERTY keyboards. We moved the <kbd>QWER</kbd> shortcuts to phyiscal keys in the 2D/3D editor already, so it won't create conflicts (in fact, it'll avoid them on AZERTY). See https://github.com/godotengine/godot/pull/103533 for an example of this.

File: editor/scene/sprite_frames_editor_plugin.cpp [hunk 1]
```diff
@@ -2239,6 +2234,11 @@ SpriteFramesEditor::SpriteFramesEditor() {
 	move_up->connect(SceneStringName(pressed), callable_mp(this, &SpriteFramesEditor::_up_pressed));
 	move_down->connect(SceneStringName(pressed), callable_mp(this, &SpriteFramesEditor::_down_pressed));
 
+	play_bw_from->set_shortcut(ED_SHORTCUT("sprite_frames/play_animation_backwards", TTRC("Play selected animation backwards from current pos."), Key::A));
```
Comment (KoBeWi) [inline editor/scene/sprite_frames_editor_plugin.cpp]: You can't just move tooltips to shortcut name, they are whole sentences. Shortcut names should be names of actions., e..g "Play Backwards".
Restore the tooltips, but remove the bracket part, as shortcuts are automatically shown in tooltip.

Comment (Giganzo) [reply editor/scene/sprite_frames_editor_plugin.cpp]: Are two shortcuts below that have similar style, so followed them. 

Does the longer tooltips need to be restored. Think it might work with just the same text as the animation player uses?

Comment (KoBeWi) [reply editor/scene/sprite_frames_editor_plugin.cpp]: The shortcuts below are still an action name, just longer (and it can't really be shortened).

> Does the longer tooltips need to be restored.

They don't, it's fine either way.

Comment (Giganzo) [reply editor/scene/sprite_frames_editor_plugin.cpp]: > The shortcuts below are still an action name, just longer (and it can't really be shortened).

But they use sentence case.

Comment (KoBeWi) [reply editor/scene/sprite_frames_editor_plugin.cpp]: Yeah, that's inconsistent with other shortcuts. They don't end with a period though, at least.

**Comment by Repiteo** [comment]
Needs rebase

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
