### PR TITLE
WebGL 2.0: Force decompressing non power-of-2 textures with repeat/mipmap

### LINKED ISSUE #33058: Mesh fails to render material with non power of 2 textures [WebGL 2.0]
**Godot version:**
3.2 alpha 3
3.2 master (2869c13ba)

**OS/device including version:**
Mageia Linux 7 x86_64
Mesa 19.1.2, Intel HD Graphics 630
Chromium 77.0.3865.120

**Issue description:**
As seen in #33055, the included project fails to render proper when exported to WebGL 2.0 (GLES3) on Chromium (likely Chrome too) on Linux.

Screenshot_20191025_102519

Among various other errors (that should all be looked into), there is:
```
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
```

Resizing the two textures `WildGrid.png` and `WildNormal.png` to 1024x1024 (from 640x640) fixes the issue:

Screenshot_20191025_103553

Detailed logs:
<details>
<pre>
tmp_js_export.js:7 Godot Engine v3.2.alpha3.official - https://godotengine.org
tmp_js_export.js:7 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
RuntimeEnvironment.ASM_CONSTS @ tmp_js_export.js:7
_emscripten_asm_const_i @ tmp_js_export.js:7
__ZN21AudioDriverJavaScript4initEv @ wasm-047ed5ae-42110:1
__ZN18AudioDriverManager10initializeEi @ wasm-047ed5ae-43443:1
__ZN13OS_JavaScript10initializeERKN2OS9VideoModeEii @ wasm-047ed5ae-45477:1
__ZN4Main6setup2Ey @ wasm-047ed5ae-39116:1
__ZN4Main5setupEPKciPPcb @ wasm-047ed5ae-39118:1
_main @ wasm-047ed5ae-21004:1
RuntimeEnvironment.Module._main @ tmp_js_export.js:7
callMain @ tmp_js_export.js:7
synchronousStart @ tmp_js_export.js:213
Promise.then (async)
Engine.startGame @ tmp_js_export.js:152
(anonymous) @ tmp_js_export.html:258
(anonymous) @ tmp_js_export.html:263
tmp_js_export.js:7 OpenGL ES 3.0 Renderer: WebKit WebGL
tmp_js_export.js:7  
tmp_js_export.js:7 **ERROR**: Texuture 'res://.import/WildNormal.png-20902661572dada35e4e3a9727ad45d6.s3tc.stex' is compressed, has mipmaps but is not of powerf-of-2 size. This does not work on OpenGL ES 3.0.
put_char @ tmp_js_export.js:7
write @ tmp_js_export.js:7
write @ tmp_js_export.js:7
doWritev @ tmp_js_export.js:7
___syscall146 @ tmp_js_export.js:7
___stdio_write @ wasm-047ed5ae-10784:1
___vfprintf_internal @ wasm-047ed5ae-22292:1
_vfprintf @ wasm-047ed5ae-4438:1
__ZN9StdLogger4logvEPKcPib @ wasm-047ed5ae-31711:1
__ZN6Logger10logf_errorEPKcz @ wasm-047ed5ae-2773:1
__ZN6Logger9log_errorEPKcS1_iS1_S1_NS_9ErrorTypeE @ wasm-047ed5ae-38519:1
__ZN15CompositeLogger9log_errorEPKcS1_iS1_S1_N6Logger9ErrorTypeE @ wasm-047ed5ae-44628:1
__ZN2OS11print_errorEPKcS1_iS1_S1_N6Logger9ErrorTypeE @ wasm-047ed5ae-40484:1
__Z16_err_print_errorPKcS0_iS0_16ErrorHandlerType @ wasm-047ed5ae-536:1
__ZN22RasterizerStorageGLES316texture_set_dataE3RIDRK3RefI5ImageEi @ wasm-047ed5ae-41558:1
__ZN18VisualServerRaster16texture_set_dataE3RIDRK3RefI5ImageEi @ wasm-047ed5ae-43214:1
__ZN13StreamTexture4loadERK6String @ wasm-047ed5ae-9101:1
__ZN33ResourceFormatLoaderStreamTexture4loadERK6StringS2_P5Error @ wasm-047ed5ae-40328:1
__ZN14ResourceLoader5_loadERK6StringS2_S2_bP5Error @ wasm-047ed5ae-16141:1
__ZN22ResourceFormatImporter4loadERK6StringS2_P5Error @ wasm-047ed5ae-41397:1
__ZN14ResourceLoader5_loadERK6StringS2_S2_bP5Error @ wasm-047ed5ae-16141:1
__ZN14ResourceLoader4loadERK6StringS2_bP5Error @ wasm-047ed5ae-1119:1
__ZN31ResourceInteractiveLoaderBinary4pollEv @ wasm-047ed5ae-40403:1
__ZN20ResourceFormatLoader4loadERK6StringS2_P5Error @ wasm-047ed5ae-42311:1
__ZN14ResourceLoader5_loadERK6StringS2_S2_bP5Error @ wasm-047ed5ae-16141:1
__ZN14ResourceLoader4loadERK6StringS2_bP5Error @ wasm-047ed5ae-1119:1
__ZN29ResourceInteractiveLoaderText4pollEv @ wasm-047ed5ae-40529:1
__ZN20ResourceFormatLoader4loadERK6StringS2_P5Error @ wasm-047ed5ae-42311:1
__ZN14ResourceLoader5_loadERK6StringS2_S2_bP5Error @ wasm-047ed5ae-16141:1
__ZN14ResourceLoader4loadERK6StringS2_bP5Error @ wasm-047ed5ae-1119:1
__ZN4Main5startEv @ wasm-047ed5ae-39117:1
_main_after_fs_sync @ wasm-047ed5ae-21003:1
RuntimeEnvironment.Module._main_after_fs_sync @ tmp_js_export.js:7
ccall @ tmp_js_export.js:7
(anonymous) @ tmp_js_export.js:7
doCallback @ tmp_js_export.js:7
done @ tmp_js_export.js:7
reconcile @ tmp_js_export.js:7
(anonymous) @ tmp_js_export.js:7
index.openKeyCursor.onsuccess @ tmp_js_export.js:7
IndexedDB (async)
(anonymous) @ tmp_js_export.js:7
req.onsuccess @ tmp_js_export.js:7
IndexedDB (async)
getDB @ tmp_js_export.js:7
getRemoteSet @ tmp_js_export.js:7
(anonymous) @ tmp_js_export.js:7
getLocalSet @ tmp_js_export.js:7
syncfs @ tmp_js_export.js:7
(anonymous) @ tmp_js_export.js:7
syncfs @ tmp_js_export.js:7
RuntimeEnvironment.ASM_CONSTS @ tmp_js_export.js:7
_emscripten_asm_const_i @ tmp_js_export.js:7
_main @ wasm-047ed5ae-21004:1
RuntimeEnvironment.Module._main @ tmp_js_export.js:7
callMain @ tmp_js_export.js:7
synchronousStart @ tmp_js_export.js:213
Promise.then (async)
Engine.startGame @ tmp_js_export.js:152
(anonymous) @ tmp_js_export.html:258
(anonymous) @ tmp_js_export.html:263
Show 10 more frames
tmp_js_export.js:7    At: drivers/gles3/rasterizer_storage_gles3.cpp:758:texture_set_data() - Texuture 'res://.import/WildNormal.png-20902661572dada35e4e3a9727ad45d6.s3tc.stex' is compressed, has mipmaps but is not of powerf-of-2 size. This does not work on OpenGL ES 3.0.
put_char @ tmp_js_export.js:7
write @ tmp_js_export.js:7
write @ tmp_js_export.js:7
doWritev @ tmp_js_export.js:7
___syscall146 @ tmp_js_export.js:7
___stdio_write @ wasm-047ed5ae-10784:1
___vfprintf_internal @ wasm-047ed5ae-22292:1
_vfprintf @ wasm-047ed5ae-4438:1
__ZN9StdLogger4logvEPKcPib @ wasm-047ed5ae-31711:1
__ZN6Logger10logf_errorEPKcz @ wasm-047ed5ae-2773:1
__ZN6Logger9log_errorEPKcS1_iS1_S1_NS_9ErrorTypeE @ wasm-047ed5ae-38519:1
__ZN15CompositeLogger9log_errorEPKcS1_iS1_S1_N6Logger9ErrorTypeE @ wasm-047ed5ae-44628:1
__ZN2OS11print_errorEPKcS1_iS1_S1_N6Logger9ErrorTypeE @ wasm-047ed5ae-40484:1
__Z16_err_print_errorPKcS0_iS0_16ErrorHandlerType @ wasm-047ed5ae-536:1
__ZN22RasterizerStorageGLES316texture_set_dataE3RIDRK3RefI5ImageEi @ wasm-047ed5ae-41558:1
__ZN18VisualServerRaster16texture_set_dataE3RIDRK3RefI5ImageEi @ wasm-047ed5ae-43214:1
__ZN13StreamTexture4loadERK6String @ wasm-047ed5ae-9101:1
__ZN33ResourceFormatLoaderStreamTexture4loadERK6StringS2_P5Error @ wasm-047ed5ae-40328:1
__ZN14ResourceLoader5_loadERK6StringS2_S2_bP5Error @ wasm-047ed5ae-16141:1
__ZN22ResourceFormatImporter4loadERK6StringS2_P5Error @ wasm-047ed5ae-41397:1
__ZN14ResourceLoader5_loadERK6StringS2_S2_bP5Error @ wasm-047ed5ae-16141:1
__ZN14ResourceLoader4loadERK6StringS2_bP5Error @ wasm-047ed5ae-1119:1
__ZN31ResourceInteractiveLoaderBinary4pollEv @ wasm-047ed5ae-40403:1
__ZN20ResourceFormatLoader4loadERK6StringS2_P5Error @ wasm-047ed5ae-42311:1
__ZN14ResourceLoader5_loadERK6StringS2_S2_bP5Error @ wasm-047ed5ae-16141:1
__ZN14ResourceLoader4loadERK6StringS2_bP5Error @ wasm-047ed5ae-1119:1
__ZN29ResourceInteractiveLoaderText4pollEv @ wasm-047ed5ae-40529:1
__ZN20ResourceFormatLoader4loadERK6StringS2_P5Error @ wasm-047ed5ae-42311:1
__ZN14ResourceLoader5_loadERK6StringS2_S2_bP5Error @ wasm-047ed5ae-16141:1
__ZN14ResourceLoader4loadERK6StringS2_bP5Error @ wasm-047ed5ae-1119:1
__ZN4Main5startEv @ wasm-047ed5ae-39117:1
_main_after_fs_sync @ wasm-047ed5ae-21003:1
RuntimeEnvironment.Module._main_after_fs_sync @ tmp_js_export.js:7
ccall @ tmp_js_export.js:7
(anonymous) @ tmp_js_export.js:7
doCallback @ tmp_js_export.js:7
done @ tmp_js_export.js:7
reconcile @ tmp_js_export.js:7
(anonymous) @ tmp_js_export.js:7
index.openKeyCursor.onsuccess @ tmp_js_export.js:7
IndexedDB (async)
(anonymous) @ tmp_js_export.js:7
req.onsuccess @ tmp_js_export.js:7
IndexedDB (async)
getDB @ tmp_js_export.js:7
getRemoteSet @ tmp_js_export.js:7
(anonymous) @ tmp_js_export.js:7
getLocalSet @ tmp_js_export.js:7
syncfs @ tmp_js_export.js:7
(anonymous) @ tmp_js_export.js:7
syncfs @ tmp_js_export.js:7
RuntimeEnvironment.ASM_CONSTS @ tmp_js_export.js:7
_emscripten_asm_const_i @ tmp_js_export.js:7
_main @ wasm-047ed5ae-21004:1
RuntimeEnvironment.Module._main @ tmp_js_export.js:7
callMain @ tmp_js_export.js:7
synchronousStart @ tmp_js_export.js:213
Promise.then (async)
Engine.startGame @ tmp_js_export.js:152
(anonymous) @ tmp_js_export.html:258
(anonymous) @ tmp_js_export.html:263
Show 10 more frames
tmp_js_export.js:7 **ERROR**: Texuture 'res://.import/WildGrid.png-09bc5364f72c31b80b9cdd2ee1128f00.s3tc.stex' is compressed, has mipmaps but is not of powerf-of-2 size. This does not work on OpenGL ES 3.0.
put_char @ tmp_js_export.js:7
write @ tmp_js_export.js:7
write @ tmp_js_export.js:7
doWritev @ tmp_js_export.js:7
___syscall146 @ tmp_js_export.js:7
___stdio_write @ wasm-047ed5ae-10784:1
___vfprintf_internal @ wasm-047ed5ae-22292:1
_vfprintf @ wasm-047ed5ae-4438:1
__ZN9StdLogger4logvEPKcPib @ wasm-047ed5ae-31711:1
__ZN6Logger10logf_errorEPKcz @ wasm-047ed5ae-2773:1
__ZN6Logger9log_errorEPKcS1_iS1_S1_NS_9ErrorTypeE @ wasm-047ed5ae-38519:1
__ZN15CompositeLogger9log_errorEPKcS1_iS1_S1_N6Logger9ErrorTypeE @ wasm-047ed5ae-44628:1
__ZN2OS11print_errorEPKcS1_iS1_S1_N6Logger9ErrorTypeE @ wasm-047ed5ae-40484:1
__Z16_err_print_errorPKcS0_iS0_16ErrorHandlerType @ wasm-047ed5ae-536:1
__ZN22RasterizerStorageGLES316texture_set_dataE3RIDRK3RefI5ImageEi @ wasm-047ed5ae-41558:1
__ZN18VisualServerRaster16texture_set_dataE3RIDRK3RefI5ImageEi @ wasm-047ed5ae-43214:1
__ZN13StreamTexture4loadERK6String @ wasm-047ed5ae-9101:1
__ZN33ResourceFormatLoaderStreamTexture4loadERK6StringS2_P5Error @ wasm-047ed5ae-40328:1
__ZN14ResourceLoader5_loadERK6StringS2_S2_bP5Error @ wasm-047ed5ae-16141:1
__ZN22ResourceFormatImporter4loadERK6StringS2_P5Error @ wasm-047ed5ae-41397:1
__ZN14ResourceLoader5_loadERK6StringS2_S2_bP5Error @ wasm-047ed5ae-16141:1
__ZN14ResourceLoader4loadERK6StringS2_bP5Error @ wasm-047ed5ae-1119:1
__ZN31ResourceInteractiveLoaderBinary4pollEv @ wasm-047ed5ae-40403:1
__ZN20ResourceFormatLoader4loadERK6StringS2_P5Error @ wasm-047ed5ae-42311:1
__ZN14ResourceLoader5_loadERK6StringS2_S2_bP5Error @ wasm-047ed5ae-16141:1
__ZN14ResourceLoader4loadERK6StringS2_bP5Error @ wasm-047ed5ae-1119:1
__ZN29ResourceInteractiveLoaderText4pollEv @ wasm-047ed5ae-40529:1
__ZN20ResourceFormatLoader4loadERK6StringS2_P5Error @ wasm-047ed5ae-42311:1
__ZN14ResourceLoader5_loadERK6StringS2_S2_bP5Error @ wasm-047ed5ae-16141:1
__ZN14ResourceLoader4loadERK6StringS2_bP5Error @ wasm-047ed5ae-1119:1
__ZN4Main5startEv @ wasm-047ed5ae-39117:1
_main_after_fs_sync @ wasm-047ed5ae-21003:1
RuntimeEnvironment.Module._main_after_fs_sync @ tmp_js_export.js:7
ccall @ tmp_js_export.js:7
(anonymous) @ tmp_js_export.js:7
doCallback @ tmp_js_export.js:7
done @ tmp_js_export.js:7
reconcile @ tmp_js_export.js:7
(anonymous) @ tmp_js_export.js:7
index.openKeyCursor.onsuccess @ tmp_js_export.js:7
IndexedDB (async)
(anonymous) @ tmp_js_export.js:7
req.onsuccess @ tmp_js_export.js:7
IndexedDB (async)
getDB @ tmp_js_export.js:7
getRemoteSet @ tmp_js_export.js:7
(anonymous) @ tmp_js_export.js:7
getLocalSet @ tmp_js_export.js:7
syncfs @ tmp_js_export.js:7
(anonymous) @ tmp_js_export.js:7
syncfs @ tmp_js_export.js:7
RuntimeEnvironment.ASM_CONSTS @ tmp_js_export.js:7
_emscripten_asm_const_i @ tmp_js_export.js:7
_main @ wasm-047ed5ae-21004:1
RuntimeEnvironment.Module._main @ tmp_js_export.js:7
callMain @ tmp_js_export.js:7
synchronousStart @ tmp_js_export.js:213
Promise.then (async)
Engine.startGame @ tmp_js_export.js:152
(anonymous) @ tmp_js_export.html:258
(anonymous) @ tmp_js_export.html:263
Show 10 more frames
tmp_js_export.js:7    At: drivers/gles3/rasterizer_storage_gles3.cpp:758:texture_set_data() - Texuture 'res://.import/WildGrid.png-09bc5364f72c31b80b9cdd2ee1128f00.s3tc.stex' is compressed, has mipmaps but is not of powerf-of-2 size. This does not work on OpenGL ES 3.0.
put_char @ tmp_js_export.js:7
write @ tmp_js_export.js:7
write @ tmp_js_export.js:7
doWritev @ tmp_js_export.js:7
___syscall146 @ tmp_js_export.js:7
___stdio_write @ wasm-047ed5ae-10784:1
___vfprintf_internal @ wasm-047ed5ae-22292:1
_vfprintf @ wasm-047ed5ae-4438:1
__ZN9StdLogger4logvEPKcPib @ wasm-047ed5ae-31711:1
__ZN6Logger10logf_errorEPKcz @ wasm-047ed5ae-2773:1
__ZN6Logger9log_errorEPKcS1_iS1_S1_NS_9ErrorTypeE @ wasm-047ed5ae-38519:1
__ZN15CompositeLogger9log_errorEPKcS1_iS1_S1_N6Logger9ErrorTypeE @ wasm-047ed5ae-44628:1
__ZN2OS11print_errorEPKcS1_iS1_S1_N6Logger9ErrorTypeE @ wasm-047ed5ae-40484:1
__Z16_err_print_errorPKcS0_iS0_16ErrorHandlerType @ wasm-047ed5ae-536:1
__ZN22RasterizerStorageGLES316texture_set_dataE3RIDRK3RefI5ImageEi @ wasm-047ed5ae-41558:1
__ZN18VisualServerRaster16texture_set_dataE3RIDRK3RefI5ImageEi @ wasm-047ed5ae-43214:1
__ZN13StreamTexture4loadERK6String @ wasm-047ed5ae-9101:1
__ZN33ResourceFormatLoaderStreamTexture4loadERK6StringS2_P5Error @ wasm-047ed5ae-40328:1
__ZN14ResourceLoader5_loadERK6StringS2_S2_bP5Error @ wasm-047ed5ae-16141:1
__ZN22ResourceFormatImporter4loadERK6StringS2_P5Error @ wasm-047ed5ae-41397:1
__ZN14ResourceLoader5_loadERK6StringS2_S2_bP5Error @ wasm-047ed5ae-16141:1
__ZN14ResourceLoader4loadERK6StringS2_bP5Error @ wasm-047ed5ae-1119:1
__ZN31ResourceInteractiveLoaderBinary4pollEv @ wasm-047ed5ae-40403:1
__ZN20ResourceFormatLoader4loadERK6StringS2_P5Error @ wasm-047ed5ae-42311:1
__ZN14ResourceLoader5_loadERK6StringS2_S2_bP5Error @ wasm-047ed5ae-16141:1
__ZN14ResourceLoader4loadERK6StringS2_bP5Error @ wasm-047ed5ae-1119:1
__ZN29ResourceInteractiveLoaderText4pollEv @ wasm-047ed5ae-40529:1
__ZN20ResourceFormatLoader4loadERK6StringS2_P5Error @ wasm-047ed5ae-42311:1
__ZN14ResourceLoader5_loadERK6StringS2_S2_bP5Error @ wasm-047ed5ae-16141:1
__ZN14ResourceLoader4loadERK6StringS2_bP5Error @ wasm-047ed5ae-1119:1
__ZN4Main5startEv @ wasm-047ed5ae-39117:1
_main_after_fs_sync @ wasm-047ed5ae-21003:1
RuntimeEnvironment.Module._main_after_fs_sync @ tmp_js_export.js:7
ccall @ tmp_js_export.js:7
(anonymous) @ tmp_js_export.js:7
doCallback @ tmp_js_export.js:7
done @ tmp_js_export.js:7
reconcile @ tmp_js_export.js:7
(anonymous) @ tmp_js_export.js:7
index.openKeyCursor.onsuccess @ tmp_js_export.js:7
IndexedDB (async)
(anonymous) @ tmp_js_export.js:7
req.onsuccess @ tmp_js_export.js:7
IndexedDB (async)
getDB @ tmp_js_export.js:7
getRemoteSet @ tmp_js_export.js:7
(anonymous) @ tmp_js_export.js:7
getLocalSet @ tmp_js_export.js:7
syncfs @ tmp_js_export.js:7
(anonymous) @ tmp_js_export.js:7
syncfs @ tmp_js_export.js:7
RuntimeEnvironment.ASM_CONSTS @ tmp_js_export.js:7
_emscripten_asm_const_i @ tmp_js_export.js:7
_main @ wasm-047ed5ae-21004:1
RuntimeEnvironment.Module._main @ tmp_js_export.js:7
callMain @ tmp_js_export.js:7
synchronousStart @ tmp_js_export.js:213
Promise.then (async)
Engine.startGame @ tmp_js_export.js:152
(anonymous) @ tmp_js_export.html:258
(anonymous) @ tmp_js_export.html:263
Show 10 more frames
tmp_js_export.html:1 [.WebGL-0x562bf6931190]GL ERROR :GL_INVALID_OPERATION : glCompressedTexImage2D: width or height invalid for level
tmp_js_export.html:1 [.WebGL-0x562bf6931190]GL ERROR :GL_INVALID_OPERATION : glCompressedTexImage2D: width or height invalid for level
tmp_js_export.html:1 [.WebGL-0x562bf6931190]GL ERROR :GL_INVALID_OPERATION : glDrawElements: uniform buffers : no buffer bound at index 4
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[.WebGL-0x562bf6931190]RENDER WARNING: texture bound to texture unit 4 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
tmp_js_export.html:1 WebGL: too many errors, no more errors will be reported to the console for this context.
</pre>
</details>

@clayjohn @reduz How should we solve this? I think we already added some code to resize to po2 on mobile platforms where needed, should this just be changed to include WebGL?

**Steps to reproduce:**
- Switch attached project to GLES3
- Export to HTML5, load in Chromium

**Minimal reproduction project:**
[MissingSphereIssue.zip](https://github.com/godotengine/godot/files/3770809/MissingSphereIssue.zip)

### PR DESCRIPTION
**Pull request by akien-mga**
While OpenGL ES 3.0 and WebGL 2.0 both support non power-of-2 (NPOT)
textures in their specification, the situation seems to be less clear
about *compressed* NPOT textures using repeat or mipmap flags.

At least Chrome on Linux doesn't seem to support this combination,
and a variety of mobile hardware have similar limitations.

As a workaround, we force decompressing such textures when running on
WebGL 2.0, at the cost of loading time and memory usage.

Fixes #33058.

### CODE REVIEW

**Comment by akien-mga** [comment]
This is probably not the right fix as discussed with @reduz. OpenGL ES 3.0 and WebGL 2.0 **should** support NPOT textures as per specification: https://www.khronos.org/registry/webgl/specs/latest/2.0/#4.1.3

But the problem seems to be that mobile hardware (and thus likely browser WebGL implementation for consistency) don't all support **compressed** NPOT textures, which is a badly specified hole in the spec. So here we are.

An option would be to add some code only for WebGL that would just uncompress NPOT textures (resizing them might not be necessary).

> (alternatively, we could add a Web-specific import preset for S3TC, to
allow having both PC S3TC non-resized and Web S3TC resized imported
textures).

This would still be the better option though IMO.

**Comment by akien-mga** [comment]
> An option would be to add some code only for WebGL that would just uncompress NPOT textures (resizing them might not be necessary).

I pushed an update to do that.

**Comment by akien-mga** [comment]
Tested successfully on Firefox Beta and Chrome on Android (current versions), and Chrom(ium) on Linux. Firefox can't be tested on Linux due to #33058.

File: drivers/gles3/rasterizer_storage_gles3.cpp [hunk 1]
```diff
@@ -753,13 +767,9 @@ void RasterizerStorageGLES3::texture_set_data(RID p_texture, const Ref<Image> &p
 	if (config.keep_original_textures && !(texture->flags & VS::TEXTURE_FLAG_USED_FOR_STREAMING)) {
 		texture->images.write[p_layer] = p_image;
 	}
-#ifndef GLES_OVER_GL
-	if (p_image->is_compressed() && p_image->has_mipmaps() && !p_image->is_size_po2()) {
-		ERR_PRINTS("Texuture '" + texture->path + "' is compressed, has mipmaps but is not of powerf-of-2 size. This does not work on OpenGL ES 3.0.");
```
Comment (akien-mga) [inline drivers/gles3/rasterizer_storage_gles3.cpp]: I removed this as AFAIK, we force resizing to power of 2 sizes when compressing to ETC, ETC2 or PVRTC. So S3TC on WebGL was the only situation where this would not happen, and it should now be fixed by this forced decompression.

**Review by clayjohn — APPROVED** [review]
