### PR TITLE
Tweak comments in `renames_map_3_to_4` & reorder

### LINKED ISSUE #73143: 3-to-4 conversion renames all "remove" functions
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Steam OS Holo, Steam Deck

### Issue description

The conversion rule renaming `remove` to `remove_at` for `Array` objects is applied to all functions named `remove`.

### Steps to reproduce

Create a 3.0 project with a function called "remove" in any script:
```gdscript
extends Node

func remove():
	pass
```

After converting to 4.0, the function will be called "remove_at":
```gdscript
extends Node

func remove_at():
	pass
```

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Mickeon**
Fixes https://github.com/godotengine/godot/issues/73143.

This PR is part one of something mainly done because it was making me insane. Conveniently, [it is now also suggested to check the list out in the documentation](https://docs.godotengine.org/en/latest/tutorials/migrating/upgrading_to_godot_4.html#list-of-automatically-renamed-methods-properties-signals-and-constants), and I believed it would only be fair to make the this enormous list at least a bit more readable.

Generally moves comments and some entries around, as well as fixing typos and miscellaneous inconsistencies.

To go more in detail on a few things:

- In comments, separate between class names and notes with "--";
- In comments, replace all "_broke_" with "_-- Breaks_"
- Moves `@GlobalScope` constants to its own group in `enum_renames`
- Move `{ "remove", "remove_at" },` underneath the Builtin Types methods.
   - Commented out, fixes https://github.com/godotengine/godot/issues/73143.
- Move C#'s `AddNode3dGizmoPlugin` to where it should be, in alphabetical order.
- Give more details to some class renames.

### CODE REVIEW

File: editor/renames_map_3_to_4.cpp [hunk 1]
```diff
@@ -574,22 +574,23 @@ const char *RenamesMap3To4::gdscript_function_renames[][2] = {
...
+	{ "clamped", "clamp" }, // Vector2 -- Be careful, this will be used everywhere.
 	{ "get_rotation_quat", "get_rotation_quaternion" }, // Basis
 	{ "grow_margin", "grow_side" }, // Rect2
-	{ "invert", "reverse" }, // Array - TODO check  // Be careful, this will be used everywhere
+	{ "invert", "reverse" }, // Array -- Give it a check. Be careful, this will be used everywhere.
 	{ "is_abs_path", "is_absolute_path" }, // String
 	{ "is_valid_integer", "is_valid_int" }, // String
 	{ "linear_interpolate", "lerp" }, // Color
 	{ "find_last", "rfind" }, // Array, String
+	{ "remove", "remove_at" }, // Array -- Breaks Directory and several more.
```
Comment (akien-mga) [inline editor/renames_map_3_to_4.cpp:587]: This should be commented out, as it does break stuff: #73143

File: editor/renames_map_3_to_4.cpp [hunk 2]
```diff
@@ -574,22 +574,23 @@ const char *RenamesMap3To4::gdscript_function_renames[][2] = {
...
 	{ "to_ascii", "to_ascii_buffer" }, // String
 	{ "to_utf8", "to_utf8_buffer" }, // String
-	{ "to_wchar", "to_utf32_buffer" }, // String // TODO - utf32 or utf16?
+	{ "to_wchar", "to_utf32_buffer" }, // String -- utf32 or utf16?
```
Comment (akien-mga) [inline editor/renames_map_3_to_4.cpp:590]: That TODO should be resolved probably. @bruvzg

File: editor/renames_map_3_to_4.cpp [hunk 3]
```diff
@@ -614,53 +615,52 @@ const char *RenamesMap3To4::gdscript_function_renames[][2] = {
...
+	// { "SetOffset", "SetProgress" }, // PathFollow2D, PathFollow3D -- Too common.
+	// { "SetProcessMode", "SetProcessCallback" }, // AnimationTree -- Breaks Node, Tween, Sky.
+	// { "SetRefuseNewNetworkConnections", "SetRefuseNewConnections"}, // MultiplayerAPI -- Breaks SceneTree.
+	// { "SetTooltip", "SetTooltipText" }, // Control -- Breaks TreeItem, at least for now.
+	// { "SetUv", "SurfaceSetUv" }, // ImmediateMesh -- Breaks Polygon2D.
+	// { "SetVOffset", "SetDragVerticalOffset" }, // Camera2D -- Breaks Camera3D, PathFollow3D, PathFollow2D.
+	// {"GetPoints","GetPointsId" }, // AStar -- Breaks Line2D, ConvexPolygonShape.
+	// {"GetVScroll","GetVScrollBar" }, // ItemList -- Breaks TextView.
+	// { "GetStylebox", "GetThemeStylebox" }, // Control -- Would rename the method in Theme as well, skipping.
 	{ "RenderingServer", "GetTabAlignment" }, // Tab
```
Comment (akien-mga) [inline editor/renames_map_3_to_4.cpp:664]: I'd remove this since you noticed it, it's obviously bogus.

File: editor/renames_map_3_to_4.cpp (hunk 2 above)
Comment (bruvzg) [reply editor/renames_map_3_to_4.cpp:590]: It depends on OS, `to_utf16_buffer` if it's Windows, `to_utf32_buffer` if not. Maybe we should expose `to_wchar_buffer` as well?

Comment (bruvzg) [reply editor/renames_map_3_to_4.cpp:590]: https://github.com/godotengine/godot/pull/73225

**Review by YuriSizov — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks! If you're looking for more actionables in the convertor, check out the replies to [this tweet](https://twitter.com/YuriSizov/status/1625820392676794370) and [this post](https://mastodon.gamedev.place/@yurisizov/109868536370429869).
