### PR TITLE
Property list changes are only notified when it did change in Curve

### LINKED ISSUE #74865: Curve Editor gets re-constructed after every operation.
### Godot version

4.0

### System information

Ubuntu 22.04.1 LTS

### Issue description

The CurveEditor constructor is called every time you do any operation. This is for example why handles get deselected after you drag them.

Upon investigation, it appears that this is because Curve's methods `add_point()` and `remove_point()` call `notify_property_list_changed()`. This was added as a fix in #61628, which fixed a regression most likely from #58023.

This bug isn't a big deal at the moment, but I'm currently making a PR to rework the curve editor and this bug is blocking it completely.

### Steps to reproduce

Create a Curve.
Add a point.
Move the point.
Watch it get deselected.

### Minimal reproduction project

N/A takes 10sec to set up, moreover the best way to see this is by playing with the source code.

### PR DESCRIPTION
**Pull request by Rindbee**
`Object::notify_property_list_changed()` should only be called when the structure of the property has actually changed.

The structure of the property tree has not changed if the size of the array has not changed, and the only possibility is that the element value has changed.

Fix #74865.

### CODE REVIEW

**Comment by MewPurPur** [comment]
Hmm, it's nice that it fixes the most visible symptom of my issue. But reconstructing the curve editor when adding or removing points is still awkward and not really done by other editors.

Right now I've got a WIP commit where I implement a snap button. Every time I add a point, the snap button gets unselected. Makes the whole thing dysfunctional. The re-constructing issue needs a broader solution and this only helps it.

**Comment by Rindbee** [comment]
> but the curve editor will still be reconstructed when adding or removing points, which isn't expected behavior.

Because when adding or removing array elements, the structure of the property tree does change.

Perhaps when the size of Array changes, we can try to use a new signal to specifically notify this change.  Make these array properties behave like a sub-inspector in the inspector like `EditorPropertyResource`.

**Comment by Rindbee** [comment]
And `EditorInspector::update_tree()` is not only a **redraw** process, but also a **rebuild** process. I think it is more appropriate to rename it to `EditorInspector::rebuild_tree()`. One reason the editor is not smooth is that it is called too often. Usually for the whole tree.

**Comment by anvilfolk** [comment]
Did a very quick look - the thought process and changes do seem to make sense. I like the discussion around making a sub-editor just for the points though, since that would allow changing points without resetting the rest of the editor. I think that would help @MewPurPur 's future efforts to add snapping!

Any chance that makes sense to add in this PR, or is that a future PR?

**Comment by YuriSizov** [comment]
I don't see why we would need to redraw the entire tree when the structure of an array or a dictionary property changes. It's all handled by a single editor property control (from the POV of the inspector), we don't really need to update the entire tree.

**Comment by anvilfolk** [comment]
@YuriSizov so the issue is that the points of the curve are individually exported as properties. The curve doesn't export the array of points:

https://github.com/godotengine/godot/blob/c0a48a343fb687a7511a639cad18f651afbedf67/scene/resources/curve.cpp#L1263-L1281

Whereas, for instance, `GradientTexture2D` directly exports the underlying packed arrays. This means that the property list doesn't change, and therefore the inspector tree isn't rebuilt (to display the "new" properties). For `Curve`, since the property list changed, the inspector is going to rebuild the tree in order to display all the properties.

Unfortunately, I believe it would be a compatibility-breaking change to directly export the underlying point & tangent arrays directly.

I think maybe the way to handle this is to follow up on the idea of having a subinspector just for the points, and that's what gets updated when the property list changes, leaving the rest untouched (particularly, the visual curve editor itself), which is at the origin of this bug. But I also don't fully understand UI and whether this is possible :)

**Comment by Rindbee** [comment]
The array here refers to using `ADD_ARRAY`/`ADD_ARRAY_COUNT` and `_get_property_list()` to organize the properties of the object into an array (like an array of structures).

File: scene/resources/curve.cpp [hunk 1]
```diff
@@ -431,7 +441,9 @@ void Curve::set_data(const Array p_input) {
 	}
 
 	mark_dirty();
-	notify_property_list_changed();
+	if (old_size != new_size) {
+		notify_property_list_changed();
+	}
```
Comment (YuriSizov) [inline scene/resources/curve.cpp:446]: I wonder if this will work correctly if you set the data of the same size. It's possible that the existing properties won't update to their new states, though it's probably fine.

**Review by YuriSizov — APPROVED** [review]
Well, I guess it makes sense to make this change for now to speed things up a bit. Looks like a proper solution would require bigger changes to the way we work with the property list in the inspector.

File: scene/resources/curve.cpp (hunk 1 above)
Comment (Rindbee) [reply scene/resources/curve.cpp:446]: It shouldn't depend on the `property_list_changed` signal if it's just updating state. It may be more dependent on the `changed` signal that will be emitted in `Curve::mark_dirty()`.

Comment (YuriSizov) [reply scene/resources/curve.cpp:446]: Yeah, it shouldn't, it just might, given this is how it works now. Well, we'll know soon enough :)

**Comment by YuriSizov** [comment]
Thanks!
