### PR TITLE
Optimize Occlusion culling jitter

### LINKED ISSUE #53288: Raster occlusion incorrectly culls objects through gaps
### Godot version

4.0 dev df57aa670

### System information

Linux Mint 20, Intel HD graphics 630

### Issue description

Objects are being culled when they should be visible, in cases where there are small gaps between occluders.

Setup:
Screenshot from 2021-10-01 08-45-37
What should be seen:
Screenshot from 2021-10-01 08-45-23
What is seen:
Screenshot from 2021-10-01 08-45-09
Occlusion buffer:
Screenshot from 2021-10-01 08-46-23

### Steps to reproduce

Create a couple of boxes as occluders and place them with a small gap, then attempt to view a 3rd object through the gap. Vary the viewing angle / distance.

### Minimal reproduction project

[TestOcclusion.zip](https://github.com/godotengine/godot/files/7265271/TestOcclusion.zip)

### Discussion

I'm just having a look at some situations likely to trip up the raster occlusion, especially edges / joins between objects. I'm guessing this is caused by the rendering of the occlusion buffer not being conservative (or rather the opposite of conservative rasterization :smile: ), i.e. gaps between objects are being joined. This makes occlusion more effective, but produces visual artifacts.

This one can be quite disturbing as objects flicker in and out of view according to the viewing angle, and whether or not a gap is rendered in the occlusion buffer.

### PR DESCRIPTION
**Pull request by Flarkk**
This PR ensures the jittering is applied in a uniform manner across the whole viewport.
Previously, pixels ~closer to the center~ with farther Z used to get less jitter than those on the edge, as a side effect of perspective division.

This is achieved by jittering the near plane corners instead of the projection matrix, as only those are ultimately passed to embree in the end anyway.

Test project : [occlusion_jitter.zip](https://github.com/user-attachments/files/17983531/occlusion_jitter.zip)

This improvement supersedes the fix in #99941.

| Before | After |
|---|---|
|391694701-b5ee252d-38ba-4d0e-904b-fb8b7ee9ea80|output |

**Edit** : Resolves #53288

### CODE REVIEW

**Comment by lawnjelly** [comment]
So this is effectively jittering the translation rather than the camera rotation, as discussed in https://github.com/godotengine/godot/pull/99941#issuecomment-2513757948 ?

I did think of a snag with translation though ... if my thinking is correct, rotation does have the advantage that it automatically compensates for distance:

The effective gap which will cause the problem described in #53288 does depend on distance, because it's the screen space distance that determines whether two adjacent walls will "merge" in the occlusion buffer. Rotation of the camera means the screen space change of jittered objects will increase with distance I think.

Translation will cause the opposite effect if I'm correct (with perspective projection):
* Objects close to the camera will be shifted *more* than objects far away, rather than less

I suspect we need to make sure the test case works correctly at different distances.

**Comment by Flarkk** [comment]
So this is the opposite : this PR jitters more like a rotation, while it's a transation right now.

You're right that translating moves closer objects more.
This is precisely why the sphere jitters more on the left : due to the spherical shape and the perspective, pixels on its left side are closer than those on its right side.
The box has instead a uniform jitter because it's flat and in the XY plane.

The current implementation (with my last PR merged) translates the whole scene relatively to the rays (equivalently the rays relatively to the scene) in clip space.

What this PR does is actually the alternative you mention above.
It translates *only the tips* of the rays on the near plane (their origin - the camera - stays fixed).
This acts more like a rotation with the additional benefit of allowing pixel perfect jittering.
Of course the implementation doesn't jitter each ray one by one, but instead the near plane bottom-left corner. As the code then interpolates from this corner across X and Y over the whole near plane to determine the rays' tips, this effectively jitters each ray.

Will take a look at #53288 and see if this PR solves the problem.

**Comment by Flarkk** [comment]
Rebased on top of #99941

**Comment by lawnjelly** [comment]
> So this is the opposite : this PR jitters more like a rotation, while it's a translation right now.

If this is the case, this should indeed be an improvement. Yup some decent testing over the distance range will be good.

If I remember right, ideally we should like to see objects jitter by around a pixel (just under in fact) no matter the distance from the camera.

**Comment by Flarkk** [comment]
I updated the PR to set the jitter magnitude to 0.99 pixel.

With these settings I confirm that :
- jitter is 1 pixel wide no matter the occluder's Z position
- no occluder does not jitter (when the amplitude is set too low below 1, it can happen that an occluder's edge is jittered within the same pixel)

[occlusion_jitter_2.zip](https://github.com/user-attachments/files/18009332/occlusion_jitter_2.zip)

The more to the right, the farther :
| Scene top view | Result |
|---|---|
| Capture d’écran du 2024-12-04 14-40-04 | output1 |


I can also confirm that this seems to greatly improve the situation described in #53288.
The gap causing the red box to be culled is now much smaller and coincides with the moment jitter fills the gap over all 9 frames.

| Not culled | Culled |
|---|---|
|Capture d’écran du 2024-12-04 14-45-17 | Capture d’écran du 2024-12-04 14-43-41 |
| output | output2 |

**Comment by lawnjelly** [comment]
That looks great.

From memory I suspect the ideal value (less than 1) for the current pattern may be 0.66, so this is worth testing too.

The jitter pattern I think is one in the centre, a medium square and a distance square (9 in total). At 1, I suspect it would be mimicking the situation where the whole scene was shifted to the left by a whole pixel, so I'm not absolutely sure we gain as much in terms of resolution.

Effectively by jittering we are aiming to increase the resolution of the occlusion buffer, in this case by 9x (with 3 x the resolution on each axis), therefore the fractions should be 0.0 (centre), 0.333 (mid square), 0.666 (far square). The multiplier we are changing here is for the far square as the mid square is multiplied by 0.5.

Essentially the way I was thinking is that by regularizing this, we are maximizing the chance of a gap occurring in the occlusion buffer for these gaps.

The alternative of a more random pattern is potentially even better, but suffers from difficulty in repeatability for the timeout (of course you could use a fixed random pattern as an alternative).

We can increase the resolution higher with more samples, but that increases the timeout required for stability and makes it more liable to pop in.

**Comment by Flarkk** [comment]
With 0.66.
Looks like the gap is even smaller.
Will change the PR right away.

| Not culled | Culled |
|---|---|
| image | Capture d’écran du 2024-12-04 17-04-01 |
| output2 | output |

**Comment by lawnjelly** [comment]
Sounds good.

I suppose if the occlusion buffer was a certain fixed integer multiple proportion of the screen resolution it should be possible to remove the problem entirely by this super sampling, but the choice of occlusion buffer size is currently pretty complex to do with how many cores. I think we'd need there to be people reporting problems for us to do things like start altering the occlusion buffer sizes.

e.g. at 1920x1080 you would use e.g. 480x270, and use 3 extra temporal jittered samples on each axis.

Might be worth doing on e.g. a console, but probably not for general use at the moment.

File: modules/raycast/raycast_occlusion_cull.cpp [hunk 1]
```diff
@@ -80,23 +80,22 @@ void RaycastOcclusionCull::RaycastHZBuffer::resize(const Size2i &p_size) {
 	memset(camera_ray_masks.ptr(), ~0, camera_rays_tile_count * TILE_RAYS * sizeof(uint32_t));
 }
 
-void RaycastOcclusionCull::RaycastHZBuffer::update_camera_rays(const Transform3D &p_cam_transform, const Projection &p_cam_projection, bool p_cam_orthogonal) {
+void RaycastOcclusionCull::RaycastHZBuffer::update_camera_rays(const Transform3D &p_cam_transform, const Vector3 &p_near_bottom_left, const Vector2 p_near_extents, float p_z_far, bool p_cam_orthogonal) {
```
Comment (lawnjelly) [inline modules/raycast/raycast_occlusion_cull.cpp:83]: I did wonder if `p_z_far` should be `real` but it looks like there are already assumptions for 32 bit in the `CameraRayThreadData`.

Comment (lawnjelly) [reply modules/raycast/raycast_occlusion_cull.cpp:83]: Presumably it should it be `const Vector2 &p_near_extents` if it is const?

Comment (Flarkk) [reply modules/raycast/raycast_occlusion_cull.cpp:83]: Right. That being said I always wondered if it wouldn't allow more compiler optimization to pass such small structs (2 `real`s ...) by value

File: modules/raycast/raycast_occlusion_cull.cpp [hunk 2]
```diff
@@ -570,16 +569,16 @@ Projection RaycastOcclusionCull::_jitter_projection(const Projection &p_cam_proj
...
-	// Higher divergence gives fewer false hidden, but more false shown.
+	jitter *= Vector2(p_half_extents.x / (float)p_viewport_size.x, p_half_extents.y / (float)p_viewport_size.y);
+
+	// The multiplier here determines the jitter magnitude in pixels.
+	// It seems like a value of 0.66 matches well the above jittering pattern as it generates subpixel samples at 0, 1/3 and 2/3
+	// Higher magnitude gives fewer false hidden, but more false shown.
 	// False hidden is obvious to viewer, false shown is not.
 	// False shown can lower percentage that are occluded, and therefore performance.
-	jitter *= Vector2(1 / (float)p_viewport_size.x, 1 / (float)p_viewport_size.y) * 0.9f;
+	jitter *= 0.66;
```
Comment (lawnjelly) [inline modules/raycast/raycast_occlusion_cull.cpp:579]: `0.66f` will do 32 bit calculation on 32 bit. 64 bit calculation not needed on 32 bit I don't think.

File: modules/raycast/raycast_occlusion_cull.cpp (hunk 1 above)
Comment (Flarkk) [reply modules/raycast/raycast_occlusion_cull.cpp:83]: On your first point, I'll make it `real`. It doesn't cost much

Comment (lawnjelly) [reply modules/raycast/raycast_occlusion_cull.cpp:83]: Generally in Godot we go with `const &` for anything over 64 bit.

In this case I'd hazard a guess the compiler won't care either way in release, as you've marked it as `const`.

**Review by lawnjelly — APPROVED** [review]

**Comment by lawnjelly** [comment]
I'm not super familiar with the 4.x release process now, but will bump to 4.4 and add to 4.4 merge queue as this should be a good addition.

**Comment by Repiteo** [comment]
Thanks!
