### PR TITLE
Disallow nested custom multiplayers in `SceneTree`

### LINKED ISSUE #77817: The 'get_multiplayer' method cannot obtain the value obtained by the 'set_multiplayer' method
### Godot version

4.1.dev

### System information

Window 10

### Issue description

If the result is what you expect, why not block it when you set the value, the value is successfully set in the Map, but when you get it, it's not what you expect, and you make mistakes.
微信图片编辑_20230604044018

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by AThousandShips**
Enables clearing the custom multiplayer

Considering further restricting to only absolute paths (the only thing that makes sense imo)

* Fixes: #77817 (resolves the issue raised)

### CODE REVIEW

**Comment by Faless** [comment]
I understand the issue, and I see how this can be confusing, but this PR heavily de-optimize the most common case (having few custom multiplayer instances and deep path names).

You can test this with the following script ([full project](https://github.com/godotengine/godot/files/11664849/test.zip)):

```gdscript
extends Node

const MULTIPLAYERS = 4
const PATH_DEPTH = 10
const CALLS = 10000

var nodes = []

func build():
	for i in range(MULTIPLAYERS):
		var s = Control.new()
		var cur = s
		for j in range(PATH_DEPTH):
			var step = Control.new()
			cur.add_child(step)
			cur = step
		add_child(s)
		nodes.append(cur)
	for i in range(MULTIPLAYERS):
		get_tree().set_multiplayer(SceneMultiplayer.new(), get_child(i).get_path())

func _ready():
	build()
	test()
	var args := OS.get_cmdline_user_args()
	if args.size() and args[0] == "q":
		get_tree().quit.call_deferred()


# Tests a single node, searching for its custom multiplayer parent
func _test_call(node: Node):
	var mp : MultiplayerAPI
	var time = Time.get_ticks_usec()
	for i in range(CALLS):
		mp = node.multiplayer
	return Time.get_ticks_usec() - time


# Tests each node for its custom multiplayer parent
func test():
	var time = Time.get_ticks_usec()
	var avg = 0
	for node in nodes:
		avg += _test_call(node)
	return avg / nodes.size()
```

Benchmarks for optimized editor builds (using [hyperfine](https://github.com/sharkdp/hyperfine))

```bash
$ ~/Downloads/hyperfine --warmup 3 --runs 10 '~/godot-a --path ~/Downloads/mp_test/ --headless -- q' '~/godot-b --path ~/Downloads/mp_test/ --headless -- q'
Benchmark 1: ~/godot-a --path ~/Downloads/mp_test/ --headless -- q
  Time (mean ± σ):     161.2 ms ±   9.4 ms    [User: 121.9 ms, System: 16.5 ms]
  Range (min … max):   151.4 ms … 174.4 ms    10 runs
 
Benchmark 2: ~/godot-b --path ~/Downloads/mp_test/ --headless -- q
  Time (mean ± σ):     294.0 ms ±   3.4 ms    [User: 183.3 ms, System: 24.1 ms]
  Range (min … max):   288.6 ms … 300.0 ms    10 runs
 
Summary
  ~/godot-a --path ~/Downloads/mp_test/ --headless -- q ran
    1.82 ± 0.11 times faster than ~/godot-b --path ~/Downloads/mp_test/ --headless -- q

```

As per the original issue, I think we should simply disallow having nested custom multiplayer APIs.

**Comment by AThousandShips** [comment]
Gotcha! Will investigate and restructure

**Comment by AThousandShips** [comment]
This doesn't handle the case when a custom API is configured for a descendant of the new path, unsure how to deal with that case

**Review by Faless — COMMENTED** [review]
This change was approved in the 2023-07-06 networking meeting (subject to further code review).
If someone has good reasons for using nested custom multiplayer implementations a proposal should be open outlining the use case(s).

**Review by Faless — COMMENTED** [review]
Sorry it took me a while.
This looks great, I've realized it still allows setting the child first and the parent after it.
But that actually works as expected during retrieval (as we use a HashSet which preserves ordering, and not an RBSet which doesn't).
I think this is okay so if one really really wants nested custom multiplayers, there is a way at least, as hacky as it is.

In case, we should probably update the commit message to something like:

`Disallow set_multiplayer if there is one configured for a parent path.`

I guess we'll have to re-discuss it this week. Sorry :crying_cat_face:

**Comment by AThousandShips** [comment]
No worries! And agreed, noticed the same limitation/quirk before but now you're right about that part

I think unless I come up with a clean way to identify and handle those cases I'll leave it as is in that sense, to not complicate the process, but I will consider how to approach it

Could for example add a warning if setting a nested path, should be trivial to identify it (i.e. if a path is a prefix of another path), but will ponder

**Comment by AThousandShips** [comment]
In that case I will update the wording in the docs too to something like:
"Will error if an API is already configured for a parent" etc.

File: scene/main/scene_tree.cpp [hunk 1]
```diff
@@ -1519,10 +1522,30 @@ void SceneTree::set_multiplayer(Ref<MultiplayerAPI> p_multiplayer, const NodePat
...
+				const StringName *sptr = snames.ptr();
+				bool valid = true;
+				for (int i = 0; i < snames.size(); i++) {
+					if (sptr[i] != nptr[i]) {
+						valid = false;
+						break;
+					}
+				}
+				ERR_FAIL_COND_MSG(valid, "Multiplayer is already configured for a parent of this path: '" + p_root_path + "' in '" + E.key + "'.");
+			}
```
Comment (Faless) [inline scene/main/scene_tree.cpp:1542]: I think this check applies only when `p_multiplayer.is_valid()`.
I know this is pretty nested already, maybe we can refactor the outer ifs as an alternative? In any case, I'd avoid failing during removal.

Comment (AThousandShips) [reply scene/main/scene_tree.cpp:1542]: How about this?

Comment (AThousandShips) [reply scene/main/scene_tree.cpp:1542]: Wait one moment

Comment (Faless) [reply scene/main/scene_tree.cpp:1542]: Oh that's nice!

**Review by Faless — APPROVED** [review]
LGTM! Great work :trophy: !

Thanks for bearing with the many back and forth :pray:

**Comment by AThousandShips** [comment]
Thank you! It's been a great journey figuring out exactly how to do it, complicated thing

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!
