### PR TITLE
[Editor] Add `.editorconfig` to the projects.

### LINKED ISSUE #27083: Can't load .cs files containing "special" characters (like ç è ì) in comments or strings (encoded in CP-1252).
**Godot version:**
3.1 Stable Mono (at least since 3.1 Beta 3)
Official builds, x64 versions.

**OS/device including version:**
Windows 7 Ultimate x64

**Issue description:**
Can't load .cs files containing "special" characters in comments or strings.
Example of such characters: ç è ì.

Unicode error: invalid utf8
 modules/mono/utils/string_utils.cpp:181 - Method/Function Failed, returning: ERR_INVALID_DATA
 Script 'res://Button03.cs' contains invalid unicode (utf-8), so it was not loaded. Please ensure that scripts are saved in valid utf-8 unicode.
 modules/mono/csharp_script.cpp:2898 - Condition ' err != OK ' is true. returned: RES()
 Failed loading resource: res://Button03.cs
 scene/resources/resource_format_text.cpp:175 - Couldn't load external resource: res://Button03.cs
 editor/editor_data.cpp:564 - Index p_idx=1 out of size (edited_scene.size()=1)

I'm using Visual Studio 2017 with default settings for encoding, those characters are valid UTF-8 (even ANSI).

**Steps to reproduce:**
Open any .cs script,
add any of those characters to a string or a comment,
try to build/run the game or load the scene containing said script.

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by bruvzg**
Adds `.editorconfig` to ensure external editors/IDEs use UTF-8 encoding.

Fixes https://github.com/godotengine/godot/issues/27083
Supersede https://github.com/godotengine/godot/pull/96837

### CODE REVIEW

**Review by aaronfranke — APPROVED** [review]
Note that this will add a `.editorconfig` into existing projects. In the event that this is desired only for new projects, this code could be moved to `editor/project_manager/project_dialog.cpp` inside `ProjectDialog::ok_pressed()`. However, I am not against retroactively adding this file personally, I'm all for it 👍

File: editor/editor_paths.cpp [hunk 1]
```diff
@@ -257,6 +257,22 @@ EditorPaths::EditorPaths() {
 			}
 		}
 
+		// Check that '.editorconfig' file exists
```
Comment (dalexeev) [inline editor/editor_paths.cpp:260]:
```suggestion
		// Check that `.editorconfig` file exists.
```

File: editor/editor_paths.cpp [hunk 2]
```diff
@@ -257,6 +257,22 @@ EditorPaths::EditorPaths() {
...
+		if (!FileAccess::exists(project_editorconfig_path)) {
+			Ref<FileAccess> f = FileAccess::open(project_editorconfig_path, FileAccess::WRITE);
+			if (f.is_valid()) {
+				f->store_line("root = true");
+				f->store_line("");
+				f->store_line("[*]");
+				f->store_line("charset = utf-8");
+				f->close();
+			} else {
+				ERR_PRINT("Failed to create file " + project_editorconfig_path);
```
Comment (dalexeev) [inline editor/editor_paths.cpp:271]:
```suggestion
				ERR_PRINT("Failed to create file " + project_editorconfig_path.quote() + ".");
```

File: editor/editor_paths.cpp [hunk 3]
```diff
@@ -245,18 +245,34 @@ EditorPaths::EditorPaths() {
 			}
 		}
 
-		// Check that the project data directory '.gdignore' file exists
+		// Check that the project data directory `.gdignore` file exists
```
Comment (dalexeev) [inline editor/editor_paths.cpp:248]:
```suggestion
		// Check that the project data directory `.gdignore` file exists.
```

File: editor/editor_paths.cpp [hunk 4]
```diff
@@ -245,18 +245,34 @@ EditorPaths::EditorPaths() {
...
 			Ref<FileAccess> f = FileAccess::open(project_data_gdignore_file_path, FileAccess::WRITE);
 			if (f.is_valid()) {
 				f->store_line("");
 			} else {
-				ERR_PRINT("Failed to create file " + project_data_gdignore_file_path);
+				ERR_PRINT("Failed to create file " + project_data_gdignore_file_path.quote() + ".");
 			}
 		}
 
+		// Check that `.editorconfig` file exists
```
Comment (dalexeev) [inline editor/editor_paths.cpp:260]:
```suggestion
		// Check that `.editorconfig` file exists.
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
This injects `.editorconfig` in `modules/gdscript/tests/scripts/` but it isn't ignored
