### PR TITLE
Fix calling `_call_shortcut_input` on a node that has been removed

### LINKED ISSUE #67837: Crash when pressing CTRL+TAB to cycle through scripts
### Godot version

v4.0.beta3.official (01ae26d31befb6679ecd92cd3c73aa5a76162e95)

### System information

Pop!_OS 22.04 LTS (64-bit), AMD® Radeon rx vega

### Issue description

When I press CTRL-TAB to toggle between files in the script panel in Godot 4, I sometimes crash.

Backtrace:

```
================================================================                                                         
handle_crash: Program crashed with signal 11                                                                             
Engine version: Godot Engine v4.0.beta3.official (01ae26d31befb6679ecd92cd3c73aa5a76162e95)                              
Dumping the backtrace. Please include this when reporting the bug to the project developer.                              
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f3f43c42520] (??:0)                                                    
[2] /home/d9n/Applications/Godot/Godot_v4.0-beta3_linux.x86_64() [0x29021ed] (??:0)                                      
[3] /home/d9n/Applications/Godot/Godot_v4.0-beta3_linux.x86_64() [0x290910e] (??:0)                                      
[4] /home/d9n/Applications/Godot/Godot_v4.0-beta3_linux.x86_64() [0x290bfcc] (??:0)                                      
[5] /home/d9n/Applications/Godot/Godot_v4.0-beta3_linux.x86_64() [0x296f1b7] (??:0)                                      
[6] /home/d9n/Applications/Godot/Godot_v4.0-beta3_linux.x86_64() [0xe136d4] (??:0)                                       
[7] /home/d9n/Applications/Godot/Godot_v4.0-beta3_linux.x86_64() [0x403544e] (??:0)                                      
[8] /home/d9n/Applications/Godot/Godot_v4.0-beta3_linux.x86_64() [0x40362c5] (??:0)                                      
[9] /home/d9n/Applications/Godot/Godot_v4.0-beta3_linux.x86_64() [0xe15678] (??:0)                                       
[10] /home/d9n/Applications/Godot/Godot_v4.0-beta3_linux.x86_64() [0xd9289b] (??:0)                                      
[11] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f3f43c29d90] (??:0)                                                   
[12] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f3f43c29e40] (??:0)                                     
[13] /home/d9n/Applications/Godot/Godot_v4.0-beta3_linux.x86_64() [0xdb3e3e] (??:0)                                      
-- END OF BACKTRACE --                                                                                                   
================================================================                              
```

### Steps to reproduce

* Download repro project and open it (using Godot 4 beta 3?)
* Enter the "World" scene from the scene tree
* Click on the "Ground" script (just a random node so we can have more than one script in the script editor)
* Check the scripts, that you have two. I have "application.gd" and "ground.gd" in there
* Press CTRL-TAB a few times. It should crash.

### Minimal reproduction project

[rogue-missile.zip](https://github.com/godotengine/godot/files/9853323/rogue-missile.zip)

### LINKED ISSUE #67886: Editor crash when duplicating Control nodes with keyboard and scene dock is on the right side
### Godot version

4.0 beta3

### System information

Linux Manjaro 6.0.3 (KDE Plasma 5.26.1 X11), AMD Ryzen 2500U, Radeon Vega 8

### Issue description

Trying to duplicate any Control node with the [`Ctrl`+`D`] keyboard shortcut or [`Ctrl` + `C`] followed by [`Ctrl` + `V`] makes the editor crash \*if the scene tree dock is on the right of the editor, sometimes outputting the following backtrace when launched from a terminal: 
```
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta3.official (01ae26d31befb6679ecd92cd3c73aa5a76162e95)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x38a00) [0x7ffbd0cc5a00] (??:0)
[2] ~/.local/bin/godot4.0-beta3() [0x2902071] (??:0)
[3] ~/.local/bin/godot4.0-beta3() [0x290910e] (??:0)
[4] ~/.local/bin/godot4.0-beta3() [0x290bfcc] (??:0)
[5] ~/.local/bin/godot4.0-beta3() [0x296f1b7] (??:0)
[6] ~/.local/bin/godot4.0-beta3() [0xe136d4] (??:0)
[7] ~/.local/bin/godot4.0-beta3() [0x403544e] (??:0)
[8] ~/.local/bin/godot4.0-beta3() [0x40362c5] (??:0)
[9] ~/.local/bin/godot4.0-beta3() [0xe15678] (??:0)
[10] ~/.local/bin/godot4.0-beta3() [0xd9289b] (??:0)
[11] /usr/lib/libc.so.6(+0x23290) [0x7ffbd0cb0290] (??:0)
[12] /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7ffbd0cb034a] (??:0)
[13] ~/.local/bin/godot4.0-beta3() [0xdb3e3e] (??:0)
-- END OF BACKTRACE --
```
Using the equivalent right click menu shortcuts behaves as expected.
Additionally, I've tested this with Godot 4.0 Beta 1 and 2 and this bug didn't exist in those two versions.
As noted by asterisks, new edit. This only happens when the scene tree dock is on the right of the editor for some reason.

### Steps to reproduce

Create or open a project, in a new scene, \*move the scene tree dock to the right of your editor, create the root node and give it a child Control node. Click on said Control node and then press [`Ctrl` + `D`] or [`Ctrl` + `C`] followed by [`Ctrl` + `V`].

### PR DESCRIPTION
**Pull request by Rindbee**
Nodes may have been deleted by shortcuts. For example, when switching scenes with `Ctrl` + `Tab` / `Ctrl` + `Shift` + `Tab`, some controls will be deleted and recreated.

Fix #67837, fix #67886.

### CODE REVIEW

File: scene/main/scene_tree.cpp [hunk 1]
```diff
@@ -941,8 +941,11 @@ void SceneTree::_call_input_pause(const StringName &p_group, CallInputType p_cal
 		}
 	}
 
-	for (Node *n : no_context_nodes) {
-		n->_call_shortcut_input(p_input);
+	for (ObjectID id : no_context_node_ids) {
```
Comment (bruvzg) [inline scene/main/scene_tree.cpp:944]:
```suggestion
	for (const ObjectID &id : no_context_node_ids) {
```

**Review by bruvzg — APPROVED** [review]

File: scene/main/scene_tree.cpp (hunk 1 above)
Comment (Rindbee) [reply scene/main/scene_tree.cpp]: Thanks for pointing it out.

**Comment by SleepyTonia** [comment]
This also fixes #67886

**Review by clayjohn — APPROVED** [review]

**Comment by clayjohn** [comment]
Looks good to me, thanks!
