### PR TITLE
Use `GetFileAttributesW` for checking file existence on Windows

### LINKED ISSUE #78645: Remote Scene Tree is unusably slow in large scenes
### Godot version

Godot 4.1.beta3

### System information

Windows 11/64, RTX 3070, Vulkan

### Issue description

My largest scene has 80,000 nodes in it and we have countless more to add. Foliage, rocks, and houses made up of individual components. Running the game, editing the SceneTree, and debugging line by line is fine, but viewing the remote scene tree is unusably slow. 

Click on something in the remote scene tree, even expanding/collapsing nodes with few children, clicking anything, or typing into the search filter, or stopping the program, and wait 5-10 seconds before you get a response. 

Even if the remote scene tree is not active, the editor menu is very sluggish, though not as bad. Maybe 1s per response.

I wrote an MRP that generates meshes in the scene tree. Browsing the large tree in the editor is no problem. Running the objects in game is no problem. Only the remote tree and editor menus when running the game has a problem.

I found that even starting around 3000 the remote tree starts to get sluggish and gets progressively worse from there. 90k is unusable. Interestingly at around 100k nodes in my running scene (108,935) I started getting this error message repeated on the console and the remote scene tree operated at normal speed, though with maybe 70k nodes in the remote tree instead of the total.

```
ERROR: Condition "err != OK || size > out_buf.size() - 4" is true. Continuing.
   at: _write_out (core/debugger/remote_debugger_peer.cpp:106)
```

It's slow even if the objects are invisible.

I've been struggling with this issue for a long time, all of GD4 builds, and maybe before. Still present in 4.1.beta3. I thought it was caused by #68232, but no. This MRP has only the automatic material and MeshInstance3D. It's not a custom shader issue, nor physics, gpuparticles, nor rendering.

### Steps to reproduce

* Run the MRP
* Click the `Objects` node.
* Set per_side to one of:
     * 30 for 28k objects (3s/click)
     * 45 for 91k objects (painful - this is my life)
     * 47 for 106k to overflow the buffer and it works at normal speed
* Generate. Wait 20-30 seconds.
* Expand/collapse nodes in the tree and observe it is normal speed
* Run the game
* Switch back to the editor, enable the remote tree and see its lag. With remote tree up, click on the menus and see how it kills everything. Good luck doing anything for 10+ seconds. You can click back to local for a usable editor.

### Minimal reproduction project

4.1b3 project file, but everything works in 4.0 if you set the message limit to 10240.

[test_slow_remote_tree.zip](https://github.com/godotengine/godot/files/11856682/test_slow_remote_tree.zip)

### PR DESCRIPTION
**Pull request by YYF233333**
~~Partially address #78645.~~ (solved by #101435)

Help to address #100109.

We are using `_wfsopen` in `FileAccessWindows::file_exists` which opens a file just to check it is there. Use `GetFileAttributesW` makes this function a lot faster. In MRP of #78645 reduce the lag by about a half (measured by eyes, not that accurate).

I used to complain that file operations on Windows were very slow. My apologies for wrongly blaming you, Windows :)

### CODE REVIEW

**Comment by YYF233333** [comment]
I see `GLOBAL_LOCK_FUNCTION` in `DirAccessWindows::file_exists` which uses `GetFileAttributesW`, so `GetFileAttributesW` is not as thread safe as `_wfsopen`? Shall I add it?

File: drivers/windows/file_access_windows.cpp [hunk 1]
```diff
@@ -402,13 +402,8 @@ bool FileAccessWindows::file_exists(const String &p_name) {
...
 	String filename = fix_path(p_name);
-	FILE *g = _wfsopen((LPCWSTR)(filename.utf16().get_data()), L"rb", _SH_DENYNO);
-	if (g == nullptr) {
-		return false;
-	} else {
-		fclose(g);
-		return true;
-	}
+	DWORD file_attr = GetFileAttributesW((LPCWSTR)(filename.utf16().get_data()));
+	return (file_attr != INVALID_FILE_ATTRIBUTES) && !(file_attr & FILE_ATTRIBUTE_DIRECTORY);
```
Comment (kiroxas) [inline drivers/windows/file_access_windows.cpp:406]: previous implementation asked for read and write access (`_SH_DENYNO`). Here you could have only read access. Given the function name, doesn't think that it is a problem, but if it is you will need to check `FILE_ATTRIBUTE_READONLY`

**Review by kiroxas — APPROVED** [review]
Reading metadata will be faster than opening the file, for sure.

File: drivers/windows/file_access_windows.cpp (hunk 1 above)
Comment (YYF233333) [reply drivers/windows/file_access_windows.cpp:406]: Isn't `_SH_DENYNO` just means it doesn't restrict read or write access from other processes? According to the commit history, it is used to tackle sharing open issues.

Comment (kiroxas) [reply drivers/windows/file_access_windows.cpp:406]: oh yes, it's for not locking for other processes. You should not have this problem with `GetFileAttributesW`. This should be good as is.

**Comment by YYF233333** [comment]
Tested and this do help address #100109.

master
```bash
1.gd load: 1.22ms
2.gd load: 1.46ms
3.gd load: 1.57ms
......
64.gd load: 14.75ms
65.gd load: 14.87ms
66.gd load: 15.11ms
67.gd load: 15.68ms
68.gd load: 16.14ms
69.gd load: 15.91ms
```
This PR
```bash
1.gd load: 1.12ms
2.gd load: 1.15ms
3.gd load: 1.34ms
......
65.gd load: 12.17ms
66.gd load: 12.27ms
67.gd load: 12.61ms
68.gd load: 12.77ms
69.gd load: 12.88ms
```

**Review by bruvzg — APPROVED** [review]
`DirAccessWindows` use the same function, so I do not see any reason to open the file here.

**Comment by akien-mga** [comment]
Thanks!
