### PR TITLE
GDScript: Fix subscript resolution on constant non-metatype GDScript base

### LINKED ISSUE #92534: Regression in "GDScript: fix segfault on invalid script" with `const foo : GDScript= preload(...)`
#92035  causes a regression in projects which access inner classes from `const foo: GDScript = preload("./foo.gd"):

System info:
Godot v4.3.beta (8bf8f41fc) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

MRP: [GDScriptPreloadBug.zip](https://github.com/godotengine/godot/files/15495154/GDScriptPreloadBug.zip)

Steps to reproduce:
1. Open the project. There are errors.
2. Change test.gd from `: GDScript =` to `:=` to infer type
3. Errors go away. Uncheck and check the plugin and it should print Hello World
4. Revert the change made in step 2.
5. There are still no errors?!?!?!

This issue does not reproduce when this PR is backed out. The MRP works fine in Godot 4.0.3 through May 17 bd2300d77.

_Originally posted by @lyuma in https://github.com/godotengine/godot/issues/92035#issuecomment-2138846348_

### PR DESCRIPTION
**Pull request by dalexeev**
* Fixes #92534.
* Resolves (partially) #89077.

#92035 exposed a bug with the static analyzer tries to get `GDScript` properties when they might be invalid (now there is [a guard](https://github.com/godotengine/godot/blob/e7dd6f11ed1ed4d72186d3a90d5f4ef42e79c4d0/modules/gdscript/gdscript.cpp#L934-L936) against it). This is due to the fact that when reducing subscript on a constant base, we use `Variant::get_named()`, while we should use the analyzer. In #79510, I fixed a related bug, but I didn't take into account that a constant value could have a broader type due to type hints and casting.

We also have a quirk that GDScript classes are both types and values. What causes collisions (#75392, #76414) is whether you mean a static class member or a non-static member of the `GDScript` resource (for instance, `resource_path`). Also, we don't have first class types and the `is_meta_type` flag sometimes leads to strange bugs.

Some users add unnecessary type hints to `const`-`preload`, which removes metatypes.

```gdscript
const MyClass: GDScript = preload("./my_class.gd")
var test := MyClass.InnerClass.new()
#                   ^^^^^^^^^^
# The specified type `GDScript` has no member `InnerClass`,
# but the value has and this is known in advance.
```

It might make sense to distinguish between a GDScript class as a type and as a value, but we proceed from the current state of affairs and strive to maintain backward compatibility. Now, for a constant `GDScript` base without the `is_meta_type` flag, the static members of the class are checked first, and then the non-static members of the `GDScript` class. For `GDScript` with the `is_meta_type` flag, only static class members are still checked.

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -4342,15 +4342,45 @@ void GDScriptAnalyzer::reduce_subscript(GDScriptParser::SubscriptNode *p_subscri
...
+					p_subscript->is_constant = true;
+					p_subscript->reduced_value = value;
+					result_type = type_from_variant(value, p_subscript);
+				}
 			}
+		}
+
+		if (valid) {
+			// Do nothing.
 		} else if (base_type.is_variant() || !base_type.is_hard_type()) {
```
Comment (Chaosus) [inline modules/gdscript/gdscript_analyzer.cpp:4384]:
```suggestion
		if (!valid && (base_type.is_variant() || !base_type.is_hard_type())) {
```

File: modules/gdscript/gdscript_analyzer.cpp [hunk 2]
```diff
@@ -4388,6 +4418,7 @@ void GDScriptAnalyzer::reduce_subscript(GDScriptParser::SubscriptNode *p_subscri
 				mark_node_unsafe(p_subscript);
 			}
 		}
+
```
Comment (Chaosus) [inline modules/gdscript/gdscript_analyzer.cpp:4421]: Previous if(!valid) may be unified with the next statement

Comment (dalexeev) [reply modules/gdscript/gdscript_analyzer.cpp:4421]: No, this would change the logic since `valid` is reassigned above.

Comment (Chaosus) [reply modules/gdscript/gdscript_analyzer.cpp:4421]: Ah, right...

File: modules/gdscript/gdscript_analyzer.cpp (hunk 1 above)
Comment (Chaosus) [inline modules/gdscript/gdscript_analyzer.cpp:4384]:
```suggestion
		if (!valid && (base_type.is_variant() || !base_type.is_hard_type())) {
```

Comment (dalexeev) [reply modules/gdscript/gdscript_analyzer.cpp:4384]: This would also change the logic, since then there is `else`. Duplicating `!valid` would preserve the logic:

```c++
if (!valid && (base_type.is_variant() || !base_type.is_hard_type())) {
    ...
} else if (!valid) {
    ...
}
```

But I think that the current version is clearer.

Comment (Chaosus) [reply modules/gdscript/gdscript_analyzer.cpp:4384]: Ah, right, sorry for worry

**Review by akien-mga — APPROVED** [review]
Makes sense to me. Thanks for the quick fix, and the detailed explanations!

**Comment by akien-mga** [comment]
Thanks!
