### PR TITLE
Sort decals and lights based on camera origin

### LINKED ISSUE #49639: Vulkan: Decal sorting changes unexpectedly depending on camera rotation
### Godot version

4.0.dev (6d98f84ab)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 465.31)

### Issue description

The new Decal node exhibits sorting issues when the camera moves or rotates. This can be seen both in the editor and in running projects:

https://user-images.githubusercontent.com/180032/122155594-9283da00-ce67-11eb-98b9-5697145dfd9b.mp4

I'm not sure *how* we should prevent this. We may not be able to rely on scene tree order because decals may be created with a lower-level API that does not use nodes. Maybe we could have a Render Priority property in the Decal node, so that users can force specific decals to render on top of others.

### Steps to reproduce

- Add 2 Decal nodes partially overlapping each other, with a different appearance (e.g. different **Modulate** property).
- Rotate the camera. Moving the camera alone does not seem to cause sorting issues, but rotating the camera will.

### Minimal reproduction project

[test_decal_sorting.zip](https://github.com/godotengine/godot/files/6660165/test_decal_sorting.zip)

### PR DESCRIPTION
**Pull request by clayjohn**
Also implement sort_offset for decals

Fixes: https://github.com/godotengine/godot/issues/49639
Supersedes: https://github.com/godotengine/godot/pull/60253
Follow up to: https://github.com/godotengine/godot/pull/69998

Primarily this PR is about ensuring that decals and lights do not change their calculated distance when the camera rotates. For both this is important if distance fade is enabled. For decals, this is important so decals do not flicker in and out when the camera rotates. 

To fix decals changing sort order when the camera moves I have extended the sort-offset to decals. 

In the sorting code for both I have removed redundancy and avoided calculating distance more than necessary. 

Finally, this PR also hides the sorting properties from most VisualInstance3D-derived types as only GeometryInstances and decals can use them. And Decals can only use sort-offset.

### CODE REVIEW

**Review by BastiaanOlij — APPROVED** [review]
Looks good to me

File: scene/3d/visual_instance_3d.cpp [hunk 1]
```diff
@@ -120,6 +120,12 @@ bool VisualInstance3D::is_sorting_use_aabb_center() const {
 	return sorting_use_aabb_center;
 }
 
+void VisualInstance3D::_validate_property(PropertyInfo &p_property) const {
+	if ((p_property.name == "sorting_offset" || p_property.name == "sorting_use_aabb_center")) {
```
Comment (akien-mga) [inline scene/3d/visual_instance_3d.cpp:124]: You have an extra pair of parentheses here and below.

This also seems to require a classref sync, the default value for `sorting_use_aabb_center` in VisualInstance3D is no longer picked up by doctool. (We could maybe fix that but it's not critical for this PR.)

**Comment by clayjohn** [comment]
Pushed the requested changes. Should be good now

**Comment by akien-mga** [comment]
Thanks!
