### PR TITLE
Fix going forward backward in editor selection history.

### LINKED ISSUE #90636: Going backward and forward in the inspector's edited history multi-select nodes in the scene tree when it should not
### Tested versions

- Reproducible from 4.1.dev3 up to current 4.3.dev master (578d937927ea9735aa7a8e0535f57801406b0b82)
- Not reproducible in 4.1.dev2 and before

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.5212) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

Since 4.1.dev3, when going backward and forward in the edited objects history, it adds to the selection (multi-select) all the inspected nodes, when multi-select should only happen when you are going back in history where you had actually selected multiples nodes (which does not work properly anyway as seen in the video) :

https://github.com/godotengine/godot/assets/75151379/54f47507-98e8-49c9-942f-b5d1e7979223

In 4.1.dev2 and before, it selected only the correct node as expected, but also fail to multi-select the correct nodes if the history point was more than 1 nodes selected, as seen in this video :

https://github.com/godotengine/godot/assets/75151379/b83e46ce-c6c4-4ff9-a0df-b3fd52a8b438

### Steps to reproduce

1. Create scene
2. Add child nodes
3. Use the edited nodes history backward and forward button or the list
4. Witness the behaviour

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by ajreckof**
Fixes #90636

### CODE REVIEW

File: editor/multi_node_edit.h [hunk 1]
```diff
@@ -36,7 +36,7 @@
 class MultiNodeEdit : public RefCounted {
 	GDCLASS(MultiNodeEdit, RefCounted);
 
-	List<NodePath> nodes;
+	Vector<NodePath> nodes;
```
Comment (akien-mga) [inline editor/multi_node_edit.h:39]: Use `LocalVector` for stuff that isn't meant to be passed around in functions.

File: editor/scene_tree_dock.h [hunk 2]
```diff
@@ -322,6 +322,7 @@ class SceneTreeDock : public VBoxContainer {
 	void set_edited_scene(Node *p_scene);
 	void instantiate(const String &p_file);
 	void instantiate_scenes(const Vector<String> &p_files, Node *p_parent = nullptr);
+	void set_selection(Vector<Node *> p_nodes);
```
Comment (akien-mga) [inline editor/scene_tree_dock.h:325]:
```suggestion
	void set_selection(const Vector<Node *> &p_nodes);
```

File: editor/multi_node_edit.h [hunk 3]
```diff
@@ -67,6 +67,19 @@ class MultiNodeEdit : public RefCounted {
 
 	void set_property_field(const StringName &p_property, const Variant &p_value, const String &p_field);
 
+	// If the nodes selected are the same independently of order then return true.
+	bool is_same_selection(const MultiNodeEdit *other) const {
```
Comment (akien-mga) [inline editor/multi_node_edit.h:71]:
```suggestion
	bool is_same_selection(const MultiNodeEdit *p_other) const {
```

File: editor/multi_node_edit.h (hunk 1 above)
Comment (akien-mga) [reply editor/multi_node_edit.h:39]: Nevermind, it's used for `SceneTreeDock::get_singleton()->set_selection()`.

Comment (ajreckof) [reply editor/multi_node_edit.h:39]: No you were right this can use LocalVector `SceneTreeDock::get_singleton()->set_selection()` use `Vector<Node>` because `EditorSelection` needs nodes and not nodepath so we need to retrieve nodes anyway ad it was already done there so I just defined the variable a bit earlier to keep it in scope longer. All in all this means this can be replaced with `LocalVector`

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
