### PR TITLE
GDScript: Properly respect `int` type hint for `@export_range`

### LINKED ISSUE #69104: @export_range allows setting float values for int variables in the inspector
### Godot version

4.0.beta6

### System information

macOS 13.0.1

### Issue description

Using `@export` on an int variable allows the variable to be modified in the inspector panel with an integer number field as expected. Entering a non-integer will round this to the closest integer and this value will be set. 

However, if you use `@export_range` to specify a value range to get a nice slider in the inspector, the slider sets a float value and the value does not round to the closest integer in the inspector panel. 

https://user-images.githubusercontent.com/17763524/203754208-36665438-58ea-409e-8d21-7aec0db84779.mov

This is confusing and unexpected since it could indicate to the user that the parameter edited is a float, when it's an int. And the float value shown will (I assume) not be the value the int variable is actually set to. So, in short the slider should be locked to integer steps in this case and the field should round any manual input to integers just like the non-slider int fields.

### Steps to reproduce

Add `@export_range(0,10) var my_integer:int = 0` to a node script and modify it in the inspector to see you can set float values for the integer.

### Minimal reproduction project

see above

EDIT:code formatting and a typo

### PR DESCRIPTION
**Pull request by jquinl**
For for issue :
@export_range allows setting float values for int variables in the inspector #69104

Where both int and float types are parsed as float when using @export_range.

This checks if the variable type is int (float default)  @export annotation

*Bugsquad edit:*
- Fixes #69104

### CODE REVIEW

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -3740,6 +3740,14 @@ bool GDScriptParser::export_annotations(const AnnotationNode *p_annotation, Node
 	// This is called after the analyzer is done finding the type, so this should be set here.
 	DataType export_type = variable->get_datatype();
 
+	if (p_annotation->name == SNAME("@export_range"))
+	{
+		if (export_type.builtin_type == Variant::INT)
+		{
+			variable->export_info.type = Variant::INT;
+		}
+	}
```
Comment (akien-mga) [inline modules/gdscript/gdscript_parser.cpp:3749]: To follow our style guidelines:

```suggestion
	if (p_annotation->name == SNAME("@export_range")) {
		if (export_type.builtin_type == Variant::INT) {
			variable->export_info.type = Variant::INT;
		}
	}
```

See https://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html

Comment (jquinl) [reply modules/gdscript/gdscript_parser.cpp:3749]: I'll keep it mind next time, Thanks!

**Comment by akien-mga** [comment]
This looks pretty good!

To do the style fixes I suggested, please use `git commit --amend` to keep it as a single commit (and update the PR with `git push --force`). See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request) for instructions.

It would also be good to amend the commit message to better follow our guidelines: https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind

Notably, we prefer putting the reference to the fixed issue in the body of the message, using closing keywords, like this:
```
GDScript: Properly respect `int` type hint for `@export_range`

Fixes #69104.
```

**Comment by jquinl** [comment]
Okay on it, thanks for the info

**Review by akien-mga — APPROVED** [review]
Looks good to me.

You didn't need to keep me as co-author in the commit though, GitHub added it in the fixup commit for my suggestion but a cosmetic change isn't really worth a mention :)

**Comment by jquinl** [comment]
Haha I'll keep it in mind. Thanks for the explanations!

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by jquinl** [comment]
Thank you for the help!

**Comment by lostminds** [comment]
Wow, that was quick! I reported this less than 24h ago, and now it's already merged. Good work @jquini and @akien-mga !
