### PR TITLE
SpriteFrames Editor: Fix FPS applied to two animations when switching animation

### LINKED ISSUE #79445: Unexpected behavior on SpriteFrames animation FPS config
### Godot version

v4.1.stable.official.970459615

### System information

Vulkan API 1.2.231 - Forward Mobile - Using Vulkan Device #0: Apple - Apple M1 Max

### Issue description

When changing a specific animation (eg. animation_a) FPS if you click on another animation name (eg. animation_b), the new FPS value is assigned to both animations.

### Steps to reproduce

- Create two animations
- Select one animation
- Click on FPS input and change to a new value
- Click on another animation name
- Now both animation with have the same FPS value.

https://github.com/godotengine/godot/assets/3025661/89c406ac-a98b-4285-a586-831e9e9a5e13

### Minimal reproduction project

Doesn't need a specific project, just create a new project and a new AnimatedSprite2D and assign new sprite frames and follow above steps.

### PR DESCRIPTION
**Pull request by dalexeev**
* Closes #79445.
* See also #79872.

Fix Animation FPS change applied to two animations when switching animation while editing spinbox FPS value.

* For context see #26979 and #28729.

Minor changes:

1. Use `*_no_signal()` methods in `_update_library()` for FPS and Loop controls.
2. Reorder some lines in the constructor.

### CODE REVIEW

File: editor/plugins/sprite_frames_editor_plugin.cpp [hunk 1]
```diff
@@ -955,7 +948,6 @@ void SpriteFramesEditor::_animation_name_edited() {
 
 	EditorUndoRedoManager *undo_redo = EditorUndoRedoManager::get_singleton();
 	undo_redo->create_action(TTR("Rename Animation"), UndoRedo::MERGE_DISABLE, EditorNode::get_singleton()->get_edited_scene());
-	_rename_node_animation(undo_redo, false, edited_anim, "", "");
```
Comment (dalexeev) [inline editor/plugins/sprite_frames_editor_plugin.cpp:958]: I'm not sure what this line is for, but after removing it, the error "Animation '' doesn't exist." disappeared and I didn't notice any regressions.

**Comment by adamscott** [comment]
Animation/assets-pipeline meeting: can you split up your PR, each PR fixing one bug (if possible?)? Thanks!

**Comment by dalexeev** [comment]
> can you split up your PR, each PR fixing one bug (if possible?)?

@adamscott Done!

* #79872

File: editor/plugins/sprite_frames_editor_plugin.cpp [hunk 2]
```diff
@@ -1240,9 +1233,9 @@ void SpriteFramesEditor::_update_library(bool p_skip_selector) {
 	if (animated_sprite) {
 		String autoplay_name = animated_sprite->call("get_autoplay");
 		if (autoplay_name.is_empty()) {
-			autoplay->set_pressed(false);
+			autoplay->set_pressed_no_signal(false);
 		} else {
-			autoplay->set_pressed(String(edited_anim) == autoplay_name);
+			autoplay->set_pressed_no_signal(String(edited_anim) == autoplay_name);
```
Comment (YuriSizov) [inline editor/plugins/sprite_frames_editor_plugin.cpp:1238]: Just leaving a note that this doesn't seem to result in any change in behavior, because the connected method `_autoplay_pressed` doesn't run if `updating` is `true`. So this should be fine.

Comment (YuriSizov) [reply editor/plugins/sprite_frames_editor_plugin.cpp:1238]: And the same applies to `anim_speed` and `anim_loop`.

File: editor/plugins/sprite_frames_editor_plugin.cpp [hunk 3]
```diff
@@ -1705,7 +1698,8 @@ SpriteFramesEditor::SpriteFramesEditor() {
 	sub_vb->add_child(animations);
 	animations->set_v_size_flags(SIZE_EXPAND_FILL);
 	animations->set_hide_root(true);
-	animations->connect("cell_selected", callable_mp(this, &SpriteFramesEditor::_animation_selected));
+	// HACK: The cell_selected signal is emitted before the FPS spinbox loses focus and applies the change.
+	animations->connect("cell_selected", callable_mp(this, &SpriteFramesEditor::_animation_selected), CONNECT_DEFERRED);
```
Comment (YuriSizov) [inline editor/plugins/sprite_frames_editor_plugin.cpp:1702]: Regarding the hack itself (and the same applies to https://github.com/godotengine/godot/pull/79872 really): we could probably avoid this if we store which item was selected when focus was gained, and on focus loss we update that item, and not the current item.

What do you think about that?

**Review by YuriSizov — APPROVED** [review]
I left a comment suggesting how to avoid relying on the order of operations, but I'm also approving this in case we are okay as is, because the fix works from my testing (and other changes seem good).

File: editor/plugins/sprite_frames_editor_plugin.cpp (hunk 3 above)
Comment (dalexeev) [reply editor/plugins/sprite_frames_editor_plugin.cpp:1702]: This will work, but I think it's about the same hack as this one, but also requires adding an unnecessary variable with duplicate content, a callback, and a connection to the `LineEdit` signal. I would prefer to keep it as is until #79695 is fixed or if we find any problems with this solution.

**Comment by akien-mga** [comment]
Thanks!
