### PR TITLE
C#: Fix NodePaths completion error for not calling from main thread

### LINKED ISSUE #78913: Exception when sending code completion message for NodePath via GodotTools.IdeMessaging (C#)
### Godot version

4.1.rc2

### System information

Window 11/MacOS

### Issue description

We integrated `GodotTools.IdeMessaging` into the Rider Godot-Support plugin to get auto completion for `NodePath` and input actions to get more feature parity with VS Code and the Godot Editor itself (https://github.com/JetBrains/godot-support/pull/102). We tested against 4.0.3 and everything works fine. But with 4.1.rc2 we get an exception thrown in the Godot Editor:

```
Caller thread can't call this function in this node (/root/@EditorNode@17664/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@VSplitContainer@754/@VBoxContainer@755/@PanelContainer@800/MainScreen/@CanvasItemEditor@10090/@VSplitContainer@9915/@HSplitContainer@9917/@HSplitContainer@9919/@Control@9920/@SubViewportContainer@9921/@SubViewport@9922/player). Use call_deferred() or call_thread_group() instead.
```

I'm not really sure what's happening here but it seems to be a problem in the editor? 

### Steps to reproduce

- use Godot 4.1.rc2
- create new C# project
- build and run godot-support plugin
  - (in rider directory) `gradlew runIde`
- open Godot project in Rider
- try to get Code Completion for `GetNode("")`

### Minimal reproduction project

An Empty project with a single, empty C# script is enough.

### PR DESCRIPTION
**Pull request by neikeq**
The node API we use for code completion changed and no longer allows being called from threads other than the main one.

Fixes #78913

I don't know if awaiting the next frame takes longer with low processor mode. It may be better to implement an awaitable version of `CallDeferred`.

### CODE REVIEW

File: modules/mono/editor/GodotTools/GodotTools/Ides/MessagingServer.cs [hunk 1]
```diff
@@ -385,9 +385,12 @@ private static async Task<Response> HandleCodeCompletionRequest(CodeCompletionRe
                 // However, it doesn't fix resource loading if the rest of the path is also case insensitive.
                 string scriptFileLocalized = FsPathUtils.LocalizePathWithCaseChecked(request.ScriptFile);
 
+                // The node API can only be called from the main thread.
+                await Godot.Engine.GetMainLoop().ToSignal(Godot.Engine.GetMainLoop(), "process_frame");
```
Comment (raulsntos) [inline modules/mono/editor/GodotTools/GodotTools/Ides/MessagingServer.cs:389]: A bit hacky but we could wrap this line in an if so it only awaits when autocompleting NodePaths.

Also nit-pick, we should probably avoid calling `GetMainLoop` twice. And the signal name can use the exposed `StringName`.

```suggestion
                if (request.Kind == CodeCompletionRequest.CompletionKind.NodePaths)
                {
                    var mainLoop = Godot.Engine.GetMainLoop();
                    await mainLoop.ToSignal(mainLoop, Godot.SceneTree.SignalName.ProcessFrame);
                }
```

By the way, since the signal is in `SceneTree` and not `MainLoop`, this would block forever if the main loop is not a `SceneTree`. Although I don't think the main loop would ever change in the Godot editor.

Comment (neikeq) [reply modules/mono/editor/GodotTools/GodotTools/Ides/MessagingServer.cs:389]: We don't want the method to block waiting for the completion. That's probably why it was using `Task.Run` before. So, I just decided to always await the signal, even if not needed.

Comment (raulsntos) [reply modules/mono/editor/GodotTools/GodotTools/Ides/MessagingServer.cs:389]: Oh yeah, then maybe we could `await Task.CompletedTask` in the else block.

**Review by raulsntos — APPROVED** [review]
Should be good to merge. The current PR implementation should fix the issue and my previous comments can be addressed later.

**Comment by akien-mga** [comment]
Thanks!
