### PR TITLE
fix GLES2 line rendering

### LINKED ISSUE #17147: GLES2 doesn't render Line2D with tiled textures correctly
**Godot version:**
 234dfde

**Issue description:**
**GLES3:**
gles3

**GLES2:**
gles2

These errors also appear:
```
0:00:00:0829 - Method/Function Failed, returning: image
----------
Type:Error
Description: 
Time: 0:00:00:0829
C Error: Method/Function Failed, returning: image
C Source: drivers/gles2/rasterizer_storage_gles2.cpp:143
C Function: _get_gl_image_and_format
```
```
0:00:00:0829 - GL ERROR: Source: OpenGL	Type: Error	ID: 14	Severity: High	Message: GL_INVALID_ENUM in glTexImage2D(incompatible format = GL_NONE, type = 0x2a474370)
----------
Type:Error
Description: 
Time: 0:00:00:0829
C Error: GL ERROR: Source: OpenGL	Type: Error	ID: 14	Severity: High	Message: GL_INVALID_ENUM in glTexImage2D(incompatible format = GL_NONE, type = 0x2a474370)
C Source: drivers/gles2/rasterizer_gles2.cpp:111
C Function: _gl_debug_print
```

### PR DESCRIPTION
**Pull request by karroffel**
fixes #17147

### CODE REVIEW

File: drivers/gles2/rasterizer_canvas_gles2.cpp [hunk 1]
```diff
@@ -392,6 +392,7 @@ void RasterizerCanvasGLES2::_canvas_item_render_commands(Item *p_item, Item *cur
 					glDrawArrays(GL_TRIANGLE_FAN, 0, 4);
 				} else {
 
+
```
Comment (akien-mga) [inline drivers/gles2/rasterizer_canvas_gles2.cpp]: `EBADSTYLE` ;)

Comment (karroffel) [reply drivers/gles2/rasterizer_canvas_gles2.cpp]: updated
