### PR TITLE
Resolve GLES 2 crash on older iOS devices

### LINKED ISSUE #26450: GLES2 crash with errors 502/506 on iOS [iPhone 5s, 6 and iPad Pro]
**Godot version:**
3.1 (tested beta 7 through beta 9)

**OS/device including version:**
iPhone 5s - iOS 11.4

**Issue description:**
Simple 2D projects crash instantly right after the launch image is shown. Screen turns dark grey. Does not occur when exporting as a GLES3 project.

XCode output:

```
2019-03-01 18:15:27.556089+0100 GLES2_TEST[295:13172] [DYMTLInitPlatform] platform initialization successful
*********** main.m
running app main
after init super 0x102bd0450
******** screen size 640, 1136
after init gles 0x102bd0450
******** adding observer for sound routing changes
******** adding observer for keyboard show/hide
glview is 0x102bd0450
Path: /var/containers/Bundle/Application/7DF1E009-FFCA-4227-B882-763032EF57A2/GLES2_TEST.app
godot_iphone /var/containers/Bundle/Application/7DF1E009-FFCA-4227-B882-763032EF57A2/GLES2_TEST.app/GLES2_TEST
cwd /private/var/containers/Bundle/Application/7DF1E009-FFCA-4227-B882-763032EF57A2/GLES2_TEST.app
os created
setting data dir to /var/mobile/Containers/Data/Application/CF445435-3FD3-4F46-89FC-A286B2707960/Documents from /var/mobile/Containers/Data/Application/CF445435-3FD3-4F46-89FC-A286B2707960/Documents
setup 0
cadisaplylink: 1start animation!
******** screen size 640, 1136
2019-03-01 18:15:28.211989+0100 GLES2_TEST[295:12957] [App] UIWindow->__registeredPreCommitHandler was abandoned !!!! this would have caused a cascade of blown fences - proactively clearing but a bug exists here somewhere between UIKit and CoreAnimation
2019-03-01 18:15:28.212285+0100 GLES2_TEST[295:12957] +[CATransaction synchronize] called within transaction
2019-03-01 18:15:28.218528+0100 GLES2_TEST[295:12957] +[CATransaction synchronize] called within transaction
2019-03-01 18:15:28.263400+0100 GLES2_TEST[295:12957] +[CATransaction synchronize] called within transaction
2019-03-01 18:15:28.322041+0100 GLES2_TEST[295:12957] OpenGL ES 2.0 Renderer: Apple A7 GPU
OpenGL ES 2.0 Renderer: Apple A7 GPU
2019-03-01 18:15:28.370377+0100 GLES2_TEST[295:12957] **ERROR**: Directional shadow framebuffer status invalid
2019-03-01 18:15:28.370805+0100 GLES2_TEST[295:12957]    At: drivers/gles2/rasterizer_scene_gles2.cpp:3330:initialize() - Directional shadow framebuffer status invalid
**ERROR**: Directional shadow framebuffer status invalid
   At: drivers/gles2/rasterizer_scene_gles2.cpp:3330:initialize() - Directional shadow framebuffer status invalid
2019-03-01 18:15:28.539121+0100 GLES2_TEST[295:12957] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2019-03-01 18:15:28.539908+0100 GLES2_TEST[295:12957] [MC] Reading from public effective user settings.
2019-03-01 18:15:29.165566+0100 GLES2_TEST[295:12957] 502 error
2019-03-01 18:15:29.203475+0100 GLES2_TEST[295:12957] **WARNING**: Could not create framebuffer!!
2019-03-01 18:15:29.203574+0100 GLES2_TEST[295:12957]    At: drivers/gles2/rasterizer_storage_gles2.cpp:4333:_render_target_allocate() - Could not create framebuffer!!
**WARNING**: Could not create framebuffer!!
   At: drivers/gles2/rasterizer_storage_gles2.cpp:4333:_render_target_allocate() - Could not create framebuffer!!
2019-03-01 18:15:29.231660+0100 GLES2_TEST[295:12957] 502 error
```

```
AGXGLDriver`___lldb_unnamed_symbol544$$AGXGLDriver:
    0x1a5906ac8 <+0>:  orr    w8, wzr, #0x1
    0x1a5906acc <+4>:  mov    w9, #0xbeef
    0x1a5906ad0 <+8>:  movk   w9, #0xdead, lsl #16
->  0x1a5906ad4 <+12>: str    w9, [x8]
    0x1a5906ad8 <+16>: ret    
```
The second one is marked 'Thread 1: EXC_BAD_ACCESS (code=1, address=0x1)' where the arrow is (see screenshot).

**Steps to reproduce:**
Make a new GLES2 project -> add Node2D -> export for iOS -> run on device

**Minimal reproduction project:**
[GLES2_TEST.zip](https://github.com/godotengine/godot/files/2920454/GLES2_TEST.zip)
(Included basic Images.xcassets with valid images to replace the xcassets Godot generates)

XCode screenshot:
screen shot 2019-03-01 at 18 25 13

### PR DESCRIPTION
**Pull request by samgreen**
This resolves #26450.

Since both types `EAGLContext` exists and are valid to create on some devices, the export template would always create a GL ES 3 context, which was causing FBO crashes when the rest of the pipeline was configured as OpenGL ES 2.

### CODE REVIEW

File: platform/iphone/app_delegate.mm [hunk 1]
```diff
@@ -641,6 +629,12 @@ - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(
 		return FALSE;
 	};
 
+	// WARNING: We must *always* create the GLView after we have constructed the
+	// OS with iphone_main. This allows the GLView to access project settings so
+	// it can properly initialize the OpenGL context
+	GLView *glView = [[GLView alloc] initWithFrame:rect];
```
Comment (samgreen) [inline platform/iphone/app_delegate.mm]: This ordering is critical now since we’re using `GLOBAL_GET` in `initGLES`

File: platform/iphone/gl_view.mm [hunk 2]
```diff
@@ -284,17 +284,27 @@ - (id)initGLES {
...
-
-	// Create our EAGLContext, and if successful make it current and create our framebuffer.
-	context = [[EAGLContext alloc] initWithAPI:kEAGLRenderingAPIOpenGLES3];
-
-	if (!context || ![EAGLContext setCurrentContext:context] || ![self createFramebuffer]) {
+	
+	// Create a context based on the gl driver from project settings
+	if (GLOBAL_GET("rendering/quality/driver/driver_name") == "GLES3") {
+		context = [[EAGLContext alloc] initWithAPI:kEAGLRenderingAPIOpenGLES3];
+		NSLog(@"Setting up an OpenGL ES 3 context. Based on Project Settings \"rendering/quality/driver/driver_name\"");
```
Comment (samgreen) [inline platform/iphone/gl_view.mm]: Might need to add something here to handle the fallback Project Setting

Comment (samgreen) [reply platform/iphone/gl_view.mm]: Looks like we’re clear here. I double checked the initialization and it handles fallback as part of driver init.

**Comment by samgreen** [comment]
Tested the fallback code and it seems to be working appropriately. Relevant console log:

```
2019-03-14 18:49:13.564022-0700 GLES2Export[732:97998] Setting up an OpenGL ES 3 context. Based on Project Settings "rendering/quality/driver/driver_name"
2019-03-14 18:49:18.993945-0700 GLES2Export[732:97998] Failed to created OpenGL ES 3 context
2019-03-14 18:49:26.106476-0700 GLES2Export[732:97998] Setting up an OpenGL ES 2 context. 
2019-03-14 18:50:04.980086-0700 GLES2Export[732:97998] OpenGL ES 2.0 Renderer: Apple A8 GPU
OpenGL ES 2.0 Renderer: Apple A8 GPU
```

With a GL ES 3 device:

```
2019-03-14 18:53:18.560944-0700 GLES2Export[739:98736] Setting up an OpenGL ES 3 context. Based on Project Settings "rendering/quality/driver/driver_name"
2019-03-14 18:53:18.629171-0700 GLES2Export[739:98736] OpenGL ES 3.0 Renderer: Apple A8 GPU
OpenGL ES 3.0 Renderer: Apple A8 GPU
```

With a GL ES 2 forced:

```
2019-03-14 18:54:51.293350-0700 GLES2Export[746:99196] Setting up an OpenGL ES 2 context.
2019-03-14 18:54:51.341819-0700 GLES2Export[746:99196] OpenGL ES 2.0 Renderer: Apple A8 GPU
OpenGL ES 2.0 Renderer: Apple A8 GPU
```

File: platform/iphone/gl_view.mm [hunk 3]
```diff
@@ -284,19 +284,37 @@ - (id)initGLES {
...
 			return nil;
 		}
 	}
 
+	if (![EAGLContext setCurrentContext:context]) {
+		NSLog(@"Failed to set EAGLContext!");
+		return nil;
+	}
+	if (![self createFramebuffer]) {
+		NSLog(@"Failed to create frame buffer!");
```
Comment (samgreen) [inline platform/iphone/gl_view.mm]: Hopefully the verbosity of these `NSLog` statements should save us from headaches in the future.

File: platform/iphone/gl_view.mm [hunk 4]
```diff
@@ -284,20 +284,28 @@ - (id)initGLES {
...
 		context = [[EAGLContext alloc] initWithAPI:kEAGLRenderingAPIOpenGLES3];
 		NSLog(@"Setting up an OpenGL ES 3 context. Based on Project Settings \"rendering/quality/driver/driver_name\"");
-	} else if (GLOBAL_GET("rendering/quality/driver/driver_name") == "GLES2") {
-		context = [[EAGLContext alloc] initWithAPI:kEAGLRenderingAPIOpenGLES2];
-		gles3_available = false;
-		NSLog(@"Setting up an OpenGL ES 2 context. Based on Project Settings \"rendering/quality/driver/driver_name\"");
+		if (!context && GLOBAL_GET("rendering/quality/driver/fallback_to_gles2")) {
+			gles3_available = false;
+			fallback_gl2 = true;
+			NSLog(@"Failed to created OpenGL ES 3 context. Falling back to OpenGL ES 2.");
```
Comment (akien-mga) [inline platform/iphone/gl_view.mm]: Typo here, "created".

Comment (akien-mga) [reply platform/iphone/gl_view.mm]: Since you have to amend, might be worth using "2.0" and "3.0" in those logs to be explicit, not just "2" and "3" (as we're not using OpenGL ES 3.1 or 3.2).

**Comment by akien-mga** [comment]
Looks great, thank you! Just needs a typo fix and I'll merge (please amend the commit).

**Review by akien-mga — APPROVED** [review]

**Comment by samgreen** [comment]
Will get this amended today. Thanks!

**Comment by samgreen** [comment]
Rebased and fixed the typos in an amended commit.

File: platform/iphone/gl_view.mm [hunk 5]
```diff
@@ -284,19 +284,37 @@ - (id)initGLES {
...
 			nil];
+	bool fallback_gl2 = false;
+	// Create a GL ES 3 context based on the gl driver from project settings
+	if (GLOBAL_GET("rendering/quality/driver/driver_name") == "GLES3") {
+		context = [[EAGLContext alloc] initWithAPI:kEAGLRenderingAPIOpenGLES3];
+		NSLog(@"Setting up an OpenGL ES 3 context. Based on Project Settings \"rendering/quality/driver/driver_name\"");
+		if (!context && GLOBAL_GET("rendering/quality/driver/fallback_to_gles2")) {
+			gles3_available = false;
+			fallback_gl2 = true;
+			NSLog(@"Failed to create OpenGL ES 3.X context. Falling back to OpenGL ES 2.");
```
Comment (akien-mga) [inline platform/iphone/gl_view.mm]: I meant *explicitly* to use "2.0" and "3.0". We do not use OpenGL ES 3.1+.

File: platform/iphone/gl_view.mm [hunk 6]
```diff
@@ -284,19 +284,37 @@ - (id)initGLES {
...
-	if (!context || ![EAGLContext setCurrentContext:context] || ![self createFramebuffer]) {
+	// Create GL ES 2 context
+	if (GLOBAL_GET("rendering/quality/driver/driver_name") == "GLES2" || fallback_gl2) {
 		context = [[EAGLContext alloc] initWithAPI:kEAGLRenderingAPIOpenGLES2];
-		gles3_available = false;
-		if (!context || ![EAGLContext setCurrentContext:context] || ![self createFramebuffer]) {
-			[self release];
+		NSLog(@"Setting up an OpenGL ES 2 context.");
+		if (!context) {
+			NSLog(@"Failed to create OpenGL ES 2.X context!");
```
Comment (akien-mga) [inline platform/iphone/gl_view.mm]: 2.0

File: platform/iphone/gl_view.mm [hunk 7]
```diff
@@ -284,19 +284,37 @@ - (id)initGLES {
...
-	context = [[EAGLContext alloc] initWithAPI:kEAGLRenderingAPIOpenGLES3];
-
-	if (!context || ![EAGLContext setCurrentContext:context] || ![self createFramebuffer]) {
+	// Create GL ES 2 context
+	if (GLOBAL_GET("rendering/quality/driver/driver_name") == "GLES2" || fallback_gl2) {
 		context = [[EAGLContext alloc] initWithAPI:kEAGLRenderingAPIOpenGLES2];
-		gles3_available = false;
-		if (!context || ![EAGLContext setCurrentContext:context] || ![self createFramebuffer]) {
-			[self release];
+		NSLog(@"Setting up an OpenGL ES 2 context.");
```
Comment (akien-mga) [inline platform/iphone/gl_view.mm]: 2.0

File: platform/iphone/gl_view.mm [hunk 8]
```diff
@@ -284,19 +284,37 @@ - (id)initGLES {
 			kEAGLColorFormatRGBA8,
 			kEAGLDrawablePropertyColorFormat,
 			nil];
+	bool fallback_gl2 = false;
+	// Create a GL ES 3 context based on the gl driver from project settings
+	if (GLOBAL_GET("rendering/quality/driver/driver_name") == "GLES3") {
+		context = [[EAGLContext alloc] initWithAPI:kEAGLRenderingAPIOpenGLES3];
+		NSLog(@"Setting up an OpenGL ES 3 context. Based on Project Settings \"rendering/quality/driver/driver_name\"");
```
Comment (akien-mga) [inline platform/iphone/gl_view.mm]: 3.0

File: platform/iphone/gl_view.mm (hunk 5 above)
Comment (samgreen) [reply platform/iphone/gl_view.mm]: Ah, I totally misread this. Have made the changes.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.1.
