### PR TITLE
Change snap settings to not use LineEdits

### LINKED ISSUE #106388: Snap Settings fields behave inconsistently
### Tested versions

v4.4.1.stable.official [49a5bc7b6]
v4.5.dev4.official [209a446e3]

### System information

Godot v4.5.dev4 - macOS Sequoia (15.3.2) - Multi-window, 2 monitors - Metal (Forward+) - integrated Apple M2 (Apple8) - Apple M2 (8 threads)

### Issue description

The fields in Snap Settings don't interpret the values the same way inspector properties do. I think it would be nice to unify this.

Also the snap settings accept any arbitrary text with no feedback. This is most noticeable when I mistakenly type a **comma instead of a dot as a decimal separator**. Inspector fields handle this gracefully (I love it).

Image

I would expect the fields to interpret the expression, like the inspector fields would. Or at least zero out the fields instead of keeping the invalid values ("a" for rotation snap) there.

[Link to the Snap Settings in source code](https://github.com/godotengine/godot/blob/09fcbb86459498985a910cdd1684844a1968dc96/editor/plugins/node_3d_editor_plugin.h#L778), they are all plain LineEdits.

### Steps to reproduce

Open the Snap Settings dialog in _3D > Transform (top bar) > Configure Snap..._ and try inputting an invalid value into the fields (all three fields act the same)

Some examples:

- `0,1` --> `0`, because comma is not interpreted as a decimal separator and zero is the first number.
- `5+5` --> `5`, similar to above - the expression isn't evaluated
- `a` --> `0`, I'm guessing the fallback for invalid number parse is zero. This is correct, but I'd expect the field to reflect that.
- `-1` --> `1`, this one behaves correctly. I'd expect it to turn into a `1` in the dialog though.

Also the invalid values (like the letter `a`) stay in the dialog fields when it's closed and opened again. I'd expect the fields it to reflect the _interpreted_ values - if not now, then surely after closing and opening.

### Minimal reproduction project (MRP)

No setup needed, this is an editor bug

### PR DESCRIPTION
**Pull request by VojtaStruhar**
- Fixes #106388 

I've set the snap settings on 2 decimal places for transform (0.25 is my favorite), 1 decimal place for rotation (10th of a single degree should be plenty of precision) and zero decimal places for scale (since that is a percentage). If you have other ideas what the defaults should be, please tell me.

### CODE REVIEW

**Comment by VojtaStruhar** [comment]
I tried SpinBox before, but I think the EditorSpinSlider works even better. My beloved `0,25` -> `0.25` works :) 

CleanShot-000126-godot macos editor dev arm64

**Review by Calinou — COMMENTED** [review]
Tested locally, it works as expected. Code looks good to me.

Before | After
-|-
image | image

Some feedback:

- You can use EditorSpinSlider's `set_suffix()` method, so that the `°` (degree) and `%` signs can be directly part of the slider. In C++, use `U"°"` to enter the degree sign in a string.
  - Once this is done, you can remove `(deg.)` and `(%)` from the rotation/scale snap heading strings.
- There are no buttons to revert to the default value (like in the inspector), but this wasn't present before either.
- The translate snap step should be reduced to `0.001`, so that you can enter values like `0.125` units.

File: editor/scene/3d/node_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -9483,20 +9480,27 @@ Node3DEditor::Node3DEditor() {
...
-	snap_rotate->set_accessibility_name(TTRC("Rotate Snap (deg.):"));
-	snap_dialog_vbc->add_margin_child(TTRC("Rotate Snap (deg.):"), snap_rotate);
-
-	snap_scale = memnew(LineEdit);
-	snap_scale->set_select_all_on_focus(true);
-	snap_scale->set_accessibility_name(TTRC("Scale Snap (%):"));
-	snap_dialog_vbc->add_margin_child(TTRC("Scale Snap (%):"), snap_scale);
+	snap_translate = memnew(EditorSpinSlider);
+	snap_translate->set_min(0.0);
+	snap_translate->set_step(0.01);
```
Comment (Calinou) [inline editor/scene/3d/node_3d_editor_plugin.cpp]:
```suggestion
	snap_translate->set_step(0.001);
```

**Comment by VojtaStruhar** [comment]
@Calinou Thanks for the feedback! 

- The suffixes are a great addition 
- Transform now snaps to `0.001`
- I didn't bother with the revert buttons, I don't think they are too important here. I find myself setting the snapping once per project and then never again. I hope that's not an issue.

CleanShot-000206-godot macos editor dev arm64

File: editor/scene/3d/node_3d_editor_plugin.cpp [hunk 2]
```diff
@@ -9483,20 +9480,29 @@ Node3DEditor::Node3DEditor() {
...
-	snap_dialog_vbc->add_margin_child(TTRC("Rotate Snap (deg.):"), snap_rotate);
-
-	snap_scale = memnew(LineEdit);
-	snap_scale->set_select_all_on_focus(true);
-	snap_scale->set_accessibility_name(TTRC("Scale Snap (%):"));
-	snap_dialog_vbc->add_margin_child(TTRC("Scale Snap (%):"), snap_scale);
+	snap_translate = memnew(EditorSpinSlider);
+	snap_translate->set_min(0.0);
+	snap_translate->set_step(0.001);
+	snap_translate->set_max(10.0);
```
Comment (Calinou) [inline editor/scene/3d/node_3d_editor_plugin.cpp:9776]: Add "meter" suffix like we have for `Node3D.position`:

```suggestion
	snap_translate->set_max(10.0);
	snap_translate->set_suffix("m");
```

Comment (VojtaStruhar) [reply editor/scene/3d/node_3d_editor_plugin.cpp:9776]: Makes sense!

**Comment by VojtaStruhar** [comment]
@Calinou Sorry for the tag - is there a better way to request a review?

I added the `m` suffix, I think we could merge now!

**Comment by VojtaStruhar** [comment]
Oh, I found the button, I'm so sorry

**Review by Calinou — APPROVED** [review]

**Comment by Repiteo** [comment]
Could you squash your commits? See our [pull request guidelines](https://contributing.godotengine.org/en/latest/organization/pull_requests/creating_pull_requests.html#the-interactive-rebase) for more information

**Comment by VojtaStruhar** [comment]
Sure! This evening I'll get to it :) Sorry, it's been a while since I read the guidelines

**Comment by VojtaStruhar** [comment]
@Repiteo Squashed! 🫡

**Comment by Repiteo** [comment]
Thanks!

**Comment by VojtaStruhar** [comment]
The pleasure is mine!
