### PR TITLE
Clear missed remaps on deinitialization

### LINKED ISSUE #34221: [iOS] Crash on exit
**Godot version:** 3.2 [fa4f525216]

**OS/device including version:** iPhone

**Issue description:**
Some times crashed on exit with error **malloc_error_brake**
**"core/string_name.cpp:107:unref()"**

**Steps to reproduce:**
Just close the app with swipe up

**Minimal reproduction project:**
I have a patch that fixing it. But need a review. Maybe problem somewhere dipper.

This is a screenshot from XCode
https://mega.nz/#!kwoFFKYJ!VISZj_TKrAWIb3U2_AD5YCP8Bg6j41U_NvmoxgmKJiU

Patch:
https://mega.nz/#!Is502QpL!xy-vbYR5mjd8-YkuWGZSvzZ9KJD7vhZ10e2odmggUJU

### PR DESCRIPTION
**Pull request by jkb0o**
This will fix #34221, can be cherry-picked in 3.2

### CODE REVIEW

File: core/self_list.h [hunk 1]
```diff
@@ -103,7 +103,7 @@ class SelfList {
 		_FORCE_INLINE_ const SelfList<T> *first() const { return _first; }
 
 		_FORCE_INLINE_ List() {}
-		_FORCE_INLINE_ ~List() { ERR_FAIL_COND(_first != nullptr); }
+		_FORCE_INLINE_ ~List() {}
```
Comment (qarmin) [inline core/self_list.h:106]: This just fixing crash, but still there is somewhere a memory leak which needs to be fixed.
I don't think that is good idea to remove memory leak check in every single element which use list because this leak happens only on iOS

Comment (akien-mga) [reply core/self_list.h:106]: Yeah, I think a better workaround would be to use `printf` or similar instead of `ERR_FAIL_COND` to notify of the leak without relying on `OS::print_error` (which crashes probably because `OS` has already been de-initialized at this point).

Comment (jkb0o) [reply core/self_list.h:106]: Ok, I'll do it with OS.

Comment (akien-mga) [reply core/self_list.h:106]: What I meant is that it should be done **without** `OS`.

Comment (jkb0o) [reply core/self_list.h:106]: Isn't it ok to protect OK with `if (!_logger) return;`? I'll look into the deinitialization order then.

Comment (jkb0o) [reply core/self_list.h:106]: @akien-mga I finally got what you say about `printf`, sorry, its difficult morning.

Comment (akien-mga) [reply core/self_list.h:106]: Yeah that's an option, `OS::print_error` could be changed to:
```
if (unlikely(!_logger)) {
	printf(...);
} else {
	_logger->log_error(p_function, p_file, p_line, p_code, p_rationale, p_type);
}
```

Not sure if the added check would have a significant performance impact.

Comment (jkb0o) [reply core/self_list.h]: I found a source of the problem, done without touching SelfList or OS.

File: core/io/resource_loader.cpp [hunk 2]
```diff
@@ -999,6 +999,9 @@ void ResourceLoader::load_translation_remaps() {
 
 void ResourceLoader::clear_translation_remaps() {
 	translation_remaps.clear();
+	while (unlikely(remapped_list.first())) {
+		remapped_list.remove(remapped_list.first());
+	}
```
Comment (akien-mga) [inline core/io/resource_loader.cpp:1004]: I'm not sure this is the correct fix. Is it really `unlikely()` that there would be leftover remaps? Why does it happen then?
I don't see any code that actually removes items from `remapped_list` apart from
```
core/resource.cpp
327:            ResourceLoader::remapped_list.remove(&remapped_list);
```

Comment (jkb0o) [reply core/io/resource_loader.cpp:1004]: I'm not sure about `unlikely`, comparing with `NULL`/`nullptr` is probably the better way. 

But `remapped_list` get never cleared, so if I have any translation remaps in the project, I end with SelfList leak (this happens in OSX as well as iOS for me). 

Also, removing from `remapped_list` could be done in `Resource::~Resource` for preventing other runtime leaks, but I need more time diving deep into `Resource`.

Comment (jkb0o) [reply core/io/resource_loader.cpp:1004]: btw, current code completely clears `remapped_list`

Comment (akien-mga) [reply core/io/resource_loader.cpp:1004]: @reduz suggests that just adding `remapped_list.clear();` instead of this while loop might be the proper fix.

Comment (jkb0o) [reply core/io/resource_loader.cpp:1004]: I'd like to, but `SelfList` has no `clear` method. I can implement it, is this the way?

Comment (akien-mga) [reply core/io/resource_loader.cpp:1004]: I guess it's fine as is then, I'd just remove `unlikely()` as it might be counter-productive (`unlikely()` is used to optimize the codepath assuming that it will be `false` most of the time - but in the case where it's actually `true`, we'd lose some performance).

**Review by akien-mga — APPROVED** [review]
Good to merge after removal of `unlikely()` (also approved by @reduz).

**Comment by jkb0o** [comment]
Done

**Comment by akien-mga** [comment]
(What is `[funexpected]` in the commit log btw? :))

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.

**Comment by jkb0o** [comment]
> (What is `[funexpected]` in the commit log btw? :))
@akien-mga Funexpected is the company name.  We have a bunch of commits on the top of stable release of Godot, and this prefix helps us to rebase the current patched branch and cherry-pick rebased commits on the top of the new stable release. Also I plan to start contributing some parts of the code back.
