### PR TITLE
Don't mark cached previously pinned AnimationMixers

### LINKED ISSUE #102108: Editor crash when interacting with a re-opened scene containing an animation player
### Tested versions

At least 4.4.beta1 to current head `6dc78c8aa17ad46e701e0c4e7b7632c2f0e098f1` but involves code introduced in  https://github.com/godotengine/godot/pull/99700 or a related PR cc @hpvb 

~~As far as I've seen, the crash does not happen if the editor is compiled with `dev_build=yes`~~

### System information

Godot v4.4.beta.mono (6dc78c8aa) - macOS Sequoia (15.2.0) - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M2 (Apple8) - Apple M2 (8 threads)

### Issue description

After closing and re-opening a scene containing an animation player and then either selecting a node or closing the scene tab several times, either SIGSEGV or SIGBUS crashes the editor. From lldb:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x3d9ec6003f8001a8)
  * frame #0: 0x0000000102cb4df8 godot.macos.editor.arm64`Node::get_parent() const
    frame #1: 0x0000000102468e1c godot.macos.editor.arm64`SceneTreeEditor::_update_tree(bool) + 500
    frame #2: 0x0000000104bd0394 godot.macos.editor.arm64`CallQueue::_call_function(Callable const&, Variant const*, int, bool) + 336
    frame #3: 0x0000000104bd06b0 godot.macos.editor.arm64`CallQueue::flush() + 352
    frame #4: 0x0000000102ceb6d0 godot.macos.editor.arm64`SceneTree::physics_process(double) + 244
    frame #5: 0x00000001003f366c godot.macos.editor.arm64`Main::iteration() + 596
    frame #6: 0x0000000100383878 godot.macos.editor.arm64`OS_MacOS::run() + 148
    frame #7: 0x00000001003b0ad4 godot.macos.editor.arm64`main + 388
    frame #8: 0x0000000196350274 dyld`start + 2840
```
Presumably some call is getting inlined between _update_tree and get_parent?

### Steps to reproduce

Close and reopen the same scene several times in a row, optionally interacting with a node. In my tests, I saw a crash after anywhere between 1 and 4 close/reopen cycles with the last user action being any of opening the scene, closing the scene, or selecting a node in the tree.

### Minimal reproduction project (MRP)

[glb_test.zip](https://github.com/user-attachments/files/18680946/glb_test.zip)

### PR DESCRIPTION
**Pull request by hpvb**
AnimationPlayerEditor will hold on to pointers to no-longer existing Nodes that were previously pinned. Make sure to not mark them as dirty if they are not already inside the cache.

This fixes #102108

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by fire** [comment]
Weird the fix has nothing to do with AnimationMixers.

File: editor/gui/scene_tree_editor.cpp [hunk 1]
```diff
@@ -2373,6 +2380,14 @@ HashMap<Node *, SceneTreeEditor::CachedNode>::Iterator SceneTreeEditor::NodeCach
 	return I;
 }
 
+bool SceneTreeEditor::NodeCache::has(Node *p_node) {
+	HashMap<Node *, CachedNode>::Iterator I = get(p_node, false);
+	if (I) {
+		return true;
+	}
+	return false;
```
Comment (AThousandShips) [inline editor/gui/scene_tree_editor.cpp:2388]:
```suggestion
	return get(p_node, false) != nullptr;
```

Comment (hpvb) [reply editor/gui/scene_tree_editor.cpp:2388]: a `HashMap<Node *, CachedNode>::Iterator` isn't a `nullptr` when the node isn't found. I am not entirely sure if this works reliably.

Comment (hpvb) [reply editor/gui/scene_tree_editor.cpp]: I think explicitly calling `operator bool()` on the result is probably the way to go!

File: editor/gui/scene_tree_editor.cpp [hunk 2]
```diff
@@ -924,12 +924,19 @@ void SceneTreeEditor::_update_tree(bool p_scroll_to_selected) {
...
-			node_cache.mark_dirty(pinned_node);
+			if (node_cache.has(pinned_node)) {
+				node_cache.mark_dirty(pinned_node);
+			}
 		}
 		// If the current pinned node changed update both the old and new node.
 		if (node_cache.current_pinned_node != pinned_node) {
-			node_cache.mark_dirty(pinned_node);
-			node_cache.mark_dirty(node_cache.current_pinned_node);
+			// get_editing_node() will return deleted nodes. If the nodes are not in cache don't try to mark them.
```
Comment (a-johnston) [inline editor/gui/scene_tree_editor.cpp:933]: Why not also fix the upstream issue and null `original_node` when `player` is cleared?

**Comment by akien-mga** [comment]
Thanks!

File: editor/gui/scene_tree_editor.cpp (hunk 2 above)
Comment (akien-mga) [reply editor/gui/scene_tree_editor.cpp:933]: Apologies I missed this comment before merging, otherwise I'd have waited for @hpvb to reply first.

Comment (a-johnston) [reply editor/gui/scene_tree_editor.cpp:933]: No worries, ultimately the current code only uses `get_editing_node` in two places and both would now be safe handling that pointer but it seems like it would be better to prevent that from being returned in the first place.

Comment (hpvb) [reply editor/gui/scene_tree_editor.cpp:933]: Because this was a release blocker I decided to do a local fix. The current way the editor pinning works is kind of broken, editors can be pinned but the status of whether or not it is pinned is stored in the button toggle state, which gets reset when switching scenes. 

The behavior is kind of silly as it is now, and was silly before any of my changes. I'm planning to do a ui fix pr separately to fix the pinning behavior in general.
