### PR TITLE
Fix GDScript extends path recursion to itself

### LINKED ISSUE #112583: Script extending itself makes the project not able to be opened
### Tested versions

4.6 6fd949a
Does not happen in 4.6 dev3

### System information

W10

### Issue description

I accidentally made a script extend itself and it caused crash and then the project couldn't be opened.
```
__chkstk() Line 109 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\misc\amd64\chkstk.asm:109)
GDScriptParser::GDScriptParser() Line 92 (c:\godot_source\modules\gdscript\gdscript_parser.cpp:92)
GDScriptParser::clear() Line 177 (c:\godot_source\modules\gdscript\gdscript_parser.cpp:177)
GDScriptParser::parse(const String & p_source_code, const String & p_script_path, bool p_for_completion, bool p_parse_body) Line 350 (c:\godot_source\modules\gdscript\gdscript_parser.cpp:350)
GDScriptLanguage::get_global_class_name(const String & p_path, String * r_base_type, String * r_icon_path, bool * r_is_abstract, bool * r_is_tool) Line 2818 (c:\godot_source\modules\gdscript\gdscript.cpp:2818)
... (1000+ lines)
GDScriptLanguage::get_global_class_name(const String & p_path, String * r_base_type, String * r_icon_path, bool * r_is_abstract, bool * r_is_tool) Line 2848 (c:\godot_source\modules\gdscript\gdscript.cpp:2848)
EditorFileSystem::_get_global_script_class(const String & p_type, const String & p_path) Line 2080 (c:\godot_source\editor\file_system\editor_file_system.cpp:2080)
EditorFileSystem::_first_scan_process_scripts(const EditorFileSystem::ScannedDirectory * p_scan_dir, List<String,DefaultAllocator> & p_gdextension_extensions, HashSet<String,HashMapHasherDefault,HashMapComparatorDefault<String,void>> & p_existing_class_names, HashSet<String,HashMapHasherDefault,HashMapComparatorDefault<String,void>> & p_extensions) Line 370 (c:\godot_source\editor\file_system\editor_file_system.cpp:370)
EditorFileSystem::_first_scan_process_scripts(const EditorFileSystem::ScannedDirectory * p_scan_dir, List<String,DefaultAllocator> & p_gdextension_extensions, HashSet<String,HashMapHasherDefault,HashMapComparatorDefault<String,void>> & p_existing_class_names, HashSet<String,HashMapHasherDefault,HashMapComparatorDefault<String,void>> & p_extensions) Line 350 (c:\godot_source\editor\file_system\editor_file_system.cpp:350)
EditorFileSystem::_first_scan_process_scripts(const EditorFileSystem::ScannedDirectory * p_scan_dir, List<String,DefaultAllocator> & p_gdextension_extensions, HashSet<String,HashMapHasherDefault,HashMapComparatorDefault<String,void>> & p_existing_class_names, HashSet<String,HashMapHasherDefault,HashMapComparatorDefault<String,void>> & p_extensions) Line 350 (c:\godot_source\editor\file_system\editor_file_system.cpp:350)
EditorFileSystem::_first_scan_filesystem() Line 322 (c:\godot_source\editor\file_system\editor_file_system.cpp:322)
EditorFileSystem::scan() Line 1070 (c:\godot_source\editor\file_system\editor_file_system.cpp:1070)
EditorNode::_notification(int p_what) Line 831 (c:\godot_source\editor\editor_node.cpp:831)
EditorNode::_notification_forwardv(int p_notification) Line 119 (c:\godot_source\editor\editor_node.h:119)
Object::_notification_forward(int p_notification) Line 993 (c:\godot_source\core\object\object.cpp:993)
Object::notification(int p_notification, bool p_reversed) Line 919 (c:\godot_source\core\object\object.h:919)
SceneTree::_process_group(SceneTree::ProcessGroup * p_group, bool p_physics) Line 1202 (c:\godot_source\scene\main\scene_tree.cpp:1202)
SceneTree::_process(bool p_physics) Line 1279 (c:\godot_source\scene\main\scene_tree.cpp:1279)
SceneTree::process(double p_time) Line 708 (c:\godot_source\scene\main\scene_tree.cpp:708)
Main::iteration() Line 4768 (c:\godot_source\main\main.cpp:4768)
OS_Windows::run() Line 2333 (c:\godot_source\platform\windows\os_windows.cpp:2333)
widechar_main(int argc, wchar_t * * argv) Line 96 (c:\godot_source\platform\windows\godot_windows.cpp:96)
_main() Line 122 (c:\godot_source\platform\windows\godot_windows.cpp:122)
main(int argc, char * * argv) Line 136 (c:\godot_source\platform\windows\godot_windows.cpp:136)
WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 150 (c:\godot_source\platform\windows\godot_windows.cpp:150)
[Inline Frame] invoke_main() Line 102 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:102)
__scrt_common_main_seh() Line 288 (d:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
ShimMainCRTStartup(...) Line 74 (c:\godot_source\platform\windows\cpu_feature_validation.c:74)
kernel32.dll!00007ffd17887374() (Nieznane źródło:0)
ntdll.dll!00007ffd1959cc91() (Nieznane źródło:0)
```

Likely some sort of infinite recursion / stack overflow. Seems very recent.

### Steps to reproduce

1. Make a script
```GDScript
extends "this_script.gd"
```

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by M4rchy-S**
See issue:  #112583
Problem was tested with v4.6dev

Error is happening during saving and loading script where get_global_class_name_ calling itself.

That is temporary fix because it is advised to ask maintainer of EditorFileSystem for editing **_GDScriptLanguage::get_global_class_name_** because it is error tolerant.

*Bugsquad edit:*
- Fixes #112583

### CODE REVIEW

**Comment by fire** [comment]
Are you able to edit EditorFileSystem directly?

**Comment by M4rchy-S** [comment]
> Are you able to edit EditorFileSystem directly?

I do not think problem directly with EditorFileSystem.
It should not fall in recursion with the same file paths.

**Comment by HolonProduction** [comment]
Doesn't this approach still fail with inheritance cycles that are bigger than just one script?

```gdscript
# a.gd
extends "b.gd"

# b.gd
extends "a.gd"
```

**Comment by M4rchy-S** [comment]
> Doesn't this approach still fail with inheritance cycles that are bigger than just one script?
> 
> ```gdscript
> # a.gd
> extends "b.gd"
> 
> # b.gd
> extends "a.gd"
> ```

You are right. I will try to figure something out. Because the first that comes to mind is cycle detection with Hashset.

**Review by HolonProduction — APPROVED** [review]
I am able to reproduce the original issue and can confirm that this patch fixes it.

I'm approving based on testing and the approach using a `HashSet`.

I'm not approving the specific implementation using a `thread_local`. I'm no c++ wizard and don't know if it's a sensible approach.

Edit: I'm also approving that this is the right place to fix the issue. EditorFileSystem is not responsible for this.

File: modules/gdscript/gdscript.cpp [hunk 1]
```diff
@@ -2852,7 +2858,9 @@ String GDScriptLanguage::get_global_class_name(const String &p_path, String *r_b
 				if (!subclass->extends_path.is_empty()) {
 					if (subclass->extends.is_empty()) {
 						// We only care about the referenced class_name.
+						extends_visited_traversal.insert(subclass->extends_path);
 						_ALLOW_DISCARD_ get_global_class_name(subclass->extends_path, r_base_type);
```
Comment (Ivorforce) [inline modules/gdscript/gdscript.cpp]:
```suggestion
						_ALLOW_DISCARD_ _get_global_class_name(subclass->extends_path, r_base_type, nullptr, nullptr, nullptr, r_visited);
```

File: modules/gdscript/gdscript.cpp [hunk 2]
```diff
@@ -2852,7 +2858,9 @@ String GDScriptLanguage::get_global_class_name(const String &p_path, String *r_b
 				if (!subclass->extends_path.is_empty()) {
 					if (subclass->extends.is_empty()) {
 						// We only care about the referenced class_name.
+						extends_visited_traversal.insert(subclass->extends_path);
```
Comment (Ivorforce) [inline modules/gdscript/gdscript.cpp]:
```suggestion
```

File: modules/gdscript/gdscript.cpp [hunk 3]
```diff
@@ -2852,7 +2858,9 @@ String GDScriptLanguage::get_global_class_name(const String &p_path, String *r_b
...
 						_ALLOW_DISCARD_ get_global_class_name(subclass->extends_path, r_base_type);
+						extends_visited_traversal.erase(subclass->extends_path);
```
Comment (Ivorforce) [inline modules/gdscript/gdscript.cpp]:
```suggestion
```

File: modules/gdscript/gdscript.cpp [hunk 4]
```diff
@@ -2829,6 +2831,10 @@ String GDScriptLanguage::get_global_class_name(const String &p_path, String *r_b
 		return String(); // No class parsed.
 	}
 
+	if (!c->extends_path.is_empty() && extends_visited_traversal.has(c->extends_path)) {
+		return String();
+	}
+
```
Comment (Ivorforce) [inline modules/gdscript/gdscript.cpp]:
```suggestion
```

File: modules/gdscript/gdscript.cpp [hunk 5]
```diff
@@ -2813,6 +2813,8 @@ bool GDScriptLanguage::handles_global_class_type(const String &p_type) const {
 }
 
 String GDScriptLanguage::get_global_class_name(const String &p_path, String *r_base_type, String *r_icon_path, bool *r_is_abstract, bool *r_is_tool) const {
+	static thread_local HashSet<String> extends_visited_traversal;
+
```
Comment (Ivorforce) [inline modules/gdscript/gdscript.cpp:2832]:
```suggestion
String GDScriptLanguage::get_global_class_name(const String &p_path, String *r_base_type, String *r_icon_path, bool *r_is_abstract, bool *r_is_tool) const {
	return _get_global_class_name()p_path, r_base_type, r_icon_path, r_is_abstract, r_is_tool, LocalVector<String>());
}

String GDScriptLanguage::_get_global_class_name(const String &p_path, String *r_base_type, String *r_icon_path, bool *r_is_abstract, bool *r_is_tool, LocalVector<String> &r_visited) const {
	if (r_visited.contains(p_path)) {
		return;
	}

	r_visited.push_back(p_path);	
```

**Review by Ivorforce — COMMENTED** [review]
The proposed solution should work, but I don't think `thread_local` is necessary here.

Instead, i would like to propose using a parameter (on a helper function) to track visitations. I think this should work the same way, but it would be a little easier to reason about.
I've added the implementation as (i think?) a complete suggestion (except the `.h` file), but it would need to be tested.

**Comment by M4rchy-S** [comment]
I am new to codebase and I do not know if this system is multithreaded. That is why I left thread_local as a placeholder. I tried to find more suitable place to hold hashset like structure because it is const function and cannot easily add or remove from hashset without changing prototype from parent class.

File: modules/gdscript/gdscript.cpp [hunk 6]
```diff
@@ -2813,6 +2813,11 @@ bool GDScriptLanguage::handles_global_class_type(const String &p_type) const {
 }
 
 String GDScriptLanguage::get_global_class_name(const String &p_path, String *r_base_type, String *r_icon_path, bool *r_is_abstract, bool *r_is_tool) const {
+	HashSet<String> r_val = HashSet<String>();
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.cpp]:
```suggestion
	HashSet<String> r_val;
```
Redundant default

**Comment by Ivorforce** [comment]
You didn't apply all of my suggestions. Please review and apply them.

File: core/object/script_language.h [hunk 7]
```diff
@@ -444,6 +444,7 @@ class ScriptLanguage : public Object {
 
 	virtual bool handles_global_class_type(const String &p_type) const { return false; }
 	virtual String get_global_class_name(const String &p_path, String *r_base_type = nullptr, String *r_icon_path = nullptr, bool *r_is_abstract = nullptr, bool *r_is_tool = nullptr) const { return String(); }
+	virtual String _get_global_class_name(const String &p_path, String *r_base_type, String *r_icon_path, bool *r_is_abstract, bool *r_is_tool, HashSet<String> &r_visited) const { return String(); }
```
Comment (Ivorforce) [inline core/object/script_language.h]: This should be declared on `gdscript.h` instead, and as `private` and not `virtual`.

**Comment by M4rchy-S** [comment]
> You didn't apply all of my suggestions. Please review and apply them.

Sorry. I didn't see full suggestions

File: modules/gdscript/gdscript.cpp [hunk 8]
```diff
@@ -2813,12 +2813,23 @@ bool GDScriptLanguage::handles_global_class_type(const String &p_type) const {
...
+}
+
+String GDScriptLanguage::_get_global_class_name(const String &p_path, String *r_base_type, String *r_icon_path, bool *r_is_abstract, bool *r_is_tool, LocalVector<String> &r_visited) const {
 	Error err;
 	Ref<FileAccess> f = FileAccess::open(p_path, FileAccess::READ, &err);
 	if (err) {
 		return String();
 	}
 
+	if (r_visited.has(p_path)) {
```
Comment (Ivorforce) [inline modules/gdscript/gdscript.cpp]: Looking at this again, this could probably be done earlier (at the start of the function). (Both the if and the push_back)

**Review by Ivorforce — APPROVED** [review]
LGTM

**Comment by Repiteo** [comment]
Could you squash your commits? See our [pull request guidelines](https://contributing.godotengine.org/en/latest/organization/pull_requests/creating_pull_requests.html#the-interactive-rebase) for more information

**Comment by akien-mga** [comment]
Sorry to add more nitpicks, but the commit message should also be amended to be clearer. "Fix rec" isn't a good description of what the commit is doing. See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind

You can use the same commit title as this PR is using.

And @Ivorforce's suggestion would be worth applying too at the same time.

Then if @HolonProduction thinks the latest code is good, we should be good to merge.

File: modules/gdscript/gdscript.cpp [hunk 9]
```diff
@@ -2826,12 +2826,23 @@ bool GDScriptLanguage::handles_global_class_type(const String &p_type) const {
...
+	}
+
 	Error err;
 	Ref<FileAccess> f = FileAccess::open(p_path, FileAccess::READ, &err);
 	if (err) {
 		return String();
 	}
 
+	r_visited.push_back(p_path);
+
```
Comment (HolonProduction) [inline modules/gdscript/gdscript.cpp]: Please put that directly after the `r_visited.has(p_path)` check. Splitting it like this just makes the code harder to read IMHO

Comment (akien-mga) [reply modules/gdscript/gdscript.cpp]: Beyond code readability, I was also wondering whether it could lead to some recursion when called with a path that will fail to load repeatedly (which would never be marked as visited in the current version, but should be if this is moved before the file access).

Comment (HolonProduction) [reply modules/gdscript/gdscript.cpp]: My conclusion to this was, that it should not create issue other than readability. There is only one recursive call so after the IO based early return no other recursive call can occur.

Basically the way recursion is used here is akin to tailrecursion or an iterative approach. Any early return completely breaks of the iteration.

**Review by HolonProduction — APPROVED** [review]
LGTM as a minimally invasive fix for the crash.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
