### PR TITLE
Don't allow empty string when splitting allowed types and allowed subtypes in `_is_drop_valid()` in EditorPropertyArray 

### LINKED ISSUE #104145: Can't drop node into `Array[NodePath]` anymore
### Tested versions

- Reproducible in current : 4.5 master (87f897ae0ad5a6770c6ee267e2f3458c89a06df7)
- Not reproducible in : 4.4-stable

### System information

Win 10

### Issue description

It is not possible to drop node(s) into exported `Array[NodePath]` anymore. It's a regression from https://github.com/godotengine/godot/pull/102630

### Steps to reproduce

1. `@export` an `Array[NodePath]`
2. Try to drop node(s) into it
3. Will consider drop invalid and thus no highlight

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by AeioMuch**
Fixes https://github.com/godotengine/godot/issues/104145

CC @KoBeWi & @ttencate

### CODE REVIEW

File: editor/editor_properties_array_dict.cpp [hunk 1]
```diff
@@ -590,6 +590,9 @@ bool EditorPropertyArray::_is_drop_valid(const Dictionary &p_drag_data) const {
 
 			for (String at : allowed_type.split(",")) {
```
Comment (KoBeWi) [inline editor/editor_properties_array_dict.cpp:591]: You could do this instead:
```suggestion
			for (String at : allowed_type.split(",", false)) {
```

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
