### PR TITLE
Cancel save dialog on editor exit

### LINKED ISSUE #102271: 2D, 3D, Script and AssetLib menu bug if you click cancel when exiting Godot
### Tested versions

v4.3.stable.official [77dcf97d8]
v4.4.beta2.official [a013481b0]

### System information

Vulkan 1.3.280 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce RTX 3070 . Windows 11 23h.

### Issue description

The bug occurs if you follow these steps: Have two scene tabs open in Godot. For example, modify the position of a node but do not save it. Click on the x to exit. The engine will ask if you want to save before exiting. Click on CANCEL. Now click on the scene that has not been modified and that has no changes to save. Then click on 2D, 3D, SCRIPT or ASSETLIB scene in the main menu above Godot. You will see that it gets bugged, not changing the engine view according to the selected one and you cannot open the script by clicking on the icon next to each node that has a script. Watch the video below:

https://github.com/user-attachments/assets/77b9eed1-a6ac-43d4-8ec4-8c44986c432d

### Steps to reproduce

Open the project I sent and follow what I wrote above and what I do in the video sent.
This happens in godot 4.3 stable and 4.4 beta 2.

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/18626678/test.zip)

### LINKED ISSUE #108675: Canceling save dialog on editor exit leaves Godot in unusable state (top panel doesn't work)
### Tested versions

- Reproducible in `4.4.1` and `4.5-beta3`

### System information

Godot v4.5.beta3 - macOS Sequoia (15.5.0) - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - Apple M1 - Apple M1 (8 threads) - 8.00 GiB memory

### Issue description

When exiting the Godot Editor with unsaved changes, a confirmation dialog appears asking whether to save the changes. If the user clicks `Cancel`, the editor does not close — as expected — but it enters a broken UI state:

https://github.com/user-attachments/assets/b0e4ba27-25dd-4656-8327-a2f510248e13

### Steps to reproduce

1. open a project
2. modify some scenes
3. close the Godot Editor
4. in the confirmation dialog that appears, click `Cancel`

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/21262672/test.zip)

### PR DESCRIPTION
**Pull request by Alex2782**
Fixes: #102271
Fixes: #108675

The solution seems very simple. 
 - Clear the `tabs_to_close` list so the user isn't spammed with confirmation dialogs: [comment](https://github.com/godotengine/godot/issues/108675#issuecomment-3079724758)
- `changing_scene = false;` so that `Top Panel` with `2D / 3D / Script` etc. remains functional.

```cpp
void EditorNode::_cancel_close_scene_tab() {
	if (_is_closing_editor()) {
		tab_closing_menu_option = -1;
	}
	changing_scene = false;
	tabs_to_close.clear();
}

```

-----------

### Test on MacOS

https://github.com/user-attachments/assets/4c0cd19f-c497-410a-9fb3-8bd9bcf23cf5

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -6205,6 +6205,8 @@ void EditorNode::_scene_tab_closed(int p_tab) {
 
 void EditorNode::_cancel_close_scene_tab() {
 	if (_is_closing_editor()) {
```
Comment (KoBeWi) [inline editor/editor_node.cpp:6207]: This condition shouldn't be here, because it causes another bug:
Have 2 unsaved scenes, select Close All Scenes option, then cancel. After that, once you close any scene, the editor will try closing remaining scenes

Comment (Alex2782) [reply editor/editor_node.cpp:6207]: Thanks for the hint, I think I was able to reproduce it.
`ERROR: editor/editor_node.cpp:6100 - Condition "tab_idx < 0" is true.`

Comment (Alex2782) [reply editor/editor_node.cpp:6207]: > This condition shouldn't be here, because it causes another bug:

The behavior seems familiar, and I don't think my change has anything to do with it. `_is_closing_editor()` is `false` when `Close All Scenes` is executed. We actually need to remove the if statement, but I'd have to look more closely at the effects.

<details><summary>print_line  debug</summary>

-----------

The `tabs_to_close` list should also be deleted correctly here. However, after `Cancel`, it is constantly incremented (see output).


image


</details>

---------------

> Have 2 unsaved scenes, select Close All Scenes option, then cancel. After that, once you close any scene, the editor will try closing remaining scenes

reproducible also in v4.5.beta3.official [4d1f26e1f] 


Bildschirmfoto 2025-07-17 um 19 20 55

Comment (Alex2782) [reply editor/editor_node.cpp:6207]: The bug fix is now also active for `Close All Scenes`, outside of the if statement. 
_(Reproducible in Beta 3 and, I think, also in 4.4x.)_

```cpp
void EditorNode::_cancel_close_scene_tab() {
	if (_is_closing_editor()) {
		tab_closing_menu_option = -1;
	}
	changing_scene = false;
	tabs_to_close.clear();
}
```

**Comment by Alex2782** [comment]
**Hint:**
The same issues occur after `Close All Scenes` -> `Cancel` not only with `on editor exit` (#102271 #108675)
The new change should fix it too.


-------------

Should I adjust my commit message?
> Fix: Canceling save dialog on editor exit

Fire had changed the title to `Cancel save dialog on editor exit`, now I'm unsure about what the commit and Github titles for PR should be 😃

File: editor/editor_node.cpp (hunk 1 above)
Comment (KoBeWi) [reply editor/editor_node.cpp:6207]: That condition is still there. It's not really a problem, but it doesn't have any purpose either.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
