### PR TITLE
Fix editor crash when inspecting 2 objects handled by the same plugin

### LINKED ISSUE #97577: Unexpected errors when creating SpriteFrames:Condition “plugins_list.has(p_plugin)" is true.
### Tested versions

- Reproducible：Godot4.0 stable, Godot4.0.1stable ,Godot4.0.2stable ,Godot 4.0.3stable ,Godot 4.0.4stable,Godot 4.1stable,Godot 4.1.1stable,Godot 4.1.2stable,Godot4.1.4stable,Godot4.2stable,Godot4.2.1stable ,Godot4.2.2stable,Godot4.3stable,Godot4.4.1dev,Godot4.4.2dev
- Not Reproducible：Godot3.6 stable

### System information

Windows10 - Godot 4.4.dev2 - Vulkan(Forward+)

### Issue description

https://github.com/user-attachments/assets/e57d4a80-f46e-4839-951b-1f6612c5ac5f

After creating an AnimatedSprite2D, I added a new SpriteFrames. Clicking on it again triggers the warning: **'editor/editor_node.cpp:8116 - Condition "plugins_list.has(p_plugin)" is true'**. This bug also exists in Godot 4.3.1 stable and every godot 4 version

### Steps to reproduce

https://github.com/user-attachments/assets/a4abda81-5a10-499f-89b1-f56d49e47ec2

https://github.com/user-attachments/assets/a4abda81-5a10-499f-89b1-f56d49e47ec2
0.Open Godot 4.4 dev2.
1.Create a new scene with any type of root node (in this example, it's Node2D).
2.Add a child node of type AnimatedSprite2D.
3.Click on the AnimatedSprite2D node, and in the inspector under the AnimatedSprite2D section, click on Animation/Sprite Frames and create a new SpriteFrames.
4.**(Important) Click on the root node, then click back on the AnimatedSprite2D node, and click on Animation/Sprite Frames in the inspector under the AnimatedSprite2D section.**,
5.Check the Output.
6.Click on the root node again, then click back on the AnimatedSprite2D node. Repeat this step, and you will see that every time you click on the AnimatedSprite2D node, the error "editor/editor_node.cpp:8116 - Condition 'plugins_list.has(p_plugin)' is true" will be triggered in the Output.

### Minimal reproduction project (MRP)

[mrp-for-the-editor-editor_node.cpp-8116---condition--plugins_list.has(p_plugin)--is-true'.zip](https://github.com/user-attachments/files/17173715/mrp-for-the-editor-editor_node.cpp-8116---condition--plugins_list.has.p_plugin.--is-true.zip)

### LINKED ISSUE #103909: Editor crash when inspecting 2 Objects handled by the same plugin, caused by corrupted ObjectID
### Tested versions

4.4

### System information

W10

### Issue description

When trying to edit 2 objects handled by the same plugin (e.g. by unfolding them in the inspector), the editor may sometimes print an error:
```
Condition "slot >= slot_max" is true. Returning nullptr.
```
It comes from here, and judging from the comment, it's not supposed to happen:

https://github.com/godotengine/godot/blob/cae3d722a3abd6d93d84a84beccc65a78948653f/core/object/object.h#L1047

And indeed, the ObjectID is corrupted, because sometimes you'll get this crash:
```
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.5.dev.custom_build (caa59c5611ee77a574d4eaf957f264ceeb17cbd3)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] ObjectID::operator!= (C:\godot_source\core\object\object_id.h:51)
[1] EditorNode::edit_item (C:\godot_source\editor\editor_node.cpp:2413)
[2] call_with_variant_args_helper<EditorNode,Object *,Object *,0,1> (C:\godot_source\core\variant\binder_common.h:319)
[3] call_with_variant_args<EditorNode,Object *,Object *> (C:\godot_source\core\variant\binder_common.h:429)
[4] CallableCustomMethodPointer<EditorNode,void,Object *,Object *>::call (C:\godot_source\core\object\callable_method_pointer.h:108)
[5] Callable::callp (C:\godot_source\core\variant\callable.cpp:58)
[6] CallQueue::_call_function (C:\godot_source\core\object\message_queue.cpp:221)
[7] CallQueue::flush (C:\godot_source\core\object\message_queue.cpp:270)
[8] SceneTree::physics_process (C:\godot_source\scene\main\scene_tree.cpp:537)
[9] Main::iteration (C:\godot_source\main\main.cpp:4462)
[10] OS_Windows::run (C:\godot_source\platform\windows\os_windows.cpp:2075)
[11] widechar_main (C:\godot_source\platform\windows\godot_windows.cpp:97)
[12] _main (C:\godot_source\platform\windows\godot_windows.cpp:122)
[13] main (C:\godot_source\platform\windows\godot_windows.cpp:136)
[14] WinMain (C:\godot_source\platform\windows\godot_windows.cpp:150)
[15] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[16] <couldn't map PC to fn name>
-- END OF BACKTRACE --
```
The error and crash seem to be random, not sure what exactly causes them.

### Steps to reproduce

1. Open the MRP
2. In Sample_Scene click the root node and open C 1 Resource
3. Open C 2. C 1 should close with an error
4. Try opening both resources and/or re-selecting the node
5. Sometimes crash or error

### Minimal reproduction project (MRP)

[mrp_crash_gdscript.zip](https://github.com/user-attachments/files/19165139/mrp_crash_gdscript.zip)

### LINKED ISSUE #103976: Editor Plugins not removed when Folding an ancestor Resource
### Tested versions

78c9f8ddd906273a5970518d54d2f5114d07b246

### System information

Windows 11

### Issue description

Possibly related to https://github.com/godotengine/godot/issues/103615, but I have been unable to reproduce the crash to know for sure.

This is a minor bug in the inspector a resource property, which had corresponding editor plugins associated with a descendent properties, does not cleanup editor plugins from the list if the ancestor property was folded. This is because the code associated with removing a plugin from the active list is only called if the exact property with an associated plugin which handles the type is deselected. If, however, an EditorPropertyResource which contains a property handled by an plugin is closed while the property handled by a plugin is open, it will not be removed from the active list and the editor will show a warning that it tried to add the plugin to the list twice while it is already open.

https://github.com/user-attachments/assets/3ca0cc80-f370-4d84-a65c-5c72d8791c12

### Steps to reproduce

* Create a MeshInstance.
* Assign it a ShaderMaterial.
* Assign the ShaderMaterial a Shader.
* Open the Shader property as shown in the video.
* Click on the ShaderMaterial property. to close it.
* Click on it again to reopen it and note the error.

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #104250: When loading the editor with a scene with a shader selected, an error is output: `Condition "plugins_list.has(p_plugin)" is true`
### Tested versions

- Reproducible in master [fde0616]
- Reproducible in v4.4.stable.official [4c311cbee]
- Not reproducible in v4.3.stable.official [77dcf97d8]

### System information

Windows 11 - Vulkan (Forward+)

### Issue description

`Condition "plugins_list.has(p_plugin)" is true` appears in the output log when opening a project, under specific conditions:
- The scene first displayed to the user already has `Material->ShaderMaterial->Shader` open in the node inspector, with the shader script selected.

See previous discussion in #80126. Note that this issue is subtly different from #97577 -- that issue is reproducible in 4.3, this one is not.

### Steps to reproduce

1. Open the MRP.
2. Open `main.tscn`.
3. In the scene panel, select the `Main` node.
4. In the node inspector panel, expand the `Material` tab.
5. Expand `ShaderMaterial`.
6. Expand `main.gdshader` inside the `ShaderMaterial`. 
7. Save the scene (CTRL+S).
8. Reload the project (or, close the editor and reopen the project manually).

### Minimal reproduction project (MRP)

[plugin-list-error.zip](https://github.com/user-attachments/files/19274190/plugin-list-error.zip)

### PR DESCRIPTION
**Pull request by Rindbee**
Already activated plugins do not need to be added again to `editor_plugins_over`.

`fold_resource()` changes `active_plugins` and is unsafe to call while iterating over `active_plugins`.

Fix #103909, fix #104250, fix #97577.
Close #103976.

### CODE REVIEW

**Review by 0xcafeb33f — APPROVED** [review]
I tested this PR, and it fixes #103909, #104250, and #97577 on my setup (64-bit Windows).

**Comment by KoBeWi** [comment]
When you open a Shader from ShaderMaterial, the material gets folded and you can no longer unfold it.

https://github.com/user-attachments/assets/a0570e16-01ec-4a0d-adf3-a55d9fb16587

In 4.5 dev1 trying to open it causes a crash 🙃

**Comment by Rindbee** [comment]
I couldn't reproduce it.

https://github.com/user-attachments/assets/25a3f1f9-3c29-439e-89a4-55214b035096

Tried from v4.5.dev1.official [97241ffea], also only error message, no crash. Can you provide the MRP?

**Comment by KoBeWi** [comment]
Try with built-in shader.
As for the crash, pretty sure it's random like #103909.

**Comment by Rindbee** [comment]
> Try with built-in shader. 

Still can't reproduce.

**Comment by 0xcafeb33f** [comment]
> Try with built-in shader.

I tried with a built-in shader on 4.5dev1 both with and without this PR, and I could not reproduce this issue. What type of node are you adding the material to? Is there anything else open in the editor, or present in the project, at the time of the bug occurring?

**Comment by KoBeWi** [comment]
I can't reproduce it anymore, idk what happened. Maybe I reloaded the scene and the shader wasn't closed properly for some reason (normally all built-in shaders are closed with the scene).

The error/crash is probably the same case as #104250, i.e. unfold a shader and restart editor. It's fixed by this PR.

File: editor/editor_properties.cpp [hunk 1]
```diff
@@ -3363,7 +3363,7 @@ void EditorPropertyResource::update_property() {
 			sub_inspector = nullptr;
 
 			if (opened_editor) {
-				EditorNode::get_singleton()->hide_unused_editors();
+				EditorNode::get_singleton()->hide_unused_editors(this);
```
Comment (KoBeWi) [inline editor/editor_properties.cpp:3366]: This might cause problems if the property had a sub-inspector editing another Resource. Though not sure if it can happen (outside of custom plugins at least).

**Review by KoBeWi — APPROVED** [review]
I tested various known errors when editing Resources in the inspector and they seem to be all gone. The ShaderMaterial problem I found might not have been caused by this PR, I didn't spot other problems.

File: editor/editor_properties.cpp (hunk 1 above)
Comment (Rindbee) [reply editor/editor_properties.cpp]: From the logic of `edit_item()`, a plugin can only edit one object at a time. However, I am not sure what happens when the property is collapsed, so it may be safer to modify it back.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.4.1.
