### PR TITLE
Fix preset cache usage in ColorPicker

### LINKED ISSUE #104223: Wrong color presets displayed after saving color palette with multiple ColorPickers in the scene
### Tested versions

- Reproducible in: 4.4 (and previous 4.4.dev builds since saving color palettes was introduced #91604)

### System information

Godot v4.4.stable - Windows 11 (build 26100) - Multi-window, 1 monitor - Vulkan (Forward+) - integrated AMD Radeon 780M Graphics (Advanced Micro Devices, Inc.; 32.0.11039.8001) - AMD Ryzen 7 8845HS w/ Radeon 780M Graphics (16 threads)

### Issue description

If you have multiple `ColorPicker`s in the scene and each has some color presets, and you will save one as color palette, presets from all `ColorPicker`s will be displayed as colors of this palette. However, the saved palette has only presets from the `ColorPicker` that was used to save it.

https://github.com/user-attachments/assets/e5482a96-a437-4e20-987a-19d478d7943d

From the code it seems to be a problem with using `preset_cache` in `ColorPicker` to display colors, which is `static`. 

### Steps to reproduce

1. Add 2 or more `ColorPicker`s to the scene
2. Assign different colors to each `ColorPicker`
3. Run the game
4. Open Swatches in each `ColorPicker` and add current color to presets
5. Save presets of one `ColorPicker` as color palette
6. You should see colors from all `ColorPicker`s displayed as the palette in the one where you saved presets

### Minimal reproduction project (MRP)

[regression-test-project.zip](https://github.com/user-attachments/files/19270266/regression-test-project.zip)

### PR DESCRIPTION
**Pull request by FeniXb3**
Fixes #104223

<details>
<summary>It also fixes two additional bugs (click to expand)</summary>

1. Palette name was not being cleared in editor in other `ColorPicker`s. Video of incorrect behaviour from 4.4.stable:

https://github.com/user-attachments/assets/89b9943f-dc5b-45fc-9216-0ff14d28861e

2. Cached presets had wrong size when adding `ColorPicker` in runtime. Video of incorrect behaviour from 4.4.stable:

https://github.com/user-attachments/assets/e0fe1684-e9c4-4dc3-9ea0-1255dd5b4a36

</details>

**Correct behaviour, fixed with this PR**:

https://github.com/user-attachments/assets/90e0cf48-8300-43ef-80f7-6aa8284f66f9

https://github.com/user-attachments/assets/558267ff-80ae-4baa-bea5-44f94d9ec496

### CODE REVIEW

File: scene/gui/color_picker.cpp [hunk 1]
```diff
@@ -745,7 +748,11 @@ void ColorPicker::_update_presets() {
 		String cached_name = editor_settings->call(SNAME("get_project_metadata"), "color_picker", "palette_name", String());
 		palette_path = editor_settings->call(SNAME("get_project_metadata"), "color_picker", "palette_path", String());
 		bool palette_edited = editor_settings->call(SNAME("get_project_metadata"), "color_picker", "palette_edited", false);
-		if (!cached_name.is_empty()) {
+		if (cached_name.is_empty()) {
+			palette_name->set_text("");
```
Comment (KoBeWi) [inline scene/gui/color_picker.cpp:752]: Is there any use in removing the text if the label is getting hidden?

Comment (FeniXb3) [reply scene/gui/color_picker.cpp:752]: Good point. I simply did it the same way it is done elsewhere - https://github.com/godotengine/godot/blob/240861f41962b6570594ec83ecae004e5793ae5f/scene/gui/color_picker.cpp#L1144

Should I remove it in both places?

File: scene/gui/color_picker.cpp [hunk 2]
```diff
@@ -759,14 +766,16 @@ void ColorPicker::_update_presets() {
 	}
 #endif
 
-	// Rebuild swatch color buttons, keeping the add-preset button in the first position.
-	for (int i = 1; i < preset_container->get_child_count(); i++) {
-		preset_container->get_child(i)->queue_free();
-	}
+	if (presets.is_empty() || Engine::get_singleton()->is_editor_hint()) {
```
Comment (KoBeWi) [inline scene/gui/color_picker.cpp:769]: I think this points at the main problem here.

The reported issue was about standalone ColorPicker, while the preset update code assumes that the ColorPicker always comes from ColorPickerButton. I think we should always update the presets in the latter case. For that the ColorPicker needs to know whether it's standalone or from a button.

File: scene/gui/color_picker.cpp (hunk 1 above)
Comment (KoBeWi) [reply scene/gui/color_picker.cpp]: Yeah, you could.

File: scene/gui/color_picker.cpp [hunk 3]
```diff
@@ -730,10 +731,10 @@ void ColorPicker::_update_color(bool p_update_sliders) {
 
 void ColorPicker::_update_presets() {
 	int preset_size = _get_preset_size();
+	btn_add_preset->set_custom_minimum_size(Size2(preset_size * 1, preset_size));
```
Comment (KoBeWi) [inline scene/gui/color_picker.cpp:734]:
```suggestion
	btn_add_preset->set_custom_minimum_size(Size2(preset_size, preset_size));
```

File: scene/gui/color_picker.h [hunk 4]
```diff
@@ -170,6 +170,7 @@ class ColorPicker : public VBoxContainer {
 	Button *btn_pick = nullptr;
 	Label *palette_name = nullptr;
 	String palette_path;
+	bool presets_just_loaded;
```
Comment (KoBeWi) [inline scene/gui/color_picker.h:173]:
```suggestion
	bool presets_just_loaded = false;
```

File: scene/gui/color_picker.cpp (hunk 2 above)
Comment (FeniXb3) [reply scene/gui/color_picker.cpp]: Are you sure ColorPicker should behave differently depending on being standalone or from ColorPickerButon? I think it would be confusing, for me at least. I would expect them to behave in the same way. I am not sure if making it behave differently in game and in editor is a good idea for the same reason, but I think we might want to use them differently when letting players to use them.

Additionaly, with palettes we have some confusing cases now (since 4.4 till 4.5 dev 2) - if you have 2 ColorPickerButtons, load/save a palette in one and clear swatches in another one, the first one still has the name of a palette. If we simply add/remove a color in the second one, the first one's palette will not be marked as changed. See the videos below (project was running on 4.5 dev 2):

https://github.com/user-attachments/assets/ef8da605-3da4-4dae-9c8a-6b3ac67e5101


https://github.com/user-attachments/assets/e81f564f-8460-48c0-8885-11637204e6d5

I think we should either make each in-game ColorPicker's presets independent regardless where it comes from (which is my current approach in this PR) or make all ColorPickers use the same data correctly and update presets and pallets in all, when any one of them is modified. Or, to let developers choose the behaviour they want in their game for each ColorPicker.

What do you think?

Comment (KoBeWi) [reply scene/gui/color_picker.cpp]: The reason I think there should be difference is that you can't display 2 ColorPickers from buttons at once, while you can show multiple stand-alone ColorPickers. In the latter case, you may have multiple Swatches visible at once, so it does not make sense to update other ColorPickers (and it's not even feasible). In case of buttons, if you add a color to one picker, the other picker is not visible, so it's easy to sync them when the other button is clicked.

The palettes make it more complicated though. Ideally a Palette should sync across ColorPickers in every case, so if you have multiple ColorPickers visible at once (which again, is only possible with standalone ones), they should update their palette in real time. I think it might be possible by connecting to Palette's `changed` signal.

File: scene/gui/color_picker.cpp [hunk 5]
```diff
@@ -157,9 +157,10 @@ void ColorPicker::_notification(int p_what) {
 				text_type->set_custom_minimum_size(Size2(28 * theme_cache.base_scale, 0));
 			}
 
-			_update_presets();
-			_update_recent_presets();
 			_update_controls();
+			// HACK: Deferring updating presets to fix wrong size of the presset when creating ColorPicker in runtime
```
Comment (KoBeWi) [inline scene/gui/color_picker.cpp]:
```suggestion
			// HACK: Deferring updating presets to fix wrong size of the preset when creating ColorPicker at runtime.
```

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
