### PR TITLE
Fix missing UID handling in Dependency Editor

### LINKED ISSUE #63366: Dependency editor doesn't work after editor restart
### Godot version

v4.0.alpha.custom_build [667cef39b]
Not reproducible on 3.4.4.stable
Not reproducible on 3.5.rc7

### System information

Arch on 5.18.12-arch1-1

### Issue description

Before:
image

After:
image

### Steps to reproduce

1) Make a scene with a dependency
2) Rename the dependency externally
3) Restart the editor
4) Open the scene

### Minimal reproduction project

[empty.zip](https://github.com/godotengine/godot/files/9174624/empty.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #63366
When the scene had UID and path as a dependency, it preferred listing the UID. This can however fail if the UID does not path to any path (not sure if possible normally; it's definitely a problem when copying files between projects).

I made the text loader add path as an optional dependency field and Dependency Editor will use it if UID fails.

### CODE REVIEW

File: scene/resources/resource_format_text.cpp [hunk 1]
```diff
@@ -900,6 +902,9 @@ void ResourceLoaderText::get_dependencies(Ref<FileAccess> p_f, List<String> *p_d
 		if (p_add_types) {
 			path += "::" + type;
 		}
+		if (!fallback_path.is_empty()) {
+			path += "::" + fallback_path;
+		}
```
Comment (akien-mga) [inline scene/resources/resource_format_text.cpp:907]: How will the loader differentiate between `type` and `fallback_path` when reading what comes after `::`, in case both `p_add_types` on/off and non-empty `fallback_path` can happen?

Comment (KoBeWi) [reply scene/resources/resource_format_text.cpp:907]: I guess there is no way to differentiate that 🙃
But given how `fallback_path` is used, it's not a big problem if it's invalid. Maybe I should add more comments about its caveats? It doesn't need to be super robust for now, as it does its job.

**Review by akien-mga — APPROVED** [review]
Tentatively approving, would be good to merge for wider testing (that was the plan originally with postponing it to 4.1, but it went under the radar again...).

Could you rebase for good measure? (And double check if this is still the way you think this bug should be solved.)

**Comment by KoBeWi** [comment]
I actually can't reproduce the bug in beta1. Or more like, there is another bug that covers it. The scene with missing dependency opens with just printing an error in the log. No prompt appears anymore, it just works .-.

File: scene/resources/resource_format_text.cpp (hunk 1 above)
Comment (KoBeWi) [reply scene/resources/resource_format_text.cpp]: Ok I changed it to just add another `::` if `p_add_types` is false, so type and fallback are at fixed positions and can be retrieved reliably.

**Comment by KoBeWi** [comment]
Rebased and made a minor tweak related to the review comment.

**Comment by akien-mga** [comment]
Needs a rebase to fix CI, the doc checks were broken temporarily yesterday by another PR.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
This PR seems to be too risky to include into the stable 4.0 branch at the moment, as it requires further fixes from follow-up PRs and more time dedicated to battle-testing it. We are not going to cherry-pick it, but if there is a strong need to have this fixed in a future 4.0.x release, please make a dedicated PR with all the follow-up fixes applied once it has been tested for at least a few months. Otherwise, we recommend updating to Godot 4.1 if this fix is important to your project.

I'll remove the cherry-pick label.
