### PR TITLE
Fix Android fingerprint scanners being recognized as joypads

### LINKED ISSUE #47656: Gamepad support: Device 0 already taken by fingerprint reader on Android
**Godot version: 3.2.3**

**OS/device:**
Running Godot on Windows 10
Running game on Xiaomi Redmi 9 with Android 10 (MIUI 12 if that's relevant)

**Issue description:**
Expected: Device 0 is nothing or bluetooth joypad that is synced
Result: Device 0 is "uinput-fpc" and if a joypad is synced the joypad is device 1

**Steps to reproduce:**
make Input.get_joy_name(0) readable while running a game on the device

[minimal example.zip](https://github.com/godotengine/godot/files/6261634/minimal.example.zip)

### PR DESCRIPTION
**Pull request by Nintorch**
Fixes https://github.com/godotengine/godot/issues/47656
This PR makes the Android code ignore the fingerprint scanners when they get recognized as joysticks.

<details>
<summary>Tested with a DualShock 4 controller</summary>

Screenshot_2025-12-25-18-17-15-579_org godotengine editor v4 debug
</details>

### CODE REVIEW

File: platform/android/java/lib/src/main/java/org/godotengine/godot/input/GodotInputHandler.java [hunk 1]
```diff
@@ -354,8 +354,7 @@ public void onInputDeviceAdded(int deviceId) {
 		}
 
 		// Device may not be a joystick or gamepad
-		if (!device.supportsSource(InputDevice.SOURCE_GAMEPAD) &&
-				!device.supportsSource(InputDevice.SOURCE_JOYSTICK)) {
+		if ((!device.supportsSource(InputDevice.SOURCE_GAMEPAD) && !device.supportsSource(InputDevice.SOURCE_JOYSTICK)) || device.getName().startsWith("uinput-")) {
```
Comment (Alex2782) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/input/GodotInputHandler.java]: `uinput-` I'm not sure if we should really ignore all devices; what exactly did you see on your devices?

EDIT: Perhaps, just to be on the safe side, ignore these devices to avoid possible regressions.

https://github.com/godotengine/godot/issues/47656#issuecomment-2200489013

```
	"uinput-fpc",
	"uinput-goodix",
	"uinput-synaptics",
	"uinput-elan",
	"uinput-vfs",
	"uinput-atrus",
```

Comment (Nintorch) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/input/GodotInputHandler.java]: On my device I had `uinput-fpc`, and sure, I will change the code to ignore a specific list of devices!

File: platform/android/java/lib/src/main/java/org/godotengine/godot/input/GodotInputHandler.java [hunk 2]
```diff
@@ -359,6 +359,22 @@ public void onInputDeviceAdded(int deviceId) {
...
 
+		String[] joypad_ignore_list = new String[] {
+			// Ignore fingerprint scanners
+			"uinput-fpc",
+			"uinput-goodix",
+			"uinput-synaptics",
+			"uinput-elan",
+			"uinput-vfs",
+			"uinput-atrus",
+		};
```
Comment (m4gr3d) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/input/GodotInputHandler.java]: Let's turn this list into a constant.

File: platform/android/java/lib/src/main/java/org/godotengine/godot/input/GodotInputHandler.java [hunk 3]
```diff
@@ -359,6 +359,22 @@ public void onInputDeviceAdded(int deviceId) {
...
+
+		for (String name : joypad_ignore_list) {
+			if (device.getName().equals(name)) {
+				return;
```
Comment (m4gr3d) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/input/GodotInputHandler.java:375]: Add an `info` logging statement to indicate the device was ignored.

**Comment by Nintorch** [comment]
Thank you for your review, m4gr3d! I will be able to fix the code later today!

**Review by m4gr3d — APPROVED** [review]
The code looks good to me!

**Review by Alex2782 — APPROVED** [review]
Looks good!
