### PR TITLE
Fix put_var encoding some 32bits ints as 64bits.

### LINKED ISSUE #15383: Send signed, 32-bit integer (as variant) over the stream.
**OS/device including version:**
OS X 10.13.x

Client: Godot 3.0.beta.build1
Server: NodeJS v8.9.3

**Issue description:**
Put a Variant into the stream. [Binary serialization](http://docs.godotengine.org/en/latest/learning/features/misc/binary_serialization_api.html#integer)

`streamPeerTCP.put_var(true)`  sends `<Buffer 08 00 00 00 01 00 00 00 01 00 00 00>` - **OK**
`streamPeerTCP.put_var(5)` sends `<Buffer 0c 00 00 00 02 00 01 00 05 00 00 00 00 00 00 00>` - **???**
`streamPeerTCP.put_var(5.5)` sends `<Buffer 08 00 00 00 03 00 00 00 00 00 b0 40>` - **OK**
`streamPeerTCP.put_var("test")` sends `<Buffer 0c 00 00 00 04 00 00 00 04 00 00 00 74 65 73 74>` - **OK**

The part that i think there is something wrong:
<Buffer **_0c_** 00 00 00 02 00 **_01_** 00 05 00 00 00 **_00 00 00 00_**>
I expected to receive something like this:
<Buffer 08 00 00 00 02 00 00 00 05 00 00 00>

Is this a bug, or am I doing something wrong?

**Steps to reproduce:**
```
var streamPeerTCP = StreamPeerTCP.new()
streamPeerTCP.connect_to_host(IP, PORT)
# after connect
streamPeerTCP.put_var(5)
```

### PR DESCRIPTION
**Pull request by Faless**
Fix wrong comparison (+ explicit cast).
Use flags later on in the same function (should save us some cycles :wink:  )

Closes #15383

### CODE REVIEW

**Comment by Faless** [comment]
Test script:

```gdscript
extends SceneTree

const MAX = int(pow(2, 31) - 1)
const MIN = -int(pow(2, 31))
const ZERO = 0
const FIVE = 5

func _init():
	printt(MAX, MIN)
	prints(var2bytes(MAX).size(), 8)
	prints(var2bytes(MAX-1).size(), 8)
	prints(var2bytes(MAX+1).size(), 12)
	prints(var2bytes(MIN).size(), 8)
	prints(var2bytes(MIN+1).size(), 8)
	prints(var2bytes(MIN-1).size(), 12)
	prints(var2bytes(ZERO).size(), 8)
	prints(var2bytes(FIVE).size(), 8)
```

File: core/io/marshalls.cpp [hunk 1]
```diff
@@ -869,7 +869,7 @@ Error encode_variant(const Variant &p_variant, uint8_t *r_buffer, int &r_len, bo
 
 			double d = p_variant;
 			float f = d;
-			if (double(f) != d) {
```
Comment (aaronfranke) [inline core/io/marshalls.cpp]: This will cause a double to be encoded unless the lower 29 bits of the double are all zero. How often is this the case anyway?

(I know this is pre-existing code, you've just changed it to use the above check on line 818, so your change is indeed good, but I'm just wondering if this can be improved further)

Comment (Faless) [reply core/io/marshalls.cpp]: > How often is this the case anyway?

Many Godot functions uses `real_t` (e.g. Vector2/Vector3/almost everything in math/a bunch of stuff in physics).
`real_t` can be defined at compile time as either `float` or `double` (default `float`, can be changed with `REAL_T_IS_DOUBLE` but I never tested it).
So if you encode say `Vector2(1.4,1.3).x` the `x` field will be encoded as float.
eg:
```
prints(var2bytes(.5).size(), 8)
prints(var2bytes(.6).size(), 12)
var v = Vector2(.6, 0)
prints(var2bytes(v.x).size(), 8)
```
The support of this is far from optimal, and there are at least 2 areas where we could do better:
- encoding/decoding Vector directly always encode floats (breaking network transfer when using double `real_t`). We probably want an `encode_real` that enforces the `REAL_T_IS_DOUBLE` directive
- GDScript could support defining floats as `0.6f` (float) beside `0.6` (default to double) which are 2 different values. (@vnen ?)

Comment (vnen) [reply core/io/marshalls.cpp]: I'm not really fond of adding this `double`/`float` distinction to GDScript. Sounds like an unneeded complication. For me it's simpler to always use `double` (everything is stored in a Variant anyway, it wouldn't save space). AFAIK the plan is to move everything to `double` eventually.

Also, I don't think adding this to GDScript would fix the underlying problem of encoding, since you usually do this to engine types that you can't control from scripting (e.g. if Vector2 uses `double` internally, it doesn't matter if the value in the script is a `float` or not, the type will be coerced).

Comment (Faless) [reply core/io/marshalls.cpp]: Yeah, you are probably right, optimizing size in networking is very important, but for good optimization one will almost certainly use `StreamPeerBuffer`. Which has `put_float` and `put_double`.

**Comment by akien-mga** [comment]
Thanks!

**Comment by Xrayez** [comment]
Does this patch breaks compatibility? I tried to load one of my existing custom level from a file which was created before this patch and I got this error during decryption and decompression of the level:
```
E 0:00:02:0937   Condition ' len < 8 ' is true. returned: ERR_INVALID_DATA
  <C Source>     core/io/marshalls.cpp:138 @ decode_variant()
```
I should note that if I create a new level, save it into the file and load it, it seems to work fine... If this is not expected behavior I'll try to isolate the problem and open a new issue in more detail.
