### PR TITLE
Expose selectable property of ItemList's Item and set default to true

### LINKED ISSUE #56570: Can't select ItemList items
### Godot version

393a44b

### System information

W10

### Issue description

I don't know what happened.
godot windows tools 64_3Jz8y4GkDC
Only happens when running project, in editor it's fine. The items emit selected signal, but never actually get selected. Also if you connect the signal and print the selected id, you always get -1 when trying to select with arrows.

### Steps to reproduce

1. Add ItemList
2. Add some items
3. Run
4. Try select

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by jmb462**
Fix #56570

### Issue description

Items added to ``ItemList`` in editor are not selectable by default whereas ``add_item()`` function adds a selectable item.

### Fix proposal
- Set ``selectable`` property default to ``true``, so even if item is not added via ``add_item()`` it will be selectable by default
- Expose this property in editor inspector

image

### CODE REVIEW

File: scene/gui/item_list.cpp [hunk 1]
```diff
@@ -1541,6 +1547,10 @@ void ItemList::_get_property_list(List<PropertyInfo> *p_list) const {
 		pi.usage &= ~(get_item_icon(i).is_null() ? PROPERTY_USAGE_STORAGE : 0);
 		p_list->push_back(pi);
 
+		pi = PropertyInfo(Variant::BOOL, vformat("item_%d/selectable", i));
+		pi.usage &= ~(is_item_selectable(i) ? PROPERTY_USAGE_STORAGE : 0);
```
Comment (akien-mga) [inline scene/gui/item_list.cpp:1551]: Shouldn't this be 
```suggestion
		pi.usage &= ~(!is_item_selectable(i) ? PROPERTY_USAGE_STORAGE : 0);
```
Like for `disabled`?

IIUC this will store the value when `selectable` is enabled (default) and not when disabled. It should be the other way around (store non-default).

Comment (akien-mga) [reply scene/gui/item_list.cpp:1551]: Nevermind I think I misread, this is probably good as is.

Comment (jmb462) [reply scene/gui/item_list.cpp:1551]: In my first try I've done the same as disabled. But it was not working : By default items were selectable but the switch checkbox didn't have any effects at first uncheck. (need to uncheck, check and uncheck).

I though it was because selectable is true by default whereas disabled is false by default so this line need to be inverted.

After changing this line, all was working as expected.

So, are you sure it need to be changed ?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
