### PR TITLE
Fix `TileMapLayer` not respecting physics interpolation mode

### LINKED ISSUE #93237: Disabling physics interpolation on TileMapLayer enables it 4.3.beta1
### Tested versions

4.3.beta1

### System information

Windows 11

### Issue description

While testing I saw some weird behavior with TileMapLayer, it seems disabling physics interpolation enables it, what is more weird the TileMapLayer is not even moving, as it is made visible and invisible

https://github.com/godotengine/godot/assets/12417513/5ac3336d-3c37-4a1b-92d3-c2aee8aa8af2

### Steps to reproduce

Create a project
Enable project wide Physics interpolation
Create a TileMapLayer
Add tileset
Disable TileMapLayer physics interpolation
Try making it visible/invisible

### Minimal reproduction project (MRP)

Project for reproducing: [new-game-project.zip](https://github.com/user-attachments/files/15859138/new-game-project.zip)

### PR DESCRIPTION
**Pull request by rburing**
This makes it respect the initial value.

- Fixes https://github.com/godotengine/godot/issues/93237

### CODE REVIEW

File: scene/2d/tile_map_layer.cpp [hunk 1]
```diff
@@ -301,6 +304,9 @@ void TileMapLayer::_rendering_update(bool p_force_cleanup) {
 					if (prev_ci == RID() || prev_material != mat || prev_z_index != tile_z_index) {
 						// If so, create a new CanvasItem.
 						ci = rs->canvas_item_create();
+						if (!is_physics_interpolated_and_enabled()) {
```
Comment (lawnjelly) [inline scene/2d/tile_map_layer.cpp:307]: Thinking about it, this might be slightly more efficient when interpolation is off globally, i.e. we only need to turn it off in `VisualServer` if global interpolation is on (as this case is dealt with already server side, when globally off).
```
if (is_inside_tree() && get_tree()->is_physics_interpolation_enabled() && !is_physics_interpolated()) {
```
The flip side is that you would have to handle switching physics interpolation on globally on the fly (I don't know if we actually properly handle that at the moment, but if not it would just propagating a change throughout the tree I think).

**Comment by lawnjelly** [comment]
The code you posted for `_physics_interpolated_changed()` looks fine I think, so I would add that.

**Review by lawnjelly — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
