### PR TITLE
Fix collider debug shape didn't changes with collider size changes

### LINKED ISSUE #27134: 'Show Collision Shapes' does not update when CollisionShapes are resized via Animation
**Godot version:** 3.1 stable

**OS/device including version:** Windows 10 64-bit 1809

**Issue description:**

After I checked 'Visible Collision Shapes' in the Debug menu and ran a scene where CollisionShapes are being resized by an Animation, the Visible CollisionShape did not update its size even though the CollisionShape itself had been resized by the animation.

The expected behaviour is that the Visible CollisionShape's size updates when the CollisionShape is resized.

**Steps to reproduce:**
1. Download reproduction project
2. Open 'Explosion.tscn'
3. There is an AnimationPlayer that resizes the Sphere Collider (StaticBody/CollisionShape)
4. Check 'Visible Collision Shapes' in the Debug menu
5. Run scene
6. Observe that Visible CollisionShape does not update its size even though the CollisionShape's radius has been increased (which can be seen as the StaticBody flung the Broken Cube apart, thus the CollisionShape's radius increased

**Minimal reproduction project:**

[upload.zip](https://github.com/godotengine/godot/files/2974232/upload.zip)

### PR DESCRIPTION
**Pull request by Raphael2048**
fix #27134

### CODE REVIEW

File: scene/3d/collision_shape.cpp [hunk 1]
```diff
@@ -199,23 +209,32 @@ CollisionShape::~CollisionShape() {
...
+		add_child(mi);
+		debug_shape = mi;
+	}
+}
 
-	add_child(mi);
-	debug_shape = mi;
+void CollisionShape::_shape_changed() {
+	if (get_tree()->is_debugging_collisions_hint()) {
+		debug_shape_dirty = true;
```
Comment (reduz) [inline scene/3d/collision_shape.cpp]: This does not make much sense and its going to create a ton of call_deferreds. You should exit this function and not do call deferred again if debug_shape_dirty is already true

File: scene/3d/collision_shape.cpp [hunk 2]
```diff
@@ -199,23 +209,32 @@ CollisionShape::~CollisionShape() {
 	//VisualServer::get_singleton()->free(indicator);
 }
 
-void CollisionShape::_create_debug_shape() {
+void CollisionShape::_update_debug_shape() {
+	if (debug_shape_dirty) {
```
Comment (reduz) [inline scene/3d/collision_shape.cpp]: Logic should work so if you get this call it's because it's dirty, so the big if() is not needed.
Put it before in _shape_changed().

**Review by reduz — CHANGES_REQUESTED** [review]

File: scene/3d/collision_shape.cpp (hunk 1 above)
Comment (raphael10241024) [reply scene/3d/collision_shape.cpp]: how should i do to check the dirty param at each frame ? I try to receive NOTIFICATION_PROCESS but it seems not work.

**Comment by raphael10241024** [comment]
has recommited

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
