### PR TITLE
Line edit placeholders now react properly to translation changes.

### LINKED ISSUE #23984: LineEdit placeholder text property doesn't properly take locale into account
**Godot version:**
commit : 11d77386221a4d911edee4fdbba5d3b9109a1c6b

**OS/device including version:**
Kubuntu 18
OpenGL ES 3.0 Renderer: GeForce GTX 1050 Ti/PCIe/SSE2
Nvidia drivers

**Issue description:**
When setting a locale with TranslationServer.set_locale("fr"), the text field of the placeholder of LineEdits is still translated in "en" language only.

**Steps to reproduce:**
1. make a lineedit with something in the text property of the placeholder
2. fill the translation of this text.
3. TranslationServer.set_locale(your_locale)
4. Enjoy

**Minimal reproduction project:**
[demo_translation_problem.zip](https://github.com/godotengine/godot/files/2615119/demo_translation_problem.zip)

you can also see this isue inside the godot editor:
image
--> look at "Filter properties", should be translated in french

Thank you!

### PR DESCRIPTION
**Pull request by flomar**
Line edit placeholders now react properly to translation changes instead of carrying the initial translation defined at application start-up.

Working for me as intended.

*Bugsquad edit:* Fixes #23984.

### CODE REVIEW

File: scene/gui/line_edit.cpp [hunk 1]
```diff
@@ -1669,6 +1679,8 @@ LineEdit::LineEdit() {
 	pass = false;
 	secret_character = "*";
 	text_changed_dirty = false;
+	placeholder = "";
+	placeholder_translated = "";
```
Comment (akien-mga) [inline scene/gui/line_edit.cpp]: Strings are default initialized to `""` (so `String() == ""`), so this is not necessary.

**Comment by akien-mga** [comment]
Judging by the description this should fix #23984, can you confirm?

**Comment by flomar** [comment]
> Judging by the description this should fix #23984, can you confirm?

Yes, I can confirm that the translation of the demo project attached to #23984 is working as intended with the pull request I submitted.

**Review by akien-mga — APPROVED** [review]
Good to merge once the commit is amended as per my previous comment.

**Comment by flomar** [comment]
> Good to merge once the commit is amended as per my previous comment.

Amended as requested.

**Comment by akien-mga** [comment]
Thanks!
