### PR TITLE
Optimize `TileSetAtlasSource::_get_property_list`

### LINKED ISSUE #98213: Godot4 editor performance regressions when removing/moving 2D nodes
### Tested versions

Reproducible in 4.3 stable, 3.5.3 stable works fine

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - integrated Intel(R) Iris(R) Xe Graphics (Intel Corporation; 31.0.101.4887) - 12th Gen Intel(R) Core(TM) i7-1255U (12 Threads)

### Issue description

I have a 430 nodes big scene with a lot of houses that have say 8 tilemaps. This scene works completely fine in Godot3, no lag. I converted the scene to Godot4 and everytime I remove or add a node, I get a 4s lag. If I duplicate a house node (that has many tilemaps) say 40 times and then remove a node, I get significantly prolonged lag. There are no tool scripts. Doing the same thing in the Godot3 editor doesn't result in any noticeable lag.

Why is this relevant?

As a Godot 2D engine developer, I want to be able to create bigger scenes for bigger games productively and not limit my creativity.

Now, I get that there's a limit to the amount of nodes that Godot should support for most devs. Also Godot as an engine doesn't seem to care about performance that much (yet). But throughout versions the performance shouldn't worsen like that imo.

### Steps to reproduce

1. Add big enough nodes to the scene tree, with a lot of tilemaps
2. Duplicate them
3. Add a simple, new node (Node2D is enough)
4. See the freeze duration go up when moving or removing this node in the scene tree the more tilemap container nodes you add.

### Minimal reproduction project (MRP)

[laggyeditorgames.zip](https://github.com/user-attachments/files/17384719/laggyeditorgames.zip)

### PR DESCRIPTION
**Pull request by YYF233333**
Fixes #98213.

`TileSetAtlasSource::_get_property_list` used to call `vformat` a lot with exact same args. Replace pure string formats with string concat and move others to outer loop.

use a slightly modified MRP to make the difference more clear.
[testgame.zip](https://github.com/user-attachments/files/17440344/testgame.zip)

Test Result:
Master:

https://github.com/user-attachments/assets/d0ad79c2-6337-4272-94a2-0ca2a093a905

This PR:

https://github.com/user-attachments/assets/253a9496-f67c-45bb-9fa9-6cfeacf814c5

### CODE REVIEW

File: scene/resources/2d/tile_set.cpp [hunk 1]
```diff
@@ -4931,10 +4931,13 @@ void TileSetAtlasSource::_get_property_list(List<PropertyInfo> *p_list) const {
 		}
 
 		for (const KeyValue<int, TileData *> &E_alternative : E_tile.value.alternatives) {
+			const String formatted_key = vformat("%d", E_alternative.key);
```
Comment (timothyqiu) [inline scene/resources/2d/tile_set.cpp:4934]:
```suggestion
			const String formatted_key = itos(E_alternative.key);
```

Since it's simply `int` to `String`.

File: scene/resources/2d/tile_set.cpp [hunk 2]
```diff
@@ -4943,14 +4946,15 @@ void TileSetAtlasSource::_get_property_list(List<PropertyInfo> *p_list) const {
...
 					alternative_property_info.usage ^= PROPERTY_USAGE_STORAGE;
 				}
-				alternative_property_info.name = vformat("%s/%s", vformat("%d", E_alternative.key), alternative_property_info.name);
+				alternative_property_info.name = alternative_property_info_prefix + alternative_property_info.name;
 				tile_property_list.push_back(alternative_property_info);
 			}
 		}
 
 		// Add all alternative.
+		const String property_info_prefix = vformat("%d:%d", E_tile.key.x, E_tile.key.y) + '/';
```
Comment (timothyqiu) [inline scene/resources/2d/tile_set.cpp:4955]:
```suggestion
		const String property_info_prefix = vformat("%d/%d/", E_tile.key.x, E_tile.key.y);
```

- Copy-paste error.
- Plus `char` is unnecessary since we're already doing `vformat()`.

Comment (YYF233333) [reply scene/resources/2d/tile_set.cpp:4955]: > * Copy-paste error.

I think it should be `%d:%d/%s` with the original code, have I missed something with `vformat`?

Comment (timothyqiu) [reply scene/resources/2d/tile_set.cpp:4955]: Ah yes, I looked at the wrong `vformat()` call.

Comment (timothyqiu) [reply scene/resources/2d/tile_set.cpp]: I mean, it's not a copy-paste error, using `:` is correct.

Comment (YYF233333) [reply scene/resources/2d/tile_set.cpp]: I know, just pull to local and merge these commits, will fix it.

**Review by groud — APPROVED** [review]
LGTM

**Comment by YYF233333** [comment]
Anything blocking this from being merged? Since this is my very first pr if there's something wrong please tell me.

**Review by Repiteo — APPROVED** [review]
Double-checked and nope, everything seems in order!

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first contribution! 🎉
