### PR TITLE
Fix `EditorHelpBitTooltip` in single window mode.

### LINKED ISSUE #105109: [macOS]: EditorHelpBitTooltip hover documentation is not interactable with "Single Window Mode"
### Tested versions

- Reproducible in v4.4 to v4.5.dev.custom_build [a210fe6db]

### System information

Godot v4.5.dev (a210fe6db) - macOS Sequoia (15.4.0) - Single-window, 2 monitors - Metal (Forward+) - integrated Apple M1 Max (Apple7) - Apple M1 Max (10 threads)

### Issue description

When "Single Window Mode" is enabled, the "hover help" tips in macOS cannot be interacted with: documentation links cannot be clicked, and all mouse input passes through to the editor control below.

This seems to be a side-effect of `EditorHelpBitTooltip` setting flag `Window::FLAG_NO_FOCUS` on macOS.  I get get clickable links when building Godot with the line that sets the flag commented out.

If these are intended to require a modifier to click, pressing any modifier (Command, Control, Option, or Shift) while the popups is displayed dismisses the popup immediately on macOS.

### Steps to reproduce

1. In the Script editor, hover over a documented identifier, (e.g. `_ready` in `func _ready() -> void:` to invoke the popup after a short delay.
2. Attempt to click one of the eight links in the popup.

With "Single Window Mode" enabled, this fails.  With "Single Window Mode" disabled, it works as expected.

### Minimal reproduction project (MRP)

I experience this with an empty project.

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/105109

Uses the same logic as other popups.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

File: editor/editor_help.cpp [hunk 1]
```diff
@@ -4555,7 +4555,7 @@ void EditorHelpBitTooltip::popup_under_cursor() {
 	// When `FLAG_POPUP` is false, it prevents the editor from losing focus when displaying the tooltip.
 	// This way, clicks and double-clicks are still available outside the tooltip.
 	set_flag(Window::FLAG_POPUP, false);
-	set_flag(Window::FLAG_NO_FOCUS, true);
+	set_flag(Window::FLAG_NO_FOCUS, !is_embedded());
```
Comment (dalexeev) [inline editor/editor_help.cpp:4558]: I'm a bit late, but still. While this looks like an acceptable workaround, should we eliminate the differences for `FLAG_NO_FOCUS` between native and embedded windows in the future?
