### PR TITLE
Make unsaved scripts in the script editor more user-friendly

### LINKED ISSUE #33313: Deleting a script leaves a blank entry in Script Editor
**Godot version:**
3.2 alpha3

**Steps to reproduce:**
1. Create a script
2. Edit it
3. Delete the file
4. This happens
image

The script is still in memory and when you try to save it, it asks for a filename. Maybe it makes sense, but it should at least show something like "Unsaved script" on the list.

EDIT:
Forgot to mention that this also happens when you move the script, in which case a new script appears on the list, but a copy of the old one remains as blank entry. The old one should be gone.

### PR DESCRIPTION
**Pull request by Xrayez**
Closes #33313.

Annotation 2020-07-24 014226

Unsaved scripts were previously displayed with blank tabs, which are mostly a result of deleted or improperly moved scripts, which is another issue in and of itself: #27635.

This patch makes sure that those kind of scripts are displayed as "[unsaved]" now, and ensures that scripts are removed from the list while deleting scripts from the filesystem dock preventing the unsaved tabs to appear in the first place (a user is already prompted with "no undo" warning while deleting any file).

A user is always prompted to save those "[unsaved]" scripts if they attempt to close them without saving in any case except as described above.

These changes don't seem to re-introduce #40175, as I've modified the "save" condition to allow saving in-memory scripts (have no resource path associated).

This also helps #35211.

### CODE REVIEW

**Comment by Xrayez** [comment]
To make sure there's no blank scripts appear at all, it's possible to update the script tabs on filesystem change, or whenever `_update_script_names()` is called. But built-in scripts which are not yet saved do appear as "unsaved" too, and if a user makes changes to that script and modifies the filesystem in any way, it would be lost, and I haven't found a way to automatically save built-in scripts once they're created, which of course would solve the issue. That's why I went for more conservative approach (only remove scripts which were explicitly requested to be removed, from within Godot editor).

**Comment by Xrayez** [comment]
Figured that the "[unsaved]" message can be encoded directly within `ScriptTextEditor::get_name()`, so that they appear in both script list and when you're prompted to save the file (also adds extra "(*)" as a byproduct):

Annotation 2020-07-24 135239

Annotation 2020-07-24 135218

File: editor/plugins/script_editor_plugin.cpp [hunk 1]
```diff
@@ -3102,6 +3136,7 @@ void ScriptEditor::_bind_methods() {
 	ClassDB::bind_method("_copy_script_path", &ScriptEditor::_copy_script_path);
 
 	ClassDB::bind_method("_get_debug_tooltip", &ScriptEditor::_get_debug_tooltip);
+	ClassDB::bind_method("_file_removed", &ScriptEditor::_file_removed);
```
Comment (akien-mga) [inline editor/plugins/script_editor_plugin.cpp:3139]: It doesn't need a binding since it uses `callable_mp`.

**Review by Paulb23 — CHANGES_REQUESTED** [review]
Code looks good. Need to add the `get_name` and `is_unsaved` changes to `TextEditor` and `VisualScriptEditor`.

**Comment by Xrayez** [comment]
Then it also requires implementing the auto-remove feature in all editors for consistency as well. With the current approach I feel like it's quite hacky, and with #40640 being merged it becomes less of an issue (blank tabs resulting from deleting or moving scripts would no longer generate an error on project startup), so I'm considering removing those and leave that for another PR which could possibly solve that on more global level (but see my failed attempts in #40634)... WDYT?

**Comment by Xrayez** [comment]
What I mean is that, ideally the script/text resource would also have to be removed from the list if you delete the file outside of Godot. Even with this PR, the script/text would only be removed automatically when you use "Remove" from the filesystem dock (which could perhaps be considered a feature anyways?)

I haven't found any signal which could be used to detect external filesystem changes to determine exactly what files are moved/deleted. Ideally I'd like godotengine/godot-proposals#468 to get implemented for this. But if you'd like this to get cherry-picked to 3.2, I can leave those `get_meta` hacks for now.

**Comment by Paulb23** [comment]
Not sure I follow. 

`ScriptTextEditor`, `TextEditor` and `VisualScriptEditor` extend `ScriptEditorBase`, so the changes here already affect all three. 
The PR updates `ScriptTextEditor` to return "[unsaved]" instead of blank, I was suggesting that the "[unsaved]" return needs to be copied to the other two else we'll still get blank `TextEditors` and `VisualScriptEditors`. Unless it's not possible with their resources paths, so it should be limited to `ScriptTextEditor`?

 I'm not worried about deletion outside Godot, that's an entirely different use case.

**Comment by Xrayez** [comment]
I think I just got confused:
```
class VisualScriptEditor : public ScriptEditorBase
class ScriptTextEditor : public ScriptEditorBase
class ScriptEditor : public PanelContainer
class TextEditor : public ScriptEditorBase
```
I'll need to return to this later to make sure we're on the same page, but yeah I just wondered if those deletion hacks are acceptable.

**Comment by Xrayez** [comment]
Yeah sorry for the confusion, the plugin shares the same functionality across editors. To note, all have pretty much the same implementation for `get_name()` currently, except that they reference the edited resource differently (`script` vs `text_file` etc).

It isn't possible to test `TextFile` deletion because those are not recognized by the editor in the first place, but in theory should work (perhaps will work for custom imported text resources).

**Review by Paulb23 — APPROVED** [review]
No worries, needs a rebase after #33760 otherwise LGTM.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
I'll opt against cherry-picking for now as this is non trivial to do. If the enhancements are wanted in `3.2`, a dedicated PR would be OK.
