### PR TITLE
[macOS] Fix driver crash when enabling per-pixel transparency on M1 macs.

### LINKED ISSUE #43951: macOS (Apple Silicon) entire machine crashes upon running project due to per-pixel transparency
**Godot version:**
Godot 3.2.3
Godot 3.2.4 beta 3

**OS/device including version:**
MacBook Pro 2020 w/ Apple M1

**Issue description:**
Entire machine crashes when running a project in GoDot. The same behaviour is exhibited when trying to run an exported application.

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes #43951

I have no idea why, but apparently driver do not like resizing window to (1 x 1), which was done to force redraw.

### CODE REVIEW

File: platform/osx/os_osx.mm [hunk 1]
```diff
@@ -2909,11 +2909,10 @@ static int get_screen_index(NSScreen *screen) {
 			layered_window = false;
 		}
 		[context update];
-		NSRect frame = [window_object frame];
-
 		if (!is_no_window_mode_enabled()) {
-			[window_object setFrame:NSMakeRect(frame.origin.x, frame.origin.y, 1, 1) display:YES];
-			[window_object setFrame:frame display:YES];
+			NSRect frameRect = [window_object frame];
+			[window_object setFrame:NSMakeRect(frameRect.origin.x, frameRect.origin.y, frameRect.size.width + 1, frameRect.size.height) display:NO];
```
Comment (akien-mga) [inline platform/osx/os_osx.mm:2914]: Might be worth adding a comment to clarify the purpose of this call (especially with `width + 1`, which I guess is to enforce a redraw with a different size?).

Comment (bruvzg) [reply platform/osx/os_osx.mm:2916]: Added comment, yes it's resizing window a bit to trigger GL context update.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.1.

**Comment by chrisg32** [comment]
Thanks! Much appreciated!
