### PR TITLE
Expose CameraFeed setters

### LINKED ISSUE #97504: CameraFeed setters are not exposed to GDExtension
### Tested versions

v4.4.dev.custom_build [a0d1ba4a3]

### System information

N/A

### Issue description

Godot class `CameraFeed` does not expose setter methods for GDExtension to implement custom CameraFeed subclasses.

- [`camera_feed.cpp` comment](https://github.com/godotengine/godot/blob/a0d1ba4a3d1760f48ef3297a6299ee3dbc1260e1/servers/camera/camera_feed.cpp#L36) mentioned that setters prefixed with underscore are exposed for the possibility of having feeds through GDExtension
- Generated binding for `CameraFeed` does not contain necessary methods such as `_set_position`, `_set_RGB_img`

### Steps to reproduce

1. Dump extension API with `--dump-extension-api`
2. There are no required setter methods for `CameraFeed` in `extension_api.json`

### Minimal reproduction project (MRP)

Reproduction project is not required

### PR DESCRIPTION
**Pull request by j20001970**
Closes #97504

In Godot 3.x, `CameraFeed` setters like `_set_position`, `_set_RGB_img` are exposed to GDNative for implementing custom camera feeds, but they are no longer visible in GDExtension due to methods starting with underscore being ignored in `extension_api_dump.cpp`

The PR simply removes underscore for these setters, exposing them to end users as the result. I'm not sure if there are better approach.

### CODE REVIEW

File: servers/camera/camera_feed.cpp [hunk 1]
```diff
@@ -33,26 +33,23 @@
...
+	ClassDB::bind_method(D_METHOD("set_position", "position"), &CameraFeed::set_position);
 
 	// Note, for transform some feeds may override what the user sets (such as ARKit)
 	ClassDB::bind_method(D_METHOD("get_transform"), &CameraFeed::get_transform);
 	ClassDB::bind_method(D_METHOD("set_transform", "transform"), &CameraFeed::set_transform);
 
-	ClassDB::bind_method(D_METHOD("_set_RGB_img", "rgb_img"), &CameraFeed::set_RGB_img);
-	ClassDB::bind_method(D_METHOD("_set_YCbCr_img", "ycbcr_img"), &CameraFeed::set_YCbCr_img);
+	ClassDB::bind_method(D_METHOD("set_RGB_img", "rgb_img"), &CameraFeed::set_RGB_img);
+	ClassDB::bind_method(D_METHOD("set_YCbCr_img", "ycbcr_img"), &CameraFeed::set_YCbCr_img);
```
Comment (akien-mga) [inline servers/camera/camera_feed.cpp:52]: Capitalized initialisms in the public API breaks the usual convention, I think we should rename those to lowercase (both the bindings and the C++ methods).

Likewise, we try to avoid abbreviations, so `image` should be spelled out fully.
```suggestion
	ClassDB::bind_method(D_METHOD("set_rgb_image", "rgb_image"), &CameraFeed::set_rgb_image);
	ClassDB::bind_method(D_METHOD("set_ycbcr_image", "ycbcr_image"), &CameraFeed::set_ycbcr_image);
```

**Review by akien-mga — APPROVED** [review]
Looks good to me!

I'll let @BastiaanOlij confirm as he implemented this class.

**Review by BastiaanOlij — APPROVED** [review]
The reasoning these were originally "private" was because we didn't want to expose these methods to normal users. They should only be called internally by the engine.
But that idea is very outdated by now as this indeed hinders their use from gdextension. So I think this change is fine.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
