### PR TITLE
Register and cleanup resource importer singletons in a predictable way

### LINKED ISSUE #80255: Random crash when trying to open a scene
### Godot version

4.2 eb4301b

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Sometimes when trying to open a scene from filesystem dock, the editor will crash. It happened 3 times to me already, but I don't know what exactly causes it.
```
[0] FileSystemDock::_select_file (C:\godot_source\editor\filesystem_dock.cpp:1115)
[1] FileSystemDock::_select_file (C:\godot_source\editor\filesystem_dock.cpp:1115)
[2] FileSystemDock::_tree_activate_file (C:\godot_source\editor\filesystem_dock.cpp:1187)
[3] call_with_variant_args_helper<FileSystemDock> (C:\godot_source\core\variant\binder_common.h:308)
[4] call_with_variant_args<FileSystemDock> (C:\godot_source\core\variant\binder_common.h:418)
[5] CallableCustomMethodPointer<FileSystemDock>::call (C:\godot_source\core\object\callable_method_pointer.h:105)
[6] Callable::callp (C:\godot_source\core\variant\callable.cpp:51)
[7] Object::emit_signalp (C:\godot_source\core\object\object.cpp:1073)
[8] Node::emit_signalp (C:\godot_source\scene\main\node.cpp:3577)
[9] Object::emit_signal<> (C:\godot_source\core\object\object.h:891)
[10] Tree::gui_input (C:\godot_source\scene\gui\tree.cpp:3867)
[11] Control::_call_gui_input (C:\godot_source\scene\gui\control.cpp:1806)
[12] Viewport::_gui_call_input (C:\godot_source\scene\main\viewport.cpp:1565)
[13] Viewport::_gui_input_event (C:\godot_source\scene\main\viewport.cpp:1794)
[14] Viewport::push_input (C:\godot_source\scene\main\viewport.cpp:3129)
[15] Window::_window_input (C:\godot_source\scene\main\window.cpp:1482)
[16] call_with_variant_args_helper<Window,Ref<InputEvent> const &,0> (C:\godot_source\core\variant\binder_common.h:303)
[17] call_with_variant_args<Window,Ref<InputEvent> const &> (C:\godot_source\core\variant\binder_common.h:418)
[18] CallableCustomMethodPointer<Window,Ref<InputEvent> const &>::call (C:\godot_source\core\object\callable_method_pointer.h:105)
[19] Callable::callp (C:\godot_source\core\variant\callable.cpp:51)
[20] DisplayServerWindows::_dispatch_input_event (C:\godot_source\platform\windows\display_server_windows.cpp:2612)
[21] DisplayServerWindows::_dispatch_input_events (C:\godot_source\platform\windows\display_server_windows.cpp:2577)
[22] Input::_parse_input_event_impl (C:\godot_source\core\input\input.cpp:722)
[23] Input::flush_buffered_events (C:\godot_source\core\input\input.cpp:979)
[24] DisplayServerWindows::process_events (C:\godot_source\platform\windows\display_server_windows.cpp:2296)
[25] OS_Windows::run (C:\godot_source\platform\windows\os_windows.cpp:1479)
[26] widechar_main (C:\godot_source\platform\windows\godot_windows.cpp:182)
[27] _main (C:\godot_source\platform\windows\godot_windows.cpp:204)
[28] main (C:\godot_source\platform\windows\godot_windows.cpp:218)
[29] WinMain (C:\godot_source\platform\windows\godot_windows.cpp:232)
[30] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[31] <couldn't map PC to fn name>
```

### Steps to reproduce

1. Open a project
2. Open a scene

I think the scene needs to be opened early enough.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by YuriSizov**
Fixes https://github.com/godotengine/godot/issues/80255. Replaces https://github.com/godotengine/godot/pull/79981.

I think I have an idea of what's happening. We create all importers in `EditorNode`, and we assume those will act as singletons (for some of them which implement the pattern). However, there is a possibility for something else to steal the instance, and then be discarded. In this case it looks like the doc generator does that. It has this bit:

```cpp

if (ClassDB::is_parent_class(name, "ResourceImporter") && name != "EditorImportPlugin" && ClassDB::can_instantiate(name)) {
	import_option = true;
	ResourceImporter *resimp = Object::cast_to<ResourceImporter>(ClassDB::instantiate(name));
	List<ResourceImporter::ImportOption> options;
	resimp->get_import_options("", &options);
	for (int i = 0; i < options.size(); i++) {
		const PropertyInfo &prop = options[i].option;
		properties.push_back(prop);
		import_options_default[prop.name] = options[i].default_value;
	}
	own_properties = properties;
	memdelete(resimp);
}
```

If this code runs after the `EditorNode` constructor, it will assume the place of the singleton, and then it will immediately be destroyed, nulling the reference. My proposed solution to this is to add a flag for the constructor so we explicitly decide which instance is going to be added as the singleton instance. I implemented it for all 3 importers that have singletons. And also made sure we don't leak anything on exit for all of them.

Note that the layered texture importer has the singleton, but it's unused as far as I can see.

----

Due to this being a race condition of sorts, it's hard to reproduce reliably, thus making it harder to validate the fix. But I think the logic is solid. When testing note that the doc generator only runs if you don't have a valid docs cache. So make sure to delete it (`editor_data/cache/editor_doc_cache.res`).

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -6926,7 +6926,7 @@ EditorNode::EditorNode() {
 	{
 		// Register importers at the beginning, so dialogs are created with the right extensions.
 		Ref<ResourceImporterTexture> import_texture;
-		import_texture.instantiate();
+		import_texture = Ref<ResourceImporterTexture>(memnew(ResourceImporterTexture(true)));
```
Comment (akien-mga) [inline editor/editor_node.cpp:6929]: I think this could be just:
```
Ref<ResourceImporterTexture> import_texture = memnew(ResourceImporterTexture(true);
```

Comment (YuriSizov) [reply editor/editor_node.cpp]: I wonder why the other pattern is used throughout the codebase. It seems to be always used when we assign to a pre-existing variable, though sometimes it's used in other situations as well.

If that's the reason, then I guess the idea was to have these lines consistent with others that just to `instantiate()`. Anyway, I've changed that to follow the suggestion.

**Review by akien-mga — APPROVED** [review]
Seems like a good option to solve this.

Would like a check from @RandomShaper but he's currently on holiday, so he can review post merge.

**Comment by akien-mga** [comment]
Thanks!
