### PR TITLE
Change translation remaps of LocalizationEditor when performing file system actions

### LINKED ISSUE #56418: Translation remaps are not updated when moving resources
### Godot version

bc2445d

### System information

W10

### Issue description

When moving files inside Godot, stuff like icon path or main scene etc. is updated to the new path. But in case of translation remaps, it doesn't happen. Nor the original file, nor any of the remaps, get updated.

### Steps to reproduce

1. Go to Project Settings -> Localization -> Remaps
image
2. Add some remaps
3. Move any of the files you just referenced

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by PucklaJ**
Fixes #56418

+ [x] React to moving of files
+ [x] React to moving of folders
+ [x] React to removing of files
  + [x] Show warning when removing file of remaps
  + [x] Display removed state in remap tab
  + [x] Fallback to normal resource when remapped one is missing (May not be trivial)
+ [x] React to removing of folders

This PR does the following things

1. `LocalizationEditor` connects to the `files_moved` signal of the `FileSystemDock` and changes the remaps accordingly.
2. `LocalizationEditor` connects to the `file_removed` signal of the `FileSystemDock` and updates the translations if remaps are affected.

3. Shows a dependency warning if someone tries to delete a translation remap.

4. Falls back to the normal resource if the translation remap does not exist and shows a warning.

### CODE REVIEW

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
This looks very good, great job with it!

File: core/io/resource_loader.cpp [hunk 1]
```diff
@@ -808,6 +808,12 @@ String ResourceLoader::_path_remap(const String &p_path, bool *r_translation_rem
 		if (r_translation_remapped) {
 			*r_translation_remapped = true;
 		}
+
+		// Fallback to p_path if new_path does not exist.
+		if (!FileAccess::exists(new_path)) {
+			WARN_PRINT_ED(vformat("Translation Remap %s does not exist. Falling back to %s", new_path, p_path));
```
Comment (akien-mga) [inline core/io/resource_loader.cpp:814]: Some style suggestions:
```suggestion
			WARN_PRINT(vformat("Translation remap '%s' does not exist. Falling back to '%s'.", new_path, p_path));
```

Also it seems we have no code anywhere in the codebase using the `_ED` variant of the warning/error macros so that seems to indicate that either we need to start using them consistently if they're useful, or remove them if they're not. It's outside the scope of this PR so I'd suggest just using the regular `WARN_PRINT`.

File: editor/dependency_editor.cpp [hunk 2]
```diff
@@ -413,6 +413,45 @@ void DependencyRemoveDialog::_find_all_removed_dependencies(EditorFileSystemDire
...
+			for (int j = 0; j < remap_keys.size(); j++) {
+				PackedStringArray remapped_files = remaps[remap_keys[j]];
+				for (int k = 0; k < remapped_files.size(); k++) {
+					int splitter_pos = remapped_files[k].rfind(":");
+					String res_path = remapped_files[k].substr(0, splitter_pos);
+					if (res_path == path) {
+						String locale_name = remapped_files[k].substr(splitter_pos + 1);
+
+						RemovedDependency dep;
+						dep.file = vformat(TTR("Localization Remap Option of %s for %s"), remap_keys[j], locale_name);
```
Comment (akien-mga) [inline editor/dependency_editor.cpp:443]:
```suggestion
						dep.file = vformat(TTR("Localization remap for path '%s' and locale '%s'."), remap_keys[j], locale_name);
```

File: editor/dependency_editor.cpp [hunk 3]
```diff
@@ -413,6 +413,45 @@ void DependencyRemoveDialog::_find_all_removed_dependencies(EditorFileSystemDire
...
+	for (KeyValue<String, String> &files : all_remove_files) {
+		const String &path = files.key;
+
+		// Look for dependencies in the translation remaps.
+		if (ProjectSettings::get_singleton()->has_setting("internationalization/locale/translation_remaps")) {
+			Dictionary remaps = ProjectSettings::get_singleton()->get("internationalization/locale/translation_remaps");
+
+			if (remaps.has(path)) {
+				RemovedDependency dep;
+				dep.file = TTR("Localization Remap");
```
Comment (akien-mga) [inline editor/dependency_editor.cpp:426]:
```suggestion
				dep.file = TTR("Localization remap");
```

File: editor/localization_editor.cpp [hunk 4]
```diff
@@ -379,6 +380,95 @@ void LocalizationEditor::_update_pot_file_extensions() {
...
+		remaps = ProjectSettings::get_singleton()->get("internationalization/locale/translation_remaps");
+	}
+
+	// Check for the keys.
+	if (remaps.has(p_old_file)) {
+		PackedStringArray remapped_files = remaps[p_old_file];
+		remaps.erase(p_old_file);
+		remaps[p_new_file] = remapped_files;
+		remaps_changed = true;
+		print_verbose(vformat("Changed remap key \"%s\" to \"%s\" due to a moved file", p_old_file, p_new_file));
```
Comment (akien-mga) [inline editor/localization_editor.cpp:403]:
```suggestion
		print_verbose(vformat("Changed remap key \"%s\" to \"%s\" due to a moved file.", p_old_file, p_new_file));
```

File: editor/localization_editor.cpp [hunk 5]
```diff
@@ -379,6 +380,95 @@ void LocalizationEditor::_update_pot_file_extensions() {
...
+			String res_path = remapped_files[j].substr(0, splitter_pos);
+
+			if (res_path == p_old_file) {
+				String locale_name = remapped_files[j].substr(splitter_pos + 1);
+				// Replace the element at that index.
+				remapped_files.insert(j, p_new_file + ":" + locale_name);
+				remapped_files.remove_at(j + 1);
+				remaps_changed = true;
+				remapped_files_updated = true;
+				print_verbose(vformat("Changed remap value \"%s\" to \"%s\" of key \"%s\" due to a moved file", res_path + ":" + locale_name, remapped_files[j], remap_keys[i]));
```
Comment (akien-mga) [inline editor/localization_editor.cpp:423]:
```suggestion
				print_verbose(vformat("Changed remap value \"%s\" to \"%s\" of key \"%s\" due to a moved file.", res_path + ":" + locale_name, remapped_files[j], remap_keys[i]));
```

File: editor/localization_editor.cpp [hunk 6]
```diff
@@ -379,6 +380,95 @@ void LocalizationEditor::_update_pot_file_extensions() {
...
+	if (!remaps_changed) {
+		Array remap_keys = remaps.keys();
+		for (int i = 0; i < remap_keys.size() && !remaps_changed; i++) {
+			PackedStringArray remapped_files = remaps[remap_keys[i]];
+			for (int j = 0; j < remapped_files.size() && !remaps_changed; j++) {
+				int splitter_pos = remapped_files[j].rfind(":");
+				String res_path = remapped_files[j].substr(0, splitter_pos);
+				remaps_changed = p_file == res_path;
+				if (remaps_changed) {
+					print_verbose(vformat("Remap value \"%s\" of key \"%s\" has been removed from the file system", remapped_files[j], remap_keys[i]));
```
Comment (akien-mga) [inline editor/localization_editor.cpp:458]:
```suggestion
					print_verbose(vformat("Remap value \"%s\" of key \"%s\" has been removed from the file system.", remapped_files[j], remap_keys[i]));
```

File: editor/localization_editor.cpp [hunk 7]
```diff
@@ -379,6 +380,95 @@ void LocalizationEditor::_update_pot_file_extensions() {
...
+				}
+			}
+		}
+	} else {
+		print_verbose(vformat("Remap key \"%s\" has been removed from the file system", p_file));
```
Comment (akien-mga) [inline editor/localization_editor.cpp:463]:
```suggestion
		print_verbose(vformat("Remap key \"%s\" has been removed from the file system.", p_file));
```

File: editor/localization_editor.cpp [hunk 8]
```diff
@@ -432,6 +522,13 @@ void LocalizationEditor::update_translations() {
 			t->set_tooltip(0, keys[i]);
 			t->set_metadata(0, keys[i]);
 			t->add_button(0, get_theme_icon(SNAME("Remove"), SNAME("EditorIcons")), 0, false, TTR("Remove"));
+
+			// Display that it has been removed if this is the case.
+			if (!FileAccess::exists(keys[i])) {
+				t->set_text(0, t->get_text(0) + vformat(" (%s)", TTR("Removed")));
+				t->set_tooltip(0, t->get_tooltip(0) + " " + TTR("can not be found"));
```
Comment (akien-mga) [inline editor/localization_editor.cpp:529]:
```suggestion
				t->set_tooltip(0, vformat(TTR("%s can not be found."), t->get_tooltip(0)));
```

File: editor/localization_editor.cpp [hunk 9]
```diff
@@ -454,6 +551,12 @@ void LocalizationEditor::update_translations() {
 					t2->set_editable(1, true);
 					t2->set_metadata(1, path);
 					t2->set_tooltip(1, locale);
+
+					// Display that it has been removed if this is the case.
+					if (!FileAccess::exists(path)) {
+						t2->set_text(0, t2->get_text(0) + vformat(" (%s)", TTR("Removed")));
+						t2->set_tooltip(0, t2->get_tooltip(0) + " " + TTR("can not be found"));
```
Comment (akien-mga) [inline editor/localization_editor.cpp:558]:
```suggestion
						t2->set_tooltip(0, vformat(TTR("%s cannot be found."), t2->get_tooltip(0)));
```

File: core/io/resource_loader.cpp [hunk 10]
```diff
@@ -819,6 +819,12 @@ String ResourceLoader::_path_remap(const String &p_path, bool *r_translation_rem
 		if (r_translation_remapped) {
 			*r_translation_remapped = true;
 		}
+
+		// Fallback to p_path if new_path does not exist.
+		if (!FileAccess::exists(new_path)) {
+			WARN_PRINT(vformat("Translation remap '%s' does not exist. Falling back to '%s'", new_path, p_path));
```
Comment (akien-mga) [inline core/io/resource_loader.cpp:825]: Still missing for at end of sentence.

File: editor/dependency_editor.cpp [hunk 11]
```diff
@@ -417,6 +417,45 @@ void DependencyRemoveDialog::_find_all_removed_dependencies(EditorFileSystemDire
...
+			for (int j = 0; j < remap_keys.size(); j++) {
+				PackedStringArray remapped_files = remaps[remap_keys[j]];
+				for (int k = 0; k < remapped_files.size(); k++) {
+					int splitter_pos = remapped_files[k].rfind(":");
+					String res_path = remapped_files[k].substr(0, splitter_pos);
+					if (res_path == path) {
+						String locale_name = remapped_files[k].substr(splitter_pos + 1);
+
+						RemovedDependency dep;
+						dep.file = vformat(TTR("Localization remap for path '%s' and locale '%s'"), remap_keys[j], locale_name);
```
Comment (akien-mga) [inline editor/dependency_editor.cpp:447]: Missing dot at end of sentence.

File: core/io/resource_loader.cpp (hunk 10 above)
Comment (PucklaMotzer09) [reply core/io/resource_loader.cpp]: My bad. I missed it. Now it's been added.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
