### PR TITLE
Fix `is_valid_float`, `Variant` parser, `Expression` parser, script highlighter, and `TextServer` not handing capital E in scientific notation.

### LINKED ISSUE #102363: Capital "E" in E notation is inconsistently handled
### Tested versions

4.4.beta2

### System information

N/A

### Issue description

In general, "E" is [valid in scientific notation](https://en.wikipedia.org/wiki/Scientific_notation).
`String.is_valid_float()` doesn't consider it valid.
Expression can't handle it either.
`to_float()` can handle it though.

The documentation doesn't say anything about this case; it only mentions the lowercase "e".

### Steps to reproduce

```gdscript
print("2E3".is_valid_float())  # False
print("2E3".to_float())  # 2000.0
```

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/102363

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Seems fine.

I wonder if we should also support uppercase `0x` and `0b` which some of those parsers handle.

**Comment by bruvzg** [comment]
> I wonder if we should also support uppercase 0x and 0b which some of those parsers handle.

C standard seems to allow both upper and lower case, so probably yes.

**Comment by HolonProduction** [comment]
Would make sense to add a test for this, wouldn't it?

**Review by AThousandShips — APPROVED** [review]

**Comment by MewPurPur** [comment]
Should the check be added in syntax_highlighter.cpp too?

**Comment by bruvzg** [comment]
> Should the check be added in syntax_highlighter.cpp too?

Yes, missed it. Will update in a moment.

**Comment by bruvzg** [comment]
> Will update in a moment.

Done, also added few tests.

File: tests/core/string/test_string.h [hunk 1]
```diff
@@ -1885,15 +1885,15 @@ TEST_CASE("[String] Join") {
...
-	for (int i = 0; i < 12; i++) {
+	static const char *data[] = { "-30", "100", "10.1", "10,1", "1e2", "1e-2", "1e2e3", "0xAB", "AB", "Test1", "1Test", "Test*1", "文字", "1E2", "1E-2" };
+	static bool isnum[] = { true, true, true, false, false, false, false, false, false, false, false, false, false, false, false };
+	static bool isint[] = { true, true, false, false, false, false, false, false, false, false, false, false, false, false, false };
+	static bool ishex[] = { true, true, false, false, true, false, true, false, true, false, false, false, false, true, false };
+	static bool ishex_p[] = { false, false, false, false, false, false, false, true, false, false, false, false, false, false, false };
+	static bool isflt[] = { true, true, true, false, true, true, false, false, false, false, false, false, false, true, true };
+	static bool isaid[] = { false, false, false, false, false, false, false, false, true, true, false, false, false, false, false };
+	static bool isuid[] = { false, false, false, false, false, false, false, false, true, true, false, false, true, false, false };
+	for (unsigned int i = 0; i < sizeof(data) / sizeof(data[0]); i++) {
```
Comment (Ivorforce) [inline tests/core/string/test_string.h:1896]: This is not important, but for the future, you can use `std::size(data)` instead of `sizeof(data) / sizeof(data[0])` :)

Comment (bruvzg) [reply tests/core/string/test_string.h:1896]: Isn't it C++20 only thing.

Comment (bruvzg) [reply tests/core/string/test_string.h:1896]: Nop, I was wrong it's C++17 (and compiler support is reasonable) so it can be used. Might good cleanup for ~70 currently used cases of `sizeof / sizeof`.

**Review by MewPurPur — APPROVED** [review]

**Comment by Repiteo** [comment]
Needs a rebase

**Comment by Repiteo** [comment]
Thanks!
