### PR TITLE
Fix x11 boot logo position in fullscreen and in maximized

### LINKED ISSUE #2123: Splashscreen does not scale to fullscreen on Linux
On Linux, the splash screen always shows in size of the viewport, even when the game is started in fullscreen. The rest of the screen is black or filled with GPU artifacts.

On windows it works, is scaled to fullscreen.

### PR DESCRIPTION
**Pull request by santouits**
a) Fixes #2123 
b) Fixes the editor's boot logo that started maximized too.

Please check in your games, and you can also use the godot demo for the window management. Also anyone with many monitors.
Checked only in openbox and xfce.

### CODE REVIEW

**Comment by Noshyaar** [comment]
Works as expected on Antergos x86_64 Cinnamon. 👍

File: platform/x11/os_x11.h [hunk 1]
```diff
@@ -193,6 +193,8 @@ class OS_X11 : public OS_Unix {
 
 	virtual void set_main_loop(MainLoop *p_main_loop);
 
+	void _window_changed(XEvent *xevent);
+	static int _check_window_events(Display *display, XEvent *xevent, char *arg);
```
Comment (karroffel) [inline platform/x11/os_x11.h]: clang-format wants you to put a blank line below here it seems.

File: platform/x11/os_x11.cpp [hunk 2]
```diff
@@ -255,41 +255,13 @@ void OS_X11::initialize(const VideoMode &p_desired, int p_video_driver, int p_au
 
 		visual_server = memnew(VisualServerWrapMT(visual_server, get_render_thread_mode() == RENDER_SEPARATE_THREAD));
 	}
-
-	// borderless fullscreen window mode
-	if (current_videomode.fullscreen) {
```
Comment (akien-mga) [inline platform/x11/os_x11.cpp]: Where did all that code go? Is it no longer relevant?

Comment (santouits) [reply platform/x11/os_x11.cpp]: The same code exists inside the set_window_fullscreen function and I call that instead, minus some legacy alternative code for openbox, which isn't needed anymore as far as I can tell, and wasn't called anyway when you explicitly called set_window_fullscreen in gdscript.

**Comment by hickop** [comment]
Works for me on current master. Using Archlinux with latest Xfce4

**Comment by akien-mga** [comment]
Let's merge and get more Testing in Production™.
