### PR TITLE
Ensure move_and_slide() is consistent between the 2D and 3D versions.

### LINKED ISSUE #24874: move_and_slide and move_and_slide_with_snap return vector with dispoportionate Y component
**Godot version:**
3.1 Beta 1

**OS/device including version:**
Windows 10

**Issue description:**
When a KinematicBody (3D) collides with a too steep slope (one that is not climbable) the returned vector has a Y value too high for the collision, if this vector is applied to the kinematicbody the result is a flying object.

**Steps to reproduce:**
Run the attached project, when colliding to the lowest slope the object goes up.

**Minimal reproduction project:**
[KinematicTest.zip](https://github.com/godotengine/godot/files/2742718/KinematicTest.zip)

### PR DESCRIPTION
**Pull request by madmiraal**
[My analysis](https://github.com/godotengine/godot/issues/24874#issuecomment-557881724) of Issue #24874 highlighted a different problem. Issue #24874 suggested the problem was on the steep slopes, but the real issue is: when not using a `RayShape` and only using a `CapsuleShape`, why does the flawed character controller not launch the player into the air on the more gentle slopes too?

PR #20908 changed the behaviour of the `move_and_slide()` function away from the [original designed behaviour](https://godotengine.org/article/godot-31-will-get-many-improvements-kinematicbody) (and the current behaviour of the `KinematicBody2D`). PR #20908 changed the returned velocity `Vector`'s direction to be perpendicular to the `Vector` passed as the `floor_normal` instead of the normal of the surface collided with when the angle of the surface collided with is less than the `floor_max_angle` (and `stop_on_slope` is set to `true`). However, when the angle of the surface collided with is greater than the `floor_max_angle` (PI/4 by default) i.e. a steep slope (or `stop_on_slope` is set to `false`: the default), it returns a vector perpendicular to the normal of the surface collided with as originally designed. This explains the variant behaviour originally described in #24874, when the `RayShape` wasn't working properly, and the current variant behaviour when only a `CapsuleShape` is used. 

This patch reverts the behaviour to the original designed behaviour and fixes #24874.

### CODE REVIEW

**Comment by akien-mga** [comment]
What about the 2D counterpart which was also added in #20908?

It would be nice if you could amend the commit message to be more explicit about what it does, a partial revert of a previous PR is useful information, but it's not enough. What's interesting from a commit log perspective is what impact this change has on the engine, what it solves, etc.  See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-logs-with-readability-in-mind

**Comment by madmiraal** [comment]
> What about the 2D counterpart which was also added in #20908?

The 2D counterpart has already been reverted as part of #21653.

However, I've done some further digging, and I've noticed the following:
- #21653 had an additional change to fix a stop on slope issue #21595. This additional change was added to the 3D version as part of #27415, but it did not include this change.
- The 2D counterpart also has a fix for #23675 introduced (speculatively) as part of #24046 that uses `Vector2.tangent()`. A fix for a similar issue #28412 was introduced to the 3D counterpart in #30588 that uses `Vector3.slide()`. The 2D counterpart should use the same slide() function.
- Finally, the 2D counterpart uses Transform2D[2] instead of the nicer 3D's nicer Transform.origin. However, this is due to the different implementations of the 2D and 3D Transform classes.

I'll update the 2D version to use the `Vector2.slide()` function, and update the commit message to:
"Ensure move_and_slide() is consistent between the 2D and 3D versions."

**Comment by madmiraal** [comment]
To add to [my list above](https://github.com/godotengine/godot/pull/33864#issuecomment-558209489), the 2D version also includes an update of the floor velocity before multiplying by the time delta, which was added as part of 13a801430bdc, which was never added to the 3D version. I'll add this to the commit as well.

**Comment by madmiraal** [comment]
38e2701 also includes a few minor formatting changes to make the functions look identical and I've updated the commit message to provide details of the changes.

**Comment by AndreaCatania** [comment]
At the time of the implementation I thought that consider the small slopes as flat ground would have make the life easier during the usage of the `move_and_slide` with `stop_on_slope=true`.

Today that I'm not using it, I'm looking at this function from another prospective; I'm not able to say the same as before. So I think that highly depends on the approach that you chose when you use this function.

So, for me is ok merge this PR.

Thanks for the contribution @madmiraal

File: scene/3d/physics_body.cpp [hunk 1]
```diff
@@ -1150,10 +1150,20 @@ Vector3 KinematicBody::move_and_slide(const Vector3 &p_linear_velocity, const Ve
...
+		//this approach makes sure there is less delay between the actual body velocity and the one we saved
+		PhysicsDirectBodyState *bs = PhysicsServer::get_singleton()->body_get_direct_state(on_floor_body);
+		if (bs) {
+			floor_motion = bs->get_linear_velocity();
+		}
+	}
+
 	// Hack in order to work with calling from _process as well as from _physics_process; calling from thread is risky
-	Vector3 motion = (floor_velocity + lv) * (Engine::get_singleton()->is_in_physics_frame() ? get_physics_process_delta_time() : get_process_delta_time());
+	Vector3 motion = (floor_motion + lv) * (Engine::get_singleton()->is_in_physics_frame() ? get_physics_process_delta_time() : get_process_delta_time());
```
Comment (akien-mga) [inline scene/3d/physics_body.cpp]: Here motion refers to a lengths (velocity x time), so using `floor_motion` for this velocity local is confusing.

**Comment by akien-mga** [comment]
Code changes look good, but I'm wary of potential compatibility breakage that would imply existing games made with Godot 3.1.

This needs thorough testing to be sure that it's fine to integrate in 3.2 as is.

File: scene/3d/physics_body.cpp (hunk 1 above)
Comment (madmiraal) [reply scene/3d/physics_body.cpp]: It's the same name that's used in the 2D version. I'll rename them both to `current_floor_velocity`.
I'll also use the opportunity to rename the `lv` and `lv_n` variables to `body_velocity` and `body_velocity_normal`

**Comment by akien-mga** [comment]
Let's get this merged and tested broadly in 3.2 beta 3, and we'll see how it goes :)

Thanks for the thorough review and sync of the 2D and 3D versions!
