### PR TITLE
Sort render list correctly in RD renderers

### LINKED ISSUE #110962: Render_priority no longer working
### Tested versions

reproducible in v4.5-beta1 and later
not reproducible in v4.4-stable and earlier

### System information

Godot v4.5.stable - Criteobuntu 22.04.5 (Cubic 2024-12-09 09:47) 22.04 on X11 - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - integrated Intel(R) UHD Graphics (CML GT2) - Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 threads) - 30.97 GiB memory

### Issue description

When modifying the `render_priority` of materials, it's no longer used to sort materials to display.
It's reproducible with materials from multiple meshes, or with `material_overlay`.
It's reproducible in editor.

### Steps to reproduce

- create multiple mesh (same shape & position)
- add different materials to each mesh
- increase the `render_priority` of one mesh.
- this mesh is not rendered on top of others like expected.

### Minimal reproduction project (MRP)

[render-priority.zip](https://github.com/user-attachments/files/22572410/render-priority.zip)

### PR DESCRIPTION
**Pull request by Kaleb-Reid**
"priority" needs to be the last bits in its key in order to properly determine the order to sort the render list in.

Closes https://github.com/godotengine/godot/issues/110962

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Looks great! Thanks

**Comment by Repiteo** [comment]
Thanks!

**Comment by Repiteo** [comment]
Cherry-picked to 4.5

**Comment by BlueCube3310** [comment]
It looks like this has caused a regression where lightmaps aren't correctly applied to objects anymore

**Comment by clayjohn** [comment]
@BlueCube3310 Which renderer?

File: servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp [hunk 1]
```diff
@@ -841,7 +841,7 @@ void RenderForwardClustered::_fill_instance_data(RenderListType p_render_list, i
 
 		RenderElementInfo &element_info = rl->element_info[p_offset + i];
 
-		element_info.value = uint32_t(surface->sort.sort_key1 & 0xFFF);
+		element_info.value = uint32_t(surface->sort.sort_key2 & 0x0FFF00000000);
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:844]: @BlueCube3310 Actually, I think I know the issue, we probably need to add a bitshift here.

Comment (BlueCube3310) [reply servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:844]: Should be fixed by #111125

**Comment by DarioSamo** [comment]
While I haven't gotten to measuring it, this PR is likely to have caused a performance regression due to the rearrangement of the values.

The reason behind material_id and shader_id being the MSB of the bitfield is that it allows the renderer to sort and group based on being able to avoid rebinding pipelines and materials as much as possible. By inverting their order on the keys, other less significant elements have now been prioritized and the possibilities of batching together compatible draw calls has been reduced.

I'd make a PR myself to fix it, but I'd like to know OP's thoughts first into addressing this. The reason behind the original ordering is that:
- Shaders can be often reused because BaseMaterial3D will assign the same shaders to materials if their configuration is similar, which means only textures must be rebound if groups of draw calls with the same.
- Grouping materials avoids the need to rebind textures.
- Grouping geometry avoids the need to rebind vertex and index buffers.

The other miscellaneous parameters having priority over these IDs are likely to cause inefficient ordering over the criteria I laid out above. If you'd prefer, I can address this ordering on a PR myself while keeping 'priority' as the MSB of the key.

**Comment by Kaleb-Reid** [comment]
@DarioSamo I hadn't really thought of that. I was looking at the pr which changed the order and broke "priority" and assumed that the arrangement was just changed in order to make the bitmask simpler. I guess the fix would be reverting the bitmask changes from this pr + #111125, and then rearranging the "*_id" fields to be the msbs after "priority". If you want to make a pr to fix it, I say go ahead.
