### PR TITLE
Avoid deadlocks in multi-threaded management of the C# script map

### LINKED ISSUE #99128: [Regression] ResourceLoader.LoadThreadedRequest(scenePath) stuck at 0.5, infinite loop.
### Tested versions

NOTReproducible in:
v4.3 stable for Windows

Reprodcible in:
v4.3 stable for MacOs
v4.4.dev4.mono.official [36e6207bb] (Windows and MacOS)

For MacOS and Windows

### System information

Godot v4.4.dev4.mono - Windows 10.0.19045 - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 32.0.15.6094) - AMD Ryzen 7 3700X 8-Core Processor (16 threads)

### Issue description

When using 
```
ResourceLoader.LoadThreadedRequest(scenePath);
```

This happened before and looks like its still happening:
https://github.com/godotengine/godot/issues/92844#issuecomment-2167849384

NOTE:
I'm calling the render server when loading TileSets, but I'm doing a RenderingServer.ForceSync();

I'm getting stuck at 0.5 progress and the progress never changes, maybe a recursive load? Or a race condition, I don't know, my debugger points here:

image

### Steps to reproduce

I'm loading the instance like this:

In MacOS it doesnt work at all it is always stuck (thats why we did the load in the same thread), on windows there is a race condition, so sometimes it works, sometime it doesnt.

```C#
public partial class Main2 : Node2D
{
    public override void _Ready()
    {
        // Construct the path to the scene file
        var scenePath = $"res://main.tscn";

        var error = ResourceLoader.LoadThreadedRequest(scenePath);
        GD.PrintErr($"Loading scene: {scenePath} {error}");
        var percentageReport = new Godot.Collections.Array();

        double percentage;
        ResourceLoader.ThreadLoadStatus loadingStatus;
        do
        {
            loadingStatus = ResourceLoader.LoadThreadedGetStatus(scenePath, percentageReport);
            if (loadingStatus == ResourceLoader.ThreadLoadStatus.Failed)
            {
                GD.PrintErr($"Failed to load scene at path: {scenePath}");
                return;
            }

            percentage = percentageReport[0].As<double>();
            GD.PrintErr($"Loading scene: loading: {loadingStatus} scene: {scenePath} percentage: {percentage} {percentageReport}");
            RenderingServer.ForceSync();
        } while (loadingStatus == ResourceLoader.ThreadLoadStatus.InProgress);

        GD.PrintErr($"Finished loading scene: {scenePath} {loadingStatus} {percentage}");
    }
}
```
            

### Minimal reproduction project (MRP)

[bug-thread.zip](https://github.com/user-attachments/files/17846554/bug-thread.zip)

### LINKED ISSUE #99839: Thread can deadlock when using a worker thread to load a C# script with a generic base class
### Tested versions

- Reproducible in: 4.4dev5

### System information

Godot v4.4.dev5.mono - Windows 10.0.26100 - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 Super with Max-Q Design (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 threads)

### Issue description

Currently, if we use either a worker thread with ResourceLoader::load() or use ResourceLoader::load_threaded_request(), and try to load any resource with a dependency on a script that inherits a generic C# class, we run into a _scriptTypeBiMap.ReadWriteLock deadlock.

This happens in a very specific circumstance:

1. The script and its base hasn't been loaded before, so it's not populated into the BiMap
2. Calling the load from a worker thread will make the ResourceLoader::load() call from inside godot_sharp_internal_script_load to spin up a separate worker thread to load the dependency base script
3. This secondary worker thread will try to get the script from the BiMap unsuccessfully, since it hasn't been populated yet, and will then fall back to creating the script bridge. While doing so, it will try to lock the already locked BiMap ReadWriteLock from when we were loading it's child script

### Steps to reproduce

1. Download the MRP
2. Launch the project with a build of Godot4.4dev5 with the --verbose arg
3. Click the Attempt Repro button several times while looking at the log. 
4. Eventually you should see the load stall at the first generic csharp:// script and not manage to print "Loaded successfully"

### Minimal reproduction project (MRP)

[thread-lock-mrp.zip](https://github.com/user-attachments/files/17961809/thread-lock-mrp.zip)

### PR DESCRIPTION
**Pull request by RandomShaper**
The idea here is that using a read-write locking instead of all-or-nothing reduces the chances of a deadlock.

I'm not sure if this covers every possibility of such, because the interaction between, say, multiple resource loading threads instantiating C# scripts and the .NET module can be complex. All I can say is that this at least stops me from being able to reproduce the issue with the MRP provided.

**Note for reviewers:** Disable whitespace diff as one of the methods has a change of indentation level that makes the patch look more complex than it actually is.

Fixes #99128.
Fixes #99839 (I haven't been able to reproduce the issue with the MRP, even after modifying it to effectively use multiple loader threads; however, it's extremely likely that the issue the reporter found is fixed by this PR).

### CODE REVIEW

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs [hunk 1]
```diff
@@ -465,26 +478,31 @@ internal static unsafe void GetOrCreateScriptBridgeForPath(godot_string* scriptP
...
         {
-            lock (_scriptTypeBiMap.ReadWriteLock)
+            _scriptTypeBiMap.ReadWriteLock.EnterUpgradeableReadLock();
+            try
             {
                 if (_scriptTypeBiMap.TryGetScriptPtr(scriptType, out IntPtr scriptPtr))
                 {
                     // Use existing
                     NativeFuncs.godotsharp_ref_new_from_ref_counted_ptr(out *outScript, scriptPtr);
-                    return;
```
Comment (RandomShaper) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:474]: Note to myself: restore this line.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.types.cs [hunk 2]
```diff
@@ -13,7 +14,7 @@ public static partial class ScriptManagerBridge
 {
     private class ScriptTypeBiMap
     {
-        public readonly object ReadWriteLock = new();
+        public ReaderWriterLockSlim ReadWriteLock = new(LockRecursionPolicy.SupportsRecursion);
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.types.cs:17]: Shouldn't need to remove the `readonly` modifier, since this field is never re-assigned.

```suggestion
        public readonly ReaderWriterLockSlim ReadWriteLock = new(LockRecursionPolicy.SupportsRecursion);
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs [hunk 3]
```diff
@@ -571,89 +603,108 @@ private static unsafe void CreateScriptBridgeForType(Type scriptType, godot_ref*
...
-            IntPtr scriptPtr = outScript->Reference;
+            _scriptTypeBiMap.ReadWriteLock.EnterWriteLock();
+            try
+            {
+                NativeFuncs.godotsharp_internal_new_csharp_script(outScript);
+                IntPtr scriptPtr = outScript->Reference;
 
-            // Caller takes care of locking
-            _scriptTypeBiMap.Add(scriptPtr, scriptType);
+                _scriptTypeBiMap.Add(scriptPtr, scriptType);
```
[the remark this answers is not in the document]
Comment (raulsntos) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:612]: Nevermind, I see now that this is entering the write lock and the locker is entering a read lock.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.types.cs (hunk 2 above)
Comment (RandomShaper) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.types.cs]: Done.

**Review by raulsntos — APPROVED** [review]
Sorry for the delay. As discussed in RC, I believe this PR to be safer than https://github.com/godotengine/godot/pull/99798 and according to the author of the other PR it fixes their issue as well.

This PR changes the locking mechanism from `lock(obj)` to using a `ReaderWriterLockSlim` instance, reducing the chances of a deadlock. The other PR moves `NativeFuncs.godotsharp_internal_reload_registered_script(scriptPtr)` outside the lock, and while this also seems to avoid the deadlock it can cause regressions due to underlocking.  So this PR seems safer.

I was unable to reproduce the linked issue, but the code looks good to me.

**Comment by akien-mga** [comment]
Thanks!

**Comment by conde2** [comment]
This didn't fix the issue in my end, any possibility to reopen the issue? Tested with the same MRP and still getting stuck when loading.
