### PR TITLE
Fix Script metadata usage

### LINKED ISSUE #100154: Deep copy custom resource created in 4.4dev4 or newer throws Parser Error: Class hides a global script class
### Tested versions

- Reproducible in 4.4dev6, 4.3 stable, 4.2.2 stable, 4.0 stable, did not test older version

### System information

Godot v4.4.dev6 - Windows 10.0.22631 - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 32.0.15.6636) - 13th Gen Intel(R) Core(TM) i9-13900H (20 threads)

### Issue description

Deep copying a custom resource ( cust_resource.duplicate(true) ) created in 4.4dev4 or newer results in Parser Error: Class "CustomResource" hides a global script class.

The same project and custom resource instance created in 4.4dev3 or older does not result in the error. Seems to be a regression related to https://github.com/godotengine/godot/issues/72119 fixed in https://github.com/godotengine/godot/pull/71142

### Steps to reproduce

As in MRP:
Create new custom resource with class_name (completely empty class is fine)
Perform a .duplicate(true) on custom resource

### Minimal reproduction project (MRP)

[mrp_resource_duplicate.zip](https://github.com/user-attachments/files/18049452/mrp_resource_duplicate.zip)

### PR DESCRIPTION
**Pull request by adamscott**
_🍾 Happy New Year everyone! 🎉_

This PR makes sure that Scripts set in metadata (namely `metadata/_custom_type_script` since #91341) aren't duplicated  when `Resource::duplicate(true)`.

Fixes #100154

### CODE REVIEW

File: core/object/object.cpp [hunk 1]
```diff
@@ -519,8 +519,14 @@ void Object::get_property_list(List<PropertyInfo> *p_list, bool p_reversed) cons
 	for (const KeyValue<StringName, Variant> &K : metadata) {
 		PropertyInfo pi = PropertyInfo(K.value.get_type(), "metadata/" + K.key.operator String());
 		if (K.value.get_type() == Variant::OBJECT) {
+			Object *obj = K.value;
 			pi.hint = PROPERTY_HINT_RESOURCE_TYPE;
-			pi.hint_string = "Resource";
+			if (obj->is_class("Script")) {
```
Comment (adamscott) [inline core/object/object.cpp:524]: Is it technically possible for `obj` to be `nullptr`?

Comment (fire) [reply core/object/object.cpp:524]: I'd probably add a condition like 
```suggestion
			if (obj && obj->is_class("Script")) {
```

Comment (RandomShaper) [reply core/object/object.cpp:524]: That code will use `Variant::operator Object *` that doesn't validate the `Object` so no nulls would come from a `Variant` of type object, in principle. However, I think it's a valid state for `Variant` to the of type object but pointing to null, so I'm not really sure...

That said, `if (Object::cast_to<Script>(obj))` seems to be a better fit here anyway.

Comment (adamscott) [reply core/object/object.cpp]: @RandomShaper Fixed!

If one of you could approve the PR, it could be nice!

**Review by RandomShaper — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
