### PR TITLE
[Button] Adds theme option to align button text and icon to either largest or current stylebox.

### LINKED ISSUE #92466: Text clipping on the Add Element button in inspector lists when using custom display scale and theme
### Tested versions

v4.3.beta.custom_build [be56cab58]

### System information

Godot v4.3.beta (be56cab58) - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

Add elemen

image

### Steps to reproduce

Set the display scale to 1.5 and make an AudioStreamPlayer with an AudioStreamRandomizer in it

Using the high ppi version of [this theme](https://github.com/passivestar/godot-minimal-theme/releases/tag/1.3.0)

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #92602: 4.3 beta 1 Button theme / content margin
### Tested versions

- Not reproducible in Godot 4.3 dev6
- Reproducible in Godot 4.3 Beta 1

### System information

Godot v4.3.dev6 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 31.0.15.5244) - 13th Gen Intel(R) Core(TM) i7-13650HX (20 Threads)

### Issue description

After updating to Godot 4.3 beta 1 from 4.3 dev 6, I noticed that the content margin in a StyleBoxTexture is not applied.

https://github.com/godotengine/godot/assets/70795945/ec45967f-9101-41c4-b8d5-814a08d4dc9a

https://github.com/godotengine/godot/assets/70795945/31c27d5e-14db-4baf-aa88-17095e31035b

### Steps to reproduce

- Create a button
- Create a new theme
- Assign the styles in StyleBoxTexture
- Modify the "content margin" when the button is pressed

I have prepared an example zip

### Minimal reproduction project (MRP)

[button_theme.zip](https://github.com/user-attachments/files/15517854/button_theme.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Alternative to https://github.com/godotengine/godot/pull/92625

Adds new theme option (disabled for default theme and enabled for the editor theme) to control whether button elements are aligned to largest or current stylebox.

Fixes button issues cause by https://github.com/godotengine/godot/pull/92009 without reintroducing https://github.com/godotengine/godot/pull/92009#issuecomment-2114744369

Fixes https://github.com/godotengine/godot/issues/92602
Fixes https://github.com/godotengine/godot/issues/92466

### CODE REVIEW

File: scene/gui/button.h [hunk 1]
```diff
@@ -75,6 +75,8 @@ class Button : public BaseButton {
 		float style_margin_top = 0;
 		float style_margin_bottom = 0;
 
+		int align_to_largest_stylebox = 0;
```
Comment (KoBeWi) [inline scene/gui/button.h:78]:
```suggestion
		bool align_to_largest_stylebox = false;
```
The cache value can be a bool.

Comment (bruvzg) [reply scene/gui/button.h]: Yes, this seems to work. Updated PR.

I guess other "boolean" theme constants, like `Tree::draw_relationship_lines` and `Tree::draw_guides`, should be changed as well. For 4.4 we should probably allow different theme constant types (I have support drafted in https://github.com/godotengine/godot/pull/87243#issuecomment-1894266187, but it's a breaking change).

Comment (KoBeWi) [reply scene/gui/button.h]: > I guess other "boolean" theme constants, like Tree::draw_relationship_lines and Tree::draw_guides, should be changed as well.

Yeah, we already use bool constants in some classes, but not everywhere.

**Comment by passivestar** [comment]
Tested, hover-pressed buttons look fine, including icons, but this doesn't seem to fix https://github.com/godotengine/godot/issues/92466:

image

**Comment by bruvzg** [comment]
> Tested, hover-pressed buttons look fine, including icons, but this doesn't seem to fix https://github.com/godotengine/godot/issues/92466:

Updated, should fix it as well.

**Comment by passivestar** [comment]
> Updated, should fix it as well.

Works 🙏

File: scene/gui/button.cpp [hunk 2]
```diff
@@ -493,6 +500,21 @@ Size2 Button::get_minimum_size_for_text_and_icon(const String &p_text, Ref<Textu
 		minsize.width = 0;
 	}
 
+	float left_internal_margin_with_h_separation = _internal_margin[SIDE_LEFT];
+	float right_internal_margin_with_h_separation = _internal_margin[SIDE_RIGHT];
+	{ // The width reserved for internal element in derived classes (and h_separation if need).
```
Comment (akien-mga) [inline scene/gui/button.cpp:505]:
```suggestion
	{ // The width reserved for internal element in derived classes (and h_separation if needeed).
```

File: scene/gui/button.cpp [hunk 3]
```diff
@@ -828,6 +850,8 @@ void Button::_bind_methods() {
 
 	BIND_THEME_ITEM(Theme::DATA_TYPE_CONSTANT, Button, h_separation);
 	BIND_THEME_ITEM(Theme::DATA_TYPE_CONSTANT, Button, icon_max_width);
+
```
Comment (KoBeWi) [inline scene/gui/button.cpp:853]:
```suggestion
```

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
