### PR TITLE
[3.x] FTI - Add custom interpolation for wheels

### LINKED ISSUE #72207: Shrinking VehicleWheel when using physics interpolation
### Godot version

3.5.1.stable

### System information

Windows 10, RTX 3070, driver version 528.24, both GLES2 and 3

### Issue description

Physics interpolation causes the child mesh of every wheel to visually shrink. This change is smooth, when the physics FPS is equal to, or a multiple of, the screen's refresh rate. Otherwise, it causes jittering. The shrinking depends on driving speed and physics FPS. Higher speeds generally cause more shrinking. When the vehicle slows down, the wheels return to their normal size. Lower physics FPS also lead to shrinking.

### Steps to reproduce

Play the reproduction project for a few seconds. No user input is needed. Results are inconsistent, even with identical settings. By default, the physics FPS is 60. Changes to it, or to the monitor's refresh rate, should lead to different results. The shrinking should only occur while physics interpolation is turned on.

### Minimal reproduction project

[reproduction.zip](https://github.com/godotengine/godot/files/10523403/reproduction.zip)

### PR DESCRIPTION
**Pull request by lawnjelly**
Now the 3D FTI has been moved to scene side, we have the opportunity to finally fix wheel interpolation to cope with high speed rotation.

Fixes #72207
See https://github.com/godotengine/godot/pull/52846#issuecomment-979811468
See https://github.com/godotengine/godot/pull/52846#issuecomment-980526067

## Description
Uses a somewhat "new" approach of managing the wheel interpolation from the vehicle rather than the wheels. This should be more efficient, and I don't think there should be any downsides. The vehicle is therefore set to the default `physics_interpolation_mode` ON and the wheels OFF, and the vehicle controls the wheels.

## Notes
* Adds bespoke interpolation code to cope with wheels rotating at more than 180 degrees per tick.
* Now handles wrapping of the rotation to prevent float error once `m_rotation` reaches high values.
* Also applicable to 4.x after #104269 is merged.
* Custom wheel interpolation solutions are no longer required in games after this PR.
* Handles `resets` and also vehicles first entering the tree on the frame, where transform must be reset _after_ the first physics tick (which is the first place an xform is available).

_This video is 10tps showing the new wheel interpolation. Texture added to wheels to make it easier to see._

https://github.com/user-attachments/assets/d76168a0-2905-4d3e-9bd2-d91cdd62a17e

## Discussion
This doesn't provide a general solution to the problem of phasing, it is specific to wheels. If we later do decide on a general solution, this solution can easily be replaced.

### CODE REVIEW

**Comment by lawnjelly** [comment]
Sorry about that faffing, I fixed the wheels to wraparound to prevent float error, and had to make some adjustments for the resets to work correctly.

File: scene/3d/vehicle_body.h [hunk 1]
```diff
@@ -40,6 +40,43 @@ class VehicleWheel : public Spatial {
...
+		bool reset_queued = false;
+
+		void rotate(real_t p_delta) {
+			curr_rotation += p_delta;
+			curr_rotation_delta = p_delta;
+
+			// Wrap rotation to prevent float error.
+			double wrapped = Math::fmod(curr_rotation + Math_PI, Math_TAU);
+			if (wrapped < 0)
+				wrapped += Math_TAU;
```
Comment (rburing) [inline scene/3d/vehicle_body.h:69]: There is `Math::fposmod`.

File: scene/3d/vehicle_body.cpp [hunk 2]
```diff
@@ -826,6 +883,79 @@ void VehicleBody::_update_friction(PhysicsDirectBodyState *s) {
...
+		// TODO: consider making the non-FTI path also use global space.
+		for (int i = 0; i < wheels.size(); i++) {
+			VehicleWheel &w = *wheels[i];
+			if (use_fti) {
+				// We use a special trick here to ensure the wheels
+				// are in roughly matching positions BEFORE the first physics tick.
+				// The physics will only supply their world space transform on the tick.
+				// We apply the initial global xform AFTER setting as top level.
+				Transform old_xform = w.get_global_transform();
+				w.set_as_toplevel(true);
```
[the remark this answers is not in the document]
Comment (lawnjelly) [reply scene/3d/vehicle_body.cpp:918]: I didn't think of that .. Hmm, we might be able to use local space when sending to server although it will be a bit more expensive. I'll take a look.

File: scene/3d/vehicle_body.h (hunk 1 above)
Comment (lawnjelly) [reply scene/3d/vehicle_body.h:69]: Wasn't aware of the function, but on looking, that version adds `0.0f` for the sign of zero, which is unnecessary here.

We could add a version of the function that doesn't do that (it seems for gdscript use), but probably for another PR.

**Comment by lawnjelly** [comment]
Although the changes are pretty small to put in local space:
```
void VehicleBody::_update_process_mode() {
	set_process_internal(is_physics_interpolated_and_enabled());
}
```

```
void VehicleBody::_notification(int p_what) {

			Transform xform;
			Transform inv_vehicle_xform = get_global_transform_interpolated().affine_inverse();

			for (int i = 0; i < wheels.size(); i++) {
				VehicleWheel &w = *wheels[i];
				w.fti_data.update_world_xform(xform, f);
				w.set_transform(inv_vehicle_xform * xform);
			}

```

I'm still not absolutely convinced we should change this. The other approach is faster, and I am wondering if we should change if _there is evidence_ that it causes a problem for a user (we are trying to future proof and predict ahead of time user problems, although I do take your point that it is in a sense compat breaking, even there is no standard yet for wheels with FTI).

It's also just as possible for the user to get local space by doing this calculation themselves (multiplying by inverse parent global xform) if they _really_ needed it.

On the other hand if we do change it now, then it makes it more difficult to warrant taking it out at a later stage. :thinking: 

Let me know what you think, I can easily change it back.

File: scene/3d/vehicle_body.cpp [hunk 3]
```diff
@@ -114,6 +116,40 @@ String VehicleWheel::get_configuration_warning() const {
 	return warning;
 }
 
+void VehicleWheel::FTIData::update_world_xform(Transform &r_xform, real_t p_interpolation_fraction) {
+	// Note that when unset (during the first few frames before a physics tick)
+	// the xform has been set to match the tscn file when setting as top level.
```
Comment (rburing) [inline scene/3d/vehicle_body.cpp:121]: Partly outdated comment.

**Review by rburing — APPROVED** [review]

**Comment by lawnjelly** [comment]
I'll update the 4.x PR with the changes.

**Comment by lawnjelly** [comment]
Thanks!
