### PR TITLE
Make hovered tabs be drawn with the unselected's width at minimum

### LINKED ISSUE #81836: TabBar: mouse events crash when tab size changes depending on hover state
### Godot version

4.2 dev 4

### System information

Godot v4.2.dev4 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.3699) - 12th Gen Intel(R) Core(TM) i7-12700KF (20 Threads)

### Issue description

The game crashes entirely with no log/feedback when just moving the mouse from a tab to another when the size between the tabs isn't the same.

It seems to depend on what style is different. Adding margins (mrp) breaks it, so does adding a border, but the skew or shadows don't etc.

### Steps to reproduce

Just move the mouse from one tab to another, moving in/out of the same tab is fine.

https://github.com/godotengine/godot/assets/17103048/a06729dc-4d6a-4bcd-9792-1af289f69411

### Minimal reproduction project

[mrp.zip](https://github.com/godotengine/godot/files/12643956/mrp.zip)

### PR DESCRIPTION
**Pull request by YeldhamDev**
Fixes #81836. Supersedes #82344.

This PR also fixes a small bug I found that makes tabs still be hovered if mouse exits the window.

### CODE REVIEW

File: scene/gui/tab_bar.cpp [hunk 1]
```diff
@@ -1373,7 +1377,8 @@ int TabBar::get_tab_width(int p_idx) const {
 		style = theme_cache.tab_disabled_style;
 	} else if (current == p_idx) {
 		style = theme_cache.tab_selected_style;
-	} else if (hover == p_idx) {
+		// Use the unselected style's width if the hovered one is shorter, to avoid an infinite loop when switching tabs with the mouse.
+	} else if (hover == p_idx and theme_cache.tab_hovered_style->get_minimum_size().width >= theme_cache.tab_unselected_style->get_minimum_size().width) {
```
Comment (AThousandShips) [inline scene/gui/tab_bar.cpp:1381]:
```suggestion
	} else if (hover == p_idx && theme_cache.tab_hovered_style->get_minimum_size().width >= theme_cache.tab_unselected_style->get_minimum_size().width) {
```

File: doc/classes/TabBar.xml [hunk 2]
```diff
@@ -414,6 +414,7 @@
 		</theme_item>
 		<theme_item name="tab_hovered" data_type="style" type="StyleBox">
 			The style of the currently hovered tab. Does not apply to the selected tab.
+			[b]Note:[/b] This style will be drawn with the same width as [theme_item tab_unselected] at minimum. This is done to avoid an infinite loop when hovering between two tabs with the cursor.
```
Comment (YuriSizov) [inline doc/classes/TabBar.xml:417]: I don't think that there needs to be a rationale added to the docs. The note can just state the fact, it's not like the reasoning changes anything for the user who reads it.

File: scene/gui/tab_bar.cpp (hunk 1 above)
Comment (YuriSizov) [reply scene/gui/tab_bar.cpp:1381]: While we're at it, why just width? Can we not use the currently drawn style's entire size and ignore that of the focus style?

Comment (YeldhamDev) [reply scene/gui/tab_bar.cpp:1381]: @AThousandShips GDScript brainrot. :zany_face:

@YuriSizov For one, the height doesn't matter at all. Second, the way tabs are drawn is by passing the style to `_draw_tab()`, and that function isn't aware of the hovering state, so that actually would add more complexity.

File: doc/classes/TabBar.xml (hunk 2 above)
Comment (YeldhamDev) [reply doc/classes/TabBar.xml:417]: I personally think it's good to be thorough here, just in case the user asks: "OK, but why?".

File: scene/gui/tab_bar.cpp (hunk 1 above)
Comment (YuriSizov) [reply scene/gui/tab_bar.cpp]: Okay, I see that the height is controlled through min size, basically, which would indeed make things way too complicated. Well, we'll see if anyone is annoyed by it.

File: doc/classes/TabBar.xml (hunk 2 above)
Comment (YuriSizov) [reply doc/classes/TabBar.xml:417]: We can wait until someone asks that. Besides, it kind of reads like "There is a bug if we don't do this, and we don't have a better solution available".

Comment (YeldhamDev) [reply doc/classes/TabBar.xml:417]: > There is a bug if we don't do this, and we don't have a better solution available.

Probably because that's exactly what this is. :no_mouth:

Comment (YuriSizov) [reply doc/classes/TabBar.xml:417]: Yeah, but putting this into the docs won't save you soul and won't offer you penance 😛

Comment (YeldhamDev) [reply doc/classes/TabBar.xml]: Fine, fine, it has been removed. :man_shrugging:

**Review by YuriSizov — APPROVED** [review]
Looks good to me. I wonder what other UI toolkits do in this case.

There is a small issue with the fact that we still use hover stylebox's margins, so the text alignment shifts. But I think this is fine for now so we fix the crash. Perhaps a bit of refactoring in `TabBar` in the future would make hover behave more like focus to avoid these issues.
image

**Comment by akien-mga** [comment]
Thanks!

**Comment by YeldhamDev** [comment]
@YuriSizov This is less an issue and more of "how it works". The text on tabs aren't draw centered, they just take into account the `content_margin` of the styles, so if you have a hover style that doesn't have margins, this happens.

**Comment by YuriSizov** [comment]
@YeldhamDev I know, but if we are enforcing some styling from another stylebox, we should probably do it consistently and apply margins as well. This shouldn't be an issue for most, of course, since making them different size is pretty user-unfriendly in the first place. Which is why I'm only leaving it as a passing comment. But still, keeping some consistency would be nice.

**Comment by YeldhamDev** [comment]
Remember when I said that `_draw_tab()` is only aware of the style you give it and nothing more, and that changing it for such a corner case would not be worth the extra complexity? :upside_down_face:

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.
