### PR TITLE
Fix reimport by scan parsing dependency paths incorrectly

### LINKED ISSUE #92250: "Can't find file" error messages when reimporting a gltf scene
### Tested versions

v4.3.dev6.official [89850d553]

### System information

Godot v4.3.dev6 - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

Reimporting a gltf file throws a "Can't find file" error message for each texture that it has

https://github.com/godotengine/godot/assets/60579014/b7a8a5be-3021-46f2-bf22-f8b74de88d64

It's possible that it's because textures are getting rewritten, but since all of the files are still there after re-export it shouldn't throw error messages

### Steps to reproduce

Re-export from MRP

### Minimal reproduction project (MRP)

https://drive.proton.me/urls/3RTJBP67YG#kLI0frQNo6Ga

### PR DESCRIPTION
**Pull request by Jordyfel**
Fix #92250
maybe other reimport related issues?

Resource loader's `get_dependencies` returns a string in the format `uid::type::path` (or path::type, or path only), but this code was not taking it into account.

Invalid strings were being passed into the `reimport_files` function. Since that function supports uids, they are now passed when possible.

The `_update_file_icon_path` function had no symptoms because of missing script uids, but would break when they are added.

### CODE REVIEW

File: editor/editor_file_system.cpp [hunk 1]
```diff
@@ -1748,7 +1749,8 @@ String EditorFileSystem::_get_global_script_class(const String &p_type, const St
 void EditorFileSystem::_update_file_icon_path(EditorFileSystemDirectory::FileInfo *file_info) {
 	String icon_path;
 	if (file_info->script_class_icon_path.is_empty() && !file_info->deps.is_empty()) {
-		const String &script_path = file_info->deps[0]; // Assuming the first dependency is a script.
+		const String &script_dep = file_info->deps[0]; // Assuming the first dependency is a script.
+		const String &script_path = script_dep.contains("::") ? script_dep.get_slice("::", 2) : script_dep;
```
Comment (lyuma) [inline editor/editor_file_system.cpp:1753]: Are you sure 2 is the correct slice here? Whenever I encounter subresources, they are of the form `res://some/path::Something_asdf` - I don't think I've ever seen two sets of `::`

My guess is it should be slice 0, just like the other example above.

Would it be able to add a comment with an example of such a `res://` path so I can better understand what is being parsed here?

Comment (Jordyfel) [reply editor/editor_file_system.cpp:1753]: This is not about subresources. Like above, `deps` contains the output of `ResourceLoader*.get_dependencies()`, which is in one of the following formats:
1. `uid::type::path`
2. `path::type` if no uid exists and type not requested,
3. just path if no uid and path not requested.

It could fail in the second case, but when being set type is never requested, so currently case 2 is not happening

Comment (Jordyfel) [reply editor/editor_file_system.cpp:1753]: As for why, I decided to go with path instead of uid, it's because it's used for efsd `find_file`, which can't use uid

Comment (Jordyfel) [reply editor/editor_file_system.cpp:1753]: https://github.com/godotengine/godot/blob/4ab8fb809396fa38ba929fec97cfcb7193f1c44d/scene/resources/resource_format_text.cpp#L886-L899

**Comment by passivestar** [comment]
Tested, this does solve the issue, the error messages are gone, thanks 💙

File: editor/editor_file_system.cpp [hunk 2]
```diff
@@ -724,8 +724,9 @@ bool EditorFileSystem::_update_scan_actions() {
 					//must reimport
 					reimports.push_back(full_path);
 					Vector<String> dependencies = _get_dependencies(full_path);
-					for (const String &dependency_path : dependencies) {
-						if (import_extensions.has(dependency_path.get_extension())) {
+					for (const String &dep : dependencies) {
+						const String &dependency_path = dep.contains("::") ? dep.get_slice("::", 0) : dep;
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:728]: The first part here is UID, not a path.

File: editor/editor_file_system.cpp (hunk 1 above)
Comment (KoBeWi) [reply editor/editor_file_system.cpp:1753]: Pretty sure the format is always `uid::type::path`. If any is omitted, one part will be empty, e.g. `uid::::path`.

File: editor/editor_file_system.cpp (hunk 2 above)
Comment (Jordyfel) [reply editor/editor_file_system.cpp:728]: That was my intention, because the function it ends up in works fine with uids

Comment (Jordyfel) [reply editor/editor_file_system.cpp:728]: https://github.com/godotengine/godot/blob/325081cb487408dee2ba9b6d7ff8eea2086a4d7a/editor/editor_file_system.cpp#L2612-L2630

Comment (KoBeWi) [reply editor/editor_file_system.cpp:728]: Yeah but `import_extensions.has(dep.get_extension())` will always be false, because UID has no extension.

Comment (Jordyfel) [reply editor/editor_file_system.cpp:728]: `get_extension` is called on the original string, which ends with the path, so it works. Thats why the concatenated string got so far down the call stack before.

Maybe we shouldn't rely on it though and just extract the path for it anyway

Comment (KoBeWi) [reply editor/editor_file_system.cpp:728]: > get_extension is called on the original string

Ok I missed that 🙃
It would be clearer if `dependency_path` was used for `get_extension()` though.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
