### PR TITLE
Fix drawing of 2D primitives in OpenGL3 renderer

### LINKED ISSUE #67412: 4.0 GLES3 renderer, CanvasItem `draw_primitive()` does not correctly handle quads
### Godot version

v4.0.beta.custom_build [39534a7ae]

### System information

Windows 10, GLES3, NVIDIA GeForce RTX 3070

### Issue description

While working on https://github.com/godotengine/godot/pull/67374 I found that draw_primitive on the GLES3 renderer is inconsistent in vertex order from Vulkan when the point count is 4. The following code:

```gdscript
extends Node2D

func _draw():
	var points = [Vector2(0, 0), Vector2(64, 0), Vector2(128, 128), Vector2(0, 64)]
	var uvs = [Vector2(0, 0), Vector2(1, 0), Vector2(1, 1), Vector2(0, 1)]
	var colors = [Color(0,0,1), Color(0,1,0), Color(1,0,0), Color(1,1,1)]
		
	draw_primitive(points, colors, uvs)
```

Results in 

(gl_compatibility):
image

(forward_plus):
image

I did some quick looking into the GLES3 renderer code and I think this section is to blame:
https://github.com/godotengine/godot/blob/39534a7aecc4ca4215af67244b23dda09ea339f8/drivers/gles3/rasterizer_canvas_gles3.cpp#L1020-L1029

The `j+1` index into the primitives points results in the second triangle being constructed from the 2nd, 3rd, and 4th points in the primitive, which would explain the shape seen above.

### Steps to reproduce

1. Create new project with either forward+ or mobile
2. Set renderer to 'gl_compatibility'
3. Create a Node2D with above script
4. Run and compare between 'gl_compatibility' and 'forward_plus'

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/67412

Previously the wrong vertices were used when assembling the second triangle of a quad.

In the RD renderer the logic looks a bit different. It loops over only j=1 to j=2. It doesn't need to run j=0 because it is writing over the same array used by the first vertex. In GLES3, since we batch draw calls, the data for all 6 vertices needs to be copied over.

### CODE REVIEW

File: drivers/gles3/rasterizer_canvas_gles3.cpp [hunk 1]
```diff
@@ -1018,12 +1018,13 @@ void RasterizerCanvasGLES3::_record_item_commands(const Item *p_item, const Tran
 					state.instance_data_array[r_index].flags = base_flags | (state.instance_data_array[r_index - 1].flags & (FLAGS_DEFAULT_NORMAL_MAP_USED | FLAGS_DEFAULT_SPECULAR_MAP_USED)); //reset on each command for sanity, keep canvastexture binding config
 
 					for (uint32_t j = 0; j < 3; j++) {
+						int offset = j == 0 ? 0 : 1;
 						//second half of triangle
```
Comment (kleonc) [inline drivers/gles3/rasterizer_canvas_gles3.cpp:1022]:
```suggestion
						// Second triangle of the quad.
```

**Review by kleonc — APPROVED** [review]

File: drivers/gles3/rasterizer_canvas_gles3.cpp (hunk 1 above)
Comment (clayjohn) [reply drivers/gles3/rasterizer_canvas_gles3.cpp]: Thanks for the review, updated!

Comment (kleonc) [reply drivers/gles3/rasterizer_canvas_gles3.cpp]: Good addition about the vertices being used, makes things clearer / `offset` less cryptic. :slightly_smiling_face:

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
