### PR TITLE
Fix a possible race condition on popup close, that might cause multiple deletions of the same list item.

### LINKED ISSUE #59906: Crash on Visual Shader editor - changing float op field.
### Godot version

4.0 dev (479143a)

### System information

popOS! (Ubuntu), RTX2060, Vulkan

### Issue description

Similar to  #59249. Happened when editing fields in float OP value (hard coded input value). 

```
  at: Callable (core/variant/callable.cpp:275)
ERROR: BUG: Unreferenced static string to 0: interface_added
   at: unref (core/string/string_name.cpp:131)
ERROR: Method argument to Callable constructor must be a non-empty string
   at: Callable (core/variant/callable.cpp:275)
ERROR: BUG: Unreferenced static string to 0: button_up
   at: unref (core/string/string_name.cpp:131)
ERROR: Method argument to Callable constructor must be a non-empty string
   at: Callable (core/variant/callable.cpp:275)
ERROR: BUG: Unreferenced static string to 0: settings_changed
   at: unref (core/string/string_name.cpp:131)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.alpha.custom_build (479143ab2a6917bb696568a1daccd9466defd167)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f331afa0520] (??:0)
[2] HashMap<StringName, HashMap<StringName, Color, HashMapHasherDefault, HashMapComparatorDefault<StringName>, (unsigned char)3, (unsigned char)8>, HashMapHasherDefault, HashMapComparatorDefault<StringName>, (unsigned char)3, (unsigned char)8>::getptr(StringName const&) const (??:0)
[3] HashMap<StringName, HashMap<StringName, Color, HashMapHasherDefault, HashMapComparatorDefault<StringName>, (unsigned char)3, (unsigned char)8>, HashMapHasherDefault, HashMapComparatorDefault<StringName>, (unsigned char)3, (unsigned char)8>::has(StringName const&) const (??:0)
[4] Theme::has_color(StringName const&, StringName const&) const (??:0)
[5] Theme::has_theme_item(Theme::DataType, StringName const&, StringName const&) const (??:0)
[6] Color Control::get_theme_item_in_types<Color>(Control*, Window*, Theme::DataType, StringName const&, List<StringName, DefaultAllocator>) (??:0)
[7] Control::get_theme_color(StringName const&, StringName const&) const (??:0)
[8] EditorLog::_add_log_line(EditorLog::LogMessage&, bool) (??:0)
[9] EditorLog::_process_message(String const&, EditorLog::MessageType) (??:0)
[10] EditorLog::add_message(String const&, EditorLog::MessageType) (??:0)
[11] EditorLog::_error_handler(void*, char const*, char const*, int, char const*, char const*, bool, ErrorHandlerType) (??:0)
[12] _err_print_error(char const*, char const*, int, char const*, char const*, bool, ErrorHandlerType) (??:0)
[13] _err_print_error(char const*, char const*, int, String const&, bool, ErrorHandlerType) (??:0)
[14] StringName::unref() (??:0)
[15] StringName::~StringName() (??:0)
[16] HashMap<StringName, Object::SignalData, HashMapHasherDefault, HashMapComparatorDefault<StringName>, (unsigned char)3, (unsigned char)8>::Pair::~Pair() (??:0)
[17] HashMap<StringName, Object::SignalData, HashMapHasherDefault, HashMapComparatorDefault<StringName>, (unsigned char)3, (unsigned char)8>::Element::~Element() (??:0)
[18] void memdelete<HashMap<StringName, Object::SignalData, HashMapHasherDefault, HashMapComparatorDefault<StringName>, (unsigned char)3, (unsigned char)8>::Element>(HashMap<StringName, Object::SignalData, HashMapHasherDefault, HashMapComparatorDefault<StringName>, (unsigned char)3, (unsigned char)8>::Element*) (??:0)
[19] HashMap<StringName, Object::SignalData, HashMapHasherDefault, HashMapComparatorDefault<StringName>, (unsigned char)3, (unsigned char)8>::erase(StringName const&) (??:0)
[20] Object::~Object() (??:0)
[21] RefCounted::~RefCounted() (??:0)
[22] Resource::~Resource() (??:0)
[23] EditorSettings::~EditorSettings() (??:0)
[24] void memdelete<EditorSettings>(EditorSettings*) (??:0)
[25] Ref<EditorSettings>::unref() (??:0)
[26] Ref<EditorSettings>::~Ref() (??:0)
[27] /lib/x86_64-linux-gnu/libc.so.6(+0x454e5) [0x7f331afa34e5] (??:0)
[28] /lib/x86_64-linux-gnu/libc.so.6(on_exit+0) [0x7f331afa3660] (??:0)
[29] /lib/x86_64-linux-gnu/libX11.so.6(+0x44a3b) [0x7f331b349a3b] (??:0)
[30] /lib/x86_64-linux-gnu/libX11.so.6(_XError+0x124) [0x7f331b349b64] (??:0)
[31] /lib/x86_64-linux-gnu/libX11.so.6(+0x44c67) [0x7f331b349c67] (??:0)
[32] /lib/x86_64-linux-gnu/libX11.so.6(_XReply+0x407) [0x7f331b34b797] (??:0)
[33] /lib/x86_64-linux-gnu/libX11.so.6(XGetWindowProperty+0x108) [0x7f331b32a7b8] (??:0)
[34] DisplayServerX11::_window_maximize_check(int, char const*) const (??:0)
[35] DisplayServerX11::window_get_mode(int) const (??:0)
[36] DisplayServerX11::can_any_window_draw() const (??:0)
[37] Main::iteration() (??:0)
[38] OS_LinuxBSD::run() (??:0)
[39] /home/dan/workspace/godot/bin/godot.linuxbsd.tools.64(main+0x178) [0x563c34e1e281] (??:0)
[40] /lib/x86_64-linux-gnu/libc.so.6(+0x29fd0) [0x7f331af87fd0] (??:0)
[41] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d) [0x7f331af8807d] (??:0)
[42] /home/dan/workspace/godot/bin/godot.linuxbsd.tools.64(_start+0x25) [0x563c34e1e045] (??:0)
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

Create visual shader, add multiply OP, play with input fields. 

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by bruvzg**
Depending on how fast OS processes a window close request, the window close event might arrive before the cleanup loop is finished (and delete the list item which is currently processed by the loop, causing invalid memory access).

So instead of removing nested popups directly, cleanup is changed to find the deepest popup to close, and send a close request to this window only, the rest (closing child popups) is handled by this window close event handler.

TODO:
- [x] Test on macOS.
- [x] Test on Windows.
- [x] Test on Linux.

Fixes: #59906

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

File: platform/linuxbsd/display_server_x11.cpp [hunk 1]
```diff
@@ -3208,37 +3208,47 @@ Rect2i DisplayServerX11::window_get_popup_safe_rect(WindowID p_window) const {
...
+	_THREAD_SAFE_METHOD_
+
 	WindowData &wd = windows[p_window];
 	if (wd.is_popup) {
-		// Close all popups, up to current popup parent, or every popup if new window is not transient.
+		// Find current popup parent, or root popup if new window is not transient.
+		List<WindowID>::Element *C = nullptr;
 		List<WindowID>::Element *E = popup_list.back();
 		while (E) {
 			if (wd.transient_parent != E->get() || wd.transient_parent == INVALID_WINDOW_ID) {
```
Comment (Anutrix) [inline platform/linuxbsd/display_server_x11.cpp:3219]: A bit late comment but
Is there any reason why we have `if-else` block inside the while loop instead of just a simple while loop with combined condition?
