### PR TITLE
Fix typed array export

### LINKED ISSUE #74050: Setting exported node properties from the inspector bypasses their setter
### Godot version

v4.0.alpha11.official [afdae67cc] (when the feature was added) and newer (still happens in RC6)

### System information

Windows 10

### Issue description

I'm unable to handle when the user sets an exported node property (this feature: https://github.com/godotengine/godot/pull/62185) from a setter in the editor (tool script).

I don't know if this is intentional or not, but for me it was unexpected. I had to revert back to `NodePath`s.

### Steps to reproduce

- Create a scene
- Attach a script to a node
- Add `@tool` at the top of the script
- Export a node property with a setter, preferably with an easy way to see if it executed:
	```
	@export var node:Node:
		set (mod_value):
			prints("node", mod_value)
			node = mod_value
	```
- Save, close and open again the scene to make sure the tool script is running in the editor
- Set the node property from the inspector
- Observe that the setter didn't run

The setter is not bypassed when running the game, it is only bypassed in the editor.

We can compare with a `NodePath` property, which setter is not bypassed regardless if it is in the editor or in game runtime.

### Minimal reproduction project

[nodepath.zip](https://github.com/godotengine/godot/files/10840411/nodepath.zip)

### LINKED ISSUE #74141: Exported Nodes are Nil in `@tool` mode
### Godot version

4.0-rc6

### System information

Fedora 37, Mesa Intel ADL GT2

### Issue description

Code that works as expected at runtime fails with Nil references to (assigned) exported vars in the editor:

tool_global_position_error

### Steps to reproduce

Try to access the `global_position` of a `Node3D` that's assigned to an exported var.

See that it works at runtime.

See that it errors in the editor with:

> Invalid get index 'global_position' (on base: 'Nil').

### Minimal reproduction project

[tool_test.zip](https://github.com/godotengine/godot/files/10856640/tool_test.zip)

### LINKED ISSUE #75981: NodePaths display incorrectly in the inspector arrays
### Godot version

4.0.2

### System information

Windows 10 x64

### Issue description

image
Both paths point to the same node, but the second one appears as if the node wasn't found. I assume this is because the NodePaths in array don't have the scene's node as "parent", so the path can't be resolved properly.

### Steps to reproduce

1.
```GDScript
@export var np1: NodePath
@export var np2: Array[NodePath]
```
2. Assign the same node
3. Compare the results

### Minimal reproduction project

N/A

### LINKED ISSUE #76642: Typed arrays exported from tool scripts cannot be edited
### Godot version

9f12e7b52d944

### System information

arch linux

### Issue description

Attempting to edit from the editor a typed array exported from a tool script fails, any value is immediately reset, setters are never called.

### Steps to reproduce

Create a script such as follows and try to add and then change items of the array in the inspector.

```gdscript
@tool
extends Node

@export var x: Array[String]
```

### Minimal reproduction project

n/a

### PR DESCRIPTION
**Pull request by ajreckof**
Fixes my mess from #76114
Fixes #75981 (as a side effect, if this PR is not accepted i could easily extract the fix from it)
Fixes also the bug i found and reported here : https://github.com/godotengine/godot/pull/76378#issuecomment-1519184710
Edit : those two bugs are related to the one just above and should be fixed with this PR #74141 #74050

This PR remove the hack with pointer and replace it with a proper handling from `EditorPropertyNodePath` of both `NodePath` and `Node`. Also needed to revise a bit the saving and loading of scene to handle properly the change.

PS: This is not polished and still needs testing

*Bugsquad edit:* Fixes #76642 Fixes #74141 Fixes #74050

### CODE REVIEW

**Comment by Chaosus** [comment]
Please amend the commit name - no need to excuse in the title, while you can do that in the PR description. 😸

**Comment by KoBeWi** [comment]
Needs rebase.

**Comment by KoBeWi** [comment]
While testing another PR, I accidentally discovered that this PR breaks ViewportTexture. When you re-assign the viewport, the path will be relative to the node with texture instead of root node.

File: editor/editor_properties.cpp [hunk 1]
```diff
@@ -3701,6 +3677,36 @@ void EditorPropertyNodePath::_notification(int p_what) {
...
+		}
+	}
+
+	base_node = Object::cast_to<Node>(get_edited_object());
+
+	if (!base_node) {
+		base_node = Object::cast_to<Node>(InspectorDock::get_inspector_singleton()->get_edited_object());
+	}
+	if (!base_node) {
+		//try a base node within history
```
Comment (KoBeWi) [inline editor/editor_properties.cpp:3694]:
```suggestion
		// Try a base node within history.
```

File: editor/editor_properties.cpp [hunk 2]
```diff
@@ -3701,6 +3677,36 @@ void EditorPropertyNodePath::_notification(int p_what) {
 
 void EditorPropertyNodePath::_bind_methods() {
 }
+Node *EditorPropertyNodePath::get_base_node() {
+	Node *base_node = nullptr;
+	if (base_hint != NodePath()) {
+		if (get_tree()->get_root()->has_node(base_hint)) {
```
Comment (KoBeWi) [inline editor/editor_properties.cpp:3683]: Can be merged into 1 condition.
```suggestion
	if (!base_hint.is_empty() && get_tree()->get_root()->has_node(base_hint)) {
```

**Review by KoBeWi — APPROVED** [review]
I tested and it fixes many issues with exported nodes and arrays.

The PR changes how exported nodes work (not only arrays), so needs a check from @reduz who implemented it originally.

File: editor/editor_properties.h [hunk 3]
```diff
@@ -781,20 +781,19 @@ class EditorPropertyNodePath : public EditorProperty {
...
 	void _node_clear();
+	Node *get_base_node();
 
 	bool can_drop_data_fw(const Point2 &p_point, const Variant &p_data, Control *p_from) const;
 	void drop_data_fw(const Point2 &p_point, const Variant &p_data, Control *p_from);
 	bool is_drop_valid(const Dictionary &p_drag_data) const;
 
-	String _get_meta_pointer_property() const;
 	virtual Variant _get_cache_value(const StringName &p_prop, bool &r_valid) const override;
-	virtual StringName _get_revert_property() const override;
```
Comment (ajreckof) [inline editor/editor_properties.h:797]: Just realised while working on something else that what I was doing previously of returning `get_edited_property` is in fact the non-overriden behaviour so I just removed the whole overriding. Moreover I think this was the only place where this function was overriden so I'm wondering wether we should remove it to use `get_edited_property` everywhere it is used instead?

Comment (ajreckof) [reply editor/editor_properties.h:797]: I'm also wondering if we could remove the overriding of `_get_cache_value` but I'm not sure at 100% why there is a check for `p_prop == get_edited_property` but I think it was to update the cache when the property was being changed between pointer mode or not.

File: editor/editor_properties.cpp [hunk 4]
```diff
@@ -3701,6 +3673,35 @@ void EditorPropertyNodePath::_notification(int p_what) {
 
 void EditorPropertyNodePath::_bind_methods() {
 }
+Node *EditorPropertyNodePath::get_base_node() {
```
Comment (YuriSizov) [inline editor/editor_properties.cpp:3676]: Missing a new line, but also this method should be somewhere above, among other similar methods.

**Review by YuriSizov — APPROVED** [review]
I would like @reduz to take a look, but with editor part tested and core changes looking fine I think it's okay to merge for now and get him to confirm changes later. There aren't any public-facing changes or incompatibilities with existing scenes, so we can even revert this PR if there are major issues.

My note still needs to be addressed though.

File: editor/editor_properties.cpp (hunk 4 above)
Comment (akien-mga) [reply editor/editor_properties.cpp:3676]: Did the change so we can merge this now.

**Comment by akien-mga** [comment]
Thanks!

File: editor/editor_properties.cpp (hunk 4 above)
Comment (YuriSizov) [reply editor/editor_properties.cpp:3676]: I don't see any changes 👀

Comment (akien-mga) [reply editor/editor_properties.cpp:3676]: Welp, seems like I forgot to force push?

**Comment by ajreckof** [comment]
If this is cherry picked. #78300 should be cherry-picked at the same time.

**Comment by YuriSizov** [comment]
Actually, no, this won't be cherry-picked. See https://github.com/godotengine/godot/pull/76378#issuecomment-1594812425.
