### PR TITLE
Prevent escape key from closing Editor Settings window when filtering for shortcuts

### LINKED ISSUE #85688: When listening for an input in the Editor Settings -> Shortcuts menu, the escape key will close the menu.
### Godot version

4.2

### System information

Windows 11

### Issue description

Title.

I don't believe this should be the desired behavior. It should search for shortcuts using the escape key, and key the menu open.

### Steps to reproduce

Press escape in the 'Listening for Input...' box.

image

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by ryevdokimov**
Fixes: #85688

Escape key previously closed the window when listening for a key, and escape is pressed. 

image

Now it doesn't, matching the behavior of   "Event Configuration" window. 

image

### CODE REVIEW

File: editor/editor_settings_dialog.cpp [hunk 1]
```diff
@@ -772,6 +780,8 @@ EditorSettingsDialog::EditorSettingsDialog() {
 	shortcut_search_by_event->set_stretch_ratio(0.75);
 	shortcut_search_by_event->set_allowed_input_types(INPUT_KEY);
 	shortcut_search_by_event->connect("event_changed", callable_mp(this, &EditorSettingsDialog::_filter_shortcuts_by_event));
+	shortcut_search_by_event->connect("focus_entered", callable_mp(this, &EditorSettingsDialog::_on_listen_focus_changed));
```
Comment (AThousandShips) [inline editor/editor_settings_dialog.cpp:783]:
```suggestion
	shortcut_search_by_event->connect("focus_entered", callable_mp((AcceptDialog *)this, &AcceptDialog::set_close_on_escape).bind(false));
```
And same below but with `true` and remove the other method

Comment (ryevdokimov) [reply editor/editor_settings_dialog.cpp]: Makes sense.

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` https://github.com/godotengine/godot/commit/9adb7c7d130c6d4eb0e80b92d6eebd71fac3384d), it works as expected.

**Comment by akien-mga** [comment]
Thanks!
