### PR TITLE
Check that motion is not zero before doing a sweep test.

### LINKED ISSUE #25476: move_and_slide crashes with zero vector
**Godot version:**
3.1

**OS/device including version:**
Windows - 1080TI

**Issue description:**
The `move_and_slide` function will crash the game if a "zero" vector is passed into it. It should throw a warning when such a value is passed rather than kill the process.

I managed to fix the issue by using `if vec.length() < 0.00001: move_and_slide(...)`. After doing some research, the bullet library will crash the client upon normalising a vector that has a "zero" value (the length being less than the epsilon they provide). I can safeguard our software by checking the vector length but feel this should be done elsewhere.

**Steps to reproduce:**
`move_and_slide(Vector3(), Vector3(0,1,0))`

### PR DESCRIPTION
**Pull request by madmiraal**
Fixes #25476.

Bullet uses a normal of the motion to create a direction vector when doing a Broad Phase Convex Sweep Test during collision testing:
https://github.com/godotengine/godot/blob/8eb183aebb9c79ff92d6f566af7ad2f91696ce08/thirdparty/bullet/BulletCollision/CollisionDispatch/btCollisionWorld.cpp#L1040-L1041
As can be seen in the comment below the call, they acknowledge it may result in a division by zero, but they haven't addressed it; so we need to.

The check in `space_bullet.cpp` matches Bullet's fuzzyZero() check:
https://github.com/godotengine/godot/blob/8eb183aebb9c79ff92d6f566af7ad2f91696ce08/thirdparty/bullet/LinearMath/btVector3.h#L688-L691
Issue #25476 was caused by Bullet ensuring the length is not zero before dividing when a vector is normalized():
https://github.com/godotengine/godot/blob/8eb183aebb9c79ff92d6f566af7ad2f91696ce08/thirdparty/bullet/LinearMath/btVector3.h#L303-L305

### CODE REVIEW

File: modules/bullet/space_bullet.cpp [hunk 1]
```diff
@@ -945,8 +945,8 @@ bool SpaceBullet::test_body_motion(RigidBodyBullet *p_body, const Transform &p_f
 
 	btVector3 motion;
 	G_TO_B(p_motion, motion);
-
-	{ /// phase two - sweep test, from a secure position without margin
+	if (motion.length2() > SIMD_EPSILON * SIMD_EPSILON) {
```
Comment (akien-mga) [inline modules/bullet/space_bullet.cpp]: Why not use `!motion.fuzzyZero()` directly?

Comment (madmiraal) [reply modules/bullet/space_bullet.cpp]: I've updated it.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AndreaCatania** [comment]
It's necessary add this check here too: https://github.com/godotengine/godot/blob/e447f5ab044c7b0cbc99d61da34afa9f5e15b349/modules/bullet/space_bullet.cpp#L154-L179

**Comment by madmiraal** [comment]
@AndreaCatania
I've created PR #34219 to address the other use of `convexSweepTest()`.

**Comment by madmiraal** [comment]
I've just realised that `test_body_motion` has a loop that modifies `motion`:
https://github.com/godotengine/godot/blob/2ebc783e9c7c257bb122f8a19e2426193a481aa4/modules/bullet/space_bullet.cpp#L994
So we need to check that motion is not zero before each iteration too.
