### PR TITLE
Fix instanced .blend/GLTF scenes lose all children after update until .tscn is reopened

### LINKED ISSUE #94056: Instanced .blend/GLTF scenes lose all children after update until .tscn is reopened
### Tested versions

- Reproducible in: v4.3.beta2.official [b75f048]
- Reproducible in: v4.3.beta.custom_build [e57312d]
- Not reproducible in: v4.3.beta.custom_build [1e6b11d]
- Not reproducible in: v4.2.dev.custom_build [524e7ac]
- Not reproducible in: v4.2.2.stable.official [15073af]

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 32.0.15.5599) - Intel(R) Core(TM) i9-14900K (32 Threads)

### Issue description

When making modifications to a .blend file, I noticed that upon reimport any child nodes that were previously there disappear until the scene is reloaded.   From a cursory glance I believe the issue has to do with [editor_node.cpp:6025 ](https://github.com/godotengine/godot/blob/42e5b3ac2da07d2105c775977b39e6949c723ded/editor/editor_node.cpp#L6025) where the addition_list is empty

### Steps to reproduce

Create new project
Instantiate an imported .blend scene
add a child node to it
save scene
modify the .blend file (anything to trigger re-import)
observe missing child node
close and re-open the scene
observe missing child node reappears.

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/user-attachments/files/16121065/MRP.zip)

### PR DESCRIPTION
**Pull request by yahkr**
closes #94056 

When making modifications to a .blend file that has been instantiated into the scene, upon re import any child nodes that were previously there disappear until the scene is reloaded.

removing this condition fixes the issue:
https://github.com/godotengine/godot/blob/e57312d84eecb7672973a36c0938ed52a3b15474/editor/editor_node.cpp#L4345

### CODE REVIEW

**Review by SaracenOne — APPROVED** [review]
Looking over this, I think this is an okay fix. I can only assume the checks here were an artefact of an early iteration of the system and that this bug occured due to testing mainly with nodes parented to editable children.

**Comment by Hilderin** [comment]
I tested this PR and it seems to work nicely.

I just found a little side-effect and I think that why the condition on the ownership was there. If the child added is another scene with child, I get the error: `Invalid owner. Owner must be an ancestor in the tree.` when reimporting the .blend file.

image

image


There is a simple modified version of the MRP:
[test-godot-blender-reimport-missing-node.zip](https://github.com/user-attachments/files/16144191/test-godot-blender-reimport-missing-node.zip)

**Comment by Yahkub-R** [comment]
> I tested this PR and it seems to work nicely.
> 
> I just found a little side-effect and I think that why the condition on the ownership was there. If the child added is another scene with child, I get the error: `Invalid owner. Owner must be an ancestor in the tree.` when reimporting the .blend file.


Modifying the original condition to the following fixes this issue, however it just pushes the issue down.
```c++
if (p_node->get_owner() != nullptr && p_node->get_owner() == p_edited_scene) {
```
image

if you add a child to CSGBox3D I'm seeing the same error, will continue to dig, it appears the parent of the additive node isnt being set properly.

**Comment by Yahkub-R** [comment]
Ok, i believe I found the issue, it has to do with the ownership_table.  Please correct me if there is something I'm missing.

https://github.com/godotengine/godot/blob/e57312d84eecb7672973a36c0938ed52a3b15474/editor/editor_node.cpp#L4361-L4368
This will add any and all children of the node. However, now that we are not skipping  "p_node->get_parent()->get_owner() != p_edited_scene"  it attempts to process the children of instantiated scenes.  in doing so it populates some ownership_tables with NULL values for parent/owner, which then breaks 
https://github.com/godotengine/godot/blob/e57312d84eecb7672973a36c0938ed52a3b15474/editor/editor_node.cpp#L6002-L6012

So far in my testing removing these sections has not caused any other side effects, but would love another opinion/review.

New MRP:
[94093-fix-3.zip](https://github.com/user-attachments/files/16146756/94093-fix-3.zip)

**Comment by Hilderin** [comment]
Seriously good job! I tested with a lot of different situation and your last modifications seems to work perfectly. Effectively, changing owner should not be required since moving object in the scene does not change the owner anyway.

I tested these situations:
- Added node in Godot to Blender object
- Multiple levels of added nodes
- Multiple levels on nodes from Blender with added nodes in Godot
- Moving nodes in Blender
- Modified properties on Blender objects
- Modified properties on added Godot objects
- Signals on Blender objects
- Reference to an Blender object in a script on an added Node
- Reference to an Blender object in a script on an added Blender object
- Reference to an child of an added Scene in a script on an added Blender object

image

**Comment by SaracenOne** [comment]
Also, it is possible that the ownership tracking might be an artefact of a more naive earlier implementation, but I'm a little skeptical that this wouldn't break something else. I would recommend testing reloading inherited scenes, since was an area I remember struggling to get behaving correctly.

**Comment by Yahkub-R** [comment]
> Also, it is possible that the ownership tracking might be an artefact of a more naive earlier implementation, but I'm a little skeptical that this wouldn't break something else. I would recommend testing reloading inherited scenes, since was an area I remember struggling to get behaving correctly.

Yup, inherited totally broken until the scene is reloaded. Will tinker with that today.

**Comment by Yahkub-R** [comment]
To add to the oddities, the blend updates dont always work when an inherited scene and it's base scene are open and you update a .blend.
```
Steps to recreate:
1. Opening simple_base.tscn, 
2. updating .blend works fine, 
3. while thats open, open simple_inherited
4. update blend again
5. see blend_child vanish in simple_inherited
6. go back to simple_base.tscn
7. update blend and see no change 😠
```

This appears only an issue when the .blend is instanced inside an **inherited** scene. as I tried the same process with simple_base.tscn and complex.tscn.  Updating blend and switching back and forth works perfectly fine.

[94093-fix-4.zip](https://github.com/user-attachments/files/16165359/94093-fix-4.zip)

**Comment by Hilderin** [comment]
I'll look into your last MRP, maybe together we can find a miracle solution :)

**Comment by Hilderin** [comment]
Wow, ok, there are weird things about ownership I did not known about.
Added nodes in base scene have the inherited scene as owner.
image

That cause problem in `update_reimported_diff_data_for_node` because `node_part_of_subscene` is set to true causing the node to never be added in `p_addition_list`.



I changed this condition and now the children "blend_child" is ok when reloading the scene:
```cpp
bool node_part_of_subscene = p_node != p_edited_scene &&
		p_edited_scene->get_scene_inherited_state().is_valid() &&
		p_edited_scene->get_scene_inherited_state()->find_node_by_path(p_edited_scene->get_path_to(p_node)) >= 0 &&
		p_node->get_owner() != p_edited_scene;
```

I publish a branch for you to see my modifications:
https://github.com/godotengine/godot/commit/1fcb52c7afc04891eddb4edaa4f2493b48d4c560

**Comment by Yahkub-R** [comment]
Awesome!  I did stumble across that change to node_part_of_subscene, but was too focused on the lack of updating to notice blend_child didn't vanish. So one problem down, one to go.  It's almost like the instantiated node gets de-referenced and thus doesn't get updated. 

I suspect this has to do with an instance of it being in the inherited scene and getting its owner or some other property updated (which affects the base scene for some reason) and so it no longer receives the signal to update? just a theory.

**Comment by Hilderin** [comment]
The screenshot was taken before the reload. I'll now focus on the problem of scene not reloading. I don't known where it could come from at this moment.

**Comment by Hilderin** [comment]
I think I understand why the scenes are not updated when the 2 scenes are opened. The problem is that on the inherited scene, the `get_modified_properties_for_node` is populated with the `transform` and the `mesh` because `EditorPropertyRevert::get_property_revert_value` returns the value of the base scene and not the value from blender. Theses props are updated on scene reload in the inherited scene with the old values and it seems that both MeshInstance3D in the two scene are using the same RID for the mesh. So updating the mesh in the inherited scene cause the mesh to revert back to the old one in the base scene. Same think for the transform.
I'm not sure how to fix `EditorPropertyRevert::get_property_revert_value`, I'm looking into it.

**Comment by Hilderin** [comment]
After a while, I was able to fix the remaining problems (that I found!). It’s a lot of modifications to manage the inherited scenes correctly.

It's all in this branch: https://github.com/Hilderin/godot/tree/fix-reimport-missing-node


### Fixed problems:
- **Mesh not refreshing & properties reverting in inherited scene**: When the MeshInstance is in an inherited scene, the comparison between the old and the new mesh was done after the mesh was updated in the node. That caused issues with `EditorPropertyRevert::get_property_revert_value`. I fixed this by adding the signal `resources_reimporting` in `EditorFileSystem` and pre-calculating the modified properties before the reimportation.
- **Inherited scene containing a Blender node**: Properties were lost when reloading. This was mainly because it's difficult to only get the modified properties and initialize a new node with exactly the right properties. My solution was to instantiate the whole base scene and grab the Blender node from it already initialized. I did not find a way to only initialize one node from a PackedScene.
- **Direct inheritance of the Blender scene**: The reload was not working. Previously, a new instance of `current_packed_scene` was created to replace the edited scene. The problem is `current_packed_scene` contains all the added nodes as well, so after a reload, all added nodes were duplicated. I calculated a `base_packed_scene`, which is the PackedScene from the base scene (one level down), and used a new instance of it to replace the current edited scene (this also solves multiple levels of inheritance).

### Tested:
- Added node in Godot to Blender object
- Multiple levels of added nodes
- Multiple levels of nodes from Blender with added nodes in Godot
- Moving nodes in Blender
- Modified properties on Blender objects
- Modified properties on added Godot objects
- Signals on Blender objects
- Reference to a Blender object in a script on an added node
- Reference to a Blender object in a script on an added Blender object
- Reference to a child of an added scene in a script on an added Blender object
- Removing or renaming nodes in Blender with attached scripts or child added nodes
- Inherited scene from Blender object
- Editing inherited scenes from Blender object with added nodes and updated properties
- Adding inherited scenes from Blender object to a scene and adding nodes and updating properties
- Multiple nodes of the same scene or inherited scene in the same scene
- Multiple opened scenes with the Blender object in their tree
- Multilevel inheritance with a Blender object

### Some demo:

https://github.com/godotengine/godot/assets/81109165/e9f74dbf-9ed8-44a1-8930-43ab350fdb6c


Test project:
[test-godot-blender-reimport-missing-node-v4.zip](https://github.com/user-attachments/files/16171638/test-godot-blender-reimport-missing-node-v4.zip)

**Comment by AThousandShips** [comment]
You included an unrelated commit into your history, please clean that up using rebasing and removing the incorrect commit, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

**Comment by Yahkub-R** [comment]
> After a while, I was able to fix the remaining problems (that I found!). It’s a lot of modifications to manage the inherited scenes correctly.
> ...

Good stuff!! What a doozy of an issue.  Pulled in your changes.
Reconfirming your tested cases and so far so good 🎉

**Comment by AThousandShips** [comment]
If this is to be included in this PR you should squash it and add Hilderin as a co-author, it needs to be a single commit

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -5917,15 +6005,60 @@ void EditorNode::reload_instances_with_path_in_edited_scenes(const String &p_ins
...
+				Ref<SceneState> scene_state = current_edited_scene->get_scene_inherited_state();
+				if (scene_path_to_node != "." && scene_state.is_valid() && scene_state->get_path() != p_instance_path && scene_state->find_node_by_path(scene_path_to_node) >= 0) {
+					Node *root_node = scene_state->instantiate(SceneState::GenEditState::GEN_EDIT_STATE_INSTANCE);
+					instantiated_node = root_node->get_node(scene_path_to_node);
+
+					if (instantiated_node) {
+						if (instantiated_node->get_parent()) {
+							// Remove from the root so we can delete it from memory.
+							instantiated_node->get_parent()->remove_child(instantiated_node);
+							// No need of the addional children that could have been added to the node
```
Comment (Mickeon) [inline editor/editor_node.cpp:6024]:
```suggestion
							// No need of the additional children that could have been added to the node.
```

File: editor/editor_node.h [hunk 2]
```diff
@@ -819,7 +820,9 @@ class EditorNode : public Node {
 		List<Node::GroupInfo> groups;
 	};
 
-	void update_ownership_table_for_addition_node_ancestors(Node *p_current_node, HashMap<Node *, Node *> &p_ownership_table);
+	HashMap<int, HashMap<NodePath, HashMap<NodePath, ModificationNodeEntry>>> scenes_modification_table;
+	HashMap<int, List<AdditiveNodeEntry>> scenes_addition_list;
```
Comment (Hilderin) [inline editor/editor_node.h:824]: `scenes_addition_list` was never used finally.

File: editor/editor_node.cpp [hunk 3]
```diff
@@ -4279,15 +4284,23 @@ void EditorNode::update_node_reference_modification_table_for_node(
...
+	}
+
 	bool node_part_of_subscene = p_node != p_edited_scene &&
 			p_edited_scene->get_scene_inherited_state().is_valid() &&
-			p_edited_scene->get_scene_inherited_state()->find_node_by_path(p_edited_scene->get_path_to(p_node)) >= 0;
+			p_edited_scene->get_scene_inherited_state()->find_node_by_path(p_edited_scene->get_path_to(p_node)) >= 0 &&
+			// It's important to process added nodes from the base scene in the inherited scene as
+			// additional nodes to ensure they do not disappear on reload.
+			// When p_reimported_root == p_edited_scene that means the edited scene
+			// is the reimported scene and that the node in the the base scene, so it's not an addition.
```
Comment (Hilderin) [inline editor/editor_node.cpp:4298]: Oups, little typos here:
Should be something like: is the reimported scene, in that case the node is in the root base scene, so it's not an addition, otherwise, the node would be added twice on reload.

File: doc/classes/EditorFileSystem.xml [hunk 4]
```diff
@@ -84,6 +84,12 @@
 				Emitted if a resource is reimported.
 			</description>
 		</signal>
+		<signal name="resources_reimporting">
```
Comment (KoBeWi) [inline doc/classes/EditorFileSystem.xml:87]: Why is the signal called `resources_reimporting`, but description mentions one resource?

File: editor/editor_node.cpp [hunk 5]
```diff
@@ -5807,25 +5859,57 @@ void EditorNode::find_all_instances_inheriting_path_in_node(Node *p_root, Node *
...
+
+			// Make sure the node is in the tree so that editor_selection can add node smoothly.
+			scene_root->add_child(current_edited_scene);
+
+			for (Node *original_node : edited_scene_map_elem.value) {
+				// Fetching all the modified properties of the nodes reimported scene.
+				HashMap<NodePath, ModificationNodeEntry> modification_table;
+				get_preload_scene_modification_table(current_edited_scene, original_node, original_node, modification_table);
+
+				if (modification_table.size()) {
```
[the remark this answers is not in the document]
Comment (KoBeWi) [reply editor/editor_node.cpp:5891]: Why not
```suggestion
				if (!modification_table.is_empty()) {
```

[the remark this answers is not in the document]
Comment (AThousandShips) [reply editor/editor_node.cpp:5891]: To match above, and more readable IMO, but either goes

File: editor/editor_node.cpp [hunk 6]
```diff
@@ -6121,6 +6237,24 @@ void EditorNode::reload_instances_with_path_in_edited_scenes(const String &p_ins
 
 		editor_data.restore_edited_scene_state(editor_selection, &editor_history);
 	}
+
+	scenes_modification_table.clear();
+}
+
+void EditorNode::_remove_all_not_owned_children(Node *p_node, Node *p_owner) {
+	Vector<Node *> nodes_to_remove;
```
Comment (KoBeWi) [inline editor/editor_node.cpp:6245]: Not critical here, but you could `resize()` the vector to child count, to avoid appending to vector.

File: editor/editor_node.cpp [hunk 7]
```diff
@@ -5780,6 +5814,24 @@ void EditorNode::reload_scene(const String &p_path) {
 	scene_tabs->set_current_tab(current_tab);
 }
 
+void EditorNode::get_edited_scene_map(const String &p_instance_path, HashMap<int, List<Node *>> &p_edited_scene_map) {
+	// Walk through each opened scene to get a global list of all instances which match
+	// the current reimported scenes.
+	for (int i = 0; i < editor_data.get_edited_scene_count(); i++) {
+		if (editor_data.get_scene_path(i) != p_instance_path) {
```
Comment (KoBeWi) [inline editor/editor_node.cpp:5821]:
```suggestion
		if (editor_data.get_scene_path(i) == p_instance_path) {
			continue;
		}
```
Less nesting.

File: editor/editor_node.cpp [hunk 8]
```diff
@@ -1036,24 +1036,38 @@ void EditorNode::_fs_changed() {
...
 
+void EditorNode::_resources_reimporting(const Vector<String> &p_resources) {
+	// This will copy all the modified properties of the nodes into 'scenes_modification_table'
+	// before they are actually reimported. It's important to do this before the reimportation
+	// because if a mesh is present in an inherited scene, the resource will be modified in
+	// the inherited scene. Then, get_modified_properties_for_node will return the mesh property,
+	// which will trigger a recopy of the previous mesh, preventing the reload.
+	for (const String &res_path : p_resources) {
+		String file_type = ResourceLoader::get_resource_type(res_path);
+		if (file_type == "PackedScene") {
```
Comment (KoBeWi) [inline editor/editor_node.cpp:1047]:
```suggestion
		if (ResourceLoader::get_resource_type(res_path) == "PackedScene") {
```

File: editor/editor_node.cpp [hunk 9]
```diff
@@ -5807,25 +5859,57 @@ void EditorNode::find_all_instances_inheriting_path_in_node(Node *p_root, Node *
...
+
+			for (Node *original_node : edited_scene_map_elem.value) {
+				// Fetching all the modified properties of the nodes reimported scene.
+				HashMap<NodePath, ModificationNodeEntry> modification_table;
+				get_preload_scene_modification_table(current_edited_scene, original_node, original_node, modification_table);
+
+				if (modification_table.size()) {
+					NodePath scene_path_to_node = current_edited_scene->get_path_to(original_node);
+					if (!scenes_modification_table.has(current_scene_idx)) {
+						scenes_modification_table[current_scene_idx] = HashMap<NodePath, HashMap<NodePath, ModificationNodeEntry>>();
```
Comment (KoBeWi) [inline editor/editor_node.cpp:5894]: IIRC this is unnecessary; HashMap handles it automagically.

**Review by KoBeWi — APPROVED** [review]
I'm not very familiar with scene import code, but this fixes the issue without causing visible regressions.

**Comment by Hilderin** [comment]
@Yahkub-R Are you ok to make these modifications or you prefer I create a PR to your branch?

**Comment by akien-mga** [comment]
Could you amend the commit title to be more explicit? It shouldn't refer to the issue but actually say what problem it's solving (the PR title is a good option "Fix instanced .blend/GLTF scenes lose all children after update until .tscn is reopened").

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by Hilderin** [comment]
Thanks @Yahkub-R for your help and teamwork!

**Comment by Yahkub-R** [comment]
> Thanks @Yahkub-R for your help and teamwork!
You too! Good stuff
