### PR TITLE
Set position to zero when saving a positioned branch as scene

### LINKED ISSUE #3962: Add an option to reset the transform of the root node when saving a branch as an instanced scene
### Describe the project you are working on

unrelated

### Describe the problem or limitation you are having in your project

When saving a branch as a scene, the transform of the root node in the new scene is the transform the node had originally:

https://user-images.githubusercontent.com/71937306/153724878-d2d198fe-025f-41df-a93b-ebe13b86e71a.mp4

However, when saving a branch as a scene the idea is in my experience almost always to "promote" a subtree and make it a component on its own, which has no reason not to be centered in its own scene.
What I have to do in the current state of things to achieve this is:
 1. save branch as scene
 2. reset the transform of the root in the newly created scene
 3. re-setup the instance that is not in the right position anymore

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Therefore imo it makes sense to add a checkbox somewhere in the "save branch as scene" dialog, titled "reset root transform" and checked by default that if checked does the following:
 1. reset the transform of the root node in the newly created scene so that the scene is at the origin of its "scene space",
 2. set the transform of the instance that replaces the branch to match the original state.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

see above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I am not sure wether this feature is used often at all. I do use it often. It can't be a script.

### Is there a reason why this should be core and not an add-on in the asset library?

I don't know if it can.

### LINKED ISSUE #80560: Usability when saving positioned branch as new scene
### Godot version

4.1.1

### System information

Windows 10

### Issue description

While prototyping it may happen, that a positioned node, e.g. an obstacle, should be saved as scene to reuse it. While doing so one still want's to preserve the position of the original obstacle in the level. 
After saving the branch to a scene, the root node is offset in the new scene. For reusability most often the root node should be positioned at zero. When setting the position in the new scene, the position in the original level changes and one needs to reposition the obstacle.

### Steps to reproduce

- create scene A
- add a `Node2D`
- change the position of the node
- save the node 2d as new scene
- reset the position to zero in the new scene
- the node is now positioned at zero in the original scene as well

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by HolonProduction**
Fixes #80560

The usability problem results from Godot keeping the state of an instanced scene in sync. This is an important feature and can't be fixed. However by changing the position in the new scene to zero the situation where it becomes a problem for the user is avoided.

* *Bugsquad edit, closes: https://github.com/godotengine/godot-proposals/issues/3962*

### CODE REVIEW

**Comment by KoBeWi** [comment]
Looks alright on the technical side, but you need to change your code. Assignments inside expressions are generally not allowed and here you even made 2 at once.

Also I wonder if this needs a proper proposal. While the new behavior is more useful, some users might rely on the origin not being reset, because it's useful for their workflow for whatever reason.
And what about other transform properties, i.e. rotation and scale? Should they get reset too?

**Comment by HolonProduction** [comment]
> Assignments inside expressions are generally not allowed and here you even made 2 at once.

I wasn't sure about that and had a look at the [C++ usage guidelines](https://docs.godotengine.org/en/stable/contributing/development/cpp_usage_guidelines.html). If that is not allowed here it should be listed there IMHO. But sure I can rewrite it.

> Also I wonder if this needs a proper proposal. While the new behavior is more useful, some users might rely on the origin not being reset, because it's useful for their workflow for whatever reason.

I try to avoid proposals whenever possible, sorry for that, but it just feels as if they never get anywhere. But if you think it might help, sure.

**Comment by KoBeWi** [comment]
> If that is not allowed here it should be listed there IMHO.

Right, it's probably an oversight. The topic was discussed a few times and there was a decision against this coding style, but was never formalized.

> I try to avoid proposals whenever possible, sorry for that, but it just feels as if they never get anywhere. But if you think it might help, sure.

Proposals have a bit more visibility than a random PR closing a random issue that was opened very recently. I think this change is fine, but it's better to get some broader feedback.

**Comment by Bitlytic** [comment]
I noticed this was an annoying issue for new people getting into Godot so I was looking at making my own PR/Proposal for it and stumbled upon this. Was this abandoned/denied or was there a reason this is set to draft mode?

**Comment by HolonProduction** [comment]
I made it a draft when I opened a proposal for it and forgot to mark it for ready when the proposal was closed. But I think I haven't fixed up KoBeWi's notion about assignments inside expressions.

**Comment by HolonProduction** [comment]
I added a question to the older proposal which didn't receive any feedback so here it is again: do we need a checkbox for it? Because if so it needs to be reworked. So yeah kinda waiting for feedback rn.

**Comment by Bitlytic** [comment]
Ah I see, I'll put my personal opinion over on the proposal thread based on things that I've seen from other people using the engine

**Comment by KoBeWi** [comment]
Based on #39754, I think non-centered scenes are a use-case that still should be supported. So indeed some checkbox/option (enabled by default) should be added.

**Comment by Bitlytic** [comment]
@HolonProduction Do you want to continue the work you did on this? I'm not currently working on it because you were before but if you give me the go ahead I'll immediately hop on it as I really care about this feature being completed

**Comment by HolonProduction** [comment]
@Bitlytic go ahead! I'm currently more focused on auto completion and don't have much time anyway.

**Comment by Bitlytic** [comment]
> Based on #39754, I think non-centered scenes are a use-case that still should be supported. So indeed some checkbox/option (enabled by default) should be added.

I'm getting around to this now, you mentioned that it should be enabled by default. I just wanna make sure, you want the new version that saves the branch at (0, 0, 0) to be the version used by default or what's live in Godot 4 to be the default?

**Comment by KoBeWi** [comment]
The new version should be default.

**Comment by HolonProduction** [comment]
Thing is, that apparently we want a checkbox to control this behavior and I never implemented that. So if this is still a requirement, this will need a bit more than a rebase I guess.

**Comment by HolonProduction** [comment]
So I added check boxes to the file dialog:

Screenshot from 2024-09-06 11-42-54

It might make sense to alter the way the options are displayed, to use a `HFlowContainer` because it really does not look great.

Also there are no API's to hide the options, which means they would also be visible when saving a node that is neither `Node2D` nor `Node3D`

**Comment by Mickeon** [comment]
> Also there are no API's to hide the options, which means they would also be visible when saving a node that is neither Node2D nor Node3D

I would have them disabled instead of hidden. But I assume you mean there's no way to infer what type is being saved, which is a pity. 

> Should these be made into editor settings like `docks/scene_tree/center_node_on_reparent` so users only need to set them once?

These kinds of settings are usually stored per-project separately. Although, I'm not sure how at the moment.

**Comment by HolonProduction** [comment]
> I would have them disabled instead of hidden. But I assume you mean there's no way to infer what type is being saved, which is a pity.

No, inferring that before the dialog is shown would be possible through the current selection (that's how it is done after a file path was chosen anyway). But `EditorFileDialog` has no methods to disable, hide or remove an option after it was added. We could probably have two separate file picker dialogues, but that feels a bit heavy (also still no way to have them disabled).

> I see that the option defaults (true, false, false) are hard-coded. Should these be made into editor settings like `docks/scene_tree/center_node_on_reparent` so users only need to set them once?

That's an interesting idea, for now I'd rather keep this PR at its current state and leave this open for a possible follow up. I don't know yet how this would be done, and I hope we can get this in for 4.4, so I don't want to delay it further.

File: editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -3233,6 +3249,36 @@ void SceneTreeDock::_new_scene_from(const String &p_file) {
 		// Root node cannot ever be unique name in its own Scene!
 		copy->set_unique_name_in_owner(false);
 
+		Dictionary dict = new_scene_from_dialog->get_selected_options();
+		bool reset_position = dict.get(TTR("Reset Position"), false);
```
Comment (KoBeWi) [inline editor/scene_tree_dock.cpp:3253]:
```suggestion
		bool reset_position = dict.get(TTR("Reset Position"), true);
```

File: editor/scene_tree_dock.cpp [hunk 2]
```diff
@@ -3233,6 +3249,36 @@ void SceneTreeDock::_new_scene_from(const String &p_file) {
 		// Root node cannot ever be unique name in its own Scene!
 		copy->set_unique_name_in_owner(false);
 
+		Dictionary dict = new_scene_from_dialog->get_selected_options();
```
Comment (KoBeWi) [inline editor/scene_tree_dock.cpp:3252]:
```suggestion
		const Dictionary dict = new_scene_from_dialog->get_selected_options();
```

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
