### PR TITLE
Fix Godot returned status code on unexpected error

### LINKED ISSUE #30207: When the game crashes it still exits with code 0
**Godot version:**
Godot 3.1.1

**OS/device including version:**
Arch Linux

**Issue description:**
When a game crashes due to some error, it exits with status code 0, and there's no way to tell if it crashed or closed on purpose.

**Steps to reproduce:**
1. Create a simple script with a syntax error
2. Attach that script to an empty scene
3. Export that scene
4. Launch the exported scene

**Minimal reproduction project:**
[crashing.zip](https://github.com/godotengine/godot/files/3343128/crashing.zip)

### PR DESCRIPTION
**Pull request by touilleMan**
fix #30207

### CODE REVIEW

File: scene/main/scene_tree.cpp [hunk 1]
```diff
@@ -551,6 +551,9 @@ void SceneTree::quit(int p_exit_code) {
 		// Override the exit code if a positive argument is given (the default is `-1`).
 		// This is a shorthand for calling `set_exit_code()` on the OS singleton then quitting.
 		OS::get_singleton()->set_exit_code(p_exit_code);
+	} else if (!OS::get_singleton()->is_custom_exit_code()) {
+		// Must customize exit code, otherwise it will default to a non-zero value
+		OS::get_singleton()->set_exit_code(0);
```
Comment (Calinou) [inline scene/main/scene_tree.cpp:556]:
```suggestion
		OS::get_singleton()->set_exit_code(EXIT_SUCCESS);
```

File: core/os/os.h [hunk 2]
```diff
@@ -52,7 +52,8 @@ class OS {
 	String _local_clipboard;
 	uint64_t _msec_splash;
 	bool _no_window = false;
-	int _exit_code = 0;
+	int _exit_code = 1; // default to non-zero so unexpected exit is marked as failure
```
Comment (Calinou) [inline core/os/os.h:55]:
```suggestion
	int _exit_code = EXIT_FAILURE; // default to non-zero so unexpected exit is marked as failure
```

**Review by Calinou — COMMENTED** [review]
Tiny nitpicks, but the C standard offers [`EXIT_SUCCESS` and `EXIT_FAILURE` macros](https://en.cppreference.com/w/c/program/EXIT_status) which we already use elsewhere in the codebase. These should be available to use in any C or C++ program.

**Comment by touilleMan** [comment]
@Calinou I've updated the PR to use EXIT_SUCCESS/EXIT_FAILURE macros ;-)

File: scene/main/scene_tree.cpp [hunk 3]
```diff
@@ -551,6 +552,9 @@ void SceneTree::quit(int p_exit_code) {
 		// Override the exit code if a positive argument is given (the default is `-1`).
 		// This is a shorthand for calling `set_exit_code()` on the OS singleton then quitting.
 		OS::get_singleton()->set_exit_code(p_exit_code);
+	} else if (!OS::get_singleton()->is_custom_exit_code()) {
```
Comment (akien-mga) [inline scene/main/scene_tree.cpp:555]: I'm not sure I like this `is_custom_exit_code` logic.

It would expect that when we call `quit()`, either we specify an exit code, or we default to `EXIT_SUCCESS`.

If we currently have situations where we `quit()` on failure with a non-zero exit code, the code that calls `quit()` should be fixed to use `quit(EXIT_FAILURE)`.

Comment (touilleMan) [reply scene/main/scene_tree.cpp:555]: I was thinking about this PR the other day, I think most of the complexity comes from `set_exit_code` which feels like a legacy artifact now we can provide the exit code to `quit()` (passing exit code while calling the exit function is what is done in basically every language)

So if we take advantage of Godot 4.0, we can ditch `set_exit_code` and have `quit()` with `EXIT_SUCCESS` as default value. The `is_custom_exit_code ` stuff is not needed anymore (`exit_code` gets initialized with `EXIT_FAILURE`, and is overwritten when calling `quit()`) ;-)

Comment (touilleMan) [reply scene/main/scene_tree.cpp]: I've updated the PR with 614d890b8944cab2819982039bf34461b8e8492a in this view

**Review by RandomShaper — APPROVED** [review]

File: doc/classes/SceneTree.xml [hunk 4]
```diff
@@ -178,10 +178,13 @@
 		<method name="quit">
 			<return type="void">
 			</return>
-			<argument index="0" name="exit_code" type="int" default="-1">
+			<argument index="0" name="exit_code" type="int" default="0">
 			</argument>
 			<description>
-				Quits the application. A process [code]exit_code[/code] can optionally be passed as an argument. If this argument is [code]0[/code] or greater, it will override the [member OS.exit_code] defined before quitting the application.
+				Quits the application. Argument [code]exit_code[/code] can optionally be given (defaulting to 0) to
+				customize the exit status code.
```
Comment (akien-mga) [inline doc/classes/SceneTree.xml:185]: There shouldn't be manual wrapping, each line == one paragraph.

**Comment by akien-mga** [comment]
Should be good to merge for `master` after a rebase + tiny fix for the documentation.

It's likely not suitable to cherry-pick for `3.2` as it breaks compatibility, maybe we can have another PR with a solution that preserves compat in `3.2` (possibly as it was done initially IIRC).

File: doc/classes/SceneTree.xml (hunk 4 above)
Comment (touilleMan) [reply doc/classes/SceneTree.xml]: fixed.

**Comment by touilleMan** [comment]
@akien-mga I've rebased the PR and created a cherry-pick PR for 3.2 with only the first commit (the one bringing not breaking compatibility), see #46422

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
