### PR TITLE
Prevent 3-to-4 project converter from adding extra line for move_and_slide

### LINKED ISSUE #66054: 3-to-4 project converter adds extra line for move_and_slide
### Godot version

4.0-beta1

### System information

Linux (Pop!_OS 20.04)

### Issue description

When the 3-to-4 project converter converts a call to KinematicBody2D.move_and_slide(), it adds a line containing only "velocity", resulting in a warning message: "Standalone expression (the line has no effect)."

This does not affect the proper execution of the code.

### Steps to reproduce

Convert and run the minimal reproduction project attached below. View the script main.gd and the Errors tab.

### Minimal reproduction project

[project_converter_3_to_4-bug1.zip](https://github.com/godotengine/godot/files/9594360/project_converter_3_to_4-bug1.zip)

### PR DESCRIPTION
**Pull request by DorianSzlachcic**
Hi, I've come up with solution to issue #66054.

The "velocity" line adds because of `move_and_slide` returning velocity in older version. I'm checking now if the line begins with variable declaration or something else. If yes it's adding the velocity line.

I made the same change in `move_and_slide_with_snap` part, where was the same problem.

*Bugsquad edit:*
- Fixes #66054

### CODE REVIEW

**Comment by DorianSzlachcic** [comment]
I have failed static checks. Is it because I didn't use clang-format?

**Review by qarmin — APPROVED** [review]
Can you add also test in test_conversion function?

**Comment by DorianSzlachcic** [comment]
Yeah, I added now test and changed solution a bit so the converter will keep the comments in the line with `move_and_slide` function

File: editor/project_converter_3_to_4.cpp [hunk 1]
```diff
@@ -3146,8 +3148,12 @@ void ProjectConverter3To4::process_gdscript_line(String &line, const RegExContai
...
 				}
 
-				line_new += starting_space + base_obj + "move_and_slide()\n";
-				line = line_new + line.substr(0, start) + "velocity" + line.substr(end + start);
+				line_new += starting_space + base_obj + "move_and_slide()";
+
+				if (!line.begins_with(starting_space + "move_and_slide"))
+					line = line_new + "\n" + line.substr(0, start) + "velocity" + line.substr(end + start);
+				else
+					line = line_new + line.substr(end + start);
```
Comment (akien-mga) [inline editor/project_converter_3_to_4.cpp:3156]: You should use braces around statement blocks for `if` and `else`, even if it's a single line.

**Comment by akien-mga** [comment]
After doing the edit I requested, could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

File: editor/project_converter_3_to_4.cpp (hunk 1 above)
Comment (DorianSzlachcic) [reply editor/project_converter_3_to_4.cpp]: Done

**Comment by akien-mga** [comment]
Please also amend the commit message so that it says what it does in a readable way. The PR title for example is good, and the commit message should be similar, e.g.:

```
Prevent 3-to-4 project converter from adding extra line for `move_and_slide`

Fixes #66054.
```

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
