### PR TITLE
Fix `Projection::invert` for orthographic projection

### LINKED ISSUE #68878: INV_PROJECTION_MATRIX incorrect for orthogonal cameras
### Godot version

4.0.dev (84c404f6bc) and same for 4.0b4

### System information

MacOS Monterey 12.0.1
Intel Iris Graphics 550 1536 MB

### Issue description

When I'm trying to use VIEW_MATRIX transform to change world pos to view pos, it seems get not so correct data. Probably it's due to wrong scaling in .w part of matrix. I'm using orthogonal camera, but it will be the same for perspective 

### Steps to reproduce

1. Add camera and plane in your project, add to plane this shader:
```glsl
shader_type spatial;
render_mode unshaded;

void fragment() {
		
	vec3 clip_uv = vec3(SCREEN_UV * 2.0 - 1.0, 0.0);
	vec4 view_space_uv = INV_PROJECTION_MATRIX * vec4(clip_uv, 1.0);
	vec3 view_uv = view_space_uv.xyz/view_space_uv.w;
	
	vec3 pos = vec3(2.0, 2.0, 0.0); // take it as world_space coordinate

	vec4 view_space_pos = VIEW_MATRIX * vec4(pos, 1.0);
	vec3 view_pos = view_space_pos.xyz/view_space_pos.w;
	
	vec4 clip_space = PROJECTION_MATRIX * VIEW_MATRIX * vec4(pos, 1.0);
	vec3 clip_pos = clip_space.xyz/clip_space.w;
	
	ALBEDO = view_uv - view_pos;
	
        // to see where in camera view our point
	if(distance(clip_pos, clip_uv) < 0.05){
		ALBEDO = vec3(1.0, 0.0, 1.0); 
	}
}
```
we are trying to shift screen uv in view space by our pos value in view space, but result is not correct:

Screenshot 2022-11-19 at 14 00 48

2. But if you transform pos to clip space first and than bring it back to view space:
```glsl
shader_type spatial;
render_mode unshaded;

void fragment() {
	
	vec3 pos = vec3(2.0, 2.0, 0.0); 
	
	vec3 clip_uv = vec3(SCREEN_UV * 2.0 - 1.0, 0.0);
	
	vec4 view_space_uv = INV_PROJECTION_MATRIX * vec4(clip_uv, 1.0);
	vec3 view_uv = view_space_uv.xyz/view_space_uv.w;
	
	vec4 view_space_pos = VIEW_MATRIX * vec4(pos, 1.0);
	vec3 view_pos = view_space_pos.xyz/view_space_pos.w;
	
	vec4 clip_space = PROJECTION_MATRIX * VIEW_MATRIX * vec4(pos, 1.0);
	vec3 clip_pos = clip_space.xyz/clip_space.w;
	
	//ALBEDO = view_uv - view_pos;
	
	vec4 view_test = INV_PROJECTION_MATRIX * vec4(clip_pos, 1.0);
	vec3 pos_test = view_test.xyz/view_test.w;
	
	ALBEDO = view_uv - pos_test;
	
        // to see where in camera view our point
	if(distance(clip_pos, clip_uv) < 0.05){
		ALBEDO = vec3(1.0, 0.0, 0.0);
	}
} 
```
it will shift uv correctly:
Screenshot 2022-11-19 at 14 02 33

but you can notice, that it's a bit not so straight, but scale of uv and pos in view space are about correct now

### Minimal reproduction project

[test_pos.zip](https://github.com/godotengine/godot/files/10046386/test_pos.zip)

### PR DESCRIPTION
**Pull request by EIREXE**
Fixes #68878, specially when using orthographic projection.

Replaces our invert implementation with mesa's, which seems to work fine.

### CODE REVIEW

**Comment by clayjohn** [comment]
Do we have tests for this? If not, this PR should add some

**Comment by EIREXE** [comment]
Added a few tests too

File: tests/core/math/test_projection.h [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+	Projection p = Projection::create_orthogonal(-125.0f, 125.0f, -125.0f, 125.0f, 0.01f, 25.0f);
+	CHECK(projection_is_equal_approx(p.inverse() * p, Projection()));
+}
+
+TEST_CASE("[Projection] Perspective projection matrix inversion") {
+	Projection p = Projection::create_perspective(90.0f, 1.77777f, 0.05f, 4000.0f);
+	CHECK(projection_is_equal_approx(p.inverse() * p, Projection()));
+}
+
+}; //namespace TestProjection
```
Comment (AThousandShips) [inline tests/core/math/test_projection.h:85]:
```suggestion
} //namespace TestProjection
```

File: tests/test_main.cpp [hunk 2]
```diff
@@ -61,7 +61,7 @@
 #include "tests/core/math/test_geometry_3d.h"
 #include "tests/core/math/test_math_funcs.h"
 #include "tests/core/math/test_plane.h"
-#include "tests/core/math/test_quaternion.h"
+#include "tests/core/math/test_projection.h"
```
Comment (AThousandShips) [inline tests/test_main.cpp:64]: Why did you remove this test?

Comment (EIREXE) [reply tests/test_main.cpp:64]: my bad

**Comment by EIREXE** [comment]
Made all expressions into their own lines and added back the accidentally removed test.

File: core/math/projection.cpp [hunk 3]
```diff
@@ -596,101 +596,236 @@ Projection Projection::inverse() const {
...
+	if (Math::abs(r3[0]) > Math::abs(r2[0])) {
+		SWAP_ROWS(r3, r2);
+	}
+	if (Math::abs(r2[0]) > Math::abs(r1[0])) {
+		SWAP_ROWS(r2, r1);
+	}
+	if (Math::abs(r1[0]) > Math::abs(r0[0])) {
+		SWAP_ROWS(r1, r0);
+	}
+	ERR_FAIL_COND(0.0 == r0[0]);
```
Comment (clayjohn) [inline core/math/projection.cpp:669]: I wonder if these should use `Math::is_zero_approx()` which is what we did in the old method. 

CC @aaronfranke

Comment (EIREXE) [reply core/math/projection.cpp:669]: I have a feeling that if it works for mesa it probably works for us, but I am not a math expert.

Comment (clayjohn) [reply core/math/projection.cpp:669]: I have the same feeling. But that's why I summoned Aaron

Comment (aaronfranke) [reply core/math/projection.cpp:669]: Oh, sorry, I missed this ping.

Looking at this code, I believe that using `==` is correct here, and we don't need `is_zero_approx`.

1. It seems that the purpose of this check is to prevent a division by zero.
2. The alternative (what to do if this is zero) is to fail, and I think it's better that the function try to work if it can. If the alternative path was a safer piece of code (like, calculating the correct result through different means) then the is_zero_approx check would be more useful for that (prefer redirecting to a more robust code path if this value may be near-zero which should really be zero itself but is not due to floating point error).

File: core/math/projection.cpp [hunk 4]
```diff
@@ -596,101 +596,229 @@ Projection Projection::inverse() const {
...
-		for (j = 0; j < 4; j++) {
-			if (j != k) {
-				columns[k][j] /= pvt_val;
-			}
-		}
-
-		/** Replace pivot by reciprocal (at last we can touch it). **/
-		columns[k][k] = 1.0 / pvt_val;
+	// Adapted from mesa's src/util/u_math.c util_invert_mat4x4
+	// on commit 0d170a81288f2427425d53965a0daa57a57b110f
```
Comment (clayjohn) [inline core/math/projection.cpp:600]: @akien-mga What do you think about the licensing? The source is MIT licence, so we could include the licence somewhere https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/util/u_math.c?ref_type=heads

But matrix invert isn't really novel code, so it might not be copy-writable. The FSF rule of thumb is 15 lines or more, but there isn't really an algorithm here, its just math.

**Comment by clayjohn** [comment]
Testing locally and I can confirm that this fixes the issue when using an orthographic projection. I also tested performance. With a debug build this version is quite a bit faster than the old version. With a release build there is no difference in performance. 

So we just need to decide what to do about the licensing, and then this should be fine to merge for 4.4

File: core/math/projection.cpp (hunk 4 above)
Comment (akien-mga) [reply core/math/projection.cpp:600]: Hm good question. It does look like a C transcription of 4x4 matrix inversion code, but I didn't look in the details to see if there's some unique "novelty" here compared to what one would derive from a math book or Wikipedia.

I'd suggest a middle ground to include the copyright statement here, but not bother duplicating the actual MIT license text which is already in our header. Also removing the commit reference because I doubt this code changes much (but you can put it in the OP of the PR so we can still find it if it's ever needed).

```suggestion
	// Adapted from Mesa's `src/util/u_math.c` `util_invert_mat4x4`.
	// MIT licensed. Copyright 2008 VMware, Inc. Authored by Jacques Leroy.
```

Comment (EIREXE) [reply core/math/projection.cpp:600]: Oh sorry, I missed it, i will do the change

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
