### PR TITLE
DOF can effect transparent objects now,

### LINKED ISSUE #28240: Depth of field blur combined with transparent materials
**Godot version:**
3.1

**OS/device including version:**
Windows 10, Intel CPU, RTX 2070 GPU

**Issue description:**
Transparent materials are being blurred as if affected by the DOF effect. They are within the range where they should take no blur from the DOF effect.

**Steps to reproduce:**
Create a material with transparency
Enable depth of field far blur
Note blurred material when not in blur range

transparencyrefractiondof

**Minimal reproduction project:**
- Object with transparent material
- Environment with DOF enabled
[DofFail.zip](https://github.com/godotengine/godot/files/3100433/DofFail.zip)

### PR DESCRIPTION
**Pull request by Raphael2048**
Re-copy depth_texture when transparent objects write to depth, so DOF can effect transparent objects. 
fix #28240

### CODE REVIEW

File: drivers/gles3/rasterizer_scene_gles3.cpp [hunk 1]
```diff
@@ -1121,13 +1121,19 @@ bool RasterizerSceneGLES3::_setup_material(RasterizerStorageGLES3::Material *p_m
 
 	if (state.current_depth_draw != p_material->shader->spatial.depth_draw_mode) {
 		switch (p_material->shader->spatial.depth_draw_mode) {
-			case RasterizerStorageGLES3::Shader::Spatial::DEPTH_DRAW_ALPHA_PREPASS:
+			case RasterizerStorageGLES3::Shader::Spatial::DEPTH_DRAW_ALPHA_PREPASS: {
+				glDepthMask(GL_TRUE);
+				// If some transparent objects write to depth, we need to re-copy depth texture when we need it
+				if (p_alpha_pass && !state.used_depth_prepass) state.prepared_depth_texture = false;
```
Comment (akien-mga) [inline drivers/gles3/rasterizer_scene_gles3.cpp]: Please avoid putting condition and statement on the same line, it's not very readable.

**Review by clayjohn — APPROVED** [review]
Looks good to me.

**Comment by akien-mga** [comment]
Thanks!
