### PR TITLE
GDScript: Report property type errors

### LINKED ISSUE #53102: GDScript: Editor does not report type errors in new inline properties
### Godot version

v4.0.dev (73668c59a)

### System information

Windows 10

### Issue description

In Godot 4 we're now able to use new inline properties. Like this:

```gdscript
var inlineprop: int:
	get:
		return inlineprop + "Test"
	set(value):
		inlineprop = value + "Test"
````

But right now the editor does not report any type errors within the getter or setter body.

There are other problems, which are not reported:

```gdscript
# Test1 should report an invalid type conversion in the getter and setter.
var _test1: int = 0
var test1: String:
	get:
		return _test1
	set(value):
		_test1 = value


# Test2 should report an invalid type conversion in the getter and setter.
var test2: String:
	get:
		var t2 : String
		t2 = 2
		print_debug(t2)
		
		return test2
	set(value):
		var t2 : String
		t2 = 2
		test2 = value


# Test 3 should report type error in getter
var _test3: float = 3.3
var test3: int:
	get:
		return _test3
	set(value):
		_test3 = value
		

# Expected Warning in Setter: Unused argument
var test4: String:
	get:
		return test4
	set(value):
		pass


# Test 5 should report getter/setter as wrongly typed
var _test5 : int
var test5 : String:
	get = get_test5, set = set_test5

func get_test5() -> int:
	return _test5

func set_test5(value : int):
	_test5 = value


# Test 6 should report getter/setter as wrongly typed
var _test6
var test6:
	get = get_test6, set = set_test6

func get_test6() -> int:
	return _test6

func set_test6(value : String):
	_test6 = value


# Test 7 should report getter/setter having wrong signature
var _test7
var test7:
	get = get_test7, set = set_test7

func get_test7(value) -> int:
	_test7 = value
	return _test7

func set_test7():
	pass
```

I think I'm able to provide a pull request, which will fix this issue.

### Steps to reproduce

Open the attached project below an open the script TestFailures.gd. No errors are reported, but there should be many.

### Minimal reproduction project

[godot-property-analysis.zip](https://github.com/godotengine/godot/files/7232154/godot-property-analysis.zip)

### PR DESCRIPTION
**Pull request by ZuBsPaCe**
Before, inline getters and setters were of type SuiteNode which were not checked by the gdscript analyzer. resolve_class_body only checked FunctionNode members.

To fix #53102 I transformed those inline getters and setters into FunctionNodes. Please check the example code provided in the issue.

Additionally, I also added some missing checks to old-style getset-properties:
* Getter must return a value and have zero parameters. If the property has a type, the returned type of the getter must be a variant or a compatible type.
* Setter must have a single parameter. If the property has a type, the parameter must be a variant or a compatible type.
* If the property is untyped, either the getter return type or the setter parameter must be a variant or their type must be compatible.

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -869,18 +869,32 @@ void GDScriptAnalyzer::resolve_class_body(GDScriptParser::ClassNode *p_class) {
...
-		}
+		if (member.type == GDScriptParser::ClassNode::Member::FUNCTION) {
+			resolve_function_body(member.function);
 
-		resolve_function_body(member.function);
+			// Apply annotations.
+			for (GDScriptParser::AnnotationNode *&E : member.function->annotations) {
+				E->apply(parser, member.function);
+			}
+		} else if (member.type == GDScriptParser::ClassNode::Member::VARIABLE && member.variable->property != GDScriptParser::VariableNode::PropertyStyle::PROP_NONE) {
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:882]: We usually don't add the enum name when referring to its elements. Although this is more of a legacy convention since older compilers didn't support it, given that in other places this code doesn't have the enum name (e.g. in `GDScriptParser::ClassNode::Member::FUNCTION` it doesn't specify the `Type` enum), I think it should be better to keep the current convention, so this should use `GDScriptParser::VariableNode::PROP_NONE`.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 2]
```diff
@@ -896,17 +910,80 @@ void GDScriptAnalyzer::resolve_class_body(GDScriptParser::ClassNode *p_class) {
...
 #ifdef DEBUG_ENABLED
-		if (member.variable->usages == 0 && String(member.variable->identifier->name).begins_with("_")) {
-			parser->push_warning(member.variable->identifier, GDScriptWarning::UNUSED_PRIVATE_CLASS_VARIABLE, member.variable->identifier->name);
-		}
+			if (member.variable->usages == 0 && String(member.variable->identifier->name).begins_with("_")) {
+				parser->push_warning(member.variable->identifier, GDScriptWarning::UNUSED_PRIVATE_CLASS_VARIABLE, member.variable->identifier->name);
+			}
+#endif
+
+			if (member.type == GDScriptParser::ClassNode::Member::VARIABLE && member.variable->property == GDScriptParser::VariableNode::PropertyStyle::PROP_SETGET) {
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:923]: The condition `member.type == GDScriptParser::ClassNode::Member::VARIABLE` is already checked in the outer `if`, so it's not needed here.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 3]
```diff
@@ -1518,12 +1595,24 @@ void GDScriptAnalyzer::resolve_parameter(GDScriptParser::ParameterNode *p_parame
...
+	bool has_expected_type = false;
+
+	if (parser->current_function != nullptr) {
+		expected_type = parser->current_function->get_datatype();
+		has_expected_type = true;
+	}
+	//else if (parser->current_property != nullptr) {
+	//	expected_type = parser->current_property->get_datatype();
+	//	has_expected_type = true;
+	//}
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:1608]: Any reason to add commented out code?

File: modules/gdscript/gdscript_parser.cpp [hunk 4]
```diff
@@ -947,17 +947,35 @@ GDScriptParser::VariableNode *GDScriptParser::parse_property(VariableNode *p_var
...
 			if (consume(GDScriptTokenizer::Token::IDENTIFIER, R"(Expected parameter name after "(".)")) {
 				p_variable->setter_parameter = parse_identifier();
 			}
 			consume(GDScriptTokenizer::Token::PARENTHESIS_CLOSE, R"*(Expected ")" after parameter name.)*");
 			consume(GDScriptTokenizer::Token::COLON, R"*(Expected ":" after ")".)*");
 
-			p_variable->setter = parse_suite("setter definition");
-			break;
+			FunctionNode *function = alloc_node<FunctionNode>();
+			function->identifier = p_variable->identifier;
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp:959]: I think this might be a bit dangerous considering that you temporarily change the name in the compiler. It's better to create a new `IdentifierNode` and set its name here.

File: modules/gdscript/gdscript_parser.cpp [hunk 5]
```diff
@@ -947,17 +947,35 @@ GDScriptParser::VariableNode *GDScriptParser::parse_property(VariableNode *p_var
...
+			ParameterNode *parameter = alloc_node<ParameterNode>();
+			parameter->identifier = p_variable->setter_parameter;
+
+			function->parameters_indices[parameter->identifier->name] = 0;
+			function->parameters.push_back(parameter);
+
+			SuiteNode *body = alloc_node<SuiteNode>();
+			body->add_local(parameter, function);
+
+			function->body = parse_suite("function declaration", body);
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp:973]: The context should be `setter declaration` to make error messages clearer.

```suggestion
			function->body = parse_suite("setter declaration", body);
```

File: modules/gdscript/gdscript_parser.cpp [hunk 6]
```diff
@@ -972,11 +990,22 @@ void GDScriptParser::parse_property_setter(VariableNode *p_variable) {
...
 
-			p_variable->getter = parse_suite("getter definition");
+			FunctionNode *function = alloc_node<FunctionNode>();
+			function->identifier = p_variable->identifier;
+
+			FunctionNode *previous_function = current_function;
+			current_function = function;
+
+			SuiteNode *body = alloc_node<SuiteNode>();
+			function->body = parse_suite("function declaration", body);
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp:1003]:
```suggestion
			function->body = parse_suite("getter declaration", body);
```

File: modules/gdscript/gdscript_parser.cpp [hunk 7]
```diff
@@ -4433,7 +4462,7 @@ void GDScriptParser::TreePrinter::print_variable(VariableNode *p_variable) {
 			if (p_variable->property == VariableNode::PROP_INLINE) {
 				push_line(":");
 				increase_indent();
-				print_suite(p_variable->getter);
+				print_function(p_variable->getter);
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp:4465]: This might be a bit awkward when printed out since it already prints a sort of signature for the getter, then `print_function` will add another signature. It's better to keep printing only the suite:

```suggestion
				print_suite(p_variable->getter->body);
```

Same thing for the setter.

File: modules/gdscript/gdscript_parser.cpp [hunk 8]
```diff
@@ -4453,7 +4482,7 @@ void GDScriptParser::TreePrinter::print_variable(VariableNode *p_variable) {
 				}
 				push_line("):");
 				increase_indent();
-				print_suite(p_variable->setter);
+				print_function(p_variable->setter);
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp:4485]:
```suggestion
				print_suite(p_variable->setter->body);
```

**Review by vnen — CHANGES_REQUESTED** [review]
Overall looks good to me, I just have some nitpicks in the way it's done.

**Comment by vnen** [comment]
One other thing: if you could add integration tests for those cases it would be great. See [the documentation](https://docs.godotengine.org/en/latest/development/cpp/unit_testing.html#integration-tests-for-gdscript) for info about how those work.

**Comment by ZuBsPaCe** [comment]
@vnen Thanks for your detailed review! Things I did:

* Fixed the things in your comments exactly as you told me to. See Commit 649849c

* Added some test cases for properties. It's not a simple task, because there are so many things which could be tested. Adding tests for all different kinds of errors is cumbersome, because each test can only check one error. Added some simple tests in commit 1fdded2

* I rebased those 3 commits to master without squashing. Hope that's what you expected.

**Review by vnen — CHANGES_REQUESTED** [review]
Other than the comments it's okay, could be merged after addressing those.

The commits can be squashed into one as well.

**Review by vnen — APPROVED** [review]
