### PR TITLE
Freelook interpolation fixes

### LINKED ISSUE #11614: The camera wiggles back and forth when freelook speed is modulated
Godot 3.0 master

Mouse wheel is supposed to modulate speed while using freelook, aside from having a link with orbit zoom.
However, when I do this in the current master it makes the camera wiggle back and forth in unwanted ways.
It worked fine before, so something must have broken the way this is handled...

### PR DESCRIPTION
**Pull request by Zylann**
Fixes #11614

- Smooth freelook position more explicitely, together with orbit smooth
- Don't let orbit zoom produce translation when it shouldn't
- Make base speed framerate-independent (and tweaked setting for that)
- Don't rely on camera for calculations because it no longer reflects immediate state

Additions:
- Make speed/zoom relation optional (if enabled, speed is adjusted from zoom)
- Never change zoom distance when freelook is active
- Orbit inertia also applies on freelook

To do (here, or a future PR):
- Show an icon on the zoom/speed bar to differentiate zoom and speed

### CODE REVIEW

File: editor/plugins/spatial_editor_plugin.cpp [hunk 1]
```diff
@@ -75,34 +75,57 @@ void SpatialEditorViewport::_update_camera(float p_interp_delta) {
...
+			//when not being manipulated, move softly
+			float free_orbit_inertia = EDITOR_GET("editors/3d/navigation_feel/orbit_inertia");
+			float free_translation_inertia = EDITOR_GET("editors/3d/navigation_feel/translation_inertia");
+			//when being manipulated, move more quickly
+			float manip_orbit_inertia = EDITOR_GET("editors/3d/navigation_feel/manipulation_orbit_inertia");
+			float manip_translation_inertia = EDITOR_GET("editors/3d/navigation_feel/manipulation_translation_inertia");
 
-	camera_cursor.x_rot = Math::lerp(old_camera_cursor.x_rot, cursor.x_rot, MIN(1.f, p_interp_delta * (1 / orbit_inertia)));
-	camera_cursor.y_rot = Math::lerp(old_camera_cursor.y_rot, cursor.y_rot, MIN(1.f, p_interp_delta * (1 / orbit_inertia)));
+			float zoom_inertia = EDITOR_GET("editors/3d/navigation_feel/zoom_inertia");
```
Comment (nooperation) [inline editor/plugins/spatial_editor_plugin.cpp]: Is it possible for zoom_inertia to be zero and cause division by zero? I notice both orbit and translation inertia both explicitly guard against division by zero below

Comment (Zylann) [reply editor/plugins/spatial_editor_plugin.cpp]: I didnt touch this code (just moved it), but well spotted :)

Comment (Zylann) [reply editor/plugins/spatial_editor_plugin.cpp]: I added `zoom_inertia = MAX(0.0001, zoom_inertia);`

**Comment by reduz** [comment]
I suggest we meet on irc at some point all those involved in this code and decide what to do about it, because it seems no one is completely happy on how it's implemented.

**Comment by djrm** [comment]
@reduz your orbit camera implementation is great, i think the freelook should behave in the same way, of course without the current zoom problem.

**Comment by Zylann** [comment]
@djrm what's wrong with the implementation? It used to work fine before, with fewer code, because I was taking programming shortcuts which allowed the code to be similar to orbit.
But since we added interpolation everywhere, the shortcuts broke, so I didn't really have much choice here but to differentiate code paths...

I can be on IRC in 1 hour

**Comment by djrm** [comment]
@Zylann all the camera changes were introduced in order to have a smooth camera, however the freelook camera has a very jerky movement when rotating it doesnt feel like the orbit, also i think this has been mentioned before and there is a discussion about it, but i think that the linkage between orbit zoom and freelook speed is very counter intuitive and a bit annoying.

**Comment by Zylann** [comment]
@djrm freelook doesnt have rotation smoothing indeed, but this PR actually makes it easier to do so, or maybe even use the orbit one.
Linking of freelook speed can be turned off pretty easily as well, I was thinking about making it an option (because if you remove the link, something else will become annoying: the speed at which you "left" freelook mode may be inaproppriate as I explained many times, but we can talk about it)

**Comment by djrm** [comment]
@Zylann yeah i agree that this needs further discussion.

**Comment by Zylann** [comment]
I added a few changes:

- Make speed/zoom relation optional (if enabled, speed is adjusted from zoom)
- Never change zoom distance when freelook is active
- Orbit inertia also applies on freelook

**Comment by n-pigeon** [comment]
I'm really happy about decoupling zoom and speed :D

**Comment by HummusSamurai** [comment]
>     Show an icon on the zoom/speed bar to differentiate zoom and speed

Yes please :D

**Comment by djrm** [comment]
I've tested this PR and it is great to have decoupled zoom and speed, also and i noticed that the (speed) bar for freelook does not update with the freelook speed, also the freelook camera is a bit floaty, but that of course can be fixed on the user side by changing the settings.

**Comment by Zylann** [comment]
@djrm yeah settings can either be tweaked or made per mode if needed.
I might have forgot to update the bar hmmm I'll have a look later, also will see if I can add the icon when I get the time

**Comment by Zylann** [comment]
Added an icon, but I can't find a way to make it load at its original size (24x24), instead it loads at 16x16, which is too small IMO...

image image

**Comment by Zylann** [comment]
Woops, I didn't update the PR with the icon yet (was waiting for @djrm's answer). I'll open another PR.
