### PR TITLE
Strip ANSI escape codes from file logging

### LINKED ISSUE #79508: 'print_rich' saves text to log with tags converted to ANSI symbols what makes closing tags unreadable.
### Godot version

4.1

### System information

Win 10

### Issue description

When using _print_rich_ to print some logs.

This is what log looks like in godot:
image

This is how its is saved in log file:
```
0:[color=deepSkyBlue][gds]:>[39m[color=palegreen][S]:>[39m[mi:1|a:1]:>[color=gold]W:[39m [1mTheGameState:[Wrapped:0][22m:> gameUnitSpawner.spawn_path:../Units
1:[color=deepSkyBlue][gds]:>[39m[color=palegreen][S]:>[39m[mi:1|a:1]:>[color=gold]W:[39m [1mTheGameState:[Wrapped:0][22m:> No 'Players' node. Creating.
2:[color=deepSkyBlue][gds]:>[39m[color=palegreen][S]:>[39m[mi:1|a:1]:>[color=firebrick]E:[39m [1mTheGameState:[Wrapped:0][22m:> Cant find Players MultiplayerSpawner with namePlayersSpawner
[bgcolor=palegreen][30m[Serv]:>[39m[49m [1mTheGameState:[Wrapped:0][22m:>No 'Players Spawner (miltiplayer)' node. Creating. 
3:[color=deepSkyBlue][gds]:>[39m[color=palegreen][S]:>[39m[mi:1|a:1]:>[color=gold]W:[39m [1mTheGameState:[Wrapped:0][22m:> PlayersSpawner.spawn_path:../Players
4:[color=deepSkyBlue][gds]:>[39m[color=palegreen][S]:>[39m[mi:1|a:1]:>[color=gold]W:[39m [1mTheGameState:[Wrapped:0][22m:> gravity 9.8
```

This is how it is displayed when i try to read it from log file and draw it with RichTextLabel:
image

Expected behavior: 
Closing tags printed as text, not as ANSI symbols. 

### Steps to reproduce

Print something with print_rich and them open log file.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Calinou**
Text editors cannot display ANSI escape codes, so these should be stripped from log files to ensure readability.

Since this uses a regex, this works both for `print_rich()` and manually inserted ANSI escape codes.

This has a slight performance impact: starting Godot, printing 200,000 lines then exiting Godot now takes 1.85 seconds instead of 1.75 seconds on an i9-13900K with a Linux x86_64 optimized (LTO) editor build. It may be possible to have a slightly faster solution using manual string handling, but handling all ANSI escape codes in a robust manner can be nontrivial. I've tried to use `strstr()` to check for the presence of an ANSI escape code in the log message before applying the regex on it, but it made no difference in performance.

- This closes https://github.com/godotengine/godot/issues/79508.

## Preview

stdout appearance for reference:

image

### Before

Log file contents:

```
raw string0
[1mte[91mst[39m[22m[0m
1
[1mte[91mst[39m[22m[0m
2
[1mte[91mst[39m[22m[0m
3
[1mte[91mst[39m[22m[0m
4
```

### After

Log file contents:

```
test
1
test
2
test
3
test
4
```

### CODE REVIEW

File: core/io/logger.cpp [hunk 1]
```diff
@@ -180,6 +182,21 @@ RotatedFileLogger::RotatedFileLogger(const String &p_base_path, int p_max_files)
...
+}
+
+RotatedFileLogger::~RotatedFileLogger() {
+	// FIXME: This doesn't appear to be run when exiting the project by clicking the X window button,
+	// therefore a leaked instance issue occurs:
+	//
+	//     WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
+	//     at: cleanup (./core/object/object.cpp:2290)
+	//     Leaked instance: RegEx:9223372039421689985
+	memdelete(strip_ansi_regex);
```
Comment (Calinou) [inline core/io/logger.cpp:199]: I'm running into an issue reported by asan here, not sure how to fix it. If I put a print statement in the destructor, I never see it. Logger and CompositeLogger both have destructors which seem to work.

I just tried making the destructor virtual (like the one for StdLogger) to no avail.

Comment (bruvzg) [reply core/io/logger.cpp:199]: Loggers are deleted in the `OS` destructor, which is called after `ObjectDB` deletion. `RotatedFileLogger` is already using `detach_from_objectdb()` method on `file` right after creation to remove it for the `ObjectDB` and avoid errors on exit, `RegEx` probably should do the same.

Comment (bruvzg) [reply core/io/logger.cpp:199]: Also, `RegEx` is `RefCounted`, so it can be declared `Ref<RegEx>` to avoid manual deletion and need for destructor.

File: core/io/logger.h [hunk 2]
```diff
@@ -86,8 +92,13 @@ class RotatedFileLogger : public Logger {
 	void clear_old_backups();
 	void rotate_file();
 
+#ifdef MODULE_REGEX_ENABLED
+	RegEx *strip_ansi_regex;
```
Comment (bruvzg) [inline core/io/logger.h:96]:
```suggestion
	Ref<RegEx> strip_ansi_regex;
```

File: core/io/logger.cpp [hunk 3]
```diff
@@ -180,6 +182,21 @@ RotatedFileLogger::RotatedFileLogger(const String &p_base_path, int p_max_files)
 		base_path(p_base_path.simplify_path()),
 		max_files(p_max_files > 0 ? p_max_files : 1) {
 	rotate_file();
+
+#ifdef MODULE_REGEX_ENABLED
+	strip_ansi_regex = memnew(RegEx);
```
Comment (bruvzg) [inline core/io/logger.cpp:187]:
```suggestion
	strip_ansi_regex.instantiate();
	strip_ansi_regex->detach_from_objectdb(); // Note: This RegEx instance will exist longer than ObjectDB, therefore can't be registered in ObjectDB.
```

File: core/io/logger.cpp (hunk 1 above)
Comment (bruvzg) [inline core/io/logger.cpp:199]:
```suggestion
```

File: core/io/logger.h [hunk 4]
```diff
@@ -86,8 +92,13 @@ class RotatedFileLogger : public Logger {
...
+#endif // MODULE_REGEX_ENABLED
+
 public:
 	explicit RotatedFileLogger(const String &p_base_path, int p_max_files = 10);
+	virtual ~RotatedFileLogger();
```
Comment (bruvzg) [inline core/io/logger.h:101]:
```suggestion
```

File: core/io/logger.cpp (hunk 1 above)
Comment (Calinou) [reply core/io/logger.cpp]: It works, thanks :slightly_smiling_face:

File: core/io/logger.cpp [hunk 5]
```diff
@@ -30,6 +30,8 @@
 
 #include "logger.h"
 
+#include "modules/modules_enabled.gen.h" // For regex.
+
```
[the remark this answers is not in the document]
Comment (akien-mga) [reply core/io/logger.cpp:34]: For this include specifically, I actually prefer that we're redundant, as it makes it clear when reading whether the `MODULE_*_ENABLED` are defined or not.

It's already happened that the header dependency on the include was removed, leaving a .cpp file resolving its `MODULE_*_ENABLED` to 0 without errors, breaking the logic.

Comment (akien-mga) [inline core/io/logger.cpp:34]: We usually put this include after the main block of Godot includes.

File: core/io/logger.h [hunk 6]
```diff
@@ -31,10 +31,16 @@
...
+#include "modules/modules_enabled.gen.h" // For regex.
+
 #include "core/io/file_access.h"
 #include "core/string/ustring.h"
 #include "core/templates/vector.h"
 
+#ifdef MODULE_REGEX_ENABLED
+#include "modules/regex/regex.h"
+#endif // MODULE_REGEX_ENABLED
+
```
Comment (akien-mga) [inline core/io/logger.h:43]: This is the canonical style for this combo:
```suggestion
#include "core/io/file_access.h"
#include "core/string/ustring.h"
#include "core/templates/vector.h"

#include "modules/modules_enabled.gen.h" // For regex.
#ifdef MODULE_REGEX_ENABLED
#include "modules/regex/regex.h"
#endif // MODULE_REGEX_ENABLED

```

**Review by akien-mga — APPROVED** [review]
Looks good.

At some point we might have to consider making RegEx a core component instead of a module, as we're starting to use it in more and more places and these conditional behaviors are error prone. (It might be the case already that a build without the regex module, while it should compile fine, might have bugs in some features that are not expected.)

**Comment by akien-mga** [comment]
Thanks!
