### PR TITLE
Fix editor crash when saving a scene containing an inherited scene instance.

### LINKED ISSUE #26694: Editor crash when saving a scene containing an inherited scene instance.
**Godot version:**
Godot 3.1 custom (release_debug, msvc), 2940417

**OS/device including version:**
Windows 10 x64

**Issue description:**
Editor crashes upon trying to save a scene which contains a scene which is inherited from the current one instance within it.

The whole thing sounds fishy and screams about cyclic references, but this surely shouldn't result in a crash.

**Steps to reproduce:**
1. Create a parent scene with a Node as root.
2. Create an inherited child scene from the first one.
3. Save everything.
4. Go to parent scene, instantiate a child scene into it.
5. Try to save by hitting Ctrl+S.
6. Experience a crash.

**Minimal reproduction project:**
[inherited_crash.zip](https://github.com/godotengine/godot/files/2935659/inherited_crash.zip)

### PR DESCRIPTION
**Pull request by Raphael2048**
Fixes #26694 by adding check for target scene's parent scene when instance scene.

### CODE REVIEW

File: editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -185,21 +185,33 @@ void SceneTreeDock::_perform_instance_scenes(const Vector<String> &p_files, Node
...
-				error = true;
-				break;
+			Node *p = instanced_scene;
+			while (p) {
+				if (_cyclical_dependency_exists(edited_scene->get_filename(), p)) {
+					accept->set_text(vformat(TTR("Cannot instance the scene '%s' because the current scene exists within one of its nodes."), p_files[i]));
+					accept->popup_centered_minsize();
+					error = true;
+					memdelete(p);
+					goto Skip;
```
Comment (hpvb) [inline editor/scene_tree_dock.cpp]: Can't this be an else branch instead?

**Review by hpvb — CHANGES_REQUESTED** [review]

File: editor/scene_tree_dock.cpp (hunk 1 above)
Comment (raphael10241024) [reply editor/scene_tree_dock.cpp]: It will track a the inherted scene's parent scene, so i use loop to track upwards here.  I found some other questions from those code, it's hard to check the scene's relationship when use inhert and instance at the same time, I'm trying to modify it

**Comment by raphael10241024** [comment]
I have commit the code changed now

**Comment by akien-mga** [comment]
Thanks!
