### PR TITLE
Fix data directory of unnamed projects

### LINKED ISSUE #44083: logs directory appears in new project when running
**Godot version:**

3.2.4 beta3

**OS/device including version:**

Windows 10

**Steps to reproduce:**
1. Create a new project
2. Add any scene
3. Run project
4.
image

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #44083
Desktop platforms defaulted to the project directory if its name was empty. Now they will use `[unnamed project]` instead.

### CODE REVIEW

File: core/os/os.h [hunk 1]
```diff
@@ -77,6 +77,8 @@ class OS {
 	void _set_logger(CompositeLogger *p_logger);
 
 public:
+	const String UNNAMED_PROJECT_NAME = "[unnamed godot project]";
```
Comment (akien-mga) [inline core/os/os.h:80]: That feels a bit overkill to have something not really OS-related as a constant here. Since it's only used in two locations, I'd suggest just hardcoding the value in each class.

Comment (akien-mga) [reply core/os/os.h:80]: I'd also suggest simplifying to just "[unnamed project]".

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.
