### PR TITLE
Don't edit current when changing docks v2

### LINKED ISSUE #90654: Toggling distraction-free mode selects (or opens) a fixed script in the script list
### Tested versions

- does *not* happen in 4.3 dev 5
- happens in v4.3.dev.custom_build [578d93792]

### System information

linux

### Issue description

- when toggling distraction free mode, a previously opened script is automatically re-opened
  - it happens independently of the number of opened scripts 
- if deleted, it reopens anyway as an unsaved script

- in the clip below, I create a new script and toggle distraction free mode after closing the script: notice how it gets automatically re-openened. Note that I use a shortcut to close the script, which is why it happens quickly.

https://github.com/godotengine/godot/assets/71937306/4ae4a8a9-0dac-455c-9941-d95b7e3c88b2

### Steps to reproduce

- create a script and open it, and close it
- toggle distraction free mode
- notice how the script opens automatically

### Minimal reproduction project (MRP)

any

### PR DESCRIPTION
**Pull request by kitbdev**
- redo of #90816
- fixes https://github.com/godotengine/godot/issues/90654

Made the `edit(nullptr)` in `NOTIFICATION_PREDELETE` not run when exiting, since it doesn't need to clean up anything if exiting.
The object was apparently freed but not null, causing a crash on some platforms.

Needs testing on Linux and macOS to make sure https://github.com/godotengine/godot/pull/90816#issuecomment-2071069759 doesn't happen.

Edit: made sure it works when there is no EditorNode, like in dotnet glue binding.

### CODE REVIEW

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -4019,14 +4019,16 @@ void EditorInspector::_notification(int p_what) {
 		} break;
 
 		case NOTIFICATION_PREDELETE: {
-			edit(nullptr); //just in case
+			if (EditorNode::get_singleton() && !EditorNode::get_singleton()->is_exiting()) {
```
Comment (KoBeWi) [inline editor/editor_inspector.cpp:4022]: Is there any case where inspector is freed without exiting the editor? 🤔

**Review by KoBeWi — APPROVED** [review]
This is basically same as #90816, but with a safeguard against exit crash.

**Review by akien-mga — APPROVED** [review]
Seems to work fine on Linux.

**Comment by akien-mga** [comment]
Thanks!
