### PR TITLE
Network: Normalize IP parsing, fix IPv6, tests

### LINKED ISSUE #99623: Incorrect results for 'is_valid_ip_address()' for compressed IPv6 adresses using '::'
### Tested versions

4.4 dev

### System information

Godot v4.4.dev (0c45ace15) - Windows 10.0.18363  - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 32.0.15.6614) - Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 threads)

### Issue description

The ```is_valid_ip_address()``` method has inconsistent behavior when validating IPv6 addresses with multiple occurrences of ```::```. According to the IPv6 standard, ```::``` can only appear once in an address to represent consecutive zero segments, but currently, for example, the method incorrectly validates addresses like  ```2001:db8:::1``` and ```2001::1::1``` as valid. These padding styles should not be possible.

Down below are some test cases that shows that the methods returns ```true``` when we expect ```false```
Image

### Steps to reproduce

```gdscript 
extends Node

func _ready() -> void:
		print("\nTesting is_valid_ip_address() Method:\n")

		print("Valid IPv4 Addresses:")
		print("Input: ", "192.168.1.1",         "\t -> Result:", "192.168.1.1".is_valid_ip_address())         # Expected: true
		print("Input: ", "255.255.255.255",     "\t -> Result:", "255.255.255.255".is_valid_ip_address())     # Expected: true (broadcast address)

		print("\nInvalid IPv4 Addresses:")
		print("Input: ", "256.256.256.256",     "\t -> Result:", "256.256.256.256".is_valid_ip_address())     # Expected: false (out of range)
		print("Input: ", "192.168.1",           "\t -> Result:", "192.168.1".is_valid_ip_address())           # Expected: false (missing octet)
		print("Input: ", "192.168.-1.1",        "\t -> Result:", "192.168.-1.1".is_valid_ip_address())        # Expected: false (negative octet)

		print("\nValid IPv6 Addresses:")
		print("Input: ", "::1",                 "\t -> Result:", "::1".is_valid_ip_address())                 # Expected: true (loopback address)
		print("Input: ", "2001:db8::",          "\t -> Result:", "2001:db8::".is_valid_ip_address())          # Expected: true (trailing `::`)

		print("\nInvalid IPv6 Addresses:")
		print("Input: ", "2001:db8:::1",        "\t -> Result:", "2001:db8:::1".is_valid_ip_address())        # Expected: false (multiple `::`)
		print("Input: ", "2001::1::1",          "\t -> Result:", "2001::1::1".is_valid_ip_address())          # Expected: false (multiple `::`)
		print("Input: ", "::ffff:999.999.999.999","\t -> Result:", "::ffff:999.999.999.999".is_valid_ip_address()) # Expected: false (invalid IPv4 in IPv6)

		print("\nEdge Cases:")
		print("Input: ", "",                    "\t -> Result:", "".is_valid_ip_address())                    # Expected: false (empty string)
		print("Input: ", ":1",                  "\t -> Result:", ":1".is_valid_ip_address())                  # Expected: false (incomplete address)
		print("Input: ", "12345::",             "\t -> Result:", "12345::".is_valid_ip_address())             # Expected: false (invalid segment length)
		
```

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #112511: IPv6 address validation accepts invalid addresses
### Tested versions

v4.5.1.stable.official

### System information

Debian 12, Micro-Star International Co., Ltd. MS-7B84, AMD Ryzen™ 7 PRO 1700X × 16

### Issue description

The ip address validation of Strings does not work properly. The Ip-Address "FF00::::::::" is accepted as valid, even though it is an invalid address. I found this when having crashes without error messages when using thejoin_multicast_group function of the PacketPeerUDP.

### Steps to reproduce

"FF00::::::::".is_valid_ip_address() returns true, even though it should return false

### Minimal reproduction project (MRP)

[ip-6-test.zip](https://github.com/user-attachments/files/23419310/ip-6-test.zip)

### PR DESCRIPTION
**Pull request by Faless**
This PR normalize IP parsing across `String` and `IPAddress`, fixes many cases of incorrect parsing, and adds many test cases to validate the new parser.

The parser is designed to do zero heap allocations, although I'm not particularly fond of the code (parsing IPv6 is hard :sob: ), the result is much better than before and makes `String.is_valid_ip_address` consistent with `IPAddress.is_valid`.

Closes #114245 (superseded)
Closes #112554 (superseded)
Closes #99624 (superseded)
Fixes #112511
Fixes #99623

<details>
  <summary>Tests result with the old implementation</summary>
  
```
===============================================================================
./tests/core/io/test_ip_address.h:51:
TEST CASE:  [IPAddress] IPv4 is_valid

./tests/core/io/test_ip_address.h:59: ERROR: CHECK( IPAddress("127.0.0.-1").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

./tests/core/io/test_ip_address.h:60: ERROR: CHECK( IPAddress("127.0.0.256").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

./tests/core/io/test_ip_address.h:61: ERROR: CHECK( IPAddress("127.0.0.").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

./tests/core/io/test_ip_address.h:62: ERROR: CHECK( IPAddress(".0.0.1").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

===============================================================================
./tests/core/io/test_ip_address.h:90:
TEST CASE:  [IPAddress] IPv6 is_valid

./tests/core/io/test_ip_address.h:134: ERROR: CHECK( IPAddress("::-0").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

./tests/core/io/test_ip_address.h:135: ERROR: CHECK( IPAddress("1:1:1:1:1:1:1:g").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

./tests/core/io/test_ip_address.h:136: ERROR: CHECK( IPAddress("1:1:1:1:1:1:1:1:1").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

./tests/core/io/test_ip_address.h:137: ERROR: CHECK( IPAddress("1:1:1:1:1:1:1:1::").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

./tests/core/io/test_ip_address.h:138: ERROR: CHECK( IPAddress("::1:1:1:1:1:1:1:1").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

./tests/core/io/test_ip_address.h:140: ERROR: CHECK( IPAddress("::1::1").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

./tests/core/io/test_ip_address.h:144: ERROR: CHECK( IPAddress("1::ffff:127.0.0.1").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

./tests/core/io/test_ip_address.h:145: ERROR: CHECK( IPAddress("::1:ffff:127.0.0.1").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

./tests/core/io/test_ip_address.h:146: ERROR: CHECK( IPAddress("::ffff:127.0.256.1").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

./tests/core/io/test_ip_address.h:147: ERROR: CHECK( IPAddress("::ffff:127.0.0.256").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

./tests/core/io/test_ip_address.h:148: ERROR: CHECK( IPAddress("::ffff:256.0.0.1").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

./tests/core/io/test_ip_address.h:149: ERROR: CHECK( IPAddress("::ffff:127.0.0.1.1").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

./tests/core/io/test_ip_address.h:150: ERROR: CHECK( IPAddress("::ffff:127.0.0.1.").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

./tests/core/io/test_ip_address.h:151: ERROR: CHECK( IPAddress("::ffff:127.0.0.").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

./tests/core/io/test_ip_address.h:152: ERROR: CHECK( IPAddress("::ffff:127.0.0").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

./tests/core/io/test_ip_address.h:153: ERROR: CHECK( IPAddress("::ffff:127.0.").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

./tests/core/io/test_ip_address.h:154: ERROR: CHECK( IPAddress("::ffff:127.0").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

./tests/core/io/test_ip_address.h:155: ERROR: CHECK( IPAddress("::ffff:127.").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

./tests/core/io/test_ip_address.h:156: ERROR: CHECK( IPAddress("::ffff:").is_valid() == false ) is NOT correct!
  values: CHECK( true == false )

===============================================================================
./tests/core/io/test_ip_address.h:164:
TEST CASE:  [IPAddress] IPv6 Parsing

./tests/core/io/test_ip_address.h:198: ERROR: CHECK( test_ip("::ffff:127.0.0.1", { 0, 0, 0, 0, 0, 0xFFFF, 0x7F00, 1 }) ) is NOT correct!
  values: CHECK( false )

./tests/core/io/test_ip_address.h:199: ERROR: CHECK( test_ip("::FFFF:127.0.0.1", { 0, 0, 0, 0, 0, 0xFFFF, 0x7F00, 1 }) ) is NOT correct!
  values: CHECK( false )

./tests/core/io/test_ip_address.h:200: ERROR: CHECK( test_ip("0::ffff:127.0.0.1", { 0, 0, 0, 0, 0, 0xFFFF, 0x7F00, 1 }) ) is NOT correct!
  values: CHECK( false )

./tests/core/io/test_ip_address.h:201: ERROR: CHECK( test_ip("0:0::ffff:127.0.0.1", { 0, 0, 0, 0, 0, 0xFFFF, 0x7F00, 1 }) ) is NOT correct!
  values: CHECK( false )

./tests/core/io/test_ip_address.h:202: ERROR: CHECK( test_ip("0:0:0::ffff:127.0.0.1", { 0, 0, 0, 0, 0, 0xFFFF, 0x7F00, 1 }) ) is NOT correct!
  values: CHECK( false )

./tests/core/io/test_ip_address.h:203: ERROR: CHECK( test_ip("0:0:0:0::ffff:127.0.0.1", { 0, 0, 0, 0, 0, 0xFFFF, 0x7F00, 1 }) ) is NOT correct!
  values: CHECK( false )

===============================================================================
[doctest] test cases:   5 |  2 passed |  3 failed | 1274 skipped
[doctest] assertions: 110 | 81 passed | 29 failed |
[doctest] Status: FAILURE!
```
  
</details>

### CODE REVIEW

File: core/io/ip_address.cpp [hunk 1]
```diff
@@ -59,103 +59,132 @@ IPAddress::operator String() const {
...
-			n = 10 + (c - 'a');
-		} else if (c >= 'A' && c <= 'F') {
-			n = 10 + (c - 'A');
-		} else if (c == ':') {
-			break;
+	int cur = 0;
+	int shift = -1;
+	for (int i = 0; i < len; i++) {
+		for (int j = i; j < len; j++) {
+			char32_t c = p_string[j];
```
Comment (kiroxas) [inline core/io/ip_address.cpp]: AS you know the index ill always be in bounds, maybe you should cache the ptr from p_string.ptr() before and avoid bound checks here ?

Comment (Faless) [reply core/io/ip_address.cpp]: Absolutely, thank you for spotting that :pray: .

I actually had the original implementation using a `char *` then when I converted it to use `String` I totally forgot about it doing boundary checks in the subscript operator.

Fixed.

File: core/io/ip_address.cpp [hunk 2]
```diff
@@ -192,6 +223,15 @@ void IPAddress::set_ipv6(const uint8_t *p_buf) {
 	}
 }
 
+bool IPAddress::is_valid_ip_address(const String &p_string) {
+	IPAddress addr;
+	if (p_string.find_char(':') > -1) {
```
Comment (AThousandShips) [inline core/io/ip_address.cpp]:
```suggestion
	if (p_string.contains_char(':')) {
```

Comment (Faless) [reply core/io/ip_address.cpp]: Thanks for pointing this out!

That actually made me realize that we were needlessly trying to parse strings that were too long, and that the test coverage was a bit lacking in some regards (not testing both lower level functions).

I've added max length checks, added a few more tests, and expanded them to cover more functions,

File: core/io/ip_address.cpp [hunk 3]
```diff
@@ -59,103 +59,134 @@ IPAddress::operator String() const {
...
-		if (parts[i] == -1) {
-			for (int j = 0; j < parts_extra; j++) {
-				field16[idx++] = 0;
-			}
-			continue;
-		}
-
-		if (part_ipv4 && i == parts_idx - 1) {
-			_parse_ipv4(p_string, parts[i], (uint8_t *)&field16[idx]); // should be the last one
+	// Shift bytes
```
Comment (adamscott) [inline core/io/ip_address.cpp]:
```suggestion
	// Shift bytes.
```

**Review by adamscott — APPROVED** [review]
Seems alright!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
