### PR TITLE
Android: Fix system bar regression

### LINKED ISSUE #108543: Android status bar colours broken in 4.5.beta3 when Immersive Mode is off
### Tested versions

- Reproducible in 4.5.beta3, 4.5.beta2
- Not reproducible in 4.4.1.stable

Device: Google Pixel 6a, Android version 16

### System information

Godot v4.5.beta3 - Windows 11 (build 26100) - Multi-window, 2 monitors - Vulkan (Mobile) - integrated Intel(R) UHD Graphics (Intel Corporation; 31.0.101.2127) - Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 threads) - 15.78 GiB memory

### Issue description

When I run my app on Android with immersive mode off (4.5.beta3), the status bar colours are broken, and I can't find a way to properly override them.

This is what it looks like in 4.4.1.stable:
Image

This is what it looks like in 4.5.beta2 and 4.5.beta3:
Image
The status bar icons are barely legible.

I was able to override the background of status bar to a different colour by providing a custom theme attribute:
key: android:windowBackground
value: @android:color/black

However, I am not able to override the colour of the icons, it is always black.
So this is the best outcome I could achieve:
Image

Can you please help me out to either find a way to override the status bar colours, or return the defaults to what they were before. 

### Steps to reproduce

- Setup your app to be exported for Android
- Set Immersive Mode to be off

### Minimal reproduction project (MRP)

[status-bar-colours-test.4.5.beta-3.zip](https://github.com/user-attachments/files/21195745/status-bar-colours-test.4.5.beta-3.zip)

[status-bar-colours-test.4.4.1.stable.zip](https://github.com/user-attachments/files/21195746/status-bar-colours-test.4.4.1.stable.zip)

### PR DESCRIPTION
**Pull request by syntaxerror247**
Fixes https://github.com/godotengine/godot/issues/108543

This PR adds an export setting `screen/background_color` to change the window background color. 
It also adds logic to check the background color luminance and set the icon appearance accordingly. This means godot would make sure system bar icons are visible on the choosen color.

### CODE REVIEW

File: platform/android/java/lib/src/org/godotengine/godot/Godot.kt [hunk 1]
```diff
@@ -434,6 +434,20 @@ class Godot private constructor(val context: Context) {
...
+		val window = getActivity()?.window ?: return
+		window.decorView.setBackgroundColor(Color.BLACK)
+
+		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
+			val controller = window.insetsController
+			val masks = WindowInsetsController.APPEARANCE_LIGHT_STATUS_BARS or WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS
+			controller?.setSystemBarsAppearance(0, masks)
+		} else {
+			window.decorView.systemUiVisibility = 0
+		}
```
Comment (Alex2782) [inline platform/android/java/lib/src/org/godotengine/godot/Godot.kt]: Looks good on `Android 13`. 

But on `Android 8.1`, the navigation bar becomes bright in `Edge to Edge` mode. _(I found a solution.)_
I'm not entirely sure about `Edge to Edge`. Shouldn't the system bars remain transparent there?

<details><summary>Tests / Screenshots on LG Nexus 5X, Android 8.1</summary>

--------------

`Beta 3` with `Edge to Edge`

Bildschirmfoto 2025-07-13 um 02 09 40

-------------

this PR + `window.navigationBarColor = Color.BLACK`

image

--------------

this PR without `window.navigationBarColor = Color.BLACK` _(the buttons / symbols are difficult to recognize)_

image

</details>

--------

```suggestion
		} else {
			window.decorView.systemUiVisibility = 0
			window.navigationBarColor = Color.BLACK
		}
```

**Review by Alex2782 — CHANGES_REQUESTED** [review]

File: platform/android/java/lib/src/org/godotengine/godot/Godot.kt (hunk 1 above)
Comment (syntaxerror247) [reply platform/android/java/lib/src/org/godotengine/godot/Godot.kt]: Hm.. I can't reproduce it on emulator.

**Comment by syntaxerror247** [comment]
I pushed a new solution which, I think, is much better than previous one. This doesn't set the system bars to black instead checks the background color luminance and set the icon appearance accordingly. This means that any color set by the user using `android:windowBackground`  would be preserved and godot would make sure system bar icons are visible on that color.

Note: This PR should be tested with changes from https://github.com/godotengine/godot/pull/108287

File: platform/android/java/lib/src/org/godotengine/godot/Godot.kt (hunk 1 above)
Comment (syntaxerror247) [reply platform/android/java/lib/src/org/godotengine/godot/Godot.kt]: > I'm not entirely sure about Edge to Edge. Shouldn't the system bars remain transparent there?

Yeah, I've fixed this issue in https://github.com/godotengine/godot/pull/108287

Comment (syntaxerror247) [reply platform/android/java/lib/src/org/godotengine/godot/Godot.kt]: @Alex2782 I've pushed a different solution. Can you test again?

File: platform/android/java/app/src/com/godot/game/GodotApp.java [hunk 2]
```diff
@@ -81,5 +83,8 @@ public void onResume() {
 	public void onGodotMainLoopStarted() {
 		super.onGodotMainLoopStarted();
 		runOnUiThread(updateImmersiveAndEdgeToEdgeModes);
+		runOnUiThread(() -> {
+			Objects.requireNonNull(getGodot()).setSystemBarsAppearance();
```
Comment (Alex2782) [inline platform/android/java/app/src/com/godot/game/GodotApp.java]: This code looks interesting (`Objects.requireNonNull`), never seen it before, but is it intended that `NullPointerException()` is thrown and the app crashes? _(if = null)_

https://stackoverflow.com/questions/45632920/why-should-one-use-objects-requirenonnull

https://docs.oracle.com/javase/10/docs/api/java/util/Objects.html#requireNonNull(T)
> Throws:
[NullPointerException](https://docs.oracle.com/javase/10/docs/api/java/lang/NullPointerException.html) - if obj is null

--------

if not, then better check directly for null and only then execute, like this code

```java 
	private final Runnable updateImmersiveAndEdgeToEdgeModes = () -> {
		Godot godot = getGodot();
		if (godot != null) {
			godot.enableImmersiveMode(godot.isInImmersiveMode(), true);
			godot.enableEdgeToEdge(godot.isInEdgeToEdgeMode(), true);
		}
	};
```

**Review by Alex2782 — COMMENTED** [review]
Test on Android 13, only this PR without #108287

- `Immersive mode`  = `disabled`
- `Edge To Edge` = `disabled`

But the app is still forced in `edge-to-edge` mode. When I try to display the system notifications/functions as in the video, or press the `Home/Task` button and bring the app back, the app is suddenly correct (no edge-to-edge mode).

**EDIT:** 
I was able to reproduce this behavior as in the video with this PR + #108287 (Cherry-pick) in a new local test branch.

https://github.com/user-attachments/assets/f637567b-a04c-4a73-8992-dc401f8e845c

**Comment by syntaxerror247** [comment]
I've converted this to draft for now. Let's first finalize https://github.com/godotengine/godot/pull/108287 . Both PRs are touching window management code so, it's hard to work on in parallel.

**Comment by syntaxerror247** [comment]
> Test on Android 13, only this PR without #108287
> 
> * `Immersive mode`  = `disabled`
> * `Edge To Edge` = `disabled`
> 
> But the app is still forced in `edge-to-edge` mode. When I try to display the system notifications/functions as in the video, or press the `Home/Task` button and bring the app back, the app is suddenly correct (no edge-to-edge mode).
> 
> **EDIT:** I was able to reproduce this behavior as in the video with this PR + #108287 (Cherry-pick) in a new local test branch.

I couldn’t reproduce it on Android 11 or 15. I had pushed a minor fix in #108287 after you tested this PR, which addressed a somewhat similar issue on Android 9. Could you try testing it again now and see if the issue still persists?

File: platform/android/java/app/src/com/godot/game/GodotApp.java [hunk 3]
```diff
@@ -81,5 +81,10 @@ public void onResume() {
 	public void onGodotMainLoopStarted() {
 		super.onGodotMainLoopStarted();
 		runOnUiThread(updateImmersiveAndEdgeToEdgeModes);
+		runOnUiThread(() -> {
+			Godot godot = getGodot();
+			if (godot != null)
+				godot.setSystemBarsAppearance();
+		});
```
Comment (m4gr3d) [inline platform/android/java/app/src/com/godot/game/GodotApp.java]: Can you move this logic into `updateImmersiveAndEdgeToEdgeModes`; feel free to rename that variable as needed.

File: platform/android/java/lib/src/org/godotengine/godot/Godot.kt [hunk 4]
```diff
@@ -448,6 +450,41 @@ class Godot private constructor(val context: Context) {
...
+			val theme = activity.theme
+			return if (theme.resolveAttribute(android.R.attr.windowBackground, typedValue, true)) {
+				if (typedValue.type in TypedValue.TYPE_FIRST_COLOR_INT..TypedValue.TYPE_LAST_COLOR_INT) {
+					typedValue.data
+				} else {
+					null
+				}
+			} else {
+				null
+			}
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/Godot.kt]: Looks like you can collapse those `else` statements:
```
return if (theme.resolveAttribute(android.R.attr.windowBackground, typedValue, true) && typedValue.type in TypedValue.TYPE_FIRST_COLOR_INT..TypedValue.TYPE_LAST_COLOR_INT) {
					typedValue.data
				} else {
					null
				}
```

File: platform/android/java/app/src/com/godot/game/GodotApp.java (hunk 3 above)
Comment (m4gr3d) [reply platform/android/java/app/src/com/godot/game/GodotApp.java]: Also is there a reason you're not calling `setSystemBarsAppearance()` in `onResume()`?

File: platform/android/java/lib/src/org/godotengine/godot/Godot.kt (hunk 4 above)
Comment (syntaxerror247) [reply platform/android/java/lib/src/org/godotengine/godot/Godot.kt]: Yep, Looks like I can :P

File: platform/android/java/app/src/com/godot/game/GodotApp.java (hunk 3 above)
Comment (syntaxerror247) [reply platform/android/java/app/src/com/godot/game/GodotApp.java]: No particular reason. I assumed the system would retain that setting, but I guess, no harm to call it in `onResume()` just to be safe.

**Review by Alex2782 — COMMENTED** [review]
On Samsung Tab S7 Android 13 the bar remains black, last week the old version as in the video worked better.
_(tested export template, Immersive mode = disabled, Edge To Edge = disabled)_

Here some `Log.d` in the function `getWindowBackgroundColor`

```java
07-22 18:57:15.816  6974  6974 D Godot   : getWindowBackgroundColor
07-22 18:57:15.816  6974  6974 D Godot   : background: android.graphics.drawable.GradientDrawable@c6a25f6
07-22 18:57:15.816  6974  6974 D Godot   : is ColorDrawable: false
07-22 18:57:15.816  6974  6974 D Godot   : typedValue.type: 3
07-22 18:57:15.816  6974  6974 D Godot   : typedValue.data: 7592
07-22 18:57:15.817  6974  6974 D Godot   : else null
```

with PR #108287
Bildschirmfoto 2025-07-22 um 19 03 03

**Review by Alex2782 — COMMENTED** [review]
We could also try evaluating `GradientDrawable`. The following code worked on Samsung Tab S7, but I'm not sure if it's all correct.

<details><summary>background is GradientDrawable</summary>

```kotlin

import android.graphics.drawable.GradientDrawable

private fun getWindowBackgroundColor(activity: Activity): Int? {
	val background = activity.window.decorView.background

	return when {
		background is ColorDrawable -> {
			background.color
		}

		background is GradientDrawable -> {
			val solidColor = background.color?.defaultColor
			if (solidColor != null) {
				return solidColor
			}

			val gradientColors = background.colors
			if (gradientColors != null && gradientColors.isNotEmpty()) {
				return gradientColors[0]
			}

			null
		}

		else -> {
			val typedValue = TypedValue()
			val theme = activity.theme

			theme.resolveAttribute(android.R.attr.windowBackground, typedValue, true)

			return if (typedValue.type in TypedValue.TYPE_FIRST_COLOR_INT..TypedValue.TYPE_LAST_COLOR_INT) {
				typedValue.data
			} else {
				null
			}
		}
	}
}

```

</details>


EDIT:  I checked it, looks right to me

```java
07-23 00:06:04.258 16239 16239 D Godot   : getWindowBackgroundColor: -15263977
07-23 00:06:04.259 16239 16239 D Godot   : bgColor HEX: #ff171717
07-23 00:06:04.259 16239 16239 D Godot   : calculateLuminance: 0.008568125618069307
```

image

**Comment by syntaxerror247** [comment]
Evaluating `GradientDrawable` is one option and this code to get color from gradient seems good too.

However, I'm considering a different approach now. I want to add a export setting `root window color` that would set the `android:windowBackground` (Black as default) and we'd make this a reserved attribute. That way we'd already have the background color and we can then set system bar appearance. This approach is simple and ensure that system bar is always visible for godot apps. It would solve the regression and would also be a good enahancement.

@m4gr3d @Alex2782 Thought?

**Comment by Alex2782** [comment]
> However, I'm considering a different approach now. I want to add a export setting `root window color` that would set the `android:windowBackground` (Black as default) and we'd make this a reserved attribute.

Sounds like a better solution. What about Gradle builds? 
I don't know all the details, but from what I've seen, many people use some kind of custom style (at least that's my impression)

I think we'll have to continue evaluating theme/styles, like the current one already does.

-----------

`return if (theme.resolveAttribute(android.R.attr.windowBackground, typedValue, true) && typedValue.type in TypedValue.TYPE_FIRST_COLOR_INT..TypedValue.TYPE_LAST_COLOR_INT)
`

`07-22 18:57:15.816  6974  6974 D Godot   : typedValue.type: 3`

In my case `TYPE_STRING` (I think it was) was determined here (apk export)

**Comment by syntaxerror247** [comment]
> What about Gradle builds?
I don't know all the details, but from what I've seen, many people use some kind of custom style (at least that's my impression)
>
> I think we'll have to continue evaluating theme/styles, like the current one already does.

We'd add  `android:windowBackground` to reserved attribute so folks won't be able to override it using `Custom Theme Attributes` option and `GodotAppMainTheme` is also generated during export so manually overwriting that is also not possible. `root window color` would be only option to change the window background.

We won't need to evaluate the theme because we can get the color directly from export setting and set appearance accordingly.

If user replaces the `GodotAppMainTheme` with a custom style, or set a window background programmatically on Android side, then it's their job to setting the appearance accordingly (as they'd do for a normal android apps) and they should override the `setSystemBarsAppearance` method.

**Comment by syntaxerror247** [comment]
Added an export setting to configure the window background color.

On non-Gradle builds, the color is applied after a slight delay, as it's set during app launch.
On Gradle builds, the color is set in the app theme (android:windowBackground) during export, so there's no delay.

When determining the window background color to set the system bar appearance, logic first checks if the window background is a ColorDrawable and retrieves its color. If it's not a ColorDrawable, it falls back to the color defined in the export setting.

While this may seem redundant, it's intentional. This approach ensures that if the window background color is changed at runtime, Godot will use that updated color when applying system bar appearance during app resume, instead of reverting to the export-time color.

File: platform/android/java/lib/src/org/godotengine/godot/Godot.kt [hunk 5]
```diff
@@ -459,6 +474,27 @@ class Godot private constructor(val context: Context) {
...
+		val background = window.decorView.background
+		return if (background is ColorDrawable) {
+			background.color
+		} else {
+			backgroundColor
+		}
+	}
+
+
+
```
Comment (Alex2782) [inline platform/android/java/lib/src/org/godotengine/godot/Godot.kt]: If it were a C++ file, I think Code Style GH-Action would fail (too many unnecessary line breaks)

**Review by Alex2782 — APPROVED** [review]
It looks good to me, and I like the option to choose the background color. 


<details><summary>some notes (optional)</summary>

--------

Here, with the background color `#b0b0b0`, I would have expected the foreground color to be dark. But it's still recognizable enough.



image



Perhaps the following method would be more suitable, but this can be done in other PRs once we have more feedback from users:

- https://www.w3.org/TR/WCAG21/#contrast-minimum
- http://w3.org/TR/WCAG21/#dfn-contrast-ratio
- https://www.siegemedia.com/contrast-ratio
- https://accessible-colors.com/


<details><summary>Kotlin code</summary>

```kotlin
fun getContrastRatio(foreground: Int, background: Int): Double {
    fun getLuminance(color: Int): Double {
        return ColorUtils.calculateLuminance(color)
    }

    val lum1 = getLuminance(foreground)
    val lum2 = getLuminance(background)

    val brighter = max(lum1, lum2)
    val darker = min(lum1, lum2)

    return (brighter + 0.05) / (darker + 0.05)
}

......

val contrast = getContrastRatio(Color.WHITE, getWindowBackgroundColor(window))

if (contrast < 4.5) {
    // use dark foreground color 
}

```




</details>




</detail>

File: platform/android/java/lib/src/org/godotengine/godot/Godot.kt [hunk 6]
```diff
@@ -459,6 +474,27 @@ class Godot private constructor(val context: Context) {
 	@Keep
 	fun isInEdgeToEdgeMode() = isEdgeToEdge.get()
 
+
```
Comment (Repiteo) [inline platform/android/java/lib/src/org/godotengine/godot/Godot.kt]:
```suggestion
```

File: platform/android/java/lib/src/org/godotengine/godot/Godot.kt [hunk 7]
```diff
@@ -459,6 +474,27 @@ class Godot private constructor(val context: Context) {
...
+		return if (background is ColorDrawable) {
+			background.color
+		} else {
+			backgroundColor
+		}
+	}
+
+
+
 	/**
```
Comment (Repiteo) [inline platform/android/java/lib/src/org/godotengine/godot/Godot.kt]:
```suggestion

	/**
```

**Review by Repiteo — CHANGES_REQUESTED** [review]
Whitespace needs trimming

**Comment by Alex2782** [comment]
> Whitespace needs trimming

Maybe we can use it to check Kotlin files? 

- https://pinterest.github.io/ktlint/latest/
- https://github.com/detekt/detekt

I've always assumed that different standards apply to Kotlin; GHA `Static checks / Code style` have so far only rejected it for C++.

**Review by Repiteo — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

File: platform/android/export/export_plugin.cpp [hunk 8]
```diff
@@ -3099,6 +3102,13 @@ void EditorExportPlatformAndroid::get_command_line_flags(const Ref<EditorExportP
 		command_line_strings.push_back("--edge_to_edge");
 	}
 
+	String background_color = "#" + p_preset->get("screen/background_color").operator Color().to_html(false);
+	if (_is_transparency_allowed(p_preset) && p_preset->get("gradle_build/use_gradle_build")) {
+		background_color = "#00000000";
```
Comment (m4gr3d) [inline platform/android/export/export_plugin.cpp:3107]: @syntaxerror247 What's the reason for overriding the background color here?

Comment (syntaxerror247) [reply platform/android/export/export_plugin.cpp:3107]: For gradle build, in `fix_themes_xml` method, we set the background to transparent instead of the color choosen during export, if `_is_transparency_allowed()`. That's why I'm overriding it to transparent here too as this value would be used as fallback to set the system bar appearance.

Comment (m4gr3d) [reply platform/android/export/export_plugin.cpp:3107]: Make sense, thanks for the clarification!

Can you add a comment there as a reminder.
