### PR TITLE
Fixing tangent and binormal logic

### LINKED ISSUE #16009: Normal maps displayed incorrectly for inbuilt meshes.
Godot version: 3.0 59e83af
OS/device including version:
Windows 10, GF970

Normal map produce wrong results with inbuilt geometry.
crazy_normals
Project:
[crazy_normals.zip](https://github.com/godotengine/godot/files/1657514/crazy_normals.zip)

Steps to reproduce:
Create MeshInstance and set mesh to 'new PlaneMesh' (or quad or box). Create material for it and add normal map. Add light into scene. Normal map will show incorrect results.

### LINKED ISSUE #21961: Cannot apply Normal Map to Sprite3D
**Godot version:**
3.0.2
3.0.6

**OS/device including version:**
Windows 10 Pro 64 bit

**Issue description:**
I have a _Sprite3D_ object with _SpatialMaterial_ applied in _GeometryInstance_ tab. Everything looks good until a normal map is enabled: sprite gets darker and stops reacting to any light sources regardless of normal texture picked (or none):
nmap
However, material is rendered as intended on the preview ball:
nmap
Also same material works fine with plane _MeshInstance_.

**Steps to reproduce:**
Bumped into issue on Godot v3.0.2 (noticed fps drop when sprite entered viewport first time) and reproduced on v3.0.6 by creating a new project with initial settings, adding Sprite3D, adding SpatialMaterial to it and enabling normal map.

**Minimal reproduction project:**
[Sprite3D Normal Map.zip](https://github.com/godotengine/godot/files/2369261/Sprite3D.Normal.Map.zip)

### PR DESCRIPTION
**Pull request by BastiaanOlij**
This fixes tangent and binormal issues for #16009 and #21961 and possibly others.
For both DEA and GLTF import we now invert the binormal, I'm not entirely sure if this is a problem because we reverse the face order, invert the V in UVs or because we swapped from a Z = up to a Y = up and Z is negative axis system.

That all said, as far as I can test normal maps and depth/parallax is now correct:
image

Do note that I get correct results with normal maps generated with a tool like [Normal Map Online](http://cpetry.github.io/NormalMap-Online/) but it looks like other generates flip one or both axis.
Same with the example project from #16009 , using the Normal_DX.png map gives the correct result.
I think we may need to add flip options for normal map imports?

I've altered the demo from 16009 to show off just about all primitive shapes, show off various CSGMesh shapes, show of meshes imported and tangents/binormals generated and importing DEA and GLTF files with tangents/binormals already included.
[crazy_normals_fixed_up.zip](https://github.com/godotengine/godot/files/2591534/crazy_normals_fixed_up.zip)

*Bugsquad edit:* Fixes #16009, fixes #21961.

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
Embedded #23674 in this PR (and corrected the tangent)

File: editor/import/editor_import_collada.cpp [hunk 1]
```diff
@@ -771,7 +771,7 @@ Error ColladaImport::_create_mesh_surfaces(bool p_optimize, Ref<ArrayMesh> &p_me
 
 						int binormal_pos = (binormal_src->stride ? binormal_src->stride : 3) * p.indices[src + binormal_ofs];
 						ERR_FAIL_INDEX_V(binormal_pos, binormal_src->array.size(), ERR_INVALID_DATA);
-						Vector3 binormal = Vector3(binormal_src->array[binormal_pos + 0], binormal_src->array[binormal_pos + 1], binormal_src->array[binormal_pos + 2]);
+						Vector3 binormal = Vector3(-binormal_src->array[binormal_pos + 0], -binormal_src->array[binormal_pos + 1], -binormal_src->array[binormal_pos + 2]); // Due to Godots face order it seems we need to flip our binormal!
```
Comment (Windfisch) [inline editor/import/editor_import_collada.cpp]: This is essentially the same as I've done in my [colladafix2 branch](https://github.com/Windfisch/godot/tree/colladafix2): The corresponding change is: https://github.com/Windfisch/godot/commit/d34a831bf674f6869e17ab1548090aa10a34963e#diff-f4c0a679eb47b23489fb761cc8c98821R781
Given that two people came to the same conclusion, I think this is right.

File: scene/resources/primitive_meshes.cpp [hunk 2]
```diff
@@ -1241,7 +1241,7 @@ void PrismMesh::_create_mesh_array(Array &p_arr) const {
 			/* bottom */
 			points.push_back(Vector3(x, start_pos.y, -z));
 			normals.push_back(Vector3(0.0, -1.0, 0.0));
-			ADD_TANGENT(-1.0, 0.0, 0.0, -1.0);
+			ADD_TANGENT(1.0, 0.0, 0.0, -1.0);
```
Comment (Windfisch) [inline scene/resources/primitive_meshes.cpp]: For Capsule, Cube, Cylinder, Sphere, Prism, PlaneMesh, you're doing essentially the same as https://github.com/godotengine/godot/pull/16096, however in all cases, your fourth component is flipped: `ADD_TANGENT(1.0, 0.0, 0.0, -1.0);` (yours) vs `ADD_TANGENT(1.0, 0.0, 0.0, 1.0);` (theirs).
This results in a tangent space which is rotated by 180 degrees. I haven't found a case yet where this actually makes a difference, especially depth mapping is fine with both ways.
Might be worth a second thought, though.

File: scene/resources/primitive_meshes.cpp [hunk 3]
```diff
@@ -1382,7 +1382,7 @@ void QuadMesh::_create_mesh_array(Array &p_arr) const {
 		tangents.set(i * 4 + 0, 1.0);
 		tangents.set(i * 4 + 1, 0.0);
 		tangents.set(i * 4 + 2, 0.0);
-		tangents.set(i * 4 + 3, 1.0);
+		tangents.set(i * 4 + 3, -1.0);
```
Comment (Windfisch) [inline scene/resources/primitive_meshes.cpp]: You are flipping the tangent also for a QuadMesh, which is the *only* builtin mesh that had correct tangents in vanilla godot. also, #16096 does not flip them: https://github.com/godotengine/godot/blob/3fe771b3eb7abf06c65261c8ab3d9d96e0bbabbe/scene/resources/primitive_meshes.cpp#L1315-L1318

I think your PR is wrong here, I will test this later.

File: editor/import/editor_scene_importer_gltf.cpp [hunk 4]
```diff
@@ -899,7 +899,16 @@ Error EditorSceneImporterGLTF::_parse_meshes(GLTFState &state) {
 				array[Mesh::ARRAY_NORMAL] = _decode_accessor_as_vec3(state, a["NORMAL"], true);
 			}
 			if (a.has("TANGENT")) {
-				array[Mesh::ARRAY_TANGENT] = _decode_accessor_as_floats(state, a["TANGENT"], true);
+				PoolVector<float> tans = _decode_accessor_as_floats(state, a["TANGENT"], true);
```
Comment (Windfisch) [inline editor/import/editor_scene_importer_gltf.cpp]: GLTF, CSG and Sprite3D weren't present in #16096, so I never have reasoned about them. I can't tell whether they are fine or not.

**Review by Windfisch — CHANGES_REQUESTED** [review]
I think, QuadMesh is wrong: you flipped the tangent, while the QuadMesh was the only PrimitiveMesh that already had a working tangent space in vanillla godot.

Other than that, your PrimitiveMesh changes create a tangent space 180 deg rotated than #16096, but I can't tell if that's wrong or right.

The Collada importer looks fine.

**Comment by BastiaanOlij** [comment]
@Windfisch , I flipped those on purpose, check out the example library i supplied. The problem is that with the way it was the bitangent/binormals works only with the flipped OpenGL normal map BUT is the wrong way around for depth/parallax so you have to flip it back with material settings.

With the changes as I've made them now the tangents and bitangents/binormals are the right way around for both the depth/parallax and the DX version of the normal map from the original poster as well as correct for normal maps I've so far seen with most assets.

File: editor/import/editor_import_collada.cpp (hunk 1 above)
Comment (BastiaanOlij) [reply editor/import/editor_import_collada.cpp]: As mentioned, keep in mind that to counter the problems in the material setting the depth/parallax had the "flip binormal" setting turned ON. This is why QuadMesh looked correct even though it isn't. All these changes are based on not having to flip the binormal

**Comment by BastiaanOlij** [comment]
Note, last commit just changed the default for flip binormal to off:
image

This defaulted to true when it was introduced because that was the only way to correctly apply depth to a bunch of things, but not all things.

All the changes I've done are based on these tickboxes being off.

**Comment by CptPotato** [comment]
This maybe doesn't belong here but one little trick I like to do is calculate tangent/binormal on the fly in the pixelshader, saving some space in the vertex buffer and producing correct normals even with mirrored UVs (I don't remember where I got the snippet from):
```
float3x3 calcWsCotangentFrame(float3 wsNormal, float3 wsInvViewDir, float2 tsCoord)
{
	// get edge vectors of the pixel triangle
	float3 dp1 = ddx(wsInvViewDir);
	float3 dp2 = ddy(wsInvViewDir);
	float2 duv1 = ddx(tsCoord);
	float2 duv2 = ddy(tsCoord);
	
	// solve the linear system
	float3 dp2perp = cross(dp2, wsNormal);
	float3 dp1perp = cross(wsNormal, dp1);
	float3 T = dp2perp * duv1.x + dp1perp * duv2.x;
	float3 B = dp2perp * duv1.y + dp1perp * duv2.y;
	
	// construct and return a scale-invariant cotangent frame
	float invmax = rsqrt(max(dot(T, T), dot(B, B)));
	
	return float3x3(T * invmax, B * invmax, wsNormal);
}

...
Surface.WorldNormal = mul(NormalMap * 2.0f - 1.0f, calcWsCotangentFrame(normalize(Input.Normal), -Input.ViewDir, Input.UV));
```
One thing to note, though, is that this doesn't work when the UVs are on the same position (due to the ddx/ddy math).
I'm also not sure if this produces 100% correct normals.

**Comment by BastiaanOlij** [comment]
@CptPotato memory comes cheap, keeping your GPU busy doesn't. But I can see where minimizing memory uses takes priority if you're on mobile or something like that :)

**Comment by BastiaanOlij** [comment]
@reduz talked to Fracteed today, exchanged some builds and some project files. He seems pretty happy with the changes.

I've also followed Blender Gurus tutorial on baking normal maps from high poly models onto a low poly models in Blender. Then exported that to Godot, looks like it takes the normal maps as is. I haven't tried or looked at the new Blender to Godot scene exporter to see if anything needs to change there. I just used DAE.

**Comment by akien-mga** [comment]
Maybe @Jason0214 would want to check that the ESCN exporter provides the proper input for the changes in this PR?

**Comment by Jason0214** [comment]
@akien-mga sure, I will have a check on it

**Comment by akien-mga** [comment]
Thanks!

**Comment by Windfisch** [comment]
Thanks! Now that this is merged, I think we can close #16096 and #21221, too.

**Comment by EzraT** [comment]
Thank you!
