### PR TITLE
[Net] Change HTTPRequest timeout type to double.

### LINKED ISSUE #44258: HttpRequest.timeout property has the wrong type
**Godot version:**
3.24b3 and master

**Issue description:**
If I understand the code correctly, the `HttpRequest` uses the timeout to start a `Timer`:
https://github.com/godotengine/godot/pull/30315

The Timer expects seconds: float as parameter. Therefore, `HttpRequest.timeout` should be a `float` as well but is of type `int` currently.

**Suggested fix**
Change HttpRequest.timeout to float and document it. 

Doc draft
> timeout
> Maximum time in seconds for the whole request. The maximum time to connect to the server is additionally limited by the project settings: network/limits/tcp/connect_timeout_seconds.

> RESULT_TIMEOUT = 12 -- Request didn't complete in time, see timeout.

**PR**
I could make the proposed changes and open a PR if desired.

### PR DESCRIPTION
**Pull request by Faless**
For consistency with the Timer class and general time representation inside the engine.

The step is left to `0.1` since I think that's fine-grained enough.
The "high" value is set to `3600` but allows for greater values.

Fixes #44258 .

### CODE REVIEW

**Review by CoolManE4 — APPROVED** [review]
I think this is a good change, timeouts only having integers sounds like a bad idea, allowing for any value sounds great!

File: scene/main/http_request.cpp [hunk 1]
```diff
@@ -615,7 +615,7 @@ void HTTPRequest::_bind_methods() {
 	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "accept_gzip"), "set_accept_gzip", "is_accepting_gzip");
 	ADD_PROPERTY(PropertyInfo(Variant::INT, "body_size_limit", PROPERTY_HINT_RANGE, "-1,2000000000"), "set_body_size_limit", "get_body_size_limit");
 	ADD_PROPERTY(PropertyInfo(Variant::INT, "max_redirects", PROPERTY_HINT_RANGE, "-1,64"), "set_max_redirects", "get_max_redirects");
-	ADD_PROPERTY(PropertyInfo(Variant::INT, "timeout", PROPERTY_HINT_RANGE, "0,86400"), "set_timeout", "get_timeout");
+	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "timeout", PROPERTY_HINT_RANGE, "0,86400,0.1"), "set_timeout", "get_timeout");
```
Comment (akien-mga) [inline scene/main/http_request.cpp:618]: Since there's no need for a hard max, you could make the hint's max maybe more reasonable (3600?) and add `,or_greater` so folks can still type something higher if they really want to.

Comment (Faless) [reply scene/main/http_request.cpp]: Done, also fixed the commit message and title so it's clearer.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
