### PR TITLE
Fix bugs of copying scene root node or pasting node as scene root

### LINKED ISSUE #81507: Crash when click "paste  from clipboad"
### Godot version

4.2.dev

### System information

Godot v4.2.dev (fc99492d3) - Arch Linux #1 SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:38:14 +0000 - Wayland - Vulkan (Forward+) - dedicated Intel(R) Arc(tm) A730M Graphics (DG2) () - 12th Gen Intel(R) Core(TM) i7-12700H (20 Threads)

### Issue description

Hello! I'm new to godot engine.

I just follow the First3D game toturial, when it's time to create another scene (2nd section: https://docs.godotengine.org/en/latest/getting_started/first_3d_game/02.player_input.html). 

I use `ctrl+x` to clip node, and create anothre scene. There was a `Paste from clipboad` button. Then I clicked, the editor was crashed.

I tried `ctrl+c`, it still. Seems will crash when do past operation.

### Steps to reproduce

Copy or clicp some nodes, and click `pasted from clipboard button` in another scene.

The console logs:

```log
→  godot:(godot) $ godot.linuxbsd.editor.x86_64
Godot Engine v4.2.dev.custom_build.fc99492d3 - https://godotengine.org
WARNING: XOpenIM failed
     at: DisplayServerX11 (platform/linuxbsd/x11/display_server_x11.cpp:5695)
WARNING: XCreateIC couldn't create wd.xic
     at: _create_window (platform/linuxbsd/x11/display_server_x11.cpp:5323)
OpenGL API 4.6 (Core Profile) Mesa 23.1.6-arch1.4 - Compatibility - Using Device: Intel - Mesa Intel(R) Graphics (ADL GT2)

Editing project: /home/nono/godot_projects/squash_the_creeps_start_1.1.0
Godot Engine v4.2.dev.custom_build.fc99492d3 - https://godotengine.org
WARNING: XOpenIM failed
     at: DisplayServerX11 (platform/linuxbsd/x11/display_server_x11.cpp:5695)
WARNING: XCreateIC couldn't create wd.xic
     at: _create_window (platform/linuxbsd/x11/display_server_x11.cpp:5323)
Vulkan API 1.3.246 - Forward+ - Using Vulkan Device #1: Intel - Intel(R) Arc(tm) A730M Graphics (DG2)

→  godot:(godot) $ WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:63)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.dev.custom_build (fc99492d3066098e938449b10e02f8e01d07e2d1)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x3e710) [0x7f859f83e710] (??:0)
[2] /apt/godot/bin/godot.linuxbsd.editor.x86_64(+0x447f230) [0x56540599e230] (??:0)
[3] /apt/godot/bin/godot.linuxbsd.editor.x86_64(+0x2600760) [0x565403b1f760] (??:0)
[4] /apt/godot/bin/godot.linuxbsd.editor.x86_64(+0x1a12a63) [0x565402f31a63] (??:0)
[5] /apt/godot/bin/godot.linuxbsd.editor.x86_64(+0x1a13b08) [0x565402f32b08] (??:0)
[6] /apt/godot/bin/godot.linuxbsd.editor.x86_64(+0x418b5cb) [0x5654056aa5cb] (??:0)
[7] /apt/godot/bin/godot.linuxbsd.editor.x86_64(+0x4432c67) [0x565405951c67] (??:0)
[8] /apt/godot/bin/godot.linuxbsd.editor.x86_64(+0x26eff9f) [0x565403c0ef9f] (??:0)
[9] /apt/godot/bin/godot.linuxbsd.editor.x86_64(+0x26f0ce3) [0x565403c0fce3] (??:0)
[10] /apt/godot/bin/godot.linuxbsd.editor.x86_64(+0x26f1086) [0x565403c10086] (??:0)
[11] /apt/godot/bin/godot.linuxbsd.editor.x86_64(+0x2678230) [0x565403b97230] (??:0)
[12] /apt/godot/bin/godot.linuxbsd.editor.x86_64(+0x2681640) [0x565403ba0640] (??:0)
[13] /apt/godot/bin/godot.linuxbsd.editor.x86_64(+0x2698666) [0x565403bb7666] (??:0)
[14] /apt/godot/bin/godot.linuxbsd.editor.x86_64(+0x26d89e5) [0x565403bf79e5] (??:0)
[15] /apt/godot/bin/godot.linuxbsd.editor.x86_64(+0x57532f) [0x565401a9432f] (??:0)
[16] /apt/godot/bin/godot.linuxbsd.editor.x86_64(+0x4125a3f) [0x565405644a3f] (??:0)
[17] /apt/godot/bin/godot.linuxbsd.editor.x86_64(+0x412841d) [0x56540564741d] (??:0)
[18] /apt/godot/bin/godot.linuxbsd.editor.x86_64(+0x57693b) [0x565401a9593b] (??:0)
[19] /apt/godot/bin/godot.linuxbsd.editor.x86_64(+0x550b00) [0x565401a6fb00] (??:0)
[20] /apt/godot/bin/godot.linuxbsd.editor.x86_64(+0x543898) [0x565401a62898] (??:0)
[21] /usr/lib/libc.so.6(+0x27cd0) [0x7f859f827cd0] (??:0)
[22] /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f859f827d8a] (??:0)
[23] /apt/godot/bin/godot.linuxbsd.editor.x86_64(+0x54e115) [0x565401a6d115] (??:0)
-- END OF BACKTRACE --
================================================================

```

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Rindbee**
Fix crash when pasting a node as a new scene root. 
Fix owner was not set correctly when copying scene root node from unsaved scene.

The owner of the root node is `nullptr`, which was ignored before.

*Bugsquad edit:* Fixes #81507

### CODE REVIEW

File: editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -3394,7 +3394,11 @@ List<Node *> SceneTreeDock::paste_nodes(bool p_paste_as_sibling) {
 	}
 
 	EditorUndoRedoManager *ur = EditorUndoRedoManager::get_singleton();
-	ur->create_action(vformat(p_paste_as_sibling ? TTR("Paste Node(s) as Sibling of %s") : TTR("Paste Node(s) as Child of %s"), paste_parent->get_name()), UndoRedo::MERGE_DISABLE, EditorNode::get_singleton()->get_edited_scene());
+	if (paste_parent) {
+		ur->create_action(vformat(p_paste_as_sibling ? TTR("Paste Node(s) as Sibling of %s") : TTR("Paste Node(s) as Child of %s"), paste_parent->get_name()), UndoRedo::MERGE_DISABLE, edited_scene);
+	} else {
+		ur->create_action(TTR("Paste Node(s) as the Root of this scene"), UndoRedo::MERGE_DISABLE, edited_scene);
```
Comment (akien-mga) [inline editor/scene_tree_dock.cpp:3400]:
```suggestion
		ur->create_action(TTR("Paste Node(s) as the Root of This Scene"), UndoRedo::MERGE_DISABLE, edited_scene);
```
As much as I dislike this style, we use Title Case for UndoRedo actions.

File: editor/scene_tree_dock.cpp [hunk 2]
```diff
@@ -3394,7 +3394,11 @@ List<Node *> SceneTreeDock::paste_nodes(bool p_paste_as_sibling) {
 	}
 
 	EditorUndoRedoManager *ur = EditorUndoRedoManager::get_singleton();
-	ur->create_action(vformat(p_paste_as_sibling ? TTR("Paste Node(s) as Sibling of %s") : TTR("Paste Node(s) as Child of %s"), paste_parent->get_name()), UndoRedo::MERGE_DISABLE, EditorNode::get_singleton()->get_edited_scene());
+	if (paste_parent) {
+		ur->create_action(vformat(p_paste_as_sibling ? TTR("Paste Node(s) as Sibling of %s") : TTR("Paste Node(s) as Child of %s"), paste_parent->get_name()), UndoRedo::MERGE_DISABLE, edited_scene);
+	} else {
+		ur->create_action(TTR("Paste Node(s) as the Root of This Scene"), UndoRedo::MERGE_DISABLE, edited_scene);
```
Comment (timothyqiu) [inline editor/scene_tree_dock.cpp:3400]:
```suggestion
		ur->create_action(TTR("Paste Node(s) as Root"), UndoRedo::MERGE_DISABLE, edited_scene);
```

"This Scene" does not make sense as the string will be shown in the action log (printed to Output).

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
