### PR TITLE
Physics interpolation (3D)

### LINKED ISSUE #2753: Add physics step interpolation in 3D (implemented in 2D since 4.3)
### Describe the project you are working on
Godot
### Describe the problem or limitation you are having in your project

The following are common scenarios where users often find trouble in Godot:

* When using monitors with high refresh rate, code that depends on physics remains fixed, does not interpolate. This results in these to have less frame rate and, in the worst case, may lead to jitter.
* When working on multiplayer games, in order to send less information, games often run at a lower tick rate (say 10 or 15fps) in order to maximize bandwidth. When using dedicated server hosting, this also allows to reduce the game CPU usage. This requires a more coarse interpolation.
* In mobile games, running at a lower tick rate also helps reduce CPU usage, but this again requires better interpolation.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Interpolation of code that runs in the physics step is generally desired, but implementing this is not easy. The main limitation is that, when using interpolation, one must discern between motion and teleporting. Failure to specify this will result in the wrong behavior. 

Additionally, "automating" things too much (make everything interpolation by default) can also be troublesome and lead to unexpected results.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

After through analysis of the use cases, it is clear that the places where actual interpolation is desired are as follows:

* **Rigid Bodies**. Their motion (when coming from the physics server) is always interpolated.
* **KinematicBody** move_and_slide. When using this function, physics interpolation is always expected to happen.
* Physics objects moved via **AnimationPlayer** (as an example, a moving platform), requires animation to operate in the physics tick.
* Character animation with **Root Motion**. This is a bit of a more complex case, because animation has no problem being processed in the regular idle tick, but the physics tick is currently required for root motion.
* For some reason, moving something via code in the physics tick that may require interpolation (though this is rare).

With this in mind, we can probably do some engine changes to make this process more or less transparent to the use. This would begin by implementing two new methods:
```
Node3D::set_transform_interpolated(const Transform& p_transform)
CanvasItem::set_transform_interpolated(const Transform2D& p_transform)
```
(we can also add translate interpolate, rotate interpolate and scale interpolate, which would call this method).

Calling these methods outside of the physics ticks will result in an error (in case user misunderstand what these are for).

In any case, calling these will work not only on the current node but also on the sub-tree, so motion of children nodes will also be interpolated. Basically, all these will call set_transform for RenderingServer 3D and 2D instances with an extra flag telling them that its interpolated, then the RenderingServer will internally perform the interpolation. Additionally, Camera3D and Camera2D will have this method too in the rendering server, since their motion can be interpolated.

The idea is that move_and_slide, RigidBody, etc. will internally all use this method so by default the user does not need to do anything and everything will just work. Camera2D and Camera3D are generally children of the character in Godot, so they will naturally know when their transform was interpolated, for which this requires no changes from the user.

So, yes, the idea is that this is implemented as transparent and possible, so existing games don't need to call the interpolated transform, and games just work, and complexity to develop by having to discern between motion and teleport does not happen.

#### FAQ

**Q:** So, I can interpolate manually by calling set_interpolated_transform, but I want to teleport an object, how do I do this?
**A:**  By default nothing is interpolated except the cases mentioned above, so setting position manually is equivalent to teleporting.

**Q:** Does this solve jitter in high refresh rate monitors?
**A:** While this mostly works now, this new implementation will out of the box improve the quality and physics motion in high refresh rate monitors.

**Q:** Does using this have known shortcomings?
**A:** Traditionally, the physics steps happens left often than the refresh, which makes it have a small amount of latency, so using the new position as target interpolation will add a physics frame of latency. This is unavoidable. The alternative would be to instead set a linear and angular velocity, but when running your game at low physics FPS (for networking or saving mobile GPU), overshooting becomes visible, so its not viable in this case.

**Q:** Interpolation is done in the RenderingServer, why not in the node?
**A:**: This is desired for performance, its much cheaper to do the interpolation in the rendering server. The only shortcoming is that, in 3D, interpolation happens in global space rather in local space, so objects rotating around a pivot will introduce some motion aliasing (mostly noticeable in 3D games with very lock physics FPS. In 2D pivot information is retained in the server, so this is not a problem). That said, this should not be a big problem, as when running at low physics tick rate, motion aliasing is present almost everywhere. If you use low physics FPS you should be aware of its effects.

**Q:** Will cubic/hermite/etc interpolation be supported?
**A:** These interpolations are troublesome in many ways. Mostly because when rotating, velocity is not constant (objects can accelerate/decelerate), and trajectories can easily overshoot (go past, then go back). Additionally as an extra sample is needed, an extra physics frame of lag is added. So, in general this will most likely not be supported.

**Q:** Will I need to change my game too much to take advantage of it?
**A:** I believe with the proposed changes, most games should be able to take advantage of this out of the box.

### Is there a reason why this should be core and not an add-on in the asset library?

There are some scripts to do this, but its clearly not ideal, needs to be core.

### LINKED ISSUE #89846: Physics interpolation is not implemented for 3D
### Tested versions

Reproducible in: 4.0-alpha1 - 4.3.dev5
Not reproducible in: 3.5-beta2 - 3.6-beta4

### System information

Godot v4.3.dev (99ff024f7) - Ubuntu 22.04.4 LTS 22.04 - X11 - GLES3 (Compatibility) - NVIDIA GeForce RTX 2060 with Max-Q Design - AMD Ryzen 9 4900HS with Radeon Graphics (16 Threads)

### Issue description

The project setting `physics/common/physics_interpolation` and the node property `physics_interpolation_mode` have no effect on 3D nodes such as physics bodies moved in `_physics_process`.

I could use an addon like https://github.com/lawnjelly/smoothing-addon/tree/4.x, but I would prefer a built-in solution.

### Steps to reproduce

1. Run the attached MRP which has its physics tick rate set to 20 ticks per second and physics interpolation enabled.
2. Notice the 3D scene does not look smooth.

### Minimal reproduction project (MRP)

[physics-interpolation-3d-test.zip](https://github.com/godotengine/godot/files/14734983/physics-interpolation-3d-test.zip)

### PR DESCRIPTION
**Pull request by rburing**
Adds 3D physics interpolation to the rendering server, based on @lawnjelly's

- https://github.com/godotengine/godot/pull/52846
- https://github.com/godotengine/godot/pull/60147

This PR does not yet include support for multimeshes (https://github.com/godotengine/godot/pull/91818) or particles.

https://github.com/godotengine/godot/assets/229837/57261451-ecab-43c4-b060-77d5ed697d68

To-do:

- [x] Make it compile.
- [x] Make it work.
- [x] Bind some `RenderingServer` methods and add their documentation.
- [x] Include more follow-up fixes/changes that came after the initial PR.
- [x] Test more extensively.

This PR is sponsored by My Spare Time™.

- *Production edit: This closes https://github.com/godotengine/godot/issues/89846 and
closes https://github.com/godotengine/godot-proposals/issues/2753.*

### CODE REVIEW

**Comment by Calinou** [comment]
Some early testing with physics ticks set to 10 Hz and physics interpolation enabled in the project settings:

It works in Truck Town, but wheels act wonky when the car moves fast enough (due to the wheels spinning too fast for a single physics ticks to handle). Also, the FOV change based on speed isn't aware of interpolation so it looks stuttery:

https://github.com/godotengine/godot/assets/180032/3e048637-8dc4-4e59-ae9b-f7f7c2f5376b

Here it is without the FOV change:

https://github.com/godotengine/godot/assets/180032/ee466a15-f85b-40d4-b933-90006ade7e19

Interpolation doesn't seem to work in Platformer 3D and Kinematic Character though:

https://github.com/godotengine/godot/assets/180032/7912189d-cc8c-435f-9807-fd2f94e67e0b


https://github.com/godotengine/godot/assets/180032/2a4c7d53-95db-484c-906a-4cd52bde9d4c

**Comment by rburing** [comment]
This now includes all the follow-up fixes/changes, so it is ready for (re-)testing and review.

**Comment by SpockBauru** [comment]
Hello, I downloaded the artifact and made a test scene with a car. Here is the scene: 
[physics-interpolation-test.zip](https://github.com/godotengine/godot/files/15462915/physics-interpolation-test.zip)

Testing with physics ticks set to 15 Hz, the car handling seems to behave the same with physics interpolation on and off, but the wheels shows in a strange way:

https://github.com/godotengine/godot/assets/67930504/e7363520-8d5f-42fe-bcb4-60ac87656121

**Comment by lawnjelly** [comment]
There seems some confusion here:

Wheels, helicopters and fast rotating objects cannot easily be natively handled by physics interpolation. I mentioned it here (and several other places if I remember right), although it may not be in the docs yet:

https://github.com/godotengine/godot/pull/52846#issuecomment-979811468

The problem is that in the `VisualServer` the only information you have for rotation is a basis, which is effectively capped between e.g. 0 and 360 degrees.  The interpolation can only assume a shortest arc between the two most recent samples, e.g. 0-40, 170-190, 350-20 etc.

The problem is that if an object moves more than 180 degrees in one tick, the interpolation will be wrong:

Wheel moves 0-190, the interpolation will be from 190-360 (because that is the shortest arc), i.e. the interpolation will rotate in the opposite direction. You can't use intelligence to decide that from the previous move it is _likely_ to move from 0-190, because, well it _could_ be moving in reality from 190-360, and in some circumstances the intelligent version would be wrong.

So for fast rotating objects you either have to up the tick rate, or turn off physics interpolation for that object and handle it manually on the client side (rather than server). It is possible the vehicle wheel class could be modified to handle this client side.

This has already come up in users games, and they have taken the approach to switch off (using `physics_interpolation_mode`) and handle it manually.

You will probably need to use `get_global_transform_interpolated()` to get the wheels to line up to the interpolated car body (else the wheel positions will not be interpolated, and will lead the car).

**Comment by passivestar** [comment]
So if an explosive force sends a box rotating quickly you'll see interpolation artifacts? Doesn't it mean that you can never be sure and will have to go back to manually interpolating all unconstrained rigid bodies if you want reliable results? Could angular velocities be taken into account when interpolating maybe?

**Comment by lawnjelly** [comment]
> So if an explosive force sends a box rotating quickly you'll see interpolation artifacts? Doesn't it mean that you can never be sure and will have to go back to manually interpolating all unconstrained rigid bodies if you want reliable results? Could angular velocities be taken into account when interpolating maybe?

Yes, ideally it would be nice to modify the physics / render server to be able to send across something like a delta so we could deal with this problem correctly. The current situation is due to historical design, which didn't foresee physics interpolation.

**Comment by Jamsers** [comment]
>It took a lot of lobbying / convincing and politics to get physics interpolation... as time has gone on the community has learned that this is not a fringe feature, but essential for most games

I am horrified, but not suprised 😐

**Comment by Calinou** [comment]
I gave the latest iteration of this PR a try, here are my findings:

- Interpolation works great on the TPS demo, Platformer 3D and Kinematic Character demos now.
- Movie Maker mode works correctly when physics interpolation is enabled (it's expected, I checked just to make sure). Adjusting time scale while the project is running also keeps physics interpolation functional.

### Is spinning VehicleWheel shrinking a problem at 60 ticks per second?

Unfortunately, it's still an issue at 60 ticks per second, even at moderate speeds (< 100 km/h). It's noticeable enough that even on 60 FPS footage with the game running at 120 FPS, it can still be seen. (On this particular example, this is because I used ShareX for recording, which isn't 100% perfect in terms of frame pacing like Movie Maker mode would be.)

It might be worth looking into a client-side solution (i.e. a solution implemented directly in VehicleWheel3D, where the node itself has interpolation disabled but interpolation is performed in the node). I haven't checked if VehicleWheel2D suffers from this issue yet.

https://github.com/godotengine/godot/assets/180032/d6bba9b2-160a-4133-bf01-313076760e48

### Are sudden position/rotation changes (e.g. caused by explosions that impact rigid bodies) a problem?

From a quick test, they don't appear to be a problem, even at very low tick rates (like 10 TPS):

#### Bouncing cylinders

https://github.com/godotengine/godot/assets/180032/9aa8100f-af05-4852-b102-60884b4d7baf

Changing tick rate during the simulation doesn't incur a noticeable hitch, as long as the change is smooth (and not a sudden change like 240 -> 10 or the other way around):

https://github.com/godotengine/godot/assets/180032/154bc41f-d585-4298-ae0c-31014b3dd889

https://github.com/godotengine/godot/assets/180032/bba4c76e-cd15-4bf5-bc22-b14a0692e904

### Boxes explosion

*Recorded with Movie Maker mode.*

https://github.com/godotengine/godot/assets/180032/369160e1-96e3-4285-b618-e11d95b573b1

https://github.com/godotengine/godot/assets/180032/5bc5496b-ebf7-4cb9-99de-13d380d6bace

**Testing projects:**

- [test-physics-interpolation-cylinders.zip](https://github.com/godotengine/godot/files/15492492/test-physics-interpolation-cylinders.zip)
- [test-physics-interpolation-boxes.zip](https://github.com/godotengine/godot/files/15492493/test-physics-interpolation-boxes.zip)

**Comment by SheepCommander** [comment]
Hey I just tested it on a certain [personal project](https://github.com/Jonn-of-Hano/Fumo-Shooter-Open/tree/4.3-Interpolation-test) and it works great! ..Almost.

For some reason at one point it crashed the game and I'm not sure why. When I checked the editor this was the only error related to Interpolation. There weren't any red errors related to it.

image

15 TPS Interpolation + Crash at end:

https://github.com/godotengine/godot/assets/66646514/b7cbb17a-fc83-4e88-bfa8-dd79ed8d6ea5

**Comment by SheepCommander** [comment]
Sorry that this isn't very helpful right now, I'll try to be a lot more helpful tomorrow. I'll appreciate any ideas/comments on what I should do to troubleshoot this!

File: scene/3d/node_3d.cpp [hunk 1]
```diff
@@ -341,6 +349,112 @@ Transform3D Node3D::get_transform() const {
...
+		SceneTree *tree = get_tree();
+		if (tree && _client_physics_interpolation_node_3d_list.in_list()) {
+			tree->client_physics_interpolation_remove_node_3d(&_client_physics_interpolation_node_3d_list);
+		}
+	}
+	_set_physics_interpolated_client_side(false);
+}
+
+Transform3D Node3D::_get_global_transform_interpolated(real_t p_interpolation_fraction) {
+	ERR_FAIL_COND_V(is_inside_tree(), Transform3D());
```
Comment (matmas) [inline scene/3d/node_3d.cpp:403]: Is this correct? Nodes can't be inside scene tree when calling `get_global_transform_interpolated()`?

**Comment by SheepCommander** [comment]
I tested it again with the Console open this time.

image

[Full log: godot.log](https://github.com/user-attachments/files/15524806/godot.log)

The final error before crashing seems to be 
```
USER ERROR: FATAL: Index p_index = 0 is out of bounds (count = 0).
   at: LocalVector<int,unsigned int,0,0>::operator [] (.\core/templates/local_vector.h:173)
```

**Comment by SheepCommander** [comment]
I found the log for the crash in my [previous reply](https://github.com/godotengine/godot/pull/92391#issuecomment-2141361744), and I'm a bit confused?

<details>  <summary>In that previous instance there is _not_ any fatal error before crashing, it just suddenly crashes.</summary>

```
USER WARNING: Target object freed before starting, aborting Tweener.
   at: PropertyTweener::start (scene\animation\tween.cpp:550)

================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.3.beta.custom_build (36dcc8382955ecf5ab981bafa6df7223039e5f56)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] <couldn't map PC to fn name>
[4] <couldn't map PC to fn name>
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] <couldn't map PC to fn name>
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
[13] <couldn't map PC to fn name>
[14] <couldn't map PC to fn name>
[15] <couldn't map PC to fn name>
[16] <couldn't map PC to fn name>
[17] <couldn't map PC to fn name>
[18] <couldn't map PC to fn name>
[19] <couldn't map PC to fn name>
[20] <couldn't map PC to fn name>
[21] <couldn't map PC to fn name>
[22] <couldn't map PC to fn name>
[23] <couldn't map PC to fn name>
[24] <couldn't map PC to fn name>
-- END OF BACKTRACE --
================================================================
```

</details>

Full log here: [godot2024-05-31T00.00.15.log](https://github.com/user-attachments/files/15524877/godot2024-05-31T00.00.15.log)

File: scene/3d/node_3d.cpp [hunk 2]
```diff
@@ -341,6 +349,112 @@ Transform3D Node3D::get_transform() const {
...
+	// We use some arbitrary timeout here, but this could potentially be user defined.
+
+	// Note: This timeout has to be larger than the number of ticks in a frame, otherwise the interpolated
+	// data will stop flowing before the next frame is drawn. This should only be relevant at high tick rates.
+	// We could alternatively do this by frames rather than ticks and avoid this problem, but then the behavior
+	// would be machine dependent.
+	data.client_physics_interpolation_data->timeout_physics_tick = Engine::get_singleton()->get_physics_frames() + 256;
+
+	// Make sure data is up to date.
+	update_client_physics_interpolation_data();
```
Comment (matmas) [inline scene/3d/node_3d.cpp:427]: This seems to be called twice per process frame - once here and other time due to calling `tree->client_physics_interpolation_add_node_3d(...)` at the end of this function. Since `update_client_physics_interpolation_data()` is not idempotent the variables `global_xform_curr` and `global_xform_curr` will end up having same value which results this function returning transforms that are not interpolated as `(a + (b - a) * f` equals `a` when `a == b`.

File: scene/3d/node_3d.cpp (hunk 1 above)
Comment (lawnjelly) [reply scene/3d/node_3d.cpp:403]: This is indeed incorrect, in 3.x it is (more :grin: ) correct:
```
ERR_FAIL_NULL_V(is_inside_tree(), Transform());
```

It should really be:
```
ERR_FAIL_COND_V(!is_inside_tree(), Transform3D());
```
I'm presuming that in trying to correct my wrong macro for 4.x this error crept in.

File: servers/rendering/renderer_scene_cull.cpp [hunk 3]
```diff
@@ -924,8 +1003,58 @@ void RendererSceneCull::instance_set_transform(RID p_instance, const Transform3D
 	Instance *instance = instance_owner.get_or_null(p_instance);
 	ERR_FAIL_NULL(instance);
 
-	if (instance->transform == p_transform) {
-		return; //must be checked to avoid worst evil
+	if (!(_interpolation_data.interpolation_enabled && instance->interpolated) || !instance->scenario) {
```
Comment (AThousandShips) [inline servers/rendering/renderer_scene_cull.cpp:1006]:
```suggestion
	if (!_interpolation_data.interpolation_enabled || !instance->interpolated || !instance->scenario) {
```
Equivalent but more readable

File: servers/rendering/renderer_scene_cull.cpp [hunk 4]
```diff
@@ -924,8 +1003,58 @@ void RendererSceneCull::instance_set_transform(RID p_instance, const Transform3D
...
+			const Vector3 &v = i < 3 ? p_transform.basis.rows[i] : p_transform.origin;
+			ERR_FAIL_COND(!v.is_finite());
+		}
+
+#endif
+		instance->transform = p_transform;
+		_instance_queue_update(instance, true);
+
+#if defined(DEBUG_ENABLED) && defined(TOOLS_ENABLED)
+		if ((_interpolation_data.interpolation_enabled && !instance->interpolated) && (Engine::get_singleton()->is_in_physics_frame())) {
```
Comment (AThousandShips) [inline servers/rendering/renderer_scene_cull.cpp:1023]:
```suggestion
		if (_interpolation_data.interpolation_enabled && !instance->interpolated && Engine::get_singleton()->is_in_physics_frame()) {
```

File: scene/3d/node_3d.cpp (hunk 2 above)
Comment (AThousandShips) [reply scene/3d/node_3d.cpp:427]: Yes but see the method, it doesn't update the previous if it's on the same tick, right?

File: servers/rendering/renderer_scene_cull.cpp [hunk 5]
```diff
@@ -4240,6 +4470,172 @@ void RendererSceneCull::set_scene_render(RendererSceneRender *p_scene_render) {
...
+void RendererSceneCull::update_interpolation_tick(bool p_process) {
+	// TODO (MultiMesh): Update interpolation in storage.
+
+	// INSTANCES
+
+	// Detect any that were on the previous transform list that are no longer active;
+	// we should remove them from the interpolate list.
+
+	for (unsigned int n = 0; n < _interpolation_data.instance_transform_update_list_prev->size(); n++) {
+		const RID &rid = (*_interpolation_data.instance_transform_update_list_prev)[n];
```
Comment (AThousandShips) [inline servers/rendering/renderer_scene_cull.cpp:4484]:
```suggestion
	for (const RID &rid : *_interpolation_data.instance_transform_update_list_prev) {
```

File: servers/rendering/renderer_scene_cull.cpp [hunk 6]
```diff
@@ -4240,6 +4470,172 @@ void RendererSceneCull::set_scene_render(RendererSceneRender *p_scene_render) {
...
+		if (!active) {
+			_interpolation_data.instance_interpolate_update_list.erase(rid);
+		}
+	}
+
+	// Now for any in the transform list (being actively interpolated), keep the previous transform
+	// value up to date, ready for the next tick.
+	if (p_process) {
+		for (unsigned int n = 0; n < _interpolation_data.instance_transform_update_list_curr->size(); n++) {
+			const RID &rid = (*_interpolation_data.instance_transform_update_list_curr)[n];
```
Comment (AThousandShips) [inline servers/rendering/renderer_scene_cull.cpp:4517]:
```suggestion
		for (const RID &rid : *_interpolation_data.instance_transform_update_list_curr) {
```

File: servers/rendering/renderer_scene_cull.cpp [hunk 7]
```diff
@@ -4240,6 +4470,172 @@ void RendererSceneCull::set_scene_render(RendererSceneRender *p_scene_render) {
...
+	SWAP(_interpolation_data.instance_transform_update_list_curr, _interpolation_data.instance_transform_update_list_prev);
+
+	// Prepare for the next iteration.
+	_interpolation_data.instance_transform_update_list_curr->clear();
+
+	// CAMERAS
+
+	// Detect any that were on the previous transform list that are no longer active.
+	for (unsigned int n = 0; n < _interpolation_data.camera_transform_update_list_prev->size(); n++) {
+		const RID &rid = (*_interpolation_data.camera_transform_update_list_prev)[n];
```
Comment (AThousandShips) [inline servers/rendering/renderer_scene_cull.cpp:4538]:
```suggestion
	for (const RID &rid : *_interpolation_data.camera_transform_update_list_prev) {
```

File: servers/rendering/renderer_scene_cull.cpp [hunk 8]
```diff
@@ -4240,6 +4470,172 @@ void RendererSceneCull::set_scene_render(RendererSceneRender *p_scene_render) {
...
+
+		// No longer active? (Either the instance deleted or no longer being transformed.)
+		if (camera && !camera->on_interpolate_transform_list) {
+			camera->transform = camera->transform_prev;
+		}
+	}
+
+	// Swap any current with previous.
+	for (unsigned int n = 0; n < _interpolation_data.camera_transform_update_list_curr->size(); n++) {
+		const RID &rid = (*_interpolation_data.camera_transform_update_list_curr)[n];
```
Comment (AThousandShips) [inline servers/rendering/renderer_scene_cull.cpp:4549]:
```suggestion
	for (const RID &rid : *_interpolation_data.camera_transform_update_list_curr) {
```

File: scene/3d/node_3d.cpp (hunk 2 above)
Comment (lawnjelly) [reply scene/3d/node_3d.cpp:427]: It is often called twice, yes. The function contains a tick counter which ensures it only operates _once_ per tick.

The data must get updated, but if `get_global_transform_interpolated()` is called before the tick update, it is refreshed early. The logic admittedly isn't super clear, but it works this way to prevent an order of operations bug.

File: servers/rendering/renderer_scene_cull.cpp [hunk 9]
```diff
@@ -4240,6 +4470,172 @@ void RendererSceneCull::set_scene_render(RendererSceneRender *p_scene_render) {
...
+	// Prepare for the next iteration.
+	_interpolation_data.camera_transform_update_list_curr->clear();
+}
+
+void RendererSceneCull::update_interpolation_frame(bool p_process) {
+	// TODO (MultiMesh): Update interpolation in storage.
+
+	// Teleported instances.
+	for (unsigned int n = 0; n < _interpolation_data.instance_teleport_list.size(); n++) {
+		const RID &rid = _interpolation_data.instance_teleport_list[n];
```
Comment (AThousandShips) [inline servers/rendering/renderer_scene_cull.cpp:4570]:
```suggestion
	for (const RID &rid : _interpolation_data.instance_teleport_list) {
```

File: servers/rendering/renderer_scene_cull.cpp [hunk 10]
```diff
@@ -4240,6 +4470,172 @@ void RendererSceneCull::set_scene_render(RendererSceneRender *p_scene_render) {
...
+			instance->transform_prev = instance->transform_curr;
+			instance->transform_checksum_prev = instance->transform_checksum_curr;
+		}
+	}
+
+	_interpolation_data.instance_teleport_list.clear();
+
+	// Camera teleports.
+	for (unsigned int n = 0; n < _interpolation_data.camera_teleport_list.size(); n++) {
+		const RID &rid = _interpolation_data.camera_teleport_list[n];
```
Comment (AThousandShips) [inline servers/rendering/renderer_scene_cull.cpp:4582]:
```suggestion
	for (const RID &rid : _interpolation_data.camera_teleport_list) {
```

File: servers/rendering/renderer_scene_cull.cpp [hunk 11]
```diff
@@ -4240,6 +4470,172 @@ void RendererSceneCull::set_scene_render(RendererSceneRender *p_scene_render) {
...
+		}
+	}
+
+	_interpolation_data.camera_teleport_list.clear();
+
+	if (p_process) {
+		real_t f = Engine::get_singleton()->get_physics_interpolation_fraction();
+
+		for (unsigned int i = 0; i < _interpolation_data.instance_interpolate_update_list.size(); i++) {
+			const RID &rid = _interpolation_data.instance_interpolate_update_list[i];
```
Comment (AThousandShips) [inline servers/rendering/renderer_scene_cull.cpp:4595]:
```suggestion
		for (const RID &rid : _interpolation_data.instance_interpolate_update_list) {
```

**Review by AThousandShips — COMMENTED** [review]
Looks very intriguing! Looking forward to this

File: core/math/transform_interpolator.cpp [hunk 12]
```diff
@@ -74,3 +75,340 @@ void TransformInterpolator::interpolate_transform_2d(const Transform2D &p_prev,
...
+	r_result.origin = p_prev.origin + ((p_curr.origin - p_prev.origin) * p_fraction);
+	interpolate_basis(p_prev.basis, p_curr.basis, r_result.basis, p_fraction);
+}
+
+void TransformInterpolator::interpolate_basis(const Basis &p_prev, const Basis &p_curr, Basis &r_result, real_t p_fraction) {
+	Method method = find_method(p_prev, p_curr);
+	interpolate_basis_via_method(p_prev, p_curr, r_result, p_fraction, method);
+}
+
+void TransformInterpolator::interpolate_transform_3d_via_method(const Transform3D &p_prev, const Transform3D &p_curr, Transform3D &r_result, real_t p_fraction, TransformInterpolator::Method p_method) {
```
Comment (AThousandShips) [inline core/math/transform_interpolator.cpp:89]:
```suggestion
void TransformInterpolator::interpolate_transform_3d_via_method(const Transform3D &p_prev, const Transform3D &p_curr, Transform3D &r_result, real_t p_fraction, Method p_method) {
```
Unnecessary

File: core/math/transform_interpolator.cpp [hunk 13]
```diff
@@ -74,3 +75,340 @@ void TransformInterpolator::interpolate_transform_2d(const Transform2D &p_prev,
...
+	r_result.origin = p_prev.origin + ((p_curr.origin - p_prev.origin) * p_fraction);
+	interpolate_basis_via_method(p_prev.basis, p_curr.basis, r_result.basis, p_fraction, p_method);
+}
+
+void TransformInterpolator::interpolate_basis_via_method(const Basis &p_prev, const Basis &p_curr, Basis &r_result, real_t p_fraction, TransformInterpolator::Method p_method) {
```
Comment (AThousandShips) [inline core/math/transform_interpolator.cpp:94]:
```suggestion
void TransformInterpolator::interpolate_basis_via_method(const Basis &p_prev, const Basis &p_curr, Basis &r_result, real_t p_fraction, Method p_method) {
```

File: scene/3d/visual_instance_3d.cpp [hunk 14]
```diff
@@ -41,7 +43,38 @@ void VisualInstance3D::_update_visibility() {
...
+	bool already_visible = _is_vi_visible();
+	bool visible = is_visible_in_tree();
+	_set_vi_visible(visible);
+
+	// If making visible, make sure the rendering server is up to date with the transform.
+	if (visible && !already_visible) {
+		if (!_is_using_identity_transform()) {
+			Transform3D gt = get_global_transform();
+			RS::get_singleton()->instance_set_transform(instance, gt);
+		}
```
Comment (AThousandShips) [inline scene/3d/visual_instance_3d.cpp:55]:
```suggestion
	if (visible && !already_visible && !_is_using_identity_transform()) {
		Transform3D gt = get_global_transform();
		RS::get_singleton()->instance_set_transform(instance, gt);
```
IMO long if conditions are easier to read than deeply nested blocks

File: scene/3d/visual_instance_3d.cpp [hunk 15]
```diff
@@ -53,13 +86,46 @@ void VisualInstance3D::_notification(int p_what) {
...
+
+					// For instance when first adding to the tree, when the previous transform is
+					// unset, to prevent streaking from the origin.
+					if (_is_physics_interpolation_reset_requested()) {
+						if (_is_vi_visible()) {
+							_notification(NOTIFICATION_RESET_PHYSICS_INTERPOLATION);
+						}
+						_set_physics_interpolation_reset_requested(false);
+					}
+				}
```
Comment (AThousandShips) [inline scene/3d/visual_instance_3d.cpp:102]:
```suggestion
			if ((_is_vi_visible() || is_physics_interpolated_and_enabled()) && !_is_using_identity_transform()) {
				Transform3D gt = get_global_transform();
				RenderingServer::get_singleton()->instance_set_transform(instance, gt);

				// For instance when first adding to the tree, when the previous transform is
				// unset, to prevent streaking from the origin.
				if (_is_physics_interpolation_reset_requested()) {
					if (_is_vi_visible()) {
						_notification(NOTIFICATION_RESET_PHYSICS_INTERPOLATION);
					}
					_set_physics_interpolation_reset_requested(false);
				}
```

**Comment by lawnjelly** [comment]
> I found the log for the crash in my [previous reply](https://github.com/godotengine/godot/pull/92391#issuecomment-2141361744), and I'm a bit confused?
> 
> In that previous instance there is _not_ any fatal error before crashing, it just suddenly crashes.
> Full log here: [godot2024-05-31T00.00.15.log](https://github.com/user-attachments/files/15524877/godot2024-05-31T00.00.15.log)

Given the amount of errors in your log, it is possible you are just blowing the message queue. If you can fix the errors with the `Tweener` and `get_pixel()` that might be helpful to see if you still get a crash.

The interpolation warnings has a built in timer to prevent excessive error spam.

**Comment by matmas** [comment]
Here is another test project that shows a potential issue:
[test-physics-interpolation-camera-godot4.zip](https://github.com/user-attachments/files/15552345/test-physics-interpolation-camera-godot4.zip)

https://github.com/godotengine/godot/assets/499286/388b09c2-701e-4edc-b8ba-a7019ee9c9c9

The NinePatchRect with the 4 corners doesn't stay centered on the ball. The issue is visible only when camera is moving. Project is using 10 physics ticks per second.

Interestingly enough this issue is also reproducible in Godot 3.6-beta5.
Here is the Godot 3 version of the project:
[test-physics-interpolation-camera-godot3.zip](https://github.com/user-attachments/files/15552439/test-physics-interpolation-camera-godot3.zip)

If instead of the built-in physics interpolation we use lawnjelly's smoothing-addon (https://github.com/lawnjelly/smoothing-addon/tree/4.x) then this issue disappears:

https://github.com/godotengine/godot/assets/499286/1383c9c5-4690-4003-ace8-4cc55dd161b4

Here is the Godot 4 version using the smoothing-addon:
[test-physics-interpolation-camera-godot4-smoothing-addon.zip](https://github.com/user-attachments/files/15552526/test-physics-interpolation-camera-godot4-smoothing-addon.zip)

To reproduce the first video you might need to get `get_global_transform_interpolated()` working first with:
```diff
diff --git a/scene/3d/node_3d.cpp b/scene/3d/node_3d.cpp
index 30f5d6f88a..3c36909732 100644
--- a/scene/3d/node_3d.cpp
+++ b/scene/3d/node_3d.cpp
@@ -400,18 +400,18 @@ void Node3D::_disable_client_physics_interpolation() {
 }
 
 Transform3D Node3D::_get_global_transform_interpolated(real_t p_interpolation_fraction) {
-   ERR_FAIL_COND_V(is_inside_tree(), Transform3D());
+   ERR_FAIL_COND_V(!is_inside_tree(), Transform3D());
 
    // Set in motion the mechanisms for client side interpolation if not already active.
    if (!_is_physics_interpolated_client_side()) {
        _set_physics_interpolated_client_side(true);
 
-       ERR_FAIL_NULL_V(data.client_physics_interpolation_data, Transform3D());
        data.client_physics_interpolation_data = memnew(ClientPhysicsInterpolationData);
        data.client_physics_interpolation_data->global_xform_curr = get_global_transform();
        data.client_physics_interpolation_data->global_xform_prev = data.client_physics_interpolation_data->global_xform_curr;
        data.client_physics_interpolation_data->current_physics_tick = Engine::get_singleton()->get_physics_frames();
    }
+   ERR_FAIL_NULL_V(data.client_physics_interpolation_data, Transform3D());
 
    // Storing the last tick we requested client interpolation allows us to timeout
    // and remove client interpolated nodes from the list to save processing.
@@ -423,9 +423,6 @@ Transform3D Node3D::_get_global_transform_interpolated(real_t p_interpolation_fr
    // would be machine dependent.
    data.client_physics_interpolation_data->timeout_physics_tick = Engine::get_singleton()->get_physics_frames() + 256;
 
-   // Make sure data is up to date.
-   update_client_physics_interpolation_data();
-
    // Interpolate the current data.
    const Transform3D &xform_curr = data.client_physics_interpolation_data->global_xform_curr;
    const Transform3D &xform_prev = data.client_physics_interpolation_data->global_xform_prev;

```

**Comment by Calinou** [comment]
> UPDATE: This turns out to be a bit of bag of worms, as a lot of Camera functions are designed without the possibility of physics interpolation. We will discuss best way to proceed on this making it as easy as possible for users.

What about adding `unproject_position_interpolated()`, `project_position_interpolated()` and so on? This would mean adding many more methods, but it keeps the code more explicit by avoiding boolean arguments.

File: scene/3d/node_3d.cpp (hunk 2 above)
Comment (matmas) [reply scene/3d/node_3d.cpp:427]: Yes, it is true that `global_xform_prev` is updated only once per tick.

The not so obvious thing is that when `update_client_physics_interpolation_data()` gets called from `SceneTree::ClientPhysicsInterpolation::physics_process()`, the function `Engine::get_singleton()->get_physics_frames()` is returning incorrect value due to being updated late. This way the newly changed value from `get_global_transform()` is stored into `global_xform_curr` even before we actually change `global_xform_prev`. The next call to `update_client_physics_interpolation_data()` from `get_global_transform_interpolated()` we finally see that the tick has changed and we set `global_xform_prev` to `global_xform_curr`. This second call happens in the same process frame as the first one and so both `global_xform_prev` and `global_xform_curr` end up having the same value.

**Comment by lawnjelly** [comment]
> What about adding unproject_position_interpolated(), project_position_interpolated() and so on? This would mean adding many more methods, but it keeps the code more explicit by avoiding boolean arguments.

This is one of the things we've been discussing. There are a lot of methods though in `Camera`.

It might be viable to just call `get_global_transform_interpolated()` internally and leave it to auto-switch based on whether it is called within a physics tick or process, I'll take a look further today. Also at this point I think it will be worth evaluating moving the `Camera` interpolation to scene, as there's less argument to do it remotely if we have to support these methods with interpolation.

**Comment by matmas** [comment]
Here is another test project that shows another potential issue:

[test-physics-interpolation-init.zip](https://github.com/user-attachments/files/15592586/test-physics-interpolation-init.zip)

https://github.com/godotengine/godot/assets/499286/4b27fd02-67d9-483a-9a2e-274853c639e5

Here the camera is moving right 20 m/s without damping or gravity and every 3 seconds a ball is spawned in front of the camera with the same linear velocity as the camera. The issue here is that when the physics interpolation is enabled the ball appears in a wrong spot initially and then moves to the correct spot. Project is using 10 physics ticks per second. The ball is spawned in a physics frame and despawn after 2 seconds.

This issue isn't visible when the objects being spawned have zero velocity. The more velocity they have the more distance they appear to travel into the correct position. The issue can also be triggered by calling `reset_physics_interpolation()`.

I also tried Godot 3.6-beta5 and the issue is there too.

I believe this is caused by initially setting `global_xform_prev` to the same value as `global_xform_curr` which is technically correct when the object is not moving but isn't ideal otherwise.

Although there are probably better ways to fix the issue I should probably mention a workaround that I was using in my personal project:
```
spawned_object_interpolation.previous_global_transform.origin -= camera_physics_interpolation.current_global_transform.origin - camera_physics_interpolation.previous_global_transform.origin
```

**Comment by lawnjelly** [comment]
> Although there are probably better ways to fix the issue I should probably mention a workaround that I was using in my personal project:

See _"Moving Start"_:
https://docs.godotengine.org/en/3.6/tutorials/physics/interpolation/using_physics_interpolation.html#call-reset-physics-interpolation-when-teleporting-objects

**Comment by matmas** [comment]
> See _"Moving Start"_: https://docs.godotengine.org/en/3.6/tutorials/physics/interpolation/using_physics_interpolation.html#call-reset-physics-interpolation-when-teleporting-objects

Thanks for the link. Since the link documents Godot 3 I went ahead and converted the previously mentioned test project into Godot 3. First thing I noticed when using the same code logic is that the ball spawned one physics tick behind the desired position. This behavior doesn't seem to be related to physics interpolation and looks like a Godot 3 vs 4 difference.

I have added the suggested changes according to the documentation link you provided:

```diff
diff --git a/main.gd b/main.gd
index 9b93ab3..921d5aa 100644
--- a/main.gd
+++ b/main.gd
@@ -10,6 +10,8 @@ func _on_SpawnTimer_timeout() -> void:
    var ball := preload("res://ball.tscn").instance() as RigidBody
    ball.position = camera_body.position + Vector3.FORWARD * 2
    ball.linear_velocity = camera_body.linear_velocity
    add_child(ball)
+   ball.reset_physics_interpolation()
+   ball.position += ball.linear_velocity * get_physics_process_delta_time()
```

Now the ball ends up in the correct spot but I can still see it streaking towards it and behaves exactly like the Godot 4 project video I included in my previous comment.

I am not sure if I am doing something wrong. Here is the Godot 3 project version if you want to try it yourself:

[Test Physics Interpolation Init Godot3.zip](https://github.com/user-attachments/files/15595375/Test.Physics.Interpolation.Init.Godot3.zip)

**Comment by lawnjelly** [comment]
> I am not sure if I am doing something wrong. Here is the Godot 3 project version if you want to try it yourself:

Firstly, just an important point that I wanted to clarify as it predictably causes confusion:

**The first thing to learn about physics Interpolation is it nothing to do with physics** :grinning: 

The correct name is fixed timestep interpolation, the only relation to physics is that the timesteps coincide with the physics engine ticks in Godot.
https://docs.godotengine.org/en/3.6/tutorials/physics/interpolation/physics_interpolation_introduction.html#fixed-timestep-interpolation

Therefore it's far easier to examine if MRPs do not include any physics (simplify and eliminate anything complex that may be causing secondary effects). So here my first step was to simplify the project to remove all physics objects and just use `Spatials` with a fixed movement speed in `_physics_process()`:

[Test Physics Interpolation Init2.zip](https://github.com/user-attachments/files/15595957/Test.Physics.Interpolation.Init2.zip)

That said, there _does_ appear to be a bug (even in 3.6), and it is likely order of operations (in fact I'm pretty sure I had to fix exactly an equivalent of this recently somewhere else in the interpolation).

The problem is that in Godot if you call `set_position()`, Godot defers that to some point in the future where it flushes the transforms (lazy updating optimization), and if you call `reset_physics_interpolation()` before the deferred change has gone through the wrong transform gets reset.

The good news is that these are usually pretty simple to fix, I'll take a look tomorrow. :+1:

**Comment by matmas** [comment]
> [Test Physics Interpolation Init2.zip](https://github.com/user-attachments/files/15595957/Test.Physics.Interpolation.Init2.zip)

> I'll be adding this to #92784 which should get forward ported to this PR.

I gave both your project and your branch `fti_camera_to_scene` a try (I found the fix you mentioned already included there) but I still see the ball streaking when the spawn timer spawns the ball:

https://github.com/godotengine/godot/assets/499286/4b55a573-64be-4c78-b152-1bc29412c031

**Comment by lawnjelly** [comment]
> I gave both your project and your branch fti_camera_to_scene a try (I found the fix you mentioned already included there) but I still see the ball streaking when the spawn timer spawns the ball:

You are correct, I don't know why it ended up working in the testbed (maybe I had switched interpolation off).
I've identified a couple of problems:
* My earlier test project was wrong, it can't just do a `reset` when you click the button (else you get the streaking, because the position has not been primed). Although maybe that was your intention with the original MRP, that the timeout worked, and the button didn't?
* In the engine, there is a convenience `teleport_list` which screws with the timing.

The `teleport_list` I forgot the exact reason for. It defers the reset until the next physics tick. This was either to prevent jumps on frames, or more likely to ensure the transform had been flushed to the `VisualServer` before the reset. However the existing part of the PR now flushes the transform to the `VisualServer` immediately before calling reset, so this may no longer be necessary.

Indeed just directly resetting in `VisualServer` (`prev = curr`) rather than using the deferred `teleport_list` seems to fix the problem. I'll see whether we can get rid of the teleport lists now for both 3D and 2D if we are going with this approach.

**Comment by lawnjelly** [comment]
@matmas If you can try the latest version of https://github.com/godotengine/godot/pull/92784 and let me know how you get on that would be great.

There is also a new MRP project which correct quite a few problems with my previous and adds similar tests for the camera:
[Test Physics Interpolation Init3.zip](https://github.com/user-attachments/files/15731412/Test.Physics.Interpolation.Init3.zip)

It does the adding with timer, you can click reset manually, or if you press return it will reset the `Camera` (similar to how it is done for the ball).

There's quite a bit of refactoring under the hood to get the moving starts working correctly, I had forgotten how much deferred stuff Godot does under the hood and we have to work around this.

**Comment by matmas** [comment]
@lawnjelly I tried the latest version of https://github.com/godotengine/godot/pull/92784 and I can no longer reproduce the issue. I tried it against my physics-based project [Test Physics Interpolation Init Godot3.zip](https://github.com/user-attachments/files/15595375/Test.Physics.Interpolation.Init.Godot3.zip) and your latest one [Test Physics Interpolation Init3.zip](https://github.com/user-attachments/files/15731412/Test.Physics.Interpolation.Init3.zip) and in both cases the issue seems to be fixed and to me it looks like things works exactly as described in the Godot 3 documentation. :+1: :partying_face: 

In [Test Physics Interpolation Init2.zip](https://github.com/user-attachments/files/15595957/Test.Physics.Interpolation.Init2.zip) the ball was streaking (from the other direction) but that was easily fixable with:

```diff
diff --git a/main.gd b/main.gd
index 8505b1e..9cbb084 100644
--- a/main.gd
+++ b/main.gd
@@ -15,7 +15,7 @@ func _on_SpawnTimer_timeout() -> void:
    
    print("adding ball")
    var new_pos = $CameraBody.position + Vector3(0, 0, -4)
-   ball.position = new_pos - Vector3(get_physics_process_delta_time(), 0, 0)
+   ball.position = new_pos
    ball.reset_physics_interpolation()
    ball.position = new_pos
```

> My earlier test project was wrong, it can't just do a `reset` when you click the button (else you get the streaking, because the position has not been primed). Although maybe that was your intention with the original MRP, that the timeout worked, and the button didn't?

The original MRP was intended to show the issue just by running the project. The button was included only to see what happens when you call `reset_physics_interpolation()` but now I think it was a bad idea as calling it outside of physics frames is rarely a good choice. I also haven't pressed this button in any of the videos I posted.

**Comment by Calinou** [comment]
Some additional observations from creating https://github.com/godotengine/godot-demo-projects/pull/1074. I tested this PR (rebased on top of `master` https://github.com/godotengine/godot/commit/475248d99df89fc29032a42f1d29ad4cef49c8b5):

- In the Kinematic Character 3D demo, the sun position is interpolated at startup. Example at 2 TPS to make it obvious:

https://github.com/godotengine/godot/assets/180032/7c4209b5-c06f-43e5-8339-2f4de1f9c77e

- I have to call `_reset_physics_interpolation()` in `cubio.gd`'s `_ready()` method to avoid having the camera be interpolated to its startup position. This seems to be the case in all other 3D demos I've modified to use physics interpolation as well (although this might be less noticeable in some of them due to their longer loading times).

**Comment by lawnjelly** [comment]
@Calinou that is to be expected as this PR does not contain #92784 yet, so has no auto-resets. It should probably be marked as draft, as I believe plan is to port this (also changes how cameras work).

File: scene/3d/visual_instance_3d.cpp (hunk 14 above)
Comment (rburing) [reply scene/3d/visual_instance_3d.cpp:55]: I prefer it the way it is. I implemented all your other style suggestions, thanks!

**Comment by rburing** [comment]
This PR now includes the automatic resets and scene-side camera interpolation from https://github.com/godotengine/godot/pull/92784.

The test project [Test.Physics.Interpolation.Init.Godot3.zip](https://github.com/user-attachments/files/15595375/Test.Physics.Interpolation.Init.Godot3.zip) from above converted to Godot 4 does exhibit streaks like in https://github.com/godotengine/godot/pull/92391#issuecomment-2153117357, both with and without physics interpolation enabled, and also streaks in Godot 4.2.2 stable (so interpolation works?). Here's the test project: [Test.Physics.Interpolation.Init.Godot4.zip](https://github.com/user-attachments/files/15859064/Test.Physics.Interpolation.Init.Godot4.zip)

The automatic resets in other test/demo projects like https://github.com/godotengine/godot/pull/92391#issuecomment-2165702119 seem to be working fine now.

Re-testing and review is welcome. Thanks to everyone who tested so far!

**Comment by Calinou** [comment]
> Re-testing and review is welcome.

I tested the latest revision of this PR and while the initial camera position is set correctly now, using `reset_physics_interpolation()` in the player script no longer prevents the camera from following the interpolated position (e.g. when the player falls off the world in Kinematic Character 3D or presses <kbd>R</kbd> to respawn).

Also, in Truck Town, `reset_physics_interpolation()` works to prevent the camera from interpolating when it's changed by the player when pressing <kbd>C</kbd>, but only if the node's top-level status isn't changed at the same time. This means the reset works when going from Exterior to Interior, but not from Interior to Top-Down or from Top-Down to Exterior.

https://github.com/Calinou/godot-demo-projects/blob/d18e12edc5477fdb514d9cd56fdd1abd9d73fb64/3d/truck_town/vehicles/follow_camera.gd#L93-L95

**Comment by matmas** [comment]
Tested last revision of this PR with project [test-physics-interpolation-camera-godot4.zip](https://github.com/user-attachments/files/15552345/test-physics-interpolation-camera-godot4.zip). I got a crash right at the start when running the project:

```
Godot Engine v4.3.beta.custom_build.8e41e5613 (2024-06-16 20:35:56 UTC) - https://godotengine.org
Vulkan 1.3.277 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce RTX 2070 SUPER

ERROR: Parameter "data.client_physics_interpolation_data" is null.
   at: _get_global_transform_interpolated (scene/3d/node_3d.cpp:409)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.3.beta.custom_build (8e41e56135e09695024829c48a561165432da269)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x414b0) [0x79583cc9c4b0] (??:0)
[2] /home/matmas/repos/godot/bin/godot.linuxbsd.editor.x86_64(+0x30970ed) [0x584234c1a0ed] (??:0)
[3] /home/matmas/repos/godot/bin/godot.linuxbsd.editor.x86_64(+0x309733a) [0x584234c1a33a] (??:0)
[4] /home/matmas/repos/godot/bin/godot.linuxbsd.editor.x86_64(+0xd8c74c) [0x58423290f74c] (??:0)
[5] /home/matmas/repos/godot/bin/godot.linuxbsd.editor.x86_64(+0xa66fe0) [0x5842325e9fe0] (??:0)
[6] /home/matmas/repos/godot/bin/godot.linuxbsd.editor.x86_64(+0x8fb4eb) [0x58423247e4eb] (??:0)
[7] /home/matmas/repos/godot/bin/godot.linuxbsd.editor.x86_64(+0x2a327fa) [0x5842345b57fa] (??:0)
[8] /home/matmas/repos/godot/bin/godot.linuxbsd.editor.x86_64(+0x30ac06d) [0x584234c2f06d] (??:0)
[9] /home/matmas/repos/godot/bin/godot.linuxbsd.editor.x86_64(+0x4f5c350) [0x584236adf350] (??:0)
[10] /home/matmas/repos/godot/bin/godot.linuxbsd.editor.x86_64(+0x2a7b478) [0x5842345fe478] (??:0)
[11] /home/matmas/repos/godot/bin/godot.linuxbsd.editor.x86_64(+0x2a7bbaa) [0x5842345febaa] (??:0)
[12] /home/matmas/repos/godot/bin/godot.linuxbsd.editor.x86_64(+0x2a7c17a) [0x5842345ff17a] (??:0)
[13] /home/matmas/repos/godot/bin/godot.linuxbsd.editor.x86_64(+0x6a03c0) [0x5842322233c0] (??:0)
[14] /home/matmas/repos/godot/bin/godot.linuxbsd.editor.x86_64(+0x60c541) [0x58423218f541] (??:0)
[15] /home/matmas/repos/godot/bin/godot.linuxbsd.editor.x86_64(+0x5e4882) [0x584232167882] (??:0)
[16] /usr/lib/libc.so.6(+0x25f8e) [0x79583cc80f8e] (??:0)
[17] /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x79583cc8104a] (??:0)
[18] /home/matmas/repos/godot/bin/godot.linuxbsd.editor.x86_64(+0x609b35) [0x58423218cb35] (??:0)
-- END OF BACKTRACE --
================================================================
```

**Comment by rburing** [comment]
@matmas Thanks, it was a typo, fixed now.

@Calinou Thanks for the new test case, we're still investigating how to fix it.

**Comment by matmas** [comment]
> The test project [Test.Physics.Interpolation.Init.Godot3.zip](https://github.com/user-attachments/files/15595375/Test.Physics.Interpolation.Init.Godot3.zip) from above converted to Godot 4 does exhibit streaks like in [#92391 (comment)](https://github.com/godotengine/godot/pull/92391#issuecomment-2153117357), both with and without physics interpolation enabled, and also streaks in Godot 4.2.2 stable (so interpolation works?). Here's the test project: [Test.Physics.Interpolation.Init.Godot4.zip](https://github.com/user-attachments/files/15859064/Test.Physics.Interpolation.Init.Godot4.zip)

One thing I noticed in your test project is that the SpawnTimer has process_mode set to _Idle_ while both my Godot 3 and 4 versions have it set to _Physics_. This difference seems to be the cause of the streaks you observed even when interpolation is turned off.

Another thing to keep in mind is the difference between Godot 3 and 4. In order to spawn a RigidBody with desired velocity and position in Godot 3 one needs add `linear_velocity * get_physics_process_delta_time()` to its `position`. This is not needed in Godot 4 so if we choose to do it anyway in order to avoid streaks we also need to compensate for it by subtracting by the same amount before.

I have tested your test project with the following diff and it solves the streaks:

```diff
diff --git a/main.gd b/main.gd
index 9720449..a7abc4b 100644
--- a/main.gd
+++ b/main.gd
@@ -10,6 +10,7 @@ func _on_SpawnTimer_timeout() -> void:
    ball.position = camera_body.position + Vector3.FORWARD * 2
    ball.linear_velocity = camera_body.linear_velocity
    add_child(ball)
+   ball.position -= ball.linear_velocity * get_physics_process_delta_time()
    ball.reset_physics_interpolation()
    ball.position += ball.linear_velocity * get_physics_process_delta_time()
 
diff --git a/main.tscn b/main.tscn
index bab659a..46e9fdd 100644
--- a/main.tscn
+++ b/main.tscn
@@ -38,6 +38,7 @@ shape = SubResource("1")
 [node name="Camera3D" type="Camera3D" parent="CameraBody"]
 
 [node name="SpawnTimer" type="Timer" parent="."]
+process_callback = 0
 wait_time = 3.0
 autostart = true
```

**Comment by matmas** [comment]
> @matmas Thanks, it was a typo, fixed now.

After testing the last revision of this PR I can confirm the crash is indeed fixed but `get_global_transform_interpolated()` returns values that are not interpolated.

See https://github.com/godotengine/godot/pull/92391#discussion_r1626838798 for possible explanation why this is happening.

As a test project you can use [test-physics-interpolation-camera-godot4.zip](https://github.com/user-attachments/files/15552345/test-physics-interpolation-camera-godot4.zip)

**Comment by lawnjelly** [comment]
> but get_global_transform_interpolated() still returns values that are not interpolated.

I've just debugged for this PR and you are indeed correct, while this is working in 3.x, the physics seems to be updating the transform in 4.x _before_ `SceneTree::physics_process()` is called.

We can try and work out why this is, it could be due to e.g. transforms being flushed prior to `SceneTree::physics_process()`.

**Comment by matmas** [comment]
After testing the last revision of this PR I can confirm `get_global_transform_interpolated()` is returning interpolated values. So far so good.

---

I have found another potential issue, here is the test project:

[test-physics-interpolation-init-4.zip](https://github.com/user-attachments/files/15894373/test-physics-interpolation-init-4.zip)

https://github.com/godotengine/godot/assets/499286/308f348c-f290-4df4-a78a-5db264306b67

This is basically the same as in https://github.com/godotengine/godot/pull/92391#issuecomment-2150431438 but with added `NinePatchRect` positioned in `_process()` using `get_global_transform_interpolated()` and `Camera3D.unproject_position()`.

The issue here is that the `NinePatchRect` appears streaking towards the correct position during one physics frame after calling `get_global_transform_interpolated()` on a new object.

This issue seems to be present also in Godot 3, here is the Godot 3 version of the project:

[Test Physics Interpolation Init 4 Godot3.zip](https://github.com/user-attachments/files/15894529/Test.Physics.Interpolation.Init.4.Godot3.zip)

**Comment by lawnjelly** [comment]
> The issue here is that the NinePatchRect appears streaking towards the correct position during one physics frame after calling get_global_transform_interpolated() on a new object. This happens only when physics interpolation is enabled.

Fixed by #93339 in 3.x.

Note that you will need to call `get_global_transform_interpolated()` once _before_ resetting the ball for moving start. This primes the client interpolation for the ball, so it can respond to the reset.

This isn't super obvious so I've added to the classref and will add to docs. I'm not immediately sure of a way of making this easier from the user perspective, as the client interpolation is expensive so needs to be primed. I guess it will be a "gotcha", unless we can think of a simpler way of automating this.

**Review by lawnjelly — APPROVED** [review]
Although I've confirmed with akien this will be for 4.4 (so can only be merged after 4.3), I wanted to give preliminary approval as this is already in a state where it could theoretically be merged (and iterated on).

We will no doubt continue improving the PR in the meantime.

**Comment by matmas** [comment]
> Fixed by #93339 in 3.x.
> 
> Note that you will need to call `get_global_transform_interpolated()` once _before_ resetting the ball for moving start. This primes the client interpolation for the ball, so it can respond to the reset.

Yes, I have tested it and it works just like you said with your fix. :+1: 

> This isn't super obvious so I've added to the classref and will add to docs. I'm not immediately sure of a way of making this easier from the user perspective, as the client interpolation is expensive so needs to be primed. I guess it will be a "gotcha", unless we can think of a simpler way of automating this.

Have you considered changing the default initial values for `xform_curr` and `xform_prev`? Currently when user isn't aware of this gotcha they will most likely notice streaks only when both camera and spawned objects are moving together with the same or similar velocities. On the other hand If we set `xform_prev` origin based on the current camera movement the streak might be virtually unnoticeable. Maybe doing something similar to:

> ```
> spawned_object_interpolation_data.xform_prev.origin -= camera_interpolation_data.xform_curr.origin - camera_interpolation_data.xform_prev.origin
> ```

The idea here is to provide such default value that covers as many use cases as possible out-of-the-box without the user experiencing issues.

**Comment by matmas** [comment]
I have found another potential issue:

https://github.com/godotengine/godot/assets/499286/6d88320e-239c-4b42-99c9-241545c383b8

This project is similar to https://github.com/godotengine/godot/pull/92391#issuecomment-2147675432. The notable difference is that in `_process()` the camera global position is being modified which seem to interfere with/disable the camera interpolation. In this case it is the position of `CameraParent` (`Node3D` parent of `Camera3D`) that is being changed but changing camera position directly would also produce similar result. In fact, to replicate the issue in projects that rely in camera interpolation you can also do simply:

```
func _process(_delta):
    var camera := get_viewport().get_camera_3d()
    camera.position = camera.position  # Just writing the same value over triggers the issue
```

Sometimes I get the following warning when running this project:
```
WARNING: [Physics interpolation] Interpolated Camera3D triggered from outside physics process: "/root/Main/CameraBody/CameraParent/Camera3D" (possibly benign).
     at: _notification (scene/3d/camera_3d.cpp:215)
```

If instead of the built-in physics interpolation we use lawnjelly's smoothing-addon (https://github.com/lawnjelly/smoothing-addon/tree/4.x) then this issue disappears:

https://github.com/godotengine/godot/assets/499286/ce5cabd4-f410-41b4-80d3-1cdd1e9d8e39

Here is the test project:
[test-physics-interpolation-camera-shake.zip](https://github.com/user-attachments/files/15903917/test-physics-interpolation-camera-shake.zip)

The smoothing addon version:
[test-physics-interpolation-camera-shake-godot4-smoothing-addon.zip](https://github.com/user-attachments/files/15904006/test-physics-interpolation-camera-shake-godot4-smoothing-addon.zip)

This issue seems to be present also in Godot `3.x` branch. Here is the Godot 3 version of the project:
[test-physics-interpolation-camera-shake-godot3.zip](https://github.com/user-attachments/files/15903920/test-physics-interpolation-camera-shake-godot3.zip)

**Review by AThousandShips — APPROVED** [review]

**Comment by lawnjelly** [comment]
> Have you considered changing the default initial value for xform_prev? Currently when user isn't aware of this gotcha they will most likely notice streaks only when both camera and spawned objects are moving together with the same or similar velocities.

Remember there are a lot of use cases for `get_global_transform_interpolated()`, many of which might assume a standing start. The suggestion that all objects should be assumed to start moving with the camera seems somewhat strange, imo.

Placing objects with a moving start requires some understanding of how interpolation works (with previous and current transforms), I'm not sure there is an easy way around this.

We could potentially have helper API functions to initially place objects with a velocity, e.g.
`set_global_transform_interpolated(Vector3 start_pos, Vector3 start_vel)`, that handle the resets for you, if that would be easier for users to understand.

But for priming client interpolated objects, you would have to prime before this call. An alternative would be to have a bool on `Spatial`s that forced them to start with client side interpolation.

**Comment by lawnjelly** [comment]
> The notable difference is that in _process() the camera global position is being modified which seem to interfere with/disable the camera interpolation.

> Sometimes I get the following warning when running this project:

You are getting the warning because you shouldn't be doing this. If you want to move a camera in process, set the interpolation mode for the node to OFF. If you want to use interpolation, move the camera in `_physics_process()`, and it will interpolate.

If you move an interpolated `Camera` during `_process()`, it will at best overwrite the current transform, and result in strange jittering. It is possible to move `Camera` during `_process()` for initial placement, but you may need to use `reset_physics_interpolation()`.

> If instead of the built-in physics interpolation we use lawnjelly's smoothing-addon (https://github.com/lawnjelly/smoothing-addon/tree/4.x) then this issue disappears:

Smoothing addon works in totally different way to core interpolation.

**Comment by matmas** [comment]
> We could potentially have helper API functions to initially place objects with a velocity, e.g. `set_global_transform_interpolated(Vector3 start_pos, Vector3 start_vel)`, that handle the resets for you, if that would be easier for users to understand. (I think we did discuss this _way back_, but it was figured that `reset_physics_interpolation()` would cover most use cases, at least to start with.)
> 
> But for priming client interpolated objects, you would have to prime before this call. An alternative would be to have a bool on `Spatial`s that forced them to start with client side interpolation.

I am really happy with the current state and the fact that there is a way to set `xform_prev` via `reset_physics_interpolation()`. Future helper functions could come in form of add-ons at first and it is probably best to leave the API as it is now.

**Comment by matmas** [comment]
I have found another potential issue:

https://github.com/godotengine/godot/assets/499286/866dc565-128a-4355-a57e-c056e1ddfe30

I have added a pause button with a label to the project described in https://github.com/godotengine/godot/pull/92391#issuecomment-2177431834. In the video I am clicking on the pause button several times.

The issue is that when `get_tree().paused` is set to `true` the physics interpolation is still moving things around for the remaining duration of the physics frame. When I tried to set `get_tree().paused` inside `_physics_process()` the result was similar except things were moving for the one whole duration of one physics frame, not just a fraction of it.

Here is the test project:
[test-physics-interpolation-init-5.zip](https://github.com/user-attachments/files/15906480/test-physics-interpolation-init-5.zip)

This issue seems to be present also in Godot `3.x` branch. Here is the Godot 3 version of the project:
[Test Physics Interpolation Init 5 Godot3.zip](https://github.com/user-attachments/files/15906481/Test.Physics.Interpolation.Init.5.Godot3.zip)

**Comment by lawnjelly** [comment]
@matmas Ah that is interesting, I hadn't tested the pausing. :+1: 

I suspect the correct thing to do would be to just reset the interpolated objects (which will prevent the frame interpolation glitch). I'm not sure trying to pause the interpolation fraction is worth it, this would be quite complicated, and some objects may not be desired to be paused by the pause.

**Comment by matmas** [comment]
> UPDATE: #93382 fixes the MRP for me.

Looks good to me. :+1:

**Comment by matmas** [comment]
> I'm not sure trying to pause the interpolation fraction is worth it, this would be quite complicated, and some objects may not be desired to be paused by the pause.

Just in case you want to pursue it further here is a bit different pausable MRP where `NinePatchRect` itself is also being paused and where you can freeze the ball and/or camera to see how it looks when camera and ball move with different velocities:

https://github.com/godotengine/godot/assets/499286/92657f8c-9e0d-4f29-87ec-226f90f6a94f

As you said the relative locations move a bit and since this time the `NinePatchRect` is also paused it doesn't always stay centered on the ball depending when you pause the game relative to the physics frame boundary. The project runs with 5 physics ticks per second.

Godot 3.x project: [test-physics-interpolation-pause-godot3.zip](https://github.com/user-attachments/files/15921358/test-physics-interpolation-pause-godot3.zip)

**Comment by azur-wolf** [comment]
physics interpolation would allow to run projects at 30 fps rather than 60?
heard that 30 lead to jitter but that fixes it I guess

**Comment by lawnjelly** [comment]
> As you said the relative locations move a bit and since this time the NinePatchRect is also paused it doesn't always stay centered on the ball depending when you pause the game relative to the physics frame boundary.

The problem here is the physics interpolation fraction, because some objects in the scene tree will be paused and some will contrinue to move. A possible way around this would be to have a main physics interpolation fraction, and a paused physics interpolation fraction, and pick the correct one depending on where it is called.

This is maybe doable, by changing all the calls to `Engine::get_physics_interpolation_fraction()` to e.g. local functions on the node that query the pause state and return either this or a paused fraction, or adding a bool parameter to `get_physics_interpolation_fraction()` to return whether it is unpaused or paused (presumably with a default to unpaused).

This does however push complexity to the many calling sites, and we'd have to see whether this trade off was worth it, versus having a small change in certain projects, just during the pause / unpause at low tick rates.

It also relies on there being no changes to the pausing system. At the moment we have a single global pause, but if they wanted to add e.g. different types of pause, or change the pause state of objects during the pause, it would break. Whereas resetting is a little clunky (I'll give you that) but it *just works* :tm: .

It's possible we can investigate the other method, but it's not massive high priority (there are likely other more important interpolation bugs to address first).

**Comment by Calinou** [comment]
> physics interpolation would allow to run physics frames on projects at 30 fps rather than 60? heard that 30 lead to jitter but that fixes it I guess

Yes, that's the main point of physics interpolation 🙂

**Comment by rburing** [comment]
This PR now includes the latest follow-up fixes that were already merged into the 3.x branch.

**Comment by ansdor** [comment]
when this gets merged, will it also work with third party physics engines like jolt and rapier?

**Comment by rburing** [comment]
Yes, I confirm it works with Godot-Jolt and any other 3D physics engine GDExtension you can find. It's physics engine agnostic, all the physics engine has to do is tick.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Thanks @rburing and @lawnjelly for the amazing work! :tada: 

I know the community is eagerly awaiting this, please all make sure to test it well (will be in 4.4-dev1 and beyond) and report any issues to fix before 4.4.

**Comment by KingKrouch** [comment]
So I just gave this a shot on the 4.4 Dev 1 release.

Setting aside not being enabled by default (I personally think enabling it by default would be a good precaution for those just getting started with the engine), it instantly makes stuff like the GDQuest TPS controller demo way smoother without any extra work needed. Fantastic PR!

**Comment by reubenmanning** [comment]
I've done a quick FPS test project. I can still notice some slight jitter on my 165hz monitor when I move the camera around. It's most apparent when I slowly walk around a small cube and keep it centered on screen. It's almost as if the camera movement is causing the jitter. Unless my character node setup isn't ideal.

If I don't look around, it looks buttery smooth while moving.

[test-fps-physics-interpolation.zip](https://github.com/user-attachments/files/16751712/test-fps-physics-interpolation.zip)

**Comment by lawnjelly** [comment]
> I've done a quick FPS test project. I can still notice some slight jitter on my 165hz monitor when I move the camera around.

Be sure to read the documentation regarding cameras.
https://docs.godotengine.org/en/3.6/tutorials/physics/interpolation/advanced_physics_interpolation.html

**Comment by mrjustaguy** [comment]
this should NOT be enabled by default, as there's plenty of stuff you need to know about to properly take advantage of this and not introduce potentially massive bugs in your games

**Comment by mrjustaguy** [comment]
Case in point: https://github.com/TokisanGames/Terrain3D/issues/470

Physics Interpolation breaks the Terrain here. It's unclear if this is a Terrain3D issue with it not properly using Interpolation or Godot messing something up with it.

Disabling Interpolation on the Terrain3D node and/or camera that it centers on does nothing

**Comment by rburing** [comment]
@mrjustaguy This PR has been merged, please create a new issue *with a minimal reproduction project* and I can take a look. (This goes for all potential issues.)

**Comment by rafa985** [comment]
Cant get it to work on quest 3 standalone. Is it mobile compatible?

**Comment by Calinou** [comment]
> Is it mobile compatible?

There's nothing that should prevent physics interpolation from working on mobile/web platforms. However, there may be XR-specific issues with physics interpolation. Does it work on a Quest 3 tethered to a PC?

**Comment by rafa985** [comment]
I have not tested that yet but I suspect it would behave just like in non
VR on pc. I don’t know why it’s just native on quest that it turns off

**Comment by mrjustaguy** [comment]
Calinou, no, under no circumstance enable this by default, you'll flood Godot's issue section with Bugs related to Physics Interpolation that aren't Godot's fault but just the fundamental principles of PI in action.

People Must Know what they're getting into, and the added complexities of dealing with PI, Period.

Physics Interpolation isn't and cannot ever be made into "just works" as you have to know when to reset Physics Interpolation (say teleportation of objects) and when to manually handle Interpolation when Godot doesn't understand what you're doing (say handling a gimbaled camera that's moving and rotating) to get the desired results that just work without PI.

the First cannot be resolved ever, and the only "patch" would be to add a "Teleport" function that handles this
the Second is an endless game of whack-a-bug as there'll always be some case where Interpolation will not understand the user's intentions, and you may very easily break existing stuff when trying to patch an edge case.

**Comment by Jamsers** [comment]
Godot's interpolation already has the "teleport" function: [reset_physics_interpolation()](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-reset-physics-interpolation)

For scenarios where you don't want physics interpolation (or want to do your own custom interpolation), you can selectively disable interpolation on a node by node basis, and all its children inherit this property (by default):
image

In fact, even if physics interpolation is enabled in the project, if your root node has the physics interpolation property turned off (and all other nodes are left at default), it'll be functionally similar to having physics interpolation disabled.

Given these facts, I can see a better argument for having (project) physics interpolation enabled by default. The scenarios where a user would benefit from interpolation far outnumber the scenarios where users would want interpolation off. And in the scenarios where you would want interpolation off, it's far better to disable interpolation for the specific nodes involved in said scenario, rather than turning it off for the entire project.

**Comment by mrjustaguy** [comment]
The main problem is the user has to KNOW they're using Physics Interpolation, something a Beginner WILL NOT KNOW, nor be informed of the implications of using it, and you totally missed the point of the 2 examples I've given above.
I know that that function exists, I also know that I can disable Physics Interpolation and do my custom logic easily.

A User that doesn't even KNOW they're using Physics Interpolation will not KNOW that they need to reset physics interpolation when teleporting, nor that there may be cases where they need to write their own Interpolation Logic, simply because they won't even KNOW that they're using the Feature, It'll just Manifest to them as Bugs that'll needlessly frustrate the unaware users

Physics Interpolation can be Heavily Recommended in the Documentation with getting started (and project setting) and all with all the relevant links to the documentation regarding proper usage, but it cannot be stressed enough, this **CANNOT** be on by default.

Don't get me wrong, I'd love to have Physics Interpolation as Standard, but this cannot be enforced by Godot, as Godot can only enforce things that are blatantly obvious to the user, or things that "Just Work"

**Comment by mvccogo** [comment]
> The main problem is the user has to KNOW they're using Physics Interpolation, something a Beginner WILL NOT KNOW, nor be informed of the implications of using it, and you totally missed the point of the 2 examples I've given above. I know that that function exists, I also know that I can disable Physics Interpolation and do my custom logic easily.
> 
> A User that doesn't even KNOW they're using Physics Interpolation will not KNOW that they need to reset physics interpolation when teleporting, nor that there may be cases where they need to write their own Interpolation Logic, simply because they won't even KNOW that they're using the Feature, It'll just Manifest to them as Bugs that'll needlessly frustrate the unaware users
> 
> Physics Interpolation can be Heavily Recommended in the Documentation with getting started (and project setting) and all with all the relevant links to the documentation regarding proper usage, but it cannot be stressed enough, this **CANNOT** be on by default.
> 
> Don't get me wrong, I'd love to have Physics Interpolation as Standard, but this cannot be enforced by Godot, as Godot can only enforce things that are blatantly obvious to the user, or things that "Just Work"

I am not entirely convinced that having it enabled by default is the correct thing, but this argument does not make much sense. There are thousands of things a Godot beginner will also not KNOW, and that's why the documentation exists. In contrast, how many "camera jitter bugs" would go away if interpolation was on by default? It seems like a rite of passage that could easily be dealt with now.

A Godot beginner will most likely go through the "Getting Started" articles, so why can't we respect them a bit more and assume they will also read a big warning note if it is added there?
