### PR TITLE
Removed faulty function update after get_property_list.

### LINKED ISSUE #63668: Exported variable appears doubled in object inspector
### Godot version

4.0-13 Alpha

### System information

Linux-Ubuntu 22.04 Vulkan RTX 3050

### Issue description

exported variable appears double in object inspector

### Steps to reproduce

exported variable appears double in object inspector

### Minimal reproduction project

[Godot4Game.zip](https://github.com/godotengine/godot/files/9225651/Godot4Game.zip)

### PR DESCRIPTION
**Pull request by object71**
The function tried to rearrange properties but that lead to problems with duplication or deleted properties. Implemented the logic that that function did inside the get_property_list both for tool scripts and non-tool scripts.

Fixes #63668

There shouldn't be an update function that rearranges properties in the first place. If there was a requirement for properties to be split into categories based on the class inheritance this should've initially been implemented into GDScript or GDScriptInstance function for getting properties.

NOT TESTED on GDExtension and C# scripts but it should work.

### CODE REVIEW

File: core/object/script_language.cpp [hunk 1]
```diff
@@ -34,6 +34,7 @@
 #include "core/core_string_names.h"
 #include "core/debugger/engine_debugger.h"
 #include "core/debugger/script_debugger.h"
+#include "editor/editor_node.h"
```
Comment (akien-mga) [inline core/object/script_language.cpp:37]: Core should not depend on Editor.
The info you're getting from it is likely in ClassDB.

Comment (object71) [reply core/object/script_language.cpp:37]: OK, I think I can implement it without the editor too.

File: modules/mono/csharp_script.cpp [hunk 2]
```diff
@@ -2335,17 +2342,18 @@ void CSharpScript::_placeholder_erased(PlaceHolderScriptInstance *p_placeholder)
...
 void CSharpScript::_update_exports_values(HashMap<StringName, Variant> &values, List<PropertyInfo> &propnames) {
-	if (base_cache.is_valid()) {
-		base_cache->_update_exports_values(values, propnames);
-	}
-
 	for (const KeyValue<StringName, Variant> &E : exported_members_defval_cache) {
 		values[E.key] = E.value;
 	}
 
+	propnames.push_back(get_class_category());
```
Comment (raulsntos) [inline modules/mono/csharp_script.cpp:2349]: In GDScript you are missing this line, not sure if this was an oversight.

Comment (object71) [reply modules/mono/csharp_script.cpp:2349]: In gdscript this line is added on another place. I need to see how to do a mono build to see whether c# works

Comment (object71) [reply modules/mono/csharp_script.cpp:2349]: To be more precise GDScript usss placholder script when the script is not defined as @tool

**Comment by object71** [comment]
I cannot compile for mono, can anybody confirm that c# scripts look okay innthe inspector both for rool an non tool scripts with inheritance?

**Comment by raulsntos** [comment]
To compile mono you need to rebase and apply PR #63537 because currently the mono module is broken in `master`. With those changes `master` should compile, but your PR still has an issue, it can be fixed with this patch:

```diff
diff --git a/modules/mono/csharp_script.cpp b/modules/mono/csharp_script.cpp
index 0e3c17557c..62463e787a 100644
--- a/modules/mono/csharp_script.cpp
+++ b/modules/mono/csharp_script.cpp
@@ -1806,7 +1806,6 @@ void CSharpInstance::get_property_list(List<PropertyInfo> *p_properties) const {
 	}
 
 #ifdef TOOLS_ENABLED
-	Ref<Script> script = get_script();
 	if (script->is_valid()) {
 		props.push_front(script->get_class_category());
 	}
```

This is probably what you intended to do, you were shadowing the `script` member with `get_script` which just returns it with a less specific type so we can't access the `script_class` and `native` members later. With those changes this PR seems to be working fine.

**Comment by object71** [comment]
> To compile mono you need to rebase ~and apply PR #63537 because currently the mono module is broken in `master`~ (**Edit:** the PR was merged and the mono module should be working in `master` now). With those changes `master` should compile, but your PR still has an issue, it can be fixed with this patch:
> 
> ```diff
> diff --git a/modules/mono/csharp_script.cpp b/modules/mono/csharp_script.cpp
> index 0e3c17557c..62463e787a 100644
> --- a/modules/mono/csharp_script.cpp
> +++ b/modules/mono/csharp_script.cpp
> @@ -1806,7 +1806,6 @@ void CSharpInstance::get_property_list(List<PropertyInfo> *p_properties) const {
>  	}
>  
>  #ifdef TOOLS_ENABLED
> -	Ref<Script> script = get_script();
>  	if (script->is_valid()) {
>  		props.push_front(script->get_class_category());
>  	}
> ```
> 
> This is probably what you intended to do, you were shadowing the `script` member with `get_script` which just returns it with a less specific type so we can't access the `script_class` and `native` members later. With those changes this PR seems to be working fine.

Thanks, will fix that one!

**Comment by object71** [comment]
Managed to get mono running and fixed the inspector for mono too. It now looks good both for inherited, tool and non-tool scripts. :)

**Comment by raulsntos** [comment]
Awesome, thank you for adding categories to mono :+1:

It seems the changes from `push_front` to `push_back` are causing the exported properties in mono to be reversed now:

GDScript | C#
-|-
gd | csharp

**Comment by object71** [comment]
Ah, ok. Will fix the ordering.

**Comment by object71** [comment]
Reveresed the properties addition for C#.

**Comment by lufog** [comment]
Checked on the artifact from actions, `@export_category(...)`, `@export_group(...)` and `@export_subgroup(...)` do not work.

**Comment by object71** [comment]
Thanks for the note. I forgot to test those new features. Will see to it.

**Comment by YuriSizov** [comment]
> Checked on the artifact from actions, `@export_category(...)`, `@export_group(...)` and `@export_subgroup(...)` do not work.

They seem to only work in tool scripts now.

**Comment by YuriSizov** [comment]
@object71 I figured how to fix the grouping annotations properly, you need to add a case in `GDScript::_update_exports()` to include them in member cache.

Something like this seems to be enough:
```
					case GDScriptParser::ClassNode::Member::GROUP: {
						members_cache.push_back(member.annotation->export_info);
					} break;
```

**Comment by YuriSizov** [comment]
I've tested some chaotic stuff with the aforementioned fix, and it seems to work as expected. For example, defining a category at the top of your script would hide the base script category, effectively overriding it. Pretty sweet!

https://user-images.githubusercontent.com/11782833/182671595-a596fcc8-d753-4484-8f6b-48dac3c8894f.mp4

There is a bug, though — when you change the exports on the base class, the inspector for the extending class does not react to these changes. You need to reload the scene to see the changes properly. This is probably outside of the scope for this particular PR, however.

Code looks way better now, and IMO makes sense. I'd like a review from @vnen on this.

File: modules/gdscript/gdscript.cpp [hunk 3]
```diff
@@ -325,16 +325,23 @@ void GDScript::_get_script_property_list(List<PropertyInfo> *r_list, bool p_incl
 		for (int i = 0; i < msort.size(); i++) {
 			props.push_front(sptr->member_info[msort[i].name]);
 		}
+
+#ifdef TOOLS_ENABLED
+		props.push_front(sptr->get_class_category());
```
Comment (YuriSizov) [inline modules/gdscript/gdscript.cpp:330]: A nitpick, but can probably push to `r_list` directly here.

File: modules/gdscript/gdscript.cpp [hunk 4]
```diff
@@ -1510,11 +1519,17 @@ void GDScriptInstance::get_property_list(List<PropertyInfo> *p_properties) const
 			props.push_front(sptr->member_info[msort[i].name]);
 		}
 
-		sptr = sptr->_base;
-	}
+#ifdef TOOLS_ENABLED
+		props.push_front(sptr->get_class_category());
```
Comment (YuriSizov) [inline modules/gdscript/gdscript.cpp:1523]: Same nitpick, can probably push to `p_properties` directly here.

**Review by YuriSizov — APPROVED** [review]

**Comment by object71** [comment]
Thanks for the great suggestions and fixes. I added them in the latest version. Yeah I noticed the thing where it requires a reload of the scene to catch up some variables but it seems to be due to no call to update for the cached variables and I think it would be out of the scope of this PR. It is complicated enough as it is.

**Comment by akien-mga** [comment]
I want this properly reviewed by @reduz but I expect this might take time to merge given the scope of the changes.

In the meantime, I was wondering if we should revert #58443 to fix the arguably "worse" regression in `master` / possibly alpha 14, until this new PR gets merged (and any changes from #58443 which are still needed can be added back here). WDYT?

**Comment by YuriSizov** [comment]
OR! We could merge it for alpha 14 and let the public testing commence 😛

Up to you, but either way we have a rather prominent issue(s), whether we keep it as is or revert it.

**Comment by akien-mga** [comment]
Well I wouldn't merge a core change without reduz even looking at it. Especially not as a follow-up to another core change which I merged without his review, which he then said was hacky, and which introduced a regression :)

**Review by reduz — APPROVED** [review]

**Comment by YuriSizov** [comment]
To be fair, he said it was okay to merge it, just needed comments, and he called the method itself hacky, and the method was added in 2020, and I agree that it's a big hack.

**Comment by akien-mga** [comment]
Well that's settled :smile:

**Comment by akien-mga** [comment]
Thanks!

**Comment by bfeber** [comment]
Can someone check if this breaks #62936?

**Comment by YuriSizov** [comment]
@bfeber I don't see why it would, the logic related to `type_name` which is used for the docs doesn't seem to be touched here.

**Comment by bfeber** [comment]
It does break it, just tested and compared the GitHub Actions builds.

**Comment by YuriSizov** [comment]
For future reference, the discussion continued in https://github.com/godotengine/godot/issues/63997.

File: core/object/script_language_extension.h [hunk 5]
```diff
@@ -663,6 +663,14 @@ class ScriptInstanceExtension : public ScriptInstance {
 		if (native_info->get_property_list_func) {
 			uint32_t pcount;
 			const GDNativePropertyInfo *pinfo = native_info->get_property_list_func(instance, &pcount);
+
+#ifdef TOOLS_ENABLED
+			Ref<Script> script = get_script();
+			if (script->is_valid() && pcount > 0) {
```
Comment (Gallilus) [inline core/object/script_language_extension.h:669]: Hi @object71 do you remember wy you use `x->valid()` in stead off `x.valid()`?
-> makes my GDExtension crash so before making a PR I want to check if it was intentional.

Comment (Zylann) [reply core/object/script_language_extension.h:669]: I think it might need both (`Ref::is_valid` and `Script::is_valid`)

Comment (kleonc) [reply core/object/script_language_extension.h:669]: It indeed should be `script.is_valid()` as it's the reference which needs to be validated before dereferencing it down below in `script->get_class_category()`.

---

 `script.is_valid()` will call:
https://github.com/godotengine/godot/blob/a83eb16fba5bb3da086b41cbd79e6f95b09eb8ee/core/object/ref_counted.h#L201

---

 `script->is_valid()` will dereference the stored `reference` pointer (possibly `nullptr`):
https://github.com/godotengine/godot/blob/a83eb16fba5bb3da086b41cbd79e6f95b09eb8ee/core/object/ref_counted.h#L104-L106
and call:
 https://github.com/godotengine/godot/blob/a83eb16fba5bb3da086b41cbd79e6f95b09eb8ee/core/object/script_language.h#L150

Comment (Gallilus) [reply core/object/script_language_extension.h:669]: What do you mean by "possibly crashing" ?

Comment (kleonc) [reply core/object/script_language_extension.h:669]: > What do you mean by "possibly crashing" ?

@Gallilus I mean if the `Ref<Script> script`'s private`Script *reference` member is indeed `nullptr` then `script->is_valid()` is equivalent to `nullptr->is_valid()`. And dereferencing `nullptr` is an undefined behavior, might result in a crash.

Hence before any `script->...` calls it should be ensured (e.g. by calling `script.is_valid()`) that it can be dereferenced.

Comment (Gallilus) [reply core/object/script_language_extension.h:669]: This may sound silly but I'm not jet a regular in C++ conversations.
With dereference you mean going true the pointer in the object to do stuff.
Not deleting it from memory.

Comment (Gallilus) [reply core/object/script_language_extension.h:669]: Also, I had a .ptr() in my code so ...

```
    MyClass my_object = memnew(MyClass);
    Ref<MyClass > reference_1 = *my_object;
    Ref<MyClass > reference_2a = reference_1;
    Ref<MyClass > reference_2b = reference_1.ptr();
    if (refrence_2b.is_valid()){
        // Is reference_2 a or b valid?
        // Will reference.is_valid() && refrence->is_valid() catch this problem?
    }
```
