### PR TITLE
Fix enums without class name not opening docs page

### LINKED ISSUE #17957: Ctrl+Click enums without a class name does not open a docs page
**Godot version:**
950d492

**Issue description & Steps to reproduce:**
In the script editor, Ctrl+Click enums values without a class name that does not belong to the global scope does not open a docs page.

eg:

In a script that extending from `KinematicBody2D` (which extends from `Node`, which has the enum `NOTIFICATION_ENTER_TREE`):
Ctrl+Click:
`NOTIFICATION_ENTER_TREE`           doesn't work
`Node.NOTIFICATION_ENTER_TREE`           works
`KinematicBody2D.NOTIFICATION_ENTER_TREE`           works

This is part of the unsolved issues raised in #17396

### PR DESCRIPTION
**Pull request by flashyincceo**
Fixes #17957

Ctrl+Click on an Enum in the script editor without a class name now opens the appropriate documentation, as opposed to ignoring the click.

Feedback welcome!

### CODE REVIEW

File: modules/gdscript/gdscript_editor.cpp [hunk 1]
```diff
@@ -2643,6 +2643,17 @@ Error GDScriptLanguage::lookup_code(const String &p_code, const String &p_symbol
 	context.base_path = p_base_path;
 	bool isfunction = false;
 
+	if (context._class && context._class->extends_class.size() > 0) {
+		bool success;
```
Comment (akien-mga) [inline modules/gdscript/gdscript_editor.cpp]: Seems fine overall, just two nitpicks:
- please initalize this bool to `false`;
- please move the definition of `bool isfunction` after the code you added, since it's used in the big switch and would be better defined above it as it was.

If you can make those changes as an amend, that would be perfect. (See [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html)).

**Comment by flashyincceo** [comment]
@akien-mga I have made the suggested changes. Thank you!

**Comment by akien-mga** [comment]
Thanks!

**Comment by hpvb** [comment]
Cherry picked into 3.0.3
