### PR TITLE
[3.x] Map 64-bit versions of `String.to_int` and `String.hex_to_int` over to GDScript

### LINKED ISSUE #56285: `String.hex_to_int()` parse int32 instead of int64
### Godot version

3.4.2.stable

### System information

Windows 10

### Issue description

Hello, I was writing some code in GDScript to parse an UUID from string to two `int64` and I found that if you try to parse values bigger than `0x7fffffff`, using `hex_to_int()` it gives you

```cpp
ERROR: Cannot represent 0xb5d54688 as integer, provided value is too big.
    at: (core/ustring.cpp:1721)
```
theoretically, because the `int` type in GDScript is a signed 64-bit integer it should parse until `0xffff ffff ffff ffff` or at least `0x7fff ffff ffff ffff` am I wrong ?

### Steps to reproduce

```gdscript
var test: int = 0xb6d6fc4e04a9
print(test) # correct, prints 201034472228009

print("0x7fffffff".hex_to_int()) # correct, prints 2147483647
print("0xb5d54688".hex_to_int()) # wrong, prints 2147483647
```

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Rubonnek**
Fixes #56285

~Also exposes the `with_prefix` parameter in `String.hex_to_int`.~

Edit: no longer exposing `with_prefix` through GDScript. See https://github.com/godotengine/godot/pull/56368#issuecomment-100324243,

### CODE REVIEW

**Review by aaronfranke — APPROVED** [review]
I haven't tested this but it makes sense to me. All it does is prevent clamping to 32-bit ints in GDScript while not breaking compatibility in the C++ code for 3rd-party modules. In master, the 64-bit versions are the only versions, so this makes the GDScript behavior identical to master without breaking compatibility anywhere.

File: core/variant_call.cpp [hunk 1]
```diff
@@ -215,6 +215,8 @@ struct _VariantCall {
 	static void _call_##m_type##_##m_method(Variant &r_ret, Variant &p_self, const Variant **p_args) { reinterpret_cast<m_type *>(p_self._data._mem)->m_method(); }
 #define VCALL_LOCALMEM0R(m_type, m_method) \
 	static void _call_##m_type##_##m_method(Variant &r_ret, Variant &p_self, const Variant **p_args) { r_ret = reinterpret_cast<m_type *>(p_self._data._mem)->m_method(); }
+#define VCALL_LOCALMEM0RI(m_type, m_method, m_internal_method) \
+	static void _call_##m_type##_##m_method(Variant &r_ret, Variant &p_self, const Variant **p_args) { r_ret = reinterpret_cast<m_type *>(p_self._data._mem)->m_internal_method(); }
```
Comment (akien-mga) [inline core/variant_call.cpp:219]: That's a bit weird IMO and unexpected that `to_int` in the scripting API will not call `to_int` in the core API. Needs discussion with @godotengine/core folks to see what's best.

Another option would be to just change `to_int()` to be 64-bit like in `master`. It would break compatibility but this change also breaks compatibility for the scripting API while introducing inconsistency.

**Comment by bruvzg** [comment]
Is there any reason to keep 32-bit versions of `*_to_int`? Unlikely any code depend on it being clamped to 32-bits. Maybe it's better to remove it and rename `*_to_int64` to `*_to_int` (like in `master`).

**Comment by Rubonnek** [comment]
> Is there any reason to keep 32-bit versions of `*_to_int`? Unlikely any code depend on it being clamped to 32-bits. Maybe it's better to remove it and rename `*_to_int64` to `*_to_int` (like in `master`).

Renaming the 64-bit function may trigger integer overflows due to implicit casting from 64-bit integers to 32-bit integers within the engine, which would then require a massive amount of changes across the engine if we want to catch those overflows. I personally see no reason for renaming the function since most of the calls seem to made to translate indexes, or handle data which is unlikely to be greater than 32-bits. Which is the main reason for holding back the function renaming given that this is the stable branch of the engine. And also, like @aaronfranke correctly stated, this PR does not break 3rd-party C++ modules which is important for a stable release.

**Review by akien-mga — APPROVED** [review]
We discussed and approved this approach in PR review meeting, it's a good way to fix it while minimizing compat breakage.

**Comment by akien-mga** [comment]
Thanks!
