### PR TITLE
Fix for..in range() resulting in floats instead of ints

### LINKED ISSUE #8278: range(n) allocates reals instead of integers
Why do I have to cast r?
`print(rs.find(1))` will return -1 without it.

```
func _ready():
	var rs = []
	
	for r in range(2):
		rs.append(int(r))
		#rs.append(r)
		
	print(rs.find(1))
```

Ubuntu
Master branch

### PR DESCRIPTION
**Pull request by bojidar-bg**
Fixes #8278, fixup of bfef8de1bc4f7a7b9617a7b181881129033a0b0e
Note that with this commit, there is difference between the following lines:
```gdscript
for i in range(5.0):
for i in 5:
  # i is TYPE_INT

# vs:

for i in 5.0:
  # i is TYPE_REAL
```

### CODE REVIEW

File: core/math/math_funcs.h [hunk 1]
```diff
@@ -178,6 +178,8 @@ class Math {
 		return abs(a - b) < CMP_EPSILON;
 	}
 
+	static _ALWAYS_INLINE_ bool is_whole_approx(real_t x) { return is_equal_approx(x, floor(x)); }
```
Comment (akien-mga) [inline core/math/math_funcs.h]: As I mentioned on IRC, this should probably be using `round(x)` instead of `floor(x)`. But the question remains for the `(int)` casting in `core/variant_op.cpp`.

Comment (bojidar-bg) [inline core/math/math_funcs.h]: Done. Also, made it round before casting to int, just in case it is better this way.

**Comment by RandomShaper** [comment]
Would this be interesting for 2.1? Or do you think it may break compatibility somehow?

**Comment by bojidar-bg** [comment]
@RandomShaper as I mentioned, this is a fixup of bfef8de1bc4f7a7b9617a7b181881129033a0b0e, so it should be cherrypicked only if the other commit is.

**Comment by RandomShaper** [comment]
I was just considering the range-gives-ints enhancement.

Do you think that thing, by itself, if back-ported to 2.1 would potentially
create some problems with current projects?

I mean, without the other enhancements.

**Comment by akien-mga** [comment]
As far as I know `range()` already gives ints in 2.1, no?

**Comment by reduz** [comment]
yes, it' s ints in 2.1

**Comment by RandomShaper** [comment]
Sorry, I didn't check. I was assuming that was something inherited from 2.1.

**Comment by reduz** [comment]
I think we should just change it to work with ints only, there's really no benefit for floats, and it's a little worst for performance. Python does not even allow floats.

**Comment by karroffel** [comment]
@bojidar-bg bump concerning reduz comment

**Comment by bojidar-bg** [comment]
@karroffel Ah, right, I sorta forgot I ever made this PR.. let's hope I will be able to fix it tonight 😃

**Comment by bojidar-bg** [comment]
Note: Changed implementation so that it can never result in floats... Not even when having a floating-point step.
