### PR TITLE
[iOS] Add device SOC list, update DPI list.

### LINKED ISSUE #110168: `OS.get_processor_name`doesn't seem to work on iOS
### Tested versions

- Reproducible in: 4.5.beta7

### System information

Godot v4.5.beta7 - iPhone XR - iOS 18.3.1

### Issue description

Put simply, calling `OS.get_processor_name` on iOS will seemingly always result in an error like so:

```
drivers/apple_embedded/os_apple_embedded.mm:419:get_processor_name(): Couldn't get the CPU model name. Returning an empty string. Method/function failed. Returning: ""
```

This seems to be due to `OS_AppleEmbedded::get_processor_name` relying on the `sysctl` name `machdep.cpu.brand_string`, which I believe only applies to macOS, but I could be wrong.

https://github.com/godotengine/godot/blob/52a5644b5f85eed80016c2dff905804e869df144/drivers/apple_embedded/os_apple_embedded.mm#L413-L420

I haven't tested this with older versions of Godot, but seeing as how this code hasn't changed in a while I have no reason to believe this is a recent regression.

### Steps to reproduce

1. Open the MRP project.
2. Export MRP project to iOS.
3. Run the project on an iOS device.
4. Note the failure/error.

### Minimal reproduction project (MRP)

[ios-processor-name.zip](https://github.com/user-attachments/files/22081806/ios-processor-name.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Seems like there's no way to get CPU name, only model name, so this PR adds model ↔ CPU list.

Fixes https://github.com/godotengine/godot/issues/110168 also updates DPI list.

### CODE REVIEW

**Comment by mihe** [comment]
Any chance I could argue for also removing the `ERR_FAIL_V_MSG` at the bottom of `OS_AppleEmbedded::get_processor_name`? Maybe we can replace it with a `print_verbose` instead or something?

Part of the motivation behind reporting #110168 was to hopefully avoid emitting this particular error, as it's proven to be prevalent and annoying for one of our clients, due to them sending all their errors off to an error reporting service.

Since there's no `OS.try_get_processor_name` or anything, there isn't a whole lot you can do to avoid this error, which basically leaves you having to explicitly filter it out before sending them off to the error reporting service, and since this solution relies on continuously adding new models to this list, it would seem guaranteed that you'll run into this error again eventually.

For what it's worth, Android relies on the default `OS::get_processor_name`, which just returns an empty string without any error, so I don't think it's too out-of-place to just remove this `Couldn't get the CPU model name` error altogether and have the fallback be an empty string.

https://github.com/godotengine/godot/blob/6339f31a0217038ce6ed5e16776e34654895edc6/core/os/os.cpp#L439-L441

**Comment by bruvzg** [comment]
> Any chance I could argue for also removing the ERR_FAIL_V_MSG at the bottom of OS_AppleEmbedded::get_processor_name? Maybe we can replace it with a print_verbose instead or something?

I guess this makes sense, there's no benefit from this error, and it will inevitably fail in some conditions (when old versions are used on yet to be released devices).

File: platform/ios/device_metrics.mm [hunk 1]
```diff
@@ -183,6 +193,15 @@ + (NSDictionary *)dpiList {
...
 			@"iPhone15,3", // iPhone 14 Pro Max
+			@"iPhone15,4", // iPhone 15
+			@"iPhone15,5", // iPhone 15 Plus
+			@"iPhone16,1", // iPhone 15 Pro
+			@"iPhone16,2", // iPhone 15 Pro Max
+			@"iPhone17,1", // iPhone 16 Pro
+			@"iPhone17,2", // iPhone 16 Pro Max
+			@"iPhone17,3", // iPhone 16
+			@"iPhone17,4", // iPhone 16 Plus
+			@"iPhone17,5", // iPhone 16e
```
Comment (akien-mga) [inline platform/ios/device_metrics.mm:214]: Should this be updated with iPhone 17 stuff?

File: platform/ios/device_metrics.mm [hunk 2]
```diff
@@ -183,6 +193,15 @@ + (NSDictionary *)dpiList {
...
 		] : @460,
```
Comment (akien-mga) [inline platform/ios/device_metrics.mm:219]: I'm not familiar with this syntax, is that a magic value that needs to be updated if the array size changes?

File: platform/ios/device_metrics.mm (hunk 1 above)
Comment (bruvzg) [reply platform/ios/device_metrics.mm:214]: Yes, will update it a bit later today.

File: platform/ios/device_metrics.mm (hunk 2 above)
Comment (bruvzg) [reply platform/ios/device_metrics.mm:219]: No, the number is DPI of devices in the sub list.

**Comment by bruvzg** [comment]
https://github.com/godotengine/godot/commit/047a7c5aa56021d7a71db42aef88d9c80a34112e

Seems like something went wrong and commit before I have added latest set of devices got merged, while PR still show as open.
