### PR TITLE
NodePath properly updated in the editor in more cases when nodes are moved or renamed

### LINKED ISSUE #49810: NodePath in built-in node properties is invalid after moving/renaming node
### Godot version

3.3.2.stable, 4.0.dev (92f20fd70e6957cd65ccb7837fdc28f9b1e4a315)

### System information

Windows 10

### Issue description

`NodePath` properties are kept up-to-date in the editor when the path changes for script export variables, but not for built-in nodes (for example bodies in physics joints).

### Steps to reproduce

Using the minimal reproduction project:

1. Open the project in the editor
2. Select `Spatial6/PinJoint` node in the tree
3. Observe the path for `node_a` property: `../RigidBody` (which is correct)
4. Move `RigidBody` node as a child of `PinJoint` node
5. Select `Spatial6/PinJoint` node again
6. Observe the path for `node_a` property: `../RigidBody` (now incorrect)

The same thing happens with `RemoteTransform`, or any other built-in node using a `NodePath` property.

### Minimal reproduction project

3.x version:
[NodePathBug.zip](https://github.com/godotengine/godot/files/6688866/NodePathBug.zip)

4.0 version:
[NodePathBug-4.0.zip](https://github.com/godotengine/godot/files/6688867/NodePathBug-4.0.zip)

### LINKED ISSUE #49811: NodePath in Array or Dictionary export variable is invalid after moving/renaming node
### Godot version

3.3.2.stable, 4.0.dev (92f20fd70e6957cd65ccb7837fdc28f9b1e4a315)

### System information

Windows 10

### Issue description

`NodePath` properties are kept up-to-date in the editor when the path changes for script export variables, except when nested in `Array` and `Dictionary` properties.

### Steps to reproduce

Using the minimal reproduction project:

1. Open the project in the editor
2. Select `Spatial2/Spatial4` node in the tree
3. Observe the node path in all script variables: `Spatial3`
4. Move `Spatial3` node as a child of `Spatial5` node
5. Select `Spatial2/Spatial4` node again
6. Observe the node path in `test_path` has been updated to reflect the change
7. Observe the node path is not updated in the array and dictionary properties

### Minimal reproduction project

3.x version:
[NodePathBug.zip](https://github.com/godotengine/godot/files/6688866/NodePathBug.zip)

4.0 version:
[NodePathBug-4.0.zip](https://github.com/godotengine/godot/files/6688867/NodePathBug-4.0.zip)

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
Fix more cases of node path needing an update when nodes are renamed or moved in the editor.

**Built-in node properties:**
Before, node paths were checked only for script export variables. Now all properties are checked from the node, which includes built-in node properties.
Allows proper node path updates for nodes like remote transform, physics joints, etc.

**Arrays and dictionaries:**
Node paths nested in array and dictionary properties are now also updated in the editor.

Also update the documentation to be clear about node path update in the editor and at runtime.

Fixes #49810
Fixes #49811

Credits to @latorril for finding the issue and investigating the cause.

### CODE REVIEW

**Comment by pouleyKetchoupp** [comment]
Pushed a fix for errors in `AnimationPlayer` due to gathering all properties for checking node paths. Now only properties marked as editor or storage are checked.

File: editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -1409,9 +1409,102 @@ void SceneTreeDock::fill_path_renames(Node *p_node, Node *p_new_parent, List<Pai
...
+				rel_path_new = root_path_new.rel_path_to(rel_path_new);
+			}
+
+			p_node_path = rel_path_new;
+			return true;
+		}
+
+		// Update the node itself if it has a valid node path and has not been deleted.
+		if (p_root_path == F->get().first && p_node_path != NodePath() && F->get().second != NodePath()) {
+			NodePath abs_path = NodePath(String(root_path_new).plus_file(p_node_path)).simplified();
```
Comment (pouleyKetchoupp) [inline editor/scene_tree_dock.cpp:1440]: Just pushed an extra fix here that fixes errors when moving a Skeleton node with BoneAttachment nodes as its children.

Building the new path now uses `root_path_new` instead of `p_root_path`, otherwise in cases where the root path **and** the child path change, this code would generate a buggy node path relative to the old root.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

File: editor/scene_tree_dock.h [hunk 2]
```diff
@@ -247,6 +247,9 @@ class SceneTreeDock : public VBoxContainer {
 	static SceneTreeDock *singleton;
 	static void _update_configuration_warning();
 
+	static bool _update_node_path(const NodePath &p_root_path, NodePath &p_node_path, List<Pair<NodePath, NodePath>> *p_renames);
+	static bool _check_node_path_recursive(const NodePath &p_root_path, Variant &p_variant, List<Pair<NodePath, NodePath>> *p_renames);
```
Comment (akien-mga) [inline editor/scene_tree_dock.h:251]: I was just wondering, do those actually need to be `static`?

Also, since `p_node_path` and `p_variant` are used to return new values, they should probably be named with a `r_` prefix instead (our convention for a mutable reference that will get changed by the method).

Comment (pouleyKetchoupp) [reply editor/scene_tree_dock.h:251]: They don't have to be `static` but they can. I generally set methods as `static` when possible to make it clear they don't use anything from the class. Do we have a different rule about when to use `static`?

Makes sense for the missing `_r`, prefix, I can make a fixup PR to change it.

Comment (akien-mga) [reply editor/scene_tree_dock.h:251]: > They don't have to be `static` but they can. I generally set methods as `static` when possible to make it clear they don't use anything from the class. Do we have a different rule about when to use `static`?

I don't think we have a specific rule, I'm just asking out of curiosity (and lack of expertise on the actual impact of making things static in C++). If it doesn't hurt and makes the code clearer, that's fine with me :)

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by Flavelius** [comment]
Does this fix InstancePlaceHolders too (https://github.com/godotengine/godot/issues/44720#issuecomment-793022167)?

**Comment by pouleyKetchoupp** [comment]
@Flavelius I don't know much about instance placeholders, but it looks like it's a different issue. What this PR fixes is `NodePath` that are used to point to a node in the scene, when the node is moved or renamed, while the problem in #44720 seems to be related to pointing to another scene as a file path when this path changes. Fixing #44720 would require specific editor code to update instance placeholders when files are moved in the file system.

**Comment by takaturre** [comment]
This feature is great, but there is one problematic use case, which could however be solved with something like: `PROPERTY_USAGE_NO_NODE_PATH_CORRECTION`

#### Background
In my case the problem occurs due to a custom "baking" system, where the source scene contains extra nodes and setup, which is then baked into a game-ready scene including various optimizations. One of the optimizations is storing all node paths within the baked scene as node paths from the root node of baking, so there's no need to get them many times. (On the unbaked / source side, things function like Godot expects: each paths starts from the node it's stored in.)

#### Problem
Due to the new auto correction feature (which I really like otherwise), I'm getting errors in these baked scenes - and even worse, Godot might in certain cases do the auto-correction which can completely mess up the functioning of the baked scene. 

#### Solution
However, if there was a corresponding flag in the `usage` of property info dictionaries (using `_get_property_list()`), it would be trivial to fix the problem in the script. (Note. There is a theoretic work-around by converting all NodePaths to Strings, but for example in my case, it would cause problems as I'm already using type_string to detect something else.)
