### PR TITLE
Enhance editor file dialog

### LINKED ISSUE #22509: Small bugs with Save Scene popup
**Godot version:**
3.1 2e87703

**OS/device including version:**
Windows 10

**Issue description:**

I don't create 3 separate issues because they seems to be interlinked and there are (probably) easy to solve

- [ ] 1. When I create Node in folder, delete this folder and try again to save a node, location of node is assigned to non-existent folder (which I a little before delete) and any try to save result this bug:

> ERROR: save: Condition ' err ' is true. returned: ERR_CANT_OPEN
   At: scene/resources/scene_format_text.cpp:1468

I think that editor should check if location exist and if not that should choose at the res:// folder

- [ ] 2. If I write the location(not choose by file manager) in the field with res://, the name of the node disappears.

- [x] 3. When I try to save scene without extension, editor show info about non valid extension - I think that will be better if editor will add .tscn to names without extension.

**Steps to reproduce:**

jfile

### PR DESCRIPTION
**Pull request by volzhs**
1. show valid directory path when opening editor file dialog
2. keep file name when changing path by entering path
3. add first extension in filter automatically if not given
4. remove directory in recent list if it's not valid anymore

Fix #22509

editor_file_dialog

### CODE REVIEW

**Comment by volzhs** [comment]
@Calinou @groud would you take a look? :smile:

File: editor/editor_file_dialog.cpp [hunk 1]
```diff
@@ -239,6 +238,14 @@ void EditorFileDialog::_save_confirm_pressed() {
 
 void EditorFileDialog::_post_popup() {
 	ConfirmationDialog::_post_popup();
+
+	// check non-existance path
```
Comment (Calinou) [inline editor/editor_file_dialog.cpp:242]:
```suggestion
	// Check if the current path doesn't exist and correct it.
```

File: editor/editor_file_dialog.cpp [hunk 2]
```diff
@@ -277,11 +284,17 @@ void EditorFileDialog::_post_popup() {
 			} else {
 				name = name.get_file() + "/";
 			}
-
-			recent->add_item(name, folder);
-			recent->set_item_metadata(recent->get_item_count() - 1, recentd[i]);
-			recent->set_item_icon_modulate(recent->get_item_count() - 1, folder_color);
+			bool exists = dir_access->dir_exists(recentd[i]);
+			if (!exists) {
+				// Remove invalid directory from Recent
```
Comment (Calinou) [inline editor/editor_file_dialog.cpp:289]:
```suggestion
				// Remove invalid directory from the list of Recent directories.
```

File: editor/editor_file_dialog.cpp [hunk 3]
```diff
@@ -432,9 +445,12 @@ void EditorFileDialog::_action_pressed() {
 			}
 		}
 
+		// add first extension of filter if no valid extension found.
```
Comment (Calinou) [inline editor/editor_file_dialog.cpp:448]:
```suggestion
		// Add first extension of filter if no valid extension is found.
```

**Review by Calinou — CHANGES_REQUESTED** [review]
Some comment style fixes, but the rest looks good to me :slightly_smiling_face:

**Comment by volzhs** [comment]
It's done. :smile:

**Review by Calinou — APPROVED** [review]

**Review by groud — APPROVED** [review]

**Comment by volzhs** [comment]
@Calinou @groud Thanks for your review. :+1:

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
