### PR TITLE
Editor: Improve Signal Dock for script classes

### LINKED ISSUE #80397: GScript Documentation Comments for Signals are not Displaying as Expected in the Node Tab
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

v4.1.1.stable.official [bd6af8e0e]

### Issue description

In-script documentation (`##`) for `signal` members is not appearing in the _Node_ tab as expected.  Other documentation appears to work correctly in the _Inspector_ tab.

Working example (exported variable):
GodotDocumentationWorking

Non-working example (`signal`)
GodotDocumentationNotWorking

I have tried deselecting and reselecting the associated Node, changing between the tabs on the left pane, changing active scripts and even restarting Godot - nothing makes it work.  According to the [GScript Documentation on Documentation Comments](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_documentation_comments.html), this **should** work, right?  Or is there something completely obvious that I am missing?

### Steps to reproduce

1. In Godot, create a new Node of type `Node`
2. Attach a new script to this Node, accepting all current defaults
3. In the script editor create a `signal` called `Foo` and right above it, create a `##` comment for it
4. Also create an `@export`ed integer variable called `Bar` and also create a `##` comment for it
5. Unselect and reselect the Node in the _Scene_ tab to refresh the _Inspector_ and _Node_ tabs
6. Hover over the variable in the _Inspector_ tab and see that the added description is shown correctly
7. Hover over the signal in the _Node_ tab and see that the added description is **not** shown and "_No description._" is shown instead

This is an example of the script that could be added:
```
## This is signal foo!
signal Foo

## This is exported signal bar!
@export var Bar : int = 0
```

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by dalexeev**
* Add signal documentation for script classes.
* Use separate sections for script class inheritance.

**Before**

**After**

* Closes #80397.

### CODE REVIEW

File: editor/connections_dialog.cpp [hunk 1]
```diff
@@ -1320,32 +1363,25 @@ void ConnectionsDock::update_tree() {
...
 							}
 						}
-						if (!F->value.inherits.is_empty()) {
-							F = dd->class_list.find(F->value.inherits);
-						} else {
-							break;
-						}
 					}
-					descr_cache[base][signal_name] = descr;
+					descr_cache[doc_class_name][signal_name] = descr;
```
Comment (dalexeev) [inline editor/connections_dialog.cpp:1384]: The cache is not invalidated until the editor is restarted. This is good for native classes, but bad for scripts. Perhaps we should not cache script signal descriptions?

We could also move the loop outside to prevent unnecessary iterations (actually, this is not so important since a class usually has few signals).

Comment (akien-mga) [reply editor/connections_dialog.cpp:1384]: I guess not caching script signal descriptions might be fine, provided that it's not too costly to recompute each time.

Otherwise they could be cached separately, and the script cache entry marked dirty whenever the script changes.

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Comment by akien-mga** [comment]
Thanks!
