### PR TITLE
Fix errors about `UndoRedo` history mismatch when deleting bezier track

### LINKED ISSUE #95516: Deleting track from bezier curve editor emits errors about "UndoRedo history mismatch"
### Tested versions

Reproducible in: 4.3.rc [06fbc8395b3c0ec6fa38588caea2ee94837f7b97]

### System information

Windows 11 (10.0.22631)

### Issue description

This seems to be a fairly old bug, as I can reproduce it in Godot 4.1.4-stable even. Frankly I don't understand how this has gone unreported until now.

Basically, when deleting any track while in the bezier curve editor, you'll be met with these errors in your output log:

```
UndoRedo history mismatch: expected 0, got 1.
UndoRedo history mismatch: expected 0, got 1.
UndoRedo history mismatch: expected 0, got 1.
```

I have a PR lined up for it that I'll push shortly.

### Steps to reproduce

- Open the MRP
- Click the `AnimationPlayer` node in the Scene dock
- Open the bezier curve editor from the bottom of the Animation dock
- Delete any track
- Note errors

### Minimal reproduction project (MRP)

[broken-bezier-delete.zip](https://github.com/user-attachments/files/16611117/broken-bezier-delete.zip)

### PR DESCRIPTION
**Pull request by mihe**
Fixes #95516.

The issue seemed to be that this particular undo/redo action queues up do-methods for different objects, the first being the `AnimationBezierTrackEdit` and the second being the `Animation` itself, which causes this history mismatch.

I made use of ~~the recently introduced `EditorUndoRedoManager::force_fixed_history()` and~~ the `p_custom_context` parameter in `EditorUndoRedoManager::create_action` to force the history to be centered around one of these objects instead (the `AnimationBezierTrackEdit` instance) which seems to do the trick.

### CODE REVIEW

File: editor/animation_bezier_editor.cpp [hunk 1]
```diff
@@ -1083,7 +1083,8 @@ void AnimationBezierTrackEdit::gui_input(const Ref<InputEvent> &p_event) {
 					if (I.key == REMOVE_ICON) {
 						if (!read_only) {
 							EditorUndoRedoManager *undo_redo = EditorUndoRedoManager::get_singleton();
-							undo_redo->create_action("Remove Bezier Track");
+							undo_redo->create_action("Remove Bezier Track", UndoRedo::MERGE_DISABLE, this);
+							undo_redo->force_fixed_history();
```
Comment (KoBeWi) [inline editor/animation_bezier_editor.cpp:1087]:
```suggestion
							undo_redo->create_action("Remove Bezier Track", UndoRedo::MERGE_DISABLE, animation.ptr());
```
`force_fixed_history()` is unnecessary in this case.

Comment (mihe) [reply editor/animation_bezier_editor.cpp]: So it is, thank you!

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
