### PR TITLE
Fix compatibility shadow size not being initialized

### LINKED ISSUE #82503: OpenGL: Directional shadow rendering works in the editor, but not in the running project
### Godot version

4.2.dev fbe611e45

### System information

Fedora 38, GeForce RTX 4090 (NVIDIA 535.104.05)

### Issue description

Following the [implementation of 3D shadows](https://github.com/godotengine/godot/pull/77496), I've noticed that directional shadows fail to render in the running project, even though they work in the editor:

Screenshot_20230928_235923

Decreasing Max Distance shows that the shadow map is pure black:
 
Screenshot_20230929_000138

In the editor:

Screenshot_20230928_235934

### Steps to reproduce

- Add some meshes in a scene.
- Add a DirectionalLight3D node and enable shadows on it.

### Minimal reproduction project

[test_shadow_compatibility.zip](https://github.com/godotengine/godot/files/12754239/test_shadow_compatibility.zip)

### LINKED ISSUE #83060: OpenGL stereo render issue on Quest when shadow is enabled
### Godot version

4.2 dev6

### System information

Quest - Godot 4.2-dev6 - GL_compatibility renderer - OpenXR Loader 2.0.0 dev2

### Issue description

Enabling shadow when using the OpenGL renderer in stereo on Quest devices causes rendering issues. The issue only happens when XR is enabled. Running the same project without stereo doesn't cause rendering issues.

See videos below:
- With shadows enabled:

https://github.com/godotengine/godot/assets/914968/48c3331c-9931-424f-9cc1-16e6001913bb

- With shadows disabled:

https://github.com/godotengine/godot/assets/914968/7f20e820-a923-45c5-8f05-dd060f3a2cfb

### Steps to reproduce

- Create a new OpenXR project using gl_compatibility renderer
- Add directional lights with shadow enabled (the default setting)
- Export and run the project on a Quest device

### Minimal reproduction project

- Unzip and open the link repro project: https://drive.google.com/file/d/1TZuFhMVjankMpUpePADf5kIi0RjhTCgS/view?usp=sharing
- Install android build templates
- Export and run the project to a Quest device

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Took me way too long to find but turned out that in a runtime build, we were never initialising our size for our directional shadow maps in the compatibility renderer, only the RD renderer.

In an editor build this was getting loaded through `EditorNode::_update_from_settings` so the issue was kind of hidden.

- Fixes #82503
- Fixes #83060

### CODE REVIEW

File: drivers/gles3/storage/light_storage.cpp [hunk 1]
```diff
@@ -46,6 +47,11 @@ LightStorage *LightStorage::get_singleton() {
 
 LightStorage::LightStorage() {
 	singleton = this;
+
+	directional_shadow.size = GLOBAL_GET("rendering/lights_and_shadows/directional_shadow/size");
+	directional_shadow.use_16_bits = GLOBAL_GET("rendering/lights_and_shadows/directional_shadow/16_bits");
+
+	// lightmap_probe_capture_update_speed = GLOBAL_GET("rendering/lightmapping/probe_capture/update_speed");
```
Comment (AThousandShips) [inline drivers/gles3/storage/light_storage.cpp:54]:
```suggestion
	//lightmap_probe_capture_update_speed = GLOBAL_GET("rendering/lightmapping/probe_capture/update_speed");
```

Comment (BastiaanOlij) [inline drivers/gles3/storage/light_storage.cpp:54]: I added this as a comment so we don't overlook this once we make the lightmapper work.

**Comment by akien-mga** [comment]
Likely fixes #82503 too?

File: drivers/gles3/storage/light_storage.cpp (hunk 1 above)
Comment (BastiaanOlij) [reply drivers/gles3/storage/light_storage.cpp:54]: No space ? I hate no space :P

**Comment by BastiaanOlij** [comment]
> Likely fixes #82503 too?

That would seem logical

**Comment by akien-mga** [comment]
> > Likely fixes #82503 too?
> 
> That would seem logical

Tested and confirmed.

**Review by akien-mga — APPROVED** [review]

**Review by clayjohn — APPROVED** [review]
Aahhhh this is an embarrassing mistake. 

Looks good

File: drivers/gles3/storage/light_storage.cpp (hunk 1 above)
Comment (AThousandShips) [reply drivers/gles3/storage/light_storage.cpp:54]: (but yes commented out code has no leading space but text does, for clarity)

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` 4b7cc99bc195387c784efced7fdd360501d9a5cf), it works as expected.

**Comment by akien-mga** [comment]
Thanks!
