### PR TITLE
Fix selection undo

### LINKED ISSUE #14835: Selections are not stored in the text operations for Undo
**Godot version:**
2.1.4, 3.0 current master a714e1a

**OS/device including version:**
Windows 8.1

**Issue description:**
 - In the script editor, or a the `TextEdit` node, when you undo text editing, the cursor moves where it was at that time, but not the selection.

 - If you undo while text is selected somewhere else, the selection remains.

 - If the selected text moves when undoing, the selection will keep its global position, and thus, will not keep the same words selected.
(Fixing that will fix the last issues in #14559)
undo3

### PR DESCRIPTION
**Pull request by zqyoung1**
Properly resets text selection when an undo occurs
Fully fixes #14835

### CODE REVIEW

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -5340,6 +5340,9 @@ void TextEdit::undo() {
 
 	TextOperation op = undo_stack_pos->get();
 	_do_text_op(op, true);
+	if(op.from_line != op.to_line || op.to_column != op.from_column + 1)
```
Comment (YeldhamDev) [inline scene/gui/text_edit.cpp]: Needs a space after the `if`.

Comment (zqyoung1) [reply scene/gui/text_edit.cpp]: My apologies. should be fixed.

**Comment by YeldhamDev** [comment]
The commits should now be squashed:
https://godot.readthedocs.io/en/3.1/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by YeldhamDev** [comment]
Weird, the clang check if failing because it sees a trailing whitespace, but there's none in the commit itself.

**Comment by zqyoung1** [comment]
Yeah that's very odd. Do you have any suggestions for how to proceed?

**Comment by YeldhamDev** [comment]
Try `git commit --amend` and `--force` push it again to trigger a new check, to see if this was just Travis being silly.

**Comment by YeldhamDev** [comment]
Yep, the static check succeeded this time.

**Comment by akien-mga** [comment]
Thanks!
