### PR TITLE
Skip initializing the C# runtime when generating glue bindings

### LINKED ISSUE #75152: First-time build of .NET glue from source generates .NET runtime errors because config file does not yet exist
### Godot version

4.1dev (a7d0e18a31)

### System information

Windows 11, .NET SDK 6.0.407/7.0.202

### Issue description

When following the instructions on the [Compiling with .NET guide](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_with_dotnet.html), the very first attempt at the ["Generate the glue"](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_with_dotnet.html#generate-the-glue) step, with a clean `bin` directory, generates errors about being unable to find the .NET runtime, even with x64 .NET SDKs installed. These errors are apparently due to a missing configuration file, and do not actually seem to prevent successfully completing a .NET build. However, they could certainly appear to be showstopping issues to new users.

After invoking:
```
> scons p=windows target=editor module_mono_enabled=yes vsproj=yes [dev_build=yes]
> bin\godot.windows.editor[.dev].x86_64.mono --headless --generate-mono-glue modules\mono\glue
```

The following command-line errors and pop-up error dialog are shown (although the Godot binary proceeds to generate a large number of `.cs` files afterward):
```
ERROR: hostfxr_initialize_for_runtime_config failed with code: -2147450733
   at: (modules\mono\mono_gd\gd_mono.cpp:201)
ERROR: .NET: Failed to load compatible .NET runtime
   at: (modules\mono\mono_gd\gd_mono.cpp:278)
ERROR: Parameter "godot_plugins_initialize" is null.
   at: GDMono::initialize (modules\mono\mono_gd\gd_mono.cpp:411)
```
Error dialog

With a dev build, debugging shows the failure is in an attempt to load the configuration file `bin\GodotSharp\Api\Debug\GodotPlugins.runtimeconfig.json`. This file does not yet exist, but _will be generated as part of the next step in the instructions_, ["Building the managed libraries"](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_with_dotnet.html#building-the-managed-libraries).

After building the managed libraries, once the JSON config file is in place, the .NET errors do not appear in subsequent invocations of the Godot binary for generating the glue code, and the resulting dev build appears to successfully open and run a .NET Godot project.

I've prepared an edit to the Compiling with .NET documentation page, which I could set up a PR for -- it places a note on the glue step warning users about these errors. However, I'm unsure if that's the "right" solution or if some other change to the code or the docs is more appropriate (e.g., if the configuration file could be generated as part of the glue step, instead of the managed-libraries step).

### Steps to reproduce

- Clone a clean copy of the Godot source on Windows 11 with the .NET SDK installed, or delete all contents of the `bin` directory in the Godot source folder in an existing copy
- Run `scons` with `module_mono_enabled=yes`
- Run `bin\godot.windows.edit.x86_64.mono --headless --generate-mono-glue modules\mono\glue`
- Errors appear
- To resolve, run `python modules\mono\build_scripts\build_assemblies.py --godot-output-dir=bin` and try the `--generate-mono-glue` step again

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by shana**
Fixes #75152

This splits out the glue generator initialization fix from #76542 into its own PR.

The bindings generator doesn't require the C# runtime in order to generate the glue, and when it the glue generation runs, it exits immediately afterwards, so we can skip this initialization when the `--generate-mono-glue` flag is passed in.

In some platforms, like on macos M1 arm, trying to run the godot+mono binary on an incomplete installation crashes during the hostfx initialization, so #75152 is a bit more serious than just an annoying popup.

### CODE REVIEW

File: modules/mono/mono_gd/gd_mono.cpp [hunk 1]
```diff
@@ -385,6 +386,16 @@ static bool _on_core_api_assembly_loaded() {
 void GDMono::initialize() {
 	print_verbose(".NET: Initializing module...");
 
+#ifdef TOOLS_ENABLED
+	// Exit early if we're going to be generating glue code, so we can bootstrap the bindings without errors
+	List<String> cmdline_args = OS::get_singleton()->get_cmdline_args();
+	BindingsGenerator::process_cmdline(cmdline_args);
```
Comment (RedworkDE) [inline modules/mono/mono_gd/gd_mono.cpp:392]: I would maybe move this to an earlier point in `main`, instead of here as it doesn't feel like it belongs here and more like a trap waiting to happen when additional command line changes are done

**Review by RedworkDE — COMMENTED** [review]
Also this causes these 2 errors on exit after the glue generation:
```
ERROR: Pages in use exist at exit in PagedAllocator: union Variant::Pools::BucketMedium
   at: (C:\dir\godot\core/templates/paged_allocator.h:140)
ERROR: Pages in use exist at exit in PagedAllocator: union Variant::Pools::BucketSmall
   at: (C:\dir\godot\core/templates/paged_allocator.h:140)
```

Not sure what exactly causes them

File: modules/mono/mono_gd/gd_mono.cpp (hunk 1 above)
Comment (shana) [reply modules/mono/mono_gd/gd_mono.cpp:392]: Are you thinking right before the `ScriptServer::init_languages();` call in main.cpp, a few lines above the `generate_bindings` call?

**Comment by shana** [comment]
> Also this causes these 2 errors on exit after the glue generation:
> 
> ```
> ERROR: Pages in use exist at exit in PagedAllocator: union Variant::Pools::BucketMedium
>    at: (C:\dir\godot\core/templates/paged_allocator.h:140)
> ERROR: Pages in use exist at exit in PagedAllocator: union Variant::Pools::BucketSmall
>    at: (C:\dir\godot\core/templates/paged_allocator.h:140)
> ```
> 
> Not sure what exactly causes them

I'm not sure either, but I'm seeing them as well. I'll chase it down.

**Comment by shana** [comment]
> > Also this causes these 2 errors on exit after the glue generation:
> > ```
> > ERROR: Pages in use exist at exit in PagedAllocator: union Variant::Pools::BucketMedium
> >    at: (C:\dir\godot\core/templates/paged_allocator.h:140)
> > ERROR: Pages in use exist at exit in PagedAllocator: union Variant::Pools::BucketSmall
> >    at: (C:\dir\godot\core/templates/paged_allocator.h:140)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Not sure what exactly causes them
> 
> I'm not sure either, but I'm seeing them as well. I'll chase it down.

Turns out it's the allocation of the BindingsGenerator instance, it needs to go completely out of scope to get cleaned up properly before exiting. I need to add back a static trampoline that got dropped with the refactor.

File: modules/mono/mono_gd/gd_mono.cpp (hunk 1 above)
Comment (RedworkDE) [reply modules/mono/mono_gd/gd_mono.cpp:392]: TBH I didn't really think about where to best put this, just that this isn't it.
above init is probably fine.

I tried just moving the command line handling above the init call and if I add a theme db initialize to the bindings generator this appears to work just fine as well (the comment stating that the script server has to be initialized appears to be wrong)
```diff
diff --git a/main/main.cpp b/main/main.cpp
index 5e0187cc7fd..758711f1ebd 100644
--- a/main/main.cpp
+++ b/main/main.cpp
@@ -2406,20 +2406,19 @@ Error Main::setup2() {
 	initialize_navigation_server();
 	register_server_singletons();
 
-	// This loads global classes, so it must happen before custom loaders and savers are registered
-	ScriptServer::init_languages();
-
-	theme_db->initialize_theme();
-	audio_server->load_default_bus_layout();
 
 #if defined(MODULE_MONO_ENABLED) && defined(TOOLS_ENABLED)
 	// Hacky to have it here, but we don't have good facility yet to let modules
-	// register command line options to call at the right time. This needs to happen
-	// after init'ing the ScriptServer, but also after init'ing the ThemeDB,
-	// for the C# docs generation in the bindings.
+	// register command line options to call at the right time.
 	List<String> cmdline_args = OS::get_singleton()->get_cmdline_args();
 	BindingsGenerator::handle_cmdline_args(cmdline_args);
 #endif
+
+	// This loads global classes, so it must happen before custom loaders and savers are registered
+	ScriptServer::init_languages();
+	theme_db->initialize_theme();
+
+	audio_server->load_default_bus_layout();
 
 	if (use_debug_profiler && EngineDebugger::is_active()) {
 		// Start the "scripts" profiler, used in local debugging.
diff --git a/modules/mono/editor/bindings_generator.cpp b/modules/mono/editor/bindings_generator.cpp
index 8504fb2ac6a..2d77e5d2f76 100644
--- a/modules/mono/editor/bindings_generator.cpp
+++ b/modules/mono/editor/bindings_generator.cpp
@@ -39,6 +39,7 @@
 #include "core/io/file_access.h"
 #include "core/os/os.h"
 #include "main/main.h"
+#include "scene/theme/theme_db.h"
 
 #include "../godotsharp_defs.h"
 #include "../utils/naming_utils.h"
@@ -3967,6 +3968,7 @@ void BindingsGenerator::handle_cmdline_args(const List<String> &p_cmdline_args)
 	}
 
 	if (glue_dir_path.length()) {
+		ThemeDB::get_singleton()->initialize_theme();
 		handle_cmdline_options(glue_dir_path);
 		// Exit once done
 		cleanup_and_exit_godot();
```

The only diff that is causes in the generated code is the value of the `NativeCalls::godot_api_hash` of godotsharp but that files is actually unused anyways to this doesn't change anything.

Comment (neikeq) [reply modules/mono/mono_gd/gd_mono.cpp:392]: Indeed, the reason this was moved to main is to prevent a crash after some theme related changes were introduced: #74565. This PR effectively reverses that patch, so I would expect it to re-introduce that issue.

I can't review @RedworkDE's patch as I'm that is not my area, and it's easy to introduce a regression. I think it would be better to just skip C# initialization if the glue generation command line argument is detected:

```diff
void CSharpLanguage::init() {
+#ifdef TOOLS_ENABLED
+	if (OS::get_singleton()->get_cmdline_args().find("--generate-mono-glue")) {
+		return;
+	}
+#endif
```

Comment (shana) [reply modules/mono/mono_gd/gd_mono.cpp]: I moved things around a bit to try and make it cleaner without changing the existing initialization order (and hopefully not introduce regressions), see if it looks better. I would rather not hardcode the flag if I can help it, it makes the code more fragile - hopefully this latest refactor feels better.

File: modules/mono/editor/bindings_generator.cpp [hunk 2]
```diff
@@ -3919,57 +3919,67 @@ void BindingsGenerator::_initialize() {
...
-void BindingsGenerator::handle_cmdline_args(const List<String> &p_cmdline_args) {
-	String glue_dir_path;
-
+void BindingsGenerator::process_cmdline(const List<String> &p_cmdline_args) {
 	const List<String>::Element *elem = p_cmdline_args.front();
 
 	while (elem) {
 		if (elem->get() == generate_all_glue_option) {
-			const List<String>::Element *path_elem = elem->next();
+			elem = elem->next();
```
Comment (raulsntos) [inline modules/mono/editor/bindings_generator.cpp:3936]: This change didn't seem necessary and I think it's now missing a `elem->next()` inside the `if` below.

File: modules/mono/editor/bindings_generator.cpp [hunk 3]
```diff
@@ -3919,57 +3919,67 @@ void BindingsGenerator::_initialize() {
...
 static void cleanup_and_exit_godot() {
 	// Exit once done
 	Main::cleanup(true);
 	::exit(0);
 }
 
-void BindingsGenerator::handle_cmdline_args(const List<String> &p_cmdline_args) {
-	String glue_dir_path;
-
+void BindingsGenerator::process_cmdline(const List<String> &p_cmdline_args) {
```
Comment (raulsntos) [inline modules/mono/editor/bindings_generator.cpp:3931]: Why rename this method?

File: modules/mono/editor/bindings_generator.cpp [hunk 4]
```diff
@@ -3919,57 +3919,67 @@ void BindingsGenerator::_initialize() {
...
+
+	// Exit once done
+	cleanup_and_exit_godot();
+}
 
-	if (glue_dir_path.length()) {
-		handle_cmdline_options(glue_dir_path);
-		// Exit once done
-		cleanup_and_exit_godot();
+void BindingsGenerator::generate(const String &p_glue_dir_path) {
```
Comment (raulsntos) [inline modules/mono/editor/bindings_generator.cpp:3971]: This method seems to be the same as `handle_cmdline_options` so why rename it?

File: modules/mono/editor/bindings_generator.h [hunk 5]
```diff
@@ -787,7 +787,9 @@ class BindingsGenerator {
 
 	void _initialize();
 
-public:
```
Comment (raulsntos) [inline modules/mono/editor/bindings_generator.h:790]: Removing this `public:` makes the methods below private, which doesn't seem intentional.

File: main/main.cpp [hunk 6]
```diff
@@ -2406,6 +2406,13 @@ Error Main::setup2() {
 	initialize_navigation_server();
 	register_server_singletons();
 
+#if defined(MODULE_MONO_ENABLED) && defined(TOOLS_ENABLED)
+	// Process command lines relevant to the bindings generator before initializing
+	// the mono module, so it can skip runtime initialization if we're generating glue
+	List<String> cmdline_args = OS::get_singleton()->get_cmdline_args();
+	BindingsGenerator::process_cmdline(cmdline_args);
+#endif
```
Comment (raulsntos) [inline main/main.cpp:2414]: Why move this here? Can't we keep it below with `BindingsGenerator::generate_bindings()`? I would rather have all the .NET related hacks in one place instead of scattered around the `main.cpp`, if possible.

**Review by raulsntos — COMMENTED** [review]
I'm a bit confused about some of the changes in this PR, they don't seem necessary for the stated purpose but I may be missing some context.

Wouldn't it be enough with the changes made to `csharp_script.cpp`?

File: modules/mono/mono_gd/gd_mono.cpp (hunk 1 above)
Comment (raulsntos) [reply modules/mono/mono_gd/gd_mono.cpp]: I feel like **neikeq**'s suggestion would be enough and simpler than all the changes this PR is currently making. I don't think there's an issue with hardcoding the flag, we can keep it in a constant/static field if you prefer like in [`BindingsGenerator::generate_all_glue_option`](https://github.com/godotengine/godot/blob/964a5353dbf5fc0dca4c4b7b9cfa5631dd5ab568/modules/mono/editor/bindings_generator.cpp#L3921).

File: modules/mono/editor/bindings_generator.cpp (hunk 2 above)
Comment (shana) [reply modules/mono/editor/bindings_generator.cpp:3936]: The code prior to this needed to use the `path_elem` variable after the loop was done (which is why it was getting stored), but this refactor doesn't need it anymore, which is why I removed it. Once we're inside this if block, the iteration is done, it will always break out of the loop, so both this assigment to a separate variable and the `elem-next()` below aren't needed anymore, that's why it ended up like this.

File: modules/mono/editor/bindings_generator.cpp (hunk 4 above)
Comment (shana) [reply modules/mono/editor/bindings_generator.cpp:3971]: Because this doesn't handle command line options anymore, it just generates bindings, and I thought it would be confusing to be called handle_cmdline_options when it's not doing that at all.

File: modules/mono/editor/bindings_generator.cpp (hunk 3 above)
Comment (shana) [reply modules/mono/editor/bindings_generator.cpp:3931]: No strong reason, it was mostly because I've been moving code around to split up the flag parsing from the binding generation, and ended up renaming this one somewhere in the process, and didn't rename it back.

File: modules/mono/editor/bindings_generator.h (hunk 5 above)
Comment (shana) [reply modules/mono/editor/bindings_generator.h:790]: Yes, I did that on purpose because the generate_ methods aren't called anywhere outside the bindings generator, they're called from inside the bindings generator - `generate_cs_api` calls the others and calculates paths for them - so it didn't look like they were meant to be public api and just happened to be made public. But if they should be public api, happy to move them back!

File: main/main.cpp (hunk 6 above)
Comment (shana) [reply main/main.cpp:2414]: This is the problem - we need to process the command line and set up state before initializing scripting languages. The point where `generate_bindings` gets called happens after the hostfxr initialization, and it will crash if it tries to initialize with an incomplete installation, aborting the binding generation before it has a chance to run. The binding generation doesn't need hostfxr to be initialized, so we have to check the command line and skip the hostfxr initialization if the bindings generator is going to run.

I put this here so it's visually close to where the `BindingsGenerator::generate()` call is, so they're paired up and if someone goes to take one out, they won't miss the other call. I've also put it in `CSharpLanguage::init()` before this, and right before hostfxr initialization before that, and nobody likes any of the places where it goes. I totally get it, this is a hack, so it's not nice to have it anywhere! But we still have to do it in some way, otherwise the runtime is going to crash when trying to generate bindings. The hack was already there, I just had to split it up in order not to crash things while trying to be as minimal and helpful as possible.

**Comment by shana** [comment]
> I'm a bit confused about some of the changes in this PR, they don't seem necessary for the stated purpose but I may be missing some context.
> 
> Wouldn't it be enough with the changes made to `csharp_script.cpp`?

That's more or less what I had originally, but it was pointed out that the command line flag loop would have to run twice - once to see if the flag is set, and another to extract the path to use. That's why I moved the parsing of the command line out, to avoid looping twice, and then was told that main.cpp would be a better place for it. I would personally prefer using the existing code that checks for the command line option instead of hardcoding it (just because that usually leads to problems later on, in my experience), but where that check is, I don't have a strong opinion.

I'm happy to move the command line parsing and flag check bits back into csharp_script instead of in main.cpp, if that makes more sense to long term maintenance. I really have no preference, I was just following the suggestions. I would just really like to have this crash fixed.

File: modules/mono/editor/bindings_generator.cpp (hunk 3 above)
Comment (raulsntos) [reply modules/mono/editor/bindings_generator.cpp:3931]: If there's no strong reason to rename it, I would prefer to keep the original name. In general, I recommend avoiding unnecessary changes.

File: modules/mono/editor/bindings_generator.cpp (hunk 4 above)
Comment (raulsntos) [reply modules/mono/editor/bindings_generator.cpp:3971]: I don't really see the difference between this method and the old `handle_cmdline_options` and we could argue that `p_glue_dir_path` is the option that's being handled which comes from a cmdline argument.

File: modules/mono/editor/bindings_generator.h (hunk 5 above)
Comment (raulsntos) [reply modules/mono/editor/bindings_generator.h:790]: I don't know if they should be public, but this kind of change would probably be better in a separate PR. I recommend avoiding refactoring or stylistic changes unless they are relevant to the goal of the PR because, otherwise, it may add noise that makes it more difficult to review the PR and would take longer to get it merged.

File: main/main.cpp (hunk 6 above)
Comment (raulsntos) [reply main/main.cpp:2414]: Ah I see. I'm a little worried that scripting languages initialization may add stuff to ClassDB which the generator would need to know about, but I don't think that's the case.

> nobody likes any of the places where it goes

Well, I personally agree with **neikeq**'s comment (see https://github.com/godotengine/godot/pull/76659#discussion_r1183208369) and, if there's no agreement, I would default to what he recommends since he's the main .NET maintainer.

File: modules/mono/editor/bindings_generator.cpp (hunk 2 above)
Comment (raulsntos) [reply modules/mono/editor/bindings_generator.cpp:3936]: > Once we're inside this if block, the iteration is done, it will always break out of the loop

You are right, I think I didn't this before.

**Comment by shana** [comment]
Ok, I went back to the original one liner fix to skip the runtime initialization if we're generating glue, but moved to csharp_script, without any other changes.

**Review by raulsntos — APPROVED** [review]
LGTM.

**Comment by YuriSizov** [comment]
Thanks, and congrats on your first merged Godot PR!
