### PR TITLE
Fix inheriting from abstract classes dialog

### LINKED ISSUE #108242: Can't inherit abstract class using inheritance tree selector when creating new script
### Tested versions

- Reproducible in: master [efb40c1524e54f2cf52f213e248bd0a7b790975a]
- Reproducible in: 4.4.dev1
- Half-reproducible in: 4.3.dev1 (inherit button is not greyed out, but does nothing)

### System information

Godot v4.5.beta (efb40c152) - Windows 11 (build 26100)

### Issue description

It's not possible to select the class you want to inherit/extend when using the inheritance tree selector in the Create Script dialog, if the class is abstract. When manually inputting the class name in the text field it does work however.

The inherit button's tooltip also wrongly states: "The selected class can't be **instantiated**", which is irrelevant in the context of inheriting it.

As a side issue, even though the abstract classes are visible (but greyed out), they get filtered away when specifically searching for them. I guess that somewhat makes sense with how it currently works though.

Image

#71834 is similar, but there the problem is with built-in non-instantiable classes, that seem to be straight up impossible to inherit in C#? But in this case, the only reason you would make your own abstract class is to inherit it.

### Steps to reproduce

1. (Optional) Create a custom abstract class.
2. Start creation of a new script (e.g. by right-clicking a folder in FileSystem).
3. Click the Tree icon next to "Inherits:"
4. Attempt to inherit an abstract class (either your own, or a built-in one).

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by IphStich**
Fixes #108242

Script classes marked as abstract could not be selected when defining inheritence for newly created scripts.

Does not change behaviour for in-built abstract classes (which cannot be extended by scripts).

Unsure if this is the best implementation, but it fixes the problem.

### CODE REVIEW

File: editor/gui/create_dialog.h [hunk 1]
```diff
@@ -58,6 +63,7 @@ class CreateDialog : public ConfirmationDialog {
 	bool is_base_type_node = false;
 	String icon_fallback;
 	String preferred_search_result_type;
+	AbstractMode abstract_mode = ABSTRACT_MODE_CREATE;
```
Comment (KoBeWi) [inline editor/gui/create_dialog.h]: Why is this an enum? `bool allow_abstract` should be enough. And the method can be renamed to `set_allow_abstract()` or `enable_abstract()` (no parameters).

Comment (IphStich) [reply editor/gui/create_dialog.h]: [This](https://github.com/godotengine/godot/issues/108242#issuecomment-3048909721) comment suggested a possible confusion between native abstract classes, and abstract scripts. Native abstract classes cannot be extended from by scripts, but abstract scripts can (at least abstract GDScript classes). I was concerned that introducing further ambiguity would only increase confusion.

EDIT:

In my experience, it is often better to have something communicate intent rather than behaviour (especially where behaviour is the direct result of intent). That is what I was hoping to do here. While the only difference right now is in connection to abstract scripts, this might not be true into the future.

If we wanted to avoid using an enum (because it only has 2 states after all, so it *is* overkill) I would think that `bool for_inheritance` might be clearer. Another solution might be to create a new class (`InheritDialog` maybe) that internally sets any appropriate behaviour flags (rather than simply re-purposing the `CreateDialog`). Or still have the method be something like `for_inherit` that similarly sets any/all internal behaviour flags.

(These are just my views and thoughts. I am responding to what I read as a query for my views and reasoning. I respect your views as a maintainer, and I will change the PR if you say that I should. I am not attempting to argue.)

Comment (KoBeWi) [reply editor/gui/create_dialog.h]: That's just internal property. You can name it `allow_abstract_scripts` then.

Comment (IphStich) [reply editor/gui/create_dialog.h]: (Not sure why I didn't see your comment when I made my edit)

What do we think of splitting the class into `InheritDialog` and having both it and `CreateDialog` extend from a common `ClassHierarchyDialog` (or something)?

Comment (KoBeWi) [reply editor/gui/create_dialog.h]: Simple solutions are preferred, and editor code does not need to be perfect, it has to work and be maintainable. A bool flag is a fine solution here, and it can always be changed if needed, as long as it's not exposed to the users. New dialog class is a total overkill.

File: editor/gui/create_dialog.cpp [hunk 2]
```diff
@@ -392,7 +396,7 @@ void CreateDialog::_configure_search_option_item(TreeItem *r_item, const StringN
 	r_item->set_metadata(0, meta);
 
 	bool can_instantiate = (p_type_category == TypeCategory::CPP_TYPE && ClassDB::can_instantiate(p_type)) ||
-			(p_type_category == TypeCategory::OTHER_TYPE && !is_abstract);
+			(p_type_category == TypeCategory::OTHER_TYPE && !(is_abstract && !allow_abstract_scripts));
```
Comment (KoBeWi) [inline editor/gui/create_dialog.cpp]:
```suggestion
			(p_type_category == TypeCategory::OTHER_TYPE && (!is_abstract || allow_abstract_scripts));
```

File: editor/gui/create_dialog.cpp [hunk 3]
```diff
@@ -222,7 +226,7 @@ bool CreateDialog::_should_hide_type(const StringName &p_type) const {
 		// Abstract scripts cannot be instantiated.
 		String path = ScriptServer::get_global_class_path(p_type);
 		Ref<Script> scr = ResourceLoader::load(path, "Script");
-		return scr.is_null() || scr->is_abstract();
+		return scr.is_null() || (scr->is_abstract() && !allow_abstract_scripts);
```
Comment (KoBeWi) [inline editor/gui/create_dialog.cpp]:
```suggestion
		return scr.is_null() || (!allow_abstract_scripts && scr->is_abstract());
```
Cheaper checks first.

**Review by KoBeWi — APPROVED** [review]

File: editor/gui/create_dialog.cpp (hunk 2 above)
Comment (IphStich) [reply editor/gui/create_dialog.cpp]: I think it's better for the expression to mirror the one used in `_should_hide_type`? It should make it clearer to anyone reading the code that both represent the same logic if they have a similar structure.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
