### PR TITLE
FoldableContainer: Override `has_point` to use title rect when folded

### LINKED ISSUE #110834: FoldableContainers are not resized when folded, and continue to handle gui input in the hidden areas.
### Tested versions

- Reproducible in: 4.5.stable

### System information

Windows 11 - 4.5.stable

### Issue description

When a foldable container is folded, the control's size stays the same, and continues to receive gui input in the hidden area.

https://github.com/user-attachments/assets/7cf1943d-3e66-436d-a2d2-df8a76843f2c

https://github.com/user-attachments/assets/fc3ce4aa-ffdc-4b1b-87cd-b27bdefca774

### Steps to reproduce

1. fold a container that handles gui input
2. notice that it continues to handle gui input in the hidden / folded area

### Minimal reproduction project (MRP)

[foldable_container_mrp.zip](https://github.com/user-attachments/files/22499912/foldable_container_mrp.zip)

### PR DESCRIPTION
**Pull request by StamLord**
An attempt to fix https://github.com/godotengine/godot/issues/110834

Issue:
- Mouse pointer still changes appearance when hovering over the invisible (folded) part of a `FoldableContainer`

Solution:
- Override `Control::has_point` so that when folded, only the title rect is considered interactive. When unfloded, the default `Control` logic is used.

Notes:
- I copied the title rect logic from `FoldableContainer::gui_input`. This rect is being created 4 times (including my addition) across `_notification`, `gui_input` and now `has_point`. It might be useful to cache this and update on some size change event, or at the very least refactor the logic into a helper function.

### CODE REVIEW

File: scene/gui/foldable_container.cpp [hunk 1]
```diff
@@ -257,6 +257,15 @@ String FoldableContainer::get_tooltip(const Point2 &p_pos) const {
 	return String();
 }
 
+bool FoldableContainer::has_point(const Point2 &p_point) const {
+	if (folded) {
+		Rect2 title_rect = Rect2(0, (title_position == POSITION_TOP) ? 0 : get_size().height - title_minimum_size.height, get_size().width, title_minimum_size.height);
+		return title_rect.has_point(p_point);
```
Comment (KoBeWi) [inline scene/gui/foldable_container.cpp]:
```suggestion
		return _get_title_rect().has_point(p_point);
```

**Review by KoBeWi — APPROVED** [review]
Seems fine.

File: scene/gui/foldable_container.cpp (hunk 1 above)
Comment (akien-mga) [reply scene/gui/foldable_container.cpp]: I don't see a `_get_title_rect()` anywhere in the codebase?

Do you mean it should be added? There's a few occurrences of this line indeed which could be streamlined.

Comment (akien-mga) [reply scene/gui/foldable_container.cpp]: I see the OP's branch was older than #110871. I'll rebase it.

**Comment by akien-mga** [comment]
Cherry-picked for 4.5.2.
