### PR TITLE
Fix focus shortcuts triggering incorrectly

### LINKED ISSUE #8799: Tab key can't be used in editor shortcuts.
**Operating system or device - Godot version:**
Linux - Master

**Issue description:**
When pressing an Editor shortcut that involves the `Tab` key, Godot will focus the next `control` instead of activating the shortcut. Easily testable with the default "next/prev scene" shortcut.

**Steps to reproduce:**
- Have 2 or more scenes open.
- Press `ctrl + tab` or `ctrl + shift + tab`
- ...
- Don't Profit :(

### LINKED ISSUE #24064: Can't switch between tabs by Ctrl+Tab
**Godot version:** 3.0.6

**OS/device including version:** Xubuntu 18.04

**Issue description:** 

Ctrl+Tab and Ctrl+Shift+Tab doesn't work to switch between tabs. If I change keybindings and replace the Tab button to something else, it will work, but this is not a solution.

### PR DESCRIPTION
**Pull request by EricEzaM**
Closes #8799
Closes #24064

Supersedes / closes #47671
Supersedes / closes #34410

See video, where I can successfully use both change focus shortcuts and previous/next tab shortcuts. This uses the "exact match" checking system added in #44355. This should theoretically solve the issue for any bindings made for the related shortcuts.

https://user-images.githubusercontent.com/41730826/128587046-1297077c-5c21-4252-9655-9946bccdc479.mp4

### CODE REVIEW

**Comment by EricEzaM** [comment]
iOS build failed due to a cache error (not my codes fault! 😜 )

**Comment by EricEzaM** [comment]
Bump, if anyone is willing to review. Cheers.

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -3598,7 +3593,7 @@ void Viewport::_bind_methods() {
 	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "snap_2d_transforms_to_pixel"), "set_snap_2d_transforms_to_pixel", "is_snap_2d_transforms_to_pixel_enabled");
 	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "snap_2d_vertices_to_pixel"), "set_snap_2d_vertices_to_pixel", "is_snap_2d_vertices_to_pixel_enabled");
 	ADD_GROUP("Rendering", "");
-	ADD_PROPERTY(PropertyInfo(Variant::INT, "msaa", PROPERTY_HINT_ENUM, String::utf8("Disabled (Fastest),2× (Average),4× (Slow),8× (Slowest)")), "set_msaa", "get_msaa");
+	ADD_PROPERTY(PropertyInfo(Variant::INT, "msaa", PROPERTY_HINT_ENUM, String::utf8("Disabled (Fastest),2� (Average),4� (Slow),8� (Slowest)")), "set_msaa", "get_msaa");
```
Comment (EricEzaM) [inline scene/main/viewport.cpp:3596]: Umm... what?

Comment (akien-mga) [reply scene/main/viewport.cpp]: Yeah that's part of why I was concerned about adding such exotic UTF-8 chars to otherwise ASCII code for a somewhat limited use case.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

File: scene/main/viewport.cpp (hunk 1 above)
Comment (EricEzaM) [reply scene/main/viewport.cpp]: I just fixed it by adding the characters manually. Looked up the alt code for it.
