### PR TITLE
Fix theme properties not being handled correctly by `MultiNodeEdit`

### LINKED ISSUE #115057: Theme overrides properties display incorrect values when multi-selecting several Control nodes.
### Tested versions

- Reproducible in: 4.6rc1, 4.5.1stable, 4.5stable.

### System information

Godot v4.6.rc1 - Windows 10 (build 19045) - Multi-window, 1 monitor - Direct3D 12 (Mobile) - dedicated NVIDIA GeForce RTX 4070 (NVIDIA; 32.0.15.7628) - 12th Gen Intel(R) Core(TM) i5-12490F (12 threads) - 31.81 GiB memory

### Issue description

Take some Labels as an example:

Single-select:
Image

Multi-select:
Image

Demo:

https://github.com/user-attachments/assets/5e7cf204-13fe-48fa-b42a-357fbe775ad1

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by YeldhamDev**
- Fix default values not appearing (fixes #115057).
- Fix properties sometimes not appearing if some are overridden and others don't.

### CODE REVIEW

File: core/object/object.h [hunk 1]
```diff
@@ -160,13 +160,11 @@ enum PropertyUsageFlags {
 struct PropertyInfo {
 	Variant::Type type = Variant::NIL;
 	String name;
-	StringName class_name; // For classes
+	StringName class_name; // For classes.
 	PropertyHint hint = PROPERTY_HINT_NONE;
 	String hint_string;
 	uint32_t usage = PROPERTY_USAGE_DEFAULT;
 
-	// If you are thinking about adding another member to this class, ask the maintainer (Juan) first.
```
Comment (YeldhamDev) [inline core/object/object.h]: I took the liberty to remove this, since it's not really the case anymore.

File: editor/inspector/multi_node_edit.cpp [hunk 2]
```diff
@@ -189,8 +189,27 @@ void MultiNodeEdit::_get_property_list(List<PropertyInfo> *p_list) const {
...
+							F.usage |= PROPERTY_USAGE_STORAGE | PROPERTY_USAGE_CHECKED;
+						} else {
+							F.usage &= ~(PROPERTY_USAGE_STORAGE | PROPERTY_USAGE_CHECKED);
+						}
+
+						if (usage_data->info.usage != F.usage) {
+							continue;
+						}
+					}
+				}
```
Comment (KoBeWi) [inline editor/inspector/multi_node_edit.cpp:211]: Is there some way to de-duplicate this code?

**Review by KoBeWi — APPROVED** [review]

File: editor/inspector/multi_node_edit.cpp (hunk 2 above)
Comment (YeldhamDev) [reply editor/inspector/multi_node_edit.cpp:211]: The question is *where* the centralized code would reside. Considering that it exists only in two places, we can kick this can forward for a while.

**Comment by Repiteo** [comment]
Thanks!

**Comment by Repiteo** [comment]
Cherry-picked for 4.6.4.
