### PR TITLE
Bring back Geometry2D.segment_intersects_circle

### LINKED ISSUE #63845: Geometry2D.segment_intersects_circle missing in latest master
### Godot version

4.0-alpha13

### System information

ArchLinux

### Issue description

Not sure if this is a regression, if the function has been moved somewhere, or if it was considered obsolete. In 3.x, it's available as `Geometry.segment_intersects_circle`

Meanwhile, other helper functions including `segment_intersects_segment` are still available in 4.x.

### Steps to reproduce

1. `Geometry2D.segment_intersects_circle(...)`
2. Error: Static function "segment_intersects_circle()" not found in base "Geometry2D".

Missing in 4.x: https://docs.godotengine.org/en/latest/search.html?q=segment_intersects_circle&check_keywords=yes&area=default
Available in 3.x: https://docs.godotengine.org/en/stable/search.html?q=segment_intersects_circle&check_keywords=yes&area=default

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by hakro**
Bring back Geometry2D.segment_intersects_circle, which seems to have disappeared while splitting Geometry 2D and 3D
Fixes [#63845](https://github.com/godotengine/godot/issues/63845)

### CODE REVIEW

File: core/core_bind.cpp [hunk 1]
```diff
@@ -933,6 +933,7 @@ Dictionary Geometry2D::make_atlas(const Vector<Size2> &p_rects) {
 
 void Geometry2D::_bind_methods() {
 	ClassDB::bind_method(D_METHOD("is_point_in_circle", "point", "circle_position", "circle_radius"), &Geometry2D::is_point_in_circle);
+	ClassDB::bind_method(D_METHOD("segment_intersects_circle", "segment_from", "segment_to", "circle_position", "circle_radius"), &_Geometry::segment_intersects_circle);
```
Comment (akien-mga) [inline core/core_bind.cpp:936]: This should be `Geometry2D`, `_Geometry` doesn't exist.

**Comment by akien-mga** [comment]
You will also need to update the class reference for the new method: https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html

You could reuse the description from `3.x`.

File: core/core_bind.cpp (hunk 1 above)
Comment (hakro) [reply core/core_bind.cpp]: Thx. Rookie mistake, fixed now.

**Comment by akien-mga** [comment]
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by hakro** [comment]
Squashed !
Man, this is exciting. And the doc is so well written :)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
