### PR TITLE
Call `PopupMenu`  min. size calculations after `about_to_popup` signal processing.

### LINKED ISSUE #106668: PopupMenu: wrong height after removing items in `about_to_popup`
### Tested versions

- Single-window: reproducible since 4.5.dev2
- Multi-window: reproducible since 4.3 (not sure about the exact dev/beta/rc build)

### System information

Godot v4.3.stable - Arch Linux #‍1 SMP PREEMPT_DYNAMIC Fri, 09 May 2025 17:36:18 +0000 - X11 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3060 Ti (nvidia; 570.144) - 13th Gen Intel(R) Core(TM) i5-13400F (16 Threads)

### Issue description

When we need to dynamically add or remove menu items, we often handle this in the `about_to_popup` signal. There are many examples in editor code. Some submenus that display lists will `clear()` and `reset_size()` in this signal.

I recently found that if the menu has fewer items than before, it will still display using the old height.

Multi-window mode games (e.g., the editor uses this mode by default) have this behavior since 4.3.

Single-window mode games (see the MRP) have this behavior since 4.5.dev2.

### Steps to reproduce

Use the editor:

https://github.com/user-attachments/assets/0cc2ac2a-256c-47ac-994c-84fd51ed6469

Use the MRP:

https://github.com/user-attachments/assets/5a91e068-9536-49db-b34e-fda9df4a8167

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/20364769/mrp.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
`about_to_popup` can change menu items and content size, therefor min. size should be calculated after it is processed, not before, should have no effect on menus without `about_to_popup`.

Fixes https://github.com/godotengine/godot/issues/106668

### CODE REVIEW

File: scene/gui/popup_menu.cpp [hunk 1]
```diff
@@ -3211,21 +3211,24 @@ void PopupMenu::popup(const Rect2i &p_bounds) {
...
+	CanvasItem *c = Object::cast_to<CanvasItem>(get_parent());
+	if (c) {
+		scale *= c->get_global_transform_with_canvas().get_scale();
+	}
+	real_t popup_scale = MIN(scale.x, scale.y);
+	set_content_scale_factor(popup_scale);
+	Size2 minsize = get_contents_minimum_size() * popup_scale;
+	minsize.height = Math::ceil(minsize.height); // Ensures enough height at fractional content scales to prevent the v_scroll_bar from showing.
+	set_min_size(minsize); // `height` is truncated here by the cast to Size2i for Window.min_size.
+	set_size(Vector2(0, 0)); // Shrinkwraps to min size.
```
Comment (KoBeWi) [inline scene/gui/popup_menu.cpp]:
```suggestion
	reset_size();
```

**Review by KoBeWi — APPROVED** [review]

File: scene/gui/popup_menu.cpp (hunk 1 above)
Comment (akien-mga) [reply scene/gui/popup_menu.cpp]: Poke @bruvzg

**Comment by akien-mga** [comment]
Thanks!
