### PR TITLE
LSP: Add `godot` to known language ids

### LINKED ISSUE #115631: [4.6] LSP functionality is broken on KDE's Kate Editor
### Tested versions

- Broken on Godot 4.6
- Works on earlier versions

### System information

Godot v4.6.stable - EndeavourOS #1 SMP PREEMPT_DYNAMIC Sun, 11 Jan 2026 17:10:53 +0000 on Wayland - X11 display driver, Multi-window, 1 monitor - OpenGL 3 (Compatibility) - Mesa Intel(R) HD Graphics 630 (KBL GT2) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 threads) - 7.61 GiB memory

### Issue description

All LSP-related functionality (auto-completion, symbols, warning/error highlighting) has stopped working in Godot 4.6 when using KDE Plasma's default text editor (Kate).

Although it seems to be able to 'establish' a connection to the LSP, it prints the following error on repeat once you begin typing on the file.

```
ERROR: Bug: Dictionary::operator[] used when there was no value for the given key "context". Please report.
   at: operator[] (core/variant/dictionary.cpp:136)

ERROR: Bug: Dictionary::operator[] used when there was no value for the given key "triggerKind". Please report.
   at: operator[] (core/variant/dictionary.cpp:136)
```

#### LSP Configuration:
*I use the default Kate LSP settings for Godot (worked previously for 4.3 ... 4.5) using `openbsd-netcat` on Arch*

Image

#### Pre 4.6 (4.5.1):
*Everything works as per-usual*

Image

#### 4.6:
*Suggestions are only based on existing terms found on the active file, symbols are broken, and warnings/errors are not highlighted*

Image

### Related Issues (?)
From a quick search, there seems to be a similar [issue](https://github.com/godotengine/godot/issues/112099) from the beta versions.

### Steps to reproduce

Open any script under 4.6 in Kate and begin typing once the connection has been taken.

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by HolonProduction**
Fixes https://github.com/godotengine/godot/issues/115631 (not the error spam though)

Kate currently uses `godot` as language id for GDScript. I will probably try to upstream a change to `gdscript` at some point but for now we just handle this id like GDScript.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: modules/gdscript/language_server/godot_lsp.h [hunk 1]
```diff
@@ -695,10 +695,12 @@ struct TextDocumentItem {
 		version = p_dict["version"];
 		text = p_dict["text"];
 
-		// Clients should use "gdscript" as language id, but we can't enforce it. The Rider integration
-		// in particular uses "gd" at the time of writing. We normalize the id to make it easier to work with.
+		// Clients should use "gdscript" as language id, but we can't enforce it.
+		// We normalize some known ids to make them easier to work with:
+		// Rider: "gd"
+		// Kate: "godot"
```
Comment (akien-mga) [inline modules/gdscript/language_server/godot_lsp.h:701]: FYI @van800. I assume we'll have to keep supporting `gd` for a while for compatibility, but it could make sense for Rider to start using `gdscript`.

Comment (HolonProduction) [reply modules/gdscript/language_server/godot_lsp.h:701]: https://youtrack.jetbrains.com/issue/RIDER-133752/Change-languageId-for-Godot-to-gdscript

Comment (van800) [reply modules/gdscript/language_server/godot_lsp.h:701]: Yes, this one was fixed in Rider 2026.1 EAP 2, thank you for mentioning.

Comment (akien-mga) [reply modules/gdscript/language_server/godot_lsp.h:701]: Great, thanks!

Might be worth mentioning in the comment: "Rider < 2026.1:"
