### PR TITLE
Properly clear scene tiles

### LINKED ISSUE #74867: TileMap Unable to Clear Scene Tiles
### Godot version

4.0 stable

### System information

Windows 10

### Issue description

Running .clear() on a TileMap with Scene tiles leaves the tiles in place, as though nothing happened.

This appears to be the same issue as raised in [#69596](https://github.com/godotengine/godot/issues/69596), [#72456](https://github.com/godotengine/godot/pull/72456), and [67330](https://github.com/godotengine/godot/pull/67330). None of the previous issues seem to have presented a fix for this issue besides running some dummy operations on the TileMap, which have not had any effect for me.

Manually running queue_free() on each tile scene doesn't work, presumably since they are being cached. And running a dummy operation on the TileMap doesn't have any impact to speak of.

Not sure how to proceed, or if it's just impossible to remove Scene tiles once they're created.

### Steps to reproduce

The minimal reproduction project has a TileMap with several simple scene tiles. The attached script attempts to .clear() the TileMap when the user presses Enter, demonstrating my issue.

### Minimal reproduction project

[TileMapMinimumRecreationProject.zip](https://github.com/godotengine/godot/files/10959111/TileMapMinimumRecreationProject.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #74867

### CODE REVIEW

File: scene/2d/tile_map.cpp [hunk 1]
```diff
@@ -773,18 +773,7 @@ void TileMapLayer::_scenes_update_dirty_quadrants(SelfList<TileMapQuadrant>::Lis
...
-		if (instantiated_scenes.is_empty()) {
-			for (const KeyValue<Vector2i, String> &E : q.scenes) {
-				Node *node = tile_map_node->get_node_or_null(E.value);
-				if (node) {
-					node->queue_free();
-				}
-			}
-		}
-
-		q.scenes.clear();
```
Comment (KoBeWi) [inline scene/2d/tile_map.cpp:787]: `q.scenes()` should not be cleared if the cache exists, otherwise the scenes can't be removed anymore.

**Review by groud — APPROVED** [review]
I'll trust @KoBeWi on that one. I did not implement the scene caching system.

It will probably become obsolete once I find the time to implement the TileMap internal rework anyway, as scenes wont be grouped into a quadrant anymore.

**Review by YuriSizov — APPROVED** [review]
