### PR TITLE
fix Tween follow_property finishing with null

### LINKED ISSUE #29398: Tween's follow_property setting interpolated property to null as final value
**Godot version:**
3.1.1

**OS/device including version:**
Archlinux

**Issue description:**
I was experimenting with the Tween functions to understand how they work and noticed that follow_property() was leaving the final property value null. It does the interpolation quite normally but leaves the property value at null instead of at the target value.

I found a similar issue linked below. However, that user reported getting NaNs while I'm consistently getting "Null" for the final value.
(https://github.com/godotengine/godot/issues/19679)

**Steps to reproduce:**
Just call follow_property() and observe the value of the property after the tween has completed.

**Minimal example**
[tween_error.zip](https://github.com/godotengine/godot/files/3244786/tween_error.zip)

### PR DESCRIPTION
**Pull request by Klowner**
`final_val` is null within the `InterpolateData` for the duration of the tween because it's plucked from the follow property/method for the `_calc_delta_vel()` call, but not after tween finalization where it falls back to `p_data.final_val`.

This change adds `_get_final_val()` which is similar to the pre-existing `_get_initial_val()` and functions in much the same way.

Hopefully this is a good fix, any feedback is appreciated.

Fixes #29398.

### CODE REVIEW

**Comment by Klowner** [comment]
Fixes #29398

**Comment by Klowner** [comment]
While eating dinner last night I had the sudden realization that these two methods are likely not thread-safe. I'm not sure if that's a concern?

File: scene/animation/tween.cpp [hunk 1]
```diff
@@ -322,23 +322,16 @@ Variant &Tween::_get_initial_val(InterpolateData &p_data) {
...
-
 		case FOLLOW_PROPERTY:
 		case FOLLOW_METHOD: {
 			// We're following an object, so grab that instance
 			Object *target = ObjectDB::get_instance(p_data.target_id);
 			ERR_FAIL_COND_V(target == NULL, p_data.initial_val);
 
 			// We want to figure out the final value
-			Variant final_val;
+			static Variant final_val;
```
Comment (bojidar-bg) [inline scene/animation/tween.cpp]: This `static` worries me. Is it really necessary?

**Comment by Klowner** [comment]
Yeah that static bothers me as well. I just copied the general structure of
that other method and then I became concerned about those refs to statics
being returned which is presumably a threading race condition waiting to
happen.

I can refactor both methods to get rid of those statics.

File: scene/animation/tween.cpp (hunk 1 above)
Comment (Klowner) [reply scene/animation/tween.cpp]: statics removed

**Comment by bojidar-bg** [comment]
Maybe just make it return `Variant` and not `Variant&`?

**Comment by Klowner** [comment]
Sounds good, I'll do that

**Comment by Klowner** [comment]
:man_dancing:

**Review by bojidar-bg — APPROVED** [review]
LGTM, hopefully the performance impact from removing the `static` from `_get_initial_val` isn't too big.

**Comment by akien-mga** [comment]
Thanks!
