### PR TITLE
GDExtension: `PtrToArg::convert()` uses const-reference where possible

### LINKED ISSUE #80074: GDExtension: `PtrToArg::convert()` creates unnecessary copies
### Godot version

4.2-dev (branched off 75f9c97deaa8378477441e07ea1782ecab6d2eca)

### System information

Windows 10

### Issue description

Stumbled upon this while debugging equality between `StringName` instances (for unrelated issue #78580).

The GDExtension function pointer for equality calls `OperatorEvaluatorEqual<StringName, StringName>::ptr_evaluate()`.
This one checks `PtrToArg<A>::convert(left) == PtrToArg<B>::convert(right)`.

The function `PtrToArg::convert()` is defined as follows (substituted `m_type` with `StringName`):
```cpp
template <>                                                  
struct PtrToArg<m_type> {                                    
    _FORCE_INLINE_ static StringName convert(const void *p_ptr) {
        return *reinterpret_cast<const StringName *>(p_ptr);     
    }
}
```

`reinterpret_cast` returns an expression of type `const StringName*`.
Dereferencing that yields `const StringName&` (and **not `StringName`**).

The return type of `convert()` however is `StringName` (by value).
Unless I'm missing something, the C++ compiler cannot apply RVO here because we don't have a value, only a const-reference.

So this calls the copy-constructor `StringName::StringName(const StringName &p_name)` -- I verified this via debugger.

This copy is unnecessary for many operations which only have read access, like equality here. Even if `StringName` is cheap to copy, this still comes with refcount inc/dec + locking, when it would mostly need to compare two hashes.

### Steps to reproduce

Equality-compare two `StringName` objects in a GDExtension binding and step in via debugger. Copy constructor of `StringName` is invoked.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Bromeon**
Fixes #80074.

In the cases where `reinterpret_cast` is immediately dereferenced, `PtrToArg::convert()` returns a const-reference instead of a value. This allows to reuse the object located at the address of the passed `const void*` pointer, instead of triggering the copy constructor.

We cannot return const-references where temporary values are constructed. Most manual `PtrToArg` specializations fall under this category and are thus untouched.

In some cases, we now return a const-reference to scalar types like `int`, `bool` etc. Since the function is annotated as `_FORCE_INLINE_`, I expect any such indirections to be optimized away though.

I did some tests with the Rust binding (gdext) already, but I'd appreciate some input on this!

### CODE REVIEW

File: core/variant/typed_array.h [hunk 1]
```diff
@@ -145,8 +145,7 @@ struct PtrToArg<TypedArray<T>> {
 template <class T>
 struct PtrToArg<const TypedArray<T> &> {
 	typedef Array EncodeT;
-	_FORCE_INLINE_ static TypedArray<T>
-	convert(const void *p_ptr) {
+	_FORCE_INLINE_ static TypedArray<T> convert(const void *p_ptr) {
```
Comment (Bromeon) [inline core/variant/typed_array.h:148]: This is purely a whitespace change (should be more readable and still OK for clang-format) 🙂

**Comment by Bromeon** [comment]
CI job _Editor with doubles and GCC sanitizers_ failed with:
> ranlib: /home/runner/work/godot/godot/godot-cpp/bin/libgodot-cpp.linux.template_debug.dev.x86_64.a: No space left on device

I encountered the same issue in my own nightly builds, also gcc memcheck running out of disk space... Was there a regression? Or GitHub decreased available disk space?

**Comment by dalexeev** [comment]
@Bromeon See:

* #79919
* `#buildsystem` channel on Godot Contributors Chat.

**Comment by dsnopek** [comment]
Good catch!

This makes sense to me. Even outside the context of GDExtension, we do ptrcalls with code like:

```c++
template <class T, class... P, size_t... Is>
void call_with_ptr_args_helper(T *p_instance, void (T::*p_method)(P...), const void **p_args, IndexSequence<Is...>) {
	(p_instance->*p_method)(PtrToArg<P>::convert(p_args[Is])...);
}
```

In the case that one (or more) of the method's arguments takes a `const &`, this would also avoid a copy.

I ran godot-cpp's automated tests and they passed. So, this seems OK from the perspective of GDExtension. It could probably use to be reviewed by the core team as well.

**Comment by Bromeon** [comment]
Rebased onto `master`.

**Comment by dsnopek** [comment]
Discussed at the GDExtension meeting, and we think this makes sense. This is also on the agenda to discuss at the core team meeting, where we hope to double check with them that this won't cause any other problems.

**Comment by jsjtxietian** [comment]
Great Catch! 
For anyone who is intersted, I made a small demo in compiler explorer, even with `-O3` the copy can not be elimated.
https://godbolt.org/z/qPWP86WcG

**Review by dsnopek — APPROVED** [review]
The core team meeting I was hoping to discuss this at didn't end up really happening. It'd still be nice to have a review from someone on the core team, however, I personally really think this should be OK. This is adding `const &` in a template and so I think any issues would be detected at compile time, and this is compiling just fine on all platforms in the CI.

**Comment by Bromeon** [comment]
> For anyone who is intersted, I made a small demo in compiler explorer, even with `-O3` the copy can not be elimated.

The compiler has to be conservative, because the pointer passed to `convert()` is opaque: it cannot know what happens to it once we've made a copy. This copy could as well be deliberate because we're intending to change the original object. The copy _itself_ could have side effects (which might be disproved by inspecting the copy constructor implementation; not sure how deep compilers go here).

It is our "insider knowledge" that a GDExtension binding keeps that pointer unchanged, as it's in a function call.

**Review by akien-mga — APPROVED** [review]
Couldn't get another review from the core team, but it looks overall sensible to me and I trust that if there's any issue with this change, we'll find out fast.

**Comment by akien-mga** [comment]
Thanks!
