### PR TITLE
[Core] Fix `Variant::construct` of `Object`

### LINKED ISSUE #90086: Memory leak when using `weakref()`
### Tested versions

- Reproducible in 4.2.1 Stable and master 29b3d9e9e538f0aa8effc8ad8bf19a2915292a89

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 980 Ti (NVIDIA; 31.0.15.3699) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

The following code leaks memory:

```GDScript
extends Node

class MyObj:
	var obj: MyObj

func _process(_delta: float) -> void:
	var obj_1 = MyObj.new()
	var obj_2 = MyObj.new()
	# obj_1.obj = obj_2 # does not leak
	obj_1.obj = weakref(obj_2) # leaks
```

If you swap the commented line with the line that leaks, it will no longer leak.

This also happens with other types:

```GDScript
extends Node

class MyResource extends Resource:
	var my_resource : MyResource

func _process(_delta: float) -> void:
	var res_1 : MyResource = MyResource.new()
	var res_2 : MyResource = MyResource.new()
	#res_1.my_resource = res_2 # does not leak
	res_1.my_resource = weakref(res_2) # leaks
```

I expect that `weakref()` should not have this sort of impact in this scenario. Please correct me if I am mistaken!

With `weakref()`:
image

Without `weakref()`:
image

### Steps to reproduce

1. Paste either of the above code snippets on a node in a scene and run the game.
2. Watch the Static Memory Monitor.

### Minimal reproduction project (MRP)

[weakref-leak-bug.zip](https://github.com/godotengine/godot/files/14817931/weakref-leak-bug.zip)

### LINKED ISSUE #91289: AnimationPlayer: Call Method track, unable to select Object type in Args of AnimationTrackKeyEdit inspector
### Tested versions

- Reproducible in: 4.3.dev (4a0160241), 4.2.1

### System information

Godot v4.3.dev (4a0160241) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XTX (Advanced Micro Devices, Inc.; 31.0.24027.1012) - AMD Ryzen 9 7950X3D 16-Core Processor (32 Threads)

### Issue description

When adding arguments to a method call on an AnimationPlayer track, you are unable to select Object from Nil. You can select other types from Nil and it works as expected. And converting from a non-Nil types to Object works.

I've found in `editor/animation_track_editor.cpp` on about line 217 is the start of the problem, we seem to be copying the original Variant (which is type Nil) in the code above. See the `d_new` variable. Then we pass the old variant (still Nil type) into the `Variant::construct` as a parameter. The crux of the problem is that `Variant::construct` doesn't set the type to Object in this case. Other cases seem to use the case below (line 219) with a nullptr argument, which calls a different construct that ends up calling a `VariantDefaultInitializer` for the desired type.

### Steps to reproduce

extract the attached test.zip and open it with godot (4.3 dev)

- Open the scene "node_3d.tscn" if it isn't already
- Click on the AnimationPlayer in the scene
- Navigate to the Animation Editor (if it isn't already opened)
- Select the "new_animation" animation in the animation drop down (if not already selected)
- click on one of the spawnObject key frames (or create a new one and select it)
- In the Key Frame inspector increase arg count if it is 0
- Drop down the Args until you find an arg with with a nil type
- Try to select the Object type and notice that it remains Nil.

### Minimal reproduction project (MRP)

[test.zip](https://github.com/godotengine/godot/files/15143494/test.zip)

### PR DESCRIPTION
**Pull request by AThousandShips**
Variant type was not updated correctly causing leaks in ref-counted

This caused errors as objects constructed this way would be typed `NIL` and therefore not be freed, even though they went through reference counting, might have caused further issues elsewhere, like extensions, but haven't tested, this should be a safe fix as it just clears and initializes the type

* Fixes: https://github.com/godotengine/godot/issues/90086
* Fixes: https://github.com/godotengine/godot/issues/91289

### CODE REVIEW

**Comment by AThousandShips** [comment]
Can add a test case to GDScript if desired matching the issue report, but unsure if it's relevant in this case

**Comment by AThousandShips** [comment]
The reason it breaks GDScript in this case is that this code passes fine, as `value` is `NIL`, which is valid for that check, a `NIL` variant is a valid type for an object here, now it will correctly error, as the resulting variant is now a valid `OBJECT` so it will go through the checks and correctly determine the type is wrong:
https://github.com/godotengine/godot/blob/29b3d9e9e538f0aa8effc8ad8bf19a2915292a89/modules/gdscript/gdscript.cpp#L1609

**Comment by AThousandShips** [comment]
Adding a GDScript test for this, a scaled down version of the test in the issue for the error

**Comment by AThousandShips** [comment]
There's still a strange leak when using `set` directly, but unsure what is causing that, it would be in some part of the code unrelated to this, will dig further but seems a different case

**Comment by AThousandShips** [comment]
There, new fix, this is perhaps not exactly the cleanest, but I prefer to use the methods available there instead of assigning directly to the type, an alterative solution would be to instead:
```diff
diff --git a/core/variant/variant_internal.h b/core/variant/variant_internal.h
index dbd4a6a7ad..d867d08b2c 100644
--- a/core/variant/variant_internal.h
+++ b/core/variant/variant_internal.h
@@ -1493,13 +1493,13 @@ struct VariantDefaultInitializer<PackedColorArray> {
 template <typename T>
 struct VariantTypeChanger {
        static _FORCE_INLINE_ void change(Variant *v) {
-               if (v->get_type() != GetTypeInfo<T>::VARIANT_TYPE || GetTypeInfo<T>::VARIANT_TYPE >= Variant::PACKED_BYTE_ARRAY) { //second condition removed by optimizer
+               if (v->get_type() != GetTypeInfo<T>::VARIANT_TYPE || GetTypeInfo<T>::VARIANT_TYPE == Variant::OBJECT || GetTypeInfo<T>::VARIANT_TYPE >= Variant::PACKED_BYTE_ARRAY) { //second condition removed by optimizer
                        VariantInternal::clear(v);
                        VariantInitializer<T>::init(v);
                }
        }
        static _FORCE_INLINE_ void change_and_reset(Variant *v) {
-               if (v->get_type() != GetTypeInfo<T>::VARIANT_TYPE || GetTypeInfo<T>::VARIANT_TYPE >= Variant::PACKED_BYTE_ARRAY) { //second condition removed by optimizer
+               if (v->get_type() != GetTypeInfo<T>::VARIANT_TYPE || GetTypeInfo<T>::VARIANT_TYPE == Variant::OBJECT || GetTypeInfo<T>::VARIANT_TYPE >= Variant::PACKED_BYTE_ARRAY) { //second condition removed by optimizer
                        VariantInternal::clear(v);
                        VariantInitializer<T>::init(v);
                }
```
And just use the `change` method without `clear` like the other cases use, this would be slightly more invasive, but accomplish the same goal, either way works for me (though the current PR changes are cheaper in rebuilds)

File: core/variant/variant_construct.h [hunk 1]
```diff
@@ -153,11 +153,14 @@ class VariantConstructor {
 class VariantConstructorObject {
 public:
 	static void construct(Variant &r_ret, const Variant **p_args, Callable::CallError &r_error) {
-		VariantInternal::clear(&r_ret);
 		if (p_args[0]->get_type() == Variant::NIL) {
+			VariantInternal::clear(&r_ret);
+			VariantTypeChanger<Object *>::change(&r_ret);
 			VariantInternal::object_assign_null(&r_ret);
```
Comment (krazzei) [inline core/variant/variant_construct.h:159]: Is this redundant in this case? `VariantTypeChanger<Object *>::change` calls `VariantInitializer<T>::init(v)` and for `Object` that calls `VariantInternal::init_object(v)` which finally calls `object_assign_null` and also sets the type to Object.

File: core/variant/variant_construct.h [hunk 2]
```diff
@@ -198,11 +202,13 @@ class VariantConstructorNilObject {
 		}
 
 		VariantInternal::clear(&r_ret);
+		VariantTypeChanger<Object *>::change(&r_ret);
 		VariantInternal::object_assign_null(&r_ret);
```
Comment (krazzei) [inline core/variant/variant_construct.h:206]: This also might be redundant.

File: core/variant/variant_construct.h (hunk 1 above)
Comment (AThousandShips) [reply core/variant/variant_construct.h:159]: Nope, see the description, it's about the *old* data, not the new

Comment (AThousandShips) [reply core/variant/variant_construct.h:159]: I tried it without several of these and arrived on that this was necessary, as explained above

Comment (krazzei) [reply core/variant/variant_construct.h:159]: The old data is null. No point in calling `object_assign_null` twice.

Comment (AThousandShips) [reply core/variant/variant_construct.h:159]: Please read this https://github.com/godotengine/godot/pull/90134#issuecomment-2032399824

The old data isn't null *without* `clear`, the problem is that we both need to *clear* and then initialize it properly, again please read the original post and my other comments that explain this

Comment (AThousandShips) [reply core/variant/variant_construct.h:159]: Thank you for trying to help, it's appreciated, but as I said I've tried different solutions and they didn't work, and I think you need to re-read what the actual problem here is, it's not just the problem in #91289

**Review by vnen — APPROVED** [review]
LGTM. Should be safe to merge too.

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank *you*!
