### PR TITLE
Make ProgressBar reflect the real value in the percent label when "allow greater" is checked

### LINKED ISSUE #63311: ProgressBar should reflect "allow greater" values in the percent label
### Godot version

v3.5.beta.custom_build [3c0d32562]

### System information

NixOS

### Issue description

`ProgressBar` currently doesn't reflect values that exceed `max_value` when `allow_greater = true`, while sibling `Range` descendant `SpinBox` does correctly display values above `max_value` in this scenario. Does it make sense for `ProgressBar`s to display >100% labels when `allow_greater = true` and `percent_visible = true` given that `value` is clamped to `max_value` when `allow_greater = false` anyway and this is a visual component not really meant as a data store? (the only scenario I can think of where clamping the label to "100%" when `allow_greater = true` is useful is when someone wants to use it as a data store)

Relevant code:

* `3c0d32562` (my build): https://github.com/godotengine/godot/blob/3c0d32562b558b60abe382f2a132f4ea0f25b380/scene/gui/progress_bar.cpp#L66
    * Specifically `get_as_ratio()` since it clamps between `min_value` and `max_value`, we probably just want a `value / max_value * 100` instead here.
* `master`: https://github.com/godotengine/godot/blob/653f95282ccd31a4e38a157bb7845405079de371/scene/gui/progress_bar.cpp#L104

### Steps to reproduce

Set `allow_greater = true` and `value = 150` and the label doesn't match the value, it's clamped to "100%" despite `allow_greater = true`.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by rarysson**
Fix https://github.com/godotengine/godot/issues/63311.

I have just a question. When we change the `min value` or the `max value`, the `current value` is updated if it is above the `max value` or below the `min value`. Should I implement this behavior when the user toggles `Allow Greater/Lesser`? Right now if I toggle  `Allow Greater/Lesser` it will keep the old value, as you can see in the video below.

https://github.com/godotengine/godot/assets/22689195/1fe71355-de93-4533-9911-6e55d4e3d865

It seems because in the `Range` class it doesn't emit the change like the other properties (e.g.: `page`, `max`, `min`, `etc`.).

https://github.com/godotengine/godot/blob/f8818f85e6c43cdf1277e8ae85eba19ca0a003b0/scene/gui/range.cpp#L360-L362

### CODE REVIEW

File: scene/gui/progress_bar.cpp [hunk 1]
```diff
@@ -91,12 +91,14 @@ void ProgressBar::_notification(int p_what) {
 			}
 
 			if (show_percentage) {
-				String txt = itos(int(get_as_ratio() * 100));
+				String txt = itos(static_cast<int>(get_value() / get_max() * 100));
```
Comment (AThousandShips) [inline scene/gui/progress_bar.cpp:94]:
```suggestion
				String txt = itos(int(get_value() / get_max() * 100));
```
Usual syntax

**Comment by KoBeWi** [comment]
You can't just divide by max, you need to take min into account also avoid dividing by 0.

**Comment by rarysson** [comment]
It was too good to be right on the first try haha. 

Now I just need to know if I need to fix the behavior that I mentioned in the video, or if it's expected.

**Comment by KoBeWi** [comment]
It breaks `exp_edit` though:
image
I think instead of inventing custom ratio, `get_as_ratio()` should be modified to allow values outside the 0-1 range if `allow_greater`/`allow_lesser` are enabled. The value is explicitly clamped, so it should be easy change.

> It seems because in the Range class it doesn't emit the change like the other properties

This is probably irrelevant, because changing these properties does not affect current value.

**Comment by rarysson** [comment]
You're right, but I don't think we can do that safely, because some UI elements rely on the value from `get_as_ratio()`, and it will break if the value is outside of the 0-1 range, as you can see below:

image

I just have one question, if the `exp_edit` and `allow_lesser` are checked what is the expected behavior if the `value` is less than 0?

**Comment by KoBeWi** [comment]
> I just have one question, if the exp_edit and allow_lesser are checked what is the expected behavior if the value is less than or equal to 0?

`exp_edit` requires the min_value to be `>= 0`, so I think the exp ratio should be always 0 when below that.

btw "`exp_edit` requires the min_value to be `>= 0`," is not respected by your code. I think the implementation is ok, just make sure that the percentage always matches the filled bar, i.e. 50% should be when the bar is half filled etc. Right now it's still possible to desync it.

**Comment by rarysson** [comment]
> [...] I think the implementation is ok, just make sure that the percentage always matches the filled bar, i.e. 50% should be when the bar is half filled etc. Right now it's still possible to desync it.

To be honest, I don't see how it could desync, because it's the same logic as the `get_as_ratio()`, do you have an example?

I tried to see if it behaved differently from the stable version, but I don't see the difference, as you can see below (I tried some different values too).

### Godot 4.1



### This PR

mine

**Comment by KoBeWi** [comment]
Ok the only one I could find was with `exp_edit` (again xd) and negative `min_value`:

https://github.com/godotengine/godot/assets/2223172/2d1ba726-9847-4f51-83d6-493e4e11d6bf

Other than that the value displays correctly.

**Comment by rarysson** [comment]
Now I think it works as expected.

File: scene/gui/progress_bar.cpp [hunk 2]
```diff
@@ -91,12 +91,31 @@ void ProgressBar::_notification(int p_what) {
 			}
 
 			if (show_percentage) {
-				String txt = itos(int(get_as_ratio() * 100));
+				double ratio = 0;
+
+				if (Math::is_equal_approx(get_max(), get_min())) {
```
Comment (KoBeWi) [inline scene/gui/progress_bar.cpp:96]: Maybe it's worth it to add a comment that it's basically copy-paste of `get_as_ratio()`, but unclamped.

**Review by KoBeWi — APPROVED** [review]

File: scene/gui/progress_bar.cpp [hunk 3]
```diff
@@ -91,12 +91,31 @@ void ProgressBar::_notification(int p_what) {
...
+					ratio = 1;
+				} else if (is_ratio_exp() && get_min() >= 0 && get_value() >= 0) {
+					double exp_min = get_min() == 0 ? 0.0 : Math::log(get_min()) / Math::log((double)2);
+					double exp_max = Math::log(get_max()) / Math::log((double)2);
+					double exp_value = get_value() == 0 ? 0.0 : Math::log(get_value()) / Math::log((double)2);
+					double r = (exp_value - exp_min) / (exp_max - exp_min);
```
Comment (AThousandShips) [inline scene/gui/progress_bar.cpp:102]: This needs to be renamed to not shadow

File: scene/gui/progress_bar.cpp [hunk 4]
```diff
@@ -91,12 +91,31 @@ void ProgressBar::_notification(int p_what) {
...
+
+					ratio = CLAMP(r, is_lesser_allowed() ? r : 0, is_greater_allowed() ? r : 1);
+				} else {
+					double r = (get_value() - get_min()) / (get_max() - get_min());
```
Comment (AThousandShips) [inline scene/gui/progress_bar.cpp:106]: Same here

**Comment by YuriSizov** [comment]
Thanks, and congrats on your first merged Godot contribution!
