### PR TITLE
`SpriteFramesEditor` Show `AtlasTexture`'s source texture path in the frame's tooltip

### LINKED ISSUE #57059: Animated Sprites do not show path to texture in IDE
### Godot version

3.4.2

### System information

PopOS

### Issue description

When you are editing a scene and access Sprites, etc you can clearly see where the image comes from because the tooltip shows the path to the file. This is pretty vital when working with lots of textures to know where the image came from, whether it was a .tres or a .png, which folder, etc.
image

However, when you are in the AnimatedSprite editor, all the popup does is show you the fact that it comes from an item in your scene, e.g. the one below as you can see you have no idea the source. 

image

I guess it might come down to being a 'proposal' but I see it more as a bug, but happy to move it :)

### Steps to reproduce

As description.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by kleonc**
Resolves #57059.

In `SpriteFramesEditor` the texture path shown in the frame's tooltip was correct but since frame is often saved as an `AtlasTexture` subresource within a scene/resource file its path might be not what the user is looking for. So now also subsequent source texture paths are being shown. Only for `AtlasTexture` though (won't work for `ProxyTexture` etc.) but that's the most common case as `AtlasTexture`s are generated when adding frames using _Add Frames from a Sprite Sheet_ dialog. So should be good enough.

I made tooltip look/formatting similar to the output of `Node::print_tree_pretty()`.

- Before (`3.4.2.stable`):

GY5uaj7VnU

- After (`3.x` build):

Ku2zBesPaS
With subsequent `AtlasTexture`:
ozStNwBtGt

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

File: editor/plugins/sprite_frames_editor_plugin.cpp [hunk 1]
```diff
@@ -821,19 +821,30 @@ void SpriteFramesEditor::_update_library(bool p_skip_selector) {
 
 	for (int i = 0; i < frames->get_frame_count(edited_anim); i++) {
 		String name;
-		Ref<Texture2D> icon;
+		Ref<Texture> frame = frames->get_frame(edited_anim, i);
```
Comment (akien-mga) [inline editor/plugins/sprite_frames_editor_plugin.cpp:824]: `SpriteFrames::get_frame()` does return `Texture2D`, this change was wrong.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

File: editor/plugins/sprite_frames_editor_plugin.cpp (hunk 1 above)
Comment (kleonc) [reply editor/plugins/sprite_frames_editor_plugin.cpp:824]: Oh, sorry, forgot about that change in `master`. New PR I guess?
