### PR TITLE
Fix project manager not working in self-contained mode

### LINKED ISSUE #66344: Can no longer use self-contained editor with projects in a sub-folder next to the editor.
### Godot version

v4.0.beta.custom_build [42f6532c3]

### System information

Windows 11, Vulkan, Nvidia GTX 1050 Ti, 512.15

### Issue description

Godot Fails to start when using Self contained when the Projects folder, in which there are projects is in the same directory as the Editor.

### Steps to reproduce

Try to Open the Godot Editor with `._sc_` after https://github.com/godotengine/godot/pull/66200

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by aaronfranke**
The behavior of `ProjectSettings::get_singleton()->get_resource_path()` was not as I expected in the project manager. This PR changes the code so that this only runs for editor and cmdline_tool but not project_manager. Fixes #66344

### CODE REVIEW

File: main/main.cpp [hunk 1]
```diff
@@ -1938,12 +1938,13 @@ Error Main::setup2(Thread::ID p_main_tid_override) {
...
 		EditorPaths::create();
-		if (EditorPaths::get_singleton()->is_self_contained()) {
-			if (ProjectSettings::get_singleton()->get_resource_path() == OS::get_singleton()->get_executable_path().get_base_dir()) {
-				ERR_PRINT("You are trying to run a self-contained editor at the same location as a project. This is not allowed, since editor files will mix with project files.");
-				OS::get_singleton()->set_exit_code(EXIT_FAILURE);
-				return FAILED;
-			}
+	}
+	if ((editor || cmdline_tool) && EditorPaths::get_singleton()->is_self_contained()) {
+		print_line(ProjectSettings::get_singleton()->get_resource_path());
```
Comment (akien-mga) [inline main/main.cpp:1943]: Debug print.

File: main/main.cpp [hunk 2]
```diff
@@ -1938,12 +1938,13 @@ Error Main::setup2(Thread::ID p_main_tid_override) {
...
 	if (editor || project_manager || cmdline_tool) {
 		EditorPaths::create();
-		if (EditorPaths::get_singleton()->is_self_contained()) {
-			if (ProjectSettings::get_singleton()->get_resource_path() == OS::get_singleton()->get_executable_path().get_base_dir()) {
-				ERR_PRINT("You are trying to run a self-contained editor at the same location as a project. This is not allowed, since editor files will mix with project files.");
-				OS::get_singleton()->set_exit_code(EXIT_FAILURE);
-				return FAILED;
-			}
+	}
+	if ((editor || cmdline_tool) && EditorPaths::get_singleton()->is_self_contained()) {
```
Comment (akien-mga) [inline main/main.cpp:1942]: I'm not sure this is enough as for example this would break when running `godot --doctool` when self-contained.

I think what you should discriminate on is `found_project`, which you'd need to make global from the previous `setup()`. That's basically what tells you that you're running with a valid project path and loading the `project.godot`.

Comment (aaronfranke) [reply main/main.cpp:1942]: Are users running doctool in self-contained mode?

Originally I had this code only inside of the export code, maybe I should move it back there?

Comment (aaronfranke) [reply main/main.cpp]: Updated the PR to use `found_project`, indeed this is better and I did some testing and it works as expected.

**Comment by mrjustaguy** [comment]
The Project Manager Works now

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
