### PR TITLE
Make the drawing logic clearer in `Button`

### LINKED ISSUE #59202: OptionButton `expand_icon` breaks the layout
### Godot version

4.0 9d732aa / 3.x

### System information

Windows 10 x64

### Issue description

image
Text overlaps arrow

### Steps to reproduce

1. Add OptionButton
2. Add some icon and text
3. Enable `expand_icon` property
4. Shrink the button to minimal size

### Minimal reproduction project

_No response_

### LINKED ISSUE #80386: If Button Icon is aligned Center, but Text is aligned Left/Right, the text will still avoid the space the icon would take.
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XTX (Advanced Micro Devices, Inc.; 31.0.21001.45002) - AMD Ryzen 7 7700X 8-Core Processor (16 Threads)

### Issue description

When a Button has an icon and the icon is set to be aligned to the center, but the Button Text is aligned to the Left or Right, the text will avoid the space the icon would take as if the icon was aligned Left or Right, respectively. In other words, the text is expected to be centered if the icon is, otherwise the behavior that the text alignment follows is somewhat strange.

The expected behavior should be that the text does not align according to an Icon that isn't there. It should align to the Left or Right of the button walls, ignoring the icon, given that the icon will be centered and therefore behind the text.

**Note**: I've created this Issue after #80385, which shows similar UI problems involving CheckBox and CheckButton.

### Steps to reproduce

1. Create Button
2. Set Icon to button. Any will do, such as placeholder texture.
3. Set Icon Alignment to Center. (Node Properties -> Button -> Icon Behavior -> Icon Alignment)
4. Set Text Alignment to Left or Right. (Node Properties -> Button -> Text Behavior -> Alignment)

The text will align as if the icon was aligned Left or Right, respectively with the text. However, there is no icon there, and instead just a blank space of the same dimensions. The icon is instead centered behind the text.

### Minimal reproduction project

[Button_Text_Bug.zip](https://github.com/godotengine/godot/files/12283440/Button_Text_Bug.zip)

### PR DESCRIPTION
**Pull request by Rindbee**
Make the drawing logic clearer. 

The drawing logic follows the calculation logic in `Button::get_minimum_size`. According to the order of `stylebox`, `icon`, and `text`, and follow properties such as alignment mode, to fill the display space of the button.

Add a `Button::_set_h_separation_is_valid_when_no_text` for Button derived classes (like `OptionButton`) that expects a `h_separation` between `icon` and theme icon even if the `text` is empty.

Fixes  #59202.
Supersedes #59340.
Depends on #64218 (Negative values of `h_separation` will be treated as `0`). 

Fixes #80386.

Try to follow the rules in Alpha13, but except when alignment is `CENTER`. This patch will try to draw inside the yellow rectangle.

captrue

The following is a set of comparison pictures.

| Alpha13 | This patch + #64218 |
| :---------: | :-------------: |
| alpha13 |  | 
|  |  |
|  |  |
|  |  |

### CODE REVIEW

**Comment by Ayush-singla27** [comment]
i would like to work on this issue but this PR is still open. Is there any particular reason why this PR is waiting for a review?

**Comment by KoBeWi** [comment]
I don't really like how this adds a special case for inheriting class, but I guess you could fix #68930 as well now.

**Comment by Rindbee** [comment]
The drawing of this PR is based on `get_minimum_size()`, when `text` is empty, `CheckBox`/`CheckButton` will ignore `h_separation` between the inner icon and `icon`, but `OptionButton` class will not ignore it. So `OptionButton` is a bit special.

**Comment by KoBeWi** [comment]
I understand why it needs to be done; it just breaks OOP this way and could be handled better.  But it would make the code more complex, so not worth it for a single case.

**Comment by Rindbee** [comment]
If the behavior of classes with internal icons (`CheckBox`/`CheckButton`/`OptionButton`) is consistent, no matter whether `h_separation` is ignored or not, no special handling is required.

**Comment by YuriSizov** [comment]
If you need a hack like that, then it's better to add an unexposed flag and set it only for the `OptionButton`. OOP would be preserved, and we'd be safe without weird circular dependencies.

**Comment by Rindbee** [comment]
> If you need a hack like that, then it's better to add an unexposed flag and set it only for the `OptionButton`. OOP would be preserved, and we'd be safe without weird circular dependencies.

OK, use `h_separation_is_valid_when_no_text` to distinguish between OptionButton (`true`) and other Button derived classes (`false`).

**Comment by YuriSizov** [comment]
This needs a rebase (and the commit message could be a bit more detailed, the title of the PR itself is good).

The flag should not be a part of the constructor, it can just have a setter method that we call from the `OptionButton` constructor. That would be cleaner.

Also does it address https://github.com/godotengine/godot/issues/68930 or not? It probably should be addressed in this PR, as suggested.

**Comment by Rindbee** [comment]
> Also does it address #68930 or not? It probably should be addressed in this PR, as suggested.

#68930 is mainly caused by enabling `fit_to_longest_item` to cache size data, and switching `expand_icon` does not update the cache data. It's not a drawing problem, but a refreshing problem of cached data.

Maybe `fit_to_longest_item` can be made a member variable of `Button`, but only exposed in `OptionButton`, which can solve the problem of refreshing the cache when switching `expand_icon`. :thinking:

**Comment by KoBeWi** [comment]
Why is there so much empty space between arrow icon and text?
image

**Review by KoBeWi — APPROVED** [review]
Aside from the weird spacing, seems correct.

**Comment by Rindbee** [comment]
> Why is there so much empty space between arrow icon and text? 
> image

This seems to be because of `theme_override_styles/normal`, which is not taken into account when drawing the arrow icon.

**Comment by Rindbee** [comment]
The more detailed `theme_override_styles` will be considered when drawing, while the calculation of `get_minimum_size()` generally only considers `theme_override_styles/normal`. This may cause some issues.

File: scene/resources/default_theme/default_theme.cpp [hunk 1]
```diff
@@ -222,20 +222,20 @@ void fill_default_theme(Ref<Theme> &theme, const Ref<Font> &default_font, const
 	// OptionButton
 	theme->set_stylebox("focus", "OptionButton", focus);
 
-	Ref<StyleBox> sb_optbutton_normal = make_flat_stylebox(style_normal_color, 2 * default_margin, default_margin, 21, default_margin);
```
Comment (Rindbee) [inline scene/resources/default_theme/default_theme.cpp:225]: That space is caused by the value here.

File: scene/gui/button.cpp [hunk 2]
```diff
@@ -413,7 +455,7 @@ Size2 Button::get_minimum_size_for_text_and_icon(const String &p_text, Ref<Textu
 		minsize.height = MAX(font_height, minsize.height);
 	}
 
-	return theme_cache.normal->get_minimum_size() + minsize;
+	return _get_current_stylebox()->get_minimum_size() + minsize;
```
Comment (Rindbee) [inline scene/gui/button.cpp:458]: Same as drawing, use current stylebox to calculate min_size.

File: scene/gui/option_button.cpp [hunk 3]
```diff
@@ -118,12 +118,13 @@ void OptionButton::_notification(int p_what) {
 			}
 
 			Size2 size = get_size();
+			Ref<StyleBox> style = _get_current_stylebox();
 
 			Point2 ofs;
 			if (is_layout_rtl()) {
-				ofs = Point2(theme_cache.arrow_margin, int(Math::abs((size.height - theme_cache.arrow_icon->get_height()) / 2)));
+				ofs = Point2(theme_cache.arrow_margin + style->get_margin(SIDE_LEFT), int(Math::abs((size.height - theme_cache.arrow_icon->get_height() - style->get_minimum_size().height) / 2 + style->get_margin(SIDE_TOP))));
```
Comment (Rindbee) [inline scene/gui/option_button.cpp:125]: Consider the currently used stylebox when calculating the position of the arrow icon

File: scene/resources/default_theme/default_theme.cpp [hunk 4]
```diff
@@ -256,7 +256,7 @@ void fill_default_theme(Ref<Theme> &theme, const Ref<Font> &default_font, const
 	theme->set_color("font_outline_color", "OptionButton", Color(1, 1, 1));
 
 	theme->set_constant("h_separation", "OptionButton", 2 * scale);
-	theme->set_constant("arrow_margin", "OptionButton", 4 * scale);
+	theme->set_constant("arrow_margin", "OptionButton", 0);
```
Comment (KoBeWi) [inline scene/resources/default_theme/default_theme.cpp:259]: This technically breaks compatibility. I think it's fine to leave it; I tested the old value and the gap is small after bugfixes.

**Review by KoBeWi — APPROVED** [review]

**Comment by YuriSizov** [comment]
> This seems to be because of `theme_override_styles/normal`, which is not taken into account when drawing the arrow icon.

Indeed, it wasn't. Instead a dedicated constant was used, and the stylebox instead accounted for the icon width so the content is correctly offset. You've changed how the button is rendered now, making the `arrow_margin` constant pointless and all existing themes invalid.

I agree that the existing behavior is badly designed, and for the next minor release we can break some styling rules to fix an issue. But then the constant needs to go. And this also makes this PR not-cherry-pickable.

File: scene/gui/button.cpp [hunk 5]
```diff
@@ -225,14 +237,37 @@ void Button::_notification(int p_what) {
 				style2->draw(ci, Rect2(Point2(), size));
 			}
 
-			Ref<Texture2D> _icon;
-			if (icon.is_null() && has_theme_icon(SNAME("icon"))) {
+			drawable_size_remained -= style->get_minimum_size();
```
Comment (YuriSizov) [inline scene/gui/button.cpp:240]: You need to explicitly subtract margins. While it's the default value, `get_minimum_size` is not guaranteed to return a value equal to margin sizes. Because this method can be overridden.

**Review by YuriSizov — CHANGES_REQUESTED** [review]
Other than that, the code seems fine.

File: scene/gui/button.cpp [hunk 6]
```diff
@@ -86,6 +86,59 @@ void Button::_update_theme_item_cache() {
...
+			// Edge case for CheckButton and CheckBox.
+			if (has_theme_stylebox("hover_pressed")) {
+				if (rtl && has_theme_stylebox(SNAME("hover_pressed_mirrored"))) {
+					stylebox = theme_cache.hover_pressed_mirrored;
+				} else {
+					stylebox = theme_cache.hover_pressed;
+				}
+				break;
+			}
+			[[fallthrough]];
```
[the remark this answers is not in the document]
Comment (Rindbee) [reply scene/gui/button.cpp:112]: When there is no `hover_pressed` stylebox, it is only drawn as `pressed`. This is not a bug.

[the remark this answers is not in the document]
Comment (YuriSizov) [reply scene/gui/button.cpp:112]: Ah, right, there was a break in there.

File: scene/gui/button.cpp (hunk 5 above)
Comment (Rindbee) [reply scene/gui/button.cpp:240]: If so, the size of the space for drawing icons and text will be different from that in `Button::get_minimum_size`.

Why not make the get method of margin overridable. `get_minimum_size` can then be overridden indirectly. If it is directly covered, it may actually be drawn incorrectly when using margin to draw.

**Comment by Rindbee** [comment]
The drawing logic is based on the calculation logic in `Button::get_minimum_size`. Now the calculation logic in `Button::get_minimum_size` has changed.

I'm not sure if the one line taller text height is intentional or accidental.

File: scene/gui/button.cpp (hunk 5 above)
Comment (YuriSizov) [reply scene/gui/button.cpp:240]: > If so, the size of the space for drawing icons and text will be different from that in `Button::get_minimum_size`.

Well, drawing happens on the actual size, not on the minimum size. Button can expand beyond its minimum size and that shouldn't affect the drawing logic, so such a discrepancy should not lead to problems.

The problem is that the minimum size of a stylebox should be _at least_ equal to its margins. Which is why by default `StyleBox::get_minimum_size()` returns a sum of stylebox's margins, and a lot of GUI code just assumes that the method is a shorthand for getting all the margins combined. This is an incorrect assumption.

The minimum size can be changed for a particular stylebox implementation. And when you calculate the minimum size of the button, you should respect that and take the full `StyleBox::get_minimum_size()` into account. But when you're deciding on the drawing area, you should only offset it based on the margin values, and not on the min size. Perhaps it's worth adding a method to stylebox to return the combined value of margins, because we've already needed that in the recent Tree PR. But for now, you can simply explicitly make `get_margin` calls for each side and use that.

**Comment by Rindbee** [comment]
https://github.com/godotengine/godot/assets/30386067/1ab8accf-a838-412b-bc5e-e7f5d074e5f6



I think it's ready.

**Review by YuriSizov — DISMISSED** [review]

**Comment by YuriSizov** [comment]
The implementation is unstable:

https://github.com/godotengine/godot/assets/11782833/5577a2b5-cc6e-450e-be7f-ffb174bb897f

[This is the configuration](https://github.com/godotengine/godot/assets/11782833/f7272458-5d4a-46d0-a532-c10148aefd46).
We can probably squash all the bugs, but I would not merge it for 4.1 at this point. We could merge it as is and fix it in follow-ups early in 4.2, but we can also use this time to try and improve it.

**Comment by Rindbee** [comment]
Presumably because the width of the text (`text_overrun_behavior = OVERRUN_TRIM_ELLIPSIS`) and the icon (`expand_icon = true`) are both dynamically adjusted.

File: scene/gui/button.cpp [hunk 7]
```diff
@@ -252,145 +292,152 @@ void Button::_notification(int p_what) {
...
+				Size2 icon_size = _icon->get_size();
 				if (expand_icon) {
-					Size2 _size = get_size() - style->get_offset() * 2;
-					int icon_text_separation = text.is_empty() ? 0 : theme_cache.h_separation;
-					_size.width -= icon_text_separation + icon_ofs_region;
-					if (!clip_text && icon_align_rtl_checked != HORIZONTAL_ALIGNMENT_CENTER) {
-						_size.width -= text_buf->get_size().width;
+					Size2 _size = custom_element_size;
+					if (!clip_text && overrun_behavior == TextServer::OVERRUN_NO_TRIMMING && icon_align_rtl_checked != HORIZONTAL_ALIGNMENT_CENTER) {
+						_size.width -= text_buf_size.width;
```
Comment (Rindbee) [inline scene/gui/button.cpp:304]: Previously, `overrun_behavior` was not considered here.

**Comment by YuriSizov** [comment]
You would need to do a rebase and force-push to fix the CI, there was a bug in GDScript that fails unit tests.

**Comment by Rindbee** [comment]
Rebased.

**Comment by akien-mga** [comment]
Needs another rebase - I'd also suggest amending the commit title to be a bit more explicit (e.g. like the PR title if it's accurate).

And then still needs a review from maintainers experienced with Button drawing logic.

File: scene/gui/button.cpp [hunk 8]
```diff
@@ -229,14 +241,42 @@ void Button::_notification(int p_what) {
...
+			if (xl_text.is_empty() && _icon.is_null()) {
+				break;
+			}
+
+			int h_separation = MAX(0, theme_cache.h_separation);
+
+			// A positive value means the internal element is on the left, a negative value means that
+			// the internal element is on the right, and 0 means no internal element.
+			float internal_margin = _internal_margin[SIDE_LEFT];
+			if (Math::is_equal_approx(internal_margin, 0.0f)) {
```
Comment (AThousandShips) [inline scene/gui/button.cpp:266]:
```suggestion
			if (Math::is_zero_approx(internal_margin)) {
```

**Comment by Rindbee** [comment]
Rebased.

File: scene/gui/button.cpp (hunk 8 above)
Comment (Rindbee) [reply scene/gui/button.cpp]: Thanks for your suggestion.

**Review by AThousandShips — APPROVED** [review]
Style looks good

**Review by KoBeWi — APPROVED** [review]
I already approved this twice, so I only skimmed through the code. It seems to work correctly, at least in the case presented in the linked issue.

File: scene/gui/button.cpp [hunk 9]
```diff
@@ -50,6 +50,59 @@ void Button::_set_internal_margin(Side p_side, float p_value) {
...
+			if (has_theme_stylebox("hover_pressed")) {
+				if (rtl && has_theme_stylebox(SNAME("hover_pressed_mirrored"))) {
+					stylebox = theme_cache.hover_pressed_mirrored;
+				} else {
+					stylebox = theme_cache.hover_pressed;
+				}
+				break;
+			}
+			[[fallthrough]];
+		}
```
Comment (AThousandShips) [inline scene/gui/button.cpp:77]: For readability and style I'd put `[[fallthrough]];` here instead

File: scene/gui/button.cpp [hunk 10]
```diff
@@ -73,131 +126,127 @@ void Button::_notification(int p_what) {
...
 
 				} break;
 			}
 
-			if (has_focus()) {
-				Ref<StyleBox> style2 = theme_cache.focus;
-				style2->draw(ci, Rect2(Point2(), size));
+			{ // Draws the stylebox in the current state.
+				if (!flat) {
+					style->draw(ci, Rect2(Point2(0, 0), size));
```
Comment (AThousandShips) [inline scene/gui/button.cpp:201]:
```suggestion
					style->draw(ci, Rect2(Point2(), size));
```

**Review by AThousandShips — APPROVED** [review]
Looks good otherwise! (Too tired today didn't remember that I'd already approved this before, but seems like a trend on this one to approve again, so maybe I'm just in style)

**Comment by YuriSizov** [comment]
I still need to review this because before I did extensive testing and found issues, and since then there was a significant change in the implementation so I need to do it all over again.

File: scene/gui/button.cpp [hunk 11]
```diff
@@ -213,146 +262,160 @@ void Button::_notification(int p_what) {
...
-						icon_height = _icon->get_height() * icon_width / _icon->get_width();
+				{ // Calculate the drawing position of the icon.
+					icon_ofs = (custom_element_size - icon_size) / 2.0f;
+
+					switch (icon_align_rtl_checked) {
+						case HORIZONTAL_ALIGNMENT_FILL:
+						case HORIZONTAL_ALIGNMENT_LEFT: {
+							icon_ofs.x = style_margin_left;
+							if (internal_margin > 0.0f) {
+								icon_ofs.x += internal_margin;
```
Comment (YuriSizov) [inline scene/gui/button.cpp:307]: So I guess it's for this bit, and for the text below. This confirms to me that this implementation is lacking. We need to account for both sides, and we cannot use the sign for that.

**Review by YuriSizov — CHANGES_REQUESTED** [review]
I didn't check all of the implementation, but one bit did stand out to me. And there are regressions in the behavior, which may or may not be related and need to be looked into (see below).

Overall, there are clear improvements in the behavior. Here's a comparison of before and after, which demonstrates both the linked issue being fixed and some inconsistencies being addressed:

### Before

godot windows editor dev x86_64_2024-01-15_16-05-08

### After

godot windows editor dev x86_64_2024-01-15_16-06-55

----

There are still some issues which are not addressed by this PR. See the top row of the right side of either image where the icon alignment varies. When the icon is center-aligned the text clipping stops to work. You can see that no matter if you set trimming or ellipses, it just stays in the "trim nothing" mode.


https://github.com/godotengine/godot/assets/11782833/2901032e-1990-452a-a361-3a7115fb0797


----

One new problem the aforementioned regression, is visible with the top-right example. For some reason, if you set the button to "trim nothing", the icon shrinks beyond the size of any other mode, and vertical positioning changes as a result. This was not happening before this patch.


https://github.com/godotengine/godot/assets/11782833/24ea473d-6c39-4bf2-b385-fff4c5ca8cab


You can also see that text alignment works funny, this may be related to the bit that I've highlighted in the code review. Left and center alignment are exactly the same, but right alignment is shifted to the left, so it's more to the left than either left or center alignment.

File: scene/gui/button.cpp (hunk 11 above)
Comment (Rindbee) [reply scene/gui/button.cpp:307]: Although the size of `_internal_margin` is 4, only 2 elements are valid. Compared with `_internal_margin`, `internal_margin` also contains possible `h_separation`. 

`internal_margin > 0.0f` is equivalent to `_internal_margin[SIDE_LEFT] > _internal_margin[SIDE_RIGHT]`, while `internal_margin < 0.0f` is equivalent to `_internal_margin[SIDE_LEFT] < _internal_margin[SIDE_RIGHT]`

Maybe the second comparison and the positive values will make them clearer.

File: scene/gui/button.cpp [hunk 12]
```diff
@@ -213,146 +262,160 @@ void Button::_notification(int p_what) {
...
-			}
-
-			text_buf->set_width(is_clipped ? text_clip : -1);
+				text_buf->set_width(-1.0f); // Calculates the width of the text without being constrained.
+				if (is_clipped) {
+					text_buf->set_width(MAX(MIN(drawable_size_remained.width, text_buf->get_size().width), 1.0f)); // Computes the constrained text width.
+				}
 
-			int text_width = MAX(1, is_clipped ? MIN(text_clip, text_buf->get_size().x) : text_buf->get_size().x);
+				const Size2 text_buf_size = text_buf->get_size();
```
Comment (Rindbee) [inline scene/gui/button.cpp:367]: @YuriSizov There seems to be some change in the behavior of `text_buf->set_width()`. It can no longer affect the result of `text_buf->get_size()`.

**Comment by Rindbee** [comment]
> There are still some issues which are not addressed by this PR. See the top row of the right side of either image where the icon alignment varies. When the icon is center-aligned the text clipping stops to work. You can see that no matter if you set trimming or ellipses, it just stays in the "trim nothing" mode.

I'm not sure if the button's text is "Some very long te" or "Some very long text", if it's the former, the width is enough for the text to display, so no change is expected.


> One new problem the aforementioned regression, is visible with the top-right example. For some reason, if you set the button to "trim nothing", the icon shrinks beyond the size of any other mode, and vertical positioning changes as a result. This was not happening before this patch.


> You can also see that text alignment works funny, this may be related to the bit that I've highlighted in the code review. Left and center alignment are exactly the same, but right alignment is shifted to the left, so it's more to the left than either left or center alignment.

Related to `text_buf->set_width()` no longer affecting `text_buf->get_size()`. When calculating the position, we need to calculate the position on the left side of `text_buf`, so when calculating from the right side of the button, we need to subtract the width of `text_buf`. Wrong width results in wrong offset.

**Comment by YuriSizov** [comment]
> I'm not sure if the button's text is "Some very long te" or "Some very long text", if it's the former, the width is enough for the text to display, so no change is expected.

It's full text. The issue is that when the icon is vertically aligned to the top, the amount of space available for the text doesn't change. However, with icon's left and right alignment we still subtract icon's size out of the space allocated for the text, but we don't do that with the center alignment. There may be some logical reason for this, but it feels super unintuitive.

That aside, there is still more text in there but it doesn't get trimmed or ellipse'd correctly. But in any case, as I mentioned, that's a pre-existing problem. We don't have to fix it here now. We can move forward with just a subset of issues fixed, as there are still more problems with button icons not tackled by this PR.

**Comment by Rindbee** [comment]
I noticed that in "Trim Nothing" mode the text always shows up as "Some very long te", if it doesn't show up completely there might be a cache issue in `OptionButton`.

Like toggling `expand_icon`, toggling `text_overrun_behavior`, `clip_text` and `vertical_icon_alignment` may affect the minimum size. 

https://github.com/godotengine/godot/assets/30386067/251466ef-43f2-478a-a2a3-b51c44d5d97c

File: scene/gui/button.cpp [hunk 13]
```diff
@@ -72,287 +129,266 @@ void Button::_notification(int p_what) {
...
-			}
-
-			text_buf->set_width(is_clipped ? text_clip : -1);
+			// Draw the text.
+			if (!xl_text.is_empty()) {
+				text_buf->set_alignment(align_rtl_checked);
 
-			int text_width = MAX(1, is_clipped ? MIN(text_clip, text_buf->get_size().x) : text_buf->get_size().x);
+				float text_buf_width = MAX(1.0f, drawable_size_remained.width); // The space's width filled by the text_buf.
+				text_buf->set_width(text_buf_width);
```
Comment (Rindbee) [inline scene/gui/button.cpp:357]: Due to the conditions added in #80402, the calculated "drawable_size_remained.width" is less affected by "text_buf->get_size()". That is to say, the calculated results are more reliable.

If I understand "text_buf->set_width()" correctly, doing this will align correctly in the remaining space.

File: scene/gui/button.cpp [hunk 14]
```diff
@@ -72,287 +129,266 @@ void Button::_notification(int p_what) {
...
 
+			{ // The size after the stelybox is stripped.
+				drawable_size_remained.width -= style_margin_left + style_margin_right;
+				drawable_size_remained.height -= style_margin_top + style_margin_bottom;
+			}
+
+			const int h_separation = MAX(0, theme_cache.h_separation);
+
+			// The width reserved for internal element in derived classes (and h_separation if need).
+			float internal_margin = _internal_margin[SIDE_LEFT] > _internal_margin[SIDE_RIGHT] ? _internal_margin[SIDE_LEFT] : _internal_margin[SIDE_RIGHT];
```
Comment (YuriSizov) [inline scene/gui/button.cpp:171]: I still don't understand why you're doing it this way. Why aren't we considering both left and right margin? What if I need to have margins on both sides? Currently, `OptionButton` is not set up this way, but that's still unreliable overall.

File: scene/gui/button.cpp [hunk 15]
```diff
@@ -72,287 +129,266 @@ void Button::_notification(int p_what) {
...
+						text_ofs.x = (drawable_size_remained.width - text_buf_width) / 2.0f;
 					}
-				} break;
-			}
+						[[fallthrough]];
+					case HORIZONTAL_ALIGNMENT_FILL:
+					case HORIZONTAL_ALIGNMENT_LEFT:
+					case HORIZONTAL_ALIGNMENT_RIGHT: {
+						text_ofs.x += style_margin_left;
+						if (_internal_margin[SIDE_LEFT] > _internal_margin[SIDE_RIGHT]) {
```
Comment (YuriSizov) [inline scene/gui/button.cpp:370]: And then this makes the right margin to be ignored completely, even if it's set to be larger than the left one.

**Review by YuriSizov — APPROVED** [review]
So one issue was actually my mistake in the test scene, I did actually have the text cut off at `te` for some reason. That still makes me wonder if the alignment works as expected by the user.

What I mean here is that a top-left-aligned icon takes horizontal space from the text, same with top-right, or bottom-left, or bottom-right. Whereas top-center and bottom-center don't do that. I think that when the icon is to the top or to the bottom, it shouldn't take horizontal space from the text. I don't find this useful.

But that's a new discussion. Let's go ahead with this rework for now, so we can finally put it to rest, and do any new fixes in follow-ups.

File: scene/gui/button.cpp (hunk 14 above)
Comment (Rindbee) [reply scene/gui/button.cpp:171]: There is no ready-made example, and it is a bit difficult to imagine its rules. In that case, `h_separation` may also need to be calculated twice?

File: scene/gui/button.cpp (hunk 15 above)
Comment (Rindbee) [reply scene/gui/button.cpp:370]: If it exists on both sides, it can be calculated similar to stylebox.

Comment (YuriSizov) [reply scene/gui/button.cpp]: What I meant is that you've unified code for LEFT and RIGHT here, but this part only adjusts for the left margin. Compare this to how you handle icon's horizontal alignment.

File: scene/gui/button.cpp (hunk 14 above)
Comment (YuriSizov) [reply scene/gui/button.cpp]: I guess, yes 👍

**Comment by Rindbee** [comment]
> What I mean here is that a top-left-aligned icon takes horizontal space from the text, same with top-right, or bottom-left, or bottom-right. Whereas top-center and bottom-center don't do that. I think that when the icon is to the top or to the bottom, it shouldn't take horizontal space from the text. I don't find this useful.

Like this:

1. When vertical_icon_alignment is center, the behavior is consistent with the previous one.
2. When vertical_icon_alignment is not center, they behave like two lines of text/icon.

https://github.com/godotengine/godot/assets/30386067/c693de09-d3c8-4009-a45c-2eb435dfecdb

**Comment by YuriSizov** [comment]
> Like this:

Yes, this looks perfect!

**Comment by Rindbee** [comment]
Does `Button::get_minimum_size()` need to be modified? I'm not sure how to calculate the new rules, such as `h_separation` and so on.

**Comment by YuriSizov** [comment]
> Does `Button::get_minimum_size()` need to be modified? I'm not sure how to calculate the new rules, such as `h_separation` and so on.

`get_minimum_size_for_text_and_icon()` doesn't appear to be accounting for internal margins at all. I would say this is a material for another PR. Reviewing this one over and over again gets very complicated.

If there is anything left to fix here, it's my comment above about logic for RIGHT missing. The rest let's address in a new PR after this one is merged.

File: scene/gui/button.cpp (hunk 15 above)
Comment (Rindbee) [reply scene/gui/button.cpp]: I set the width of `text_buf` to `drawable_size_remained.width`. This way the alignment can be left to `TextParagraph` and we can calculate the offset from the left.

File: scene/gui/button.cpp (hunk 13 above)
Comment (Rindbee) [reply scene/gui/button.cpp:358]: Visible characters will be offset in the text‘s reserve space by `TextParagraph`. 

So we can later calculate the offset to this space from the left, as the required values are all determined.

**Comment by YuriSizov** [comment]
Thanks a lot!

**Comment by halotroop2288** [comment]
> The following is a set of comparison pictures.
> Alpha13 	This patch + #64218
>  	

This specific change sucks. I was so confused about why *some* of my buttons had icons and others just *don't* render the icons.

When Expand Icon is enabled, the rendering is inconsistent and I'm not aware of any way to override this behavior. And it looks to me that according to this PR, this is intended behavior!

No Expand Icons
Expand Icons

This is in an HFlowContainer, which should easily be able to expand and realign the buttons to fit both the icons and text.

C'mon. I just want my icons to be the same size!

**Comment by Rindbee** [comment]
> C'mon. I just want my icons to be the same size!

Want something like `EXPAND_FIT_WIDTH_PROPORTIONAL` for `TextureRect`, but relative to the text height? A property close to what you need might be `theme_override_constants/icon_max_width`.
