### PR TITLE
Fix unrestricted mouse-event propagation to SubViewports for Physics-Picking

### LINKED ISSUE #17326: Sub - viewports still don't handle _unhandled_input or CollisionObject._input_event()
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

I noticed in PR https://github.com/godotengine/godot/pull/15712 the _input event is forwarded to explicitly created Viewports, but `_unhandled_input` and `CollisionObject._input_event()` still don't respond 

**Godot version:**
3.0.stable.official

**OS/device including version:**
OSX 10.13.2 (17C88)

**Issue description:**
The only input events that propagate into sub-viewports are _input. 

`_unhandled_event` and `_input_event` (for Area2D etc) do not get called. 

**Steps to reproduce:**
Open the attached Godot project and run it. 

The Red area is in the default Viewport and receives all click events. 
The green area is a child of the explicit viewport and only receives `_input`events. 

**Minimal reproduction project:**
[ViewportInputBug.zip](https://github.com/godotengine/godot/files/1799020/ViewportInputBug.zip)

### LINKED ISSUE #58902: Physics Picking Events happen in SubViewport without area restrictions of SubViewportContainer
### Godot version

v4.0.alpha.custom_build [31b3bda36]

### System information

Debian 11, Vulkan

### Issue description

Prerequisite:
- SubViewportContainer with `rect_clip_content = true`
  - SubViewport (blue area)
    - `Area2D` + `CollisionShape2D` (gray + red area)

image

A `CollisionShape2D` within a `SubViewport` receives Mouse-events on positions that are not visible in the viewport.
I would expect to receive MouseEnter and MouseExit events at the border of the gray area, however current behavior is that the events trigger in the following way:
- Enter event at the border of the red area
- Exit event at the border of the red+gray+blue area

This is related to #28833, but not a duplicate, because this issue is based on`_unhandled_input`, while the other is based on `_gui_input`.

The reason for this issue is, that `_unhandled_input` is propagated by `SubViewportContainer` to its `SubViewport`, even if the position of the event is outside of the `SubViewportContainer`.

This issue can be solved by ensuring that `SubViewportContainer` propagates events with a position property to its SubViewports `_unhandled_input` only if the event happens within the area of the `SubViewportContainer`. The combination of PR #57894 + #58334 fixes this problem.

### Steps to reproduce

1. Load and run MRP
2. Move mouse over the border of the red area
3. View Console output

### Minimal reproduction project

[ViewportPhysicsClip.zip](https://github.com/godotengine/godot/files/8206470/ViewportPhysicsClip.zip)

### LINKED ISSUE #75015: `SubViewport`s dont process object picking when under `Panel` with mouse mode set to stop
### Godot version

92bee43ad 4.0.stable

### System information

ArchLinux x11

### Issue description

If a panel is above a viewport in the tree, the viewport does not process object picking.
```gdscript
Panel # needs mouse mode to be set to ignore, if it isnt set to ignore, object picking doesnt occur.
└── SubViewportContainer
    └── ViewportContainer
        └── StaticBody3D
```

I believe this is non standard behaviour, as `Panel` -> `Button` works just fine.

### Steps to reproduce

- Run `view.tscn` in mrp
- Verify that it prints `input` when you mouse over the cube
- Run `main.tscn`
- See that it no longer prints `input` when you mouse over the cube

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/10998751/bug.zip)

### LINKED ISSUE #75019: InputEvent emitted by TouchScreenButton does not reach _unhandled_input
### Godot version

4.0.stable

### System information

Arch Linux

### Issue description

Pressing a `TouchScreenButton` can produce a corresponding `InputEventAction`.

In 3.x, the event works the same as regular input events. You can receive it in `_input()` and `_unhandled_input()`, and it can be checked via `Input.is_action_just_pressed()`.

In 4.0, the event is not available in `_unhandled_input()`.

### Steps to reproduce

Use the MRP.

There's a `TouchScreenButton` assigned the action `custom_action`.

* Press the space bar, there are three entries in the Output panel.
* Click the button, there are only two entries in the Output panel, `_unhandled_input()` is not reached.

### Minimal reproduction project

[test-4.zip](https://github.com/godotengine/godot/files/10999615/test-4.zip)

### PR DESCRIPTION
**Pull request by Sauermann**
resolve #17326
resolve #58902
resolve #75015
resolve #75019

<details>
<summary>previous description</summary>

Currently, Events get processed by Nodes in order of the green arrow in the following graphic, when a`SubViewportContainer` is within the Root Viewport:

CurrentSubViewportHandlingOld

The red "X" denotes the place where `set_input_as_handled()` is called within `Viewport::_gui_input_event`, when an `InputEventMouseMotion` happens over the `SubViewportContainer`. Here is the according location in the source code:
https://github.com/godotengine/godot/blob/84f2c68c84bde10026454292578e5fdcc9ab69a3/scene/main/viewport.cpp#L1789-L1796
If the `SubViewportContainer` marks the event as stopped, `_unhandled_input` is never called.
If the `SubViewportContainer` ignores the event, it is processed in `_unhandled_input`, even though ignoring should be a synonym for not sending the event to the SubViewport of SubViewportContainer.

This pull request makes sure, that the event reaches _unhandled_input inside the SubViewport before the "X":

CurrentSubViewportHandlingNew

This is done by moving the `push_unhandled_input` call from  `Window::_window_input` to  `Viewport::push_input`.

This change makes `SubViewportContainer::unhandled_input` redundant, since it would distribute the event to _unhandled_input inside the SubViewport a second time.

Shortcut Events now need to be distributed via `push_input`, in order for them to be able to reach `SubViewports`.

</details>

MRP for all linked issues: [SubViewportEventBugs.zip](https://github.com/godotengine/godot/files/11423555/SubViewportEventBugs.zip)

BugsSVC

Currently InputEvents get sent unconditionally to `SubViewports` via `SubViewportContainer::unhandled_input`, even if the event-position is outside of the area of the `SubViewportContainer`. This leads to problems like #58902, where the mouse enters `CollisionObjects2D`, even if they are not visible. (in the MRP, clicking in the red area causes a mouse-click on the non-visible Logo within the `SubViewport`).

Also hovering `CollisionObjects2D` within `SubViewports` currently is reversed:
- If the `SubViewportContainer` is set to `MOUSE_FILTER_IGNORE`, the `CollisionObject2D` does receive mouse events.
- If the `SubViewportContainer` is set to `MOUSE_FILTER_STOP`, the `CollisionObject2D` doesn't receive mouse events.

A third bug is that a Panel with `MOUSE_FILTER_STOP`, parent of a SubViewportContainer, prohibits Physics-picking in the SubViewport.

The fourth bug, that gets fixed is that TouchScreenButtons don't receive some mouse events within `_unhandled_input`. (TouchScreenButton doesnt send event via _unhandled_input)

This PR solves all problems by moving the call of `push_unhandled_input` from `Window::_window_input` to `Viewport::push_input`.
This makes sure, that only events with a position within the area of the `SubViewportContainer` are considered for physics picking.
This change makes `SubViewportContainer::unhandled_input` redundant, since it would distribute the event to _unhandled_input inside the SubViewport a second time.

Updated 2022-09-26: fix merge conflict, made sure that this PR is still relevant after #61088 and adjusted description.
Updated 2022-10-14: adjust shortcut event handling
Updated 2022-11-06: update documentation of `push_input`.
Updated 2022-11-23: fix merge conflict
Updated 2023-01-27: fix merge conflict, update description based on the recently merged #58334
Updated 2023-03-17: fix merge conflict, updated MRP, linked a third bug, that this PR fixes.
Updated 2023-05-08: linked a fourth bug, that this PR fixes and updated description and MRP.

### CODE REVIEW

**Review by KoBeWi — APPROVED** [review]
Tested the attached project + some random stuff and it appears to be working correctly.

File: editor/editor_command_palette.cpp [hunk 1]
```diff
@@ -256,7 +256,7 @@ void EditorCommandPalette::register_shortcuts_as_command() {
 		ev.instantiate();
 		ev->set_shortcut(shortcut);
 		String shortcut_text = String(shortcut->get_as_text());
-		add_command(command_name, E.key, callable_mp(EditorNode::get_singleton()->get_viewport(), &Viewport::push_unhandled_input), varray(ev, false), shortcut_text);
+		add_command(command_name, E.key, callable_mp(EditorNode::get_singleton()->get_viewport(), &Viewport::push_input), varray(ev, false), shortcut_text);
```
Comment (KoBeWi) [inline editor/editor_command_palette.cpp:259]: This doesn't seem necessary 🤔

Comment (Sauermann) [reply editor/editor_command_palette.cpp:259]: The other changes of this PR cause, that `push_unhandled_input` no longer propagates events to SubViewports.
So this change becomes necessary in order to allow shortcuts to work also within SubViewports.

Comment (KoBeWi) [reply editor/editor_command_palette.cpp:259]: But this is editor-only code. Are there any SubViewports that are affected?

Comment (Sauermann) [reply editor/editor_command_palette.cpp:259]: I was not aware that the editor currently doesn't use SubViewports.

Is it possible to create add-ons or editor-extensions, that utilize shortcuts in SubViewports?
If that is the case, then it would be prudent to make the switch from `push_unhandled_input` to `push_input`.

I would consider the `push_input`-variant more robust than `push_unhandled_input`.

Comment (KoBeWi) [reply editor/editor_command_palette.cpp:259]: Well, this change doesn't seem to have any unwanted side-effects, so it's fine to keep it I guess.
> Is it possible to create add-ons or editor-extensions, that utilize shortcuts in SubViewports?

I think in this case not. The shortcut commands of CommandPalette are not exposed to scripting.

**Comment by RandomShaper** [comment]
I think it's a good time to merge this.

**Comment by akien-mga** [comment]
Thanks!

**Comment by WolfgangSenff** [comment]
I commented already in https://github.com/godotengine/godot/issues/17326, but I think some or much of this PR may be missing from the latest beta, 4.2.beta5. At least, I looked at the code and it seemed like some of it was missing - could be it was updated in the future and I missed that.

**Comment by Sauermann** [comment]
@WolfgangSenff The only thing, that changed, was the renaming of `_push_unhandled_input` to `_push_unhandled_input_internal`, but the important parts of this PR are still in the code.
