### PR TITLE
[macOS] Do not use `openApplicationAtURL` for headless instances.

### LINKED ISSUE #111592: Failure to run and segfault on MacOS in Godot 4.5 and 4.5.1 editors when running the game with --headless option
### Tested versions

# Godot versions 
- Reproducible in v4.5.stable.official [876b29033]
- Reproducible in v4.5.stable.mono.official [876b29033]
- Not reproducible in v4.4.1.stable.official [49a5bc7b6]
- Not reproducible in v4.4.1.stable.mono.official [49a5bc7b6]

# OS
- Reproducible on macOS
- Not reproducible on Windows

### System information

macOS Tahoe 26.0.1 (25A362) - chip: Apple M1 Max (and one other Mac for which I don't have details)

### Issue description

On Mac OS, we get the following error when running the game from the editor with the `--headless` command line parameter.

Image

Note: the game must not be running as embedded for this to happen

Image

A force quit of the game can cause a segfault and crash godot and all other running apps!

### Steps to reproduce

The bug can be reproduced quickly with a new empty project:
1. Create a new Godot project and open it in the editor
2. Create, save and assign a main scene (as is required to run the game from the editor)
3. Open the "Debug > Customize Run Instances..." window
4. Add `--headless` to the command line arguments
5. In the Game tab, under Embedding Options, set "Embed Game on Next Play" to false
6. Run the game
7. Notice the app fails to open and just seems to hang (bouncing up and down in the dock)
8. After a while the error dialog shows: "Could not start subprocess(es)!"

Optional - to cause a segfault (Warning: closes all apps):
1. After running the game (step 6 above), immediately force quit the launched instance (the one bouncing in the dock)
2. If you see the stop button (see screenshot below), press it
3. Crash! all windows close, segfault reported.
Video of the crash: https://youtu.be/rnQbPFnTzBc

Image

### Minimal reproduction project (MRP)

[new_game_project.zip](https://github.com/user-attachments/files/22886728/new_game_project.zip)

Note: You need to manually enable multiple run instances and set the --headless command line argument on the second instance.

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/111592

`openApplicationAtURL` used for launching GUI instances, is waiting for app to finish launching before returning, and since headless instance will never emit `applicationDidFinishLaunching` it was causing 20 sec freeze (timeout set for waiting) and error message (since `create_instance` return `ERR_TIMEOUT`) when running headless instance from the editor.

### CODE REVIEW

**Review by Ivorforce — APPROVED** [review]
Makes sense. Does this imply that changes are needed elsewhere to compensate that we cannot wait for `applicationDidFinishLaunching`, and instead return immediateley?

**Comment by bruvzg** [comment]
> Does this imply that changes are needed elsewhere to compensate that we cannot wait for applicationDidFinishLaunching, and instead return immediateley?

I do non think so, it's how OS API works, we do not need to wait for it. `openApplicationAtURL` is used for GUI instances only to ensure window is correctly activating (running executable directly often result in activation bugs), which is irrelevant for headless.

File: platform/macos/os_macos.h [hunk 1]
```diff
@@ -79,6 +79,21 @@ class OS_MacOS : public OS_Unix {
...
+		"/?",
+		"--version",
+		"--dump-gdextension-interface",
+		"--dump-extension-api",
+		"--dump-extension-api-with-docs",
+		"--validate-extension-api",
+		"--convert-3to4",
+		"--validate-conversion-3to4",
+		"--doctool",
+	};
```
Comment (akien-mga) [inline platform/macos/os_macos.h:97]: It's fine for now but having to maintain this list here is sure going to lead to inconsistencies eventually when relevant args are added/removed in `main`.

Most of those aren't actually headless though unless used together with `--headless`. E.g. `--dump-gdextension-interface` still shows a window by default.

We have `Main::is_cmdline_tool()` for most of these which could maybe be used here, especially if we were to change logic to imply that `cmdline_tool` means headless. I believe we wanted to do that in the past, but there might have been hurdles with headless mode that stopped it. CC @Calinou who might remember.

Comment (bruvzg) [reply platform/macos/os_macos.h:97]: > We have Main::is_cmdline_tool() for most of these which could maybe be used here

This will not work until `Main::setup` is executed, and it will be called long after the check (when list is used in the app entry point to select which version of `OS` to use).

> E.g. --dump-gdextension-interface still shows a window by default.

Not on macOS, everything on this list can't show windows. It was added specifically to prevent ~windows~ app icon in the dock from popping up when command line tools are used.

Comment (bruvzg) [reply platform/macos/os_macos.h:97]: The list is not new, just moved from `godot_main_macos.mm`, to avoid duplication.

Comment (akien-mga) [reply platform/macos/os_macos.h:97]: > > E.g. --dump-gdextension-interface still shows a window by default.
> 
> Not on macOS, everything on this list can't show windows. It was added specifically to prevent windows from popping up when command line tools are used.

Any reason for this behavior to be macOS specific?

Note: I see we imply headless for `--doctool` already, but not the other ones.

Comment (bruvzg) [reply platform/macos/os_macos.h:97]: No reason, I was sure it is the case for all platforms, but maybe it's not.

Comment (akien-mga) [reply platform/macos/os_macos.h:97]: Some other options missing from the list most likely:
```
--import  # unless we're not sure it's 100% safe headless
--export*  # likewise
--install-android-build-template
--dump-gdextension-interface-json
--test
```

Comment (bruvzg) [reply platform/macos/os_macos.h:97]: `export` and `import` seems to be opening an editor window, so not truly headless. And `install-android-build-template` is suboption for `export`.

Comment (bruvzg) [reply platform/macos/os_macos.h:97]: And `dump_` commands are indeed not-headless on Windows (show dummy window with splash screen), which is surprising.

Comment (bruvzg) [reply platform/macos/os_macos.h:97]: Added `--dump-gdextension-interface-json` and `--test`.

Comment (bruvzg) [reply platform/macos/os_macos.h:97]: Not sure what's the best way to handle this, it probably should be in `Main`, but there's an issue with the way command line arguments caused by macOS specific quirks:

- `OS_MacOS` need to know if it's headless on init to pick correct main loop for the app.
- File associations for GUI apps are handled by event, not command line arguments, so `Main::start` argument parsing logic can run before GUI app is finished starting, or it will miss the opened files.

I guess making a separate setup function in the `Main` (which will only set headless flag) might be better.

**Review by akien-mga — APPROVED** [review]

**Comment by madsbangh** [comment]
Reporter of https://github.com/godotengine/godot/issues/111592 here.

Works on my end 🎉

File: platform/macos/os_macos.h (hunk 1 above)
Comment (Calinou) [reply platform/macos/os_macos.h:97]: In the future, we'd like to make `--import` and `--export` imply `--headless`. This was originally attempted years ago, but we reverted it due to various bugs that occur with headless export. This is one of the reasons I created https://github.com/godotengine/godot/pull/109146.

**Review by Calinou — APPROVED** [review]
Code looks good to me.

**Comment by akien-mga** [comment]
Thanks!
