### PR TITLE
Fix verbose running message

### LINKED ISSUE #111989: Weird output when running a project in verbose mode
### Tested versions

4.5.1

### System information

W10

### Issue description

When you run a project in verbose mode, the editor will print something like
```
Running: C:/godot_source/bin/godot.windows.editor.dev.x86_64.exe
 %s --path
 %s C:/Program%20Files/Godot/BugReports/Repro
 %s --editor-pid
 %s 8872
 %s --debug-collisions
 %s --position
 %s 384,191
 %s --scene
 %s uid://d2xlutcxu02rh
```
Judging from the code, it's not intended 🙃

https://github.com/godotengine/godot/blob/084d5d407e62efcd5be9de44148c5dedce3b9386/editor/run/editor_run.cpp#L170-L175

### Steps to reproduce

1. Start Godot with `-v` CLI option
2. Run project

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #111989

The new message is like

> Running: C:/godot_source/bin/godot.windows.editor.dev.x86_64.exe --path C:/Program%20Files/Godot/BugReports/Repro --remote-debug tcp://127.0.0.1:9000 --editor-pid 16860 --debug-collisions --position 384,191 --scene uid://bqxg1acw1j6ep

### CODE REVIEW

File: editor/run/editor_run.cpp [hunk 1]
```diff
@@ -168,10 +168,13 @@ Error EditorRun::run(const String &p_scene, const String &p_write_movie, const V
...
 		if (OS::get_singleton()->is_stdout_verbose()) {
-			print_line(vformat("Running: %s", exec));
+			PackedStringArray output;
+			output.reserve_exact(instance_args.size() + 1);
+			output.append(vformat("Running: %s", exec));
 			for (const String &E : instance_args) {
-				print_line(" %s", E);
+				output.append(E);
 			}
+			print_line(String(" ").join(output));
```
Comment (Ivorforce) [inline editor/run/editor_run.cpp:177]: I'd probably go for a string-only approach, since it involves fewer concepts:

```suggestion
			String output = "Running: ";
			output += exec;
			for (const String &E : instance_args) {
				output += ' ';
				output += E;
			}
			print_line(output);
```

It's probably also slightly faster, but that likely doesn't matter.

Feel free to keep using the `join` approach if you prefer it.

**Review by Ivorforce — APPROVED** [review]

File: editor/run/editor_run.cpp (hunk 1 above)
Comment (akien-mga) [reply editor/run/editor_run.cpp:177]: Yeah I suggested `join` because I thought this was already a `Vector<String>` but if it isn't, a simple concatenation makes sense.

Comment (KoBeWi) [reply editor/run/editor_run.cpp:177]: I prefer using join.
And it's not really consistent across the codebase. Sometimes we even use StringBuilder.

> It's probably also slightly faster, but that likely doesn't matter.

Is it faster because there isn't many elements? I remember joining PackedStringArray is a lot faster than adding Strings.

Comment (Ivorforce) [reply editor/run/editor_run.cpp:177]: Normally, the advantage of using just one `String` is that you're growing just one buffer and have less function overhead. But with `reserve_exact` it may actually come out roughly even.

Anyway, this is not a bottleneck, so either should be fine.

**Comment by Repiteo** [comment]
Thanks!
