### PR TITLE
[Net] Fix Marshalls infinite recursion crash.

### LINKED ISSUE #51049: Game crashes when debugging the project (infinite recursion after ScriptDebuggerRemote::_put_variable)
### Godot version

3.3.2.stable

### System information

Windows 10, Nvidia GeForce GTX 1050, 27.21.14.5771

### Issue description

When running my game, my game crashes whenever I pause for debugging, no errors over in Godot Console, it seems to crash in Godot 3.3.2 stable, Godot 3.4 beta 1, Godot 3.4 beta 2.

### Steps to reproduce

1. Download my project
2. Run the game
3. Create any sort of structure and press T and click any node (road node, not Godot node).
4. Pause with a error or a breakpoint (wait like around 10-15 secs)
5. Observe the game crash.

### Minimal reproduction project

[CrashingGameWhenDebugging.zip](https://github.com/godotengine/godot/files/6905329/CrashingGameWhenDebugging.zip)

Video showcasing the crash:

https://user-images.githubusercontent.com/61322406/127625332-8cf366e9-5f19-4791-9471-4136852eb34b.mp4

### PR DESCRIPTION
**Pull request by Faless**
Variants like dictionaries and arrays can have cyclic references, which caused `encode_variant` to run an infinite recursion.
Instead of keeping a stack and looking for cyclic references which would make serialization slower, this commit adds a `MAX_RECURSION_DEPTH` constant to Variant, and have `encode_variant` keep track of the current recursion depth, bailing when it's too high since this likely means a cyclic reference has been encountered.

Fixes #51049

### CODE REVIEW

File: core/io/marshalls.cpp [hunk 1]
```diff
@@ -1433,15 +1432,19 @@ Error encode_variant(const Variant &p_variant, uint8_t *r_buffer, int &r_len, bo
...
 				if (buf) {
 					buf += len;
 				}
 				Variant *v = d.getptr(E);
 				ERR_FAIL_COND_V(!v, ERR_BUG);
-				encode_variant(*v, buf, len, p_full_objects);
+				err = encode_variant(*v, buf, len, p_full_objects, p_depth + 1);
+				if (err) {
+					return err;
+				}
```
Comment (akien-mga) [inline core/io/marshalls.cpp:1447]: Did you intend to keep this one specifically not as an `ERR_FAIL_COND_V`?

Comment (Faless) [reply core/io/marshalls.cpp]: No, I did not. Nice spot :+1: .

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.
