### PR TITLE
Fix connecting a signal with a double click is too difficult

### LINKED ISSUE #92382: Connecting a signal with a double click is too difficult
### Tested versions

- Reproducible in v4.3.dev6.mono.official [89850d553]

### System information

Godot v4.3.dev6.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.5212) - Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 Threads)

### Issue description

Connecting a signal using a double click is quite difficult. It nees a lot of fast clicking, a normal double click doesn't usually work. 

The culprit here is the popup window showing information about the signal. If I manage to double click before the popup pops up, all is fine and the "Connect Signal to a Method" window opens. But the popup pops up quite fast and after that the first mouse click (part 1 of a double click) just closes the popup. Then the second mouse click (part 2 of a double click)  doesn't do anything. Then the popup pops up again, even if the mouse cursor is not moved.

The simplest (even if not perfect) solution could be to ensure that the popup does not popup again if the mouse cursor is not moved a decent amount. The at least after the first unsuccessful double click the second attempt would work.

kuva

### Steps to reproduce

1. Move cursor over some signal in Node's Signals view.
2. Wait until the popup pops up.
3. Double click --> "Connect Signal to a Method" window does not open.
4. Be confused for a few seconds --> Popup pops up again.
5. Goto 3.

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #94030: Animation key button in property inspector fails to register click sometimes
### Tested versions

Reproducible in 4.3.beta [b97110cd307e4d78e20bfafe5de6c082194b2cd6]

### System information

Windows 11 (10.0.22631)

### Issue description

The symptoms of this issue are fairly straight-forward. Sometimes when you click the key button in the property inspector (after having selected an `AnimationPlayer` node with at least one animation) you'll find that the click doesn't always register.

I have yet to pin down exactly when or why it happens, but at least one consistent repro is if you let the tooltip of the property itself show up before you click, in which case the click will only dismiss the tooltip but not actually register as a click of the key button, thereby failing to add a new keyframe.

You should be able to see that in this video:

https://github.com/godotengine/godot/assets/4884246/4b1dd288-5e5c-4dfd-a8e5-8f33f505dce0

There may very well be other cases where this happens as well, which might speak to a bigger problem with the button in general.

### Steps to reproduce

1. Open the MRP
2. Select the `AnimationPlayer` node
3. Select the `Sprite` node
4. Hover over the key button for the `position` property
5. Wait for the tooltip to show up
6. Click the button
7. Note how no keyframe is added in the Animation dock

### Minimal reproduction project (MRP)

[key-button-fails-to-register.zip](https://github.com/user-attachments/files/16119562/key-button-fails-to-register.zip)

### LINKED ISSUE #94615: Popup window is closed by tooltips of other components on X11
### Tested versions

Godot_v4.3-beta1_linux.x86_64

### System information

WSL Version： 2.2.4.0     Kernel Version： 5.15.153.1-2       WSLg Version： 1.0.61          MSRDC Version： 1.2.5326            Direct3D Version： 1.611.1-81528511                         DXCore Version： 10.0.26091.1-240325-1447.ge-release             Windows Version： 10.0.19045.4651

### Issue description

X11 popup window is closed when the mouse hovers over other components with tooltip

### Steps to reproduce

tooltip

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #96008: Left click not working correctly after scroll and click outside PopupMenu
### Tested versions

Godot v4.3.stable 
Godot v4.1.2.stable 

### System information

Fedora Linux 39 (KDE Plasma) - X11 - Vulkan (Forward+) 

### Issue description

Left click not working correctly after scroll and click outside PopupMenu. Hover works.

[Screencast_20240823_223826.webm](https://github.com/user-attachments/assets/f534a6f4-bf7b-4c28-b4b1-fec13dab69d3)

If you right click again and then click outside without scrolling first it goes back to normal. Or if you use scroll wheel up/down again it also goes back to normal.

Could not recreate this issue on Windows or with single window mode on
 

### Steps to reproduce

Open a PopupMenu
Scroll outside the popup and then click outside
Try to click on any other control in the editor

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Hilderin**
- Fixes #92382
- Fixes #94030
- Fixes #96008
- Fixes #94615

The main issue was that when showing the tooltip, the editor was losing focus due to the custom tooltip popup. After that, the first mouse click was used to refocus the editor, making a double-click impossible.

Setting `FLAG_POPUP` to false solved the focus issue but created a new problem where the "normal" tooltip with the empty Control returned by `make_custom_tooltip` was also displayed. I modified `Viewport::_gui_show_tooltip` to skip creating the tooltip if the returned control is not visible. This is a bit of a hack; I did not know a better way. It's was not possible in `Viewport::_gui_show_tooltip` to have a tooltip text but preventing the tooltip to be showned.

Additionally, it created another problem where `EditorHelpBitTooltip::_target_gui_input` was triggered when the tooltip was shown, even if the mouse did not move. I don't know exactly why this happens. I added a flag to skip the first `_target_gui_input`.

Finally, without the "real" tooltip, the Viewport tries to create it every few seconds. I added the method `EditorHelpBitTooltip::is_tooltip_visible` to prevent displaying multiple custom tooltips in `ConnectionsDockTree::make_custom_tooltip`, and I created an `_invisible_tooltip` control global to the class to prevent the creation of a new Control every time.

Tested only on Windows 11 on Linux.

That's the result:

https://github.com/user-attachments/assets/694fd8bc-e571-41ca-a233-baa18e492ec1

Edit: Tested on Linux
Edit 2: Added #94030 and #96008 to the fixed issue list.
Edit 3: Added #94615 to the fixed issue list.

### CODE REVIEW

**Comment by Hilderin** [comment]
This issue that this PR fixes is in the Release Blocker for 4.3, is it normal that it has been put in 4.4 Milestone?

**Comment by Giganzo** [comment]
I wanted to see if this also solved a similar problem with the revert button (you have to click the button two times because of the tooltip)

[Screencast_20240725_155139.webm](https://github.com/user-attachments/assets/e937a363-b75b-4fe0-b035-053c15398808)

But that problem is still there. Should I open another issues for that?

**Comment by Giganzo** [comment]
Also with this fix, I don't seem to be able to open documentation when clicking inside the tooltips for signals, instead it highlights the text.

**Comment by Hilderin** [comment]
Thanks for testing @Giganzo 

> But that problem is still there. Should I open another issues for that?

I'll make the same fix for the tooltip in the Inspector to fix that.

> Also with this fix, I don't seem to be able to open documentation when clicking inside the tooltips for signals, instead it highlights the text.

Hum... I feared that could cause issues on other platforms. On Windows, as you can see in my video, click on the tooltip on open documentation works on Windows. I'm setuping my Linux machine to test that right now, I'll check if I can find a work around. Unfortunately, I don't have access to a Mac to test it.

**Comment by Hilderin** [comment]
I debugged it on Ubuntu Wayland and I have the same issue where I cannot click on documentation link. The problem comes from the fact that the mouse up event is not received by the `RichTextLabel` when the popup does not have focus (due to the `FLAG_POPUP` at false).

If someone with more experience can help on Wayland, I would appreciate it.

File: editor/editor_help.cpp [hunk 1]
```diff
@@ -3818,7 +3827,20 @@ void EditorHelpBitTooltip::show_tooltip(EditorHelpBit *p_help_bit, Control *p_ta
...
+}
+
+bool EditorHelpBitTooltip::is_tooltip_visible() {
+	return _current_tooltip;
+}
+
+Control *EditorHelpBitTooltip::get_invisible_control() {
+	ERR_FAIL_NULL_V(_current_tooltip, nullptr);
+	return _current_tooltip->_invisible_control;
 }
```
Comment (dalexeev) [inline editor/editor_help.cpp:3844]:
```suggestion
Control *EditorHelpBitTooltip::make_invisible_control() {
	Control *control = memnew(Control);
	control->set_visible(false);
	return control;
}
```

There is no point in storing `_invisible_control` in `EditorHelpBitTooltip`. The control returned by `make_custom_tooltip()` will be automatically freed when the standard tooltip disappears.

Also `_current_tooltip` is no longer needed.

File: editor/connections_dialog.cpp [hunk 2]
```diff
@@ -899,9 +899,15 @@ Control *ConnectionsDockTree::make_custom_tooltip(const String &p_text) const {
...
-	EditorHelpBit *help_bit = memnew(EditorHelpBit(p_text));
-	EditorHelpBitTooltip::show_tooltip(help_bit, const_cast<ConnectionsDockTree *>(this));
-	return memnew(Control); // Make the standard tooltip invisible.
+	// Show the custom tooltip only if it is not already visible.
+	// The Viewport will retrigger make_custom_tooltip every few seconds
+	// because the return control is not visible even if the custom tooltip is displayed.
+	if (!EditorHelpBitTooltip::is_tooltip_visible()) {
+		EditorHelpBit *help_bit = memnew(EditorHelpBit(p_text));
+		EditorHelpBitTooltip::show_tooltip(help_bit, const_cast<ConnectionsDockTree *>(this));
+	}
```
Comment (dalexeev) [inline editor/connections_dialog.cpp:908]: I think we can put this logic in `show_tooltip()` instead of duplicating it in multiple places.

File: editor/editor_help.cpp [hunk 3]
```diff
@@ -3818,7 +3827,20 @@ void EditorHelpBitTooltip::show_tooltip(EditorHelpBit *p_help_bit, Control *p_ta
 	tooltip->add_child(p_help_bit);
 	p_target->get_viewport()->add_child(tooltip);
 	p_help_bit->update_content_height();
+	// When FLAG_POPUP is false, it prevents the editor from losing focus when displaying the tooltip.
+	// This way, clicks and double-clicks are still available outside the tooltip.
+	tooltip->set_flag(Window::FLAG_POPUP, false);
```
Comment (dalexeev) [inline editor/editor_help.cpp:3832]: As far as I remember, this flag makes hyperlinks in the tooltip unclickable.

File: scene/main/viewport.cpp [hunk 4]
```diff
@@ -1457,17 +1457,24 @@ void Viewport::_gui_show_tooltip() {
...
+	// Controls can implement `make_custom_tooltip` to provide their own tooltip.
+	// This should be a Control node which will be added as child to a TooltipPanel.
+	Control *base_tooltip = tooltip_owner->make_custom_tooltip(gui.tooltip_text);
+
+	// When the custom control is not visible, don't show any tooltip.
+	// This way, the custom tooltip from ConnectionsDockTree can create
+	// its own tooltip without conflicting with the default one, even an empty tooltip.
+	if (base_tooltip && !base_tooltip->is_visible()) {
+		return;
+	}
```
Comment (dalexeev) [inline scene/main/viewport.cpp:1469]: This is a nice workaround! :+1: Instead of `is_visible()`, we could check a method or metadata to ensure compatibility is preserved, but the current option looks good to me too.

File: editor/editor_help.cpp (hunk 3 above)
Comment (Hilderin) [reply editor/editor_help.cpp:3832]: Effectively. It works on Windows, but not on Linux (Wayland). Is there another way to display a popup without getting the focus?

File: editor/editor_help.cpp (hunk 1 above)
Comment (Hilderin) [reply editor/editor_help.cpp]: I refactored the method `EditorHelpBitTooltip::show_tooltip` to received the symbol text and an optional description. This was, I could put all the display logic in one place. I still need a static variable to prevent the custom tooltip to be displayed multiple times.

File: editor/connections_dialog.cpp (hunk 2 above)
Comment (Hilderin) [reply editor/connections_dialog.cpp]: Done, see my other comment!

File: editor/editor_help.cpp (hunk 3 above)
Comment (Hilderin) [reply editor/editor_help.cpp:3842]: I found a way to make the hyperlinks works in tooltips on Linux. That also fix the hyperlink in the Editor Settings tooltips.

I removed the faulty code in `display_server_x11` that was added by #69678 to fix when the mouse button release was done outside the Color Picker window. I was not able to reproduce the problem after my modifications, and from what I tested, it did not even pass into the removed code in that situation.

File: scene/main/viewport.cpp (hunk 4 above)
Comment (Hilderin) [reply scene/main/viewport.cpp:1469]: I'll let it like that then, thanks.

File: platform/linuxbsd/x11/display_server_x11.cpp [hunk 5]
```diff
@@ -4840,14 +4840,7 @@ void DisplayServerX11::process_events() {
 
 					WindowID window_id_other = INVALID_WINDOW_ID;
 					Window wd_other_x11_window;
-					if (wd.focused) {
```
Comment (Hilderin) [inline platform/linuxbsd/x11/display_server_x11.cpp:4843]: This code was from #69678 but removing it fixes the hyperlinks in tooltip and from what I could test, I was not able to reproduce the problem with the Color picker on Ubuntu Wayland.

**Comment by akien-mga** [comment]
> This issue that this PR fixes is in the Release Blocker for 4.3, is it normal that it has been put in 4.4 Milestone?

The issue isn't critical, and the fix is not trivial, so at this stage (mere days to stable release) we prefer to be cautious and merge after the 4.3 release. It can then be cherry-picked for 4.3.1 once we've confirmed in the `master` branch that there are no obvious regressions.

**Comment by matheusmdx** [comment]
This pr also fixes #94030

**Comment by Giganzo** [comment]
This pr looks like it also fixes https://github.com/godotengine/godot/issues/94615
There seems to be a difference compared to 4.3.stable on Windows, with this pr on Linux you can trigger tooltips in the inspector outside of the popup. 

image

**Comment by Parsnip** [comment]
Similar issue happens with menu items that have sub menus, such as the Editor Docks or the Editor Layout items in the Editor menu.
Eg, hovering mouse over the Editor Layout item so that the sub menu opens and then moving mouse downwards to other menu items (not the sub menu items), the mouse hover effect isn't displayed for as long as the sub menu remains open.
I have assumed this was a case of the submenu grabbing the focus, and then "releasing" it when it closes.

But to me at least it seems incorrect for the submenu to grab the mouse focus as soon as the menu opens, instead it should only take the mouse focus when mouse moves over the items. Mouse focus should always be where the cursor is, no? But maybe there's a reason it's this way.

To be clear I don't know if the tooltip handling is different from how the editor handles opening its submenus, so this might be an off-topic comment so pardon if that is the case. I was however reminded of this while reading this issue and figured I'd mention it all the same. I also don't know if the behavior is the same on other platforms, I've only used Godot on Windows.

**Comment by kitbdev** [comment]
Needs rebase to fix conflicts.
- Seems to fix https://github.com/godotengine/godot/issues/99287 for me after I rebase manually.

**Comment by akien-mga** [comment]
The merge conflict seems to have been caused by #98160, which also seemed to aim at fixing jittery tooltips. I'm not sure whether that change should be kept in this PR, or reverted (i.e. keeping the original code from this PR without #98160). CC @Rindbee @KoBeWi

**Comment by Rindbee** [comment]
> keeping the original code from this PR without #98160

Doing this will re-open #98135 if `p_target->get_viewport()` is the root window.  

`1024` is a hard-coded minimum window width, but in tiled windows the actual width may be smaller than `1024`. If the root window is recalculated, it will first be set to `1024` and then forced to the actual size. This can cause visible jitter on i3wm/sway.

**Comment by Hilderin** [comment]
> Doing this will re-open #98135 if `p_target->get_viewport()` is the root window.

I agree with @Rindbee, I just pushed a fix for the merge conflict including the modification from #98160. It seems to work fine without extensive tests.

File: editor/editor_help.h [hunk 6]
```diff
@@ -325,20 +325,22 @@ class EditorHelpBit : public VBoxContainer {
...
 
+	static bool _is_tooltip_visible;
 	Timer *timer = nullptr;
 	int _pushing_input = 0;
 	bool _need_free = false;
 
 	void _start_timer();
 	void _safe_queue_free();
 	void _target_gui_input(const Ref<InputEvent> &p_event);
+	static Control *_make_invisible_control();
```
Comment (dalexeev) [inline editor/editor_help.h:336]: I don't know if it's a best practice, but I personally prefer to place static methods before non-static ones.

File: editor/editor_inspector.cpp [hunk 7]
```diff
@@ -1005,30 +1005,30 @@ Control *EditorProperty::make_custom_tooltip(const String &p_text) const {
...
-			if (!help_bit->get_description().is_empty()) {
-				description += "\n" + help_bit->get_description();
+			const String custom_warning_description = "[b][color=" + get_theme_color(SNAME("warning_color")).to_html(false) + "]" + custom_warning + "[/color][/b]";
+			if (description.is_empty()) {
+				description = custom_warning_description;
+			} else {
+				description = custom_warning_description + "\n" + description;
 			}
-			help_bit->set_description(description);
 		}
```
Comment (dalexeev) [inline editor/editor_inspector.cpp:1029]: This changes the logic, since `parse_symbol()` set the description, it is read using `get_description()`. The previous logic appends/prepends the symbol description, rather than replacing it.

**Review by dalexeev — APPROVED** [review]
Overall looks good to me. :+1: I tested it on Linux and everything seems to work correctly. There is a comment about custom descriptions in the inspector and minor code style suggestions.

**Comment by Hilderin** [comment]
Thanks @dalexeev for finishing this PR, very appreciated :)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks @Hilderin and @dalexeev!

File: editor/editor_help.cpp [hunk 8]
```diff
@@ -3806,76 +3806,108 @@ EditorHelpBit::EditorHelpBit(const String &p_symbol) {
...
-	//content->set_context_menu_enabled(true); // TODO: Fix opening context menu hides tooltip.
+	content->set_selection_enabled(p_allow_selection);
+	content->set_context_menu_enabled(p_allow_selection);
 	content->connect("meta_clicked", callable_mp(this, &EditorHelpBit::_meta_clicked));
 	add_child(content);
 
 	if (!p_symbol.is_empty()) {
-		parse_symbol(p_symbol);
+		parse_symbol(p_symbol, p_prologue);
 	}
```
Comment (dalexeev) [inline editor/editor_help.cpp:3816]: Despite my best efforts, I still missed one thing. Please add this if you will cherry-pick this for 4.3. For master, this will be fixed in #91060.

```diff
 	if (!p_symbol.is_empty()) {
 		parse_symbol(p_symbol, p_prologue);
+	} else if (!p_prologue.is_empty()) {
+		set_custom_text(String(), String(), p_prologue);
 	}
```
