### PR TITLE
pcre2: Update to upstream version 10.42 (take two)

### LINKED ISSUE #76174: [4.0] RegEx.search_all causes 'Condition "p_ptr == nullptr" is true.' error
### Godot version

v4.0.2.stable.arch_linux

### System information

ArchLinux rolling, Linux 6.2.11-arch1-1. Vulkan Mobile on RX 6900XT

### Issue description

When using RegEx.search_all, an error is added to the log:
> ERROR: Condition "p_ptr == nullptr" is true.
>   at: free_static (core/os/memory.cpp:148)

The number of triggered errors seems to be affected by the number of matches the regex makes.

### Steps to reproduce

Have any script that does something using `RegEx.search_all`:

```gd
var regex: RegEx = RegEx.new()
regex.compile(".")
regex.search_all("test")
```

The above example will trigger 5 error messages (1 per match + 1 fixed).

### Minimal reproduction project

[minimal_project.zip](https://github.com/godotengine/godot/files/11252686/minimal_project.zip)

Script was made for running through [CLI](https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html):
`godot --headless -s new_script.gd`

### PR DESCRIPTION
**Pull request by akien-mga**
Changelog: https://github.com/PCRE2Project/pcre2/blob/pcre2-10.42/ChangeLog

This fixes support for RISC-V architectures in the sljit library, so we enable the module's compilation for `rv64` too.

Redo of #70447 which I reverted due to a regression described there:
https://github.com/godotengine/godot/pull/70447#issuecomment-1363812432

Fixes #76174

---

From @vonagam:

> This PR caused those lines to appear (repeated multiple times) in unit tests logs at the start.
>
> ```
> ERROR: Condition "p_ptr == nullptr" is true.
>    at: free_static (core/os/memory.cpp:148)
> ```
>
> While tests do not fail because of that, this does not seem right...
> Or is it unavoidable known issue?

My early findings:

Backtrace:
```
(gdb) bt
#0  Memory::free_static (p_ptr=0x0, p_pad_align=false) at core/os/memory.cpp:149
#1  0x0000000006c247fb in _regex_free (ptr=0x0, user=0x0) at modules/regex/regex.cpp:43
#2  0x0000000006c1cb84 in pcre2_match_32 (code=0xc9019b0, subject=0xc8a74c0, length=9, start_offset=0, options=0, match_data=0xc830060, mcontext=0xc9863b0) at thirdparty/pcre2/src/pcre2_match.c:6846
#3  0x0000000006c25c85 in RegEx::search (this=0x7fffffffc300, p_subject=..., p_offset=0, p_end=-1) at modules/regex/regex.cpp:219
#4  0x00000000057cfee7 in TestRegEx::DOCTEST_ANON_FUNC_6556 () at ./modules/regex/tests/test_regex.h:81
#5  0x00000000053d282d in doctest::Context::run (this=0x7fffffffd0e0) at ./thirdparty/doctest/doctest.h:6930
#6  0x00000000057d5540 in test_main (argc=2, argv=0x7fffffffd728) at tests/test_main.cpp:174
#7  0x0000000005393ec2 in Main::test_entrypoint (argc=2, argv=0x7fffffffd728, tests_need_run=@0x7fffffffd1bf: true) at main/main.cpp:608
#8  0x0000000005333cc2 in main (argc=2, argv=0x7fffffffd728) at platform/linuxbsd/godot_linuxbsd.cpp:55
```

It probably comes from this change:
```
9. Removed the use of an initial backtracking frames vector on the system stack
in pcre2_match() so that it now always uses the heap. (In a multi-thread
environment with very small stacks there had been an issue.) This also is
tidier for JIT matching, which didn't need that vector. The heap vector is now
remembered in the match data block and re-used if that block itself is re-used.
It is freed with the match data block.
```

We likely need to change our `_regex_free` (and maybe `_regex_malloc`) to take this new heap vector into account somehow.

### CODE REVIEW

**Comment by akien-mga** [comment]
Added a `nullptr` check in `_regex_free` as suggested by @lawnjelly, and it solved the error spam.

I don't know if there are other implications for that upstream change which caused this error spam in the first place.

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

File: thirdparty/pcre2/src/sljit/sljitExecAllocator.c [hunk 1]
```diff
@@ -152,9 +152,6 @@ static SLJIT_INLINE void apple_update_wx_flags(sljit_s32 enable_exec)
 {
 #if MAC_OS_X_VERSION_MIN_REQUIRED >= 110000
 	pthread_jit_write_protect_np(enable_exec);
-#elif defined(__clang__)
-	if (__builtin_available(macOS 11.0, *))
-		pthread_jit_write_protect_np(enable_exec);
 #else
 #error "Must target Big Sur or newer"
```
Comment (aaronfranke) [inline thirdparty/pcre2/src/sljit/sljitExecAllocator.c:156]: As of this PR cherry-picked into the 3.x branch, I am unable to compile Godot on macOS, because Godot 3.x targets macOS 10.15+, and this change breaks support for macOS < 11.0.

Comment (bruvzg) [reply thirdparty/pcre2/src/sljit/sljitExecAllocator.c:156]: > I am unable to compile Godot on macOS, because Godot 3.x targets macOS 10.15+, and this change breaks support for macOS < 11.0.

Target version should be changed to 11.0, 10.15 for arm64 existed only as the early alphas.

Comment (aaronfranke) [reply thirdparty/pcre2/src/sljit/sljitExecAllocator.c:156]: Thanks, fixed in https://github.com/godotengine/godot/pull/82007
