### PR TITLE
Fix root folder logic in the filesystem

### LINKED ISSUE #99932: Folder color is bugged in FileSystem
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

Mac M1 Pro macos 15.1.1 

### Issue description

When you set the folder color most time one of the folders color is bugged 

### Steps to reproduce

Just create 3 folders in my case and try to set the color in the file tree it's fine but in the file view it's not, as you can see in the image the Assets folder color is yellow in the file tree but default in the file view

Image

### Minimal reproduction project (MRP)

[hell-cycle.zip](https://github.com/user-attachments/files/17981963/hell-cycle.zip)

### LINKED ISSUE #100159: Root folder color can be changed if selected in a particular order
### Tested versions

Tested in v4.4.dev.custom_build [aa8d9b83f]

### System information

Godot v4.4.dev (aa8d9b83f) - Windows 10.0.22631 - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 (NVIDIA; 32.0.15.6094) - 12th Gen Intel(R) Core(TM) i7-12700KF (20 threads)

### Issue description

It appears that the file/folder multi-selection logic is not working correctly. When I select multiple folders (including the root folder), then depending on the order of selection, I can either set the root folder's color or I can't. From inspecting the file system logic, it appears that I should not be able to change the root folder's color regardless of selection order. 

Menu when root is not the first folder selected:
Image

Menu when root is the first folder selected:
Image

This issue appears related to #99932 

### Steps to reproduce

1. Open any project and create a folder under the root folder in the file system. 
2. Select the root folder then multi-select your created sub folder (you should not see an option to set the file color in the menu after right clicking)
3. Select only the sub folder then multi-select your root folder (you should see an to set the file color in the menu after right clicking)

### Minimal reproduction project (MRP)

[broken_filesystem.zip](https://github.com/user-attachments/files/18050273/broken_filesystem.zip)

### PR DESCRIPTION
**Pull request by alessand10**
This PR should:
Fix #100159
Fix #99932

The previous logic appears to check that the root folder is not selected using the following bit of logic:
```
p_paths[0] != "res://"
```

But the function that populates p_path, which is _tree_get_selected(...), inserts the actively selected item at p_path[0]. This means that the root folder may still be selected, but may not be the first element in p_path:
```
Vector<String> FileSystemDock::_tree_get_selected(bool remove_self_inclusion, bool p_include_unselected_cursor) const {
	// Build a list of selected items with the active one at the first position.
	Vector<String> selected_strings;

	TreeItem *cursor_item = tree->get_selected();
	if (cursor_item && (p_include_unselected_cursor || cursor_item->is_selected(0)) && cursor_item != favorites_item) {
		selected_strings.push_back(cursor_item->get_metadata(0));
	}
        ... 
```

The root folder will only be at p_path[0] if it is the actively selected item, but otherwise it will exist at p_path[1]. To compensate for this, I have added an additional check that verifies that the root folder is not at p_path[0] and also not at p_path[1] before determining if the root folder is selected:

```
bool root_path_not_selected = p_paths[0] != "res://" && (p_paths.size() <= 1 || p_paths[1] != "res://");
```

### CODE REVIEW

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -3289,25 +3294,31 @@ void FileSystemDock::_file_and_folders_fill_popup(PopupMenu *p_popup, const Vect
 		}
 	}
 
+	// Add the options that are only available when a single item is selected
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:3297]:
```suggestion
	// Add the options that are only available when a single item is selected.
```
Same in other comments.

**Review by KoBeWi — APPROVED** [review]
Looks like `res://` is reliably either at `p_paths[0]` or `p_paths[1]`, so this works 🤔

**Comment by akien-mga** [comment]
Thanks!
