### PR TITLE
[Editor] Add option to override editor UI layout direction.

### LINKED ISSUE #84998: in a right to left language in Godot the Ui gets reversed, and its hard to work.
### Godot version

4.1.2

### System information

Godot v4.1.2.stable.mono - Windows 11 22h2 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3742) - 11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz (12 Threads)

### Issue description

in a right to left language (in my case Persian) the Ui gets inverted and i know it should be like that but you just cant work i will leave a screen shot so  you can see
Screenshot 2023-11-16 042657

### Steps to reproduce

change the language to Persian

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
- Adds `Interface → Editor → UI Layout Direction` editor setting to override editor UI layout direction independently of the project layout direction (`Internationalization → Rendering → Root Node Layout Direction` project setting).
- Adds `Based on System Locale` option to both settings (to allow matching UI layout direction to the system UI direction regardless of used locale).

Fixes https://github.com/godotengine/godot/issues/84998

### CODE REVIEW

File: scene/gui/control.cpp [hunk 1]
```diff
@@ -49,6 +49,7 @@
 #include "servers/text_server.h"
 
 #ifdef TOOLS_ENABLED
+#include "editor/editor_settings.h"
```
Comment (akien-mga) [inline scene/gui/control.cpp:52]: I see it's a pre-existing issue here, but `scene` code shouldn't depend on `editor` code.

IMO the `root_dir` stuff should be made a public (static?) property and set from outside `control.cpp` by the editor. Similar to how we handle swapping Ok/Cancel on AcceptDialog.

Comment (bruvzg) [reply scene/gui/control.cpp]: Changed to use static property.

**Review by akien-mga — APPROVED** [review]

File: scene/gui/control.cpp [hunk 2]
```diff
@@ -197,6 +197,12 @@ void Control::reparent(Node *p_parent, bool p_keep_global_transform) {
 
 // Editor integration.
 
+int Control::root_dir = 0;
```
Comment (YuriSizov) [inline scene/gui/control.cpp:200]: I'd prefer if we used a full name so it's not confused with anything else, like directory.
