### PR TITLE
[Editor] Fix crash in `ConnectionsDialog`

### LINKED ISSUE #107664: Editor crash when editing signal connections
### Tested versions

4.5 46c495c

### System information

W10

### Issue description

```
ERROR: Parameter "mem" is null.
   at: Memory::alloc_static (C:\godot_source\core/os/memory.cpp:111)
ERROR: Out of memory
   at: (C:\godot_source\core/templates/local_vector.h:179)
```
```
LocalVector<Pair<enum Variant::Type,StringName>,unsigned int,0,0>::reserve(unsigned int p_size) Line 179 (c:\godot_source\core\templates\local_vector.h:179)
ConnectDialog::_filter_method_list(const List<MethodInfo,DefaultAllocator> & p_methods, const MethodInfo & p_signal, const String & p_search_string) Line 294 (c:\godot_source\editor\connections_dialog.cpp:294)
ConnectDialog::_update_method_tree() Line 385 (c:\godot_source\editor\connections_dialog.cpp:385)
ConnectDialog::_tree_node_selected() Line 180 (c:\godot_source\editor\connections_dialog.cpp:180)
call_with_variant_args_helper<ConnectDialog>(ConnectDialog * p_instance, void(ConnectDialog::*)() p_method, const Variant * * p_args, Callable::CallError & r_error, IndexSequence<> __formal) Line 228 (c:\godot_source\core\variant\binder_common.h:228)
call_with_variant_args<ConnectDialog>(ConnectDialog * p_instance, void(ConnectDialog::*)() p_method, const Variant * * p_args, int p_argcount, Callable::CallError & r_error) Line 338 (c:\godot_source\core\variant\binder_common.h:338)
CallableCustomMethodPointer<ConnectDialog,void>::call(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 107 (c:\godot_source\core\object\callable_method_pointer.h:107)
Callable::callp(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 58 (c:\godot_source\core\variant\callable.cpp:58)
Object::emit_signalp(const StringName & p_name, const Variant * * p_args, int p_argcount) Line 1288 (c:\godot_source\core\object\object.cpp:1288)
Node::emit_signalp(const StringName & p_name, const Variant * * p_args, int p_argcount) Line 4130 (c:\godot_source\scene\main\node.cpp:4130)
Object::emit_signal<>(const StringName & p_name) Line 941 (c:\godot_source\core\object\object.h:941)
SceneTreeEditor::set_selected(Node * p_node, bool p_emit_selected) Line 1471 (c:\godot_source\editor\gui\scene_tree_editor.cpp:1471)
ConnectDialog::set_dst_node(Node * p_node) Line 532 (c:\godot_source\editor\connections_dialog.cpp:532)
ConnectDialog::init(const ConnectDialog::ConnectionData & p_cd, const Vector<String> & p_signal_args, bool p_edit) Line 675 (c:\godot_source\editor\connections_dialog.cpp:675)
ConnectionsDock::_open_connection_dialog(TreeItem & p_item) Line 1207 (c:\godot_source\editor\connections_dialog.cpp:1207)
ConnectionsDock::_tree_item_activated() Line 1166 (c:\godot_source\editor\connections_dialog.cpp:1166)
call_with_variant_args_helper<ConnectionsDock>(ConnectionsDock * p_instance, void(ConnectionsDock::*)() p_method, const Variant * * p_args, Callable::CallError & r_error, IndexSequence<> __formal) Line 228 (c:\godot_source\core\variant\binder_common.h:228)
call_with_variant_args<ConnectionsDock>(ConnectionsDock * p_instance, void(ConnectionsDock::*)() p_method, const Variant * * p_args, int p_argcount, Callable::CallError & r_error) Line 338 (c:\godot_source\core\variant\binder_common.h:338)
CallableCustomMethodPointer<ConnectionsDock,void>::call(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 107 (c:\godot_source\core\object\callable_method_pointer.h:107)
Callable::callp(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 58 (c:\godot_source\core\variant\callable.cpp:58)
```

### Steps to reproduce

1. Open the attached scene
2. Click ItemList
3. In Node dock, edit the `item_selected` connection and press OK (without any changes)
4. Click Tree
5. In Node dock, double click `cell_selected` signal

### Minimal reproduction project (MRP)

[Crasher.tscn.txt](https://github.com/user-attachments/files/20794013/Crasher.tscn.txt)

### PR DESCRIPTION
**Pull request by AThousandShips**
* Fixes: #107664

### CODE REVIEW

File: editor/connections_dialog.cpp [hunk 1]
```diff
@@ -290,7 +290,7 @@ List<MethodInfo> ConnectDialog::_filter_method_list(const List<MethodInfo> &p_me
 
 	LocalVector<Pair<Variant::Type, StringName>> effective_args;
 	int unbind = get_unbinds();
-	effective_args.reserve(p_signal.arguments.size() - unbind);
+	effective_args.reserve(MAX(p_signal.arguments.size() - unbind, 0));
```
Comment (AThousandShips) [inline editor/connections_dialog.cpp:293]: Could replace with:
```suggestion
	if (p_signal.arguments.size() > unbind) {
		effective_args.reserve(p_signal.arguments.size() - unbind);
	}
```
But think as it is is cleaner

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank *you*!
