### PR TITLE
Disable signal callback generation in C#

### LINKED ISSUE #18721: (MONO) New signal method declared outside of class
**Godot version:**
3.0.3 rc1 Mono Build

**Issue description:**
When using the editor to connect a signal to a C# script, the new method declaration is added to the end of the file, and outside of the class.  It should instead add the new method just before the final closing brace.

**Steps to reproduce:**
1. Create a button node. 
2. Attach a new C# script to this node.
3. Select the button in the editor, choose Node -> Signals
4. Select the "pressed()" signal and click connect.
5. Choose the same button as the "Node to Connect." Leave everything default and hit connect.
6. Notice that the new method is created outside of the class.

Example:
```cs
using Godot;
using System;

public class btn_move : Button
{
    public override void _Ready()
    {
    }
} //End of class


private void _on_Button_pressed()
{
    // Replace with function body
}
```

This is a low priority issue as the easy workaround is to just move the closing brace of the class, but this creates invalid code and could be confusing.

### PR DESCRIPTION
**Pull request by paulloz**
A while ago, we talked about disabling the signal callback generation altogether for C# until we have a better implementation. Reasons are, it currently generates the method outside the class (creates compilation error, obviously), and the behaviour is weirdly inconsistent depending on how you have external editors configured.

To prevent confusion like "the dialog didn't do the thing", I added a small message in the connection window, depending on the language of the script. Not sure if this is wanted, let me know (also, the message itself probably kinda sucks, feel free to suggest something better).

godot windows editor dev x86_64 mono_HnMDcxVcl2

*Bugsquad edit:*
- Works around / fixes #18721.

### CODE REVIEW

File: core/object/script_language.h [hunk 1]
```diff
@@ -256,6 +256,7 @@ class ScriptLanguage : public Object {
 	virtual bool can_inherit_from_file() const { return false; }
 	virtual int find_function(const String &p_function, const String &p_code) const = 0;
 	virtual String make_function(const String &p_class, const String &p_name, const PackedStringArray &p_args) const = 0;
+	virtual bool can_make_function() { return true; }
```
Comment (AThousandShips) [inline core/object/script_language.h:259]: I'd suggest adding a virtual method for this to `ScriptLanguageExtension` so we don't forget about it

Comment (paulloz) [reply core/object/script_language.h:259]: Double-checking before I do something wrong. We're talking about adding an `EXBIND`, and a `GDVIRTUAL_BIND` in `ScriptLanguageExtension`, right?

Comment (AThousandShips) [reply core/object/script_language.h:259]: Yep! There should be good examples of `bool` returns there that can be copied

**Review by zaevi — APPROVED** [review]
Looks good to me👍

File: editor/connections_dialog.cpp [hunk 2]
```diff
@@ -433,6 +434,23 @@ void ConnectDialog::_update_ok_enabled() {
...
+		return;
+	}
+
+	ScriptLanguage *language = scr->get_language();
+	if (language->can_make_function()) {
+		warning_label->set_visible(false);
+		return;
+	}
+
+	warning_label->set_text(vformat(TTR("%s: callback code won't be generated, please write it yourself."), language->get_name()));
```
Comment (AThousandShips) [inline editor/connections_dialog.cpp:450]:
```suggestion
	warning_label->set_text(vformat(TTR("%s: Callback code won't be generated, please add it manually."), language->get_name()));
```
Think this might feel more friendly

**Review by AThousandShips — APPROVED** [review]
LGTM code wise

**Review by Calinou — APPROVED** [review]
Until we find a better workaround for this (such as displaying the code you should copy in a read-only TextEdit), this is probably for the better.

**Review by raulsntos — COMMENTED** [review]
I feel a bit hesitant about adding new API to ScriptLanguage. I don't know if there are Script languages other than C# that would make use of this, adding this just for C# knowing that C# will eventually move away from the ScriptLanguage API feels wrong.

But if the area maintainers are fine with this, then I do think this is an improvement over the current state for C#.

**Comment by paulloz** [comment]
> I feel a bit hesitant about adding new API to ScriptLanguage. I don't know if there are Script languages other than C# that would make use of this, adding this just for C# knowing that C# will eventually move away from the ScriptLanguage API feels wrong.

I had a similar feeling. We could simply always return an empty string and not display anything to the user. It'd be a bit worse UX, but still better than the current state, IMHO. In that case, I'd still modify the `add_callback` logic to not overwrite the file if `make_function` returns a string of length zero...

File: modules/mono/csharp_script.cpp [hunk 3]
```diff
@@ -516,22 +516,10 @@ static String variant_type_to_managed_name(const String &p_var_type_name) {
...
-			s += ", ";
-		}
-
-		s += variant_type_to_managed_name(arg.get_slice(":", 1)) + " " + escape_csharp_keyword(arg.get_slice(":", 0));
-	}
-	s += ")\n{\n    // Replace with function body.\n}\n";
-
-	return s;
+	// TODO
+	// Implement function generation. This has been disabled for now because the behaviour was not consistent
```
Comment (akien-mga) [inline modules/mono/csharp_script.cpp:520]: We use en_US spelling:
```suggestion
	// Implement function generation. This has been disabled for now because the behavior was not consistent
```

**Review by akien-mga — APPROVED** [review]
I think it's fine to add this method. It does feel very specific, but `find_function` and `make_function` do too and they're already part of the API. Having a boolean check to control the user of those two methods doesn't seem too far fetched.

File: modules/mono/csharp_script.cpp (hunk 3 above)
Comment (paulloz) [reply modules/mono/csharp_script.cpp:520]: Noted. I'm going to re-write this comment as per @raulsntos' point [above](https://github.com/godotengine/godot/pull/87952#discussion_r1478874974) anyway.

**Review by raulsntos — APPROVED** [review]
LGTM. Thanks!

**Comment by akien-mga** [comment]
Thanks!

**Comment by dayo05** [comment]
I have a question about this: is this breaks custom signal registration by code as [introduced on docs](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_signals.html#custom-signals-as-c-events)?

**Comment by paulloz** [comment]
> I have a question about this: is this breaks custom signal registration by code as [introduced on docs](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_signals.html#custom-signals-as-c-events)?

Hello! No, this only blocks the editor to write the empty method in your `.cs` file when you connect a signal to an inexistent method from Godot's UI.
