### PR TITLE
Load/update GDScript from disk on load if cache mode is CACHE_MODE_IGNORE

### LINKED ISSUE #49298: Auto Reload Scripts On External Change does not work
**Godot version:**
v4.0.dev.custom_build.5d9cab3ae

**OS/device including version:**
Artix Linux 5.12.8
`$ uname -a` provides the following output:
`Linux x1e2 5.12.8-artix1-1 #1 SMP PREEMPT Fri, 28 May 2021 22:51:03 +0000 x86_64 GNU/Linux`

**Issue description:**
Editing scripts from an external editor and saving them does not trigger the Godot editor to reload the script.  Tried this with neovim within terminal, and also VS Code.

**Steps to reproduce:**
Open the editor settings and set the following:
 - *General > Text Editor > Files > Auto Reload Scripts on External Change* : True
 - *General > Text Editor > Files > Auto Reload and Parse Scripts On Save* : True
 - *General > Text Editor > External > Use External Editor* : True

For neovim:
 - *General > Text Editor > External > Exec Path* : `/usr/local/bin/st` (I use suckless terminal)
 - *General > Text Editor > External > Exec Flags* : `-n TerminalFloat /usr/bin/nvim -c "cd {project}" -c "call cursor ({line}, {col})" {file}`  -- this names the terminal TerminalFloat so that my window manager makes it floating (i3-gaps), launches /usr/bin/nvim (neovim), and issues to neovim the command `"cd {project}"` and `"call cursor ({line},{col})"`, and passes the filename `{file}`.

For VS Code:
 - *General > Text Editor > External > Exec Path* : `/usr/bin/code`
 - *General > Text Editor > External > Exec Flags* : `{project} --goto {file}:{line}:{col}` -- exactly as the docs say

In either case, continue:
 - Open a script (new or existing) from the Godot editor -- it will correctly open the file in the specified external editor
 - Edit and save the script from within the external editor, particularly making changes to exported variables
 - Observe that no Output log message appears stating that the script was reloaded, and observe that no changes appear in the inspector to reflect changes made from the external editor
 
**Minimal reproduction project:**

An empty new project, with external text editor settings enabled

**Screenshots**
image
image

### PR DESCRIPTION
**Pull request by Rindbee**
`GDScript` has two caches, in `ResourceCache` and `GDScriptCache`.
Previously, it would not load/update from disk even if the cache mode was `CACHE_MODE_IGNORE`. Causes reloading `GDScript` to not work when externally changed.

[Peek 2022-07-18 22-04.webm](https://user-images.githubusercontent.com/30386067/179908456-9db2c488-7166-4bf1-b187-6bfc757ed80d.webm)

The left one is Alpha12

~~Fix #49298.~~

**Edit:**

I've found that external editing can be roughly divided into two cases:

1. External editing without _LSP_;
2. External editing via _LSP_ connection.

This PR is able to address the first case.

### CODE REVIEW

File: modules/gdscript/gdscript_cache.cpp [hunk 1]
```diff
@@ -185,20 +185,26 @@ Ref<GDScript> GDScriptCache::get_shallow_script(const String &p_path, const Stri
 	return script;
 }
 
-Ref<GDScript> GDScriptCache::get_full_script(const String &p_path, Error &r_error, const String &p_owner) {
+Ref<GDScript> GDScriptCache::get_full_script(const String &p_path, Error &r_error, const String &p_owner, const bool update_cache) {
```
[the remark this answers is not in the document]
Comment (Rindbee) [reply modules/gdscript/gdscript_cache.cpp:188]: p_update_from_disk might give a better indication of what that is.

**Comment by duchainer** [comment]
Fixes https://github.com/godotengine/godot/issues/59115 on my end: https://github.com/godotengine/godot/issues/59115#issuecomment-1221083579

Thanks a lot @Rindbee for the fix ^^

File: modules/gdscript/gdscript_cache.h [hunk 2]
```diff
@@ -88,7 +88,7 @@ class GDScriptCache {
 	static Ref<GDScriptParserRef> get_parser(const String &p_path, GDScriptParserRef::Status status, Error &r_error, const String &p_owner = String());
 	static String get_source_code(const String &p_path);
 	static Ref<GDScript> get_shallow_script(const String &p_path, const String &p_owner = String());
-	static Ref<GDScript> get_full_script(const String &p_path, Error &r_error, const String &p_owner = String());
+	static Ref<GDScript> get_full_script(const String &p_path, Error &r_error, const String &p_owner = String(), const bool p_update_from_disk = false);
```
Comment (akien-mga) [inline modules/gdscript/gdscript_cache.h:91]: We don't use const for bool, int and float parameters.

File: modules/gdscript/gdscript_cache.cpp [hunk 3]
```diff
@@ -183,20 +183,26 @@ Ref<GDScript> GDScriptCache::get_shallow_script(const String &p_path, const Stri
...
 
 	if (!p_owner.is_empty()) {
 		singleton->dependencies[p_owner].insert(p_path);
 	}
 
+	Ref<GDScript> script;
 	r_error = OK;
 	if (singleton->full_gdscript_cache.has(p_path)) {
-		return singleton->full_gdscript_cache[p_path];
+		script = (Ref<GDScript>)(singleton->full_gdscript_cache[p_path]);
```
Comment (akien-mga) [inline modules/gdscript/gdscript_cache.cpp:196]: We normally don't use C style casting for Ref, instead it should be `Ref<T>(...)`.

File: modules/gdscript/gdscript_cache.h (hunk 2 above)
Comment (Rindbee) [reply modules/gdscript/gdscript_cache.h:91]: OK, thanks for pointing it out.

File: modules/gdscript/gdscript_cache.cpp (hunk 3 above)
Comment (Rindbee) [reply modules/gdscript/gdscript_cache.cpp:196]: OK, thanks for pointing it out.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by floriandotorg** [comment]
thank you so much for this 🥳
