### PR TITLE
Use `point_grab_radius` setting in `Polygon2DEditor` bottom panel editor

### LINKED ISSUE #106788: Polygon Editor, Point Grab Radius not working
### Tested versions

- Reproducible in: 
  - v4.4.stable.steam [4c311cbee]
  - v4.1.stable.official [970459615]
  - v4.0.stable.official [92bee43ad]

### System information

Windows 11 (build 26100) - Multi-window, 1 monitor - Vulkan (Forward+) - integrated AMD Radeon(TM) 780M (Advanced Micro Devices, Inc.; 31.0.22024.17002) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 threads)

### Issue description

The setting, `editors/polygon_editor/point_grab_radius`, does not have any effect on the point radius in the Polygon Editor, visual or for the clickable area.

The default value is 16, and changing it to any other value does not change anything (I've tested 1, 10, 80, 100, 200, 1000, and some other values).

### Steps to reproduce

1. Open a Polygon2D node to see current point size
2. Go to `Editor` -> `Editor Settings...`
3. Search for "Point Grab Radius"
4. change the Point Grab Radius setting, and it will have no visible effect on the point size in the Polygon2D node

Additionally, reloading the project, editor, etc. does not change anything.

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/20429044/test.zip)

### PR DESCRIPTION
**Pull request by aaronp64**
Updated `Polygon2DEditor` bottom panel editor to use `point_grab_radius` setting instead of fixed value, similar to grab behavior in main 2D editor panel.  Also updated closest point detection to better handle overlapping grab areas.

Fixes #106788

### CODE REVIEW

File: editor/scene/2d/polygon_2d_editor_plugin.cpp [hunk 1]
```diff
@@ -574,13 +574,16 @@ void Polygon2DEditor::_canvas_input(const Ref<InputEvent> &p_input) {
...
 					int closest = -1;
+					real_t closest_dist = Math::INF;
 
 					for (int i = editing_points.size() - 1; i >= editing_points.size() - internal_vertices; i--) {
 						Vector2 tuv = mtx.xform(previous_polygon[i]);
-						if (tuv.distance_to(mb->get_position()) < 8) {
+						const real_t dist = tuv.distance_to(mb->get_position());
+						if (dist < grab_threshold && dist < closest_dist) {
 							closest = i;
-							break;
```
Comment (KoBeWi) [inline editor/scene/2d/polygon_2d_editor_plugin.cpp:583]: This reverts a fix from #107932

Comment (aaronp64) [reply editor/scene/2d/polygon_2d_editor_plugin.cpp:583]: Interesting, I didn't notice the closest point check was intentionally changed.  To support larger grab radiuses, I think the closest point logic in this PR is needed for cases where the points themselves are not overlapping but the grab areas are.  For when the points are overlapping, should it be easier to select the front point (using `break`), or easier to select the closest to the mouse (this PR's behavior)?  If we want to keep it easier to select the front point for overlaps, I could change this PR to still use the grab area to determine the closest, but break if under 8 (representing the point size).  I think editing the polygon in the 2D editor area chooses the closest point instead of front for overlaps, while the polygon panel editor chooses front on `master`.

Comment (KoBeWi) [reply editor/scene/2d/polygon_2d_editor_plugin.cpp:583]: > For when the points are overlapping, should it be easier to select the front point

This is more intuitive I think, though it's mostly a problem until #107890 is merged.

> I could change this PR to still use the grab area to determine the closest, but break if under 8

That could work.

Comment (aaronp64) [reply editor/scene/2d/polygon_2d_editor_plugin.cpp:583]: I updated the `ACTION_REMOVE_INTERNAL` and `ACTION_ADD_POLYGON` cases to stop once a point is found within 8 pixels of the mouse position, similar to their current behavior on `master`.  I also updated `ACTION_EDIT_POINT` to stop in this case - this is new behavior compared to `master`, but I think it makes sense to keep the three cases consistent.  All three actions should now prioritize the front point when two or more points overlap.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
