### PR TITLE
Fix AnimatedSprite2D & 3D animation list in inspector

### LINKED ISSUE #54637: AnimatedSprite animation is displayed twice.
### Godot version

v4.0.dev.20211027.official [157cba393]

### System information

Windows 10

### Issue description

The animation dropdown list always shows the currently selected animation twice.

### Steps to reproduce

Godot4_nQvhca0M7j <- There are only these 2 animations.
Godot4_Lq2NQ1mKMa
Godot4_3BRLmbDm8N

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by jmb462**
Fixes #54637

### Issue : 

Current animation is shown twice in inspector animation list of AnimatedSprite2D & AnimatedSprite3D.

### Identified cause : 

Current animation isn't correctly detected in the loop which populates the dropdown menu and leads to add it twice to the menu.

### Before : 

image

### After : 

image

### CODE REVIEW

**Comment by KoBeWi** [comment]
Maybe the loop should be changed to range iterator instead? It uses `E->prev()`, but this can be worked around.

File: scene/2d/animated_sprite_2d.cpp [hunk 1]
```diff
@@ -122,7 +122,7 @@ void AnimatedSprite2D::_validate_property(PropertyInfo &property) const {
 			}
 
 			property.hint_string += String(E->get());
-			if (animation == E) {
+			if (animation == String(E->get())) {
```
Comment (akien-mga) [inline scene/2d/animated_sprite_2d.cpp:125]: `animation` is a `StringName`, so it would be better to compare to `E->get()` (also `StringName`) instead of casting to `String`.

File: scene/3d/sprite_3d.cpp [hunk 2]
```diff
@@ -996,7 +996,7 @@ void AnimatedSprite3D::_validate_property(PropertyInfo &property) const {
 			}
 
 			property.hint_string += String(E->get());
-			if (animation == E) {
+			if (animation == String(E->get())) {
```
Comment (akien-mga) [inline scene/3d/sprite_3d.cpp:999]: Same here.

**Comment by jmb462** [comment]
> Maybe the loop should be changed to range iterator instead? It uses `E->prev()`, but this can be worked around.

I'm sure to understand. Do you suggest to get rid of iterator in the loop and use a classical for loop based on index and size of the list ?

**Comment by KoBeWi** [comment]
I mean doing `for (const StringName &E : names)`.

**Review by akien-mga — APPROVED** [review]
Sorry for the delay reviewing.

Looks good, but needs a rebase.

**Comment by akien-mga** [comment]
Thanks!
