### PR TITLE
Android: Handle `YUV_420_888` strides correctly in CameraFeed

### LINKED ISSUE #110711: Android: CameraServer fails with "Expected Image data size" error on YUV_420_888 stream
### Tested versions

Reproducible in:
- Godot Engine v4.5.stable.official.876b29033

I have not tested earlier or later versions. Given the nature of the bug, it appears to be a hardware-specific issue related to the handling of YUV camera streams, which may have been present in other versions as well.

### System information

OS: Android 13   -   Device: Oppo CPH2565   -   GPU: Qualcomm Adreno (TM) 610   -   Godot Version: v4.5.stable.official.876b29033   -   Rendering Backend: OpenGL ES 3.2 (Compatibility)

### Issue description

Activating the `CameraServer` on certain Android devices results in a **black screen** being displayed instead of the camera feed, while the debugger is **continuously spammed** with C++ errors.

This occurs on devices where the camera's only available output format is `YUV_420_888`. The errors (`Expected Image data size... got... bytes instead`) strongly indicate that Godot is not correctly handling memory stride/padding from the camera driver's raw YUV data stream.

The expected behavior is that the camera feed should be displayed correctly without errors.

**Error Log:**
```cpp
E 0:00:06:113   _texture_set_data: Condition "texture->format != p_image->get_format()" is true.
  <C++ Source>  drivers/gles3/storage/texture_storage.cpp:1551 @ _texture_set_data()
E 0:00:06:173   initialize_data: Expected Image data size of 2400x1080x1 (Red8 without mipmaps) = 2592000 bytes, got 2764640 bytes instead.
  <C++ Error>   Method/function failed.
  <C++ Source>  core/io/image.cpp:2227 @ initialize_data()
E 0:00:06:174   initialize_data: Expected Image data size of 1200x540x2 (RedGreen without mipmaps) = 1296000 bytes, got 1382239 bytes instead.
  <C++ Error>   Method/function failed.
  <C++ Source>  core/io/image.cpp:2227 @ initialize_data()
```
**Available Camera Formats (Logged from Device):**
```json
[{ "width": 2400, "height": 1080, "format": "YUV_420_888" }, { "width": 1920, "height": 1080, "format": "YUV_420_888" }, { "width": 1680, "height": 720, "format": "YUV_420_888" }, { "width": 1612, "height": 720, "format": "YUV_420_888" }, { "width": 1600, "height": 900, "format": "YUV_420_888" }, { "width": 1600, "height": 720, "format": "YUV_420_888" }, { "width": 1600, "height": 716, "format": "YUV_420_888" }, { "width": 1520, "height": 720, "format": "YUV_420_888" }, { "width": 1440, "height": 1080, "format": "YUV_420_888" }, { "width": 1280, "height": 960, "format": "YUV_420_888" }, { "width": 1280, "height": 768, "format": "YUV_420_888" }, { "width": 1280, "height": 720, "format": "YUV_420_888" }, { "width": 1080, "height": 1080, "format": "YUV_420_888" }, { "width": 1024, "height": 768, "format": "YUV_420_888" }, { "width": 960, "height": 960, "format": "YUV_420_888" }, { "width": 960, "height": 720, "format": "YUV_420_888" }, { "width": 800, "height": 600, "format": "YUV_420_888" }, { "width": 800, "height": 480, "format": "YUV_420_888" }, { "width": 800, "height": 400, "format": "YUV_420_888" }, { "width": 720, "height": 720, "format": "YUV_420_888" }, { "width": 720, "height": 480, "format": "YUV_420_888" }, { "width": 640, "height": 480, "format": "YUV_420_888" }, { "width": 640, "height": 400, "format": "YUV_420_888" }, { "width": 640, "height": 360, "format": "YUV_420_888" }, { "width": 352, "height": 288, "format": "YUV_420_888" }, { "width": 320, "height": 240, "format": "YUV_420_888" }, { "width": 176, "height": 144, "format": "YUV_420_888" }]
```

### Steps to reproduce

1.  Use the attached Minimal Reproduction Project.
2.  Export and run the project on an affected Android device (details in System Info).
3.  The project will automatically attempt to activate the camera feed.
4.  Observe that the output is a permanent **black screen** instead of the camera feed.
5.  Check the Godot debugger or `logcat` to see the continuous stream of errors.

### Minimal reproduction project (MRP)

- File: [godot-camerafeed-demo-main.zip](https://github.com/user-attachments/files/22437354/godot-camerafeed-demo-main.zip).

- [Link to the project on GitHub.](https://github.com/shiena/godot-camerafeed-demo)

### LINKED ISSUE #114468: Unable to correctly switch CameraFeed on Android apps.
### Tested versions

Reproducible under:
[Play in Editor, or installed build (sans Gradle, obviously)]
Quest: 4.5.1-stable; in either standard apps, or OpenXR environments.

[Both One-touch deploy, or exported & installed build]
Win64: v4.6.beta.custom_build [19527c623] (#110720 , 19527c623a441911a386c1cf170a003dde4d5145)
Win64: v4.6.beta-2
Win64: v4.5.1-stable

Seems to go all the way back to the introduction of CameraServer support for Android (post 4.4).

### System information

Godot v4.6.beta2 - Windows 11 (build 26200) - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 32.0.15.9159) - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 threads) - 63.75 GiB memory

### Issue description

Once an initial CameraFeed has been set active, even if deactivated and then left for a period first, no other feed activates properly.

### Steps to reproduce

Actually spotted in the proposed camera test demo and reproducible there. But how the more *universal* demo approaches Android permissions, strides bug / compatibility, camera formats - and the default behaviour of selecting CameraFeed[0]! - make things a bit murky to see wrt the problem here. Instead, try my 'MRP' attached below.

Either attach an Android device in Debug mode and one-touch deploy, or export and install APK to one.

I've tested the behaviour on:
* Quest 3 - standard 2D app
* Quest 3 - OpenXR - no vendor plugin (with a slight modification to the MRP project, naturally)
* HammerConstruction2-Thermal
* Samsung Galaxy S20+

... working my way down from my intended use case, backwards, to most basic and likely compatible / consumer gear.

```
###################################################################################################
## What we witness here is that - under Android, certainly - once an initial feed has been set active,
## even if deactivated and then left for a period first, no other feed activates properly;
## 
## Attempting to do so:
## 	-	'active' property is set, but frame_changed signal is not detected to emit.
##	-	set_format returns true, but doesn't actually set the format of any subsequent feed.
##
## If reselecting (and activating) the original feed, that one then behaves as normal.
##
## NOTE: Although *hinted* at in the docs, if CameraServer.monitoring == true, new 
##		camera_feeds_updated.connections() seem to silently fail!
##		Could be related behind-the-scenes to our feed-switch problem?
###################################################################################################
```

See, a video demo with narrative here: https://youtu.be/KWirdEIKQb8

### Minimal reproduction project (MRP)

Again, technically, https://github.com/godotengine/godot-demo-projects/pull/1225 is MRP enough.
However, my project is likely simpler and more tailored to demonstrating the... bug?

[stuck_camera_feeds.zip](https://github.com/user-attachments/files/24390996/stuck_camera_feeds.zip)

### PR DESCRIPTION
**Pull request by shiena**
- fixes #110711
- fixes #114468

**Stride-aligned plane handling:**
- Adjust CameraFeed's AIMAGE_FORMAT_YUV_420_888 path to copy Y and UV planes while honoring their row/pixel strides.
- Allocate plane buffers by logical dimensions (not raw byte counts) and branch for packed vs. planar UV layouts.
- Reference the Android YV12 docs (https://developer.android.com/reference/android/graphics/ImageFormat.html#YV12) to explain the stride-aware copy logic and expected fix for padded-stride devices.

**Camera feed synchronization fixes:**
- Make callback structures instance members instead of static to ensure correct `this` pointer is captured for each camera feed instance
- Fix resource leaks for session outputs and camera output target
- Synchronize camera session closure before device close using semaphore to prevent "Device is closed but session is not notified" warning
- Fix image buffer stall when switching camera feeds by acquiring and discarding pending images when feed is not active
- Add atomic flags (`is_deactivating`, `session_close_pending`, `device_error_occurred`) for proper synchronization during deactivation
- Deactivate feeds in `update_feeds()` and `remove_all_feeds()` before removing them to prevent resource leaks

- ~~Improved Android camera preview rotation so that feed transforms stay in sync with both sensor orientation and the current display rotation, ensuring the correct angle (and mirroring) is applied for front and back cameras without redundant updates.~~
- ~~Fix race condition in camera feed deactivation by adding mutex protection and correcting resource cleanup order~~
- ~~Add Android lifecycle management for camera rotation and pause/resume events~~
- ~~Implement horizontal mirroring for front camera to provide mirror-like experience~~
- ~~Add comprehensive safety checks for metadata, formats, and array bounds~~
- ~~Implement metadata refresh mechanism to handle configuration changes~~

<i>Bugsquad edit:</i>
- Fix #110711
- Fix #114468

### CODE REVIEW

**Comment by j20001970** [comment]
After applying the patch, I run into problems that acquiring image from image reader does not succeed.

```
09-20 22:26:49.710  2456  2680 E godot   : ERROR: Condition "status != AMEDIA_OK" is true.
09-20 22:26:49.710  2456  2680 E godot   :    at: onImage (modules/camera/camera_android.cpp:294
```

**Comment by MuslimDev-sys** [comment]
> After applying the patch, I run into problems that acquiring image from image reader does not succeed.
> 
> ```
> 09-20 22:26:49.710  2456  2680 E godot   : ERROR: Condition "status != AMEDIA_OK" is true.
> 09-20 22:26:49.710  2456  2680 E godot   :    at: onImage (modules/camera/camera_android.cpp:294
> ```

_**Same here**_

### **Test Results for the Patch**

Hello! I have tested the [new export templates](https://github.com/godotengine/godot/actions/runs/17885188125), and this is a very positive update.

### Godot version

v4.6.dev.gh-110720 [36d0e1ff9]

#### **1. The Original Bug is FIXED**

Your patch was successful! The original `"Expected Image data size"` errors are **completely gone**. This confirms that your fix for the memory stride/padding issue worked correctly. Thank you!

#### **2. A New, Different Error Has Appeared**

While the original error is fixed, the screen is still black. A new, different error appeared 8 times in the debugger:

```
E 0:00:01:896   onImage: Condition "status != AMEDIA_OK" is true.
  <C++ Source>  modules/camera/camera_android.cpp:294 @ onImage()
```

#### **Analysis**

Based on the C++ source file (`camera_android.cpp:294`), this new error indicates that the `AImageReader_acquireNextImage` function is now failing.

**Summary:**
*   **FIXED:** The app no longer crashes when processing the image data.
*   **NEW BUG:** The app is now failing one step earlier, when it tries to *acquire* the image frame from the Android camera system.

This is fantastic progress, and it proves we are on the right track. Please let me know if you have another patch you would like me to test. Thank you again for your hard work on this @shiena

**Comment by j20001970** [comment]
> After applying the patch, I run into problems that acquiring image from image reader does not succeed.
> 
> ```
> 09-20 22:26:49.710  2456  2680 E godot   : ERROR: Condition "status != AMEDIA_OK" is true.
> 09-20 22:26:49.710  2456  2680 E godot   :    at: onImage (modules/camera/camera_android.cpp:294
> ```

The previous problem seems to be fixed in 355c6ed34da4d44e7338387658447675c32bc203, so it now works as expected, thanks!

File: modules/camera/camera_android.cpp [hunk 1]
```diff
@@ -291,74 +291,170 @@ void CameraFeedAndroid::onImage(void *context, AImageReader *p_reader) {
...
 			memcpy(data_uv.ptrw(), data, len);
 
-			image_y->initialize_data(width, height, false, Image::FORMAT_R8, data_y);
-			image_uv->initialize_data(width / 2, height / 2, false, Image::FORMAT_RG8, data_uv);
+			// Process Y plane - handle stride by creating a packed buffer
+			Vector<uint8_t> packed_y;
+			packed_y.resize(width * height);
+			if (y_row_stride == width) {
+				// No padding, direct copy
+				memcpy(packed_y.ptrw(), data_y.ptr(), width * height);
```
Comment (j20001970) [inline modules/camera/camera_android.cpp]: We are copying the same data twice here, is there any chances that this can be improved?

**Comment by shiena** [comment]
@j20001970 
Thank you for the review. After investigating the cause, I found that memory alignment considerations are necessary as explained in https://developer.android.com/reference/android/graphics/ImageFormat.html#YV12 , so I've recreated the diff.

**Comment by shiena** [comment]
@MuslimDev-sys 
Thank you for testing the functionality. I fixed it using a different approach, so could you please test it again?
~https://github.com/godotengine/godot/actions/runs/17892068593~
https://github.com/godotengine/godot/actions/runs/17898213735

**Comment by j20001970** [comment]
I do not have Android devices that provide full planar YUV format to test, but 41367697b69659f403eb606fe051370fbd5aa402 works well for the case of interleaved UV plane.

**Review by j20001970 — APPROVED** [review]

**Comment by MuslimDev-sys** [comment]
### **Test Results for the Final Patch: Success!**

Hello @shiena,

I have tested the new build with [your different approach](https://github.com/godotengine/godot/actions/runs/17898213735), and it is a **complete success.**

### Godot version

`v4.6.dev.gh-110720 [533e77659]`

### 1. The Main Bug is FIXED

Your patch was successful! The camera feed is now **working** and visible on my device. The black screen is gone, and all the previous C++ errors (`Expected Image data size` and `AImageReader_acquireNextImage`) have been resolved. Thank you!

### 2. Next Steps and Final Observations

Now that the main issue is solved, I can interact with the feed and have observed two new behaviors. **I am not sure if these are new engine bugs or issues with [your GDScript logic](https://github.com/shiena/godot-camerafeed-demo), so I am reporting them here for your review.**

*   **Rotation:** The camera preview is now visible, but it appears to be rotated by -90 degrees.

*   **Error When Switching Cameras:** When I try to switch to the front camera or select a different resolution, the switch does not happen, and the following error is logged once:
    ```
    E 0:00:37:884   set_format: Feed is active.
      <C++ Error>   Condition "active" is true. Returning: false
      <C++ Source>  modules/camera/camera_android.cpp:260 @ set_format()
    ```

### Summary

The fix for the critical blocking bug is **complete and successful.** You have solved the core engine issue, and the camera is now functional on my device.

Thank you again for all your hard work and persistence on this! @shiena

**Comment by shiena** [comment]
@MuslimDev-sys 
Thank you for testing the functionality.
Both the rotation and camera switching errors are suspected to be bugs in [godot-camera-demo](https://github.com/shiena/godot-camerafeed-demo). So let's check with https://github.com/shiena/godot-camerafeed-demo/issues/3 .

File: modules/camera/camera_android.h [hunk 2]
```diff
@@ -30,6 +30,9 @@
 
 #pragma once
 
+#include <cstddef>
+
+#include "core/os/mutex.h"
```
Comment (AThousandShips) [inline modules/camera/camera_android.h]:
```suggestion
```

**Comment by shiena** [comment]
- Why Lifecycle Management?
  Android invalidates camera resources when the app is paused or the device rotates. These methods properly handle these events by deactivating/reactivating camera sessions and refreshing metadata to maintain correct functionality.

- Race Condition Details
  Previously, if deactivate_feed() was called while onImage() callback was executing, it could access freed resources. The callback_mutex ensures thread-safe cleanup, and the corrected order (device → reader → request) prevents use-after-free errors.

- Front Camera Mirror Effect
  Users expect front cameras to behave like mirrors. We apply horizontal flip via Transform2D scaling (-1.0, 1.0) before rotation, matching standard camera app behavior.

- Metadata Refresh Mechanism
  During configuration changes (rotation), Android camera metadata (sensor orientation, formats) may become invalid. refresh_camera_metadata() re-fetches this data from the camera manager, ensuring the camera state stays synchronized with the system.

- Safety Philosophy
  Multiple defensive checks prevent crashes in unexpected states: null metadata, invalid format indices, zero dimensions, and inactive feeds. When problems are detected, the code attempts recovery (metadata refresh) or gracefully skips processing rather than crashing.

File: modules/camera/camera_android.cpp [hunk 3]
```diff
@@ -93,23 +95,89 @@ CameraFeedAndroid::~CameraFeedAndroid() {
...
+		ERR_PRINT(vformat("Camera %s: Failed to refresh metadata (status: %d)", camera_id, status));
+		return;
+	}
+
+	// Re-fetch sensor orientation
+	ACameraMetadata_const_entry orientation_entry;
+	status = ACameraMetadata_getConstEntry(metadata, ACAMERA_SENSOR_ORIENTATION, &orientation_entry);
+	if (status == ACAMERA_OK) {
+		orientation = orientation_entry.data.i32[0];
+		print_verbose(vformat("Camera %s: Orientation updated to %d", camera_id, orientation));
```
Comment (AThousandShips) [inline modules/camera/camera_android.cpp]:
```suggestion
		print_verbose(vformat("Camera %s: Orientation updated to %d.", camera_id, orientation));
```

File: modules/camera/camera_android.cpp [hunk 4]
```diff
@@ -93,23 +95,89 @@ CameraFeedAndroid::~CameraFeedAndroid() {
...
+	} else {
+		ERR_PRINT(vformat("Camera %s: Failed to get sensor orientation after refresh (status: %d)", camera_id, status));
+	}
+
+	// Re-fetch available formats
+	formats.clear();
+	_add_formats();
+
+	print_verbose(vformat("Camera %s: Metadata refreshed successfully", camera_id));
```
Comment (AThousandShips) [inline modules/camera/camera_android.cpp]:
```suggestion
	print_verbose(vformat("Camera %s: Metadata refreshed successfully.", camera_id));
```

File: modules/camera/camera_android.cpp [hunk 5]
```diff
@@ -93,23 +95,89 @@ CameraFeedAndroid::~CameraFeedAndroid() {
...
-			display_rotation = 270;
-			break;
-		case 270:
-			display_rotation = 90;
-			break;
-		default:
-			break;
+	// Safety check: ensure metadata is valid
+	if (!metadata) {
+		print_verbose(vformat("Camera %s: metadata is null in _set_rotation, attempting refresh", camera_id));
```
Comment (AThousandShips) [inline modules/camera/camera_android.cpp]:
```suggestion
		print_verbose(vformat("Camera %s: metadata is null in _set_rotation, attempting refresh.", camera_id));
```

File: modules/camera/camera_android.cpp [hunk 6]
```diff
@@ -363,8 +547,22 @@ void CameraFeedAndroid::onImage(void *context, AImageReader *p_reader) {
...
+	// Rotation - only update if formats are still valid
+	// During screen rotation, metadata may become invalid and formats may be empty
+	if (!feed->formats.is_empty()) {
+		// Check if metadata is still valid before setting rotation
+		if (feed->metadata != nullptr) {
+			feed->_set_rotation();
+		} else {
+			// Metadata has been invalidated (possibly due to configuration change)
+			// Attempt to refresh it
+			print_verbose(vformat("Camera %s: metadata invalidated in onImage, attempting refresh", feed->camera_id));
```
Comment (AThousandShips) [inline modules/camera/camera_android.cpp]:
```suggestion
			print_verbose(vformat("Camera %s: metadata invalidated in onImage, attempting refresh.", feed->camera_id));
```

File: modules/camera/camera_android.cpp [hunk 7]
```diff
@@ -505,6 +711,131 @@ void CameraAndroid::set_monitoring_feeds(bool p_monitoring_feeds) {
 	}
 }
 
+void CameraFeedAndroid::handle_pause() {
+	if (is_active()) {
+		was_active_before_pause = true;
+		print_verbose(vformat("Camera %s: Pausing (was active)", camera_id));
```
Comment (AThousandShips) [inline modules/camera/camera_android.cpp]:
```suggestion
		print_verbose(vformat("Camera %s: Pausing (was active).", camera_id));
```

File: modules/camera/camera_android.cpp [hunk 8]
```diff
@@ -143,6 +211,12 @@ void CameraFeedAndroid::_add_formats() {
 
 bool CameraFeedAndroid::activate_feed() {
 	ERR_FAIL_COND_V_MSG(selected_format == -1, false, "CameraFeed format needs to be set before activating.");
+
+	// Safety checks: ensure formats array is valid
+	ERR_FAIL_COND_V_MSG(formats.is_empty(), false, "No camera formats available.");
+	ERR_FAIL_INDEX_V_MSG(selected_format, formats.size(), false,
+			vformat("Selected format index %d is out of bounds (formats size: %d)", selected_format, formats.size()));
```
Comment (AThousandShips) [inline modules/camera/camera_android.cpp]:
```suggestion
			vformat("Selected format index %d is out of bounds (formats size: %d).", selected_format, formats.size()));
```

**Comment by shiena** [comment]
Regarding Android lifecycle events, currently we can control the CameraAndroid and CameraFeedAndroid classes from gdscript. However, there's also an option to call from Godot.kt and have it work transparently. Which approach would be better?

**Comment by shiena** [comment]
Ahhh, the methods exposed in CameraAndroid and CameraFeedAndroid were not visible from GDScript. Therefore, we control Android lifecycle events from Godot.kt. This approach has the advantage that app developers don't need to implement it themselves, and it prevents unauthorized recording by stopping the camera in the background.

File: platform/android/java/lib/src/org/godotengine/godot/Godot.kt [hunk 9]
```diff
@@ -757,6 +761,8 @@ class Godot private constructor(val context: Context) {
 			darkMode = newDarkMode
 			GodotLib.onNightModeChanged()
 		}
+
+		GodotLib.onCameraRotationChange()
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/Godot.kt]: Configuration change callback does not necessarily mean that there was a screen orientation change, so you should check specifically for it before calling `onCameraRotationChange()`.

Also make the call generic by renaming it to `GodotLib.onScreenRotationChange`, and move the camera specific logic to the native version.

File: modules/camera/camera_android.cpp [hunk 10]
```diff
@@ -93,23 +95,85 @@ CameraFeedAndroid::~CameraFeedAndroid() {
...
-			break;
-		default:
-			break;
+	// Safety check: ensure metadata is valid
+	if (!metadata) {
+		print_verbose(vformat("Camera %s: metadata is null in _set_rotation, attempting refresh", camera_id));
+		refresh_camera_metadata();
+		if (!metadata) {
+			ERR_PRINT(vformat("Camera %s: Cannot update rotation, metadata unavailable after refresh", camera_id));
+			return;
```
Comment (m4gr3d) [inline modules/camera/camera_android.cpp]: Should we use the fallback here instead?

File: modules/camera/camera_android.cpp [hunk 11]
```diff
@@ -143,6 +207,12 @@ void CameraFeedAndroid::_add_formats() {
 
 bool CameraFeedAndroid::activate_feed() {
 	ERR_FAIL_COND_V_MSG(selected_format == -1, false, "CameraFeed format needs to be set before activating.");
```
Comment (m4gr3d) [inline modules/camera/camera_android.cpp]: This can be collapsed into the `ERR_FAIL_INDEX_V_MSG` check below.

File: modules/camera/camera_android.cpp [hunk 12]
```diff
@@ -278,11 +348,45 @@ Array CameraFeedAndroid::get_formats() const {
 
 CameraFeed::FeedFormat CameraFeedAndroid::get_format() const {
 	CameraFeed::FeedFormat feed_format = {};
-	return selected_format == -1 ? feed_format : formats[selected_format];
+	// Safety check: ensure selected_format is valid
+	if (selected_format < 0 || selected_format >= formats.size()) {
+		ERR_PRINT(vformat("Invalid format index: %d (formats size: %d)", selected_format, formats.size()));
+		return feed_format;
+	}
```
Comment (m4gr3d) [inline modules/camera/camera_android.cpp]: You can use `ERR_FAIL_INDEX_V_MSG` instead.

File: platform/android/java/lib/src/org/godotengine/godot/GodotLib.java [hunk 13]
```diff
@@ -295,6 +295,22 @@ public static void calldeferred(long p_id, String p_method, Object[] p_params) {
...
 
+	/**
+	 * Invoked when the app is paused to release camera resources.
+	 */
+	public static native void onCameraPause();
+
+	/**
+	 * Invoked when the app is resumed to restore camera resources.
+	 */
+	public static native void onCameraResume();
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/GodotLib.java]: Instead of adding new methods, use `onRendererResumed()` and `onRendererPaused()` instead to notify the camera logic that it should resume / pause.

File: platform/android/java_godot_lib_jni.cpp [hunk 14]
```diff
@@ -608,6 +613,54 @@ JNIEXPORT void JNICALL Java_org_godotengine_godot_GodotLib_onRendererPaused(JNIE
...
+#ifdef CAMERA_ENABLED
+	if (step.get() <= STEP_SETUP) {
+		return;
+	}
+
+	CameraServer *camera_server = CameraServer::get_singleton();
+	if (camera_server) {
+		CameraAndroid *camera_android = Object::cast_to<CameraAndroid>(camera_server);
+		if (camera_android) {
+			camera_android->handle_rotation_change();
```
Comment (m4gr3d) [inline platform/android/java_godot_lib_jni.cpp]: Which thread does this need to be invoked on?

**Review by m4gr3d — CHANGES_REQUESTED** [review]
> * Why Lifecycle Management?
>   Android invalidates camera resources when the app is paused or the device rotates. These methods properly handle these events by deactivating/reactivating camera sessions and refreshing metadata to maintain correct functionality.
> * Race Condition Details
>   Previously, if deactivate_feed() was called while onImage() callback was executing, it could access freed resources. The callback_mutex ensures thread-safe cleanup, and the corrected order (device → reader → request) prevents use-after-free errors.
> * Front Camera Mirror Effect
>   Users expect front cameras to behave like mirrors. We apply horizontal flip via Transform2D scaling (-1.0, 1.0) before rotation, matching standard camera app behavior.
> * Metadata Refresh Mechanism
>   During configuration changes (rotation), Android camera metadata (sensor orientation, formats) may become invalid. refresh_camera_metadata() re-fetches this data from the camera manager, ensuring the camera state stays synchronized with the system.
> * Safety Philosophy
>   Multiple defensive checks prevent crashes in unexpected states: null metadata, invalid format indices, zero dimensions, and inactive feeds. When problems are detected, the code attempts recovery (metadata refresh) or gracefully skips processing rather than crashing.

This will need to be split into multiple PRs:
- One PR for the YUV_420_888 strides fix
- Another PR for the rotation bug
- Another PR for the front camera mirror effect

File: modules/camera/camera_android.cpp [hunk 15]
```diff
@@ -505,6 +707,119 @@ void CameraAndroid::set_monitoring_feeds(bool p_monitoring_feeds) {
...
+
+RotationResult CameraFeedAndroid::calculate_rotation(const CameraRotationParams &params) {
+	RotationResult result = { 0, false, false };
+
+	if (params.sensorOrientation < 0 || params.sensorOrientation > 270 ||
+			params.sensorOrientation % 90 != 0) {
+		return result;
+	}
+
+	int rotationAngle = params.sensorOrientation - params.displayRotation;
```
Comment (AThousandShips) [inline modules/camera/camera_android.cpp]:
```suggestion
	int rotation_angle = params.sensorOrientation - params.displayRotation;
```

**Comment by shiena** [comment]
I've implemented the review feedback.

> This will need to be split into multiple PRs:
> 
> One PR for the YUV_420_888 strides fix
> Another PR for the rotation bug
> Another PR for the front camera mirror effect

OK. For the front camera mirroring, since the app can determine this functionality, we plan to remove it from the camera module.

File: modules/camera/camera_android.cpp [hunk 16]
```diff
@@ -142,7 +223,11 @@ void CameraFeedAndroid::_add_formats() {
 }
 
 bool CameraFeedAndroid::activate_feed() {
-	ERR_FAIL_COND_V_MSG(selected_format == -1, false, "CameraFeed format needs to be set before activating.");
+	// Safety checks: ensure formats array is valid
+	ERR_FAIL_COND_V_MSG(formats.is_empty(), false, "No camera formats available.");
+	ERR_FAIL_INDEX_V_MSG(selected_format, formats.size(), false,
+			vformat("CameraFeed format needs to be set before activating. Selected format index: %d (formats size: %d)", selected_format, formats.size()));
```
Comment (AThousandShips) [inline modules/camera/camera_android.cpp]:
```suggestion
			vformat("CameraFeed format needs to be set before activating. Selected format index: %d (formats size: %d).", selected_format, formats.size()));
```

File: modules/camera/camera_android.cpp [hunk 17]
```diff
@@ -278,11 +363,42 @@ Array CameraFeedAndroid::get_formats() const {
 
 CameraFeed::FeedFormat CameraFeedAndroid::get_format() const {
 	CameraFeed::FeedFormat feed_format = {};
-	return selected_format == -1 ? feed_format : formats[selected_format];
+	ERR_FAIL_INDEX_V_MSG(selected_format, formats.size(), feed_format,
+			vformat("Invalid format index: %d (formats size: %d)", selected_format, formats.size()));
```
Comment (AThousandShips) [inline modules/camera/camera_android.cpp]:
```suggestion
			vformat("Invalid format index: %d (formats size: %d).", selected_format, formats.size()));
```

File: platform/android/java_godot_lib_jni.cpp [hunk 18]
```diff
@@ -596,18 +601,57 @@ JNIEXPORT void JNICALL Java_org_godotengine_godot_GodotLib_onRendererResumed(JNI
...
 	}
+
+#ifdef CAMERA_ENABLED
+	// Resume camera feeds that were active before pause
+	CameraServer *camera_server = CameraServer::get_singleton();
+	if (camera_server) {
+		CameraAndroid *camera_android = Object::cast_to<CameraAndroid>(camera_server);
+		if (camera_android) {
+			camera_android->handle_resume();
+		}
```
Comment (AThousandShips) [inline platform/android/java_godot_lib_jni.cpp]:
```suggestion
	CameraAndroid *camera_android = Object::cast_to<CameraAndroid>(CameraServer::get_singleton());
	if (camera_android) {
		camera_android->handle_resume();
```
For all three

File: modules/camera/camera_android.cpp [hunk 19]
```diff
@@ -93,23 +95,102 @@ CameraFeedAndroid::~CameraFeedAndroid() {
...
+		params.sensorOrientation = orientation;
+		params.cameraFacing = (position == CameraFeed::FEED_FRONT) ? CameraFacing::FRONT : CameraFacing::BACK;
+		params.displayRotation = get_app_orientation();
+
+		RotationResult result = calculate_rotation(params);
+
+		if (result.isValid) {
+			imageRotation = static_cast<float>(result.rotationAngle);
+		} else {
+			// Fallback if calculation fails
```
Comment (AThousandShips) [inline modules/camera/camera_android.cpp]:
```suggestion
			// Fall back if calculation fails.
```

**Comment by shiena** [comment]
@m4gr3d 
We have split the PR as follows:
#110720: the YUV_420_888 strides fix
#111871: the rotation bug

File: modules/camera/camera_android.h [hunk 20]
```diff
@@ -30,6 +30,8 @@
 
 #pragma once
 
+#include <cstddef>
```
Comment (m4gr3d) [inline modules/camera/camera_android.h]: Is the include needed?

Comment (shiena) [reply modules/camera/camera_android.h]: Removed unnecessary header.

**Comment by m4gr3d** [comment]
@Alex2782 @syntaxerror247 Can you help with reviewing this bug fix.

**Comment by Alex2782** [comment]
Maybe next week, I'll first try to reproduce issue #110711 on regular smartphones; I'm less familiar with XR. (no Android XR devices)

**Comment by m4gr3d** [comment]
> Maybe next week, I'll first try to reproduce issue #110711 on regular smartphones; 

Thanks!

> I'm less familiar with XR. (no Android XR devices)

The issue is not XR specific; it's just that `CameraFeed` related logic falls under the `XR` topic for some reasons.

**Comment by shiena** [comment]
Stride alignment is device-dependent, so some cameras work without this fix. 
However, the Oppo CPH2565 reported in the issue displays corrupted images 
without proper stride handling.

**Review by Alex2782 — COMMENTED** [review]
Tested on these two devices, first with `v4.5.1-stable`:
- Pixel 4a, Qualcomm - Adreno (TM) 618
- Samsung Tab S 7, Qualcomm - Adreno (TM) 650

Reproducible on both devices (black screen), Pixel 4a also crashed after 2 to 3 seconds.

---------------

**This PR:**
- On my `Samsung Tab S7` I see the "CameraFeed", but as soon as I press "Reload" or select a different camera (Back / Front), it stops working and the screen remains black.

- On my `Pixel 4a`, I see the "CameraFeed" for 2 to 3 seconds, then the app keeps crashing. Should I debug this with Android Studio?

**Comment by Alex2782** [comment]
> Stride alignment is device-dependent, so some cameras work without this fix.
> However, the Oppo CPH2565 reported in the issue displays corrupted images
> without proper stride handling.

Not reproducible on my `Pixel 8a, ARM - Mali-G715` (this bug fix doesn't seem to be necessary there either)

From issue report `OS: Android 13 - Device: Oppo CPH2565 - GPU: Qualcomm Adreno (TM) 610` 
Seems to be another GPU-specific issue, **Adreno 6xx**.

**Comment by shiena** [comment]
@Alex2782 
Thanks for testing and the detailed report!

I've pushed a fix that addresses the crash issue. The changes include:

- **Fix AImage memory leak**: Added missing `AImage_delete()` calls on early returns in the `onImage` callback. This was likely causing the crash after 2-3 seconds on Pixel 4a due to memory exhaustion.
- **Add stride validation**: Added guard for `stride <= width` in `compact_stride_inplace` to handle edge cases.
- **Add buffer bounds checking**: Validate buffer size before stride compaction to prevent out-of-bounds memory access.

**Comment by shiena** [comment]
@Alex2782 @The-Cyber-Captain
I believe this should be fixed in 31351ba49a0d95886823c36a1696fca6b4e821a7.

**Comment by The-Cyber-Captain** [comment]
Sadly, building https://github.com/godotengine/godot/commit/31351ba49a0d95886823c36a1696fca6b4e821a7 and running my simplified test scene / MRP from https://github.com/godotengine/godot/issues/114468 I'm still unable to switch CameraFeed under Android. 😿

**Comment by The-Cyber-Captain** [comment]
> @The-Cyber-Captain Could you grab the logcat (filtered by package name) while reproducing the issue?

Ahhhhh. I'm more a User than a Dev. 🤣 Filtering logcats is about the edge of my skillset / setup. But I gave it a shot and updated the issue with them. Only to see you have a new fix; you absolute machine! 👍 

I'll give that new build a test as soon as able, and report back.
PS: related to this
oKEgewjFoA
at all? I have high hopes for the new commit.

Like I say, will test it out and feed back how it goes. Thanks.

**Review by Alex2782 — APPROVED** [review]
It looks great on both of my devices now!

I can't say much about the code (I'm not very familiar with it)

Except that you should avoid `auto`. 
https://contributing.godotengine.org/en/latest/engine/guidelines/cpp_usage_guidelines.html#auto-keyword

However, a line of code containing `auto` was already accepted 8 months ago. (`CameraFeedAndroid::onDisconnected`)

**Comment by shiena** [comment]
Thank you for the review. Fixed by replacing `auto *` with explicit type `CameraFeedAndroid *` in both `onError()` and `onDisconnected()` callbacks.

**Review by m4gr3d — APPROVED** [review]
The code looks good. Can you squash the commits.

File: modules/camera/camera_android.h [hunk 21]
```diff
@@ -61,23 +63,40 @@ class CameraFeedAndroid : public CameraFeed {
...
 	ACameraCaptureSession *session = nullptr;
 	ACaptureRequest *request = nullptr;
+	ACaptureSessionOutput *session_output = nullptr;
+	ACaptureSessionOutputContainer *session_output_container = nullptr;
+	ACameraOutputTarget *camera_output_target = nullptr;
 	Mutex callback_mutex;
+	Semaphore session_closed_semaphore;
+	std::atomic<bool> is_deactivating{ false };
+	std::atomic<bool> session_close_pending{ false };
+	std::atomic<bool> device_error_occurred{ false };
```
Comment (akien-mga) [inline modules/camera/camera_android.h]: We have our own SafeFlag wrapper for `std::atomic` that should probably be used here.

Comment (shiena) [reply modules/camera/camera_android.h]: Fixed. Replaced `std::atomic<bool>` with Godot's `SafeFlag` wrapper.

**Comment by shiena** [comment]
@syntaxerror247 
Regarding the zoom appearing too zoomed in: The MRP displays the camera to fill the entire screen, cropping any overflow. Switching to a format with a different aspect ratio should change how it appears.

**Comment by syntaxerror247** [comment]
@shiena I think I've figured out the issue and it is related to rotation. The camera feed isn't rotating with the device orientation. When I set the device to landscape, everything looks correct. However, when I switch to portrait mode, the camera feed doesn't rotate. So the issue seems to be caused by rotation handling somewhere.

**Comment by shiena** [comment]
@syntaxerror247 
I've recently improved the rotation handling. Please give it a try.
https://github.com/shiena/godot-camerafeed-demo

**Review by syntaxerror247 — APPROVED** [review]
