### PR TITLE
Fix `modified_time` on Android

### LINKED ISSUE #101007: Android export from android will not update main scene layout unless .godot/exported/... is deleted
### Tested versions

- Reproducible on:
    - Godot v4.4-dev7 - Android -> Android
    - Godot master 0c45ace151f25de2ca54fe7a46b6f077be32ba6f - Android -> Android
    - Godot master 2582793d408ade0b6ed42f913ae33e7da5fb9184 - Android -> Android
-  Not Reproducible on:
    - Godot 4.4-dev7 - Linux -> Android
    - Godot 4.3-stable - Linux -> Android
    - Godot master 2582793d408ade0b6ed42f913ae33e7da5fb9184 - Linux -> Android
    - Godot 4.3-stable - Linux -> Linux
    - Godot 4.4-dev7 - Linux -> Linux
    - Godot 4.3-stable - Android -> Android (not implemented yet: https://github.com/godotengine/godot/commit/a5897d579bb0af496a18f7430345a67fe27ff0df)

### System information

Godot v4.4.dev7 - Android - Single-window, 1 monitor - Vulkan (Mobile) - integrated Mali-G715 -  (9 threads)
(Google Pixel 8)

### Issue description

It looks like the scene is cached in `.godot/exported/<id>/file_cache` on the first export, which is not updated in subsequent exports....

~~It appears that the desktop editor does not create `.godot/exported/<id>/file_cache` when exporting!?~~

### Steps to reproduce

Create a simple app on the editor in android. Export the app and install (all on the same device 😙🤌) then adjust the main scene layout to something different.. and re-export.

In the MRP you can hide/show the TextRect named `HideMeThenReExport`

It seems like the scripts get updated but the scene contents don't change on the exported app.

Delete `.godot/exported/<id>/file_cache` and then re-export and the scene updates to the new layout.

### Minimal reproduction project (MRP)
[repro-godotatoaexportedcache2.zip](https://github.com/user-attachments/files/18286768/repro-godotatoaexportedcache2.zip)

---
**Bugsquad Edit:** Adding info from #99023

When I export an APK file, it always exports the first exported version.When I delete a folder called exported in the file manager, I can export the new version of the file again. It's just me. My friend is totally fine.And it seems that only the scene files and resource files will not be updated, the script will be updated. Not only did I save it several times, but I even deleted GODOT and tried again, with the same result.

### PR DESCRIPTION
**Pull request by Alex2782**
Fixes: #101007 (Workaround)

**Issue Description:**
After saving, all timestamps (`st_mtime, st_ctime, st_atime`) are set to the same value.
After exporting or after some time, only `modified_time` resets to a past timestamp.

Cache files are created during export and rely on `modified_time`.

**Workaround:**
Use `created_time` if `modified_time` is in the past.

-------

https://github.com/godotengine/godot/issues/101007#issuecomment-2670335154
I initially suspected `thirdparty/minizip/unzip.c` because the timestamps were only reset after `unz*` functions. However, this behavior also occurs when no export is performed, once even when the Godot Editor was not running (terminated).

<details><summary>Test</summary>

--------

https://github.com/user-attachments/assets/b534990a-7fe0-4232-a164-e1eb2ed15dc3

</details>

<details><summary>timestamp check after export</summary>

---------

After saving the time was still 16:xx and after export it was reset to 15:xx.

timestamp_bug
</details>

### CODE REVIEW

**Comment by Alex2782** [comment]
@syntaxerror247 Does this workaround also work on your device?


--------
Notice:

My first pull request wasn't accepted, there were these check warnings for Android. All other operating systems were not affected.

```sh
Error: drivers/unix/file_access_unix.cpp:348:21: error: 
comparison of integers of different signs: 'uint64_t' (aka 'unsigned long') and 
'__kernel_old_time_t' (aka 'long') [-Werror,-Wsign-compare]
                if (modified_time < status.st_ctime) {
                    ~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~
1 error generated.
scons: *** [drivers/unix/file_access_unix.android.editor.arm64.o] Error 1
```

**Review by syntaxerror247 — APPROVED** [review]
Works as expected.

**Review by m4gr3d — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

File: drivers/unix/file_access_unix.cpp [hunk 1]
```diff
@@ -340,7 +340,17 @@ uint64_t FileAccessUnix::_get_modified_time(const String &p_file) {
 	int err = stat(file.utf8().get_data(), &status);
 
 	if (!err) {
-		return status.st_mtime;
+		uint64_t modified_time = status.st_mtime;
+#ifdef ANDROID_ENABLED
+		// Workaround for GH-101007
+		//FIXME: After saving, all timestamps (st_mtime, st_ctime, st_atime) are set to the same value.
+		// After exporting or after some time, only 'modified_time' resets to a past timestamp.
+		uint64_t created_time = status.st_ctime;
```
Comment (Alex2782) [inline drivers/unix/file_access_unix.cpp:348]: `st_ctime` is not `created_time`.

The effects need to be examined in more detail, a few days ago I noticed that this timestamp was updated outside of Godot.

```bash
alex@localhost godot-github % adb shell "stat sdcard/Documents/starter-kit-city-builder"
  File: sdcard/Documents/starter-kit-city-builder
  Size: 3488	 Blocks: 7	 IO Blocks: 512	 directory
Device: 62h/98d	 Inode: 547529	 Links: 11	 Device type: 0,0
Access: (0770/drwxrwx---)	Uid: (    0/    root)	Gid: ( 9997/everybody)
Access: 2024-07-21 13:06:31.602339129 +0200
Modify: 2024-07-21 13:06:48.914339123 +0200
Change: 2024-07-21 13:06:48.914339123 +0200
```

Comment (syntaxerror247) [reply drivers/unix/file_access_unix.cpp:348]: `st_ctime` updated when files metadata updates. So, if its metadata is updated due to any reason `st_ctime` would update. I thinks, it's not a problem for us as this would just create a new file_cache.
