### PR TITLE
Fix editors potentially being used twice

### LINKED ISSUE #72133: Drawing a Polygon or Curve results in duplicate vertices
### Godot version

v4.0.beta15.official [4fa6edc88]

### System information

Windows 11

### Issue description

When drawing a polygon in the editor, several duplicate vertices are added to the polygon array for each click.  In the image below, I clicked three times to draw the triangle, but got 10 entries.  The number you get varies, though I don't know why; I've seen hundreds of points from drawing a hexagon.  I tested it with a Polygon2D, a CollisionPolygon2D, and a CollisionPolygon3D; the issues occurs with all of them.  It later occurred to me that this might happen with a Curve2D as well, and it does.

image

### Steps to reproduce

Add a node that has a Polygon or Curve resource, such as a Polygon2D, draw some points, then check the PackedVector2Array resource.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #72133

When an object was edited twice in a row for whatever reason, it could end up being assigned twice to an editor.

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -2096,14 +2096,25 @@ void EditorNode::edit_item(Object *p_object, Object *p_editing_owner) {
...
 			if (!item_plugins.has(plugin)) {
+				// Remove plugins no longer used by this editing owner.
+				to_remove.push_back(plugin);
 				plugin->make_visible(false);
 				plugin->edit(nullptr);
 			}
 		}
 
+		for (EditorPlugin *plugin : to_remove) {
+			active_plugins[owner_id].erase(plugin);
```
Comment (KoBeWi) [inline editor/editor_node.cpp:2110]: Not related to this fix, but it probably fixes something too.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
