### PR TITLE
display of large help text in visual script

### LINKED ISSUE #58121: Godot 4: Visual Script node search window opens as a non-window popup (DisplayServer regression) when adding a very long description node into the canvas
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

Visual Script node search window (RMB on the canvas) opens as a non-window popup and can't be resized when adding a very long description node into the canvas. I have to restart the engine to fix this issue.

The popup window's corners don't appear to be rounded indicating it's not open as a window. All opened windows in Windows 11 should have round corners. This issue is shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/153957564-418d5994-518e-4982-8fb8-6bfa79c528b2.mp4

This is how the window appears when it works correctly:

Screenshot 2022-02-14 192203

I expect the node search window to open as a window all of the time so I don't have to restart the engine.

Note: See [this comment](https://github.com/godotengine/godot/issues/58121#issuecomment-1066004459) for more info.

### Steps to reproduce

1. Right mouse click at the Visual Script canvas to search for nodes. 
2. Add the `connect()` node.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by derammo**
implemented vertical scroller for help text in popup
disabled broken positioning code
fixes #58121

~~Note to reviewers: I disabled some positioning code that does not work at all.  I don't know what requirements this was supposed to address, so I could not implement it.   The disabled code was pushing large windows off the screen due to incorrect calculations and was doing very bad things in multi monitor setups where screen coordinates are very different from global coordinates.~~

[edit: Akien correctly points out these calculations may have been correct in 3.x, so I could be wrong here.]
[edit: After discussion, the disabled code is being removed entirely, since it isn't required in either mode.]

### CODE REVIEW

**Comment by derammo** [comment]
Note to reviewer:  This is my first UI change contribution.  Please feel free to aggressively :) check if I did anything stupid in the layout constraints or similar.  Thanks.

**Comment by fire** [comment]
Typically for ui contributors we suggest that contribution add visuals so that others that aren't technical can also contribute.

Also, most of the ui contributions are quite cool to look at!

**Comment by derammo** [comment]
> Typically for ui contributors we suggest that contribution add visuals so that others that aren't technical can also contribute.
> 
> Also, most of the ui contributions are quite cool to look at!

I will definitely do that if I actually design some UI, instead of just adding some scroll bars and fixing bugs. :)
Thanks for the info though, will keep that in mind for the future!

**Comment by derammo** [comment]
I will just claim this fixes #60296 also.  It certainly seems the same issue.

File: modules/visual_script/editor/visual_script_editor.cpp [hunk 1]
```diff
@@ -1960,6 +1960,9 @@ void VisualScriptEditor::_generic_search(Vector2 pos, bool node_centered) {
 
 	new_connect_node_select->select_from_visual_script(script, false); // do not reset text
 
+#if 0
```
Comment (fire) [inline modules/visual_script/editor/visual_script_editor.cpp:1963]: Typically we delete code instead of defining them out.

Will need to check the visuals next after reviewing the code on the website.

Comment (derammo) [reply modules/visual_script/editor/visual_script_editor.cpp:1963]: My intent was for the code owner to decide what to do about this code.  

I could not leave it, because it causes the popup to get pushed off screen.   However, I also could not fix it, because it isn't clear what it is trying to do.   There is a comment that it is trying to put the popup within the bounds of the graph.

I can't figure out why this would have been a requirement?   Surely if the main window is currently small on the screen, you don't want the popup to try to fit inside it?  It is a floating window.

I also could not determine intent from the code itself, because its calculation is so wrong.

I put the FIXME according to https://docs.godotengine.org/en/stable/community/contributing/code_style_guidelines.html#comment-style-guide but I couldn't leave the code enabled, because it messes up popup handling entirely.

I was hoping the code owner would know what the requirements/intent of this was and figure out what to do.   Is there some requirement that should be implemented here?   I didn't find anything in the guide about what to do in this scenario.

Comment (derammo) [reply modules/visual_script/editor/visual_script_editor.cpp:1963]: So much for the background info. :)  I am of course happy to delete the code if you determine that is the right thing.

Comment (akien-mga) [reply modules/visual_script/editor/visual_script_editor.cpp:1963]: > I could not leave it, because it causes the popup to get pushed off screen. However, I also could not fix it, because it isn't clear what it is trying to do. There is a comment that it is trying to put the popup within the bounds of the graph.
>
> I can't figure out why this would have been a requirement? Surely if the main window is currently small on the screen, you don't want the popup to try to fit inside it? It is a floating window.

You have to remember that Godot before 4.0 did not support multiple windows. So all dialogs were embedded in the main window (which can be reproduced in 4.0 by enabling single window mode).

So this code probably tries to make sure that the dialog in 3.x and in single window mode in 4.0 fits within the bounds of the graph editor. Since windowing changed in 4.0, this may no longer be needed, or may indeed be done wrong. So it can either be removed completely if the issue it tries to solve is no longer an issue, or fixed.

I'd suggest removing, after checking how things work in Single Window Mode.

Comment (akien-mga) [reply modules/visual_script/editor/visual_script_editor.cpp:1963]: CC @swarnimarun who implemented that code in case you remember why it's needed and why it's done this way. But I strongly suspect the DisplayServer and multi window support changes in 4.0 pretty much invalidate what it was trying to do, so the simplest is probably to remove it if it causes issues, and make a new fix if there are still problems (e.g. in Single Window Mode).

Comment (derammo) [reply modules/visual_script/editor/visual_script_editor.cpp:1963]: Great info, thanks.  Will do.

Comment (derammo) [reply modules/visual_script/editor/visual_script_editor.cpp:1963]: @akien-mga was right.  This code doesn't do anything bad in ```--single-window```.   

Window::set_position(...) in single window mode takes coordinates relative to the main window, presumably like 3.x.

Window::set_position(...) in multi window takes absolute screen coordinates, so things can end up on an entirely different monitor for example.  I am going to start a separate discussion on that, but it is the reason why I initially said the calculation is wrong (for 4.x).

I tested it on both single and multi, and it is better to just remove the code and let the popup code position things, because it is single/multi aware.

Comment (fire) [reply modules/visual_script/editor/visual_script_editor.cpp:1963]: Sounds good.

Comment (derammo) [reply modules/visual_script/editor/visual_script_editor.cpp]: Removed.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
