### PR TITLE
Relaxes node name sanitization in gltf documents.

### LINKED ISSUE #45544: glTF import process strips most non-alphanumeric characters when generating Nodes
**Godot version:**
3.2.3 (but still exists in master as of today)

**OS/device including version:**
Verified with Windows/x64, macOS/x64

**Issue description:**
Importing a glTF file with node names containing characters other than `a-zA-Z0-9_ -` results in Nodes with those characters removed.

It is expected that any characters that are valid in a Godot Node name should also be valid here. The error message within the editor in 3.2.3 indicates that only `. : @ / " ` are disallowed, though in looking at the importer code in 3.2.3 it looks like `$` could be problematic as it is used as a suffix delimiter and by inspection `#` was found to prevent import hints from being processed as well. 

This is particularly useful for `EditorScenePostImport` processing (my specific usecase is adding `key=value` pairs as hints to facilitate BoneAttachment generation)

**Steps to reproduce:**
Create a glb or gltf file with a node whose name contains interesting characters (e.g., `Test!%^&*`), import into Godot and note 
that the imported node in the scene omits those characters.

This project contains a glb file with a default cube named `Cube!%^&*()=[]WithInterestingCharacters` which is renamed `CubeWithInterestingCharacters` by Godot.

[MinimalReproProject.zip](https://github.com/godotengine/godot/files/5890030/MinimalReproProject.zip)

Not clear if this would be obviated by https://github.com/godotengine/godot-proposals/issues/1823
This is also similar to #43482 which covers the impact bone name sanitization has on users.

### PR DESCRIPTION
**Pull request by abaire**
Expands the set of allowed characters in `_sanitize_scene_name`.

This is what my team uses to patch around #45544 though it'd probably be better to use some global method to sanitize names consistently across Godot.

*Bugsquad edit:* Fixes #45544.

### CODE REVIEW

**Comment by fire** [comment]
What test cases did you use to show it works?

File: modules/gltf/gltf_document.cpp [hunk 1]
```diff
@@ -450,7 +450,7 @@ Error GLTFDocument::_serialize_nodes(Ref<GLTFState> state) {
 }
 
 String GLTFDocument::_sanitize_scene_name(const String &name) {
-	RegEx regex("([^a-zA-Z0-9_ -]+)");
+	RegEx regex("([^a-zA-Z0-9_ -=!%^&*(){}\\[\\]|<>,~]+)");
```
Comment (fire) [inline modules/gltf/gltf_document.cpp:453]: Trying to find cases where this breaks. How does it behave with non English node names?

**Comment by abaire** [comment]
Tested with a few glb's generated via Blender (one of which is attached to #45544). The more extensive one has a cube named `Cube=!%^&*(){}\\[\\]|<>,~` and a torus named `Torus=!%^&*(){}\\[\\]|<>,~-noimp`, just verified that the cube is imported as a `MeshInstance` w/ the full name and the torus is not imported at all.

This was intended as a demonstration of the workaround we're using for #45544 (on the 3.2 branch) and a discussion point more than a fully tested patch. Unfortunately I don't know enough about actual limitations on node names in Godot other than what I found enforced here: https://github.com/godotengine/godot/blob/5496174dd40b61a6cfb7d55639820703480846b7/scene/main/node.cpp#L994 . I'm not sure what the intent was behind the original sanitization (which looks like it initially broke import hints and was relaxed in a followup, and I also found that preserving `#` breaks hints but haven't tracked down why) so I'm not sure what cases to look out for.

I'd be happy to dig/test further if I can get a pointer in the right direction.

Wrt. non-English names there should be no change in the existing behavior; anything outside of ASCII and the explicitly listed symbolic characters would still be stripped.

File: modules/gltf/gltf_document.cpp (hunk 1 above)
Comment (abaire) [reply modules/gltf/gltf_document.cpp:453]: Sorry, replied in the top level comment - it'll still strip any non-ASCII characters.

**Comment by fire** [comment]
We had some fun discussion about adding the 💩 emoji and Japanese / Korean / Chinese / etc node names. So that's undecided.

However https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#json-encoding says

> Implementation Note: This allows generic glTF client implementations to not have full Unicode support. Application-specific strings (e.g., values of "name" properties or content of extras fields) may use any symbols.

However, they will still need to be unique.

**Comment by abaire** [comment]
> This expands the list of characters and it's something is hard to discover unless you read or try it, I can understand expanding to other languages, but these list of symbols have other meanings in code, not sure about the interaction with $ get node.

Totally agree, I'm not at all sure what ill effects there could be and would definitely appreciate the guidance. 

Quickly tested the get_node behavior for the symbols in this PR:
```
	var t1 = $"normal=!%^&*(){}[]|<>,~"
	var t2 = get_node("normal=!%^&*(){}[]|<>,~")
```
and they are resolved correctly.

That being said, if there are any other consequences of allowing these symbols to be part of the node names I think it'd be good to capture them in node.cpp's `invalid_character` list, since those seem to be the only things that can't be entered when renaming nodes in the editor.


I think adding unicode support would also be great, having this sanitization apply the superset of node.cpp and glTF limitations feels like it'd be the best user experience. 
Quickly testing in the main and 3.2 branches it looks like attempting to add a unicode emoji into a node name isn't prevented, but it's also not displayed correctly in the editor (whereas adding Japanese is correctly displayed). Similar to the symbols added in this PR, both emoji and Japanese will cause `$` to fail unless the name is quoted (which appears to work as expected, even with the incorrect display of emoji), though I noticed that in master having a name `"文字"` causes the editor to behave abnormally.

**Comment by akien-mga** [comment]
Some comments I put in the Godot Contributors chat:

> I'm not sure why we have to whitelist specific characters instead of just letting `Node::set_name()` do the validation? It calls `Node::_validate_node_name()` which strips:
> ```
> String Node::invalid_character = ". : @ / \"";
> ```
> The only problem would be if a node has an empty name once validated (e.g. if the name is `.:@`).
> Or are there additional characters forbidden in the spec?

**Comment by abaire** [comment]
> Some comments I put in the Godot Contributors chat:
> 
> > I'm not sure why we have to whitelist specific characters instead of just letting `Node::set_name()` do the validation? It calls `Node::_validate_node_name()` which strips:
> > ```
> > String Node::invalid_character = ". : @ / \"";
> > ```
> > 
> > 
> > The only problem would be if a node has an empty name once validated (e.g. if the name is `.:@`).
> > Or are there additional characters forbidden in the spec?

Totally agree. I'd hope that we can assume any additional forbidden chars in the glTF spec would've already been stripped/replaced/whatever'd by the time the importer is run (unless you mean the Godot node spec, in which case I'd expect `set_name` to strip them).

I did notice that names including `#` caused issues with the importer hint processing but never got around to tracking down why.

**Comment by fire** [comment]
Anyone opposing:

> Letting Node::set_name() do the validation?

Note this should probably match skeleton validation.

**Comment by abaire** [comment]
> Anyone opposing:
> 
> > Letting Node::set_name() do the validation?

No objection from my side. We'd just have to track down and fix the behavior I observed with '#' breaking import hints. I'm happy to take a pass at that.

> Note this should probably match skeleton validation.

I agree in principle that it's a better user experience to be as permissive as possible but haven't looked at the bone code myself. My understanding is that they're not Node's so I'm not sure if they need something more restrictive than the Node enforcement. That said, I think it'd be a big improvement to centralize bone name sanitization across all the import paths as well for the sake of consistency/ease of documentation. 
Do you recall the reason behind the current sanitization approach for bones?

Also, is there a mechanism to test the import behavior automatically that I should leverage?

**Comment by fire** [comment]
See https://github.com/godotengine/godot-tests/tree/master/tests/blend_export for some automated testing. You can add new test cases.

File: scene/main/node.h [hunk 2]
```diff
@@ -187,7 +187,9 @@ class Node : public Object {
 
 #ifdef TOOLS_ENABLED
 	friend class SceneTreeEditor;
+	friend class GLTFDocument;
```
Comment (abaire) [inline scene/main/node.h:190]: I'm curious as to whether _validate_node_name should just be made public instead.

File: modules/gltf/gltf_document.cpp [hunk 3]
```diff
@@ -464,7 +477,7 @@ String GLTFDocument::_gen_unique_name(Ref<GLTFState> state, const String &p_name
 		name = s_name;
 
 		if (index > 1) {
-			name += " " + itos(index);
+			name += itos(index);
```
Comment (abaire) [inline modules/gltf/gltf_document.cpp:480]: Removed the trailing space to align with the behavior used by the editor for Nodes (which I suspect would be aligned with user expectations)

**Comment by abaire** [comment]
Switched over to leverage Node's validation. Still a couple outstanding issues with Animation handling and the Emoji tests.

For Emoji specifically, they are not displayed correctly in Blender or in Godot and they're encoded in the reserved range, causing them to trigger the `Unicode parsing error: Invalid unicode codepoint` handlers in ustring.cpp. This results in the creation of nodes that display but can't easily be referenced via `getNode` since the emoji chars get sanitized to the `�` replacement character.
@fire do you think we should explicitly strip Emoji in the sanitizers or just leave it as semi-supported behavior?

**Comment by fire** [comment]
I'll ping @bruvzg and the rocket chat development community.

**Comment by bruvzg** [comment]
> Unicode parsing error: Invalid unicode codepoint

If it's triggering this error, the source string is probably UTF-16 (Godot strings are UTF-32) and emojis are encoded as surrogate pairs. It should be decoded using `String::utf16(const char16_t *p_utf16, int p_len)` method.

**Comment by bruvzg** [comment]
And there is no emoji font in the editor, but the correct string should not give any errors, emoji will be displayed as it hex code: Screenshot 2021-02-13 at 20 25 44

**Comment by bruvzg** [comment]
> If it's triggering this error, the source string is probably UTF-16

Since it's JSON, UTF-16 pair might be stored as "\u0000\u0000" UTF-8 string, we should add handling for this case to the `JSON::_get_token` function (right now it's reading it as is, which will cause `Invalid unicode codepoint` errors).

Or it might be some sort of pseudo-UTF-8 (CESU-8, WTF-8 or some other garbage), in this case it's better to strip it.

**Comment by abaire** [comment]
> > If it's triggering this error, the source string is probably UTF-16
> 
> Since it's JSON, UTF-16 pair might be stored as "\u0000\u0000" UTF-8 string, we should add handling for this case to the `JSON::_get_token` function (right now it's reading it as is, which will cause `Invalid unicode codepoint` errors).

It is indeed a UTF-16 pair in the glTF JSON: `"name" : "Basic_Emoji_\ud83d\ude00\ud83e\udd16",`

@bruvzg your attached fix for `_get_token` fixes this case, the string is now correctly displayed with the hex codes for the two emoji characters - thanks! Is that change something you're working on in a separate PR that I should rebase off of? I can also just disable my emoji-specific test cases until the `_get_token` improvement is available.

File: scene/main/node.h (hunk 2 above)
Comment (fire) [reply scene/main/node.h:190]: Is anything else using it? Do we want other things to use it?

**Comment by fire** [comment]
Are there any specific places you wanted more review? I hope that the test suite is able to give you a feedback improvement cycle.

File: modules/gltf/gltf_document.cpp (hunk 3 above)
Comment (fire) [reply modules/gltf/gltf_document.cpp:480]: This case aligning with user expectation makes sense.

Comment (abaire) [reply modules/gltf/gltf_document.cpp:480]: 👍

File: scene/main/node.h (hunk 2 above)
Comment (abaire) [reply scene/main/node.h:190]: I don't think anything else is using it today, but I'm also not sure if there are other cases where sanitization is being performed (maybe in the other import modules?). In my mind it'd be better for consistency's sake if we'd have everything that generates a Node and needs fine control over naming would leverage `_validate_node_name` so any future modifications to expand/reduce the restricted characters would be applied uniformly. 

Similarly since AnimationPlayer adds a couple additional restrictions, I think we would ideally have a similar public static `_validate_animation_name` that can perform animation-specific cleanup.

**Comment by abaire** [comment]
> Are there any specific places you wanted more review? I hope that the test suite is able to give you a feedback improvement cycle.

I think the test suite change is the more interesting bit to review, assuming the general approach here seems reasonable to you. I'll switch that from a WIP to an actual review; there's still a bit of work left to be done and I may need to remove the emoji tests since they won't pass until the fix that @bruvzg suggested is incorporated.

**Comment by fire** [comment]
Well you could add that change to this pr for the sake of easier review.

File: scene/main/node.h (hunk 2 above)
Comment (fire) [reply scene/main/node.h:190]: I would try hard to find at least one other use or invent a use because if nothing uses it, we don't need to expose.

Comment (abaire) [reply scene/main/node.h:190]: > I would try hard to find at least one other use or invent a use because if nothing uses it, we don't need to expose.

You mean making `_validate_node_name` public specifically? On the one hand it feels odd to make `GLTFDocument` a full friend class just to get access to one method (I assume `SceneTreeEditor` does more interesting Node manipulation), but if there's a general trend towards being conservative about making utility methods public that's fine as well.

**Comment by abaire** [comment]
> Well you could add that change to this pr for the sake of easier review.

Sorry, can you point me at how? I didn't realize you can have a PR span multiple repos (and I'm failing to find out how).

File: modules/gltf/gltf_document.cpp [hunk 4]
```diff
@@ -477,6 +478,40 @@ String GLTFDocument::_gen_unique_name(Ref<GLTFState> state, const String &p_name
 	return name;
 }
 
+String GLTFDocument::_sanitize_animation_name(const String &name) {
+	// Animations disallow the normal node invalid characters as well as  "," and "["
+	// (See animation/animation_player.cpp::add_animation)
+
+	// TODO: Consider adding invalid_characters or a _validate_animation_name to animation_player to mirror Node.
+	String p_name = _sanitize_scene_name(name);
+	RegEx regex("([\\[,]+)");
```
Comment (akien-mga) [inline modules/gltf/gltf_document.cpp:487]: I'd suggest doing a plain `.replace()` for the invalid characters instead of using `RegEx`. The regex module can be disabled, and here this would trigger compilation errors if you don't guard it with `#ifdef MODULE_REGEX_ENABLED` (that's a pre-existing issue in this class though).

File: scene/main/node.h (hunk 2 above)
Comment (akien-mga) [reply scene/main/node.h:190]: Yes please make `_validate_node_name` public (and remove the `_` private prefix), and expose it in `_bind_methods`.

File: modules/gltf/gltf_document.cpp (hunk 4 above)
Comment (abaire) [reply modules/gltf/gltf_document.cpp]: Done, thanks!
I left the regex handling in `_sanitize_bone_name` but can do a followup if we decide to relax sanitization there as well.

File: scene/main/node.h (hunk 2 above)
Comment (abaire) [reply scene/main/node.h]: @akien-mga  Big 👍 on making it public (done, and removed the `STE` `friend` declaration as it seems it was really only used to access name validation). 
Wrt. exposing in `_bind_methods`; it feels like this particular method would provide an atypical GDScript API as it potentially modifies the given String parameter and returns a `bool` indicating if the parameter was modified. Would it be better to expose a wrapping method that returns an `Array` (maybe `[was_valid, validated_name]`) instead?

**Comment by abaire** [comment]
To make the link bidirectional: tests are in godotengine/godot-tests#21

File: scene/main/node.h (hunk 2 above)
Comment (akien-mga) [reply scene/main/node.h]: Ah right, that type of API doesn't work so well for scripting langs. I think this could be refactored into `String Node::validate_node_name(const String p_string)` (i.e. returns a modified string instead of changing in place), though maybe the current form was made this way to avoid allocations in performance critical code?

Comment (akien-mga) [reply scene/main/node.h]: @reduz suggests adding and exposing `String String::validate_node_name(const String &p_string)` instead, and using that in Node and other relevant code that needs to sanitize a node name.

Comment (abaire) [reply scene/main/node.h]: Glancing at the blame I suspect it was just to facilitate the use in `STE` which wants to display an error message if the node name had to be sanitized: 6758b6c1317bbdabd04a2c9f8dc16876429b6bfb
If that's the case it seems like it'd be fine to have it return the string and then do a (admittedly expensive) equality check on the original and returned string in that one spot. 

I'm happy to make that change if you think it's worthwhile?

Comment (abaire) [reply scene/main/node.h]: Sorry, missed the later comment regarding moving the validation to `String`. 
My initial reaction is that approach feels like it smears `Node` concerns into a potentially unexpected place (naively if I was looking for node validation and saw a `Node` class I'd assume it was there). That said, `String` does have things like `simplify_path` that arguably would be appropriate in `_File`.

Comment (abaire) [reply scene/main/node.h]: Poking around a bit more I see that there doesn't appear to be a way to expose a static method via ClassDB so if there's a strong desire to make this bindable, moving it to `String` with the signature: `String String::validate_node_name() const` (where it returns a copy of the string after sanitizing invalid characters) seems like it'd be the most straightforward approach, though it still feels slightly out of place to me.

@akien-mga I'll wait for direction from you/@reduz before going that path, but in the meantime I've pushed a new commit with a script friendly API in case there's a way to bind `static` methods that I've missed. If it's not necessary to bind this method then it'd probably make sense to revert this latest commit to avoid the performance penalty of copying the string.

Comment (akien-mga) [reply scene/main/node.h]: Yeah the scripting bindings don't support static methods, so we have to work it around for now. That's why we tend to (ab)use the String API for some File and Node checks. If we do implement support for static methods, then it would indeed make sense to have this under Node, but for the time being the String approach is the simplest one for a binding.

Comment (abaire) [reply scene/main/node.h]: Makes sense, thanks for the guidance! I've made the change (and added documentation and a basic unit test).

File: core/string/ustring.cpp [hunk 5]
```diff
@@ -4364,6 +4364,17 @@ String String::property_name_encode() const {
 	return *this;
 }
 
+const String String::invalid_node_name_characters = ". : @ / \"";
+
+String String::validate_node_name() const {
+	Vector<String> chars = String::invalid_node_name_characters.split(" ");
```
Comment (akien-mga) [inline core/string/ustring.cpp:4370]: I know this is pre-existing code but I'm not sure if there's much gain having this as a static constant which then gets `split()` on each call. Compilers might be able to optimize this I guess? But we could just as well have `const String restricted_chars = ".:@/\"";` inside the function and iterate over the characters directly.

Comment (akien-mga) [reply core/string/ustring.cpp:4370]: Ah I see `invalid_node_name_characters` is used in SceneTreeEditor` to show a nice error message. Makes sense then I guess.

File: doc/classes/String.xml [hunk 6]
```diff
@@ -887,6 +887,13 @@
 				[/codeblocks]
 			</description>
 		</method>
+		<method name="validate_node_name">
+			<return type="String">
+			</return>
+			<description>
+				Removes any characters from the string that are prohibited in Node names.
```
Comment (akien-mga) [inline doc/classes/String.xml:894]:
```suggestion
				Removes any characters from the string that are prohibited in [Node] names.
```
I think we might as well give the list of those characters here.

File: core/string/ustring.cpp (hunk 5 above)
Comment (abaire) [reply core/string/ustring.cpp:4370]: I thought the same (I'm dubious that this would get memoized by the compiler) but my gut feel is that `validate_node_name` is probably not called frequently enough for the `split` to have a meaningful impact on performance in typical scenarios. If there are scenarios where very large numbers of nodes are getting created it'd be trivial to modify the error message case (which should be even more rare), but I wanted to keep changes limited to the original bug as much as practical.

File: doc/classes/String.xml (hunk 6 above)
Comment (abaire) [reply doc/classes/String.xml]: Done

File: core/string/ustring.cpp (hunk 5 above)
Comment (abaire) [reply core/string/ustring.cpp:4371]:
```suggestion
// Changes made to the set of invalid characters must also be reflected in the String documentation.
const String String::invalid_node_name_characters = ".:@/\"";

String String::validate_node_name() const {
	String invalid_char(&String::invalid_node_name_characters[0], 1);
	String replacement("");
	String name = this->replace(invalid_char, replacement);
	for (int i = 1; i < String::invalid_node_name_characters.length(); ++i) {
		invalid_char[0] = String::invalid_node_name_characters[i];
		name = name.replace(invalid_char, replacement);
	}

	return name;
}
```

**Review by akien-mga — APPROVED** [review]
Core/scene changes look good to me. Could you squash the commits into one?

Would still like confirmation from @fire that the glTF-specific changes are also good.

**Comment by fire** [comment]
Test plan: load test suite once and check for irregularities. Then I’ll approve. Getting there later today.

**Comment by abaire** [comment]
Squashed and repushed. 
@fire as a heads up the Emoji tests are still dependent on the `_get_token` patch from @bruvzg which is not included in this PR (so I'd expect those 3 cases to fail). I can either disable those tests, update them to expect the unicode replacement char (matching the current behavior), or let them fail with the expectation that `_get_token` will be fixed in the near future.

**Review by fire — APPROVED** [review]
Looks good.

Order of operations is:

1. Submit PR / Merge _get_token changes. 
1. _get_token change allows conversion to unknown font glyph because the current behavior of invalid text isn't the correct behavior and this is a way to avoid creating mojibake. https://en.wikipedia.org/wiki/Mojibake
2. Merge this 45545 pr.
3. Merge the tests linked.

**Comment by bruvzg** [comment]
> Submit PR / Merge _get_token changes.

Submitted and merged.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
This doesn't seem trivial to cherry-pick for the `3.2` branch, so it will likely require a dedicated backport PR.
