### PR TITLE
Fix "res://" being replaced by resource packs in the editor and on Android

### LINKED ISSUE #16798: It is currently impossible to test external package loading from within the editor
**Godot version:** 3.0 Release

**OS/device including version:** Windows

**Issue description:**
When loading resource packs using ProjectSettings.load_resource_pack one would assume the content from the resource pack is added to the virtual filesystem, this does work but it also breaks other things, I now present three cases.

In each of the following cases the pck has a folder structure of Content/ModTest and two files in that folder, modtest.png and project.json, modtest.png is a picture of Godette and project.json is some text data.

The game itself has two folders inside the Content folder, BaseContent and TestContent.

**1st case: Directly loading resource using load():** This works exactly as expected, no issues about it.

imagen

**2nd case: Iterating a directory using Directory.list_dir**: It doesn't work, only the files and folders from the newly loaded pck file seem to be found, this is my method:
```

func test_pck_issue():
	var dir = Directory.new()
	if dir.open("res://Content") == OK:
		dir.list_dir_begin(true)
		var directory_name = dir.get_next()
		while (directory_name != ""):
			if dir.current_is_dir():
				print(directory_name)
				file_name = dir.get_next()

```

In this case only ModTest is found, this doesn't seem right to me.

Output when ProjectSettings.load_resource_pack is used:
`ModTest`

Output when it's not used:
```
BaseContent
TestContent
```

**3rd case: trying to find files using the file browser**: This only seems to find the game's base content, but none of the newly loaded pck content.

imagen

I have also tried removing the project configuration from the package, it doesn't change anything.

### LINKED ISSUE #19815: Issues with ProjectSettings.load_resource_pack(pack) when running the project from the editor
**Godot version:**
v3.0.4 stable + PR 19708 (because it fixes my touchscreen issues)

**OS/device including version:**
Surface Pro 4, running Windows 10 Home v1709 (Fall Creator's Update)

**Issue description:**
`ProjectSettings.load_resource_pack('pack.pck')` seems to replace the entire `res://` structure rather than add to it upon its first use **(edit: only when running from the editor; see [comment](https://github.com/godotengine/godot/issues/19815#issuecomment-524161562) for details)**. After the first use, any new loads will add to the current file list.

To give you some examples (presume `current_pack.pck` is the game's main file pack):
```gdscript
# No load; or
ProjectSettings.load_resource_pack("current_pack.pck")
# Can load current_pack.pck's files (expected)
```
```gdscript
ProjectSettings.load_resource_pack("other_pack.pck")
# Will replace files
# Can't load files from current_pack.pck as the file list has been replaced (NOT expected)
```

In order to still have access to my main pack's files, I have to load my game's pck first:
```gdscript
ProjectSettings.load_resource_pack("current_pack.pck")
ProjectSettings.load_resource_pack("other_pack.pck")

# Will add other_pack.pck's files onto the file list (replacing any files that are already in current_pack.pck) (expected)
# Can load current_pack.pck's files as normal except where they've been replaced by other_pack.pck (expected)
# But now I need to load the current .pck over itself, which isn't fun. (NOT expected)

# At this point though, loading resource packs works the same:
# always adding/replacing files after the first load, rather than replacing them like the first load.
```

I would expect to be able to use `ProjectSettings.load_resource_pack("other_pack.pck")` alone and still have access to the files from `current_pack.pck`, without needing to load `current_pack.pck` over itself.

**Steps to reproduce:**
N/A, though here is some code you can use to check the `res://` structure after loading:

```gdscript
func _ready():
	# Should print normal directory structure
	print(dir_contents('res://'))
	
	# Is supposed to only append/replace files, but instead replaces the entire `res://` filesystem
	ProjectSettings.load_resource_pack("other_pack.pck")
	print(dir_contents('res://'))
	
	# But this brings it back to normal by reloading the original pack
	# Except this appends/replaces, which means inconsistent behavior!
	ProjectSettings.load_resource_pack("current_pack.pck")
	print(dir_contents('res://'))

func dir_contents(path):
	# taken from the docs and modified
	var dir = Directory.new()
	if dir.open(path) == OK:
		dir.list_dir_begin(true, false)
		var files = []
		var file_name = dir.get_next()
		while (file_name != ""):
			if (file_name == '.git') or (file_name == '.import'):
				pass
			elif dir.current_is_dir():
				for file in dir_contents(path + file_name + '/'):
					files.append(file)
			else:
				files.append(path + file_name)
			file_name = dir.get_next()
		dir.list_dir_end()
		return files
	else:
		print("An error occurred when trying to access the path.")
		return []
```

**Minimal reproduction project:**
N/A (you can use the demo project repository for this -- just export a couple or five to .pck files and replace `current_pack.pck` and `other_pack.pck` in the script above with appropriate paths)

### LINKED ISSUE #48563: `ProjectSettings.load_resource_pack` replaces res:// completely
**Godot version:**
3.3 stable

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
I tried to load a resource pack:

```
ProjectSettings.load_resource_pack("res://resource_pack.pck")
```

[as described in the documentation](https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_pcks.html#opening-pck-files-at-runtime)

After loading the resource pack, it is not possible to access the resources of the original game. It looks like the loaded resource pack *replaces* `res://` completely.

**Steps to reproduce:**
1. import my minimal reproduction project into Godot 3.3
2. hit F5 to run it
3. the console will show the contents of res://

Expected:
* `Main.tscn` should still be listed as part of res:// even after using `load_resource_pack`

Observed:
*  `Main.tscn` **is missing** in `res://`

**Minimal reproduction project:**

[load_resource_pack.zip](https://github.com/godotengine/godot/files/6446241/load_resource_pack.zip)

This is the `Main.gd` script of the minimal project:
```
func _ready():
	# zip or pck doesn't matter, produces the same result
	ProjectSettings.load_resource_pack("res://resource_pack.pck")
	
	# check res:// content
	var dir = Directory.new()
	dir.open("res://")
	dir.list_dir_begin(true, true)
	while true:
		var file = dir.get_next()
		if not file:
			break
		print(file)
```

### LINKED ISSUE #87274: After loading a pck file (including zip), you can only access the directories and files in the pck
### Tested versions

v4.2.1.stable.arch_linux

### System information

Godot v4.2.1.stable unknown - Arch Linux #1 ZEN SMP PREEMPT_DYNAMIC Mon, 15 Jan 2024 01:11:17 +0000 - Wayland - GLES3 (Compatibility) - Mesa Intel(R) UHD Graphics 630 (CFL GT2) () - Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 Threads)

### Issue description

As the title suggests
图片
I'm using the pck system for mod functions, and it's getting in the way of some of my plans because I still need to access directories and files in my own "res" after loading the player-supplied pck.
By looking at the source code, this seems to be intentional? Is it possible to add a parameter to "load_resource_pack" to determine whether file system access starts from the loaded pck?
图片

### Steps to reproduce

Running Projects

### Minimal reproduction project (MRP)

[test_pck.zip](https://github.com/godotengine/godot/files/13955871/test_pck.zip)

### LINKED ISSUE #89299: ProjectSettings.load_resource_pack overrides files in the main project if replace_files is false.
### Tested versions

Reproducible in 4.2.1-stable.

### System information

Godot v4.1.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 (NVIDIA; 31.0.15.2879) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

I'm trying to load a resource pack from a zip file using `ProjectSettings.load_resource_pack()` with the `replace_files` boolean set to `false`, but regardless the script file in the zip, which has the same name as an identical script in the main project, is being replaced.

### Steps to reproduce

Open and run the sample project. It prints the following lines to the output window:
```
plugin loaded
hello from the plugin
```
That last line means it executed the `hello()` function from the `res://Plugin.gd` script in the plugin.zip. I would expect it to use the function from the same script that is already present in the main project.

### Minimal reproduction project (MRP)

This is the project to reproduce the issue. It contains a plugin.zip which is exported from a second project which is listed here as the second file. You don't need it to reproduce the issue, but it's included in case you want to re-generate plugin.zip yourself.
[godot-host.zip](https://github.com/godotengine/godot/files/14543325/godot-host.zip)
[godot-plugin.zip](https://github.com/godotengine/godot/files/14543330/godot-plugin.zip)

### PR DESCRIPTION
**Pull request by tracefree**
### The problem
When using `ProjectSettings.load_resource_pack` and launching the game from the editor or on Android, `DirAccess` no longer sees files and directories outside of loaded packs, which is unexpected behavior and makes it difficult to work on modding support for example.

### My solution
The simplest way I could find to solve this was to add a new kind of `PackSource`: `PackedSourceDirectory` (working title). 
It uses a resource directory as the source of the "pack" rather than a file, and returns regular FileAccess references.
The first time a resource pack is loaded, the entire "res://" directory gets added to `PackedData`.

I adapted the MRP of #48563 to Godot 4.x: 
[MRPResourcePack.zip](https://github.com/godotengine/godot/files/14916234/MRPResourcePack.zip)

I am new to Godot's codebase and C++ in general, so there is probably a better solution. I'd be happy about any feedback or suggestions on how to solve this problem properly.

Edit: This should also solve `replace_files == false` not doing anything in non-exported projects, see #89299.

* *Bugsquad edit, fixes: #48563*
* *Bugsquad edit, fixes: #19815*
* fixes #87274 
* fixes #16798 
* fixes #89299

### CODE REVIEW

**Comment by tracefree** [comment]
One alternative approach I could imagine might be preferable is to change the behavior of `DirAccess::make_default`, but I think that would require more substantial changes and I'm not sure I understand the codebase well enough to make them myself.

**Comment by scgm0** [comment]
Similar problems also exist on Android, because on Android, "res://" is also a real local directory.

**Comment by tracefree** [comment]
> Similar problems also exist on Android, because on Android, "res://" is also a real local directory.

Is there an issue documenting the problem on Android? I'm not sure my fix would resolve that, but I could try it out.

By the way, this may go beyond the scope of a bugfix, but I think my approach could easily be adapted to allow users to load _any_ directory on the filesystem as a "pack", not just the resource folder. This could be very useful to modders, who would otherwise need to pack all assets into a .pck or .zip file every time they want to test changes to their mod while developing it. This would work by e.g. ProjectSettings.load_resource_pack("path/to/mod/directory").

**Comment by scgm0** [comment]
> > Similar problems also exist on Android, because on Android, "res://" is also a real local directory.
> 
> Is there an issue documenting the problem on Android? I'm not sure my fix would resolve that, but I could try it out.
> 
> By the way, this may go beyond the scope of a bugfix, but I think my approach could easily be adapted to allow users to load _any_ directory on the filesystem as a "pack", not just the resource folder. This could be very useful to modders, who would otherwise need to pack all assets into a .pck or .zip file every time they want to test changes to their mod while developing it. This would work by e.g. ProjectSettings.load_resource_pack("path/to/mod/directory").

https://github.com/godotengine/godot/issues/87274
Although I didn’t mention Android in the introduction, I did initially discover this problem on Android.

**Comment by tracefree** [comment]
> #87274 Although I didn’t mention Android in the introduction, I did initially discover this problem on Android.

Ah yes, that does appear to be the same problem and my PR should fix it (unless there are additional complications due to Android, I'll try to test that out). Adding it to the list of relevant issues, thank you.

File: core/config/project_settings.cpp
Comment (scgm0) [inline core/config/project_settings.cpp:1]: Maybe you can use `!OS::get_singleton()->get_resource_dir().is_empty()` instead of `OS::get_singleton()->has_feature("editor")`, because the Android export has the same problem.

Comment (tracefree) [reply core/config/project_settings.cpp:1]: Finally managed to setup building for Android and tested it out. You are right, with that condition the fix also works on Android. Thanks for the feedback!

File: core/io/file_access_pack.cpp
Comment (scgm0) [inline core/io/file_access_pack.cpp:1]: It seems that `print_line(file_path);` is a bit redundant?

Comment (tracefree) [reply core/io/file_access_pack.cpp:1]: Ah I was only using that for debugging and forgot to remove that line, sorry about that!

**Comment by tracefree** [comment]
I just realized there is a problem in my code: After loading a resource pack, you can only see files that existed in res:// at the time the first pack was loaded. Meaning any files that were created in the resource folder at runtime after loading the pack won't be visible. This is still better than the current behavior, where you can't see any files in the resource folder, but ideally there shouldn't be _any_ unexpected differences between loading and not loading a resource pack. I'll try to see if there's a simple way to keep the contents of PackedData synced to changes in the filesystem. This would probably have to  involve adding something like "remove_path" to PackedData to support cases where resource files were removed at runtime.

**Comment by scgm0** [comment]
> I just realized there is a problem in my code: After loading a resource pack, you can only see files that existed in res:// at the time the first pack was loaded. Meaning any files that were created in the resource folder at runtime after loading the pack won't be visible. This is still better than the current behavior, where you can't see any files not belonging to datapacks in the resource folder at all, but ideally there shouldn't be _any_ unexpected side effects to loading a resource pack. I'll try to see if there's a simple way to keep the contents of PackedData synced to changes in the filesystem. This would probably have to involve adding something like "remove_path" to PackedData to support cases where resource files were removed at runtime.

It feels like the current fix is the usable version, `res://` is not supposed to be modified at runtime, so synchronizing only the first time is good enough.

**Comment by tracefree** [comment]
> It feels like the current fix is the usable version, `res://` is not supposed to be modified at runtime, so synchronizing only the first time is good enough.

I tend to agree, but then the behavior of this edge case should be documented. Fact is that it is currently possible to modify `res://` at runtime in the editor, and while it doesn't make sense to do so in exported builds I could imagine there are legitimate use cases for it during development of a project. Perhaps I could add a short sentence to the documentation of `load_resource_pack`?

**Comment by tracefree** [comment]
The last thing I need clarity on is whether and how to expose `PackedSourceDirectory` to users. At the moment, due to how I implemented the fix, users can call load_resource_pack("res://") by themselves, and they can even use subdirectories of `res://`, which would be like loading a pack that has the contents of that directory.  I see four options:

1) Do nothing. Then there would be undocumented / possibly undefined behavior of load_resource_pack.
2) Leave it as is but document this relatively useless behavior.
3) Somehow try to prevent users from doing this manually.
4) Make it into a useful feature by allowing to load any directory on the filesystem as a pack, not just ones in "res://", and document it alongside .pck and .zip as a fully supported third kind of pack. This would be my personal preference, but I'd like to hear some more opinions before I work on including this in the PR.

**Comment by scgm0** [comment]
I don't think there is any need to expose `PackedSourceDirectory` at the moment. Let this PR only fix bugs. 4 can be considered for completion in subsequent PRs.

**Comment by tracefree** [comment]
> I don't think there is any need to expose `PackedSourceDirectory` at the moment. Let this PR only fix bugs. 4 can be considered for completion in subsequent PRs.

Makes sense. Would you say this PR is ready to be merged as is then, or should I include a check to prevent users from accessing the new internal functionality manually from GDScript until it's fleshed out and documented later? I'm thinking of adding something like `if (p_pack == "res://") { return false }` to `_load_resource_pack`.

**Comment by scgm0** [comment]
Reasonable, before the function is determined, user calls should indeed be prevented from producing unpredictable results.

**Comment by tracefree** [comment]
As discussed earlier, I added a line to the documentation of `load_resource_pack` explaining the remaining limitation to `DirAccess`. The wording may be a bit awkward, I'd appreciate any feedback if the same thing can be said in a more straightforward way.

**Comment by tracefree** [comment]
I'm failing a unit test for the macOS editor. Unfortunately I don't have access to any Apple computers... does anyone have an idea for what could be causing this? I assume it might have something to do with how I'm iterating over hidden directories?

**Comment by AThousandShips** [comment]
That one happens randomly on macOS, we're still unsure why, I'll just run it again and it should fix itself

**Comment by scgm0** [comment]
How is the progress of this PR? Is it possible to merge in 4.3?

**Comment by tracefree** [comment]
> How is the progress of this PR? Is it possible to merge in 4.3?

It's ready from my side. Since it's a bug-fix I assume it could even be cherrypicked to 4.2.x / 4.1.x?

**Review by m4gr3d — APPROVED** [review]
The logic looks good to me!

Worth calling out that the touched code is not specific to Android, so an additional review from `#platforms` and `#core` may be needed.

**Review by AThousandShips — APPROVED** [review]

File: core/io/file_access_pack.cpp [hunk 1]
```diff
@@ -267,6 +267,37 @@ Ref<FileAccess> PackedSourcePCK::get_file(const String &p_path, PackedData::Pack
 
 //////////////////////////////////////////////////////////////////
 
+bool PackedSourceDirectory::try_open_pack(const String &p_path, bool p_replace_files, uint64_t p_offset) {
+	// load with offset feature only supported for PCK files
```
[the remark this answers is not in the document]
Comment (tracefree) [reply core/io/file_access_pack.cpp:271]: I copied the comment from the ZIP version of the method, should I change it there as well? Or is that too unrelated?

https://github.com/godotengine/godot/blob/86bf8354a06ab7b23a0ff6a81b48fd015e92ac94/core/io/file_access_zip.cpp#L150

[the remark this answers is not in the document]
Comment (AThousandShips) [reply core/io/file_access_pack.cpp:271]: You can leave it as is to not make too much noise

**Comment by AThousandShips** [comment]
Please squash your commits into one, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

**Comment by tracefree** [comment]
I've been thinking, maybe `PackedSourceFileSystem` is a better name than `PackedSourceDirectory`?

**Comment by akien-mga** [comment]
Just a quick status update. This looks promising (and appears to solve a lot of important issues), but from a quick chat with @reduzio it seemed to us that there is a deeper design issue with the resource pack loading, which would need to be addressed properly instead of worked around like done here.

So this needs further research (likely from the @godotengine/core team), which may or may not lead to merging this solution as is, or a more involved one. Either case, since we're in feature freeze for 4.3 now and this is relatively sensitive code, we'll postpone this to 4.4 (and consider a 4.3 cherry-pick if the solution we end up merging seems suitable for it).

**Comment by dannygaray60** [comment]
I hope don't forget about godot 3.6 all bugs reported for the 3.x branch are sent to 4.x ...

**Comment by AThousandShips** [comment]
> I hope don't forget about godot 3.6 all bugs reported for the 3.x branch are sent to 4.x ...

If there isn't a dedicated 3.x report for this please open one, the claim that all bugs are just sent to 4.x isn't true if they're specific to 3.x

**Comment by AThousandShips** [comment]
The other issue is off topic for this PR, but the 3.6 marked issue is now not linked to this so it can be tracked and discussed, not all fixes can be applied to 3.x because of compatibility and complexity

**Comment by tracefree** [comment]
For what it's worth, I think my fix would easily transfer to 3.x as well. I can look into it once we have an agreed upon solution for 4.x.

**Comment by ThatFinnDev** [comment]
I've found an issue with this fix (because it doesn't fix something crucial). When you load a resource pack with replace files enabled, it will only replace files if they haven't been referenced before loading the pck/zip. 
For example, in the MRPResourcePack project, if the icon.svg is used in another scene as an image, the `ProjectSettings.load_resource_pack` function won't replace the icon.svg with replace files enabled.
I'm not talking about the image not updating in the other scene (even though that's broken too). When a file has been referenced before in any kind (with preload, in other scenes, in other resources) and you load a resource pack and then try to load the file with `load("res://path-to-file")`, you get the old one

**Comment by JHDev2006** [comment]
adding on to this, this fix is mostly what id need, however trying to replace files using load_resource_pack is hopeless. either checking which files and what not are loaded before the pck gets loaded, then unloading them. or just giving us a way to see what resources are already loaded would be incredibly helpful!

**Comment by tracefree** [comment]
Hi! It's been a while since I worked on this, but IIRC replacing files that have been previously loaded is not a trivial fix due to how the resource system works, and I think it would be out of scope for this specific PR. And as akien said earlier, the whole resource pack system has design flaws and will have to be fundamentally changed to properly fix all its various issues, so I am waiting on updates on those plans before I can build on this PR.

File: core/config/project_settings.cpp [hunk 2]
```diff
@@ -474,12 +474,24 @@ bool ProjectSettings::_load_resource_pack(const String &p_pack, bool p_replace_f
...
 	if (!ok) {
 		return false;
 	}
 
+	if (!using_datapack && !OS::get_singleton()->get_resource_dir().is_empty()) {
+		// Add the project's resource file system to PackedData so directory access keeps working when
+		// the game is running without a main pack, like in the editor or on Android.
+		PackedData::get_singleton()->add_pack_source(memnew(PackedSourceDirectory));
+		PackedData::get_singleton()->add_pack("res://", !p_replace_files, 0);
+	}
```
Comment (bruvzg) [inline core/config/project_settings.cpp:493]: Should it go before `PackedData::get_singleton()->add_pack` and always have `replace_files = false` when loading additional packs? Since loaded, resource pack should override files in the folder (like it will do with main pack).

Probably something like:
- Skip entirely when loading main pack (might need additional wrapper method with extra argument set for main pack).
- When loading additional pack, do it before loading pack (as if it is main pack).

```c++
// Exposed wrapper:
bool ProjectSettings::load_resource_pack(const String &p_pack, bool p_replace_files, int p_offset) {
	return _load_resource_pack(const String &p_pack, bool p_replace_files, int p_offset, false)
}

// Implementation:
bool ProjectSettings::_load_resource_pack(const String &p_pack, bool p_replace_files, int p_offset, bool p_main_pack) {

...

	if (!p_main_pack && !using_datapack && !OS::get_singleton()->get_resource_dir().is_empty()) {
		// Add the project's resource file system to PackedData so directory access keeps working when
		// the game is running without a main pack, like in the editor or on Android.
		PackedData::get_singleton()->add_pack_source(memnew(PackedSourceDirectory));
		PackedData::get_singleton()->add_pack("res://", false, 0);
	}
	bool ok = PackedData::get_singleton()->add_pack(p_pack, p_replace_files, p_offset) == OK;
...

}
```

File: core/io/file_access_pack.cpp [hunk 3]
```diff
@@ -267,6 +267,42 @@ Ref<FileAccess> PackedSourcePCK::get_file(const String &p_path, PackedData::Pack
...
+
+	if (p_path != "res://") {
+		return false;
+	}
+	add_directory(p_path, p_replace_files);
+	return true;
+}
+
+Ref<FileAccess> PackedSourceDirectory::get_file(const String &p_path, PackedData::PackedFile *p_file) {
+	return FileAccess::open(p_path, FileAccess::READ);
```
Comment (bruvzg) [inline core/io/file_access_pack.cpp:282]: `FileAccess::open` will try to load the file from `PackedData`, which can be an issue if the file is overridden. Probably should use, `open_internal` to skip it and directly open underling file system:
```suggestion
	Ref<FileAccess> ret = FileAccess::create_for_path(p_path);
	ret->reopen(p_path, FileAccess::READ);
	return ret;
```

**Comment by mihe** [comment]
@tracefree Any chance you would be able to incorporate the feedback from @bruvzg above, within the next few weeks? If not, I could take this pull request across the finish line, if that's fine with you.

The issue that this PR solves has turned out to (perhaps unsurprisingly) affect the patch system introduced in #97118 as well, so it would seem to me that it's quite important that we get this fixed before 4.4-stable.

**Comment by tracefree** [comment]
@mihe Hi! Sorry, I got sidetracked and hadn't found the time to look into this issue once more even though I've been meaning to. Thanks for the reminder, I will look into it by this weekend at the latest!

File: core/config/project_settings.cpp (hunk 2 above)
Comment (tracefree) [reply core/config/project_settings.cpp]: Hi, thank you so much for the review! Sorry for the delayed response. So it's been a long time since made the PR and to be honest I'm not entirely sure anymore what my thought process was. I implemented your suggestion and my test project seems to keep working.

I added the additional argument, but since it's preceded by two optional arguments I also had to give it a default value - I went with `false` for now, but all instances in the code base where `_load_resource_pack` is called are for loading the main pack as far as I can tell where the value needs to be `true`. So I had to change those calls and also include the arguments `p_replace_files` and `p_offset`. Should I just set the default value to `true`? It would make the code in the setup phase more readable.

Although, I _think_ the condition `!using_datapack && !OS::get_singleton()->get_resource_dir().is_empty()` was meant to ensure the code is skipped exactly when the main pack is being loaded and to not make an additional argument necessary... let me think this through once more.

So in the context of exported builds that rely on a main pack, when that first pack is loaded the resource directory will be empty, skipping the code block. Subsequent pack loads also skip it since the `using_datapack == true`.

In Android builds or when launched from the editor, there is no main pack and the first datapack to be loaded should cause the PackedSourceDirectory to be added. When the first datapack is loaded, `using_datapack` will be false and the resource directory not empty, meaning the block gets executed. In subsequent calls, `using_datapack` will be true again.

I might be missing something, but I think the code already works as intended even without the wrapper method and an explicit `p_main_pack`? If that makes sense to you I could revert those changes to my original code and add a comment explaining the condition instead.

Regarding the order of `add_pack`, I assume my thinking was that I want to return as early as possible when the datapack can't be loaded for some reason, i.e. when loading an invalid pack the `PackedSourceDirectory` should not be added. And since I added it after the user datapack it was necessary to use `!p_replace_files` (since, when the pack gets added before "res://", there is nothing to overwrite so all files go through, and to respect the `p_replace_files` argument the opposite has to be applied to the "res://" pack loaded after it). But if it makes the code more readable I can keep your suggestion to reverse the order and set `p_replace_files = false`. The only downside is that attempting to load an invalid datapack would have the side effect of changing FileAccess to datapack mode when it's not strictly necessary.

**Comment by tracefree** [comment]
Some more thoughts in addition to my code review comment:

- I would be very happy for this bug to get fixed since there so many associated issues. But I just want to point once more that my PR still has a weird side effect: after adding a datapack and `PackedSourceDirectory` is activated, new files added to `res://` will no longer be picked up by `DirAccess::get_files_at` etc since the way it works is that a "snapshot" of the current `res://` directory is taken and interpreted as a `PackedSource` at the moment the first non-main datapack is loaded. It is a very niche problem since modifying `res://` is not really intended during runtime, but it's also not forbidden and I can imagine that people will come up with scenarios e.g. with tool development where doing just that is necessary, but once a resource pack is loaded there will be unexpected behavior. This side effect is a consequence of my PR being a bandaid on top of the rigid way resource packs were originally implemented. Akien mentioned in an earlier comment that a more extensive solution tackling the underlying issues would be better. Has there been any progress on this front? Are there ongoing discussions? I'm of course happy for the PR to be merged as-is as a temporary solution if it doesn't make an eventual greater rewrite more difficult.
- There are some other PRs and proposals regarding unloading datapacks (#61286), mounting them to specific paths (#7769), adding custom prefixes (#98544), etc. I hope my PR doesn't cause too much trouble for those efforts.
- Finally, if my PR gets merged, I think it would be neat to explicitly support loading filesystem directories as "PackedSources". It would only be a matter of removing a check preventing this and adding documentation. It would be cool e.g. for mod development, where one could more easily load the working directory of a mod instead of having to zip the folder every time after making a change before launching the game.

File: core/config/project_settings.cpp (hunk 2 above)
Comment (bruvzg) [reply core/config/project_settings.cpp]: > when that first pack is loaded the resource directory will be empty

No, it's not always true. Android can use main pack (it's not by default), and `get_resource_dir()` won't be empty. Custom OS implementations can override it as well.

**Review by bruvzg — APPROVED** [review]

File: core/config/project_settings.cpp (hunk 2 above)
Comment (tracefree) [reply core/config/project_settings.cpp]: Ah, I didn't know that! Okay then the wrapper method is inevitable.

**Comment by Repiteo** [comment]
Thanks!
