### PR TITLE
Do not try to save internal scripts

### LINKED ISSUE #40175: Closing a scene with built-in script opened will open a Save Resource dialog
**Godot version:**

3.2.3 beta 07b24de (and probably master)

**Steps to reproduce:**
1. Create/open a built-in script so it appears in the script editor
2. Close the scene tab

### PR DESCRIPTION
**Pull request by danielzting**
Fixes #40175

If I'm reading the code correctly, to check if a script is internal, it must have a path that is either empty or contains `local://` or `::`. Since I see that snippet being used 4 times verbatim I also thought it would be a good idea to factor it out into `Resource`.

### CODE REVIEW

File: editor/plugins/script_editor_plugin.cpp [hunk 1]
```diff
@@ -800,7 +802,7 @@ bool ScriptEditor::_test_script_times_on_disk(RES p_for_script) {
 				continue;
 			}
 
-			if (edited_res->get_path() == "" || edited_res->get_path().find("local://") != -1 || edited_res->get_path().find("::") != -1) {
```
Comment (akien-mga) [inline editor/plugins/script_editor_plugin.cpp:803]: There's one more occurrence at line 2102.
The check is also used in editor/plugins/shader_editor_plugin.cpp, editor/plugins/script_text_editor.cpp and (partially, so might not be a candidate for changing it) editor/plugins/text_editor.cpp.

But such core changes take more time to review than ad-hoc fixes, so I'd suggest keeping the fix ad-hoc for this bugfix PR, and then make a new PR proposing the addition of `Resource::is_internal`, which might have use cases beyond just checking for built-in scripts too.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.
