### PR TITLE
Fix export(float ...) so that step is .01 

### LINKED ISSUE #11964: export (float,min,max) clamps float to int
This issue: #539 still happens in godot 2.1.4.

Code that I am using is:
export(float, -100, 100) var variable = 0.0
in inspector any number given is then rounded to int.

In future should I comment on closed issue instead opening new one?

### PR DESCRIPTION
**Pull request by minifigmaster125**
So that in the property editor the range does not increment by integer step. Fix for #11964 

@bojidar-bg pointed out those lines so I changed both. It's my first contribution to godot, so be blunt if I'm doing something wrong. Also if someone could explain to me what the functions I adjusted achieve on a higher level I'd appreciate that. I understand that it has something to do with display when the property editor is updated, but some more info would be cool. 

*Bugsquad edit:* Fixes #11964.

### CODE REVIEW

File: editor/property_editor.cpp [hunk 1]
```diff
@@ -376,7 +376,7 @@ bool CustomPropertyEditor::edit(Object *p_owner, const String &p_name, Variant::
 			if (hint == PROPERTY_HINT_RANGE) {
 
 				int c = hint_text.get_slice_count(",");
-				float min = 0, max = 100, step = 1;
+				float min = 0, max = 100, step = .01;
```
Comment (minifigmaster125) [inline editor/property_editor.cpp]: to be honest this part didn't seem to affect the property editor, leaving at 1 still allowed the property to have float values in the range. Though I probably am missing how it's used, which is why I changed it anyway.

**Comment by bojidar-bg** [comment]
Shoudn't you do something like (psuedo-cpp) `type == TYPE_INT ? 1 : 0.01`? This way, I guess, it wouldn't work for integers.

File: editor/property_editor.cpp (hunk 1 above)
Comment (bojidar-bg) [reply editor/property_editor.cpp]: This is for the spinbox (used when dragging up/down).

**Comment by minifigmaster125** [comment]
Well, it seems to work with export(int, 0, 100) because I'm assuming the int is casting the float. 

export_fix

I can still do it though.

**Comment by minifigmaster125** [comment]
are any tests needed?

**Review by bojidar-bg — APPROVED** [review]

**Comment by bojidar-bg** [comment]
@minifigmaster125 We don't have a test suite for the editor yet, so no tests needed.
