### PR TITLE
Disallow antialiasing for software skinned 2d polys

### LINKED ISSUE #46466: Software Skinning doesn't work when using a Polygon2D with Antialiasing enabled.
**Godot version:**

3.2.4.rc3

**OS/device including version:**

Windows 10 PC with RTX 2060, using the most recent NVidia Game Ready drivers and the GLES3 backend.

**Issue description:**

When Software Skinning is enabled in the Project Settings, a Polygon2D doesn't deform to a skeleton if Antialiasing is enabled on that polygon. If it is disabled, skinning works as expected.

**Steps to reproduce:**
Create a Polygon2D and a Skeleton2D with some bones. Go through the usual process of attaching the Polygon2D to the Skeleton2D. Note that a texture is required to do so. Move around the bones to ensure that skinning is working. Then, enable Antialiasing on the Polygon2D and move the bones again. It will not work. This only occurs when Software Skinning is enabled in the Project Settings, which is the default condition.

**Minimal reproduction project:**

[Polygon2DSkinning.zip](https://github.com/godotengine/godot/files/6053644/Polygon2DSkinning.zip)

Possibly related to https://github.com/godotengine/godot/issues/46465?

### PR DESCRIPTION
**Pull request by lawnjelly**
Antialiasing is not supported for batched polys. Currently due to the fallback mechanism, skinned antialiased polys will be rendered without applying animation.

This PR simply treats such polys as if antialiasing had not been selected. The class reference is updated to reflect this.

Fixes #46466.

## Notes
I was wavering between two of the options in the linked issue, they both have plus and negative points:

3) Automatically turn off anti-aliasing in skinned polys when software skinning is on
4) Put in a warning / error message, and put a note in the docs

In the absence of feedback, and on reflection I've gone for (3) here as it will pretty much run fine even if you weren't aware of the limitation. It's probably a good compromise, but I can change if there are preferences to other methods. 

Strictly speaking software skinned polys _could_ be rendered with anti aliasing, but it would require another codepath, and I'm not convinced of the need to implement it currently. The problem is compounded because software skinned meshes can be batched together and rendered in one drawcall (e.g. 100 can render as 1 drawcall). But if antialiasing was used that would no longer possible, and the logic would need to be added for this.

### CODE REVIEW

File: drivers/gles_common/rasterizer_canvas_batcher.h [hunk 1]
```diff
@@ -2282,7 +2282,19 @@ PREAMBLE(bool)::prefill_joined_item(FillState &r_fill_state, int &r_command_star
...
+				bool use_legacy_path = false;
+
 				if (polygon->antialiased) {
+					// anti aliasing is also not support for software skinned meshes.
+					// we can't easily revert, so we force software skinned meshes to run through
+					// batching path with no AA.
+					if (bdata.settings_use_software_skinning && p_item->skeleton != RID()) {
+					} else {
+						use_legacy_path = true;
+					}
```
Comment (clayjohn) [inline drivers/gles_common/rasterizer_canvas_batcher.h:2294]:
```suggestion
					if (!(bdata.settings_use_software_skinning && p_item->skeleton != RID())) {
						use_legacy_path = true;
					}
```

Comment (lawnjelly) [reply drivers/gles_common/rasterizer_canvas_batcher.h:2294]: Haha yeah that probably is better. I sometimes end up doing it the longhand way because I find it easier to reason with, but I am nuts. :+1: :grin:

Comment (akien-mga) [reply drivers/gles_common/rasterizer_canvas_batcher.h:2294]: Or if you want to be a cool oneliner kid:
```cpp
use_legacy_path = !(bdata.settings_use_software_skinning && p_item->skeleton != RID());
```
or
```cpp
use_legacy_path = !bdata.settings_use_software_skinning || p_item->skeleton == RID()

File: drivers/gles_common/rasterizer_canvas_batcher.h [hunk 2]
```diff
@@ -2282,7 +2282,19 @@ PREAMBLE(bool)::prefill_joined_item(FillState &r_fill_state, int &r_command_star
 #ifdef GLES_OVER_GL
 				// anti aliasing not accelerated .. it is problematic because it requires a 2nd line drawn around the outside of each
 				// poly, which would require either a second list of indices or a second list of vertices for this step
+				bool use_legacy_path = false;
+
 				if (polygon->antialiased) {
+					// anti aliasing is also not support for software skinned meshes.
```
Comment (akien-mga) [inline drivers/gles_common/rasterizer_canvas_batcher.h:2288]:
```suggestion
					// anti aliasing is also not supported for software skinned meshes.
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
