### PR TITLE
Fix `NodePath` `EditorProperty` using the wrong scene root

### LINKED ISSUE #115402: ViewportTexture doesn't update from SubViewport in 4.6 w/Editable Children
### Tested versions

Reproduces in 4.6
Does not reproduce in 4.5

### System information

Godot v4.6.stable - Windows 11 (build 26100) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 32.0.15.7216) - 13th Gen Intel(R) Core(TM) i9-13900K (32 threads) - 63.78 GiB memory

### Issue description

Just did an import of my project and now all my ViewportTextures are broken.

Image

This is a visual shader that uses a viewport texture passed into a Texture2DParameter. Recreating the ViewportTexture fixes the problem, but only while the file is open. The next time the tscn is loaded, the viewport is not longer rendered.

### Steps to reproduce

Open a 4.5 project that uses viewport textures in 4.6
Result: ViewportTexture is magenta.
Expected: should show contents of viewport

Clear the viewport texture and reassign to a new viewport texture that points at the subviewport
Results: viewport texture now renders correctly

Save scene and reload.
Results: Texture is back to being magenta.
Expected: Texture should load and display viewport frames.

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by Rindbee**
For properties like `ViewportTexture.viewport_path` that enable `PROPERTY_USAGE_NODE_PATH_FROM_SCENE_ROOT`. The case of enabling **Editable Children** to edit nodes in a child scene seems to have been overlooked before.

Fix https://github.com/godotengine/godot/issues/115402#issuecomment-3802056398.

### CODE REVIEW

**Comment by Rindbee** [comment]
> Assign a new `ViewportTexture` to the `texture` property.

Confirmed. This is related to the code below.

https://github.com/godotengine/godot/blob/77579f93e6ee7cf2515da4a7a5000d8a0244be98/editor/inspector/editor_properties.cpp#L3485-L3488

File: editor/inspector/editor_properties.cpp [hunk 1]
```diff
@@ -3246,15 +3246,29 @@ Node *EditorPropertyNodePath::get_base_node() {
...
-	return base_node;
+	if (get_edited_object()->has_method("get_root_path")) {
+		return Object::cast_to<Node>(get_edited_object()->call("get_root_path"));
+	}
+
+	if (!base_node) {
+		return nullptr; // Editing external resources.
+	}
+
+	if (!base_node->get_scene_file_path().is_empty()) {
```
Comment (KoBeWi) [inline editor/inspector/editor_properties.cpp]:
```suggestion
	if (base_node->is_instance()) {
```

File: editor/inspector/editor_properties.cpp [hunk 2]
```diff
@@ -3475,6 +3500,39 @@ bool EditorPropertyResource::_should_stop_editing() const {
 	return !resource_picker->is_toggle_pressed();
 }
 
+Node *EditorPropertyResource::_get_base_node() {
```
Comment (KoBeWi) [inline editor/inspector/editor_properties.cpp:3499]: It would be nice to unify this with EditorPropertyNodePath, as their methods are _almost_ the same, but it's for another PR.

**Review by KoBeWi — APPROVED** [review]
