### PR TITLE
Fix parsing Resource type as value type of a Dictionary

### LINKED ISSUE #100889: Loading resources containing typed `Dictionary`s with values of type `Resource` causes a parse error
### Tested versions

- Reproducible in v4.4.dev2 [97ef3c837] and later snapshots (tested in v4.4.dev2, v4.4.dev5, v4.4.dev6, and v4.4.dev7)
- Not reproducible in earlier versions, as support for typed dictionaries had not been added yet.

### System information

Godot v4.4.dev7 - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated Quadro M2200 - Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 threads)

### Issue description

When using the `load` function to load a .tres file containing a typed `Dictionary` with values of type `Resource` (e.g. `Dictionary[int, Resource]`), the resource fails to load and the following errors are present:
```
E 0:00:01:0172   main.gd:5 @ _ready(): user://save.tres:7 - Parse Error: Expected ']'
  <C++ Source>   scene/resources/resource_format_text.cpp:41 @ _printerr()
  <Stack Trace>  main.gd:5 @ _ready()

E 0:00:01:0172   main.gd:5 @ _ready(): Failed loading resource: user://save.tres. Make sure resources have been imported by opening the project in the editor at least once.
  <C++ Error>    Condition "found" is true. Returning: Ref<Resource>()
  <C++ Source>   core/io/resource_loader.cpp:323 @ _load()
  <Stack Trace>  main.gd:5 @ _ready()
```
The expected behavior is that the resource loads successfully without errors.

The issue does not occur when using a class that inherits `Resource`. For example, using a custom class called `CustomResource` that extends `Resource` will not cause the error.

Additionally, adding an extra mismatched closing square bracket to the .tres file stops the error as well:
```
data = Dictionary[int, Resource]]({})
```

### Steps to reproduce

1. Download and open the minimal reproduction project
2. Run the project
3. Check the Errors tab of the debugger, the above errors appear
4. In `SaveData.gd`, replace `Dictionary[int, Resource]` with `Dictionary[int, CustomResource]`
5. Run the project again and check the debugger, the errors are no longer thrown

### Minimal reproduction project (MRP)

[resource-loading-error.zip](https://github.com/user-attachments/files/18268655/resource-loading-error.zip)

### PR DESCRIPTION
**Pull request by Synzorasize**
Fixes #100889.

A line was forgotten, so I added it. I do not believe it affects anything else as the scope is specifically for this use case.

### CODE REVIEW

File: core/variant/variant_parser.cpp [hunk 1]
```diff
@@ -1224,6 +1224,7 @@ Error VariantParser::parse_value(Token &token, Variant &value, Stream *p_stream,
 						value_type = Variant::OBJECT;
 						value_class_name = token.value;
 						got_comma_token = true;
```
Comment (dalexeev) [inline core/variant/variant_parser.cpp:1226]:
```suggestion
```

Looks like a copy-paste bug, `got_bracket_token` should be _instead_ of `got_comma_token`. CC @Repiteo

**Review by dalexeev — COMMENTED** [review]
It would also be nice to add tests for typed arrays and dictionaries, somewhere here:

https://github.com/godotengine/godot/blob/aa65940a8509fb880e2c666eb8a901525d9200ff/tests/core/variant/test_variant.h#L1740

https://github.com/godotengine/godot/blob/aa65940a8509fb880e2c666eb8a901525d9200ff/tests/core/variant/test_variant.h#L1790

File: core/variant/variant_parser.cpp (hunk 1 above)
Comment (Synzorasize) [reply core/variant/variant_parser.cpp:1226]: Yes, the `got_comma_token` is already consumed by this check, so it is essentially useless here.

**Comment by Synzorasize** [comment]
> It would also be nice to add tests for typed arrays and dictionaries, somewhere here

Should this be added in this PR, or a future one? I suppose the Dictionary one fits here, since this PR fixes a bug that slipped through as a result of not having this check, but it may be out of scope for the Array one.

**Comment by Synzorasize** [comment]
I feel like the code could potentially be cleaned up/optimized, though I am not sure what usecase the parentheses after `Resource` is usually for, as I haven't recalled seeing them before in `tres` or `tscn` files. I have only seen usecases of `ExtResource` and `SubResource` with parentheses. Other than that, I think it might be best to merge this for now.

**Review by akien-mga — APPROVED** [review]
Looking at surrounding code, that seems to make sense, but I'm not expert.

**Review by Repiteo — APPROVED** [review]
Good eye!

**Comment by Repiteo** [comment]
Thanks!
