### PR TITLE
LSP: Fix loading scene for every request on script file for workspace completion

### LINKED ISSUE #100934: LSP performance issues on "slower" devices
### Tested versions

- Reproducable in 4.3.stable

### System information

Godot v4.3.stable - Windows 10.0.26100 - Vulkan (Mobile) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.21024.2004) - AMD Ryzen 7 7735U with Radeon Graphics (16 Threads)

### Issue description

Using the LSP server via NeoVim or VSCode on my laptop results in very slow responses (several seconds) when working with specific scripts in my project.

I have investigated the LSP client-side settings and could not find any differences between files that respond quickly and those with slow responses. Additionally, the project runs without any issues on my desktop PC. Running the LSP server on my desktop and connecting to it from my laptop also eliminates the problem.

File length does not seem to be a factor. Even after deleting the entire content of a problematic file, leaving only the class name and its extends declaration, the slow response persists. Similarly, the number of references to the class does not appear to influence performance. Certain classes consistently cause slow responses, while others resolve normally.

I have also noticed a significant increase in memory usage by Godot when editing files with slow responses—about 2–3 times the usual amount. This behavior does not occur on my desktop PC, even for the same files/classes.

Unfortunately, I don’t have any additional insights at this time, as I haven’t been able to identify a specific cause within the project, the files, or their references. However, it seems there might be a performance issue with the LSP server that the desktop's processing power overcomes but manifests as slow responses on the laptop.

If anyone has experienced a similar issue or can provide guidance on debugging the LSP server side, I would greatly appreciate your help.

Thanks in advance!

### Steps to reproduce

Unfortunately not yet.

### Minimal reproduction project (MRP)

Unfortunately not yet.

### PR DESCRIPTION
**Pull request by HolonProduction**
Fixes https://github.com/godotengine/godot/issues/100934

Supersedes https://github.com/godotengine/godot/pull/101091

I originally was only going to fix up some style issues to get the PR ready for merge, but ended up with some structure changes that I did not want to push to the original PR. (CC @dekaravanhoc if you are fine with the changes and want to integrate them feel free to do so!)

Differences:
- rebased onto recent LSP changes
- removed some excessive includes
- moved the scene cache into it's own file
- renamed some methods and parameters -> most of this is pretty subjective, some of it is meant to disambiguate or align stuff with other code
- adjusted the behaviour of `get` to do a blocking load as fallback -> this is a measure for edge cases when multiple clients are connected and was an easier solution for the edge case than refcounting the loaded instances.
- flattened out the additional queue struct. It made the code more clear but made the adjustment to `get` more complicated than necessary.

---

### Short explanation

GDScript autocompletion can provide certain options that are tied to a specific scene instance, e.g. node paths for `$Node` literals. In the builtin editor the opened scene is used for that so an instance is inherently present. For external editors we need a different approach. Previously we would search a scene, load it and instantiate it for every request from the external editor. This has shown to be too slow in certain situations.

This change introduces a cache that keeps those scene instances alive between requests.

### CODE REVIEW

File: modules/gdscript/language_server/gdscript_language_protocol.cpp [hunk 1]
```diff
@@ -147,6 +147,9 @@ Error GDScriptLanguageProtocol::on_client_connected() {
 
 void GDScriptLanguageProtocol::on_client_disconnected(const int &p_client_id) {
 	clients.erase(p_client_id);
+	if (clients.size() == 0) {
```
Comment (AThousandShips) [inline modules/gdscript/language_server/gdscript_language_protocol.cpp]:
```suggestion
	if (clients.is_empty()) {
```

File: modules/gdscript/language_server/scene_cache.cpp [hunk 2]
```diff
@@ -0,0 +1,189 @@
...
+/**************************************************************************/
+
+#include "scene_cache.h"
+
+#include "godot_lsp.h"
+
+#include "core/io/resource_loader.h"
+#include "core/string/ustring.h"
+#include "core/templates/local_vector.h"
+#include "core/typedefs.h"
```
Comment (AThousandShips) [inline modules/gdscript/language_server/scene_cache.cpp]:
```suggestion
```

File: modules/gdscript/language_server/scene_cache.h [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+
+/**
+ * Used to load and cache scene instances for LSP autocompletion.
+ *
+ * This implementation is not thread safe.
+ */
+class SceneCache {
+	// Always contains the path to the scene which is currently loaded via the `ResourceLoader`.
+	// If this is not empty, `script_path_queue` must have at least one element.
+	String current_loaded_owner = "";
```
Comment (AThousandShips) [inline modules/gdscript/language_server/scene_cache.h]:
```suggestion
	String current_loaded_owner;
```

**Review by akien-mga — APPROVED** [review]

**Review by AThousandShips — APPROVED** [review]
