### PR TITLE
GDScript: Fix autocompletion issues with nested types

### LINKED ISSUE #11430: Suggest type constants as types
### Describe the project you are working on

Complex GDScript-based project.

### Describe the problem or limitation you are having in your project

GDScript supports using constants as types, e.g. `const MyType = preload("res://script/path.gd")` and afterwards `var my_object: MyType` etc. It's a nice feature if you don't want to pollute global namespace. However these "types" are not suggested in autocompletion, so e.g. if you write `var my_object: MyT`, the type won't be suggested.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be useful if type constants were available for autocompletion. Both local constants (`MyType`) and external ones (`ClassName.MyType`).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The editor is able to determine when to complete for type hint. "Constant types" are just constants of type Script, so they could be added to the type autocompletion list.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

Built-in autocompletion can't be extended.

### LINKED ISSUE #71734: Missing autocompletion for nested types
### Godot version

v4.0.beta13.official [caacade56]

### System information

Windows 11

### Issue description

No autocompletion suggestions are provied when giving type hints for a nested type.

### Steps to reproduce

Consider the following:

```
# foo.gd
enum NestedEnum {
	CONSTANT_ONE,
	CONSTANT_TWO
}

# bar.gd
# There is no "Foo.NestedEnum" in the autocompletion when writing the type hint.
var e: Foo.NestedEnum
```

### Minimal reproduction project

[bug_no_autocompletion_when_type_hinting_with_nested_type.zip](https://github.com/godotengine/godot/files/10466809/bug_no_autocompletion_when_type_hinting_with_nested_type.zip)

### PR DESCRIPTION
**Pull request by HolonProduction**
Fixes #71734
Fixes https://github.com/godotengine/godot/issues/108045
Closes https://github.com/godotengine/godot-proposals/issues/11430
Salvaged from #71842

Also improves/fixes some smaller issues that I stumbled upon when writing tests for the original issue:
- preloaded types are now correctly suggested in type hints
- ordering of types in inner classes shows types from the inner class first
...

Adds support for global classes to the completion test runner and turns of error printing for the tests.

~Marked as draft for now, since I still want to finish the test cases.~

### CODE REVIEW

File: modules/gdscript/tests/test_completion.h [hunk 1]
```diff
@@ -219,13 +221,50 @@ static void test_directory(const String &p_dir) {
...
+		} else if (next.ends_with(".gd")) {
+			String base_type;
+			String source_file = path.path_join(next);
+			String class_name = GDScriptLanguage::get_singleton()->get_global_class_name(source_file, &base_type);
+			if (class_name.is_empty()) {
+				next = dir->get_next();
+				continue;
+			}
+			ERR_FAIL_COND_MSG(ScriptServer::is_global_class(class_name),
+					"Class name '" + class_name + "' from " + source_file + " is already used in " + ScriptServer::get_global_class_path(class_name));
```
Comment (AThousandShips) [inline modules/gdscript/tests/test_completion.h]:
```suggestion
					"Class name \"" + class_name + "\" from \"" + source_file + "\" is already used in \"" + ScriptServer::get_global_class_path(class_name) + "\".");
```

**Review by Geometror — COMMENTED** [review]
Looks great!
I think we have no clear rules regarding TODO comments, but for me they are fine in this case.

Needs a rebase though, I will continue my review after that.

File: modules/gdscript/gdscript_editor.cpp [hunk 2]
```diff
@@ -1013,6 +1013,7 @@ static void _list_available_types(bool p_inherit_only, GDScriptParser::Completio
 		}
 	}
 
+	// TODO: Unify with _find_identifiers_in_class
```
Comment (Geometror) [inline modules/gdscript/gdscript_editor.cpp:1016]:
```suggestion
	// TODO: Unify with _find_identifiers_in_class.
```

**Comment by Geometror** [comment]
To be honest, I'm not a fan of deleting the test. I'd suggest linking the issue you created as a dependency and waiting for it to be fixed :) (or fixing it yourself if you have the time)

**Comment by HolonProduction** [comment]
For reference the issue: https://github.com/godotengine/godot/issues/105421

Personally I don't think it should be a blocker for this PR though. I'm also not removing the test, just excluding it from running for now.

**Review by vnen — APPROVED** [review]
LGTM

File: modules/gdscript/tests/test_completion.h [hunk 3]
```diff
@@ -183,7 +183,6 @@ static void test_directory(const String &p_dir) {
 				scr->set_path(res_path);
 				owner->set_script(scr);
 			}
-
```
Comment (AThousandShips) [inline modules/gdscript/tests/test_completion.h]: Unrelated and noisy, please restore

**Review by AThousandShips — APPROVED** [review]

File: modules/gdscript/tests/test_completion.h (hunk 1 above)
Comment (HolonProduction) [reply modules/gdscript/tests/test_completion.h]: What's up with the escaped underscore in the part that isn't a string. Is this some quirk with C++ macros?

Comment (AThousandShips) [reply modules/gdscript/tests/test_completion.h]: Oh my bad no clue how that got in the suggestion!

Comment (HolonProduction) [reply modules/gdscript/tests/test_completion.h]: Alright, resolved :+1:

**Comment by HolonProduction** [comment]
Temporarily converting to draft to check what's going on with the CI.

**Comment by HolonProduction** [comment]
Alright, should be working now.

**Comment by Repiteo** [comment]
Thanks!
