### PR TITLE
LSP: Fix singleton registration

### LINKED ISSUE #86132: Cannot access the `GDScriptLanguageProtocol` in GDScript
### Tested versions

Reproducible in 4.2-stable
Not reproducible in 4.1.3-stable

### System information

Linux/Manjaro

### Issue description

Trying to access the `GDScriptLanguageProtocol` singleton using either its identifier (#52162) or `Engine.get_singleton()` fails and returns `null` when running a `@tool` script. The engine prints `ERROR: Failed to retrieve non-existent singleton 'GDScriptLanguageProtocol'.` to console.

### Steps to reproduce

Make a `@tool` script that tries to access GDScriptLanguageProtocol

### Minimal reproduction project (MRP)

[singleton-repro.zip](https://github.com/godotengine/godot/files/13665651/singleton-repro.zip)
To observe the issue, run the project with:
`$ godot4.2 --editor --quit --headless --script res://test_dump.gd`
One of the lines printed will be the error mentioned above.
Running the script with 4.1.3 works and generates `dump.json` properly, even though it prints that there are no clients connected to the LSP.

### PR DESCRIPTION
**Pull request by HolonProduction**
Fixes https://github.com/godotengine/godot/issues/52162
Fixes https://github.com/godotengine/godot/issues/86132

The singleton is now registered on `MODULE_INITIALIZATION_LEVEL_EDITOR` instead of a late callback.

To make this work I removed an old test case that limited singletons to only types that inherit directly from `Object`. This should be fine based on my question on RC.

### CODE REVIEW

**Review by Repiteo — APPROVED** [review]
Discussed in [this rc thread](https://chat.godotengine.org/channel/core?msg=YE8XEkBcBpsYWXJkN), and I agree that singletons should not be constrained to `Object` alone (at least, not without it being explicitly documented as such).

File: editor/doc/doc_tools.cpp [hunk 1]
```diff
@@ -988,9 +988,6 @@ void DocTools::generate(BitField<GenerateFlags> p_flags) {
 			}
 			pd.name = s.name;
 			pd.type = s.ptr->get_class();
-			while (String(ClassDB::get_parent_class(pd.type)) != "Object") {
-				pd.type = ClassDB::get_parent_class(pd.type);
-			}
```
Comment (HolonProduction) [inline editor/doc/doc_tools.cpp:993]: This dates back to GODOT IS OPENSOURCE and does not make any sense to me. Singletons should just be documented with their type.

Although I'm not 100% certain if their might be some GDExtension concern with this.

**Review by Ivorforce — APPROVED** [review]
Agreed.
I can't think of a reason to restrict to direct `Object` succession. It might just be leftover code from when it made more sense.

The rest of the changes also look good to me.

File: editor/doc/doc_tools.cpp (hunk 1 above)
Comment (HolonProduction) [reply editor/doc/doc_tools.cpp:993]: Nevermind. It prevents implementation classes like e.g. `IPUnix` to appear. I guess this would require registering singletons with an explicit type to fix.

Comment (Ivorforce) [reply editor/doc/doc_tools.cpp:993]: `IPUnix` shouldn't appear in the docs anyway since it's an internal class.
Edit: The fact that it does sounds like a bug in the docs.

Comment (HolonProduction) [reply editor/doc/doc_tools.cpp:993]: Yeah the same seems to be true for the other classes that appear like this. So by now we have better ways to deal with what this code did originally. We can just search for the closest public class and should be fine.

**Review by akien-mga — APPROVED** [review]
