### PR TITLE
Resize project dialog only when necessary

### LINKED ISSUE #66620: New project: lag when typing manually into project path input
### Godot version

4.0-beta2

### System information

Fedora 36

### Issue description

image

In this state, whenever I backspace the 'a' - or type 'a' again after the / - Godot lags. I'm presuming this is because it's checking my home directory `/home/doug` for something.

Note that there are a lot of files in this directory - so maybe it's doing some sort of full scan?

### Steps to reproduce

Alternate the input between having an existent and non-existent path.

### Minimal reproduction project

n/a

### PR DESCRIPTION
**Pull request by Nidjo123**
Fixes #66620.

To improve both performance and user experience, we should not resize the dialog on every message change. Rather we resize it only if the content wouldn't fit into the current window size.

The other thing encountered while fixing this is that (at least) on X11 resizing window can fail if the requested size does not fall into current min and max range. Therefore, we should first change the min and max values and only then set the new size value.

### CODE REVIEW

**Review by bruvzg — APPROVED** [review]

File: editor/project_manager.cpp [hunk 1]
```diff
@@ -143,7 +143,11 @@ class ProjectDialog : public ConfirmationDialog {
 			install_status_rect->set_texture(new_icon);
 		}
 
-		set_size(Size2(500, 0) * EDSCALE);
+		Size2i window_size = get_size();
+		Size2 contents_min_size = get_contents_minimum_size();
+		if (window_size.x < contents_min_size.x || window_size.y < contents_min_size.y) {
+			set_size(window_size.max(contents_min_size) * EDSCALE);
```
Comment (bruvzg) [inline editor/project_manager.cpp:149]:
```suggestion
			set_size(window_size.max(contents_min_size));
```
It should already be correctly scaled.

Comment (Nidjo123) [reply editor/project_manager.cpp]: Right, the scale gets applied upon dialog creation. Fixed.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
