### PR TITLE
Fix looking at with 180 degree arc

### LINKED ISSUE #53793: look_at_from_position: Up vector and direction between node origin and target are aligned, look_at() failed.
### Godot version

v3.4.beta4.official [6a058cbf3]

### System information

Windows 10, Nvidia GTX 750Ti

### Issue description

I would like to know why the up vector and direction between node origin and target being aligned is considered an error and why I have to add checks to make sure its directly not Vector3.Up and Vector3.Down. This seriously does not make since to me at all. Shouldn't it just be the default rotation of being upwards or downwards? If there is some complex reason why this is like this, can it have some sort of documentation? Thanks!

### Steps to reproduce

Note that this is is just a example of a line that would cause the error:

```
var collision_normal_up = Vector3.UP
var collision_normal_down = Vector3.DOWN

spatial.look_at(collision_normal_up, Vector3.UP) # Returns a error
spatial.look_at(collision_normal_down, Vector3.UP) # Returns a error
```

### Minimal reproduction project

_No response_

### LINKED ISSUE #57457: look_at() can't look up
### Godot version

3.4.2

### System information

windows 10

### Issue description

b.look_at( b.transform.origin+Vector3.UP, Vector3.UP )

When I try to make my object look upwards, it fails to rotate at all.
Based on the documentation, it should end up with the -z towards the target position.

### Steps to reproduce

b.look_at( b.transform.origin+Vector3.UP, Vector3.UP )

### Minimal reproduction project

_No response_

### LINKED ISSUE #80249: `new Quaternion(Up, Down) * Up == Up`, but it should be Down
### Godot version

4.1

### System information

Linux 5.15

### Issue description

When using the [arc-based quaternion constructor](https://docs.godotengine.org/en/latest/classes/class_quaternion.html#class-quaternion-constructor-quaternion) very specifically with the arguments `Vector3.Up` & `Vector3.Down`, the resulting quaternion is wrong.

### Steps to reproduce

Sorry that it's in C# instead of GDScript, but I don't have much experience with GDScript.
```C#
// These assertions are fine:
assert (new Quaternion(Vector3.Left, Vector3.Right) * Vector3.Left == Vector3.Right);
assert (new Quaternion(Vector3.Right, Vector3.Left) * Vector3.Right == Vector3.Left);
assert (new Quaternion(Vector3.Forward, Vector3.Back) * Vector3.Forward == Vector3.Back);
assert (new Quaternion(Vector3.Back, Vector3.Forward) * Vector3.Back == Vector3.Forward);

 // These assertions will fail:
assert (new Quaternion(Vector3.Down, Vector3.Up) * Vector3.Down == Vector3.Up);  // Result is actually Vector3.Down
assert (new Quaternion(Vector3.Up, Vector3.Down) * Vector3.Up == Vector3.Down);  // Result is actually Vector3.Up
```

### PR DESCRIPTION
**Pull request by TokageItLab**
- Supersedes/closes https://github.com/godotengine/godot/pull/93653
- Fixes https://github.com/godotengine/godot/issues/80249
- Fixes https://github.com/godotengine/godot/issues/57457
- Fixes https://github.com/godotengine/godot/issues/53793

Have it calculate the perpendicular vectors by the cross product of the constants vector3 `(1, 0, 0)` or `(0, 1, 0)` depends on the nearest axis and implement the similar[^1] approach as #93653 in a more simple way. Also, for `looking_at()` and `look_at()`, allow this with a warning (and explain it in the document).

[^1]: This PR may cause a breaking compatibility in that the quaternion of the 180 degree rotation will be inverted for consistency in the direction of rotation, but this is almost never a problem unless you use slerp, etc. in the special situation of generating a 180 degree arc. If you really want to migrate/make compatibility it, the user can align the phase of the quaternion, as in `Quaternion(Basis(Quaternion(v0, v1)))`.

### CODE REVIEW

**Review by fire — APPROVED** [review]

**Comment by fire** [comment]
We tend to require more help with documentation!

File: tests/core/math/test_quaternion.h [hunk 1]
```diff
@@ -235,6 +235,36 @@ TEST_CASE("[Quaternion] Construct Basis Axes") {
...
+	Quaternion left_to_right(left, right);
+	Quaternion right_to_left(right, left);
+	CHECK(left_to_right.xform(left).is_equal_approx(right));
+	CHECK(Quaternion(right, left).xform(right).is_equal_approx(left));
+	CHECK(Quaternion(up, down).xform(up).is_equal_approx(down));
+	CHECK(Quaternion(down, up).xform(down).is_equal_approx(up));
+	CHECK(Quaternion(forward, back).xform(forward).is_equal_approx(back));
+	CHECK(Quaternion(back, forward).xform(back).is_equal_approx(forward));
+
+	// With (arbitrary) opposite vectors that are not axis-aligned as parameters
```
Comment (AThousandShips) [inline tests/core/math/test_quaternion.h:257]:
```suggestion
	// With (arbitrary) opposite vectors that are not axis-aligned as parameters.
```

File: doc/classes/Basis.xml [hunk 2]
```diff
@@ -214,7 +214,8 @@
 			<description>
 				Creates a new [Basis] with a rotation such that the forward axis (-Z) points towards the [param target] position.
 				By default, the -Z axis (camera forward) is treated as forward (implies +X is right). If [param use_model_front] is [code]true[/code], the +Z axis (asset front) is treated as forward (implies +X is left) and points toward the [param target] position.
-				The up axis (+Y) points as close to the [param up] vector as possible while staying perpendicular to the forward axis. The returned basis is orthonormalized (see [method orthonormalized]). The [param target] and [param up] vectors cannot be [constant Vector3.ZERO], and cannot be parallel to each other.
+				The up axis (+Y) points as close to the [param up] vector as possible while staying perpendicular to the forward axis. The returned basis is orthonormalized (see [method orthonormalized]).
+				It is recommended that the direction from the node position to the [param target] vector not be parallel to the [param up] vector. Although, the Z axis points to the target, but the second axis is not defined, therefore causing a Z rotation implicitly.
```
Comment (AThousandShips) [inline doc/classes/Basis.xml:218]:
```suggestion
				It is recommended that the direction from the node position to the [param target] vector not be parallel to the [param up] vector. In this case the Z axis points to the target the second axis is not defined, therefore causing a Z rotation implicitly.
```
Assuming this was meant, also should clarify if it's `+Z` or `-Z` that points to the target

File: doc/classes/Node3D.xml [hunk 3]
```diff
@@ -127,7 +127,8 @@
 			<description>
 				Rotates the node so that the local forward axis (-Z, [constant Vector3.FORWARD]) points toward the [param target] position.
 				The local up axis (+Y) points as close to the [param up] vector as possible while staying perpendicular to the local forward axis. The resulting transform is orthogonal, and the scale is preserved. Non-uniform scaling may not work correctly.
-				The [param target] position cannot be the same as the node's position, the [param up] vector cannot be zero, and the direction from the node's position to the [param target] vector cannot be parallel to the [param up] vector.
+				The [param target] position cannot be the same as the node's position, the [param up] vector cannot be zero.
+				It is recommended that the direction from the node position to the [param target] vector not be parallel to the [param up] vector. Although, the Z axis points to the target, but the second axis is not defined, therefore causing a Z rotation implicitly.
```
Comment (AThousandShips) [inline doc/classes/Node3D.xml:131]: And apply same changes here

**Review by AThousandShips — COMMENTED** [review]
Can't speak to the mathematics but some tweaks to the docs

File: doc/classes/Basis.xml (hunk 2 above)
Comment (TokageItLab) [reply doc/classes/Basis.xml:218]: It can be either, depending on the use_model_front argument

File: doc/classes/Basis.xml [hunk 4]
```diff
@@ -214,7 +214,8 @@
 			<description>
 				Creates a new [Basis] with a rotation such that the forward axis (-Z) points towards the [param target] position.
 				By default, the -Z axis (camera forward) is treated as forward (implies +X is right). If [param use_model_front] is [code]true[/code], the +Z axis (asset front) is treated as forward (implies +X is left) and points toward the [param target] position.
-				The up axis (+Y) points as close to the [param up] vector as possible while staying perpendicular to the forward axis. The returned basis is orthonormalized (see [method orthonormalized]). The [param target] and [param up] vectors cannot be [constant Vector3.ZERO], and cannot be parallel to each other.
+				The up axis (+Y) points as close to the [param up] vector as possible while staying perpendicular to the forward axis. The returned basis is orthonormalized (see [method orthonormalized]).
+				It is recommended that the direction from the node position to the [param target] vector not be parallel to the [param up] vector. Although, the +Z or -Z axis points to the target, but the second axis is not defined, therefore causing a Z rotation implicitly.
```
Comment (AThousandShips) [inline doc/classes/Basis.xml:218]: The wording still need to be changed, the use of comma here isn't right, so I'd suggest something like what I was suggesting, or at least clearing up the commas, so:
```suggestion
				It is recommended that the direction from the node position to the [param target] vector not be parallel to the [param up] vector. In this case the +Z or -Z axis points to the target, but the second axis is not defined, therefore causing a Z rotation implicitly.
```
Or
```suggestion
				It is recommended that the direction from the node position to the [param target] vector not be parallel to the [param up] vector. Although the +Z or -Z axis points to the target, the second axis is not defined, therefore causing a Z rotation implicitly.
```
The sentence with `although` doesn't flow well and AFAIK they aren't used together

**Review by AThousandShips — APPROVED** [review]

File: doc/classes/Basis.xml [hunk 5]
```diff
@@ -214,7 +214,8 @@
 			<description>
 				Creates a new [Basis] with a rotation such that the forward axis (-Z) points towards the [param target] position.
 				By default, the -Z axis (camera forward) is treated as forward (implies +X is right). If [param use_model_front] is [code]true[/code], the +Z axis (asset front) is treated as forward (implies +X is left) and points toward the [param target] position.
-				The up axis (+Y) points as close to the [param up] vector as possible while staying perpendicular to the forward axis. The returned basis is orthonormalized (see [method orthonormalized]). The [param target] and [param up] vectors cannot be [constant Vector3.ZERO], and cannot be parallel to each other.
+				The up axis (+Y) points as close to the [param up] vector as possible while staying perpendicular to the forward axis. The returned basis is orthonormalized (see [method orthonormalized]).
+				It is recommended that the direction from the node position to the [param target] vector not be parallel to the [param up] vector. In this case the +Z or -Z axis points to the target, but the second axis is not defined, therefore causing a Z rotation implicitly.
```
Comment (Flarkk) [inline doc/classes/Basis.xml:218]: [param target] and [param up] cannot be [constant Vector3.ZERO],  and shouldn't be colinear to avoid unintended rotation around local Z axis.

File: doc/classes/Node3D.xml [hunk 6]
```diff
@@ -127,7 +127,8 @@
 			<description>
 				Rotates the node so that the local forward axis (-Z, [constant Vector3.FORWARD]) points toward the [param target] position.
 				The local up axis (+Y) points as close to the [param up] vector as possible while staying perpendicular to the local forward axis. The resulting transform is orthogonal, and the scale is preserved. Non-uniform scaling may not work correctly.
-				The [param target] position cannot be the same as the node's position, the [param up] vector cannot be zero, and the direction from the node's position to the [param target] vector cannot be parallel to the [param up] vector.
+				The [param target] position cannot be the same as the node's position, the [param up] vector cannot be zero.
+				It is recommended that the direction from the node position to the [param target] vector not be parallel to the [param up] vector. In this case the +Z or -Z axis points to the target, but the second axis is not defined, therefore causing a Z rotation implicitly.
```
Comment (Flarkk) [inline doc/classes/Node3D.xml:131]: Same as previous comment

File: core/math/vector3.h [hunk 7]
```diff
@@ -326,6 +327,11 @@ Vector3 Vector3::direction_to(const Vector3 &p_to) const {
 	return ret;
 }
 
+Vector3 Vector3::perpendicular() const {
+	ERR_FAIL_COND_V_MSG(is_zero_approx(), Vector3(0, 0, 0), "The Vector3 must not be zero.");
+	return cross((Math::abs(x) <= Math::abs(y) && Math::abs(x) <= Math::abs(z)) ? Vector3(1, 0, 0) : Vector3(0, 1, 0)).normalized();
```
[the remark this answers is not in the document]
Comment (Flarkk) [reply core/math/vector3.h:332]: Gave it a second thought and I'm not sure this deserves to be a member function. It's definition is quite tricky to document clearly : it's supposed to return _some_ perpendicular vector. I'd suggest to make it rather a free function on the cpp.

[the remark this answers is not in the document]
Comment (TokageItLab) [reply core/math/vector3.h:332]: Since Vector3 is a Godot-defined class, it could be a static function, but I think it would not make sense to define a function that returns some Vector3 outside of it. Also, if we expose this method along with the documentation that "it returns some perpendicular vector", some users may always use this to get look_at up vectors, but that is never recommended, so I would keep this private.

[the remark this answers is not in the document]
Comment (TokageItLab) [reply core/math/vector3.h:337]: For now, I left it only in the comments so that later people will not be confused.

Also, I found in the Plane class has get_any_perpendicular_normal() as a non-exposed (to GDScript) member function, so I think it is okay to not make it public. BTW, I assume we should change the internal of get_any_perpendicular_normal() to use Vector3.perpendicular() as well, but it would be fine to make it a separate PR later as a follow up.

[the remark this answers is not in the document]
Comment (Flarkk) [reply core/math/vector3.h:337]: Maybe rename it to `get_any_perpendicular()` instead of just `perpendicular()` then.

File: core/math/basis.cpp [hunk 8]
```diff
@@ -1049,9 +1049,10 @@ Basis Basis::looking_at(const Vector3 &p_target, const Vector3 &p_up, bool p_use
 		v_z = -v_z;
 	}
 	Vector3 v_x = p_up.cross(v_z);
-#ifdef MATH_CHECKS
-	ERR_FAIL_COND_V_MSG(v_x.is_zero_approx(), Basis(), "The target vector and up vector can't be parallel to each other.");
-#endif
+	if (v_x.is_zero_approx()) {
+		WARN_PRINT("Target and up vectors are colinear. This is not advised as it may cause unwanted rotation around local Z axis.");
```
Comment (akien-mga) [inline core/math/basis.cpp:1053]: This might spam a lot, shouldn't it be `WARN_PRINT_ONCE`?

In general this kind of warnings aren't super helpful to end users, as a basis may end up in this state from internal engine code or complex calculations, and the warning doesn't point at which basis / object transform is referred to. So I'm not convinced this will make end users happy.

**Comment by lawnjelly** [comment]
Since asked for review, my thoughts are mainly on https://github.com/godotengine/godot/issues/53793#issuecomment-943007010 .

As I said in the comment, the rotation is undefined close to the up vector, and (as far as I can see) this is still likely to be the case after this PR (it just spams warnings instead of refusing to attempt, either way the user has to correct for this). There's no magic with cross product and the "any perpendicular" function, you are still losing precision as the vectors get close to each other.

I suspect the problem is really with the API, as it is trying to solve an impossible problem (this PR is effectively just a band-aid).

The typical case is a 1st person camera wanting to look up.

The obvious solution I can see is that *somewhere*, you want to keep a record of the previous yaw, and use that in cases where the yaw is undefined (close to the up vector, or 180 degrees from this).

So something like
```
yaw = look_at_relative(const Vector3 &p_pos, const Vector3 &p_up, float p_previous_yaw);
```

And have the `look_at` routine calculate the yaw, send it back to be stored by the user and fed into the routine on the next frame as `p_previous_yaw`, so it can be used in the degenerate case.

This ensures you get no randomization close to zero due to float precision, and no error spamming.

Of course this means you either the user needs to store this previous value (which makes documenting the function more complex to newbies), or you need e.g. some kind of automatic storage on the node (which might be prone to error depending on the use case, say if there are two `look_at` per frame etc, but could be doable).

Even after this PR, effectively the user will likely have to do all this manually, to avoid error spam, so we aren't really better off (imo), it's just that we are trying to hide the bug (which will instead happen rarely and user won't know why).

**Comment by lawnjelly** [comment]
Since asked for review, my thoughts are mainly on https://github.com/godotengine/godot/issues/53793#issuecomment-943007010 .

This post is just some advance thoughts on the issues, and I'm sure PRs on the below would refine things.

## Cause
As I said in the comment, the rotation is undefined close to the up vector, and (as far as I can see) this is still likely to be the case after this PR (it just spams warnings instead of refusing to attempt, either way the user has to correct for this). There's no magic with cross product and the "any perpendicular" function, you are still losing precision as the vectors get close to each other.

I'll describe this in terms of the typical situation of a first person camera looking up, but this applies to other situations too.

## Variations of problem
There are actually three problem situations to consider:

1) Looking straight up from a previous different orientation. Here we have the potential to reuse the previous yaw.
2) Looking straight up from orientation *very close* to straight up. Here the previous yaw is subject to random precision error.
3) Looking straight up with no information as to previous yaw.

The real problem stems that to give sensible results, we need a concept of "previous yaw", to fallback on in the degenerate case if the yaw is undefined.

## API and previous yaw
This is really an API problem imo, the existing API is problematic and may be best deprecated / altered. The `Basis` function in particular is designed with no concept of previous basis (and therefore previous yaw), so is always in situation (3). _(Same applies to `Quat` but I'll just refer to `Basis` for brevity.)_

The ideal solution would be something like:
```
yaw = look_at_relative(const Vector3 &p_rel_pos, const Vector3 &p_up, float p_previous_yaw);
```

i.e. We need to provide the function with a fallback yaw to use in case it is undefined (`p_rel_pos` is close to `p_up` or at 180 degrees to `p_up`).

The function in most cases would be able to calculate the yaw, return it to the caller to be used in the next frame for smooth motion. It could be initialized to e.g. 0 on the first frame as the previous yaw is undefined and doesn't hugely matter.

The real problem is therefore where this "previous yaw" should come from.

In the case of both a `Basis` and a `Node`, we can either:
* Have the user provide previous yaw
* Calculate it from the existing basis

For a `Node`, we also have the option to store a previous yaw directly on the node, rather than derive from the `Basis` on the `Transform`. This would work better for case (2).

In terms of API for `Node` you have a choice:
* Leave it to the user to store and provide "previous yaw" (this is most adaptable)
* Have the node store a previous yaw automatically (this could _possibly_ cause problems in some use cases, such as multiple `look_at` per frame, but could be doable)

For `Basis` you probably need two versions, calculate yaw from previous basis contents, or supply the previous yaw. Obviously calculating yaw from previous basis is still susceptible to (2).

Another option to solve (2) is to not change the basis (as it is very close to up vector anyway), not report an error, but maybe return a `false` for success (in case the user wanted to act upon this).

## This PR
This PR is more a band-aid if I'm reading it right, it just prevents the previous behaviour of failing, and estimates a yaw, but takes no account of previous yaw, so will result in spurious behaviour I think, and the user will still probably have to handle all this manually if they don't want spurious rotation changes.

**Comment by Flarkk** [comment]
Could use the current `Basis` as the "previous value" you refer to be an acceptable middle ground ?

Wouldn't solve all 3 cases you mention but at least provide consistent results in the FPS case where the `Basis` is updated incrementally.

**Comment by lawnjelly** [comment]
> Could using the current Basis as the "previous value" you refer to be an acceptable middle ground ?

For the `Node` at least, deriving `previous_yaw` from the existing basis would be a first step, but it is still susceptible to problems with (2), although as I say in the case close to `p_up` (or 180) it could simply not alter the basis at all (in which case the yaw would be preserved).

For `Basis` itself, it would be strictly speaking breaking compatibility as it would be relying on the current contents (although maybe this doesn't matter too much as previous behaviour is so broken). Also the case for (2) would have to be handled.

**Comment by TokageItLab** [comment]
In my thinking, the definition of the current yaw is ambiguous for Basis and Quaternion, so there is not much point in worrying about it.

For Node, however, the current direction is explicit, so in cases 1 and 2, a preliminary check before calling Basis.looking_at() could improve things before the warning in Basis is reached; For case 2, we can do not to rotate. Since the user has no control over the very small vectors that would introduce errors, it is better to do nothing than to make a rotation that depends on it. However, there should be nothing that can be done about case 3, i.e., the 180-degree rotation case.

**Comment by TokageItLab** [comment]
Also, this may be a niche case, but in cases where `looking_at()` is used to align yaw, it is necessary to be aware of the possibility that `looking_at()` may cause problems if the rotation is implicitly dependent on the previous yaw.

For example, if the bone orientation of a model loaded from an external source is used as it is, or if the orientation is different for each saved scene, there will be cases where the yaw will not match when `looking_at()` is used to match the rotation.

Given this, it appears that a warning is still required. In other words, since this needs to be handled by the user, I think a currently possible compromise is to provide a method for checking colinear case such as `Vector3.is_cololinear()` method and to write in the documentation how to prevent rotation with `looking_at()` on the user side; As similer idea with @lawnjelly said above:

> Another option to solve (2) is to not change the basis (as it is very close to up vector anyway), not report an error, but maybe return a false for success (in case the user wanted to act upon this).

**Comment by lawnjelly** [comment]
Actually I wrote all that, but I think I was getting my wires crossed on a previous similar issue, sorry for any confusion. :blush: 

If looking from a distant angle from up, the yaw should be preserved, and if looking from near zero, we can probably just not make the change.

File: core/math/basis.cpp (hunk 8 above)
Comment (TokageItLab) [reply core/math/basis.cpp:1053]: If look_at is called continuously, it may be spammed, but in that case it should not be called continuously in the first place, so spamming it is not considered excessive.

As mentioned in https://github.com/godotengine/godot/pull/100991#issuecomment-2569178136, if the orientation is nearly the same, the user should detect it and do nothing. Well, this could be add documentation or changing a warning text.

**Comment by Mickeon** [comment]
In the process of rebasing https://github.com/godotengine/godot/pull/87440, it is my understanding that the following is particularly misleading?

> The [param target] and the [param up] cannot be [constant Vector3.ZERO], and shouldn't be colinear to avoid unintended rotation around local Z axis.

First of all, it's "_collinear_".
Second, from what I can see, the original sentence was fine, as this is just a more mathematical way of saying "parallel to one other (regardless of direction)". There's little mentions of collinearity across all of Godot and doing it here makes it look more complicated than it is in practice.
Third, it's wrong, I think? `target` is a position vector and `up` is a direction vector. The **Node3D** version of the same method got this right:
> "and the direction from the node's position to the [param target] vector cannot be parallel to the [param up] vector."

Probably someone fixed this in the past, but it was not fixed in the other descriptions. This PR homogenised the inaccurate description.

**Comment by aaronfranke** [comment]
@Mickeon Correct, so for the Basis method, it makes more sense say the direction from the origin to the target should not be parallel to the up vector. That way we are talking about these vectors as both being lines, and we talk about them being parallel. The word collinear implies working with points, but 2 points always form a line.
