### PR TITLE
Fix script editor unexpected scroll upon resize

### LINKED ISSUE #55691: Script editor scrolls by itself when resizing any other stuff
### Godot version

ca2b0f6e776ed3e8898093caa9706c8e176fe406

### System information

Linux binogure 5.15.0-2-amd64 #1 SMP Debian 5.15.5-1 (2021-11-26) x86_64 GNU/Linux

### Issue description

bug-auto-scroll

### Steps to reproduce

- Launch Godot Engine
- Create a new script
- Type a very long script (can be anything)
- Resize any part of the editor

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by cdemirer**
Fixes #55691

PS: The root cause of this bug seems to be the discrepancy in `get_visible_line_count_in_range`, where it considers `p_to_line` either inclusive or exclusive depending on whether wrapping is enabled etc. This seems to cause confusion about what the callers of the function should expect for it to return. It might be a good idea to make it consistent, though it's out of the scope of this PR.

https://github.com/godotengine/godot/blob/e8082003f19ad8d98b6b2f74f64f4eaa7fe86353/scene/gui/text_edit.cpp#L4286-L4304

### CODE REVIEW

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -4226,7 +4226,10 @@ double TextEdit::get_scroll_pos_for_line(int p_line, int p_wrap_index) const {
 		return p_line;
 	}
 
-	double new_line_scroll_pos = get_visible_line_count_in_range(0, CLAMP(p_line, 0, text.size() - 1));
+	double new_line_scroll_pos = 0.0;
+	if (p_line > 0) {
+		new_line_scroll_pos = get_visible_line_count_in_range(0, CLAMP(p_line - 1, 0, text.size() - 1));
+	}
```
Comment (akien-mga) [inline scene/gui/text_edit.cpp:4232]: This makes the `CLAMP` redundant since `p_line - 1` can no longer be less than 0, so it should be `MIN(p_line - 1, text.size())`.

Comment (cdemirer) [reply scene/gui/text_edit.cpp]: Fixed :+1:

**Review by Paulb23 — CHANGES_REQUESTED** [review]
Interesting bug, looks to be a regression from #54462.

Comparing to the old code `get_scroll_pos_for_line` expects to count from `0` whereas the other methods that call `get_visible_line_count_in_range` expect to count from `1`. Making `get_scroll_pos_for_line` always off by `1`.

`get_visible_line_count_in_range` should be made consistent as it does break mouse clicking etc when both `wrapping` and `folding` is disabled. Then `get_scroll_pos_for_line` can take one to start from `0` which should fix this.

**Comment by cdemirer** [comment]
Ok I changed `get_visible_line_count_in_range` to consider `p_to_line` inclusive in both cases. It does seem to fix mouse clicking for that case.

File: scene/gui/text_edit.cpp [hunk 2]
```diff
@@ -4226,7 +4226,10 @@ double TextEdit::get_scroll_pos_for_line(int p_line, int p_wrap_index) const {
 		return p_line;
 	}
 
-	double new_line_scroll_pos = get_visible_line_count_in_range(0, CLAMP(p_line, 0, text.size() - 1));
+	double new_line_scroll_pos = 0.0;
+	if (p_line > 0) {
+		new_line_scroll_pos = get_visible_line_count_in_range(0, MIN(p_line - 1, text.size() - 1));
+	}
```
Comment (Paulb23) [inline scene/gui/text_edit.cpp:4232]: Should now be able to do:
```suggestion
	double new_line_scroll_pos = get_visible_line_count_in_range(0, CLAMP(p_line, 0, text.size() - 1)) - 1;
```

File: scene/gui/text_edit.cpp [hunk 3]
```diff
@@ -4290,7 +4293,7 @@ int TextEdit::get_visible_line_count_in_range(int p_from_line, int p_to_line) co
 
 	/* Returns the total number of (lines + wrapped - hidden). */
 	if (!_is_hiding_enabled() && get_line_wrapping_mode() == LineWrappingMode::LINE_WRAPPING_NONE) {
-		return p_to_line - p_from_line;
+		return p_to_line - p_from_line + 1;
```
Comment (Paulb23) [inline scene/gui/text_edit.cpp:4296]: Nit:
```suggestion
		return (p_to_line - p_from_line) + 1;
```

**Review by Paulb23 — CHANGES_REQUESTED** [review]

File: scene/gui/text_edit.cpp (hunk 2 above)
Comment (cdemirer) [reply scene/gui/text_edit.cpp:4232]: I think this doesn't work because `p_line`th line might be wrapped, increasing the return value by more than 1

**Comment by cdemirer** [comment]
Would it make sense to remove these lines from `get_scroll_pos_for_line`:
https://github.com/godotengine/godot/blob/e8082003f19ad8d98b6b2f74f64f4eaa7fe86353/scene/gui/text_edit.cpp#L4225-L4227
as the rest of the function will have the same behavior anyway?

File: scene/gui/text_edit.cpp (hunk 2 above)
Comment (Paulb23) [reply scene/gui/text_edit.cpp:4232]: Ahh I see, good spot. 

Probably for the best to keep as is, otherwise we'd have to fix too many other places.

**Review by Paulb23 — APPROVED** [review]

**Comment by Paulb23** [comment]
> Would it make sense to remove these lines from get_scroll_pos_for_line, as the rest of the function will have the same behavior anyway?

No, it's a short out for performance.

**Comment by akien-mga** [comment]
Thanks!
