### PR TITLE
Handle custom Callables in Thread.start()

### LINKED ISSUE #62584: "Can't get method on CallableCustom" when using Thread.start() on a lambda function
### Godot version

v4.0.alpha.custom_build [26dd4746a]

### System information

Windows 10

### Issue description

Calling a lambda function from `Thread.start()` throws an error becuase the thread fails to take the method name of the lambda in `Thread::_start_func()` (`core_binds.cpp` line 1823). 

Simple workaround is to use a regular function instead of a lambda function.

### Steps to reproduce

```
var t = Thread.new()
t.start(func thread_lambda(): print("thread started"))
```

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #62584

### CODE REVIEW

File: core/core_bind.cpp [hunk 1]
```diff
@@ -1840,13 +1840,14 @@ void Thread::_start_func(void *ud) {
 		ERR_FAIL_MSG(vformat("Could not call function '%s' on previously freed instance to start thread %s.", t->target_callable.get_method(), t->get_id()));
 	}
 
-	::Thread::set_name(t->target_callable.get_method());
+	String func_name = t->target_callable.is_custom() ? t->target_callable.get_custom()->get_as_text() : t->target_callable.get_method();
```
Comment (akien-mga) [inline core/core_bind.cpp:1843]:
```suggestion
	String func_name = t->target_callable.is_custom() ? t->target_callable.get_custom()->get_as_text() : String(t->target_callable.get_method());
```
```
core/core_bind.cpp:1843:52: error: conditional expression is ambiguous; 'String' can be converted to 'StringName' and vice versa
        String func_name = t->target_callable.is_custom() ? t->target_callable.get_custom()->get_as_text() : t->target_callable.get_method();
                                                          ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
