### PR TITLE
Fix SceneImportSettings perf issues

### LINKED ISSUE #68301: Import 3d model view lags when physics is ticked in Generate section.
### Godot version

4.0 b3 c#

### System information

Windows 10, Nvidia GTX 1660Ti, Vulkan

### Issue description

The 3d view of a model in the import window lags when you try to generate a collision mesh, depending on which method you use it seriously lags or just not so much (lots of frames dropped vs not many), if you view the model in the editor as part of a scene it doesn't cause any issues.

Trimesh works for me better (still dropping some frames), Decompose convex, Simple Convex work the worst so far.

### Steps to reproduce

Open the import window of a 3d model (use a model with more complex geometry if possible to make sure you get the issue in case a simpler model doesn't do the trick for you - I have no idea if it matters, for me I just have very low frame rates; or the test.glb in KayKit directory in the test project. don't try to run the project it might not work, just open it in godot and double click the test.glb file to open the import window), tick physics Generate section of a MeshInstance3D node you selected in the scene view, try to rotate around.

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/9944620/test.zip)

### PR DESCRIPTION
**Pull request by hcoura**
Scene Importer was generating collider mesh at every tick when `Physics` options was enabled, this makes it only do it when changing settings related to `INTERNAL_IMPORT_CATEGORY_MESH_3D_NODE`.

Honestly I am not 100% confident the actual implementation is how something like this would be done in the project but I couldn't find some clear pattern to replicate.

This closes https://github.com/godotengine/godot/issues/68301

### CODE REVIEW

File: editor/import/scene_import_settings.cpp [hunk 1]
```diff
@@ -530,6 +535,12 @@ void SceneImportSettings::_load_default_subresource_settings(HashMap<StringName,
 	}
 }
 
+void SceneImportSettings::set_generate_collider(ResourceImporterScene::InternalImportCategory &category) {
+	if (category == ResourceImporterScene::INTERNAL_IMPORT_CATEGORY_MESH_3D_NODE) {
+		generate_collider = true;
+	}
```
Comment (clayjohn) [inline editor/import/scene_import_settings.cpp:541]: I would move the if statement out of this function and rename the function ``request_generate_collider``

So it would be called like:
```
if (category == ResourceImporterScene::INTERNAL_IMPORT_CATEGORY_MESH_3D_NODE) {
    SceneImportSettings::get_singleton()->request_generate_collider();
}
```

To me that is more clear about what the function is doing, and it matches the pattern already used in ``_set()``

**Review by clayjohn — COMMENTED** [review]
I've left a suggestion that I think helps the codestyle/clarity. In terms of content, this change makes sense to me. We definitely do not want to be creating a collider every tick

File: editor/import/scene_import_settings.cpp (hunk 1 above)
Comment (hcoura) [reply editor/import/scene_import_settings.cpp:541]: Fair enough, let me make the change and resubmit

**Review by clayjohn — APPROVED** [review]
Looks fine to me, but I am not expert in the importer, so it would be nice to have a review from someone else more knowledgeable as well.

File: editor/import/scene_import_settings.cpp [hunk 2]
```diff
@@ -530,6 +537,10 @@ void SceneImportSettings::_load_default_subresource_settings(HashMap<StringName,
 	}
 }
 
+void SceneImportSettings::request_generate_collider(ResourceImporterScene::InternalImportCategory &category) {
```
Comment (akien-mga) [inline editor/import/scene_import_settings.cpp:540]: Why does this pass a category as argument if it isn't used?

Comment (hcoura) [reply editor/import/scene_import_settings.cpp]: Thanks for the catch, just cause when making a change Clay requested I forgot to remove the argument. Just fixed it

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
