### PR TITLE
Fix Editor crash when MeshLibrary gets replaced while used in an open Scene

### LINKED ISSUE #64393: Editor crashes when converting scene to a MeshLibrary while a scene using this library is open
### Godot version

3.5.stable.official

### System information

GLES2, Ubuntu 20.04.4 LTS, Windows 10

### Issue description

Editor crashes when converting scene to a MeshLibrary while a scene using this library is open.

Tested on:
- Ubuntu 20.04.4 LTS (NV138 / Mesa Intel® UHD Graphics 620 (KBL GT2))
- Windows 10 (Intel® HD Graphics 3000)

#### Backtrace
```
ERROR: Condition "!is_inside_tree()" is true. Returned: Transform()
   at: get_global_transform (scene/3d/spatial.cpp:407)
ERROR: Condition "!is_inside_world()" is true. Returned: Ref<World>()
   at: get_world (scene/3d/spatial.cpp:648)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v3.5.stable.official (991bb6ac74ac8c09d7683041b50a8ced3a2defb1)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7f9cb437c090] (??:0)
[2] /home/user/Downloads/Godot/godot() [0xf34a69] (??:0)
[3] /home/user/Downloads/Godot/godot() [0xf34c75] (??:0)
[4] /home/user/Downloads/Godot/godot() [0xabffd9] (??:0)
[5] /home/user/Downloads/Godot/godot() [0x2e6fd89] (??:0)
[6] /home/user/Downloads/Godot/godot() [0x334bef8] (??:0)
[7] /home/user/Downloads/Godot/godot() [0x2e7c6cc] (??:0)
[8] /home/user/Downloads/Godot/godot() [0x1fb61e1] (??:0)
[9] /home/user/Downloads/Godot/godot() [0xa97d03] (??:0)
[10] /home/user/Downloads/Godot/godot() [0x1774d80] (??:0)
[11] /home/user/Downloads/Godot/godot() [0x324ff4e] (??:0)
[12] /home/user/Downloads/Godot/godot() [0x1a7aa8d] (??:0)
[13] /home/user/Downloads/Godot/godot() [0x15ecf0f] (??:0)
[14] /home/user/Downloads/Godot/godot() [0xdd84d5] (??:0)
[15] /home/user/Downloads/Godot/godot() [0x2e6fd89] (??:0)
[16] /home/user/Downloads/Godot/godot() [0x2e7b14a] (??:0)
[17] /home/user/Downloads/Godot/godot() [0x152ee23] (??:0)
[18] /home/user/Downloads/Godot/godot() [0xabffd9] (??:0)
[19] /home/user/Downloads/Godot/godot() [0x2e6fd89] (??:0)
[20] /home/user/Downloads/Godot/godot() [0x2e7b14a] (??:0)
[21] /home/user/Downloads/Godot/godot() [0x205c58b] (??:0)
[22] /home/user/Downloads/Godot/godot() [0xabffd9] (??:0)
[23] /home/user/Downloads/Godot/godot() [0x2e6fd89] (??:0)
[24] /home/user/Downloads/Godot/godot() [0x2e7b14a] (??:0)
[25] /home/user/Downloads/Godot/godot() [0x20012ea] (??:0)
[26] /home/user/Downloads/Godot/godot() [0x20023b3] (??:0)
[27] /home/user/Downloads/Godot/godot() [0x20028ee] (??:0)
[28] /home/user/Downloads/Godot/godot() [0x179c895] (??:0)
[29] /home/user/Downloads/Godot/godot() [0x2e6f937] (??:0)
[30] /home/user/Downloads/Godot/godot() [0x2015381] (??:0)
[31] /home/user/Downloads/Godot/godot() [0x201ba21] (??:0)
[32] /home/user/Downloads/Godot/godot() [0x201dd25] (??:0)
[33] /home/user/Downloads/Godot/godot() [0x201dffb] (??:0)
[34] /home/user/Downloads/Godot/godot() [0xd08ad5] (??:0)
[35] /home/user/Downloads/Godot/godot() [0x2e6fd89] (??:0)
[36] /home/user/Downloads/Godot/godot() [0x2e61cbe] (??:0)
[37] /home/user/Downloads/Godot/godot() [0x1fb1a5b] (??:0)
[38] /home/user/Downloads/Godot/godot() [0x1fca810] (??:0)
[39] /home/user/Downloads/Godot/godot() [0xa40c0b] (??:0)
[40] /home/user/Downloads/Godot/godot() [0xa41e59] (??:0)
[41] /home/user/Downloads/Godot/godot() [0xa46f74] (??:0)
[42] /home/user/Downloads/Godot/godot() [0xa015dc] (??:0)
[43] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f9cb435d083] (??:0)
[44] /home/user/Downloads/Godot/godot() [0xa13fde] (??:0)
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

- Open a GridMap scene using a MeshLibrary
- Open a scene to be converted to a MeshLibrary
- Go to Scene > Convert To... > MeshLibrary... 
- Overwrite the MeshLibrary used by the GridMap

https://user-images.githubusercontent.com/19820741/184538744-fcb0bb3c-d472-4a66-acae-b56724343b04.mp4

### Minimal reproduction project

[meshlib-crash.zip](https://github.com/godotengine/godot/files/9333424/meshlib-crash.zip)

### PR DESCRIPTION
**Pull request by smix8**
Fixes #64393

Some functions are intended to be called inside the SceneTree so get_global_transform() and get_world() can work but this is not always the case when the scene is loaded in e.g. an Editor background tab. The MeshLibrary replacement is triggering a lot of them and while transform fails only polluted the error log the call to get_world() was a fatal error that crashed the Editor.

In Godot 4.x this is already guarded / handled slightly differently.

### CODE REVIEW

File: modules/gridmap/grid_map.cpp [hunk 1]
```diff
@@ -561,10 +561,12 @@ bool GridMap::_octant_update(const OctantKey &p_key) {
 				NavigationServer::get_singleton()->region_set_navigation_layers(region, navigation_layers);
 				NavigationServer::get_singleton()->region_set_navmesh(region, navmesh);
 				NavigationServer::get_singleton()->region_set_transform(region, get_global_transform() * nm.xform);
-				if (navigation) {
-					NavigationServer::get_singleton()->region_set_map(region, navigation->get_rid());
-				} else {
-					NavigationServer::get_singleton()->region_set_map(region, get_world()->get_navigation_map());
+				if (is_inside_tree()) {
```
Comment (DarkKilauea) [inline modules/gridmap/grid_map.cpp:564]: Do you need to protect all of this, or just the `NavigationServer::get_singleton()->region_set_map(region, get_world()->get_navigation_map());` call below?

Comment (smix8) [reply modules/gridmap/grid_map.cpp:564]: All to be more consistent with Godot 4 code and don't add a trap for the next time a line is added.

**Review by akien-mga — APPROVED** [review]

**Comment by timothyqiu** [comment]
Cherry-picked for 3.5.2
