### PR TITLE
Fix inherited scenes produce errors in editor when `editable_children` is true

### LINKED ISSUE #87424: Inherited scenes produce errors in editor when "editable_children" is true.
### Tested versions

Reproducible in mono 4.3.dev2

### System information

Windows 11 Intel(R) Core(TM) i7-12700H CPU @ 2.30GHz

### Issue description

When a base scene (containing at least one child) is inherited and the inherited scene is instanced inside of a parent scene and has 'editable_children' = true then saving the parent scene or selecting one of the editable children inside of this instanced node spams the output with this error:

image

This error does not happen when the base scene does not have any children.

Seems to happen regardless of node types.

### Steps to reproduce

1. Create a base scene and add at least 1 child node.
image
2. Create a new inherited scene from the base scene.
image
3. Create a new 'parent' scene and instance the inherited scene inside of it. Set the 'editable_children' of the instance to true.
image
4. Now either selecting the child node inside of the inherited instance or saving the parent scene will spam the previous error to the console.
image
image

### Minimal reproduction project (MRP)

[BugReportMRP.zip](https://github.com/godotengine/godot/files/13999604/BugReportMRP.zip)

### LINKED ISSUE #88258: Inheriting an inherited scene causes error on save: Index p_idx = X out of bounds
### Tested versions

- Reproducible in 4.3-dev3 [d3352813e]
- Reproducible in 4.3-dev2
- Not reproducible in 4.2

### System information

v4.3.dev.custom_build [d3352813e] 

### Issue description

When saving a scene that inherits from another inherited scene containing at least one child node, this error appears.
Screenshot 2024-02-12 at 10 23 25 PM

### Steps to reproduce

* Create a scene (scene_1)
* Add a child node
* Create an inherited scene from scene_1 (scene_2)
* Add a child node
* Create an inherited scene from scene_2 (scene_3)
* Save scene_3

### Minimal reproduction project (MRP)

[Archive.zip](https://github.com/godotengine/godot/files/14251512/Archive.zip)

### PR DESCRIPTION
**Pull request by Rindbee**
Since the same argument is used, `SceneState::get_node_deferred_nodepath_properties()` should use similar logic to `SceneState::get_property_value()`.

Fix #87424, fix #88258.

Make `SceneState::get_property_value()` to return whether the property is node deferred. This simplifies the logic in `PropertyUtils::get_property_default_value()`.

### CODE REVIEW

File: scene/resources/packed_scene.cpp [hunk 1]
```diff
@@ -1254,29 +1254,30 @@ int SceneState::_find_base_scene_node_remap_key(int p_idx) const {
 	return -1;
 }
 
-Variant SceneState::get_property_value(int p_node, const StringName &p_property, bool &found) const {
+Variant SceneState::get_property_value(int p_node, const StringName &p_property, bool &found, bool &node_deferred) const {
```
Comment (akien-mga) [inline scene/resources/packed_scene.cpp:1257]:
```suggestion
Variant SceneState::get_property_value(int p_node, const StringName &p_property, bool &r_found, bool &r_node_deferred) const {
```

File: scene/resources/packed_scene.cpp [hunk 2]
```diff
@@ -1666,13 +1667,24 @@ StringName SceneState::get_node_property_name(int p_idx, int p_prop) const {
...
+			if (idx & FLAG_PATH_PROPERTY_IS_NODE) {
+				ret.push_back(names[idx & FLAG_PROP_NAME_MASK]);
+			}
 		}
+		return ret;
 	}
+
+	// Property not found, try on instance.
+	if (base_scene_node_remap.has(p_idx)) {
+		return get_base_scene_state()->get_node_deferred_nodepath_properties(base_scene_node_remap[p_idx]);
```
Comment (KoBeWi) [inline scene/resources/packed_scene.cpp:1685]:
```suggestion
	HashMap<int, int>::ConstIterator I = base_scene_node_remap.find(p_idx);
	if (I) {
		return get_base_scene_state()->get_node_deferred_nodepath_properties(I->value);
```

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
