### PR TITLE
Fix TileMap layer loading

### LINKED ISSUE #53098: TileMap layers above 0 aren't loaded
### Godot version

73668c5

### System information

W10

### Issue description

When you have a TileMap with more than 1 layer, the additional layers are lost upon loading the scene. The layers are correctly saved in the scene, so it's some loading issue.

It's regression from #52277

### Steps to reproduce

1. Add TileMap
2. Add 1 or more additional layers
3. Save and reload the scene

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #53098

### CODE REVIEW

**Comment by KoBeWi** [comment]
Unfortunately this does not work. If you add any tiles, this is spammed in the console:
```
ERROR: Condition "p_elem->_root != this" is true.
   at: SelfList<struct TileMapQuadrant>::List::remove (C:\godot_source\core/templates/self_list.h:80)
```
Putting as draft for now.

File: scene/2d/tile_map.cpp [hunk 1]
```diff
@@ -2034,10 +2034,18 @@ bool TileMap::_set(const StringName &p_name, const Variant &p_value) {
...
+		if (index < 0) {
 			return false;
 		}
 
+		if (index >= (int)layers.size()) {
+			_clear_internals();
+			while (index >= (int)layers.size()) {
+				layers.push_back(TileMapLayer());
+			}
+			_recreate_internals();
```
Comment (groud) [inline scene/2d/tile_map.cpp:2046]: You also need to call `notify_property_list_changed()` as it changes the list of properties exposed by the TileMap.

**Review by groud — APPROVED** [review]

**Comment by groud** [comment]
Thanks!
