### PR TITLE
Pause physics command queue during physics processing

### LINKED ISSUE #94205: Physics running on separate thread with max fps enabled causes the physics server to be synchronized every frame when a collision happens
### Tested versions

- Tested in v4.3.beta3.official [82cedc83c]
- Does not happen in beta 2

### System information

Manjaro Linux - Godot v4.3.beta3 - Forward+

### Issue description

When `physics/2d/run_on_separate_thread` or `physics/3d/run_on_separate_thread` is enabled and `application/run/max_fps` is set to any value higher than zero in the project settings, moving a CharacterBody2D or a CharacterBody3D with `move_and_slide` will cause this warning to be printed in the console every time it collides with something:
```
Call to body_get_collision_layer causing PhysicsServer2D synchronizations on every frame. This significantly affects performance.
```

This does not happen if `physics/2d/run_on_separate_thread` is set to false and `application/run/max_fps` is set to something higher than zero or if `application/run/max_fps` is set to zero and `physics/2d/run_on_separate_thread` is set to true.

The warning is not printed in v4.3 beta 2.

### Steps to reproduce

* Go the Project Settings
  * Set *Application -> Run -> Max* fps to 60 (or any other number)
  * Set *Physics -> 2D -> Run on separate thread* and *Physics -> 3D -> Run on separate thread* to true.
* Create a scene with a CharacterBody2D or CharacterBody3D as root and add a collision shape.
  * Create a script attached to move the body using `move_and_slide`. This also happens with the built-in template.
  * Create a scene that contains the character that was just created and any other collider.

Running the project now will cause the warning to be printed every time there is a collision.

### Minimal reproduction project (MRP)

[issure-reproduction-project.zip](https://github.com/user-attachments/files/16174463/issure-reproduction-project.zip)

### LINKED ISSUE #109554: ShapeCast3D may crash engine with JoltPhysics
### Tested versions

- Reproducible in 4.5-beta5  
- Reproducible in 8aa37cab8950351d96f541581abdc42136283f24 (MSVC x86_64, latest)  

### System information

Godot v4.5.beta.mono (8aa37cab8) - Windows 11 (build 26100) - Multi-window, 4 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XTX (Advanced Micro Devices, Inc.; 32.0.21025.1024) - AMD Ryzen 9 3900X 12-Core Processor (24 threads) - 63.92 GiB memory

### Issue description

Jolt Physics may crash the engine upon/after collision checks of a shapecast  
In my "reproductive sample", it can take anywhere from seconds to minutes to occur, so it leads me to believe it's some kind of race-condition.

## Additional notes / files 

I'm sorry for the brief description
I'm still investigating the Issue myself, but am unsure if anything more comes up from my side.

In any case, I've included a crashdump, and a reproducible sample.  
The files are too big for GitHub, so they may only exist temporarily (please ping me when I can take them down)

[Crashdump](https://sharex.1-3-3-7.dev/godot_dump/crash.dmp) (Godot @ 8aa37cab8950351d96f541581abdc42136283f24 built with mono module and debug symbols)   

### Steps to reproduce

[Reproductive Sample](https://sharex.1-3-3-7.dev/godot_dump/sample.zip  )  
Instructions: 
1. Drive for a few seconds or minutes
2. Observe Crash

### Minimal reproduction project (MRP)

[Reproductive Sample](https://sharex.1-3-3-7.dev/godot_dump/sample.zip  )  
Instructions: 
1. Drive for a few seconds or minutes
2. Observe Crash

### PR DESCRIPTION
**Pull request by mihe**
Fixes #109554.

> [!WARNING]
> This change is a bit crude and will likely be a performance regression for some projects that rely on the `physics/*d/run_on_separate_thread` project setting, but I'm not sure how else to fix this race condition, other than to somehow introduce synchronization between `PhysicsServer*DWrapMT`, `PhysicsDirectSpaceState*D` and `PhysicsDirectBodyState*D`, which has its own complications/downsides.

What this does is make it so that `PhysicsServer*DWrapMT::sync` and `PhysicsServer*DWrapMT::end_sync` (called [here](https://github.com/godotengine/godot/blob/8aa37cab8950351d96f541581abdc42136283f24/main/main.cpp#L4738) and [here](https://github.com/godotengine/godot/blob/8aa37cab8950351d96f541581abdc42136283f24/main/main.cpp#L4777) in the main loop) actually "pauses" and "unpauses" the asynchronous processing of commands in the command queue of `PhysicsServer*DWrapMT`, thereby ~~effectively disabling `physics/*d/run_on_separate_thread` during the physics processing part of the main loop~~.

EDIT: It's probably more fair to say that we are _deferring_ `physics/*d/run_on_separate_thread` with this change now, since we're still offloading non-read/non-sync tasks to the physics thread, but until after the physics processing is done.

This would mean that we resolve the (apparently long-standing) race conditions between `PhysicsServer*DWrapMT::_thread_loop` and `PhysicsDirectSpaceState*D` (and `PhysicsDirectBodyState*D` as well) while preserving the ability for users to freely perform physics queries in parallel as much as they want[^1] from any thread[^2] when `physics/*d/run_on_separate_thread` is enabled.

Note however that much of the benefit from `physics/*d/run_on_separate_thread` comes from doing the actual physics step asynchronously, which would still be the case, as that happens after `PhysicsServer*DWrapMT::end_sync`.

[^1]: Only as long as it's done during physics processing, but this is already being enforced [here](https://github.com/godotengine/godot/blob/8aa37cab8950351d96f541581abdc42136283f24/modules/godot_physics_3d/godot_physics_server_3d.cpp#L194), albeit not very rigorously.
[^2]: You're technically only allowed to fetch `PhysicsDirectSpaceState*D` from the main thread, as seen [here](https://github.com/godotengine/godot/blob/8aa37cab8950351d96f541581abdc42136283f24/servers/physics_server_3d_wrap_mt.h#L115), but there's nothing stopping you from caching the instance and using it from multiple threads, which should be fine for that class specifically, since physics queries should (at least in theory) all be read-only.

### CODE REVIEW

**Comment by mihe** [comment]
I'm realizing now that there's one other potential problem with this change.

If you're calling methods on `PhysicsServer*D` from a thread other than the main thread during physics processing, you will now just queue up those operations endlessly until the physics command queue has resumed its processing. This could maybe lead to out-of-memory scenarios.

We also never shrink the allocated size of that queue, so if that other thread was doing a ton of physics operations one frame then you'll be stuck with that allocated memory for the rest of the program's lifetime.

**Comment by lawnjelly** [comment]
> If you're calling methods on PhysicsServer*D from a thread other than the main thread during physics processing, you will now just queue up those operations endlessly until the physics command queue has resumed its processing. This could maybe lead to out-of-memory scenarios.

This is surely just a cost of using the queues to deal with multithreading. I don't think it's unreasonable for any queue to contain a frame / ticks worth of commands. The emphasis should be on keeping the commands compact for this reason.

Maybe there's some specific situation you were thinking of?

Essentially imo the need to prevent race conditions is more important than the need to conserve memory, unless there is some specific that precludes this.

**Comment by mihe** [comment]
> This is surely just a cost of using the queues to deal with multithreading. I don't think it's unreasonable for any queue to contain a frame / ticks worth of commands. The emphasis should be on keeping the commands compact for this reason.

Yeah, actually, thinking about this some more, you likely run into this exact problem with non-main threads when `physics/*d/run_on_separate_thread` is left at its default of `false` anyway, since those commands would only ever get flushed at `PhysicsServer*DWrapMT::sync`, so nevermind I guess.

**Comment by mihe** [comment]
I should point out one potential "optimization" to this PR, which is that the macros in `server_wrap_mt_common.h` that call `CommandQueueMT::push` don't need the same `ASYNC_COMMAND_COND` that the synchronizing macros do, meaning the ones that call `CommandQueueMT::push_and_ret` and `CommandQueueMT::push_and_sync`.

Changing the `CommandQueueMT::push` macros to instead queue the commands like normal would mean that you could theoretically still get the benefit of deferring those costs to the physics thread (i.e. after `PhysicsServer*DWrapMT::end_sync` is called).

The "problem" with this optimization is that the synchronizing macros then become a serious performance footgun, since we're still forced to flush the queue (on the main thread) when any of those methods are called, in order to keep the order of operations. So just adding a single `CharacterBody3D` with its default template script could mean that its `move_and_slide` call ends up being very expensive indeed (because of its call to `PhysicsServer3D::body_get_collision_layer`) depending on how many commands were deferred until that call. So this would essentially be another manifestation of #94205, albeit potentially much worse, since we wouldn't have the benefit of a physics thread that can process some of the commands before the flush/synchronization happens.

So I figured it's better to just execute everything on the main thread immediately during physics processing, to have more predictable performance.

**Comment by mihe** [comment]
> So this would essentially be another manifestation of #94205, albeit potentially much worse, since we wouldn't have the benefit of a physics thread that can process some of the commands before the flush/synchronization happens.

After thinking about this some more, this is a weak argument against this optimization, since the usage of `PhysicsServer3D::body_get_collision_layer` in `move_and_slide` shouldn't be happening in the first place.

I've gone ahead and pushed this optimization after all, which should hopefully make the performance impact of this PR less noticeable. I've also pushed a separate PR (#109607) to fix #94205 properly, which means `move_and_slide` shouldn't cause any more problems with `physics/*d/run_on_separate_thread`.

File: servers/physics_server_2d_wrap_mt.h [hunk 1]
```diff
@@ -35,6 +35,10 @@
 #include "core/templates/command_queue_mt.h"
 #include "servers/physics_server_2d.h"
 
+#define ASYNC_COND_PUSH Thread::get_caller_id() != server_thread
+#define ASYNC_COND_PUSH_AND_RET Thread::get_caller_id() != server_thread && !(doing_sync.is_set() && Thread::is_main_thread())
+#define ASYNC_COND_PUSH_AND_SYNC Thread::get_caller_id() != server_thread && !(doing_sync.is_set() && Thread::is_main_thread())
```
Comment (AThousandShips) [inline servers/physics_server_2d_wrap_mt.h]:
```suggestion
#define ASYNC_COND_PUSH (Thread::get_caller_id() != server_thread)
#define ASYNC_COND_PUSH_AND_RET (Thread::get_caller_id() != server_thread && !(doing_sync.is_set() && Thread::is_main_thread()))
#define ASYNC_COND_PUSH_AND_SYNC (Thread::get_caller_id() != server_thread && !(doing_sync.is_set() && Thread::is_main_thread()))
```
To ensure there's no unforeseen consequences of using this in other contexts

File: servers/physics_server_3d_wrap_mt.h [hunk 2]
```diff
@@ -36,6 +36,10 @@
 #include "core/templates/command_queue_mt.h"
 #include "servers/physics_server_3d.h"
 
+#define ASYNC_COND_PUSH Thread::get_caller_id() != server_thread
+#define ASYNC_COND_PUSH_AND_RET Thread::get_caller_id() != server_thread && !(doing_sync.is_set() && Thread::is_main_thread())
+#define ASYNC_COND_PUSH_AND_SYNC Thread::get_caller_id() != server_thread && !(doing_sync.is_set() && Thread::is_main_thread())
```
Comment (AThousandShips) [inline servers/physics_server_3d_wrap_mt.h]:
```suggestion
#define ASYNC_COND_PUSH (Thread::get_caller_id() != server_thread)
#define ASYNC_COND_PUSH_AND_RET (Thread::get_caller_id() != server_thread && !(doing_sync.is_set() && Thread::is_main_thread()))
#define ASYNC_COND_PUSH_AND_SYNC (Thread::get_caller_id() != server_thread && !(doing_sync.is_set() && Thread::is_main_thread()))
```

File: servers/rendering/rendering_server_default.h [hunk 3]
```diff
@@ -109,6 +109,9 @@ class RenderingServerDefault : public RenderingServer {
 #endif
 
 #define WRITE_ACTION redraw_request();
+#define ASYNC_COND_PUSH Thread::get_caller_id() != server_thread
+#define ASYNC_COND_PUSH_AND_RET Thread::get_caller_id() != server_thread
+#define ASYNC_COND_PUSH_AND_SYNC Thread::get_caller_id() != server_thread
```
Comment (AThousandShips) [inline servers/rendering/rendering_server_default.h]:
```suggestion
#define ASYNC_COND_PUSH (Thread::get_caller_id() != server_thread)
#define ASYNC_COND_PUSH_AND_RET (Thread::get_caller_id() != server_thread)
#define ASYNC_COND_PUSH_AND_SYNC (Thread::get_caller_id() != server_thread)
```

**Review by smix8 — APPROVED** [review]
Approve to ship a version with 4.5 that does not crash with multithreading and Jolt but to be clear, this can only be a stopgap solution as this is closer to a hack than a fix.

This is not mihe or Jolt's fault. The PhysicsServer and related physics nodes always had major problems with multithreading. The physics system design is fundamentally flawed for threading in Godot. (e.g. allowing internal node calls to force sync and lock the server is a major design flaw as nodes should have zero say what and when the server does anything).

I remember in old Godot there was even a big warning on the physics threading setting to never use it in production but for some reason it was removed without anything fixed.

The physics threading problems are basically the original NavigationServer threading disaster all over (because the original NavigationServer copied the PhysicsServer design) just in different context, with more users and even worse exposed API functions on server and nodes (e.g. only look at the CharacterBody code when you are not already depressed or prone to violent outbursts).

**Comment by mihe** [comment]
> this can only be a stopgap solution as this is closer to a hack than a fix

Just to be clear, since I didn't add this to the PR description since my last push, we are still offloading non-read/non-sync tasks to the physics thread with this approach, but now they're instead deferred until the end of the physics processing. So me saying that we are now "effectively disabling `physics/*d/run_on_separate_thread` during the physics processing part of the main loop" is not entirely true.

Seeing as how much of the physics cost comes from the state synchronization (i.e. `flush_queries`) and the physics step, neither of which are affected by this change, I wouldn't expect *that* much of a performance impact from this. It's only if you're doing expensive (or many) physics server calls, like changing the shape data of complex collision shapes, that I would expect to see an impact, since we're now taking away a slice of the frame for the physics thread to do its thing.

So while this PR is still a bit heavy-handed in its approach, I wouldn't necessarily consider it an urgent code smell to get rid off, but perhaps I'll be proven wrong by some future issue reports.

**Comment by Repiteo** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Will have to test further but it seems that this broke physics on Web in no threads mode, will investigate after the weekend and make a report (might have been https://github.com/godotengine/godot/pull/109607, will bisect later)

Edit: My bad was not related to this, will continue looking
