### PR TITLE
Fix crash when trying to export zero files.

### LINKED ISSUE #43145: Editor crashes if you try to export with `*` as exclude filter.
**Godot version:**
3.2.3

**OS/device including version:**
```
$ uname -a
Linux pc 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
```

**Issue description:**
The editor crashes if you set "Filters to exclude files/folders from project" to `*` while also having a resource selected.

**Steps to reproduce:**
crash

**Minimal reproduction project:**
[export_crash.zip](https://github.com/godotengine/godot/files/5447785/export_crash.zip)

### PR DESCRIPTION
**Pull request by mujpao**
Fixes crash that happened while exporting if zero files were selected and adds more error handling to EditorExportPlatform class.

Fixes #43145

### CODE REVIEW

File: editor/editor_export.cpp [hunk 1]
```diff
@@ -918,14 +930,21 @@ Error EditorExportPlatform::export_project_files(const Ref<EditorExportPreset> &
 				} else {
 					export_plugins.write[i]->_export_file(path, type, features);
 				}
+				err = OK;
```
Comment (akien-mga) [inline editor/editor_export.cpp:933]: This doesn't seem useful, I don't see any check for `err != OK` in this loop which would not have an assignment to `err` before it.

**Review by akien-mga — APPROVED** [review]
Left one comment, otherwise seems good to me.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
