### PR TITLE
Fix animation track inserted path and key type

### LINKED ISSUE #99115: Animation Player keyframes unable to handle sub-properties (e.g. position:x vs. position); incorrect data type is applied.
### Tested versions

Reproducible in:
- v4.4.dev4.mono.official [36e6207bb]
- v4.4.dev4.official [36e6207bb]
- **v4.4.dev3.official [f4af8201b]**
Not Reproducible in:
- v4.4.dev2.official [97ef3c837]
- v4.4.dev1.official [28a72fa43]
- v4.3.stable.mono.official [77dcf97d8]

### System information

Godot v4.4.dev3 - Windows 10.0.19045 - Multi-window, 3 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 32.0.15.6603) - AMD Ryzen 7 5800X 8-Core Processor (16 threads)

## Expected
Setting a keyframe for, say, `position:x` lays down a `float` keyframe.
**(v4.4.dev2.official [97ef3c837])**
image

## Problem
The keyframe incorrectly sets itself as a `Vector2`.
**(v4.4.dev3.official [f4af8201b])**
image

## Imported Projects
When importing projects created in previous versions, their keyframes appear to still hold their original data, as seen in the mouseover, though this is not reflected in the Inspector:
image

Playing the Animation in this situation does seem to work (I tested with two keyframes after the screenshot), but editing any keyframe's value at all immediately renders said keyframe useless.

### Steps to reproduce

1. Open MRP
2. Examine the two keyframes of the AnimationPlayer in the Inspector.
3. Confirm that the two are Vector2-type keyframes, both with a value of `Vector2.ZERO`

(The values of the keyframes in the MRP **should** instead be: **419.0**, and **500.0**, respectively.)

### Minimal reproduction project (MRP)

[animation-player-test.zip](https://github.com/user-attachments/files/17715578/animation-player-test.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
- Closes https://github.com/godotengine/godot/issues/99115
- Supersedes/Closes https://github.com/godotengine/godot/pull/106580

There are two issues with the current AnimationTrackEditor.

- The key type is incorrect
- The insertion path for the Bezier track is incorrect

To solve them:

- Adopt @YuriSizov 's suggestion regarding the acquisition of properties when inserting keys
- As with PR #106580, partially revert https://github.com/godotengine/godot/pull/96789
- Add a hack to prevent Bezier track try parsing sub-properties since in that case, the property variant always becomes a Nil, so we will use that. Since Bezier tracks do not display properties other than numerical properties in the property selection screen, this should not be a problem

### CODE REVIEW

File: editor/animation_track_editor.cpp [hunk 1]
```diff
@@ -4463,17 +4463,12 @@ void AnimationTrackEditor::insert_node_value_key(Node *p_node, const String &p_p
...
-			Object *obj = value;
-			value = obj->get(E);
-		} else {
-			value = Variant();
-			break;
-		}
+	Vector<String> subpath = p_property.split(":");
+	Vector<StringName> subpath_names;
+	for (const String &s : subpath) {
+		subpath_names.push_back(s);
```
Comment (YuriSizov) [inline editor/animation_track_editor.cpp]: I think the `p_property` string can be converted to `NodePath` and then these subpaths can be extracted with

```
Vector<StringName> subpath_names = p_property_path.get_as_property_path().get_subnames();
```

**Review by SaracenOne — APPROVED** [review]
Thanks! Yes, I think this does indeed address the problems with my previous effort. I've closed the original and would recommend merging this now. 👍

**Comment by akien-mga** [comment]
Thanks!
