### PR TITLE
GDExtension: Show warning on missing PDB file, rather than error

### LINKED ISSUE #96350: PBD renaming functionality assumes file is present when it shouldn't
### Tested versions

Since: https://github.com/godotengine/godot/commit/e73f40e26067cf265e311bbb895b80853574cd93

### System information

N/A

### Issue description

In short, https://github.com/godotengine/godot/pull/87117 makes the assumption mentioned in the title resulting in error like this, which is now possible after this PR https://github.com/godotengine/godot/pull/93972: 
image

See comments here for details: https://github.com/godotengine/godot/pull/93972#issuecomment-2321833260

image

### Steps to reproduce

Build: https://github.com/godotengine/godot/commit/f0ee0bdd376c7d32adb83754e4ae5899dba37f91
Add a plugin like Godot-Jolt that has an entry for PBD in the header (may have to build this for 4.4)
Make sure .godot folder is deleted
Open the project

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by dsnopek**
Fixes https://github.com/godotengine/godot/issues/96350

Marking as a draft for now, because I haven't had a chance to test it yet (since Windows isn't my main development platform).

### CODE REVIEW

**Comment by mihe** [comment]
I just tested this and can confirm that it works as intended.

**Comment by dsnopek** [comment]
@mihe Thanks!

Taking out of draft based on mihe's testing :-)

File: platform/windows/windows_utils.cpp [hunk 1]
```diff
@@ -155,7 +155,11 @@ Error WindowsUtils::copy_and_rename_pdb(const String &p_dll_path) {
 	} else if (!FileAccess::exists(copy_pdb_path)) {
 		copy_pdb_path = dll_base_dir.path_join(copy_pdb_path.get_file());
 	}
-	ERR_FAIL_COND_V_MSG(!FileAccess::exists(copy_pdb_path), FAILED, vformat("File '%s' does not exist.", copy_pdb_path));
+	if (!FileAccess::exists(copy_pdb_path)) {
+		// The PDB file may be distributed separately on purpose, so we don't consider this an error.
+		WARN_VERBOSE(vformat("File '%s' does not exist.", copy_pdb_path));
```
Comment (mihe) [inline platform/windows/windows_utils.cpp:160]: I would maybe go so far as to say that this shouldn't even be emitted as a verbose warning, since there isn't really anything particularly weird or erroneous happening, but given the amount of noise in the `--verbose` output already I'm not sure there's much harm in it.

Perhaps some more context could be given at least, since there's none given when you return `ERR_SKIP`:

```suggestion
		WARN_VERBOSE(vformat("PDB file '%s' for library '%s' was not found, skipping copy/rename.", copy_pdb_path, p_dll_path));
```

**Review by mihe — APPROVED** [review]

File: platform/windows/windows_utils.cpp (hunk 1 above)
Comment (dsnopek) [reply platform/windows/windows_utils.cpp]: I like having the verbose message, in case we ever need to debug something going wrong with the PDB copying.

However, I agree about adding some more context! I've updated the message for your suggestion in my latest push

**Review by ryevdokimov — APPROVED** [review]
Works for me.

After https://github.com/godotengine/godot/pull/93972, https://github.com/godotengine/godot/pull/92667, and this PR I can finally gitignore the .godot folder and have my project startup without errors or having to restart!

**Review by Hilderin — APPROVED** [review]
Sounds good to me! Thanks!

**Comment by akien-mga** [comment]
Thanks!
