### PR TITLE
[3.x] Add a node configuration warning using NinePatchRect's Tile or Tile Fit modes in GLES2

### LINKED ISSUE #52708: Add a node configuration warning when using NinePatchRect's Tile or Tile Fit modes in GLES2
### Godot version

3.3.3

### System information

Mac Os 10.13.6 

### Issue description

The options "Tile" and "Tile Fit" of NinePatchRect are without effect. The result is always stretched.

### Steps to reproduce

Create a NinePatchRect node, load a texture, define the margin an test the different options.
Bildschirmfoto 2021-09-15 um 17 40 47

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by jmb462**
Fix #52708

### Issue fixed :

The options "Tile" and "Tile Fit" of NinePatchRect are without effect with GLES2 driver but there isn't any node configuration warning.

### Fix proposal

Add a node configuration warning when using one of these modes with GLES2 driver.

image

### Notes
As it's the first time I use NodeConfigurationWarning, I'm not sure about some points : 

- I only check ``ProjectSettings::get_singleton()->get("rendering/quality/driver/driver_name")`` but not the fallback_to_gles2 to avoid false positive warning.

(fixed) - When modifying the Tile mode, warning icon update only if we click outside the inspector. Don't know if it's the attented behavior or if I need to call an update function.

- As it's the only warning for that node, not sure that this test is needed (seems to be used in other nodes warning) 
```
	if (!warning.empty()) {
				warning += "\n\n";
			}```

### CODE REVIEW

**Comment by Calinou** [comment]
> When modifying the Tile mode, warning icon update only if we click outside the inspector. Don't know if it's the attented behavior or if I need to call an update function.

Call `update_configuration_warning()` within the `set_tile_mode()` functions (after the property itself has been set).

**Comment by jmb462** [comment]
> To resolve this, call `update_configuration_warning()` within the `set_tile_mode()` functions (after the property itself has been set).

Thanks. I've added the update calls.

File: scene/gui/nine_patch_rect.cpp [hunk 1]
```diff
@@ -165,13 +166,29 @@ NinePatchRect::AxisStretchMode NinePatchRect::get_h_axis_stretch_mode() const {
...
 }
 
 NinePatchRect::AxisStretchMode NinePatchRect::get_v_axis_stretch_mode() const {
 	return axis_v;
 }
 
+String NinePatchRect::get_configuration_warning() const {
+	String warning = Control::get_configuration_warning();
+
+	if (ProjectSettings::get_singleton()->get("rendering/quality/driver/driver_name") == "GLES2") {
```
Comment (Calinou) [inline scene/gui/nine_patch_rect.cpp:180]:
```suggestion
	if (String(GLOBAL_GET("rendering/quality/driver/driver_name")) == "GLES2") {
```

File: scene/gui/nine_patch_rect.cpp [hunk 2]
```diff
@@ -165,13 +166,29 @@ NinePatchRect::AxisStretchMode NinePatchRect::get_h_axis_stretch_mode() const {
...
+		if (axis_v > AXIS_STRETCH_MODE_STRETCH || axis_h > AXIS_STRETCH_MODE_STRETCH) {
+			if (!warning.empty()) {
+				warning += "\n\n";
+			}
+			warning += TTR("The Tile and Tile Fit options for Axis Stretch properties are only effective when using the GLES3 rendering backend.");
```
Comment (Calinou) [inline scene/gui/nine_patch_rect.cpp:185]:
```suggestion
			warning += TTR("The Tile and Tile Fit options for Axis Stretch properties are only effective when using the GLES3 rendering backend.\nThe GLES2 backend is currently in use, so these modes will act like Stretch instead.");
```

**Review by Calinou — CHANGES_REQUESTED** [review]

File: scene/gui/nine_patch_rect.cpp (hunk 2 above)
Comment (jmb462) [reply scene/gui/nine_patch_rect.cpp]: Thanks. Requested changes done.

**Review by Calinou — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
