### PR TITLE
Fix: InputEventJoypadMotion should trigger only once on a vslider

### LINKED ISSUE #4911: InputEventJoypadMotion should have the same behaviour as the keyboard
### Describe the project you are working on

Hi all, 

I'm creating a 2D platform with gamepad support. The user should be able to navigate and set value both with the D-PAD and the joystick.

In the futur, I also want to allow a custom mapping of the UI input (changing left/right joystick, mapping D-PAD function to other button), to allow a full custom experience for user with motion restriction. 

### Describe the problem or limitation you are having in your project

When creating the settings page for my game, I discover the following issue 

`if you map ui_left and ui_left with the left joystick of a controller (xbox one in this case), when using a hslider, the on changed value event will be trigged multiples times.`

see [issue](https://github.com/godotengine/godot/issues/62932)

https://user-images.githubusercontent.com/1162446/179619567-74eec9dc-280c-49b7-a5d6-5ee359dc9af3.mp4

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

- If we quickly move the axis to the left or right, it should only increment by one step
- If we held the stick to the left or right, it should increment the step until we unheld the stick (could be easier for user with motion issue)

To quote Calinou

"Ideally, sliders should behave like this with both keyboard and gamepad input. Thanks to the operating system, keyboards will automatically provide echo events, but gamepads don't provide echo events for their buttons or axes. Therefore, this behavior needs to be manually implemented for gamepad input.

I suggest using a delay of 0.5 seconds and a repeat rate of 20 repeats/second, similar to Windows' default rate for repeating keyboard input. This delay and repeat rate should be adjustable with project settings for accessibility reasons as well."

https://user-images.githubusercontent.com/1162446/179620753-882a8ddc-0702-49e4-a0ef-e063ab5bc394.mp4

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I would create a Timer in slider.cpp, detect when the joystick is pressed and start a timer. 
- After .5 seconds, I would repeat the step action at a rate of 20 repeats/second, similar to Windows
- This delay and repeat rate should be adjustable with project settings for accessibility reasons as well

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Slider are pretty common in UI, and to propose a full gamepad support, it seems like a good advantage to make it works out of the box

### Is there a reason why this should be core and not an add-on in the asset library?

It directly impact one of the main node

### LINKED ISSUE #62932: InputEventJoypadMotion will trigger multiples on_value_changed with hslider
### Godot version

3.4.4 (and 3.3.4, 3.5-rc6)

### System information

Windows 10

### Issue description

Hi all, 
If you map `ui_left `and `ui_left` with the left joystick of a controller (xbox one in this case), when using a hslider, the on changed value event will be trigged multiples times. 

image

e.g. a hslider with a step of 5%, with the stick, the value increase randomly from 10% to 20%, while using the direction cross will only trigger a 5% step.

https://user-images.githubusercontent.com/1162446/178392471-b41b5954-1482-45d8-adf1-8ad2027e1635.mp4

I think InputEventJoypadMotion should only be trigger once to match industry standard.

If this isn't a duplicate, I would be interested to take a look and create a PR if this is a good "first issue".

Thanks

### Steps to reproduce

1 - Create a minimal project with a hslider
2 - Remap ui_left, ui_right to the left joystick
image
3 - Create a hslider
4 - Change the value with the joystick

### Minimal reproduction project

[hslider_issue.zip](https://github.com/godotengine/godot/files/9088786/hslider_issue.zip)

### PR DESCRIPTION
**Pull request by Levrault**
Fixes #62932
Closes https://github.com/godotengine/godot-proposals/issues/4911

Both slider and popup_menu has been modified to support joypad motion.

https://user-images.githubusercontent.com/1162446/217901269-05cfddb6-b205-49a2-be84-398d1be1d2b4.mp4

### CODE REVIEW

**Comment by Levrault** [comment]
It could also be backported to 3.x. Was tested on both 4.0, 3.4 and 3.5

**Comment by Levrault** [comment]
PR has been updated to match my proposal https://github.com/godotengine/godot-proposals/issues/4911

**Comment by univeous** [comment]
I suggest renaming `default_slider_repeating_rate` to `default_joypad_motion_repeating_rate` 
and `default_slider_delay_timer`to `default_joypad_motion_delay` ,
and apply these changes to all control nodes that change UI focus in their `_gui_input`. 
They are ItemList, PopupMenu, RichTextLabel, ScrollBar, Slider and Tree. I'm not sure if CodeEdit needs this.
Then it will fix #71918, #35751 and other issues that I have not found or have not yet raised.

It can also be applied to Viewport to make UI focus change with common control nodes benefit too.

**Comment by Levrault** [comment]
@univeous I updated my PR to add slider, pop_menu, item_list, tree and rich text label.

But I'm pretty much stock about the Viewport. I'm pretty confuse about how the viewport manage the focus and pass it to the selected node. It seems to conflict with the timer and node position.

It also create some issue with item_list and tree. If I focus out and re-focus on the item, echoing and the whole direction with the gamepad broke. A quick workaround could be simply to ignore those control and only applied the fix on slider, popup_menu and rich text label.

https://user-images.githubusercontent.com/1162446/216380927-8c585de7-8639-463c-b64e-f65243d64754.mp4
https://user-images.githubusercontent.com/1162446/216381030-cf164a78-a339-4852-9a88-6fbd5d79449a.mp4

I also saw the following issue, if we focus on a rich_text_label, we can't focus out (both keyboard and gamepad). I will create an issue for that.

The test project can be download right here https://github.com/Levrault/joypad-motion-echo

**Comment by univeous** [comment]
Sorry I haven't gone through your implementation in detail, but I feel that instead of implementing similar logic in every gui node, it might be better to implement a helper function in the Input class somehow, or implement echo event for joypad motion input. It might be harder to implement though. 
Maybe we should call more people to join the conversation. CC @groud @EricEzaM

**Comment by groud** [comment]
First of all, thanks for working on that!

I don't feel like the implementation is right though. Echo events aren't really meant for handling, like, "continuous pressing" of a given key. TBH, I don't think echo events are very useful nowadays. They kind of make sense for moving a text cursor, for, like, compatibility with the fact the OS asks us to handle the event. However,  they could also be very easily replaced by a check to `is_action_pressed(...)` in the `process` function (in our situation), which in general provide a lot more customizable behavior than relying on how often, and after which delay, the OS sends us the echo events.

As a consequence, I don't think that this implementation is perfect, as i don't think it should emulate echo events out of joypad events. It makes things more complex than things need to be, and creates an additional constraint for little gain. Instead, I believe each control should check themselves the status of each ui_left/right... actions in their `process` function. It might make use of some helper function if you need to, though I am not sure it's needed. Overall it would likely simplify the implementation by avoiding to rely on those crafted fake events.

**Comment by Levrault** [comment]
@groud  checking `Input.is_action_pressed` in the `_process` function seems way more cleaner but delay and repeat reate should be keep in some specific case scenario like the slider.

e.g.
```
Slider: Min value is 0, max value is 100, the value is increment by 5 each times. The default value is 100.

1- The user move his left joystick to the left
2- `gui_input` catch the input and decrement the value to 95
3- The user keep his left joystick to the left
4- After 20 frames, we decrement the value to 90 
5- The user keep his left joystick to the left
6 - After 10 frames, we decrement the value to 85, 80 until the user stop using the left joystick.
```
This is the default slider behavior in many games and we should tried to archieve it. I also think supporting it out-of-the-box should be great for the user like @BlooRabbit said in https://github.com/godotengine/godot/issues/71918#issuecomment-1416416679 and https://github.com/godotengine/godot/issues/62932

But others controls like the popup_menu, item list, tree, could only have simple repeat rate. We re-call the gui_input function every X frames to seems if the Input is still pressed. And incremental repeat rate doesn't seems necessary for those nodes.

I just need some leads about how it should be implemented. Instead of timer, I think and repeat rate at each X frames could be cleaner. Maybe directly re-calling `gui_input` in the process function could be cleaner and prevent code duplication, but I don't know if it's possible. 

Also having a more contextual incremental behavior by control could be the best way to help our user and their futurs users.

**Comment by Calinou** [comment]
> I just need some leads about how it should be implemented. Instead of timer, I think and repeat rate at each X frames could be cleaner.

Repeat speed should not depend on rendering or physics FPS.

**Comment by groud** [comment]
> @groud checking Input.is_action_pressed in the _process function seems way more cleaner but delay and repeat reate should be keep in some specific case scenario like the slider.

Yeah you are right. The way it can be implemented is not that complex though:
- In the gui_input handler, handle the event like it used to be before (a single time, with a predetermined step value).
- In the process function, start some sort of a timer (that resets when you are not pressing the action). Then, after a given delay, move the slider by `step_value * delta * step_per_second_factor`. 

The timer does not need to be a Timer node/scene tree Timer btw, you can just store a "started pressing" time and check the difference with the current time. It would be lighter than using a node.

**Comment by KoBeWi** [comment]
Not sure if enabling process for many GUI nodes is a good idea (unless they have that already?). It should probably get enabled with key press and disabled with release.

**Comment by KoBeWi** [comment]
> I don't know if this could interfer if an user use _process for something specific.

This should use internal process, to not interfere with user code.

File: scene/gui/popup_menu.cpp [hunk 1]
```diff
@@ -888,6 +905,87 @@ void PopupMenu::_notification(int p_what) {
...
+
+			if (input->is_action_just_released("ui_left") || input->is_action_just_released("ui_right") || input->is_action_just_released("ui_up") || input->is_action_just_released("ui_down")) {
+				gamepad_event_delay_ms = DEFAULT_GAMEPAD_EVENT_DELAY_MS;
+				set_process_internal(true);
+				return;
+			}
+
+			gamepad_event_delay_ms -= get_process_delta_time();
+			if (gamepad_event_delay_ms < 0) {
+				gamepad_event_delay_ms = gamepad_event_repeat_rate_ms;
```
Comment (groud) [inline scene/gui/popup_menu.cpp:919]: Theoretically, if you want a better consistent rate, you should probably use `gamepad_event_delay_ms = gamepad_event_repeat_rate_ms + gamepad_event_delay_ms;`.

File: scene/gui/slider.cpp [hunk 2]
```diff
@@ -163,6 +191,41 @@ void Slider::_update_theme_item_cache() {
...
+
+			if (input->is_action_just_released("ui_left") || input->is_action_just_released("ui_right") || input->is_action_just_released("ui_up") || input->is_action_just_released("ui_down")) {
+				gamepad_event_delay_ms = DEFAULT_GAMEPAD_EVENT_DELAY_MS;
+				set_process_internal(false);
+				return;
+			}
+
+			gamepad_event_delay_ms -= get_process_delta_time();
+			if (gamepad_event_delay_ms < 0) {
+				gamepad_event_delay_ms = gamepad_event_repeat_rate_ms;
```
Comment (groud) [inline scene/gui/slider.cpp:205]: same here

File: scene/gui/slider.cpp [hunk 3]
```diff
@@ -163,6 +191,41 @@ void Slider::_update_theme_item_cache() {
...
+				if (orientation == HORIZONTAL) {
+					if (input->is_action_pressed("ui_left")) {
```
Comment (groud) [inline scene/gui/slider.cpp:207]: I would probably weight the value change using the action's strength, so that leaning the thumbstick leads to a smaller step change ?

Comment (Levrault) [reply scene/gui/slider.cpp:207]: I'm not quite sure if I understood your proposition but I think that we should not use the action strengh in this case. 

The user could find the feedback pretty strange and it could go again the industry strandard. If the user want a precise value, he just need to move the joystick one time. If he want a greater value, he can keep the joystick in the desired direction.

Comment (groud) [reply scene/gui/slider.cpp:207]: Fair enough!

**Review by groud — APPROVED** [review]

**Comment by KoBeWi** [comment]
idk if it's just me or the movement has a weird jitter 🤔

https://user-images.githubusercontent.com/2223172/232902010-135aa8ac-cc49-4db5-a376-1270af53c6bb.mp4

File: core/input/input_map.cpp [hunk 4]
```diff
@@ -399,21 +399,25 @@ const HashMap<String, List<Ref<InputEvent>>> &InputMap::get_builtins() {
 	inputs = List<Ref<InputEvent>>();
 	inputs.push_back(InputEventKey::create_reference(Key::LEFT));
 	inputs.push_back(InputEventJoypadButton::create_reference(JoyButton::DPAD_LEFT));
+	inputs.push_back(InputEventJoypadMotion::create_reference(JoyAxis::LEFT_X, -1.0));
```
Comment (KoBeWi) [inline core/input/input_map.cpp:402]: Are we sure that all Controls handle analog input correctly?

File: scene/gui/popup_menu.cpp [hunk 5]
```diff
@@ -273,7 +273,18 @@ void PopupMenu::gui_input(const Ref<InputEvent> &p_event) {
...
 
 	if (!items.is_empty()) {
+		Input *input = Input::get_singleton();
+		Ref<InputEventJoypadMotion> joypadmotion_event = p_event;
+		Ref<InputEventJoypadButton> joypadbutton_event = p_event;
+		bool is_joypad_event = (joypadmotion_event.is_valid() || joypadbutton_event.is_valid());
+
 		if (p_event->is_action("ui_down", true) && p_event->is_pressed()) {
+			if (is_joypad_event) {
+				if (!input->is_action_just_pressed("ui_down", true)) {
```
Comment (KoBeWi) [inline scene/gui/popup_menu.cpp:283]: Is this condition necessary? The one above already checks if the action is pressed.

File: scene/gui/popup_menu.cpp [hunk 6]
```diff
@@ -876,6 +893,86 @@ void PopupMenu::_notification(int p_what) {
 		} break;
 
 		case NOTIFICATION_INTERNAL_PROCESS: {
+			Input *input = Input::get_singleton();
+
+			if (input->is_action_just_released("ui_left") || input->is_action_just_released("ui_right") || input->is_action_just_released("ui_up") || input->is_action_just_released("ui_down")) {
```
Comment (KoBeWi) [inline scene/gui/popup_menu.cpp:898]: This stops movement if unrelated action is released. Not sure if intended.

File: scene/gui/popup_menu.cpp [hunk 7]
```diff
@@ -876,6 +893,86 @@ void PopupMenu::_notification(int p_what) {
...
+					}
+
+					bool match_found = false;
+					for (int i = search_from; i < items.size(); i++) {
+						if (!items[i].separator && !items[i].disabled) {
+							mouse_over = i;
+							emit_signal(SNAME("id_focused"), i);
+							scroll_to_item(i);
+							control->queue_redraw();
+							set_input_as_handled();
```
Comment (KoBeWi) [inline scene/gui/popup_menu.cpp:919]: This line has no effect inside `PROCESS`, should be removed.

File: scene/gui/popup_menu.cpp [hunk 8]
```diff
@@ -876,6 +893,86 @@ void PopupMenu::_notification(int p_what) {
...
 		case NOTIFICATION_INTERNAL_PROCESS: {
+			Input *input = Input::get_singleton();
+
+			if (input->is_action_just_released("ui_left") || input->is_action_just_released("ui_right") || input->is_action_just_released("ui_up") || input->is_action_just_released("ui_down")) {
+				gamepad_event_delay_ms = DEFAULT_GAMEPAD_EVENT_DELAY_MS;
+				set_process_internal(false);
+				return;
+			}
+			gamepad_event_delay_ms -= get_process_delta_time();
+			if (gamepad_event_delay_ms < 0) {
```
Comment (KoBeWi) [inline scene/gui/popup_menu.cpp:904]:
```suggestion
			if (gamepad_event_delay_ms <= 0) {
```

File: scene/gui/popup_menu.h [hunk 9]
```diff
@@ -131,6 +131,11 @@ class PopupMenu : public Popup {
 	ScrollContainer *scroll_container = nullptr;
 	Control *control = nullptr;
 
+	const int DEFAULT_GAMEPAD_EVENT_REPEAT_RATE = 20;
+	const float DEFAULT_GAMEPAD_EVENT_DELAY_MS = 0.5;
+	float gamepad_event_repeat_rate_ms = 0.25;
```
Comment (KoBeWi) [inline scene/gui/popup_menu.h:136]: This is some weird variable. It's not a constant, but the constructor overwrites the default value, which is then never changed anymore.

File: scene/gui/slider.cpp [hunk 10]
```diff
@@ -163,6 +191,41 @@ void Slider::_update_theme_item_cache() {
...
+						set_value(get_value() - (custom_step >= 0 ? custom_step : get_step()));
+					}
+
+					if (input->is_action_pressed("ui_right")) {
+						set_value(get_value() + (custom_step >= 0 ? custom_step : get_step()));
+					}
+				}
+
+				if (orientation == VERTICAL) {
```
Comment (KoBeWi) [inline scene/gui/slider.cpp:216]:
```suggestion
				} else if (orientation == VERTICAL) {
```

**Comment by KoBeWi** [comment]
Seems fine, but I left some comments. The comments I left in PopupMenu also apply to Slider (mostly).

File: scene/gui/popup_menu.cpp (hunk 7 above)
Comment (Levrault) [reply scene/gui/popup_menu.cpp]: removed on both line

File: scene/gui/popup_menu.cpp (hunk 8 above)
Comment (Levrault) [reply scene/gui/popup_menu.cpp]: fixed

File: scene/gui/popup_menu.cpp (hunk 5 above)
Comment (Levrault) [reply scene/gui/popup_menu.cpp:305]: it's prevent unecessary echoing between the check in internal process and input. If I remove this line, we will have inconsistant value

File: core/input/input_map.cpp (hunk 4 above)
Comment (Levrault) [reply core/input/input_map.cpp:402]: I still pretty new to Godot Engine's code, but since we check with ui_XXX, should the alt key take the lead if the analog isn't set?

File: scene/gui/popup_menu.cpp (hunk 6 above)
Comment (Levrault) [reply scene/gui/popup_menu.cpp:927]: I removed ui_left and ui_right

File: scene/gui/popup_menu.h (hunk 9 above)
Comment (KoBeWi) [reply scene/gui/popup_menu.h]: By weird I mean `gamepad_event_repeat_rate_ms` is never changed, so it could be a constant too.
Also the primitive types *should* be initialized in the header. You can use `0.0` if the default is not important.

Comment (Levrault) [reply scene/gui/popup_menu.h]: I get it. It should be easier to understand now

```
	const float DEFAULT_GAMEPAD_EVENT_DELAY_MS = 0.5;
	const float GAMEPAD_EVENT_REPEAT_RATE_MS = 1.0 / 20;
	float gamepad_event_delay_ms = DEFAULT_GAMEPAD_EVENT_DELAY_MS;
```

**Comment by KoBeWi** [comment]
Then I guess it's fine.

File: core/input/input_map.cpp (hunk 4 above)
Comment (KoBeWi) [reply core/input/input_map.cpp:402]: What I mean is that this PR adds a specific logic to two nodes just to handle analog input, so I wonder if all other controls can handle it. If not, including axis in default controls can lead to exposing buggy behavior.

File: scene/gui/popup_menu.cpp [hunk 11]
```diff
@@ -905,6 +922,84 @@ void PopupMenu::_notification(int p_what) {
...
+					}
+
+					bool match_found = false;
+					for (int i = search_from; i >= 0; i--) {
+						if (!items[i].separator && !items[i].disabled) {
+							mouse_over = i;
+							emit_signal(SNAME("id_focused"), i);
+							scroll_to_item(i);
+							control->queue_redraw();
+							set_input_as_handled();
```
Comment (KoBeWi) [inline scene/gui/popup_menu.cpp:981]: There's two more to remove.

File: scene/gui/popup_menu.cpp [hunk 12]
```diff
@@ -905,6 +922,84 @@ void PopupMenu::_notification(int p_what) {
...
+
+					if (!match_found) {
+						// If the first item is not selectable, try re-searching from the end.
+						for (int i = items.size() - 1; i >= search_from; i--) {
+							if (!items[i].separator && !items[i].disabled) {
+								mouse_over = i;
+								emit_signal(SNAME("id_focused"), i);
+								scroll_to_item(i);
+								control->queue_redraw();
+								set_input_as_handled();
```
Comment (KoBeWi) [inline scene/gui/popup_menu.cpp:995]: ^

File: scene/gui/slider.cpp [hunk 13]
```diff
@@ -163,6 +191,39 @@ void Slider::_update_theme_item_cache() {
 
 void Slider::_notification(int p_what) {
 	switch (p_what) {
+		case NOTIFICATION_INTERNAL_PROCESS: {
+			Input *input = Input::get_singleton();
+
+			if (input->is_action_just_released("ui_left") || input->is_action_just_released("ui_right") || input->is_action_just_released("ui_up") || input->is_action_just_released("ui_down")) {
```
Comment (KoBeWi) [inline scene/gui/slider.cpp:197]: Same problem as in https://github.com/godotengine/godot/pull/63168#discussion_r1170564401, but I guess it's a bit more complicated to handle. You could leave it like that.

File: core/input/input_map.cpp (hunk 4 above)
Comment (Levrault) [reply core/input/input_map.cpp:402]: We got a [discussion]( https://github.com/godotengine/godot/pull/63168#issuecomment-1419268885) about it and I ended up doing a per control implementation since the behavoir of some control node can be quite different from one to another.

That's why I targetted pop_menu and slider, the most common control that should be usable with a gamepad. 

Of course, there is maybe a solution to add it to all control by I'm certainly too inexperienced with the engine to find that solution.

File: scene/gui/popup_menu.cpp [hunk 14]
```diff
@@ -308,7 +319,6 @@ void PopupMenu::gui_input(const Ref<InputEvent> &p_event) {
 					emit_signal(SNAME("id_focused"), i);
 					scroll_to_item(i);
 					control->queue_redraw();
-					set_input_as_handled();
```
Comment (KoBeWi) [inline scene/gui/popup_menu.cpp:311]: Ok sorry, this one was correct ;_;
I didn't notice that it's `gui_input` not `PROCESS`.
Same the one below.

File: core/input/input_map.cpp (hunk 4 above)
Comment (KoBeWi) [reply core/input/input_map.cpp:402]: Adding it to other Controls would involve testing all of them and tweaking the behavior where necessary.
Good point about commonly used Controls, Tree for example is not used in games at all, so there is no point in fixing it. So I think this PR is enough to cover the most common use-cases.

File: scene/gui/popup_menu.cpp (hunk 14 above)
Comment (Levrault) [reply scene/gui/popup_menu.cpp]: Re-added

**Review by KoBeWi — APPROVED** [review]
Looks good now.
Needs to be squashed into 1 commit.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
