### PR TITLE
Fix 2D lighting when using skeleton.

### LINKED ISSUE #32212: Light2D doesn't affect Polygon2D when attached to Bone2D
**Godot version:** 3.1.1 stable

**OS/device including version:** Windows 10

**Issue description:** light stops casting on a polygon when it's attached to a bone on a skeleton

**Steps to reproduce:** Create a polygon, map the uv points, create a skeleton and bone, attach the polygon to the bone. When they are connected, the light stops casting on the polygon. I followed this guide: https://docs.godotengine.org/en/3.1/tutorials/animation/2d_skeletons.html

**Minimal reproduction project:**
[bugdemoproject.zip](https://github.com/godotengine/godot/files/3633927/bugdemoproject.zip)

### PR DESCRIPTION
**Pull request by MadEqua**
Fixes #32212.

Two problems on the light pass when using skeletons, leading to the wrong transform being applied to geometry:

- The texture unit used to bind the bone weights was the same as the light texture.
- The skeleton transform matrices were not being set after binding the lighting shader.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Looks great! Thank you!

File: drivers/gles3/rasterizer_canvas_gles3.cpp [hunk 1]
```diff
@@ -1683,6 +1682,10 @@ void RasterizerCanvasGLES3::canvas_render_items(Item *p_item_list, int p_z, cons
 						} else {
 							state.canvas_shader.set_uniform(CanvasShaderGLES3::SCREEN_PIXEL_SIZE, Vector2(1.0, 1.0));
 						}
+						if (state.using_skeleton) {
+							state.canvas_shader.set_uniform(CanvasShaderGLES3::SKELETON_TRANSFORM, state.skeleton_transform);
```
Comment (clayjohn) [inline drivers/gles3/rasterizer_canvas_gles3.cpp]: Is this necessary if https://github.com/godotengine/godot/pull/34570 is merged? It looks to me like we would end up setting the same uniform twice.

Comment (MadEqua) [reply drivers/gles3/rasterizer_canvas_gles3.cpp]: I was thinking the same, but I believe this is necessary here because these uniforms go to the lighting pass shader. On #34570 they go to the "regular" shader.

Comment (clayjohn) [reply drivers/gles3/rasterizer_canvas_gles3.cpp]: Ah yes, good point.

Comment (clayjohn) [reply drivers/gles3/rasterizer_canvas_gles3.cpp]: The uniforms are set regardless of whether it is a light pass or not here https://github.com/godotengine/godot/blob/master/drivers/gles3/rasterizer_canvas_gles3.cpp#L1606

The canvas_shader is not rebound during the light passes so the uniform should still be up to date for each light.

Comment (clayjohn) [reply drivers/gles3/rasterizer_canvas_gles3.cpp]: @MadEqua ping. The extra setting of the uniform is unnecessary here, the shader is the same as the uniforms are set immediately above, whether in a light pass or not.

Comment (MadEqua) [reply drivers/gles3/rasterizer_canvas_gles3.cpp]: Sorry, this went under my radar.

I might be misunderstanding something but the shader with lighting active is being bound after that, here:

https://github.com/godotengine/godot/blob/318c69351624f7794c51b5385d252af397c0404a/drivers/gles3/rasterizer_canvas_gles3.cpp#L1677-L1679

and it needs the skeleton transforms to work correctly. That's why the issue still reproduces after merging #34570.

Comment (clayjohn) [reply drivers/gles3/rasterizer_canvas_gles3.cpp]: Ah, I missed the ``bind()`` call. Thanks for bearing with me here. Looks good then.

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Sektor13** [comment]
Sorry can't understand from this, was this fixed or not ?
Because i still have problems with Light2d and polygons on bones.

I have attached TSCN - mostly light works, but if you rotate polygone to some extend it stops working.
[light2d_b13.zip](https://github.com/godotengine/godot/files/4590949/light2d_b13.zip)

**Comment by MadEqua** [comment]
@Sektor13 This was fixed. Light2D wasn't working at all with Bone2D. It seems you are experiencing a different, more specific bug. 
I suggest you open a new issue with your test project.
