### PR TITLE
Defer clearing of ResourceUID cache

### LINKED ISSUE #64881: Excessive warnings about invalid UUID in ext_resource
### Godot version

4.0.alpha14

### System information

macOS Monterey - 12.5.1 - M1 - Vulkan

### Issue description

While developing a plugin using custom resources I get many warnings saying:

> scene/resources/resource_format_text.cpp:448 - res://`resource path here`.tscn:3 - ext_resource, invalid UUID: uid://d3g4i4dshtdpu - using text path instead: res://`resource path here`

I'm not using any UUID reference in my code, and things are working as expected, but this warning is still showing up.

image

### Steps to reproduce

I'm unsure, but I assume you have to have custom resources in your plugin/tool scripts. 

### Minimal reproduction project

It is not a minimal reproduction project but it has the current build of my plugin with nothing but a single custom resource created by the "user".

[testing-plain-dialogic-build.zip](https://github.com/godotengine/godot/files/9424126/testing-plain-dialogic-build.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
EditorFile dock was clearing the UID cache, but it was happening before plugins, autolads etc. are loaded, resulting in error spam. I deferred the call, so the editor stuff can load properly. This also makes it possible to use UIDs directly in editor plugins instead of paths.

Fixes #64881

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by bitbrain** [comment]
Just tested this change on my game and it seems the issue described in https://github.com/godotengine/godot/issues/64881 is still happening for my game:

Capture

The .tscn files containing the uid:// strings were already pre-existing so perhaps due to this bug some of the resource ids were created wrongly and are now permanently broken. The only way to fix it currently is to manually edit every single .tscn file and remove the broken uid:// bits from there to get rid of these warnings.

**Comment by KoBeWi** [comment]
You can actually fix this without opening the scenes (manually). Just run this script in your project:
```GDScript
@tool
extends EditorScript

var files: Array[String]

func _run() -> void:
	files = []
	
	add_files("res://")
	
	for file in files:
		print(file)
		var res = load(file)
		ResourceSaver.save(res)

func add_files(dir: String):
	for file in DirAccess.get_files_at(dir):
		if file.get_extension() == "tscn" or file.get_extension() == "tres":
			files.append(dir.path_join(file))
	
	for dr in DirAccess.get_directories_at(dir):
		add_files(dir.path_join(dr))
```
It will open and re-save all text resource files, to make sure they are up to date. It fixes formatting, uids, old classes etc.

**Comment by bitbrain** [comment]
@KoBeWi nope - running that makes it even worse on restart:

https://gist.github.com/bitbrain/d3870f0c52cfdb20038a0066a1251a5a

I also attempted to delete the .godot folder and remove all *.import files and re-import but same issue. The game works fine and resources load as expected, it's just that it still spams when opening the project. Perhaps somebody else can reproduce this on this branch?

**Comment by KoBeWi** [comment]
Are the UIDs correct though? Compare the ext resources in scenes with their actual ids; maybe it's a different issue.

**Comment by bitbrain** [comment]
@KoBeWi example when loading my game project:
```
WARNING: res://ui/savegame/LoadGameContainer.tscn:6 - ext_resource, invalid UUID: uid://k810555el837 - using text path instead: res://worldobjects/player/player.png
     at: ResourceLoaderText::load (scene\resources\resource_format_text.cpp:448)
```
Looking into `res://ui/savegame/LoadGameContainer.tscn` the affected line is this:
```
[ext_resource type="Texture2D" uid="uid://k810555el837" path="res://worldobjects/player/player.png" id="4"]
```
However, this id is present within `res://worldobjects/player/player.png.import`:
```
[remap]

importer="texture"
type="CompressedTexture2D"
uid="uid://k810555el837"
path="res://.godot/imported/player.png-0c8880c21a1280c073ecfb89c7ec2ba3.ctex"
metadata={
"vram_texture": false
}

[deps]

source_file="res://worldobjects/player/player.png"
dest_files=["res://.godot/imported/player.png-0c8880c21a1280c073ecfb89c7ec2ba3.ctex"]

[params]

compress/mode=0
compress/lossy_quality=0.7
compress/hdr_compression=1
compress/bptc_ldr=0
compress/normal_map=0
compress/channel_pack=0
mipmaps/generate=false
mipmaps/limit=-1
roughness/mode=1
roughness/src_normal=""
process/fix_alpha_border=false
process/premult_alpha=false
process/normal_map_invert_y=false
process/hdr_as_srgb=false
process/hdr_clamp_exposure=false
process/size_limit=0
detect_3d/compress_to=0
```

**Comment by KoBeWi** [comment]
Ok I checked again and the warnings seem to still appear. The PR fixes the warning before editor load, but there seem to be more warnings after it's loaded. Maybe caused by scan?

**Comment by bitbrain** [comment]
We might get away with just merging this PR (as it brings value already) bit this means https://github.com/godotengine/godot/issues/64881 won't be fixed yet.

**Comment by KoBeWi** [comment]
I added a brutal silencer for the warning. If the UID does not exist in cache, ResourceLoader will validate whether UID and path still match. @bitbrain check again if it fixes the warnings for you.

The deferred call from the original fix is still needed for using UIDs in plugins (otherwise they fails, not just warn).

**Comment by bitbrain** [comment]
No more warnings happening here!

File: core/io/resource_format_binary.cpp [hunk 1]
```diff
@@ -1042,8 +1042,15 @@ void ResourceLoaderBinary::open(Ref<FileAccess> p_f, bool p_no_resources, bool p
...
 					er.path = ResourceUID::get_singleton()->get_id_path(er.uid);
 				} else {
+#ifdef TOOLS_ENABLED
+				// Silence a warning that can happen during the initial filesystem scan due to cache being regenerated.
+				if (ResourceLoader::get_resource_uid(res_path) != er.uid) {
 					WARN_PRINT(String(res_path + ": In external resource #" + itos(i) + ", invalid UUID: " + ResourceUID::get_singleton()->id_to_text(er.uid) + " - using text path instead: " + er.path).utf8().get_data());
 				}
+#else
+				WARN_PRINT(String(res_path + ": In external resource #" + itos(i) + ", invalid UUID: " + ResourceUID::get_singleton()->id_to_text(er.uid) + " - using text path instead: " + er.path).utf8().get_data());
+#endif
```
Comment (akien-mga) [inline core/io/resource_format_binary.cpp:1052]: Indentation issue.

**Comment by akien-mga** [comment]
Thanks!

**Comment by InfiniteProductions** [comment]
I still have those weird warnings for a while now, using RC til the newly released RC3:
godot-4rc3-warnings-scene

I don't remember when they were displayed first, never change anything, and not tried the tool script provided by @KoBeWi, I don't know what t think about this, it doesn't looks like #64881 has been actually fixed or maybe #67124 created those warnings in the first place.

Although everything looks like to work as expected despite the name of the loaded scene instead is not.

**Comment by InfiniteProductions** [comment]
> Do you have any minimal reproduction project? Does saving the problematic scenes again fix the issue?

No I don't and yes, saving the scenes again makes the warning no longer displayed.

**Comment by Zimmabue** [comment]
immagine
I'm having these warnings from rc if I remember right, and they still appear in 4.0
Every time I open the project the warnings are from different resources. If I run the game or save the scene they still appear.

**Comment by KoBeWi** [comment]
Is the UID always the same?
The warnings come from external resources, so you need to save the resource file, not the scene.

**Comment by Zimmabue** [comment]
Ok I saved the tscn and glb (in which I have external materials setted) files and warnings disappeared. Why do they appear? May I did something wrong?

**Comment by KoBeWi** [comment]
When were the files created?
The warnings might appear if you do some changes to the file outside Godot. Although this shouldn't be happening when you modify the glb file, so maybe it's some importer bug.

**Comment by Zimmabue** [comment]
If I remember right I delete a plug-in from the file system (wrong move, I did it without thinking too much). I had out warnings related to the missing plug-in that I managed to resolve and then this warnings appeared. But I don't know if they are related

**Comment by KoBeWi** [comment]
If you do changes to files that affect UIDs, like moving the file, renaming etc, it will cause UID mismatch. Each UID corresponds to a specific path, which is stored in a cache file. Godot updates it automatically when you manipulate the files (it even updates all usages of an UID inside scenes/resources), but if you e.g. externally duplicate or move the file, it will get detected as a new resource and cause all kinds of weird things.

Some related issues:
#73916
#68661

**Comment by eh-jogos** [comment]
> You can actually fix this without opening the scenes (manually). Just run this script in your project:
> 
> ```gdscript
> @tool
> extends EditorScript
> 
> var files: Array[String]
> 
> func _run() -> void:
> 	files = []
> 	
> 	add_files("res://")
> 	
> 	for file in files:
> 		print(file)
> 		var res = load(file)
> 		ResourceSaver.save(res)
> 
> func add_files(dir: String):
> 	for file in DirAccess.get_files_at(dir):
> 		if file.get_extension() == "tscn" or file.get_extension() == "tres":
> 			files.append(dir.path_join(file))
> 	
> 	for dr in DirAccess.get_directories_at(dir):
> 		add_files(dir.path_join(dr))
> ```
> 
> It will open and re-save all text resource files, to make sure they are up to date. It fixes formatting, uids, old classes etc.

I get this warnings a lot not on the editor but on exported projects. This snippet really helped to automate "fixing" it Thanks a lot!

But there are some strange things:
- The amount of changes on git after running this script doesn't match the amount of files I receive warnings for. And I've noticed it sometimes that the UID in the scene's "external resources" listing and in the external resource itself match perfectly, and then just opening the scene and saving usually fixed the warning even though the uid itself didn't change.
- I also have to re import all my pngs as I receive warnings for almost all of them when exporting the game as well.

Am I doing something wrong, or is this normal?

I don't think I edited these files externally since last export, I might have moved the images and a lot scenes/resources as I reorganized the project folder but I always do that through the editor. 

Sometimes I do save scenes and scripts in VScode, as I use it for git, but it's usually throwing away debug prints when reviewing changes before commit, or sometimes when I want to split some changes between commits, I commit some lines and not other from files. 

In the end everything gets committed, but there might be some file saving between them. Could that be it?

**Comment by pennyloafers** [comment]
@KoBeWi 's editor script worked for me on 4.1. I had to also add ".material" resources as well. Thanks

**Comment by dzsqxhy** [comment]
> You can actually fix this without opening the scenes (manually). Just run this script in your project:
> 
> ```gdscript
> @tool
> extends EditorScript
> 
> var files: Array[String]
> 
> func _run() -> void:
> 	files = []
> 	
> 	add_files("res://")
> 	
> 	for file in files:
> 		print(file)
> 		var res = load(file)
> 		ResourceSaver.save(res)
> 
> func add_files(dir: String):
> 	for file in DirAccess.get_files_at(dir):
> 		if file.get_extension() == "tscn" or file.get_extension() == "tres":
> 			files.append(dir.path_join(file))
> 	
> 	for dr in DirAccess.get_directories_at(dir):
> 		add_files(dir.path_join(dr))
> ```
> 
> It will open and re-save all text resource files, to make sure they are up to date. It fixes formatting, uids, old classes etc.

Thanks very much. This resolved an issue that had been bothering me for a long time.
