### PR TITLE
Fix error when exporting files without import parameters

### LINKED ISSUE #94400: Compute shader file gives error when exporting project
### Tested versions

v4.3.beta.custom_build [97b8ad1]

### System information

Windows 11 - Vulkan (Forward+)

### Issue description

If the project has a compute shader `.glsl` file, it will give this error when exporting:

> Cannot erase nonexistent section "params".

### Steps to reproduce

* Create a "compute_example.glsl" file
* Export project to some platform (I tested with Windows)

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by ydeltastar**
* Fixes: https://github.com/godotengine/godot/issues/94400

### CODE REVIEW

File: editor/export/editor_export_platform.cpp [hunk 1]
```diff
@@ -1230,7 +1230,9 @@ Error EditorExportPlatform::export_project_files(const Ref<EditorExportPreset> &
 
 				// Erase useless sections.
 				config->erase_section("deps");
```
Comment (Calinou) [inline editor/export/editor_export_platform.cpp:1232]: Should this also have a check just in case?

File: editor/export/editor_export_platform.cpp [hunk 2]
```diff
@@ -1295,7 +1297,9 @@ Error EditorExportPlatform::export_project_files(const Ref<EditorExportPreset> &
...
```
Comment (Calinou) [inline editor/export/editor_export_platform.cpp:1299]: Same as above.

**Review by clayjohn — APPROVED** [review]
Makes sense to me. 

It seems like the `[params]` section is ignored when the config is loaded because it never contains any items. 

Additionally, the only other place that `config->erase_section("params");` is called, checks for the existence of "params" first

File: editor/export/editor_export_platform.cpp (hunk 1 above)
Comment (clayjohn) [reply editor/export/editor_export_platform.cpp]: I think "deps" always has elements in it since it stores the path of the source file and the imported file. So we shouldn't need to check it

**Comment by akien-mga** [comment]
Thanks!
