### PR TITLE
Editor: Fix escaping issues with POT generator

### LINKED ISSUE #80004: Impossible to generate well formated POT files when a `String` with `\"` is used
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 (NVIDIA; 31.0.15.3667) - Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 Threads)

### Issue description

When generating a POT file using Godot Editor, if the `String` contains double quotes, its entry in the POT file will be wrong (see below).

### Steps to reproduce

Create this script:
```
extends Control


func _ready():
	
	var a: String = tr("\"Problematic\" string")
	print(a)
```

And then generate a POT file from it. You will get something like:
```
# LANGUAGE translation for Bugs for the following files:
# res://main.gd
#
# FIRST AUTHOR < EMAIL @ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Bugs\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8-bit\n"

#: main.gd
msgid ""Problematic" string"
msgstr ""
```

The problem cames from the extra double quotes inside the string, they will raise an error when generating a PO file.

A possible solution would be to make:
```
extends Control


func _ready():
	
	TranslationServer.set_locale("fr")
	var a: String = tr("\\\"Problematic\\\" string")
	print(a)
```

Therefore, the POT file:
```
# LANGUAGE translation for Bugs for the following files:
# res://main.gd
#
# FIRST AUTHOR < EMAIL @ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Bugs\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8-bit\n"

#: main.gd
msgid "\"Problematic\" string"
msgstr ""
```

But then, the string is not recognized. This is the PO file with an extra entry added manually:
```
# LANGUAGE translation for Bugs for the following files:
# res://main.gd
#
# FIRST AUTHOR < EMAIL @ADDRESS>, 2023.
#
msgid ""
msgstr ""
"Project-Id-Version: Bugs\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"Language: fr\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: main.gd
msgid "\"Problematic\" string"
msgstr "TEST0"

msgid "\\\"Problematic\\\" string"
msgstr "TEST1"
```
Then `print(a)` prints `TEST1` instead of `TEST0`.

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/12207357/project.zip)

### PR DESCRIPTION
**Pull request by dalexeev**
* Closes #80004.

**Note:** I'm not familiar with `gettext`, please test this if you are.

```gdscript
print(tr(""))
print(tr("\n"))
print(tr("Test 1."))
print(tr("Test 2.\n"))
print(tr("Test 3.\nNewline."))
print(tr("Test 4.\nNewline.\n"))
print(tr("Test 5. \\n - Not newline."))
print(tr("Test 6. \" \\"))
```

**Before:**

```pot
#: node.gd
msgid ""
msgstr ""

#: node.gd
msgid ""
"\n"
""
msgstr ""

#: node.gd
msgid "Test 1."
msgstr ""

#: node.gd
msgid ""
"Test 2.\n"
""
msgstr ""

#: node.gd
msgid ""
"Test 3.\n"
"Newline."
msgstr ""

#: node.gd
msgid ""
"Test 4.\n"
"Newline.\n"
""
msgstr ""

#: node.gd
msgid ""
"Test 5. \n"
" - Not newline."
msgstr ""

#: node.gd
msgid "Test 6. " \"
msgstr ""
```

**After:**

```pot
#: node.gd
msgid ""
msgstr ""

#: node.gd
msgid "\n"
msgstr ""

#: node.gd
msgid "Test 1."
msgstr ""

#: node.gd
msgid "Test 2.\n"
msgstr ""

#: node.gd
msgid ""
"Test 3.\n"
"Newline."
msgstr ""

#: node.gd
msgid ""
"Test 4.\n"
"Newline.\n"
msgstr ""

#: node.gd
msgid "Test 5. \\n - Not newline."
msgstr ""

#: node.gd
msgid "Test 6. \" \\"
msgstr ""
```

### CODE REVIEW

File: editor/pot_generator.cpp [hunk 1]
```diff
@@ -99,25 +99,27 @@ void POTGenerator::_write_to_pot(const String &p_file) {
...
 	for (int i = 0; i < files.size(); i++) {
-		extracted_files += "# " + files[i] + "\n";
+		extracted_files += "# " + files[i].replace("\n", "\\n") + "\n";
 	}
 	const String header =
-			"# LANGUAGE translation for " + project_name + " for the following files:\n" + extracted_files +
+			"# LANGUAGE translation for " + project_name + " for the following files:\n" +
+			extracted_files +
 			"#\n"
 			"# FIRST AUTHOR < EMAIL @ADDRESS>, YEAR.\n"
```
Comment (dalexeev) [inline editor/pot_generator.cpp:112]:
```suggestion
			"# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.\n"
```

Comment (timothyqiu) [reply editor/pot_generator.cpp:112]: Yeah, `gettext` generated POT files don't have these spaces.

**Review by timothyqiu — APPROVED** [review]
LGTM.

Escaping file paths looks unnecessary. But yeah, newlines in a path seem not forbidden :P

**Comment by dalexeev** [comment]
> Escaping file paths looks unnecessary. But yeah, newlines in a path seem not forbidden :P

I just added protection in case the string had newlines for some reason. Because the comment ends on a newline.

File: editor/pot_generator.cpp [hunk 2]
```diff
@@ -99,25 +99,27 @@ void POTGenerator::_write_to_pot(const String &p_file) {
...
 			"#, fuzzy\n"
 			"msgid \"\"\n"
 			"msgstr \"\"\n"
 			"\"Project-Id-Version: " +
-			project_name + "\\n\"\n"
-						   "\"MIME-Version: 1.0\\n\"\n"
-						   "\"Content-Type: text/plain; charset=UTF-8\\n\"\n"
-						   "\"Content-Transfer-Encoding: 8-bit\\n\"\n";
+			project_name +
+			"\\n\"\n"
```
Comment (YuriSizov) [inline editor/pot_generator.cpp:119]: Style-wise this could probably be on the same line.

**Review by YuriSizov — APPROVED** [review]
Looks sensible, good job!

File: editor/pot_generator.cpp (hunk 2 above)
Comment (dalexeev) [reply editor/pot_generator.cpp:119]: Do you mean like this:

```c++
			"\"Project-Id-Version: " + project_name +
			"\\n\"\n"
			"\"MIME-Version: 1.0\\n\"\n"
			"\"Content-Type: text/plain; charset=UTF-8\\n\"\n"
			"\"Content-Transfer-Encoding: 8-bit\\n\"\n";
```

Or should I revert this part?

Comment (dalexeev) [reply editor/pot_generator.cpp:119]: `clang-format` requires string literal concatenation (without the `+` operator) to continue in the same column as previous literal.

Comment (YuriSizov) [reply editor/pot_generator.cpp:119]: Ah, that's why it was like that before. Damn, that sucks. I guess the first line works without triggering clang-format because the next line is a variable, not a literal?
