### PR TITLE
[3.x] Fix TileMap error msg when Navigation2D node is not set

### LINKED ISSUE #64011: `Condition "!parent_2d" is true.` error for `TileMap` with `bake_navigation=true` and no `Navigation2D` parent
### Godot version

3.5.stable

### System information

N/A

### Issue description

`TileMap` with `bake_navigation=true` and no `Navigation2D` ancestor/parent (or non-`Node2D` node between them) results in errors:
```
E 0:00:00.509   get_relative_transform_to_parent: Condition "!parent_2d" is true. Returned: Transform2D()
  <C++ Source>  scene/2d/node_2d.cpp:356 @ get_relative_transform_to_parent()
E 0:00:00.519   get_relative_transform_to_parent: Condition "!parent_2d" is true. Returned: Transform2D()
  <C++ Source>  scene/2d/node_2d.cpp:356 @ get_relative_transform_to_parent()
```

Seems like a regression from #61996, cc @smix8.

### Steps to reproduce

Add a `TileMap` and set `bake_navigation` to true.

Errors (on run / reparenting nodes etc. in the editor):
TeKagG4MQhGodot_v3 5-stable_win64_kGUvIfh2OVBSuEaOFXgG

No errors:
rQhRmZEkPc4902QvFokT

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by smix8**
Fixes TileMap error msg spam when `bake_navigation=true` but the optional and depr `Navigation2D` node is not set.

Fixes #64011

### CODE REVIEW

File: scene/2d/tile_map.cpp [hunk 1]
```diff
@@ -157,7 +157,13 @@ void TileMap::_update_quadrant_transform() {
 
 	Transform2D nav_rel;
 	if (bake_navigation) {
-		nav_rel = get_relative_transform_to_parent(navigation);
+		if (navigation) {
+			nav_rel = get_relative_transform_to_parent(navigation);
+		} else if (Object::cast_to<Node2D>(get_parent())) {
+			nav_rel = get_relative_transform_to_parent(get_parent());
```
Comment (kleonc) [inline scene/2d/tile_map.cpp:163]:
```suggestion
```

`get_transform()` returns the transform relative to the direct parent (result of `get_parent()`) so this is equivalent to the `else` block and thus it's not needed.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.1.
