### PR TITLE
[4.x] Use depth prepass to increase opaque render performance

### LINKED ISSUE #60364: Vulkan: Massive performance hit when rendering transparent objects
### Godot version

Godot 4.0 dev, commit 690fefe43ee74c0ae3ed5642f3aefbeb711f9d1c

### System information

Fedora Linux 36 Beta, Vulkan, Gnome 42 (Wayland), Radeon RX580 (Mesa 22)

### Issue description

I know that a certain performance hit is to be expected when rendering objects that have transparent parts. The official Godot documentation specifically suggests that transparent objects in a scene should be kept to a minimum. However, in practice, for certain kinds of assets, there is just no way around using transparent textures to avoid an otherwise insane vertex count, which is also very bad for performance (e.g. grass, foliage, trees etc.)

I've been playing around with grass and tree assets inside Godot lately and noticed that the performance hit is insane. Even a simple tree with a couple of planes and transparent textures easily brings my framerate down from 200 to something like 40, when using Alpha Scissor or Depth Pre-Pass with Depth Draw set to "Opaque Only". 

I understand that these are mostly limitations by the way graphics rendering works and that in production a lot of trickery is involved to keep the amount of overdraw low. However, there are a lot of games that use a lot of foliage and trees and still perform well. I can't imagine that this would be currently possible with Godot and think there might be something wrong with transparency rendering.

The attached example might be a little extreme, but should illustrate the issue. It uses GPUParticles3D to render 20.000 patches of grass on a plane. Enabling transparency (Depth Pre-Pass with Opaque Only Depth Draw) reduces the framerate from around above 300 to below 30. 
Bildschirmfoto vom 2022-04-19 02-29-30
Bildschirmfoto vom 2022-04-19 02-29-12

### Steps to reproduce

see minimal reproduction project

### Minimal reproduction project
[transparency_test.zip](https://github.com/godotengine/godot/files/8509012/transparency_test.zip)

### PR DESCRIPTION
**Pull request by Ansraer**
Some minor performance improvements I came up with while investigating #68959.

1. Disable writing depth in opaque pass since we have already done so in the pre pass. 
2. Change depth comparison op to equal in the opaque pass.
This has the big advantage that transparent fragments can be discarded by the early test before they even enter the fragment stage. We thus save ourselves from starting a fragment shader just to immediately quit it again when we discard.

I tested this PR using https://github.com/Rytelier/Godot-4-forest-benchmark and got the following results:

<details>
<summary>Details</summary>

image

</details>

As you can see this change can reduce the time needed for the opaque pass by up to half. 
According to renderdoc 33678, 12582, and 3654 are all meshes used to render the leaves of the trees.

Visually I could see no difference between the rendered frames.

(Kinda) fixes #60364

_This PR is not applicable to the mobile renderer, since it has no prepass. I am fairly certain that a similar change could be implemented in the OpenGL renderer, but it appears to be currently broken_

### CODE REVIEW

**Comment by clayjohn** [comment]
> I am fairly certain that a similar change could be implemented in the OpenGL renderer, but it appears to be currently broken

What seems broken, this change should be applicable to the OpenGL renderer as well

**Comment by Ansraer** [comment]
Checked the log, and it would appear that GL doesn't like many of the image formats that were used with the clustered renderer. Also, it would appear that refraction is currently broken. Whenever I try to start godot complains about the following:

```
ERROR: SceneShaderGLES3: Fragment shader compilation failed:
ERROR: 0:955: 'm_SCREEN_TEXTURE' : undeclared identifier
ERROR: 0:955: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.
```

A quick search would imply that this is caused by Line 1230 in material.cpp.

https://github.com/godotengine/godot/blob/d44d0cc0fd543da143010ad96978951facd87c1e/scene/resources/material.cpp#L1229-L1231

**Comment by Calinou** [comment]
Is this change relevant for 3.x's GLES3 renderer, which features a depth prepass?

**Comment by clayjohn** [comment]
> Checked the log, and it would appear that GL doesn't like many of the image formats that were used with the clustered renderer. Also, it would appear that refraction is currently broken. Whenever I try to start godot complains about the following:
> 
> ```
> ERROR: SceneShaderGLES3: Fragment shader compilation failed:
> ERROR: 0:955: 'm_SCREEN_TEXTURE' : undeclared identifier
> ERROR: 0:955: '' : compilation terminated
> ERROR: 2 compilation errors.  No code generated.
> ```
> 
> A quick search would imply that this is caused by Line 1230 in material.cpp.
> 
> https://github.com/godotengine/godot/blob/d44d0cc0fd543da143010ad96978951facd87c1e/scene/resources/material.cpp#L1229-L1231

Ah yes, ``SCREEN_TEXTURE`` hasn't been re-implemented yet. I should do something to make sure it doesn't result in a compile error though. You shouldn't need the SCREEN_TEXTURE to test these changes

File: servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp [hunk 1]
```diff
@@ -307,8 +308,21 @@ void SceneShaderForwardClustered::ShaderData::set_code(const String &p_code) {
 							continue;
 						}
 
+						RD::PipelineDepthStencilState depth_stencil;
+						if (depth_test != DEPTH_TEST_DISABLED) {
+							if (depth_pre_pass_enabled) {
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp:313]: We need a finer grain check here, as this only works for fragments that write to the depth buffer, it shouldn't be used for regular transparent objects as it will result in them not getting drawn at all.

**Comment by Calinou** [comment]
I've tested this change on https://github.com/Calinou/godot-reflection, but it doesn't improve things much on a Radeon RX 6900 XT (Mesa RADV):

### 1152×864

Before | After (this PR)
-|-
806 FPS (1.24 mspf) | 817 FPS (1.22 mspf)

### 3840×2160

Before | After (this PR)
-|-
138 FPS (7.24 mspf) | 139 FPS (7.19 mspf)

File: servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp (hunk 1 above)
Comment (Ansraer) [reply servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp:313]: Ah, true. I thought true alpha was handled by a different pipeline version. Will change that to only trigger when something that has depth is rendered.

**Comment by Ansraer** [comment]
@Calinou That scene is a bad test case for this PR since it is >90% solid geometry.

What I do is leverage the depth pre-pass to make the rendering of alpha-clipped elements far cheaper, which doesn't really matter in scenes without alphaclipped objects. You should see at least some speedup if you open a scene with vegetation or hair cards.

I think there is a link to an example project in my original post.

File: servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp [hunk 2]
```diff
@@ -307,8 +308,21 @@ void SceneShaderForwardClustered::ShaderData::set_code(const String &p_code) {
 							continue;
 						}
 
+						RD::PipelineDepthStencilState depth_stencil;
+						if (depth_test != DEPTH_TEST_DISABLED) {
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp:312]: This is already checked above. Since the check above is needed in the ``else`` branch we can remove this one

**Review by clayjohn — COMMENTED** [review]
Other than this one small comment, I think this should be good!

File: servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp (hunk 2 above)
Comment (Ansraer) [reply servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp]: That wouldn't have worked the way the code was currently structured, since in the next if branch this wasn't checked previously.
I changed things a bit, should be fine now.

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
