### PR TITLE
Android: Run clipboard tasks on UI thread

### LINKED ISSUE #108793: Crash when using clipboard on old Androids
### Tested versions

- Reproducible in master and 4.5-beta1
- Not reproducible in 4.5-dev5
Regression from #102866

### System information

Samsung Galaxy J7 2016 (Android 8), Samsung Galaxy J5 2016 (Android 7)

### Issue description

It's not crash, it's signal 9 as logcat writes, I couldn't get any backtrace. Happens when clipboard_(get/set) is used.

### Steps to reproduce

```gdscript
DisplayServer.clipboard_get()
```

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/21334312/mrp.zip)

### PR DESCRIPTION
**Pull request by syntaxerror247**
Fixes crashes on older Android versions (API level <= 27) by ensuring that all clipboard operations are executed on the UI thread.

Fixes https://github.com/godotengine/godot/issues/108793

### CODE REVIEW

**Comment by syntaxerror247** [comment]
The crash is not reproducible on API level >= 28. It seems Android handles clipboard access differently on newer versions.

Since this solution blocks the thread, do we want to restrict it only to API <= 27 and continue calling the method directly on newer versions?

**Review by m4gr3d — CHANGES_REQUESTED** [review]
Let's use a [`FutureTask`](https://developer.android.com/reference/java/util/concurrent/FutureTask) instead. For api <= 27, you can submit the `FutureTask` to the `mainExecutor`. For api > 27, you can just call `FutureTask#run()` directly.

**Comment by m4gr3d** [comment]
> Let's use a [`FutureTask`](https://developer.android.com/reference/java/util/concurrent/FutureTask) instead. For api <= 27, you can submit the `FutureTask` to the `mainExecutor`. For api > 27, you can just call `FutureTask#run()` directly.

Quick clarification; you should create persistent `Callable` fields to wrap the logic for each method:
- on api > 27, you call the `Callable` directly and return their result (this way we're not allocated new objects for each method call)
- on api <= 27, you wrap the `Callable` in a `FutureTask` and submit it to the `mainExecutor`. We're allocating new `FutureTask` objects on each invocation, but there's no other options.

**Comment by syntaxerror247** [comment]
@m4gr3d Does this looks good now?

I kept `setClipboard()` to always run on the UI thread across all Android versions. Since it doesn't return a value, there's no need to block the call on older versions, and running on UI thread doesn't cause any issues on newer ones either.

File: platform/android/java/lib/src/org/godotengine/godot/Godot.kt [hunk 1]
```diff
@@ -934,19 +945,31 @@ class Godot private constructor(val context: Context) {
 
 	@Keep
 	fun hasClipboard(): Boolean {
-		return mClipboard?.hasPrimaryClip() == true
+		return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/Godot.kt]: Looks good but we should also run this block when we are already on the main thread as well, otherwise the other block will cause a deadlock on the main thread.

```suggestion
		return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P || Looper.getMainLooper().getThread() == Thread.currentThread()) {
```

**Review by m4gr3d — CHANGES_REQUESTED** [review]

**Review by m4gr3d — APPROVED** [review]
Looks good!

**Comment by Repiteo** [comment]
Thanks!
