### PR TITLE
GLTF: Support 64-bit sizes in glTF import and export

### LINKED ISSUE #70973: Segmentation fault when exporting large scene as gltf
### Godot version

4.0 master dev build (1d14c054a12dacdc193b589e4afb0ef319ee2aae)

### System information

Win 10, forward plus, 32gb ram, 5800x, rx6900xt, latest gpu driver (Nov 22)

### Issue description

I have recently used the following scene to profile Godot's rendering performance https://github.com/Rytelier/Godot-4-forest-benchmark and as part of that wanted to import the scene into other engines.

However, after running for a few minutes (and freezing up Godot) this process fails with a segfault and then crashes the editor without showing any additional information. GDB wasn't able to tell me anything more either, only that the crash occurred in "?? ()".

### Steps to reproduce

1. Open the project linked above
2. Let the editor import everything
3. Try to export the main scene as gltf.
4. Wait a minute or two

### Minimal reproduction project

https://github.com/Rytelier/Godot-4-forest-benchmark

### PR DESCRIPTION
**Pull request by aaronfranke**
Fixes #70973. This PR fixes the ability to import and export glTF files with buffers larger than 4 GiB.

I tested this with the https://github.com/Rytelier/Godot-4-forest-benchmark project linked in issue #70973. In master, Godot crashes. With this PR, Godot successfully exports the file, though it does take a minute, and the resulting `.bin` file is 4,308,900,759 bytes.

I tested importing this file back in. It loads correctly in Blender, but it takes about an hour, and then Blender uses 30 GiB of RAM. I tried loading it into Godot, and the glTF code succeeds at importing the file, but Godot stalls when trying to save the imported scene, specifically `ResourceFormatSaverBinaryInstance::save` gets stuck in calling `_find_resources` over and over, until it uses about 30 GiB of RAM and the CPU usage stalls at 0%, but it seems to still be calling that function. Anyway, I don't know how to fix that, but it's not a bug with the glTF code.

Note that the integer sizes in GLTFAccessor and GLTFBufferView were increased, affecting the exposed API.

### CODE REVIEW

**Comment by Ansraer** [comment]
Hmm my guess would be that either the exporter or importer don't properly habdle instances and thus needlessly duplicate meshes. (Probably some foliage asset like the trees)

**Comment by fire** [comment]
Taking exactly shaped meshes in godot engine and making them instances is a missing feature, does anyone want to write a proposal for it?

I am not doing great, so my bandwidth is variable and low.

File: modules/gltf/gltf_document.cpp [hunk 1]
```diff
@@ -8154,43 +8147,59 @@ Error GLTFDocument::_serialize_file(Ref<GLTFState> p_state, const String p_path)
...
+		uint64_t binary_data_length = 0;
+		uint64_t binary_chunk_length = 0;
 		if (p_state->buffers.size() > 0) {
 			binary_data_length = p_state->buffers[0].size();
+			binary_chunk_length = ((binary_data_length + 3) & (~3));
+			const uint64_t file_length_with_buffer = total_file_length + chunk_header_size + binary_chunk_length;
+			// Check if the file length with the buffer is greater than glTF's maximum of 4 GiB.
+			// If it is, we can't write the buffer into the file, but can write it separately.
+			if (unlikely(p_state->buffers.size() > 1 || file_length_with_buffer > (uint64_t)UINT32_MAX)) {
+				err = _encode_buffer_bins(p_state, p_path);
```
Comment (lyuma) [inline modules/gltf/gltf_document.cpp]: Minor issue.... Technically, calling `_encode_buffer_bins` after `_encode_buffer_glb` will cause buffers 1 and above to be written twice. But since no application currently uses more than one buffer, it probably doesn't matter, and the harm is pretty low: it just writes the same file twice. We don't need to fix this part right now.

File: modules/gltf/gltf_document.cpp [hunk 2]
```diff
@@ -8154,43 +8147,59 @@ Error GLTFDocument::_serialize_file(Ref<GLTFState> p_state, const String p_path)
...
+		uint64_t total_file_length = header_size + chunk_header_size + text_chunk_length;
+		uint64_t binary_data_length = 0;
+		uint64_t binary_chunk_length = 0;
 		if (p_state->buffers.size() > 0) {
 			binary_data_length = p_state->buffers[0].size();
+			binary_chunk_length = ((binary_data_length + 3) & (~3));
+			const uint64_t file_length_with_buffer = total_file_length + chunk_header_size + binary_chunk_length;
+			// Check if the file length with the buffer is greater than glTF's maximum of 4 GiB.
+			// If it is, we can't write the buffer into the file, but can write it separately.
+			if (unlikely(p_state->buffers.size() > 1 || file_length_with_buffer > (uint64_t)UINT32_MAX)) {
```
Comment (lyuma) [inline modules/gltf/gltf_document.cpp]: `unlikely(p_state->buffers.size() > 1` is an incorrect check. We should allow the internal buffer to be used as long as it is less than UINT32_MAX.

The problem probably is that `_encode_buffer_glb` has an off-by-one error in the for loop:
```
for (GLTFBufferIndex i = 1; i < p_state->buffers.size() - 1; i++) {
```
should be
```
for (GLTFBufferIndex i = 1; i < p_state->buffers.size(); i++) {
```
same as `_encode_buffer_bins`, but starting at index 1.

File: modules/gltf/gltf_document.cpp [hunk 3]
```diff
@@ -8154,43 +8147,59 @@ Error GLTFDocument::_serialize_file(Ref<GLTFState> p_state, const String p_path)
...
+				err = _encode_buffer_bins(p_state, p_path);
+				ERR_FAIL_COND_V(err != OK, err);
+				// Since the buffer bins were re-encoded, we need to re-convert the JSON to string.
+				json_string = Variant(p_state->json).to_json_string();
+				cs = json_string.utf8();
```
Comment (lyuma) [inline modules/gltf/gltf_document.cpp:8177]: After adding to the byteLength and uri fields to each buffer, the UTF string will grow by up to `(60 + 4 * p_path.size()) * p_state->buffers.size()` bytes - we may want to subtract this from the `UINT32_MAX` constant above.

I got this 60 number by calculating length `{"byteLength": 12345678901234567890, "uri": "1234567890"}, ` . and assuming 4 bytes per character (if my filename is all emojis or something) it's kind of overkill, but better safe than sorry.

File: modules/gltf/gltf_document.cpp [hunk 4]
```diff
@@ -8154,43 +8147,59 @@ Error GLTFDocument::_serialize_file(Ref<GLTFState> p_state, const String p_path)
...
+		CharString cs = json_string.utf8();
+		uint64_t text_data_length = cs.length();
+		uint64_t text_chunk_length = ((text_data_length + 3) & (~3));
+		uint64_t total_file_length = header_size + chunk_header_size + text_chunk_length;
+		uint64_t binary_data_length = 0;
+		uint64_t binary_chunk_length = 0;
 		if (p_state->buffers.size() > 0) {
 			binary_data_length = p_state->buffers[0].size();
+			binary_chunk_length = ((binary_data_length + 3) & (~3));
+			const uint64_t file_length_with_buffer = total_file_length + chunk_header_size + binary_chunk_length;
```
Comment (lyuma) [inline modules/gltf/gltf_document.cpp:8169]: As a user, if I want to guarantee that no .bin file is generated, I would need to first check a bunch of conditions, such as if the buffer length is less than something, otherwise if I only reference the generated .glb (for example, if I upload it somewhere that expects everything self-contained), I could end up copying a broken .glb.

A user's only choice would be to check `p_state->json).to_json_string()` and roughly approximate 2*32 less the header size to see if Godot might split it into a separate file... it is highly unlikely that the json will take 1 GB (but technically you can't know this for certain)

I do understand for usecases like exporting a scene as glb from the editor, this case makes sense to generate the extra .bin file, so this is fine for that purpose.

**Review by lyuma — COMMENTED** [review]
Overall this change is good. My feedback just centers around the special case when exporting a glb

File: modules/gltf/gltf_document.cpp (hunk 4 above)
Comment (aaronfranke) [reply modules/gltf/gltf_document.cpp:8169]: If it's impossible to export a single self-contained `.glb`, isn't it better to export 2 files than to fail? The user can check for the existence of a `.bin` after export.

However, if a single self-contained `.glb` or error is desired, there is another option: You can export an in-memory buffer, and save that buffer to disk. This way, runtimes that need that option do still have it.

File: modules/gltf/gltf_document.cpp (hunk 3 above)
Comment (aaronfranke) [reply modules/gltf/gltf_document.cpp:8177]: `.glb` files will contain compact JSON, so won't have spaces in them.

File: modules/gltf/gltf_document.cpp (hunk 1 above)
Comment (aaronfranke) [reply modules/gltf/gltf_document.cpp]: Yeah I don't see a way to fix this without making the code messier, and it's mostly a theoretical issue, which isn't really even a problem, it's just a slight reduction in performance compared to the best possible.

File: modules/gltf/gltf_document.cpp (hunk 4 above)
Comment (fire) [reply modules/gltf/gltf_document.cpp:8169]: No it is better to fail

File: modules/gltf/gltf_document.cpp (hunk 3 above)
Comment (aaronfranke) [reply modules/gltf/gltf_document.cpp:8177]: I'm confused as to why this would be needed at all. The JSON only grows after the `if (unlikely(file_length_with_buffer > (uint64_t)UINT32_MAX)) {` check passes, after which we re-calculate the size values directly from the new JSON. If the `if (unlikely(file_length_with_buffer > (uint64_t)UINT32_MAX)) {` check fails (less than max), then we don't modify the JSON after that - it just gets stored as-is.

File: modules/gltf/gltf_document.cpp (hunk 4 above)
Comment (aaronfranke) [reply modules/gltf/gltf_document.cpp:8169]: @fire What should we tell the user who opened issue #70973 then?

File: modules/gltf/gltf_document.cpp (hunk 3 above)
Comment (lyuma) [reply modules/gltf/gltf_document.cpp:8177]: yeah you're right, I'm not sure what I was trying to figure out.

File: modules/gltf/gltf_document.cpp (hunk 4 above)
Comment (lyuma) [reply modules/gltf/gltf_document.cpp:8169]: Most of this PR is good. It shouldn't segfault.

Also, I think the behavior of writing glb + bin is fine in the editor.

Personally I'm not sure it needs to fail. Perhaps we just need to document this behavior in the API docs (as well as how the behavior of .glb vs .gltf depends on file extension) and explain how to check if the buffer 0 size + length of json is 4 GB, before calling write to filesystem.

**Review by lyuma — APPROVED** [review]
I think it seems good.

For applications that need writing to fail instead of creating two files, it is possible to check the size of the buffers beforehand as I mentioned previously, so it's just a question of defaults.

**Comment by akien-mga** [comment]
Thanks!
