### PR TITLE
Fixed a property warning when loading a correct resource type

### LINKED ISSUE #24562: Light2D Error/Warning when loading light texture
**Godot version:**
Godot 3.1 alpha 4

**OS/device including version:**
Windows 10, GeForce GTX 1070

**Issue description:**
Light2D gives out warning when loading a light texture.

**Steps to reproduce:**
- Start new project
- Create Node2D scene
- Add light2D node
- Load light texture

image

### PR DESCRIPTION
**Pull request by Mahoukyou**
Fixes #24562.

Fixed warning when loading a correct resource type to a property that could take more than one resource type.

### CODE REVIEW

File: editor/editor_properties.cpp [hunk 1]
```diff
@@ -1959,16 +1959,17 @@ void EditorPropertyResource::_file_selected(const String &p_path) {
...
 		if (E->get().name == get_edited_property() && (E->get().hint & PROPERTY_HINT_RESOURCE_TYPE)) {
-			type = E->get().hint_string;
+			property_types = E->get().hint_string;
 		}
 	}
 
-	if (!type.empty() && !res->is_class(type))
-		EditorNode::get_singleton()->show_warning(vformat(TTR("The selected resource (%s) does not match the type expected for this property (%s)."), res->get_class(), type));
+	const Vector<String> split_property_types = property_types.split(",");
+	if (split_property_types.find(res->get_class()) == -1)
```
Comment (akien-mga) [inline editor/editor_properties.cpp]: A simple string compare won't work, as we need to match classes that inherit the type hint (e.g. `StreamTexture` is a valid `Texture` type). `Object::is_class` used previously does both check (== or inherits), so you should use that.

Comment (SoIAS) [reply editor/editor_properties.cpp]: My bad, thought it would be sufficient, should have checked Object::is_class before removing it for simple string comparison. I am on it.

Comment (SoIAS) [reply editor/editor_properties.cpp]: @akien-mga Corrected, now we check using is_class for every hinted type. I have also added check for an empty property_types string that I have removed in previous commit, in case the property doesn't have a resource type hint.

**Comment by akien-mga** [comment]
Thanks!
