### PR TITLE
Metal: Ensure baked Metal binaries can be loaded on the minimum target OS

### LINKED ISSUE #109846: iOS 17 crash on startup
### Tested versions

v4.5.beta.mono.double.custom_build [39e6a67fc]

### System information

Godot v4.5.beta.mono.double (39e6a67fc) - Pop!_OS 22.04 LTS on Wayland - X11 display driver, Multi-window, 3 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (nvidia; 565.77) - AMD Ryzen 7 5800X 8-Core Processor (16 threads) - 31.26 GiB memory

### Issue description

Exported ios projects crash immediately on startup with iOS 17.  iOS 18 works fine.  Here is the crash report:

<details>
<summary>Click to expand</summary>

```
Incident Identifier: 338303BA-E2B7-424A-BFD1-B6114CB224BB
Distributor ID:      com.apple.TestFlight
Hardware Model:      iPhone14,7
Process:             blockyballot [11539]
Path:                /private/var/containers/Bundle/Application/29A33647-A9E6-469B-8D6F-AED71D37297B/blockyballot.app/blockyballot
Identifier:          com.langestudios.blockyballot
Version:             0.1.39 (2)
AppStoreTools:       16F7
AppVariant:          1:iPhone14,7:17.4
Beta:                YES
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.langestudios.blockyballot [3153]

Date/Time:           2025-08-20 22:05:13.0784 -0400
Launch Time:         2025-08-20 22:05:12.5202 -0400
OS Version:          iPhone OS 17.6.1 (21G93)
Release Type:        User
Baseband Version:    2.60.02
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000024
Exception Codes: 0x0000000000000001, 0x0000000000000024
VM Region Info: 0x24 is not in any region.  Bytes before following region: 4308893660
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                   100d48000-1016ec000 [ 9872K] r-x/r-x SM=COW  /var/containers/Bundle/Application/29A33647-A9E6-469B-8D6F-AED71D37297B/blockyballot.app/blockyballot
Termination Reason: SIGNAL 11 Segmentation fault: 11
Terminating Process: exc handler [11539]

Triggered by Thread:  0


Kernel Triage:
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter


Thread 0 name:
Thread 0 Crashed:
0   blockyballot                  	0x0000000102797fec RenderingDeviceDriverMetal::command_bind_push_constants(RenderingDeviceDriver::CommandBufferID, RenderingDeviceDriver::ShaderID, unsigned int, VectorView<unsigned int>) + 40
1   blockyballot                  	0x0000000103ff1154 RenderingDeviceGraph::_run_render_commands(int, RenderingDeviceGraph::RecordedCommandSort const*, unsigned int, RenderingDeviceDriver::CommandBufferID&, RenderingDeviceGraph::CommandBufferPool&, in... + 4856
2   blockyballot                  	0x0000000103ff3d98 RenderingDeviceGraph::end(bool, bool, RenderingDeviceDriver::CommandBufferID&, RenderingDeviceGraph::CommandBufferPool&) + 2640
3   blockyballot                  	0x0000000103f5c0a0 RenderingDevice::_end_frame() + 360
4   blockyballot                  	0x0000000103f5bd2c RenderingDevice::swap_buffers(bool) + 92
5   blockyballot                  	0x000000010410d4d0 RendererCompositorRD::set_boot_image(Ref<Image> const&, Color const&, bool, bool) + 1744
6   blockyballot                  	0x0000000101726ba4 Main::setup2(bool) + 15588
7   blockyballot                  	0x000000010248a488 -[GDTViewRenderer setupProjectData] + 68
8   blockyballot                  	0x000000010248a3d8 -[GDTViewRenderer setupView:] + 112
9   blockyballot                  	0x0000000102487a48 -[GDTView drawView] + 256
10  QuartzCore                    	0x000000019b05cdc4 CA::Display::DisplayLinkItem::dispatch_(CA::SignPost::Interval<(CA::SignPost::CAEventCode)835322056>&) + 48 (CADisplay.mm:5751)
11  QuartzCore                    	0x000000019b05b0e8 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 876 (CADisplay.mm:4994)
12  QuartzCore                    	0x000000019b05ac88 CA::Display::DisplayLink::dispatch_deferred_display_links(unsigned int) + 352 (CADisplay.mm:4119)
13  UIKitCore                     	0x000000019bc52660 _UIUpdateSequenceRun + 84 (_UIUpdateSequence.mm:119)
14  UIKitCore                     	0x000000019bc522a4 schedulerStepScheduledMainSection + 172 (_UIUpdateScheduler.m:1058)
15  UIKitCore                     	0x000000019bc53148 runloopSourceCallback + 92 (_UIUpdateScheduler.m:1221)
16  CoreFoundation                	0x000000019996f834 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28 (CFRunLoop.c:1957)
17  CoreFoundation                	0x000000019996f7c8 __CFRunLoopDoSource0 + 176 (CFRunLoop.c:2001)
18  CoreFoundation                	0x000000019996d298 __CFRunLoopDoSources0 + 244 (CFRunLoop.c:2038)
19  CoreFoundation                	0x000000019996c484 __CFRunLoopRun + 828 (CFRunLoop.c:2955)
20  CoreFoundation                	0x000000019996bcd8 CFRunLoopRunSpecific + 608 (CFRunLoop.c:3420)
21  GraphicsServices              	0x00000001de3b91a8 GSEventRunModal + 164 (GSEvent.c:2196)
22  UIKitCore                     	0x000000019bfa5ae8 -[UIApplication _run] + 888 (UIApplication.m:3713)
23  UIKitCore                     	0x000000019c059d98 UIApplicationMain + 340 (UIApplication.m:5303)
24  blockyballot                  	0x00000001016efa6c main + 120
25  dyld                          	0x00000001bd143154 start + 2356 (dyldMain.cpp:1298)

Thread 1:
0   libsystem_pthread.dylib       	0x00000001f63e90c4 start_wqthread + 0 (:-1)

Thread 2:
0   libsystem_pthread.dylib       	0x00000001f63e90c4 start_wqthread + 0 (:-1)

Thread 3:
0   libsystem_pthread.dylib       	0x00000001f63e90c4 start_wqthread + 0 (:-1)

Thread 4:
0   libsystem_pthread.dylib       	0x00000001f63e90c4 start_wqthread + 0 (:-1)

Thread 5 name:
Thread 5:
0   libsystem_kernel.dylib        	0x00000001e25f16c8 mach_msg2_trap + 8 (:-1)
1   libsystem_kernel.dylib        	0x00000001e25f4ec8 mach_msg2_internal + 80 (mach_msg.c:201)
2   libsystem_kernel.dylib        	0x00000001e25f4de0 mach_msg_overwrite + 436 (mach_msg.c:0)
3   libsystem_kernel.dylib        	0x00000001e25f4c20 mach_msg + 24 (mach_msg.c:323)
4   libdispatch.dylib             	0x00000001a185db18 _dispatch_mach_send_and_wait_for_reply + 544 (mach.c:1980)
5   libdispatch.dylib             	0x00000001a185deb8 dispatch_mach_send_with_result_and_wait_for_reply + 60 (mach.c:2017)
6   libxpc.dylib                  	0x00000001f643cac8 xpc_connection_send_message_with_reply_sync + 264 (connection.c:3985)
7   Metal                         	0x00000001995eaedc XPCCompilerConnection::checkConnectionActive(bool&) + 184 (MTLCompilerConnection.mm:1435)
8   Metal                         	0x0000000199545300 XPCCompilerConnection::BuildRequestInternal(MTLCompilerRequest*, char const*, NSObject<OS_dispatch_data>*, int, bool, void (unsigned int, void const*, unsigned long, char const*) block_pointer) + 1100 (MTLCompilerConnection.mm:1832)
9   libdispatch.dylib             	0x00000001a184113c _dispatch_call_block_and_release + 32 (init.c:1530)
10  libdispatch.dylib             	0x00000001a1842dd4 _dispatch_client_callout + 20 (object.m:576)
11  libdispatch.dylib             	0x00000001a184a400 _dispatch_lane_serial_drain + 748 (queue.c:3900)
12  libdispatch.dylib             	0x00000001a184af64 _dispatch_lane_invoke + 432 (queue.c:3991)
13  libdispatch.dylib             	0x00000001a1855cb4 _dispatch_root_queue_drain_deferred_wlh + 288 (queue.c:6998)
14  libdispatch.dylib             	0x00000001a1855528 _dispatch_workloop_worker_thread + 404 (queue.c:6592)
15  libsystem_pthread.dylib       	0x00000001f63ec934 _pthread_wqthread + 288 (pthread.c:2696)
16  libsystem_pthread.dylib       	0x00000001f63e90cc start_wqthread + 8 (:-1)

Thread 6:
0   libsystem_pthread.dylib       	0x00000001f63e90c4 start_wqthread + 0 (:-1)

Thread 7 name:
Thread 7:
0   libsystem_kernel.dylib        	0x00000001e25f16c8 mach_msg2_trap + 8 (:-1)
1   libsystem_kernel.dylib        	0x00000001e25f4ec8 mach_msg2_internal + 80 (mach_msg.c:201)
2   libsystem_kernel.dylib        	0x00000001e25f4de0 mach_msg_overwrite + 436 (mach_msg.c:0)
3   libsystem_kernel.dylib        	0x00000001e25f4c20 mach_msg + 24 (mach_msg.c:323)
4   CoreFoundation                	0x000000019996cf5c __CFRunLoopServiceMachPort + 160 (CFRunLoop.c:2624)
5   CoreFoundation                	0x000000019996c600 __CFRunLoopRun + 1208 (CFRunLoop.c:3007)
6   CoreFoundation                	0x000000019996bcd8 CFRunLoopRunSpecific + 608 (CFRunLoop.c:3420)
7   Foundation                    	0x000000019888cb5c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212 (NSRunLoop.m:373)
8   Foundation                    	0x000000019888c9ac -[NSRunLoop(NSRunLoop) runUntilDate:] + 64 (NSRunLoop.m:420)
9   UIKitCore                     	0x000000019bfb981c -[UIEventFetcher threadMain] + 420 (UIEventFetcher.m:1207)
10  Foundation                    	0x00000001988a3428 __NSThread__start__ + 732 (NSThread.m:991)
11  libsystem_pthread.dylib       	0x00000001f63ee06c _pthread_start + 136 (pthread.c:931)
12  libsystem_pthread.dylib       	0x00000001f63e90d8 thread_start + 8 (:-1)

Thread 8:
0   libsystem_kernel.dylib        	0x00000001e25f708c __psynch_cvwait + 8 (:-1)
1   libsystem_pthread.dylib       	0x00000001f63eb6e4 _pthread_cond_wait + 1228 (pthread_cond.c:862)
2   libc++.1.dylib                	0x00000001a9d59504 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28 (condition_variable.cpp:45)
3   blockyballot                  	0x00000001046fa190 _IP_ResolverPrivate::_thread_function(void*) + 164
4   blockyballot                  	0x0000000102478760 Thread::thread_callback(void*) + 220
5   libsystem_pthread.dylib       	0x00000001f63ee06c _pthread_start + 136 (pthread.c:931)
6   libsystem_pthread.dylib       	0x00000001f63e90d8 thread_start + 8 (:-1)

Thread 9 name:
Thread 9:
0   libsystem_kernel.dylib        	0x00000001e25f708c __psynch_cvwait + 8 (:-1)
1   libsystem_pthread.dylib       	0x00000001f63eb6e4 _pthread_cond_wait + 1228 (pthread_cond.c:862)
2   libc++.1.dylib                	0x00000001a9d59504 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28 (condition_variable.cpp:45)
3   blockyballot                  	0x0000000104c7df9c WorkerThreadPool::_thread_function(void*) + 532
4   blockyballot                  	0x0000000102478760 Thread::thread_callback(void*) + 220
5   libsystem_pthread.dylib       	0x00000001f63ee06c _pthread_start + 136 (pthread.c:931)
6   libsystem_pthread.dylib       	0x00000001f63e90d8 thread_start + 8 (:-1)

Thread 10 name:
Thread 10:
0   libsystem_kernel.dylib        	0x00000001e25f708c __psynch_cvwait + 8 (:-1)
1   libsystem_pthread.dylib       	0x00000001f63eb6e4 _pthread_cond_wait + 1228 (pthread_cond.c:862)
2   libc++.1.dylib                	0x00000001a9d59504 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28 (condition_variable.cpp:45)
3   blockyballot                  	0x0000000104c7df9c WorkerThreadPool::_thread_function(void*) + 532
4   blockyballot                  	0x0000000102478760 Thread::thread_callback(void*) + 220
5   libsystem_pthread.dylib       	0x00000001f63ee06c _pthread_start + 136 (pthread.c:931)
6   libsystem_pthread.dylib       	0x00000001f63e90d8 thread_start + 8 (:-1)

Thread 11 name:
Thread 11:
0   libsystem_kernel.dylib        	0x00000001e25f708c __psynch_cvwait + 8 (:-1)
1   libsystem_pthread.dylib       	0x00000001f63eb6e4 _pthread_cond_wait + 1228 (pthread_cond.c:862)
2   libc++.1.dylib                	0x00000001a9d59504 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28 (condition_variable.cpp:45)
3   blockyballot                  	0x0000000104c7df9c WorkerThreadPool::_thread_function(void*) + 532
4   blockyballot                  	0x0000000102478760 Thread::thread_callback(void*) + 220
5   libsystem_pthread.dylib       	0x00000001f63ee06c _pthread_start + 136 (pthread.c:931)
6   libsystem_pthread.dylib       	0x00000001f63e90d8 thread_start + 8 (:-1)

Thread 12 name:
Thread 12:
0   libsystem_kernel.dylib        	0x00000001e25f708c __psynch_cvwait + 8 (:-1)
1   libsystem_pthread.dylib       	0x00000001f63eb6e4 _pthread_cond_wait + 1228 (pthread_cond.c:862)
2   libc++.1.dylib                	0x00000001a9d59504 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28 (condition_variable.cpp:45)
3   blockyballot                  	0x0000000104c7df9c WorkerThreadPool::_thread_function(void*) + 532
4   blockyballot                  	0x0000000102478760 Thread::thread_callback(void*) + 220
5   libsystem_pthread.dylib       	0x00000001f63ee06c _pthread_start + 136 (pthread.c:931)
6   libsystem_pthread.dylib       	0x00000001f63e90d8 thread_start + 8 (:-1)

Thread 13 name:
Thread 13:
0   libsystem_kernel.dylib        	0x00000001e25f708c __psynch_cvwait + 8 (:-1)
1   libsystem_pthread.dylib       	0x00000001f63eb6e4 _pthread_cond_wait + 1228 (pthread_cond.c:862)
2   libc++.1.dylib                	0x00000001a9d59504 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28 (condition_variable.cpp:45)
3   blockyballot                  	0x0000000104c7df9c WorkerThreadPool::_thread_function(void*) + 532
4   blockyballot                  	0x0000000102478760 Thread::thread_callback(void*) + 220
5   libsystem_pthread.dylib       	0x00000001f63ee06c _pthread_start + 136 (pthread.c:931)
6   libsystem_pthread.dylib       	0x00000001f63e90d8 thread_start + 8 (:-1)

Thread 14 name:
Thread 14:
0   libsystem_kernel.dylib        	0x00000001e25f708c __psynch_cvwait + 8 (:-1)
1   libsystem_pthread.dylib       	0x00000001f63eb6e4 _pthread_cond_wait + 1228 (pthread_cond.c:862)
2   libc++.1.dylib                	0x00000001a9d59504 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28 (condition_variable.cpp:45)
3   blockyballot                  	0x0000000104c7df9c WorkerThreadPool::_thread_function(void*) + 532
4   blockyballot                  	0x0000000102478760 Thread::thread_callback(void*) + 220
5   libsystem_pthread.dylib       	0x00000001f63ee06c _pthread_start + 136 (pthread.c:931)
6   libsystem_pthread.dylib       	0x00000001f63e90d8 thread_start + 8 (:-1)

Thread 15 name:
Thread 15:
0   libsystem_kernel.dylib        	0x00000001e25f16c8 mach_msg2_trap + 8 (:-1)
1   libsystem_kernel.dylib        	0x00000001e25f4ec8 mach_msg2_internal + 80 (mach_msg.c:201)
2   libsystem_kernel.dylib        	0x00000001e25f4de0 mach_msg_overwrite + 436 (mach_msg.c:0)
3   libsystem_kernel.dylib        	0x00000001e25f4c20 mach_msg + 24 (mach_msg.c:323)
4   CoreFoundation                	0x000000019996cf5c __CFRunLoopServiceMachPort + 160 (CFRunLoop.c:2624)
5   CoreFoundation                	0x000000019996c600 __CFRunLoopRun + 1208 (CFRunLoop.c:3007)
6   CoreFoundation                	0x000000019996bcd8 CFRunLoopRunSpecific + 608 (CFRunLoop.c:3420)
7   CoreFoundation                	0x00000001999d9f04 CFRunLoopRun + 64 (CFRunLoop.c:3446)
8   CoreMotion                    	0x00000001a6680e3c CLMotionCore::runMotionThread(void*) + 1292 (CLMotionCore.mm:376)
9   libsystem_pthread.dylib       	0x00000001f63ee06c _pthread_start + 136 (pthread.c:931)
10  libsystem_pthread.dylib       	0x00000001f63e90d8 thread_start + 8 (:-1)

Thread 16 name:
Thread 16:
0   libsystem_kernel.dylib        	0x00000001e25f1644 semaphore_wait_trap + 8 (:-1)
1   caulk                         	0x000000020b787724 caulk::semaphore::timed_wait(double) + 212 (semaphore.cpp:98)
2   caulk                         	0x000000020b7875e4 caulk::concurrent::details::worker_thread::run() + 36 (messenger.cpp:234)
3   caulk                         	0x000000020b78752c void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 96 (thread.h:189)
4   libsystem_pthread.dylib       	0x00000001f63ee06c _pthread_start + 136 (pthread.c:931)
5   libsystem_pthread.dylib       	0x00000001f63e90d8 thread_start + 8 (:-1)

Thread 17 name:
Thread 17:
0   libsystem_kernel.dylib        	0x00000001e25f1644 semaphore_wait_trap + 8 (:-1)
1   caulk                         	0x000000020b787724 caulk::semaphore::timed_wait(double) + 212 (semaphore.cpp:98)
2   caulk                         	0x000000020b7875e4 caulk::concurrent::details::worker_thread::run() + 36 (messenger.cpp:234)
3   caulk                         	0x000000020b78752c void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 96 (thread.h:189)
4   libsystem_pthread.dylib       	0x00000001f63ee06c _pthread_start + 136 (pthread.c:931)
5   libsystem_pthread.dylib       	0x00000001f63e90d8 thread_start + 8 (:-1)

Thread 18 name:
Thread 18:
0   libsystem_kernel.dylib        	0x00000001e25f16c8 mach_msg2_trap + 8 (:-1)
1   libsystem_kernel.dylib        	0x00000001e25f4ec8 mach_msg2_internal + 80 (mach_msg.c:201)
2   libsystem_kernel.dylib        	0x00000001e25f4de0 mach_msg_overwrite + 436 (mach_msg.c:0)
3   libsystem_kernel.dylib        	0x00000001e25f4c20 mach_msg + 24 (mach_msg.c:323)
4   libEmbeddedSystemAUs.dylib    	0x0000000214fb28b8 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, AURemoteIO::IOThread::IOThread(AURemoteIO&, caulk::thread::attributes const&, caulk::mach::os_workgroup_managed const&)::'lambda... + 556 (thread.h:189)
5   libsystem_pthread.dylib       	0x00000001f63ee06c _pthread_start + 136 (pthread.c:931)
6   libsystem_pthread.dylib       	0x00000001f63e90d8 thread_start + 8 (:-1)


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x000000010bf84cc0   x1: 0x000000016f0b5d20   x2: 0x000000016f0b5d18   x3: 0x0000000000000000
    x4: 0x000000010bfb6308   x5: 0x0000000100000014   x6: 0x0000000300ef9680   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x0000000000000001  x10: 0x00000000000000b7  x11: 0x000000010512db7a
   x12: 0x0000000300ef9680  x13: 0x00000000001ff800  x14: 0x00000000000007fb  x15: 0x000000009865205b
   x16: 0x000000000000005a  x17: 0x000000009885185d  x18: 0x0000000000000000  x19: 0x000000010af62ca0
   x20: 0x00000000000000b8  x21: 0x000000010bf86fd8  x22: 0x000000010bfb62b0  x23: 0x000000010bfb62f8
   x24: 0x0000000000000000  x25: 0x0000000000000048  x26: 0x000000010c0aeed0  x27: 0x0000000000000001
   x28: 0x0000000000000000   fp: 0x000000016f0b5c50   lr: 0x0000000103ff1154
    sp: 0x000000016f0b5c40   pc: 0x0000000102797fec cpsr: 0x60001000
   esr: 0x92000006 (Data Abort) byte read Translation fault


Binary Images:
        0x100d48000 -         0x1057cffff blockyballot arm64  <c52abfa8d147311ea0b586f8381f7d1c> /private/var/containers/Bundle/Application/29A33647-A9E6-469B-8D6F-AED71D37297B/blockyballot.app/blockyballot
        0x106014000 -         0x10601ffff libobjc-trampolines.dylib arm64e  <be553713db163c12aaa48fd6211e48ce> /private/preboot/Cryptexes/OS/usr/lib/libobjc-trampolines.dylib
        0x10656c000 -         0x109c53fff BlockyBallOT arm64  <bc96913f811f346d87756adcc26aa83a> /private/var/containers/Bundle/Application/29A33647-A9E6-469B-8D6F-AED71D37297B/blockyballot.app/Frameworks/BlockyBallOT.framework/BlockyBallOT
        0x1987c5000 -         0x19933afff Foundation arm64e  <d27a6ec5943c3b0e8d158840fd2914f0> /System/Library/Frameworks/Foundation.framework/Foundation
        0x1994f8000 -         0x19970cfff Metal arm64e  <f8cf586733e33e80aaf96f0c8b68730f> /System/Library/Frameworks/Metal.framework/Metal
        0x199919000 -         0x199e46fff CoreFoundation arm64e  <76a3b1983c09323e83590d4978e156f5> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
        0x19af8b000 -         0x19b319fff QuartzCore arm64e  <aedc1a5617313315a87ec6610024a405> /System/Library/Frameworks/QuartzCore.framework/QuartzCore
        0x19bb9b000 -         0x19d6bcfff UIKitCore arm64e  <9da0d27355063712b73de0149d74c13c> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
        0x1a183f000 -         0x1a1885fff libdispatch.dylib arm64e  <5f66cdb608a936158c6a4e3b47005495> /usr/lib/system/libdispatch.dylib
        0x1a1886000 -         0x1a1903ff3 libsystem_c.dylib arm64e  <7135c2c8ba5836368b46a9e6226ead45> /usr/lib/system/libsystem_c.dylib
        0x1a6671000 -         0x1a6b3ffff CoreMotion arm64e  <5d6e7429116638b3807bdfad246f9132> /System/Library/Frameworks/CoreMotion.framework/CoreMotion
        0x1a9d4c000 -         0x1a9dd5fff libc++.1.dylib arm64e  <febfb476c9003e0d8b93f22b586104ac> /usr/lib/libc++.1.dylib
        0x1bd106000 -         0x1bd193937 dyld arm64e  <52039c944da13638bd52020a0b5fa399> /usr/lib/dyld
        0x1de3b8000 -         0x1de3c0fff GraphicsServices arm64e  <3ebbd576e7d83f69bcb5b9810ddcc90e> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
        0x1e25f0000 -         0x1e2629fef libsystem_kernel.dylib arm64e  <21ee5290d1193c31b948431865a67738> /usr/lib/system/libsystem_kernel.dylib
        0x1f63e8000 -         0x1f63f4ff3 libsystem_pthread.dylib arm64e  <e4a9d6dbf93b3c88bdd185671ec22e2b> /usr/lib/system/libsystem_pthread.dylib
        0x1f642c000 -         0x1f6474fff libxpc.dylib arm64e  <cd0f76a8713a3fdb877e386b089bc2d1> /usr/lib/system/libxpc.dylib
        0x20b77f000 -         0x20b7a8fff caulk arm64e  <e5c09db9103f38c798201fb237c06434> /System/Library/PrivateFrameworks/caulk.framework/caulk
        0x214f83000 -         0x215093ff7 libEmbeddedSystemAUs.dylib arm64e  <c9ab992184f835fca25573acb5e2fbd5> /System/Library/Frameworks/AudioToolbox.framework/libEmbeddedSystemAUs.dylib

EOF
```

</details>

### Steps to reproduce

- Export an ios project to ios version 17
- See that it crashes

NOTE:

This is on one of our users devices.  I have been unable to acquire another ios with version 17 to see if it crashes.  This was the common denominator at the time though.

### Minimal reproduction project (MRP)

NA

### PR DESCRIPTION
**Pull request by stuartcarnie**
Closes #109846

# Summary

Ensure baked Metal binaries can be loaded on the minimum target OS for the exported Apple platform.

Supersedes:

- #110244

> [!NOTE]
>
> This PR incorporates PR #110244 to specify the `<os>-version-min` argument, but performs additional runtime checks to ensure the shader can be loaded by the target OS. Further, it uses the Metal toolchain to provide details about the target OS and Metal shader language to ensure SPIR-V → Metal succeeds by not enabling features that may be unavailable for the target OS.

# Background

Originally, #109846 reported that baked shaders would not load due to the target OS (iOS 17.x) Metal language being lower than the `.metallib` binary being loaded:

```text
drivers/metal/rendering_device_driver_metal.mm:2435:compute_pipeline_create(): error creating pipeline: Function main0 is using language version 3.2 which is incompatible with this OS. Condition "error != nullptr" is true. Returning: PipelineID()
```

The first fix, #110063, attempted to address that by setting the default minimum Metal version to 3.1, which is available on iOS 17.x and the device being validate per [this comment](https://github.com/godotengine/godot/issues/109846#issuecomment-3229210794):

```
Metal 3.1 - Forward Mobile - Using Device #0: Apple - Apple A15 GPU (Apple8)
```

This change succeeded in suppressing the error; however, a new issue surfaced regarding an incompatibility with the `.metallib` being loaded per [this comment](https://github.com/godotengine/godot/issues/109846#issuecomment-3250099771):

```text
drivers/metal/rendering_device_driver_metal.mm:2440:compute_pipeline_create(): error creating pipeline: Function main0 has a deployment target (0x00020007) which is incompatible with this OS (0x00020006). Condition "error != nullptr" is true. Returning: PipelineID()
```

This second issue was due to the compilation logic not specifying the `<os>-version-min` argument to the Metal compiler toolchain, thus using the toolchain default, which for Xcode 16 would be iOS 18:

https://github.com/godotengine/godot/blob/3c7f9b937214068bc892be0d2bd9a8a7026edae1/drivers/metal/rendering_shader_container_metal.mm#L118-L127

@TCROC discovered this and introduced PR #110244 to address this. This PR incorporated those changes and added these additional changes:

## Determine OS and Metal language from toolchain

To ensure the generated SPIR-V targets the correct Metal language, the Metal compiler toolchain is inspected to extract some preprocessor variables, essentially running and parsing the following:

```sh
echo "" | xcrun -sdk iphoneos metal -mios-version-min=17.0 -E -dM -x metal - | grep -E "__METAL_VERSION__|__ENVIRONMENT_OS"
```
```
#define __ENVIRONMENT_OS_VERSION_MIN_REQUIRED__ 170000
#define __METAL_VERSION__ 310
```

Here we can see that targeting iOS 17 uses the Metal 310 or 3.1 language standard. The shader baker parses this and ensures SPIRV-Cross generates Metal source for Metal 3.1 and then executes the compiler toolchain with the same arguments.

> [!IMPORTANT]
>
> This override only takes place when baking shaders. Under normal conditions, recompiling shaders will target the highest Metal language standard available on the target device.

## Perform runtime checks in the Metal driver

At runtime in the [`shader_create_from_container`](https://github.com/godotengine/godot/blob/3c7f9b937214068bc892be0d2bd9a8a7026edae1/drivers/metal/rendering_device_driver_metal.mm#L1126) function, further checks are performed to ensure the baked shader can be loaded.

### CODE REVIEW

**Comment by TCROC** [comment]
@stuartcarnie

### Edit

Moved the comment over here: https://github.com/godotengine/godot/pull/110244#issuecomment-3256908430

**Comment by Zireael07** [comment]
I'm thinking this would be better with a comment explaining that the two must match and why

**Comment by stuartcarnie** [comment]
@DarioSamo / @bruvzg this is a derivative of #110244. It no longer requires a `get_customization_configuration_info` function, as the minimum OS version and metal versions are already included in the serialised header data, which will affect the SHA hash.

File: drivers/metal/rendering_shader_container_metal.mm [hunk 1]
```diff
@@ -85,6 +86,71 @@
...
+		return;
+	}
+
+	String sdk;
+	switch (device_profile->platform) {
+		case MetalDeviceProfile::Platform::macOS:
+			sdk = "macosx";
+			break;
+		case MetalDeviceProfile::Platform::iOS:
+			sdk = "iphoneos";
```
Comment (clayjohn) [inline drivers/metal/rendering_shader_container_metal.mm:100]: Does this cover iPadOS too?

Comment (bruvzg) [reply drivers/metal/rendering_shader_container_metal.mm:100]: In terms of SDK/compilation, there's no such thing as iPadOS, it's the same iOS for both.

Comment (clayjohn) [reply drivers/metal/rendering_shader_container_metal.mm:100]: Awesome, that's what I was wondering!

**Review by clayjohn — APPROVED** [review]
Looks good to me!

**Comment by clayjohn** [comment]
Let's go ahead and merge this and then wait for @TCROC's testing before releasing RC2!

**Review by bruvzg — APPROVED** [review]
Code looks good. But I do not have any old devices to test.

**Comment by TCROC** [comment]
@bruvzg @clayjohn @stuartcarnie Just tested on the ``17.6.1`` device.  Can confirm everything works as expected!  I don't have permissions to approve so here is my poor man's green check mark ✅ :)

Great work everyone!  It was a pleasure collabing with all of you on this PR!  It was very tricky since the actual behavior diverged from Apple's docs leaving us to piece together our own docs.  And special shoutout again to @stuartcarnie for being an absolute legend! 😎

**Comment by clayjohn** [comment]
Thanks everyone! Great work. I am very happy to have this fixed before RC2!
