### PR TITLE
Fixes Tab Switching of Main Scene State. Closes #11045

### LINKED ISSUE #11045: Editing a project always opens the 3D view at first, even if there are no 3D nodes in the default scene
**Operating system or device, Godot version, GPU Model and driver (if graphics related):** Windows 10, Godot Git https://github.com/godotengine/godot/commit/5f0d367fef25b30742ba71f12e339137e02c59ab

**Issue description:** Opening a project (in my case, I'm working on a Godot console, which only uses 2D nodes) will always open the 3D view in the editor, even if the project doesn't use any 3D nodes. In 2.1.4, the 2D view is opened if the project's default scene does not contain any 3D nodes, which is a more logical behavior.

**Steps to reproduce:** Open a 2D-only project in a 3.0 development build.

### PR DESCRIPTION
**Pull request by ISylvox**
- Also, could help to solve https://github.com/godotengine/godot/issues/10405

mainscenestate_fixed

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -2741,47 +2741,42 @@ Dictionary EditorNode::_get_main_scene_state() {
 	state["property_edit_offset"] = get_property_editor()->get_scene_tree()->get_vscroll_bar()->get_value();
 	state["saved_version"] = saved_version;
 	state["node_filter"] = scene_tree_dock->get_filter();
+	return state;
+}
+
+void EditorNode::_set_main_scene_state(Dictionary p_state, Node *p_for_scene) {
+
 	int current = -1;
+	int index = p_state["editor_index"];
```
Comment (akien-mga) [inline editor/editor_node.cpp]: It would be better to move that back where it's actually used, because:
- it's more readable
- it will crash if `!p_state.has("editor_index")`

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -2741,47 +2741,42 @@ Dictionary EditorNode::_get_main_scene_state() {
...
+	int n2d = 0, n3d = 0;
```
Comment (akien-mga) [inline editor/editor_node.cpp]: It would also be clearer if those were defined where they used to be, no other code chunk needs them so they don't need to be in the main scope. Remember that this is C++, not C, you don't have to (and shouldn't, unless relevant) declare local variables upfront in a method.

File: editor/editor_node.cpp [hunk 3]
```diff
@@ -2741,47 +2741,42 @@ Dictionary EditorNode::_get_main_scene_state() {
...
 	for (int i = 0; i < editor_table.size(); i++) {
```
Comment (akien-mga) [inline editor/editor_node.cpp]: It would be more readable if that `for` loop (and the related `int current` declaration came just before the `if (p_state.has("editor_index"))`. The early return at line 2759 should come first as it used to.

**Comment by reduz** [comment]
Possibly my fault

On Sep 13, 2017 7:01 AM, "Rémi Verschelde" <notifications@github.com> wrote:

*@akien-mga* commented on this pull request.
------------------------------

In editor/editor_node.cpp
<https://github.com/godotengine/godot/pull/11075#discussion_r138576173>:

>  	int current = -1;
+	int index = p_state["editor_index"];
+	int n2d = 0, n3d = 0;
 	for (int i = 0; i < editor_table.size(); i++) {

It would be more readable if that for loop (and the related int current
declaration came just before the if (p_state.has("editor_index")). The
early return at line 2759 should come first as it used to.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/pull/11075#pullrequestreview-62387108>,
or mute the thread

**Comment by ISylvox** [comment]
Just updated. :-)

**Review by akien-mga — APPROVED** [review]
