### PR TITLE
Fix editor-only visibility for lights

### LINKED ISSUE #26399: Duplicating a editor_only Light turns it dark
**Godot version:** f2003b1a7e5d3fce6448bd578a15bbf8f9462183

**OS/device including version:** Linux/X11 Intel graphics

**Issue description:**

When a light with the `editor_only` property set is duplicated, then the duplicate light will not work in the editor (which is unexpected. It should shine). Unsetting the `editor_only`-property on that duplicate will turn it back on, and setting the property again will keep it on in the editor (which is expected).

**Steps to reproduce:**
1. Create a scene with only a Cube MeshInstance
2. Create an OmniLight or a DirectionalLight (or probably a SpotLight, not tested) and position it such that one face of the cube is lit.
3. Turn on its `editor_only` option. It will still light the cube in the editor.
3. Right-click the light in the` scene tree and choose "duplicate".
4. Move the newly created light so that it should light a different face of the cube. Notice that it does not light the face.
5. Uncheck and re-check `editor_only` on that second light. Now it will lights the face.

### PR DESCRIPTION
**Pull request by reduz**
* Update visibility again for editor-only lights if owner changes.

Fixes #26399, supersedes #52327

### CODE REVIEW

File: scene/3d/light_3d.cpp [hunk 1]
```diff
@@ -176,6 +176,11 @@ Ref<Texture2D> Light3D::get_projector() const {
 	return projector;
 }
 
+void Light3D::owner_changed_notify() {
+	// For cases where owner changes _after_ entering tree (as example, editor editing).
```
Comment (akien-mga) [inline scene/3d/light_3d.cpp:180]: Sounds like a comment that should go in `node.cpp/h` to clarify what this core API is for.

Comment (reduz) [reply scene/3d/light_3d.cpp:180]: I could add one there (though the function is quite self explanatory by name), but this comment is meant specifically for these nodes, because the editor-only lights need to check the owner to verify they are in the right scene and hence see that it must be enabled or disabled.

**Review by JFonS — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.
