### PR TITLE
Prevent off-thread errors when generating resource previews for animation nodes

### LINKED ISSUE #102106: Off-thread access error spam in specific case from AnimationTree
### Tested versions

Reproducible on and after [53f3143028134bef517f1f598acd7f33a8bf8cf6] but I have no idea why this commit would be related. Bizarrely while initially bisecting I was only able to reproduce the error on mono builds and not standard, but after `git clean -fdx` and rebuilding to make sure I was only able to reproduce on standard and not mono.

### System information

Godot v4.4.beta.mono (6dc78c8aa) - macOS Sequoia (15.2.0) - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M2 (Apple8) - Apple M2 (8 threads)

### Issue description

This error gets printed out once per animation node within an animation tree (at least a blend tree) when opening the project and sometimes when running the project/opening a scene as well:
```
ERROR: This function in this node (/root/@EditorNode@21262/@Panel@14/@VBoxContainer@15/DockHSplitLeftL/DockHSplitLeftR/DockHSplitMain/@VBoxContainer@26/DockVSplitCenter/@EditorBottomPanel@7939/@VBoxContainer@7924/@AnimationTreeEditor@15287) can only be accessed from either the main thread or a thread group. Use call_deferred() instead.
   at: is_visible (scene/main/canvas_item.cpp:124)
```
at least in this case (I'm not sure if there are other triggering cases) `is_visible` is called by `AnimationTreeEditor::get_animation_list`. The error can be avoided by changing the condition in that method to:
```c++
if (!singleton->tree || !singleton->is_accessible_from_caller_thread() || !singleton->is_visible()) {
    [ .. ]
}
```
however this feels like a bad hack, especially without understanding the root cause

### Steps to reproduce

In an affected version, create an AnimationTree node with a blend tree root and add animation playback nodes to the tree. There doesn't need to be an animation library or an animation set on the node for the error to print. Save the scene and close + reopen the editor.

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/18742157/mrp.zip)

### PR DESCRIPTION
**Pull request by a-johnston**
Fixes https://github.com/godotengine/godot/issues/102106

This check could be moved to [`AnimationTreeEditor::get_animation_list`](https://github.com/godotengine/godot/blob/master/editor/plugins/animation_tree_editor_plugin.cpp#L237) if that's preferred.

### CODE REVIEW

File: scene/animation/animation_blend_tree.cpp [hunk 1]
```diff
@@ -79,7 +79,11 @@ AnimationNode::NodeTimeInfo AnimationNodeAnimation::get_node_time_info() const {
 
 void AnimationNodeAnimation::_validate_property(PropertyInfo &p_property) const {
 	if (p_property.name == "animation" && get_editable_animation_list) {
-		Vector<String> names = get_editable_animation_list();
+		Vector<String> names;
+		// Prevents off-main-thread errors when generating resource previews.
+		if (is_current_thread_safe_for_nodes()) {
```
Comment (akien-mga) [inline scene/animation/animation_blend_tree.cpp:84]: This is part of engine internals and AFAIK not really meant to be used throughout the codebase. You can see that current usage of this API is limited to core classes: Node and WorkerThreadPool.

So the problem might need a different solution that doesn't make wrong assumptions on thread safety.

CC @RandomShaper @TokageItLab

Comment (a-johnston) [reply scene/animation/animation_blend_tree.cpp:84]: Ah I didn't notice that. It makes sense why you wouldn't want random non-warning thread checks. The only small obvious other thing I can think of is if `get_animation_list` doesn't need to check `!singleton->is_visible()` - it seems like the rest of the method doesn't rely on it as a soft thread check but it does short circuit calls in some events such as reassigning the root node of the tree.

Comment (RandomShaper) [reply scene/animation/animation_blend_tree.cpp:84]: `get_editable_animation_list()` is meant to be called only from the main thread because it boils down to a function in some editor plugin (and editor APIs are in general meant to be used from the main thread only). Instead of `is_current_thread_safe_for_nodes()`,, you want to use `Thread::is_main_thread()`. The former worls because the main thread happens to be safe-for-nodes, but both checks aren't conceptually (nor practically) equivalent.

Comment (a-johnston) [reply scene/animation/animation_blend_tree.cpp:84]: Oh ok, I'll update to use that. I originally had that there but wasn't sure if other threads could be marked as safe, and that thread local marker is ultimately what `is_visible` uses (although I'm unsure why I didn't submit this with the exact same call the guard does)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by a-johnston** [comment]
Thanks for the quick reviews! It's probably still not ideal having this thread check instead of the other thread check but in the meantime I'll appreciate having fewer errors in console. If there's a suggestion for a better way to do it I'm open to changing this again.
