### PR TITLE
Wayland: Pass unmodified symbols to key events

### LINKED ISSUE #100713: Tooltips stops working after writing code
### Tested versions

Godot v4.4.dev7

Doesn't look like it happens on v4.4.dev6

### System information

Fedora Linux 40 (KDE Plasma) on Wayland - Wayland display driver, Single-window

### Issue description

Tooltips stops working after writing some code
Have only seen it happen with prefer Wayland on, so not sure if it can happen with other settings. It doesn't happen every time you write code, so might need to write more or less code until the bug triggers. 

https://github.com/user-attachments/assets/ddc2aa64-1cbd-4a5d-9151-79351a99d36c

### Steps to reproduce

Write code and then try to hover over something that triggers a tooltip with documentation help. 

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #100879: `keys_pressed` does not seem to accurately reflect the keys being pressed on Wayland
### Tested versions

- Reproducible in [75ce426](https://github.com/godotengine/godot/commit/75ce4266c4774b30ed5df67e6c43365418fcce5f) & 4.3

### System information

Manjaro Gnome Wayland

### Issue description

Keys pressed seems to not be reset sometimes. 

I noticed this issue because the method `is_anything_pressed` returns `true` when I was trying out the new tooltip feature, even it should be returning `false`. 
https://github.com/godotengine/godot/blob/75ce4266c4774b30ed5df67e6c43365418fcce5f/core/input/input.cpp#L298 

### Steps to reproduce

It seems like I can trigger it fairly consistently by searching and then opening a file in the filesystem browser.

https://github.com/user-attachments/assets/911fe0be-904b-400f-b83e-c25e32aadb4c

### Minimal reproduction project (MRP)

This is just a simple project with a tool script that calls `is_anything_pressed`
[project.zip](https://github.com/user-attachments/files/18267684/project.zip)

### PR DESCRIPTION
**Pull request by deralmas**
Fixes #100713
Fixes #100879

Before this change we would internationalize the keycode itself in all `InputEventKey`s, confusing the whole input subsystem.

### CODE REVIEW

File: platform/linuxbsd/wayland/wayland_thread.cpp [hunk 1]
```diff
@@ -193,12 +193,20 @@ Vector<uint8_t> WaylandThread::_wp_primary_selection_offer_read(struct wl_displa
 
 // Sets up an `InputEventKey` and returns whether it has any meaningful value.
 bool WaylandThread::_seat_state_configure_key_event(SeatState &p_ss, Ref<InputEventKey> p_event, xkb_keycode_t p_keycode, bool p_pressed) {
-	// TODO: Handle keys that release multiple symbols?
-	Key keycode = KeyMappingXKB::get_keycode(xkb_state_key_get_one_sym(p_ss.xkb_state, p_keycode));
+	// NOTE: xkbcommon's API really encourages to apply the modifier state but we
+	// only want a "plain" symbol so that we can convert it into a godot keycode.
+	const xkb_keysym_t *syms = nullptr;
+	int num_sys = xkb_keymap_key_get_syms_by_level(p_ss.xkb_keymap, p_keycode, p_ss.current_layout_index, 0, &syms);
```
Comment (bruvzg) [inline platform/linuxbsd/wayland/wayland_thread.cpp:199]: Is it possible to get more than one `keysym` here?

**Review by bruvzg — APPROVED** [review]
I can reproduce the issue (as described in https://github.com/godotengine/godot/issues/100713#issuecomment-2602363212) and confirm it is fixed.

File: platform/linuxbsd/wayland/wayland_thread.cpp (hunk 1 above)
Comment (bruvzg) [reply platform/linuxbsd/wayland/wayland_thread.cpp:199]: It's used only for `keycode`, and `keycode` should be limited to ASCII only. As long as it can't return codes for multiple events, it is probably fine to only handle the first one.

**Comment by Repiteo** [comment]
Thanks!

**Comment by tdaven** [comment]
@Riteo, For some reason this has broken the keypad for me when using Wayland on Fedora.  It is always stuck in num-lock off mode event when it is on.
