### PR TITLE
Don't return Tree items outside visible rect

### LINKED ISSUE #102146: Drag & Drop file to FileSystem dock saves it in the underlying directory behind the opened directory
### Tested versions

Reproducible in: 4.4-dev7 and 4.4-beta1
Not reproducible in: 4.4-dev6 and earlier builds, 4.3-stable

### System information

Godot v4.4.beta1 - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Wed Dec 11 22:24:04 UTC 2024 on X11 - X11 display driver, Single-window, 1 monitor - OpenGL 3 (Compatibility) - GeForce GT 520M (nvidia; 390.157) - Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz (4 threads)

### Issue description

Drag & Drop on split mode FileSystem dock (selected directory in that dock) saves the file in a directory behind the lower part of FileSystem dock if there is any.
I think I can show it in some screenshots:
- Scrollbar is at its lowest position so there's no part of the main dock under the 2nd part. This way the drag & drop works perfectly
Image
- 1 is the selected directory which is shown in part 3 in the screenshot. The scrollbar is not at its lowest position, so there is a part of it under part 3. So if I drag and drop a file from my system to part 3, it will be saved on the directory which is behind part 3 where the mouse position was on drop moment.

Image

https://github.com/user-attachments/assets/22903028-25c0-47b4-b4d2-6d6a59324a65

### Steps to reproduce

1. In the editor make the FileSystem dock splitted so the selected directory is shown under the main dock
2. Make some directories and subdirectories and open all of them (the arrow beside them are all pointing down) so the scrollbar is visible
3. Select one of the top directories so it is opened in the lower dock
4. Keep the scrollbar at its top position so there are some parts of the upper FileSystem dock is hidden behind the lower dock
5. Drag and drop a file from your system on the lower dock (opened directory in step 3)
6. The file will be saved on the directory behind this lower dock and not in the lower dock

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #102146
Likely needs some testing.

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -5708,6 +5708,10 @@ Variant Tree::get_drag_data(const Point2 &p_point) {
 }
 
 TreeItem *Tree::get_item_at_position(const Point2 &p_pos) const {
+	if (!Rect2(get_position(), get_size()).has_point(p_pos)) {
```
Comment (kleonc) [inline scene/gui/tree.cpp:5711]: AFAICT this method works in local coords, so the `position` is irrelevant here.

```suggestion
	if (!Rect2(Point2(), get_size()).has_point(p_pos)) {
```


Besides, there are other `Tree::get_{...}_at_position` methods having similar duplicated logic (and thus probably the same issue). Would make sense to refactor them so they'd have shared finding logic. But as a simple fix adding similar checks to them should do. :thinking:

**Comment by KoBeWi** [comment]
Added checks and early returns to all `at_position` methods, but it increased the scope a bit...

File: scene/gui/tree.cpp [hunk 2]
```diff
@@ -5494,22 +5494,30 @@ void Tree::_do_incr_search(const String &p_add) {
...
 
-TreeItem *Tree::_find_item_at_pos(TreeItem *p_item, const Point2 &p_pos, int &r_column, int &h, int &section) const {
+TreeItem *Tree::_find_item_at_pos(TreeItem *p_item, const Point2 &p_pos, int &r_column, int &r_height, int &r_section) const {
+	r_column = -1;
+	r_height = 0;
+	r_section = -1;
+
+	if (!root || !Rect2(Vector2(), get_size()).has_point(p_pos)) {
+		return nullptr;
+	}
```
Comment (kleonc) [inline scene/gui/tree.cpp:5504]: `_find_item_at_pos` shouldn't have the local rect check, AFAICT it takes in a position within the "unscrolled items area" (other methods before calling it account for the title and add scroll offsets, so it getting a position e.g. much bigger than size is valid/expected).

```suggestion
	if (!root) {
		return nullptr;
	}
```

Comment (kleonc) [reply scene/gui/tree.cpp:5504]: +It's an internal method so seems like `root` check is potentially not needed too. :thinking:

Comment (KoBeWi) [reply scene/gui/tree.cpp]: Also reverted `_find_button_at_pos()` (the two methods are now consistent).

File: scene/gui/tree.cpp [hunk 3]
```diff
@@ -5494,22 +5494,30 @@ void Tree::_do_incr_search(const String &p_add) {
 	ensure_cursor_is_visible();
 }
 
-TreeItem *Tree::_find_item_at_pos(TreeItem *p_item, const Point2 &p_pos, int &r_column, int &h, int &section) const {
+TreeItem *Tree::_find_item_at_pos(TreeItem *p_item, const Point2 &p_pos, int &r_column, int &r_height, int &r_section) const {
+	r_column = -1;
+	r_height = 0;
+	r_section = -1;
```
Comment (kleonc) [inline scene/gui/tree.cpp:5500]:
```suggestion
	r_section = -100;
```
`-1` is a valid section indicator, `get_drop_section_at_position` returns `-100` as invalid one, these should be consistent.
(and yeah, they could be constants...)

**Review by kleonc — COMMENTED** [review]
Overall LGTM, one more nitpick.

**Review by kleonc — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
