### PR TITLE
Fix CheckButton and CheckBox font hover pressed color override

### LINKED ISSUE #34727: CheckButton and CheckBox hover pressed color does not draw
___

***Bugsquad edit:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Godot version:**
3.2 beta 4

**Issue description:**
font_color_hover_pressed does not draw, when hovering/focusing them when they are pressed. The CheckButton and CheckBox just draws the font_color_pressed instead.

check button font color hover pressed

### PR DESCRIPTION
**Pull request by Geometror**
Co-authored-by: @fossegutten

Fixes: #34727

This PR allows to override the font color in the hover_pressed state (salvaged from #35094).

reverse_button_pressed_color

### CODE REVIEW

File: scene/gui/button.cpp [hunk 1]
```diff
@@ -138,8 +139,6 @@ void Button::_notification(int p_what) {
 						}
 						if (has_theme_color(SNAME("font_hover_pressed_color"))) {
 							color = get_theme_color(SNAME("font_hover_pressed_color"));
-						} else {
-							color = get_theme_color(SNAME("font_color"));
```
Comment (KoBeWi) [inline scene/gui/button.cpp:142]: This removal is not really necessary, but then again, it's super-unlikely that the `else` would be ever executed.

**Review by KoBeWi — APPROVED** [review]
Looks ok.

I find it weird that `font_hover_pressed_color` is defined in Button, but it depends on `hover_pressed` stylebox, which doesn't exist in Button. That's unrelated to the fixed issue however.

**Comment by pycbouh** [comment]
> I find it weird that `font_hover_pressed_color` is defined in Button, but it depends on `hover_pressed` stylebox, which doesn't exist in Button. That's unrelated to the fixed issue however.

It used to be all in button, but those styles were never used by the normal button itself. They can only be triggered by special states of `Check*` nodes. So the styles seem to have been appropriately moved at some point to the only nodes that can actually utilize them. But I agree, the overall setup get weird.

**Comment by KoBeWi** [comment]
Shouldn't `font_hover_pressed_color` be moved too?

**Comment by pycbouh** [comment]
Probably, yes

**Comment by akien-mga** [comment]
Thanks!
