### PR TITLE
Free script and extension instance before object deconstructing

### LINKED ISSUE #109762: GDExtension: Undefined behavior when calling base class methods in deconstructor
### Tested versions

Godot 4.4.1

### System information

Linux

### Issue description

In gdextension class deconstructor, calling base class method causes UB: 

```cpp
ExampleClass::~ExampleClass() {
	print_line("deconstruct");
	print_line(get_reference_count());
}
```

```
deconstruct
core/object/ref_counted.cpp:55:9: runtime error: member access within address 0x614000258850 which does not point to an object of type 'const RefCounted'
0x614000258850: note: object is of type 'Object'
 be be be be  30 f5 85 cc f3 55 00 00  68 b6 19 00 40 61 00 00  60 56 ba 00 40 60 00 00  be be be be
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'Object'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior core/object/ref_counted.cpp:55:9 in 
0
```

This is because the godot native instance is already being deconstructing when freeing gdextension instance, so it's UB for extension class to access any base class method except `Object` in deconstructor:
https://github.com/godotengine/godot/blob/8ebf8ae23c095d4185e79602bb18a6952e192b56/core/object/object.cpp#L2258-L2269

### Steps to reproduce

Build Godot with undefined behavior sanitizer, run a game with gdextension that calls base class methods (except `Object` methods) in deconstructor.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by beicause**
Fixes #109762, as suggested in https://github.com/godotengine/godot/issues/109762#issuecomment-3285471628. This seems to work in my test.

### CODE REVIEW

File: core/object/object.cpp [hunk 1]
```diff
@@ -258,6 +258,36 @@ bool Object::_predelete() {
 		_class_name_ptr = nullptr; // Must restore, so constructors/destructors have proper class name access at each stage.
 		notification(NOTIFICATION_PREDELETE_CLEANUP, true);
 	}
+
+	if (script_instance) {
```
Comment (Ivorforce) [inline core/object/object.cpp:266]: This should only execute if `_predelete_ok`.
We prefer early exit syntax, so please change the above lines to something like:

```c++
if (!_predelete_ok) {
	return false;
}

_class_name_ptr = nullptr; // Must restore, so constructors/destructors have proper class name access at each stage.
notification(NOTIFICATION_PREDELETE_CLEANUP, true);
```

File: core/object/object.cpp [hunk 2]
```diff
@@ -258,6 +258,36 @@ bool Object::_predelete() {
 		_class_name_ptr = nullptr; // Must restore, so constructors/destructors have proper class name access at each stage.
 		notification(NOTIFICATION_PREDELETE_CLEANUP, true);
 	}
+
```
Comment (Ivorforce) [inline core/object/object.cpp:260]: I think this could use a comment explaining the deletion order.
Something like this:

```c++
// Deletion order objects start with the most derived class, and progresses towards the base Object class:
// Script subclasses -> GDExtension subclasses -> C++ subclasses -> Object
```

**Review by Ivorforce — APPROVED** [review]
Looks good to me!

File: core/object/object.cpp [hunk 3]
```diff
@@ -254,10 +254,44 @@ Object::Connection::Connection(const Variant &p_variant) {
...
-		_class_name_ptr = nullptr; // Must restore, so constructors/destructors have proper class name access at each stage.
-		notification(NOTIFICATION_PREDELETE_CLEANUP, true);
+	if (!_predelete_ok) {
+		return false;
+	}
+
+	_class_name_ptr = nullptr; // Must restore, so constructors/destructors have proper class name access at each stage.
+	notification(NOTIFICATION_PREDELETE_CLEANUP, true);
+
+	// Deletion order objects start with the most derived class, and progresses towards the base Object class:
```
Comment (Ivorforce) [inline core/object/object.cpp]: This one's on me but
```suggestion
	// Destruction order starts with the most derived class, and progresses towards the base Object class:
```

File: core/object/object.cpp [hunk 4]
```diff
@@ -254,10 +254,44 @@ Object::Connection::Connection(const Variant &p_variant) {
...
+		GDExtensionManager *gdextension_manager = GDExtensionManager::get_singleton();
+		if (engine && gdextension_manager && engine->is_extension_reloading_enabled()) {
+			for (uint32_t i = 0; i < _instance_binding_count; i++) {
+				gdextension_manager->untrack_instance_binding(_instance_bindings[i].token, this);
+			}
+		}
+	}
+#endif
+
 	return _predelete_ok;
```
Comment (Ivorforce) [inline core/object/object.cpp]: There's no turning back at this point, this needs to return `true` now.

```suggestion
	return true;
```

**Review by Ivorforce — APPROVED** [review]

**Review by dsnopek — APPROVED** [review]
Thanks! Looks good to me :-)

**Comment by Repiteo** [comment]
Thanks!
