### PR TITLE
Fix StaticBody2D ignore in tileset bug

### LINKED ISSUE #14386: collision polygon node not displaying correctly
the indices on the collsion pollygon does not update or display correctly when using a texture size different than the default 64x64
this paticular case was using a 50x50 sprite
[Bug File.zip](https://github.com/godotengine/godot/files/1540125/Bug.File.zip)
go to the tileset scene and look at the hitboxes for the bug and then under the collision polygon node look at the indices under vector and notice that the positions do not correlate to the visual indicator nor do they correlate to how it is when it runs

### PR DESCRIPTION
**Pull request by swarnimarun**
Using staticbody2d position to affect the collision shape position whenever a tileset is created. Fix for #18090

This uses the xfrom() of staticbody2d transform to change the shape_transform origin.

This is also fixes #14386.

### CODE REVIEW

File: editor/plugins/tile_set_editor_plugin.cpp [hunk 1]
```diff
@@ -126,7 +126,7 @@ void TileSetEditor::_import_node(Node *p_node, Ref<TileSet> p_library) {
 				Transform2D shape_transform = sb->shape_owner_get_transform(E->get());
 				bool one_way = sb->is_shape_owner_one_way_collision_enabled(E->get());
 
-				shape_transform.set_origin(shape_transform.get_origin() - phys_offset);
```
Comment (reduz) [inline editor/plugins/tile_set_editor_plugin.cpp]: you can do:
```
 shape_transform[2] -=
```
instead if set/get origin. I still have the feeling something like this probably should use more matrix code.

Comment (swarnimarun) [reply editor/plugins/tile_set_editor_plugin.cpp]: will look into it.

Comment (swarnimarun) [reply editor/plugins/tile_set_editor_plugin.cpp]: Made some changes. Is it better.

File: editor/plugins/tile_set_editor_plugin.cpp [hunk 2]
```diff
@@ -126,8 +126,8 @@ void TileSetEditor::_import_node(Node *p_node, Ref<TileSet> p_library) {
 				Transform2D shape_transform = sb->shape_owner_get_transform(E->get());
 				bool one_way = sb->is_shape_owner_one_way_collision_enabled(E->get());
 
-				shape_transform.set_origin(shape_transform.get_origin() - phys_offset + sb->get_transform().xform(shape_transform.get_origin()));
-
+				shape_transform[2] -= phys_offset - sb->get_transform().xform(shape_transform[2]);
+
```
Comment (akien-mga) [inline editor/plugins/tile_set_editor_plugin.cpp]: There's trailing whitespace on this line.

Could you also squash the commits together? See [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase).

Comment (swarnimarun) [reply editor/plugins/tile_set_editor_plugin.cpp]: Fixed trailing spaces and squashed the commits.

File: editor/plugins/tile_set_editor_plugin.cpp (hunk 1 above)
Comment (swarnimarun) [reply editor/plugins/tile_set_editor_plugin.cpp]: Fixed all the mistakes and problems I am very sorry for any problems. 😳

**Comment by akien-mga** [comment]
Thanks!
