### PR TITLE
Only unload the library if the reloadable flag is true

### LINKED ISSUE #45952: Godot 3.2 branch crashes when using VR plugins (regression)
**Godot version:**
Godot 3.2.4 83e4e4dc52f37ea6a093ba72b2790aecdae502a5

**OS/device including version:**
Any

**Issue description:**
Due to #44617 Godot now crashes when using VR plugins as these implement functionality that is not solely using NativeScript. 
I think this code needs to listen to the `reloadable=false` setting for the library which was added to prevent the reloading the editor did for exactly this same crashing issue.

**Steps to reproduce:**
Run any VR project that uses the OpenVR or OpenXR plugins. The others may be effected but not 100% sure.

### PR DESCRIPTION
**Pull request by BastiaanOlij**
A recent change allowed Godot to unload a GDNative library when all script objects using it got destroyed. Unfortunately there are GDNative libraries that do more then just nativescript which now get unloaded while still in use.

We had similar issues with tool based libraries where Godot would unload a library when focus was lost so you could hotload a newly compiled library. To prevent this the `reloadable` flag was introduced. If set to false Godot will keep the GDNative library loaded until the application terminates.

This PR simply adheres to this same flag in order to prevent premature unloading of the library. 

Fixes #45952

### CODE REVIEW

File: modules/gdnative/nativescript/nativescript.cpp [hunk 1]
```diff
@@ -1729,8 +1729,10 @@ void NativeScriptLanguage::unregister_script(NativeScript *script) {
 
 			Map<String, Ref<GDNative>>::Element *G = library_gdnatives.find(script->lib_path);
 			if (G) {
-				G->get()->terminate();
-				library_gdnatives.erase(G);
+				if (G->get()->get_library()->is_reloadable()) {
```
Comment (akien-mga) [inline modules/gdnative/nativescript/nativescript.cpp:1732]: I guess you could group the two `if`s in one.

Comment (BastiaanOlij) [reply modules/gdnative/nativescript/nativescript.cpp]: No problem:)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
