### PR TITLE
Set a minimum zoom of 1% on the tileset editor

### LINKED ISSUE #57292: Cant zoom in after zooming out to 0% in tileset editor
### Godot version

Godot 4 alpha 1

### System information

Windows 10

### Issue description

In the tileset editor after zooming out all the way to 0%, zooming in does nothing
The only way to get it back is to reset the zoom.

### Steps to reproduce

1. Add TileMap node
2. Add a tileset to it
3. Zoom out of the tileset until it stops zooming (using mousewheel or - icon)
4. Try to zoom in using the mousewheel or the + icon.

The reproduction project below has a TileMap with the tileset I'm using.

### Minimal reproduction project

[4.0 alpha 1 tileset bug.zip](https://github.com/godotengine/godot/files/7946929/4.0.alpha.1.tileset.bug.zip)

### PR DESCRIPTION
**Pull request by Ev01**
Fixes #57292 where zooming out too much stops you from being able to zoom back in.

### CODE REVIEW

File: editor/plugins/tiles/tile_atlas_view.cpp [hunk 1]
```diff
@@ -95,6 +95,9 @@ Size2i TileAtlasView::_compute_alternative_tiles_control_size() {
 }
 
 void TileAtlasView::_update_zoom_and_panning(bool p_zoom_on_mouse_pos) {
+
```
Comment (KoBeWi) [inline editor/plugins/tiles/tile_atlas_view.cpp:98]: The blank line should be removed.

Comment (Ev01) [reply editor/plugins/tiles/tile_atlas_view.cpp]: okay fixed it

**Review by KoBeWi — APPROVED** [review]
Works alright (not sure about the EDSCALE part though).

**Comment by Ev01** [comment]
> Works alright (not sure about the EDSCALE part though).

Yeah, I put the EDSCALE part there because it's what `EditorZoomWidget::_update_zoom_label()` does to get the percentage. I'm not exactly sure what EDSCALE is and the bug could still happen if EDSCALE is 1000 or higher.

**Comment by KoBeWi** [comment]
EDSCALE is the scale of the editor (you can set it in Editor Settings). 1000 is insane value, so it won't be a problem.

**Comment by Ev01** [comment]
`CanvasItemEditor` does it like this:
```
// At top of file
#define MIN_ZOOM 1. / 128
#define MAX_ZOOM 128

// At top of zoom function
p_zoom = CLAMP(p_zoom, MIN_ZOOM, MAX_ZOOM);
```
Maybe this would be a better/more consistent way to do it?

**Comment by Ev01** [comment]
Setting a max zoom would also prevent reaching insane 40-digit zoom levels.

**Comment by Calinou** [comment]
I'd probably the clamp the zoom to a factor of 100 (that is, 10000%).

**Comment by Ev01** [comment]
After testing with different editor scales I discovered dividing by EDSCALE was unnecessary. I set the minimum zoom to 1% and the maximum to 10000%.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

We discussed this in a PR review meeting and found that this is fine as an ad hoc solution, but it would be good to rework things in `EditorZoomWidget` directly so that it can prevent reaching 0 and being unable to zoom in. Then existing editor plugins that use `EditorZoomWidget` could have their ad hoc clamping removed as this should be part of the `EditorZoomWidget` behavior.
