### PR TITLE
Spread direct lighting calculation for LightmapGI over several submissions

### LINKED ISSUE #98180: Lightmap bake crash at the beginning of the baking
### Tested versions

v4.4.dev.custom_build [708acdf1d]

### System information

Ubuntu 22.04
Edit: Nvidia 2060 6gb VRAM

### Issue description

Trying to bake lightin in the TPS demo gets this error at the beginning of the bake. Previous builds had no problem baking

```
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.4.dev.custom_build (708acdf1d440d9dcc7daa1fc5a457f1a2e125181)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42990) [0x73ae1d042990] (??:0)
[2] RenderingDeviceDriverVulkan::command_queue_execute_and_present(RenderingDeviceDriver::CommandQueueID, VectorView<RenderingDeviceDriver::SemaphoreID>, VectorView<RenderingDeviceDriver::CommandBufferID>, VectorView<RenderingDeviceDriver::SemaphoreID>, RenderingDeviceDriver::FenceID, VectorView<RenderingDeviceDriver::SwapChainID>) (/media/juan/NTFS1/dev/godot/drivers/vulkan/rendering_device_driver_vulkan.cpp:2456 (discriminator 2))
[3] RenderingDevice::_execute_frame(bool) (/media/juan/NTFS1/dev/godot/servers/rendering/rendering_device.cpp:5868 (discriminator 3))
[4] RenderingDevice::submit() (/media/juan/NTFS1/dev/godot/servers/rendering/rendering_device.cpp:5646)
[5] LightmapperRD::bake(Lightmapper::BakeQuality, bool, float, int, int, float, float, int, bool, bool, Lightmapper::GenerateProbes, Ref<Image> const&, Basis const&, bool (*)(float, String const&, void*, bool), void*, float) (/media/juan/NTFS1/dev/godot/modules/lightmapper_rd/lightmapper_rd.cpp:1734)
[6] LightmapGI::bake(Node*, String, bool (*)(float, String const&, void*, bool), void*) (/media/juan/NTFS1/dev/godot/scene/3d/lightmap_gi.cpp:1118 (discriminator 1))
[7] LightmapGIEditorPlugin::_bake_select_file(String const&) (/media/juan/NTFS1/dev/godot/editor/plugins/lightmap_gi_editor_plugin.cpp:71 (discriminator 2))
[8] LightmapGIEditorPlugin::_bake() (/media/juan/NTFS1/dev/godot/editor/plugins/lightmap_gi_editor_plugin.cpp:123 (discriminator 2))
[9] void call_with_variant_args_helper<__UnexistingClass>(__UnexistingClass*, void (__UnexistingClass::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (/media/juan/NTFS1/dev/godot/./core/variant/binder_common.h:309)
[10] void call_with_variant_args_dv<__UnexistingClass>(__UnexistingClass*, void (__UnexistingClass::*)(), Variant const**, int, Callable::CallError&, Vector<Variant> const&) (/media/juan/NTFS1/dev/godot/./core/variant/binder_common.h:452)
[11] MethodBindT<>::call(Object*, Variant const**, int, Callable::CallError&) const (/media/juan/NTFS1/dev/godot/./core/object/method_bind.h:345 (discriminator 1))
[12] Object::callp(StringName const&, Variant const**, int, Callable::CallError&) (/media/juan/NTFS1/dev/godot/core/object/object.cpp:813 (discriminator 1))
[13] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (/media/juan/NTFS1/dev/godot/core/variant/callable.cpp:69 (discriminator 1))
[14] Object::emit_signalp(StringName const&, Variant const**, int) (/media/juan/NTFS1/dev/godot/core/object/object.cpp:1201)
[15] Node::emit_signalp(StringName const&, Variant const**, int) (/media/juan/NTFS1/dev/godot/scene/main/node.cpp:3974)
[16] Error Object::emit_signal<>(StringName const&) (/media/juan/NTFS1/dev/godot/./core/object/object.h:920)
[17] BaseButton::_pressed() (/media/juan/NTFS1/dev/godot/scene/gui/base_button.cpp:139)
[18] BaseButton::on_action_event(Ref<InputEvent>) (/media/juan/NTFS1/dev/godot/scene/gui/base_button.cpp:179)
[19] BaseButton::gui_input(Ref<InputEvent> const&) (/media/juan/NTFS1/dev/godot/scene/gui/base_button.cpp:69 (discriminator 2))
[20] Control::_call_gui_input(Ref<InputEvent> const&) (/media/juan/NTFS1/dev/godot/scene/gui/control.cpp:1823)
[21] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (/media/juan/NTFS1/dev/godot/scene/main/viewport.cpp:1576)
[22] Viewport::_gui_input_event(Ref<InputEvent>) (/media/juan/NTFS1/dev/godot/scene/main/viewport.cpp:1837 (discriminator 2))
[23] Viewport::push_input(Ref<InputEvent> const&, bool) (/media/juan/NTFS1/dev/godot/scene/main/viewport.cpp:3176 (discriminator 2))
[24] Window::_window_input(Ref<InputEvent> const&) (/media/juan/NTFS1/dev/godot/scene/main/window.cpp:1680)
[25] void call_with_variant_args_helper<Window, Ref<InputEvent> const&, 0ul>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (/media/juan/NTFS1/dev/godot/./core/variant/binder_common.h:304 (discriminator 2))
[26] void call_with_variant_args<Window, Ref<InputEvent> const&>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, int, Callable::CallError&) (/media/juan/NTFS1/dev/godot/./core/variant/binder_common.h:419)
[27] CallableCustomMethodPointer<Window, void, Ref<InputEvent> const&>::call(Variant const**, int, Variant&, Callable::CallError&) const (/media/juan/NTFS1/dev/godot/./core/object/callable_method_pointer.h:111)
[28] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (/media/juan/NTFS1/dev/godot/core/variant/callable.cpp:57)
[29] Variant Callable::call<Ref<InputEvent> >(Ref<InputEvent>) const (/media/juan/NTFS1/dev/godot/./core/variant/variant.h:893)
[30] DisplayServerX11::_dispatch_input_event(Ref<InputEvent> const&) (/media/juan/NTFS1/dev/godot/platform/linuxbsd/x11/display_server_x11.cpp:4063 (discriminator 2))
[31] DisplayServerX11::_dispatch_input_events(Ref<InputEvent> const&) (/media/juan/NTFS1/dev/godot/platform/linuxbsd/x11/display_server_x11.cpp:4040)
[32] Input::_parse_input_event_impl(Ref<InputEvent> const&, bool) (/media/juan/NTFS1/dev/godot/core/input/input.cpp:803)
[33] Input::flush_buffered_events() (/media/juan/NTFS1/dev/godot/core/input/input.cpp:1084)
[34] DisplayServerX11::process_events() (/media/juan/NTFS1/dev/godot/platform/linuxbsd/x11/display_server_x11.cpp:5200)
[35] OS_LinuxBSD::run() (/media/juan/NTFS1/dev/godot/platform/linuxbsd/os_linuxbsd.cpp:960)
[36] /media/juan/NTFS1/dev/godot/bin/godot.linuxbsd.editor.dev.x86_64(main+0x190) [0x60232bcce1e9] (/media/juan/NTFS1/dev/godot/platform/linuxbsd/godot_linuxbsd.cpp:85)
[37] /lib/x86_64-linux-gnu/libc.so.6(+0x28150) [0x73ae1d028150] (??:0)
[38] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x89) [0x73ae1d028209] (??:0)
[39] /media/juan/NTFS1/dev/godot/bin/godot.linuxbsd.editor.dev.x86_64(_start+0x25) [0x60232bccdf95] (??:?)
-- END OF BACKTRACE --
================================================================

```

### Steps to reproduce

Bake Lightmaps with 5 bounces, low quality, 1.5 texel density

### Minimal reproduction project (MRP)

TPSDemo

### LINKED ISSUE #101391: Baking LightmapGI with shadowmasks can crash Godot after transparency support was added
### Tested versions

-Reproducible in latest master v4.4.dev.gh [24d74510e]

### System information

Windows 10 - Godot 4.4dev - Vulkan (Foward+) - Nvidea 1070

### Issue description

Trying to bake the LightmapGI with shadowmasks can get stuck and crash Godot in some circunstances.

Using the latest master (v4.4.dev.gh [24d74510e]) and trying to bake the lightmapGI using the testproject from (https://github.com/godotengine/godot/pull/85653#issuecomment-2447529657) crashes Godot.
With a lot of "Couldn't map PC to fn name" errors.

https://github.com/user-attachments/assets/852e65f9-1f42-476e-928f-f004ba76c92c

Here is the start of the crash:
(On Windows 10, Foward+, Nvidea 1070)

shadowmask

It appears this started happening since adding transparency support to the lightmapGI (https://github.com/godotengine/godot/pull/99538)

As found out by https://github.com/godotengine/godot/pull/85653#issuecomment-2581660852
> @Geometror EDIT: Tested some some PR's and is crashing since #99538 (Transparency PR). Something broke between Dec 12 and Dec 19.
> 
> EDIT2: It seems like if I insist and try again it manage to bake, but taking double the time and the computer becomes unresponsive in the process.

### Steps to reproduce

I didn't figure out the MRP yet, but you can 
use the test project from https://github.com/godotengine/godot/pull/85653#issuecomment-2447529657
(Used to work until the transparency to GI was added)
([direct download link](https://github.com/user-attachments/files/17580558/shadowmask_test_2.zip))

- Try to bake the LIghtmapGI

Expected: LightmapGI baked
Results: Goes until about 50% then Godot gets stuck and crashes.

### Minimal reproduction project (MRP)

Use the test project from https://github.com/godotengine/godot/pull/85653#issuecomment-2447529657
([direct download link](https://github.com/user-attachments/files/17580558/shadowmask_test_2.zip))

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/101391
Fixes: https://github.com/godotengine/godot/issues/98180

The root of the problem here is TDR on Windows which is an OS level interrupt that intentionally crashes GPU contexts that it suspects are frozen. The TDR limit by default is very low on Windows, it can be adjusted (and many users choose to do so), but we don't expect that all users will dig around in the Windows registry in order to do so.

Prior to this PR, we calculate all direct lighting in a single command buffer by doing one compute dispatch per atlas slice. Contrast that to indirect lighting where we do one command buffer for each ray, for each region, for each slice). In 4.3 and earlier we didn't have any issues with this simplistic approach because direct lighting was very simple, it either cast one ray for hard shadows or `rendering/lightmapping/bake_quality/medium_quality_ray_count` (depending on the quality level) for soft shadows. With the introduction of shadow map antialsing in https://github.com/godotengine/godot/pull/95828, we multiply the shadow rays by 16, and now with transparency support in https://github.com/godotengine/godot/pull/99538 we also multiply the number of rays by `rendering/lightmapping/bake_performance/max_transparency_rays`. 

All that is to say, we do a lot more work in the direct light compute invocations, so we need to spread the work out over multiple command buffers. 

This PR does that simply by splitting the work up over regions like we do for indirect lighting so they can take advantage of [`rendering/lightmapping/bake_performance/region_size`](https://docs.godotengine.org/en/latest/classes/class_projectsettings.html#class-projectsettings-property-rendering-lightmapping-bake-performance-region-size)

### CODE REVIEW

**Comment by jcostello** [comment]
>  The root of the problem here is TDR on Windows which is an OS level interrupt that intentionally crashes GPU contexts that it suspects are frozen

Does it fix it for linux?

**Comment by clayjohn** [comment]
> > The root of the problem here is TDR on Windows which is an OS level interrupt that intentionally crashes GPU contexts that it suspects are frozen
> 
> Does it fix it for linux?

Possibly. I wasn't able to reproduce a crash on linux even on integrated graphics

**Comment by SpockBauru** [comment]
With so many crashes on the same day I started to suspect on my device, so tested the [hundred trees MRP](https://github.com/user-attachments/files/17580558/shadowmask_test_2.zip) on the Shadowmap PR (189c8eb). It bakes without issues.
Went back to 4.3 stable and set the directional light to static. Also baked without issues.

Now I tested the windows artifact (c85b399) and it does not crash \o/. But unfortunately, Shadowmaks are not working anymore.
Later, I tried to set Shadowmask off and set the DirectionalLight to static. Still no luck, seems like shadows does not work correctly.

Here is a comparison:
| Shadowmask PR (189c8eb) and 4.3 (DirectionalLight "static") | This PR (c85b399) |
|--------------------------------------------------------------------|---------------------|
| shadowmaks_PR | This_PR_c85b399 |

**Comment by GustJc** [comment]
> But unfortunately, Shadowmaks are not working anymore.

I've noticed the same behavior. It doesn't crash anymore, but the shadows are weird. Not sure if it is related to this fix or not.


https://github.com/user-attachments/assets/3b66eae5-1271-45c6-ad73-55280bcfcdc8

**Comment by clayjohn** [comment]
@SpockBauru thank you for testing and confirming that it no longer crashes for you. I have a theory about why shadowmask broke. I'll take a look using your MRP

File: modules/lightmapper_rd/lightmapper_rd.cpp [hunk 1]
```diff
@@ -1718,18 +1722,53 @@ LightmapperRD::BakeError LightmapperRD::bake(BakeQuality p_quality, bool p_use_d
...
+
+					push_constant.region_ofs[0] = x;
+					push_constant.region_ofs[1] = y;
+
+					group_size = Vector3i(Math::division_round_up(w, 8), Math::division_round_up(h, 8), 1);
+					RD::ComputeListID compute_list = rd->compute_list_begin();
+					rd->compute_list_bind_compute_pipeline(compute_list, compute_shader_primary_pipeline);
+					rd->compute_list_bind_uniform_set(compute_list, compute_base_uniform_set, 0);
+					rd->compute_list_bind_uniform_set(compute_list, light_uniform_set, 1);
+					push_constant.atlas_slice = i;
```
Comment (clayjohn) [inline modules/lightmapper_rd/lightmapper_rd.cpp:1744]: Copy and paste error 😛 

I'm AFK now, but will quickly fix this up once I'm back

**Comment by wojtekpil** [comment]
Did also a test on relatively large scene. I did a bake with ultra quality, single directional light with angular distance = 0.5  Bake took almost 2 hours without issues. I can confirm no crashes on Windows on this PR for me!

**Comment by GustJc** [comment]
> @SpockBauru @GustJc Shadows are back! Thanks for catching that. Please test again once the CI finishes building and let me know if you have any problems

All working now! Great work!

image

**Comment by SpockBauru** [comment]
No crashes and now Shadowmask work! \o/

Tested the Forward+, Mobile and Compatibility renderers. No crashes and shadowmask now have a even higher quality thanks to the transparency, yay!

Made the size of the terrain lightmap 1.8x higher, no crashes and now the smadowmask shows even the brunches of the trees! This was not possible before! \o/

Baking times doubled, but this is expected due the high amount of transparent materials in this scene.

| Shadowmasks increased by 1.8x with transparency! |
|--------------------------------------------------|
| Shadowmask_fixed_1 8x |


Awesome work! No crashes at all! I believe that #101391 can be finally closed. Excelent!

Now the only remaining issues with this MRP are the tunnel regression in #102164 and I just noted the wrong colors with static DynamicLight in #102203, but these belongs to other PRs.

**Comment by ricky-daniel13** [comment]
This seems like a great idea. not using soft-shadows when baking made lightmapping way less crash prone on previous versions of 4.x, probably because of the more memory and time consumed for the more rays, so this seems to be the correct approach in making the lightmapper more reliable.

**Comment by jcostello** [comment]
Crash at the begining of the bake is fixed. How ever in the backyard distro scene with 0.5 texel density or higher I get this error:

VRAM before the crash:

```
Usage: 4539MiB /  6144MiB
godot.linuxbsd.editor.dev.x86_64 :    4117MiB
```

Error:

```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42990) [0x734006e42990] (??:0)
[2] RenderingDeviceDriverVulkan::command_queue_execute_and_present(RenderingDeviceDriver::CommandQueueID, VectorView<RenderingDeviceDriver::SemaphoreID>, VectorView<RenderingDeviceDriver::CommandBufferID>, VectorView<RenderingDeviceDriver::SemaphoreID>, RenderingDeviceDriver::FenceID, VectorView<RenderingDeviceDriver::SwapChainID>) (/home/juan/dev/godot/drivers/vulkan/rendering_device_driver_vulkan.cpp:2597 (discriminator 2))
[3] RenderingDevice::execute_chained_cmds(bool, RenderingDeviceDriver::FenceID, RenderingDeviceDriver::SemaphoreID) (/home/juan/dev/godot/servers/rendering/rendering_device.cpp:6459 (discriminator 3))
[4] RenderingDevice::_execute_frame(bool) (/home/juan/dev/godot/servers/rendering/rendering_device.cpp:6486)
[5] RenderingDevice::submit() (/home/juan/dev/godot/servers/rendering/rendering_device.cpp:6232)
[6] LightmapperRD::bake(Lightmapper::BakeQuality, bool, float, int, int, float, float, int, bool, bool, bool, Lightmapper::GenerateProbes, Ref<Image> const&, Basis const&, bool (*)(float, String const&, void*, bool), void*, float, float) (/home/juan/dev/godot/modules/lightmapper_rd/lightmapper_rd.cpp:1889)
[7] LightmapGI::bake(Node*, String, bool (*)(float, String const&, void*, bool), void*) (/home/juan/dev/godot/scene/3d/lightmap_gi.cpp:1269)
[8] LightmapGIEditorPlugin::_bake_select_file(String const&) (/home/juan/dev/godot/editor/plugins/lightmap_gi_editor_plugin.cpp:73 (discriminator 2))
[9] LightmapGIEditorPlugin::_bake() (/home/juan/dev/godot/editor/plugins/lightmap_gi_editor_plugin.cpp:129 (discriminator 2))
[10] void call_with_variant_args_helper<__UnexistingClass>(__UnexistingClass*, void (__UnexistingClass::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (/home/juan/dev/godot/./core/variant/binder_common.h:320)
[11] void call_with_variant_args_dv<__UnexistingClass>(__UnexistingClass*, void (__UnexistingClass::*)(), Variant const**, int, Callable::CallError&, Vector<Variant> const&) (/home/juan/dev/godot/./core/variant/binder_common.h:463)
[12] MethodBindT<>::call(Object*, Variant const**, int, Callable::CallError&) const (/home/juan/dev/godot/./core/object/method_bind.h:345 (discriminator 1))
[13] Object::callp(StringName const&, Variant const**, int, Callable::CallError&) (/home/juan/dev/godot/core/object/object.cpp:849 (discriminator 1))
[14] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (/home/juan/dev/godot/core/variant/callable.cpp:69 (discriminator 1))
[15] Object::emit_signalp(StringName const&, Variant const**, int) (/home/juan/dev/godot/core/object/object.cpp:1237)
[16] Node::emit_signalp(StringName const&, Variant const**, int) (/home/juan/dev/godot/scene/main/node.cpp:4021)
[17] Error Object::emit_signal<>(StringName const&) (/home/juan/dev/godot/./core/object/object.h:933)
[18] BaseButton::_pressed() (/home/juan/dev/godot/scene/gui/base_button.cpp:143)
[19] BaseButton::on_action_event(Ref<InputEvent>) (/home/juan/dev/godot/scene/gui/base_button.cpp:186)

```

**Comment by clayjohn** [comment]
> Crash at the begining of the bake is fixed. How ever in the backyard distro scene with 0.5 texel density or higher I get this error:
> 
> VRAM before the crash:
> 
> ```
> Usage: 4539MiB /  6144MiB
> godot.linuxbsd.editor.dev.x86_64 :    4117MiB
> ```
> 
> Error:
> 
> ```
> [1] /lib/x86_64-linux-gnu/libc.so.6(+0x42990) [0x734006e42990] (??:0)
> [2] RenderingDeviceDriverVulkan::command_queue_execute_and_present(RenderingDeviceDriver::CommandQueueID, VectorView<RenderingDeviceDriver::SemaphoreID>, VectorView<RenderingDeviceDriver::CommandBufferID>, VectorView<RenderingDeviceDriver::SemaphoreID>, RenderingDeviceDriver::FenceID, VectorView<RenderingDeviceDriver::SwapChainID>) (/home/juan/dev/godot/drivers/vulkan/rendering_device_driver_vulkan.cpp:2597 (discriminator 2))
> [3] RenderingDevice::execute_chained_cmds(bool, RenderingDeviceDriver::FenceID, RenderingDeviceDriver::SemaphoreID) (/home/juan/dev/godot/servers/rendering/rendering_device.cpp:6459 (discriminator 3))
> [4] RenderingDevice::_execute_frame(bool) (/home/juan/dev/godot/servers/rendering/rendering_device.cpp:6486)
> [5] RenderingDevice::submit() (/home/juan/dev/godot/servers/rendering/rendering_device.cpp:6232)
> [6] LightmapperRD::bake(Lightmapper::BakeQuality, bool, float, int, int, float, float, int, bool, bool, bool, Lightmapper::GenerateProbes, Ref<Image> const&, Basis const&, bool (*)(float, String const&, void*, bool), void*, float, float) (/home/juan/dev/godot/modules/lightmapper_rd/lightmapper_rd.cpp:1889)
> [7] LightmapGI::bake(Node*, String, bool (*)(float, String const&, void*, bool), void*) (/home/juan/dev/godot/scene/3d/lightmap_gi.cpp:1269)
> [8] LightmapGIEditorPlugin::_bake_select_file(String const&) (/home/juan/dev/godot/editor/plugins/lightmap_gi_editor_plugin.cpp:73 (discriminator 2))
> [9] LightmapGIEditorPlugin::_bake() (/home/juan/dev/godot/editor/plugins/lightmap_gi_editor_plugin.cpp:129 (discriminator 2))
> [10] void call_with_variant_args_helper<__UnexistingClass>(__UnexistingClass*, void (__UnexistingClass::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (/home/juan/dev/godot/./core/variant/binder_common.h:320)
> [11] void call_with_variant_args_dv<__UnexistingClass>(__UnexistingClass*, void (__UnexistingClass::*)(), Variant const**, int, Callable::CallError&, Vector<Variant> const&) (/home/juan/dev/godot/./core/variant/binder_common.h:463)
> [12] MethodBindT<>::call(Object*, Variant const**, int, Callable::CallError&) const (/home/juan/dev/godot/./core/object/method_bind.h:345 (discriminator 1))
> [13] Object::callp(StringName const&, Variant const**, int, Callable::CallError&) (/home/juan/dev/godot/core/object/object.cpp:849 (discriminator 1))
> [14] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (/home/juan/dev/godot/core/variant/callable.cpp:69 (discriminator 1))
> [15] Object::emit_signalp(StringName const&, Variant const**, int) (/home/juan/dev/godot/core/object/object.cpp:1237)
> [16] Node::emit_signalp(StringName const&, Variant const**, int) (/home/juan/dev/godot/scene/main/node.cpp:4021)
> [17] Error Object::emit_signal<>(StringName const&) (/home/juan/dev/godot/./core/object/object.h:933)
> [18] BaseButton::_pressed() (/home/juan/dev/godot/scene/gui/base_button.cpp:143)
> [19] BaseButton::on_action_event(Ref<InputEvent>) (/home/juan/dev/godot/scene/gui/base_button.cpp:186)
> ```

That is a crash in indirect lighting. 

Can you try reducing `rendering/lightmapping/bake_performance/max_rays_per_pass` and `rendering/lightmapping/bake_performance/region_size` to see if they fix the crash?

**Comment by jcostello** [comment]
> That is a crash in indirect lighting.
> 
> Can you try reducing rendering/lightmapping/bake_performance/max_rays_per_pass and rendering/lightmapping/bake_performance/region_size to see if they fix the crash?

That fix the issue and let me bake. Should I create a new issue to prevent this to happen on the default settings?

**Comment by SpockBauru** [comment]
> That fix the issue and let me bake. Should I create a new issue to prevent this to happen on the default settings?

As soon as this PR gets merged, I think it is better to just include in #102243 since these settings make baking times longer.

**Review by BlueCube3310 — APPROVED** [review]
Tested on Windows with the TPS demo, baking lightmaps no longer crashes

**Comment by Repiteo** [comment]
Thanks!
