### PR TITLE
Editor: Improve signal callback generation

### LINKED ISSUE #79247: Generated documentation show all arrays as untyped
### Godot version

4.1.stable

### System information

Linux 5.10.181-2-MANJARO

### Issue description

A class with a function defined like this:

```gdscript
class_name Foo extends Node

func my_func(arr: Array[int]) -> Array[int]:
	return arr

```

Will show up in the docs as:

image

Whereas i'd expect it to show up as
```
Array[int] my_func(arr: Array[int])
```

The same seems to be true for properties.

### Steps to reproduce

1. Add script
```gdscript
class_name Foo extends Node

func my_func(arr: Array[int]) -> Array[int]:
	return arr
```
2. open class `Foo` in help

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by dalexeev**
**Note: Some changes have been extracted to #80745, #80765 and #81079.**

Added support for typed arrays, enums and `Variant`.

### CODE REVIEW

File: modules/mono/csharp_script.cpp [hunk 1]
```diff
@@ -437,6 +437,10 @@ static String variant_type_to_managed_name(const String &p_var_type_name) {
 		return "Collections.Dictionary";
 	}
 
+	if (p_var_type_name.begins_with(Variant::get_type_name(Variant::ARRAY) + "[")) {
+		return "Collections.Array<" + p_var_type_name.trim_prefix(Variant::get_type_name(Variant::ARRAY) + "[").trim_suffix("]") + ">";
```
Comment (raulsntos) [inline modules/mono/csharp_script.cpp:441]: This assumes that for `Array[T]`, the `T` string is the same in C#. But that's not necessarily true, for example: `int` is `long`, `AABB` is `Aabb`, etc. Take a look at the `var_types` variable below that contains the mapping.

Also, I don't understand why this change is needed. I thought this was a GDScript PR. C# doesn't support generated documentation yet.

**Comment by dalexeev** [comment]
Also this PR adds default argument values and `static` qualifier to methods.

<details>
<summary>Before</summary>



</details>

<details>
<summary>After</summary>



</details>

**Review by raulsntos — APPROVED** [review]
The C# changes look good to me. Should likely be reviewed by the Editor team as well.

File: editor/connections_dialog.cpp [hunk 2]
```diff
@@ -517,16 +517,41 @@ String ConnectDialog::get_signature(const MethodInfo &p_method, PackedStringArra
...
+			case Variant::INT:
+				if ((pi.usage & PROPERTY_USAGE_CLASS_IS_ENUM) && pi.class_name != StringName() && !String(pi.class_name).begins_with("res://")) {
+					type_name = pi.class_name;
+				} else {
+					type_name = "int";
+				}
+				break;
+			case Variant::ARRAY:
+				if (pi.hint == PROPERTY_HINT_ARRAY_TYPE && !pi.hint_string.is_empty() && !pi.hint_string.begins_with("res://")) {
+					type_name = "Array[" + pi.hint_string + "]";
```
Comment (raulsntos) [inline editor/connections_dialog.cpp:534]: For `PROPERTY_HINT_ARRAY_TYPE`, isn't the hint string formatted as `%s/%s:%s`? See the [`MAKE_RESOURCE_TYPE_HINT`](https://github.com/godotengine/godot/blob/3ed4497113fa10611b90290ce22a751fb9d26e2e/core/object/object.h#L142-L144) macro.

Comment (dalexeev) [reply editor/connections_dialog.cpp:534]: > What about `PROPERTY_HINT_TYPE_STRING`?

I think `PROPERTY_HINT_TYPE_STRING` is mainly for the editor. The [core](https://github.com/godotengine/godot/blob/3ed4497113fa10611b90290ce22a751fb9d26e2e/core/variant/typed_array.h#L154-L188), documentation ([one](https://github.com/godotengine/godot/blob/3ed4497113fa10611b90290ce22a751fb9d26e2e/core/doc_data.cpp#L58-L59), [two](https://github.com/godotengine/godot/blob/3ed4497113fa10611b90290ce22a751fb9d26e2e/editor/doc_tools.cpp#L523-L524)) and GDScript ([one](https://github.com/godotengine/godot/blob/3ed4497113fa10611b90290ce22a751fb9d26e2e/modules/gdscript/gdscript_analyzer.cpp#L4749), [two](https://github.com/godotengine/godot/blob/3ed4497113fa10611b90290ce22a751fb9d26e2e/modules/gdscript/gdscript_parser.cpp#L4392)) use `PROPERTY_HINT_ARRAY_TYPE`.

> See the [`MAKE_RESOURCE_TYPE_HINT`](https://github.com/godotengine/godot/blob/3ed4497113fa10611b90290ce22a751fb9d26e2e/core/object/object.h#L142-L144) macro.

This is a bug. See #77618 and https://github.com/godotengine/godot/pull/81293#discussion_r1316095969.

Comment (raulsntos) [reply editor/connections_dialog.cpp:534]: Sorry, I'm a bit confused. Are you saying exported properties should use `PROPERTY_HINT_TYPE_STRING` and method/signal parameters should use `PROPERTY_HINT_ARRAY_TYPE`? I don't really understand when to use one over the other, they seem to serve the same purpose at least when type is `Variant:ARRAY`.

I'm trying to understand this because C# method/signal parameters currently use `PROPERTY_HINT_NONE` (so arrays remain untyped even after the changes in this PR[^1]), and I was wondering if we could reuse the code we use when generating the `hint` and `hint_string` for exported members. But exported array properties use `PROPERTY_HINT_TYPE_STRING` right now (I believe [GDScript](https://github.com/godotengine/godot/blob/3ed4497113fa10611b90290ce22a751fb9d26e2e/modules/gdscript/gdscript_parser.cpp#L4128-L4130) does too for exported properties).

[^1]: To clarify, your PR makes generating signal callbacks in C# scripts work as expected as long as the signal is built-in or declared in a GDScript. But signals declared in C# scripts still use untyped arrays, because the parameter `PropertyInfo` always uses `PROPERTY_HINT_NONE`.

Comment (dalexeev) [reply editor/connections_dialog.cpp:534]: I agree that we do have some confusion. Note that “typed” arrays appeared in the Inspector earlier than in the core. You can use untyped arrays, and encode in `hint_string` the element type, as well as `hint` and `hint_string` of the elements. The Inspector currently does not check the `hint` of the array at all, only the `hint_string`. This is probably where the confusion arose.

With typed arrays, `PROPERTY_HINT_ARRAY_TYPE` was added to the core, `hint_string` expecting an element type as a string, no way to specify `hint` and `hint_string` of elements. However, support for `PROPERTY_HINT_ARRAY_TYPE` was not implemented in the Inspector (see #77618).

`PROPERTY_HINT_ARRAY_TYPE` is used in the stricter typed array scenario: in the core, documentation, and GDScript when it receives information from the core. As for `PROPERTY_HINT_TYPE_STRING`, perhaps its use with the older (and more functional) `hint_string` format was not intended (since the editor accepts any `hint`). However, GDScript already used `PROPERTY_HINT_TYPE_STRING` to export typed arrays, and the documentation for this constant contained slightly incorrect information. So in #77734 I documented it properly.

By the way, the inability to represent _any_ type using `PropertyInfo` (for example, a non-global GDScript class, inner class, GDScript created on the fly) causes certain inconvenience. We should think about this. Maybe we should add a new type `GodotType` to represent a type. This would make it easier to add nested types (`Array[Array[int]]`), generic types, allow you to switch the type hint format in the editor depending on the language, contextualize the type chain (`MyClass.InnerClass.MoreInnerClass`) and/or namespaces (see godotengine/godot-proposals#6502).

**Review by YuriSizov — APPROVED** [review]
This looks like an improvement, and a bugfix too. There are probably still cases which aren't handled perfectly, but they are certainly not handled worse than before.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
