### PR TITLE
Fix positioning of `PopupMenu` submenus

### LINKED ISSUE #118839: `PopupMenu` submenus are not positioned correctly when parent is scaled
### Tested versions

- Reproducible in: 4.7.dev [835e2dcbba974d72d23e348e1ba48f9231fdcd3c]

### System information

Godot v4.7.dev (835e2dcbb) - Fedora Linux 43 (Forty Three) on Wayland - X11 display driver, Single-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 9070 XT (RADV GFX1201) - AMD Ryzen 9 9950X3D 16-Core Processor (32 threads) - 60.39 GiB memory - PulseAudio (44100 Hz, Stereo/mono)

### Issue description

When a `PopupMenu` is scaled in any way, like through its parent `Control`, hovering over the parent item of a submenu entry causes it to be opened at the wrong position.

https://github.com/user-attachments/assets/7678c92e-6856-47a1-81f4-c59d644ae1fb

### Steps to reproduce

1. Run the MRP main scene
2. Right-click anywhere to open the `PopupMenu`
3. Scroll down to and hover over the "Submenu" entry
4. Note how the submenu is positioned incorrectly

### Minimal reproduction project (MRP)

[sub-menu-scaled-position.zip](https://github.com/user-attachments/files/26963527/sub-menu-scaled-position.zip)

### LINKED ISSUE #118841: `PopupMenu` submenus are not positioned correctly when search bar is enabled
### Tested versions

- Reproducible in: 4.7.dev [835e2dcbba974d72d23e348e1ba48f9231fdcd3c]
- Not reproducible in: 4.7.dev [a074a96527fbaa29c8b8b710fb1b7c152585dc95]

### System information

Godot v4.7.dev (835e2dcbb) - Fedora Linux 43 (Forty Three) on Wayland - X11 display driver, Single-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 9070 XT (RADV GFX1201) - AMD Ryzen 9 9950X3D 16-Core Processor (32 threads) - 60.39 GiB memory - PulseAudio (44100 Hz, Stereo/mono)

### Issue description

`PopupMenu` submenus are positioned too high up when the search bar is enabled (i.e. `search_bar_enabled_on_item_count` > 0).

https://github.com/user-attachments/assets/2f955607-3449-4e5a-ab4f-c03127176f44

### Steps to reproduce

1. Run the MRP scene
2. Right-click anywhere in the viewport
3. Hover over "Submenu"
4. Note how the child `PopupMenu` isn't positioned at the "Submenu` entry on the Y-axis

### Minimal reproduction project (MRP)

[popup-menu-position.zip](https://github.com/user-attachments/files/26963296/popup-menu-position.zip)

### PR DESCRIPTION
**Pull request by mihe**
- Fixes #118839
- Fixes #118841

This offsets the sub-menus by the position of `scroll_container`, in order to account for the height of any search bar.

It also incorporates `win_scale` into `scroll_offset`, since positioning seemed to otherwise be broken when the `PopupMenu` list was scaled and scrollable.

As best I can tell, this does not re-introduce #117994.

---
_Disclaimer: AI tooling was used to triage these issues as part of #118571, which prompted some of these changes, all of which I've reviewed to the best of my ability._

### CODE REVIEW

File: scene/gui/popup_menu.cpp [hunk 1]
```diff
@@ -399,21 +399,22 @@ void PopupMenu::_activate_submenu(int p_over, bool p_by_keyboard) {
 	const Point2 panel_offset_end = Point2(-panel->get_offset(SIDE_RIGHT), -panel->get_offset(SIDE_BOTTOM)) * win_scale;
 	const Vector2 scaled_this_size = this_rect.size * win_scale;
 	const float scaled_theme_v_separation = theme_cache.v_separation * win_scale;
-	const float scroll_offset = control->get_position().y;
+	const float scaled_scroll_offset = control->get_position().y * win_scale;
+	const float scaled_scroll_container_offset = scroll_container->get_global_position().y * win_scale;
```
Comment (mihe) [inline scene/gui/popup_menu.cpp]: I'll admit I am not super confident about the use of `scroll_container->get_global_position().y` here.

`get_position` seemed to break when there were content margins in the parent `PopupMenu`, which makes some sense to me, but perhaps there's a more idiomatic way of getting this offset?

File: scene/gui/popup_menu.cpp [hunk 2]
```diff
@@ -399,21 +399,22 @@ void PopupMenu::_activate_submenu(int p_over, bool p_by_keyboard) {
...
 	const float scaled_ofs_cache = items[p_over]._ofs_cache * win_scale;
 	const float scaled_height_cache = items[p_over]._height_cache * win_scale;
```
Comment (YeldhamDev) [inline scene/gui/popup_menu.cpp]: I feel like starting all this variable names with `scaled_` is unnecessary.

Comment (mihe) [reply scene/gui/popup_menu.cpp]: Do I change all of them, or just drop the prefix from `scroll_container_offset` and leave `scroll_offset` unchanged?

Comment (YeldhamDev) [reply scene/gui/popup_menu.cpp]: I personally would change all of them, if possible. It just creates noise.

Comment (mihe) [reply scene/gui/popup_menu.cpp]: Agreed. Done.

**Review by YeldhamDev — APPROVED** [review]
Fixes the issue.

Unrelated to this PR, but this happens if the search bar is enabled:

https://github.com/user-attachments/assets/8f702694-965e-454a-9667-be9c5f25e90e

**Comment by mihe** [comment]
> Unrelated to this PR, but this happens if the search bar is enabled:

Yeah, already reported here: #118840

I have a potential fix lined up, but I need to verify it properly.

**Comment by Repiteo** [comment]
Thanks!
