### PR TITLE
[3.4] Android: Only warn when Target SDK is non default

### LINKED ISSUE #62465: "Changing the "Target SDK" is not valid" error even though I never tried to
### Godot version

3.5. RC5

### System information

Win, Nvidea 765M

### Issue description

I'm testing the latest Godot 3.5.RC build, trying the one click deploy but can't export and get this error:

image

I have not touched the "Target SDK":

image

If I enable "Use Custom Build" like the error message seems to want me to, I get another error which also makes no sense to me (I have the 3.5.RC5 templates installed, even restarted Godot 3.5RC5 after just to make sure):

image

Not sure if this is related to https://github.com/godotengine/godot/pull/61691 or https://github.com/godotengine/godot/pull/51815 since the times I have tested Godot 3.5 so far, I never tried to export.

### Steps to reproduce

Trying to export working 3.4.4 project to Android.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by akien-mga**
The validation logic for Min Sdk and Target Sdk was flawed as it triggers
errors for users not using Custom Build even if they never modified the
values themselves.

The default values for those settings get saved in `export_presets.cfg` and
thus the error gets triggered when moving from 3.4.4 or earlier to 3.4.5, as
the target SDK changed from 30 to 31.

So instead we just raise a warning to make users aware of this non-default
Min Sdk or mostly Target Sdk that might be in their preset.

We also warn when they do use Custom Build as the target SDK 30 would likely
still be an upgrade issue and not an intentional choice, especially given
that Google Play will now require SDK 31.

The export info dialog is now exclusive so that when it doesn't auto-close,
i.e. when it errors, you don't close it by mistake by clicking outside.

The valid range for both options is no longer limited to Godot's own default
target SDK, but can accept higher values (they are not guaranteed to work,
but they might).

- Fixes #62465 without breaking compatibility for 3.4.5.

### CODE REVIEW

File: platform/android/export/export_plugin.cpp [hunk 1]
```diff
@@ -2249,20 +2249,30 @@ bool EditorExportPlatformAndroid::can_export(const Ref<EditorExportPreset> &p_pr
...
+	// in the export preset, users would get an unexpected error when updating to a Godot
+	// version that has different values (GH-62465).
+	// So we don't make a blocking error, instead we just print a warning.
+
 	int min_sdk_version = p_preset->get("version/min_sdk");
 	if (min_sdk_version != DEFAULT_MIN_SDK_VERSION && !custom_build_enabled) {
-		valid = false;
-		err += TTR("Changing the \"Min Sdk\" is only valid when \"Use Custom Build\" is enabled.");
-		err += "\n";
+		EditorNode::get_singleton()->make_bottom_panel_item_visible(EditorNode::get_log()); // Ensure visible.
```
Comment (akien-mga) [inline platform/android/export/export_plugin.cpp:2261]: I need to check what happens in headless mode when this is called.

Comment (akien-mga) [reply platform/android/export/export_plugin.cpp:2261]: Seems to work fine.

**Comment by akien-mga** [comment]
I updated this PR to use `r_err` to pass warnings (without setting `valid = false;`). So I reworded them a bit to make them more concise as we're more constrained on string length. They're still with a line break so they will show as two warnings each, but given that it's just a hack to provide users with relevant info on upgrade to 3.4.5, I think it's fine.
