### PR TITLE
Fix update property for dictionaries so that it updates only what is necessary.

### LINKED ISSUE #75124: "Paste Value" does not refresh the displayed values of array/dict elements in inspector
### Godot version

4.1.dev (4d5f10fc3a)

### System information

MacOS 13.1 M1 Pro

### Issue description

This is similar to #61188, but only happening on elements of array and dictionaries.

Elements of array/Dictionaries are not properly refreshed when using Paste value on them. The values do change internally but the inspector doesn't show the updated value until it is refreshed manually.
This might be related to the fact that the option to copy property path returns an empty string, but i'm not sure as i don't know how updating the property was implemented.

### Steps to reproduce

1. export an array
2. Add two element to the array
3. Change the value of one of the array's element.
4. copy the value of the one you modified.
5. Paste the value on the second element. (here nothing visually changed)
6. click in the tree anywhere except on the node with the exported array then click again on the node (here you will see it has updated and the value was pasted and just not shown)

### Minimal reproduction project

N/A

### LINKED ISSUE #87139: Nested Array editors do not update automatically
### Tested versions

most likely a regression from #80706

### System information

macOS 13.3.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

When changing the type of a nested Array nothing gets updated until you close and open it again. 

### Steps to reproduce

- create a script and export an array
- create a nested array
- try changing the type nothing happens close and re-open the array editor change will be shown 

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #88283: EditorDictionary use VectorX editors for VectorXi elements
### Tested versions

- Reproducible : 4.2.1 (and everywhere else)

### System information

macOS 13.3.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

EditorDictionary use VectorX editors for VectorXi elements which is quite disturbing as it is the only place to do that. 

https://github.com/godotengine/godot/assets/66184050/261e9666-f32d-4ce8-ab3b-d6c52afacc0c

Here is how it looks in arrays which is the proper editor.
Capture d’écran 2024-02-13 à 15 03 08

### Steps to reproduce

1. create a script exporting a dict
2. on new item key or value change type to a VectorXi
3. see the absence of arrows

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #88531: Resources Editor inside Array/Dictionary editors inside Dictionary editors look strange
### Tested versions

reproducible in : v4.3.dev.custom_build [dfe226b93]

### System information

macOS 13.3.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

All subsection of the Resource Editor are forced open which looks like this 

Capture d’écran 2024-02-18 à 23 56 56

for arrays it works as expected :

Capture d’écran 2024-02-18 à 23 57 17

I have't checked yet but might be fixed by #88231 as it changes how sub EditorProperty are generated for Dictionaries to be more in line with what was done for Arrays

### Steps to reproduce

1. Create a script with an exported dictionary
2. add a dictionary or an array to the exported dictionary
3. add a Resources to the nested dictionary/array
4. Open the resources editor 
5. see the problem

### Minimal reproduction project (MRP)

N/A

Edit : Checked and effectively #88231 fix this issue too

### PR DESCRIPTION
**Pull request by ajreckof**
This is the dictionary counter part of #80706. 

- Fixes #75124 ( see https://github.com/godotengine/godot/pull/80706#issuecomment-1682603068)

This is a small step towards #76078 as I decided to break it into smaller pieces for it to be easier to make and review.

- Supersedes #87140 and Fixes #87139

The last part could be removed from this PR if needed, I would then update #87140 once this PR is merged with what I removed from here. See https://github.com/godotengine/godot/pull/87140#issuecomment-1900003828 for why the array parts are linked to dictionnary parts

- EDIT : Fixes #88283 
- Fixes #88531

### CODE REVIEW

File: editor/editor_properties_array_dict.cpp [hunk 1]
```diff
@@ -111,6 +111,7 @@ bool EditorPropertyDictionaryObject::_set(const StringName &p_name, const Varian
 	}
 
 	if (name.begins_with("indices")) {
+		dict = dict.duplicate();
```
Comment (KoBeWi) [inline editor/editor_properties_array_dict.cpp:114]: Why is this needed?

**Comment by KoBeWi** [comment]
It breaks dragging elements to other pages:

https://github.com/godotengine/godot/assets/2223172/fa940ae7-95cc-45f3-aefc-0c5d0b9a8895

File: editor/editor_properties_array_dict.cpp [hunk 2]
```diff
@@ -877,331 +896,72 @@ void EditorPropertyDictionary::update_property() {
...
-				} break;
-				case Variant::PACKED_COLOR_ARRAY: {
-					EditorPropertyArray *editor = memnew(EditorPropertyArray);
-					editor->setup(Variant::PACKED_COLOR_ARRAY);
-					prop = editor;
-				} break;
-				default: {
+			// Check if the editor property needs to be updated.
+			bool value_as_id = Object::cast_to<EncodedObjectAsID>(value);
+			if (value_type != slot.type || (value_type == Variant::OBJECT && (value_as_id != slot.as_id))) {
```
Comment (AThousandShips) [inline editor/editor_properties_array_dict.cpp:944]:
```suggestion
			if (value_type != slot.type || (value_type == Variant::OBJECT && value_as_id != slot.as_id)) {
```
Too nested

File: editor/editor_properties_array_dict.cpp [hunk 3]
```diff
@@ -877,331 +896,72 @@ void EditorPropertyDictionary::update_property() {
...
-			for (int i = property_vbox->get_child_count() - 1; i >= 0; i--) {
-				property_vbox->get_child(i)->queue_free();
+
+			for (int i = 0; i < page_length; i++) {
+				create_new_property_slot(slots.size());
 			}
+
+			add_panel = memnew(PanelContainer);
+			property_vbox->add_child(add_panel);
+			add_panel->add_theme_style_override(SNAME("panel"), get_theme_stylebox(SNAME("DictionaryAddItem"), SNAME("EditorStyles")));
```
Comment (AThousandShips) [inline editor/editor_properties_array_dict.cpp:906]:
```suggestion
			add_panel->add_theme_style_override(SNAME("panel"), get_theme_stylebox(SNAME("DictionaryAddItem"), EditorStringName(EditorStyles)));
```

File: editor/editor_properties_array_dict.cpp [hunk 4]
```diff
@@ -877,331 +896,72 @@ void EditorPropertyDictionary::update_property() {
...
+			VBoxContainer *add_vbox = memnew(VBoxContainer);
+			add_panel->add_child(add_vbox);
+
+			create_new_property_slot(-1);
+			create_new_property_slot(-2);
+
+			button_add_item = EditorInspector::create_inspector_action_button(TTR("Add Key/Value Pair"));
+			button_add_item->set_icon(get_theme_icon(SNAME("Add"), SNAME("EditorIcons")));
```
Comment (AThousandShips) [inline editor/editor_properties_array_dict.cpp:914]:
```suggestion
			button_add_item->set_icon(get_theme_icon(SNAME("Add"), EditorStringName(EditorIcons)));
```

File: editor/editor_properties_array_dict.cpp (hunk 1 above)
Comment (ajreckof) [reply editor/editor_properties_array_dict.cpp:114]: This is needed for undo/redo so that the new and old dictionaries are different and uptading the new won't update the old. It didn't cause any bug before because in fact it was never called. I realized there was duplication of code between this function and one part of code around line 750. The only difference being it never duplicated the dict in the function. So I added the duplication and removed the line of codes to call set instead.

**Comment by KoBeWi** [comment]
> Fixed

It's still a little bugged 🤔

https://github.com/godotengine/godot/assets/2223172/dae98aa3-3e3d-48db-976b-23a536d64ed6

The original element gets focused once drag ends. But at least it's moved correctly, so maybe it's fine *for now*.

File: editor/editor_properties_array_dict.h [hunk 5]
```diff
@@ -160,6 +162,44 @@ class EditorPropertyArray : public EditorProperty {
...
+		int index = -1;
+		Variant::Type type = Variant::VARIANT_MAX;
+		bool as_id = false;
+		EditorProperty *prop = nullptr;
+		String prop_name;
+
+		void set_index(int p_idx) {
+			index = p_idx;
+			switch (index) {
+				case -2:
```
Comment (KoBeWi) [inline editor/editor_properties_array_dict.h:177]: The magic number should likely be replaced with a constant.

**Review by KoBeWi — APPROVED** [review]

**Comment by ajreckof** [comment]
> > Fixed
> 
> It's still a little bugged 🤔
> 
>  godot.windows.editor.dev.x86_64_ThlgrE8Clj.mp4 
> The original element gets focused once drag ends. But at least it's moved correctly, so maybe it's fine _for now_.

This was not introduced by this PR(present on master). Should be easy to fix though. Do you think I should add the fix in this PR or create a separate issue/PR?

**Comment by KoBeWi** [comment]
If it's pre-existing, you can open an issue (if it wasn't reported already).

File: editor/editor_properties_array_dict.h [hunk 6]
```diff
@@ -170,15 +210,18 @@ class EditorPropertyDictionary : public EditorProperty {
 	Button *edit = nullptr;
 	MarginContainer *container = nullptr;
 	VBoxContainer *property_vbox = nullptr;
+	PanelContainer *add_panel = nullptr;
 	EditorSpinSlider *size_sliderv = nullptr;
 	Button *button_add_item = nullptr;
 	EditorPaginator *paginator = nullptr;
 	PropertyHint property_hint;
+	LocalVector<Slot> slots;
+	void create_new_property_slot(int p_idx);
```
Comment (AThousandShips) [inline editor/editor_properties_array_dict.h:219]:
```suggestion
	void _create_new_property_slot(int p_idx);
```

**Comment by akien-mga** [comment]
Thanks!
