### PR TITLE
Properly handle theme changes in the Skeleton3DEditor

### LINKED ISSUE #65037: Skeleton bones have invalid icons
### Godot version

v4.0.alpha.custom_build [e60086f98]

### System information

Arch on 5.19.2-arch1-1

### Issue description

image

### Steps to reproduce

Open MRP, right click mesh, new inherited scene, click skeleton

### Minimal reproduction project

Just copied this MRP from # 56458
[BoneAABBWarnings.zip](https://github.com/godotengine/godot/files/9444587/BoneAABBWarnings.zip)

### PR DESCRIPTION
**Pull request by YuriSizov**
Fixes https://github.com/godotengine/godot/issues/65037. Pretty much described in my comment there.

### CODE REVIEW

File: editor/plugins/skeleton_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -845,8 +834,23 @@ void Skeleton3DEditor::_notification(int p_what) {
 			skeleton->connect("bone_enabled_changed", callable_mp(this, &Skeleton3DEditor::_bone_enabled_changed));
 			skeleton->connect("show_rest_only_changed", callable_mp(this, &Skeleton3DEditor::_update_gizmo_visible));
 #endif
-			break;
-		}
+
+			get_tree()->connect("node_removed", callable_mp(this, &Skeleton3DEditor::_node_removed), Object::CONNECT_ONESHOT);
+		} break;
+		case NOTIFICATION_READY: {
```
Comment (akien-mga) [inline editor/plugins/skeleton_3d_editor_plugin.cpp:840]: Nitpick, but we try to keep a separation like between `case`s for `_notification` switches, as these are often big/method-sized scopes.

**Review by akien-mga — APPROVED** [review]

File: editor/plugins/skeleton_3d_editor_plugin.cpp (hunk 1 above)
Comment (akien-mga) [reply editor/plugins/skeleton_3d_editor_plugin.cpp:840]: But this code already didn't follow that convention so let's not make it block a regression fix.
