### PR TITLE
Fix undo redo not adjusting TextEdit viewport to caret

### LINKED ISSUE #67453: Script undo no longer follows caret
### Godot version

4.0 beta3

### System information

Windows 10 x64

### Issue description

When undoing a change in script editor, previously the view would follow the caret. It's not happening anymore, undo/redo will do changes off-screen.

### Steps to reproduce

1. Have a scrollable script
2. Change something
3. Scroll to leave the changed area outside of view
4. Undo/redo

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Paulb23**
Since we now restore the carets directly and not through `set_caret_line|column` the viewport was no longer being adjusted. 

closes #67453

### CODE REVIEW

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -3863,6 +3863,7 @@ void TextEdit::undo() {
 		}
 		caret_pos_dirty = true;
 	}
+	adjust_viewport_to_caret();
 	queue_redraw();
```
Comment (KoBeWi) [inline scene/gui/text_edit.cpp:3867]: `adjust_viewport_to_caret()` seems to already call `queue_redraw()`, so the other call is redundant.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
