### PR TITLE
Shadow fade for omni lights actually stops the shadow from updating while faded out to improve performance.

### LINKED ISSUE #88085: OmniLight3D performace doesn't improve with distance fade (shadows still update?)
### Tested versions

Reproduced in v4.2.1.stable.official [b09f793f5]

### System information

Windows 10, Vulkan forward +, Nvidia 3070

### Issue description

I added some distant lights that really started hurting performance, so I enabled distance fade, which did not improve the performance, even when set to something super short like 5m.  Occlusion culling or disabling the lights completely does improve performance, so it seems the distance fade is not taken into account when recalculating shadows.

### Steps to reproduce

1) Add a bunch of omni lights with shadows enabled.
2) Have some dynamic things or something that causes the shadows to update.
3) Enable distance fade.
4) Move out of the range of the distance fade.
5) Note performance does not increase.
6) Disable lights and compare performance.

### Minimal reproduction project (MRP)

[test_omnilight_fade.zip](https://github.com/godotengine/godot/files/14203338/test_omnilight_fade.zip)

There's a light group to make it easy to hide the visibility of all the lights so you can compare distance fade vs. hidden.

For me, the framerate is the same with and without distance fade enabled when shadows are on.  Framerate improves with distance fade when shadows are disabled.

Side note: It would be really nice if there were some sort of priority system / max shadow updates per frame or something like that to trade off some stuttery shadows at a distance for performance rather than having to completely disable lighting at a distance.

Also might be nice if the shadows cached the depth buffer for static geometry and only dynamic geo would update (not sure if this is the case).  I also tried to break up my level (larger, more complex one than in the MRP) into chunks thinking the shadows might just render close objects, but that seemed to make performance worse.  There might be a few other opportunities for omni light shadow optimization.

### PR DESCRIPTION
**Pull request by jitspoe**
This is to address https://github.com/godotengine/godot/issues/88085

* *Bugsquad edit, fixes: https://github.com/godotengine/godot/issues/88085*

### CODE REVIEW

**Comment by lawnjelly** [comment]
This is not so efficient and won't work with shadow map caching unfortunately. I can take a look this.

**Comment by lawnjelly** [comment]
> You can fade the shadows before the lights. There are 3 parameters on the light for the fade start (of the light), the fade start of the shadow, and the distance of the fade (shared between the 2). I've been using this by fading the shadows out at a shorter distance than the lights, so that aspect seems to work.

In that case it does seem like both approaches can complement each other. :+1: :smile: 

Gross culling as you have done here is a great approach, and culling shadows individually by distance should considerably speed things up further when shadows can be faded out earlier (this can be done with directional lights too actually).

Hopefully not rendering the entire shadow map as done here will mean we won't have to deal with the caching issues which are quite tricky (the shadowmap should just remain dirty, and keep trying to render until it comes within range).

File: servers/rendering/renderer_rd/storage_rd/light_storage.h [hunk 1]
```diff
@@ -544,6 +544,29 @@ class LightStorage : public RendererLightStorage {
 		return light->shadow;
 	}
 
+	virtual bool light_is_shadow_visible_at_position(RID p_light_instance, const Vector3 position) const override {
+		const LightInstance *light_instance = light_instance_owner.get_or_null(p_light_instance);
+		ERR_FAIL_NULL_V(light_instance, RS::LIGHT_DIRECTIONAL);
```
Comment (lawnjelly) [inline servers/rendering/renderer_rd/storage_rd/light_storage.h:549]: This error seems to be copy-pastad quite a bit prior to your PR.
`ERR_FAIL_NULL_V` should return true or false I think, not `RS::LIGHT_DIRECTIONAL`.

File: servers/rendering/renderer_rd/storage_rd/light_storage.h [hunk 2]
```diff
@@ -544,6 +544,29 @@ class LightStorage : public RendererLightStorage {
 		return light->shadow;
 	}
 
+	virtual bool light_is_shadow_visible_at_position(RID p_light_instance, const Vector3 position) const override {
```
Comment (lawnjelly) [inline servers/rendering/renderer_rd/storage_rd/light_storage.h:547]: Most of the functions here take a light RID directly, you may be able to do this by passing `ins->base` for the light instance from `renderer_scene_cull`.

**Comment by lawnjelly** [comment]
Once the nitpicks above are done this looks fine to me (the function should take a light `RID` if possible imo). I've tested (reasonably, hard to test every permutation) and it seems to work fine.

Probably one of the 4.x rendering team should also review when back from GDC prior to moving forward.

File: servers/rendering/renderer_rd/storage_rd/light_storage.h (hunk 1 above)
Comment (jitspoe) [reply servers/rendering/renderer_rd/storage_rd/light_storage.h:549]: Classic copy paste without reading. 😅  Surprised that didn't end up with a compiler error.

File: servers/rendering/storage/light_storage.h [hunk 3]
```diff
@@ -74,6 +74,7 @@ class RendererLightStorage {
 	virtual RS::LightOmniShadowMode light_omni_get_shadow_mode(RID p_light) = 0;
 
 	virtual bool light_has_shadow(RID p_light) const = 0;
+	virtual bool light_is_shadow_visible_at_position(RID p_light, const Vector3 p_position) const = 0;
```
[the remark this answers is not in the document]
Comment (jitspoe) [reply servers/rendering/storage/light_storage.h:77]: Isn't it more optimal to pass by value than pass by reference unless it's a large struct?

File: servers/rendering/renderer_rd/storage_rd/light_storage.h (hunk 2 above)
Comment (jitspoe) [reply servers/rendering/renderer_rd/storage_rd/light_storage.h:547]: How do I get the position from the light?

File: servers/rendering/storage/light_storage.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (AThousandShips) [reply servers/rendering/storage/light_storage.h:77]: We do it everywhere and it's not a small structure, on double precision builds you're passing 24 bytes

File: servers/rendering/renderer_rd/storage_rd/light_storage.h (hunk 2 above)
Comment (lawnjelly) [reply servers/rendering/renderer_rd/storage_rd/light_storage.h:547]: Ah I see what you mean, you would have to pass the light position, so I guess it's not too bad as is.

Although I've realised if you are passing light instance, it should be in the `LIGHT INSTANCE API` section below, and the func name should start with `light_instance` rather than `light`.

I also wonder whether `light_instance_is_shadow_visible_at_camera_position()` might be slightly less confusing than just `position`, as it is hard to interpret what the function does? :thinking: Naming is always really difficult.

_(Another alternative would be to query the threshold distance from the light `RID` and do the calculation in the calling code.)_

Comment (jitspoe) [reply servers/rendering/renderer_rd/storage_rd/light_storage.h:547]: Oh, maybe.  Originally, I was trying to do it with just the light, but it seemed I needed the light instance to get the position.

I was also going to do the calculation in the calling code but realized that most of the time the distance is never needed since lights don't have the distance fade enabled by default, so it's probably more optimal to only do the distance calculation when actually needed.

**Comment by jitspoe** [comment]
Updated the code.  Hopefully I got everything!

**Review by lawnjelly — APPROVED** [review]
Looks fine to me.

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` https://github.com/godotengine/godot/commit/29b3d9e9e538f0aa8effc8ad8bf19a2915292a89), it works as expected in all rendering methods.

**Testing project:** [test_shadow_distance_fade_performance.zip](https://github.com/godotengine/godot/files/14797520/test_shadow_distance_fade_performance.zip)

Not only this PR improves performance, but this also improves shadow quadrant selection for nearby lights when distant lights are faded out:

master https://github.com/godotengine/godot/commit/29b3d9e9e538f0aa8effc8ad8bf19a2915292a89 | This PR
-|-
shadow_distance_fade_master | shadow_distance_fade_pr

Unfortunately, this PR doesn't improve the situation when light per-instance limits are reached in the Mobile and Compatibility rendering methods (I haven't checked Forward+ with low **Max Clustered Elements** project setting). We should try to make it so fully faded lights are ignored entirely at a low level, so that you can bypass per-instance light limits using distance fade. https://github.com/godotengine/godot/issues/67845 is not fixed by this PR either.

Either way, considering how much this PR improves performance, I'd say it's already in a mergeable state.

## Benchmark

<details open>

<summary>PC specifications</summary>

- **CPU:** Intel Core i9-13900K
- **GPU:** NVIDIA GeForce RTX 4090
- **RAM:** 64 GB (2×32 GB DDR5-5800 C30)
- **SSD:** Solidigm P44 Pro 2 TB
- **OS:** Linux (Fedora 39)
</details>

Type | master | This PR
-:|-|-
**1152×648 idle** | 1304 FPS (0.77 mspf) | 4208 FPS (0.24 mspf)
**1152×648 moving** | 582 FPS (1.72 mspf) | 2608 FPS (0.38 mspf)
**3840×2160 idle** | 546 FPS (1.83 mspf) | 675 FPS (1.48 mspf)
**3840×2160 moving** | 403 FPS (2.48 mspf) | 619 FPS (1.62 mspf)

**Review by clayjohn — COMMENTED** [review]
Just a little nitpick to avoid the virtual function call and duplicated code. Other than that this seems great! Good job!

File: servers/rendering/storage/light_storage.h [hunk 4]
```diff
@@ -98,6 +98,7 @@ class RendererLightStorage {
 	virtual bool light_instances_can_render_shadow_cube() const {
 		return true;
 	}
+	virtual bool light_instance_is_shadow_visible_at_position(RID p_light, const Vector3 &p_position) const = 0;
```
[the remark this answers is not in the document]
Comment (jitspoe) [reply servers/rendering/storage/light_storage.h:101]: Is that possible?  The light structs are defined in the driver specific implementations (though maybe they shouldn't be?)

[the remark this answers is not in the document]
Comment (clayjohn) [reply servers/rendering/storage/light_storage.h:101]: Ahhh, I guess we would have to move the struct definition here and then extend the struct in each implementation. 

Hmmm, it's a bit more work, but it is probably best to keep the function definition in one place

[the remark this answers is not in the document]
Comment (clayjohn) [reply servers/rendering/storage/light_storage.h:101]: Sure, there are probably other functions that can similarly be shared between the implementations.

**Review by clayjohn — APPROVED** [review]
Seems great! I also tested locally and confirmed that its working as intended.

Good job!

**Comment by akien-mga** [comment]
Thanks!
