### PR TITLE
[Curve3D] Fix middle point forward vector when control1=end and control2=begin

### LINKED ISSUE #88923: Curve3D: `sample_baked_with_rotation` returns `Basis()` for a curve section's middle point when its control1==end and control2==begin
### Tested versions

- Reproducible in: v4.0.4.stable.official [fc0b241c9], v4.1.1.stable.official [bd6af8e0e], v4.2.1.stable.official [b09f793f5], v4.3.dev3.official [36e943b6b]

### System information

Godot v4.2.1.stable - Ubuntu 23.10 23.10 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (nvidia; 545.29.06) - AMD Ryzen 7 5800X3D 8-Core Processor (16 Threads)

### Issue description

When using `sample_baked_with_rotation` with an offset that corresponds to the middle point of a curve section where `out` of the first point equals the second point and `in` of the second point equals the first point, it triggers an error [here](https://github.com/godotengine/godot/blob/bb6b06c81343073f10cbbd2af515cf0dac1e6549/core/math/basis.cpp#L1044) with `The target vector can't be zero.` and returns a transform with the default `Basis()`.

With an offset that corresponds to the next baked point right after the middle point, the error occurs as well, but the transform's basis is correct. 

#### Details

The call to `looking_at` happens [here](https://github.com/godotengine/godot/blob/fb10e67fefb85af3b8f5abd30db561588d8456c6/scene/resources/curve.cpp#L1826) in `_compose_posture`, which is called twice by `_sample_posture` [here](https://github.com/godotengine/godot/blob/fb10e67fefb85af3b8f5abd30db561588d8456c6/scene/resources/curve.cpp#L1840), which, in turn, is called by `sample_baked_with_rotation` [here](https://github.com/godotengine/godot/blob/fb10e67fefb85af3b8f5abd30db561588d8456c6/scene/resources/curve.cpp#L1926).

The problem: The baked forward vector that `_compose_posture` gets from `baked_forward_vector_cache` for the affected middle points is zero. That's because, in the call-chain [_bake](https://github.com/godotengine/godot/blob/15a03ed98e63590c85dac62405d785e1b7ca7fed/scene/resources/curve.cpp#L1545) -> [p_begin.bezier_derivative(...](https://github.com/godotengine/godot/blob/15a03ed98e63590c85dac62405d785e1b7ca7fed/scene/resources/curve.cpp#L1542) in `_calculate_tangent` -> [Math::bezier_derivative](https://github.com/godotengine/godot/blob/bb6b06c81343073f10cbbd2af515cf0dac1e6549/core/math/math_funcs.h#L397), the result of the formula in the latter function equals `0` if the following conditions are met: `p_control_1` equals `p_end`, `p_control_2` equals `p_start` and `p_t` equals `0.5`.

The `0.5` passed to it in our case corresponds to the middle of the curve segment between two curve points, and is the "most middle" for each of the middlepoint `RBMap` key-value maps initialized [here](https://github.com/godotengine/godot/blob/15a03ed98e63590c85dac62405d785e1b7ca7fed/scene/resources/curve.cpp#L1593) in `_bake` using `_tessellate_even_length` (down that call-chain, this happens [here](https://github.com/godotengine/godot/blob/15a03ed98e63590c85dac62405d785e1b7ca7fed/scene/resources/curve.cpp#L1523) in `_bake_segment3d_even_length` for our `0.5`, since for the first recursion `p_begin` is `0` and `p_end` is `1`).

Thus, if we don't count its initial call to `_bake`, the bug isn't caused by something in the `sample_baked_with_rotation` call-chain, but earlier when the forward vectors are baked. `sample_baked_with_rotation` (or rather, `_compose_posture`) simply trips over it.

The reason that the next point right after the middle point triggers the error as well, but without the basis being wrong, is this: `_compose_posture` is called twice in `_sample_posture` [here](https://github.com/godotengine/godot/blob/15a03ed98e63590c85dac62405d785e1b7ca7fed/scene/resources/curve.cpp#L1837), creating an `idx`-and-`idx+1` "moving window", which, naturally, features each problem-idx twice. The actual problem with the default basis only occurs the first time when it's used for `frame_end`, which causes `sample_posture` to `slerp` to it, since `frac`, in the cases I've explored, always seems to be `1.0`.

### Steps to reproduce

The vectors with two-digit coordinates aren't relevant, they're just set to something else than `Vector3()` to make it less likely for other corner cases to be triggered by accident.
```gdscript
var curve := Curve3D.new()
curve.add_point(Vector3(), Vector3(23, 87, -15), Vector3(1, 0, 0))
curve.add_point(Vector3(1, 0, 0), Vector3(-1, 0, 0), Vector3(19, -22, 56))

var baked_points := curve.get_baked_points()
var middle_point_idx := int(len(baked_points) / 2.0)

for idx in range(middle_point_idx, middle_point_idx + 2):
    var offset := curve.get_closest_offset(baked_points[idx])
    # Error will trigger here.
    curve.sample_baked_with_rotation(offset)
```

### Minimal reproduction project (MRP)

- MRP: [linear-curve-zero-vector-bug-mrp.zip](https://github.com/godotengine/godot/files/14422935/linear-curve-zero-vector-bug-mrp.zip)
- [Exploratory project](https://github.com/Aziroshin/godot-linear-curve-zero-vector-bug-exploration)

### PR DESCRIPTION
**Pull request by Aziroshin**
This, in turn, fixes the wrong middle point transform returned by `sample_baked_with_rotation` with the control point constellation mentioned in the title.

Fixes #88923, which contains further details.

### CODE REVIEW

File: scene/resources/curve.cpp [hunk 1]
```diff
@@ -1543,6 +1543,10 @@ Vector3 Curve3D::_calculate_tangent(const Vector3 &p_begin, const Vector3 &p_con
 		return (p_end - p_begin).normalized();
 	}
 
+	if (Math::is_zero_approx(p_t - 0.5f), p_control_1.is_equal_approx(p_end) && p_control_2.is_equal_approx(p_begin)) {
```
Comment (AThousandShips) [inline scene/resources/curve.cpp:1546]:
```suggestion
	if (Math::is_equal_approx(p_t, 0.5) && p_control_1.is_equal_approx(p_end) && p_control_2.is_equal_approx(p_begin)) {
```

File: tests/scene/test_curve_3d.h [hunk 2]
```diff
@@ -217,6 +217,17 @@ TEST_CASE("[Curve3D] Sampling") {
 		c->add_point(Vector3(0, .1, 1));
 		CHECK_LT((c->sample_baked_up_vector(c->get_closest_offset(Vector3(0, 0, .9))) - Vector3(0, 0.995037, -0.099504)).length(), 0.01);
 	}
+
+	SUBCASE("sample_baked_with_rotation, linear curve with control1==end and control2==begin") {
```
Comment (AThousandShips) [inline tests/scene/test_curve_3d.h:221]:
```suggestion
	SUBCASE("sample_baked_with_rotation, linear curve with control1 = end and control2 = begin") {
```

File: tests/scene/test_curve_3d.h [hunk 3]
```diff
@@ -217,6 +217,17 @@ TEST_CASE("[Curve3D] Sampling") {
...
+		// Regression test for issue #88923
+		// The Vector3s that aren't relevant to the issue have z==2.
```
Comment (AThousandShips) [inline tests/scene/test_curve_3d.h:223]:
```suggestion
		// The Vector3s that aren't relevant to the issue have z == 2.
```

**Comment by Aziroshin** [comment]
I'll now go and squash+force push the new commits.

**Comment by Aziroshin** [comment]
The compiler doesn't like using `5.0` instead of `5.0f`.
command: `$ scons platform=linuxbsd dev_build=yes tests=yes`
Here's the output:
```
scons: Reading SConscript files ...
Auto-detected 16 CPU cores available for build parallelism. Using 15 cores by default. You can override it with the -j argument.
Building for platform "linuxbsd", architecture "x86_64", target "editor".
NOTE: Developer build, with debug optimization level and debug symbols (unless overridden).
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[ 10%] Compiling tests/test_main.cpp ...
[ 85%] Compiling scene/resources/curve.cpp ...
[ 91%] scene/resources/curve.cpp: In static member function 'static Vector3 Curve3D::_calculate_tangent(const Vector3&, const Vector3&, const Vector3&, const Vector3&, real_t)':
scene/resources/curve.cpp:1546:34: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
 1546 |         if (Math::is_equal_approx(p_t, 0.5) && p_control_1.is_equal_approx(p_end) && p_control_2.is_equal_approx(p_begin)) {
      |             ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
In file included from ./core/math/vector3.h:35,
                 from ./core/math/plane.h:34,
                 from ./core/math/aabb.h:34,
                 from ./core/variant/variant.h:36,
                 from ./core/object/message_queue.h:38,
                 from ./core/object/object.h:35,
                 from ./core/variant/binder_common.h:35,
                 from ./core/object/method_bind.h:34,
                 from ./core/object/class_db.h:34,
                 from ./core/object/ref_counted.h:34,
                 from ./core/io/resource_uid.h:34,
                 from ./core/io/resource.h:34,
                 from scene/resources/curve.h:34,
                 from scene/resources/curve.cpp:31:
./core/math/math_funcs.h:586:37: note: candidate 1: 'static bool Math::is_equal_approx(double, double)'
  586 |         static _ALWAYS_INLINE_ bool is_equal_approx(double a, double b) {
      |                                     ^~~~~~~~~~~~~~~
./core/math/math_funcs.h:560:37: note: candidate 2: 'static bool Math::is_equal_approx(float, float)'
  560 |         static _ALWAYS_INLINE_ bool is_equal_approx(float a, float b) {
      |                                     ^~~~~~~~~~~~~~~
[ 93%] Compiling core/version_hash.gen.cpp ...
[ 99%] progress_finish(["progress_finish"], [])
[100%] Linking Static Library core/libcore.linuxbsd.editor.dev.x86_64.a ...
[100%] Linking Static Library scene/libscene.linuxbsd.editor.dev.x86_64.a ...
Ranlib Library core/libcore.linuxbsd.editor.dev.x86_64.a ...
[100%] Ranlib Library scene/libscene.linuxbsd.editor.dev.x86_64.a ...
[100%] Linking Static Library tests/libtests.linuxbsd.editor.dev.x86_64.a ...
Ranlib Library tests/libtests.linuxbsd.editor.dev.x86_64.a ...
[100%] Linking Program bin/godot.linuxbsd.editor.dev.x86_64 ...
[100%] scons: done building targets.
[Time elapsed: 00:00:46.365]
```

**Comment by Aziroshin** [comment]
Regarding the change from `==` to `=` in the comment, I should probably use words instead, as these don't strictly refer to parameters. Would that be fine?

**Comment by Aziroshin** [comment]
The test now uses `is_equal_approx` instead of `==`.

File: tests/scene/test_curve_3d.h [hunk 4]
```diff
@@ -217,6 +217,17 @@ TEST_CASE("[Curve3D] Sampling") {
...
+
+	SUBCASE("sample_baked_with_rotation, linear curve with control1 = end and control2 = begin") {
+		// Regression test for issue #88923
+		// The Vector3s that aren't relevant to the issue have z == 2.
+		// They're just set to make collisions with corner cases less likely
+		// that involve zero-vector control points.
+		Ref<Curve3D> cross_linear_curve = memnew(Curve3D);
+		cross_linear_curve->add_point(Vector3(), Vector3(-1, 0, 2), Vector3(1, 0, 0));
+		cross_linear_curve->add_point(Vector3(1, 0, 0), Vector3(-1, 0, 0), Vector3(1, 0, 2));
+		CHECK(cross_linear_curve->sample_baked_with_rotation(cross_linear_curve->get_closest_offset(Vector3(0.5, 0, 0))).is_equal_approx(Transform3D(Basis(Vector3(0, 0, 1), Vector3(0, 1, 0), Vector3(-1, 0, 0)), Vector3(0.5, 0, 0))));
```
Comment (kitbdev) [inline tests/scene/test_curve_3d.h:229]:
```suggestion
		CHECK(cross_linear_curve->sample_baked_with_rotation(cross_linear_curve->get_closest_offset(Vector3(0.5, 0, 0))) == Transform3D(Basis(Vector3(0, 0, 1), Vector3(0, 1, 0), Vector3(-1, 0, 0)), Vector3(0.5, 0, 0)));
```
The test should use `==`, not `is_equal_approx`. This is because its not needed (when I tested at least),  so the CHECK can see the 2 values for better error messages, and to match the other tests above.

**Review by kitbdev — COMMENTED** [review]
Works as expected.
Needs a rebase.

**Comment by kitbdev** [comment]
Also, this should be applied to Curve2D, since the same problem happens there.

File: tests/scene/test_curve_3d.h (hunk 4 above)
Comment (kitbdev) [reply tests/scene/test_curve_3d.h:229]: Actually, if it is necessary for the doubles build, then it is fine.

File: scene/resources/curve.cpp [hunk 5]
```diff
@@ -1543,6 +1543,10 @@ Vector3 Curve3D::_calculate_tangent(const Vector3 &p_begin, const Vector3 &p_con
 		return (p_end - p_begin).normalized();
 	}
 
+	if (Math::is_equal_approx(p_t, (real_t)0.5) && p_control_1.is_equal_approx(p_end) && p_control_2.is_equal_approx(p_begin)) {
```
[the remark this answers is not in the document]
Comment (Aziroshin) [reply scene/resources/curve.cpp]: I've removed the check.

**Review by kitbdev — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
