### PR TITLE
Fix cannot update remote after disabling `use_global_coordinates` in `RemoteTransform2D`

### LINKED ISSUE #83297: RemoteTransform2D projects wrong position
### Godot version

4.2.beta

### System information

Windows 10

### Issue description

I assume the main use-case of `RemoteTransform2D` is to have another node match the transform of the `RemoteTransform2D`'s parent node. When `RemoteTransform2D` has `use_global_coordinates` set to `false`, however, the position sent to the controlled node will be the `RemoteTransform2D`'s local position, which makes sense, I guess, but that will always be `(0,0)`. This could be the expected behavior, but I can't imagine when it'd ever be useful, so please correct me if I'm wrong. 

### Steps to reproduce

1. Make a sprite.
2. Make a second sprite with a `RemoteTransform2D` child and move it anywhere on screen.
3. Select the first sprite as the `RemoteTransform2D`'s target.
4. Set `use_global_coordinates` to false.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Rindbee**
Due to the optimization in `CanvasItem`, `global_transform` is only updated when `get_global_transform()` is called, and then notify `NOTIFICATION_TRANSFORM_CHANGED`. That is, in the case where `global_transform` is not obtained, the notification `NOTIFICATION_TRANSFORM_CHANGED` will not be sent.

So we use `NOTIFICATION_LOCAL_TRANSFORM_CHANGED` in this case. Use in combination to prevent certain optimizations.

Fix https://github.com/godotengine/godot/issues/83297#issuecomment-1762815741.

Same change for `RemoteTransform3D`, to prevent the same optimization from being used in Node3D in the future.

### CODE REVIEW

**Comment by Rindbee** [comment]
Provide a scene for testing.
[node_2d.tscn.txt](https://github.com/godotengine/godot/files/12905724/node_2d.tscn.txt)

**Comment by kleonc** [comment]
> Due to the optimization in `CanvasItem`, `global_transform` is only updated when `get_global_transform()` is called, and then notify `NOTIFICATION_TRANSFORM_CHANGED`. That is, in the case where `global_transform` is not obtained, the notification `NOTIFICATION_TRANSFORM_CHANGED` will not be sent.

That's not really true as both Node2D and Control do call `CanvasItem::_notify_transform` from their methods when their local transform is being changed.

So AFAICT for RemoteTransform2D the `NOTIFICATION_TRANSFORM_CHANGED` is being sent just fine when its `transform` changes. Meaning regardless of the value of `use_global_coordinates` the updating already works.

Given all this, this PR still makes sense because when `use_global_coordinates == false` then RemoteTransform2D still propagates its local transform on any change of its global transform. And that's not needed, in such case the propagation is needed only when the local transform changes (if global transform changes because some parent transform has changed then it's irrelevant).

**Comment by Rindbee** [comment]
https://github.com/godotengine/godot/blob/a574c0296b38d5f786f249b12e6251e562c528cc/scene/main/canvas_item.cpp#L890-L892

https://github.com/godotengine/godot/blob/a574c0296b38d5f786f249b12e6251e562c528cc/scene/main/canvas_item.cpp#L181

This flag doesn't seem to change in `Node2d`/`Control`. The optimization still works. Maybe `get_global_transform()` is called somewhere else.

**Comment by kleonc** [comment]
I wrongly assumed that `_set_global_invalid(true)` is called only from `CanvasItem::_notify_transform`. :man_facepalming:

But because it's called on `NOTIFICATION_PARENTED`:
https://github.com/godotengine/godot/blob/a574c0296b38d5f786f249b12e6251e562c528cc/scene/main/canvas_item.cpp#L371-L376
and because `NOTIFICATION_PARENTED` is received before a node is added to the tree, then it results in `is_inside_tree()` check to fail:
https://github.com/godotengine/godot/blob/a574c0296b38d5f786f249b12e6251e562c528cc/scene/main/canvas_item.cpp#L896-L907
Hence after such CanvasItem is added to the SceneTree it's marked as havinf invalid global but it's not added to the `SceneTree::xform_change_list` which would result in propagating `NOTIFICATION_TRANSFORM_CHANGED`:
https://github.com/godotengine/godot/blob/a574c0296b38d5f786f249b12e6251e562c528cc/scene/main/scene_tree.cpp#L179-L190

Seems like potentially a bigger issue. :thinking:

---

 Regarding specifically the changes in this PR the 2D part looks good to me anyway. I haven't dived into 3D notifications.

**Comment by Rindbee** [comment]
> Regarding specifically the changes in this PR the 2D part looks good to me anyway. I haven't dived into 3D notifications.

There is currently no relevant optimization in 3D. If it is not needed, I can reset that commit.

**Comment by kleonc** [comment]
> There is currently no relevant optimization in 3D. 

Indeed, so what I've said in https://github.com/godotengine/godot/pull/83323#issuecomment-1762896443 is true for the RemoteTransform3D (but not for the RemoteTransform2D because of the discussed optimization).

>If it is not needed, I can reset that commit.

No, the changes are good. :+1: Quoting myself (just replace RemoteTransform2D with RemoteTransform3D):

> Given all this, this PR still makes sense because when `use_global_coordinates == false` then RemoteTransform2D still propagates its local transform on any change of its global transform. And that's not needed, in such case the propagation is needed only when the local transform changes (if global transform changes because some parent transform has changed then it's irrelevant).

File: scene/3d/remote_transform_3d.cpp [hunk 1]
```diff
@@ -140,7 +141,14 @@ NodePath RemoteTransform3D::get_remote_node() const {
...
 
 void RemoteTransform3D::set_use_global_coordinates(const bool p_enable) {
+	if (use_global_coordinates == p_enable) {
+		return;
+	}
+
 	use_global_coordinates = p_enable;
+
+	set_notify_transform(use_global_coordinates);
+	set_notify_local_transform(!use_global_coordinates);
```
Comment (kleonc) [inline scene/3d/remote_transform_3d.cpp:151]: I think `_update_remote()` is also needed in here, no ? :thinking: (for 2D it's in there)
```suggestion
	set_notify_transform(use_global_coordinates);
	set_notify_local_transform(!use_global_coordinates);
	_update_remote();
```

File: scene/2d/remote_transform_2d.cpp [hunk 2]
```diff
@@ -141,7 +142,13 @@ NodePath RemoteTransform2D::get_remote_node() const {
 }
 
 void RemoteTransform2D::set_use_global_coordinates(const bool p_enable) {
+	if (use_global_coordinates == p_enable) {
+		return;
+	}
```
Comment (kleonc) [inline scene/2d/remote_transform_2d.cpp:147]: Probably makes sense to also add such guards to other setters (`set_use_position` etc.).

File: scene/3d/remote_transform_3d.cpp (hunk 1 above)
Comment (Rindbee) [reply scene/3d/remote_transform_3d.cpp:151]: Yes, it makes sense.

**Review by kleonc — APPROVED** [review]
LGTM! :+1:
I've also tested it is some more (debug-stepped through some notification code etc.), haven't noticed any issue.

Changed milestone to 4.2 as 2D part is a bugfix (3D part can be treated as an enhancement as it effectively only removes some redundant transform updates for the target node).

**Comment by akien-mga** [comment]
Thanks!
