### PR TITLE
[3.x] Fix for 2D viewport not updating in the editor when the camera moves

### LINKED ISSUE #40441: Viewports do not register 2D Cameras while in the editor
**Godot version:**
v3.2.1

**OS:**
Windows 10

**Issue description:**
When rendering the contents of a Viewport while in the editor, it ignores Camera2Ds. The bug does not occur when rendering 3D objects using a viewport.

**Steps to reproduce:**
1. Open reproduction project 
4. Observe editor preview of a Viewport with a 2D scene with 2D.tscn

image

5. Run 2D.tscn (the view now correctly uses the Camera2D)
image

**Minimal reproduction project:**
[ViewportTextureEditorBug.zip](https://github.com/godotengine/godot/files/4929957/ViewportTextureEditorBug.zip)

### PR DESCRIPTION
**Pull request by radenling**
This fixes a problem with 2D viewports not taking the camera position into consideration when previewed in the editor.

Backport of #69644.

Fixes #40441

### CODE REVIEW

File: scene/2d/camera_2d.cpp [hunk 1]
```diff
@@ -41,8 +41,10 @@ void Camera2D::_update_scroll() {
 	}
 
 	if (Engine::get_singleton()->is_editor_hint()) {
-		update(); //will just be drawn
-		return;
+		update();
+		// Only set viewport transform when not bound to the main viewport
+		if (get_viewport() == get_tree()->get_edited_scene_root()->get_viewport())
+			return;
 	}
```
Comment (lawnjelly) [inline scene/2d/camera_2d.cpp:48]: Needs braces around the `return;` as in your 4.x PR, that's the coding convention even for one liners.

**Comment by lawnjelly** [comment]
Aside for the braces comment above, this looks fine, will wait for the fix before approving.

**Comment by radenling** [comment]
I seem to have fixed it locally and then forgotten to push the changes. Anyways, they're up!

**Review by lawnjelly — APPROVED** [review]
Looks fine similar to 4.x.

Note that if `get_tree()` or `get_edited_scene_root()` fail, this will crash, but I'm assuming you have checked these conditions can't happen. If not these situations would need dealing with.

**Comment by KoBeWi** [comment]
> Note that if get_tree() or get_edited_scene_root() fail, this will crash

`get_tree()` is handled by `!is_inside_tree()` condition above.
`get_edited_scene_root()` by `Engine::get_singleton()->is_editor_hint()` (AFAIK scene root is null only on empty scenes).

**Comment by SallarShayegan** [comment]
hello everyone, how can I apply this change to the already installed Godot application? I'm running v3.5.1 stable mono version which I've downloaded from the official website and installed on macos (I don't run the development or git repo)

would be thankful if I could get some support

**Comment by Calinou** [comment]
> hello everyone, how can I apply this change to the already installed Godot application? I'm running v3.5.1 stable mono version which I've downloaded from the official website and installed on macos (I don't run the development or git repo)
> 
> would be thankful if I could get some support

You can get the [3.5.2 source code](https://docs.godotengine.org/en/3.5/development/compiling/getting_source.html), patch it with this pull request's changes:

```
git switch --detach 3.5.2-stable
curl -L https://github.com/godotengine/godot/pull/69645.patch | git am
```

Then [compile the source for macOS](https://docs.godotengine.org/en/3.5/development/compiling/compiling_for_osx.html) [with Mono support](https://docs.godotengine.org/en/3.5/development/compiling/compiling_with_mono.html). Be advised though, as the Mono support makes it quite harder to build from source.

**Comment by SallarShayegan** [comment]
> 
> You can get the 3.5.2 source code and patch it with this pull request's changes:
> 
> ```shell
> git clone --branch="3.5.2-stable" https://github.com/godotengine/godot.git
> curl -L https://github.com/godotengine/godot/pull/69645.patch | git am
> ```
> 
> Then [compile the source for macOS](https://docs.godotengine.org/en/3.5/development/compiling/compiling_for_osx.html) with [Mono support](https://docs.godotengine.org/en/3.5/development/compiling/compiling_with_mono.html). Be advised though, as having to build with Mono support makes it more difficult to build from source.

Thanks a lot, I've once tried to build from source but several errors occurred, as installing the mono version on a Mac has a lot more difficulties because of .net support

is the fix going to be part of the next 3.x version, which is ready to use without building from source?

**Comment by akien-mga** [comment]
Thanks!
