### PR TITLE
Fix spatial editor plugin issues on multi viewport view menu shortcuts (only those that are bound to keys)

### LINKED ISSUE #12409: Focus/Align Hotkeys Apply to Only one Viewport
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, Godot 3.0 #12328

**Issue description:**
When using multiple viewports, the hotkeys binded to "Focus Origin", "Focus Selected" and "Align Selection With View", only change focus in the most bottom-right positioned viewport. I believe that "Align Selection With View" should align to the viewport that the mouse is on top of, but "Focus Origin" and "Focus Selected" could be applied to all viewports at once.
Selecting the option from a viewport's drop-down menu performs the action normally on the viewport selected.

**Steps to reproduce:**
1. Create a scene with an object and select multiple viewports from the View menu.
2. Use the hotkeys discussed.

### LINKED ISSUE #14371: "F" key Viewport focus problem
version -> http://godot3builds.digitecnology.com/builds/2017-12-06.12:52:48.a8ae46e14/godot-v3.0-osx.fat.zip

**Issue description:**
When i press F key, wrong viewport is active.

**Steps to reproduce:**
https://www.youtube.com/watch?v=y5K5xv7UBuo&feature=youtu.be

### PR DESCRIPTION
**Pull request by carlosfvieira**
These are proposed changes that closes #14371 and closes #12409

**Problem:**

All view menu items, that are also shortcuts activated by a Key, had issues with the viewport that was being updated...
In the case of multiple viewports, instead of the action to be applied to the viewport in focus, it was being applied always and only to the last viewport.

The affected key shortcuts were these ones:
- Top View
- Bottom View
- Left View
- Right View
- Front View
- Rear View
- Focus Origin
- Focus Selection
- Align Selection With View

Also, for the top/bottom/left/view/front/rear view shortcuts, there was duplicated code being ran, which caused updates to the focused viewport, and the last viewport.

**Proposed solution:**
- When a viewport looses focus, the view menu is hidden avoiding the menu action being called, when a key shortcut was used
- When a viewport gains focus, the view menu is set to visible -> either a click the menu item, or a key shortcut is used, the correct focused viewport will be updated, since it is the only viewport that has the view menu active, and so, it's the only menu/shortcut action that will trigger the event action
- All of those key shortcuts are now being handled by the `_sinput(...)` method, which call then the `_menu_option(...)` method, where the logic code related to the action is, in fact:
  - when shortcut is used -> `_sinput(...)`
  - when menu item is used -> `_menu_option(...)`

I've tested this fix with success... now the key shortcut actions listed above, updates only the focused viewport, as it should be.

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks for your contribution! Haven't reviewed it in details but it looks fine overall.

Note: Please use more descriptive titles (and if relevant, descriptions) for your commit, so that we can know what the commit does when reading the changelog, without having to go to GitHub, find again the mentioned issues, and understand how they were fixed. See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-logs-with-readability-in-mind

**Comment by carlosfvieira** [comment]
Yes, you're right... Deal! I'll take into account in the next contributions :+1: 

>Note: Please use more descriptive titles (and if relevant, descriptions) for your commit, so that we can know what the commit does when reading the changelog, without having to go to GitHub, find again the mentioned issues, and understand how they were fixed. See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-logs-with-readability-in-mind

**Comment by vnen** [comment]
Actually you should fix this commit. You can dot a `git commit --amend` to edit the message and then force push to your branch. The PR will be updated automatically. Check http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request

**Comment by carlosfvieira** [comment]
commit description was amended

File: editor/plugins/spatial_editor_plugin.cpp [hunk 1]
```diff
@@ -823,6 +823,16 @@ void SpatialEditorViewport::_smouseexit() {
 	_remove_preview();
 }
 
+void SpatialEditorViewport::_sfocusentered() {
```
Comment (reduz) [inline editor/plugins/spatial_editor_plugin.cpp]: you can use NOTIFICATION_FOCUS_ENTER and EXIT instead of connecting a signal

File: editor/plugins/spatial_editor_plugin.cpp [hunk 2]
```diff
@@ -823,6 +823,16 @@ void SpatialEditorViewport::_smouseexit() {
...
+
+	view_menu->show();
```
Comment (reduz) [inline editor/plugins/spatial_editor_plugin.cpp]: I don't like the idea of hiding, would prefer a function that disables shortcuts on it (on MenuButton), so it can be disabled when not focused.

File: editor/plugins/spatial_editor_plugin.cpp (hunk 1 above)
Comment (carlosfvieira) [reply editor/plugins/spatial_editor_plugin.cpp]: Ok

File: editor/plugins/spatial_editor_plugin.cpp (hunk 2 above)
Comment (carlosfvieira) [reply editor/plugins/spatial_editor_plugin.cpp]: Ok

File: editor/plugins/spatial_editor_plugin.cpp (hunk 1 above)
Comment (carlosfvieira) [reply editor/plugins/spatial_editor_plugin.cpp]: as per our conversation, signals must be used in this case

File: editor/plugins/spatial_editor_plugin.cpp (hunk 2 above)
Comment (carlosfvieira) [reply editor/plugins/spatial_editor_plugin.cpp]: a disable all shortctus mechanism was done, following your suggestions... all changes wwere squashed into one commit, that you can review
