### PR TITLE
Fix crash when using "Close All Tabs"

### LINKED ISSUE #79943: Godot editor crash with signal SIGSEGV when "Close All Tabs" is selected
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable (bd6af8e0e) - Freedesktop SDK 22.08 (Flatpak runtime) - Vulkan (Forward+) - integrated AMD Custom GPU 0405 (RADV VANGOGH) () - AMD Custom APU 0405 (8 Threads)

### Issue description

Closing all scene tabs in Godot results with a crash with following signature:

```
Godot Engine v4.1.1.stable.flathub.bd6af8e0e - https://godotengine.org
Vulkan API 1.3.246 - Forward+ - Using Vulkan Device #0: AMD - AMD Custom GPU 0405 (RADV VANGOGH)

handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.1.1.stable.flathub (bd6af8e0ea69167dd0627f3bd54f9105bda0f8b5)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
ERROR: FATAL: Index p_index = 1 is out of bounds (size() = 0).
   at: get (./core/templates/cowdata.h:155)
```

Since this is a release build which is missing debug symbols, the whole backtrace is not visible. Due to that, I have downloaded source code and build myself a debug version (latest commit on master available at the time) of Godot and got the following more insightful backtrace:

```
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.dev.custom_build (6588a4a29af1621086feac0117d5d4d37af957fd)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x38a00) [0x7f11002dea00] (??:0)
[2] /run/media/mmcblk0p1/godot/bin/godot.linuxbsd.editor.dev.x86_64(__dynamic_cast+0x2d) [0x55bffe1e44bd] (??:?)
[3] Node* Object::cast_to<Node>(Object*) (/opt/workspace/./core/object/object.h:764 (discriminator 1))
[4] VariantObjectClassChecker<Node*>::check(Variant const&) (/opt/workspace/./core/variant/binder_common.h:230)
[5] VariantCasterAndValidate<Node*>::cast(Variant const**, unsigned int, Callable::CallError&) (/opt/workspace/./core/variant/binder_common.h:256 (discriminator 2))
[6] void call_with_variant_args_helper<__UnexistingClass, Dictionary, Node*, 0ul, 1ul>(__UnexistingClass*, void (__UnexistingClass::*)(Dictionary, Node*), Variant const**, Callable::CallError&, IndexSequence<0ul, 1ul>) (/opt/workspace/./core/variant/binder_common.h:303 (discriminator 4))
[7] void call_with_variant_args_dv<__UnexistingClass, Dictionary, Node*>(__UnexistingClass*, void (__UnexistingClass::*)(Dictionary, Node*), Variant const**, int, Callable::CallError&, Vector<Variant> const&) (/opt/workspace/./core/variant/binder_common.h:451)
[8] MethodBindT<Dictionary, Node*>::call(Object*, Variant const**, int, Callable::CallError&) const (/opt/workspace/./core/object/method_bind.h:331)
[9] Object::callp(StringName const&, Variant const**, int, Callable::CallError&) (/opt/workspace/core/object/object.cpp:739 (discriminator 1))
[10] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (/opt/workspace/core/variant/callable.cpp:62)
[11] CallQueue::_call_function(Callable const&, Variant const*, int, bool) (/opt/workspace/core/object/message_queue.cpp:220)
[12] CallQueue::flush() (/opt/workspace/core/object/message_queue.cpp:326)
[13] SceneTree::physics_process(double) (/opt/workspace/scene/main/scene_tree.cpp:473)
[14] Main::iteration() (/opt/workspace/main/main.cpp:3396)
[15] OS_LinuxBSD::run() (/opt/workspace/platform/linuxbsd/os_linuxbsd.cpp:912)
[16] /run/media/mmcblk0p1/godot/bin/godot.linuxbsd.editor.dev.x86_64(main+0x19f) [0x55bff8d0f4e8] (/opt/workspace/platform/linuxbsd/godot_linuxbsd.cpp:76)
[17] /usr/lib/libc.so.6(+0x23290) [0x7f11002c9290] (??:0)
[18] /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f11002c934a] (??:0)
[19] /run/media/mmcblk0p1/godot/bin/godot.linuxbsd.editor.dev.x86_64(_start+0x25) [0x55bff8d0f285] (??:?)
-- END OF BACKTRACE --
```

Based on the fact that I am a total beginner with Godot code base, and that I know that the Godot 4.0.3 doesn't have this issue, and the fact that this is trivial to reproduce, I have decided to use `git bisect` to find the first bad commit which is:

```
commit ddc856702264cf892cea6e19f57d750ab824952a
Author: kobewi <kobewi4e@gmail.com>
Date:   Fri Oct 14 20:41:05 2022 +0200

    Scene tab closing refactor
```

This commit from Kobe helped me tremendously to focus on just a small code path. Together with this information and a couple of sessions with GDB, I have found the following:

```
Thread 1 "godot.linuxbsd." received signal SIGSEGV, Segmentation fault.
0x000055555d3a4e3d in __dynamic_cast ()
(gdb) bt
#0  0x000055555d3a4e3d in __dynamic_cast ()
#1  0x0000555557d4d700 in Object::cast_to<Node> (p_object=0x555560f5eee0) at ./core/object/object.h:754
#2  0x00005555587413e6 in VariantObjectClassChecker<Node*>::check (p_variant=...) at ./core/variant/binder_common.h:220
#3  0x0000555558741290 in VariantCasterAndValidate<Node*>::cast (p_args=0x7fffffffd860, p_arg_idx=1, r_error=...) at ./core/variant/binder_common.h:246
#4  0x00005555598ab795 in call_with_variant_args_helper<__UnexistingClass, Dictionary, Node*, 0ul, 1ul> (p_instance=0x55556382d4c0, 
    p_method=(void (__UnexistingClass::*)(__UnexistingClass * const, Dictionary, Node *)) 0x555559839456 <EditorNode::_set_main_scene_state(Dictionary, Node*)>, p_args=0x7fffffffd860, r_error=...) at ./core/variant/binder_common.h:293
#5  0x00005555598a9ef1 in call_with_variant_args_dv<__UnexistingClass, Dictionary, Node*> (p_instance=0x55556382d4c0, p_method=(void (__UnexistingClass::*)(__UnexistingClass * const, Dictionary, Node *)) 0x555559839456 <EditorNode::_set_main_scene_state(Dictionary, Node*)>, 
    p_args=0x7fffffffda80, p_argcount=2, r_error=..., default_values=...) at ./core/variant/binder_common.h:440
#6  0x00005555598a491a in MethodBindT<Dictionary, Node*>::call (this=0x55557108d130, p_object=0x55556382d4c0, p_args=0x7fffffffda80, p_arg_count=2, r_error=...) at ./core/object/method_bind.h:324
#7  0x000055555ce7c423 in Object::callp (this=0x55556382d4c0, p_method=..., p_args=0x7fffffffda80, p_argcount=2, r_error=...) at core/object/object.cpp:733
#8  0x000055555cac8c13 in Callable::callp (this=0x7ffff2753af0, p_arguments=0x7fffffffda80, p_argcount=2, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:62
#9  0x000055555ce76036 in MessageQueue::_call_function (this=0x555561238e60, p_callable=..., p_args=0x7ffff2753b08, p_argcount=2, p_show_error=false) at core/object/message_queue.cpp:229
#10 0x000055555ce7639d in MessageQueue::flush (this=0x555561238e60) at core/object/message_queue.cpp:275
#11 0x000055555ab31046 in SceneTree::physics_process (this=0x5555638337f0, p_time=0.016666666666666666) at scene/main/scene_tree.cpp:430
#12 0x0000555557d44ea0 in Main::iteration () at main/main.cpp:3131
#13 0x0000555557cbab78 in OS_LinuxBSD::run (this=0x7fffffffdd90) at platform/linuxbsd/os_linuxbsd.cpp:889
#14 0x0000555557cb12d8 in main (argc=4, argv=0x7fffffffe2d8) at platform/linuxbsd/godot_linuxbsd.cpp:73
(gdb) frame 9
#9  0x000055555ce76036 in MessageQueue::_call_function (this=0x555561238e60, p_callable=..., p_args=0x7ffff2753b08, p_argcount=2, p_show_error=false) at core/object/message_queue.cpp:229
(gdb) p *p_callable.method._data
$4 = {refcount = {count = {value = {<std::__atomic_base<unsigned int>> = {static _S_alignment = 4, _M_i = 8}, static is_always_lock_free = true}}}, static_count = {value = {<std::__atomic_base<unsigned int>> = {static _S_alignment = 4, _M_i = 1}, 
      static is_always_lock_free = true}}, cname = 0x0, name = {_cowdata = {_ptr = 0x55557108a8d0 U"_set_main_scene_state"}, static _null = 0 U'\000', static invalid_node_name_characters = {_cowdata = {_ptr = 0x555560f14470 U". : @ / \" %"}, static _null = 0 U'\000', 
      static invalid_node_name_characters = <same as static member of an already seen type>}}, debug_references = 0, idx = 10433, hash = 704063681, prev = 0x0, next = 0x55556319f4a0}
```

From this backtrace, it can be seen that the method `_set_main_scene_state` is called deferred (on the next call to physics_process) for each of the scenes that Godot actually removed. Since a scene is removed (memory holding this scene has been de-allocated), `dynamic_cast` casts an invalid address (address that Godot now doesn't have an access to anymore) which results in SIGSEGV.

This issue is reproducible on 4.1 as well as on master branch.

### Steps to reproduce

Issue is trivial to reproduce with reproduction rate of 100%. No special project configuration is needed. The only precondition is to have multiple scene files available in a project. For your convenience, attached is a test project from which this issue can be reproduced.

Steps to reproduce this issue are following:

1. Open the attached project in Godot.
2. Open two or more scenes. More then one scene has to be open for editing, otherwise the issue will not be triggered.
3. Right click on one of the opened scene tabs and from the popup menu click on "Close All Tabs".

The last step will cause Godot to crash.

### Minimal reproduction project

[test.tar.gz](https://github.com/godotengine/godot/files/12179462/test.tar.gz)

### PR DESCRIPTION
**Pull request by hvarga**
Fixes #79943.

I have fixed this in a way so that this deferred call to `_set_main_scene_state` is done only once at the very end after all tabs are closed.

There is a potential for further improvement which can speed-up the closing of the tabs. I could be wrong, and probably I am due to my lack of knowledge about Godot, but I don't see any need to update the editor for each of the closed tab. The update can be done only once at the end when closing of scene tabs is complete. But I will leave this decision to guys smarter then me like Tomasz Chabora who made this original refactor.

### CODE REVIEW

**Comment by hvarga** [comment]
[test_project.tar.gz](https://github.com/godotengine/godot/files/12171921/test_project.tar.gz)

**Comment by hvarga** [comment]
I have tried to not break the legacy code, and hopefully I haven't. I have tested this change manually, but it would be really good if we could have tests for the GUI as well. I can see that the tests are using mocked display server and `test_macros.h` has `_SEND_DISPLAYSERVER_EVENT` to simulate input events from mouse or keyboard. Is it possible to use this mechanism to test something like closing of editor scene tabs?

**Comment by hvarga** [comment]
@YuriSizov, can we port this to 4.1 branch? I know this is not something that blocks, but I would really like to have it on 4.1.x since I am using this version for my purposes. On the other hand, there is really nothing that keeps me on 4.1. I can always downgrade to 4.0.

But if a backport comes to mind, just note that, while the first issue reproducible on 4.1.x, the second one is only reproducible on master branch. I will add this info as well in the description. What I am trying to say is that, if someone decides to backport this change, we need to separate this into two PRs.

**Comment by YuriSizov** [comment]
@hvarga Generally speaking, you shouldn't mix together different fixes to begin with. In this case they are closely related, so I haven't asked you to split them. But since you raise that concern yourself, it's worth a mention.

It would also be great if you open issue reports first, so PRs can be properly linked to them, especially since these are different issues affecting different versions and thus different users. It doesn't mean you need to wait for something, you can just open the report and the relevant PR at the same time.

We normally cherry-pick PRs that are trivially cherry-pickable and only ask for backports if this is not the case. So that's another reason to make separate PRs for separate fixes.

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -3617,7 +3617,8 @@ void EditorNode::set_current_scene(int p_idx) {
 	_update_title();
 	_update_scene_tabs();
 
-	call_deferred(SNAME("_set_main_scene_state"), state, get_edited_scene()); // Do after everything else is done setting up.
+	if (tabs_to_close.is_empty())
+		call_deferred(SNAME("_set_main_scene_state"), state, get_edited_scene()); // Do after everything else is done setting up.
```
Comment (YuriSizov) [inline editor/editor_node.cpp:3621]:
```suggestion
	if (tabs_to_close.is_empty()) {
		call_deferred(SNAME("_set_main_scene_state"), state, get_edited_scene()); // Do after everything else is done setting up.
	}
```

This doesn't follow our codestyle. Curly brackets are mandatory.

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -5387,7 +5385,8 @@ void EditorNode::_load_open_scenes_from_config(Ref<ConfigFile> p_layout) {
 	if (p_layout->has_section_key(EDITOR_NODE_CONFIG_SECTION, "current_scene")) {
 		String current_scene = p_layout->get_value(EDITOR_NODE_CONFIG_SECTION, "current_scene");
 		int current_scene_idx = scenes.find(current_scene);
-		set_current_scene(current_scene_idx);
+		if (current_scene_idx >= 0)
+			set_current_scene(current_scene_idx);
```
Comment (YuriSizov) [inline editor/editor_node.cpp:5389]:
```suggestion
		if (current_scene_idx >= 0) {
			set_current_scene(current_scene_idx);
		}
```

Same here.

**Comment by hvarga** [comment]
Understood. I will separate this into two PRs and also open issues for them.

**Comment by hvarga** [comment]
@YuriSizov I am done with separating this change into two PRs. The second fix is done in #79945.

**Comment by YuriSizov** [comment]
> Sorry for the noise.

No problem at all! You did a lot of work identifying and describing problems despite this being your first engine contribution. Hiccups can happen, and it all looks perfect now :)

**Review by KoBeWi — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks! And congrats on your first merged Godot PR!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.
