### PR TITLE
GLES2: Restructure depth_internalformat code to work on mobile

### LINKED ISSUE #33551: 3.2 beta - shadows from DirectionalLight broken on android gles2
**Godot version:**
Godot Engine v3.2.beta.custom_build.953f37f49

**OS/device including version:**
```
Android GLES: ARM, Mali-450 MP, OpenGL ES 2.0
GL_EXT_debug_marker GL_OES_texture_npot GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map GL_KHR_debug
EGL:
EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_ANDROID_image_native_buffer EGL_ANDROID_recordable EGL_ANDROID_native_fence_sync EGL_ANDROID_framebuffer_target EGL_EXT_create_context_robustness EGL_ANDROID_blob_cache
```
**Issue description:**
DirectionalLight shadows are broken on android gles2 device.
SpotLight shadows seems to work as intended on android gles2 device.
OmniLight shadows seems to work as intended on android gles2 device.
All three light types seems to work ok on desktop PC.
There are no error's in log.

directionallight_shadow
(there are grid because image is taken from editor)

but on android it looks like whole scene is covered with one huge shadow
Screenshot_2019-11-12-00-36-25
(whole scene is more dark and there are no shadow shape)

**Steps to reproduce:**
try example project on android gles2 device

**Minimal reproduction project:**
[DirectionalLight_shadow.zip](https://github.com/godotengine/godot/files/3833604/DirectionalLight_shadow.zip)

### LINKED ISSUE #33825: Glow on GLES 2 not work in Android
Godot Engine 3.2 beta 2:

Develop on Windows 10, Export to Nokia 7.1 Android 9:

In alpha 3, the effect works fine, in beta 1 and beta 2 it is completely absent.
The project is the same.:

1. Create a project with GLES 2
2. Add light, some (any) objects
3. Turn on the glow and try to adjust it
4. Export to device
5. Run and Watch

### PR DESCRIPTION
**Pull request by akien-mga**
*Edit:* Added commit by @clayjohn that fixes #33825.

**Restructure depth_internalformat code to work on mobile**

This changes the code path so that `glRenderBufferStorage*` always uses
values appropriate for renderbuffers and `glTexImage2D` never uses an
internalformat meant for buffers.

Fixes #33825.

*Edit:* Fixes #33551.

---

The `format` parameter is similar to `internalFormat` but takes different
values, and especially only `GL_DEPTH_COMPONENT` for depth, without size
specifier.

Cf. https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glTexImage2D.xhtml

Fixes a regression from #33278 and another occurrence.

---

I don't know if it actually caused issues though, I thought it could be a cause for #33825 but this PR does not fix it.

### CODE REVIEW

**Comment by akien-mga** [comment]
> Cf. https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glTexImage2D.xhtml

Actually referencing the ES 3.0 docs for that is probably not a good idea.
ES 2.0 docs don't mention depth components at all (http://docs.gl/es2/glTexImage2D), so I'll dig up the relevant extension to find out what the expected ES 2.0 parameters should be.

**Comment by akien-mga** [comment]
>  ES 2.0 docs don't mention depth components at all (http://docs.gl/es2/glTexImage2D), so I'll dig up the relevant extension to find out what the expected ES 2.0 parameters should be.

https://www.khronos.org/registry/OpenGL/extensions/OES/OES_depth_texture.txt adds `DEPTH_COMPONENT` for both `internalFormat` and `format`, so we're good.

File: drivers/gles2/rasterizer_storage_gles2.cpp [hunk 1]
```diff
@@ -5783,27 +5783,29 @@ void RasterizerStorageGLES2::initialize() {
...
 
 #ifdef GLES_OVER_GL
 	config.float_texture_supported = true;
 	config.s3tc_supported = true;
 	config.pvrtc_supported = false;
 	config.etc1_supported = false;
 	config.support_npot_repeat_mipmap = true;
-	config.depth_internalformat = GL_DEPTH_COMPONENT;
-	config.depth_type = GL_UNSIGNED_INT;
+	config.depth_buffer_internalformat = GL_DEPTH_COMPONENT24;
```
Comment (akien-mga) [inline drivers/gles2/rasterizer_storage_gles2.cpp]: I've tried looking whether it's OK to use `GL_DEPTH_COMPONENT24` for `glRenderbufferStorage` on OpenGL 2.1, but navigating the specs and various extensions is as painful as ever...

What I found so far:
- `glRenderbufferStorage` is not core in OpenGL 2.1, we use `glRenderbufferStorageEXT` from https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_framebuffer_object.txt, which only defines `STENCIL_INDEX{1,4,8,16}_EXT` as valid `internalFormat` values.
Amazingly the examples in `EXT_framebuffer_object` do use `GL_DEPTH_COMPONENT24` but don't specify where they take it from.
- `glTexImage2D` for OpenGL 2.1 mentions that `GL_DEPTH_COMPONENT24` is available with GL 1.4+. It's however in the content of `glTexImage2D`, it doesn't tell us if it's available for `EXT_framebuffer_object`.
- https://www.khronos.org/registry/OpenGL/extensions/OES/OES_depth24.txt adds `GL_DEPTH_COMPONENT24` for the OpenGL **ES** extension. As I understand it there `glRenderbufferStorage` is core in ES 2.0, but this extension is still needed for the 24-bit component.

What a mess... I guess if it compiles, it's fine...

(Reposted from akien-mga/godot#4.)

**Comment by akien-mga** [comment]
Thanks @clayjohn!

**Comment by clayjohn** [comment]
For our future reference. The EXT_framebuffer_object extension documentation specifies that any internal format found in table 3.16 of the spec is valid for render buffer storage. It includes DEPTH_COMPONENT(16, 24, and 32)
