### PR TITLE
Apply inspector read_only only when changed

### LINKED ISSUE #72289: Name Textbox for Atlas resets caret position to start after every key press
### Godot version

v4.0.beta16.mono.official [518b9e580]

### System information

Windows 10

### Issue description

Typing into the textbox for Atlas's Name property resets its caret position to the start after every key press, causing you to type in reverse:

image

### Steps to reproduce

1. Add a TileMap node to a scene
2. Create a new TileSet for it in-place in the Inspector
3. In the "Tiles" tab, press the plus button to create a new Atlas
4. Start typing in the textbox for its name

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #72289

### CODE REVIEW

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -3374,6 +3374,9 @@ void EditorInspector::set_keying(bool p_active) {
 }
 
 void EditorInspector::set_read_only(bool p_read_only) {
+	if (p_read_only == read_only) {
+		return;
+	};
```
Comment (akien-mga) [inline editor/editor_inspector.cpp:3379]: Stray semicolon 🐈

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
