### PR TITLE
Fixed issues with Editor Log after recent changes

### LINKED ISSUE #48443: Number of occurrences of message doesn't update immediately in Editor Log
**Godot version:**

56316b2

**Issue description:**

Not sure if it only applies to properties or to everything, but
pnmTU2P4RM

CC @EricEzaM

### LINKED ISSUE #48446: Editor Log steals search focus
**Godot version:**

56316b2

**Issue description:**

When Output panel is expanded, pressing Ctrl + F while in Scrip Editor will focus the output.
z730FcgHNB

CC @EricEzaM

### PR DESCRIPTION
**Pull request by EricEzaM**
Fixed #48446, Fixed #48443

### CODE REVIEW

File: scene/gui/rich_text_label.cpp [hunk 1]
```diff
@@ -2615,6 +2615,7 @@ void RichTextLabel::pop() {
 // Creates a new line without adding an ItemNewline to the previous line.
 // Useful when wanting to calling remove_line and add a new line immediately after.
 void RichTextLabel::increment_line_count() {
+	_validate_line_caches(main);
```
Comment (EricEzaM) [inline scene/gui/rich_text_label.cpp:2618]: I think this was a new function added since I first wrote this PR? I definitely would have noticed #48450 in testing when I originally wrote it... Anyway, this seems to resolve the issue at least.

Comment (akien-mga) [reply scene/gui/rich_text_label.cpp:2618]: You seem to have referenced an unrelated PR here.

**Review by akien-mga — APPROVED** [review]

File: scene/gui/rich_text_label.cpp (hunk 1 above)
Comment (EricEzaM) [reply scene/gui/rich_text_label.cpp:2618]: Hmm.. was meant to be #48443

**Comment by akien-mga** [comment]
Thanks!
