### PR TITLE
Fix audio samples not being able to be "finished"

### LINKED ISSUE #94226: [4.3 beta 3] AudioStreamPlayer does not work correctly during web export
### Tested versions

Godot 4.3 Beta 3

OpenGL API OpenGL ES 3.0 (WebGL 2.0 (OpenGL ES 3.0 Chromium)) - Compatibility - Using Device: WebKit - WebKit WebGL

### System information

 Linux Ubuntu 22.04

### Issue description
There are the following problems with web export:

- For a sound that has been played at least once, the playing variable is always true
- It is impossible to set the volume of audio channels, even Master
- Cannot add effects to channels (they are ignored)

### Steps to reproduce

- Add an AudioStreamPlayer node to the scene
- Add WAV sound to it
- Play sound
- Check the $node.playing variable for the sound, it will be true even when the sound stops playing.

### Minimal reproduction project (MRP)

[audiodemo.zip](https://github.com/user-attachments/files/16190772/audiodemo.zip)

_Bugsquad edit: added the MRP_

### PR DESCRIPTION
**Pull request by adamscott**
Fixes #94226 about issues with `AudioStreamPlayer.playing` always being `true` once started. 

Now, with this PR, I keep a list of currently playing samples and remove them of the list when stopped or when receiving the "finished" callback.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: servers/audio_server.h [hunk 1]
```diff
@@ -473,6 +473,8 @@ class AudioServer : public Object {
 
 	PlaybackType get_default_playback_type() const;
 
+	Vector<Ref<AudioStreamPlayback>> sample_playback_list;
```
Comment (akien-mga) [inline servers/audio_server.h:476]: This could be a `LocalVector` I think since it's not passed around.

Comment (adamscott) [reply servers/audio_server.h]: Updated!

**Comment by akien-mga** [comment]
Thanks!
