### PR TITLE
Make FindInFiles globally accessible

### LINKED ISSUE #12418: Make Script Find in Files globally accessible
### Describe the project you are working on

Any godot project, this is an editor usability improvement

### Describe the problem or limitation you are having in your project

If you are not in the Script tab you are unable to use the `Find in Files` - `Ctrl+Shift+F` shortcut. If you have the Script tab open, but no scripts open, you are still unable to use the shortcut (but can access it through the `Search` menu).

Image

Related issue to the shortcut not working https://github.com/godotengine/godot/issues/98312

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

By making Find in Files globally accessible it provides a common feature in many IDEs. This allows users to "jump to a string in files" in the same way `Ctrl+P` or `Ctrl+Shift+P` facilitates "jump to resource" or "jump to command". 

Image

I think this could also enable other editor improvements as well as plugin developers. For example a common use case of Find in Files is to search a log string to quickly take you to what is triggering it.

If this was globally accessibly a button in the top right of the Output could be added `Find Selection in Files` much like there is a `Copy Selection` button. I think it would also be nice if this was available in the right click context menu. 

Image

Image

Image

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I have done a bit of investigation and it seems the `Ctrl+Shift+F` shortcut is unused elsewhere, where `Ctrl+F` screenshot (mockup above) is used in a few places. I think reusing the `Ctrl+Shift+F` shortcut is ok for everywhere suggested, and the currently selected `Find:` text will be pre-filled depending on the context the shortcut was used.

In terms of code I found that currently the [FindInFiles](https://github.com/godotengine/godot/blob/master/editor/find_in_files.h) family of classes has the implementation, and the actual usage is in the [ScriptEditorPlugin](https://github.com/godotengine/godot/blob/master/editor/plugins/script_editor_plugin.cpp) class. 

I'm not sure where it needs to move to, or if it needs to be used elsewhere as well, instead of moving completely; as well as any nuances that would entail. I would appreciate some help here. 

My first thought would be around where [Quick Open](https://github.com/godotengine/godot/blob/db6634352870de6a7e2f43dbac8cd74288b24743/editor/editor_node.cpp#L7804) or the [Command Palette](https://github.com/godotengine/godot/blob/db6634352870de6a7e2f43dbac8cd74288b24743/editor/editor_node.cpp#L7913) start. 

I also think the implementation of this should add the Output/EditorLog improvements as demonstrated above. I think the button [would be straightforward](https://github.com/godotengine/godot/blob/db6634352870de6a7e2f43dbac8cd74288b24743/editor/editor_log.cpp#L478-L490), but the context menu may be more difficult because the output uses a [RichTextLabel](https://github.com/godotengine/godot/blob/db6634352870de6a7e2f43dbac8cd74288b24743/editor/editor_log.cpp#L451-L452) and I'm not sure if that supports context menu additions.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't believe so

### Is there a reason why this should be core and not an add-on in the asset library?

I'm not sure if this is possible with a plugin, but it feels like a core usability enhancement with no foreseen drawbacks

### LINKED ISSUE #98312: Project-wide-search keyboard shortcut doesn't work if no script is open
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

Mac OS 10.14.8

### Issue description

See title.

### Steps to reproduce

1. Open a project.
2. Press Command+Shift+F.
3. Observe that nothing happens.
4. Open the script tab and do the same, still nothing happens.
5. Open a script, and now it works.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Frozenfire92**
Closes https://github.com/godotengine/godot-proposals/issues/12418
Closes https://github.com/godotengine/godot/issues/98312

[2025-05-19-00.webm](https://github.com/user-attachments/assets/6e069363-6942-40a0-801b-baf2cbd4ceaa)

### Summary
FindInFiles is inherently tied to the ScriptEditor as that is where the results are opened. With the current implementation you can only FindInFiles when the Script tab is open (and use the keyboard shortcut only when a file is open).

To make this more global I have left all the connection in ScriptEditor, but have exposed FindInFilesDialog as a singleton as that is the entry point for triggering the action.

In the proposal I have suggested making changes to the EditorLog as well, but that was starting to feel like scope creep and has been undone. I have opened a proposal (https://github.com/godotengine/godot-proposals/issues/12462) specifically for it to gather more discussion instead.

### Changes
- Make ScriptEditor expose open_find_in_files_dialog to replace `_on_find_in_files_requested` to allow opening from anywhere
- Add FindInFiles to EditorNode as a keyboard shortcut, command, and project menu option
- Change all find_in_files commands/shortcuts to be editor/find_in_files

### CODE REVIEW

**Comment by cruglet** [comment]
I'd honestly rather the button being under the `Project` dropdown (maybe under the `Tools` submenu?) since "find in files" goes through your project's directory. The Editor tab is more for configuration _across_  different projects.

**Comment by Frozenfire92** [comment]
I definitely think the Project menu makes more sense, but Tools kind of imply modifications/seldom used; I worry it might be hidden there 🤔

**Comment by arkology** [comment]
> Add FindInFiles shortcut/button to the EditorLog

This will worsen the size issues on small screen devices. I suggest not adding this button.

**Comment by Frozenfire92** [comment]
> This will worsen the size issues on small screen devices. I suggest not adding this button.

I agree, but I think the functionality is quite useful. Is it possible to have the keyboard shortcut only?

Some other alternatives:
- add to the context menu as suggested in initial proposal
- remove the copy selection button and replace it with this new button (as copy is a commonly known keyboard shortcut and available in the context menu already, so it would still be mouse-only-accessible)

**Comment by cruglet** [comment]
> This will worsen the size issues on small screen devices. I suggest not adding this button.

Can you clarify what you mean by "size issues"

**Comment by arkology** [comment]
> > This will worsen the size issues on small screen devices. I suggest not adding this button.
> 
> Can you clarify what you mean by "size issues"

Like this `https://github.com/godotengine/godot/issues/26835`

**Comment by Frozenfire92** [comment]
I have moved the menu option to the Project menu in [9345e7f](https://github.com/godotengine/godot/pull/106500/commits/9345e7f9fe6d1c7d24f08637618cafe45ee71251)

My thinking for the location of it is command palette is under the editor settings as it lets you find something in the editor, so I put find in files under the project settings as it lets you find something in the project

image

image

**Comment by Frozenfire92** [comment]
I've been working on the EditorLog and thinking about how best to prevent adding more buttons to the interface (when its already tight on small screen/window sizes). I think keeping this as a shortcut makes a lot of sense, which I have added in [9a348ab](https://github.com/godotengine/godot/pull/106500/commits/9a348ab34a83812eeebe530210057ea5b5801308)

I think it might make sense to have a separate proposal for the EditorLog interface changes to prevent scope creep from this PR, and allow it to get the thought and intention it deserves.

With the change in [9a348ab](https://github.com/godotengine/godot/pull/106500/commits/9a348ab34a83812eeebe530210057ea5b5801308) it works, however there is a slight nuance of the selection always taking precedence when the shortcut is initiated outside of the Script window. I think this is probably fine but if there is a nice way to fix this I'd be happy to change it.

[2025-05-17-00.webm](https://github.com/user-attachments/assets/cc027a1a-adfd-41fe-8cd3-a0033893443c)

**Comment by arkology** [comment]
> it might make sense to have a separate proposal for the EditorLog interface changes to prevent scope creep from this PR

This. Because having global `Find In Files` dialog is an improvement from any point of view, but changes in `EditorLog` need more discussion/consensus.

File: editor/editor_node.h [hunk 1]
```diff
@@ -263,6 +265,7 @@ class EditorNode : public Node {
 	EditorResourcePreview *resource_preview = nullptr;
 	EditorSelection *editor_selection = nullptr;
 	EditorSettingsDialog *editor_settings_dialog = nullptr;
+	FindInFilesDialog *find_in_files_dialog = nullptr;
```
Comment (arkology) [inline editor/editor_node.h:268]: Maybe changes in header and constructor (`find_in_files_dialog` assignment) could be moved directly to `case PROJECT_FIND_IN_FILES: {` (to keep variable local).

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -7858,6 +7867,9 @@ EditorNode::EditorNode() {
 	project_menu->add_shortcut(ED_SHORTCUT_AND_COMMAND("editor/project_settings", TTRC("Project Settings..."), Key::NONE, TTRC("Project Settings")), PROJECT_OPEN_SETTINGS);
 	project_menu->connect(SceneStringName(id_pressed), callable_mp(this, &EditorNode::_menu_option));
 
+	ED_SHORTCUT_AND_COMMAND("editor/find_in_files", TTRC("Find in Files..."), KeyModifierMask::CMD_OR_CTRL | KeyModifierMask::SHIFT | Key::F);
```
Comment (arkology) [inline editor/editor_node.cpp:7870]:
```suggestion
	ED_SHORTCUT_AND_COMMAND("editor/find_in_files", TTRC("Find in Files"), KeyModifierMask::CMD_OR_CTRL | KeyModifierMask::SHIFT | Key::F);
```
To keep it the same as in script editor.

Comment (arkology) [reply editor/editor_node.cpp]: @Frozenfire92 I tested it again and looks like suggested change is completely useless... Sorry about that. But even with this change everything still works fine.

**Review by arkology — APPROVED** [review]
Tested again and it looks good to me.
I think now you could squash commits into single one.
But my approval means nothing (as you see my mark is gray), you need to get a review from (most likely) @Calinou or @KoBeWi.

File: editor/editor_node.cpp (hunk 2 above)
Comment (Frozenfire92) [reply editor/editor_node.cpp]: @arkology it worked for me 🤔 

image

image

Comment (Frozenfire92) [reply editor/editor_node.cpp]: Ah ok, my misunderstanding 😅

File: editor/plugins/script_editor_plugin.cpp [hunk 3]
```diff
@@ -4457,7 +4457,7 @@ ScriptEditor::ScriptEditor(WindowWrapper *p_wrapper) {
 	add_child(help_search_dialog);
 	help_search_dialog->connect("go_to_help", callable_mp(this, &ScriptEditor::_help_class_goto));
 
-	find_in_files_dialog = memnew(FindInFilesDialog);
+	find_in_files_dialog = FindInFilesDialog::get_singleton();
```
Comment (kitbdev) [inline editor/plugins/script_editor_plugin.cpp:4460]: Find in Files is still dependent on ScriptEditor to set it up first, so it shouldn't be a Singleton by itself.
We should either move Find in Files to its own plugin somehow, or `_on_find_in_files_requested` can just be made public, and the EditorNode can call it on the ScriptEditor singleton.

Comment (Frozenfire92) [reply editor/plugins/script_editor_plugin.cpp:4460]: To confirm my understanding your latter suggestion is saying that anywhere else that accesses the FindInFilesDialog (currently only EditorNode), should do it through the ScriptEditor singleton because `_on_find_in_files_requested` becomes public, and this would make it so FindInFilesDialog doesn't need to be a singleton anymore.

I'm not too clear on the suggestion of its own plugin, so the above suggestion seems clear to me. Happy to have some guidance/discuss further

Comment (kitbdev) [reply editor/plugins/script_editor_plugin.cpp:4460]: Actually, I meant that the EditorNode should call `ScriptEditor::get_singleton()->on_find_in_files_requested` and FindInFilesDialog is not made a Singleton.
The alternative of making FindInFiles a separate plugin would require separating it from the ScriptEditor as much as possible, and it would take more effort. But for this PR it's probably best to just make `_on_find_in_files_requested` public.

Comment (Frozenfire92) [reply editor/plugins/script_editor_plugin.cpp:4460]: thanks for the clarification, I misunderstood and changed my original post, will make an update now

File: editor/editor_node.cpp (hunk 2 above)
Comment (Frozenfire92) [reply editor/editor_node.cpp:7866]: I ended up going back to as it was to keep things consistent between locations

File: editor/editor_node.cpp [hunk 4]
```diff
@@ -106,6 +106,7 @@
 #include "editor/export/project_zip_packer.h"
 #include "editor/fbx_importer_manager.h"
 #include "editor/filesystem_dock.h"
+#include "editor/find_in_files.h"
```
Comment (KoBeWi) [inline editor/editor_node.cpp:109]: Does this need to be included? You don't use the dialog anywhere.

**Review by KoBeWi — APPROVED** [review]

File: editor/editor_node.cpp (hunk 4 above)
Comment (Frozenfire92) [reply editor/editor_node.cpp:109]: Good catch, must have missed this when changing to going through Script editor singleton, can fix this tonight

**Review by Calinou — COMMENTED** [review]
Tested locally, it works as expected. This is a great usability improvement :slightly_smiling_face: 

However, this means Find in Files is now defined 3 times in the Editor Settings:

image

We should harmonize the setting names to make all of them use `editor/find_in_files`. This way, we avoid duplicating the shortcut.

**Comment by arkology** [comment]
> Tested locally, it works as expected. This is a great usability improvement 🙂
> 
> However, this means Find in Files is now defined 3 times in the Editor Settings:
> 
> image
> 
> We should harmonize the setting names to make all of them use `editor/find_in_files`. This way, we avoid duplicating the shortcut.

Oh, this is where I saw "Find In Files" without "..." 😄

**Comment by Repiteo** [comment]
Thanks!

**Review by Calinou — COMMENTED** [review]
Works great now :slightly_smiling_face: I can confirm the duplicate shortcuts are gone, and changing it while the editor is open will update all usages consistently:

However, the **Replace in Files** shortcut is still duplicated:

image

**Comment by Frozenfire92** [comment]
@Calinou good call, made a PR https://github.com/godotengine/godot/pull/106854
