### PR TITLE
Core: Add `Callable.create` static method for `Variant` callables

### LINKED ISSUE #87122: No warning when getting built in Callable from Dictionary
### Tested versions

4.3.dev [b04263644c3307b8b4a20838cd48f3c19692f1d2]

### System information

Godot v4.2.stable - Windows 10.0.22621 - GLES3 (Compatibility) - Intel(R) Iris(R) Xe Graphics (Intel Corporation; 31.0.101.4255) - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

A GDScript feature was recently added (https://github.com/godotengine/godot/pull/82264) that allows methods of built-in Variant types to be accessed as Callables. For example the feature makes the following code work.

```gdscript
var vec: Vector2 = Vector2(1.5, 2.5)
var callable: Callable = vec.ceil
print(callable.call()) # prints (2, 3)
```

This is a great feature, except there are cases where it could lead to potential confusion.

```gdscript
var dict: Dictionary = {&"clear" : randf}
var callable: Callable = dict.clear # does this refer to randf or the built in clear method?
callable.call()
print(dict) # does this print a blank dictionary or the original dictionary?
```

There is also potnential for confusion when using type annotations. In the following code
```gdscript
var dict: Dictionary = {&"clear" : "oops"}
var callable: Callable = dict.clear
```
the analyzer does not complain, but at runtime, I get "INTERNAL ERROR: Trying to assign value of type 'String' to a variable of type 'Callable'."

I'm not entirely sure what the best solution is, but as the title suggests, it might make sense to emit some kind of GDScript warning when the user creates or accesses a key that has the same name as a built in method.

### Steps to reproduce

Run the script above.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by dalexeev**
* Resolves #87122.
* See also #82264.
* Unfortunately, the `Callable(Variant, StringName)` constructor is quite difficult to implement due to binding limitations.

### CODE REVIEW

File: core/variant/callable.cpp [hunk 1]
```diff
@@ -31,6 +31,8 @@
 #include "callable.h"
 
 #include "callable_bind.h"
+#include "variant_callable.h"
+
```
Comment (akien-mga) [inline core/variant/callable.cpp:35]: Unless the order of includes matters here, I would make those two "absolute" (`core/variant/...`) and thus move them at the end after the `core/object` includes.

File: core/variant/callable.cpp [hunk 2]
```diff
@@ -327,12 +329,26 @@ Callable::operator String() const {
 	}
 }
 
+Callable Callable::create(const Variant &p_variant, const StringName &p_method) {
+	if (unlikely(p_method == StringName())) {
+		ERR_FAIL_V_MSG(Callable(), "Method argument to Callable::create method must be a non-empty string");
+	}
```
Comment (AThousandShips) [inline core/variant/callable.cpp:335]:
```suggestion
	ERR_FAIL_COND_V_MSG(p_method == StringName(), Callable(), "Method argument to Callable::create method must be a non-empty string.");
```

File: core/variant/callable.cpp [hunk 3]
```diff
@@ -327,12 +329,26 @@ Callable::operator String() const {
...
+
+	switch (p_variant.get_type()) {
+		case Variant::NIL:
```
Comment (AThousandShips) [inline core/variant/callable.cpp:338]:
```suggestion
		case Variant::NIL:
			return Callable(ObjectID(), p_method);
```
No need to go through the operator if we know what we have

File: doc/classes/Callable.xml [hunk 4]
```diff
@@ -160,7 +188,11 @@
 		<method name="is_custom" qualifiers="const">
 			<return type="bool" />
 			<description>
-				Returns [code]true[/code] if this [Callable] is a custom callable. Custom callables are created from [method bind] or [method unbind]. In GDScript, lambda functions are also custom callables.
+				Returns [code]true[/code] if this [Callable] is a custom callable. Custom callables are used:
+				- for binding/unbinding arguments (see [method bind] and [method unbind]);
+				- for representing methods of built-in [Variant] types (see [method create]);
+				- for representing lambda functions in GDScript;
+				- and other.
```
Comment (Mickeon) [inline doc/classes/Callable.xml:195]: "And other" strikes me a little odd. What could "other" possibly entail? What's the engine hiding from us?

File: doc/classes/Callable.xml [hunk 5]
```diff
@@ -160,7 +188,11 @@
 		<method name="is_custom" qualifiers="const">
 			<return type="bool" />
 			<description>
-				Returns [code]true[/code] if this [Callable] is a custom callable. Custom callables are created from [method bind] or [method unbind]. In GDScript, lambda functions are also custom callables.
+				Returns [code]true[/code] if this [Callable] is a custom callable. Custom callables are used:
```
Comment (Mickeon) [inline doc/classes/Callable.xml:191]: I may be better to reword the list to describe how custom Callables are created, how to create and obtain them, rather than list what they're used for.

I have no suggestions at the moment.

**Review by adamscott — APPROVED** [review]
Great way to fix https://github.com/godotengine/godot/issues/87122!

File: doc/classes/Callable.xml [hunk 6]
```diff
@@ -120,6 +139,15 @@
 				Calls the method represented by this [Callable]. Unlike [method call], this method expects all arguments to be contained inside the [param arguments] [Array].
 			</description>
 		</method>
+		<method name="create" qualifiers="static">
+			<return type="Callable" />
+			<param index="0" name="variant" type="Variant" />
+			<param index="1" name="method" type="StringName" />
+			<description>
+				Creates a new [Callable] for the method named [param method] in the specified [param variant]. To represent a method of a built-in [Variant] type, a custom callable is used (see [method is_custom]). If [param variant] is [Object], then a standard callable will be created instead.
+				[b]Note:[/b] In GDScript, you can use [code]instance.method[/code] syntax in most cases. The exception is [Dictionary], since dot syntax is used to access keys. Also, you can use this method when the instance type is not known in advance (for polymorphism).
```
Comment (Mickeon) [inline doc/classes/Callable.xml:148]: Perhaps? (If I understand the method right?)
```suggestion
				[b]Note:[/b] In GDScript, to get or create a [Callable] you can use the dot syntax ([code]instance.method[/code]). This method is always needed for the [Dictionary] type, as dot syntax is used to access its entries. You may also use this method when [param variant]'s type is not known in advance (for polymorphism).
```
or (but I'm not sure since it loses information).
```suggestion
				[b]Note:[/b] This method is always necessary for the [Dictionary] type, as dot syntax is used to access its entries. You may also use this method when [param variant]'s type is not known in advance (for polymorphism).
```

File: doc/classes/Callable.xml [hunk 7]
```diff
@@ -46,6 +46,24 @@
 		    # Prints "Attack!", when the button_pressed signal is emitted.
 		    button_pressed.connect(func(): print("Attack!"))
 		[/codeblock]
+		In GDScript, you can access methods and global functions as [Callable]s using property syntax.
```
Comment (Mickeon) [inline doc/classes/Callable.xml:49]: "Property syntax" or "dot syntax"? Which is it?

File: doc/classes/Callable.xml [hunk 8]
```diff
@@ -46,6 +46,24 @@
...
+		[codeblock]
+		func _init():
+		    create_tween().tween_callback(node.queue_free)  # Object methods.
+		    create_tween().tween_callback(array.clear)  # Methods of built-in types.
+		    create_tween().tween_callback(print.bind("Test"))  # Global functions.
+		[/codeblock]
+		[b]Note:[/b] [Dictionary] doesn't support above due to ambiguity with keys.
```
Comment (Mickeon) [inline doc/classes/Callable.xml:56]:
```suggestion
		[b]Note:[/b] [Dictionary] does not support the above due to ambiguity with keys.
```

File: doc/classes/Callable.xml [hunk 9]
```diff
@@ -46,6 +46,24 @@
...
+		[codeblock]
+		func _init():
+		    var dictionary = {"hello": "world"}
```
Comment (Mickeon) [inline doc/classes/Callable.xml:59]:
```suggestion
		    var dictionary = { "hello": "world" }
```

File: doc/classes/Callable.xml (hunk 7 above)
Comment (dalexeev) [reply doc/classes/Callable.xml:49]: There is a terrible secret, this works too:

```gdscript
node["queue_free"]
array["clear"]
```

That's why I called it "property syntax" here. Below I mentioned "dot syntax" in the context of `Dictionary` because we had the idea of allowing `dict.clear` as `Callable`, but leaving `dict["clear"]` as a key (but this is confusing and would break compatibility).

File: doc/classes/Callable.xml (hunk 9 above)
Comment (dalexeev) [reply doc/classes/Callable.xml:59]: I think this is not a recommended style, actually.

File: doc/classes/Callable.xml (hunk 4 above)
Comment (dalexeev) [reply doc/classes/Callable.xml:195]:
```
16 matches
core/extension/gdextension_interface.cpp: 1
 47: 31: class CallableCustomExtension : public CallableCustom {
core/object/callable_method_pointer.h: 6
 40: 39: class CallableCustomMethodPointerBase : public CallableCustom {
 81: 35: class CallableCustomMethodPointer : public CallableCustomMethodPointerBase {
127: 38: class CallableCustomMethodPointerRet : public CallableCustomMethodPointerBase {
174: 39: class CallableCustomMethodPointerRetC : public CallableCustomMethodPointerBase {
227: 41: class CallableCustomStaticMethodPointer : public CallableCustomMethodPointerBase {
268: 44: class CallableCustomStaticMethodPointerRet : public CallableCustomMethodPointerBase {
core/variant/callable_bind.h: 2
 37: 26: class CallableCustomBind : public CallableCustom {
 65: 28: class CallableCustomUnbind : public CallableCustom {
core/variant/variant_callable.h: 1
 37: 23: class VariantCallable : public CallableCustom {
modules/gdscript/gdscript_lambda_callable.h: 2
 44: 30: class GDScriptLambdaCallable : public CallableCustom {
 71: 34: class GDScriptLambdaSelfCallable : public CallableCustom {
modules/gdscript/gdscript_rpc_callable.h: 1
 39: 27: class GDScriptRPCCallable : public CallableCustom {
modules/gdscript/gdscript_utility_callable.h: 1
 38: 31: class GDScriptUtilityCallable : public CallableCustom {
modules/mono/managed_callable.h: 1
 40: 23: class ManagedCallable : public CallableCustom {
modules/mono/signal_awaiter_utils.h: 1
 41: 26: class BaseSignalCallable : public CallableCustom {
```

File: doc/classes/Callable.xml (hunk 9 above)
Comment (Mickeon) [reply doc/classes/Callable.xml:59]: Ah, hm. It is not actually specified in the style guide at all.

File: doc/classes/Callable.xml (hunk 4 above)
Comment (Mickeon) [reply doc/classes/Callable.xml:195]: One could then say custom Callables may be generated and used internally, perhaps?

File: doc/classes/Callable.xml (hunk 7 above)
Comment (Mickeon) [reply doc/classes/Callable.xml:49]: Yeah, I was aware of this. In that case, if this is what it refers to, you could maybe say "[...]as [Callable] as if they were properties"?

File: doc/classes/Callable.xml (hunk 9 above)
Comment (dalexeev) [reply doc/classes/Callable.xml:59]: Yes, but it's presented [here](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html):

File: core/variant/callable.cpp [hunk 10]
```diff
@@ -327,34 +328,47 @@ Callable::operator String() const {
 	}
 }
 
+Callable Callable::create(const Variant &p_variant, const StringName &p_method) {
+	ERR_FAIL_COND_V_MSG(p_method == StringName(), Callable(), "Method argument to Callable::create method must be a non-empty string.");
```
Comment (nlupugla) [inline core/variant/callable.cpp:332]: maybe change `p_method == StringName()` to `p_method.is_empty()` for a better looking error message?

File: core/variant/callable.cpp [hunk 11]
```diff
@@ -327,34 +328,47 @@ Callable::operator String() const {
...
+
+	switch (p_variant.get_type()) {
+		case Variant::NIL:
+			return Callable(ObjectID(), p_method);
+		case Variant::OBJECT:
+			return Callable(p_variant.operator ObjectID(), p_method);
+		default:
+			return Callable(memnew(VariantCallable(p_variant, p_method)));
+	}
+}
```
Comment (nlupugla) [inline core/variant/callable.cpp:342]: It'd be nice to have some unit tests (either in core, GDScript, or both) verifying that all these cases work as intended.

File: core/variant/callable.cpp [hunk 12]
```diff
@@ -327,34 +328,47 @@ Callable::operator String() const {
...
+
 Callable::Callable(const Object *p_object, const StringName &p_method) {
-	if (p_method == StringName()) {
+	if (unlikely(p_method == StringName())) {
```
Comment (nlupugla) [inline core/variant/callable.cpp:345]: Same comment as above about p_method.is_empty(), although it's maybe less relevant here since this line won't get printed in an error message.

File: core/variant/callable.cpp [hunk 13]
```diff
@@ -327,34 +328,47 @@ Callable::operator String() const {
...
 		object = 0;
-		ERR_FAIL_MSG("Method argument to Callable constructor must be a non-empty string");
+		ERR_FAIL_MSG("Method argument to Callable constructor must be a non-empty string.");
 	}
-	if (p_object == nullptr) {
+	if (unlikely(p_object == nullptr)) {
```
Comment (nlupugla) [inline core/variant/callable.cpp:349]: I seem to remember seeing `!p_object` more often over `p_object == nullptr`, but it probably doesn't matter much.

File: core/variant/callable.cpp (hunk 10 above)
Comment (dalexeev) [reply core/variant/callable.cpp:332]: The method does not exist in the `StringName` class.

File: core/variant/callable.h [hunk 14]
```diff
@@ -125,6 +125,8 @@ class Callable {
 
 	operator String() const;
 
+	static Callable create(const Variant &p_variant, const StringName &p_method);
```
Comment (nlupugla) [inline core/variant/callable.h:128]: Question about naming: why `create` as opposed to some of the other "creation" verbs used in other places like `new` or `init`?

File: core/variant/callable.cpp (hunk 10 above)
Comment (nlupugla) [reply core/variant/callable.cpp:332]: Wat?

What about this entry? https://docs.godotengine.org/en/stable/classes/class_stringname.html#class-stringname-method-is-empty

File: core/variant/callable.h (hunk 14 above)
Comment (dalexeev) [reply core/variant/callable.h:128]: I was thinking between `create()` and `from_variant()`. I think `new()` and `instantiate()` are bad options because of the confusion with `Object.new()` and `PackedScene.instantiate()`.

<details>
<summary>35 matches</summary>

```
35 matches for <method name="(create|new|instantiate|init|from|make)\w*" qualifiers="static">
doc/classes/Basis.xml: 2
 74:  3: 		<method name="from_euler" qualifiers="static">
100:  3: 		<method name="from_scale" qualifiers="static">
doc/classes/Color.xml: 4
144:  3: 		<method name="from_hsv" qualifiers="static">
162:  3: 		<method name="from_ok_hsl" qualifiers="static">
180:  3: 		<method name="from_rgbe9995" qualifiers="static">
187:  3: 		<method name="from_string" qualifiers="static">
doc/classes/DirAccess.xml: 2
237:  3: 		<method name="make_dir_absolute" qualifiers="static">
252:  3: 		<method name="make_dir_recursive_absolute" qualifiers="static">
doc/classes/Image.xml: 2
121:  3: 		<method name="create" qualifiers="static">
131:  3: 		<method name="create_from_data" qualifiers="static">
doc/classes/ImageTexture.xml: 1
 32:  3: 		<method name="create_from_image" qualifiers="static">
doc/classes/MultiplayerAPI.xml: 1
 15:  3: 		<method name="create_default_interface" qualifiers="static">
doc/classes/PhysicsRayQueryParameters2D.xml: 1
 12:  3: 		<method name="create" qualifiers="static">
doc/classes/PhysicsRayQueryParameters3D.xml: 1
 12:  3: 		<method name="create" qualifiers="static">
doc/classes/Projection.xml: 10
 46:  3: 		<method name="create_depth_correction" qualifiers="static">
 53:  3: 		<method name="create_fit_aabb" qualifiers="static">
 60:  3: 		<method name="create_for_hmd" qualifiers="static">
 75:  3: 		<method name="create_frustum" qualifiers="static">
 87:  3: 		<method name="create_frustum_aspect" qualifiers="static">
100:  3: 		<method name="create_light_atlas_rect" qualifiers="static">
107:  3: 		<method name="create_orthogonal" qualifiers="static">
119:  3: 		<method name="create_orthogonal_aspect" qualifiers="static">
131:  3: 		<method name="create_perspective" qualifiers="static">
143:  3: 		<method name="create_perspective_hmd" qualifiers="static">
doc/classes/Quaternion.xml: 1
 93:  3: 		<method name="from_euler" qualifiers="static">
doc/classes/Vector2.xml: 1
201:  3: 		<method name="from_angle" qualifiers="static">
modules/gltf/doc_classes/GLTFCamera.xml: 2
 15:  3: 		<method name="from_dictionary" qualifiers="static">
 22:  3: 		<method name="from_node" qualifiers="static">
modules/gltf/doc_classes/GLTFLight.xml: 2
 14:  3: 		<method name="from_dictionary" qualifiers="static">
 21:  3: 		<method name="from_node" qualifiers="static">
modules/gltf/doc_classes/GLTFPhysicsBody.xml: 2
 14:  3: 		<method name="from_dictionary" qualifiers="static">
 21:  3: 		<method name="from_node" qualifiers="static">
modules/gltf/doc_classes/GLTFPhysicsShape.xml: 2
 15:  3: 		<method name="from_dictionary" qualifiers="static">
 22:  3: 		<method name="from_node" qualifiers="static">
modules/regex/doc_classes/RegEx.xml: 1
 65:  3: 		<method name="create_from_string" qualifiers="static">
```

</details>

File: core/variant/callable.cpp (hunk 10 above)
Comment (dalexeev) [reply core/variant/callable.cpp:332]: This is GDScript only. See [source code](https://github.com/godotengine/godot/blob/master/core/string/string_name.h) instead.

File: core/variant/callable.h (hunk 14 above)
Comment (Mickeon) [reply core/variant/callable.h:128]: I think `create` is fine. It doesn't overlap with anything that could potentially be added for Callable. Combined with the parameters it can be thought as "create a Callable for this variant's method with the given name).

Granted, it's a bit misleading because for Objects it doesn't really create them, per say, but you know.

Actually the second parameter could be called `method_name`. There's a lot of misleading Callable parameter names and I wouldn't want this to be one of them, too.

Comment (nlupugla) [reply core/variant/callable.h:128]: If anything, I'd say `from_string_name` would be more appropriate than `from_variant`, but in any case, I think you've made a convincing argument that `create` is a good choice after all.

Comment (dalexeev) [reply core/variant/callable.h:128]: > Granted, it's a bit misleading because for Objects it doesn't really create them, per say, but you know

This method actually creates a `Callable` as a value _representing_ method/function. Yes, we have differences between standard and custom callables (the latter can hold a reference), but I think that this has nothing to do with the creation of the callable itself.

> Actually the second parameter could be called `method_name`.

I'd prefer to keep the parameter names consistent with the constructor.

File: core/variant/callable.cpp (hunk 13 above)
Comment (dalexeev) [reply core/variant/callable.cpp:349]: I see both options in the codebase and don't have a strict preference. I try to use an option depending on the context and not change it in the existing code. I think this is a case where consistency does more harm than good.

File: doc/classes/Callable.xml (hunk 7 above)
Comment (dalexeev) [reply doc/classes/Callable.xml:49]: I just removed this part, since global functions are not properties.

File: core/variant/callable.cpp (hunk 11 above)
Comment (dalexeev) [reply core/variant/callable.cpp:342]: I added a GDScript test, but skipped the core for now since there is no `tests/core/variant/callable.h` file.

**Comment by akien-mga** [comment]
Thanks!
