### PR TITLE
Fix parse error using Vector{2,3,4}.INF

### LINKED ISSUE #45139: GDScript 2.0: Using Vector2.INF or Vector3.INF causes parse error
**Godot version:** latest master, custom build based on commit:8e514bbf6ab3d2cff4daeb64e842bd8846c07046
platform = "linuxbsd"
bits = 64
target = "release_debug"
tools = "yes"
module_mono_enabled = "no"

**OS/device including version:** Gentoo linux

**Issue description:**
using Vector3.INF causes parse errors in editor:
```
 Parser bug (please report): Trying to check compatibility of unset value type
- Parse Error: Expected identifier after "." for attribute access.
modules/gdscript/gdscript.cpp:816 - Method/function failed. Returning: ERR_PARSE_ERROR
```
**reproduction:**
in any gdscript that extends Node try using Vector3.INF constant.

### PR DESCRIPTION
**Pull request by adamscott**
Fixes #45139

Yes, technically, it would be now possible to run this code, without warning, but it's already the case with `match`.

```gdscript
extends Node

func _ready() -> void:
    var INF: = 42
    print(INF)  # prints `inf`
```

### CODE REVIEW

**Comment by MewPurPur** [comment]
And `Vector4.INF`?

**Comment by akien-mga** [comment]
That seems a bit hacky, and the shadowing bug it introduces doesn't seem like a good tradeoff.

AFAIK it worked in 3.x, so there should be a way to fix this properly, parsing the scoped one as a member/constant and not as a token.

**Comment by adamscott** [comment]
> And `Vector4.INF`?

Forgot about it, I'll add it to the tests. It should work flawlessly.

**Comment by adamscott** [comment]
> That seems a bit hacky, and the shadowing bug it introduces doesn't seem like a good tradeoff.

I don't introduce a shadowing bug _per se_. The behavior already exists for `match`.

```gdscript
extends Node

func _ready() -> void:
    var match: = 123
    print(match)  # Editor will complain `Expected expression as the function argument.`
```

I suggest to merge this PR first, than log an issue about `match` and `INF` shadowing issue. The issue lies with the fact that the parser automatically tags `match` and `INF` (and other reserved tags) as reserved, without considering the context, like if the token is an attribute or if it's used standalone.

File: modules/gdscript/gdscript_tokenizer.cpp [hunk 1]
```diff
@@ -164,6 +164,7 @@ bool GDScriptTokenizer::Token::is_identifier() const {
 	switch (type) {
 		case IDENTIFIER:
 		case MATCH: // Used in String.match().
+		case CONST_INF: // Used in Vector2.INF and Vector3.INF
```
Comment (Maran23) [inline modules/gdscript/gdscript_tokenizer.cpp:167]: The comment should also include `Vector4.INF`

**Comment by Maran23** [comment]
> without considering the context, like if the token is an attribute or if it's used standalone.

Do you know if this actually possible to implement one day?

File: modules/gdscript/gdscript_tokenizer.cpp (hunk 1 above)
Comment (adamscott) [reply modules/gdscript/gdscript_tokenizer.cpp]: Fixed it! Thanks!

**Comment by adamscott** [comment]
> > without considering the context, like if the token is an attribute or if it's used standalone.
> 
> Do you know if this actually possible to implement one day?

I'm no tokenizer expert, so I don't really no. Maybe, surely in fact!

**Comment by adamscott** [comment]
CC @anvilfolk @vonagam @vnen 

I'm summoning you to have your input about the hackiness/good enough value of my fix.

**Comment by vonagam** [comment]
My input: I don't see much reason why INF/NAN/PI/TAU should be treated differently by parser/tokenizer compared to other constants. Analyzer with `reduce_identifier_from_base` (to get value),  `check_native_member_name_conflict` (to protect from naming members) and `is_shadowing` (to protect from naming local things) can do just fine (need a static hashmap<StringName, Variant> with simple additions to those functions).

**Comment by vnen** [comment]
The constants could be considered regular identifiers. In fact, the tokenizer doesn't really need to care about those especially, they could be resolved later by the parser.

Regarding `match` (and potentially other keywords), we can change the system to allow keywords as attributes (e.g. `x.match`) but not directly as identifiers, especially in locals that can never be accessed via attribute syntax.

For now I think it's good merge this to fix the immediate issue.

**Review by vnen — APPROVED** [review]

**Comment by Maran23** [comment]
Thanks!
