### PR TITLE
[Linux/BSD] Offload RenderingDevice creation test to subprocess.

### LINKED ISSUE #103518: Editor: Crash when launching on Linux due to #91172 (instantiating RenderingDevice context in OpenGL project manager context)
### Tested versions

- Reproducible on 4.4
- Not reproducible on 4.3, 4.2

### System information

Linux 6.9.3-76060903-generic #202405300957\~1738770968~22.04\~d5f7c84 SMP PREEMPT_DYNAMIC Wed F x86_64 x86_64 x86_64 GNU/Linux - Godot v4.4-stable - Pop!_OS 22.04 LTS

### Issue description

Attempting to launch Godot 4.4 immediately crashes with the following logs:

```plaintext
Godot Engine v4.4.stable.official.4c311cbee - https://godotengine.org
OpenGL API 4.6 (Core Profile) Mesa 23.1.0-devel - Compatibility - Using Device: AMD - AMD Radeon Graphics (gfx1100, LLVM 15.0.7, DRM 3.57, 6.9.3-76060903-generic)

: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
[1]    273820 IOT instruction (core dumped)  ~/apps/Godot_v4.4-stable_linux.x86_64
```

### Steps to reproduce

1. Extract and run `./Godot_v4.4-stable_linux.x86_64`.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Same as https://github.com/godotengine/godot/pull/103245, but for Linux.

Fixes https://github.com/godotengine/godot/issues/103518

As with Windows, since I can't reproduce the crash, I can't fully test if it's detecting crashing context correctly.

### CODE REVIEW

**Comment by EpicEric** [comment]
Confirming that this fixes the project manager crashes on my end.

File: core/os/os.h [hunk 1]
```diff
@@ -363,8 +363,8 @@ class OS {
 	virtual void load_platform_gdextensions() const {}
 
 	// Windows only. Tests OpenGL context and Rendering Device simultaneous creation. This function is expected to crash on some NVIDIA drivers.
```
Comment (akien-mga) [inline core/os/os.h:365]: Not anymore Windows only.

**Review by akien-mga — APPROVED** [review]
Tested briefly on Fedora 41 with
```
OpenGL API 4.6 (Core Profile) Mesa 25.0.0 - Compatibility - Using Device: AMD - AMD Radeon Graphics (radeonsi, phoenix, LLVM 19.1.7, DRM 3.61, 6.13.5-200.fc41.x86_64)
```

I couldn't reproduce the bug but this doesn't seem to cause issues either. I can create Forward+ projects in the project manager.

**Comment by HeavyBro1337** [comment]
I downloaded Godot 4.4 mono, it doesn't crash on the project manager. However, I haven't tried to open any of my projects. But I assume it works fine.

**Comment by Repiteo** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.4.1.
