### PR TITLE
Inheriting from virtual class no longer causes the engine to crash.

### LINKED ISSUE #25596: Crash when using `new` on a virtual class
**Godot version:**
Reproduced on Godot 3.1 beta 3 and git master 919fa75803177d0dc8f03c16b6be1360140145e1

**OS/device including version:**
Platforms tested:
* Ubuntu Linux 18.10
  - `uname -a`: `Linux <hostname> 4.18.0-13-generic #14-Ubuntu SMP Wed Dec 5 09:04:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
  - OpenGL version `4.6.0 NVIDIA 390.87`
* Windows 10

Hardware (same for both platforms):
* AMD Ryzen Threadripper 1950X 16-Core Processor
* nVidia GeForce GTX 1080 Ti/PCIe/SSE2

**Issue description:**
When instantiating a new custom script that extends `InputEvent`, Godot crashes.

**Steps to reproduce:**
1. Create a script that extends `InputEvent`.
2. `preload` it from another file.
3. Call `.new()` on the `preload` variable.

**Minimal reproduction project:**
https://github.com/zlsa/godot-custom-input-event-crash

### PR DESCRIPTION
**Pull request by QbieShay**
It prints an error instead.

Fixes #25596

### CODE REVIEW

File: modules/gdscript/gdscript.cpp [hunk 1]
```diff
@@ -152,12 +152,21 @@ Variant GDScript::_new(const Variant **p_args, int p_argcount, Variant::CallErro
 	}
 
 	ERR_FAIL_COND_V(_baseptr->native.is_null(), Variant());
+    bool owner_valid = false; //owner can be invalidated in two ways: no base class or virtual base class
```
Comment (akien-mga) [inline modules/gdscript/gdscript.cpp]: Wrong indentation, see [Code style guidelines](http://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html).

**Review by bojidar-bg — COMMENTED** [review]
Looks good overall, but can be simplified a bit.
Change `if (!owner_valid)` to `if (!owner)`; if not already, initialize `owner` to NULL.
Also, using `ERR_FAIL_COND_V`, like on line 154, might do for the error prints.

File: modules/gdscript/gdscript.cpp (hunk 1 above)
Comment (QbieShay) [reply modules/gdscript/gdscript.cpp]: I just installed the pre-commit hooks

File: modules/gdscript/gdscript.cpp [hunk 2]
```diff
@@ -152,12 +152,13 @@ Variant GDScript::_new(const Variant **p_args, int p_argcount, Variant::CallErro
...
-
-	if (_baseptr->native.ptr()) {
+	if (_baseptr->native->instance()) {
 		owner = _baseptr->native->instance();
 	} else {
-		owner = memnew(Reference); //by default, no base means use reference
+		owner = memnew(Reference);
 	}
+	ERR_EXPLAIN("Can't inherit from a virtual class");
+	ERR_FAIL_COND_V(!owner, Variant());
```
Comment (akien-mga) [inline modules/gdscript/gdscript.cpp]: Can this condition be true at all?
If `_baseptr->native->instance()` is `NULL`, then `owner` is `memnew(Reference)`, which shouldn't give `NULL`.
If `_baseptr->native->instance()` is not `NULL`, then `owner` is `_baseptr->native->instance()`.

Comment (QbieShay) [reply modules/gdscript/gdscript.cpp]: Ah yes, I put the wrong condition in the if. Will correct tomorrow-ish

**Review by bojidar-bg — APPROVED** [review]
LGTM, I guess.

File: modules/gdscript/gdscript.cpp [hunk 3]
```diff
@@ -152,12 +152,13 @@ Variant GDScript::_new(const Variant **p_args, int p_argcount, Variant::CallErro
 	}
 
 	ERR_FAIL_COND_V(_baseptr->native.is_null(), Variant());
-
 	if (_baseptr->native.ptr()) {
 		owner = _baseptr->native->instance();
 	} else {
-		owner = memnew(Reference); //by default, no base means use reference
```
Comment (vnen) [inline modules/gdscript/gdscript.cpp]: Any particular reason to remove this comment?

Comment (akien-mga) [reply modules/gdscript/gdscript.cpp]: Bump.

**Comment by akien-mga** [comment]
Thanks!
