### PR TITLE
Ensure that environment is available before checking for BCS

### LINKED ISSUE #91239: `ERROR: Parameter "env" is null.` with Compatibility renderer
### Tested versions

v4.3.dev.custom_build [6118592c6]

### System information

Godot v4.3.dev (6118592c6) - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.5222) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Repeated errors:

```
ERROR: Parameter "env" is null.
   at: RendererEnvironmentStorage::environment_get_adjustments_enabled (servers\rendering\storage\environment_storage.cpp:787)
ERROR: Parameter "env" is null.
   at: RendererEnvironmentStorage::environment_get_color_correction (servers\rendering\storage\environment_storage.cpp:817)
```

### Steps to reproduce

Run [Godot Demo Pause project](https://github.com/godotengine/godot-demo-projects/tree/master/misc/pause) and start it.

### Minimal reproduction project (MRP)

Use the [Godot Demo Pause Project](https://github.com/godotengine/godot-demo-projects/tree/master/misc/pause)

```
git bisect bad
e8bb0a5719ca78a0b10ab980c4c5c06b5bdf7dbb is the first bad commit
commit e8bb0a5719ca78a0b10ab980c4c5c06b5bdf7dbb
Author: clayjohn
Date:   Thu Apr 25 12:24:51 2024 -0700

    Add adjustments and color correction to Compatibility renderer
```

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/91239

I wrongfully assumed that doing a post process meant we had the environment available. But we also use the post pass for resolving MSAA, so this code can be reached even if there is no environment in the scene. 

Simple fix is to check for the environment before enabling BCS.

### CODE REVIEW

File: drivers/gles3/rasterizer_scene_gles3.cpp [hunk 1]
```diff
@@ -2706,27 +2706,30 @@ void RasterizerSceneGLES3::_render_post_processing(const RenderDataGLES3 *p_rend
...
-		bool use_1d_lut = environment_get_use_1d_color_correction(p_render_data->environment);
-		GLenum texture_target = GL_TEXTURE_3D;
-		if (use_1d_lut) {
-			bcs_spec_constants |= PostShaderGLES3::USE_1D_LUT;
-			texture_target = GL_TEXTURE_2D;
-		}
+	if (p_render_data->environment.is_valid()) {
+		bool use_bcs = environment_get_adjustments_enabled(p_render_data->environment);
+		RID color_correction_texture = environment_get_color_correction(p_render_data->environment);
+		bcs_spec_constants |= use_bcs ? PostShaderGLES3::USE_BCS : 0;
```
Comment (RandomShaper) [inline drivers/gles3/rasterizer_scene_gles3.cpp:2713]: A bit more readable:
```suggestion
		if (use_bcs) {
			bcs_spec_constants |= PostShaderGLES3::USE_BCS;
		}
```

You could even nest `if (color_correction_texture.is_valid())` inside this one.

**Review by RandomShaper — APPROVED** [review]

File: drivers/gles3/rasterizer_scene_gles3.cpp (hunk 1 above)
Comment (clayjohn) [reply drivers/gles3/rasterizer_scene_gles3.cpp]: Done!

File: drivers/gles3/rasterizer_scene_gles3.cpp [hunk 2]
```diff
@@ -2706,27 +2706,32 @@ void RasterizerSceneGLES3::_render_post_processing(const RenderDataGLES3 *p_rend
...
-		bcs_spec_constants |= PostShaderGLES3::USE_BCS;
-		bcs_spec_constants |= PostShaderGLES3::USE_COLOR_CORRECTION;
-
-		bool use_1d_lut = environment_get_use_1d_color_correction(p_render_data->environment);
-		GLenum texture_target = GL_TEXTURE_3D;
-		if (use_1d_lut) {
-			bcs_spec_constants |= PostShaderGLES3::USE_1D_LUT;
-			texture_target = GL_TEXTURE_2D;
-		}
+	if (p_render_data->environment.is_valid()) {
```
Comment (fire) [inline drivers/gles3/rasterizer_scene_gles3.cpp:2710]: Code style nitpick, I try to reduce the deepness of parenthesis nesting via early return or techniques like that.

Comment (akien-mga) [reply drivers/gles3/rasterizer_scene_gles3.cpp:2710]: An early return doesn't seem to be an option here, so I think it's fine.

**Comment by akien-mga** [comment]
Thanks!
