### PR TITLE
Wrap angles to (-pi, pi) in momentum calculation.

### LINKED ISSUE #31940: Strange behaviour PinJoint2D + rotating Kinematic2D + RigidBody2D
**Godot version:**
3.2 (nightly)

**OS/device including version:**
Linux davidkbd-Vostro-3558 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)

**Issue description:**
I have a KinematicBody2D with a PinJoint2D linked to a Rigid Body.
When the Kinematic is rotated 180 degrees the RigidBody jumps.

**Steps to reproduce:**
Add a KinematicBody2D
Add a PinJoint2D inside the KinematicBody2D
Add a RigidBody2D outside of the KinematicBody
Link KinematicBody to node_a
Link RigidBody to node_b

Rotate KinematicBody2D, for example:
	$Kinematic.rotation += .001

Selección_012

 **Minimal reproduction project:**

Selección_011

### LINKED ISSUE #41527: Excess angular momentum when 2D kinematic body rotates beyond 180 degrees
**Godot version:**
3.2.2-stable, also latest master as of this writing (git commit 443686d724ce8ac58dcdf09389e9f996aee866c1).

**OS/device including version:**
All (tested on Ubuntu 20.04, Windows 10).

**Issue description:**
When a KinematicBody2D rotates beyond 180 degrees, any RigidBody in contact with it flies away.

This is because the 2D physics server calculates angular momentum using the difference between the previous update's angle and the current angle. When rotating beyond 180, the angle wraps around to -180, and the server calculates a difference of nearly 360 degrees between frame, resulting in a very high angular momentum. This is then propagated to colliding physics bodies.

See reddit thread: https://www.reddit.com/r/godot/comments/ifxtf5/is_this_something_that_should_be_fixed_for/

**Steps to reproduce:**
Have a KinematicBody2D rotating to nearly 180 degrees. Place a RigidBody on top. As soon as the KinematicBody2D passes 180 degrees of rotation, the RigidBody will fly away with large amounts of momentum.

**Minimal reproduction project:**
See https://github.com/Tobzster/KinematicBody2D_Angular_Velocity_Glitch from the author of the reddit thread.

### PR DESCRIPTION
**Pull request by keegano**
Fixes bug #41527 (Excess angular momentum when 2D kinematic body rotates beyond 180 degrees) by limiting the difference in angle between frames to the range (-pi, pi). 

This was the most minimal solution I could think of; it uses the standard library remainder function to produce the difference between the angle and the nearest integer multiple of 2pi. Another solution might be to add a method to the Transform2D class that gets an orientation vector, then use an angle-between-vectors method - this would avoid computing two angles then taking a modulus.

This change was actually tested on 3.2.2-stable; I assume the same change will work in 4.0, however I cannot get it to compile on my machine.

_Bugsquad edit:_ Fixes #31940, fixes #41527.

### CODE REVIEW

**Comment by keegano** [comment]
I see that it does not build on Windows (I assumed M_PI would be available there, too). Let me refactor into a platform-agnostic unwrap function.

**Review by madmiraal — APPROVED** [review]

**Review by madmiraal — CHANGES_REQUESTED** [review]
The change is good, but please squash the commits into one commit.

**Comment by keegano** [comment]
I have squashed the commits.

**Review by madmiraal — APPROVED** [review]

File: servers/physics_2d/body_2d_sw.cpp [hunk 1]
```diff
@@ -468,7 +468,7 @@ void Body2DSW::integrate_forces(real_t p_step) {
 		linear_velocity = motion / p_step;
 
 		real_t rot = new_transform.get_rotation() - get_transform().get_rotation();
-		angular_velocity = rot / p_step;
+		angular_velocity = remainder(rot, 2.0 * Math_PI) / p_step;
```
Comment (aaronfranke) [inline servers/physics_2d/body_2d_sw.cpp:471]: Why `2.0 * Math_PI` to wrap to `(-pi, pi)`? Also, prefer `Math_TAU` to `2.0 * Math_PI`.

Comment (keegano) [reply servers/physics_2d/body_2d_sw.cpp:471]: The remainder function takes the (signed) distance between the first parameter and the nearest integer multiple of the second value. By way of analogy, remainder is to rounding as the modulus is to truncation.

It may help to mentally step through all of the ranges for the angle. Between 0 and pi, the nearest integer multiple of 2*pi is 0, so the angle is unchanged. Between pi and 2*pi, the nearest integer multiple is 2pi, and the distance is `angle - 2*pi` (negative, because the angle is less than the nearest multiple), so the angle gets transformed to the range (-pi, 0), which is correct. Similarly, between -pi to 0, the nearest multiple is 0 and the angle is unchanged. Between -2pi and -pi, the nearest angle is -2pi and the distance is `2pi + angle`.

Comment (aaronfranke) [reply servers/physics_2d/body_2d_sw.cpp:471]: Oh, I see. This behavior is correct in this situation, however, the name of this standard library function is very confusing, because this is not the typical behavior that the word "remainder" describes. A comment would be nice:

```suggestion
		// The remainder is relative to the nearest multiple rather than the multiple closest to zero.
		angular_velocity = remainder(rot, Math_TAU) / p_step;
```

Comment (keegano) [reply servers/physics_2d/body_2d_sw.cpp:471]: Arguments over the naming of the remainder function notwithstanding, I think we don't need to make a habit of describing functions from the standard library wherever they are used.

Perhaps it would be better to define an inline unroll_angle function to make it clearer the intent of this line, and that way the implementation could also be change with something more performant later if someone decided to do that. 

I also prefer 2.0*Math_PI in this case, because it makes the relationship to the range (-pi, pi) more explicit. 

That said as of right now this is the only place I'm aware of where angle unrolling is needed, so I'd lean against adding complexity and optimization prematurely. This is a bugfix PR, another PR could be used to redesign (and if I were doing that, I'd change to a stable angle-between-vectors algorithm instead of subtracting angles).

Comment (aaronfranke) [reply servers/physics_2d/body_2d_sw.cpp:471]: We do have `fposmod`, which works for angles, but would give outputs on the range (0, TAU) if used with TAU or 2PI, so we would have to add a check with `> Math_PI` and then do `-= Math_TAU`.

Comment (akien-mga) [reply servers/physics_2d/body_2d_sw.cpp:471]: So is this good to merge as is, or should this be further documented/changed?

Comment (madmiraal) [reply servers/physics_2d/body_2d_sw.cpp:471]: I think it's good to merge as it is.

**Comment by jtaart** [comment]
Is there any reason this can't be merged into a 3.2/3.3 release?

**Comment by akien-mga** [comment]
No, and that's why it has the `cherrypick:3.2` label which means that it's queued for merging into `3.2`.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
