### PR TITLE
Hide private enums from documentation

### LINKED ISSUE #84119: GdScript documentation comments - enums always appear in the help window
### Godot version

v4.2.beta3.official [e8d57afae]

### System information

Godot v4.2.beta3 - Pop!_OS 20.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) UHD Graphics 630 (CFL GT2) () - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

An enum always appears in the help window, even if it is not preceded by documentation and its name starts with an underscore .

This is not consistent with the behavior of other items.

```
# The below function isn't documented and its name starts with an underscore
# so it will treated as private and will not be shown in the help window.
func _internal() -> void:
	pass
```
Reference for GdScript documentation comments:
https://docs.godotengine.org/en/4.1/tutorials/scripting/gdscript/gdscript_documentation_comments.html

### Steps to reproduce

Create a script `test.gd` with contents:
~~~
enum _A {B, C}
~~~

Press the F1 key or click the Search Help icon, and type the name of the file.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by quirkylemon**
This loops through all the enums and checks if it has a description (doc comment) or if it is public. it also renames the variable `e` to a more descriptive name 
fixes #84119

### CODE REVIEW

**Comment by quirkylemon** [comment]
I think it is working properly

**Comment by daveTheOldCoder** [comment]
I tested this PR, but it didn't completely fix the problem.

It fixes the simple example I posted here: https://github.com/godotengine/godot/issues/84119

But it does not fix this more complicated example:
https://github.com/daveTheOldCoder/Godot3To4FileConversion/blob/v1.0.2/addons/godot_3_to_4_file_conversion/file_access_godot3.gd
The private enum `_Godot3_Variant_Type` is still visible in the Help page.

I used this procedure to test the PR:

~/github/godot is the local folder with a cloned Godot repo.

$ cd ~/github/godot
$ git fetch origin pull/84396/head:84396_tmp_branch
$ git checkout 84396_tmp_branch

The file editor/editor_help.cpp now has the changes starting at line 1382.

$ scons platform=linuxbsd

$ bin/godot.linuxbsd.editor.x86_64 -e --path ~/GodotProjects4.2/Test_PR_84396

**Review by daveTheOldCoder — APPROVED** [review]
I tested this PR and it worked correctly.

**Review by Mickeon — APPROVED** [review]
Tested myself and works as intended.

File: editor/editor_help.cpp [hunk 1]
```diff
@@ -1401,27 +1419,19 @@ void EditorHelp::_update_doc() {
...
-					}
-
-					if (cd.enums[e].is_experimental) {
-						EXPERIMENTAL_DOC_TAG;
-					}
+				if (cd.enums[key].is_deprecated) {
+					DEPRECATED_DOC_TAG;
+				}
+				if (cd.enums[key].is_experimental) {
+					EXPERIMENTAL_DOC_TAG;
```
Comment (dalexeev) [inline editor/editor_help.cpp:1434]: As far as I understand, it is not guaranteed that `cd.enums` has `key`. Above:

```c++
if (cd.enums.has(key)) {
    if (cd.enums[key].description.strip_edges().is_empty() && E.key.begins_with("_")) {
        continue;
    }
}
```

File: editor/editor_help.cpp [hunk 2]
```diff
@@ -1379,7 +1379,16 @@ void EditorHelp::_update_doc() {
 		}
 
 		// Enums
+		bool has_enums = false;
 		if (enums.size()) {
+			for (KeyValue<String, DocData::EnumDoc> &E : cd.enums) {
+				if (!E.key.begins_with("_") || !E.value.description.strip_edges().is_empty()) {
+					has_enums = true;
+					break;
+				}
```
Comment (dalexeev) [inline editor/editor_help.cpp:1388]: It makes sense to check `is_script_doc`, like here:

https://github.com/godotengine/godot/blob/447030ec5efc44f8edf66f84065f9d45a344d3a8/editor/editor_help.cpp#L983-L986

File: editor/editor_help.cpp (hunk 1 above)
Comment (quirkylemon) [reply editor/editor_help.cpp:1434]: So we should still be checking if `cd.enums.has(key)` or should we skip any enum that doesn't have a key?

File: editor/editor_help.cpp (hunk 2 above)
Comment (quirkylemon) [reply editor/editor_help.cpp]: can you check the latest commit to see if it is correct?

File: editor/editor_help.cpp [hunk 3]
```diff
@@ -1389,8 +1399,17 @@ void EditorHelp::_update_doc() {
 			class_desc->add_newline();
 
 			for (KeyValue<String, Vector<DocData::ConstantDoc>> &E : enums) {
-				enum_line[E.key] = class_desc->get_paragraph_count() - 2;
+				String key = E.key;
+				if ((key.get_slice_count(".") > 1) && (key.get_slice(".", 0) == edited_class)) {
+					key = key.get_slice(".", 1);
+				}
+				if (cd.enums.has(key)) {
+					if (cd.enums[key].description.strip_edges().is_empty() && E.key.begins_with("_")) {
```
Comment (AThousandShips) [inline editor/editor_help.cpp:1407]: Above the enums are filtered on script docs, but not here, is that an oversight?
```suggestion
					if (cd.is_script_doc && cd.enums[key].description.strip_edges().is_empty() && E.key.begins_with("_")) {
```

File: editor/editor_help.cpp [hunk 4]
```diff
@@ -1379,7 +1379,17 @@ void EditorHelp::_update_doc() {
 		}
 
 		// Enums
+		bool has_enums = false;
 		if (enums.size()) {
+			for (KeyValue<String, DocData::EnumDoc> &E : cd.enums) {
+				if (cd.is_script_doc && cd.is_script_doc && E.key.begins_with("_") && E.value.description.strip_edges().is_empty()) {
```
Comment (AThousandShips) [inline editor/editor_help.cpp:1385]:
```suggestion
		bool has_enums = enums.size() && !cd.is_script_doc;
		if (enums.size() && !has_enums) {
			for (KeyValue<String, DocData::EnumDoc> &E : cd.enums) {
				if (E.key.begins_with("_") && E.value.description.strip_edges().is_empty()) {
```
No need to check these every time, the loop accepts enums if they're non-script doc ones, so we can skip this part

Might be a more elegant way to do this just a suggestion, but the loop is unnecessary if it's not a script doc

File: editor/editor_help.cpp (hunk 3 above)
Comment (quirkylemon) [reply editor/editor_help.cpp:1407]: correct me if I'm wrong but we shouldn't have to check cd.is_script_doc every time because it doesn't change per enum. 
the reason we are checking if the description is empty or if the name starts with "_" is it is possible for enums that don't need documentation generated to be in the for loop.

Comment (AThousandShips) [reply editor/editor_help.cpp:1407]: Then there should be some other flag to control this as the filtering is on script docs only,

File: editor/editor_help.cpp (hunk 4 above)
Comment (quirkylemon) [reply editor/editor_help.cpp:1385]: yeah you're right.

File: editor/editor_help.cpp (hunk 3 above)
Comment (quirkylemon) [reply editor/editor_help.cpp:1407]: oh I didn't realize we only filter on script docs.

**Review by AThousandShips — APPROVED** [review]
LGTM, would need to verify the comment about the enum key though, I'd suggest keeping it as it was to avoid any weirdness

**Comment by quirkylemon** [comment]
Should I go ahead and combine the commits?
Also what does "LGTM" mean?

**Comment by AThousandShips** [comment]
Looks Good To Me :)

Yes please squash

**Comment by quirkylemon** [comment]
whenever I do git rebase it says there are 1382 commits to push. this has happened before and it didn't mess anything up but it did send a message in every pr that was in it. Is there any way to fix it?

**Comment by AThousandShips** [comment]
It's just because you're updating your branch, the others should be just the normal ones, just that the branch doesn't contain them upstream

**Comment by quirkylemon** [comment]
Squashed!!
and sorry about all the issues.

**Comment by AThousandShips** [comment]
No problem at all! It's a learning experience :)

**Comment by akien-mga** [comment]
Apologies for yet another nitpick, but could you amend the commit message to be a bit more explicit (and ideally start with a capital letter like other commits)? The title of this PR would be a good option, for a changelog reader I think the "from documentation" part is important to get the context.

I can do it myself too if needed.

**Comment by quirkylemon** [comment]
Done

**Comment by akien-mga** [comment]
Thanks!
