### PR TITLE
Fix C# `get_all_delegates` method for generic classes

### LINKED ISSUE #47830: Can't use signal declared in abstract generic class
**Godot version:** 3.2.3.stable.mono

**OS/device including version:** Windows 19042.870, GTX1060 (Driver 461.09)

**Issue description:**

Working on a system I noticed I could give myself a nicer API by making the abstract base class generic over what entity or node it will be dealing with. There was one signal declared in the abstract base class which I was able to connect from concrete implementations of the base class before making the base class generic. With the generic type argument in use neither connecting nor emitting the signal works.

```
E 0:00:00.686   connect: In Object of type 'Node': Attempt to connect nonexistent signal 'MySignal' to method 'Node2D.MySignalCallback'.
  <C++ Error>   Condition "!signal_is_valid" is true. Returned: ERR_INVALID_PARAMETER
  <C++ Source>  core/object.cpp:1503 @ connect()
  <Stack Trace> :0 @ Int32 Godot.NativeCalls.godot_icall_5_593(IntPtr , IntPtr , System.String , IntPtr , System.String , IntPtr , UInt32 )()
                Object.cs:512 @ Godot.Error Godot.Object.Connect(System.String , Godot.Object , System.String , Godot.Collections.Array , UInt32 )()
                Manager.cs:13 @ void Manager._Ready()()

```

```
E 0:00:00.689   emit_signal: Can't emit non-existing signal "MySignal".
  <C++ Error>   Condition "!signal_is_valid && !script.is_null() && !Ref<Script>(script)->has_script_signal(p_name)" is true. Returned: ERR_UNAVAILABLE
  <C++ Source>  core/object.cpp:1195 @ emit_signal()
  <Stack Trace> :0 @ void Godot.NativeCalls.godot_icall_2_591(IntPtr , IntPtr , System.String , System.Object[] )()
                Object.cs:359 @ void Godot.Object.EmitSignal(System.String , System.Object[] )()
                ConcreteThing.cs:8 @ void ConcreteThing.MyMethod()()
                Manager.cs:14 @ void Manager._Ready()()
```

**Steps to reproduce:**
To verify this change in behaviour in the minimal reproduction project simply remove/add the generic type argument to the `GenericThing` class and `ConcreteThing` inheriting from it, then run the project.

**Minimal reproduction project:**

[Generics Example.zip](https://github.com/godotengine/godot/files/6298014/Generics.Example.zip)

### PR DESCRIPTION
**Pull request by raulsntos**
If the class is generic, we must get its generic type definition and use it to retrieve the delegates.

Closes #47830

---

I tested this PR using the 3.x version (#55564) because there seems to be an issue in `master` with the Source Generators and generic types.

### CODE REVIEW

File: modules/mono/mono_gd/gd_mono_class.cpp [hunk 1]
```diff
@@ -464,9 +464,18 @@ const Vector<GDMonoClass *> &GDMonoClass::get_all_delegates() {
 		return delegates_list;
 	}
 
+	// If the class is generic we must use the generic type definition.
+	MonoClass *klass = mono_class;
+	MonoReflectionType *reftype = mono_type_get_object(mono_domain_get(), get_mono_type());
+	if (GDMonoUtils::Marshal::type_is_generic(reftype)) {
```
Comment (neikeq) [inline modules/mono/mono_gd/gd_mono_class.cpp:470]: I don't think you need this helper function. You should be able to do the same with `mono_type_get_type(this->get_mono_type()) == MONO_TYPE_GENERICINST`, but I haven't tested.

Comment (raulsntos) [reply modules/mono/mono_gd/gd_mono_class.cpp]: It works, so I changed it.

**Review by neikeq — APPROVED** [review]

**Comment by neikeq** [comment]
Thanks!
