### PR TITLE
Fix `Camera3D::project_position()` when `depth == zfar`

### LINKED ISSUE #46010: Camera.project_position() always give wrong results when z_depth is Camera.far
**Godot version:**
3.2.3 stable official

**OS/device including version:**
Windows 10 64 bits

**Issue description:**
When I call Camera.project_position() with Camera.far as z_depth, I always have wrong results, the projected point is always at the center of the screen. To have correct results, I have to call this function with Camera.far-1 or Camera.far+1.

**Steps to reproduce:**
I made a minimal example to reproduce the bug:
```gdscript
extends Spatial

func _input(event: InputEvent) -> void:
	if event is InputEventMouseButton and event.is_pressed():
		calc_far(event.position)

func calc_far(position:Vector2) -> void:
	var camera := get_tree().root.get_camera()
	var far := camera.project_position(position, camera.far)
	$Far.global_transform.origin = far
	print(far)
```

**Minimal reproduction project:**
The project only have a Spatial node with the provided script and 2 children: a camera and a sphere mesh to visualize wrong projected positions.

### LINKED ISSUE #95786: Camera3D.project_position(point,z_depth) return wrong value when z_depth==far
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

macOS  10.15.7

### Issue description

Camera3D.project_position(point,z_depth) return wrong value when z_depth==far

### Steps to reproduce

add this script to a Camera3D:
```gdscript
extends Camera3D
func _ready() -> void:
	far=2000
	print(project_position(Vector2.ONE,999))
	print(project_position(Vector2.ONE,1000))
	print(project_position(Vector2.ONE,1001))
	print("---")
	far=1000
	print(project_position(Vector2.ONE,999))
	print(project_position(Vector2.ONE,1000))
	print(project_position(Vector2.ONE,1001))
```

the log:
```
(-1360.407, 764.1937, -999)
(-1361.769, 764.9588, -1000)
(-1363.13, 765.7237, -1001)
---
(-1360.407, 764.1937, -999)
(-0.998264, 0.996914, -1000)
(-1363.13, 765.7237, -1001)
```

### Minimal reproduction project (MRP)

empty project with camera3D

### PR DESCRIPTION
**Pull request by Flarkk**
Fixes #95786.
Edit : Fixes #46010

This PR computes the viewport half-extents directly by finding the intersection of the camera top and right planes with a camera-facing plane positioned at the user provided depth.

Without this PR, a second projection matrix was built from the camera projection by overriding its near distance with the user provided depth (`Projection cm = _get_camera_projection(p_z_depth);`).
When `p_z_depth` equals the camera far distance, the near and far distances become equal and :
- if the camera is in `PROJECTION_PERSPECTIVE` mode, a subsequent call to `Projection::set_perspective()` [returns an identity projection](https://github.com/godotengine/godot/blob/ff9fb0abea2027c35f0a024297c780648cc806bc/core/math/projection.cpp#L263C1-L265C3). This leads to an incorrect projection of the user provided position to the view space. This is the case that is reported in #95786
- if the camera is in `PROJECTION_FRUSTUM` mode, a subsequent call to `Projection::set_frustum()` [raises an exception](https://github.com/godotengine/godot/blob/ff9fb0abea2027c35f0a024297c780648cc806bc/core/math/projection.cpp#L367)
- if the camera is in `PROJECTION_ORTHOGONAL` mode, a subsequent call to `Projection::set_orthogonal()` generates a [division by zero](https://github.com/godotengine/godot/blob/ff9fb0abea2027c35f0a024297c780648cc806bc/core/math/projection.cpp#L351C2-L352C61).

This PR also updates unit tests of class `Camera3D` to add the case where the provided depth = zfar.

**Note :**

After this PR, `Camera3D::_get_camera_projection(real_t p_near)` is now exclusively called with its own camera's near value across the code (this PR removes the one and only case it was called with an user provided `p_near`).

It could be worth considering removing this function's parameter for the sake of code simplicity.
Note that it's a `protected` function member which means that it could be theoritically used in user modules by classes inheriting `Camera3D`.
I can definitely make this change in this PR or in another one if there is a consensus on making this small breaking change.

### CODE REVIEW

**Comment by Flarkk** [comment]
As a side note, I just realized that `XRCamera3D::project_position()` is likely doing it wrong too, for different reasons (the user-provided depth does not currently influence the final x and y components of the projected point).

https://github.com/godotengine/godot/blob/ff9fb0abea2027c35f0a024297c780648cc806bc/scene/3d/xr_nodes.cpp#L149C1-L177C3

The first thing to do would be to write unit tests for `XRCamera3D` too.

File: tests/scene/test_camera_3d.h [hunk 1]
```diff
@@ -234,7 +234,7 @@ TEST_CASE("[SceneTree][Camera3D] Project/Unproject position") {
 			// Top left.
 			CHECK(test_camera->project_position(Vector2(0, 0), 1.5f).is_equal_approx(Vector3(-5.0f, 2.5f, -1.5f)));
 			// Bottom right.
-			CHECK(test_camera->project_position(Vector2(400, 200), 5.0f).is_equal_approx(Vector3(5.0f, -2.5f, -5.0f)));
+			CHECK(test_camera->project_position(Vector2(400, 200), test_camera->get_far()).is_equal_approx(Vector3(5.0f, -2.5f, -test_camera->get_far())));
```
Comment (clayjohn) [inline tests/scene/test_camera_3d.h:237]: Do the old tests still pass? I think it would probably be worthwhile to keep the old tests in addition to the new tests

Comment (Flarkk) [reply tests/scene/test_camera_3d.h:237]: Yes they do. Ok I'm going to keep them

**Review by clayjohn — APPROVED** [review]
I'm approving as the code makes sense to me and I trust the tests. I'll admit though, without doing a deep dive into the geometry I'm at a loss why this works better than the old code.

**Comment by Flarkk** [comment]
For future reference, the key change is really this :
```diff
- Projection cm = _get_camera_projection(p_z_depth);
+ Projection cm = _get_camera_projection(_near);
```
It avoids using a modified camera projection where the near plane is replaced by the user input `p_z_depth`.
This produces a degenerate frustum when `p_z_depth == _far` and breaks further steps.

The rest just replaces the call to `Projection::get_viewport_half_extents()` with the unpacked logic of this function. This allows taking a plane (`z_slice`) as the input.

Hope it clarifies.

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
