### PR TITLE
Fix `AudioStreamRandomizer.random_volume_offset_db` not working

### LINKED ISSUE #82469: AudioStreamRandomizer.random_volume_offset_db not working
### Godot version

Godot v4.2dev5

### System information

Godot v4.2.dev5 - Windows 11- GLES3 (Compatibility) - NVIDIA GeForce GT 1030 (NVIDIA; 31.0.15.3742) - AMD 4700S 8-Core Processor Desktop Kit (16 Threads)

### Issue description

AudioStreamRandomizer's random_volume_offset_db does not make any audio volume variations playing an WAV file through an AudioStreamPlayer.

### Steps to reproduce

- Create an AudioStreamPlayer node
- Load an AudioStreamRandomizer
- Load an WAV file
- Set Volume Offset to any value

Playing it gives the same audio level everytime

### Minimal reproduction project

[ASRandomizer Bug.zip](https://github.com/godotengine/godot/files/12745215/ASRandomizer.Bug.zip)

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes #82469

Note：I did not quite obey the rule of OOP here but I think it's fine. Add a dedicated virtual method for getting the volume seems a little overkill.

### CODE REVIEW

**Comment by rakkarage** [comment]
`get_volume_variantion_range` = `get_volume_variation_range`? :)

File: servers/audio/audio_stream.cpp [hunk 1]
```diff
@@ -497,6 +497,14 @@ float AudioStreamRandomizer::get_random_volume_offset_db() const {
 	return random_volume_offset_db;
 }
 
+float AudioStreamRandomizer::get_volume_variation_range() const {
```
Comment (ellenhp) [inline servers/audio/audio_stream.cpp:500]: Nit: since this doesn't return the range, but rather the calculated random value, could we name it differently?

**Review by ellenhp — COMMENTED** [review]
Looks good overall, just a naming suggestion. I feel kind of silly that I didn't hook that up originally but I'm glad someone noticed and fixed it :sweat_smile:

File: servers/audio/audio_stream.h [hunk 2]
```diff
@@ -258,6 +258,8 @@ class AudioStreamRandomizer : public AudioStream {
 	void set_random_volume_offset_db(float p_volume_offset_db);
 	float get_random_volume_offset_db() const;
 
+	float get_volume_variation_range() const;
```
Comment (ellenhp) [inline servers/audio/audio_stream.h:261]: This should also be private.

**Comment by ellenhp** [comment]
Couldn't we just apply the volume shift here[1]? Leave the code that sets it where it is and just multiply the values returned by _mix by `volume_scale`

[1] https://github.com/godotengine/godot/blob/master/servers/audio/audio_stream.cpp#L811C3-L811C3

**Comment by jsjtxietian** [comment]
> multiply the values returned by `playing->mix` by `volume_scale`

Yes we can! I did not know we can do it this way : )

File: servers/audio/audio_stream.h (hunk 2 above)
Comment (jsjtxietian) [reply servers/audio/audio_stream.h:261]: > I don't like the way we're handling this with the casting attempt and public method.

To be honest, me too.

File: scene/audio/audio_stream_player.cpp [hunk 3]
```diff
@@ -32,6 +32,7 @@
 
 #include "core/config/engine.h"
 #include "core/math/audio_frame.h"
+#include "core/object/object.h"
```
Comment (AThousandShips) [inline scene/audio/audio_stream_player.cpp:35]:
```suggestion
```
Added by IDE I assume, make sure to remove these or deactivate the feature, this is already included (or you couldn't have `AudioStreamPlayer`)

File: scene/audio/audio_stream_player.cpp [hunk 4]
```diff
@@ -269,7 +270,14 @@ Vector<AudioFrame> AudioStreamPlayer::_get_volume_vector() {
 		channel_volume_db = AudioFrame(0, 0);
 	}
 
-	float volume_linear = Math::db_to_linear(volume_db);
+	float final_volume_db = volume_db;
+
+	AudioStreamRandomizer *randomizer = Object::cast_to<AudioStreamRandomizer>(stream.ptr());
+	if (randomizer != NULL) {
```
Comment (AThousandShips) [inline scene/audio/audio_stream_player.cpp:276]:
```suggestion
	if (randomizer != nullptr) {
```

File: scene/audio/audio_stream_player.cpp (hunk 3 above)
Comment (jsjtxietian) [reply scene/audio/audio_stream_player.cpp:35]: Yes added by IDE, I will take a look, thanks !

**Comment by ellenhp** [comment]
> I tried, it didn't work out. The output sound is glitch.

Just to confirm, what I was suggesting it to save the value of `volume_scale` that you're calculating here into a field of the playback object. Once it's set, it won't be updated ever again. If you're re-calculating the value each time `_mix` is called, that's going to cause some really glitchy audio. But calculating it once when the playback is started, and then re-using it each time `_mix` is called will work. I don't want to approve this with the `cast_to` because I don't want to special-case the randomizer stream.

**Comment by jsjtxietian** [comment]
@ellenhp  Sorry for my misundersanding and thank you for your suggestion.
What I mean is if I only add `volume_scale *` to this `mix` function like below, the sound is weird.
```
int AudioStreamPlaybackRandomizer::mix(AudioFrame *p_buffer, float p_rate_scale, int p_frames) {
	if (playing.is_valid()) {
		return volume_scale * playing->mix(p_buffer, p_rate_scale * pitch_scale, p_frames);
	} else {
		for (int i = 0; i < p_frames; i++) {
			p_buffer[i] = AudioFrame(0, 0);
		}
		return p_frames;
	}
}

```

**Comment by ellenhp** [comment]
Ah! Okay, I see now. Can you try doing something more like this:

```
......
	if (playing.is_valid()) {
		int mixed_samples = playing->mix(p_buffer, p_rate_scale * pitch_scale, p_frames);
		for (int samp = 0; samp < mixed_samples; samp++) {
			p_buffer[samp] *= volume_scale;
		}
		return mixed_samples;
	} else {
......
```

The mix function returns an integer representing the number of samples it actually mixed into the provided buffer, and the samples themselves are written directly to the array provided in `p_buffer`. So to multiply the samples by `volume_scale` you have to go through that array and perform the multiplication for each one.

**Comment by jsjtxietian** [comment]
Tested locally, it worked！

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
