### PR TITLE
Fix AHashMap realloc cause AnimationPlayer crash (reverted)

### LINKED ISSUE #112038: Engine crashes on animation name with a float
### Tested versions

I am using version 4.5.1.

### System information

Godot v4.5.1.stable - Ubuntu 24.04.3 LTS 24.04 on X11 - X11 display driver, Multi-window, 2 monitors - OpenGL 3 (Compatibility) - Mesa Intel(R) UHD Graphics 630 (CFL GT2) - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 threads) - 15.24 GiB memory

### Issue description

I am manually creating an animation in the following form:

```gdscript
func _ready() -> void:
	var adjustment = randf_range(-0.3, 0.3)
	var animation = Animation.new()
	var track_index = animation.add_track(Animation.TYPE_VALUE)
	animation.track_set_path(track_index, ":position:y")
	animation.track_insert_key(track_index, 0.0, -10)
	animation.track_insert_key(track_index, 1.0 + adjustment, 0)
	animation.length = 1.0 + adjustment
	var library = $AnimationPlayer.get_animation_library("global")
	var name = "rise_" + str(adjustment)
	print(name)
	library.add_animation(name, animation)
	$AnimationPlayer.play("global/" + name)
```

This leads to a crash. I attach a sample of names:

```
rise_0.13513279836257
rise_-0.24190951726188
rise_-0.01806726535611
rise_-0.21182971002127
rise_0.20171917486071
rise_0.02601517296699
rise_0.190256156346
rise_0.06735320351299
rise_0.08413656086737
rise_-0.03430272418879
rise_0.23699314709116

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.5.1.stable.official (f62fdbde15035c5576dad93e586201f4d41ef0cb)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x45330) [0x795488445330] (??:0)
[2] /home/gru/Programs/Godot_v4.5.1-stable_linux.x86_64() [0x3218d5c] (??:0)
[3] /home/gru/Programs/Godot_v4.5.1-stable_linux.x86_64() [0x323da14] (??:0)
[4] /home/gru/Programs/Godot_v4.5.1-stable_linux.x86_64() [0x321bcc7] (??:0)
[5] /home/gru/Programs/Godot_v4.5.1-stable_linux.x86_64() [0x47ab201] (??:0)
[6] /home/gru/Programs/Godot_v4.5.1-stable_linux.x86_64() [0x288a02f] (??:0)
[7] /home/gru/Programs/Godot_v4.5.1-stable_linux.x86_64() [0x288b19f] (??:0)
[8] /home/gru/Programs/Godot_v4.5.1-stable_linux.x86_64() [0x2858f11] (??:0)
[9] /home/gru/Programs/Godot_v4.5.1-stable_linux.x86_64() [0x53e479] (??:0)
[10] /home/gru/Programs/Godot_v4.5.1-stable_linux.x86_64() [0x42d2b7] (??:0)
[11] /lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca) [0x79548842a1ca] (??:0)
[12] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x79548842a28b] (??:0)
[13] /home/gru/Programs/Godot_v4.5.1-stable_linux.x86_64() [0x46ca2a] (??:0)
-- END OF C++ BACKTRACE --
================================================================
```

These might be potentially illegal names, but I don't think they should crash the engine, but throw instead.

### Steps to reproduce

As shown above

### Minimal reproduction project (MRP)

1. Mesh node + Animation player as a scene with the script I attached above
2. In another scene instantiate the other scene

### PR DESCRIPTION
**Pull request by xuhuisheng**
- *Fixes: https://github.com/godotengine/godot/issues/112038*

## Issue Description

When we create 15 (more than 12) animations with multiple `AnimationPlayer` in GDScript, the game will crash at the beginning of running.

The asan shows the relevant memory of `playback.current.from` is freed by `realloc`.

```
=================================================================
==287135==ERROR: AddressSanitizer: heap-use-after-free on address 0x515000554010 at pc 0x62e0145ab21e bp 0x7fff8df78af0 sp 0x7fff8df78ae8
READ of size 8 at 0x515000554010 thread T0
    #0 0x62e0145ab21d in Ref<Animation>::operator->() const /home/work/godot/./core/object/ref_counted.h:120:10
    #1 0x62e02aab5ad2 in AnimationPlayer::_blend_pre_process(double, int, AHashMap<NodePath, int, HashMapHasherDefault, HashMapComparatorDefault<NodePath, void>> const&) /home/work/godot/scene/animation/animation_player.cpp:324:13
    #2 0x62e02a8fb0f5 in AnimationMixer::_process_animation(double, bool) /home/work/godot/scene/animation/animation_mixer.cpp:1003:6
    #3 0x62e02a943ca0 in AnimationMixer::_notification(int) /home/work/godot/scene/animation/animation_mixer.cpp:2370:5
    #4 0x62e02a97538a in AnimationMixer::_notification_forwardv(int) /home/work/godot/scene/animation/animation_mixer.h:43:2
    #5 0x62e02aaeab98 in AnimationPlayer::_notification_forwardv(int) /home/work/godot/scene/animation/animation_player.h:37:2
    #6 0x62e0333d0f07 in Object::_notification_forward(int) /home/work/godot/core/object/object.cpp:993:2
    #7 0x62e011fad0f6 in Object::notification(int, bool) /home/work/godot/./core/object/object.h:919:4
    #8 0x62e026c252f2 in SceneTree::_process_group(SceneTree::ProcessGroup*, bool) /home/work/godot/scene/main/scene_tree.cpp:1201:8
    #9 0x62e026c117ae in SceneTree::_process(bool) /home/work/godot/scene/main/scene_tree.cpp:1281:8
    #10 0x62e026c1773e in SceneTree::process(double) /home/work/godot/scene/main/scene_tree.cpp:708:2
    #11 0x62e0124422f4 in Main::iteration() /home/work/godot/main/main.cpp:4859:44
    #12 0x62e011fcdcc5 in OS_LinuxBSD::run() /home/work/godot/platform/linuxbsd/os_linuxbsd.cpp:994:7
    #13 0x62e01202d805 in main /home/work/godot/platform/linuxbsd/godot_linuxbsd.cpp:121:6
    #14 0x7dc52482a1c9 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #15 0x7dc52482a28a in __libc_start_main csu/../csu/libc-start.c:360:3
    #16 0x62e011ecd7e4 in _start (/home/work/local/godot.linuxbsd.editor.dev.x86_64.llvm.san+0x209ad7e4) (BuildId: a4a626d0fcd74417)

0x515000554010 is located 272 bytes inside of 496-byte region [0x515000553f00,0x5150005540f0)
freed by thread T0 here:
    #0 0x62e011f68a50 in realloc (/home/work/local/godot.linuxbsd.editor.dev.x86_64.llvm.san+0x20a48a50) (BuildId: a4a626d0fcd74417)
    #1 0x62e031517268 in Memory::realloc_static(void*, unsigned long, bool) /home/work/godot/core/os/memory.cpp:170:21
    #2 0x62e02a9852b2 in AHashMap<StringName, AnimationMixer::AnimationData, HashMapHasherDefault, HashMapComparatorDefault<StringName, void>>::_resize_and_rehash(unsigned int) /home/work/godot/./core/templates/a_hash_map.h:219:47
    #3 0x62e02a9848f9 in AHashMap<StringName, AnimationMixer::AnimationData, HashMapHasherDefault, HashMapComparatorDefault<StringName, void>>::_insert_element(StringName const&, AnimationMixer::AnimationData const&, unsigned int) /home/work/godot/./core/templates/a_hash_map.h:243:4
    #4 0x62e02a94ca14 in AHashMap<StringName, AnimationMixer::AnimationData, HashMapHasherDefault, HashMapComparatorDefault<StringName, void>>::insert(StringName const&, AnimationMixer::AnimationData const&) /home/work/godot/./core/templates/a_hash_map.h:617:18
    #5 0x62e02a8dbc58 in AnimationMixer::_animation_set_cache_update() /home/work/godot/scene/animation/animation_mixer.cpp:166:19
    #6 0x62e02a8dd7e8 in AnimationMixer::_animation_added(StringName const&, StringName const&) /home/work/godot/scene/animation/animation_mixer.cpp:209:2
    #7 0x62e02a98a0d5 in void call_with_variant_args_helper<AnimationMixer, StringName const&, StringName const&, 0ul, 1ul>(AnimationMixer*, void (AnimationMixer::*)(StringName const&, StringName const&), Variant const**, Callable::CallError&, IndexSequence<0ul, 1ul>) /home/work/godot/./core/variant/binder_common.h:223:2
    #8 0x62e02a989ca4 in void call_with_variant_args<AnimationMixer, StringName const&, StringName const&>(AnimationMixer*, void (AnimationMixer::*)(StringName const&, StringName const&), Variant const**, int, Callable::CallError&) /home/work/godot/./core/variant/binder_common.h:337:2
    #9 0x62e02a989795 in CallableCustomMethodPointer<AnimationMixer, void, StringName const&, StringName const&>::call(Variant const**, int, Variant&, Callable::CallError&) const /home/work/godot/./core/object/callable_method_pointer.h:103:4
    #10 0x62e0323afacb in Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const /home/work/godot/core/variant/callable.cpp:57:11
    #11 0x62e0323c80ff in CallableCustomBind::call(Variant const**, int, Variant&, Callable::CallError&) const /home/work/godot/core/variant/callable_bind.cpp:150:11
    #12 0x62e0323afacb in Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const /home/work/godot/core/variant/callable.cpp:57:11
    #13 0x62e0333dc918 in Object::emit_signalp(StringName const&, Variant const**, int) /home/work/godot/core/object/object.cpp:1341:13
    #14 0x62e0227af355 in Error Object::emit_signal<StringName>(StringName const&, StringName) /home/work/godot/./core/object/object.h:967:10
    #15 0x62e02af69394 in AnimationLibrary::add_animation(StringName const&, Ref<Animation> const&) /home/work/godot/scene/resources/animation_library.cpp:59:2
    #16 0x62e02af87997 in void call_with_variant_args_ret_helper<__UnexistingClass, Error, StringName const&, Ref<Animation> const&, 0ul, 1ul>(__UnexistingClass*, Error (__UnexistingClass::*)(StringName const&, Ref<Animation> const&), Variant const**, Variant&, Callable::CallError&, IndexSequence<0ul, 1ul>) /home/work/godot/./core/variant/binder_common.h:672:10
    #17 0x62e02af874ec in void call_with_variant_args_ret_dv<__UnexistingClass, Error, StringName const&, Ref<Animation> const&>(__UnexistingClass*, Error (__UnexistingClass::*)(StringName const&, Ref<Animation> const&), Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) /home/work/godot/./core/variant/binder_common.h:454:2
    #18 0x62e02af8533f in MethodBindTR<Error, StringName const&, Ref<Animation> const&>::call(Object*, Variant const**, int, Callable::CallError&) const /home/work/godot/./core/object/method_bind.h:515:3
    #19 0x62e017d0a0ae in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) /home/work/godot/modules/gdscript/gdscript_vm.cpp:2058:25
    #20 0x62e0173c5eb3 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) /home/work/godot/modules/gdscript/gdscript.cpp:2059:22
    #21 0x62e0333cd7fc in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) /home/work/godot/core/object/object.cpp:884:26
    #22 0x62e03246fd4d in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) /home/work/godot/core/variant/variant_call.cpp:1419:27
    #23 0x62e017d065cb in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) /home/work/godot/modules/gdscript/gdscript_vm.cpp:1955:12
    #24 0x62e0173c5eb3 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) /home/work/godot/modules/gdscript/gdscript.cpp:2059:22
    #25 0x62e026b0bd4a in Node::_gdvirtual__ready_call() /home/work/godot/scene/main/node.h:431:2
    #26 0x62e026a6f0e9 in Node::_notification(int) /home/work/godot/scene/main/node.cpp:273:4
    #27 0x62e0145f820a in Node::_notification_forwardv(int) /home/work/godot/./scene/main/node.h:51:2
    #28 0x62e014bbf8a8 in Node3D::_notification_forwardv(int) /home/work/godot/./scene/3d/node_3d.h:51:2
    #29 0x62e016b0c278 in VisualInstance3D::_notification_forwardv(int) /home/work/godot/./scene/3d/visual_instance_3d.h:38:2
```

### `AHashMap` will call `realloc` when meets auto grow factor

The default capacity of `AHashMap` is `16`.

https://github.com/godotengine/godot/blob/235a32ad11f40ecba26d6d9ceea8ab245c13adb0/core/templates/a_hash_map.h#L85

The auto expand factor of `AHashMap` is 0.75 (12 = 16 * 0.75).

https://github.com/godotengine/godot/blob/235a32ad11f40ecba26d6d9ceea8ab245c13adb0/core/templates/a_hash_map.h#L115-L117

When the size of `AHashMap` meets `12`, it will `realloc` its memory, grows to `32`.

https://github.com/godotengine/godot/blob/235a32ad11f40ecba26d6d9ceea8ab245c13adb0/core/templates/a_hash_map.h#L219

I guess when there is no enough continuous memory, `realloc` may allocate a new range of memory and free original memory. Because I cannot re-produce crash with only one `AnimationPlayer`.

### `AnimationPlayer` use a pointer to reference address from `AHashMap`

When we call `play(animation_name)`, we will store relevant address of `animation_set[name]` to a pointer named `playback.current.from`.

https://github.com/godotengine/godot/blob/235a32ad11f40ecba26d6d9ceea8ab245c13adb0/scene/animation/animation_player.cpp#L501

- First, we called `play()` to store an `AnimationData` address from `AHashMap` to `playback.current.from` of `AnimationPlayer`.
- Second, we keep adding animation and exceed  the auto grow factor, this time is 12, to trigger `realloc`.
- If `realloc` frees the original memory of `AHashMap`. Next time when we used `playback.current.from`, we will meet crashing. Because relevant memory is freed by `realloc`.

## Solution

The solution is **DON'T** reference the address of `AHashMap` element directly, because it may be freed when **AUTO GROW**. We can save animation name and get `AnimationData` with name when used.

### CODE REVIEW

File: scene/animation/animation_player.cpp [hunk 1]
```diff
@@ -300,12 +301,13 @@ void AnimationPlayer::_blend_playback_data(double p_delta, bool p_started) {
 }
 
 bool AnimationPlayer::_blend_pre_process(double p_delta, int p_track_count, const AHashMap<NodePath, int> &p_track_map) {
-	if (!playback.current.from) {
+	if (playback.current.animation_name == String()) {
```
Comment (AThousandShips) [inline scene/animation/animation_player.cpp]:
```suggestion
	if (playback.current.animation_name.is_empty()) {
```

File: scene/animation/animation_player.cpp [hunk 2]
```diff
@@ -498,11 +500,16 @@ void AnimationPlayer::play_section(const StringName &p_name, double p_start_time
...
-	c.current.from = &animation_set[name];
+	c.current.animation_name = name;
+	c.current.animation_length = animation_set[name].animation->get_length();
 	c.current.speed_scale = p_custom_scale;
 	c.current.start_time = p_start_time;
 	c.current.end_time = p_end_time;
 
+	// print_line("animation_set[name]", animation_set[name].name);
+	// print_line("c.current.from", c.current.from);
+	// print_line("c.current.from", "name", c.current.from->name);
```
Comment (AThousandShips) [inline scene/animation/animation_player.cpp]:
```suggestion
	//print_line("animation_set[name]", animation_set[name].name);
	//print_line("c.current.from", c.current.from);
	//print_line("c.current.from", "name", c.current.from->name);
```
Or
```suggestion
```

**Review by Ivorforce — COMMENTED** [review]
I can confirm it is illegal to store a reference into a mutating `AHashMap`, for the reasons given in the OP. For more information, see [Core types](https://docs.godotengine.org/en/latest/engine_details/architecture/core_types.html#containers). 

This is notably not the case for `HashMap`, which was previously used, which I think makes this a regression from #92554 (4.4). Interesting how it didn't come up yet!

Considering this, an alternative solution to what's proposed here would be exchanging `AHashMap` for `HashMap` again, although this would regress the performance benefits measured in #92554.
Overall, I'd probably go with the solution proposed here. But I'll leave this decision for the animation team to make.

**Review by TokageItLab — APPROVED** [review]
As mentioned above by @Ivorforce, it would be preferable to avoid using an AHasmap and thus compromising performance if the issue can be resolved by not holding references.

File: scene/animation/animation_player.h [hunk 3]
```diff
@@ -65,20 +65,21 @@ class AnimationPlayer : public AnimationMixer {
 	bool is_stopping = false;
 
 	struct PlaybackData {
-		AnimationData *from = nullptr;
+		String animation_name;
+		int animation_length;
```
Comment (AThousandShips) [inline scene/animation/animation_player.h]:
```suggestion
		int animation_length = 0;
```
Or some appropriate default

File: scene/animation/animation_player.cpp (hunk 1 above)
Comment (AThousandShips) [inline scene/animation/animation_player.cpp]:
```suggestion
	if (playback.current.animation_name.is_empty()) {
```

File: scene/animation/animation_player.cpp (hunk 2 above)
Comment (AThousandShips) [inline scene/animation/animation_player.cpp]:
```suggestion
	//print_line("animation_set[name]", animation_set[name].name);
	//print_line("c.current.from", c.current.from);
	//print_line("c.current.from", "name", c.current.from->name);
```
Or
```suggestion
```

**Comment by Repiteo** [comment]
Thanks!

File: scene/animation/animation_player.cpp [hunk 4]
```diff
@@ -455,11 +457,11 @@ void AnimationPlayer::play_section(const StringName &p_name, double p_start_time
 
 	Playback &c = playback;
 
-	if (c.current.from) {
+	if (!c.current.animation_name.is_empty()) {
```
Comment (TokageItLab) [inline scene/animation/animation_player.cpp:460]: This change caused issue https://github.com/godotengine/godot/issues/113165, so it was reverted in https://github.com/godotengine/godot/pull/113187.

As I commented that, but explain it here again: Avoidance to hold reference is fine, but change of the animation existence check to use animation name was wrong since current animation uses empty and [stop] as the stopped state. See also https://github.com/godotengine/godot/pull/98704.

File: scene/animation/animation_player.cpp [hunk 5]
```diff
@@ -300,12 +301,13 @@ void AnimationPlayer::_blend_playback_data(double p_delta, bool p_started) {
 }
 
 bool AnimationPlayer::_blend_pre_process(double p_delta, int p_track_count, const AHashMap<NodePath, int> &p_track_map) {
-	if (!playback.current.from) {
+	if (playback.current.animation_name.is_empty()) {
```
Comment (TokageItLab) [inline scene/animation/animation_player.cpp:304]: This is the same issue.

File: scene/animation/animation_player.cpp [hunk 6]
```diff
@@ -699,37 +704,37 @@ void AnimationPlayer::_check_immediately_after_start() {
...
 	if (p_end_marker && Animation::is_less_approx(end_time, 0)) {
-		WARN_PRINT_ONCE_ED(vformat("Marker %s time must be positive in animation: %s.", p_end_marker, playback.current.from->animation->get_name()));
+		WARN_PRINT_ONCE_ED(vformat("Marker %s time must be positive in animation: %s.", p_end_marker, playback.current.animation_name));
 	}
 	set_section(start_time, end_time);
 }
 
 void AnimationPlayer::set_section(double p_start_time, double p_end_time) {
-	ERR_FAIL_NULL_MSG(playback.current.from, "AnimationPlayer has no current animation.");
+	ERR_FAIL_COND_MSG(!playback.current.animation_name.is_empty(), "AnimationPlayer has no current animation.");
```
Comment (TokageItLab) [inline scene/animation/animation_player.cpp:737]: This is the same issue. (And all other lines which uses `animation_name.is_empty()`)

**Comment by xuhuisheng** [comment]
Thank you for pointing out. I think I need do more tests.
