### PR TITLE
Daily physics Fixes

### LINKED ISSUE #16451: animating rigidbody in kinematic mode don't return linear velocity
**Godot version:**

Godot 3.0 Stable

**OS/device including version:**

Windows 7

**Issue description:**

In Godot 2.1.4, if I move a rigidbody in kinematic mode by animationplayer,
I can query its linear velocity in GDScript by calling get_linear_velocity

But now in Godot 3, I get zero vector by calling getting its linear_velocity

**Steps to reproduce:**
1. create a rigidbody in kinematic mode
2. create a animation player
3. animate the rigidbody to move from one point to another point
4. get the linear velocity of rigidbody by getting its linear_velocity in GDScript
5. the resulting velocity is always zero vector

### LINKED ISSUE #21952: Area: signal body_entered is called too early with correct collision shape setup
**Godot version:**
master (https://github.com/godotengine/godot/commit/864a3143406fe9a8023995ef5ca10758bcdd6ecd)

**OS/device including version:**
Arch Linux

**Issue description:**
When I run the racing game, the game ends before the car reachs the final lap. This only happens on master.

**Minimal reproduction project:**
https://github.com/HugeGameArtGD/Solus-Stunts.git (```git clone --recursive```)

### LINKED ISSUE #22167: get_contact_local_position() wrong direction [with bullet physics, work normally with GodotPhysics]
**Godot version: 3.06**
**windows 10:**
**Issue description:**
hello hello,
get_contact_local_position(0) report a vector that sound to be the opposite of expected
work around is easy -> contact_point = - get_contact_local_position(0) 
**Steps to reproduce:**
create 2 rigidbodies with collision shape (make collision shape visible)
make one fall on the other
print or draw the result of  : s.get_contact_local_position(0)
do this with bullet physics and godot physics engine

I wish I could put an explicit gif of the issue but that's not really easy for me now.
cheers

### PR DESCRIPTION
**Pull request by AndreaCatania**
fixes #22167
fixes #21952
fixes #16451

### CODE REVIEW

**Comment by groud** [comment]
The first one is a PR, not an issue.

File: modules/bullet/space_bullet.cpp [hunk 1]
```diff
@@ -786,30 +786,32 @@ void SpaceBullet::check_body_collision() {
...
-					B_TO_G(pt.getPositionWorldOnB() - contactManifold->getBody1()->getWorldTransform().getOrigin(), collisionLocalPosition);
-					bodyA->add_collision_object(bodyB, collisionWorldPosition, collisionLocalPosition, normalOnB, appliedImpulse, pt.m_index1, pt.m_index0);
-				}
-				if (bodyB->can_add_collision()) {
-					B_TO_G(pt.getPositionWorldOnA(), collisionWorldPosition);
-					/// pt.m_localPointA Doesn't report the exact point in local space
-					B_TO_G(pt.getPositionWorldOnA() - contactManifold->getBody0()->getWorldTransform().getOrigin(), collisionLocalPosition);
-					bodyB->add_collision_object(bodyA, collisionWorldPosition, collisionLocalPosition, normalOnB * -1, appliedImpulse * -1, pt.m_index0, pt.m_index1);
-				}
+				if (pt.getDistance() <= 0.0) {
```
Comment (akien-mga) [inline modules/bullet/space_bullet.cpp]: It's a matter of style, but this would save you of the hassle of indenting everything by one more tab:
```
if (pt.getDistance() > 0.0) {
	return;
}
```

**Review by akien-mga — APPROVED** [review]

**Comment by AndreaCatania** [comment]
Yep, but in this case it's not possible to use it. Check the macro above

**Comment by akien-mga** [comment]
Ah indeed :)

**Comment by akien-mga** [comment]
Thanks!
