### PR TITLE
LSP: Fix autocomplete quote handling

### LINKED ISSUE #48436: Language server string autocomplete place undesired quotes
**Godot version:**
3.3

**OS/device including version:**
Ubuntu

**Issue description:**
When autocompleting strings, the language server puts undesired quotes.

**Steps to reproduce:**
See video

https://user-images.githubusercontent.com/1168582/116951932-b1376400-ac5f-11eb-9eb5-a3d940c7ef32.mp4

**Minimal reproduction project:**
Any GD script file

### PR DESCRIPTION
**Pull request by 0x4448**
Fixes #48436

Updates to language server:
- Add missing context to CompletionParams so context can be used in the resolve function.
- Omit quotes in auto-complete suggestion if triggered with single or double quote.

I'm new to Godot and C++, but after poking around the code base a bit, I was able to get it working by making two changes:

1. CompletionParams has a new `context` member. It provided an implementation for `load()` to include that data, but not one for `to_json()`. So `context` was missing from the JSON and there's already code in `GDScriptTextDocument::resolve()` that depends on that. I added `context` to the JSON so it can be used in `resolve()`.
2. Now that `resolve()` has the context, the current bug can be fixed. If the completion was triggered with a single or double quote,  then there's already a quote (or a pair of quotes) in the external editor. The auto-complete suggestion should be returned without quotes.

Both changes are in language server classes, so this change should not break the built-in editor. I did a quick test to confirm that still returns quotes.

Again, I'm new to Godot and C++, so if I'm overlooking something obvious, please let me know and I'll try to fix it.

### CODE REVIEW

**Comment by Ury18** [comment]
Any updates on this issue?

**Review by adamscott — APPROVED** [review]
It seems fine to me! I tested it and it works.

And thank you for this first contribution. It's clean and does the job. Good job!

Don't hesitate to join the [developer chat](https://chat.godotengine.org), especially if you want to continue contributing to Godot! Happy to see you there!

File: modules/gdscript/language_server/gdscript_text_document.cpp [hunk 1]
```diff
@@ -346,6 +346,16 @@ Dictionary GDScriptTextDocument::resolve(const Dictionary &p_params) {
 		}
 	}
 
+	if (item.kind == lsp::CompletionItemKind::Method) {
+		bool isTriggerCharacter = params.context.triggerKind == lsp::CompletionTriggerKind::TriggerCharacter;
+		bool isQuoteCharacter = params.context.triggerCharacter == "\"" || params.context.triggerCharacter == "'";
+
+		if (isTriggerCharacter && isQuoteCharacter && item.insertText.is_quoted()) {
+			item.insertText = item.insertText.lstrip("'").rstrip("'");
+			item.insertText = item.insertText.lstrip("\"").rstrip("\"");
```
Comment (akien-mga) [inline modules/gdscript/language_server/gdscript_text_document.cpp:355]: Wouldn't `item.insertText.unquote()` be equivalent / sufficient here?

To be clear that's the implementation:
```
String String::unquote() const {
        if (!is_quoted()) {
                return *this;
        }

        return substr(1, length() - 2);
}
```

So it just removes the first and last char after confirming those are quotes.

The different with your code is that it would also remove nested quotes of this form: `'"some text"'` (single quote then double quote). But I'm not sure that's wanted?

Comment (0x4448) [reply modules/gdscript/language_server/gdscript_text_document.cpp]: Thank you for pointing out `unquote()`. I updated the code to use it, but left in the `is_quoted()` check for the reasons you mentioned.

File: modules/gdscript/language_server/gdscript_text_document.cpp [hunk 2]
```diff
@@ -346,6 +346,15 @@ Dictionary GDScriptTextDocument::resolve(const Dictionary &p_params) {
 		}
 	}
 
+	if (item.kind == lsp::CompletionItemKind::Method) {
+		bool isTriggerCharacter = params.context.triggerKind == lsp::CompletionTriggerKind::TriggerCharacter;
+		bool isQuoteCharacter = params.context.triggerCharacter == "\"" || params.context.triggerCharacter == "'";
+
+		if (isTriggerCharacter && isQuoteCharacter && item.insertText.is_quoted()) {
+			item.insertText = item.insertText.unquote();
+		}
```
Comment (AThousandShips) [inline modules/gdscript/language_server/gdscript_text_document.cpp:355]:
```suggestion
		bool is_trigger_character = params.context.triggerKind == lsp::CompletionTriggerKind::TriggerCharacter;
		bool is_quote_character = params.context.triggerCharacter == "\"" || params.context.triggerCharacter == "'";

		if (is_trigger_character && is_quote_character && item.insertText.is_quoted()) {
			item.insertText = item.insertText.unquote();
		}
```
Use `snake_case` in c++

**Comment by AThousandShips** [comment]
Please squash your commits into one, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

**Comment by 0x4448** [comment]
> Please squash your commits into one, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

I've squashed the revisions to `resolve()` into one commit. I can also squash the `to_json()` change, but since that also fixes other existing code, I thought that might be better in a separate commit.

**Comment by AThousandShips** [comment]
No need for two different commits here, the changes aren't significant enough

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by Andy608** [comment]
Hello, I'm a noob when it comes to this kind of stuff, but I was wondering if this fix is going to be merged into Godot 3.5 LTS? Just started working with Godot and I've noticed this bug present in the current 3.5.3 LTS version. Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.3.
