### PR TITLE
Restore 'rotation_degrees' properties.

### LINKED ISSUE #63390: Restore rotation_degrees or provide deg_to_rad(Vector*)
### Godot version

4.0alpha12+

### System information

Win 10/64 NVIDIA GeForce GTX 1060/PCIe/SSE2

## Core Issues

* Many of us used rotation_degrees in our code and AnimationPlayers. It was removed for no good reason. Please restore it.

* The Inspector and code use different units for the same rotation variable. (?!)

The engine devs clearly understand that game devs wish to use degrees, because they provide degrees in the inspector. In fact it's the only option. Yet in code we can only work with radians, as rotation_degrees was removed. 

It's crazy to use `rotation` in the inspector with degrees, while `rotation` in code works in radians. Any experienced game dev is going to be working with rotations in both the inspector and code. Virtually no one is going to use only one. 

Radians and degrees are currently both implemented in the engine, so there is absolutely no savings of code or memory by neutering the API. At best, there are a few less lines on the manual page.

This choice has broken our animationplayers, forced us to rewrite our code, and manually convert degrees, and leaves the engine in a weird state where we use two different units for the same variable.

Please give us back the two variable syntactic sugar of rotation(radians) and rotation_degrees. Or if you want to drop one, drop radians. Or find another solution, such as below, but using two different units for rotation is nuts.

## Alternative
Rotation, like all transform options are commonly updated frequently, every frame, on potentially thousands of objects. There is a `deg_to_rad(float)` function, but no Vector* variations. 

This means for those of us who want to work in degrees in 3D, we must deconstruct a Vector3, convert each component, then reconstruct the Vector. This is unnecessarily slow in GDScript, every frame, on thousands of objects, when it could be done in C++ (especially since the code is already there).

As an alternative to the above:
* Please provide `deg_to_rad(Vector2/3/4)` variations (and `rad_to_deg`) so we can convert in C++ rather than GDscript.
* Convert AnimationPlayer animations by renaming rotation_degrees to rotation. The values are the same since the editor works in animations only. See #65481.

Or maybe we do everything: restore rotation_degrees, make the code and inspector function the same way, and provide deg_to_rad(vector) and convert animation tracks. I haven't heard a single good reason for neutering the API. And I've experienced and heard of a lot of pain from devs as we fix things that unnecessarily broke.

Related to #58316, but that's an editor issue.

### Steps to reproduce

```
# Unnecessarily slow:
node.rotation = Vector3( deg_to_rad(new_deg_rotation.x), deg_to_rad(new_deg_rotation.y), deg_to_rad(new_deg_rotation.z) )

# Should be:
node.rotation_degrees = new_deg_rotation
# or
node.rotation = deg_to_rad(new_deg_rotation) 
```

### Temporary Workaround
Fine for limited use, but not optimal for updates on many objects every frame.

```
# Util.gd
static func d2r(vect: Vector3) -> Vector3:
	return Vector3( deg_to_rad(vect.x), deg_to_rad(vect.y), deg_to_rad(vect.z) )

# Called like:
node.rotation = Util.d2r(new_deg_rotation)
```

### PR DESCRIPTION
**Pull request by reduz**
By popular demand, restoring the helper properties to rotate objects in degrees. Affected are local and global rotations for:

* Node2D
* Node3D
* Control

*Bugsquad edit:*
- Fixes #63390

### CODE REVIEW

**Comment by fire** [comment]
I think we can assist with filling the descriptions.

File: scene/2d/node_2d.cpp [hunk 1]
```diff
@@ -149,6 +149,14 @@ void Node2D::set_rotation(real_t p_radians) {
 	_update_transform();
 }
 
+void Node2D::set_rotation_degrees(real_t p_degrees) {
+	if (_xform_dirty) {
+		const_cast<Node2D *>(this)->_update_xform_values();
+	}
+	rotation = Math::deg_to_rad(p_degrees);
+	_update_transform();
```
Comment (KoBeWi) [inline scene/2d/node_2d.cpp:157]:
```suggestion
	set_rotation(Math::deg_to_rad(p_degrees));
```
This time there is no reason to not reuse it...

File: doc/classes/Control.xml [hunk 2]
```diff
@@ -1050,6 +1050,8 @@
 		<member name="rotation" type="float" setter="set_rotation" getter="get_rotation" default="0.0">
 			The node's rotation around its pivot, in radians. See [member pivot_offset] to change the pivot's position.
 		</member>
+		<member name="rotation_degrees" type="float" setter="set_rotation_degrees" getter="get_rotation_degrees">
+		</member>
```
Comment (KoBeWi) [inline doc/classes/Control.xml:1054]:
```suggestion
		<member name="rotation_degrees" type="float" setter="set_rotation_degrees" getter="get_rotation_degrees">
			Helper property to access [member rotation] in degrees instead of radians.
		</member>
```
Can be copy-pasted to others.

File: scene/2d/node_2d.cpp (hunk 1 above)
Comment (reduz) [reply scene/2d/node_2d.cpp:157]: yeah you are right, I thought one less function called may be good for performance, but I dont think it should make a difference

Comment (KoBeWi) [reply scene/2d/node_2d.cpp:157]: I think compilers may optimize it to inline call.

**Comment by tinmanjuggernaut** [comment]
Fixes #63390

File: scene/2d/node_2d.cpp (hunk 1 above)
Comment (KoBeWi) [reply scene/2d/node_2d.cpp:157]: You missed a few methods :v

Comment (reduz) [reply scene/2d/node_2d.cpp]: I forgot to commit the changes, sorry :(

File: scene/3d/node_3d.cpp [hunk 3]
```diff
@@ -251,12 +251,22 @@ Vector3 Node3D::get_global_rotation() const {
 	return get_global_transform().get_basis().get_euler();
 }
 
+Vector3 Node3D::get_global_rotation_degrees() const {
+	Vector3 radians = get_global_transform().get_basis().get_euler();
```
Comment (KoBeWi) [inline scene/3d/node_3d.cpp:255]:
```suggestion
	Vector3 radians = get_global_rotation();
```

File: scene/gui/control.cpp [hunk 4]
```diff
@@ -1475,10 +1475,18 @@ void Control::set_rotation(real_t p_radians) {
...
+void Control::set_rotation_degrees(real_t p_degrees) {
+	set_rotation(Math::deg_to_rad(p_degrees));
+}
+
 real_t Control::get_rotation() const {
 	return data.rotation;
 }
 
+real_t Control::get_rotation_degrees() const {
+	return Math::rad_to_deg(data.rotation);
```
Comment (KoBeWi) [inline scene/gui/control.cpp:1487]:
```suggestion
	return Math::rad_to_deg(get_rotation());
```
For consistency mostly.

**Review by KoBeWi — APPROVED** [review]

**Comment by Mickeon** [comment]
There's a whole bit of mess now regarding rotation. What currently being exposed in the Inspector in Godot 4.0 is `rotation` in radians, with the _"radians"_ hint_string, which allows it to be displayed in degrees, all the while showing an incorrect description when being hovered on...

**Comment by reduz** [comment]
@Mickeon This is fine, the main rotation is and will be in radians (even if editing can be done in degrees, because nobody edits those values in radians). The added functions are helpers and are documented as such.

**Comment by akien-mga** [comment]
Thanks!
