### PR TITLE
Fixed completion showing for class members

### LINKED ISSUE #56270: Autocompletion stops on perfect match
### Godot version

28174d5

### System information

W10

### Issue description

When you have a word with perfect match to some identifier, the autocompletion will no longer appear.

Godot
image

VS Code (expected)
image

At least using Ctrl + Space should force the popup.

### Steps to reproduce

1. Type something that perfectly matches some identifier, but also is part of another, longer identifier
2. Try to autocomplete the longer identifier

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by NNesh**
For classes the error showed when token type is unknown, but a list with identifiers for a completion wasn't shown.
This pull request fix this issue #56270

*Bugsquad edit:*
- Fixes #56270.

### CODE REVIEW

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -805,6 +805,8 @@ void GDScriptParser::parse_class_body(bool p_is_multiline) {
 				class_end = true;
 				break;
 			default:
+				// Display a completion with identifiers
```
Comment (akien-mga) [inline modules/gdscript/gdscript_parser.cpp:808]:
```suggestion
				// Display a completion with identifiers.
```

Comment (NNesh) [reply modules/gdscript/gdscript_parser.cpp]: Changed.

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
