### PR TITLE
Make terrain painting not change neighbors centers bits

### LINKED ISSUE #67143: Placing terrain tile clears adjacent non-terrain tiles
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Linux (Pop OS), NVIDIA GeForce RTX 2060, Video Drive v 470.141.03

TileMapBugScreenshot

### Issue description

If you place a terrain tile, any non-terrain tiles in the adjacent bit-checked cells get cleared out.

ex: 
  - For a 'Check sides' terrain, the N,W,S, and E tiles get cleared
  - For a 'Check sides and corners' terrain, all 8 adjacent tiles get cleared.

This happens both in the editor and in code.

I would expect that placing a terrain tile would only affect adjacent terrain tiles, and not tiles from other terrains or non-terrain tiles.

### Steps to reproduce

1) Create a terrain set in a TileSet
2) Create at least one non-terrain tile in the same TileSet
3) Place some non-terrain tiles
4) Place terrain tiles adjacent to the non-terrain tiles

### Minimal reproduction project

[TileTerrainBugRepro.zip](https://github.com/godotengine/godot/files/9741942/TileTerrainBugRepro.zip)

### PR DESCRIPTION
**Pull request by groud**
This changes two things:
- The terrain painting algorithm will now never change a neighbor's tile center bit, or the bits that are not touching a painted tile. So here painting the dark green tile can only modify the bits with the green check marks (sorry for my art skills):
better_terrain
- The terrain painting algorithm only changes the tiles you are painting on and should not erase tiles if not transition tile was found. On this video example, the dark mud terrain is not part of any terrain.

https://user-images.githubusercontent.com/6093119/195822211-8702100f-4660-4012-868c-1aacb7ba499d.mp4

Fixes https://github.com/godotengine/godot/issues/67143
Partially solves https://github.com/godotengine/godot-proposals/issues/5575

### CODE REVIEW

File: editor/plugins/tiles/tile_map_editor.cpp [hunk 1]
```diff
@@ -2348,27 +2348,27 @@ HashMap<Vector2i, TileMapCell> TileMapEditorTerrainsPlugin::_draw_terrain_path_o
...
-					if (tile_data && tile_data->get_terrains_pattern() == E.value) {
-						keep_old = true;
+					if (tile_data && tile_data->get_terrain_set() == p_terrain_set) {
+						in_map_terrain_pattern = tile_data->get_terrains_pattern();
 					}
 				}
 			}
-			if (!keep_old) {
-				output[E.key] = tile_set->get_random_tile_from_terrains_pattern(p_terrain_set, E.value);
+			if (!(in_map_terrain_pattern == kv.value)) {
```
Comment (KoBeWi) [inline editor/plugins/tiles/tile_map_editor.cpp:2370]:
```suggestion
			if (in_map_terrain_pattern != kv.value) {
```

File: scene/2d/tile_map.cpp [hunk 2]
```diff
@@ -2627,14 +2656,38 @@ void TileMap::set_cells_terrain_connect(int p_layer, TypedArray<Vector2i> p_cell
...
+				TileSetAtlasSource *atlas_source = Object::cast_to<TileSetAtlasSource>(source);
+				if (atlas_source) {
+					// Get tile data.
+					TileData *tile_data = atlas_source->get_tile_data(cell.get_atlas_coords(), cell.alternative_tile);
+					if (tile_data && tile_data->get_terrain_set() == p_terrain_set) {
+						in_map_terrain_pattern = tile_data->get_terrains_pattern();
+					}
+				}
+			}
+			if (!(in_map_terrain_pattern == kv.value)) {
```
Comment (KoBeWi) [inline scene/2d/tile_map.cpp:2686]: Here too.

**Review by KoBeWi — APPROVED** [review]
I'm not really versed in the terrain code, but seems ok (aside from style comments I left).

File: editor/plugins/tiles/tile_map_editor.cpp (hunk 1 above)
Comment (groud) [reply editor/plugins/tiles/tile_map_editor.cpp:2370]: No this does not work as the `!=` operator is not defined for TerrainPattern. I can add it though, I guess it's a not impossible define it as the inverse of `==`

Comment (KoBeWi) [reply editor/plugins/tiles/tile_map_editor.cpp:2370]: Yeah I think that would be better. Negating `==` looks just weird.

Comment (KoBeWi) [inline editor/plugins/tiles/tile_map_editor.cpp:2370]: You missed this one.

**Review by clayjohn — APPROVED** [review]

**Comment by clayjohn** [comment]
Code looks good to me and groud is the boss of Tilemap anyway, so let's merge and see how it goes :)
