### PR TITLE
Fix Project Settings array/dicts initial value being shared instances of the current value.

### LINKED ISSUE #55856: ProjectSettings' initial array/dict values can be modified.
### Godot version

master

### System information

Win10

### Issue description

I found ProjectSettings' initial values can be modified if they are arrays. You can get the initial array reference by `ProjectSettings.get()` and modify it. 

It causes that when you modify it in Project Settings dialog, the initial value also changes. So it cannot revert and won't be saved in `project.godot`. This related to #55721.

### Case 1:

Open `Project Settings` dialog, find `editor/script/search_in_file_extensions` property (it is `PackedStringArray`), change it and the revert button won't show.

image

Create a plugin to test its initial value:
```GDScript
@tool
extends EditorPlugin

func _enter_tree():
    print(ProjectSettings.property_get_revert("editor/script/search_in_file_extensions"))
    # will prints [gd, gdshader, 123, 456]
```

### Case 2:
Modify the property directly in plugin:
```GDScript
@tool
extends EditorPlugin

func _enter_tree():
    var array = ProjectSettings.get("editor/script/search_in_file_extensions")
    array.append("123")
    var init = ProjectSettings.property_get_revert("editor/script/search_in_file_extensions")
    print(array, init) # will prints the same array
```

### Case 3:

Reproduce #55721. Modify any default input action:
image

Print its initial value:
```GDScript
@tool
extends EditorPlugin

func _enter_tree():
    for event in ProjectSettings.property_get_revert("input/ui_accept").events:
        print(event)
#    will prints:
#    InputEventKey: keycode=16777221 (Enter), ...
#    InputEventKey: keycode=16777222 (Kp Enter), ...
#    InputEventKey: keycode=32 (Space), ...
# -> InputEventKey: keycode=71 (G), ...
```
That's why it can't affect the runtime....

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by EricEzaM**
Fixes #55856

There could be other ways to fix the issue, but this works. The issue originates here:

https://github.com/godotengine/godot/blob/3c9bf4bc210a8e6a208f30ca59de4d4d7e18c04d/core/config/project_settings.cpp#L1035-L1042

`->set(...)` is done with same same value passed into `->set_initial_value(...)`, so for arrays and dicts that will be the same instance. Thus when you change the project setting value, it changes the initial too, so you can't revert or detect changes when saving.

The change in `ProjectSettings::_property_get_revert(...)` is required for the same reason, if you just return `initial` there, you will be changing the initial array/dict.

Tested with `editor/script/search_in_file_extensions` and various built-in input map inputs.

### CODE REVIEW

**Comment by reduz** [comment]
This looks ok to me on the ProjectSettings side, but I am not familiar with the action editor. Maybe @groud wants to review?

File: editor/project_settings_editor.cpp [hunk 1]
```diff
@@ -370,17 +370,7 @@ void ProjectSettingsEditor::_action_edited(const String &p_name, const Dictionar
 
 	} else {
 		// Events changed
-		int act_event_count = ((Array)p_action["events"]).size();
-		int old_event_count = ((Array)old_val["events"]).size();
-
-		if (act_event_count == old_event_count) {
```
Comment (groud) [inline editor/project_settings_editor.cpp:376]: Why remove that ? More precise messages are welcome.

Comment (EricEzaM) [reply editor/project_settings_editor.cpp:376]: Because I don't think it is an accurate reflection of what happneded 100% of the time now. Say you have 5 events which are all different to the defaults. Then you reset to default. What happened technically is you just removed 3 events and changed 2 events. But with this message it would just say 'Remove Input Action Event' - which is not accurate as more than one was removed and 2 others were changed.

Eaiser to just make it a generic message imo

**Comment by akien-mga** [comment]
It's not clear to me what the editor-side changes are doing. Isn't the duplication in ProjectSettings enough to prevent sharing the array/dicts?

**Review by akien-mga — APPROVED** [review]
Tentatively approving to keep track of it / merge for 4.0.

**Comment by EricEzaM** [comment]
Previously you could not revert to default for the default shortcuts/actions. This pr allows you to do that. Did you want me to split it into two PRs perhaps?

**Comment by akien-mga** [comment]
> Previously you could not revert to default for the built in shortcuts/actions. This pr allows you to do that. Did you want me to split it into two PRs perhaps? They are stored in arrays hence the relevance but I Can see how it might be out of the scope for solving the issue specifically.

No it's fine as is, it was just not obvious to me from the description.

**Comment by akien-mga** [comment]
Thanks!
