### PR TITLE
Edit font properties on multiple objects at once

### LINKED ISSUE #57398: (4.0) Can't edit font size on multiple objects at once
### Godot version

4.0 alpha 1

### System information

Windows 11

### Issue description

This is not so much bug but kinda lack of cohesion. For example if i select multiple Label nodes I can modify they modulation and other properties. Simply make change on X nodes at a time.

But if I pick multiple labels. New font menu at the top dissapear and if I want to change font size I need to do it one by one.

One Label:
image

Multiple Labels:
image

### Steps to reproduce

Simply select multiple Labels.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by NeilKleistGao**
Allow editing font properties on multiple objects at once, including font sizes, colors and so on.
related issue: #57398 

Here are some final results on my PC:

*Bugsquad edit:* Fixes #57398.

### CODE REVIEW

**Review by bruvzg — CHANGES_REQUESTED** [review]
`edited_font` and other `edited_{property}` should be local variables to the loop they are used in, since they depend on the control type.

Also, `void TextControlEditor::_clear_formatting()` should have
```c++
    // Get override names.
    if (edited_control->is_class("RichTextLabel")) {
        edited_color = "default_color";
        edited_font = "normal_font";
        edited_font_size = "normal_font_size";
    } else {
        edited_color = "font_color";
        edited_font = "font";
        edited_font_size = "font_size";
    }
```
on each loop iteration.

**Review by bruvzg — APPROVED** [review]

File: editor/plugins/text_control_editor_plugin.cpp [hunk 1]
```diff
@@ -121,78 +122,162 @@ void TextControlEditor::_update_styles_menu() {
...
+		int count = edited_controls.size();
+		for (int i = 0; i < count; ++i) {
+			Control *edited_control = edited_controls[i];
+
+			String edited_color;
+			String edited_font;
+			String edited_font_size;
+
+			// Get override names.
+			if (edited_control->is_class("RichTextLabel")) {
```
Comment (akien-mga) [inline editor/plugins/text_control_editor_plugin.cpp:151]: It's better to cast instead of relying on strings:
```suggestion
			if (Object::cast_to<RichTextLabel>(edited_control)) {
```

File: editor/plugins/text_control_editor_plugin.cpp [hunk 2]
```diff
@@ -121,78 +122,162 @@ void TextControlEditor::_update_styles_menu() {
...
+					same_font = same_font && (font_selected == FONT_INFO_THEME_DEFAULT);
+					same_style = same_style && (style_selected == 0);
+				}
+
+				font_selected = FONT_INFO_THEME_DEFAULT;
+				style_selected = 0;
 			}
+
+			int current_font_size = edited_control->get_theme_font_size(edited_font_size);
+			int current_outline_size = edited_control->get_theme_constant("outline_size");
```
Comment (akien-mga) [inline editor/plugins/text_control_editor_plugin.cpp:223]: This (and line 225) can wrap the string literal in `SNAME` to get a statically allocated StringName instead of an implicit coercion.

File: editor/plugins/text_control_editor_plugin.cpp [hunk 3]
```diff
@@ -292,18 +406,30 @@ void TextControlEditor::_outline_size_selected(double p_size) {
...
-	if (edited_control->has_theme_color_override(edited_color)) {
-		ur->add_undo_method(edited_control, "add_theme_color_override", edited_color, edited_control->get_theme_color(edited_color));
-	} else {
-		ur->add_undo_method(edited_control, "remove_theme_color_override", edited_color);
+	int count = edited_controls.size();
+	for (int i = 0; i < count; ++i) {
+		Control *edited_control = edited_controls[i];
+
+		String edited_color;
+		if (edited_control->is_class("RichTextLabel")) {
```
Comment (akien-mga) [inline editor/plugins/text_control_editor_plugin.cpp:421]: Same here, can use casting.

File: editor/plugins/text_control_editor_plugin.cpp [hunk 4]
```diff
@@ -121,78 +122,162 @@ void TextControlEditor::_update_styles_menu() {
...
+
+			String edited_color;
+			String edited_font;
+			String edited_font_size;
+
+			// Get override names.
+			if (edited_control->is_class("RichTextLabel")) {
+				edited_color = "default_color";
+				edited_font = "normal_font";
+				edited_font_size = "normal_font_size";
```
Comment (akien-mga) [inline editor/plugins/text_control_editor_plugin.cpp:154]: To be confirmed, but I think these could be changed to be wrapped with `SNAME()` (and defined as `StringName` instead of `String`) to reuse preallocated StringNames for performance.

File: editor/plugins/text_control_editor_plugin.cpp [hunk 5]
```diff
@@ -205,42 +290,54 @@ void TextControlEditor::_font_style_selected(int p_id) {
...
-			style = "Default";
+	int count = edited_controls.size();
+	for (int i = 0; i < count; ++i) {
+		Control *edited_control = edited_controls[i];
+
+		String edited_font;
+		if (edited_control->is_class("RichTextLabel")) {
+			edited_font = "normal_font";
+		} else {
+			edited_font = "font";
```
Comment (akien-mga) [inline editor/plugins/text_control_editor_plugin.cpp:308]: Same here:
```suggestion
		StringName edited_font;
		if (Object::cast_to<RichTextLabel>(edited_control)) {
			edited_font = SNAME("normal_font");
		} else {
			edited_font = SNAME("font");
```

File: editor/plugins/text_control_editor_plugin.cpp [hunk 6]
```diff
@@ -205,42 +290,54 @@ void TextControlEditor::_font_style_selected(int p_id) {
...
-				Ref<Font> font;
-				font.instantiate();
-				font->add_data(fd);
-				ur->add_do_method(edited_control, "add_theme_font_override", edited_font, font);
+		if (font_list->get_selected_id() == FONT_INFO_THEME_DEFAULT) {
+			// Remove font override.
+			ur->add_do_method(edited_control, "remove_theme_font_override", edited_font);
+		} else if (font_list->get_selected_id() == FONT_INFO_USER_CUSTOM) {
+			// Restore "custom_font".
+			ur->add_do_method(edited_control, "add_theme_font_override", edited_font, custom_font);
```
Comment (akien-mga) [inline editor/plugins/text_control_editor_plugin.cpp:316]:
```suggestion
			ur->add_do_method(edited_control, SNAME("remove_theme_font_override"), edited_font);
		} else if (font_list->get_selected_id() == FONT_INFO_USER_CUSTOM) {
			// Restore "custom_font".
			ur->add_do_method(edited_control, SNAME("add_theme_font_override"), edited_font, custom_font);
```

File: editor/plugins/text_control_editor_plugin.cpp [hunk 7]
```diff
@@ -205,42 +290,54 @@ void TextControlEditor::_font_style_selected(int p_id) {
...
+				style = "Default";
+			}
+
+			if (fonts.has(name)) {
+				Ref<FontData> fd = ResourceLoader::load(fonts[name][style]);
+				if (fd.is_valid()) {
+					Ref<Font> font;
+					font.instantiate();
+					font->add_data(fd);
+					ur->add_do_method(edited_control, "add_theme_font_override", edited_font, font);
```
Comment (akien-mga) [inline editor/plugins/text_control_editor_plugin.cpp:331]:
```suggestion
					ur->add_do_method(edited_control, SNAME("add_theme_font_override"), edited_font, font);
```
etc. for other string literals passed when `StringName` is expected.

**Comment by akien-mga** [comment]
All my above review comments seem to relate to pre-existing code which is just being moved around, so it shouldn't be blocking for this PR. But a follow-up PR cleaning the code in this class following my comments would be great :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by seppoday** [comment]
Thank you!
