### PR TITLE
Acquire MulticastLock on Android when using broadcast/multicast

### LINKED ISSUE #24666: UDP Broadcasting not received on all Android devices
**Godot version:**
Master branch
Pulled 15th December 2018

**OS/device including version:**

**Issue description:**
Using PacketPeerUDP to broadcast on 255.255.255.255 to other clients who are listening with:

```
func _process():
   while udp.get_available_packet_count() > 0:
      var pkt = udp.get_var()
       if str(pkt) == "whatever":
         server_ip = udp.get_packet_ip()
```
This works well on some Android devices, but it does not work on others. Some devices do not receive any packets at all. One device seems to work on one WiFi router but not on others. The problem is a bit random. I have the following permissions set on Android export:

INTERNET
ACCESS_NETWORK_STATE
CHANGE_WIFI_MULTICAST_STATE

Looking around on the web, it is a common problem and it could be the same issue as this post:
https://pzoleeblogen.wordpress.com/2014/03/04/android-udp-broadcast-message-is-not-received/

i.e. Maybe Godot needs a way of adding a "MulticastLock"?

**Steps to reproduce:**

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by Faless**
Some android devices require that the application acquire a "MulticastLock" if they want to receive broadcast/multicast traffic on android.

In this PR, we try to do that automatically when needed.

- Added a new `NetSocketAndroid` class that extends `NetSocketPosix` so it can intercept calls to `set_broadcasting_enabled` and `[join|leave]_multicast_group` and acquire/release the lock accordingly.
- The lock is reference counted,
- Added a new method `set_broadcast_enabled` in `PacketPeerUDP`.
- **Broadcast is now OFF by default** (this is a breaking change from `3.1`), users willing to keep using broadcast will need to call `PacketPeerUDP.set_broadcast_enabled`. (Note, when broadcast is disabled you cannot _send_ broadcast packets, but you might still receive them).

Fixes #24666

EDIT: Permission `CHANGE_WIFI_MULTICAST_STATE` is required to acquire the lock. If the app does not have that permission (checked during setup) the lock will not work.

### CODE REVIEW

File: platform/android/os_android.cpp [hunk 1]
```diff
@@ -106,6 +107,9 @@ void OS_Android::initialize_core() {
 		DirAccess::make_default<DirAccessJAndroid>(DirAccess::ACCESS_RESOURCES);
 	DirAccess::make_default<DirAccessUnix>(DirAccess::ACCESS_USERDATA);
 	DirAccess::make_default<DirAccessUnix>(DirAccess::ACCESS_FILESYSTEM);
+#ifndef NO_NETWORK
```
Comment (akien-mga) [inline platform/android/os_android.cpp]: Another undocumented define probably introduced for proprietary ports... We'll really have to document all this for 4.0 and review whether they all make sense (and maybe give them more consistent names).

File: drivers/unix/net_socket_posix.cpp [hunk 2]
```diff
@@ -335,7 +335,7 @@ Error NetSocketPosix::open(Type p_sock_type, IP::Type &ip_type) {
 
 	if (protocol == IPPROTO_UDP && ip_type != IP::TYPE_IPV6) {
 		// Enable broadcasting for UDP sockets if it's not IPv6 only (IPv6 has no broadcast option).
-		set_broadcasting_enabled(true);
+		set_broadcasting_enabled(false);
```
Comment (akien-mga) [inline drivers/unix/net_socket_posix.cpp]: The comment is no longer valid. I guess the `if` condition isn't either, it could be a plain `set_broadcasting_enabled(false);` by default (if it's not already false).

File: core/io/net_socket.h [hunk 3]
```diff
@@ -69,7 +69,7 @@ class NetSocket : public Reference {
 	virtual bool is_open() const = 0;
 	virtual int get_available_bytes() const = 0;
 
-	virtual void set_broadcasting_enabled(bool p_enabled) = 0;
+	virtual Error set_broadcasting_enabled(bool p_enabled) = 0;
```
Comment (akien-mga) [inline core/io/net_socket.h]: Could you also sync the docs, and possibly document possible return values and their meaning?

File: platform/android/os_android.cpp (hunk 1 above)
Comment (Faless) [reply platform/android/os_android.cpp]: Yeah, in the old times we used to be able to compile without network support. I added it there for future reference (importing it from `OS_Unix`)

**Comment by Faless** [comment]
Meh, now spits error when running IPv6. Will need some extra work

**Comment by Faless** [comment]
Okay, should be ready now.

File: drivers/unix/net_socket_posix.cpp [hunk 4]
```diff
@@ -333,9 +333,10 @@ Error NetSocketPosix::open(Type p_sock_type, IP::Type &ip_type) {
 		set_ipv6_only_enabled(ip_type != IP::TYPE_ANY);
 	}
 
-	if (protocol == IPPROTO_UDP && ip_type != IP::TYPE_IPV6) {
-		// Enable broadcasting for UDP sockets if it's not IPv6 only (IPv6 has no broadcast option).
-		set_broadcasting_enabled(true);
+	if (protocol == IPPROTO_UDP) {
+		// Make sure to disable broadcasting for UDP sockets.
+		// Depending on the OS, this option might or might not be enabled by default. Let's normilize it.
```
Comment (m4gr3d) [inline drivers/unix/net_socket_posix.cpp]: Typo on `normilize`.

File: platform/android/java/lib/src/org/godotengine/godot/GodotIO.java [hunk 5]
```diff
@@ -345,6 +349,19 @@ public void dir_close(int id) {
 		//streams = new HashMap<Integer, AssetData>();
 		streams = new SparseArray<AssetData>();
 		dirs = new SparseArray<AssetDir>();
+		hasMulticastLock = false;
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/GodotIO.java]: You should be able to check ownership of the permission directly instead of using this workaround logic.
Check `org.godotengine.godot.utils.PermissionsUtil.java` for reference.

File: platform/android/java/lib/src/org/godotengine/godot/GodotIO.java [hunk 6]
```diff
@@ -55,6 +56,9 @@
 
 	MediaPlayer mediaPlayer;
 
+	WifiManager.MulticastLock multicastLock;
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/GodotIO.java]: Can you create a separate class to host the multicast logic.
For example, you could create a `NetUtils` class in the `org.godotengine.godot.utils` package. Or if you think the net related logic will grow, create a separate `net` package with a `NetManager` or `NetSocket` class to host network related code.

File: platform/android/java_godot_io_wrapper.h [hunk 7]
```diff
@@ -45,6 +45,8 @@ class GodotIOJavaWrapper {
 	jobject godot_io_instance;
 	jclass cls;
 
+	jmethodID _multicast_lock_acquire = 0;
```
Comment (m4gr3d) [inline platform/android/java_godot_io_wrapper.h]: Following the above comments, these would also need to move into a matching wrapper file. It seems the `NetSocketAndroid` would be the prime location. Is there a reason why these are not defined there?

File: platform/android/net_socket_android.cpp [hunk 8]
```diff
@@ -0,0 +1,105 @@
...
+		multicast_groups(0) {
+}
+
+NetSocketAndroid::~NetSocketAndroid() {
+	close();
+}
+
+void NetSocketAndroid::close() {
+	NetSocketPosix::close();
+	if (wants_broadcast)
```
Comment (m4gr3d) [inline platform/android/net_socket_android.cpp]: Seems like these two can be merged (e.g: `wants_broadcast || multicast_groups`. Are there kept separate because of reference counting?

File: platform/android/net_socket_android.cpp [hunk 9]
```diff
@@ -0,0 +1,105 @@
...
+		((OS_Android *)OS::get_singleton())->get_godot_io_java()->multicast_lock_release();
+	if (multicast_groups)
+		((OS_Android *)OS::get_singleton())->get_godot_io_java()->multicast_lock_release();
+	wants_broadcast = false;
+	multicast_groups = 0;
+}
+
+Error NetSocketAndroid::set_broadcasting_enabled(bool p_enabled) {
```
Comment (m4gr3d) [inline platform/android/net_socket_android.cpp]: The logic is very similar for all three methods. Seems like you can merge `wants_broadcast` and `multicast_group` into a single counter and define a private helper method that all three methods call to:

- increment the counter and acquire the multicast lock when joining a multicast group or enabling broadcast.

- decrement the counter and release the multicast lock when leaving a multicast group or disabling broadcast.

File: platform/android/os_android.cpp (hunk 1 above)
Comment (m4gr3d) [reply platform/android/os_android.cpp]: I lack the context, @Faless can you clarify why the `define` is needed?

**Review by m4gr3d — CHANGES_REQUESTED** [review]

**Comment by Faless** [comment]
@m4gr3d update with your suggestion. I hope I understood what you meant correctly.
The multicast logic in Java is now in it's own class. `GodotIO` only funnels the call to the proper `GodotNetUtils` class. Methods and references are no longer in the GodotIO wrapper, but in NetSocketAndroid.

We can't merge `wants_broadcast` and `multicast_groups`, `set_broadcast_enabled` might be called two times with `true` (or 2 times with `false`) and we wouldn't be able to notice that otherwise.

File: platform/android/java/lib/src/org/godotengine/godot/GodotIO.java [hunk 10]
```diff
@@ -338,10 +339,25 @@ public void dir_close(int id) {
 		dirs.remove(id);
 	}
 
+	/////////////////////////
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/GodotIO.java]: Instead of routing through GodotIO, can you instead follow a pattern similar to what we're doing for GodotIO access  in the native code:

- Make `GodotNetUtils netUtils` a static variable in `Godot.java` and initialize there.
- In the `java_godot_lib_jni.cpp` use `godot_java->get_member_object` to get a `jobject` for `GodotNetUtils`.
- Pass that `jobject` to `NetSocketAndroid` directly and use that to setup the `multicastLock*` methods.

File: platform/android/java/lib/src/org/godotengine/godot/utils/GodotNetUtils.java [hunk 11]
```diff
@@ -0,0 +1,70 @@
...
+
+package org.godotengine.godot.utils;
+
+import android.content.Context;
+import android.net.wifi.WifiManager;
+import android.util.Log;
+
+import org.godotengine.godot.Godot;
+
+public class GodotNetUtils {
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/utils/GodotNetUtils.java]: Can you add javadocs for this class.

File: platform/android/java/lib/src/org/godotengine/godot/utils/GodotNetUtils.java [hunk 12]
```diff
@@ -0,0 +1,70 @@
...
+
+	WifiManager.MulticastLock multicastLock;
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/utils/GodotNetUtils.java]: This field should be private.

File: platform/android/java/lib/src/org/godotengine/godot/utils/GodotNetUtils.java [hunk 13]
```diff
@@ -0,0 +1,70 @@
...
+
+	public GodotNetUtils(Godot p_activity) {
+		if (PermissionsUtil.hasManifestPermission(p_activity, "android.permission.CHANGE_WIFI_MULTICAST_STATE")) {
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/utils/GodotNetUtils.java]: In terms of UX, is there any way we want to surface that a key permission is missing?
At the very least, we can log an error.

File: platform/android/java/lib/src/org/godotengine/godot/utils/GodotNetUtils.java [hunk 14]
```diff
@@ -0,0 +1,70 @@
...
+			WifiManager wifi = (WifiManager)p_activity.getApplicationContext().getSystemService(Context.WIFI_SERVICE);
+			multicastLock = wifi.createMulticastLock("GodotMulticastLock");
+			multicastLock.setReferenceCounted(true);
+		}
+	}
+
+	public void multicastLockAcquire() {
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/utils/GodotNetUtils.java]: Can you add javadocs for this and the `multicastLockRelease` method.

File: platform/android/java/lib/src/org/godotengine/godot/utils/PermissionsUtil.java [hunk 15]
```diff
@@ -161,6 +161,18 @@ public static boolean requestManifestPermissions(Godot activity) {
 		return dangerousPermissions.toArray(new String[0]);
 	}
 
+	public static boolean hasManifestPermission(Godot activity, String permission) {
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/utils/PermissionsUtil.java]: Can you add javadocs for this method.

File: platform/android/net_socket_android.h [hunk 16]
```diff
@@ -0,0 +1,69 @@
...
+/*************************************************************************/
+
+#ifndef NET_SOCKET_ANDROID_H
+#define NET_SOCKET_ANDROID_H
+
+#include "drivers/unix/net_socket_posix.h"
+
+#include <jni.h>
+
+class NetSocketAndroid : public NetSocketPosix {
```
Comment (m4gr3d) [inline platform/android/net_socket_android.h]: Can you add some documentation for the class.

**Review by m4gr3d — CHANGES_REQUESTED** [review]

**Comment by m4gr3d** [comment]
> @m4gr3d update with your suggestion. I hope I understood what you meant correctly.
> The multicast logic in Java is now in it's own class. `GodotIO` only funnels the call to the proper `GodotNetUtils` class. Methods and references are no longer in the GodotIO wrapper, but in NetSocketAndroid.
> 
> We can't merge `wants_broadcast` and `multicast_groups`, `set_broadcast_enabled` might be called two times with `true` (or 2 times with `false`) and we wouldn't be able to notice that otherwise.

@Faless Thanks for the clarification and the update to the code! I've added some additional feedback. Let me know if you have any questions.

**Comment by Faless** [comment]
> Instead of routing through GodotIO, can you instead follow a pattern similar to what we're doing for GodotIO access in the native code:

Is it worth it to have an extra object around (the only extra object beside GodotIO) just for 2 functions? If the answer is yes, why aren't we doing already the same thing dividing files/directories/audio/miscellaneous? I honestly think having my an extra object around is a bad idea. It's inconsistent with what we are doing for everything else, and honestly strange, given that networking (sockets) is inside core/io/ so it makes sense for it to be in GodotIO, much more sense than audio stuff...

**Comment by m4gr3d** [comment]
> > Instead of routing through GodotIO, can you instead follow a pattern similar to what we're doing for GodotIO access in the native code:
> 
> Is it worth it to have an extra object around (the only extra object beside GodotIO) just for 2 functions? If the answer is yes, why aren't we doing already the same thing dividing files/directories/audio/miscellaneous? I honestly think having an extra object around is a bad idea. It's inconsistent with what we are doing for everything else, and honestly strange, given that networking (sockets) is inside core/io/ so it makes sense for it to be in GodotIO, much more sense than audio stuff...

I'm not sure I follow. The extra object is already there, except that it's within GodotIO for now. What we're doing here is just moving the reference from GodotIO to Godot, so technically nothing changes, but the code is a lot more readable, concise, easy to understand and modify.

Regarding files/directories/audio/miscellaneous code inside GodotIO that you're referring to, I can't speak to that since this was done before I joined the Android maintainers, but it's fair to say that GodotIO, at 600+ LOCs, could benefit to have its internal code split up and organized in packages/classes. That is not an urgent issue, so that cleanup is at the bottom of my list (VR, Android plugins, and app bundles for example are higher priority) but I'll eventually get to it.
In the meantime, I try to ensure that new code doesn't exacerbate the issue, hence why having the net code in its own classes.

Let me know if you have any questions/feedback.

**Comment by Faless** [comment]
> I'm not sure I follow. The extra object is already there, except that it's within GodotIO for now

Yeah, right, I meant an extra reference in GodotLib, the only extra reference beside GodotIO.

I still think this makes everything more spaghetti and harder to read, but if that's the direction you think we should go, I trust your judgement, I'll change my PR.

File: platform/android/java/lib/src/org/godotengine/godot/utils/GodotNetUtils.java (hunk 13 above)
Comment (Faless) [reply platform/android/java/lib/src/org/godotengine/godot/utils/GodotNetUtils.java]: We could, it's worth noticing though, that 90% of the devices will work just fine without that permission. Only a handful of devices (for what I managed to test) seem to implement that packet filtering.

**Comment by Faless** [comment]
@m4gr3d should be ready now. Thanks for your feedback.

**Comment by m4gr3d** [comment]
> > I'm not sure I follow. The extra object is already there, except that it's within GodotIO for now
> 
> Yeah, right, I meant an extra reference in GodotLib, the only extra reference beside GodotIO.
> 
> I still think this makes everything more spaghetti and harder to read, but if that's the direction you think we should go, I trust your judgement, I'll change my PR.

@Faless I was referring to adding a reference in `Godot.java`. I had forgotten about the `GodotIO` reference in `GodotLib` and after looking it up it doesn't look like it's needed anymore, and might be safe to delete. 

In the native side (`java_godot_lib_jni`), nothing extra needs to be added since we can access the new reference `jobject` via `get_member_object` on the `GodotJavaWrapper` and pass that directly to `NetSocketAndroid::setup`.

**Comment by Faless** [comment]
>  I had forgotten about the `GodotIO` reference in `GodotLib` and after looking it up it doesn't look like it's needed anymore

I've noticed, it should be ready for review, I've added the reference in `Godot.java` only.

**Review by m4gr3d — APPROVED** [review]
Looks great, thanks for the updates!

**Comment by akien-mga** [comment]
Thanks to both of you :)
