### PR TITLE
Fix 3d animations doesn't play

### LINKED ISSUE #51990: 3D Animations doesn't play
### Godot version

4.0 dev 2daef0400

### System information

Windows 10

### Issue description

The error happens on this line:
`quaternion.cpp:107 The start quaternion must be normalized.`

### Steps to reproduce

1. Import some 3d model with animation
1. Add to the scene
1. Open Animation Player in model node
1. Click "play selected animation from start" or "play selected animation from current pos"

### Minimal reproduction project

No need

### PR DESCRIPTION
**Pull request by requizm**
Fix #51990
Related #51785

https://user-images.githubusercontent.com/12533045/130366789-190fb915-b5c2-40a0-b2d3-0fa200c8d1e5.mp4

### CODE REVIEW

**Comment by YeldhamDev** [comment]
A comment to explain the magic numbers would be nice.

**Comment by requizm** [comment]
> A comment to explain the magic numbers would be nice.

12 = TransformKey variable count (10) + Key variable count (2)
4 = sizeof(real_t)  //means float

**Comment by YeldhamDev** [comment]
> > A comment to explain the magic numbers would be nice.
> 
> 12 = TransformKey variable count (10) + Key variable count (2)
> 4 = sizeof(real_t) //means float

I meant a comment within the code. :stuck_out_tongue:

File: scene/resources/animation.cpp [hunk 1]
```diff
@@ -83,9 +83,11 @@ bool Animation::_set(const StringName &p_name, const Variant &p_value) {
 
 				const real_t *r = values.ptr();
 
-				tt->transforms.resize(vcount / 12);
+				//12 = TransformKey variable count (10) + Key variable count (2)
+				//4 = sizeof(real_t)
+				tt->transforms.resize(vcount / (12 * 4));
```
Comment (qarmin) [inline scene/resources/animation.cpp:88]: What if `real_t` will be double not float?

Comment (requizm) [reply scene/resources/animation.cpp]: Check again. I did the same usage in the `_get` function

File: scene/resources/animation.cpp [hunk 2]
```diff
@@ -83,9 +83,11 @@ bool Animation::_set(const StringName &p_name, const Variant &p_value) {
...
 
-				tt->transforms.resize(vcount / 12);
+				int transform3d_size = (int)sizeof(Transform3D);
 
-				for (int i = 0; i < (vcount / 12); i++) {
+				tt->transforms.resize(vcount / transform3d_size);
+
+				for (int i = 0; i < (vcount / transform3d_size); i++) {
 					TKey<TransformKey> &tk = tt->transforms.write[i];
 					const real_t *ofs = &r[i * 12];
```
Comment (fire) [inline scene/resources/animation.cpp:92]: I wonder if all the 12 constants should be replaced.

Comment (requizm) [reply scene/resources/animation.cpp:92]: Maybe we should add something like this: `(sizeof(Quaternion) / sizeof(real_t)) + (sizeof(Vector3) / sizeof(real_t)) + (sizeof(Vector3) / sizeof(real_t)) + 2`

Comment (fire) [reply scene/resources/animation.cpp:92]: Are we replacing the 12 valued constants?

Comment (requizm) [reply scene/resources/animation.cpp:92]: Yes. For the readability, we can replace.
Example:
`int transform3d_var_count = 12`
or
`int transform3d_var_count = (sizeof(Quaternion) / sizeof(real_t)) + (sizeof(Vector3) / sizeof(real_t)) + (sizeof(Vector3) / sizeof(real_t)) + 2`

But this is not related to this issue, we need to push another commit/pr

**Review by fire — APPROVED** [review]
Looks good to me.

File: scene/resources/animation.cpp [hunk 3]
```diff
@@ -83,9 +83,11 @@ bool Animation::_set(const StringName &p_name, const Variant &p_value) {
 
 				const real_t *r = values.ptr();
 
-				tt->transforms.resize(vcount / 12);
+				int transform3d_size = (int)sizeof(Transform3D);
 
-				for (int i = 0; i < (vcount / 12); i++) {
+				tt->transforms.resize(vcount / transform3d_size);
+
+				for (int i = 0; i < (vcount / transform3d_size); i++) {
```
Comment (aaronfranke) [inline scene/resources/animation.cpp:90]: Why not just make the value have the division already in it?

```cpp
const int transform3d_count = vcount / sizeof(Transform3D);
tt->transforms.resize(transform3d_count);
for (int i = 0; i < transform3d_count; i++) {
```

File: scene/resources/animation.cpp (hunk 2 above)
Comment (aaronfranke) [reply scene/resources/animation.cpp:92]: @requizm Transform3D doesn't contain Quaternion, it contains one Basis and one separate Vector3 for the origin.

Comment (fire) [reply scene/resources/animation.cpp:92]: sizeof(Basis) is 9 floats vs sizeof(Quaternion) which is 4 floats.

**Comment by aaronfranke** [comment]
> 12 = TransformKey variable count (10) + Key variable count (2)
> 4 = sizeof(real_t)  //means float

Do not assume that `sizeof(real_t)` is 4, it can be 8 if Godot is compiled with real_t defined as double.

File: scene/resources/animation.cpp (hunk 2 above)
Comment (aaronfranke) [reply scene/resources/animation.cpp:92]: @requizm This code is quite confusing actually because `transform3d_var_count` is not the variable count of `Transform3D`, it is the variable count of `TransformKey`'s members plus `Key`'s `transition` and `time`.

File: scene/resources/animation.cpp (hunk 3 above)
Comment (requizm) [reply scene/resources/animation.cpp:90]: Cause i don't want to make a refactor. I just fix the issue. Refactor should be different commit with commit message. (also unrelated to this issue)

**Comment by aaronfranke** [comment]
@requizm `sizeof(Transform3D)` is actually the size in bytes (either 48 or 96). It's likely that this PR breaks something.

**Comment by fire** [comment]
It's a late night so I'll leave a pointer to my pr in testing https://github.com/V-Sekai/godot/tree/anim-length

**Comment by requizm** [comment]
> @requizm `sizeof(Transform3D)` is actually the size in bytes (either 48 or 96). It's likely that this PR breaks something.

Yes, sizeof returns byte. 

If we define real_t as float, it will be 48. Everything perfectly working for float.

If we define real_t as double, it will be 96. Everything perfectly should work for double too. I don't understand how it broke.

File: scene/resources/animation.cpp (hunk 2 above)
Comment (requizm) [reply scene/resources/animation.cpp:92]: > transition

You're right. Bad naming.

**Comment by nonunknown** [comment]
this error is still reproduceable in: v4.0.dev.20210916.official [104a6191f]


https://user-images.githubusercontent.com/58845030/133887578-00bc1c01-fc5d-4a83-8fd2-8c0bd2bd9dbe.mp4

**Comment by requizm** [comment]
@nonunknown 
Well, seems like broken again. The parts I changed were changed again like this last time. 
https://github.com/godotengine/godot/commit/ffe54af0db209fb8c2dfd22c71c617fe92975590   author @fire 
Maybe it's relevant. I don't know. 
I can check that part in the next days

**Comment by fire** [comment]
Will look into it
