### PR TITLE
[TextEdit] Improve block/insert caret drawing.

### LINKED ISSUE #50245: Text Editor's block_caret options when enabled has wrong offset
### Godot version

v4.0.dev.custom_build [cb4e42155]

### System information

manjaro Gnome 21, AMD R7 200 series, Intel i3 3.0 GHZ,8GB RAM

### Issue description

When the user enables block_caret option, it has wrong offset:

image

over non-empty lines is fine:
image

over empty lines it has wrong offset:
image

### Steps to reproduce

* Click Editor
* Editor Settings
* Text Editor
* Cursor
* block_caret
* Enable it!

### Minimal reproduction project

N/a

### PR DESCRIPTION
**Pull request by bruvzg**
Fix block caret alignment on empty line:
empty

Fix block caret width, when the logical end of the line is visually in the middle:
endl

Add secondary caret indicator:
sec

Always draw insert caret as solid box.
solid

Fixes #50245

### CODE REVIEW

**Comment by VedatGunel** [comment]
When insert mode is enabled, it shows the block caret on empty lines. Other than that, everyhings seems to work well.
Animation

**Comment by bruvzg** [comment]
> When insert mode is enabled, it shows the block caret on empty lines.

Fixed.

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -1110,20 +1110,41 @@ void TextEdit::_notification(int p_what) {
...
+											if (l_caret.position.x >= TS->shaped_text_get_size(rid).x) {
+												l_caret.size.x = font->get_char_size('m', 0, font_size).x;
 											} else {
-												l_caret.position.y = -TS->shaped_text_get_ascent(rid);
-												l_caret.size.y = h;
+#ifdef TOOLS_ENABLED
+												l_caret.size.x = 3 * Math::round(EDSCALE);
+#else
+												l_caret.size.x = 3;
+#endif
```
Comment (Paulb23) [inline scene/gui/text_edit.cpp:1141]: Would be possible to `* caret_width` rather then grabbing `EDSCALE`?

Comment (bruvzg) [reply scene/gui/text_edit.cpp:1141]: Yes, `caret_width` is exactly the same as `EDSCALE`. This is for the case on the second screenshot (the logical end of the line is visually in the middle). Caret is set to the smallest size, which still looks like block caret.

**Review by Paulb23 — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
