### PR TITLE
Fix potential integer underflow in rounded up divisions

### LINKED ISSUE #80358: Integer underflows throughout the code when trying to round up
### Godot version

4.2.x master [16a93563bfd3b02ca0a8f6df2026f3a3217f5571]

### System information

Godot v4.2.dev (262d1eaa6) - Ubuntu 20.04.6 LTS (Focal Fossa) - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 6800 XT - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Based on my findings on #80356 I noticed this pattern repeats throghout the code in order to perform integer division that rounds up:

- `compute_list_dispatch(p_list, (p_x_threads - 1) / cl->state.local_group_size[0] + 1, (p_y_threads - 1) / cl->state.local_group_size[1] + 1, (p_z_threads - 1) / cl->state.local_group_size[2] + 1);` in rendering_device_vulkan.cpp
- `(multimesh->instances - 1) / MULTIMESH_DIRTY_REGION_SIZE + 1` in mesh_storage.cpp (GLES3 and Vulkan)
- Possibly `count = ((to - from - 1) / incr) + 1;` & `count = ((from - to - 1) / -incr) + 1` in gdscript_utility_functions.cpp
- `Vector3i group_size((atlas_size.x - 1) / 8 + 1, (atlas_size.y - 1) / 8 + 1, 1)` in lightmapper_rd.cpp (repeats twice)
- lightmapper_rd.cpp
```cpp
int x_regions = (atlas_size.width - 1) / max_region_size + 1;
int y_regions = (atlas_size.height - 1) / max_region_size + 1;
int ray_iterations = (push_constant.ray_count - 1) / max_rays + 1;
```
- Lots more in lightmapper_rd.cpp
- `bitmask.resize((((p_size.width * p_size.height) - 1) / 8) + 1)` in bit_map.cpp
- `cluster_screen_size.width = (p_screen_size.width - 1) / cluster_size + 1;` & `cluster_screen_size.height = (p_screen_size.height - 1) / cluster_size + 1;`  in cluster_builder_rd.cpp
- `push_constant.render_element_count_div_32 = render_element_count > 0 ? (render_element_count - 1) / 32 + 1 : 0;` the code is safe but the check for 0 is not required
- `int x_groups = (p_size.x - 1) / 8 + 1;` & `int y_groups = (p_size.y - 1) / 8 + 1;` copy_effects.cpp
- `uint32_t cluster_screen_width = (p_settings.rb_size.x - 1) / cluster_size + 1;` & `uint32_t cluster_screen_height = (p_settings.rb_size.y - 1) / cluster_size + 1;` in fog.cpp
- `RD::get_singleton()->compute_list_dispatch(compute_list, (rect.size.x - 1) / 8 + 1, (rect.size.y - 1) / 8 + 1, 1);` in gi.cpp
- `compute_list_dispatch(compute_list, (rect.size.x - 1) / 8 + 1, (rect.size.y - 1) / 8 + 1, 1);` in gi.cpp
- `cluster_screen_width = (p_screen_size.width - 1) / p_render_data->cluster_size + 1;` & `cluster_screen_height = (p_screen_size.height - 1) / p_render_data->cluster_size + 1;` in render_forward_clustered.cpp

Whenever the code wants to round up, it performs `x = (x - 1) / y + 1` when it should be doing `x = (x + y - 1) / y`

The original code when the input is 0 is wrong for both unsigned (produces a very large value) and signed (produces 1 instead of 0)

This version handles 0 properly.  (x / y = 0).

e.g.

- 0 / 64 = 0
- 63 / 64 = 1
- 64 / 64 = 1
- 65 / 64 = 2

Mathematically they're the same:

```cpp
= (x - 1) / y + 1
= (x - 1) / y + y / y
= (x + y - 1) / y
```

However in terms of computer science, they're not

If no one objects I'll submit a PR next weekend.

### Steps to reproduce

None, this is a chronic problem spread out throghout the code.

See #80286 for an example of a repro.

### Minimal reproduction project

See #80286

### PR DESCRIPTION
**Pull request by EddieBreeg**
A new division_round_up function was added in the Math class, allowing for easy and correct computation of integer divisions when the result needs to be rounded up.
https://github.com/EddieBreeg/godot/blob/8349f16f316b90f705da1219f52828a0af889907/core/math/math_funcs.h#L190-L201

* *Bugsquad edit, fixes: #80358*

### CODE REVIEW

**Comment by AThousandShips** [comment]
To link it use "fixes", also don't write "bugsquad", that means it was added by one of the members of that team

**Comment by EddieBreeg** [comment]
Alright thanks. I had written the "fixes" keyword though so I'm still not sure what github expects?

File: core/math/math_funcs.h [hunk 1]
```diff
@@ -187,6 +187,19 @@ class Math {
...
+		return (num + den - 1) / den;
+	}
+	static _ALWAYS_INLINE_ uint32_t division_round_up(uint32_t num, uint32_t den) {
+		return (num + den - 1) / den;
+	}
+	static _ALWAYS_INLINE_ int64_t division_round_up(int32_t num, int64_t den) {
+		return (num + den - 1) / den;
+	}
+	static _ALWAYS_INLINE_ uint64_t division_round_up(uint32_t num, uint64_t den) {
+		return (num + den - 1) / den;
```
Comment (AThousandShips) [inline core/math/math_funcs.h:200]:
```suggestion
	static _ALWAYS_INLINE_ int32_t division_round_up(int32_t p_num, int32_t p_den) {
		return (p_num + p_den - 1) / p_den;
	}
	static _ALWAYS_INLINE_ uint32_t division_round_up(uint32_t p_num, uint32_t p_den) {
		return (p_num + p_den - 1) / p_den;
	}
	static _ALWAYS_INLINE_ int64_t division_round_up(int32_t p_num, int64_t p_den) {
		return (p_num + p_den - 1) / p_den;
	}
	static _ALWAYS_INLINE_ uint64_t division_round_up(uint32_t p_num, uint64_t p_den) {
		return (p_num + p_den - 1) / p_den;
```
Arguments are prefixed with `p_`

**Comment by AThousandShips** [comment]
Please squash your commits into one, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

**Comment by EddieBreeg** [comment]
Done

File: core/math/math_funcs.h [hunk 2]
```diff
@@ -187,6 +187,19 @@ class Math {
 #endif
 	}
 
+	static _ALWAYS_INLINE_ int32_t division_round_up(int32_t p_num, int32_t p_den) {
+		return (p_num + p_den - 1) / p_den;
+	}
+	static _ALWAYS_INLINE_ uint32_t division_round_up(uint32_t p_num, uint32_t p_den) {
+		return (p_num + p_den - 1) / p_den;
+	}
+	static _ALWAYS_INLINE_ int64_t division_round_up(int32_t p_num, int64_t p_den) {
```
Comment (AThousandShips) [inline core/math/math_funcs.h:196]: Any reason `p_num` is 32 bits?

**Comment by miv391** [comment]
How about adding comments about the parameter limits/requirements? For example the first function requires that the sum of num and den must be between min_int and max_int (otherwise there in an overflow).

File: core/math/math_funcs.h (hunk 2 above)
Comment (EddieBreeg) [reply core/math/math_funcs.h:196]: No, not quite sure why because I'm quite certain I had checked

Comment (AThousandShips) [reply core/math/math_funcs.h:196]: Same with the unsigned version below, copy-paste error I'd say

Use `git commit --amend` to fix to avoid creating new commits

**Comment by EddieBreeg** [comment]
Would there be any benefit to marking the function as constexpr?

**Comment by AThousandShips** [comment]
No I'd say, none of the contexts where it is used are constexpr compatible

**Comment by EddieBreeg** [comment]
Well right now they're not used in a constexpr context but do we know that's not going to change? And adding wouldn't change a thing if it has to be evaluated at runtime anyway

**Comment by EddieBreeg** [comment]
Ok what the hell, I didn't close this

**Comment by AThousandShips** [comment]
But if you're doing things at compile time then you should probably not be depending on this right?

**Comment by AThousandShips** [comment]
You closed this, you probably clicked the wrong button when commenting

**Comment by EddieBreeg** [comment]
> You closed this, you probably clicked the wrong button when commenting

Well that's great, thanks github...

> But if you're doing things at compile time then you should probably not be depending on this right?

In theory no, but then why does anyone use constexpr right? Arguably, for code readability so that it's still obvious what you're doing. I agree it's unlikely it will actually get used, I just think it doesn't hurt

**Comment by miv391** [comment]
As this PR is being made because previous implementation bugged when num was 0, I would suggest making unit tests to prove that now this works.

**Comment by AThousandShips** [comment]
> Arguably, for code readability so that it's still obvious what you're doing.

Except it's inlined so it will have no effect what so ever

**Comment by EddieBreeg** [comment]
> As this PR is being made because previous implementation bugged when num was 0, I would suggest making unit tests to prove that now this works.

Will do

**Comment by EddieBreeg** [comment]
So you'd suggest not adding comments and adding the cheap tests instead?

**Comment by AThousandShips** [comment]
To ensure the correct behaviour of these I'd say test cases should be added to `tests/core/math
/test_math_funcs.h`

**Comment by EddieBreeg** [comment]
As I said, I will. In fact I have, the changes just aren't pushed yet.

**Comment by AThousandShips** [comment]
Wanted to make sure as there was talk of different tests going on

**Comment by lawnjelly** [comment]
> So you'd suggest not adding comments and adding the cheap tests instead?

I wouldn't make it a hard requirement, but it's worth considering.

If it were me I would probably judge where it is used and how much of a bottleneck these cases are likely to be (in DEV builds) in order to make that call. If it is used in really tight loops maybe not, but if used < a few thousand times a frame then there's probably no harm in adding and it might catch a bug or two in future.

**Comment by EddieBreeg** [comment]
> Wanted to make sure as there was talk of different tests going on

For now I only have one template test case:
```cpp
CHECK(Math::division_round_up((T)0, (T)64) == 0);
CHECK(Math::division_round_up((T)63, (T)64) == 1);
CHECK(Math::division_round_up((T)64, (T)64) == 1);
CHECK(Math::division_round_up((T)65, (T)64) == 2);
```

**Comment by EddieBreeg** [comment]
> > So you'd suggest not adding comments and adding the cheap tests instead?
> 
> I wouldn't make it a hard requirement, but it's worth considering.
> 
> If it were me I would probably judge where it is used and how much of a bottleneck these cases are likely to be (in DEV builds) in order to make that call. If it is used in really tight loops maybe not, but if used < a few thousand times a frame then there's probably no harm in adding and it might catch a bug or two in future.

Judging by the cases we currently have in the code I'd say it's okay

**Comment by AThousandShips** [comment]
It's `DEV_CHECK_ONCE`

**Comment by EddieBreeg** [comment]
Oh right yeah, should I add it there then?

**Comment by miv391** [comment]
> ```c++
> CHECK(Math::division_round_up((T)0, (T)64) == 0);
> CHECK(Math::division_round_up((T)63, (T)64) == 1);
> CHECK(Math::division_round_up((T)64, (T)64) == 1);
> CHECK(Math::division_round_up((T)65, (T)64) == 2);
> ```
> 
> All of them pass without any issue

Are the signed versions supposed to be used with negative `num` too? If yes, add some negative number tests. 

As adding tests is cheap, I would suggest adding:

> ```c++
> CHECK(Math::division_round_up((T)1, (T)64) == 1);
> ```

just to make sure there are no surprising off-by-one errors near zero. Also some tests where `p_den` is 1 would be nice.

File: core/math/math_funcs.h (hunk 2 above)
Comment (AThousandShips) [reply core/math/math_funcs.h:196]: Did you decide this was intentional? Please elaborate why the nominator should be 32 bits here

**Comment by akien-mga** [comment]
> Oh right yeah, should I add it there then? Bare with me, I'm a new contributor so I'm a bit wary when it comes to modifying these kinds of files I want to make sure I'm not doing anything stupid

I would suggest not adding these extra checks in this PR. That's not a task for a first time contributor and would require a proper proposal and assessment of where it would be useful. There are hundreds of existing functions which could overflow integers, this one is no exception and doesn't require more guards than existing methods.

Sometimes we get a bit carried away discussion potential improvements in a PR review but this one would be out of scope IMO.

**Comment by EddieBreeg** [comment]
Yeah that makes sense I guess I'll just add the comment to let people know

**Comment by lawnjelly** [comment]
Yeah on reflection agree with @akien-mga , it's controversial and something separate for bikeshedding on another day and has wider implications. Sorry for giving impression that it might be required. :+1:

**Comment by EddieBreeg** [comment]
No worries! At least it's worth discussing

**Comment by EddieBreeg** [comment]
Turns out, tests failed with negative values, I'll take a look

**Comment by EddieBreeg** [comment]
I corrected the code, it should now support both signed and unsigned correctly if the tests are anything to go by

File: core/math/math_funcs.h [hunk 3]
```diff
@@ -187,6 +187,33 @@ class Math {
 #endif
 	}
 
+	/**
+	 * @note Assumes (p_num + p_den) doesn't overflow
```
Comment (AThousandShips) [inline core/math/math_funcs.h:191]: This should be a single line, and no "@note", we don't have yay s:
```suggestion
	 // Assumes (p_num + p_den) doesn't overflow.
```

File: tests/core/math/test_math_funcs.h [hunk 4]
```diff
@@ -108,6 +108,23 @@ TEST_CASE_TEMPLATE("[Math] round/floor/ceil", T, float, double) {
 	CHECK(Math::ceil((T)-1.9) == (T)-1.0);
 }
 
+TEST_CASE_TEMPLATE("[Math] integer division round up unsigned", T, uint32_t, uint64_t) {
+	CHECK(Math::division_round_up((T)0, (T)64) == 0);
+	CHECK(Math::division_round_up((T)1, (T)64) == 1);
+	CHECK(Math::division_round_up((T)63, (T)64) == 1);
+	CHECK(Math::division_round_up((T)64, (T)64) == 1);
+	CHECK(Math::division_round_up((T)65, (T)64) == 2);
+	CHECK(Math::division_round_up((T)65, (T)1) == 65);
```
Comment (miv391) [inline tests/core/math/test_math_funcs.h:117]: I would suggest copy-pasting these same tests also to the next test case template which tests signed integers.

**Comment by AThousandShips** [comment]
Potential case for this:
* #84672

File: core/math/math_funcs.h [hunk 5]
```diff
@@ -187,6 +187,25 @@ class Math {
...
+	}
+	// Assumes (p_num + p_den) doesn't overflow.
+	static _ALWAYS_INLINE_ int64_t division_round_up(int64_t p_num, int64_t p_den) {
+		int32_t offset = (p_num < 0 && p_den < 0) ? 1 : -1;
+		return (p_num + p_den + offset) / p_den;
+	}
+	// Assumes (p_num + p_den) doesn't overflow.
+	static _ALWAYS_INLINE_ uint64_t division_round_up(uint64_t p_num, uint64_t p_den) {
+		return (p_num + p_den - 1) / p_den;
+	}
```
Comment (akien-mga) [inline core/math/math_funcs.h:207]:
```suggestion
	// These methods assume (p_num + p_den) doesn't overflow.
	static _ALWAYS_INLINE_ int32_t division_round_up(int32_t p_num, int32_t p_den) {
		int32_t offset = (p_num < 0 && p_den < 0) ? 1 : -1;
		return (p_num + p_den + offset) / p_den;
	}
	static _ALWAYS_INLINE_ uint32_t division_round_up(uint32_t p_num, uint32_t p_den) {
		return (p_num + p_den - 1) / p_den;
	}
	static _ALWAYS_INLINE_ int64_t division_round_up(int64_t p_num, int64_t p_den) {
		int32_t offset = (p_num < 0 && p_den < 0) ? 1 : -1;
		return (p_num + p_den + offset) / p_den;
	}
	static _ALWAYS_INLINE_ uint64_t division_round_up(uint64_t p_num, uint64_t p_den) {
		return (p_num + p_den - 1) / p_den;
	}
```

**Review by akien-mga — APPROVED** [review]
Looks good to me from a cursory look. Sorry for the delay reviewing.

**Comment by YuriSizov** [comment]
@EddieBreeg Will you be available to address the feedback? This PR also needs a rebase.

File: core/math/math_funcs.h (hunk 5 above)
Comment (akien-mga) [reply core/math/math_funcs.h]: Applied these changes myself.

**Comment by akien-mga** [comment]
I rebased the PR myself, solving the conflicts, adding the change I suggested, and handling a few other occurrences which I found with this regex:
```
rg "\- 1\) /.*\+ 1" -g'!thirdparty'
```

There might be more when they're multiline of with either operand being a local variable, but this should be a good start.

File: tests/core/math/test_math_funcs.h (hunk 4 above)
Comment (akien-mga) [reply tests/core/math/test_math_funcs.h:119]: Seems like this was done.

File: drivers/gles3/storage/mesh_storage.cpp [hunk 6]
```diff
@@ -2044,8 +2044,8 @@ void MeshStorage::_update_dirty_multimeshes() {
 			uint32_t visible_instances = multimesh->visible_instances >= 0 ? multimesh->visible_instances : multimesh->instances;
 
 			if (multimesh->data_cache_used_dirty_regions) {
-				uint32_t data_cache_dirty_region_count = (multimesh->instances - 1) / MULTIMESH_DIRTY_REGION_SIZE + 1;
-				uint32_t visible_region_count = visible_instances == 0 ? 0 : (visible_instances - 1) / MULTIMESH_DIRTY_REGION_SIZE + 1;
+				uint32_t data_cache_dirty_region_count = Math::division_round_up(multimesh->instances, (int)MULTIMESH_DIRTY_REGION_SIZE);
+				uint32_t visible_region_count = visible_instances == 0 ? 0 : Math::division_round_up(visible_instances, (int)MULTIMESH_DIRTY_REGION_SIZE);
```
Comment (AThousandShips) [inline drivers/gles3/storage/mesh_storage.cpp:2048]:
```suggestion
				uint32_t visible_region_count = visible_instances == 0 ? 0 : Math::division_round_up(visible_instances, (uint32_t)MULTIMESH_DIRTY_REGION_SIZE);
```

Comment (akien-mga) [reply drivers/gles3/storage/mesh_storage.cpp]: Thought I could YOLO my way through CI, but no, those pesky type mismatches required a local build.

**Comment by akien-mga** [comment]
Thanks!

File: servers/rendering/renderer_rd/shaders/environment/sdfgi_preprocess.glsl [hunk 7]
```diff
@@ -1033,7 +1033,7 @@ void main() {
 
 	if (local == ivec3(0) && store_position_count > 0) {
 		store_from_index = atomicAdd(dispatch_data.total_count, store_position_count);
-		uint group_count = (store_from_index + store_position_count - 1) / 64 + 1;
+		uint group_count = Math::division_round_up(store_from_index + store_position_count, 64);
```
Comment (reduz) [inline servers/rendering/renderer_rd/shaders/environment/sdfgi_preprocess.glsl:1036]: This should not have been merged, the shader does not even compile.
Was this PR even tested?

**Review by reduz — COMMENTED** [review]
This PR was merged without even being tested. I am not happy about it.

File: servers/rendering/renderer_rd/shaders/environment/sdfgi_preprocess.glsl (hunk 7 above)
Comment (akien-mga) [reply servers/rendering/renderer_rd/shaders/environment/sdfgi_preprocess.glsl:1036]: My mistake, I added this yesterday.

Comment (akien-mga) [reply servers/rendering/renderer_rd/shaders/environment/sdfgi_preprocess.glsl:1036]: Fixed by 7abaac631bd897154686e6db030904d0af238248.

**Comment by akien-mga** [comment]
> This PR was merged without even being tested. I am not happy about it.

I tested, but didn't notice the error. My test project was likely not using SDFGI.
It does show a shader compilation error when running Godot from terminal, but none in the editor itself, so I missed it when doing a quick check after finalizing the PR.

Anyway, this was my bad, I added this change yesterday after rebasing and noticing a few new cases of `(x + 1) / y - 1` that should be refactored. I've undone the .glsl change in 7abaac6.
