### PR TITLE
Fix weigth scale of A* being applied to the whole estimation

### LINKED ISSUE #8584: AStar weight scale applied to whole path during solve?
**Operating system or device - Godot version:**
X11, 64 bits, 2.1.3 and 3.0

**Issue description:**
Trying to make a board game style hex tile map. Connecting points and giving most points a weight of 1, and some points a weight of 2. Expected solution would be to consider moving through 2-weighted cells to cost 2 move points and 1-weighted cells to cost 1 point.  Looks like weight gets multiplied to the whole distance calculation (*= used in line 194 or 222, etc). I saw it avoiding a path of 8 2-weighted cells and choosing instead 22 1-weighted cells.

**Steps to reproduce:**
Create a hex tile map and add only the hexes that have a tile on them as points in A-Star. connect all adjacent hexes. Give some cells a weight of 2 and some a weight of one, making some paths theoretically cost more. When path is solved, the shortest path often doesn't seem to properly factor cost as per cell, but cumulative instead. Pretty hard to explain, but it seems wrong to me.

**Link to minimal example project:**
I'll make a sample project and add it soon...it'll take a little extra time. Wanted to get issue raised first.

### PR DESCRIPTION
**Pull request by bojidar-bg**
Attempt to fix #8584.

Would be nice if someone with A* knowledge can confirm that this is correct.

This should be backported to 2.x in case it is merged.

### CODE REVIEW

File: core/math/a_star.cpp [hunk 1]
```diff
@@ -190,8 +190,7 @@ bool AStar::_solve(Point *begin_point, Point *end_point) {
 
 		Point *n = begin_point->neighbours[i];
 		n->prev_point = begin_point;
-		n->distance = _compute_cost(n->id, begin_point->id);
-		n->distance *= n->weight_scale;
+		n->distance = _compute_cost(begin_point->id, n->id) * n->weight_scale;
```
Comment (bojidar-bg) [inline core/math/a_star.cpp]: I swapped the arguments here, since `_compute_cost` takes `(p_from_id, p_to_id)`, and we are obviously moving from the initial point to one of the neighbouring points.

**Comment by tagcup** [comment]
This will still overestimate the cost if any of the user-specified weights is less than 1. Can be worked around through documentation maybe.

**Comment by bojidar-bg** [comment]
@tagcup I'd go with documentation for that one...
The other option would be to keep track of the minimum weight_scale and multiply the heuristic by it, but this would probably have a high performance cost on big maps with many deletions/recreations of nodes.

**Comment by tagcup** [comment]
Such a check can be done only during node insertion (in add_node) so it wouldn't hurt the performance (if it does affect, then A* itself will be unusably slow to use anyway). Furthermore, it could be enabled for debug builds only.

**Comment by bojidar-bg** [comment]
@tagcup Actually, I thought a bit about it, and I think that we should actually go the `min_weigth_scale` way, and update it only in `add_point`, with an optional way to set/reset it (or maybe, we can just reset it when the amount of points == 0). That way, we wouldn't bother the user with nagging errors, and still not break the algorithm or performance.

**Comment by tagcup** [comment]
There's always going to be an invalid input (0 weight, or negative weight), so we would need those errors and documentation about the valid range either way. Since you can ever get rid of them, I'd say it would be best to stick with the simpler solution.

**Comment by akien-mga** [comment]
So in the end do you both agree on this PR's solution? :)

**Comment by bojidar-bg** [comment]
@tagcup Well, having weight less than 1 is going to be useful in some cases, like when you have the whole grid made of 1-es, and just want to make a few nodes be more likely to get visited.
Also, simpler solution isn't much simpler, we just have one float less, nothing else. And it makes a few unlikely users a bit happier, as well as speeding up the algorithm on, e.g., grids made up of weight-2 nodes only.

**Comment by tagcup** [comment]
I don't think there are any advantages one way or the other way, you just need to prepare the weights accordingly.

Yes, it's just more more float, but you need to pay some effort to maintain that float.
Adding a point is easy but you need to scan all the points to find the new minimum when a point is removed for example (which isn't in the PR).

**Comment by tagcup** [comment]
Using a priority queue would help with remove (such that the operation becomes logarithmic rather than linear), but either way, I think it'd be adding complexity with no real benefits.

**Comment by bojidar-bg** [comment]
@tagcup Well, I would rather leave it as it. The user can still normalise his weights on his own, and the algorithm isn't getting much slower from the change. Or he can forget everything about normalisation and leave the engine to normalise the values on the fly, no problem for us.

You might think of it this way: If the user added a point with weight scale of 0.5, and then somehow decided to remove it, we can safely assume that he would want to add another one with such weight scale in the future. Since this doesn't deteriorate the paths produced if the original heuristic is admissible, everyone is happy.

If we do not normalise values ourselves, we would just get a few grumpy developers from time to time, nothing more.

I think I'm going to stop discussing this point since the prize -- ± a few grumpy developers -- is too low to be worth the time. If it works, it works.

**Comment by tagcup** [comment]
> You might think of it this way: If the user added a point with weight scale of 0.5, and then somehow decided to remove it, we can safely assume that he would want to add another one with such weight scale in the future. Since this doesn't deteriorate the paths produced if the original heuristic is admissible, everyone is happy.

No, you can't safely assume that. You can't make such assumptions at all.

> If we do not normalise values ourselves, we would just get a few grumpy developers from time to time, nothing more.

If you want to introduce renormalization, you need to do it correctly by fixing `remove_points`, which can only be done by using an O(n) operation in its current state. You can't expect users to work around an implementation bug.

I'm in favor of not doing any renormalization at all, and just document that all the weights have to be at least 1.

Note that even with renormalization, you still have a range of invalid inputs (0 or negative weights), so you'll get "grumpy developers" with or without the renormalization.

**Comment by tagcup** [comment]
To see why an additional factor of underestimating can be so bad, you can think what happens if a user adds a vertex with weight 1e-10 (which is a valid input) and then removes it.

**Comment by tagcup** [comment]
> I think I'm going to stop discussing this point since the prize -- ± a few grumpy developers -- is too low to be worth the time. If it works, it works.

I submitted my own PR to implement [what I said three weeks ago](https://github.com/godotengine/godot/issues/8584#issuecomment-298386446) (which long predates this PR) since you're saying you're not interested in discussing to address the issue I pointed out.

**Comment by bojidar-bg** [comment]
Do not merge yet. I have to remove the min_weight_scale code from my commit, since isn't related to the issue I'm supposed to fix.

**Comment by bojidar-bg** [comment]
Ok, removed all references to `min_weigth_scale`, as it seems a bit too hard to reach consensus about it with some members of the community.

@tagcup I see you made another PR for the issue you mentioned, which is nice. Now this PR is no longer blocked by it 😃.
