### PR TITLE
Fix bad popups offset in editor with single window off

### LINKED ISSUE #47217: Context menu wrong offset in code editor
**Godot version:**
4.0 master branch 07f076fa4f2896415993bb8e3fb42128423de0d2

**OS/device including version:**
Windows 10

**Issue description:**
In code editor, the context menu that pops on right mouse click doesn't appear at the cursor position.

It's not only an esthetic issue because the mouse is already on the first item when it pops so this item can be chosen by mistake on just releasing the right mouse button.

That doesn't occurs with context menu in scene tree or file tree.

Doesn't seem to be linked to other issues where popup are far away from normal position until window is resized.

**What happens :**

pop1

**What is expected :**

pop2

I've investigate on this issue and it seems that the mouse coordinates used for Popup creation are correct.
I've try to replace the current contextmenu with a basic popup with one item only (without icon or shortcut) and the problem is the same.

**Steps to reproduce:**

Right click on code editor.
Popup offset is wrong.

**Minimal reproduction project:**
Any project with a script in editor.

### PR DESCRIPTION
**Pull request by jmb462**
Fix #47217

### Issue description

When single window is disabled, popup menus in editor pops at a bad offset (see GIFs below)

### Fix proposal (Updated after Kobewi comment)

Using ``get_screen_transform()`` instead of ``get_global_transform()`` to set the popup position to deal with offset in multiwindow mode correctly.

### BEFORE
bug_bezier
Bezier Editor bug

bug_script_editor
Script Editor bug

bug_shader
Shader Editor Bug

bug_curve
Curve editor bug

bug_node2
Canvas editor bug

### AFTER

fix_bezier
Bezier editor fixed

fix_script_editor
Script editor fixed

fix_script_shader
Shader Editor Fixed

fix_curve
Curve Editor Fixed

fix_node2
Canvas Editor Fixed

### CODE REVIEW

**Comment by KoBeWi** [comment]
This won't work if the control is rotated or scaled. It's not a problem in the editor, but e.g. TextEdit can't use this.

**Comment by jmb462** [comment]
> This won't work if the control is rotated or scaled. It's not a problem in the editor, but e.g. TextEdit can't use this. The problem might lie in `get_screen_transform()` possibly returning wrong value.

get_screen_transform() is working well.

All buggy popup were using get_global_transform() instead.

I've modified the PR to replace these occurence.
A lot of other popups uses get_screen_transform() and works well.

**Comment by KoBeWi** [comment]
The change is good, but it doesn't fix all popups. I'd take the chance to replace all wrong usage of global position/transform. Also there are cases like e.g. ConnectionsDock, where the menu isn't properly trimmed:
image
Such popups need `popup->set_size(Vector2())` call.

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -786,7 +786,7 @@ void EditorProperty::gui_input(const Ref<InputEvent> &p_event) {
 		}
 	} else if (mb.is_valid() && mb->is_pressed() && mb->get_button_index() == MOUSE_BUTTON_RIGHT) {
 		_ensure_popup();
-		menu->set_position(get_screen_position() + get_local_mouse_position());
+		menu->set_position(get_screen_transform().xform(get_local_mouse_position()));
```
Comment (KoBeWi) [inline editor/editor_inspector.cpp:789]: I think this one is ok. If something already uses screen position then it can be left like that.

Also for other changes, I'd do
`get_global_position()` -> `get_screen_position()`
`get_global_transform().xform()` -> `get_screen_transform().xform()`
i.e. if something uses position, just fix the position and if it uses transform, fix transform.

**Comment by groud** [comment]
This PR looks quite similar to https://github.com/godotengine/godot/pull/37506, but I am not sure that on e is still being worked on. You might want to have a look to it.

**Comment by jmb462** [comment]
> This PR looks quite similar to #37506, but I am not sure that on e is still being worked on. You might want to have a look to it.

@groud All cases fixed by this PR are also fixed in #37506 with the same modifications and #37506 is more exhaustive.

I think we could close this one and "reactivate" the review process of #37506.

**Comment by pycbouh** [comment]
@jmb462 If you are up for it, it would likely be preferable if you were to incorporate the changes from the other PR here, add that other contributor as co-author and see it through to the end. The other PR is a year old, they may not be ready to work on it yet. But you are here 🙃

File: editor/editor_inspector.cpp (hunk 1 above)
Comment (jmb462) [reply editor/editor_inspector.cpp]: Thanks. Done.

**Comment by jmb462** [comment]
OK, I've included most of @giarve modification in this PR (from #37506).
I've also found one or two popups that still use get_global_transform() and fixed it.
I've added some default size to popup to ensure they are trimmed properly (each time I can't find set_size() for these popups)

BUT I didn't include @giarve modification for following files cause it wasn't clear to me  :
- scene/main/window.cpp  related to screen set current screen
- platform/linuxbsd/display_server_x11.cpp cause I don't understand this part

**Comment by KoBeWi** [comment]
Needs rebase, also `set_size(Vector2(1, 1)` needs to be changed to `reset_size()`.
Is this finished aside from that?

**Comment by jmb462** [comment]
> Needs rebase, also `set_size(Vector2(1, 1)` needs to be changed to `reset_size()`. Is this finished aside from that?

@KoBeWi Done. Seems finished to me.

**Comment by TokageItLab** [comment]
Does it fix to #50720? I guess that issue caused by same reason.

**Comment by KoBeWi** [comment]
So I *accidentally* opened [an extremely similar PR](https://github.com/godotengine/godot/pull/55297) 3 days ago, which has most of the changes that this one has. I made sure to go over every single popup, so you can take a look if your PR isn't missing something I did. I know that at least my changes to `visual_shader_editor_plugin.cpp` are still relevant, so you could just copy them over here.

**Comment by jmb462** [comment]
> So I _accidentally_ opened [an extremely similar PR](https://github.com/godotengine/godot/pull/55297) 3 days ago, which has most of the changes that this one has. I made sure to go over every single popup, so you can take a look if your PR isn't missing something I did. I know that at least my changes to `visual_shader_editor_plugin.cpp` are still relevant, so you could just copy them over here.

Done.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
I just created a new conflict by merging a new PR, so needs a rebase.

**Comment by akien-mga** [comment]
> I just created a new conflict by merging another PR, so needs a rebase.

I did it myself and force pushed the rebase so that we can get it merged.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
For the record there's a few more places with `get_global_transform().xform` which might be worth reviewing, if they haven't been already:
```
$ rg "get_global_transform\(\).xform"
scene/3d/soft_dynamic_body_3d.cpp
403:                    PhysicsServer3D::get_singleton()->soft_body_move_point(physics_rid, r[i].point_index, r[i].spatial_attachment->get_global_transform().xform(r[i].offset));

scene/3d/visual_instance_3d.cpp
36:     return get_global_transform().xform(get_aabb());

scene/2d/node_2d.cpp
362:    return get_global_transform().xform(p_local);

editor/animation_track_editor.cpp
5229:                   box_selecting_from = scroll->get_global_transform().xform(mb->get_position());
5274:           Vector2 to = scroll->get_global_transform().xform(mm->get_position());

scene/3d/node_3d.cpp
757:    return get_global_transform().xform(p_local);

editor/plugins/node_3d_editor_plugin.cpp
6528:                                   aabb = collision_shape->get_global_transform().xform(collision_shape->get_shape()->get_debug_mesh()->get_aabb());
6534:                                           aabb.merge_with(col_shape->get_global_transform().xform(col_shape->get_shape()->get_debug_mesh()->get_aabb()));
```

**Comment by KoBeWi** [comment]
These are unrelated. The PR was only about popups. `get_global_transform()` is in window's local coordinates, but popups expect screen coordinates.

**Comment by akien-mga** [comment]
Thanks!
