### PR TITLE
Auto create tile for multiple atlases

### LINKED ISSUE #69273: Can't batch create atlas tiles when dragging multiple images into TileSet editor
### Godot version

4.0.beta6

### System information

Arch Linux

### Issue description

When dragging an image into the TileSet editor, you'll be prompted with:

> Would you like to automatically create tiles in the atlas?

This is quite handy.

However, some asset packs split tiles into multiple sprite sheet images. Dragging multiple images into the TileSet editor won't ask to create the tiles for you. So the user have to either

* drag the sprite sheets into the editor one by one, and click "Yes" when prompted, or
* go through each created atlas, and select "Create Tiles in Non-Transparent Texture Regions"

Quite tedious when the number of sprite sheets are large.

### Steps to reproduce

Drag two or more images into a TileSet editor. There won't be any dialog asking for creating tiles in the altas for you.

### Minimal reproduction project

N/A

### LINKED ISSUE #79473: Atlas Merging Tool not working
### Godot version

4.1.stable

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Compatibility) - Intel(R) HD Graphics 4600 (Intel Corporation; 20.19.15.5126) - Intel(R) Core(TM) i3-4330 CPU @ 3.50GHz (4 Threads)

### Issue description

When I try to join 68 images of 128x128 resolution in an atlas it returns a transparent 1x1 image

I tried using few images and it doesn't work either

It doesn't work either with 16x16, 32x32, 64x64 resolutions

- Google Translate :)

### Steps to reproduce

https://github.com/godotengine/godot/assets/136469511/ca5f64c2-f0c5-486f-a13e-b941ae2dea7d

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by thiagola92**
Based on issues: #69273 #79473 
And PRs: #70790 #79558 

- Support for auto create tiles when adding multiple atlases
- Button to add Atlas can be used for multiple files
- Unify functions `TileSetEditor::_texture_file_selected()` and `TileSetEditor::_drop_data_fw()` into `TileSetEditor::_load_texture_files()`

*Bugsquad edit:*
- Fixes https://github.com/godotengine/godot/issues/69273
- Fixes https://github.com/godotengine/godot/issues/79473

### CODE REVIEW

**Comment by groud** [comment]
Thanks for the contribution!

Why do you create 3 functions to do handle that, and store atlases as a property of the editor ? I would suggest to instead use a single function that takes an array instead, it would be simpler.

**Comment by Chaosus** [comment]
And commits needs to be squashed in order for PR to be accepted (see https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html).

**Comment by thiagola92** [comment]
@groud I really didn't want to store atlases as a property but I don't know how to get the array after the user accept/decline a popup.

```cpp
void TileSetAtlasSourceEditor::init_source(Vector<Ref<TileSetAtlasSource>> atlases) {
	tool_setup_atlas_source_button->set_pressed(true);
	atlases_to_auto_create_tiles = atlases;
	confirm_auto_create_tiles->popup_centered();
}
```

`_clear_auto_create_tiles()` created for when the user cancel the popup.  
`_auto_create_tiles_in_atlas()` i think that i'm going to move the logic back to `_auto_create_tiles()`  
Can you tell me the third function? `init_source()` existed before to deal with the popup.  

@Chaosus Thank you, I will read and do right after any adjustment from feedbacks

**Comment by groud** [comment]
> @groud I really didn't want to store atlases as a property but I don't know how to get the array after the user accept/decline a popup.

Ah I see what you mean. I think it's fine to do it that way then, using a property. However I would probably move the definition closer to the popup's one in the .h file, so that's it's a bit more obvious this variable is only needed for the popup.

**Comment by thiagola92** [comment]
@groud Like this?  

```cpp
void _auto_create_tiles();
void _auto_remove_tiles();
void _cancel_auto_create_tiles();
AcceptDialog *confirm_auto_create_tiles = nullptr;
```

Also I renamed `_clear_auto_create_tiles()` to `_cancel_auto_create_tiles()`.

**Comment by groud** [comment]
I meant something like this:
```
void _auto_create_tiles();
void _auto_remove_tiles();
void _cancel_auto_create_tiles();
AcceptDialog *confirm_auto_create_tiles = nullptr;
Vector<Ref<TileSetAtlasSource>> atlases_to_auto_create_tiles;
```
Related variables and methods close together.

**Comment by thiagola92** [comment]
@groud Sorry, fixed.
@Chaosus Squashed.

File: editor/plugins/tiles/tile_set_atlas_source_editor.cpp [hunk 1]
```diff
@@ -2259,54 +2263,61 @@ void TileSetAtlasSourceEditor::edit(Ref<TileSet> p_tile_set, TileSetAtlasSource
...
+			if (texture.is_valid()) {
+				Vector2i margins = atlas_source->get_margins();
+				Vector2i separation = atlas_source->get_separation();
+				Vector2i texture_region_size = atlas_source->get_texture_region_size();
+				Size2i grid_size = atlas_source->get_atlas_grid_size();
+				EditorUndoRedoManager *undo_redo = EditorUndoRedoManager::get_singleton();
+				undo_redo->create_action(TTR("Create tiles in non-transparent texture regions"));
+				for (int y = 0; y < grid_size.y; y++) {
+					for (int x = 0; x < grid_size.x; x++) {
+						// Check if we have a tile at the coord
```
Comment (AThousandShips) [inline editor/plugins/tiles/tile_set_atlas_source_editor.cpp:2285]:
```suggestion
						// Check if we have a tile at the coord.
```
Code style requires that comments start with a capital letter and ends in a period

Comment (thiagola92) [reply editor/plugins/tiles/tile_set_atlas_source_editor.cpp]: Updated

**Review by groud — CHANGES_REQUESTED** [review]
Needs a rebase, but I believe looks mostly good.

**Comment by thiagola92** [comment]
Moved the comment `// Handle dropping a texture in the list of atlas resources.` back to `_drop_data_fw()`

File: editor/plugins/tiles/tile_set_editor.cpp [hunk 2]
```diff
@@ -124,6 +97,44 @@ bool TileSetEditor::_can_drop_data_fw(const Point2 &p_point, const Variant &p_da
 	return false;
 }
 
+void TileSetEditor::_load_data(const Vector<String> &p_paths) {
```
[the remark this answers is not in the document]
Comment (thiagola92) [reply editor/plugins/tiles/tile_set_editor.cpp]: Agree, changed

[the remark this answers is not in the document]
Comment (thiagola92) [reply editor/plugins/tiles/tile_set_editor.cpp]: I marked as resolved but i should have let you do that, right?

**Comment by thiagola92** [comment]
@groud Can you confirm if i did rebase correctly?

File: editor/plugins/tiles/tile_set_atlas_source_editor.cpp [hunk 3]
```diff
@@ -2242,54 +2246,61 @@ void TileSetAtlasSourceEditor::edit(Ref<TileSet> p_tile_set, TileSetAtlasSource
 	_update_current_tile_data_editor();
 }
 
-void TileSetAtlasSourceEditor::init_source() {
+void TileSetAtlasSourceEditor::init_source(Vector<Ref<TileSetAtlasSource>> atlases) {
```
Comment (AThousandShips) [inline editor/plugins/tiles/tile_set_atlas_source_editor.cpp:2249]:
```suggestion
void TileSetAtlasSourceEditor::init_source(const Vector<Ref<TileSetAtlasSource>> &p_atlases) {
```
Prefix arguments with `p_`, also pass by reference, no need to do unnecessary copying even if it only is refcounting

File: editor/plugins/tiles/tile_set_atlas_source_editor.cpp [hunk 4]
```diff
@@ -2242,54 +2246,61 @@ void TileSetAtlasSourceEditor::edit(Ref<TileSet> p_tile_set, TileSetAtlasSource
...
 	tool_setup_atlas_source_button->set_pressed(true);
+	atlases_to_auto_create_tiles = atlases;
```
Comment (AThousandShips) [inline editor/plugins/tiles/tile_set_atlas_source_editor.cpp:2251]:
```suggestion
	atlases_to_auto_create_tiles = p_atlases;
```

File: editor/plugins/tiles/tile_set_atlas_source_editor.h [hunk 5]
```diff
@@ -288,7 +290,7 @@ class TileSetAtlasSourceEditor : public HSplitContainer {
 
 public:
 	void edit(Ref<TileSet> p_tile_set, TileSetAtlasSource *p_tile_set_source, int p_source_id);
-	void init_source();
+	void init_source(Vector<Ref<TileSetAtlasSource>> atlases_to_auto_create_tiles);
```
Comment (AThousandShips) [inline editor/plugins/tiles/tile_set_atlas_source_editor.h:293]:
```suggestion
	void init_source(const Vector<Ref<TileSetAtlasSource>> &p_atlases);
```
Match argument names

File: editor/plugins/tiles/tile_set_atlas_source_editor.cpp [hunk 6]
```diff
@@ -2242,54 +2246,61 @@ void TileSetAtlasSourceEditor::edit(Ref<TileSet> p_tile_set, TileSetAtlasSource
...
 	confirm_auto_create_tiles->popup_centered();
 }
 
 void TileSetAtlasSourceEditor::_auto_create_tiles() {
-	if (!tile_set_atlas_source) {
-		return;
-	}
+	for (Ref<TileSetAtlasSource> atlas_source : atlases_to_auto_create_tiles) {
```
Comment (AThousandShips) [inline editor/plugins/tiles/tile_set_atlas_source_editor.cpp:2256]:
```suggestion
	for (Ref<TileSetAtlasSource> &atlas_source : atlases_to_auto_create_tiles) {
```
Reference here, no need to refcount

**Comment by thiagola92** [comment]
@AThousandShips thank you for reviewing.
Changed as requested.

File: editor/plugins/tiles/tile_set_atlas_source_editor.cpp [hunk 7]
```diff
@@ -2242,54 +2246,61 @@ void TileSetAtlasSourceEditor::edit(Ref<TileSet> p_tile_set, TileSetAtlasSource
 	_update_current_tile_data_editor();
 }
 
-void TileSetAtlasSourceEditor::init_source() {
+void TileSetAtlasSourceEditor::init_source(const Vector<Ref<TileSetAtlasSource>> &p_atlases) {
```
Comment (groud) [inline editor/plugins/tiles/tile_set_atlas_source_editor.cpp:2249]: Since we have several sources now:
```suggestion
void TileSetAtlasSourceEditor::init_sources(const Vector<Ref<TileSetAtlasSource>> &p_atlases) {
```

Comment (thiagola92) [reply editor/plugins/tiles/tile_set_atlas_source_editor.cpp:2249]: I could change to `init_atlases` or `init_new_atlases`.

File: editor/plugins/tiles/tile_set_editor.cpp [hunk 8]
```diff
@@ -126,6 +100,43 @@ bool TileSetEditor::_can_drop_data_fw(const Point2 &p_point, const Variant &p_da
 	return false;
 }
 
+void TileSetEditor::_load_texture_files(const Vector<String> &p_paths) {
+	int source_id = TileSet::INVALID_SOURCE;
+	Vector<Ref<TileSetAtlasSource>> atlases;
+
+	for (String p_path : p_paths) {
```
Comment (AThousandShips) [inline editor/plugins/tiles/tile_set_editor.cpp:107]:
```suggestion
	for (const String &p_path : p_paths) {
```
Avoid referencing if not needed

Comment (thiagola92) [reply editor/plugins/tiles/tile_set_editor.cpp]: I really need to pay attention to this, sorry

Comment (AThousandShips) [reply editor/plugins/tiles/tile_set_editor.cpp]: It's no problem, it's a learning experience

**Review by groud — APPROVED** [review]
