### PR TITLE
Disable camera interpolation when switching scene tabs

### LINKED ISSUE #11764: Disable the viewport camera's interpolation when switching scene tabs or preset view angle
**Operating system or device, Godot version**
Linux Mint 18.2 Cinnamon x64, Godot master c9a925c

**Issue description:**
Each open scene tab will remember the position/rotation data of the viewport camera when switching to another tab, and re-apply it when switching back. When this happens, the movement to the new transform is interpolated, which doesn't make much sense and can be a little nauseating when switching between tabs often. It should really just 'jump' to the destination.

This is similar to #11008, but unlike what is stated there, it actually does happen when switching to already opened scenes (as shown in the video below).

**Steps to reproduce:**
1. Create a new scene or two
2. Move the camera around in each scene 
3. Switch between the scene tabs
4. [Vomit](https://streamable.com/1gj0p)

### PR DESCRIPTION
**Pull request by guilhermefelipecgs**
Fix #11764

### CODE REVIEW

File: editor/plugins/spatial_editor_plugin.cpp [hunk 1]
```diff
@@ -2128,7 +2128,12 @@ void SpatialEditorViewport::_notification(int p_what) {
 			}
 		}
 
-		_update_camera(delta);
+		if (EditorNode::get_singleton()->is_update_camera_without_interpolation()) {
```
Comment (akien-mga) [inline editor/plugins/spatial_editor_plugin.cpp]: It's overkill to add a new property just for that. I think `EditorNode::get_singleton()->is_changing_scene()` would work just fine.

Comment (guilhermefelipecgs) [reply editor/plugins/spatial_editor_plugin.cpp]: Unfortunately this method doesn't work because of this line: https://github.com/godotengine/godot/blob/d7b9fcd33689673c6237d91afdb4a8dfe548784a/editor/editor_node.cpp#L2641
and I was afraid to move this and break something.

Comment (guilhermefelipecgs) [reply editor/plugins/spatial_editor_plugin.cpp]: I'll take a closer look.

Comment (guilhermefelipecgs) [reply editor/plugins/spatial_editor_plugin.cpp]: @akien-mga I found another way to do this with less code. What do you think?

**Review by akien-mga — APPROVED** [review]
Nice! Is that enough to fix the issue?

File: editor/plugins/spatial_editor_plugin.cpp (hunk 1 above)
Comment (Zylann) [reply editor/plugins/spatial_editor_plugin.cpp]: Less code indeed, but re-using the notification looks like a hack (since visibility didn't strictly change). Also, it looks like this won't work if multi-viewport modes are used (split/quad views).

**Comment by guilhermefelipecgs** [comment]
Yes. It's working pretty well here. I made a little change to update all viewports now.

**Comment by akien-mga** [comment]
Thanks!

**Comment by Zylann** [comment]
I know it's nickpicking, but still not much convinced by the re-use of the VISIBILITY_CHANGED notification. It may work now and we could think it's fine by *having to know* what `SpatialEditorViewport` does right now. But I relate to it, because this is a standard notification which has meaning, and I've had bugs in my own projects due to it being wrongly called twice, so I can imagine future bugs to arise from this kind of practice. A more explicit function would have done it in a more semantically correct way IMO. Hopefully someone notices that if the code has to change in the future.

**Comment by guilhermefelipecgs** [comment]
`SpatialEditorViewport` and `edited_scene_changed` is only used in editor, this should not affect the game itself. If this cause some bug in the future we can find it with `git bisect` in the worst case.

**Comment by Zylann** [comment]
@guilhermefelipecgs plugins or even further editor code can be affected (it happened in a few of my plugin projects). Just saying this as it should be easy to avoid when coding, but I know it causes no problem for now :)
