### PR TITLE
Optimize shared texture creations

### LINKED ISSUE #98733: `RD::texture_create_shared_from_slice` become very slow when used extensively on a `Texture2DArrayRD`
### Tested versions

- Reproducible in Godot v4.3.1.rc (725f50752)

### System information

Ubuntu 22.04.5 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (nvidia; 535.183.01) - Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 Threads)

### Issue description

I noticed a performance issue in `RenderingDevice::texture_create_shared_from_slice`. In my game I use a `Texture2DArrayRD` and create 9 shared textures for each layer (the mipmaps). When I end up with 2000 shared textures, my game starts jittering a lot.

 I profiled my game using [Tracy](https://github.com/wolfpld/tracy) and the issue is with this line of code: `Texture texture = *src_texture;` in  `RenderingDevice::texture_create_shared_from_slice`. 80% of the duration of  `RenderingDevice::texture_create_shared_from_slice` can be spent there.

The `Texture` class has a member named `slice_trackers` which is a hashmap tracking the shared textures (correct me if I am wrong). It's the copy of this hashmap which slows down the `Texture` copy. On my system the copy takes about 50ns when the hashmap is almost empty and can reach 200µs or more when it contains 2500+ elements:

slice_trackers copy
As I can create 100 shared textures per frame, I get frames at 40ms or more...

IMO this can be solved by not copying the `slice_trackers` member.  `slice_trackers` is only used by the owner texture and not by the shared ones. In the current implementation we have `Texture texture = *src_texture;` and then `texture->slice_trackers.clear();` comes later in `RD::_texture_make_mutable`.

I am considering creating a PR replacing the line `Texture texture = *src_texture;` by something like `Texture texture = src_texture->duplicate_as_shared_texture();` where `Texture duplicate_as_shared_texture() const` copies every members except `slice_trackers`.  

I tested this fix and I got the expected results (this the durations of `RenderingDevice::texture_create_shared_from_slice`):
slice_trackers no copy

I am worried about maintainability and if you would like to support such a use case in the first place. So before creating a MRP (which require some work) and a PR I would like to get some feedback first.

### Steps to reproduce

- Create a `Texture2DArrayRD` with 1024 layers
- Call 10 times `RD::texture_create_shared_from_slice` for each layer

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/17607001/mrp.zip)

### PR DESCRIPTION
**Pull request by ze2j**
Fix [#98733](https://github.com/godotengine/godot/issues/98733)

This PR removes an unnecessary copy of `Texture::slice_trackers`, as it is always cleared afterward.

Build: scons platform=linuxbsd optimize=speed_trace debug_symbols=yes
Profiler: Tracy 
Test project: see MRP in  [#98733](https://github.com/godotengine/godot/issues/98733)

Results with master branch:
master

Results with this PR:
pr

### CODE REVIEW

File: servers/rendering/rendering_device.cpp [hunk 1]
```diff
@@ -903,7 +903,7 @@ RID RenderingDevice::texture_create_shared(const TextureView &p_view, RID p_with
 
 	// Create view.
 
-	Texture texture = *src_texture;
+	Texture texture = src_texture->duplicate_as_shared_texture();
 	texture.shared_fallback = nullptr;
```
Comment (clayjohn) [inline servers/rendering/rendering_device.cpp:907]: I guess `duplicate_as_shared_resource` should also avoid copying `shared_fallback` so we don't have to manually set it to nullptr right after doing the copy

File: servers/rendering/rendering_device.cpp [hunk 2]
```diff
@@ -1055,7 +1053,7 @@ RID RenderingDevice::texture_create_shared_from_slice(const TextureView &p_view,
 		slice_layers = 6;
 	}
 
-	Texture texture = *src_texture;
+	Texture texture = src_texture->duplicate_as_shared_texture();
```
Comment (clayjohn) [inline servers/rendering/rendering_device.cpp:1056]: I find it a bit surprising that we don't call `texture.slice_trackers.clear();` here. 

CC @DarioSamo who added the call in `texture_create_shared()`. Do you think this was missed by mistake? Or is there a reason to maintain the `slice_tracker` when creating a shared texture from a slice?

Comment (ze2j) [reply servers/rendering/rendering_device.cpp:1056]: The clear is made in `_texture_make_mutable`

**Comment by DarioSamo** [comment]
I think `slice_trackers` should be turned into a pointer instead and allocate it on demand only if a shared texture is created. The HashMap currently occupies 48 bytes per texture and largely goes unused in the vast majority of cases. Then when the copy is made, the simple solution is to just set it to a nullptr. That way there'll be no cost from copying the contents as is and we get a reduced memory footprint overall, for the small extra cost of an indirection.

I'm not a big fan of the proposed solution as it adds another function to maintain and keep track of when the copy is made.

**Comment by ze2j** [comment]
I agree and I am not a big fan of my solution too : ) I am going to rework my PR with your solution, it's a nice idea.

**Comment by ze2j** [comment]
Here is the new implementation following @DarioSamo suggestion. Sorry for the delay.

**Comment by DarioSamo** [comment]
I'm probably in need of this so I will test it again and confirm if it works.

**Review by DarioSamo — APPROVED** [review]
Tested and confirmed to be working. Gives me a very nice time reduction on the creation of reflection probe atlases.

File: servers/rendering/rendering_device.cpp [hunk 3]
```diff
@@ -5844,9 +5844,12 @@ bool RenderingDevice::_texture_make_mutable(Texture *p_texture, RID p_texture_id
 					p_texture->draw_tracker->reference_count++;
 				} else {
 					// Slice texture.
-					HashMap<Rect2i, RDG::ResourceTracker *>::ConstIterator draw_tracker_iterator = owner_texture->slice_trackers.find(p_texture->slice_rect);
+					if (owner_texture->slice_trackers == nullptr) {
+						owner_texture->slice_trackers = memnew((HashMap<Rect2i, RDG::ResourceTracker *>));
```
Comment (Calinou) [inline servers/rendering/rendering_device.cpp:5848]: Do we need the double parentheses on each side here?

Comment (ze2j) [reply servers/rendering/rendering_device.cpp:5848]: Yes it's definitely mandatory, it doesn't build without it:
`error: macro "memnew passed 2 arguments,  but takes just 1"`

**Comment by MarianoGnu** [comment]
> Gives me a very nice time

Out of curiosity, the profiling shown at the top of the discussion was from the original implementation or of this rework, has the result improved in speed beside memory footprint?

**Comment by ze2j** [comment]
@MarianoGnu  the profiling shown at the top of the discussion was from the original implementation. Here is the new one: 
pr_new_impl

**Comment by Repiteo** [comment]
Thanks!
