### PR TITLE
Account for file deletion and renaming in Export Presets

### LINKED ISSUE #39269: Export Presets with Resource selection don't account for deleting files
**Godot version:**
v3.2.2.beta3.official

**OS/device including version:**
Win10 64x

**Issue description:**

The Exporter keeps printing load errors for resources that were deleted inside Godot after including them ones in an Exporter Preset with "Export Mode: Export selected resources (and dependencies)". 

The problem is that the export mode fileselection only displays files that exist in the project so it becomes impossible to deselect deleted files to correct the preset inside the editor.

export_bug2

export_bug5

The ugly workaround is a manual cleanup in the presetfiles or creating a replacement file with the same name, go to export, untoggle the file, save the preset, delete the placeholder again. Sometimes it even requires deleting the Godot cache (no idea were the culprit is hiding inside so burn it) to go away.

Both the preset filelist (keeps filepath for deleted files indefinitely) and the export UI fileselection (only shows existing files so deleted filepaths from the preset can not be untoggled) are not updated correctly.

**Possible fix:**

My C-fu isn't very strong but I think right around [this_line ](https://github.com/godotengine/godot/blob/dc67d0737b86c7a6cab66752b96631c59c703997/editor/editor_export.cpp#L1301) in the editor_export source is a need for some form of file validation.

Pseudocode:
`valid_file = FileAccess::exists(files[i]);`
`if (!valid_file) {`
`    preset->remove_export_file(files[i]);`
`}`

If the file doesn't exist in the filesystem (and therefor isn't shown in the Export fileselection window) it should be remove from the preset filelist as well
OR
added to the Export fileselection window anyway ( that currently only shows existing files) but marked as deleted so users have a button to deselect manually and trigger the preset cleanup.

**Steps to reproduce:**
1.) Export project with a Preset and "Export Mode: Export selected resources (and dependencies)" and a few files selected.
2.) Delete some of the selected files inside Godot
3.) Export again, the Export Preset UI doesn't show the deleted files but prints errors for missing them.
4.)Try to correct the fileselection inside the Exporter UI, no longer possible without workaround.

### PR DESCRIPTION
**Pull request by mrushyendra**
Previously, when a file was deleted after an export preset was created, Godot
 would still attempt to export the deleted file, and issue a spurious error in the
process. There was also no way to change this from the Project Export window.

This PR ensures that presets stay updated, by removing any deleted or renamed 
files from the presets. It does this either when the editor starts up, or when the Project
Export window is opened, ensuring that the user always sees the latest versions.

Closes #39269

Can be cherry picked for 3.2

### CODE REVIEW

File: editor/editor_export.cpp [hunk 1]
```diff
@@ -90,6 +90,19 @@ Ref<EditorExportPlatform> EditorExportPreset::get_platform() const {
 	return platform;
 }
 
+void EditorExportPreset::update_files_to_export() {
+	Vector<Set<String>::Element *> to_remove;
```
Comment (akien-mga) [inline editor/editor_export.cpp:94]: I think this could be simplified to `Vector<String>` (and `push_back(E->get())`).

Comment (mrushyendra) [reply editor/editor_export.cpp]: Made the changes. Thanks!

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Comment by Anutrix** [comment]
Why was the cherrypick label removed?

**Comment by akien-mga** [comment]
Because I cherry-picked it already.
