### PR TITLE
Fix "Fully Axis-Locked" Freelook Navigation Scheme

### LINKED ISSUE #39573: Unexpected behavior with "Fully Axis-Locked" Freelook Navigation Scheme
**Godot version:**
v3.2.2.rc1.official

**OS/device including version:**
Windows 7 Professional Build 7601 SP1 / Workstation.

**Issue description:**
In Freelook Navigation Scheme "Fully Axis-Locked", when pointing the view straight down, flying forward/backwards pans the view in seemingly random directions. It appears to be caused by the direction suddenly inverting on the global X-axis (not Z) when looking down. It does not happen when moving right/left or when looking straight up.
bug234

**Steps to reproduce:**
-Enable the "Fully Axis-Locked" Freelook Navigation Scheme for the 3D Editor.
-Pitch the view straight down and start flying forwards and backwards.
-Rotate a bit back and forth around the global Y-axis and see that the direction the viewport will pan in is not what is expected.

**Minimal reproduction project:**
No project is needed to encounter this issue.

### PR DESCRIPTION
**Pull request by Voklen**
closes https://github.com/godotengine/godot/issues/39573

When looking straight down, `camera->get_rotation()` becomes negative (or positive depending on what direction your facing). 

ezgif-6-367d3b966318

I just made an "if" statement, to check whether the camera is facing directly down and if it is, the camera rotates around the -y-axis instead of the y-axis. This is probably not the best solution, so just request a change if you have a better one.

### CODE REVIEW

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -2254,7 +2254,11 @@ void Node3DEditorViewport::_update_freelook(real_t delta) {
 	Vector3 forward;
 	if (navigation_scheme == FREELOOK_FULLY_AXIS_LOCKED) {
 		// Forward/backward keys will always go straight forward/backward, never moving on the Y axis.
-		forward = Vector3(0, 0, -1).rotated(Vector3(0, 1, 0), camera->get_rotation().y);
+		if (camera->get_rotation().x == float(-Math_PI / 2)) {
```
Comment (groud) [inline editor/plugins/node_3d_editor_plugin.cpp:2257]: Equality check on float values is not a good practice, as the result is always unreliable due to precision errors.

Comment (vorblen) [reply editor/plugins/node_3d_editor_plugin.cpp:2257]: I've tried `double(camera->get_rotation().x) == -Math_PI / 2.` although that doen't seem to work, and I'm not sure why.

Comment (groud) [reply editor/plugins/node_3d_editor_plugin.cpp:2257]: Precision errors. You should almost never check for equality between float or double (both are floating-point stored values). When you can, you should instead use `<=` or `>=`. Here is likely one of those cases.

Comment (vorblen) [reply editor/plugins/node_3d_editor_plugin.cpp:2257]: So something like `if (camera->get_rotation().x <= 1.5708)`?

Comment (groud) [reply editor/plugins/node_3d_editor_plugin.cpp:2257]: Simply `if (camera->get_rotation().x <= -Math_PI / 2)` I guess. Provided it's not supposed to go any lower I guess.

Comment (vorblen) [reply editor/plugins/node_3d_editor_plugin.cpp]: d0279e17be22cb3e8a80dcf22e5decbc196f754a

**Comment by aaronfranke** [comment]
I think it would be better to instead prevent the camera from looking directly up or down, limiting the maximum rotation just before that point. How about +/- 1.57 radians (89.95 degrees)?

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 2]
```diff
@@ -2139,8 +2139,8 @@ void Node3DEditorViewport::_nav_look(Ref<InputEventWithModifiers> p_event, const
 		cursor.x_rot += p_relative.y * radians_per_pixel;
 	}
 	cursor.y_rot += p_relative.x * radians_per_pixel;
-	if (cursor.x_rot > Math_PI / 2.0) {
-		cursor.x_rot = Math_PI / 2.0;
+	if (cursor.x_rot > Math_PI / (2.0 + radians_per_pixel)) {
+		cursor.x_rot = Math_PI / (2.0 + radians_per_pixel);
```
Comment (aaronfranke) [inline editor/plugins/node_3d_editor_plugin.cpp:2143]: This code + the below if statement should be replaced with the `CLAMP` macro.

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 3]
```diff
@@ -2139,12 +2134,7 @@ void Node3DEditorViewport::_nav_look(Ref<InputEventWithModifiers> p_event, const
 		cursor.x_rot += p_relative.y * radians_per_pixel;
 	}
 	cursor.y_rot += p_relative.x * radians_per_pixel;
-	if (cursor.x_rot > Math_PI / 2.0) {
-		cursor.x_rot = Math_PI / 2.0;
-	}
-	if (cursor.x_rot < -Math_PI / 2.0) {
-		cursor.x_rot = -Math_PI / 2.0;
-	}
+	cursor.x_rot = CLAMP(cursor.x_rot, -Math_PI / 2, Math_PI / 2.0005);
```
Comment (aaronfranke) [inline editor/plugins/node_3d_editor_plugin.cpp:2137]:
```suggestion
	cursor.x_rot = CLAMP(cursor.x_rot, -1.57, 1.57);
```

I think we can just hard-code the values instead of changing the number we divide by.

**Review by aaronfranke — APPROVED** [review]
Needs [a squash](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html) but otherwise the code looks good to me.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.
