### PR TITLE
Thread: Re-add `<new>` include for `std::hardware_destructive_interference_size`

### LINKED ISSUE #100768: Godot crash on Linux when compiled with GCC 12
### Tested versions

Launch Godot.
I compiled Godot master from git using this settings:

```
       _,met$$$$$gg.          binogure@binogure 
    ,g$$$$$$$$$$$$$$$P.       ----------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux trixie/sid x86_64 
 ,$$P'              `$$$.     Host: A520 AORUS ELITE 
',$$P       ,ggs.     `$$b:   Kernel: 6.11-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 8 hours, 35 mins 
 $$P      d$'     ,    $$P    Packages: 4712 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.2.37 
 $$;      Y$b._   _,d$P'      Resolution: 2560x1440, 2560x1440 
 Y$$.    `.`"Y$$$$P"'         DE: Cinnamon 6.2.9 
 `$$b      "-.__              WM: Mutter (Muffin) 
  `Y$$                        WM Theme: cinnamon (Default) 
   `Y$$.                      Theme: Adwaita [GTK2/3] 
     `$$b.                    Icons: gnome [GTK2/3] 
       `Y$$b.                 Terminal: terminator 
          `"Y$b._             CPU: AMD Ryzen 7 5800X (16) @ 4.851GHz 
              `"""            GPU: NVIDIA GeForce RTX 3070 
                              Memory: 18014MiB / 64226MiB 
gcc (Debian 12.2.0-14) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
gcc (Debian 12.2.0-14) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Using git bisect, it seems that this commit causes the crash:
be86ce3103d92e4f7a625cbf11866266473ac99c

### System information

Linux binogure 6.11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.11-1~exp1 (2024-09-19) x86_64 GNU/Linux

### Issue description

Launch Godot and it crashes on a SIGSEGV:
```
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.4.dev.custom_build (be86ce3103d92e4f7a625cbf11866266473ac99c)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
```

### Steps to reproduce

Launch Godot on Linux

https://github.com/user-attachments/assets/3406bc5a-0f10-402b-9353-ccde9003e852

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by akien-mga**
Somehow it would still build fine, but would crash when compiled with GCC 12.2 on Debian 12.

Also re-add wrongly removed Mutex include from `thread_safe.h`, where it's used in macros.
    
Add IWYU pragma comments to prevent it from mistakenly flagging those as unused.

- Fixes #100768.
- Fixes up #100564 which introduced the regression.

CC @RandomShaper @hpvb 
I still don't know *why* it would compile OK without `<new>`, but then crash, but I've confirmed that this patch fixes the crash with Debian 12's GCC 12.2.0.

### CODE REVIEW

File: core/os/thread_safe.h [hunk 1]
```diff
@@ -31,6 +31,8 @@
 #ifndef THREAD_SAFE_H
 #define THREAD_SAFE_H
 
+#include "core/os/mutex.h" // IWYU pragma: keep // Used in macro.
```
Comment (akien-mga) [inline core/os/thread_safe.h:34]: CC @Repiteo, I took this format from #100918.

Does that work for `clangd` too and not just `include-what-you-use`?

File: core/os/thread.h [hunk 2]
```diff
@@ -29,19 +29,30 @@
...
-#include "core/templates/safe_refcount.h"
 #include "core/typedefs.h"
 
+#ifdef THREADS_ENABLED
+
+#include "core/templates/safe_refcount.h"
+
+#if defined(__cpp_lib_hardware_interference_size) && !defined(ANDROID_ENABLED)
+#include <new> // For CACHE_LINE_BYTES.
+#endif
```
Comment (akien-mga) [inline core/os/thread.h:54]: I'm assuming that adding the `#if` conditions matching where it's used will prevent tools like clangd to iwyu from flagging this as unused when run on platforms which don't fulfill that condition (seems to be GCC specific, possibly supported on Clang, but thus not MSVC most likely).

If not, we should add a pragma comment to prevent its removal, but then I wouldn't trust the judgement of those tools.

**Comment by akien-mga** [comment]
I went maybe a tiny bit heavy handed on tweaking code style / `#ifdef`s in a critical bugfix, so to be clear the minimal fix is just this:
```diff
diff --git a/core/os/thread.h b/core/os/thread.h
index 066c4befa7..1c442b41f6 100644
--- a/core/os/thread.h
+++ b/core/os/thread.h
@@ -42,6 +42,8 @@
 #include "core/templates/safe_refcount.h"
 #include "core/typedefs.h"
 
+#include <new>
+
 #ifdef MINGW_ENABLED
 #define MINGW_STDTHREAD_REDUNDANCY_WARNING
 #include "thirdparty/mingw-std-threads/mingw.thread.h"
diff --git a/core/os/thread_safe.h b/core/os/thread_safe.h
index 316b0c9687..042a0b7d98 100644
--- a/core/os/thread_safe.h
+++ b/core/os/thread_safe.h
@@ -31,6 +31,8 @@
 #ifndef THREAD_SAFE_H
 #define THREAD_SAFE_H
 
+#include "core/os/mutex.h"
+
 #define _THREAD_SAFE_CLASS_ mutable Mutex _thread_safe_;
 #define _THREAD_SAFE_METHOD_ MutexLock _thread_safe_method_(_thread_safe_);
 #define _THREAD_SAFE_LOCK_ _thread_safe_.lock();
```

This PR should be equivalent to that diff if I didn't mess up.

**Comment by akien-mga** [comment]
Taking back as draft for a bit, the latest iteration of my PR doesn't seem to fix the crash anymore... Seems like some of the harmless refactoring I've done may have caused harm? Or the problem is deeper than I thought.

File: core/os/thread.h (hunk 2 above)
Comment (akien-mga) [reply core/os/thread.h:54]: Ok this is what broke my fix, to test `__cpp_lib_hardware_interference_size` we first need to include `<new>`.

So pragma comment it will be.

File: core/os/thread_safe.h (hunk 1 above)
Comment (Repiteo) [reply core/os/thread_safe.h:34]: It indeed worked for `clangd`, so much so that it's part of their guidelines:

https://clangd.llvm.org/guides/include-cleaner#scenarios-and-solutions

**Comment by akien-mga** [comment]
OK I fixed the issue, the include of `<new>` can't be made conditional on `defined(__cpp_lib_hardware_interference_size)` because `<new>` is needed to check that feature.

Which hints to why everything compiled fine despite the removal of `<new>`. It meant that (at least occasionally) we were falling back to the `#else` case here:
```cpp
#if defined(__cpp_lib_hardware_interference_size) && !defined(ANDROID_ENABLED) // This would be OK with NDK >= 26.
#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winterference-size"
#endif
        static constexpr size_t CACHE_LINE_BYTES = std::hardware_destructive_interference_size;
#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic pop
#endif
#else
        // At a negligible memory cost, we use a conservatively high value.
        static constexpr size_t CACHE_LINE_BYTES = 128;
#endif
```

Either it doesn't work properly, or we're mixing both branches depending on whether `thread.h` is included in code that already includes `<new>` or not.

I made this quick test to confirm:

```diff
diff --git a/core/os/thread.h b/core/os/thread.h
index 066c4be..6d1ac06 100644
--- a/core/os/thread.h
+++ b/core/os/thread.h
@@ -90,11 +90,13 @@ public:
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Winterference-size"
 #endif
+       #warning Good branch.
        static constexpr size_t CACHE_LINE_BYTES = std::hardware_destructive_interference_size;
 #if defined(__GNUC__) && !defined(__clang__)
 #pragma GCC diagnostic pop
 #endif
 #else
+       #warning Bad branch.
        // At a negligible memory cost, we use a conservatively high value.
        static constexpr size_t CACHE_LINE_BYTES = 128;
 #endif

```

Here are the full build logs: 
[godot-thread-build.log](https://github.com/user-attachments/files/18286815/godot-thread-build.log)

There's indeed a few "Bad branches." in there:
```
$ cat ~/godot-thread-build.log | grep "Good branch" | wc -l
2462
$ cat ~/godot-thread-build.log | grep "Bad branch" | wc -l
44
```

Including `<new>` explicitly prevents this, but this hints that we might have more such problems in the codebase where a file is wrongly compiled taking diverging code paths, and the consequences can be disastrous, as seen here. We should really look into this and see if we can detect and prevent this.

**Review by Repiteo — APPROVED** [review]

**Comment by fire** [comment]
> Somehow it would still build fine, but would crash when compiled with GCC 12.2 on Debian 12.

I think the only way is build with Github actions, and then test with a benchmark server with a gpu, but it might to be too expensive.

**Review by RandomShaper — APPROVED** [review]
