### PR TITLE
GDScript: Track columns by raw string offsets

### LINKED ISSUE #117546: Starting a file with a tab followed by any character causes "Unicode parsing error"
### Tested versions

Reproducible in v4.6.1.stable.arch_linux [14d1969]  and the current master branch: v4.7.dev.custom_build [29d2c7ece] 

### System information

Godot v4.6.1.stable (14d1969) - Arch Linux #1 SMP PREEMPT_DYNAMIC Mon, 09 Feb 2026 17:16:33 +0000 on Wayland - Wayland display driver, Single-window, 2 monitors - OpenGL 3 (Compatibility) - AMD Radeon 780M Graphics (radeonsi, phoenix, LLVM 21.1.6, DRM 3.64, 6.18.9-arch1-2) - AMD Ryzen 7 8745HS w/ Radeon 780M Graphics (16 threads) - 28.18 GiB memory

### Issue description

Starting a file with a tab followed by any character causes the console to spam

related to https://github.com/godotengine/godot/issues/79806

```
ERROR: Unicode parsing error, some characters were replaced with � (U+FFFD): Unexpected NUL character
```

https://github.com/user-attachments/assets/3d42cf3e-16a7-43b5-853e-8eeada2b1337

### Steps to reproduce

1. Create a new gdscript file
2. Make the first line blank
3. Make sure your indentation is set to tabs in the editor settings
4. Press the tab key
5. Type any character, like "t"
6. Console gets spammed

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by HolonProduction**
GDScript keeps track of the position of tokens/nodes/errors/..., however at the moment the column of this position counts tab characters not as one character but by the currently configured tab width. This PR changes this tracking to always count tabs as a single character in position information.

With this PR GDScript still tracks positions one-based while other systems use zero-based positions. It's not worth changing that, the conversion isn't complex and there is a lot more stuff which relies on line numbers.

This PR also includes a fix to the functionality from https://github.com/godotengine/godot/pull/75216 to actually get the links to jump to the right positions.

### Motivation

This current position format is pretty unusual and requires conversions in adjacent systems. This change in particular is motivated by the language server.

In order to convert positions from the parser to something we can send to external editors we always need to be aware of the associated source code. Without going into detail, this isn't exactly great if we want to share more code and utilities between the builtin editor and the LSP implementation.

_Triage edit: Fixes https://github.com/godotengine/godot/issues/117546_

### CODE REVIEW

**Review by bruvzg — APPROVED** [review]
Fixes https://github.com/godotengine/godot/issues/117546, code looks good. Have not checked language server part.

File: editor/gui/code_editor.cpp [hunk 1]
```diff
@@ -1586,18 +1576,22 @@ Point2i CodeTextEditor::get_error_pos() const {
...
-		const String line_text = text_editor->get_line(error_line);
-		const int indent_size = text_editor->get_indent_size();
-		if (indent_size > 1) {
-			const int tab_count = line_text.length() - line_text.lstrip("\t").length();
-			corrected_column -= tab_count * (indent_size - 1);
-		}
+	const String line_text = text_editor->get_line(p_internal_position.x);
+	const int indent_size = text_editor->get_indent_size();
+	if (indent_size > 1) {
+		const int tab_count = line_text.count("\t", 0, error_column);
```
Comment (kitbdev) [inline editor/gui/code_editor.cpp]:
```suggestion
		const int tab_count = line_text.count("\t", 0, corrected_column);
```

Comment (HolonProduction) [reply editor/gui/code_editor.cpp]: Good catch.

File: editor/gui/code_editor.cpp [hunk 2]
```diff
@@ -1586,18 +1576,22 @@ Point2i CodeTextEditor::get_error_pos() const {
...
-		const String line_text = text_editor->get_line(error_line);
-		const int indent_size = text_editor->get_indent_size();
-		if (indent_size > 1) {
-			const int tab_count = line_text.length() - line_text.lstrip("\t").length();
-			corrected_column -= tab_count * (indent_size - 1);
-		}
+	const String line_text = text_editor->get_line(p_internal_position.x);
+	const int indent_size = text_editor->get_indent_size();
+	if (indent_size > 1) {
+		const int tab_count = line_text.count("\t", 0, corrected_column);
```
Comment (kitbdev) [inline editor/gui/code_editor.cpp]:
```suggestion
	if (indent_size > 1 && corrected_column > 0) {
		const int tab_count = line_text.count("\t", 0, corrected_column);
```
String `count` searches the entire string if the to column is 0, so this needs to be skipped in that case.

File: editor/gui/code_editor.cpp [hunk 3]
```diff
@@ -1586,18 +1576,22 @@ Point2i CodeTextEditor::get_error_pos() const {
...
+		corrected_column += tab_count * (indent_size - 1);
```
Comment (kitbdev) [inline editor/gui/code_editor.cpp]: This approach is better than the previous one since it accounts for tabs after the start of the line, but it's not completely correct either.
Tabs aren't always `indent_size`, they stop at tab boundaries even if there are already some characters before it.

It would have to iterate over the line and keep track of the tab alignment to get the proper column, if there are tabs after any non-tabs.

Comment (kitbdev) [inline editor/gui/code_editor.cpp]: This approach is better than before where it only considered the start of the line, but it still isn't completely correct to get the visual column.
I don't think gdscript handled this correctly previously either.

Tabs aren't always 4 characters wide, they can be smaller for tab alignment.
So if there are tabs after the start of the string, this should iterate over the line to count the column and keep track of the alignment.
Edit: github didn't show me the previous version of this comment so I thought it didn't save and rewrote it, but now that one is back.

**Review by kitbdev — COMMENTED** [review]
If I have mixed tabs and indentation at the start of the file, the error uses a line far outside the file. On master it says at the error is at (0, 0). (script is only 166 lines here, but the error says 8119 despite the error happening at line 1):

Image

File: editor/gui/code_editor.cpp (hunk 3 above)
Comment (HolonProduction) [reply editor/gui/code_editor.cpp]: Done

**Review by kitbdev — APPROVED** [review]
Tested with internal editor and external editor over lsp, looks good.
Makes sense to use char based columns internally as much as possible and visual columns just for display.

**Comment by HolonProduction** [comment]
> Did you change them to 0-based?

No, this PR only changes how columns are counted in regards to tabs. Positioning is still one-based in GDScript/`ScriptLanguage`, while other parts of the engine use zero based positions.

Edit: Slight correction, some parts of the `ScriptLanguage` API also use zero based positions (`find_function`), it's kinda a mess.

File: modules/gdscript/tests/test_gdscript.cpp [hunk 4]
```diff
@@ -65,19 +65,19 @@ static void test_tokenizer(const String &p_code, const Vector<String> &p_lines)
...
 
-			int line_width = 0;
-			if (current.start_line - 1 >= 0 && current.start_line - 1 < p_lines.size()) {
-				line_width = p_lines[current.start_line - 1].replace("\t", tab).length();
-			}
-
-			const int offset = MAX(0, current.start_column - 1);
-			const int width = MAX(0, line_width - current.start_column + 1);
-			pointer += String::chr(' ').repeat(offset) + String::chr('v').repeat(width);
+			const int line_width = start_line.length() + start_line.count("\t") + (tab_size - 1);
```
Comment (dalexeev) [inline modules/gdscript/tests/test_gdscript.cpp:77]: `count("\t")` isn't entirely correct because the tab width depends on the column it starts in. Perhaps we should add a helper method?

```c++
static int get_visual_column(const String &p_line, int p_raw_column) { ... }
```

**Review by dalexeev — COMMENTED** [review]
Looks good to me, but I haven't tested this. It seems to make more sense from the editor's perspective (while we still display the traditional "visual" 1-based lines and columns to users).

Perhaps in the future we should use a more structured approach (like `SourcePosition` and `SourceRegion` in my example). This would allow us to encapsulate the logic. But for now, this is probably too significant a change.

File: modules/gdscript/tests/test_gdscript.cpp (hunk 4 above)
Comment (HolonProduction) [reply modules/gdscript/tests/test_gdscript.cpp:77]: It is not correct for the builtin editor, and there a different calculation is utilized. In this specific context it's correct since we do this:
```c++
String tab = String(" ").repeat(tab_size);
...
print_line(vformat("%04d %s", l, p_lines[l - 1]).replace("\t", tab));
```

It's a tool for debugging, it handles well formatted GDScript correctly. No need to reinvent the wheel here IMO

Comment (dalexeev) [reply modules/gdscript/tests/test_gdscript.cpp:77]: Tabs can appear in the middle of a line. You're right that an internal debugging tool isn't a high priority, but I'd still consider this case.

Comment (HolonProduction) [reply modules/gdscript/tests/test_gdscript.cpp:77]: I guess I can fix the tab substitution as well. But I'd prefer not to touch unrelated code and fix this in a followup.

Comment (dalexeev) [reply modules/gdscript/tests/test_gdscript.cpp:77]: I'm not insisting on it. We can fix it later, it's not a blocker.

Comment (HolonProduction) [reply modules/gdscript/tests/test_gdscript.cpp:77]: Alright then I'll do a followup for handling mid line tabs correctly.

**Review by dalexeev — APPROVED** [review]

**Comment by Repiteo** [comment]
Needs rebase; getting compilation errors from `GodotRange::to_lsp` argument size discrepancies

**Comment by HolonProduction** [comment]
Done

**Comment by Repiteo** [comment]
Thanks!

**Comment by nikitalita** [comment]
Doesn't this require the bytecode version being bumped? Binary scripts of previous versions will no longer parse correctly due to this, the column numbers will be wrong and would lead to parsing errors.

**Comment by HolonProduction** [comment]
I was under the impression, that binary tokenization does not encode column information.

Do you have an MRP?

**Comment by nikitalita** [comment]
> I was under the impression, that binary tokenization does not encode column information.

It does. See here: https://github.com/HolonProduction/godot/blob/612475a680178afc6910687c616a054664ccc8f2/modules/gdscript/gdscript_tokenizer_buffer.cpp#L342

**Comment by HolonProduction** [comment]
Ah fair, I guess I only checked `_token_to_binary`.

After taking a closer look I'm still not convinced a version bump is needed. Columns seem to be exclusively used for indentation purposes, as long as they are consistent within the file everything should work fine.

Or put differently, a tab indented script tokenized on a previous version will result in the same bytecode as a space indented script tokenized on a version containing this PR. So there should be no issues parsing those old files. Am I missing something?
