### PR TITLE
[3.x] Fix RichTextLabel discards appended BBCode text on window resize when using DynamicFont

### LINKED ISSUE #62640: RichTextLabel's BBCode is reset to the initial value when the window is resized if a DynamicFont is used
### Godot version

3.5 RC 5

### System information

Windows (I think it's not matter)

### Issue description

A RichTextLabel using a DynamicFont and bbcode_enabled = true if at start in scene inspector bbcode_text was not empty will reset to the initial value its text on resizing the window. This happens when the text is set with append_bbcode or add_text.

Looks like an old problem #22203

### Steps to reproduce

Create a RichTextLabel and give it a DynamicFont. Enable BBCode, enter some text in bbcode_text inspector property. And call append_bbcode. Text will be reset on resizing the window.

### Minimal reproduction project

[https://github.com/mishkarch/RichTextLabelBug](https://github.com/mishkarch/RichTextLabelBug)
Press space to add some text to initial text then resize the window.

### PR DESCRIPTION
**Pull request by OsakiTsukiko**
Fixes #62640

### CODE REVIEW

**Comment by OsakiTsukiko** [comment]
I think that should fix the formatting issue

File: scene/gui/control.h [hunk 1]
```diff
@@ -265,8 +265,7 @@ class Control : public CanvasItem {
 public:
 	enum {
 
-		/*		NOTIFICATION_DRAW=30,
-		NOTIFICATION_VISIBILITY_CHANGED=38*/
+		// NOTIFICATION_VISIBILITY_CHANGED=38
```
Comment (bruvzg) [inline scene/gui/control.h:268]: I guess `NOTIFICATION_DRAW` was here to indicate full CanvasItem notification range, to avoid overlaps if it's changed. In any case, it's completely unrelated to the issue, and probably should be left intact.

**Review by bruvzg — APPROVED** [review]

File: scene/gui/control.h (hunk 1 above)
Comment (OsakiTsukiko) [reply scene/gui/control.h:268]: Yea, I don't really remember why I removed that, ill add it back.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.2.
