### PR TITLE
Make `Mesh::generate_triangle_mesh()` handle `PRIMITIVE_TRIANGLE_STRIP`

### LINKED ISSUE #61552: SurfaceTool triangle strips don't create faces in a Mesh
### Godot version

3.4.4.stable.mono

### System information

Windows 10 21H1

### Issue description

I'm creating a triangle strip along a curve with SurfaceTool, committing it to a MeshArray, then assigning that to a MeshInstance. If I use the `TriangleStrip` primitive type, subsequently calling `CreateTrimeshCollision()` on the MeshInstance fails, and the Mesh says it has zero faces despite rendering properly. If I instead use the `Triangles` primitive type and include duplicate verts appropriately (012132 instead of 0123), everything works as expected. I first suspected this was related to #38391, but the fix there of calling `Mesh.GetFaces().Count()` does nothing and still reports zero faces.

### Steps to reproduce

* Create a SurfaceTool using `Mesh.PrimitiveType.TriangleStrip`.
* With it, create a quad:
```cs
st.AddNormal(Vector3.Up);
st.AddVertex(Vector3.Right);
st.AddNormal(Vector3.Up);
st.AddVertex(Vector3.Zero);
st.AddNormal(Vector3.Up);
st.AddVertex(Vector3.Forward + Vector3.Right);
st.AddNormal(Vector3.Up);
st.AddVertex(Vector3.Forward);
```
* `AddIndex()` may be used here but is redundant with the ordering given.
* `Commit()` it to an ArrayMesh and assign that to a MeshInstance.
* Call `CreateTrimeshCollision()` on the MeshInstance. This should error and produce nothing.
* Change the primitive type to `Triangles` and add the following before committing:
```cs
st.AddIndex(0);
st.AddIndex(1);
st.AddIndex(2);
st.AddIndex(1);
st.AddIndex(3);
st.AddIndex(2);
```
* This should run fine and produces a collision mesh as expected.
The included repro project generates with `Triangles` by default. To use `TriangleStrip`, comment the call to `STTriangles()` and uncomment the call to `STTriStrip()`.

### Minimal reproduction project

[STTest.zip](https://github.com/godotengine/godot/files/8801573/STTest.zip)

### PR DESCRIPTION
**Pull request by kleonc**
Enhacement: makes `Mesh::generate_triangle_mesh()` handle `PRIMITIVE_TRIANGLE_STRIP` (besides already supported `PRIMITIVE_TRIANGLES`).

Bugfix: now `Mesh::generate_triangle_mesh()` ignores surfaces with incorrect vertex/index count and shows an error for each such surface. Previously it was checking only the total amount of vertices/indices (sum of counts) so for example it wouldn't error out when having 2 surfaces with 1 and 2 vertices respectively, it would incorrectly deduce it's 1 triangle (1+2=3 vertices/indices).

Fixes #61552.

### CODE REVIEW

File: scene/resources/mesh.cpp [hunk 1]
```diff
@@ -161,32 +161,45 @@ Ref<TriangleMesh> Mesh::generate_triangle_mesh() const {
...
+				int len = (surface_get_format(i) & ARRAY_FORMAT_INDEX) ? surface_get_array_index_len(i) : surface_get_array_len(i);
+				// Don't error if zero, it's valid (we'll just skip it later).
+				ERR_CONTINUE_MSG((len % 3) != 0, vformat("Ignoring surface %d, incorrect %s count: %d (for PRIMITIVE_TRIANGLES).", i, (surface_get_format(i) & ARRAY_FORMAT_INDEX) ? "index" : "vertex", len));
+				faces_size += len;
+			} break;
+			case PRIMITIVE_TRIANGLE_STRIP: {
+				int len = (surface_get_format(i) & ARRAY_FORMAT_INDEX) ? surface_get_array_index_len(i) : surface_get_array_len(i);
+				// Don't error if zero, it's valid (we'll just skip it later).
+				ERR_CONTINUE_MSG(len != 0 && len < 3, vformat("Ignoring surface %d, incorrect %s count: %d (for PRIMITIVE_TRIANGLE_STRIP).", i, (surface_get_format(i) & ARRAY_FORMAT_INDEX) ? "index" : "vertex", len));
+				faces_size += (len == 0) ? 0 : (len - 2) * 3;
```
Comment (clayjohn) [inline scene/resources/mesh.cpp:178]: Is it possible for ``len`` to equal 1? If so, this will need to handle that case as well. could just change ``len == 0`` to ``len <= 1``

Comment (akien-mga) [reply scene/resources/mesh.cpp:178]: There's an err check on the previous line that indeed ensures it won't be < 3.

**Review by clayjohn — APPROVED** [review]
Looks good to me!
