### PR TITLE
Fixed issues with using a relative path in the export window.

### LINKED ISSUE #31427: File dialog gets stuck on the path of the first selected preset in export dialog
**Godot version:**
afecc0b

**Issue description:**
On the "Export" dialog, the first selected preset's export path will always be the one showing in the file dialog when exporting a project, while selecting others unable to change it.

From the testing I did, the problem seems to be with the `EditorFileDialog` itself, as the select paths are sent to it, but it fails to acknowledge them. Here's the line if anyone want to try their luck:
https://github.com/godotengine/godot/blob/afecc0bc2283dfbfbce70ae95c28e0ed4ecd4160/editor/project_export.cpp#L944

### LINKED ISSUE #33567: the export path in export window does not work.
**Godot version:**
3.2 beta1

**OS/device including version:**

**Issue description:**
Whatever the path set, when click export project, the current directory is alway the project root folder.

**Steps to reproduce:**

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by Catchawink**
This fix addresses issue #33567. Before this fix, opening relative export paths inside of an EditorFileDialog was broken. This fix improves how relative paths are saved in EditorExportPreset and how relative paths are opened in EditorFileDialog.

*Bugsquad edit:*
Fixes #33567.
Fixes #31427.

### CODE REVIEW

File: editor/editor_export.cpp [hunk 1]
```diff
@@ -151,7 +151,7 @@ void EditorExportPreset::set_export_path(const String &p_path) {
 	/* NOTE(SonerSound): if there is a need to implement a PropertyHint that specifically indicates a relative path,
 	 * this should be removed. */
 	if (export_path.is_abs_path()) {
-		String res_path = OS::get_singleton()->get_resource_dir();
+		String res_path = OS::get_singleton()->get_resource_dir()+"/";
```
Comment (akien-mga) [inline editor/editor_export.cpp]: Style issue, there should be spaces around `+`.

Is the extra `/` always needed, or only if `get_resource_dir()` somehow lacks it?
If it's the latter, you can use `plus_file("")`, which is a hacky way to ensure that `/` is appended only if it's missing (so we don't end up with `some/path//`).

Comment (akien-mga) [reply editor/editor_export.cpp]: Alternatively, `path_to_file()` could maybe be fixed to properly add a directory separator if the String it operates on lacks it?

**Comment by akien-mga** [comment]
Might also fix #31427 (which #33567 might be a duplicate of) and thus supersede #31840 (which I meant to review in depth as I have a feeling that the String changes are overkill, but I never got to it...). CC @SonerSound

File: editor/editor_export.cpp (hunk 1 above)
Comment (Catchawink) [reply editor/editor_export.cpp]: It looks like when the value of `get_resource_dir()` is initialized the slash on the end is consistently removed (see line 460 of project_settings.cpp).

For sure, `path_to_file()` could be modified to include `plus_file("")`. That sounds better if `get_resource_dir()` is one of many directory paths lacking a `/` at the end. I'm not sure though.

Comment (akien-mga) [reply editor/editor_export.cpp]: > For sure, `path_to_file()` could be modified to properly add a separator. That sounds better if `get_resource_dir()` is one of many directory paths lacking a separator at the end. I'm not sure if that's the case, though.

`path_to_file` is not part of the public scripting API for String, but it's exposed in GDNative, so in theory GDNative plugins can call it, and might do it with non slash-terminated paths.

I would expect `"/home/akien".path_to_file("bin/godot")` to give me `/home/akien/bin/godot` (otherwise I might just as well use `+`), so IMO it's best to fix this one instead of fixing all calling sites.

Comment (akien-mga) [reply editor/editor_export.cpp]: Something like this might work:
```diff
diff --git a/core/ustring.cpp b/core/ustring.cpp
index 6a1dc2295f..345db0eb13 100644
--- a/core/ustring.cpp
+++ b/core/ustring.cpp
@@ -3792,7 +3792,8 @@ bool String::is_valid_float() const {
 
 String String::path_to_file(const String &p_path) const {
 
-	String src = this->replace("\\", "/").get_base_dir();
+	// Don't get base dir for src, this is expected to be a dir already.
+	String src = this->replace("\\", "/");
 	String dst = p_path.replace("\\", "/").get_base_dir();
 	String rel = src.path_to(dst);
 	if (rel == dst) // failed
diff --git a/editor/editor_file_dialog.cpp b/editor/editor_file_dialog.cpp
index 7fc989b5e9..7bf7cd17ec 100644
--- a/editor/editor_file_dialog.cpp
+++ b/editor/editor_file_dialog.cpp
@@ -958,6 +958,9 @@ String EditorFileDialog::get_current_path() const {
 }
 void EditorFileDialog::set_current_dir(const String &p_dir) {
 
+	if (p_dir.is_rel_path()) {
+		dir_access->change_dir(OS::get_singleton()->get_resource_dir());
+	}
 	dir_access->change_dir(p_dir);
 	update_dir();
 	invalidate();
```

Comment (akien-mga) [reply editor/editor_export.cpp]: I can confirm that the above patch fixes both #31840 and #31427.
Would you mind amending the commit to do those changes?

Comment (Catchawink) [reply editor/editor_export.cpp]: Awesome, fixed!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
