### PR TITLE
Mono/C#: Add Basis.Slerp, update Quat.Xform and add some math checks

### LINKED ISSUE #35448: Quaternion Xform returns unexpected result in C#
**Godot version:**
3.2 Beta 4 Godot mono.
**OS/device including version:**
Linux Mint 18.3 "Sylvia"
**Issue description:**
I was playing aroud with Quat class and found out that results of Xfom function are not equal the one I get in online calculators [(eg. here)](https://www.andre-gaschler.com/rotationconverter/).
**Steps to reproduce:**
```
Quat q3 = new Quat(1, 1, 1, 1);
Vector3 v3_3 = q3.Xform(new Vector3(1, 1, 1));
Assert.Equal(v3_3, new Vector3(1, 1, 1));
```
**Minimal reproduction project:**
It is possible to send you the whole project if needed. Please contact me.

### PR DESCRIPTION
**Pull request by neikeq**
Fixes #35448

### CODE REVIEW

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs [hunk 1]
```diff
@@ -387,6 +387,19 @@ public Basis Scaled(Vector3 scale)
             return b;
         }
 
+        public Basis Slerp(Basis target, real_t t)
+        {
+	        var from = new Quat(this);
```
Comment (akien-mga) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs]: Indentation issue.

**Review by akien-mga — APPROVED** [review]
