### PR TITLE
Fix renaming directories

### LINKED ISSUE #48254: In Godot 3.3.2, scripts cannot use rename() to change folder names
**Godot version:**

3.3.2

**OS/device including version:**

windows10

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

Godot 3.3中无法使用rename对文件夹进行重命名，但是对文件可以。对文件夹进行重命名时，系统报错为：file_exists()所选文件不存在。本人推测是将文件夹作为文件进行判断，我对Godot进行卸载重装，依然是这样。在3.2.3版本中没有出现这个错误

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #48254

Seems like `dir_exists()` is less strict with names, e.g. "" or ".." are valid directories even though it will result in the same bug as #41623, so I added some basic checks for invalid paths.

### CODE REVIEW

File: core/core_bind.cpp [hunk 1]
```diff
@@ -1560,15 +1560,17 @@ Error _Directory::copy(String p_from, String p_to) {
 
 Error _Directory::rename(String p_from, String p_to) {
 	ERR_FAIL_COND_V_MSG(!is_open(), ERR_UNCONFIGURED, "Directory must be opened before use.");
+	ERR_FAIL_COND_V_MSG(p_from.is_empty() || p_from == "." || p_from == "..", ERR_INVALID_PARAMETER, "Invalid path to rename.");
+
 	if (!p_from.is_rel_path()) {
 		DirAccess *d = DirAccess::create_for_path(p_from);
-		ERR_FAIL_COND_V_MSG(!d->file_exists(p_from), ERR_DOES_NOT_EXIST, "File does not exist.");
+		ERR_FAIL_COND_V_MSG(!d->file_exists(p_from) && !d->dir_exists(p_from), ERR_DOES_NOT_EXIST, "File nor directory does not exist.");
```
Comment (akien-mga) [inline core/core_bind.cpp:1567]:
```suggestion
		ERR_FAIL_COND_V_MSG(!d->file_exists(p_from) && !d->dir_exists(p_from), ERR_DOES_NOT_EXIST, "File or directory does not exist.");
```

**Comment by akien-mga** [comment]
Maybe also update the doc which currently only mentions files.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.3.
