### PR TITLE
Fix errors when removing non Control node from TabContainer

### LINKED ISSUE #45105: Errors when removing child of tabcontainer
**Godot version:**
3.2.4.beta.custom_build. a64ffa3a3

**Issue description:**
When removing node placed under TabContainer node, then this error is shown
```
ERROR: _disconnect: Attempt to disconnect a nonexistent connection to signal 'renamed' in [PopupDialog:8265], with target '_child_renamed_callback' in [TabContainer:7964].
   At: core/object.cpp:1569.
```
**Steps to reproduce:**
1. Add Tabcontainer node
2. Add as child Spatial node
3. Remove Spatial node

### PR DESCRIPTION
**Pull request by qarmin**
Fixes https://github.com/godotengine/godot/issues/45105

In `add_child_notify`, only Control based nodes have connected signal `renamed`, but in `remove_child_notify` for all nodes disconnect function is executed

### CODE REVIEW

File: scene/gui/tab_container.cpp [hunk 1]
```diff
@@ -789,6 +789,11 @@ Control *TabContainer::get_current_tab_control() const {
 void TabContainer::remove_child_notify(Node *p_child) {
 	Container::remove_child_notify(p_child);
 
+	Control *c = Object::cast_to<Control>(p_child);
+	if (!c) {
```
Comment (akien-mga) [inline scene/gui/tab_container.cpp:793]: Maybe this since we don't need `c` further down:
```suggestion
	if (!Object::cast_to<Control>(p_child)) {
```

**Comment by akien-mga** [comment]
For the reference, there's also a `move_child_notify` function which could use similar logic? I don't know if that would impact any of the container's functionality though.

**Review by groud — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
