### PR TITLE
Android: Don't request `CAMERA` permission on editor startup

### LINKED ISSUE #106461: Unnecessary permission requests occur in the Android editor.
### Tested versions

- Reproduciblein: 4.5.dev [b7b3a1a78ad07591fa64e471ef5d42c1166e33e7]

### System information

Godot v4.5.dev (6b6452fec) - Android - Single-window, 1 monitor - Vulkan (Mobile) - integrated Adreno (TM) 650 - (8 threads)

### Issue description

The first time the editor is run on Android, it requests camera and video recording permissions.
https://github.com/godotengine/godot/pull/106094#issuecomment-2884941303

### Steps to reproduce

1. Uninstall the existing godot.apk if it's installed.
1. Install godot.apk.

### Minimal reproduction project (MRP)

Not relevant (editor issue).

### PR DESCRIPTION
**Pull request by shiena**
fixed #106461
Preventing the camera permission request on Android editor startup. Now, the permission prompt will only appear when `OS.request_permission("CAMERA")` is called in the editor.
relation: https://github.com/godotengine/godot/pull/106094#issuecomment-2884941303

### CODE REVIEW

File: platform/android/java/editor/src/main/java/org/godotengine/editor/BaseGodotEditor.kt [hunk 1]
```diff
@@ -190,6 +190,7 @@ abstract class BaseGodotEditor : GodotActivity(), GameMenuFragment.GameMenuListe
 			// The RECORD_AUDIO permission is requested when the "audio/driver/enable_input" project
 			// setting is enabled.
 			Manifest.permission.RECORD_AUDIO,
+			Manifest.permission.CAMERA,
```
Comment (m4gr3d) [inline platform/android/java/editor/src/main/java/org/godotengine/editor/BaseGodotEditor.kt:193]: Can you add a comment to describe when the `CAMERA` permission is being used for the editor.

**Review by m4gr3d — APPROVED** [review]
Looks good!

File: platform/android/java/editor/src/main/java/org/godotengine/editor/BaseGodotEditor.kt [hunk 2]
```diff
@@ -190,6 +190,7 @@ abstract class BaseGodotEditor : GodotActivity(), GameMenuFragment.GameMenuListe
 			// The RECORD_AUDIO permission is requested when the "audio/driver/enable_input" project
 			// setting is enabled.
```
Comment (JimmyCushnie) [inline platform/android/java/editor/src/main/java/org/godotengine/editor/BaseGodotEditor.kt:191]: This comment should be updated to also explain the new CAMERA permission being added.

**Comment by akien-mga** [comment]
Could you amend the commit message to be a bit more explicit (it should mention Android, and editor startup, so there's proper context). Just copying the PR title should be good.

File: platform/android/java/editor/src/main/java/org/godotengine/editor/BaseGodotEditor.kt (hunk 1 above)
Comment (shiena) [reply platform/android/java/editor/src/main/java/org/godotengine/editor/BaseGodotEditor.kt:194]: Comment added on `CAMERA` permission.

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
