### PR TITLE
Fix shift clicking on Add Sun/Environment to Scene buttons

### LINKED ISSUE #73467: Shift-clicking "Add Sun to Scene" or "Add Environment to Scene" no longer adds both sun and environment at the same time
### Godot version

4.0.rc2

### System information

Fedora 37, GeForce RTX 4090 (NVIDIA 525.85.05)

### Issue description

Prior to 4.0.beta17, you could hold <kbd>Shift</kbd> to add both the current preview sun and environment to the scene when clicking either **Add Sun to Scene** or **Add Environment to Scene** in the 3D editor's preview sky/environment editor:

image

This feature no longer works since 4.0.beta17. If I hold <kbd>Shift</kbd> while clicking, it acts as if it wasn't holding <kbd>Shift</kbd> and will only add the sun or environment (which matches whichever button I clicked).

This feature is useful to add both sun and environment with a single click, speeding up the setup of simple test projects (useful for MRPs and prototyping).

I bisected the regression to 9f426498231816ccb9d686b3944373f61312aa24. cc @bruvzg

### Steps to reproduce

- Ensure the preview sun and sky are enabled, so you can edit them and add them to the current scene. Also make sure there is neither a WorldEnvironment nor a DirectionalLight3D node in the current scene.
- Click the 3 vertical dots icon at the top of the 3D editor viewport, next to the globe.
- Hold <kbd>Shift</kbd> and click **Add Sun to Scene** or **Add Environment to Scene**.
- Notice it only adds one node, while it's supposed to add both. Test this in previous 4.0 betas for comparison.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Giganzo**
Believe this fixes: https://github.com/godotengine/godot/issues/73467
Only tested on Linux

First is a single click, second is shift click.

[Screencast_20240905_013752.webm](https://github.com/user-attachments/assets/99ab73ec-778b-4150-9e96-143c9d92dbfa)

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected (Fedora 40 KDE X11), with and without single window mode.

https://github.com/user-attachments/assets/4d3985b5-3c70-4df3-a825-9e63ee2bd73e

https://github.com/user-attachments/assets/8f828160-80e1-4a04-b6ac-ad0c82bdbdd8

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -7847,6 +7847,7 @@ void Node3DEditor::_sun_environ_settings_pressed() {
 	sun_environ_popup->set_position(pos - Vector2(sun_environ_popup->get_contents_minimum_size().width / 2, 0));
 	sun_environ_popup->reset_size();
 	sun_environ_popup->popup();
+	sun_environ_popup->grab_focus();
```
Comment (Calinou) [inline editor/plugins/node_3d_editor_plugin.cpp:7850]: Add a comment to explain why this is needed, as it's not obvious at a glance:

```suggestion
	// Grabbing the focus is required for Shift modifier checking to be functional
	// (when the Add sun/environment buttons are pressed).
	sun_environ_popup->grab_focus();
```

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.
