### PR TITLE
Fix lookup symbol for `super()`

### LINKED ISSUE #103215: super() lacks lookup symbol in GDScript editor
### Tested versions

4.x

### System information

-

### Issue description

There is no reaction from the editor when a user presses `Control+Click` on `super` keyword:

Image

I think this is incorrect and should be fixed.

### Steps to reproduce

^^

### Minimal reproduction project (MRP)

No need - trivial to reproduce

### PR DESCRIPTION
**Pull request by Chaosus**
- Fix https://github.com/godotengine/godot/issues/103215

fix

### CODE REVIEW

File: modules/gdscript/gdscript_editor.cpp [hunk 1]
```diff
@@ -4325,6 +4325,12 @@ ::Error GDScriptLanguage::lookup_code(const String &p_code, const String &p_symb
 			GDScriptParser::DataType base_type;
 			if (context.current_class) {
 				if (context.type != GDScriptParser::COMPLETION_SUPER_METHOD) {
+					if (context.current_function && p_symbol == "super") {
```
Comment (HolonProduction) [inline modules/gdscript/gdscript_editor.cpp]: IMO we should avoid using `p_symbol` in new code. It comes from the editor which has a very limited understanding of what is a symbol to GDScript and with the introduction of custom word separators `p_symbol` is completely unreliable since it depends on user settings.

Comment (Chaosus) [reply modules/gdscript/gdscript_editor.cpp]: Take a look again - I've changed it to use a context enum instead

Comment (HolonProduction) [reply modules/gdscript/gdscript_editor.cpp]: Do we need a new entry though :thinking: Isn't that basically the same as `COMPLETION_IDENTIFIER`?

Comment (Chaosus) [reply modules/gdscript/gdscript_editor.cpp]: Yes, because otherwise we cannot separate a call logic (without using p_symbol == "super"):

`if (_lookup_symbol_from_base(base_type, p_symbol, r_result) == OK)`

->

`if (_lookup_symbol_from_base(context.current_class->base_type, context.current_function->info.name, r_result) == OK)`

Comment (HolonProduction) [reply modules/gdscript/gdscript_editor.cpp]: Alright, feel free to disregard my original comment about using `p_symbol`, I was assuming that it should be trivial to get the same info from the completion context, but this seems to be quite complicated for super. Let's use `p_symbol` for now, we will have to fix it at some point anyway.

Comment (Chaosus) [reply modules/gdscript/gdscript_editor.cpp]: But the current approach is more flexible because it prevents completion of `super` in such context:

изображение

using `if (!check(GDScriptTokenizer::Token::PERIOD)) {`

File: modules/gdscript/gdscript_parser.h [hunk 2]
```diff
@@ -1300,6 +1300,7 @@ class GDScriptParser {
 		COMPLETION_PROPERTY_METHOD, // Property setter or getter (list available methods).
 		COMPLETION_RESOURCE_PATH, // For load/preload.
 		COMPLETION_SUBSCRIPT, // Inside id[|].
+		COMPLETION_SUPER, // super()
```
Comment (HolonProduction) [inline modules/gdscript/gdscript_parser.h]:
```suggestion
		COMPLETION_SUPER, // super(), used for lookup.
```
It's more like an editing context but since everything still uses the term completion, I think we should make the purpose clear.

**Review by HolonProduction — COMMENTED** [review]
Alright you have convinced me. Let's add a new context type for `super`. The fact that we need different lookup depending on whether it is a call makes this pretty much impossible to solve without parser changes.

**Comment by HolonProduction** [comment]
Should have some test. We don't have a specific test suite for lookup AFAIK, but the LSP test suite uses lookup under the hood. So we should add a supper call in one of those test cases.

**Comment by Chaosus** [comment]
> Should have some test. We don't have a specific test suite for lookup AFAIK, but the LSP test suite uses lookup under the hood. So we should add a supper call in one of those test cases.

Done.. I think. Check it up.

**Review by HolonProduction — APPROVED** [review]
LGTM 👍

**Review by Calinou — APPROVED** [review]
Code and tests look good to me.

**Comment by Chaosus** [comment]
I think it's fine to be merged to 4.5 beta milestone - it's a safe change.

**Comment by Repiteo** [comment]
Thanks!
