### PR TITLE
GDScript: Fix non-global class export

### LINKED ISSUE #93168: GDScript "Parse Error: Script export type must be a global class." regression in HungryProton Scatter plugin
### Tested versions

- Reproducible in 4.3.beta (71699e08c9df78b7203fa4ef9cede28e995d6ace)
- Also reproducible after merging #92326 locally, which I hoped might fix it as it sounds related
- Not reproducible in 4.3.beta1, so it's a recent regression, needs bisecting

### System information

Fedora Linux 40 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7600M XT (RADV NAVI33) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)

### Issue description

When opening a project using the https://github.com/HungryProton/scatter addon (installed from the asset lib), the following errors are printed:
```
SCRIPT ERROR: Parse Error: Script export type must be a global class.
          at: GDScript::reload (res://addons/proton_scatter/src/stack/modifier_stack.gd:15)
SCRIPT ERROR: Compile Error: 
          at: GDScript::reload (res://addons/proton_scatter/src/scatter.gd:-1)
SCRIPT ERROR: Parse Error: Script export type must be a global class.
          at: GDScript::reload (res://addons/proton_scatter/src/stack/modifier_stack.gd:15)
SCRIPT ERROR: Compile Error: 
          at: GDScript::reload (res://addons/proton_scatter/src/common/scatter_util.gd:-1)
SCRIPT ERROR: Compile Error: 
          at: GDScript::reload (res://addons/proton_scatter/src/scatter_shape.gd:-1)
SCRIPT ERROR: Compile Error: 
          at: GDScript::reload (res://addons/proton_scatter/src/shapes/gizmos_plugin/components/path_panel.gd:-1)
ERROR: Failed to load script "res://addons/proton_scatter/src/shapes/gizmos_plugin/components/path_panel.gd" with error "Compilation failed".
   at: load (./modules/gdscript/gdscript.cpp:2943)
SCRIPT ERROR: Invalid call. Nonexistent function 'selection_changed' in base 'MarginContainer (path_panel.gd)'.
          at: _on_selection_changed (res://addons/proton_scatter/plugin.gd:137)
```

This is a recent regression which doesn't appear in 4.3-beta1.

### Steps to reproduce

- Create new project
- Install and enabled HungryProton scatter addon

### Minimal reproduction project (MRP)

[testscatter.zip](https://github.com/user-attachments/files/15840567/testscatter.zip)

### PR DESCRIPTION
**Pull request by dalexeev**
* Fixes #93168.

Technically, the current behavior is not a regression, we just added missing validation for an already existing and documented limitation. But since this breaks plugins (which often try to avoid `class_name`), I tried to fix it as [suggested](https://github.com/godotengine/godot/issues/93168#issuecomment-2168330876): when exporting a non-global class property, GDScript looks for the nearest global/native class, rather than throwing an analyzer error.

### CODE REVIEW

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -4160,6 +4160,64 @@ static String _get_annotation_error_string(const StringName &p_annotation_name,
 	return vformat(R"("%s" annotation requires a variable of type %s, but type "%s" was given instead.)", p_annotation_name, string, p_provided_type.to_string());
 }
 
+static StringName _find_narrowest_native_or_global_class(const GDScriptParser::DataType &p_type) {
```
Comment (akien-mga) [inline modules/gdscript/gdscript_parser.cpp:4163]: Should it be "nearest"? Or is "narrowest" a term that typically has this meaning in class inheritance?

Comment (dalexeev) [reply modules/gdscript/gdscript_parser.cpp:4163]: We are moving up the inheritance hierarchy. If we find a global script class, we stop and use it. If not, then we reach the first native class and use it. "Narrowest" means we are looking for the most specific type (having a global name) as possible.

**Review by akien-mga — APPROVED** [review]
I confirm this fixes the regression with the Scatter addon in my full project.

Can't assess the code in depth but it seems reasonable to me.

**Comment by akien-mga** [comment]
Thanks!
