### PR TITLE
[Converter]: Improve performance and add option to set maximum line length to prevent freezes

### LINKED ISSUE #63672: --convert-3to4 hangs. Also fails on files >500kb
### Godot version

5c6744ae54189869580d713a6c31caa90492838a

### System information

Win 10/64 NVIDIA GeForce GTX 1060/PCIe/SSE2

### Issue description

6GB repo, 5100 files (assets, code, scenes). Now that #63377 is fixed, I ran the conversion again on my project. It identified 2011 files to process.

First I started with --validate-conversion-3to4, then went on to --convert-3to4. Both had the same behavior.

## 1 - 500kb Limit

There should be no such limit. If the editor can read such files, the conversion tool should be able to. Other conversion scripts can process them fine. I have plenty of large, text based assets and scenes. Binaries are no good for frequently changing files stored in git.

```
Checking for conversion - 1001/2011 file - "assets/models/rocks/mountain_pack/meshes/Mountain_rock_big_02_1.tscn" with size - 4153 KB
    Checking file took 0 ms.
        ERROR: File has exceeded the maximum size allowed - 500 KB
```

Also the check isn't even consistent. It's ok with this file >500kb, but not others:
```
Trying to convert       568/2011 file - "assets/models/village/fireplaces/FireplaceTop.tscn" with size - 1227 KB
    File was changed, conversion took 11848 ms.
```

## 2 - Hanging
It was chugging away fine validating everything, skipping anything above 500kb. Then it hit some file that it should have skipped due to the above limit and is hanging at 100% CPU on one thread. 220mb used.

```
Checking for conversion - 1000/2011 file - "assets/models/rocks/mountain_pack/meshes/Mountain_rock_big_01_5.tscn" with size - 1440 KB
    Checking file took 4557 ms.
                Line (75) CollisionShape -> CollisionShape3D  -  LINE """ [node name="CollisionShape" type="CollisionShape" parent="."] """
                Line (54) ConcavePolygonShape -> ConcavePolygonShape3D  -  LINE """ [sub_resource type="ConcavePolygonShape" id=4] """
                Line (61) ImmediateGeometry -> ImmediateMesh  -  LINE """ [node name="RootNode" type="ImmediateGeometry" parent="."] """
                Line (64) MeshInstance -> MeshInstance3D  -  LINE """ [node name="mountain_rock_big_01_5_LOD0" type="MeshInstance" parent="RootNode"] """
                Line (67) MeshInstance -> MeshInstance3D  -  LINE """ [node name="mountain_rock_big_01_5_LOD1" type="MeshInstance" parent="RootNode"] """
                Line (71) MeshInstance -> MeshInstance3D  -  LINE """ [node name="mountain_rock_big_01_5_LOD2" type="MeshInstance" parent="RootNode"] """
                Line (57) StaticBody -> StaticBody3D  -  LINE """ [node name="Mountain_rock_big_01_5" type="StaticBody"] """
                Line (10) PoolByteArray -> PackedByteArray  -  LINE """ "array_data": PoolByteArray( 196, 23, 214, 190, 58, 231, 20, 190, 84, 38, 94, 190, 146, 199, 25, 0, 213, 107, 51, 127, 255, 255, 255, 255, 4, 44, 69, 53, 94, 46, 154, 46, 43, 116, 195, 190, 215, 155, 90, 190, 252, 89, 89, 190, 146, 199, 25, 0, 213, 107, 51, 127, 255, 255, 255, 255, 48, 41, 118, 53, 57, 44, 192, 47, 143, 146, 216, 190, 35, 153, 32, 190, 57, 13, 135, 190, 146, 199, 25, 0, 213, 10... """
                Line (11) PoolByteArray -> PackedByteArray  -  LINE """ "array_index_data": PoolByteArray( 0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0, 8, 0, 9, 0, 10, 0, 11, 0, 12, 0, 13, 0, 14, 0, 15, 0, 16, 0, 17, 0, 18, 0, 19, 0, 20, 0, 21, 0, 22, 0, 23, 0, 24, 0, 25, 0, 26, 0, 27, 0, 28, 0, 29, 0, 30, 0, 31, 0, 32, 0, 33, 0, 34, 0, 35, 0, 36, 0, 37, 0, 38, 0, 39, 0, 40, 0, 41, 0, 42, 0, 43, 0, 44, 0, 45, 0, 46, 0, 47, 0, 48, 0, 49, 0, 50, 0, 51, 0, 52, 0, 5... """
                Line (26) PoolByteArray -> PackedByteArray  -  LINE """ "array_data": PoolByteArray( 47, 205, 140, 190, 125, 132, 86, 190, 60, 3, 181, 190, 31, 2, 134, 0, 118, 223, 29, 127, 255, 255, 255, 255, 205, 54, 65, 53, 103, 57, 100, 53, 151, 152, 83, 190, 71, 145, 11, 190, 194, 29, 171, 190, 31, 2, 134, 0, 118, 223, 29, 127, 255, 255, 255, 255, 10, 55, 182, 53, 191, 57, 9, 53, 214, 216, 156, 190, 211, 21, 32, 190, 55, 143, 184, 190, 31, 2, 134, 0, 118, 223,... """
                Line (27) PoolByteArray -> PackedByteArray  -  LINE """ "array_index_data": PoolByteArray( 0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0, 8, 0, 9, 0, 10, 0, 11, 0, 12, 0, 13, 0, 14, 0, 15, 0, 16, 0, 17, 0, 18, 0, 19, 0, 20, 0, 21, 0, 22, 0, 23, 0, 24, 0, 25, 0, 26, 0, 27, 0, 28, 0, 29, 0, 30, 0, 31, 0, 32, 0, 33, 0, 34, 0, 35, 0, 36, 0, 37, 0, 38, 0, 39, 0, 40, 0, 41, 0, 42, 0, 43, 0, 44, 0, 45, 0, 46, 0, 47, 0, 48, 0, 49, 0, 50, 0, 51, 0, 52, 0, 5... """
                Line (42) PoolByteArray -> PackedByteArray  -  LINE """ "array_data": PoolByteArray( 175, 165, 209, 58, 138, 35, 212, 188, 6, 9, 143, 190, 23, 2, 132, 0, 120, 222, 21, 127, 255, 255, 255, 255, 236, 55, 160, 54, 112, 58, 103, 51, 58, 107, 146, 62, 146, 64, 25, 190, 91, 244, 105, 190, 23, 2, 132, 0, 120, 222, 21, 127, 255, 255, 255, 255, 200, 56, 104, 54, 69, 58, 229, 44, 160, 110, 131, 62, 33, 237, 249, 60, 80, 97, 107, 190, 23, 2, 132, 0, 120, 222, ... """
                Line (43) PoolByteArray -> PackedByteArray  -  LINE """ "array_index_data": PoolByteArray( 0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0, 8, 0, 9, 0, 10, 0, 11, 0, 12, 0, 13, 0, 14, 0, 15, 0, 16, 0, 17, 0, 18, 0, 19, 0, 20, 0, 21, 0, 22, 0, 23, 0, 24, 0, 25, 0, 26, 0, 27, 0, 28, 0, 29, 0, 30, 0, 31, 0, 32, 0, 33, 0, 34, 0, 35, 0, 36, 0, 37, 0, 38, 0, 39, 0, 40, 0, 41, 0, 42, 0, 43, 0, 44, 0, 45, 0, 46, 0, 47, 0, 48, 0, 49, 0, 50, 0, 51, 0, 52, 0, 5... """
                Line (55) PoolVector3Array -> PackedVector3Array  -  LINE """ data = PoolVector3Array( 0.0016, -0.0259, -0.2794, 0.286, -0.1497, -0.2285, 0.2567, 0.0305, -0.2299, 0.1979, -0.3036, 0.366, -0.3022, -0.2952, -0.252, -0.3018, -0.3007, 0.0349, -0.4746, -0.0009, 0.0372, -0.4267, -0.0882, 0.1183, -0.4991, 0.0595, 0.017, 0.1411, 0.1554, -0.2544, 0.1983, 0.0884, -0.2179, 0.2583, 0.1204, -0.0577, -0.4107, 0.1271, 0.0184, -0.4746, -0.0009, 0.0372, -0.4991, 0.0595, 0... """
Checking for conversion - 1001/2011 file - "assets/models/rocks/mountain_pack/meshes/Mountain_rock_big_02_1.tscn" with size - 4153 KB
    Checking file took 0 ms.
        ERROR: File has exceeded the maximum size allowed - 500 KB
Checking for conversion - 1002/2011 file - "assets/models/rocks/mountain_pack/meshes/Mountain_rock_big_02_2.tscn" with size - 3878 KB
```

After about 30+ minutes I finally hit ctrl+c and saw this:

```
ERROR: BUG: Unreferenced static string to 0: ShaderCompilation
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: interface_added
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: bus_layout_changed
   at: unref (core/string/string_name.cpp:131)
```

Structurally, there's no difference between Mountain_rock_big_02_1.tscn and Mountain_rock_big_02_2.tscn, and the next one _3 in case it started that before printing. I diffed them and they only differ by names or array data. They are static bodies as the root, an immediate geometry w/ a LOD script, three LOD mesh instances as arraymeshes, and a collision shape w/ a ConcavePolygonShape (trimesh generated off of LOD1 or 2. About the same number of vertices at each LOD level. As you see above the second file is smaller. _3 is between 1 and 2 at 4mb.

Here's the scene.
[Mountain_rock_big_02_2.zip](https://github.com/godotengine/godot/files/9225913/Mountain_rock_big_02_2.zip)

Here is the full conversion log so far.
[convert_log.zip](https://github.com/godotengine/godot/files/9225909/convert_log.zip)

## Testing what was converted

Finally, I opened up the half converted project to see if it is any better than my current conversion process. I'm especially interested in anything that might fix #63550.

After a couple hours with my own conversion process I got my error count on open under 100. After this half finished conversion, my error count is 2862. It's not a fair comparison, just a data point.

I looked at some files that were reported as converted and here's what I found:

* Shaders - not converted properly, opened a separate issue here #63673

* Mesh conversion - No different than the corrupted footbridge and support beam meshes shown in #63550

@qarmin

### PR DESCRIPTION
**Pull request by qarmin**
Fixes https://github.com/godotengine/godot/issues/63672

This PR added option to choose maximum checked file size and maximum length of checked line.
By default only files smaller than 4MB are checked and lines shorter than 10000 characters, which seems for me quite reasonable(at the end there is additional info how much exactly lines were ignored).

Additionally due caching regex, searching sometimes can be faster by few percent(I was expecting bigger change, but looks that most of the time is spend on searching files with regex, not creating new regex thousands of times).

When testing projects with a lot of files and short lines, I got a little lower performance than before(this was probably caused by running regexes on lines instead full files like before - this change was required to be able to cache regex), but when checking tps-demo which contains files with longer lines, time to check for renames dropped from 120s to 13s

Edit:
I found with help of hotspot that running `regex.sub` on small lines is very time consuming, so using `string.contains` before to decrease amount of regex to run can speedup this part even few times

Some benchmarks:

| Project | Mode | Master branch | PR | 
| --- | --- | --- | --- |
| tps-demo | converting | 180s | 11s |
| tps-demo | validating | 116s | 11s | 
| jetpaca | converting | 98s | 26s | 
| jetpaca | validating | 290s | 27s | 
| liblast | converting | 11s | 7s | 
| liblast | validating | 32s | 6s | 

Edit2:
Also added(re-enable actually) check to validate if new function name already exists.

### CODE REVIEW

**Comment by tinmanjuggernaut** [comment]
I tried this PR 1cabf13b1fd8bc834bc18e5e69a3b48abeef572a on a fresh copy of my gd3 project. It reports 2011 resources to do.

It is indeed much faster and no longer hangs on the file I mentioned. Great work.

First I tried with 1GB file size and 1MB on one line. It completed in a few minutes.
```
../../godot/bin/godot.windows.opt.tools.64.exe --convert-3to4 999999 999999
...
Conversion ended - all files(2011), converted files(2011), not converted files(0).
Conversion of all files took 462119 ms.
```

However, I had many instances of skipped lines. Yet none of them are displayed at the end, neither in summary nor detail. Those are now broken files. It should report the skipped lines files at the end so a user can take steps to fix them.

It even processed my 353MB player scene file with 200 animations, a complex rig, and complete AAA quality human model. 88 seconds to process it is acceptable given what it is.
```
Trying to convert       1714/2011 file - "assets/models/characters/dorian/Dorian.tscn" with size - 353159 KB
    Checking file took 88459 ms.
```

If it can process the above file, then it should be able to process any other file I have. The default 10,000 character limit is wayyyyy too low. 999,999 was fine.

Yet it skipped lines > 1MB as I specified. 
```
Trying to convert       329/2011 file - "src/inventory/items/shields/OrnateBuckler.tscn" with size - 1429 KB
    Checking file took 219 ms.
    File was changed, conversion took 219 ms.
    Ignored 1 lines, because their length exceeds maximum allowed characters - 999999
```

So I expanded it to 100MB which it should be able to allocate and process without sweating. However it hung on a tiny 4mb file. The whole thing could fit in an allocation smaller than many texture files. It's the same structure as described in #63672 with a LOD manger, a few ArrayMeshes.

```
../../godot/bin/godot.windows.opt.tools.64.exe --convert-3to4 999999 99999999

Trying to convert       361/2010 file - "scenes/BlackMountain.tscn" with size - 4354 KB

# after Ctrl+C
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketLargeE
   at: (./core/templates/paged_allocator.h:140)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools12BucketMediumE
   at: (./core/templates/paged_allocator.h:140)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketSmallE
   at: (./core/templates/paged_allocator.h:140)
ERROR: BUG: Unreferenced static string to 0: interface_added
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: bus_layout_changed
   at: unref (core/string/string_name.cpp:131)

```

I left this for about 10-15 minutes. Allocated memory is only 185mb. Processor is 100% on one core. 350mb Dorian only took 88 seconds and the process allocated up to 3GB.

**Comment by qarmin** [comment]
Latest freeze with 4MB file should be fixed now.

After recent changes, String `contains` method takes ~75% converting time so I don't think that there is room for improvements
The only two possible things which could be done to speedup a little a code:
- caching rest of regex, this will increase slightly startup time
- improving algorithm of finding text in strings(https://en.wikipedia.org/wiki/String-searching_algorithm#Single-pattern_algorithms)

Screenshot from 2022-08-17 20-55-00

**Comment by tinmanjuggernaut** [comment]
Ok, I let it work again on my project w/ 1GB files and 100MB lines:

```
../../godot/bin/godot.windows.opt.tools.64.exe --convert-3to4 999999 99999999

Trying to convert       570/2010 file - "assets/models/village/buildings/HouseC.tscn" with size - 60322 KB
    Checking file took 30839 ms.
    File was changed, conversion took 30839 ms.

Trying to convert       1614/2010 file - "assets/models/dungeon/architecture/TrippleArch.tscn" with size - 15323 KB
    Checking file took 8674 ms.
    File was changed, conversion took 8674 ms.

Trying to convert       1679/2010 file - "assets/models/creatures/dragon/dragon_body.tres" with size - 13157 KB
    Checking file took 1408 ms.
    File was changed, conversion took 1408 ms.

Trying to convert       1713/2010 file - "assets/models/characters/dorian/Dorian.tscn" with size - 353159 KB
    Checking file took 184101 ms.
    File was changed, conversion took 184101 ms.

Conversion ended - all files(2010), converted files(2010), not converted files(0).
Conversion of all files took 558289 ms.

```

Nothing was skipped, nothing hung. It chew through even monster files like the highlights included above. Dorian took twice as long, but still acceptable. Great work. Thank you!

**Comment by qarmin** [comment]
Recently I only added changes which should speedup searching, especially with big files, so 2x slower checking of 300mb file is quite suspicious.

I think that converting times cannot be really predictable due random OS CPU usage(converter should most of the time use 100% of one core), because one time entire godot demo repository converted most of the time in 32s but sometimes took even in 47s.

The only possible way now to speedup searching is to move computations to multiple cores(which may I implement in future in other PR)

**Comment by tinmanjuggernaut** [comment]
Converting my 4gb project in 10 minutes is fine. The skipping and hanging issues were a bigger deal and those seem resolved.

File: editor/project_converter_3_to_4.h [hunk 1]
```diff
@@ -35,37 +35,42 @@
 #include "core/io/file_access.h"
 #include "core/object/ref_counted.h"
 #include "core/string/ustring.h"
+#include "core/templates/local_vector.h"
+#include "modules/regex/regex.h"
```
Comment (akien-mga) [inline editor/project_converter_3_to_4.h:39]: It's best if you forward declare RegEx instead. It can be compiled out and the `.cpp` already has the logic to handle this properly. If you need to include it here too, you should also include `modules/modules_enabled.gen.h` and properly handle conditional compilation.

File: main/main.cpp [hunk 2]
```diff
@@ -391,8 +393,8 @@ void Main::print_help(const char *p_binary) {
...
 	OS::get_singleton()->print("  --export-debug <preset> <path>               Same as --export, but using the debug template.\n");
 	OS::get_singleton()->print("  --export-pack <preset> <path>                Same as --export, but only export the game pack for the given preset. The <path> extension determines whether it will be in PCK or ZIP format.\n");
-	OS::get_singleton()->print("  --convert-3to4                               Converts project from Godot 3.x to Godot 4.x.\n");
-	OS::get_singleton()->print("  --validate-conversion-3to4                   Shows what elements will be renamed when converting project from Godot 3.x to Godot 4.x.\n");
+	OS::get_singleton()->print("  --convert-3to4 <max_file_kb> <max_line_size>              Converts project from Godot 3.x to Godot 4.x.\n");
+	OS::get_singleton()->print("  --validate-conversion-3to4 <max_file_kb> <max_line_size>  Shows what elements will be renamed when converting project from Godot 3.x to Godot 4.x.\n");
```
Comment (akien-mga) [inline main/main.cpp:397]:
```suggestion
	OS::get_singleton()->print("  --convert-3to4 [<max_file_kb> [<max_line_size>]]              Converts project from Godot 3.x to Godot 4.x.\n");
	OS::get_singleton()->print("  --validate-conversion-3to4 [<max_file_kb> [<max_line_size>]]  Shows what elements will be renamed when converting project from Godot 3.x to Godot 4.x.\n");
```
The `[ ]` syntax means that it's optional.

File: main/main.cpp [hunk 3]
```diff
@@ -1071,10 +1073,24 @@ Error Main::setup(const char *execpath, int argc, char *argv[], bool p_second_ph
 			// Actually handling is done in start().
 			cmdline_tool = true;
 			main_args.push_back(I->get());
+
+			if (I->next() && !I->next()->get().begins_with("-")) {
+				converter_max_kb_file = I->next()->get().to_int();
+				if (I->next()->next() && !I->next()->get().begins_with("-")) {
```
Comment (akien-mga) [inline main/main.cpp:1079]:
```suggestion
				if (I->next()->next() && !I->next()->next()->get().begins_with("-")) {
```

File: main/main.cpp [hunk 4]
```diff
@@ -1071,10 +1073,24 @@ Error Main::setup(const char *execpath, int argc, char *argv[], bool p_second_ph
...
+				}
+			}
 		} else if (I->get() == "--validate-conversion-3to4") {
 			// Actually handling is done in start().
 			cmdline_tool = true;
 			main_args.push_back(I->get());
+
+			if (I->next() && !I->next()->get().begins_with("-")) {
+				converter_max_kb_file = I->next()->get().to_int();
+				if (I->next()->next() && !I->next()->get().begins_with("-")) {
```
Comment (akien-mga) [inline main/main.cpp:1090]:
```suggestion
				if (I->next()->next() && !I->next()->next()->get().begins_with("-")) {
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
