### PR TITLE
Fix: saving gdscript with cyclic inheritance crash the editor

### LINKED ISSUE #9609: Circular inheritance crashes editor
**Operating system or device - Godot version:** Ubuntu 16.04 running Godot 2.1.3

**Issue description:**
When two scripts inherit each other on a `extends` statement and you try to save the second one, the editor crashes. Running Godot on a terminal doesn't output any errors.

**Steps to reproduce:**
1. Create two GDScripts: test1.gd and test2.gd
2. Open test1.gd and make it inherit "res://test2.gd" (the rest of the file doesn't matter at all)
3. Save test1.gd
4. Open test2.gd and make it inherit "res://test1.gd".
5. When you try to save test2.gd, the editor closes. This happens when using both the shortcut (Ctrl+S) and the File menu.

**Link to minimal example project:**
Not needed, easy to reproduce.

### PR DESCRIPTION
**Pull request by ThakeeNathees**
Fix: #9609

cyclic reference causes some non terminating recursive calls which leads to stack overflows -> fixed  

cyclic-inheritance

### CODE REVIEW

**Review by vnen — APPROVED** [review]

File: modules/gdscript/gdscript.cpp [hunk 1]
```diff
@@ -379,10 +379,14 @@ void GDScript::_update_exports_values(Map<StringName, Variant> &values, List<Pro
 }
 #endif
 
-bool GDScript::_update_exports() {
+bool GDScript::_update_exports(bool *p_ret_err, bool p_recursive_call) {
 
 #ifdef TOOLS_ENABLED
 
+	static Vector<GDScript *> base_caches;
+	if (!p_recursive_call) base_caches.clear();
```
Comment (akien-mga) [inline modules/gdscript/gdscript.cpp:387]: Please avoid putting both the condition and the statement on the same line. (Same below.)

File: modules/gdscript/gdscript.h [hunk 2]
```diff
@@ -133,7 +133,7 @@ class GDScript : public Script {
 
 #endif
 
-	bool _update_exports();
+	bool _update_exports(bool *p_ret_err = (bool *)0, bool p_recursive_call = false);
```
Comment (akien-mga) [inline modules/gdscript/gdscript.h:136]: Does it make a difference to use `(bool *)0` here instead of simply `nullptr`?

Comment (ThakeeNathees) [reply modules/gdscript/gdscript.h]: No now I've changed it to `nullptr`, it was opened back then where we don't use `nullptr`

File: modules/gdscript/gdscript.cpp (hunk 1 above)
Comment (ThakeeNathees) [reply modules/gdscript/gdscript.cpp:384]: done, now I also have to avoid `condition && func();` 😄

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.
