### PR TITLE
Fixes the bad calculation of margin & anchors when child of Node2D

### LINKED ISSUE #18169: Controls use bad calculation for margins + anchors when child of Node2D
**Godot version:**
Master branch

**Issue description:**
Following the discussion in #18166, several calculus in control.cpp use the _edit_get_rect() function for core mechanisms. This ends up in the code using the meaningless Node2D's "selection rectangle" as a base for the calculation of archors and margins, when a Control is used as a child of a Node2D.

So if you have this hierarchy:
- Node2D
   - Control with anchors 0,0,1,1 and Margins 0,0,0,0

The control will appear 64x64 while it should be 0x0 (the Node2D size makes no sense)

### PR DESCRIPTION
**Pull request by groud**
Fixes #18169

And also cleans the code a little bit.

### CODE REVIEW

File: scene/gui/control.cpp [hunk 1]
```diff
@@ -1254,15 +1254,18 @@ bool Control::has_constant(const StringName &p_name, const StringName &p_type) c
...
 
-	ERR_FAIL_COND_V(!is_inside_tree(), Size2());
+	if (!is_inside_tree())
+		return Size2();
 
 	Size2 parent_size;
-
 	if (data.parent_canvas_item) {
+		if (data.parent_canvas_item->_edit_use_rect()) {
+			parent_size = data.parent_canvas_item->_edit_get_rect().size;
```
Comment (reduz) [inline scene/gui/control.cpp]: I don't think _edit functions should be used in production.

**Review by reduz — CHANGES_REQUESTED** [review]

**Comment by groud** [comment]
I updated the PR, but I had to change a lot of things to fix this bug.
Also, it removes the rect for sprites, animatedsprites, etc... when theydo not have a valid texture.
