### PR TITLE
GDScript: Add error when exporting node in non `Node`-derived classes

### LINKED ISSUE #82809: When using a Node exported through a Resource, you can not listen to its signals.
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Compatibility) - NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.3168) - 12th Gen Intel(R) Core(TM) i9-12900K (24 Threads)

### Issue description

With the code below, if you select a node and a signal name, it will await the execution of the signal correctly.

```GDScript
@export var signal_node: Node
@export var signal_name: String = ""

func _ready():
   await signal_node[signal_name]
   print("Signal happened!")
```

If I now move these exports to a Resource class, the code will no longer work:

```GDScript
class_name SignalInput
extends Resource

@export var node: Node
@export var name: String = ""
```

```GDScript
@export var signal_input: SignalInput

func _ready():
   await signal_input.node[signal_input.name]
   print("This will never show up")
```

### Steps to reproduce

```GDScript
# SignalInput.gd
class_name SignalInput
extends Resource

@export var node: Node
@export var name: String = ""

```

```GDScript
# main.gd
extends Control

@export var signal_input: SignalInput ## (Node: Set to a timer node, Name: "timeout")

@onready var timer = $Timer

func _ready():
	await signal_input.node[signal_input.name] ## await timer.timeout
	print("[Method 1] Resource signal, will not appear") ## this should never run
```

### Minimal reproduction project

[source.zip](https://github.com/godotengine/godot/files/12807026/source.zip)

### PR DESCRIPTION
**Pull request by dalexeev**
* Closes #82809.
  * Display an error when trying to export a node in a non `Node`-derived class.
* Extends the `@export` annotation documentation.
* Rename `p_node` to `p_target` so `.cpp` matches `.h`.

### CODE REVIEW

**Review by adamscott — APPROVED** [review]
Looks nice!

**Comment by akien-mga** [comment]
Thanks!

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -5544,7 +5544,7 @@ Error GDScriptAnalyzer::analyze() {
 	// Apply annotations.
 	for (GDScriptParser::AnnotationNode *&E : parser->head->annotations) {
 		resolve_annotation(E);
-		E->apply(parser, parser->head);
+		E->apply(parser, parser->head, nullptr);
```
Comment (aaronfranke) [inline modules/gdscript/gdscript_analyzer.cpp:5547]: `parser->head` is a `ClassNode *`, so this line should be:

```cpp
E->apply(parser, parser->head, nullptr);
```

Comment (dalexeev) [reply modules/gdscript/gdscript_analyzer.cpp:5547]: No, `p_class` is the class that `p_target` is in. The root class is **not** in any other class. This is a subtle detail, but for example if an annotation is applied to an inner class (we don't have such a case right now), then `p_target` will be the class, and `p_class` will be its outer class. Therefore, if you do not need the _context_ class, then it is important to use `p_target` rather than `p_class`, even this requires `static_cast`.

Comment (aaronfranke) [reply modules/gdscript/gdscript_analyzer.cpp:5547]: Thanks, I missed that detail before. I've updated my PR and add a comment in the abstract annotation apply method for why we are using p_target instead of p_class.

**Comment by YuriSizov** [comment]
Just a small note: if we are referring to some unspecified limitations, we should link to some place that explains what those are. Do we have an article that goes into such detail about Node exports?

**Comment by dalexeev** [comment]
> Just a small note: if we are referring to some unspecified limitations, we should link to some place that explains what those are. Do we have an article that goes into such detail about Node exports?

Fair point. I remember that there are issues with exporting nodes in `@tool` mode, but I'm not sure about other issues, which of them are limitations and which are bugs. So I left room for interpretation. I wanted to warn that exporting nodes is less stable than exporting node paths and may not work in non-standard scenarios.
