### PR TITLE
ShaderCompiler: Optimize compilation error printing

### LINKED ISSUE #103109: Editor hangs when printing complex shader errors to the output panel
### Tested versions

- Reproducible in 4.3.0-stable, v4.4.beta4.official [93d270693]

### System information

Godot v4.4.beta4 - Fedora Linux 41 (Workstation Edition) on Wayland - X11 display driver, Single-window, 1 monitor - OpenGL 3 (Compatibility) - AMD Radeon RX 560 Series (radeonsi, polaris11, LLVM 19.1.0, DRM 3.60, 6.12.15-200.fc41.x86_64) - Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 threads)

### Issue description

When the visibility of output messages (and, to a lesser degree, error messages) is enabled, it's easy to hang the editor for a long time by typing invalid code.

Shader includes, in particular, quickly bloat the output—especially when chained together (with `#ifndef` include guards). There's a lot of redundant and irrelevant content printed. An example chain might be a shader that uses a specialty include that use a utility function include that uses a math include. The attached project uses `shader > fog > colors > gradients > utilities > math` (although, in retrospect, `gradients > colors` would have been a more natural example relationship order). That chain is very similar to the chains I use in my current game project. And, pretty much everything uses my custom math include. So, editing that file prints _a lot_.

Ideal changes:

1. Don't print messages about shader errors to the output in the first place. Don't even waste CPU cycles generating the strings. In big projects, the editor hitching is frustrating. The output is worthless while working in the shader editor and a mess when viewed in the output panel.
2. If something _really_ needs printed, only print a minimal message that redirects the user to the file path so that they can see the error in the shader editor instead. And, even then, maybe put them in a separate output panel category.

### Steps to reproduce

This test was performed with `interface/editor/single_window_mode` enabled.

1. Open the attached project in Godot v4.4.beta4.official [93d270693].
2. Ensure that the output panel is set to print standard output and error messages.
3. Open `shaders/common/math.gdshaderinc` in the shader editor.
4. Type some invalid code (like "test") into `math.gdshaderinc`, to cause an error.
5. Observe that the editor becomes unresponsive for a long time. If not, duplicate `test_shader_1.gdshader` or `test_shader_2.gdshader` to make printing output take even longer.
6. Undo the error, restoring `math.gdshaderinc` to an error-free state.
7. In the output panel, disable the visibility of standard output and error messages.
8. Add an error to `math.gdshaderinc` again.
9. Observe that the editor becomes unresponsive for less time than when visibility of output messages was enabled.

### Minimal reproduction project (MRP)

[godot-4_4-dev4---shader-freeze-test.zip](https://github.com/user-attachments/files/18898901/godot-4_4-dev4---shader-freeze-test.zip)

### PR DESCRIPTION
**Pull request by beicause**
Background:
I included https://github.com/Auburn/FastNoiseLite/blob/master/GLSL/FastNoiseLite.glsl in gdshader. Whenever I modify the gdshader file, the editor freezes for ~10 secs  and prints out ~12,000 lines of output.

This also happends in issue #107403 where the core shader fails to compile and causes the editor to freeze and prints a large amount of log.

After testing I found that most of the time is spent on `RichTextLabel` operations during console printing:

屏幕截图_20250615_031128

After this PR the editor's freezing time is reduced from ~10 secs to nearly instantaneous. This will significantly improve the performance when editing large shader files that contain many gdshaderinc. And the main cause of compilation failure will still be printed as errors.

This changes to only print 5 lines around the error line. And changes `ShaderRD` to print in verbose mode.
Example log: 
```
--res://shader/fast_noise.gdshader--
    1 | shader_type spatial;
    2 | 
E   3-> #include "res://shader/include/thirdparty/FastNoiseLite.gdshaderinc"
    4 | 
    5 | 
--res://shader/include/thirdparty/FastNoiseLite.gdshaderinc--
  111 |  
  112 |  
E 113->  fnl_noise_typ noise_type;
  114 | 
  115 |  
  ERROR: res://shader/include/thirdparty/FastNoiseLite.gdshaderinc:113 - Expected data type.
  ERROR: Shader compilation failed.

```

- Fixes #103109
- Related #103894

### CODE REVIEW

File: servers/rendering/shader_compiler.cpp [hunk 1]
```diff
@@ -1529,20 +1540,17 @@ Error ShaderCompiler::compile(RS::ShaderMode p_mode, const String &p_code, Ident
...
 				if (i == err_line - 1) {
 					// Mark the error line to be visible without having to look at
 					// the trace at the end.
 					print_line(vformat("E%4d-> %s", i + 1, V[i]));
-				} else {
+				} else if ((i == err_line - 3) || (i == err_line - 2) || (i == err_line) || (i == err_line + 1)) {
+					// Print 4 lines around the error line.
 					print_line(vformat("%5d | %s", i + 1, V[i]));
+				} else {
+					print_verbose(vformat("%5d | %s", i + 1, V[i]));
```
Comment (beicause) [inline servers/rendering/shader_compiler.cpp]: I suspect whether it makes sense to print the full code in verbose mode. Printing errors and 5 lines of code should suffice.

**Comment by beicause** [comment]
I didn't notice #103894 when I created this PR, but I think this is a good alternative to #103894.

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected. Code looks good to me.

Example with an error in a shader include:

```
--res://d.gdshader--
    1 | shader_type spatial;
    2 | 
E   3-> #include "res://test.gdshaderinc"
    4 | 
    5 | 
--res://test.gdshaderinc--
    7 | 
    8 | 
E   9-> const int TEST = 225x;
   10 | 
   11 | 
  ERROR: res://test.gdshaderinc:9 - Invalid (hexadecimal) numeric constant
  ERROR: Shader compilation failed.
```

Note that the shortened errors don't apply to errors in [core shaders](https://docs.godotengine.org/en/latest/contributing/development/core_and_modules/internal_rendering_architecture.html#doc-internal-rendering-architecture-core-shaders), which are still printed in full in all renderers. We could probably change this in a future PR and make them only print 4 lines around the error unless `--verbose` is used.

**Comment by beicause** [comment]
Actually, I reverted the change that makes `ShaderRD` output in verbose mode, because the core shaders should never produce errors to users. If it does, it would be a bug in Godot.

**Review by clayjohn — APPROVED** [review]
Makes sense to me! The goal of printing out the shader is to help people identify shader errors for shaders not open in the shader editor. We just need to give them enough information to find where the error is coming from. The entire shader is definitely not needed

File: servers/rendering/shader_compiler.cpp [hunk 2]
```diff
@@ -1520,6 +1520,17 @@ Error ShaderCompiler::compile(RS::ShaderMode p_mode, const String &p_code, Ident
 
 		// Print the files.
 		for (const KeyValue<String, Vector<String>> &E : includes) {
+			int err_line = -1;
+			for (int i = 0; i < include_positions.size(); i++) {
+				if (include_positions[i].file == E.key) {
+					err_line = include_positions[i].line;
```
Comment (AThousandShips) [inline servers/rendering/shader_compiler.cpp]:
```suggestion
			for (const ShaderLanguage::FilePosition &include_position : include_positions) {
				if (include_position.file == E.key) {
					err_line = include_position.line;
```

**Review by AThousandShips — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
