### PR TITLE
Made Editor Log buttons save their state, per project.

### LINKED ISSUE #48445: EditorLog should remember pressed buttons
**Godot version:**

56316b2

**Steps to reproduce:**
None of these buttons have their state remembered between sessions:
image
We could save this as part of project's editor state. Not sure if there is a good place to store it globally.

### PR DESCRIPTION
**Pull request by EricEzaM**
Closes #48445

State is saved in `res://.godot/editor_layout.cfg`, which is the same as the editor docks layout, per project. This seems to be the most appropriate place to save it. A slight logic change was required in `EditorNode` so that the file is not overwritten every time it is saved, since now the file is read and written to from somewhere other than the one `EditorNode` method.

The state of all 4 filter buttons and the collapse state is saved:
image

A timer is used to delay the save, as is done in other places in the editor, so that rapid changes to the state do not spam saving the config file.

CC @KoBeWi

### CODE REVIEW

**Comment by KoBeWi** [comment]
- Collapse messages seems to be not stored properly.
- Saving the search bar visibility would be useful too.
- Seems like all messages are disabled by default. Should be the opposite, to avoid confusion.

**Comment by EricEzaM** [comment]
> * Collapse messages seems to be not stored properly.

I cannot reproduce. Toggling collapse saves the file as expected. If I open the file in VS Code, it automatically updates when it gets changed. I can see the value updating as I change the `collapse` option, as expected.

> * Saving the search bar visibility would be useful too.

Added.

> * Seems like all messages are disabled by default. Should be the opposite, to avoid confusion.

I cannot reproduce. Delete `res://.godot/editor_layout.cfg` -> restart editor -> all filters are enabled.

File: editor/editor_log.h [hunk 1]
```diff
@@ -124,6 +133,9 @@ class EditorLog : public HBoxContainer {
 	// Warnings or Errors are encounetered.
 	Button *tool_button;
 
+	bool is_loading_state = false; // Used to disable saving requests while loading (some signals from buttons will try trigger a save, which happens during loading).
+	Timer *save_state_timer;
```
Comment (KoBeWi) [inline editor/editor_log.h:137]: Timer should be initialized to `nullptr`, but seeing as there are other non-initialized pointers, it's not very important for now.

**Review by KoBeWi — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Calinou** [comment]
The filter buttons are disabled by default on newly created projects. Would it be possible to enable them by default instead, to get behavior similar to `3.x`? Right now, it's possible to miss important error/warning messages, and your `print()`s won't appear by default when you run the project.

**Comment by EricEzaM** [comment]
Oops, I thought I fixed that.
