### PR TITLE
Fix quick open dialog recursive problem

### LINKED ISSUE #114153: Empty warning popup on trying to assign cyclic resource reference in editor
### Tested versions

Reproducible in 4.5.1 and 4.6beta1

### System information

Godot v4.5.1.stable - macOS Sequoia (15.6.1) - Multi-window, 2 monitors - OpenGL 3 (Compatibility) - Apple M2 Pro - Apple M2 Pro (10 threads) - 16.00 GiB memory

### Issue description

When assigning resource references in the editor inspector by picking them from existing files there's apparently some check to see you're not assigning cyclic references since that's not currently supported (at least that's what I think is happening?).

However, the warning message that appears when you do this is completely blank.

### Steps to reproduce

- Have a custom resource class that has an export variable of the same Resource class. 
- Create a resource of this class and save 
- In the inspector try to assign the same resource to the export variable

https://github.com/user-attachments/assets/251f0005-6d89-4c9e-bc96-8dc1153cc8b0

### Minimal reproduction project (MRP)

[cyclic-resources.zip](https://github.com/user-attachments/files/24238833/cyclic-resources.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #114153

Making the recursive warning deferred fixed the empty popup.

For quick preview, I moved `find_recursive_resources()` method to EditorNode and the Quick Open dialog will use it when trying to preview. If recursion is detected, it will use null for preview and show error via toaster.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: editor/gui/editor_quick_open_dialog.cpp [hunk 1]
```diff
@@ -232,6 +233,16 @@ void EditorQuickOpenDialog::preview_property() {
 	Ref<Resource> loaded_resource = ResourceLoader::load(container->get_selected());
 	ERR_FAIL_COND_MSG(loaded_resource.is_null(), "Cannot load resource from path '" + container->get_selected() + "'.");
 
+	Resource *res = Object::cast_to<Resource>(property_object);
+	if (res) {
+		HashSet<Resource *> resources_found;
+		resources_found.insert(res);
+		if (EditorNode::find_recursive_resources(loaded_resource, resources_found)) {
+			EditorToaster::get_singleton()->popup_str(TTR("Recursion detected, quick preview failed."), EditorToaster::SEVERITY_ERROR);
```
Comment (Meorge) [inline editor/gui/editor_quick_open_dialog.cpp:241]:
```suggestion
			EditorToaster::get_singleton()->popup_str(TTR("Recursion detected, Instant Preview failed."), EditorToaster::SEVERITY_ERROR);
```
Perhaps a minor nitpick, but since the functionality is referred to as "Instant Preview" in other places in the editor, I think it makes sense to use the same name here.

**Comment by Repiteo** [comment]
Thanks!

**Review by Meorge — APPROVED** [review]
Looks like I may have been a few seconds too late, oops. Overall this looks/sounds good to me; I thought it might be wise to use the term "Instant Preview" in the toast error message for consistency's sake but it's not a huge issue either way 😅

File: editor/gui/editor_quick_open_dialog.cpp (hunk 1 above)
Comment (KoBeWi) [reply editor/gui/editor_quick_open_dialog.cpp:241]: Makes sense.
