### PR TITLE
[3.x] Add half frame to floor() for animated particles UV

### LINKED ISSUE #36435: Particles Animation repeat the first frame when using not square sheets
**Godot version:**
3.2 stable

**OS/device including version:**
Ubuntu 19.10

**Issue description:**
The Particles2D with Particles Animation repeat the first frame when it animates.
On a 3x2 sheet the Particles Animation shows in this order: 1, 2, 3, 1, 5, 6. But it must be: 1, 2, 3, 4, 5, 6
The sheet is correctly created from left to right and uppter to bottom.
I numerated the sheet and it repeat the number "1". So it is eventualy wrong.

**Steps to reproduce:**
1) Add a Particles2D node.
2) Load a texture with a sheet of animation (ie: Explosion)
3) Create a CanvasItemMaterial and set it to animate and fill the H and V frames properly.

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by metinc**
Depending on the hardware or drivers it can occur on some devices that animated sprites do not render in the correct order. This happens because of an inprecision when calling floor(). Adding a 0.5 before using floor fixes this bug.

Closes #36435

### CODE REVIEW

**Comment by Calinou** [comment]
Thanks for opening a pull request :slightly_smiling_face: 

Pull requests should be opened against the `master` branch instead of `3.x` first. This is because feature development occurs in the `master` branch. We can then cherry-pick specific PRs to the `3.x` branch if they don't break backwards compatibility.

(Keep this PR open as the fix is also relevant for `3.x`, and the `master` PR is most likely not easy to cherry-pick.)

**Comment by metinc** [comment]
Sorry for that! Here is the PR on master:  #53237

**Comment by clayjohn** [comment]
I am a little skeptical. Adding 0.5 before calling ``floor()`` is the same as calling ``round()`` Adding 0.5 doesn't just adjust for a minor imprecision, it completely changes the behaviour. 

My guess is that #36435 is actually an issue with how ``particle_frame`` is calculated.

**Comment by JFonS** [comment]
I think in this case it works out. The `0.5` is added before the division, not after. Assuming both `particle_frame` and `h_frames` are integers and greater than 0 the result after `floor()` should be the same but with more margin for precision errors.

**Comment by lawnjelly** [comment]
I also think it looks good. I'm wondering if it is also susceptible to a similar bug for the x? Should we make a similar adjustment for the x?

**Comment by metinc** [comment]
@clayjohn Thanks for your feedback. I understand your point but please note the brackets I added in my changes. As @JFonS pointed out the 0.5 is added before division to add a margin to the floor that is exactly a half frame. Let's assume we have a texture with 3x2 frames. Here is what happens:
floor_example
 @lawnjelly I think the code for x is good because there is only a mod() and not a floor(). An imprecision would only mean a tiny non-visible offset in the UV coordinates.

**Comment by lawnjelly** [comment]
Well for example, if you had e.g. 31.9999999 coming in, with a row of 16. Because of the mod operation, this will come out as 15.9999, instead of 0.0. I only say this because we not long ago had a similar bug in another area of Godot (I forgot the details).

File: scene/2d/canvas_item.cpp [hunk 1]
```diff
@@ -148,7 +148,7 @@ void CanvasItemMaterial::_update_shader() {
 		code += "\t\tparticle_frame = mod(particle_frame, particle_total_frames);\n";
 		code += "\t}";
 		code += "\tUV /= vec2(h_frames, v_frames);\n";
-		code += "\tUV += vec2(mod(particle_frame, h_frames) / h_frames, floor(particle_frame / h_frames) / v_frames);\n";
+		code += "\tUV += vec2(mod(particle_frame, h_frames) / h_frames, floor((particle_frame + 0.5) / h_frames) / v_frames);\n";
```
Comment (akien-mga) [inline scene/2d/canvas_item.cpp:151]: I guess to address @lawnjelly's comment this should be:
```suggestion
		code += "\tUV += vec2(mod(floor(particle_frame + 0.5), h_frames) / h_frames, floor((particle_frame + 0.5) / h_frames) / v_frames);\n";
```

Comment (akien-mga) [reply scene/2d/canvas_item.cpp:151]: But then this might be worth doing further up when `particle_frame` is calculated?

Maybe there's a better operator that could be done on integer values to calculate `particle_frame` in the first place instead of using floating point?

Comment (lawnjelly) [reply scene/2d/canvas_item.cpp:151]: It's kind of hard to read and follow in the stringifyed format :confused: but I think it could be:
```
floor (mod(particle_frame+0.5, h_frames)) / h_frames
```
Or do the `particle_frame += 0.5;` earlier as a once off as @akien-mga points out.

You could also _in theory_ do something like a:
```
particle_frame = round(particle_frame) + epsilon;
```
And then not need the later bodges .. but for being a little more 'clever' this is something that would be be bound to screw up on some hardware with some special precision etc.

GLES has next to no support for integers unfortunately, which makes this kind of juggling super annoying but necessary.

**Review by lawnjelly — APPROVED** [review]
Am approving this because, despite my comment about the x coordinate, the PR as is fixes a bug, and there's no reason why we can't do the x in a separate PR after this is merged.

**Comment by akien-mga** [comment]
Thanks!
