### PR TITLE
Fix symbol jump history navigation issue.

### LINKED ISSUE #92420: Script editing history is not always correct
### Tested versions

4.3 dev6

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

While #63515 works reliably for the most time, there are some bugged cases that should be fixed. They are related to jumping to other script methods and autoloads.

### Steps to reproduce

0. Open the MRP.
1. Open Base.gd and Second.gd
2. In Second.gd Ctrl+Click on `test()`. You will be teleported to Base.gd
3. Go back in history. You won't land directly at `test()`, there is some extra step in the history
4. In Second.gd, Ctrl+Click on `global` (make sure Single.gd is *not* open)
5. You will be teleported to Single.gd
6. When you go back to history, the previous location is skipped and you'll end up in Base.gd
7. Going forward will skip again to Single.gd. The middle step is gone

### Minimal reproduction project (MRP)

[JumpBugs.zip](https://github.com/godotengine/godot/files/15453186/JumpBugs.zip)

### PR DESCRIPTION
**Pull request by jinyangcruise**
- Fix #92420

- Related #97031
- Related #108057

This PR aims to make the history navigation behave like it does in VS Code/Visual Studio.

There are several main issues in the original code:
1. Each time a script is opened (jump) from other script, its old state will be saved to history, which is unnecessary.
2. A calling of `_save_history()` is unnecessary, as saving is auto triggered by caret changed signal.
3. `TabContainer` and other `Container`s are calling deferred to re-fitting their children. The original code used some `call_deferred` to try as much as possible to `adjust_viewport_to_caret`/`center_viewport_to_caret`. However, sometimes only one tick delay is not enough to get the editor ready for these operations.

before:

https://github.com/user-attachments/assets/39badd73-c9b5-4601-b354-f7c1fc136dfe

https://github.com/user-attachments/assets/b62a067f-7e91-44e0-a3f4-b59a8377e515

after:

https://github.com/user-attachments/assets/193745d2-2c16-42b0-b696-5cf0bb7adef0

https://github.com/user-attachments/assets/8f74f9ae-ad8a-459a-8a20-c5719d6be0b1

MRP:
[test_static_set_2026-02-21_22-50-19.zip](https://github.com/user-attachments/files/25459011/test_static_set_2026-02-21_22-50-19.zip)

### CODE REVIEW

File: scene/gui/control.cpp [hunk 1]
```diff
@@ -1743,6 +1743,54 @@ Size2 Control::get_custom_minimum_size() const {
...
+}
+
+bool Control::is_layout_pending_in_path() const {
+	ERR_MAIN_THREAD_GUARD_V(false);
+	const Control *current_node = this;
+	while (current_node != nullptr) {
+		if (current_node->is_layout_pending()) {
+			return true;
+		}
+		current_node = Object::cast_to<Control>(current_node->get_parent_control());
```
Comment (KoBeWi) [inline scene/gui/control.cpp]:
```suggestion
		current_node = current_node->get_parent_control();
```

**Review by KoBeWi — COMMENTED** [review]
I can confirm that it fixes the issue, but I'm not sure about all the changes to Control class, and especially exposing them. If they are absolutely necessary, they can be internal. Although sounds like it's just a workaround for script editor overusing deferred calls (or maybe it's the "proper" fix that's supposed to avoid the deferred calls?).

File: scene/gui/tab_container.h [hunk 2]
```diff
@@ -126,7 +126,9 @@ class TabContainer : public Container {
 	int _get_tab_height() const;
 	Vector<Control *> _get_tab_controls() const;
 	void _on_theme_changed();
+	void _repaint_call_deferred();
 	void _repaint();
+	void __repaint();
```
Comment (AThousandShips) [inline scene/gui/tab_container.h]: This should be named something else `__` is reserved

File: doc/classes/TextEdit.xml [hunk 3]
```diff
@@ -840,6 +841,13 @@
 				Returns [code]true[/code] if the gutter at the given index on the given line is clickable. See [method set_line_gutter_clickable].
 			</description>
 		</method>
+		<method name="is_line_in_viewport" qualifiers="const">
+			<return type="bool" />
+			<param index="0" name="line" type="int" />
+			<description>
+				Returns [code]true[/code] if the given line is within the scope of scrollable area of the viewport.
```
Comment (AThousandShips) [inline doc/classes/TextEdit.xml]:
```suggestion
				Returns [code]true[/code] if the given line is within the scope of the scrollable area of the viewport.
```

File: doc/classes/TabContainer.xml [hunk 4]
```diff
@@ -6,6 +6,7 @@
 	<description>
 		Arranges child controls into a tabbed view, creating a tab for each one. The active tab's corresponding control is made visible, while all other child controls are hidden. Ignores non-control children.
 		[b]Note:[/b] The drawing of the clickable tabs is handled by this node; [TabBar] is not needed.
+		[b]Note:[/b] Some operations, such as adding or removing child, switching tabs, or changing the active tab, and so on, can trigger the [TabContainer] to start layout pending, see [method Control.layout_pending_start].
```
Comment (AThousandShips) [inline doc/classes/TabContainer.xml]:
```suggestion
		[b]Note:[/b] Some operations, such as adding or removing a child, switching tabs, or changing the active tab, can trigger the [TabContainer] to start layout pending, see [method Control.layout_pending_start].
```
Though "start layout pending" is a bit odd

File: doc/classes/Control.xml [hunk 5]
```diff
@@ -1193,6 +1236,13 @@
 				Emitted when the node receives an [InputEvent].
 			</description>
 		</signal>
+		<signal name="layout_pending_finished">
+			<description>
+				Emitted when the node's layout is finished.
+				[b]Note:[/b] This signal is emitted by [method layout_pending_finish]. Not all [Control] types emit or handle this signal. Currently, only [Container] types do so, as children sorting does not complete immediately.
```
Comment (AThousandShips) [inline doc/classes/Control.xml]:
```suggestion
				[b]Note:[/b] This signal is emitted by [method layout_pending_finish]. Not all [Control] types emit or handle this signal. Currently, only [Container] types do so, as child sorting does not complete immediately.
```

File: doc/classes/Control.xml [hunk 6]
```diff
@@ -355,6 +355,16 @@
...
 			</description>
 		</method>
+		<method name="call_on_all_layout_pending_finished">
+			<return type="void" />
+			<param index="0" name="callback" type="Callable" />
+			<description>
+				Call [param callback] on self and all ancestor controls have finished layout pending. If not any of these controls is pending layout, [param callback] is called immediately.
+				If the [param callback] depends on the control's position or size while any ancestor container is still laying out, you should use this method.
+				[b]Note:[/b] This is achieved by a signal emitted by [method layout_pending_finish], so it may be delayed, see [signal layout_pending_finished].
+				[b]Note:[/b] Not all [Control] types support or require pending layout. Currently only [Container] types do, as children sorting does not complete immediately. However, This method is still safe to use even on controls with no [Container] ancestors.
```
Comment (AThousandShips) [inline doc/classes/Control.xml]:
```suggestion
				[b]Note:[/b] Not all [Control] types support or require pending layout. Currently only [Container] types do, as child sorting does not complete immediately. However, This method is still safe to use even on controls with no [Container] ancestors.
```

**Comment by KoBeWi** [comment]
> The reason I expose these methods is to reduce some of the uncertainty around Control and Container nodes.

That should be its own proposal/PR. Don't add new features for a bugfix 🙃

File: scene/gui/tab_container.h (hunk 2 above)
Comment (jinyangcruise) [reply scene/gui/tab_container.h]: Renamed to `_repaint_internal`.

File: doc/classes/TextEdit.xml (hunk 3 above)
Comment (jinyangcruise) [reply doc/classes/TextEdit.xml]: Fixed.

**Review by AdriaandeJongh — COMMENTED** [review]
The resulting behavior is quite obviously desired from a usability perspective, but I think the code review is what matters most here as there may be unexpected changes in behavior that I haven't found while trying this PR. I'm not knowledgeable enough about the underlying code.

File: scene/gui/control.cpp [hunk 7]
```diff
@@ -1743,6 +1743,54 @@ Size2 Control::get_custom_minimum_size() const {
...
+		if (current_node->is_layout_pending()) {
+			return current_node;
+		}
+		current_node = current_node->get_parent_control();
+	}
+	return nullptr;
+}
+
+void Control::call_on_all_layout_pending_finished(const Callable &p_callable) {
+	if (Control *pending_control = get_layout_pending_control_in_path()) {
```
Comment (KoBeWi) [inline scene/gui/control.cpp]: Don't assign inside conditions.

File: scene/gui/control.cpp [hunk 8]
```diff
@@ -1743,6 +1743,54 @@ Size2 Control::get_custom_minimum_size() const {
 	return data.custom_minimum_size;
 }
 
+bool Control::is_layout_pending() const {
+	ERR_MAIN_THREAD_GUARD_V(false);
+	return data.layout_pending;
+}
+
+bool Control::is_layout_pending_in_path() const {
```
Comment (KoBeWi) [inline scene/gui/control.cpp]:
```suggestion
bool Control::is_layout_pending_in_tree() const {
```
Consistent with `is_visible_in_tree()`.
Same with `get_layout_pending_control_in_path()`.

File: scene/gui/tab_container.cpp [hunk 9]
```diff
@@ -259,7 +259,17 @@ void TabContainer::_on_theme_changed() {
 	theme_changing = false;
 }
 
+void TabContainer::_repaint_call_deferred() {
+	layout_pending_start();
+	callable_mp(this, &TabContainer::_repaint).call_deferred();
```
Comment (KoBeWi) [inline scene/gui/tab_container.cpp]: Shouldn't this call `_repaint_internal()`?

File: scene/gui/container.cpp
Comment (KoBeWi) [inline scene/gui/container.cpp:1]: Is this change relevant if the methods are internal?

File: editor/script/script_editor_plugin.cpp [hunk 10]
```diff
@@ -315,6 +309,7 @@ void ScriptEditor::_save_history() {
 
 		if (Object::cast_to<TextEditorBase>(n)) {
 			history.write[history_pos].state = Object::cast_to<TextEditorBase>(n)->get_navigation_state();
+			Dictionary(history[history_pos].state)["ensure_caret_visible"] = true;
```
Comment (KoBeWi) [inline editor/script/script_editor_plugin.cpp]:
```suggestion
			Dictionary nav_state = Object::cast_to<TextEditorBase>(n)->get_navigation_state();
			nav_state["ensure_caret_visible"] = true;
			history.write[history_pos].state = nav_state
```

File: editor/script/script_editor_plugin.cpp [hunk 11]
```diff
@@ -374,6 +369,7 @@ void ScriptEditor::_go_to_tab(int p_idx) {
...
```
Comment (KoBeWi) [inline editor/script/script_editor_plugin.cpp]: Same as above.

File: editor/script/script_editor_plugin.cpp [hunk 12]
```diff
@@ -3425,6 +3413,7 @@ void ScriptEditor::_update_history_pos(int p_new_pos) {
 
 	if (Object::cast_to<TextEditorBase>(n)) {
 		history.write[history_pos].state = Object::cast_to<TextEditorBase>(n)->get_navigation_state();
+		Dictionary(history[history_pos].state)["ensure_caret_visible"] = true;
```
Comment (KoBeWi) [inline editor/script/script_editor_plugin.cpp]: Same.

**Review by KoBeWi — APPROVED** [review]
Seems ok overall. The newly added methods are fully internal, so they are fine.

File: scene/gui/control.cpp (hunk 7 above)
Comment (jinyangcruise) [reply scene/gui/control.cpp]: Fixed.

File: scene/gui/control.cpp (hunk 8 above)
Comment (jinyangcruise) [reply scene/gui/control.cpp]: Fixed.

File: scene/gui/tab_container.cpp (hunk 9 above)
Comment (jinyangcruise) [reply scene/gui/tab_container.cpp]: Yes, replaced to `_repaint_internal()`.

File: scene/gui/container.cpp
Comment (jinyangcruise) [reply scene/gui/container.cpp:1]: Yes, since the code editor has many ancestor containers (not just TabContainer), the Container's `_sort_children()` method uses `call_deferred`. Therefore, we need to wait until all pending operations are completed.

File: editor/script/script_editor_plugin.cpp (hunk 10 above)
Comment (jinyangcruise) [reply editor/script/script_editor_plugin.cpp]: Fixed.

File: editor/script/script_editor_plugin.cpp (hunk 11 above)
Comment (jinyangcruise) [reply editor/script/script_editor_plugin.cpp]: Fixed.

File: editor/script/script_editor_plugin.cpp (hunk 12 above)
Comment (jinyangcruise) [reply editor/script/script_editor_plugin.cpp]: Fixed.
