### PR TITLE
Fix `EditorContextMenuPlugin` `CONTEXT_SLOT_FILESYSTEM_CREATE` does not receive path information for some menus

### LINKED ISSUE #106819: Development: EditorContextMenuPlugin CONTEXT_SLOT_FILESYSTEM_CREATE does not receive path information when accessing from empty space click context menu of file list
### Tested versions

- Reproducible at software built from `master` branch.
Causing code at: https://github.com/godotengine/godot/blob/45fc515ae3574e9c1f9deacaa6960dec68a7d38b/editor/filesystem_dock.cpp#L2608

### System information

MacOS 15.5 (24F74)

### Issue description

This issue was discovered while fixing another bug in [this pull request](https://github.com/godotengine/godot/pull/106811).

When clicking the empty space of the file tree, after click the popup menu generated by EditorContextMenuPlugin, the path of that file tree is not passed to the handle callback.

For `CONTEXT_SLOT_FILESYSTEM_CREATE` context, clicking the option at "Create New" sub-popup menu (in stable version), the folder path is passed as the callback parameter. However, for the file list panel, if it does not pass the folder path, users might not have a quick way to get the folder location, making it hard for creating new files.

Causing code (at master branch):
```c++
if (!EditorContextMenuPluginManager::get_singleton()->activate_custom_option(EditorContextMenuPlugin::CONTEXT_SLOT_FILESYSTEM, p_option, p_selected)) {
	EditorContextMenuPluginManager::get_singleton()->activate_custom_option(EditorContextMenuPlugin::CONTEXT_SLOT_FILESYSTEM_CREATE, p_option, p_selected);
}
```
Instead of `current_path`, `p_selected` is passed to the plugin handle. For empty space click on file tree, since nothing selected, the containing folder location will not be passed.

### Steps to reproduce

* Use the mock code below
* Move mouse pointer to the empty space of file list panel of FileSystem dock.
* Right-click, find the test option in the popup menu.
* The console output should be empty array.

### Minimal reproduction project (MRP)

Mock code:

`FileSystemCreateNewHelper.gd`.
```gdscript
class_name  FileSystemCreateNewHelper
extends EditorContextMenuPlugin

func _popup_menu(paths: PackedStringArray) -> void:
    self.add_context_menu_item(
        "TestItem..." if paths.size() > 0 else "New TestItem...",
        self.handleCreateNew,
        godot_util.getEditorIcon("Node2D")
    )

static func handleCreateNew(paths: PackedStringArray):
    print_debug(paths)
    pass
```

Add above class's instance in `plugin.gd`:

```gdscript
func _get_plugin_name() -> String: return "TestPlugin"

func _enter_tree()():
    self.filesystem_popup_helper = FileSystemCreateNewHelper.new()
    self.add_context_menu_plugin(
        EditorContextMenuPlugin.CONTEXT_SLOT_FILESYSTEM_CREATE,
        self.filesystem_popup_helper
    )

func _exit_tree():
    if self.filesystem_popup_helper != null:
        self.remove_context_menu_plugin(self.filesystem_popup_helper)
```

### PR DESCRIPTION
**Pull request by OzelotVanilla**
Testable based on the code of [this pull request](https://github.com/godotengine/godot/pull/106811), since this bug was found when fixing another issue.

fix #106819

### CODE REVIEW

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -2605,7 +2605,14 @@ void FileSystemDock::_file_option(int p_option, const Vector<String> &p_selected
...
 				if (!EditorContextMenuPluginManager::get_singleton()->activate_custom_option(EditorContextMenuPlugin::CONTEXT_SLOT_FILESYSTEM, p_option, p_selected)) {
-					EditorContextMenuPluginManager::get_singleton()->activate_custom_option(EditorContextMenuPlugin::CONTEXT_SLOT_FILESYSTEM_CREATE, p_option, p_selected);
+					// For create new file option, pass the path location of mouse click position instead, to plugin callback.
+					String fpath = current_path;
+					if (!fpath.ends_with("/")) {
+						fpath = fpath.get_base_dir();
+					}
+					Vector<String> paths;
+					paths.push_back(fpath);
+					EditorContextMenuPluginManager::get_singleton()->activate_custom_option(EditorContextMenuPlugin::CONTEXT_SLOT_FILESYSTEM_CREATE, p_option, paths);
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:2615]:
```suggestion
					EditorContextMenuPluginManager::get_singleton()->activate_custom_option(EditorContextMenuPlugin::CONTEXT_SLOT_FILESYSTEM_CREATE, p_option, { fpath });
```

**Review by KoBeWi — APPROVED** [review]

**Comment by OzelotVanilla** [comment]
Sorry I just mis-typed the commit message !

**Comment by OzelotVanilla** [comment]
Typo fixed.

**Comment by OzelotVanilla** [comment]
> I realized this also requires updating the docs.

I found the editing the document will make conflict when this PR and [another one](https://github.com/godotengine/godot/pull/106811) merge to the master branch.
Should I solve merge conflicts by myself, or just finish updating the document here ?

**Comment by KoBeWi** [comment]
Update the doc normally and then you'll have to rebase the other PR after one is merged.

**Comment by OzelotVanilla** [comment]
> Update the doc normally and then you'll have to rebase the other PR after one is merged.

Got it. Waiting for either PR to be merged first.

**Comment by Repiteo** [comment]
Could you squash the commits? See our [workflow guidelines](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#modifying-a-pull-request) for more information

**Comment by OzelotVanilla** [comment]
> Could you squash the commits? See our [workflow guidelines](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#modifying-a-pull-request) for more information

OK. I misunderstood the content. Let me squash all into one.

**Comment by OzelotVanilla** [comment]
Now my two PRs has done the squashing job. Thank you all for the patience and instructions.
Waiting for either PR to be merged first.

**Comment by Repiteo** [comment]
That PR got merged first, so this'll need that rebase

**Comment by OzelotVanilla** [comment]
Just finished the rebase work and pushed.
And I remember in the first, I wrongly chose `4.4` branch for testing, then I changed to `master`, found that the path param for the callback function changes.

In my own opinion, I also agree that changing the behaviour of passing the param for the callback is better.

**Comment by Repiteo** [comment]
Is that compilation error tied to this PR, or is it unrelated?

**Comment by OzelotVanilla** [comment]
> Is that compilation error tied to this PR, or is it unrelated?

I would like to say this PR does not breaks the compilation.
Previously this PR is based on branch `4.4`, and I had successfullt compiled this many times.

I notice that `drivers/metal` is only generating warnings while compiling `4.4` but errors for `master`. I guess that the changing in that folder makes the compilation fail.

Warning example while compiling `4.4`:
```
drivers/metal/pixel_formats.mm:576:41: warning: mixture of designated and non-designated initializers in the same initializer list is a C99 extension [-Wc99-designator]
  576 |         _mtl_pixel_format_descs[p_pix_fmt] = { .mtlPixelFormat = p_pix_fmt, DataFormat::DATA_FORMAT_MAX, p_fmt_caps, p_view_class, p_pix_fmt_linear, p_name };
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/metal/pixel_formats.mm:576:70: note: first non-designated initializer is here
  576 |         _mtl_pixel_format_descs[p_pix_fmt] = { .mtlPixelFormat = p_pix_fmt, DataFormat::DATA_FORMAT_MAX, p_fmt_caps, p_view_class, p_pix_fmt_linear, p_name };
  ```

**Comment by OzelotVanilla** [comment]
By the way, I think this pull request itself could be merged for now @Repiteo.
Currently discussing the compilation issue in the developers' chat channel.

Edit: Rebased current branch onto `master`. 
As @KoBeWi mentioned before, can I ask if this pull request itself still need more edit, or it gets ready to be merged ?

**Comment by Repiteo** [comment]
Thanks!

**Comment by OzelotVanilla** [comment]
> Thanks!

Thank you also !
