### PR TITLE
Separate Node editor dock

### LINKED ISSUE #11590: Replace 'Node' dock with 'Signals' and 'Groups'
### Describe the project you are working on

A Godot game (this applies to all Godot users).

### Describe the problem or limitation you are having in your project

The 'Node' editor dock has an unnecessarily confusing and cluttered layout.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

One aspect of Godot that never made any sense to me since the day I started using it was signals and groups being hidden away in a 'Node' editor dock. For the following reasons, I believe it would make more sense for these two features to be separated into their own editor docks:
1. The naming of the dock is more confusing than it needs to be. Sure, both signals and groups are aspects of a node, but so are their properties/values, which are instead in the 'Inspector' tab. If I were using Godot for the first time, I would have no idea that signals and groups are under this tab, and might even expect to find their properties there (this is exactly what happened to me when I was new to Godot).
2. It adds unnecessary clutter and takes up space. Making this change would remove the 'Node' tab entirely, as well as effectively shrinking the 'Signals' and 'Groups' sub-tabs by turning them into their own docks, freeing up a little more space for actual information (the lists of signals and groups). Having a dock with separate sections seems overkill when there are only two of them.
3. It can add unnecessary clicks. For example, to access the groups of a node, if you are currently looking at the node inspector, you must first click 'Node' and then select 'Groups'. I realise this is minor, but reducing the number of clicks required to perform a task can be beneficial for user experience.
4. The change will allow for more customisation of the editor layout.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Before:
Image
After (the font looks a bit off but you get the idea):
Image

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It will be used often. I will instead use this section to discuss the potential downsides:
1. The main reason to not implement this that I can think of is that people are used to the old way instead. I'd argue that this change is small enough to not be disruptive/confusing to people experienced with Godot but helpful enough to make the experience easier for newer users (and all users in general due to the reduced clicks).
2. There may also be concerns about this taking up more screen space as one dock is being split into two. However, this change will free up more screen space than it takes, and importantly, it will free up space in an area where information is listed, and instead use space where there is currently only whitespace for 99% of Godot users.

### Is there a reason why this should be core and not an add-on in the asset library?

It is core.

I'm not sure how this idea will be received as it is a change to something that has remained the same for a long time, but I do believe it would be an improvement. Thank you all for your consideration! :)

### LINKED ISSUE #103033: Node dock broken right after opening project
### Tested versions

4.4 beta4

### System information

W10

### Issue description

Image

This happens when the editor has just opened and no node was selected yet. The dock never edits anything and doesn't get initialized properly.

### Steps to reproduce

1. Make sure no node is selected
2. Restart the project
3. Make sure still no node is selected
4. Check Node dock

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Break-Ben**
Closes https://github.com/godotengine/godot-proposals/issues/11590
Fixes #103033
Alternative PR: #101584
Also related to https://github.com/godotengine/godot-proposals/discussions/9052 and https://github.com/godotengine/godot-proposals/issues/9448

Separated the Node editor dock into a Signals editor dock and a Groups editor dock (justification in the linked proposal). 

Before:
before
After:
after

Thanks :)

### CODE REVIEW

**Comment by Break-Ben** [comment]
Update: fixed documentation references

File: editor/editor_feature_profile.h [hunk 1]
```diff
@@ -49,7 +49,8 @@ class EditorFeatureProfile : public RefCounted {
 		FEATURE_SCRIPT,
 		FEATURE_ASSET_LIB,
 		FEATURE_SCENE_TREE,
-		FEATURE_NODE_DOCK,
+		FEATURE_SIGNALS_DOCK,
+		FEATURE_GROUPS_DOCK,
```
Comment (Mickeon) [inline editor/editor_feature_profile.h:53]: Do not remove the Node dock constant, and add the new two at the end of the enum.

**Review by Mickeon — COMMENTED** [review]
As is, the current PR breaks compatibility with feature profiles because of the removal of **FEATURE_NODE_DOCK** and the two new features added in the middle. The **FEATURE_NODE_DOCK** constant should at least be marked as deprecated. But it would also no longer do anything, which is likely not desired...

**Comment by Break-Ben** [comment]
There were many merge conflicts with this PR, so I rewrote it from scratch, and it's now back to its previous functional state.

To reiterate, this PR is **fully functional**. The only unresolved concern I had was allowing it to work with feature profiles without breaking compatibility. My current solution, as shown in my last comment, simply marks the Node dock option as deprecated and adds the 2 new docks to the bottom of the list.
If this solution is acceptable, I will reopen the PR. If not, I would appreciate some help/advice with an alternate solution, as I can't personally think of a good alternative that doesn't break compatibility.

With all the other UI changes in 4.6, I would love to get this merged in time!

_Also, apologies for leaving this PR dormant for so long - seemingly whenever I had free time, there was a feature freeze_

File: editor/docks/signals_dock.h [hunk 2]
```diff
@@ -31,44 +31,27 @@
...
+	GDCLASS(SignalsDock, EditorDock);
 
 	ConnectionsDock *connections = nullptr;
-	GroupsEditor *groups = nullptr;
-
-	HBoxContainer *mode_hb = nullptr;
 
 	Label *select_a_node = nullptr;
 
 private:
```
Comment (AThousandShips) [inline editor/docks/signals_dock.h]:
```suggestion
```

File: editor/docks/signals_dock.h [hunk 3]
```diff
@@ -31,44 +31,27 @@
...
-	static NodeDock *get_singleton() { return singleton; }
-
-protected:
-	void _notification(int p_what);
-
-	virtual void save_layout_to_config(Ref<ConfigFile> &p_layout, const String &p_section) const override;
-	virtual void load_layout_from_config(const Ref<ConfigFile> &p_layout, const String &p_section) override;
+	static SignalsDock *get_singleton() { return singleton; }
 
 public:
```
Comment (AThousandShips) [inline editor/docks/signals_dock.h]:
```suggestion
```

File: editor/docks/groups_dock.h [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+#include "groups_editor.h"
+
+class GroupsDock : public EditorDock {
+	GDCLASS(GroupsDock, EditorDock);
+
+	GroupsEditor *groups = nullptr;
+
+	Label *select_a_node = nullptr;
+
+private:
```
Comment (AThousandShips) [inline editor/docks/groups_dock.h]:
```suggestion
```

File: editor/docks/groups_dock.h [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
+/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
+/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
+/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
+/**************************************************************************/
+
+#pragma once
+
+#include "editor/docks/editor_dock.h"
+#include "groups_editor.h"
```
Comment (AThousandShips) [inline editor/docks/groups_dock.h]:
```suggestion
#include "editor/docks/groups_editor.h"
```

**Comment by passivestar** [comment]
Tested, works as expected and makes sense

**Comment by Break-Ben** [comment]
I'll reopen this PR now in case the current deprecation approach is acceptable, but I'm still happy to implement an alternative

**Comment by KoBeWi** [comment]
The Group dock is not properly disabled when a Resource is selected and prints errors when toggling groups.

File: doc/classes/EditorFeatureProfile.xml [hunk 6]
```diff
@@ -110,7 +110,7 @@
 			Scene tree editing. If this feature is disabled, the Scene tree dock will still be visible but will be read-only.
 		</constant>
 		<constant name="FEATURE_NODE_DOCK" value="4" enum="Feature">
```
Comment (KoBeWi) [inline doc/classes/EditorFeatureProfile.xml]: The deprecated note should be added as a tag
```suggestion
		<constant name="FEATURE_NODE_DOCK" value="4" enum="Feature" deprecated="Message">
```

File: doc/classes/EditorFeatureProfile.xml [hunk 7]
```diff
@@ -124,7 +124,13 @@
 		<constant name="FEATURE_GAME" value="8" enum="Feature">
 			The Game tab, which allows embedding the game window and selecting nodes by clicking inside of it. If this feature is disabled, the Game tab won't display.
 		</constant>
-		<constant name="FEATURE_MAX" value="9" enum="Feature">
+		<constant name="FEATURE_SIGNALS_DOCK" value="9" enum="Feature">
+			The Signals dock. If this feature is disabled, signals won't be visible from the editor.
```
Comment (KoBeWi) [inline doc/classes/EditorFeatureProfile.xml]:
```suggestion
			The Signals dock. If this feature is disabled, signals won't be visible and modifiable from the editor.
```

File: editor/settings/editor_feature_profile.cpp [hunk 8]
```diff
@@ -47,23 +47,27 @@ const char *EditorFeatureProfile::feature_names[FEATURE_MAX] = {
 	TTRC("Script Editor"),
 	TTRC("Asset Library"),
 	TTRC("Scene Tree Editing"),
-	TTRC("Node Dock"),
+	TTRC("Node Dock (deprecated)"),
```
Comment (KoBeWi) [inline editor/settings/editor_feature_profile.cpp:51]: All deprecated code should also be wrapped in `#ifndef DISABLE_DEPRECATED`, that includes labels, descriptions, enum values etc.

File: editor/docks/groups_dock.h [hunk 9]
```diff
@@ -0,0 +1,54 @@
...
+
+class GroupsDock : public EditorDock {
+	GDCLASS(GroupsDock, EditorDock);
+
+	GroupsEditor *groups = nullptr;
+
+	Label *select_a_node = nullptr;
+
+private:
+	inline static GroupsDock *singleton = nullptr;
```
Comment (KoBeWi) [inline editor/docks/groups_dock.h]:
```suggestion
	static inline GroupsDock *singleton = nullptr;
```

File: doc/classes/EditorFeatureProfile.xml [hunk 10]
```diff
@@ -110,7 +110,7 @@
 			Scene tree editing. If this feature is disabled, the Scene tree dock will still be visible but will be read-only.
 		</constant>
 		<constant name="FEATURE_NODE_DOCK" value="4" enum="Feature">
-			The Node dock. If this feature is disabled, signals and groups won't be visible and modifiable from the editor.
+			The Node dock (deprecated). If this feature was disabled, signals and groups wouldn't be visible and modifiable from the editor.
```
Comment (AThousandShips) [inline doc/classes/EditorFeatureProfile.xml]: Please restore, this shouldn't be made past tense

File: editor/settings/editor_feature_profile.cpp [hunk 11]
```diff
@@ -46,23 +46,27 @@ const char *EditorFeatureProfile::feature_names[FEATURE_MAX] = {
...
+	TTRC("Groups Dock")
 };
 
 const char *EditorFeatureProfile::feature_descriptions[FEATURE_MAX] = {
 	TTRC("Allows to view and edit 3D scenes."),
 	TTRC("Allows to edit scripts using the integrated script editor."),
 	TTRC("Provides built-in access to the Asset Library."),
 	TTRC("Allows editing the node hierarchy in the Scene dock."),
-	TTRC("Allows to work with signals and groups of the node selected in the Scene dock."),
+	TTRC("Allowed to work with signals and groups of the node selected in the Scene dock."),
```
Comment (AThousandShips) [inline editor/settings/editor_feature_profile.cpp]: Same here, please restore

File: editor/docks/signals_dock.h (hunk 2 above)
Comment (AThousandShips) [inline editor/docks/signals_dock.h]:
```suggestion
```

File: editor/docks/signals_dock.h (hunk 3 above)
Comment (AThousandShips) [inline editor/docks/signals_dock.h]:
```suggestion
```

File: editor/docks/groups_dock.h (hunk 4 above)
Comment (AThousandShips) [inline editor/docks/groups_dock.h]:
```suggestion
```

File: editor/docks/groups_dock.h (hunk 5 above)
Comment (AThousandShips) [inline editor/docks/groups_dock.h]:
```suggestion
#include "editor/docks/groups_editor.h"
```

File: editor/docks/groups_dock.h [hunk 12]
```diff
@@ -0,0 +1,54 @@
...
+
+public:
+	static GroupsDock *get_singleton() { return singleton; }
+
+public:
```
Comment (AThousandShips) [inline editor/docks/groups_dock.h]:
```suggestion
```

**Comment by Break-Ben** [comment]
Thank you all for the reviews! I believe it should be all good now

**Review by KoBeWi — APPROVED** [review]

**Comment by KeyboardDanni** [comment]
This seems like a net positive to me.

It feels weird to have these views in tabs named "Signals" and "Groups" because now you don't have the context of them being properties of the selected Node. On the other hand I think it's weirder that we had multiple levels of tabs. At one point I had an editor layout saved with the Node tab open and focused on "Groups" which led to some confusion in the past whenever I loaded that layout. Because I don't use groups, this change means I can just close the Groups tab and remove some of the clutter.

I do worry that this could create too many top-level tabs though. Right now I have Inspector, Node, Import, History as the four tabs in my right pane. This change would increase that to 5 were I to not close the Groups tab.

**Comment by Meorge** [comment]
This also sounds good to me.

It does make me wonder if the "Inspector" tab should be named to something else, like "Properties". The word "Inspector" feels too all-encompassing to me, for something that only allows you to inspect _some_ aspects of a selected item, while other aspects are in separate tabs with more precise names. That being said, the term "Inspector" is no doubt used in lots of tutorials and resources, so changing it could cause confusion for newcomers...

**Comment by trickster721** [comment]
In my heart I want all the inspecting to happen in the inspector, but I can't find a way to argue with the logic of the separate docks, it just makes more sense.

The inspector has a slightly odd name, but that uniqueness helps make references to it clear and unambiguous. "Properties" is a technical term, it already refers to a separate idea. "Change the property in the inspector" makes more sense than "change the property in the properties". People would need to call it "the properties tab" for clarity. It's a more accurate description, but a less useful name.

**Comment by Break-Ben** [comment]
Fixed the new merge conflicts. Not exactly sure why the `select_a_node` label was moved out of node dock, as it now makes `signals_dock.cpp` and `groups_dock.cpp` very short, but I updated this PR to match it regardless.

Also, to touch on the reasoning, I understand that having an extra dock will take up more space, but I believe its benefits outweigh this, e.g.
1. Strong level of customisation (you can rearrange the docks, hide some, show them all at once, etc)
2. Consistency with the rest of the app/theming
3. Eliminates the issue of sometimes needing multiple clicks to view signals/groups

**Comment by KoBeWi** [comment]
> Not exactly sure why the select_a_node label was moved out of node dock, as it now makes signals_dock.cpp and groups_dock.cpp very short

The label was moved to Signals and Groups tabs separately, because they have different messages. If they were to be covered by single message, it'd need to be something like "Select a single node to edit its signals or one or multiple nodes to edit their groups, or select an independent resource to view its signals.". Totally incomprehensible.
I guess the alternative was changing the message based on the selected tab, but it's easier if the text does not change.

**Comment by Repiteo** [comment]
Needs rebase

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉

**Comment by HolonProduction** [comment]
Is it intended, that the Signal panel works with resources after this PR? I don't see it mentioned in the PR description.

**Comment by KoBeWi** [comment]
That's from #109043

**Comment by HolonProduction** [comment]
Alright thanks! Does this count under the new theme tracker or is this a separate thing? Because I feel like this addition really requires disambiguation in the dock about which object is currently viewed (similar to how the inspector shows the object in its header). Right now there is no way to tell what the panel is even looking at.

**Comment by KoBeWi** [comment]
The dock changes aren't related to the new theme.

> Right now there is no way to tell what the panel is even looking at.

That's more or less the same as before, just the tabs were moved. The inspector always matches the signal/group docks.
