### PR TITLE
mesh indexing failing with small scale values

### LINKED ISSUE #44655: Regression in fbx with new indexer
**Godot version:**
- 4.0 master 
- I am working in #44653

**OS/device including version:**
- Linux, RX580, VK backend

**Issue description:**
1. Opened working scene in 4.0
2. Scene is not rendered

**video of issue**
https://www.youtube.com/watch?v=zw3hdC2iOV0&feature=youtu.be

**Steps to reproduce:**
1. load current master
2. open **Bistro Exterior fbx**
3. bistro fbx is blank visually but nodes and meshes are in the scene
4. revert commit 3fdf4bfe71311000bf706c16d79b475308a200ac
5. problem is gone

**Minimal reproduction project:**
https://developer.nvidia.com/orca/amazon-lumberyard-bistro

I spent 5 hours yesterday debugging this and it's caused by this commit, before it didn't happen.

I would like to fix this, there are no errors reported on opening the scene.

**Fixes tried**
- null materials
- increase scaling values
- clearing material mapping manually
- rescaling scene meshes
- copying meshes outside of the scene seems to make them visible in some cases but they still disappear.
- flipping cull direction, disabling culling and also disabling depth test
This completely blocks me from working.

### PR DESCRIPTION
**Pull request by RevoluPowered**
Fixes:
- #44655 fbx files not working in latest release
- previous behavior was culling scale values of 0.01 and det == 0.00004. which were valid in FBX land, det was not == 0, but in the cases of actual det==0 scenario which can be reproduced with node_3d_editor_plugin you can see it actually has a det == 0.
- node_3d_editor_plugin was creating gizmos with transforms with det == 0, this is safe to do now due to this change, I have also fixed this for the gizmos but the grid still needs this to be done for it. This relies on absolute zero values to change visibility so I fixed this.
- fixed fbx material mappings going to metallic property

I debugged this by putting checks on det == zero.
I checked bistro fbx and it imports fine, no dropped geometry anymore even with 0.01 scaling and det == 0.00004.

debug build
image

release_debug build (cpu time halves :D)
image

without this PR

image

### CODE REVIEW

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -3281,6 +3281,20 @@ void Node3DEditorViewport::update_transform_gizmo_view() {
 
 	xform.basis.scale(scale);
 
+	// now it's calculated check it's scale if its invalid then disable it.
```
Comment (akien-mga) [inline editor/plugins/node_3d_editor_plugin.cpp:3284]: 1 out of 3, can do better :P

> Now it's calculated check **its** scale if **it's** invalid then disable it.

File: servers/rendering/renderer_scene_cull.cpp [hunk 2]
```diff
@@ -1160,7 +1160,8 @@ void RendererSceneCull::_update_instance(Instance *p_instance) {
 
 	p_instance->transformed_aabb = new_aabb;
 
-	if (p_instance->scenario == nullptr || !p_instance->visible || Math::is_zero_approx(p_instance->transform.basis.determinant())) {
+	// note: is equal approx means 0.01 scale won't work so don't do that.
```
Comment (akien-mga) [inline servers/rendering/renderer_scene_cull.cpp:1163]: That sounds weird, `is_zero_approx` uses `CMP_EPSILON` which is `0.00001`, that's 1000 times smaller than `0.01`.

Comment (RevoluPowered) [reply servers/rendering/renderer_scene_cull.cpp:1163]: Smallest value which is valid to render are these:

so these aren't precision errors
```cpp
Smallest rendered value is 0.000004
Smallest rendered value is 0.000004
Smallest rendered value is 0.000004
Smallest rendered value is 0.000004
Smallest rendered value is 0.000004
Smallest rendered value is 0.000004
Smallest rendered value is 0.000003
```

determinant is returning these, but they're valid.

float can do much much smaller numbers albeit with precision errors but the value must be dealt with otherwise the rendered scene breaks.

File: editor/plugins/node_3d_editor_plugin.cpp (hunk 1 above)
Comment (RevoluPowered) [reply editor/plugins/node_3d_editor_plugin.cpp]: corrected

File: servers/rendering/renderer_scene_cull.cpp (hunk 2 above)
Comment (RevoluPowered) [reply servers/rendering/renderer_scene_cull.cpp]: corrected

**Review by AndreaCatania — APPROVED** [review]

**Comment by AndreaCatania** [comment]
This PR fixes this issue: https://github.com/godotengine/godot/issues/45067

**Comment by akien-mga** [comment]
Needs a rebase @RevoluPowered.

**Comment by reduz** [comment]
Current BVH does not really allow flat AABBs so this fix will do, but I want to replace by one that does soon so this fix will be irrelevant by then. I suggest lets just merge for now so things work.

**Comment by RevoluPowered** [comment]
Rebase is completed.

**Comment by akien-mga** [comment]
Thanks!
