### PR TITLE
Fix the uniform set creation of multimesh with a invalidated buffer

### LINKED ISSUE #60651: `MultiMesh` emits `Condition "uniform.get_id_count() != 1" is true.` error at creation
### Godot version

Godot 4.0 alpha 7

### System information

Windows 10

### Issue description

The following code:
```
extends Node3D

# GrassGenerator.gd

@export var width : int = 512
@export var height : int = 512
@export var subdivisions : int = 20
@export var grass_mesh : Mesh
@export_range(1.0, 10.0) var n = 2.0

var generated = false

func generate():
	if generated:
		return
	var ns := NoiseTexture.new()
	ns.width = width
	ns.height = height
	ns.noise = FastNoiseLite.new()
	await ns.changed
	
	var image : Image = ns.get_image()
	var img_chunk_size = Vector2(width, height) / subdivisions
	var half = Vector2(width, height) / 2
	var grass_mat = preload("res://materials/grass.material")
	var chunk_size = Vector3(img_chunk_size.x, 0, img_chunk_size.y) / n

	for x in range(subdivisions):
		for y in range(subdivisions):
			var mp = Vector3(x, 0, y) * chunk_size - Vector3(half.x, 0, half.y) / n
			var transforms = []
			for sx in range(img_chunk_size.x):
				for sy in range(img_chunk_size.y):
					var v = Vector2(x * img_chunk_size.x + sx, y * img_chunk_size.y + sy)
					var amount = image.get_pixel(v.x, v.y).r
					if amount > 0.5:
						var p = Vector3(sx, 0, sy)
						p /= n
						p += Vector3(randf_range(-0.5, 0.5), 0, randf_range(-0.5, 0.5))
						var random_scale = randf_range(2.0, 3.5)
						var random_height = randf_range(0.0, 3.0)
						var t = Transform3D(Basis(Vector3(0, 1, 0), randf_range(-PI, PI)).scaled(Vector3(random_scale, random_scale + random_height, random_scale)), p)
						
						transforms.push_back(t)
			
			var mmi := MultiMeshInstance3D.new()
			mmi.material_override = grass_mat
			mmi.position = mp
			mmi.visibility_range_end = 100
			mmi.visibility_range_begin_margin = 1.0
			mmi.visibility_range_fade_mode = GeometryInstance3D.VISIBILITY_RANGE_FADE_SELF

			var mm := MultiMesh.new()
			mm.transform_format = MultiMesh.TRANSFORM_3D
			mm.instance_count = transforms.size()
			mm.mesh = grass_mesh
			
			var i = 0
			for t in transforms:
				mm.set_instance_transform(i, t)
				i+=1
			mmi.multimesh = mm
			add_child(mmi)
	generated = true

func _ready() -> void:
	if visible:
		generate()
	else:
		connect(&"visibility_changed", generate)
```

is creating successfully but generate errors

image

Not sure why it's happening, probably `MultiMesh` resource need to take step to be properly initialized.

### Steps to reproduce

Just run the demo project

### Minimal reproduction project

[MMBug.zip](https://github.com/godotengine/godot/files/8596557/MMBug.zip)

### PR DESCRIPTION
**Pull request by n0tank3sh**
Fixes #60651

### CODE REVIEW

File: servers/rendering/renderer_rd/storage_rd/mesh_storage.h [hunk 1]
```diff
@@ -615,6 +615,9 @@ class MeshStorage : public RendererMeshStorage {
 	_FORCE_INLINE_ RID multimesh_get_3d_uniform_set(RID p_multimesh, RID p_shader, uint32_t p_set) const {
 		MultiMesh *multimesh = multimesh_owner.get_or_null(p_multimesh);
 		if (!multimesh->uniform_set_3d.is_valid()) {
```
Comment (Chaosus) [inline servers/rendering/renderer_rd/storage_rd/mesh_storage.h:617]: I would suggest adding a check for multimesh for null also, eg: `if(multimesh == nullptr) { return RID(); }`

Comment (MightiestGoat) [reply servers/rendering/renderer_rd/storage_rd/mesh_storage.h:617]: Thanks for the feedback Chaos.

Comment (MightiestGoat) [reply servers/rendering/renderer_rd/storage_rd/mesh_storage.h]: Done

**Review by clayjohn — APPROVED** [review]
