### PR TITLE
Do not replace starting digit with underscore when making identifier

### LINKED ISSUE #82773: Ctrl-dragging file from FileSystem to code replaces starting digit with underscore
### Godot version

v4.2.dev6.official [57a6813bb]

### System information

Godot v4.2.dev6 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3640) - Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 Threads)

### Issue description

Ctrl-dragging file from FileSystem to code replaces first character with underscore when the file's first character is a digit.

kuva

It seems that all invalid characters are replaced with underscore. But when the file name starts with a digit (invalid character only at the beginning), that seems too harsh. I would suggest just adding extra underscrore to the beginning of the variable name. So in this example, I would expect variable name `_123_ICON` instead of `_23_ICON`.

### Steps to reproduce

1. Duplicate `icon.svg` and rename the duplicate as `123_icon.svg`
2. Ctrl-drag both `icon.svg` and `123_icon.svg` to code 
-> 
```gdscript
const _23_ICON = preload("res://123_icon.svg")
const ICON = preload("res://icon.svg")
```

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by theraot**
This pull request modifies `validate_identifier` to add an underscore when the `String` stars with a digit (instead of replacing the digit with an underscore, which was the old behavior). The `validate_identifier` test cases has been updated accordingly.

Since `validate_identifier` is modified, the helper method `_is_valid_identifier_bit` is not necessary, to remove it `is_valid_identifier` was also modified to not use it.

Fixes https://github.com/godotengine/godot/issues/82773

### CODE REVIEW

**Review by Chubercik — APPROVED** [review]

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected. Results from drag-and-dropping from the FileSystem dock while holding <kbd>Ctrl</kbd>:

```gdscript
const _12345 = preload("res://12345.tscn")
const _0 = preload("res://0.gd")
const __ = preload("res://__.tscn")
const _ = preload("res://_.tscn")
```

`validate_identifier()` is only used in the script editor and for script template creation. The method isn't exposed to scripting, so it should be fine to cherry-pick for `4.1` (given the small behavior change).

File: core/string/ustring.cpp [hunk 1]
```diff
@@ -3974,24 +3974,22 @@ bool String::is_absolute_path() const {
 	}
 }
 
-static _FORCE_INLINE_ bool _is_valid_identifier_bit(int p_index, char32_t p_char) {
-	if (p_index == 0 && is_digit(p_char)) {
-		return false; // No start with number plz.
```
Comment (Calinou) [inline core/string/ustring.cpp:3979]: I'll miss that comment. :eyes:

**Comment by akien-mga** [comment]
I'm a bit worried about the impact this may have on compatibility, notably for the import pipeline. We already broke compat in 4.1 by changing the logic that would remove `.` from node names, and replaced them instead with `_`. If this method is used similarly, we could again run into a situation where Godot 4.1 imported scenes will break.

CC @godotengine/import to help assess this.

**Comment by theraot** [comment]
@akien-mga

If it helps, searching on my end, it seems that `validate_identifier` (aside from the tests) is only used in:

- script_text_editor.cpp on `_get_dropped_resource_line` and `ScriptTextEditor::drop_data_fw`, i.e. as result of dropping something in the text editor, and generating source code.
- gdscript_editor.cpp on `GDScriptLanguage::make_template`, i.e. also generating source code.

Thus, it does not provide names for nodes. Modifying it should not affect existing scripts. And as far as I know it is not involved in importing anything.

I also modified `is_valid_identifier`, however, I believe I didn't change its behavior (its test cases are untouched).

At least, I don't expect issues, but of course I might be mistaken.

**Comment by akien-mga** [comment]
Sounds good, thanks for researching it. I expected it to be used way more, but I guess we have other similar methods in Node that partially duplicate this functionality.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.4.
