### PR TITLE
Fix moving and renaming files

### LINKED ISSUE #22230: Moving a folder can cause Godot to crash even if no scenes are open
Godot 3.1 beta 1
Windows 10 64 bits

It looks very similar to #16853, however it happened with no scenes open*.
Project: [MovingFolder.zip](https://github.com/godotengine/godot/files/2394321/MovingFolder.zip)

Steps:
1) Open the project in editor
2) Close the main scene (so no scenes remain open)
3) In the `gui` folder, move the `main_menu` folder inside the `yolo` folder
4) Godot crashes

*Relevant note: this does not repro if the project has no main scene defined (which won't open it on start). So it looks like some state from the scene leaks even after it was closed.

I had the issue while trying to repro #14900, and this is the log I got:
```
PS D:\PROJETS\INFO\GODOT\Games\Diptera\Diptera> ../../../bin/Godot_v3.1-alpha1_win64.exe -e
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
Boot splash path: res://splash.png
WARNING: load: Loaded resource as image file, this will not work on export: 'res://splash.png'. Instead, import the image file as an Image resource and load it normally as a resource.
     At: core/image.cpp:1734
ERROR: set_drag_preview: Condition ' get_viewport()->gui_is_dragging() ' is true.
   At: scene/gui/control.cpp:772
erasing D:/PROJETS/INFO/GODOT/Games/Diptera/Diptera/gui/yolo/main_menu/main_menu.tscn
erasing D:/PROJETS/INFO/GODOT/Games/Diptera/Diptera/main_client.tscn
ERROR: load_source_code: Condition ' err ' is true. returned: err
   At: modules/gdscript/gdscript.cpp:799
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: modules/gdscript/gdscript.cpp:2126
ERROR: _unref: Condition ' !_p ' is true.
   At: core/dictionary.cpp:171
PS D:\PROJETS\INFO\GODOT\Games\Diptera\Diptera>
```

### LINKED ISSUE #26394: Segmentation fault when moving resources from a folder to another
**Godot version:**

310c755a

**OS/device including version:**
4.20.10-arch1-1-ARCH

**Issue description:**
When moving  a bunch of files from a folder to another folder, the editor crashed with the following backtrace:

```
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x37e00) [0x7f23f254fe00] (??:0)
[2] /usr/lib/libstdc++.so.6(__dynamic_cast+0x24) [0x7f23f290b694] (??:0)
[3] Spatial* Object::cast_to<Spatial>(Object*) (godot/./core/object.h:587)
[4] SpatialEditor::_request_gizmo(Object*) (godot/editor/plugins/spatial_editor_plugin.cpp:5202)
[5] MethodBind1<SpatialEditor, Object*>::call(Object*, Variant const**, int, Variant::CallError&) (godot/./core/method_bind.gen.inc:815)
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (godot/core/object.cpp:945)
[7] MessageQueue::_call_function(Object*, StringName const&, Variant const*, int, bool) (godot/core/message_queue.cpp:256)
[8] MessageQueue::flush() (godot/core/message_queue.cpp:305)
[9] SceneTree::iteration(float) (godot/scene/main/scene_tree.cpp:477)
[10] Main::iteration() (godot/main/main.cpp:1869)
[11] OS_X11::run() (godot/platform/x11/os_x11.cpp:2975)
[12] ./godot.x11.tools.64.llvm(main+0x151) [0x15415e1] (godot/platform/x11/godot_x11.cpp:55)
[13] /usr/lib/libc.so.6(__libc_start_main+0xf3) [0x7f23f253c223] (??:0)
[14] ./godot.x11.tools.64.llvm(_start+0x2e) [0x15413ce] (??:)
-- END OF BACKTRACE --

```

Note about what I was moving:
I was moving files from a folder to a sub folders.
The files were related in the following way:
- A.tscn
- A.escn
- A.gd
- B.tscn
- B.escn
- B.gd

A.tscn is including A.escn and A.gd
B.tscn is including B.escn and B.gd

**Steps to reproduce:**
See Jfons first comment :)

### LINKED ISSUE #28012: Crash when moving directories in FileSystem pane
**Godot version:**
v3.1.stable.official

**OS/device including version:**
MacBook Pro
macOS 10.14.4

**Issue description:**
I created a new "assets" folder in the project's root directory, and dragged and dropped my "audio" folder into it. It said it was reimporting audio assets and then it crashed:

```Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff5bfa22c6 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff5c057bf1 pthread_kill + 284
2   libsystem_c.dylib             	0x00007fff5bf0c6a6 abort + 127
3   org.godotengine.godot         	0x0000000108918e02 handle_crash(int) + 2898
4   libsystem_platform.dylib      	0x00007fff5c04cb5d _sigtramp + 29
5   ???                           	0x000000010bf46240 Engine::singleton + 8
6   org.godotengine.godot         	0x000000010ab3ead6 Object::set(StringName const&, Variant const&, bool*) + 102
7   org.godotengine.godot         	0x000000010ab94f17 Resource::reload_from_file() + 407
8   org.godotengine.godot         	0x00000001094a5c18 EditorNode::_resources_reimported(Vector<String> const&) + 280
9   org.godotengine.godot         	0x00000001094fb18e MethodBind1<Vector<String> const&>::call(Object*, Variant const**, int, Variant::CallError&) + 302
10  org.godotengine.godot         	0x000000010ab41f63 Object::call(StringName const&, Variant const**, int, Variant::CallError&) + 355
11  org.godotengine.godot         	0x000000010ab43e40 Object::emit_signal(StringName const&, Variant const**, int) + 2016
12  org.godotengine.godot         	0x000000010ab42602 Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) + 114
13  org.godotengine.godot         	0x000000010942aa9c EditorFileSystem::reimport_files(Vector<String> const&) + 1548
14  org.godotengine.godot         	0x00000001094293db EditorFileSystem::_update_scan_actions() + 2027
15  org.godotengine.godot         	0x000000010942edd6 EditorFileSystem::_notification(int) + 1334
16  org.godotengine.godot         	0x000000010943804c EditorFileSystem::_notificationv(int, bool) + 76
17  org.godotengine.godot         	0x000000010ab3e9d3 Object::notification(int, bool) + 19
18  org.godotengine.godot         	0x0000000109c74978 SceneTree::_notify_group_pause(StringName const&, int) + 1976
19  org.godotengine.godot         	0x0000000109c74e58 SceneTree::idle(float) + 600
20  org.godotengine.godot         	0x000000010894d95f Main::iteration() + 799
21  org.godotengine.godot         	0x0000000108923407 OS_OSX::run() + 631
22  org.godotengine.godot         	0x000000010892613b main + 811
23  libdyld.dylib                 	0x00007fff5be673d5 start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff5bf9def2 read + 10
1   org.godotengine.godot         	0x00000001089262e9 SemaphoreOSX::wait() + 25
2   org.godotengine.godot         	0x000000010ad420ec _IP_ResolverPrivate::_thread_function(void*) + 60
3   org.godotengine.godot         	0x00000001091148a5 ThreadPosix::thread_callback(void*) + 85
4   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 2:: CVDisplayLink
0   libsystem_kernel.dylib        	0x00007fff5bf9f86a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5c0585a1 _pthread_cond_wait + 773
2   com.apple.CoreVideo           	0x00007fff31758a4b CVDisplayLink::waitUntil(unsigned long long) + 229
3   com.apple.CoreVideo           	0x00007fff31757ffa CVDisplayLink::runIOThread() + 482
4   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff5bf9def2 read + 10
1   org.godotengine.godot         	0x00000001089262e9 SemaphoreOSX::wait() + 25
2   org.godotengine.godot         	0x000000010a97270d VisualServerScene::_gi_probe_bake_thread() + 29
3   org.godotengine.godot         	0x00000001091148a5 ThreadPosix::thread_callback(void*) + 85
4   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 4:: com.apple.audio.IOThread.client
0   libsystem_kernel.dylib        	0x00007fff5bf9c22a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff5bf9c76c mach_msg + 60
2   com.apple.audio.CoreAudio     	0x00007fff2f469eda HALB_MachPort::SendMessageWithReply(unsigned int, unsigned int, unsigned int, unsigned int, mach_msg_header_t*, bool, unsigned int) + 122
3   com.apple.audio.CoreAudio     	0x00007fff2f469e4f HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 45
4   com.apple.audio.CoreAudio     	0x00007fff2f46639f HALC_ProxyIOContext::IOWorkLoop() + 1017
5   com.apple.audio.CoreAudio     	0x00007fff2f465df4 HALC_ProxyIOContext::IOThreadEntry(void*) + 122
6   com.apple.audio.CoreAudio     	0x00007fff2f465956 HALB_IOThread::Entry(void*) + 72
7   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
8   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
9   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff5bf9ff32 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff5bf2b914 nanosleep + 199
2   org.godotengine.godot         	0x000000010911104b OS_Unix::delay_usec(unsigned int) const + 59
3   org.godotengine.godot         	0x0000000109259adf EditorExportPlatformAndroid::_device_poll_thread(void*) + 8543
4   org.godotengine.godot         	0x00000001091148a5 ThreadPosix::thread_callback(void*) + 85
5   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
6   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
7   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 6:
0   libsystem_kernel.dylib        	0x00007fff5bf9ff32 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff5bf2b914 nanosleep + 199
2   org.godotengine.godot         	0x000000010911104b OS_Unix::delay_usec(unsigned int) const + 59
3   org.godotengine.godot         	0x0000000109814934 EditorFileServer::_thread_start(void*) + 884
4   org.godotengine.godot         	0x00000001091148a5 ThreadPosix::thread_callback(void*) + 85
5   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
6   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
7   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 7:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff5bf9c22a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff5bf9c76c mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff2f9f013e __CFRunLoopServiceMachPort + 328
3   com.apple.CoreFoundation      	0x00007fff2f9ef6ac __CFRunLoopRun + 1612
4   com.apple.CoreFoundation      	0x00007fff2f9eee0e CFRunLoopRunSpecific + 455
5   com.apple.AppKit              	0x00007fff2d07dd1a _NSEventThread + 175
6   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
8   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 8:
0   libsystem_kernel.dylib        	0x00007fff5bf9def2 read + 10
1   org.godotengine.godot         	0x00000001089262e9 SemaphoreOSX::wait() + 25
2   org.godotengine.godot         	0x000000010a98c788 VisualServerWrapMT::texture_get_data(RID, int) const + 248
3   org.godotengine.godot         	0x000000010a4daec3 ImageTexture::get_data() const + 51
4   org.godotengine.godot         	0x000000010924e892 ResourceSaverPNG::save(String const&, Ref<Resource> const&, unsigned int) + 210
5   org.godotengine.godot         	0x000000010ad946e5 ResourceSaver::save(String const&, Ref<Resource> const&, unsigned int) + 373
6   org.godotengine.godot         	0x000000010957ad7a EditorResourcePreview::_generate_preview(Ref<ImageTexture>&, Ref<ImageTexture>&, EditorResourcePreview::QueueItem const&, String const&) + 1914
7   org.godotengine.godot         	0x0000000109578ed3 EditorResourcePreview::_thread() + 2019
8   org.godotengine.godot         	0x00000001091148a5 ThreadPosix::thread_callback(void*) + 85
9   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
10  libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
11  libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 9:
0   libsystem_pthread.dylib       	0x00007fff5c0543f0 start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000111a0a5c0  rcx: 0x00007ffee72e66d8  rdx: 0x0000000000000000
  rdi: 0x0000000000000307  rsi: 0x0000000000000006  rbp: 0x00007ffee72e6710  rsp: 0x00007ffee72e66d8
   r8: 0x00000000000130a8   r9: 0x00007fff8ee61048  r10: 0x0000000000000000  r11: 0x0000000000000206
  r12: 0x0000000000000307  r13: 0x0000000000000015  r14: 0x0000000000000006  r15: 0x000000000000002d
  rip: 0x00007fff5bfa22c6  rfl: 0x0000000000000206  cr2: 0x00007fff8ee5f188
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133
```

### PR DESCRIPTION
**Pull request by hpvb**
This commit fixes several issues related to moving scenes and resources
in an open project.

* Don't try to reload scenes while not all scenes are updated yet.
* Don't use the UndoRedo system to update non-user initiated editor
state.
* Resave scenes after moving files and updating resource path(s).

Fixes #28012
Fixes #22230
Fixes #26394

Closes #26910 (superseded by this)

### CODE REVIEW

**Comment by hpvb** [comment]
@QbieShay Does this make sense to you too?

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -2859,7 +2873,7 @@ bool EditorNode::is_addon_plugin_enabled(const String &p_addon) const {
 	return plugin_addons.has(p_addon);
 }
 
-void EditorNode::_remove_edited_scene() {
+void EditorNode::_remove_edited_scene(bool change_tab) {
```
Comment (akien-mga) [inline editor/editor_node.cpp]: Please use `p_` prefix for parameters.

**Comment by groud** [comment]
Wow thanks ! I had hard time trying to understand why my changes to the Filesystem dock caused those issues. Glad you figured it out !

**Comment by QbieShay** [comment]
@hpvb Works for me! Thanks a lot!

**Review by akien-mga — APPROVED** [review]

File: editor/filesystem_dock.cpp [hunk 2]
```diff
@@ -1384,13 +1406,20 @@ void FileSystemDock::_move_operation_confirm(const String &p_to_path, bool overw
...
 		_update_resource_paths_after_move(file_renames);
 		_update_project_settings_after_move(file_renames);
 		_update_favorites_list_after_move(file_renames, folder_renames);
 
+		editor->set_current_tab(current_tab);
+
 		print_verbose("FileSystem: calling rescan.");
 		_rescan();
+
+		print_verbose("FileSystem: saving moved scenes.");
```
Comment (reduz) [inline editor/filesystem_dock.cpp]: you forgot a print :)

Comment (hpvb) [reply editor/filesystem_dock.cpp]: I added this because there's a print_verbose for 'calling rescan' also

**Comment by hpvb** [comment]
After talking to @reduz I've made the new tab change methods on EditorNode protected and added FilesystemDock as a friend. I think this is good to go.

https://github.com/godotengine/godot/pull/29459/files#diff-6c5dc324a846b5dc5b3b8934b1130a5bR647

**Comment by akien-mga** [comment]
Thanks a lot!

**Comment by groud** [comment]
Would this fix #29215 too ?

**Comment by hpvb** [comment]
@groud I don't think so, but I'm happy to have a look at that one.

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.
