### PR TITLE
Fix LineEdit drag selection to the left

### LINKED ISSUE #11948: It's not possible to move text back with the cursor in LineEdit
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
[Build](https://bintray.com/calinou/godot/editor) 7eecfcb

**Issue description:**
While you can make the text move forward, you have to use the keyboard to move it backwards:
video

### PR DESCRIPTION
**Pull request by AlexHolly**
Not sure what the code for the right dragging is, maybe it is also needed with left direction dragging.

see
https://github.com/AlexHolly/godot/blob/99a3f3ec19cdb1246a548407be99fd5bd69e0e89/scene/gui/line_edit.cpp#L1046

My solution seems to work.

Closes #11948

### CODE REVIEW

File: scene/gui/line_edit.cpp [hunk 1]
```diff
@@ -1036,9 +1036,11 @@ void LineEdit::set_cursor_position(int p_pos) {
 	Ref<StyleBox> style = get_stylebox("normal");
 	Ref<Font> font = get_font("font");
 
-	if (cursor_pos < window_pos) {
+	if (cursor_pos <= window_pos) {
 		/* Adjust window if cursor goes too much to the left */
-		set_window_pos(cursor_pos);
+		if (window_pos > 0)
+			set_window_pos(window_pos-1);
```
Comment (Noshyaar) [inline scene/gui/line_edit.cpp]: clang-format error

Comment (AlexHolly) [reply scene/gui/line_edit.cpp]: :( I was hoping copy and paste could handle it.
