### PR TITLE
Restore gltf embedded scenes due to problems with textures.

### LINKED ISSUE #72197: Error while importing GLTF file due to problem with texture
### Godot version

v4.0.beta16.official [518b9e580]

### System information

Windows 10 (10.0.19045 Build 19045) | Forward+ | Vulkan API 1.3.206 | AMD Radeon RX 6800 XT

### Issue description

When opening the attached GLTF file (with textures set to extract), it produces an error. Reimporting it with textures set to embedded does work, but the surfaces with that texture are invisible. In Beta 15 the GLTF worked fine.

The error with default import settings is:

```
  Task 'reimport' already exists.
  editor/import/resource_importer_texture.cpp:336 - Condition "f.is_null()" is true.
  Cannot open MD5 file 'res://.godot/imported/_Tree Fruits_Byv7pfwHRTnbXRYGkIeo5gBshRHIRnwOAMnvTtyJN5sy4iqIYLkBW95H9irFDgBlQ5gl2LIgsQ7AFV0EQ4BQqxif40CWPthzH2w3rtxAMA0QcgChcgDmAHRHwHIUIQcAAFC2yiHCIEipAAAAAElFTkSuQmCC.png-dfad032756448f4c0361cdaeb9bf7b9b.md5'.
  Unable to open file: res://.godot/imported/_Tree Fruits_Byv7pfwHRTnbXRYGkIeo5gBshRHIRnwOAMnvTtyJN5sy4iqIYLkBW95H9irFDgBlQ5gl2LIgsQ7AFV0EQ4BQqxif40CWPthzH2w3rtxAMA0QcgChcgDmAHRHwHIUIQcAAFC2yiHCIEipAAAAAElFTkSuQmCC.png-dfad032756448f4c0361cdaeb9bf7b9b.ctex.
  Failed loading resource: res://.godot/imported/_Tree Fruits_Byv7pfwHRTnbXRYGkIeo5gBshRHIRnwOAMnvTtyJN5sy4iqIYLkBW95H9irFDgBlQ5gl2LIgsQ7AFV0EQ4BQqxif40CWPthzH2w3rtxAMA0QcgChcgDmAHRHwHIUIQcAAFC2yiHCIEipAAAAAElFTkSuQmCC.png-dfad032756448f4c0361cdaeb9bf7b9b.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://_Tree Fruits_Byv7pfwHRTnbXRYGkIeo5gBshRHIRnwOAMnvTtyJN5sy4iqIYLkBW95H9irFDgBlQ5gl2LIgsQ7AFV0EQ4BQqxif40CWPthzH2w3rtxAMA0QcgChcgDmAHRHwHIUIQcAAFC2yiHCIEipAAAAAElFTkSuQmCC.png. Make sure resources have been imported by opening the project in the editor at least once.
  modules/gltf/gltf_document.cpp:3249 - glTF: Image index '1' couldn't be loaded with the name: Byv7pfwHRTnbXRYGkIeo5gBshRHIRnwOAMnvTtyJN5sy4iqIYLkBW95H9irFDgBlQ5gl2LIgsQ7AFV0EQ4BQqxif40CWPthzH2w3rtxAMA0QcgChcgDmAHRHwHIUIQcAAFC2yiHCIEipAAAAAElFTkSuQmCC. Skipping it.
  modules/gltf/gltf_document.cpp:3240 - Condition "err != OK" is true. Returning: err
  modules/gltf/gltf_document.cpp:7123 - Condition "err != OK" is true. Returning: ERR_PARSE_ERROR
  modules/gltf/gltf_document.cpp:6775 - Condition "err != OK" is true. Returning: err
  modules/gltf/gltf_document.cpp:7203 - Condition "err != OK" is true. Returning: err
  editor/editor_file_system.cpp:2004 - Error importing 'res://_Tree Fruits.gltf'.
  editor/progress_dialog.cpp:235 - Condition "!tasks.has(p_task)" is true.
  Task 'reimport' already exists.
  editor/import/resource_importer_texture.cpp:336 - Condition "f.is_null()" is true.
  Cannot open MD5 file 'res://.godot/imported/_Tree Fruits_Byv7pfwHRTnbXRYGkIeo5gBshRHIRnwOAMnvTtyJN5sy4iqIYLkBW95H9irFDgBlQ5gl2LIgsQ7AFV0EQ4BQqxif40CWPthzH2w3rtxAMA0QcgChcgDmAHRHwHIUIQcAAFC2yiHCIEipAAAAAElFTkSuQmCC.png-dfad032756448f4c0361cdaeb9bf7b9b.md5'.
  Unable to open file: res://.godot/imported/_Tree Fruits_Byv7pfwHRTnbXRYGkIeo5gBshRHIRnwOAMnvTtyJN5sy4iqIYLkBW95H9irFDgBlQ5gl2LIgsQ7AFV0EQ4BQqxif40CWPthzH2w3rtxAMA0QcgChcgDmAHRHwHIUIQcAAFC2yiHCIEipAAAAAElFTkSuQmCC.png-dfad032756448f4c0361cdaeb9bf7b9b.ctex.
  Failed loading resource: res://.godot/imported/_Tree Fruits_Byv7pfwHRTnbXRYGkIeo5gBshRHIRnwOAMnvTtyJN5sy4iqIYLkBW95H9irFDgBlQ5gl2LIgsQ7AFV0EQ4BQqxif40CWPthzH2w3rtxAMA0QcgChcgDmAHRHwHIUIQcAAFC2yiHCIEipAAAAAElFTkSuQmCC.png-dfad032756448f4c0361cdaeb9bf7b9b.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://_Tree Fruits_Byv7pfwHRTnbXRYGkIeo5gBshRHIRnwOAMnvTtyJN5sy4iqIYLkBW95H9irFDgBlQ5gl2LIgsQ7AFV0EQ4BQqxif40CWPthzH2w3rtxAMA0QcgChcgDmAHRHwHIUIQcAAFC2yiHCIEipAAAAAElFTkSuQmCC.png. Make sure resources have been imported by opening the project in the editor at least once.
  modules/gltf/gltf_document.cpp:3249 - glTF: Image index '1' couldn't be loaded with the name: Byv7pfwHRTnbXRYGkIeo5gBshRHIRnwOAMnvTtyJN5sy4iqIYLkBW95H9irFDgBlQ5gl2LIgsQ7AFV0EQ4BQqxif40CWPthzH2w3rtxAMA0QcgChcgDmAHRHwHIUIQcAAFC2yiHCIEipAAAAAElFTkSuQmCC. Skipping it.
  modules/gltf/gltf_document.cpp:3240 - Condition "err != OK" is true. Returning: err
  modules/gltf/gltf_document.cpp:7123 - Condition "err != OK" is true. Returning: ERR_PARSE_ERROR
  modules/gltf/gltf_document.cpp:6775 - Condition "err != OK" is true. Returning: err
  modules/gltf/gltf_document.cpp:7203 - Condition "err != OK" is true. Returning: err
  editor/editor_file_system.cpp:2004 - Error importing 'res://_Tree Fruits.gltf'.
  editor/editor_file_system.cpp:2228 - Condition "!importer.is_valid()" is true. Continuing.
  editor/editor_file_system.cpp:2228 - Condition "!importer.is_valid()" is true. Continuing.
  editor/editor_file_system.cpp:2228 - Condition "!importer.is_valid()" is true. Continuing.
  editor/editor_file_system.cpp:2228 - Condition "!importer.is_valid()" is true. Continuing.
  editor/progress_dialog.cpp:235 - Condition "!tasks.has(p_task)" is true.
```

It should be mentioned that this model was created with blockbench.

### Steps to reproduce

Import the attached GLTF file with default settings.

### Minimal reproduction project

[_Tree Fruits.zip](https://github.com/godotengine/godot/files/10522215/_Tree.Fruits.zip)

### PR DESCRIPTION
**Pull request by fire**
gltf: Avoid using base64 hash as an image filename

Fixes: https://github.com/godotengine/godot/issues/72197

How does this fix?

It ignores the base 64 string or the buffer. Consistently use the images.name property with deduplication, or else the image index. Does not use the material name because we don't know yet.

### CODE REVIEW

File: modules/gltf/gltf_document.cpp [hunk 1]
```diff
@@ -3096,7 +3096,7 @@ Error GLTFDocument::_parse_images(Ref<GLTFState> p_state, const String &p_base_p
 		if (d.has("uri")) {
 			// Handles the first two bullet points from the spec (embedded data, or external file).
 			String uri = d["uri"];
-			image_name = uri;
+			image_name = itos(i);
```
Comment (fire) [inline modules/gltf/gltf_document.cpp:3099]: Might need to keep image_name = uri here.

and 

move image_name = itos(i) under the data section.

Doing testing.

File: modules/gltf/gltf_document.cpp [hunk 2]
```diff
@@ -3096,7 +3096,7 @@ Error GLTFDocument::_parse_images(Ref<GLTFState> p_state, const String &p_base_p
 		if (d.has("uri")) {
 			// Handles the first two bullet points from the spec (embedded data, or external file).
 			String uri = d["uri"];
-			image_name = uri;
```
Comment (lyuma) [inline modules/gltf/gltf_document.cpp:3099]: we should try and use the d["name"] if it exists. otherwise, fallback to textures or material names
NOTE: we should check some files from a few different DCC to see how they handle this.

And then fallback to index only if no name

images->name exists in blender embedded exports.

**Review by lyuma — COMMENTED** [review]
I like this change because we should never be exposing the base64 data. However, I want to see if we can do a little better than always using texture index

File: modules/gltf/gltf_document.cpp (hunk 2 above)
Comment (lyuma) [reply modules/gltf/gltf_document.cpp:3099]: Updated. For now I'm only using image["name"]. using material name is rather tricky, especially if they use multiple texture maps which all need unique names assigned.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
