### PR TITLE
Fix editor preset names not being validated 

### LINKED ISSUE #112646: [UX] Export presets names aren't validated
### Tested versions

- Reproducible in: Godot 4.0.4 and later

### System information

Godot v4.6.dev (a4607b4a6) - macOS Tahoe (26.2.0) - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M3 Max (Apple9) - Apple M3 Max (16 threads) - 48.00 GiB memory

### Issue description

When adding a new export preset, if the default name already exists, it will add a counter to the name equivalent to the number of attempts it took.

> [!NOTE]
> Take note that these screenshots include "Async PCKs" content that is currently from a local branch of mine.

Image

But it is really easy to rename one of these "Web <N>" to "Web" without any issue nor error.

Image

Afterwards, when using a command like `godot --headless --export-debug "Web"`, it seems to take the first export preset in the list named "Web", so it may leave an export preset unexportable from the command line.

<figure>

Image

<figcaption markdown=1>

It's even possible to set the name as an empty string.

</figcaption>

</figure>

### Steps to reproduce

1. Open the export window.
2. Click on "Add"
3. Select the Web platform.
4. Repeat steps 2. and 3. at least once.
5. Select "Web <N>"
6. Change the current preset name to "Web"
7. Realize that the editor is OK with having two export presets that have the same name
8. Change the current preset name to ""
9. Realize that the editor is OK with having a blank export preset name

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by MiracleAig**
Fixed: https://github.com/godotengine/godot/issues/112646

Sorry, im making this PR again because I merged coded that altered my fix and I didn't check if that code actually worked, (it didn't) so this PR addresses that.

When creating build profiles usally you were able to have profiles with blank names, and multiple profiles with the same name which made it difficult to export the project when using a CLI, so this fix adresses those issues by checking if the build profile name is left blank or matches the name of other build profiles. Then it resets the name and logs an error to the console that the preset name is invalid for any of those reasons.

https://github.com/user-attachments/assets/f040540e-d386-40bb-a0e0-b22adff1666d

### CODE REVIEW

**Comment by AThousandShips** [comment]
You used a merge commit to update your branch, please use rebase in the future instead, see [here](https://contributing.godotengine.org/en/latest/organization/pull_requests/creating_pull_requests.html#the-interactive-rebase) (you will need to squash your commits when the PR has been approved and before it can be merged)

File: editor/export/editor_export.h [hunk 1]
```diff
@@ -87,7 +87,9 @@ class EditorExport : public Node {
 
 	void load_config();
 	void update_export_presets();
+	int get_export_platform_index_by_name(const String &p_name);
```
Comment (AThousandShips) [inline editor/export/editor_export.h]: Why readding this? It's already present

File: editor/export/editor_export.cpp [hunk 2]
```diff
@@ -147,15 +147,31 @@ int EditorExport::get_export_platform_count() const {
 }
 
 int EditorExport::get_export_platform_index_by_name(const String &p_name) {
-	for (int j = 0; j < get_export_platform_count(); j++) {
-		Ref<EditorExportPlatform> plat = get_export_platform(j);
-		if (!plat.is_null() && plat->get_name().nocasecmp_to(p_name) == 0) {
-			return j;
+	for (int i = 0; i < get_export_platform_count(); i++) {
+		Ref<EditorExportPlatform> platform = get_export_platform(i);
+		if (platform.is_valid() && platform->get_name() == p_name) {
```
Comment (AThousandShips) [inline editor/export/editor_export.cpp]: Can you please explain this change? It makes the check not consider duplicates just by casing

File: editor/export/editor_export.h (hunk 1 above)
Comment (MiracleAig) [reply editor/export/editor_export.h]: Whenever the CI checks ran they would fail citing that the `get_export_platform_index_by_name()` does not exist so I went in and added it back, but apparently its still there so I need to remove it.

File: editor/export/editor_export.cpp (hunk 2 above)
Comment (MiracleAig) [reply editor/export/editor_export.cpp]: Yeeah your right. Using `==` would treat platform names as different if the casing varied.
I updated the comparison to use `casecmp_to()` so the check is case-insensitive, matching how platform names are handled elsewhere in the editor. However, pertaining to the other issue I still couldn't find any duplicate symbols of `get_export_platform_index_by_name()` even after running `git grep -n "get_export_platform_index_by_name"
`

Comment (AThousandShips) [reply editor/export/editor_export.cpp]: That's because your branch is out of date with `master`, you need to rebase your branch, see [here](https://contributing.godotengine.org/en/latest/organization/pull_requests/creating_pull_requests.html#the-interactive-rebase) 

Your branch is out of date and doesn't include the addition of this method

Again please rebase instead of using merge commits

File: editor/export/editor_export.cpp [hunk 3]
```diff
@@ -147,15 +147,31 @@ int EditorExport::get_export_platform_count() const {
 }
 
 int EditorExport::get_export_platform_index_by_name(const String &p_name) {
-	for (int j = 0; j < get_export_platform_count(); j++) {
-		Ref<EditorExportPlatform> plat = get_export_platform(j);
-		if (!plat.is_null() && plat->get_name().nocasecmp_to(p_name) == 0) {
-			return j;
+	for (int i = 0; i < get_export_platform_count(); i++) {
+		Ref<EditorExportPlatform> platform = get_export_platform(i);
+		if (platform.is_valid() && platform->get_name().casecmp_to(p_name) == 0) {
```
Comment (AThousandShips) [inline editor/export/editor_export.cpp]: All of these changes should just be reverted, they're not relevant to this PR (also it changes `nocasecmp_to` to `casecmp_to`

Comment (MiracleAig) [reply editor/export/editor_export.cpp]: I fixed that issue and rebased like you said, but I think I did it wrong because there's a lot of new commits.

File: main/main.cpp [hunk 4]
```diff
@@ -3920,6 +3920,7 @@ int Main::start() {
 			return EXIT_FAILURE;
 #endif // defined(OVERRIDE_PATH_ENABLED)
 		} else if (E->get().length() && E->get()[0] != '-' && positional_arg.is_empty() && game_path.is_empty()) {
+#if defined(OVERRIDE_PATH_ENABLED)
```
Comment (AThousandShips) [inline main/main.cpp]: Unrelated from the broken rebase

**Comment by AThousandShips** [comment]
You have included unrelated commits because you used a merge commit instead of a rebase, you will need to remove this by using `git reset --hard HEAD~` and then pushing with `git push -f`, also please rebase your branch instead of using merge commits

File: editor/export/editor_export.h [hunk 5]
```diff
@@ -87,7 +86,9 @@ class EditorExport : public Node {
...
```
Comment (AThousandShips) [inline editor/export/editor_export.h]: Shouldn't be moved as part of this PR

Comment (MiracleAig) [reply editor/export/editor_export.h]: Sorry, I am a little confused by what you mean here. Do you want me to move the line to where it was previously?

Comment (AThousandShips) [reply editor/export/editor_export.h]: Yes, this method isn't part of this PR so it shouldn't be moved as part of this, remnant of your previous code duplicating it

Comment (MiracleAig) [reply editor/export/editor_export.h]: Okay, thanks for the clarification.

**Comment by KoBeWi** [comment]
The errors should be shown via editor toaster. You can use either EditorToaster directly or `ERR_PRINT_ED`.

File: editor/export/editor_export.cpp [hunk 6]
```diff
@@ -156,6 +156,22 @@ int EditorExport::get_export_platform_index_by_name(const String &p_name) {
 	return -1;
 }
 
+bool EditorExport::has_preset_with_name(const String &p_name, int p_exclude_index, int *r_found_index) const {
```
Comment (KoBeWi) [inline editor/export/editor_export.cpp]: The last argument seems not used anywhere.

File: editor/export/editor_export.cpp [hunk 7]
```diff
@@ -156,6 +156,22 @@ int EditorExport::get_export_platform_index_by_name(const String &p_name) {
...
+	for (int i = 0; i < export_presets.size(); i++) {
+		if (i == p_exclude_index) {
+			continue;
+		}
+		if (export_presets[i]->get_name() == p_name) {
+			if (r_found_index) {
```
Comment (MiracleAig) [inline editor/export/editor_export.cpp]: I'm using `int *r_found_index` here, no?

Comment (KoBeWi) [reply editor/export/editor_export.cpp]: You are only assigning it, but the value is not used anywhere. And the code is never executed, because the pointer is always null.

Comment (MiracleAig) [reply editor/export/editor_export.cpp]: Oh, I see. Thanks for pointing that out.

**Review by KoBeWi — APPROVED** [review]

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Could you squash your commits? See our [pull request guidelines](https://contributing.godotengine.org/en/latest/organization/pull_requests/creating_pull_requests.html#the-interactive-rebase) for more information

**Comment by MiracleAig** [comment]
@Repiteo Done.

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
