### PR TITLE
Fix memory leak with Gradient in Node3DEditorViewport

### LINKED ISSUE #44896: Memory leak of frame_time_gradient
**Godot version:**
4.0.dev.custom_build. 950dedbb6
Regression from https://github.com/godotengine/godot/pull/44709

CC @Calinou 

**Issue description:**
~`frame_time_gradient` is not added to the scene, so memory leak exists~

```
Indirect leak of 320 byte(s) in 4 object(s) allocated from:
    #0 0x7f72bdba2517 in malloc (/lib/x86_64-linux-gnu/libasan.so.6+0xb0517)
    #1 0x125815ef in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:76
    #2 0xce3864d in CowData<Gradient::Point>::resize(int) core/templates/cowdata.h:278
    #3 0xce372a6 in Vector<Gradient::Point>::resize(int) core/templates/vector.h:88
    #4 0xf125c1a in Gradient::Gradient() scene/resources/gradient.cpp:37
    #5 0xa4b9574 in Node3DEditorViewport::Node3DEditorViewport(Node3DEditor*, EditorNode*, int) editor/plugins/node_3d_editor_plugin.cpp:4089
    #6 0xa59218d in Node3DEditor::Node3DEditor(EditorNode*) editor/plugins/node_3d_editor_plugin.cpp:6461
    #7 0xa5ac698 in Node3DEditorPlugin::Node3DEditorPlugin(EditorNode*) editor/plugins/node_3d_editor_plugin.cpp:6725
    #8 0x87fb962 in EditorNode::EditorNode() editor/editor_node.cpp:6613
    #9 0x1f5af83 in Main::start() main/main.cpp:2139
    #10 0x1e0edf4 in main platform/linuxbsd/godot_linuxbsd.cpp:57
    #11 0x7f72bc96f0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

Indirect leak of 192 byte(s) in 4 object(s) allocated from:
    #0 0x7f72bdba2517 in malloc (/lib/x86_64-linux-gnu/libasan.so.6+0xb0517)
    #1 0x125815ef in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:76
    #2 0x125814ee in operator new(unsigned long, char const*) core/os/memory.cpp:41
    #3 0x12e4b915 in Dictionary::Dictionary() core/variant/dictionary.cpp:267
    #4 0x1367a45f in Object::Object(bool) core/object/object.cpp:1769
    #5 0x136b3737 in Reference::Reference() core/object/reference.cpp:100
    #6 0x12acf094 in Resource::Resource() core/io/resource.cpp:401
    #7 0xf1259e4 in Gradient::Gradient() scene/resources/gradient.cpp:35
    #8 0xa4b9574 in Node3DEditorViewport::Node3DEditorViewport(Node3DEditor*, EditorNode*, int) editor/plugins/node_3d_editor_plugin.cpp:4089
    #9 0xa59218d in Node3DEditor::Node3DEditor(EditorNode*) editor/plugins/node_3d_editor_plugin.cpp:6461
    #10 0xa5ac698 in Node3DEditorPlugin::Node3DEditorPlugin(EditorNode*) editor/plugins/node_3d_editor_plugin.cpp:6725
    #11 0x87fb962 in EditorNode::EditorNode() editor/editor_node.cpp:6613
    #12 0x1f5af83 in Main::start() main/main.cpp:2139
    #13 0x1e0edf4 in main platform/linuxbsd/godot_linuxbsd.cpp:57
    #14 0x7f72bc96f0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
```

https://github.com/godotengine/godot/blob/2abe996414b8b551e69e29461de3ff1bcaf5a28f/editor/plugins/node_3d_editor_plugin.cpp#L4089-L4091

**Steps to reproduce:**
1. Run with address sanitizer empty editor and close it

### PR DESCRIPTION
**Pull request by qarmin**
Fixes #44896

### CODE REVIEW

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -4141,6 +4141,9 @@ Node3DEditorViewport::Node3DEditorViewport(Node3DEditor *p_spatial_editor, Edito
 	EditorSettings::get_singleton()->connect("settings_changed", callable_mp(this, &Node3DEditorViewport::update_transform_gizmo_view));
 }
 
+Node3DEditorViewport::~Node3DEditorViewport() {
+	memdelete(frame_time_gradient);
+}
 //////////////////////////////////////////////////////////////
```
Comment (akien-mga) [inline editor/plugins/node_3d_editor_plugin.cpp:4147]: Keep a separation line between those two.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
