### PR TITLE
Center shape according to logic Bullet applies

### LINKED ISSUE #27998: Collisions against HeightMapShape do not work
Version: 3.2-dev

I could not make HeightMapShape work against CapsuleShape (StaticBody vs KinematicBody).
Have anybody tested this?

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Bullet will center the heightmap data you supply to it. Bit counter intuitive but so be it. 
This PR adjusts our debug shape to match and adds a remark in the help pages about this behaviour.

This could be improved by somehow offsetting the shape in bullet, giving it a different transform, but that is a larger structural change. 

Fixes #27998

### CODE REVIEW

File: scene/resources/height_map_shape.cpp [hunk 1]
```diff
@@ -34,35 +34,49 @@
...
+			if (min > r[i]) min = r[i];
+			if (max < r[i]) max = r[i];
+		};
+		float center = min + ((max - min) * 0.5);
 
-			if (w != map_width - 1) {
-				points.push_back(height);
-				points.push_back(Vector3(height.x + 1.0, r[offset], height.z));
-			}
+		// no set our points
```
Comment (Zylann) [inline scene/resources/height_map_shape.cpp]: *now

File: doc/classes/HeightMapShape.xml [hunk 2]
```diff
@@ -4,7 +4,7 @@
 		Height map shape for 3D physics (bullet only)
 	</brief_description>
 	<description>
-		Height map shape resource, which can be added to a [PhysicsBody] or [Area].
+		Height map shape resource, which can be added to a [PhysicsBody] or [Area]. Note that bullet will always center the collision shape. If you minimum height is 0, and you maximum height is 10, bullet will adjust your collision shape down so the minimum height is -5 and the maximum height is 5.
```
Comment (Zylann) [inline doc/classes/HeightMapShape.xml]: I know heightmap isn't supported by Godot Physics, but perhaps we could indicate this is a Bullet-only behavior?

File: scene/resources/height_map_shape.cpp [hunk 3]
```diff
@@ -34,35 +34,49 @@
...
+					points.push_back(height);
+					points.push_back(Vector3(height.x + 1.0, r[offset] - center, height.z));
+				}
 
-			if (d != map_depth - 1) {
-				points.push_back(height);
-				points.push_back(Vector3(height.x, r[offset + map_width - 1], height.z + 1.0));
+				if (d != map_depth - 1) {
+					points.push_back(height);
+					points.push_back(Vector3(height.x, r[offset + map_width - 1] - center, height.z + 1.0));
```
Comment (Zylann) [inline scene/resources/height_map_shape.cpp]: Note for the future, this could be optimized to not use push_back at all since we surely know in advance how many vertices the grid will have (and it can be big), so we could resize a PoolVector directly to the proper size and set its values

File: doc/classes/HeightMapShape.xml (hunk 2 above)
Comment (BastiaanOlij) [reply doc/classes/HeightMapShape.xml]: It's in the brief description:
Height map shape for 3D physics **(bullet only)**

File: scene/resources/height_map_shape.cpp (hunk 3 above)
Comment (BastiaanOlij) [reply scene/resources/height_map_shape.cpp]: It's not using a poolvector but a vector, does it have the same syntax? I can surely change it

File: scene/resources/height_map_shape.cpp (hunk 1 above)
Comment (BastiaanOlij) [reply scene/resources/height_map_shape.cpp]: oops

File: doc/classes/HeightMapShape.xml (hunk 2 above)
Comment (akien-mga) [reply doc/classes/HeightMapShape.xml]: Could you capitalize "Bullet", to make it clear it's the library and not a bullet object/scene?

Comment (akien-mga) [reply doc/classes/HeightMapShape.xml]: Also, trailing space on this line :)

File: scene/resources/height_map_shape.cpp (hunk 3 above)
Comment (Zylann) [reply scene/resources/height_map_shape.cpp]: Oh right... nevermind them. The API for collision shape lines isn't practical to get around this.

Comment (BastiaanOlij) [reply scene/resources/height_map_shape.cpp]: Done

File: doc/classes/HeightMapShape.xml (hunk 2 above)
Comment (BastiaanOlij) [reply doc/classes/HeightMapShape.xml]: All good :)

**Review by akien-mga — APPROVED** [review]

**Comment by BastiaanOlij** [comment]
I've changed this back to WIP, see #27998 for the discussion on improving this logic even further.

**Comment by BastiaanOlij** [comment]
Ok, I've added my changes based on the discussion in #27998. 

It works really well however it has one fundamental flaw. Doing so implements a fix specific to Bullets behavior into the physics system. I believe it's the wrong place however fixing this in the bullet module feels a lot more difficult to handle (I could be wrong).

So I am leaving this in WIP for further discussion.

**Comment by BastiaanOlij** [comment]
Ok, I managed to make the adjustment in the bullet glue code. Any suggestions on making it prettier are welcome but it works like a charm.

Someone should really make an editor gizmo for this. I have no idea how to do this (yet).

**Comment by AndreaCatania** [comment]
I looks ok to me, but I didn't try it.

The only two things are:
- are you sure that when you change the height map data you reload the position of the shape in the btCollisionObject?
- I think that call the function `get_transform` instead of `get_adjusted_transform` is better

however nice work

**Comment by BastiaanOlij** [comment]
@AndreaCatania I need to reload the position because a change in the heightmap data requires us to adjust the transform Bullet uses.

If the lowest height in my heightmap is -100, and the highest is 100, then bullet will position the collision shape as we expect, nicely centered on our transform.

If I change the lowest height in my heightmap to -50 and keep the highest as 100, I do not expect my heightmap to move, but bullet will recenter it and suddenly my heightmap behaves asif the lowest value is -75 and the height is 75.

What I do in this case is adjust the transform where we've placed the collision shape by moving it upwards by 25 units.

Hence the name, get_adjusted_transform

**Comment by AndreaCatania** [comment]
Yep sure, but for the other shapes doesn't make sense, for this reason I think that would be more appropriate `get_transform`.

While review the code the question that I asked to myself was: Why the shape need an adjusted transform with this change?

Then I opened the function to answer it, and I got it. But since this is true only for one case I think that is more appropriate name it `get_transform`.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
> Then I opened the function to answer it, and I got it. But since this is true only for one case I think that is more appropriate name it get_transform.

Woops, just merged while you were posting this. If you agree on renaming it, it can be done in another commit.

**Comment by Zylann** [comment]
I realize just now that this breaks compatibility in my plugin. Now I have to add an `if` to check if it's Godot 3.2 or later to change the transform differently.

**Comment by akien-mga** [comment]
As I understand it that's an expected compatibility breakage, but it would be good to have a confirmation from @BastiaanOlij or @AndreaCatania. Should also be mentioned in the changelog (@Calinou).

**Comment by BastiaanOlij** [comment]
@akien-mga that is my position indeed. Before we introduced the collision shape the heightmap could only be used directly on the physics engine so its unlikely a lot of people used it extensive enough and I think the previous behavior is just plain confusing. With the collision shape added in 3.2 and this behavior changed in 3.2 I think we can get away with the breakage. Probably @Zylann plugin is the only thing really effected by this.

I understand why Bullet does what it does, but it would have been easy to solve upstream, instead they chose to have the collision shape centered and thus move which to the end users is unintuitive and hard to predict.
For us to properly deal with this so the heights you set in the heightmap are the actually heights at which the collision shape is positioned instead of it moving around on you as your minimum and maximum height values change, seems legit to me :)
The way we solved it means that Bullet is still happy as the collision shape is still centered in its bounding box, but we reposition it so the end user isn't tripped up by this and its totally transparent.
