### PR TITLE
Fix basisu texture mipmaps

### LINKED ISSUE #72237: Textures using Basis Universal compression no longer generate mipmaps
### Godot version

v4.0.beta.custom_build [a43db5afa]

### System information

Windows 10, Forward+, NVidia RTX 3070 (516.94)

### Issue description

After recompiling the engine, a grid texture using Basis Universal compression in a test project became extremely noisy, having lost its mipmaps.

Opening a Basis Universal texture in the inspector shows that there are no mips, even if Generate Mipmaps is enabled:
image
editor_screenshot_2023-01-28T184045

### Steps to reproduce

1. Import a texture to a project (The noisier the better).
2. Open texture in the inspector, enable mipmaps, change the compression mode to Basis Universal, and re-import.

### Minimal reproduction project

[Basis Universal MipMapping.zip](https://github.com/godotengine/godot/files/10526818/Basis.Universal.MipMapping.zip)

### PR DESCRIPTION
**Pull request by fire**
Previously basisu was storing mip maps as an array of basisu in the internal format for Texture. The new work makes sense and it generates smaller files with one image.

This pull request fixes the basisu decompression and keeps the approach of 1 image. If we need to change the format in 4.x, we can still support the old format with some limitations too.

Basisu from gltfpack can only output with mipmaps in one image.

The single image will not work for StreamedTexture. We should support both approaches for CompressedTexture we use one, and for StreamedTexture we use another.

Supersedes: https://github.com/godotengine/godot/pull/73857
Fixes: https://github.com/godotengine/godot/issues/72237

### CODE REVIEW

File: modules/basis_universal/register_types.cpp [hunk 1]
```diff
@@ -228,35 +234,29 @@ static Ref<Image> basis_universal_unpacker_ptr(const uint8_t *p_data, int p_size
...
+	uint8_t *dst = w;
+	for (int i = 0; i < gpudata.size(); i++) {
+		dst[i] = 0x00;
+	}
+	uint32_t mip_count = Image::get_image_required_mipmaps(info.m_orig_width, info.m_orig_height, imgfmt);
+	for (uint32_t level_i = 0; level_i < mip_count; level_i++) {
+		basist::basisu_image_level_info level;
+		tr.get_image_level_info(ptr, size, level, 0, level_i);
+		int ofs = Image::get_image_mipmap_offset(info.m_width, info.m_height, imgfmt, level_i);
+		bool ret = tr.transcode_image_level(ptr, size, 0, level_i, dst + ofs, level.m_total_blocks, format);
```
Comment (lyuma) [inline modules/basis_universal/register_types.cpp:254]: Might be a good idea to add some checks that `Image::get_image_mipmap_size` matches the decoded size of this basisu level (something from `info`, `struct basisu_image_level_info` defined in `thirdparty/basis_universal/transcoder/basisu_transcoder.h` )

Note that at some mipmap levels, width and height might not be a multiple of 4, but the data will still be a multiple of blocks.

You could imagine potentially decoding a ktx file made with different mipmap levels, since (I believe) there is no requirement that all mipmap levels exist, and a malicious or incompatible ktx file might crash godot in such a case.

**Review by lyuma — APPROVED** [review]
Looks pretty reasonable to me.

I think this would be safe for 4.0. I haven't tested this yet, but in terms of how the code is written, it's not breaking compatibility, and it is touching code that is currently not working correctly (so it can't make it worse). I'll try and test it when I have a chance.

**Comment by akien-mga** [comment]
As a side note for future work (post 4.0): `register_types.cpp` should only be used for some general registration code. Actual implementation of compression/decompression should be moved to `image_compress_basisu.cpp` or similar.

**Comment by fire** [comment]
Regarding the issue rename.

Godot Engine calls this type of import an image import, similar to PNG and WEBP. The code in CompressedTexture2D is unmodified, but is related.

**Review by akien-mga — APPROVED** [review]
Approved for 4.0 as this only touches basisu images and they're apparently not usable right now.
