### PR TITLE
Fix recursive resource local to scene (array/dictionary properties on resources)

### LINKED ISSUE #71406: Materials Not Honoring Local to Scene
### Godot version

4.0 Beta 10

### System information

Kubuntu 18.04, Forward+, NVIDIA GeForce GTX 1660

### Issue description

I have a model created via Blender, exported from Blender as a GLTF file, and imported into Godot as a local copy.

There is a set of materials in the mesh, with each material intended to display a different texture, and each material in the set is flagged as "Local to Scene".

I create multiple instances of this mesh, and set each material set to a different set of textures. Setting the individual textures within the mesh works fine, but each instance of the mesh displays the same set of textures. This shouldn't happen with each material set as "Local to Scene". Each instance should display a different set of textures.

### Steps to reproduce

I've added an MRP to demonstrate the issue. Each flattened cube has two materials, which each material flagged as "Local to Scene". Each instance of the cube shows the exact same textures, though all instances are given unique textures. What is displayed is the set of textures assigned to the last cube instance.

### Minimal reproduction project

[materials.zip](https://github.com/godotengine/godot/files/10418153/materials.zip)

### LINKED ISSUE #85614: Local to Scene doesn't work when inside exported arrays
### Godot version

v4.2.stable.official [46dc27791]

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1050 Ti with Max-Q Design (NVIDIA; 31.0.15.4617) - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 Threads)

### Issue description

If I create a custom resource that has some runtime-mutable state (that is, the game modifies the resource during gameplay), and then store that resource in an Array used by multiple subscenes in my main scene, the mutable state ends up shared, _even if_ Local to Scene is checked. If the resource is top-level instead of inside an Array, it works as expected (unshared).

Unexpected sharing of state between instances:

https://github.com/godotengine/godot/assets/10625/2252bac5-8926-4c42-901f-c04769f09e97

---

What I'm looking for:

1. Is this a bug, or is this by design?
2. If it's by design...should it be by design? I think we know this area's a bit confusing already https://github.com/godotengine/godot-proposals/issues/1848
3. If it's not a bug and it's definitely by design, can we document this behavior somewhere? [Local to Scene](https://docs.godotengine.org/en/stable/tutorials/scripting/resources.html) isn't even mentioned in the Resources tutorial, but some kind of best practice callout should probably be added here. Either "be careful when using Resources in Arrays" or "avoid mutable state inside Resources"?

### Steps to reproduce

1. Create a custom resource. It should have at least one field modified by the game at runtime, e.g. a checkbox to indicate whether the animation it represents has completed.
2. Store this resource in an Array on a scene.
3. Write a script and attach to the scene that uses the resource.
4. Instantiate this scene multiple times and add it to the main scene.
5. Observe that the mutated state is shared across all instances.

For the attached project, just run the main scene, then click on the first image, then the second image.

### Minimal reproduction project

[LocalToScene_GD.zip](https://github.com/godotengine/godot/files/13528251/LocalToScene_GD.zip)

I've attached a simple project where there's a stateful animation resource that's in an array shared by two instances. Because I've chosen `Resource > Local to Scene` for the AnimNames resource (and tried `Make Unique` on that resource for good measure), I expect the AnimNames resource to be fully independent between the two images. But it's actually shared.

What I expect the behavior to be when clicking on the images:

https://github.com/godotengine/godot/assets/10625/0e69c0d3-5061-425e-a674-2da4e3daa8ca

What actually happens when clicking on different instances. The jerking behavior is because it's unexpectedly playing the wrong animation.

https://github.com/godotengine/godot/assets/10625/2252bac5-8926-4c42-901f-c04769f09e97

### PR DESCRIPTION
**Pull request by RedMser**
Related to #71243
Fixes #71406
Fixes #85614

Any resource that contains arrays or dictionaries with local to scene resources will now be duplicated and configured correctly. This also includes built-in nodes, such as when marking a mesh's surface materials as local to scene.

A side effect of this change is that any array and dictionary property is now duplicated for local-to-scene instances.

What **isn't handled** in this PR is the case where a **scene's node** has an exported array/dictionary property containing local to scene resources. That code has a lot more special cases that I don't fully understand yet, but the solution would look largely similar.

---

NOTE: Using resources as dictionary keys does not work with the inspector (they get saved as `null` into the scene file), so this code branch was not tested.

### CODE REVIEW

**Comment by RedMser** [comment]
Seems to assign the wrong local scene in the https://github.com/godotengine/godot/issues/71243 MRP.

<details>
<summary>Output Log</summary>

```
pre-modified first ---------
simple:
true	1	LocalToSceneTests1:<Node#26474447287>
array:
true	2	<Object#null>
true	3	<Object#null>
dict:
true	4	<Object#null>
sub:
true	5	LocalToSceneTests1:<Node#26474447287>
sub array:
true	6	LocalToSceneTests2:<Node#26575110566>
check first ---------
simple:
true	1	LocalToSceneTests1:<Node#26474447287>
array:
true	4	<Object#null>
true	6	<Object#null>
dict:
true	8	<Object#null>
sub:
true	5	LocalToSceneTests1:<Node#26474447287>
sub array:
true	12	LocalToSceneTests2:<Node#26575110566>
check second ---------
simple:
true	2	LocalToSceneTests2:<Node#26575110566>
array:
true	4	<Object#null>
true	6	<Object#null>
dict:
true	8	<Object#null>
sub:
true	10	LocalToSceneTests2:<Node#26575110566>
sub array:
true	12	LocalToSceneTests2:<Node#26575110566>
```
</details>

**Comment by Luzzotica** [comment]
I would like to push this if possible.

I'm building a game that relies heavily on resources to decouple systems and I have a lot of resources in arrays and dictionaries.

With this merged in I can at least create a workaround by only having a Local to Scene resource hold my arrays of resources. Not 100% optimal, but it would let me do what I want to do.

Also a little annoying to debug this issue when you first discover the Local to Scene checkbox.

**Comment by KoBeWi** [comment]
> Fixes the MRP in https://github.com/godotengine/godot/issues/71406.

Tested, it doesn't. The textures are still all the same.
Maybe something changed since then; there were a couple of PRs touching local to scene.

File: core/io/resource.cpp [hunk 1]
```diff
@@ -233,14 +341,15 @@ void Resource::configure_for_local_scene(Node *p_for_scene, HashMap<Ref<Resource
...
-		if (p.get_type() == Variant::OBJECT) {
-			Ref<Resource> sr = p;
-			if (sr.is_valid()) {
-				if (sr->is_local_to_scene()) {
-					if (!remap_cache.has(sr)) {
-						sr->configure_for_local_scene(p_for_scene, remap_cache);
-						remap_cache[sr] = sr;
-					}
+
+		HashSet<Ref<Resource>> resources_found;
```
Comment (KoBeWi) [inline core/io/resource.cpp:345]:
```suggestion
		HashSet<Ref<Resource>> sub_resources;
```

File: core/io/resource.cpp [hunk 2]
```diff
@@ -222,6 +291,45 @@ Ref<Resource> Resource::duplicate_for_local_scene(Node *p_for_scene, HashMap<Ref
 	return r;
 }
 
+static void _find_sub_resources(const Variant &v, HashSet<Ref<Resource>> &resources_found) {
+	switch (v.get_type()) {
+		case Variant::ARRAY: {
+			Array a = v;
+			for (int i = 0; i < a.size(); i++) {
+				Variant v2 = a[i];
+				if (v2.get_type() == Variant::ARRAY || v2.get_type() == Variant::DICTIONARY || v2.get_type() == Variant::OBJECT) {
```
Comment (KoBeWi) [inline core/io/resource.cpp:300]: This check is already done by the `switch` in `_find_sub_resources`, so it's not needed here.

File: core/io/resource.cpp [hunk 3]
```diff
@@ -222,6 +291,45 @@ Ref<Resource> Resource::duplicate_for_local_scene(Node *p_for_scene, HashMap<Ref
 	return r;
 }
 
+static void _find_sub_resources(const Variant &v, HashSet<Ref<Resource>> &resources_found) {
```
Comment (KoBeWi) [inline core/io/resource.cpp:294]: There is not reason to make this static.

File: core/io/resource.cpp [hunk 4]
```diff
@@ -200,7 +266,10 @@ Ref<Resource> Resource::duplicate_for_local_scene(Node *p_for_scene, HashMap<Ref
 		if (!(E.usage & PROPERTY_USAGE_STORAGE)) {
 			continue;
 		}
-		Variant p = get(E.name);
+		Variant p = get(E.name).duplicate(true);
+
+		_dupe_sub_resources(p, p_for_scene, remap_cache);
```
Comment (KoBeWi) [inline core/io/resource.cpp:271]: You can move the code below to `_dupe_sub_resources()`.

File: core/io/resource.cpp [hunk 5]
```diff
@@ -187,6 +187,72 @@ void Resource::reload_from_file() {
...
+			}
+		} break;
+		case Variant::DICTIONARY: {
+			Dictionary d = v;
+			List<Variant> keys;
+			d.get_key_list(&keys);
+			for (const Variant &k : keys) {
+				if (k.get_type() == Variant::ARRAY || k.get_type() == Variant::DICTIONARY) {
+					_dupe_sub_resources(k, p_for_scene, remap_cache);
+				} else if (k.get_type() == Variant::OBJECT) {
```
Comment (KoBeWi) [inline core/io/resource.cpp:219]: This can be another `case,` like in `_find_sub_resources()`, no?

File: core/io/resource.cpp (hunk 4 above)
Comment (RedMser) [reply core/io/resource.cpp:271]: Good point! I'm not deep into C++ so I thought doing `p = ...` wouldn't work from inside a function.
But references seem to allow this :D

File: core/io/resource.cpp (hunk 5 above)
Comment (RedMser) [reply core/io/resource.cpp:219]: You're right, for arrays and for sub-resources this can be extracted.
Replacing a dictionary key however needs different logic, due to the `.erase()` call.

**Comment by RedMser** [comment]
Applied review feedback, which cleaned up the code by a lot! :D
Also tested both issue's MRPs again and they behave as expected.

**Comment by KoBeWi** [comment]
Seems like it fixes #71243 too, not sure why you didn't link it.

**Comment by RedMser** [comment]
> Seems like it fixes #71243 too, not sure why you didn't link it.

It doesn't fix the case where an array or a dictionary with sub-resources is exported directly on a Node (as opposed to being a property on a Resource).

To fix it, we would need changes in the [PackedScene loading code](https://github.com/godotengine/godot/blob/bd42d337/scene/resources/packed_scene.cpp#L326), which looks scary to me since it also needs to handle scene inheritance among other things.

File: core/io/resource.cpp [hunk 6]
```diff
@@ -200,6 +200,57 @@ void Resource::reload_from_file() {
 	copy_from(s);
 }
 
+void _dupe_sub_resources(Variant &v, Node *p_for_scene, HashMap<Ref<Resource>, Ref<Resource>> &remap_cache) {
```
Comment (KoBeWi) [inline core/io/resource.cpp:203]:
```suggestion
void _dupe_sub_resources(Variant &r_variant, Node *p_for_scene, HashMap<Ref<Resource>, Ref<Resource>> &p_remap_cache) {
```
Also you should make it private method of Resource. We don't use global functions often, especially when there is no need.

Comment (KoBeWi) [reply core/io/resource.cpp:203]: So this is what https://github.com/godotengine/godot/pull/71578#discussion_r1333500876 was for? 🙃

It's better to move it to a method.

Comment (AThousandShips) [reply core/io/resource.cpp:203]: Yep, it makes sure the name isn't accessible outside this file, causes clashes otherwise

Comment (RedMser) [reply core/io/resource.cpp]: Made them private methods. Also I believe it should be `r_remap_cache` (and further down `r_resources_found`) since you must pass the HashMap and it gets modified by the method?

File: core/io/resource.h [hunk 7]
```diff
@@ -74,6 +74,9 @@ class Resource : public RefCounted {
 
 	SelfList<Resource> remapped_list;
 
+	void _dupe_sub_resources(Variant &r_variant, Node *p_for_scene, HashMap<Ref<Resource>, Ref<Resource>> &r_remap_cache);
+	void _find_sub_resources(const Variant &r_variant, HashSet<Ref<Resource>> &r_resources_found);
```
Comment (KoBeWi) [inline core/io/resource.h:78]: `r_` stands for parameters passed as pointer/reference that get modified inside the function (like the variant you are replacing). For other parameters you should use `p_` prefix.

Comment (AThousandShips) [reply core/io/resource.h:78]: So it should be `p_variant` in the second one, as it's not mutable

Comment (KoBeWi) [reply core/io/resource.h:78]: Also `p_hashmap`. The contents are changed, the HashMap itself is the same.

**Review by KoBeWi — APPROVED** [review]
It fixes the issue and seems to work correctly. Not sure how to test for potential regressions, probably still needs checking from core team to spot if something is obviously wrong.

You should squash the commits into 1.

**Comment by akien-mga** [comment]
Should be good to merge now, but could be worth a rebase to make sure everything still builds fine.

**Comment by akien-mga** [comment]
Thanks!
