### PR TITLE
Fix checking the visibility condition of selected file in the Godot editor's dock

### LINKED ISSUE #80937: double clicking to preview a resource scrolls the filesystem view when in split mode
### Godot version

4.1.1

### System information

linux

### Issue description

[simplescreenrecorder-2023-08-23_18.31.23.webm](https://github.com/godotengine/godot/assets/71937306/0b9a3971-a793-41a5-874c-e5f98bbc98d4)

In this clip I'm double-clicking textures to preview them and as you can see the file view scrolls to put the clicked file at the bottom of the panel.

The behavior should be: scroll to have the clicked item fully in view *only* if said item was partially out of the view to begin with.

### Steps to reproduce

1. filesystem in split mode (thumbnail grid or item list, doesn't matter).
2. have enough resources to scroll
3. scroll down so the bug can occur (since it will auto scroll *up*)
4. double click on a texture to view it in the inspector

### Minimal reproduction project

[filesystem_view_auto_scroll.zip](https://github.com/godotengine/godot/files/12421448/filesystem_view_auto_scroll.zip)

### PR DESCRIPTION
**Pull request by Vilcrow**
Fixes #80937.

### CODE REVIEW

**Review by KoBeWi — DISMISSED** [review]

**Comment by KoBeWi** [comment]
The line was added in #28770. Removing it reintroduces #26041
Instead of outright removing it, add a check if the path is directory.

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -1160,9 +1164,7 @@ void FileSystemDock::_update_file_list(bool p_keep_selection) {
 void FileSystemDock::_select_file(const String &p_path, bool p_select_in_favorites) {
 	String fpath = p_path;
 	if (fpath.ends_with("/")) {
-		if (fpath != "res://") {
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:1163]: Not sure what this change is for?

Comment (Vilcrow) [reply editor/filesystem_dock.cpp:1163]: We don't need to remove the slash at the end of the path, otherwise we won't be able to check for the directory. Wherever the method `_select_file()` is called, there is still a slash deletion, if there is one.
The condition
```
if (fpath.ends_with("/")) {
```
is left here to avoid an attempt to load the resource below
```
} else {
        EditorNode::get_singleton()->load_resource(fpath);
    }
```
This is not critical, but an error message appears.
As a result, there is no need to check the condition in the line that you have highlighted.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
