### PR TITLE
Swap rest pose actions in the Skeleton2D editor

### LINKED ISSUE #54793: Reset to Rest Pose in Skeleton2D menu fails
### Godot version

v3.4.stable.official [206ba70f4]

### System information

Windows 10

### Issue description

I have rigged a paper doll guy, mapped bones to verts for deformation, and created animations.
image

In Godot v3.3.4.stable.official [faf3f883d] I can select the Skeleton2D and use the Skeleton2D menu to "Set Bones to Rest Pose." The result looks good. However, in Godot v3.4.stable.official [206ba70f4] this does not work as expected.
image

When I select "Reset to Rest Pose" in the newer version, the Polygon2D assets return to rest pose, however the bones do not. This seems to scramble the mapping of verts to bones for all animations.
image

### Steps to reproduce

1. Load a Skeleton that has been mapped to Polygon2Ds authored in v3.3.4.stable.official [faf3f883d]
2. Select the Skeleton2D
3. Use the Skeleton2D menu to "reset to rest pose"

Observe: Polygon2Ds correctly return to rest pose, bones do not.

4. Try to play an animation

Observe: Now that bones have new offsets animations no longer look correct.

### Minimal reproduction project

[RestPoseBug.zip](https://github.com/godotengine/godot/files/7501439/RestPoseBug.zip)

### PR DESCRIPTION
**Pull request by Calinou**
The texts were changed before, but the actions weren't swapped around. This led to unexpected behavior.

This closes https://github.com/godotengine/godot/issues/54793.

@irslutz Please double-check this, just in case :slightly_smiling_face:

### CODE REVIEW

File: editor/plugins/skeleton_2d_editor_plugin.cpp [hunk 1]
```diff
@@ -52,34 +52,34 @@ void Skeleton2DEditor::_menu_option(int p_option) {
 	}
 
 	switch (p_option) {
-		case MENU_OPTION_MAKE_REST: {
+			case MENU_OPTION_SET_REST: {
```
Comment (akien-mga) [inline editor/plugins/skeleton_2d_editor_plugin.cpp:55]: Style bug.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.1.
