### PR TITLE
[Mono] Fix string Find methods having reversed case sensitivity

### LINKED ISSUE #34294: findn doesn't work in C#
**Godot version:**
269145a346bddae5cbbf00fd17b6c8eac4cd4665
**OS/device including version:**
ArcoLinux
**Issue description:**
image

**Steps to reproduce:**
```swift
func _ready() -> void:
    var test := "MyTeXt"
    var search := "mytext"
    print(test.findn(search))
```
```cs
public override void _Ready() {
    var test = "MyTeXt";
    var search = "mytext";
    GD.Print(test.FindN(search));
}
```

### PR DESCRIPTION
**Pull request by aaronfranke**
Fixes #34294, and also adds a `caseSensitive` bool like in many of the other methods, and ~~removes~~ fixes the unused "from" argument which literally did nothing before.

### CODE REVIEW

File: modules/mono/glue/Managed/Files/StringExtensions.cs [hunk 1]
```diff
@@ -928,7 +928,7 @@ public static float[] SplitFloats(this string instance, string divisor, bool all
 
             while (true)
             {
-                int end = instance.Find(divisor, from);
+                int end = instance.Find(divisor);
```
Comment (akien-mga) [inline modules/mono/glue/Managed/Files/StringExtensions.cs]: How does this work without `from` if there are several divisors?

Comment (aaronfranke) [reply modules/mono/glue/Managed/Files/StringExtensions.cs]: Well, I don't know for sure, but I think it doesn't. Still, this code didn't work before either...

I didn't know if I should try to refactor so much code for what was originally supposed to be just a bug fix, but I just looked it up and it seems IndexOf does actually have this functionality... brb.

**Review by neikeq — APPROVED** [review]
Looks good, but I think we should start enforcing the use of named parameters at least for booleans.

**Comment by akien-mga** [comment]
Thanks!
