### PR TITLE
Change picking dialog title based on track type

### LINKED ISSUE #57799: Garbled text on creating a method call track in the animationplayer
### Godot version

v3.5.beta1.official [b9b23d222]

### System information

w10 64

### Issue description

When you click on "+ Add track" -> "Method Call track".
This brings up a node selection box, this box has the title "Select the node will be animated".
This is wrong. The title should be "Select the node that contains the method to call".
I am going to animate a sprite node but the node that has the script with the method that I want to call is another node, it is not that sprite node that I want to animate. 
If I obey the title of that panel, then I will select my Sprite node.

https://user-images.githubusercontent.com/19652075/152982108-8533d702-f8ff-4ab7-a3bb-4591d58c8aee.mp4

### Steps to reproduce

See the video

### Minimal reproduction project

...

### PR DESCRIPTION
**Pull request by KoBeWi**
Closes #57799
image

### CODE REVIEW

File: editor/animation/animation_track_editor.cpp [hunk 1]
```diff
@@ -5830,16 +5832,21 @@ void AnimationTrackEditor::_add_track(int p_type) {
...
+			title_text = TTRC("Pick a node to select method:");
+		} break;
 		case Animation::TYPE_AUDIO: {
 			valid_types.push_back(SNAME("AudioStreamPlayer"));
 			valid_types.push_back(SNAME("AudioStreamPlayer2D"));
 			valid_types.push_back(SNAME("AudioStreamPlayer3D"));
+			title_text = TTRC("Pick a node to play audio:");
 		} break;
 		case Animation::TYPE_ANIMATION: {
 			valid_types.push_back(SNAME("AnimationPlayer"));
```
Comment (TokageItLab) [inline editor/animation/animation_track_editor.cpp:5845]: I think we can add:
```
title_text = TTRC("Pick a node to play animation:");
```
or
```
title_text = TTRC("Pick a node to playback animation:");
```
but it should make consistent with TYPE_AUDIO.

**Review by TokageItLab — APPROVED** [review]
