### PR TITLE
Check if any global script class is shadowed by a variable

### LINKED ISSUE #80003: Variable name shadowing class_name class doesn't trigger any error/warning
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 (NVIDIA; 31.0.15.3667) - Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 Threads)

### Issue description

If you define a `class_name` and then use the same name in a variable, no shadowing error/warning is triggered. This also create some bad references (see below).

### Steps to reproduce

Just do something like:
```
class_name Foo
extends Control

var Foo: Foo
```

In another script you can also do:
```
extends Node

var Foo: Foo #= Foo.new() # this raises an error if uncommented: Parse Error: Could not resolve member "Foo": Cyclic reference


func _ready():
	Foo ## This refers to main.gd and not to the local variable
```

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by garychia**
Related to #80003

* *Bugsquad edit, fixes: #80003*

### CODE REVIEW

**Review by anvilfolk — APPROVED** [review]
Looks great to me! Make sure to use keywords that github understands, like directly say `Fixes #<pr-number>`, which will autolink it :)

**Comment by dalexeev** [comment]
I haven't tested, just guessing. Can you get a false positive warning when reloading the script in the editor if the class name is already in the global script cache?

**Comment by anvilfolk** [comment]
Oh, good point. Let me try.

**Review by anvilfolk — CHANGES_REQUESTED** [review]
I couldn't get the warning to fire when it shouldn't. This is an easy one to revert should problems crop up, so I'd say I still want to merge!

However, I'd actually like to see improved error handling, like so:
1) The current warning should explicitly say it's a `native` class, because I think what `ClassDB` contains?
2) We should add another case for the GDScript/scriptserver warning, which should also actually expose what file the class is defined in using `ScriptServer::get_global_class_path(class_name)`. That way we easily know where the conflict is coming from!

**Comment by anvilfolk** [comment]
Also, I notice you have quite a few PRs but often say related to instead of fixes/closes in them - feel free to edit those so that GH actually links the issues!

And you'd be very welcome in the [Godot contributors chat](https://chat.godotengine.org/) if you wanted to discuss stuff with other godot devs!

**Review by anvilfolk — CHANGES_REQUESTED** [review]
Just a small change more so the code is consistent, then I think it's good to merge :)

**Review by anvilfolk — APPROVED** [review]
Looks great!!! :)

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -5026,7 +5026,12 @@ void GDScriptAnalyzer::is_shadowing(GDScriptParser::IdentifierNode *p_identifier
 			parser->push_warning(p_identifier, GDScriptWarning::SHADOWED_GLOBAL_IDENTIFIER, p_context, name, "built-in function");
 			return;
 		} else if (ClassDB::class_exists(name)) {
-			parser->push_warning(p_identifier, GDScriptWarning::SHADOWED_GLOBAL_IDENTIFIER, p_context, name, "global class");
+			parser->push_warning(p_identifier, GDScriptWarning::SHADOWED_GLOBAL_IDENTIFIER, p_context, name, "native class");
+			return;
+		} else if (ScriptServer::is_global_class(name)) {
+			String class_path = ScriptServer::get_global_class_path(name);
+			class_path = class_path.substr(class_path.rfind("/") + 1);
```
Comment (dalexeev) [inline modules/gdscript/gdscript_analyzer.cpp:5033]:
```suggestion
			String class_path = ScriptServer::get_global_class_path(name).get_file();
```

There is [`get_file()`](https://docs.godotengine.org/en/stable/classes/class_string.html#class-string-method-get-file) method. I'm not sure if it's worth truncating the path, but unfortunately the tests now use absolute paths, so the choice is between the file name and not using the path at all.

**Review by dalexeev — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
