### PR TITLE
Fix creating outline for skinned meshes

### LINKED ISSUE #106074: creating outline mesh in a skinned mesh does not automatically associate outline mesh with Skeleton3D
### Tested versions

- Reproducible in: 4.5.dev3

### System information

Godot v4.5.dev (1cf573f44) - Pop!_OS 22.04 LTS on X11 - X11 display driver, Multi-window, 1 monitor - OpenGL 3 (Compatibility) - AMD Radeon Graphics (radeonsi, renoir, LLVM 15.0.7, DRM 3.59, 6.12.10-76061203-generic) - AMD Ryzen 5 4600H with Radeon Graphics (12 threads)

### Issue description

when I create an outline mesh in a skinned mesh the outline mesh does not follow the movement of Skeletom3D

Image

### Steps to reproduce

import a skinned mesh with animation into your scene

Image

select the skinned mesh and create an outline mesh for it

Image

and then run an animation that deforms the skinned mesh

Image

### Minimal reproduction project (MRP)

[outline_issue.zip](https://github.com/user-attachments/files/20028222/outline_issue.zip)

### PR DESCRIPTION
**Pull request by TheoLomeuBraga**
Closes https://github.com/godotengine/godot/issues/106074

now creating an outline mesh for a mesh with skim property will share the skim and skeleton properties for the outline mesh

### CODE REVIEW

**Comment by akien-mga** [comment]
Hello! Thanks for contributing.

I assigned animation maintainers for review as they're most familiar with mesh skinning.

A small form nitpick: The commit message should be amended to be a proper sentence in English (like I did with the PR title). See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind and [PR workflow](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html) for details on how to format and amend commits.

File: editor/plugins/mesh_instance_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -542,6 +542,13 @@ void MeshInstance3DEditor::_create_outline_mesh() {
 
 	MeshInstance3D *mi = memnew(MeshInstance3D);
 	mi->set_mesh(mesho);
+
+	Node *skeleton = node->get_node(node->get_skeleton_path());
```
Comment (fire) [inline editor/plugins/mesh_instance_3d_editor_plugin.cpp:546]: This seems ok, we have a new MeshInstance3D and we either use the existing math or assume that it's the parent node (as a skeleton3d).

Comment (TheoLomeuBraga) [reply editor/plugins/mesh_instance_3d_editor_plugin.cpp:546]: precisely

**Review by SaracenOne — APPROVED** [review]
Approved in meeting 👍

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
