### PR TITLE
Fix issue with disconnecting events when font changes

### LINKED ISSUE #34548: "Attempt to disconnect signal 'changed' while emitting" when zooming Script Editor.
**Godot version:**
3.2 beta4

**Steps to reproduce:**
1. Open script editor.
2. Hold Ctrl
3. Move mouse wheel to zoom
4.
image

### PR DESCRIPTION
**Pull request by NoFr1ends**
When the editor changes the font (e.g. zooming) the theme changes and try to disconnect signals in a signal emission (`add_font_override`). 

Fixes #34548

### CODE REVIEW

File: scene/gui/control.cpp [hunk 1]
```diff
@@ -2286,7 +2286,7 @@ void Control::set_theme(const Ref<Theme> &p_theme) {
 	}
 
 	if (data.theme.is_valid()) {
-		data.theme->connect("changed", this, "_theme_changed");
+		data.theme->connect("changed", this, "_theme_changed", Vector<Variant>(), CONNECT_DEFERRED);
```
Comment (akien-mga) [inline scene/gui/control.cpp]: I think you can use `varray()` for the default parameter, that's what other such calls use.

Comment (NoFr1ends) [reply scene/gui/control.cpp]: I saw both in this file, but I changed it.

**Comment by akien-mga** [comment]
Thanks!
