### PR TITLE
Apply "Remove Immutable Tracks" after post-import.

### LINKED ISSUE #90031: Remove Immutable Tracks import option breaks some character animations
### Tested versions

Reproduces in: v4.3.dev.custom [7d151c838]
Doesn't reproduce in: v4.2.1.stable

### System information

Win 11, but it's not an OS issue

### Issue description

When importing animation files with single animation, where armature's initial pose is the first frame of the animation, Remove Immutable Tracks option removes one-key tracks that set this pose up, causing bones affected by these tracks to show rest or previous pose instead of the correct pose. This is especially noticeable on character hands holding weapons and staying in one pose throughout the animation clip.

Screenshots: Left - Remove Immutable Tracks enabled, Right - disabled
Screenshot 2024-03-29 005810Screenshot 2024-03-29 005745_

I've mostly encountered this on skinless one-clip animations FBX files exported from 3dMax, common in animation packs from asset stores. I tried to reproduce this in 4.2 and didn't manage to find a file that would import but have this issue. Probably means it's not a regression. It wasn't such a problem in previous versions, because previously such files would just be impossible to import :)

### Steps to reproduce

- Add animation file to project
- Tick Import as Skeleton Bones if necessary (see #88819)
- Set Rest Pose to an external T-pose animation fit for this rig (see #88824)
- Set BoneMap
- Reimport

Remove Immutable Tracks is on by default, so this issue pops up during normal import process. You don't need to go out of your way to encounter it. Note that it happens on specific files that would not import correctly without the new process.

### Minimal reproduction project (MRP)

I encountered this issue with commercially available asset packs, so I can't really include them in an MRP and I was unable to reproduce them with mixamo animations because they have a proper initial pose baked into them, even if you download the versions without the mesh.

EDIT(lyuma): I made a blend file to reproduce the issue (rename the file extensions after downloading):
[simple_vrm_rig_anim4.blend](https://github.com/godotengine/godot/files/14814381/simple_vrm_rig_anim4.blend.pptx)
[simple_vrm_rig_nlaonly2.fbx](https://github.com/godotengine/godot/files/14814384/simple_vrm_rig_nlaonly2.fbx.pptx)

### PR DESCRIPTION
**Pull request by lyuma**
Reimplements "Remove Immutable" in `ResourceImportScene::_post_fix_animations` by comparing to the skeleton rest.

The old implementation took a shortcut, effectively optimizing animation tracks before the animation tracks were even added to the AnimationPlayer. However, this optimization led to incorrect results in cases where the skeleton bone rest was not equal to the initial bone pose. Therefore, it is necessary to delay removing animation tracks until after the correct rest pose is calculated in rest-fixer.

I pass false into GLTFDocument / FBXDocument APIs in order to preserve the original implementation (which is available at runtime) for compatibility. The codepaths are too different to offer a replacement with the new implementation. The old implementation of "remove_immutable_tracks" rather chose which tracks to keep before adding them in the first place (a shortcut), while the new implementation detects which tracks are immutable and removes them in the post import flow. While it is sort of duplicate functionality in two places, the code is not duplicated, and after basically a day of thinking about it, I was unable to come up with an approach for reconciling the two features of the same name.

Fixes #90031 (See the test files I uploaded to that issue)
Note that the position offset is incorrect on the imported animation tracks. I chose to split that off into a separate issue. See also
* #90065

CC @TokageItLab

### CODE REVIEW

**Review by fire — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

File: modules/gltf/editor/editor_scene_importer_blend.cpp [hunk 1]
```diff
@@ -301,10 +301,9 @@ Node *EditorSceneFormatImporterBlend::import_scene(const String &p_path, uint32_
 
 #ifndef DISABLE_DEPRECATED
 	bool trimming = p_options.has("animation/trimming") ? (bool)p_options["animation/trimming"] : false;
-	bool remove_immutable = p_options.has("animation/remove_immutable_tracks") ? (bool)p_options["animation/remove_immutable_tracks"] : true;
-	return gltf->generate_scene(state, (float)p_options["animation/fps"], trimming, remove_immutable);
+	return gltf->generate_scene(state, (float)p_options["animation/fps"], trimming, false);
 #else
-	return gltf->generate_scene(state, (float)p_options["animation/fps"], (bool)p_options["animation/trimming"], (bool)p_options["animation/remove_immutable_tracks"]);
+	return gltf->generate_scene(state, (float)p_options["animation/fps"], (bool)p_options["animation/trimming"], false);
```
Comment (TokageItLab) [inline modules/gltf/editor/editor_scene_importer_blend.cpp:306]: I suspect that the original implementation of remove_immutable_tracks is completely ignored due to enforcing `false` here and causing the issue in #91893. I wonder if it needs to be enabled depending on the options as `(bool)p_options["animation/remove_immutable_tracks"]);`, in this case such as if the external pose is not being used as a reference for rest. Though? @lyuma @fire

Comment (lyuma) [reply modules/gltf/editor/editor_scene_importer_blend.cpp:306]: That argument enables the old option which applies before silhouette fixer and hence will remove tracks inappropriately before silhouette fixer changes the pose. When doing retargeting, it is important for this to be false, and it can always be false.

The remove immutable tracks code in resource_importer_scene has code that should remove scale tracks if they match the rest pose.

Comment (TokageItLab) [reply modules/gltf/editor/editor_scene_importer_blend.cpp:306]: But has this PR also changed the order of ApplyNodeScale and RemoveImmutableTrack when you changed the order?

**Comment by yythlj** [comment]
how to fix this problem on godot 4.3.dev6 or godot4.2?my project can not import any new mixamo skeleton now...

**Comment by yythlj** [comment]
when I click the import the animationplayer node on the import scene instance, the model disappear.And never occur on the scene

**Comment by lyuma** [comment]
@yythlj My apologies for introducing the regression in this PR. We have solved the issue you describe in #92012

The fix was already merged and will be included in 4.3 beta which should be out shortly. Please be patient ;-)

**Comment by yythlj** [comment]
such a big bug how to continue project's work ...
cannot wait a minutes
image

**Comment by yythlj** [comment]
luckyly I has the backup.The bug will make all glb.import be fail and no fix forever

**Comment by akien-mga** [comment]
@yythlj You were already asked to be patient. If you can't use 4.3-dev6 due to this, stay on 4.2.2. Or build from the master branch to have the fix until a new snapshot is published.

Dev snapshots are what the name implies - snapshots from the development branch. If you start using them, you accept the risk that they might have bugs.

Please refer to the [Code of Conduct](https://godotengine.org/code-of-conduct/) for an overview of what kind of behavior is expected on this platform.

**Comment by yythlj** [comment]
4.2.2stable has both the bug



---Original---
From: "Rémi ***@***.***&gt;
Date: Wed, May 29, 2024 14:01 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [godotengine/godot] Apply "Remove Immutable Tracks" afterpost-import. (PR #90064)




 
@yythlj You were already asked to be patient. If you can't use 4.3-dev6 due to this, stay on 4.2.2. Or build from the master branch to have the fix until a new snapshot is published.
 
Dev snapshots are what the name implies - snapshots from the development branch. If you start using them, you accept the risk that they might have bugs.
 
Please refer to the Code of Conduct for an overview of what kind of behavior is expected on this platform.

**Comment by yythlj** [comment]
new proj on 4.2.1.stable maybe no problem.But my project now both error on the 4.2 and 4.3, because alreay use 4.3 open the proj and the tscn had changed.this state go back to 4.2 version take no use

**Comment by lyuma** [comment]
@yythlj 4.3 beta is out. I would be interested to know if updating to 4.3 beta solves the issue.
 (Note that if you have an existing .tscn, it might remember old values so double check with a new instanced scene or replay the animation.)
