### PR TITLE
`Curve3D` bake refactor continue

### LINKED ISSUE #68893: Curve3D::sample_baked_up_vector() returns value perpendicular to its previous value after merge
### Godot version

8ab3e73a799bbfa862403747a5de9fc96ba83149

### System information

Ubuntu 22.04

### Issue description

Prior to 8ab3e73a799bbfa862403747a5de9fc96ba83149, `Curve3D::sample_baked_up_vector()` returned a somewhat plausible up vector for some curves, however since 8ab3e73a799bbfa862403747a5de9fc96ba83149 it returns a vector perpendicular to the old value. Original PR #64212

The simple attached project displays the angle between the first curve point up vector, and the global up vector

8ab3e73a799bbfa862403747a5de9fc96ba83149

2022-11-19-102053_1916x1033_scrot

8ab3e73a799bbfa862403747a5de9fc96ba83149^

2022-11-19-103036_1916x1033_scrot

Additional screenshots here: https://github.com/godotengine/godot/pull/64212#issuecomment-1320811390 (more difficult to reproduce because it requires rebasing another change)

### Steps to reproduce

1. Create a Node3D
2. Assign it a Curve3D
3. call `Curve3D::sample_baked_up_vector()`
4. Observe the value with Godot after 8ab3e73a799bbfa862403747a5de9fc96ba83149
5. Observe the value with Godot 8ab3e73a799bbfa862403747a5de9fc96ba83149^

Run the attached project to accomplish the same

### Minimal reproduction project

Run the example scene in this project to show this behavior [Curve3D Up Vector Test.zip](https://github.com/godotengine/godot/files/10047493/Curve3D.Up.Vector.Test.zip)

### PR DESCRIPTION
**Pull request by xiongyaohua**
This PR follows https://github.com/godotengine/godot/pull/64212, further refactoring the bake code of `Curve3D`. 

The main change is to calculate tangent directly from bezier curve, without going
through discretized polyline.

This is mathematically correct method has the following benefits:
1. More accurate transform frames sampling along the curve; 
2. Path3DFollow movement is completely smooth, fixing https://github.com/godotengine/godot/pull/64212#discussion_r1020716713;
3. Initial up vector is not influenced by baking interval, fixing https://github.com/godotengine/godot/issues/68893
4. Adhoc checks and fixes become unnecessary, leading to simpler and more performant code.

The same refactor can be applied to `Curve2D` in a seperate PR.

_Production edit: Fixes https://github.com/godotengine/godot/issues/68893_

### CODE REVIEW

**Review by fire — COMMENTED** [review]
@TokageItLab has combined many bezier curve equations into a central place. Maybe you can combine?

**Comment by xiongyaohua** [comment]
> @TokageItLab combined many bezier curve equations into a central place. Maybe you can combine?

Sure. Where is this "central place" refers to?

> name it something like bezier_derivative() without normalizing

Done.

File: core/math/vector3.h [hunk 1]
```diff
@@ -100,6 +100,7 @@ struct _NO_DISCARD_ Vector3 {
 	_FORCE_INLINE_ Vector3 cubic_interpolate(const Vector3 &p_b, const Vector3 &p_pre_a, const Vector3 &p_post_b, const real_t p_weight) const;
 	_FORCE_INLINE_ Vector3 cubic_interpolate_in_time(const Vector3 &p_b, const Vector3 &p_pre_a, const Vector3 &p_post_b, const real_t p_weight, const real_t &p_b_t, const real_t &p_pre_a_t, const real_t &p_post_b_t) const;
 	_FORCE_INLINE_ Vector3 bezier_interpolate(const Vector3 &p_control_1, const Vector3 &p_control_2, const Vector3 &p_end, const real_t p_t) const;
+	_FORCE_INLINE_ Vector3 _bezier_derivative(const Vector3 &p_control_1, const Vector3 &p_control_2, const Vector3 &p_end, const real_t p_t) const;
```
Comment (TokageItLab) [inline core/math/vector3.h:103]:
```suggestion
	_FORCE_INLINE_ Vector3 bezier_derivative(const Vector3 &p_control_1, const Vector3 &p_control_2, const Vector3 &p_end, const real_t p_t) const;
```

Can you make public with binging?

Comment (xiongyaohua) [reply core/math/vector3.h:103]: For consistency, if we expose for `Vector3` we also need to expose for `Vector2` and `Math`. Is it better to do this in an follow up PR?

Comment (TokageItLab) [reply core/math/vector3.h:103]: I think it is fine that doing it all in this PR.

Comment (xiongyaohua) [reply core/math/vector3.h]: done

**Review by fire — COMMENTED** [review]
@TokageItLab Can you look and review for approval? I'm not able to check the math. The structure is good.

**Comment by YuriSizov** [comment]
Please don't forget to squash your commits and give it a short but clear message.

File: core/math/math_funcs.h [hunk 2]
```diff
@@ -364,6 +364,26 @@ class Math {
...
+
+	static _ALWAYS_INLINE_ float bezier_derivative(float p_start, float p_control_1, float p_control_2, float p_end, float p_t) {
+		/* Formula from Wikipedia article on Bezier curves. */
+		float omt = (1.0 - p_t);
+		float omt2 = omt * omt;
+		float t2 = p_t * p_t;
+
+		float d = (p_control_1 - p_start) * 3.0 * omt2 + (p_control_2 - p_control_1) * 6.0 * omt * p_t + (p_end - p_control_2) * 3.0 * t2;
+		return d;
+	}
```
Comment (TokageItLab) [inline core/math/math_funcs.h:385]:
```suggestion
	static _ALWAYS_INLINE_ float bezier_derivative(float p_start, float p_control_1, float p_control_2, float p_end, float p_t) {
		/* Formula from Wikipedia article on Bezier curves. */
		float omt = (1.0f - p_t);
		float omt2 = omt * omt;
		float t2 = p_t * p_t;

		float d = (p_control_1 - p_start) * 3.0f * omt2 + (p_control_2 - p_control_1) * 6.0f * omt * p_t + (p_end - p_control_2) * 3.0f * t2;
		return d;
	}
```

**Review by TokageItLab — CHANGES_REQUESTED** [review]

File: scene/resources/curve.cpp [hunk 3]
```diff
@@ -1601,8 +1559,8 @@ void Curve3D::_bake() const {
 				is_loop = false;
 			}
 
-			real_t dot = forward_write[0].dot(forward_write[point_count - 1]);
-			if (dot < 1.0 - 0.01) { // Alignment should not be too tight, or it dosen't work for coarse bake interval
+			real_t dot = forward_ptr[0].dot(forward_ptr[point_count - 1]);
+			if (dot < 1.0 - UNIT_EPSILON) { // Alignment should not be too tight, or it dosen't work for coarse bake interval
```
Comment (TokageItLab) [inline scene/resources/curve.cpp:1563]:
```suggestion
			if (dot < 1.0 - UNIT_EPSILON) { // Alignment should not be too tight, or it dosen't work for coarse bake interval.
```

File: scene/resources/curve.h [hunk 4]
```diff
@@ -310,6 +314,7 @@ class Curve3D : public Resource {
 	real_t get_closest_offset(const Vector3 &p_to_point) const;
 
 	PackedVector3Array tessellate(int p_max_stages = 5, real_t p_tolerance = 4) const; //useful for display
+	PackedVector3Array tessellate_even_length(int p_max_stages = 5, real_t p_length = 0.2) const; //useful for baking
```
Comment (TokageItLab) [inline scene/resources/curve.h:317]:
```suggestion
	PackedVector3Array tessellate(int p_max_stages = 5, real_t p_tolerance = 4) const; // Useful for display.
	PackedVector3Array tessellate_even_length(int p_max_stages = 5, real_t p_length = 0.2) const; // Useful for baking.
```

**Review by TokageItLab — CHANGES_REQUESTED** [review]

File: scene/resources/curve.h [hunk 5]
```diff
@@ -309,7 +313,8 @@ class Curve3D : public Resource {
 	Vector3 get_closest_point(const Vector3 &p_to_point) const;
 	real_t get_closest_offset(const Vector3 &p_to_point) const;
 
-	PackedVector3Array tessellate(int p_max_stages = 5, real_t p_tolerance = 4) const; //useful for display
+	PackedVector3Array tessellate(int p_max_stages = 5, real_t p_tolerance = 4) const; // Useful for display.
+	PackedVector3Array tessellate_even_length(int p_max_stages = 5, real_t p_length = 0.2) const; // Useful for baking.
```
Comment (TokageItLab) [inline scene/resources/curve.h:317]: Is there any reason to keep the old original tessellate?

Comment (xiongyaohua) [reply scene/resources/curve.h:317]: Yes. For the drawing code the old method is more efficient as it doesn't break long straight segments.

**Review by TokageItLab — APPROVED** [review]
The behavior seems to be better than before.

File: scene/resources/curve.h (hunk 5 above)
Comment (TokageItLab) [reply scene/resources/curve.h:317]: Okay, thank you for explanation.

**Comment by TokageItLab** [comment]
@xiongyaohua Please squash again.

File: doc/classes/@GlobalScope.xml [hunk 6]
```diff
@@ -106,6 +106,17 @@
...
 		</method>
+		<method name="bezier_derivative">
+			<return type="float" />
+			<param index="0" name="start" type="float" />
+			<param index="1" name="control_1" type="float" />
+			<param index="2" name="control_2" type="float" />
+			<param index="3" name="end" type="float" />
+			<param index="4" name="t" type="float" />
+			<description>
+				Returns the derivative at the given [param t] on a one-dimensional [url=https://en.wikipedia.org/wiki/B%C3%A9zier_curve]Bezier curve[/url] defined by the given [param control_1], [param control_2], and [param end] points.
```
Comment (TokageItLab) [inline doc/classes/@GlobalScope.xml:117]: Is this URL correct?

Comment (xiongyaohua) [reply doc/classes/@GlobalScope.xml:117]: yes

**Comment by xiongyaohua** [comment]
> @xiongyaohua Please squash again.

squashed

File: doc/classes/@GlobalScope.xml (hunk 6 above)
Comment (akien-mga) [reply doc/classes/@GlobalScope.xml:117]: I think Tokage meant that you should put the é in the title, not the URL:
```suggestion
				Returns the derivative at the given [param t] on a one-dimensional [url=https://en.wikipedia.org/wiki/B%C3%A9zier_curve]Bézier curve[/url] defined by the given [param control_1], [param control_2], and [param end] points.
```

**Comment by akien-mga** [comment]
Thanks!

File: doc/classes/@GlobalScope.xml (hunk 6 above)
Comment (xiongyaohua) [reply doc/classes/@GlobalScope.xml:117]: Ah, I see. I misunderstood. I'll change the spelling in the follow up PR.
