### PR TITLE
Fix #19507 Not emitted particles affects performance

### LINKED ISSUE #19507: Not emitted particles affects performance
**Godot version:**
257d3c3f39fd144d202f112c9cb08a82c174afbc

**OS/device including version:**
nvidia gtx 1060, Ubuntu 18.04

**Issue description:**
I recently tried to find out why I have such performance problems in my game and I have found an interesting thing. Particle 3D node seems to be processing/rendering even if it's not emitting any particles. It can affect performance heavily especially in the scenario when you have a lot of nodes on the screen which are holding some 'visibly rich' particle effects, that are meant to be used rarely (like hit/death effect)

**Steps to reproduce:**
Full:
1. Create new scene, add Particle node and camera
2. Add cylinder as a particle model in `Draw Passes`
3. Add `Particles material` as `process material`
4. Turn off  `Emitting` property
5. Set amount of particles to 100000
6. Run scene and check number of fps
7. Hide Particle node
8. Run scene again and notice a lot higher number of fps

Quick:
1. Download project with reproduction scene
2. Run it, notice number of fps
3. Hide particle node
4.  Run scene again, notice number of fps

**Minimal reproduction project:**
[NonEmittedParticlesPerformance.zip](https://github.com/godotengine/godot/files/2090447/NonEmittedParticlesPerformance.zip)

### PR DESCRIPTION
**Pull request by malbach**
This PR is to fix #19507, where Particles3D uses ressources (mostly GPU) even when not emitting.

### CODE REVIEW

**Comment by malbach** [comment]
I'd like to correct my PR so travis build won't fail, but I don't understand the problem...
Can someone explain what is wrong, please ? :+1:

**Comment by akien-mga** [comment]
> I'd like to correct my PR so travis build won't fail, but I don't understand the problem...
Can someone explain what is wrong, please ? +1

The build log shows you a diff with the code that is "wrong" and how to fix it: https://travis-ci.org/godotengine/godot/jobs/396418700

Namely:
```diff
--- a/servers/visual/visual_server_scene.cpp	2018-06-25 14:24:50.186020570 +0000
+++ b/servers/visual/visual_server_scene.cpp	2018-06-25 14:25:04.798210680 +0000
@@ -1869,8 +1869,7 @@
 			InstanceGeometryData *geom = static_cast<InstanceGeometryData *>(ins->base_data);
 
 			if (ins->base_type == VS::INSTANCE_PARTICLES) {
-				if (VSG::storage->particles_get_emitting(ins->base) || !VSG::storage->particles_get_inactive(ins->base))
-				{
+				if (VSG::storage->particles_get_emitting(ins->base) || !VSG::storage->particles_get_inactive(ins->base)) {
 					//particles visible? process them
 					VSG::storage->particles_request_process(ins->base);
 					//particles visible? request redraw
```

The problem is that you used Allman bracket style while we use K&R-like (starting bracket on the same line as the if/for/while, etc.). See http://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html

**Comment by malbach** [comment]
Well, my problem is that I did not commit such change, look at the files changes from my PR for the incriminated file and you'll see that what travis is showing does not exist... or I have a big updating problem somewhere

**Comment by mhilbrunner** [comment]
Thank you for fixing this, congrats on your first contribution - and sorry this took some time to get merged, we've got a lot of contributions coming in. :)

**Comment by mhilbrunner** [comment]
Note: After feedback from reduz, we had to revert this, as it may negatively impact performance when multithreaded rendering is enabled. Comments from IRC below:

```
this will incur a huge performance cost if rendering is threaded
because visual server, when threaded feeds all commands to a queue
if you call any functiont that requests data from it, it needs to flush the entire command queue and stop rendering
requesting data from servers is a no
this is why most functions dont return data
unless you are doing something like saving
```

**Comment by reduz** [comment]
Sorry, please let me review this before merging

File: servers/visual_server.h [hunk 1]
```diff
@@ -508,6 +508,7 @@ class VisualServer : public Object {
 
 	virtual void particles_set_emitting(RID p_particles, bool p_emitting) = 0;
 	virtual bool particles_get_emitting(RID p_particles) = 0;
+	virtual bool particles_get_inactive(RID p_particles) = 0;
```
Comment (reduz) [inline servers/visual_server.h]: This is not necessary, emitting may be needed to eventually serialize back the state of the particles.

Inactive is an internal variable that should never be exposed, the reason is that VisualServer, when running on a thread, puts all functions into a command buffer. If data is requested from it in that scenario by calling a function that returns something, it will force all the previous commands to execute and stall rendering, severely affecting performance.

Because of this, internal run-time state should never be requested. For this PR to be merged, just not exposing this function is enough.
