### PR TITLE
[3.x] Fix 2D MultiMesh hierarchical culling

### LINKED ISSUE #80086: [3.x] 2D Particle hierarchical culling not working correctly
### Godot version

3.6 (after #68738 merged)

### System information

All

### Issue description

2D particles are being culled when the parent object leaves the frame, when hierarchical culling is enabled.

https://github.com/godotengine/godot/assets/21999379/1ec3575d-0711-4bea-b152-b673cd3249ca

### Steps to reproduce

Create 2D particle system and move off screen with hierarchical culling enabled. Note that the particles disappear as soon as the origin moves off screen, rather than still showing the particles that have been emitted.

### Minimal reproduction project

[particle_hierarchical_culling.zip](https://github.com/godotengine/godot/files/12215342/particle_hierarchical_culling.zip)

## Discussion
This is easy enough to fix in the meantime by turning off hierarchical culling (`rendering/2D/options/culling_mode` set to `Item` instead of `Node`).

I'm just fixing this now. The problem is the same as with skeletons - the bounding rect is changed by updates from the scene tree, and the local bound is never updated, so everything is culled from the parent object.

In the legacy item culling code, the bound is deferred updated when `get_rect()` is called on the item during the render traversal through the tree.

There's a number of ways to solve this, but I'll probably use something similar to skeletons, and trigger an update of the local bounds when the multimesh is changed (at least in the case of `CPUParticles2D`, haven't got to `GPUparticles2D` yet).

### PR DESCRIPTION
**Pull request by lawnjelly**
Fixes updating local bounds for MultiMeshes used in canvas items by introducing a back link.

This version as well as fixing `CPUParticles2D`, also fixes `MultiMeshInstance2D` and direct use of `VisualServer`.

Fixes #80086
Alternative to #80090

_before_

https://github.com/godotengine/godot/assets/21999379/d5ccc84e-ad5f-4301-8a61-47c5205472ee

_after_

https://github.com/godotengine/godot/assets/21999379/e770d74f-f7a4-4661-b848-7ee042b23176

This PR is basically an automated version of #80090 . `canvas_item_invalidate_local_bound()` is called automatically when changing the `MultiMesh`. This means users don't have to call this function.

The downside is that the machinery for maintaining the backlink is fairly complex, and complexity often equals bug prone and more maintenance burden. The system is equivalent to that used for `Skeleton`, which maintains a backlink to the `canvas_item`. However, the situation here is more complex for two reasons:

1) `MultiMesh` references are stored in Item commands, rather than directly in the `canvas_item`. This means that adding / removing links has to to take place via the command list, rather than directly via the `canvas_item`. There can also potentially be _multiple_ commands referencing the same `MultiMesh`. There is no need to reference count here, because commands are only cleared all at once, so there either _is_, or _is not_ a reference held at any one time.
2) Order of deletion is not guaranteed. We have to support both the `MultiMesh` being deleted before the `canvas_item`, and the other way around, with code to support both.

## Designed to keep CanvasItem "light"
* We could alternatively keep a `LocalVector` of linked `MultiMeshes` on the `CanvasItem`, which would in some ways be simpler (with no need to iterate through commands). However we want to keep `CanvasItem` as light as possible (most `CanvasItem`s will be rects, and not care about `MultiMesh`), and storing the links in the commands is effectively "free", so it's probably worth the extra hassle.
* Storing the `canvas_item` RID on each `Command::MultiMesh` is a little superfluous, but it enables us to clear out the links in the destructor with _no cost_ to `CanvasItem`s that do not contain multimeshes. The 8 extra bytes is likely to be unimportant, because most `Command::MultiMesh`es will only be stored singly on `CanvasItems`. Essentially it is more important to keep the typical `CanvasItem` light than the `Command::MultiMesh`.
There may be a slightly better way of doing this (e.g. using a static or global to store the canvas_item RID during deletion) but storing the canvas_item RID is at least thread safe.

## Notes
* It turned out for #80090 that in order to support `MultiMeshInstance2D` we would have to introduce similar complexity scene side, so I'm now leading with this PR.

### CODE REVIEW

File: servers/visual/visual_server_canvas.cpp [hunk 1]
```diff
@@ -1463,7 +1471,16 @@ void VisualServerCanvas::canvas_item_attach_skeleton(RID p_item, RID p_skeleton)
 	}
 }
 
-void VisualServerCanvas::_canvas_item_skeleton_moved(RID p_item) {
```
Comment (lawnjelly) [inline servers/visual/visual_server_canvas.cpp:1466]: Note this function is renamed to `_canvas_item_invalidate_local_bound()`, as this behaviour is now shared between skeleton and multimesh.

File: drivers/gles3/rasterizer_storage_gles3.cpp [hunk 2]
```diff
@@ -5001,6 +5019,14 @@ void RasterizerStorageGLES3::update_dirty_multimeshes() {
 			}
 
 			multimesh->aabb = aabb;
+
+			// Inform any linked canvas items that bounds have changed.
+			// (for hierarchical culling)
```
Comment (akien-mga) [inline drivers/gles3/rasterizer_storage_gles3.cpp:5024]:
```suggestion
			// Inform any linked canvas items that bounds have changed
			// (for hierarchical culling).
```

File: drivers/gles2/rasterizer_storage_gles2.cpp [hunk 3]
```diff
@@ -6052,6 +6078,14 @@ bool RasterizerStorageGLES2::free(RID p_rid) {
 		_interpolation_data.notify_free_multimesh(p_rid);
 
 		MultiMesh *multimesh = multimesh_owner.get(p_rid);
+
+		// remove any references in linked canvas items
```
[the remark this answers is not in the document]
Comment (akien-mga) [reply drivers/gles2/rasterizer_storage_gles2.cpp:6082]: Ah well I see it's following pre-existing style. Probably fine to keep it consistent with existing code, unless we want to do a cleanup pass.

[the remark this answers is not in the document]
Comment (lawnjelly) [reply drivers/gles2/rasterizer_storage_gles2.cpp:6082]: Have left as is for now.

File: servers/visual/rasterizer.h [hunk 4]
```diff
@@ -1181,6 +1192,16 @@ class RasterizerCanvas {
 			return rect;
 		}
 
+		void remove_references(const RID &p_rid) {
+			for (int i = commands.size() - 1; i >= 0; i--) {
+				if (commands[i]->contains_reference(p_rid)) {
+					// Delete the command and pop the last.
+					memdelete(commands[i]);
+					commands.resize(commands.size() - 1);
```
Comment (lawnjelly) [inline servers/visual/rasterizer.h:1200]: Just noticed a bug here, the command isn't always the last in the list so it needs an unordered remove I think. Just fixing.

Comment (lawnjelly) [reply servers/visual/rasterizer.h]: Fixed.

File: servers/visual/visual_server_canvas.cpp (hunk 1 above)
Comment (kleonc) [reply servers/visual/visual_server_canvas.cpp:1585]: You've left `_canvas_item_skeleton_moved` declaration in the `.h` file, is this intended?

Comment (lawnjelly) [reply servers/visual/visual_server_canvas.cpp:1585]: Good catch, probably got reintroduced in the rebase. I'll remove it. :+1:

File: drivers/gles2/rasterizer_storage_gles2.cpp [hunk 5]
```diff
@@ -3388,6 +3388,24 @@ RasterizerStorage::MMInterpolator *RasterizerStorageGLES2::_multimesh_get_interp
...
+		int64_t found = multimesh->linked_canvas_items.find(p_canvas_item);
+		if (found == -1) {
+			multimesh->linked_canvas_items.push_back(p_canvas_item);
+		}
+	} else {
+		int64_t found = multimesh->linked_canvas_items.find(p_canvas_item);
+		if (found != -1) {
+			multimesh->linked_canvas_items.remove_unordered(found);
+		}
+	}
```
Comment (kleonc) [inline drivers/gles2/rasterizer_storage_gles2.cpp:3406]: Why the difference compared to the skeleton one? Shouldn't these be pretty much the same? :thinking:
https://github.com/godotengine/godot/blob/b776cf54982e5f5bcbe33c226eb984f8ac0ef3ed/drivers/gles2/rasterizer_storage_gles2.cpp#L3782-L3788

Comment (lawnjelly) [reply drivers/gles2/rasterizer_storage_gles2.cpp:3406]: The skeleton one is simpler because there can only be one skeleton linked by a `canvas_item` (it is stored as a `RID` on the `canvas_item`).

For `MultiMesh`, the situation is more complex, each `Item::Command` which stores a draw instruction on the `canvas_item` can potentially hold a link to a `MultiMesh`. Thus the same `MultiMesh` can contain _multiple_ links per `canvas_item`.

These links need to be simplified to build up and destroy such that when the commands referencing a particular `MultiMesh` are gone, the link is broken.

One obvious way would be to use a refcount. But in fact the situation here can be slightly simplified, because `canvas_items` never delete `Commands` once they are added. They are only ever cleared at once. So we can guarantee during deletion if any `Command` contains a link to a `MultiMesh`, we can destroy the link. Any later duplicate links will not find the `linked_item` (hence the test for `found`) in the destroy.

For creation it's the same deal. We only need to add the link on the first `Command` which references a `MultiMesh`. Later commands will find the already existing link and do nothing.

Comment (lawnjelly) [reply drivers/gles2/rasterizer_storage_gles2.cpp:3406]: Sorry, my explanation with the ratios was perhaps a little confusing, as there are lots of permutations.

The important point is that if you look at the definition of `Item` (rasterizer.h, line 801) you will see that only ONE skeleton can be used by an `Item`. Therefore no similar check is needed for skeleton, as the canvas item can only be linked once.

For multimeshes, there can be MULTIPLE multimeshes linked per `Item`.

**Review by kleonc — APPROVED** [review]
Changes make sense, code looks good AFAICT.

I'd say don't merge without @clayjohn's review though.

File: drivers/gles2/rasterizer_storage_gles2.cpp (hunk 5 above)
Comment (kleonc) [reply drivers/gles2/rasterizer_storage_gles2.cpp:3406]: I mean yes, many errors theoretically should not occur and thus could be dev-only. Theoretically though... :wink:

To be clear: I'm not advocating for adding error checks everywhere. It's strange that both "should-never-happen" cases are treated differently, that's all. And I get the `ERR_FAIL_COND(found == -1);` has kinda no cost as `found` is available anyway but it's still kinda pointless as `LocalVector::remove_unordered` checks the index validity itself (and double checking because it's cheap doesn't seem reasonable). So alternative to adding more checks like in #80325 could be removing the existing `ERR_FAIL_COND(found == -1);` check. Or could be left as is, it's not a big thing anyway, just catched my eye.

Comment (lawnjelly) [reply drivers/gles2/rasterizer_storage_gles2.cpp:3406]: Correct about `remove_unordered()`, but optimizer should sort this kind of redundant thing. If there's a check for -1, and a later similar check (inlined), it should remove the latter. It's also imo a bit of a micro-optimization (unless it shows up in profiles), and on the plus side the error message is better this way. :grinning: 

The potentially expensive bit is the `find()` in worst cases (say the skeleton has 10,000 linked canvas items), then detaching each in turn will be log performance drop with `n`. This is the same problem we had with notifications.

That isn't to say there are other techniques / containers that avoid using `find()`, but I don't think it is warranted here.

**Comment by akien-mga** [comment]
> I'd say don't merge without @clayjohn's review though.

Woops, I missed that one before merging. I'll ask Clay to review post-merge when he has time.

**Comment by clayjohn** [comment]
It looks fine from a visual review!
