### PR TITLE
Physics Interpolation - Move 3D FTI to `SceneTree`

### LINKED ISSUE #9964: Interpolate camera FOV (3D) and zoom (2D) when using physics interpolation
- *Related to https://github.com/godotengine/godot-proposals/issues/2753
and https://github.com/godotengine/godot-proposals/issues/10770.*

### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

It's common for camera FOV (in 3D) or zoom (in 2D) to be dynamic in a game. For instance, racing games often increase FOV when the vehicle is moving quickly or when boost is used. Likewise, top-down games tend to decrease the camera zoom when the player moves so they can get a better view of their surroundings.

Since movement is performed in `_physics_process()` and the camera is updated on the physics step, changing FOV/zoom only takes place once per physics tick. This means that if the rendered FPS doesn't match the physics tick, the FOV/zoom change will appear to be jittery. If the FOV change is significant enough, this can make physics interpolation feel much worse than it should.

See this 120 FPS video where the project is configured to run at 20 physics ticks per second:

https://github.com/godotengine/godot-proposals/assets/180032/5258c844-3c32-43a8-84d4-5028e127be4f

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Interpolate camera FOV (3D) and zoom (2D) when using physics interpolation.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This should be easier to do now that camera interpolation is being moved to the scene side, including in the [4.x implementation of 3D physics interpolation](https://github.com/godotengine/godot/pull/92391).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This can be worked around by setting the FOV/zoom in `_process()` with the help of `Engine.get_physics_interpolation_fraction()` (by reading a member that is set in `_physics_process()`), but it's not trivial.

Considering this can make or break the appearance of physics interpolation in a game, it makes sense that this happens out of the box so users don't need to worry about it.

### Is there a reason why this should be core and not an add-on in the asset library?

Besides, there's also prior art of this with the InterpolatedCamera3D node in 3.x which not only interpolated FOV changes, but even Z near/far changes (although that aspect is probably not needed often).

### LINKED ISSUE #103025: Skeleton's deferred update process should be performed after physics interpolation
### Tested versions

- Reproduced in v4.4.beta4.official [93d270693]

### System information

Godot v4.4.beta4 - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti (NVIDIA; 32.0.15.6636) - 12th Gen Intel(R) Core(TM) i9-12900K (24 threads)

### Issue description

Enabling physics interpolation in project settings and following procedures to manually implement interpolation for camera movement ([trying to follow this](https://docs.godotengine.org/en/3.6/tutorials/physics/interpolation/advanced_physics_interpolation.html#mouse-look)) results in the SkeletonIK3D failing to have physics interpolation while moving and looking around, while everything else is smooth:

https://github.com/user-attachments/assets/0645a0ac-7f8b-48fe-a912-1e8695df23ec

It is noteworthy that disabling physics interpolation globally but keeping the manual implementation on the camera results in smooth ik movement when looking around but NOT while walking:

https://github.com/user-attachments/assets/bf066442-43d8-4549-9d8b-55cc49cd6035

It's entirely possible I am implementing this incorrectly, in which case, better documentation/information would be really helpful, as currently it seems unclear how to properly implement first person camera mouse movement with physics interpolation on high refresh monitors and inverse kinematics.

### Steps to reproduce

1. Enable physics interpolation globally and turn down the physics tick rate to 10 (so the effect is more clear)
2. Create a first person player with a camera child that is top level and has it's interpolation turned off, and manually implemented (see camera_3d.gd)
3. Using a rigged model (provided in the MRP) attach a skeletonIK3D node and put its target to a Marker3D node that is a child of the camera
4. Play the project and walk/look around

### Minimal reproduction project (MRP)

[firstpersontest.zip](https://github.com/user-attachments/files/18858802/firstpersontest.zip)

### LINKED ISSUE #103683: [4.4] BoneAttachment3D is lagging behind bone (regression from 4.3) if physics interpolation is enabled
### Tested versions

Reproducible in: 4.4.stable
Not reproducible in: 4.3.stable

### System information

Windows 10, Godot 4.4

### Issue description

BoneAttachment3D lags behind the bone slightly , more pronounced if manually setting or adjusting bone position ,but seems to happen universally
This is not visible if frame-stepping through the game in the "game" view, only pausing in the editor proper maintains this behaviour

This makes bone attachment for cosmetic reasons, like hair/equipment on characters basically unusable since causes constant clipping, happens only during physics interpolation
Image

### Steps to reproduce

Import a skeletal model, attach an object with a bone attachment, enable physics interpolation, play animation with fast movement (to make it properly visible) , observe slight lag

### Minimal reproduction project (MRP)

[boneattachmentbugtest.zip](https://github.com/user-attachments/files/19103988/boneattachmentbugtest.zip)

### LINKED ISSUE #103724: get_global_transform_interpolated() returns wrong transform after reset_physics_interpolation()
### Tested versions

- Reproducible in v4.4.stable.official [4c311cbee] and v4.4.beta3.official [06acfccf8]

### System information

Godot v4.4.stable - Windows 11 (build 26100) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 32.0.15.6636) - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 threads)

### Issue description

I am trying to have a non-interpolated mesh follow an interpolated mesh using get_global_transform_interpolated(), but after calling reset_physics_interpolation() on the interpolated mesh, get_global_transform_interpolated still returns transforms as if it wasn't reset and is interpolating

In this video you can see the green interpolated mesh being teleported correctly, but the red non-interpolated mesh being interpolated to the new position. Physics fps is set to 2 to make it more visible.

https://github.com/user-attachments/assets/461a5791-796c-4f54-8ff3-5dca3496498f

### Steps to reproduce

Press ui_accept to teleport the green interpolated mesh between a left and right position, and see the red non-interpolated mesh not teleporting, but interpolating to the new position

### Minimal reproduction project (MRP)

[physicsinterpolationbug.zip](https://github.com/user-attachments/files/19114894/physicsinterpolationbug.zip)

### LINKED ISSUE #104198: 3D Physics Interpolation: AnimationPlayer causes instance_set_transform warning when animating the position of a physics-interpolated node
### Tested versions

Reproducible in 4.4.stable

### System information

Godot v4.4.stable.mono - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 32.0.15.6636) - Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 threads)

### Issue description

If physics interpolation is enabled, animating a Node3D's position with an AnimationPlayer causes the following warning to appear roughly every 15 seconds:
`W 0:00:15:015   instance_set_transform: [Physics interpolation] Interpolated instance triggered from outside physics process: "/root/Node3D/Cube" (possibly benign).
  <C++ Source>  servers/rendering/renderer_scene_cull.cpp:1032 @ instance_set_transform()`

This is happening because AnimationPlayer's `callback_process_mode` defaults to "Idle", which is equivalent to moving the object during `_process()` instead of `_physics_process()`.  While that would normally be ill-advised, I would expect an exception to be made in the case of AnimationPlayer; after all, if the user is animating `position`, then they obviously want the animator to handle any interpolation.

There are workarounds to make this warning go away, but they all have unacceptable downsides.

### Workaround 1:  Set the callback mode to "Physics".
This is the "obvious" solution, but it has a lethal drawback: it makes skeleton animations look choppy, since armatures aren't affected by physics interpolation.  See `WhyCallbackModeIsBadFix.tscn` in my example project for a demonstration.

### Workaround 2: Disable physics interpolation for the object being animated.
This doesn't work if the object's _parent_ is using physics interpolation, since [3D physics interpolation is performed on the _global_ transform instead of the _local_ one](https://docs.godotengine.org/en/4.4/tutorials/physics/interpolation/2d_and_3d_physics_interpolation.html).  If you try this, then the object being animated will appear to jitter, since its parent is being interpolated but it itself isn't.  See `WhyDisablingInterpolationIsBadFix.tscn` for a demonstration.

### Workaround 3: Don't animate a node's position.  Ever.
Or its rotation.  Or its scale.  This is only an option for models with a skeleton.  If you're animating something _without_ a skeleton, you're out of luck.

### Workaround 4: Ignore the warning, embrace chaos
This is what I'm currently doing.  It's making me warning-blind, though.

### Steps to reproduce

1. Create a Node3D
2. Animate its `position` with a looping AnimationPlayer
3. Turn on physics interpolation
4. Wait 15 seconds.  The warning will appear.

### Minimal reproduction project (MRP)

[AnimatorPhysicsInterpBug.zip](https://github.com/user-attachments/files/19266223/AnimatorPhysicsInterpBug.zip)

### LINKED ISSUE #104290: Godot 4.4 3D physics interpolation causes gridmap flickering
### Tested versions

Godot 4.4 beta 1 mono version
Godot 4.4 beta 3 mono version
Godot 4.4 mono version
Godot 4.4 RC1 mono version

### System information

Godot v4.4.1.rc1.mono - Windows 11 (build 22631) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated Radeon RX Vega (Advanced Micro Devices, Inc.; 31.0.21921.1000) - AMD Ryzen 9 3900X 12-Core Processor (24 threads)

### Issue description

I'm using GridMap in my 3D isometric turn-based game for some part of the gameplay, like for example the fights. I display a basic grid map with cells and I use the GridMap function set_cell_type to change cell color/effect during the fight. When 3D physics interpolation is disabled, everything works correctly.

When I enable 3D physics interpolation, i have some weird issues:

Image

Note: this bug only happen when grid map is not positioned at 0, 0, 0. When its at the center of the map, it works. But my fight maps in my game are not at 0, 0, 0 unfortunately. That was working well with Godot 4.3 and with Godot 4.4 when 3D physics interpolation is disabled.

### Steps to reproduce

- Open the project
- Run main scene
- Move mouse around white cells, they are supposed to become red using SetCellType
- You should see weird flickering

Then: 

- Disable 3D physics interpolation
- Redo steps above
- No flickering

### Minimal reproduction project (MRP)

[DebugGridMap.zip](https://github.com/user-attachments/files/19299749/DebugGridMap.zip)

### PR DESCRIPTION
**Pull request by lawnjelly**
Moves 3D interpolation from server to the client code (`SceneTree`). Complete rework of 3D physics interpolation, but using the same user API.

Forward port of #103685
Also includes forward port of #104854 and #104888 and #104920 and #105141 and #105463

Fixes #103683
Fixes #104198
Fixes #103724
Fixes #103025
Fixes #104290

- *Production edit: This closes https://github.com/godotengine/godot-proposals/issues/9964.*

Fixes IK with root motion, Wheels, Pivot relationships, OFF branches
Adds `InterpolatedProperty`
Adds Interpolated properties for `Camera3D`

This should bring master up to date with the improvements to 3D physics interpolation in 3.x.

https://github.com/user-attachments/assets/a42b8e75-a27e-4a93-bc87-d015f71beb50

There are a number of near-insurmountable problems with the old server based 3D interpolation design. These were [identified at an early stage as a likely outcome ](https://x.com/MelindaHoward4/status/1847297586803208366) . The main problems with the old design come from the assumption that scene side would not require access to interpolated xforms (these cannot be retrieved from the server due to the multithread design, command queue and stalling). However, in practice many scene nodes have proven to require access to interpolated xforms in order to work, see the various bugs reported. In practice this leaves us little option but to abandon the server based design for 3D.

Luckily, moving FTI scene side in this PR makes everything conceptually easier for maintainers and users, and should make bug fixing, and interpolation of new properties and nodes far simpler in the future.

* API compatible / backward compatible with old system
* Solves a large number of bugs with complex cases
* Much easier user experience with `physics_interpolation_mode` OFF branches
* Accurately renders scene tree pivot relationships

Adds a `SceneTreeFTI` class with the intention of being used by third parties that write their own custom `SceneTree`, so 
even custom versions of Godot can easily integrate FTI. Note this currently requires deriving from `SceneTree`. (_If there is evidence that projects deriving from `MainLoop` require this functionality we can change the access to `SceneTreeFTI` to allow this, but this should probably be based on evidence for a need because there may be some costs or bug potential._)

## Notes
* This is now a somewhat large PR but it contains nearly all the work and bug fixes to 3.x (barring the small XR changes which I will likely leave to @Asaduji as I can't test XR as I don't have the appropriate hardware).

## Two passes
There is a chicken egg problem with `get_global_transform_interpolated()`. Ideally we want to concatenate scene tree xforms to calculate interpolated versions _once_ after idle and immediately prior to rendering. _However_ that would mean getting the interpolated xform during `idle` would be at best one frame out of date.

The solution to that is some clever management. First of all we do a pass _before_ idle. This ensures that any initial calls to `get_global_transform_interpolated()` are up to date. When we change node xforms during idle, as part of the normal propagate we add a `DIRTY_GLOBAL_INTERPOLATED` flag to those altered nodes.

Then during the second pass, we refresh _only those nodes_ that have this flag set. Thus we minimize any recalculation of moved nodes.

Strictly speaking we also can make subsequent calls to `get_global_transform_interpolated()` correct as to previous calls which may have set transforms during idle. This can be done by checking the dirty flag, and recalculating any dirty chains. I'm not sure yet whether this will be necessary.

## Discussion
See #103685

Note that this PR includes a minor fix to `CPUParticles` but `CPUParticles` physics interpolation has not been completely forwarded ported yet so constitutes a "work in progress".
`GPUParticles` does seem to work fine though with physics interpolation after this PR.

### CODE REVIEW

**Comment by lawnjelly** [comment]
I've added a proof of concept draft #104518 for giving users the ability to still use physics interpolation when using servers directly - to address any concerns that these users might be losing out.

They won't lose out, we can support this use case too fairly easily. :+1: 

This is a considerably simpler requirement than for scene tree interpolation.

Note that it doesn't make sense to combine the two PRs, as they work completely independently (and #104518 will benefit from further bikeshedding to ensure we are happy with the user interface / method, as I say in the PR there are several ways of doing it).

**Review by Calinou — COMMENTED** [review]
Tested locally on all 3D demos from godot-demo-projects at 20 TPS, it works as expected on those demos.

However, on the TPS demo, this causes graphical glitches with shadows not present on `master` with the PR's commit locally reverted:

Image

Image

There are many clustering artifacts and shadow maps have missing elements in them.

<details open>

<summary>PC specifications</summary>

- **CPU:** Intel Core i9-13900K
- **GPU:** NVIDIA GeForce RTX 4090
- **RAM:** 64 GB (2×32 GB DDR5-5800 C30)
- **SSD:** Solidigm P44 Pro 2 TB
- **OS:** Linux (Fedora 41)
</details>

**Comment by lawnjelly** [comment]
Great, thanks @Calinou . :+1: 

I'll check out TPS demo tommorrow and see if I can figure what's going on, it could just be a line I missed from the forward port.

**Review by Calinou — COMMENTED** [review]
Works great now!

I noticed one issue with particles interpolation in the TPS demo though (which didn't occur in `master`). When you fire a bullet, the particles will create a streak between a fixed position in the world and the bullet's initial position:

https://github.com/user-attachments/assets/45d8230c-c184-4900-8981-65feba38b696

This may be a game code issue that's highlighted by the PR, but it didn't happen before (I've double-checked it).

**Comment by lawnjelly** [comment]
> I noticed one issue with particles interpolation in the TPS demo though (which didn't occur in master). When you fire a bullet, the particles will create a streak between a fixed position in the world and the bullet's initial position:

I'll take a look, this sounds like it was maybe being auto-reset before and not now. Haven't been able to see details like this as TPS demo runs at quite a low frame rate for me. :grin:

**Review by Calinou — APPROVED** [review]
Tested again on TPS demo, 3D platformer and Truck Town, it works as expected. The particle streaking issue is fixed.

Camera FOV is now interpolated in Truck Town as well. Here's what it looks like at 10 TPS:

https://github.com/user-attachments/assets/0b9b7ba6-8a16-4ba0-a5db-00399aca745c

This seems to already be the case in 2D in `master`, but not in 3D. Therefore, this PR now fully addresses https://github.com/godotengine/godot-proposals/issues/9964.

**Comment by lawnjelly** [comment]
Rebased now that #105437 is merged, and added hook to call `instance_teleport()` to reset motion vectors.

**Comment by Calinou** [comment]
I tested this PR again and I noticed that VehicleWheels are no longer interpolated with it (both the wheel rotation and suspension). This means https://github.com/godotengine/godot/issues/72207 is fixed, but wheels will appear to update at a reduced rate according to the physics FPS. It's not too noticeable if you use untextured wheels, but it's definitely noticeable with detailed wheel models/textures.

**Comment by lawnjelly** [comment]
The problems with wheels are described here as "phasing" and "throbbing":
https://github.com/godotengine/godot/pull/52846#issuecomment-979811468
https://github.com/godotengine/godot/pull/52846#issuecomment-980526067

This PR makes the default `physics_interpolation_mode` OFF for wheels (which I'm getting the impression most users were doing manually for this problem). To get the old behaviour you can simply change the `physics_interpolation_mode` back to `INHERIT` in the inspector (or via script).

We have the *potential* to solve this properly now we have interpolation off. This was discussed in a rendering meeting some time ago (a year or 2 I think) but the crux of the problem is that the interpolation (currently) only has available a previous and current basis in order to calculation interpolation.

A basis can only encode a rotation between 0 and 360 degrees, thus if we need to rotate at 180-360 degrees per tick, we have a problem - the interpolation will choose the shortest arc, and will thus interpolate _backwards_. At 360-540 degrees per tick it will again interpolate forwards, but _slower_ than it should move in reality. This is described as "phasing" in the post.

The problem of only having a basis available was especially acute with the previous `VisualServer` solution, but now we are doing FTI in the scene code, we have the potential to add bespoke solutions for wheels and objects rotating faster than 180 degrees per tick.

This would have to be investigated later, it's a somewhat tangential problem to general FTI. For now the best compromise for wheels is probably to either keep FTI off, or to alternate between on and off depending on wheel speed. Again this latter would require bespoke code.

File: scene/3d/visual_instance_3d.cpp [hunk 1]
```diff
@@ -77,6 +73,11 @@ void VisualInstance3D::set_instance_use_identity_transform(bool p_enable) {
 	}
 }
 
+void VisualInstance3D::fti_update_servers_xform() {
+	if (!_is_using_identity_transform()) {
+		RS::get_singleton()->instance_set_transform(get_instance(), _get_cached_global_transform_interpolated());
+	}
+}
 void VisualInstance3D::_notification(int p_what) {
```
Comment (AThousandShips) [inline scene/3d/visual_instance_3d.cpp:81]:
```suggestion

void VisualInstance3D::_notification(int p_what) {
```

File: scene/main/scene_tree_fti.cpp [hunk 2]
```diff
@@ -0,0 +1,475 @@
...
+			s->data.global_transform_interpolated = local_interp;
+		}
+
+		// Watch for this, disable_scale can cause incredibly confusing bugs
+		// and must be checked for when calculating global xforms.
+		if (s->data.disable_scale) {
+			s->data.global_transform_interpolated.basis.orthonormalize();
+		}
+
+		// Upload to VisualServer the interpolated global xform.
```
Comment (rburing) [inline scene/main/scene_tree_fti.cpp:408]: While at it with the style comments:

```suggestion
		// Upload to RenderingServer the interpolated global xform.
```

**Review by rburing — APPROVED** [review]
Looks like a correct forward-port from what I can tell.

File: doc/classes/RenderingServer.xml [hunk 3]
```diff
@@ -1931,14 +1931,6 @@
 				Sets the visibility range values for the given geometry instance. Equivalent to [member GeometryInstance3D.visibility_range_begin] and related properties.
 			</description>
 		</method>
-		<method name="instance_reset_physics_interpolation">
```
[the remark this answers is not in the document]
Comment (lawnjelly) [reply doc/classes/RenderingServer.xml:1934]: Yeah, but I suspect that's probably likely to be for the best in the long run.

Users should fix their scripts up using 4.5, this technique will no longer work (at all, physics interpolation no longer works by calling the server directly), and it's better to alert users to this sooner than have it fail silently imo.

Scripts using servers directly for 3D FTI with the 4.4 method and the 4.5 onward method won't be compatible, there's no way around this, or swapping projects between the two without change.

**Comment by lawnjelly** [comment]
Lots more goodies coming after this BTW, I've considerably optimized the system since in #105728 and #105681 (should be 2-10x faster), but those are best left for followups.

Had a look at the wheel code and it does seem to receive rotational velocity from the physics, so it may be simple to fix up a bespoke bit of code to handle fast rotating wheels.

Also we can interpolate more properties such as light parameters.

**Comment by Repiteo** [comment]
Thanks!
