### PR TITLE
[Shaders] Allow constants and expressions in `hint_range`

### LINKED ISSUE #101926: hint_range emit wrong error
### Tested versions

- Reproducible in v4.3.stable.mono.official [77dcf97d8]

### System information

Apple M1 Pro, Sequoia 15.2

### Issue description

hint_range with a non literal value produce the error:  `Expected an integer constant after!.`

hint_range works with floats but does not work with constants, so the error should most likely be `Expected a literal after`.

### Steps to reproduce

In any shader, add a line:

```glsl
uniform float foo : hint_range(1.1, PI) = 0.0;
```
However if you just specify a float, it compiles with no errors:

```glsl
uniform float foo : hint_range(1.1, 2.2) = 0.0;
```

### Minimal reproduction project (MRP)

It is easily reproducible. Let me know if it is absolutely necessery.

### PR DESCRIPTION
**Pull request by Chaosus**
Allows expressions in `hint_range` declaration:

```glsl
shader_type spatial;

const float begin = 0.5;
const float end = 4.0;
const float st = 0.1;

uniform float test : hint_range(begin, end);
uniform float test2 : hint_range(0.25 + 0.25, TAU + 1.0, st);
```

- Fix https://github.com/godotengine/godot/issues/101926

### CODE REVIEW

File: servers/rendering/shader_language.cpp [hunk 1]
```diff
@@ -9061,6 +9064,51 @@ Error ShaderLanguage::_validate_precision(DataType p_type, DataPrecision p_preci
 	return OK;
 }
 
+bool ShaderLanguage::_parse_hint_range_constant(const FunctionInfo &p_constants, float &r_constant) {
+	ShaderLanguage::Node *expr = _parse_and_reduce_expression(nullptr, p_constants);
+	if (expr == nullptr || (expr->type != Node::NODE_TYPE_CONSTANT && expr->type != Node::NODE_TYPE_OPERATOR && expr->type != Node::NODE_TYPE_VARIABLE)) {
+		_set_error(RTR("Expected an integer expression after ','."));
```
Comment (AThousandShips) [inline servers/rendering/shader_language.cpp:9070]: "Integer" doesn't seem correct if it accepts a general real here, this would be misleading in cases where you provide something that isn't an expression but the value is allowed to be non-integer

Comment (Chaosus) [reply servers/rendering/shader_language.cpp:9070]: `Expected a valid numeric expression after ','.` is fine?

Comment (AThousandShips) [reply servers/rendering/shader_language.cpp:9070]: Should be, what is the error for example after a declaration like `int x = `?

Comment (Chaosus) [reply servers/rendering/shader_language.cpp]: Expected expression: found 'SYMBOL`

**Comment by maxpiepenbrink** [comment]
big fan of this

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected.

Code looks good to me.

For reference, this is already allowed in GDScript.

File: servers/rendering/shader_types.cpp [hunk 2]
```diff
@@ -52,16 +52,29 @@ static ShaderLanguage::BuiltInInfo constt(ShaderLanguage::DataType p_type) {
...
 	/*************** SPATIAL ***********************/
 
+	ShaderLanguage::Scalar pi_scalar;
+	pi_scalar.real = Math_PI;
+
+	ShaderLanguage::Scalar tau_scalar;
+	tau_scalar.real = Math_TAU;
+
+	ShaderLanguage::Scalar e_scalar;
+	e_scalar.real = Math_E;
```
Comment (Repiteo) [inline servers/rendering/shader_types.cpp:71]:
```suggestion
	ShaderLanguage::Scalar pi_scalar;
	pi_scalar.real = Math::PI;

	ShaderLanguage::Scalar tau_scalar;
	tau_scalar.real = Math::TAU;

	ShaderLanguage::Scalar e_scalar;
	e_scalar.real = Math::E;
```

Comment (Chaosus) [reply servers/rendering/shader_types.cpp]: Fixed

**Comment by Repiteo** [comment]
Thanks!

**Comment by geekley** [comment]
The hints `instance_index` and `hint_enum` also accept parameters. Should we assume they may eventually allow expressions or at least named constants as well?
I guess not with `hint_enum`, since only strings are allowed, and we can't set those in constants (except for macros).
But what about `instance_index`?
