### PR TITLE
C#: Remove VariantSpanDisposer and use constants in stackalloc

### LINKED ISSUE #67263: application crash with "corrupted double-linked list"
### Godot version

4.0 beta 2 mono

### System information

Ubuntu 22.04.1 / GTX 960 / Vulkan

### Issue description

Godot application (not editor) crashes with either "corrupted double-linked list" or "malloc(): smallbin double linked list".

Here is the output from the console (2 different occurrences)

`Godot Engine v4.0.beta2.mono.official.f8745f2f7 - https://godotengine.org
Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 960
libdbus-1.so: cannot open shared object file: No such file or directory
libdbus-1.so: cannot open shared object file: No such file or directory
 
ERROR: Condition "!d.has("handle_modes")" is true. Returning: false
   at: _set (scene/resources/animation.cpp:319)
ERROR: Condition "!d.has("handle_modes")" is true. Returning: false
   at: _set (scene/resources/animation.cpp:319)
WARNING: res://Scripted agents/Systems3D/Guns/Gettling/Gettling.tscn:4 - ext_resource, invalid UUID: uid://dabx56bsjisvu - using text path instead: res://Scripted agents/Systems3D/Guns/Gettling/GettlingTurret.tscn
     at: load (scene/resources/resource_format_text.cpp:448)
WARNING: res://Scripted agents/Systems3D/Guns/Gettling/GettlingTurret.tscn:10 - ext_resource, invalid UUID: uid://6m0p06s5bt5v - using text path instead: res://Graphics/materials/exhaust_process_shader.tres
     at: load (scene/resources/resource_format_text.cpp:448)
malloc(): smallbin double linked list corrupted
Aborted (core dumped)`

sometimes that second last line is `corrupted double-linked list`

### Steps to reproduce

Despite how often it happens, the bug is hard to reproduce and happens at will It seams however, that it always triggers on Signal Emission in C#. I have also tried and failed to reproduce this in a smaller project.

### Minimal reproduction project

_No response_

### LINKED ISSUE #68590: Failed to unload assemblies when loading an Array of Resource
### Godot version

v4.0.beta.mono.custom_build [f814e15c7]

### System information

Arch Linux

### Issue description

My C# plugin is loading an array of Resources.
It prevents assemblies from reloading when I recompile.

```
Unloading assembly load context...
Assembly unloading is taking longer than expected...
Failed to unload assemblies. Possible causes: Strong GC handles, running threads, etc.
ERROR: .NET: Failed to unload assemblies.
   at: reload_project_assemblies (modules/mono/mono_gd/gd_mono.cpp:504)
ERROR: Condition "delegate_handle.value == nullptr" is true.
   at: call (modules/mono/managed_callable.cpp:92)
ERROR: Can't get method on CallableCustom "Delegate::Invoke".
   at: get_method (core/variant/callable.cpp:333)
ERROR: Error calling from signal 'timeout' to callable: 'Node::': Method not found..
   at: emit_signalp (core/object/object.cpp:1057)
```

The console is then flooded with infinite messages of the nullptr exception.

In the provided repro, I use a Texture2D to trigger the bug but any kind of Resource seems to have the same behavior (Gradient, etc).
The most specific repro I could find is: `CustomResource` -> `Array<CustomResource2>` -> `Texture2D`

### Steps to reproduce

```CSharp
#if TOOLS
using Godot;

[Tool]
public partial class myplugin : EditorPlugin
{
    public override void _EnterTree()
    {
        var libResource = ResourceLoader.Load<LibResource>("res://myResource.res");
    }
}
#endif
```

```CSharp
[Tool]
public partial class LibResource : Resource
{
    [Export] public Array<LibEntry> Entries { get; set; }
}
```

```CSharp
[Tool]
public partial class LibEntry : Resource
{
    [Export] public Texture2D Preview { get; set; }
}
```

### Minimal reproduction project

https://github.com/geowarin/ReloadBug

[ReloadBug-main.zip](https://github.com/godotengine/godot/files/9996345/ReloadBug-main.zip)

### PR DESCRIPTION
**Pull request by raulsntos**
- Remove `VariantSpanDisposer`, no need to dispose of the Variant Spans since we are now borrowing the Variants them instead of copying them.
- Fix stackalloc Spans to use constant VarArgsSpanThreshold and avoid bound checks.
- Fixes https://github.com/godotengine/godot/issues/67263.
- Fixes https://github.com/godotengine/godot/issues/68590.

May fix:
- https://github.com/godotengine/godot/issues/66174
- https://github.com/godotengine/godot/issues/67460
- https://github.com/godotengine/godot/issues/67563
- https://github.com/godotengine/godot/issues/68148
- https://github.com/godotengine/godot/issues/68329
- https://github.com/godotengine/godot/issues/68849

### CODE REVIEW

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Callable.cs [hunk 1]
```diff
@@ -131,12 +129,10 @@ public unsafe void CallDeferred(params Variant[] args)
                 stackalloc godot_variant.movable[VarArgsSpanThreshold].Cleared() :
                 new godot_variant.movable[argc];
 
-            Span<IntPtr> argsSpan = argc <= 10 ?
-                stackalloc IntPtr[argc] :
+            Span<IntPtr> argsSpan = argc <= VarArgsSpanThreshold ?
+                stackalloc IntPtr[VarArgsSpanThreshold] :
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Callable.cs:133]: The `VarArgsSpanThreshold` constant has a value of `5` in `Callable`, but `10` in code generated by bindings_generator. Not sure why they are different and maybe we should consider declaring this constant in a single place and reuse it rather than redefine it in every file.

Comment (neikeq) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Callable.cs:133]: It's weird that I added `VarArgsSpanThreshold` here but used a hard-coded value instead. It's obviously a mistake, but I don't know which one I truly wanted. I think `10` should be fine for both.

**Comment by geowarin** [comment]
This also fixes #68590 were custom resources with an array of variants would prevent successful reloading of the c# assemblies.
Great work!

**Review by neikeq — APPROVED** [review]

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Callable.cs (hunk 1 above)
Comment (raulsntos) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Callable.cs:133]: I'll change it to `10` in this PR and we can move the constant to a single place later.

**Comment by neikeq** [comment]
Thanks!
