### PR TITLE
Fix leak when using audio samples instead of streams

### LINKED ISSUE #96068: Audio samples leaks
### Tested versions

- Reproducible in 4.3-stable, 4.3beta2, and 4.3beta3
- Does not occur in 4.3beta1, or 4.2.2-stable

### System information

Godot v4.3.stable - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.5161) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Playing an AudioStream in a web build in 4.3 causes objects to be created that are not freed. A windows build of the same code doesn't cause the same leaks. I could not reproduce this with 4.3beta1, only the release 4.3 build (v4.3.stable.official [77dcf97d8]).

In games with lots of audio, this will lead to an eventual crash when the object count gets too high for the wasm/webgl buffer code to handle.

### Steps to reproduce

Create any kind of AudioStream node, and call `play` on it.
On web, the object count goes up and never goes back down. Check using `Performance.OBJECT_COUNT`.

### Minimal reproduction project (MRP)

MRP: [web-leak-repro.zip](https://github.com/user-attachments/files/16740338/web-leak-repro.zip)

I've uploaded this to itch here with debug symbols and gdscript as text: https://blambear.itch.io/godot-web-audio-leak-bug the password is `godot`.

You can see the object count keep going up and up.

(Note the pop.mp3 file in here is an audio file I recorded, it's MIT licensed)

### PR DESCRIPTION
**Pull request by adamscott**
Fixes #96068 

The issue was caused by the fact that the `Ref<AudioStreamPlayback>` deletion from `AudioServer::playback_list` was done in the `AudioServer::_mix_step()` function. When a stream was replaced, it was tagged to be faded out. And when the fading was done, it was promptly deleted/unreferenced.

The thing is that samples never trigger `_mix_step()`, thus never clearing those references.

I now implemented the deletion in a function that `_mix_step()` calls and that `AudioServer::stop_playback_stream()` calls too. The later calls it if the stream is stopped, flagged as containing a sample, and that it's reference to the sample is `nullptr`.

### CODE REVIEW

File: servers/audio_server.h [hunk 1]
```diff
@@ -297,6 +297,8 @@ class AudioServer : public Object {
 
 	SafeList<AudioStreamPlaybackListNode *> playback_list;
 	SafeList<AudioStreamPlaybackBusDetails *> bus_details_graveyard;
+	void _delete_stream_playback(Ref<AudioStreamPlayback> p_playback);
+	void _delete_stream_playback_list_node(AudioStreamPlaybackListNode *p_node);
```
Comment (akien-mga) [inline servers/audio_server.h:301]: Nitpick, but usually we define private methods after the block of private variables.

Comment (adamscott) [reply servers/audio_server.h:301]: I suggest that we merge this PR, then I'll create a new one reorganizing the mess that is the `AudioServer` class.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.
