### PR TITLE
Don't try to merge unused bone AABBs in the rendering server

### LINKED ISSUE #56458: Warnings "AABB size is negative" when importing glTF file with zero-weight bones
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

master (937fb63a)

### System information

Windows 10

### Issue description

I'm seeing a lot of "AABB size is negative" spam when importing a glTF file with a skeleton, because some bones have zero weights (non-deform bones) and have an "empty" AABB. `RendererStorageRD::mesh_add_surface` still tries to merge them with the mesh AABB.

```
		for (int i = 0; i < p_surface.bone_aabbs.size(); i++) {
			mesh->bone_aabbs.write[i].merge_with(p_surface.bone_aabbs[i]);
		}
		mesh->aabb.merge_with(p_surface.aabb);
```

This is caused by the recent addition of warnings in `AABB::merge_with`: #37626
I have a tentative fix by just checking if both AABBs are valid ("has_no_volume"), but not sure if that's a proper solution. I agree with commenters that these warnings should not be issued for a valid case like this.

```
		for (int i = 0; i < p_surface.bone_aabbs.size(); i++) {
			if (p_surface.bone_aabbs[i].has_no_volume()) {
				continue;
			}
			if (mesh->bone_aabbs.write[i].has_no_volume()) {
				mesh->bone_aabbs.write[i] = p_surface.bone_aabbs[i];
			} else {
				mesh->bone_aabbs.write[i].merge_with(p_surface.bone_aabbs[i]);
			}
		}
		mesh->aabb.merge_with(p_surface.aabb);
```

### Steps to reproduce

1. Open the attached project
2. Select the _Beetle.glb_ file in the asset browser
3. Open the _Import_ tab
4. Click the _Reimport_ button

### Minimal reproduction project

[BoneAABBWarnings.zip](https://github.com/godotengine/godot/files/7801265/BoneAABBWarnings.zip)

### PR DESCRIPTION
**Pull request by aaronfranke**
This PR fixes #56458. With this PR, the test project works, I can import the beetle car GLB without any errors.

I had investigated this half a year ago and was hoping that someone from rendering could confirm this was the correct fix. However, after thinking it over, I am fairly confident that this is indeed the correct fix.

### CODE REVIEW

**Comment by lawnjelly** [comment]
Partly I hadn't commented because I'm not familiar with the pipeline for bones in 3d in godot, especially in 4.x.

Ideally it would probably be nice to mark bones as unused in another way (like passing some bitflags or something), but I suspect the original author thought this might be an easy way of stopping some problem at the time (just making size negative). They are probably essentially hacking in this bool into the AABB, either to make the API smaller and simpler, save typing etc, which might be okay to continue this approach, or might not.

There are two potential downsides that jump out:
1) Could there be legit negative AABBs as a result of bones being mirrored in the skeleton (I don't know, no idea where the AABB calculation code is)
2) Checking no volume is not as cheap as say, checking a bool or bitflag. But then again it's not super expensive, and unless it appears on a profile probably isn't worth worrying out

So I guess providing (1) doesn't seem to occur (I would check this code rigorously) this might not be bad just to fix the current bug, then see if any more appear. If there are knock bugs you could consider something else.

**Comment by YuriSizov** [comment]
cc @clayjohn

**Comment by reduz** [comment]
This makes sense to me (I will approve)

**Review by reduz — APPROVED** [review]

**Review by clayjohn — APPROVED** [review]
Looks good to me too

File: drivers/gles3/storage/mesh_storage.cpp [hunk 1]
```diff
@@ -255,7 +255,10 @@ void MeshStorage::mesh_add_surface(RID p_mesh, const RS::SurfaceData &p_surface)
 			mesh->bone_aabbs.resize(p_surface.bone_aabbs.size());
 		}
 		for (int i = 0; i < p_surface.bone_aabbs.size(); i++) {
-			mesh->bone_aabbs.write[i].merge_with(p_surface.bone_aabbs[i]);
+			AABB bone = p_surface.bone_aabbs[i];
+			if (!bone.has_no_volume()) {
+				mesh->bone_aabbs.write[i].merge_with(p_surface.bone_aabbs[i]);
+			}
```
Comment (lawnjelly) [inline drivers/gles3/storage/mesh_storage.cpp:261]: Sorry to only notice this just after merging, but should it be:
```
const AABB &bone = p_surface.bones_aabbs[i];
```
for a const reference rather than copying the AABB?

And then using `bone` directly in the next line:
```
mesh->bone_aabbs.write[i].merge_with(bone);
```
It is possible the optimizer might optimize this out, but there seems to be little point in copying by value here.

And same in the 2nd section below.

Comment (Calinou) [reply drivers/gles3/storage/mesh_storage.cpp:261]: > It looks like the name for this optimization is copy elision:

C++17 has guaranteed copy elision. Since Godot uses C++17 in `master`, does this address the issue?

Comment (lawnjelly) [reply drivers/gles3/storage/mesh_storage.cpp:261]: I wouldn't rely on anything like that, especially in hot loops. :grin:

Be explicit in what you are asking the compiler to do, and you won't go far wrong. If you are vague, be prepared to examine the assembly. Which will take 10x as long as just writing it correctly in the first place.

Comment (aaronfranke) [reply drivers/gles3/storage/mesh_storage.cpp:261]: Ah, I completely forgot about using `bone` on the next line. And yeah, I'll update the code to have the AABB a const ref.

**Comment by permelin** [comment]
I have models that still get "AABB size is negative". The problem is that the object that `merge_with()` is called on is (-1, -1, -1) while this fix only checks if the the **argument** has no size. Is this a different bug?

I can try to create a minimal GLB if it helps.

**Comment by aaronfranke** [comment]
@permelin Yes, a new test GLB would be helpful. The test project in the linked issue was fixed with this PR.

**Comment by permelin** [comment]
@aaronfranke Here it is. It admittedly looks a bit weird, but I started with a humanoid character and reduced it down as much as I could while keeping the error.

Let me know if I should create a new issue.

[godot_negative_aabb_minimal.zip](https://github.com/godotengine/godot/files/9376345/godot_negative_aabb_minimal.zip)
