### PR TITLE
Fix EditorProperty shortcuts being global and unintentionally triggering

### LINKED ISSUE #88234: Ctrl+C and Ctrl+V shortcuts are broken, they apply to the wrong tab
### Tested versions

v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3623) - AMD Ryzen 5 2600X Six-Core Processor (12 Threads)

### Issue description

When I try to use Ctrl+C and Ctrl+V to copy and paste an object in my scene, it instead for some reason pastes an option in the `Import` tab.

- I do not have the `Import` tab open, I have the `Scene` tab open.
- I do not even have something selected in the `FileSystem` tab which would show up in the `Import` tab when I switch to it.
- But nonetheless I get `Set meshes/force_disable_compression` in the output when trying to Ctrl+C and Ctrl+V, which was the most recent setting I changed in the `Import` tab before moving on to other tasks.

Using the right click menu and selecting `Copy` and then selecting `Paste` works as intended. For some reason it is just the keyboard shortcut which is broken.

### Steps to reproduce

1. change a setting in the `Import` tab
2. try to copy something in the `Scene` tab
3. it will do nothing and the output will show that it just affected whatever setting you changed in the `Import` tab.

### Minimal reproduction project (MRP)

Open a brand new project and follow the steps. Change some setting of icon.svg and now you cannot Ctrl+C Ctrl+V in the `Scene` tab

### LINKED ISSUE #99524: `CTRL+C` and `CTRL+V` of `EditorProperty::shortcut_input` hide shortcuts of `SceneTreeDock`
### Tested versions

- Reproducible in 4.4.dev5, 4.4.dev4

### System information

Windows 11 - Godot v4.4.dev5 - Windows 10.0.22631 - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 32.0.15.6094) - 13th Gen Intel(R) Core(TM) i5-13600KF (20 threads)

### Issue description

1. Click a node in SceneTreeDock
2. Click a property name of the node in Inspector
3. Click this node in SceneTreeDock agian (can click on the icon or hide button to avoid renaming)
4. CTRL+C
5. CTRL+V (will notice there is a message in output and the node is not duplicated)

https://github.com/user-attachments/assets/499da9a0-f248-426e-a873-1abf0adf4d67

### Steps to reproduce

See above

### Minimal reproduction project (MRP)

NA

### LINKED ISSUE #104313: Can't paste node if import dock gets focus
### Tested versions

4.5.dev

### System information

Godot v4.5.dev.mono  - EndeavourOS  SMP PREEMPT_DYNAMIC Fri, 07 Mar 2025 20:19:00 +0000 on Wayland - X11 display driver, Multi-window, 1 monitor - Vulkan (Mobile) - integrated AMD Radeon Graphics (RADV RENOIR) - AMD Ryzen 7 4800U with Radeon Graphics (16 threads)

### Issue description

Can't paste node if import dock gets focus.
In the video, after the import dock gets focus, I try to paste node by `Ctrl+V` but the console shows I'm setting roughness mode. Unless I resatrt the editor.

https://github.com/user-attachments/assets/5f0031c7-cae1-41b8-9ae4-3aec4197418d

### Steps to reproduce

Click import dock to focus it, then you can't copy&paste node.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by EricEzaM**
Hi again, it's been a while.

See my comment here for further context: https://github.com/godotengine/godot/pull/104366#issuecomment-2745278021

Fixes #104313
Fixes #99524
Fixes #88234

In addition to my above comment, if you whack a breakpoint down and look at `resolved_nodes_without_context`, it contains a list of all nodes without a "context", i.e. global. May want to review which of these should actually be global. Note that this list will change as different parts of the editor are loaded, if context has not been set. The list in the pic below are just from initial load.

image

Note that the changes to `SceneTree` are optional I think. They are an improvement on the default behaviour (somewhat), but if there are still shortcuts unintentionally being registered as global then it does nothing to stop them from being triggered.

I'll also specifically quote part of my comment from above to possibly drive further discussion about this feature (might warrant an issue/proposal):
> I think part of the problem with the "shortcut context" system is that by default, every single node will have its shortcut_input be global unless it opts-in to the context system by using set_shortcut_context. This means if someone forgets to use set_shortcut_context when writing some UI, the shortcuts can be pretty messed up since everything is considered global.

>This doesn't seem like it is leading developers to the "pit of success". I'm not sure if there is a good way to fix it, but perhaps the logic should somehow be flipped so that being a global shortcut is opt-in. In this scenario, by default all controls would essentially have set_shortcut_context(this) in their constructor. That could be overridden on a case-by-case basis to give shortcuts a larger scope.

### CODE REVIEW

**Comment by EricEzaM** [comment]
https://github.com/user-attachments/assets/69ba4529-9af6-4497-9400-af42bd96623b

**Comment by beicause** [comment]
Can this fix issue #103345?

**Comment by EricEzaM** [comment]
@beicause unfortunately that is a little bit more complex. Not sure if it can be solved easily, let me explain:

When a shortcut input is made, **all** `EditorProperty` instances receive it via `shortcut_input`, then they themselves determine if they should activate if `selected == true`.

When sub-insepctors are used, it appears that only the `root` inspector is what has the Viewport `gui_focus`, even if you click into a sub-inspector. That is why in this PR we get the `root_inspector`, since it is what will have focus. It means that essentially multiple `EditorProperty` instances have `selected == true` and receive the input (since they are in the shortcut context), so they will all execute their logic. Possible fixes off the top of my head:
- Allow sub-inspectors to have `gui_focus`.
- When a property is selected, go to the root inspector and recursively deselect all other properties.

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -579,6 +579,13 @@ void EditorProperty::_notification(int p_what) {
 			}
 		} break;
 		case NOTIFICATION_ENTER_TREE: {
+			// Ensure shortcuts on properties are only triggered in the context of the inspector they are contained within.
+			EditorInspector *inspector = get_parent_inspector();
+			if (inspector) {
+				inspector->get_root_inspector();
```
Comment (KoBeWi) [inline editor/editor_inspector.cpp:585]: This does nothing.

File: scene/main/scene_tree.cpp [hunk 2]
```diff
@@ -1336,13 +1354,27 @@ void SceneTree::_call_input_pause(const StringName &p_group, CallInputType p_cal
...
-		if (p_viewport->is_input_handled()) {
-			break;
+	if (p_call_type == CALL_INPUT_TYPE_SHORTCUT_INPUT && !p_viewport->is_input_handled()) {
+		// These controls did not have a context, therefore may receive shortcut input from anywhere.
+		// Sort them by their priority in handling the shortcut.
+		// Note: We can only make a best-effort attempt to select the node to handle the input first. To customize
+		// shortcut handling and propagation logic more explicitly, the shortcut context should be used.
+		Vector<Pair<Node *, bool>> resolved_nodes_without_context;
+		for (const Pair<ObjectID, bool> &pair : nodes_without_context) {
+			Node *node = Object::cast_to<Node>(ObjectDB::get_instance(pair.first));
```
Comment (KoBeWi) [inline scene/main/scene_tree.cpp:1364]:
```suggestion
			Node *node = ObjectDB::get_instance<Node>(pair.first);
```
(you'll need to rebase to use this)

**Comment by KoBeWi** [comment]
The new algorithm seems to be more complex, involving sorting. I'm a bit worried about performance impact. Although for shortcut input maybe it won't make difference.

File: editor/editor_inspector.cpp (hunk 1 above)
Comment (EricEzaM) [reply editor/editor_inspector.cpp:585]: Ahaha whoops, at the time I didn't realise that getting the root was possible so I thought maybe I needed to loop through parents to get the root. Pretty funny mistake though lol

File: scene/main/scene_tree.cpp [hunk 3]
```diff
@@ -1317,13 +1329,19 @@ void SceneTree::_call_input_pause(const StringName &p_group, CallInputType p_cal
 					// If calling shortcut input on a control, ensure it respects the shortcut context.
 					// Shortcut context (based on focus) only makes sense for controls (UI), so don't need to worry about it for nodes
 					if (c->get_shortcut_context() == nullptr) {
-						no_context_node_ids.append(n->get_instance_id());
+						const bool is_ancestor_of_focused = viewport_focused_control == nullptr
+								? false
+								: c->is_ancestor_of(viewport_focused_control);
```
Comment (AThousandShips) [inline scene/main/scene_tree.cpp:1334]:
```suggestion
						const bool is_ancestor_of_focused = (viewport_focused_control != nullptr) && c->is_ancestor_of(viewport_focused_control);
```

File: editor/editor_inspector.cpp (hunk 1 above)
Comment (EricEzaM) [reply editor/editor_inspector.cpp:585]: Hmm never mind, this did have intention. `get_parent_inspector()` can return `nullptr`. Therefore we need to protect against it returning returning `nullptr` before calling `get_root_inspector()`. There is no way to get the root inspector directly from an `EditorProperty`

Comment (EricEzaM) [reply editor/editor_inspector.cpp]: updated to `inspector = inspector->get_root_inspector();`

**Comment by EricEzaM** [comment]
> The new algorithm seems to be more complex, involving sorting. I'm a bit worried about performance impact. Although for shortcut input maybe it won't make difference.

On my PC, the addition of this sorting makes the processing of such inputs about 5 times slower, 0.05ms -> 0.25ms, on an input which has no effect (e.g. pressing ctrl). This is only triggered when the keyboard/joypad input is not handled by a control directly (which is most 'release' events).

As I said in the OP this is optional. It _may_ make the base case better in _some scenarios_. Honestly it doesn't seem worth it to me. The advice should always be to properly set the shortcut context and try not to have conflicting global shortcuts.

**Comment by KoBeWi** [comment]
If the inspector changes are enough to fix the linked issues, you should split the SceneTree changes into separate PR.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
