### PR TITLE
Fix error when click edge of the tree icon

### LINKED ISSUE #27580: Error when trying to drag visibility button too close to the edge
**Godot version:**
3.2 9c3ddf0

**OS/device including version:**
Linux Mint 19

**Issue description:**
When I drag visibility button in scene tree, too close to the edge then this error is shown:
```
ERROR: _cell_button_pressed: Condition ' !item ' is true.
   At: editor/scene_tree_editor.cpp:52.
```

**Steps to reproduce:**
https://streamable.com/4zaxv

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #27580

This might be a little hack though. The problem is that the method which sets `cache.click_type` and the `get_item_at_position()` use different logic and recognize clicks with different results. The clicked item is then "ensured" here, which might result in nulling a correct click:
https://github.com/godotengine/godot/blob/5f99e3396f8468ab74bff6bc2fe9742f670a054a/scene/gui/tree.cpp#L2611-L2615
If you add another null check in the code I linked above, it results in click having a visual click rectangle and no effect.

The logic of determining click is too convoluted, so I just gave up in fixing the differences and ensured the same result by calling `get_item_at_position()`.

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -1784,13 +1784,22 @@ int Tree::propagate_mouse_event(const Point2i &p_pos, int x_ofs, int y_ofs, bool
 					cache.click_type = Cache::CLICK_NONE;
 					return -1;
 				}
+
+				// Make sure the click is correct.
+				Point2 click_pos = get_global_mouse_position() - get_global_position();
+				if (get_item_at_position(click_pos) == NULL) {
```
Comment (akien-mga) [inline scene/gui/tree.cpp]: I'm concerned about the potential performance impact, `get_item_at_position` sounds pretty heavy handed. But I don't have a better fix to propose for now.

Comment (KoBeWi) [reply scene/gui/tree.cpp]: It's one additional call though, also guarded by multiple other conditions. It's called at the same time as the original one (at the time of a click).

But yeah, unexpected things might happen :I

Comment (akien-mga) [reply scene/gui/tree.cpp:1790]: Side note, should be updated to `nullptr` now.

**Review by akien-mga — APPROVED** [review]
Let's give this a spin :)

**Comment by akien-mga** [comment]
Thanks!
