### PR TITLE
Fix pressing `F3` do both changing to script editor AND find next text

### LINKED ISSUE #17334: When switching to the script editor if an old "find" is active, it jumps to the result
**Godot version:** 3.0.2

**OS/device including version:** Arch Linux

**Issue description:** After executing a search in a script, even when aborting it with Esc, afterwards switching to the script editor will re-execute the search.

**Steps to reproduce:**
* Open a script, preferably more than one screenful.
* Hit Ctrl+F and search for something that appears near the top of the script.
* Hit Esc to stop the search.
* Hit Ctrl+End to move the cursor to the end of the file.
* Hit F1, then F3 to switch to the scene editor and back.

**Expected result:** the cursor is in the location we put it, at the end of the file.

**Actual result:** the cursor moves to the first find result, and the result is highlighted as if we were executing a search, even though the search bar is not visible.

**Workaround:** hit Ctrl+F, Backspace, Esc to clear the search query.

### PR DESCRIPTION
**Pull request by robfram**
Fix pressing `F3` do both changing to script editor AND find next text

As `KEY_F3` was used both for changing to script editor window and, in
the script editor, for finding the next result in the last search, and
the key event is **not** consumed, the resulting behaviour was similar
to press `F3` twice, first to change to script editor and second to
find the next result of a previous search.

This PR sets the `key_pressed` status of `InputEvent` to `false` if
this event is responsible of an editor change, simulating the
consumption of the event.

Fix #17334

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -225,6 +227,10 @@ void EditorNode::_unhandled_input(const Ref<InputEvent> &p_event) {
 				_bottom_panel_switch(false, i);
 			}
 		}
+
+		if (old_editor != editor_plugin_screen) {
+			k->set_pressed(false);
```
Comment (akien-mga) [inline editor/editor_node.cpp]: Wouldn't it work with `get_tree()->set_input_as_handled();`? That would be cleaner.

Comment (akien-mga) [reply editor/editor_node.cpp]: Or @hpvb mentioned `accept_event()`. Not sure which would work, if any.

Comment (hpvb) [reply editor/editor_node.cpp]: accept_event() won't work here as EditorNode is not a control :-/

**Comment by akien-mga** [comment]
Thanks!

**Comment by hpvb** [comment]
Cherry picked into 3.0.3
