### PR TITLE
PO loader: Fix unclosed files and error messages

### LINKED ISSUE #40324: Godot doesn't free file lock when loading .po fails
**Godot version:**

3cbf4971b

**Steps to reproduce:**
1. Open a project with a .po translation file
2. Edit the file while the project is opened and make some error (e.g. remove single quotation mark)
3. Run the game and close
4. Try to change the file and save
5. You can't, because the file is locked

**Minimal reproduction project:**

[ReproductionProject.zip](https://github.com/godotengine/godot/files/4909395/ReproductionProject.zip)

### PR DESCRIPTION
**Pull request by akien-mga**
Trying to get `f->get_path()` after deleting `f` was not super clever :)

Fixes #40324.

### CODE REVIEW

File: core/io/translation_loader_po.cpp [hunk 1]
```diff
@@ -147,7 +150,6 @@ RES TranslationLoaderPO::load_translation(FileAccess *f, Error *r_error) {
 		line++;
 	}
 
-	f->close();
```
Comment (akien-mga) [inline core/io/translation_loader_po.cpp:150]: `close()` already happens in the destructor for all `FileAccess` types.

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.
