### PR TITLE
[Complex Text Layouts] Refactor `String` to use UTF-32 encoding.

### LINKED ISSUE #23093: Most emojis don't work on Windows
**Godot version:**

Godot 3.1 master https://github.com/godotengine/godot/commit/0d8284d3d4f439e074bf498af81e8c73be23cc67

**OS/device including version:**

Window 10

**Issue description:**

In theory, emoji support was added with this PR https://github.com/godotengine/godot/pull/15780 but I've been testing it and I can't get it to work. I tested it with  the NotoColorEmoji.ttf font. That's the font I think @volzhs used for both that PR and this issue https://github.com/godotengine/godot/issues/10873 but I couldn't make it work. The font doesn't work on windows (opening it with the font viewer throws an error) because Windows doesn't support the type of color font https://github.com/googlei18n/noto-emoji/issues/43 But I'm not sure if it has anything to do with the issue.

**Steps to reproduce:**
1. Download the font https://www.google.com/get/noto/#emoji-zsye-color
2. Use it in a label with an emoji like 😄

### LINKED ISSUE #25620: Pasting an emoji in code creates an invisible error (Parse Error: Unknown character)
**Godot version:**
3.1 beta 3

**OS/device including version:**
Windows 10

**Issue description:**
When you paste an emoji in the code editor, it looks like it didn't accept the symbol  because no character is shown. But it's there so it throws an unkown character error. It won't happen to people often but if it does happen, it could keep people clueless of what the problem is because you don't see anything wrong.

**Steps to reproduce:**
Paste an emoji in the code editor

### LINKED ISSUE #41159: String.repeat and format error
**Godot version:** 3.2
**OS/device including version:** Mac OSX GLE3

**Issue description:**
Found a very strange bug that looks like a pointer into memory going awry. String.repeat used to create a format string results in random unwanted chars.

```
tool
extends EditorScript

func _run():
	var repeats = "%s".repeat(3) % ['a','b','c']
	assert(repeats == 'abc', repeats)
```

Fails and produces:
```
 <built-in>:6 - Assertion failed: abcX
 <built-in>:6 - Assertion failed: abcX
 <built-in>:6 - Assertion failed: abc@
 <built-in>:6 - Assertion failed: abc)/=
)/=H
 <built-in>:6 - Assertion failed: abc5
 <built-in>:6 - Assertion failed: abc
 <built-in>:6 - Assertion failed: ab
```

### PR DESCRIPTION
**Pull request by bruvzg**
Part of https://github.com/godotengine/godot-proposals/issues/1180 implementation.

- Change `String` to use UTF-32 encoding on all platforms. ✔️
- Add UTF-16 encode / decode functions. ✔️
- Cleanup and update gdnative wrappers for string (remove duplicate compatibility functions, add missing). ✔️
  - Add UTF-16 string wrapper.
  - Add string constructors from ASCII/Latin-1, UTF-8, UTF-16, UTF-32 data.
  - Add few missing functions to GDNative and GDScript.
  - Remove redundant `int` / `int64` functions (all inst are 64-bit).
  - Change inconsistent by value (`godot_string`) arguments to `const godot_string *`.
  - Change `godot_array` returns/arguments to `godot_packed_?_array` to match GDScript and avoid unnecessary conversion.
- Add missing units tests for `String` and string gdnative wrapper. ✔️
- Update documentation. ✔️

Fixes: #23093, fixes #25620

*Bugsquad edit:* Incidentally fixes #41159.

### CODE REVIEW

**Comment by aaronfranke** [comment]
Why UTF-32? You can store all Unicode characters in UTF-8, and the maximum encoding length for any Unicode character is 4 characters. Therefore UTF-8 can only ever be smaller or equal to UTF-32 in size, and has the same feature set.

**Comment by bruvzg** [comment]
> Why UTF-32? You can store all Unicode characters in UTF-8, and the maximum UTF-8 encoding length for any Unicode character is 4 bytes. Therefore UTF-8 can only ever be smaller or equal to UTF-32 in size, and has the same feature set.

UTF-8 is extremely incontinent to use for anything but storage (and all Godot files are stored in UTF-8 anyway), for example something like `substr(from, len)`:
- With UTF-32 is just check boundaries and copy part of array.
- With UTF-8 you need to be sure it's cutting whole characters, you have to decode at least substring porting (in case `from` and `len` are byte offsets which is incontinent for end users), or full string (in case `from` and `len` are character offsets), same for any function mutating the string or reading characters from the string.

File: core/ustring.cpp [hunk 1]
```diff
@@ -96,37 +96,95 @@ bool select_word(const String &p_s, int p_col, int &r_beg, int &r_end) {
...
+
+void Char16String::copy_from(const char16_t *p_cstr) {
+	if (!p_cstr) {
+		resize(0);
+		return;
+	}
+
+	const char16_t *s = p_cstr;
+	for (; *s; s++) {
+	};
```
Comment (akien-mga) [inline core/ustring.cpp:140]: Seems to be an unnecessary semicolon?

File: core/ustring.cpp [hunk 2]
```diff
@@ -190,55 +286,117 @@ void String::copy_from(const CharType *p_cstr, const int p_clip_to) {
...
-	for (int i = 0; i < p_length; i++) {
-		dst[i] = p_char[i];
+	for (int i = 0; i < len; i++) {
+		dst[i] = p_cstr[i];
 	}
+	dst[len] = 0;
+}
+
+void String::copy_from(const wchar_t *p_cstr) {
+#ifdef WINDOWS_ENABLED
```
Comment (akien-mga) [inline core/ustring.cpp:300]: How is it on UWP?

Comment (bruvzg) [reply core/ustring.cpp:300]: UWP have `WINDOWS_ENABLED` defined.

File: core/ustring.cpp (hunk 1 above)
Comment (bruvzg) [reply core/ustring.cpp:140]: Yep, if was `for (; *s; s++);` and clang-format added `{}`.

Comment (akien-mga) [reply core/ustring.cpp:140]: Ah yeah I got that too when formatting. Then I usually change it to `for (; *s; s++) {}` which I think `clang-format` might be happy with.
But it's no big deal and doesn't warrant an amend just for this anyway.

**Comment by akien-mga** [comment]
I reviewed the changes in `core/`, it seems pretty good to me. But @reduz should have a glance at the new API to confirm that it's how he'd want it.

File: core/ustring.h [hunk 3]
```diff
@@ -404,6 +496,16 @@ _FORCE_INLINE_ bool is_str_less(const L *l_ptr, const R *r_ptr) {
 	}
 }
 
+#ifdef WINDOWS_ENABLED
+// wchar_t is 16-bit
+#define FROM_WCSTR(m_value, m_len) (String::utf16((const char16_t *)(m_value), (m_len)))
+#define TO_WCSTR(m_value) ((const wchar_t *)((m_value).utf16().get_data()))
```
Comment (reduz) [inline core/ustring.h:502]: I think this can be a method in String, including the ifdef, no need to make a macro

Comment (bruvzg) [reply core/ustring.h:502]: Simply moving `TO_WCSTR` code to the method will cause `heap-use-after-free` crash, since `Char16String` created by `utf16()` will be freed on exiting function and its data pointer will be invalid. With the macros it will live long enough.

`FROM_WCSTR` is just for symmetry, not used anywhere and can be safely removed.

I can replace all the Windows API calls with `x.utf16().get_data()` (on Windows it's always UTF-16), and debug prints with `x.utf8().get_data()` and `%s` instead of `%ls`, to avoid macros.

Comment (bruvzg) [reply core/ustring.h:502]: Actually I already did `utf16().get_data()` for Windows APIs, it's only used for debug `printfs` (and half of them are commented), so I'll just replace it with `utf8` and remove the macros.

**Comment by akien-mga** [comment]
Thanks for the awesome work!
